### ISSUE TITLE
Default font-family in Editor has changed for multiple WPCOM themes (where `font-family` is not defined in Editor styles)

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#51257]
This is a stub issue for us to gather more information. It appears recent changes to the default Gutenberg editor styles have meant that the appearance of text in the Editor may change for users depending on:

* Whether the theme provides a editor-styles stylesheet
* Whether the Editor Styles define a default `font-family`

This change is potentially disruptive to our customers - making it harder to edit content.
As this is across multiple themes and situations - I'm starting this issue for us to track it.

See Slack conversation here:
p1616175586038800-slack-CBTN58FTJ

### Steps to reproduce the behavior

1. Use the 'Nucleare' theme on a Simple Site
2. Edit content in the editor - particularly noting the lack of difference between paragraph text and quote blocks.

#### Is this specific to the applied theme? Which one?

So far it appears to effect:

* Nucleare
* Old P2
* Lovecraft

#### Does this happen on simple or atomic sites or both?

Unclear at this stage

#### Level of impact 

Low at this stage - but unclear a we don't know how many themes this is effecting.

#### Screenshot / Video: 

https://d.pr/v/SQPe88

**Comment by jordesign** [comment]
Unsure if this is a dupe of https://github.com/Automattic/themes/issues/3280 ?

@scruffian @simison

**Comment by simison** [comment]
Seems duplicative to me but I'll let Themers decide. :-)

**Comment by scruffian** [comment]
It could be caused by https://github.com/WordPress/gutenberg/pull/30080, but I'm happy to close in favour of https://github.com/Automattic/themes/issues/3280
