### ISSUE TITLE
Nav Unification: Force Posts and Pages to WP Admin on Atomic

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#51283]
**What**

Force Posts and Pages to link to WP Admin on Atomic sites

**Why**

Please find the context to this change here: pbAPfg-1sT-p2
And the decision to this change here: pbAPfg-1sT-p2#comment-2895

**Acceptance criteria**

* Should a site be Atomic the links for menu items Posts and Pages should link to WP Admin regardless of the Advanced Dashboard menu toggle

**Comment by getdave** [comment]
Reopen as we are waiting for the JP release to declare this fully "Done". However, the fix should now be in place on Atomic.
