### ISSUE TITLE
Payments Block Setup Not Visible At Narrow Widths (like in Columns)

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#51287]
When adding Payments blocks inside columns, the block settings indicate a plan is selected, but the block is still asking for the user to click on the plan in the block itself.

The options to select the plan are not visible in the block when it is narrow, like in a column.

### Steps to reproduce the behavior

1. Add a columns block with three columns
2. Add a Payments block in one column
3. Check that a plan is selected in the block settings in the sidebar
4. View live site. 

#### What I expected to happen

For the Payments block to be visible on the live site.

#### What actually happened

The block isn't visible on the live site b/c it's not completely setup, but there's no way to see that in the editor.

Column View:
<img width="782" alt="PaymentsNarrow" src="https://user-images.githubusercontent.com/42279181/112046915-3a606480-8b12-11eb-9dee-b1d6169b54b8.png">

Same block moved to full-width view:
<img width="773" alt="paymentswide" src="https://user-images.githubusercontent.com/42279181/112046956-43e9cc80-8b12-11eb-9835-325e607985dc.png">

User report in 28577750-hc

**Comment by kosiew** [comment]
Closed.

Similar to https://github.com/Automattic/wp-calypso/issues/40493
