### ISSUE TITLE
Theme Showcase: Remove Nessie image

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51290]
When no themes are found we should not be showing this Nessie illustration. We removed most of these a few years ago, iirc. It appears this one has stuck around. :)

![image](https://user-images.githubusercontent.com/545779/112065340-81f6e880-8b32-11eb-836c-58a068956643.png)

**Comment by kwight** [comment]
@blackjackkent this might be a good @andres-blanco issue. 👍

**Comment by youbrokesomething** [comment]
Confirmed this issue was fixed.
