### ISSUE TITLE
CoBlocks: Placeholder text within CoBlocks are not localizing when UI language is changed.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#51294]
### Steps to reproduce the behavior

This is an offshoot of the issue first reported at #37543. That issue dealt with localization of the help text, which remained in English despite UI language being changed.

This issue is for the text block placeholder text which are blocks embedded within the CoBlocks.

1. Start a new post.
2. Insert a selection of CoBlocks (eg. Hero block)
3. Save post as draft.
4. From `/me`, change the UI language (eg. Japanese)
5. return to the post. 

#### What I expected to happen
Placeholder text within the CoBlocks are localized.

#### What actually happened
Placeholder text within the CoBlocks are not localized and remain displayed in English.

### Context
Reproducing the issue #37543 .

#### Browser / OS version
OS: macOS Big Sur 11.1 (20C69)
Browser: Firefox Nightly 88.0a1 (2021-03-22) (64-bit)

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Tested on Simple only.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - but annoying to users that do not use English.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot 2021-03-22 at 5 08 41 PM](https://user-images.githubusercontent.com/6549265/112073405-44de2680-8b31-11eb-93eb-a292de4dca08.png)

**Comment by WunderBart** [comment]
I can see CoBlocks' blocks localized when changing the language to Polish. Maybe there's a translation missing for the Japanese pack (which would mean it's not a bug)? Could you confirm that, @worldomonation?

**Comment by worldomonation** [comment]
Looks to be resolved now for Japanese at least - checked all coblocks.
