### ISSUE TITLE
Block editor settings sidebar collapsed by default leads to lack of feature knowledge

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#51312]
**What**
I believe the setting sidebar in the block editor shouldn't be collapsed by default or at least should be highlighted somehow - as a new user I have no indication that this exists or even contains additional block settings.

**Why**
Running a test as a brand new user who purchases an eCommerce plan I decided to try and add a post. This was easy enough - I added a few paragraphs and a more block and an image but now I have these blocks and the settings sidebar is collapsed by default. 

![Markup on 2021-03-23 at 15:14:00](https://user-images.githubusercontent.com/22053773/112151910-69e2a000-8bea-11eb-9593-f318ee4d977d.png)

As a new user I have no experience of the editor so I don't know I have additional image or other block controls in the sidebar.

Many useful controls exist in the toolbar above the block but unless I happen to click the settings cog icon I will not know to check that and it's pure chance for me to notice I can actually do more with blocks than this.

**Additional context**
Came up during team empathy testing - p7DVsv-aWu-p2

**Comment by zdenys** [comment]
Definitely! I encountered this today in 28593742-hc.

**Comment by zdenys** [comment]
I was reviewing various bugs I commented on and stumbled upon this one. The issue was addressed by https://github.com/Automattic/wp-calypso/issues/53383 so I will close this one. Feel free to reopen if it makes sense.
