### ISSUE TITLE
Create "Domain Picker stability" milestone

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#51318]
## What

Create a milestone to group =folder structure refactor, semantics rewrite, unit and integration tests issues

## Why

Helps visualise it as a overall goal

## A/C

- [x] Create milestone
- [x] Add all issues (completed and open)

**Comment by ciampo** [comment]
@Automattic/luna since there's no PR associated to this issue, I thought we could review directly here.

I created the milestone and added all the domain-picker-related issues:  https://github.com/Automattic/wp-calypso/milestone/349

**Comment by razvanpapadopol** [comment]
I think all the related issues are now included in the milestone. I've also took out some bugs and moved over to a new milestone, [Domain picker: Bug Backlog](https://github.com/Automattic/wp-calypso/milestone/352 ), where we'll keep track of missing features, bugs, a11y issues and design misalignment:
