### ISSUE TITLE
Launch: Coming Soon label in sidebar takes seconds to full minute to disappear

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51322]
### Screenshot

![image](https://user-images.githubusercontent.com/545779/112175416-39d4d600-8bc5-11eb-9544-9aeb185ad0a1.png)

### Steps to reproduce the behavior

1. Create a new site
2. Launch site
3. Observe how long it takes for the label to disappear from the sidebar

**Note:** Tested using my typical a12n account setup.

**Comment by youbrokesomething** [comment]
I can't reproduce this issue at this time. Please reopen if needed.
