### ISSUE TITLE
Plugins: WooCommerce onboarding does not launch after installation

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51327]
### Steps to reproduce the behavior

1. Go to plugins screen in Calypso
2. Install WooCommerce

#### What I expected to happen

One of the following options

1. That I be directed automatically to the WooCommerce Onboarding flow similar to actions in the Ecommerce Plan on WP.com or when installing Woo on a self-hosted site.
2. That I am offered direction via the UI on how to get to the Onboarding flow.

#### What actually happened

I was left on this screen after installation.

![image](https://user-images.githubusercontent.com/545779/112178653-ee6ff700-8bc7-11eb-957e-a92a706b323f.png)

**Comment by ianstewart** [comment]
For comparison here's some different experiences offered …

Dotcom after installing the WooCommerce Plugin:

![image](https://user-images.githubusercontent.com/545779/115072163-d6388280-9ebc-11eb-8296-73deffe3da6c.png)

Dotcom after upgrading to the Ecommerce Plan (which activates Woo):

![image](https://user-images.githubusercontent.com/545779/115072297-04b65d80-9ebd-11eb-9ae2-5f690d53c6db.png)

Core WordPress:

![image](https://user-images.githubusercontent.com/545779/115072359-1d267800-9ebd-11eb-8584-1a8d7b553ea0.png)

**Recommendation:**

- Woo is a complex plugin with a complex setup.
- Recommend we start running the WooCommerce Onboarding Flow to match the Core and Ecommerce Plan experience when a user installs WooCommerce on WordPress.com.

**Comment by retrofox** [comment]
Are we agree that

* The ability to add the WooCommerce plugin (or whatever actually) for non Jetpack sites is only possible **ONCE**, for Simple sites? Once the plugin is added, the site becomes an Atomic site, and the plugins page will be handled by wp-admin. 
* For Jetpack sites, it's possible to keep installing/uninstalling plugins from the calypso app.

**Comment by retrofox** [comment]
> That I am offered direction via the UI on how to get to the Onboarding flow.

Could you provide a simple UI design for this purpose? I mean how we should do this?

**Comment by olaolusoga** [comment]
>Could you provide a simple UI design for this purpose? I mean how we should do this?

Does this answer the question, @retrofox ?

`Recommend we start running the WooCommerce Onboarding Flow to match the Core and Ecommerce Plan experience when a user installs WooCommerce on WordPress.com.`

**Comment by retrofox** [comment]
with _WooCommerce Onboarding Flow_ we mean to the wp-admin wizard page, or it refers to another onboarding?

**Comment by ianstewart** [comment]
![image](https://user-images.githubusercontent.com/545779/117499186-7a539d80-af40-11eb-8949-cf6d7966bff0.png)

This thing. I think (from the URL) it's the "Setup Wizard"? Looks like it runs in /wp-admin.
