### ISSUE TITLE
Plugins: Search results for "ecom" and "ecommerc" do not surface WooCommerce

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51326]
### Steps to reproduce the behavior

1. Go to plugins screen in calypso
2. Search for `ecom` or `ecommerce`

#### What I expected to happen

For WooCommerce and any other non-extension `ecommerce` plugins to be surfaced in search results as I typed.

#### What actually happened

No WooCommerce.

![image](https://user-images.githubusercontent.com/545779/112178164-90dbaa80-8bc7-11eb-9c1f-d4d3b8d0cf45.png)

**Comment by allilevine** [comment]
Typing "ecommerce" and pressing enter in the Marketplace now surfaces WooCommerce:

<img width="1107" alt="Screen Shot 2022-04-19 at 12 27 17 PM" src="https://user-images.githubusercontent.com/1689238/164051124-9bc25525-4c44-42ed-86cd-a857c4828ae8.png">
