### ISSUE TITLE
Nav Unification: Jetpack Security settings are duplicated for Atomic Sites

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#51340]
### Steps to reproduce the behavior

1. Using a WoA site, navigate to Jetpack > Settings > Security
2. For the same site, in a new tab, navigate to My Site > Settings > Security
3. Note the available options on each screen. "Downtime monitoring," "WordPress.com log in," and "Prevent brute force login attacks" are all present on both menus

#### What I expected to happen
These options to exist on a single screen, without duplication

#### What actually happened
They're presented in two different places within unified dashboard/navigation

### Context
Prior to Nav unification, these settings existed in two places, but were more separate, so it made a certain amount of sense. With Nav Unification active, having these settings duplicated can be confusing for site owners.

**Comment by mmtr** [comment]
This should've been fixed as of https://github.com/Automattic/jetpack/pull/20088
