### ISSUE TITLE
Nav Unification: Jetpack Performance settings are duplicated for Atomic sites

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#51342]
**Steps to reproduce the behavior**
1. Using a WoA site, navigate to Jetpack > Settings > Performance
2. For the same site, in a new tab, navigate to My Site > Settings > Performance
3. Note the available options on each screen. "Search/Jetpack Search" and "Performance & Speed" sections are shown on both screens

**What I expected to happen**
These options to exist on a single screen, without duplication

**What actually happened**
They're presented in two different places within unified dashboard/navigation

**Context**
Prior to Nav unification, these settings existed in two places, but were more separate, so it made a certain amount of sense. With Nav Unification active, having these settings duplicated can be confusing for site owners.

**Comment by mmtr** [comment]
I wonder if this could be solved by hiding the Jetpack > Settings submenu. That way we'd keep the menu consistent with Simple sites.

**Comment by mmtr** [comment]
> I wonder if this could be solved by hiding the Jetpack > Settings submenu. That way we'd keep the menu consistent with Simple sites.

I explored this and seems doable. Most of the settings that can be managed on "Jetpack > Settings", can be also managed on other Calypso screens as per the table below:

Jetpack screen | Calypso screen
--- | ---
Jetpack > Settings > Security | Settings > General > Security
Jetpack > Settings > Performance | Settings > General > Performance
Jetpack > Settings > Writing | Settings > General > Writing
Jetpack > Settings > Sharing > Publicize | Tools > Marketing > Connections
Jetpack > Settings > Sharing > Sharing | Tools > Marketing > Sharing buttons
Jetpack > Settings > Sharing > Like | Tools > Marketing > Sharing buttons > Show like button
Jetpack > Settings > Discussion | Settings > General > Discussion
Jetpack > Settings > Traffic | Tools > Marketing > Traffic
Jetpack > Settings > Traffic > Ads | Tools > Earn > View ad dashboard > Settings
