### ISSUE TITLE
Nav Unification: Writing Settings are duplicated for Atomic sites

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#51346]
**Steps to reproduce the behavior**
1. Using a WoA site, navigate to Jetpack > Settings > Writing
2. For the same site, in a new tab, navigate to My Site > Settings > Writing
3. Note the available options on each screen. Many are duplicated, sometimes with different options provided:

- "Media" exists on both screens, but in Jetpack has an additional option to display comments in the carousel
- In "Composing," "Compose using shortcodes to embed media from popular sites" and the option to enable LaTex formatting is present on both screens.
- Jetpack's "Custom Content Types" and the general setting's "Content Types" provide duplicate settings, but Jetpack lacks the option to set the posts per page count for each content type.
- "Theme Enhancements" section duplicates, with additional "Infinite Scroll" options being shown in General Settings that are not present in Jetpack Settings
- "Widgets" section is present on both screens
- "Publishing Tools" and "Post by Email" are two different names for identical settings on the two screens. The wording of the button to set up an email address for new site owners to email posts to (Create address vs Regenerate address) is also different. Using "create" for the first time this is set up, and then "regenerate" going forward would probably be the least confusing.

**What I expected to happen**
These options to exist on a single screen, without duplication. If duplication can't be avoided, the options provided should be consistent.

**What actually happened**
They're presented in two different places within unified dashboard/navigation

**Context**
Prior to Nav unification, these settings existed in two places, but were more separate, so it made a certain amount of sense. With Nav Unification active, having these settings duplicated can be confusing for site owners.

For cases where the options are different between the two screens, site owners could be very confused as to why the setting isn't with other related settings, especially if they've seen a particular option on a different menu in the past, but don't realize they're on a similar but different options panel.

**Comment by obenland** [comment]
@jeherve What are our options here? Is it possible to remove the `Settings` menu item without breaking too much stuff for Jetpack?

Also #51342 and #51340.

**Comment by jeherve** [comment]
> What are our options here? Is it possible to remove the Settings menu item without breaking too much stuff for Jetpack?

I believe we would need to add additional options to Jetpack > Settings > Writing in wp-admin before we can remove Settings > Writing in Calypso.

On other sub-screens of the Settings page in Calypso, we have similar problems: there are things that are only available in Calypso and that would need to be made available in wp-admin before we remove the whole Settings screen from Calypso. For example:

- The space indicator next to the Video setting.
- The whole connection sub-screen, available at the bottom of the main settings screen.

**Comment by obenland** [comment]
What about removing Jetpack > Settings in favor of Calypso settings screens?

**Comment by jeherve** [comment]
> What about removing Jetpack > Settings in favor of Calypso settings screens?

This may work for the Calypso settings screens that live under Jetpack > Settings, but won't work for the Calypso settings screens that live under Settings in wp-admin, such as Calypso > Settings > General that is equivalent to Settings > General in wp-admin.

**Comment by mmtr** [comment]
This should've been fixed of https://github.com/Automattic/jetpack/pull/20088.
