### ISSUE TITLE
Nav Unification: Jetpack Search odd flow/ lost focus in navigation

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#51345]
If I have Jetpack Search and click "Settings" while in My Site > Jetpack > Search, it takes me to a Settings screen that should show as My Site > Settings on the navigation on the left - but it looks like I am nowhere in navigation:

<img width="1058" alt="Screen Shot 2021-03-23 at 14 19 57" src="https://user-images.githubusercontent.com/31009008/112202235-84ffe080-8be7-11eb-8d68-25579b4fad84.png">

### Steps to reproduce the behavior

On an atomic site, enable Jetpack search product.

1. Go to Jetpack > Search
2. Click on Settings

#### What I expected to happen

To remain inside Jetpack as I am taken to Settings, in the navigation on the left.

#### What actually happened

The Jetpack panel remains open on the left navigation, but I am now in Settings, and this is not focused in the navigation.

**Comment by cpapazoglou** [comment]
@davipontesblog can you confirm this is still happening? I can't reproduce it..

**Comment by davipontesblog** [comment]
Not happening anymore, I do see the focused item "Settings" in the nav. Thanks for checking!
