### ISSUE TITLE
Featured Images Next to Posts Missing

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#51357]
* Go to My Site>Posts>All Posts 
* Note that one can see:

![screenshot](https://d.pr/i/2wDjXI+)

But there are no Featured Images. An example of a site where the old navigation menu exists shows featured images:

![screenshot](https://d.pr/i/DMJPvF+)

I'm not totally sure if this is a bug or Feature Request.

The issue was brought to light in #28602207-hc

**Comment by tjcafferkey** [comment]
Hey @ChrissiePollock if you are viewing your posts on a Simple site you should get the Calypso view which does indeed have featured images.

For Atomic sites if you go to Posts > All Posts you get the WP Admin screen which doesn't include this view. This was introduced as part of https://github.com/Automattic/wp-calypso/issues/51283.

In order for us to show featured images in the all posts view on Atomic sites we would need to update core to have this behaviour I believe.

**Comment by ChrissiePollock** [comment]
Thanks. It was Atomic.

**Comment by dsas** [comment]
This was resolved in November, see p7DVsv-dfi-p2

![image](https://user-images.githubusercontent.com/93301/162488842-ef12cf08-2d53-4f8c-bf2b-23dee69e60e3.png)
