### ISSUE TITLE
Atomic: 'My Site' link does not redirect the user to the AT site home page

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#51367]
### Steps to reproduce the behavior

1. Go to an AT site and click on a WP-Admin page (e.g. Posts > Categories).
2. Click on 'My Site' link.

#### What I expected to happen
The user should be redirected to https://wordpress.com/sites/site_name.wpcomstaging.com

#### What actually happened
The user remains on the same page

#### Browser / OS version
Chrome 89.0.4389.90 / MacOS
#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Atomic

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
The user cannot switch the site or visit the main page.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screenshot 2021-03-24 at 13 02 56](https://user-images.githubusercontent.com/995955/112300371-71b14b80-8ca1-11eb-9504-9e8598982251.png)

**Comment by cpapazoglou** [comment]
Actually this is expected. "My Site" means that you are in the "My Sites" section which shows the sidebar of that site. On the same note, it doesn't redirect to any page if you were already on Calypso eg "Media" screen. It will redirect if you are on "Reader" or "Me" though.
