### ISSUE TITLE
Choose a Domain: grayed out search field doesn't encourage searching for URLs

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#51368]
When using the new onboarding, it's not super clear how one could change the list of suggested URLs under the  **Choose a Domain** page. The grayed-out field feels like a sub-heading or even an input field on a disabled state.

### Steps to reproduce the behavior

1. Go to https://wordpress.com/new/
2. Type your site title. In my case, _I am Testing_
3. Get to the **Choose a Domain**  page

#### What I expected to happen

* To quickly spot a way to change the domain suggestions.
* Perhaps a more prominent input field that drives my attention to it
* Show a proper URL instead of the site title in the search field. There is a similar discussion on #32514

#### What actually happened

While I do see a list of domain suggestions, it's not clear to me how can I change that list. It took me at least 30 seconds to understand that the grayed-out field with _I am Testing_ was available to me.

To me, it feels like it was some sort of a sub-heading called _I am Testing_.

### Context
Empathy Flow Testing p7DVsv-aWu-p2

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Not sure.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot on 2021-03-24 at 10:23:15](https://user-images.githubusercontent.com/1136160/112317590-f93f9000-8c8a-11eb-9c17-30889f6650ba.png)

**Comment by ollierozdarz** [comment]
@razvanpapadopol do we have a different default `input` state available which isn't the grey background? 

I believe in the past we tried having this input focused by default (or at least there was discussion about it) for when the user enters the page. This could be an option to consider, but the only non-ideal consequence is on mobile it would activate the keyboard which blocks the majority of the content.

A happy medium might be to just apply a more active looking style to the input so it doesn't look disabled. This is what we've proposed for the [refined reskin](https://www.figma.com/file/gnYBUOBthTMckJRJr3pZmk/Control-Experiments?node-id=1114%3A536):

<img width="1505" alt="Screen Shot 2021-04-06 at 9 27 18 am" src="https://user-images.githubusercontent.com/67085494/113638773-fac17d00-96ba-11eb-85fb-b22edbbb6dc8.png">
