### ISSUE TITLE
Welcome Guide: welcome guide opens automatically after atomic transfer, even for existing users who have already dismissed it

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#51362]
### Steps to reproduce the behavior

1. Created a site via [wp.com/new](wp.com/new) using an existing account
2. Visited homepage in editor, saw no welcome guide (which is expected, the guide's been dismissed by this account long ago)
3. Upgraded to Business Plan
4. Installed WooCommerce plugin
5. Visited homepage in editor ...

#### What I expected to happen

Shouldn't see the welcome guide, we're not a new user

#### What actually happened

The wpcom welcome guide opens automatically as if you're a new user.

This thing:
<img width="428" alt="Screenshot 2021-03-24 at 10 20 14 AM" src="https://user-images.githubusercontent.com/1500769/112256287-71787680-8cc8-11eb-843e-33e83a14076c.png">

### Context
p1616516330003900-slack-CRNF6A9DX

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low impact. Could annoy users who have just switched to atomic (there could also be a portion of users who find the welcome guide a useful refresher 🤷)

#### Investigation

The decision about whether to show the welcome guide is made here on the backend: https://github.com/Automattic/wp-calypso/blob/0f3d16387a815b48f9e11433f60494143d02c7d7/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-nux-status-controller.php#L71
The editor remembers the response in `localStorage` so it doesn't have to make this API request every time the editor opens.

If it's a simple site then the `wpcom_block_editor_nux_get_status` filter will be present and it will be used to determine whether to show it or not. However the `wpcom_block_editor_nux_get_status` filter doesn't exist on atomic so it falls back to checking the `wpcom_block_editor_nux_status` user meta value.

When the user dismisses the guide we do update the user meta value https://github.com/Automattic/wp-calypso/blob/0f3d16387a815b48f9e11433f60494143d02c7d7/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-nux-status-controller.php#L110
However there are two issues with that:
1. If the user never dismisses the guide before doing an atomic transfer, then `wpcom_block_editor_nux_status` will never get set (it's not initialised anywhere, it depends on the user dismissing the guide)
2. The `wpcom_block_editor_nux_status` user meta value is not even copied to atomic during transfer.

So atomic sites have their own independent flag for showing the welcome guide (which I suppose is understandable given they're stand alone sites), and that flag isn't being initialised during transfer to match the user's current setting in wpcom (I think this is the most unexpected part).

**Comment by dsas** [comment]
If it's just a case of setting `wpcom_block_editor_nux_status` when a site is atomised, then it should _probably_ be a case of adding that to the array in `av2_usermeta_key_whitelist` in wpcoms wp-content/lib/atomic-v2.php 

Will need to follow PCYsg-3Ri-p2 for testing async jobs.

**Comment by cpapazoglou** [comment]
Thanks @dsas for exploring this! You are right, D64726-code adds `wpcom_block_editor_nux_status` in the `av2_usermeta_key_whitelist`

**Comment by cpapazoglou** [comment]
Deployed r229405-wpcom

Tested the following:

**Creating directly an eCommerce (Atomic) site** 
✅ Going to the editor shows the Welcome Guide
✅ I can dismiss the Welcome Guide
✅ Refreshing the page doesn't show the Welcome Guide again
✅  Creating a new post doesn't show the Welcome Guide again

**Transferring a Simple site to Atomic with editor dismissed** 
✅ Going to the editor doesn't show the Welcome Guide
