### ISSUE TITLE
Ability to see CSS revisions (Atomic)

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#51366]
### Steps to reproduce the behavior

1. On an Atomic site head over to Appearance > Customizer
2. Open "Additional CSS" panel. If this is your first time adding CSS here you will need to add some, save and refresh to enable the "CSS Revisions".

#### What I expected to happen
At step 2, CSS Revisions should be visible

#### What actually happened
CSS Revisions is missing

`wp-admin/themes.php?page=editcss` does not work either, it yields
`Sorry, you are not allowed to access this page.`

**Comment by tjcafferkey** [comment]
This has been fixed. You can access revisions via the Customizer. See screenshot below.

![Screenshot 2021-04-06 at 09 48 33](https://user-images.githubusercontent.com/8639742/113685088-cbf8d600-96bd-11eb-9875-104480da3491.png)

**Comment by cpapazoglou** [comment]
Also,  while `wp-admin/themes.php?page=editcss` doesn't work, there is an Appearance -> Edit CSS which redirects you to the Customizer Additional CSS.
