### ISSUE TITLE
Jetpack Plugins: "Plugin doesn't exits in the plugin repo."

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#5138]
#### To repro
1. Connect at least two Jetpack sites with Manage enabled.
2. Using wp-admin, install and enable Hello Dolly (or any other plugin) on *one* of the sites.
3. Go here: https://wordpress.com/plugins/hello-dolly
4. Click the Install button for the site without Hello Dolly installed.

Interestingly, if the plugin is not yet installed on *either* site, you can install it on either one just fine. But once it's installed on one (doesn't matter which), you won't be able to install it on the others; you just get the error instead.

#### What I expected

The plugin to be installed.

#### What happened instead

An error: 

![screen shot 2016-04-30 at 10 49 08 am](https://cloud.githubusercontent.com/assets/5512652/14936694/2fea95a2-0ec1-11e6-8b70-5830dcbfc24d.png)

#### Browser / OS version

Mac 'n Chrome, latest everything.

2642239-t

**Comment by aheckler** [comment]
Could also fix some typos while we're at it:

https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=exits

**Comment by lancewillett** [comment]
Good find, and good catch on the typos. 👍

**Comment by sahin** [comment]
+1 any update?
