### ISSUE TITLE
Atomic / Nav Unification: Jetpack Stats page inaccessible

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#51381]
On some Atomic sites, `/wp-admin/admin.php?page=stats` is inaccessible and returns a 403 with the following message.

`Sorry, you are not allowed to access this page.`

![Screen Shot on 2021-03-24 at 19:27:43](https://user-images.githubusercontent.com/4887830/112396704-084c2f80-8cd7-11eb-8f07-71673c9c9f68.png)

Visiting the page with `/wp-admin/admin.php?page=stats&disable-nav-unification` appended allows it to be visited; however, the page does not load properly.

![image](https://user-images.githubusercontent.com/4887830/112397007-9aecce80-8cd7-11eb-909a-3e3511b83b88.png)

A POST to `SITE/wp-admin/admin.php?page=stats&noheader&chart=flot-stats-data` returns a 403.

---

To double-check things, I disabled nav unification by using the following code snippet that disables the WPCOM admin bar -- essentially disabling nav unification on an Atomic site beyond the URL workaround.

***Note, after review, let's not use this as a workaround as this breaks a lot of important parts of nav unification and breaks the WPCOM/Calypso side of things.  Please do not use as a workaround.  It can be used to verify nav unification is the cause.***

```
function disable_wpcomtoolbar ( $modules ) {
  if ( isset( $modules['masterbar'] ) ) {
    unset( $modules['masterbar'] );
  }
  return $modules;
}
add_filter( 'jetpack_get_available_modules', 'disable_wpcomtoolbar' );
```
This worked and the page loaded properly.

![Screen Shot on 2021-03-24 at 19:35:42](https://user-images.githubusercontent.com/4887830/112397280-27978c80-8cd8-11eb-8528-6a96e6af34c6.png)

### Steps to reproduce the behavior

1. Access an Atomic site's Jetpack > Dashboard and click View detailed stats -- or go directly to `/wp-admin/admin.php?page=stats`

#### What I expected to happen

For the page to load properly.

#### What actually happened

At first, page was not accessible. The workaround doesn't provide a working page.
### Context

3850326-zen

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

~Intermittent~ -- actually all my tests sites have this issue now so reproducing fairly consistently.

**Comment by galakhyati** [comment]
Got another case here: 28626674-hc

In this case, when adding the code for disabling WPCOM admin bar, it shows the stats on the domain/wp-admin dashboard widget as well as on the `/wp-admin/admin.php?page=stats` page too.

**Comment by obenland** [comment]
Rather than [bringing back the menu item](https://github.com/Automattic/jetpack/blob/66a1be724db0038d90286b4fea01978c954625b4/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L399), could we update the Jetpack Dashboard to not show the "View detailed stats" button in Jetpack > Dashboard when the masterbar module is active? /cc @jeherve
 
![Untitled](https://user-images.githubusercontent.com/1398304/112551745-b5c64e00-8d7e-11eb-828a-612d9b921744.jpg)

**Comment by Aurorum** [comment]
Even if it isn't included within the menu, should it not still be available through the direct link? I could imagine that may be helpful, at least until all the information provided on that page is available through Calypso (see #51252).

**Comment by JoshuaGoode** [comment]
We still have users that try to access that page or have it bookmarked @obenland 

For whatever reason, they prefer it over the WPCOM version.

**Comment by mmtr** [comment]
Another option is to do what @mrfoxtalbot suggested in https://github.com/Automattic/wp-calypso/issues/49756, and make sure that Jetpack Stats redirects to the Calypso Stats.

In general, as discussed in paYJgx-1tw-p2, anytime we unregister a page because there is already an equivalent one that we favor, we should either redirect users visiting the unregistered one to the registered one, or keep the old screen accessible via URL.

**Comment by jeherve** [comment]
> could we update the Jetpack Dashboard to not show the "View detailed stats" button in Jetpack > Dashboard when the masterbar module is active? /cc @jeherve

That can certainly be done, but I'm not sure I'd recommend doing that alone. Stats are an important part of many folks' sites, important enough that they bookmark the URL. If we were to remove that button, I would recommend creating the redirection @mmtr mentioned above.

That said, if we decide to hide that button from the Jetpack dashboard, we'll also need to remove it from the dashboard widget, as well as refactor that widget so that clicking on a specific date in the widget does not lead you to wp-admin stats.

![image](https://user-images.githubusercontent.com/426388/112613138-0c379900-8e20-11eb-8133-2f9245122e0f.png)

**Comment by JoshuaGoode** [comment]
Bringing over feedback @supernovia shared on the related issue regarding feature parity https://github.com/Automattic/wp-calypso/issues/51095

---

> One of our volunteers [mentioned a stats page discrepancy in our feedback thread](https://wordpress.com/forums/topic/unified-navigation/page/2/#post-3653791)
> 
> > I can no longer view my Sharing Stats or Akismet Stats in the Advanced Dashboard Pages. If I try to use the direct WP Admin links, I get a “this page does not exist” error.
> 
> She also [mentions](https://wordpress.com/forums/topic/unified-navigation/page/3/#post-3654353):
> 
> > Count me as one of the users who wants the full drilled down information that appeared on the previous sharing stats pages, including not only number of shares per social network, but also which posts were shared, as is mentioned in the support doc


https://github.com/Automattic/wp-calypso/issues/51095#issuecomment-808444400

---

> A user [complained in this thread](https://wordpress.com/forums/topic/unified-navigation/page/3/#post-3654264) that the newer Stats and Insights page is slow, and they don't like it. We can try to get more feedback on that if you're interested, but they did find the previous stats page more useful.

https://github.com/Automattic/wp-calypso/issues/51095#issuecomment-808445396

---

> More stats feedback from our [feedback thread](https://wordpress.com/forums/topic/unified-navigation/page/3/#post-3654107):
> 
> > WP-Admin Stats is by far the most significant loss. The summary charts were particularly important to me. On a single page, there was a table that showed the page view totals for each month and year over the lifetime of the site, and another table showing daily and weekly totals, and percentage gains or losses vs. the previous weeks, for recent weeks.

https://github.com/Automattic/wp-calypso/issues/51095#issuecomment-808560354

**Comment by Aurorum** [comment]
> Another option is to do what @mrfoxtalbot suggested in #49756, and make sure that Jetpack Stats redirects to the Calypso Stats.

@mmtr Looking at the feedback, it seems the main source of dismay is that Stats in Calypso doesn't provide all the information contained on `/wp-admin/admin.php?page=stats`. I wonder if this approach might not be ideal until the equivalent data is fully available in Calypso, and as there seems to be a fair amount missing currently, if it might not be better just to ensure `/wp-admin/admin.php?page=stats` is functioning with the direct link for now?

**Comment by marcuswisecaesar** [comment]
Stats feedback 

> The biggest difference that I recall is that you can click on "summary" and it will give you several charts. If I recall correctly, there's a chart of total views for every month since I began the blog (and a total of these for each year); one for average daily views for every month since I began the blog (and a total for each year); and total views for every day for the last month or so.These charts are all on the same page.
I also prefer the look of it (but that's something that won't kill me if it can't be recovered.)

Source: 3850326-zen

**Comment by sanjeev00733** [comment]
Another report in #28759706-hc
Follow up here #3872283-zen

**Comment by dcoleonline** [comment]
Another request in 28800282-hc

**Comment by katiebethbrown** [comment]
Another report in 3866599-zd-woothemes

They access the wp-admin stats page daily via a saved link. They do not like the Calypso stats page layout, and would like it to show their site icon as the favicon like the wp-admin page did (which it can't b/c it's loading from WordPress.com and not their custom domain).

**Comment by hacchism** [comment]
Another report in #28821709-hc

**Comment by devNigel** [comment]
Another report in #28739524-hc

**Comment by msilbers** [comment]
reported in #21754339-hc by a customer who misses the detailed stats from Jetpack/wp-admin

**Comment by gwensmithx** [comment]
> reported in #21754339-hc by a customer who misses the detailed stats from Jetpack/wp-admin

Just adding they came back to chat and said "It is the viewers breakdown - percentage of gender and age of viewers on my pages."

**Comment by Aurorum** [comment]
> It is the viewers breakdown - percentage of gender and age of viewers on my pages.

Am I correct in thinking that this information was never collected or presented by Jetpack?

**Comment by Nic-Sevic** [comment]
another 29008455-hc
