### ISSUE TITLE
Nav unification: Dutch interface display issue for the "Pages" menu item

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#51390]
### Steps to reproduce the behavior

1. Go to your account settings and set the Interface language to Dutch(Nederlands)
2. Click back to see the main dashboard of your site
3. You'll see this for the Pages menu item:

![image](https://user-images.githubusercontent.com/6737345/112443870-1ab97e00-8d56-11eb-8caf-e2b084ee1c13.png)

Pagina&#039;s

#### What I expected to happen
To see the Pagina's menus item. 

#### What actually happened
It seems the ' isn't rendered properly in the code.

### Context
- Manual testing

#### Browser / OS version
- Chrome / MacOS (89 / Big Surr)
-  
#### Is this specific to the applied theme? Which one?
- No

#### Does this happen on simple or atomic sites or both?
- Only on the Simple sites - the AT sites display it correctly. 

#### Is there any console output or error text?
- No
- 
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
- All the simple sites sites with the Dutch language set 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Added above

**Comment by Aurorum** [comment]
PR for this issue in #51418 :)
