### ISSUE TITLE
All posts missing in the dashboard since nav unification

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#51397]
Since nav unification launch
On this site - https://militarygogglebox.com
Premium plan / Simple site
In the dashboard all posts are not showing anymore.
The user has 11711 posts
It lists as having no posts
Switched to advanced view in the account settings and the posts re-appear again
Screenshot - 

<img width="1437" alt="Markup 2021-03-25 at 10 52 53" src="https://user-images.githubusercontent.com/1398304/113037455-3fdd3080-914a-11eb-89cc-c6ed7dd1a515.png">

**Comment by obenland** [comment]
Did they mention whether they used wp-admin exclusively before?

**Comment by tjcafferkey** [comment]
Potentially related to https://github.com/Automattic/wp-calypso/issues/45317 ?

**Comment by obenland** [comment]
Looks like it. Closing in favor of #45317.
