### ISSUE TITLE
Design picker: add integration test

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#51403]
### What
`DesignPicker` component should be covered with integration tests.

### Why
The component is being used in critical user flows such as onboarding.

### A/C
- [ ] Add an integration test to `DesignPicker` component that should check the following:
  *  all the designs are rendered
  * `onSelect` callback is called when clicking on a design
- [ ] should accept designs and render them.

**Comment by StefanNieuwenhuis** [comment]
Something to consider: Isn't there a way to use the original JSON-file instead of mocking it?
