### ISSUE TITLE
Design picker: cleanup after extraction to package

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#51404]
### What
Clean-up after the `DesignPicker` extraction to a package.

### Why
Keep the code maintainable and documentation updated.

### A/C
- [ ] Extract the randomization logic from `client/landing/gutenboarding/index.tsx` to the `DesignPicker` package and update `getAvalableDesigns` function to support returning also randomized designs. Design randomization and persistence should work as before in `/new`.
- [ ] Rename `DesignSelector` (`client/landing/gutenboarding/onboarding-block/design-selector`) folder, component name and the classnames to `Designs` and `designs__*` to avoid confusion with the `DesignPicker` package.
- [ ] JSON file: search for references to `available-designs-config.json` and update accordingly (code comments, p2 posts, fieldguide pages)

**Comment by ciampo** [comment]
Opened https://github.com/Automattic/wp-calypso/issues/51632 to track the randomization of the design in the onboarding flow separately, removed it as an A/C for this issue
