### ISSUE TITLE
Jetpack Connect: error message doesn't suggest alternatives

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5141]
Start by entering a wrong site URL in the form field:

![screen shot 2016-05-02 at 10 34 25 am](https://cloud.githubusercontent.com/assets/426388/14950517/7baf2ed4-1052-11e6-9d35-166573c1a453.png)

In this case, I added `www.` to an existing URL.

Would it be possible to have a nicer error message, maybe suggesting they try again, copy / paste their site URL?

**Comment by johnHackworth** [comment]
sounds like a good idea! ping @rickybanister @richardmuscat

**Comment by rickybanister** [comment]
We need to do a scrub of all the copy.

"Oops, we couldn't find that site. Try another url."

And 'selecting-all' the entered url in the field would be nice.

**Comment by rickybanister** [comment]
This was updated to be:

<img width="442" alt="screen shot 2016-06-16 at 5 02 51 pm" src="https://cloud.githubusercontent.com/assets/437258/16133119/3fb7230e-33e4-11e6-9397-bd644dea3630.png">

Some other improvements are coming regarding auto-focusing the url field. If you see an error message of any kind we need to focus the field and select the contents.

**Comment by rickybanister** [comment]
#6219 closes the second half of this issue—the field will be auto-focused and the submit button disabled until there is a change event on the field.

Am I correct @ryelle ?

**Comment by ryelle** [comment]
Correct about the auto-focus, but the submit button is only disabled for "already exists" errors.

**Comment by rickybanister** [comment]
Is it possible/practical to disable the button until the field changes regardless of the error? I don't think it makes sense to encourage users to re-submit a value if they've already been told it won't work.

**Comment by ryelle** [comment]
Sure -- I'll update that PR.

**Comment by ryelle** [comment]
@rickybanister now that the autofocus updates have been merged, is there anything else to do on this issue?

**Comment by rickybanister** [comment]
I think we can close this out for now. We'll see if the improvement you made helps any and then reprioritize improvements to the first step.
