### ISSUE TITLE
Nav Menu disappears on Jetpack sites after resizing window?

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51428]
### Steps to reproduce the behavior
Here's a video. Seems to only happen on wide views (1400pxish). And only happens after viewing a site with unified menu, and then viewing a Jetpack site. It also works to resize the window while viewing a unified site, and then navigate to a Jetpack one. 

1. Start in a wide window, maybe 1400px+ wide?
2. Go to a site with unified menu
2. Resize the window width 
3. Navigate to a Jetpack site
4. Menu disappears and will not return

#### Browser / OS version
Chrome Version 89.0.4389.90

#### Does this happen on simple or atomic sites or both?
Jetpack

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://user-images.githubusercontent.com/7129409/112557969-0ef4a880-8da4-11eb-97db-57909406477d.mov

**Comment by jsnajdr** [comment]
Fixed in #51364
