### ISSUE TITLE
Nav Unification: Use wp-admin comments screen for WoA sites

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#51429]
### Steps to reproduce the behavior

On a WordPress.com Atomic site with WooCommerce installed and at least one published customer product review:

1. Go to Comments which is also where product reviews are shown by Woo
2. Notice that it does not show the reviews in the Calypso version
3. Go to Account Settings and enable the Dashboard Appearance toggle
4. Go to Comments again (now showing WP Admin version) and see the product reviews

#### What I expected to happen

I expected to be able to see my product reviews without needing to enable the dashboard appearance toggle since it's not clear that's what I would need to do.

#### What actually happened

I could not access my product reviews.

### Context

#28623879-hc

#### Does this happen on simple or atomic sites or both?

Atomic with WooCommerce plugin

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects all sites running WooCommerce on the Business plan, and all eCommerce plan sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Before enabling the dashboard appearance toggle in Account Settings:

![image](https://user-images.githubusercontent.com/30727666/112561500-799bf780-8e29-11eb-9dce-f93cdd3d4b9b.png)

After:

![Annotation on 2021-03-26 at 11-51-36](https://user-images.githubusercontent.com/30727666/112561592-a819d280-8e29-11eb-9251-027ebaf60da3.png)

**Comment by katiebethbrown** [comment]
Another report in 3869798-zd-woothemes

**Comment by obenland** [comment]
@sfougnier Have you had a chance to audit the comment screen for feature parity with Calypso yet? Would this be candidate on WoA sites to switch over to wp-admin by default sooner than others, like posts/pages list screens?

**Comment by ghost** [comment]
Thanks for bringing this to my attention! I wasn't aware this was a scenario. The functionality between the two screens is actually almost 1:1, things are just styled a bit differently.

> Would this be candidate on WoA sites to switch over to wp-admin by default sooner than others, like posts/pages list screens?

Yes, I don't see why not.

**Comment by annbingle** [comment]
Reported the same here 3896251-zd

**Comment by aisajib** [comment]
This came up just now on 29094378-hc.

**Comment by tarunvijwani** [comment]
Another report in 28865312-hc

**Comment by daria2303** [comment]
Another one: [28271626-hc](https://hud.happychat.io/chat/28271626)
