### ISSUE TITLE
After canceling payment in `/new` flow, launching site from launch checklist fails

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#51436]
If payment was cancelled after selecting a paid plan in the `/new` flow, the user will be unable to launch their site from the launch checklist on the homepage. Launching from the editor still works as expected.

### To reproduce
* Navigate to the plans step of the `/new` flow
* Select a paid plan
<img width="1045" alt="Screen Shot 2021-03-26 at 4 21 28 PM" src="https://user-images.githubusercontent.com/22446385/112600055-69514000-8e5c-11eb-87d9-1f5237849c02.png">
* Close the payments window
<img width="1045" alt="Screen Shot 2021-03-26 at 4 22 06 PM" src="https://user-images.githubusercontent.com/22446385/112600094-7837f280-8e5c-11eb-9186-a7e56ebb1727.png">
* You will land in the editor, navigate back to the site home page
<img width="1045" alt="Screen Shot 2021-03-26 at 4 23 06 PM" src="https://user-images.githubusercontent.com/22446385/112600363-d533a880-8e5c-11eb-9126-494c44fd498a.png">
* Launch the site from the launch checklist 
<img width="1044" alt="Screen Shot 2021-03-26 at 4 23 31 PM" src="https://user-images.githubusercontent.com/22446385/112600427-ec729600-8e5c-11eb-9a16-0d100b53d383.png">

#### Expected 
You see the first step of the launch flow which is to select domains

#### Actual
You see this congratulations screen but the site is not launched

<img width="1048" alt="Screen Shot 2021-03-26 at 4 24 42 PM" src="https://user-images.githubusercontent.com/22446385/112600507-04e2b080-8e5d-11eb-8fbf-347c97cf390d.png">

this behavior persists after reloading the page.

**Comment by razvanpapadopol** [comment]
I'm not sure if this is directly related to the New Onboarding and it looks very similar, like a variation of https://github.com/Automattic/wp-calypso/issues/50273. Could you try to reproduce it also on the site creation `/start` flow?

**Comment by roo2** [comment]
hey @razvanpapadopol I tried the same steps from the `/start` flow but launching the site worked correctly, for some reason this only happens when using the `/new` flow.

**Comment by razvanpapadopol** [comment]
Unfortunately, I'm still unable to reproduce this one but I believe we should first manage to reproduce consistently https://github.com/Automattic/wp-calypso/issues/50273, and then check if something is different in this case that involves `/new`.
cc: @ciampo

**Comment by roo2** [comment]
since the /new flow is being deactivated and I believe is currently only available for podcast users from (the podcast company we partnered with). I've tested this with purchasing from via the /plans page and from the /start flow and can't reproduce it either way. Let's close this.
