### ISSUE TITLE
Nav Unification: Add option for re-publicize to wp-admin for Atomic sites

### ISSUE THREAD

**Issue by pauloeaquino** [Automattic/wp-calypso#51435]
### Steps to reproduce the behavior

1. Go to My Sites -> Posts
2. View post options

#### What I expected to happen

> Re-publicizing posts is a feature for sites on our WordPress.com Premium plan and Business plan plans.

I expected there to be an option to "Share" as per our support document here, https://wordpress.com/support/publicize/#sharing-your-content-again

![screenshot](https://d.pr/i/4ydjwy+)
_Note: Example screenshot is displaying a simple site_

#### What actually happened

I found no options in the post settings, or anywhere else. 

### Context
First encountered in #3853559-zen.

Simple sites still have the option to select "Share" when the "Show advanced dashboard pages." option is toggled off in Account Settings. 

However, this same condition does not seem to apply to Atomic sites since pages/posts are defaulting the WP-Admin view in any case.

#### Browser / OS version
macOS Big Sur 11.2.3

#### Is this specific to the applied theme? Which one?
Not theme specific.

#### Does this happen on simple or atomic sites or both?
Atomic sites only.

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all Atomic sites.

**Comment by rezzap** [comment]
Another report of this in 26103277-hc.

**Comment by zdenys** [comment]
28367777-hc

**Comment by jamiepalatnik** [comment]
Another report: 28678981-hc

User also reported that the post was not automatically shared either when it was first published because social buttons are greyed out and cannot be enabled. Could this be related? Screenshot: https://d.pr/i/WVIqha

**Comment by nagpai** [comment]
Atomic site. but the option does not appear within https://wordpress.com/posts/<site address>

#28664043-hc

**Comment by jp-imagines** [comment]
Another report in 28748346-hc.

**Comment by CompChris** [comment]
Another report: 28653208-hc

**Comment by kaitohm** [comment]
Another request for this feature here: 3883331-zd-woothemes

**Comment by obenland** [comment]
@lcollette @olaolusoga Would you anticipate the need for a design iteration for this in the context of wp-admin?

I wonder if we could use existing patterns, inline action links triggering either the Calypso component or a component that looks like it?

**Comment by lcollette** [comment]
@obenland, I don't think we need a design iteration here as there's already an established pattern for links within that UI. In the continued interest of unification, let's use the Calypso component, assuming the alternative would be to create a new one?

**Comment by obenland** [comment]
Right, re-assemble it through Gutenberg and/or Jetpack components. Happy to leave that to the technical exploration, though.

**Comment by goblinartificer** [comment]
one more from 28813292-hc :)

**Comment by zdenys** [comment]
28978798-hc

**Comment by donalirl** [comment]
Another request to bring back access to re-sharing posts in #29091391-hc

**Comment by joweber123** [comment]
Another report here - 28704142-hc

**Comment by cpapazoglou** [comment]
~~Recent discussion p9dueE-2LC-p2 .~~

**Comment by msilbers** [comment]
@cpapazoglou I was following along to read more, but it looks like that p2 post is about a totally different feature, Reblog, is that right?

**Comment by cpapazoglou** [comment]
> @cpapazoglou I was following along to read more, but it looks like that p2 post is about a totally different feature, Reblog, is that right?

Thanks for following up @msilbers! You are right, they are different features. I got confused by the "Share" link 😞!

**Comment by ericamQA** [comment]
Another instance in 29607996-hc

**Comment by aamills** [comment]
Came up amidst other conversation in 29680588-hc

**Comment by sajmes** [comment]
I see this is being worked on, but dropping another report here: 4038428-zd-woothemes

**Comment by carladoria** [comment]
Another report in [30095532-hc ](30095532-hc)

**Comment by ezebecke** [comment]
Another instance: 22952231-hc

**Comment by tjcafferkey** [comment]
Users now have the ability to use "Screen Options" to change the individual view to Calypso where the feature is available.

**Comment by daria2303** [comment]
> Users now have the ability to use "Screen Options" to change the individual view to Calypso where the feature is available.

I believe this is for now for simple sites only.

**Comment by xpurichan** [comment]
This problem appears to be resolved now. I was checking on it since 4038428-zen came out of hold. For this site if I go to https://wordpress.com/posts/DOMAINCOM I do see the Calypso version of the page, along with the "Share" option in the dot menu next to each post.

If someone could double-check me then I believe this can be closed. :)

**Comment by obenland** [comment]
I updated the title of the ticket to better reflect its purpose. Porting re-publicize to wp-admin will help with feature parity between Calypso and wp-admin, which is especially important for WoA sites.

**Comment by xpurichan** [comment]
That makes sense to me, thank you! So the workaround is to perform the action in the Calypso Posts page, and the long-term goal is to add the function to WP Admin.

**Comment by obenland** [comment]
@pablinos @allilevine Can this be closed now? The publicize work seems like it's separate to the purpose of this ticket?

**Comment by pablinos** [comment]
Yes, I think it can be. I think this was the issue that most closely matched the work we were doing on Republicize, but it's 'fixed' for now. I think @xpurichan sums it up nicely:

> That makes sense to me, thank you! So the workaround is to perform the action in the Calypso Posts page, and the long-term goal is to add the function to WP Admin.
