### ISSUE TITLE
Jetpack Connect: activate description isn't correct 

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5143]
> Once the plugin is installed, you'll need to click this tiny blue 'Activate' link from your plugins list page.

![screen shot 2016-05-02 at 10 57 08 am](https://cloud.githubusercontent.com/assets/426388/14950802/bcf24a28-1054-11e6-9d35-984bf22cb46d.png)

If I follow the instructions of the connect flow, I don't need to go to my Plugins list page. After clicking the Install button, I'm redirected to this page:

![screen shot 2016-05-02 at 10 58 48 am](https://cloud.githubusercontent.com/assets/426388/14950815/e140ef60-1054-11e6-882a-7c4a8d0605eb.png)

I think we should update the description to mention this step.

**Comment by johnHackworth** [comment]
This is right ... we are using only one activate example, when there have to be two:

One, as @jeherve say, for the activation after install, and other for the case where Jetpack is already installed but inactive (this is the case currently reflected by the "activation example")

**Comment by rickybanister** [comment]
How's this @johnHackworth 

> Once Jetpack is installed, click the 'Activate Plugin' link.
