### ISSUE TITLE
Calypsoify: Remove unnecessary parameter from external links

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#51444]
**Task Details**
In #50923 we added the `calypsoify=0` parameter to ensure that Calypsoify was disabled on those links. As Calypsoify now has to be explicitly enabled, this isn't necessary anymore, so we should remove this code.

**Related to**
#50923

**Comment by mmtr** [comment]
This was fixed in https://github.com/Automattic/wp-calypso/pull/51750.
