### ISSUE TITLE
Jetpack Connect: Test: link to search page instead of detail page

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5144]
When launching the installation, I'm redirected to `wp-admin/plugin-install.php?tab=plugin-information&plugin=jetpack`

![screen shot 2016-05-02 at 10 45 29 am](https://cloud.githubusercontent.com/assets/426388/14950661/d69e44be-1053-11e6-8358-d69f9103c4b5.png)

While the page offers useful information, the "Install button" isn't very visible. How about linking to `/wp-admin/plugin-install.php?tab=search&s=jetpack/` instead?

![screen shot 2016-05-02 at 10 50 40 am](https://cloud.githubusercontent.com/assets/426388/14950945/e1a7506a-1055-11e6-8c52-6cffeb5b4f88.png)
1. The user will be familiar with that screen, it includes details about their site, they recognize the menu
2. The Install button is at the top of the page.
3. It also has the advantage of avoiding a dead end when Jetpack is already installed, but not activated on the site:

![screen shot 2016-05-02 at 12 06 45 pm](https://cloud.githubusercontent.com/assets/426388/14952161/5dead1b2-105e-11e6-90b2-238218fe2395.png)

**Comment by johnHackworth** [comment]
^ ping @richardmuscat  & @rickybanister

**Comment by rickybanister** [comment]
If Jetpack is installed (I'm pretty sure we can effectively detect that) they instead go directly to activate the plugin, rather than the install screen. 

I'm not sure about the other suggestion. While it may be more familiar, there are more distractions on that screen. 

This may be a good candidate for a test where we just see which is more successful. 

Curious to hear what @beaulebens and @richardmuscat think.

**Comment by beaulebens** [comment]
I agree that it's worth testing, but yeah, I share the same concerns as Rick mentioned above, primarily that there are so many other options on that screen. We're also subject to the vagaries of the plugin search in wp-admin, and what it decides to display there as results.

@jeherve did you actually land on that plugin install screen for a site while testing out JPC? Or did you manually visit that link? As Rick said, we're at least attempting to detect if the plugin is there, to avoid that exact scenario.

**Comment by jeherve** [comment]
> @jeherve did you actually land on that plugin install screen for a site while testing out JPC?

Yes, it was during testing, when launching Connect for a site where Jetpack wasn't installed.

**Comment by beaulebens** [comment]
Sorry @jeherve, I meant the third screenshot in your post - the one with the disabled button. As far as I know, that only ever appears when you've got the plugin installed already. We do attempt to detect if you've got Jetpack installed, and then we don't send you to that screen (we send you to the Plugins screen, and tell you to activate/connect).

**Comment by jeherve** [comment]
> We do attempt to detect if you've got Jetpack installed, and then we don't send you to that screen (we send you to the Plugins screen, and tell you to activate/connect).

I actually can't reproduce anymore. I am indeed redirected to the Plugins screen now.

**Comment by rickybanister** [comment]
I've updated this issue as a proposal for a test. Once we get some baseline data we can do a split and see where users are more successful.

**Comment by jeherve** [comment]
This is not valid anymore since the install process has changed. Closing.
