### ISSUE TITLE
Site Editor: adjust template parts theme paths for site content export

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#51442]
### Description
Currently our FSE theme paths are prefixed with pub/ on Dotcom  for simple sites. This affects how our theme template parts taxonomies are saved, and it impacts the loading of template parts in the editor and the front end.

Everything works fine for simple sites since correct paths are established when the site created. However, if we export the template / part data, FSE theme paths in destination sites will probably change. If theme paths aren't nested like in simple sites, and are instead installed in the default `wp-content/themes` folder, user customized template / parts will not load.

Side note: The "Everything imports" might need to be updated as well ( see PCYsg-_qeJ-p2 ) 

### Steps to reproduce the behavior
1. Choose a full site editing enabled site
3. Navigate to the site editor
4. Update a template and template part
5. Export the site's content

![CleanShot 2022-03-25 at 12 14 15@2x](https://user-images.githubusercontent.com/533/160068622-d5876cec-939a-45ce-8882-e1cff47796d9.png)

6. On an atomic site or [a local WordPress Gutenberg development environment](https://github.com/wordpress/gutenberg), select tan FSE theme.
7. Import template and template part content

<img width="964" alt="CleanShot 2022-03-25 at 12 15 05@2x" src="https://user-images.githubusercontent.com/533/160068711-67084ba7-5cc9-4323-9c46-d0e9d2d369f1.png">

9. Navigate to the site editor
10. Verify that customizations to template / parts are _not_ shown

Resources:
- file that does not work (has pub/ template parts): [vishnugopaltest240.WordPress.2022-03-25.xml.zip](https://github.com/Automattic/wp-calypso/files/8348129/vishnugopaltest240.WordPress.2022-03-25.xml.zip)
- file that works (edited to remove pub/ prefix): [vishnugopaltest240.WordPress.2022-03-25-edited.xml.zip](https://github.com/Automattic/wp-calypso/files/8348133/vishnugopaltest240.WordPress.2022-03-25-edited.xml.zip)

**Comment by creativecoder** [comment]
cc @vishnugopal This issue came up recently as a maintenance issue for Caribou, see: p1646789768419779/1646764442.952139-slack-C01DF571R5Y

Some background:

Here's what we did for the import side of things, to add the theme prefix when needed D62467-code

And here's what we do for Atomic transfers to remove the prefix on transfer D60384-code. I imagine something similar could be done for exports.

**Comment by vishnugopal** [comment]
@creativecoder A simple site does not have Template and Template Parts for me, is there something I need to do to get that option in Tools > Export?

<img width="556" alt="CleanShot 2022-03-10 at 14 48 07@2x" src="https://user-images.githubusercontent.com/533/157630321-ef5efee9-9153-4d2e-a4f6-38f22c8afcd3.png">

**Comment by vishnugopal** [comment]
Just for clarification, here's what I tried:

https://user-images.githubusercontent.com/533/158753860-ea0a4594-7249-44f4-8945-f30cd60f9cc1.mp4

I'm unable to find `tt1-blocks` (think it's twenty twentyone blocks, but I'm assuming twentytwentytwo will work fine here)

cc @creativecoder

**Comment by creativecoder** [comment]
> A simple site does not have Template and Template Parts for me, is there something I need to do to get that option in Tools > Export?

@vishnugopal The post types aren't displayed in that list in the export options, but you should see the custom template data in the export if you select "All content". Try text searching the export file for `wp_template` and `wp_template_part` (post types) and also `wp_theme` (taxonomy).

**Comment by vishnugopal** [comment]
Triaged and reproduced! I've also updated the issue description and added 2 test files that can reproduce behavior.

**Comment by ouikhuan** [comment]
See more details on D83673-code

**Comment by ouikhuan** [comment]
It's been deployed and fixed so I'll close the issue for now.
