### ISSUE TITLE
Nav Unification: PressThis is missing in Advanced mode

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#51457]
### Steps to reproduce the behavior
1. Go to https://wordpress.com/settings/writing/ -- notice the Press This bookmarklet is an option at the bottom of the page.
2. Enable the advanced navigation mode at https://wordpress.com/me/account
3. Try to find the Press This option for that site

#### What I expected to happen
I would expect it to show up on Tools, or the site's Writing settings

#### What actually happened
It's only available in Calypso, and the link to that page is lost if advanced mode is enabled.

### Context
One of our forum volunteers noticed this and [mentioned it in our feedback thread](https://wordpress.com/forums/topic/unified-navigation/page/2/#post-3653791).

#### Does this happen on simple or atomic sites or both?
Sites with nav unification set to Advanced mode

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Unsure: it likely only affects people who are aware of PressThis.

**Comment by obenland** [comment]
PressThis _would_ be available in `wp-admin/tools.php` if we linked to it with the toggle active. 

Given how few customers this will affect, could we close for now and see how much feedback we actually get on this?

**Comment by supernovia** [comment]
If we have a toggle I think this would be a non-issue for now.

**Comment by tjcafferkey** [comment]
>If we have a toggle I think this would be a non-issue for now.

Now that we have the Quick Switch I am closing this issue. If any work needs to be done RE moving a feature then we should create another issue for this.
