### ISSUE TITLE
Nav Unification: All in One SEO plugin settings page leads to a blocked page and error.

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#51459]
While nav unification is active, users that activate the All in One SEO plugin will be greeted with "Sorry, you are not allowed to access this page" as they attempt to access the plugin's setup wizard at `wp-admin/index.php?page=aioseo-setup-wizard`

### Steps to reproduce the behavior

1. On an Atomic site, install https://wordpress.org/plugins/all-in-one-seo-pack/
2. You'll likely see the error immediately. If not, access `[domain]/wp-admin/index.php?page=aioseo-setup-wizard`

### Context
User and HE interactions

* Example interaction: 28660152-hc , p1616785757159200-slack-C01APA37DDW , p1616784535277400-slack-C03TY6J1A

*  Example interaction: 28653827-hc , 3855906-zen , p1616763189125500-slack-C03TY6J1A

* Also reported internally, pc4f5j-pf-p2#comment-919

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Impacts all sites attempting to setup [All in One SEO
](https://wordpress.org/plugins/all-in-one-seo-pack/)

#### Reproducibility (Consistent, Intermittent)

Consistent

**Comment by khristiansnyder** [comment]
Also ran into this in #28711490-hc .
