### ISSUE TITLE
Jetpack Connect: secondary user can't link their account via connect flow

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5145]
#### Steps to reproduce
0. Start on a Jetpack site that you've already connected to WordPress.com.
1. On your Jetpack site, create a new "Editor" user.
2. In a separate browser window, open WordPress.com and log in with that editor's WordPress.com account.
3. Go to https://wordpress.com/jetpack/connect and enter the Jetpack site URL
4. The site is shown as already connected, although it's not linked to that particular WordPress.com account

![screen shot 2016-05-02 at 11 35 30 am](https://cloud.githubusercontent.com/assets/426388/14951569/301ae0aa-105a-11e6-852b-b5c8a2f038f4.png)

**Comment by johnHackworth** [comment]
This should be fixed already
