### ISSUE TITLE
Jetpack Connect: screenshots are too big

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5146]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/connect
2. Enter a Jetpack site URL and hit connect
3. The screenshots seem a bit too big:

![screen shot 2016-05-02 at 11 40 25 am](https://cloud.githubusercontent.com/assets/426388/14951668/f5516f2e-105a-11e6-9833-f0383c25040c.png)

![screen shot 2016-05-02 at 11 41 22 am](https://cloud.githubusercontent.com/assets/426388/14951670/fac4a822-105a-11e6-993e-d2e3152d4491.png)

#### Browser / OS version

- Firefox 45.0.2
- Mac OS 10.11.4
- Macbook Pro Retina 13''

**Comment by johnHackworth** [comment]
oh, firefox :shakesFist: ... Good catch! :)

**Comment by v18** [comment]
@johnHackworth A similar issues happens in IE11:

<img width="1418" alt="jetpack-connect-ie-11" src="https://cloud.githubusercontent.com/assets/11487924/15034145/8be9e754-1240-11e6-8e36-0f29df1d1a2d.png">
