### ISSUE TITLE
Account Settings: Please Save on Toggle

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#51464]
Our forums volunteer sent in feedback about the toggle at https://wordpress.com/me/account, which does not automatically save when changed.

This is inconsistent with other areas of Calypso, like our [AMP settings](https://wordpress.com/settings/performance/), [Testimonial and Portfolio Settings](https://wordpress.com/settings/writing/), and the [Discussion Settings](https://wordpress.com/settings/discussion/).

Some of these pages have a save button, too, like Writing Settings, but a toggle change saves the settings automatically.  Because people may expect the toggle to save, and the dashboard color schemes can push the save button below the fold (or at least is quite disconnected from the toggle), a user may not realize they need to scroll down and save for their preference to take effect.

<img width="718" alt="Screen Shot 2021-03-26 at 3 45 45 PM" src="https://user-images.githubusercontent.com/3476361/112696033-b7f5de80-8e4a-11eb-9b1c-e6b88cc5bf2e.png">

<img width="707" alt="Screen Shot 2021-03-26 at 3 49 12 PM" src="https://user-images.githubusercontent.com/3476361/112696105-df4cab80-8e4a-11eb-9396-e9aee3298d79.png">

**Additional context**
Jen sent the feedback [in this thread.](https://wordpress.com/forums/topic/unified-navigation/page/4/#post-3654764) After a slack conversation I understood our toggles don't auto-save, but she pointed out that several do. She helps a lot of our users and tends to notice issues like this that get in their way.

**Comment by blackjackkent** [comment]
Given the current structure of this page, the easiest approach seemed to be to remove the save button entirely and have all three controls in the "Interface Settings" section (Language, Advanced Dashboard Pages, and Dashboard Color Scheme) autosave on change. A PR for this is open at https://github.com/Automattic/wp-calypso/pull/52168 !

**Comment by supernovia** [comment]
Thank you @blackjackkent !

**Comment by blackjackkent** [comment]
Closed after merge of #52168
