### ISSUE TITLE
Theme Editor, wp-admin/theme-editor.php is missing (Atomic)

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#51472]
Theme Editor, wp-admin/theme-editor.php is missing 

#### What I expected to happen

Able to edit theme via Theme Editor or wp-admin/theme-editor.php

#### What actually happened

Error: `Sorry, you are not allowed to access this page.`

#### Does this happen on simple or atomic sites or both?
Atomic Site

**Comment by Aurorum** [comment]
I can't seem to reproduce this issue, even with Nav Unification enabled, on my Atomic site - I wonder if there's only certain cases where this occurs?  

<img width="1852" alt="Screenshot 2021-03-27 at 08 56 12" src="https://user-images.githubusercontent.com/43215253/112715797-5ed58b80-8eda-11eb-9760-0e511f2ba29a.png">

Interestingly though, if I include the `wordpress.com` subdomain into the address URL (ie. `https://site.wordpress.com/wp-admin/theme-editor.php`) then I am given a 403 error. That's the first case where I haven't seen it just automatically redirect to the proper page.

**Comment by cpapazoglou** [comment]
@kosiew, how do you access the Theme Editor?

In my case it works by going Appearance -> Theme Editor

![](https://cln.sh/lZN7aF+)

I am closing it now, please reopen it if you still experience a problem.
