### ISSUE TITLE
Jetpack Connect: Jump Start when connecting to enable Manage

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5147]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/connect
2. Go though Connect process
3. Once the connection is complete, go to `yoursite.com/wp-admin/admin.php?page=jetpack`
4. You get the usual Jump Start message:

![screen shot 2016-05-02 at 11 53 31 am](https://cloud.githubusercontent.com/assets/426388/14951907/84edd234-105c-11e6-88e1-d91a3f5f453e.png)

#### What I expected

Since we skip that part of the connection, and redirect users to Calypso, shouldn't we run Jump Start in the background, or at least enable Manage so users can see everything Manage has to offer right away, without having to discover the Jetpack menu on their own first?

**Comment by johnHackworth** [comment]
This is already almost ready :)

https://github.com/Automattic/wp-calypso/pull/5056

**Comment by kraftbj** [comment]
The issue with that is if this is _the_ way to connect Jetpack, we'll need to prompt people or decide how we're going to do it.

If I visit wp-admin, install Jetpack all on my own, then click on Activate, I'm left on the /plans/ page on dotcom.

**Comment by johnHackworth** [comment]
when the new version of jetpack is released, manage will be autoactivated on this flow. So this would be a non-issue
