### ISSUE TITLE
Signup/Site Editor: Add three new Starter Designs

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#51476]
We've converted three of our existing Starter Designs to use a block-based theme, so that they can be added to the Site Editor signup flow.
1. https://vestablockstarter.wordpress.com/
2. https://easleyblockstarter.wordpress.com
3. https://maylandblockstarter.wordpress.com/

![image](https://user-images.githubusercontent.com/4550351/112772350-fa523200-907b-11eb-939d-0d9d96521b93.png)

![image](https://user-images.githubusercontent.com/4550351/112772361-0938e480-907c-11eb-94aa-1d91694dcb52.png)

cc @Automattic/dotcom-view-design @simison @vindl 

**Recipe**
The starter design "recipe" for these sites looks like the following.

* Mayland Blocks theme.
* Reduce default content to one static homepage.
* Update block-based content on the homepage.
* Reduce the nav menu in the site header and footer to one item ("Home")
* Default fonts and colors.

If the output of the created site does not match the screenshot above it's likely to be related to one of those parts of the "recipe".

**Comment by ramonjd** [comment]
Does https://github.com/Automattic/wp-calypso/pull/51701 close this one?

**Comment by simison** [comment]
Looks like yep! 

<img width="2194" alt="image" src="https://user-images.githubusercontent.com/87168/114019537-35701480-9877-11eb-9c60-7be736a16e88.png">
