### ISSUE TITLE
Jetpack Connect: searching for available upgrades takes about 20 seconds on average

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5148]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/connect
2. When going through the signup process, I often get stuck at this step: 

![screen shot 2016-05-02 at 12 07 31 pm](https://cloud.githubusercontent.com/assets/426388/14952176/99a5885a-105e-11e6-8bfc-35de326bf43a.png)

It usually takes about 20 seconds for the button to become clickable.

Are there any situations when no upgrades are available? Could the button be blue right away?

**Comment by danjjohnson** [comment]
I'd also be tempted to put a spinner on the button while it's searching, as it could appear that it has frozen.

**Comment by johnHackworth** [comment]
The big "searching available upgrades" delay is going to be hard to remove (under the hood, what we are doing there is refreshing user's WordPress.com sites list, so the freshly connected site appears there, so we can show them the available plans), but a spinner has been indeed added: 

https://github.com/Automattic/wp-calypso/pull/5370#issuecomment-219989962

**Comment by rickybanister** [comment]
I think we can shut this down for now—the spinner and new copy help set user expectations a little better. Also the time it takes is reflective of how many sites the user has (it's going to be higher for us). 

Maybe we can do some speed testing on different accounts to confirm this.

Or perhaps there's some way to do this without refreshing the whole site list? @mtias?

**Comment by johnHackworth** [comment]
I think the idea is to show here the plans list even if the site is not authorized / refreshed yet...  While the user takes a look at the plans, we can do all this on the background

**Comment by rickybanister** [comment]
That makes sense. If they already have a plan for some reason, we can just modify the plans page when that data comes through? The upgrade buttons should be disabled until the list loads I suppose.

**Comment by johnHackworth** [comment]
@rickybanister yeah, that was my idea... show the plans info, and then disable the buttons, or show a loader there or something like that
