### ISSUE TITLE
Jetpack Connect: link to empty stats when not interested in upgrades

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5149]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/connect/
2. At the end of the connection process, I get a link to the Stats' insights page for my site:

![screen shot 2016-05-02 at 12 09 40 pm](https://cloud.githubusercontent.com/assets/426388/14952224/ea55402e-105e-11e6-8b4b-ecb3f10264ff.png)

3. However, since I just connected my site, stats aren't useful at all for me right now. Should we link to a different view instead, like `/posts`?

**Comment by johnHackworth** [comment]
Not happening anymore, now you are redirected to you /posts
