### ISSUE TITLE
Jetpack Connect: do not offer dismiss option to email confirmation box

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5150]
#### Steps to reproduce
1. Starting in my site's dashboard, I install and activate Jetpack.
2. I click on the Connect button to create a WordPress.com account.
3. Upon creating an account, I get the following screen:

![screen shot 2016-05-02 at 12 26 24 pm](https://cloud.githubusercontent.com/assets/426388/14952499/1c6e6a02-1061-11e6-90cc-97640f838272.png)

4. Should the email confirmation box be dismissible? It seems like the most important thing to do for the user at that point.

**Comment by rickybanister** [comment]
@johnHackworth did we work up our own email validation notice, or is this the standard nux one? If it's the standard one, we'll need to address this upstream for all users.

**Comment by johnHackworth** [comment]
@rickybanister It's the standard nux one, we didn't do anything new there

**Comment by rickybanister** [comment]
Then we should open a different issue about the shared notice.

**Comment by rickybanister** [comment]
@jeherve this notice is being changed to more contextual messaging about verifying email and general nux work. Going to close this for now.
