### ISSUE TITLE
Nav Unification: Atomic sites with AMP can have oversized site icons.

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#51535]
### Steps to reproduce the behavior

1. On an Atomic site with AMP activated, switch from Reader Mode to either Standard/Transitional.
2. Refresh the page.
3. See the size of the site icon change in the site's dashboard admin sidebar.

#### What I expected to happen
No change to the site icon when switching between AMP modes. 

#### What actually happened
It looks like when  Standard/Transitional is enabled the CSS file 'admin-menu.css' is not being loaded so those CSS rules are not being applied.

![Markup on 2021-03-30 at 15:09:24](https://user-images.githubusercontent.com/24914028/112941716-061c2200-916a-11eb-80ea-4308c68372f0.png)

#### Does this happen on simple or atomic sites or both?
Atomic sites with AMP enabled. 

#### Is there any console output or error text?
No console errors

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Does not block purchases.  Cosmetic issue. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
*Standard/Transitional enabled*
![Markup on 2021-03-30 at 15:04:29](https://user-images.githubusercontent.com/24914028/112941259-3f07c700-9169-11eb-84df-c2458bd7c0bc.png)

*Reader Enabled*
![Markup on 2021-03-30 at 15:05:43](https://user-images.githubusercontent.com/24914028/112941354-6a8ab180-9169-11eb-9b95-f0820a4d36b2.png)

**Comment by cpapazoglou** [comment]
Thanks for reporting this! It's very interesting that if something else than "Reader" is selected then the masterbar module doesn't load at all.

![](https://cln.sh/DmRygl+)

**Comment by nickpagz** [comment]
Adding another instance of this issue from a user in chat #28268296-hc
In this case however, the image was extremely large and obscuring some of the menu items.

[![oops - image missing](https://d.pr/i/yRVONo+)](https://d.pr/i/yRVONo)

**Comment by obenland** [comment]
Received another report (p1617127529205600-slack-C01APA37DDW). With the site icon impeding the admin like that, let's bump it in priority and find a way to enqueue the styles with AMP in Standard mode.

**Comment by katiebethbrown** [comment]
Another report in 28654297-hc

**Comment by tellisbethel** [comment]
Another report here: 28728773-hc . This instance made large areas of the dashboard inaccessible as well: 
![image](https://user-images.githubusercontent.com/1767799/113070439-ee0fc700-9198-11eb-8b56-4bdbd549f835.png)

**Comment by mmtr** [comment]
We have hotfixed this for Atomic sites on 659-gh-Automattic/wpcomsh. A proper fix will be included in the next Jetpack release (https://github.com/Automattic/jetpack/pull/19357).
