### ISSUE TITLE
Redirect Flag - Disparity between Calypso & WP Admin

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#51530]
~~When the 'Show advanced dashboard pages.' option is enabled~~ on a simple site **with a mapped/registered domain**, a redirect flag will appear in the user's sidebar when accessing ~~the theme~~ a WP Admin page.

### Steps to reproduce the behavior

1. Go to WP Admin of a site with a mapped/registered domain
2. Check under the domain title in the upper lefthand corner to see the 'Redirect' flag. 

### Context
3858063-zen

#### Does this happen on simple or atomic sites or both?
I can only reproduce this on a Simple site. 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This does not affect functionality but is confusing for the user when they see that flag appear. 

#### Screenshot
![Markup on 2021-03-30 at 13:07:21](https://user-images.githubusercontent.com/24914028/112932888-b170ab00-9159-11eb-9de0-ee4a69fd4dbd.png)

**Comment by obenland** [comment]
Do we update the `is_redirect` site option somehow? 

https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/blocks/site/index.jsx#L186-L188

**Comment by cpapazoglou** [comment]
This happens in WP Admin and doesn't depend on the toggle. The toggle has surfaced it since user gets redirected to WP Admin. I updated the title & description.

This badge depend on the `is_redirected_domain()`  on https://github.com/Automattic/jetpack/blob/ba122ea426497ae860d770e58b0429802574f38e/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L115-L117

I am not sure what "Redirect" means, having a mapped domain classifies as a redirect to that domain from the WPCOM one?

**Comment by blackjackkent** [comment]
I'm a little confused on the desired behavior here. 🤔 

@joweber123 Is the issue that the "Redirect" link should not appear? Or that the wording is confusing and should be changed to something else?

**Comment by joweber123** [comment]
@blackjackkent The issue is that the redirect link appears at all.  I believe that it should not appear for the user.

**Comment by joweber123** [comment]
Looks like this has been reported again here - https://github.com/Automattic/wp-calypso/issues/51186

**Comment by msilbers** [comment]
@blackjackkent if it helps, the Redirect flag should only be appearing if someone has a paid Site Redirect on their site: https://wordpress.com/support/site-redirect/

That used to be the case, but it seems that right now it's seeing any custom domain as a redirect.

**Comment by blackjackkent** [comment]
@msilbers Thanks for the extra info! I meant to comment here and forgot, but I have a diff open for this at D60809-code.
