### ISSUE TITLE
Distclean doesn't work; missing lerna

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#51544]
Running `yarn distclean` fails with missing Lerna:

```
yarn run v1.22.10
$ yarn run clean && npx rimraf node_modules client/node_modules desktop/node_modules apps/*/node_modules packages/*/node_modules test/e2e/node_modules .cache apps/*/.cache vendor
$ yarn run clean:packages && yarn run clean:build && yarn run clean:public && yarn run clean:translations
$ lerna run clean --stream
/bin/sh: lerna: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Suppose `npx rimraf node_modules` gets rid of Lerna and then at the end `lerna clean` doesn't work anymore?

I don't have Lerna installed globally and I expected not to have ([it's not mentioned in docs either](https://wpcalypso.wordpress.com/devdocs/docs/install.md))

cc @Automattic/team-calypso

**Comment by scinos** [comment]
It is not required to have `lerna` installed.

`yarn distclean` expands to a series of commands, the first one being `yarn run clean` which eventually does `lerna run clean --stream`. In other words, `lerna` is executed before wiping out `node_modules`.

`yarn distclean` seems to work for me. However, I've seen the behavior you describe when running `yarn distclean` with an incomplete (or missing) `node_modules`.

**Comment by simison** [comment]
I indeed had a pretty old setup (maybe a couple months) and I updated dependencies only after running distclean. Just wanted to clean before refreshing deps. :-)

Feel free to close if it's non-issue. :-)

**Comment by scinos** [comment]
I was about to fix it by replacing `lerna run clean` with `npx lerna run clean`, which will download `lerna` if it is not in `node_modules`. In theory it should fix the issue. The problem then is that `npx lerna run clean` will launch a bunch of scripts from `./packages/`, which in turn also assumes some modules are installed (mainly `tsc`). So fixing this will uncover more problems.

We could add `npx` everywhere, but that has a few drawbacks: it is noisy, and more importantly, we won't have control over which version of `tsc` is used, which can break things if the wrong version is picked.

So I'd say we leave it as is. My guess is this is not a common scenario, or at least not common enough to outweigh the con specified above. Happy to be proven wrong though :)

**Comment by simison** [comment]
Sounds good, thanks for looking into it!
