### ISSUE TITLE
Atomic / Nav Unification: Dashboard Appearance Enabled not applied to Comments

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#51553]
### Steps to reproduce the behavior

On an Atomic site: 

1. Go to Comments - list of comments will appear (Calypso style)
2. Go to /me and enable dashboard appearance and save
3. Go back to Comments - list of comments will appear (Calypso style instead of WP-admin ). 

#### What I expected to happen

Enabling dashboard appearance will make the comments section look like WP-admin: 

<img width="1009" alt="Screen Shot 2021-03-30 at 4 21 09 PM" src="https://user-images.githubusercontent.com/36863633/113004518-f3a6e600-9173-11eb-9d00-d0758faecd26.png">

#### What actually happened

Enabling dashboard appearance did not change the comments section to look like WP-admin, and remained looking like the one in Calypso: 

<img width="1441" alt="Screen Shot 2021-03-30 at 4 22 55 PM" src="https://user-images.githubusercontent.com/36863633/113004844-32d53700-9174-11eb-9a85-f2b92bd4fb66.png">

#### Browser / OS version

Firefox, MacOS 11.2.3

#### Does this happen on simple or atomic sites or both?

Atomic only.

#### Is there any console output or error text?

No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects all Atomic sites. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

In an Atomic site, when Dashboard Appearance is  activated or deactivated, it looks like Calypso instead of WP-admin: 

<img width="1009" alt="Screen Shot 2021-03-30 at 4 21 09 PM" src="https://user-images.githubusercontent.com/36863633/113004518-f3a6e600-9173-11eb-9d00-d0758faecd26.png">

 

**Additional context**

User report and feedback in 3866945-zd

**Comment by cpapazoglou** [comment]
I can confirm that it works as expected for Simple sites but not for Atomic.

**Comment by kylemcph** [comment]
Another user pointed out they used the search feature to sort through email addresses of their commenters. I provided a direct link to the WP Admin → Comments page which is a fine temporary solution.

**Comment by nerdysandy** [comment]
Reported on #26142964-hc I shared the direct WP-Admin URL for now and asked them to bookmark it. This was for a Simple site

**Comment by obenland** [comment]
This will be fixed by https://github.com/Automattic/wp-calypso/issues/51429, defaulting the comments screen to wp-admin.

@tjcafferkey If #51429 is not closed by the time Ajax gets to this, maybe you could take it over and make the change for both tickets?

**Comment by tjcafferkey** [comment]
@obenland Yep the related issue #51429 is part of the bundle for Ajax's next iteration starting next week so we can pick it up then.

**Comment by kwight** [comment]
This ticket is part of Serenity's bundle, so I'll drop it from our sprint – @tjcafferkey let me know if you need assistance for it. 👍

**Comment by obenland** [comment]
Fixed in #51429.
