### ISSUE TITLE
Notifications: Gallery blocks display tiny images on mobile email notifications

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#51566]
### Steps to reproduce the behavior

1. Create a new post on a simple site
2. Add a gallery block with 2 images - it can be 1 or 2 columns
3. Publish the post
4. Check email notification post on a mobile - 

#### What I expected to happen
The gallery would display much like it does on a website - images in columns that are easy to see

#### What actually happened
The images are tiny on mobile when you view the email:

Post:
![Markup on 2021-03-31 at 09:35:12](https://user-images.githubusercontent.com/22053773/113108098-eb4abb80-9204-11eb-8e05-ecaba7e1fc29.png)

Notification:
![Markup on 2021-03-31 at 09:37:53](https://user-images.githubusercontent.com/22053773/113108115-ef76d900-9204-11eb-9a46-d42fb84a2fff.png)

Adding an image in a columns block utilises the space more effectively.

### Context
3860898-zd-woothemes

#### Is this specific to the applied theme? Which one?
The level of impact is different based on the theme but the issue is still existent. Tested on TwentySeventeen and that's what I used for the screenshot.

A similar issue occurs with TwentyTwentyOne but the images are slightly bigger so the impact is less.

#### Does this happen on simple or atomic sites or both?
Tested on Simple

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium impact due to large spread but it's not a blocker

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

**Comment by kdevnel** [comment]
cc: @inaikem

**Comment by pauljacobson** [comment]
I have a very similar report in 3870080-zen for this post (and previous posts on this site): https://keurwood.com/2021/03/30/5-week-pupdates-tiva-x-creed-f4-pomskies/

### Screenshots

Mobile email -

![img_4606](https://user-images.githubusercontent.com/2912202/113170809-92ecdb80-924f-11eb-9f2c-7f4a5da6eec4.png)

Desktop Gmail -

![img_4607](https://user-images.githubusercontent.com/2912202/113170850-9e400700-924f-11eb-84f4-ca9ba42b7e51.png)

By contrast, this is the site in responsive mode -

<img width="508" alt="Screen Shot 2021-03-31 at 18 32 23" src="https://user-images.githubusercontent.com/2912202/113170933-b1eb6d80-924f-11eb-81c3-c9f956e3c0fc.png">

The site is using the Exford theme.

**Comment by synora** [comment]
@davemart-in or @obenland would either one of you be able to look into this or at least let us know which team could do so?

**Comment by davemart-in** [comment]
I'm not 100% sure. cc @kwight and @apeatling. It seems like someone was working on galleries lately.

**Comment by obenland** [comment]
@mreishus Any chance the Atomic work on image sizes could affect this?

**Comment by mreishus** [comment]
I don't believe it's the cause:

I tested by taking a local version of jetpack, reverting https://github.com/Automattic/jetpack/commit/2e049665899fc74169e7da87131271fa451d1acb (https://github.com/Automattic/jetpack/pull/19201), building the jetpack extensions, syncing them to my sandbox, sandboxing public-api, creating a new post w/ a gallery on a simple site and checking the email on my iphone. I saw the bug both before and after taking these steps.

**Comment by kwight** [comment]
I can't replicate this myself; anyone have any further details?

![cats-1](https://user-images.githubusercontent.com/349751/128935509-7e323777-5025-4159-b80f-24f302c45965.jpg)
![cats-2](https://user-images.githubusercontent.com/349751/128935511-60f5bee5-8b5c-413e-8bb2-6b0d23508a99.jpg)

**Comment by kwight** [comment]
Closing – anyone feel free to reopen if there are some steps to replicate.

**Comment by jp-imagines** [comment]
I had another user report this in 32783889-hc.

They provided a screenshot:
![small-gallery](https://user-images.githubusercontent.com/5630717/142234684-8db35c66-8882-4368-b927-a44e43ce7624.png)

They said this _only_ happens on iPhones, and started no more than 2-3 weeks ago (though they weren't certain on the exact timeline). Android phones displayed the gallery fine.

Singular Image blocks also display correctly, even on iPhones, and the shrunken Gallery images display at a more normal size for iPhones in landscape orientation:
![landscape](https://user-images.githubusercontent.com/5630717/142235132-965feccb-332e-475b-b6be-34e7a9ce1fdd.png)

I confirmed that these are just standard Gallery blocks.

Not able to replicate this myself (as I don't have an iPhone), but I'm reopening the issue just in case other reports start coming in as well.

**Comment by mashikag** [comment]
Those are old templates. Let's verify this is reproducible with the new templates.

**Comment by TimBroddin** [comment]
It looks OK with the Gallery caption patch applied: D89255-code

Probably fixed with https://github.com/Automattic/wp-calypso/issues/63297

![IMG_417607116CD5-1](https://user-images.githubusercontent.com/528287/194298860-4dda75ad-52bf-4c9f-92f6-ff2c87a7336b.jpeg)
