### ISSUE TITLE
Nav Unification: Introduction modal has truncated text in non-English languages.

### ISSUE THREAD

**Issue by emilyaudela** [Automattic/wp-calypso#51561]
### Steps to reproduce the behavior

1. Go to WordPress.com
2. Change your user language to one of the following languages: Russian, German, Dutch, or French.
3. Activate the Nav Unification Customer Modal
4. The text in the first screen is cut off in languages with a lot of text expansion.

#### What I expected to happen

I expected to see the entire message or to be able to scroll down and see the text that was cut off. 

#### What actually happened

The text is truncated in the first screen for several languages. 

<img width="474" alt="Screen Shot 2021-03-30 at 3 29 19 PM" src="https://user-images.githubusercontent.com/36699353/113060187-8e4ff680-916d-11eb-8a60-ed4427a448fc.png">
<img width="474" alt="Screen Shot 2021-03-30 at 3 25 17 PM" src="https://user-images.githubusercontent.com/36699353/113060197-9019ba00-916d-11eb-8066-7e10fc5fb2b7.png">

The modal needs to be fixed to adapt for text expansion, so users can see all the text.

**Comment by cpapazoglou** [comment]
I marked this as High, cause if we are not fixing it now that there are still Users who haven'd dismissed it then probably there is no reason fixing it as new users don't see that modal at all.
