### ISSUE TITLE
Free Atomic: Activity Log Banner

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51585]
Activity Log is different based on their plan. We need to ensure that after they purchase Yoast and are migrated to Atomic infrastructure that the view and upgrade options are maintained.

### What plan tier is the site on?
Free

### Where are you seeing the issue?
/activity-log/site

#### What I expected on the Atomic site

![image](https://user-images.githubusercontent.com/7129409/113170151-4b952980-9214-11eb-8fda-644298565c90.png)

#### What actually happened
![image](https://user-images.githubusercontent.com/7129409/113170120-459f4880-9214-11eb-817a-789eb04575b3.png)

#### Is this specific to the applied theme? Which one?
no

**Comment by mmtr** [comment]
Wondering if maybe adding an additional `! isAtomic` check here would solve the issue: https://github.com/Automattic/wp-calypso/blob/0f30cbab5d3b29de26f395277d16ac5e2d5dc386/client/my-sites/activity/activity-log-banner/upgrade-banner.jsx#L31
