### ISSUE TITLE
Free Atomic: Upsell banners showing the wrong logo (Jetpack)

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51584]
### What plan tier is the site on?
Free 

### Where are you seeing the issue?

/plugins/site
![image](https://user-images.githubusercontent.com/7129409/113169086-45eb1400-9213-11eb-8d00-0e455f254810.png)

/hosting-configuration/site
![image](https://user-images.githubusercontent.com/7129409/113169213-61561f00-9213-11eb-9e19-60ea556483ea.png)

#### What I expected on the Atomic site
The same as wp.com. Should look like this:
![image](https://user-images.githubusercontent.com/7129409/113169360-877bbf00-9213-11eb-9e2a-ae1b029e3161.png)

#### What actually happened
See above screenshots

**Comment by Aurorum** [comment]
Hi @dereksmart, just of curiosity, how is it possible to turn a site on the Free Plan into an Atomic one? Is it just a matter of a paid plan expiring?

**Comment by mmtr** [comment]
This should've been fixed by https://github.com/Automattic/wp-calypso/pull/53146.

> Is it just a matter of a paid plan expiring?

Correct.
