### ISSUE TITLE
Nav Unification: Add Quick Edit 

### ISSUE THREAD

**Issue by aleone89** [Automattic/wp-calypso#51581]
Now that Nav Unification is launched, users who would automatically revert to wp-admin are now noticing things that may not be there, but maybe a handy feature. 

**What**

A way to edit some of the smaller pieces of information regarding a post via a Quick Edit system  Posts > All posts:

<img src="https://cdn-std.droplr.net/files/acc_662189/NPmIy9" />

<img src="https://cdn-std.droplr.net/files/acc_662189/ujO8MX" />

- Title
- Slug 
- Password 
- Categories 
- Tags 
- Allow comments/pings 
- Status
- Sticky 

**Why**
This is a really nice, handy way of making quick changes without having to load the post. 

**Additional context**
Users have reported this in the forums here: 

https://wordpress.com/forums/topic/adding-tags-21/
https://wordpress.com/forums/topic/quick-edit-2/

**Comment by obenland** [comment]
Is this a request to add Quick Edit to Calypso's pages and posts list? I'm not entirely clear on that based on the ticket description.

**Comment by nerdysandy** [comment]
Yes, to add Quick Edit to Calypso's pages and posts lists. Something to add here https://d.pr/i/410e1l or to the three dots dropdown on the right. This is usually shown when you are in WP-Admin. For now, if the users want to use Quick Edit, they either need to add /wp-admin to the URL or toggle on the `Show Advanced Dashboard` pages option :)

**Comment by obenland** [comment]
Thanks for the clarification! 

We've recently switched WoA customers to using wp-admin's post list to take advantage of Core's built-in bulk edit functionality. To that end we are currently exploring porting Calypso-only features to wp-admin so we can do that for Simple Site customers as well. (Example: p1HpG7-bH3-p2).

If you don't mind, I'll close this in favor of https://github.com/Automattic/wp-calypso/issues/51435. Thank you!

**Comment by aleone89** [comment]
> We've recently switched WoA customers to using wp-admin's post list to take advantage of Core's built-in bulk edit functionality.

Does this mean when AT users click on posts, they'll go to wp-admin/posts.php ?

> To that end we are currently exploring porting Calypso-only features to wp-admin so we can do that for Simple Site customers as well. (Example: p1HpG7-bH3-p2).

Ok, does this mean these features going from Calypso to WP Admin will only be visible via wp-admin?

> If you don't mind, I'll close this in favor of #51435. Thank you!

I think I'm missing something here, I'm not sure how #51435 relates to this particular feature request? 

> Is this a request to add Quick Edit to Calypso's pages and posts list? 

That's correct. This ticket really isn't about features going from calypso to WP-Admin, but the other way round. Features available on WP-Admin to be placed on Calypso. 

Many thanks in advance for any clarification that can be offered. :)

**Comment by obenland** [comment]
> Does this mean when AT users click on posts, they'll go to wp-admin/posts.php ?

Yes, that is already live. If you encounter a WoA site that has their Posts menu item link to Calypso it should be considered a bug.

> Ok, does this mean these features going from Calypso to WP Admin will only be visible via wp-admin?

Yes, we want to remove the need for duplicate screens because one environment has a feature that the other doesn't have.

> I think I'm missing something here, I'm not sure how #51435 relates to this particular feature request?

By fixing #51435 we can move simple sites over to using wp-admin for their posts/pages list as well, removing the need to port bulk editing to Calypso.
