### ISSUE TITLE
Free Atomic: Show Footer credit 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51587]
### What plan tier is the site on?
Free

### Where are you seeing the issue?

On WP.com we display a footer credit back to WordPress.com that is managed by the Customizer. This is not present on Atomic sites.

For feature parity this needs to be enabled for Free sites that are on Atomic.

#### What I expected on the Atomic site
![image](https://user-images.githubusercontent.com/7129409/113170616-b9415580-9214-11eb-9962-00e5f2ad352b.png)

![image](https://user-images.githubusercontent.com/7129409/113170670-c6f6db00-9214-11eb-8d27-58389d6d2016.png)

#### What actually happened
It's not shown.

**Comment by cpapazoglou** [comment]
Related https://github.com/Automattic/wp-calypso/issues/51929

**Comment by obenland** [comment]
We should check persistent data, have wp.com set persistent data based on the plan, and have wpcomsh read that data and display the footer if the plan indicates it should.

**Comment by DustyReagan** [comment]
Created #60734 to address the missing "Footer credit" panel in Settings. Hopefully that covers this particular issue. I'd like to move #51929 up from the backlog and look at it next, since it's closely related.
