### ISSUE TITLE
Free Atomic: Gutenberg Block plan restrictions 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51595]
We need to maintain upgrade routes for the following blocks. Note that the plans listed are where they should be restricted

* Video 
  * Free
  * Personal
* Donations
  * Free
* Open Table
  * Free
  * Personal
* Payments
  * Free
* Pay with Paypal
  * Free
  * Personal
* Calendly 
  * Free
  * Personal

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/7129409/113174590-8600c580-9218-11eb-8d7c-d8c3458edad6.png)

**Comment by cpapazoglou** [comment]
@retrofox will the above be resolved as part of https://github.com/Automattic/jetpack/pull/19762 ?

**Comment by retrofox** [comment]
We need to check the proper plan for the paid block, but I think it should be handled by Automattic/jetpack#19762

**Comment by retrofox** [comment]
The URLs are properly created for the upgrade button in the Jetpack PR. However, I think we need to start to handle some of these plans for Atomic sites. Currently, it's possible to upgrade only to `Business` or `eCommerce` plan.

**Comment by retrofox** [comment]
In my tesitng site:

<img src="https://user-images.githubusercontent.com/77539/117665249-0223ec80-b179-11eb-8962-59e3e092a3dc.png" width="800px" />

<img width="800px" alt="Screen Shot 2021-05-10 at 10 17 03 AM" src="https://user-images.githubusercontent.com/77539/117665182-f46e6700-b178-11eb-8dd6-70db33ecc1af.png">

**Comment by retrofox** [comment]
> @retrofox will the above be resolved as part of [Automattic/jetpack#19762](https://github.com/Automattic/jetpack/pull/19762) ?

Although the [Automattic/jetpack#19762](https://github.com/Automattic/jetpack/pull/19762) will update the upgrade button URL, we need to handle the plans for Atomic sites since right now it isn't possible to buy a `Personal` plan.

So in the meanwhile, would you consider proper to offer to customers upgrading for the next lowest plan? For instance, if `Premium` is not supported for Atomic sites, let's suggest a `Business` plan.

**Comment by cpapazoglou** [comment]
Currently `Business` on Atomic seems the safest bet.

**Comment by retrofox** [comment]
Also, we can redirect to the plans page too.

**Comment by cpapazoglou** [comment]
> Also, we can redirect to the plans page too.

Ahhh, yeah! Redirecting to plans page seems better! How would you feel keeping the Checkout Url with the correct plan and then when user lands in Checkout, redirect them to plans page if the cart doesn't have a valid plan? That way, when we properly enable all plans in Atomic, we won't need to change the code again.

**Comment by retrofox** [comment]
That sounds good to me. Let me dig on this.

**Comment by retrofox** [comment]
After diving into the code I think it should be tackled in a separate approach, probably here in calypso. For now, we are going to redirect to the plans page instead of the checkout one.

**Comment by obenland** [comment]
In the context of Limited Atomic, this should be a non-issue once customers can upgrade to a Personal/Premium plan on Atomic?

**Comment by DustyReagan** [comment]
I believe we addressed this issue in Limited Atomic in https://github.com/Automattic/jetpack/pull/23189. I took the blocks for another spin on my free and personal Atomic dev sites. They appear to be properly gating on feature and nudging a plan upgrade.
