### ISSUE TITLE
Themes: Improve visibility of documentation

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#5160]
While reviewing theme documentation we've found that it's currently hard to discover the existing docs when selecting a theme during initial signup/site creation (including Headstart) or choosing a different theme at wordpress.com/design.

For example, from wordpress.com/design the only way to get to the theme documentation is to click the three dots icon, then click Details to open the single theme page on wordpress.com/themes/ that includes the documentation.

<img width="697" alt="screen shot 2016-05-02 at 10 22 34 am" src="https://cloud.githubusercontent.com/assets/1900444/14961789/647c5e28-1050-11e6-94c1-6181c2462fb9.png">

We should improve the visibility of this documentation by adding a banner, overlay, or other design to highlight where this documentation can be found immediately after activating and/or add it to the navigation in some way for future navigation.

cc @kathrynwp @joelwills

**Comment by folletto** [comment]
Thanks for the reminder. This is taken into consideration, but there wasn't a tracker for it.

Note (mostly to self, but for general awareness too):

1. Check / Add item in the ••• popup menu
2. Check / Add item in the activation window overlay
3. Check / Add item in the current theme top bar

**Comment by ockham** [comment]
@folletto I think we've got your checklist covered -- so do we close this?

**Comment by folletto** [comment]
I'm using this as a reminder to refactor the ••• menu. We can either close this and open a new one, or keep this for that objective (maybe changing the title?).

**Comment by ockham** [comment]
Ah okay, sry, misunderstood you then.

**Comment by folletto** [comment]
I'm closing this because we launched live M4 and the navigation changes have been split into two separate ones: #6221 (default action) and #6249 (aligned ••• menu). :)
