### ISSUE TITLE
Allow 4K resolution videos in VideoPress

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#51615]
### Description

A user is seeing a drop in video quality between VideoPress and other SNS platforms.
As phones can now shoot in 4k, we should be able to support this on our platform, too.

### References

Internal discussion already started here: pxWta-Qo-p2
VidePress reduces video quality to 720p.

I'm starting this GitHub thread, so we can collect user interactions where they request this.

Starting with 3861419-zd-woothemes

**Comment by roundhill** [comment]
VideoPress supports 4K now!
