### ISSUE TITLE
Stats hovercard not fully closing/hiding on mouse out

### ISSUE THREAD

**Issue by jessepearson** [Automattic/wp-calypso#5162]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/jp20160404.wordpress.com or any site .wordpress.com
2. Hover over days of the month, left to right and back.
3. Hovercard does not fully close on most browsers, but is worse on Win10 Edge and Firefox

#### What I expected
Hovercard to show and disappear.

#### What happened instead
Hovercard shows, and sometimes the top section remains. 

#### Browser / OS version
OSX: Firefox, Chrome
Win10: Edge, Firefox, Chrome

#### Other notes
Appears to have been reported previously, but could not find bug report on GitHub.

#### Screenshot / Video

OSX: Chrome
![stats_get_stuck_mac_chrome](https://cloud.githubusercontent.com/assets/4634416/14963862/aae1222c-1073-11e6-8910-a7dd83001120.gif)

OSX: Firefox
![stats_get_stuck_mac_ff](https://cloud.githubusercontent.com/assets/4634416/14963861/aae09672-1073-11e6-9f75-af8424048491.gif)

OSX: Safari
![stats_get_stuck_mac_safari](https://cloud.githubusercontent.com/assets/4634416/14963863/aae1bbba-1073-11e6-8688-6b9770631b28.gif)

Win10: Chrome
![stats_get_stuck_win10_chrome](https://cloud.githubusercontent.com/assets/4634416/14963864/aae21cae-1073-11e6-8dd3-7f6be7a72e4f.gif)

Win10: Edge
![stats_get_stuck_win10_edge](https://cloud.githubusercontent.com/assets/4634416/14963866/aae5949c-1073-11e6-8e48-febe46b8e3aa.gif)

Win10: Firefox
![stats_get_stuck_win10_ff](https://cloud.githubusercontent.com/assets/4634416/14963865/aae26a38-1073-11e6-8c50-bfd145bfd78c.gif)

**Comment by lancewillett** [comment]
Thanks for the report. :)

**Comment by lancewillett** [comment]
Here's the previous report: 

> Fast mouseover on the posting activity graph result in popover artifacts (Firefox-only)

https://github.com/Automattic/wp-calypso/pull/2863#issuecomment-204488056

**Comment by kathrynwp** [comment]
Another report of a similar issue in Firefox 47 by... my mom. 

I was able to replicate by visiting the Stats page of a site on which I'm a user and clicking the Day view, such as:

https://wordpress.com/stats/day/fieldguide.automattic.com

![stats automattic field guide wordpress com-2](https://cloud.githubusercontent.com/assets/7662449/16133787/b78d2ed4-33e7-11e6-9486-f894a17f9057.png)

No user report since this is a family matter. :)

**Comment by kriskarkoski** [comment]
I could not reproduce this issue in Chrome 53 or Firefox 48.

@jessepearson @kathrynwp Do either of you see this issue still?

**Comment by kathrynwp** [comment]
I no longer see this issue. Firefox 49.0.1. Will confirm with my mom as well.

**Comment by kathrynwp** [comment]
My mom confirmed it's gone for her in Firefox as well.

**Comment by jessepearson** [comment]
I wasn't able to reproduce anymore, either :)

**Comment by lancewillett** [comment]
Thanks for the follow-ups. :)
