### ISSUE TITLE
Write Button: Ensure that the Dashboard Appearance setting is honoured

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#51634]
#51058 has been solved within Calypso by #51108, but with people switching between `wp-admin` and Calypso now that the unified navigation is live, the Write button in the toolbar of `wp-admin` needs to be updated to make sure that it respects the Dashboard Appearance setting also.

This isn't an urgent fix as if someone navigates to a Gutenframe URL, they will be redirected to `wp-admin` with the Dashboard Appearance toggle enabled, but we shouldn't be relying on that redirect - although we have been up until now with the check as to whether a site is eligible for Gutenframe.

**Comment by fresatomica** [comment]
This was reported here: https://wordpress.com/forums/topic/unified-navigation/page/6/#post-3658232.

**Comment by cpapazoglou** [comment]
Here is the WPCOM part D61646-code.

In https://github.com/Automattic/wp-calypso/issues/51639, I am going to move on with the Atomic / Jetpack counterpart.

**Comment by BogdanUngureanu** [comment]
> Here is the WPCOM part D61646-code.
> 
> In #51639, I am going to move on with the Atomic / Jetpack counterpart.

Just tested on my sandbox and it works great! 🎉  I've added a small comment about a possible warning that will be triggered since PHP 8.

**Comment by cpapazoglou** [comment]
Deployed r226017-wpcom
