### ISSUE TITLE
Write Button: Ensure Atomic sites are sent to wp-admin

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#51639]
Atomic sites should always default to the `wp-admin` version of the editor, but the Write button currently links to the Gutenframe version unless the Dashboard Experience toggle is on.

We need to check if it's an Atomic site and if so, use the same link as the new post link in the admin menu. It would be good to investigate if we could do this in general, so that the logic of which link to use is kept in one place.

**Related to**

#51634 and #51108

**Comment by cpapazoglou** [comment]
> It would be good to investigate if we could do this in general, so that the logic of which link to use is kept in one place.

That's a good point. That would entail removing all masterbar related code from WPCOM and refactoring the current Jetpack masterbar https://github.com/Automattic/jetpack/blob/76db8162f645ea47974db0738f61f34363e06909/projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php#L26.

I am afraid that this would increase the scope of this issue exponentially. We should have it in mind though!
