### ISSUE TITLE
Coming Soon Mode: Users can find a blog that's in coming soon mode in Reader and follow it.

### ISSUE THREAD

**Issue by Thelmachido** [Automattic/wp-calypso#51660]
### Steps to reproduce the behavior

1. Go to 'Reader' search for a blog that is currently set to coming soon.
2. You will be given an option to follow the blog.
3. Checked the notifications on the blog owner's account and it looks like another user liked a post and then followed the blog.

#### What I expected to happen
I expected to find the blog in Reader but not have the option to follow the blog, also not have the option to like a post.

#### What actually happened
Another user managed to like a post and follow the blog.

**Comment by simison** [comment]
I believe we have a sticker to exclude from Reader, which we could add on site creation, and remove on site launch?

**Comment by Thelmachido** [comment]
> I believe we have a sticker to exclude from Reader, which we could add on site creation, and remove on site launch?
 
I can also add this sticker?

**Comment by roo2** [comment]
I've got a patch to fix this, I just need to get it merged D55562-code

**Comment by roo2** [comment]
fixed now with  D55562-code
