### ISSUE TITLE
Stats: "Average per day" in Insights for current month is inaccurate

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#51673]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/stats/insights/DOMAIN.COM
2. Click on "Average per day" tab in "All-time views"
3. Check the number for current month

#### What actually happened

It shows a number that makes no sense. For example, for the user I chatted with today, they have gotten 3,760 views until the end of April 4th. And given that today is April 5th, the average daily number should be 940 but it showed 129 instead, which is totally inaccurate. 

I've checked several sites(both simple and atomic) and could reproduce the issue on all sites I've tested so far.

Jetpack Stats page we can access via https://DOMAIN.com/wp-admin/admin.php?page=stats&view=table&disable-nav-unification is showing the accurate number for "Average per Day". So this could be another reason why users prefer Jetpack Stats page(Related to #51381).

### Context

Originally reported in 28821709-hc.

**Comment by Aurorum** [comment]
I believe that the issue in this case is that the number is calculated with the total number of days in the month instead of how many days have already passed in the month.

**Comment by Aurorum** [comment]
PR for this issue in #51677. :)

**Comment by hacchism** [comment]
> I believe that the issue in this case is that the number is calculated with the total number of days in the month instead of how many days have already passed in the month.

Oh! That's true. Good find. Thanks for opening the PR and working on a fix so promptly✨

**Comment by arunsathiya** [comment]
@tyxla When you have some time, could you help understand if WordPress.com desktop app might need a different patch? In this chat report 28810614-hc that @tarunvijwani and @sanjeev00733 worked on, user reported seeing incorrect "average by day" on the desktop app, but correct numbers on the web browser. So, is it just a case of the desktop app needing a restart so that the Calypso PR https://github.com/Automattic/wp-calypso/pull/51677 is accounted for, or does desktop require a separate PR? Thanks for taking a look!

**Comment by tyxla** [comment]
Hey @arunsathiya! The latest desktop app release was released before we merged #51677, so the fix should be in the next release.

**Comment by arunsathiya** [comment]
That makes more sense, thanks @tyxla! Just to make sure I understand the releases part, was the last release of desktop app really in Aug 2020? 🤔 - https://github.com/Automattic/wp-desktop/releases

**Comment by tyxla** [comment]
> That makes more sense, thanks @tyxla! Just to make sure I understand the releases part, was the last release of desktop app really in Aug 2020? 🤔 - https://github.com/Automattic/wp-desktop/releases

Good question - actually, the WP.com desktop app has been part of Calypso since then, and the releases [can be found](https://github.com/Automattic/wp-calypso/releases) in the `wp-calypso` repo.

**Comment by arunsathiya** [comment]
Ooh, that's helpful info, thanks @tyxla!
