### ISSUE TITLE
People: Accepting viewer invite to private site sometimes shows additional "Join" dialog

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5169]
Our automated e2e tests highlight an inconsistency in invites/signup for viewers of private sites

#### Steps to reproduce
1. Invite a user to a private site with an email that isn't registered
2. In fresh browser open that link and fill out sign up form and continue

#### What I expected

This step should result in the newly registered user being added straight away to the site

#### What happened instead

On occasion (20% ish of the time) - an additional screen is shown to the newly signed up user requesting that they "Join" the site - see screenshot below of what this looks like for a new user

#### Browser / OS version

OSX Latest Chrome Latest

#### Screenshot / Video

![new user additional dialog](https://cloud.githubusercontent.com/assets/128826/14971122/bd12dfea-1112-11e6-99fe-36695e997aac.png)

**Comment by alisterscott** [comment]
@ebinnion: do you have any ideas about how this one could be happening? A race condition?

**Comment by ebinnion** [comment]
I'm not too sure off of the top of my head, but I'll take a look at it this week.

**Comment by kriskarkoski** [comment]
@alisterscott Has this happened again since #5272 was merged?

**Comment by alisterscott** [comment]
Thanks. I haven't found any instances of this happening since that PR.
