### ISSUE TITLE
Nav Unification: WordPress.com now loads My Site by default instead of Reader

### ISSUE THREAD

**Issue by macmanx2** [Automattic/wp-calypso#51693]
### Steps to reproduce the behavior

1. Go to https://wordpress.com (and log in if you aren't already).

#### What I expected to happen

Prior to nav unification, this would have gone to https://wordpress.com/read when logged in.

#### What actually happened

After nav unification, this loads https://wordpress.com/stats/day for the primary site under My Sites when logged in.

### Context

Reported via https://wordpress.com/forums/topic/new-navigation-oddity/

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

All users affected, default behavior has changed.

**Comment by Aurorum** [comment]
If memory serves correctly, quite a bit of work was undergone to make this happen so I don't _think_ it's a bug. I think it's unrelated to the Nav Unification change since it really was a long time ago: #37547 and #39656.

**Comment by obenland** [comment]
I also thought this is intentional.

@ramonjd Can you confirm that this is indeed the intended behavior?

**Comment by ramonjd** [comment]
Hi folks,

@Aurorum is right: it was a while back now that we set the user's primary site's home as the default landing page for logged-in users. 

`/read` was the fallback, e.g., if the user's account had yet not sites. cc @andrewserong for citation check :D

I can't seem to replicate the redirect to `https://wordpress.com/stats/day`.  For my test account, which has several sites, I am always redirected to `https://wordpress.com/home/{my_primary_site}`.


The report mentions the following:

> My dashboard interface setting is set to “Advanced Dashboard Pages” 

Is this a WooCommerce plugin?

**Comment by macmanx2** [comment]
>> My dashboard interface setting is set to “Advanced Dashboard Pages”
> Is this a WooCommerce plugin?

No, that's https://wordpress.com/support/account-settings/#dashboard-appearance

**Comment by ramonjd** [comment]
> No, that's https://wordpress.com/support/account-settings/#dashboard-appearance

Ah, yes. Thanks! I had that checked already :)

This comment describes what has been the case since [March 2020](https://github.com/Automattic/wp-calypso/pull/39656): https://wordpress.com/forums/topic/new-navigation-oddity/#post-3659479

So, yes the redirect to home is intentional. 👍

**Comment by obenland** [comment]
Thank you!

**Comment by andrewserong** [comment]
> /read was the fallback, e.g., if the user's account had yet not sites. cc @andrewserong for citation check :D
> I can't seem to replicate the redirect to https://wordpress.com/stats/day

Thanks for the ping @ramonjd — yes, the logic lives here: https://github.com/Automattic/wp-calypso/blob/ed3e91545e431da92beeffcbe80289eadde067c0/client/root.js#L69-L69 and roughly goes:

1. If the user does not have a primary site, we default to the reader (`/read`).
2. If the user / site is eligible for the customer home, we redirect to the customer home (`/home/`).
3. If the user / site is not eligible for the customer home, we fallback to the stats page (`/stats/`).

A site will be [ineligible](https://github.com/Automattic/wp-calypso/blob/bbad57e43a740e0d5ea37224b9e4114a2ed8beed/client/state/sites/selectors/can-current-user-use-customer-home.js#L18) for the customer home if it's a Jetpack site (but not Atomic) or if the user doesn't have the `manage_options` capability.
