### ISSUE TITLE
Anchor: Podcast Showing Wrong Episode

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#51706]
### Summary
When adding a podcast with multiple episodes, even if you add the link to the right one, it shows the first one on the site - although it shows the correct episode in the editor.

### Context
We got 2 reports about this, please, check this post for detailed information and troubleshooting steps: p2EDhh-1fu-p2

**Comment by annbingle** [comment]
31202113-hc

**Comment by susanjanec** [comment]
Another report on 31717728-hc  - user is using the Audio block and using the download URL as a workaround.

**Comment by devNigel** [comment]
I have closed the follow-up ticket 4306332-zen for 31717728-hc

Noting down here to update the user via a new ticket once this bug is resolved.

**Comment by sixhours** [comment]
I'm running into CORS issues when I try to embed my test podcast. 🤔 But I'm able to embed other podcasts. 🤷‍♀️ 

When embedding a podcast feed (even if it looks like it's just for a single episode, it's actually pulling the whole feed) it looks like it will always show the X latest episodes, unless you specify which episode you want in the Podcast Settings:

<img width="1666" alt="Screen Shot 2021-10-11 at 11 54 11 AM" src="https://user-images.githubusercontent.com/2124984/136819983-4a5e4085-1cfa-4f73-a19f-59b4e281b65d.png">

So I wonder if this is a mismatch between user expectation and reality? I'm not sure why one episode would show in the block editor and another on the actual page, though.

**Comment by sixhours** [comment]
It makes sense to me that one should be able to paste the URL to a single episode and have it appear as a single episode and not a whole feed, but I don't think that's currently the way it works, so fixing that would be a feature enhancement.

In the meantime, users should be able to select a single episode from the episodes list in the Podcast settings after pasting the initial feed into the editor.

**Comment by sixhours** [comment]
Looked into this further and confirmed:

* We use a core function `fetch_feed` to grab the data for the Podcast Player block
* The RSS feed URL remains the same regardless of whether you're viewing the whole podcast page ([like this](https://anchor.fm/caroline-moore6)) or a single episode ([like this](https://anchor.fm/caroline-moore6/episodes/Episode-3-e18kmhe)); you can find this info in the podcast page's `head`:

<img width="835" alt="Screen Shot 2021-10-12 at 11 47 52 AM" src="https://user-images.githubusercontent.com/2124984/136988431-a722a0ea-5abc-468e-a5d0-efb632928382.png">

From there, users can choose a specific episode from the whole feed to display or tweak other settings in the block, but we don't have a built-in way to pull back just a single episode at first. Lacking an API from Anchor.fm, we could maybe refactor the plugin to compare the requested embed URL with the available feed's podcast titles and intuit that they want to show just one episode. But this feels like a lot of overhead for something that has a relatively simple fix built in.

I'm not sure if we document the Podcast Player block settings, though. I'm going to look into updating the documentation to make this clearer if not.

> I'm not sure why one episode would show in the block editor and another on the actual page, though.

In looking through the plugin code, I found we do cache the feed results (`wp-content/lib/class-jetpack-podcast-helper.php?r=222022#112`) when we display them as a block and through the API, so those discrepancies may have to do with cached values not being cleared.

**Comment by sixhours** [comment]
Confirmed the documentation doesn't address the ability to select a single episode to display:
<img width="750" alt="Screen Shot 2021-10-12 at 12 07 13 PM" src="https://user-images.githubusercontent.com/2124984/136991457-8ef0c1ef-bda3-40f5-8c1d-389689714805.png">

vs. what the user should see:
<img width="287" alt="Screen Shot 2021-10-12 at 12 07 05 PM" src="https://user-images.githubusercontent.com/2124984/136991494-4a866256-2e45-4a37-94e8-befa57dfb3f9.png">

I've updated [the docs](https://wordpress.com/support/wordpress-editor/blocks/podcast-player-block/) to include information about selecting a single episode:

<img width="746" alt="Screen Shot 2021-10-12 at 12 13 41 PM" src="https://user-images.githubusercontent.com/2124984/136992464-da2ec595-d7c9-4e8c-bd3a-f0ca7361660f.png">

**Comment by sixhours** [comment]
Given alllll the above, I'm going to close this out. The best summary is here: https://github.com/Automattic/wp-calypso/issues/51706#issuecomment-941150366

In short, the player will display all episodes by default, but you can select a specific episode in the settings. And updating the feed URL in the block will help clear the cache if there's a discrepancy between the editor and the site's front end. Or just wait about an hour. :)
