### ISSUE TITLE
Media Library Shows "Invalid Date"

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#51709]
A user reported an "invalid date" message instead of an actual upload date. 

<img width="830" alt="Screen Shot on 2021-04-06 at 08-06-04" src="https://user-images.githubusercontent.com/10015451/113708287-09a23280-96af-11eb-87bb-25c9a7e2829b.png">

I can replicate this across both simple and Atomic sites.

**Comment by allanftd** [comment]
Also reported by another user on HC - 22002049-hc (Premium planholder). Thanks!

**Comment by synora** [comment]
Resolved.
