### ISSUE TITLE
Collapse Sidebar: Persist state in Calypso

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#51703]
**Steps to reproduce**

1. Starting at URL: `/home`
2. Collapse the sidebar
3. Refresh the page

Result: The sidebar is expanded

Adding Persistence in the selector will mitigate this problem, since subsequent reloads of calypso will have the same state (eg sidebar collapsed)

**Comment by cpapazoglou** [comment]
While persisting the state is easy, it's not so clear when - how we are going to apply this state after the User lands on Calypso.

### Facts
- We've got two states for the sidebar: Expanded, Collapsed
- Collapsed state is possible only for `>800px` breakpoints
- The sidebar state affects the primary content. Depending on sidebar `width` the content shifts to the left (collapsed) or to the right (expanded)
- While Calypso loads, the background (not the content) of the sidebar appears so that user gets a hint that something is loading. In the same time, the primary content layout is shown.
![](https://cln.sh/j94RsN+)

### The Problem
Whenever the state is different from the default, we will need to apply the new state to the sidebar thus triggering a layout shift

![SS 2021-04-06 at 17 22 19](https://user-images.githubusercontent.com/12430020/113726157-a9d27880-96fc-11eb-80e9-13aa431c0eb0.gif)

So, we either accept this OR we don't show the `sidebar` and `primary` layout sections till calypso  gets the sidebar collapsed state.

**Comment by cpapazoglou** [comment]
You can also check it live here: https://hash-78a3f9d517bb511f54e825117c54c9b78fcf922d.calypso.live/home

cc: @sfougnier

**Comment by tjcafferkey** [comment]
>So, we either accept this OR we don't show the sidebar and primary layout sections till calypso gets the sidebar collapsed state.

It feels like the second option here is most preferable imho for a better experience. What are the trade offs with waiting until we know the state of the layout before determining the sizes of the loading states? Seems like as the state is persisted in cache there shouldn't be much delay when retrieving that value?

Also, how much effort would be involved with this?

**Comment by cpapazoglou** [comment]
> > So, we either accept this OR we don't show the sidebar and primary layout sections till calypso gets the sidebar collapsed state.
> 
> It feels like the second option here is most preferable imho for a better experience. What are the trade offs with waiting until we know the state of the layout before determining the sizes of the loading states? Seems like as the state is persisted in cache there shouldn't be much delay when retrieving that value?
> 
> Also, how much effort would be involved with this?

Never mind, I was too naive. The styles were loading together with the unified sidebar which loaded async. Moving the code to files that don't load async fixed everything.
