### ISSUE TITLE
Horizon Site Editor Flow: New pages always loading in Site Editor after Publish

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51715]
### Steps to reproduce the behavior

1. Visit  Calypso Pages Screen.
2. Add new page titled “Test 1” and publish it in “not-FSE page editor”.
3. Return to Calypso Pages Screen.
4. Click on “Test 1” page to edit it.
5. “Test 1” loads in Site Editor.

1. Visit Calypso Pages Screen
2. Add new page titled “Test 2” and publish it in “not-FSE page editor”.
3. Click View Page in post-publish sidebar to view on front-end in same tab.
4. Click Browser back button.
5. “Test 2” loads in Site Editor.

#### What I expected to happen

Test 1 and Test 2 would load in the editor context in which they were created.

**Comment by jeyip** [comment]
> The Site Editor does not support creating new pages, and our Starter Page Templates functionality also is only activated in the Post Editor, so we have to use the Post Editor for new pages, for now.

I wasn't aware of this earlier, but the described behavior does, in fact, appear to be intentional. See https://github.com/Automattic/wp-calypso/pull/50866

I think we can close this issue 🙂

**Comment by ianstewart** [comment]
Let's close it up. :D
