### ISSUE TITLE
CoBlocks Hero Block: Enable FullScreen Overlapped Contents on Mobile

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#51714]
### Steps to reproduce the behavior

1. Create a [Hero Block](https://blocks.wp-a2z.org/block/hero-coblocks-hero/) with a background image, on a page or post.
2. Enable Fullscreen mode on Hero Block.
3. Publish the content, and visit the page/post on mobile.

#### What I expected to happen

Hero Blocks can be seen nicely, with hero block contents 

#### What actually happened

Contents within Hero block are being overlapped or squished vertically (screenshot below)

### Context

Hero blocks on fullscreen contains the following CSS code:

```
.wp-block-coblocks-hero__inner.is-fullscreen {
    height: 100vh;
}
```

#### Does this happen on simple or atomic sites or both?

AT Sites

#### Workaround

Deactivate fullscreen mode, or apply the following CSS code:

```
.wp-block-coblocks-hero__inner.is-fullscreen {
    height: initial;
}
```

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Result is seen when viewed on mobile.

![image link 2](https://cldup.com/KQgIc3mRJd.png)
image link: https://cloudup.com/c_kPmAs2XMs

Reported in 3881716-zen

**Comment by kriskorn** [comment]
It seems this is happening on Simple with Cover block as well.
Report: 3902043-zen

**Comment by WunderBart** [comment]
We've just upgraded CoBlocks on Simple sites to v2.18.1 which seems to be fixing this issue! 🙌 (p7DVsv-dlk-p2).
