### ISSUE TITLE
i18n: Include string locations in make translate output file

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#5172]
For our translators it would be very useful if the `calypso-strings.php` file contained the actual paths where the string is coming from.

It is likely that this is not possible with the current approach because the strings are actually extracted from the minified files.

It the process it might be useful to switch from generating a PHP file to a POT file.

The contents of `calypso-strings.pot` could look like this:
```
#: client/my-sites/sidebar-navigation/sidebar-navigation.jsx:24
msgid "All Sites"
msgstr ""

#: client/me/sidebar-navigation/sidebar-navigation.jsx:22
msgid "Me"
msgstr ""
```

Generating a .pot file would solve our need to get the file locations into GlotPress at the same time (currently it just says `wp-content/js/jed/calypso-strings.php:4257`).

**Comment by yoavf** [comment]
Related: https://github.com/Automattic/xgettext-js/issues/4
