### ISSUE TITLE
Jetpack Connect: Back to wp-admin link "external icon" indicator

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#5173]
From @beaulebens  review: 

```New window/external link icon feels weird for “Cancel and go back” https://cloudup.com/cxBrdeJpq0N. I know technically it’s an external link, but it feels like a pretty central part of the flow.```

^ ping @rickybanister & @mtias  to discuss

**Comment by rickybanister** [comment]
Let's just remove the external icon. 

I think we can make the link identical to the WordPress.com sign in form.

`Return to %site url%`

<img width="472" alt="screen shot 2016-05-06 at 11 21 09 am" src="https://cloud.githubusercontent.com/assets/437258/15077511/bf4095c0-137c-11e6-9512-b1516f4db83c.png">

**Comment by johnHackworth** [comment]
I'm closing this, since we are not using this screen for wp-admin-initiated connections anymore
