### ISSUE TITLE
"Links" menu missing when custom hidden links are created

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#51745]
### Steps to reproduce the behavior

1. Go to '/wp-admin/link-manager.php'
2. Remove all existing links.
3. Create a new private link (make sure to check the "Keep this link private" setting).

#### What I expected to happen

Since a non-default link has created, the "Links" menu should show up.

#### What actually happened

The "Links" menu is still missing.

**Comment by tjcafferkey** [comment]
Deploy to WPCOM in r223887-wpcom to Simple sites. Atomic sites will get this on May 4th when the next scheduled Jetpack release is.
