### ISSUE TITLE
Top bar: Should front-end match Calypso color scheme?

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#51757]
Continued from #49154

> I think my personal expectation would be for that bar to match my color scheme (especially if wp-admin/calypso are being kept in sync now) because it's part of the logged-in management UI

_Originally posted by @noahtallen in https://github.com/Automattic/wp-calypso/issues/49154#issuecomment-814447171_

This is a fair point, and although the issue in question isn't really a bug, it's something we could discuss and prioritize. Should the front-end top bar match the Calypso color scheme for that user account, since it's technically an admin feature?

**Comment by obenland** [comment]
I think I'd prefer to keep it as is. I'd worry that customers would be confused by a color-schemed toolbar in the front-end, assuming that they're actually still in wp-admin.

**Comment by obenland** [comment]
@lcollette @sfougnier What do you think?

**Comment by lcollette** [comment]
I'd also prefer we leave it as is, mostly because there are higher priority things to work on.
