### ISSUE TITLE
Customizer: Color options are overriding block editor paragraph color options.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#51758]
### Steps to reproduce the behavior

1. Activate a theme that has options for Colors & Backgrounds in the Customizer (the more, the merrier). User report was on Button 2. Other options could be Apostrophe 2 or Dara.
2. Go to Customize - Colors & Backgrounds, and set some non-traditional colors, like a teal background, for example, and some other colors in the palette.
3. Open the editor for a page, add some text (lorem ipsum), and click on Color Settings on the Paragraph Block
4. Instead of normal colors for text, the color options will change to match the palette set in the Customizer, which can result in:

![image](https://user-images.githubusercontent.com/30731356/113910504-c1a60d00-978d-11eb-9d8d-8d6f39395275.png)
![image](https://user-images.githubusercontent.com/30731356/113910429-ae933d00-978d-11eb-9941-3b25307b77e8.png)

#### What I expected to happen
Color Settings on Paragraph Blocks to maintain some traditional colors for text, instead of matching the options set in the Customizer for Colors & Backgrounds

#### What actually happened
User's Color Settings were radically changed.

### Context
This just started happening recently for the user, without any recent changes made in the Customizer. They want a black font color to appear for them in Color Settings, like it used to.

#### Browser / OS version
All

#### Is this specific to the applied theme? Which one?
Multiple

#### Does this happen on simple or atomic sites or both?
It happens on Atomic as well, but there are way more options, including some default/typical ones:
![image](https://user-images.githubusercontent.com/30731356/113911960-73920900-978f-11eb-9bcf-b8ca68d4cc38.png)

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Seems to affect the editor on all sites using themes that have non-generic Colors & Background options set in the Customizer. 
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Screenshots above. 

Possibly related? https://github.com/Automattic/themes/issues/3231

**Comment by khristiansnyder** [comment]
Another report in #28879414-hc

**Comment by happychait** [comment]
28858874-hc

**Comment by happychait** [comment]
28854175-hc

**Comment by jerrysarcastic** [comment]
Also reported in the wpcom public forums at https://wordpress.com/forums/topic/paragraph-text-color-and-background-color-settings-cannot-be-managed/

**Comment by devNigel** [comment]
Another report 8890061-hc

**Comment by Robertght** [comment]
Another one in 

3885393-zen,  3889047-zen

**Comment by druesome** [comment]
28658411-hc

**Comment by fresatomica** [comment]
Another report here: https://wordpress.com/forums/topic/several-problemsbugs-when-editing-pages-and-posts/

**Comment by poojashetty18** [comment]
Another one in 28889670-hc

**Comment by csonnek** [comment]
Originally reported [here](https://github.com/Automattic/newspack-blocks/issues/735#issuecomment-814441333), but it seems more appropriate on this issue.

I can replicate this on any theme including the Twenty themes by going through the following steps:

1. Set custom colors in Customizer -> Colors and Backgrounds for the theme
2. Create a new post in the block editor.
3. Change any colors (background or text) using the options provided: example https://d.pr/i/tZ6ZMw
4. The colors aren't reflected on the front end: example: https://d.pr/i/gP3qkj
5. If you set a custom hex color that is different from the options provided, it does work (see above screenshot for the red text working on the front end): backend https://d.pr/i/VYUdMV

Forums thread for follow up: https://wordpress.com/forums/topic/janky-and-not-working-stuff/

**Comment by supernovia** [comment]
Question for y'all: do the customizer colors you've picked there actually apply outside the editor? I ran into a similar issue yesterday and ended up testing it quite a bit.

Ack. My link keeps getting changed, what up Github? veldatest2 dot wordpress dot com has a post on it.

Here's what I see in the editor:

<img width="1129" alt="Screen Shot 2021-04-07 at 5 53 39 PM" src="https://user-images.githubusercontent.com/3476361/114054046-bb2a9a80-984c-11eb-9e3e-e29830e5f25c.png">

Here's what shows up on the site:

<img width="1129" alt="Screen Shot 2021-04-07 at 5 53 58 PM" src="https://user-images.githubusercontent.com/3476361/114054098-c8478980-984c-11eb-9cb6-db1b8842ac5f.png">

**Comment by kriskorn** [comment]
3889241-zen

**Comment by marcuswisecaesar** [comment]
Themes affected thus far: 
Twenty-Fifteen
Gateway
Olsen

**Comment by khristiansnyder** [comment]
> Question for y'all: do the customizer colors you've picked there actually apply outside the editor? I ran into a similar issue yesterday and ended up testing it quite a bit.

I have had several instances this week where the editor colors do not work on the published version. I've had to go into the code editor to change/remove some of the block styling in those instances.

**Comment by kcswong** [comment]
Follow-up sent in 3892620-zen

**Comment by ericamQA** [comment]
Another example on Ixion theme in 3885193-zen

**Comment by katiebethbrown** [comment]
Another report:
28849736-hc

User had a palette selected in the Customizer that only had a single color, so the custom colors in the editor showed four white circles and one custom color. 

<img width="45%" alt="Screen Shot 2021-04-08 at 2 39 28 PM" src="https://user-images.githubusercontent.com/42279181/114100148-1a0a0700-9881-11eb-8a21-ccc3213d329a.png"> <img width="45%" alt="customcolor" src="https://user-images.githubusercontent.com/42279181/114100163-1ecebb00-9881-11eb-979d-227bd9c99c4d.png">

We had to jump through some hoops to select a new palette and reset the background image (lost when choosing a new palette) so they could have more colors they liked in the editor. They did not want to work with the "custom color" selection option.

**Comment by pauloeaquino** [comment]
Another instance, #3893287-zen

**Comment by davipontesblog** [comment]
Raised as high-priority with engineering teams here: p1617975288125300-slack-C02FMH4G8

**Comment by jffng** [comment]
Potential solution that needs further testing proposed here: pNEWy-dQJ-p2

**Comment by ivan-ottinger** [comment]
Another case: 28906081-hc - the colors don't apply in the front end.

**Comment by jffng** [comment]
We reverted and deployed the change causing this issue for now while we explore a more robust solution to making customizer color palettes available to the editor. 

D59976-code

The default palette in the editor should be restored for these themes, ex twentyfifteen:

<img width="1268" alt="Screen Shot 2021-04-09 at 11 24 39 AM" src="https://user-images.githubusercontent.com/5375500/114203588-289e0000-990d-11eb-9e63-52642336563e.png">

cc @jeffikus @MaggieCabrera

**Comment by jffng** [comment]
To clarify — this issue should be fixed.

@scosgro:

> It happens on Atomic as well, but there are way more options, including some default/typical ones:

I think this is a different issue. The [screenshot](https://user-images.githubusercontent.com/30731356/113911960-73920900-978f-11eb-9bcf-b8ca68d4cc38.png) is the default color palette supplied by the block editor. 

In any case, the custom color options should not be overriding the block editor color palette options in either simple sites or atomic sites now. 

Please let us know if the issue persists, I will leave the issue open for now.

**Comment by davipontesblog** [comment]
Closing as fixed.

**Comment by csonnek** [comment]
Responded to the forums threads.

**Comment by isocialtish** [comment]
This just happened on 30394303-hc using the Maywood theme. 
I walked the user through adding the Custom color hex code instead of clicking on the color options being pulled from the Customizer and that fixed the issue for them in the meantime.
