### ISSUE TITLE
Jetpack Connect: Wrong text in the connection png examples

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#5176]
When we show people diagrams of what to do when we send them over to wp-admin, we refer to the “Connect Jetpack” button, but the one they’re most likely to see is actually “Connect to WordPress.com”; https://cloudup.com/cyJHyznIqDP

**Comment by johnHackworth** [comment]
![image](https://cloud.githubusercontent.com/assets/1554855/14979451/9d448d98-1122-11e6-8a3c-b1a1dcefc7fd.png)

**Comment by folletto** [comment]
> When we show people diagrams of what to do when we send them over to wp-admin, we refer to the “Connect Jetpack” button

For reference, where can I find this text to check? :) 
`/signup/jetpack-connect/index.jsx`. How do I get there?

**Comment by johnHackworth** [comment]
@folletto It's an image, Davide. This one: https://github.com/Automattic/wp-calypso/blob/master/client/signup/jetpack-connect/exampleComponents/jetpack-connect.jsx#L31

https://github.com/Automattic/wp-calypso/blob/master/public/images/jetpack/jetpack-connect-connect.png

**Comment by johnHackworth** [comment]
and @rickybanister already made a new version of those pngs (that we plan to transform to html mockups as soon as we have time), but I didn't committed them yet:

![jetpack-connect__activate](https://cloud.githubusercontent.com/assets/1554855/15427266/2504e092-1e94-11e6-9044-c560ec884c1e.png)
![jetpack-connect__connect](https://cloud.githubusercontent.com/assets/1554855/15427267/2507e7ec-1e94-11e6-9e3d-6197cb6a4d25.png)
![jetpack-connect__install](https://cloud.githubusercontent.com/assets/1554855/15427268/250a13a0-1e94-11e6-8041-62aa9499225e.png)

**Comment by folletto** [comment]
Thanks! :)
