### ISSUE TITLE
Reader: Not able to find or follow WordPress.com or WordPress.com Blog due to errors

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#51786]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/read/search
2. Type in `WordPress.com` or `WordPress.com Blog` and click enter
3. Wait a bit to see the message `Could not get results for query: WordPress.com Blog` or `Could not get results for query: WordPress.com` and no relevant result below
4. Click the `Follow WordPress.com Blog` or `Follow WordPress.com `link that appears below the search field
5. See the errors: `Sorry, there was a problem following http://WordPress.com Blog. Please try again.` or `Sorry, there was a problem following http://WordPress.com Blog. Please try again.`

### Context
p1617880187478500-slack-C025Q5RK2 
cc: @kwight 
#### Browser / OS version
Chrome 89 on macOS BigSur 11.2.3
#### Is this specific to the applied theme? Which one?
No
#### Is there any console output or error text?
```
Failed to load resource: the server responded with a status of 404 () https://en-blog.files.wordpress.com/2021/01/featured-image.png?quality=80&strip=info&w=800
```
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![](https://d.pr/i/IpltwC+)
_Link: https://d.pr/i/IpltwC_

**Comment by kwight** [comment]
It does seem limited to just our site (at least I couldn't replicate with any other sites I tried) – but it's kind of a big site for us to not have working. 🙃 It's also not proxy or a11n-related, I was able to replicate from a separate comp, not proxied, on a regular user account.

**Comment by obenland** [comment]
The feed results do return when lowercasing the search query to wordpress.com or wordpress.org. The follow still won't go through though.

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
