### ISSUE TITLE
Site Info: Badges differ between Calypso and wp-admin

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#51790]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/ and select a site that has not been launched yet (Coming Soon badge)
2. Navigate to Settings > Reading and check the site card
3. See error

#### What I expected to happen

For the badge to be the Coming Soon badge
![image](https://user-images.githubusercontent.com/1398304/114070755-2f693c00-9855-11eb-81bc-465860e13480.png)

#### What actually happened

There are two badges that are not the Coming Soon badge
![image](https://user-images.githubusercontent.com/1398304/114070824-46a82980-9855-11eb-853f-337c1f48f20b.png)

I opened https://github.com/Automattic/wp-calypso/issues/51788 for the color scheme issue.

**Comment by mmtr** [comment]
Seems this one has been fixed, I cannot longer reproduce it.
