### ISSUE TITLE
Site Editor Compatibility: Event Timeline block doesn't use alignment in full site editor

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#51802]
In the new site editor in Gutenberg (/wp-admin/admin.php?page=gutenberg-edit-site), there are some issues with the Event Timeline block on the front end of the site. The block doesn't add an alignment class, so by default is rendered left aligned at full width, instead of within a central container / alignment. The solution might be to add `supports: { align: [ 'center', 'wide' ] }` or something like it, and then make sure the alignment class is [saved out to the block markup here](https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline.js#L120-L120).

### Steps to reproduce the behavior

* On a site running FSE, e.g. create a site via https://horizon.wordpress.com/new?flags=gutenboarding/site-editor and select the tt1-blocks theme (Twenty Twenty One)
* In the site editor, within the footer template part, insert a Timeline block into the Footer template part
* Add some entries and save the template part
* View the front end of the site and observe that the block is rendered left aligned to the edge of the page, instead of being within a central container

#### What I expected to happen
The block to be rendered within a central container by default, as we'd expect with blocks like the paragraph block.

#### What actually happened
On the front end of the site, the block is rendered left aligned against the edge of the page, instead of being visually within the central container of the site, as we'd expect of other blocks.

### Context

Related to 256-gh-Automattic/view-design

#### Is this specific to the applied theme? Which one?
tt1-blocks (the blocks / FSE version of Twenty Twenty One)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low — FSE isn't rolled out yet, so this doesn't affect current production sites.

##### Editor view

![image](https://user-images.githubusercontent.com/14988353/114134515-3a9e9380-994b-11eb-8301-b05cf9125613.png)

##### Front end of the site view

![image](https://user-images.githubusercontent.com/14988353/114134653-70dc1300-994b-11eb-9e96-5df57b9ffcd9.png)

**Comment by ramonjd** [comment]
> tt1-blocks (the blocks / FSE version of Twenty Twenty One)

Reporting on my testing so far, I'm seeing this across both site and block editors on tt1, vesta and seedlet block themes


<img width="400" alt="Screen Shot 2021-04-16 at 3 07 34 pm" src="https://user-images.githubusercontent.com/6458278/114974319-81e5d080-9ec5-11eb-8be6-ca02bfb9508c.png">

<img width="400" alt="Screen Shot 2021-04-16 at 3 03 58 pm" src="https://user-images.githubusercontent.com/6458278/114974092-1439a480-9ec5-11eb-8835-bee4e691e62f.png">


<img width="400" alt="Screen Shot 2021-04-16 at 2 59 40 pm" src="https://user-images.githubusercontent.com/6458278/114974084-11d74a80-9ec5-11eb-8855-44f291b215d8.png">

So it seems to be an existing issue for block themes in general. 

Can't yet replicate on existing non-FSE sites 👍
