### ISSUE TITLE
Permalinks: Do not allow changing permalinks on Free plans

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51819]
### What plan tier is the site on?
Free

### Where are you seeing the issue?

From the menu bar: Settings -> Permalinks

#### What I expected

For it to not be available on a Free plan

#### What actually happened

It's available!

**Comment by tjcafferkey** [comment]
@dereksmart can you please confirm if this issue still exists? I do not have the Permalinks menu item on my free site.

<img width="272" alt="Screenshot 2021-05-07 at 13 15 00" src="https://user-images.githubusercontent.com/8639742/117448175-512e0f80-af36-11eb-9d36-07cd13275f41.png">

**Comment by tjcafferkey** [comment]
I can confirm this happens on Free Atomic sites.
