### ISSUE TITLE
Marketing -> Traffic settings: Fix for Free plans

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51828]
### What plan tier is the site on?
Free

### Where are you seeing the issue?
Marketing > Traffic settings 

Both Google Analytics and wpcom's SEO feature needs consideration when on a Free plan on Atomic. 

#### What I expected on the Atomic site
![image](https://user-images.githubusercontent.com/7129409/114237733-7d636a00-9951-11eb-89bc-4f218aa9892c.png)
![image](https://user-images.githubusercontent.com/7129409/114237760-85bba500-9951-11eb-8dd7-bb671d36b2bc.png)

#### What actually happened
![image](https://user-images.githubusercontent.com/7129409/114237748-82281e00-9951-11eb-8aa0-c5709fcd6939.png)
![image](https://user-images.githubusercontent.com/7129409/114237769-88b69580-9951-11eb-90df-45aae15b1b66.png)

**Comment by mmtr** [comment]
@allilevine FYI, I'm fixing a similar issue in https://github.com/Automattic/wp-calypso/pull/53146, maybe there are some changes there that may be helpful here.

**Comment by allilevine** [comment]
> @allilevine FYI, I'm fixing a similar issue in #53146, maybe there are some changes there that may be helpful here.

Thanks, definitely!

**Comment by allilevine** [comment]
PR here: https://github.com/Automattic/wp-calypso/pull/53196
