### ISSUE TITLE
Akismet: Do not show as a menu option on Free sites

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51827]
### What plan tier is the site on?
Free

### Where are you seeing the issue?
On a Free tier of Atomic, the Akismet menu item is shown in the Jetpack menu: 
![image](https://user-images.githubusercontent.com/7129409/114237040-7c7e0880-9950-11eb-9a4f-c34a540ca1e9.png)

#### What I expected on the Atomic site
No Akismet menu item.

#### What actually happened
Screenshot above

**Comment by BogdanUngureanu** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/52862
