### ISSUE TITLE
Reader: Use `root-child` instead of tertiary, drop the latter

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#5182]
`tertiary` is only still used in `client/reader/controller.js`. @mtias [suggested](https://github.com/Automattic/wp-calypso/pull/5081#discussion_r61571644) we remove it altogether, and replace that one occurrence with `root-child`.

/cc @blowery

**Comment by mtias** [comment]
I think @blowery wants to rip off the whole thing for the reader full post view.

**Comment by blowery** [comment]
might be a first good step though?

**Comment by ockham** [comment]
Looks like it's gone. @blowery Can we close this?

**Comment by blowery** [comment]
Yup!

**Comment by ockham** [comment]
Yay!

**Comment by ockham** [comment]
Ah, found it. For reference: https://github.com/Automattic/wp-calypso/pull/8969
