### ISSUE TITLE
Stats Page: Banners on Free plans 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51822]
### What plan tier is the site on?
Free

### Where are you seeing the issue?
https://wordpress.com/stats/day/SITE_URL

#### What I expected on the WoA site
This Cloudflare banner isn’t seen on Simple, but it is shown on WoA:
![image](https://user-images.githubusercontent.com/7129409/114227131-91ec3600-9942-11eb-909f-c2e5c01b699c.png)

Same with this earn banner at the bottom of the screen:
![image](https://user-images.githubusercontent.com/7129409/114227158-99abda80-9942-11eb-8277-b31cf5ab93c6.png)

**Comment by retrofox** [comment]
I checked that I see the earning banner for a **Simple** site with a **Free** plan:

<img src="https://user-images.githubusercontent.com/77539/118997047-bb937680-b95e-11eb-962c-b095c39e15cf.png" width="600px" />
