### ISSUE TITLE
Media Library: Do not allow uploading of videos on Free plans

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51826]
### What plan tier is the site on?
Free

### Where are you seeing the issue?

https://wordpress.com/media/videos/SITE_URL

#### What I expected on the Atomic site
Not to be able to upload videos.
![image](https://user-images.githubusercontent.com/7129409/114236722-04174780-9950-11eb-8898-cd97f08f7fe8.png)

#### What actually happened
At least the UI is showing that you're able to upload videos. 
![image](https://user-images.githubusercontent.com/7129409/114236750-0c6f8280-9950-11eb-9652-f8316e01a8b3.png)

**Comment by tjcafferkey** [comment]
@dereksmart please can you confirm if this is still an issue? I am not able to replicate and get the expected outcome.

<img width="1790" alt="Screenshot 2021-05-07 at 13 12 12" src="https://user-images.githubusercontent.com/8639742/117447887-f7c5e080-af35-11eb-80d3-587be13fbbb1.png">

**Comment by tjcafferkey** [comment]
I can confirm this happens on Free Atomic sites.

**Comment by allilevine** [comment]
I think this needs a server-side fix. Details here: 100-gh-Automattic/wordpress-seo-premium

**Comment by retrofox** [comment]
> I think this needs a server-side fix. Details here: 100-gh-Automattic/wordpress-seo-premium

I'm not sure about this, Allison. I think we should check whether the Jetpack site is not an Atomic one. [Here the PR](https://github.com/Automattic/wp-calypso/pull/53144).

**Comment by obenland** [comment]
Related: #51593.
