### ISSUE TITLE
Security settings should not be shown to Free plans 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51820]
PRs to review:
- https://github.com/Automattic/wp-calypso/pull/53484
- ~https://github.com/Automattic/jetpack/pull/20384~

### What plan tier is the site on?
Free

### Where are you seeing the issue?

Settings > Security tab: 

https://wordpress.com/settings/security/SITE_URL

#### What I expected on the Atomic site
We should not be showing these security features to Free users. The "Security" tab should be hidden. 

#### What actually happened
They are shown: 
![image](https://user-images.githubusercontent.com/7129409/114226409-88ae9980-9941-11eb-93f9-e576d8be4c7c.png)

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

PR: https://github.com/Automattic/jetpack/pull/20384

**Comment by allilevine** [comment]
Should we hide the Security tab on free Atomic, or all Atomic sites? See pd2C1Z-10-p2

**Comment by allilevine** [comment]
PR to hide the Security Settings page in Calypso: https://github.com/Automattic/wp-calypso/pull/53484
We need to also hide the Security nav item added here: https://github.com/Automattic/jetpack/blob/95a7b30c34fcb57eadc352e03b4b21ab49af5446/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L270
And check that sites return to the default settings on downgrade.

**Comment by allilevine** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/53484 and https://github.com/Automattic/jetpack/pull/20384
