### ISSUE TITLE
Write Button: Make it visually more clear that the number of posts shown to the right is a separate button

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#51834]
**What**
I only recently found out that the number next to the Write button in the WordPress.com toolbar is a separate button! If you click it, it shows the list of the drafts you have.

https://user-images.githubusercontent.com/39308239/114265504-d1c22480-99f9-11eb-9208-f9e9cc06467b.mov

**Why**
Users may not be aware that the number is clickable and it results in a different action than clicking Write. The Write button with the number appears visually as one button, so it's unclear that those are two different buttons actually.

**How**
Maybe add a clearer visual separation with a vertical bar `|` or some other way that is more clear from the usability point of view. A designer's input would be helpful here to propose the best solution.

**Comment by autumnfjeld** [comment]
Blogger Pod:  let's consider this ready for dev even though we will need design approval.   We can do either
 1) take a stab at  adding design clarity then get design approval before shipping  or
 2) reach out to Ola or Ollie to see if they can offer design guidance before starting dev work

**Comment by p-jackson** [comment]
Just noticed this split button type style in the launch flow. It's different (in thise case it's a button attached to an edit box), but thought it was relevant prior art for comparison.

<img width="796" alt="Screenshot 2021-08-10 at 5 00 29 PM" src="https://user-images.githubusercontent.com/1500769/128810760-d50bc341-6a0b-4722-8f53-43ec2457bf09.png">

**Comment by arthur791004** [comment]
@ollierozdarz Do you have any idea for this design?

**Comment by p-jackson** [comment]
An earlier design from #11593 did have a vertical bar separating the buttons, and no oval.

What about something like this?
<img width="248" alt="Screenshot 2021-08-16 at 3 57 58 PM" src="https://user-images.githubusercontent.com/1500769/129511156-4f38ddc6-5671-42fd-bc2d-2c684c6afd4b.png">

I like removing the oval because it starts to feel messy having both the vertical bar _and_ the oval around the number. Does this idea seem worth trying @ollierozdarz?

**Comment by autumnfjeld** [comment]
Looks good to me!  Think its ok to ship. :)

**Comment by p-jackson** [comment]
Heads up, this was not XS 😞 
The masterbar touches a lot more areas than I realised. We have nav-unification to deal with, and Jetpack sites (not on wpcom) can also be using the masterbar.
Happy with the design that we've eventually landed on though.
