### ISSUE TITLE
People: Accepting Invite - Tour message shown

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#5185]
While testing out the people invite flow from the desktop app, and clicking on the subsequent email invitation I was given the following message:

<img width="789" alt="blog_posts_ _fly_fishers_place_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/22080/14990062/bf24e09c-110f-11e6-88a5-76fbcbd39c2e.png">

The bit about being "new" kind of surprised me.  I suppose I am new to the site, but maybe this messaging could look at how many sites a certain user has, and base showing the tour link off of that piece of data?

**Comment by lancewillett** [comment]
Good point — that could be better as a contextual message based on the age of the user's ID, too — how long they've been signed up on WP.com.
