### ISSUE TITLE
Nav Unification: WordPress.com user profile does not match wp-admin/users.php

### ISSUE THREAD

**Issue by sguzovskaia** [Automattic/wp-calypso#51864]
### Steps to reproduce the behavior

This happens when the user has their author bio showing in their blog posts on AT sites.

1. Go to WordPress.com
2. Click on My Profile and then you would change About me field.
OR:
1. Go to My Site > Users > User profile.
2. Edit About me.

#### What I expected to happen
Changes made in the user profile to show in the author bio showing in blog posts.

#### What actually happened
Nothing changes in the author bio showing in blog posts.

### Context
28967719-hc
User had to go to wp-admin/users.php to change the author bio.

#### Browser / OS version
All

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
AT

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low level of impact

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

**Comment by cpapazoglou** [comment]
This will be resolved as part of https://github.com/Automattic/wp-calypso/issues/46077
