### ISSUE TITLE
FSE Round 3 Alpha test - H1 text is white and not visible

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#51883]
At the Update Design screen, the H1 text is white and not visible.

![Screenshot](https://d.pr/i/SXPoDK+)
*if image does not load, please click on this link  : https://d.pr/i/SXPoDK*

![Screenshot](https://d.pr/i/kTsdBQ+)
*if image does not load, please click on this link  : https://d.pr/i/kTsdBQ*

It should be visible so that users know to have to edit it.

The text in other elements are also white.

![Screenshot](https://d.pr/i/yfvDV9+)
*if image does not load, please click on this link  : https://d.pr/i/yfvDV9*

**Comment by Addison-Stavlo** [comment]
this seems to be resolved.
