### ISSUE TITLE
FSE Round 3 Alpha test - Single template contains errors

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#51890]
![Screenshot](https://d.pr/i/cQJAyb+)
*if image does not load, please click on this link  : https://d.pr/i/cQJAyb*

### Steps to reproduce the behavior

1. In Update Design, browse to Single template
2. The template contains errors like `The block contains unexpected or invalid content`, `Attempt Block Recovery`, `Template part has been deleted or is unavailable: post-meta`

**Comment by Greatdane** [comment]
Not sure this is the same bug (this is the only issue that came up when searching);

My Query Block on template pages shows `The block contains unexpected or invalid content` inconsistently. I am unable to reproduce it, it seems random.

There is a console log error in Chrome when it happens;

```
logger.js:11 Block validation: Block validation failed for `core/query` (Object).

Content generated by `save` function:

<div class="wp-block-query"></div>

Content retrieved from post body:

<main class="wp-block-query">
		
</main>
```

Photo;

<img width="2555" alt="Markup 2022-03-08 at 11 01 12" src="https://user-images.githubusercontent.com/5075840/157346254-18189a7f-e103-4162-81f5-9fb4b222c003.png">

**Comment by Addison-Stavlo** [comment]
this original issue seems to be resolved.

@Greatdane 

> My Query Block on template pages shows The block contains unexpected or invalid content inconsistently. I am unable to reproduce it, it seems random.

Thats an interesting block validation error. If you see this again would you mind opening and issue and some more details that might help repro (if you start to see a pattern in what might be causing it).

Was this a query block that existed on a template supplied by the theme? Or one you had added and customized yourself?
