### ISSUE TITLE
Press This doesn't pull the post URL, only the title

### ISSUE THREAD

**Issue by silvio-meter** [Automattic/wp-calypso#51899]
### Steps to reproduce the behavior

1. Go to Settings > General > Writing, and enable "Press This".
2. Open any post and click on "Press This" (without highlighting anything).

#### What I expected to happen

This should open up the Editor inside a pop-up with the post/page URL added inside the post body.

#### What actually happened

Only the post title is pulled, not the URL itself.

Screenshot:

![Optional alternative text if image doesn't load](https://cakebake378932590.files.wordpress.com/2021/04/screenshot-on-2021-04-13-at-16-30-02.png)
--

**Comment by donalirl** [comment]
Follow-up with any updates #4084045-zen

**Comment by kosiew** [comment]
Thanks @silvio-meter , @donalirl for highlighting this issue.

I tested and see the same issue on both AT and simple site.

**Comment by nickpagz** [comment]
FWIW, I also ended up doing some testing on an Atomic site for a user where the button does not work at all for them, and I noticed if I highlight some text before clicking on the **Press This** button, the highlighted text along with the url is inserted as a quote block. So in this regard, it seems to work as described in the instructions shown in Settings > Writing, ie `Use Press This to clip text, images and videos from any web page`.

**Comment by arthur791004** [comment]
@nickpagz Yeah, I agreed with you. I think the original design is that you need to highlight the text before clicking on the **Press This** button as the description said. Maybe we should update the description to ensure people understand that they have to **highlight the text before clicking Press This button**. Or we should assume the user wants to highlight all of the pages without highlighting everything. @silvio-meter How do you think?

**Comment by nickpagz** [comment]
@arthur791004 I think an update to the messaging would be better. Tbh, clicking the Press This button without first highlighting text as a way to copy the entire page content is poor form, IMO, and akin to copying content, even if there's a referral link (which the user may be able to remove before publishing anyways?). Just my 2 cents.

**Comment by arthur791004** [comment]
@nickpagz Yeah, I agreed! Do you have any idea about the new copy?

**Comment by jordesign** [comment]
Is another option to just include the URL of the page as the fallback? It wouldn't be copying the entire content of the page - but it would at least form a post with a Title and Link to the reference page?

**Comment by arthur791004** [comment]
@jordesign I think it's great! We just need to let the user know that the default content will be the URL if they don't highlight any text.

**Comment by marutim** [comment]
A similar issue was reported. In this case, neither the post title or post URL was displayed.

I was able to replicate the same steps.

Screenshot:
<img width="1809" alt="Markup 2021-09-08 at 10 27 02" src="https://user-images.githubusercontent.com/3498917/132456821-58d16d6c-4244-4565-92ca-ee9a396552e1.png">

Chat: 30692153-hc
Follow up ticket: 4281629-zd

**Comment by kosiew** [comment]
The important step that is often overlooked is to highlight some text before clicking on Press This.

From the documentation:

```
... highlight the text you want to grab with your cursor, then click the Press This bookmarklet in your browser. A pop-up publishing window will appear.
```

Source: [Using Press This](https://wordpress.com/support/press-this/#using-press-this)


If the bookmarklet javascript is amended to check selection text, to pull in title when selection is blank, this will work

Excerpt:
```
javascript: (function (e) {
  var t,
    n = document,
    s = window,
    a = s.getSelection,
    o = n.getSelection,
    i = n.selection,
    r = n.location;
  t = a ? a() : o ? o() : i ? i.createRange().text : 0;
  if (t.toString().length < 2) {
      t = n.title;
  }
...
```

![Screen Capture on 2021-09-08 at 18-28-28](https://user-images.githubusercontent.com/29057562/132493857-cc7ed850-3c8b-40d6-a054-75aa79edb254.gif)

**Comment by jordesign** [comment]
So my thoughts here are 'why don't we do both'? Can we

* Improve the handling of situations where no text is selected - so it pulls in the URL as a link/reference?, AND
* Improve the wording of the instructions?

The wording in the support doc is pretty good:

> Simply highlight the text you want to grab with your cursor, then click the Press This bookmarklet in your browser. A pop-up publishing window will appear.

- https://wordpress.com/support/press-this/#using-press-this

Compared to the instructions in Settings > Writing:

> Drag-and-drop the following link to your bookmarks bar or right click it and add it to your favorites for a posting shortcut.

I feel like the instructions in the settings could be extended a little more to explain:
* adding the button to bookmarks bar
* Selecting text and using the bookmark.

We could also include a link to the full support doc there.

What do you think @kristastevens ?

**Comment by arthur791004** [comment]
> Improve the handling of situations where no text is selected 

I think one way is to show an alert to tell our users to select the text. But we cannot show i18n in this case. So I still prefer to notice our users by improving the wording. Also, we can use URL as a default link/reference if our users don't select any of them.

> Improve the wording of the instructions?

Maybe we can step-based approach to guide our users on how to use it? For example,

Here are a few steps to clip text, images and videos from any web page
1. Adding the button to bookmarks bar. You can drag-and-drop the following link to your bookmarks bar or right click it and add it to your favorites for a posting shortcut.
2. Selecting text, images, and videos you want to clip. If you don't select any of them, we would use URL as default text.
3. Clicking the **Press This** bookmarklet in your browser. A pop-up publishing window will appear.

**Comment by kristastevens** [comment]
In looking into this I tested Press This by highlighting some copy and clicking the bookmarklet. A new post modal appeared with the copy, the post title and a clickable URL back to the original post. 👍 

Here's the original copy explaining Press This in Settings > Writing: 


> Press This is a bookmarklet: a little app that runs in your browser and lets you grab bits of the web. 

> Use Press This to clip text, images and videos from any web page. Then edit and add more straight from Press This before you save or publish it in a post on your site.

> Drag-and-drop the following link to your bookmarks bar or right click it and add it to your favorites for a posting shortcut.

Here's some proposed copy that includes an explanation of what it does and (hopefully clearer!) steps on how to use it. Let me know what you think!

***********************

**Press This** allows you to copy text, images, and video from any web page and add them to a new post on your site, along with an automatic citation.

**How to use Press This**

- Drag and drop the "Press This" button below to your bookmarks bar, or right-click the button to copy the link, then add the link to your favourites. 
- Highlight the text or item you'd like to copy into a new post.
- Click on the "Press This" bookmarklet / favorite.

*************************

**Comment by jordesign** [comment]
That copy looks brilliant to me - thanks Krista

**Comment by arthur791004** [comment]
Looks good to me too 👍

**Comment by arthur791004** [comment]
> Improve the handling of situations where no text is selected - so it pulls in the URL as a link/reference?

@jordesign Do we still need to handle this part?

**Comment by jordesign** [comment]
Hey @arthur791004 - I'd love to have that happen as a fallback - but I don't imagine it is vital. If we've got higher priority things - then I think updating the wording would be sufficient.

**Comment by arthur791004** [comment]
@jordesign @kristastevens  I've created a PR to improve this one and here are the results

## Press This Description
<img src="https://user-images.githubusercontent.com/13596067/134858015-b933bdf1-92ef-404d-b5c0-b742d170791d.png" />

## Situation where no text is selected
https://user-images.githubusercontent.com/13596067/134865168-587cec0e-f7ee-4c92-95cf-0cdb45d6c629.mov

**Comment by kristastevens** [comment]
Hi @arthur791004, looks good to me, except for a typo I made. 

Please change "favourites" to "favorites" in the first bullet point. (A British spelling variant crept in. Sorry about that!)

**Comment by arthur791004** [comment]
@kristastevens Okay, thank you!

**Comment by arthur791004** [comment]
@jordesign @kristastevens This change is shipped!
