### ISSUE TITLE
FSE Round 3 Alpha test - Index Template contains error

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#51891]
![Screenshot](https://d.pr/i/5cSjmM+)
*if image does not load, please click on this link  : https://d.pr/i/5cSjmM*

### Steps to reproduce the behavior

1. In Update Design, browse to Index template

Tye page contains `Template part has been deleted or is unavailable: post-meta`

**Comment by Addison-Stavlo** [comment]
this has since been resolved.
