### ISSUE TITLE
FSE Round 3 Alpha test - Site logo size not changing

### ISSUE THREAD

**Issue by tarunvijwani** [Automattic/wp-calypso#51902]
When increasing the site logo size in the header and footer blocks on the front page template, it is not getting changed on the published site.

### Steps to reproduce the behaviour

1. Go to 'Front page template' editor
2. In the header block, add site logo block and add image
3. Increase the size of the block
4. Save the changes

#### What I expected to happen
The size of the site logo should be increased on the published site

#### What actually happened

The size of the site logo is not getting changed on the published site.

#### Screenshots: 

![Xnip2021-04-13_21-19-51](https://user-images.githubusercontent.com/11503784/114583771-8b8def00-9c9f-11eb-9573-1fbcead918bd.jpg)
![Xnip2021-04-13_21-22-33](https://user-images.githubusercontent.com/11503784/114583811-98124780-9c9f-11eb-9d14-09a14f87e8f8.jpg)

**Comment by Addison-Stavlo** [comment]
this has since been resolved.
