### ISSUE TITLE
All My Sites View: Posts and Pages labels do not adjust to multi-site view

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51904]
### Steps to reproduce the behavior

1. Visit WP.com with an account that has multiple sites.
2. Use the nav sidebar to click on Posts or Pages screen.
3. Click Switch Site in sidebar.
4. Click All My Sites in sidebar.
5. See label that refers to single site view on the multi-site screen.

![image](https://user-images.githubusercontent.com/545779/114586188-00363e80-9c4a-11eb-8407-0142225d6246.png)

![image](https://user-images.githubusercontent.com/545779/114586214-07f5e300-9c4a-11eb-8244-69ce881fa423.png)

#### What I expected to happen

The label to update relative to the multi-site management context.

**Comment by obenland** [comment]
@tjcafferkey I think we'll need another "fallback" menu for the "All My Sites" mode?

**Comment by Aurorum** [comment]
PR for this issue in #51950. :)
