### ISSUE TITLE
FSE Round 3 Alpha test - Page list block not available in Style by block type list

### ISSUE THREAD

**Issue by tarunvijwani** [Automattic/wp-calypso#51903]
Page list block not available in Style by block type list

#### What I expected to happen
Page list block should be available in Style by block type to add some style to the block

#### What actually happened
Page list block not available in Style by block type list

![Xnip2021-04-13_21-38-27](https://user-images.githubusercontent.com/11503784/114585128-f2f86e80-9ca0-11eb-9334-3f6a50d77704.jpg)

**Comment by jeyip** [comment]
From what I can tell, in the current version of Gutenberg, the page list block _does_ respond to "List" block style customization in the global styles menu.

![2021-11-08 11 52 02](https://user-images.githubusercontent.com/5414230/140808669-7ec97e82-8172-4ece-8f91-3a324be83de1.gif)

One thing to note, though, is that there are no block-level color customizations available in the block settings menu. I can file a core Gutenberg issue for this request.

![2021-11-08 11 53 03](https://user-images.githubusercontent.com/5414230/140808717-27e63330-75fc-4252-bdf4-0d6568e0fe01.gif)

**Comment by creativecoder** [comment]
Next steps for this issue:

- Open a Gutenberg issue for adding color controls to the Page List block
- Open a Gutenberg issue to propose differentiating Block Level Global Styles for the various List blocks... right now they are all affected by the "List" styles

**Comment by jeyip** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/36537 and https://github.com/WordPress/gutenberg/issues/36539
