### ISSUE TITLE
Support: /help loads at random position when visited from Home Screen

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#51912]
### Steps to reproduce the behavior

1. Go to home screen
2. Click on More help
3. Support screen does not load at top of screen but in random position

![2021-04-13 14 45 39](https://user-images.githubusercontent.com/545779/114612031-3a620900-9c67-11eb-8ad6-4936a5935e1a.gif)

#### What I expected to happen

New screen would load at top of screen.

**Comment by Aurorum** [comment]
PR for this issue in #51914. :)
