### ISSUE TITLE
"Advanced Users Management" option should not appear on Free Atomic Site

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#51928]
### What plan tier is the site on?

Free Atomic Site

### Where are you seeing the issue?

1. Go to https://wordpress.com/home/SITE_URL
2. Click on "Users"

### What I expected 

We should see only "All Users", "Add New", "My Profile" and "Personal Settings":

![Screen Shot on 2021-04-13 at 16:12:55](https://user-images.githubusercontent.com/32432463/114673296-ff340880-9d40-11eb-95cb-1a30cb625edd.png)

#### What actually happened

"Advanced Users Management" option appears. 

This is going to be an issue because users can add users manually through the option and those users added through the option can't get to the site's dashboard properly. On Simple sites, users should be added only through https://wordpress.com/people/team/SITE_URL.

![Screen Shot on 2021-04-13 at 16:19:28](https://user-images.githubusercontent.com/32432463/114673340-09560700-9d41-11eb-8754-0eb6458b1145.png)

**Comment by sixhours** [comment]
There's no longer an "Advanced Users Management" menu item; it looks like it was introduced in https://github.com/Automattic/jetpack/commit/007dfa5db1d36bdb7cf34bc41abf9d260378b004 and removed in https://github.com/Automattic/jetpack/pull/20147
