### ISSUE TITLE
Themes: Active Theme isn't showing on Free Atomic Site

### ISSUE THREAD

**Issue by annbingle** [Automattic/wp-calypso#51930]
### What plan tier is the site on?
Free

### Where are you seeing the issue?

1. Go to 'Appearance > Themes.'
2. The Active Theme details are just showing as blank.

### What I expected on the WordPress.com site
The current active theme should be displayed in the Themes section.
<img width="981" alt="Screen Shot on 2021-04-14 at 16-53-35" src="https://user-images.githubusercontent.com/40605613/114682883-19221b00-9d42-11eb-8f33-e1e0532466d8.png">

#### What actually happened
It shows as blank.
![Themes Blank ](https://user-images.githubusercontent.com/40605613/114683068-4969b980-9d42-11eb-9d53-edf3a5a75963.jpg)

#### Is this specific to the applied theme? Which one?
No, tested it in Radcliffe-2 and Mayland.

**Comment by ianstewart** [comment]
Is this site set up with the same details mentioned in the comment below?

https://github.com/Automattic/wp-calypso/issues/51931#issuecomment-823439238

**Comment by mmtr** [comment]
@annbingle is this issue still reproducible for you? It works as expected on my tests 🤔. It has been probably fixed by 687-gh-Automattic/wpcomsh, so I'm closing this one out. Feel free to reopen if this is still an issue.
