### ISSUE TITLE
Themes: Unable to Change to any themes

### ISSUE THREAD

**Issue by annbingle** [Automattic/wp-calypso#51931]
### What plan tier is the site on?
Free

### Where are you seeing the issue?

1. Go to 'Appearance > Themes > '
2. Select any theme then Activate it. Try either the Free or Premium theme and it will generate an error message.

### What I expected on the WordPress.com site
Will be able to activate a Free theme.

#### What actually happened

Got an error instead.
![Theme Activation](https://user-images.githubusercontent.com/40605613/114684280-5804a080-9d43-11eb-97e5-6285b4f74642.jpg)

#### Is this specific to the applied theme? Which one?
No, Tested it in Radcliffe2 and Mayland (different WPCOM account)

**Comment by zdenys** [comment]
From the screenshot I can see that the site has `wpcomstaging.com` address, so that hints it's an AT (WoA) site but maybe without a WordPress.com Business Plan? Those types of sites need to be reverted first in order to allow theme changes, if I am not mistaken.
