### ISSUE TITLE
Site navigation: Screen Reader not reading sidebar items as links

### ISSUE THREAD

**Issue by michaelnutt2** [Automattic/wp-calypso#51945]
### Steps to reproduce the behavior

1. Go to My Home with screen reader enabled
2. Screen Reader reads sidebar navigation items as list items

#### What I expected to happen
When navigating the page with a screen reader the sidebar navigation would be read as links

#### What actually happened
The screen reader read the text as content on the screen, not as a link that could be clicked

#### Browser / OS version
Chrome 89 / Windows 10

Reported at 28996972-hc, 3908402-zen

**Comment by daria2303** [comment]
another one: 3964395-zd-woothemes

**Comment by worldomonation** [comment]
I tried to reproduce this issue in my environment. Note that I'm not familiar with a11y so if you find issues with my methodology, please do let me know.

- environment: macOS Ventura
- browser: Firefox Nightly 115
- screen reader: VoiceOver

1. enable VoiceOver.
2. navigate to `/home`.
3. press tab until the focus is on the sidebar.
4. cycle through the items in sidebar.

For every sidebar link I cycled though (including top and secondary level links) the VoiceOver utility correctly read out "...link, ...".

<img width="809" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/6dd61a80-bd02-4702-9e7a-4312be0e0fc0">

**Comment by worldomonation** [comment]
https://github.com/Automattic/wp-calypso/assets/6549265/a948e020-22f5-4722-9f2e-ead49c32179d

**Comment by worldomonation** [comment]
@youbrokesomething Did I do the steps correctly? If so, is this still an issue?

**Comment by dsas** [comment]
I tried Chrome and everything seemed ok to me too - though I've not used voiceover before so might have understood something incorrectly.

**Comment by arinoch** [comment]
Sidebar items read as links to me with latest chrome and a screen reader. We could reach out to the affected users and see if they're still having this issue, but I'm inclined to close this as resolved/completed.

**Comment by dsas** [comment]
Lets just close it, looking at the transcripts above from several years ago it's not 100% clear to me that the issue was with this implementation of the sidebar menu. We can always reopen.
