### ISSUE TITLE
Editor settings — Featured image UI differences vs dotorg

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#51943]
Originally reported in p1618262639053800-slack-CRNF6A9DX

### Steps to reproduce the behavior

- In WordPress.com, edit a post
- Click the cog icon in the top right to open the sidebar
- Under the Post tab, open the "Featured Image" section and add a featured image
- Notice differences with dotorg

#### What I expected to happen

The Featured Image section looks and behaves like in the dotorg counterpart

#### What actually happened

- The two-button thing definitely looks wrong.
- The featured image size looks off in comparison.
- There’s some weird interactions with the image replace outside of the visual aspect that I haven’t commented on yet that are maybe related to it being custom?

#### Browser / OS version

All browsers

#### Is this specific to the applied theme? Which one?

All themes

#### Does this happen on simple or atomic sites or both?

All issues appear on simple, but only some on Atomic sites (to be investigated)

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects all sites, but does not prevent users to upload / change featured image

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/1083581/114712877-de63b700-9d30-11eb-8b26-7397f3864f5f.png)

**Comment by ciampo** [comment]
Here's a more detailed analysis of the differences that I've found between WPcom and Gutenberg for the Featured Image section:

| What | Gutenberg screenshot | WPCom screenshot |
|---|---|---|
| No featured image selected | ![Screenshot 2021-04-15 at 16 28 11](https://user-images.githubusercontent.com/1083581/114886126-92d00c80-9e07-11eb-93ec-4861e13e743f.png) | ![image](https://user-images.githubusercontent.com/1083581/114886555-ec383b80-9e07-11eb-9255-2b77e72298d9.png) |
| With featured image selected | ![Screenshot 2021-04-15 at 16 36 30](https://user-images.githubusercontent.com/1083581/114887432-bd6e9500-9e08-11eb-884e-ab6cceb9f683.png) | ![image](https://user-images.githubusercontent.com/1083581/114887702-fad32280-9e08-11eb-872a-ad8aeec1e53d.png) |


### Additional "Selecting a featured image is recommended for an optimal user experience." text when there's no selected featured image (marked with `1` in screenshots)

The additional text seems to come from the [AMP plugin](https://github.com/ampproject/amp-wp/blob/2.0/assets/src/common/helpers/index.js#L82-L122).

### Extra "Select Image" primary button (marked with `2` in the screenshots above)

This button is added by the [Jetpack plugin](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/shared/external-media/index.js#L53-L60), but it seems like a bit of a repetition. The difference with the "Replace Image" button is that, while the "Replace Image" opens the media gallery directly when clicked, the "Select Image" button first shows a dropdown allowing the user to choose between different sources of images

![Screenshot 2021-04-15 at 16 45 37](https://user-images.githubusercontent.com/1083581/114889001-02df9200-9e0a-11eb-950b-1d69be901714.png)

Those same sources can be also selected from the media gallery modal itself, which is why I believe we could simply remove this button from the Featured Image section

![Screenshot 2021-04-15 at 16 47 09](https://user-images.githubusercontent.com/1083581/114889241-39b5a800-9e0a-11eb-97d7-1ced2ff4ee75.png)

### The featured image preview in WPCom does not entirely fill its designated area (marked with `3` in the screenshots above)

By default, the featured image preview uses the `post-thumbnail` version of an image (see [gutenberg docs](https://github.com/WordPress/gutenberg/blob/086b77ed409a70a6c6a6e74dee704851eff812f2/docs/reference-guides/filters/editor-filters.md#editorpostfeaturedimageimagesize)). In Gutenberg, the featured image component first tries to use that value, and [otherwise uses the fallback value of `thumbnail`](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-featured-image/index.js#L69-L74).

I tried uploading the same image to both a .org and .com site:
- On .org sites, the API response for the featured image contains a `post-thumbnail` image `size` that is `1568px` wide.
  ![Screenshot 2021-04-16 at 10 52 38](https://user-images.githubusercontent.com/1083581/114999136-decf8f80-9ea1-11eb-9946-b6e6bf3e7534.png)
- On .com sites, the API response for the featured image contains a `thumbnail` image `size` that is `150px` wide.
  ![Screenshot 2021-04-16 at 10 51 16](https://user-images.githubusercontent.com/1083581/114998914-ad56c400-9ea1-11eb-98b6-b144d3cd29e5.png)

The featured image preview on .dom doesn't have a `post-thumbnail` size, and therefore the `thumbnail` size option is used, which is only 150px. This causes the actual image to be smaller than the preview "area"

![image](https://user-images.githubusercontent.com/1083581/114999911-92d11a80-9ea2-11eb-9f68-36b8888a9afb.png)

The counterproof is that this issue can be hack-fixed by:
- Opening devtool on a dotcom editor page
- In the console, switch window context to `post.php`
- execute this code:  `wp.hooks.addFilter( 'editor.PostFeaturedImage.imageSize', 'my-plugin/with-image-size', () => 'large' );`
- Upload a featured image

**Comment by simison** [comment]
> Those same sources can be also selected from the media gallery modal itself, which is why I believe we could simply remove this button from the Featured Image section

I think there was a project in the past to bring those media source selections to editor canvas for a reason;
- E.g. some sites that aren't iframed (many more as 3rd party cookies become reality) are not getting the Calypso media modal, hence they lose those features.
- They're easier to discover in editor canvas rather than in media library. The dropdown is present also in image block, cover block, etc.

I see it works on my Atomic site likely as intended:

<img width="278" alt="Screenshot 2021-04-16 at 10 11 29" src="https://user-images.githubusercontent.com/87168/114986350-919cef00-9e9c-11eb-962d-1e9b6606651b.png">

<img width="283" alt="Screenshot 2021-04-16 at 10 11 37" src="https://user-images.githubusercontent.com/87168/114986359-95307600-9e9c-11eb-836e-9e53851fc974.png">

**Comment by ciampo** [comment]
> I think there was a project in the past to bring those media source selections to editor canvas for a reason

I see the benefits of adding such a button. But in the context of the featured image, this button is adding a lot of duplicated functionality (e.g. in the screenshots that you posted, clicking or dragging an image on "Set featured image" would already work).

Regarding this this specific matter, what should we do then?

1. We could remove the Jetpack "Select Image" button from the featured image section, and get back to parity with dotorg
2. We can keep the "Select Image" button from Jetpack. If we do so, we could look into improving the current situation by removing the "Replace Image" button when the "Select Image" is rendered.
3. Any other "in-between" approached

Personally, I like option 1 more — it removes complexity and get closer to the dotorg experience.

**Comment by simison** [comment]
I would expect;
- No duplicate "Replace image" button
- Only "Select image" button, but it opens up the dropdown
- Image preview width work just like it does in core

It's not as much a question of .org consistency (after all we have our own custom media library) but more of a question of keeping things consistent across .com. Here's the same feature for image block:

<img width="622" alt="Screenshot 2021-04-16 at 11 40 51" src="https://user-images.githubusercontent.com/87168/114997633-bac37c80-9ea8-11eb-9b22-ace7d0980e96.png">
<img width="393" alt="Screenshot 2021-04-16 at 11 40 41" src="https://user-images.githubusercontent.com/87168/114997637-bbf4a980-9ea8-11eb-98b0-a0894fca764c.png">

Note that the feature isn't shipping to Jetpack sites — only in Jetpack codebase for .com sites (Simple & Atomic).

**Comment by simison** [comment]
> No duplicate "Replace image" button
> Only "Select image" button, but it opens up the dropdown

I looked closer and understood a bit better the crust of the problem:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/87168/115001908-c6b13d80-9eac-11eb-9b09-bb39d1379cf9.png">

- When no featured image is selected, this works well. We have "select image" button with a dropdown appearing.
- When an image is selected, we have two buttons. We should have only "replace image" _with dropdown", no "select image" button.
- There might be some small alignment issues with buttons.

@ciampo does this sound accurate / clear?

**Comment by ciampo** [comment]
> @ciampo does this sound accurate / clear?

I think so. I opened https://github.com/Automattic/jetpack/issues/19555 to track this separately.

I will proceed and do the same to track the preview image size separately too, and then I will close this issue

**Comment by ciampo** [comment]
Opened https://github.com/Automattic/wp-calypso/issues/52010 to track the preview image sizing.

Closing this issue in favour of the 2 smaller issues linked above

**Comment by simison** [comment]
Split another issue to Gutenberg about the blurb above the featured image area: https://github.com/WordPress/gutenberg/issues/30904
