### ISSUE TITLE
Domains: Domain details card layout is hard to read

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#5195]
I noticed this when I went to add a domain to one of my sites. 

Currently the domains settings page `/domains/manage/SITE-URL/edit/DOMAIN` is a bit hard to read, most notably on the domain details card. The label is so far removed from the content it refers to. The label should probably be directly above the content instead of floated left. If space is an issue, there could be two columns of information.

Below is a screenshot of both a mapped domain and a dot-com hosted domain:

<img width="761" alt="screen shot 2016-05-03 at 2 15 13 pm" src="https://cloud.githubusercontent.com/assets/5835847/14997023/0b135018-113a-11e6-899e-69db94ccf978.png">

**Comment by wensco** [comment]
@breezyskies is this something your team could take a look at?

**Comment by breezyskies** [comment]
We have an existing issue for this, including proposed designs here: https://github.com/Automattic/wp-calypso/issues/1737

**Comment by kellychoffman** [comment]
Thanks @breezyskies. Missed that one. Closing this as a dupe.
