### ISSUE TITLE
Checkout: Cart URL redirects to image file

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#51952]
This is really just a minor thing, but I ran into it today and figured I'd report it just in case!

### Steps to reproduce the behavior

1. Visit https://wordpress.com/cart (note: to my knowledge, this is not a URL that we use anywhere, or one that is supposed to work, but is one that people might accidentally try to access from time to time.)

#### What I expected to happen

I was assuming I would probably be redirected to the correct URL for the cart/checkout page, which is https://wordpress.com/checkout

#### What actually happened

I was redirected to https://wpcom.files.wordpress.com/2020/09/cart.png

### Context

I typed in the wrong address from memory while assisting a user and landed there

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Super low

**Comment by sirbrillig** [comment]
Also relevant: Google Chrome notices when you visit a URL like `/cart` and shows it in its default page:
<img width="603" alt="Screen Shot 2022-08-25 at 5 07 47 PM" src="https://user-images.githubusercontent.com/2036909/186769349-cfd0fadd-582d-4e6f-a647-26a1eba42bd1.png">


We might want to consider redirecting this URL explicitly to `/checkout`?

**Comment by spraveenitpro** [comment]
I can take a look at this.

**Comment by michaeldcain** [comment]
From planning:

This is the WordPress-generated media attachment page for the linked image. @MindyPostoff could you let us know if this image is used anywhere before we try to edit it or remove it?

We should try to edit the media attachment page's permalink. If it's not used, we could ask Systems to implement a redirect from `/cart/` > `/checkout`

**Comment by spraveenitpro** [comment]
I have reached out to @MindyPostoff directly regarding this to change the permalink, if that does not work out then we can reach out to systems.

**Comment by spraveenitpro** [comment]
1. The slug of that image has been changed causing the cart image to not appear any more when visiting /cart 
2. Completed the redirection implementation.
3. Tested the redirection for both logged in and logged out situation. @lakellie

**Comment by sirbrillig** [comment]
Nice, I visited `/cart` and it now 301 redirects to `/checkout`!

<img width="349" alt="Screen Shot 2022-09-06 at 5 47 18 PM" src="https://user-images.githubusercontent.com/2036909/188746894-292acaa4-7f87-477f-8cf4-44db60eecb5e.png">
