### ISSUE TITLE
Yoast Integration: Coblocks and Page Optimize plugins activated and usable

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#51956]
### Steps to reproduce the behavior

1. Create a free site
2. Complete the setup the Yoast add-on in SA and enable the Yoast CFT settings.
3. Once the site is made Atomic it may have the Coblocks plugin activated, which is only included with our Business and eCommerce plans. I also see that Page Optimize is activated and we have Page Optimize settings appearing in WP Admin:
`DOMAINCOM/wp-admin/options-general.php?page=page-optimize&return=https%3A%2F%2Fwordpress.com%2Fhosting-config%2FDOMAINCOM`

Here is the list of plugins that are activated on my test site:
![Screen Shot 2021-04-14 at 3 46 28 PM](https://user-images.githubusercontent.com/33190975/114769741-9779bf80-9d38-11eb-894c-6fa79623da3d.jpg)

I'll also note that the Plugins page in nav unification doesn't show these plugins are activated, but they actually are and we can modify the optimization settings and add coblocks blocks.

#### What I expected to happen
None of the Business+ features should be available to customers using Yoast SEO on our free plan.

#### What actually happened
Business plan features such as Coblocks and Page Optimize were added to my free website.

### Context
Team testing

#### Browser / OS version
N/A

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
Free

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Normal

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See above

**Comment by WunderBart** [comment]
Regarding CoBlocks, we've just stopped activating a customized build of that plugin for Simple sites (p4TIVU-9QA-p2). Nevertheless, blogs before the cutoff date would still have that plugin active, which is an expected behavior AFAIK.

**Comment by obenland** [comment]
> None of the Business+ features should be available to customers using Yoast SEO on our free plan.

Let's double-check that these plugins don't get activated when transferring a site with a plan below Business.

**Comment by obenland** [comment]
Page Optimize is part of the Free set (see `atomic_get_plugin_details()`) so I'd expect that to be available to all WoA sites, regardless of plan. 
CoBlocks will only get activated for parity on sites that also had it on Simple.
