### ISSUE TITLE
Yoast Integration: "Install Theme" area can be accessed, but there's no prompt to upgrade when theme installation fails

### ISSUE THREAD

**Issue by annacmc** [Automattic/wp-calypso#51957]
**What plan tier is the site on?**
Free

**Where are you seeing the issue?**

- Go through the process of adding Yoast to a free site
- Go to My Site > Appearance > Themes
- Notice that "Install theme" appears (likely related to: https://github.com/Automattic/wp-calypso/issues/51663)
- Click on the "Install Theme" button in the top right
- Upload a theme .zip file

**What I expected to happen**

Either that this dashboard would not be available for free Atomic sites, or alternatively that an upgrade prompt would be shown to guide users through an upgrade flow before being able to attempt installing a third party theme file.

**What happened instead**

The theme will not be installed, `problem installing theme unauthorized` notice will appear with no further details or prompts to upgrade (likely related to: https://github.com/Automattic/wp-calypso/issues/51759)

![image](https://user-images.githubusercontent.com/30754158/114771232-70ff6700-9dc0-11eb-997b-07564f0a30f5.png)

**Comment by mmtr** [comment]
I cannot longer reproduce this one. Likely fixed by https://github.com/Automattic/wp-calypso/pull/52776
