### ISSUE TITLE
Jetpack Scan: Buttons are a jumbled mess

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#5196]
On one of my sites I have VaultPress active. Inside of my settings area I can see this:

![screen shot 2016-05-03 at 4 34 32 pm](https://cloud.githubusercontent.com/assets/214813/14997632/b28792ba-114d-11e6-8e71-ea1ba60a4b4b.png)

More importantly, this doesn't make sense to me if I have VaultPress active on this site.

*To Recreate*

Navigate to `/settings/security/yoursite.com`

**Comment by designsimply** [comment]
Note: this feature is not yet launched, so you must either be viewing the staging server or use `wpcalypso` to see the problem in action.

**Comment by lancewillett** [comment]
I've seen this jumbled button layout before, too – +1 to fixing it.

**Comment by lancewillett** [comment]
This is a dupe of #4192
