### ISSUE TITLE
E2E: Flaky delete site flow.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#51973]
This spec seems to be flaky so let's try to fix it.

#### Failing spec details

I'm just working on E2E tests locally and I sometimes get this when it reaches the Delete Site flow. Used in multiple spec files. 

Wondering why the alert box sometimes show, sometimes now. Should be an easy fix. Might look into it later.

```
{} There was an error in the hooks that delete test sites, but since it is cleaning up we really don't care: 'UnexpectedAlertOpenError: unexpected alert open: {Alert text : }
  (Session info: chrome=89.0.4389.128)'
```

**Comment by yansern** [comment]
Also now when logging in.

![image](https://user-images.githubusercontent.com/1287077/114851868-f1d35880-9dea-11eb-80c8-603146fba060.png)

**Comment by worldomonation** [comment]
No longer relevant with Gutenboarding gone and also us having moved to use API calls to delete sites.
