### ISSUE TITLE
Design Picker: Add Blank Canvas design option

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#51979]
## What

As a user, I want to be able to skip the design picking step during onboarding and land in the editor, **with a blank canvas**. 

## Why

Give the user the possibility to start with an empty template.

## A/C

* [ ] #52107 is solved
* [ ] Add empty template (https://github.com/Automattic/wp-calypso/pull/50215/files#diff-4b145f851c587a66faeef450d03a5f5b730664b4991e5cf1c38d145fc490c802R6)
* [ ] Add a design to ["available designs" json](https://github.com/Automattic/wp-calypso/blob/3cb4af1850a6b3c7b24b6fe13801ef00930b3984/client/landing/gutenboarding/available-designs-config.json) with `is_alpha: true` key so that it doesn't show up to customers. PR: https://github.com/Automattic/wp-calypso/pull/50215
* [ ] The design should not set a font pairing, and should therefore fallback to the Blank Canvas theme fonts (which are [system fonts](https://github.com/Automattic/themes/blob/1558f1da743be0015273e3818cfbfe163b5f23b2/blank-canvas/variables.css#L7-L8))

### Additional info
Blocked by #52107 (since this should be released first to avoid bugs).

**Comment by ciampo** [comment]
Hey @Automattic/theam , do you have any advice regarding which font pairing (headings + base font) should be used when picking the Blank Canvas design option? (see [example](https://github.com/Automattic/wp-calypso/blob/trunk/packages/design-picker/src/available-designs-config.json#L8-L11) )

Thank you!

**Comment by MaggieCabrera** [comment]
> Hey @Automattic/theam , do you have any advice regarding which font pairing (headings + base font) should be used when picking the Blank Canvas design option? (see [example](https://github.com/Automattic/wp-calypso/blob/trunk/packages/design-picker/src/available-designs-config.json#L8-L11)
> 
> Thank you!

@kjellr can you help here? I think he's not being tagged when you tag theam

**Comment by kjellr** [comment]
The theme uses [our usual System Fonts stack by default](https://github.com/Automattic/themes/blob/1558f1da743be0015273e3818cfbfe163b5f23b2/blank-canvas/variables.css#L7-L8), so I'd prefer to stick to that for both headings + body text. If for some reason we need to use other fonts, I think Source Sans Pro is a reasonable replacement.

**Comment by StefanNieuwenhuis** [comment]
Thanks for helping out @MaggieCabrera & @kjellr! As proposed by @ollierozdarz, we skip the font pairings step in the onboarding flow, so the default fonts will be used. For more details, see #52107.
