### ISSUE TITLE
FSE site creation flow: add blank canvas design option

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#51985]
This technical task is going to fix https://github.com/Automattic/wp-calypso/issues/52172 

**What**
Similar to what we've done in #51979, add Blank Canvas for FSE sites (with `is_fse: true`). 

See also p1619163067291000-slack-C0KDTA48Y for context

**Question**
Does that need a separate, FSE compatible empty template?

**Comment by StefanNieuwenhuis** [comment]
I've closed this issue in favor of #52172.
