### ISSUE TITLE
Store Admin gives a large Atomic WITHOUT BUSINESS PLAN notification on Yoast SEO Premium sites that are not Business Plan sites.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#51995]
### What plan tier is the site on?
The free plan, Personal Plan, Premium Plan

### Where are you seeing the issue?

1. If you go to the Store Admin for a non-Business Plan site that has the Yoast SEO Premium subscription on it, the Store Admin will give a large Atomic WITHOUT BUSINESS PLAN notification on that plan, which is typically evidence of a problem:

![image](https://user-images.githubusercontent.com/30731356/114944036-c73dcb80-9dfb-11eb-8ca8-37294701f307.png)

### What I expected 
The Store Admin notification to be updated to let us know that this is a Yoast SEO Premium site, and that there isn't necessarily a problem.

#### What actually happened
The same notification that appears on AT sites where the plan has been cancelled/expired appears. It's typically indicative of a problem, but there's no issue here, since it's working as intended. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/30731356/114944036-c73dcb80-9dfb-11eb-8ca8-37294701f307.png)

**Comment by mmtr** [comment]
Seems this is no longer an issue. Just made a test on a Free Atomic site with Yoast Premium and this is how SA displays the site:

<img width="1100" alt="Screen Shot 2022-02-08 at 16 24 55" src="https://user-images.githubusercontent.com/1233880/153019231-f946f31e-1b77-430d-8752-c2beed45515e.png">

cc @cpapazoglou
