### ISSUE TITLE
Design Picker: Integrate Blank Canvas custom item in the grid of designs

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#52016]
### What

We want to add an internal prototype flow for a Blank Canvas option in `/new`. 

![image](https://user-images.githubusercontent.com/87168/105397874-4ae78200-5c2a-11eb-9766-7a9af0ff2971.png)

### Why

We want the user to have the opportunity to start a site without any design (i.e. a blank canvas). 

### A/C

* [x] The theme has an _empty_ thumbnail (see the example from Themes showcase: https://cloudup.com/cTv4ZJchXoZ) and this https://github.com/Automattic/wp-calypso/issues/49141#issuecomment-773700429.
* [x] The theme is always the first in the list (i.e. excluded from randomization). We could use the slug (`blank-canvas`) to differentiate.
* [x] The theme's name is `Start with an empty page` and is marked for translations (thus ignoring the value from the JSON configuration) (see [this comment](https://github.com/Automattic/wp-calypso/pull/52113#discussion_r617258812) for more context)
* [x] The `<DesignPicker/>` works with the blank canvas enabled or disabled (use the `is-alpha` flag to differ). 
* [x] Unit tests are written and pass for the blank canvas _edge case_.

### Additional info

Original issue: https://github.com/Automattic/wp-calypso/issues/49141

<s>Blocked by: #51979</s>

**Comment by simison** [comment]
> The theme has an empty thumbnail (see the example from Themes showcase: https://cloudup.com/cTv4ZJchXoZ) and this #49141 (comment).

Latest design; p9Jlb4-2qt-p2 — those other ones you linked were older:

![image](https://user-images.githubusercontent.com/87168/115224348-6c66e580-a115-11eb-8368-834f54257a6e.png)

**Comment by razvanpapadopol** [comment]
@kwight, we assume that Blank Canvas template is not going to be an option for the AnchorFM flavored onboarding. Is this correct?

**Comment by kwight** [comment]
@razvanpapadopol Correct, Anchor flows have their own template automatically assigned.
