### ISSUE TITLE
Reader: Cloudup featured image styles off

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#5202]
After I posted some AFK time today along with an image from Cloudup, I went to the reader and saw this:

![screen shot 2016-05-03 at 9 12 01 pm](https://cloud.githubusercontent.com/assets/1126811/15003683/2a7b64f6-1174-11e6-8007-d2b94c0d2d61.png)

In this case, I would have expected the card to have a white background, but it looks like the `.reader__card.card.tag-afk` class is making the background transparent.

The AFK post right below it looks better:

![screen shot 2016-05-03 at 9 17 27 pm](https://cloud.githubusercontent.com/assets/1126811/15003726/89e22092-1174-11e6-8343-7d5616523886.png)

**Comment by bluefuton** [comment]
Thanks for the report @ebinnion! I think it's the first AFK post we've encountered with a featured image :)

I think the intention with the AFK styles was to display the title only, so perhaps we can just hide the featured image and excerpt in the stream. I'll work up a quick PR.

**Comment by ebinnion** [comment]
I just had to share the tour schedule. 😝 

Looks like the PR fixed it up. 👍
