### ISSUE TITLE
Jetpack Connect: No warning when switching sites

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/wp-calypso#5203]
Test case:
- Logged into wp.com
- Not logged into wp.org
- Jetpack IS activated
- Jetpack is NOT connected

If you go to https://wordpress.com/jetpack/connect and enter the URL of a site which you are NOT logged into, you immediately get taken to the login screen of your site without any warning that you are leaving wp.com

It may not be clear that you are logging into your self-hosted site here.

Perhaps a warning screen would be a good idea, like we already have when logged in but Jetpack is not active, saying something like "We'll need to send you to your site to log in so that Jetpack can connect."

**Comment by johnHackworth** [comment]
do you think we could detect if an user is logged into their self-hosted site with the same kind of tricks/cookie forwarding you proposed to guess if a user is logged into .com, @oskosk ?

**Comment by rickybanister** [comment]
If we can actually detect that, then I'll work up another instruction step for log in.

**Comment by oskosk** [comment]
I'm thinking that more important than the ability to detect if the user is logged in or not, is the warning that should be there instead/too because the user may be logged in with a non-admin user and it could be misleading to them to be redirected to something that won't work for connecting Jetpack

**Comment by johnHackworth** [comment]
@oskosk  you are right, but from wp.com there's no way to tell if the user is logged with a non-admin account! How could we solve that?

**Comment by oskosk** [comment]
Honestly I'd go with a pure warning solution (i.e. no detection) stating: "we are redirecting to your site now and you should be logged with an admin user there for connecting jetpack" offering a ok/cancel flow for allowing the user to log in in another tab and letting them get back.

**Comment by rickybanister** [comment]
The flow is already kind of disjointed with warnings and spinners, I'd rather not add any further ambiguity. 

Could we start by logging any kind of stats here? Can we tell what page referred the user to the Jetpack Dashboard and see how often they are logged out when returned from wp.com?

**Comment by oskosk** [comment]
I think you have a point about first collecting stats. What I don't know is if we have the ability to detect an authenticated request to a WP Admin Page from inside a plugin.

**Comment by johnHackworth** [comment]
I may be wrong, but I think we don't have any way of knowing how many times we redirect someone to their site's login screen (at least without modifying jetpack)

**Comment by rickybanister** [comment]
Let's modify Jetpack then
