### ISSUE TITLE
Welcome Tour: show on all new sites 

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#52049]
**Task Details**
Currently the [Welcome Tour is shown only to new users](https://github.com/Automattic/wp-calypso/blob/1ecd0aae4fbf7772bec647abd2aefea82fe30cd9/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-nux-status-controller.php) when they arrive in the editor for the first time.
Instead we would like to show the Tour in the Editor for _any new site created_, regardless of the status of the user.
(The Tour is also accesible from the Options menu if the user choses to open it again. Although the user wouldn't have any way of knowing that besides poking around the Options menu.)

**Prior ideation:**
https://github.com/orgs/Automattic/projects/147#card-56471157
**Implementation idea:**
new sites can be determined from site creation date

**Related **
This work servers as prep for https://github.com/Automattic/wp-calypso/issues/49048

[Prior Welcome Tour work](https://github.com/orgs/Automattic/projects/147?card_filter_query=welcome+tour#card-42963912)

cc: @simison  @ollierozdarz @StefanNieuwenhuis 

![Screen Shot 2021-04-19 at 13 39 45](https://user-images.githubusercontent.com/5665959/115178500-bef3d200-a114-11eb-9ba7-7e64eaa86d61.png)

**Comment by autumnfjeld** [comment]
I'm estimating this as Ganon Size S (well defined, few days work) based on the idea that we "simply" need to:
* get the site creation date, 
* do  a little time math, 
* determine that the site is new and user is viewing editor for this site for first time
* flag to show the welcome tour
For onboarding flows that drop user into the editor, this is straightforward because the site creation and viewing editor for the first time happen together (meaning there isn't a delay of hours or days from when site is created and the user enters editor for the first time)

Please correct/refine the above if I've oversimplified anything. :)

**Comment by roo2** [comment]
hmm yea it looks like it's not too hard if we do like a _site_creation_time > time_welcome_tour_was_last_dismissed_ comparison.

Although, this would mean that if you create site A, then create site B, then dismiss the tour on site A, you wouldn't see the tour on site B. If we want to solve that problem, I think we would have to implement something on a per-site basis.

I feel like the purpose behind this card is that users who've had an existing site for some time and then make a new one would see the new welcome tour.

And if a user created five new sites, and then dismissed the tour on one of them, I think that we should hide the tour on all of them, rather then making the user go through manually on each new site.

👍

**Comment by autumnfjeld** [comment]
>  I think we would have to implement something on a per-site basis.

Yep, it has to be on a per site basis.  Will need to reliably show the Tour on every new site, regardless of what the user has done before with any site/Welcome Tour.

> I feel like the purpose behind this card is that users who've had an existing site for some time and then make a new one would see the new welcome tour.

100% spot on. 👍   But "some time" might be difficult for us to pin point right now.  We might need to gather feedback after launching.

> And if a user created five new sites, and then dismissed the tour on one of them, I think that we should hide the tour on all of them, rather than making the user go through manually on each new site.

You are right to be considering this scenario 😄 , but I don't think we should worry about this now, unless it is easy to prevent.
The goal is to get the Tour showing on all new sites, there may be odd edge cases like a "professional" WP dev creating many sites for clients within a short time span, but addressing that could be sorted out in another ticket.

@simison @ollierozdarz @StefanNieuwenhuis  Could you chime in so we can properly define the scope of this ticket?

**Comment by roo2** [comment]
> Yep, it has to be on a per site basis. Will need to reliably show the Tour on every new site, regardless of what the user has done before with any site/Welcome Tour.

hmmm I think that if we make the requirement to show on every single new site hard and fast then we will need a more complex implementation, adding a flag to each site to signify if the user has closed the tour _on that site_ yet or not. we'll have to think about sites created before this change and will probably have to handle atomic sites differently then simple sites, make sure the new flag gets migrated in the atomic transfer etc.

The method of testing if _site_creation_time > time_that_welcome_tour_was_last_dismissed_ is a lot simpler and I think it actually achieves the intention of showing the tour to users when it might be useful _better_ than having the tour show strictly for each site.

(AFAIK) The only place that the behavior is different is in the scenario where a user creates several new sites and _then_ dismisses the tour on one of them. if we go with _a flag for each site_, the user needs to close the tour on each site, if we go with  _site_creation_time > time_that_welcome_tour_was_last_dismissed_ the user only needs to close the tour on one of them ( if they have already been created ).

So yea my 2c is it seems like testing if _site_creation_time > time_that_welcome_tour_was_last_dismissed_ is simpler and meets the intended outcome _better_ than a flag for each site.

**Comment by autumnfjeld** [comment]
Summarizing slack & call @roo2 and I had to discuss. 

Is there a way we can do this without considering ` time_that_welcome_tour_was_last_dismissed`?

Something like  `if ( current_time - site_creation_time > N minutes) then showTour`.  
Admittedly, that might not be a robust solution. What other data is available that is an indication of a new site?

I'm thinking of this in terms of this core task:
 “how can we identify that a site is new, and that a user is in the editor of that new site for the first time”

(If we can harness this in-the-editor-of-new-site-for-first-time flag  it could possibly be used for other interesting/educational purposes, not just the Welcome Tour. )

I'll update this task to Size [M] now that we know some trial and error code is probably needed.

**Comment by roo2** [comment]
yep I'll try a draft PR with the `if ( current_time - site_creation_time < N minutes) then showTour` 👍

**Comment by deBhal** [comment]
We could do a pretty direct per-user to per-user-site upgrade by changing the meta key to `$wpdb->get_blog_prefix() . '_wpcom_block_editor_nux_status'`, that'd just leave handling the existing cases.

Handling existing cases depends on how much effort we want to spend on it.

At the heavy end, we could write a job to go through every site for every user and copy the current value into the new one. I don't really think this is appropriate here, but it's an option.

A nice cheap compromise would be to honor the existing flag, so this behaviour change only effects new users. - This seems like an S task to me.

We could ship that, and then consider an additional layer that fires off a cron job to update those user-meta values when we use the fallback (i.e. when a user loads up the editor, we notice that they've only dismissed the tour globally, and we asyncronously copy that value into all their sites). Maybe call this an M sized task?

While we're speccing this, though, I just want to flag that this is a pretty questionable design. We're not your average user, but we're talking about e.g. dismissing the tour on every p2 you post on.

The alternative interpretation is that one person creates the blog and sees the tour while the, say, dozen or so editors and writers on it didn't create the blog and so never see the tour.

Edit: Another implementation option would be to clear the flag as part of the site creation process. Still a weird experience, but logically tidy.

**Comment by roo2** [comment]
created draft PR here https://github.com/Automattic/wp-calypso/pull/52139

**Comment by lsl** [comment]
Both approaches work, I prefer the age of site approach because there is no need to store anything. But if you want the dismiss / view data then its probably going to come down to using meta info:

I'd just upgrade `wpcom_block_editor_nux_status` to be an array of blog id's the user has dismissed the tour on, handle both new and old formats, upgrade any old format user meta you encounter along the way on dismiss. Not really any need for a one off.

> While we're speccing this, though, I just want to flag that this is a pretty questionable design. We're not your average user, but we're talking about e.g. dismissing the tour on every p2 you post on.

Agreed, you could use the count of dismisses present in the upgraded `wpcom_block_editor_nux_status` array to make a judgement call on this, you could also store the time of each dismiss per blog in the option to give you more information, or what I suspect we want it for: showing new versions of the tour to more people.

**Comment by StefanNieuwenhuis** [comment]
> Could you chime in so we can properly define the scope of this ticket?

Absolutely! For the [Blank Canvas Project](pbAok1-27t-p2), the goal is to show the Welcome Tour on every new site, so it has to be on a per-site basis, regardless of what the user has done before with any site/Welcome Tour. So, at least for this project, we shouldn't worry about the odd edge cases of "professional" WP devs.
I guess your Acceptance Criteria (https://github.com/Automattic/wp-calypso/issues/52049#issuecomment-823631346) are spot on and define the scope perfectly 👍
