### ISSUE TITLE
Settings: Default category number bubbles need vertical alignment tweak

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#52071]
### Steps to reproduce the behavior

Found this while working on #50568

1. Go to Settings -> Writing -> Categories on a site that has some posts assigned to the **default** category (other categories are fine)
2. Note the vertical alignment of the number label - the number should be centered in the bubble, but it's quite a bit off:

<img width="759" alt="Screen Shot 2021-04-19 at 1 47 13 PM" src="https://user-images.githubusercontent.com/2124984/115280422-e9925a80-a115-11eb-8ca7-e9cb54a4fec2.png">

#### Browser / OS version

Chrome, Firefox, and Safari for Mac

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low

**Comment by Aurorum** [comment]
PR for this issue in #52072. :)
