### ISSUE TITLE
eCommerce: Customer is unable to access Chat option at https://wordpress.com/help/contact

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#52087]
### Steps to reproduce the behavior

1. SU to this user of this ticket - #3921327-zen
2. Go to https://wordpress.com/help/contact

#### What I expected to happen
Customer sees option to Chat 

#### What actually happened
Customer only sees option to Send Email

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screenshot](https://d.pr/i/ZBsVfL+)
*if image does not load, please click on this link  : https://d.pr/i/ZBsVfL*

**Comment by zdenys** [comment]
Since it's user-specific, I suspect it may be due to the fact that they were blocked in chat as per User Note added on 2021-04-15.

**Comment by kosiew** [comment]
Tested and confirmed that unblocking chat at URC enables chat for Customer.
