### ISSUE TITLE
Gutenboarding Design Previews: uniform scroll speed on hover

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#52085]
Continuing work from  https://github.com/Automattic/wp-calypso/pull/51918

Current:
In the Gutenboarding flow design selection screen,  each preview screenshot is a different height and the way the css animation is currently set up to use a fixed time for the animation,  means the scroll velocity is dependent on the screenshot height.
https://hash-a5b79c626dc0dd48962bca7ea6bef8c8195427f0.calypso.live/new/design?flags=gutenboarding/long-previews

Proposed:
It would probably be better to have a uniform scroll speed on every preview.

**Comment by autumnfjeld** [comment]
cc: @ollierozdarz

**Comment by ollierozdarz** [comment]
I think this is a great idea, @autumnfjeld. Some designs also have no scroll (as you will know!) since they're one page designs.
