### ISSUE TITLE
WordPress.com/Plugins Loads as a WhiteScreen for HE's 

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/wp-calypso#52114]
### Steps to reproduce the behavior

1. Go to WordPress.com/Plugins
2. See the Plugin page briefly, then see it disappear

#### What I expected to happen
The Plugin Page to load, as it does when I add a site URL to the end of the link.
![screenshot](https://d.pr/i/XYQML7+)
[Direct Link](https://d.pr/i/XYQML7)

#### What actually happened
Loading WordPress.com/Plugins/ loads a blank white page:
![screenshot](https://d.pr/i/JxjPjp+)
[Direct Link](https://d.pr/i/JxjPjp)

#### Browser / OS version
Chrome: Version 89.0.4389.128 (Official Build) (x86_64)
Mac OS: 11.2.3 (20D91)

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
![screenshot](https://d.pr/i/RFXW4O+)
[Direct Link](https://d.pr/i/RFXW4O)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Seems to only be impacting Proxied HE's.

**Comment by sixhours** [comment]
This should be fixed by #52115! :)
