### ISSUE TITLE
Nav Unification: inconsistent page linking

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#52123]
### Steps to reproduce the behavior

1. Publish a post or page from the editor
2. Click on the WP icon in the tool bar (upper left) and select all posts/ all pages
3. get taken to the WP Admin version of the page

#### What I expected to happen
should go back to the calypso version for simple sites

#### What actually happened
only after publishing a page you're taken to the wp admin version

### Context
found during empathy testing

#### Does this happen on simple or atomic sites or both?
simple sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://videopress.com/v/pPhhBe6L

**Comment by tjcafferkey** [comment]
Do you have the WP Admin Dashboard Appearance toggle enabled in `https://wordpress.com/me/account` by any chance?

Also the video is private, any chance it can be made public?

**Comment by tjcafferkey** [comment]
@Nic-Sevic any chance you can share some more information on this please?

**Comment by cpapazoglou** [comment]
Had a chat with Nic, the issue is no longer reproducable.
