### ISSUE TITLE
Themes Showcase: Make it easier to find the ability to Search

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#52121]
**What**
It's difficult to search for themes in WordPress.com. How does a user know where Premium themes are? We should change the layout of Themes to help place the search bar and toggles for Premium themes/ Free themes more prominently at the top, along with our "Recommended themes" which are important to show first.

<img width="1193" alt="Screen Shot 2021-04-20 at 2 43 48 PM" src="https://user-images.githubusercontent.com/31009008/115447740-d69b8b00-a1e6-11eb-9d3e-307672f81beb.png">

**Why**
This makes searching for themes easier for users.

**Additional context**
#dogfooding

**Comment by jordesign** [comment]
Does the plan to retire most of our V1 Premium themes impact this? We'll still definitely need to search but it may change the distinction between our 'Recommended' themes and the rest?

Would it be possible for some kind of solution whereby the search field appears above the Recommended Themes and essentially replaces the 'View All Themes' button? If you focus the search field it could reveal the rest of the themes when searching/filtering?

**Comment by jordesign** [comment]
Or another thought... What if the filters became something like:

Recommended | Premium | Free | All

If you had a search form with those filters at the top - and 'Recommended' selected by default it might unify the overall section?

**Comment by kathrynwp** [comment]
Seems like the relevant changes needed to address this have been deployed already - @davipontesblog can we close this?

**Comment by davipontesblog** [comment]
Surely, closing now!
