### ISSUE TITLE
New post email notification: Image Captions displayed to the right of image

### ISSUE THREAD

**Issue by kylemcph** [Automattic/wp-calypso#52144]
### Steps to reproduce the behavior

1. Follow the test site
2. Publish a blog post with caption added to an image block
3. Check the email notification on mobile

#### What I expected to happen

The image captions would be displayed below the image, similar to how displayed on live site. 

#### What actually happened

The caption is instead displayed awkwardly, with part of the caption to the right of the image and part of it below. 

Screenshot of email notification: 

![](https://d.pr/i/nBd0LR+)
Direct link to image: https://d.pr/i/nBd0LR

Screenshot of same captions on live site: 

![](https://d.pr/i/I6BeRU+)
Direct link to image: https://d.pr/i/I6BeRU

### Context

The user points out this is not professional and risk losing followers. 

#### Browser / OS version

I checked my email with Firefox Developer Edition 89.0b2 (64-bit). 

#### Is this specific to the applied theme? Which one?

No, I have tried multiple themes and the result is the same. 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It affects all sites and is unprofessional for bloggers.

3923644-zd-woothemes

**Comment by Robertght** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/63297
