### ISSUE TITLE
Purchases: Show subtitles on /me Purchases screen to match

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#52174]
We recently added subheadings to many pages across Calypso, including `/purchases/[site]`. There's another Purchases screen at `/me/purchases` that has the same content and could benefit from the same subheading. It should read:

`View, manage, or cancel your WordPress.com plan and other purchases.`

The subheading should probably also be present on the Billing History and Payment Methods screens in the `/payments` section:

<img width="1090" alt="Screen Shot 2021-04-21 at 3 54 32 PM" src="https://user-images.githubusercontent.com/2124984/115613057-f354c300-a2b9-11eb-82ca-ca9999c77133.png">

pbAPfg-1iV-p2#comment-3017 /cc @donalirl

**Comment by michaeldcain** [comment]
@sixhours - happy to grab this (or use it for some new dev onboarding on Payments).

> It should read: View, manage, or cancel your WordPress.com plan and other purchases.

Should the sub-title be specific to the tab within the section? That sub-title fits the "Active Upgrades" tab, but not so much the Billing History (just a list of receipts), and the Payment Method tabs.

**Comment by sixhours** [comment]
> Should the sub-title be specific to the tab within the section?

Yep, that makes sense. We did change it for sub-tabs in a couple other places IIRC.

**Comment by michaeldcain** [comment]
@DavidRothstein pointed out that `View, manage, or cancel your WordPress.com plan and other purchases.` is technically incorrect for non-WPcom plan management (Jetpack, Recurring Payments). When we add the other sub-titles, let's fix that to read "View, manage, or cancel your plan and other purchases."
