### ISSUE TITLE
Site Editor: add Blank Canvas and Blank Canvas Blocks themes

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#52172]
### What
We need to add Blank Canvas and Blank Canvas Blocks themes to the FSE Horizon flow in a similar fashion as TT1 Blocks, Mayland Blocks, and Seedlet Blocks.

Here are the required steps:
1. Add Gutenboarding site designs for **both** designs(see PCYsg-r7w-p2): 
    * Add a new “Blank Canvas Blocks” design to /new.
    * Add a new Gutenboarding site design.
    * Create a new starter site where the design lives.
    * Send the starter site out for translation.
    * Generate Headstart annotations.
2. Update the WPCOM API by opening a diff (example: D59752-code) for `blank-canvas` & `blank-canvas-blocks`.
    * Add headstart annotations JSON file for both designs to `wp-content/lib/nux-helpers/gutenboarding-content`
    * Add both starter design sites to the `$starter_design_sites` array in `wp-content/lib/nux-helpers/class-nux-starter-designs.php` (line 23).
3. Use the new `blank-canvas-blocks` design in New Onboarding for the FSE flow.

### Why
The FSE Horizon flow is up for its 4th round of testing, and to make the experience complete, the blank canvas design needs to be added as well. 

### A/C
* [x] Starter designs and annotations are created   
  * [x] Gutenboarding site design is created for Blank Canvas. `blankcanvasdesignsite.wordpress.com`
  * [x] Gutenboarding site design is created for Blank Canvas Blocks. `blankcanvasblocks.wordpress.com`
* [x] WPCOM API is updated.
  * [x] D61115-code Blank Canvas headstart annotations JSON is added to `nux-helpers/gutenboarding-content`
  * [x] D61115-code Blank Canvas starter is added to the NUX starter design sites array.
  * [x] D60806-code Blank Canvas Blocks headstart annotations JSON is added to `nux-helpers/gutenboarding-content`
  * [x] D60806-code Blank Canvas Blocks starter is added to the NUX starter design sites array.
* [x] (https://github.com/Automattic/wp-calypso/pull/52295) Add `blank-canvas-blocks` design option to Design Picker with `is_fse` flag

### Additional details
More details are found in p1619163067291000-slack-C0KDTA48Y. The URL to the flow is found here as well.

Screenshot of the currently added themes: 

<img width="1786" alt="Screen Shot 2021-04-21 at 8 59 52 PM" src="https://user-images.githubusercontent.com/1182160/115606855-8acf0b80-a2e4-11eb-9a30-c535104563ec.png">

**Comment by StefanNieuwenhuis** [comment]
> Create a new starter site where the design lives.

@yuliyan, since we're creating empty starter sites (since they don't have content), do we need to send it for translation?

**Comment by yuliyan** [comment]
@StefanNieuwenhuis, I'm not sure if I understand the question correctly. If there'll be no content, then no strings will be extracted and sent for translation.

**Comment by StefanNieuwenhuis** [comment]
> @StefanNieuwenhuis, I'm not sure if I understand the question correctly. If there'll be no content, then no strings will be extracted and sent for translation.

Thanks for your quick reply! The designs we're adding are completely empty so nothing has to be translated, but looking at the example diff (D59752-code), I realize that some metadata requires translation too. So we'll send it out for translation :)

**Comment by razvanpapadopol** [comment]
With D61115-code and D60806-code deployed we need only to merge #52295 for a fully working FSE Blank Canvas design option.

**Comment by vindl** [comment]
> With D61115-code and D60806-code deployed we need only to merge #52295 for a fully working FSE Blank Canvas design option.

Thanks for the update @razvanpapadopol, and @Automattic/luna for you work on this! 🚀

**Comment by razvanpapadopol** [comment]
We can consider this issue done since Blank Canvas experience is available in `/new`:
- default: https://wordpress.com/new/design
- with FSE flag: https://wordpress.com/new/design?flags=gutenboarding/site-editor

As a follow-up, I've created #52744 to add support for FSE site creation in `/start`
