### ISSUE TITLE
Editor: Update Permalinks and Excerpt "Learn More" Links

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#52191]
### Steps to reproduce the behavior

1. Go to the WordPress editor
2. In the Page/Post settings sidebar on the right, look for 'Permalinks'
3. Click the link "Read about permalinks(opens in a new tab)"
2. In the Page/Post settings sidebar on the right, look for 'Excerpts'
3. Click the link "Learn more about manual excerpts(opens in a new tab)"

#### What I expected to happen

I expected to be taken to a WordPress.com resource.

#### What actually happened

For permalinks, it took me to:

https://wordpress.org/support/article/writing-posts/#post-field-descriptions

For excerpts, it took me to:

https://wordpress.org/support/article/excerpt/

### Proposed change

It would make more sense to link to the WordPress.com help docs:

https://wordpress.com/support/permalinks-and-slugs/

https://wordpress.com/support/excerpts/

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects all sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/30727666/115681079-86175f80-a397-11eb-8165-0bcc7db1d100.png)

![image](https://user-images.githubusercontent.com/30727666/115680423-e22db400-a396-11eb-80b2-0f479a51115d.png)

**Comment by donalirl** [comment]
Closed in favor of p2rHU0-Tk-p2#comment-2738

**Comment by formosattic** [comment]
This makes a lot of sense as our doc is adapted to the experience on WordPress.com.

**Comment by dpasque** [comment]
Switching prioritization to Normal for now due to the ability to still find these docs when searching WordPress.com support, and that the .org docs still have relevant, although not the best, information.

**Comment by dpasque** [comment]
Actually, nevermind, I think this should go back to High, my apologies for the back and forth! Inline help is a big push for us right now, and I think it's pretty important to make sure we are directing people towards the docs that are most tailored to the .com experience.

**Comment by donalirl** [comment]
Hello @dpasque @escapemanuele 👋 

It looks like this reverted at some point. The links are linking to .org docs again in the editor on both simple and atomic:

![image](https://user-images.githubusercontent.com/30727666/191175645-26d7ced5-a55d-45d8-846c-b49479f0b9bb.png)
Links to: https://wordpress.org/support/article/settings-sidebar/#permalink

and:

![image](https://user-images.githubusercontent.com/30727666/191175691-ed4a1781-2eef-4918-834f-07bb75f9b7b7.png)
Links to: https://wordpress.org/support/article/settings-sidebar/#excerpt

**Comment by escapemanuele** [comment]
Hey @donalirl, I see that also the link text changed ( From `Read about permalinks` to `Learn more` for example). So I suppose that someone changed the links in core and now in calypso we fail to intercept those new links.
I'll open a new PR for these links.

**Comment by escapemanuele** [comment]
Hi @donalirl, [a PR](https://github.com/Automattic/wp-calypso/pull/68446) has been opened for this 👍

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closing as solved - looks like this just never was closed after it was fixed by https://github.com/Automattic/wp-calypso/pull/62056

**Comment by donalirl** [comment]
Sorry @cuemarie I just checked and Excerpts is still linking to the dotorg URL:

<img width="345" alt="Screenshot 2023-10-05 at 11 31 30 am" src="https://github.com/Automattic/wp-calypso/assets/30727666/13142809-df63-4004-9223-0f5cc60fb9f0">

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO

The learn more link is still linking to https://wordpress.org/documentation/article/page-post-settings-sidebar/#excerpt 

📌 ACTIONS
- Kept the issue open.

**Comment by cuemarie** [comment]
No need to say Sorry, @donalirl, thank you for reopening! I think I checked the wrong link on my site, so I'm glad you caught that! 😃

**Comment by autumnfjeld** [comment]
@cuemarie  is there still work to be done here?   Lego team can take a look if so.

**Comment by escapemanuele** [comment]
I just checked and the link points to `https://wordpress.com/support/excerpts/`, so it should be good!

**Comment by arthur791004** [comment]
Checked and both links point to the WordPress.com help docs as well 🙂
