### ISSUE TITLE
Replace Editor Help Link with WP. com Resource

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#52190]
### Steps to reproduce the behavior

1. Go to the WordPress editor
2. Click on the three vertical dots in the top-right corner
3. Scroll down to Help and click it

#### What I expected to happen

I expected to be taken to a WordPress.com resource.

#### What actually happened

It took me to:

https://wordpress.org/support/article/wordpress-editor/

### Proposed change

It would make more sense to link to the WordPress.com editor help doc:

https://wordpress.com/support/wordpress-editor/

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects all sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/30727666/115678981-70a13600-a395-11eb-8c50-e6f419b22704.png)

**Comment by donalirl** [comment]
Closed in favor of p2rHU0-Tk-p2#comment-2738

**Comment by formosattic** [comment]
This makes a lot of sense as our doc is adapted to the experience on WordPress.com.
