### ISSUE TITLE
Editor: Users cannot edit post with error "Sorry, you are not allowed to edit this post."

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52209]
Some users since early April 2021 have started seeing the error "Sorry, you are not allowed to edit this post." when using the block editor.

There was [long-standing issue](https://github.com/Automattic/wp-calypso/issues/45881) that we believed fixed, but reports have started cropping up again of the same error. When adding a report, please try to determine their browser, whether they were in Gutenframe (the URL of their editing session), and if clearing cookies helped at all. If the user can get a screenshot of the actual error, it might help narrow down potential causes further.

**Comment by kwight** [comment]
Copied from https://github.com/Automattic/wp-calypso/issues/45881 since April 2021:

11649536-hc
https://wordpress.com/forums/topic/i-hate-the-new-editor-2/
9086584-hc
3911399-zen

**Comment by metabreakr** [comment]
23368054-hc

Browser: https://www.whatsmybrowser.org/b/3FE1H

**Comment by katiebethbrown** [comment]
Another report in 17894378-hc

Simple site. User editing in wp-admin. Asked for more detail but they left.

**Comment by happychait** [comment]
13043817-hc

Suggested to clear browser cache and cookies and let us know if that doesn't help.

**Comment by jp-imagines** [comment]
12429662-hc

Simple site, using Chrome 90.0.
Clearing cache resolved the issue.

**Comment by metabreakr** [comment]
29512842-hc

Advised they clear their cache.

**Comment by jp-imagines** [comment]
1649344-hc

Simple site.
Blank editing screen in Safari 14.1. "Sorry, you are not allowed to edit this post" error showed up in Chrome 90.0.
Clearing cache has temporarily worked.

**Comment by retnonindya** [comment]
28925731-hc

Simple site.

And, I'm not sure about the error, but here goes...

First error: The user mentioned the text "Updating failed. Sorry, you are not allowed to edit this post" appears *within the sentence/paragraph* of their blog post -- in contrast with the usual pop-up/modal.

Second error: The error displayed using banner as usual.

As of now, I suggested them to clear browser cache.

Browser: Safari 14.1 on Mac OS X 10.15.7 
Editor link: Calypso (`https://wordpress.com/post/...`)

**Comment by supernovia** [comment]
Noting I've seen another case where people are getting this when trying to edit a page. edit.php lists the affected page as the posts page with a little round ℹ️  icon and says it cannot be edited. But Customizer does not list that page as the posts page.  It's probably a different issue, but as it has the same error I will note it here as well:
3960837-zd-woothemes

**Comment by desnum** [comment]
**INTERACTION**: 21281692-hc, simple site.

**ISSUE**: when editing the homepage it says: "Sorry, you are not allowed to edit this item."

**NOTICED**: Toggled on advanced WP Admin settings and saw an info bubble that says "The content of your latest posts page is automatically generated and cannot be edited" next to the homepage

**WORKAROUND**: created a Posts Page and set it in Homepage Settings so that the homepage could be editable

**Comment by carinapilar** [comment]
The recent reports seem to be a new issue. It seems some kind of conflict with this new (it seems to be new) _"The content of your latest posts page is automatically generated and cannot be edited"_ message in WP-Admin, somehow conflicting with Calypso's interface.

This is happening at some point when what you have in Calypso doesn't match the Reading settings for homepage/blog pages, you make changes to that, either on WP-Admin or the Customizer, and sometimes Calypso isn't reflecting those, and when it doesn't it sends the user trying to edit the Blog page to a link like this:

`https://[site's URL]/wp-admin/post.php?post=ID`

Even though the user isn't trying to edit on WP-Admin, it's from Calypso, and it shows this message:

![Screen Shot 2021-05-26 at 11 39 00](https://user-images.githubusercontent.com/16104522/119679776-0279e400-be17-11eb-83af-1856847a2ddb.png)

Here are another 2 reports:
4018894-zd-woothemes
4019020-zd-woothemes

It seems to fix if you set the homepage and blog pages again in the Homepage Settings in the Customizer, or the Reading settings on WP-Admin.

**Comment by lizswafford** [comment]
Interaction: 29358550-hc simple site

Issue: The homepage cannot be edited. 

Error: Sorry, you are not allowed to edit the item.
Error: The content of your latest posts page is automatically generated and cannot be edited. 

Workaround: create or assign a new page to be the homepage, assign a posts page. 
This allows the original homepage to be edited.

**Comment by carinapilar** [comment]
The issue related to homepage/posts page settings, from the reports above, is now here: https://github.com/Automattic/wp-calypso/issues/53167

**Comment by as-esu** [comment]
Another report here: 4021406-zd-woothemes
The user has only a homepage set in Customizer, the Blog post page is set to empty.
I asked the user to change homepage and blog post page settings in Customizer and try to edit the page again.
The error message does not seem to be related to a browser since the user tried to open the page in two different browsers as well as the mobile app.

**Comment by chrism245** [comment]
3147099-hc simple site.
Suggested to clear browser cache and cookies, and they will contact us once they can do it.

**Comment by happychait** [comment]
User from [three days ago](https://github.com/Automattic/wp-calypso/issues/52209#issuecomment-847470017) returned to report the same issue in 29829242-hc. 

Clearing cache in Safari did not help. I suggested trying Firefox.

**Comment by kwight** [comment]
Tagging @obenland FYI, and @taggon for Flow Patrol consideration.

**Comment by edwinho89** [comment]
4040672-zen simple site.

Affected user is on Windows WordPress.com desktop app v6.15.0 which is interesting.

Had asked user to logout, then login again if it helps (as an act of clearing cache)

**Comment by jp-imagines** [comment]
29972536-hc

Simple site. Chrome 91.0 on Windows 10. Clearing cache did not resolve the issue.
User was able to edit by switching to Firefox.

**Comment by daria2303** [comment]
Problem appears in the Desktop App too, clearing cache did not help, settings for homepage are the same in wp admin and customizer
4051894-zd-woothemes

**Comment by JessBoctor** [comment]
Had this come up in #22628165-HC. Clearing the browser cache didn't resolve the issue. 

Following up in 4071380-ZD to ask the customer to log out and back in, check anti-virus, etc

**Comment by galakhyati** [comment]
Another case. They are on a simple site and the error was shown when they were trying to save the changes.

Asked them to clear the cache and check.

4063500-zd-themes

**Comment by CodeAllNightNDay** [comment]
A simple site where the user is getting the "Updating failed. Sorry, you are not allowed to edit this post" message.
They are still using the classic editor for all posts. Using chrome on an older Mac with OS X 10.10.5 installed

The user is not able to edit or schedule posts.

Clearing chrome cache did not help. I'm not able to reproduce the issue on my end.

29534711-hc

**Comment by rinazrina** [comment]
Another case on simple site: 2676375-hc | 4193547-zd-woothemes
Didn't get the chance to ask about their browser details. Suggested to clear cache and cookies. Screenshot of the error below:

![Markup 2021-08-03 at 12 21 56](https://user-images.githubusercontent.com/33721365/127957364-bc4568f7-6e82-4b67-af84-fceaad678d92.png)

**Comment by jp-imagines** [comment]
Another report on a simple site: 23146975-hc / 4198811-zen
User on Chrome 92.0 on Mac OS X 10.13.6.

They were seeing the "Sorry, you are not allowed to edit this post error." at times, but also were able to access the editor but *unable* to publish a draft post other times.
They also mentioned that sometimes the editor wasn't loading for them at all.

Switching to Safari resolved these issues.

**Comment by liviopv** [comment]
Simple site #20721183-hc / #4209435-zen

I wasn't able to reproduce it, but the user experiences this consistently on Chrome and managed to reproduce it on Edge as well.

Homepage Settings are set to Latest Posts, and resaving the settings doesn't fix the issue either.

I asked for a screenshot and detailed browser info.

**Comment by cuemarie** [comment]
Another issue, simple site: 31168527-hc / 4231915-zen
Chrome, editing in wp-admin. Working on detailed browser info and helping them download a different browser to try for now.

**Comment by Robertght** [comment]
Another case in #4209435-zen

```
Windows 10 (64-bit)
Web Browser Chrome 92.0.4515.131
Browser Size 1366 x 625
Javascript Yes
Cookies Yes

User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/92.0.4515.131 Safari/537.36

```

**Comment by katiebethbrown** [comment]
Another report in 29241258-hc

Chrome. 

We checked third-party cookies, cleared cache/cookies, refreshed the page (what they said worked previously) all with no success.

**Comment by rinazrina** [comment]
Additional info from the same user as @katiebethbrown report above -- 29241258-hc and 31322930-hc

1) Browser and OS: Chrome 92 on Windows 10 - browser info: https://www.whatismybrowser.com/w/AN3XHDS
2) What's the date on which that issue was first noticed? 4 months ago. Looks like it's intermittent. 26071168-hc
3) Which method do you use for logging in (password / social / magic link)? password
4) Do you use a VPN or Proxy? No 
5) Do you have antivirus that blocks cookies? They use McAfee but it's not blocking cookies.

**Comment by Robertght** [comment]
Is this something @Automattic/flow-patrol-create can take a look at?

**Comment by liviopv** [comment]
More info about  29241258-hc and 31322930-hc and now 31335467-hc:

- Firefox works
- The user has several different sites on the account, but the only one affected by it is http://neighborsofpinehurst.com
- The issue is still present after setting a Posts Page

**Comment by fstath** [comment]
This is happening when copying a post.

- OS: Windows 10 (64-bit)
- Browser: Chrome 92.0.4515.159
- Forum post: https://wordpress.com/forums/topic/copy-post-fails-to-save-still-not-fixed/

**Comment by carinapilar** [comment]
Another report: https://wordpress.com/pt-br/forums/topic/erro-ao-salvar-alteracoes-no-post/ - asked to clear cache, or try a different browser.

**Comment by renata-franco** [comment]
New report here: 30193600-hc. User was using Brave browser. 
They changed to Firefox and the issue stopped. 31438850-hc

**Comment by darnelldibbles** [comment]
Another report in https://wordpress.com/forums/topic/a-fantastic-morning/
Clearing cache did not fix the issue, but Microsoft Edge worked.

Generated link: https://www.whatsmybrowser.org/b/GHZKG

**Comment by darnelldibbles** [comment]
Another report in: https://wordpress.com/forums/topic/you-are-not-allowed-to-edit-this-post/

Generated link: https://www.whatsmybrowser.org/b/QUEHW

**Comment by edwinho89** [comment]
29779279-hc

Generated link: https://www.whatsmybrowser.org/b/0D8Y1

User mentioned they were using Brave browser

**Comment by JuniorTak** [comment]
Another report 4292541-zen

Asked to clear the browser cache and follow the browser troubleshooting steps. But, the issue persists.

**Comment by sajmes** [comment]
Possible report here: 4298932-zd-woothemes

**Comment by poeticabdul** [comment]
Another report here: 4638679-zen

Suggested they clear their browser cache and if it persists try in Firefox or Safari browsers.

**Comment by happychait** [comment]
Another report in 34469269-hc

**Comment by KirkwallDay** [comment]
Another instance here: 16776065-hc

The error they got was: Publishing failed. Sorry, you are not allowed to assign the provided terms.

Flushing the site cache and having them add the tags onto the post did work in this case.

**Comment by fetenlakhal** [comment]
Another one here: 5352488-zd

**Comment by jordesign** [comment]
With only 3 reports here in the last year (and presumably no follow-on from those) I'm going to close this issue.
If we start to see more reports we can always open it again.

**Comment by thekingsprojects** [comment]
Had what looks like another case here:

37738694-hc

Lost touch with the user at the end, but it sounds like logging in in incognito mode helped while we were talking, so I asked them to clear cache/cookies.

**Comment by mahfuzurwp** [comment]
7548591-zen
