### ISSUE TITLE
Site Editor: cover block nested blocks alignment

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#52208]
In our internal testing round the following issues was reported:

> For some reason a Cover block only allows me to add content to the right-side half of the block area? I would like to add some content center-aligned to take advantage of the block area, but there doesn’t seem to be a way to do this.

cc @davipontesblog 

<img width="710" alt="screen-shot-2021-04-06-at-15 20 17" src="https://user-images.githubusercontent.com/1182160/115775459-30e94700-a3b3-11eb-84ca-1798f917186c.png">

We need to triage this and figure out if it's a theme issue (TT1 blocks) or something related to the editor and file issues and PRs in appropriate repos for it.

**Comment by davipontesblog** [comment]
@vindl I had a feeling this was already fixed, and I am pretty sure it has: https://github.com/Automattic/wp-calypso/issues/51670
I also can't replicate the issue anymore on Horizon.
