### ISSUE TITLE
Use existing Anchor FM Accounts with anchor integration

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#52213]
### Steps to reproduce the behavior

1. Go to https://anchor.fm/wordpressdotcom
2. Click on 'Get Started

#### What I expected to happen

Be able to choose between an existing AnchorFM account and creating a new one

#### What actually happened

You can only use a new one

### Context

Customer requested to be able to use their existing account in #28638245-HC

**Comment by inaikem** [comment]
Thanks for the feature request, Jess! I'm closing this and pointing it to an existing task over at `dotcom-manage`: 500-gh-Automattic/dotcom-manage
