### ISSUE TITLE
Free Atomic: 'Save Changes' in Yoast settings showing partially under the nav

### ISSUE THREAD

**Issue by Jaccuse** [Automattic/wp-calypso#52214]
### What plan tier is the site on?

Free

### Where are you seeing the issue?

Yoast SEO -> Search Appearance

### What I expected on the Atomic site

For the 'Save Changes' button to stay to the right of the nav

### What actually happened

Ability to see Site Health which includes all the information shown on the Info Tab.

### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/31910936/115796814-bb1fb400-a38f-11eb-9685-4af99f5f83a1.png)

### Steps to reproduce the behavior

1. Go to 'Yoast SEO' in the sidebar
2. Click on 'Search Appearance' or any other tab with a 'Save Changes' button
3. Scroll down to the page all the way
4. 'Save Changes' button will move partially under the nav

**Comment by inaikem** [comment]
Confirmed. Yoast’s floating “Save changes” button appears obscured behind unified navigation with the nav expanded:

## Image: Yoast + Nav expanded
<img width="909" alt="Yoast + Nav expanded" src="https://user-images.githubusercontent.com/66711744/117607791-51751780-b18f-11eb-865b-59258eeb16a1.png">

## Image: Yoast + Nav collapsed
![Yoast + Nav collapsed](https://user-images.githubusercontent.com/66711744/117607800-53d77180-b18f-11eb-81ac-2fc32887c018.png)

On this particular screen (Search appearance), the presence of the floating button also stops the navigation's collapse button from being clickable. This renders the floating button impossible to view.

I was unable to record the nav collapse issue in action via Droplr as the toggle is obscured by the Droplr toolbar. However, you can check for yourself with Yoast installed on any Atomic site and visiting: https://your-domain.com/wp-admin/admin.php?page=wpseo_titles.

Additional triage-related discussion: p1620622387355500-slack-C01APA37DDW

**Comment by inaikem** [comment]
Reported in Yoast's GH repo here: https://github.com/Yoast/wordpress-seo/issues/17008.

Keeping this issue open temporarily pending feedback here: p1620624644053300-slack-C0208US71GC

**Comment by obenland** [comment]
I noticed a similar symptom of nav unification impacting yoast premium yesterday p1643666403243409-slack-C029JEQRVRT

I'm not sure if there is already a stylesheet for misc nav unification fixes, if there is it probably doesn't hurt to add a fix for this there. Generally, I think, this is something that could be fixed on the Yoast side to account for WP.com circumstances.

**Comment by DustyReagan** [comment]
> Generally, I think, this is something that could be fixed on the Yoast side to account for WP.com circumstances.

I agree. We could address this by overriding the [left value in the CSS](https://github.com/Yoast/wordpress-seo/blob/569430c76624e83b021e883aed37f1ae120c739f/css/src/admin-global.css#L538) on our end. But that's liable to break in the future when the plugin's CSS changes. The long term solution is for the Yoast plugin CSS to not require a specific width for the sidebar menu, which I think is doable.

I opened a [PR](https://github.com/Yoast/wordpress-seo/pull/18031) and commented on the [issue](https://github.com/Yoast/wordpress-seo/issues/17008) with a possible approach.

**Comment by DustyReagan** [comment]
[PR](https://github.com/Yoast/wordpress-seo/pull/18031) accepted! ✅ 🎉 

I propose we leave this issue open until the plugin updates and the fix is visible in production. In case any follow up is needed.

**Comment by DustyReagan** [comment]
Yoast 18.2 landed. Fix is in production. 🙌
