### ISSUE TITLE
Horizon Site Editor Flow creates un-used empty menus

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52245]
The New Onboarding flow that creates FSE sites on Horizon appears to be creating two menus by default. We can see this here when interacting with the menu in the Site Editor.

![image](https://user-images.githubusercontent.com/545779/115914880-21601180-a438-11eb-8db3-e3d885600276.png)

Or by manually visiting the Customizer on a fresh site.

![image](https://user-images.githubusercontent.com/545779/115914924-3177f100-a438-11eb-8102-c501158570ca.png)

Current default experience when activating TT1 on a fresh core install:

![image](https://user-images.githubusercontent.com/545779/115915353-d5fa3300-a438-11eb-8158-44f8ce90ddc9.png)

Recommendation:

I think there's likely some code in the new onboarding flow that's doing this. We should make sure that we're not creating these un-needed menus by default. And/or that we're matching core to reduce variables for remaining aligned specifically with the new user experience of the nav block.

**Comment by Addison-Stavlo** [comment]
I think this has since been resolved. Creating a new FSE today I have 1 menu at start - "Primary".
