### ISSUE TITLE
Should we remove `target="blank"` when clicking the site URL from the site picker?

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/wp-calypso#5224]
I think so. It might also need to be removed elsewhere as well.
1. It's easy to flip between the site and Calypso.
2. It's not going away from our application. Just to another part of it.
3. It's breaking expected browser behavior.
4. It's not an external link (and even if it was, we still shouldn't use `_blank` for [these reasons](https://css-tricks.com/use-target_blank/)
5. When I've modified a page and try to go to another URL before saving, I get a popup warning
6. It doesn't actually prevent users from leaving.
7. We cache pretty well. When they come back, it won't take nearly as long.

This is one of those deeply emotional opinionated topics. Be respectful. Thoughts?

CC @dereksmart

**Comment by mtias** [comment]
The general plan here was to use `WebPreview` for quick in-app views, which would be a much nicer experience in desktop where it's forcefully an external link regardless of _blank.

**Comment by alisterscott** [comment]
Closing as the URL is no longer clickable as we have site preview in built into the sidebar/picker.
