### ISSUE TITLE
Logging in isn't working in calypso.live without 3rd party cookies

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#52243]
### Steps to reproduce the behaviour

1. Disable third-party cookies and visit any calypso.live link in an incognito window
2. Try logging in

#### What I expected to happen

I expected to be able to log in

#### What actually happened

I couldn't log in

### Context

Related to third party cookies. Reported in https://github.com/Automattic/wp-calypso/pull/52166#pullrequestreview-643039308

**Comment by niranjan-uma-shankar** [comment]
This is now fixed as described by @jsnajdr in p4TIVU-9J2-p2.
