### ISSUE TITLE
Null Placeholder on Pages Search

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#52242]
### Steps to reproduce the behavior

1. Select a site and go to the Pages menu
2. Click on the search icon on the top right

#### What I expected to happen
To show _"Search pages..."_

#### What actually happened
It shows _"null..."_ - it shows correctly once you go to Posts, and then back to Pages.

#### Browser / OS version
Mac OS X 10.15.7
Chrome 90.0.4430.85

#### Does this happen on simple or atomic sites or both?
Both, it happens on Calypso.

#### Screenshot
![NullSearchIssue](https://user-images.githubusercontent.com/16104522/115878052-7d1da100-a41e-11eb-9722-2bbd7f68de7a.png)

**Comment by Aurorum** [comment]
PR for this issue in #52244. :)

**Comment by Robertght** [comment]
Closing this as it appears to be fixed.

cc @michaeldcain  for a confirmation
