### ISSUE TITLE
Jetpack Connect: make sure to use correct plugin folder when trying to connect

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#5225]
The connection flow should work even when these things have been changed from the default:
1. The plugin folder has been moved elsewhere (see comment for details)
2. The wp-content has been moved (see comment for details)
3. The site URL has changed (see comment for details)

#### Steps to reproduce
1. Make sure you are logged in to WordPress.com
2. Make sure you are logged in to your self-hosted site
3. On your self hosted site, get latest version of Jetpack installed _but not activated_:
<img width="490" alt="jp-installed-not-activated" src="https://cloud.githubusercontent.com/assets/11487924/15034228/5a8fe20c-1241-11e6-899f-0af990c4f4f5.png">
4. Go to https://wordpress.com/jetpack/connect and enter your site URL from step 3. Click on 'Connect Now'
5. Click on 'Install Jetpack' on the next page
6. See this page:
<img width="1680" alt="jp-already-installed" src="https://cloud.githubusercontent.com/assets/11487924/15034247/88a30732-1241-11e6-80ad-23042da25503.png">

I can't do anything to move forward from this page.

#### What I expected
I expected to be able to go to the next step, or not to be shown the plugin installation page at all and instead the process should try to activate Jetpack.

#### Browser / OS version
Chrome on Mac OS X, IE11 on Windows

**Comment by johnHackworth** [comment]
I've just tested (on chrome on ubuntu) and it worked fine. I entered the url and got this:

![image](https://cloud.githubusercontent.com/assets/1554855/15040594/5461ca56-12b6-11e6-9e1b-94d8d2635089.png)

and then, after clicking the button, the expected:

![image](https://cloud.githubusercontent.com/assets/1554855/15040612/67280bd2-12b6-11e6-8fa9-7584bc335a5a.png)


Which site url are you using to test? Maybe are not detecting that jetpack as inactive because can get the readme in the usual url (we are using `$readme = wp_safe_remote_get( $url . '/wp-content/plugins/jetpack/readme.txt' );` to check if jetpack is there ... so if jetpack is not in that path, we can't detect if it's installed or not :/ This is horribly fragile, better ideas on how to know if jetpack is there or not are welcome!! )

**Comment by v18** [comment]
@johnHackworth - we should handle the cases where Jetpack is found in a different folder. There are three cases like that ([Codex documentation here](https://codex.wordpress.org/Determining_Plugin_and_Content_Directories#Constants)):

1. When `wp-content` is defined to be somewhere else, using `WP_CONTENT_DIR` and `WP_CONTENT_URL`. This can be accessed using `content_url()`
2. When the plugins folder is defined to be somewhere else using `WP_PLUGIN_DIR` and `WP_PLUGIN_URL`. This can be accessed using `plugins_url()`
3. The site URL can be changed on the page Settings > General to have a subdirectory. In that case `site_url()` may be different from `home_url()`, i.e. http://www.example.com/wp-content vs http://www.example.com/wordpress/wp-content.

**Comment by v18** [comment]
This is not possible to detect right now for sites where Jetpack is installed but not activated. It would be great if we could detect that the JP plugin was not found where expected and branch off to a different flow from there (cc @rickybanister since you mentioned this idea)

**Comment by rickybanister** [comment]
@v18 I think we want to gather some more data first to try to figure out how often this is the case. I don't want to optimize our core flow for this other branching circumstance and overcomplicate anything. 

At the moment, I think the best thing we can do is see if we can add something in an upcoming Jetpack release to help here. For older versions we may need to rely on documentation.

**Comment by v18** [comment]
@rickybanister - I agree that we should get more data before trying to solve this case. This is probably indeed pretty edgecase.

**Comment by rickybanister** [comment]
After discussing with @johnHackworth we decided this:

We will add a link beneath the 'back' link in cases when we can't find jetpack. The link will say 'I already have Jetpack installed'.

That link will change the instructions to the isInstalled scenario, which will direct the user to simply activate Jetpack and then connect.

That should be good enough for now, until we can gather more data.
