### ISSUE TITLE
Site Editor: verse blocks breaks after changing the padding

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#52253]
1. Open up the Site Editor integration on Dotcom.
2. Insert a Verse block somewhere in the template.
3. Open up block settings and add custom padding for it.
4. Save changes.
5. Reload the page and notice that the block displays the following error message:

<img width="688" alt="Screen Shot 2021-04-23 at 11 40 43 PM" src="https://user-images.githubusercontent.com/1182160/115932487-577bb080-a48d-11eb-8d6f-6e822d18cca8.png">

Also note that Spacing drawer styles are broken:

<img width="287" alt="Screen Shot 2021-04-23 at 11 41 11 PM" src="https://user-images.githubusercontent.com/1182160/115932542-71b58e80-a48d-11eb-9752-525be977b60d.png">

I wasn't able to reproduce this issue in core. It's also not reproducible in post editor integration.

**Comment by Addison-Stavlo** [comment]
I am no longer able to replicate this, it may have been resolved elsewhere.
