### ISSUE TITLE
Nav Unification: Sidebar Oddly Collapsed

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#52260]
### Steps to reproduce the behavior

1. SU the user from 3934837-zd-woothemes
2. Got to https://wordpress.com/me/account
3. See the left sidebar collapsed in an odd way

Issue happens on random screens, but the above one is the where I could reproduce consistently

#### What I expected to happen

See the uncollapsed sidebar

#### What actually happened

Sidebar collapsed in an ugly way

### Context

Reported in 29150555-hc and started the discussion in p1619251926317800-slack-C01APA37DDW

User mentioned:

>Case in point: I let chrome reopened all tabs after a system crash and all tabs were uncollapsed. This never happened before

#### Browser / OS version

Chrome 89 on macOS (myself)

#### Does this happen on simple or atomic sites or both?
Atomic (in the above case at least)
#### Is there any console output or error text?
```
WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: 
w @ ?v=2.0:16
C @ ?v=2.0:16
D @ ?v=2.0:16
```
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/39308239/115952875-4bc1d580-a4f1-11eb-82a9-386d865c4c5a.png)

**Comment by zdenys** [comment]
I was able to reproduce it on my own account once but not consistently after that. So it's still random for me 😞 . To do so I took these steps from https://github.com/Automattic/wp-calypso/issues/52261 while trying to reproduce that bug:

- Go to https://wordpress.com/home and pick any site you have
- Click on `Collapse menu` at the bottom of the left sidebar
- Click `Switch Site` and pick another site
- Click `Switch Site`again and select the previous site again
- See the sidebar uncollapsed
- Now navigate to https://wordpress.com/me/account
- See the left sidebar oddly collapsed
![](https://d.pr/i/43u6rR+)
_Link: https://d.pr/i/43u6rR_

**Comment by inaikem** [comment]
+1 I have been able to reproduce on a test site 3/5 times when reloading a page/clicking to a new nav item.
