### ISSUE TITLE
Embed Blocks: When converting to a paragraph, any styling on caption turns into visible HTML tags in the text

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#52267]
### Steps to reproduce the behavior

1. Go to Wordpress.com page/post editor
2. Add any embed block (like YouTube, Vimeo, Twitter etc.)
3. Add a caption, and add some styling to it (like bold, or color)
4. Convert the whole block to a Paragraph block

#### What I expected to happen
The styling to either translate to the Paragraph block, or at least be stripped

#### What actually happened
All the html tags pull into the text node on the converted paragraph block

#### Browser / OS version
Chrome 90.0.4430.72
Windows 10 Home 19042.928

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Before:
![embed_caption_before](https://user-images.githubusercontent.com/26772342/115973388-4036d480-a51a-11eb-9f00-2c7baf84d41a.png)

After:
![embed_caption_after](https://user-images.githubusercontent.com/26772342/115973395-44fb8880-a51a-11eb-903f-fde35c1e3479.png)

**Comment by kosiew** [comment]
Hi @dpasque ,

Thanks for reporting this and the detailed steps.

I reproduced this on a Jurassic Ninja site too.
I am closing this and reporting this as a Gutenberg issue - https://github.com/WordPress/gutenberg/issues/32265 instead.

**Comment by talldan** [comment]
Please could you remember to strip out mentions of WordPress.com when transferring bugs.
