### ISSUE TITLE
Javascript errors on clicking on add post button after local build on windows 10

### ISSUE THREAD

**Issue by zdravkov** [Automattic/wp-calypso#5227]
#### Steps to reproduce
1. pull --rebase the repo
2.make run 
3.message after this- [https://gist.github.com/zdravkov/655b516490e9bef537da422524d6c687]
4.http://calypso.localhost:3000/ loads correctly
5. when I click add post I see this javscript error in the console -  Uncaught module definition dependecy not found: tinymce/util/Tools plugin.js:19
6 after each next stem the error is this one - Uncaught TypeError: __webpack_require__(...) is not a function sections.js:816 

#### Browser / OS version
Windows 10

#### Screenshot / Video
video -http://screencast.com/t/iUSv22iFS6yD

**Comment by m-muhsin** [comment]
Hi,

I am encountering the same issue as @zdravkov 

Anyone fixed this issue?

**Comment by lancewillett** [comment]
Hi @m-muhsin Could you please add details such as URL, steps to repeat, OS version, etc. Screenshots and JS errors are also helpful to track it down.

**Comment by m-muhsin** [comment]
Thanks for your response @lancewillett 

**Steps to reproduce:**
1. Git clone wp-calypso
2. make run 
3. I can now open http://calypso.localhost:3000/ successfully
4. Under 'My Sites' -> Blog Posts -> click on 'Add'
I get the following error in the browser console:

**Uncaught module definition dependecy not found: tinymce/util/Tools**
app:///./~/tinymce/plugins/paste/plugin.js:19 

When I click on 'Add' again, I get this on the browser console:
**Uncaught TypeError: __webpack_require__(...) is not a function**
    at eval (sections.js:1017) ...........
sections.js:1017 

**Browser / OS:**
Chrome 56 on Windows 10
