### ISSUE TITLE
People: Inviting person with long email address on narrow screens resizes field off screen

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5228]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/people/new/ on mobile or narrow viewport
2. Add a long email address

#### What I expected

Email address truncates or wraps elegantly

#### What happened instead

Field resizes larger than screen width which makes the remaining elements inaccessible on a mobile phone

#### Browser / OS version

iOS9.2

#### Screenshot / Video

![invite](https://cloud.githubusercontent.com/assets/128826/15036496/fb5396b6-12d2-11e6-93cf-113b621047f0.png)

**Comment by lancewillett** [comment]
Now THAT'S a long email. :)

**Comment by alisterscott** [comment]
Yes, a long email, but that's an iPhone 6+ screen whereas an iPhone 5 screen say would be narrower

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the steps provided.

<img alt="img_0542" src="https://cloud.githubusercontent.com/assets/1119271/17907975/91c87c06-693b-11e6-8a54-b0d9ed3034eb.PNG" width="400" />
<sup>Seen at https://wordpress.com/people/new/design5279.wordpress.com using Safari iOS 9.3.4 on iPhone 6S</sup>

**Comment by folletto** [comment]
> Email address truncates or wraps elegantly

Yep. The text field shouldn't expand to accomodate text, but crop the text as a normal input field.

**Comment by ManrajGrover** [comment]
@folletto I can take this one up. Please help me get started.

**Comment by folletto** [comment]
> Please help me get started.

Sure! What kind of help do you need? :)

**Comment by ManrajGrover** [comment]
@folletto I've set up the dev environment and can confirm this issue. Please help me proceed with the fix. I'm new to React in particular. I tried using `word-wrap` property but that didn't help.

**Comment by jahvi** [comment]
I tried to give this a shot on my end since it's one of the few issues in calypso I feel I can contribute to for now 😅

Feel free to give feedback #8485
