### ISSUE TITLE
Referral links lead to a - Not Page Found - when Interface language is not "English" (localized links)

### ISSUE THREAD

**Issue by marianearchimbaud** [Automattic/wp-calypso#52281]
Referral links are not working as expected after copying them from the Earn section:

![](https://d.pr/i/4o5i6i+)
[image](https://d.pr/i/4o5i6i)

According to this previous report https://github.com/Automattic/i18n-issues/issues/150 the link is supposed to have this structure:
http://**fr.wordpress.com**/refer-a-friend/6kvPP1RioVR730bbl0AZ

### Expected behavior
Visiting a referral link should lead users to the referral page, using the localized version if needed.

### Actual behavior
If a user's account/interface setting is set to other language instead of English the referral link looks like this:
https://wordpress.com**/pt-br/**refer-a-friend/thecodegoeshere/
and it leads you to a 404 error - No page found here: 

![](https://d.pr/i/x8EnUH+)
[Image](https://d.pr/i/x8EnUH)

The link starts working if we modify the links like these examples:
https://**br**.wordpress.comrefer-a-friend/thecodegoeshere/
https://**pt**.wordpress.comrefer-a-friend/thecodegoeshere/
https://**es**.wordpress.comrefer-a-friend/thecodegoeshere/

### To Reproduce

On a localized account 
1. Go to Tools > Earn
2. Click on Copy on the Referral links section
3. Open the copied link on a browser
4. See 404 error.

This issue was reported in this interaction: 3934074-zd

**Comment by Aurorum** [comment]
PR for this issue in #52299. :)

**Comment by lsl** [comment]
@jaswrks / @dlind1 please see https://github.com/Automattic/wp-calypso/pull/52299#issuecomment-827326437 a backend fix is required.

**Comment by dlind1** [comment]
The fix to correctly redirect wordpress.com/(locale)/refer-a-friend/(hashid) links was implemented in D60747-code.

**Comment by jaswrks** [comment]
Awesome. Thank you. @marianearchimbaud I believe this can be closed now?

**Comment by marianearchimbaud** [comment]
Perfect. I have just tested this, and it's working as expected:
https://wordpress.com/es/create-blog-referral/?aff=46628&sid=NKkk9vBIV18Z4m3GJPLZ
Screenshot: https://d.pr/i/nGPvfb

Thank you!!
