### ISSUE TITLE
FSE / Query Block: Block breaks after editor reload

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#52310]
### Steps to reproduce the behavior

1. Create a new site using the FSE flow. Also, make sure you have a couple of posts to test with.
2. In the site editor add a Query block to the Post Content.
3. Save and close the editor. 
4. Preview the site - the posts should be displaying properly.
5. Open up the site editor again. Notice the Query block has an "Attempt block recovery" message.

#### Is this specific to the applied theme? Which one?
I don't think so. This happened to me using Mayland and Seedlet designs in signup.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
I set up a few sites to test our stater designs, and this consistently happened every time I used Query block.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://cloudup.com/cMJDRfUaMHf

**Comment by glendaviesnz** [comment]
@alaczek - this should have been fixed by D60947-code & D60943-code. @alaczek please reopen if you still experience this issue
