### ISSUE TITLE
Earn tab: Unable to connect to Stripe

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#52313]
### Steps to reproduce the behavior

1. Go to WordPress.com > My Sites > Tools > Earn > Collect Recurring Payments > Connect Stripe
2. Enter your email address and try to log in.
3. See error message `There was a problem logging you in. Please try again in a few moments.`

#### What I expected to happen
Expected to login to Stripe and connect it to WordPress.com account.

#### What actually happened
Login didn't work.

### Context
When the user tries to log in directly to their Stripe account from the Stripe website, their login works all okay.

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
There is a 401 error in the console when trying to login

![Markup on 2021-04-27 at 08:46:50](https://user-images.githubusercontent.com/7382505/116179546-2f15df80-a735-11eb-93f4-3607127becd1.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects the user's site as well as on my test site, so I'm assuming blocks new Stripe connection and hence any new payments.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
<img width="1418" alt="Markup 2021-04-27 at 08 43 15" src="https://user-images.githubusercontent.com/7382505/116179576-389f4780-a735-11eb-9c21-be03686ab913.png">

#user-report

Chat: 29248693-hc
Ticket: 3941656-zen

**Comment by Robertght** [comment]
@galakhyati I was able to connect with Stripe from my end using Chrome(latest version).

Can you give this a second shot and let us know if this is still an issue on your end?

If the issue is still happening, we may need more details about it.

**Comment by galakhyati** [comment]
Hey @Robertght I tested again on Chrome browser (latest version) and still able to see the issue. 

Here is a screencast video showing the same:


https://user-images.githubusercontent.com/7382505/117655545-d45c9900-b1b4-11eb-9c06-ba88c41d7201.mov

Chrome browser: Version 90.0.4430.93 (Official Build) (x86_64)
OS: macOS Big Sur v 11.3.1
Plan: WordPress.com Premium plan.
Site URL: khyatipremium.wordpress.com

Let me know if you require any additional information needed, happy to provide.

**Comment by Robertght** [comment]
Thank you @galakhyati ! I followed your video and I was able to connect with Stripe as well.

A few things that I noticed and I'm not sure if they make a difference for further testings (cc @kwight):

- I had a Stripe account previously and only created the Stripe express one afterwards
- After selecting the account and confirming the last screen, I'm getting returned to pick the Stripe account again in the process, but once I click on the next steps it connects to it correctly.

**Comment by donlair** [comment]
Is anybody else able to replicate this? The connection works fine when I test it.

**Comment by galakhyati** [comment]
I was able to rectify the issue. My Stripe account wasn't set up, which is why the error was being shown. Once I set up my account fully, I was able to connect without any error.

**Comment by Robertght** [comment]
Thank you for testing this @galakhyati ! As there are no further reports at the moment, I think we can close this, but I'm wondering if we can improve the documentation and specify this is a must when connecting to Stripe. (cc @donalirl for a second opinion on the documentation part)

**Comment by Robertght** [comment]
After chatting with @donalirl the intro was changed to a clearer one to help the users in the process.
