### ISSUE TITLE
E2E: Force reduced motion

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#52326]
We're currently testing a [`waitUntilElementStopsMoving`](https://github.com/Automattic/wp-calypso/pull/52089/files) helper that should cover situations where E2E specs are flaky because of moving/animated elements. While this might be a good solution, an even better one could be forcing [reduced motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) (as it's done i.e. [in Gutenberg](https://github.com/WordPress/gutenberg/blob/6fbbc985c4644abc6ad62269476889166860d008/.github/workflows/end2end-test.yml#L41)). Let's see if we can use it here.

/cc @lsl @griffbrad @sarayourfriend @scinos @Automattic/team-calypso-platform

**Comment by noahtallen** [comment]
Do you think having animations enabled would give us more signals regarding broken features? What if an animation actually does break something?

**Comment by WunderBart** [comment]
> Do you think having animations enabled would give us more signals regarding broken features? What if an animation actually does break something?

Good question! I do share that concern. IMO, the closer we simulate our actual user interaction the better. With the animations on, we're actually testing them (which kinda makes me think that testing the app **without** animations would be a whole separate test case). And since we're recording videos, in case of any failure we could easily verify if the animations are OK.
The `clickWhenClickable` equipped with `waitUntilElementStopsMoving` has been working pretty reliably so far (we're down to only 2 flakies! 😄  p1619777831019500-slack-C01QG4Y91RR), so I would be perfectly fine with keeping things as they currently are.

**Comment by lynnbgriffith** [comment]
As long as the helper is working reliably, I’m totally fine with that. If it turns out to be a barrier to people writing reliable tests, though, I think the trade-off of using reduce motion would be a worthwhile one.

**Comment by WunderBart** [comment]
Closing, as the animated elements haven't been an issue since the `waitUntilElementStopsMoving` was implemented 🎉
