### ISSUE TITLE
Site Editor: Mis-aligned Replace Image Button

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52344]
### Steps to reproduce the behavior

1. Create a site on WP.com with the Site Editor
2. Add an image or select one in the Site Editor
3. Open the block inspector

#### What I expected to happen

Image Block Settings similar to the core experience.

![image](https://user-images.githubusercontent.com/545779/116300451-87b0a100-a764-11eb-9a2e-dec19d618fe9.png)

#### What actually happened

Strange mis-aligned replace image button in block inspector.

![image](https://user-images.githubusercontent.com/545779/116300538-9e56f800-a764-11eb-8ba0-093a5168d106.png)

![image](https://user-images.githubusercontent.com/545779/116300581-aa42ba00-a764-11eb-8ac0-fdc0afbcb671.png)

**Comment by apeatling** [comment]
Does not seem to be an issue anymore.
