### ISSUE TITLE
Editor: The loading placeholder is missing a gap between the header and placeholder content

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#52363]
### Steps to reproduce the behavior

1. Open site in Calypso
2. Add a new page or post
3. Wait while editor loads in iframe

#### What I expected to happen

See a visually pleasing placeholder

#### What actually happened

![Screen Shot on 2021-04-28 at 18:38:35](https://user-images.githubusercontent.com/1500769/116357902-29152100-a851-11eb-8fdb-5d02de87a8ad.png)

It'd be more apparent the white bar at the top of the placeholder is supposed to represent the editor header if there was space between the it and the darker grey pill.

### Context
p1619449914079000-slack-CRNF6A9DX

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

CC @pablohoneyhoney

**Comment by yansern** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/52433.
