### ISSUE TITLE
Jetpack Connect: signing in as a different user tells me it's already connected

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5239]
### Steps to reproduce:

1. Connect Jetpack to your WordPress.com account.
2. Go to https://wordpress.com/jetpack/connect
3. You will get a green warning that the site is already connected.
4. Click on "Sign in as a different user" below the connect screen.
5. Log in to WordPress.com with a different account.
6. You get redirected back to https://wordpress.com/jetpack/connect/authorize
    - The success message is still there, because the site is indeed connected to WordPress.com.
    - It's not connected to that WordPress.com account, though.

I think we should remove the "Sign in as a different user" and "Create new account" options when the site is already connected, to avoid confusion.

**Comment by johnHackworth** [comment]
fixed in https://github.com/Automattic/wp-calypso/pull/5337
