### ISSUE TITLE
Jetpack Search: shows as active on your site even if toggled off

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#52405]
### Steps to reproduce the behavior
1. On a site with a Jetpack Search plan purchased, go to Settings > General > Performance
2. Click to deactivate Jetpack Search with "Improve built-in WordPress search performance." toggle
3. Go to `/jetpack-search`

#### What I expected to happen

If I have an active Jetpack Search plan but have chosen to turn off Jetpack Search, the page should say that.

#### What actually happened

If I have an active Jetpack Search plan but have chosen to turn off Jetpack Search, I am still told "Jetpack Search is active on your site".

### Context

Raised by @jinnypark in Automattic/jpop-issues#6586.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Medium. The page isn't showing the correct information in this scenario.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/17325/116504388-43600500-a90c-11eb-8e8a-b799d5b6c760.png)

**Comment by bluefuton** [comment]
I believe the page only checks to see if there is a currently active JPS plan. It may not check whether the user has turned it off manually.

**Comment by Aurorum** [comment]
Hi @bluefuton, I'd like to work on this and #52405 if nobody else is planning to, but since I don't have access to a site with a JPS plan, would it please be possible to invite me as an administrator to one?

**Comment by bluefuton** [comment]
Thank you @Aurorum! We'd really appreciate your help on those :) 

It's probably easiest if I give you some WordPress.com credits on an account you already have - just let me know the username and I'll arrange it for you.

**Comment by Aurorum** [comment]
Thank you! My WordPress.com username is `torres126`.

**Comment by bluefuton** [comment]
Thanks @Aurorum! I've added 100 free credits for you, and you should be able to upgrade via https://wordpress.com/jetpack-search.

**Comment by Aurorum** [comment]
Thank you! PR to resolve this in #52454. :)
