### ISSUE TITLE
Export: Button placement looks off

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#52424]
### Steps to reproduce the behavior

Noticed this during a team demo...

1. Go to `/export` on a simple site
2. Note the placement of the Export All button and the Download button below it
3. Those buttons should probably be aligned to the right for a cleaner visual design

<img width="808" alt="Screen Shot 2021-04-29 at 12 08 58 PM" src="https://user-images.githubusercontent.com/2124984/116584125-06cce300-a8e5-11eb-8da3-376693cc348d.png">

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low

**Comment by Aurorum** [comment]
PR for this issue in #52427. :)
