### ISSUE TITLE
Editor: Show patterns inserter modal after dismissing

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#52422]
With the adjustment of the modal as the “pattern” view, we need a way for folks to access once closed. Following core’s lead around pattern directory work, we should introduce a button within the pattern inserter sidebar that allows folks to “browse all” patterns, which should resurface the modal. See: p9Jlb4-2qt-p2#comment-3874

**Comment by annezazu** [comment]
Closing this out as the design and experience has evolved beyond this issue from 2021.
