### ISSUE TITLE
Reader: Unable to add sites to a list using URL

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#52444]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/list/new
2. Create a new list or edit an existing list
3. Click on the Sites tab
4. Type/paste the URL of a site you're following, that you want to add to the list in the search box
5. Click the Follow {site URL} link that appears

#### What I expected

For the site to be added to the list

#### What happened instead

I see the error, `Unable to add feed to list`. It happens for both WordPress.com-hosted sites, and external sites.

It works fine if I just search for the first part of the domain, and then click the Add button from the results, but it does not work if I type the full URL in the search box and then try to add it.

#### Browser / OS version

Replicated in the most recent versions of Chrome and Firefox on Mac OS 11.3

#### Screenshot / Video

![Screen Capture on 2021-04-30 at 12-42-08](https://user-images.githubusercontent.com/11873759/116685330-71982000-a9b2-11eb-9d3b-f47c02ad0ee6.gif)

#### Context / Source

Reported by a user in https://wordpress.com/forums/topic/reader-almost-a-year-with-lists-in-bug/

**Comment by Aurorum** [comment]
PR for this issue in #53234. :)
