### ISSUE TITLE
Theme Details: Redirect invalid section to default one

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#5245]
When accessing an invalid section of the Theme Details page via the entered URL -- e.g. http://calypso.localhost:3000/theme/rosalie/invalid -- we return the page content for the default section, 'Overview'.

Instead, we should actually redirect to that section -- otherwise the URL in the address bar will continue to read whatever invalid section was entered. (Also, server-side -- and hence indexable -- pages are going to be created for that URL!)

To that end, we'll need to provide an isomorphic wrapper covering both `page.redirect()` and its`express` counterpart, `res.redirect()`.

**Comment by seear** [comment]
> (Also, server-side -- and hence indexable -- pages are going to be created for that URL!)

There shouldn't ever be links to an invalid section, though?. The important thing is that if no section param is supplied we show the overview.
