### ISSUE TITLE
Jetpack Connect: Login with a 2FA-enabled account

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#5246]
When you attempt to connect a Jetpack site, and during authorization, you login with a 2FA enabled WordPress account, query parameters are lost, and the authorization fails.

This happens in the new flow AND the current, existing flow!

Here are the steps to reproduce on the current flow: https://github.com/Automattic/jetpack/issues/3465

And on the new flow:
- disconnect a Jetpack site
- log out of wpcom
- while logged in to wp-admin of your Jetpack site with an account that has an a8c email, click 'Connect Jetpack'
- click 'Already have an account? Sign in'
- sign in with a 2FA account
- You should get this error when you click 'Approve'

![screen shot 2016-05-06 at 7 18 03 am](https://cloud.githubusercontent.com/assets/2694219/15071601/cbcac15c-135a-11e6-9f0e-64e6d3521159.png)

props to @jeffgolenski for reporting

**Comment by lancewillett** [comment]
Could you please add info like steps to repeat, screenshot or video, and browser details (if applicable). Thanks! That info is very helpful for reproducing.

**Comment by roccotripaldi** [comment]
updated the description @lancewillett

**Comment by beaulebens** [comment]
In attempting to test this (before even switching to this branch, and just trying the initial reproduction steps on staging), I get a JS error in the auth flow, after the 2FA login:

`Uncaught TypeError: Cannot read property 'replace' of undefined`

Appears to be coming from this statement:

`var site=this.props.jetpackConnectAuthorize.queryObject.site.replace(/.*?:\/\//g,"");`
