### ISSUE TITLE
Checkout: do not show monthly plan option when upgrading from annual plan

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#52473]
From an internal bug report:

1. Customer bought our annual Premium plan
2. Customer then upgraded to our monthly Business plan on the same website
3. This left the customer charged with both the annual Premium and monthly Business plans

Apparently this is not desirable. It looks like someone already took care of this in https://github.com/Automattic/wp-calypso/pull/47229 but maybe it has become a problem again?

**Comment by DavidRothstein** [comment]
More context (internal) at pNPgK-5q8-p2

**Comment by sirbrillig** [comment]
As discussed on the internal post, before we take any action here, we need to better understand what exactly we're trying to do. The specific feature request was to prevent a user who has an annual Premium plan from purchasing a monthly Business plan. However, this brings up a lot of related questions:

- What about changing from an annual Premium plan to a monthly Premium plan?
- What about changing from an annual Premium plan to a biannual Business plan?
- What about changing from a biannual Premium plan to a monthly Business plan?

Etc. At least some of the possible flows are desirable for the business, but some are clearly not. Someone with authority should explain which upgrades should be allowed and which not.

**Comment by DavidRothstein** [comment]
Pinged on it again: pNPgK-4vm-p2#comment-22089

>Someone with authority should explain which upgrades should be allowed and which not

It might just fall on us to be the authority and make it up ourselves :smile:  But I believe we could just block the case where a user changes their plan **and** tries to downgrade the billing term also (that is hopefully the only thing that is broken, and we can probably get away with just not offering it).  So in my opinion:
1. "What about changing from an annual Premium plan to a monthly Premium plan?" (KEEP - that should work fine and is currently a specifically-supported feature in some contexts)
2. "What about changing from an annual Premium plan to a biannual Business plan?" (KEEP - we should double-check that works correctly, but I think it does)
3. "What about changing from a biannual Premium plan to a monthly Business plan?" (REMOVE - along with any variation like it where there's a plan upgrade and a billing term downgrade at the same time, e..g biannual-to-annual or annual-to-monthly also; I think those are the broken ones currently)

**Comment by DavidRothstein** [comment]
I guess this is related to (and will "fix") https://github.com/Automattic/wp-calypso/issues/51037.

**Comment by sirbrillig** [comment]
I'm doing this first in the shopping-cart endpoint (297-gh-Automattic/payments-shilling) via D62586-code. Once that works, I'll make similar restrictions in calypso here.

**Comment by sirbrillig** [comment]
> "What about changing from an annual Premium plan to a monthly Premium plan?" (KEEP - that should work fine and is currently a specifically-supported feature in some contexts)

Currently, this costs the user the full price of the monthly Premium plan. Do we want to maintain that behavior?

**Comment by DavidRothstein** [comment]
>Do we want to maintain that behavior?

Yes, I think so.  My understanding is that it adds the monthly term on top of the yearly term (e.g. if you buy an annual plan today and then immediately upgrade to a monthly plan, you'll wind up with a subscription that expires 13 months from today).  If so, then there's no discount and the user should be charged the full price.

**Comment by DavidRothstein** [comment]
Just a note: This is now blocked in the shopping cart for all types of billing term downgrades (i.e. you can't downgrade to monthly during a product upgrade, as per the issue title here, but you also can't downgrade from 2-year to 1-year either).

So when we prevent the user from selecting these options in Calypso, we should prevent all those options from being selected.
