### ISSUE TITLE
Stats: Empty "most popular day and hour" overlay misaligned on tablet/mobile

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#5247]
#### Steps to reproduce
1. Create a new site, or browse to /stats/insights for a site that has had no views
2. Look at the "Most popular day and hour" section
3. There's an overlay saying that no popular day and time has been recorded.
#### What I expected

It looks fine on desktop:
<img width="703" alt="screen shot 2016-05-05 at 1 17 11 pm" src="https://cloud.githubusercontent.com/assets/7233112/15054413/582a6b4c-12d5-11e6-8ad0-e2cdd7eee4db.png">
#### What happened instead

On mobile/tablet widths the overlay isn't well aligned, so it's confusing to read:
<img width="375" alt="screen shot 2016-05-05 at 1 17 20 pm" src="https://cloud.githubusercontent.com/assets/7233112/15054426/6d54af1e-12d5-11e6-8205-5bc311544e4b.png">
#### Browser / OS version

OSX Chrome v50

It's worth noting that on the Android version of Chrome the overlay doesn't show up at all, so all you see is this:
![image](https://cloud.githubusercontent.com/assets/7233112/15054464/a213b59c-12d5-11e6-833b-6f9833093b56.png)

**Comment by lancewillett** [comment]
This could be a duplicate of #4948

**Comment by hoverduck** [comment]
I actually meant to link to that one, but forgot in the process of adding all the screenshots.

I don't think it's really a duplicate, but they're definitely related and could likely be fixed together.

**Comment by designsimply** [comment]
#bug-scrub

I think the overlay is okay as is because it's such a rare case, however, I think the missing notice on Android Chrome is a bug.

**Comment by hoverduck** [comment]
#bug-scrub

Closing, the notice now appears fine on Android
