### ISSUE TITLE
Media: File upload doesn't work on Calypso Media link, but does when using wp-admin Media link.

### ISSUE THREAD

**Issue by sstabrizi** [Automattic/wp-calypso#52476]
### Steps to reproduce the behavior

1. Go to Media
2. Click on Add New
3. Select a .ZIP file to upload
4. See error 1 file could not be uploaded because an error occurred while uploading.
5. Go to wp-admin version of Media and upload a ZIP file and it works.

#### What I expected to happen

I expect the ZIP file to upload from either the Calypso or wp-admin version of Media.

#### What actually happened

An error appeared saying 1 file could not be uploaded because an error occurred while uploading.

### Context

A user was having trouble uploading a ZIP file successfully due to seeing an error message when they try. After enabling wp-admin pages and trying from the wp-admin version of Media, the file would upload without any issue. 

29343825-hc
29344187-hc

**Comment by metabreakr** [comment]
I had a similar issue with a JPG file in 29363229-hc

Browser: https://www.whatsmybrowser.org/b/85P4F

**Comment by synora** [comment]
Thanks for these reports. There's an open issue for this at https://github.com/Automattic/wp-calypso/issues/50928. I'll this issue in favor of 50928.
