### ISSUE TITLE
Images appear upscaled when posted with the new editor

### ISSUE THREAD

**Issue by koke** [Automattic/wp-calypso#525]
It looks right in the editor:

![screen shot 2015-11-23 at 16 39 12](https://cloud.githubusercontent.com/assets/8739/11341507/0619123e-9203-11e5-8b1b-71270801a0d4.png)

But when I preview it on the site I get this:

![screen shot 2015-11-23 at 16 39 17](https://cloud.githubusercontent.com/assets/8739/11341528/15333114-9203-11e5-8aaf-4a26c64cdeab.png)

**Comment by aduth** [comment]
Can you provide a link to the post, if it's published? Otherwise, can you right-click each image, comparing the result of "Copy image URL", and report here if there's any differences?

**Comment by koke** [comment]
The post is http://koke.me/2015/11/23/using-all-the-buttons-of-a-logitech-g500-on-a-mac/ but before publishing I went into the HTML editor and removed the `size-full` class from all the images

**Comment by aduth** [comment]
@koke - The Custom CSS configuration for that site applies a `width: 100%;` style to the `img.size-full` class, so this sounds as though it is working as intended. If you remove this custom styling, are you still observing the upscaling?

**Comment by koke** [comment]
:facepalm: I guess I forgot about that. That seems to be the cause. I'll remove that custom CSS since images are served a smaller size
