### ISSUE TITLE
Pricing Table Block: The button in pricing plan tile should not move based on 'Add Feature' text

### ISSUE THREAD

**Issue by sowmya2709** [Automattic/wp-calypso#52507]
The button in the pricing Table tile should not move based on the 'Add Feature' text

### Steps to reproduce the behavior

1. Go to WordPress editor
2. Add Pricing table  block
3. Select 4 tiles pricing table option
4. Edit pricing table items
5. Add random text in the 'Add Feature' item of each tile. Make sure the text content length is different for each tile
6. Check Buy Now button location in the preview

#### What I expected to happen
I expect button placement to be in co-relation to the tile's bottom border, not the Add Feature content length

#### What actually happened
Based on the 'Add Feature' pricing table item's text length, the buttons in all 4 tiles are not in the same horizontal level.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/8281027/116875868-b8666e00-ac6f-11eb-97ad-ecfdf21fe9fa.png)

**Comment by Rolilink** [comment]
This seems to be related with the CoBlocks plugin added the label, should we log this issue on the coblocks repo instead?

**Comment by Rolilink** [comment]
Created https://github.com/godaddy-wordpress/coblocks/issues/2195.
