### ISSUE TITLE
Reusable Block: when "Create Reusable Block" pop-up appears, the control is not in the text box. Save button should be before cancel button

### ISSUE THREAD

**Issue by sowmya2709** [Automattic/wp-calypso#52506]
Reusable Block: when "Create Reusable Block" pop-up appears, the control is not in the text box when the pop-up loads
And also Save button should be before the cancel button in the pop-up

### Steps to reproduce the behavior

1. Go to Wordpress editor
2. Add Pricing plan block
3. Edit the pricing plan
4. Select pricing plan and click the More options menu in the  top menu bar
5. Select "Add To Reusable block" from the list options
6. check pop-up block to enter new resuable block name

#### What I expected to happen
I expect to see "Create Reusable Block" pop-up to appear with control already in textbox field so that user can just start typing in the name. Also I expect 'Save' button to be before 'Cancel' button as user will have to tab twice save after entering the name

#### What actually happened
As a user, I am forced to click on the textbox to start typing. When the pop-up is displayed, the control should already be in textbox but it's not. User is forced to tab or click in textbox using mouse to start typing the reusable block name
Also 'Save' button should be before 'Cancel', the immediate action after entering the name of the block is Save not Cancel.
This saves one tab action from users perspective

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://www.loom.com/share/782a45cbb2ca457ba9154a3f25cda573

**Comment by Rolilink** [comment]
This seems more like a feature request than a bug to me ... Adding the Feature Request label!.

**Comment by Rolilink** [comment]
I confirmed this behavior is still happening, but this seem to be related to the gutenberg project, I created two issues over there:
https://github.com/WordPress/gutenberg/issues/37240
https://github.com/WordPress/gutenberg/issues/37241
