### ISSUE TITLE
Plugins: no option to install / activate plugin when secondary user on Atomic site

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#52510]
### Steps to reproduce the behavior

1. Start with an Atomic site.
2. Invite another WordPress.com user to join your site as an admin.
2. In a different browser, sign in with that other WordPress.com user, and ensure you can access `https://yoursite.com/wp-admin/admin.php?page=jetpack`, and that you're linked to WordPress.com there.
3. Go to https://wordpress.com/plugins/tinymce-advanced/ and select that site.
4. You will not see any button to install the plugin.

#### What I expected to happen

![image](https://user-images.githubusercontent.com/426388/116882675-02763200-ac25-11eb-8e68-7cc0aeb97b46.png)

#### What actually happened

![image](https://user-images.githubusercontent.com/426388/116882659-fc805100-ac24-11eb-88e1-d62c24e59b93.png)

### Context

Internal reference: p8oabR-F6-p2#comment-5283

**Comment by cpapazoglou** [comment]
Just tried installing Mailpoet from my second "invited" account through Calypso and seems working:
- The button appears
- Installation goes through as expected

<img width="1333" alt="SS 2022-01-06 at 10 08 38" src="https://user-images.githubusercontent.com/12430020/148350316-40b55742-3384-48f7-874f-329ca94727c8.png">

<img width="1588" alt="SS 2022-01-06 at 10 09 03" src="https://user-images.githubusercontent.com/12430020/148350351-fb71da11-15dd-445a-967e-77e320fc5b33.png">

Closing this, please reopen if I am missing something.
