### ISSUE TITLE
Cannot Increase Syndication Feed Beyond 150 Items on Simple Sites

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#52513]
### Steps to reproduce the behavior

1. Select a simple site and navigate to Settings > Reading > Syndication feeds show the most recent 
2. Change the number in the field to 151 or greater
3. Save the change

#### What I expected to happen
The "Syndication feeds show the most recent" setting to remain at 151. 

#### What actually happened
The "Syndication feeds show the most recent" setting changes the number to 150. The maximum number of episodes in a podcast feed is 350, so they should be able to increase it up to 350. It appears that users of all WordPress.com plans should have this ability. 

### Context
Report 29374748-hc.

#### Does this happen on simple or atomic sites or both?
Simple sites only. Works as expected on Atomic sites. 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
High impact as simple sites cannot increase this setting beyond 150 items. 

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

**Comment by kwight** [comment]
@michaeldcain Any idea who might be able to look at this?

**Comment by michaeldcain** [comment]
Related issue: #37541

The 150 item WPcom feed limit was implemented here: p195om-1bH-p2. It looks like it can be overridden via filter priority. We could probably increase the limit to 350 for podcast feeds by default.

**Comment by taggon** [comment]
I created a diff D61339-code to increase the limit to 350.

**Comment by taggon** [comment]
Resolved by D61339-code.
