### ISSUE TITLE
Theme Showcase: Theme menu has a blank option that's selectable

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#52526]
### Steps to reproduce the behavior

1. Visit the theme showcase
2. Click on the vertical three dots in the bottom right of any theme's square
3. A popup menu appears
4. At the very bottom of the menu, there is a blank entry that is highlightable. If you click it, it asks you to activate the theme. Just seems odd and low-polish.

![2021-05-03_14-24](https://user-images.githubusercontent.com/937354/116922878-8c210200-ac1b-11eb-9ad6-3507f6d7a9c5.png)

https://user-images.githubusercontent.com/937354/116923046-bd99cd80-ac1b-11eb-968c-ff74e35783bf.mp4

This is caused by something called [showAutoLoadingHomepageWarning](https://github.com/Automattic/wp-calypso/blob/87083962f859b79de269733f89ed1f0eb4e576cf/client/my-sites/themes/theme-options.js#L148-L150), which is turned into a menu item by [this code](https://github.com/Automattic/wp-calypso/blob/87083962f859b79de269733f89ed1f0eb4e576cf/client/components/theme/more-button.jsx#L93-L102).

I'm unsure of the purpose of `showAutoLoadingHomepageWarning` and if it is working. If it is working, does it need to render a blank menu item? If it isn't working, can we fix it and remove the menu item?

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/42052
