### ISSUE TITLE
Theme Showcase: Encoding issues on hover tooltips

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#52524]
### Steps to reproduce the behavior

1. Go to theme showcase
2. Hover over the screenshot of the seedlet theme
![2021-05-03_14-09](https://user-images.githubusercontent.com/937354/116921222-54b15600-ac19-11eb-934d-ad01d877473a.png)

#### What I expected to happen

- See tooltip text in the correct encoding

#### What actually happened

- See html codes like `&#8217;` in the tooltip

**Comment by Aurorum** [comment]
PR for this issue in #52536. :)
