### ISSUE TITLE
Atomic: Image thumbnails not loading when an AT site is Private

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#52520]
### Steps to reproduce the behavior

1. On an Atomic Public site, upload images to the Media Library
2. Set the AT site to Private
3. Check the Media library
4. Notice thumbnails are not loading

#### What I expected to happen

For the thumbnails to load normally

#### What actually happened

The thumbnails are not displayed

### Context

User report:

29243073-hc

Explanation about what causes the issue by @JoshuaGoode:

>When a site is Coming Soon or Public site and uploads images, subsizes are routed through photon.
If they switch to Private later, it'll break that.  Amongst many other things.
Private itself is no longer default for new sites and is still problematic. I've been collecting some feedback to see if we can adjust or eliminate it.
We can fix this by deactivating Photon Subsizes and regenerate subsizes but it's best if the use Coming Soon if at all possible.  Since Private prevents them from using VideoPress and certain plugins and themes.

p1618416140279100/1618414971.262400-slack-C03TY6J1A

#### Browser / OS version

Chrome Version 90.0.4430.93 (Official Build) (x86_64)
macOS Big Sur 11.3 (20E232)

#### Is this specific to the applied theme? Which one?

Nope

#### Does this happen on simple or atomic sites or both?

Atomic

#### Is there any console output or error text?

![Screen Shot 2021-05-03 at 13 19 04](https://user-images.githubusercontent.com/3696121/116915824-28dea200-ac12-11eb-9562-8ab525df3afe.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It affects any AT site that was public, uploaded images, and was set to Private.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/3696121/116915912-427fe980-ac12-11eb-91ee-09c86e7d2a4a.mp4

**Comment by JoshuaGoode** [comment]
Due to the restrictions Private on Atomic places right now, this is somewhat expected. Private is quite overbearing which is why Coming Soon v1 was replaced with v2 and also why we no longer set Atomic sites to be private by default. 

Private deactivates many modules and prevents Photon from working properly.

#### Possible solutions

I suppose a workaround might be to deactivate the Photon subsizes whenever Private mode is activated and then regenerate thumbnails.

Overall, Private is not user-friendly and can be a bit destructive. Perhaps we can remove the option for sites not private that launched after a specific date. 

#### Context
In some of the documentation for this, we mention:

> This feature does not work for private sites because Photon can only retrieve publicly available images.

> Private sites. The Photon service requires public access to images, so private sites are not supported.

Related internal threads:

- P9o2xV-WH-p2
- p7DVsv-9mK-p2

**Comment by inaikem** [comment]
Thanks for the context, @JoshuaGoode. Regarding this:

> Due to the restrictions Private on Atomic places right now, this is somewhat expected. Private is quite overbearing which is why Coming Soon v1 was replaced with v2 and also why we no longer set Atomic sites to be private by default.

Do you know if there are any plans to upgrade Private on Atomic to its own v2 as with Coming Soon? 

About this:

> In some of the documentation for this, we mention:
This feature does not work for private sites because Photon can only retrieve publicly available images.
Private sites. The Photon service requires public access to images, so private sites are not supported.

It feels like we need to surface the information in public documentation, too. The way content is affected on privacy switch is jarring and on first glance, can appear from a user perspective to be destructive.

**Comment by JoshuaGoode** [comment]
> Do you know if there are any plans to upgrade Private on Atomic to its own v2 as with Coming Soon?

I'm not aware of any WPCOM product team or pod actively working on that. This isn't in the infrastructure team's area and would be a change from a product team/pod. 

What would be in their area, perhaps, is making `wpcomsh`  or something turn the special Atomic Photon-subsizes feature off and run `media regenerate` when a site switches to Private mode.

> It feels like we need to surface the information in public documentation, too. The way content is affected on privacy switch is jarring and on first glance, can appear from a user perspective to be destructive.

This is the most visible issue. Private mode really makes things _**private**_ on Atomic so it will also break some things such as third-party theme demo importers and plugins that work with external requests.   Documentation might help but perhaps some kind of notice right on the setting itself might be better.


As for Photon not being compatible with Private mode, there are a few important discussions that I failed to mention in my previous comment.


- pMz3w-b58-p2
- p7DVsv-8Ue-p2#comment-29815
- P9HQHe-yS-p2

**Comment by JoshuaGoode** [comment]
Adding to my comments above:

There was a sprint to help with rendering and displaying images within certain blocks while in Private mode, since photon isn't available: https://github.com/Automattic/wp-calypso/issues/41272#issuecomment-811481221

However, the issue reported here is that the user switches to Private after uploading and using images.  Since the special Atomic Photon subsizes feature remains active, it cannot access the thumbnails necessary.  

Not to sound repetitive, I just want to highlight it so it doesn't get lost in my comments:  I still think setting something in `wpcomsh` or somewhere to force Photon Subsizes off and then `media regenerate` -- whenever a site sets itself to Private mode -- might be a good fix for now. 

cc: @brandonpayton

**Comment by edwinho89** [comment]
30507531-hc

The affected AT site takes a very long time for tiled gallery images to load as the site is currently private (not yet launched). (Though, it is more relating to this GH which has been addressed already: https://github.com/Automattic/wp-calypso/issues/41272 )

**Comment by JoshuaGoode** [comment]
Adding to my notes above:

Ideally, we will eventually be setting something to force Photon Subsizes off and then media regenerate whenever a site is changed to Private. 

For now, there are two options to resolve this when working with a user.

**1. The user should consider switching to Coming Soon mode or Public paired with a Coming Soon plugin. Private mode doesn't work well and deactivates many modules and features. For example, it deactivated VideoPress -- meaning all their video uploads will count against their storage.** 

Once set back to Coming Soon or Public, Photon subizes can work again and the issue will be resolved.

**2. The other option is to ping an Atomic Ambassador and have them deactivate Photon subsizes on the site.  After, `media regenerate` can then be run from CLI.**   

This will then allow the site to create and serve the thumbnails again and resolve the issue.  Doing this might cause the site to utilize more media storage space, especially if they have a lot of images.

**Comment by katiebethbrown** [comment]
Another report in 32534528-hc. We switched to Coming Soon to resolve.

**Comment by kylemcph** [comment]
Another report in 28814480-hc. We switched to public, loaded images in the media library, then switched back to private. I also suggested switching to Coming Soon to resolve.

**Comment by Agepeuve** [comment]
Another case in 33288403-hc. We ended up switching to Coming Soon for now.

**Comment by annbingle** [comment]
Got the same issue here 33392114-hc. Setting it to Coming Soon fixed it.

**Comment by Gustavo-Hilario** [comment]
Other reports here: 4735355-zen and 4731964-zen

**Comment by Gustavo-Hilario** [comment]
Another report here: 33861842-hc

**Comment by edwinho89** [comment]
35444389-hc

**Comment by Robertght** [comment]
5251577-zen

**Comment by aleone89** [comment]
hc-12455841

**Comment by Gustavo-Hilario** [comment]
Another report: 5305472-zen

**Comment by edwinho89** [comment]
35250223-hc

**Comment by Robertght** [comment]
35960978-hc

**Comment by JoshuaGoode** [comment]
We can reduce the impact a bit by [ensuring that Photon Subsizes is deactivated and thumbnails regenerated when a site is marked Private](https://github.com/Automattic/wp-calypso/issues/52520#issuecomment-837005821). Ideally, it would also be reactivated when set to Public.



@brandonpayton, I can try rounding up a WPCOM team to work on this but they might have questions for you.

I've started a new discussion

* p9F6qB-9PH-p2

Additional references

* P9HQHe-yS-p2#private-missing-images
* P9o2xV-WH-p2
* p7DVsv-9mK-p2
* pMz3w-b58-p2

**Comment by brandonpayton** [comment]
@JoshuaGoode, if there is an easy way to detect that a site is private, we can automatically disable Photon Subsizes via a filte. This seems like a good way to disable it without actually turning off the feature at the Atomic platform level. Then when the site is no longer private Photon Subsizes would begin working again.

Perhaps, setting a site to Private via Calypso could also queue a job to regenerate images via WP-CLI via SSH but **only** if Photon Subsizes is not already disabled at the Atomic platform level.

> @brandonpayton, I can try rounding up a WPCOM team to work on this but they might have questions for you.

That would be great. Thank you.

**Comment by Robertght** [comment]
5371875-zen

**Comment by annbingle** [comment]
5549864-zen Recommended them to either switch to Public or Coming Soon.

**Comment by wpshellbelle** [comment]
5588790-zen
Recommended switching to Coming Soon mode

**Comment by cuemarie** [comment]
This is a very common issue. When a site's plan expires and the site reverts, it is switched to "Private" mode. When a user resolves the plan issue and restores their site, the site privacy doesn't change, and many folks then reach out to support wondering why their images are broken.

An example here: 5784504-zd-woothemes

**Comment by pauljacobson** [comment]
I have another report here: 5869083-zen

Recommended that the user set site privacy to "Coming Soon" instead.

**Comment by kriskorn** [comment]
@ash1eygrace has developed a notice for this:

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/36432/218839777-c453f684-bf08-45af-880e-db0d354985f1.png">

- Project thread: pdtR3Z-1Aa-p2
- Public support article: https://wordpress.com/support/settings/privacy-settings/#private-mode-on-plugin-enabled-sites
- Calypso: https://github.com/Automattic/wp-calypso/pull/73197
- WP Admin: https://github.com/Automattic/wpcomsh/pull/1256

Marking this as solved.
