### ISSUE TITLE
Theme Showcase: Move "Install theme" button into header area

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#52521]
We made a point of moving the primary action for installing plugins to the header like so:

<img width="1080" alt="Screen Shot 2021-05-03 at 1 04 55 PM" src="https://user-images.githubusercontent.com/2124984/116918096-7b718b80-ac1d-11eb-8994-5f1470ef4393.png">

My Home and Support pages follow a similar pattern, so we should do the same for Themes (`/themes`):

<img width="1368" alt="Screen Shot 2021-05-03 at 10 19 25 AM" src="https://user-images.githubusercontent.com/2124984/116918098-7c0a2200-ac1d-11eb-8675-2d64ac1e0788.png">

This also removes the weird dead space between the currently active theme bar and the list of themes.

**Comment by Aurorum** [comment]
Do you think that moving the button upwards could revive #40791 too by adding a "Previous theme" button next to the "Install theme" one?

**Comment by kwight** [comment]
@Aurorum Let's stick to just this button change as a first step (the "Previous theme" button needs more thought) – thanks!

**Comment by DanielSmithMichigan** [comment]
Current branch: https://github.com/Automattic/wp-calypso/tree/update/52521_install-theme-button-2

(In progress, not a pull request yet)

**Comment by sixhours** [comment]
@DanielSmithMichigan You can go ahead and create a PR even if the branch isn't ready for review yet; that way tests can start running and a https://calypso.live URL will build. You can add an "In Progress" label so folks know it's not ready for review. :)
