### ISSUE TITLE
"Redirect" flag showing under the domain in the navigation menu for wp-admin pages

### ISSUE THREAD

**Issue by wprhunt** [Automattic/wp-calypso#52535]
## Steps to reproduce the behaviour

1. Log in to WordPress.com and access any site using a simple site and visit the /wp-admin for that site. (example: https://testingpremiumplan.wordpress.com/wp-admin/ )
2. Under the site title and domain, you will see the "Redirect" flag implying the site has a Site Redirect or that the primary domain set is a domain not pointed to WordPress.com

This only displays on pages that use the /wp-admin URL and does not affect Calypso pages and is causing confusion for some customers thinking that there is something wrong with the site.

I was able to replicate this on a customer's site and my own site.

### Context

Customer reported this in hc-28953694

#### Does this happen on simple or atomic sites or both?

Simple only as far as I have found.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
<img width="615" alt="Dashboard ‹ TEST PREM — WordPress 2021-05-03 14-01-39" src="https://user-images.githubusercontent.com/16481427/116933300-36972600-ac18-11eb-9193-52c500ecba1a.png">

**Comment by mreishus** [comment]
Possibly the same issue: https://github.com/Automattic/wp-calypso/issues/51530

**Comment by kwight** [comment]
Closing for #51530
