### ISSUE TITLE
Customizer: How do we present one-page themes?

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#52563]
It appears one-page themes have a special set of Content Options in the Customizer that hide some of the things we don't want enabled by default:

<img width="298" alt="Screen Shot 2021-05-04 at 10 11 11 AM" src="https://user-images.githubusercontent.com/2124984/117016984-3f900200-acc1-11eb-9bff-c103abb0fc5f.png">

This introduces a lot of confusion when you get to the Customizer. It's better explained by outlining the flow I took from signing up with a one-page theme (Blank Canvas, although it was Balan in signup) on a free plan.

1. Sign up for a new site, select Balan theme
2. Dropped into the editor; start editing the content. Not too bad so far...
3. I preview my changes:

<img width="1648" alt="Screen Shot 2021-05-04 at 10 09 32 AM" src="https://user-images.githubusercontent.com/2124984/117018200-48cd9e80-acc2-11eb-9645-9e6883f8265e.png">

I notice a button just kinda hanging out there called "Edit header". I don't know what this does (and I'm not pretending here, I really don't know 😆 ). When I click on it, I get a warning that I'm going to lose my changes. Yikes! So I close the preview and update what I've done so far, then because I'm curious, I go back to preview to click "Edit header".

4. I'm brought to the Customizer! But not to the Site Identity panel. There's no connection between what I've just clicked and how I'm supposed to edit my header. In fact, none of the options say "header":

<img width="1649" alt="Screen Shot 2021-05-04 at 10 10 31 AM" src="https://user-images.githubusercontent.com/2124984/117019059-107a9000-acc3-11eb-8292-ecd94b6ede53.png">

5. I know if I go to Site Identity I can edit my site title, for example. So I do that...but nothing on the front end of my site changes. I'm confused again.

6. I have an inkling that I can't see the header of my site because the theme I'm using doesn't show the header by default. Checking Content Options proves this to be true; I have to manually enable the site header checkbox for the Site Identity stuff to show up.

Steps 5 and 6 are things I know to do because I have insider info. I suspect most users get lost at step 4. So my questions are:

* Why do we show the Site Identity panel when it's effectively disabled for this theme unless I've made a concentrated effort to enable it?
* Why do we show the Edit header button when this theme doesn't support a traditional header?
* Why is the Edit header button in the preview panel?

**Comment by kwight** [comment]
@ianstewart and @sixhours can consider the best flows here.

**Comment by ianstewart** [comment]
Going back through this issue …

> notice a button just kinda hanging out there called "Edit header". I don't know what this does (and I'm not pretending here, I really don't know 😆 ).

Noting that we changed this. Looks like more people are using it with the better placement and clearer text. (Might be one or the other. I think it's both.)

![image](https://user-images.githubusercontent.com/545779/123163072-ef1e6080-d436-11eb-9b77-246d8e1055c0.png)

> When I click on it, I get a warning that I'm going to lose my changes. Yikes! So I close the preview and update what I've done so far, then because I'm curious, I go back to preview to click "Edit header".

This makes sense when you have unsaved changes.

![image](https://user-images.githubusercontent.com/545779/123163211-1412d380-d437-11eb-89d3-b89b2fa73bec.png)

Though I wonder what we can do to improve that in general. Warning users they're about to leave before pressing a button that causes their browser to alert them. Notably, I get a _different_ alert when I try to leave via the nav sidebar in the page editor?

![image](https://user-images.githubusercontent.com/545779/123163413-50deca80-d437-11eb-8e5b-edcb9c749c51.png)

And I get this alert again when I try and leave the Editor via the Add new page button.

![image](https://user-images.githubusercontent.com/545779/123163581-7cfa4b80-d437-11eb-8461-cbcb993e65ab.png)

(All the other exits from the Editor are links that open in a new tab or involve forcing a save change like Publish.)

Not sure why those are different. I think the alert for leaving to the dashboard is preferable. 

Weirdly I can also get the error after clicking update sometimes. We should make a separate issue for the warnings on exiting the editor.

This comment is long, I'll look at the actual issue in another comment. :D

**Comment by ianstewart** [comment]
> I know if I go to Site Identity I can edit my site title, for example. So I do that...but nothing on the front end of my site changes. I'm confused again.

> I have an inkling that I can't see the header of my site because the theme I'm using doesn't show the header by default. Checking Content Options proves this to be true; I have to manually enable the site header checkbox for the Site Identity stuff to show up.

1. I think with the change to the label from Edit Header to Customize this might "fix" this issue as it doesn't set an expectation that you'll be dropped in to editing your header.
2. With the issue that connects the site identity options to the content options for the header and footer we might have improved some of the findability there as well?

Obviously not ideal without a site editor. :D

**Comment by ianstewart** [comment]
@sixhours let me know if you think this one is a wont-fix for now and/or thoughts on breaking down some of the above into a distinct issue.

**Comment by sixhours** [comment]
I think the changes above pretty much addressed my confusion here, at least until there's a proper site editing flow.
