### ISSUE TITLE
Theme Showcase: Advanced themes section is unbalanced for Atomic sites

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#52566]
### Steps to reproduce the behavior

1. On a Business site with some custom themes installed...
2. Go to the Theme Showcase at `/themes`
3. Scroll down, and click "Show all themes"
4. Depending on how many themes you have installed and whether you have WooCommerce active, the grid will be off, with the installed/previously active themes at the top, followed by some whitespace, and a list of the available themes on WordPress.com.

<img width="1376" alt="Screen Shot 2021-05-04 at 11 22 27 AM" src="https://user-images.githubusercontent.com/2124984/117028002-4459b380-accb-11eb-82aa-d8fdd592594b.png">

<img width="1372" alt="Screen Shot 2021-05-04 at 11 26 53 AM" src="https://user-images.githubusercontent.com/2124984/117028355-a31f2d00-accb-11eb-8882-729803d73636.png">

#### What I expected to happen

Themes should appear in a neat grid.  Or we should find a way to show separately the themes you've installed/activated previously, rather than tacking them on at the top.

This appears to be unique to eCommerce and Atomic sites, since simple sites can't install custom themes.

**Comment by kwight** [comment]
We may just be missing a "installed themes" heading.

**Comment by kwight** [comment]
We might be missing these labels:

<img width="592" alt="Screen Shot 2021-05-17 at 10 27 29 AM" src="https://user-images.githubusercontent.com/349751/118531397-a74f3f80-b6fa-11eb-8404-1604bada2721.png">
