### ISSUE TITLE
Customizer: Using the color customizer sometimes removes colors

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#52562]
### Steps to reproduce the behavior

1. Go to `/new` and create a site using the Edison design.
2. Visit the customizer
3. Click colors & backgrounds
4. Click on the light blue color circle which matches the text of the blog title in the top left, the text of "Home" in the top right, and the underline under "Home" in the top right. It should read "Secondary Color"
under the 5 circles.
5. Click the red square.

Expect to see: All three elements (Title, Home, Home Underline) turn red.
Actually see: One element (Home Underline) turns red. The other two turn black, and cannot be changed via the secondary color anymore.

https://user-images.githubusercontent.com/937354/117019407-fb99fe80-acba-11eb-9ac5-c977a2659fa3.mp4

![2021-05-04_09-26](https://user-images.githubusercontent.com/937354/117019526-17050980-acbb-11eb-8c43-3507020776bd.png)

![2021-05-04_09-28](https://user-images.githubusercontent.com/937354/117019589-284e1600-acbb-11eb-98d5-36c1618e7f37.png)

**Comment by mreishus** [comment]
I discovered that the Primary Color actually controls the text of the title and "home" text. But, out of the box, the primary color is black, but those elements are blue. Maybe a theme or design issue?

**Comment by sixhours** [comment]
Maybe related to #52533

**Comment by DanielSmithMichigan** [comment]
This is the pull request I'm working out of: https://github.com/Automattic/themes/pull/4222

**Comment by DanielSmithMichigan** [comment]
New pull request: https://github.com/Automattic/themes/pull/4230. This only addresses a part of the issue.

I created this new issue to address the remainder of the issue: https://github.com/Automattic/themes/issues/4231

**Comment by kwight** [comment]
The above PRs and issues have been resolved, closing.
