### ISSUE TITLE
Signup: Consider a newer default theme than Hever.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52580]
Hever is the theme assigned to all new signups – since all new signups go through our pre-Gutenboarding flow that gives the user no choice over design.

<img width="1408" alt="Screen Shot 2021-05-04 at 1 50 26 PM" src="https://user-images.githubusercontent.com/349751/117068137-bb994280-acdf-11eb-8e60-cf07048380b5.png">

Let's consider a newer theme, with more vibrant imagery – something a little more inspiring and encouraging.

**Comment by kwight** [comment]
Even Twenty Twenty-One would be a more vibrant option (and more modern and maintained).

**Comment by ianstewart** [comment]
@kjellr we talked about this somewhere on a p2, I think. Do we have a theme demo site setup somewhere that is a simple blog that could work better. Perhaps one based on blank canvas but with the header turned on?

**Comment by kjellr** [comment]
Yeah, I'd suggested Blank Canvas Blocks with a simple header: 

<img width="670" alt="frame-1-2" src="https://user-images.githubusercontent.com/1202812/118649538-9b728480-b7b1-11eb-8f60-fc6082eff129.png">

If we'd like to change this up before Blank Canvas Blocks becomes a live theme, I recently discovered you can create basically the same thing using Spearhead: 

Desktop|Mobile
---|---
![Screen Shot 2021-05-19 at 08 19 41](https://user-images.githubusercontent.com/1202812/118650149-22276180-b7b2-11eb-96d5-6ba249113d4e.png)|![Screen Shot 2021-05-19 at 08 20 50](https://user-images.githubusercontent.com/1202812/118650150-22276180-b7b2-11eb-9ed6-6fbd88dbab09.png)

[Here's a demo site](https://defaultthemetesting52021.wordpress.com) if you'd like to see that in action (We could swap out the homepage with a blog if that's desired).

**Comment by ianstewart** [comment]
@alaczek we're going to replace Hever with Zoologist when that's ready. Let's close this one out when that launches.

**Comment by fushar** [comment]
We have replaced the default theme:

- Build flow: Hever => Zoologist => TT3, see #71025
- Write flow: Livro, see #67141

Closing this issue! cc: @autumnfjeld
