### ISSUE TITLE
Editor: applying an inline style from TinyMCE menu breaks Markdown footnotes

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/wp-calypso#5258]
To reproduce:

Write a post in the editor. Include footnotes as per https://en.support.wordpress.com/markdown-quick-reference/

apply "justify formatting"
![see screen shot](http://cld.wthms.co/1iKUr/4OXnfVMH+)

expected: mardown parsed, footnotes added
actual: markdown is not applied

2644199-t

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the steps provided.

For reference, here's how the HTML looks for this case:

<img width="1280" alt="screen shot 2016-08-30 at tue aug 30 3 50 01 pm" src="https://cloud.githubusercontent.com/assets/1119271/18108482/ab7d0480-6ec9-11e6-8476-0a42ca64dcb2.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10298 using Firefox 48.0.1 on Mac OS X 10.11.6</sup>
