### ISSUE TITLE
Editor: Provide a direct path to the Customizer.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52586]
When a user ends up in the block editor (intentionally or unintentionally), and wants to edit any aspect of their site managed by the Customizer, they have no direct path to that tool (nor any hints of how to get there otherwise). Let's consider adding a path in some way.

**Comment by kwight** [comment]
I dunno – add a menu item to the Editor section? It would be (somewhat) discoverable, without adding something to the main UX view. ¯\_(ツ)_/¯

<img width="496" alt="Screen Shot 2021-05-04 at 2 43 51 PM" src="https://user-images.githubusercontent.com/349751/117074059-b2ac6f00-ace7-11eb-9358-b3357aa3c9d4.png">

**Comment by jordesign** [comment]
I love this idea. In my testing I noted that while getting users straight into editing content is good - it means there is NO clear way to edit the 'design'/theme of the site from there.

I mentioned this in Slack - but a real world example was my wife starting a site - and wanting to be able to Add a logo and set up brand colors immediately. Without guidance - there is NO way to know how to do that.

My 2c is that even having a menu item 'Site Customizer' still requires some level of knowledge of what the Customizer is/does.

**Comment by kwight** [comment]
This would be better expressed in onboarding videos or guides.
