### ISSUE TITLE
After page edit: not obvious what "Launch" does

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#52590]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/10274366/117079805-88b87400-ad0a-11eb-8972-ac7a4f5f6158.png">

**Context:**

Blog is private. User is editing a page and wants to save their changes. Options at the top of the page are "Update" and "Launch." If the user is not aware of the difference between a "public" and a "private" blog, then it's not clear which button is going to save my changes.

The meaning of the word "launch" isn't necessarily obvious and relies on the user understanding some of the context. Also, the button doesn't specify what is being "launched" - is it the post or the blog?

Being a newer user myself, I've found myself confused a few times looking at these two buttons.

**Suggestions:**
Replace "Launch" with "Go Public"?
Replace "Update" with "Save"?

**Comment by razvanpapadopol** [comment]
Fixed by removing the Launch button in https://github.com/Automattic/wp-calypso/pull/53115
