### ISSUE TITLE
Editing Toolkit Fatal on WoA sites: Calling non-existent get_blog_details() function

### ISSUE THREAD

**Issue by brandonpayton** [Automattic/wp-calypso#52599]
### Steps to reproduce the behavior

1. Pick a WordPress.com-on-Atomic (WoA) test site
2. Open the post editor
3. Use WP-CLI access to list php-errors on the site via `wp php-errors`
4. See the fatal error logging like:

```
[05-May-2021 01:47:36 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function A8C\FSE\get_blog_details() in /wordpress/plugins/full-site-editing/3.5834/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-nux-status-controller.php:86
Stack trace:
#0 /wordpress/core/5.7.1/wp-includes/rest-api/class-wp-rest-server.php(1139): A8C\FSE\WP_REST_WPCOM_Block_Editor_NUX_Status_Controller->get_nux_status(Object(WP_REST_Request))
#1 /wordpress/core/5.7.1/wp-includes/rest-api/class-wp-rest-server.php(985): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wpcom/v2/block...', Array, NULL)
#2 /wordpress/core/5.7.1/wp-includes/rest-api/class-wp-rest-server.php(412): WP_REST_Server->dispatch(Object(WP_REST_Request))
#3 /wordpress/core/5.7.1/wp-includes/rest-api.php(354): WP_REST_Server->serve_request('/wpcom/v2/block...')
#4 /wordpress/core/5.7.1/wp-includes/class-wp-hook.php(292): rest_api_loaded(Object(WP))
#5 /wordpress/core/5.7.1/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#6 /wordpress/core/5.7.1/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
#7 /wordpress/core/5.7.1/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#8 /wordpress/core/5.7.1/wp-includes/class-wp.php(750): WP->parse_request('')
#9 /wordpress/core/5.7.1/wp-includes/functions.php(1291): WP->main('')
#10 /wordpress/core/5.7.1/wp-blog-header.php(16): wp()
#11 /wordpress/core/5.7.1/index.php(17): require('/wordpress/core...')
#12 {main}
  thrown in /wordpress/plugins/full-site-editing/3.5834/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-nux-status-controller.php on line 86
```

#### What I expected to happen

The editor would hit the site's `/wp-json/wpcom/v2/block-editor/nux?_locale=user` endpoint, and the endpoint would not fatal.

#### What actually happened

The endpoint fatals. It might be because ms-blogs.php, the file that defines `get_blog_details()`, is not required outside of multisite (which WoA sites are not). I'm not 100% on that.

#### Does this happen on simple or atomic sites or both?

Atomic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

With a basic test, the editor seems to work OK despite the issue.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

cc @roo2

**Comment by roo2** [comment]
Thank you for reporting and digging into this @brandonpayton!

I've applied a simple fix to check for the existence of the get_blog_details function and this fixed the error on atomic sites

Again, thanks for investigating this

https://github.com/Automattic/wp-calypso/pull/52653

**Comment by brandonpayton** [comment]
Thank you, @roo2!
