### ISSUE TITLE
Theme Showcase: Make it easier to see my own content in the theme previews

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#52592]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/10274366/117081878-e0f17500-ad0e-11eb-8a0c-126648a30814.png">

I would like to optionally see my own content instead of the demo content in these theme previews.

Alternately, if we could make it easier to try out a lot of different themes, I think that might be helpful.

Possibly related issue: [Try & Customize option missing for recommended themes](https://github.com/Automattic/wp-calypso/issues/52591)

**Comment by ianstewart** [comment]
Yes. :D I'm not sure about on this screen but this could be an option on the theme preview screens? We should take a look at this one.

**Comment by davipontesblog** [comment]
I believe we can close this issue in favor of https://github.com/Automattic/wp-calypso/issues/52792
Thoughts @ianstewart ?

**Comment by ianstewart** [comment]
I'm going to close it with this comment: I think it's still worthwhile pursuing. 

@onuro I could see it being neat for future iterations — especially where block themes are concerned — to allow different previewing. Perhaps someone wants to look at a grid of live previews with different global styles applied for example. (That's what seeing your own content here would mean.) Or perhaps they want to investigate page templates provided by themes.

That's a lot. Would be good to pull out some ideas from a larger vision like that.

**Comment by onuro** [comment]
That would be phenomenal. Backlogged for the future Theme Showcase iterations.
