### ISSUE TITLE
Feature Request: More tooling to control image dimensions when cropping site logo.

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#52594]
Context: I've selected a theme such as "Spatial." I've clicked "Select logo" from within customizer. I selected a pre-existing image and now I'm cropping that image. 

Any/all of these options might help out in this process:
1. Specify a width/height
2. Specify a ratio of width to height
3. Lock the aspect ratio so that my cropped region is a square
4. Let me preview the site as I'm cropping the image
6. Trim white/transparent space
5. If this is a theme which is going to resize the image after I crop it, let me know.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/10274366/117082313-ea2f1180-ad0f-11eb-9770-56039a19996c.png">

**Comment by ianstewart** [comment]
I could see us tackling this in core, perhaps? Perhaps we could take a look at swapping in image blocks or logo blocks to handle this here as well? Worth taking a look at the core blocks for this functionality.

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/52537
