### ISSUE TITLE
Video Block: Include settings to resize video

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#52605]
### Steps to reproduce the behavior

Add any video on your site using the Video block. (videos hosted with VideoPress) 

#### What I expected to happen
I would like to see a block setting to edit the size of videos. It currently enforces full size.

#### What actually happened
It is currently not avaiable and users need to do the roundabout method of creating shortcodes and then using Shortcode block

### Context
#7526401-hc

#### Browser / OS version
Any

#### Is this specific to the applied theme? Which one?
All

#### Does this happen on simple or atomic sites or both?
All

#### Is there any console output or error text?
N. A.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

**Comment by porada** [comment]
@nagpai — Just to confirm: the core Video and VideoPress blocks are two separate blocks. Is this strictly about VideoPress or both?

**Comment by porada** [comment]
Correction: VideoPress isn’t even its own block—it’s turns into an instance of the Embed block.

**Comment by xpurichan** [comment]
Also requested in 4144298-zd.

One easier workaround that we can recommend for now is to place the video inside of a single column block. Previously videos did not resize properly in column blocks, but this was fixed (https://github.com/Automattic/jetpack/issues/17465).

**Comment by nagpai** [comment]
It looks like this would need an enhancement in the WordPress core Video block. Am I right?

The workaround suggested by @xpurichan works well. It would be a great enhancement to have the ability to resize the video easily like an image block, or by specifying size in block settings.

**Comment by nagpai** [comment]
I have created a featured request for Core here
https://core.trac.wordpress.org/ticket/53864#ticket

**Comment by Gustavo-Hilario** [comment]
9084528-hc

+1 one to this feature. The workaround is great, but it would be more intuitive to have the resize option on the Video block itself.

**Comment by nagpai** [comment]
Issue fixed by this 
1320-gh-Automattic/en.support-docs-content
