### ISSUE TITLE
Logged out pricing toggle: scrolls to top

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#52609]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/pricing
2. Scroll down a bit and click on "Pay monthly" in the pricing toggle.

#### What happened

The page scrolls to the top

#### What I expected to happen

For the page to not scroll to the top

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![pricingtoggle](https://user-images.githubusercontent.com/1269602/117123504-bbb74200-adb4-11eb-9584-20e0dbb405d5.gif)

**Comment by porada** [comment]
Addressed in D61015-code.

**Comment by porada** [comment]
It’s [now fixed](https://wordpress.com/pricing).
