### ISSUE TITLE
Allow Site Logo to be resized (after upload) in the Customizer

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#52615]
A very common request which HEs provide CSS solutions for is to resize the Site Logo within the header.
User's like to be able to be specific about the overall size of the logo to ensure readability and overall balance.

Would it be possible to have an option within the customizer which allowed them to resize the logo (in position) after it has been uploaded. Something as simple a a 'max-width' field would allow us to add inline CSS or something similar?

**Comment by kathrynwp** [comment]
Or rather than CSS, add a logo resizer, like Radcliffe 2 has.

![Customize__Radcliffe_2](https://user-images.githubusercontent.com/7662449/117573408-a2104600-b0a5-11eb-9351-7b22ed40401b.jpg)

**Comment by kathrynwp** [comment]
It looks like it was in the original plans for the Varia child themes to add a logo resizer similar to Radcliffe 2's, but it did not end up panning out.

As the Varia themes are still in heavy use – and part of the WordPress.com signup flow – let's revisit whether we can make it happen now.

Here is the original PR: https://github.com/Automattic/themes/pull/1320

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/52537
