### ISSUE TITLE
eCommerce: "WordPress dashboard" link first opens wp-admin home, then Calypso home

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#52616]
On Atomic site with eCommerce plan, from the WooCommerce sidebar, it's possible to end up in wp-admin home instead of Calypso home. That's super confusing and affects our highest-paying customers.

### Steps to reproduce the behavior

1. Create new eCommerce plan site
2. Click on "WordPress dashboard" from the sidebar in WooCommerce
   
   <img width="525" alt="Screenshot 2021-05-05 at 15 22 59" src="https://user-images.githubusercontent.com/87168/117140179-c9b99280-adb5-11eb-9683-959d434e1a0e.png">

3. End up at `/wp-admin/`, note how "my home" in the sidebar is selected
    
<img width="1538" alt="Screenshot 2021-05-04 at 18 38 39" src="https://user-images.githubusercontent.com/87168/117140232-d9d17200-adb5-11eb-8e49-3244acbf8ee3.png">

4. Press that "my home" link in the sidebar again, and end up at the calypso version:
<img width="1677" alt="Screenshot 2021-05-05 at 15 24 36" src="https://user-images.githubusercontent.com/87168/117140353-fd94b800-adb5-11eb-93df-b6dea8153ce3.png">

#### What I expected to happen

I expected never to see the confusing wp-admin homepage and always see Calypso my home instead.

#### What actually happened

wp-admin 🤯 😭 

cc @tjcafferkey hi! would this be something for Atomic/Simple parity pod?

**Comment by jordesign** [comment]
I'm no longer able to recreate this - in all my testing I am returned to My Home consistently (as expected)
