### ISSUE TITLE
Domain suggestions are not loaded when clicking Back from checkout page

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#52610]
### Steps to reproduce the behavior

1. Signup as a new user from https://wordpress.com, select a paid plan and proceed to the checkout page
2. Click on the browser back button

#### What I expected to happen

To be taken to the domain step of signup flow with initial suggestions loaded. You can check the expected behaviour in p7DVsv-9p1-p2.

#### What actually happened

The domain suggestions are not loading.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![checkoutback](https://user-images.githubusercontent.com/1269602/117124093-84956080-adb5-11eb-8a3b-a4fe9b965d39.gif)

**Comment by taggon** [comment]
The fix has been shipped! :)
