### ISSUE TITLE
Editor: page parent selector should include non-page menu items

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5261]
I believe the primary purpose of selecting a page parent is to add a new page into the menu hierarchy (maybe I'm wrong and there's more going on). In that case, I think the parent selector should include non-page menu items, like links or top-level placeholders. I'm adding a page to my blog (Triton) and I'd like to set it as a subnav item in an existing non-page menu item. But there appears to be no way to do that from here. @aduth I'm assigning to you for your feedback/confirmation and to set priority. Feel free to reassign/reshuffle.

![page parent](https://cloudup.com/c3WExpRk7Lh+)

EDIT: I'll add a little more color here. As a user, the lack of being able to place this page in the menu hierarchy prior to publishing makes me hesitant to publish it because I would fear that it will show up in the primary navigation.

cc @mtias

**Comment by aduth** [comment]
I don't believe it's the case that assigning a page parent is at all related to menus. In-fact, even with "Auto-add pages" menu setting enabled, child pages are not automatically added (only new top-level pages). Rather, my understanding of page parent is that it's serves an organizational purpose (page list view ordering) and in generating URLs (e.g. `/top-level/child-page`).

FWIW, the equivalent field in core uses [`wp_dropdown_pages`](https://codex.wordpress.org/Function_Reference/wp_dropdown_pages) which also does not include non-page types.

**Comment by rralian** [comment]
Makes sense, though obviously that wasn't my assumption as a user. I would have benefitted from a (?) tooltip in this case.

**Comment by aduth** [comment]
>I would have benefitted from a (?) tooltip in this case.

Makes sense to me, and surprised it doesn't exist already given that we do in many other cases in the editor. Want to repurpose this issue, or create a separate one?

**Comment by rralian** [comment]
I'll add a new one.
