### ISSUE TITLE
Editor: page parent section should have an explanation tooltip

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5262]
It's not totally clear what setting a page parent will do. See #5261 where I had assumed this would add a page to the menu hierarchy. Could be just me, but I think that's the main thing a user is concerned with when writing a page. Not understanding this makes me hesitant to publish the page.

cc @aduth

**Comment by aduth** [comment]
While we're at it, should probably add tips for the other two page options, "Template" and "Order".

**Comment by rachelmcr** [comment]
Confirmed this issue still exists as described.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by creativecoder** [comment]
With the [Calypso editor deprecated](https://github.com/Automattic/wp-calypso/milestone/309?closed=1), I don't think this issue is relevant any longer. But please feel free to re-open it if that's incorrect.
