### ISSUE TITLE
Themes: Consider retiring more themes.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52626]
We need to retire themes that don't properly support blocks, of which we don't intend to fix.

Examples:
* Radcliffe 2

**Comment by kwight** [comment]
We have about 200 themes, and we don't want to drop down much lower than that (and some of the free themes are not so good at block support).

**Comment by youbrokesomething** [comment]
While Radcliffe 2 hasn't been retired, a few other themes were retired after this ticket was opened. I'm going to close this for now.
