### ISSUE TITLE
Gallery Block: Image Size removed after 10.5.0 version

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#52647]
### Steps to reproduce the behavior

1. Create a page or post
2. Add the Gallery block
3. Select some images
4. Select one of the images added in the block

#### What I expected to happen
To see the Image Size option on the block's settings.

#### What actually happened
It seems that option was removed after the 10.5.0 version.

#### Does this happen on simple or atomic sites or both?
Tested on Simple and WordPress.org. It seems it was available on 10.4.1, but was removed on 10.5.0.

#### Screenshot
This is what we had in the block on 10.4.1:

![Gutenberg 10 4 1](https://user-images.githubusercontent.com/16104522/117353754-e671cb00-ae86-11eb-9b97-691605e2fa09.jpg)

Which is now gone on 10.5.0+:
![Gutenberg 10 5 0](https://user-images.githubusercontent.com/16104522/117353762-e83b8e80-ae86-11eb-8e24-b59f13f2510a.jpg)

Still shows _"Thumbnails are cropped to align."_, although you can't change it.

It's also shown on the GIF here: https://wordpress.org/support/article/gallery-block/#block-toolbar

Reported on 3969630-zd-woothemes

**Comment by kingsleyinfo** [comment]
The user responded to the ticket asking for an update or a workaround as this is important to them. Do we have any workaround on what they can do instead? 

Note:
_Please provide an update to the user once we have one._

**Comment by kosiew** [comment]
Created this as Gutenberg issue:

https://github.com/WordPress/gutenberg/issues/31880
