### ISSUE TITLE
Atomic: Feedback CTP Export CSV submenu with a blank page when there're no submissions

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#52661]
### Steps to reproduce the behavior

1. Go to an AT or Jetpack site WP-Admin
2. Make sure you don't have any feedback form submissions (in the first submenu of Feedback CTP)
3. The `Feedback > Export` menu is displayed in the navigation.
4. Click on the `Feedback > Export CSV` submenu

#### What I expected to happen
Since on Simple sites the submenu is not displayed, we should remove it when there are no submissions.

#### What actually happened
The `Export CSV` submenu is displayed even though there are no submissions, displaying a blank page.

#### Does this happen on simple or atomic sites or both?
Only on Atomic and JP.

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
On every AT site that does not have any feedback form submissions.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screenshot 2021-05-07 at 14 07 57](https://user-images.githubusercontent.com/995955/117441192-afaabc00-af3d-11eb-8e8f-d1e5ef8f1f9a.png)

**Comment by cpapazoglou** [comment]
Noting that Simple Sites do not have the "Export CSV" menu item (at least with there're no submissions)
![](https://cln.sh/8RixEi+)

**Comment by tjcafferkey** [comment]
Remove the menu item when there is nothing to export
