### ISSUE TITLE
Action Bar Not Working on Safari when Tracking Blocked

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/wp-calypso#52683]
### Steps to reproduce the behavior

* Setup a WordPress.com site with a custom domain.
* Open Safari.
* Enable "Prevent cross-site tracking"
* Clear cache and cookies.

To test:

* Visit site
* Login

Action Bar does not change

#### What I expected to happen

Once a user logs in, the "Follow..." bar should update to reflect it.

#### What actually happened

The Action Bar does not update after login. It continues to show the "Follow..." text as if the user was logged out.

#### Browser / OS version

Safari / MacOS

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Simple. Did not text on Atomic.

**Comment by bobmatyas** [comment]
Reported on 3955621-zen

**Comment by niranjan-uma-shankar** [comment]
Hey @bobmatyas , I'm closing this issue as a duplicate of https://github.com/Automattic/wp-calypso/issues/33077. This issue has been fixed as noted in [this comment.](https://github.com/Automattic/wp-calypso/issues/33077#issuecomment-851240339).
