### ISSUE TITLE
Email: Add to the Upgrades Menu

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#52682]
### What
For increased visibility, we could have an Email option, under the Upgrades menu.

### Why
It would bring more visibility to this feature, for users that have an email license, and might probably help sell more licenses. At this moment you have to go to Upgrades > Domains, which isn't intuitive, click on the domain, then on _"Manage your email accounts"_, and then you're redirected to a new page when clicking on _"Manage your email settings and accounts"_.

Full path: Upgrades > Domains > domain.com > Manage your email accounts > Manage your email settings and accounts

### How
Something like this:

![Screen Shot 2021-05-07 at 15 15 50](https://user-images.githubusercontent.com/16104522/117494814-3b771500-af4b-11eb-8b5f-a218ee3bc1cd.png)

**Additional context**
User requested here: 29461278-hc

**Comment by daledupreez** [comment]
We're working on this and expect to have it launched to all users early next week! 😁

**Comment by daledupreez** [comment]
I am going to close this out as we rolled this out to all users on 2021-05-25. (The change was made in some of our APIs.)
