### ISSUE TITLE
Framework: Replace component-* (and click-outside) modules with "React-friendly" modules.

### ISSUE THREAD

**Issue by furf** [Automattic/wp-calypso#5268]
# Objective

> ...replace the usage of come [sic] “component-*” libraries with more React-friendly # alternatives

To replace `component-*` (and `click-outside`) modules with modules (3rd-party or internal) that meet the following criteria:
- [x] Server-side rendering support
- [x] Source is actively maintained (if 3rd-party)

_Additional criteria to be considered:_
- [ ] Accessibility
- [ ] Code cleanliness
- [ ] Consistency and reasonability of API
- [ ] Documentation
- [ ] Feature-completeness
- [ ] i18n/L10n
- [ ] Security
- [ ] Test coverage
- [ ] Themability
## Modules under review:
- `click-outside`
- `component-bind`
- `component-classes`
- `component-closest`
- `component-css`
- `component-delegate`
- `component-each`
- `component-emitter`
- `component-event`
- `component-events`
- `component-file-picker`
- `component-indexof`
- `component-inherit`
- `component-matches-selector`
- `component-props`
- `component-query`
- `component-raf`
- `component-tip`
- `component-type`
- `component-uid`
# Background

Original components from the ([component](https://github.com/component/)) library were designed to be compatible with a client-side built tool, specifically _browserify_, and executed in the browser. Some components rely on access to global `window` object, which is not supported when server-side rendering. One of the workarounds for environment (client vs. server) and dependency resolution involves a fragile/dirty `try-catch` solution. The solution should remove any clumsy workarounds and use familiar syntax/design patterns to React and the WP code base.
# Risks
- Replacement will be buggy and/or introduce regressions.
- (3rd-party) Replacement will not be feature-complete and require additional development.
- Replacement project maintainer will be unresponsive or unavailable.
- Scope of replacement will be unexpectedly large.
- Broad scope of project could touch a lot of files in active development and increase complexity of merge resolutions/risk of merge conflicts.
# Approach
- [x] Determine the purpose and reach of each module.
- [ ] Consider other UI components for inclusion in this project.
- [ ] Consider ad hoc replacement vs. adoption/creation of a UI component library.
- [ ] Evaluate 3rd-party replacements and consider 3rd-party vs. internal alternatives.
- [ ] Deprecate obsolescent modules.
- [x] Prioritize modules for replacement.

/re #4072 and #5181
/cc @nb @ockham @seear @mtias

**Comment by furf** [comment]
## Summary of Usage
Only 8 of 20 modules in use; 12 modules are not referenced in codebase (outside of npm-shrinkwrap.json and package.json).

### Referenced
* **click-outside** (2)
  * *client/components/dialog/dialog-base.jsx*
  * *client/components/popover/index.jsx*
* **component-classes** (13)
  * *client/boot/index.js*
  * *client/components/dialog/dialog-base.jsx*
  * *client/lib/accept/test/index.js*
  * *client/lib/accessible-focus/index.js*
  * *client/lib/layout-focus/index.js*
  * *client/my-sites/upgrades/domain-management/list/test/index.js*
  * *client/notifications/index.jsx*
  * *client/post-editor/test/post-editor.jsx*
  * *client/reader/following-stream/post.jsx*
  * *client/reader/full-post/index.jsx*
  * *client/reader/post-images/index.jsx*
  * *server/bundler/loader.js*
  * *test/test/helpers/mocks/component-classes.js*
* **component-closest** (11)
  * *client/components/dialog/dialog-base.jsx*
  * *client/components/tinymce/plugins/editor-button-analytics/plugin.js*
  * *client/components/tinymce/plugins/media/plugin.jsx*
  * *client/me/billing-history/transactions-header.jsx*
  * *client/post-editor/media-modal/index.jsx*
  * *client/post-editor/media-modal/test/index.jsx*
  * *client/reader/following-stream/post.jsx*
  * *client/reader/following-stream/x-post.jsx*
  * *client/reader/full-post/index.jsx*
  * *client/reader/sidebar/index.jsx*
  * *client/reader/sidebar/reader-sidebar-tags/index.jsx*
* **component-event** (1)
  * *client/lib/accept/test/index.js*
* **component-file-picker** (1)
  * *client/components/file-picker/index.jsx*
* **component-matches-selector** (4)
  * *client/lib/accept/test/index.js*
  * *client/my-sites/plugins/plugin-autoupdate-toggle/test/index.jsx*
  * *client/my-sites/plugins/plugins-list/test/index.jsx*
  * *client/post-editor/test/post-editor.jsx*
* **component-query** (4)
  * *client/lib/accept/test/index.js*
  * *client/my-sites/plugins/plugin-autoupdate-toggle/test/index.jsx*
  * *client/my-sites/plugins/plugins-list/test/index.jsx*
  * *client/post-editor/test/post-editor.jsx*
* **component-tip** (3)
  * *client/components/popover/index.jsx*
  * *client/my-sites/upgrades/domain-management/list/test/index.js*
  * *test/test/helpers/mocks/component-tip.js*

### Unreferenced
* **component-bind**
* **component-css**
* **component-delegate**
* **component-each**
* **component-emitter**
* **component-events**
* **component-indexof**
* **component-inherit**
* **component-props**
* **component-raf**
* **component-type**
* **component-uid**

## Detailed Search Results
78 results found in 32 files for (?:click-outside|component-(?:bind|classes|closest|css|delegate|each|emitter|event|events|file-picker|indexof|inherit|matches-selector|props|query|raf|tip|type|uid))


* **client/boot/index.js(1)**
   * 9 classes = require( 'component-classes' ),
* **client/components/dialog/dialog-base.jsx(3)**
   * 6 clickOutside = require( 'click-outside' ),
   * 7 closest = require( 'component-closest' ),
   * 10 componentClasses = require( 'component-classes' );
* **client/components/file-picker/index.jsx(1)**
   * 9 import pick from 'component-file-picker';
* **client/components/popover/index.jsx(2)**
   * 4 import clickOutside from 'click-outside';
   * 9 import Tip from 'component-tip';
* **client/components/tinymce/plugins/editor-button-analytics/plugin.js(1)**
   * 5 import closest from 'component-closest';
* **client/components/tinymce/plugins/media/plugin.jsx(1)**
   * 15 closest = require( 'component-closest' );
* **client/lib/accept/test/index.js(4)**
   * 23 mockery.registerSubstitute( 'event', 'component-event' );
   * 24 mockery.registerSubstitute( 'matches-selector', 'component-matches-selector' );
   * 25 mockery.registerSubstitute( 'query', 'component-query' );
   * 26 mockery.registerMock( 'component-classes', function() {
* **client/lib/accessible-focus/index.js(1)**
   * 4 var classes = require( 'component-classes' );
* **client/lib/layout-focus/index.js(1)**
   * 4 var classes = require( 'component-classes' );
* **client/me/billing-history/transactions-header.jsx(1)**
   * 8 closest = require( 'component-closest' ),
* **client/my-sites/picker/picker.jsx(1)**
   * 6 wrapWithClickOutside = require( 'react-click-outside' ),
* **client/my-sites/plugins/plugin-autoupdate-toggle/test/index.jsx(2)**
   * 34 mockery.registerSubstitute( 'matches-selector', 'component-matches-selector' );
   * 35 mockery.registerSubstitute( 'query', 'component-query' );
* **client/my-sites/plugins/plugins-list/test/index.jsx(2)**
   * 21 mockery.registerSubstitute( 'matches-selector', 'component-matches-selector' );
   * 22 mockery.registerSubstitute( 'query', 'component-query' );
* **client/my-sites/upgrades/cart/cart-items.jsx(1)**
   * 28 // and then click-outside from Popover would consider it as an outside click,
* **client/my-sites/upgrades/domain-management/list/test/index.js(2)**
   * 29 require( 'test/helpers/mocks/component-classes' )( mockery );
   * 30 require( 'test/helpers/mocks/component-tip' )( mockery );
* **client/notifications/index.jsx(1)**
   * 8 classes = require( 'component-classes' ),
* **client/post-editor/media-modal/index.jsx(1)**
   * 10 closest = require( 'component-closest' ),
* **client/post-editor/media-modal/test/index.jsx(1)**
   * 55 mockery.registerMock( 'component-closest', {} );
* **client/post-editor/test/post-editor.jsx(3)**
   * 31 mockery.registerSubstitute( 'matches-selector', 'component-matches-selector' );
   * 32 mockery.registerSubstitute( 'query', 'component-query' );
   * 33 mockery.registerMock( 'component-classes', () => {} );
* **client/reader/following-stream/post.jsx(2)**
   * 9 closest = require( 'component-closest' ),
   * 10 classes = require( 'component-classes' ),
* **client/reader/following-stream/x-post.jsx(1)**
   * 8 closest = require( 'component-closest' ),
* **client/reader/full-post/index.jsx(2)**
   * 8 classes = require( 'component-classes' ),
   * 9 closest = require( 'component-closest' ),
* **client/reader/post-images/index.jsx(1)**
   * 8 classes = require( 'component-classes' ),
* **client/reader/sidebar/index.jsx(1)**
   * 5 import closest from 'component-closest';
* **client/reader/sidebar/reader-sidebar-tags/index.jsx(1)**
   * 5 import closest from 'component-closest';
* **CREDITS.md(1)**
   * 1279 ### https://github.com/kentor/react-click-outside
* **npm-shrinkwrap.json(27)**
   * 479 "click-outside": {
   * 528 "component-bind": {
   * 531 "component-classes": {
   * 534 "component-closest": {
   * 537 "component-css": {
   * 540 "component-delegate": {
   * 543 "component-each": {
   * 546 "component-emitter": {
   * 549 "component-event": {
   * 552 "component-events": {
   * 555 "component-file-picker": {
   * 558 "component-indexof": {
   * 561 "component-inherit": {
   * 564 "component-matches-selector": {
   * 567 "component-props": {
   * 570 "component-query": {
   * 573 "component-raf": {
   * 576 "component-tip": {
   * 579 "component-type": {
   * 582 "component-uid": {
   * 859 "component-emitter": {
   * 2978 "react-click-outside": {
   * 3338 "component-emitter": {
   * 3366 "component-emitter": {
   * 3377 "component-emitter": {
   * 3501 "component-emitter": {
   * 3539 "component-emitter": {
* **package.json(7)**
   * 27 "click-outside": "1.0.4",
   * 30 "component-classes": "1.2.6",
   * 31 "component-closest": "0.1.4",
   * 32 "component-file-picker": "0.2.1",
   * 33 "component-tip": "3.0.3",
   * 34 "component-uid": "0.0.2",
   * 87 "react-click-outside": "2.1.0",
* **server/bundler/loader.js(1)**
   * 15 "\tclasses = require( 'component-classes' ),",
* **test/test/helpers/mocks/component-classes.js(1)**
   * 11 mockery.registerMock( 'component-classes', MockComponentClasses );
* **test/test/helpers/mocks/component-tip.js(2)**
   * 4 const debug = debugFactory( 'calypso:test:mocks:component-tip' );
   * 15 mockery.registerMock( 'component-tip', MockTip );
* **test/test/helpers/mocks/README.md(1)**
   * 9 const mockComponentClasses = require( 'test/helpers/mocks/component-classes' );

**Comment by furf** [comment]
## Summary of Functionality

**click-outside** The inverse of the DOM "click" event. For those times when you want a callback invoked when a DOM element _was not_ clicked, you can use this `click-outside` module.

**component-classes** Cross-browser element class manipulation, utilizing the native `.classList` when possible. This is not designed to be a `.classList` polyfill.

**component-closest** Finds the closest parent that matches a selector. Similar to jQuery's `$.fn.closest` and `$.fn.parents`. 

**component-event** Element event binding component.

**component-file-picker** Opens a file picker dialog upon being called. Doesn't need a DOM
  element or pre-existing `<input type="file">`.

**component-matches-selector** Check if an element matches a given selector.

**component-query** Query the DOM with selector engine fallback support. This abstraction allows all other components that require dom querying to indirectly support old browsers, without explicitly adding support for them.

**component-tip** Tip component. Inspired by [tipsy](https://github.com/jaz303/tipsy) without the weird jQuery API.

**Comment by furf** [comment]
Confirmed with a simple walker/AST-parser that the following 17 files contain require/import statements:

* _client/boot/index.js_
* _client/components/dialog/dialog-base.jsx_
* _client/components/file-picker/index.jsx_
* _client/components/popover/index.jsx_
* _client/components/tinymce/plugins/editor-button-analytics/plugin.js_
* _client/components/tinymce/plugins/media/plugin.jsx_
* _client/lib/accessible-focus/index.js_
* _client/lib/layout-focus/index.js_
* _client/me/billing-history/transactions-header.jsx_
* _client/notifications/index.jsx_
* _client/post-editor/media-modal/index.jsx_
* _client/reader/following-stream/post.jsx_
* _client/reader/following-stream/x-post.jsx_
* _client/reader/full-post/index.jsx_
* _client/reader/post-images/index.jsx_
* _client/reader/sidebar/index.jsx_
* _client/reader/sidebar/reader-sidebar-tags/index.jsx_

The remainder, found via text search, are tests and may/may not need to be addressed:

* _client/lib/accept/test/index.js_
* _client/my-sites/plugins/plugin-autoupdate-toggle/test/index.jsx_
* _client/my-sites/plugins/plugins-list/test/index.jsx_
* _client/my-sites/upgrades/domain-management/list/test/index.js_
* _client/post-editor/media-modal/test/index.jsx_
* _client/post-editor/test/post-editor.jsx_
* _test/test/helpers/mocks/component-classes.js_
* _test/test/helpers/mocks/component-tip.js_

And then there's this guy who concatenates JavaScript (including requires) for dynamic execution:

* _server/bundler/loader.js_

**Comment by furf** [comment]
Since **component-event**, **component-matches-selector** and **component-query** are only referenced as `mockery` substitutes in test files, I will de-prioritize them for now. In some cases, they may be the only way to test until more formal React-friendly testing is implemented.

That leaves five (5) components for vetting, three "utility" components (1–3) and two "widget" components:

1. **component-click-outside** has a React-friendly alternative in the codebase already. Need to compare the implementations. 

	**Estimated LOE: _low_**

1. **component-classes** A pseudo-polyfill for the `classList` JavaScript DOM API that [may no longer be needed](http://caniuse.com/#feat=classlist). Browsers in question are Opera Mini (supported by wp-calypso?) and IE 11 (due to partial support). 

	*IE 11's partial support includes:*
	
	1. Does not have support for classList on SVG or MathML elements.
	1. Does not support the second parameter for the toggle method.
	1. Does not support multiple parameters for the add() & remove() methods
	
	If Opera Mini is not a concern and current usage falls within IE 11's partial capabilities, a replacement component may not be necessary, native JavaScript will suffice.

	In some cases, **component-classes** is being used to reach above the React application root element to get/set properties/classes on the `<html>` element (`document.documentElement`) and/or `<body>` element `document.body`. It is possible in those cases that there exists a more React-friendly approach. *More research necessary.*
	
	**Estimated LOE: _medium_**
	
1. **component-closest** does not seem like a React-friendly approach. In theory, it allows you to look above the current component. It is perhaps worth a look at inverting the behavior using `Node.contains`. It is being used in some places for *click-outside*-like behavior, so maybe investigate replacing with that specific functionality. In others, it is being used to hack a 3rd-party, non-React component, so it may need to remain there. In at least one case, `ReaderSidebarTags`, it may be unnecessarily used for event delegation. Due to the variety of uses, there may not be a _one-size-fits-all_ replacement.

	**Estimated LOE: _high_**

1. **component-file-picker** This component is a dependent of only one other module, `FilePicker`, which acts as a wrapper. Since the `FilePicker` module is already React-friendly, I would recommend writing the **component-file-picker** functionality into the `FilePicker` component.

	**Estimated LOE: _medium_**

1. **component-tip** This component is only depended upon by one other tangible UI component, `Popover`, however that component is used extensively. Testing will likely be time-consuming. Since this is the only "widget" component which I would recommend replacing, a comprehensive UI library is not immediately needed, though could still be considered. It is not a complicated component and could be rewritten   relatively quickly if a replacement with a suitable API is unavailable.

	**Estimated LOE: _high_**

*LOE estimations do not currently include testing. I will need to check the scope of usage of consumer modules to calculate testing LOE.*

**Comment by nb** [comment]
Thanks for the solid and detailed research, @furf. I agree that we may leave the tests for now.

What are next steps? Do you think you should do more research or try to replace one of them? Is the level of effort proportional to the gain we will get from replacing a library?

P.S. I had to google that LOE means “level of effort” 📖

**Comment by furf** [comment]
LOL (laughing out loud)

**Comment by furf** [comment]
It's difficult to gauge the value of replacing something with its equivalent. I would say that in the cases of **component-classes**, at least you have the opportunity to _remove_ code—which is almost always a good thing. One way to gauge the value would be to weigh the downstream consumption, but that metric is in direct proportion to risk. I will take a deeper look at **component-classes**, then move on to **click-outside** and aim to finish my trial with some flourish with **component-file-picker**. I think the downstream reach of **component-tip** (via **popover**) may require too much testing and research to be suitable for a trial period.

**Comment by furf** [comment]
At this point, I think it makes sense to open issues for each of the **component-*** modules. Issues for **click-outside** (#5181) and **component-tip** (#4072) exist. I think this issue can be closed for now, but should be referenced in issues for individual modules (if it is deemed to provide value).

**Comment by Saravanan90** [comment]
@nb @seear @lancewillett Can this issue be taken up?

**Comment by ockham** [comment]
cc/ @Automattic/team-calypso in case you can maybe give this a stab :smile:

**Comment by noahtallen** [comment]
This popped up in my GitHub notifications today, and did a quick search in our codebase. These are the components listed in the issue which we still use in `wp-calypso`:

- `component-closest` (used in 5 react components)
- `component-file-picker` (used in 1 react component)
- `component-event` (mocked in 1 test)
- `component-query` (mocked in 1 test)

I'm unsure how much impact any of these have on the original issue goal, which was to migrate to more SSR-friendly components. I'm inclined to close this issue since the impact seems low, and since it's not very related to our current projects.
