### ISSUE TITLE
Calendly Block: Popup not working as expected when placed inside of a column block

### ISSUE THREAD

**Issue by nicholasjeberlin** [Automattic/wp-calypso#52687]
### Steps to reproduce the behavior

1. Create a page
2. Add a column block
3. Add the Calendly block within the column block
4. Embed an appropriate Calendly URL
5. Set Calendly block setting 'Styles' to 'Link'
6. Publish and view the page, click on the Calendly button

#### What I expected to happen

I expect a Calendly iframe to open up.

#### What actually happened

An iframe opens up with the address of the page you are currently on.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://d.pr/v/N0USWq

**Comment by kriskarkoski** [comment]
I have reproduced this and will leave the page up if it's needed for testing: P2UvKS-bS9Yl-p2

**Comment by sbathompson-he** [comment]
Occurred here as well: HC-29533185

**Comment by xpurichan** [comment]
Reported in 4002697-hc.

**Comment by janmckell** [comment]
Occurred here as well: 
34816734-HC
4889677-ZD
