### ISSUE TITLE
Nav Unification: Overflow issue on WooCommerce setup pages

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#52696]
On the WooCommerce setup page there is an overflow issue on the right side:

![https://d.pr/i/vHHYDP](https://d.pr/i/vHHYDP+)

This results in the help modal being offset to the right, and there is no way to close the button that is on top of the modal, so the modal can’t be closed.

![https://d.pr/i/URplcg](https://d.pr/i/URplcg+)

### Steps to reproduce the behavior

1. Install Woo on a Business plan site 
2. Go to store homepage 
3. Look at the right overflow 

#### What I expected to happen

Should be able to access the right icons, like when you have the left menu collapsed:

![https://d.pr/i/WSyAEc](https://d.pr/i/WSyAEc+)

#### What actually happened

They are cut off:

![https://d.pr/i/hBcrCT](https://d.pr/i/hBcrCT+)

### Context

Reported: 29488345-hc

#### Browser / OS version

Firefox 8.0.1 
Mac 10.15.5 (19F101)

#### Is this specific to the applied theme? Which one?

Probably not theme related. Tested Blank Canvas & Storefront.

#### Does this happen on simple or atomic sites or both?

AT

#### Is there any console output or error text?

Probably a width issue / CSS, etc.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

At least one issue is that you can’t setup payments, since the modal can’t be closed. A temporary solution is to collapse the left sidebar, you can then close the modal.

**Comment by cpapazoglou** [comment]
Can we use `position: sticky` instead of `fixed`?

![](https://cln.sh/Y4N86B+)

**Comment by sixhours** [comment]
It looks like this may have been fixed; I'm unable to reproduce the overflow in Chrome or Firefox:

<img width="1679" alt="Screen Shot 2021-08-16 at 2 30 42 PM" src="https://user-images.githubusercontent.com/2124984/129612563-d585bf38-11f5-4484-8d2d-96d011de42e6.png">
<img width="1680" alt="Screen Shot 2021-08-16 at 2 30 59 PM" src="https://user-images.githubusercontent.com/2124984/129612567-d75b0a04-534a-4352-95da-d84fc53df64a.png">

@mikeicode can you confirm this is still an issue?

**Comment by mikeicode** [comment]
@sixhours 

Appears to have been resolved with this:

```
/* Fix header overflow https://github.com/woocommerce/woocommerce-admin/issues/7035 */
@media (min-width: 961px) {
	.jetpack-connected .woocommerce-layout__header {
		width: calc( 100% - 272px );
	}
}

```

For this similar issue:

https://github.com/woocommerce/woocommerce-admin/issues/7035

I'll close this, thanks! :)
