### ISSUE TITLE
Onboarding checklist on atomic sites: Launch your site

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#52707]
### Task Details
On atomic sites, the _Launch your site_ task shows as completed even before the site is launched

### More info
It appears that the blog option `onboarding_checklist_task_site_launched` is being prematurely set to `1` (`wp-content/lib/onboarding-checklist/blog-tasks.php#76`)
We'll have to investigate why that is happening.

The launch button is currently not enabled in the editor for Atomic sites #50394, this may be related.

### Testing instructions

in the wpcom codebase, in `wp-content/lib/onboarding-checklist/functions.php`, modify the `is_blog_eligible_for_dotcom_checklist` to return `true`;

Create an atomic site
Do not launch the site
Go to the My Home page.
Notice that the _Launch your site_ task is set to _completed_ prematurely

Part of #50523

**Comment by deBhal** [comment]
A couple of interesting results from initial investigations:

1) `get_blog_option( $blog_id, 'launch-status' );` for [my test site](julesaustestatomic.wordpress.com) gets two different results: When run against our live databases, we get a `launched`, but if we use the atomic cli tool to check on that site, it believes itself to be `unlaunched`. This might be normal, or it might indicate a syncing problem (although I can't see any sync errors).

2. I created a new test atomic site for this issue, and so far it's happily unlaunched (from both perspectives). I'm going to leave it alone overnight to make really sure there isn't some async process before I start poking around to see if something changes it's status.

**Comment by deBhal** [comment]
The new test site is still unlaunched overnight, so we can rule out automatic processes for now and focus on actions that trigger the change.

**Comment by deBhal** [comment]
This seems to be fine now. I've created a new site and forced on the checklist and the launch option was unchecked:

![My_Home_‹_Julesaustestatomicunlaunched_—_WordPress_com](https://user-images.githubusercontent.com/5952255/118202712-d4eb7d00-b49d-11eb-98e7-3d225c1498fc.jpg)

I went through the rest of the checklist steps to make sure there wasn't a hidden trigger, but I think this was just a consequence of the launch button being disabled (#50394). Now that the launch button is available again, the checklist item is also working as expected.

However, it looks like launching the site is an unconditional part of the site migration process, so I'll double-check that I didn't skip that step.

**Comment by deBhal** [comment]
So we do launch blogs that we migrate using the `migrate-from` API call, but that doesn't seem to be part of the automated transfer process. There's a comment in the code there that that launch is because it's needed for the atomic upgrade, so I also messaged the team that's maintaining it to let them know that it may no longer be necessary.

I don't think the migration is a problem for our purposes, though, so I'm going to close this issue.

**Comment by deBhal** [comment]
I suspect this was fixed by 617-gh-Automattic/wpcomsh

**Comment by roo2** [comment]
just got around to retesting this and can confirm that I'm seeing this checklist item behave as expected 👍
