### ISSUE TITLE
Plans: can we show all wpcom plugins on one page?

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5270]
Been meaning to give this feedback for a while, but can we just show all standard plugins on the main plugins page, rather than hiding some of them behind a "view all standard plugins" link? IMHO this page isn't really about converting people to plans, but is more-so about explaining what people are getting with WordPress.com and helping to explain our approach to plugins in general. So I think it's ok (preferred, even) if this is a long page showing lots of plugins, even if that pushes the "purchase" buttons for plans below the fold.

cc @roundhill @drw158

**Comment by drw158** [comment]
Yes, the worry is that we wouldn't sell as much, and users might miss the big features at the bottom. The less important plugins like Markdown might hinder users seeing the more important paid ones at the bottom. In any case we should wait for the test results.

**Comment by drw158** [comment]
On the other hand, Custom Design is the most clicked paid plugin on the page, but it pales in comparison to the clicks on the free plugins.

As a compromise, we could add one more row (3 total) to the standard plugins section.

**Comment by rralian** [comment]
I wasn't really thinking of this page as a strong push for upgrade conversion. I thought the original idea behind this page was to address user concerns about "cannot install plugins", and help to explain our (somewhat confusing) approach to plugins in general as a way to improve churn/refunds. In which case I would think it's better to show a lot of them and make it easy to scan and see what you're looking for. In fact, one concern I have with this page is that by splitting the plugins between plan groupings so prominently, it sorta gives the impression (to me at least) that these plugins are the only difference between the plans, which I think could actually harm us a bit.

**Comment by drw158** [comment]
Hm yea, not grouping them at all would be a bigger design change. Could be interesting.

The original intent was to show what plugins are available to the user, whether that be free or paid plugins. It should be clear which ones are paid, and it should be easy to upgrade.

We could accomplish this goal with ungrouped plugins, but the tradeoff is that it's not clear that you get a set of plugins with a plan, or which plugins are included in which plan.

I think it could be an easier design challenge if we had a page for each plugin.

Overall it could be done, of course, but I don't know how I would handle the purchasing aspect. Adding a purchase button on each of the paid plugins is not ideal.

**Comment by drw158** [comment]
duplicate and irrelevant because of #5799
