### ISSUE TITLE
Sidebar: Jetpack submenu stays open on site switch.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52727]
Reported by @4thhubbard:

When switching sites in Calypso, the Jetpack submenu gan get stuck in the open position. See video at 552-gh-Automattic/dotcom-manage

**Comment by kwight** [comment]
@Automattic/ajax I'm not sure if this is nav unification related?

**Comment by cpapazoglou** [comment]
> @Automattic/ajax I'm not sure if this is nav unification related?

Hmm, that's interesting! 

Steps to Repro:
- Select a Jetpack site and expand "Upgrades" & "Jetpack".
- Now select a WPCOM site.
- Both "Upgrades" & "Jetpack" will appear as expanded and only one (the last) as selected.

So this selector
https://github.com/Automattic/wp-calypso/blob/78054ec40e0fa0a5583c5e91c5b5103b7bf7ace8/client/my-sites/sidebar-unified/menu.jsx#L51

returns `true` correctly for both of these menus. It would probably be better to filter the children for the one and only selected menu.

**Comment by cpapazoglou** [comment]
@kwight, I have drafted a PR to remedy this.
