### ISSUE TITLE
AMP: When disabled, redirect /amp/ URLs to original post

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#52726]
On sites with AMP disabled, amp urls don't redirect to the original posts, resulting in 404 errors.

### Steps to reproduce the behavior

1. Go to https://wordpress.com/settings/performance and select a simple site that is not private.
2. Make sure the AMP toggle is off (See https://wordpress.com/support/amp-accelerated-mobile-pages/#turn-amp-on-or-off).
3. Attempt to load a post on that site with `/amp/` appended to the URL
4. See 404 error

#### What I expected to happen

To see the linked post.

See p1606668916029200/1606593905.020300-slack-C02AVAR9B

**Comment by wojtekn** [comment]
We removed AMP support for Simple sites on July 11th, 2022 so this issue is not actual anymore. pdKhl6-lx-p2#comment-368

All `/amp/` URLs are now redirecting to the original post.
