### ISSUE TITLE
Cannot launch site from My Home "Launch Site" button

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#52737]
### Steps to reproduce the behavior

* Go to list of your sites in "My Sites" and click ADD NEW SITE
* Create new site
* Go to My Home
* Click on Launch y our site in the site setup checklist
* Click on "Launch site" button
* Get the "Horray" page and nothing else happens

#### What I expected to happen
My site would be generated

#### What actually happened
Site was never created. Stuck on this screen:

![image](https://user-images.githubusercontent.com/5665959/117760912-ce74bf80-b269-11eb-907c-18e133ad3bf1.png)

### Context
Trying to test this fix https://github.com/Automattic/wp-calypso/pull/52702

#### Does this happen on simple or atomic sites or both?
Simple
Didn't test on atomic because the Site setup list isn't shown on atomic https://github.com/Automattic/wp-calypso/issues/50523

#### Is there any console output or error text?

![image](https://user-images.githubusercontent.com/5665959/117760888-c452c100-b269-11eb-94b2-ca5e91b38ae0.png)

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consitent. Tested on staging and calypso live link

**Comment by deBhal** [comment]
I had no problems launching both simple and atomic sites using the launch button.

I was creating free sites without a domain, so I wonder if it was some specific product?

@autumnfjeld - did you add a plan/domain/other product to see this error? Are you still seeing it?

**Comment by deBhal** [comment]
@autumnfjeld isn't seeing it either, so I'll assume it's already been fixed and close this for now and we'll re-open and search harder if we see it again.

**Comment by autumnfjeld** [comment]
I retested this a few times with a free subdomain account and paid domain premium plan and it all looks good now.  Thanks for following up here!

**Comment by simison** [comment]
Cc @razvanpapadopol @alshakero @StefanNieuwenhuis in case error says anything.
