### ISSUE TITLE
Site Editor: crash after onboarding is complete

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#52732]
If you create a new design through [Horizon flow](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor) the Site Editor will crash when trying to load. Currently this is **not** happening only for TT1 blocks theme/layout, and all of the other layouts seem to be affected:

- Seedlet
- Vesta
- Easly
- Mayland
- Blank Canvas Blocks (not yet merged, but reproducible while testing the PR to add it)

<img width="461" alt="Screen Shot 2021-05-11 at 1 24 31 AM" src="https://user-images.githubusercontent.com/1182160/117736360-acdaf000-b1f7-11eb-9e16-f1423b718bf2.png">

cc @Automattic/theam in case themes need to be updated
cc @ianstewart

**Comment by david-szabo97** [comment]
Related issue: 31560-gh-WordPress/Gutenberg

The issue is already closed, fixed by two PRs. Once we have a fresh version of Gutenberg out on WPcom then this crash will go away.

**Comment by vindl** [comment]
This has been fixed with Gutenberg v10.6 update in D61304-code.
