### ISSUE TITLE
Investigation: obtain authenticated session on a mapped domain

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#52741]
Using a chrome incognito window (no cookies pre-set, and 3rd party cookies disabled), signing into WordPress.com will only sign you into the WordPress.com domain (and subdomains, public-api etc).

This works relatively the same way with 3rd party cookies enabled, the difference is, when you then visit a mapped domain it won't be able to access your WordPress.com cookies from that third party context and automatically treat you as logged in (to e.g. the nav bar)

This is the main problem we need to solve, the specific goal is to obtain an authenticated session on a mapped domain. Once we have that we can proxy anything else we need through the backend.

The solution is a bit undefined at this point. I'm laying out some options here but I think we need to spike a few things to figure out what will work best.

1. [Logmein](https://github.com/Automattic/wp-calypso/issues/52740) during signup (or login). 

During signup, if a domain is purchased, we should find a way to send the user through logmein on the mapped domain and back to calypso. 

This preemptively signs you in for your next visit. The downside is that cookies can expire and get out of sync so we still need a fallback method to get people logged in either before we send them to a mapped domain or once they get there.

2. Intercept clicks on outgoing links pointing at mapped domains 

Links going to a users mapped domain should append ?logmein to ensure the user lands on the mapped domain with a logged in state.

Ideally we only attach this when we know the user is logged out on the mapped domain. This is likely only possible if we can map the current session with a session on the mapped domain.

Advice: Start by getting links working all the time then restrict if possible. It might not be needed if the login flow is fast / reliable enough.

3. Test http referers and automatically send the users through ?logmein redirects if the user is coming from WordPress.com

I think I like this the most as it should be the cleanest fix with the widest impact (fixes most things) but I haven't fully thought this through and I might be missing something glaring.

**Comment by aneeshd16** [comment]
Thanks for putting this up @lsl!

> During signup, if a domain is purchased, we should find a way to send the user through logmein on the mapped domain and back to calypso.

If a domain is purchased during signup, the domain is activated only after the email address is verified. Effectively, the user exits the signup flow and then sees a prompt to verify the email address in "My Home". After the domain is purchased, it will still require some time for DNS changes to propagate. So maybe we can completely remove the signup flow from the overall scope?

> Test http referers and automatically send the users through ?logmein redirects if the user is coming from WordPress.com

I like this idea, but there may be instances where we link to a post/page on a mapped domain website from a logged out context, like marketing pages ([example](https://wordpress.com/discover-wordpress/)). This would have the unintended effect of redirecting a site "visitor" to the login page. [ITP 2.3](https://webkit.org/blog/9521/intelligent-tracking-prevention-2-3/) downgrades the referrer to eTLD+1 (`wordpress.com`), so we won't be able to differentiate between a logged-in and logged-out referrer.

**Comment by lsl** [comment]
> So maybe we can completely remove the signup flow from the overall scope?

Great point!

> This would have the unintended effect of redirecting a site "visitor" to the login page

Ah yes, this is a bit of a show stopper. Thanks for thinking this through.

I wonder if it's worth investigating anyway but just for things we know the user must be logged in to view - e.g. wp-admin/editor/customizer etc?

It's possible we should just always push these routes though logmein on mapped domains if the user is missing a first party auth cookie.

i.e, replace the normal login check with logmein redirects (for secured locations on mapped domains).

**Comment by lsl** [comment]
This morphed into #52939 and is mostly closed by #53443.
