### ISSUE TITLE
Onboarding: add support for FSE site creation

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#52744]
**Task Details**
When creating a site on `/start/with-design-picker` with an FSE design selected (check `design.is_fse` property to be `true`), the site should be FSE enabled and the selected design should be correctly applied.

A similar change to support FSE was done for `/new` in https://github.com/Automattic/wp-calypso/pull/43349
* passing `options.enable_fse` when calling the API to create a site
* using `seedlet-blocks` as default theme

**Comment by simison** [comment]
@Copons  @vindl This might be good for your team to pick?

**Comment by vindl** [comment]
> @Copons @vindl This might be good for your team to pick?

Yep, I'll pull it to our backlog.

**Comment by mattwiebe** [comment]
This was fixed with #56514
