### ISSUE TITLE
Canard: overlapping menu

### ISSUE THREAD

**Issue by kcswong** [Automattic/wp-calypso#52758]
User reported menu was overlapping content on their site in 6600877-hc, and I can see it happening in the theme demo as well [here](https://canarddemo.wordpress.com/):

![overlapping menu](https://d.pr/i/voVRLV+)

Here's how it should look: 

![correct menu position](https://d.pr/i/RkOPOR+)

Seems to only be happening on the homepage.

Follow up email in 3982177-zen

**Comment by aamills** [comment]
Additional report here - 20288529-hc

**Comment by tarunvijwani** [comment]
Another report: 29371746-HC

Sharing the below CSS code as a workaround:


.blog .featured-content .hentry:first-child {
    margin-top: 60px;
}

**Comment by JoshuaGoode** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/52758
