### ISSUE TITLE
Editor: uncheck uncategorized when another category is selected

### ISSUE THREAD

**Issue by ericandrewlewis** [Automattic/wp-calypso#5275]
#### Steps to reproduce

Open the post editor for a new post. In the categories menu, the uncategorized category is selected as the default. Clicking another category selects both the new category and uncategorized.

#### What I expected

Uncheck the uncategorized category when I select a new category

**Comment by lancewillett** [comment]
I'm pretty sure this has been reported before... but not seeing the other issue right now (might be closed)?

**Comment by jeremeylduvall** [comment]
@lancewillett pretty sure you're referring to #561 which is still open and has some additional discussion. I'm going to close this one in favor of the previous discussion.@ericandrewlewis—appreciate the report!
