### ISSUE TITLE
Change Secondary CTA for support search on My Home to 'Contact Support'

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#52762]
At the moment the CTA button for the secondary action on the help/support section of My Home is 'More Help' and links to /help.

We could provide a more immediate pathway to assistance (especially given users can *already* search our help docs from My Home) by instead changing the CTA to be 'Contact Support' and linking to /help/contact.

<img width="203" alt="Screen Shot 2021-05-12 at 6 18 55 am" src="https://user-images.githubusercontent.com/1842363/117879421-526e8c00-b2ea-11eb-9746-a351cabcfbbf.png">

**Comment by jeffgolenski** [comment]
@jordesign Love it. I've got a few design enhancements I'm thinking on for this area as well. I'll save those for another issue!

**Comment by Aurorum** [comment]
PR for this issue in #52831. :)
