### ISSUE TITLE
My Home: Idea, replace stats card with "changes since last visit" card

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#52767]
### Overview
This is part of [My Home Pod short-term design improvements](pd2qGl-2P-p2#short-term-goals)

My Home Stats Card: Post-launch traffic: Display changes since last visit or over a time period (views, comments, etc)

### User facing acceptance criteria
Given that the user has launched their site 
When they go to My Home
Then they see a stats card that
------ to do -------

### Figma Designs
N/A for this ticket

### Related links
[My Home Project thread]( pd2qGl-17-p2)
[My Home: Short-term design improvements](pd2qGl-4i-p2)

### Notes / Background

This is the stats card on the My Home page
<img width="632" alt="Screenshot 2021-05-12 at 11 47 32 AM" src="https://user-images.githubusercontent.com/1500769/117898073-3681df00-b318-11eb-935e-0f33e8878fb8.png">

It's really a duplicate of the information that's already available in the stats screen, which users can navigate to in the sidebar.
![Untitled](https://user-images.githubusercontent.com/1500769/117898080-3a156600-b318-11eb-928a-dcb7ed019425.jpg)

Is there a way of highlighting stats in a way that is unique for My Home? Perhaps it could focus more on what's changed since your last visit. Ideas:
- You've received your first visitor
- You've reached a new visitor milestone (e.g. 100 visitors in one day)
- Your post with the most interactions

"Changes since last visit" doesn't have to be limited to stats:
- You've received 4 new comments, click here to moderate them
- You have 2 new emails (e.g. if they have Titan mail)

Idea pulled from p1620626375227200-slack-C01VA0R5NKY @michaelpick

**Comment by jordesign** [comment]
It also strikes me that it's likely a user will be *more* interested in the stats for recently posted content? 

If I added a post yesterday - The stats for that post are top of mind for me...

**Comment by autumnfjeld** [comment]
Improvements to the post launch stats card happening in [My Home Pod medium term design explorations](pd2qGl-9y-p2)

Design in progress, not final:
![image](https://user-images.githubusercontent.com/5665959/124188402-915ada00-db02-11eb-8e2c-8edc1a78eed3.png)

**Comment by jordesign** [comment]
Closing this - as Stats in my Home are being considered as part of the redesign
pbAok1-2L4-p2
