### ISSUE TITLE
My Home: Don't show stats card on un-launched sites

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#52764]
### Describe the problem
For un-launched sites, the stats card on the My Home page always shows a placeholder message. The site has no traffic by definition, so the card will never show anything useful.
![Screen Shot on 2021-05-12 at 09:47:00](https://user-images.githubusercontent.com/1500769/117889046-041bb600-b307-11eb-8140-171b52d0b415.png)

At the very least this is taking up space we could use for something else (e.g. the free photo library card could move up if the stats card wasn't there). At worst it could be discouraging to the user to have no traffic yet.

### Additional Details
A counter argument to keep in mind: we should be mindful of persistence and consistency. Will doing this make My Home feel less stable? You could also argue that the empty card at least advertises that we have a stats feature (although the sidebar item does that to).

Idea came from this conversation p1620626375227200-slack-C01VA0R5N @michaelpick

**Comment by autumnfjeld** [comment]
Just an FYI: this is part of My Home Pod short-term goals pd2qGl-2P-p2

**Comment by autumnfjeld** [comment]
As we chatted about if the logic gets too messy for this likely interim fix, then let's reconsider this work.  Hopefully this stats "Getting Started" video will be available to use in this card. https://github.com/Automattic/wp-calypso/issues/52906

**Comment by p-jackson** [comment]
Deployed in D61566-code
