### ISSUE TITLE
Login to private .blog subdomains briefly flashes the "Coming soon" page

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#52773]
This behaviour is seen with 3rd party cookies enabled.

### Steps to reproduce the behavior

1. Open Chrome incognito window and disable the option to block third party cookies

<img width="653" alt="Screenshot 2021-05-12 at 11 33 32 AM" src="https://user-images.githubusercontent.com/1269602/117944378-d0eb1e00-b32a-11eb-9bc2-4ef2946085fb.png">

2. Visit a .blog subdomain private site such as example.food.blog  - confirm that you can see the "Coming soon" landing page

<img width="1434" alt="Screenshot 2021-05-12 at 12 35 02 PM" src="https://user-images.githubusercontent.com/1269602/117944607-114a9c00-b32b-11eb-89c6-833bd36115a5.png">

3. Click on the login button and enter the credentials for that site.

#### What I expected to happen

After login success, I expected to be taken to the site

#### What actually happened

I am taken back to the "Coming soon" again for a couple of seconds or so, and then taken to the blog. This is a slightly confusing UX to see the "Coming soon" page with the login button once again after a successful login.

In the gif below, I'm in the 2FA authentication page after login, and then taken to the "Coming Soon" page briefly before being taken to the site.

![mdlin](https://user-images.githubusercontent.com/1269602/117946616-16a8e600-b32d-11eb-92d4-8e4c914b808d.gif)

### Context

This is likely related to the changes described in p58i-aqo-p2 that implemented a method to log in to private mapped domains.

**Comment by aneeshd16** [comment]
Hi, I tried to reproduce this, but could not. It might have been fixed via D61364-code

https://user-images.githubusercontent.com/5436027/124907078-604c3f00-e005-11eb-9669-ef0f2635225e.mp4

**Comment by niranjan-uma-shankar** [comment]
Confirmed that I don't see this issue any longer. Closing.
