### ISSUE TITLE
Settings : Privacy setting to hide site from search engines doesn't work

### ISSUE THREAD

**Issue by kavyagokul** [Automattic/wp-calypso#52783]
### Steps to reproduce the behavior

1. Go to **My SIte > Settings > General** for an Atomic site
2. Turn on the option "Discourage search engines from indexing this site"
3. Check robots.txt 

#### What I expected to happen

Something like this
```
User-agent: *
Disallow: /
```

#### What actually happened

This 
```
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
```

#### Browser / OS version
Firefox developer edition on Linux
Chromium on Linux

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Atomic

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects more than one site

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

**Comment by kavyagokul** [comment]
This was reported in 29543871-hc

**Comment by kosiew** [comment]
Could not replicate on my AT site - https://wp20180808.com/robots.txt

![Screenshot](https://d.pr/i/QRgNMI+)
*if image does not load, please click on this link  : https://d.pr/i/QRgNMI*
