### ISSUE TITLE
Nav Unification: "Feedback" page missing 

### ISSUE THREAD

**Issue by darcie** [Automattic/wp-calypso#52797]
### Steps to reproduce the behavior

1. Go to the dashboard
2. Click on My Site
3. Feedback is not listed in options 

#### What I expected to happen
Feedback as a menu in Nav Uni to see form submissions

#### What actually happened
Feedback is missing except when using wp-admin 

### Context
User came in to chat looking for Feedback. Initially thought it was hidden from view, then realized it was missing in my sites as well. Additional reports since. 

#### Browser / OS version
Not related to browser

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Simple sites only 

#### Is there any console output or error text?
None seen 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

User report 23519061-hc, 23519061-hc

**Comment by zdenys** [comment]
It was fixed in r225586-wpcom. Closing.
