### ISSUE TITLE
Editor: an 'updated' notice appears before 'published' notice if publish before save

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5281]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Create a new post - as you type content immediately click "Publish"
#### What I expected

`Post published on <blogname>!`
#### What happened instead

First I see:
`Post updated on <blogname>!`
Then
`Post published on <blogname>!`

This causes 'publish anxiety' as it led me to believe that I had already published it before I made the changes - which means the prior content would be sent to email subscribers/publicise connections etc.
#### Browser / OS version

Chrome latest/Firefox latest/OSX
#### Screenshot / Video

![updated before publish](https://cloud.githubusercontent.com/assets/128826/15106404/7970fbba-160c-11e6-96fa-6923bb951470.gif)
ug

**Comment by designsimply** [comment]
#bug-scrub

Tested and confirmed using the steps provided.

Video: [30s](https://cloudup.com/cmYjUqtgTxl)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10264 using Safari 9.1.2 on Mac OS X 10.11.6</sup>

**Comment by hoverduck** [comment]
#bug-scrub

Tested and confirmed using the steps provided.

**Comment by rachelmcr** [comment]
#bug-scrub

Tested and confirmed the issue still exists using the steps provided.

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue. After I publish the post I only see the publish confirmation, without an update confirmation. Closing as resolved.
