### ISSUE TITLE
Calypso Colour Schemes: There is no "default" option.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52837]
1. Create a new site.
2. Go to the colour scheme page.
3. There is no "default" option.
4. Change to one of the listed schemes, there's no way to go back to default, unless default is "dark classic", if so it isn't selected.

![image](https://user-images.githubusercontent.com/545779/118176129-9e0e5c00-b3f6-11eb-9c7c-bf0cee999a85.png)

Hat tip @olaolusoga for the issue.

Recommendation:

1. Lets pick the one looks most like wp-admin.
2. Add it to the first spot in the list.
3. Rename it Default or highlight it in that fashion somehow.

**Comment by ianstewart** [comment]
Quick mockup of the recommendation:

![image](https://user-images.githubusercontent.com/545779/120853324-0efdeb00-c541-11eb-9686-151987f33060.png)

- Moved Classic Dark to the front of the list.
- Renamed to Default.

**Comment by ianstewart** [comment]
Looks like these last two images are off-grid.

![image](https://user-images.githubusercontent.com/545779/120853554-787df980-c541-11eb-9810-7e79858482c2.png)

If it's a simple fix we should fix it in the same PR, or if it's non-simple, or we want a cleaner PR, we can fix it later in another Issue+PR.

**Comment by andres-blanco** [comment]
> Looks like these last two images are off-grid.
> 
> ![image](https://user-images.githubusercontent.com/545779/120853554-787df980-c541-11eb-9810-7e79858482c2.png)
> 
> If it's a simple fix we should fix it in the same PR, or if it's non-simple, or we want a cleaner PR, we can fix it later in another Issue+PR.

It seems like replacing the current css rules for `.form-radios-bar .form-radio-with-thumbnail` by
```css
width: 141px;
margin-bottom: 10px;
```

So I will include it in this PR

**Comment by andres-blanco** [comment]
@ianstewart I submitted a PR. There's a small detail: [the dark color scheme is only default if nav-unification is enabled](https://github.com/Automattic/wp-calypso/blob/trunk/client/me/account/main.jsx#L1093). I don't know if this is something that changes the plans for this issue or not.

**Comment by ianstewart** [comment]
Are there sites that don't or won't have nav unification enabled?

**Comment by andres-blanco** [comment]
That's a good question that I don't know how to answer. @kwight do you have any insights on this?

**Comment by kwight** [comment]
> Are there sites that don't or won't have nav unification enabled?

I think anyone that wants to can turn it off in _Settings > Advanced General_.

**Comment by andres-blanco** [comment]
Ok, it doesn't seem to be normal to have nav-unification disabled.

I will move this to review.
