### ISSUE TITLE
Activating a theme from the demo site does not give option to keep/change Home Page Content

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#52844]
When viewing the Theme Demos I am shown an option to activate that theme for any of my sites. When I select a theme to do so - no modal to change/keep Home Page content is shown.

Example: Pb8PuN-9-p2

This is inconsistent with switching themes from the theme showcase, or viewing demo sites *within* modais in the showcase or setup pages.

<img width="1116" alt="Screen Shot 2021-05-14 at 6 27 07 am" src="https://user-images.githubusercontent.com/1842363/118183868-fb012500-b47d-11eb-9e45-9100f7b2e541.png">

**Comment by youbrokesomething** [comment]
I'm closing this issue as I'm not able to reproduce it at this time. I tested with several non-FSE themes and got the homepage content selector from live demo.
