### ISSUE TITLE
Query patterns exposed to regular sites

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#52859]
I noticed my regular simple site (`simisontestinfree.wordpress.com`) has Query pattern category, with all the broken Query block patterns:

<img width="2044" alt="Screenshot 2021-05-14 at 11 46 14" src="https://user-images.githubusercontent.com/87168/118245999-1c780600-b4aa-11eb-824f-be2e91369f88.png">

We shouldn't expose this before Query block lands in Gutenberg.

Plugin info for the site as of May 14, 2021:

Gutenberg: v10.5.4
CoBlocks: 2.10.1
Editing Toolkit: 3.6512
WP AMP: 2.0.5

**Comment by annezazu** [comment]
Closing this out :) The Query Loop block landed a long time ago and our patterns experience has evolved significantly since then.
