### ISSUE TITLE
Signup: Content improvements, contrast, remove username.

### ISSUE THREAD

**Issue by ollierozdarz** [Automattic/wp-calypso#52852]
Based on the current performance of the refined reskin onboarding flow, let's make the following changes to help increase the likelihood of reaching parity (and beyond) with control.

**Updates to content:**
- Remove the username field (this was approved by Dave Martin)
- Update the input label copy to read; "Your email address" and "Choose a password".
- Add "OR" between the two dividing columns
- Add the word "First" to the subtitle of the page. It should now read; "First, create your WordPress.com account. Have an account? Log in"

**Updates to styles:**
- Add a darker Grey to inputs, subtext, and social button borders ([Figma with instructions](https://www.figma.com/file/gnYBUOBthTMckJRJr3pZmk/Control-Experiments?node-id=2557%3A0))

**Notes:**
- We need to ensure there is a sensible default added for the user as their replacement username. There have been experiments on this before, so probably a good pattern to reuse?

**Designs for reference:**
<img width="1440" alt="Reskined Reskin" src="https://user-images.githubusercontent.com/67085494/118218866-aaa8b800-b4bb-11eb-9ea7-c0a316a6ec65.png">
<img width="375" alt="Reskined Reskin" src="https://user-images.githubusercontent.com/67085494/118218880-af6d6c00-b4bb-11eb-834f-91e8decbfa7b.png">

**Comment by razvanpapadopol** [comment]
> Remove the username field (this was approved by Dave Martin)

We are currently doing this in `/new` using just a `username_hint` which may be left `undefined` in this case. The backend service seems to create the username: https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/gutenboarding/components/signup-form/index.tsx#L80

<img width="969" alt="Screenshot 2021-05-14 at 14 29 42" src="https://user-images.githubusercontent.com/14192054/118264772-e2662e80-b4c0-11eb-99fc-b0c08b367256.png">

> We need to ensure there is a sensible default added for the user as their replacement username. 

An idea would be to take what's before `@` from the email address and try creating a username with that.

**Comment by ollierozdarz** [comment]
Great! Sounds like we've got a good option with the `/new` solution! 

> An idea would be to take what's before @ from the email address and try creating a username with that.

Yeah, I like this idea.

**Comment by razvanpapadopol** [comment]
Username input field has been removed in #53509
Style improvements have been applied in #53549. @ollierozdarz could you double check them using https://wordpress.com/start?flags=signup/reskin before closing this issue?
