### ISSUE TITLE
Visually broken help button at signup flow

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#52860]
1. Go to https://wordpress.com/start/onboarding
2. At resolutions around 600px and under, the help FAB breaks visually:
    <img width="80" alt="image" src="https://user-images.githubusercontent.com/87168/117783805-8f377600-b24b-11eb-84fb-4ed92737830d.png">

It doesn't happen in the rest of Calypso, only in signup.

**Comment by alshakero** [comment]
Fix is in https://github.com/Automattic/wp-calypso/pull/52864.
