### ISSUE TITLE
Cookie banner covers footer on wordpress.com logged-out marketing page

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#52868]
At wordpress.com logged-out marketing page, I see a cookie banner covering the footer sometimes, but not in every screen size. I know people can just dismiss, but some people don't care about these banners and might just not notice that e.g. language switch is behind it. 

Note also the un-proportionally big "got it" button, which feels unexpected.

![image](https://user-images.githubusercontent.com/87168/118267644-10e60880-b4c5-11eb-96d7-878618239d34.png)

![image](https://user-images.githubusercontent.com/87168/118267636-0e83ae80-b4c5-11eb-86f8-9441873f556e.png)

![image](https://user-images.githubusercontent.com/87168/118267649-12afcc00-b4c5-11eb-812f-49517c24125e.png)

**Comment by porada** [comment]
@simison — Any chance you remember the page you took these screenshots on? I’m trying to determine whether that’s an AMP or a non-AMP landing page.

**Comment by simison** [comment]
This was at https://wordpress.com/pricing/

Thanks for the patience with the reply. :-)

**Comment by porada** [comment]
Closing due to possible scope creep and conflicts with the existing cookie bar advancements in progress (`pau2Xa-2lc-p2`).

This version of the cookie bar appears only on AMP pages and there is very little we can do in this context without redesigning the whole bar.
