### ISSUE TITLE
Add Akismet Anti-Spam submenu in Jetpack menu for Simple Sites

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#52862]
In order to improve Simple/Atomic Feature, we should look into adding Akismet's Anti-Spam submenu in Jetpack menu for Simple Sites, [instead of removing it from Free Atomic plans](https://github.com/Automattic/wp-calypso/issues/51827) (since Akismet is available on all Simple Sites plans).

### What plan tier is the site on?
On all Simple site plans

### What I expected on the WordPress.com site
To have a `Akismet Anti-Spam` submenu in Jetpack menu and removing the custom configuration settings from Settings > Discussion: wp-admin/options-discussion.php
#### What I expected on the Atomic site
Nothing, the submenu is already present in there.

### Discussion:
pd2C0z-F-p2

**Comment by tjcafferkey** [comment]
Going to split this into two separate issues

* Make the settings accessible consistently across Simple / WoA / Jetpack by adding the "Akismet Anti-Spam" menu item to "Jetpack" menu item. Also remove the settings from "Settings > Discussion" so they're not duplicated.
* Align the actual settings so the screens are the same across Simple / WoA / Jetpack

@BogdanUngureanu can you update this issue with the relevant information to tackle the first of the two issues above. And then create a second issue for the follow up please?

**Comment by BogdanUngureanu** [comment]
As Tom mentioned, we'll be splitting this into two separate issues:
- Adding the submenu element in Jetpack menu for simple sites (requires the modification of WPCOM specific code).
- Align Akismet settings for SImple and WoA sites which can be achieved by reusing the logic from WPCOM on WoA, and possibly touching the Akismet plugin.

**Comment by mmtr** [comment]
Proposed fix ready for review in D64710-code.

**Comment by mmtr** [comment]
Fixed in r229383-wpcom and r229385-wpcom.
