### ISSUE TITLE
Gutenberg: copy-paste is creating only code blocks

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#52881]
<img width="794" alt="Screenshot 2021-05-14 at 19 12 13" src="https://user-images.githubusercontent.com/4389/118311820-4fd98580-b4e8-11eb-8cfb-02bb1ce04cd7.png">

### Steps to reproduce the behavior

1. Go to any site
2. Create or edit post
3. Copy any rich text (i.e. a HTML page)
4. Paste

#### What I expected to happen

Before it matched semantically everything from the source to be cleaned up and converted to proper blocks with formatting preserved.

#### What actually happened

A code block was created

#### Browser / OS version

Chrome 90.0.4430.93
MacOS 11.3 

#### Does this happen on simple or atomic sites or both?

I tried P2 and Simple.

#### Is there any console output or error text?

<img width="1187" alt="Screenshot 2021-05-14 at 19 10 30" src="https://user-images.githubusercontent.com/4389/118311642-143ebb80-b4e8-11eb-8cb1-0769906e6459.png">

#### Level of impact

High. Copy paste is a primary interaction with the editor.

**Comment by folletto** [comment]
Might be related to: #52882

**Comment by folletto** [comment]
Note: this seems a bug showing up only with Automattic Proxy on.
/ht Kris

**Comment by WunderBart** [comment]
Fixed via r225761-wpcom
