### ISSUE TITLE
Theme showcase: consider intent-based categories

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52885]
Our logged-out theme showcase surfaces some popular intent-based categories.

![image](https://user-images.githubusercontent.com/545779/118320405-d5960a80-b4c1-11eb-8c99-c52ff5de0746.png)

But we don't surface these for logged-in users.

![image](https://user-images.githubusercontent.com/545779/118320575-11c96b00-b4c2-11eb-831f-7ebdbcc02634.png)

Additionally the design picker we show in signup is likely to get intent-based categories. Could we align here and surface more browse-able categories everywhere?

**Comment by dsas** [comment]
This was fixed at some point in the last four years 👍
