### ISSUE TITLE
Gutenberg: can't convert paragraph block

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#52882]
<img width="646" alt="Screenshot 2021-05-14 at 19 03 50" src="https://user-images.githubusercontent.com/4389/118311960-8911f580-b4e8-11eb-90d8-d94c11a0eb4e.png">

### Steps to reproduce the behavior

1. Go to any site
2. Create or edit post
3. Click on a paragraph

#### What I expected to happen

I can convert paragraph do various different types of block.

#### What actually happened

I can only convert a paragraph to "Conversation".

#### Browser / OS version

Chrome 90.0.4430.93
MacOS 11.3

#### Does this happen on simple or atomic sites or both?

I tried P2 and Simple.

#### Is there any console output or error text?

<img width="1198" alt="Screenshot 2021-05-14 at 19 15 11" src="https://user-images.githubusercontent.com/4389/118312097-c1193880-b4e8-11eb-8ffa-330a0876af02.png">

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

High.

**Comment by kriskarkoski** [comment]
I noticed the same in the front-end p2 editor. I can create a different block type from the / command for example, but cannot convert an existing p to another block.

**Comment by folletto** [comment]
Note: this seems a bug showing up only with Automattic Proxy on.
/ht Kris

**Comment by WunderBart** [comment]
Fixed via r225761-wpcom
