### ISSUE TITLE
Domains: Ability to renew expired domain from domain page

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#52898]
Please, be as descriptive as possible. Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

**What**

Instead of having to visit the purchases page, ability to renew the expired domain from domain page (`Upgrades > Domains > Domain name`) would be great.

**Why**

Better experience for customers, especially those that have multiple sites and domains.

**How**

<img width="769" alt="Screenshot 2021-05-16 at 11 12 56 AM" src="https://user-images.githubusercontent.com/18581859/118387143-23ce1980-b63a-11eb-9b28-607d5b23a88d.png">

**Additional context**

Came up on a customer interaction. 3990233-zen

Related https://github.com/Automattic/wp-calypso/issues/52897

**Comment by kelliepeterson** [comment]
Actually this is already in place.
![Screen Shot 2021-06-17 at 2 49 02 PM](https://user-images.githubusercontent.com/3022756/122476496-2abeb380-cf7b-11eb-9152-b8c88f7a811a.png)

**Comment by arunsathiya** [comment]
@kelliepeterson I couldn't see that button for an expired domain, as the screenshot on my post indicates. Is it possible that the button is available only for those that are active? I don't have an expired domain to test with at the moment.

**Comment by kelliepeterson** [comment]
@arunsathiya your screenshot indicates that you are not the owner of that domain so you wouldn't be able to take a renewal action.
