### ISSUE TITLE
Domains: Mobile improvements

### ISSUE THREAD

**Issue by ollierozdarz** [Automattic/wp-calypso#52905]
Edit: Some of the changes will be added in #53768 (follow up of #53700)

Based on the current performance of the refined reskin onboarding flow, let's make the following changes to help increase the likelihood of reaching parity (and beyond) with control.

**Main improvement areas:**

- Change the order of the 'Already own a domain?' and 'Get a free plan' information to now be places at the bottom of the list of domains. This will suit the same hierarchy as the desktop version, and is Iess important than a user finding a domain quickly
- Change the layout of each domain offering to be more like control, where we have stacked information and a full width button for each
- Make the domain name font-size bigger (from a default 14px to 16px)
- Make the adequate style, margin, and padding adjustments outlined in the [Figma File](gnYBUOBthTMckJRJr3pZmk-fi-2557%3A0)
- Make the 'View more domains' link, a button.

![Refined Reskin](https://user-images.githubusercontent.com/67085494/118436173-ada5e180-b723-11eb-8717-1b2a8f3edcef.png)

**Comment by StefanNieuwenhuis** [comment]
![image (1)](https://user-images.githubusercontent.com/12104589/119006595-cf57d080-b990-11eb-878d-cb55454e45a2.png)

Currently, the marketing copy hides the search results below the fold.

@ollierozdarz, what do you think of moving the marketing copy below the search results? See p1620915194324400/1620913276.320500-slack-C01VA100LEA

**Comment by StefanNieuwenhuis** [comment]
@ollierozdarz , another one is that the marketing copy is spread over 2 columns. 
WDYT? Does its layout need to change as well? 

Another issue is that the off-margins around the search bar and is the search bar in the right place?

![image (2)](https://user-images.githubusercontent.com/12104589/119009849-d3392200-b993-11eb-8b79-7934ab403eb1.png)

**Comment by ollierozdarz** [comment]
Hey @StefanNieuwenhuis, 

> Currently, the marketing copy hides the search results below the fold.
@ollierozdarz, what do you think of moving the marketing copy below the search results? 

Yep, if you check out the latest mobile design in the description (and below), we'll put the marketing copy at the bottom underneath the results once they're populated:

![image](https://user-images.githubusercontent.com/67085494/119094613-9ed96a80-ba54-11eb-9231-9849cca580d6.png)

> Another one is that the marketing copy is spread over 2 columns.
WDYT? Does its layout need to change as well?

The implementation for tablet view should look similar to below, with the input staying in the same place.

> Another issue is that the off-margins around the search bar and is the search bar in the right place?

Yep, it looks off by a lot.

<img width="710" alt="Screen Shot 2021-05-21 at 4 52 45 pm" src="https://user-images.githubusercontent.com/67085494/119094983-0bed0000-ba55-11eb-96ce-3d4be7264af3.png">

The tablet view once the domains list is populated will need some more thought, but let's leave this until I'm back from AFK and I'll design a better solution from our latest learnings.

**Comment by razvanpapadopol** [comment]
Thanks for your input, @ollierozdarz 🙌🏼 

> we'll put the marketing copy at the bottom underneath the results once they're populated

@StefanNieuwenhuis, let's do the same also for tablet view (when we have marketing on 2 columns) and we can always improve later.

**Comment by razvanpapadopol** [comment]
https://github.com/Automattic/wp-calypso/pull/53700 was reverted in https://github.com/Automattic/wp-calypso/pull/53820 to fix the following regressions on Domains step:
- position of the "Get a free one-year domain..." banner
- spacing at the bottom, before "show more" button

**Expected**
<img width="809" alt="Screenshot 2021-06-18 at 19 02 48" src="https://user-images.githubusercontent.com/14192054/122588480-d3e2d800-d067-11eb-8505-a89b9097466b.png">

**UI regression**
<img width="812" alt="Screenshot 2021-06-18 at 17 12 36" src="https://user-images.githubusercontent.com/14192054/122588152-6afb6000-d067-11eb-82d0-7da705fb92db.png">
