### ISSUE TITLE
Show login button on public sites

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#52913]
When a logged out user visits a public site, we don't show a "Login" button but only a "Register" button. Existing users who want to login will have to navigate to the Signup page and then follow the Log In link from there. Can we show a Login button here next to the "Register" button? 

The login flow should work on mapped domain sites with 3rd party cookies disabled.

<img width="857" alt="Screenshot 2021-05-12 at 2 05 01 PM" src="https://user-images.githubusercontent.com/1269602/118476514-3c6a2c80-b72b-11eb-895d-86ef35c4ed2d.png">

**Comment by aneeshd16** [comment]
Looks like this bar is not shown on mapped domains or on paid sites (please see 294a9-pb). Wondering if this would be out of the pod scope?

**Comment by niranjan-uma-shankar** [comment]
> Looks like this bar is not shown on mapped domains or on paid sites (please see 294a9-pb). Wondering if this would be out of the pod scope?

Good point, makes sense why the marketing bar is not on paid sites. I still wonder if it would make sense to provide a login link but I think low on the priority list since we need to figure out a placement for the link. I'll move this back to the Triage column and we could revisit later.

**Comment by niranjan-uma-shankar** [comment]
Fixed by D63784-code and D61523-code.
