### ISSUE TITLE
"Upload Theme" tracks event not recorded/categorized separately for Atomic sites

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#52927]
When you click the "Upload Theme" button, multiple tracks event are created. We used to have a tracks event: [calypso_automated_transfer_click_theme_upload](https://github.com/Automattic/wp-calypso/blob/e797df8452361ce7ead6ae1cdfec37378da0309c/client/my-sites/themes/theme-showcase.jsx#L225) specifically for atomic sites. But the code which fires off that tracks event has been unreachable since 2017, due to [this commit](https://href.li/?https://github.com/Automattic/wp-calypso/commit/Cd08edbb750d30f4320cf4831b08207e5c8228ff#diff-5e6c175ac60d9ed48935454e0bcf1861c5d5893c33a08edb946162d2e0dea550L258), which deleted the definition of the "atEnabled" property.

If you view the trends in our tracks stats, we can see that the event has fired very rarely since 2017 May (Probably only firing for those who have a cached version of Calypso, prior to the above commit?): paYKcK-10A-p2#comment-1018

More information and suggestions in this p2 post: paYKcK-10A-p2

The unused code related to this tracks event will be removed for now in this pull request: https://github.com/Automattic/wp-calypso/pull/52671

### Steps to reproduce the behavior

1. For an atomic site, go to the /themes/SITE_SLUG page.
2. Click "Upload Theme"
3. Observe that "calypso_automated_transfer_click_theme_upload" tracks event is not fired.

### Proposal

Add a new property to the calypso_click_theme_upload event, indicating whether this is a simple site or atomic.

**Comment by kwight** [comment]
@DanielSmithMichigan Can we close this now then?

**Comment by DanielSmithMichigan** [comment]
@kwight No, it's not fixed. I referenced it from another pull request because that's when I discovered this was an issue and I cleaned up some of the related code, but I didn't fix it in that pull request.
