### ISSUE TITLE
Themes: Add Tracks events for the theme switch modal.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52926]
Let's add Tracks events to the theme switch modal, which doesn't appear to have any at the moment.

See: pd2qbF-33-p2

![image-7](https://user-images.githubusercontent.com/349751/118545733-d5894b00-b70b-11eb-9b52-2fa1ccf26567.png)

**Comment by ianstewart** [comment]
Will be adding tracks events for this other modal at the same time?

![image](https://user-images.githubusercontent.com/545779/118697782-46e10080-b7d5-11eb-8c2d-e633d925bc36.png)

**Comment by DanielSmithMichigan** [comment]
@sixhours Should this be closed out?

**Comment by sixhours** [comment]
Yep! :D
