### ISSUE TITLE
Themes: Install a theme sometimes gives an error message.

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#52931]
~~This might be a theme issue instead of an application issue. I noticed this DOES happen with the [AltoFocus theme](https://wordpress.com/theme/altofocus). It does NOT happen with the [Cavatina theme](https://wordpress.org/themes/cavatina/).~~

**(See comment below)**

### Steps to reproduce the behavior

1. Create new free blog via wordpress.com/new
2. Go to this page: https://wordpress.com/themes/test8811919.wordpress.com
3. Click "Install theme"
4. "Upgrade and continue"
5. "Pay $300 with credits"
6. "Continue installing theme"
7. "Install Theme"
8. "Continue"
9. Upload the theme from [this page](https://wordpress.com/theme/altofocus).
10. Once it's done, click "Activate"
11. Notice the [error message](https://user-images.githubusercontent.com/10274366/118561779-8a862c80-b739-11eb-9a12-5db87c7c2beb.png)

![118561779-8a862c80-b739-11eb-9a12-5db87c7c2beb](https://user-images.githubusercontent.com/349751/118721960-616ca700-b7e0-11eb-8a15-9d95924afeaa.png)

**Comment by DanielSmithMichigan** [comment]
After continuing to look into this, it seems a lot more random than suggested above. It happens some of the time, and it's not related to whether or not that specific theme is uploaded. It's also not related to how long you wait (didn't seem like a race condition to me)

**Comment by michaeldcain** [comment]
> Once it's done, click "Activate"

Just adding some context from our work on the theme upgrade flow last week (#53585)… @ianstewart noticed that when a [theme is uploaded and kicks-off the Atomic process](https://github.com/Automattic/wp-calypso/blob/3abdf13ff3fed326daed436d252027cfe5cdd05b/client/state/themes/actions/theme-transfer.js#L31), the endpoint seems to auto-activate that theme _before_ the "activate" option is shown. This can be seen by visiting the front-end of the site before clicking "activate". It's possible that the error is a result of the "activate" button attempting to enable an already-active theme - it [conditionally changes its action here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/themes/theme-upload/index.jsx#L277).

**Comment by andres-blanco** [comment]
Following the steps in the description I consistently get this error when clicking "activate":
![image](https://user-images.githubusercontent.com/375980/122605618-14355c80-d04e-11eb-8b36-c65d2d7aae07.png)

When I click refresh I end up in this page: https://[YOUR_SITE].wpcomstaging.com/wp-admin/theme-install.php?browse=featured

The uploaded theme is activate but this behaviour is strange. I will check up on cains comment

**Comment by andres-blanco** [comment]
I remove my assignment to this for now because working on issue themes/3483 is taking longer than expected

**Comment by ianstewart** [comment]
I was also able to get that "Theme not yet available for this site" error. With an older test site on a wpcomstaging domain. But not a newer one.

**Comment by DanielSmithMichigan** [comment]
I'm going to close this, but @ianstewart @kwight, feel free to reopen it if this was the wrong choice. Reasoning below.

I think the **original** issue is gone or very unlikely in our current state. I remember this issue happening much more often when I had made the issue. The originally suggested testing steps aren't even possible anymore, due to some recent UX changes, so maybe there were code changes that made this less likely in the last two months.

There are two discussions in this thread:

----
### Discussion one: Uploading AltoFocus Theme causes error: 'Theme not yet available for this site'
- AltoFocus is already available as an advanced theme. User's don't need to upload it.
- I can upload AltoFocus on self-hosted installations without an issue
----
### Discussion two: Uploading any theme has the chance to sometimes cause error: 'Unable to activate theme. Contact support'
- I uploaded the 20 most popular themes on wordpress.org, and didn't get this error for any of them.
- I created 15 new sites and uploaded a different theme for each one, and didn't see any errors.

One message I did see was sometimes was:  "async_cleanup". I wasn't creating new sites at the time though, I was just repeatedly reverting a site from atomic to simple from the blog report card, and then causing it to go atomic again by uploading a theme. I never got the error from a new site. So maybe I was just getting this error due to attempting an atomic upgrade while the revert process was still cleaning up some things. If you look at this graph (p1624928945025100-slack-CS4RTG11A), that explanation looks plausible.
