### ISSUE TITLE
Auto log in to mapped domain when navigating from Calypso

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#52939]
Navigating to a mapped domain site by clicking on links inside Calypso should automatically render the logged in experience for that site by setting auth cookies in the first party context. This would involve sending the user through the [logmein](https://github.com/Automattic/wp-calypso/issues/52740) redirects when they click on a link to the mapped domain site in Calypso. 

For example, we link to the site in the site preview page:

<img width="1667" alt="Screenshot 2021-05-18 at 8 58 15 AM" src="https://user-images.githubusercontent.com/1269602/118592811-35432d00-b7c4-11eb-80ec-5ef5e320cb00.png">

**Comment by niranjan-uma-shankar** [comment]
Worked on in https://github.com/Automattic/wp-calypso/pull/52909 and D61461-code.

**Comment by lsl** [comment]
Partially complete with #53443 and D61461-code, moving remaining work to new tickets.
