### ISSUE TITLE
Visiting a mapped domain site should render the logged in experience

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#52944]
A user who is logged in to WPCOM visiting a mapped domain site should get login cookies set in the first party context, and then the logged in experience should be rendered(admin bar, Edit button and so on).

**Comment by niranjan-uma-shankar** [comment]
This is being discussed in pcNnmV-5l-p2.

**Comment by lsl** [comment]
Partially fixed by #53443.

Follow up issues in the queue: #54110, #54109, #54108

I think you might have some open diffs for this but I'm not sure of the status so re-open if closing this was a mistake.
