### ISSUE TITLE
Domains: No error when registering .fr domain with a UK address

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#52957]
### Steps to reproduce the behavior

1. Go to My Site ->Upgrades ->Domains ->Add domain
2. Search for and add a .fr domain
3. On the contact info screen, select United Kingdom as the country
4. Make sure to also use a valid UK postal code, or else that will generate its own error
5. Click Continue to proceed to payment

#### What I expected to happen
To not be able to proceed past the contact information section. As per [our support documentation](https://wordpress.com/support/tlds-with-special-policies/about-fr-domains/#who-can-register-fr-domains), .fr domains cannot be registered by individuals or organisations in the UK, as the UK is no longer part of the European Union.

And if I try to register a .fr domain with another country selected, I get an immediate error indicating which countries' residents are allowed to register a .fr domain, so I cannot even proceed with the registration:

![Checkout_—_WordPress_com](https://user-images.githubusercontent.com/11873759/118626776-7428b100-b7cb-11eb-8069-7a62a269b75a.png)

#### What actually happened
For a UK address, ther are no errors at all, and a customer can even complete payment for the domain. However, the domain registration fails at the registry, resulting in a domain registration failed ticket in our system and no explanation to the customer why their domain registration failed.

### Context
Discovered this while following up on a domain registration failed ticket: 3995969-zen

The customer was charged $15 for the domain in the process. I've since refunded the charge.

**Comment by KokkieH** [comment]
We've had another customer attempt to register a .fr domain with a UK address in 4007890-zen

**Comment by ericamQA** [comment]
Was able to reproduce. I imagine this is due to Brexit, as when you set the country to "United States" you get the following error: 

".fr domains can only be registered by a company or resident of the European Union, Switzerland, Norway, Iceland, or Liechtenstein." 

The United Kingdom only recently stopped meeting this criteria.

**Comment by taggon** [comment]
The related data has been updated so UK addresses are no longer allowed of `.fr` domains.
For more details, see pd2HMz-Y-p2
