### ISSUE TITLE
Cropping images in Media cannot be saved in wp-admin Media

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#52955]
### Steps to reproduce the behavior

1. Go to Media (wp-admin/upload.php)
2. Click on Edit Image
3. Crop
4. Save

#### What I expected to happen

Cropped image saved

#### What actually happened

Save button is inactive https://d.pr/i/AcbMx2, it activates if I do another editing e.g. rotate, but after saving cropping is not saved, rotation yes.

#### Browser / OS version

Chrome, maxOS Big Sur, Ver 11.2.3

#### Is this specific to the applied theme? Which one?

Tried on 3 themes - repeats

#### Does this happen on simple or atomic sites or both?

Both

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://d.pr/i/AcbMx2

**Comment by kosiew** [comment]
Could reproduce this on a Jurassic Ninja site, confirming this is a Gutenberg issue.
Closed this.
Opened as https://github.com/WordPress/gutenberg/issues/32084
