### ISSUE TITLE
Comment Formatting: Bold and Italics not working in the Comment editor

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#52964]
### Steps to reproduce the behavior

1. Go to Comments page in the dashboard: https://wordpress.com/comments/all/
2. Click Edit to edit the comment
3. Double click on a word to highlight it and then click on the Bold or Italic option in the menu bar

![screenshot](https://d.pr/i/V03X2h+)
Image URL: https://d.pr/i/V03X2h

#### What I expected to happen
I expected the word to be made bold or italic

#### What actually happened
Nothing.

#### Browser / OS version
Chrome Version 90.0.4430.212 / Mac OS Catalina v 10.15.7

#### Is this specific to the applied theme? Which one?
It doesn't appear to be. I saw it on sites using Twenty Eleven, Karuna, and Balasana

#### Does this happen on simple or atomic sites or both?
Simple sites. My AT site seems to use the WP Admin version of the comments page.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It affected my user's site and my test sites.

#### Workaround
Manually dd the HTML tags (`<strong></strong>` and `<em></em>`)

3998819-zen

**Comment by sbathompson-he** [comment]
Also reported this exact issue here: Zen-4003035

**Comment by ericamQA** [comment]
Able to reproduce on Simple site, VIP (P2 site), and atomic sites (with and without Dashboard Appearance setting on). In all three cases, nothing happens when you try to make a portion of comment text **bold** or _italicized_.

**Comment by daria2303** [comment]
another one: 4086108-zd-woothemes
