### ISSUE TITLE
Gaps between cover blocks in the editor

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#52961]
### Steps to reproduce the behavior

1. Add two cover blocks, on after the other.
2. There is a gap between them in the editor but not in the public site
Editor view - https://d.pr/i/KAZS3a
Public view - https://d.pr/i/wLRrN8

Seems to occur on all themes and sites.

#### What I expected to happen
The editor to look like the public view

**Comment by porada** [comment]
The gap in the editor is intentional for two main reasons:

1. Visual distinction between the two separate blocks.
2. To provide the space for editor UI controls (which even happened to get captured on the screenshot).

Closing the issue for now.
