### ISSUE TITLE
Reader: Text appears below (not layered on top of) Cover Block images

### ISSUE THREAD

**Issue by Sandkorner** [Automattic/wp-calypso#52977]
#### What I expected to happen
To show the cover block text on the image in reader as well.

#### What actually happened
Text shown under the image.

#### Browser / OS version
Chrome - Version 90.0.4430.212 (Official Build) (x86_64)

#### Is this specific to the applied theme? Which one?
No, seems to be with many themes the same (Spearhead & 2021 checked)

#### Does this happen on simple or atomic sites or both?
Seems to be on both

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
<img width="823" alt="Screenshot 2021-05-18 at 21 30 09" src="https://user-images.githubusercontent.com/71094068/118705261-b0d2c780-b820-11eb-8315-78fcd4ec0cf0.png">
<img width="792" alt="Screenshot 2021-05-18 at 21 29 52" src="https://user-images.githubusercontent.com/71094068/118705265-b3352180-b820-11eb-9c33-8d62ff0ad2c4.png">

**Comment by ericamQA** [comment]
Related  (but more general) reader vs live site issue here: https://github.com/Automattic/wp-calypso/issues/43595

**Comment by roo2** [comment]
One change is we now support center aligned text properly. The reader experience is supposed to be simplified and visually consistent, so I think that we are best off leaving this as is.

On Site:
<img width="705" alt="Screen Shot 2023-02-16 at 2 02 59 pm" src="https://user-images.githubusercontent.com/22446385/219265634-f05fc75a-2f82-481c-b9bf-35e3f3371a13.png">


In Reader:
<img width="757" alt="Screen Shot 2023-02-16 at 2 02 42 pm" src="https://user-images.githubusercontent.com/22446385/219265552-e23d3f2d-dc8b-438a-8e62-cb9f9eb6824a.png">


Any objections to closing this @davemart-in , @ollierozdarz ?
