### ISSUE TITLE
Domain Manager: TXT records in the DNS with subdomains break wildcard CNAME records

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#5298]
This applies to all browsers and devices - it is a bug in how we are handling DNS in a very rarecircumstance: when you add a TXT record with a subdomain (host) entry.

In this case, our wildcard *.domain CNAME entry no longer works for that, and only that subdomain.

If you add the CNAME record as it's own DNS record, it does operate as it should once again.

Hopefully we can fix this at the core - by not allowing TXT records to interfere with the wildcard CNAMES

You can easily test this:
1) Register a custom domain with a WPcom site
2) load whatever.domain.com
3) Add a TXT with whatever subdomain, save
4) reload whatever.domain.com - it's broken

**Comment by lancewillett** [comment]
Could you add a screenshot or two if it's easy to grab? Visual records mean a lot for bug reports — even the future "you" that comes back to read it and parse it out again. :)

**Comment by spncrb** [comment]
It is pretty tough to capture easily since DNS propagates slowly and records get cached...but here is the main issue, /domains DNS on left, broken subdomain (CNAME) on the right:
![screen shot 2016-05-09 at 4 03 25 pm](https://cloud.githubusercontent.com/assets/8921630/15130773/c55b4092-15ff-11e6-8d03-607ac9d022fd.png)

**Comment by klimeryk** [comment]
Pinging team Lava (@schwuk @rads @matthusby) since this seems to be more of a backend issue to me.

**Comment by umurkontaci** [comment]
This is actually not a bug. It is an error to have a CNAME and a TXT record at the same record. i.e. you can't have both CNAME and TXT records at sub.domain.com. 

If you have a wildmark CNAME record though, TXT takes precedence and CNAME doesn't resolve at all.

RFC (Common DNS Errors): http://www.rfc-editor.org/rfc/rfc1912.txt (Section 2.4 - CNAME Records)

> A CNAME record is not allowed to coexist with any other data. In other words, if suzy.podunk.xx is an alias for sue.podunk.xx, you can't also have an MX record for suzy.podunk.edu, or an A record, or even TXT record. [...]
