### ISSUE TITLE
Site editor: Clicking "Site Editor" redirects me to the Post Editor

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#52981]
When testing the site editor in WordPress.com with Maylands Blocks theme, I am getting a weird redirect:

Steps:
1. Click My Site > Site Editor
2. See the browser URL temporarily show wordpress.com/site-editor/DOMAIN
3. See the browser URL redirect to https://DOMAIN/wp-admin/post-new.php?post_type=post&calypsoify=1 and I can’t access the site editor.

Video showing the issue:

https://user-images.githubusercontent.com/31009008/118707551-0d1df300-b7f1-11eb-91ec-0daa02985cd8.mp4

**Comment by mattwiebe** [comment]
Note that, while the fix is committed, this won't start working reliably until Jetpack 10.0 is released.
