### ISSUE TITLE
Plugins: Remove logic to disable and redirect plugins pages for Atomic

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#52986]
**Task Details**
- We need to remove all of the logic to disable and redirect the Plugins pages for Atomic sites.
- See client/my-sites/plugins/

PR: https://github.com/Automattic/wp-calypso/pull/53968

**Related to**
https://github.com/Automattic/wp-calypso/pull/52807

**Comment by allilevine** [comment]
PR: https://github.com/Automattic/wp-calypso/pull/53968

**Comment by allilevine** [comment]
We've deployed https://github.com/Automattic/wp-calypso/pull/53968 to remove several Calypsoify references, but we still need to:
- Decide whether to remove the /plugins redirect to wp-admin for Atomic (see https://github.com/Automattic/wp-calypso/pull/53968#pullrequestreview-699249512)
- Fix the redirect if we're keeping it (see https://github.com/Automattic/wp-calypso/issues/54143)
- Remove [one other reference to the `calypsoify/plugins` feature ](https://github.com/Automattic/wp-calypso/blob/a05c1757a87465ee93cf7477791456cc6324af00/client/my-sites/sidebar/tools-menu.jsx#L51) (see https://github.com/Automattic/wp-calypso/pull/53968#pullrequestreview-699249512)

**Comment by obenland** [comment]
Closing as all depending issues/PRs are closed.
