### ISSUE TITLE
Monthly business plan not recognized when installing plugin, on Horizon

### ISSUE THREAD

**Issue by desnum** [Automattic/wp-calypso#52982]
### Steps to reproduce the behavior

1. Go to https://href.li/?https://horizon.wordpress.com/new?flags=gutenboarding/site-editor
2. Walk through steps to create a new site
3. Select the business plan
4. In checkout, edit it to be a monthly (rather than annual) business plan
5. Checkout
6. Attempt to install WooCommerce

#### What I expected to happen

WooCommerce should be able to be installed

#### What actually happened

I get a message telling me to upgrade the plan:

<img width="1393" alt="Screen Shot 2021-05-18 at 1 48 59 PM" src="https://user-images.githubusercontent.com/43796228/118707133-29696200-b7e8-11eb-9b0e-c03c4d64363c.png">

### Context

This was discovered while testing WooCommerce with Full Site Editing: https://teamrubik.wordpress.com/2021/04/30/call-for-testing-woocommerce-with-fse-ii/

#### Browser / OS version

Chrome, Version 90.0.4430.93 (Official Build) (x86_64)
MacBookPro running Catalina

#### Is this specific to the applied theme? Which one?

I had Twenty Twenty active, but it seems irrelevant to the theme

#### Does this happen on simple or atomic sites or both?

A simple business site

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Just on Horizon

**Comment by kwight** [comment]
Horizon is considered a non-production testing environment, so low priority.

**Comment by arunsathiya** [comment]
Closing this report as the WordPress.com Business plan is not sold anymore, and various things have changed in terms of purchase flows in the last year.
