### ISSUE TITLE
My Home: Show reminder card at top of My Home if user hasn't verified their email yet

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#52991]
**What**
If the site setup checklist is complete, and the current user hasn't verified their email, then show a notification card on My Home to prompt them to verify.

Proposed card:
![image](https://user-images.githubusercontent.com/5665959/119572461-1eb95900-bdf6-11eb-9ebb-2af9b7eae806.png)

**Why**
It's possible for users to make it past the site setup checklist without verifying their email. If two users are admins on the same site, and user A completes the checklist, this hides the checklist for user B too. And user B may not have verified yet.
See: 114-gh-Automattic/dotcom-manage

Having a reminder on My Home is a way of reminding users who have fallen through this gap.

**How**
We already have alert style cards on My Home to remind the user about expiring plans. I'm thinking the email verification reminder could be something like this. In terms of order it'd come after the site setup checklist, but before the feature promotion cards.

(this is what the plan expiry reminder looks like)
<img width="947" alt="Screenshot 2021-05-19 at 5 26 55 PM" src="https://user-images.githubusercontent.com/1500769/118760745-6f492780-b8c7-11eb-9c1d-e804c635c0e9.png">

**Comment by p-jackson** [comment]
Actually, this edge case might not exist after all. If a user hasn't verified their email then they can't invite another admin to the site. And if a verified user invites an unverified user as an admin, the unverified user can't accept that invite without verifying their email (the invite is sent via email).

**Comment by autumnfjeld** [comment]
Per our verbal discussion @p-jackson I might to emphasize the business case in the "Why", that we want users to verify their email for a variety of reasons.  

A site might have many admin users, and the "Confirm your email address" will be satisfied if any one of these users have confirmed their email--which is appropriate, as it is a _site checklist_ not a user checklist.
If we are interested in using My Home to encourage email confirmation, we could create a view (294fb-pb) (a primary card) that would show conditionally when a user has not confirmed their email.

Would be good to know from design/biz point of view if we should go forward with this.  @simison @jeffgolenski 

Helpful info on views & cards
pd2qGl-2J-p2
Visual of a view & its cards: pd2qGl-2w-p2#comment-81
My Home Design Guidelines: PCYsg-quF-p2


![bitmoji](https://sdk.bitmoji.com/render/panel/c7cb9dee-3c6f-488e-96e3-76db13f87c0d-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=40)

**Comment by p-jackson** [comment]
> Would be good to know from design/biz point of view if we should go forward with this

I think a difficulty with answering this question is we don't know how common this problem is. There _shouldn't_ be any users in this edge case, but I'm not sure that's true. My proposal would be very quickly create a new card (copy paste some existing copy) that is shown to unverified users post setup and add an MC stat to it so we can count if it's happening.
If it's a lot of users then we can do a nicer design.

**Comment by p-jackson** [comment]
#53035 creates a card for unverified users using pre-existing text. Re-using text so that we don't have to spend as much time on design if this doesn't end up affecting many users.

<img width="940" alt="Screenshot 2021-05-20 at 4 03 02 PM" src="https://user-images.githubusercontent.com/1500769/118919470-adf2e680-b988-11eb-9a64-b8f22e7eda8f.png">

The existing `calypso_customer_home_card_impression` tracks event can be used to see how often the new card is seen. The property to look for will be `card=home-task-verify-email`

**Comment by autumnfjeld** [comment]
@p-jackson    Just want to make sure we get HE/business/eyes across this. I wasn't sure if anyone is actually aware we're ready to ship this.  Maybe a P2 for HE? If you didn't already have that in the works.   

cc: @jordesign

**Comment by p-jackson** [comment]
Card has been deployed in #53035. Tracking post for feedback/metrics pd2qGl-4V-p2
