### ISSUE TITLE
My Home: Hide 'WordPress App' card on my home if the user already has the mobile app & logged in

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#52995]
If the user has already downloaded and installed the WordPress App - can we please hide this card from My Home.

<img width="354" alt="Screen Shot 2021-05-19 at 5 13 48 pm" src="https://user-images.githubusercontent.com/1842363/118771339-c8b05700-b8c5-11eb-900c-eb290a9582b4.png">

There seems to have been a little discussion around this previously:
https://github.com/Automattic/wp-calypso/issues/39146

Previous advice from @elibud was: 

> This is fine with me as long as we check that the user has logged in into the app via tracks, thanks for the ping.

**Comment by autumnfjeld** [comment]
Work to do on this: finding the appropriate flag that reliably tells us that the user has logged in to the mobile app. 

Not sure exactly what the reference to tracks meant, we'd want to create a more robust conditional check in the code than tracks (I think).

**Comment by p-jackson** [comment]
The reason I'm not convinced about using tracks is it's designed to be purgable. Once the retention window is up we should expect the event to go away, so it's not quite like our regular database.

I did some digging and unfortunately haven't found anything in our existing metadata/attributes for users that changes when the user logs in to the mobile app for the first time. I wonder if it'd be a good idea to add this to the login endpoint i.e. check if the login comes from a mobile app and set a user attribute.

**Comment by jordesign** [comment]
Could we check if they have a valid/open oAuth connection to the App?

My User report card shows that I have a connection to the iOS app as an example?

**Comment by p-jackson** [comment]
Oh that's a great idea @jordesign! It's visible right here in Calypso `/me/security/connected-applications`

<img width="974" alt="Screenshot 2021-05-22 at 12 14 02 PM" src="https://user-images.githubusercontent.com/1500769/119208629-427b5700-baf7-11eb-8ac9-6b3b3a765ce2.png">

**Comment by p-jackson** [comment]
Working on changes here: D62067-code

@yaelirub the logic I'm using to hide this card 
<img width="354" alt="118771339-c8b05700-b8c5-11eb-900c-eb290a9582b4" src="https://user-images.githubusercontent.com/1500769/120135535-93d8c400-c224-11eb-8bcf-f0372d6be75d.png">
 on My Home is to check whether any of these oauth clients are currently connected to the user's account:
- Android app
- iOS app
- Android trialmattician app
- iOS trialmattician app
- iOS beta app
- iOS alpha app

It means that if the user disconnects the app from their account, then the card will appear again.

Does this seem like a reasonable approach?

**Comment by autumnfjeld** [comment]
Given recent discussion and work on this, should we close this?
https://github.com/orgs/Automattic/projects/252#card-62139652

Or should we keep it open for the possibility of using tracks event to provide more refinement?  e.g. `wpandroid_application_opened`

**Comment by p-jackson** [comment]
@autumnfjeld I was keeping it open and working on other things because I wasn't sure where the discussion would end up landing. It still seemed possible that, on balance, the oauth approach could still be the approach we take. But happy to close if that's not how you're reading the situation.

**Comment by autumnfjeld** [comment]
I'm going to go ahead an close this:
*  ~~This work was done in D62067-code, hiding the WP App card when user has already downloaded the app~~ ❗ CORRECTION 29 July 2021: that diff was never merged into the back end.
*  I expect we might be collaborating with mobile team, @yaelirub  to [flesh out additional ideas of how we can better promote the mobile app](pbArwn-2nd-p2#comment-3468) to both users who have already downloaded the app as well as users who have downloaded it but are not active, and to also share new mobile app features.  

c: @yaelirub

**Comment by yaelirub** [comment]
Nexts so much @autumnfjeld ! Will be more than happy to collaborate :D

**Comment by autumnfjeld** [comment]
> * This work was done in D62067-code, hiding the WP App card when user has already downloaded the app

❗ CORRECTION: that diff was never merged into the back end.

The WP App card still shows even if the user has downloaded the app.

cc: @p-jackson @yaelirub
