### ISSUE TITLE
My Home: Decide which Support Docs should be shown by default in My Home.

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#52996]
Currently, there is a list of 6 Support Docs in My Home by default. These are displayed *before* the user enters a search term.

<img width="339" alt="Screen Shot 2021-05-19 at 5 20 03 pm" src="https://user-images.githubusercontent.com/1842363/118772110-b2ef6180-b8c6-11eb-9874-e49261e840e7.png">

* Do I Need a Website, a Blog, or a Website with a Blog?
* Uploading custom plugins and themes
* All About Domains
* Quick-Start Guide
* Privacy Settings
* Managing Purchases

We have an opportunity to decide:

1. How many items to show
2. Which items to show

---

We have a list of most viewed  support documents:
https://docs.google.com/spreadsheets/d/1GIFTkLwHg7zqDQAGSeLeTs5VEguAvKoOFR32Dt37hNs/edit#gid=1409874312

And also some insights drawn from that list:
pd2qGl-q-p2

---

**Comment by jordesign** [comment]
Question: Should we have different items pre-launch VS post-launch?

**Comment by jordesign** [comment]
I thought I'd start us off with 2 lists - something to seed the discussion:

#### Pre-Launch

* https://wordpress.com/support/start/
* https://wordpress.com/support/settings/privacy-settings/
* https://wordpress.com/support/domains/
* https://wordpress.com/support/wordpress-editor/
* https://wordpress.com/support/menus/
* https://wordpress.com/support/manage-purchases/

#### Post-Launch

* https://wordpress.com/support/getting-more-views-and-traffic/
* https://wordpress.com/support/add-email/adding-email-powered-by-titan-to-your-site/
* https://wordpress.com/support/stats/
* https://wordpress.com/support/monetize-your-site/

----
Totally keen for anyone else thoughts - particularly @ktyfuller604 and @donalirl

**Comment by ktyfuller604** [comment]
There are also 20 How-To videos in post-production, pulled from the top viewed docs and pain points, that Athens worked on as part of our Virtual Meetup. 

Many of the videos will replace existing, outdated videos in docs (like Add a Domain and Setting up Menus), but can also be added to this [Video Tutorials landing page](https://wordpress.com/support/video-tutorials/) - if we'd like to emphasize that link the support list for folks who gravitate toward visual learning. Although... it is mentioned in the "Start" guide in the Pre-launch list. So, up for discussion!

Assuming they're ready in time. :-)  

List of videos in post-production: https://docs.google.com/spreadsheets/d/17CLU74oS_7yWqgXljxFx3ObUPNMX8Xb3RkBtGRc7D38/edit#gid=903749075

The Manage Purchases doc is in the middle of a revamp (it suffers from ["doc bloat"](p2rHU0-Uu-p2)), just as a heads up. :-)

The Images guide might be a good one to include in the Pre-launch list: https://wordpress.com/support/images/

**Comment by donalirl** [comment]
> The Manage Purchases doc is in the middle of a revamp (it suffers from ["doc bloat"](p2rHU0-Uu-p2)), just as a heads up. :-)

This doc will be in the best shape of its life by the end of this week 😁 

I like your list Jordan and don't have any others to add. Will there be an opportunity to change which docs are linked over time? Let's say in six months from now we want to highlight resources relating to FSE for example, we may want to request those docs be included.

**Comment by jordesign** [comment]
> Will there be an opportunity to change which docs are linked over time? Let's say in six months from now we want to highlight resources relating to FSE for example, we may want to request those docs be included.

I'd certainly like to think so.

Just flagging that with Devs for discussion as we move forward with this - what will the difficulty level be of periodically updating this list of links?

**Comment by jordesign** [comment]
Based on existing conversations about the 'Edit Menu' item of the checklist - I think it i important that we keep a link to the support doc for Menus in the list for both states.
https://github.com/Automattic/wp-calypso/issues/52706

**Comment by jordesign** [comment]
Flagging that based on our Pod discussions today - we may want to have a number of lists of popular/helpful documents for different use-cases:

* Sites
* Bloggers
* eCommerce/Stores

**Comment by jordesign** [comment]
Closing this issue - as support docs will be handled differently in the new redesign.
pbAok1-2L4-p2
