### ISSUE TITLE
DSS: Header image not updating with themes that set random default header images

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#53]
Happened with Colinear theme in testing, reported by @ianstewart.

Tested DSS here https://cutedogsnov16.wordpress.com/ and the custom header didn’t update. Perhaps an issue with themes that have random default header images?

![screen shot 2015-11-16 at 3 50 29 pm](https://cloud.githubusercontent.com/assets/66797/11228592/ec50d182-8d4a-11e5-8877-eede6b5ef7c5.png)

Also it looks like the Headstart survey is running with the test:

![screen shot 2015-11-16 at 3 43 41 pm](https://cloud.githubusercontent.com/assets/66797/11228597/f21e6b06-8d4a-11e5-83f5-3576a301bef4.png)

**Comment by kwight** [comment]
DSS was removed from signup in #2580, and we have no future plans for this version.
