### ISSUE TITLE
Custom fields setting is not working in the Gutenberg

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#53008]
### Steps to reproduce the behavior

1. Open Gutenberg on WPCOM
2. Open ... -> Preferences -> Panels
3. Turn on "Additional -> Custom fields"
4. It will ask you to reload
5. There is no change. When you return to that setting, it's still OFF.

Video here: https://www.loom.com/share/c712a7f6cda14f018e6c66678dabbe08

#### What I expected to happen

The custom fields panel to appear in the post sidebar

#### What actually happened

Nothing, the setting was not changed.

### Context

I want to use meta field for master threads on the P2.

#### Browser / OS version

Chrome, OSX Catalina

#### Is this specific to the applied theme? Which one?

Tried on P2 and Shoreditch

#### Does this happen on simple or atomic sites or both?

**Both**

#### Is there any console output or error text?

Nope

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects more than one site, but I do not expect many people using it.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Zrzut ekranu 2021-05-19 o 14 20 28](https://user-images.githubusercontent.com/3775068/118812231-305aa800-b8ae-11eb-9fa6-5048d47118e2.png)

**Comment by simison** [comment]
Should the solution be to make custom fields work, or hide the setting entirely? I.e. not sure if simple sites have some limitations for these.

**Comment by artpi** [comment]
They would show up in the API if you edit it on the simple site, but I don't think we have a theme or functionality that utilizes them.
I see the value in having those working, but clearly, it's not a big issue if nobody discovered it before me.

**Comment by simison** [comment]
cc @WunderBart @fullofcaffeine this might be good for your backlog since it's Gutenberg/Simple compatibility issue.

**Comment by joashrajin** [comment]
4042945-zd-woothemes

**Comment by artpi** [comment]
Edit: the problem is definitely on Simple. After moving my site to Atomic, it stopped.

I was under the impression Atomic is affected as well, but it was just cached version of the UI

**Comment by formosattic** [comment]
Just noting there's an older related thread at https://github.com/Automattic/wp-calypso/issues/36226 , we should close one in favor of one open issue, though not sure which one you prefer keeping.

**Comment by artpi** [comment]
Closing this in favor of #36226
