### ISSUE TITLE
Domains: Registered Domain Forwarding / Redirect

### ISSUE THREAD

**Issue by kristenzuck** [Automattic/wp-calypso#53027]
**What**

The ability to offer domain forwarding to customers who have their domain registered with us. This is something other services offer, and currently HEs use hacks like moving a domain to a free placeholder site to help customers achieve what they want. 

**Why**

If we are acting as a domain registrar we should make it simpler for customers to keep their domains with us and use them how they would prefer, without weird hacks like creating another site and moving it over. Support is seeing requests for this with increasing frequency. 

This suggestion came out of a discussion internally about workarounds used to accomplish customer goals.

**Comment by JoshuaGoode** [comment]
Related internal discussions:

pKdGS-1Ow-p2
p7DVsv-6DY-p2

Example: p1629823693259100-slack-C03TY6J1A

---

**Additional details:**

Some users request an option to redirect a secondary domain or subdomain to a specific URL.  Often, this will be a subdomain that they want to redirect to a specific URL on their primary domain.

**Example:**
User would like to redirect/forward `subdomain.example.tld` to `example.tld/destination`.

Or, `examplesecondarydomain.tld` to `example.tld/destination`.

---

One workaround is to use a third-party DNS service like Cloudflare and set up a Page Rule with the Forwarding URL option.

**Comment by JoshuaGoode** [comment]
4397593-hc

**Comment by jp-imagines** [comment]
31709727-hc: user registered two domains on their site, and wanted to point one of them to a specific page on that site. Directed them to Cloudflare per Joshua's suggestions.

**Comment by cuemarie** [comment]
Had this request here: 6940433-hc

Will follow up with them and offer the Cloudflare suggestion

**Comment by kathrynwp** [comment]
Also requested in 34795374-hc

**Comment by cuemarie** [comment]
Requested here: 35328301-hc
Suggested Cloudflare workaround

**Comment by Greatdane** [comment]
Moving over requests from other issue;

p7DVsv-6DY
p7DVsv-6Ir
pKdGS-1Ow

reports;
4430312-zen
33878296-hc
33816111-hc
19814760-hc
35550279-hc

**Comment by rw-ye** [comment]
Another request here: 35392659-hc

Suggested Cloudflare

**Comment by kelasante** [comment]
Another request in 35746989-hc. Shared Site redirect and Cloudflare as options.

**Comment by jp-imagines** [comment]
Another request in 34934927-hc. User wanted to forward two domains to different pages on their site, so I suggested the Cloudflare workaround.

**Comment by happychait** [comment]
A customer asked to allow using the root domain as of the site at a page like /site example: https://yourgroovydomain.com/site 

37609003-hc

**Comment by rw-ye** [comment]
36688539-hc

Suggested Cloudflare Page Rules

**Comment by cuemarie** [comment]
Another request for this here: 37613859-hc

Pointed them to Cloudflare

**Comment by carinapilar** [comment]
Another on 38691081-hc - shared Cloudflare's workaround.

**Comment by carinapilar** [comment]
Another request on 37344357-hc

**Comment by kelasante** [comment]
Another request in 36529623-hc

**Comment by liviopv** [comment]
- [ ] 5984471-zd-woothemes

**Comment by carinapilar** [comment]
Another on 29938754-hc

**Comment by happychait** [comment]
A user requested this in 36538278-hc

**Comment by happychait** [comment]
42562539-hc

**Comment by vajrasar** [comment]
42566787-hc

**Comment by liviopv** [comment]
42698190-hc

**Comment by Greatdane** [comment]
6473678-zd-woothemes

**Comment by rw-ye** [comment]
6607513-zen

**Comment by happychait** [comment]
WordPress.com now offers Domain Forwarding 🎉

- Announcement blog post: [More Control Over Your Domain—Introducing Forwarding ](https://wordpress.com/blog/2023/08/22/introducing-domain-forwarding/)
- Support guide: [Domain Forwarding](https://wordpress.com/support/domain-forwarding/)

**Comment by cuemarie** [comment]
Domain Forwarding, mentioned above, now also supports redirecting to the same domain, which is a big part of where these user requests come from. Yay! 🎉  https://github.com/Automattic/wp-calypso/issues/81323
