### ISSUE TITLE
My Home: Inconsistent use of 'Home Page' and 'Homepage' 

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#53036]
At the moment we have varied usage of 'Home Page' and 'Homepage' throughout my home - we should standardize this. At the very least this well effect:

* 'Update Home Page' action card
* Checklist item
* Quick link
<img width="857" alt="Screen Shot 2021-05-20 at 3 38 06 pm" src="https://user-images.githubusercontent.com/1842363/118925175-9f550100-b981-11eb-87a5-e40a1baea2c2.png">

Perhaps @Automattic/editorial can direct us on the best option?

**Comment by simison** [comment]
Few more places to consider:

![Screenshot_20210521-103820_Firefox.png](https://user-images.githubusercontent.com/87168/119100707-e80fc700-ba20-11eb-8633-552bf1d633ce.png)

![Screenshot_20210521-103428_Firefox.png](https://user-images.githubusercontent.com/87168/119100718-eba34e00-ba20-11eb-8909-5f7ae6c21c7d.png)

![Screenshot_20210521-103234_Firefox.png](https://user-images.githubusercontent.com/87168/119100731-ee9e3e80-ba20-11eb-9f11-f6753f492e2b.png)

<img width="387" alt="Screenshot 2021-05-21 at 14 22 08" src="https://user-images.githubusercontent.com/87168/119129750-01743b80-ba40-11eb-91cb-2dab3fffe61b.png">


App
![Screenshot_20210521-103140_WordPress.png](https://user-images.githubusercontent.com/87168/119100754-f5c54c80-ba20-11eb-9def-93fb49ad3870.png)

**Comment by michaelpick** [comment]
The Automattic Style Guide says 'homepage', FWIW!

**Comment by jordesign** [comment]
'Homepage' also seems to be the core WP usage as suggested in this guide.
https://make.wordpress.org/docs/handbook/documentation-team-handbook/handbooks-grammar-guide/#general

**Comment by Aurorum** [comment]
The capitalisation should also probably be consistent - "**H**omepage" is used in a few cases (eg. the checklist and the post ellipses) but I wonder if "**h**omepage" might be better?

**Comment by simison** [comment]
Sounds like the "Front Page" bit at core could be updated as well, then! 🎉

**Comment by jordesign** [comment]
Ah - missed these last few messages regarding capitalisation - but have drafted a PR
https://github.com/Automattic/wp-calypso/pull/53076

Will hold off until we get a decision about the final capitalisation.

**Comment by jordesign** [comment]
Although looking at things - I think I may have made that PR incorrectly...

New one at https://github.com/Automattic/wp-calypso/pull/53101 which I think is correct.

**Comment by p-jackson** [comment]
Fixed by #53101
