### ISSUE TITLE
Onboarding: Likes added to pages by default

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#53057]
### Steps to reproduce the behavior

1. Create a new site on WP.com.
2. Navigate to a page that was created by WP.com setup processes.

#### What I saw

Like buttons turned on for every page by default.

![image](https://user-images.githubusercontent.com/545779/119028754-71fe5800-b96d-11eb-946e-4287f7a5b71a.png)

#### What I expected to happen

Subjective, but my general feeling is that, while Like and Sharing buttons are natural for indexed and regularly published content like Blog Posts, it feels un-natural to turn Like buttons on for all pages on all new sites by default.

I expected like buttons to be off by default.

**Comment by michaeldcain** [comment]
Closed in #53605
