### ISSUE TITLE
Jetpack Connect: Header Jetpack logo touches masterbar on mobile

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#5306]
@rickybanister mentioned to me that y'all may be getting rid of the Jetpack logo in the header, so this may not be an issue. But, today I noticed that when on a mobile size viewport, that the Jetpack logo touches the masterbar.

I would expect there to be some space there. Maybe 16px?

![screen shot 2016-05-09 at 5 58 34 pm](https://cloud.githubusercontent.com/assets/1126811/15130789/a5451286-1610-11e6-9cbd-3094c603bcb0.png)

**Comment by johnHackworth** [comment]
That logo has been removed in the latest iteration :tada:
