### ISSUE TITLE
Plans SEO: Tweaks to Visibility Section

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5307]
Let's match up the Visibility section in site settings to how it works in the WP mobile apps:

1. Updates to the copy
2. Rename 'Visibility' to 'Privacy'

Updates detailed here:
![artboard1](https://cloud.githubusercontent.com/assets/789137/15131064/cf5f6d96-1601-11e6-8f35-82c44e216060.png)

**Comment by drw158** [comment]
If we only do this, I think it will be a good first change to ship. Eventually, I think this would be ideal:

Settings > SEO
![artboard copy 5](https://cloud.githubusercontent.com/assets/618551/15186738/cf53bfec-1763-11e6-9dcf-cd153501dbe5.png)

Settings > General
![artboard copy 11](https://cloud.githubusercontent.com/assets/618551/15186918/8db8a34e-1764-11e6-8116-64d911481446.png)


But, this is a bigger change that will need some more eyes on it and updates to support docs. I'm not sure if it should be done before or after SEO v1.

If we do this later, then we can add a notice on the SEO page that informs the user why everything is grayed out (if they have something other that Public selected).

**Comment by mtias** [comment]
@drw158 that looks great. Should we use the `toggle` component since it's a single option?

**Comment by drw158** [comment]
@mtias I didn't use it since the expectation with a toggle is that it saves the setting immediately. I would like to use a toggle though, if the user didn't have to hit the save button.

**Comment by mtias** [comment]
Ah, that's interesting because we are adding a few toggles for custom post types. Also the editor uses toggles that are not saved immediately, I think.

In the settings page we have a dialog warning if you navigate with unsaved changes, so I think it should be fine?

**Comment by drw158** [comment]
Hm, I haven't seen the custom post type stuff, but I did notice that the editor uses toggles. I think that is appropriate because there is no save button — you just toggle the switch and it saves.

Where are the custom post type examples?

I think we could use a toggle, but I didn't know if there was a push to get rid of the save buttons in Settings.
