### ISSUE TITLE
Plans SEO: New SEO Section in Site Settings

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5308]
Let's add a new section to site settings that includes some details about SEO, and a new feature that allows you to add a custom site meta description for search engines. This new setting will override the site tagline from being used as the meta description if it exists.

Design details:
![artboard-copy-6](https://cloud.githubusercontent.com/assets/789137/15131121/283b764e-1602-11e6-8ea4-47b279cfd553.png)

If the site is set to private, then the entire card should be disabled:
![artboard-copy-7](https://cloud.githubusercontent.com/assets/789137/15131123/3660cbc0-1602-11e6-8d26-dc85714e693c.png)

#5307 should be implemented before this.

**Comment by mtias** [comment]
Does this mean moving privacy to the SEO section?

**Comment by roundhill** [comment]
> Does this mean moving privacy to the SEO section?

No, privacy will remain in its own section, like shown in the screenshot.

**Comment by mtias** [comment]
@roundhill I mean under what sub section of `/settings`? Setting a site as private is done in `/settings/general` would SEO be under that area as well or under `/settings/seo`?

**Comment by roundhill** [comment]
> @roundhill I mean under what sub section of /settings? Setting a site as private is done in /settings/general would SEO be under that area as well or under /settings/seo?

Oh, I believe still in `general`. @drw158 that was your thinking, right?

**Comment by mtias** [comment]
I wonder if perhaps we can combine it with Analytics & SEO? The general tab is getting quite big :)

**Comment by drw158** [comment]
The quickest solution I can think of is:

- Put Import, Export (it's still coming right?), and Analytics in a new tab called `Tools`.
- Put SEO into its own tab.

The question is whether it deserves its own tab. Are users interested in SEO only the vocal minority, or is SEO just as important as Writing and the other top level tabs?

**Comment by roundhill** [comment]
I've got it working in a tab, let me know what you think!

<img width="736" alt="screen shot 2016-05-10 at 4 49 54 pm" src="https://cloud.githubusercontent.com/assets/789137/15166014/6fb244ee-16cf-11e6-8013-da82aadf3caa.png">

**Comment by drw158** [comment]
I tried to use your branch, but clicking on SEO didn't seem to work. Judging from the screenshot, I think it's coming along nicely. That was fast, good job!

Does the site description only affect the homepage, or all pages? After digging more into this, I'd like to think more about the effect of this change for every page that is not the homepage. Afaik, we automatically change the meta description for posts and CPTs, but I'm not sure.

I think the webmaster section will need the most attention to UX. It can be hard to understand what this is. I think with the combination of good copy and placeholder text, it will be clear. I'm leaning toward listing out the services with links in the intro copy.

**Comment by drw158** [comment]
Suggestions for warning notices:

If they have the Private setting on:

> Your site is not visible to search engines when the Private setting is enabled.

If they have the Hidden setting on:

> Your site is not visible to search engines when the Hidden setting is enabled.

Or if you want to simply it in the code to just one warning:

> Your site is not visible to search engines when the Private or Hidden settings are enabled.

I'm not sure what the notice will look like when you drop it into the Card, so you don't have to follow the mockups closely. Whatever happens will probably look good.

**Comment by roundhill** [comment]
> Does the site description only affect the homepage, or all pages?

This only affects the front page description, since WordPress uses the post/page content as the description. I've changed the label to `Front Page Meta Description`.

**Comment by drw158** [comment]
We need to add links for the site verification copy, and after that I think this is ready for a PR and design review.

Links:

https://www.google.com/webmasters/tools/
http://www.bing.com/webmaster/
https://pinterest.com/website/verify/
https://webmaster.yandex.com/sites/

And a link for the `Full instructions` text

https://en.support.wordpress.com/webmaster-tools/

**Comment by roundhill** [comment]
> We need to add links for the site verification copy

Added the links and created #5365 🚀
