### ISSUE TITLE
PDF embeds inline in Gutenberg editor but disappears in published post

### ISSUE THREAD

**Issue by sethmclellana8c** [Automattic/wp-calypso#53088]
### Steps to reproduce the behavior

1. Make a draft p2 post
2. Drag and drop a pdf into post
3. (My editor auto-selected the 'Inline embed' setting from the File block - as expected)
4. Link to download file appears below inline embed in editor
5. Hit publish
6. Inline embed disappears and download file link remains 

#### What I expected to happen

-Drag and drop pdf file into draft of post and inline embed automatically appears (THIS HAPPENED AS EXPECTED)
-pdf is embedded inline in p2 post, enabling me to scroll through my deck in the p2 post (this didn't happen)

#### What actually happened

pdf inline embed disappeared when I published my draft

#### Browser / OS version

Browser: Version 90.0.4430.212 (Official Build) (x86_64)
OS: Mac OS Big Sur 11.3.1

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/37377834/119180463-f3b9b880-ba35-11eb-9510-a6ec21a8fdc5.mov

**Comment by fylgjur** [comment]
I experienced this too

**Comment by aleone89** [comment]
There's been a report of this here: https://wordpress.com/forums/topic/loaded-new-post-but-its-not-opening-on-page/?view=all - the user was using a PDF, and have suggested just placing the link of the PDF into the post.

**Comment by KokkieH** [comment]
Could this be related to #52728? PDF embeds via the File Block are also broken.

**Comment by KokkieH** [comment]
User report in https://wordpress.com/forums/topic/embedded-pdf-no-longer-displaying/?view=all

**Comment by csonnek** [comment]
Reported in https://wordpress.com/forums/topic/embedding-a-pdf-file-not-working-after-changing-the-theme/?view=all

In my own testing using the File Block, Embed Block, and simply pasting the PDF file into the post editor [per our own support documents](https://wordpress.com/support/embedding-a-pdf-file/), it only will show the link to the file and not the embed. 

Even on the linked support document the "[example embed](https://wordpress.com/support/embedding-a-pdf-file/#example-of-an-embedded-pdf)" is also showing a link to the file and not the embed. 

Test post: p3jvOq-bW3G0-p2

**Comment by rosepajaroja** [comment]
This could be related ZD-4707018. Facebook and Embed block don't seem to work. 

I did a couple of tests: 

On simple sites: 

Both Facebook and Embed blocks change to Paragram Block after clicking "Embed" button, and it will display a text link. 

On AT sites: 

It will show an error: 

![Alt text](https://d.pr/i/ibMXtV/kaTooqIPmQ+)

**Comment by metabreakr** [comment]
Also reported here: https://wordpress.com/forums/topic/pdf-file-display-on-blog-post-not-working/

This issue is discussed in p3btAN-1Ab-p2

**Comment by formosattic** [comment]
Will close this in favor of this older thread #52728 which has more user reports and is already triaged.
