### ISSUE TITLE
Images do not display when site is private and has a custom domain when cross site cookies are blocked

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#53102]
### Steps to reproduce the behavior

1. Set site as private 
2. Open Safari 
3. block cross site cookies in preferences > privacy

#### What I expected to happen
since rest of site loads, images should load as well

#### What actually happened
no images load for some reason
works fine in Chrome and Firefox

### Context

4012360-zen

#### Browser / OS version
safari

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
for sure simple, not sure about AT

#### Is there any console output or error text?
`Failed to load resource: the server responded with a status of 403 ()`

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
presumably all private sites using safari

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
without cookies blocked:
![image](https://user-images.githubusercontent.com/47717887/119261381-cc065400-bbdf-11eb-900f-11680a13719d.png)

with cookies blocked:
![image](https://user-images.githubusercontent.com/47717887/119261389-df192400-bbdf-11eb-8e9c-e87fcee1b73a.png)

**Comment by kosiew** [comment]
Hi @Nic-Sevic ,

Can you provide more details to reproduce this?

I could not reproduce it with these conditions:
1. simple site
2. prevent cross site trackin
3. site set to private

![Screenshot](https://d.pr/i/53Nddr+)
*if image does not load, please click on this link  : https://d.pr/i/53Nddr*

**Comment by rezzap** [comment]
Triaging this issue and replicated this only on a site with a mapped custom domain which would indicate the 3rd party cookies is definitely related

There's a very similar issue reported on mobile that seems related to this in https://github.com/wordpress-mobile/WordPress-iOS/issues/15596 

I can get the images to be kept in place if I set the site to be public temporarily and then move back to private and refresh the page. 

I'll keep this issue open since the issue is for the web and not the app.

**Comment by MaxPhilip** [comment]
Two more tickets with the same issue. While sites are private no images are loading in Safari (tested on Mac, iPhone and iPad), same 403 error shown in browser console. As soon as site is published the images are loading fine. When disabling the "block cross site tracking" option all images are loading fine on private sites.

4026397-zen
4034674-zen

Both sites are using custom domains registered with WP.com.

**Comment by chad1008** [comment]
I'm actually able to reproduce this in Chrome now as well. Reported in 23817087-hc.

Same symptoms, no images, 403s in the console.

Changing the primary domain resolves it, at least temporarily.

Works fine in Firefox, so I'm wondering if there's something new in Chrome?

My Chrome version: 91.0.4472.101 (Official Build) (x86_64)

Relates slack convos:
- p1623698215168200-slack-C01V2160U15
- p1623697515422000-slack-C03TY6J1A

**Comment by gwensmithx** [comment]
I have another to add here:

30317279-hc
4101765-zen

Using Chrome with custom domain as primary, we set the site (AT) to private and image links on most products were broken. Also visiting the site in incognito mode still showed the page still but with the broken images. When site is public all images are working fine. Also switching to the wpcomstaging domain when site is private will show the private site message in incognito mode as expected but the images are still broken if logged in.

Chrome V: Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by dcoleonline** [comment]
28559420-hc

This failed for the customer on an iPhone 12 in Safari and Firefox. 
We set the site to Coming Soon and then back to Private and it ended up working for them.
I didn't end up getting the iOS version info as wasn't aware of this report until after the chat ended.
For now at least, they seem to be all set.

**Comment by tanjoymor** [comment]
> 28559420-hc
> 
> This failed for the customer on an iPhone 12 in Safari and Firefox.
> We set the site to Coming Soon and then back to Private and it ended up working for them.
> I didn't end up getting the iOS version info as wasn't aware of this report until after the chat ended.
> For now at least, they seem to be all set.

This customer returned #30658931-hc saying that the problem returned and I advised about disabling Safari ITP for now. They have specifically asked for a follow up once this has been fixed. Noting here for cross-reference.

**Comment by cuemarie** [comment]
4194815-zd-woothemes
Safari 14.1 on macOS 
Custom domain registered with WP.Com

>The workaround that I have now got is as follows:
>1. In Private mode, on a page where the images are missing, make a change (even just adding a space somewhere). Update. View Page - still missing.
>2. Change to Coming Soon - refresh page - can see images
>3. Change back to Private - refresh page - images are still there!

I have asked the user to try enabling cross-site cookies in Safari and switching their primary domain as potential workarounds.

**Comment by zachspears** [comment]
31104768-hc
I had this user return in chat and ask about the status of this bug report. They would like to use their custom domain with their site again. They have specifically asked for a follow-up once this has been fixed.

**Comment by hideandgeek404** [comment]
4312501-zd-woothemes

Simple site
Custom domain as primary
No images - 403 error

It looks like this is another case and I also did spot another the other day but didn't realise this was an existing issue. If I can find it then I will add it here.

**Comment by hideandgeek404** [comment]
4327740-zd-woothemes

Simple site
Custom domain as primary
No images - 403 error

Here is another reported instance of images not loading on a simple site when the custom domain is set as primary.

**Comment by rachelwinspear** [comment]
4399933-zen 

Simple site
Custom domain as primary
No images - 403 error

Switching to default domain resolves the issue. Please update user when resolved.

**Comment by metabreakr** [comment]
32953245-hc

**Comment by daria2303** [comment]
4713402-zd-woothemes

**Comment by zdenys** [comment]
4736381-zd-woothemes

**Comment by zdenys** [comment]
4747684-zd-woothemes

**Comment by zdenys** [comment]
4774971-zd-woothemes

**Comment by zdenys** [comment]
4785282-zd-woothemes

**Comment by zdenys** [comment]
4829352-zd-woothemes

**Comment by zdenys** [comment]
4932291-zd-woothemes

**Comment by zdenys** [comment]
4935151-zd-woothemes

**Comment by MaxPhilip** [comment]
4966920-zd

**Comment by MaxPhilip** [comment]
5177276-zd

**Comment by bluefuton** [comment]
Updated the description because this happens in multiple browsers.

This is a good candidate for a priority upgrade I think, because the private site experience feels really broken with images failing to load at all. The available workaround (switch to a *.wordpress.com as your primary domain) is not a great one.

**Comment by mzitinfo** [comment]
I've come across a report of this happening in both Firefox and Safari, in zen-5340660.

Update: This user confirmed that the workaround of first publishing the site, and then setting it back to private, solved the issue. (The images are displayed, even though the site is set back to private)

**Comment by MaxPhilip** [comment]
Another report: 5361297-zd

**Comment by mzitinfo** [comment]
Another one in 5368345-zd

**Comment by carinapilar** [comment]
Another one in 5418687-zd-woothemes

**Comment by aleone89** [comment]
Another report of this here: https://wordpress.com/forums/topic/issue-with-people-seeing-content 

- Custom domain
- Site set to private

**Comment by csonnek** [comment]
Another report here: https://wordpress.com/forums/topic/issue-with-people-seeing-content/

**Comment by mzitinfo** [comment]
Another report in 5505589-zen. Switching the privacy settings around solved the issue.

**Comment by daledupreez** [comment]
Just to provide an update to followers of this issue, I've picked up this work and I have been working on it for the last week or two.
Our internal discussions are in pMz3w-fNu-p2, but I want to share where we have got to thus far.

Last week, I explored appending tokens to URLs in the content, which we eventually decided was not going to be secure enough due to the way we were adding the tokens. That was in D86898-code.

The week before that, I was working on an approach that allows us to conditionally serve files from the mapped domain instead of the `*.files.wordpress.com` subdomain, which should allow us to access the user's login cookie for the site. I have now picked that work up again, and will be working to get some security review on that this week: D86397-code

**Comment by zdenys** [comment]
- [ ] 37512324-hc

**Comment by zdenys** [comment]
5628876-zd-woothemes

**Comment by csabarakasz** [comment]
27910255-hc

**Comment by obenland** [comment]
@daledupreez Is D86397-code only a devops-review away from being shippable?

**Comment by louinel** [comment]
5803233-zd-woothemes
5812929-zd-woothemes
5830175-zd-woothemes
6208115-zd-woothemes

**Comment by daledupreez** [comment]
Apologies for missing the ping here, @obenland. We need some more detailed research into possible downstream side-effects of the proposed changes in D86397-code, as we're not clear on what might break given the current approach. The current state and the concerns involved are being tracked in this internal thread: pMz3w-fNu-p2#comment-102184

**Comment by zdenys** [comment]
5829540-zd-woothemes

**Comment by eduardozulian** [comment]
Another report: 5854805-zen

**Comment by zdenys** [comment]
5854805-zd-woothemes Affected: Chrome and Safari on iPad and iPhone. Not affected: MS Edge.

**Comment by zdenys** [comment]
39950214-hc

**Comment by rinazrina** [comment]
Another report: 41475641-hc
The user is using mobile Safari. Disabling the Prevent cross-site tracking option worked.

**Comment by ClassicRKR27** [comment]
Another report here on mobile Safari: 34534146-hc

**Comment by masperber** [comment]
Another report 42710209-hc

I helped them to workaround the issue by disabling the Prevent cross-site tracking setting.

**Comment by cuemarie** [comment]
Another instance here: 6309367-zd-woothemes

Had user switch to "Coming Soon" mode, that resolved it for them.

**Comment by cuemarie** [comment]
Interactions from dupe report: https://github.com/Automattic/wp-calypso/issues/58462

- [ ] 32011615-hc
- [ ] 32951052-hc

**Comment by happychait** [comment]
6329078-zen

**Comment by christianguerrag** [comment]
6338930-zen

**Comment by daledupreez** [comment]
For the record, we're exploring an approach to addressing this issue on three internal sites. We haven't yet worked out how to make the approach work across all private sites yet, or how we can manage the necessary web server configurations, but we'll report back when we have a clearer picture.

**Comment by carinapilar** [comment]
6473305-zen

**Comment by filipanoscampos** [comment]
6767570-zd-a8c

**Comment by cuemarie** [comment]
📌 ACTIONS
- Due to the age of this issue, KitKat has downgraded the priority from `Blocker` to `High` to better reflect it's impact/status in the larger landscape of open bugs.

**Comment by ariel-maidana** [comment]
Another report here: 7109476-zd-a8c
It seems the workaround of switching to Coming Soon and back to Private didn't work this time.

**Comment by Robertght** [comment]
Another case in 7188567-zen

**Comment by filipanoscampos** [comment]
We have a user reporting that, after the most recent updates, the images are displayed even with **Prevent Cross-site tracking** enabled.

**Comment by poeticabdul** [comment]
Another case 7351073-zen

**Comment by zdenys** [comment]
7488532-zd-a8c

**Comment by OmarFPG** [comment]
7518457-zen

**Comment by OmarFPG** [comment]
7640680-zen
Update 1: Coming soon workaround didn't work here...
Update 2: Setting it to Public then back to Private seems to have worked.

**Comment by OmarFPG** [comment]
7689312-zen

**Comment by daledupreez** [comment]
As an update on this issue, we're making some fairly low-level changes that should result in us routing requests via URLs that won't trigger third-party cookie issues. More details are in pMz3w-fNu-p2#comment-115221.

**Comment by masperber** [comment]
7815770-zen

**Comment by Aurorum** [comment]
7875276-zen 

Launching the site worked in resolving the issue

**Comment by Aurorum** [comment]
7898878-zen

**Comment by daledupreez** [comment]
We've started rolling out changes to address the issue. See p58i-gPS-p2 for more details.

**Comment by Robertght** [comment]
I have another report in 7891706-zen, but it looks like things are working for them. Can I get a double check on this perhaps please?

**Comment by dolgelukkig** [comment]
I have a user mentioning this happening on a simple site. They already reported this before on April 3rd. 
8060994-zd

**Comment by jorpdesigns** [comment]
Reported in 8062026-zen (Follow-up Ticket). Please notify user when issue has been resolved.

**Comment by devicenull** [comment]
This has been fully resolved.
