### ISSUE TITLE
Editor: Change 'Post Visibility' label to 'Page Visibility'

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#5313]
Currently when setting the visibility option for a page the label says "post visibility" we should change this to read "page visibility" 

![screenshot_09-05-2016-19 23 08](https://cloud.githubusercontent.com/assets/150348/15133891/12a37e0c-161c-11e6-842a-c08baa6ab8d0.png)
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/[site]/1854
2. Click on visibility icon
3. Notice the label says "post visibility"

**Comment by aduth** [comment]
We should also anticipate how this will display for custom post types. Perhaps we should change the label to something more generic like "Visibility" (and if so, should this apply for all post types, or only CPTs?).

**Comment by brbrr** [comment]
It is not relevant anymore since the design was changed.
