### ISSUE TITLE
Themes: Misaligned button text on theme selection screen.

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#5314]
#### Steps to reproduce
1. Go to Theme selection 
2. **More** button, next to the search box, has misaligned text (the text is 2px higher than the baseline set by the dropdown next to it

#### Browser / OS version

Chrome Version 50.0.2661.94 (64-bit) / Firefox 46.0.1 on OS X 10.11.4 

#### Screenshot / Video

![screen shot 2016-05-10 at 12 27 16](https://cloud.githubusercontent.com/assets/184938/15142442/adf32b50-16ad-11e6-8c14-10ef0bdd753a.png)

**Comment by jeremeylduvall** [comment]
Fixed via #5380
