### ISSUE TITLE
Purchases: unable to add/change PayPal details without renewing

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#5316]
'Edit Payment Method' on an active subscription allows user to switch to a credit card, but has no link for using PayPal:

![screen shot 2016-05-10 at 9 25 10 am](https://cloud.githubusercontent.com/assets/13856531/15148120/ca09ac68-1691-11e6-85d1-3e531fe57a06.png)

On an inactive subscription, 'Add Payment Method' also does not provide a PayPal link:
![screen shot 2016-05-10 at 9 24 22 am](https://cloud.githubusercontent.com/assets/13856531/15148143/edc24a16-1691-11e6-85df-b685d27a2dc8.png)

So the only way to switch PayPal accounts is to either cancel and re-order, or renew manually. Probably not super common, but it came up in 2659476-t

**Comment by fabianapsimoes** [comment]
This has come up before, see pbg9X-8Tk-p2. Unfortunately, there’s no way to create a new PayPal billing agreement without a new payment, so the only way is indeed to submit a renewal.

Closing, but feel free to follow-up if you need more information :)
