### ISSUE TITLE
My Home: Add better indication that a site is in 'Coming Soon' mode

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#53171]
Immediately after onboarding the user lands on My Home with a success message and is prompted to start their site. Would it be possible to add some further clarity about the fact that their site is not yet launched/public?

<img width="1579" alt="Screen Shot 2021-05-26 at 9 43 18 am" src="https://user-images.githubusercontent.com/1842363/119583297-a197df00-be09-11eb-8aac-0c51fd047473.png">

There is currently a small 'Coming Soon' notice in the sidebar - and we reference 'launching' the site - but I feel like there is potential to be clearer:

* Do we introduce the concept of the site being in 'Coming Soon' mode to the 'Your site has been created' card description? This would only help for the *initial* landing in My Home.
* Could we introduce some kind of messaging that is consistently in My Home until the site is launched?
* Maybe the 'Status' area we are otherwise considering could include the Site privacy status (Coming Soon | Private | Public )

**Comment by roo2** [comment]
I personally think that there are cases where this would make sense to be in the _Action Center_ if and when that becomes a thing https://github.com/Automattic/wp-calypso/issues/54443

I think it only makes sense to go there if the user _should have_ launched their site, like maybe if all of the other checklist tasks are complete, or the site is older then a week old?

**Comment by jordesign** [comment]
This issue is resolved in the new My Home design - where there are different states for un/launched sites
pbAok1-2L4-p2
