### ISSUE TITLE
Theme Showcase: Make it clearer how to close the "Thanks for choosing' modal

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#53174]
### Steps to reproduce the behavior

1. Starting at URL: https://wordpress.com/themes/
2. Activate a theme.
3. 'Thanks for choosing' modal appears

#### Issue

Currently two options are displayed as buttons (actions differ depending on the theme) but there is no clear option to jus close the modal and remain on the showcase page

<img width="1010" alt="Screen Shot 2021-05-26 at 11 02 20 am" src="https://user-images.githubusercontent.com/1842363/119587537-3ef71100-be12-11eb-9e59-97c471c55edd.png">

Previously there was *no* way to close the modal - this was changed in #35892 to allow clicking *outside* the modal to clear it. It seems this might still be unclear to some users who may feel trapped with only the 2 options presented in buttons.

Is it possible to add a clearer way to close the modal? A close button, or 'X' or something?

**Comment by kwight** [comment]
Yep, it's strange that this modal doesn't have an `X`.
