### ISSUE TITLE
My Home: Make 'Edit Homepage' more inclusive for users who are starting a blog

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#53172]
During the onboarding checklist we currently prompt users to 'Edit your homepage`. This makes sense if the user is building a 'site' with a traditional homepage - but could be a bit of a roadblock to users who intend on starting a blog.

Really - they want to get started with adding post content...

<img width="1034" alt="Screen Shot 2021-05-26 at 10 20 59 am" src="https://user-images.githubusercontent.com/1842363/119584851-dd807380-be0c-11eb-8fb6-654c424fed36.png">

This may be a bigger question about user intent and checklist items - but as a first step is there a way to make the concept of 'editing content' prior to launch more inclusive? I worry that for someone focused on blogging - there is no need/desire to 'Edit homepage'.

**Comment by jordesign** [comment]
Just noting that if we could somehow know a user was blogging - then writing their first post is a *far* more useful checklist item than 'Update your Homepage'.

**Comment by jordesign** [comment]
Repurposing this a little for the 'Blogger Experience' Pod...

If the user has the front_page set to show 'latest posts' - the checklist item to 'Edit Home Page' makes no sense. Can we detect that setting and prompt them to "Add a Post' instead?

**Comment by jordesign** [comment]
It looks like we'll know the user intent (based on https://github.com/orgs/Automattic/projects/272#card-66764022) so that will be handy for this to be considered once that is possible.

**Comment by autumnfjeld** [comment]
I think current work by Ollie in the Blogger pod is addressing this--e.g. designs on the way to tailor this experience.  Do you think we can close this @jordesign , since this is actively being addressed?

**Comment by jordesign** [comment]
That works for me - closing in favour of Ollie's work.
