### ISSUE TITLE
Crowdsignal: "Create A Poll" button is broken on simple sites

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#53199]
### Steps to reproduce the behavior

1. Go to My Sites > Feedback > Crowdsignal
2. Click on "Create a Poll"
3. See error: "Cannot load polls." https://d.pr/i/tc2nE3

### Context

User report in 4017593-zen

#### Is this specific to the applied theme? Which one?

Happening on all themes

#### Does this happen on simple or atomic sites or both?

Simple

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Impacts all simple sites

#### Reproducibility (Consistent, Intermittent) 

Consistent

**Comment by synora** [comment]
I'm unable to replicate this on my own simple site but the suggested workaround (adding a poll directly in a poll block) was a great one!
