### ISSUE TITLE
My Home (post-launch): visual refresh & style update

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#53213]
### Overview
This is part of [My Home Pod short-term design improvements](pd2qGl-2P-p2#short-term-goals)
Styling updates to My Home **(post-launch view )** to create a more light, airy and modern UI.  Much of this work may come for free from the pre-launch view ticket https://github.com/Automattic/wp-calypso/issues/53212.  

![image](https://user-images.githubusercontent.com/5665959/119782370-75668600-bf0f-11eb-8785-55f26d8a3960.png)

### User facing acceptance criteria
Given that the user has gone through site onboarding
When they land in My Home and have launched their site
Then they see My Home with updated styling per [Figma designs](https://href.li/?https://www.figma.com/file/fLQcNzdadWzo87n89Imecj/?node-id=1763%3A0)
And they will see the proper update on desktop, tablet, and mobile viewports

### Figma Designs
https://href.li/?https://www.figma.com/file/fLQcNzdadWzo87n89Imecj/?node-id=1763%3A0

### Related links
[My Home Project thread]( pd2qGl-17-p2)
[My Home: Short-term design improvements](pd2qGl-4i-p2)

### Dev Notes

**Comment by roo2** [comment]
The only remaining change I can see for post launch is https://github.com/Automattic/wp-calypso/pull/54008
Other changes are covered by https://github.com/Automattic/wp-calypso/pull/53972
