### ISSUE TITLE
Themes: Headstart is not effective for some Atomic site contexts.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#53233]
Mentioned again by @kathrynwp during a demo call:

Headstart is not usable for Atomic sites in some situations, so we'll need to do an audit. Can we do the following when the target is an Atomic site:

* Headstart on theme switch
* Headstart on signup (eg. a Business plan is purchased during signup? although think the user would still start on a Headstarted Simple site until a plugin or theme was uploaded)
* Headstart RC tool used by HEs

Also, the ability to use Headstart on Atomic sites will become more important with various plan and plugin projects on the near horizon. 🤔

**Comment by zdenys** [comment]
This is needed. Also, on Atomic site users cannot choose to replace the homepage with the demo content (aka Homepage Updating) like it happens on Simple sites. Encountered the limitation in this chat 30099309-hc.

I haven't had a chance to test things out further yet, but I think it could be somehow related to https://github.com/Automattic/wp-calypso/issues/43877. As of now, on Atomic, we don't show the confirmation dialogue asking if the users whether they want to replace the homepage with demo or keep it as it is. 

On Simple sites we do show it:

![image](https://user-images.githubusercontent.com/39308239/121767710-b0e58f00-cb62-11eb-9361-62b06654d962.png)

**Comment by happychait** [comment]
Just had a customer annoyed about not being able to headstart Atomic site, in 30825087-hc

**Comment by zdenys** [comment]
31228642-hc We had to manually export demo from a theme demo and import it into their AT site. Not very efficient.

**Comment by roo2** [comment]
It looks like there's a fair amount of effort needed to get headstart working on atomic sites. I posted in a P2 to discuss further pbxlJb-WW-p2

**Comment by nagpai** [comment]
Quite a few users have a confusion once they install one of our new premium themes. Byrne for instance. Users are confused how to get the contents of the theme on their site. 

#34277826-hc

**Comment by jamiepalatnik** [comment]
Another user report: 5252013-zd-woothemes

They expected to be able to restore the demo content of a specific theme so they could edit it further.

**Comment by nagpai** [comment]
User frustrated about getting blank pages on premium themes on business plan whenever they switch 
35679037-hc

**Comment by i11za** [comment]
Another headstart request here: 35733939-hc
Theme: Archeo (or a similar alternative)

**Comment by nagpai** [comment]
35742813-hc

**Comment by andres-blanco** [comment]
I am working on the theme switch part of this issue: https://github.com/Automattic/wp-calypso/issues/56869

**Comment by nagpai** [comment]
5319688-zen

**Comment by davipontesblog** [comment]
With https://github.com/Automattic/wp-calypso/issues/56869 merged, I am closing this issue. If we would like to explore further improvements to the atomic infrastructure when it comes to applying headstart annotations to sites on theme switch it's best a new issue is created with a more narrowly defined scope or goal.
