### ISSUE TITLE
My Home: "Update your homepage" link should go to the site editor for Site Editor blogs

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#53236]
Clicking the "Update your homepage" link in the checklist should take you to the _site editor_ for _block based_ sites. Currently it takes you to the _page editor_.

Originally raised here https://github.com/Automattic/wp-calypso/issues/50484#issuecomment-844023956
<img width="834" alt="Screen Shot 2021-05-28 at 10 13 28 AM" src="https://user-images.githubusercontent.com/22446385/119903825-65958300-bf9d-11eb-9c8e-875c099b1aa4.png">

### Testing instructions

Create a site with the site-editor flag enabled https://wordpress.com/new?flags=gutenboarding/site-editor
You will be dropped into the site editor.
Without saving, navigate to the my home page 
Expand the "update your homepage" task and click the link

You should be taken to  https://wordpress.com/site-editor/YOURSITE.wordpress.com
but you will be taken to the wp-admin page editor https://YOURSITE.wordpress.com/wp-admin/post.php?post=2

**Comment by autumnfjeld** [comment]
Related discussion in pd2qGl-7u-p2

**Comment by deBhal** [comment]
The checklist is using the function `getEditorUrl()` ([here](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/selectors/get-editor-url.js)) , via `getFrontPageEditorUrl()` in [client/state/selectors/get-checklist-task-urls.js](https://github.com/Automattic/wp-calypso/blob/c9dfd6ad21f9267f97077fb54652b63ab6a757d8/client/state/selectors/get-checklist-task-urls.js#L49).

Those utility functions will clearly need to be updated to be FSE aware as part of the FSE project, and there's no checklist specific changes required, so I'm going to go ahead and mark this as closed.
