### ISSUE TITLE
Live chat information bubble contains error

### ISSUE THREAD

**Issue by taggon** [Automattic/wp-calypso#53238]
Originally reported on p8HJWS-Jg-p2

> Howdy everyone!
> 
> I was in the process of registering a new Premium plan and digging through the available information on the upgrade page, found under “Upgrades -> Plans”, I discovered that the information bubble for both the Business and eCommerce plans contain an error: they mention live chat support available Monday through Friday …with the yearly subscription selected. 😳

![붙여넣은_이미지_2021__5__28__오전_11_35](https://user-images.githubusercontent.com/212034/119921473-063d7000-bfa9-11eb-8a68-00ed2fd2ea48.jpg)

**Comment by Aurorum** [comment]
Duplicate of #53215 - both issues should be fixed by that PR!
