### ISSUE TITLE
Settings / Site Address: Cannot change free site address

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#53258]
@katiebethbrown reported a live chat user encountered issues changing their `.wordpress.com` site address and minified react errors present. ( p1622222175215100-slack-C03TY6J1A )

After, multiple HEs were able to reproduce and consistently see `Minified React Error #31` in the console and `We're sorry, but an unexpected error has occurred.`

@katiebethbrown reports seeing the minified errors across different areas of Calypso but I cannot reproduce at this time. 

https://user-images.githubusercontent.com/4887830/120023531-ecf1ef00-bfbb-11eb-9802-c480cdf991b2.mp4

### Steps to reproduce the behavior

1. Go to a WordPress.com Simple site
2. Click on My Site > Upgrades > Domains and select the free site address.
3. Click on `Change site address`
4. If looped back, click on `Change site address` again.

#### What I expected to happen

Proceed to change site address.

#### What actually happened

Errors.

### Context

Slack, live chat/user report.

#### Does this happen on simple or atomic sites or both?
Simple

#### Is there any console output or error text?

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BaRecordsRequiredForMapping%2C%20autoRenewalDate%2C%20adminEmail%2C%20autoRenewing%2C%20blogId%2C%20bundledPlanSubscriptionId%2C%20canSetAsPrimary%2C%20contactInfoDisclosureAvailable%2C%20contactInfoDisclosed%2C%20currentUserCanAddEmail%2C%20currentUserCanManage%2C%20currentUserCannotAddEmailReason%2C%20domain%2C%20domainLockingAvailable%2C%20domainRegistrationAgreementUrl%2C%20emailForwardsCount%2C%20expired%2C%20expiry%2C%20expirySoon%2C%20gdprConsentStatus%2C%20googleAppsSubscription%2C%20titanMailSubscription%2C%20hasRegistration%2C%20hasWpcomNameservers%2C%20hasZone%2C%20isLocked%2C%20isRenewable%2C%20isRedeemable%2C%20isEligibleForInboundTransfer%2C%20isAutoRenewing%2C%20isPendingIcannVerification%2C%20isPremium%2C%20isPrimary%2C%20isPendingWhoisUpdate%2C%20isSubdomain%2C%20isWPCOMDomain%2C%20isWpcomStagingDomain%2C%20manualTransferRequired%2C%20mustRemovePrivacyBeforeContactUpdate%2C%20newRegistration%2C%20name%2C%20owner%2C%20partnerDomain%2C%20pendingRegistration%2C%20pendingRegistrationTime%2C%20pendingTransfer%2C%20pointsToWpcom%2C%20privateDomain%2C%20privacyAvailable%2C%20registrar%2C%20registrationDate%2C%20renewableUntil%2C%20redeemableUntil%2C%20sslStatus%2C%20subdomainPart%2C%20subscriptionId%2C%20supportsDomainConnect%2C%20supportsGdprConsentManagement%2C%20supportsTransferApproval%2C%20tldMaintenanceEndTime%2C%20transferAwayEligibleAt%2C%20transferLockOnWhoisUpdateOptional%2C%20type%2C%20transferStatus%2C%20transferStartDate%2C%20transferEndDate%2C%20whoisUpdateUnmodifiableFields%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ts (74319.f236d09e491927a3afc6.min.js:2)
    at 74319.f236d09e491927a3afc6.min.js:2
    at Li (74319.f236d09e491927a3afc6.min.js:2)
    at wa (74319.f236d09e491927a3afc6.min.js:2)
    at yl (74319.f236d09e491927a3afc6.min.js:2)
    at ml (74319.f236d09e491927a3afc6.min.js:2)
    at al (74319.f236d09e491927a3afc6.min.js:2)
    at 74319.f236d09e491927a3afc6.min.js:2
    at t.unstable_runWithPriority (74319.f236d09e491927a3afc6.min.js:2)
    at Ho (74319.f236d09e491927a3afc6.min.js:2)
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

All WordPress.com Simple sites wanting to change their free site address.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

See above.

**Comment by katiebethbrown** [comment]
User report in 9409813-hc

They are looking to change their wpcom subdomain, but are getting errors.

**Comment by JoshuaGoode** [comment]
Screenshot from @katiebethbrown seeing a variation of the error just visiting the domains page.

![image](https://user-images.githubusercontent.com/4887830/120023948-7b667080-bfbc-11eb-9a40-930065241b89.png)

**Comment by JoshuaGoode** [comment]
> Objects are not valid as a React child (found: object with keys {aRecordsRequiredForMapping, autoRenewalDate, adminEmail, autoRenewing, blogId, bundledPlanSubscriptionId, canSetAsPrimary, contactInfoDisclosureAvailable, contactInfoDisclosed, currentUserCanAddEmail, currentUserCanManage, currentUserCannotAddEmailReason, domain, domainLockingAvailable, domainRegistrationAgreementUrl, emailForwardsCount, expired, expiry, expirySoon, gdprConsentStatus, googleAppsSubscription, titanMailSubscription, hasRegistration, hasWpcomNameservers, hasZone, isLocked, isRenewable, isRedeemable, isEligibleForInboundTransfer, isAutoRenewing, isPendingIcannVerification, isPremium, isPrimary, isPendingWhoisUpdate, isSubdomain, isWPCOMDomain, isWpcomStagingDomain, manualTransferRequired, mustRemovePrivacyBeforeContactUpdate, newRegistration, name, owner, partnerDomain, pendingRegistration, pendingRegistrationTime, pendingTransfer, pointsToWpcom, privateDomain, privacyAvailable, registrar, registrationDate, renewableUntil, redeemableUntil, sslStatus, subdomainPart, subscriptionId, supportsDomainConnect, supportsGdprConsentManagement, supportsTransferApproval, tldMaintenanceEndTime, transferAwayEligibleAt, transferLockOnWhoisUpdateOptional, type, transferStatus, transferStartDate, transferEndDate, whoisUpdateUnmodifiableFields}). If you meant to render a collection of children, use an array instead.

**Comment by samiff** [comment]
@katiebethbrown @JoshuaGoode Thanks for catching this one. https://github.com/Automattic/wp-calypso/pull/53259 just landed in produciton and should fix the issue. Could you please follow up with any users that were having trouble changing their site addresses, thanks ❤️
