### ISSUE TITLE
Set featured image: different behavior on Atomic and Simple sites

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#53267]
**What**
The experience of setting a featured image on Atomic (WoA) and on Simple site differs. 

On Simple site we only have one panel named `Set featured image` that when clicked opens the menu to pick the image from Media, Google Photos or Pexels. All good and clear.

https://user-images.githubusercontent.com/39308239/120073867-da061a00-c0a2-11eb-9268-d148f8e276db.mov

On Atomic site we have the same panel named `Set featured image` that when clicked opens the Media library modal. And only if one clicks the `Select image` button below `Set featured image` one can see the same menu to pick the image from Media, Google Photos or Pexels.

https://user-images.githubusercontent.com/39308239/120073991-500a8100-c0a3-11eb-909a-c5f513f2a29a.mov

**Why**
The behavior between Simple and Atomic sites is different. this may be confusing for users who upgrade from Simple to Atomic.

**Additional context**
Noticed during a Quick Start session 4028149-zd-woothemes

**Comment by cpapazoglou** [comment]
~~@retrofox, do you remember if there was a technical reason for not being able to have the same UX in Calypso block editor and WP Admin block editor?~~

**Comment by cpapazoglou** [comment]
It seems that https://github.com/Automattic/jetpack/pull/19778 will resolve that inconsistency when Jetpack 9.8 is released on 2021-06-01. It is possible that the inconsistency was introduced cause the code of the above PR was deployed in WPCOM prior the Jetpack release.

@zdenys, can you also check it for yourself by installing the Jetpack Beta plugin https://jetpack.com/download-jetpack-beta/ and loading the Release Candidate?

**Comment by zdenys** [comment]
>@zdenys, can you also check it for yourself by installing the Jetpack Beta plugin https://jetpack.com/download-jetpack-beta/ and loading the Release Candidate?

Tested it on Jurassic Ninja with Jetpack Beta. I can see the right behavior now, exactly as on a Simple Site 🎆  🥳  🤝  Thank you!
