### ISSUE TITLE
Custom Fonts: Add additional fonts

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#53287]
Stubbing out an issue to add additional fonts to the Custom Fonts and Global Styles lists on Dotcom.

P2 ref: p9Jlb4-2yR-p2
cc @kjellr

**Comment by kjellr** [comment]
For quick reference: Here are the three new font additions, and three new pairings. 

## New Fonts 

Inter|DM Sans|Bodoni Moda
---|---|---
<img width="215" alt="gliphs-1-1" src="https://user-images.githubusercontent.com/1202812/120637276-b2b1a300-c43c-11eb-9919-3168b54bd788.png">|<img width="215" alt="gliphs-6" src="https://user-images.githubusercontent.com/1202812/120637278-b2b1a300-c43c-11eb-859f-20202fdf10ea.png">|<img width="215" alt="gliphs-2-1" src="https://user-images.githubusercontent.com/1202812/120637279-b2b1a300-c43c-11eb-90d0-1dcc97f6d2e2.png">
[Inter on Google Fonts →](https://fonts.google.com/specimen/Inter?query=inter)|[DM Sans on Google Fonts →](https://fonts.google.com/specimen/DM+Sans?query=dm+sans)|[Bodoni Moda on Google Fonts →](https://fonts.google.com/specimen/Bodoni+Moda?query=Bodoni+Moda)

## New Font Pairings

**Bodoni Moda & Overpass**

<img width="2618" alt="pairings-6-1" src="https://user-images.githubusercontent.com/1202812/120637877-703c9600-c43d-11eb-970c-f99afda239e4.png">


**Inter & Source Serif Pro**

<img width="2618" alt="pairings-8-1" src="https://user-images.githubusercontent.com/1202812/120637889-73378680-c43d-11eb-8030-bb05ca1bb38d.png">

**Comment by kwight** [comment]
Completed in https://github.com/Automattic/wp-calypso/pull/53417
