### ISSUE TITLE
My Home: WordPress App Card on mobile browser

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#53295]
This card contains links to app stores and getting a download link to install mobile apps.

This card was reported as missing on mobile browser: pd2qGl-4i-p2#comment-154 , while it is shown on desktop and tablet view.

I investigated and it looks like there are different ways of displaying this card depending on viewport size.  Unfortunately didn't see comments in code explaining the biz logic motivation.

Task: note/document what the behavior is per viewport and then check in with Jeff or WordPress App people

**Comment by p-jackson** [comment]
Here's the big "go mobile" card that can appear at the top of My Home
<img width="583" alt="Screenshot 2021-06-01 at 4 09 06 PM" src="https://user-images.githubusercontent.com/1500769/120265273-c271a000-c2f3-11eb-9c72-146fc5881181.png">

And here's the smaller "go mobile" card that can appear at the bottom right of My Home
![preview-118771339-c8b05700-b8c5-11eb-900c-eb290a9582b4](https://user-images.githubusercontent.com/1500769/120265310-d87f6080-c2f3-11eb-9a61-b9bfd9b83ee0.png)

Here's my proposal for how the app cards should appear:
- We don't show either card if the user has logged in to a mobile app (which we detect by the user having an oauth connection with the a mobile app)
- The big "go mobile" card will randomly be selected to appear at the top of the screen (which we do for various post-launch cards pd2qGl-2J-p2). It should do this on mobile and desktop devices (it currently only does this on mobile).
- If the big "go mobile" card is shown at the top, then we don't show the small one at the bottom right.
- If the big card _isn't_ shown at the top, the small card will appear at the bottom right, regardless of what device the user is using.

My intention with these rules is, if the user isn't an app user, there will always be a nudge to install on My Home. And periodically that nudge will be promoted to the top of the screen.

Does that seem reasonable @jeffgolenski @yaelirub ? If so then I'll make sure it's working this way, testing that it works on all the various screen sizes.

**Comment by yaelirub** [comment]
>which we detect by the user having an oauth connection with the a mobile app

When you say "having" do you mean at the time they view my home page?

>We don't show either card if the user has logged in to a mobile app (which we detect by the user having an oauth connection with the a mobile app)

Honestly I want to share that if it was up to me, I wouldn't have gone into so much trouble creating a logic conditioning the display of the bottom card at all.  I would just always display it. I'm trying to think of the problem this conditioning is trying to solve and I can't come up with anything that will justify the work. Its not clearing up significant space in the browser and on mobile, the card appears at the bottom, passed the cut point anyways, but Im probably missing something.

On a different note, looks like the designs for the top card you attached here are missing the App Store button?

**Comment by p-jackson** [comment]
> On a different note, looks like the designs for the top card you attached here are missing the App Store button?

Thanks for noticing that! This large card currently only shows on mobile so only needs to show one of the stores. If I make it appear on desktop too then it'll need to show both store buttons.

> > which we detect by the user having an oauth connection with the a mobile app
>
> When you say "having" do you mean at the time they view my home page?

It means they have a "connection" as listed in the `/me/security/connected-applications` page

![Screen Shot on 2021-06-02 at 10:10:44](https://user-images.githubusercontent.com/1500769/120396594-ee8c3000-c38a-11eb-95e4-3536ae53523e.png)

> I'm trying to think of the problem this conditioning is trying to solve and I can't come up with anything that will justify the work.

Fair point to ask about the rationale. @jeffgolenski should have a better explanation of the design rationale. From my point of view there are a lot of features and a lot of teams that would love to be promoted on My Home. Removing app promos when they're not needed frees up space (not just screen space, but mental space) to promote something else.

**Comment by yaelirub** [comment]
>It means they have a "connection" as listed in the /me/security/connected-applications page

Do you know if it will return connected even if the app was deleted? From the list of my apps and the little test I just did , it seems like it still shows even if I delete the app.

**Comment by p-jackson** [comment]
> From the list of my apps and the little test I just did , it seems like it still shows even if I delete the app.

Yes that makes sense thinking about how oauth works. When I tested logging out of the app it removed the connection, but I guess deleting the app doesn't give us any opportunity to clean up the oauth connection.

**Comment by yaelirub** [comment]
We would definitely want to show the prompt to people that deleted the app 😬

**Comment by p-jackson** [comment]
If the user tries out the app, decides it's not for them, and deletes it; that feels very much like "dismissing" the card to me. Which is something we allow the user to do.

![Screen Shot on 2021-06-02 at 10:47:53](https://user-images.githubusercontent.com/1500769/120399392-03b78d80-c390-11eb-88b1-8f5919ec7a0a.png)

The "Hide this" button allows the user to remove the app promotion forever. So I think it's reasonable that there would come a time for a user when we stop promoting the app. An earlier proposal for the logic we'd use to hide the card that depended on tracks data (https://github.com/Automattic/wp-calypso/issues/39146#issuecomment-579926644) would have had similar behaviour.

**Comment by jeffgolenski** [comment]
Thanks for diving in @p-jackson 

> We don't show either card if the user has logged in to a mobile app (which we detect by the user having an oauth connection with the a mobile app)

Ace. Well done.

> The big "go mobile" card will randomly be selected to appear at the top of the screen (which we do for various post-launch cards pd2qGl-2J-p2). It should do this on mobile and desktop devices (it currently only does this on mobile).

> If the big "go mobile" card is shown at the top, then we don't show the small one at the bottom right.

> If the big card isn't shown at the top, the small card will appear at the bottom right, regardless of what device the user is using.

I'm wondering if we could narrow this down a bit.

How about:

1) Large screens: We randomly show the large CTA in the primary CTA area. When that happens, like you said, the smaller card won't appear.
2) Mobile (tablet and phone): If we see the customer is viewing My Home in the browser on a mobile device, we only show the large version in the primary CTA at all times and the smaller card won't display. It already sits waaaaaaay down on the screen of my home on small screens and @yaelirub and myself had a p2 convo about bumping that small CTA up above the fold anyway. 

> Thanks for noticing that! This large card currently only shows on mobile so only needs to show one of the stores. If I make it appear on desktop too then it'll need to show both store buttons.

Just for clarity, if a customer is viewing My Home in the browser on a mobile device, we're able to see which device they're on and only show a specific app store button?

> Honestly I want to share that if it was up to me, I wouldn't have gone into so much trouble creating a logic conditioning the display of the bottom card at all. I would just always display it. 

@yaelirub, @p-jackson said it best. It's valuable real estate and a lot of teams / features are fighting for the attention of the customer in a free-for-all fashion. It's too much for the customers. We need to create a proper system with a slow release of information as not to burden the customer. 

Imagine My Home for a customer who already has Yoast, uses the mobile apps, has already signed up for WP courses, etc. Yet we continue to display those CTAs all over My Home. It becomes a useless place for them and they stop looking for new helpful information. If we change the logic based on the customer, we create a place of recurring value for them. Win!

**Comment by jeffgolenski** [comment]
> The "Hide this" button allows the user to remove the app promotion forever. So I think it's reasonable that there would come a time for a user when we stop promoting the app. An earlier proposal for the logic we'd use to hide the card that depended on tracks data (#39146 (comment)) would have had similar behaviour.

Just a note for this action. I'm currently exploring new ways for this to work, so this experience will be enhanced soon

**Comment by yaelirub** [comment]
>If we change the logic based on the customer, we create a place of recurring value for them. Win!

I totally get that. I just worry that the conditioning will not work as expected. I think that someone could have had a connection to the app because they tried it ages ago. Just having an oauth connection doesn't mean they're an active app user. We have improved our app tremendously in the last couple of years so I'd prefer to just display it unless the user has specifically chosen to dismiss the mobile promo card. At least on Mobile and tablets (if they are at My Home on phone or tablet, they need the app)
The rest of the logic about when to display the bigger version is not that big a deal for us.

**Comment by jeffgolenski** [comment]
@yaelirub Absolutely. I can get behind that reasoning! Maybe it boils down to simply allowing customers to dismiss either card depending on which one is displaying. Rather than make assumptions we can just ask for their input.

> I think that someone could have had a connection to the app because they tried it ages ago. Just having an oauth connection doesn't mean they're an active app user. We have improved our app tremendously in the last couple of years

This opens up a new door in my brain. I think I'm going too far down the rabbit hole, but imagine if we could see that they once had used the app, but no longer do. We could tailor the content in the app card to try and get them to give it another shot, or quickly provide feedback on why they don't want to use it. :-P

Again, that's probably too much. I appreciate the conversation!

**Comment by p-jackson** [comment]
> Just for clarity, if a customer is viewing My Home in the browser on a mobile device, we're able to see which device they're on and only show a specific app store button?

Yep that's right, on iOS or Android we can just show the store button that's specific to them.

**Comment by yaelirub** [comment]
@jeffgolenski , we really believe that the apps can serve and benefit Dotcom users especially with all the improvements we made and are constantly making but we also know that a large portion of them don’t even know we have an app or have used it a long time ago.
I truly appreciate the conversation as well. Thank you so much for listening and being creative with solutions 🙏

**Comment by autumnfjeld** [comment]
I think there are a number of themes that have been exposed here, bigger than the original purpose of this ticket.  So success on a good discussion!! 😄 

* I'm not sure we need to intertwine the logic of the two cards. So for now let's treat them as separate entities, as they currently are, not intertwining their visibility.  Or similarly they could each have their own dismiss mechanism--separate from each other. (But not sure I would advocate for that, Jeff can ponder that from a design perspective)
* @yaelirub  has pointed out a valid point about active/inactive app users.   It would be great if we could differentiate between 1) doesn't have the app 2) has the app & is active user 3) has the app but is inactive user  - if this is worthwhile to pursue we should create another ticket for this. (@p-jackson has some preliminary ideas, we would just need to assess effort vs impact)
* Having the small bottom card always there, forever, doesn't seem reasonable.  As @jeffgolenski & @p-jackson pointed out there are many things we want to communicate & help the user with, that real estate is valuable.  So we'll think on this, and maybe pursue the point above as possible solution.

My original motivation for this ticket was about the small App card at the bottom of My Home--to address the card missing on mobile browser as reported here by Yael: pd2qGl-4i-p2#comment-154.   Unfortunately I didn't make that clear enough in the ticket description.  We'll get the card showing on mobile devices, consistent with tablets.

**Comment by jeffgolenski** [comment]
Solid breakdown @autumnfjeld. Sorry—my mind moves at a hundred kilometers a minute. Thanks for wrangling us back in! 

As you mention, let's fix up the missing small card on mobile devices for now. I'll continue to think on the larger relationship. I think with the concepts I'm working on for better navigation of the primary CTA cards, will alleviate @p-jackson from pulling his hair out writing logic for all this stuff. I'll have some concepts to share at our next sync and we can finalize a decision then if that seems agreeable!

**Comment by p-jackson** [comment]
> I think with the concepts I'm working on for better navigation of the primary CTA cards, will alleviate @p-jackson from pulling his hair out writing logic for all this stuff.

Yes please 😅 

Here's a teeny tiny diff that just the smaller "go mobile" card appears on all devices, including mobile D62243-code

**Comment by autumnfjeld** [comment]
Root issue addressed via https://href.li/?D62243-code .  Closing this.
