### ISSUE TITLE
Sidebar: Upgrades lags on showing correct plan for AT sites

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/wp-calypso#53294]
No steps to reproduce, this has just happened three times in support in the last couple of weeks. 

In all cases: 

- Business plan recently purchased
- Sidebar displays Free instead
- Resolves on its own eventually, which seems like some kind of caching. 

The plan appears correct on the Plans page, but the sidebar still says Free. at_options in CLI shows the correct plan slug, and everything else seems correct.

#### Does this happen on simple or atomic sites or both?

Looks like it's Atomic.

#### Is there any console output or error text?

Nope!

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Impact limited to confusion after upgrading.

#### Reproducibility (Consistent, Intermittent) 

This doesn't seem to happen every time ⁠— at a guess, because the site I worked on today was AT, expired, then repurchased the plan, another site cancelled Biz then reupgraded, and the third site was switching between eCom and Biz, it only happens on sites that have already been Atomic. 

#### Cases 

- p1622506254226700-slack-C03TY6J1A
- p1622216314170800-slack-C03TY6J1A
- p9F6qB-6Vd-p2

**Comment by cpapazoglou** [comment]
The plan shown in the sidebar depends on the data synced to the Atomic site
https://github.com/Automattic/jetpack/blob/e754e80326402bce81f3e8aee8e6a58940dd0b9f/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L251

It seems that data are updated only on `jetpack_heartbeat` 
https://github.com/Automattic/jetpack/blob/529d07f441bb4667acd773918563296878e19cb4/projects/plugins/jetpack/class.jetpack.php#L760

We should trigger this `refresh_from_wpcom` function on every plan change.

**Comment by annbingle** [comment]
Same issue report here 4038326-zen

**Comment by annbingle** [comment]
Same issue reported here 27150926-hc but I was able to fix it with Site Restoration.

**Comment by BogdanUngureanu** [comment]
This issue will be handled in wpcomsh, there's a pending for for it. However, after doing several tests, I've noticed that the VideoPress module still remains disabled and cannot be re-enabled in the settings interface by users.  A separate issue has been created for [this issue](https://github.com/Automattic/wp-calypso/issues/54287).

**Comment by JoshuaGoode** [comment]
This is generally due to the `jetpack_active_plan` option not being properly set and should sync/fix itself but it's best to fix it for a user ASAP.

Internal notes: P9HQHe-14R-p2

**Workaround:** A quick way to get the proper `jetpack_active_plan` option is to navigate to My Site > Jetpack > Dashboard.  That will get the option updated.

**Comment by BogdanUngureanu** [comment]
A fix for this has been deployed in r239502-wpcom. The Limited Atomic pod might continue the work with a front-end improvement [here](https://github.com/Automattic/wp-calypso/issues/59834).
