### ISSUE TITLE
Jetpack Connect: Add schema for persisting authorize state

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#5330]
Per [this comment](https://github.com/Automattic/wp-calypso/pull/5319#discussion_r62749742), @gwwar  suggested that we add a schema to avoid client errors when the data structure changes. Copying her comment here:

> If you'd like to persist this state, I'd highly recommend adding a schema to avoid client errors in the future when this data structure changes. See: https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#solution-schema-validation

**Comment by gwwar** [comment]
;) probably makes a case for #4805 to land soon

**Comment by johnHackworth** [comment]
This is going to be fixed as soon as https://github.com/Automattic/wp-calypso/pull/5786 is merged

**Comment by johnHackworth** [comment]
This is still pending because the fix was reverted because it was breaking SSO, isn't it, @roccotripaldi  ?

**Comment by roccotripaldi** [comment]
@johnHackworth , we have a schema, but we do not persist the state anymore because it was breaking JPC when a user created a new wpcom account. This issue still stands. We'll need to carefully bring persistence back.
