### ISSUE TITLE
Theme Showcase: Add tracking to demo preview links from theme sheets

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#53312]
<img width="1660" alt="Screen Shot 2021-06-01 at 1 28 01 PM" src="https://user-images.githubusercontent.com/2124984/120366328-859aae80-c2dd-11eb-89af-21c89f8f2cb1.png">

We don't record Tracks events when someone clicks on the "Open live demo" or screenshot (circled areas on the above screenshot) to preview a site's demo from the Showcase. We probably should for clarity in the event we decide to work on the Theme Showcase in the future.

**Comment by Aurorum** [comment]
PR for this issue in #53330. :)
