### ISSUE TITLE
Jetpack Form can have issues in mobile app browsers

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#53326]
### Steps to reproduce the behavior

1. Send this link to yourself through a mobile app: https://itspremiumsandbox42.blog/2021/06/02/mobile-contact-form-test/ 
2. Fill out the form
3. Submit the form
4. See error `the link you followed has expired` or the form redirects to a blank version of itself
5. Check the website 'Feedback' and see the form submission is not there

#### What I expected to happen

The form to submit correctly on the first time and be available in `Feedback`
Compare to using a mobile browser directly to fill out the contact form

#### What actually happened

I tested in three apps: 
Gmail: When I opened the link and submitted the form, everything worked as expected

Slack: I received the error `the link you followed has expired` and the form submission was not in `Feedback`

**WordPress App**: When I clicked on `submit` the form redirected to a mobile browser (out of the app) and refreshed itself. My previous form-field answers were erased but also not submitted. If I re-submitted the form in the browser, I get a confirmation message and the submission was available in `Feedback`

### Context

Brought to my attention by a user in #26297360-HC

#### Browser / OS version

Samsung Note 9 | Android 10

Slack Mobile: 21.05.20
Gmail: 2021.05.02
WordPress: 17.3.2

Chrome: 90.0.4430

#### Is this specific to the applied theme? Which one? 

Nope

#### Does this happen on simple or atomic sites or both?

Simple, haven't tested Atomic

#### Is there any console output or error text?

NA

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects more than one site. Doesn't block WP.com purchases but can affect sales leads for our customers

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Error message from Slack Browser: 

https://d.pr/i/Blvqds

The correct confirmation after submitting a second time on WordPress app: 

https://d.pr/i/lX4OGX

**Comment by synora** [comment]
@JessBoctor I just finished testing the form and it's working as expected via Gmail, Slack, and the WordPress App (iPhone).
