### ISSUE TITLE
FSE: Add common actions like delete and revisions to template parts 

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#53320]
### Steps to reproduce the behavior

1. Go to Site Editor https://horizon.wordpress.com/site-editor/
2. Click on W > Theme > Template Parts > Headers > Template (ex. `header`)
3. With the sidebar open (gear cog) not that common actions for posts/pages are not available, including the ability to delete a template or to access revisions.

#### What I expected to happen

To be able to access common functions like deleting a template or restoring a revision like on pages:

![Screen Shot 2021-06-01 at 2 14 24 PM](https://user-images.githubusercontent.com/1900444/120371637-16748880-c2e4-11eb-9f0a-ad07e14edfb2.png)

#### What actually happened

None of these functions can be accessed:

![Screen Shot 2021-06-01 at 2 08 28 PM](https://user-images.githubusercontent.com/1900444/120371672-22f8e100-c2e4-11eb-9e5c-2f071e45669d.png)

### Context

p58i-aCg-p2

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

High. I anticipate users wanting the ability to manage their template parts as well as restore previous versions if they make a mistage.

**Comment by jeyip** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/55372. The requests seem similar enough.

I'll leave a note in the other Github issue about how there have been multiple requests for the ability to manage template parts from within the site editor.
