### ISSUE TITLE
Full Site Editing: Template Part Area Terms aren't migrated during a lossless revert

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#53347]
### Description

Lossless reverts don't seem to correctly carry the `wp_template_part_area` tax term back to the simple site. This happens regardless of whether or not the template part existed before the AT.

### Steps to reproduce the behavior

1. Create a template part of type general on the template.
2. Upgrade and initiate the Atomic Transfer.
3. Update that template part's area from "general" to "header", also update some of its block content, and save.
4. Go through the revert and lossless import.
5. Notice that while the content changes persisted, the area term is back to general

OR

1. Get the site on Atomic.
2. Create a new template part of with the area as. "header".
3. Go through the revert/lossless import process.
4. Notice the template part's area is "general".

**Comment by Addison-Stavlo** [comment]
This seems expected behavior for the revert process. We can close this, especially since there have been no HE / user interactions posted about here.
