### ISSUE TITLE
"Contact Us" support page doesn't load with an ad-blocker enabled

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/wp-calypso#5338]
I've Managed to reproduce it in Chrome 50 for Mac, with uBlock Origin 1.7.2.

Steps to reproduce:
Try to open the "Contact Us" support page: https://wordpress.com/help/contact

Observed behaviour: The form doesn't load. If I disable uBlock and reload the page, the form works as expected.

I don't know if it happens with other ad-blockers or browsers. It happened at least to other user with Chrome 50 for Mac, so it's not some weird configuration on my end.

**Comment by gwwar** [comment]
https://stats.wp.com/w.js is being blocked

**Comment by gwwar** [comment]
<img width="1046" alt="olark" src="https://cloud.githubusercontent.com/assets/1270189/15200244/e2209c54-1799-11e6-87f1-54711c2519c9.png">
