### ISSUE TITLE
Editor: Custom Color missing in block settings

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#53397]
### Steps to reproduce the behavior

1. Edit post or page
2. Add or edit any block that uses Color in block settings (paragraph, heading, table, columns, group, list, verse, button etc)
3. Open Color section in Block settings sidebar
4. Only the 4-5 colored circles are present, Custom Color link is missing

#### What I expected to happen

To be able to choose a custom color

![image](https://user-images.githubusercontent.com/2031017/120728274-e4e80100-c51f-11eb-8287-07c077363e7b.png)

#### What actually happened

Can't choose custom color

![image](https://user-images.githubusercontent.com/2031017/120728173-af431800-c51f-11eb-8bb0-6ce08bce5208.png)

### Context

This seems to be after the update to Gutenberg 10.7.1
Setting is present in Gutenberg 10.5.4

#### Browser / OS version

n/a

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Currently only simple sites as atomic has not updated Gutenberg yet.

#### Is there any console output or error text?

May not be replated, but warning in Console:
`wp.data.select( 'core/editor' ).getSelectedBlock` is deprecated since version 5.3. Please use `wp.data.select( 'core/block-editor' ).getSelectedBlock` instead.`

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

All simple sites

**Comment by kaitohm** [comment]
Another report: 28982151-hc
Will need a follow-up once resolved: 4042010-zd-woothemes

**Comment by chrisfromthelc** [comment]
I've run into a similar issue with the custom font size missing.

Previously:

<img width="345" alt="Screenshot on 2021-06-03 at 17-42-45" src="https://user-images.githubusercontent.com/8002138/120729111-31392f80-c493-11eb-8dd4-7f1dc90a0fa9.png">

Currently:
<img width="155" alt="Screenshot on 2021-06-03 at 17-41-26" src="https://user-images.githubusercontent.com/8002138/120729130-38603d80-c493-11eb-8fd7-ae73bb8b06d2.png">

There is a LOT of info being dumped into the console.
<img width="1762" alt="Screenshot on 2021-06-03 at 17-47-00" src="https://user-images.githubusercontent.com/8002138/120729367-d6540800-c493-11eb-9087-35424ac0a601.png">

I was able to suss out the line of code dumping all this to the console:

`p.validationIssues && p.validationIssues.length > 0 && (p.isValid ? console.info("Block successfully updated for `%s` (%o).\n\nNew content generated by `save` function:\n\n%s\n\nContent retrieved from post body:\n\n%s", u.name, u, Lt(u, p.attributes), p.originalContent) : p.validationIssues.forEach(({log: e, args: t})=>e(...t))),`


I have a followup in 4042008-zd-woothemes for this particular user.

**Comment by kristarella** [comment]
+1 user report 28834643-hc
followup 4042087-zd

**Comment by kristarella** [comment]
+1 29026451-hc
followup: 4042101-zd

**Comment by kosiew** [comment]
24352467-hc

**Comment by retnonindya** [comment]
10455731-hc

Followup email: 4042211-zd-woothemes

**Comment by formosattic** [comment]
29890517-hc (email follow-up: 4042305-zd-woothemes)

**Comment by KokkieH** [comment]
We've had a report via Twitter DM as well

**Comment by galakhyati** [comment]
24383007-hc
Follow up: 4042300-zd-woothemes

**Comment by devNigel** [comment]
27634680-hc
Follow up: 4042064-zd

**Comment by mrsjaved** [comment]
another report:
29625113-hc
Follow-up: 4042427-zd-woothemes

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/text-color-16/

**Comment by galakhyati** [comment]
another one:
29961226-hc

Follow up: 4042561-zd-woothemes

**Comment by kdevnel** [comment]
Additional report:
26703114-hc

Follow up: 4042684-zd-woothemes

**Comment by kriskorn** [comment]
Another report: 29872281-hc
I also added a high priority label, as this is affecting all Simple sites as far as I can see.

**Comment by nagpai** [comment]
Another report 
27864513-hc

Followup: 4042727-zen

**Comment by edwinho89** [comment]
4042224-zen

Added comment to p7DVsv-bR1-p2#comment-36218 , as it appears to be affecting simple sites (related to recent Gutenberg update?)

WoA site is not affected as tested at current time.

**Comment by MaxPhilip** [comment]
Another report 4042748-zen

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/colour-change-5

**Comment by daria2303** [comment]
Another one: 28271626-hc

**Comment by teofilushansl** [comment]
Another User report: 4042337-zd-woothemes

**Comment by swoodipto** [comment]
Another report: 29628727-hc

**Comment by syds87** [comment]
Another report: 16444673-hc

**Comment by Robertght** [comment]
A new report in 24442742-hc

**Comment by syds87** [comment]
New report in 29958094-hc

**Comment by simison** [comment]
Release with fix: https://github.com/WordPress/gutenberg/releases/tag/v10.7.2 — not on .com yet.

Core equivalent of this issue was in https://github.com/WordPress/gutenberg/issues/32410

**Comment by joashrajin** [comment]
4042145-zd-woothemes

**Comment by dhackneya8c** [comment]
New report in 22423676-hc

**Comment by ersatzpenguin** [comment]
Another report of the font-size option missing mentioned by @chrisfromthelc here: 18400546-hc

Also confirmed that the font-size issue is confined to Simple sites. AT sites seem unaffected.

**Comment by kcswong** [comment]
Report in 29692355-hc, follow up in 4043620-zen

**Comment by deancroyal** [comment]
WordPress.com forums: https://wordpress.com/forums/topic/heading-and-text-block-colours-no-longer-allow-custom-hex-code/

**Comment by joashrajin** [comment]
New report: 4042945-zd-woothemes

**Comment by deancroyal** [comment]
WordPress.com forums: https://wordpress.com/forums/topic/captions-and-colors-in-wordpress/

**Comment by kaitohm** [comment]
This issue has now been resolved. I've responded to all tickets and forums linked above, letting users know the issue has been resolved. I have not responded to any chats where no follow-up tickets was listed.

**Comment by villanovachile** [comment]
Another report 4041989-zd

Responded to user letting them know the issue has been resolved

**Comment by kathleenjross** [comment]
Another report: 824823-hc

Follow-up: 4070444-zd
