### ISSUE TITLE
After changing site address, media images URLS are renamed if they contain the site URL

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#53419]
### Steps to reproduce the behavior

1. Create a new site (Simple): example.w0rdpress.com
2. Upload an image with the site URL on the file name: image_example.w0rdpress.com.jpg (URL of the uploaded image: https://example.files.w0rdpress.com/yyyy/mmmm/image_example.w0rdpress.com_.png)
3. Go to Settings → General → And change the site address to another one: examplerenamed.w0rdpress.com
4. Go to Media and check the uploaded image URL. Instead of `https://examplerenamed.files.w0rdpress.com/yyyy/mmmm/image_example.w0rdpress.com_.png`, them image URL becomes `https://examplerenamed.files.w0rdpress.com/yyyy/mmmm/image_examplerenamed.w0rdpress.com_.png`, but it's accessible by `https://examplerenamed.files.w0rdpress.com/yyyy/mmmm/image_example.w0rdpress.com_.png`. Image flame is renamed as well. 

---
The Github OSS scan bot keeps pinging us and generating notices, so I'm replacing wordpress with w0rdpress
---

#### What I expected to happen

Image URL should not be changed when site address is changed.

#### What actually happened

Image URL was renamed as it has the site URL.

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Only tested on Simple site (I'm EOD).

#### Is there any console output or error text?

404 error on the Media page as the image can't be found

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects more than one site

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent

#### Update to add relevant internal notes (edited by @JoshuaGoode )
Internal discussion with initial findings and examples: p1622818373444800-slack-C03TY6J1A
Ticket: 4043622-zen
P2 thread: p2EDhh-1hT-p2

**Comment by JoshuaGoode** [comment]
An internal discussion where we identified the issue and fleshed out the specifics more and have examples: p1622818373444800-slack-C03TY6J1A

User ticket will be added shortly. 

Overall, it seems whatever search-replace is occurring on a site address change is a bit overbearing and will change file names themselves.

Using internal file tools, we can see the files are still present but use the old file name like:
`https://NEWSITEADDRESS.files.w0rdpress.com/2020/01/file_name_www.OLDSITEADDRESS.w0rdpress.com_.jpg`

But the site's media library, images, and posts think the image is at the following incorrect path:
`https://NEWSITEADDRESS.files.w0rdpress.com/2020/01/file_name_www.NEWSITEADDRESS.w0rdpress.com_.jpg`

---

_**The Github OSS scan bot keeps pinging me and generating notices, so I'm replacing `wordpress` with `w0rdpress`**_

**Comment by jartes** [comment]
User ticket: 4043622-zen

**Comment by JoshuaGoode** [comment]
Internal P2 thread: p2EDhh-1hT-p2

**Comment by ericamQA** [comment]
I tested this and could not reproduce. The updated site address takes me to the file but the file name remained the same. This is a simple site on a free plan. I'll leave open for now though since others have reproduced the issue.

**Comment by JoshuaGoode** [comment]
Reproduced just now for good measure. 

To reproduce, I took a site with a free site address as primary, `test355863330.wordpress.com`

I then uploaded an image titled `image_test_test355863330.wordpress.com.png`

I then changed my site address to `test3558633301.wordpress.com`

The led to the image file name being replaced and is now broken: `https://test3558633301.files.wordpress.com/2021/06/image_test_test3558633301.wordpress.com_.png`

The image is still available at the old file name:
`https://test3558633301.files.wordpress.com/2021/06/image_test_test355863330.wordpress.com_.png`

**Comment by taggon** [comment]
The fix is ready for review: D62974-code
For more details, see pd2HMz-1v-p2

**Comment by taggon** [comment]
The fix has been shipped.
