### ISSUE TITLE
Captions: Invisible on Some Themes

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#53425]
### Steps to reproduce the behavior

1. Add a Video block, embed a Youtube video for example
2. Or add an Image block
3. Add a caption to the video, or the image

#### What I expected to happen
To see the caption text.

#### What actually happened
Caption text is invisible:

![CaptionIssue1](https://user-images.githubusercontent.com/16104522/120844991-8f731a80-c546-11eb-936d-b9b25a620e47.jpg)

#### Reports
28619507-hc
29970127-hc

We were able to replicate with Lodestar and Twenty Fourteen themes.

**Comment by ericamQA** [comment]
Closed in favor of https://github.com/Automattic/wp-calypso/issues/53422
