### ISSUE TITLE
Editor: "Add Title" Label is Missing in Page and Post Editor

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#53444]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/themes
2. Scroll to the bottom, click on "Show all themes"
3. Activate any older WordPress.com themes after Redhill theme.
4. Go ahead create a new post/page, or edit existing post/page without any page titles.

#### What I expected to happen

The "Add title" label is visible on the top of editor, so you know where to add page/post titles.

#### What actually happened

The "Add title" label for page/post title is not visible on top of editor

#### Is this specific to the applied theme? Which one?

Tested and reproducible on themes older than Redhill theme. List of themes under https://wordpress.com/themes (before "Show all themes") are not affected.

#### Does this happen on simple or atomic sites or both?

Simple sites. At sites appears unaffected with Gutenberg v10.6.0. Updating Gutenberg version to v10.7.2 had similar results.

#### Is there any console output or error text?

Quite a number of error texts, though it is unsure if related or not.

![image link 1](https://cldup.com/W5ig8_5GVs.png)
image link: https://cloudup.com/c-OX7M56cg3

Sample log: 29794-pb/

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Site wide using older themes, with Gutenberg version 10.7.2

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image link 2](https://cldup.com/n-MqC6g4Rw.png)
image link: https://cloudup.com/cIEIs3eB8O1

gz#4046358

**Comment by edwinho89** [comment]
Initially reported in 8000150-hc

**Comment by serabi** [comment]
Also reported in 4046358-zen

**Comment by metabreakr** [comment]
29328127-hc

**Comment by thekingsprojects** [comment]
30035937-hc

**Comment by AMcGrady** [comment]
Reported in 4052214-zen

**Comment by davipontesblog** [comment]
I am going to skip triaging on this one and move it to Flow patrol directly to look into.

**Comment by donalirl** [comment]
#22794413-hc

**Comment by nickpagz** [comment]
Another report here #14771418-hc

**Comment by kosiew** [comment]
New report at #4057622-zen

Some test findings.

Reproduced on Gema theme.
Switching to TwentyTwenty fixes the issue.

**Comment by davipontesblog** [comment]
Shifting priorities as there has been a surge of new reports in the last few days.

**Comment by syds87** [comment]
Reported on #4010403-zen

Theme Radcliffe 2.

**Comment by taggon** [comment]
This bug is fixed by https://github.com/WordPress/gutenberg/pull/32477
For more details, check out my analysis. pd2HMz-T-p2

**Comment by retnonindya** [comment]
I'm currently updating internal doc, and I able to replicate this issue.
Theme: Twenty Fifteen

I noticed a fix is underway. Thanks for the hard works, folks!

**Comment by aisajib** [comment]
Also reported in #4064321-zen using the Stow theme.

**Comment by kathrynwp** [comment]
Ran into this in a Concierge Session with a user running Radcliffe 2 - 4065928-zen

**Comment by davipontesblog** [comment]
Added the `[Status] Fix Inbound` label as this bug is already fixed in the Gutenberg core v10.8. When that is updated in WP.com, the issue will be fixed.

**Comment by KirkwallDay** [comment]
This showed up in: 4588232-Hc
Debut theme.

**Comment by taggon** [comment]
Closed as this issue is fixed. Please reopen when it happens again.
