### ISSUE TITLE
New user confirmation screen pauses out

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#53454]
## Steps to reproduce

1. Create a new user on a WP.com account.
2. Check your email for the new user invite email and click the "Accept Invitation" button.
3. You should see a screen similar to the screenshot below. Click the "Accept Invitation" button.
4. The button changes color and the button text changes to "Joining..." and then nothing happens.

## Screenshot

![image](https://user-images.githubusercontent.com/5634774/120999303-f8c97800-c756-11eb-9f83-f08e271f0d94.png)

#### What I expected

I expected this screen to go away and for me to be taken to the Calypso My Home page for this site.

#### What happened instead

This screen never went away. I had to manually type "wordpress.com" into my browser, then manually select this site to get to the admin screen.

#### Browser / OS version

Chrome Version 90.0.4430.212 (Official Build) (arm64)
MacOS Big Sur Version 11.0.1

**Comment by cpapazoglou** [comment]
Closing this as it seems resolved by #53666.

Trying to reproduce it, I got redirected to the new site after I clicked "Join". Also, I got the following nice notification
![](https://cln.sh/P4vBuF+)
