### ISSUE TITLE
Allow Changing Merchant Name or Statement Descriptor on Email Receipts using Payments Block

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#53451]
Please, be as descriptive as possible. Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

What
Allow users the option to add their own merchant name, or renaming statement descriptor when sending email receipts to customers using Payments Block.

Why
More Personalised

How
[Stripe has this option](https://support.stripe.com/questions/update-business-name-shown-on-customer-bank-statements), however it appears we send information in the “statement descriptor” parameter when creating user payments, hence overwriting users.

4035668-zd-woothemes

**Comment by carinapilar** [comment]
I noticed that when testing the Payments block on my site. I have something specific set on my Stripe's account, but once a user makes a payment it shows “WPMEM” plus a UUID (unique alphanumeric code), as described here: PCYsg-lW4-p2 - which wouldn't be expected, since you have something different set on Stripe's side.

It's also a very confusing statement descriptor, and might lead to high occurrences of refund and dispute requests.

**Comment by inaikem** [comment]
Thanks for the feature request, @edwinho89. I raised this here: p1626685750115900-slack-C01B6KEJ5GE.

I'll feedback once I have an update there.

**Comment by inaikem** [comment]
P2'd here: pNPgK-5vM-p

**Comment by DavidRothstein** [comment]
Previous internal discussion: pbMlHh-Fn-p2

**Comment by pauljacobson** [comment]
We had a request for this in 4357438-zen where the customer reported the following:

>At least two subscribers have disputed the renewal transaction as "fraudulent" because they didn't recognise the credit card statement.

**Comment by dcoleonline** [comment]
I'm closing 4357438-zen but we should notify the customer if/when this is implemented.

**Comment by sophiegyo** [comment]
I had request for this today in 33016947-hc.
I let the user know I've added them to the feature request, but also that I have no guarantees it'd be implemented.

**Comment by mrsjaved** [comment]
Another request here:
4673733-zd-woothemes

**Comment by renata-franco** [comment]
Adding this request here: 4817152-zd-woothemes

**Comment by ckmccoy2** [comment]
Another request to be able to update payment descriptor here: https://woothemes.zendesk.com/agent/tickets/4929518

**Comment by ckmccoy2** [comment]
Another request here: 4929518-zd

**Comment by KirkwallDay** [comment]
Another request here: 35606401-hc

**Comment by poojashetty18** [comment]
Another request on: 5545940-zd-woothemes

**Comment by freelylovinglife** [comment]
Another request here 5765252-ZD

**Comment by syhussaini** [comment]
Another request here 6039909-zen

**Comment by millerf** [comment]
Removing the override we do in Earn should allow merchant to set their own. It is part of our current project and should be fixed soon:
pbOQVh-3l7-p2

**Comment by n3f** [comment]
Payments discussion of the descriptor: pbOQVh-3xl-p2

Interested in feedback about where to get the information (do we pull from Stripe -- how often, this probably isn't scalable though), or add a form/field to the Earn page, etc.

Another caveat: this descriptor field isn't very large and the UUID should be required for tracking the order through our systems.

**Comment by n3f** [comment]
https://code.a8c.com/D113437

**Comment by n3f** [comment]
D113437-code

**Comment by n3f** [comment]
Merged/deployed
