### ISSUE TITLE
Global Styles: Make it easier to find

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#53473]
Users running [most](https://github.com/Automattic/themes/issues/3202) themes on WordPress.com that **don't** have a Fonts panel in the Customizer instead have the option to change their Base & Heading font via a Global Styles panel in the post and page editor.

![Edit_Post_‹_Global_Styles_Demo_—_WordPress_com](https://user-images.githubusercontent.com/7662449/121069517-92b31400-c79b-11eb-8234-cefb28e5f256.jpg)

Unfortunately, many users entirely miss the fact that this icon is the key to finding the spot where they can modify their fonts site-wide, and end up either not changing their fonts and remaining frustrated, contacting support for help, or sometimes even churning.

I think the reasons they have trouble finding it are many fold, including:

- The editor is where people expect to **edit page and post content**; it's not intuitive to have site-wide design settings tucked there as well.
- The A icon is tiny and not immediately obvious as a typography/font control.
- The icon is alongside many other competing icons/links/buttons and easily missed.
- The "tooltip" wording Global Styles is not standard and not easily recognized by users. 
 
### Interim Suggestions

- Could we rename the "Global Styles" tooltip to "Fonts" for the time being – at least until there are other settings tucked in with it as Global Styles is developed further? 
- Could we add a Fonts panel in the Customizer for these themes, with a prompt pointing people to Global Styles? That way, when people go to the spot where they expect to find font options, there's some guidance as to where they can find the setting they're looking for. Very rough mockup:

![Global Styles - Customizer prompt](https://user-images.githubusercontent.com/7662449/121069036-0274cf00-c79b-11eb-977b-153fa4c08f6c.jpg)

I'm sure there are other ideas as well.

**Additional context**
Thousands of interactions with WordPress.com users in live chat, email, and Quick Start sessions.

**Comment by kwight** [comment]
I absolutely love this idea. We can include a zoomed-in screenshot of the editor with the button circled, or something.

**Comment by jordesign** [comment]
+1 fantastic idea.

Can we deep link into the editor to make Global Styles visible? (I guess we'd need to pick a default page to take them to *from* the customizer)?

Or we would it be a case of linking to a support doc?

**Comment by ianstewart** [comment]
> Can we deep link into the editor to make Global Styles visible? (I guess we'd need to pick a default page to take them to from the customizer)?

If someone has a static home page, telling people they can "open your home page in the Editor to update fonts" and providing a link seems like it could work. But it'd have to be contextual as they can only view a blog index in the customizer.

**Comment by kwight** [comment]
A reminder to add any Tracks events needed to determine how helpful this has been.

**Comment by jordesign** [comment]
> But it'd have to be contextual as they can only view a blog index in the customizer.

So if they *do* have the front_page set to show latest posts - do we just ask them to edit _any_ page?

**Comment by DanielSmithMichigan** [comment]
> > But it'd have to be contextual as they can only view a blog index in the customizer.
> 
> So if they _do_ have the front_page set to show latest posts - do we just ask them to edit _any_ page?

There's a configuration called "page_on_front" which is usually the homepage. If you switch to "show_latest_posts," I think it sticks to your recent homepage.

I'm using that. But if that configuration isn't set, then the deep link doesn't show and the 'fonts' section in customizer will just show instructions [like this](https://user-images.githubusercontent.com/10274366/124637710-1540f900-de58-11eb-85a5-0fb0694ed784.png).
