### ISSUE TITLE
Themes: Retire Brompton and Redhill

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#53478]
![image](https://user-images.githubusercontent.com/545779/121078436-985e2900-c79e-11eb-9e06-f1cba7b1dbdb.png)

These ones are looking a bit less-fresh than others. With new themes launching, let's retire these ones for new users.

**Comment by kjellr** [comment]
👍 👍

**Comment by scruffian** [comment]
D62678-code

**Comment by scruffian** [comment]
https://github.com/Automattic/themes/pull/4045

**Comment by scruffian** [comment]
This has now been completed.
