### ISSUE TITLE
Reader: Manage: can't reach "searching your followed sites" with keyboard

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#5347]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/edit
2. Use your keyboard TAB key to navigate from Export, Import, by Date
3. Note that the keyboard does not focus on the search icon at all
4. Can't open the search icon without a mouse click

#### What I expected
To be able to TAB, then hit ENTER to open the search field. Good for keyboard only users and people with motion disabilities.

#### What happened instead
The focus keeps going past the search icon.

#### Browser / OS version
Tested in Firefox, Chrome, and Safari on OS X 10.11.4

Note: Safari works less well that the other two browsers with TAB during this keyboard navigation — it skips Export and Import entirely.

Side note: in Firefox when testing this I saw this visual bug again: #4541 — the by Date button looks pretty bad. :/

#### Screenshot / Video
![keyboard-firefox-tab](https://cloud.githubusercontent.com/assets/66797/15196277/72e89f1c-1780-11e6-8d2c-3248af274e7a.gif)

**Comment by lancewillett** [comment]
Flow note: found this during dogfooding, trying to search my sites.

**Comment by psealock** [comment]
**Safari Issue**
TIL: OS X has [disabled tab key navigation](http://osxdaily.com/2011/08/14/enable-tab-key-navigation-safari/) by default. @lancewillett  is your's enabled?

_Safari > Preferences > Advanced > Check "Press Tab to highlight each item on a webpage"_

**Accessibility Issue**
You can enable focus by adding the [tabindex attribute]() to the ```<svg>```, but ENTER won't work

(Safari Version 9.0.3)
![tabindex](https://cloud.githubusercontent.com/assets/1922453/15208480/e19b1d40-187f-11e6-820a-5da8d427f6b1.gif)

**Fix**
Wrap the ```<svg>``` in the native button element via a button component.

**Comment by lancewillett** [comment]
> Safari > Preferences > Advanced > Check "Press Tab to highlight each item on a webpage"
I checked it on now — thanks for the tip, @psealock. Weird default behavior. :)

**Comment by bluefuton** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/5393. Thanks @psealock!
