### ISSUE TITLE
Menu: can't add items before confirming the email address

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#5348]
The Calypso editor allows you to add menus to your website, even if your account is not confirmed by email. When you add items to your menu and try to save it, Calypso simply removes those items without a notice.

Possible solutions: disabling the menu editor or use the [proposed dialog](https://github.com/Automattic/wp-calypso/issues/2650#issuecomment-173899587) by @folletto

Referencing #2650 here.
#### Steps to reproduce
1. Sign up from WordPress.com
2. Go to your My Site > Menus
3. Add a menu item
4. Click save
#### What happened

When you add items to your menu and try to save it, Calypso simply removes those items without a notice.
#### Browser / OS version

Tested with Chrome 50.0.2661.94 and OSX 10.10.5
#### Screenshot / Video

Adding the menu: 

![menu](https://cloud.githubusercontent.com/assets/1136160/15196219/56ce2018-1799-11e6-8e90-7d579f865257.gif)

In WP Admin, however, we can see the items labeled as _Pending_: 

![captura de tela 2016-05-11 as 17 08 17](https://cloud.githubusercontent.com/assets/1136160/15196589/160398ea-179b-11e6-896b-41e8c5f5e188.png)

**Comment by folletto** [comment]
> or use the proposed dialog

Note: that dialog is tailored specifically for the Editor because fits intent and flow, I wouldn't reuse it anywhere else.

We should just disable this UI until the user is approved. Or.... not block it at all, allowing users to publish updates even if the mail isn't approved. I can't see it being a big issue.

**Comment by lancewillett** [comment]
Closing as we are moving menus into Customizer, see #4610
