### ISSUE TITLE
Playwright: automatic sort of imports

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#53486]
**Task Details**
For more consistent import order, we should either define our own rule or incorporate a library that would sort it for us.

**Related to**

**Comment by scinos** [comment]
Can be done as part of p4TIVU-9Hd-p2 ?

**Comment by worldomonation** [comment]
> Can be done as part of p4TIVU-9Hd-p2 ?

Definitely, sorry I recalled reading your post but it escaped me when I wrote up this task.

Looks like you have an accepted answer. Have you had a chance to start this yet?

**Comment by scinos** [comment]
> Have you had a chance to start this yet?

Soon™️.
Is something I'd like to do, but I don't feel it is impactful enough to be on the top of my todo list.

**Comment by worldomonation** [comment]
See: #54448

**Comment by worldomonation** [comment]
Closing this as #54448 has been implemented.
