### ISSUE TITLE
Post Excerpt block: The "read more" link appears twice

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#53488]
Post Excerpt block has an option to customize the "Read more" text. But when a custom text is entered, two "Read more" links appear.

### Steps to reproduce the behavior

1. Create a new post or a page. Add Posts List or Query block.
2. If there's no Post Excerpt block inside, add one.
3. Save and preview. There will be a "Continue reading" link displayed after the excerpt (which I think is a bug too).
4. Go back to the editor, and type in a custom text where it says: "Add "Read more" link text"
5. Save and preview. Note there are two read more links now - one with your custom text, and one that says "Continue reading"

#### What I expected to happen
I expected to only have one read more link, using the custom text I entered.

#### Is this specific to the applied theme? Which one?
I don't think so - I was able to replicate in TT1, Blank Canvas, Spearhead.

#### Does this happen on simple or atomic sites or both?
I have not tested on atomic, BUT this does not happen on a local install, running WP 5.7.2, Gutenberg 10.7.4, and TT1 theme.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Group 248](https://user-images.githubusercontent.com/4550351/121128001-01f93880-c86e-11eb-8f96-7893fec49532.png)
![Group 249](https://user-images.githubusercontent.com/4550351/121128009-07568300-c86e-11eb-90ee-daf001470394.png)
![Group 250](https://user-images.githubusercontent.com/4550351/121128017-0b82a080-c86e-11eb-9f38-2d3935a67e46.png)
![Group 251](https://user-images.githubusercontent.com/4550351/121128027-0f162780-c86e-11eb-879a-1fdf6128fffb.png)

**Comment by alaczek** [comment]
Hmm... this might not be a .com issue after all: https://github.com/WordPress/gutenberg/issues/32473

**Comment by jordesign** [comment]
@alaczek are you happy for this to be closed in favour of the gutenberg issue?

**Comment by alaczek** [comment]
Yep, good to close!
