### ISSUE TITLE
Site Stats: Stats missing from 6 months of site activity

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#53493]
Our customer reached out to us to query why their Site Stats are missing data for a roughly 6 month period for their site https://tinytramper.com/

### Steps to reproduce the behavior

1. Go to the _Stats_ page in the user's site dashboard
2. Click on the toggle to display stats in _Months_
3. Observe missing stats between December 2020 and June 2021

We have attempted the following:

- We ran a full Jetpack sync, with no apparent improvement;
- I believe I was able to confirm the existence of a stats tracking pixel on the site ([see GET response](297cc-pb/))

#### What I expected to happen

The site should have recorded some site stats over this period.

#### What actually happened

There are no stats recorded over this period. See here:

![Screenshot 2021-06-08 at 15-18-42 Stats and Insights ‹ Tinytramper — WordPress com](https://user-images.githubusercontent.com/2912202/121183765-16890100-c86d-11eb-9f54-b1a03a2b3ed9.png)

### Context

This was originally reported in 25234796-hc with a follow-up in 4048710-zen.

#### Browser / OS version

I tested this in Firefox Developer Edition v90.0b3 on macOS 11.4. This does not appear to be affected by browser or OS.

#### Is this specific to the applied theme? Which one?

This is unclear. I'm unable to determine a correlation between the theme and when this issue began.

#### Does this happen on simple or atomic sites or both?

This site is an Atomic site.

#### Is there any console output or error text?

I see the following error, although I'm unsure if this is relevant. My browser is currently configured to block trackers:

```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://3b6225cd-f4ba-dd46-b281-1ea303fd9df7/userscripts/WordPress%20Quick%20Navigate.user.js?id=daa7c1f9-ab51-4066-93c7-fef58da08722
Source Map URL: vue-select.js.map
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

There are other reports of missing stats, although it's not clear if those issues are caused by the same issue (whatever that is).

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

See above

**Comment by kriskarkoski** [comment]
Was there any Jetpack connection issue we're aware of? I don't believe stats are recorded when Jetpack is disconnected

**Comment by rezzap** [comment]
Not aware of any Jetpack connection issues as far as I can see, but I do see a few PHP errors in the logs going back to December that might be related here. One in particular with the `google-analytics-dashboard-for-wp` plugin. 

I've opened a new report for this for Jetpack devs to take a look: 6693-gh-Automattic/jpop-issues since it's a single issue. Closing this here.
