### ISSUE TITLE
Reader: Comment button doesn't work on Android

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#535]
If you view the Reader list on Android, tapping on the comment button does turn it to the blue highlight color but nothing happens after that.

Samsung Galaxy S6, Android 5.1 and Chrome browser.

**Comment by lancewillett** [comment]
Could you please add a screenshot or video (GIF?) if you are able?

**Comment by roundhill** [comment]
> Could you please add a screenshot or video (GIF?) if you are able?

A screenshot of it doing nothing? :)

![screenshot_2015-11-23-10-16-01](https://cloud.githubusercontent.com/assets/789137/11345378/6cb91a30-91cb-11e5-91c7-92f741f6e5da.png)

**Comment by lancewillett** [comment]
Visual oxygen! It's the lifeblood of communication, on the same page and worth a thousand words (sometimes).
