### ISSUE TITLE
Bugged behavior when switching sites after viewing a theme demo

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#53504]
https://user-images.githubusercontent.com/10274366/121209658-03fcd080-c849-11eb-808a-bd01c988bcfa.mov

### How to recreate

1. Use mobile
2. Go to /themes/SITE_SLUG page from a SIMPLE site.
3. For any theme, click the ellipsis to expand the popover menu or view the demo.
5. Close the demo / ellipsis sub-menu
4. Click the "My sites" button / wordpress logo.
5. Select an ATOMIC site.
6. Before you even select which page to view, the themes you saw in step 2 are now overlaying the page.

**Comment by DanielSmithMichigan** [comment]
I'm still confused, but here's what I understand so far.

This is the basic HTML hierarchy:

```
    <div id="secondary">
        <!-- menu -->
    </div>
    <div id="primary">
        <div id="themes">
            <!-- themes content -->
        </div>
    </div>
```

The menu has these properties which mean that the content and menu are stacked on top of each other.
```
position: fixed;
top: 0;
```

But why do we only see one at a time? We apply a "focus-sidebar" or "focus-content" class to one of the parent containers, to choose whether we see the menu or sidebar.

When focus-content is applied, then the **menu** has this property:
```
/* Push the menu off the screen to the left side, so the content is visible */
transform: translateX(-100%);
```

When focus-menu is applied, then the **content** has this property:
```
/* Push the content off the screen to the right side, so the menu is visible */
transform: translateX(100%);
```

Therefore, we will only see one at a time. The issue is for some reason we end up with a layout like below. ***for some reason*** content is pushed off to the left. When content is to the left, then the translateX on themes pushes it ontop of the menu.

![image](https://user-images.githubusercontent.com/10274366/121449938-c7c09180-c968-11eb-82e4-4cd17ab25c1c.png)

So the big mystery is this:

Why is content pushed off to the left side of the screen? There's no obvious CSS properties causing it to do that.

Here's some random facts:



- Following the steps above, this happens 100% of the time when I switch from a simple site to an atomic site. It never works the other way around.
- When following the steps above, you can replace the theme demo step with just clicking the ellipsis below a theme to display the theme options. The issue will still occur 100% of the time.
- You can "fix" the issue by forcing chrome to re-render (shown later in this post)
- The issue occurs in firefox as well.

https://user-images.githubusercontent.com/10274366/121450400-a7450700-c969-11eb-891a-619a242ae276.mov


Here's a full html/css recreation of the issue. Note the "mystery property" described in the source:

```
<style type='text/css'>
    #menu {
        position: fixed;
        top: 0;
    }

    #themes {
        transform: translateX(100%);
    }

    #content {
        background-color: blue;


        /* The mystery property! I don't see this one in prod, but it's required to get the full effect */
        transform: translateX(-100%);
    }

    #menu {
        background-color: red;
    }

    div {
        height: 100px;
        width: 100px;
    }

    html, body {
        width: 100px;
        height: 100px;
        margin: 0;
        padding: 0;
    }
</style>

<div id="menu">
    menu
</div>

<div id="content">
    content
    <div id="themes">
        <br />themes
    </div>
</div>
```

**Comment by DanielSmithMichigan** [comment]
I think that our system of using translateX to move our windows off screen is causing the root issue. Translate is a relative property and we can't specify what we're translating relative to. When we have multiple things being translated it can get complicated. I prototyped a different version of our layout that might have fewer edge cases. But I don't know if this will provide any practical value, since it might not be something we could reasonably implement. For now I'm going to put this prototype aside and try to look into quicker fixes.

```
<style type='text/css'>
/* Relevant CSS Begin */
  .grid-container {
    width: 100%;
    height: 100%;
    display: grid;
    grid-template-columns: 100% 100% 100%;
  }

  .grid-container.panel2 {
    transform: translateX(-100%);
  }

  .grid-container.panel3 {
    transform: translateX(-200%);
  }

  .grid-container {
    transition: 0.15s ease-in-out, opacity 0.15s ease-out;
  }

  .grid-elem a {
    width: 100%;
    height: 100%;
    display: inline-block;
    text-align: center;
  }
/* Relevant CSS End */

  body, html {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
  }


  .container {
    width: 100%;
    height: 100%;
    background-color: #222;
    display: grid;
    justify-items: center;
  }

  .centered {
    width: 200px;
    height: 100%;
    background-color: #333;
    overflow: hidden;
  }
</style>

<script type="text/javascript">
  function panel1() {
    document.getElementById('grid-container').className = 'grid-container panel1';
  }
  function panel2() {
    document.getElementById('grid-container').className = 'grid-container panel2';
  }
  function panel3() {
    document.getElementById('grid-container').className = 'grid-container panel3';
  }
</script>

<div class="container">
  <div class="centered">
    <div id="grid-container" class="grid-container">
      <div id="elem1" class="grid-elem">
        <a onClick='panel2();'>panel1</a>
      </div>
      <div id="elem2" class="grid-elem">
        <a onClick='panel3();'>panel2</a>
      </div> 
      <div id="elem3" class="grid-elem">
        <a onClick='panel1();'>panel3</a>
      </div>  
    </div>
  </div>
</div>
```

**Comment by DanielSmithMichigan** [comment]
@kwight 

In the middle of last sprint [two issues came up in the same slack thread](p1623165103106600-slack-C0202PMUXLJ) and you pulled one of them into the sprint. That was [53506](https://github.com/Automattic/wp-calypso/issues/53506).

THIS issue, which is from the same slack thread, was never pulled into a sprint. 53506 was blocked for me at one point so I started looking into this issue.

Since we're starting a new sprint, just wanted your thoughts, if I should keep looking into this, or grab something from the "current sprint" column instead.

**Comment by kwight** [comment]
@DanielSmithMichigan I'll pull this one into the column too, you can work on whatever you think is best!
