### ISSUE TITLE
Clicking "My Sites" button from the /theme/THEME_NAME/SITE_SLUG page is not working

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#53506]
1. Go to the themes page for one of your sites. Select a theme.
2. Click "My Sites"/WordPress logo in the top left.

Mobile behavior:

https://user-images.githubusercontent.com/10274366/121213298-1af0f200-c84c-11eb-96e7-b3e8a4fd4a40.mov

Desktop behavior:

https://user-images.githubusercontent.com/10274366/121215534-1af1f180-c84e-11eb-9af5-9d10309147f2.mov

**Comment by mreishus** [comment]
I thought it might be related to 954d52147a98055b9f4cce46f8b1bd986597da5f (#52686), but I don't think it is; I still see the bug after reverting that commit locally.

**Comment by davipontesblog** [comment]
Moving to Flow Patrol to triage.
