### ISSUE TITLE
Plans: Allow free Atomic sites to upgrade to Premium

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#53515]
#### What plan tier is the site on?
Free

#### Where are you seeing the issue?

1. Go to /plans/{site-url}?feature=google-analytics&plan=value_bundle
2. See it!

#### What I expected on the WordPress.com site
The Premium plan and Google Analytics feature to be highlighted.

#### What I expected on the Atomic site
The Premium plan and Google Analytics feature to be highlighted.

#### What actually happened
Simple | Atomic
------- | -------
<img width="342" alt="Screen Shot 2021-06-08 at 2 09 44 PM" src="https://user-images.githubusercontent.com/1689238/121235780-3a474980-c863-11eb-984b-e5f991ff72ec.png"> | <img width="348" alt="Screen Shot 2021-06-08 at 2 09 08 PM" src="https://user-images.githubusercontent.com/1689238/121235790-3ca9a380-c863-11eb-99a0-647030220f0e.png">
------ | -------
<img width="347" alt="Screen Shot 2021-06-08 at 2 09 50 PM" src="https://user-images.githubusercontent.com/1689238/121235826-48956580-c863-11eb-9995-49358ecef969.png"> | <img width="344" alt="Screen Shot 2021-06-08 at 2 09 15 PM" src="https://user-images.githubusercontent.com/1689238/121235838-4a5f2900-c863-11eb-9005-dc916bce470d.png">

#### Is this specific to the applied theme? Which one?
Nope.

#### Possible Cause
- We only add the `is-highlighted` class if `availableForPurchase` is `true` (as of https://github.com/Automattic/wp-calypso/pull/53146)
- `availableForPurchase` is only `true` if `canUpgradeToPlan()` returns `true`
- `canUpgradeToPlan()` doesn't allow Atomic sites without a plan to upgrade to Premium:
https://github.com/Automattic/wp-calypso/blob/e797df8452361ce7ead6ae1cdfec37378da0309c/client/state/selectors/test/can-upgrade-to-plan.js#L347-L351

**Comment by cpapazoglou** [comment]
I suppose that we should do the same for Personal plans too?

**Comment by mreishus** [comment]
As of today, my Atomic site on a **premium plan** is showing the GA feature highlighted when given the link above:

![Image](https://user-images.githubusercontent.com/937354/174684666-32f80313-6091-4fb8-b585-c4acde891e6c.png)

My Atomic site on a **free plan** is showing a new style plan comparison page. I'm not sure if this is the bug or if the page does not support highlighting features given in the query string:



![Image](https://user-images.githubusercontent.com/937354/174684729-2bbc737c-d2e4-4fee-a07a-a34f89ac6829.png)

**Comment by DustyReagan** [comment]
I'm seeing the same thing as @mreishus. I feel like we can close this particular issue on account that Atomic free sites now see the "Starter/Pro" upgrade page, and (non-free) Atomic legacy plans are showing the correct behavior.
