### ISSUE TITLE
Import: Enable imports in WP Desktop app

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#5353]
#### What I expected

I expected to find the Calypso import feature (available on the web at https://wordpress.com/settings/import) in the desktop app.

#### What happened instead

The import feature is not available in the desktop app settings.

Currently, the feature relies on [a feature flag](https://github.com/Automattic/wp-calypso/blob/f70ae76e3740c1e262e9be064669615641748491/client/my-sites/site-settings/index.js#L19), and the feature is not [enabled in the desktop app](https://github.com/Automattic/wp-calypso/blob/master/config/desktop.json) yet.

The importer was enabled about 2 months ago, with a note in https://github.com/Automattic/wp-calypso/pull/3725 about enabling it later in the desktop app:

> After a period of successful deployment we can test in the desktop client and then remove the flag altogether.

@dmsnell are we at a point where we can test imports in the desktop client? Not sure if you want to wait until after the [Importer: Reduxify milestone](https://github.com/Automattic/wp-calypso/milestones/Importer:%20Reduxify) is complete but I wanted to open an issue for this so I don't lose track.

**Comment by dmsnell** [comment]
@rachelmcr I don't think we should have any trouble testing in the desktop client. There's no need to wait on the refactor, as it's slated to be a slow and gradual beast.

If you want, I can ask around and see if anyone has a problem turning it on. Thanks!
