### ISSUE TITLE
Invites: Accepting invitation doesn't redirect to posts page

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#53546]
### Steps to reproduce the behavior

You'll need two accounts for this, and the second one shouldn't have any sites:
1. With first account, go to  Users / Add new
2. Add the second account as an editor to your site
3. Log out with the first account and accept the invitation with the second account
4. See that Calypso is still on the `You have no sites` page instead of the Posts page for the site you were invited to.

See this whole flow in this recording of a [failing spec](https://teamcity.a8c.com/viewLog.html?buildId=6281404&buildTypeId=calypso_RunCalypsoE2eDesktopTests&tab=buildResultsDiv&branch_calypso_WebApp=fix%2Fe2e-create-site-for-domain-tests): https://teamcity.a8c.com/repository/download/calypso_RunCalypsoE2eDesktopTests/6281404:id/screenshots/user-has-been-added-as-editor-2021-06-09T12-23-13.mpg

#### What I expected to happen

After accepting an invitation a user should be redirected to the Posts page of the site they were invited to.

#### What actually happened

The `You have no sites` page is opened after accepting an invitation.

#### Level of impact

Low. The redirect happens when page is refreshed or the `My Sites` button is clicked.

**Comment by tyxla** [comment]
Hey @WunderBart I’m assuming that the second account must have no sites at the time of accepting the invitation, right?

**Comment by WunderBart** [comment]
> Hey @WunderBart I’m assuming that the second account must have no sites at the time of accepting the invitation, right?

Ah, right! I don't know what would happen if that second account has any other sites :/

**Comment by tyxla** [comment]
Fix and explanation is in #53553. Thanks for reporting it @WunderBart!

**Comment by tyxla** [comment]
Alternative (and better) fix is here: #53576
