### ISSUE TITLE
Livechat: empty color in CSS

### ISSUE THREAD

**Issue by nb** [Automattic/wp-calypso#5355]
In `assets/stylesheets/shared/_livechat.scss` there are few instances of `color:!important` and that’s causing CSS warnings.

Should we remove them or is this a symptom of a deeper problem?

cc @rickybanister (added the file initially)

**Comment by rickybanister** [comment]
That file was copied from Olark and contained a lot of dubious stuff. I cleaned up quite a bit at the time, but apparently missed some things. Since `color: !important` has no affect on display it should be fine to remove.

**Comment by lancewillett** [comment]
Closing as duplicate of #3494
