### ISSUE TITLE
Hosting panel stuck "Activating Hosting Features" for reverted WoA sites

### ISSUE THREAD

**Issue by brandonpayton** [Automattic/wp-calypso#53555]
### Steps to reproduce the behavior

1. Pick a simple test site with a business plan
2. Go to the hosting panel and activate hosting features
3. Once the site is transferred to Atomic infrastructure, revert it
4. Refresh the hosting panel

#### What I expected to happen

The hosting panel would show the option to Activate hosting features again

#### What actually happened

The hosting panel is stuck in "Activating hosting features" state.

<img width="1245" alt="Screen Shot 2021-06-09 at 9 00 00 AM" src="https://user-images.githubusercontent.com/530877/121390149-f22b3400-c901-11eb-947f-9f1716121c2d.png">

Clearing the `calypso_store` indexed DB and refreshing quickly resolves the issue.

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It can effect all reverted sites.

**Comment by mreishus** [comment]
Saw another occurrence today.

**Comment by JoshuaGoode** [comment]
Duplicate with some progress: https://github.com/Automattic/wp-calypso/issues/61974

**Comment by JoshuaGoode** [comment]
Closing in favor of the newer duplicate, only because it seems to have some progress and a PR pending.  https://github.com/Automattic/wp-calypso/issues/61974
