### ISSUE TITLE
Sidebar: Main content column shifts offscreen between 660px and 780px

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#53574]
### Steps to reproduce the behavior

1. Resize your browser to be between 660px and 780px wide
2. Visit a Calypso page like 'My Home' or Settings'
3. Click 'My Sites' to reveal the left Nav

#### What I expected to happen

Nav to slide in - and keep main content still visible

#### What actually happened

Content is shifted far to the right - so there is a large gap and the content is barely visible.

<img width="675" alt="Screen Shot 2021-06-10 at 5 21 59 pm" src="https://user-images.githubusercontent.com/1842363/121482311-6227e000-ca10-11eb-9d4a-23e3cc54b063.png">

#### Browser / OS version

Confirmed in Chrome and Safari

#### Does this happen on simple or atomic sites or both?

Both

#### Video

https://user-images.githubusercontent.com/1842363/121482671-b3d06a80-ca10-11eb-9004-9b6e77f05fd7.mov

**Comment by jordesign** [comment]
Looks like this CSS is the culprit:

```
@media only screen and (max-width: 782px){
.theme-default.is-nav-unification .layout.focus-sidebar:not(.is-section-post-editor) .layout__primary .main, .theme-default.is-nav-unification .layout.focus-sites:not(.is-section-post-editor) .layout__primary .main {
    transform: translateX(100%);
}
}
```

Changing it to this fixes the display problem 

```
@media only screen and (max-width: 660px){
.theme-default.is-nav-unification .layout.focus-sidebar:not(.is-section-post-editor) .layout__primary .main, .theme-default.is-nav-unification .layout.focus-sites:not(.is-section-post-editor) .layout__primary .main {
    transform: translateX(100%);
}
}
```

**Comment by jordesign** [comment]
I'm seeing the above CSS in line 257 of /client/assets/stylesheets/_nav-unification.css

**Comment by davipontesblog** [comment]
Shifting priorities as this may be affecting most (if not all) users using a tablet device.

**Comment by jordesign** [comment]
Thanks Davi!
