### ISSUE TITLE
Sharing Buttons: Hide by default on pages for new sites

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#53605]
Sharing buttons are currently on by default on pages for new sites:

![image](https://user-images.githubusercontent.com/545779/121577842-9b9c2380-c9ef-11eb-850e-3714cc335338.png)

Default for all new pages on all new sites seems like an uncommon option for page creation.

**Task:**

Let's look at making sure the Headstart annotations running in signup/onboarding are turning this off by default.

**Comment by andres-blanco** [comment]
Fixed in D62915-code
