### ISSUE TITLE
Sharing Buttons: Swap order of customization and display cards

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#53604]
It can be difficult to customize display options for sharing buttons as the show/hide at the page/post level can be a bit buried. Future updates might combine the following cards with a more refined layout but here's a simple change we can make: we'll swap the card order.

**Before**

![image](https://user-images.githubusercontent.com/545779/121577565-42cc8b00-c9ef-11eb-90b1-8cd11e703ed2.png)

**After**

![image](https://user-images.githubusercontent.com/545779/121577731-714a6600-c9ef-11eb-9106-86469a449306.png)

**Comment by jordesign** [comment]
So.... this looked like a good kind of a task for me to see if I can figure out more about how Calypso works. Sorry if I've stepped on anyone's toes by diving in... But I have a PR that swaps the locations of the sections.... Super open to if I have done the right thing (either in code _or_ process).

PR in #53614

**Comment by jordesign** [comment]
Just noting this will make the video currently shown on the Support Doc for this functionality out of date.
