### ISSUE TITLE
My Home has a number of accessibility issues

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#53617]
My Home in Calypso has a number of accessibility issues. For some users this could make using My Home to setup up their site difficult (or worse).

I've listed some of the issues below. It's probably not exhaustive, I found these without spending much time looking.

- [x] Some links in Quicklinks aren't tab navigable or semantically marked up as buttons
  https://user-images.githubusercontent.com/1500769/121634557-e04fb980-cad8-11eb-959d-d76f8ccc6a71.mov
- [x] The "Hide this" button on promotional cards isn't usable with a keyboard
  <img width="239" alt="Screenshot 2021-06-11 at 5 18 36 PM" src="https://user-images.githubusercontent.com/1500769/121634660-15f4a280-cad9-11eb-809e-7e5f3a3bbac5.png">
- [x] The focus state isn't clear on some controls e.g. the "Hide this" and App Store buttons
- [x] Uses heading tags that skip levels e.g. "Edit homepage" and the mobile app tagline use `<h6>` but there's not `<h5>` anywhere.
- [x] Quicklinks and site setup checklist accordian controls aren't using ARIA attributes so assistive technology doesn't know what these custom controls are (they should probably use the accordian control from Gutenberg which already has the correct ARIA attributes)
- [x] DotPager slides unexpectedly when using tabs. See [comment](https://github.com/Automattic/wp-calypso/issues/53617#issuecomment-1042601223).

**Comment by autumnfjeld** [comment]
We can consider this an umbrella issues and we'll break these down into separate Issues or PRs as we have the bandwidth.

**Comment by roo2** [comment]
I found some very wierd behaviour with using tab on the primary cards slider in chrome.
In the video, I tab to the primary "Enroll today" button, then to the "Hide this" button, and then one more time. The slider scrolls unexpectedly, and even stays scrolled when I use the next and previous keys. cc @taipeicoder 

https://user-images.githubusercontent.com/22446385/154414298-33cf1add-3914-4809-8ba0-0a9bc0197c30.mov

**Comment by roo2** [comment]
I also tried using the tab key to go through elements on the page in Firefox on macos. I found that I couldn't tab to most of the links on the page. I find similar tabbing behavior throughout calypso in FF.

**Comment by taipeicoder** [comment]
> I found some very wierd behaviour with using tab on the primary cards slider in chrome. In the video, I tab to the primary "Enroll today" button, then to the "Hide this" button, and then one more time. The slider scrolls unexpectedly, and even stays scrolled when I use the next and previous keys. cc @taipeicoder
> 
>  Screen.Recording.2022-02-17.at.3.53.54.pm.mov

Yes! I came across this issue as well. Will try to spend some time to look into this.

**Comment by arthur791004** [comment]
I think we should set `tabindex` of non-active elements to -1 to remove them from the page tab sequence.

**Comment by autumnfjeld** [comment]
Great work that you all have tackled so many of these accessibility issues! :) 

@taipeicoder Will all the items in the original issue description be addressed after this last fix for the tab behavior?   We probably don't want to spend too much more time on My Home (just because we have some other priority [bugs](https://github.com/orgs/Automattic/projects/338/views/1?filterQuery=bug) in Ready for Dev), the fixes you've already implemented are a nice improvement! :)

**Comment by taipeicoder** [comment]
@autumnfjeld I agree! We've done plenty of improvements over the last days, which covers the description checklist and a bit more than that. One outstanding issue is the positioning problem reported by both @roo2 and @arthur791004. I'm thinking we can create new GitHub issue for that and track it there, and close this one in the meantime (or move it back to the backlog as it's more of an umbrella issue). Any thoughts?

**Comment by p-jackson** [comment]
With #61230 it looks like everything in this list has been addressed 🎉 
If I'm right then feel free to close this one @taipeicoder 💪
