### ISSUE TITLE
Sharing: Connect button position issue

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#5362]
The issue was reported in 2655052-t
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/110942689
2. Click on the _Connect a different account_ button for Twitter while you are logged into a Twitter account

#### What I expected
The Connect button should be normally displayed.

#### What happened instead
The Connect button is pushed all the way down. It can still be clicked on desktop, but it doesn't show on mobile at all and it can't be clicked.

#### Browser / OS version
Chrome 50.0.2661.94 on OS X 10.11.4
Android device (Tecno Y6) with OS version 4.4.2

#### Screenshot / Video
<img width="1178" alt="screen shot 2016-05-11 at 1 00 52 am" src="https://cloud.githubusercontent.com/assets/10340370/15230082/534132ae-1894-11e6-8eb2-f37224049cbb.png">

![photogrid_1462810969106](https://cloud.githubusercontent.com/assets/10340370/15229996/dbd1b7ac-1893-11e6-8ed4-e69c5269b33f.jpg)

**Comment by lancewillett** [comment]
Closing as this hasn't come up in other reports. Feel free to re-open if it's a common bug that people with many Twitter accounts run into.
