### ISSUE TITLE
Atomic: WebP support on GD module

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#53627]
### What
Enable WebP support on GD PHP module. 

### Why
For performance reasons, required to use this plugin: https://wordpress.org/plugins/webp-converter-for-media/

**Additional context**
Requested by user here: 30086905-hc
Also found this older request here: p9F6qB-5Oz-p2

**Comment by JoshuaGoode** [comment]
Hi there! Please make these requests on our internal Atomic requests P2 when possible @carinapilar. Opening an associated GH issue is great for tracking and additional visibility but the main request should be on the P2.

I believe @bazza worked on this back in July 2021.  

Moved to p9F6qB-5Oz-p2

**Comment by carinapilar** [comment]
> I believe @bazza worked on this back in July 2021.

Ah, yes, I remember seeing that a bit after opening this request.

> Please make these requests on our internal Atomic requests P2 when possible

Since the request on the P2 was already marked as done, was a year old, and our Bugomattic tool only searches on GH repos, my thought was that opening this here would be more appropriate, so other HEs would be able to find that it's been reported already and contribute with new user interactions. 🙂

**Comment by JoshuaGoode** [comment]
Totally understandable and there should be Github issues opened for things like this for tracking and visibility.  

However, for Atomic-specific platform changes, there must be an open Atomic request P2 post open for it as well. That will help ensure the Atomic platform team reviews it as a WordPress.com product team cannot make this change. 

Feel free to open new Atomic requests in these cases.  Old requests can be reopened but it's often better to make a new request summarizing things.   In this case, I reopened an old request.

**Comment by carinapilar** [comment]
> However, for Atomic-specific platform changes, there must be an open Atomic request P2 post open for it as well. That will help ensure the Atomic platform team reviews it as a WordPress.com product team cannot make this change.

Understood, although my understanding is that even in this case as an HE my responsibility is only to report to GH, then Bug Herders/PAs would triage and move to a P2 if necessary, but I'll keep that in mind for the next time. 😌

**Comment by JoshuaGoode** [comment]
I'd recommend reporting directly to the Atomic folks over on our internal P2, doesn't look like this was ever moved to the right place.

Anyway, thank you for reporting it.  We did indeed deploy WebP for GD. Closing this issue.
