### ISSUE TITLE
Allow Changing Site Address under General Settings

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#53653]
Please, be as descriptive as possible. Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

What
To allow users to change default site address directly under "Settings > General" section - https://wordpress.com/settings/general/

Or at least, adding another quick button to [change site address](https://wordpress.com/support/changing-site-address/) easily - https://wordpress.com/domains/manage/domain_url/change-site-address/domain_url

Why
If the WordPress.com site is on the free plan, it'd be nice to provide options to allow changing site address easily.

How

![image](https://user-images.githubusercontent.com/34882260/121835671-6bf95e00-cd04-11eb-8e23-468b72f51f11.png)

Suggested in 5332490-hc

**Comment by Aurorum** [comment]
PR for this issue in #53858. :)
