### ISSUE TITLE
Me: Security settings unavailable with "unexpected error"

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#53670]
### Steps to reproduce the behavior

1. Go to 'https://wordpress.com/me/security' when unproxied
2. See `We're sorry, but an unexpected error has occurred` error

#### What I expected to happen

To be able to access security settings as I can when proxied

#### What actually happened

We're sorry, but an unexpected error has occurred error

### Context

User reported

#### Browser / OS version

Chrome, OSX

#### Is this specific to the applied theme? Which one?

NA

#### Does this happen on simple or atomic sites or both?

NA

#### Is there any console output or error text?

![Screen Shot 2021-06-14 at 11 14 06 AM](https://user-images.githubusercontent.com/1900444/121915961-b3cab600-cd01-11eb-90f9-9c11636e8cab.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

High, seems to be all users

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot 2021-06-14 at 11 14 58 AM](https://user-images.githubusercontent.com/1900444/121916020-c3e29580-cd01-11eb-8be9-22df8f182530.png)

**Comment by obenland** [comment]
@jsnajdr @Automattic/team-calypso Could this be related to #53658 or #53660?

**Comment by julsyd** [comment]
I am also getting this in my own WPcom account while proxied (was checking for another user who reported the same issue).

**Comment by tyxla** [comment]
Looks like this might be caused by #53658. Haven't investigated, but at a first glance, it seems like it happens because we're attempting to throttle unexisting functions.

We might need to move the declarations that call `debounce` like `debouncedPasswordValidate` after the actual method that they debounce is defined. It's a bummer that JS classes don't quite work like PHP ones 😅 

Trying that in #53671 to see if it will do the job.

**Comment by tyxla** [comment]
Noting that `me/security/password` for example is dead in all environments, regardless of proxy. It dies with the same error, so it's likely that fixing that will fix the other error, too.

**Comment by tyxla** [comment]
This should have fixed the problem, I'm monitoring and will reopen if it doesn't fix it when it lands in production. We need roughly 15 minutes to get the new build to production.

**Comment by tyxla** [comment]
Confirmed that this resolved the problem. Feel free to ping me if you encounter this again.

**Comment by kriskarkoski** [comment]
The original issue is resolved by #53671 in that the page loads now, but new passwords cannot be saved.

**Comment by kriskarkoski** [comment]
![Screen Shot 2021-06-14 at 12 27 41 PM](https://user-images.githubusercontent.com/1900444/121926412-ef6a7d80-cd0b-11eb-9d25-f0502f2dceaa.png)

From @rfaile313:

> You can edit it in the DOM to actually make it usable

**Comment by tyxla** [comment]
Original PR that caused the regression was reverted in #53673. I think this is good to close now?

**Comment by kriskarkoski** [comment]
I think so @tyxla following the revert. Closing now.
