### ISSUE TITLE
Nav Unification: Create UI for rendering a quick switcher on WP Admin

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#53707]
As part of https://github.com/Automattic/wp-calypso/issues/51441, we need to create a UI component in WP Admin that will render the new Calypso/WP switcher in the following pages:
- My Home
- Posts > All posts
- Posts > Categories
- Posts > Tags
- Media
- Pages > All pages
- Testimonials > All testimonials
- Portfolio > All projects
- Comments
- Appearance > Themes
- Users > All users
- Tools > Import
- Tools > Export
- Settings > General
- Settings > Writing
- Settings > Discussion

This task is about creating the UI pieces without any functionality (just the markup and styling) according to the Figma design file (JOrcjwreJTRNKKtd6HNYG1-fi-1821%3A289).

**Note:** While the designs show the switcher to the bottom of the Screen Options, there was a decision to place it in the top pd2C0z-2y-p2#comment-107 

![image](https://user-images.githubusercontent.com/12430020/123086374-086ddf80-d42c-11eb-9501-0a9d2bd5eb6b.png)

**Comment by cpapazoglou** [comment]
There is a filter we can use `screen_settings` https://developer.wordpress.org/reference/classes/wp_screen/show_screen_options/
