### ISSUE TITLE
VideoPress: Video Block and VideoPress Block embed appears as link

### ISSUE THREAD

**Issue by lizswafford** [Automattic/wp-calypso#53716]
### Steps to reproduce the behavior

1. Go to a new page or post in editor view. 
2. Add a new Video Block or VideoPress Block. 
3. Add a video from the Media Library to the block.
4. Publish or view the page or post preview. 
5. Video is not embedded, it appears as a hyperlink.

#### What I expected to happen

Video Block and VideoPress Block should show an embed of a video on the page or post preview and the final published version of the page. 

#### What actually happened

The link to the video appeared instead of an embed. The video on the site works, has a valid URL, but the block is not showing the video. 

#### Does this happen on simple or atomic sites or both?

This is for an atomic site. Both the Video Block and VideoPress Block fail to embed.  However, on a simple site, the VideoPress Block renders a link instead of an embed. While the Video Block does show the video embed as expected. 

Workaround is to use a Shortcode Block and the wpvideo shortcode like: [wpvideo Xvtiek9b]

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

I was able to reproduce this on two atomic sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Screenshot of hyperlinks: https://d.pr/i/fFfOZz

4070421-zen

**Comment by Robertght** [comment]
Thank you for reporting this @lizswafford !

I looked into it and it appears the blocks showed up correctly. I'm wondering if this is specific to a certain theme for now.

Also, does [this](https://github.com/Automattic/wp-calypso/issues/33371) look similar to the one above?

**Comment by carladoria** [comment]
Another report at 31601868-hc

**Comment by thekingsprojects** [comment]
Another report at 31373558-hc

For now, the user is using the VideoPress embed block and video shortcodes as a workaround, although they'd prefer using the Video block because its playback controls include a "rewind" option where VP doesn't. Using the third-party Yaatra Mag theme.

**Comment by kathleenjross** [comment]
Another report with 4339738-zd

Offered user the workaround with the shortcode, but they wanted to have 1) autoplay on the video, and 2) turn off playback controls, so they would prefer the video block.

**Comment by thekingsprojects** [comment]
Another report at 32304579-hc

**Comment by carladoria** [comment]
another report at 32589000-hc  with Video block
VideoPress worked though

**Comment by sguzovskaia** [comment]
Another report at 32844903-hc. Both the Video Block and VideoPress Block fail to embed. Atomic site.
Offered the workaround with the shortcode as a temporal solution.

**Comment by Nic-Sevic** [comment]
Another report here 32909395-hc where only the Video block (with video selected from media gallery) rendered as link in live site.
When using a video block and adding the video via URL it embeds fine. 
Both videopress embeds worked fine in live (shortcode and block) although both show as code only in editor.

**Comment by kosiew** [comment]
Additional finding.

I noticed that I can consistently reproduce the video block showing only code by  doing this:

1. upload video to VideoPress
2. Uncheck the Share box

![image](https://user-images.githubusercontent.com/29057562/143669959-4d43d3bd-506b-4474-a799-1aa7a7f47e4e.png)

Once, it is unchecked, the video will always display as code, even if I subsequently check the Share box.


Test page - https://wpstore101.wpcomstaging.com/video-block/

![image](https://user-images.githubusercontent.com/29057562/143670018-be1317fc-1606-44cb-9c1f-c92703f8f824.png)

**Comment by happychait** [comment]
Another report in 33220585-hc and followed up in 4620193-zen

**Comment by i11za** [comment]
Another report in 33967221-hc and followed up in 4739002-zen.

**Comment by i11za** [comment]
Another report in 4751719-zen

**Comment by Robertght** [comment]
Another report in 4817907-zen

**Comment by villanovachile** [comment]
Another report in 35225411-hc

**Comment by sguzovskaia** [comment]
Another report in 36131859-hc

**Comment by galakhyati** [comment]
Another case: 36223295-hc
Follow up: 5430107-zd-woothemes

Screenshots:
![Markup on 2022-07-28 at 10:36:14](https://user-images.githubusercontent.com/7382505/181425057-0a40700c-bf37-44a9-a5f4-b16fd42165f7.png)
![Markup on 2022-07-28 at 10:36:47](https://user-images.githubusercontent.com/7382505/181425077-d0a8ebff-a069-46ba-a342-ecde27bb4605.png)

**Comment by ha-un** [comment]
Another report on 35741035-hc and 18437628-hc

**Comment by devNigel** [comment]
Another report: [35802630](35802630-hc)
Followup: 5446540-zd-woothemes

**Comment by eoinsav** [comment]
We have also run into this with a Special Projects partner. The videos broke after unchecking the Sharing option mentioned here: https://github.com/Automattic/wp-calypso/issues/53716#issuecomment-980508628

**Comment by roundhill** [comment]
I think this is by design, but I could be wrong. If the video can't be shared, then it also cannot be embedded anywhere and must be viewed at the `https://videopress.com/v/{guid}` url.

**Comment by eoinsav** [comment]
@roundhill - the main reason to uncheck the box is to remove the "SHARE" option at the top of videos (shown in first screenshot here: https://wordpress.org/support/article/videopress-embed/)

Users should still be able to embed the videos on their own site even with the share option unchecked. I think the intent is to prevent other people from sharing the video on external sites. Since the video works as expected using the `[videopress]` Shortcode there seems to be a disconnect there (looks like a `?metadata_token=` parameter is added to the working video URLs).

----

There is also an issue with the video still showing as a link even after re-checking that share option.

----

**Edit**: Not sure if this is related, but when videos are restricted to members of the site and I go to the `https://videos.files.wordpress.com/{guid}/video.mp4` link I get a `403 Forbidden | nginx` error. However, when I go to the `https://videopress.com/v/{guid}` URL and  I get this (even though I'm an Administrator on the site):

<img width="600" alt="Screen Shot 2022-08-11 at 3 10 20 PM" src="https://user-images.githubusercontent.com/35590156/184251374-54fbd022-513b-4477-9add-3af85d0c14f5.png">

**Comment by roundhill** [comment]
> Edit: Not sure if this is related, but when videos are restricted to members of the site and I go to the https://videos.files.wordpress.com/{guid}/video.mp4 link I get a 403 Forbidden | nginx error. However, when I go to the https://videopress.com/v/{guid} URL and I get this (even though I'm an Administrator on the site):

You must go to `https://video.wordpress.com/v/{guid}` if the video is private so you can authenticate.

> Users should still be able to embed the videos on their own site even with the share option unchecked.

Agreed, and I _think_ that should be working so maybe we have a bug here. It should work if the domain is the site that the videos were uploaded to. @jgcaruso would you mind poking at this when you're back?

**Comment by eoinsav** [comment]
> Agreed, and I think that should be working so maybe we have a bug here. It should work if the domain is the site that the videos were uploaded to.

It works exactly as expected when using the `[videopress]` shortcode. It just seems to be the Video Block where there is an issue.

**Comment by jgcaruso** [comment]
It looks like at some point the `for` parameter that the Jetpack/Atomic site was sending as part of the oembed request started including the http(s) protocol. This was causing the domain comparison to fail.

D85952-code is up for review to address this.

**Comment by jgcaruso** [comment]
I've deployed the above diff which should fix the issue of embeds not working for videos with Sharing disabled on the site that owns the video.

Existing posts may need to be edited/re-published in order for the oembed handler to retrieve the proper embed code.

**Comment by eoinsav** [comment]
Works for me now! Thanks, @roundhill and @jgcaruso!
