### ISSUE TITLE
Domains: Show more results button before information blocks

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#53744]
### What
In production, the "show more results button" is placed under the information blocks.
Let's display it above, like illustrated in Figma (gnYBUOBthTMckJRJr3pZmk-fi-2598%3A1)
<img width="338" alt="Screenshot 2021-07-05 at 12 06 05" src="https://user-images.githubusercontent.com/14192054/124446758-63d39200-dd89-11eb-99b0-e31fd20e1544.png">

### Why? 
From the user's perspective, it makes more sense to place it above since the new results will are going to be displayed there.

### A/C
- [ ] Render the "Show more" button above the information blocks on mobile

Related to https://github.com/Automattic/wp-calypso/issues/52905

**Comment by razvanpapadopol** [comment]
Let's leave this on hold for now. See https://github.com/Automattic/wp-calypso/pull/53700#issuecomment-862913690
