### ISSUE TITLE
Image Block: Link rel Hides or Removes noreferrer noopener Attribute

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#53740]
### Steps to reproduce the behavior

1. Create a new page or post
2. Insert Image block and add a sample image.
3. Add link to the image
4. Expand link options on the image, paste `noreferrer noopener sponsored nofollow` under "Link rel" text field.

#### What I expected to happen

All link attribute pasted under "link rel" are visible

#### What actually happened

Only `noreferrer noopener` attributes were hidden or removed. `sponsored nofollow` attributes remain.

#### Does this happen on simple or atomic sites or both?

Both

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image link 2](https://cldup.com/smgzxdckV7.png)
image link: https://cloudup.com/ccubtvlX2hP

Reported from 29849993-hc

**Comment by Robertght** [comment]
I tested this on a self-hosted website and the `noreferrer` and `noopener` attributes were automatically removed after typing them. I found [this issue](https://github.com/WordPress/gutenberg/issues/9731) to be quite similar to what we had so I'm closing this one for now.
