### ISSUE TITLE
Page template modal broken

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#53754]
- Add new page on a site with the Blank Canvas Theme
- 💥

![image](https://user-images.githubusercontent.com/87168/122245627-8e3ed780-cece-11eb-85ab-0541e340a4e2.png)
![image](https://user-images.githubusercontent.com/87168/122245648-926af500-cece-11eb-9db8-5d8ae049ec8f.png)

Core changes likely culprit in Gutenberg 10.8

![image](https://user-images.githubusercontent.com/87168/122245716-a31b6b00-cece-11eb-9a74-93011de92cce.png)

Overriding above max-height in here would help: https://github.com/Automattic/wp-calypso/blob/trunk/packages/page-pattern-modal/src/styles/page-pattern-modal.scss

Kudos @ianstewart spotting.

**Comment by WunderBart** [comment]
>Overriding above max-height in here would help

Looks like the preview column would still go under the header and get overlayed with the close `x` button? What fixes it for me is (instead altering the max-height):
- Add `padding-top: 60px` (modal header height) to the `.components-modal__content` element
- Add `background-color: white` to the `.components-modal__header` element
- Remove the `margin-bottom: 24px` from the `.components-modal__content:before` pseudo

![Jun-16-2021 17-24-58](https://user-images.githubusercontent.com/1451471/122247771-e4f4e300-cec7-11eb-962d-48fac2aa83e1.gif)

**Comment by mattwiebe** [comment]
@WunderBart nice catch, I solved it by just nudging the close button to the top right to get it out of the way in #53755
