### ISSUE TITLE
Signup: misaligned help text under account only user step

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#5376]
![](https://cloudup.com/cGAG4afi1Xk+)

repro:
1. on any browser, go to wordpress.com/account/start
2. notice misaligned help text under form

HT @rickybanister

**Comment by lancewillett** [comment]
Should it be centered instead? (Just to be 100% clear on what's broken...)

**Comment by bisko** [comment]
Fixed in #5390
