### ISSUE TITLE
[Widgets Screen] Unable to Update to Save 

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#53762]
Copypasta from https://github.com/WordPress/gutenberg/issues/32705 as, according to the issue, this might be related to WP.com instead.

### Description
When editing the Widget area under Appearance> Widgets changes can't be saved. An error message appears when you try to:

<img src="https://user-images.githubusercontent.com/7907292/122104156-5e67d500-cde5-11eb-81f1-47ceeecd210e.gif"/>

### Step-by-step reproduction instructions
1 . Follow guide to enable Widget Editor
2. Click to Appearance> Customize
3. Edit or add widgets
4. Hit update

### Expected behaviour
I expected that clicking update would make the widget changes save

### What happened

There is an error:

```
There was an error. No route was found matching the URL and request method.
```

Also reported twice below:

* p58i-axR-p2#comment-5070
* p58i-axR-p2#comment-50630

cc @sarahfg

**Comment by WunderBart** [comment]
Addressed in D63064-code

**Comment by david-binda** [comment]
The above mentioned changeset addressing the bug has actually been deployed just now.
