### ISSUE TITLE
Signup: user step on account only flow shouldn't reference "site"

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#5378]
![](https://cloudup.com/chPH6FPperQ+)

#### Steps to reproduce
1. Starting at URL: wordpress.com/start/account
2. Notice that for a user-only flow, we are referencing "your WordPress site," which is out of context for this segment
3. Alt: "Welcome to the wonderful WordPress.com community" (added .com here given this flow is accessed for JPOP services, readers, etc. and is specifically for .com user access.

HT @rickybanister

**Comment by bisko** [comment]
Fixed in #5389
