### ISSUE TITLE
Themes: Implement mobile view for auto-loading homepage confirmation modal changes

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#53797]
As an extension of the work in https://github.com/Automattic/wp-calypso/issues/53675, we will also update the design of the auto-loading homepage modal on mobile views. Since the visual theme previews described in https://github.com/Automattic/wp-calypso/issues/52792 would be potentially too cramped in a mobile setting, we will instead implement the following user improvements for mobile:

* Adding an icon to dismiss the modal in addition to the two buttons, both of which actually trigger functionality.
* Clean up the text in the same way it is being improved for desktop.
* Add a learn more link (as on desktop) to direct users to support docs.

**Comment by ianstewart** [comment]
cc @onuro

**Comment by blackjackkent** [comment]
Implemented as part of https://github.com/Automattic/wp-calypso/pull/53796
