### ISSUE TITLE
Professional Email: Confusing "You can purchase new mailboxes at the prorated price of $0.00 per mailbox" message when adding a new mailbox

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#53837]
### Steps to reproduce the behavior

1. Purchase an Email subscription for a domain you own (you will get it via a free trial).
2. Go to the screen for adding a new mailbox.
3. See a message like "You can purchase new mailboxes at the prorated price of $0.00 per mailbox":

![email-zero-dollar-proration](https://user-images.githubusercontent.com/235183/122614565-e56eb480-d054-11eb-80a8-5e67c58ce5fb.png)

It's not totally wrong (because of the free trial the mailboxes really do cost $0) but it's pretty confusing to call it a "prorated price" in this case.  I would expect to see a message mentioning something about the free trial instead.

**Comment by DavidRothstein** [comment]
Internal report: pcyqBp-4n-p2

**Comment by olaseni** [comment]
Thanks for surfacing this @DavidRothstein. We have scheduled to handle this in the nearest possible time. I have also responded on that P2.

**Comment by daledupreez** [comment]
We addressed this in #56951.
