### ISSUE TITLE
Embed icon should be vertically aligned with comments icon

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#53844]
### Steps to reproduce the behavior

1. Copy the URL of a published WP.com post
2. Create a new post
3. Paste the URL of the other post
4. Link will transform into an oEmbed card

#### What I expected to happen

I expected the embed icon to be vertically aligned with the comments icon next to it:

<img width="629" alt="CleanShot 2021-06-19 at 08 24 16@2x" src="https://user-images.githubusercontent.com/5634774/122642304-c49b7300-d0d7-11eb-9efd-716e4ebcfb62.png">

#### What actually happened

The embed icon is pushed down by about 14 pixels:

<img width="622" alt="CleanShot 2021-06-19 at 08 15 49@2x" src="https://user-images.githubusercontent.com/5634774/122642328-eac11300-d0d7-11eb-981f-c5923f5bb3b0.png">

#### Browser / OS version

Google Chrome Version 91.0.4472.106 (Official Build) (arm64) / MacOS Big Sur v11.0.1

**Comment by Cottrell217** [comment]
I would like to potentially assist you if you are willing!

**Comment by cpapazoglou** [comment]
Reserved for onboarding.

**Comment by cpapazoglou** [comment]
To reliably reproduce this, please use:
- pcdCd1-6q-p2 as the post to be embedded.
- On the block editor with theme: TwentyTwenty.

**Comment by gavande1** [comment]
Phab diff D63714-code

**Comment by cpapazoglou** [comment]
Deployed r228288-wpcom
