### ISSUE TITLE
Gallery Block: Images not being displayed in lightbox

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#53882]
One of our customers reported that images don't display in a lightbox when clicking on them while in a Gallery Block. By contrast, the images do appear to load when the gallery is a Tiled Gallery Block instead.

### Steps to reproduce the behavior

1. Go to the Gallery Block;
2. Click on either of the two images in the Gallery Block;
3. See that while the lightbox loads, and the page code indicates the images are there, the images don't actually render.

#### What I expected to happen

Clicking on an image in the Gallery Block should result in the image being displayed in the lightbox.

#### What actually happened

The images are not being displayed in the lightbox.

### Context

Report in 30251260-hc with a follow-up in 4083938-zen

#### Browser / OS version

I tested this on Firefox Developer Edition v90.0b9 on macOS 11.4

#### Is this specific to the applied theme? Which one?

I don't know. The site is using the Textbook theme.

#### Does this happen on simple or atomic sites or both?

This is a simple site.

#### Is there any console output or error text?

I noticed this console output when I clicked on an image to view it in lightbox: 299a0-pb/

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

I am only aware of this one report.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Inspecting the page when the two images should be loading:

<img width="1994" alt="Markup 2021-06-22 at 10 20 55" src="https://user-images.githubusercontent.com/2912202/122883355-ca968b80-d345-11eb-946d-1443ac8e4145.png">

<img width="2120" alt="Markup 2021-06-22 at 10 23 25" src="https://user-images.githubusercontent.com/2912202/122883366-ccf8e580-d345-11eb-8cad-494ee0ad7cde.png">

Video demo:

https://user-images.githubusercontent.com/2912202/122883497-f0239500-d345-11eb-864a-b1d1313fceb1.mp4

**Comment by synora** [comment]
Solved in 866067231. I also tested this with the Textbook theme and can confirm the lightbox is loading images as expected. A follow-up in 4083938-zen has been made.
