### ISSUE TITLE
Me: The 2fa disabled message persists while re-enabling 2fa

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#5388]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/security/two-step
2. Disable existing two-step
3. Re-enable two step

#### What I expected

During the final step of two factor (being asked to print backup codes), the message telling me that two step has been disabled is still on the screen. It should dismiss itself as soon as I start re-adding my 2fa info.

https://cloudup.com/cedmRIFbUPE

#### What happened instead

I've already re-configured 2fa at this point, so I shouldn't be told it is disabled.

#### Browser / OS version

Chrome

This may not be important to fix is #19 gets implemented. That looks like a much better solution than what we currently have.

**Comment by gibrown** [comment]
Related: after completing the config, the enabled/disabled messages pile up on each other and it is really not clear what has happened: https://cloudup.com/cEHNtcMSUDI

The "most recent message is at the top" makes it unclear what the current state is.

**Comment by lancewillett** [comment]
Closing as it's too low priority to accomplish right now. We might revisit 2FA flow entirely in the future.
