### ISSUE TITLE
Playwright: refactor ElementHandle.click() into a helper function

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#53899]
**Task Details**
In several places within `@automattic/calypso-e2e` there are code that does, in effect, something like this:

```
get elementHandle
wait for element to be stable and ready
click
```

Playwright performs [auto-wait](https://playwright.dev/docs/actionability) but turns out this is not always suitable for Calypso, as often the code executes too fast and getting dead-ended.

This should be abstracted into a helper function and all instances of the above replaced with the helper function.

**Comment by WunderBart** [comment]
> Playwright performs auto-wait but turns out this is not always suitable for Calypso, as often the code executes too fast and getting dead-ended.

We should avoid creating helpers as much as possible as they create another layer that needs maintenance and increases the entry threshold for folks that will come work on the E2Es. The stability check should be needed only for elements that are animated. Could you explain what you mean by code executing too fast and getting dead-ended? An example would be helpful here 🙏

**Comment by worldomonation** [comment]
Closing this issue as per Bart's comment, and with proper restructuring of the code we haven't needed this helper.
