### ISSUE TITLE
Ian Atomic Walkthroughs (Video 1) - /new flow has long wait while atomic site created

### ISSUE THREAD

**Issue by sethmclellana8c** [Automattic/wp-calypso#53911]
### Video information
Video 1
1:24 to 2:00

#### What I expected to happen

User knows this is expected and something is happening in the background. Some indication of progress or expected amount of wait time

See this p2 for more ideas - shortlink code: pd2C1Z-1g

#### What actually happened

When user (unwittingly) upgrades their site to Atomic, user is left for between 1-2 minutes looking at a spinning icon or a “Processing” screen while on the backend, site is upgraded to Atomic infrastructure. While there are animations, it’s unclear 1) how long user is supposed to wait and 2) whether anything is actually being done.
 
### Context

Pod work

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

5 of 5

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

In Video 1 (1:24 to 2:00)
![image](https://user-images.githubusercontent.com/37377834/123006121-d8b3ce80-d37c-11eb-8ed3-07224867dd03.png)

And in Video 4 (6:00 to 6:57)
![image](https://user-images.githubusercontent.com/37377834/123011017-4a901600-d385-11eb-8ea3-976f0be00f60.png)

**Comment by JanaMW27** [comment]
My recomendation is to use the loading screen that we are currently using for signup and we were going to use it for the marketplace. It looks like this:
<img width="570" alt="Screenshot 2021-07-15 at 14 00 46" src="https://user-images.githubusercontent.com/71137829/125784935-5957cdf9-fbac-430b-af32-de5619cb7a73.png">
The design can be found here: https://www.figma.com/file/vhlZnPqg5e5bDNcQgJ6WaN/Yoast-SEO-Premium?node-id=5479%3A26228
The only issue is to know what are the steps that we can have.

**Comment by allilevine** [comment]
> My recomendation is to use the loading screen that we are currently using for signup and we were going to use it for the marketplace. 

@JanaMW27 I've opened a PR to implement this screen in the ecommerce flow: https://github.com/Automattic/wp-calypso/pull/55073 It would be great to get your feedback / changes! 🙌 

> The only issue is to know what are the steps that we can have.

It turns out we can add any steps and any number of steps, since they don't correspond to actual status changes. The only status change we're tracking from this screen is whether the transfer has completed. Then we redirect to the thank you card.

**Comment by allilevine** [comment]
The ecommerce flow part of this issue was completed by https://github.com/Automattic/wp-calypso/pull/55073.
I've opened https://github.com/Automattic/wp-calypso/issues/55207 to address the plugins flow.
