### ISSUE TITLE
Ian Atomic Walkthroughs (Video 1) - /new flow no warning for transition to wpstaging site

### ISSUE THREAD

**Issue by sethmclellana8c** [Automattic/wp-calypso#53912]
### Video information
Video 1
1:55 to 2:10

#### What I expected to happen

User knows the url will go from mysite.wordpress.com to mysite.wpcomstaging.com

#### What actually happened

No warning site going to a staging site

### Context

Pod work

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

5 of 5

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/37377834/123009152-d3a54e00-d381-11eb-80bf-65e156a8f959.png)

**Comment by simison** [comment]
Safe to close since /new flow doesn't exist anymore :-)
