### ISSUE TITLE
Page Options: Unexpected Italian partial UI

### ISSUE THREAD

**Issue by jobthomas** [Automattic/wp-calypso#5391]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/example.wordpress.com/15
2. Go to: Page Options > Page template > Select dropdown
3. The options there are in Italian (well, I think it is)

#### What I expected

Everything else in my wp.com UI is in English (which is the language of my account, and the language of the website), so I was expecting English there as well.

Theme installed: Goran

#### What happened instead

The options showed in Italian.

#### Browser / OS version

OSX 10.11.4 - Chrome 50.0.2661.94 (64-bit)

#### Screenshot / Video

![](http://cld.wthms.co/DCKp/L5YL0WjU+)

**Comment by jobthomas** [comment]
Now is back to normal. Not sure what happened there.

**Comment by jobthomas** [comment]
While teaching at GROW! academy in Cape Town, almost all users had the same issue, this time with the dropdown being in German.

**Comment by jobthomas** [comment]
By comparison, while mine is still in German in Calypso, it's not the case in the original WP Dashboard:

![](http://cld.wthms.co/10XNa/1hwb9UNm+)

**Comment by garethallison** [comment]
Can confirm the issue @jobthomas experienced yesterday.

**Comment by jobthomas** [comment]
Safari doesn't give the problem (at the moment at least).

**Comment by SiobhyB** [comment]
Looks to be related to the reports in 7502-wpcom.

**Comment by lancewillett** [comment]
This is most likely API related (fixable on WP.com servers, not in Calypso) — so closing this in favor of the WP.com ticket.
