### ISSUE TITLE
Themes Page: Sometimes "Uploaded themes" is empty

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#53913]
### Steps to reproduce the behavior

1. Load /themes/SITE_SLUG page for one of your atomic sites.
2. Scroll down to "Show all themes" and click it.
3. Check if there are any themes under the "Uploaded themes" header. Know that your currently active theme should be an uploaded theme.

In my testing, I had found that "Uploaded Themes" did not populate for 9 out of 34 page refreshes - about 25% of the time

[Incorrect Behavior](https://user-images.githubusercontent.com/10274366/123008948-d6a43c80-d389-11eb-8b1c-35d073a663b3.png)

[Correct Behavior](https://user-images.githubusercontent.com/10274366/123008972-e15ed180-d389-11eb-8b00-351c3eb8aa4e.png)

**Comment by kwight** [comment]
@sixhours Can we close this now, with our addition of the My Themes tab?

**Comment by sixhours** [comment]
Yep!
