### ISSUE TITLE
Ian Atomic Walkthroughs (Video 1) - /new flow top menu showing

### ISSUE THREAD

**Issue by sethmclellana8c** [Automattic/wp-calypso#53910]
### Video information
Video 1
1:24 to 1:45 (and 2:23 to 2:35)

#### What I expected to happen

Only loading screen is shown (without the menu)

#### What actually happened

Top menu bar (My Sites, Reader, Write, etc) is present

### Context

Pod work

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

4 of 5

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/37377834/123005265-6e4e5e80-d37b-11eb-8007-8a8099074f23.png)

**Comment by JanaMW27** [comment]
For this, I think we should have the checkout navigation or none so the user can't start a different action while loading.
I do think we should provide a progress bar of some sort to keep the user updated on progress rather than just waiting.

**Comment by allilevine** [comment]
Separate issues:
1. Remove nav bar.
2. Figure out a way to display progress bars: https://github.com/Automattic/wp-calypso/issues/53911
