### ISSUE TITLE
Widgets Editor: Ensure Nudge comes out further when Nav Unification is enabled.

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#53947]
### Steps to reproduce the behavior

1. Enable the Widgets Editor by following the instructions under the "How to Enable the Widgets Editor" from p58i-axR-p2
2. Go to Appearance > Widgets once its enabled to load the Gutenberg Widgets Editor
3. Create a Block (e.g. just a paragraph will do) and click the Three Dots at the end of the block toolbar to reveal the context menu and then select "Add to Reusable blocks"
4. Observe the nudge appear partly behind the navigation in the bottom left

#### What I expected to happen

The nudge to come out past the navigation

#### What actually happened

The nudge didn't come out enough and was partly hidden behind the navigation

![Screenshot 2021-06-23 at 14 07 39](https://user-images.githubusercontent.com/8639742/123101898-66022c00-d42c-11eb-805e-a13fcad14ca8.png)

#### Does this happen on simple or atomic sites or both?

Both but easier to test on Simple.

#### Solutions

In order of preference

1. Make the nudge come out past the .com Unified Nav taking into account that some sites will have the smaller width core nav still.
2. Make the nudge appear over the navigation so its visible should option 1 not be achievable.

**Comment by mmtr** [comment]
@tjcafferkey can you still reproduce this issue?

I enabled the `enable-widget-block-editor` blog sticker on my test site, went to `/wp-admin/themes.php?page=gutenberg-widgets` and added a paragraph block. However I don't see the "Add to Reusable blocks" option in the block toolbar:

<img width="696" alt="Screen Shot 2021-07-28 at 16 07 37" src="https://user-images.githubusercontent.com/1233880/127336971-a2806ddb-36c6-4ac5-bea9-abbf43e0c4d7.png">

Am I missing anything?

**Comment by tjcafferkey** [comment]
@mmtr hmm, I no longer have the option to create a reusable block here. So I am unable to reproduce.

@draganescu can you confirm if the option to add reusable blocks has been intentionally removed?

**Comment by draganescu** [comment]
Yes it was removed b/c all blocks that use the entity system don't work yet in the block widgets editor.
