### ISSUE TITLE
Theme Showcase: Improve the overall user experience.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#53960]
The Theme Showcase currently only displays our "recommended" themes (those that support Headstart on theme switch), with search and everything else hidden behind a "Show all themes" button. With design input by @onuro in Figma: QnkOH11BM3MoPFOFr2OTBC-fi-150%3A2253, let's make some first step improvements.

<img width="852" alt="Screen Shot 2021-06-23 at 12 31 08 PM" src="https://user-images.githubusercontent.com/349751/123157236-2254f580-d41f-11eb-8aae-91f0baa3668b.png">

* Add a more visible top card for the active theme - #54075
* Bring search up to the top (let's keep the current `All | Free | Premium` segmentation) - #54076
* Remove the "Show all themes" button. - #54083
* Figure out what we're doing with the "Experts" banner. - #54087
* Remove the "Search by" filters for now. - #54078
* ~~Remove the dropdown from search results (just have the theme cards update). - #54077~~
* Investigate adding a Trending tab. - #54088

Some related issues:
* https://github.com/Automattic/wp-calypso/issues/52567
* https://github.com/Automattic/wp-calypso/issues/52121
* https://github.com/Automattic/wp-calypso/issues/53826
* https://github.com/Automattic/wp-calypso/issues/16440
* https://github.com/Automattic/wp-calypso/issues/40411
* https://github.com/Automattic/wp-calypso/issues/52883
* https://github.com/Automattic/wp-calypso/issues/52883

**Comment by kwight** [comment]
@ianstewart Feel free to update or improve anything in the description. 👍

**Comment by sixhours** [comment]
> Add a more visible top card for the active theme
> Bring search up to the top (let's keep the current All | Free | Premium segmentation).
> Remove the "Show all themes" button.
> Remove the dropdown from search results (just have the theme cards update).
> Remove the "Search by" filters for now.

I'm breaking this list up into bite-size issues so we're less likely to step on each other's toes and it's easier to keep track of progress. Links to new issues forthcoming. :)

**Comment by kwight** [comment]
I'm going to close this out as we've wrapped up this round of improvements, and will continue with a new set of issues. 🎉
