### ISSUE TITLE
Themes lose custom color palette when made atomic.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#53967]
### Steps to reproduce the behavior

1. Have an Atomic site and activate a theme from our showcase that supports custom color palates.
2. Check the customizer, the "Colors and Backgrounds" option will be gone entirely, or will be replaced with "Colors" that has limited functionality.

#### What I expected to happen
To see and edit the custom color palates.

#### What actually happened
Either the option is missing or has a "Colors" option that is very limited in functionality.

#### Is this specific to the applied theme? Which one?
Happens with all themes I tested: Shawburn, Carbon, Karuna.

#### Does this happen on simple or atomic sites or both?
Atomic only.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Every atomic site using one of our showcase themes that supports custom color palates on simple sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Shawburn: 
![Annotation on 2021-06-23 at 16-20-05](https://user-images.githubusercontent.com/49131029/123175802-9f906280-d43f-11eb-95b3-e8db88a7d8a6.png)
![Annotation on 2021-06-23 at 16-24-26](https://user-images.githubusercontent.com/49131029/123175821-aae38e00-d43f-11eb-911c-1174f7e5ed33.png)

Carbon:
![Annotation on 2021-06-23 at 16-27-53](https://user-images.githubusercontent.com/49131029/123176102-19c0e700-d440-11eb-801a-68eb58b7a4a7.png)
![Annotation on 2021-06-23 at 16-28-26](https://user-images.githubusercontent.com/49131029/123176133-22192200-d440-11eb-940a-a39b4435edce.png)

Karuna:
![Annotation on 2021-06-23 at 16-36-01](https://user-images.githubusercontent.com/49131029/123176709-31e53600-d441-11eb-8ee2-c26d81c0c5fd.png)
![Annotation on 2021-06-23 at 16-36-18](https://user-images.githubusercontent.com/49131029/123176721-3873ad80-d441-11eb-99a6-af30e5ebf6ac.png)

**Comment by daria2303** [comment]
4091679-zd-woothemes

Users Customizer > Colors: https://d.pr/i/Zfcpz2 - only Background color left
Mine on test site: https://d.pr/i/FC4Ixg

**Comment by JoshuaGoode** [comment]
A similar, if not the same issue, occurred previously and was fixed back in February: 485-gh-Automattic/wpcomsh

cc: @kwight

**Comment by JoshuaGoode** [comment]
Started an internal thread: p1624656369088200-slack-C02FMH4G8

I'm leaving for now. I didn't see much but I found that `custom-colors` was updated recently: 700-gh-Automattic/wpcomsh

Looks like that that didn't get deployed until 2 days ago via WPCOMSH 2.7.6.4. 

cc: @scruffian

**Comment by hacchism** [comment]
Another report with Rockfield theme - 30330631-hc

**Comment by aamills** [comment]
Also reported in 30170776-hc - Rockfield theme

**Comment by mikeicode** [comment]
Another Shawburn 30342341-hc

**Comment by mikeicode** [comment]
Another Barnsbury 4096661-zd-woothemes

**Comment by mikeicode** [comment]
Dara 29999701-hc

Only option:

![Screen Shot on 2021-06-27 at 12:36:51](https://user-images.githubusercontent.com/10353785/123552483-5c3a3a80-d744-11eb-9ea9-29e35e75af65.png)

**Comment by donalirl** [comment]
Same issue on Dara theme in #30358452-hc (and on my test atomic site too.)

**Comment by ivan-ottinger** [comment]
Another report: 17130514-hc (Maywood on Atomic)
Follow-up: 4100453-zd-woothemes

**Comment by mreishus** [comment]
Tried shawburn. After transferring to atomic, the "colors" menu in the customizer did not display. Inspecting the html revealed an inline style of display none was put on the entry:
![2021-06-28_10-14](https://user-images.githubusercontent.com/937354/123660914-b0ebbd00-d7f9-11eb-8238-09433e03e648.png)

**Comment by carladoria** [comment]
Another reported in Dara 30373017-hc

**Comment by kwight** [comment]
The PR that caused this issue will be reverted tomorrow. 👍

**Comment by aisajib** [comment]
Also reported in 30360146-hc using the leven theme.

**Comment by formosattic** [comment]
+1 4102274-zd-woothemes with Natural theme.

**Comment by sajmes** [comment]
30384080-hc - would like to be notified when resolved.

Theme: Coutoire and option completely gone in customizer.

**Comment by DanielSmithMichigan** [comment]
@andres-blanco and I have merged a pull request which we think should resolve the issue. We are waiting for the automated system to detect and deploy the patch.

708-gh-Automattic/wpcomsh

**Comment by DanielSmithMichigan** [comment]
The revert patch is in production now. 708-gh-Automattic/wpcomsh
 
Coutoire, Natural, Leven, Dara, Maywood, Barnsbury, Karuna and Carbon appear to be working correctly.

Rockfield - "Colors & Backgrounds" option shows up. But customization seems limited. This is probably a separate issue, since it works the same way on simple sites. [Simple Site Demo](https://user-images.githubusercontent.com/10274366/123831941-d39dd480-d8d2-11eb-952e-4266badebd64.mov).

Shawburn - Colors & Backgrounds option shows up, but changes aren't visible until you save and refresh.
I'm not sure if this is a pre-existing or new issue.

@kwight Should we close this issue, and make two new issues for the above? Should those above issues be a part of this sprint?

Tagging @andres-blanco for visibility

**Comment by DanielSmithMichigan** [comment]
@sajmes please see above: https://github.com/Automattic/wp-calypso/issues/53967#issuecomment-870733221. Issue should be resolved

**Comment by andres-blanco** [comment]
The issue with Shawburn also happens on Simple Site

**Comment by DanielSmithMichigan** [comment]
I'm going to close this issue; I created these two followup issues to address [the two themes mentioned above](https://github.com/Automattic/wp-calypso/issues/53967#issuecomment-870733221).

[Rockfield Followup](https://github.com/Automattic/themes/issues/4127)
[Shawburn Followup](https://github.com/Automattic/themes/issues/4126)
