### ISSUE TITLE
My Home: Changes to items in the Site setup onboarding checklist

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#53976]
In https://github.com/Automattic/wp-calypso/issues/53212 I noticed some changes to the onboarding checklist, I think these need a little more discussion, either here or privately in a P2, and then should be done in their own task(s):

"Launch your site" moved to the last item in the checklist
"Learn how to use the editor" added
"Confirm your email address" removed

<img width="777" alt="Screen Shot 2021-06-24 at 5 28 48 PM" src="https://user-images.githubusercontent.com/22446385/123207537-a687a580-d511-11eb-9bcb-37581cd444e8.png">

**Comment by autumnfjeld** [comment]
Thanks for creating this @roo2!   Good to highlight that these changes, which are part of the [My Home Pod short-term visual refresh](pd2qGl-4i-p2), are particularly significant changes to the Site setup checklist.

**Comment by autumnfjeld** [comment]
@jeffgolenski  We also need to know the "Watch video" link .  Is there a video already in existence that we are linking to?

**Comment by jeffgolenski** [comment]
Thanks for surfacing this again @roo2 @autumnfjeld 

I'm trying to recall the conversation about the video, but am failing to do so.

I think with the launch of the onboarding re-skin that was just launched, we don't need the editor task to exist here. The onboarding now drops them right into the editor to work on their homepage. Customers will [hopefully] find my home after that. This item would then be redundant.

As for the launch item, I think we should definitely move that to the end of the checklist as the final anchor item.

**Comment by autumnfjeld** [comment]
OK. confirmed we will **not add** the "Learn how to use the editor" task.

@roo2  For now let's just move "Launch your site" to the end of the checklist.

Let's also get more input on removing "Confirm your email address" before we act on that.  @p-jackson  might have insight on the importance of this task, I believe there was a discussion about email verification in a P2 post, and he created a [dedicated My Home card prompting users to verify their email](https://github.com/Automattic/wp-calypso/pull/53035).

**Comment by p-jackson** [comment]
Email verification is important, for account recovery, and potentially for spam prevention.
A couple places that have mentioned account verification.
- 114-gh-Automattic/dotcom-manage#issuecomment-668701621
- p58i-aPN-p2

I'd be ok with removing it from this setup checklist if we had a proposal for where we would show an email verification CTA instead.

**Comment by roo2** [comment]
Created a diff to move "Launch your site" to be the last item of the list

D63683-code

**Comment by roo2** [comment]
shipped D63683-code I think we can close this if we don't want to remove the "Confirm your email address" task or add the "Learn how to use the editor" task
