### ISSUE TITLE
Hide the FAB (?) icon for Store Admin pages

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#53980]
* **Hide the FAB icon for Store Admin pages** - This can be picked up immedaitely

Thanks in advance.

_Originally posted by @tjcafferkey in https://github.com/Automattic/wp-calypso/issues/50701#issuecomment-866021143_

**Comment by jordesign** [comment]
Closing this as the FAB is being removed as part of the new Help Center work
