### ISSUE TITLE
Theme Switch Modal: "Launch Site" banner is visible

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#53997]
### Steps to reproduce

1. Create a new site. Don't launch the site as public. Continue through the entire site creation process.
2. Go to the /themes page
3. Attempt to activate a recommended theme, such as Spearhead. See the theme switch modal.
4. Notice that the "Launch Site"  button/banner is visible.

#### What I expected to happen

I expected the theme preview to look like what my visitors would see if they viewed my site with the theme.

![image](https://user-images.githubusercontent.com/10274366/123303248-9957c000-d4eb-11eb-993c-4beb34913ceb.png)

**Comment by sixhours** [comment]
Fixed in r230111-wpcom
