### ISSUE TITLE
Theme Switch Modal: wrong preview when replacing homepage

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#53998]
### Steps to reproduce the behavior

1. Pick a theme using the 'Replace Homepage' feature from the modal
2. Edit the homepage heavily
3. Pick a new theme using the 'Replace Homepage' feature from the modal
4. Open the modal again in the theme from 1)

https://user-images.githubusercontent.com/375980/123304640-8d70fb80-d4f5-11eb-8b44-ab08b88c5852.mov

#### What I expected to happen
See the content I added to the homepage in 2) because that's what you get when you click on 'Replace Homepage'

#### What actually happened
I see the default theme screenshot

This problem appears because when you replace your homepage the replaced one is saved and recalled when you select the theme again.

**Comment by blackjackkent** [comment]
Let's follow up with Happiness and see if this is an issue that anyone has reported on the user side. If not, maybe we should at least update the text of the preview but this may not need further changes beyond that.

**Comment by markbiek** [comment]
Reached out to Happiness to see if this is something that's been reported.

paYKcK-1rJ-p2

**Comment by sixhours** [comment]
Based on Happiness' response I don't think this is something encountered very often. @Robertght mentioned a different issue (the time it takes to complete a Headstart on theme switch) in the P2 post but it doesn't sound like the same thing. I'm going to close this for now; please feel free to reopen if this behavior causes user-facing issues!
