### ISSUE TITLE
Signup: DSS: Display the Flickr footer attribution only if the DSS image is still in use.

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#54]
If a site is set up using a Flickr image from DSS during signup, we add a notice in the footer of the user's site:

![screen shot 2015-11-11 at 5 14 20 pm](https://cloud.githubusercontent.com/assets/349751/11107992/ce13faee-8897-11e5-83d9-5d8daf6acb9e.png)

However, if the user removes that photo from posts, or deletes the image from their media library, we need to stop displaying that footer credit.

**Comment by kwight** [comment]
DSS was removed from signup in #2580, and we have no future plans for this version.
