### ISSUE TITLE
Signup: UI jumps to top before advancing to the next step, when selecting a domain or plan

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#54015]
### Why 
This might be one of the causes of the sudden drop in mobile users completing the flow (see p1620845064285900/1620844611.285400-slack-C01VA100LEA). 

### What
After selecting a domain, the page scrolls to the top of the page **before** redirecting to the plans page. This forces unnecessary scrolling and performance drops on certain browsers/devices. This is particularly relevant for mobile devices since the reskinned UI contains more white space.

It also occurs on the non-reskin (blue) Domain step and the rest of the Signup steps where the user scrolls before making a selection to advance to the next step.

### Acceptance Criteria
- [ ] When selecting a domain or plan in `/start` signup flow after scrolling down (on mobile especially), no visible scrolling should happen. Instead, the user should just land directly at the top of the next step.

**Comment by chriskmnds** [comment]
I've added some thoughts in a draft PR [here](https://github.com/Automattic/wp-calypso/pull/54388). I am guessing the changes there could be considered irrespective of fixing the aforementioned issue or not. 

> This forces unnecessary scrolling and performance drops on certain browsers/devices.

Not sure if there is a significant performance improvement with the proposed changes. Sounds like something to profile in more detail. There are definitely fewer steps and conditioning now with a single call to `scrollTo`, but not sure if the polyfill for Safari does anything different than what we had before (so it could be just as bad in that case at least). Need to do more tests on mobile to also see how the changes behave on much longer lists.

Let's put some perspective on the alternatives/options and go from there? Do some profiling, etc.

@razvanpapadopol @alshakero - thoughts?

**Comment by razvanpapadopol** [comment]
Thanks for the exploration, @chriskmnds! 
I've updated now the description taking into consideration the latest decision in https://github.com/Automattic/wp-calypso/pull/54388#issuecomment-876928543
