### ISSUE TITLE
Reader: Emoji Topics don't work

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#5402]
Oh yes, we're going there.

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/tag/%E2%9D%A4%EF%B8%8F

Also a smiley face doesn't work either: https://wpcalypso.wordpress.com/tag/%3a (gets trimmed to just a colon) Makes me :(

#### What I expected

To find things people love!

#### What happened instead

https://cloudup.com/cgX1S4iK0sK

So much wrong.

#### Browser / OS version

Chrome.

Sidenote: I actually came across a user that is following ':)'

**Comment by lancewillett** [comment]
This seems to be working better now, testing in Mac-n-Chrome today as part of a bug scrub.

https://wpcalypso.wordpress.com/tag/%E2%9D%A4%EF%B8%8F

![screen shot 2016-10-10 at 11 14 49](https://cloud.githubusercontent.com/assets/66797/19246352/c614b4ec-8eda-11e6-9c93-f54c2a78fccc.png)

and

https://wpcalypso.wordpress.com/tag/%E2%9B%91

![screen shot 2016-10-10 at 11 13 56](https://cloud.githubusercontent.com/assets/66797/19246355/ca268a56-8eda-11e6-9fdd-03a997b9c20a.png)


both work
