### ISSUE TITLE
Ian Atomic Walkthroughs (Video 3) - Plugin’s description page continues to display after install

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54034]
### Video Information:
Video 3
6:45 - 7:40

### Summary:
1. Use a simple Business plan site
2. Click a plugin from wordpress.com/plugins
3. You will be taken to the plugin’s page, such as wordpress.com/plugins/buddypress/DOMAINCOM
4. Use the Install button to make the site Atomic
5. Note that after the plugin completes its install and activation we’re left on this wordpress.com/plugins/buddypress/DOMAINCOM page which is problematic for a few reasons:
   a. The page doesn’t hold a lot of valuable information for the customer (it continues showing the plugin’s description and may or may not have much information about actually installing/setting up the plugin).
   b. We lose the “<- Back” button which previously appeared above the plugin’s header image prior to install

### What I expected to happen:
We should be taken to a more relevant page such as the main BuddyPress page of WP Admin (for this example). A majority of plugins will have created some page in the dashboard that we can redirect to instead. If nothing else then redirecting to DOMAINCOM/wp-admin/plugins.php would likely be more ideal.

### What actually happened:
We are left on wordpress.com/plugins/buddypress/DOMAINCOM after installing the plugin with no clear next step.

### Context:
Pod work

### Level of impact (Does it block purchases? Does it affect more than just one site?):
4/5

### Screenshot / Video: If applicable, add screenshots to help explain your problem.
none

**Comment by allilevine** [comment]
Investigate: Default to redirecting to plugins.php, but see if we can redirect to specific plugin settings for popular plugins. 
Or see if we can create some kind of modal or popup message to indicate that the plugin is installed (add settings links that you would normally see in plugins.php).

**Comment by obenland** [comment]
This is resolved [by the new marketplace thank you page](https://github.com/Automattic/wp-calypso/issues/33066#issuecomment-1108514519).
