### ISSUE TITLE
Video block will not autoplay on mobile

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#54036]
### Steps to reproduce the behavior

1. Go to https://blakebays272021.wpcomstaging.com/about/ on mobile
2. Scroll down to see the video
3. See that autoplay does not run, playback buttons are still in use, and video does not loop despite settings (see below):

https://d.pr/i/EWknAp

#### What I expected to happen
Video should autoplay and loop.

#### What actually happened
Video does not act appropriately on mobile as it does on desktop.

### Context
30327434-hc

#### Browser / OS version
Tried on multiple browsers with the same result.

#### Is this specific to the applied theme? Which one?
So far the issue appears on both Rockfield and Hever, so it appears to be theme-agnostic.

#### Does this happen on simple or atomic sites or both?
Both (see Pd8ZOo-2-p2 for example on simple test site)

#### Is there any console output or error text?
"Error: Promised response from onMessage listener went out of scope 2 common.js:4:491"

Not sure if this is related to the issue.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Does not block purchases, affects more than one site

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

**Comment by kosiew** [comment]
Thanks @ClassicRKR27 for the report.
I found a related issue - https://github.com/wordpress-mobile/gutenberg-mobile/issues/1998
May I know whether your tests were on iOS or Android?

**Comment by ericamQA** [comment]
@ClassicRKR27 - do you know whether this was happening on iPhone, Android, or both?

**Comment by ClassicRKR27** [comment]
Hi all - @wpericam pointed out to me that autoplay with sound is not supported on either iOS or Android, so I'm going to go ahead and close out this issue as this is something out of our control.
