### ISSUE TITLE
Ian Atomic Walkthroughs (Video 3) - Add custom domain prompt to .wpcomstaging.com warning when going AT

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54033]
### Video Information:
Video 3
5:53 - 6:10

### Summary:
When making the site Atomic we see a prompt that states:
“Your subdomain will change from example.wordpress.com to example.wpcomstaging.com.”

### What I expected to happen:
We could enhance this from an undesirable warning prompt to a suggestion for adding a custom domain to the site.

### What actually happened:
We are only warned that this change will take place.

### Context:
Pod work

### Level of impact (Does it block purchases? Does it affect more than just one site?):
3/5

### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![issue5](https://user-images.githubusercontent.com/33190975/123459627-8bba3d00-d5b4-11eb-9695-7da68e810dbd.jpg)

**Comment by obenland** [comment]
Closing in favor of #55898.
