### ISSUE TITLE
Ian Atomic Walkthroughs (Video 3) - Caching issue with Calypso Plugins page showing after going AT

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54039]
### Video Information:
Video 3
7:37 - 7:46

### Summary:
Use a simple site with the Business plan
Install a plugin to make the site Atomic
Once the install completes and the plugin is automatically activated then click the Plugins button on the dashboard
You will be taken to wordpress.com/plugins instead of DOMAINCOM/wp-admin/plugins.php

### What I expected to happen:
Once the site is made Atomic it should always go to the WP Admin Plugins page (DOMAINCOM/wp-admin/plugins.php) instead of the Calypso page (wordpress.com/plugins). This behavior does happen after the site has been Atomic for a while. We suspect that the page isn’t being properly directed due to cache.

### What actually happened:
The site goes to the Calypso wordpress.com/plugins page.

### Context:
Pod work

### Level of impact (Does it block purchases? Does it affect more than just one site?):
4/5

### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![issue7](https://user-images.githubusercontent.com/33190975/123480553-85d25500-d5d0-11eb-918f-07a81f2cf216.jpg)

**Comment by obenland** [comment]
With the Marketplace the expectations have changed here. Plugins will now always point to Calypso's marketplace while Installed Plugins points to `/wp-admin/plugins.php`.
