### ISSUE TITLE
Ian Atomic Walkthroughs (Video 3) - Updating the featured plugins list

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54031]
### Video Information:
Video 3
2:20 - 3:23

### Summary:
We should question the “featured” and other plugins that we display on wordpress.com/plugin. Some examples:

* Akismet - already installed
* Elementor and Site Origin - Gutenberg competitors
* Classic editor - not ideal if we are recommending Gutenberg first

### What I expected to happen:
We could replace redundant/competitive plugins with others such as our own products: WooCommerce, add-ons for Gutenberg, Yoast SEO, etc.

### What actually happened:
The “featured” and other plugins displayed on this page do not seem ideal

### Context:
Pod work

### Level of impact (Does it block purchases? Does it affect more than just one site?):
2/5

### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![issue3](https://user-images.githubusercontent.com/33190975/123458994-b2c43f00-d5b3-11eb-846d-0b492b354025.jpg)

**Comment by metabreakr** [comment]
+1 Contact Form 7 competes with the Form Block.

**Comment by obenland** [comment]
This is now fixed.

The Featured area is now "Editor's pick" and accounts for plugins that are already installed
