### ISSUE TITLE
Ian Atomic Walkthroughs (Video 3) - Hardcoded plugin data (author name) incorrect

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54030]
### Video Information:
Video 3
1:53 - 2:20

### Summary:
Ian mentions that the plugin data on wordpress.com/plugins is hard coded and notes some mis-information. In this example the TinyMCE Advanced reports the author name is “Andrew Ozz” on the page. Once you click the plugin the author name changes to “Automattic”.

### What I expected to happen:
Plugin data should be consistent across all pages. This particular plugin should probably have “Andrew Ozz” as the author name, but rather than fixing the hardcoding we may want to find a better solution for displaying this information.

### What actually happened:
Author name is incorrect on wordpress.com/plugins for the TinyMCE Advanced plugin.

### Context:
Pod work

### Level of impact (Does it block purchases? Does it affect more than just one site?):
2/5

### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![issue2_2](https://user-images.githubusercontent.com/33190975/123458796-755fb180-d5b3-11eb-886f-962511ab68a4.jpg)
![issue2](https://user-images.githubusercontent.com/33190975/123458805-7690de80-d5b3-11eb-9c85-d8ca1a914f9f.jpg)

**Comment by obenland** [comment]
This is now fixed.

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/1398304/169610588-fa873564-c1c3-4166-8e4d-9375f42c808a.png">
