### ISSUE TITLE
Ian Atomic Walkthroughs (Video 3) - WP Admin’s Plugins page isn’t accessible on Free plan

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54032]
### Video Information:
Video 3
5:04 - 5:24

### Summary:
Visiting DOMAINCOM/wp-admin/plugins.php leads to a “You do not have permission to access this page” error while using the free plan.

Noting that this WP Admin page isn’t accessible from the dashboard when the site is simple. We always link to wordpress.com/plugins when the site is simple (even if “Show wp-admin pages if available” is enabled). This issue was only found when entering the URL directly.

### What I expected to happen:
The DOMAINCOM/wp-admin/plugins.php page should redirect to wordpress.com/plugins if a site is simple. (If the site is Atomic then we do show the WP Admin version of the Plugins page.)

### What actually happened:
We could not load the page and were denied permission since the site is simple.

### Context:
Pod work

### Level of impact (Does it block purchases? Does it affect more than just one site?):
3/5

### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![issue4](https://user-images.githubusercontent.com/33190975/123459360-2ebe8700-d5b4-11eb-9167-98e2ca2be2c9.jpg)

**Comment by obenland** [comment]
Fixed in 811-gh-Automattic/wpcomsh.
