### ISSUE TITLE
Earn blocks: Create Stripe customer

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#54038]
Currently, the backend of the payments blocks is not creating a customer object on Stripe connected account.

It would be better if it did.
More details here: pNPgK-5tS-p2#comment-22226

**Comment by serabi** [comment]
Feature requested in #4063765-zen

**Comment by DavidRothstein** [comment]
This would probably also fix the ability of the Earn blocks to work on Stripe accounts based in India, currently not possible due to https://stripe.com/india-data-storage-faq ("Payment information can no longer be cloned into or out of India").

See: pNPgK-5te-p2

**Comment by tellisbethel** [comment]
Ticket tied to the above https://stripe.com/india-data-storage-faq issue: 4300066-zd-woothemes
Payments Admin Orders page showing: "Payment information can no longer be cloned into or out of India"

**Comment by artpi** [comment]
> This would probably also fix the ability of the Earn blocks to work on Stripe accounts based in India, currently not possible due to https://stripe.com/india-data-storage-faq ("Payment information can no longer be cloned into or out of India").

This is more complicated
In order to make the saved credit cards work, we always clone the payment method. What I'm suggesting in this task is to saved that cloned payment method within the customer.

In order to stop cloning payment methods, we would have to reorganize how we process payments.
This would be a significant task, but it is also solved by Woo transition

**Comment by dcoleonline** [comment]
related customer report in 4718553-zen

We should notify them once payments from India can be accepted

**Comment by pauljacobson** [comment]
We also have a report in 5081098-zen

Adding details here so we can follow-up with the user once this issue is resolved.

**Comment by sirbrillig** [comment]
Assigning to @Automattic/gold now that we have a team who works on Earn features.

**Comment by millerf** [comment]
Should fix #54038

**Comment by millerf** [comment]
> In order to stop cloning payment methods, we would have to reorganize how we process payments.
This would be a significant task, but it is also solved by Woo transition


@artpi I would be happy to discuss about that! From what I gathered [in this task](https://github.com/Automattic/wp-calypso/issues/63012#issuecomment-2554039369), the only way around this would be to have Payment Platform in India and process all Indian-based blog owners with this platform account.
