### ISSUE TITLE
Ian Atomic Walkthroughs (Video 3) - WooCommerce appears in dashboard menu on AT site when it is not installed

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54040]
### Video Information:
Video 3
8:48 - 10:24

### Summary:
Make a site Atomic an any way (except by installing WooCommerce)
Refresh the browser screen to refresh the cache (or wait for a period of time)
“WooCommerce” will appear in the dashboard menu even though it hasn’t been installed

Clicking on the WooCommerce menu item will take customers through an install prompt which will install the plugin and then take them through the setup.

### What I expected to happen:
I would only expect to see new menu items appear in my dashboard if they were related to the plugin I installed.

### What actually happened:
WooCommerce appears in the dashboard navigation without being installed. If we go to this WooCommerce page we see a “Set up my store!” button which installs Woo in the background, without explicitly saying so. This process may not be completely understood by the customer.

### Context:
Pod work

### Level of impact (Does it block purchases? Does it affect more than just one site?):
3/5

### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![issue8](https://user-images.githubusercontent.com/33190975/123480670-af8b7c00-d5d0-11eb-8b14-6fefc10e4d2b.jpg)

**Comment by allilevine** [comment]
We need to verify that this should be removed.

**Comment by pablinos** [comment]
I've just been chatting to @mattsherman about this, after being pointed to #49232 by @mmtr. It sounds like this link has been in the navigation for a long time and isn't something we'd want to remove right now. If we want to have a broader conversation about changing it/removing it, then @mattsherman suggested @pmcpinto might be a good person to talk to.

So, I'll close this one for now.
