### ISSUE TITLE
Nav unification: can't access infinite scroll option if WP-admin pages toggle on

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#54054]
### Steps to reproduce the behavior

1. Go to Settings > Writing
2. Look for infinite scroll setting

#### What I expected to happen
When the default is set for wp admin pages and there are settings only available on calypso there should still be a way to get to the calypso version of the page

#### What actually happened
if you do not know the link to the calypso settings page you can't access infinite scroll settings

### Context
4095343-zen
I noticed when checking settings for a different bug

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
saw on simple

**Comment by synora** [comment]
Triaged. Can replicate on both simple and Atomic.

**Comment by kwight** [comment]
@Automattic/ajax for consideration

**Comment by tjcafferkey** [comment]
Since the launch of the Quick Switch, if a screen has both a WP Admin & Calypso counterparts you have the ability to access one or the other through the screen options tab.

More info found here: pd2C0z-4A-p2
