### ISSUE TITLE
Nav unification: The hamburger menu is displayed on mobile on Simple Sites WP-Admin

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#54069]
### Steps to reproduce the behavior

1. Go to your yoursite.wordpress.com Simple site.
2. Change to a mobile resolution
3. Notice that the hamburger menu is displayed

#### What I expected to happen
There shouldn't be any hamburger menu since on Atomic and Calypso we use the WordPress icon to open the navigation.
#### What actually happened
A hamburger icon is displayed.
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
WP-admin Simple Sites.
#### Is there any console output or error text?
No
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screenshot 2021-06-28 at 12 09 10](https://user-images.githubusercontent.com/995955/123610914-b9e48a80-d809-11eb-877f-f6f48517ec53.png)

**Comment by tjcafferkey** [comment]
RFR D63718-code

**Comment by tjcafferkey** [comment]
Deployed in r228295-wpcom

**Comment by obenland** [comment]
Is there more work for this ticket or can it be closed?
