### ISSUE TITLE
Billing: User's Receiving a Partial Refund for renewal when Full Refund should be given

### ISSUE THREAD

**Issue by rezzap** [Automattic/wp-calypso#54072]
I've come across two users in the last hour of chat that are only receiving a partial refund when doing the self-serve cancellation. 

### Steps to reproduce the behavior

1. Go to Upgrades > Cancel and issue a refund and cancellation on a recent plan renewal that only includes the plan renewal
2. Click on cancel and refund
3. You'll only receive a partial refund even though you should be due the full refund. 

#### What I expected to happen

I'd expect the full refund to be given as it does not include the domain renewal charge.

#### What actually happened

Only a partial refund was given and I had to manually process the refund in SA for the users.

### Context

Both customers had a custom domain registered that originally used free credits to register the domain, but the renewal was only for the price of the plan and did not include the domain registration. 

22991709-hc
30366039-hc

#### Browser / OS version

I don't think this applies here.

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It's possible going to give wrong refund amounts to a number of self-server users who may not be aware. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

**Comment by synora** [comment]
Triaged. I have seen this recently as well but don't have any examples at the moment. I'll keep an eye out for more reports of this though.

**Comment by kwight** [comment]
@michaeldcain is this something your team would help with?

**Comment by rezzap** [comment]
I have another report of this here: 4119084-zen

In this case the user had an expired credit card on file that got charged anyway, when the renewal was attempted to cancel it only offered a partial refund to the user they are saying.

**Comment by michaeldcain** [comment]
@kwight: taking a look.

**Comment by michaeldcain** [comment]
Responded in Slack: p1625619273470600-slack-C02BEP610

**Comment by michaeldcain** [comment]
This issue is tracked on P2 here: pNPgK-4w6-p2

**Comment by obenland** [comment]
Looks like other reports have been closed as duplicates of that P2 post. Should we do the same with this?

**Comment by ClassicRKR27** [comment]
Not sure if this is the correct place to report this as there seems to be a stream of reports elsewhere, but a teammate and I have had two reports of this in the past 24 hours:

4160793-zd-woothemes
4163897-zd-woothemes

**Comment by michaeldcain** [comment]
@ClassicRKR27 can you make sure that it's reported on the P2: pNPgK-4w6-p2

I'm closing this issue as a duplicate.
