### ISSUE TITLE
Theme Showcase: Remove "Show all themes" button in favor of tabs

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#54083]
<img width="852" alt="123157236-2254f580-d41f-11eb-8aae-91f0baa3668b" src="https://user-images.githubusercontent.com/2124984/123669979-b1d91a80-d80a-11eb-94d2-d1b22a9da57b.png">

Instead of separating Recommended and Advanced themes with the "Show all themes" button, let's sort using tabs for All, Recommended, and Advanced (to be renamed something nicer). Eventually we can add more tabs for different filters.

Related to #53960

**Comment by sixhours** [comment]
The tabs are proving tricky, but I think I'm onto a solution.

The current Recommended Themes were kinda plopped over the existing Theme Showcase infrastructure rather than being integrated into it, so they don't take advantage of search or filtering capabilities available to the "all themes" view. They have a separate query and their own actions, selectors, and reducers from the themes library as a whole, but at the core it's just a basic call to the API looking for the "Auto Loading Homepage" tag in the Showcase.

Rather than create a new query for each theme section in the tabs, we can take advantage of the filter paths like `themes/filter/[tag]/[site]`, where `[tag]` is just a tag we've added to each theme in the Showcase that we want to belong to that section.

Will keep working at it tomorrow.

**Comment by kathrynwp** [comment]
> Advanced (to be renamed something nicer)

Just throwing out a suggestion:

Conventional

**Comment by sixhours** [comment]
It came up in Slack that we probably won't add a specific tag for Advanced themes: p1624905131164700/1624902974.164200-slack-C0202PMUXLJ

Which makes sense; they'll still be under All but we want to put the best ones forward. :)

**Comment by jordesign** [comment]
> we can take advantage of the filter paths like themes/filter/[tag]/[site]

I often use this URL to send users to a specific result - so having that be the way the tabs filter results would work nicely for that use case.

**Comment by ianstewart** [comment]
> let's sort using tabs for All, Recommended, and Advanced (to be renamed something nicer). Eventually we can add more tabs for different filters.

@onuro is there an updated image for this issue that has the final phrasing and tab order?

**Comment by onuro** [comment]
@ianstewart  yes, I've labeled **Classic Editor** for Advanced on my iteration. Do we have any other suggestions for the label?

Also, are we enabling the FSE tab in this PR? Just wanted to make sure.

![image](https://user-images.githubusercontent.com/645713/124753865-2e1ddd00-df32-11eb-8696-aa3c0d9f26fb.png)

**Comment by kathrynwp** [comment]
I would strongly recommend we **not** use the wording "Classic Editor," as that is not a clear distinction since all themes still work with the Classic Editor, and the themes formerly known as "Advanced" themes also work with the block editor.

I'm not sure what else to call it, though. :) I'd thrown out a couple of suggestions earlier but none is really ideal:

- Legacy
- Other
- Older
- Traditional

and further above, I mentioned Conventional.

**Comment by kathrynwp** [comment]
Is there a reason we need to include a tab for the currently named "Advanced" themes? I'm not so sure we even need it, is there a compelling reason?

**Comment by sixhours** [comment]
> Is there a reason we need to include a tab for the currently named "Advanced" themes? I'm not so sure we even need it, is there a compelling reason?

I'm of the same mind; I don't think we *want* to point out themes that aren't our best.

**Comment by onuro** [comment]
@sixhours @kathrynwp as far as I remember, in our last mtg we discussed there may be customers that would still want to quick access a list of old editor themes. 

I also think it comes down to what we'll do with those old themes over time. Do we completely retire them in the short/medium term? If we will, +1 for no need for adding that Advanced tab.

**Comment by onuro** [comment]
Following up on that, a revised future version without he Advanced tab could maybe look like this:

![image](https://user-images.githubusercontent.com/645713/124766797-e8681100-df3f-11eb-8633-0938bef8dc48.png)

Advanced/old themes to reside in the All Themes tab.

**Comment by kathrynwp** [comment]
These are not "old editor themes" though. They are just old themes. They still work with the block editor, they just may not support every style well, like full-width alignment.

**Comment by sixhours** [comment]
@onuro I was operating from @ianstewart's comment in Slack; I don't think we're adding a tab for the non-recommended themes, just falling back to All Themes: p1624905131164700/1624902974.164200-slack-C0202PMUXLJ

**Comment by onuro** [comment]
Fair enough 😊 I was just concerned for the novice user, in terms of scenarios of what will happen if they list and choose a theme that is Old | FSE | New(not FSE).

**Comment by ianstewart** [comment]
@onuro Yes — we can come back to that when we take off our Design Selection Hats and put on our Dotcom FSE Hats when we're working with FSE teams.  :)

**Comment by sixhours** [comment]
We're 2 hours post launch and nothing has exploded. Calling this closed. :)
