### ISSUE TITLE
Can't Paste Following a SHIFT-RETURN With Gutenberg 10.9.1 Active

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#54106]
### Steps to reproduce the behavior

1. Open a post or page in the editor.
2. Copy something (a link, etc) to your clipboard
3. Add text to a paragraph block and type SHIFT-RETURN for a new line in the same block
4. Use CTRL-V to paste the contents of your clipboard

#### What I expected to happen

The contents of my clipboard to show in the block

#### What actually happened

The clipboard contents do not appear, and I get the following console error:

```
Uncaught TypeError: can't access property "length", t is undefined
```

from `index.min.js:61:1188`

<img width="1429" alt="Screen Shot 2021-06-28 at 7 27 47 PM" src="https://user-images.githubusercontent.com/42279181/123723163-12864880-d847-11eb-8bbf-73c7d545eb26.png">

### Context

The issue happens on the frontend of P2s, and I was able to replicate in the editor as well on Simple sites, Atomic sites, and a Jurassic Ninja site with GB 10.9.1 active. Deactivating the Gutenberg plugin on the Atomic and JN sites resolves the issue.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects all sites with GB 10.9.1

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Able to repo across all sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

GIF showing what happens:
![shift-return_paste_issues](https://user-images.githubusercontent.com/42279181/123724122-04392c00-d849-11eb-8c0a-59f2d2a6537c.gif)

**Comment by katiebethbrown** [comment]
Looks like this _may_ be corrected with this merge to GB 11

https://github.com/WordPress/gutenberg/pull/32527

**Comment by Robertght** [comment]
I can confirm this is a problem on my end as well and on the user's. 

Ticket: 4100337-zen

**Comment by lizswafford** [comment]
Found a similar issue on my test site. If I copy text, then use shift-return to create a new line, I can't paste the text. I'm only able to type new text.

**Comment by NoHopeRadio** [comment]
User reporting they cannot paste text into list blocks until they type a character first:

#4114454-zen

**Comment by annezazu** [comment]
I can no longer replicate this with WordPress 6.6.1 and GB 19.1. Closing out!
