### ISSUE TITLE
Reskinned Launch: Hide the "Step 1 of 1" copy

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#54118]
![image](https://user-images.githubusercontent.com/12104589/123806015-d60e2780-d8ee-11eb-8c2b-48246ee19472.png)

> On a related note, the "Step 1 of 1" looks a bit off if there's only one step cc @ollierozdarz @StefanNieuwenhuis

@StefanNieuwenhuis @niranjan-uma-shankar yeah, I don't think it's going to detract from the page if we were to hide the 'Step 1 of 1' there (above). Even for `/new` when we have 2-3 steps in the processing state, they're so fast (**and** have a progress indicator) that I think hiding the number wouldn't cause any negative movement in metrics.

_Originally posted by @ollierozdarz in https://github.com/Automattic/wp-calypso/issues/53973#issuecomment-869274437_

**Comment by razvanpapadopol** [comment]
It looks like this was fixed somewhere else.
