### ISSUE TITLE
Purchases: renewing fully expired domains

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#5411]
Suggested by @p3ob7o in p2MSmN-4Vf-p2:

If a domain has fully expired and for some reason it wasn't removed by the unsubscribe script, there's nothing the user can do from `/purchases` apart from removing the domain manually. If the domain is still available for registration, we should display a notice allowing users to "reactivate" the domain -- meaning we register it again for them.

I'm not quite sure how often this happens, since the unsubscribe script should be removing these domains as soon as they expire.

Also, cc @mikeshelton1503 and @ranh for input on the "reactivate" terminology.

**Comment by mikeshelton1503** [comment]
>I'm not quite sure how often this happens, since the unsubscribe script should be removing these domains as soon as they expire.

That's what I was wondering. Why isn't it and how often isn't it? Nonetheless I'm treating this as just a fallback state. Why not still use "Renew Now"? Yes technically it's a bit different than renew in other contexts but to the user it's the same action. I'd prefer not introduce more terminology if we can avoid it.

**Comment by fabianapsimoes** [comment]
It's hard to tell how often this happens. Maybe @matthusby can give more information, since he mentioned seeing a couple cases of this recently.

**Comment by fabianapsimoes** [comment]
In that same thread, Husby mentioned this should happen even less often, considering recent changes in the backend. I'll close this issue.
