### ISSUE TITLE
Full Site Editing: fetch theme supports flag from remote site

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#54138]
In #52981 we see that Jetpack-connected sites (Atomic, in that case) incorrectly redirect the Site Editor to the post editor. This is because the Site endpoint does not set the `is_core_site_editor_enabled` property correctly for remote sites, due to the fact that this ultimately calls down to `gutenberg_is_fse_theme`, which checks the theme for the existence of the `/block-templates/index.html` file. Since the theme is on the remote site, we cannot directly check inside the wpcom endpoint. We will have to fetch this state from the remote site itself, almost definitely through the Jetpack connection.

D63357-code is a partial solution that can check against wpcom themes, for cases where the remote site is currently running a wpcom theme. This is at least the case for a good portion of freshly-transferred-to-Atomic sites.

NB: The remote site's endpoint [already calls `gutenberg_is_fse_theme` in an expected way](https://github.com/Automattic/jetpack/blob/24d76013733ef66de87f8fe9b3e170877d33454a/projects/plugins/jetpack/sal/class.json-api-site-jetpack.php#L294-L296). We _may_ just need to remove the check against the cache site to enable its functionality.

**Comment by mattwiebe** [comment]
> We may just need to remove the check against the cache site to enable its functionality.

This theory has been disproved with a lovely run of `500` errors on my sandbox.

**Comment by Addison-Stavlo** [comment]
Closing this as outdated / resolved. Please feel free to reopen and ping if I misunderstood the current state of things.
