### ISSUE TITLE
Ovation: Full Width Video Embeds Broken

### ISSUE THREAD

**Issue by azollafox** [Automattic/wp-calypso#54137]
### Steps to reproduce the behavior

1. Open a new page and add a Vimeo block
2. Set the block to be Full Width
3. Publish the page

#### What I expected to happen

I expected what I see in the editor to match the published page

![ovation vimeo editor view](https://user-images.githubusercontent.com/7907292/123857681-a102d480-d8f0-11eb-8815-4e42fc531fa3.png)

#### What actually happened
![full width vimeo published page bork bork](https://user-images.githubusercontent.com/7907292/123857704-a6601f00-d8f0-11eb-8c80-f40836fff805.png)

#### Is this specific to the applied theme? Which one?

Ovation

#### Does this happen on simple or atomic sites or both?
Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low, just those using Ovation and Vimeo

**Comment by synora** [comment]
I'm going to close this one in favor of Automattic/wp-calypso/issues/54139
