### ISSUE TITLE
Publish Label in Gear Status Options not updated

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#54144]
### Steps to reproduce the behavior

1. Go to wordpress.com/customize and select a site.
2. Make a settings change that makes the save button switch to "Save Changes"
3. Click on the cog icon next to "Save Changes" to open the drawer.
4. See "Publish" not being replaced with "Save Changes".

### Context

https://github.com/Automattic/wp-calypso/issues/39224 introduced an update to that label. Today the JS selector throws an error, first mentioned in https://github.com/Automattic/wp-calypso/issues/44510:

```js
Uncaught TypeError: Cannot read property 'parentElement' of null
    at HTMLDocument.<anonymous> (customizer-labels-site-not-launched.js?ver=20200206:10)
```

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="745" alt="Screen Shot 2020-02-07 at 1 16 52 PM" src="https://user-images.githubusercontent.com/1270189/74066569-345e0180-49ac-11ea-9a81-af76d722e9f0.png">

See  381-gh-wpcomsh for the Atomic patch

**Comment by kwight** [comment]
@DanielSmithMichigan @andres-blanco Can you take a look please? <3

**Comment by andres-blanco** [comment]
D63656-code
