### ISSUE TITLE
Plugins: Fix redirect logic for Atomic sites

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#54143]
### Steps to reproduce the behavior

1. Go to /plugins or click "Plugins" in the nav for a Simple site
2. Switch to an Atomic site

#### What I expected to happen

To be redirected to wp-admin/plugins.php

#### What actually happened

I was redirected to wp-admin/plugin-install.php with the site id as a search term parameter.

### Context

We now always redirect from /plugins to wp-admin for Atomic sites, but we need to redirect to the correct place. The current behavior is appropriate for a specific plugin (e.g. plugins/wordpress-seo) that we want to search for and install via wp-admin, but not for /plugins in general.

https://github.com/Automattic/wp-calypso/blob/a71f5167411d11a4e49ebc9fb3dea7c4a988dcca/client/my-sites/controller.js#L253-L271

**Comment by obenland** [comment]
This should be fixed now, after the Marketplace changed the way the Plugins menu item works.
