### ISSUE TITLE
Develop Parity Between Simple and Atomic Import Options

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#54149]
### Steps to reproduce the behavior

1. Go to Tools → Import on a Simple site
2. View list of import options: WordPress, Blogger, Medium, Squarespace, Wix, Choose from full list.
3. Make the site atomic
4. Go to Tools → Import 
5. View the import options now reduced to: WordPress, Choose from full list.

#### What I expected to happen

I expected the list of import options to stay the same when upgrading to an atomic site, without options being removed. 

#### What actually happened

These options were removed:  Blogger, Medium, Squarespace, Wix. In addition, only Blogger remains in the "full list." The remaining platforms are not available at all.

### Context

#30384373-hc

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Simple:
![image](https://user-images.githubusercontent.com/30727666/123898129-18e00600-d9a8-11eb-891f-f647865e4172.png)

Atomic:
![image](https://user-images.githubusercontent.com/30727666/123898141-209faa80-d9a8-11eb-9cd2-921bef1189a2.png)

**Comment by metabreakr** [comment]
4259508-zen 

Atomic site cannot import to Squarespace.

**Comment by vishnugopal** [comment]
We're exploring this here: pcmemI-BQ-p2

**Comment by donalirl** [comment]
Parity has been achieved 🎉
