### ISSUE TITLE
Earn Section: `Learn more` link destination needs to be corrected

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#54157]
### Steps to reproduce the behavior

1. Visit https://wordpress.com/earn/payments/ on a site where Stripe is connected
2. Click the `Learn more` link

![image](https://user-images.githubusercontent.com/39308239/123939098-72443700-d9a0-11eb-980e-ef7d4c5830bd.png)

#### What I expected to happen
See the correct support page open: https://wordpress.com/support/wordpress-editor/blocks/payments/#related-fees

#### What actually happened

Link points to https://wordpress.com/support/recurring-payments-button/#related-fees that doesn't load properly

#### Browser / OS version
Chrome 91 on macOS Big Sur 11.4
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Tested on Simple for now
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/39308239/123939098-72443700-d9a0-11eb-980e-ef7d4c5830bd.png)

**Comment by Aurorum** [comment]
PR for this issue in #54166. :)
