### ISSUE TITLE
My Home: "Add a menu" task shows a Calypso tour in the customizer, but doesn't take the user to the menu controls

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#54151]
Reported p1624894628082100-slack-C01VA100LEA @ianstewart 

### Steps to reproduce

1. Go to My Home on site where site setup is incomplete
2. Click "Edit the site menu" task 
![image](https://user-images.githubusercontent.com/1500769/123910149-28724580-d9ce-11eb-88ae-8e25d5b5bb52.png)
3. Click "Add a menu"
4. Taken to the customiser and see what looks like the beginnings of a Calypso tour ![image](https://user-images.githubusercontent.com/1500769/123910165-2dcf9000-d9ce-11eb-88d8-e463ce055d20.png)
4. Click "Got it"
5. There's no follow up, where to I see ![image](https://user-images.githubusercontent.com/1500769/123910178-34f69e00-d9ce-11eb-9ade-72e8f0d35960.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low impact, but increases the chance we send the user on a wild goose chase right after they've created a new site

#### Reproducibility

When @p-jackson tested this he saw no popup in the customizer and was taken directly to the menu interface (which I think actually the expected behaviour)
<img width="1392" alt="Screenshot 2021-06-30 at 6 12 29 PM" src="https://user-images.githubusercontent.com/1500769/123910571-c1a15c00-d9ce-11eb-847a-0264d13f93b7.png">

Doing on a new account in an incognito browser might be important for reproducibility

**Comment by p-jackson** [comment]
I just reproduced this in incognito mode with a new user. I didn't reproduce when using incognito with an existing user.

So it appears to only be a bug in the brand new user experience. Which is probably the more common case.

**Comment by p-jackson** [comment]
Turns out this is just a relic of the past. The customizer menus screen used to require account verification #13017. That requirements gone, but the code is still there to prevent unverified accounts being directed to the menus UI.

https://github.com/automattic/wp-calypso/blob/a07146227d1052c23d37af70ee02b2f84951b8d9/client/state/selectors/get-menus-url.js#L27

It just needs to be removed.

**Comment by autumnfjeld** [comment]
@p-jackson Given this fix  #54345 and this ticket #54436 to explore better UX experience for new users, can we close this issue?

**Comment by p-jackson** [comment]
Yep agree, was just keeping open until we had a plan to move forward with something like #54436
