### ISSUE TITLE
Connections: Sharing / Keyring connections displaying that it was connected by incorrect user

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#54188]
Recently, we received a report that a WordPress.com on Atomic site was displaying that legitimate Google Photos and Google My Business connections were connected by the incorrect user.

After review, the user it claimed to have been connected by was a local customer without any Jetpack connection to the site and no admin privileges.  We also confirmed that the actual site owner made the original connections. 

It seems that, at least for WoA sites, the user ID can sometimes be incorrect when checked via https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/marketing/connections/connection.jsx#L250

For a11ns, please see the internal report for specific examples and findings: p9F6qB-78r-p2

cc: @tyxla 

### Steps to reproduce the behavior

We haven't reproduced the behavior consistently yet.

Here are the steps we believe would be required.

1. Connect a WordPress.com on Atomic site to Google Photos / Google My Business under Tools > Marketing > Connections
2. Create some non-WPCOM local users without Jetpack connections.
3. Check Tools > Marketing > Connections and inspect the "Connected By `username`" for changes.

#### What I expected to happen

To display the proper user account that made the connection.

#### What actually happened

An incorrect user might be displayed.

### Context

Atomic request report. p9F6qB-78r-p2

#### Does this happen on simple or atomic sites or both?

Unsure. Initial report is on Atomic.

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low but causes security concerns for users.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Unsure.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Please see the internal request for a specific example, p9F6qB-78r-p2

![image](https://user-images.githubusercontent.com/4887830/124026682-fd80f500-d9bf-11eb-9c0a-f971f4336132.png)

**Comment by tyxla** [comment]
@JoshuaGoode thanks for the ping!

Unfortunately, I was unable to reproduce. Perhaps I'm missing something?

Also, something to note - all changes I did to this area were purely cosmetic and not related to the actual logic. I'm not sure who would be better to ping here - this is from the pre-OSS era of Calypso, and the folks who worked on it are no longer with us.

Perhaps if I can have consistent instructions to reproduce then I'd be happy to further investigate.

**Comment by tyxla** [comment]
Actually, I was able to repro using a support session and the details from p2. I'm working on a fix.

**Comment by tyxla** [comment]
Got a fix in https://github.com/Automattic/wp-calypso/pull/54205 and will ship it shortly.
