### ISSUE TITLE
Better Styling for Support Documents in modal

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#54194]
In some places we currently display Support Documents an an inline modal window (`InlineSupportLink`).

<img width="1024" alt="screen-shot-2021-06-16-at-11 39 52-am" src="https://user-images.githubusercontent.com/1842363/124042539-644bf000-da4c-11eb-9433-bf7e91384098.png">

The styling is currently pretty plain and could be updated to better reflect:

* Stying seen in our Support Docs ( PEmnE-5f8-p2), or
* Styling to match Calypso style guidelines

----

I'm assuming we'll need to get some design input on the styling of these.

**Comment by autumnfjeld** [comment]
Closing this since we are now linking to the support doc page #54202.  Thank you @Aurorum  ![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)

**Comment by michaeldcain** [comment]
I think this is worth keeping open (and maybe just removing from the My Home pod's board) since we use the `InlineSupportModal` component elsewhere in Calypso, and it could really use a visual refresh.

**Comment by jordesign** [comment]
With more of these links to inline/modal docs being used now - I'm wondering if the Trail Markers pod ha bandwidth to pick this up?

**Comment by donalirl** [comment]
Just want to point out a specific issue as well. Throughout the docs there are callout blocks to highlight pieces of information, such as this from [the Media doc:](https://wordpress.com/support/media/#delete-files-from-media)

![image](https://user-images.githubusercontent.com/30727666/130542868-f918630c-7f00-47a2-bce6-81cd8084eee8.png)

They don't appear great in the modal:

![image](https://user-images.githubusercontent.com/30727666/130542850-494679a2-226b-4801-9697-1409e098ec40.png)

**Comment by donalirl** [comment]
Another issue is buttons:

On the support site:
![image](https://user-images.githubusercontent.com/30727666/130580077-d424e1d9-73af-44fe-891c-de15d9742fa7.png)

In the modal:
![image](https://user-images.githubusercontent.com/30727666/130580120-e7c6a297-c488-4fad-8a03-a4779b46d9f4.png)

**Comment by jordesign** [comment]
This will no longer be relevant with the new Help Center work that is coming
