### ISSUE TITLE
NUX: The NUX breaks when clicking the WordPress.com logo

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#5419]
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/start
2. Go through a couple of steps
3. Hit the WordPress.com logo in the top left
4. The NUX breaks

#### What I expected

Taken back to the first step? Or just don't do anything on this click. Actually, why are there any nav links in the top bar here? We are linking to /start from /start, and if you're going through this as a new user, you don't need a log in link.

#### What happened instead

I saw a mangled screen

#### Browser / OS version

Chrome latest Mac OS

**Comment by meremagee** [comment]
Ran into this as well
![](https://cloudup.com/cJrxQ7j41rg+)

**Comment by seear** [comment]
> why are there any nav links in the top bar here?

This is the standard logged-out masterbar. For example, see https://wordpress.com/design

There are difficulties switching between Calypso pages when logged-out because of the different layouts in play (see #2960). I don't fully understand the problem here, though, because the page that the logo links to should not be part of Calypso. This could be some kind of routing problem.

Best fix in the short term could be to disable the logo link when logged-out.

**Comment by lancewillett** [comment]
Wow, that's really bad — we should just unlink the logo during signup steps (other logged pages should be fine).

**Comment by seear** [comment]
> we should just unlink the logo during signup steps (other logged pages should be fine).

PR #5453 does not do the above, but instead fixes the link to point to https://wordpress.com, keeping it consistent across the logged-out pages. This is simpler than disabling the link for /start only.

Seems harmless to me, but I can change it to the disabled fix if there are strong opinions?

**Comment by seear** [comment]
#5453 didn't fix the problem on staged/prod. A proper fix would require a server-reload on the / route. 

#5454 removes the link.

**Comment by lancewillett** [comment]
Thanks @seear — confirmed in a quick test. Logo is no longer a link (tested in Mac-n-Chrome and Safari).

![screen shot 2016-05-19 at 09 50 13](https://cloud.githubusercontent.com/assets/66797/15402064/19a15f8e-1da7-11e6-8144-996e5eb433df.png)
