### ISSUE TITLE
Editor: Unclear dialog: "A more recent version of this posts exists"

### ISSUE THREAD

**Issue by bgbg** [Automattic/wp-calypso#542]
When accessing a saved draft for which a more recent version exists, the user see this dialog

<img width="395" alt="screen shot 2015-11-23 at 20 37 26" src="https://cloud.githubusercontent.com/assets/506547/11345811/1dde0964-9222-11e5-98a7-cb4053b229a8.png">

It is not clear (for me) what does "restore" mean: does it mean "restore the older and have the newer" or the other way around?

**Comment by codebykat** [comment]
Hi @bgbg! Thanks for the feedback. What would be a clearer way to phrase this? ("Restore" means "load up the more recent changes", "Close" means "ignore them and close this prompt".)

**Comment by bgbg** [comment]
How about "Get the newest"  and "Ignore more recent version"? 

Or maybe "Which version do you want to edit?" followed by two options "this one" and "more recent"

**Comment by designsimply** [comment]
This also came up in https://github.com/Automattic/wp-calypso/issues/9833:

<blockquote>This ambiguity follows when you edit an existing post. I haven’t visited the post below in 3 years. When I open it, I get a restore unsaved changes prompt. This happens for lots of my old posts.

![screen shot 2016-12-02 at 3 54 04 pm 1dde8cf8ca76495799958edac5a01ef4](https://cloud.githubusercontent.com/assets/2047747/20902970/2a96766c-baff-11e6-9e6e-bfb7d5d163b9.png)


What am I restoring? I just want to peek the post right now, not edit it, so I click “Don’t restore”. I’ll postpone dealing with it until next time I venture to this post. After reading, I click the editor’s back button to return to my posts search and receive an unsaved changes AYS (Are You Sure). That’s an interruption on the way into the post and one on the way out. Unless I restore unseen changes, I will be twice interrupted on every visit.</blockquote>

**Comment by designsimply** [comment]
This came up again in p58i-6Gd-p2 (internal ref):

<blockquote>I see the “A more recent revision of this post exists. Restore?” prompt a lot when editing published posts. Often times, I have no idea what the more recent version was, or how much it will change the post, or when I made it, or if someone else made it (?), or if I will be able to revert the change easily, or if it will publish the change before I have the chance to figure what it was. It would be super nice if there were a step in between that let me see the latest revision so I can decide from there whether to restore it or not.


![screen-shot-2017-12-18-at-mon-dec-18-12-26-57-pm](https://user-images.githubusercontent.com/1119271/34234442-70403188-e5a8-11e7-8514-87654c5ec62f.png)
</blockquote>

**Comment by designsimply** [comment]
Noting that Gutenberg likely won't affect revisions and this enhancement request is still valid.

**Comment by annacmc** [comment]
Could not repro this dialog/prompt any longer. New prompt and wording now being displayed:

![image](https://user-images.githubusercontent.com/30754158/108779464-c8a50180-75cb-11eb-845b-ea381c23822d.png)

Closing this up with tag `[Closed] Not Reproducible`
