### ISSUE TITLE
Uploading files on the Media Library on Safari is not showing the loading bar

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#54204]
### Steps to reproduce the behavior

1. On Safari, enable the `Show wp-admin pages if available` option. 
2. Go to `Media` and upload a file. 

#### What I expected to happen

See the loading bar showing that the file is being updated.

#### What actually happened

The loading bar was not displayed and there's no information that the file is being uploaded. 

### Context

Encountered this error on 29703427-hc

#### Browser / OS version

Safari Version 14.1.1 (16611.2.7.1.4) on macOS Big Sur 11.4

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Doesn't block purchases, affects more than one site.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

**Uploading a video file on Chrome:**

https://user-images.githubusercontent.com/1046943/124098019-6f0e8100-da5c-11eb-8d67-25c61fd9531b.mp4

**Uploading a video file on Safari:**

https://user-images.githubusercontent.com/1046943/124097811-37073e00-da5c-11eb-9643-a531c3a902f6.mov

**Comment by synora** [comment]
Triaged. Can replicate.

**Comment by jordesign** [comment]
Can still replicate this behaviour on Safari at `/wp-admin/upload.php?preferred-view=classic`

**Comment by mmtr** [comment]
Reopening, this still needs a counterpart fix in Jetpack (https://github.com/Automattic/jetpack/pull/21632).
