### ISSUE TITLE
Settings: "Performance" tab no longer accessible on Simple Sites

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#54220]
I was trying to help a user disable AMP on their simple site, but was not able to find the tab `My Site> Settings> Performance`. 

It is mentioned in the doc as well, on how to find that setting to disable AMP-
https://wordpress.com/support/amp-accelerated-mobile-pages/#turn-amp-on-or-off

This probably happened when we replaced horizontal tabs on settings with submenus for Nav unification ([#53774](https://github.com/Automattic/wp-calypso/issues/53774)).
Also check this Jetpack change request. [#](https://github.com/Automattic/jetpack/pull/20100/files/7032da42f73477e9b1c2cd2eb8c33000f14f9261)

### Steps to reproduce the behavior

1. Go to 'My Site> Settings'
2. See the `Performance` tab missing.

#### Does this happen on simple or atomic sites or both?
Only on Simple Sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Performance tab missing-
![Markup on 2021-07-02 at 00:16:12](https://user-images.githubusercontent.com/40609190/124175100-ccd9b200-daca-11eb-91b3-df1287dd31ee.png)

**Comment by villanovachile** [comment]
Wanted to note that our public facing doc here mentions this is only accessible on Business & eCommerce plans, but I'm not sure why. It is in fact accessible via direct link on simple sites: 

https://wordpress.com/support/settings/performance-settings/

**Comment by JoshuaGoode** [comment]
Related feature issue for the horizontal & vertical menu changes: https://github.com/Automattic/wp-calypso/issues/53774

**Comment by JoshuaGoode** [comment]
Preemptively adding to an AJAX board.

CC: @mmtr @tjcafferkey @BogdanUngureanu

**Comment by mmtr** [comment]
Seems I mistakenly removed the "Performance" submenu in [this commit](https://github.com/Automattic/jetpack/commit/8463c84690df627d6bfa3abb3e505cfd3b1325a5#diff-f28ed4934935881a801bf44892fea5a11c9bad4f4ffaa1c7bc1c297669a1a567L433) (part of https://github.com/Automattic/jetpack/pull/20147).

This is an important regression for Atomic sites which will be noticeable today once Jetpack 9.9 is released, we may want to increase the priority of this and and start working on a fix immediately. cc @tjcafferkey

**Comment by BogdanUngureanu** [comment]
LGTM, tested on Simple and Atomic sites and the submenu item is working properly! 💯
