### ISSUE TITLE
My Home: Create improved primary CTA navigation

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#54226]
**Currently:**

The Primary CTA area doesn't allow for easy browsing of recommendations in that area. Customers need to act on a CTA or dismiss it to see the next one.

![Screen Shot 2021-06-30 at 2 54 47 PM](https://user-images.githubusercontent.com/214813/124186205-f6beb480-da89-11eb-9448-8150138f1c6e.png)

**Proposed:**

![Screen Shot 2021-07-01 at 4 39 12 PM](https://user-images.githubusercontent.com/214813/124186844-e5c27300-da8a-11eb-9bb9-de9b386ddb9c.png)

Notes:
- For this change, we can retain the "hide this" logic that already present. We'll explore a better mechanism once we begin to build the "view all recommendations" list.
- The left and right arrows are part of the official WordPress Design Library icon set (gutenberg). 
- The randomly displayed card logic should stay! 
- Disabled / unselected arrows and bullet color is `gray 10` from our color studio
- Currently selected bullet and active arrows are `gray 80`

**Bonus idea:**

For mobile devices, I'd love for us to explore an off-canvas "hinted" navigation. The arrows would go away, but a sneak peak of the next card should display, so customers know to swipe to see it. 

This could be quite time consuming to build and test, I'm unsure of the dev time for this. We need to rely on true device detection and not simply break-points.

This is an optional idea for this issue, since we have more pressing things to complete! 

![Screen Shot 2021-07-01 at 4 39 58 PM](https://user-images.githubusercontent.com/214813/124187057-3508a380-da8b-11eb-8b56-2d71bd4a2dff.png)

**Comment by deBhal** [comment]
#54367 Adds the DotPager component and a bit more breathing-room to the cards. As long as we're only serving a single primary card from the backend, this component will render only minor style updates, but before we can start serving multiple primary cards to users we'll need to address three followup tasks:
- [x] Address Accessibility issues with tab order, especially where it relates to the CTA buttons hidden in the non-current cards
- [x] Address the dismiss behaviour, especially with the second-to-last card which frequently results in a big blank space.
- [x]  Address the white-space at the bottom of the smaller cards when they're in the same dotpager as the larger cards (i.e. make the pager resize for the current card)

**Comment by autumnfjeld** [comment]
@deBhal  I'm confused why you closed this.  It's the umbrella issue for the navigation feature.  The feature isn't in shipped yet.  I'm reopening it.

**Comment by autumnfjeld** [comment]
This the final diff that ships this change to production: D65266-code

With this I believe we can call this feature complete! 
cc: @deBhal @roo2

**Comment by deBhal** [comment]
Yep, it looks great! High-fives all around!

**Comment by jeffgolenski** [comment]
Looks really good. Thanks folks!!! @deBhal @autumnfjeld! The transition of the cards is super smooth.
