### ISSUE TITLE
My Home: Move scheduled quick start support session above quick links

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#54223]
When a customer has a quick start session scheduled, it takes a higher priority than quick links. Let's bump it up in the sidebar of my home!

Note: I may be exploring some different styles in the future, but for now, let's get this shipped! Current styling is okay. 

![Screen Shot 2021-07-01 at 4 14 23 PM](https://user-images.githubusercontent.com/214813/124184658-e4dc1200-da87-11eb-97a1-717cb6cc0dd9.png)

**Comment by roo2** [comment]
created a diff for this: D63628-code

**Comment by jordesign** [comment]
Closing this for now - as the number of QS sessions we still have (having discontinued them) is very minimal
