### ISSUE TITLE
Theme Showcase: Move uploaded themes to their own tab

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#54251]
<img width="1361" alt="Screen Shot 2021-07-02 at 11 07 47 AM" src="https://user-images.githubusercontent.com/2124984/124301655-1dcec200-db2e-11eb-89ef-2eb7bcf6126c.png">

I notice on my Jetpack site (and on my test sites) that my uploaded themes are listed under All Themes. This is expected, but it might be more intuitive to move the uploaded themes to their own tab in a future iteration on the showcase.

**Comment by kwight** [comment]
Done!
