### ISSUE TITLE
Nav Unification: Changer overlaps fixed position theme search

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#54252]
The new nav unification toggle menu overlaps the fixed-position search bar on the Theme Showcase and obscures the filters. This isn't as obvious now because the search functionality is hidden behind a button, but once that's moved in #54095, it will be noticeable. 

<img width="1665" alt="Screen Shot 2021-07-02 at 12 21 33 PM" src="https://user-images.githubusercontent.com/2124984/124303438-72733c80-db30-11eb-9266-8d5a971af4ef.png">

### Steps to reproduce the behavior

1. Go to `/themes/site`, click on Show All Themes at the bottom of the page
2. Scroll down the page until the search bar sticks to the top
3. Note the position of the nav unification toggle overlapping the search filters

#### What I expected to happen

The Screen Options tab does not cover the theme search and filter bar.

#### What actually happened

The Screen Options tab obscures part of the search bar and makes it tough to click on the All | Free | Premium filters.

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low-medium

**Comment by kwight** [comment]
This looks awkward, but would a better alternative be?

**Comment by andres-blanco** [comment]
One alternative would be to put the bar on higher z-index. This is what it would look like:
![2021-07-28 10 46 23](https://user-images.githubusercontent.com/375980/127333829-092ad67f-781c-483a-b735-94ec151790fd.gif)

**Comment by kwight** [comment]
@andres-blanco Oh, that's not bad – the switcher would be visible until that scroll point. @onuro @ianstewart any ideas?
