### ISSUE TITLE
GIF Block: thumbnails are not animated and no GIF can be added or previewed

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#54266]
### Steps to reproduce the behavior

1. Go to a post/page and add the GIF block
2. Type any search term and click `Search`

#### What I expected to happen
See a strip of animated GIF thumbnails and a big one below when clicking any thumbnail
#### What actually happened
Thumbnails in the strip are not animated and no big GIF is seen when clicking any thumbnail
#### Browser / OS version
*   Device: MacBook Pro (16-inch, 2019)
*   Operating system: macOS Big Sur 11.4
*   Browser: Chrome 91
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Tested on Simple Sites only so far, including P2020-themed ones, backend and frontend
#### Is there any console output or error text?

```
Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.
22 cookies
https://web.dev/samesite-cookies-explained/?utm_source=devtools
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/39308239/124349110-39050480-dbf6-11eb-8d47-5201d9882d17.mov

**Comment by inaikem** [comment]
@zdenys, I'm unable to replicate so far. Can you confirm you're still experiencing this bug?

**Browser / OS**
MacBook Pro (16-inch, 2019) / macOS Big Sur 11.3 / Chrome 91

**Site type / theme**
Premium with Blank Canvas, TT1 Blocks and Veni

**Video (TT1 Blocks)**
https://user-images.githubusercontent.com/66711744/124583943-3ae4f700-de86-11eb-95de-60c223a916a3.mp4

**Comment by zdenys** [comment]
Kind of no. I still see some inconsistent behavior with the GIF block. Some images don't load at first but then they do. So I'll close this one for now and it can be reopened if needed later. Thanks for taking a look, @inaikem!


https://user-images.githubusercontent.com/39308239/124588203-34905400-de61-11eb-8000-68b096582d66.mov

**Comment by inaikem** [comment]
Looking at how they load in, I'm wondering if this is might be service delivery/network connection issue. Happy to leave it closed for the moment, cheers!
