### ISSUE TITLE
Cover Block: Wrong rendering of Secondary Overlay color

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#54265]
I was able to reproduce this issue only with Rockfield theme in Atomic site. I tried to reproduce with some other themes, nothing of this sort was issued with other themes

### Steps to reproduce the behavior

1. Switch to Rockfield theme in Atomic site
2. In a Page / Post and add a Cover block
3. Set Overlay color as Secondary color
4. You will notice that the Cover block is green in the editor 
5. But if you preview the page / post, the secondary color is rendered

#### What I expected to happen

The selected secondary color should be shown in the editor.

#### What actually happened

The Cover block showed green color despite the selected secondary color being 

#### Is this specific to the applied theme? Which one?

Rockfield

#### Does this happen on simple or atomic sites or both?

Atomic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects AT sites

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Editor:

![image](https://user-images.githubusercontent.com/33957570/124348381-3eb71600-dc07-11eb-9c88-71ec4b476065.png)

Live page:

![image](https://user-images.githubusercontent.com/33957570/124348392-57273080-dc07-11eb-958d-b5b607ab1f2b.png)

User report: 4112883-zen

**Comment by inaikem** [comment]
Pinged @devNigel re Bugomattic and added the issue to the HE Triage board.

**Comment by Robertght** [comment]
I cannot replicate this on my end. @devNigel do you see the Secondary color as an option still?

**Comment by Robertght** [comment]
I'm closing this for now as we haven't heard back.

If the situation appears, please re-open and add more details. Thanks!

**Comment by devNigel** [comment]
I am no longer able to reproduce it either. Guess it got fixed with some other bug.
