### ISSUE TITLE
Reader Search: Combine input box and header to make it clearer?

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5426]
When using Reader Search I found having both the search input box, then a header that shows the icon with the search term I found a bit confusing, especially when scrolling down to read, then returning to the top I tried a couple of times to type into the header not realising the input box was above it (I had to scroll higher). Is there some way to combine these elements into a single row?

<img width="561" alt="reader-search" src="https://cloud.githubusercontent.com/assets/128826/15343388/939d690e-1cdf-11e6-8b5d-73c95146e76f.png">

**Comment by bluefuton** [comment]
Looks like @blowery has addressed this one in https://github.com/Automattic/wp-calypso/pull/5382 :)
