### ISSUE TITLE
Reader Search: searching by #hashtag doesn't work as expected

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5427]
When using Reader Search, searching by hashtag didn’t work as I expected which was to show posts tagged with that tag. For example, I searched for `#automatedtesting`, which showed the same results as `automatedtesting`(only 2), compared with lots of results for `automated testing`

**Comment by gibrown** [comment]
We should look at things like this more holistically. For instance there are some interesting potential features here. search.wp.com has “author:” “site:” “tag:”. We could do those, or do things like #hashtag and @author

I think we should launch the first version of search and then take a look at the data to see what users are trying to do. This sort of feature needs a lot of design thought IMO.

**Comment by gibrown** [comment]
I'm going to close this. Tag pages do now match against hashes. Search can match as well, but we really aren't every going to be able to properly tokenize "automatedtesting" into "automated testing". "#automated-testing" will work though.
