### ISSUE TITLE
Karuna: Social Links Menu disappears when setting Primary menu

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#54272]
Our customer has reported an odd error when using the Karuna theme - when they try to enable both a regular, Primary menu, and a Social Links Menu, the Social Links Menu disappears from view in the Customizer.

### Steps to reproduce the behavior

1. Go to Customizer > Appearance > Menus
2. Click on _Social Menu_, and set the menu as the Social Links Menu
3. Switch over to the _Primary Menu_ and set the menu as _Primary_
4. See the Social Links Menu disappear in the Customizer preview

#### What I expected to happen

The enabled menus should remain visible when enabled.

#### What actually happened

The Social Links Menu disappeared when enabling the Primary menu.

### Context

A report from the customer in 4091364-zen

#### Browser / OS version

The customer is using Firefox on Windows.

I tested this in Firefox Developer Edition v90.0b12 on macOS 11.4

#### Is this specific to the applied theme? Which one?

This seems to be specific to this theme on the customer's site. 

#### Does this happen on simple or atomic sites or both?

The customer's site is on a monthly WordPress.com Personal Plan. My test site is also on the WordPress.com Personal Plan.

#### Is there any console output or error text?

I captured the process in this video:

https://user-images.githubusercontent.com/2912202/124380596-2d810e80-dcc6-11eb-905c-2a9a79d16329.mp4

The error that seems to come up when enabling the menus is this one:

```
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://cl248144425.wordpress.com’) does not match the recipient window’s origin (‘https://wordpress.com’). customize.php
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

I'm only aware of one site affected by this issue.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Inconsistent: I wasn't able to reproduce this issue on a test site using the same theme.

I previewed the customer's site in a Varia theme, and I noticed that when I tried to disable the Social Links Menu, it persisted. So in a preview for that theme, the customer's site displayed the opposite behavior of the current issue.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

This is the customer's video demonstrating the issue:

https://user-images.githubusercontent.com/2912202/124380638-68834200-dcc6-11eb-8554-69aacb342a61.mp4

**Comment by Robertght** [comment]
Thank you for reporting this @pauljacobson !

I'm getting the same errors in the console but I can't seem to replicate this on my end at the moment. 
I'm asking here in case it's affected by this [issue](https://github.com/Automattic/wp-calypso/issues/53431):

p7DVsv-bZF#comment-36637

**Comment by Robertght** [comment]
We got a fix in the P2 linked above and I can confirm it's working now. 

Closing.
