### ISSUE TITLE
Ability to block other WordPress.com users from following

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#54286]
(Edited from original) In this particular situation, the user is concerned that a certain WordPress.com user is consistently liking their blog posts as new blog posts are published. It is possible that they are doing so from the WordPress.com Reader. The user wants an option to have the ability to block other WordPress.com users from following, and to remove likes on Reader when the like settings in Calypso are turned off.

User report: 4081261-zen

Originally posted to pKdGS-27k-p2.

**Comment by jordesign** [comment]
Closing this in favour of #52205. Please feel free to re-open if there's something different about this instance.
