### ISSUE TITLE
Theme Showcase: The search bar is to narrow on mobile

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#54289]
### Steps to reproduce the behavior

1. Go mobile
2. Go to '/themes'
3. Type something on the search bar
4. Click outside the text box

#### What I expected to happen
Keep seeing the search term, like this:
<img width="424" alt="can be harder to setup and c Screen Options" src="https://user-images.githubusercontent.com/375980/124492726-3be52e00-dd8b-11eb-8ee0-405cbd282db9.png">

#### What actually happened
I saw this:
<img width="397" alt="Premium" src="https://user-images.githubusercontent.com/375980/124492745-430c3c00-dd8b-11eb-86a0-8a62f462a70e.png">
I can't see what I searched for and the `Show Advanced` really takes a prominent place.

### Context
Testing with the `theme/showcase-revamp` flag enabled

### Possible paths for action

* Maybe the text toggle should be replaced by an icon of some sort?
* Another solution might be just hiding the toggle on mobile

**Comment by sixhours** [comment]
This was fixed in #54514!
