### ISSUE TITLE
VideoPress remains disabled on AT after plan upgrade from Free plan

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#54287]
### Steps to reproduce the behavior

1. Go to Store Admin and remove the plan on an Atomic site
2. Go to your site and make sure you are on a free plan.
3. Upgrade your site to a Business plan
4.Go to Jetpack > Dashboard > Settings > Performance.
5. Notice that VideoPress is disabled and cannot be enabled.
 
#### What I expected to happen
To have VideoPress enabled by default on Atomic on paid plans. On Simple sites we only support VideoPress.

#### What actually happened
The module is disabled and cannot be enabled.

#### Does this happen on simple or atomic sites or both?
Atomic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
On all Atomic sites upgrading their plan.

**Comment by DustyReagan** [comment]
Closing this issue because I was unable to reproduce it. I suspect it may have been fixed by Limited Atomic work replacing plan checks with feature checks.

**Comment by BogdanUngureanu** [comment]
Thanks @DustyReagan, this indeed should be closed. It was fixed by the back-end plan refresh done when the user purchases another Atomic compatible subscription.
