### ISSUE TITLE
Coming Soon Badge not shown correctly on wp-admin interface

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#54298]
There are two problems: 

#### In wp-admin for a simple site, the "Private" badge is shown instead of "Coming Soon"
We should see a "Coming Soon" badge here.
There also seems to be an [ issue with the style of the badge](https://github.com/Automattic/wp-calypso/issues/51788).

<img width="473" alt="Screen Shot 2021-07-06 at 9 11 26 am" src="https://user-images.githubusercontent.com/22446385/124523356-2549e000-de3a-11eb-959d-c2ed56c8f92e.png">

#### On wp-admin for atomic sites, the badge is not shown at all.
<img width="620" alt="Screen Shot 2021-07-06 at 8 35 02 am" src="https://user-images.githubusercontent.com/22446385/124523887-35fb5580-de3c-11eb-81a0-c5fd2d2450d4.png">

I Originally noticed this investigating https://github.com/Automattic/wp-calypso/issues/51119

I wonder how we've missed this until now, I notice I didn't mention the wp-admin interface in my testing notes around badges https://github.com/Automattic/wp-calypso/pull/47399#pullrequestreview-529713674 🤭

**Comment by autumnfjeld** [comment]
We'll break this into two tickets:
Estimate:
 - simple sites: Size S
 - atomic sites: Size M (due to hassle of testing)

Difficult to test. 
 - Self-hosted sites wouldn't have this
 - Atomic developer sites

**Comment by roo2** [comment]
both issues closed with https://github.com/Automattic/jetpack/pull/20319
