### ISSUE TITLE
Theme Showcase does not retain position when browsing themes

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#54294]
### Steps to reproduce the behavior

https://user-images.githubusercontent.com/545779/124511213-3859a300-dd9b-11eb-83fa-d1c1255dc828.mov

#### What I expected to happen

Scroll position would be retained when browsing.

**Comment by sixhours** [comment]
This appears to have been fixed at some point over the last couple weeks:

https://user-images.githubusercontent.com/2124984/126370969-5a55d163-79ea-4bdc-8996-054641535deb.mov
