### ISSUE TITLE
Theme Showcase: autofocus on mobile after clicking filters on search bar

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#54291]
### Steps to reproduce the behavior

1. Go on mobile to `/themes/[YOUR_SITE]`
2. Click on a filter on the search bar (Premium or Free is the same)
3. See that the filter bar disappear and the text area is focused

I think on mobile it might be a good idea to not focus the text field after clicking a filter. This way you wont get puzzled when the filters disappear.

**Comment by markbiek** [comment]
@andres-blanco I'm not sure I understand the issue here. Do you have a screenshot or recording or anything?

**Comment by andres-blanco** [comment]
Things have changed since Jul 5, 2021. Thankfully, the issue is no longer with us.
