### ISSUE TITLE
Reader Search: returning to reader search clears the results but keeps the input

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5429]
When using Reader Search, either clicking (desktop) or returning to (mobile) Search when already having done a search clears the search results but keeps the input.

The only way to show results again is entering/removing characters, the enter/return key doesn’t work on this field

<img width="796" alt="safari" src="https://cloud.githubusercontent.com/assets/128826/15343471/72a40d24-1ce0-11e6-9cee-ec4c5f62fee6.png">

**Comment by blowery** [comment]
@alisterscott What was the exact path you followed here? I'm currently unable to repro.

**Comment by alisterscott** [comment]
@blowery: I can no longer reproduce. Closing this.

**Comment by blowery** [comment]
@alisterscott thanks!
