### ISSUE TITLE
Purchases: Update link to "Manage Plan" on Plans page

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#543]
The button to manage your plan upgrade on wordpress.com/plans still links to the old "my upgrades".

![image](https://cloud.githubusercontent.com/assets/448298/11345950/21d63d82-91e8-11e5-881d-db114987b4b1.png)

ht @rickybanister

**Comment by matthusby** [comment]
Imported from #199 
We need to update all "My Upgrades" copy and links:

![image](https://cloud.githubusercontent.com/assets/12596797/11276990/6794bf6c-8eb2-11e5-92f1-7fd635907fbf.png)

Including the "Manage upgrade" links:
![image](https://cloud.githubusercontent.com/assets/12596797/11277022/970613d6-8eb2-11e5-85bf-85eeda80cd03.png)

**Comment by stephanethomas** [comment]
We should also update links in the API. I'm thinking for example of error messages that display a link to the former `My Upgrades` page.

**Comment by scruffian** [comment]
@stephanethomas I moved this that https://github.com/Automattic/wp-calypso/issues/903
