### ISSUE TITLE
Button Block: Default styles does not make any changes to the button

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/wp-calypso#54307]
#### Steps to reproduce

1. Open a page/post edit
2. Add a button block
3. Select a drop-down option from the Default Styles settings
4. There are no changes reflected on the button block

#### What I expected
The Outline option should actually remove the background color of the button

#### What happened instead
No changes were reflected on the button

#### Browser / OS version
Chrome Version 91.0.4472.114
MacOS Big Sur Version 11.3

#### Screenshot / Video
![Screen Capture on 2021-07-06 at 11-41-22](https://user-images.githubusercontent.com/44837596/124563324-fdb24200-de50-11eb-8b31-46116ea2b888.gif)

#### Context / Source

Tested this during the Empathy flow team testing

**Comment by Robertght** [comment]
The way I understand this feature is that styles(Fill/Outline) should update as soon as they are changed, however, the default styles can't render a change as it should work with any new button blocks added after the change.

The button block updates the styles on my end correctly.

@poojashetty18 can you take a look and let me know if you're seeing another issue instead?

cc @yansern for a second look on the behavior of the default styles.

**Comment by poojashetty18** [comment]
Thanks for clearing that up! I wasn't aware that the default style would only apply to new buttons and not to the existing ones. We may probably need to update the support docs to clarify this.

**Comment by Robertght** [comment]
I'm closing this one as there are no further reports, but please open it again if needed.
