### ISSUE TITLE
Vimeo Block - Embeds Before Entry Content

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#54304]
I am unable to reproduce this even when copying the exact code from the user's site but I can confirm that this is happening on their simple site.  Opening this in case anyone else sees this and we are able to replicate it. 

### Steps to reproduce the behavior
1.) Add a Vimeo Block to a page
2.) View the page and observe that the Vimeo Embed is added in a `<figure> `tag above the `.entry-content. ` 

![Markup on 2021-07-06 at 12:54:50](https://user-images.githubusercontent.com/24914028/124540202-dad85b80-de59-11eb-82bd-72e31eb782a2.png)

Workaround - For some reason, if we include both a shortcode block with the Vimeo code as well as the Vimeo block, then the shortcode version will appear normally. Including either one or the other only does not work.  We can then provide CSS to hide the duplicate video.  

![Markup on 2021-07-06 at 13:22:51](https://user-images.githubusercontent.com/24914028/124541887-4cfe6f80-de5d-11eb-880c-7684ecccd5f4.png)

#### What I expected to happen
The Vimeo Block would appear where it is added in the Block Editor.

#### What actually happened
The Vimeo embed is appearing outside of `.entry-content` instead. 

### Context
4104191-zen

#### Browser / OS version
I can see this issue on the page in Firefox, Chrome, Safari. 
Theme - Ovation

#### Does this happen on simple or atomic sites or both?
Simple Site

#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Seems to only be affecting this one site and I cannot reproduce yet. 

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Not currently reproducible

**Comment by Robertght** [comment]
Thank you for reporting this @joweber123! I wasn't able to replicate this locally using **Ovation**, however, I was able to add a new page with the same content and the video would show up correctly markup-wise.

~I'm checking with the user if they need further help with this, otherwise, I think this may be a one-off glitch.~

Closing for now, but please reopen if we can replicate this consistently.
