### ISSUE TITLE
Editor: Safari console errors 'Deprecated attempt to access property 'URL' on a non-WebSocket object.'

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5431]
Safari (Version 9.1 (11601.5.17.1) OSX) is showing lots of console errors on the editor.

Everything still seems to work in the editor - it's just that lots of errors: `Deprecated attempt to access property 'URL' on a non-WebSocket object.'` are being shown.

I have tried WordPress.com both proxied and unproxied and the same errors show.

#dogfooding

![safari errors](https://cloud.githubusercontent.com/assets/128826/15344190/0b381e20-1ce8-11e6-8e86-818007ca3d8a.png)

**Comment by lancewillett** [comment]
Re-testing this during a bug scrub: cannot reproduce.

<img width="1906" alt="screen shot 2016-10-10 at 11 17 23" src="https://cloud.githubusercontent.com/assets/66797/19246424/285a1ca0-8edb-11e6-8477-6c8c8672088f.png">


Feel free to re-open if you see it again in the future.
