### ISSUE TITLE
Gallery Block - Link to setting not working

### ISSUE THREAD

**Issue by tarunvijwani** [Automattic/wp-calypso#54322]
### Steps to reproduce the behavior

1. Go to post or page editor
2. Add gallery block
3. Add media to the block
4. Change the link to settings to attachment page/media/none

#### What I expected to happen
- Link to feature should work on the published page or post

#### What actually happened
-  Link to feature is not working on the published page or post

#### Browser / OS version
- Chrome / Mac OS 11.4

#### Is this specific to the applied theme? Which one?
No, issue exists on all themes

#### Does this happen on simple or atomic sites or both?

Tried only on a simple site. 

#### Is there any console output or error text?

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://public-api.wordpress.com') does not match the recipient window's origin ('https://widgets.wp.com').

#### Screenshot / Video: 

https://user-images.githubusercontent.com/11503784/124639753-2a467800-deaa-11eb-8153-17730b30b40a.mov

**Comment by as-esu** [comment]
I could reproduce the issue as well using Firefox 90.0.1 (64-bit) on Windows 10
A user reported the issue here: zen-4163792

**Comment by Robertght** [comment]
I just encountered a similar case. It happens everywhere, so I'm not entirely sure what's the purpose for **Link to: none**. The carousel still pops up for example.

I reckon we can transfer it to Jetpack.

Can we get more insights on this @jeherve ?

**Comment by jeherve** [comment]
> It happens everywhere, so I'm not entirely sure what's the purpose for Link to: none. The carousel still pops up for example.

The carousel feature, when enabled, does indeed take over that setting, and the Carousel modal is displayed at all times. This is done on purpose.

We've discussed how this could be changed in this issue: https://github.com/Automattic/jetpack/issues/11264

I'll close this one as duplicate.
