### ISSUE TITLE
Name Your Site walkthrough message overlaps confirmation and save settings button

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#54326]
### Steps to reproduce the behavior

1. Go to `https://wordpress.com/home/`
2. Click on `Name Your Site`
3. Change the Site Title
4. The confirmation message that the title was saved successfully and the Save settings button are overlapped by the message.

The overlap of the save button in particular is frustrating if you want to make other changes while on the page as you have to scroll very specifically to get it visible.

#### What I expected to happen

To see confirmation the change was saved and be able to save other changes.

#### What actually happened

The confirmation message was overlapped and it was difficult to save further changes.

#### Browser / OS version

Chrome 91.0.4472.114 OS X

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both as it's in Calypso

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent the first time you follow the Name Your Site walkthrough. The message doesn't appear if you revisit it.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot 2021-07-06 at 1 00 11 PM](https://user-images.githubusercontent.com/1900444/124644863-b8960c00-de60-11eb-8440-91dd96cab42a.png)

**Comment by heavyweight** [comment]
This is not reproducible for me anymore
