### ISSUE TITLE
Editor: Slash command doesn't clear when / deleted

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#54330]
### Steps to reproduce the behavior

1. Create a new post
2. Type the / block inserter shortcut
3. Remove the /

#### What I expected to happen

The / window to be hidden

#### What actually happened

The / window persisted until I pressed delete a second time and can jump around if you click away and back into a block area. This can lead to overlap on narrower content areas.

### Context

Empathy testing

#### Browser / OS version

Chrome 91.0.4472.114 OS X

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot 2021-07-06 at 1 28 38 PM](https://user-images.githubusercontent.com/1900444/124649067-02352580-de66-11eb-861f-d207d9cb29dc.png)

**Comment by Robertght** [comment]
Thank you for reporting this @kriskarkoski !

I was able to replicate this on a self-hosted WordPress site so I'm closing this in favor of this:

https://github.com/WordPress/gutenberg/issues/33246
