### ISSUE TITLE
Editor: adding youtube on mobile device shows embed wider than editor

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5433]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/ (on mobile device)
2. Paste YouTube URL eg. https://youtube.com/watch?v=5GL9JoH4Sws
#### What I expected

YouTube embed shows the width of editor
#### What happened instead

YouTube embed is wider than editor. This makes it difficult to enter text _after_ the embedded video
#### Browser / OS version

iPhone 6+ iOS 9.2 Safari
#### Screenshot / Video

![youtube embed](https://cloud.githubusercontent.com/assets/128826/15344725/7fd6f95a-1cec-11e6-9fcb-5f0e0347582c.png)
# dogfooding

**Comment by designsimply** [comment]
Tested and confirmed this is still an issue using iPhone 6S, iOS 11.1.2.

Video: [27s](https://cloudup.com/cjlk0lv1FR7)

<img width="320" alt="screen shot 2017-12-07 at thu dec 7 10 07 37 am" src="https://user-images.githubusercontent.com/1119271/33728162-ca8af60e-db36-11e7-829b-b4884ee291cc.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11537 using iPhone 6S, iOS 11.1.2.</sup>

**Comment by alisterscott** [comment]
Confirming still an issue but blocks in Gutenberg should fix this, so as OP I am happy to close

#bug-scrub #pre-gutenburg-bug-purge
