### ISSUE TITLE
Checkout: Do a better job clarifying the difference between monthly/annual/biannual pricing during upgrades

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#54341]
### Steps to reproduce the behavior

1. Buy a plan (e.g. a Premium plan).
2. Go to upgrade to a higher plan (e.g. Business).
3. Edit the order.
4. See something like the screenshot below:

![upgrade-edit-cart-current](https://user-images.githubusercontent.com/235183/124691728-49450a00-deaa-11eb-990e-432968a4431b.png)

It's working as expected, but the design and numbers are a bit confusing.  For example, the "one year" option shows the price difference between 12 months of a monthly subscription ($396) and 1 year of an annual subscription ($300) to the Business plan.  Then on top of that, there is also a $96 discount (bringing the price down from $300 to $204 for the annual subscription) because the user is upgrading from a Premium plan.  That discount isn't included in the monthly-vs-yearly comparisons, because the percentages really wouldn't make much sense (at least not without some careful thought on how to present them).  But as is, the numbers are still confusing.

Originally noticed by @xpurichan (p1625579934450000-slack-C02BEP610)

### Solution

I can think of a couple ways to improve this.

First, instead of "Save X%" maybe it should say something like "Save X% vs. monthly billing"?

Second, maybe we could do something visually to highlight the link between the $33, $300, and $499 (to show that they are all pre-discount prices) and then visually highlight the $204 (next to one of the $300s) differently, since it's the after-discount price.

To go further, one could actually imagine putting the $300-$96=$204 discount on its own line in checkout instead, below everything else (similar to other discounts like coupons), and get rid of the crossed-out "Discount for first year" behavior entirely.  That might also help emphasize that it's a one-time discount due to the upgrade only, and nothing to do with the actual product price.  That was suggested at one point while discussing this originally, I think (p1613673088222500-slack-CT1FP5D62) -- we didn't do it then because we were really just trying to fix a regression and restore the original behavior at the time.  But it might be a good change.

**Comment by michaeldcain** [comment]
This is probably a lower priority, given that users don't generally interact with the term picker in Checkout. The best quick fix is probably to say "Save XX% over monthly" in the term picker discount messages. Bigger fixes (like pulling the overall discount to its own line item) would involve changing the way our shopping cart endpoint works.

**Comment by sirbrillig** [comment]
I think that this is covered by https://github.com/Automattic/wp-calypso/issues/65968 (and may in fact no longer be an issue after https://github.com/Automattic/wp-calypso/pull/65998)
