### ISSUE TITLE
Editor: uploading .m4a files results in 'file type not supported' error

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#5435]
A user in 2670241-t reported that uploading `.m4a` / `.m4v` files to the Editor results in the following error message:

![screen shot 2016-05-18 at 2 04 58 pm](https://cloud.githubusercontent.com/assets/10125810/15352450/e23b49a6-1d01-11e6-8226-ebff6289ab71.png)

> 1 file could not be uploaded because the file type is not supported.

This happens both when the file is uploaded via drag and drop, or via the `Add New` button, and I was able to reproduce this issue on both Mac and Windows, using Chrome / Firefox / Safari.

`.m4a` / `.m4v` files can be uploaded via WP-Admin's Editor or Media Library, and once embedded in a Post, play without a problem. 

The user's site, as well as all test sites I used, had the necessary upgrades to upload and use audio and video.

Also just making a note that this issue is limited to `.m4a` / `.m4v` files. `.mp4` files upload without an issue in the Calypso Editor.

**Steps to reproduce**
1) Make sure your test site has a plan, or a legacy space upgrade (and therefore supports audio/video uploads)
2) Create a new Post / open an existing Post in the Editor.
3) Upload a `.m4a` or `.mf4v` file via drag and drop or the `Add New` button.

Please let me know if you need any other info. Thank you!

**Comment by aduth** [comment]
Suspected regression of #5407, cc @gwwar @robobot3000 

I'm finding that I'm also unable to upload mp3 files. Following the logic, we're trying to determine the file extension from the mime type `audio/mp3`, but the mp3 extension mime type defined in our constants is `audio/mpeg`. I'm not sure we should be trying to determine the file extension from mime time when we have the file name available.

**Comment by gwwar** [comment]
Interesting, this is a chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=227004

**Comment by alexjgustafson** [comment]
Another report of this in #376831-chat

**Comment by chaitanyamsv** [comment]
Another report in 16632696-hc
