### ISSUE TITLE
Theme Showcase: Update One-Page Filter for Themes like Blank Canvas

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#54356]
Blank Canvas is by far the best theme for creating a one-page site or landing page, but it does not appear in the "one page" filtered theme search results:

https://wordpress.com/themes/filter/one-page

Can it be added?

**Comment by ianstewart** [comment]
Moved it and updated the issue.

**Comment by ianstewart** [comment]
I just added it. :)
