### ISSUE TITLE
Video Block: Video height is taller than video leading to black bars

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#54351]
### Steps to reproduce the behavior

1. Add a video block to a simple site or, add columns and then add a video block in a column
2. See the issue

#### What I expected to happen
The video block should only be the height of the video block

#### What actually happened
The block is actually taller than the video and the extra space is taken up by black bars. This should be visible in the editor and on the front-end of the site.

![Markup on 2021-07-07 at 15:05:39](https://user-images.githubusercontent.com/22053773/124764454-42afa480-df35-11eb-8418-730770c2e75b.png)

### Context
Experienced in 30384827-hc and replicated on a test site. This is only impacting simple sites that I can see and was replicated on multiple themes.

It seems very similar to this old bug that was fixed - https://github.com/Automattic/wp-calypso/issues/46890

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Likely impacting all simple sites.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

**Comment by inaikem** [comment]
@apeatling would you be able to confirm if the above is a reoccurrence of #46890? Thanks! 🙏

**Comment by apeatling** [comment]
Added to our backlog to investigate in an upcoming sprint.

**Comment by philnick206** [comment]
Another report #4122323-hc

**Comment by apeatling** [comment]
I don't think we are going to get to this very soon. @roundhill is this something your team could look at?

**Comment by roundhill** [comment]
Sure, added to our backlog.

**Comment by roundhill** [comment]
Seeking @cpapazoglou's advice on this one! Looks like https://github.com/Automattic/jetpack/pull/17464 added some code that adds some CSS classes to restrict the block to a certain aspect ratio. I think what we're seeing here is videos that are not fitting a 'standard' aspect ratio like `16:9`, so the black bars show up.

It seems to me like everything is working fine if I disable these `wp-aspect-ratio` classes, videos get resized in the column blocks even if they have uncommon aspect ratios:

<img width="651" alt="Screen Shot 2021-07-26 at 4 35 04 PM" src="https://user-images.githubusercontent.com/789137/127067996-f6f3a0a6-6610-43c9-a011-243b7834fd57.png">

Maybe something was fixed along the way and we don't need this aspect ratio check anymore? It could be the new VideoPress player that we launched late last year that is based on video.js.

**Comment by cpapazoglou** [comment]
> Seeking @cpapazoglou's advice on this one! Looks like [Automattic/jetpack#17464](https://github.com/Automattic/jetpack/pull/17464) added some code that adds some CSS classes to restrict the block to a certain aspect ratio. I think what we're seeing here is videos that are not fitting a 'standard' aspect ratio like `16:9`, so the black bars show up.
> 
> It seems to me like everything is working fine if I disable these `wp-aspect-ratio` classes, videos get resized in the column blocks even if they have uncommon aspect ratios:
> 
> <img alt="Screen Shot 2021-07-26 at 4 35 04 PM" width="651" src="https://user-images.githubusercontent.com/789137/127067996-f6f3a0a6-6610-43c9-a011-243b7834fd57.png">
> 
> Maybe something was fixed along the way and we don't need this aspect ratio check anymore? It could be the new VideoPress player that we launched late last year that is based on video.js.

👋 @roundhill, the current behavior is certainly different than the one I got when developing Automattic/jetpack#17464. It seems that reverting that implementation produces better results now (not perfect though)

Before | After
-------|------
 ![](https://cln.sh/rsYrNH+)| ![](https://cln.sh/FYRWTe+)

**Comment by roundhill** [comment]
Thanks @cpapazoglou! I'll see if I can get those black bars to go away w/o the CSS classes added.
