### ISSUE TITLE
Plans: Update text for two-year plans

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54355]
### Steps to reproduce the behavior

1. Add a two year plan to your test site via SA or through the normal checkout flow. In my example I am using a two year Premium plan.
2. Visit https://wordpress.com/plans
3. Note the pricing on this page shows a monthly breakdown price based on the breakdown of our two year plans (this makes sense, since we're on a two year plan currently), but the text indicates "per month billed annually".

#### What I expected to happen
I expected to see the wording written something like "per month, billed once per two years", because the price shown reflects this. This is not the price breakdown that is equivalent to our one year annual plan.

#### What actually happened
We found text indicating that the pricing was reflective of our annual plan, and the pricing shown was reflective of our two year plan.

### Context
This was found during pod testing and discussed in Slack (p1625579934450000-slack-C02BEP610).

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-07-06 at 9 58 31 AM](https://user-images.githubusercontent.com/33190975/124805550-aaf88900-df29-11eb-8a45-9095f879b525.jpg)

**Comment by vaish567** [comment]
I would like to work on this issue.
