### ISSUE TITLE
Account Settings: unable to add or edit account recovery phone number

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#54376]
### Steps to reproduce the behaviour

1. Go to https://wordpress.com/me/security/account-recovery
2. Click on the `Edit` or `Add` button for the recovery SMS number

#### What I expected to happen
To be able to set a phone number for account recovery

#### What actually happened
The screen goes completely blank. Pressing the browser's back button returns to the previous screen I was on before navigating to the Account Recovery screen.

### Context
Reported by a user in https://wordpress.com/forums/topic/sms-recovery-not-working/

#### Browser / OS version
Confirmed in latest versions of Firefox, Chrome, Safari and Edge on MacOS 11.4

#### Is there any console output or error text?
Console shows two errors the moment the button is clicked:

<img width="1091" alt="Account_Recovery_—_WordPress_com" src="https://user-images.githubusercontent.com/11873759/124868902-c2368580-dfc0-11eb-8ec2-61489af95177.png">
<img width="1086" alt="Account_Recovery_—_WordPress_com-2" src="https://user-images.githubusercontent.com/11873759/124868908-c498df80-dfc0-11eb-9156-364782ea9717.png">

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all users, but especially those who use 2FA and want a recovery phone number set up.

**Comment by chrisfromthelc** [comment]
Another in 4122737-zd

**Comment by sanjeev00733** [comment]
Another report in #30542876-hc
Follow up 4126815-zen

**Comment by flootr** [comment]
A fix is up at https://github.com/Automattic/wp-calypso/pull/54404; seems like this was caused by a change in https://github.com/Automattic/wp-calypso/pull/54282 (specifically [this file](https://github.com/Automattic/wp-calypso/pull/54282/files#diff-c9bd6d9f21af5ae916601d3f4f694ea79e28265a6cb99b1f99bd5451be65044d), thanks @razvanpapadopol for the pointer).

**Comment by KokkieH** [comment]
It's fixed now in production. Followed up with the users who reported this.
