### ISSUE TITLE
Image upload block: Uploading .webp with .jpg infinite load in chrome, hard freeze in firefox

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#54377]
Related but not the same: #30426.

### Steps to reproduce the behavior

If you view and save a webp file as a jpg, for instance hit cmd+s at this URL:

https://dotcompatterns.files.wordpress.com/2021/04/stocksnap_qjo8nshmnx.jpeg?w=781

And then try to upload it in an image block, in chrome, the block gets stuck in an infinite loading state with no error shown, in firefox the entire block editor freezes requiring a page reload before things are clickable again.

There is a console error pointing to: "Sorry, this file type is not permitted for security reasons."

This is the same error you receive properly in the image block if you attempt to upload a webp file with the webp extension directly.

It looks like the serverside error isn't being handled on the front end unless we expect it in the first place based on the filename / extension.

I suspect a similar issue is happening in #30426 where we expect the file to be valid based on the file name but then its not on serverside inspection of the mimetype.

This may be a Gutenberg bug but testing on a .org site, it doesn't seem to have the same restrictions on webp.

While uploading an invalid or misnamed file you should expect some kind of error, freezing the editor seems like something we could be handling better.

#### Screenshot / Video: 

https://user-images.githubusercontent.com/811776/124871239-24b27480-e007-11eb-9911-faab691e5c2c.mp4

**Comment by lsl** [comment]
@sixhours should this also go in dotcom manage project?

**Comment by sixhours** [comment]
@lsl 👋 I'm not sure! I think since it has the Needs triage lable, the quality squad will take a look and triage it to the appropriate team/pod, though.

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I have not been able to recreate this issue so far on Simple, AT, or Self-hosted. Tested with Firefox 100 on macOS and Chrome 101 on macOS. Steps taken:

1. Opened https://dotcompatterns.files.wordpress.com/2021/04/stocksnap_qjo8nshmnx.jpeg?w=781 and cmd+s to save image. This saved it as a webp file
2. I also exported the file on my mac to a JPEG version
3. Opened Test sites and created new page with image blocks
4. Dropping either the WEBP image or the JPEG image version resulted in the image being uploaded to the site without issue.
5. Checked Media Library and all images show as uploaded there as well: 

<img width="1133" alt="Markup 2022-05-26 at 11 29 30" src="https://user-images.githubusercontent.com/27249804/170553095-88ffa23c-df2a-4032-97c4-16b40c487653.png">

<img width="1118" alt="Markup 2022-05-26 at 11 30 01" src="https://user-images.githubusercontent.com/27249804/170553143-5b2d46a3-ea9f-4489-9b58-9c2dcc8fe33a.png">

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
- @lsl , I was not able to replicate this issue in FireFox or Chrome, so I've closed for the moment. Can you check the steps I took to reproduce the issue and see if I am doing anything different than you?

**Comment by lsl** [comment]
Looks like its fixed, Firefox is also saving it with a webp extension now too.
