### ISSUE TITLE
Subscriptions: subscribers not getting confirmation email when subscribing

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#54381]
### Steps to reproduce the behavior

1. Go to http://baskervillepups.com/
2. At subscription widget, test subscribe with these emails 29ba4-pb/ <- pb link

#### What I expected to happen
Logstash to show emails sent to both

#### What actually happened
No emails were sent

#### Does this happen on simple or atomic sites or both?
Simple site

#### Context

4124096-zd-woothemes

**Comment by jeherve** [comment]
Transferring this issue to the Calypso repo, since the issue impacts a WordPress.com site.

**Comment by jeherve** [comment]
Closing this now. For reference, this was resolved here:
p1625715784201500-slack-C0299DMPG
