### ISSUE TITLE
Theme Showcase: Add an FSE beta tab under the FSE feature flag.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#54389]
With some site editing features active on Horizon, let's add a tab to the new Theme Showcase for filtering FSE-compatible themes. This tab UI will need to be behind the existing FSE feature flag (`gutenboarding/site-editor`).

<img width="1074" alt="Screen Shot 2021-07-08 at 8 18 48 AM" src="https://user-images.githubusercontent.com/349751/124948102-412dbd00-dfc5-11eb-8f88-ed36a1e323d1.png">

The themes to be included are the FSE themes currently in Horizon signup behind the flag, accessible at https://horizon.wordpress.com/new?flags=gutenboarding/site-editor

**Comment by jordesign** [comment]
Nice - I'm excited for this!

Is 'Full Site Editing' definitely going to be the labeling/terminology we use on WPCOM? @ianstewart

**Comment by mreishus** [comment]
The current filter implemented by https://horizon.wordpress.com/new?flags=gutenboarding/site-editor uses an attribute that's set on designs (not themes) that is specific to the gutenboarding data: [Example](https://github.com/Automattic/wp-calypso/blob/21bb09874f244accd3fe6845c4973c553521c90d/packages/design-picker/src/available-designs-config.json#L14). We're going to need a theme tag, like `auto-loading-homepage` or `block-templates`, that can be used to create the new tab.

Looking at the tags for seedlet and twenty-twenty-one, I'm not seeing any FSE related tags in the "Theme Features" box:
![2021-07-15_14-41](https://user-images.githubusercontent.com/937354/125847696-2a75b931-0c72-4263-bb68-9bff5775ad88.png)

So I think we'll have to make a new tag that we can use to filter. Does that sound right? @kwight @sixhours

**Comment by sixhours** [comment]
Yep, I think that's the right idea @mreishus; that's how the Recommended themes are fetched, too. :)

**Comment by sixhours** [comment]
Looks like this is being worked on in #54713

**Comment by mreishus** [comment]
Hm, yes, I also have a different implementation using react-query (but it has no badge): https://github.com/Automattic/wp-calypso/pull/54698/commits/3a3b1f99915e1a3021d44fd4171515cd03614593
