### ISSUE TITLE
Theme Showcase: Move the segmented selector out of the search bar.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#54392]
It's visually odd to have the segmented repo selector contained within the search bar itself; let's move it out and to the right.

<img width="1100" alt="Screen Shot 2021-07-08 at 9 55 35 AM" src="https://user-images.githubusercontent.com/349751/124962022-fc108780-dfd2-11eb-9c5b-bd92fa175bd1.png">

cc/ @onuro @ianstewart

**Comment by kwight** [comment]
This will also need mobile treatment (also see https://github.com/Automattic/wp-calypso/issues/54246#issuecomment-876724717)

**Comment by mreishus** [comment]
We've implemented this in #54514.
