### ISSUE TITLE
White screen after checkout - Quick Start offer does not load + console error.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#54396]
### Steps to reproduce the behavior

This happened to me twice in a row:

1. Go to My Site - Switch Sites - Add New Site - Give it a name (anything) - Add a domain mapping subscription - Select a plan - Go to checkout - Make the purchase.
2. After purchasing, I get a white screen:

![image](https://user-images.githubusercontent.com/30731356/124982079-2a9a5c80-dfeb-11eb-8070-06afa4bd7929.png)

The console error is:

![image](https://user-images.githubusercontent.com/30731356/124982141-3c7bff80-dfeb-11eb-8854-8da859bc334e.png)

> Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    nl https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    enqueueSetState https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    setState https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    fr https://wordpress.com/calypso/evergreen/checkout.2c7c3cd73d2a832d081f.min.js:1
    componentDidUpdate https://wordpress.com/calypso/evergreen/checkout.2c7c3cd73d2a832d081f.min.js:1
    ua https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    jl https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    unstable_runWithPriority https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Ho https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    _l https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    al https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Yo https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    unstable_runWithPriority https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Ho https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Yo https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Go https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    ll https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    notify https://wordpress.com/calypso/evergreen/79571.44ac27a5da1cf9778b98.min.js:1
    notifyNestedSubs https://wordpress.com/calypso/evergreen/79571.44ac27a5da1cf9778b98.min.js:1
    handleChangeWrapper https://wordpress.com/calypso/evergreen/79571.44ac27a5da1cf9778b98.min.js:1
    m https://wordpress.com/calypso/evergreen/63156.14ade85c56827a066865.min.js:2
    i https://wordpress.com/calypso/evergreen/entry-main.b2e80efc8c1569735e7d.min.js:2
    v https://wordpress.com/calypso/evergreen/entry-main.b2e80efc8c1569735e7d.min.js:2
    S https://wordpress.com/calypso/evergreen/29613.2c5d744976336c3bd281.min.js:1
    enhancer https://wordpress.com/calypso/evergreen/91411.705a45fd24df864d9ee9.min.js:2
    w https://wordpress.com/calypso/evergreen/entry-main.b2e80efc8c1569735e7d.min.js:2
    d https://wordpress.com/calypso/evergreen/entry-main.b2e80efc8c1569735e7d.min.js:2
    v https://wordpress.com/calypso/evergreen/29613.2c5d744976336c3bd281.min.js:1
    t https://wordpress.com/calypso/evergreen/79571.44ac27a5da1cf9778b98.min.js:1
    dispatch https://wordpress.com/calypso/evergreen/63156.14ade85c56827a066865.min.js:2
    o https://wordpress.com/calypso/evergreen/checkout.2c7c3cd73d2a832d081f.min.js:1

Refreshing doesn't change anything, and I still get the white screen upon refresh. I get no confirmation of purchase, and the URL is for a Quick Start Session offer that never loads.

#### What I expected to happen
The purchase to go through, and I'm assuming, the Quick Start Session offer to load.

#### What actually happened
The purchase goes through, but I get no confirmation, and I get a white screen with no quick start session offer loading.
#### Browser / OS version
FireFox Dev edition, MacOS
#### Is there any console output or error text?
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    nl https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    enqueueSetState https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    setState https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    fr https://wordpress.com/calypso/evergreen/checkout.2c7c3cd73d2a832d081f.min.js:1
    componentDidUpdate https://wordpress.com/calypso/evergreen/checkout.2c7c3cd73d2a832d081f.min.js:1
    ua https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    jl https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    unstable_runWithPriority https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Ho https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    _l https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    al https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Yo https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    unstable_runWithPriority https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Ho https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Yo https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    Go https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    ll https://wordpress.com/calypso/evergreen/51865.7f066b3455a8a911a695.min.js:2
    notify https://wordpress.com/calypso/evergreen/79571.44ac27a5da1cf9778b98.min.js:1
    notifyNestedSubs https://wordpress.com/calypso/evergreen/79571.44ac27a5da1cf9778b98.min.js:1
    handleChangeWrapper https://wordpress.com/calypso/evergreen/79571.44ac27a5da1cf9778b98.min.js:1
    m https://wordpress.com/calypso/evergreen/63156.14ade85c56827a066865.min.js:2
    i https://wordpress.com/calypso/evergreen/entry-main.b2e80efc8c1569735e7d.min.js:2
    v https://wordpress.com/calypso/evergreen/entry-main.b2e80efc8c1569735e7d.min.js:2
    S https://wordpress.com/calypso/evergreen/29613.2c5d744976336c3bd281.min.js:1
    enhancer https://wordpress.com/calypso/evergreen/91411.705a45fd24df864d9ee9.min.js:2
    w https://wordpress.com/calypso/evergreen/entry-main.b2e80efc8c1569735e7d.min.js:2
    d https://wordpress.com/calypso/evergreen/entry-main.b2e80efc8c1569735e7d.min.js:2
    v https://wordpress.com/calypso/evergreen/29613.2c5d744976336c3bd281.min.js:1
    t https://wordpress.com/calypso/evergreen/79571.44ac27a5da1cf9778b98.min.js:1
    dispatch https://wordpress.com/calypso/evergreen/63156.14ade85c56827a066865.min.js:2
    o https://wordpress.com/calypso/evergreen/checkout.2c7c3cd73d2a832d081f.min.js:1

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent for me. One teammate was able to reproduce as well.
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Screenshots above.

**Comment by wpshellbelle** [comment]
Able to replicate this consistently. I tried purchasing the Business plan, Premium plan, and Personal plan and saw the same error. Here is a video of the error: 


https://user-images.githubusercontent.com/77413972/124983520-e60fc080-dfec-11eb-8f3c-6c4ad6e418d7.mov

**Comment by kwight** [comment]
@michaeldcain @sirbrillig Is this maybe related to your team?

**Comment by sirbrillig** [comment]
Thanks for the ping. Should be fixed by https://github.com/Automattic/wp-calypso/pull/54400
