### ISSUE TITLE
Start Tour button flows outside of the container

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#54398]
### Steps to reproduce the behavior

1. Create a new/fresh site, then go to the editor for a new post. 
2. A tour will appear in the bottom left corner. The Start Tour Button styling pushes it outside of the box:

![image](https://user-images.githubusercontent.com/30731356/124982971-3d616100-dfec-11eb-8703-5fbfad2de66c.png)

3. If you click to start the tour, the Next button also gets pushed outside of the box:

![image](https://user-images.githubusercontent.com/30731356/124983023-4fdb9a80-dfec-11eb-81cd-d651b59cd0f4.png)

#### What I expected to happen
The button to not be pushed outside of the box
#### What actually happened
The button appears half in the box, and half out.
### Context
Empathy testing
#### Browser / OS version
Firefox Dev Edition (latest version)/ MacOS
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Screenshots above.

**Comment by inaikem** [comment]
A new issue was raised in #54445, which has been marked as complete. Tested to confirm it is now fixed.
