### ISSUE TITLE
NUX: can we remove the i18n bar in absence of i18n evidence

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5439]
I am seeing the i18n prompt about WordPress being available in other languages. I've tested this in production, logged-out, without proxy and without the tunnel to make sure this isn't just an automattician-only thing.

![i18n prompt](https://cloudup.com/cNCEaZ2PS4N+)

I understand we want people to be aware of this capability, but shouldn't it be based on some user-agent or IP based data? There isn't anything about my visit that I'm aware of to suggest I am a German speaker. Aber dass stimmt, und Ich spreche ein bischen Deutsch. But it really seems like a lucky guess.

Have we tested this to make sure it's not hurting our NUX conversion? The page in general has so many visual elements and words all around "WordPress.com, Sign Up, Log In, Step 1 of 5, i18n, title, paragraph, label....", I'd be really surprised if we couldn't lift conversion by simplifying this quite a bit.

cc @meremagee

**Comment by rachelmcr** [comment]
@rralian do you have German listed anywhere in your browser language settings? If you have a non-English language as a secondary language in your browser, you'll see that prompt. (Related: #622)

**Comment by rralian** [comment]
@rachelmcr It looks like I do. Though I don't recall ever adding German, nor can I think of why I would have done so. Does it add a language if google offers to translate it for you and you elect not to do so?

**Comment by rachelmcr** [comment]
I tested that out, and if you tell Chrome to never translate a language it will indeed add that language to the browser language settings.

**Comment by rralian** [comment]
So would you consider this a non-issue (and therefore closeable)? Would be interesting if we had stats to show how common the secondary language setting is, though I suppose there's really no telling how often it's an error.

**Comment by rachelmcr** [comment]
The language prompt is working as expected here, but I wouldn't argue against testing its impact on NUX conversion and looking more at stats around how often the prompt appears and how often users click on it. :)

**Comment by davoraltman** [comment]
@rachelmcr I have a case in 3096859-t where clicking on the link _Deutsch_ does nothing. I was able to reproduce this in Chrome at https://wordpress.com/start/design-type-with-store?ref=homepage/de

**Comment by alisterscott** [comment]
I was able to see the Deutsch link by changing my browser language settings and can confirm it is working as expected. Closing this issue now, we can test NUX conversion separately.

<img width="875" alt="screen shot 2017-07-18 at 12 43 57 pm" src="https://user-images.githubusercontent.com/128826/28298496-f1e9d390-6bb6-11e7-91e4-b922e9cbce56.png">
