### ISSUE TITLE
Customizing email notifications when publishing blog posts

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/wp-calypso#54402]
**What**
The ability to customize the email notifications (sent to followers/subscribers) when blog posts are published.

**Why**
User requested this feature here: 30528687-hc (Atomic / Business plan site) without the need of using a plugin.

**Customer feedback:**
"I was extremely unhappy with the message sent out by WordPress, as if WordPress were me. The message was full of inappropriate and inconsistent content - not rude, just dumb. I really am not used to organizations sending out mail, while pretending to be me and then saying things that do not make sense and using words like "Howdy" which I would never use. It was full of inconsistencies - first it was sent to me, in my email, by "me," which is silly. Secondly, it says to the recipient "you have followed this post" but I think there's no such thing as following a "post", only a blog or a website or maybe a comment. It was not something I could ever possibly have written to anyone. What is the need to pretend to be me -- especially if the content is irritating and irrational? Why not send it from WordPress itself, since that's who sent it and it is an advertisement for WordPress? I've been using WordPress for eleven years. I'm a huge fan of Wordpress and I recommend it to everyone who is online dong anything. But this notification is a mistake. Please don't pretend to be me (without telling me). Please have a look and change something. I am grateful for WordPress. Thank you for all that is beneficial that you do! All the best!”

**Comment by autumnfjeld** [comment]
~This seems like a great issue to look into.~   @p-jackson  @jordesign @ianstewart .  First understanding what this would entail.  I'll have to get educated on email systems.

EDIT: sorry guys, I was trigger happy,  should have done the vetting first, see my comment below.

**Comment by autumnfjeld** [comment]
This is the email  that my follower-account received from my blogger-account.

The complaints from the[ user mentioned](30528687-hc)  include dislike of the word"Howdy",  and the phrase "follow a post".   These did not appear in my email.  

![image](https://user-images.githubusercontent.com/5665959/128433865-e47bdff3-595a-4372-ae2a-76028b9bd723.png)

From my perspective the email is very benign, very neutral.   That said. The task here would be to give users the ability change these emails.

Is this a project we want to pursue?

**Comment by jordesign** [comment]
I feel like there's potentially a suite of things we could address about the current notification emails. If we were to take this on - I'd also be interested in looking into whether we can toggle notifications on/off per post as mentioned in https://github.com/Automattic/wp-calypso/issues/44263

**Comment by jordesign** [comment]
There's also the bigger questions of:
1. Customizing design (like having your own logo)
2. Being able to send emails to your list other than post-notifications.

They may well be beyond our scope - but worth considering Post notifications holistically I think.

**Comment by p-jackson** [comment]
> I think there's no such thing as following a "post"

There is on P2. Maybe this email was sent after they'd _commented_ on a post, and that caused the post to be followed?

**Comment by jordesign** [comment]
Yeah - could be. If they'd opted in to be emailed with follow up comments.

**Comment by kwight** [comment]
I also don't see any "howdy" at all:

<img width="750" alt="Screen Shot 2021-08-10 at 2 22 53 PM" src="https://user-images.githubusercontent.com/349751/128937479-e9593ea2-7374-4125-8cec-74850d19ba7e.png">

> Maybe this email was sent after they'd commented on a post, and that caused the post to be followed?

... but I did find a reference to "follow one of my posts" by commenting on an ordinary Atomic post (not P2) – still, no "howdy":

<img width="1072" alt="Screen Shot 2021-08-10 at 2 26 36 PM" src="https://user-images.githubusercontent.com/349751/128937610-0ed11590-15ea-41f9-945f-037e7dda2645.png">

**Comment by kwight** [comment]
There are definitely some references to "howdy" in our email template codebase, but it's tough to see what gets used for what (or if the template is even active for anything). 🤔 Regardless, Giving users any customization of templates will require a dedicated, careful project.

**Comment by kwight** [comment]
@adelineyaw Oh! @saygunnyc also pointed out that we've got these Settings > Reading options:

<img width="1160" alt="Screen Shot 2021-08-10 at 3 29 35 PM" src="https://user-images.githubusercontent.com/349751/128943249-c7a53284-8aa7-4a3e-87d8-782d87120e77.png">

It looks like the default values include "howdy". 😬

**Comment by saygunnyc** [comment]
Thank you, @kwight for the ping! Yes, definitely. And, below is a screenshot from a confirmation email with "Howdy".

<img width="1381" alt="Confirmation" src="https://user-images.githubusercontent.com/78876323/129046197-7fc06767-1be7-4272-bb9d-c3a7c549f9bf.png">

**Comment by kwight** [comment]
I could see the default wording being easily tweaked to remove the awkward "howdy" and possessive "my" references.

**Comment by mdrockwell** [comment]
Another user asked about this feature:

> 

is there also a way to change how the emails look when people are notified?


4286081-zd-woothemes

**Comment by kelasante** [comment]
Another user in 38405004-hc asked for email customization options. Specifically the option to remove [New post] from the email subject line and to remove the logo/Site Title from appearing in the post notification emails.

**Comment by simison** [comment]
These templates have since been improved significantly.
