### ISSUE TITLE
Reduxify: excludedSteps (signup)

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#54417]
**Task Details**
The current [Flows object](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/config/flows.js#L153-L238), even if it's considered config, has a stateful property: `excludedSteps`.

All the signup steps are getting `flows.getFlow().steps` as a prop so it's expected for it to cause a re-render when updated. In cases when a step is removed dynamically by calling `flows.excludeStep()`, the UI is not immediately updated.

This is currently blocking https://github.com/Automattic/wp-calypso/pull/54117#issuecomment-878117715

**Comment by autumnfjeld** [comment]
@razvanpapadopol Is this still an open issue? Is it something Ganon could help out with?

**Comment by razvanpapadopol** [comment]
Yes, @autumnfjeld, this is still an issue in the `/start` framework. I've just re-checked and [this comment](https://github.com/Automattic/wp-calypso/pull/54117#issuecomment-878117715) continues to be applicable. 

Right now it impacts a specific scenario (paid plan + free domain) in the `/start/launch-site` flow, but we'll need this to work if we plan to introduce other flows where steps get excluded dynamically.

**Comment by arthur791004** [comment]
@razvanpapadopol  Oh, I have already kept `excludedSteps` in the redux store in this [PR](https://github.com/Automattic/wp-calypso/pull/60609). As I'm not sure is there any side effect, I only apply to flows with branching steps and those flows will restore the excluded steps to `flows.excludedSteps`. Maybe we can try always reading `excludedSteps` from redux store and remove `flows.excludedSteps`.

But for https://github.com/Automattic/wp-calypso/pull/54117, could we just check `isPaidPlan` to hide the explainer?

**Comment by razvanpapadopol** [comment]
> Maybe we can try always reading excludedSteps from redux store and remove flows.excludedSteps.

Absolutely! I don't see why that wouldn't work 👍🏼

**Comment by razvanpapadopol** [comment]
The [cause for this task seems to be fixed](https://github.com/Automattic/wp-calypso/pull/54117#issuecomment-1036329420) and `excludedSteps` has been reduxified in https://github.com/Automattic/wp-calypso/pull/60609 so we can close this one 🎉

**Comment by alshakero** [comment]
Sooo happy to see this finally live!

**Comment by razvanpapadopol** [comment]
Not live yet but thanks to excellent sleuthing from @arthur791004 it's getting there 👯
