### ISSUE TITLE
Desktop app: Only loads a blank screen with WP logo

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#54428]
We've received reports from two users that after updating to the newest version of the desktop app, when it launches they only see a blank screen with the WordPress logo top left, and the help icon bottom right.

### Steps to reproduce the behavior

We've not been able to reproduce it so far, but one of the users have provided app logs as requested in https://github.com/Automattic/wp-calypso/issues/53220#issuecomment-876589428

### Context
Report in https://wordpress.com/forums/topic/getting-error-on-desktop-app/page/2/#post-3701274

Follow-up emails in 4126895-zen and 4126894-zen

Log file in 170966-pb

cc @nsakaimbo

**Comment by KokkieH** [comment]
Looks like there's also an issue for this in https://github.com/Automattic/wp-desktop/issues/988

**Comment by nsakaimbo** [comment]
@KokkieH Thanks for sourcing the application logs - we're still looking into this. One additional troubleshooting step (not sure if they've tried this already):

Can the user try uninstalling the app - _including all caches_ - and then re-installing the application? Instructions for a complete uninstall are located here: 

PCYsg-6LX-p2

**Comment by nsakaimbo** [comment]
@KokkieH It's also unclear to me whether this happens only when they try to use the editor? From what I can tell, the user is trying to load the editor on boot. What happens when they click the "W" button in the top-left?

**Comment by nsakaimbo** [comment]
Closing this issue as this is being tracked in Automattic/wp-desktop/issues/988.

Please share subsequent updates in that issue.
