### ISSUE TITLE
Mobile Browser: Welcome guide doesn't have option to close on mobile browser

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#54426]
### Steps to reproduce the behavior

1. Open the website on a mobile browser. I've checked this with Chrome browser.
2. Open WordPress.com > My Sites > Pages > Add New Page (and select blank layout) or a Post. 
3. Click on the three dots on top right corner and open Welcome guide. 
4. You'll see the welcome guide is shown. It is spread all across the screen and doesn't have the option to close it at all.
5. Now even if I create a new page/post, the welcome guide is being shown, not allowing me to close it at all and makes the mobile browser experience not usable.

#### What I expected to happen
After opening the Welcome guide is opened it should have the option to close it.

#### What actually happened
The Welcome Guide is spread across the screen and doesn't have the option to close.

#### Browser / OS version
Mobile browser. Checked on Chrome and Firefox.

#### Is this specific to the applied theme? Which one?
Nope, happens on the editor.

#### Does this happen on simple or atomic sites or both?
Simple sites only.

#### Is there any console output or error text?
Couldn't check on the mobile browser.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects the editor on mobile browsers across the site 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/7382505/125152022-d23c9980-e167-11eb-9797-6c2c6323adfb.mp4

Firefox:
![Screenshot_20210710-101335](https://user-images.githubusercontent.com/7382505/125152035-db2d6b00-e167-11eb-91e8-15d1d6dd6654.jpg)

**Comment by kosiew** [comment]
Hi @galakhyati ,

Thanks for reporting this and the detailed steps.
