### ISSUE TITLE
Penscratch 2: SVG image doesn't load as featured image

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#54427]
### Steps to reproduce the behavior

1. In `WordPress.com > My Sites > Appearance > Customize > Content Options` and check the box next to `Automatically use first image in post`
2. Create a post and add an .svg image as an [Image Block](https://wordpress.com/support/wordpress-editor/blocks/image-block/) at the very top (you can use https://s-ssl.wordpress.com/i/spotify-badge.svg)
3. Preview the post

#### What I expected to happen
See the featured image load normally
#### What actually happened
The featured image doesn't load
### Context
Encountered in 29996749-hc
#### Browser / OS version
Any
#### Is this specific to the applied theme? Which one?
Yes, Penscratch 2
#### Does this happen on simple or atomic sites or both?
Tested on Simple Site so far
#### Is there any console output or error text?
```
Failed to load resource: the server responded with a status of 400 () https://i2.wp.com/s-ssl.wordpress.com/i/spotify-badge.svg?resize=656%2C300&ssl=1&crop=1
```
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/39308239/125166670-5bbe8c80-e1a5-11eb-8bf0-2ceff3f3ee9c.png)

**Comment by kosiew** [comment]
Hi @zdenys ,

Thanks for reporting this and the detailed steps.

I checked this for you and svg is not a supported image type.
Are you able to reproduce adding an svg image on a simple site?

[Supported Image File Types](https://wordpress.com/support/images/#image-file-types)

**Comment by kwight** [comment]
True, this would need to be reframed as a feature request (we can't upload SVGs to the media manager either for the same reason).
