### ISSUE TITLE
Using "Play Inline" on the Video Block Setting on an AT site breaks the video block.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#54433]
### Steps to reproduce the behavior

1. On an AT site, insert a video block and turn on the "Play Inline" setting.
2. The screen will refresh, and the setting is still off.
3. Turn it on again.
4. Preview the page
5. The video will be replaced by a long link that goes to the video attachment page.

#### What I expected to happen
The video to play inline

#### What actually happened
The video block breaks and must be deleted and re-added.

#### Browser / OS version
Tested with FireFox 89, Mac OS 11.4

#### Does this happen on simple or atomic sites or both?
Atomic Sites

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all Atomic Sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://d.pr/i/8DkWb6 (Recording was too big to embed)

**Comment by inaikem** [comment]
Thanks for reporting the issue, @KirkwallDay 🙏

I was unable to replicate this on my AT sites. I inserted a video block, selected a video, enabled the "Play Inline" block setting and was able to save/preview/view the post as expected. There was no refresh on my side after enabling the "Play Inline" setting.

I tested on macOS 11.3, Chrome 91, Firefox 89 and 90. Would you be able to test again on your site with user plugins disabled?

I'm going to close this as not replicable for the moment but please reopen it again if needed.
