### ISSUE TITLE
Block Editor: Toolbar hides under block settings panel when content doesn't fit

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#54435]
### Steps to reproduce the behavior

1. Open a page or post in the editor
2. Add a columns block and choose the 1/3, 1/3, 1/3 option
3. Set the columns block to full width (if the theme has the option, like Hever) or to simulate the effect, just make the browser window smaller
4. Add an image to each column
5. Select the third image and try to reach the ... icon in the block toolbar just above the block

#### What I expected to happen

To be able to select the ... icon

#### What actually happened

The block toolbar is partially hidden, under the block settings panel on the right, so it's not possible to select the ... (or any of the other hidden options; this varies depending on screen resolution/window size)

If your OS is set to hide scrollbars by default, it's especially confusing, as it's not obvious how to access the missing toolbar options, as in the following screenshot (System Settings set to "Show scrollbars: automatically based on mouse or trackpad")

![Edit_Page_‹_Global_Styles_Demo_—_WordPress_and_General](https://user-images.githubusercontent.com/7662449/125205165-ec9d7280-e24e-11eb-8f89-85c9b5a373b2.jpg)

This issue isn't specific to the image block, but happens when any block is so far to the right that its toolbar doesn't have space to fit in the editor window.

### Context

I've run into this during three recent WordPress.com Quick Start sessions and it's caused confusion every time.

#### Browser / OS version

Firefox 89.0.2 / MacOS 11.4 (but also happens in Chrome/PC)

#### Is this specific to the applied theme? 

No

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact 

Affects all sites using blocks where a toolbar is far to the right

**Comment by inaikem** [comment]
Thanks for reporting this, @kathrynwp!

Confirming I can replicate this and that there's an existing thread related to this issue here: p1621935770059000-slack-C45SNKV4Z.

A related issue has been reported in the main `/gutenberg` repo. Closing this issue in favour of that: https://github.com/WordPress/gutenberg/issues/32402
