### ISSUE TITLE
Media Library: Documents and VideoPress files showing 0.00 B file size

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#54434]
### Steps to reproduce the behavior

 On a simple site, upload a document, such as a PDF. Check the file size in the media library in Calypso and it shows 0.00 B.

#### What I expected to happen

It should show the correct file size.

#### Does this happen on simple or atomic sites or both?

Simple sites. Atomic seems fine.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Calypso media library size vs actual:

![File Size](https://user-images.githubusercontent.com/41035049/125201423-f198fc80-e223-11eb-9d86-38eeda108c0a.png)

**Comment by inaikem** [comment]
Thanks for reporting this, @khristiansnyder 🙏

I was able to replicate this on Simple sites in the Calypso view: file size is shown as `0.00 B`

WP Admin / Classic view shows file sizes as expected. Only PDF files seem affected by this. Image files report file size correctly.

**Comment by inaikem** [comment]
There's an additional report of VideoPress files being affected in #55343

**Comment by sixhours** [comment]
On my WordPress.com site, the API is returning a file size of `0.0 B`, which bypasses checks on the frontend that are looking for an empty value or value of `0`. I also noticed that for these documents, the file size value in the `/wp-admin` media library is not shown, leading me to believe it's also seeing an empty value from the API; it's just doing a better job of hiding it: 

<img width="1379" alt="Screen Shot 2021-08-17 at 10 02 22 AM" src="https://user-images.githubusercontent.com/2124984/129741867-47d212a9-0c69-4b20-8f98-8477ad2013bc.png">

Images, on the other hand, do show file size in the `/wp-admin` Media Library and in Calypso.

So I'm trying to figure out why we're getting a `0.0 B` response from the API for the document's size. Retrieving data directly from the endpoint gives me no size information at all:

<img width="760" alt="Screen Shot 2021-08-17 at 10 14 31 AM" src="https://user-images.githubusercontent.com/2124984/129742521-98e407fc-abcf-43fd-9a8b-65280a9c3a5f.png">

Also good to note, things are working as expected for my Jetpack site with the same uploaded file, so it's probably hitting a different endpoint that has more robust file information? Possibly the core endpoint, although that doesn't appear to show file size, either, when I access it directly:

<img width="1476" alt="Screen Shot 2021-08-17 at 10 19 23 AM" src="https://user-images.githubusercontent.com/2124984/129743108-f8ef5f39-1ec6-4f88-b31b-8e8f2c91c97b.png">

Will keep digging!

**Comment by sixhours** [comment]
Found `/rest/class.json-api-endpoints.php` is where we're getting the data from; it has a special process for WordPress.com media:
<img width="870" alt="Screen Shot 2021-08-17 at 10 49 03 AM" src="https://user-images.githubusercontent.com/2124984/129748417-7d17ed91-78b4-4b15-8446-6e447d5c05f7.png">

Core function `wp_get_attachment_metadata` returns `NULL` for non-image file types, which results in `$filesize = 0`, but later you can see that we apply `size_format( (int) $filesize, 2 )` to that value which results in `0.00 B`. 

I'm not sure why the core function doesn't retrieve metadata for non-image file types, and it's not clear *why* we treat WP.com differently based on the comment above that block.

**Comment by sixhours** [comment]
Looks like file size was added in Automattic/jetpack#18637 and modified slightly for WP.com in Automattic/jetpack#18690 -- so only a few months ago. We started showing file sizes in the media library in #49500. 

I wonder if this addition wasn't tested with non-image file types, and if the zero bytes bug above is making this more obvious. 🤔 

For that reason, I think the fix is to correct the logic to make sure the file size doesn't show as `0.00 B` when we can't get info from `wp_get_attachment_metadata`.

**Comment by sixhours** [comment]
I may have found a solution based on some MGS searching: p9zhOE-iF-p2#comment-2281

We don't store attachment metadata on upload so it doesn't exist for non-image files. However, we could make an HTTP call to the file and check the content headers for that information if we don't have the metadata stored:

`$filesize = wp_remote_head( wp_get_attachment_url( $media_id ) )['headers']['content-length'];`

But I'm not sure how this impacts performance on sites with lots of docs/non-images.

**Comment by klavdijas** [comment]
The problem with Videopress File Size 0.00 B on AT sites #55343 occurs after the domain change, before Videopress File Size was correct. Videopress file size that were uploaded prior to domain change still show correct file size.

**Comment by sixhours** [comment]
> The problem with Videopress File Size 0.00 B on AT sites #55343 occurs after the domain change, before Videopress File Size was correct. Videopress file size that were uploaded prior to domain change still show correct file size.

Gotcha. I suspect at the root of it, the issue is the same -- at some point along the way, we fail to record the `filesize` to metadata on upload. I opened #55597 to follow up, investigating why we don't always store the filesize metadata for uploaded media.

**Comment by ariel-maidana** [comment]
A PDF upload appears as 0.00 B in the Media Library: 4926930-zd-woothemes
