### ISSUE TITLE
Export: Not able to perform full export with ERR_INVALID_RESPONSE error

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#54432]
### Steps to reproduce the behavior

1. Go to Tools → Export. Click Export All.

#### What I expected to happen

Export runs successful.

#### What actually happened

Web browser returned "This site can’t be reached" message with `ERR_INVALID_RESPONSE` at the end.

#### Does this happen on simple or atomic sites or both?

Affected users appeared to be on Atomic sites.

#### Is there any console output or error text?

This was the URL: https://cineaddiction.com/wp-admin/export.php?download=true&content=all&cat=0&post_author=0&post_start_date=0&post_end_date=0&post_status=0&page_author=0&page_start_date=0&page_end_date=0&page_status=0&attachment_start_date=0&attachment_end_date=0&submit=Download+Export+File

This is the error text displaying on web browser:

```
This site can’t be reachedThe web page at https://cineaddiction.com/wp-admin/export.php?download=true&content=all&cat=0&post_author=0&post_start_date=0&post_end_date=0&post_status=0&page_author=0&page_start_date=0&page_end_date=0&page_status=0&attachment_start_date=0&attachment_end_date=0&submit=Download+Export+File might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Appears to be affecting very large AT sites. If exporting smaller exports (like pages) works as expected.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/34882260/125199871-ce5d6400-e29a-11eb-900d-444320b14f59.png)

The issue was previously reported by another user on p2: p9F6qB-5JV-p2

Reported case: 30298059-hc

**Comment by kosiew** [comment]
Hi @edwinho89 ,

Thanks for reporting this and the detailed steps.


It is impossible that the web-based exporter will work for large sites given Atomic sites don’t have async exports like Simple sites. If they really want a XML export, please ask somebody from opers to export the files via wp-cli export and then tell them they can download them via SFTP.

ref: p9F6qB-5JV-p2#comment-32199

Closing this. Please reopen if you have additional context to add.
