### ISSUE TITLE
 Pay with PayPal Block: Uncaught Error: jQuery is not defined on non-WordPress.com users

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#54446]
### Steps to reproduce the behavior

1. Create a page, add [Pay with PayPal](https://wordpress.com/support/pay-with-paypal/) block.
2. On the published page, click "Pay with Paypal" button with any logged in WordPress.com account.
3. Log out of WordPress.com, visit the published page, click "Pay with Paypal" button

#### What I expected to happen

The "Pay with Paypal" button works

#### What actually happened

The "Pay with Paypal" button only works on logged in WordPress.com account. non-WordPress.com users are not able to proceed with "Uncaught Error: jQuery is not defined" message under browser console.

#### Browser / OS version

Reproducible across any web browsers, mobile.

#### Is there any console output or error text?

A copy of the console text error can be find here: 29be5-pb/

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Yes, it impacts purchases.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Had not able to reproduce this on test sites thus far.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/34882260/125267987-dae4c980-e339-11eb-9874-643cfa804009.png)

Here is the following HTML text from affected user:

```
<!-- wp:jetpack/simple-payments {"currency":"EUR","email":"consultaluna@gmail.com","multiple":true,"price":88,"productId":8156} -->
<div class="jetpack-simple-payments-wrapper jetpack-simple-payments-8156"><div class="jetpack-simple-payments-product"><div class="jetpack-simple-payments-details"><div class="jetpack-simple-payments-title"><p>El VALOR DEL TALLER POR LOS CUATRO ENCUENTROS ES DE 88 EUROS</p></div><div class="jetpack-simple-payments-description"><p>Tienes hasta el 25 de agosto para reservar tu plaza con este valor. 
Aquí el enlace para tu pago :</p></div><div class="jetpack-simple-payments-price"><p>88,00 €</p></div><a class="jetpack-simple-payments-purchase" href="https://lunadeabril.com/alquimia-lunar-online-introductorio/" target="_blank" rel="noopener noreferrer">Haz clic aquí para comprar.</a></div></div></div>
<!-- /wp:jetpack/simple-payments -->
```

Reported on 18340106-hc
Followup in 4132423-zd-woothemes

**Comment by inaikem** [comment]
Thanks for reporting this, @edwinho89. I'm also unable to replicate (macOS with Firefox 90 or Chrome 91, proxied or unproxied). A test page loads fine on my test site. Clicking the "Pay with Paypal" button loads the login modal without issue.

It also appears the user has removed the PayPal block from the page you noted in 4132423-zen - the block has been replaced with a paypal.me link.

I'd like to see if we can replicate this on a new test page on their site. Could you please follow up with them on that? Thanks!

**Comment by kwight** [comment]
I can't replicate myself either with Chrome on macOS – will close.
