### ISSUE TITLE
Payments Page: Toggle Menu Color

### ISSUE THREAD

**Issue by lizswafford** [Automattic/wp-calypso#54456]
The toggle button for the subscriber list on the Payments page is light gray, making it difficult to see. 
It does not match the toggle button on the pages and posts pages which is a darker gray, almost black. 
I would expect all toggle buttons to be the same color. 

Link to Payments: https://wordpress.com/earn/payments

Screenshot of payments toggle: https://d.pr/i/zVkE1D
Screenshot of pages page toggle: https://d.pr/i/xNQJtq

**Comment by inaikem** [comment]
Thanks for reporting this, Liz. I'm merging it into an existing open issue. I've also updated the title of that issue to make it easier to find.

**Comment by inaikem** [comment]
Closing in favour of #43227.
