### ISSUE TITLE
Full Site Editing: Beta opt-in flow

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54461]
Add the Dotcom FSE Beta opt-in flow to the design picker in the new site creation for existing customers.

- [x] Design side
- [x] Turn on the Site Editor on opted-in sites using universal themes (see https://github.com/Automattic/wp-calypso/issues/54469)
- [x] Development side (e.g. add the beta flag/sticker/etc. and handle it where appropriate in Calypso and wp-admin)

**Comment by Copons** [comment]
Note: this PR might be a good starting point for the behind-the-scenes handling of the beta: https://github.com/Automattic/wp-calypso/pull/53010
Let's keep it in mind when we start working on this issue.

**Comment by mattwiebe** [comment]
Note that the toggle being introduced in #54620 can essentially function as part of the opt-in flow for existing users, once we expose it to them.
