### ISSUE TITLE
Site Editor: Replace the navigation sidebar with a "back to dashboard" button

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54460]
To simplify the information overload of the Site Editor, we will start without navigation sidebar.
It will be replaced by a simple "back to dashboard" button, like in the Core Post Editor.

This change requires adding a SlotFill in Core Gutenberg that will allow us to replace the whole navigation sidebar, or a filter to override the toggle's `onClick`.

- [x] ~~Core side: https://github.com/WordPress/gutenberg/pull/33423~~
- [x] Dotcom side: https://github.com/Automattic/wp-calypso/pull/55471
- [x] Update events tracking E2E: https://github.com/Automattic/wp-calypso/pull/55558

**Comment by Copons** [comment]
Question about removing the Site Editor sidebar: what should we do with Atomic sites?

On one hand, we should keep the experience consistent across Simple and Atomic.
On the other, Atomic is supposed to give users the same freedoms of self-hosted, so there might be Atomic users expecting to get the sidebar (and in turn, to be able to customize all templates at will, etc.).

Any opinions on this? @ianstewart @mtias

**Comment by Copons** [comment]
Code is ready, but we are keeping this on hold until we are closer to the Beta roll out.

**Comment by creativecoder** [comment]
Noting here what I mentioned in Slack to help keep track of it:

Let's add a note to each of the relevant tracks events after this has been deployed so that it's more obvious why the event counts are low (can't have events triggered in the sidebar if there's no sidebar 😄)

**Comment by Addison-Stavlo** [comment]
> Let's add a note to each of the relevant tracks events after this has been deployed so that it's more obvious why the event counts are low (can't have events triggered in the sidebar if there's no sidebar 😄)

Agreed, PRs are open to update the notes for the tracks events.  Since the sidebar removal / test skips are deployed, il close this issue now.
