### ISSUE TITLE
Full Site Editing: Decide the initial block-based theme

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54463]
We need to choose the right block-based theme for the beta (depending on which one is more ready and with the more appropriate patterns over the next month.

**Comment by vindl** [comment]
Hi @jeffikus! Do you have a suggestion which theme to pick for this purpose? We'd like to launch the FSE beta soon, so I'm looking for one that's going to be in the most stable state in your opinion.

**Comment by vindl** [comment]
After discussing this with @Copons we have settled on the Quadrat theme.

**Comment by jeffikus** [comment]
Thanks @vindl - I missed this one. Quadrat is a good choice, feel free to ping us in #themes if you have questions.
