### ISSUE TITLE
Site Editor: Add a FSE-specific welcome tour

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54467]
Currently the Site Editor displays the same welcome tour we show in the Post Editor.
We should update it to feature guidance specific to the Site Editor.

**Comment by vindl** [comment]
cc @olaolusoga

**Comment by Addison-Stavlo** [comment]
Closing this since we have the help-center/welcome-tour project ramping up and are tracking elsewhere.  paYE8P-1xk-p2
