### ISSUE TITLE
Site Editor: Improve the navigation sidebar content

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54465]
This is an optional iteration to #54460.

Instead of replacing the whole sidebar on the Dotcom Site Editor, let's only replace its content with a simplfied version that doesn't expose the entire template hierarchy to the user.

For example, we could have only the content submenu, which also selects the edited template behind the scenes.

**Comment by Copons** [comment]
I've got a draft PR for this: https://github.com/WordPress/gutenberg/pull/33298
We can use it as a starting point, if we ever get to this point. 🙂

**Comment by Addison-Stavlo** [comment]
closing as this is a core issue and has since been updated
