### ISSUE TITLE
Site Settings: Make front page settings available outside of the Customizer

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54473]
Currently, users can only set their front page settings (if showing the latest posts or a static page, and which page) in the Customizer.

With FSE, the Customizer is gone, so we need to make those settings available elsewhere.
Some alternatives:

- Add them to Settings -> Reading (where they would show up for self-hosted and Atomic sites).
- Add them to the actions menu in the Pages list in Calypso (#42016).
- Add them to the Documents settings in the Page Editor (e.g. “set this page as homepage”).
- Remove the settings altogether, default the site to show a (predefined) static page as front page, and let the Site Editor take care of it entirely.

**Comment by Copons** [comment]
I'll close this issue as various unrelated changes across Dotcom made it much less of a problem than it was back then.

> With FSE, the Customizer is gone

Not quite!
Universal themes will still keep the Customizer around for the time being.

> Add them to Settings -> Reading (where they would show up for self-hosted and Atomic sites).

With the Nav Unification, this happens already: users have access to the `wp-admin/options-reading.php` screen from Settings -> Reading, and can set the "Your homepage displays" options.

<img width="462" alt="Screenshot 2021-10-07 at 11 53 01" src="https://user-images.githubusercontent.com/2070010/136370834-87a2adf0-cf37-4bc4-b33d-6b3e4f51a32d.png">

(Note: if the site doesn't have any published pages, these options will be automatically hidden in both Reading Settings and Customizer.)

**Comment by jordesign** [comment]
With reports of users confused about their Homepage when a theme is activated with Latest Posts on front page (like TT2) - I'm wondering if we can discuss this option again?

**Comment by kdevnel** [comment]
I'm reopening this since it came up with a couple of users using FSE themes. With the customizer disabled and the default being "Homepage displays latest posts" sending users to the Classic View of the reading settings to change this is a bit jarring.

Edit: In cases where a static page is already set, this isn't an issue since Calypso allows setting a different homepage from the page list.

This only applies to any site that wants a static homepage but currently have the default setting of "Homepage displays latest posts" active.

Context: 34326647-hc

**Comment by Addison-Stavlo** [comment]
From the point of the original issue - having these settings available outside of the customizer has been resolved with the access available in "Reading -> Settings".

Interaction from users shows this to be confusing or hard to find.

Surfacing these settings in the editors is a feature request for core gutenberg (example here https://github.com/WordPress/gutenberg/issues/28341 although that issue hasnt had much discussion lately).

Alternatively, surfacing these settings in a separate part of Calypso will need some input from dotcom designers. Im also curious on HE thoughts regarding where this would better fit inside calypso.

**Comment by Addison-Stavlo** [comment]
given the above findings and staleness of this issue im closing this.
