### ISSUE TITLE
Nav unification Quick switcher not displayed in WP-Admin when SSO is disabled

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#54499]
Given that the `show wp-admin` toggle will be removed, users having SSO disabled will not being able to switch between the interfaces since the quick switcher is currently not loaded for sites with SSO disabled.

### Steps to reproduce the behavior

1. Go to an Atomic site and make sure it doesn't have any quick switcher preferences.
2. Turn on the show admin toggle in /me/account (this toggle will be removed in another PR).
3. Go to WP-Admin > Jetpack > Dashboard > Settings and disable SSO (WordPress Login) 
3. Go to Posts > All posts
4. Use the switcher to land in WP-Admin
5. Notice that the switcher is not present in the WP-Admin

#### What I expected to happen
To be able to see the quick switcher in WP-Admin pages.
#### What actually happened
The button for switching to Calypso is not present.

#### Does this happen on simple or atomic sites or both?
Atomic
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Atomic with SSO disabled.

**Comment by mmtr** [comment]
Moving this back to "In progress" since we're slightly changing the implementation (see p1626695421153400-slack-C01VDMPHG69).

- We’re going to hide the quick switcher on Calypso when SSO is disabled (Calypso PR)
- We’re going to force the default view on the admin menu classes when SSO is disabled (Jetpack PR)

**Comment by mmtr** [comment]
Reopening, we still need https://github.com/Automattic/jetpack/pull/20404
