### ISSUE TITLE
Reader: Top bar doesn't scale well in narrow screens at top of single post view

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/wp-calypso#545]
With the Desktop app at minimum width, there is a styling issue with the TopBar when viewing a post in the reader:

![](http://cld.wthms.co/1csGe/5YvFwLQM+)

**Comment by lancewillett** [comment]
It might need a minimum scale — if you try the same thing in a desktop browser (running Calypso in Safari, for example) — you can't make it smaller than a certain width.

**Comment by WPprodigy** [comment]
Chrome allows for a much smaller width than safari, and firefox is the smallest of all. This issues exists on all of them now that I look at it though, not just the desktop app.

Chrome: http://cld.wthms.co/18sEz/4wTJMlfM
Safari: http://cld.wthms.co/18Yug/5NvST1EE
Firefox: http://cld.wthms.co/1bpBR/Yffb4WZC

**Comment by lancewillett** [comment]
Caleb, can you please add steps to repeat this? Which blog URL — and is it only in the Reader view?

**Comment by WPprodigy** [comment]
This is the blog post I used in my testing: https://en.blog.wordpress.com/2015/11/23/the-new-wordpress-dot-com/. And yes, it only seems to be happening from the Reader.

**Comment by lancewillett** [comment]
I think this is specific to the Reader single post view, not the main stream with sidebar.

**Comment by shaunandrews** [comment]
We had a fix for this ready to go but may have gotten lost in the switch to this new repo. Ill update when I'm back at my computer.

**Comment by shaunandrews** [comment]
Working on this over in #630
