### ISSUE TITLE
Clicking on My Sites menu in navigation opens an empty slider on sites with SSO disabled

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#54502]
### Steps to reproduce the behavior

1. Go to an Atomic site
2. Go to WP-Admin > Jetpack > Dashboard > Settings and disable SSO (WordPress Login)
3. Go to WP-Admin of the site
4. Click on `My Sites`
5. Notice that 
#### What I expected to happen
Display site selector?

#### What actually happened
An empty slider that hides the actual navigation.

#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Atomic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Atomic with SSO disabled

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/995955/125443355-7eab5630-0d1c-4293-88f9-486b3d2d59d9.mov

**Comment by AlexanderMonsanto** [comment]
Possibly related ZD-4120019
Screenshot provided by user reference issues with "My Sites" menu
