### ISSUE TITLE
Deleted site received '50 views' milestone notification

### ISSUE THREAD

**Issue by annacmc** [Automattic/wp-calypso#54530]
### Steps to reproduce the behavior

- Delete blog, wait for it to be purged. 
- HC-30023426 for reference

#### What I expected to happen

- Expect no further milestone notifications for this site once deleted.

#### What actually happened

- Blog is so far deleted enough as to being purged now. The user received a notification `Congratulations! Your site passed 50 all-time views.` 

### Context

- This happened during the purge process, I wonder if something in that tripped the 50th site view. 

#### Does this happen on simple or atomic sites or both?

- This happened on a simple, free site. 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low level of impact. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/30754158/125531686-8a5266f9-8167-4faf-952c-a22e8e72a674.png)

**Comment by kosiew** [comment]
Thanks @annacmc for reporting this.

Additional note:
Verified in BRC that blog was deleted more than 7 months ago.

**Comment by cometgrrl** [comment]
Please re-open if we see this happen again.
