### ISSUE TITLE
Convert domains to logmein links on domain contact verification page

### ISSUE THREAD

**Issue by aneeshd16** [Automattic/wp-calypso#54548]
The domains listed on the domain contact verification page can be converted to logmein links. Clicking on these links will log the user into their domain. Since this page opens in a logged-out context, we cannot use the existing `logmein` lib for this.
<img width="869" alt="Screenshot 2021-07-14 at 2 48 39 PM" src="https://user-images.githubusercontent.com/5436027/125597946-9a9d74e7-f8c1-4130-8edb-763559ffa886.png">

@niranjan-uma-shankar @lsl what do you think?

**Comment by niranjan-uma-shankar** [comment]
> The domains listed on the domain contact verification page can be converted to logmein links. 

+1 agree. We can convert the domain name here to a link. Once it becomes a link, I think @lsl 's link intercept will automatically append the logmein, is that right? 

> Since this page opens in a logged-out context, we cannot use the existing logmein lib for this

The existing logmein client-side lib assumes the user is always logged in when in a Calypso context. This is an example that it might not be true always. Looks like we need to modify [this line](https://github.com/Automattic/wp-calypso/blob/801bc86f1697badbea0e386da7edf3b0e1bb27ca/client/lib/logmein/index.ts#L66) to conditionally append `logmein=1` or `logmein=direct` based on the logged in status of the user.

**Comment by lsl** [comment]
That function will only apply logmein to links going to sites in the user's set of sites, so if they're not logged in they shouldn't be seeing logemein links in calypso (from this function). (this is why we assume logged in and always go with direct on that line.)

Probably need to move some of this code around and expose a function for each mode without validating things but you're also free to just add the logmein=1 param anyway, the logmein lib if applied later will overwrite it with direct if it makes sense.
