### ISSUE TITLE
Stats: add edit link to Post Stats Page

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#5456]
This was a user suggestion submitted via Twitter:

https://twitter.com/Mrfoxtalbot/status/733070747304927233?ref_src=twsrc%5Etfw

The request is to include a link to edit a post from the post detail page.  In their image, the user suggested placing the edit link to the right of the post title in the Header Cake component.

Though Header Cake does not support this sort of UI, perhaps the view/edit actions could be included elsewhere on the page.

/cc @jancavan

**Comment by drw158** [comment]
![cixj9axwgaehs6j](https://cloud.githubusercontent.com/assets/618551/15399682/41be42a0-1dae-11e6-8346-099f39a1337c.jpg)

**Comment by jancavan** [comment]
I think this already has somehow been implemented. I see a "View post" button:

![screenshot 2017-11-30 15 59 37](https://user-images.githubusercontent.com/4924246/33461476-7c4b92a4-d5e7-11e7-86e5-16ea262c5dcb.png)

An "Edit" button is also on the overlay that opens up when you click "View post":
![screenshot 2017-11-30 15 59 54](https://user-images.githubusercontent.com/4924246/33461502-9f37d890-d5e7-11e7-8502-91d67eaaad6c.png)
