### ISSUE TITLE
Custom Colors: Clicking default colors leads to strange behaviour on Atomic

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#54598]
@DanielSmithMichigan found this while reviewing a different issue. The default colors button on the customizer doesn't work on Atomic

https://user-images.githubusercontent.com/375980/125786514-955b205d-85d5-4630-b973-066732929fec.mov

**Comment by andres-blanco** [comment]
this works OK on Simple. The problem seems to be that this CSS variable is not updating `--branding--color-link`

**Comment by andres-blanco** [comment]
## Status

This seems to be happening with seedlet, I didn't test other themes for now.

### Possible fix

If you go to the `Chrome Inspector > Sources` and make this additions to the `extraCSS` const on the file `wpcom-customize-preview.js?ver=1.1` (you can press `cmd + p` to open a file picker)

```js
'--branding--color-link: var(--global--color-primary);' +
'--entry-header--color: var(--global--color-primary);' +
'--entry-meta--color: var(--global--color-foreground);' +
'--branding--color-text: var(--global--color-foreground);' +
'--button--color-background: var(--global--color-secondary);' +
```

the bug stops appearing. But this fix would be to error prone, since every new css variable definition based on another css variable would need to be added here. I think we need to find out **why** these variables are not being refreshed correctly. 

I am inclined to think that this is due to a subtle difference in html structure between simple/atomic, but I cannot confirm it.

**Comment by kwight** [comment]
@andres-blanco Is this fixed with any of the recent merges?

**Comment by andres-blanco** [comment]
This bug doesn't seem to be happening anymore on seedlet on Atomic. 

Closing this issue
