### ISSUE TITLE
Small Line height with large text causes problems on mobile views.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#54617]
Workaround for now: If they need text lines close together, use shift+enter to create new lines inside the same paragraph block, the bug doesn't occur then. Only when the text is in separate blocks does this bug occur.

### Steps to reproduce the behavior

1. Create a cover block and put 3 paragraph blocks inside it. Set their line-height to 0.2
4. Enter long lines of text into each block, so they will wrap around on a smaller screen.
5. Preview the page.

#### What I expected to happen
Text should wrap around and not overlap.

#### What actually happened
Text wraps, but overlaps the text and elements under it.

#### Browser / OS version
Firefox Browser, although it happens on all browsers I tried.
On Safari it happens less.

#### Is this specific to the applied theme? Which one?
Happens on 3 themes I tried: Hever, Exford, and Dalston. I believe it happens on all themes.

#### Does this happen on simple or atomic sites or both?
Happens on both Simple and Atomic sites.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
All simple and atomic sites. Does not block purchases.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot on 2021-07-15 at 10-30-53](https://user-images.githubusercontent.com/49131029/125825052-b1080e5f-94da-40b5-9cb2-2e21027f070c.png)- Desktop View
![Screen Shot on 2021-07-15 at 10-31-19](https://user-images.githubusercontent.com/49131029/125825117-5a20e17c-cee9-48a5-82e9-c207c11fc154.png) - Mobile View.

**Comment by inaikem** [comment]
Thanks for submitting the issue, @KirkwallDay. I’ve dealt with similar issues twice over the past few weeks and consider this to be more of an education/awareness issue vs platform bug.

We should allow folks to set whatever line-height they want, as there may be a design reason for doing so. 

However, I think we _should_ also consider adding a warning if line-height is set to <1. Something similar to the mock-up below would work well, I think.
&nbsp;

![line-height-warning-v4](https://user-images.githubusercontent.com/66711744/126137571-9699b794-a546-4af5-b691-47ddb55fab4a.png)

&nbsp;
We have similar warnings for low-contrast text colour combinations:
<img width="1176" alt="Screen Shot 2021-07-19 at 11 27 01" src="https://user-images.githubusercontent.com/66711744/126137876-48f00ddb-d5f1-4c14-b85a-9df32288d1ca.png">

&nbsp;
Thanks for the screenshot, @mrfoxtalbot 

Re-labeling as a feature request. Thanks again!

**Comment by inaikem** [comment]
After some discussion I created a new issue in the main Gutenberg repo here: https://github.com/WordPress/gutenberg/issues/33536.

The request contains a couple of suggestions for communicating the result of low line heights to users. Closing this request in favour of the above link.

Discussion: p1626686492060200/1626677897.047000-slack-C01UW7SB411
