### ISSUE TITLE
Media Library: Uploaded Media Is Being Displayed In Wrong Date Section

### ISSUE THREAD

**Issue by jgcaruso** [Automattic/wp-calypso#54610]
### Steps to reproduce the behavior

1. Go to 'Media'
2. Upload a new media file
3. Observe the date heading it is placed under is today's date
4. Wait for media to finish uploading
5. Observe that the date heading changes to yesterday's date. Looking at the actual media item, it has the correct date stored in its "Upload Date" property (maybe its doing some UTC conversion on a date field with no time value??)

#### What I expected to happen
The media file should stay under the current day's date

#### What actually happened
The media file moved under yesterday's date

#### Browser / OS version
Safari and Firefox

#### Is this specific to the applied theme? Which one?
nope

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
Nope

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Files are confusing to find when looking for things you uploaded today.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/4081020/125816947-3a67c08a-a9f6-400b-bf1c-3b92167a819f.mov

**Comment by jp-imagines** [comment]
Came across a report of this in 5354922-zd-woothemes.
I was able to reproduce the same on both a Simple and Atomic test site, with the exact same behavior as in the video above. The upload date is correct while uploading, but once the upload finishes it switches to yesterday's date. 

If you click on a media file and click `Edit`, the correct upload date is shown in the file details.

**Comment by jgcaruso** [comment]
A year later I'm a bit more familiar with Calypso code, so I'm making an attempt to fix this now. @jp-imagines thanks for updating the issue to bring it back to my attention 😂
