### ISSUE TITLE
Signup: avoid duplicate error and success message when creating a site that matches username

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#5461]
This is split from #288 since it's a minor UX improvement and not a blocker to getting that fixed. CC @bisko 

This is to remove an unneeded warning in the UI when trying to creating a site that matches username, and choosing the exact URL in the domains "Let's find a domain" field.

#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/start/account/user
2. Sign up for a user account only
3. Then, go to My Sites and follow steps to create a first site
4. In the step for choosing a name, enter the exact username (without the `.wordpress.com` part)
5. It should suggest `username` (dot) wordpress (dot) com as the first suggestion. Which is what #288 addressed.
6. Now, type or paste the entire URL into the input field: `username` (dot) wordpress (dot) com

#### What I expected

To see the suggestion at the top of the list, so I can create it.

#### What happened instead

The suggestion is in a green box, nice! But, there's a red box above it that looks dangerous and is possibly confusing.

<img width="1392" alt="screen shot 2016-05-19 at 09 18 24" src="https://cloud.githubusercontent.com/assets/66797/15401424/66d114e6-1da4-11e6-803b-01c37ee2a7a4.png">

#### Browser / OS version
Tested with Firefox stable on OS X 10.11.4.

**Comment by meremagee** [comment]
It appears we are querying both mapping and domain availability at the same time for .wordpress.com domains where we should be running the availability check only (since mapping would never make sense in this instance) to show whether the subdomain is available or not.

**Comment by bisko** [comment]
Fixed in #5582.
