### ISSUE TITLE
Signup: Starting a new site from the "someunusedsiteurliwant.wordpress.com doesn't exist" screen doesn't carry over the URL

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#5462]
#### Steps to reproduce
1. Starting at URL: http://someunusedsiteurliwant.wordpress.com/
2. Click on "Do you want to register http://someunusedsiteurliwant.wordpress.com/ ?"
3. I'm brought to signup, where I select my vertical and theme...
4. It's time to select my domain name! Yay! But I already requested that in step 2...why do I have to type it in again?

#### What I expected

For the URL field to auto-fill with the URL I asked for in step 2 (or some variation, in the event the URL I want is taken).

#### What happened instead

I have to type my desired URL in again. I'm lazy, I don't want to do that.

This happens when logged in or logged out.

#### Browser / OS version

Chrome 50 / OS X 10.11.1

#### Screenshot / Video

<img width="1440" alt="screen shot 2016-05-19 at 12 28 34 pm" src="https://cloud.githubusercontent.com/assets/2124984/15401725/d3d2fe6e-1dbe-11e6-8b15-2bcaf5522093.png">
<img width="1009" alt="screen shot 2016-05-19 at 12 29 08 pm" src="https://cloud.githubusercontent.com/assets/2124984/15401724/d3d0a452-1dbe-11e6-9a34-6583d694189d.png">

**Comment by lancewillett** [comment]
See related #5461 — Delta team is working on improving this flow.

**Comment by michaeldcain** [comment]
Fixed in #5779.
