### ISSUE TITLE
Themes: old theme remains marked active after new theme is activated

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#5463]
#### Steps to reproduce
1. Starting at URL: wordpress.com/themes/
2. Activate a different theme
3. Note that your old theme still says "Active"

#### What I expected
The new theme to say "Active"

#### What happened instead
The old theme still says "Active"

#### Browser / OS version
Chrome 52.0.2741.0 / OS X 10.11.5

#### Screenshot / Video
<img width="958" alt="screen shot 2016-05-19 at 11 43 50" src="https://cloud.githubusercontent.com/assets/195089/15401870/0de183a8-1db7-11e6-8cda-d212b7fff15a.png">
^ Shoreditch was activated, Twenty Sixteen was the old theme

**Comment by folletto** [comment]
That's the old Atlas showcase, will be retired. :)
