### ISSUE TITLE
Shawburn background margin colors can't be changed on Simple Sites

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#54630]
### Steps to reproduce the behavior

1. Activate Shawburn  on a simple site
2. Go to Appearance - Customize - Colors & Backgrounds
3. Try changing the color of the margins. On AT sites, the Foreground color controls this. Foreground color on Simple controls something else though, and that body background-color is permanently #444444
4. CSS is required to change the left/right margin colors (the body background-color).

#### What I expected to happen
Those margins, or the body background-color, to be able to be adjusted in the Customizer.
#### What actually happened
CSS is required to change the body background-color from #444444 to something else.
### Context
User report, trying to change that color, and CSS seemed to be required.
#### Browser / OS version
All
#### Is this specific to the applied theme? Which one?
Shawburn
#### Does this happen on simple or atomic sites or both?
Simple site only. On AT site, the Foreground Color swatch changes the body background-color. 
#### Is there any console output or error text?
None.
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all simple sites using Shawburn.
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
AT site showing it working: 
![image](https://user-images.githubusercontent.com/30731356/125862043-188fc594-f40e-4d64-ab18-77455b4ec49d.png)

Simple site showing it not working:
![image](https://user-images.githubusercontent.com/30731356/125862087-19e4fbd7-3949-4ed9-a174-7eb3c860482e.png)

**Comment by inaikem** [comment]
Thanks for submitting this report, @scosgro 🙏

I tested and was able to confirm your findings. Moving into the triaged queue.

**Comment by youbrokesomething** [comment]
I'm not able to reproduce this issue currently. Please reopen it if it becomes reproducible again.
