### ISSUE TITLE
CoBlocks: Services Block center align not holding on edit

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#54631]
### Steps to reproduce the behavior

1. Add a Services Block (with some content)
2. Center the "description" text in the Paragraph block and save or publish
3. Leave the editor and then return to the editor
4. Centered text reverts to being left aligned

#### What I expected to happen

Text to remain centered.

#### What actually happened

Text shows as centered at first, then reverts to be left aligned.

#### Is this specific to the applied theme? Which one?

Tested in Shoreditch and Rockfield

#### Does this happen on simple or atomic sites or both?

Only test on AT site

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Shoreditch: https://d.pr/v/91Mpdl
Rockfield: https://d.pr/v/9bOhAc

Tested with copied content and brand new content, and with the preceeding Header block removed or left in place: https://d.pr/v/NYB1G4

Reported by user #30659775-hc

I was able to override it by applying a custom CSS class to the outer Services block (I used centerservices) and then added the following to the Customizer:

`.centerservices {
	text-align: center;
}`

**Comment by inaikem** [comment]
Thanks for the filing this report, @tanjoymor 🙏

I tested and was able to replicate the issue exactly as you described it. Moving into the triaged queue now.

**Comment by sixhours** [comment]
Hmm, it looks like Services is a CoBlocks block that's only available to Atomic sites, and since we don't have access to their code base and it's not part of the subset of CoBlocks run on WP.com, this isn't something we can fix.

We could move this report to the appropriate place so the maintainers are aware. /cc @yansern do you know how we usually handle bug reports for CoBlocks?

**Comment by sixhours** [comment]
Pinged the Create flow patrol team to see if they have ideas where we can report this.

**Comment by sixhours** [comment]
Opened a bug with CoBlocks: https://github.com/godaddy-wordpress/coblocks/issues/1977

**Comment by yansern** [comment]
> We could move this report to the appropriate place so the maintainers are aware. /cc @yansern do you know how we usually handle bug reports for CoBlocks?

Apologies as I was AFK and yes https://github.com/godaddy-wordpress/coblocks/issues/1977 seems like the place to report this issue!

**Comment by sixhours** [comment]
Looks like this was recently fixed in https://github.com/godaddy-wordpress/coblocks/pull/2008
