### ISSUE TITLE
Plans: HTML tags are visible on plans page during new site/user flow

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#5464]
Raised by @rudzki 

HTML tags visible on Plans page during new site/user flow, or at: https://wordpress.com/start/domains-with-premium/plans

<img width="425" alt="plans-html" src="https://cloud.githubusercontent.com/assets/66797/15402487/4b36280c-1da9-11e6-8d70-8c645533229e.png">

**Comment by lancewillett** [comment]
I'm able to repeat, using Mac-n-Chrome with the same URL as above (both logged in or logged out).

![screen shot 2016-05-19 at 10 24 40](https://cloud.githubusercontent.com/assets/66797/15403074/fc7c2b50-1dab-11e6-9f31-20142d56799f.png)

**Comment by rodrigoi** [comment]
@rralian looks like it's calling API version 1.1 instead of 1.2. Maybe related to this commit: https://github.com/Automattic/wp-calypso/commit/28fff4f95ea8eb8a8555df547e7afe8d70ede537
