### ISSUE TITLE
Apostrophe2: Newspack Carousel Block break out of container on atomic

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#54644]
### Steps to reproduce the behavior

1. Activate Apostrophe 2 on an atomic site
2. Go to Customiser > Content Options and ensure featured images are set to display on pages or posts
3. On a page or post, add a Newspack Post Carousel block to the page
4. The featured image should break out of the page container

#### What I expected to happen
The carousel should stay in the container width like it does on simple sites

#### What actually happened
The featured image break out of the container like this:

![Markup on 2021-07-16 at 14:19:07](https://user-images.githubusercontent.com/22053773/125946280-bdcb9c2d-3b9c-4570-a8b3-0b9a62619790.png)

### Context
30663814-hc
Follow-up: 4152701-zd-woothemes

#### Browser / OS version
Any

#### Is this specific to the applied theme? Which one?
Apostrophe 2

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Specific to this theme and also atomic sites. There is no temporary solution since it appears that the width is calculated on page load by JavaScript so CSS isn't solving the image width.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

**Comment by Robertght** [comment]
I looked into this briefly, however it appears to be related to this one:

https://github.com/Automattic/jetpack/issues/20289

We can go around with it using CSS code.

@jeherve Has the fix been merged yet?

**Comment by jeherve** [comment]
That's indeed the same problem. The fix has been merged, and will be shipped with the next version of Jetpack, scheduled to be released on WordPress.com sites next Tuesday.

Until then, I would recommend using CSS to solve the issue. You can learn more about workarounds here:
https://github.com/Automattic/wp-calypso/issues/54340
