### ISSUE TITLE
Theme Showcase: Clicking Recommended tab doesn't preserve viewport position

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#54651]
### Steps to reproduce the behavior

1. Go to `/themes/[site]` and scroll down a bit.
2. Click "All Themes" tab. Note how the screen stays put.
3. Click "Recommended" tab. Note how you're jumped to the top of the screen.

It's a small thing, but it will probably become more noticeable as we add more tabs.

#### What I expected to happen

For the tabs to behave the same way; both should keep your position on the screen to avoid jumpiness.

#### What actually happened

A jarring jump when you click the Recommended tab from the All Themes tab:

https://user-images.githubusercontent.com/2124984/125973109-6a783087-4a56-47b0-bdcc-1ca6fd5e22e2.mov

### Context

Found while testing

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

Nope

#### Level of impact 

Low - just visually jarring, doesn't harm overall functionality

**Comment by sixhours** [comment]
This is not fully fixed after merging #55041 so I'm reopening it, with the caveat that it's not a high priority issue.

**Comment by kwight** [comment]
This no longer happens, it must have been corrected at some point.
