### ISSUE TITLE
Jetpack Settings: Blank page shows for free Atomic sites

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#54652]
### What plan tier is the site on?
Free

### Where are you seeing the issue?

1. Go to /settings/jetpack/
3. See it!

### What I expected on the WordPress.com site

Empty content with error message:
<img width="761" alt="Screen Shot 2021-07-16 at 11 59 22 AM" src="https://user-images.githubusercontent.com/1689238/125976146-fc924055-4fab-401b-a70b-34ffe5a83da1.png">

#### What I expected on the Atomic site

Empty content with error message, like on Simple.

#### What actually happened

An empty page:
<img width="693" alt="Screen Shot 2021-07-16 at 12 02 22 PM" src="https://user-images.githubusercontent.com/1689238/125976249-d41046b3-24ef-47fa-94d5-6b9ea50007e9.png">

**Comment by obenland** [comment]
We might be able to just unregister the menu item linking to that page, when a site doesn't have the appropriate plan.
