### ISSUE TITLE
Editor: Preview doesn't work without existing Autosave

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#54657]
If you go to preview your site prior to saving anything, when you get to the front of your site, none of your changes are there. This feels like a bug when it happens. Prior to previewing, let’s just trigger a draft save of the customers changes.

### Steps to reproduce the behavior

1. Open the Editor for a new post.
2. Add content to the post.
3. Click on "Preview".
4. In the preview modal, click on "Visit Site".
4. See a 404 error.

See p58i-aJq-p2

**Comment by taggon** [comment]
@obenland Is this still relevant? Look like the draft is saved as soon as the Preview button is clicked. Check out the following video.

https://user-images.githubusercontent.com/212034/126278025-be5f4fc6-8de5-47e4-82b7-209c75fb2b6a.mov

**Comment by obenland** [comment]
Hm, so it looks like this might be a browser-specific issue?

In Chrome I see the 404 and then it reloads to show the preview.
In Safari I get stuck on the 404 without a page reload.

Does that match your experience?

**Comment by taggon** [comment]
@obenland No, I don't think it is a browser-specific issue. To me, it works well in Safari too. I don't see 404 in both browsers.

https://user-images.githubusercontent.com/212034/126474223-7d2210e3-fe66-4e69-96d1-f0ce9379a0cb.mov

**Comment by kwight** [comment]
Hm, I have the same experience as @taggon on WP.com – no issue.

![2021-10-04 14 37 23](https://user-images.githubusercontent.com/349751/135928357-1fb986af-7efb-43b9-8f6a-872e55c9997b.gif)

**Comment by obenland** [comment]
I can't reproduce it myself anymore either. Closing for now.
