### ISSUE TITLE
Support: update generic "email support" text

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#54674]
Since we have an email product, the generic use of ["email support" in Calypso](https://github.com/Automattic/wp-calypso/search?q=%22email+support%22), especially in Checkout's "included with your purchase" sidebar, to describe non-live chat support can be confusing for users.

Let's update it mentions of "email support" to "customer support via email".

/cc @olaolusoga @semihakocer @daledupreez

**Comment by Patil2099** [comment]
I would love to work on this
