### ISSUE TITLE
Widget Visibility Not Applied in Customizer

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#54678]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/customize/
2. Open Widgets and apply visibility settings such as Hide if Page is Front Page
3. Note the widget continues to show when it should be hidden (and is hidden if you view the site outside of the Customizer)

#### What I expected to happen

The Customizer to reflect widget visibility settings

#### What actually happened

Widgets are always shown

### Context

Reported by user in 4155757-zen

#### Browser / OS version

Chrome 91 OS X

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low. Affects all sites in my testing, but settings are applied properly on the front-end.

**Comment by jp-imagines** [comment]
Another report in 4214651-zen.

**Comment by sbathompson-he** [comment]
This user reported this as well: 29125295-hc
As a fix, we set the disable block widgets sticker in the BlogRC. They are able to see the visibility now, however, even though the visibility is set correctly in the Customizer, it is still not correct on the site.

**Comment by ccwalburn** [comment]
Another report where the Customizer doesn't recognize the visibility settings here: 4336648-zen

Also, if the visibility is set to display only on the posts page, then the widget doesn't display in the Customizer widget section either. If you hover, you can see the outline of a box like this:

![screenshot](https://d.pr/i/yyAtLM+)
Image URL: https://d.pr/i/yyAtLM

...and clicking on the white box will open the widget like this:

![screenshot](https://d.pr/i/52FawC+)
Image URL: https://d.pr/i/52FawC

Tested on Premium site with Hemingway and Penscratch.

**Comment by Nic-Sevic** [comment]
another similar case here: 29674548-hc

This one's AT though and there is no option that I see to sticker the blog as block widgets disabled

Additionally, if you try to update the visibility in the widgets.php page it won't save; you can only change the visibility in the customizer

**Comment by LauraSWP** [comment]
A similar issue here 29307687-hc but it's only for the Instagram widget, rules are not saved. Follow-up 4394899-zn

**Comment by obenland** [comment]
@mreishus Have you come across this before?

**Comment by mreishus** [comment]
I believe it's desired behavior that the visibility settings are not applied in the customizer. It's possible to create rules that would make widgets display only in very obscure conditions. If this is the case, we still want the widgets to be easily editable inside the editing interface: that the rules can be edited without having to navigate to the specific page where the rules are true for each widget. This helps widgets from being "lost".

**Comment by ghost** [comment]
Another case in 4419471-zen

**Comment by devNigel** [comment]
Another case: 33104796-hc
Follow up: 4578129-zen

**Comment by cometgrrl** [comment]
I am not able to reproduce this issue. I set an image block widget to hide if the front page, and in the customizer, it was no longer shown on the front page.
