### ISSUE TITLE
Recently edited posts list in the WordPress menu in the editor does include Drafts

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#54676]
### Steps to reproduce the behavior

1. Create a post and save it as a draft
2. Click on the WordPress icon in the top-left of the editor to open the menu
3. Click on Add new post
4. Click on WordPress icon in the top-left of the editor

#### What I expected to happen

The draft post should be shown under Recently edited in the menu

#### What actually happened

No draft post is shown in the Recently edited section of the menu

### Context

User reported

#### Is this specific to the applied theme? Which one?

Any theme

#### Does this happen on simple or atomic sites or both?

Both

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="524" alt="Markup 2021-07-18 at 14 41 19" src="https://user-images.githubusercontent.com/51966986/126069528-15dbb0cc-57c1-4448-b462-c08f5bffbc57.png">

**Comment by synora** [comment]
Triaged. Can replicate.
