### ISSUE TITLE
Calypso crashes to  a white screen when an Administrator tries to manage a domain it doesn't own.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#54670]
When an administrator of a site tries to manage the domain that is under the ownership of another administrator, the Calypso dashboard crashes to a white screen. 

### Steps to reproduce the behavior

1. Go to a site that has two or more administrators.
2. Make sure a custom domain name is added to the site from Administrator 1's account.
2. log in to WordPress.com with Administrator 2's account.
3. Go to Upgrades > Domains and click on the custom domain added by Administrator 1.
4. You will encounter a white screen.

#### What I expected to happen

All administrators should be able to manage all custom domains of their site.

#### What actually happened

Calypso dashboard crashed.

### Context

An administrator of the site was trying to manage the domain on the site.

#### Browser / OS version

Microsoft Edge 91.0.864.70 / macOS 1.3

Reproducible in multiple browsers.

#### Is this specific to the applied theme? Which one?

No.

#### Does this happen on simple or atomic sites or both?

Both.

#### Is there any console output or error text?

```
51865.7f066b3455a8a911a695.min.js:2 TypeError: Cannot read property 'saleAmount' of null
    at St (60865.9f154ebb99f487fa8691.min.js:1)
    at Da (domains.38a9ec8109e4e9310f70.min.js:41)
    at Xs (51865.7f066b3455a8a911a695.min.js:2)
    at wa (51865.7f066b3455a8a911a695.min.js:2)
    at yl (51865.7f066b3455a8a911a695.min.js:2)
    at ml (51865.7f066b3455a8a911a695.min.js:2)
    at al (51865.7f066b3455a8a911a695.min.js:2)
    at 51865.7f066b3455a8a911a695.min.js:2
    at t.unstable_runWithPriority (51865.7f066b3455a8a911a695.min.js:2)
    at Ho (51865.7f066b3455a8a911a695.min.js:2)
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

High. Other admins will not be able to manage domains settings.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/33957570/126027663-d51b5cde-9d3c-4956-b087-9c35f6f6da7a.mov

User report: 4142461-zen / 30648047-hc

**Comment by michaeldcain** [comment]
@Automattic/nomado

**Comment by delputnam** [comment]
This appears to have been introduced by https://github.com/Automattic/wp-calypso/pull/53685

cc @donlair

**Comment by delputnam** [comment]
Deploying https://github.com/Automattic/wp-calypso/pull/54679 to revert the change that caused this regression.
