### ISSUE TITLE
Atomic: New page template splash immediately disappears

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#54684]
### Steps to reproduce the behavior

1. On an AT site click to add a new page
2. See the template slash briefly appear and then disappear

#### What I expected to happen
I should be able to pick a page template and the splash should only disappear when I close it

#### What actually happened
It disappears immediately

### Context
was trying to see what home page demo templates we have for themes

#### Browser / OS version
Chrome 91 on macOS (Catalina)

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
atomic only

#### Is there any console output or error text?
![2021-07-19 at 14 19](https://user-images.githubusercontent.com/47717887/126152486-9e098a36-eac0-40bd-a565-079c8a6f46a9.jpg)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
makes it impossible for users to start from a template

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![new page](https://user-images.githubusercontent.com/47717887/126152594-48faf133-72c8-45a4-88fe-02fb7ce419bf.gif)

**Comment by synora** [comment]
I'm unable to replicate this on my Atomic site:

https://user-images.githubusercontent.com/10015451/127019430-341a52ee-2772-46c9-bb05-89d53825eb0c.mp4

I'm using Chrome v. 91.0.4472.114 / macOS Bug Sur v 11.4

But that doesn't mean there's an issue here though. What about on other browsers?

**Comment by cometgrrl** [comment]
I'm not seeing the page templates on my site either, I'm not even seeing it appear briefly like in the original report.

I'm on Chrom Version 103.0.5060.134 (Official Build) (arm64), Mac OS 12.4.

https://user-images.githubusercontent.com/86427589/182263639-b4218ee3-cb8a-48b7-bb80-25d4a87ff4e5.mov

**Comment by alshakero** [comment]
Hi everyone! This happens when the Editing Toolkit Plugin is disabled. I checked both sites that can reproduce here and both have ETK disabled. Enabling it should fix the issue, page templates are part of ETK.

**Comment by Nic-Sevic** [comment]
@alshakero I'm not sure that ETK was disabled at the time of testing since I'm regularly testing on that site and may have disabled it for something else. If you can reliably reproduce though, thank you for taking a look! If I happen to see it again with ETK enabled I can reopen but in this case it sounds like maybe we can close?

**Comment by alshakero** [comment]
Yes, please do! That would be very helpful, thanks 🙏🏼

**Comment by cometgrrl** [comment]
> Enabling it should fix the issue, page templates are part of ETK.

@alshakero TIL! Thanks!
