### ISSUE TITLE
Theme Showcase: Add more styles for new theme sheets

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#5470]
For the new theme sheets, we should add some basic styling for these elements and classes:

`.info` class - used for Quick Specs box at bottom.

Current example screenshot from [this page](https://wpcalypso.wordpress.com/theme/forefront/overview) - 

![theme wordpress com-1](https://cloud.githubusercontent.com/assets/7662449/15405434/d19668dc-1dcf-11e6-8cfb-ac7db967a5e2.png)

**Styling suggestion:** add shaded background, make font smaller. This is how it [currently looks](https://wordpress.com/themes/forefront/):

![wordpress themes wordpress com](https://cloud.githubusercontent.com/assets/7662449/15405458/f8f862d6-1dcf-11e6-84f1-3a75aa94cc06.png)

--------
All headings h1-h6 should also get styled.

It's mainly h2-h4 that are currently used.

Example of how h2s are not currently distinguishable from the body text:

![theme wordpress com-2](https://cloud.githubusercontent.com/assets/7662449/15405513/3567a0b0-1dd0-11e6-8417-972e383f937d.png)

**Styling suggestion:** bold, make larger, add bottom margin.

--------
Other tags that should have at least basic styling:

hr (used a lot in the showcase)
code (used a lot in the showcase)
ul, ol, li (used a lot in the showcase)
strong
em
pre
big
small
blockquote
dl, dd, dt

**Suggestion for basic styling:** can borrow from [_s styles.](https://github.com/Automattic/_s/blob/master/style.css#L261)

**Comment by kathrynwp** [comment]
Let's also please add styling for:

figure
figcaption

These will be used in some cases to replace gallery shortcodes. Example:

<img width="775" alt="screen shot 2016-05-20 at 17 45 41" src="https://cloud.githubusercontent.com/assets/7662449/15428159/c250fa2a-1e67-11e6-9c04-1c247835db09.png">

**Comment by folletto** [comment]
The styling has been merged in #5493. :)
