### ISSUE TITLE
Domain credit not available for monthly plans not mentioned in FAQ on the plans page

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#54718]
### Steps to reproduce the behavior

1. Go to 'https://wordpress.com/plans/SITEADDRESS'
2. Scroll down to FAQ
3. Free domain credit included in all plans (not only annual)

screenshot: https://d.pr/i/2NFab9

Solution: Add "The domain credit for a free domain for the first year is only included with the annual or two-year plans."

**Comment by chrisfromthelc** [comment]
This was addressed in a different PR, #54624, so I'm closing this issue.
