### ISSUE TITLE
Theme Showcase: Add a way to access more themes from theme sheet

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#5471]
Once a user is on an individual theme sheet, there needs to be a way to view all themes, without relying on the "back" button, since users may reach a sheet from many different places.

On the current page - [example](https://wpcalypso.wordpress.com/theme/twentysixteen) - there is no way to look at another theme sheet from here, as there is no link to "all themes" - not that we can find, anyway.

**Suggestion:** add an obvious link to all themes somewhere at the top left, like on the current showcase:

![wordpress themes wordpress com-1](https://cloud.githubusercontent.com/assets/7662449/15406174/48a4399c-1dd3-11e6-86d1-798797b450bd.png)

Or like on the previous showcase:

![twenty sixteen theme wordpress themes for blogs at wordpress com](https://cloud.githubusercontent.com/assets/7662449/15406220/92a320e4-1dd3-11e6-9d09-cba3463fcc8a.png)

**Comment by folletto** [comment]
> On the current page - example - there is no way to look at another theme sheet from here, as there is no link to "all themes" - not that we can find, anyway.

It's the back button:

![screen shot 2016-05-20 at 18 00 40](https://cloud.githubusercontent.com/assets/4389/15435545/c97057b8-1eb4-11e6-951b-c0c38a983a12.png)

Still being hooked up, however. So it doesn't work yet. It's being implemented in #5422.

**Comment by kathrynwp** [comment]
I read #5422 but this does not seem like quite the same thing as an actual "All Themes" link. 

For example, let's say a user is looking at someone's site running Twenty Sixteen and clicks "Get Theme: Twenty Sixteen" on the action bar and arrives on a theme sheet. 

Once on the Twenty Sixteen theme sheet, they then decide they want to see some other themes before making a decision. The word "Back" implies they will go back to the last page they were on -- another user's site -- not view more themes.

It still seems to me like we still need an "All Themes" link of some kind. Let me know if I'm missing something, though!

**Comment by folletto** [comment]
> It still seems to me like we still need an "All Themes" link of some kind. Let me know if I'm missing something, though!

"← Back" goes back to the full list of themes, so that's the "link of some kind". In your example clicking that will get you back to the full list of themes at `/design`. 
I guess part of he confusion comes from the fact that it's currently not working. :)

_Note that there might be some exceptions that might happen, like coming from the customizer, but we're still evaluating there — we'll review in the future ad-hoc)_

We can rename "← Back" to  "← All Themes", for sure. :)

**Comment by kathrynwp** [comment]
I think renaming the link may be the best solution in that case! Maybe either "Theme Showcase" or "All Themes"?

**Comment by folletto** [comment]
..or "All Designs" / "More Designs"? :) 

![screen shot 2016-05-20 at 22 36 07](https://cloud.githubusercontent.com/assets/4389/15442868/da0e5b84-1edb-11e6-8a35-8b492ecfd66a.png)

**Comment by kathrynwp** [comment]
Since we still refer to them as "themes" in the dashboard and in support docs I think "All Themes" is better for users than "Designs."
