### ISSUE TITLE
Theme Showcase: Filters are cumulative in the search bar.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#54727]
Every time a user clicks on a filter, a new instance of that filter's prefix is added to the search bar (even if that prefix already exists). I believe they're mutually exclusive, so I'd expect only one prefix at a time. If I'm wrong and they're additive, then the filters popover should have an active state for whichever filters have been selected.

![2021-07-20 09 43 20](https://user-images.githubusercontent.com/349751/126363505-4cf7a8e0-bd02-4316-bf74-6fa01b8d59da.gif)

**Comment by mreishus** [comment]
Previous to our design changes, as long as there was any text in the search bar, the welcome bar was invisible. After clicking in the welcome bar once, it would input text in the search bar, which made the welcome bar invisible and it wasn't possible to click again.

That said, I'm not clear what the solution here is. If I click the column button, I would like to see the column dropdown for autocomplete appear. (Autocomplete suggestions are based only on the last word in the search input). However, if the buttons refuse to input text if another selection is already made, that would not work. Maybe it looks for "column: "feature:" "subject:" that is previously existing, not filled out, and replaces it.

I am not seeing autocomplete suggestions in the gif, but I see them on prod, so I assume that is an artifact of the recording software used.

**Comment by kwight** [comment]
@ianstewart @onuro could you let us know how best to proceed here?

> I am not seeing autocomplete suggestions in the gif, but I see them on prod, so I assume that is an artifact of the recording software used.

The autocomplete suggestions only appear for me once I click into the search bar.

**Comment by mreishus** [comment]
Interesting, maybe a browser difference. Here is what I'm seeing in firefox:

https://user-images.githubusercontent.com/937354/126381355-ede9a682-ccb7-4d0c-9317-170039da1c29.mp4

**Comment by ianstewart** [comment]
> I believe they're mutually exclusive, so I'd expect only one prefix at a time. If I'm wrong and they're additive, then the filters popover should have an active state for whichever filters have been selected.

I believe originally they were intended to be additive. So that you could, say, find all the themes that had an author-bio that also had a right sidebar.

![image](https://user-images.githubusercontent.com/545779/126381810-cb611ac9-2c07-4a84-9c8e-177bbb490d68.png)

Which is why I think you'll sometimes get no results by adding up too many filters. We don't have a theme that meets the whole set of criteria.

**Comment by ianstewart** [comment]
I suspect this has been a bug for a while but you can click on the same filter multiple times which is probably unhelpful.

![image](https://user-images.githubusercontent.com/545779/126382533-aefd214d-4d8e-4864-9912-a734b64d2422.png)

**Comment by ianstewart** [comment]
> The autocomplete suggestions only appear for me once I click into the search bar.

This sounds like it's own bug. We shouldn't add the prefix until you click a tag from the drop-down.

**Comment by mreishus** [comment]
The current design of the system is that only certain strings typed into the search bar can trigger autocomplete suggestions, there's no external trigger to make them display. The "Magic Welcome Bar" helps input those strings into the search bar. I'd call it more of a design rework than a bug.

**Comment by kwight** [comment]
@mreishus will try a new option: when a user clicks a filter, we remove all empty filter prefixes from the search bar. This should keep the search bar clean and sensical, while maintaining the ability to search for, say, multiple features at once.

**Comment by mreishus** [comment]
Here's trying that approach: https://github.com/Automattic/wp-calypso/pull/54774

**Comment by kwight** [comment]
Resolved in #54774.
