### ISSUE TITLE
Theme Showcase: Responsive breakpoints for new theme sheets

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#5472]
The responsive breakpoints need some tweaking.

There seems to be only one mobile breakpoint on the new theme sheets, and it kicks in at a quite a narrow width. This means that on smaller screens above 661px, the main column is displayed in an awkward narrow strip along the left, like this:

![twenty sixteen theme wordpress com](https://cloud.githubusercontent.com/assets/7662449/15406998/d7652468-1dd6-11e6-81d1-1f38719091fa.png)
Screenshot from [this page](https://wpcalypso.wordpress.com/theme/twentysixteen) at browser window of about 680px.

Below 661px, the responsive style kicks in and looks acceptable:

![twenty sixteen theme wordpress com-1](https://cloud.githubusercontent.com/assets/7662449/15407036/0bd8e7f2-1dd7-11e6-82d8-78ee661b12a0.png)

-------

On the opposite end of the spectrum, the pages look extremely unbalanced on larger screens, especially with the left-aligned layout, and so much empty right-hand space below the screenshot:

![twenty sixteen theme wordpress com-2](https://cloud.githubusercontent.com/assets/7662449/15407100/4f312a96-1dd7-11e6-8bb1-982058e598c3.png)

**Comment by folletto** [comment]
> Below 661px, the responsive style kicks in and looks acceptable

We chose that one as a balance between a "too big" single column and "too constrained" sidebar. Do you have a suggestion on where to try to break it to see if it works better? :)

> the pages look extremely unbalanced on larger screens, especially with the left-aligned layout, and so much empty right-hand space below the screenshot:

Note that the plan is to "fill" the right side: now we're just using the cropped screenshot, but ideally will should the full height page(s). :)

**Comment by kathrynwp** [comment]
> We chose that one as a balance between a "too big" single column and "too constrained" sidebar. Do you have a suggestion on where to try to break it to see if it works better? :)

I'll get more of the team's eyes on this next week and get back to you with a suggestion!

> Note that the plan is to "fill" the right side: now we're just using the cropped screenshot, but ideally will should the full height page(s). :)

Ah, I see! Should we be adding longer, full-page featured images at the same time that we're going through and updating showcase docs for other things (like removing galleries, shorcodes, etc.)? Or is the plan for these full-page screenshots to be added in some other, more automated way, all at once later? If we'll be adding them manually, now might be an ideal time to do that since the pages are being updated for other things as well. Thanks for letting me know!

**Comment by folletto** [comment]
> I'll get more of the team's eyes on this next week and get back to you with a suggestion!

Thanks!

> Should we be adding longer, full-page featured images at the same time that we're going through and updating showcase docs for other things (like removing galleries, shortcodes, etc.)? Or is the plan for these full-page screenshots to be added in some other, more automated way, all at once later? If we'll be adding them manually, now might be an ideal time to do that since the pages are being updated for other things as well. Thanks for letting me know!

Good point!

We weren't planning to do that in this milestone, but might be worth replacing one with a full height screenshot and see if anything breaks. :)

(One of the reasons why we weren't considering that right now is that most themes have a full height screenshot in the body currently at the first image, and we can't remove that until we retire the other showcases, otherwise they will end up _without_ image... :( )

**Comment by kathrynwp** [comment]
Ah, I understand the dilemma now... I'll run this by the team next week as well.

**Comment by kathrynwp** [comment]
Discussed this with @sixhours and suggestions are:

**Option 1** - add another mobile breakpoint at 1024px, and add some right/left margin to ensure line length is readable

**Option 2** - reduce the size of the big right-hand screenshot faster so the proportions change slightly and the left column is wider than the right

**Option 2** - widen the existing mobile breakpoint to 768px

re: the featured image in the right column, we'll leave them as is for now and then try to do a sprint to go through them after the old showcase pages get redirected to the new.
