### ISSUE TITLE
Image Block FSE: Rotating image for the first time takes time to load, or does not display loading effect

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#54721]
When attempting to rotate image using image block FSE, rotating image takes while for it to happen.

### Steps to reproduce the behavior

1. Add an image using image block.
2. Click on "Crop", then "Rotate".
3. Wait for image to rotate.
4. Click on "Apply" to save changes.

#### What I expected to happen

Image rotates almost instantaneously.

#### What actually happened

User had to wait for a couple of seconds, unknown if the rotate button has been clicked or not.

### Context

Image sample: https://edwinho89testfse.wordpress.com/wp-admin/upload.php?item=24

Comparing to rotating image from wp-admin: https://edwinho89testfse.wordpress.com/wp-admin/upload.php?item=24&mode=edit the page shows that the page is loading while waiting for image to rotate.

#### Does this happen on simple or atomic sites or both?

Currently happening on simple sites while testing FSE

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

gif link: https://d.pr/i/NTvtUg

**Comment by inaikem** [comment]
Pinged @edwinho89 re Bugomattic and added the issue to the HE Triage board.

**Comment by synora** [comment]
Triaged. Working as expected. Within the Site Editor (on a simple site created via the Horizon flow), rotating images occurs instantly within Image Blocks. 

https://user-images.githubusercontent.com/10015451/135472154-20ef746c-5813-4c1f-84ce-87e335e1eeee.mp4

Closing issue for now.
