### ISSUE TITLE
Theme Showcase: New searches cause results to be added to previous searches

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#54739]
### Steps to reproduce the behavior

1. Visit Appearance -> Themes
2. Search `feature:block-templates`, see 4 results 
3. Use backspace and change to `feature:author-bio`, see lots of results
4. Backspace and change to `feature:block-templates`, see ~30 results

#### What I expected to happen

See only 4 results after making another `feature:block-templates` search 

#### What actually happened

Saw 30 results. The results of my previous search were merged into this one.

**Comment by mreishus** [comment]
Slack discussion / investigation: p1626816688196800-slack-C0202PMUXLJ

**Comment by mreishus** [comment]
The correct information is returned from the backend, but the front-end is mixing up data from previous searches together.

The redux store contains "items" and "queries". "items" is a list of every theme encountered so far.  "queries" is an object with keys as every previous search done so far, and values as list of ids matching that search.
![2021-07-20_17-04](https://user-images.githubusercontent.com/937354/126403800-121fc2c3-f22f-443b-8d81-ab8608d2f4d7.png)
When I make a new search, those results are added to every list of results in "queries". These are done by a function called `receive()` in something called the query-manager:
https://github.com/Automattic/wp-calypso/blob/afb214ef8d367bac7045d293cef38ffb34b31ad9/client/lib/query-manager/index.js#L260

**Comment by kwight** [comment]
@DanielSmithMichigan @mreishus Can this be closed now with the merge of https://github.com/Automattic/wp-calypso/pull/54770?

**Comment by mreishus** [comment]
yup, fixed by #54770
