### ISSUE TITLE
Settings: Add Markdown checkbox to writing settings

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#5474]
We currently have a markdown checkbox in /wp-admin/options-writing.php:

![screen shot 2016-05-19 at 4 56 43 pm](https://cloud.githubusercontent.com/assets/2738252/15409410/ae49e5ee-1de2-11e6-912f-fe77da7c2d28.png)

We do not have the setting in Calypso. Let's add it! It probably belongs under https://wordpress.com/settings/writing/:site:

The checkbox will toggle whether markdown is available or not. When toggled on, any posts saved while toggled on will output markdown-generated html instead of markdown itself when displayed. Display is handled by the already existing plugin.

**Comment by rralian** [comment]
I got a ping about adding this feature and had started working on it as well before seeing this issue. This requires a change to our api endpoint code, and it's wpcom-specific, so I was just learning about our new site-abstraction-layer in the endpoint code. I'll start with adding a `markdown_enabled` node to our `site/settings` endpoint.

**Comment by rralian** [comment]
@southp I wound up tackling this in #5508. I would welcome your review though. It requires applying a patch to your sandbox until we merge some necessary API changes.
