### ISSUE TITLE
List block: Direct Copy and Paste breaks list

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#54754]
### Steps to reproduce the behavior

1. Create a new list of items on a page or post
2. Highlight lists above, copy and paste to an empty paragraph

#### What I expected to happen

List block are copied successfully without any issues

#### What actually happened

Pasting List block turns to a paragraph block (though it shows the bullet list at start.

![image](https://user-images.githubusercontent.com/34882260/126472863-be52d649-8bbd-42ad-9c0e-7b449d07986e.png)

#### Does this happen on simple or atomic sites or both?

Both

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/34882260/126472265-0459436d-cfa9-4595-a633-50b50bf8cf1a.png)

```
<!-- wp:paragraph -->
<p><meta charset="utf-8">Original list below:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>list 1</li><li>list 2</li><li>list 3</li><li>list 4</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><meta charset="utf-8">Copy and paste list below:</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><meta charset="utf-8"><li>list 1list 2list 3list 4</li></p>
<!-- /wp:paragraph -->
```

Reported in 30337470-hc

User reported it was working normally before recent update to WordPress 5.8

Workaround:

Expand options, copy the whole block, and paste to a new line.

![image](https://user-images.githubusercontent.com/34882260/126472569-3bc3c7a7-9495-463f-aaeb-d9ce5bd84c67.png)

**Comment by synora** [comment]
Triaged. Can replicate.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
This is now tracked in https://github.com/WordPress/gutenberg/issues/34262.
