### ISSUE TITLE
Cookies Widget: Add 'Reject' Option

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#54785]
User brought us a request for a way to enable a "Reject" option to the Cookies widget, which currently only offers "Accept and Close".  They pointed out that in Ireland, a 'Reject' option is required (see below). 4164035-zen

> If you use a cookie banner or pop-up, you must not use an interface that ‘nudges’ a user into accepting cookies over rejecting them. Therefore, if you use a button on the banner with an ‘accept’ option, you must give equal prominence to an option which allows the user to ‘reject’ cookies, or to one which allows them to manage cookies and brings them to another layer of information in order to allow them do that, by cookie type and purpose.

- [April 2020 Guidance for Cookies and other tracking technologies, from An Coimisiún um Chosaint Sonraí Data Protection Commission, Page 9](https://www.dataprotection.ie/sites/default/files/uploads/2020-04/Guidance%20note%20on%20cookies%20and%20other%20tracking%20technologies.pdf)

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by radtechgh** [comment]
I would like to add a +1 to this issue. User in Italy says: "people now need to have the option of: accepting cookies, customize cookies, or reject"
4665472-zen

**Comment by jeherve** [comment]
Closing as duplicate of https://github.com/Automattic/jetpack/issues/20022
