### ISSUE TITLE
Domain management: Unable to set domain as primary address

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#54788]
One of our customers reported that they were unable to set their domain as their site's primary address. The site's interface language is set to French, and clicking on the option to set the domain as the primary address using the overflow menu in WordPress.com > My Sites > Upgrades > Domains didn't work.

### Steps to reproduce the behavior

1. Go to WordPress.com > My Sites > Upgrades > Domains
2. Click on the overflow menu link (three dots), and select the option to `Désigner comme domaine principal` - nothing happens
3. Observe that the section of the dashboard that should display the current primary address and a button to change this is not loading.

#### What I expected to happen

The customer ought to have been able to switch to a new primary address using either the button on the WordPress.com > My Sites > Upgrades > Domains page or in the overflow menu.

#### What actually happened

The page didn't load correctly, and the user wasn't able to click the usual button to set the domain as the primary address.

In addition, the link for this purpose in the overflow menu doesn't work.

The page only seems not to load correctly when the primary site address is set to the default address. The page loaded correctly after I set the domain to the primary site address using our tools.

### Context

4157504-zen

#### Browser / OS version

I tested this in Chrome 91.0.4472.164 on macOS 11.4 and in Firefox Developer Edition v91.0b3

#### Is this specific to the applied theme? Which one?

I don't have any information on this.

#### Does this happen on simple or atomic sites or both?

This site is on a WordPress.com Premium plan

#### Is there any console output or error text?

Yes, see here: 29d4d-pb/

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

This just seems to affect this site for now.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

The overflow menu on a separate test site:

![pBqb12a](https://user-images.githubusercontent.com/2912202/126628308-34a59d58-d91b-400e-8b27-ff47c715ddef.png)

The loading not completing:

https://user-images.githubusercontent.com/2912202/126627985-d3a892c9-37ab-4d68-a525-de6149a76838.mp4

This is what should be loading, but doesn't when the primary address is set to the `.wordpress.com` address:

![Capture_2021-07-22 at 13 32 29](https://user-images.githubusercontent.com/2912202/126628101-b986f3f2-3794-4e25-910e-2b559f8b2def.png)

**Comment by delputnam** [comment]
It appears that this same domain name was mapped to an atomic site in the past and an old error left an incorrectly set site URL. I've fixed the site URL so that everything should work properly now.
