### ISSUE TITLE
Theme Showcase: Clicking theme popover menu causes page to scroll up.

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/wp-calypso#54803]
#### How to recreate
1. Go to the /themes page
2. Scroll down so you're not at the top of the page
3. Click the [...] (three dots) on any theme card
4. Notice that you're now scrolled to the top of the page and you can't use any of the options in the menu until you scroll down again

https://user-images.githubusercontent.com/10274366/126667690-89d3015e-69f9-49da-8b4a-1bf7c95c4409.mov

**Comment by kwight** [comment]
I don't think this is anything specific to the Theme Showcase – I can see the same behaviour in the [post list screen](https://wordpress.com/posts/) too. 🙃

**Comment by obenland** [comment]
This might be unrelated, in the demo I also noticed the page scrolling up when one of the "Tabs" was tapped on mobile

**Comment by sixhours** [comment]
@obenland yep, maybe related to #54651

**Comment by sixhours** [comment]
Nope, not related. :) Introduced yesterday in a change to the `Popover` component in c8758cd. Tested the hash before that one and it works.

**Comment by p-jackson** [comment]
Thanks for the report! Yes this was introduced by #54682. Fix deployed: #54870.
