### ISSUE TITLE
Theme Showcase: Tab alignment needs refinement

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#54804]
### Steps to reproduce the behavior

1. Go to `/themes/[site]` and add the flag param to the URL: `?flags=gutenboarding/site-editor`
2. Note the Full Site Editing (Beta) tab -- it's lower than the other tabs like Recommended or All Themes
3. Hover over any of the tabs; note the text is not vertically centered within the gray highlight

<img width="548" alt="Screen Shot 2021-07-22 at 12 13 19 PM" src="https://user-images.githubusercontent.com/2124984/126672978-80cfb89c-6cc4-4335-9fe2-df14a2d76497.png">

<img width="262" alt="Screen Shot 2021-07-22 at 12 18 46 PM" src="https://user-images.githubusercontent.com/2124984/126673552-edf3121e-8e2f-4a0b-8bf5-8f3420ec6a8a.png">

**Comment by kwight** [comment]
Fixed in #54937
