### ISSUE TITLE
Image block: update dimensions in real time with drag & drop

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#54800]
### Steps to reproduce the behavior

1. Add an image inside of an image block on a page or post.
2. Use the round selector on the side of the image to drag and drop the image to adjust the size up and down.
3. Note how the Image Dimension height and width values in the Image Settings section of the block do not change in real-time.

#### What I expected to happen
The height and width values should update in real time

#### What actually happened
The height and width values do not update as we resize the image using drag and drop. To see the update values we actually have to click off of the image block and then back on to it.

### Context
User report in 4161542-hc 

Customer believes that the height and width values used to update in real time. I personally can't recall that, but I suppose this should be changed from an enhancement to a bug report if so.

#### Browser / OS version
n/a

#### Is this specific to the applied theme? Which one?
n/a

#### Does this happen on simple or atomic sites or both?
Both, though the behaviour is different.

On simple:
After adjust the image size the height and width values are updated are not updated until we un-click the round selector on the side of the image **and** click off of the image block and then back on to it.

On atomic:
After adjust the image size the height and width values are updated as soon as we un-click the round selector on the side of the image.

#### Is there any console output or error text?
no

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Normal, effects all customers who use this block but does not actually break anything.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Here is a video of the behavior on a simple site:

https://user-images.githubusercontent.com/33190975/126658439-f01ec5af-984b-4ad3-8ed7-abc120f46c6f.mp4

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by alshakero** [comment]
PR ready https://github.com/WordPress/gutenberg/pull/34649
