### ISSUE TITLE
Framework: abtest does not handle 0/100 allocation case properly

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#5480]
When dealing with an A/B test that has the following variations:

* `variation0`: `0`
* `variation100`: `100`

that is, all new users should be allocated to the `variation100` variation, there's an edge case that is not being handled properly.

See the [`assignVariation`](https://github.com/Automattic/wp-calypso/blob/5db429b4d849cfe592a404d2656dcdf49c3fd481/client/lib/abtest/index.js#L176) method. `randomAllocationAmount` can be in the range `[0 to 100)` (that is, not including `100`, because `Math.random` [returns](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) `[0, 1)`). We then check if `randomAllocationAmount <= sum`, but this is incorrect for the edge case when `randomAllocationAmount` is `0`. In this case, this condition will succeed (both values are `0`) and the _new_ (eligible for `variation100`) user will get assigned to the incorrect `variation0` variation.

The float (`randomAllocationAmount`) comparison to an integer (`sum`) could also lead to some problems - like, it's very unlikely that they will ever be equal. We should at least do `Math.floor` on `randomAllocationAmount`.

The `100` case is also making my senses tingling, but I can't seem to find anything wrong it :wink: But I'd love someone else to look at it too.

I think this explains (at least some cases) why some users are assigned to the incorrect variation, for example, in the [`domainsWithPlansOnly` test](https://github.com/Automattic/wp-calypso/blob/14213aae0cbadda1b916919040dcdfb358bb35f0/client/lib/abtest/active-tests.js#L102-L111).

/cc @umurkontaci @lucasartoni

**Comment by umurkontaci** [comment]
Too early to spot what's going on but these users should never hit this line since they are not eligible per their registration dates: https://github.com/Automattic/wp-calypso/blob/5db429b4d849cfe592a404d2656dcdf49c3fd481/client/lib/abtest/index.js#L169

**Comment by umurkontaci** [comment]
Also, those users are not reported in this bucket at all.

**Comment by lancewillett** [comment]
Closing this one as abandoned (during a #bug-scrub). Feel free to re-open in the future.
