### ISSUE TITLE
Themes: Launch Bradford to the public.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#54818]
Let's launch the new Bradford theme to the public. We won't do any sort of en.blog post, but the launch should include a heads-up to support.

@ianstewart has begun the process, so he'll know what tasks remain.

![bradford](https://user-images.githubusercontent.com/349751/126709386-23355e5a-b351-4775-8b10-c995a6f95295.png)

**Comment by kwight** [comment]
@ianstewart internal notes:

> Launch generated themes:
> * got stuck when he got to the translation thing
> * script needs to be rerun to get the screenshots in?
> * and then we need to recommit the theme.

**Comment by sixhours** [comment]
POT file diff is here: D64619-code

**Comment by sixhours** [comment]
Sent Bradford Headstart annotations for translation, Strand ID: 89189

**Comment by sixhours** [comment]
Block highlights screenshot for the showcase /cc @ianstewart 

![bradford-blocks](https://user-images.githubusercontent.com/2124984/127017807-ee2313f5-6e08-47bc-b76a-6115ba6292b3.png)

**Comment by sixhours** [comment]
Screenshot diff: D64631-code

**Comment by sixhours** [comment]
Theme has been Network Activated and Showcase pages published. I'll notify Happiness shortly!
