### ISSUE TITLE
Theme Gen: Add support for universal themes as sources.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#54816]
While the library has been developed to allow any source theme in the future, we've only been using it with Blank Theme up to this point. It's important to move to universal themes (themes that support both traditional and Full Site Editing modes) as FSE rolls out over the next few months; let's verify and prepare the Theme Gen library for any developers coming after us.

See: pd2qbF-cA-p2#comment-233

**Comment by mreishus** [comment]
Testing out using blockbase as the source theme for theme-gen.
* D64650-code : theme-gen: Stop crashing when headstart destination directory does not exist [Deployed]
* D64659-code : ThemeGen: Use different replacement orders for php files [Deployed]
  * This may not be a 100% solution; an alternative might be to rename "blockbase" to two words like "block-base" and to mandate that all future source themes have at least two words in the name, that way we have the context clues to know when to use `-` vs `_` vs ` ` etc.
* We discovered that changing fonts and colors in the customizer on a starter site based on blockbase does not work properly. They reflect immediate changes, but upon F5ing in the browser, they are gone.
  * Tomorrow I'll check to see if we can grab the fonts and colors somehow, anyway, maybe assuming they are changing correctly.
  * Seems to be fixed: https://github.com/Automattic/themes/pull/4336
* D64724-code: theme-gen no longer copies language files [Deployed]
* D63165-code: theme-gen: Add update command [Deployed]
* Screenshot issues?
  * The generated screenshot seems to have a different content width – just curious if that's known/explainable?
  * The generated screenshot has the "get started" banner across the top – that's a known issue, IIRC?

**Comment by kwight** [comment]
> an alternative might be to rename "blockbase" to two words like "block-base" and to mandate that all future source themes have at least two words in the name

I don't see us doing this just for the sake of the library.

**Comment by mreishus** [comment]
I was able to get blockbase style color replacements working: D64982-code

**Comment by mreishus** [comment]
I was not able to get font replacements working, but I added some helpful log messages and code comments about a way to approach the problem: D64994-code
I'll be updating the field guide with a list of its limitations too.

**Comment by kwight** [comment]
Fantastic, thanks @mreishus ! ❤️
