### ISSUE TITLE
Theme Showcase: Add the FSE tab for sites created under the FSE flag.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#54820]
The FSE showcase tab is currently hidden behind the `gutenboarding/site-editor` flag, but this doesn't help those testing FSE; while a tester can create a site with that flag in signup, they'll lose that flag in the URL when navigating Horizon. Let's see if we can get the FSE tab to display based on whether the active site is an FSE-enabled site (rather than depending on the feature flag).

cc/ @ianstewart @mattwiebe

**Comment by Copons** [comment]
Fixed by #55043
