### ISSUE TITLE
Payments Block: One-Time Payments Confirmation Should Not Say "Thanks For Subscribing"

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#54829]
### Steps to reproduce the behavior

1. Add a new payments block
2. Add a payment plan and set the renewal frequency to a one time sale
3. Publish.
4. Make a payment.
5. View confirmation message.

#### What I expected to happen

I expected the message to say something like "Thanks for your payment" that makes sense for a one-time payment.

#### What actually happened

The message said "thanks for subscribing" which applies to a renewing payment frequency, not one-time payments.

### Suggested Change

It would be useful to update this messaging for one time payments to something like "Thanks for your payment"

Better still, it would be great to allow the user to customize the confirmation message entirely.

### Context

#30767671-hc 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Any site using the Payments block for one-time purchases.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Annotation on 2021-07-23 at 11-34-33](https://user-images.githubusercontent.com/30727666/126728336-9d53b91e-32f9-46b3-99ae-2d77c429872e.png)

**Comment by dsas** [comment]
This isn't really some "one off" sentence that's wrong. The email will still include 'subscription price' and 'subscription type' and with the current data we don't know whether it's a subscription or not.

![image](https://user-images.githubusercontent.com/93301/211336215-e3d823e1-d1fe-4a86-a3d3-a6f45f8c1666.png)


Really the whole suite of emails, messages etc need looking at with fresh eyes and a list of use cases but given this is an email heading and is prominent, I'll make this once change.

**Comment by dsas** [comment]
Opened D97345-code
