### ISSUE TITLE
Gutenberg: v11.2.x plugin upgrade

### ISSUE THREAD

**Issue by scinos** [Automattic/wp-calypso#54832]
Previous upgrade: #54393
Release notes:

- [ ] Install and activate
   - [ ] Copy & install v11.2.0
   - [ ] Activate v11.2.0 on edge
   - [ ] Copy & install v11.2.0
   - [ ] Activate v11.2.0 on edge
   - [ ] Activate v11.2.0 on production
   - [ ] Request AT upgrade
 - [ ] Testing
   - [ ] Desktop viewport E2E
   - [ ] Mobile viewport E2E
   - [ ] WPCOM
 - [ ] Publish internal announcements
    - [ ] Slack: #team-calypso
    - [ ] Slack: #wpcom-happy-announce
    - [ ] P2: wpcomhappy
 - [ ] Clean up unused releases
 - [ ] Add log entry to the Gutenberg Upgrade Log
 - [ ] Open a new issue for the next upgrade, transfer remaining tasks, close this issue.

 ### Blockers 🤷‍♀️

 ### Other Issues 🐛

 **Issues transferred from previous release(s)**
 ---
 cc @inaikem @simison

**Comment by chad1008** [comment]
Closing in favor of #54859 (looks like we just wound up with two accidentally this round)
