### ISSUE TITLE
Jetpack Connect: remember sites that have previously been connected and are reconnecting

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#5483]
#### What I expected

A user reconnects their site to wp.com via Jetpack and we 'welcome them back' in all the copy. We still have their shadow site and can tell if they are simply cycling the connection.

#### What happened instead

Currently all connections are treated as a new connection, which doesn't feel very welcoming or smart.

cc @johnHackworth

**Comment by johnHackworth** [comment]
I'm closing this issue because it's replicated in https://github.com/Automattic/wp-calypso/issues/5483

**Comment by tyxla** [comment]
I think @johnHackworth meant https://github.com/Automattic/wp-calypso/issues/6689.
