### ISSUE TITLE
My Home: Add Growth Summit card to primary cta area

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#54850]
### What

The growth summit is happening in august 2021 and we'll need to reinstate the promo card for it

### Why

We need to promote the event in my home to current customers.

This card was displayed in 2020 so it should still exist in the code! cc @autumn

### How

<img width="1591" alt="Screenshot 2020-07-21 at 14 34 57" src="https://user-images.githubusercontent.com/214813/126823105-70e185cd-f369-4d23-a67b-95979cd11913.png">

Details from the marketing team:

**Title:** The WordPress.com Growth Summit
**Copy:** Join us August 17th (Americas + EMEA) & August 18th (APAC) to get expert advice on how to grow your audience and earn money.
**Button copy:** Register today for $25 USD!
**Link:** https://wordpress.com/growth-summit/?utm_source=my_home&utm_medium=organic_social_media&utm_campaign=myhome&flags=a8c-analytics.on,ad-tracking,google-analytics&ga_optimize=on

Please ping Selena Jackson for final approval.

**Comment by p-jackson** [comment]
The logic for displaying the card has been removed, but you can see what the previous logic was here: D54035-code
