### ISSUE TITLE
Posts: (and Pages): restore from Trash doesn't update view to remove post

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#5488]
Raised first by @m in Slack this is more of UX polish for a superb experience than a bug. Sharing it here so we can improve the app, especially in terms of the "real-time" data capabilities of Calypso framework. And in context of multi-author sites.

**What I expected to happen:**
A page is in the trash. I load the page with it in the trash in Calypso. Someone else restores it from trash.

**What actually happens:**
For me it still shows up as in the trash, never updates. (Only with a page refresh using browser refresh action.)

In fact, after clicking the navigation links (Published, Drafts, Scheduled, Trash) -- I'd expect the view to refresh. It does for views except Trash, which needs a full page refresh to update.

When a single user makes the action to restore a post or page, the Published list isn't updated without a full page refresh.

When a second user is logged in, same view but different session — the original post or page is stuck in "Published" even after a navigation change to Trash and back to Published.

**Notes:**
- This happens with posts and pages both
- The in-view refresh seems to be working a bit better in other views other than trash (such as Drafts), but Trash seems to needs a full page refresh to make it eventually work whereas other views seem to update with just a navigational change
- Would be ideal if view updates happened without user intervention: automatically

**Video with visual explanation:**

2 min 17 sec, MOV format: https://cloudup.com/c7RwSXmKQrb

I think overall we can nail two things:
1. Improve how the posts / pages views are refreshed after an action (no click, refresh, user action required) — same user, same session.
2. Improve how same behavior works across sessions, multiple users: the views could update without a full page refresh, or even without any navigation.

See also
- #4793 Posts: Controls disappear when trashing a draft

**Comment by hoverduck** [comment]
#bug-scrub

This is still an issue, but is slightly better.  As shown in the GIF below the page doesn't require a full refresh to show the new Trashed/Published status, but the user does need to click on something to reload the list.

![wp-calypso-5488](https://cloud.githubusercontent.com/assets/7233112/19449691/98cb5258-9474-11e6-989a-aa0b73565f63.gif)

**Comment by lancewillett** [comment]
Confirmed this is working much better now — after restore, the counts refresh and the page confirmation is correct.
