### ISSUE TITLE
Signup: Persistent invalid domain notice

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#549]
If I enter an invalid domain using Chrome and correct it after the notice appears the notice will not update. I expect it would disappear after correcting the domain.

![image](https://cloud.githubusercontent.com/assets/545779/11347142/c3fd3618-91e5-11e5-8e57-ac4b9e1366ab.png)

**Comment by fabianapsimoes** [comment]
This seems to have been fixed. See:

![domain](https://cloud.githubusercontent.com/assets/1248436/13320369/c95fb7d4-dbc8-11e5-84ed-4e50865005e0.gif)
