### ISSUE TITLE
Add eligibility logic to POST_LAUNCH view

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#54919]
I added the VIEW_POST_LAUNCH in D64174-code to work with the primary card slider component.

But currently when VIEW_POST_LAUNCH is displayed, it just returns all cards to the front end. VIEW_POST_LAUNCH should use eligibility logic corresponding to what is currently in the `is_view_applicable` function in `home/views.php`.

For example, the webinars promo card should only be shown for 7 days from when the site setup checklist was completed.

The shuffling behavior should also work as before.

**Comment by roo2** [comment]
Diff ready for review D64878-code

**Comment by p-jackson** [comment]
D64878-code has shipped

**Comment by p-jackson** [comment]
No it hasn't ...

**Comment by autumnfjeld** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/c7cb9dee-3c6f-488e-96e3-76db13f87c0d-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)
This can be shipped once https://github.com/Automattic/wp-calypso/pull/55089 is shipped.
Correct me if I got that wrong @deBhal & @roo2 . 
p1628121874050900/1628119955.044000-slack-CRWCHQGUB

**Comment by roo2** [comment]
phew, yep just once #55089 is shipped, if this were shipped first (a8c dev's only) would see multiple cards but not be able to dismiss them.
