### ISSUE TITLE
Dashboard Quick switcher not appearing in WP-Admin when clicking on the Block editor sidebar

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#54920]
### Steps to reproduce the behavior

1. Go to WP-Admin/edit.php (for Posts)
2. Click on a Post (doesn't matter which one)
3. Click on the WordPress menu logo (Block editor sidebar) and click on "All Posts" link.
4. You'll be redirected to edit.php?post_type=post
5. Click on "Screen options" and notice that the button for switching to Calypso interface is missing.

#### What I expected to happen
The `Use WordPress.com view` button should be displayed
#### What actually happened
It's missing

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both Simple and Atomic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects Simple and Atomic sites when going back from Block editor
#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

To fix this, we'll just need to add a new mapping in `projects/plugins/jetpack/modules/masterbar/admin-menu/menu-mappings.php` for `edit.php?post_type=post`.

**Comment by jordesign** [comment]
Can confirm this behaviour is still in place.
