### ISSUE TITLE
Masonry Block: If Captions have a text link, some or all caption text will disappear when a new image is added

### ISSUE THREAD

**Issue by sbathompson-he** [Automattic/wp-calypso#54936]
### Steps to reproduce the behavior

On a page with the Masonry Block set up and captions all added in if another image is added, all the captions disappear. The user then needs to re-add these captions back once again. 

https://user-images.githubusercontent.com/77308634/127203765-97a1be6c-0425-4f50-adb7-507195150a68.mp4

#### What I expected to happen
- Captions should not disappear

#### What actually happened
- They disappeared

#### Workaround
Just have text in the captions, and put the link using the Link settings of the image.
![image](https://user-images.githubusercontent.com/15944096/131460932-245a7a5e-ccd3-4eec-bcde-78ff54401687.png)

#### Is this specific to the applied theme? Which one?
- Lovecraft Theme

#### Does this happen on simple or atomic sites or both?
- Simple so far

#### Is there any console output or error text?
- No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
- No

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
- Yes, every time

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
- Added above

4177958-zd-woothemes
30836556-hc

**Comment by devNigel** [comment]
I ran into this ticket recently. I noticed on my testing that the issue happened only with those existing Masonry Blocks. I was not able to reproduce the issue on new Masonry blocks.

I advised them to create a new Masonry Block for the time being.

**Comment by formosattic** [comment]
From further testing, content disappears but the behavior is erratic, either happens:

* text caption remains but text links and any content after will get removed
* whole captions is removed

Issue happens on Simple sites, and Atomic sites (wether Gutenberg disabled or not).

Also happens on .org with just CoBlocks enabled, but whole captions disappear.
Reported it at https://github.com/godaddy-wordpress/coblocks/issues/2009

Updated the initial report with a workaround.

**Comment by formosattic** [comment]
Unable to reproduce this now, so will close.

**Comment by alliebbush2** [comment]
This is also occurring in the Balasana theme. ZD: #4870225

**Comment by Robertght** [comment]
Another case in 5959322-zen.

We can only replicate this if we have a simple site with CoBlocks on it.
