### ISSUE TITLE
Tortuga - featured image setting missing in editor

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#54942]
A user reported that the featured image settings have disappeared in the editor. I was able to confirm this using the theme demo: https://tortugademo.wordpress.com/

### Steps to reproduce the behavior

1. Activate the Tortuga theme: https://wordpress.com/theme/tortuga/
2. Create a page/post
3. In the editor, try adding a featured image
4. Observe that the option is missing

#### What I expected to happen

I expected to be able to set a featured image.

#### What actually happened

The featured image setting is missing. 

### Context

30840165-hc / 4178686-zen

#### Is this specific to the applied theme? Which one?

Tortuga

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1134" alt="Markup 2021-07-27 at 14 06 06" src="https://user-images.githubusercontent.com/39252765/127223083-c0b8ad2e-564c-41aa-901c-096a05d73b50.png">

**Comment by villanovachile** [comment]
Can we close this in favor of this issue I reported here: https://github.com/Automattic/wp-calypso/issues/54943

This issue affects multiple themes and appears to be isolated to Gutenberg.

**Comment by metabreakr** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/54943
