### ISSUE TITLE
Task: Show the App Banner on mobile web after site creation 

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#54948]
## What

Update when the mobile web App Banner that is displayed on the WordPress.com mobile web.
![image](https://user-images.githubusercontent.com/5665959/127231409-f884940a-2269-4b94-b362-2e9302b64f50.png)

In https://github.com/Automattic/wp-calypso/pull/42164 the banner was set to show:
if the site is [_older than 1 <s>week</s> hour and launched._](https://github.com/Automattic/wp-calypso/pull/42164/files#diff-b78545f34bb9d1f105686d041bd86f6e10f2d913ee167be544bb4631d5360199)

**New specs**
Remove the condition that the site must be launched and _show the App Banner immediately after site creation_.  @yaelirub please confirm that is the desired behavior.

**Comment by simison** [comment]
> if the site is older than 1 week and launched.

This was later changed to 1h: https://github.com/Automattic/wp-calypso/pull/46649 with some other changes to logic as well: https://github.com/Automattic/wp-calypso/pull/46650

What's the plan in terms of avoiding this looking like in the screenshot above?

**Comment by arthur791004** [comment]
@autumnfjeld Do you mean revert https://github.com/Automattic/wp-calypso/pull/42164? Or what's the definition “after site creation”? As @simison said, if we follow the new spec, we need to deal with the original problem.

Here are possible solutions:
- The App Banner should push up the screen, so there is no overlay between guide and App Banner (But I think it might be not easy to do)
- Show the App Banner after the user finished the guides

How do you think?

**Comment by yaelirub** [comment]
Hey everyone, I think there is a bit of confusion as to the ask. the change we were asking to revert is this one: https://github.com/Automattic/wp-calypso/issues/52995

**Comment by arthur791004** [comment]
@yaelirub just to clarify that the new spec is showing  'WordPress App' card no matter the user has connected with the mobile app or not, right?

**Comment by autumnfjeld** [comment]
@yaelirub @arthur791004 
> Hey everyone, I think there is a bit of confusion as to the ask. the change we were asking to revert is this one: #52995

#52995 was never completed. This is the code D62067-code that would have made that change, it was never merged, because there was pushback against that idea. Thus that card on My Home shows regardless of if the user downloaded the app or not.  Additionally changes in this diff D62243-code fixed issues where the card was missing on some devices, so now the Mobile App Card on My Home is actually showing more.

Could you double and triple check that you don't want the work in this issue complete?  Because this work is what you and @davemart-in have talked about on two different occasions:
pbArwn-2nd-p2#comment-3423
and just a couple days ago: pd2qGl-cM-p2#comment-383
I also described the potential confusion here: pbArwn-2nd-p2#comment-3428

We will pause work on this, in https://github.com/Automattic/wp-calypso/pull/54967, until we get clarity.   
![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)

**Comment by autumnfjeld** [comment]
@simison 
> 
> This was later changed to 1h: #46649 with some other changes to logic as well: #46650
👍 
Also, I believe the fact that the[ banner is hidden until site launch](https://github.com/Automattic/wp-calypso/blob/779855d60c008f83080fa2649fe3fa26d56bbd04/client/layout/utils.ts) is in opposition to the goals of _increasing visibility of  the banner_.  cc: @yaelirub 
> What's the plan in terms of avoiding this looking like in the screenshot above?

There was no discussion of any design change--is that what you mean?   This issue isn't about design change but, if there is opinion that the current design is a problem we can open another ticket.

**Comment by razvanpapadopol** [comment]
@poligilad-auto, I've proposed a solution in https://github.com/Automattic/wp-calypso/pull/57140 that prevents the banner to be overlapping with the Editor Welcome Tour with the following logic:
1. In Calypso (Stats, Notifications, Reader, etc) the app banner is displayed immediately for all sites, including unlaunched.
2. In page/post editor, the banner is displayed only when the following two conditions are true:
  * The Editor Welcome Tour has been dismissed.
  * The site is older than 30 minutes (window of time when we force the welcome tour for all new sites)
  
Meanwhile, we can think of a solution to show the mobile app banner sooner inside the editor, maybe even as part of the welcome tour as mentioned in p1633638889049100-slack-C01VA0R5NKY

**Comment by razvanpapadopol** [comment]
With https://github.com/Automattic/wp-calypso/pull/58524 merged, is this issue good to be closed, @escapemanuele?

**Comment by escapemanuele** [comment]
Yes, the App Banner is now shown **before** the Editor Welcome Tour, without waiting for the site to be older than 30 minutes.

**Comment by razvanpapadopol** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/58524
