### ISSUE TITLE
Atomic: WC_Rest_Controller error (Jetpack refused to work properly when WooCommerce is not active/not installed on the website)

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#54950]
GitHub for collecting reports.

Atomic sites. Users mentioned they can't edit any pages and keep seeing `Class 'WC_REST_Controller' not found` error.

This GH issue is for reporting this (I'm still checking what's going on ) and to collect reports. At first, I thought this is related with WooCommerce, but two of the websites don't have Woo/Woo is inactive.

I also found inactive Woo plugin caused the site's Jetpack connection in limbo. Jetpack looks connected on CLI (and it is,) but the dashboard still displaying Calypso-display with no reference at all to WP Admin menu items.

#### Does this happen on simple or atomic sites or both?
Atomic

Slack ping call: p1627441432162000-slack-CB0B2G43X

---

## Update:

Activating Woo-related plugins resolved this issue.

Also, a really interesting workaround (in case the user doesn't want Woo):

- Activate/install Woo then see the issue resolved
- Then, deactivate Woo and delete Woo plugin

This is not ideal since editing pages should be possible *with or without* specific plugin to be active on the website. Is it possible to check and ensure that users are still able to update/edit their pages without having to install and activate Woo?

---

**Update**: The cause is recent deployment for WCPay by default experiment. Developers are aware of this.

**Comment by cuemarie** [comment]
User example, now resolved thanks to activating Woo-related plugins: 30616918-hc // 4179254-zd-woothemes

**Comment by marutim** [comment]
- Another report here: hc-30525888
- Activating the WooCommerce plugins fixes the issue
- Following up with the user: zd-4179275

**Comment by tarunvijwani** [comment]
Another report - HC-26667142

**Comment by edwinho89** [comment]
Similar report: 26496909-hc and 30844556-hc 

Activating WooCommerce plugin fixed it.

**Comment by tarunvijwani** [comment]
Another report: HC-30243079

Activating the WooCommerce plugin fixed it.

For those users who don't want the WooCommerce plugin, deleting the plugin from CLI after activating it will also fix the error.

**Comment by marutim** [comment]
- Another report here: hc-17802862
- Activating the WooCommerce plugins fixes the issue
- Following up with the user: zd-4179286

**Comment by rosepajaroja** [comment]
Another report here: HC-30844003
Activating the WooCommerce plugin fixed the issue

**Comment by galakhyati** [comment]
Another two reports:

30690308-hc, Follow up: 4179290-zd-woothemes.

30844257-hc, Follow up: 4179295-zd-woothemes.

In both cases activating the WooCommerce plugin fixed the issue.

**Comment by adelineyaw** [comment]
Another report 29001669-hc
Activating WooCommerce fixed the issue

**Comment by tarunvijwani** [comment]
Another report: 29177230-HC

**Comment by devNigel** [comment]
Another report:

* 4179302-zen
* 4179249-zen
* 30825594-hc, follow up: 4179324-zen

WooCommerce was activated on the site to fix the error.

**Comment by marutim** [comment]
- Another report here: hc-30799733
- Following up with the user: zd-4179342
- Activating the WooCommerce plugins fixes the issue

**Comment by ghost** [comment]
Another report: hc-28402644
Follow up: zd-4179404
Activating the WooCommerce fixed it.

**Comment by happychait** [comment]
Got one in 30845128-hc

Activating the WooCommerce plugins fixed the issue.

**Comment by hacchism** [comment]
Another one in zd-4179205

Deleting WooCommerce via CLI fixed the issue.

**Comment by retnonindya** [comment]
This is now **RESOLVED**! We have deployed a revert and things should work properly now. Thank you for the updates and the hard works, folks! I'm closing this GH issue 🙇
