### ISSUE TITLE
Themes: flash of content (SSR?) on Edge / IE11

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#5495]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/theme/mood
2. Open that in Edge / IE11
3. The page appears, then goes blank!

#### Browser / OS version

Win 10 both Edge and IE11

#### Screenshot / Video

![cap-](https://cloud.githubusercontent.com/assets/4389/15440356/f3577de6-1ecc-11e6-8ceb-8deb9fda3945.gif)

**Comment by ockham** [comment]
Any errors shown in the console?

**Comment by folletto** [comment]
IE has a console? :P 

Here's Edge's:

![screen shot 2016-05-20 at 23 05 02](https://cloud.githubusercontent.com/assets/4389/15443324/511802ea-1edf-11e6-9d6a-af50a0387cc1.png)

Expanded:

![screen shot 2016-05-20 at 23 05 57](https://cloud.githubusercontent.com/assets/4389/15443329/6bd25d56-1edf-11e6-856e-f8cde58ead19.png)

Given that "Re-auth" I tried to login again, but while it removed that issue, the blank content flashed again:

![screen shot 2016-05-20 at 23 09 09](https://cloud.githubusercontent.com/assets/4389/15443403/dfd5baf4-1edf-11e6-9c90-a77ea96c0385.png)

**Comment by ockham** [comment]
What happens if you try to access other parts of Calypso?

**Comment by folletto** [comment]
Other parts of Calypso are fine.

If I try to navigate there instead of directly opening the URL, just shows the loader skeleton:

![screen shot 2016-05-23 at 20 43 49](https://cloud.githubusercontent.com/assets/4389/15482370/1f7d7cd4-2127-11e6-8df3-b912e52c1193.png)

**Comment by seear** [comment]
Likely cause is the use of `default` locale here:
https://github.com/Automattic/wp-calypso/blob/master/client/state/themes/theme-details/selectors.js#L20

This needs changing anyway since `style: 'currency'` is not supported in most browsers.
