### ISSUE TITLE
Editor: Fixing selecting/editing paragraph text copy

### ISSUE THREAD

**Issue by saygunnyc** [Automattic/wp-calypso#54981]
### Steps to reproduce the behavior

1. Go to any P2 to post within full-editor within WordPress.com
2. Click on '+' to create a paragraph block.
3. Write down or copy/paste 2 lines of copy
4. Try to select the full copy starting from bottom-right towards upper-left.
5. Change the copy styling to be Bold, Italic.

#### What I expected to happen
You would normally expect the full copy to switch to Bold/Italic as it looks like the whole copy is selected.

#### What actually happened
However only a part of the copy changes, as somehow it's not fully selected even if it seems like it. And the actual selected copy changes each time randomly.

### Context
I checked this on core and it seems like everything is fine there. Seems like this is a WordPress.com bug.

#### Browser / OS version
Google Chrome Version 92.0.4515.107 (Official Build) (x86_64)
OSX Version 11.4

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
Not on the core.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It's really annoying once editing copy on a post.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/78876323/127381018-c5f66211-cbee-44c7-a8c1-b6b25c7fef55.mov

**Comment by getdave** [comment]
Is this specific to Calypso or does this happen on a fresh install of WordPress? I ask because this might be a Gutenberg Core issue.

**Comment by saygunnyc** [comment]
Hey @getdave, when I tried on a hosted WordPress I didn't experience the same issue. However, when I chatted with @shaunandrews about the issue, he was able to replicate it on WordPress as well, and the problem seemed to resolve when he disabled Jetpack. I haven't personally had the chance to test but it seemed like this has something to do with Jetpack.

**Comment by mreishus** [comment]
I was able to reproduce this on a standalone core installation: 
* Cloned https://github.com/WordPress/gutenberg
  * (Optional) _Verified that `.wp-env.json` had no extra plugins from previous experiments ( `"plugins": [ "." ],` )_
* Cd into it and `wp-env destroy && wp-env start` to create a clean WP
* Visit http://localhost:8888/wp-admin/ and login with admin:password
* Created a new post
* Create a paragraph block with two lines of text
* Select all text with click and drag (either starting from the top left and going to the bottom right, or starting from the bottom right and going to the top left), and click bold and italic buttons

https://user-images.githubusercontent.com/937354/133327404-f9a9967c-609b-4600-bfc9-c6dd05c7d2fa.mp4

* Video is on the following gutenberg commit:
  * `ca67d60363      Siobhan Bamber  Fri Sep 3 17:15:04 2021 +0100   [RNMobile] Resolve Text Entry Issues/Errors in Alt Text Settings  (#33975)`
  * options-general.php show this WP version: `You are using a development version (5.9-alpha-51813).`

Tagging @getdave

**Comment by getdave** [comment]
Thanks for verifying @mreishus. I can confirm this is an Issue with Gutenberg which I can replicate on a clean install.

Would you be able to raise an Issue in the Gutenberg repo so that someone can take a look.

@ellatrix will probably want to be aware. 

I will say I'm finding it difficult to replicate _consistently_. There is some condition which I'm yet to isolate which causes the selection to be incomplete...

**Comment by mreishus** [comment]
It looks like this is already reported: https://github.com/WordPress/gutenberg/issues/33712

**Comment by getdave** [comment]
[Here's a comment which has narrowed down the conditions](https://github.com/WordPress/gutenberg/issues/33712#issuecomment-901520115) to reproduce this error.

**Comment by synora** [comment]
Triaged. Can replicate. The link @getdave references in the comment above is spot-on!

**Comment by dpasque** [comment]
Closing in favor of the core issue here: WordPress/gutenberg#33712
