### ISSUE TITLE
Paragraph Block:  Selecting Color from Toolbar doesn't change text color in editor

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#54990]
_2023-10-04 update - this issue has been remained open as themes are fixed on a theme-by-theme basis.  The only remaining theme that this is currently waiting on is Karuna. See [latest comments](https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-1747785420)_

---

When you select some text in a Paragraph block and change the color using the Font Color option on the toolbar, it changes the color on the front end, but not in the editor. 

### Steps to reproduce the behavior

1. Activate the Rebalance theme
2. Create a new post and add a Paragraph block
3. Add some text to the Paragraph block; highlight one word in the text and click the Text Color option under the down arrow on the toolbar:

![screenshot](+)
Image URL: 

4. Select a color
5. Publish the page.

#### What I expected to happen
I expected to see the font color in the Paragraph block change in the editor.

#### What actually happened
The font color was added to the Paragraph Block toolbar, but it didn't change the font color in the editor:

![screenshot](+)
Image URL: 

However, the font color did change on the front end:

![screenshot](+)
Image URL: 

#### Browser / OS version
I was using Chrome on Mac version 10.15.7

#### Is this specific to the applied theme? Which one?
I've been able to reproduce it on Rebalance and Dara. I tried testing on Dalston, Twenty Twenty, and Ryu but couldn't reproduce there. It seems like it may not happen on Recommended themes.

#### Does this happen on simple or atomic sites or both?
I only tested on Simple Sites

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
I have only had one report, but I can reproduce it on my test site.

4173857-zen

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

**Comment by inaikem** [comment]
Thanks for raising this issue! I am able to replicate on my test sites.

Wondering if this and `When Headings Font Size Set in Customizer, Type Scale is Ignored on Blog Posts Block Post Titles` (#54911) are somehow related?

**Comment by alshakero** [comment]
Can confirm reproducing this. It's reproducible in Rebalance theme, but not all themes. We'll investigate the issue today.

**Comment by alshakero** [comment]
PR ready here https://github.com/Automattic/themes/pull/4359

**Comment by tellisbethel** [comment]
I believe I've encountered a version of this bug here: 4233694-zen
The only difference is that when selecting the text colour, the text changes to the wrong colour in the editor (instead of not changing at all), but then reflects the correct colour when previewing or on the live site.

**Comment by goblinartificer** [comment]
An interesting rendition in 4257432-zen today: the colors look right _until_ you try to apply any other text decoration, then only the bold/underline/etc shows up. The preview is right, but the editor is wrong.

**Comment by hacchism** [comment]
Another instance in 4293838-zen with Canard theme.

**Comment by thekingsprojects** [comment]
Also seeing this in the Aquene theme: 14276663-hc and replicated on my own test site. Not sure if we're doing anything about that given that's a retired theme now, but worth noting, I suppose.

**Comment by sbathompson-he** [comment]
Experienced this bug on the Affinity theme here: 30538090-hc

**Comment by tellisbethel** [comment]
Preview colour is right but colour in editor when using the palette (not the picker) is wrong: 30511716-hc
Simple site.

**Comment by alshakero** [comment]
Hi @scruffian! I have sent a [PR](https://github.com/Automattic/themes/pull/4359) to fix this issue earlier. It's probably a bad PR but will give you a clear idea about this issue. Can you please give it look? Thanks!

**Comment by EjayhanFernandes** [comment]
This occurred as well here 4320518-zen. 
Theme: Gateway by Rescue Themes.

**Comment by ahmadbaig1** [comment]
User returned and requested a quicker resolution 31830828-hc.

**Comment by inaikem** [comment]
@Robertght, do you think this is something for Flow Patrol could look into?

**Comment by Robertght** [comment]
Thanks! I've added it now. cc @Automattic/flow-patrol-create

**Comment by benchilcote** [comment]
Adding another report - 22972062-hc

Theme isola.  Simple site.

**Comment by ccwalburn** [comment]
Another report - 4335926-zen
Theme: Lovecraft

**Comment by dcoleonline** [comment]
Reported in 31927285-hc
Theme: Baskerville 2
We should follow up in 4337424-zen

Example:
![image](https://user-images.githubusercontent.com/3505172/135360786-1dacb518-9a65-4316-99f9-5cd9c6b3088d.png)

**Comment by nicolynramos** [comment]
Another report for Lovecraft, simple site - 31984931-hc

**Comment by kosiew** [comment]
Hi @nicolynramos ,

Thanks for reporting this

I could reproduce this on a Simple site and Atomic site on the Lovecraft theme.

**Comment by kosiew** [comment]
I also tested that the on Rebalance, the Paragraph block text color does change.

**Comment by scruffian** [comment]
I believe this will be fixed by https://github.com/WordPress/gutenberg/pull/35514. It might take some time for that commit to make it to simple/atomic sites....

**Comment by mzitinfo** [comment]
We just had another case of this in 4368273-hc, with the Independent Publisher theme.

**Comment by KokkieH** [comment]
The Text Color option appears to be completely missing from the toolbar drop-down:
![New_Post_‹_kokkiestrialtestsite_—_WordPress_com](https://user-images.githubusercontent.com/11873759/137579286-02bdc0b7-2900-4742-aff6-ff878399b9a6.png)

There's also now a Highlight option which isn't present in the screen shot at the top of this issue, which makes me wonder if #57036 might be somehow related. 

Missing Text Color option pointed out by user in https://wordpress.com/forums/topic/no-colors/

**Comment by KokkieH** [comment]
It appears this is intentional. See #57054.

**Comment by DjamWork** [comment]
Maybe another case here zd-4379749
user wants to change the link color.

**Comment by Nic-Sevic** [comment]
Another instance here: 27931525-hc

Also +1 to labelling this as text highlight being confusing. I would expect highlight to change just the background color, not the text itself

**Comment by as-esu** [comment]
4657930-zen
I could reproduce the issue using the Karuna theme, but only if I choose the suggested colours. 
Picking custom colour, reflected changes in the editor.

**Comment by francoishvz** [comment]
Another instance here: 35792663-hc

Workaround was to pick a custom color.

**Comment by cometgrrl** [comment]
> I could reproduce the issue using the Karuna theme, but only if I choose the suggested colours.
> Picking custom colour, reflected changes in the editor.

Same for me (although white is suggested and displayed correctly in the editor, none of the others worked).

**Comment by cometgrrl** [comment]
@jeffikus Can you take a look at this? It seems there's at least one more theme (Karuna) that's affected by this bug.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Normal` to better reflect it's status in the larger context of open bugs in the repo.
- Looks like this is getting fixed at the theme level, which is why it's still open - waiting on a fix for Karuna:

https://github.com/Automattic/wp-calypso/assets/27249804/5d3c129a-3452-4d5e-b06f-b08a6dd6c760


CC: @Automattic/theam

**Comment by alaczek** [comment]
This is fixed now in Karuna too. Closing.
