### ISSUE TITLE
Professional Email description in signup overflows available space on mobile

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#55017]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/start/domains?flags=signup/professional-email-step
2. When the Professional Email signup prompt appears, the description can seen to overflow available space. So far I have tested certain device types: issue on Galaxy and iPhone devices. Fine on iPhone Plus devices. Haven't tested the exact width just yet.

#### What I expected

Description does not overflow.

#### What happened instead

Description overflows.

#### Browser / OS version

Firefox 90.0.2 (64-bit).

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/18581859/127472165-028e7696-adab-4be0-8d1f-a970fdf34c74.png)

![image](https://user-images.githubusercontent.com/18581859/127472177-5442cc08-9d87-4029-842e-a7c01c29057e.png)

![image](https://user-images.githubusercontent.com/18581859/127472196-d47a9384-af1b-48c4-bef8-baf2b4223999.png)

#### Context / Source

Internal testing: p9anKZ-1VR-p2#comment-3857

**Comment by inaikem** [comment]
Thanks for raising this issue! I am able to replicate.

Long, unbroken text strings won't normally break over multiple lines unless explicitly told to (however, if the string contains a hyphen it will break across multiple lines at that point).

It's possible to target just the domain on this page using some CSS, which would make it behave as follows:
&nbsp;

<img width="414" alt="Screenshot on 2021-08-02 at 22-16-34" src="https://user-images.githubusercontent.com/66711744/127876355-38332abd-1cbc-4c82-9b3f-e6a5caa88ae8.png">

```
p.formatted-header__subtitle strong {
    word-break: break-all;
}
```

However, I'd think a more robust solution would be desired and I'm moving this into the triaged queue as we speak!

**Comment by alshakero** [comment]
PR ready https://github.com/Automattic/wp-calypso/pull/55125
