### ISSUE TITLE
Help icon on the signup flow has a broken style that makes it appear as if they are two icons

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#55016]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/start/domains?flags=signup/professional-email-step
2. See that the help icon (bottom right of the screen) has a broken style that makes it appear as if they are two icons
3. This does not occur if you start at https://wordpress.com/start/ or https://wordpress.com/start/domains

#### What I expected

The help icon appears as a single icon.

#### What happened instead

The help icon appears as if it overlaps another icon

#### Browser / OS version

Firefox 90.0.2 (64-bit).

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/18581859/127471706-f2d7edc3-d497-42c1-8c5e-397f6248eea7.png)

![image](https://user-images.githubusercontent.com/18581859/127471714-4f7bc872-7ddb-4269-a0f4-6144fc7e9cb6.png)

#### Context / Source

Internal testing: p9anKZ-1VR-p2#comment-3856

**Comment by inaikem** [comment]
Thanks for the report! I can replicate. 

It looks like the selector `.button.is-borderless.inline-help__button .gridicon` has a margin call that is out by a few pixels.

Correcting `margin: -3px 0 0 -3px;` to be `margin: -6px 0 0 -3px;` aligns the nested the SVG inside `<button title="Help" ...>`

CSS is at: https://wordpress.com/calypso/evergreen/async-load-calypso-blocks-inline-help.7f2e9c0c6b6618064d0f.min.css
