### ISSUE TITLE
My Home: interaction weirdness on Quick Links

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#55035]
### Steps to reproduce the behavior

1. Go to My Home selecting a dotcom simple/atomic site; e.g.: https://wordpress.com/home/SITE_URL
1. Click repeatedly on Quick Links.
1. See error.

#### What I expected to happen

The section to expand/collapse when I click the card.

#### What actually happened

The section seems to suffer a delay when clicked repeatedly, where it expands/collapses way after it's been interacted with.

### Context

—

#### Browser / OS version

- Version 92.0.4515.107 (Official Build) (arm64)
- MacOS Big Sur 11.4 (20F71)

#### Is this specific to the applied theme? Which one?

No.

#### Does this happen on simple or atomic sites or both?

Both.

#### Is there any console output or error text?

No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Very easily reproducible with just a few clicks.

#### Video

https://user-images.githubusercontent.com/390760/127543578-a3308540-b782-4af7-aa61-a558a28786fb.mov

**Comment by autumnfjeld** [comment]
I could not reproduce this, the collapse/expand seems to be working perfectly.
