### ISSUE TITLE
User Theme JSON is inappropriately stripped of data

### ISSUE THREAD

**Issue by pbking** [Automattic/wp-calypso#55030]
## Description

In some environments (wpcom being the only that I have found) when the User Theme JSON is saved and retrieved relevant data is removed.

## Step-by-step reproduction instructions
* Activate a Blockbase theme.
* Using the customizer adjust the colors so that there are custom colors set and publish.
* Observe the User Theme JSON returned by WP_Theme_JSON_Resolver_Gutenberg (this is tricky and I have only been able to do this by echoing the variables as this is only reproducible for me on wpcom).
* Note that the `settings.color.palette` value is appropriately set.
* Using the customizer adjust the FONTS so that there are custom fonts set and publish.
* Observe the User Theme JSON.
* Note that the values for `settings.custom` and `settings.typography.fontFamilies` have been removed.

## Expected behaviour
That the data saved on the User Theme JSON be persisted and retrieved.

## Actual behaviour
Values are removed from the User Theme JSON

## Device information
I have been unable to reproduce this locally (WordPress 5.8 and Gutenberg 11.1.0 or /trunk) to no avail.  It only happens on wpcom.

**Comment by ersatzpenguin** [comment]
I'm guessing this issue is related to one reported by a user in 4192686-zen

User had Blockbase activate, and set a custom color palette. None of the custom colors were applied live on the site, and I couldn't find any mention of them in the site's styles—just the default palette variables. Clearing color cache etc. had no effect.

**Comment by mattwiebe** [comment]
This should be fixed by https://github.com/WordPress/gutenberg/pull/33919

**Comment by pbking** [comment]
Closing as fixed
