### ISSUE TITLE
SEO Settings: Settings not disabled for private/hidden sites when visiting the settings directly

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#5504]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/seo
2. Select a site with the site privacy set to hidden or private (not public)
3. Result: SEO settings are accessible, and no warning appears about the site's privacy setting
4. Select another settings page (e.g. "General")
5. Select "SEO" again to visit the SEO settings
6. Result: A yellow warning appears ("SEO settings are disabled because the site visibility is not set to Public.") and the settings are disabled.

#### What I expected

I expected that no matter how I visit the settings page (by going directly to the SEO settings URL or by navigating there from another settings page), if I'm viewing the settings for a non-public site I would see the warning and have the settings disabled.

#### What happened instead

When I navigate to the SEO settings directly (using the SEO settings URL instead of navigating from another settings page) the settings are accessible.

If I try to change the settings, the warning appears and the settings are disabled as I start typing or if I try to save the settings.

#### Browser / OS version

Chrome 50.0.2661.102, Mac OS X 10.11.5

#### Screenshot / Video

Screencast: https://cloudup.com/cK2pC22_dRn

**Comment by roundhill** [comment]
Fixed in #5601
