### ISSUE TITLE
Plans: Manage plan button is disabled in mobile viewport

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#55046]
### Steps to reproduce the behavior

1. On a mobile device or in a browser emulating a mobile viewport, navigate to `https://wordpress.com/plans` for a site with a subscription (like Personal or Premium) (or go Upgrades >> Plans)
2. Scroll down to that active plan
3. See the Manage Plan button

#### What I expected to happen
The button to be enabled, like it is in the desktop viewport

#### What actually happened
The button is disabled, and clicking on it does nothing.

#### Browser / OS version
Chrome, Mac Big Sur

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
There are work-arounds as there are other ways to access the purchases page for a single plan, but it might confuse folks who are used to navigating through this pathway.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-07-29 at 3 57 05 PM](https://user-images.githubusercontent.com/26772342/127567334-1fdb068e-a736-46c1-843a-3634586713fd.png)

**Comment by jjchrisdiehl** [comment]
Resolved in #55174 - closing this issue
