### ISSUE TITLE
User is getting blank screen when trying to create a new post or edit existing post

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#55048]
### Summary

I am able to recreate the issue but not finding any errors (aside from console errors). At first, I thought it was related to [this open issue](https://github.com/Automattic/wp-calypso/issues/53100) but there are a number of issues showing in the console.

The issue can be reproduced by using Support Session and clicking on 'Add New' under posts.

### Console Log Attached when clicking on add new post button.
[medicalobservernews.wordpress.com-1627596014591.log](https://github.com/Automattic/wp-calypso/files/6903877/medicalobservernews.wordpress.com-1627596014591.log)

The same issue occurs when trying to edit an existing post.

### Console log when trying to edit an existing post
[medicalobservernews.wordpress.com-1627597052300.log](https://github.com/Automattic/wp-calypso/files/6903923/medicalobservernews.wordpress.com-1627597052300.log)

User reports being able to create new posts from the mobile application.

The user tried clearing cache and logging into another browser with no change to the issue.

The user has another WordPress.com site and does not experience these issues.

4177957-zen

23573177-chat

**Comment by retnonindya** [comment]
I want to add that this is happening specifically on **post-revert** Atomic website. So far, I can only recall two incidents:

p9F6qB-7gR-p2
p9F6qB-6Yk-p2

It seems like something got stuck during the revert which causes the `Siteurl` on Network Admin to keep using the website's custom domain name -- while it should be using the `.wordpress.com` address. AT developer assistance is needed/this is something that HE and AA couldn't solve on their own.

**Comment by kwight** [comment]
Asked for help: p1628114406069700-slack-C7YPW6K40

**Comment by kwight** [comment]
Fixed two days ago by @jmdodd  👍
