### ISSUE TITLE
Signup: can't sign up for WordPress.com in Safari 7.0.6

### ISSUE THREAD

**Issue by davidlenehan** [Automattic/wp-calypso#5507]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. I click on the "Create Website" Button
3. On the next page I choose a theme
4. On the next page where I can type in a domain or sub domain, nothing happens.

#### What I expected
To be able to enter a sub domain for WordPress.com and choose from using it or purchasing a domain.

#### What happened instead
Nothing happens, I still see the "What are my options?" section underneath.
JS Console shows: "Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings."

#### Browser / OS version
Safari Version 7.0.6 (9537.78.2)

**Comment by lancewillett** [comment]
While it's good to know it doesn't work in this older version of Safari — we only provide official support for the latest browser versions minus 1 — so Safari 8.x.

**Comment by lancewillett** [comment]
If more folks report the same error, let's re-open.
