### ISSUE TITLE
Notifications: User @mentions do not send any notifications

### ISSUE THREAD

**Issue by aisajib** [Automattic/wp-calypso#55086]
This came up in the forums, but I was able to replicate the issue on my test site/accounts. 

### Steps to reproduce the behavior

1. Invite a new user to a site if one doesn't already exist (I invited my other test account `aistesting2` as an Administrator.)
2. `@mention` the newly added/existing users on the site in a new post or a comment. 
3. Log in to the other account to see if a notification was received. 

#### What I expected to happen
I expected to see a notification of the mention on the account `aistesting2`.

#### What actually happened
Nothing showed up when I checked the account `aistesting2`. I ensured all Username mentions notification was turned on. 

<img width="1012" alt="Screen Shot 2021-08-01 at 6 18 07 PM" src="https://user-images.githubusercontent.com/2541844/127770564-c0b22e93-e6cc-4b60-8a89-bc4839c44a0e.png">

(No email notifications were received for that mention either.)

### Context
First reported on [this forum thread](https://wordpress.com/forums/topic/user-mention-comment-notifications-down/), the user said the username mention notifications have stopped working in the last couple of days. I was able to replicate it on my test site using a test account. 

#### Is this specific to the applied theme? Which one?
Doesn't look like it. 

#### Does this happen on simple or atomic sites or both?
I've tested on a Simple site. 

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Doesn't seem to affect our p2s, but likely affects all simple sites. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

GIF showing me mentioning my test (non-a8c) account: 

![Screen Capture on 2021-08-01 at 09-03-31](https://user-images.githubusercontent.com/2541844/127770659-90458cef-8ea4-42e8-a5af-67df6cb1fb39.gif)

**Comment by inaikem** [comment]
Should be moved to 'spacelab' for further work per this interaction p1627880082000900-slack-C029HCKPXP0. Thank you, @yansern 🙏

**Comment by aisajib** [comment]
Just noting that there was [another forum thread](https://wordpress.com/forums/topic/email-notifications-not-being-received-about-mentions-in-comments/) about this issue.

**Comment by aidvu** [comment]
This was a regression, and was fixed by D65274-code on August 5th. Closing.
