### ISSUE TITLE
Checkout: add Tracks event for step completion

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#55080]
From pbOQVh-1d7-p2, let's add a `calypso_checkout_composite_step_complete` event with a `step_name` prop that takes a slug and a `step` prop that takes the step number. This would fire regardless of the user completing the step and rather as long as the step is in a "completed" state.

**Comment by rinaZC** [comment]
Hi, I'm new to the community, and I'm wondering if I can take this issue?
