### ISSUE TITLE
Feedback/Request: Move Comment box above the Related Posts area (for increasing visitors' interactions) -- Theme Twenty Twenty

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#55084]
Hey team! This is a feedback/request from our user about theme Twenty Twenty and I would like to share it with you all. Not a bug, but this is definitely something we can include in our considerations.

When the website/blog is using theme Twenty Twenty, the comment section is at the bottom of the page (under Related Posts area)

![Screenshot 2021-08-01 at 10 40 38 AM](https://user-images.githubusercontent.com/44726232/127757584-7d6d9324-7d7d-4252-908f-bcb4cff97adb.png)

The user is aware that asking for the comment box to be moved above the Related Posts area would be out of our CSS scope. However, I want to check with you folks if we can update our theme (or if there is a prospect of having this theme updated) to cater to this feedback,

One of the concerns is website interaction. Having the Comment box on the very bottom of the content area might affect the website interactions far from favorable. The user mentioned:

> Yes, in my classic theme I got a lot more interaction/comments, now I barely get any.

One of the important factors of blogging is website interactions (somebody is liking the post, somebody is leaving comments, etc...) so I wonder if we can move the Comment box placement would be helpful to increase website interaction between the blogger/website owner with their visitors/readers.

However, I also want to check with you all if this is actually super needed or not. Maybe, putting Related Posts above Comment box also helps with website interactions? I really don't have data to support this, other than personal thoughts/anecdotal.

Or, *maybe*, far into the future (or not super far?) we can have the option on where to put the Comment box (above or below Related Posts section)? 😄 

### Context
User feedback/insights. 
30906944-hc

#### Is this specific to the applied theme? Which one?
Theme Twenty Twenty. But if we can use this feedback for other themes, that might be pretty cool too.

**Comment by autumnfjeld** [comment]
@ollierozdarz @alaczek   Could you comment on if this something design is interested in working on? Or if we should close this ticket (maybe it is in discussion elsewhere or more appropriate for including  in larger/other design considerations).

**Comment by jordesign** [comment]
My feeling is that Jetpack injects the Publicize and Related Posts at the end of the the_content - so that's why it appears above the comments (which are part of the template itself).

I'm not sure of the logistics of changing that around - although I suspect we can maybe filter the_content or something like that to include it earlier?

**Comment by alaczek** [comment]
I don't know if it would make sense to tackle this tbh. This is how this works across all our themes, so would we make this change in this single case?

> Maybe, putting Related Posts above Comment box also helps with website interactions?

I have a feeling it might - the idea is that by serving other potentially interesting pieces of content you can keep a visitor on your site longer.

**Comment by retnonindya** [comment]
Thank you for sharing your insights, folks! And yes, this falls on non-urgent request, even if this would go to `wontfix` situation, I am personally okay with it. I'd figure this can be a huge thing to tackle, just for this one theme.

>  the idea is that by serving other potentially interesting pieces of content you can keep a visitor on your site longer.

This is a good insight! For SEO-conscious folks, knowing Related Posts can help to improve their website interactions is a good thing!

Again, I really appreciate you folks looking into this 🙇

**Comment by autumnfjeld** [comment]
Wontfix due to FSE.

Functionality should create be available and built into FSE.

pdgK6S-2X-p2#comment-125
