### ISSUE TITLE
Calyspo Posts: Multiple items highlighted on sub-menu

### ISSUE THREAD

**Issue by sethmclellana8c** [Automattic/wp-calypso#55103]
#### Steps to reproduce

1. Go to My Site (Calypso/Unified nav)
2. Go to Posts section
3. Click on three dots to the right of a certain post (which opens a drop-down sub-menu)
4. Hold cursor over different sub-menu items
5. When going from a couple menu items to others, multiple lines will highlight at the same time (see below)

#### What I expected

Only one sub-menu item is highlighted at a time (the one my cursor is hovering on)

#### What happened instead

When going from "Copy post" -to-> "Copy link" , both sub-menu items end up highlighted simultaneously.

Also when going from "Trash" -to-> "Copy link" , both sub-menu items end up highlighted simultaneously.

#### Browser / OS version

Browser: Version 91.0.4472.164 (Official Build) (x86_64)
OS: Mac Big Sur 11.5

#### Screenshot / Video

https://user-images.githubusercontent.com/37377834/127888439-24b9153e-092c-4e76-a493-38000cd30188.mov

#### Context / Source

If it helps, this was seen on multiple, internal-a8c p2's - but also a test atomic site I have.

**Comment by jordesign** [comment]
I've been able to recreate/confirm this in Chrome on Mac OS Big Sur as well.
