### ISSUE TITLE
Empathy Testing: drag and drop with List view

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#55116]
![image](https://user-images.githubusercontent.com/29057562/127985252-17369c1b-5fc7-4166-951f-cb08c1b70c40.png)

## Test drag and drop with List view:

![Screen Capture on 2021-08-03 at 16-37-59](https://user-images.githubusercontent.com/29057562/127985416-3418f26b-db3e-430f-8d56-da909e736830.gif)

Expected to be able to drag `test` to below `something`

Actual: `test` did not move to below `something`

## Test drag and drop with List view to columns block

Drag and drop results are haphazard. It works in some cases only

https://d.pr/i/uGUWjd

**Comment by synora** [comment]
Triaged. I'm able to replicate this intermittently.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by masperber** [comment]
Here's a video showing some testing for this bug. I've narrated the video explaining what I'm doing as I'm trying to drag and drop.

The line that appears when you drag and hover an item in List View appears one element below where the dragged item will actually go if you release it.

https://user-images.githubusercontent.com/12906034/173198539-bda5c037-4c87-4af8-8ea6-31755cc34be6.mp4

Also, there is a green plus sign that confirms that the drag and drop will work if you release the mouse button, but unfortunately the line doesn't disappear if the green plus sign disappears.

**Comment by masperber** [comment]
Closing since this seems to have been resolved in https://github.com/WordPress/gutenberg/issues/42058 :)
