### ISSUE TITLE
My Home: Add checklist item for connecting Publicize

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#55113]
This is a stub of a ticket for us to extend.

Knowing a user would want to share their posts to Social Media is a strong signal of their intent to blog. For user's who *do* want to blog it is also a great way for them to build traffic.

I propose we add a checklist (for launch) item, or some other messaging within My Home to encourage this.
It might be the instance that this has to be an optional item (dismissable?) so people don't feel they have to do so.

**Comment by autumnfjeld** [comment]
Per @p-jackson 's comment: pdgAPm-D-p2#comment-15 we'd want to think this through since we already have a post-launch card for integration with social media.

**Comment by autumnfjeld** [comment]
Closing this as we got input from @olaolusoga to not pursue this, plus we already have a post launch card for publicize.
