### ISSUE TITLE
Empathy Testing: Popover cart price is not rounded off.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#55119]
### Steps to reproduce the behavior

1. Go to Upgrades > Domains
2. Add a new domain to the site
2. Select a discounted domain such as `.blog` which has a discounted price of $9.90
3. You will notice that the domain price is not rounded off properly in the popover cart

#### What I expected to happen

The domain price in the popover cart should be the same as the listed price.

#### What actually happened

The price was not rounded off properly

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

 Affects all sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/33957570/127993652-b6d2c651-a1f1-4036-9fbe-df8d38739ea4.png)

**Comment by Aurorum** [comment]
PR for this issue in #55123. :)
