### ISSUE TITLE
Gallery Block: Additional background line added between 4th and 5th image in Editor

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#55115]
### Steps to reproduce the behavior

1. Create a new post, add a new gallery block
2. Insert at least 6 images within gallery block
3. See error in Editor
 
#### What I expected to happen

Images added within Gallery block is displaying as expected

#### What actually happened

There's an additional line between 4th and 5 image within gallery block. It appears to be appearing as `.blocks-gallery-grid .blocks-gallery-item:nth-child(5) figure:before` element there.

### Context

CSS code populating the line as below:

```
.annotation-text-jetpack-tweetstorm, .block-editor-block-list__block li:after, .blocks-gallery-grid .blocks-gallery-item:nth-child(5) figure:before, .jetpack-publicize-twitter__tweet-divider {
    transition: opacity .5s;
    opacity: 1;
}

.blocks-gallery-grid .blocks-gallery-item:nth-child(5) figure:before {
    content: "";
    height: calc(100% + 16px);
    width: 4px;
    background: rgba(0,0,0,.6);
    position: absolute;
    left: -10px;
    top: -8px;
}
```

#### Is this specific to the applied theme? Which one?

Does not appear to be theme specific, as the line is visible within editor and published gallery block

#### Does this happen on simple or atomic sites or both?

Both.

#### Is there any console output or error text?

None.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/34882260/127980285-efdb6616-0051-4af8-81d0-59658eb6efe5.png)

**Comment by edwinho89** [comment]
Reported in 4167917-zd-woothemes

**Comment by synora** [comment]
Triaged. Can replicate.

**Comment by cometgrrl** [comment]
This appears to have been resolved sometime in the last year, I am not able to reproduce it.
