### ISSUE TITLE
Empathy Testing: Text beside icons are not aligned properly

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#55118]
#### Steps to reproduce

1. Open the Calypso dashboard of a site.
2. Visit Appearance > Themes
3. You will notice the text beside icons is not properly aligned.

#### What I expected

The text should be vertically aligned with its icon.

#### What happened instead

The text was not vertically aligned with its icon.

#### Browser / OS version

Google Chrome 92.0.4515.131 (Official Build) (x86_64)

macOS Big Sur 11.3 (20E232)

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/33957570/127990252-3f5e2d8b-55bf-4419-b50f-a3bb61665a1d.png)

**Comment by Aurorum** [comment]
PR for this issue in #55124. :)
