### ISSUE TITLE
Query Loop: "Choose" option in query block does not display all posts

### ISSUE THREAD

**Issue by yashitamittal11** [Automattic/wp-calypso#55120]
### Steps to reproduce the behavior

1. Go to the page editor
2. Add Query Loop block 
3. Select the "Choose" option and choose a 'Post Type' from the right sidebar.
4. The block shows only 1 post

#### What I expected to happen

I expect the block to display all the posts belonging to the selected post type. Also, I expect to see an option to choose the number of posts the user wants to display in the block.

#### What actually happened

The block displays only one post for the selected "Post Type"

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/21078987/127999687-b433c1d3-a229-4961-b25f-c40cd942b4b1.mov

**Comment by synora** [comment]
In the Query Loop Block's toolbar, there's a "display settings" button. Click on that reveals an "items per page" option. You can enter the number of posts to display there.

https://user-images.githubusercontent.com/10015451/128561650-44b132bb-e51c-4a45-8fe4-c41b1d4904e5.mov

 It sounds like you were looking for this setting to be the block settings (sidebar) area @yashitamittal11? If so, we'd need to swap out the bug label for feature request instead.

**Comment by dpasque** [comment]
Waiting on response from @yashitamittal11 to clarify issue before finishing prioritization triage!

**Comment by yashitamittal11** [comment]
Thanks for sharing. I missed the "Items per page" setting in the top toolbar. I was expecting it to show in the sidebar like the Blog Posts block. AFAIK for most of the blocks, the display settings are available in the sidebar. E.g., for the Layout Grid block, the offset control setting is available in the sidebar.

I think we can close this request now and open it again in the future if users request this or they find it confusing.

**Comment by dpasque** [comment]
Closing based on @yashitamittal11 's comment!
