### ISSUE TITLE
WooCommerce Product import UI issue: Continue button on the import page should be grayed on no file selection

### ISSUE THREAD

**Issue by yashitamittal11** [Automattic/wp-calypso#55122]
### Steps to reproduce the behavior

1. Go to 'WooCommerce > Products > Import' page.
2. The 'Continue' button on the page is not grayed out.

#### What I expected to happen

If the user presses the 'Continue' button without adding a file, it gives an error. 
I expect the 'Continue' button to be grayed out and not clickable if no file is selected for uploading. When a file is uploaded then I expect the button to change color and be clickable.

In my test, I was not sure if I would be able to click the button after adding the file as there was no UI change to prompt it.

#### What actually happened

The 'continue' button is clickable even if no file is added and the user sees an error message. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Import screen](https://user-images.githubusercontent.com/21078987/128000972-6d510d1d-5923-4e8a-84e5-65f85e2e0ea8.jpg)

**Comment by kosiew** [comment]
Hi @yashitamittal11 ,

Thanks for reporting this and the detailed steps.

Transferred to https://github.com/woocommerce/woocommerce/issues/30454

Closing this.
