### ISSUE TITLE
SEO Settings: Validation on Front Page Meta Description shows error at 160 chars

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5512]
#### Steps to reproduce
1. Starting at URL: For a WordPress.com public site, visit https://wpcalypso.wordpress.com/settings/seo/
2. Enter 160 characters

#### What I expected

No validation error as I entered 160 characters which should be allowed

#### What happened instead

Red error is shown for 160 characters, even though description states `Craft a description of your site in 160 characters or less`

Should we only show this error for 161 or more characters? Or change the description to less than 160 characters.

#### Browser / OS version

Chrome OSX

#### Screenshot / Video

![160 chars](https://cloud.githubusercontent.com/assets/128826/15458562/276acbb0-20df-11e6-9e64-06b44f51da61.png)

**Comment by drw158** [comment]
will be fixed in #5541
