### ISSUE TITLE
Reader: Followed blog controls are styled incorrectly on mobile

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#55135]
On mobile screen widths, the controls for managing a followed blog in the Reader intersect the header and content:

![image](https://user-images.githubusercontent.com/13437011/128047750-af55b8c2-5ee5-4066-9477-7ab90518a05a.png)

**Comment by andres-blanco** [comment]
The problem arises on sites that don't have an icon. As I see it there are two ways to fix this:

1. Just display the empty placeholder that's hidden through css
Mobile: 
![image](https://user-images.githubusercontent.com/375980/130845802-6c0b3743-c3e3-43fe-a073-22ce18012ec9.png)
Desktop:
![image](https://user-images.githubusercontent.com/375980/130845853-0ad5ccb2-bbc4-490b-9849-509d473bc5bd.png)

2. Re-align the buttons (this is just a mockup, imagine the buttons are aligned)
Mobile
![image](https://user-images.githubusercontent.com/375980/130845535-d624af5f-5726-42a3-a42e-f8c8a5cc3905.png)

Desktop
![image](https://user-images.githubusercontent.com/375980/130845571-ccab3d37-cdb0-4bc1-b226-fca00b4325ed.png)

The first one is easier but the second feels better. @saygunnyc @blackjackkent what do you think?

**Comment by saygunnyc** [comment]
While I'm liking the second one better, I'm also questioning the benefits of displaying a default icon, and I have some questions in my mind, sharing below 😄 

- Seeing a default icon might actually get the customer to take any action on uploading an avatar. However, I wonder if the user itself is looking at this post, is there a way to provide a quick link here for them to take action right away? " ✏️ Edit" over the image.
- On the other hand, if we were to remove the default profile image, would that be clear for users to understand they could actually use an avatar here instead?

Let me know your thoughts!

**Comment by andres-blanco** [comment]
@saygunnyc I think there are 2 things to consider.
1. Now the placeholder image is hidden. If we unhide it The edit button is a good idea! But I think we should have a separate issue for that.
1. The buttons (follow, settings, mark as viewed) might look better under the title than on the side.

Maybe the best is to show the placeholder AND move the buttons below the title?

**Comment by saygunnyc** [comment]
> If we unhide it The edit button is a good idea! But I think we should have a separate issue for that.

👍 to a separate issue. Let's do it if that's not too much work. And let me get back to you with a mockup for this one. What would be the URL to see the actual thing in action?
