### ISSUE TITLE
Implement new selector createCurrentRouteURL

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#55130]
My preference would be to create a new selector, `createCurrentRouteURL`, that constructs the entire `/path?query` string, and use that.

Imagine rendering the React component in an Express.js server, producing a static HTML response. There, you know the request URL: it's in the HTTP request and in the server's `Request` object. And you can use it to render the right `signupUrl` link. There's no `window` and no `window.location` though. The route information is available from a different source. Here, the Redux selector (or any other abstraction mechanism, e.g., some custom `useCurrentRoute()` hook) provides a unified way how to read the current route.

_Originally posted by @jsnajdr in https://github.com/Automattic/wp-calypso/pull/54646#discussion_r681705729_

**Comment by chriskmnds** [comment]
Forgot we already have a ticket for this! I'll close this in favor of #57109
