### ISSUE TITLE
SEO Settings: Front Page Meta Description allows HTML/XML tags

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5513]
#### Steps to reproduce
1. Starting at URL: For a WordPress.com public site, visit https://wpcalypso.wordpress.com/settings/seo/
2. Enter some HTML tags like `<head>` etc.

#### What I expected

These to be shown as invalid

#### What happened instead

Allows saving of these, although these are wrapped in a string in the meta tag so this doesn't really break the site

#### Browser / OS version

Chrome OSX

#### Screenshot / Video

![html tags](https://cloud.githubusercontent.com/assets/128826/15459238/94daed68-20e6-11e6-8066-04f2c83d5c27.png)

**Comment by roundhill** [comment]
Fixed in #5586
