### ISSUE TITLE
Atomic Downgrade: Investigate current infrastructure for reverting a site

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55155]
### Details

In order to provide Atomic users the ability to self-cancel their plans, we'll likely need to expose the current tools used by HEs behind one or more API endpoints that will be later consumed by Calypso.

One of these tools is the reverter, so let's investigate the code involved when a HE reverts an Atomic site into the Simple site infrastructure, and note our findings in a comment on this issue.

Further reading:
- P9HQHe-jY-p2
- p9o2xV-Wc-p2
- pdgTfM-k-p2

**Comment by dsas** [comment]
As an overall point, the atomic code mostly lives in WPCOM's wp-content/lib/atomic (and particularly the reverts subdir), the user interface that uses the revert code is in MCs automated-transfer/revert.php

**Comment by dsas** [comment]
Just sticking some notes in a series of comments as I go, I'll collate and tidy up into a P2 later.
### UI

This shouldn't really matter, but it explains how the tool that HEs use works. 

- Entry point is in `missioncontrol/automated-transfer/revert.php`
    - This collects up details on the reversion and then displays `missioncontrol/automated-transfer/templates/revert.php`
        - If a site is reverting
            - It will display a please wait message
        - If a site is already reverted and the atomic site exists
            -  If the atomic site doesn't have a temporary url it will display the form to create one (form action `temporary_serve`)
            - else if the site does have a temporary url it will display the temporary url and the form to restore  the url (form action `restore_url`)
            - In either case
                - it will display the form (checkbox) for performing a lossless import of atomic content to the reverted site (form action `lossless_import`)
                - It will also display a form to clean-up the atomic site immediately (form action `early_cleanup`)
        - If a site has an incomplete reversion that has failed
            - It will display a warning and tell the HE how to request manual assistance
        - Otherwise (i.e. a site that isn't reverted and isn't in progress)
            - If the site has been part of a rare bug that might have issues reverting (see p9F6qB-3NO-p2 and linked P2) then warn the user.  Not sure how much we need to be concerned about this
            - In any case, display the revert site form with form details being nested inside a payload var (action is `hard_revert`)
                - There are some differences between atomic v1 and v2 sites, - allowing hard resets, or indicating it's a v1, unsure whether the latter is a material concern.
        - Lastly, if a site is atomic, on a supported plan and isn't being reset or reverted
            - Display a reset site form (form action `reset_site`)
    - The forms all submit to `/automated-transfer/api.php` (which is handled by the javascript at `automated-transfer/assets/scripts.js`). 
    - `automated-transfer/api.php` essentially just sorts the postvars out and delegates to `AT_API->handle_api_request`. 
    - The AT_API isn't structured using the usual WP rest infra, it's just a big switch on the `action` & `payload[action]` request vars, runs a method based on that passing other request vars as params and then sends a json response.

**Comment by dsas** [comment]
### Revert to simple

- Starting from `AT_API->handle_api_request` (see missioncontrol/automated-transfer/includes/class-at-api.php)
- The action is hard_revert
- Gets the transfer object using `get_mc_atomic_Transfer` (this is simply the most recent non-error db record for the given blog hydrated into a `Transfer_Record` object and then a `MC_Atomic_Transfer_V2` object) and then calls it's `revert` method. It looks as though the lossless & cleanup parameters are always set to their default values of false.
    - `MC_Atomic_Transfer_V2->revert`
        - This essentially just records the reason for the reversion in the transfer meta and calls `revert_atomic_site`
    - `revert_atomic_site`
        - It gets a reverter object (`A8C\Atomic\Reverts\Revert`)
        - Then calls the `A8C\Atomic\Reverts\Revert->trigger_process` method, which is where the bulk of the actual reverting happens.
            - Renames jetpack and  archived simple database tables
            - Updates the site ID to be WPCOM
            - rollback the domain (using `A8C\Atomic\Domains\Setup::set_domain_to_wpcom`)
            - reset the blog's upload space based upon it's current subscription
            - Queues an async job (`generic_reloacate_blog`) which actually moves database shard
        - If there are any errors related to missing archived simple tables it attempts to resolve them, and if it can't do this immediately creates an async job to do so, finally it returns a message tells the user to try again.
          - We'll probably have to move this into wpcom code, checking the stats, the errors still occur several times each month.

**Comment by mmtr** [comment]
Thanks, @dsas! Very helpful information 🙂 

As discussed in Slack, I separated the whole investigation into 4 smaller tasks, so I think we can close this one for now.
