### ISSUE TITLE
Domains: Unable to transfer an existing domain from the domain registration screen

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55150]
In the domain registration screen, if the user types an existing domain, a link shows up: “Do you own it?“. It was supposed to offer the user to transfer the domain, but the link is not leading anywhere.

##### For logged in users

1.  Go to _**Upgrades → Domains → Add a Domain → Without a site**_ ([https://wordpress.com/start/domain/domain-only](https://wordpress.com/start/domain/domain-only)).

2. Type an existing domain (for example `testingdomain.com`)

3. Click **Do you own it?**

##### For unlogged users

1.  Go to **WordPress.com → Find your domain** ([https://wordpress.com/domains](https://wordpress.com/domains))

2. Type an existing domain (for example `testingdomain.com`)

3. Click **Do you own it?**

#### What I expected to happen
See an offer to transfer the existing domain to WordPress.com
#### What actually happened
The user gets redirected to a different URL (https://wordpress.com/start/domain/domain-only/use-your-domain/ or https://wordpress.com/start/domain/domain-only/transfer) but with the same content. No option to transfer the domain is displayed.

### Context
Initially reported at pd4QKa-av-p2
#### Browser / OS version
Firefox 90.0 and Chrome 92.0 on Linux and macOS
#### Is this specific to the applied theme? Which one?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/39308239/128133172-3605d9a7-c1bb-46b0-9056-c951d4df0b53.png)
![image](https://user-images.githubusercontent.com/39308239/128133189-d44e5259-2a60-4265-941c-844f96e5e5b8.png)

**Comment by delputnam** [comment]
Closing this since it was addressed in #55159
