### ISSUE TITLE
Atomic Downgrade: Create API endpoint skeleton

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55160]
### Details

In order to provide Atomic users the ability to self-cancel their plans, we'll likely need to expose the current tools used by HEs behind one or more API endpoints that will be later consumed by Calypso.

While we determine the code involved in such tools in https://github.com/Automattic/wp-calypso/issues/55155, we can start creating a new API endpoint with some basic mechanisms.

Since the whole downgrade process can take a long time, we can assume that the endpoint will queue an async job and will notify the status (running, failed, success) in the response.

### API definition

- Route: `wpcom/v2/sites/:site/atomic/revert`.
- Methods: `GET` and `POST`.
- Permissions: Administrators only.
- Callback:
  - Make sure the site is Atomic.
  - For now, let's return a hardcoded response like `{ status: 'idle' }`

**Comment by dsas** [comment]
I've had an initial stab at this, see D65210-code
