### ISSUE TITLE
Subscriptions: Audit what Tracks and bump stats we have active.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#55171]
Subscriptions have existed for a long time, and the various screens and Calypso may have a varying level of stats coverage. Let's find out what we're working with: what screens and buttons have what stats tied to them.

**Comment by blackjackkent** [comment]
I've got some notes built up regarding tracks events across four different areas (action bar, emails, reader, and subscribe.wordpress.com) - also chatted with @andres-blanco about email stuff to make sure I was on top of things there. I'll get a P2 post up on Monday with a summary.

**Comment by blackjackkent** [comment]
Posted at pdgv5Y-gg-p2
