### ISSUE TITLE
My Home -> Mobile App Card: Update copy on mobile CTA

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#55188]
This is simply to update the copy of the subtitle on the app download call to action card.

New subtitle:
> Inspiration strikes any time, anywhere

<img width="379" alt="126821839-cdb5d756-8629-4efa-81f8-3fd3b56a445e" src="https://user-images.githubusercontent.com/22446385/128320851-d969c121-9033-46b2-b603-d170ccd27795.png">

**Comment by roo2** [comment]
@mattmiklic @yaelirub It looks like this one slipped through the cracks too, would you still like the copy on this card to be changed?

**Comment by mattmiklic** [comment]
I don't know if there's been any discussion or changes to the subtitle text since that was mocked up, but it still seems like a good choice to me.

**Comment by autumnfjeld** [comment]
@jrushfinn  @mattmiklic @roo2 
 Taking some key discussion points from this sister issue https://github.com/Automattic/wp-calypso/issues/55141
[Mural ideas](https://app.mural.co/t/a8c1359/m/a8c1359/1642775570168/adb041c3bcd97c52e5698c21ba19cbde07e15c61?sender=u74e9502380fc214159157096)

* Add QR code
* These app store badges should redirect to apps.wordpress.com not the app stores. On desktop, sending to the app stores is a poor experience. 


Is there a designer that can help with some of these ideas?

**Comment by mattmiklic** [comment]
I'm helping the team working on mobile growth projects right now so I may be able to give some attention to this after our current project. cc @yaelirub or @jrushfinn if there are opinions about making this a priority.

**Comment by yaelirub** [comment]
Since FSE has been deployed and will be landing people on the editor instead of My Home, this has become lower priority imo.

**Comment by arthur791004** [comment]
I create a new issue for https://github.com/Automattic/wp-calypso/issues/55188#issuecomment-1028580974. So this issue only focuses on new copy and it's done via https://github.com/Automattic/wp-calypso/pull/61151
