### ISSUE TITLE
update tracks `calypso_customer_home_card_impression` to only fire when card is viewed

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#55180]
With the multiple card slider https://github.com/Automattic/wp-calypso/issues/54226 we are now sending a `calypso_customer_home_card_impression` event to tracks for every card that is loaded.

It should only be sent when a card is actually viewed. Probably only the first time that the card is viewed

**Comment by autumnfjeld** [comment]
@roo2   Could you make the description a little bit clearer?   With **Testing Instructions** section?    I think this is meant for test the tracks events, but there isn't a PR and itsn't clear what or how the tester is supposed to test.

Also please ping Phil or Arthur  to get reviews through as quickly as possible. (You may already be doing that)   

![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)
