### ISSUE TITLE
Akismet Shows Your API key is no longer valid on Simple Sites

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#55193]
### Steps to Reproduce

1. Go to the menu Jetpack > Akismet Anti-Spam

### What I expected to happen

To see Akismet-related settings on that page.

### What actually happened

It shows the message _"Your API key is no longer valid. Please enter a new key or contact support@akismet.com."_.

### Context

More details here: pd4QKa-aH-p2
Reported on 4198137-zd-woothemes
Found a recent discussion about this menu here: pd2C0z-F-p2

### Operating System

macOS

### Browser

Firefox

### Other information

It doesn't seem to happen on A11n accounts, I was able to replicate it on multiple test accounts.

**Comment by zdenys** [comment]
I can replicate it on a test account, in Chrome, but also on a Simple site where my a11n account is an Admin and not the owner of the site.

![image](https://user-images.githubusercontent.com/39308239/128339132-405283f3-4cf6-448d-a9ca-3ad2ea80e9f4.png)

**Comment by synora** [comment]
I can replicate this in my non-A11n account as well.

**Comment by allilevine** [comment]
@mmtr @stephdau Could this be related to D64710-code ?

**Comment by mmtr** [comment]
@allilevine quite possible yeah. I'm not able to reproduce it though, tested with both an a11n account and a non-a11n account, so I'm not sure what's causing the message to appear 🤔

**Comment by ahmadbaig1** [comment]
A user reported this- zd-4207985

**Comment by allilevine** [comment]
> @allilevine quite possible yeah. I'm not able to reproduce it though, tested with both an a11n account and a non-a11n account, so I'm not sure what's causing the message to appear 🤔

Thanks. I'm able to reproduce it with a non-a11n account, and so far from digging around it looks like that user gets an `invalid` response when checking for an Akismet subscription.

**Comment by kuropixel** [comment]
Another user experiencing the same issue: zd-4207795.

**Comment by edwinho89** [comment]
Another report in 4210870-zd-woothemes

**Comment by khristiansnyder** [comment]
I had a customer with this a few days ago. Fixed it by manually adding the Akismet plan.

**Comment by cfinke** [comment]
I've deployed a fix on the Akismet side that should fix this issue. Can someone confirm?

**Comment by edwinho89** [comment]
Hi @cfinke ! I confirm the issue has been fixed, as confirmed by recent reported user above (and my own test site) . Thank you!

**Comment by kuropixel** [comment]
@cfinke The user I reported above's site does not display the error message anymore. My test site is also showing ok. Appreciate the help.

**Comment by allilevine** [comment]
Thanks @cfinke! Closing, details here: pZbK5-6nk-p2
