### ISSUE TITLE
Atomic Downgrade: Add revert functionality to cancel/delete purchase endpoints

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55191]
### Details

Let's add the Atomic revert functionality to the API endpoint created in https://github.com/Automattic/wp-calypso/issues/55555 which matches the current behavior of the existing revert tool (see https://github.com/Automattic/wp-calypso/issues/55155#issuecomment-892737726 and  https://github.com/Automattic/wp-calypso/issues/55155#issuecomment-892738741).

The revert process should be triggered only for purchases that need an Atomic revert prior cancellation/removal. These are plans supported by the Atomic infra (Business and eCommerce). In the future, this list can contain other marketplace purchases such as the Yoast subscription.

### `GET` requests

Disallowed.

### `POST` requests

- Only allow requests from users who can actually cancel/remove purchases (blog owners).
- If site isn't reverted and isn't reverting, trigger the site revert process (`A8C\Atomic\Reverts\Revert->trigger_process`).
- Return in the `status` field a `queued` value if the revert has been completed successfully.

**Comment by dsas** [comment]
> If site is already reverted: { status: 'reverted' }.

If I've understood correctly this won't be possible - a reverted site will no longer be atomic and hence the permissions check implemented in #55160 will give a 403. 

I think this means this "is atomic" aspect of the permissions check ought to become something only checked on POST, for the GET it ought to just be reflected in the status.

**Comment by mmtr** [comment]
@dsas right, let's change the permissions check and perform the "is atomic" one only on `POST` requests. `GET` requests should allow any site as long as the request is coming from an admin. The status for non-reverted Simple sites could be something like `{ status: 'unavailable' }` (but feel to change it to something else if you can think of a better status name).

**Comment by dsas** [comment]
I pushed the permissions change as D65279-code and will continue on with the other changes on this issue

**Comment by dsas** [comment]
Miguel deployed D65279-code 🚀 I'm now working on further changes on D65285-code

**Comment by jmdodd** [comment]
"Reverting" is not "reverting", it is "reverted and queued for import".

**Comment by mmtr** [comment]
@jmdodd is that import different from the lossless import? Note that the lossless import functionality will be handled in a separate issue/PR/diff: https://github.com/Automattic/wp-calypso/issues/55243

**Comment by dsas** [comment]
@mmtr, no it's the same one. The reverting @jmdodd is talking about doesn't actually do any reverting, just locks the blog and changes state so the rest of the lossless import can happen. According to the code comments there's an aim to do the actual reverting while in that state, but that isn't the case right now.

> "Reverting" is not "reverting", it is "reverted and queued for import".

I've [implemented the "reverting" mentioned in this issue as `relocating_revert` and `relocating_switcheroo states`](D65285-code)

**Comment by dsas** [comment]
The GET changes are in  D65285-code

I've added the POST changes in D65367-code which builds upon the above, I can merge them into the same review if that's easier but I think the POST changes are more likely to require further work (I'll look over again myself too) so I've separated them for now.

**Comment by mmtr** [comment]
Following the discussion in D65285-code, we're finally dropping support for `GET` requests on the new endpoint.

Calypso will use the existing `rest/v1.2/sites/:site/transfers/latest` endpoint to determine the current revert status, and the new `wpcom/v2/sites/:site/atomic/revert` endpoint will only accept `POST` requests which will initiate the revert process.

**Comment by BogdanUngureanu** [comment]
D66333-code contains the revert implementation for both `delete` and `cancel` endpoints and is ready for review.

**Comment by BogdanUngureanu** [comment]
Since a generic revert and lossless import function will be handled by the Atomic team and based on feedback received in the diff, I've created a new diff for this: D66593-code and currently put on hold until the generic function for revert & import is ready to consume in our code. 

Also, this diff will also cover https://github.com/Automattic/wp-calypso/issues/55243

**Comment by BogdanUngureanu** [comment]
Two new diffs are ready for review:
- D67906-code
- D67909-code

**Comment by BogdanUngureanu** [comment]
Deployed on WPCOM in rWP233099 and rWP233100.
