### ISSUE TITLE
Signup: NUX Trampoline layout broken for RTL users

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#5519]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ (logged out)
2. At the bottom of the page, select "Language" and choose an RTL language (e.g. Arabic, Farsi, Hebrew). I chose Farsi, which took me to the Farsi logged-out homepage at https://fa.wordpress.com/
3. Select the "Create website" button (in Farsi, this goes to https://wordpress.com/start/fa/?ref=homepage )
4. Complete the signup process for a new account and site
5. After signup finishes, let the front end of your new site load and the NUX trampoline prompt appear

#### What I expected

I expected the NUX trampoline to pop up just as it does when signing up with an LTR language, only with an RTL orientation.

#### What happened instead

The NUX trampoline prompt has incorrect placement (too far to the right, so the My Site menu overlaps it) and the arrow is pointed to the left (instead of to the right, to the My Site menu).

#### Browser / OS version

Chrome 50.0.2661.102, Mac OS X 10.11.5

#### Screenshot / Video

![screen shot 2016-05-23 at 11 03 27 am](https://cloud.githubusercontent.com/assets/8658164/15467425/668b86b2-20d6-11e6-9600-2076da319c59.png)

**Comment by mattwiebe** [comment]
The fix is deployed now. Props @yoavf for the fix
