### ISSUE TITLE
Atomic Downgrade: Investigate current infrastructure for importing Atomic content into a reverted site

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55202]
### Details

In order to provide Atomic users the ability to self-cancel their plans, we'll likely need to expose the current tools used by HEs behind one or more API endpoints that will be later consumed by Calypso.

One of these tools is the lossless importer, so let's investigate the code involved when a HE imports the Atomic content into the reverted site, and note our findings in a comment on this issue.

Further reading:
- P9HQHe-jY-p2
- p9o2xV-Wc-p2
- pdgTfM-k-p2

**Comment by dsas** [comment]
The current UI is documented [here](https://github.com/Automattic/wp-calypso/issues/55155#issuecomment-892737726), but in summary it ends up inside AT_API in the missioncontrol repo, so I'll cover from there

- Starting from AT_API->handle_api_request (see missioncontrol/automated-transfer/includes/class-at-api.php)
- The action is lossless_import
- Gets the transfer object using `get_mc_atomic_Transfer` (this is simply the most recent non-error db record for the given blog hydrated into a `Transfer_Record` object and then a `MC_Atomic_Transfer_V2` object). Presumably this is just a way to check that it is an atomic site as it does nothing with the transfer object other than error checking
- Calls `queue_lossless_import` (still in missioncontrol)
    - Gets the latest successful transfer and bails out unless the status of it is `reverted`
    - Logs who started the revert
    - Updates the transfer record fetched earlier to set the status to reverting and sets some transfer meta. 
    - ⚠ checks the $_POST directly ⚠ to see if it's an overwrite and updates the `lossless_revert_update_existing` transfer meta accordingly
    - Does some logging & audit logging
    - Returns back to the user saying it's queued.

The rest of the process takes place inside wpcom via async jobs, so it's a completely separate set of processes.
  - A cronjob executes the `atomic_lossless_revert` action.
    - This gets all transfers in a relevant state and iterates over them, calling the relevant method on `A8C\Atomic\Reverts\Lossless::do___statename__`
    - The five relevant atomic transfer states are. 
        - **reverting** - taking a blog that has been reverted and preparing it for renaming. Confusing name as the aspiration is to move the revert to here
            - Adds blog stickers to ensure other changes don't mess it up
            - Updates the transfer status to renaming
        - **renaming** - creates an async job to create a temporary url and waits until it's done
            - Creates an async job `atomic_create_temporary_url` and returns, retaining the same transfer status
            - Each further call will check to see if the job succeeded, and if so updates the transfer status to exporting
        - **exporting** - creates an async job to export the atomic site to files
            - Creates an async job `atomic_revert_export_site` and returns, retaining the same transfer status
            - Each further call will check to see if the job succeeded, and if so stores the file update details inside the blog options and updates the transfer status to importing
        - **importing** - creates async jobs to import the files
            - Creates an `atomic_revert_import` job for the current file that needs importing
            - Each further call will check to see if the job succeeded, and if so mark the file as imported. If there are no more files left to import it will update the transfer status to cleanup
        - **cleanup** - cleans up after everything else, primarily importing
            - Queues an async `atomic_revert_backfill` job to sort out images
            - Removes blog options used for importing files / domains etc

**Comment by mmtr** [comment]
Brilliant! Thanks, @dsas.
