### ISSUE TITLE
Atomic Downgrade: Investigate current infrastructure for issuing a refund to a reverted site

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55204]
### Details

In order to provide Atomic users the ability to self-cancel their plans, we'll likely need to expose the current tools used by HEs behind one or more API endpoints that will be later consumed by Calypso.

One of these tools is the Store Admin, so let's investigate the code involved when a HE issues a refund to a customer due to a plan removal, and note our findings in a comment on this issue. We can also check how these refunds are currently issued for Simple sites in Calypso, since we can probably reuse that once the site has been reverted.

Further reading:
- P9HQHe-jY-p2
- p9o2xV-Wc-p2
- pdgTfM-k-p2

**Comment by onuro** [comment]
If we'll provide refunds once they downgrade within the refund period, we'll also eventually need a UI reflecting that to the customer right?

Just thinking out loud.

**Comment by mmtr** [comment]
@onuro Correct, although we already display that info in the current UI when a user wants to cancel a plan on a Simple site:

<img width="1268" alt="Screen Shot 2021-08-11 at 12 16 05" src="https://user-images.githubusercontent.com/1233880/129012507-e9ed3561-d8f9-4221-94c8-f8354e3c6cdf.png">
<img width="1271" alt="Screen Shot 2021-08-11 at 12 16 32" src="https://user-images.githubusercontent.com/1233880/129012514-d2fa1daa-d1e0-4ed4-8b26-7a12806673f2.png">

We could re-use that UI, effectively removing the necessity of creating a new UI reflecting it.

**Comment by dsas** [comment]
In store admin the form is processed by `wp-content/admin-plugins/wpcom-store-admin/wpcom-store-admin-page.php`, the interesting part starts on the "refundtxn" case of the action switch.

 * Gets the refund value and transaction id and calls `WPCOM_Store::refund_payment`:
   * Get the payment processing class for this method (subclass of `WPCOM_Billing_Payment_Processor`)
   * Call the `refund` method on the Payment_Processor
     * Uses the method to look up the name of the payment partner for that transaction
     * Gets exactly one receipt for that transaction
     * Issues a refund via `BD\Receipts\refund`
       * Refunds via `refund_receipt_through_payment_gateway`
       * Creates a refund receipt via `Container::api_purchases()->refund_receipt` which records the refund
 * Do some special logging if it's a paypal transaction
