### ISSUE TITLE
Signup: "Enter a domain or keyword" field has wrong orientation for RTL languages

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#5520]
#### Steps to reproduce
1. Starting at URL: https://he.wordpress.com/
2. Select "Create website" button
3. Select a theme
4. Enter a domain or keyword for your new site

#### What I expected

I expected the "Enter a domain or keyword" field (at step 2 "Let's find a domain.") to be LTR, since the domain has to be LTR with Latin characters (not RTL).

#### What happened instead

The "Enter a domain or keyword" field is RTL. Entering RTL text (e.g. Hebrew text) results in an error.

On the "Create your account" screen (step 4) the fields are correctly LTR to fit the expected input.

#### Browser / OS version

Chrome 50.0.2661.102, Mac OS X 10.11.5

#### Screenshot / Video

Domain field with RTL input:

![screen shot 2016-05-23 at 11 34 30 am](https://cloud.githubusercontent.com/assets/8658164/15468181/9d7105c2-20da-11e6-9d1c-d159fa2969e9.png)

Domain field with LTR input:

![screen shot 2016-05-23 at 11 34 46 am](https://cloud.githubusercontent.com/assets/8658164/15468184/a28acfb6-20da-11e6-9b03-e4249144d6a7.png)

**Comment by yoavf** [comment]
Alternative initial test instructions for development:
- Edit `config/development.json` and set `rtl` to `true`
- Visit http://calypso.localhost:3000/start/he
