### ISSUE TITLE
Atomic Downgrade: Investigate current infrastructure for removing a plan from a reverted site

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55203]
### Details

In order to provide Atomic users the ability to self-cancel their plans, we'll likely need to expose the current tools used by HEs behind one or more API endpoints that will be later consumed by Calypso.

One of these tools is the Store Admin, so let's investigate the code involved when a HE removes the current plan from a reverted site, and note our findings in a comment on this issue. We can also check how a plan removal is currently done in Calypso, since we can probably reuse that.

One of these tools is the Store Admin, so let's investigate the code involved when a HE removes the current plan from a reverted site, and note our findings in a comment on this issue. We can also check how a plan is currently removed for Simple sites in Calypso, since we can probably reuse that once the site has been reverted.

Further reading:
- P9HQHe-jY-p2
- p9o2xV-Wc-p2
- pdgTfM-k-p2

**Comment by dsas** [comment]
> We can also check how a plan is currently removed for Simple sites in Calypso, since we can probably reuse that once the site has been reverted.

@mmtr has identified that's done by a POST to /rest/v1.X/me/purchases/:purchase/delete, see [#1](https://github.com/Automattic/wp-calypso/blob/c66aa82fd226fe35315cc0964195aaf83112692f/client/me/purchases/remove-purchase/index.jsx#L127), [#2](https://github.com/Automattic/wp-calypso/blob/c6d25085e3431e8831ee670d4a9efdff6e8a687f/client/state/purchases/actions.js#L87-L108) 

This is implemented by `WPCOM_JSON_API_Delete_Purchase_Endpoint` which basically does some checking of stuff and then gets the subscription (`Store_Subscription`) and calls it's `remove` method.

**Comment by dsas** [comment]
### Store admin

**The summary is that it does basically as the API does** 

This is in admin-plugins/wpcom-store-admin/wpcom-store-admin-page.php 

Removing subscription will trigger an 'unsub' action, which starts on line ~237. This checks what is being unsubscribed from but atomic goes down the main case. 

 - Gets the store subscription details (`Store_Subscription`)
 - Gets the product (`Store_Product_Bundle_Business` and `Store_Product_Bundle_Ecommerce` are relevant presently) being unsubscribed from.
 - Records the event in tracks via `Store_Subscription_Cancellations::record_store_admin_remove_subscription_event`
 - Calls the store subscription's  `remove` method with 'cancel' as the context, this:
   - Calls `_deactivate_upgrade`  
     - Iterates over the subscriptions for the site to check whether any of the others have a bundle containing the product being deactivated. If they do then it bails out rather than deactivate the product. Presumably this isn't relevant for the plans themselves?
     - Fires the `deactivate_product` action
       - There are a lot of subscribers to this action
       - The most relevant one I think is `deactivate_product` in `admin-plugins/atomic.php`
         - It handles the ecommerce to business downgrade via async jobs
         - If this deactivation means the site will not have any atomic eligible plans it will queue a `atomic_deactivate_plan` async job (`deactivate_plan` in async-jobs/includes/atomic.php
           - The async job will fiddle with domains and then requeue itself
           - The second time it will call `Plan_Manager::deactivate_plan`
             - This will disable plugins, switch to a public theme, set the plan to free, cancel woo etc etc 
       - Another relevant one is  `Store_Product::deactivate_handler`, eventually this calls Store_Product_Bundle::deactivate
         - Calls `remove_upgrade` for all of the products in the bundle which means `deactivate_product` is fired for them too
         - Calls `Store_Product+Bundle::start_deactivation_email_campaigns` which starts some "win back" email campaigns
   - Deletes the sub in `store_subscriptions`
   - Calls `WPCOM_Billingdaddy::remove_subscription` to issue receipts.
   - Inserts in `store_subscriptions_inactive` instead
   - Uses `subscription_state_changed` to extends any related soon to be expired standalone plans, presumably domains?
   - Fires the `removed_subscription` event, but that is currently only subscribed to by jetpack products
 - Calls the product's cancel_callback if defined (neither of the relevant classes do at present). **⚠ the API doesn't do this. ⚠**

**Comment by dsas** [comment]
I have had another look at this and haven't yet found how refund happens when removing a plan via the API

**Comment by mmtr** [comment]
> I have had another look at this and haven't yet found how refund happens when removing a plan via the API

Seems we have a different endpoint for that: https://github.com/Automattic/wp-calypso/blob/49ea2453c8d150e169d841b105ccd23a69e9a0b6/client/lib/wpcom-undocumented/lib/undocumented.js#L1986-L1996

**Comment by dsas** [comment]
Via the API, a refund is done as part of cancelling an upgrade rather than [deleting a purchase](https://github.com/Automattic/wp-calypso/issues/55203#issuecomment-897767072), use of the [store admin](https://github.com/Automattic/wp-calypso/issues/55204#issuecomment-899592767) is different again.

The upgrade cancellation is implemented by `WPCOM_JSON_API_Upgrades_Cancel_Endpoint` 
 *  It gets a `Store_Subscription` using the subscription ID given in the request
 * Calls `Store_Subscription_Cancellations::request_cancel`
   * This acts differently depending on the product being cancelled and whether performing a downgrade (see it's `downgrade` method) or a cancellation.
   * A cancellation will call `Store_Subscription_Cancellations::cancel` which
     * If the subscription isn't refundable:
       * And it's a monthly subscription: cancel the auto_renew
       * Otherwise calls [`Subscription_Remove`](https://github.com/Automattic/wp-calypso/issues/55203#issuecomment-897823432) and returns a 'unsubnorefund'
     * if it is refundable:
       * And there's a bundled domain, do a bunch of stuff to calculate the refund amount on that
       * Call `refund_with_calculation` which works basically as [store admin refunds do](https://github.com/Automattic/wp-calypso/issues/55204#issuecomment-899592767) 
       * If a domain is involved then do some special cancellation of that
       * Call `cancel_callback` on the product being cancelled (no products define that method so it's a noop)
       * Send an email confirming it
       * Fire the `upgrade_cancelled` event (no listeners)
       * Record some stats
