### ISSUE TITLE
JS Error when creating a new site; "Applying Design" step hangs

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#55219]
### Steps to reproduce the behavior

1. Create a new browser profile in chrome
2. Visit WordPress.com
3. Create a new account with an `@example.com` email address
4. Create a new site; choose the `.wordpress.com` domain and the free plan
5. As it creates your site, it hangs on the "Applying Design" step, with a javascript error

```
Uncaught Error: The dependencies [redirect] were listed as provided by the user step but were not provided by it [ current flow: onboarding ].
```

![2021-08-05_16-53](https://user-images.githubusercontent.com/937354/128426203-1a451dc0-51b7-4b84-bc3a-600dfda239d1.png)

https://user-images.githubusercontent.com/937354/128426297-28cef315-56c4-4bf4-9305-d4ef899d2acf.mp4

#### What I expected to happen

* No javascript errors and the site progresses through the "Applying Design" step

#### What actually happened

* Javascript errors and the site hangs on the "Applying Design" step

**Comment by bluefuton** [comment]
Should be fixed by revert in #55223. 

cc @donlair
