### ISSUE TITLE
Nav Unification: Screen Options tab is missing on Customizer screens

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55231]
#### Details

When we removed the global "show wp-admin pages" toggle in https://github.com/Automattic/wp-calypso/pull/54387, we intentionally continued using its value as fallback when a user has still not set a preferred view with the new "Screen Options" tab. See p7DVsv-ch6-p2#comment-36832.

This is problematic on the Customizer and derived screens (such as Widgets or Menus) because we don't render the "Screen Options" tab there due to the different layout, but the global "show wp-admin pages" toggle is still acting on them. That means that users who has active global toggle, don't have any way now of switching back to the default view.

This seems to be blocking the activation of the new block widgets feature.

#### Steps to reproduce

1. Make sure the user option behind the old global "show wp-admin pages" toggle is active. You can do this by dispatching the Redux action below via Redux devtools:
```
{
type: 'PREFERENCES_SAVE',
key: 'linkDestination',
value: 'true'
}
``` 
2. Check the Appearance > Customizer or the Appearance > Widgets menu.

#### What I expected

To see a Screen Options tab so I can switch back to the default view in Calypso.

#### What happened instead

No Screen Options tab is rendered, so I'm stuck in the classic view in WP Admin.

**Comment by mmtr** [comment]
@JanaMW27 since you worked in the design of the "Screen Options" solution, are you able to take a look and propose a design for including the quick switcher on the Customizer screens?

**Comment by JanaMW27** [comment]
After exploration and chat with @mmtr we have decided to default to wp-admin in all pages since the functionality is not lost and provides a consistent experience. In addition, the users can access the calyspo view through wp-admin.
