### ISSUE TITLE
Google Apps: Font / italics issue on "billed yearly" text

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#5523]
Starting at URL: https://wordpress.com/domains/manage/email/:site:

Font / italics issue on "billed yearly" text:
![pasted_image_5_23_16__7_29_am](https://cloud.githubusercontent.com/assets/3011211/15474116/23ec4224-20b8-11e6-9667-092885ca3495.png)

**Comment by jeremeylduvall** [comment]
Closed via #5588
