### ISSUE TITLE
Editor: Block preview styles not loaded

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#55248]
### Steps to Reproduce

1. Create a new post or page and add a block that has styles, like Table, Images, or Tiled Gallery. 
2. Open the block settings and check and toggle the Styles section if it's not opened. 
3. Check the preview images:

![Markup on 2021-08-06 at 18:09:56](https://user-images.githubusercontent.com/1046943/128539999-5d9c1b66-6eec-46a0-ba43-6f7cfd206a7c.png)

### What I expected to happen

See the images for each block style.

### What actually happened

Block style preview images are not being displayed. 

I can see that the "image" it's an empty iframe: 

![Markup on 2021-08-06 at 18:06:57](https://user-images.githubusercontent.com/1046943/128540114-20684404-5ac8-43b8-a586-30237f4da6b9.png)

### Context

I've seen that while testing. 

### Operating System

macOS

### OS Version

11.5.1 (20G80) (Big Sur)

### Browser

Chrome/Chromium

### Browser Version

Version 92.0.4515.107 (Official Build) (x86_64)

### Simple, Atomic or both?

Simple, Atomic

### Console and/or error logs

I've spotted the following JS error on the dev console (I've changed my WPcom site URL): 

```
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://mysite.wordpress.com/wp-admin/') with script ('https://mysite.wordpress.com/wp-admin/?frame-nonce=4de0e21c06?service-worker'): The script has an unsupported MIME type ('text/html').
```

### Reproducibility

Consistent

**Comment by kosiew** [comment]
Hi @jartes ,

Thanks for reporting this and the detailed steps.

I managed to reproduce this with a non-automattic account.

![Markup on 2021-08-11 at 15:02:45](https://user-images.githubusercontent.com/29057562/128984314-b1450750-a3c1-4105-9da1-6d53bc8b61ff.png)

Triaging for developers' further investigation.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by arcangelini** [comment]
Spent some time investigating this. It looks like this may be core-related. I tested on my WordPress.org site and found the same thing:

<img width="429" alt="Markup 2021-08-11 at 16 29 56" src="https://user-images.githubusercontent.com/33258733/129098904-f031eebc-a802-492a-be60-f02d04c8055b.png">

**Comment by cometgrrl** [comment]
This bug is no longer applicable as the feature has changed on core. The style previews are now shown to the left when you hover on the buttons.
