### ISSUE TITLE
Private site Viewers automatically changed to Followers when invited

### ISSUE THREAD

**Issue by kcswong** [Automattic/wp-calypso#55259]
### Steps to Reproduce

1. Set site to Private
2. Invite a user as a Viewer from Users > Add New
3. Go back to Users > Invites

### What I expected to happen

Invited user should be listed as a pending Viewer

### What actually happened

Invited user is listed as pending Follower, and therefore doesn't have access to view the Private site.

### Context

Follow up in 4204169-zen. Replicated on another Simple test site. 

### Operating System

macOS

### OS Version

Big Sur 11.5.1

### Browser

Chrome/Chromium

### Browser Version

92.0.4515.107

### Simple, Atomic or both?

Simple

### Level of impact

Blocker

### Reproducibility

Consistent

**Comment by kosiew** [comment]
Hi @kcswong  ,

Thanks for reporting this and the detailed steps.

Triaging for developers' further investigation.

**Comment by sixhours** [comment]
I'm not quite able to reproduce this one. I do see that the invited user is incorrectly marked as a "Follower":

<img width="776" alt="Screen Shot 2021-08-31 at 9 48 22 AM" src="https://user-images.githubusercontent.com/2124984/131514275-42c9e180-c627-4cb6-8927-a3a3b86f80c4.png">

But upon accepting the invite, they're listed as a "Viewer" and they're able to see the private site:

<img width="816" alt="Screen Shot 2021-08-31 at 9 48 08 AM" src="https://user-images.githubusercontent.com/2124984/131514585-4a9e5aed-b2eb-4866-a56e-16471e5c86e6.png">

<img width="1680" alt="Screen Shot 2021-08-31 at 9 49 49 AM" src="https://user-images.githubusercontent.com/2124984/131514552-358ebb7c-11a2-491a-a874-c00bbd803f3c.png">

@kcswong Could you send me your test site where this is happening so I can debug further? You can either ping me on Slack or post it here. Thanks!

**Comment by sixhours** [comment]
It looks like we don't even include "Viewer" as a role in the badge text function so it's just falling back to "Follower":

https://github.com/Automattic/wp-calypso/blob/c7f615f7a3deb6cb6f27e703df6f4d2754d763df/client/my-sites/people/people-profile/index.jsx#L37

I can probably fix that so it's less confusing, at least.

**Comment by sixhours** [comment]
Aha, looks like we need to use `getWpcomFollowerRole`(https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/get-wpcom-follower-role.js) in the pending invites list rather than looking at `user.role` directly, since the role is still `follower`, we just call it "Viewer" if the site is private. Will work on that.

**Comment by kcswong** [comment]
Ah, I had totally skipped the final step of accepting the invitation! I got so caught up in getting this reported, so sorry about that. Going back and reading over the original chat with the user, I think this may have been something they missed as well, that the invited viewers needed to accept the invitation and be logged in, in order to see the Private site.

**Comment by sixhours** [comment]
Fixed in #55866!
