### ISSUE TITLE
Timeline Block: Editor displays extra timeline line

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#55263]
### Steps to Reproduce

1. Add the timeline block to a page/post with two entries
2. On the parent block select **Alternate items**.
3. View the extra line that appears to form a square instead of the proper styling that appears in the Editor. 

![Markup on 2021-08-07 at 12:40:20](https://user-images.githubusercontent.com/24914028/128586874-cefdd080-2b61-40e2-b504-c8e77e22d1a1.png)

### What I expected to happen

That the Block Editor would have parity with what is shown on the live site. 

### What actually happened

The Block Editor displays an extra line that does not match what is shown on the live site. 

### Context

4204264-zen

### Operating System

Windows, macOS, Linux

### Browser

Chrome/Chromium, Firefox, Safari, Microsoft Edge (legacy)

### Simple, Atomic or both?

Simple, Atomic

### Level of impact

Low

### Reproducibility

Consistent

**Comment by kosiew** [comment]
Hi @joweber123 ,

Thanks for reporting this and the detailed steps.

I could reproduce this on a Simple site.

Triaging for developers' further investigation.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
I am unable to replicate this unless I squeeze the viewport to a very narrow width with the block list panel open.
Do you have a direct link to the post where I can test with @joweber123 & @kosiew?

![image](https://user-images.githubusercontent.com/1287077/132516733-2f0ef922-fa55-4ff9-8cf1-43aa694dbe29.png)

**Comment by joweber123** [comment]
I am unable to reproduce this any longer.  The issue must have been solved in some release since this was created. Closing this issue.
