### ISSUE TITLE
Independent Publisher 2: Mobile menu toggle displays as white on white

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#55272]
### Steps to Reproduce

1. Switch a WordPress.com site to Independent Publisher 2 theme
2. Do not change the default colors in the Customize > Colors & Backgrounds section
3. View site on mobile

### What I expected to happen

The menu toggle should be visible

### What actually happened

The menu toggle displays as white text and border and is not visible on the white background

### Context

reported in 4206173-zen

@kathrynwp found that there was a change made 3 days ago that may be causing this: r59479-wpcom-themes

I provided the customer with a workaround for now to fix it:

```
button#primary-menu-button {
    color:#0087be;
}
```

Also reproduced on my test site: https://melissasgutenbergteststuff.blog/

### Operating System

macOS

### Browser

Chrome/Chromium

### Is this specific to applied theme? If so, what is the theme name?

Independent Publisher 2

### Simple, Atomic or both?

Simple

### Level of impact

Low

### Reproducibility

Consistent

**Comment by kathrynwp** [comment]
pinging @sixhours since you worked on this recently - thanks! :)

**Comment by sixhours** [comment]
Yep, I probably broke something. :) Will work on this today.

**Comment by sixhours** [comment]
Patch started here: D65278-code

**Comment by sixhours** [comment]
Deployed fix in r59495-wpcom-themes
