### ISSUE TITLE
VideoPress: Allow Play Button Size Customization

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#55273]
### What

A setting in Video blocks or within VideoPress to customize the Play button size

### Why

Customer noticed that the Play button appears bigger than previously and wanted it smaller, in #31030242-hc. Because it's in an iframe, we can't change it with CSS

**Comment by rinazrina** [comment]
I have another user requesting this: 4356723-zd-woothemes

**Comment by ClassicRKR27** [comment]
I've got another request here: 33243822-hc

**Comment by msilbers** [comment]
requested in 34175624-hc
they find it entirely too large and were hoping to make it smaller or even remove it

**Comment by muffinpeace** [comment]
Requested on 5189678-zen.

**Comment by edequalsawesome** [comment]
Also requested in 5297311-zen

**Comment by ghost** [comment]
Another request here: 36495458hc

**Comment by roundhill** [comment]
We recently made it smaller, so hopefully that satisfied some customers. It's not customizable, however. We can revisit if we get more requests for it?
