### ISSUE TITLE
Wellness Blog

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#55276]
We are working to improve the WP experience for bloggers and offering better blog designs is key to this effort.

We have many gaps in our blog designs, so this is a part of the effort to fill them up. We already have a couple of designs in the pipeline: pcjTuq-p4-p2

**The general process:**
1. Pick up one of the verticals we want to fill and start the design process in Figma.
2. Post for feedback + design iteration.
3. Build in the Editor + design teaks as needed.
4. Generate theme (pd2qbF-cA-p2).
5. Add starter design to signup.

This issue will tackle the wellness blog, for which design is underway (step 1 above). Here's an initial screenshot from Figma (WIP): 

![Frame 2](https://user-images.githubusercontent.com/4550351/128791749-c445bba3-03f6-436a-8070-cca948f8e9cd.jpg)

**Comment by alaczek** [comment]
We have many gaps in our blog designs, so this is a part of the effort to fill them up. We already have a couple of designs in the pipeline: pcjTuq-p4-p2

**The general process:**
1. Pick up one of the verticals we want to fill and start the design process in Figma.
2. Post for feedback + design iteration.
3. Build in the Editor + design teaks as needed.
4. Generate theme (pcjTuq-p4-p2).
5. Add starter design to signup.

This issue will tackle the wellness blog, for which design is underway (step 1 above). Here's an initial screenshot from Figma (WIP): 

![Frame 2](https://user-images.githubusercontent.com/4550351/128668139-2ccc7dd5-c7ac-4cc4-8eb2-a0cca2f90c3d.jpg)

**Comment by jordesign** [comment]
@autumnfjeld  - I'm closing this as the tracking issue seems to be no longer needed. Please re-open if it is needed for some reason.
