### ISSUE TITLE
Donations block: Stripe checkout is unresponsive when viewed using iOS 14

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#55279]
### Steps to Reproduce

1. Use iOS device with iOS 14 (for example, iPhone)
2. Open a page with Donations block
3. Type or choose the amount. Click "Donate"

### What I expected to happen

In mobile, I expect to see black/dark green overlay and a pop-up window for Stripe payment and checkout.

Please check the GIF recording (from Browserstack) here:
https://cldup.com/HqGemSuDBI.gif

Please note, the device information:
iOS 13. Browser Safari

### What actually happened

Black overlay with no pop-up window for Stripe payment and checkout.

Please check the GIF recording (from Browserstack) here:
https://cldup.com/atrg5JgOMq.gif

Please note, the device information:
iOS 14. Browser Safari

### Context

Customer report, and I able to replicate it. This issue does not happen on Android, so I feel this issue is restricted on iOS 14.

### Operating System

macOS

### OS Version

iOS 14.x

### Browser

Safari

### Simple, Atomic or both?

Atomic

### Console and/or error logs

No console error.

### Level of impact

Normal

### Reproducibility

Consistent

### Workaround

If users needs a fix quickly, can consider to:

* install a plugin, https://wordpress.org/plugins/search/donation/
* add PayPal donate button, https://wordpress.com/support/paypal/#donate-button

### Other information

Slack discussion:
p1628487486262400-slack-C03TY6J1A

**Comment by kosiew** [comment]
Hi ,

Thanks for reporting this and the detailed steps.

I could reproduce this on a AT site.

Triaging for developers' further investigation.

**Comment by nickpagz** [comment]
We had directed this user to check with Apple and Stripe as it may be related to one of those. Apple directed the user to Stripe, and Stripe responded by pushing back on us, saying it is related to the modal window not coded correctly, which seems likely, tbh.
#4207539-zen

FWIW, Chrome on iOS 14 also does the same. 

Also, and possibly un-related, in desktop Chrome console window, the following error is shown only on this user's page:
https://d.pr/i/kIBmRB
...though the modal works just fine on desktop.

**Comment by cometgrrl** [comment]
This is still reproducible. I have iOS 16 beta installed on my phone, and could replicate it in Chrome and Safari.

**Comment by dsas** [comment]
I couldn't repro this with ios 15.5 on the iphone simulator, testing against a simple site.

**Comment by rcrdortiz** [comment]
I also can't reproduce the error on Atomic sites using iOS 15.5. The donations form now seems to be opening the donation screen instead of using a pop-up.


https://user-images.githubusercontent.com/1989914/185331721-53fc820b-bd34-4d36-84d3-9e64342f0349.mp4
