### ISSUE TITLE
WordPress.com Stats: Previously included countries no longer included in traffic sources

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#55283]
### Steps to Reproduce

1. Head to WordPress.com > My Sites > Stats
2. For certain days, countries that were previously listed as traffic sources are no longer listed
3. For example, 2 August 2021, 31 July 2021, 27 July 2021

![Capture_2021-08-09 at 11 27 54@2x](https://user-images.githubusercontent.com/2912202/128678543-684e3290-589e-47cf-9c4c-9f75b5934aec.png)

 

### What I expected to happen

Countries that were previously included as sources of site traffic should continue to be listed as sources of traffic.

### What actually happened

It seems that previously included countries are not consistently being displayed as sources of traffic.

### Context

This is a customer report from 4196951-zen for the site `believeinbetternow.wordpress.com`

### Operating System

macOS

### OS Version

11.5.1

### Browser

Firefox

### Browser Version

91.0b9 

### Is this specific to applied theme? If so, what is the theme name?

No, doesn't seem to be theme specific

### Simple, Atomic or both?

Simple

### Console and/or error logs

Not sure if this is relevant. I noticed this error in my browser console:

```
GETwss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data
[HTTP/1.1 403 Forbidden 483ms]

GET
	wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data
Status403
Forbidden
VersionHTTP/1.1
Transferred210 B (0 B size)

    	
    HTTP/1.1 403 Forbidden

    Server: nginx

    Date: Mon, 09 Aug 2021 08:31:16 GMT

    Content-Type: text/plain

    Content-Length: 9

    Connection: keep-alive

    X-ac: 2.vie _dca

    Strict-Transport-Security: max-age=15552000
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-GB,en-US;q=0.7,en;q=0.3
    Cache-Control
    	no-cache
    Connection
    	keep-alive, Upgrade
    Cookie
    	wordpress_logged_in=support-session-noauth; wordpress_test_cookie=WP+Cookie+check; _wpndash=1150f0112bbfd06a82a86ff9; wpc_wpc=account=believeinbetternow&avatar=https%3A%2F%2F2.gravatar.com%2Favatar%2F8a1f2b3db79195a8bd450e2e6f1e3a30%3Fs%3D25%26amp%3Bd%3Dhttps%253A%252F%252Fs0.wp.com%252Fwp-content%252Fmu-plugins%252Fhighlander-comments%252Fimages%252Fwplogo.png&email=daviddhelmers%40gmail.com&link=https%3A%2F%2Fbelieveinbetternow.com%2F&name=believeinbetternow&uid=159925158&access_token=13f5491fe356985b7a835b11b03d59e0f7d676ea; tk_qs=
    DNT
    	1
    Host
    	public-api.wordpress.com
    Origin
    	https://public-api.wordpress.com
    Pragma
    	no-cache
    Sec-Fetch-Dest
    	websocket
    Sec-Fetch-Mode
    	websocket
    Sec-Fetch-Site
    	same-origin
    Sec-WebSocket-Extensions
    	permessage-deflate
    Sec-WebSocket-Key
    	l07DsTkD42dm9LAouXoZTw==
    Sec-WebSocket-Version
    	13
    Upgrade
    	websocket
    User-Agent
    	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
```

### Level of impact

Normal

### Reproducibility

Consistent

### Other information

An HE pointed out that it may be worth checking whether the countries appear in `$clist` here:

```
SELECT country, SUM(views) views FROM stats_{$_date}_geoviews WHERE blog_id = %d AND country IN ($clist) GROUP BY country
```

Could we check if countries that were previously included as traffic sources are not included in the referenced countries list for some reason?

**Comment by kosiew** [comment]
Hi @pauljacobson ,

Thanks for reporting this and the detailed steps.


Added next investigation steps - 29f12-pb

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by inaikem** [comment]
User reports:

- Forum / 3710874 (@jerrysarcastic)
- 30782822-hc (@inaikem)
- 31050448-hc (@inaikem)
- 4196951-zen (@eduardozulian)
- 4191822-zen (@cuemarie)

The above, mostly via p1628037881042400-slack-C01UW7SB411.

**Comment by ChrissiePollock** [comment]
Another report - 4171465-hc

**Comment by Gustavo-Hilario** [comment]
Another report here: 650590-hc - Simple site.

**Comment by inaikem** [comment]
@Robertght: One for FP/Create to investigate 🙏

**Comment by KirkwallDay** [comment]
This is triaged, so closing 4226506-zen for now, please create a follow-up ticket to notify them when it is resolved.

**Comment by thabotswana** [comment]
Another report - 4233594-zen

**Comment by KirkwallDay** [comment]
Closing 4196951-zen for now, please create a follow-up ticket to notify them when this issue is resolved.

**Comment by alshakero** [comment]
In investigated the entire reading part of the stack, SQL Query -> PHP -> REST, and all seem fine. Sadly, it seems the recording that is broken, fixing this bug will only improve future records.

**Comment by the-misha** [comment]
Another report (simple site): 4196951-zd-woothemes

**Comment by allanftd** [comment]
Hi @alshakero, user 31050448-hc followed up on a new chat today 31164559-hc and said they still have consistency issues with Views data. Screenshot of their stats taken today - https://d.pr/i/OclEJP 
Could the Countries data be referring to Visits and not Views?

Ticket: 4258520-zen

> My query related to the recording of stats by country. Prior to 26 July the daily page views by country were almost always equal to the total number of page views shown. But since that date the total views are always (much) larger than the views by country. Here are some figures:
> 
> May 300 total, 300 by country
> 
> June 523 total, 523 by country
> 
> July 451 total, 299 by country
> 
> August 892 total, 347 by country
> 
> This sudden change makes me think there is probably something wrong with the stat I'm seeing these days.
>

**Comment by ogodoabiola** [comment]
HC-4271555

**Comment by msilbers** [comment]
reported in #31541042-hc
almost all country information is missing

**Comment by inaikem** [comment]
@msilbers, hope you don't mind but I edited the reference above to `hc` 

@alshakero, are you able to take a look at @allanftd's comment above? 

Any idea if flow Patrol's going to have a chance to look into this further any time soon? Thanks!

**Comment by bobmatyas** [comment]
Another report here: https://wordpress.org/support/topic/histogram-vs-heat-map-stats-mismatch/?view=all

**Comment by bazza** [comment]
This is the expected behavior since not all views can be geolocated.  There are a few reasons for this, but a couple of them are 

(a) the IP address is listed as an anonymous proxy in the geo IP database. This could happen if a site is visited using Tor, for example.   

(b) the IP address just isn't in the geo ip database at all for whatever reason.

If it would help prevent confusion we could add some sort of tip to the stats page to explain that not all views can be geolocated or we could try to fill in the gap using some sort of "N/A" or similar country status

**Comment by hideandgeek404** [comment]
@bazza I have had the customer from 4334355-zen come back with the following having seen your comment about it being expected behaviour.

> I understand that a visitor may be behind a VPN or there might be some reason why the country cannot be identified. But until 26 July 2021, the country could be identified for virtually every one of my page views. Then, since that date, we suddenly find less than half the views can be geolocated.

>This seems a very strange occurrence and suggests to me there is something going on that is more than just expected behaviour.

**Comment by rinazrina** [comment]
Got another report here: #4562900-zen

Suddenly there are big discrepancies between total views and views by country starting from Nov 15th, 2021. 

<img width="1094" alt="Markup 2021-12-03 at 17 46 37" src="https://user-images.githubusercontent.com/33721365/144581881-a90ba148-e7d7-41fc-8a08-4a633aeab37e.png">

**Comment by Greatdane** [comment]
@bazza I see this is in the 'in progress' board but I am not sure if it's actively being worked on? The user is pretty unhappy with the discrepancies. Not sure if an actual bug is causing the larger discrepancies recently.

**Comment by sharonlaker19** [comment]
A user came back to check on this at 4633070-zen

**Comment by jordesign** [comment]
Flagging this for some further investigation. Whilst it is the expected behaviour (thanks @bazza) that not *all* views will be assigned to a country - the larger discrepency in some of these items means it might be worth some further investigation.

**Comment by daledupreez** [comment]
I've done some deeper exploration and can see that the gap in views seems to accompany a notable increase in views as well. This suggests that there may be bot activity involved, but I am not sure if that's what is going on.

I have kicked off an internal discussion to see if I can get access to the logs we use to build the relevant page view data. pMz3w-fmu-p2

**Comment by daledupreez** [comment]
We've now worked out that the bug stems from situations where we can't determine a geolocation. When this happens, we're not recording those as views from an unknown location, which gives us a big discrepancy between page views and geolocated page views. The core problem was spelled out in pMz3w-fmu-p2#comment-99270.

I have now put forward two related changes to support this more clearly:
 * D82573-code - this patch returns a country code of `ZZ` when we don't know where a viewer was located
 * D82577-code - this patch updates our processing to handle these unknown viewer locations

**Comment by daledupreez** [comment]
As of a few hours ago, we have addressed this issue by ensuring that we correctly track page views where we can't determine the region of the visitor. The most common situation for this is where a user has an anonymous proxy/service that masks their IP address (and thus where they are), but it's also possible that your visitors are using a satellite internet provider.

We now have this data starting from just before 18:00 UTC, and "Unknown Region" (or its translation) should now be appearing in users' stats on Calypso.
