### ISSUE TITLE
Classic block - Caption not showing up for WebP images

### ISSUE THREAD

**Issue by syds87** [Automattic/wp-calypso#55287]
### Steps to Reproduce

1. Add a new Classic block
2. Click the Add Media icon
3. Choose a WebP image from the library or upload a new WebP image.

### What I expected to happen

I expected to see the caption, as it happens if I choose a JPG image, instead of a WebP one.

### What actually happened

The caption is not displayed, under the image.

### Context

Reported in #4207206-ZD
I have tested this on my test site as well. The caption is showing perfectly for JPG images: https://d.pr/i/WTB6Aa
But when I add a WebP image, this is not happening: 
https://d.pr/i/nbfVAw
https://d.pr/i/Ri7ou3

Tested on different themes.

### Operating System

macOS

### Browser

Firefox

### Simple, Atomic or both?

Simple, Atomic

**Comment by kosiew** [comment]
Hi @syds87,

Thanks for reporting this and the detailed steps.

I could not reproduce this and am closing this for now. Please feel free to re-open if you have further findings to add.

![image](https://user-images.githubusercontent.com/29057562/129156283-849b83d6-7730-493c-a0c9-9043d1cd644a.png)
