### ISSUE TITLE
Tag education in the Editor

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#55300]
## Why
A new blogger or publisher (or even an existing one) mayb not be familiar with how tags work, what their impact are, how they are related to the Reader.  

## What
We can add small helpful copy in the Editor Settings sidebar "tags section" to link to support docs.

![a post by autumn](https://user-images.githubusercontent.com/5665959/128781425-8f1e7b1e-cf72-4b7d-8a8c-c10ee68913a2.png)

Copy Suggestions
pdgK6S-14-p2#comment-51
![image](https://user-images.githubusercontent.com/5665959/128781616-3809143b-e825-4373-b00d-c1e1f0495e6e.png)

## Tech checklist
- [ ] New copy "Build your audience with tags" goes underneath the the existing “Separate with commas or the Enter key.” 
- [ ] Add new copy to the post confirmation section (see Eru's screenshot below) 
- [ ] link out to https://wordpress.com/blog/2014/04/21/better-tagging/
- [ ] Tracks events or bump stats to evaluate usage
 

Thanks @arthur791004 for getting this discussion going in pdgK6S-14-p2

**Comment by roo2** [comment]
We should also update the pre post confirmation section. I would check with Krista Stevens about changing this copy, or just add that  https://wordpress.com/blog/2014/04/21/better-tagging/ link here as well.
<img width="273" alt="Screen Shot 2021-08-10 at 12 42 34 pm" src="https://user-images.githubusercontent.com/22446385/128800302-ea4bc57c-e5ed-4ab2-8be9-17271557dcc5.png">

**Comment by arthur791004** [comment]
Here is the screenshot after adding the new copy

#### Tags Block
![image](https://user-images.githubusercontent.com/13596067/128978721-860039c6-5700-4159-b047-f9ca88a63fe9.png)

#### Pre Post Confirmation Check
![image](https://user-images.githubusercontent.com/13596067/128978768-75a77b92-cbde-430c-bf95-94d2e67256fe.png)

I made all of the new copy "Build your audience with tags"  be a clickable link which aligned the styles with eduction tips of **Excerpt** section
![image](https://user-images.githubusercontent.com/13596067/128979091-ebf98d1b-2bc5-4f3f-95e6-c250421f9034.png)

Is there any style that needs to adjust?

And I'll focus on how to track or bump stats to evaluate usage

**Comment by autumnfjeld** [comment]
@donalirl  Just wanted to flag this with you as it seems aligned with the [Trail Markers ](https://href.li/?https://docs.google.com/spreadsheets/d/14dlqA7_3n9UF7-to-nHW2tKB6vlEuBnXcKNSGKbFg6g/edit#gid=0) work.  We'll be thinking of ideas like this from a blogger perspective in the Blogger Experience pod. :)

**Comment by autumnfjeld** [comment]
>  I would check with Krista Stevens

Agreed @arthur791004 .  Maybe ping Krista in slack, with a link to your comment above, to get her input when you are ready for that.

![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=30)

**Comment by donalirl** [comment]
This is awesome! Very much aligns with Trail Markers and the HG post. 

However, please do not link out to a blog post from 2014 in the interface! Can you link to https://wordpress.com/support/posts/tags/ instead? Happy to make any updates to that doc as necessary as well.

**Comment by arthur791004** [comment]
@kristastevens Do you have any ideas for https://github.com/Automattic/wp-calypso/issues/55300#issuecomment-895684683? Also, [here is the screenshot after adding the new copy](https://github.com/Automattic/wp-calypso/issues/55300#issuecomment-896535182)

**Comment by arthur791004** [comment]
@donalirl Do we have a related link under https://wordpress.org/support/ ? If so, it's easier to add the link in the editor!

**Comment by donalirl** [comment]
> @donalirl Do we have a related link under https://wordpress.org/support/ ? If so, it's easier to add the link in the editor!

Please use this link: https://wordpress.com/support/posts/tags/ That's our official .com doc on tags.

We want to avoid using any more .org links (and we're looking at ways to change existing .org links to .com equivalents.)

**Comment by simison** [comment]
Worth considering what of this can be suggested directly at Gutenberg as well, even if the docs link would be different from ours.

**Comment by kristastevens** [comment]
@arthur791004, we should probably use this link in the editor: https://wordpress.com/support/posts/tags/

**Comment by arthur791004** [comment]
@kristastevens Yeah, I use that link 👍

**Comment by p-jackson** [comment]
#55436 has merged

**Comment by donalirl** [comment]
@p-jackson The wrong link was used. It's linking to a very old blog post: https://wordpress.com/blog/2014/04/21/better-tagging/

The correct link is https://wordpress.com/support/posts/tags/ as mentioned at https://github.com/Automattic/wp-calypso/issues/55300#issuecomment-897278128 and https://github.com/Automattic/wp-calypso/issues/55300#issuecomment-897684534

**Comment by arthur791004** [comment]
@donalirl Thank you for checking. As mentioned at pdgK6S-14-p2#comment-159, @kristastevens has updated that post.

**Comment by donalirl** [comment]
> @donalirl Thank you for checking. As mentioned at pdgK6S-14-p2#comment-159, @kristastevens has updated that post.

Great, I've commented there. Let's leave this open until we can resolve the two issues mentioned there.

**Comment by p-jackson** [comment]
Link has been changed to the translated support site
