### ISSUE TITLE
Unclear error in Calypso when trying to rename wpcomstaging address

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#55306]
### Steps to Reproduce

1. Create AT site without a custom domain
2. try to rename the site once it's gone AT
3. see the following error
![2021-08-11 at 09 56](https://user-images.githubusercontent.com/47717887/128983437-f7f067b3-832a-4801-917a-cdf00e4ea438.jpg)

### What I expected to happen

They shouldn't be given this as an option in the first place
- also it would be nice if there was a clear reason given for why they can't change
- ala this section: https://wordpress.com/support/changing-site-address/#a-note-on-wpcomstaging-com-addresses

### What actually happened

It gives an error but doesn't explain why or what to do about it

### Context

p1628584715162900-slack-C03TY6J1A
User wanting to change address and workaround is to create a new site and import other contents... not a good option

### Operating System

macOS

### Browser

Chrome/Chromium

### Is this specific to applied theme? If so, what is the theme name?

no

### Simple, Atomic or both?

Atomic

### Available Workarounds

Add a custom domain
create a new site and import contents <- terrible option

### Reproducibility

Consistent

**Comment by Robertght** [comment]
Thank you for sharing this Nic! The error message you got only showed up for me when I started to type the new address, but this came up after I was done:

![image](https://user-images.githubusercontent.com/6737345/129672746-42a8cdb2-1d4e-4356-afc3-eba461a511fa.png)

I'm not sure if this should be an option on AT sites for the staging domain, but I'm checking with Flow patrol.

**Comment by jordesign** [comment]
Maybe something Explorers/Simple > Atomic Pod can pick up?

**Comment by allilevine** [comment]
@Nic-Sevic @galakhyati 👋 We have [a PR open](https://github.com/Automattic/wp-calypso/pull/57408) to change the error message to "wpcomstaging.com addresses cannot be changed," which is the same text we show for Atomic sites on this page. Do you have any suggestions for making that clearer? Should we link to the Domains page?

**Comment by pablinos** [comment]
I think our current fix that improves the error message is good, but from a parity perspective, I wonder what it would take to allow this for Atomic sites.

There's a 1:1 relationship between the wordpress.com subdomain and the wpcomstaging.com one, so we could use the current mechanism to change the blog ID's subdomain and then have a way of informing the Atomic site that it needs to update.

It's probably not that straightforward, and as most Atomic customers will have a domain too, it may not be worth it, but I think it could work as a solution.

**Comment by Nic-Sevic** [comment]
@allilevine Sorry I didn't respond when you tagged me! For some reason I only got a notification when the threads were closed. I think saying that "wpcomstaging can't be changed" works just fine, thank you for changing it!

**Comment by allilevine** [comment]
> @allilevine Sorry I didn't respond when you tagged me! For some reason I only got a notification when the threads were closed. I think saying that "wpcomstaging can't be changed" works just fine, thank you for changing it!

No worries, we landed on "This site's address cannot be changed"
