### ISSUE TITLE
Domains: Email with + does not register error

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#5531]
#### Steps to reproduce
1. Starting at URL: wordpress.com/start
2. Create an account with a + in the email address (user+something@gmail.com for example)
3. Create an account with a custom domain name
4. When you get to the domain details page, the email address is not valid, but an error will not be shown unless you click into the field or submit.
5. The main issue here is that if the "Domain Privacy" modal shows, you cannot see this error, and the privacy selection buttons do not work. The modal still shows even if the email has an error.

#### What I expected

To see an error on the email field instantly. And also for the modal to not show if there are errors.

#### What happened instead

The modal showed, and covered up the error, the buttons in the modal did not work.

#### Browser / OS version

Chrome latest, mac os x

/cc @fabianapsimoes

**Comment by apeatling** [comment]
I think the modal is an active a/b test, because I didn't get it on my second time around.

**Comment by fabianapsimoes** [comment]
This would be something for team Cobalt. cc @wensco

**Comment by klimeryk** [comment]
This seems to be a regression caused by the A/B test in #3838.
