### ISSUE TITLE
Hosting Configuration: No visual indication / clue when clicking `Copy` button within SFTP Credentials fields

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55316]
### Steps to Reproduce

1. Start at WordPress.com > My Sites > Settings > Hosting Configuration > Create SFTP Credentials
2. Try clicking any `Copy` button inside the text fields

### What I expected to happen

See some visual indication of the button being clicked or some message confirming that the value has been copied.

### What actually happened

There is no visual indication of the button being clicked or some message confirming that the value has been copied.

### Context

Encountered in 4208655-zd-woothemes after testing the SFTP Credentials creation on my own AT site

### Operating System

macOS

### OS Version

BigSur 11.4

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple, Atomic or both?

Atomic

### Number of Users Impacted

All users

### Reproducibility

Consistent

### Other information

https://user-images.githubusercontent.com/39308239/128865368-8aa0f105-722b-4718-9d07-de81d63b7000.mov

**Comment by Robertght** [comment]
Thank you for reporting this Denys! I can confirm the same thing on my end, regardless of the browser.

**Comment by Aurorum** [comment]
PR for this issue in #56427. :)
