### ISSUE TITLE
Features: Fix Akismet availability for free Jetpack

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#55328]
### Details

The new features framework was added here: D63248-code
We currently return `akismet` as a feature for all Jetpack plans, but it's not available on free Jetpack sites (reference: p1625664961316000/1625664780.314700-slack-CDLH4C1UZ).
It is available for all free WPCOM sites.

### Checklist

- [ ] Update the feature availability.
- [ ] Check that the change doesn't remove the Akismet feature for any site that should have it.
- [ ] Check for Akismet availability correctly from Calypso.

### Related

https://github.com/Automattic/wp-calypso/issues/54735

**Comment by obenland** [comment]
See D79892-code
