### ISSUE TITLE
Videopress File Size 0.00 B on AT sites

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#55343]
### Steps to Reproduce

1. On an atomic site with Videopress is on
2. Upload an MP4 (any size)
3. Give it time to convert
4. Refresh page
5. Click the video, and press Edit in the top left to see details
6. Notice: File Size 0.00 B | https://d.pr/i/NIbwBz

 

### What I expected to happen

To see something like: File Size 16.03 MB

### What actually happened

The size displayed is 0

### Context

hc-31041291
zd-4208957

### Operating System

macOS

### OS Version

10.15.7 (19H1217)

### Browser

Firefox

### Browser Version(s)

90.0.2

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple, Atomic or both?

Atomic

### Number of Users Impacted

Most users (>50%)

### Available Workarounds

Disabling Videopress
The videos still work as expected

### Reproducibility

Consistent

**Comment by inaikem** [comment]
Closing in favour of #54434
