### ISSUE TITLE
FAB Covers bottom of Publish confirmation Screen

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#55345]
### Steps to Reproduce

1. Start a new Post or Page
2. Click 'Publish' to reveal the pre-publish check.

### What I expected to happen

I should be able to see and access all options in the panel

### What actually happened

The FAB (Floating Action Button) at bottom right obscures the label of the 'Always Show Publish Check' option

### Context

User testing

### Operating System

macOS

### Browser

Chrome/Chromium

### Browser Version(s)

Also confirmed in Safari

### Simple, Atomic or both?

Simple

### Number of Users Impacted

Most users (>50%)

### Reproducibility

Consistent

### Other information

This only effects Simple Sites as Atomic sites do not show the FAB. Confirmed in both Chrome and Safari.

<img width="330" alt="Screen Shot 2021-08-11 at 12 35 16 pm" src="https://user-images.githubusercontent.com/1842363/128962571-5d1e19d6-13ef-420b-9a2d-f869e97d124b.png">

**Comment by jordesign** [comment]
Adding this to the Blogger Experience board in the hope we can push out a small quick fix.

Maybe more padding at the bottom of the publish check?

**Comment by jordesign** [comment]
Removing this from the 'Blogger Experience' board as it is being covered by Flow Patrol (thanks).

**Comment by sixhours** [comment]
The fix here is simple, but figuring out where that fix should live is less so. 😅 I'm going to spin up a PR for the Editing Toolkit for now.
