### ISSUE TITLE
SEO Settings: Overloading the size of the meta description fields yields error, but can still save

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#5534]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/seo/YOURSITE.wordpress.com
2. Input more than 160 characters into the Meta Description field.  I used the Chrome extension Bug Magnet, since copy/pasting seems to actually cut off at 160 characters
3. Note the error
4. Click save

#### What I expected
A warning that the description was not actually saved, or maybe the field would be cleared out / reverted to indicate that the content was not saved.

#### What happened instead
I got a green Success notice

#### Browser / OS version
OSX Chrome

#### Screenshot / Video
![wp-calypso-seo-description-overload](https://cloud.githubusercontent.com/assets/7233112/15483248/bb311904-2101-11e6-8342-a993cf725d4e.gif)

**Comment by roundhill** [comment]
Not sure if this is an actual issue, since the field does cap input when typed/pasted in and the api will truncate it at 160 characters anyways.

**Comment by roundhill** [comment]
We added some nice enhancements to the warning in #5543. It doesn't directly address the issue, but the API will trim it to the maximum amount anyways so I think we're good.
