### ISSUE TITLE
Instagram Widget: Can never connect to Instagram account

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#55344]
### Steps to Reproduce

1. Go to "Appearance > Customize > Widgets" and select any available widget area
2. Add Instagram Widget
3. Hit "Connect Instagram Account" button
4. Hit "Allow" button in Instagram's authorization popup

### What I expected to happen

Authorization goes well and the widget starts displaying the latest Instagram posts.

### What actually happened

I get a popup from the browser asking if it's okay to leave a page before saving change. 

If I choose "Leave", Customizer just reloads. And the Instagram widget I added is just gone.

If I choose "Cancel", the Instagram widget remains but says "Connecting". And it can never be connected to Instagram account. 

### Context

I got a user report in 31067435-hc where their Instagram Widget on Footer stopped working suddenly. So I tried to add Instagram Widget to my test sites to see if it just works fine on my end. And I found this issue.

### Operating System

macOS

### Browser

Chrome/Chromium, Safari

### Simple, Atomic or both?

Simple, Atomic

### Number of Users Impacted

Some users (<50%)

### Reproducibility

Consistent

### Other information

Here is a video how I'm reproducing the issue on my end:

https://user-images.githubusercontent.com/32432463/128959460-5cfa7b18-883a-44a2-b1d5-674c47f90718.mp4of 

I'm wondering if this is actually related to the adoption of Block Widgets🤔

**Comment by kuropixel** [comment]
Another user experiencing this exact issue: 4211835-zen
I've also tested and have been able to reproduce the issue on a test simple site.

**Comment by kathrynwp** [comment]
Also reported in 4213922-zen (Simple Site)

Replicated on test site (Simple)

**Comment by hngdny** [comment]
SImilar issue on 4212151-zen (Simple Site)

Confirmed issue can be replicated on test site (Premium).

**Comment by erricgunawan** [comment]
Possible similar issue on 4215164-zd-woothemes (Simple site/Premium).

Confirming with the user.

**Comment by jartes** [comment]
Another one on #4203015-zen. We were able to connect the widget with the Classic Widgets plugin but the widget is not being displayed on the front-end. Suggesting to use the Instagram block instead.

**Comment by carladoria** [comment]
Another issue in [4217003-hc](4217003-zd-woothemes)
Suggested Instagram plugins, IMHO, if they have other widgets, it is not worth changing them to the whole classic view for one widget until this is fixed.

**Comment by msilbers** [comment]
reported in #4222192-zen
There's no available workaround since it's a Simple site

**Comment by DjamWork** [comment]
Seems like another issue reported in #4215164-zd

**Comment by RealCarFax** [comment]
Another report of this issue here: #31171597-hc
Moved it to a ticket here so we can follow up: #4228897-zd

**Comment by aetta** [comment]
A similar issue was reported on #4216194-zn

**Comment by inaikem** [comment]
@yansern, @sixhours, would it be possible for one of your pods to give this one a quick review? 

We're up to 10 reports over the past 7 days and I've just added this into our "[Needs reply](https://github.com/Automattic/wp-calypso/projects/112)" project. Thanks!

cc/ @Robertght

**Comment by sixhours** [comment]
I'm doing a quick dive into this to gauge the scope of the issue; will add my notes here.

Confirmed this only happens with this version of the Instagram widget; the other ones connect/embed as expected:

<img width="384" alt="Screen Shot 2021-08-18 at 9 57 59 AM" src="https://user-images.githubusercontent.com/2124984/129911651-5802bb6a-bae5-4342-b1f9-2017b360bf15.png">

A temporary workaround for users might be to switch to one of the other Instagram blocks.

**Comment by sixhours** [comment]
So this is happening because `window.wpWidgets` is `undefined`, so the widget fails to save because it has nothing to save to:

https://github.com/Automattic/jetpack/blob/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/modules/widgets/class-jetpack-instagram-widget.php#L476-L479

I suspect we need to figure out how to access`window.wpWidgets` from within the block editor. Instagram appears to be our only widget that uses this method - a search for `window.wpWidgets` in the code base only returns the core JS and this widget file.

**Comment by sixhours** [comment]
Confirmed the widget works as expected when I disable the widget block editor. That's another workaround for folks on the Business plan who want to install the Classic Widgets plugin: https://wordpress.org/plugins/classic-widgets/

<img width="288" alt="Screen Shot 2021-08-18 at 10 46 39 AM" src="https://user-images.githubusercontent.com/2124984/129919713-39f9a63b-77d2-486a-8385-e88cb2d93320.png">

**Comment by sixhours** [comment]
> A temporary workaround for users might be to switch to one of the other Instagram blocks.

~~Ahh, I just realized those blocks are only available for Premium plans. 😕 That's a bummer, because now we have two widgets that do essentially the same thing, but one is behind a paywall, and one is not (but is broken).~~

I'm trying to see if there's a hacky way to include the widgets.js base from core in the Instagram widget so it has access to that store when the Instagram widget is active.

**Comment by sixhours** [comment]
I need to step away from this; it looks like it's on Create's backlog, but a summary of what I've found:

* This is caused by using this widget in the block editor
* There are workarounds for Business customers (install [Classic Blocks plugin](https://wordpress.org/plugins/classic-widgets/)) everyone else should be able to switch to the newer block widgets instead
* The widget is trying to save to `wpWidgets` in [the core JS module](https://github.com/WordPress/wordpress-develop/blob/2382765afa36e10bf3c74420024ad4e85763a47c/src/js/_enqueues/admin/widgets.js#L10) and can't find it, so the operation fails

**Comment by sajmes** [comment]
Likely similar issue here: 31196600-hc. User requests to be notified when this is resolved.

**Comment by csonnek** [comment]
Noting another report in the forums: https://wordpress.com/forums/topic/instagram-widget-201/

**Comment by CodeAllNightNDay** [comment]
Similar issue here: 11239374-hc
Same exact behavior as on 4212151-zen

Simple Site with Premium plan on Olsen theme.

**Comment by hacchism** [comment]
Another report from 4227590-zen

**Comment by mzitinfo** [comment]
Hi, I've had this exact issue with the Instagram widget for a few months now on my test sites, so I don't think it's due to the implementation of block widgets. Related interactions were in 3977474-zen and 4023101-zen.

**Comment by kspilarski** [comment]
Same case as 4238135-zen.

**Comment by dcoleonline** [comment]
4236596-zen

**Comment by sajmes** [comment]
Another report 31276528-hc

**Comment by ahmadbaig1** [comment]
Report 4242292-zen

**Comment by carladoria** [comment]
~~ scratch report ~~
User was able to connect while chatting

**Comment by carladoria** [comment]
Another report in 4239003-zen 
User ended upgrading to Business plan. 
Do we have an estimate of when this will be fixed?

**Comment by edwinho89** [comment]
4254899-zen

**Comment by kspilarski** [comment]
4255054-zen

**Comment by oyadeyiseun** [comment]
4254519-hc

**Comment by rinazrina** [comment]
4240748-zd-woothemes

**Comment by sixhours** [comment]
Heads up, I chatted with @Robertght yesterday and realized I was wrong! The non-legacy Instagram blocks are available to **all users**,  not just premium, so that's a solid workaround.

**Comment by yansern** [comment]
> The non-legacy Instagram blocks are available to all users, not just premium, so that's a solid workaround.

Hi, I don't understand what non-legacy Instagram blocks mean? Are there 2 different Instagram blocks on WPCOM?

**Comment by sixhours** [comment]
> Hi, I don't understand what non-legacy Instagram blocks mean? Are there 2 different Instagram blocks on WPCOM?

Yep! There are three. Two modern blocks and one legacy widget:

<img width="374" alt="Screen Shot 2021-08-31 at 11 35 06 AM" src="https://user-images.githubusercontent.com/2124984/131532535-77c6f3c7-fd4c-4559-85ed-3406925afd28.png">

^ That's searching for "instagram" in the Customizer -> Widgets -> Block widgets area. The the two modern blocks still work, the legacy one is broken.

**Comment by hacchism** [comment]
> The non-legacy Instagram blocks are available to all users, not just premium, so that's a solid workaround.

> The the two modern blocks still work, the legacy one is broken.

Just to clarify, the Instagram modern block is just for embedding a single Instagram post. So it wouldn't work as a replacement for the legacy Instagram widget. The Latest Instagram Posts block would definitely work as a solid workaround though.

**Comment by arcangelini** [comment]
@hacchism from what I was testing the `Instagram` block is indeed for 1 post, but the `Latest Instagram Posts` should give you the options like the legacy widget.

### Findings
I spent some time digging into this and thought I would share my notes. It looks like this was an issue that popped up last year ( p1584639644028100-slack-CKZHG0QCR, pb5gDS-mB-p2#comment-1021 ). `wpWidgets.save` is how the previous block would refresh and save the token needed for Instagram. Does it seem like we may be able to create an API to handle the save?

**Comment by hacchism** [comment]
> @hacchism from what I was testing the Instagram block is indeed for 1 post, but the Latest Instagram Posts should give you the options like the legacy widget.

Thanks @arcangelini! Yes, I'm aware of that and mentioned that in my comment above too👍

**Comment by aleone89** [comment]
Another report the forums here: https://wordpress.com/forums/topic/instagram-widget-not-connecting/

**Comment by aleone89** [comment]
Another report in the forums here: https://wordpress.com/forums/topic/cant-link-my-instagram-on-the-widget-for-shawburn-theme/

**Comment by arcangelini** [comment]
Tested this also from `wp-admin/widgets.php` and ran into a slightly different issue. It looks like the JS that gets loaded in the absence of a token is not being loaded? I am still looking through this original issue but wanted to notate this here.

<img width="1083" alt="Markup 2021-09-03 at 08 59 29" src="https://user-images.githubusercontent.com/33258733/132019520-0db45c8e-9a26-41a7-bbcb-9e32de72e5b2.png">

**Comment by saraita90** [comment]
Similar issue: #4253121-zen

**Comment by daria2303** [comment]
Same case: 4276737-zd-woothemes

**Comment by jerrysarcastic** [comment]
Same issue reported in https://wordpress.com/forums/topic/i-cant-get-instagram-to-conncet/

**Comment by simison** [comment]
> the Instagram block is indeed for 1 post, but the Latest Instagram Posts should give you the options like the legacy widget.

Chatted with @arcangelini, summary;

- Let's hide the legacy widget from the inserter, effectively deprecating it. No reason to promote widget there anymore if we now have a block instead that works. That shouldn't completely remove the legacy widget; it should still work if people have it inserted in the widget area already.
- Let's add `transform` if possible; that'll let folks with old widget to transform to a new block. This is less urgent than hiding it.

Does the legacy widget that was previously connected to Instagram still work, or does that need some fixes?

**Comment by arcangelini** [comment]
[Just created a PR to remove the legacy Instagram option in the widget block editor](https://github.com/Automattic/jetpack/pull/21050).

During my testing, I was able to verify this should not affect anyone who is currently using the legacy version of Instagram. It only removes it from the available block/widgets in the block editor.

I will work on getting the `transform` pushed soon.
