### ISSUE TITLE
Feature Request: Update the first notification users get so it doesn't direct them to the customiser

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#55362]
### What

The very first notification we give users should direct them somewhere other than the customiser

### Why

We've all been trained to click on the little red un-read notification buttons. So when the user creates a site, and we send them an automatic notification (I suppose to teach them about that interface), the pull to click that little bell is very high IMO.

If they're going to open that notification it should be something that helps them with there onboarding. Perhaps if they were a blogger it'd direct them to write their first post? Since we don't know what type of user they are maybe taking them to My Home?

### How

Reworking this CTA in the first notification.
<img width="842" alt="Screenshot 2021-08-11 at 6 46 56 PM" src="https://user-images.githubusercontent.com/1500769/128982456-2371699e-dce0-4af7-8828-183c9e3544ed.png">

The "... right away!" really makes me feel like the customiser is the urgent bit!

**Comment by kwight** [comment]
Ooooh, yes please – I'm not sure My Home existed/was useful when I did that notif. 🙃 My Home is a much better destination. 👍

**Comment by autumnfjeld** [comment]
Cool, let's send user to My Home instead of the Customizer.

@kristastevens could you help us with new copy for that?  To replace  the copy that @p-jackson points to above with the pink arrow.

**Comment by kristastevens** [comment]
I think @p-jackson's idea of inviting users to write a post would be great. How about: 

Start drafting your first post! Need some inspiration? Check out our [library of writing prompts](https://wordpress.com/dailypost/prompts/).

**Comment by p-jackson** [comment]
> Start drafting your first post! Need some inspiration? Check out our [library of writing prompts](https://wordpress.com/dailypost/prompts/).

Linking to the writing prompts is cool 😎 We don't know whether the user getting this notification is a "blogger" or not, so writing a post might not be the first thing they want to do (or at all). But given it's one of a few options in this notification I think it's an improvement over directing users to the customiser.

**Comment by kwight** [comment]
> We don't know whether the user getting this notification is a "blogger" or not, so writing a post might not be the first thing they want to do (or at all).

Right – the nice thing about redirecting to My Home is that it will present whatever's appropriate.

**Comment by arthur791004** [comment]
I also think redirecting to My Home is great! @kristastevens Do we have a new copy for it?

**Comment by kristastevens** [comment]
How about we simply say: 

Get started!

^ Where both words are linked to My Home.

**Comment by arthur791004** [comment]
Awesome! I love the simple word!
![image](https://user-images.githubusercontent.com/13596067/131068433-8b27d5ad-7dc3-47d5-a759-3a7806f43de4.png)

**Comment by p-jackson** [comment]
Change deployed D66025-code
