### ISSUE TITLE
Unable to update products when Facebook for Woocommerce active

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#55366]
### Steps to Reproduce

1. Activate plugin and try to update product field (such as SKU id)
2. see that clicking update doesn't seem to do anything

### What I expected to happen

I should be able to update the product

### What actually happened

nothing except this network error shared below

### Context

4213140-zd-woothemes

### Operating System

macOS

### Browser

Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Console and/or error logs

`Request URL: https://antiqueblackthings.com/wp-admin/admin-ajax.php
Request Method: POST
Status Code: 400 
Remote Address: 127.0.0.1:8080
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-origin: https://antiqueblackthings.com
cache-control: no-cache, must-revalidate, max-age=0
content-type: text/html; charset=UTF-8
date: Wed, 11 Aug 2021 07:33:04 GMT
expires: Wed, 11 Jan 1986 06:00:00 GMT
host-header: WordPress.com
referrer-policy: strict-origin-when-cross-origin
server: nginx
strict-transport-security: max-age=31536000
x-ac: 3.lhr _atomic_ams
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-hacker: If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.
x-robots-tag: noindex
:authority: antiqueblackthings.com
:method: POST
:path: /wp-admin/admin-ajax.php
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 173
content-type: application/x-www-form-urlencoded; charset=UTF-8
cookie: wordpress_sec_ed430f1ff5500c744007f8bc604c0196=vintagedollsociety%7C1628669702%7CLhzlqDbSrPBuqursfraflc9kcwVQfGhikQ2fnT5SO7M%7Cc7a487f0da7aa73fc56688ce3505249ac45418b865cf0b0294997dabf647073b; mailchimp_landing_site=https%3A%2F%2Fantiqueblackthings.com%2Fwp-login.php%3Fredirect_to%3Dhttps%253A%252F%252Fantiqueblackthings.com%252Fwp-admin%252Fadmin.php%253Fpage%253Dsnippets%2526return%253Dhttps%25253A%25252F%25252Fwordpress.com%25252Fstats%25252Fday%25252Fantiqueblackthings.com%26reauth%3D1; wordpress_test_cookie=WP%20Cookie%20check; _wpcomsh_support_session_detected=true; wordpress_logged_in_ed430f1ff5500c744007f8bc604c0196=vintagedollsociety%7C1628669702%7CLhzlqDbSrPBuqursfraflc9kcwVQfGhikQ2fnT5SO7M%7C81b8b85b96dd6fcf86c825b29d55c066b76a9e11b48d2178cf530dbfc2d466a0; tk_ai=woo%3Ajj5ZDKv6dp6xn6b3H4C5g%2Bp6; wp-settings-190508319=imgsize%3Dfull%26libraryContent%3Dbrowse%26mfold%3Do%26unfold%3D1%26editor%3Dtinymce; wp-settings-time-190508319=1628666102; woocommerce_items_in_cart=1; wp_woocommerce_session_ed430f1ff5500c744007f8bc604c0196=190508319%7C%7C1628838923%7C%7C1628835323%7C%7C745f6c897dd1353aa8949549566d2697; woocommerce_cart_hash=b9c2b6dbf969b811077ed635f0063a2b; tk_qs=
dnt: 1
origin: https://antiqueblackthings.com
referer: https://antiqueblackthings.com/wp-admin/post.php?post=3900&action=edit
sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
x-requested-with: XMLHttpRequest
action: facebook_for_woocommerce_set_product_sync_prompt
security: 83af6f0af5
sync_enabled: enabled
var_sync_enabled: enabled
product: 3900
categories[]: 703866241
tags[]: `

they also have these two notices showing:
`Notice: is_page was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /wordpress/core/5.8/wp-includes/functions.php on line 5535

Notice: is_singular was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /wordpress/core/5.8/wp-includes/functions.php on line 5535`

### Reproducibility

Consistent

**Comment by formosattic** [comment]
Thanks for the report @Nic-Sevic. 

Based on the latest of the ticket, it sounds like the issue might be specific to the user's setup. 

I'm closing this for now. Please feel free to re-open if you have further findings to add.
