### ISSUE TITLE
Editor: Success message placement when featured image is present 

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#5537]
Successful post without featured image:

![screen shot 2016-05-23 at 3 03 00 pm](https://cloud.githubusercontent.com/assets/5835847/15484510/9edd9872-20f7-11e6-9cae-0d8a0eba85d1.png)

Successful post with featured image:

![screen shot 2016-05-23 at 3 03 51 pm](https://cloud.githubusercontent.com/assets/5835847/15484511/9ee158ea-20f7-11e6-9a34-b99ae352d23b.png)

I think the success message should remain at the top regardless of the presence of a featured image. @mtias @folletto what do you think?

**Comment by folletto** [comment]
> I think the success message should remain at the top regardless of the presence of a featured image.

Agreed. :)

**Comment by jeremeylduvall** [comment]
Fixed in #5630.
