### ISSUE TITLE
Have a way from the WordPress.com Dashboard (Calypso) to access the WP Admin Menus editor

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#55388]
### What

There's not a way to access a "Screen Options" dropdown to select the option to access the WP Admin version for menus when going to "My Site" > Appearance > Customize > Menus

### Why

Users with a lot of menu items find it easier to edit from the WP Admin screen

### How

Not sure how 😆  Could the "My Site" > Appearance > Customize > Menus option lead to the WP Admin screen same as the "My Site" > Appearance > Customize > Widgets option?

**Comment by JoshuaGoode** [comment]
This is _**essential**_  for WordPress.com on Atomic sites using third-party themes and plugins. 

If we keep this new behavior, there absolutely needs to be an option to toggle this off or have a workaround for WoA sites that need to use the WP core behavior.

#### Why?
WoA users going to Appearance > Menus and Appearance > Widgets have historically been taken to the proper WP-Admin page and not the Customizer.

Those pages are essential for numerous popular third-party plugins and themes. In some cases, the options are not available in the Customizer.

---

#### Example

Users are having to manually go to the following links.  This needs a toggle or option similar to the Screen Options we have now.

• wp-admin/nav-menus.php
• wp-admin/widgets.php

For example, many sites using a plugin like `megamenu` will have to manually access wp-admin/nav-menus.php.

--

Related internal discussion:

p1631178748139800-slack-C7YPUHBB2

cc: @simison

**Comment by jordesign** [comment]
Just had a chat with a user in 31584826-hc with a BIG +1 on bringing this back.

**Comment by JoshuaGoode** [comment]
Encountered on 31580417-hc

**Comment by tellisbethel** [comment]
Chatted with a user who (understandably) insists upon having direct access to the editor restored: 28743236-hc

The user finds having to use the Customizer to access their menus  "slow and cumbersome".

**Comment by JoshuaGoode** [comment]
What was the purpose of this change on WoA? Outside of parity with Simple.

It'd nice to revert back to core functionality, how it has been, or offer an option to disable this redirection.

cc: @simison @mmtr

**Comment by JoshuaGoode** [comment]
An HE reached out to Atomic help for help about this, directed user to use direct link as a workaround.

* p1631273903240600-slack-C03TY6J1A
* 28743236-hc

**Comment by JoshuaGoode** [comment]
Another HE reached out just now.

* p1631308306024800-slack-C03TY6J1A
* 31602836-hc

**Comment by JoshuaGoode** [comment]
Additional HE and user requests for help about this change:

* p1631035868379500-slack-C03TY6J1A
* p1631036752187000-slack-C3GP81E05

**Comment by hngdny** [comment]
Another request here: 4289411-zen

**Comment by Greatdane** [comment]
Another user had a custom theme and was unable to access WP Admin Menus editor. I had to give them the direct link. I think it may be related to this as well; 
4284538-zd-woothemes
31570676-hc

**Comment by Greatdane** [comment]
Another user with a big BRING BACK request; 
31602836-hc
4289345-zd-woothemes

**Comment by arunsathiya** [comment]
Requested on 31607625-hc too.

**Comment by marianearchimbaud** [comment]
Reported here too:
31297135-hc

**Comment by villanovachile** [comment]
Another request here, but for the Widgets area  (same issue): 20839154-hc

**Comment by marcuswisecaesar** [comment]
Reported here too: 31617193-hc

**Comment by ash1eygrace** [comment]
31617483-hc 

The third-party theme's top text widget is not responsive in the customizer. 
Gave them the direct URL to wp-admin/widgets.php

**Comment by AtrumGeost** [comment]
Got a report here: 30934087-hc

The user was using a third-party theme that wouldn't allow editing menus via the Customizer. Sent them the direct WP Admin link

**Comment by mmtr** [comment]
> What was the purpose of this change on WoA? Outside of parity with Simple.

The context behind these changes was to be aligned as well with the "Appearance > Widgets" menu, where we link to the Customizer since we want to avoid WP.com customers from seeing multiple interfaces. See p1628152719014300/1628119959.008100-slack-C021Z8P3RMG. I'll let @simison expand on why we prefer the Customizer over the Core default screen, but I guess it's because it's less overwhelming for new users.

Said that, we can diverge the behavior here, and keep "Appearance > Widgets" linking to the Customizer and "Appearance > Menus" to the default Core screen.

**Comment by Poliuk** [comment]
Reported here too: 4282420-zd-woothemes

**Comment by kerrynicl** [comment]
Another report - HC-31649578

**Comment by metabreakr** [comment]
4293974-zen

**Comment by inaikem** [comment]
18097743-hc

> ...now WordPress.com has updated to a new Menu creation/editing screen and the old is completely gone. All of the functionality that I relied upon is now completely gone as well. Why would the team get rid of a screen completely. I'd like access to the legacy menu building screen.

**Comment by goblinartificer** [comment]
31654583-hc

**Comment by daria2303** [comment]
Another report: 4297157-zd-woothemes

**Comment by dpasque** [comment]
Just did a ping to Simple/Atomic folks to find right group to address this.

**Comment by pablinos** [comment]
> Could the "My Site" > Appearance > Customize > Menus option lead to the WP Admin screen same as the "My Site" > Appearance > Customize > Widgets option?

Looking at Automattic/jetpack#20587 this should already be the case for menus. @mmtr Is that right, or do you have any suggestions here?

**Comment by thelogicwizards** [comment]
HC-31158908

**Comment by JoshuaGoode** [comment]
> Could the "My Site" > Appearance > Customize > Menus option lead to the WP Admin screen same as the "My Site" > Appearance > Customize > Widgets option?

I think we can skip that and just return default core behavior and have Appearance > Widgets and Appearance > Menus go to their respective WP-Admin pages.  That's all we're looking for, core behavior -- at least on WoA.

**Comment by pablinos** [comment]
Yeah that makes sense @JoshuaGoode, but as as I can see that's the intended behaviour. Maybe it's only working on Simple sites?

**Comment by jackiejade** [comment]
User wanted to be able to edit the description of their menu and descriptions on widgets. They needed the WP Admin screens. HC-31433328

**Comment by JoshuaGoode** [comment]
> Yeah that makes sense @JoshuaGoode, but as as I can see that's the intended behaviour. Maybe it's only working on Simple sites?

In prep for block widgets, Nav Unification was updated to redirect `Appearance > Widgets` and `Appearance > Menus` to the Customizer instead of the standalone WP-Admin pages for those options.  Internal discussion about that here: p1628119959008100-slack-C021Z8P3RMG

This new redirection behavior came to WordPress.com on Atomic sites via Jetpack: https://github.com/Automattic/jetpack/pull/20587 

The part that ensures the Customizer is the WP-Admin version is fine.  The part where we redirect `Appearance > Widgets` and `Appearance > Menus` to the Customizer is not.

#### Issue
The core behavior is for `Appearance > Widgets` to go to `wp-admin/widgets.php` and `Appearance > Menus` to `wp-admin/nav-menus.php` -- the standalone WP-Admin pages -- and _**not the Customizer**_. 

With these changes, there is no way for a user to access `wp-admin/widgets.php` or `wp-admin/nav-menus.php` without entering the link directly or following a bookmark. 

There are popular plugins and themes that require the use of the dedicated WP-Admin pages and not the Customizer.  In some cases, menus and widgets can also be easier to manage in the dedicated WP-Admin pages as well. 

While likely okay for Simple, it is not appropriate for WordPress.com on Atomic sites.  Not without a toggle or links to turn this redirection off.   Some of the reports here have also been for Simple users that prefer the WP-Admin interfaces.

**Comment by pablinos** [comment]
Right, I saw Automattic/jetpack#20587 and thought that was the desired behaviour. It sounds like we should revert the redirection part? I'll discuss it with @mmtr as I think he'll have some more context.

**Comment by mmtr** [comment]
To expand a little bit:

- As a way of aligning Simple with Atomic (while also dealing with the lack of a Screen Options button in the Customizer: https://github.com/Automattic/wp-calypso/issues/55231), the Simple/Atomic pod changed the “Appearance > Menus” and “Appearance > Widgets” menus to link to `wp-admin/nav-menus.php` and `wp-admin/widgets.php` respectively (D65216-code).
- However, @simison confirmed that “Appearance > Widgets” should link to the Customizer as part of the block widgets launch (p1628193314037400/1628119959.008100-slack-C021Z8P3RMG), so @fullofcaffeine implemented that change (D65237-code)
- @chad1008 then asked if we should do the same for “Appearance > Menus” (p1628530897093900-slack-CJS75TX3R), which made sense in order to avoid different behaviors in the menu, so I implemented that change (D65308-code).
- All these changes were synced to the Jetpack codebase in https://github.com/Automattic/jetpack/pull/20587.

I'm fine having the original behavior back, but given that the divergent behavior was a need for the block widgets, I think we need to loop @Automattic/team-calypso in and make sure these changes won't affect their work on the block widgets.

**Comment by chad1008** [comment]
I'll defer to @fullofcaffeine for confirmation, but I don't _think_ reverting these redirects would disrupt things with block widgets. IIRC, before we updated the redirect, block widgets were testing fine in wp-admin.

**Comment by zdenys** [comment]
Another case here: 31247611-hc

**Comment by masperber** [comment]
+1 31696571-hc

**Comment by mikeicode** [comment]
31280712-hc

**Comment by jp-imagines** [comment]
Another request in 31646094-hc

**Comment by tellisbethel** [comment]
Provided direct URL workaround for user to access wp-admin menus page in this chat: 30428802-hc

**Comment by jartes** [comment]
Another one on 31722663-hc

Provided WP-Admin url as a workaround.

**Comment by susanjanec** [comment]
Another request in 31552378-hc

Provided WP-Admin URL as a workaround.

**Comment by CodeAllNightNDay** [comment]
Another request 30999193-hc

Gave WP-Admin URL workaround

**Comment by ash1eygrace** [comment]
31085062-hc 

The third-party theme can't add widgets via the customizer. Provided the direct wp-admin links.

**Comment by kingsleyinfo** [comment]
Another request here 31612053-HC
They were really not happy. Provided them with the direct links

**Comment by TeniCola** [comment]
Another request in 4312391-zen. In the previous livechat with them, they were also insistent on reaching this area for their website and theme, so I'll provide the URL workaround in the follow-up.

**Comment by TeniCola** [comment]
Another request in 31672170-hc, though this was for the Appearance > Widgets area + Classic Widgets plugin -- I provided the workaround URL

**Comment by ccwalburn** [comment]
Another request here: 4321116-zen

They need the WP Admin screen because these two plugins have options that are not accessible from the Customizer:

Menu Icons By ThemeIsle
User Menus By Code Atlantic

**Comment by ash1eygrace** [comment]
Another third-party theme where the customizer won't work: 31837606-hc 

Provided them the direct link as a workaround.

**Comment by metabreakr** [comment]
4321810-zen

**Comment by zdenys** [comment]
5346744-hc

**Comment by Gustavo-Hilario** [comment]
30856017-hc

**Comment by gmovr** [comment]
Also relevant for users using Polylang and WPML (to localize menus).

**Comment by katiebethbrown** [comment]
Another request in 31711363-hc

```
I want to be able to access the Menus the old way, compared to going to Theme Customizing window

Previously, it used to take me to a menus page where I could edit and add mega menu content if I need to

Now its going to the theme customizing window
```

**Comment by inaikem** [comment]
Another request here: 31864223-hc.

I provided a direct link to the menu page at `domain.com/wp-admin/nav-menus.php`.

**Comment by inaikem** [comment]
Another request here: 31875584-hc.

I provided a direct link to the menu page at domain.com/wp-admin/nav-menus.php.

**Comment by Greatdane** [comment]
Another request here; 4326645-zd-woothemes

**Comment by Greatdane** [comment]
Another confused user and request for menu; 4330968-zd-woothemes

**Comment by sanjeev00733** [comment]
Another user in 28613639-hc is not happy about using a direct link for the menu. They shared the feedback:

> it's a really inconvenient solution, there are multiple people who have to work with this and now I have to explain to everyone of theme this workaround.

**Comment by tellisbethel** [comment]
Another request here: 31955316-hc
Provided direct link workaround: [DOMAIN]/wp-admin/nav-menus.php

**Comment by Greatdane** [comment]
another request; 31969722-hc

Suggested user bookmark the direct link for now.

**Comment by yashitamittal11** [comment]
Another request here- #31899169-hc
Suggested user bookmark the direct link.

**Comment by inaikem** [comment]
Another request: 4345053-zen

@dpasque, could we get eyes on this when you have a moment? We have close to 50 interactions noted here, plus over 10 noted on these two issues:

- https://github.com/Automattic/wp-calypso/issues/49830
- https://github.com/Automattic/wp-calypso/issues/55553

**Comment by dpasque** [comment]
Pinged in Slack to start getting some eyes on this: p1633361587184500-slack-C01VDMPHG69

**Comment by jp-imagines** [comment]
Another request in 32027687-hc, gave user the direct link.

**Comment by pablinos** [comment]
I've just been trying to absorb all the context on this and work out the fix. The issues I can see with reverting it are:

- It was partly done to unblock (sorry for the pun) block widgets https://github.com/Automattic/jetpack/pull/20587#issuecomment-899396532 but as far as I can tell this isn't an issue anymore. Could someone confirm that? @fullofcaffeine, or @Automattic/team-calypso more generally.
- I'm not sure of the other implications with reverting it. It sounds like (although perhaps not optimal) the reason is to make sure there is still access (via the navigation) to the Customizer version and the `wp-admin` screen. Is that preferable to defaulting to the Customizer? I'm not sure how much contact we were receiving because of confusion caused by the two screens.
- We won't be introducing a toggle as this isn't an option in the Customizer interface, and as much as possible we want to unify the experience rather than provide workarounds. There are examples of people with Simple and Atomic sites wanting to access the `wp-admin` version. If we are going to revert this, should we do it for both environments or just Atomic. @simison might be the best person to answer this - can you help please?

**Comment by inaikem** [comment]
On your second bullet above:

> Is that preferable to defaulting to the Customizer? I'm not sure how much contact we were receiving because of confusion caused by the two screens.

A lot of the contact/confusion in user interactions falls into 2 camps from my perspective:

1. _"I've been using this for years and it suddenly changed without warning"_ - simple UI shock from being used to the `wp-admin` screen and it "disappearing". These may be self-hosted folks who've some over to WPcom, or equally people who are simply used to and prefer the "Classic" WP view. In any case, we should still serve their needs!
2.  _"I cannot edit my menu"_ - Using the `wp-admin` screen to make edits is a requirement for many standalone menu plugins  and themes/theme-specific menu-plugins. The Customizer cannot be used to edit the menu.

Hope that adds some of the context you were looking for here! 🙏

Cc @JoshuaGoode and @jmdodd for any additional related input.

**Comment by pablinos** [comment]
Thanks @inaikem, that is helpful context. I think it's clear that many people would be happy if this was changed back. What I'm finding hard to understand is what problem it fixed.

If it was just part of unifying the experience which has accidentally caused some problems, then it's fine to revert. But if it was to fix another pain point then we'll just be reintroducing that. It's not clear if that's the case and which is the preferred behaviour.

We're also talking about perhaps reverting it for Atomic but not simple sites, and the same applies. Will this introduce any other issue?

**Comment by inaikem** [comment]
I'll leave @simison and others to speak to the underlying reasons for this implementation and any negative/breaking implications of mirroring core WP.

To add my 2¢: if there's no technical reason _not to_ enable direct access to `wp-admin/nav-menus.php` and `wp-admin/widgets.php` via the `Appearance` menu, then we should just do it.

Even more context to support that can be found in this comment: https://github.com/Automattic/wp-calypso/issues/49830#issuecomment-919198531.

**Comment by chad1008** [comment]
> If it was just part of unifying the experience which has accidentally caused some problems, then it's fine to revert. But if it was to fix another pain point then we'll just be reintroducing that. It's not clear if that's the case and which is the preferred behaviour.

To the best of my knowledge this was more about unification and presenting a single UI whenever possible than addressing a specific pain point. When we released block widgets, @simison shared that our goal was a single UI (in that case, Customizer) where possible. Shortly after that I noticed that Menus still had a split experience and asked if that should follow the same single-UI pattern (p1628530897093900-slack-CJS75TX3R).

Based on that, I'd personally vote to revert this for menus, and restore the wp-admin interface, at the very least for Atomic... but I'd prefer to see the two platforms remain in sync so I'd say restore it for both.

A single UI when one offers little or minimal advantage over the other makes sense. In a case like Menus where a single UI is actively hurting the user experience for what appears to be a decent number of site owners, it feels less valuable to me.

**Comment by vinnykaur** [comment]
One more hc-32053674
Gave direct link to the user.

**Comment by inaikem** [comment]
@chad1008, thank you. On this:

> Based on that, I'd personally vote to revert this for menus, and restore the wp-admin interface, at the very least for Atomic... but I'd prefer to see the two platforms remain in sync so I'd say restore it for both.

> A single UI when one offers little or minimal advantage over the other makes sense. In a case like Menus where a single UI is actively hurting the user experience for what appears to be a decent number of site owners, it feels less valuable to me.

What's the best way to progress this?

**Comment by chad1008** [comment]
If that's the route we decide to go, it looks like it would be a matter of reverting:
- the change on wpcom: (D65308-code)
- the matching change to sync to Jetpack: https://github.com/Automattic/jetpack/pull/20587

I'll defer to other more seasoned devs on a final decision and confirming that this is the right approach.

**Comment by JoshuaGoode** [comment]
Thanks for the continued discussion, ya'll.

Many would really like the widgets stuff reverted as well.  

It should no longer impact Block Widgets and, if anything, the WP-Admin version gives the user a more accessible interface to view and edit block widgets.

Some plugins and themes rely on the dedicated WP-Admin widgets area just as they rely on the WP-Admin menus.

I'll defer to my previous comments on this for now but I'm happy to help clear things up.

Related:
* p1631649743199700-slack-C7YPUHBB2
* p1631178748139800-slack-C7YPUHBB2
* https://github.com/Automattic/wp-calypso/issues/55388#issuecomment-916327106
* https://github.com/Automattic/wp-calypso/issues/55553

**Comment by fullofcaffeine** [comment]
It looks like the best way to go would be to revert to the previous links for `Appearance->Widgets` and `Appearance->Menus`. I don't feel comfortable making the final call to go ahead with this, though, so I'll defer to @simison on the decision.

Also, If we decide to revert to the WP-Admin version of the widgets' screen for simple sites too, we'll need to update this E2E test: https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-playwright/wp-widgets__spec.ts.

**Comment by yashitamittal11** [comment]
Another one - #32108963-hc
Shared direct link to menu page

**Comment by kdevnel** [comment]
Another request - #4363153-zd-woothemes
Shared link
Context: WPML requires the interface for some of it's translation features and syncing menus across languages. This isn't available in the Customizer.

**Comment by zdenys** [comment]
31485070-hc

**Comment by JoshuaGoode** [comment]
32114484-hc,  WoodMart theme requires access to the WP-Admin version.

**Comment by mxhassani** [comment]
32161981-hc

**Comment by erricgunawan** [comment]
4319693-zen 
Gave direct link to the user.

**Comment by DustyReagan** [comment]
Hi @fullofcaffeine! 👋

> Also, If we decide to revert to the WP-Admin version of the widgets' screen for simple sites too, we'll need to update this E2E test: https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-playwright/wp-widgets__spec.ts.

I’m looking at these E2E tests for the first time and wondering what will break when we change the "Widgets" and "Menus" links. I noticed at the top of [the test file](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-playwright/wp-widgets__spec.ts) `@group calypso-pr` was removed, but `@group gutenberg` remains. Do you know if this test fails will it break any builds?

Ultimately, I’m wondering if we should have a fix for this test ready to go before shipping any changes?

**Comment by mikeicode** [comment]
Request for the classic menu location 31618262-hc

**Comment by mikeicode** [comment]
Request for the classic menu location 32234013-hc

**Comment by jartes** [comment]
Another one on: 30657990-hc

They needed the wp-admin version as was necessary to manage the locations from the https://wordpress.org/plugins/conditional-menus/ plugin

**Comment by DustyReagan** [comment]
The update for this issue is now live! “**Appearance > Widgets**” and “**Appearance > Menus**” masterbar links now link back to classic “widgets.php” and “nav-menus.php” destinations for Simple and Atomic sites!

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/bug-herders have finished following up with affected users reported in this thread.

Thanks for all the reports!
