### ISSUE TITLE
Subscriptions: Test Atomic upgrades.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#55384]
Let's verify that all is well with subscriptions when a Simple user upgrades their account and ends up on Atomic.

* Are all subscriptions carried over?
* Do users have clear access to management tools?
* Do new (Atomic) posts get to subscribers as expected?
* Anything else we can think of!

**Comment by kwight** [comment]
I think we're good here! 🎉

I created a Simple site, then subscribed three users by email only and two WP.com test users that I have. After upgrading to Premium and activating a newly-uploaded theme, I published a new post. All of the expected users received it, and the Users section in Calypso still listed all of the correct subscribers. I then remove some followers, and published another post – only the remaining subscribers got the post. All good enough to close this task.

The one thing I'm confused about is that at the start, my Simple site didn't have a Follow button in the Action Bar – so I'm unclear what happens to it once upgraded to Atomic. I'm wondering if there's more for us to do here: if a user on Simple sees that their site has an easy Follow button (in the Action Bar), they might not be aware that once they upgrade, they now have to add something themselves (which is certainly less than optimal).

@inaikem @saygunnyc As far as either of you know, is there any subscribe prompt automatically present on an Atomic site after transfer?

**Comment by saygunnyc** [comment]
> The one thing I'm confused about is that at the start, my Simple site didn't have a Follow button in the Action Bar 

Do you know how this might have happened? I thought it would be there by default on Simple Sites. Is there maybe a setting somewhere else that switches it on and off?

> As far as either of you know, is there any subscribe prompt automatically present on an Atomic site after transfer?

I don't think we have anything like that, but I am not sure. @inaikem would know better. However +1 to that. Assuming I am a blog owner who relies on the action bar for following actions on my site _– also worth exploring this and figuring out how many users out there relying on it_, it would be really annoying to lose that functionality without any notice. IMO this is another good reason for parity seemingly leaning towards also having an action bar over atomic sites as well. However, with each day spent with subscriptions experience, I am leaning towards removing it or at least giving the decision to both Atomic and Simple site owners to have it or not, similar to how blocks and widgets work.

**Comment by inaikem** [comment]
> As far as either of you know, is there any subscribe prompt automatically present on an Atomic site after transfer?

To the best of my knowledge, there is nothing resembling the Action Bar or an automatic platform-level subscribe prompt after a site goes Atomic.

The only persistent cross-plan subscription method I can think of right now is a [Subscription Form block](https://wordpress.com/support/wordpress-editor/blocks/subscription-form-block/) added via Block Widgets to a site's sidebar/footer area. This would remain unchanged regardless of if the site was Simple or Atomic.

JP subscriptions are Atomic-specific IIRC and the Follow Blog widget does not work on Atomic sites.
&nbsp;

> However, with each day spent with subscriptions experience, I am leaning towards removing it or at least giving the decision to both Atomic and Simple site owners to have it or not, similar to how blocks and widgets work.

On a related note, I'd like to know what volume of follows the Action Bar generates each day as it'll help support the above.

Personally, I'm more for providing Atomic and Simple site owners the _option_ of having the Action Bar as opposed to removing it across the board.

It's worth remembering that if we removed the Action Bar, we'd lose the easiest, most obvious and lowest friction method for WordPress.com users to subscribe to blogs - this assumes that Reader is used more for consumption and curation as opposed to discovery.

So many assumptions that need testing!

**Comment by saygunnyc** [comment]
> On a related note, I'd like to know what volume of follows the Action Bar generates each day as it'll help support the above.

This would be a great start! Is there a way to track this?


> Personally, I'm more for providing Atomic and Simple site owners the _option_ of having the Action Bar as opposed to removing it across the board.

This would be a great action number 02, **not forcing the action bar, esp. to new users**, and give them the opportunity to shape their sites however they want, and then the existing users can have the option to remove it or choose to use it consciously given they already have other widgets and blocks as well to pick from.

> It's worth remembering that if we removed the Action Bar, we'd lose the easiest, most obvious, and lowest friction method for WordPress.com users to subscribe to blogs - this assumes that Reader is used more for consumption and curation as opposed to discovery.

Removing is never easy, esp. with the volume of users we have over WordPress.com, however, I also believe we should challenge the existing status of things. Sometimes it can be worth taking the risks and think about how to change course towards something greater. Note that we already are including the subscription block to a lot of blogger templates today. And re-thinking about the action bar, I feel stronger in my opinion that we should never force a UI element into a user's site and respect their choices if they don't want an action bar with the goal of democratizing the experience, despite we won't be tackling on this today.

**Comment by inaikem** [comment]
I've asked both Flow Patrol pods to see if they're able to join the discussion here: p1629711376015500-slack-C029WGXE5T4.
