### ISSUE TITLE
Customizer: Cannot add a Tag menu item if there's already a Category with the same name

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#55385]
### Steps to Reproduce

1. Create a tag and category with the same name, for instance `WordPress`.
2. Got to "My Site" > Appearance > Customize > Menus > Primary
3. Try adding the `WordPress` **tag** to the menu
4. Notice the WordPress category item is added instead

![Screen Capture on 2021-08-11 at 11-42-22](https://user-images.githubusercontent.com/3696121/129069379-9622f43b-89b8-42da-a34c-5315b3a1f9fb.gif)

### What I expected to happen

For the respective tag to be added

### What actually happened

A category was added to the menu, instead of a tag

### Context

User report: 23746224-hc

### Operating System

macOS

### OS Version

Big Sur 11.5.1 (20G80)

### Browser

Chrome/Chromium

### Browser Version(s)

Version 92.0.4515.131 (Official Build) (x86_64)

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple, Atomic or both?

Simple

### Number of Users Impacted

All users

### Available Workarounds

Add a Custom Link that leads to the Tag page

### Reproducibility

Consistent

**Comment by synora** [comment]
Triaged. Able to replicate on Simple sites. Works as expected on Atomic.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
Both category and tag taxanomy has the same id. The only way to further distinguish them is by the object type through the `object` property.
![image](https://user-images.githubusercontent.com/1287077/133395789-cffb70ad-7d86-4d89-b43c-2fc17713858f.png)

The script `wp-admin/js/customize-nav-menus.js` and `wp-includes/class-wp-customize-nav-menus.php` needs to more granularly handle id and object type like composite keys.

The codebase is in `wordpress-develop`.
Not working phab fix is D66879-code. (findWhere keys to `id` very strongly, need to use other means of identification).

**Comment by ahmadbaig1** [comment]
Another one reported here- 4291729-zen
Advised the user to use custom links for the tag pages for now.

**Comment by yansern** [comment]
~Update: Phab patch is now ready. D66879-code~ 
Superceded by D67452-code

![image](https://user-images.githubusercontent.com/1287077/134674782-58af0e87-94ec-419b-b76b-523487b39d34.png)

**Comment by yansern** [comment]
Phab patch superceded by D67467-code. (Difference is instead of touching WP core on the JS end, we make IDs unique through a filter on WPCOM on the PHP end).

**Comment by yansern** [comment]
Deployed!
