### ISSUE TITLE
Activity Log - Theme link destinations are not consistent theme-to-theme

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#55383]
**To Reproduce**

Change a theme on your site. Do it a few times with a few different ones.
Go to My Site > Jetpack > Activity Log
Scroll down to see theme changes in the log
Browse over a theme name, and check the link destination in the browser status bar, or click the link.

**Expected behavior**
As a user, I would expect to click on a Theme name in Activity Log and to be presented with the Theme info page in calypso, so I can learn about the theme/ activate it.

**Actual behavior**
For some themes this doesn't happen, for example, with Maywood - It takes you to the theme GH page: https://github.com/Automattic/themes/tree/master/maywood
It feels like taking users to the theme's GH repo aggregates nothing in the Dotcom context.

here is some testing I did:
For Maywood: https://github.com/Automattic/themes/tree/master/maywood
For Twenty Twenty: https://wordpress.org/themes/twentytwenty/
For Spearhead: https://wordpress.com/theme/spearhead/
For Seedlet: https://wordpress.com/theme/seedlet/
For Radcliffe 2: https://wordpress.com/theme/radcliffe-2/littlevillagewoodpieces.wordpress.com

Is there a way to make the path consistent to https://wordpress.com/theme/SLUG?

originally logged by @davipontesblog 

https://user-images.githubusercontent.com/31009008/98155960-1c68cf00-1ea5-11eb-9579-dfa39ea94ee5.png
![image](https://user-images.githubusercontent.com/16654218/98278398-87c6a580-1f66-11eb-86e6-28fb646c7f85.png)

**Comment by kwight** [comment]
> would this be better placed in wp-calypso repo?

I'd say so, for visibility if nothing else. I could see the problem being in a variety of places, but Calypso would be best for managing the issue.

**Comment by synora** [comment]
Triaged. Can replicate.

**Comment by AtrumGeost** [comment]
+1 to this. I noticed this when helping a user check recent theme changes.

**Comment by markbiek** [comment]
It's worth nothing that the theme url we link to is the `theme_uri` field as returned from the `/themes` API call.

The value of that field comes from the `style.css` file of the theme itself.

For example, if we look at the **Archeo** theme in the API, we see that the theme uri is https://github.com/Automattic/themes/tree/trunk/archeo.
![image](https://user-images.githubusercontent.com/917632/161550298-8aad15cd-a62f-4fcd-8e38-ced620fda123.png)

[Looking at the `style.css` file for the theme](https://github.com/Automattic/themes/blob/trunk/archeo/style.css#L3), we see that the "Theme URI" field there is the same.

@blackjackkent I'm not sure the best way to handle this. The choices seem to be updating all the "Theme URI"s or tweaking the activity log to treat theme stuff as a special case so we can link to the theme on WordPress.com.

**Comment by blackjackkent** [comment]
@markbiek I'm inclined to say fiddling with all the theme data itself is probably not the best plan. How complicated is the second option, to tweak the logic of the activity log itself? That seems like a better bet if we can swing it.

**Comment by markbiek** [comment]
@blackjackkent All of the activity log components are pretty generic so I don't think adding extra logic in there is the way to go.

_However_, if you trace things all the way down, those theme links in the text "Switched Whatever to Whatever" are ultimately rendered by the [Theme formatted-block](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/notes-formatted-block/blocks.jsx#L112).

It seems like we should be able to change [this line](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/notes-formatted-block/blocks.jsx#L137) from 

```
href={ themeUri}`
```

to

```
href={ `/theme/${ themeSlug }` }
```

Though I'll need to double check that this isn't used for non wpcom themes.

**Comment by markbiek** [comment]
Double-checked and the only place the `FormattedBlock` component is being used is in the activity log. So I think it's safe to make the change I outlined above.

**Comment by markbiek** [comment]
@sixhours When you start tackling this one, could I shadow you? I'm curious about the process for rolling out theme changes (unless it's as simple as just merging PRs to https://github.com/Automattic/themes).

**Comment by markbiek** [comment]
Here's a list of the themes in the theme repo that have github.com urls for the `Theme URI`.

Please check off themes as they get updated:

- [x] alves
- [ ] ~appleton~ (Not visibile in the theme showcase)
- [x] arbutus
- [x] archeo
- [x] balasana
- [x] barnsbury
- [x] blank-canvas-blocks
- [x] blockbase
- [x] brompton
- [x] calm-business
- [x] coutoire
- [x] dalston
- [x] elegant-business
- [x] exford
- [x] friendly-business
- [x] geologist
- [x] geologist-blue
- [x] geologist-cream
- [x] geologist-slate
- [x] geologist-yellow
- [x] hever
- [ ] ~ibis~ (Not visibile in the theme showcase)
- [x] leven
- [x] livro
- [x] mayland
- [x] mayland-blocks
- [x] maywood
- [x] modern-business
- [x] morden
- [x] pendant
- [x] professional-business
- [x] quadrat
- [x] quadrat-black
- [x] quadrat-green
- [x] quadrat-red
- [x] quadrat-white
- [x] quadrat-yellow
- [x] redhill
- [x] remote
- [x] rivington
- [x] rockfield
- [x] russell
- [x] seedlet-blocks
- [x] shawburn
- [x] skatepark
- [x] sophisticated-business
- [x] stewart
- [x] stow
- [x] stratford
- [x] twentytwentytwo-blue
- [x] twentytwentytwo-mint
- [x] twentytwentytwo-pink
- [x] twentytwentytwo-red
- [x] twentytwentytwo-swiss
- [x] varia
- [x] videomaker
- [x] videomaker-white
- [x] zoologist
