### ISSUE TITLE
Subscriptions - Document behavior/structure of subscribe.wordpress.com code and calypso subscription management

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#55394]
We are putting together a number of P2 posts documenting the code structure of various features relating to subscriptions in Calypso and elsewhere, as part of the subscriptions pod's discovery phase.

**Comment by blackjackkent** [comment]
@andres-blanco has already put together an initial post regarding WPCOM's Reader tool for managing followers - dgv5Y-p2?p=194

We are still working on documentation for the action bar code (Andy) and subscribe.wordpress.com (me); for me at least this will probably bleed into 20% time to finalize the writeup, as the code is very long and somewhat convoluted.

**Comment by kwight** [comment]
Reader: pdgv5Y-38-p2
subscribe.wordpress.com: pdgv5Y-7F-p2
