### ISSUE TITLE
Themes: non-standard screenshot sizes break the layout in /design

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#554]
Although most themes use a standard screenshot size (300x225px), others use custom sizes that can break the layout in `/design`:

![screen shot 2015-11-23 at 8 38 16 pm](https://cloud.githubusercontent.com/assets/426388/11347528/26daf676-9222-11e5-8725-e5142f82e52d.png)

In the example above, Hybrid News uses a custom size, 300x435px. 

It would be nice if we could restrict the screenshot height to avoid such issues.

Reported here:
http://wptavern.com/automattic-unveils-calypso-an-open-source-wordpress-desktop-application-for-the-mac

**Comment by lancewillett** [comment]
I can't repeat this one now — Hybrid News seems to be retired or gone.

This should also be enforced on the Theme Showcase editing side — incoming theme edits in theme.wordpress.com by the Automattic theme team, there are checks there for screenshot size that might be failing (needs reminder to all 3rd party premium theme authors, maybe). CC @sixhours

**Comment by jeherve** [comment]
The problem still exists; you'll need to install Hybrid News on your self-hosted WordPress site first:

![screen shot 2016-04-15 at 11 29 33 am](https://cloud.githubusercontent.com/assets/426388/14557403/775b3718-02fd-11e6-9ded-30feae4c0361.png)

**Comment by lancewillett** [comment]
Oh? @jeherve Should WP.com theme directory list non-WP.com themes? I didn't think so.

**Comment by jeherve** [comment]
I'm sorry, I should have mentioned in the original post: that's when looking at `/design` for a Jetpack site, where you've installed your own themes.

**Comment by lancewillett** [comment]
Gotcha — that part is clear now, but I'm wondering if we *still* just filter those out since they aren't themes we review and recommend (only from the Calypso view — not wp-admin/themes.php on their side).

**Comment by folletto** [comment]
Fixed in #11229.
