### ISSUE TITLE
SEO Settings: front page excerpt overrides SEO meta description

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#5540]
It appears that if you add a page excerpt on a page that is set as the front page, then that excerpt will override the meta description setting on the SEO tab.

The SEO tab setting should override it.

**Comment by roundhill** [comment]
Fixed over on the WP.com side.

**Comment by chrisfromthelc** [comment]
I'm re-opening this issue to address a practical problem with the way the Front Page Meta Box works.

In a site with a static front page, and a blog, the Front Page Meta Description (FPMD) overrides both the static front page's meta description, as well as sets the blog page's meta description. In the case where a front page should have a unique meta description (which, is pretty much always), it's not possible to do so without introducing a duplicate content issue with the blog page.

The front _static_ page's meta description (or excerpt) should always override to give the ability to assign a unique meta description when using the Static Front Page option.

**Comment by chrisfromthelc** [comment]
Now that the Front Page Meta Description is locked behind the Business plan featurewall, this has become a greater issue.

If you had a description using the SEO Settings page (pre-featurewall), it's no longer accessible, and there's no way to change it. The excerpt is not able to override the meta.

**Comment by roundhill** [comment]
Fear not, for we have fixed this on the server side, but it isn't deployed yet. 

cc @vindl

**Comment by vindl** [comment]
After we deploy the fix, Front Page Meta Description will only be used on sites that have a business plan. One thing to note is that those users would still not be able to edit it until Advanced SEO feature flag is enabled in Calypso, but that should happen soon too.

**Comment by chrisfromthelc** [comment]
@vindl What about Premium users who changed the Front Page Meta Description previously, but now no longer have access to it? The fix will allow them to utilize the Excerpt instead, correct? We've had a few users asking about this.

**Comment by vindl** [comment]
@chrisfromthelc That's correct, Front Page Meta Description will not be used on their sites anymore, so it should fall back to the meta description value they had used previously (Excerpt if it is set).

**Comment by vindl** [comment]
This issue has been resolved by grandfathering of Front Page Meta Description that was shipped with Advanced SEO.
