### ISSUE TITLE
Remove install plugin prompt from woo

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#55418]
The extensions page suggests installing a plugin to manage automatic updating of themese, clicking this link results in a 404. 

In wpcom we don't need to add extra plugins to manage theme updates and in atomic we probably want to either auto install this on Atomic transfer or manage the updates ourselves in another way.

- [ ] Disable the nudge on wpcom
- [ ] Disable the nudge on atomic?

@cpapazoglou / @olaolusoga / @ianstewart I think we're going to need to make an early call on how tightly we want to integrate Woo on Atomic. Do we want woo extensions managed by the wpcom marketplace in the atomic context? Do we want woo marketplace themes managed by wpcom themes when on atomic? Same question will pop up for any other modifications we intend to make in the wpcom context.

Before:
![Screenshot 2021-08-12 at 15-38-31 WooCommerce extensions ‹ Woo on Plans Test Site — WordPress](https://user-images.githubusercontent.com/811776/129143825-5c790298-4fd0-441e-ac6a-8672c95d8737.png)

**Comment by cpapazoglou** [comment]
Here is a related atomic discussion p9o2xV-1A4-p2. My take is that since folks are buying a plugin from us and installing it on our infrastructure then it should be as a managed plugin. They should not worry whether to update it or not.

**Comment by lsl** [comment]
Agree, thanks for the link, good discussion there. For this ticket specifically we'll just hide the nudge.

**Comment by lsl** [comment]
D65585-code
