### ISSUE TITLE
Woocommerce sidebar navigation

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#55428]
We want to add a WooCommerce menu item for all plans.

The menu item should link to WooCommerce if it is installed. If it is not installed it should like to the /woocommerce-installation/ route in calypso for activation.

Place this menu item behind the `woop` config flag as the WooCommerce installer needs to be updated to handle non atomic sites.

There are three places in code that need updating:

- [x] Jetpack (for atomic/wp-admin) https://github.com/Automattic/jetpack/pull/21182
- [x] WPCom deploy of JP (for calypso) D67501-code
- [x] WPCom feature filter to enable it on woop sites D67636-code
- [x] Calypso fallback menu items https://github.com/Automattic/wp-calypso/pull/56488
- [x] ^ Fix required for p2 sites and similar: https://github.com/Automattic/wp-calypso/pull/56728
- [ ] Move wpcomsh woo menu item to Jetpack admin menu and remove wpcomsh implementation (or at least add a separator there to be consistent with woo core)

**Comment by ianstewart** [comment]
@olaolusoga @JanaMW27 will we need any special consideration for how we handle the Extensions page here? Should it be un-hooked at some point?

Edit: See https://github.com/Automattic/wp-calypso/issues/55416 :)

**Comment by lsl** [comment]
I was envisioning either removing it or pointing it at the marketplace with a woo search filter applied.

**Comment by olaolusoga** [comment]
remove/hide

**Comment by lsl** [comment]
Not too fussed about the menu loading via wpcomsh for now.

**Comment by lsl** [comment]
^ got picked up by @DustyReagan 783-gh-Automattic/wpcomsh / 8-gh-Automattic/woo-on-plans
