### ISSUE TITLE
Categories and Tags still mentioned in Settings > Writing, needs rewording 

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#55429]
### Steps to Reproduce

1. Go to a WordPress.com website
2. Navigate to Settings → Writing
3. The subheader/page description says 'Manage **categories**, **tags**, and other settings related to your site's content.'

See here: 
https://d.pr/i/v7kVdB

### What I expected to happen

Categories and Tags should not be in the sub-header/page description. 

They are now under Posts → Tags And Posts → Categories

Seems to affect all WordPress.com sites. 

### What actually happened

N/A

### Context

Noticed randomly!

### Operating System

macOS

### Browser

Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Number of Users Impacted

All users

**Comment by jordesign** [comment]
I feel like this could be simplified to something like:

"Manage settings related to your site's content."

@Automattic/editorial could you please review?

**Comment by kristastevens** [comment]
@jordesign, thanks for the ping! That works perfectly!

**Comment by synora** [comment]
Closing as this is fixed. 
<img width="612" alt="Screen Shot on 2021-08-17 at 11-06-48" src="https://user-images.githubusercontent.com/10015451/129751663-abb9838a-c168-4e33-b7bc-b04ef214e90f.png">
