### ISSUE TITLE
Feature Request: Reblog Block or pattern

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#55432]
### What

A block which pulls in all your  reblogged posts

### Why

This could be a great way for users to have a dedicated page/section for posts they have reblogged. Something like a 'Recently Reading' section.

Has great potential to build community if it encourages reblogging to happen more often - and become a part 'how' to blog on WPCOM.

ref: p7DVsv-cnw-p2#comment-37054

### How

I don't know how reblogged posts are stored/differentiated. Maybe it is sufficient to be able to select them in the Query Loop block and include them in a pattern?

Or maybe it would need to be a custom block that had a query for reblogged posts.

**Comment by autumnfjeld** [comment]
This sounds like something that would need P2 discussion and definition. Is that correct?   If so let's file it in "For the future" until the idea is more concrete.

**Comment by jordesign** [comment]
Doing a bit of digging - it looks as though when a post is re-blogged to your site - there's no real way to distinguish it from any other post in the site. So I can't think of any _easy_ way to pull them all together.

The main thing I can see is in that the post content contains everything in a `wpcom-reblog-snapshot` div - something we could maybe target programatically. But definitely something to consider with more research in the future.
