### ISSUE TITLE
Atomic Downgrade: Make site private while reverting/importing

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55452]
The lossless import task that runs as part of the Atomic site lossless revert can take a long a time. Unfortunately, during such time, some content may be unavailable because it's not been imported yet. 

Due to that, some customers may prefer to have their site private until the lossless revert is completed. A subset of these customers may also prefer to check their site before it's public again, while others may prefer the site to be public again automatically after the revert is completed.

To satisfy these users, we could introduce an additional step prior starting the lossless revert asking what's their preference:
- Keep site as public during the lossless revert.
- Set site as private during the lossless revert, and automatically change it back to public once if finishes.
- Set site as private during the lossless revert, and leave the user to change it back to public whenever they want.

Props to @jmdodd for the suggestion (p1628766939109100/1628761881.093800-slack-C029N3D2ZHR):
> What about setting the Simple Site (once reverted) to nogoogle (or even private) and emphasizing that once we’ve imported content, the customer will have the chance to make sure their site is ship-shape before it is public again?

**Comment by dsas** [comment]
Site visibility can be done with the blog_public setting. `WPCOM_JSON_API_Site_Settings_V1_4_Endpoint` has a good description of the values, and is also an API endpoint for changing the setting if that's useful..

**Comment by dsas** [comment]
Rather than provide a choice we (specifically @jmdodd) are going to set the site as private during the lossless revert, and leave the user to change it back to public whenever they want. #56059 will prompt users to check and change it back to public.

Leaving this issue open for now in case we do want to give users the option before revert & restore and have time to do that.

**Comment by kdevnel** [comment]
Just adding that the #56988 JITM will also prompt users to check and change the privacy of the site if they visit their Calypso during the import.

**Comment by JoshuaGoode** [comment]
Reverted sites will now default to private.

* D68786-code
* p7DVsv-cXE-p2

Not sure if ya'll want to keep this issue open for anything changes related to user-facing@ds reverts or messages.  So, I'll leave it open.

**Comment by mmtr** [comment]
I created a new issue for specifically tracking the lack of a warning message before a user self-cancels a plan from an Atomic site in Calypso (https://github.com/Automattic/wp-calypso/issues/57278) so I guess we can close this one out.
