### ISSUE TITLE
Templates: Add a new bug reports to the the `HE Triaging Board (new bugs)` project

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#55463]
Please add new issues created using the "Bug report" button at `/wp-calypso/issues/new` to the `HE Triaging Board (new bugs)` project at: `/Automattic/wp-calypso/108`. Thanks!

Discussion here: p1628779696120400-slack-C01UW7SB411

Cc: @davipontesblog

**Comment by dpasque** [comment]
@Automattic/quality-squad Pinging us as this would be good for us to take!

**Comment by inaikem** [comment]
For reference, the Bugomattic link that adds the project, labels and calls the report template:

https://github.com/Automattic/wp-calypso/issues/new?projects=Automattic/wp-calypso/108&labels=User+Report%2C+%5BType%5D+Bug&template=happiness-bug-report.yml

**Comment by kwight** [comment]
Weird, at https://github.com/Automattic/wp-calypso/issues/templates/edit, I don't see this as an option, and it's not mentioned at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository either. Strange that this would only be supported when creating an issue directly by URL (like we do with Bugomattic) – am I missing something?..

**Comment by inaikem** [comment]
This is all quite new to me. I pulled together the various chats we've been having across GH and Slack into this thread.

I'd like us to put this on hold for the moment while I get some consensus on our next steps: pcLjiI-i3-p2

**Comment by jeherve** [comment]
> I don't see this as an option

It's worth noting that issue forms are still in Beta, so this may be added in later.

I've created this issue to pass on that feedback to the GitHub team:
https://github.com/github/feedback/discussions/5210

Until then, I would recommend relying on GitHub actions to automatically add labels to a project board based on the content of the issue (and thus the content you've added to the issue form). We take a similar approach to automatically label issues created via forms in Jetpack:
https://github.com/Automattic/jetpack/blob/1be27985f8c9fcea91dacdaf5bffbd300bc1c3c0/projects/github-actions/repo-gardening/src/tasks/triage-new-issues/index.js

Here is an example of implementation for project boards:
https://github.com/peter-evans/create-or-update-project-card/blob/f3e6d3c5482d0be50c6a4fc4b911629ee32354c5/src/main.ts

**Comment by cometgrrl** [comment]
Marking this done, although the current destination board is different, this has been implemented.
