### ISSUE TITLE
Templates: Add a new feature requests to the the `HE Triaging Board (new bugs)` project

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#55464]
Please add new issues created using the "Feature report" button at `/wp-calypso/issues/new` to the `HE Triaging Board (new bugs)` project at: `/Automattic/wp-calypso/108`. Thanks!

Discussion here: p1628779696120400-slack-C01UW7SB411

Cc: @davipontesblog

**Comment by inaikem** [comment]
For reference, the Bugomattic link that adds the project, labels and calls the report template:

https://github.com/Automattic/wp-calypso/issues/new?projects=Automattic/wp-calypso/108&assignees=&labels=%5BType%5D+Feature+Request&template=feature_request.yml&title=

Would it be possible to add `User+Report` to the query string so we can track the report as coming from Happiness?

**Comment by inaikem** [comment]
I pulled together the various chats we've been having across GH and Slack into this thread.

I'd like us to put this on hold for the moment while I get some consensus on our next steps: pcLjiI-i3-p2

**Comment by cometgrrl** [comment]
This one is also done, although we're using a new board now.
