### ISSUE TITLE
The Tiktok embed block does not work on WP.com reader

### ISSUE THREAD

**Issue by geektzu** [Automattic/wp-calypso#55479]
### Steps to Reproduce

1. Make a post with Tiktok embed block on a P2. The Tiktok will work on the post.
E.g: 
{p73hfx-44X}-p2

Tiktok displayed correctly like this screenshot: https://d.pr/i/ydVosb

2. When the post is read from WP reader. The Tiktok block does not show up correctly. E.g
https://wordpress.com/read/blogs/{blog-id}/posts/{post-id}
Screenshot:
https://d.pr/i/2AAGBH

### What I expected to happen

The Tiktok block from the WP.com reader should be displayed like:  https://d.pr/i/ydVosb

### What actually happened

The TikTok block is displayed like: https://d.pr/i/2AAGBH

### Context

The WP.com reader and the original P2 post were opened on the same browser and OS. 

### Operating System

macOS

### Browser

Firefox

### Simple/Atomic

Simple

**Comment by sixhours** [comment]
This has been fixed by #84967
