### ISSUE TITLE
Stats: HTML entity not stripped from title in the post stats page

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#55477]
It is possible to add custom HTML such as `<em>` or `<i>` to post and page titles and they will be rendered correctly when you visit the post.

Examples from WordPress.com:

- https://wordpress.com/forums/topic/italics-in-post-title/
- https://wordpress.com/forums/topic/how-do-i-italicize-in-the-title/

The individual post stats page does not strip the HTML.

### Steps to reproduce the behavior

1. Go to Stats
2. On the "Posts & Pages" section, click on a post that has an HTML entity on the title. 
3. Check the post title

#### What I expected to happen

To have HTML tags either:

-  Transformed into the element. For example, <em>This is italic</em> shown as italic in the post list; or
-  Stripped as we see in the post/page list:

<img src="https://user-images.githubusercontent.com/1136160/128740656-77a44324-21ea-4ee9-9a05-d7ad65bb2275.png"/>

#### What actually happened

![Screen Shot on 2021-08-12 at 18:44:52](https://user-images.githubusercontent.com/1136160/129274162-5ceb1e18-7169-411c-8349-2900a3b7bbc2.png)

### Context
Dogfooding

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

**Comment by Aurorum** [comment]
PR for this issue in #55495. :)
