### ISSUE TITLE
Plans: Ensure WoA sites always use WordPress.com plans

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#55488]
During our work recently on closing the differences in the experience between WordPress.com simple and Atomic sites, we discovered that Atomic sites without a plan would report as being `jetpack_free`.

As a result there are checks in the code base that look for this plan and whether the site is Atomic, but other parts of code that assume these are Jetpack sites and not WordPress.com.

This complexity and inconsistency in the logic leads to bugs that could be solved/avoided by ensuring that all WordPress.com sites always use a WordPress.com plan slug.

As such we should find uses of `jetpack_free` and update it as necessary.

**Comment by gavande1** [comment]
Diff created at D75518-code

**Comment by gavande1** [comment]
Deployed r240996-wpcom
