### ISSUE TITLE
Services Block: Include option to replace image

### ISSUE THREAD

**Issue by lizswafford** [Automattic/wp-calypso#55517]
### What

Request to add an option to replace an image previously added to the Services Block. 

### Why

Add a Services Block to a post or page. 
Insert the image, heading, and text. 
It is not possible to replace the inserted image. 
To replace the image you need to add the block again, choose the new image, and copy and paste the heading and text. 

(#31127840-hc)

### How

Request to add a Replace Image link to the block toolbar, or to the Image Settings where it currently has the option to change the image focal point. Similar to the Cover Block, or the Featured Image option for a page or post. 

Screenshot of current block settings: https://d.pr/i/FweS1B

**Comment by inaikem** [comment]
Hi Liz, thanks for submitting this feature request!

As the Services block is provided as part of the CoBlocks plugin on WordPress.com, I've gone ahead and raised an issue in that repo: https://github.com/godaddy-wordpress/coblocks/issues/2004. I'll be closing this request now.

As a quick note on process here in GitHub, please embed images _directly_, as opposed to linking via Droplr, Cloudup, etc 🙏 

(Internal thread for reference: pbg9X-fWF-p2)

**Comment by inaikem** [comment]
I revisited my test for the initial report as part of the new issue reported in [godaddy-wordpress/coblocks#2004](https://github.com/godaddy-wordpress/coblocks/issues/2004). 

An "X" button used to clear the currently set image is now visible, so I've closed the other issue for the moment.

Please reopen this one if the issue appears again!
