### ISSUE TITLE
Edit site title. I want to edit tagline too but the popup guide blocks the tagline

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#55513]
TODO: Autumn will finish this description

![image](https://user-images.githubusercontent.com/5665959/129424951-ef606339-0a6c-4d99-9e1c-e98adace6834.png)

**Comment by jordesign** [comment]
ooh - yes please. This is a real 'back to basics' one...

That being said - Is this step of the checklist something we should revisit the idea of sending folks to the Customizer to change (as we investigated in the My Home pod)?

**Comment by autumnfjeld** [comment]
>  Is this step of the checklist something we should revisit the idea of sending folks to the Customizer to change (as we investigated in the My Home pod)? 

Yes.  https://github.com/Automattic/wp-calypso/issues/53434  should be considered in finding a solution.

**Comment by tyxla** [comment]
Marking this as a good first issue. 

Just to clarify, this is easy to reproduce by going to: `/settings/general/:site?tour=checklistSiteTitle` where `:site` is the slug/domain of your site.

**Comment by spraveenitpro** [comment]
I am looking at this @autumnfjeld  @tyxla

**Comment by tyxla** [comment]
Awesome, @spraveenitpro! Feel free to reach out to me if you need any help with it.

**Comment by spraveenitpro** [comment]
### Here is what I am planning to implement:

![](https://d.pr/i/2e3z9O+)
[Direct Link](https://d.pr/i/2e3z9O+)



### Here is the original:

![](https://d.pr/i/pdHvmE+)
[Direct Link](https://d.pr/i/pdHvmE+)

Moving the popup upwards, creates the space for the site tag line, hope that is fine.

@tyxla

**Comment by arthur791004** [comment]
I'm not sure but I think if we have a sort of educational tour, we should only allow the user to edit the target element. That being said, the user should only fill out the site title and click the “All done, continue” button and follow the next educational tour. I'm okay to adjust the popup position for now.

**Comment by tyxla** [comment]
I think this is a solid solution @spraveenitpro! I'll review the PR code-wise, but will also ping folks from @Automattic/ganon who own the onboarding flows and should give the final call on it.

**Comment by spraveenitpro** [comment]
Hi @autumnfjeld 

The Popup guide is blocking the Site Tagline at this moment, here is my thinking:

1. If we place the popup guide above the `Site title` then on the mobile layout [it will be  forced](https://github.com/Automattic/wp-calypso/blob/97220c28205a5e722daf9342ddb35b74d6f8c52f/client/layout/guided-tours/positioning.ts#L193) to be placed below causing it to again go over the `Site Tagline` in the mobile layout
2. Placing it `beside` is not encouraged as it will not work well on the mobile layout, more on that [here](https://github.com/Automattic/wp-calypso/pull/58087#issuecomment-972706723)
3. What do you think about this proposal: Place the popup guide below the `Site Tagline input` which would look like this on the desktop layout:

![](https://d.pr/i/rCosYw+)

4. On the mobile layout, it will look like this - again not overlapping on the `Site Tagline`:
![](https://d.pr/i/aPge06+)


Let me know your thoughts on this.
Ccing @tyxla

**Comment by autumnfjeld** [comment]
@spraveenitpro  
>  Place the popup guide below the Site Tagline input
I think your proposal is better than the existing situation, in which the tagline field is blocked. 👍 

We could also update the copy (but I think it is ok if we don't): "Update the Site title and tagline fields to let visitors clearly identify your site."

![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=40)

**Comment by spraveenitpro** [comment]
Great, updated the copy,  so let me know if any changes:

### On Desktop:

![](https://d.pr/i/4eD09D+)
[Direct Link](https://d.pr/i/4eD09D+)

### On Mobile:

![](https://d.pr/i/n3FoS0+)
[Direct Link](https://d.pr/i/n3FoS0+)

🙏🏼 @autumnfjeld

**Comment by enejb** [comment]
If we do this do we cover up the Site icon UI on mobile web? 
cc: @spraveenitpro

**Comment by spraveenitpro** [comment]
@enejb As the real estate is limited, it is going to cover something on the mobile layout. As soon as the user clicks on the `All done, Continue` button, it will go away. :)

**Comment by tyxla** [comment]
My $0.02 on the latest solution: I find the fact that the step is below the tagline field confusing. As a user, I'm confused whether I have to fill the site title field or the site tagline one.

**Comment by autumnfjeld** [comment]
A couple suggestions for the copy in the popup guide:
* match the capitalization that is in the UI , meaning only Site is capitalized, while title and tagline are not capitalized. 
* instead of "...Site tagline and title...", use "...Site tagline and Site title...". (repeat the word Site for added clarity and to match the UI)
* use bold font for both "Site title" and "Site tagline" to emphasize these are fields the user can edit

Hopefully this will reduce the confusion you mentioned @tyxla . :) 
Thank you!

**Comment by spraveenitpro** [comment]
Thank you, @autumnfjeld  @tyxla 

- [x] match the capitalization that is in the UI , meaning only Site is capitalized, while title and tagline are not capitalized.
- [x] instead of "...Site tagline and title...", use "...Site tagline and Site title...". (repeat the word Site for added clarity and to match the UI)
- [x] use bold font for both "Site title" and "Site tagline" to emphasize these are fields the user can edit
- [x] I find the fact that the step is below the tagline field confusing. As a user, I'm confused whether I have to fill the site title field or the site tagline one.

Here is what we have at this moment:

![](https://d.pr/i/8sorvU+)
[Direct Link](https://d.pr/i/8sorvU+)

**Comment by autumnfjeld** [comment]
Looks great!!  Nice work!

![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)
