### ISSUE TITLE
Reader: Posts loaded with "New Post" button are already marked as seen

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#55514]
When you use the "new post" button, the new posts that appear in the feed are already marked as seen with the `.is-seen` class.

I cannot reproduce the issue in the internal A8C tab.

### Steps to reproduce the behavior

1. Go to https://wordpress.com/read
2. Wait for new posts to appear
3. Tap the "new post" button on the upper right
4. Check the posts just loaded in the feed

#### What I expected to happen

That these posts were not marked as seen.

#### What actually happened

Post appears as _seen_ in:

- Main Reader: https://wordpress.com/read
- Site Reader Feed. Example: https://wordpress.com/read/feeds/50426619

https://user-images.githubusercontent.com/1136160/129423234-d2946eb2-5ed3-41ed-b43b-bf81478d8d40.mp4

If you refresh the page, however, the items won't appear as _seen_ any longer. Here's a screenshot from the day after:

![Screen Shot on 2021-08-14 at 10:59:20](https://user-images.githubusercontent.com/1136160/129448699-8e602eb4-eda4-4de9-8f33-a3719824d987.png)

### Context
dogfooding

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Impacts all users using the Reader.

**Comment by inaikem** [comment]
Pinged @eduardozulian re Bugomattic and added the issue to the HE Triage board.

**Comment by roo2** [comment]
I think this has been fixed, the post now doesn't have the `\.is-seen` class and appears normally. 

Note, to test this you must not be sandboxed so that websockets connection works.

https://user-images.githubusercontent.com/22446385/218355836-9f437de1-c591-43b0-b7d8-4a16078382b9.mov
