### ISSUE TITLE
Widgets: Restore or deprecate legacy Podcast Widget

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#55512]
WordPress.com previously offered a Podcast Widget but this appears to be no longer available within the new block widget editor.

Documentation: https://wordpress.com/support/audio/podcasting/#podcast-widget

The widget is available on Atomic if the Classic Widgets plugin is active and the WordPress.com podcasting feature is enabled.

If this widget will no longer be available, we will want to open a WPCOM documentation issue and remove it from our docs.

If setup, it pulls in the WordPress.com podcasting settings information under My Site > Settings > Writing. This includes the title, image, subtitle, author, copyright information, and a link to Subscribe on iTunes.  

![Screen Shot on 2021-08-13 at 19:02:19](https://user-images.githubusercontent.com/4887830/129425725-cf4b4b49-6b44-4db3-91ec-12196323a6d5.png)

While helpful to only need to keep that information up-to-date in one place, it can be recreated with blocks.

### Steps to Reproduce
1. Enable the WordPress.com Podcasting feature under My Site > Settings > Writing
2. Open the widget editor under Customize > Widgets.
3. Look for the Podcast Widget, double-check within the Legacy Widget block.

### What I expected to happen

For the Podcast Widget to be present.

### What actually happened

No podcast widget.

### Context

HE working with a user pinged for information about it and alternatives.

* Slack: p1628892130149000-slack-C03TY6J1A
* 31114908-hc

Documentation:
* https://wordpress.com/support/audio/podcasting/#podcast-widget

### Simple/Atomic

Simple and Atomic

### Number of Users Impacted

One user

### Available Workarounds

Depending on the goal, utilize a block to manually create this.

On WordPress.com Atomic, active the Classic Widgets plugin.

### Reproducibility

Consistent

**Comment by dpasque** [comment]
Putting in front of Blogger Experience in case this seems like something that could be related to that work. If not, let me know and I can move this around!

**Comment by autumnfjeld** [comment]
@dpasque I don't think we'd make this a priority any time soon, we are full on getting the new Blogger onboarding flows launched and debugged.  

I can't judge the relevance of this off the top of my head, probably good to check with someone who is active in the podcasting realm. :)

**Comment by arcangelini** [comment]
It looks like the documentation has already been updated and the widget was removed from the documentation. I am not seeing anything on ⇢ https://wordpress.com/support/audio/podcasting/#podcast-widget

I am not 100% sure why this widget is not being shown in the Legacy Widget block, but it seems like this may be redundant since the [Podcast Block](https://wordpress.com/support/wordpress-editor/blocks/podcast-player-block/) is available now.

Is it safe to close this as Deprecated?

**Comment by arcangelini** [comment]
Widget seems to be deprecated. Please reopen if this is not the case.
