### ISSUE TITLE
Add "interactive" to Welcome Tour slide. And maybe a sentence:  "Try each suggestion for yourself."

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#55515]
The Welcome Tour is meant to be interactive, but the user may not realize that.  We don't prompt them at all to "try it for yourself while going through the tour"

BEFORE
![image](https://user-images.githubusercontent.com/5665959/129426124-43c0faf1-47f0-4aef-bf14-ed144f63554f.png)

PROPOSED
new copy: "Continue on with this short, interactive tour to learn the fundamentals of the WordPress editor."

MAYBE (to be discussed with Ollie)
Add wording the preps the user that they can/should play in the editor, follow the suggestions on each slid.  
 "Try each suggestion for yourself."    There is a better way to say that.

**Comment by jordesign** [comment]
I like the idea of encouraging/prompting action. Something like 'Give it a try' or 'try it out!'

**Comment by p-jackson** [comment]
pdgK6S-6i-p2

**Comment by p-jackson** [comment]
Change deployed in latest ETK release: D66502-code
Code change here: #56049
