### ISSUE TITLE
Navigation block: allow for collapsed (i.e. responsive) vertical menus on desktop/tablet

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#55541]
### What

Allow for drop-down menus, akin to HTML select boxes

### Why

In instances where a user is trying to add a vertical menu, and they might just like a select box, this would be helpful. Just a plain, ordinary drop-down.

For example, I am trying to create multiple group blocks, each with their own title and menu below. A drop-down would be useful here to ensure that each group remains in proportion to one another, and that all menu options are not exposed by default.

<img width="1406" alt="Markup 2021-08-16 at 14 19 55" src="https://user-images.githubusercontent.com/39252765/129625025-3cde99be-66c4-494c-b74b-fa1f97ad2103.png">

**Comment by jordesign** [comment]
Shifting this over to the Gutenberg repo:
https://github.com/WordPress/gutenberg/issues/34253
