### ISSUE TITLE
Fix Woo Atomic Upgrade

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#55544]
Upgrading a Woop simple site to atomic fails somewhat spectacularly.

We need to figure out why and fix it (or get it fixed).

![Your_Site_‹_Jules_Aus_Test_eCommerce_—_WordPress_com_and_Woop_and_Debug_–_Jetpack_Tools](https://user-images.githubusercontent.com/5952255/129648467-4d0b8e1e-70ad-4894-88ea-86517ebe4da6.jpg)

**Comment by lsl** [comment]
Woo on simple infra - no longer relevant.

**Comment by lsl** [comment]
Actually this was a sort of bug and has been fixed in D66750-code
