### ISSUE TITLE
Reader: Gutenberg gallery caption background is longer than the images

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#55548]
### Steps to reproduce the behavior

1. Create a post with a two-column gallery in the Gutenberg editor.
2. View the post in the Reader.

#### What I expected to happen
Nice, neat backgrounds underneath the image captions.

#### What actually happened
The gradient extends beyond the gallery:

<img width="801" alt="Screen Shot 2021-08-17 at 14 47 57" src="https://user-images.githubusercontent.com/17325/129663583-1c5703da-a2a4-4358-a53d-411f3fc48a04.png">

### Context

Discovered while viewing my own blog in the Reader.

I know that we use the standard Gutenberg styles in _typography.scss to style this content, but it might need a further tweak in the Reader styles.

#### Browser / OS version

Firefox / OS X.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low.

**Comment by ivan-ottinger** [comment]
I am preparing a patch in D66276-code.

**Comment by ivan-ottinger** [comment]
https://github.com/Automattic/wp-calypso/pull/55985 fix is now deployed to production. → Closing this issue.
