### ISSUE TITLE
Subscriptions: Refresh the email templates.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#55540]
The email template we use to send Followers a new post is looking very dated. Let's update this template to look more modern, and possibly bring it more in line with P2 templates (which are quite lovely).
Let's also keep in mind updating the links included in the template; some (such as the Manage Subscriptions link) may best be redirected somewhere else (in Calypso).

| Current | P2 |
| --- | --- |
| <img width="600" alt="Screen Shot 2021-08-12 at 8 11 43 AM" src="https://user-images.githubusercontent.com/349751/129622016-9e84ad36-0c16-48e3-9a1d-d2a14b2126e9.png"> | <img width="600" alt="Screen Shot 2021-08-16 at 12 54 23 PM" src="https://user-images.githubusercontent.com/349751/129622045-2847ff16-8ddc-4ac5-a50f-a9122a095c63.png"> |

**Comment by kwight** [comment]
In fact, there are _plenty_ of templates needing a refresh – see this Figma for the up-to-date list: crtNho9opJSnM80QsE275F-fi-2%3A51

<img width="1990" alt="Screen Shot 2021-08-17 at 12 59 43 PM" src="https://user-images.githubusercontent.com/349751/129792327-346b042f-c4ee-4f5f-9b4b-675c3836e424.png">

**Comment by coreymckrill** [comment]
Sorry if this isn't the right spot for this, but I'd love to see the way the daily and weekly digests are rendered get an overhaul too. Right now they are just a group of single new post email templates stacked together, so you get the site header and the unsubscribe / "powered by WordPress" stuff repeated for each post. Not only is that a lot of extra clutter, but it means the email tends to get cut off when reading in Gmail (with a "view entire message" link), which seems to be based on a [byte limit](https://www.drip.com/learn/docs/guides/avoid-email-clipping-in-gmail).

**Comment by kwight** [comment]
@saygunnyc Do you see yourself wanting to re-use some P2 templates, or going from scratch? I see some value in the former, but don't want to limit us if they're not appropriate or helpful.

**Comment by saygunnyc** [comment]
> I see some value in the former, but don't want to limit us if they're not appropriate or helpful.

Same page with you. I'd say TBD at the moment. You likely won't be surprised to hear but there are also many different email templates we use across WordPress.com. –  these being the latest pbvYe0-hS-p2#comment-590. So worth taking the time to look at what's good/what's not good in others with the goal of driving towards some kind of parity.

**Comment by saygunnyc** [comment]
@coreymckrill would you feel comfortable with adding screenshots of those emails within the Figma file @kwight shared above? You can just dump them in or feel free to share them here, and I can add them over to the document.

**Comment by coreymckrill** [comment]
Sure, here's a screen shot of the transition between posts that have been aggregated into a weekly digest (from the WordPress.org [Team Updates](https://make.wordpress.org/updates/) site). Will this work?

![weekly-digest](https://user-images.githubusercontent.com/916023/129796389-bd8e53e4-7aa3-4968-930d-2d0b2b73c045.jpg)

The modern P2 templates still do the same thing:

![p2-weekly-digest](https://user-images.githubusercontent.com/916023/129797038-19fdb179-ba06-4a8c-a4d3-37346cfeed7c.jpg)

**Comment by saygunnyc** [comment]
Looking at exact emails and posts, 
1 - https://make.wordpress.org/updates/2021/08/17/plugin-review-team-update-16-aug-2021/
2- https://make.wordpress.org/updates/2021/08/17/themes-team-update-august-17-2021/

These actually are posts and new post email templates–_not a combination of multiple posts_, so if WordPress.org is technically a blog under dotcom, I believe you can expect these emails to also get updated. But @kwight should confirm.

On the other hand, I am wondering how different are daily or weekly digest emails are. I am assuming it's a longer email with a combination of multiple posts but does anyone have any examples to share?

**Comment by coreymckrill** [comment]
I would guess that the only structural difference between Daily and Weekly digests is the subject line. Other than that they are both just aggregated single posts.

**Comment by kwight** [comment]
> I believe you can expect these emails to also get updated.

I think so – my error message would imply it's all part of the same system. 🙃 

<img width="328" alt="Screen Shot 2021-08-18 at 7 24 07 AM" src="https://user-images.githubusercontent.com/349751/129917006-f0ea6c6a-fd76-4f9c-9d91-3b546882e2b9.png">

**Comment by kwight** [comment]
@saygunnyc For prioritization, I'd say "Confirm Follow", "Follow Confirmation", and "New Post" would be the top three – this covers the most common user flow. "New Comment" and "New Like" would probably be the close 4 and 5 (I don't think there's any reason we can't get all five of these done this pod).

**Comment by kwight** [comment]
After those, I'd say the three site owner-specific ones (leaving the non-existant Contributed Post Approval out of scope), then the invites, then the digests. So, in a more readable list:

* New Post
* Confirm Follow
* Follow Confirmation
* New Comment
* New Like
* New Email Follower
* New WordPress.com Follower
* Comment Moderation Request
* Invited as Follower
* Accepted Follow Invite
* Invited as (Role)
* Confirmation as Role
* Accepted (Role) Invite
* Mentions in Comment
* Mentions in Post

**Comment by saygunnyc** [comment]
Sharing some initial explorations for the prioritized Confirm Email template along with some thoughts on what might be customized –once we have that project kicked off thinking it would be helpful to align on day 1 and future customizations while deciding on the default template.  _“Where do those settings be for customizing” is not a part of this._

**Existing Email**
<img width="668" alt="Existing" src="https://user-images.githubusercontent.com/78876323/129976208-325939cc-9a21-472f-ad9e-2be37d42db34.png">

**New Default i1**
<img width="1200" alt="Default" src="https://user-images.githubusercontent.com/78876323/129976257-13bec52a-032a-4bdb-80bf-28d0be6c0a22.png">
Note that the copy needs more work. Esp. thinking about the footer links. However, I already tweaked the language from subscriptions to follow. 

**Customization Exercise over i1**
<img width="1200" alt="Customized" src="https://user-images.githubusercontent.com/78876323/129976415-3e0e5823-92fb-4246-a07f-f18bb58e9c0b.png">

The example shared above is customizing...

- Background color
- Content background-color
- Logo
- Adding an image block under the title
- Adding social media handles, along with their links
- Changing CTA colors
- Editing Primary CTA corner radius
- Footer copy

We can limit the customizations for an initial roll-out however there can be more opportunities for customization:

- Title
- Content background-color
- Body copy - I believe this is one of the first we’d like to make customizable. 
- Links provided “Sign Up” and “Follow Settings” in this case.
- CTA copy
- Adding more visual blocks

What are your thoughts?

**Comment by kwight** [comment]
These look fantastic @saygunnyc , thank you! I notice your buttons are square, compared to the pill style of P2; is that intentional, or a problem one way or the other? We're happy implementing whatever you think is best. 👍

> Body copy - I believe this is one of the first we’d like to make customizable.

I think the first step would be to have a slot for custom text in the New Post template (in addition to existing template content) – any other customizations in other templates, I'm skeptical we'll get to them in this pod. I hope I'm wrong, they would be nice to see.

**Comment by saygunnyc** [comment]
Thank you so much, @kwight! 

>I notice your buttons are square, compared to the pill style of P2; is that intentional, or a problem one way or the other? 

Yes, that's intentional to have parity with the button styles we use over WordPress.com. And the color used here is Blue 50 for a similar reason.



As the next steps, I am planning on P2ing the first 3 templates this week. While also planning to move forward with the remainder list, I'm still finding myself a bit unsure about using standard font vs. "Recoleta" over the header. I reached out to our white-labeled email product, Titan Email to figure if their webmail Inbox would be able to render "Recoleta" if we were to use it. Also will further discuss with the broader team.

Finally, I also wanted to drop this "Recoleta" version for visibility along with the customization in the meanwhile.

<img width="1193" alt="Revamp_02" src="https://user-images.githubusercontent.com/78876323/130526293-b5795226-a8f1-4f9e-9f41-2383799e8c34.png">

**Comment by kwight** [comment]
Launch plan is at pdgv5Y-gJ-p2. See the call for testing at pdgv5Y-hH-p2.

We'll do the following templates:
* confirmation request
* subscriber welcome
* new post
* new comment
* liked post
* liked comment
* new WP.com follower

**Comment by yansern** [comment]
> confirmation request
> subscriber welcome
> new post
> new comment
> liked post
> liked comment
> new WP.com follower

Covered in pdDOJh-99-p2 and pdDOJh-wY-p2.
