### ISSUE TITLE
Unable to Delete P2 with 0 Spaces

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#55559]
### Steps to Reproduce

1. Create a new p2 at https://wordpress.com/start/p2/p2-site?ref=p2-lp
2. Delete the initial space
3. Attempt to delete the hub p2
4. Receive an error message that 

### What I expected to happen

The hub p2 would be possible to delete.

### What actually happened

The hub p2 with 0 spaces could not be deleted.

![image](https://user-images.githubusercontent.com/3505172/129747349-03d68f12-85d0-4ec0-8a9d-3a4dfb6832f2.png)

![image](https://user-images.githubusercontent.com/3505172/129747850-422611b0-803a-4019-a0e8-a3439a5159c2.png)

### Context

Customer report in 4224503-zen

### Operating System

macOS

### Browser

Chrome/Chromium

### Is this specific to applied theme? If so, what is the theme name?

P2

### Number of Users Impacted

All users

### Available Workarounds

Manually deleting the site with super admin access works, but that's not ideal.

### Reproducibility

Consistent

**Comment by sixhours** [comment]
Moved to 3589-gh-Automattic/p2
