### ISSUE TITLE
Account closure: Disable autocorrect for account name

### ISSUE THREAD

**Issue by twstokes** [Automattic/wp-calypso#55563]
### Steps to reproduce the behavior

1. Go to [wordpress.com/me](https://wordpress.com/me)
2. Click on Account Settings
3. Scroll down to and click "Close your account permanently"
4. Click Close account
5. Click Continue on the "Are you sure?" dialog
6. Type account name in the "Confirm account closure" dialog

#### What I expected to happen

No autocomplete / autocorrect suggestions from browser.

#### What actually happened

Browser suggests an autocorrection to the username.

### Context

Found this while closing an account.

#### Browser / OS version

Safari 14.1.2, possibly others.

#### Screenshot

<img width="450" alt="Account closure dialog box" src="https://user-images.githubusercontent.com/2092798/129783406-01a72c4e-64b0-4ed8-83bb-eee6ec532f02.png">

**Comment by tyxla** [comment]
Marking this as a "Good First Issue".

**Comment by spraveenitpro** [comment]
Hi @twstokes  @tyxla 

I was able to replicate this behaviour on safari/mac:

![](https://d.pr/i/mbR4rj+)
[Direct Link](https://d.pr/i/mbR4rj+)

The best way to fix it I realized was to uncheck this option from safari menu:

![](https://d.pr/i/hPRw7q+)
[Direct Link](https://d.pr/i/hPRw7q+)

i.e. from Edit >> Spelling & Grammar >> Correct spelling automatically

**Comment by twstokes** [comment]
Thanks for the suggestion @spraveenitpro. That certainly could work, but if I understand correctly that setting would apply to all websites and that may not be the user's preference. My initial thought was to add the [`spellcheck="false"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) attribute to the `<input>` as it may not be particularly helpful in this scenario.

**Comment by tyxla** [comment]
Thanks for taking a look @spraveenitpro!

Yeah, I totally agree with @twstokes - we can't just tell every user "hey, change this setting locally". Ideally, the UI should work well and not stand in the way, regardless of the user's preferences.

**Comment by tyxla** [comment]
This is fixed by #57465 - thanks @spraveenitpro 🙌
