### ISSUE TITLE
Themes: View a log of previously activated themes

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#5556]
When exploring new themes, users will sometimes activate multiple themes and experiment with them, only to return to their original choice later.

We mitigate some of this by offering a **Preview** tool for each theme, but if a user does indeed experiment by **Activating**, and they do not recall the name of the theme they were originally using, it can be difficult to get back to where they started.

Could we offer a log visible to the user where they can see a list of themes previously activated on the site?

**Comment by folletto** [comment]
Nice idea! :)

**Comment by formosattic** [comment]
User request to have access to history of activated themes: 447079-chat

**Comment by formosattic** [comment]
> I was trying out different themes to see if they would work better and I activated several so that I could check them out and now I cannot remember or find the them I originally had for years.

445891-chat
