### ISSUE TITLE
Framework: Style/reset `:invalid`

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#5557]
We should either style or reset the [`:invalid`](https://developer.mozilla.org/docs/Web/CSS/:invalid) selector. That selector is added to `<input>`s with a `pattern` attribute specified, when that pattern isn't matched. Due to React's way of dealing with controlled `<input>`s, I currently only know of one way to reproduce it, which is with React 15, under Firefox. I suspect it will become more prevalent once we switch to React 15.
- Check out the branch corresponding to #5116, `make distclean`, `npm install`, `make run`
- In Firefox, navigate to http://calypso.localhost:3000/devdocs/design/form-fields
- Enter some non-numeric content into the 'Phone Number' field below `Form Phone Input`
- It gets a red border

No red border in Chrome though, so maybe we should just reset `:invalid`. 

Related: #5554, which fixes the example's initial value to be valid.
Found via p6jOYE-sc-p2.

/cc @mtias @folletto

**Comment by folletto** [comment]
Ok, I gave it a run.

I think we need to style `:invalid` in a way that matches `.is.error` for form fields:

![screen shot 2016-05-25 at 17 55 37](https://cloud.githubusercontent.com/assets/4389/15548802/e9cc9904-22a1-11e6-818a-f2549d8e28ed.png)

However I'm not sure if it solves all the concerns, would it? :)

**Comment by ockham** [comment]
> However I'm not sure if it solves all the concerns, would it? :)

I think the remaining issue is that Firefox picks it up while Chrome seems to ignore it. So maybe we should just disable it as described in the [MDN article](https://developer.mozilla.org/de/docs/Web/CSS/%3Ainvalid)?

**Comment by ockham** [comment]
Uh, maybe misread that article:

> By default, Gecko does not apply a style to the :invalid pseudo-class. However it does apply a style (a red "glow" using the box-shadow property) to the :-moz-ui-invalid pseudo-class, which applies in a subset of cases for :invalid.

Okay, so maybe we can style it and both will apply it.
