### ISSUE TITLE
Marketplace: New Plugin Details page

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#55577]
Final designs: oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A46946

- [x] New Layout (wider, 2 columns)
- [x] Header with summary 
- [x] CTA Actions (Install)
- [x] Description (includes plugin cover image) / FAQ's
- [x] Secondary Info
- [ ] Make sure that author link redirects to our plugin search results showing plugins of that author eg for yoast `https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request[author]=yoast`

Notes from our call:
- Let's keep the tabbed experience
- Let's keep all tabs that currently appear on Production (eg Description, Installation, Chagelog, FAQ)
- Don't use "Read More" and have the content expanded by default

|Before | After|
|-------|------|
|![](https://cln.sh/GSkC83+)|![](https://cln.sh/drMA44+)|

- **Let's avoid adding any pricing details for the time being. Paid plugins will be part of Marketplace V1, while this is part of V0.5**
- Let's create a new plugin details component and use a feature flag here https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/client/my-sites/plugins/controller.js#L33-L39

**Comment by tjcafferkey** [comment]
Blocked until designs are finalised
