### ISSUE TITLE
Jetpack Carousel: Conflict with other swiper carousels

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#55579]
### Steps to Reproduce

It appears that if other plugins are using the swiper carousel that Jetpack is conflicting with it. This seems related to the following PR - #20268

It seems that in the case I came across, the CSS for the carousel arrows is still applied to a slider added by the Colibri page builder. This leads to doubling of arrows in some cases.

### What I expected to happen

Jetpack carousel shouldn't interfere with other sliders using the swiper.

### What actually happened

![Uploading Markup on 2021-08-18 at 14:25:24.png…]()

### Context

31191416-hc

### Operating System

macOS

### Browser

Firefox

### Available Workarounds

I had to use the following CSS to hide the Jetpack swiper arrows:

```
.swiper-button-prev::after, .swiper-container-rtl .swiper-button-next::after, .swiper-button-next::after, .swiper-container-rtl .swiper-button-prev::after {
	display: none;
}
```

**Comment by inaikem** [comment]
@kdevnel thanks for reporting this. 

~~I'm not sure the PR you mentioned above is related as it's from December 2017. Would you mind double checking that for me?~~

Also, if you have the screenshot you tried to add to the report, please drop it in as a comment. The upload looks to have failed 😞 

EDIT: The PR was from the JP repo (see below). Adding the issue ID here linked it to the same PR ID in this repo.

**Comment by inaikem** [comment]
Regarding the above, this should be the correct PR: https://github.com/Automattic/jetpack/pull/20268 (H/T @jordesign)

@jeherve, is this something you could take a look into? Please let me know if requests like this are better directed elsewhere if not! 🙏 

I'm happy to move this into the JP repo if that's the next action.

**Comment by jeherve** [comment]
We've done more work to address more potential conflicts with other plugins. The latest patch on this issue is https://github.com/Automattic/jetpack/pull/20599 , and it will ship with next major release of Jetpack, scheduled for September 7. I would consequently recommend waiting until then; the problem should then be solved.
