### ISSUE TITLE
Marketplace: Create a WPCOM API serving the wpcom extensions offered to the Marketplace.

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#55574]
**Tasklist**

- [x] Return all results
- [x] Return results filtered by a term
- [x] Return item by id or slug
- [x] Tests
- [x] #57318

**Acceptance Criteria**

- [x] The results schema should be the same as .org results for consistency
- [x] We will use a static json file for storing plugin details
- [x] The endpoint might be used in a logged out landing page, it should be publicly available
- [x] Searching for `shipping` or other terms should return all extensions that contain this keyword

**Comment by tjcafferkey** [comment]
D65426-code

**Comment by gavande1** [comment]
D65972-code

**Comment by tjcafferkey** [comment]
@gavande1 is it both diffs above we're reviewing as part of this issue or just the one you commented with?

**Comment by gavande1** [comment]
@tjcafferkey Both the diff are part of this issue. The D65972-code provides a base for marketplace products and the  D65426-code is the endpoint that consumes the base code.

**Comment by gavande1** [comment]
Please discard previous diff's in favour of D68020-code

**Comment by gavande1** [comment]
Deployed r233015

**Comment by gavande1** [comment]
New diff search functionality D68564-code

**Comment by cpapazoglou** [comment]
Is now a good time to update the documentation here PCYsg-AhH-p2?

**Comment by gavande1** [comment]
Deployed the search feature: r233573

**Comment by gavande1** [comment]
> Is now a good time to update the documentation here PCYsg-AhH-p2?

Yes. It is. Will do.
