### ISSUE TITLE
Marketplace: New Plugins List page v0.5

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#55576]
**Tasks**
- [x] We need to make sure that both Atomic & Simple sites can reach the plugins Calypso page. 746-gh-Automattic/wpcomsh
- [x] #57067
- [x] #57100
- [x] #57101

Final designs: oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A46946

**Comment by tjcafferkey** [comment]
Blocked until designs are finalised
