### ISSUE TITLE
Notifications: filters redirect to old URL in Windows

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#5558]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Click Notifications bell icon
3. Click on a filter 
4. It incorrectly goes to https://wordpress.com/notifications
#### Browser / OS version
- IE 11 Windows 7
- Edge 20 Windows 10
#### Screenshot / Video

![screen recording 2016-05-24 at 10 52 am](https://cloud.githubusercontent.com/assets/618551/15510702/306729b0-219e-11e6-9706-ce6d6669c1ba.gif)

**Comment by dmsnell** [comment]
nasty - thanks for finding @drw158

**Comment by lancewillett** [comment]
Could we start redirecting `/notifications` now to auto-route to Calypso?

**Comment by lancewillett** [comment]
Re-ping @dmsnell on this one since you're working on IE already. :)

**Comment by lancewillett** [comment]
Re-testing this today with Windows 10 and IE Edge, still happening — needs fixing. Clicking any of the notifications tabs (Unread, Comments, Follows, Likes) redirects the page to https://wpcalypso.wordpress.com/notifications — which is a 404.

<img width="1395" alt="screen shot 2016-10-03 at 09 43 37" src="https://cloud.githubusercontent.com/assets/66797/19045758/4e40cd1a-894f-11e6-9f50-582c832443cd.png">

I confirmed Chrome and desktop app in same Windows 10 install worked correctly — seems to be only Internet Explorer.

**Comment by lancewillett** [comment]
Hi @dmsnell — just checking on this one, happy to re-test or confirm a fix when you're ready.

**Comment by dmsnell** [comment]
@lancewillett I haven't worked on it at all. I may have ran into the same problem when working on integrating my iframe-less notifications client - the master bar was wrapping (at a much higher point in the tree) the notifications bell in an `<a>` when a `<div>` would have probably been more appropriate. Something with the way the events were propagating was coming back up to it.

I'm out this week and can try and look into it when I get back unless @rodrigoi or someone knowledgable with the master bar wants to try and fix it before then.

Thanks for the checkup!

**Comment by rodrigoi** [comment]
@lancewillett @dmsnell I'll look into this. Definitely looks like an event propagation issue.

**Comment by lancewillett** [comment]
@rodrigoi Any update on this one? It's a few weeks old now.

**Comment by rodrigoi** [comment]
@lancewillett PR is up for review: https://github.com/Automattic/notifications-client/pull/608 😉

**Comment by lancewillett** [comment]
Still pending a merge from the notifications client side.
