### ISSUE TITLE
WooCommerce 5.6.0: default pages installed and activated after update

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#55582]
### Steps to Reproduce

1. Start with Woo below 5.6.0
2. Delete one or more of the default store pages
3. Update Woo to 5.6.0
4. Allow some time for DB updates etc.

### What I expected to happen

I only expected the new Refund and Returns Policy page to be installed as a draft (it was) but none of the other pages to be impacted.

I would expect that we may create those other pages as drafts, but not publish them since not all store owners want this.

### What actually happened

The default pages are reinstalled and published

### Context

p9F6qB-7lE-p2

### Operating System

macOS

### Browser

Firefox

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Reproducibility

Consistent

### Other information

Worth noting, this will likely impact all Woo sites since I tested this on WPcom and also on a local test site with the same results.

**Comment by kosiew** [comment]
Hi @kdevnel ,

Thanks for reporting this and the detailed steps.

Closing this to https://github.com/woocommerce/woocommerce/issues/30532
