### ISSUE TITLE
Marketplace: Research - Modify WooCommerce_Host_Service class to provision licenses

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#55588]
### What

Modify WooCommerce_Host_Service class to provision licenses for Woo extensions when they are purchased on subscription

### Why

We need a way to manage licenses for Woo extensions and this is the most appropriate place for it 2a04c-pb/

### How

We may need assistance from the Alphamattic team for this.

**Comment by gavande1** [comment]
I've been looking into `WooCommerce_Manager` and `WooCommerce_Host_Service` classes. Based on documentation at: https://github.com/Automattic/host-partner-documentation/blob/master/woocommerce/plan-register.md and our needs. 
We need to add support for the `products` parameter within the `WooCommerce_Host_Service` class. 

Additionally, there are multiple instances of `WooCommerce_Manager` are in place, where it is called conditionally based on plan slug. [class-transfer-manager.php#104](https://opengrok.a8c.com/source/xref/trunk/wp-content/lib/atomic/transfers/class-transfer-manager.php?r=231725#104) and [class-transfer-manager.php#203](https://opengrok.a8c.com/source/xref/trunk/wp-content/lib/atomic/transfers/class-transfer-manager.php?r=231725#203)

There are invocations on [class-transfer-manager.php#737](https://opengrok.a8c.com/source/xref/trunk/wp-content/lib/atomic/transfers/class-transfer-manager.php?r=231725#737) for cancellation of the plan and in [atomic.php#307](https://opengrok.a8c.com/source/xref/trunk/wp-content/admin-plugins/atomic.php?r=227393#307) for the primary domain change. 

We can make modifications within `WooCommerce_Manager` and `WooCommerce_Host_Service` to support the `products` parameter to register installations. 

I might be wrong but we need to take clarification from Woo team who can advise us if simply adding the `products` parameter would work or not. Which I think should work based on partner documentation.

**Comment by cpapazoglou** [comment]
How are we going to handle plugins that require a subscription key / license?
Can we use the fact that these plugins are "managed" so that we don't require subscription?

**Comment by cpapazoglou** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/60661
