### ISSUE TITLE
Subscriptions: Pending tab missing when subs are pending on the Subscription Management page.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#55590]
The Subscription Management page (subscribe.wordpress.com) should display a Pending tab when subs are, well, pending. I've tried subscribing to WordPress.org's Team Updates, and got the error that I have too many subs pending (https://make.wordpress.org/updates/?subscribe=many_pending_subs#blog_subscription-2) – but I have no Pending tab showing for my user.

| Form | Management |
| --- | --- |
| <img width="328" alt="Screen Shot 2021-08-18 at 7 24 07 AM" src="https://user-images.githubusercontent.com/349751/129918218-9d883233-431d-4fa9-8637-a99b8754f3b9.png"> | <img width="900" alt="Screen Shot 2021-08-18 at 7 37 04 AM" src="https://user-images.githubusercontent.com/349751/129918229-365b85e2-6da5-4d46-847e-ac3545c53425.png"> |

**Comment by kwight** [comment]
@andres-blanco Do I have this right? I've never actually seen the Pending tab myself. 🙃

**Comment by andres-blanco** [comment]
Here's a screenshot of the Pending tab on the wild:
![image](https://user-images.githubusercontent.com/375980/129921617-e3b5303d-0f69-4683-8a0b-809db019c0ed.png)

You can browse to this tab using this URL https://subscribe.wordpress.com/?option=pending

**Comment by kwight** [comment]
Hunh, and now it works fine. Not sure if I did something with a different email? ¯\_(ツ)_/¯ Closing.
