### ISSUE TITLE
View post should open post url in a tab

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#55599]
## Description
After user clicks to publish a post from the editor, then sees the "publish sidebar" , clicking "View post" should open in a new tab.  The UI with the "View post" button is shown in the image below.

### Current behavior
Clicking "View post" opens the post in the same tab. The problem with this is that the context of being in WordPress is poor: There's no way to go back unless you use the browser back button or fumble around in the top bar

### Suggested behavior
Clicking "View post" will open the post url in a new tab

![image](https://user-images.githubusercontent.com/5665959/129976359-12f4613c-663b-44f1-9d24-515e7d58f124.png)

## Dev tasks
- [ ] post should open in new tab

## Links
Prior slack discussion: p1629265049105900/1629261881.101300-slack-C029SB8JT8S

**Comment by arthur791004** [comment]
Currently, we can go back to edit the post via this **Edit** button but it will disappear when you scroll.
![image](https://user-images.githubusercontent.com/13596067/130940845-ace6953a-cb17-405d-bef3-f6daeeeda8aa.png)

Maybe we should also need to improve the experience

Related slack discussion: p1629736263249400-slack-C029SB8JT8S

**Comment by roo2** [comment]
also, when you use CMD+Click, I would expect the View Post button to open the post in a new tab, however it uses the existing tab.

This also affects the "View Post" link in the notification after updating the post 

<img width="246" alt="Screen Shot 2021-08-27 at 3 06 55 pm" src="https://user-images.githubusercontent.com/22446385/131074791-b447648b-5b6c-4daa-b50c-6006608cc931.png">

**Comment by p-jackson** [comment]
This behaviour is difficult to customise just for wpcom, so we should be looking at general Gutenberg fixes.

- #55785
- The view post link in the post settings sidebar opens a new tab, so the fact that it doesn't in the post-publish sidebar is inconsistent. The GB project might be interested in fixing this inconsistency

**Comment by autumnfjeld** [comment]
Good for new Ganonites. :)

**Comment by autumnfjeld** [comment]
@fushar I just went through the UX flow for this and this is the current state of the flow for an unlaunched site: 
![Screen Capture on 2022-02-11 at 10-41-42](https://user-images.githubusercontent.com/5665959/153515818-41b91573-8240-466e-ba2b-c2c461775c63.gif).
 We recently introduced the launch bar, which you can see adds functionality:
* the user has a "back button" in the UI, which leads to My Home 
* the user can choose Edit post to return to the editor

However this issue is about the fact that clicking "View Post" should open in a new tab.  If this needs to be a core-first solution, you could investigate if there are already open issues and if not you can open an issue in Gutenberg.

**Comment by fushar** [comment]
As #55785 is already fixed, users can already view the post in a new tab using the "correct workaround" by using cmd-click.

As this is not a blocker anymore, I think we should avoid custom hack in Calypso and push the "fix" in Gutenberg instead. Gutenberg already has an open issue around this:

- https://github.com/WordPress/gutenberg/issues/28599

I added a few more context as a comment on the above issue.
