### ISSUE TITLE
Themes: display theme details inside Calypso instead of redirecting to theme page

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#556]
Steps to reproduce:

1. Go to `/design` and pick your site.
2. Click on the three little dots next to a theme.
3. Click on Details.

I would expect a modal to pop up with more details about the theme. Instead, it loads a brand new page. When the site is a Jetpack site, it's even more confusing as one needs to log in before to access the theme detail page.

It would be nice if we could pull the theme's description and tags and display it in Calypso instead.

Suggested here:
http://wptavern.com/automattic-unveils-calypso-an-open-source-wordpress-desktop-application-for-the-mac

**Comment by folletto** [comment]
It's planned (that part is still on the old infrastructure). 
Upcoming in a future milestone. :)

**Comment by nylen** [comment]
Related - a link to the documentation on theme.wordpress.com would be nice to provide information about custom features the theme may have, like https://theme.wordpress.com/themes/sela/ and Testimonials.

**Comment by folletto** [comment]
That site is going to be retired. The upcoming design will address that too. :)
Testimonials will be removed in the v1 of the new showcase, but it's something to be re-evaluated later. :)

**Comment by ockham** [comment]
>>  information about custom features the theme may have, like https://theme.wordpress.com/themes/sela/ and Testimonials.

> Testimonials will be removed in the v1 of the new showcase, but it's something to be re-evaluated later.

Hm? I think @nylen meant the Sela theme having the custom feature of testimonial CPTs, right?

**Comment by folletto** [comment]
Ah sorry, I misread... I was thinking of User Sites ("Awesome blogs using").

So yeah, the new design has an area to list features. Not sure about CPTs, but we can factor that in. :)

It's a different request tho, currently tracked in: #3163
