### ISSUE TITLE
Help FAB contact form; search input visually broken

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#55608]
### Steps to reproduce the behavior

1. Open help FAB and click "contact us"
    <img width="336" alt="image" src="https://user-images.githubusercontent.com/87168/130072816-fb0e9914-453f-4c11-9c34-b5ff28e3cc57.png">

2. Click site name to change to another site, note how search input falls down

    <img width="353" alt="Screenshot 2021-08-19 at 16 00 08" src="https://user-images.githubusercontent.com/87168/130072719-e7e09e9d-0a08-4fa4-bdcf-655153bb95bc.png">

Hope it's not because of that Grammarly icon that appears there.

Using Firefox.

cc @razvanpapadopol

**Comment by imktho** [comment]
Hi there, mind if I look into this issue?

**Comment by alshakero** [comment]
Closing as fixed by https://github.com/Automattic/wp-calypso/pull/55930
