### ISSUE TITLE
Themes: Fix reconciliation errors

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#5560]
AFAICT, there are currently three reasons for reconciliation errors:

1. The `has-no-sidebar` class is determined by `sections.js`'s `secondary` field, which is either `true`, or `false`. However, `/design` can be used both when logged-in (with a sidebar), and logged-out (no sidebar). So this scheme is too rigid for our purpose. Related: #6950
2. `wp-singletree-layout` is a class only present on the server-side (introduced by #4992, see there for a rationale). Maybe we can use Redux state to convey this information instead. Related: #7000
3. We're stubbing components like `ThanksModal` on the server (in `webpack.node.config.js`). One solution could be to stub at a lower level (e.g. `Popover` or `Dialog`), or to make things SSR compatible (see e.g. #4072).

This issue supersedes #2299, which dealt with other reasons for reconc errors.

**Comment by lancewillett** [comment]
All the linked issues looked fixed now — closing this one. Feel free to re-open with smaller, more specific issues as needed.
