### ISSUE TITLE
[Simple Business Plan Only] Tags link exists under Pages

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#55605]
### Steps to Reproduce

1. Start at My Sites
2. Go to Pages
3. Go to Tags

This loads a wp-admin version of the Tags page, 

![menu](https://d.pr/i/Aw76uk+)
*Image link: https://d.pr/i/Aw76uk*

### What I expected to happen

The tag page currently exists under My Site → Posts → Tags for **ALL** plans. 

### What actually happened

Tags should not exist under the Pages sidebar menu

### Context

Testing and noticed it only on my SImple business site.

Does not show on any other plan, or .org site. 

### Operating System

macOS

### Browser

Chrome/Chromium

### Is this specific to applied theme? If so, what is the theme name?

Various themes where tested

### Simple/Atomic

Simple

**Comment by Greatdane** [comment]
There has been an ongoing discussion on if this is caused by certain themes, such as the Prosperity theme (themes that allow pages to become featured content). 

However, I tried various themes on simple/atomic Business sites and nothing seemed to change.

slack-p1629357981052400

**Comment by jordesign** [comment]
I'm unable to recreate this *except* for when using a theme with Featured Content (like Prosperity).  
@Greatdane are you still having this occur - and on more than one site?

**Comment by Greatdane** [comment]
I think we can close this out. Perhaps it was a caching issue on the dashboard. The link is no longer there under Pages.
