### ISSUE TITLE
Woo block Product Categories List not differentiating between Level3 and Level4 category in Hierarchy view

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#55601]
### Steps to Reproduce

1. Create 4 WooCommerce product categories, each one nested under the previous one created, like follows: 
 	- Level 1
		- Level 2
			- Level 3
				- Level 4
2. Add a product to the last category
3. To a page, add the block Product Categories List
4. Under the block settings > List settings > Display style, pick "Dropdown"
5. Again under the block settings > Content, switch On "Show hierarchy"
6. Save and view page

### What I expected to happen

To be able to see the hierarchy and distinguish between level 3 and level 4 As follows: https://d.pr/i/kMqhdc

### What actually happened

The hierarchy is clear between all levels except Level 3 and Level 4, Level 4 categories appear like Level 3, Like follows: https://d.pr/i/9bULee

### Context

zd-4227938
Test: https://mxhtestwoo.wpcomstaging.com/test-woo-product-categories-list/

### Operating System

macOS

### OS Version

10.15.7 (19H1217)

### Browser

Firefox

### Browser Version(s)

90.0.2

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

Complicated, I guess it can be customized with some JS code that searches for Select>Options that have a value containing four slashes after the /product-category/. But I didn't test that.

### Reproducibility

Consistent

**Comment by inaikem** [comment]
Transferring to `woocommerce/woocommerce-gutenberg-products-block` 

I was also able to reproduce on the following browsers (all macOS 11.3):

- Safari 14.1
- Firefox 90.0.2 + 91.0.1
- Chrome 92.0.4515.159

Safari screenshot:

![wc-blocks-dropbown-safari-14 1](https://user-images.githubusercontent.com/66711744/130552528-81d42ffc-bcd5-4cc1-9799-27e6061c0ec1.png)

**Comment by inaikem** [comment]
As a quick note on process here in GitHub, please embed images directly, as opposed to linking via Droplr, Cloudup, etc 🙏

(Internal thread for reference: pbg9X-fWF-p2)

**Comment by inaikem** [comment]
The related cross-repo issue has been closed!

https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4625
