### ISSUE TITLE
Consider Upgrades

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#55625]
A future concern is Woo upgrades. I _think_ we just need a clear plan here along with a clearly responsible party.

![WooCommerce_settings_‹_Jules_Aus_Test_eCommerce_—_WordPress](https://user-images.githubusercontent.com/5952255/130175158-176c6493-26c8-4c7f-84dd-6d8b6e4af9b6.jpg)

As an example picked at random, this upgrade updates all the subscription data for a woo site:
https://github.com/wp-premium/woocommerce-subscriptions/blob/master/includes/upgrades/class-wcs-upgrade-2-1.php
Running that on every WPCOM site is not a trivial task.

Schema changes also have additional performance concerns for for simple sites.

(From p9dueE-2pf-p2)

**Comment by lsl** [comment]
Atomic/core will handle this.
