### ISSUE TITLE
Playwright: Give each TeamCity agent its own user

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#55639]
### Details

We continue to look into ways to mitigate data isolation issues in our E2E tests, as discussed in issue #54992. 

One relatively low-effort and low-maintenance way to make a small improvement would be to give each TeamCity agent its own default user to use. This way, runs happening across multiple agents won't fight with each other.

### Checklist

Suggested approach
- [ ] Make 8 copies (one for each TeamCity agent) of the default user. (e2eflowtestingagent1, e2eflowtestingagent2, etc.)
- [ ] Make a library function (`getDefaultUser`?) that looks to see if an ENV variable is set to get that copy of the user, otherwise returns the regular default user (to be used in local runs)
- [ ] Update all the tests to use that wrapper function

**Comment by worldomonation** [comment]
Closing for now as it is unfeasible as per discussion we had with Sergio in a thread.
