### ISSUE TITLE
WP-admin Users Customer shipping address Name not updating 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#55645]
### Steps to reproduce the behavior

1. Go to 'wp-admin'
2. Click on 'Users'
3. Look at a User's Name
4. Under the username, click Edit 
5. Scroll down to  Customer shipping address and change First Name and Last Name, then save. 
6. Go back to Users > All Users 

#### What I expected to happen

The new first name and last name set will be displayed under Name in Users > All Users. 

#### What actually happened

The old name remained instead of the new one. Removing the First Name and Last Name and saving it still shows the old name, and going back to edit > Customer shipping address, the old name is auto-filled. 

#### Browser / OS version

Firefox 91, Mac OS 11.5.2

#### Is this specific to the applied theme? Which one?

No. 

#### Does this happen on simple or atomic sites or both?

Atomic only. 

#### Is there any console output or error text?

No. 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects all atomic sites. 

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

I was able to reproduce the same issue in my test site. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

All Users 

![Screen Shot on 2021-08-22 at 11:02:45](https://user-images.githubusercontent.com/36863633/130349175-84ba44de-7763-4995-8d70-a45b6bf2278f.png)

Edit > Customer billing address > add a new name `P... M...`  

<img width="360" alt="Screen Shot 2021-08-22 at 11 04 06" src="https://user-images.githubusercontent.com/36863633/130349237-09aad4b4-d119-4b17-b75f-feb9e70ad421.png">

Go back to Users > All Users, Name is still the old one (even the new name is added or completely removed): 

![Screen Shot on 2021-08-22 at 11:02:45](https://user-images.githubusercontent.com/36863633/130349175-84ba44de-7763-4995-8d70-a45b6bf2278f.png)

Ticket: 4239927-zen

**Comment by jartes** [comment]
Closing this one as this is now done via https://wordpress.com/me (My Profile in Calypso), as a fix was deployed in order to sync WPcom account info to the Atomic site: #46077

This reported case was followed-up on #4294566-zen.
