### ISSUE TITLE
Playwright: stand up task/infrastructure for WPCOM tests.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#55661]
### Details

The next big target for Playwright would be for WPCOM tests.

Currently the `trunk` [branch](https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_desktop?branch=%3Cdefault%3E&buildTypeTab=overview&mode=builds) in WPCOM Tests/Gutenberg tests doesn't appear very active with a lot of permanent failures.

Generally, it looks to be in worse shape than calypso e2e tests were at the beginning of the migration.

Do we want to migrate Gutenberg tests over to Playwright? If not, should existing tests either be disabled, run on a strict schedule, or something else? 

### Checklist

- [ ] Stand up a separate Playwright Gutenberg tests task.
    - [ ] desktop
    - [ ] mobile
- [ ] Migrate test specs over.

**Comment by worldomonation** [comment]
@dpasque @bsessions85

**Comment by fullofcaffeine** [comment]
> Currently the trunk branch in WPCOM Tests/Gutenberg tests doesn't appear very active with a lot of permanent failures.

We actually use it every week for GB upgrades, and make sure they are passing before we proceed with the upgrade. It's true that these are more prone to failures due to how Gutenberg intersects with many other areas of the WPCOM app, which is under constant development throughout the week. I think @Automattic/cylon keeps an eye on those tests, too.

**Comment by dpasque** [comment]
I definitely we should migrate these in Playwright!

In fact, I'm working on that right now as part of task #55715

What I'm doing right now is looking at all the `wpcom` specs from a high-level perspective, cross-comparing them with some of the already migrated `calypso` specs, and re-mapping the existing cases to remove some duplication and allow more granular execution.

I will have a P2 post sometime tomorrow with my proposed test plan map. @fullofcaffeine - it would be awesome to have your review on that test plan map as I know you added a lot of the original cases, and I want to make sure we maintain the right level of coverage in the transition!

**Comment by worldomonation** [comment]
This has been largely implemented and we are now in the test migration phase.
