### ISSUE TITLE
Customizer: re-add user guiding

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#55679]
### What
Let's add back the functionality to show Dotcom user guides in the Customizer. They were removed when fixing https://github.com/Automattic/wp-calypso/issues/55365

### Why
Our users need UI guidance on this screen.

### Context

> By customizer guide, do we mean the little blue edit pencils? Because they are now missing for the widgets. 
>
> This is causing some confusion for users, especially non-advanced. I believe many users accessed the widgets by clicking the blue edit pencils, and some do not know how to edit widgets otherwise. 
see: 4238136-zd-woothemes.

_Originally posted by @Greatdane in https://github.com/Automattic/wp-calypso/issues/55365#issuecomment-903469480_

### Screenshots
- Missing editing prompts from the preview. Shared by @roo2  
![image](https://user-images.githubusercontent.com/14192054/130586249-2d609313-5d83-4dd2-a89d-c0751b6581f9.png)

**Comment by razvanpapadopol** [comment]
A solution is currently WIP in D65828-code

**Comment by chriskmnds** [comment]
We can close this as it's been addressed by reverting D65402-code in D65686-code.
