### ISSUE TITLE
Sites: Suggestion for managing many sites — create folders or categories for sites

### ISSUE THREAD

**Issue by KienTrong** [Automattic/wp-calypso#557]
Is there a way to create a folder/category for our sites ( or maybe a search filed at the top of sites list )? because finding a site in the list of about 50 sites can be difficult.

Thanks.

**Comment by lancewillett** [comment]
There is a search function at the top of My Sites to sort many sites.

<img width="666" alt="screen shot 2015-11-23 at 13 25 24" src="https://cloud.githubusercontent.com/assets/66797/11348795/dc628c8a-91e5-11e5-8344-ecb7f1f4a443.png">

If you are connected to WordPress.com you can also hide/show certain sites from https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs.

<img width="823" alt="screen shot 2015-11-23 at 13 27 31" src="https://cloud.githubusercontent.com/assets/66797/11348814/fa45318a-91e5-11e5-86c5-d48de9213511.png">

> Is there a way to create a folder/category for our sites

We'll consider this for a future enhancement — thanks for asking.

**Comment by KienTrong** [comment]
Thank you and looking forward for folders/categories for sites :+1:

**Comment by mtias** [comment]
A related planned task for sorting sites: #375.
