### ISSUE TITLE
Plugins: Enable searching for plugins on Simple Sites with fewer or no clicks

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55706]
### What

Reduce the number of clicks required for searching for plugins on Simple Sites

### Why

On a Simple Site, searching for a plugin requires at least two clicks:
- Click the search icon on the right and it enables the text field for typing the query
- Click inside this text field to actually start typing

https://user-images.githubusercontent.com/39308239/130779262-6fd5318a-fe9f-4ef5-8455-fa53ef152764.mov

### How

Make the search text field in focus after one clicks the search icon. Ideally, don't require any clicks at all and allow searching as soon as one starts typing. Possibly get inspired by the macOS approach for this as described below.

**Inspiration:** macOS (at least BigSur) has this really nice feature at login screen where you don't need to actually click the text field to start typing the password. Instead, you can start typing right away since there is only one text field and there is no ambiguity. It felt like magic the first time I discovered this!

**Comment by Robertght** [comment]
I think this might be a quick adjustment.  Flow Patrol Manage / @sixhours can this be added to your inbox?

**Comment by dpasque** [comment]
Usually Flow Patrol Manage doesn't focus too much right now on feature requests, but this seems to be a blur between a bug and feature request, so adding tag and board to let them see!

**Comment by sixhours** [comment]
I definitely think we should auto-focus on the search input as soon as it opens; that feels like a bug that should be fixed at the component level.

**Comment by mreishus** [comment]
We've fixed the search component so it autofocuses upon opening. However, you'll still need to click the search icon.

**Comment by cpapazoglou** [comment]
I am closing this since we have popped out the search box in our new Plugins page

![SS 2021-11-22 at 15 56 20](https://user-images.githubusercontent.com/12430020/142874100-5943284d-fc44-4ba1-bef3-08777ed40745.png)
