### ISSUE TITLE
Load images on scroll in the media library instead of a Load More button.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#55712]
### What

Have more media load as you scroll on the media library, rather then use a load more button at the bottom.

### Why

It helps remove an extra click (or multiple clicks) and saves users time when adding old photos. This was requested here: 4227712-zen.

They said it used to be this way before the last WordPress.com update.

### How

Currently when you get to the bottom of the media library, you need to click this button to load more images: 
![Annotation on 2021-08-25 at 08-27-20](https://user-images.githubusercontent.com/49131029/130809994-4c9693a1-4bd8-4291-a6fc-3645eb436264.png)

Instead, they would like it more like Facebook infinite scroll. As you scroll down the images load automatically.

**Comment by jordesign** [comment]
Thanks for the report @KirkwallDay 

This is by design in WordPress 5.8 in order to make the media library more accessible.
https://core.trac.wordpress.org/ticket/40330

I don't imagine it is something that will be reverted - so I'm closing this request.
