### ISSUE TITLE
The site title font changes when changing the page. 

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#55714]
### Steps to Reproduce

When you change the page for a brief moment the site title is using a different font.
The font used was Montserrat, it also happened with other custom fonts. 

video: https://d.pr/v/JYtC5X

I was able to reproduce on my test site, both Atomic and Simple
video: https://d.pr/v/jKagPQ

Why is this happening and how do we stop it from happening?

### What I expected to happen

I expected the font to stay the same when opening a new page

### What actually happened

Instead of keeping the same font for a brief moment the font changed and then went back to the correct font. 

### Context

Chat: 31312349-hc
Follow up ticket: 4247822-zd

### Operating System

macOS

### OS Version

MAcOS BigSur 11.5.2

### Browser

Chrome/Chromium, Firefox, Safari

### Browser Version(s)

all up to date

### Is this specific to applied theme? If so, what is the theme name?

Ovation

### Simple/Atomic

Simple, Atomic

### Console and/or error logs

none

### Available Workarounds

I tried adding the custom font to Additional CSS but that didn't help. 

### Reproducibility

Consistent

**Comment by ckmccoy2** [comment]
For what it's worth, the user noted that the same momentary font change happens with the menu as well, which can be seen in the screen recording

**Comment by Robertght** [comment]
Thank you for reporting this @dolgelukkig !

I don't think this is a bug, but more like the standard FOUT effect: https://css-tricks.com/fout-foit-foft/

We have documented this internally p2-p2EDhh-fq#comment-1173
