### ISSUE TITLE
Playwright: [Meta] Migrate editor-related specs in specs/specs-wpcom

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#55715]
### Details

There are a lot of test specs in `specs/specs-wpcom` that still need to be migrated to Playwright. This task focuses on migrating editor and block related specs.

It makes sense to test plan map and migrate all the editor related tests together, and use this as a chance to simplify those tests and prune duplicates with other tests.

Then once we have everything together in the Playwright directory, we can work on making new suites and subdirectories with the logical groupings that make sense.

**Comment by worldomonation** [comment]
Project is complete.
