### ISSUE TITLE
Playwright: investigate viewport

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#55718]
### Details

Currently, the screen size for Playwright tests are set through a command line argument to the browser instance. 

Look into if a viewport can be used instead.

**Comment by worldomonation** [comment]
What I know so far:

- `--window-size=width, height` flag is only for Chromium and will not scale to other browsers.
- it appears the minimum width that can be specified by `--window-size` flag is 500px-15px=485ps.

**Comment by worldomonation** [comment]
It appears that this extra space that appears on the side when using the `viewport: {height: 1000, width: 400}` is due to constraints of Chromium, which does not allow window size less than 500px. This can easily be tested by launching normally installed Chrome/ium, then attempting to resize the width. It is not possible to be below 500px width.

Further, the `viewport` flag is set to `null` [here](https://github.com/Automattic/wp-calypso/blob/4b0978376a3e2df818cdc2adf1f82c9f8b2d69bd/packages/calypso-e2e/src/browser-manager.ts#L69) which means the viewport expands to fill the full width and height of the browser window, ending up at 500 - 15 (scrollbar) pixels.

This begs the question: do we want to:
- [ ] continue to simulate 400px wide viewport?
- [ ] update the mobile viewport size to 500px?

![Screen Shot 2021-08-26 at 3 23 16 PM](https://user-images.githubusercontent.com/6549265/131043876-7059042a-255e-44c8-9f6b-3f65e01ce23c.png)

**Comment by worldomonation** [comment]
Playwright offers a rich set of pre-defined `devices` which set the viewport, screen and user agent string among other features.

It is defined using JSON notation so it is also trivial to extract viewport size from the defined devices as well.

[link](https://github.com/microsoft/playwright/blob/1e8e54702327955be8d53abcbe6e13f1a884b277/src/server/deviceDescriptorsSource.json)

**Comment by worldomonation** [comment]
@WunderBart @dpasque What do you think of with what I've written so far?

I think we would be much better served by using one of Playwright's pre-defined devices, but first we'd need to get a sense of what would be a typical `mobile` and `desktop` resolution our users use. I've started a thread to obtain metrics - p1630021773003900-slack-C029GN3KD.

What do you think about this? I'm currently leaning towards using `iPhone 12` for mobile and `Chrome Desktop` for desktop.

**Comment by WunderBart** [comment]
> first we'd need to get a sense of what would be a typical `mobile` and `desktop` resolution our users use.

Good call! Let's see which viewports are the most used and then make a decision. 👍 

For what it's worth, [these seem to be the breakpoints we use in Calypso](https://github.com/WordPress/gutenberg/blob/807cac1dc98e4fc526d18a92f8b5978c8dc97619/packages/base-styles/_breakpoints.scss#L5-L13). Also, [these are the viewport resolutions](https://github.com/WordPress/gutenberg/blob/c5141c724879f5f27f2ffdd1162f0bb2dd406667/packages/e2e-test-utils/src/set-browser-viewport.js#L21-L32) Gutenberg is being currently tested at (although [I don't think](https://github.com/WordPress/gutenberg/blob/914f543e1e50d8c65c05a417efbdf539ef0d7a63/packages/e2e-tests/config/setup-test-framework.js#L71-L74) they're specifically running a "mobile" suite).

**Comment by dpasque** [comment]
>I think we would be much better served by using one of Playwright's pre-defined devices, but first we'd need to get a sense of what would be a typical mobile and desktop resolution our users use. 
> What do you think about this? I'm currently leaning towards using iPhone 12 for mobile and Chrome Desktop for desktop.

+1 to all of this! I think we should definitely use one of their devices, and we should base it on what the most popular ones are for using WordPress.com!

**Comment by worldomonation** [comment]
> For what it's worth, [these seem to be the breakpoints we use in Calypso](https://github.com/WordPress/gutenberg/blob/807cac1dc98e4fc526d18a92f8b5978c8dc97619/packages/base-styles/_breakpoints.scss#L5-L13). Also, [these are the viewport resolutions](https://github.com/WordPress/gutenberg/blob/c5141c724879f5f27f2ffdd1162f0bb2dd406667/packages/e2e-test-utils/src/set-browser-viewport.js#L21-L32) Gutenberg is being currently tested at (although [I don't think](https://github.com/WordPress/gutenberg/blob/914f543e1e50d8c65c05a417efbdf539ef0d7a63/packages/e2e-tests/config/setup-test-framework.js#L71-L74) they're specifically running a "mobile" suite).

Interesting, thanks for the links! TIL the technical term for this.

**Comment by worldomonation** [comment]
I got data from the Marketing team.

I won't post the screenshots here, but you can see it here: p1630021773003900-slack-C029GN3KD

It looks like for desktop, we have 1920x1080 taking narrow lead over 1366x768.
The screen resolution chart doesn't distinguish mobile, so I am going by guess here, but it would appear 414x896 is the largest share of mobile-esque resolution.

**Comment by worldomonation** [comment]
What this data shows us aside from resolution, is that we should test both Chrome and Safari to get the most coverage, and run tests with Windows where possible.

The Windows part is a tough issue to solve, though 😆
