### ISSUE TITLE
Exford and Alves themes do not respect full width column blocks in the editor.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#55726]
### Steps to Reproduce

1. Have a site on Exford or Alves and add a new page.
2. Make a new column block in the editor and make it full width.
3. The column will not expand to full width in the editor, in preview it will look fine, however.

I tested Exford and Alves, it's possible there are other themes affected by this as well.
Exford: 
<img width="1505" alt="Screen Shot on 2021-08-25 at 12-44-09" src="https://user-images.githubusercontent.com/49131029/130847601-881d4e87-affe-425d-93e4-3ce2f6e7bc6b.png">

Twenty TwentyOne (This theme does not show the issue):
<img width="1501" alt="Screen Shot on 2021-08-25 at 12-44-48" src="https://user-images.githubusercontent.com/49131029/130847664-a08ba67e-34f8-47c2-a951-afa06098681e.png">

Workarounds:
Use the Layout Grid block, this one works properly on both themes.

### What I expected to happen

Editor should show the column block contents at full width.

### What actually happened

The editor shows the column block contents at "Wide width" instead.

### Context

Customer reported here: #4233018-zen

### Operating System

macOS

### OS Version

Catelina

### Browser

Firefox

### Browser Version(s)

91

### Is this specific to applied theme? If so, what is the theme name?

Exford and Alves (Could be more)

### Simple/Atomic

Simple, Atomic

### Number of Users Impacted

All users

### Available Workarounds

Use the Layout Grid or use the "Preview in a New Tab" feature to see an accurate preview of the page or post.

### Reproducibility

Consistent

**Comment by jordesign** [comment]
Triaging this - it seems that this only happens when the Columns block is a single column. The block itself appears to be full width - but the text within it appears to have a max-width.

Also confirmed this coming from Varia - so affecting all Varia themes.

**Comment by jordesign** [comment]
Shifting this over to the Themes repo and closing in favour of https://github.com/Automattic/themes/issues/4473
