### ISSUE TITLE
Facebook Page Plugin Widget Displaying URL Configuration Error on AT Sites

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/wp-calypso#55735]
### Steps to Reproduce

1. Add the Facebook Page Plugin Widget to an AT site in any widget area
2. Use any Facebook Page URL. I used this one as an example: https://www.facebook.com/walmart/
3. You may see the widget as expected in the editor but view the page and you will see this message: `It looks like your Facebook URL is incorrectly configured. Please check it in your widget settings.`

Screenshot of setup:

<img width="717" alt="Screenshot on 2021-08-25 at 20-37-28" src="https://user-images.githubusercontent.com/5779512/130881904-195d649e-0d0f-4471-8b68-68dfa0901595.png">

Screenshot of message upon viewing the page:

<img width="453" alt="Screenshot on 2021-08-25 at 20-34-35" src="https://user-images.githubusercontent.com/5779512/130881932-66ba56e5-44c3-430d-bf8b-21f61b355172.png">

This only happens on AT sites. Does not seem to be theme specific. Works as expected on Simple Sites.

### What I expected to happen

I expected the widget to show with the Facebook page embed as per this guide: https://wordpress.com/support/facebook-integration/#facebook-page-widget but I saw an error instead

### What actually happened

Saw a URL configuration error which occurred with any Facebook Page URL: `It looks like your Facebook URL is incorrectly configured. Please check it in your widget settings.`

### Context

#4248501-zd

### Operating System

macOS

### OS Version

11.5.2 (20G95)

### Browser

Chrome/Chromium

### Browser Version(s)

92.0.4515.159 (Official Build) (x86_64)

### Simple/Atomic

Atomic

### Number of Users Impacted

All users

### Available Workarounds

I suggested using the Smashballoon plugin as an alternative

### Reproducibility

Consistent

**Comment by jordesign** [comment]
Triaged: It looks like this is related to the Block Editor. confirmed the behaviour when adding a Jetpack/FB widget within the block editor. However, the FB page widget loads correctly when loaded in the legacy/classic widget editor.

I've recreated this in a Jurassic Ninja site so the issue appears to be within Jetpack.
Closing this in favour of https://github.com/Automattic/jetpack/issues/20836
