### ISSUE TITLE
Billing History: Print Receipt displays onscreen items

### ISSUE THREAD

**Issue by kimerlin81** [Automattic/wp-calypso#55757]
### Steps to Reproduce

1. Start at **My Home**
2. Hover **Upgrades**
2. Click on **Purchases**
3. Click **Billing History**
4. Click **View Receipt** on any purchase listed.
5. Click **Print Receipt** at the bottom of the purchase details screen.

#4250230-zd

### What I expected to happen

Purchase details should print without the Billing Details description showing: **Use this field to add your billing information (eg. business address) before printing.**

### What actually happened

As shown in the attachment:

[Billing History.pdf](https://github.com/Automattic/wp-calypso/files/7060228/Billing.History.pdf)

**Use this field to add your billing information (eg. business address) before printing.** displays under the Billing Details section and should be hidden.

Also, if the textarea is left empty, it will show up on the printed version as seen in the attachment:

[2nd - Billing History.pdf](https://github.com/Automattic/wp-calypso/files/7060230/2nd.-.Billing.History.pdf)

### Context

This issue occurs for all users

### Operating System

macOS

### Browser

Chrome/Chromium

### Simple/Atomic

Simple, Atomic

### Number of Users Impacted

All users

### Reproducibility

Consistent

**Comment by Robertght** [comment]
Thank you for reporting this @kimerlin81 ! Adding to the Flow Patrol Manage inbox.

**Comment by mreishus** [comment]
#55867 is deployed; the helper text and the border for the field will no longer be displayed while printing.
