### ISSUE TITLE
Add feature flag that directs users to `site-setup` flow after checkout/free-plan selection

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#55784]
<img width="1766" alt="Untitled" src="https://user-images.githubusercontent.com/1500769/131079617-fd1bd8af-ca20-44e4-aae6-8180fce0e5a8.png">

We want to be able to demo the prototype of the flow that takes users from the checkout to the design picker and beyond (to My Home or the editor)

We can demo this with a feature flag like `/start?flags=signup/design-picker-after-checkout`
If the user uses this flag then after vising the checkout they are somehow taken back to the `/start/site-setup?siteSlug=<< the new site >>` flow, which contains the design picker.

**Comment by arthur791004** [comment]
We need to consider the following cases:
- The user closes the checkout from masterbar. See: `clickClose`
- The user removes all of cart items. See: `redirectDueToEmptyCart`
- The user completes the checkout. See: `useCreatePaymentCompleteCallback`
