### ISSUE TITLE
Customizer: Clicking the pencil icon next to widgets doesn't do anything and should navigate to the Widget section instead

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55788]
### Steps to Reproduce

1. Open Customizer 
2. Add at least one widget to any widget area
3. Click the pencil icon next to a widget

### What I expected to happen

Be redirected to Widgets subsection of the Customizer where I can actually edit the widget.

### What actually happened

Nothing happens

### Context

Manual testing

### Operating System

macOS

### OS Version

macOS BigSur 11.5.2

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Simple

### Available Workarounds

Navigate to Widgets section manually

### Reproducibility

Consistent

### Other information

https://user-images.githubusercontent.com/39308239/131108533-55a904df-5a30-4caa-90c5-96de8549fcba.mov

**Comment by jordesign** [comment]
Closing in favour of #55365
