### ISSUE TITLE
The `site-setup` flow's design step runs headstart on the selected site

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#55782]
The design picker introduced in #55741 doesn't do anything when a design is selected. It should run headstart on the site identified by the `siteSlug` query param and ensure it's homepage content matches the design.

Basically, after running the design picker step, the site should end up in the same state as if you'd gone through the `/new` flow and created a site with that design.

**Comment by arthur791004** [comment]
I think maybe we don't need to do anything for this one. As the new flow is the same as `with-design-picker` flow, it already has this feature. In the `DesignPicker` component, it would set the `selectedDesign` via `submitSignupStep` and the `selectedDesign` would be used in `getNewSiteParams` to get the params to create new site.

**Comment by arthur791004** [comment]
We can use the following API to run headstart
```
POST /rest/v1.1/sites/:site_id/themes/mine

dont_change_homepage: bool (default: false)
theme: string
```
