### ISSUE TITLE
Spike to investigate how "themes" can be shown in the design picker (as part of the `/start/site-setup` flow)

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#55781]
p1629756241264800/1629755538.259700-slack-C029SB8JT8S

Quoting @ianstewart 
>The designs in the design picker are a superset of the designs offered in the showcase created by applying alternate fonts and colours that don’t exist as themes in the showcase.
It’s a known issue for HEs as people keep wondering where Reynolds is or Vesta or Bowen. Seems likely to increase if the designs on offer in a picker aren’t 1:1 with the showcase.

#55741 created a prototype design picker. How might we show the themes from `/themes/{ siteSlug }` in the design picker?

- Maybe we just only show themes, reusing all the existing metadata from the theme gallery (e.g. static, untranslated thumbnails, etc.)
- Maybe we should create a "design" that maps 1:1 to each theme we want to have in the design picker. That way we can mix old themes in with new designs

**Comment by arthur791004** [comment]
Currently, the themes of the design step come from `available-designs-config.json` and the themes of `/themes/{ siteSlug }` page come from `/rest/v1.2/themes`.

If we want to display categories, we can use `/rest/v1.2/theme-filters` to get the list under the `subject` key and then query themes by specifying the subject as a filter. For example, we can query themes by `/rest/v1.2/themes?filter=portfolio` to get the themes with `portfolio` tag.

Here is part of the current subjects related to figma
* Blog
* Recommended (but list under the `feature` key
* Portfolio
* Business
* ~Entertainment~
* ~Culture~
* ~Travel~

**Comment by p-jackson** [comment]
Another approach we've discussed is to create a separate theme for each theme/layout/font/colours combination. This way choosing a design would be the same thing as choosing a theme.

**Comment by p-jackson** [comment]
Spike completed. It's possible to pass our own custom list of designs to the `<DesignPicker>` component.
