### ISSUE TITLE
Twenty Twenty-One: Footer credit cannot be changed on sites with site language set to Italian

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55790]
### Steps to Reproduce

1. Got to My Site → Settings → General → Language and set Italian as language
2. Navigate to My Site → Appearance → Customize → Site Identity → Footer Credit and try to change it

### What I expected to happen

See the selected footer credit

### What actually happened

Nothing happens. Footer remains `Con tecnologia WordPress.` where WordPress links to http://wordpress.org/ which should not be the case, but should be http://wordpress.com instead.

### Context

I checked the [translation strings](https://translate.wordpress.com/projects/wpcom/themes/twentytwentyone/it/default/) and cannot seem to spot if the issue is due to one of them.

Reported by the user in 4252368-zd-woothemes and brought up by the HC p1630053556053900-slack-CJDUN89L1

### Operating System

macOS

### OS Version

macOS BigSur 11.5.2

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

Yes, Twenty Twenty-One.

### Simple/Atomic

Simple

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

Set the site language to English

### Reproducibility

Consistent

### Other information

https://user-images.githubusercontent.com/39308239/131110993-0aee2d78-4598-4feb-b195-f6f6848bb5ca.mov

**Comment by Robertght** [comment]
Thank you for reporting this @zdenys ! It looks like it's all the same with other languages so I'm closing this in favor of this:

https://github.com/Automattic/themes/issues/3723
