### ISSUE TITLE
Themes: Cache markup only when logged-out

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#5580]
We're caching server-side rendered markup in an LRU with 1000 entries [here](https://github.com/Automattic/wp-calypso/blob/master/server/render/index.js). However, if we're caching individually for each logged-in user visiting a theme sheet page for a site of theirs (e.g. `/theme/themename/overview/example.wordpress.com`), we're going to fill up the cache quite rapidly.

I think logically, it'd make most sense to add a check to only cache markup if no user is logged-in, because those are the pages that are going to be re-used the most.

(We also discussed making site not part of the key, but I think differentiating based on logged-in vs logged-out is the more generic solution that could also apply to other sections wanting to cache markup.)

**Comment by seear** [comment]
We should turn off server-side rendering completely for logged-in users, at least until we can do i18n properly on the server. See the flash of English for French UI here:

![lang_flash](https://cloud.githubusercontent.com/assets/7767559/15603677/048b41de-23f4-11e6-8c71-de99232d2787.gif)
