### ISSUE TITLE
Feedback Button issue in Block Editor and Block Widget Editor

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#55808]
### Steps to Reproduce

1. Add a Feedback Button to widget area from Customise > Widgets
2. Add a Feedback Button to a page using the Block Editor

### What I expected to happen

1) In the widget editor, I expected to be able to edit settings for the Feedback Button, including the text of the button itself and other settings.

2) In the Block Editor on a page, I expected to be able to edit the settings of the button and remove the button from the page using the Block Editor

### What actually happened

1. In the widget editor the Feedback Button does not appear in the list of widgets as expected but, rather, shows at the bottom of the list and is partially hidden. It shows 'this block has encountered an error and cannot be previewed'. The settings of the block cannot be changed, neither can the text showing on the button.

<img width="453" alt="Screenshot on 2021-08-28 at 11-18-02" src="https://user-images.githubusercontent.com/76757079/131222693-e3a4fe80-a323-45b2-9f9f-a89702a260bf.png">

2. In the Block Editor, I expect to be able to change settings on the Feedback Button. I also expect to be able to remove it from the site in the Block Editor. Instead, I can only change the text on the button itself and can only delete it from the code editor.

![Screen Capture on 2021-08-28 at 11-22-20](https://user-images.githubusercontent.com/76757079/131222885-0a32a165-d8c3-4991-93ca-6ec4cc48b4de.gif)

### Context

Reported here 4248570-zd-woothemes indirectly

I thought perhaps the issue in the Block Editor was related to already having a Feedback Button in the Widget area but the issue persisted when I added a button only to the Block Editor.

### Operating System

macOS

### OS Version

11.5.1

### Browser

Chrome/Chromium

### Browser Version(s)

92.0.4515.131 

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Simple

### Available Workarounds

I could delete the Feedback Button in block editor from the code editor, but this does not affect being unable to change settings. 

### Reproducibility

Consistent

**Comment by Greatdane** [comment]
I was able to replicate this error on the widget editor (simple and atomic), but not on the block editor.

**Comment by dpasque** [comment]
Not sure if this related to something wrong in the block widget editor, or the block itself. If it's the block itself, it might be worth moving to https://github.com/Automattic/crowdsignal-forms.

Tagging @Automattic/flow-patrol-create based on issue content.

**Comment by simison** [comment]
Team @Automattic/crowdsignal hi, could you have a look at this one?

**Comment by ice9js** [comment]
I gave it a spin and can confirm the widget editor issue but also wasn't able to reproduce the second one with the block editor.

In case of the customizer, the block doesn't recognize the sidebar widgets editor and it's trying to display its regular 'button' version. To fix it, we'll need to update [this check](https://github.com/Automattic/crowdsignal-forms/blob/master/client/blocks/feedback/util.js#L23).  
If anyone has any suggestions for what I can add there (or maybe in Calypso?) to have a somewhat stable support for the Customizer, that would be appreciated.  
I'm almost certain it'll break again rather soon if I just grab a random class name so I'd like to avoid that if I can, but it is an option if it has to be.

**Comment by yansern** [comment]
> In case of the customizer, the block doesn't recognize the sidebar widgets editor and it's trying to display its regular 'button' version. To fix it, we'll need to update [this check](https://github.com/Automattic/crowdsignal-forms/blob/master/client/blocks/feedback/util.js#L23).
If anyone has any suggestions for what I can add there (or maybe in Calypso?) to have a somewhat stable support for the Customizer, that would be appreciated.

I noticed the existence of the `core/customize-widgets` store when Widgets Editor is loaded.

I verified this by running `wp.data.select('core/customize-widgets')` on a normal block editor, widgets editor on customizer, and a site running the classic widget editor and I can confirm that the store only exists when widgets editor is loaded.

Not sure if this is the official way to test if a block is running on widgets editor, but this could work.

Either this:
```
const isWidgetsEditor = !!wp.data.select('core/customize-widgets');
```

Or this:

```
import { select } from `@wordpress/data`;
const isWidgetsEditor = !!select('core/customize-widgets');
```

**Comment by yansern** [comment]
@noisysocks suggested `const isWidgetsEditor = !! window.wp.widgets;`.
p1631602799044000/1631602105.043300-slack-C029HCKPXP0

**Comment by sajmes** [comment]
Confirming that I can also no longer replicate the issue with the Feedback Button in the editor, even when loading the page where I originally tested the issue.
