### ISSUE TITLE
Atomic: display name not synced with WordPress.com, no longer changeable in WP Admin

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/wp-calypso#55813]
### Steps to Reproduce

On an Atomic site, attempt to change your display name by accessing the WP Admin > Users > Edit process. You'll need to switch screen view on the Users page, and Profile consistently takes you to https://wordpress.com/me/ instead either way. 

### What I expected to happen

You should: 

- either be able to edit your display name, as you used to be able to; or
- your posts' display name should be your WordPress.com display name

### What actually happened

In this user interaction, the display name was an old one, synced from WordPress.com long before a rebranding, despite the Calypso display name being changed. I could find no way to direct them to update it. 

### Context

Working on 23942972-hc, I had to change the user's display_name field in CLI. 

### Operating System

Windows, macOS, Linux

### Browser

Chrome/Chromium, Firefox, Microsoft Edge, Safari

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

Users would have to come into chat to have us set it via CLI.

**Comment by jordesign** [comment]
Closing this in favour of https://github.com/Automattic/wp-calypso/issues/46077 (which I will keep an eye on)
