### ISSUE TITLE
Block Editor Widgets: Blog Posts block displaying post full contents despite "Display Excerpt" is active

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#55810]
### Steps to Reproduce

1. On Customizer > Widgets, make sure the widgets area is using Block Editor

2. Add Blog Posts block on the widget area

3. Notice how the Blog Posts block should display post excerpts

![Screenshot 2021-08-29 at 10 17 09 AM](https://user-images.githubusercontent.com/44726232/131236689-94316afa-a7f0-4917-be81-09ae92a41e5b.png)

4. Also, noticed the expected display on Customizer

![Screenshot 2021-08-29 at 10 17 58 AM](https://user-images.githubusercontent.com/44726232/131236702-0e863f17-6da5-4f67-abeb-73ad2b0c9d29.png)

### What I expected to happen

I expected to see the posts displayed via Blog Posts block just like how it's displayed on Customizer. The post with excerpt.

### What actually happened

Somehow, the Blog Posts block widget displays the post in full. Causing design issue.

![screencapture-judetullochartist-category-what-im-doing-now-2021-08-29-10_19_20](https://user-images.githubusercontent.com/44726232/131236723-545d3bdb-5d71-4f8f-93da-bc40865a9532.png)

### Context

User report

### Operating System

Windows, macOS, Linux, Android, iOS

### Browser

Chrome/Chromium, Firefox, Microsoft Edge, Microsoft Edge (legacy), Safari

### Simple/Atomic

Simple

### Number of Users Impacted

One user

### Available Workarounds

Since the goal/idea is to display latest posts, I suggested the user to use Latest Posts block

### Reproducibility

Consistent

**Comment by inaikem** [comment]
Thanks for reporting this, Retno! I can replicate part of this issue: excerpt length is not respected by the Blog Posts Block when a excerpt is manually set.

Example:

![Markup on 2021-09-08 at 17:54:29](https://user-images.githubusercontent.com/66711744/132488390-1a919122-c135-4de4-9fc7-a66a0d8c9df1.png)

The above screenshot shows the excerpt length set to 10 words. When a manual excerpt is set in the block editor, the excerpt length will not change regardless of if the excerpt length in the block is set to 10 or 100 words.

I was not able to replicate the entire post content showing, however.

Can you please check to see if you can replicate the issue on the site above and reopen this issue as needed?
