### ISSUE TITLE
eCommerce Plan – WooCommerce > Coupons doesn't load

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#55825]
### Steps to Reproduce

Go to WooCommerce > Coupons

### What I expected to happen

Get redirected to https://ecommercemaywood.wpcomstaging.com/wp-admin/edit.php?post_type=shop_coupon

![image](https://user-images.githubusercontent.com/15944096/131311491-7af4d2a9-e414-40e8-982e-ee7e82e55c90.png)

### What actually happened

Error message `Sorry, you are not allowed to access this page.`

Redirected to https://ecommercemaywood.wpcomstaging.com/wp-admin/admin.php?page=coupons-moved&return=https%3A%2F%2Fwordpress.com%2Fhome%2Fecommercemaywood.wpcomstaging.com

![troubleshooting](https://user-images.githubusercontent.com/15944096/131311053-bd640cba-8e15-4d12-bfdb-cdca4c54e6b4.gif)

### Available Workarounds

Go to **WooCommerce -> Settings -> Advanced -> Features**, then uncheck `Navigation` option
![image](https://user-images.githubusercontent.com/15944096/132079940-e20b007a-31cb-4dc8-8bf7-60dd30e4c621.png)

### Context

31185650-hc (no follow-up needed)

**Comment by dpasque** [comment]
For Flow Manage folks - is this an issue with navigation on WordPress.com? If it's a bug specific to Woo, I will then move this to the Woo repo!

**Comment by mreishus** [comment]
* Url that does not load: `/wp-admin/admin.php?page=coupons-moved`
* Url that does load: `/wp-admin/edit.php?post_type=shop_coupon`

@dpasque I'm not 100% sure, but after an initial investigation I'm leaning towards this being a woocommerce issue. I'm seeing the code for adding this menu item and handling where it goes to located here: `woocommerce-admin/src/Features/Coupons.php` and `woocommerce-admin/src/Features/CouponsMovedTrait.php`, which belongs to the woo repo.

**Comment by dpasque** [comment]
Based on investigation, this has been transferred to the woocommerce/woocommerce-admin repo here: https://github.com/woocommerce/woocommerce-admin/issues/7603

Closing this issue in this repo for now!

@formosattic @mreishus
