### ISSUE TITLE
 WooCommerce alters theme customizations, site display

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#55822]
WooCommerce Core issue tracked at https://github.com/woocommerce/woocommerce/issues/29996

Let's use this thread to gather WordPress.com user reports.

User reports:

* 31322225-hc – After going through the WooCommerce setup, the theme (Storefront) was no longer displaying as expected. For example, the header and footer areas are missing.
* 31093495-hc – The homepage was changed after installing WooCommerce
* 30376001-hc – The homepage was changed, as were the custom colors.

Also mentioned in p9F6qB-76b-p2

**Comment by katiebethbrown** [comment]
There is also an issue for this in the Woo repo:

https://github.com/woocommerce/woocommerce/issues/29996

**Comment by dpasque** [comment]
@formosattic It looks like folks are adding user reports right directly on the Woo issue - I'm going to close this issue for now to avoid any confusion or missing reports on that issue! 

Folks should still be able to find this issue to find the link to the Woo one.

Please let me know if you have any concerns with that and we can re-open!

**Comment by dpasque** [comment]
Closing - please see and comment on Woo issue: woocommerce/woocommerce#29996

**Comment by dpasque** [comment]
@formosattic Actually, winding that back, sorry, I can now see how closing this now might be confusing as folks are trying to track and follow this!

For folks monitoring the Triage Queue for fixes, you can ignore this issue, as it is being tracked and fixed in the Woo repo!

Also, if folks have new user reports, it would probably be best to add those directly to the Woo issue.

**Comment by dev-sabbir** [comment]
Another case here: 5420155-zd-woothemes

**Comment by csabarakasz** [comment]
Same issue here

- [ ] 36046401-hc

The shop page was set to home page automatically and the original home page was renamed to untitled.

**Comment by cometgrrl** [comment]
Linked woocommerce issue has been resolved.
