### ISSUE TITLE
Subscriptions Emails: new "Confirm Follow" email template

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#55835]
Apply the new template to the `Confirm Follow` email.

This is the current template:
![image](https://user-images.githubusercontent.com/375980/131357596-080b96a4-eed8-4481-ac97-581482a99f5c.png)

This is what we aim for:
![image](https://user-images.githubusercontent.com/375980/131357728-ce6ae4e5-4552-41cf-b2ab-6e4cf4f31c3f.png)

The new design is based on the P2 emails so those can be used for reference. The P2 templates can be found here: `wp-content/mu-plugins/html-emails/themes/wp-for-teams/html`

@saygunnyc feel free to drop any design reference you think is important like:
 * specific colors
 * link to the icons that should be used

**Comment by saygunnyc** [comment]
Sharing the latest with the updated copy over here. @provenself 

<img width="1281" alt="Emails" src="https://user-images.githubusercontent.com/78876323/131698675-a8ebf2a2-42d7-4f85-98f7-6dd22a1f2428.png">

____

Uploading the SVGs for branding. 

[SVGs.zip](https://github.com/Automattic/wp-calypso/files/7092397/SVGs.zip)

____

Sharing colors here for visibility.

<img width="882" alt="Colors" src="https://user-images.githubusercontent.com/78876323/131699228-ba66207a-cd21-43e2-84f8-eb4ce31a881e.png">

Details can be found over this Figma file. – crtNho9opJSnM80QsE275F-fi-514%3A1044

**Comment by andres-blanco** [comment]
being worked on ~D66119-code~ D66481-code

**Comment by andres-blanco** [comment]
closed in D66774-code
