### ISSUE TITLE
Subscriptions Email: Define wording for the Confirm Follow template

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#55838]
We should define the wording we want to get in our new Confirm Follow template.

This is what we have now:
![image](https://user-images.githubusercontent.com/375980/131379406-8fffc050-04fc-402d-a10e-497cf8187713.png)

**Comment by saygunnyc** [comment]
Sharing this over here for the latest copy reference.


<img width="1281" alt="Emails" src="https://user-images.githubusercontent.com/78876323/131699849-bcdcb629-ca9c-4ca8-ab4b-7de28fabc13b.png">




@provenself and I might have found a way to unblock us from the follow/subscription language challenge over the emails, leaning towards using the words “updates” and “settings”.
Updated copy for the 3 initial emails can be seen over here, crtNho9opJSnM80QsE275F-fi-514%3A1044
We still would need to see if this can be applied to all the emails – looks promising so far. But let us know your thoughts!

> This doesn’t get us around the follow/subscribe language issue entirely, but it lets the email refresh move forward while the bigger gnarlier problem gets hashed out!

by @provenself

**Comment by andres-blanco** [comment]
the Confirm Follow Template is implemented in this diff: D66468-code, once that is merged I will close this issue.

**Comment by andres-blanco** [comment]
Merged D66481-code
