### ISSUE TITLE
Full Site Editing on Dotcom: Remove the edge sticker

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#55861]
Sites created through the Horizon FSE flow, and eventually through the Beta flow, are currently provided a `gutenberg-edge` sticker which loads the most bleeding-edge version of the Gutenberg plugin.

This has been valuable during the development, as all Core Gutenberg fixes would show up on Dotcom almost immediately, but we have also seen a lot of breakages caused by using an unstable version of the plugin.

For this reason, we should not use `gutenberg-edge` on production sites, even if in Beta.
Let's stop adding the sticker on FSE Beta sites once we are closer to the rollout.

**Comment by Copons** [comment]
It will be fixed by D66082-code (already approved).

**Comment by vindl** [comment]
@Addison-Stavlo I think we can deploy this diff at this point?

**Comment by Addison-Stavlo** [comment]
deployed!
