### ISSUE TITLE
Customizer: Block Widgets: Changing settings causes active section to change

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#55875]
### Steps to reproduce the behavior

1. Visit the customizer of a simple site (Apperance -> Customize)
2. Click on 'Widgets'
2. If applicable to your theme, choose an area like 'Sidebar' or 'Footer'
3. Click inside a block widget, (or add a simple paragraph block if you don't have one and click in it)
4. Click on the 3 dot menu in the floating Gutenberg toolbar
5. Click "Show more settings"
6. Change any of the settings displayed in this sidebar. For example, change the font size, or turn on "Drop Cap."

#### What I expected to happen

7. The change is made and you stay on the "Show more settings" sidebar section you are on.

#### What actually happened

8. The change is made and the active sidebar section 

#### Videos

https://user-images.githubusercontent.com/937354/131564385-0dca2f21-0be5-42e9-88f2-657ba062f2c0.mp4

^ Unexpected behavior on .com simple site - After changing setting, the sidebar display returns to the block

https://user-images.githubusercontent.com/937354/131564366-b52f34b6-f8dc-417c-83dd-fe39f2fc32d6.mp4

^ Expected behavior on core .org only - After changing setting, the sidebar remains on the settings page

### Location of bug

I believe this is an interaction between .com and .org code. [If these lines of code in .org are commented out](https://github.com/WordPress/wordpress-develop/blame/d4abd5ca4a500f7b704c59d7a03ac1c583fde6a3/src/js/_enqueues/wp/customize/controls.js#L7199-L7206), the undesired behavior no longer happens. However, the bug does not happen on a standalone .org site. I believe .com has an autosave plugin which may be causing this behavior. Changing the setting causes this trigger to fire: the `api.state( 'saved' ).bind( updateSectionActive );`, and `updateSectionActive` moves the sidebar away from the settings page and to the block you were editing.

**Comment by mreishus** [comment]
This is theme dependent.

* Twentyninteen, twentytwenty, twentytwentyone - Only the first change sends you back to the block
* Independent Publisher 2, Sapor - All changes send you back to the block


https://user-images.githubusercontent.com/937354/131748646-1706cc09-326f-4809-a1db-35a530d24bd9.mp4

^ Independent Publisher 2 example

**Comment by mreishus** [comment]
I was able to reproduce this using WP.org only. I downloaded the gutenberg repo and ran `wp-env destroy && wp-env start`, then logged into http://localhost:8888/wp-admin/ with `admin:password` before recording this video:

https://user-images.githubusercontent.com/937354/131900785-c9f3e678-349d-43fa-9862-ba712740ed03.mp4

On .org, I needed to publish once before the error happened, and it only happens on the first change.

**Comment by mreishus** [comment]
Reported on wp.org trac: https://core.trac.wordpress.org/ticket/54063

**Comment by mreishus** [comment]
The per-theme behavior is dependent upon `add_theme_support( 'customize-selective-refresh-widgets' );`. When the active theme doesn't' support this, we see you're kicked out of the block settings more often.

* Core using 20s theme: When publish button goes OFF -> ON, you're kicked out of block settings.
* Any theme without customize-selective-refresh-widgets: Also, when publish button goes ON->ON, you're kicked out of block settings

**Comment by mreishus** [comment]
Here's the code that's running (at least for case 1 in the 2020s)
https://github.com/WordPress/wordpress-develop/blob/40edc2addb5284804e698beda487206f8dd70992/src/js/_enqueues/wp/customize/controls.js#L1148-L1153
active is false, and construct looks to be the block settings section.. so something is explicitly telling this section to deactivate, I'm just not sure what it is yet
![2021-09-02_16-08](https://user-images.githubusercontent.com/937354/131916658-651b3fcc-c93b-4f2f-a37a-a57439db86c8.png)

**Comment by mreishus** [comment]
Got a step closer. When the customizer reflows, each section reinits and figures out if it should be active. It uses an incoming "active" variable but also wants to make sure the area "is contextually active".
https://github.com/WordPress/wordpress-develop/blob/40edc2addb5284804e698beda487206f8dd70992/src/js/_enqueues/wp/customize/controls.js#L999
In the case of the block settings section, it thinks that it is active, but the is contextually active returns false, so it becomes inactive and collapses.
The default definition of isContextuallyActive for a section, looks for controls in that section, then checks to make sure at least one is active.
https://github.com/WordPress/wordpress-develop/blob/40edc2addb5284804e698beda487206f8dd70992/src/js/_enqueues/wp/customize/controls.js#L1559-L1569
In the case of the block settings, it doesn't find any controls, so this section fails. This is probably because the block settings section is coming from Gutenberg, and this is a missing part of the integration; it doesn't recognize any of the controls in Gutenberg.
so the step forward is to find out how to override isContextuallyActive for the block controls section, which might mean a PR to Gutenberg; it's possibly being added somewhere in the 'package/customize-widgets' or 'package/edit-widgets' directories in G

**Comment by mreishus** [comment]
Created Gutenberg PR: https://github.com/WordPress/gutenberg/pull/34543

**Comment by sixhours** [comment]
Since WordPress/gutenberg#34543 has been merged, I'm marking this as closed. :)
