### ISSUE TITLE
Video Widgets: Not displaying on certain pages

### ISSUE THREAD

**Issue by sbathompson-he** [Automattic/wp-calypso#55877]
### Steps to Reproduce

1. Visiting the home and about pages, one sees that the videos on the sidebar widget don't display
2. Going to the users Customizer, the videos do show and play on all pages

### What I expected to happen

All videos should show on all pages at all times

### What actually happened

They only show on 4 out of the 6 pages

### Context

Video attached

https://user-images.githubusercontent.com/77308634/131590840-c8e8dc57-e311-4fe8-906d-28a375b7a5ec.mp4

### Operating System

macOS

### Browser

Firefox

### Simple/Atomic

Simple

**Comment by Robertght** [comment]
@sbathompson-he Thank you for reporting this!

I've got a few questions:
- Is this happening on a user's site? If yes, could you share the ticket/chat ID with us?
- Also, are there any browser console errors?
- Are the videos coming from the same source?

**Comment by Robertght** [comment]
I'm marking this as duplicate in favor of https://github.com/Automattic/wp-calypso/issues/55696#issuecomment-911587948
