### ISSUE TITLE
Reader comments: "view earlier comments" does not load all top-level comments

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#5587]
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/read/feeds/40474296/posts/999143144
2. Click "view earlier comments" twice

The original post for comparison is https://futonbleu.wordpress.com/2016/04/18/comment-test/.

#### What I expected

All top-level comments are displayed. 

#### What happened instead

The initial view shows three of four top-level comments.

After clicking "view earlier comments" twice, only two of four top level comments are displayed.

#### Screenshot / Video

<img width="696" alt="screen shot 2016-05-25 at 12 50 40" src="https://cloud.githubusercontent.com/assets/17325/15552391/53ca63ac-2277-11e6-97ac-af4582ca47a2.png">

**Comment by blowery** [comment]
@yurynix any chance you can take a peek at this?

**Comment by yurynix** [comment]
Sure thing. Will check it out at the morning.
