### ISSUE TITLE
Crowdsignal block cutting off poll

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#55887]
### Steps to Reproduce

1. Add crowdsignal block to page
2. add longish content
3. try to skip a required answer and see content pushed down and inaccessible

### What I expected to happen

either the content should resize or the iframe should 

### What actually happened

the content just gets clipped and can't be accessed

![2021-09-01 at 10 57](https://user-images.githubusercontent.com/47717887/131634848-97217352-9307-4dd8-8e58-74caff83b645.jpg)
![image](https://user-images.githubusercontent.com/47717887/131634862-82eec19e-c4bb-44d4-9124-523b03008321.png)

### Context

4258686-zd-woothemes

### Operating System

macOS

### Browser

Chrome/Chromium

### Is this specific to applied theme? If so, what is the theme name?

no

### Simple/Atomic

Simple

### Available Workarounds

can just embed link from another service

### Reproducibility

Consistent

**Comment by Robertght** [comment]
Thank you for reporting this @Nic-Sevic ! 


I'm not able to replicate this for now. I have tried using the same theme in the process as well, but no dice.

Would there be any additional details that you could share with us?

**Comment by synora** [comment]
Triaged. I'm unable to replicate this as well. I'll close this issue for now but feel free to open if it happens again. 


![Screen Capture on 2021-09-14 at 13-37-33](https://user-images.githubusercontent.com/10015451/133306792-41da6a21-2545-4b18-a75d-fe4e1cc33d12.gif)
