### ISSUE TITLE
The blog preview not showing when embedding WordPress blog links

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#55888]
### Steps to Reproduce

1. On the page editor, paste the link to a post. URL: https://vietnamhoonist.com/2021/08/31/tong-hop-tin-tuc-thang-8-2021/ It doesn't unfurl, but only shows a link that is embedded without any preview on the editor.
2. When previewing the page, it doesn't show the preview of the post shared, it only shows a link.
3. Shared another link from the same site on the editor, it unfurls and shows the preview. 
4. When previewing the page on the front end, it doesn't show the preview on the front end.
5. Checked by pasting link from another blog (simple as well as an atomic site), it unfurls in the editor as well as on the front end.

https://user-images.githubusercontent.com/7382505/131634569-e8797d6e-b862-4f4d-a5ff-4ffc83cc7238.mp4

### What I expected to happen

When any link is pasted on the editor, it should unfurl and show on the front end.

### What actually happened

Some links from the site unfurl on the editor but never on the front end.

### Context

Customer report

### Operating System

Windows, macOS

### Browser

Chrome/Chromium

### Simple/Atomic

Simple

### Console and/or error logs

No errors in the console

### Number of Users Impacted

One user

### Reproducibility

Consistent

### Other information

I'm able to replicate the issue when sharing the links from the user's site. 
Slack: p1630417859035100-slack-C7YPUHBB2 & p1630391925482000-slack-C03TY6J1A
Chat: 31410986-hc
Follow up ticket: 4261160-zen
User's site: http://vietnamhoonist.wordpress.com
Test post where I checked: p95aOX-yD-p2

**Comment by kosiew** [comment]
Hi @galakhyati ,

Thanks for reporting this and the detailed steps.

https://github.com/WordPress/gutenberg/issues/32689 says that internal links should show preview too.

**Comment by kosiew** [comment]
As I could also reproduce on a Jurassic Ninja site, I filed a Gutenberg issue - https://github.com/WordPress/gutenberg/issues/34676

Closing this in favour to https://github.com/WordPress/gutenberg/issues/34676

**Comment by jordesign** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/56279
