### ISSUE TITLE
Sela: Clicking on Widget Edit Icons in Customizer Preview Does Not Open Widgets For Editing

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#55881]
### Steps to Reproduce

1. Open the Customizer
2. In the preview pane, click on a blue pencil icon to edit a widget.

### What I expected to happen

The widget to open in the sidebar for editing.

### What actually happened

Nothing at all. Clicking the pencil/edit icons on widgets has no effect. There are no console errors reported.

GIF:
![widgeteditbuttons](https://user-images.githubusercontent.com/42279181/131606702-28d0f050-f501-4c09-99d5-55868bcf1fcf.gif)

### Context

User Report - 4257834-zd-woothemes

### Operating System

Windows, macOS, Linux, Android, iOS

### Browser

Firefox

### Is this specific to applied theme? If so, what is the theme name?

Sela

### Simple/Atomic

Simple

### Console and/or error logs

None.

### Available Workarounds

Manually navigate through the panels the Customizer to the widget areas to edit them.

### Reproducibility

Consistent

**Comment by kosiew** [comment]
Hi @katiebethbrown ,

Thanks for reporting this and the detailed steps.

I could reproduce this on a Simple site.

In addition, I also tested this on AT site and it works per expectation.

![Screenshot](https://d.pr/i/QALjtX+)
*if image does not load, please click on this link  : https://d.pr/i/QALjtX*

Triaging for developers' further investigation.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content.

**Comment by katiebethbrown** [comment]
Looks like this may be related to https://github.com/Automattic/wp-calypso/issues/55365

**Comment by yansern** [comment]
Fixed in: https://github.com/Automattic/customize-direct-manipulation/pull/53
