### ISSUE TITLE
Marketplace: Universal feature flag(s) for Simple, Atomic

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#55894]
### Details

Since we are going to be changing the left navigation menu, we will need a feature flag or blog sticker that can work in Simple & Atomic context.

We can explore using the jetpack xmlrpc response as we did with nav-unification 
wpcomsh/blob/ece3b6846da967cdab077fc581df6a5665f20068/feature-plugins/masterbar.php#L142

**Comment by tjcafferkey** [comment]
@lsl am I correct in thinking this was a problem you were looking into (feature flags/toggles on Atomic)?

Interested to know if you came up with a solution/made any progress around this?

**Comment by lsl** [comment]
@tjcafferkey I was just reading this hoping it might solve my problem :smile:. Looks like the jetpack/wpcomsh thing linked above is for user data not site data, this might work for you or maybe you can add site data in the same way?

I'm looking at syncing site stickers through persistent data but haven't got to it yet. (was looking at starting into it either tomorrow or Monday depending what happens with p9o2xV-1Bd-p2)

Tracking in #55738 it has links to some background / chatting with @apokalyptik & @brandonpayton (cc in case this using the jetpack connection to sync site stickers is a better option than persistent data)

**Comment by cpapazoglou** [comment]
Related patch D66393-code

**Comment by lsl** [comment]
^ now replaced by D66496-code
