### ISSUE TITLE
My Home: `Visit site` button should open the site in a new tab

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55896]
### What

Make  `Visit site` open in a new tab as other support links

### Why

Links in My Home section either open in a modal window or in a new tab. This helps keep the main dashboard view always active without switching context. 

In contrast, `Visit site` button at top right opens the site in the same tab. For a new user it may be unclear how to go back to the dashboard. 

Also, the `Visit site` button that is used when you click on the site name above `My Home` does open in a new tab, which is good:

![image](https://user-images.githubusercontent.com/39308239/131678495-16625d86-1927-450a-be9e-fc7b1b888ec1.png)

So for less confusion and for consistency, isn't better if `Visit site` button would open the site in a new tab?

Here is the current behavior of various links in My Home:

https://user-images.githubusercontent.com/39308239/131678065-8380b2d0-e1ce-43e6-9692-401a2db75240.mov

### How

Make `Visit site` button open the site in a new tab

**Comment by kosiew** [comment]
Hi @zdenys ,

Thanks for improvement idea and the detailed steps.

@Robertght - for attention of flow patrol

**Comment by Robertght** [comment]
I think this should be a quick win. 

cc @sixhours

**Comment by sixhours** [comment]
I'm going to punt this over to Create since they oversee My Home stuff, and I have a feeling it will get done faster since we're short on engineers next sprint. :)

**Comment by Aurorum** [comment]
PR in #56371 - should be fairly quick to test. :)
