### ISSUE TITLE
WooCommerce Onboarding: Task List not created in WooCommerce > Home when the plugin is installed to make WordPress.com site go Atomic

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55902]
### Steps to Reproduce

1. Start with a monthly or yearly WordPress.com Business Plan Simple site (that has never had any plugins or custom themes installed yet)
2. Install WooCommerce from My Site > Plugins > Add New
3. Be redirected to WooCommerce > Home

### What I expected to happen

See the Task List named `Get ready to start selling` similar to this one (from another testing site of mine).

![image](https://user-images.githubusercontent.com/39308239/131682344-6e354f92-beae-43ce-870e-e0df95deb2a2.png)

### What actually happened

No Task List is available:

![WooCommerce Home No Task List](https://user-images.githubusercontent.com/39308239/131683282-1adbc9dd-09fd-492d-b854-09463fa658a8.png)

This is confirmed by navigating to `/wp-admin/admin.php?page=wc-settings` > Help > Setup wizard > Task List where the button reads `Enable` meaning that the feature is disabled.

![Markup on 2021-09-01 at 16:46:05](https://user-images.githubusercontent.com/39308239/131682753-05e97c02-8d05-4fa4-be49-b6bbf0926850.png)

### Context

Manual testing

### Operating System

macOS

### OS Version

BigSur 11.5.2

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

Enable the `Task List` manually. But for the new customer, having no task list after WooCommerce installation may be not helpful. They would not know what the next steps should be.

### Reproducibility

Once

### Other information

Possibly needs to be moved to a WooCommerce repo, such as https://github.com/woocommerce/woocommerce-admin

**Comment by kosiew** [comment]
Hi @zdenys ,

Thanks for reporting this and the detailed steps.

I followed the above steps and reached this screen after installing WooCommerce 5.6.0

![image](https://user-images.githubusercontent.com/29057562/132634289-e010041f-2a3b-4528-bd9a-9007bd2bc993.png)

After completing the above setup, I was redirected to:

![image](https://user-images.githubusercontent.com/29057562/132637740-95a696e5-9dbc-4afa-973b-d6332450ae6e.png)

In addition, in the Setup wizard, task list is also enabled:

![image](https://user-images.githubusercontent.com/29057562/132634419-399eacd2-8f71-44e3-a5ec-150947c966dd.png)

Can you check whether you're still having this issue?

**Comment by kosiew** [comment]
Closing for now.
Please reopen if you have more information on how to replicate this.

**Comment by zdenys** [comment]
I cannot reproduce anymore indeed. I must have done it on a Simple Site that was not a new one, but possibly an older one and maybe even a previously reverted AT site. So unless I can reproduce consistently, it's right to have this closed. Thanks for checking.
