### ISSUE TITLE
Premium Themes retirement: Sign-up flow "Premium" mentions

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/wp-calypso#55926]
This issue will contain a list of "Premium themes" mentions that need to be removed, since the Premium Themes program is being retired.

Sign-up onboarding check:
- [x] Free plan
- [x] Personal plan
- [x] Premium
- [x] Business
- [x] eCommerce

**Comment by danieldudzic** [comment]
**Theme showcase**
_"Premium customizable starter themes!"_
URL: https://wordpress.com/themes/freepremiumthemestest.wordpress.com

<img width="1479" alt="2dfnN2fuwb" src="https://user-images.githubusercontent.com/905781/131845526-d48f644c-8eed-4f12-ac5a-fec20f2ce78e.png">

COMMENT (pbking): This one seems appropriate to leave as-is; I believe it's referencing the woo themes you only get on that plan?

<img src="https://user-images.githubusercontent.com/146530/131860315-fb7024a7-dff1-455e-9031-067007c2d189.png" width="300px">

----
**Cart - Upgrade purchase from Free to Premium**
_"Unlimited access to our library of Premium Themes"_
URL https://wordpress.com/checkout/freepremiumthemestest.wordpress.com

<img width="1339" alt="q6EYKqFMqB" src="https://user-images.githubusercontent.com/905781/131846412-f21c0b9c-95c4-4661-b0db-0eeac908d55c.png">

Note: (pbking) I was unable to find the above in the calypso codebase.  Perhaps it would be found elsewhere?
Note: (scruffian) It's in client/my-sites/checkout/composite-checkout/lib/get-plan-features.ts, but you removed it in #55942
----
**Checkout sign-up - Premium Plan**
_"Unlimited access to our library of Premium Themes"_
URL: https://wordpress.com/checkout/premiumpremiumthemestest.wordpress.com?signup=1#step2

<img width="1314" alt="6BVdrhIUOp" src="https://user-images.githubusercontent.com/905781/131846546-8466bdc7-d2bf-4161-9e0a-985055b8c2ba.png">

Note: (pbking) I was unable to find the above in the calypso codebase.  Perhaps it would be found elsewhere?
----
**Plan Choice**
_"Unlimited premium themes"_
URL: https://wordpress.com/start/plans?intervalType=monthly

<img width="1191" alt="sTRPMY04O6" src="https://user-images.githubusercontent.com/905781/131846865-82342db5-7c43-4118-af71-bc08735f156b.png">

----
**Business Plan / eCommerce - Plan Features**
_"Try a premium theme"_
_"Access a diverse selection of beautifully designed premium themes included with your plan."_
_"Browse Premium Themes"_
URL: https://wordpress.com/plans/my-plan/businesspremiumthemestest.wordpress.com

<img width="1178" alt="lj3D3PYxRP" src="https://user-images.githubusercontent.com/905781/131846983-6703642b-fba3-4b20-97db-43f81dd3fc5a.png">

Note: (pbking) I was unable to find the above in the calypso codebase.  Perhaps it would be found elsewhere?
Note (scruffian) - It's in the file "client/blocks/product-purchase-features-list/find-new-theme.jsx" which you have removed! :)
----
**eCommerce Plan - Theme Showcase**
_"Get unlimited premium themes"_
_"In addition to our collection of premium themes, get comprehensive WordPress security, real-time backups, and unlimited video hosting."_
URL: https://wordpress.com/themes/ecommercepremiumthemestest.wpcomstaging.com

<img width="1065" alt="wdPqoV9UQp" src="https://user-images.githubusercontent.com/905781/131847072-5b74ba10-abe2-4838-8463-168d13b62b53.png">

----
**Themes page (upsell banner)**
_"Unlock ALL premium themes with our Premium and Business plans!"_ 
OR
_"Access all our premium themes with our Premium and Business plans!"_

http://calypso.localhost:3000/themes/pbking.wordpress.com

<img src="https://user-images.githubusercontent.com/146530/131856856-62a272fa-c098-428d-b3bd-5f9408197db4.png">

**Comment by zdenys** [comment]
I'm not 100% sure it's related to your above work, but it seems like it is, so posting here for you to take a look: https://github.com/Automattic/wp-calypso/issues/55941

**Comment by pbking** [comment]
Yes, absolutely @zdenys thank you.

**Comment by danieldudzic** [comment]
Thanks for the fixes @pbking :)
