### ISSUE TITLE
SEO Settings: hidden site has enabled settings

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#5592]
#### Steps to reproduce

Make sure you first have a site with Hidden enabled.

1. Starting at URL: https://wpcalypso.wordpress.com/settings/seo
2. pick the site with the Hidden setting on.
3. the yellow notice does not show up, settings are not disabled
4. Click on a tab
5. Go back to SEO
6. the yellow notice appears, settings are disabled

Also happens if you go to SEO settings and then reload the page.

#### Browser / OS version

Chrome 50

**Comment by rachelmcr** [comment]
I think this is a dupe of https://github.com/Automattic/wp-calypso/issues/5504
