### ISSUE TITLE
Google Analytics: Update Link to Google Support Page

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#55923]
### Steps to Reproduce

1. Go to Tools → Marketing → Traffic. 
2. Scroll down to Google Analytics 
3. Click on the link "where can I find my Measurement ID?"
4. Notice there is no mention of the measurement ID on this page.

### What I expected to happen

To see instructions on how to find my measurement ID.

### What actually happened

I was taken to a Google support page that does not mention "measurement ID". Perhaps this was accurate at the time this was added to Calypso, but Google has since changed things.

This seems to be Google's doc on the topic: https://support.google.com/analytics/answer/9539598 (you need to scroll down to "I'm using a Google Analytics 4 property. How do I find my Measurement ID (i.e. "G-" ID)?")

Perhaps we should link to https://wordpress.com/support/google-analytics/ because we can control the information on this page. This is less risky than relying on a support page from an external company.

### Context

Noticed with 31039499-hc

### Operating System

Windows, macOS

### Browser

Chrome/Chromium

### Simple/Atomic

Simple, Atomic

### Number of Users Impacted

Most users (>50%)

**Comment by Aurorum** [comment]
PR for this issue in #55979. :)
