### ISSUE TITLE
Upgrade Stripe's react library

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#55944]
We currently use the package `react-stripe-elements`. However, that package is outdated and doesn't support React 17. In order for the rest of calypso to update (see #54793), we'll need to migrate to `@stripe/react-stripe-js`.

**Comment by sirbrillig** [comment]
(cc @noahtallen who brought this up)

**Comment by michaeldcain** [comment]
Given that this is blocking the upgrade to React 17 (and just generally a good change), we're marking this as higher priority and will move it to the To Do column.

Some of the flows to test:

- [ ] adding a card (with and without 3DS)
- [ ] making a purchase (with and without 3DS)
- [ ] paying with a stored card (with and without 3DS)
- [ ] check the failure flows of all of the above
- [ ] Stripe redirect methods?
- [ ] Apple Pay and Google Pay

**Comment by sirbrillig** [comment]
Working on this in https://github.com/Automattic/wp-calypso/pull/56089. It actually seems to be working even though there's a couple pretty major changes necessary.
