### ISSUE TITLE
Playwright - Editor Transition: Page Basic Flow

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#55948]
### Details

See overall transition details here: pciE2j-sq-p2

Coverage:
- Create new page
- Accept a starting template (**this is new)
- Publish and validate

Includes coverage from prior specs:
- wp-calypso-gutenberg-page-editor-spec.js

**Comment by worldomonation** [comment]
Reopening because I misunderstood this to be for `basic post flow` when in fact it is `basic page flow`.
