### ISSUE TITLE
eCommerce Plan: `Upload your own themes` banner displayed in Appearance > Themes and when clicked results in errors at the checkout

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55941]
### Steps to Reproduce

1. Start with a WordPress.com eCommerce Plan or upgrade to it from a lower plan
2. Navigate to Appearance > Themes
3. Click the banner `Upload your own themes`

### What I expected to happen

See no banner that reads:

>Get unlimited premium themes
In addition to our collection of premium themes, get comprehensive WordPress security, real-time backups, and unlimited video hosting.

![image](https://user-images.githubusercontent.com/39308239/131859586-a4a32c87-a124-4a44-9aa6-6d85b473f399.png)

### What actually happened

Previously, a banner was displayed with this message:

>Get unlimited premium themes
In addition to our collection of premium themes, get comprehensive WordPress security, real-time backups, and unlimited video hosting.

But after some recent change that happened after I created this report the new banner is displayed:

> Upload your own themes
In addition to uploading your own themes, get comprehensive WordPress security, real-time backups, and unlimited video hosting.

If clicked, it leads to checkout but displays errors since the upgrade is not compatible with the plan 

https://user-images.githubusercontent.com/39308239/131860116-1630dc5d-af66-42fc-b58b-d6b28755cb9b.mov

Errors:

```
Sorry, that product is not compatible with sites hosted on WordPress.com.

Sorry, but we were not able to find that coupon. Please check that you typed the coupon code correctly and that this coupon is for the product you have selected.
```

### Context

Manual testing

### Operating System

macOS

### OS Version

BigSur 11.5.2

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

no

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

None

### Reproducibility

Consistent

**Comment by jeffikus** [comment]
I cannot replicate this with the testing instructions. Screenshot below:

I've tried with multiple upgrade scenarios from each plan.

<img width="1203" alt="Screenshot 2021-09-03 at 22 19 25" src="https://user-images.githubusercontent.com/937325/132062034-a309dd3d-ed6c-4c24-9c80-9b7854b46bd7.png">

**Comment by zdenys** [comment]
I cannot see the `Get unlimited premium themes` banner anymore, and now I see the `Upload your own themes` one. So something has changed already.

However, when I click this new banner, when I get to checkout, I see the same two errors I mentioned above. 


https://user-images.githubusercontent.com/39308239/132085219-c8c31436-0a86-4b22-862f-422cc857f6a7.mov

Does it happen for you too, @jeffikus?

I updated my initial instructions too.

**Comment by Robertght** [comment]
For what is worth, I'm not able to replicate this on my end either. I've tried on a Premium plan, which showed the banner but not the error. 

Then upgraded to an eCommerce one but that didn't show the banner anymore. 

@zdenys Can you give this another go and let us know if you're still seeing the issue?

**Comment by zdenys** [comment]
I cannot reproduce anymore 🤷‍♂️ I'll close this one now. I suspect I just happened to see those banners while other changes for the removal of Premium Theme mentions were being deployed. Thank you for taking a look!
