### ISSUE TITLE
Site not saving menu changes. Baskerville 2 theme.

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#55945]
### Steps to Reproduce

Site: https://forevermirai.jp/
ZD #4250071
Baskerville 2 theme/ Personal plan

Customizer -> Menu, change menu, add new menu, select menu location, add menu items, clicking Save changes will not change the menu settings. Only top pages are showing in the header menu.

### What I expected to happen

Any steps above should add the new test menu to the site. After saving changes, the menu should show on live site.

### What actually happened

No matter what was tried, or selections made, after saving changes and viewing the live site, the menu is NOT there. The two active pages remain the only menu items on the live site.

### Context

- current test menu, applied to header, worked in customizer, would not save.
- Create new menu Test 2, select Header location, create menu, Add items, Selected front page, category Travel, tag Yokohama, Custom link: # test. Save changes - appears to save. View site from homepage, new menu is NOT there.
- Tried adding Test 2 menu to Header position, worked in customizer, but would not save
- switch theme to 2021, saving menu works...viewable on live site.
- **Test site**, create new menu Test 2, select Header location, create menu, Add items, Selected front page, category Travel, tag Yokohama, Custom link: # test. Save changes - appears to save. View site from homepage, new menu is there.

### Operating System

macOS

### OS Version

Big Sur 11.5.2

### Browser

Firefox

### Browser Version(s)

91.0.2 (64 bit)

### Is this specific to applied theme? If so, what is the theme name?

Yes, Baskerville 2

### Simple/Atomic

Simple

### Console and/or error logs

Unsure

### Number of Users Impacted

All users

### Available Workarounds

n/a

### Reproducibility

Consistent

**Comment by Robertght** [comment]
Thank you for reporting this @Camaropilot ! I'm not able to replicate this anymore with the user's site. 

Please follow up with the user and open the issue again if it's still a problem.
