### ISSUE TITLE
Homestore theme: Block Widgets added to `Below Header` break WooCommerce breadcrumbs navigation

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55943]
### Steps to Reproduce

1. Activate Homestore (Storefront's child theme) on a WordPress.com eCommerce Plan site
2. Go to My Site → Appearance → Widgets
3. Add any block widget, for example [Spacer Block](https://wordpress.com/support/wordpress-editor/blocks/spacer-block/)
4. Navigate to a page other than home to see the WooCommerce breadcrumbs navigation (for example to a Product Category page)

### What I expected to happen

The breadcrumbs should be clickable

### What actually happened

Breadcrumbs navigation links are unclickable. 

https://user-images.githubusercontent.com/39308239/131864657-15dc197c-b94b-45b1-98a5-d79108748776.mov

This is likely due to some overly of the HTML elements from Below Header widget area.

![image](https://user-images.githubusercontent.com/39308239/131865048-f969f393-f616-4031-94b6-1f6c98c92d4e.png)

### Context

Observed during a Quick Start session 4267078-zd-woothemes and confirmed after manual testing on Homestore theme on a WordPress.com eCommerce Plan site.

### Operating System

macOS

### OS Version

BigSur 11.5.2

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

Homestore

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

Add no widgets to `Below Header` widget area.

### Reproducibility

Consistent

### Other information

Possibly this needs to be moved to Homestore repo at https://github.com/woocommerce/homestore

**Comment by synora** [comment]
Triaged. I cannot replicate this on Storefront so this seems to be specific to the child theme(Homestore). 
@zdenys can you report the issue in https://github.com/woocommerce/homestore please?
