### ISSUE TITLE
Playwright - Editor Transition: Comments & Likes

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#55954]
### Details

See overall transition details here: pciE2j-sq-p2

Coverage:
- Make a new basic post
- Comment & reply to comment
- Like post and comment as logged in user
- Like post as logged out user & login through popup

Includes coverage from prior specs:
- wp-comments-spec.js
- wp-likes__comment-spec.js
- wp-likes__post-spec.js

**Comment by worldomonation** [comment]
So, it looks like our current `wp-like__comments-spec` covers this.

The course of action here would be:

- migrate the above specs to use TypeScript.
- ensure the specs run as part of `gutenberg` and `calypso-pr` groups.

**Comment by worldomonation** [comment]
On second look, the Likes tests are already running for the `gutenberg` group.

I am marking this task as done at this in the context of WPCOM transition to Playwright. If we want to run these Likes tests on `calypso-pr` groups in the future, let's file a new task for that.
