### ISSUE TITLE
Subscription Emails: New Post email template

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#55965]
Current template:
![image](https://user-images.githubusercontent.com/375980/131897651-a25e1a27-c6e0-4f9c-bf4d-13794eb2a989.png)

This is what we aim for:
![image](https://user-images.githubusercontent.com/375980/131897680-8595844b-7753-4ed4-b786-9f946ad66263.png)

Reference: crtNho9opJSnM80QsE275F-fi-519%3A1048

**Comment by kwight** [comment]
@blackjackkent Do you have an existing PR for this? If so, can you add it to the board?

I'll remove you from this so you can focus on the Action Bar. 👍

**Comment by blackjackkent** [comment]
@kwight Added it to the subscriptions board. (Direct link is D66573-code)

**Comment by andres-blanco** [comment]
Closing this, merged on D66573-code
