### ISSUE TITLE
Form block: Allow adding custom placeholder in field

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#55976]
### What

It'd be nice to allow custom placeholder on text, message fields

### Why

It used to be possible with the use [shortcodes](https://wordpress.com/support/wordpress-editor/blocks/form-block/2/#adding-a-contact-form-with-shortcodes).

### How

A possible duplicate of https://github.com/Automattic/wp-calypso/issues/22426 , but adding here as feature requests

**Comment by edwinho89** [comment]
9017154-hc

**Comment by formosattic** [comment]
Thanks @edwinho89!

Thanks for flagging the duplicate #22426, will close this in favor of it.
