### ISSUE TITLE
Marketplace: Add blog sticker toggle in blog report card

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#55975]
Add blog `wpcom-marketplace` sticker toggle in the blog report card so that managing blog sticker become little easy for testing purpose.

**Comment by gavande1** [comment]
Diff created at D66328-code

**Comment by cpapazoglou** [comment]
Should we close this @gavande1 ?

**Comment by gavande1** [comment]
Yes. We can close it 👍
