### ISSUE TITLE
Flow for adding a subdomain of a domain that is already pointed to WordPress.com is confusing

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#55996]
### Steps to Reproduce

1. Create a new site with any paid WordPress.com plan (tested with Premium and Business fwiw)
2. Go through the flow to choose a free `.wordpress.com` domain and complete site creation
3. Go to `Upgrades > Domains`
4. Click `I Have a Domain`
5. Add a subdomain to the site for a domain that is already pointed to a WordPress.com site
6. Complete the process for adding a domain to your site

### What I expected to happen

The flow would know that the parent domain is using WordPress.com's name servers, so the new subdomain NS record will be added automatically, and that no other steps would be required to complete the process

### What actually happened

The flow displayed information on how to change the name servers for the domain that I added as if I was adding a new top-level domain, which didn't apply.

### Context

Testing.

### Operating System

macOS

### OS Version

11.5.2

### Browser

Firefox

### Browser Version(s)

92.0

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Simple, Atomic

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

If you continue through the process to the point of selecting Verify Domain, it'll work, but regular users won't necessarily know that

### Reproducibility

Consistent

### Other information

![2021-09-03 13 33 07](https://user-images.githubusercontent.com/4000628/132047013-8587bd99-b423-442b-848b-9346b633b2fa.gif)

**Comment by Robertght** [comment]
Thank you Ed! Flagged this for the domains pod in Slack slack-C020919TDRA/p1631258207063000

**Comment by hambai** [comment]
Hey @dpasque - we think this is fixed in the above PR which is already merged. Can you please check again and close the issue

**Comment by dpasque** [comment]
Closed by #58233
