### ISSUE TITLE
Signup: DSS: Add multi-image support

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#56]
DSS currently passes only the first result to Headstart. Now that Headstart supports multiple images, we'll need DSS to do the same, and pass the number of image results required on a per-theme basis (some themes only need one image, others might need four or five).

![screen shot 2015-09-28 at 1 16 44 pm](https://cloud.githubusercontent.com/assets/349751/10147545/6428c6a4-65e3-11e5-911c-19b9055cfbfe.png)

**Comment by kwight** [comment]
DSS was removed from signup in #2580, and we have no future plans for this version.
