### ISSUE TITLE
The TikTok block and embed doesn't work

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#56012]
### Steps to Reproduce

1. On a post or page editor, add a TikTok block
2. Paste a TikTok video URL > Embed
3. Also try to copy the embed code from the TokTok video and add it using the HTML block

### What I expected to happen

The TikTok video is showing 

### What actually happened

The TikTok video is not showing. It's showing only the link as shown in the following screenshot:

![Screenshot on 2021-09-06 at 08-02-25](https://user-images.githubusercontent.com/33721365/132145019-d960f760-9f21-4691-bbec-57f556338d70.png)

### Context

31508460-hc / 4275548-zd-woothemes

### Operating System

macOS

### OS Version

Mojave

### Browser

Chrome/Chromium, Firefox, Safari

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Simple, Atomic

### Number of Users Impacted

Some users (<50%)

### Reproducibility

Consistent

**Comment by formosattic** [comment]
Thanks @rinazrina.

Seems like issue have resolved on its own. I checked one the user's page, and the TikTok embeds loaded ok.

I wasn't able to reproduce either, in Simple or Atomic.
TikTok test link: https://www.tiktok.com/@keke.janajah/video/6802722722389576965
| Editor View | Live site View |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/15944096/133231143-3f0325b8-7ef3-4c19-b373-a0ddd0698f8a.png)  | ![image1](https://user-images.githubusercontent.com/15944096/133231162-d752e42a-a9de-4e79-b444-cd410aa1375d.png) |

Closing, but reopen if needed.

**Comment by hideandgeek404** [comment]
Reopening as have found another site that is reporting the same issue. 

Reported on 4308406-zd-woothemes

The customer reports that the TikTok block shows the contents of the post but not the video itself.

Various errors in the console on both the blogroll and the single page. 

Single page console error suggests an inability to read sessionStorage from Window directly related to TikTok links

**Comment by inaikem** [comment]
Based on "_Single page console error suggests an inability to read sessionStorage from Window directly related to TikTok links_", I'm wondering if 

Perhaps this user has actively blocked third-party cookies / site data? The preview (post content and video) loads as expected on a test site. Screenshot:

&nbsp;
<img width="702" alt="Markup 2021-09-23 at 17 58 12" src="https://user-images.githubusercontent.com/66711744/134489423-57a69f74-850c-4c79-8683-2e81e94054ef.png">

&nbsp;
Can you please confirm with the user they have third-party cookies enabled and if possible, see if they test while using a different browser!

**Comment by hideandgeek404** [comment]
Thanks for the response. 

I can certainly see if this is the case, however, it is worth noting that this is reproducible on my own computer if I try to load the single page in Incognito, but if I load it normally it works fine for me. 

This could be conducive with the above, could you see if you can reproduce in Incognito?

**Comment by Robertght** [comment]
I can confirm the incognito page doesn't load the TikTok embed. Instead, I see this:

![image](https://user-images.githubusercontent.com/6737345/134660076-8dee165f-26e1-4c9d-93e2-6cf2cbbb5bcf.png)

The same happens on my test website.

**Comment by alshakero** [comment]
You nailed it @inaikem! Allowing 3rd party cookies fixes the issue. I'll add more details shortly.

**Comment by alshakero** [comment]
Alright, so it seems TikTok tries to fingerprint users using session storage and other utils, and when you block 3rd party cookies, even touching `SessionStorage` throws an error. TikTok seems to check if `sessionStorage` is undefined, but even that check throws. 

They'll need to add a try catch around it. Here is the [faulty line](https://sf16-scmcdn-va.ibytedtos.com/goofy/tiktok/web/node/_next/static/chunks/commons.fa7e170f1b4f3be44eec.js#:~:text=undefined%22!%3Dtypeof%20sessionStorage%3FsessionStorage%3Avoid). 

They don't have any open-source presence, so I'll email support.

Hey @ahussam! Maybe you have some way to report a bug? I tried to find something and I can't :D

**Comment by cometgrrl** [comment]
This is working correctly now, even with 3rd party cookies blocked.
