### ISSUE TITLE
VAT Details entry | Trim the leading country code if it matches the selected one

### ISSUE THREAD

**Issue by toncijajic** [Automattic/wp-calypso#56032]
### Steps to reproduce the behavior

Slack discussion: p1630936548136200-slack-C0117V2PCAE

1. Go to [VAT Details entry](https://wordpress.com/me/purchases/vat-details)
2. Add VAT details with the full VAT ID (country code included) - see slack thread for test number
3. Click "Validate and save"
4. Observe

#### What I expected to happen
The validator successfully validates and saves the data.

#### What actually happened
The validator doesn't strip the leading country code from the ID, trying to validate the wrong ID.
In the case of my VAT ID, it's trying to validate HRHR------ instead of HR------.
Validation returns an error. Trying to force it produces invoices with "HR HR------" VAT numbers on them

I would expect that the leading country code is trimmed if the same as the one selected during validation and saving.

### Context
In the EU, VAT ID is complete with the leading country code. Users entering VAT ID in an international environment almost exclusively enter it with the leading country code.

#### Is there any console output or error text?
Documented only client-side errors, see screenshots

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
All sites, all users trying to add full VAT ID

**Comment by toncijajic** [comment]
@Automattic/shilling

**Comment by michaeldcain** [comment]
Let's start with a backend fix to validate the data, but then additionally modify both forms (Calypso and MC) allow for dynamic validation (i.e. if I input a VAT number with country code, auto-select country from the dropdown and remove it from the VAT number).

**Comment by kingsleyinfo** [comment]
I had a user with this issue here 31721115-HC 
The validation was failing for them until I suggested that they use only the number without the country code.

**Comment by ghost** [comment]
>The validation was failing for them until I suggested that they use only the number without the country code.

I had a similar case today as well. Glad this is already reported.

**Comment by fabz1001** [comment]
Hi, may I take this one? I already have a working solution in my local env.

**Comment by sirbrillig** [comment]
@romokebi PRs are certainly welcome!

**Comment by fabz1001** [comment]
Thank you @sirbrillig, I have just opened it! ([PR](https://github.com/Automattic/wp-calypso/pull/57686))

**Comment by michaeldcain** [comment]
Closed with #57686. Thank you @romokebi!
