### ISSUE TITLE
Open in new tab option when toggled removes link from Service Block Media

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#56037]
### Steps to Reproduce

1) Create a new page and add Services Page layout to it
2) Add images to service block.
3) Add link to it https://d.pr/i/BequG1 and then try to toggle on Open in new tab option
4) This is making the link disappear.
5) Also the fields Link Rel and Link CSS Class do not work as I cannot type into them

### What I expected to happen

The link should not disappear and open in new tab feature should be toggled on correctly.

### What actually happened

The link gets removed.

### Context

The URL disappears from https://d.pr/i/BequG1 when the user tries to toggle Open in new tab. I can replicate on my test site too.

### Operating System

macOS

### Browser

Firefox

### Simple/Atomic

Atomic

### Reproducibility

Consistent

**Comment by davipontesblog** [comment]
I did some testing here and was able to narrow this "Services" block to the Coblocks plugin - this only shows on atomic sites too:

<img width="787" alt="Screen Shot on 2021-09-10 at 10-19-16" src="https://user-images.githubusercontent.com/31009008/132868269-daca2cdf-af29-4b8d-a0b2-94f041f212f2.png">

We should open this on the Coblocks repo. I will let the user know of a workaround to use our Images block in the meantime - this "Services block" is essentially a Columns + Image + Heading + Paragraph combo.

User report 4276608-zd-woothemes

**Comment by synora** [comment]
Reported at https://github.com/godaddy-wordpress/coblocks/issues/2026
