### ISSUE TITLE
Clicking 'Back' from Domain Mapping Screen Does Not Take User Back

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#56047]
### Steps to Reproduce

Scenario 1:

1. On a site with a paid plan, go to Upgrades > Domains
2. Click *Add a domain to this site* → *Use a domain I own*
3. Click Back

Scenario 2:

1. On a site with a paid plan that has not used its free domain credit, go to Upgrades > Domains
2. Click *I have a domain*
3. Click Back

### What I expected to happen

I expected to be taken back to the 'Site Domains' screen: https://wordpress.com/domains/manage/SITE-URL

### What actually happened

I was taken to the 'Search for a domain' screen: https://wordpress.com/domains/add/SITE-URL

Scenario 1:

https://user-images.githubusercontent.com/30727666/132297364-779247ad-a52a-47fd-9215-6d3909cc7836.mp4

Scenario 2:

https://user-images.githubusercontent.com/30727666/132297379-f0aa978e-a716-422f-b8d4-de3305e96d06.mp4

### Context

My own usage

### Operating System

Windows

### Browser

Chrome/Chromium

### Simple/Atomic

Simple, Atomic

**Comment by synora** [comment]
Triaged. Able to reproduce.

**Comment by donalirl** [comment]
Still occurring, but no longer a problem thanks to the new Domains interface.
