### ISSUE TITLE
Pre-Renewal Emails: Add Copy to Guide Customers to Self-Serve Their Billing Needs

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#56051]
### What

Encourage users to self-serve their billing needs instead of contacting support.

### Why

In support, we receive a lot of email replies to the pre-renewal emails, with basic questions that can all be answered by the customer without needing to contact support. Some examples: #4218629-zen #4273099-zen #4265785-zen #4264634-zen

To reduce support contacts, it would be helpful to add details to the pre-renewal email copy to make it clear that customers can self-serve many tasks like canceling, turning off auto-renew, and updating their payment method.

### How

Currently, the emails have a link for "Manage your subscriptions" (screenshot below). This text can seem vague to many recipients, and we could make it clearer what "managing" entails. There are lots of ways to address the "why" in this request. My suggestion is to enhance the copy to say something like:

> Manage your subscriptions, where you can:
> 
> * Turn off automatic renewal (your subscription will expire on [EXPIRY DATE])
> * Renew manually
> * Update a payment method
> * View receipts
> * Cancel a purchase

I've included the subscription's expiry date because this is not mentioned in the email. 

In addition, we could make "Manage your subscriptions" a button instead of a text link to encourage people to visit their Purchases in their account.

![Image 2021-09-07 at 6 46 40 PM](https://user-images.githubusercontent.com/30727666/132314589-a874bcb7-bacc-4509-acc4-4a6404237de8.jpeg)

**Comment by michaeldcain** [comment]
This is a good suggestion. In our planning call, we made some changes to the list of items, since "cancel a purchase" is essentially turning off auto-renew (and maybe not needed in this email) and renew manually might also not be needed, since this is an auto-renew pre-renewal email.

> Manage your subscriptions, where you can:
> 
> - Turn off automatic renewal (your subscription will expire on [EXPIRY DATE])
> - Update a payment method
> - View receipts

**Comment by donalirl** [comment]
Great. If it's not too much, it would also be helpful to add a link to our Manage Purchases support doc somewhere, for users who need a little extra help.

If we can do that, one suggestion is directly underneath the Manage Subscriptions button, add a text link:

[Get Help](https://wordpress.com/support/manage-purchases/)

(And at the bottom of that doc is a link to contact support, if they need human help.)

**Comment by DavidRothstein** [comment]
>If it's not too much, it would also be helpful to add a link to our Manage Purchases support doc somewhere, for users who need a little extra help.
>
>If we can do that, one suggestion is directly underneath the Manage Subscriptions button, add a text link

I wonder if it would be enough to **just** do that actually, and nothing else?  Either "Get help" or "Need help?" for the wording.

This email is a little long already, and I'm not sure if we should put so much text into it that isn't fully related to the primary purpose of the email.

**Comment by martian77** [comment]
I wasn't really sure which option we had decided on, so I've mocked up 3. The styling can be changed to e.g. remove the padding between the bottom of the button and the list, or maybe add some over the get help link on the third. 

First there's a list of things you can manage, no button, help link as part of list:

<img width="490" alt="list-no-button" src="https://user-images.githubusercontent.com/7126226/137932807-2a481bef-754e-4e17-81e8-26f06029f9e5.png">

This is with the button and the list:

<img width="542" alt="button-and-list" src="https://user-images.githubusercontent.com/7126226/137932882-b2d8c8b5-93b9-40e5-a31a-a42bf8650ee1.png">

And this is the button and the get help link:

<img width="481" alt="button-and-help" src="https://user-images.githubusercontent.com/7126226/137932920-07ec5cfc-14ae-457d-abbd-982751595857.png">

(I should have put a border on my images!)

I'm not sure the button and the list works well here, personally. I tried putting the list before the CTA too, but to me the button feels separate from the text. Of the other two, I lean towards the third - as David said, it's a reasonably long email already, and this option gives a clear link and the main help page. 

@donalirl any preferences?

**Comment by michaeldcain** [comment]
In line with [David's comment above](https://github.com/Automattic/wp-calypso/issues/56051#issuecomment-926742647) can we do the third option and add some margin to the top of the text link (or bottom of the button)?

**Comment by donalirl** [comment]
I'm happy with option 3! (my second preference would be option 1)

**Comment by martian77** [comment]
Diff at D68706-code.

**Comment by sirbrillig** [comment]
✅

**Comment by martian77** [comment]
@donalirl This is ready to go for WPCOM plan renewals. 

Do you want this change for non-plan emails as well? e.g. Domains, GSuite, Jetpack etc. That's a different email template e.g. 

<img width="541" alt="Screenshot 2021-10-22 at 12 03 53" src="https://user-images.githubusercontent.com/7126226/138443948-61fd36cc-d9aa-41c2-8b2e-10eb1195c779.png">

If so I think we should probably start a new ticket, and get this one live.

**Comment by donalirl** [comment]
@martian77 Yes, I think so. I'm not too familiar with which emails live where but it would definitely be helpful to make this update for all subscriptions that customers can manage themselves.
