### ISSUE TITLE
Atomic Downgrade: Investigate emails sent due to plan expiration

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#56057]
As described in P9o2xV-1yt-p2, and in order to automatically revert Atomic sites back to the Simple sites infrastructure after their plan expire, we need to inform users via emails what are the actions we're going to take if they let the plan to expire. 

In particular, we want to send 3 emails:
- A reminder that the plan is about to expire.
- A notification that their plan has expired.
- A notification that their site has been reverted.

Seems we are already sending the 2 first emails so we'd need to only change its content under specific circumstances. On the other hand, the third one does not exist at the moment, so we should create it.

Before jumping into implementing the needed changes, let's take a moment to investigate how the 2 first emails are sent, how their content is defined, and note our findings here. That way, we'll know better how to change the content of the existing emails, and how we can create a new email.

**Comment by dsas** [comment]
# How current emails work

There are several different cases for plan renewal emails, depending whether auto-renew is on etc. There's a high-level summary of all renewal (not "has expired") emails here: PCYsg-24R-p2. We will need to decide which ones need the backup link & feature reminder but that's a problem for a P2 post.

This is what happens:

Every day, the `billingdaddy_run_all_renewals` function is called, this loops over `A8C\Billingdaddy\WPCOM\SUBSCRIPTION_EVENTS_SCHEDULE` and calls `schedule_service_renewals` for each service (wpcom, jetpack etc) it then calls `A8C\Billingdaddy\Subscriptions\Event_Scheduler::queue_events` and via `queue_event_groups` and `queue_event_group` creates events in the database before eventually calling `Event_Scheduler::start_event`:

 * `Event_Scheduler::start_event` will get an action 
   * `A8C\Billingdaddy\Subscriptions\Actions\Action` will set `event_type` with a value it's constructed with
   * `Event_Scheduler::start_event` will then call the event_start method on the action
     * `A8C\Billingdaddy\Subscriptions\Actions\Action\event_start` will check the `event_type` and then queue an action by inserting into `billing_subscription_event_actions` 

`billingdaddy_queue_event_jobs` will then iterate over `billing_subscription_event_actions` creating `billing_run_event_group_actions` async jobs



The async jobs are handled by`billingdaddy_run_event_group_actions` which will use `Action_Scheduler::process_pending_actions` to get the pending actions in the group and run it.

 * `Action_Scheduler::run_pending_actions`
     * `Action_Scheduler::run_action`
         * `Action_Scheduler::fire`
             * `A8C\Billingdaddy\Subscriptions\Actions\Action::register_action_handlers` will map action names, to do_ methods
             * `A8C\Billingdaddy\Subscriptions\Actions\Action::fire_action` will then execute the mapped do_ method

The do_ method will gather some info (e.g. previous receipt, email address) and then call a specific function.

The specific function, e.g. `send_plan_expired_email` will use some helper functions / objects to build up a list of parameters and then send the email with `html_email_simple_send` (some specifics below)

### Plan expired

Template is in wp-content/mu-plugins/html-emails/themes/osmatic/html/plan-expired.php
Sending backtrace
 * (Various bits that probably don't matter)
 * `\html_email_simple_send`
 *  `Api\Mailer\send_plan_expired_email` 
 * `WordPress_Subscription_Action::do_send_plan_expired`

### Plan expiring
Manual renew
Template is in wp-content/mu-plugins/html-emails/themes/bluestripe/html/renew-expiration-notice.php
Sending backtrace
 * (Various bits that probably don't matter)
 * html_email_simple_send
 * `email_renew_expiration_notice`
 * `WordPress_Subscription_Action::do_send_wpcom_subscription_email`
 * `WordPress_Subscription_Action::do_send_wpcom_pre_renew_notification`
 * `WordPress_Subscription_Action::do_send_wpcom_subscription_manual_renew_notify` 

### Auto-renew
Template is in `wp-content/lib/billingdaddy/email/services/memberships/pre-renew.php`
 * (Various bits that probably don't matter)
 * `html_email_simple_send`
 * `bd_send_email_pre_renew`
 * `Default_Subscription_Action::do_send_pre_renew`

**Comment by dsas** [comment]
## High level plan for adding another email

Add an entry to `A8C\Billingdaddy\WPCOM\SUBSCRIPTION_EVENTS_SCHEDULE`
 * It's ok for day to be negative for "days after the expiration"
 * Would need to define a new event as a const in wp-content/lib/billingdaddy/src/subscriptions/subscriptions.php
 * Define new loader / filter / group filter on A8C\Billingdaddy\WPCOM\Event_Scheduler as/if necessary to narrow down the records to send to

Add the new event in `Event_Scheduler::$event_types` and possibly also `A8C\Billingdaddy\WPCOM\Event_Scheduler::supported_events` & possibly `A8C\Billingdaddy\WPCOM\Event_Scheduler::is_wpcom_subscription_event`

Update `WordPress_Subscription_Action`
 * Add a new action as a class const
 * Add a do_ method for performing the action
 * Register a mapping between the two in `register_action_handlers`
 * Update the switch in `event_start`

Add template in `wp-content/lib/billingdaddy/email/services/wordpress-com/foo.php`

### Development aids
Simulate scheduling for a given day `wp --require=bin/store/billingdaddy/simulate-bdse-scheduler.php help simulate-bdse-scheduler`

Look at a user in payments admin to see their upcoming scheduled things and preview emails

With a sandboxed store you can manually test auto-renewals by running `php bin/store/billingdaddy/auto-renew-ownerships-in-store-sandbox.php` I _think_ adding to the list of event_types in `renew_ownerships_without_auth` will let you test other events.

**Comment by dsas** [comment]
I've published two P2 posts (pdgTfM-3c-p2 & pdgTfM-3f-p2) about what I've learned, the actual implementation of emails will be done by #56058, #56059 & #56061 I'm therefore going to close this investigation issue.

**Comment by dsas** [comment]
I've noticed another way that emails are sent after plan expiry, a 'win back' series of emails are sent after both refundable cancellations and expirations (PCYsg-kN7-p2).

1. `Store_Product::deactivate_handler` is called via a `deactivate_product` action hook when a plan is deactivated.
2. `Store_Product_Bundle::deactivate`
3. `Store_Product_Bundle::start_deactivation_email_campaigns` checks whether the subscription was refundable and deactivated due to cancellation, or whether it is expired and was deactivated due to expiry
4. `MarketingEmailCampaigns::start_winback_emails_if_eligible` creates an `marketing_plan_cancelation_winback2` appointment for three hours time and calls some other methods to schedule the appointment. 
5. Sending is then done by another process using the Guides system (PCYsg-7l7-p2)

I don't think these are suitable to our goals as we'd still have to do something for non-refundable plan cancellation.
