### ISSUE TITLE
Atomic Downgrade: Email notice after plan expiration, before revert is complete

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#56058]
As noted in pdgTfM-3Y-p2, we need to improve the current email we sent to inform Atomic users that their plan is about to expire, so we can automatically revert the site after plan expiration.

> **Tell them their plan is about to expire.** The customer receives a renewal reminder email at least 3 times from BillingDaddy; a notice is also included in WP Admin of the WoA site for a month prior to plan expiration. To do:
>
> - Include a link to download their backups from their Activity Log.
> - Inform the customer that if they do not renew their plan, they will lose access to plan features like being able to run custom plugins and themes that will impact their site. This allows them to both retain their data, and to decide whether or not they want to continue having access to advanced hosting features.
> - Let them know that without action on their part, their site will be downgraded to a Free plan and that plugin and theme features will no longer be available. Also inform them that because some features will not be available, there will be data loss between the plans and it is important for them to have downloaded a backup of their site.

**Comment by onuro** [comment]
Hey folks, let me know if this works. 

<img width="964" alt="Plan Expire" src="https://user-images.githubusercontent.com/645713/134345142-87b89e14-fc37-49b8-aed5-4ec1d8799405.png">


Thanks!

**Comment by mmtr** [comment]
Thanks @onuro, it looks great! As noted in pdgTfM-4r-p2, we're finally using the existing template to expedite a little bit our velocity. Once we ship a first iteration, we'll look into creating a new template according to your design.

**Comment by kdevnel** [comment]
I updated the title to better reflect the timing and intention of the email as per pdgTfM-4r-p2#comment-172

**Comment by dsas** [comment]
Clarifying the features is done as D68350-code, back-up link and atomic modifications are to follow

**Comment by dsas** [comment]
Clarifying the features has been deployed as  D68350-code

D68448-code has the back-up link and atomic wording
