### ISSUE TITLE
Add information for Customizer logo accepted file types 

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#56066]
### What

When uploading a logo to the Customizer there is a list of accepted file types, but these aren’t correct for file types that can be used for the logo. Ideally this information would be displayed somewhere.

### Why

This can result in confusion, since you can't actually use all of these files types as a logo (.tiff for example).

Example of issue. It says you can upload a tiff, but you can't actually use that for the logo.

![Screen Capture on 2021-09-07 at 10-53-33](https://user-images.githubusercontent.com/10353785/132366236-62811ec3-20c1-4a60-a3dd-47321b307f9c.gif)

Reported 31398472-hc

### How

Perhaps under the logo it could list accepted file types (.png, .jpg, etc).

**Comment by Robertght** [comment]
Closing this one as it appears to be similar to this: https://github.com/Automattic/wp-calypso/issues/56066

**Comment by mikeicode** [comment]
@Robertght You linked to the same (this) issue in your comment (56066)

**Comment by Robertght** [comment]
Sorry! Copy-pasta glitch: https://github.com/Automattic/wp-calypso/issues/34630
