### ISSUE TITLE
Atomic Downgrade: Automatically revert sites after plan expiration

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#56060]
As noted in pdgTfM-3Y-p2, we want to automatically revert Atomic sites one week after plan expiration.

**Comment by dsas** [comment]
I've written a P2 about the approach for this: pdgTfM-3Y-p2

**Comment by dsas** [comment]
Working on as D67956-code

**Comment by mmtr** [comment]
I think we can close this one out now that we've shipped D68425-code, right? cc @BogdanUngureanu
