### ISSUE TITLE
Stratford: Navigation Block missing spaces

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#56071]
### Steps to Reproduce

1. Activate the Stratford theme
2. Add a Navigation Block (horizontal)

### What I expected to happen

There should be some space space between menu items, as there is when viewing the page directly.

![Navigate_around_the_site__–_Our_Fancy_New_Travel_Site](https://user-images.githubusercontent.com/7662449/132374526-8b733a66-af1d-4a87-8bcf-f4987b9f3f09.jpg)

### What actually happened

There are no spaces between menu items in the editor view.

![Edit_Post_‹_Our_Fancy_New_Travel_Site_—_WordPress](https://user-images.githubusercontent.com/7662449/132374323-f6718d80-12bd-4747-98df-1617fecc3b31.jpg)

### Context

No user reports, discovered during team empathy testing.

### Operating System

macOS

### OS Version

11.5.2 

### Browser

Firefox

### Browser Version(s)

91.0.2 

### Is this specific to applied theme? If so, what is the theme name?

Stratford

### Simple/Atomic

Simple

### Available Workarounds

Add a space in the editor or add custom CSS

**Comment by synora** [comment]
Using Chrome, the Navigation Block displays as expected: 

![Annotation on 2021-09-09 at 09-00-25](https://user-images.githubusercontent.com/10015451/132690465-19ed64f3-2446-47c4-b348-73806fd6fa55.png)

View from within the editor: 
<img width="585" alt="Screen Shot on 2021-09-09 at 09-01-38 (1)" src="https://user-images.githubusercontent.com/10015451/132690640-d7882a23-fdcf-4a1b-804f-d42b6db3c753.png">


Is this issue still persisting for you @kathrynwp?

**Comment by kathrynwp** [comment]
Can confirm that I do not see the bug in Chrome, only Firefox.

**Comment by kathrynwp** [comment]
Actually I just re-tested in Firefox and I no longer see the issue there either! 

@thekingsprojects Would you mind checking as well on the original test site, the URL of which I seem to have lost? Thank you!

**Comment by thekingsprojects** [comment]
Just checked the testing site again. I'm not seeing it in Firefox any longer, either.

**Comment by Robertght** [comment]
Thank you all for working on this! I'm going to close this one for now, but if someone finds another case, please re-open it.
