### ISSUE TITLE
Block Patterns: Can't access the Header patterns in Safari 

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#56077]
### Steps to Reproduce

1. Start by opening a page to edit
2. Click the blue plus sign to open the blocks & pattern search sidebar
3. Go to Patterns → Headers (in the Patterns drop down)
4. Start scrolling. The second pattern, "Large header with text and a button" does not load correctly and breaks the entire pattern selection box. 

I tested this on Chrome and did not see the same error/issue. 

In Safari, I also got an error that "This webpage is using significant memory. Closing it may improve the responsiveness of your Mac." 

I'm currently running Safari Version 14.1.2 (16611.3.10.1.6) on macOS Big Sur, version 11.5.2. 16" 2019 MacBook Pro. 

Video of the error: 

https://user-images.githubusercontent.com/30205248/132394213-f4588668-003c-4fea-9aec-0a6e2806f971.mov

### What I expected to happen

I expected to be able to scroll through header patterns and select a pattern that I wanted to use. 

### What actually happened

I was unable to select a header pattern. Instead, the sidebar container just kept scrolling and scrolling. 

### Context

Empathy testing (Asgard team testing, September 7th) 

### Operating System

macOS

### OS Version

11.5.2

### Browser

Safari

### Browser Version(s)

14.1.2

### Is this specific to applied theme? If so, what is the theme name?

I tested using Blank Canvas and also Bradford. Issue happened on both themes. 

### Simple/Atomic

Simple

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

You can use a different web browser - I was able to select a header pattern in Chrome.

**Comment by Robertght** [comment]
Thank you for reporting this @serabi ! I can confirm this happens with Gutenberg turned on on a self hosted website as well, but it doesn't if it's turned off.

I've also noticed some of the other patterns are sharing a similar effect so I've raised it here:

https://github.com/WordPress/gutenberg/issues/34729

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
Let's consolidate all to https://github.com/WordPress/gutenberg/issues/34729
