### ISSUE TITLE
Action Bar: Subscription settings are missing text.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56073]
When subscribing to https://whippetwisdom.com/, I don't get settings text, not styles I think.

<img width="441" alt="Screen Shot 2021-09-07 at 8 48 59 AM" src="https://user-images.githubusercontent.com/349751/132375539-bb0f80cb-a19b-40b5-b5e1-7d8ebd73d91a.png">

**Comment by blackjackkent** [comment]
This issue stems from the fact that we are not explicitly setting a text color for the labels of these toggles, so if the blog in question has a theme with white or light-colored text, the toggle text appears invisible.

I've created a diff with a fix at D66464-code.

**Comment by blackjackkent** [comment]
Fix has been deployed! Closing.
