### ISSUE TITLE
Scroll Jumpy in Media Library

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#56074]
### Steps to Reproduce

1. Go to https://wordpress.com/media/ and set the size to 50% (six columns). 
2. Scroll down the page. 
3. Notice the images jump before displaying.

The gif is too big to upload, but you can see it on https://d.pr/i/2WdVBO

### What I expected to happen

The scrolling should be smooth.S

### What actually happened

Scrolling causes the media images to jump.

### Context

This was reported in 4268858-zen

The screencast is from my replicating on a personal site.

### Operating System

macOS

### Browser

Firefox

### Simple/Atomic

Atomic

**Comment by sixhours** [comment]
👋 Hey hey @ChrissiePollock ! The screencast is 404ing. Do you have an example of the behavior I can see? Feel free to ping me in Slack if the site is private. Thanks!

**Comment by ChrissiePollock** [comment]
@sixhours I think we can close this. I can no longer replicate it. I'll leave that up to you, though. Thanks for looking :)
