### ISSUE TITLE
Theme search on Atomic not showing all the showcase themes.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#56085]
### Steps to Reproduce

1. Go to the Theme Search on an atomic site.
2. Use the "WordPress.com" view so you can search the showcase.
3. Try to search for themes that should be available (I tried Edin and Colinear)

### What I expected to happen

These showcase themes should be available in the search results on Atomic.

### What actually happened

It does not find these themes, and they appear to be unavailable.

### Context

Customer reported in chat: 31542617-hc

### Operating System

macOS

### OS Version

Catalina

### Browser

Firefox

### Browser Version(s)

https://whatismybrowser.com/w/H29EBE4

### Is this specific to applied theme? If so, what is the theme name?

Colinear, Edin

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

You can go to the default theme search (WP-Admin) and find them on the wp.org theme repo. However, this makes it hard to differentiate from the themes we support.

### Reproducibility

Consistent

### Other information

Screenshots!
Edin on Simple: 
<img width="1525" alt="Edin Simple" src="https://user-images.githubusercontent.com/49131029/132415830-72e9745d-6ae8-4f64-ba70-a0a8c27fbd31.png">

Edin on Atomic: 
<img width="1499" alt="Edin Atomic" src="https://user-images.githubusercontent.com/49131029/132415849-3476dd22-78e3-4953-a579-e47a316ee435.png">

**Comment by synora** [comment]
I'm able to locate those themes on my Atomic site following your steps. I'm using Chrome as my browser: 


https://user-images.githubusercontent.com/10015451/132687064-3a6ee60c-e5b0-4d2e-b7e8-fc95ad5bef36.mp4

@KirkwallDay is this issue still persisting for you?

**Comment by KirkwallDay** [comment]
Hi @synora , It still is happening to me.

I'm using Firefox, although I tried chrome as well and it happened on both.

I tried two AT sites I have and the issue happened on both of them. I also tried making a new AT site and the issue happened on that one as well.

https://user-images.githubusercontent.com/49131029/132704628-daa25919-077f-427e-bdf3-3a595b1508e5.mp4

I'm going to ask some other people to check, maybe it's just something with my setup that's causing this. I'll post here when I know more.

**Comment by KirkwallDay** [comment]
I had a few team members duplicate the issue on their AT sites. I've reached out to @synora to see if they could duplicate the issue on my test sites.

**Comment by Robertght** [comment]
Thank you for reporting this! I'm flagging this for Flow Patrol Manage to have a look. cc @sixhours / @mreishus

**Comment by kdevnel** [comment]
Just to note it looks like this is also causing only installed or previously used themes to show on the "All Themes" tab. It means users can currently only activate previous or recommended themes on Atomic at the moment.

p1631272409225100-slack-C03TY6J1A

**Comment by kdevnel** [comment]
Reported by customer in 31544026-hc

**Comment by kdevnel** [comment]
And to add, it looks like you can see and search for themes you've previously activated on your Atomic site - it's only themes in the gallery but not yet installed and aren't in the recommended list that are hidden.

**Comment by synora** [comment]
Ah! Upon further testing with a fresh Atomic site, I can replicate the issue: 

https://user-images.githubusercontent.com/10015451/132851296-e604044e-0310-4704-9b28-fa587f6b38b8.mp4

**Comment by davipontesblog** [comment]
Isn't this related to how Premium themes are now retired? As in "I think they shouldn't show anymore".

**Comment by sixhours** [comment]
I'm testing and noticed there's no Infinite Scroll on the "All Themes" view at all for Atomic sites, so most of the themes don't load. I'm checking to see if recent changes for premium themes might have broken it. 

I shipped https://github.com/Automattic/wp-calypso/pull/55910 two days ago but it looks like this was happening before then.

**Comment by sixhours** [comment]
Traced it back to https://github.com/Automattic/wp-calypso/pull/56033
