### ISSUE TITLE
Flow to access WooCommerce settings broken when first setting up a domain

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#56080]
### Steps to Reproduce

1. Buy a new site, with a new domain
2. Go to Plugins and install WooCommerce
3. Once WooCommerce is installed, an alert will pop up that says that you'll be redirected in 5 seconds
4. You'll then be redirected to a broken page if the domain hasn't propagated yet. Screenshot of an example: 

<img width="2268" alt="screen_shot_2021-09-07_at_2 42 04_pm" src="https://user-images.githubusercontent.com/30205248/132395881-9f148e4d-db89-407e-84ba-53955b1428c9.png">

### What I expected to happen

I expected the WooCommerce setup wizard to launch.

### What actually happened

I saw an error message with no clear indicator of what was happening or what to do next. 

### Context

Empathy testing (Asgard team) 

### Operating System

macOS

### Browser

Safari

### Simple/Atomic

Atomic

### Number of Users Impacted

Most users (>50%)

### Other information

This will resolve once the domain finishes propagating, but there's no clear warnings anywhere in the WooCommerce installation process that you need to wait for the domain to propagate before you start installing plugins/accessing your plugin settings reliably.

**Comment by Robertght** [comment]
Thank you for reporting this @serabi! Flagged this for the domains pod in Slack slack-C020919TDRA/p1631258207063000

**Comment by zachspears** [comment]
I tested this following the same steps and was able to reproduce but received a different error: 
<img width="1297" alt="Screen Shot 2022-05-19 at 8 45 39 PM" src="https://user-images.githubusercontent.com/10124024/169438626-ddb61afd-a326-4756-8b8f-c46569afe875.png">
:

**Comment by cuemarie** [comment]
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Normal` to better reflect it's status in the larger context of open bugs in the repo.

**Comment by gikaragia** [comment]
Tried this and couldn't reproduce. I am now redirected to a `*.wpcomstaging.com` url:


![Image](https://github.com/user-attachments/assets/adc35924-5c4d-406e-a469-09342e0531da)
