### ISSUE TITLE
Reorder Social Icons not working in Jetpack Social Icons widget 

### ISSUE THREAD

**Issue by kamlesh08** [Automattic/wp-calypso#56096]
**Steps to reproduce**

1. On a Simple site, add a Jetpack Social Icons widget to any widget location.
2. Add Facebook, Twitter, Instagram, or any other social URLs that you wish to display on the site.
3. Post adding the URLs, try reordering the Icons. It won't work.

**Screenshot**

<img width="292" alt="Screenshot 2021-09-08 at 15 14 30" src="https://user-images.githubusercontent.com/22547800/132486764-cd3b951a-87d6-4aa8-a83b-811c02df6f57.png">

**What I tested**

- I replicated the issue on the Maywood theme and Seedlet theme.
- I could replicate the issue with my own social media links.

**Context**

Reported here - https://wordpress.com/forums/topic/cant-reorder-icons-in-social-icons-widget/

**Comment by synora** [comment]
Triaged. Can replicate. The ability to change the order of the icons appears to be broken.

**Comment by yansern** [comment]
Jetpack Social Icons is deprecated and no longer available. Any sites that has the old Jetpack Social Icons widget will be automatically transformed to the new Social Icons block from core.
