### ISSUE TITLE
Add Support Link to Block Card Description

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#56091]
### What

In the block description, let's link to that block's support doc so users can learn how to use the block without contacting support.

### Why

This will help WordPress.com users easily discover our comprehensive resources on how to use each block in the editor. With these support docs, users can learn about blocks more quickly, figure out the settings themselves, and reduce their likelihood of contacting support for basic editing tasks. 

Refs: 
p58i-9Vz-p2 
p2rHU0-Tk-p2

### How

In `.block-editor-block-card__description`, each block has a short description of what the block is about. We could add a HTML link to each block description:

![Edit Page ‹ Brock's Rock Album — WordPress 2021-09-08 at 4 44 12 PM com - Google Chrome](https://user-images.githubusercontent.com/30727666/132459688-28948216-08b2-45a8-89b4-18f8d09d382f.jpeg)

The link text can say "How to use this block" or "Learn more".

Our full list of block docs are at the following two links:

* Page/post editor docs: https://wordpress.com/support/wordpress-editor/blocks/
* FSE docs: https://wordpress.com/support/full-site-editing/fse-blocks/

If we didn't want to add a support link for every doc, this shorter list would be a good start:

Columns block | https://wordpress.com/support/wordpress-editor/blocks/columns-block/
Image block | https://wordpress.com/support/wordpress-editor/blocks/image-block/
Cover Block | https://wordpress.com/support/wordpress-editor/blocks/cover-block/
Blog Posts block | https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/
Buttons block | https://wordpress.com/support/wordpress-editor/blocks/buttons-block/
Form block | https://wordpress.com/support/wordpress-editor/blocks/form-block/
Gallery block | https://wordpress.com/support/wordpress-editor/blocks/gallery-block/
Group block | https://wordpress.com/support/wordpress-editor/blocks/group-block/
Layout grid block | https://wordpress.com/support/wordpress-editor/blocks/layout-grid-block/
Mailchimp block | https://wordpress.com/support/wordpress-editor/blocks/mailchimp-block/
Navigation block | https://wordpress.com/support/wordpress-editor/blocks/navigation-block/
Premium Content block | https://wordpress.com/support/wordpress-editor/blocks/premium-content-block/
Reusable block | https://wordpress.com/support/wordpress-editor/blocks/reusable-block/
Social Icons block | https://wordpress.com/support/wordpress-editor/blocks/social-links-block/
Slideshow block | https://wordpress.com/support/wordpress-editor/blocks/slideshow-block/
Table block | https://wordpress.com/support/wordpress-editor/blocks/table-block/
Subscription form block | https://wordpress.com/support/wordpress-editor/blocks/subscription-form-block/
Tiled Gallery block | https://wordpress.com/support/wordpress-editor/blocks/tiled-gallery-block/

This feature would not be requested on core, because we want to provide users with support content specifically aimed at WordPress.com users.

**Comment by chriskmnds** [comment]
Some additional notes/discussion (and a couple of links) in a Slack thread: p1631084135042600-slack-C029WSAQMT9

**Comment by donalirl** [comment]
Potentially relevant solution: https://github.com/WordPress/gutenberg/pull/11330

**Comment by arcangelini** [comment]
I am working on two things right now to hopefully add this feature.

1. I am attempting to hook into this using `editor.BlockEdit` to add the link into each block setting. This will allow us to get something started soon.
2. I am working on picking up the PR that went stale in core Gutenberg in hopes to get this integrated in the future.

**Comment by arcangelini** [comment]
I have a rough draft of 2 options to implement this on WPCOM, probable in the`editing-toolkit` similar to the `tags-education` package. This is hopefully a short-term solution while I work to maybe implement something in core.

1. Adding this to the sidebar as mentioned above. I was able to use the `blocks.registerBlockType` hook to append the link like so:
<img width="616" alt="Markup 2022-03-16 at 00 17 05" src="https://user-images.githubusercontent.com/33258733/158488257-510db718-f90c-45c6-b103-c11c2301e55b.png">

2. Another option I found was adding it to the toolbar under the "info" icon that opens in a new tab:
![Screen Capture on 2022-03-15 at 23-15-56](https://user-images.githubusercontent.com/33258733/158488489-7d7ff582-1398-401a-965b-0d458e957812.gif)

Tagging some folks who could offer some insight so I can get something tested and launched. 

@jordesign @donalirl @mrfoxtalbot @poligilad-auto @alshakero

**Comment by donalirl** [comment]
My vote would definitely be for the settings sidebar. There is already a description of the block there and so a link to Learn More seems to perfectly belong here.

I feel the inclusion of a doc link in the toolbar would be a distraction from using the block and result in a lot of users clicking it accidentally.

**Comment by jordesign** [comment]
+1 to the sidebar. This also feels like a reasonable WPCOM specific addition.

I really feel like adding anything to the toolbar itself is something that should be proposed in core.

**Comment by arcangelini** [comment]
The advantage the toolbar button has is that it shows even if the user has the sidebar hidden which can be a struggle sometimes for newer users.

Also, the added trick with the block description add-on is making sure it only adds the link in the sidebar. Currently, the description is used in many other places such as when you hover over the blocks in the selector. I missed this when setting up the demo, it will need some additional logic.

<img width="814" alt="Markup 2022-03-16 at 09 53 07" src="https://user-images.githubusercontent.com/33258733/158553326-1c4d410f-4044-4389-89b8-bca541730ecc.png">

I will spend some time today working on that logic.

**Comment by poligilad-auto** [comment]
+1 to the sidebar. 

> I really feel like adding anything to the toolbar itself is something that should be proposed in core.

Agree here as well, we don't want to be introducing a new pattern for this.

BTW, looking forward to when we can open the articles in the new help center instead of sending to the support site :)

**Comment by arcangelini** [comment]
OK, I published a PR to apply these links to the blocks mentioned above there was an issue with 2 of them. I can add more links if you think it would be helpful. Just let me know what else you would need.

1. **Group block** - this has a fancy "variation" option in place where the description should be so it is not able to be added here.
2. **Subscription block** - there is a link to the Reader added to that one which was causing the description to break when adding the support link. In this case, I overwrote the description completely to remove that link.

I am moving on to resurrecting the PR to add a support link option in Gutenberg core.
