### ISSUE TITLE
Editor: uncheck 'uncategorized' when a category is chosen

### ISSUE THREAD

**Issue by shawnajean** [Automattic/wp-calypso#561]
When you select a category in the editor, 'Uncategorized' becomes active, but remains checked. This means that to add a category and not include 'Uncategorized' required the extra step of unchecking it for each post.

![uncategorized-calypso-editor](https://cloud.githubusercontent.com/assets/775884/11348721/374a8142-91f6-11e5-818b-d88ccd521eef.gif)

**Comment by timmyc** [comment]
If we implement some logic to uncheck the default category, we could have users encounter an edge case where they want both their default category, and an additional category checked.  So for that flow, they would have to re-check the default category after it is de-selected.

Perhaps the best solution here is to use the flow in wp-admin, where the default category is not checked until the post is published.

I know @mtias and I have talked about this before, so curious to hear his thoughts on this now that it has come up a few times.

**Comment by aheckler** [comment]
Couldn't we just detect if the default category's name is "Uncategorized" and uncheck if so?

**Comment by mtias** [comment]
@timmyc yes, we've been going rounds with this one. Maybe not trying to be helpful would be better like you say. What if we keep everything unchecked until publish time or user interaction, but add a line of text if everything is unchecked saying "If you don't select a category the post will be assigned to Default Category Name"?

**Comment by timmyc** [comment]
>  add a line of text if everything is unchecked saying "If you don't select a category the post will be assigned to Default Category Name"?

Would this just be shown inside the Tags & Categories accordion?  Alternatively we could include that snippet inside the (i) popover.

**Comment by designsimply** [comment]
<blockquote>If we implement some logic to uncheck the default category, we could have users encounter an edge case where they want both their default category, and an additional category checked.</blockquote>

Consider solving the problem for the most common flow first though, which I believe is: user leaves default category named "Uncategorized," user sets category to something else, publishes, then wonders why they have their custom category name and "Uncategorized" both applied (it's just weird like that, how can it be categorized AND uncategorized…). If you were to look at stats, I bet this flow is a hundred million times more common. :)

<blockquote>Couldn't we just detect if the default category's name is "Uncategorized" and uncheck if so?</blockquote>

This would be great! It'd be nice to "Uncategorized" completely, but at least unchecking it the first time a 2nd category is applied would be a good step forward.

**Comment by mtias** [comment]
@hugobaeta this could be a good one for you to take a look and see if we can approach it better. :)
Maybe we just not select anything by default and add some text saying "Foo would be your default category" until you select something.

**Comment by hugobaeta** [comment]
In calypso we have an issue we don't in wp-admin: you can't manage categories and tags. There's no way to change the default category's name. Maybe that's the problem we should try to solve.

Otherwise, I agree that we should not pre-select anything. If the user doesn't select any category, then the default is assigned automatically (like core does).

**Comment by timmyc** [comment]
> Otherwise, I agree that we should not pre-select anything. If the user doesn't select any category, then the default is assigned automatically (like core does).

+1

Have to agree with the feedback on the current flow - I find the extra step kind of annoying and think following the core flow is the best route right now.

I agree we need a place to manage categories in calypso as well.

**Comment by mtias** [comment]
Let's switch to core flow but look at adding a line or a label to the default category?
