### ISSUE TITLE
Atomic: Can't update featured image on Gutenberg 11.4.1

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#56108]
### Quick summary

On Atomic sites with Gutenberg 11.4.1 plugin active, updating a post that has an existing featured image saved just results in a spinning icon and the image never updates. 

### Steps to reproduce

1. On an AT site, open a post up with an existing featured image
2. Try and update that image in the editor. After selecting the image, a spinning icon shows but never updates:
<img width="274" alt="Markup 2021-09-08 at 09 43 43" src="https://user-images.githubusercontent.com/41035049/132551106-58dfd5df-6591-4e72-bb92-d6290c6319bf.png">

### What you expected to happen

The featured image should update and show in the editor.

### What actually happened

The featured image doesn't update. Spinning icon shows. 

### Context

First discovered in #27919646-hc and reproduced on multiple test sites. 

### Browser

Google Chrome/Chromium, Microsoft Edge

### Simple, Atomic or both?

Atomic

### Other notes

Deactivating the Gutenberg plugin resolves the issuew. Plugin version with issue: Gutenberg 11.4.1issue

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Deactivate Gutenberg 11.4.1

**Comment by synora** [comment]
Triaged. I'm able to replicate this but the new featured image does end up being updated on the page/post. It’s just not displaying in the page/post featured image settings. 

Once you've updated the featured image, you'll notice the "spinning icon" as mentioned in the steps above. However, if you click "Update" in the page/post and then visit the page, the updated featured image appears on the page/post. The "spinning icon" still persists though. 


https://user-images.githubusercontent.com/10015451/132555900-9b21d22b-a9a7-4608-be3e-64c6735a93a7.mp4

**Comment by khristiansnyder** [comment]
Added the GB repo here: https://github.com/WordPress/gutenberg/issues/34671

**Comment by creativecoder** [comment]
I believe this will be fixed in Gutenberg 11.5.0 (see https://github.com/WordPress/gutenberg/issues/34671#issuecomment-915699071)

**Comment by synora** [comment]
Closing this in favor of https://github.com/WordPress/gutenberg/issues/34671
