### ISSUE TITLE
Action Bar: Follow settings styling needs improvement.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56117]
Font weights, line heights, font colors, and switch colors all need further consideration. The settings panel doesn't full match the Calypso Reader, nor the ellipsis menu of the Action Bar itself.

![2021-09-08 14 37 10](https://user-images.githubusercontent.com/349751/132589074-ab43b98e-2503-4306-affa-cd47ecf357d2.gif)

**Comment by kwight** [comment]
@saygunnyc Can you give some guidance here please? I'm assuming we'd like the switch on position to be blue, like Calypso... but would the text all follow the weight and such of the Action Bar's ellipsis menu? I guess all of it could follow Calypso, but the background color might look out of place with the rest of the Action Bar. 🤔 

<img width="419" alt="Screen Shot 2021-09-08 at 2 29 17 PM" src="https://user-images.githubusercontent.com/349751/132589444-9a315dd7-2138-4772-91b0-a341e1d49d8f.png">

**Comment by saygunnyc** [comment]
@kwight Let me think about this, I don't have a direct answer for this yet as I also find the Calypso component's design to be not amazing. Perhaps we should tweak the design here and update both if it's worth it.

Sharing some initial thoughts,
- When I go over the Reader/Manage page and toggle Settings, the active state of that switch is not blue but black. I'm using the default theme.  
- There are def. line-height issues with the Action Bar version, where we explain each one. 
- I'm actually finding the white background over the Action Bar version to be cleaner than the Reader. And we don't really use that gray color in any overflow menus over Domains and Emails management pages under Upgrades.

<img width="251" alt="Examples" src="https://user-images.githubusercontent.com/78876323/132686775-40be642a-30c4-45ce-8584-ac3638ca90c8.png">

- Same goes for the lines in between each. I don't think we need the lines in between each toggle.
- The font size for "Instantly, Daily and Weekly" are off –_larger than the toggle description itself_ breaking the visual hierarchy.
- Also noticing that in your screenshot that the circles over deactivated states of toggles are not perfect circles. Wondering why... Below is a screenshot of what I see.

<img width="363" alt="Screen Shot 2021-09-09 at 15 37 57" src="https://user-images.githubusercontent.com/78876323/132687302-e6d9798b-dd39-408e-9d18-775f9e56ecf6.png">

**Comment by blackjackkent** [comment]
Closed by #56401
