### ISSUE TITLE
Action Bar: Follow settings don't allow for email frequency changes.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56118]
The Follow settings in the Reader allow the user to change their frequency of email delivery, but in the Action Bar, we make the user go to the Reader for that setting (kind of defeating the convenience of having the settings all in the Action Bar). Let's add the email frequency setting to the Action Bar also.

| Action Bar | Reader |
| --- | --- |
| <img width="355" alt="Screen Shot 2021-09-08 at 2 32 05 PM" src="https://user-images.githubusercontent.com/349751/132590030-b1bee67a-b6f3-4a85-b1dc-61af148847a3.png"> | <img width="355" alt="Screen Shot 2021-09-08 at 2 29 17 PM" src="https://user-images.githubusercontent.com/349751/132590044-54ea96e2-baae-4454-869f-d6e56f6042fe.png"> |

**Comment by blackjackkent** [comment]
Resolved in D66785-code
