### ISSUE TITLE
Action Bar: Default values of follow settings are incorrect.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56115]
When following a site with the Action Bar, the new follow settings show all switches in the off position, when the "Email me new posts" settings should be on. The subscribe itself seems to work properly, though (the switch will show as on if verified in the Reader).

| Front-End | Reader |
| --- | --- |
| <img width="350" alt="Screen Shot 2021-09-08 at 2 29 04 PM" src="https://user-images.githubusercontent.com/349751/132588194-92c45e65-62aa-42e3-b896-00d899675672.png"> | <img width="350" alt="Screen Shot 2021-09-08 at 2 29 17 PM" src="https://user-images.githubusercontent.com/349751/132588211-a7f1c279-2c03-43e5-a269-5c0dc7fd503a.png"> |

**Comment by blackjackkent** [comment]
Started looking into this today and got basic functionality implemented (triggering a click event on that toggle during the follow process to make sure we're enabling notification settings appropriately). In discussion with Kirk, we realized that this behavior should also take into account the user's default frequency settings set in their user profile, so I will be combining my work on this and https://github.com/Automattic/wp-calypso/issues/56118 into one diff.

**Comment by blackjackkent** [comment]
This (and #56118) are just about done; will do final tweaks Monday morning and get the diff ready to kick off the new sprint.

**Comment by blackjackkent** [comment]
Resolved in D66785-code
