### ISSUE TITLE
Write button on wordpress.com/home should produce pop-up list of sites that are left aligned

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#56114]
### Steps to reproduce the behavior

1. Go to https://wordpress.com/home
2. Click on write
3. See pop up list of sites that are oddly centered

#### What I expected to happen
List of sites should be left aligned after clicking on write button

#### What actually happened
LIst of sites are centered
![image](https://user-images.githubusercontent.com/5665959/132579179-7f8f2271-e8b3-491b-87b3-7f1601f63207.png)

## Related
Another left-align issue.
https://github.com/Automattic/wp-calypso/issues/56252

**Comment by jordesign** [comment]
Confirmed we can just set a text-align:left; and this will work - but I can't fire up my local copy of Calypso to try and push a PR

```
.site__info {
    width: 0;
    flex: 1 0 auto;
    text-align: left;
}
```

<img width="1216" alt="Screen Shot 2021-09-17 at 8 03 57 am" src="https://user-images.githubusercontent.com/1842363/133691746-9d67fed7-db52-4f8a-ac4f-6219a84dcc2c.png">

**Comment by arthur791004** [comment]
Close this via https://github.com/Automattic/wp-calypso/pull/58340
