### ISSUE TITLE
Domain Connection updates requires URL changes in Calypso's UI

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#56119]
Domain Mapping was changed to Domain connection. Therefore [several docs were updated](1200-gh-Automattic/en.support-docs-content), and hence the permalinks were also updated. 

These doc URLS:

https://wordpress.com/support/domains/map-existing-domain/
https://wordpress.com/support/domains/map-subdomain/
https://wordpress.com/support/domain-mapping-vs-domain-transfer/

are linked in Calypso:

https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/url/support.js
https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/inline-help/contextual-help.js

**Comment by dpasque** [comment]
Noting that for me, it appears that following those links will trigger a redirect to the new URLs.

**Comment by carladoria** [comment]
@dpasque We've set up redirection rules in the Docs. But wouldn't it be better to update the URLs in Calypso directly instead of using the redirection?

**Comment by dpasque** [comment]
@carladoria Oh yes, I very much agree! My apologies, I should have been clearer in my comment - I was just noting that for the prioritization label that I applied (we factor in available workarounds as part of which GH priority labels we apply). It is definitely worth updating those URLs!

**Comment by obenland** [comment]
I was only able to find https://wordpress.com/support/domains/map-existing-domain/ mentioned once in Calypso. I assume the other instances have been updated or removed since this ticket was created?

Fix in https://github.com/Automattic/wp-calypso/pull/69214.
