### ISSUE TITLE
Add Success Message to domain-notice alerts for Connected Domain

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#56122]
### What

We use domain-notice to show a connection error when a mapped/connected domain is not set up correctly. Can we also show a success message when the domain is mapped successfully?

### Why

A typical WordPress.com user does not understand domains, DNS, and propagation. When a domain is not yet mapped correctly, we show an error to prompt them to fix it. However, when the domain is successfully connected, the error disappears. There is no visual confirmation that things are working now. 

By showing a success message, we can reassure the user that they have completed the task successfully, and can just wait for propagation to finish.

This will help reduce the number of customers contacting support to ask if they have mapped their domain correctly, a common request. An example: #31048624-hc

### How

At Upgrades → Domains → [click on a mapped domain], the connection error says:

"Connection error: The name servers are incorrect. Please try this step again."

![image](https://user-images.githubusercontent.com/30727666/132598640-52c56156-7d3f-4bbd-8f8c-f600c8047c49.png)

When we detect the domain is mapped correctly, can we show:

"Connection successful! The domain may take up to 72 hours to become operational."

![image](https://user-images.githubusercontent.com/30727666/132599282-c8ce824e-0e50-4ce6-b1f1-b51ab1cf406c.png)

(and replace the warning gridicon with a checkmark gridicon.)

We can show the notice for 72 hours, after which it could be shortened to "Connection successful" or else hidden entirely.

**Comment by poligilad-auto** [comment]
I like it @donalirl! Good idea. I'll add this to the current work going on to redesign the domain management pages: p9Jlb4-30z-p2.

**Comment by donalirl** [comment]
Closing this as connected domains show an 'active' status now in the new interface.
