### ISSUE TITLE
Action Bar: The only way to dismiss the follow settings is to unsubscribe.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56120]
When we subscribe to a site with the Action Bar, the Follow settings pop up – but then they can't be dismissed (the page would have to be refreshed). The obvious user action is to click the button they're stemming from visually, which will... unsubscribe the user. 🙃

![2021-09-08 14 52 18](https://user-images.githubusercontent.com/349751/132591172-7c280532-47f7-4ecf-8c5b-ac83ced10ee5.gif)

**Comment by kwight** [comment]
I'm thinking any click outside of the popup should close it: the ellipsis, background (and the Following button). We could also introduce a closing `X` to the top right of the popup?.. @saygunnyc does any of this make more sense to you for handling this issue?

**Comment by saygunnyc** [comment]
> I'm thinking any click outside of the popup should close it.

💯 and yes, clicking on the overflow menu should also close it. It's weird to have two pop-up menus open at the same time over each other. Also, vice versa, once the overflow menu is opened, clicking somewhere else including the follow button should deactivate it.

> We could also introduce a closing X to the top right of the popup?

This may not be necessary as both menus are visually attached to the module and not independent modals. So they act like site dropdown menus, where we don't usually expect an "X" button to close. Also, that would make these a bit more crowded than they are which may not be a good idea. In my past experiences users have always managed to click somewhere else to close menus like these. In a few rare cases, they clicked somewhere else with frustration but then learned that closes the menu.

**Comment by blackjackkent** [comment]
Resolved in D66911-code
