### ISSUE TITLE
Accordion block: Video block added inside the accordion item disappears when previewed but reappears if browser is resized.

### ISSUE THREAD

**Issue by flameslash** [Automattic/wp-calypso#56126]
**Steps to reproduce the behavior**

1. Create an accordion block on the page.
2. Within the accordion item content, add a video block in it.
3. Save the changes and preview the site and see if the videos display properly

**What I expected to happen**

Videos should display in the page preview

**What actually happened**

The videos in the accordion element do not show up on the preview. Only when you resize the browser will it display properly.

**Reproducibility (Consistent, Intermittent)**

Only able to reproduce this on user's site. It's not happening on all accordion blocks as there are some blocks that have videos working properly without the need to resize

**Workarounds performed**

Recreate the affected accordion blocks and the content in it - did not resolve the issue

GIF link -> https://d.pr/i/8L2j3L

Reported in 31423312-hc
Follow up ticket here -> 4284307-zd-woothemes

**Comment by Greatdane** [comment]
The Accordion Block is from the plugin [CoBlocks](https://wordpress.org/plugins/coblocks/) - so does not affect Simple sites. 

I am able to replicate this issue on Atomic sites only. Self-hosted sites do not seem to be affected, so it could be a calypso issue. 

To confirm on WordPress.com Atomic sites, placing a video within an Accordion Block stops the video from loading unless the page is resized.

**Comment by Greatdane** [comment]
To add, the issue seems to be, by default, the height and width of the videpress iframe is 0, rendering the video practically invisible. When you resize the window, the height/width changes and the video becomes visible. 

```
<iframe title="pexels-mart-production-7565817-mp4" width="0" height="0" src="https://videopress.com/embed/slMoq7y2?preloadContent=metadata&amp;hd=1" frameborder="0" allowfullscreen="" data-resize-to-parent="true"></iframe>
```

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
What needs to be done is that when scanning for videopress elements on the page, it should also check if there is a `<details>` tag in its parents/ancestors in the dom tree.

Just like how the script listens for window resize event, also listen to the `toggle` on that `<details>` tag this way.
```
details.addEventListener("toggle", event => {
  if (details.open) {
    /* resize the videopress player */
  }
});
```

The codebase to work with is in https://github.com/Automattic/videopress-iframe. This seems like a simple script.

Also, test on actual Atomic sites not ephemerals as VideoPress don't work there.

**Comment by alshakero** [comment]
Fix is now live! It would be nice if you inform the user @flameslash. Thanks!
