### ISSUE TITLE
Calypso notifications: Comments notification indicator with no unread comments

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#56135]
### Quick summary

Our customer noticed a comments notification indicator in the dashboard menubar. There are no apparent comments or other indication why this number should appear here.

![Capture_2021-09-09 at 12 13 21@2x](https://user-images.githubusercontent.com/2912202/132658419-6b036427-0cc8-4f4a-8dcd-600de27fa2ef.png)

Also see here:

https://user-images.githubusercontent.com/2912202/132658466-faae4010-73ef-4198-9416-ddae34c90bca.mp4

### Steps to reproduce

1. Checked for any unread notifications in the Comments section;
2. Also checked for unread comments under the notification bell;
3. Marked unread comments as read (no change);
4. Ran a full Jetpack sync (no change);
5. Cleared the site's cache using `wp cache flush` (no change);
6. Previous HE disabled all plugins, and switched to a default theme (no effect);
7. Checked `php-errors` and the only error that seemed vaguely related is this one:

```
[09-Sep-2021 07:38:10 UTC] PHP Notice:  is_singular was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in /wordpress/core/5.8.1/wp-includes/functions.php on line 5663
```

### What you expected to happen

There shouldn't be a notification for no apparent reason.

### What actually happened

There is a notification for no apparent reason.

### Context

31572716-hc with a follow-up in 4284925-zen

### Operating System

macOS

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Doesn't seem to be related to the theme.

### Reproducibility

Consistent

### Severity

One

**Comment by Robertght** [comment]
Thank you! I've flagged this one for @Automattic/flow-patrol-create for now.

**Comment by Addison-Stavlo** [comment]
I think this may have been resolved with pe7F0s-1kj-p2 and https://github.com/Automattic/wp-calypso/pull/83006 

I am unable to repro after those changes and don't see any more bumps of this issue, so closing it. Please reopen if this surfaces again!
