### ISSUE TITLE
Posts: Drafts indicator in sidebar does not update correctly

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#5613]
This is on the /posts page for a single site. If I have one or more drafts, and see the (1) indicator in the sidebar:

![screen shot 2016-05-26 at 11 23 11 am](https://cloud.githubusercontent.com/assets/1464705/15585499/72c8a7ce-2334-11e6-8a45-698900f9a3c5.png)

If I then go and trash that draft, the (1) does not go away. If I delete it permanently it doesn't go away either. It seems as though that number is not updating at all based on modifying drafts.

**Comment by mtias** [comment]
@aduth another one for counts reconciliation. We need something robust here that just works across the app.

**Comment by lancewillett** [comment]
Should be fixed with https://github.com/Automattic/wp-calypso/commit/44ea5671c0250e6909214cd04cf3ca40c13e86f1

Also, the UI has changed since this report and we no longer show the draft count in the same way.
