### ISSUE TITLE
Feature Request: "Spacer" block as a child block within "Features" block

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#56139]
### What

I would like "Spacer" block to be available to be added within "Features" block.

### Why

Requested by a customer on 4279516-zen. The spacer block will allow them to add a space between the feature heading and feature body. Right now, they are using a workaround in the form of a paragraph block with white text. I recommended using CSS to create the space, but an ideal solution would be making spacer block available.

### How

The spacer block is available outside of that block area:

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/18581859/132686667-30c3f912-8245-4ca2-944f-37d54c6bbb6b.png">

But not when one attempts to add inside the "Features" block. Only 5 others are available instead:

<img width="1589" alt="image" src="https://user-images.githubusercontent.com/18581859/132686733-85d64a6a-25c4-4309-b924-f240feac6c4f.png">

**Comment by arunsathiya** [comment]
"Features" block is part of CoBlocks, thus part of "WordPress.com Editing Toolkit", I believe.

**Comment by arunsathiya** [comment]
Actually, it looks like we maintain our own coblocks repository: https://github.com/Automattic/coblocks

**Comment by synora** [comment]
@dpasque 👋 
I've triaged this feature request that involves our Spacer Block and the CoBlocks Feature Block. Would it be best to keep here or place it in https://github.com/godaddy-wordpress/coblocks/issues?

**Comment by dpasque** [comment]
@synora Hi there! 👋 

I would say that this issue actually probably belongs best in the GoDaddy repo! We pull from there and adapt in to WPCOM, but this looks like a limitation that exists natively in their block!

**Comment by dpasque** [comment]
@synora Also, I'm migrating it ATM! (Just as a heads up so we don't both do it! 😄 )

**Comment by dpasque** [comment]
Opened here: https://github.com/godaddy-wordpress/coblocks/issues/2032 

Closing this issue in favor of that one!
