### ISSUE TITLE
Music player widget broken on Ixion

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#56142]
### Quick summary

URL: corthantortosabearder.com
Theme: Ixion

PROBLEM:
Music player widget in the sidebar doesn't work.
It doesn't appear, only a blank area in the sidebar.
It appears in the customizer but not on the published page.

WHAT I FOUND:
* I can repeat the error on a test site too.
* It only occurs with the Ixion theme.
* It shows with the 2015 theme but not Ixion. 
* Simple site, personal plan

### Steps to reproduce

Add a music player widget into the sidebar on personal plan with Ixion theme.

### What you expected to happen

The music player to appear

### What actually happened

A blank space appears in the sidebar

### Context

#4284195-zd

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Ixion not 2015.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by synora** [comment]
Hi there @rickmgithub 👋 
I'm unable to replicate this. Both the Legacy and Block Widget are working as expected for me: 


<img width="533" alt="Screen Shot on 2021-09-15 at 11-46-43" src="https://user-images.githubusercontent.com/10015451/133466327-08d91529-f244-4fa4-821f-37e322f1e4be.png">


Are you still able to replicate this?

**Comment by rickmgithub** [comment]
Thanks @synora Looking at the ticket it looks like someone did something somewhere that fixed it. User happy. So looks like it's all good now.

**Comment by dpasque** [comment]
Closing as it seems to no longer be reproducing.
