### ISSUE TITLE
Connected domains: expiration message is confusing

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#56155]
### What

I would like the "expires in __ days" message displayed on connected domains to be better clarified.

### Why

Context: 4286390-zen

Example of the expiry message I'm referring to:

<img width="1091" alt="Markup 2021-09-09 at 16 49 09" src="https://user-images.githubusercontent.com/5630717/132763935-7a9e1b48-943b-41de-b2c6-82876b34b6d4.png">

This message also displays after clicking on the domain (at `/domains/manage/{primary}/edit/{domain}`).

This user was confused about the expiration date of their domain which was connected to their WordPress.com site. At _My Site > Upgrades > Domains_, it displays the above message, which implies that their domain itself expires in 25 days.

As the domain isn't registered here, we don't display the domain's actual expiration date. Instead, this message is referring to the domain _connection subscription_, which is part of their WordPress.com plan.

In this particular instance, the message should likely not be displayed at all. Their plan was set to auto-renew, so the domain and its connection subscription were never under threat of expiring.

### How

The language should be altered to better explain _what_ is expiring at this time. It might also be beneficial to show an exact date as well, rather than "in x days," which could lead to extra confusion. Clarifying here that their domain connection subscription is part of their WordPress.com plan would be a bonus.

It would be particularly nice if the message wasn't displayed – and the yellowish warning left-border was removed – if the user's plan (and therefore their domain connection subscription) were set to auto-renew.

**Comment by inaikem** [comment]
Suggested update text:

- Your WordPress.com domain connection subscription expires [in XX days / on DATE].
- Your WordPress.com domain connection service expires in [XX days / on DATE].
- Your domain connection subscription expires in [XX days / on DATE].
- Your domain connection service expires in [XX days / on DATE].


Cc @delputnam + added to pod project board for better Domain Pod visibility 🙏
