### ISSUE TITLE
Include "Add Page to Menu" Option to editor-post-publish-panel 

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#56157]
### What

Add a link to menu settings to the panel that shows after publishing a new page.

### Why

After publishing a new page, a common next step is to add the page to the navigation menu. However, there is nothing to guide a user in the editor to go to their menu settings to add the page there. In the post-publish prompt, we can add this suggestion to smooth out the process for users. 

A common support request is for users to add a new page, and not understand why it isn't appearing in their menu. Example: 25445464-hc Adding a prompt to add the page to the menu can help reduce the number of customers who contact us about this.

Suggested by @msilbers !

### How

The editor-post-publish-panel:

![image](https://user-images.githubusercontent.com/30727666/132798719-738859eb-2040-471a-9d1d-a5d5805dae21.png)

**Comment by jordesign** [comment]
I've opened this up as a core Gutenberg issue - as recommended by @simison 
https://github.com/WordPress/gutenberg/issues/38973
