### ISSUE TITLE
Email Templates: Button text is title cased.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56152]
The button text in our new subscriptions email templates is title cased, instead of sentence cased. All buttons should be checked that only the first letter is capitalized (bringing us consistency with Calypso).

| Current | Calypso |
| --- | --- |
| <img width="733" alt="Screen Shot 2021-09-09 at 12 45 16 PM" src="https://user-images.githubusercontent.com/349751/132753373-61936a54-9f6c-45f6-b10a-dd908e7d078a.png"> | <img width="1206" alt="Screen Shot 2021-09-09 at 12 45 06 PM" src="https://user-images.githubusercontent.com/349751/132753347-d8314096-321c-4fd3-9355-4e1468182639.png"> |

**Comment by kwight** [comment]
@saygunnyc Double-checking this is what you wanted?..

**Comment by saygunnyc** [comment]
💯

**Comment by kwight** [comment]
FYI @andres-blanco while doing new templates.

**Comment by kwight** [comment]
I've confirmed that both the existing new templates have been corrected to sentence-cased buttons in D66421-code and D66481-code
