### ISSUE TITLE
Mention SSL on Domain Security Page

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#56162]
### What

Add SSL description and support doc link to the domain security Calypso screen.

### Why

SSL is something that many site owners check for when creating a new site, but SSL is not mentioned on the domain security page. This page is accessible by going to Upgrades → Domains  → clicking on a domain → click 'Review your domain security'.

We should mention SSL here so that users have a visual confirmation that SSL is protecting their site.

We should also link to the support doc https://wordpress.com/support/https-ssl/ for customers who wish to learn more, or figure out why their domain doesn't have SSL yet.

### How

I am not familiar with the technical side of this - is SSL the same as "HTTPS encryption"?

If yes, I would change the opening sentence on this page to:

"Strong encryption with SSL is critical to ensure the privacy..."

If no, I would change both mentions of "HTTPS encryption" (in the title and opening line) to "HTTPS & SSL encryption".

Just my suggestions :) Feel free to go with whatever makes sense.

For the link to the support doc, we could add a new card above the two current support doc links with the text "Frequently asked questions about HTTPS and SSL":

![b95b8464-d22b-4639-820a-0769d538e933](https://user-images.githubusercontent.com/30727666/132821129-106fa9c2-3b5a-4abf-9705-783bd2cd8020.png)

(we could also replace one. In fact, it's a bit strange that we link to payment and form docs on this screen. I understand the connection to encryption, but it's not an association a user would make.)

**Comment by synora** [comment]
➕ 1 to this suggestion. 

Even having a "lock" icon next to the domain in Upgrades > Domains would be helpful.

![Annotation on 2021-09-15 at 13-13-43](https://user-images.githubusercontent.com/10015451/133479116-e9fbc001-70af-462d-8416-05b7ce9ea491.png)

**Comment by donalirl** [comment]
Now present via UI updates and the Learn more link
<img width="757" alt="Screenshot 2024-01-25 at 12 28 38 pm" src="https://github.com/Automattic/wp-calypso/assets/30727666/5726cb3a-b08d-4149-b388-6075dcdf1a99">
