### ISSUE TITLE
Domains Manage Page: Connection Error Status is Wrong

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#56167]
### Quick summary

The Domains Manage page for all sites on an account is displaying a Connection Error for a mapped domain even when the domain is configured correctly. 

The Domains Manage page for the particular site does not display an error, but the Domains Manage page that combines all sites is displaying an error even after the domain has been configured correctly.

![image](https://user-images.githubusercontent.com/6737345/132856671-7fae7dbf-4dc1-4e8d-afff-626fcfd4551b.png)

### Steps to reproduce

1. Go to Domains Manage page for all sites here: https://wordpress.com/domains/manage

### What you expected to happen

I expected there to be no error when a mapped domain is connected properly.

### What actually happened

There was an error for the mapped domain that said: 
Connection Error: The name servers are incorrect. Please try this step again

### Context

This is a report for a particular site
4285313-zen

### Other notes

I was wondering if it could be related to this update: https://github.com/Automattic/wp-calypso/pull/54649

**Comment by Robertght** [comment]
Thank you for reporting this @ccwalburn ! 

I initially asked here: slack-C0761SX4K/p1631217896181800, however, I think this might be suitable for the @Automattic/pod-domains.

**Comment by delputnam** [comment]
I've created a task for Nomado to look into this.

**Comment by gius80** [comment]
This seems be resolved after Domain Management redesign (I double check on the user account). 
I'll close this issue.
