### ISSUE TITLE
Change Block Widget Help Links from .org to .com + Remove Plugin Suggestion

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#56161]
### Quick summary

The block widgets interface links to .org docs in two places. They should be changed to .com.

Also remove the suggestion to install a plugin for sites without access to plugins

### Steps to reproduce

On a WordPress.com site:

1. Go to Appearance → Customize →  Widgets
2. View the welcome modal:

![image](https://user-images.githubusercontent.com/30727666/132818199-106cb8c0-1752-4f1b-a153-86bd2d956ab7.png)

3. Click the link "Here's a detailed guide."
4. Click 'Got it'
5. Click the ... (ellipses) menu
6. Click 'Help':

![image](https://user-images.githubusercontent.com/30727666/132818335-55f0c13b-5c17-47db-9b9a-4acd5bb58c5d.png)

7. Also observe link to classic widgets plugin:

![markup-2021-08-10-at-10 37 22-1](https://user-images.githubusercontent.com/30727666/135225445-bf52350b-bb6a-45e1-ad35-169b766c5b04.jpg)

### What you expected to happen

I expected to arrive at https://wordpress.com/support/widgets/ when clicking the links in steps 3 and 6 above.

I expected to not see a link to install a plugin to restore the old interface, when I don't have the ability to install plugins on my simple site.

### What actually happened

I was taken to .org docs, which are not as relevant for a WordPress.com user. I was prompted to install a plugin to restore legacy widgets.

### Context

p7DVsv-cqD-p2#comment-37136

p7DVsv-cqD-p2#comment-37129 

### Simple, Atomic or both?

Simple, Atomic

### Other notes

Mentioned also in p58i-bfk-p2

### Reproducibility

Consistent

### Severity

All

**Comment by StefanNieuwenhuis** [comment]
Note to myself: How to disable the default tour (p1633010164007000/1633004581.003300-slack-C02E88CMSP9, p7DVsv-cqD-p2#comment-37138 & p7DVsv-cqD-p2#comment-37190).
