### ISSUE TITLE
Block Patterns: Shrinking block pattern previews

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#56182]
### Quick summary

While working with a customer in a Quick Start session, I noticed that block pattern previews started shrinking as the previews were loaded, like this:

https://user-images.githubusercontent.com/2912202/132982276-55c0f346-6686-4a4b-baf4-9cb73c09d7d2.mp4

### Steps to reproduce

1. Open a post in the block editor
2. Open the left sidebar to view blocks and block patterns
3. Select the _Patterns_ tab
4. See block pattern previews shrinking vertically.

### What you expected to happen

I expected block pattern previews to load completely, and not resize themselves automatically, like this:

https://user-images.githubusercontent.com/2912202/132982516-118f4efc-7907-4e5c-a265-a0f92f9da16c.mp4

### What actually happened

Block pattern previews resized themselves automatically.

### Context

I noticed this in a Quick Start session with a customer. The ticket is 4284652-zen

### Operating System

Windows

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Other notes

The customer was using the Windows WordPress.com app, version 7.2.0 on Windows 10. I was not able to reproduce this issue using the macOS WordPress.com app (version 7.2.0).

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is likely to use the browser. The user was using the Windows WordPress.com app.

**Comment by pauljacobson** [comment]
I saw another instance of this issue in another Quick Start session where our customer was using Chrome on Windows. I don't have version details, though.

https://user-images.githubusercontent.com/2912202/133112126-3efeae40-89c0-4b28-97f2-4b91c4a57b83.mp4

**Comment by synora** [comment]
I was able to reproduce this on Chrome (Version 93.0.4577.63 (Official Build) (x86_64)) with my MacBook Pro (Big Sur 11.6). 

The resizing seems to happen when I first select the "Link In Bio" patterns category.  After that, if I select a new category of patterns and then return to the "Link In Bio" patterns, the resizing doesn't occur: 


https://user-images.githubusercontent.com/10015451/133447202-542ef02e-90f2-4835-83a3-857cd2ae1be4.mp4




I don't have the macOS WordPress.com app installed at the moment.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
Issue is similar to https://github.com/Automattic/wp-calypso/issues/56077 except this one is expanding.

**Comment by yansern** [comment]
Let's consolidate all to https://github.com/WordPress/gutenberg/issues/34729.
