### ISSUE TITLE
Link for wp-admin menu editor

### ISSUE THREAD

**Issue by wprhunt** [Automattic/wp-calypso#56185]
### What

Add link for the wp-admin version of the menu editor instead of only offering a link to the customizer

### Why

I've had two customers today request how to access the /wp-admin/nav-menus.php and having no option to do so means they have to manually go to that page in the address bar.

hc-31567597
hc-31629565

### How

Possibly add an additional link to the appearance menu of the sidebar for Advanced Menus or even replace the URL for the Appearance -> Menus link to still take the customer to the classic menu editor instead.

**Comment by inaikem** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/55388
