### ISSUE TITLE
Checkout: remove concept of required fields

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#56209]
Assuming there's no issues with https://github.com/Automattic/wp-calypso/pull/55904, we can remove the `isRequired` properties of each contact field and all the mechanisms that support the concept of required fields.

**Comment by DavidRothstein** [comment]
Leaving this in the inbox for now (in case it's a cleanup we want to do soon, given that it's an immediate followup of something else).

**Comment by sirbrillig** [comment]
This was done in https://github.com/Automattic/wp-calypso/pull/57212
