### ISSUE TITLE
Marketplace: Implement automatic translations for Table Rate Shipping and Checkout Field Editor extensions

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#56238]
Table Rate Shipping – delete https://translate.wordpress.com/projects/woocommerce/table-rate-shipping/ (try migrating existing translations to the new project before that?) and keep https://translate.wordpress.com/projects/woocommerce/woocommerce-table-rate-shipping/. Move to Extensions GP project for automatic inclusion in WK.

Checkout Field Editor – delete https://translate.wordpress.com/projects/woocommerce/checkout-field-editor/ (try migrating existing translations to the new project before that?) and keep https://translate.wordpress.com/projects/woocommerce/woocommerce-checkout-field-editor/. Move to Extensions GP project for automatic inclusion in WK.

**Comment by dlind1** [comment]
Moved the projects and informed the maintainers so that they could do some smoke testing.

**Comment by cpapazoglou** [comment]
@dlind1 we will no be shipping Checkout Field Editor in the marketplace.

Table Rate Shipping is already included though, are the translations resolved by now? Can we close this issue?

**Comment by dlind1** [comment]
Yes, closed.
