### ISSUE TITLE
Task: In WP notifications drawer, notifications should be left-aligned

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#56252]
## Description
All notifications in the WP Notifications Drawer should have left alighed text, currently most (or all) all centered aligned causing the copy to look awkward.  See the [entertaining slack thread for many more examples](p1631653328406200-slack-C029SB8JT8S).

Good to also prevent "orphaned" or "widowed" text using the [`preventWidows` method.](https://github.com/Automattic/wp-calypso/pull/41427/files#diff-b8607662e0fb39ee2bf57962ebe5a3df1cbc0851ac26fa9c64afb63af0dcb458R11)

### BEFORE/CURRENT:
Some examples of notifications in the Notifications Drawer:

![image](https://user-images.githubusercontent.com/5665959/133336799-dd2a2c21-b878-4a23-b348-b8d2ee70ec0e.png)

![image](https://user-images.githubusercontent.com/5665959/133336868-a7409bf2-a68c-42c5-b359-67ea1fb7ebd4.png)

![image](https://user-images.githubusercontent.com/5665959/133336846-9c86f1c8-59b1-4937-8541-90349cab9f60.png)

### EXPECTED:
Copy should be left aligned

![image](https://user-images.githubusercontent.com/5665959/133337015-6dbaf2d6-84d6-44df-b744-9b2f38e516ea.png)
Example of "widowed" text (single word hanging on second line)

## Testing
Ensure the copy content of the notifications are left-aligned
@ianstewart [has volunteered to be tester](p1631653453409800-slack-C029SB8JT8S)!

### Dev Checklist

- [ ]
- [ ]

### Related

https://github.com/Automattic/wp-calypso/issues/56114

**Comment by arthur791004** [comment]
Closed as https://github.com/Automattic/wp-calypso/pull/58388 is shipped!
