### ISSUE TITLE
Base64 image when embedding a blog post

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#56263]
### Quick summary

When a blog post is embedded to a post, the image from the post embedded isn't showing and shows a base64 in the image link:

`data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PScwIDAgNDgwIDI3MCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48L3N2Zz4=`

When tried to decode the base64, it looks like this <svg viewBox='0 0 480 270' xmlns='http://www.w3.org/2000/svg'></svg> (it's an empty SVG)

### Steps to reproduce

1. Open the page editor. 
2. Add an embedding block and enter the link https://spacebetweenblog.com/the-mason-dixon-trail/mason-dixon-trail-map-7/
3. The page gets embedded, but the image shown is empty. The page does have a featured image assigned.
4. On the front end, the image isn't showing, it shows grey area.

Screencast video: 

https://user-images.githubusercontent.com/7382505/133366946-78a90af1-375a-4883-9122-459faf643b67.mov

### What you expected to happen

The featured image should show up from the page when it is embedded

### What actually happened

The image is shown as empty srv image. 

### Context

Customer report

### Operating System

Windows, macOS

### Simple, Atomic or both?

Atomic

### Other notes

Got a related bug for classic editor which was closed: https://github.com/Automattic/wp-calypso/issues/16715

### Reproducibility

Consistent

### Severity

One

**Comment by kdevnel** [comment]
Just a note on this, the issue on this specific site disappears when you change to a different theme so I'm putting this down to a theme issue rather than an actual bug on our end for now.

Closing the issue and we can reopen if further information to indicate a bug comes out.

**Comment by inaikem** [comment]
NB. The theme is `CheerUp 7.6.0` by ThemeSphere: https://cheerup.theme-sphere.com.
