### ISSUE TITLE
Signup: Update Mayland starter design

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#56261]
### Details

I've swapped out CoBlocks Masonry Gallery for Columns + Images block (see p4TIVU-9B7-p2 for details as to why).

### Checklist

- [x] [Update Mayland demo](https://maylandstarter.wordpress.com/)
- [x] Update Mayland theme annotation

### Related

#56567

**Comment by roo2** [comment]
It looks like this has been done already (changeset 59607 in wpcom-themes)

**Comment by roo2** [comment]
sorry, it looks like this isn't quite done yet

**Comment by roo2** [comment]
PR to update annotations D68110-code

**Comment by roo2** [comment]
closed with D68110-code
