### ISSUE TITLE
First plug-in installed doesn't appear to be installed

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#56271]
### Steps to reproduce the behavior

1. Create a site on the business plan on wordpress.com
2. Go to plug-ins in the menu
3. Choose a plug-in (I used google-analytics-for-wordpress but any should be fine)
4. The plugin information will be displayed. Press install
4. Get the dialog explaining the site will be atomised, press Continue
5. This goes back to the plugin screen which now displays 'Installing plugin name' (it's also atomising the site)
6. Wait patiently, after some seconds it will say 'Activating plugin name',
7. The message will quickly disappear
8. The plugin screen now displays 'Install' again - even though it just told us for tens of seconds it was installing/activating it
9. Open up Plugins in the menu in a new tab, or look at the blog RC - it should show that the plugin is actually installed
10. Go back to the first tab, press Install again
11. A message will say 'Installing plugin name' (in a different position to the first time), in fact this will never finish.

#### What I expected to happen
A confirmation that the plugin was installed, possibly a CTA of what to do next

#### What actually happened

The plugin screen now displays 'Install' again and pressing 'Install' just says 'Installing plugin name' but doesn't seem to do anything

#### Is there any console output or error text?
The browser console says '[`slug` is not correctly defined](https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/packages/wpcom.js/src/lib/site.plugin.js#L21)'

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Happens on every freshly atomicised site. 
Accessing the plug-in screen after that works as expected.
The plugin is actually installed, it just looks like it's stuck.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://user-images.githubusercontent.com/93301/133409804-e8db9fc8-1fe3-4618-9342-1b3387955031.mp4

**Comment by cpapazoglou** [comment]
Thanks @dsas for reporting!

Solving this bug #56792 by applying the designs oU6nEIeiKSg8CayhEtgR6b-fi-6452%3A46534 will probably make current issue obsolete cause users will get into a "installing - activating - thank you" flow outside the plugin details page.

**Comment by cpapazoglou** [comment]
FWIW, this was eventually fixed by https://github.com/Automattic/wp-calypso/issues/57999
