### ISSUE TITLE
Explore bugs or missing features of Calypso site plugins page

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#56277]
After deploying https://github.com/Automattic/wp-calypso/pull/55938 which allowed direct access to the Calypso plugins page - `https://wordpress.com/plugins/[DOMAIN]`, now is a good time to explore whether:

- there is feature parity in contrast to `/wp-admin/plugin-install.php` 
- features are working as expected

**Comment by ianstewart** [comment]
Plugin installation flows worked as expected. It was a bit strange that my first plugin was auto-activated for me after installation while subsequent ones weren't. I'm assuming that's a separate issue however.

**Comment by cpapazoglou** [comment]
I tested `https://wordpress.com/plugins/[DOMAIN]`:

✅ I can install a plugin from the list, it gets auto-activated 
✅ Searching for a plugin returns the wp.org results in the same order
✅ I can install a .org plugin from a zip file

❌ I can install a premium (not .org) plugin from a zip file but the details page doesn't work cause it can't find the plugin details in the .org repo
![](https://cln.sh/EjMhDI+)
❌ Searching for a plugin returns a limited search of results, no pagination
❌ `Search by author or tag` functionality is missing
❌ The install button is missing on some cases from Business simple sites - after running a headstart on that site problem was fixed.

@JanaMW27, I am sure that the `pagination` problem will be fixed with the updated designs. Should we wait for the designs to be implemented before we default to that page? 

Also, regarding
> I can install a premium plugin from a zip file but the details page doesn't work cause it can't find the plugin details in the .org repo

should we redirect to WP Admin after installing a premium plugin from a zip file? Chances that Calypso knows something about that plugin are so limited. Eg I can upload my custom plugin.

**Comment by JanaMW27** [comment]
Hello @cpapazoglou!

Regarding the pagination issue, we do have pagination in the new design; fixing it now in calypso (where it looks like there is no pagination) may be a waste of time before implementing the new design. But, if it will take more than three months to implement the new design, then maybe we should bring the pagination into calypso.

Regarding the plugin installation through zip files, I would like to know if the plugin detail page will look different if we redirect them to WP admin than what it looks now.

**Comment by cpapazoglou** [comment]
> Hello @cpapazoglou!
> 
> Regarding the pagination issue, we do have pagination in the new design; fixing it now in calypso (where it looks like there is no pagination) may be a waste of time before implementing the new design. But, if it will take more than three months to implement the new design, then maybe we should bring the pagination into calypso.
> 
> Regarding the plugin installation through zip files, I would like to know if the plugin detail page will look different if we redirect them to WP admin than what it looks now.

Good points! 
> I would like to know if the plugin detail page will look different if we redirect them to WP admin than what it looks now.

AFAIK, there is no WP Admin plugin details page. I was thinking of redirecting users to `/wp-admin/plugins.php`

**Comment by cpapazoglou** [comment]
Closing this in favor of 
https://github.com/Automattic/wp-calypso/issues/56792
https://github.com/Automattic/wp-calypso/issues/56793
