### ISSUE TITLE
Me: stale 2FA token leads to too many API requests

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#5627]
#### Steps to reproduce
1. have a stale 2FA token
2. go to http://calypso.localhost:3000/me
3. see the "please enter the verification code" modal
4. open the developer console
#### What I expected

When we make an API request that fails because of a stale 2FA token, we wait with future requests until we have a valid token again. 
#### What happened instead

We keep making requests for `profile-links`, apparently in no way throttled. This is probably not very nice to the API, and possibly also the user's bandwidth in low-bandwidth contexts. 

GIF:

![profile-links](https://cloud.githubusercontent.com/assets/23619/15606822/db18dc56-240e-11e6-98ea-7559add6574d.gif)

**Comment by lancewillett** [comment]
Good catch for both performance and UX.

**Comment by rachelmcr** [comment]
Bug scrub: 31Oct2016

I retested this issue by deleting the `twostep_auth` cookie from my browser. I can reproduce the behavior described above, which also seems related to this issue with the `Get /me/settings` endpoint returning a 401 error when you have a stale 2FA token: https://github.com/Automattic/wp-calypso/issues/202

**Comment by lsinger** [comment]
This isn't happening for me anymore: 

![stale-token](https://user-images.githubusercontent.com/23619/34870728-3a695108-f78b-11e7-9bac-64d0fa5acab7.gif)

Closing.
