### ISSUE TITLE
Calendly Block: Preview in the block inserter is not loading as before

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#56273]
### Quick summary

Previously, the preview of the Calendly Block in the main block inserter (at the top right of the Editor) showed an image with a calendar view and how Calendly Block looked like with a Calendly linked pasted in the Block. Now it doesn't do that and loads a message of error in French stating that that URL is no longer used/available as seen here:

![image](https://user-images.githubusercontent.com/39308239/133422544-66247234-bb24-4232-ac15-a5d6da2ffd53.png)

### Steps to reproduce

1. In a Post or Page, click the `+` in the top right to bring up the global block inserter
2. Search for Calendly
3. Hover over Calendly Block to see a preview panel to the right

### What you expected to happen

An image with a calendar view and how Calendly Block looked like with a Calendly linked pasted in the Block. If I recall correctly, it sued to look like this:

![image](https://user-images.githubusercontent.com/39308239/133425564-349ff843-7cb5-41b1-ae50-62a1fb786e7d.png)

### What actually happened

Preview doesn't load the full animation and shows some error in French:

![image](https://user-images.githubusercontent.com/39308239/133422544-66247234-bb24-4232-ac15-a5d6da2ffd53.png)

### Context

Observed during a Quick Start session 4293818-zd-woothemes

https://user-images.githubusercontent.com/39308239/133423313-e61c8106-8b2c-43e9-825c-f47f46b6886e.mov

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by synora** [comment]
Triaged. Can replicate.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
The block preview points to `https://calendly.com/wordpresscom/jetpack-block-example?background_color=ffffff&embed_domain=wordpress.com&embed_type=Inline&hide_event_type_details=0&primary_color=00A2FF&text_color=4D5055`.

This URL returns that page shown in the screenshot.

The constant the modify is `CALENDLY_EXAMPLE_URL` in `jetpack/extensions/blocks/calendly/index.js`. It seems that this line was inserted from this PR https://github.com/Automattic/jetpack/pull/14814.

@Copons Do you own the `wordpresscom` account on Calendly? We'll need to get the URL updated.

**Comment by Copons** [comment]
> @Copons Do you own the `wordpresscom` account on Calendly? We'll need to get the URL updated.

Nope, but it's available in the SS!

(Just FYI though, I only moved that URL into a constant, but it was added before my brief involvement with the Calendly block 😄)

**Comment by yansern** [comment]
Thanks @Copons! That really helps!

**Comment by yansern** [comment]
The existing calendly account is used for something else now. The remedy is to create another account, create an event type for "Jetpack Block Example", and update the URL here. (Also, add the account to SS).
![image](https://user-images.githubusercontent.com/1287077/136207142-7e654083-2b7b-4a94-99fe-bf6b42a59b83.png)

**Comment by ivan-ottinger** [comment]
The fix has been deployed to WPCOM production. When it comes to Jetpack, the fix will be available in the next release.

Related PR: https://github.com/Automattic/jetpack/pull/21323
