### ISSUE TITLE
Feature Request: Atomic Site Ownership Transfer

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#56294]
### What

Option to transfer an Atomic site ownership on the user's side.

### Why

The process to transfer an Atomic site ownership between users is very manual, and needs support intervention. I wasn't able to find any GH for this, so I'm creating this one for additional reports.

**Comment by zdenys** [comment]
4793293-zd-woothemes

**Comment by JoshuaGoode** [comment]
Moving to https://github.com/Automattic/wp-calypso/issues/61041
