### ISSUE TITLE
Gallery block refactor: Update Reader CSS to handle new gallery block markup

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#56307]
Reported by @vajrasar in p58i-bb8-p2#comment-51946

Before we can activate the refactored gallery block in wpcom, we need to ensure that the new gallery block's markup is handled by the Reader's CSS in https://github.com/Automattic/wp-calypso/blob/e3465afee05c1e9ea083d585d2c91d940c0174c9/client/assets/stylesheets/shared/_typography.scss#L315-L315

### Steps to reproduce the behavior

1. With the Gallery refactor enabled
2. Add a Gallery block with image captions
3. Publish the Gallery block
4. View in the Reader

#### What I expected to happen

For the gallery block's styling to match closely to how the gallery would appear on the front end of a site

#### What actually happened

The gallery was displayed in a single row or column, and metadata (e.g. image captions) was rendered where it shouldn't be

### Screenshots

| Metadata showing | Rendered in single column |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/133554079-837e7c3d-e1fd-4041-8df9-ff36d0a96f07.png) | ![image](https://user-images.githubusercontent.com/14988353/133554087-44a9f982-8d3c-466f-bf14-01f2926d4509.png) |

### Context

p58i-bb8-p2#comment-51946

CC: @glendaviesnz

**Comment by glendaviesnz** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/56855
