### ISSUE TITLE
`Screen Options` label partly covers the chat exit button `X` in the customer view

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#56308]
### Quick summary

Thanks to the buddying done with @michalczaplinski and @SantosGuillamot I was able to observe how the Live Chat interface looks from the customer perspective.

I discovered that the `Screen options` tab/section at the top-right of the dashboard does cover the chat title and most importantly the exit button `X`. 

![image](https://user-images.githubusercontent.com/39308239/133461188-0296d5e1-9e16-4e65-a1fb-03148bfec972.png)

### Steps to reproduce

1. Start a Live Chat session at https://wordpress.com/help/contact as if you were a customer

### What you expected to happen

The `Screen options` label/tab/section at the top-right of the dashboard should not cover/overlay the chat title and most importantly the exit button `X`. 

### What actually happened

The `Screen options` label/tab/section at the top-right of the dashboard does cover the chat title and most importantly the exit button `X`. 

### Context

Thanks to the buddying done with @michalczaplinski and @SantosGuillamot I was able to observe how the Live Chat interface looks from the customer perspective.

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Other notes

As pointed out by @mattwondra, the Happiness Gardeners pod was working on new Help Center placements, so they might be interested to know about this. p9Jlb4-2Vw-p2

cc: @poligilad-auto 

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
Thank you for reporting this! Adding this to Flow Patrol Manage to take a look.

**Comment by mreishus** [comment]
We have deployed a slight movement to the tab so it will not overlap the X.
