### ISSUE TITLE
Domains: More Info on 255 Record Limitation

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#56326]
### What

Add more details on why there's a 255 limitation for DNS records.

### Why

Right now we only show this error message:
![DNSRecordsLimit](https://user-images.githubusercontent.com/16104522/133670983-0df3769a-ff81-4dab-8546-140ba3a68a7c.jpg)

We could add more details in there, or/and a link to [our support doc on Custom DNS > TXT Record Character Limit](https://wordpress.com/support/domains/custom-dns/#txt-record-character-limit).

**Comment by delputnam** [comment]
I have created a task for Nomado to handle this issue. We'll update and close this issue once the task is complete.

**Comment by jordesign** [comment]
Closing this as resolved by https://github.com/Automattic/wp-calypso/pull/58129
