### ISSUE TITLE
Error message when opening pages with Classic block

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#56338]
### Quick summary

Error message when opening a page with a Classic block in the block editor or adding a Classic block to a new page in block editor: `Failed to initialize plugin: gutenberg-wpcom-iframe-media-modal`

Pages open without error in Classic Editor, but consistently with errors in block.

![image](https://user-images.githubusercontent.com/79414372/133690465-ed307a4c-4d74-41f3-b1b9-1832c5b3a818.png)

### Steps to reproduce

1. Start at user site.
2. Open any page in block editor.

### What you expected to happen

Page should open in block editor and display Classic block content.

### What actually happened

Page opens, but displays error.

### Context

HC: 31713310-hc
ZD: 4304343-zd-woothemes

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Use Classic Editor.

**Comment by goblinartificer** [comment]
Another incident in 30730926-hc today

**Comment by goblinartificer** [comment]
4304728-zen

**Comment by rw-ye** [comment]
Another incident here:
617893-hc
4304846-zd-woothemes

Suggested the workaround for now.

**Comment by Greatdane** [comment]
Another: 4291139-zd-woothemes

Suggested Classic Editor workaround.

**Comment by Greatdane** [comment]
All 4 reports are within the last 24 hours, and all appear to be Simple sites.

**Comment by kosiew** [comment]
#4304699-zen too.

Adding a bigger screenshot:

![image](https://user-images.githubusercontent.com/29057562/133734519-7177dffa-302a-4dc4-bb7b-4c9243490f7a.png)

**Comment by simison** [comment]
Disabling the plugin until problem is fixed could be good first step: 

https://github.com/Automattic/wp-calypso/blob/fb55dd173718474002a6204905974f2d9a669314/apps/wpcom-block-editor/src/calypso/features/tinymce.js#L9

**Comment by simison** [comment]
@scinos  onfirmed on Slack (p1631860983056900-slack-dotcom) that this is due to recent React 17 upgrade https://github.com/Automattic/wp-calypso/pull/54793

**Comment by retnonindya** [comment]
Report:
4304721-zd-woothemes

I'm informing the user to switch to Classic Editor temporarily

**Comment by scinos** [comment]
Fix has been deployed.
I'm going to reopen the issue until I get confirmation from somebody else that this is indeed fixed.

**Comment by galakhyati** [comment]
Another instance: 4305254-zd-woothemes

Informed them to switch to classic view and edit the page from there.

**Comment by noahtallen** [comment]
I'm going to close, as I can no longer the replicate the issue. @galakhyati's report is within a few minutes if when the fix was deployed, so it's possible the customer was still served a cached version of the changes.
