### ISSUE TITLE
Marketplace: Update state selector to correctly identify Marketplace products

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#56349]
Right now the `isMarketplaceProduct` selector returns a static list. Let's change this selector to use wpcom store products endpoint `https://public-api.wordpress.com/rest/v1.1/products?http_envelope=1` and filter by `product_type starts with marketplace`.

This selector is already used in a crucial flow of the atomic downgrade here https://github.com/Automattic/wp-calypso/pull/55381/files#diff-c191744b750fde532ca70b5e107d3bd1fa1e8b0cee336cd01cbf64b1f163cf96R614

We will need to use this selector in the Plugin Details page so that we query either the org or wpcom api for plugin details info.

**Comment by gcsecsey** [comment]
I’ve looked into this a bit, and the existing `isMarketplaceProduct` function is in the `calypso-products` package, which contains only constant values and functions that select from those.
https://github.com/Automattic/wp-calypso/blob/1ea9195e359dd047b88952635054c8a1eab6d3a3/packages/calypso-products/src/is-marketplace-product.ts#L3-L5

I'm not sure which approach to choose to have the selector work with dynamic data:

- The function could be updated to perform the API call, but then all invocations would need to be changed to async calls.
- We could also do something similar to `shouldFetchSitePlans`, which just returns the logic for if a refetch is needed: 
   https://github.com/Automattic/wp-calypso/blob/1ea9195e359dd047b88952635054c8a1eab6d3a3/packages/calypso-products/src/main.ts#L177-L182
   In this case the fetching of the data would need to be handled separately, as done eg. here:
   https://github.com/Automattic/wp-calypso/blob/1ea9195e359dd047b88952635054c8a1eab6d3a3/client/my-sites/checkout/checkout-thank-you/index.jsx#L148-L150
- I think the best approach would be to fetch this info into a piece of state via an action, and then access it via a selector. It could either be placed under the existing `marketplace` namespace, eg. client/state/marketplace/products or maybe we could extend the existing `client/state/products-list` with the Marketplace products:
  https://github.com/Automattic/wp-calypso/blob/1ea9195e359dd047b88952635054c8a1eab6d3a3/client/state/products-list/actions.js#L38-L52

@cpapazoglou @WBerredo what do you think? 🙂

**Comment by cpapazoglou** [comment]
@gcsecsey all marketplace products should already be present in the persisted `productsList`. Maybe we can create a new state selector by filtering with `product_type: "marketplace_plugin"` in https://github.com/Automattic/wp-calypso/tree/1ea9195e359dd047b88952635054c8a1eab6d3a3/client/state/products-list/selectors and remove the `wp-calypso/packages/calypso-products/src/is-marketplace-product.ts` file?

**Comment by gcsecsey** [comment]
Thanks @cpapazoglou for the great insight! I've created the selector, it works brilliantly.  🚀 I've also replaced the previous function with the selector, where it's been used before.
