### ISSUE TITLE
Nav unification breaks WPML plugin navigation

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#56340]
### Quick summary

The Calypso side of nav unification breaks WPML sidebar navigation.

Within the WPCOM Calypso view, WPML links are broken.  If a user manually navigates to the WP-Admin view, they work.

![Screen Shot on 2021-09-16 at 18:10:55](https://user-images.githubusercontent.com/4887830/133692339-b096224e-18ac-4c05-bce6-6d9f1dedd8c3.png)

#### Examples

`WPML` in Calypso attempts to go to  `wp-admin/sitepress-multilingual-cms/menu/languages.php?page=sitepress-multilingual-cms%2Fmenu%2Flanguages.php`

This should be `/wp-admin/admin.php?page=sitepress-multilingual-cms/menu/languages.php`

Clicking `WPML > Settings` in Calypso goes to `/wp-admin/sitepress-multilingual-cms/menu/languages.php?page=wpml-translation-management%2Fmenu%2Fsettings`

This should be `/wp-admin/admin.php?page=wpml-translation-management/menu/settings`

### Steps to reproduce

1. Access site with WPML, `sitepress-multilingual-cms`, installed.
2. Within WPCOM Calypso, attempt to navigate to any WPML links in the sidebar.
3. See error.
4. Navigate to WP-Admin directly. Attempt to access WPML links in sidebar. See that they work.

### What you expected to happen

WPML sidebar links to work.

### What actually happened

WPML sidebar do not work in Calypso. 

### Context

Customer report.

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Accessing WP-Admin directly can resolve this must there are many cases where the user will end up back in Calypso.

Deactivating SSO, and setting local user passwords, will hamper the user experience a bit but allow them to ensure they always remain in the WP-Admin after access the WP-Admin. This also turns off nav unification.

**Comment by obenland** [comment]
> Access site with WPML, sitepress-multilingual-cms, installed.

Is there a test site with that plugin installed that can be used to troubleshoot and test solution? Or is there a copy of the plugin available to test locally?

**Comment by obenland** [comment]
For future reference, this is probably something that goes wrong in `prepare_menu_item_url()` in the API endpoint where [this conditional doesn't return true](https://github.com/Automattic/jetpack/blob/d3cc0ca200dc4bc9c3c20f69ca731bf9c50b5668/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php#L366-L371)

**Comment by synora** [comment]
@JoshuaGoode  ^^ (see comment above about test site).
