### ISSUE TITLE
Action Bar no longer clickable

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#56354]
### Quick summary

It appears that the action bar on simple sites isn't responding

### Steps to reproduce

1. Visit a simple site front-end
2. Allow the action bar to load
3. Check the console and also try to interact with the action bar - nothing happens

### What you expected to happen

The action bar should be interactive

### What actually happened

Nothing happens and there is a JavaScript error instead

![Markup on 2021-09-17 at 13:48:25](https://user-images.githubusercontent.com/22053773/133777782-6479ced1-1114-438b-acac-392ad36ea884.png)
![Uploading Markup on 2021-09-17 at 13:51:56.png…]()

### Context

Customer report

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
I can confirm this on my end as well. Checking with the Calypso team for now in C02DQP0FP/p1631879815131700

**Comment by kdevnel** [comment]
Appears to be a duplicate of #56352 - leaving this open for now to help bug herders with triaging but this can be closed in favour of the other.

**Comment by Robertght** [comment]
I'm closing this as a duplicate for now in favor of https://github.com/Automattic/wp-calypso/issues/56352
