### ISSUE TITLE
Trail Marker for Speed and Performance

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#56355]
### What

Add a support doc link on the Performance page.

### Why

Under Settings > Performance, it feels that we could add the [Site Speed and Performance](https://wordpress.com/support/site-speed/) doc in there, here's an example:

![PerformanceSettingsTrailMarker](https://user-images.githubusercontent.com/16104522/133787002-14b6431a-0b68-411d-aa34-fccdd66ff9e1.jpg)

**Comment by arcangelini** [comment]
There is a PR ready for this if someone wants to check to make sure this is what we want the link to say. @jordesign @carinapilar 👍 👍

**Comment by jordesign** [comment]
Thanks Tony - I'd be happy with that wording 👍

Will give it 24 hours for Carina to weigh in as well.
