### ISSUE TITLE
Bug: ActionBar is not working anymore – no action on click

### ISSUE THREAD

**Issue by AliSoftware** [Automattic/wp-calypso#56352]
### Steps to reproduce the behavior

1. Go to any .com site you own
2. Click on the '•••' in the action bar at the bottom (next to "Customize")

#### What I expected to happen

The dropdown menu (to Follow the site and all) should open

#### What actually happened

Nothing happens – the dropdown doesn't show

#### Browser / OS version

Happening both in Chrome (`Version 93.0.4577.82 (Official Build) (x86_64)`) and Safari (`Version 14.1.2 (16611.3.10.1.6)`)

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Only tested on simple site

#### Is there any console output or error text?

```
actionbar.js?v=20210915:119 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at actionbar.js?v=20210915:119
    at actionbar.js?v=20210915:142
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Block users especially from following sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/216089/133768450-b69d4141-26a1-430d-ba80-44ded5527d70.png)

**Comment by yansern** [comment]
cc @blackjackkent as you were recently working on this file.

**Comment by AliSoftware** [comment]
Additional note that if I inspect the HTML to remove the `actnbr-hidden` class to hack the menu into being displayed, I see the menu including its "Follow" button, but then clicking on "Follow" in that menu doesn't work either.

When I do that:
1. The page seems to reload
2. But (after I re-do the hack to remove `actnbr-hidden` class and show the menu) the state of the button is still "Follow" not "Following"
3. And I get the following error in the console:

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://public-api.wordpress.com') does not match the recipient window's origin ('https://widgets.wp.com').
```

(Note that clicking on "Show site in Reader" instead, then clicking on "Follow" in the Reader itself, works as expected)

**Comment by arcangelini** [comment]
It looks like the actionbar.js breaks when it gets to these event listeners:

```
instantlyOption.addEventListener( 'click', function( e ) { onFrequencyOptionClick( e, 'instantly' ); } );
dailyOption.addEventListener( 'click', function( e ) { onFrequencyOptionClick( e, 'daily' ); } );
weeklyOption.addEventListener( 'click', function( e ) { onFrequencyOptionClick( e, 'weekly' ); } );
```

Those elements do not exist in the actionbar when the user is logged in and viewing their own page.

**Comment by arcangelini** [comment]
Fix is published waiting for review D67034-code @simison @yansern

**Comment by yansern** [comment]
Fixed & deployed!

**Comment by blackjackkent** [comment]
Great catch - thank you for making this fix!

**Comment by kwight** [comment]
Thank you @arcangelini ! <3
