### ISSUE TITLE
Modal window for site language in Settings > General > Language has undesired scrollbars

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#56372]
### Quick summary

Modal window for site language in Settings > General > Language has undesired scrollbars

https://user-images.githubusercontent.com/39308239/133892413-6fc460de-a10f-4179-b53c-e9862af6a3d5.mov

### Steps to reproduce

1. Go to Settings > General > Language
2. Click the language
3. Observe the modal window

### What you expected to happen

The modal window used to look different and could fit the list of languages without any horizontal and vertical scroll bars

### What actually happened

The modal window cannot fit the list of languages and has undesired horizontal scroll bars

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Other notes

I cannot reproduce 100% of the time, but refreshing the page and switching to a different site helps bring up the issue. 

Additionally, here is the view of Google Inspector:

https://user-images.githubusercontent.com/39308239/133892491-f54de55f-f161-4375-bb16-85fcc323114f.mov

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Refresh the page until the issue is gone.

**Comment by Robertght** [comment]
Thank you for reporting this @zdenys ! I can't see the scrollbars continuously but there's definitely a shift in the layout. I was also able to see a more organized layout once but I can't bring it back - not sure what I did.

Now:

![image](https://user-images.githubusercontent.com/6737345/133894358-c3de3378-88bc-432a-b6fd-497e6a7aca82.png)

**Comment by dpasque** [comment]
Upping priority to normal because the entire layout is all shifted.

**Comment by scinos** [comment]
Testing old Calypso versions suggests the bug was introduced by #54793

**Comment by mattwiebe** [comment]
The layout is also broken in the `/new` Gutenboarding flow:

![image](https://user-images.githubusercontent.com/195089/134210985-986c44ac-71d8-4032-972e-3dd85bfc5c7e.png)

**Comment by noahtallen** [comment]
The language picker is written with `Flex` components from `@wordpress/components`. This package was updated from v13.x to v17.x in the React 17 PR. I notice this item [in the changelog from the v14 release](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md#1400-2021-05-14):  `Flex, FlexBlock, and FlexItem components have been re-written from the ground up (#31297).`

Seems like a good place to start investigating. I'll see what I can find!
