### ISSUE TITLE
Custom Message does not show for Contact Form when set in widget

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#56375]
### Quick summary

User wants a custom message to display when someone submits to their contact form, but when it is set as a widget the message does not appear.

### Steps to reproduce

1. Add Form Block to any widget area
2. Change the settings to "Show a custom message"
3. Test the form field and you'll see the screen flash and show the form again without the custom message

### What you expected to happen

The custom message set by the user should appear when the form is submitted.

### What actually happened

The screen flashes as if resetting the page and the form appears without displaying the message.

[Here is a GIF showing the behavior](https://d.pr/i/qm56bh)

It also appears that it is redirecting to a different URL which I suspect is part of the issue. I get the following URL ending after submitting:

`/?contact-form-id=2&contact-form-sent=76&contact-form-hash=c23251339c26ef6319e2107bc507ac27f502e47b&_wpnonce=d5db31fafe#contact-form-2`

### Context

Discovered the bug while chatting with user about it.

Happychat Transcript: 31143256-hc
[SA](https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=swbuilders23)
Site: https://stevenwaltersbuilders.com/

### Operating System

macOS, iOS

### Browser

Google Chrome/Chromium, Apple Safari

### Simple, Atomic or both?

Simple, Atomic

### Other notes

I've only tested it on Apple devices but it is consistent across MacOS and iOS

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by ClassicRKR27** [comment]
Hi there - it appears that there is an instance of this now involving the custom message when the Form Block is on the page itself. I have tried this on my own sites and I'm unable to replicate it there, but the error is consistent on this page: https://midnightatthemuseum.co.uk/join-the-adventure/

URL ends with `/?contact-form-id=108&contact-form-sent=510&contact-form-hash=d0111771eb1f43fed800fb91428b29d5a04a8809&_wpnonce=ebb3e2ebb6#contact-form-108` for me upon submission with no custom message.

[SA](https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=kateandbert)

Transcript: 32166617-hc
Follow-up Ticket: 4371731-zd-woothemes

**Comment by cometgrrl** [comment]
I cannot reproduce this using a classic theme or block theme, either as a widget or directly on a page. Please re-open if we get more customer reports. However, I think this has been resolved at some point. https://midnightatthemuseum.co.uk/join-the-adventure/ doesn't exist, and the form on the main page is an elementor form, so I don't think that's the same as this bug.
