### ISSUE TITLE
Full Site Editing: API endpoint and lib

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#56373]
### Details

Updates to the lib code and surfacing FSE Beta eligibility and Site editor enabled in the REST api.

### Checklist

- [x] Add/update FSE Beta eligibility and Site Editor status in the REST API (D67076-code)
- [x] ~~Add lib function for Beta eligibility (https://github.com/Automattic/wp-calypso/pull/56374)~~
- [x] Update existing references to the old sticker (`core-site-editor-enabled`) to use the lib function (`\A8C\FSE\is_fse_eligible()`) (D67840-code)
- [x] Update existing sites to use the new blog sticker (`fse-eligible`) (D68189-code)
- [x] Add toggle to MC for blog sticker (`fse-eligible`) (D68036-code)
- [x] Add/update Calypso state to use `wpcom/v2/sites/:site/block-editor` endpoint (#56670)
- [ ] Remove the existing `is_core_site_editor_enabled` property and related code from the v1.1 `/sites` endpoint
- [ ] Refactor `\A8C\FSE\is_core_fse_active()` to `\A8C\FSE\is_fse_active()` and related functions for consistency sake

Bonus

- [x] Update API developer console for easier testing of API endpoint (https://github.com/Automattic/wp-api-console/pull/85)

### Related

#54462

**Comment by creativecoder** [comment]
Note that @zaguiini and I have started on the task "Add/update Calypso state to use wpcom/v4/sites/gutenberg", using the WIP endpoint in D67076-code

**Comment by creativecoder** [comment]
Endpoint is ready for review in D67076-code

**Comment by zaguiini** [comment]
The sticker name change from `core-site-editor-enabled` to `core-fse-eligible` is ready for review in D67840-code.

**Comment by Copons** [comment]
Adding the sticker to the BlogRC in D68036-code.

**Comment by creativecoder** [comment]
A script for updating the sticker on existing FSE sites is at D68189-code

**Comment by creativecoder** [comment]
Note that there are just a few tasks left, and none of them I'd consider blockers for the Beta, so I'm removing the blocker label from this issue.

**Comment by zaguiini** [comment]
@creativecoder are we ever going to work on this epic again? 😄

**Comment by creativecoder** [comment]
We still need to do this, but I'm not sure when we'll get to it.

**Comment by creativecoder** [comment]
Closing this, as I think https://github.com/Automattic/wp-calypso/issues/61107 captures the remaining tasks.
