### ISSUE TITLE
User Management: Improve Message When Removing Owner

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#56387]
### What

Add a less generic error when trying to remove an owner from the site.

### Why

When you try to remove the site's owner, this is what it shows up:

![GenericErrorDeletingOwner](https://user-images.githubusercontent.com/16104522/133949218-62bcbd70-2997-4a2f-ac18-719cf5081d1a.jpg)

It's not clear what the error is, and there is no way to get additional info.

**Comment by sixhours** [comment]
I'm thinking we should avoid showing an error message here, and instead show a message that notes the site owner must be reassigned (with a link/internal link to documentation) before the user can be removed.

But I'm having a tough time finding a selector that denotes the site owner. We have `wpcom_get_blog_owner` on the server side, but I don't see an equivalent on the front end. Will keep digging.
