### ISSUE TITLE
"Share This" available on password protected posts

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#56386]
### Quick summary

The options to share a post to Facebook, Twitter, and like/reblog a post, show up before you've entered the password on a protected post.

### Steps to reproduce

1: On a WordPress.com site (any plan), set up the sharing buttons (tools > Marketing > sharing Buttons). Have them displayed on posts and pages (I did not test archive pages and/or the homepage).
2: Create a post, password protect it.
3: In an incognito window, view the newly created post. Do not enter the password.

In my test, only "Facebook" and "Twitter" appeared. "Like" etc showed up after I entered the password. In the user report's case, "Like" showed up before the password was entered.

### What you expected to happen

"Share This" should probably be hidden and/or outright removed on password protected posts, as sharing is pointless if you don't also share the password. "Like" etc should be hidden until the password is entered, as it's pointless to like a post who's content you can't see.

### What actually happened

Most/all "Share This" options are available with no password. Post content is not.

### Context

Reported by a user in 4308039-zd-woothemes and tested by me. See me privately for test site details, or reproduce the issue on your own.

### Operating System

macOS

### Simple, Atomic or both?

Simple, Atomic

### Other notes

This was raised as a possible security concern, as explained in the user's report.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Setting the post or page to private, instead of password protecting it, negates this issue.

**Comment by Christopher-Stevers** [comment]
I can work on this issue.

**Comment by yansern** [comment]
> I can work on this issue.


Hi @Christopher-Stevers, it is likely that the fix will have to made on Jetpack's repository at this file:
https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php#L700

Let us know if you're successful in that endeavor!

**Comment by Christopher-Stevers** [comment]
> Hi @Christopher-Stevers, it is likely that the fix will have to made on Jetpack's repository at this file: 
https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php#L700
Thanks! I'm setting up the dev environment for jetpack, then I'll get to work on it.
