### ISSUE TITLE
Justify text on paragraph blocks does not show up in editor, but does on preview and live modes.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#56385]
### Quick summary

On any site, justifying text in a paragraph block does not show the results in the editor, but the results are visible on the live site.

### Steps to reproduce

1. Insert a paragraph block on a post.
2. Put multiple lines of text in it and try to justify the text.
3. Notice the text does not justify.
4. Click "Preview" and notice the text is justified there.

### What you expected to happen

The editor should show the justified text as well.

### What actually happened

The editor does not show the justified text, but the preview mode does.

### Context

Customer report here: 4293075-Zen

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple, Atomic

### Other notes

Preview View:
<img width="805" alt="Preview View" src="https://user-images.githubusercontent.com/49131029/133942505-4ae430c9-4055-4438-b255-901135ff2a41.png">

Editor View:
<img width="922" alt="Editor View" src="https://user-images.githubusercontent.com/49131029/133942510-1cdccdf5-f578-430b-a692-86fe5699b153.png">

 

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by synora** [comment]
Triaged. With the Blank Canvas theme active on my test site, it appears the justified text is seen in the editor:

https://user-images.githubusercontent.com/10015451/134203950-434b79e4-b472-40c6-83bd-1302aeb38441.mp4

**Comment by thekingsprojects** [comment]
Another case here: 14276663-hc (...I think: user never specified justify as the issue, but I do see that their paragraphs are justified on the live site/preview and not in the editor, and clicking "Justify" on their paragraph blocks doesn't seem to do anything in-editor.) I can replicate with both Aquene and Twenty Twenty-One.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
Unable to replicate this issue anymore.

The justify setting is provided by WPCOM Block Editor plugin and both the script & stylesheet (particularly the `.has-text-align-justify` class) are always loaded. They are not dependent on any themes.
