### ISSUE TITLE
Sites: don't show current site domain notice for non-admin users

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#5640]
#### Steps to reproduce
1. Starting at URL: logged in, any My Sites URL like stats or blog posts
2. On a site with more than one user, log in as both admin and an editor or contributor (separate sessions)
3. If `domainCreditsInfoNotice` a/b test is running `showNotice` you'll see the message for all user roles

<img width="819" alt="screen shot 2016-05-27 at 11 41 17" src="https://cloud.githubusercontent.com/assets/66797/15617911/f20d9f3c-23ff-11e6-8554-4b1eea48b0cb.png">

(Testing with WP Desktop app in this case.)

<img width="332" alt="screen shot 2016-05-27 at 2 34 01 pm" src="https://cloud.githubusercontent.com/assets/66797/15617949/33bd204c-2400-11e6-8f6c-f6db1ef4fd22.png">

#### What I expected
Only to see the notice when logged in as the owner of the site.

#### What happened instead
Everyone sees it. When you click the notice "Claim" link without being able to administer the site, you are asked to select a site (because you can't apply a credit to current site). 

I think we should hide the notices for non-admins — or make it clear to claim the credit you should contact the site owner.

**Comment by lancewillett** [comment]
Thanks for the quick fix. :)

I'll re-test again once this makes it into WP Desktop app (which is where I first saw the issue).

**Comment by lancewillett** [comment]
Confirmed in a Safari web test — with a user that doesn't have access to manage options.

<img width="850" alt="screen shot 2016-05-27 at 13 14 46" src="https://cloud.githubusercontent.com/assets/66797/15620092/08dd7afe-240d-11e6-8a5d-ebac7e221f39.png">

**Comment by mtias** [comment]
Thanks for catching this one.
