### ISSUE TITLE
Site Editor: detect changes to Site Editor state and re-fetch

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#56412]
It is currently possible for the Site Editor to be enabled on a site but its Nav Menu to be stale and outdated. This is true for any Simple or Atomic site that prefers to use `wp-admin` screens. We will be addressing this on theme switch in #56172 but that is only effective when the action is taken in the Calypso environment.

**Comment by Copons** [comment]
Could you clarify on this?

The stale navigation bug should only happen in a SPA context like Calypso (fixed by #56172).
In wp-admin, activating a theme involves a full-fledged page reload, which would inevitably also refresh the navigation.

**Comment by mattwiebe** [comment]
> Could you clarify on this?

Sorry, missed this comment and now I don't remember the situation as clearly.

Oh, actually, never mind. I do remember now: I was dealing with a non-Atomic Jetpack site, which doesn't use Nav Unification and therefore never shows the Site Editor. 🤦 

Closing now, will reopen if I come across this again.
