### ISSUE TITLE
Marketing> Traffic: Site verification services link change

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#56426]
We (Docs) have changed the link to the doc formerly called Webmaster Tools from https://wordpress.com/support/webmaster-tools/ to https://wordpress.com/support/site-verification-services/

This link appears in Calypso from My Site > Tools > Marketing > Traffic, under Site verification services.

The link for Full instructions should be changed:

<img width="1054" alt="Screen Shot 2021-09-21 at 9 30 35 AM" src="https://user-images.githubusercontent.com/31680407/134179801-df9ac5e1-ce71-4de6-88d8-b40647c65bb4.png">

A redirect is already set on the URL but changing the link would be ideal. The link appears here: https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/inline-help/contextual-help.js

**Comment by Aurorum** [comment]
PR for this issue in #56560. :)
