### ISSUE TITLE
Canape theme feature images

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#56428]
### Quick summary

Problem loading featured images

### Steps to reproduce

URL: theshamrockirishbar.com
Plan: Personal

PROBLEM:
User can't change the featured image on the "menu" page on this site. When you try to change the image, the spinner just keeps spinning.

WHAT I FOUND:
* I could replicate this with multiple images on their site. Nothing loaded in the featured area
* When you try the spinner just spins.
* Theme is canape. Personal plan.
* set up a test site with Capape and personal plan. It also wouldn't load featured images on my test site.
* Changed the theme to Bantry and it worked straight away.
* Changed back to Canape - Some images seemed to load but then not load. I tried resizing them and something they loaded sometimes the spinner just span.
* This seems to occur with their images and my test images.

### What you expected to happen

Featured image to load 

### What actually happened

It spins

### Context

4314021-zen

### Operating System

macOS

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Theme-specific issue?

Canape

### Reproducibility

Intermittent

### Severity

Some (< 50%)

**Comment by inaikem** [comment]
Thanks for the report! I was able to repeatedly switch and save the featured image on the user's site with no lag/loading icon showing on my side. Closing for the moment but please review and reopen if needed!


NB. I also updated interaction reference to use `-zen` as opposed to `-zd` so Github Highlighter works.

**Comment by dcoleonline** [comment]
The customer wrote in to say thanks and that it works for them now. :)
