### ISSUE TITLE
Atomic Downgrade: Display JITM when Atomic revert is in progress

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#56421]
It'd be helpful if customers can see in Calypso whether the asynchronous process that removes a plan from an Atomic site is still running or not, so let's display a message indicating that info. Something like the text below can work:

```
We are removing/cancelling <PLAN_NAME> from <SITE>.

Please give it some time for changes to take effect. An email will be sent once the process is complete.
```

#### Technical references
- Sites with an Atomic revert in progress are marked with a `subscription_deactivation_locked` blog sticker (see D66763-code).
- We can add a new JITM to the `calypso:home:admin_notices` area to display this message (see PCYsg-cLC-p2 and `wp-content/lib/jetpack-jitm/jitm-engine.php`).

**Comment by dsas** [comment]
D67371-code
