### ISSUE TITLE
cryptalknews.com user is not seeing the file URL in the media pop up 

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#56437]
### Quick summary

The user and I are seeing completely different URLs when trying to copy the URL of a video.
We are both in the Calypso media library. 
User:
XXXXXX.com/bitcoinup-app-part-1-en-3-mp4/
![26wZ9s](https://user-images.githubusercontent.com/5507879/134202672-b6ea5f84-f194-4674-974d-6cd5d76b1ed6.png)
ME:
videos.files.wordpress.com/FacDbysZ/XXXXXX-part-1-en-3_mp4_hd.mp4
<img width="900" alt="Markup 2021-09-21 at 14 40 08" src="https://user-images.githubusercontent.com/5507879/134203956-24ce2aad-c526-4e1a-b431-46bb97d74a5b.png">

### Steps to reproduce

The user is the only one seeing this. 
When I SU as the user I am seeing the Videopress URL. 
When I opened the media library via wp-admin the videos were not showing at all. 
XXXXXX.com/wp-admin/upload.php

I tested to see if I could replicate on one of my own Atomic sites but that is not the case. 

### What you expected to happen

I was expecting the user and me to see the same URL in the media file field. 

### What actually happened

The user and I are seeing completely different URLs when trying to copy the URL of a video.
We are both in the Calypso media library. 
User:
XXXXXX/bitcoinup-app-part-1-en-3-mp4/
![26wZ9s](https://user-images.githubusercontent.com/5507879/134202672-b6ea5f84-f194-4674-974d-6cd5d76b1ed6.png)
ME:
videos.files.wordpress.com/FacDbysZ/XXXXXX-part-1-en-3_mp4_hd.mp4
<img width="900" alt="Markup 2021-09-21 at 14 40 08" src="https://user-images.githubusercontent.com/5507879/134203956-24ce2aad-c526-4e1a-b431-46bb97d74a5b.png">

### Context

4314564-zen

### Simple, Atomic or both?

Atomic

### Severity

One

**Comment by Robertght** [comment]
I'm unable to replicate this one but please re-open it if more cases arise.
