### ISSUE TITLE
Subscriptions: New email templates for Jetpack sites need a Jetpack-specific footer branding.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56435]
Our new email templates currently always display a "Powered by WordPress.com" footer text. This needs to be changed to "Powered by Jetpack" for Jetpack sites. Let's keep the same text color – any color discussions that arise can happen as a separate issue.

This is a blocker for launching these templates to production.

<img width="777" alt="Screen Shot 2021-09-20 at 2 27 59 PM" src="https://user-images.githubusercontent.com/349751/134209775-fff86798-a82f-4479-bc7e-092d1a950118.png">
 
Related: https://github.com/Automattic/wp-calypso/issues/56410
See: pdgv5Y-f0-p2

**Comment by andres-blanco** [comment]
I think we should also update the logo and the anchor on the JP case to:

Logo: JP in a b&w version
Link: should go to https://jetpack.com/

@saygunnyc let me know if you think this is correct.

actual code on: `wp-content/mu-plugins/html-emails/themes/wpcom-notifications/html/template-footer.php`

**Comment by saygunnyc** [comment]
@andres-blanco 💯 
I think we can swap the SVG, keeping the color the same. I am sharing a mockup below. Let me know if you happen to need an SVG from me.

@eeeeevon13 just wanted to ping you and ask if you have a preference between 01 and 02?
I want to keep the same color (**02** – Gray 80 - 2C3338 ) for consistency with WordPress.com emails, but unsure sure if that works with Jetpack branding.

**01**

<img width="1352" alt="JP01" src="https://user-images.githubusercontent.com/78876323/134333769-35677b70-f766-4b52-8726-d80f4765198f.png">

**02**

<img width="1352" alt="JP2" src="https://user-images.githubusercontent.com/78876323/134333781-294e0616-7825-471f-83d7-64e0685226da.png">

**Comment by andres-blanco** [comment]
D67457-code
