### ISSUE TITLE
Embed Block no longer embedding links from Meetup.com

### ISSUE THREAD

**Issue by syds87** [Automattic/wp-calypso#56433]
### Quick summary

The Embed block should automatically embed the events by Meetup.com, as stated in the [official tutorial](https://wordpress.com/support/wordpress-editor/blocks/embed-block/).

However, when I try and add a Meetup.com link, I get an error saying: `Sorry, this content could not be embedded.`

### Steps to reproduce

1. Add an embed block to a page
2. Paste a Meetup.com link, like https://www.meetup.com/wiccaNL/events/280312936/
3. Click Embed

### What you expected to happen

The event should be embedded here.

### What actually happened

I get an error stating that the URL can't be embedded:

<img width="841" alt="Screen Shot on 2021-09-21 at 17-32-23" src="https://user-images.githubusercontent.com/70008187/134201262-1fd3ce26-0a98-4353-8e87-b65299dc1858.png">

### Context

Reported by #4314536-zen - Reproduced on my test site.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Reproducibility

Consistent

**Comment by Robertght** [comment]
Thank you @syds87 ! This seems to be documented here as well: https://github.com/Automattic/wp-calypso/issues/28126 

As I don't see any updates, I'm flagging it for Flow Patrol Create.

**Comment by yansern** [comment]
Meetup removed Oembed support. There's no way to embed Meetup links now. https://api.meetup.com/oembed
This needs to be removed from the support docs. (cc @donalirl)

**Comment by cometgrrl** [comment]
Meetup is no longer mentioned [here](https://wordpress.com/support/wordpress-editor/blocks/embed-block/), so I'm closing this.
