### ISSUE TITLE
Subscriptions: Update the "new comment like" email template.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56445]
Part of https://github.com/Automattic/wp-calypso/issues/55540. See pdgv5Y-a6-p2.

| Current | Update |
| --- | --- |
| <img width="707" alt="Screen Shot 2021-09-21 at 1 23 52 PM" src="https://user-images.githubusercontent.com/349751/134242461-aba8cf30-4769-47bd-8eaf-ac4b2a8f27e1.png"> | <img width="700" alt="Screen Shot 2021-09-21 at 1 25 48 PM" src="https://user-images.githubusercontent.com/349751/134242780-779566b7-307d-47d9-a94b-1aba221fa558.png"> |

**Comment by andres-blanco** [comment]
D67263-code

**Comment by andres-blanco** [comment]
Merged in D67263-code
