### ISSUE TITLE
Subscriptions: Update the "new email follower" email template.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56446]
Part of https://github.com/Automattic/wp-calypso/issues/55540. See pdgv5Y-a6-p2.

| Current | Update |
| --- | --- |
| <img width="800" alt="Screen Shot 2021-09-21 at 1 32 10 PM" src="https://user-images.githubusercontent.com/349751/134243579-7d31b375-843f-4ac2-8d89-29f5e089330a.png"> | <img width="688" alt="Screen Shot 2021-09-21 at 1 32 50 PM" src="https://user-images.githubusercontent.com/349751/134243602-d0f5bad2-1bc7-45a4-86d3-d9a22f91a866.png"> |

**Comment by blackjackkent** [comment]
I had started working on this but it looks like it's going to be addressed for free by @andres-blanco 's changes in D67392-code.
