### ISSUE TITLE
Subscriptions: Update the "new WP.com user follower" email template.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56447]
Part of https://github.com/Automattic/wp-calypso/issues/55540. See pdgv5Y-a6-p2.

| Current | Update |
| --- | --- |
| <img width="720" alt="Screen Shot 2021-09-21 at 1 38 54 PM" src="https://user-images.githubusercontent.com/349751/134244466-8a563eba-48bc-45ac-99c4-b28ccee6a54b.png"> |<img width="716" alt="Screen Shot 2021-09-21 at 1 38 10 PM" src="https://user-images.githubusercontent.com/349751/134244481-be51f5aa-57d1-4e1e-88e2-b083ab474c20.png"> |

**Comment by andres-blanco** [comment]
D67392-code
