### ISSUE TITLE
Subscriptions: Update the "new comment" email template.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56443]
Part of https://github.com/Automattic/wp-calypso/issues/55540. See pdgv5Y-a6-p2.

| Current | Update |
| --- | --- |
| <img width="968" alt="Screen Shot 2021-09-21 at 12 59 56 PM" src="https://user-images.githubusercontent.com/349751/134239798-130b61de-864e-408f-a136-e43b824c439a.png"> | <img width="968" alt="Screen Shot 2021-09-21 at 1 01 12 PM" src="https://user-images.githubusercontent.com/349751/134239816-211de8b5-af65-4328-b736-698619036e30.png"> |

**Comment by andres-blanco** [comment]
This was merged in D66917-code to get ahead of translation. We still need to verify that the `Delete` and `Mark as spam` works correctly

**Comment by andres-blanco** [comment]
This task is complete with D67598-code
