### ISSUE TITLE
Snackbar when saving widgets on widgets.php is hidden behind menu

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#56461]
### Steps to reproduce the behavior

1. Go to sitename.wordpress.com/wp-admin/widgets.php
2. Add / change a widget
3. Press save
4. See half of a snackbar saying 'Widgets saved'

#### Browser / OS version

Firefox 92 / OSX

#### Does this happen on simple or atomic sites or both?

Reproducible on simple site
Not reproducible on jetpack connected dotorg site running wp 5.8.1

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low - we prefer to use the customizer and it's kind of cosmetic 

#### Screehttps://cdn-std.droplr.net/files/acc_1183136/Vi86xanshot / Video: If applicable, add screenshots to help explain your problem.
| Bad | Good |
|----|-------|
|<img width="1136" alt="Markup 2021-09-22 at 12 48 58" src="https://user-images.githubusercontent.com/93301/134339010-af2a0a12-c3e1-472a-a91e-31af2db0f34c.png"> | <img width="505" alt="Screenshot on 2021-09-22 at 12-47-07" src="https://user-images.githubusercontent.com/93301/134339020-f840c837-b4a0-4cbd-a208-1b50ffbf7c80.png"> |

**Comment by Robertght** [comment]
I encountered this while checking other things.

Happens with Classic/widget-enabled themes.

**Comment by rcrdortiz** [comment]
Changes have been merged and will be available on the next release.
