### ISSUE TITLE
Search bar confusion in the Reader

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#5646]
The magnifying glass icon typically means "search" to me, so it's weird that it appears in the 'add a URL' field here. I at first tried to search in it: 

<img width="768" alt="screen shot 2016-05-27 at 3 01 22 pm" src="https://cloud.githubusercontent.com/assets/8698879/15622132/5051e922-2423-11e6-90e2-405423183722.png">

Before realizing there was a separate search bar just below:

<img width="824" alt="screen shot 2016-05-27 at 3 01 43 pm" src="https://cloud.githubusercontent.com/assets/8698879/15622143/86188d68-2423-11e6-9437-40c7ff477376.png">

<img width="919" alt="screen shot 2016-05-27 at 3 01 51 pm" src="https://cloud.githubusercontent.com/assets/8698879/15622160/aebbdbc6-2423-11e6-9379-4ba39bd1047c.png">

It'd be cool if the URL field served a combined 'add content'/'search existing content' function, but otherwise I definitely think the magnifying glass icon should be removed.

**Comment by SiobhyB** [comment]
+1! I confused that bar for the search bar when attempting to manage my P2 notifications this morning, not for the first time either.

**Comment by SiobhyB** [comment]
This has been fixed now. :) It is not possible to both search and enter a URL in the "Follow Something New" field. There's also a clearer separation between it and the "Search Followed Sites" field:

<img width="835" alt="screen shot 2018-01-16 at 20 47 01" src="https://user-images.githubusercontent.com/2998162/35011555-7669fff6-fafe-11e7-8eb3-453dfb6e52be.png">
