### ISSUE TITLE
Widgets display twice

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#56486]
### Quick summary
Simple Site

Nikau theme.

Customer set up these widgets in Customizer:

1. Follow Blog
2. Search
3. Categories
4. Recent Pots
5. Archives
6. Instagram
7. Twitter Timeline
8. Meta

On the frontend, these widgets appeared twice

1. Search
2. Categories
3. Archives
4. Instagram
5. Twitter Timeline

![Markup on 2021-09-23 at 09:41:41](https://user-images.githubusercontent.com/29057562/134443517-7c8b15ca-6843-4a9d-9569-45c8f3eb3960.png)

### Steps to reproduce

Could not reproduce on my test site.

On Customer's site, I could reproduce this (without saving) even when I removed all but the Categories widget.

### What you expected to happen

Widgets do not duplicate

### What actually happened

Some widgets duplicated

### Context

4318925-zd-woothemes

### Theme-specific issue?

Customer's site is Nikau but I could not reproduce on my Nikau site.

**Comment by Robertght** [comment]
I was able to see this issue on their website, but I think it's a glitch as there are no visibility rules on the widgets, and that I can see the duplicates in the wp-admin/widgets.php 

I'm asking the user to try and remove them for now and see if that helps.

I'm marking this as solved but please open it again if more cases arise.
