### ISSUE TITLE
Make list building easier

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#5648]
I wanted to create some lists in the Reader, but when I went to the place to add some, all I got was a list of blog titles: 

<img width="1108" alt="screen shot 2016-05-27 at 2 30 26 pm" src="https://cloud.githubusercontent.com/assets/8698879/15622229/123e9706-2424-11e6-9838-8a3da78788d9.png">

This actually wasn't helpful, because I follow a whole lot of blogs and I have no idea what any of those are. It'd be good to have the titles, URLs, and possibly taglines displayed there. Or at least be able to click the entries in that list to expand for more info. Would also be nice if the "Enter a Blog URL" field was also a search bar that searched blog titles and URLs. 

Then I went over to "Manage" (https://wordpress.com/following/edit) to see if I could add the sites directly from there to the lists, but you can't: 

<img width="811" alt="screen shot 2016-05-27 at 2 38 15 pm" src="https://cloud.githubusercontent.com/assets/8698879/15622285/7976833e-2424-11e6-9b5b-4bbd9ce2c3c6.png">

It'd be great if there was an "add to lists" option there.

**Comment by bluefuton** [comment]
Hi @eurello! Just to keep you posted - list management hasn't been ported to Calypso and we're no longer actively developing the feature.
