### ISSUE TITLE
Calypso changes to see whether to inhibit plan changes

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#56498]
### Details

In #55381 we check to see if subscription_deactivation_locked is a blog sticker to decide whether to lock the UI from changing a subscription (e.g. cancelling it). This endpoint is only available to a12s.

In #56496 a new bespoke endpoint will be added to use instead.

**Comment by mmtr** [comment]
As discussed in p3hLNG-18B-p2, we're finally exposing a new property to all the purchases objects returned on API endpoints, so we don't need to consume a new endpoint.

Instead, Calypso will check the new property of a given purchase (suggested name: `is_locked`) and hide all the managements actions when true.
