### ISSUE TITLE
Block patterns: Link in Bio preview keeps expanding, breaks view, scrolls endlessly

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#56495]
### Quick summary

When browsing block patterns under the "link in bio" section, the preview for one of the patterns expands and breaks the view, causing you to need to scroll endlessly,

### Steps to reproduce

1. Open block patterns tab to insert a pattern
2. Choose "Link in Bio" category
3. Scroll down list

### What you expected to happen

Each pattern should show in a thumbnail

### What actually happened

Some pattern expand endlessly and breaks the view and ability to scroll.

<img width="458" alt="Markup 2021-09-23 at 12 17 17" src="https://user-images.githubusercontent.com/51966986/134498023-339989d1-b991-48ef-9cc6-7b998e691401.png">

See the following video demo: 

https://user-images.githubusercontent.com/51966986/134498045-947cc1fb-b602-4ec7-955f-395e5824ab49.mp4

### Context

Exploring block patterns

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

**Comment by Robertght** [comment]
Thank you for reporting this @philnick206 ! I'm closing it in favor of this one:

https://github.com/Automattic/wp-calypso/issues/56077

Core Gutenberg issue here: https://github.com/WordPress/gutenberg/issues/34729
