### ISSUE TITLE
API changes for whether to inhibit plan changes

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#56496]
In #55381 we check to see if `subscription_deactivation_locked` is a blog sticker to decide whether to lock the UI from changing a subscription (e.g. cancelling it). It gets the blog sticker from the rest endpoint implemented by `WPCOM_JSON_API_Get_Blog_Stickers`. This endpoint is only available to a12s. 

The solution is to add a new public endpoint that checks whether the blog sticker is present.

**Comment by mmtr** [comment]
> the rest endpoint implemented by WPCOM_JSON_API_Get_Blog_Stickers. This endpoint is only available to a12s.

I wonder why is that and whether we could remove that limitation to expose the endpoint publicly. I'll publish a P2 post to gather some feedback.

**Comment by mmtr** [comment]
Internal discussion: p3hLNG-18B-p2

**Comment by mmtr** [comment]
As discussed in p3hLNG-18B-p2, we're finally exposing a new property to all the purchases objects returned on API endpoints, so we don't need to create a new endpoint.

I think we could add a new `is_locked` property in the `set_properties_for_purchases_rest_api` function (`wp-content/admin-plugins/wpcom-billing/store-subscription.php`) when the blog sticker is present and the purchase requires an Atomic downgrade.

**Comment by mmtr** [comment]
Diff ready for review: D67879-code.

**Comment by BogdanUngureanu** [comment]
Deployed in rWP232920-wpcom

**Comment by BogdanUngureanu** [comment]
Re-opened: When the site is back on simple infrastructure, the API property displays `false` instead of `true`.

**Comment by BogdanUngureanu** [comment]
D68155-code is RfR.

**Comment by BogdanUngureanu** [comment]
Deployed in WPCOM with r233088-WPCOM
