### ISSUE TITLE
Block patterns: Block patterns in .org directory are missing from .com

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#56499]
### Quick summary

I tried searching for some block patterns that are available in the WordPress.org directory (https://wordpress.org/patterns/) in the block inserter on a .com site and am not able to find them.

### Steps to reproduce

1. Search for a block pattern like the following: https://wordpress.org/patterns/pattern/image-with-angled-overlay-and-text/ - using the text "Image with angled overlay and text"

### What you expected to happen

The block patterns should be shown in the search results.

### What actually happened

Nothing is returned.

<img width="299" alt="Markup 2021-09-23 at 12 41 47" src="https://user-images.githubusercontent.com/51966986/134500893-2344516d-1d78-4a75-b550-a5db6f43c653.png">

### Context

Exploring patterns.

### Other notes

Might be by design but I thought these used to show.

### Reproducibility

Consistent

**Comment by cometgrrl** [comment]
This is the same behavior as a self-hosted site. Not all patterns are exposed in the inserter. You have to copy some of them from the pattern library to use them. See p1660867184058399-slack-C02KBT54T9T.
