### ISSUE TITLE
Block patterns: Tiled mosaic gallery pattern shaking in preview window

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#56505]
### Quick summary

Observed the Tiled Mosaic Gallery block pattern "shaking" when viewed in the preview window.

### Steps to reproduce

1. Browse Featured block patterns and scroll down until you get to this pattern

### What you expected to happen

The pattern preview would display properly

### What actually happened

The patter preview shakes, like so:

![Screen Capture on 2021-09-23 at 13-32-25](https://user-images.githubusercontent.com/51966986/134507862-2297f8fc-8b63-4707-a53b-f7f56ec3f8fc.gif)

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

**Comment by Robertght** [comment]
Thank you for reporting this @philnick206 !

Unfortunately, I can't replicate this on Chrome or Firefox:

https://d.pr/v/NQc9P3

Could you share a bit more details about the environment, please?

**Comment by worldomonation** [comment]
I am not the original reporter, however I was able to reproduce something similar on Firefox 94.0a1 (2021-09-23) (64-bit) (nightly).

See attached video on both P2 and my own personal site.

P2
https://user-images.githubusercontent.com/6549265/134733567-964b518f-4de3-4701-8887-29a821da589f.mov

Personal site
https://user-images.githubusercontent.com/6549265/134733594-77866a30-dafa-49f0-a407-caa37460db84.mov

Steps to reproduce in my case:

1. start a new post.
2. open the block inserter.
3. scroll down to reveal `Tiled Gallery` or `Slideshow` blocks.
4. hover the cursor **slowly** over the `Tiled Gallery` or `Slideshow` block item in the inserter.

**Comment by philnick206** [comment]
I was using Firefox 92 on macOS (Catalina). I just tried again now with both Firefox and Chrome and am not seeing the same behavior any longer. 🤷🏼‍♂️ I'll go ahead and close this for now.

**Comment by worldomonation** [comment]
Repoening this issue as this issue is still present. It should not be closed.

The shaking of `Tiled Mosaic Gallery` affects every pattern below itself.

Firefox Nightly 97.0a1.

https://user-images.githubusercontent.com/6549265/145919468-34357431-5dbc-46a6-9897-2fc078546f4b.mov

**Comment by Robertght** [comment]
I'm not able to replicate this unfortunately using Firefox 12.1 and the following:

Gutenberg: v12.0.2
Editing Toolkit: 3.22012
WP AMP: 2.0.5
CoBlocks: 2.10.1

I'm wondering if this is dependent on the display. 

cc @Automattic/flow-patrol-create  @Automattic/flow-patrol-spacelab for a second look.

**Comment by syhussaini** [comment]
The issue has been fixed.

_See the image below for reference_
![image](https://d.pr/i/1I0Z3w+)
_Please [click here](https://d.pr/i/1I0Z3w) if you are unable to see the image above_

**Comment by worldomonation** [comment]
I tested this on Firefox Nightly 102.0a1 and still observe the Tiled Mosaic Gallery entry shaking in the preview.

https://user-images.githubusercontent.com/6549265/170771431-888405db-3ebf-4e6c-8dc9-aa9db167ca63.mov
