### ISSUE TITLE
Reader: Prevent sites with redirects from being followed 

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#5651]
If a site has a redirect on it to an external site we still allow that site to be followed and show its content in the reader. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/following/edit
2. Enter a site with a redirect (for example bandonrandontest1234545667756546546.wordpress.com)
3. Notice how the blog can be followed but the blog location shows where the redirect is pointed. 

#### What I expected
To either be told the site could not be followed (or that a site wasn't found) or be asked if I wanted to follow the redirected location.

#### What happened instead
I was able to follow the site.

Note that if the site at the redirect location does have posts, those posts will show in the reader instead of the intended followed site. 

#### Browser / OS version
Chromium 50 / Linux Mint 17.3

#### Screenshot / Video
https://cloudup.com/cclTJy83pJH

**Comment by lancewillett** [comment]
Good find — do you have a sense how often this happens? Trying to figure out if it's an edge case or needs higher priority.

**Comment by BandonRandon** [comment]
> do you have a sense how often this happens
I don't. Anecdotally, I've never had a user mention it. The only cases I've seen of it have been sites owned by Automattic or myself. 

We could possibly get a data request of how any sites have redirects/mapping with external name servers then check how many times those sites have been followed.

**Comment by lancewillett** [comment]
Going to close this one for now. We can re-open if it gets more interest or user reports in the future.
