### ISSUE TITLE
Legacy FSE: Duplicate template parts on initial load

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#56524]
### Steps to reproduce the behavior

1. Create a legacy FSE enabled site
2. Pin the site to the latest Gutenberg version
3. Note that header and footer legacy FSE template parts are duplicated at the bottom of the view. To clarify, these duplicates were _not_ inserted by the user.

#### Is this specific to the applied theme? Which one?
Mayland

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![2021-09-23 14 55 07](https://user-images.githubusercontent.com/5414230/134594153-4551d2c8-69d0-42d9-874b-ef68798c0c02.gif)

**Comment by Addison-Stavlo** [comment]
can close since we deprecated LFSE
