### ISSUE TITLE
FSE / Global Styles - empty block settings menus.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#56538]
The Global Styles panel (as seen in the Site Editor) has recently (v11.6.1) been updated in Gutenberg to use a new UI.
In doing so, all registered blocks are shown in the blocks list regardless of whether or not they support global styles options.  This creates a lot of confusion, especially when we have other blocks of the same titles registered.  For example if we open the global styles panel -> blocks -> and select the first "Button" (possibly a coblocks or jetpack block?) we see this:

![image](https://user-images.githubusercontent.com/28742426/134667151-093cfff4-5dec-48c0-8801-65fc15d6bd7a.png)

Moving way further down the list we see a second "Button" option that corresponds to the core/button.  This shows the options as expected.

![Screen Shot 2021-09-24 at 8 56 43 AM](https://user-images.githubusercontent.com/28742426/134677791-ca245f51-5a5a-4619-94a4-f4f5c8502cf3.png)
)

per discussion with @youknowriad it sounds like the plan in Gutenberg is to hide all blocks in this list that do not have global styles options.

**Comment by Copons** [comment]
This has been fixed Core-side in https://github.com/WordPress/gutenberg/pull/35178, and will land on Dotcom along with Gutenberg 11.7 next week (tentatively)
