### ISSUE TITLE
Navigation: Stats Sparkline does not appear on WP Admin pages for Atomic sites

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#56542]
### Steps to reproduce the behavior

1. Go to a page that's served via WP Admin. For example, the Feedback/Form Responses at `wp-admin/edit.php?post_type=feedback`
2. Check the missing sparkline right next to stats

#### What I expected to happen

To see the sparkline on all screens

#### What actually happened

Sparkline disappears from wp-admin/ pages.

### Context

#dogfooding

#### Does this happen on simple or atomic sites or both?

Atomic.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low.

#### Screenshot

On WP.com pages | On WP Admin
------------ | -------------
<img src="https://user-images.githubusercontent.com/1136160/134684973-2542dea9-3e1a-45d8-abaf-33cfbc757d74.png" width="400"/> | <img src="https://user-images.githubusercontent.com/1136160/134684983-42813e45-eada-4cd3-a36c-0d78bf3a18e3.png" width="400"/>

**Comment by inaikem** [comment]
Pinged @eduardozulian re Bugomattic and added the issue to the HE Triage board.

**Comment by formosattic** [comment]
Thanks for the report @eduardozulian!

I was able to confirm that it only happens on atomic sites.

![troubleshooting](https://user-images.githubusercontent.com/15944096/135064675-f8d08305-213b-4d2f-9259-c6cc763524b9.gif)
