### ISSUE TITLE
Domains Only flow: redirects to incorrect page post-checkout

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#56548]
### Quick summary

When using the `/start/domain` flow, post-checkout the page redirects to an invalid page.

### Steps to reproduce

prerequisite: log out of WordPresss.com account.
prerequisite for a11n: enable store sandbox.

1. start at /start/domain.
2. search for a domain to purchase and select it.
3. opt to purchase just to domain.
4. create a WordPress.com account.
5. enter domain registrar and billing details.
6. checkout.

### What you expected to happen

Page is redirected to `/checkout/thank-you/<domain name>`.

### What actually happened

Page briefly redirects to `/checkout/thank-you/<domain name>`.
It then redirects to `/checkout/thank-you/no-site/<purchase_id>/<purchase_id>`. 

Real example I generated: `https://wordpress.com/checkout/thank-you/no-site/19997771/19997771`

![Screen Shot 2021-09-24 at 9 12 59 AM](https://user-images.githubusercontent.com/6549265/134708990-5e4101d1-de54-48b0-b381-26d92511ca6c.png)

![Screen Shot 2021-09-24 at 9 13 15 AM](https://user-images.githubusercontent.com/6549265/134708994-d41ed2f3-e098-4efc-8575-1ff376c6b4eb.png)

### Context

Developing automation testing for Playwright.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Other notes

No errors in developer console.

Logs from Playwright showing the redirect path:

```
  pw:api   navigated to "https://wordpress.com/checkout/no-site?signup=1&isDomainOnly=1#step2" +3m
  pw:api   navigated to "https://wordpress.com/checkout/thank-you/no-site/19997771" +44s
  pw:api   navigated to "https://wordpress.com/checkout/thank-you/e2eflowtestingdomainonly1632499598092.live" +224ms
  pw:api   navigated to "https://wordpress.com/checkout/thank-you/no-site/19997771/19997771" +597ms
  pw:api   "domcontentloaded" event fired +323ms
  pw:api   navigated to "https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0#https://wordpress.com" +6ms
  pw:api   "domcontentloaded" event fired +88ms
  pw:api   "load" event fired +20ms
  pw:api   navigated to "https://wordpress.com/checkout/thank-you/no-site/19997771/19997771" +377ms
  pw:api   "load" event fired +514ms
  pw:api   "networkidle" event fired +544ms
```

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The erroneous page still has the NavBar, so it is trivial to click on `My Sites` to navigate away.

**Comment by worldomonation** [comment]
I attempted to reproduce this using an existing account and purchasing domains only, but was unable to.

It would appear (currently at least) that this issue is tied to the`/start/domain` flow.

**Comment by delputnam** [comment]
@rafaelgalani I think the PR you're currently working on will address this, but pinging you here just to make sure.
