### ISSUE TITLE
All blocks displaying "This block has encountered an error and cannot be previewed"

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#56575]
### Quick summary

When editing older posts (before August 2021), all blocks are showing this error: "This block has encountered an error and cannot be previewed"

### Steps to reproduce

1. Go to Posts 
2. Look for posts that are published before August 2021 > open the post editor (e.g. https://wordpress.com/post/blog.shopsolensis.com/460)
3. Click on any blocks to see the error

### What you expected to happen

Blocks should display content.

### What actually happened

All blocks are displaying the error message "This block has encountered an error and cannot be previewed."

### Context

User report. 
30729149-hc | 4322595-zd-woothemes

### Operating System

iOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Other notes

<img width="2498" alt="Screenshot on 2021-09-25 at 12-17-04 (1)" src="https://user-images.githubusercontent.com/33721365/134911964-c55cc6f9-fdb2-4c88-a8a3-8bcf6d3f0db6.png">

### Reproducibility

Consistent

### Severity

One

**Comment by Robertght** [comment]
We're currently troubleshooting this here as I was unable to replicate the issue: EDhh-1kD-p2

**Comment by Robertght** [comment]
I'm going to close this as the situation resolved itself and we haven't heard back from the user.
