### ISSUE TITLE
In WordPress.com view there is no option to update a theme.

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#56591]
### Quick summary

If there are some theme updates available, the user can not update the theme from `WordPress.com > My Sites > Appearance > Themes`. But we can do that from the `Classic view`.

WordPress.com view: ![WordPress.com view](https://d.pr/i/6Bz7CN+) **Image Link:** https://d.pr/i/6Bz7CN

Classic view: ![Classic view](https://d.pr/i/r9jWF7+) **Image Link:** https://d.pr/i/r9jWF7

As you can see, the option to update the Storefront and Botiga theme is available in the classic view.

### Steps to reproduce

You need to have some outdated themes on your site

### What you expected to happen

Either the user should be able to update their themes from WordPress.com view.

Or we can hide the notification counts for `Appearance > Themes` in the `WordPress.com view`.

### What actually happened

Although we have been able to see the notification count for Appearance > Themes in the WordPress.com view, we don't have an option to update the themes.

### Context

The customer reported this issue here: 31826294-hc.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

The user can switch to classic view and update their themes to get rid of the notifications alert.

**Comment by sixhours** [comment]
I'm not going to be able to work on this for long, so I'll document what I've found so far in case it's helpful for the next dev:

* We don't yet have an action in Calypso for updating a theme: https://github.com/Automattic/wp-calypso/blob/trunk/client/state/themes/actions/index.js
* But there is an endpoint here that suggests we can check for updates:
<img width="958" alt="Screen Shot 2021-10-29 at 9 06 33 AM" src="https://user-images.githubusercontent.com/2124984/139446262-4712acef-ac07-408d-be4d-2eab38ba83d7.png">

* And core has an upgrade endpoint here: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-theme-upgrader.php#L295

* ... so in theory, it's a matter of connecting Calypso to the endpoint with a new action and adding it to the theme options here: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/themes/theme-options.js

* ...with a check to make sure 1) there's not an update available and 2) you're not on a Jetpack site for `hideForTheme`

**Comment by cometgrrl** [comment]
This appears to be working correctly now. 
![Uploading Screenshot 2022-08-22 at 3.50.37 PM.png…]()
