### ISSUE TITLE
Crawlers: Prevent Google bot (and some other bots) from seeing the /browsehappy browser unsupported page

### ISSUE THREAD

**Issue by dkd903** [Automattic/wp-calypso#56602]
### Steps to reproduce the behavior

1. [Override Chrome user agent](https://developer.chrome.com/docs/devtools/device-mode/override-user-agent/) to use the Google mobile crawler bot user agent string: **Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot /2.1; +http://www.google.com/bot.html)**
2. Then go to one of these urls: WordPress.com/log-in or WordPress.com/start or WordPress.com/themes
3. Notice you will be redirected to /browsehappy?from=/log-in (browser unsupported page)

#### What I expected to happen
Page should load correctly for GoogleBot (very Important), Google Mobile Crawler Bot (Very Important) and Semrush Bot (Required for internal analysis)

#### Browser / OS version

- User Agents: Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot /2.1; +http://www.google.com/bot.html)
- User Agents: Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)

#### Does this happen on simple or atomic sites or both?

- WordPress.com/log-in 
- WordPress.com/start
- WordPress.com/themes

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It is hampering clicks to the Log-In page in terms of - the google bot is seeing this unsupported message and as a result it is gradually pulling urls out of its index.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

- https://share.getcloudapp.com/p9ukDGLm
- https://share.getcloudapp.com/wbubl7xd 
- https://share.getcloudapp.com/geuANze7
- https://share.getcloudapp.com/wbubl7Gn

**Comment by noahtallen** [comment]
@dkd903 Are the bots trying to access logged-in pages, or are the pages they interact with public? @Automattic/team-calypso-platform have been talking about this, and we think it might be best to just not redirect public pages.

**Comment by dkd903** [comment]
@noahtallen we have noticed these issues on 3 pages so far and all of them are public pages:

- WordPress.com/log-in
- WordPress.com/start
- WordPress.com/themes
