### ISSUE TITLE
Feature Parity: @import CSS call is stripped on Simple sites, not on Atomic sites.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#56603]
### What plan tier(s) are affected?

Business, eCommerce

### Steps to Reproduce

1: Go into Appearance > Customize > Additional CSS, on any theme.
2: Paste the following code:

```
@import url('https://fonts.googleapis.com/css2?family=Caveat:wght@400;500&display=swap');

:root {
		--global--font-primary: Caveat;
	
	  --responsive--alignwide-width: 1500px;
	--responsive--aligndefault-width: 800px;
	--global--spacing-vertical: 50px;
	--button--padding-vertical: 20px;
}
```

3: Save your CSS.

### Expected (Simple)

This should be valid CSS code, and accepted by the customizer.

### Expected (Atomic)

If this is not meant to be accepted by the customizer, then atomic sites should strip it out.

### Actual

On atomic sites, the above CSS will be passed into the customizer without issue and reflected on the site. On simple sites, it will be stripped out.

**Comment by arinoch** [comment]
Brought to my attention by a colleague in p1632789758337500-slack-C03TY6J1A as I was reverting their site at their request. They were using the above CSS on their site while atomic, it was stripped when they attempted to use it after the revert. Reporting it here as it may be a source of user frustration--both scenarios are undocumented and inconsistent.

**Comment by formosattic** [comment]
Thanks for the report @arinoch 

From https://wordpress.com/support/editing-css/#frequently-asked-questions, it's not expected to work on Simple sites:

> WordPress.com Premium currently does not allow loading outside files via CSS, but is possible on WordPress.com Business and eCommerce.

But I guess we could have a more elegant way to handle it on Simple sites, like having a warning when clicking on Save. 
Right now, this happens when the code is saved and Customize get reloaded:

![troubleshooting](https://user-images.githubusercontent.com/15944096/135044999-b032c0f6-fd1c-4751-9d45-b8901bab15a2.gif)

As an aside, on atomic, fonts can also be added by:
* enqueuing the fonts in `functions.php` or with a dedicated plugin
*  import call to their theme/child theme’s main `styles.css` file

**Comment by arinoch** [comment]
Thanks for the feedback, @formosattic. I believe the issue is, and this is why I didn't include premium sites in the labels when I opened the issue, the user remained on a business plan. They only reverted from atomic to simple.

If I'm a user on a business plan and I have no reason to go atomic (I'm fine with the Twenty Twenty-one theme, for example, or all the functionality I need is provided by wpcom), I'm reading the quoted section of that document and thinking "Good, this applies to me.". Then I'm adding that code, watching it get stripped out, and I'm in live chat or a ticket asking why. That, I believe, is the issue that needs addressed in the thread.

> As an aside, on atomic, fonts can also be added by:

* enqueuing the fonts in functions.php or with a dedicated plugin

* import call to their theme/child theme’s main styles.css file

To do that, however, you first need to go atomic. Per the linked Slack thread, once you're atomic, you don't need a plugin to make use of @import or any of the other code pasted here. So: Keep Twenty Twenty-One, install Hello Dolly, now the above CSS code works. Revert and therefore remove Hello Dolly, that code fails.

**Comment by inaikem** [comment]
Expected functionality. Simple sites do not permit loading external files via CSS. see: https://wordpress.com/support/editing-css/#frequently-asked-questions.

Internal discussion is here: p1632916575392700/1632789758.337500-slack-C03TY6J1A
