### ISSUE TITLE
Alphabetise the WordPress.com account/connected apps list

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#56610]
### What

Alphabetise the WordPress.com Account connected apps page at: https://wordpress.com/me/security/connected-applications.

### Why

The current ordering is cluttered and confusing 🙏 

Example:
&nbsp;

<img width="1119" alt="Markup 2021-09-28 at 18 47 26" src="https://user-images.githubusercontent.com/66711744/135073517-aa7c8a01-3c01-424d-ba76-7c4d7c6f98ab.png">

### How

Sort the items in the screenshot above from A to Z.

**Comment by Aurorum** [comment]
PR for this issue in #56620. :)
