### ISSUE TITLE
Block widgets: Sidebar widgets area won't come up in the Customizer

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#56621]
### Quick summary

I am not sure (didn't have time to research more) how widespread this is, if it's theme-related, atomic vs simple, etc, but I just helped a user in 31923292-hc to be able to edit their sidebar widgets (a mix of Legacy AND block ones), and I had to point them to /wp-admin/widgets.php for the sidebar area to come up.

Theme: Tortuga

In WordPress.com we are pointing users who click in Appearance > Widgets to /wp-admin/customize.php?return=%2Fwp-admin%2Fwidgets.php&autofocus%5Bpanel%5D=widgets - and here, for this site, the sidebar area does not come up - if you click Widgets > only the "Footer" option comes up, no "Sidebar".

### Steps to reproduce

See above

### What you expected to happen

Both widget areas should come up in the Customizer.

### What actually happened

Only Footer area comes up.

### Simple, Atomic or both?

Atomic

### Available workarounds?

Yes, easy to implement

### Workaround details

Direct users to wp-admin/widgets.php.

**Comment by helenaartmann** [comment]
Thanks, David! I also helped someone this morning with the same issue: 4333211-zen

**Comment by Robertght** [comment]
One similar report where using /widgets.php/ also did the trick: https://github.com/Automattic/wp-calypso/issues/55437

**Comment by yansern** [comment]
Customizer only show widget areas that exist on the page. If the widget area does not exist on the page, click on other pages where the widget area is shown. This is left as a note which is easily missed.
![image](https://user-images.githubusercontent.com/1287077/136245617-85db4128-1989-412f-8eaa-a409289c1ac8.png)

The standalone widgets editor is the place to go to edit all the widget areas. :)

Marking this as won't fix as it is a non-issue.

**Comment by davipontesblog** [comment]
Thanks for looking into this one @yansern . I am reopening it as, in fact, the page visualized in the Customizer when that message appeared does in fact contain the sidebar - but it still shows the message, and it doesn't allow to edit the widgets.

**Comment by davipontesblog** [comment]
I opened the customer's site in the Customizer now, and it seems like this is not an issue anymore. I wonder if it got fixed with a recent Gutenberg plugin update or similar? In ay fashion, I am closing it again as "Fixed" :)

<img width="1513" alt="Screen Shot 2021-10-06 at 13 03 07" src="https://user-images.githubusercontent.com/31009008/136250513-2748600e-0c8b-40fb-9c0a-89b33abcf18f.png">

**Comment by yansern** [comment]
Thanks!
