### ISSUE TITLE
Misalignment of text in the `/start` domain picker

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#56628]
### Steps to reproduce the behavior

1. Go to `/start`
2. Click on a domain search

#### What actually happened

The left edge doesn't line up.

<img width="50%" src="https://user-images.githubusercontent.com/1500769/135174910-b3d0ecf6-aebc-4a26-9e9e-61333133f105.png">

#### What I expected to happen

This is what it used to look like, and what it looks like if we revert the changes to the reskinned header and buttons #56311

<img width="1445" alt="Screenshot 2021-09-29 at 11 30 13 AM" src="https://user-images.githubusercontent.com/1500769/135174800-e6fdf6a1-912d-4b87-8cfb-002579bebad0.png">

Of course we can't just revert #56311 because we want those changes to the reskinned style too.

### Context

Reported p1632512970019900-slack-C01VA100LEA

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

**Comment by roo2** [comment]
looks like this was fixed already by https://github.com/Automattic/wp-calypso/pull/56642
