### ISSUE TITLE
Obsidian: Logo is not showing on Homepage

### ISSUE THREAD

**Issue by sguzovskaia** [Automattic/wp-calypso#56644]
### Quick summary

User can't get the logo to display correctly on the homepage. They have changed the logo in the Customizer and it displays correctly on other pages, but it is not showing anything on Homepage. They've reset the logo multiple times, deleted the old logo image from the site, and cleared the cache.

![Markup 2021-09-29 at 10 03 21](https://user-images.githubusercontent.com/47414943/135239548-59c15e24-7642-4b32-8b84-9f48d8b4850f.png)

I was not able to replicate it on my site with the Obsidian theme installed.

Follow-up ticket: 4333818-zd-woothemes

### Steps to reproduce

**On user site:**
1. Change the logo in Customizer > Site Identity
2. Click Save Changes.

### What you expected to happen

Expected to be able to save the logo on the Homepage as well.

### What actually happened

No change with the logo on the Homepage neither in Preview nor on the live site. Other pages showing updated logo.the 

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Obsidian

### Reproducibility

Consistent

### Severity

One

**Comment by formosattic** [comment]
Closing as it was a theme setting, logo is to be set under `Appearance > Customize > Theme Options > Front Page Logo`.

Obsidian theme guide: https://web.archive.org/web/20210830120841/https://wordpress.com/theme/obsidian
