### ISSUE TITLE
Feature Request: Welcome Notifcation in the Notifications Sidebar copy update

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#56669]
## What

Update the Welcome Notification that new users receive in the Notifications Sidebar.

## Why

The Welcome Notification sent to  all new users via the Notifications Sidebar needs sharper copy. It's the first notification users see and it should be clear and deliver con

See the P2 for the in-depth discussion on improvements to the Welcome Card Notification pdgK6S-7z-p2

## How

Update the copy to be pdgK6S-7z-p2#comment-336:

Welcome to WordPress.com! Soon, you’ll be launching a beautiful new site you can be proud of.

Here are a few steps to get started:

Go through your site set-up checklist.
Watch a getting started video or join our free live webinars.
Check out our help library or connect with us in live sessions to get expert advice on building your site.
If you need more help, our support documentation covers a wide variety of topics.

BEFORE (existing)
![image](https://user-images.githubusercontent.com/5665959/135334537-c2549433-3b4a-4127-987f-37db707eafa5.png)

AFTER (the change to be made)

![image](https://user-images.githubusercontent.com/5665959/135333360-c310d6c6-5409-435e-a9a7-0cc5abc472a7.png)

### Recent updates to copy:
https://github.com/Automattic/wp-calypso/issues/55362
D66025-code

**Comment by arthur791004** [comment]
I'm working on this and here is the result

<img width="300" src="https://user-images.githubusercontent.com/13596067/143539193-11f3dcdd-798d-417e-a632-b61d9e1847b6.png" />

**Comment by arthur791004** [comment]
Close it via D70483-code, https://github.com/Automattic/wp-calypso/pull/58483, and https://github.com/Automattic/wp-calypso/pull/58388
