### ISSUE TITLE
Full Site Editing: Create a FSE card in Blog Report Cards

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#56676]
### Details

Our blog report cards are the critical HEs and we should create a section for Full Site Editing

### Checklist

- [ ] explain how active status works
- [ ] result of `gutenberg_is_fse_theme`
- [ ] active status
- [ ] is_eligible status

**Comment by Copons** [comment]
Work in progress: D68074-code

**Comment by Copons** [comment]
Closed by D68074-code!
