### ISSUE TITLE
Cookie & Consents Banner Widget: Warning for WordAds appears when WordAds is not active

### ISSUE THREAD

**Issue by lizswafford** [Automattic/wp-calypso#56673]
### Quick summary

Unable to change the Cookie & Consents Banner options in the Customizer > Widgets specifically for the section titled "Capture consent & hide the banner". 

Unable to select any of the options in that section: 
- after the user clicks the dismiss button
- after the user scrolls the page
- after this amount of time 

Error message is visible: 
Visitors must provide consent by clicking the dismiss button when WordAds is turned on. 

However, the site does not have WordAds turned on.  This appears to affect only simple sites.

<img width="463" alt="Cookie_banner_error" src="https://user-images.githubusercontent.com/33204818/135340617-e25610b3-c7c8-496b-afe1-67033897f1f3.png">

### Steps to reproduce

1. Use a simple site, with no active WordAds account 
2. Go to WordPress.com > My Sites > Appearance > Customize > Widgets 
3. Add the Cookie & Consents Banner Widget 
4. Click to select one of the options under "Capture consent & hide the banner"
5. Notice that there is a WordAds related error message
6. Banner works as expected and does appear on the site, but it's not possible to change that specific setting

### What you expected to happen

Expect the options for "Capture consent & hide the banner" to be clickable (selected). 
No WordAds mention when the site does not have the WordAds program active.

### What actually happened

It's not possible to click to select the three options for 

"Capture consent & hide the banner": 
- after the user clicks the dismiss button
- after the user scrolls the page
- after this amount of time 

It's not possible to dismiss the warning about WordAds. 

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by synora** [comment]
Triaged. Can replicate. Though I'm not sure, I think @Automattic/flow-patrol-create may be able to assist with this.

**Comment by devNigel** [comment]
I have closed a related ticket ( 4337048-zen )  since the bug report has been triaged.

Please update the user via a new ticket once the bug is fixed.

**Comment by arcangelini** [comment]
It looks like the widget form is supposed to be looking for a PHP that is likely not available from the block editor `$this->wordads_active`.

Let me see if I can find a resolution for this.

**Comment by arcangelini** [comment]
OK, since the widget customizer is not able to grab the public variables, the function that determines if wordads is enabled automatically returns `true`.

`! defined( 'NOADVERTS' ) && ! defined( 'NOADSUPGRADE' ) && 1 != get_option( 'permanent_noadverts' )`

I have been trying to use some of the newer methods for determining if wordads is enabled, but when I try to grab the blog-id I continue to return the public.api ID rather than the blog. Probably because it is the API making the cal to retrieve the widget? I will see if there is another method for grabbing this information.

**Comment by arcangelini** [comment]
There is a patch that is being reviewed and should be deployed soon that fixes this - D69860-code

**Comment by arcangelini** [comment]
Deployed and resolved - r234769-wpcom
