### ISSUE TITLE
Comments: Clicking on "Bulk Edit" button crashes Calypso

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#56704]
### Steps to reproduce the behavior

- Start with a WordPress.com site (doesn't matter if it's simple or Atomic)
- Click on the comments menu on the left
- Click on 'Bulk edit' button
- See that Calypso crashes with a white screen, and has a log on console as well

#### What I expected to happen

That the bulk edit button allows the user to choose comments.

#### What actually happened

Calypso crashes instead.

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/18581859/135459029-9094fb13-9368-4b1d-be3f-b43a1df4f17c.png">

<img width="1773" alt="image" src="https://user-images.githubusercontent.com/18581859/135459270-056529c5-0f98-4fb6-9637-62b8b8054937.png">

### Context

User report.

#### Browser / OS version

- Firefox on Mac: 92.0.1 (64-bit)
- Mac OS 12.0 beta

#### Is this specific to the applied theme? Which one?

Not applicable.

#### Does this happen on simple or atomic sites or both?

Both.

#### Is there any console output or error text?

Console shows this:

```
Uncaught TypeError: e.props is undefined
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

All sites.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Added above.

**Comment by arunsathiya** [comment]
30753684-hc.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by nickpagz** [comment]
Another report here #31979176-hc
Suggested the classic view as a workaround.

**Comment by kingsleyinfo** [comment]
Another report here: #4342665-ZEN
Suggesting the classic view as a workaround as well.

**Comment by rw-ye** [comment]
Another report: 4343442-zd-woothemes

**Comment by kuropixel** [comment]
Another report, was able to duplicate: 4348506-zd. Classic view seems to be the current workaround, will suggest.

**Comment by alshakero** [comment]
Fix is being deployed. Should be live in 30 mins.

**Comment by alshakero** [comment]
Fix is live! Would be nice to inform the users that the issue is fixed.

**Comment by sharonlaker19** [comment]
> Another report here: #4342665-ZEN Suggesting the classic view as a workaround as well.

The user has now responded to confirm that the fix is working for them.
