### ISSUE TITLE
Ability to check PHP error log without contacting support

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#56705]
### What

Users would like to check PHP error logs on their Atomic sites without contacting WordPress.com Happiness Engineers.

### Why

This is help customers self-service their theme or plugin crashes, without having to contact WordPress.com support team.

### How

I think it'd be neat to have the log automatically display on the `Hosting Configuration` area: https://wordpress.com/hosting-config/

**Comment by arunsathiya** [comment]
Requested on 31952947-hc.

**Comment by JoshuaGoode** [comment]
Until a dashboard exists, users can utilize WP_DEBUG to do this on their own: https://wordpress.com/support/wp-debug/

**Comment by arunsathiya** [comment]
This is now possible: [Access PHP Logs and Webserver Logs](https://developer.wordpress.com/docs/troubleshooting/site-monitoring/#access-php-logs-and-webserver-logs). Closing.

![Image](https://github.com/user-attachments/assets/fd7ac287-208e-49f5-8326-78710f58d8ce)
