### ISSUE TITLE
Stats: Follower count doesn't update after 15000 followers

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#5671]
When a site hits 15000 followers, new readers can still follow and the follow works correctly. However the follower count caps out at 15000 in the Stats view.

#### Steps to reproduce
1. View site stats with 15,000 followers
2. Follow the site
3. View stats and notice the count doesn't bump to 15,000, it stays at 15,000

#### What I expected
As a site owner, as each new reader follows the site I expect to see the count of Followers to go up accordingly.

#### What happened instead
The new follower is added, their information and gravatar appears in the stats listing, but the follower count doesn't increase. Perhaps older followers no longer appear in the list and only the first 15,000 appear?

**Comment by alexjgustafson** [comment]
Need to follow up with WordPress.com user in #2684127-t regarding this issue.

**Comment by lancewillett** [comment]
Thanks for the report. And, great problem to have. :)

**Comment by kriskarkoski** [comment]
@alexjgustafson I checked the site in the referenced ticket and I now see 15,029 in their stats so it looks like this was fixed at some point.
