### ISSUE TITLE
Blogger Import: Apostrophes have a backslash after import

### ISSUE THREAD

**Issue by aisajib** [Automattic/wp-calypso#56747]
### Quick summary

We got a report that a Blogger import is causing issues with apostrophes. Every apostrophe on WordPress.com (after importing from Blogger) has a backslash before them.

### Steps to reproduce

1. Following the instructions [here](https://wordpress.com/support/import/coming-from-blogger/#import-to-word-press-com), go to My Sites → Tools → Import → choose Blogger. 
2. Upload the file from Slack: p1633229489325500-slack-C01UW7SB411 
3. Wait till import is finished. 
4. Visit the site.

### What you expected to happen

1. All posts should have the correct formatting, including apostrophes. 

### What actually happened

1. There's a backspace before every apostrophe. 

### Context

Originated on this forum thread: https://wordpress.com/forums/topic/import-from-blogger-35/?view=all#post-3744096

Slack convo: p1633229489325500-slack-C01UW7SB411 

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by kerrynicl** [comment]
Triaged. Can replicate in testing

**Comment by pento** [comment]
Fix in progress for this in D68324-code.

**Comment by pento** [comment]
Fix has been deployed, confirmed that it works correctly in production. 🙂
