### ISSUE TITLE
Jetpack Search: two `Search` submenu for atomic sites

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#56741]
### Quick summary

Two Search submenu under Jetpack in the sidebar.

![image](https://user-images.githubusercontent.com/1425433/135784073-254d8151-9d7e-4845-8096-504f90715c83.png)

### Steps to reproduce

1. Open a atomic site with Jetpack Search subscription
2. Open Calypso, expand Jetpack menu in the sidebar
3. You could find two `Search` sub menus

### What you expected to happen

Only one Search submenu should be shown for atomic sites -  I'd prefer the new Search admin page - while simple site should still use the Calypso Jetpack Search page.

### What actually happened

two `Search` sub menus are shown.

### Browser

Mozilla Firefox, Apple Safari, Android Chrome

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by lsl** [comment]
Should have checked wp-calypso first eh, I created this issue in Jetpack yesterday: https://github.com/Automattic/jetpack/issues/21443

**Comment by kangzj** [comment]
Hi @lsl thanks for report the issue anyway. And you were right, the fix is on the Jetpack side 😄

**Comment by masperber** [comment]
+1 32428932-hc / 4409294-zen

Clicking the top of the two Search items prompts the user to sign up for Jetpack. The bottom one properly shows Jetpack Search enabled.

**Comment by kangzj** [comment]
Hi team, the fix is merged , and will be deployed to Atomic sites in Jetpack 10.3.
