### ISSUE TITLE
Implement woocommerce-installation for business plans on simple

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#56776]
The current /woocommerce-installation/ menu item in calypso only supports installation of WooCommerce for Business plans on Atomic sites. We want to expand this to Business and premium plans on simple or atomic. Due to other blockers for premium plan atomic transfers limit the scope of this ticket to working on business plans on simple.

- [x] Unblock the atomic only restriction
- [x] Add a wpcomstaging.com warning step
- [x] Add an atomic transfer step
- [ ] Update plugins installed to be WooCommerce + WC Pay

**Comment by lsl** [comment]
`/woocommerce-installation/`: ~https://github.com/Automattic/wp-calypso/pull/56489~ https://github.com/Automattic/wp-calypso/pull/57307

Enabling plugin install of more than one plugin at a time: D68873-code

**Comment by lsl** [comment]
- [ ] Update plugins installed to be WooCommerce + WC Pay

D70119-code D69935-code, D69993-code, D68873-code

**Comment by retrofox** [comment]
> [x] Add a wpcomstaging.com warning step

https://github.com/Automattic/wp-calypso/pull/58024

**Comment by lsl** [comment]
Closing this out, broke the final task down into:

- https://github.com/Automattic/wp-calypso/issues/58227
- 11-gh-Automattic/woo-on-plans
