### ISSUE TITLE
Domain Search: Updated design for privacy selection with plans-only

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#5677]
It was noted last week that we should update the Privacy selection to account for the new plans-only model. This design updates the copy to make it more clear that privacy is included and defaults privacy to selected. 

<img width="690" alt="screen shot 2016-05-30 at 2 33 04 pm" src="https://cloud.githubusercontent.com/assets/3011211/15658707/8d7f657e-2674-11e6-90b5-050f6c3141f9.png">

Note: This change should not apply to additional domains purchased or any other scenario where privacy is not included for free.

cc: @umurkontaci @lucasartoni (as this is an iteration on the Privacy A/B test that's being deployed this week)

**Comment by ranh** [comment]
Not directly related to the plansOnly change, but how about this for the description?

> Privacy Protection hides personal information in your domain's public records, to protect your identity and prevent spam.

**Comment by breezyskies** [comment]
Copy 👍

**Comment by umurkontaci** [comment]
@aidvu What's the status of this issue?

**Comment by aidvu** [comment]
https://github.com/Automattic/wp-calypso/pull/6455
Done.
