### ISSUE TITLE
"What's New" Feature Broken on Atomic Sites

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#56797]
### Quick summary

The "What's New" feature doesn't appear once clicked on for Atomic sites. It's working as expected on Simple sites.

My Atomic test site:

https://user-images.githubusercontent.com/10015451/136072304-6fb7e7e4-4ccb-4b07-bf82-0df066ad5b34.mp4

My Atomic site with the Site Editor enabled:

https://user-images.githubusercontent.com/10015451/136072344-0310b37d-5209-4033-a0f2-53c19c3c2d9f.mp4

My simple site:

https://user-images.githubusercontent.com/10015451/136072422-f545a153-fbd5-4361-906b-110e70b97a14.mp4

Note: “What’s New” works as expected when a FSE site is created via the Horizon link though.

Originally reported at p5uIfZ-bu2#comment-16671

### Steps to reproduce

1. Open a page or post on an Atomic site
2. Click on the three vertical dots within the editor
3. Click on "What's New"

### What you expected to happen

The "What's New" modal to pop-up on the screen and show me information about new WordPress.com features.

### What actually happened

Nothing happens when What's New is clicked on.

### Context

Discovered this in my own testing.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

N/a

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by synora** [comment]
Tagging @Automattic/flow-patrol-create in case this within your realm. @jordesign this may be something for the Simple/Atomic Pod folks to look into as well.

**Comment by alshakero** [comment]
I did some investigation and it seems WhatsNew package [issues a wpcom-proxy request](https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/packages/whats-new/src/index.js#L20) and then renders the response. 

But this request is never going though, because the wpcom-proxy-iframe (which is what we use to proxy requests to public-api) isn't sending a message to the parent window, which keeps the request enqueued forever. Because the requests are queued until the iframe posts the first message, but it never does. I'll dig deeper tomorrow.

**Comment by jordesign** [comment]
Scrubbed and confirmed this issue - I'm not seeing any console errors when clicking the 'What's New' - just a total lack of *anything* happening.

**Comment by vindl** [comment]
Hi @alshakero, just wanted to check if there are any new updates on this issue? If you are not planning to work on it anymore Build can take it over.

**Comment by alshakero** [comment]
@vindl hi!it would be great help if you take this over. Thanks!

**Comment by p-jackson** [comment]
See #63874 for details, but in the end we decided to disable the What's New button on Atomic for now. Better than having a broken button. The What's New feature will ultimately find its way into the Help Centre which is also going to have to figure out how to make this work. Better to piggy back off that work.
