### ISSUE TITLE
[Bug]: Searching for plugins in Calypso doesn't have pagination

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#56793]
### Quick summary

We will need to add pagination to the Calypso plugins search list. Let's use the Marketplace new designs for plugins search list oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A46946

### Steps to reproduce

1. Start at `https://wordpress.com/plugins/[DOMAIN]`
2. Search for `woocommerce`

### What you expected to happen

I expected to be able to find more than 24 plugins

### What actually happened

<img width="1157" alt="SS 2021-10-05 at 18 55 50" src="https://user-images.githubusercontent.com/12430020/136059200-bcbdc7f3-0ab5-40c7-b2ad-07ad881f34ac.png">

### Reproducibility

Consistent

**Comment by gcsecsey** [comment]
While testing the staging build with @cpapazoglou, we've identified an issue of the placeholder items not showing when using the paginated `PluginBrowserList` component. I'll create a follow up PR to resolve it soon.
