### ISSUE TITLE
Editor: Preview on smaller screens not responsive

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#568]
Noticed this happening on iPhone 6+, but also occurs when browser size is >760px wide. 

It always shows the desktop view, even if the theme is responsive. 

![img_1338](https://cloud.githubusercontent.com/assets/5835847/11347016/9db6471c-91ed-11e5-9861-ecd681c759bc.PNG)

**Comment by nishanttotla** [comment]
The preview button is also unresponsive while editing posts on the Mac desktop app
<img width="381" alt="screen shot 2015-11-23 at 2 23 22 pm" src="https://cloud.githubusercontent.com/assets/1872537/11351877/f26a5820-91ed-11e5-800d-77cc8a51b6b7.png">

**Comment by designsimply** [comment]
Related: #312
