### ISSUE TITLE
Gutenberg - Mark HTML tag - Styles attributes removed after saving

### ISSUE THREAD

**Issue by geriux** [Automattic/wp-calypso#56826]
When a post has a `mark` HTML tag with a set color and background styles, it loses those styles attributes after saving.

There's a [new feature](https://github.com/WordPress/gutenberg/pull/34680) in Gutenberg core, that will allow this customization from the editor but it will be affected by this bug as well.

#### Steps to reproduce

1. Create a new post
2. Toggle to the Code editor (HTML mode)
2. Add a `mark` tag with a custom color and background style:
```
<!-- wp:paragraph -->
<p>Hey <mark style="background-color:#986060;color:#ff7700">there</mark> how <mark style="background-color:#003d9e;color:#00bbff">are</mark> you?</p>
<!-- /wp:paragraph -->
```
3. Toggle back to Visual mode
4. **Expect** to see the right colors 
5. Save the post and close it
6. Open the post
7. You'll see that the colors are gone, if you check the HTML the mark tags don't have the `style` attribute.

#### What I expected

To see this after saving:

<kbd><img width="496" alt="Screenshot 2021-10-06 at 12 01 06" src="https://user-images.githubusercontent.com/4885740/136182887-22f36746-5bbb-4a9a-95a5-7e6bd8249126.png"></kbd>

#### What happened instead

The `style` attributes are removed from the `mark` tags, losing the previous colors.

<kbd><img width="475" alt="Screenshot 2021-10-06 at 12 00 51" src="https://user-images.githubusercontent.com/4885740/136182933-27a95e18-b94a-4484-86be-7e2352679035.png"></kbd>

#### Browser / OS version

Chrome 94.0.4606.54 

#### Screenshot / Video

You can see it above

#### Context / Source

It looks like this attribute is being removed while saving.

**Comment by KokkieH** [comment]
Previous issue for this in #48536.

This should be fixed by D68544-code, so we can close this issue.
