### ISSUE TITLE
Collect Payments: Three-dots menu `...` not visibile enough

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#56820]
### Quick summary

The three-dots menu at https://wordpress.com/earn/payments/ has a very light grey color and is hardly visible, so customers miss it sometimes.

### Steps to reproduce

Visit My Site → Tools → Earn → Collect Payments (https://wordpress.com/earn/payments/) on a site that has at least one customer/subscriber

### What you expected to happen

See a more visible three-dots menu `...`

### What actually happened

Three-dots menu `...` has a very light grey color and is hardly visible

![image](https://user-images.githubusercontent.com/39308239/136172735-6c00ad0b-f99a-43a5-90c0-cb169d36e0c9.png)

### Context

Reported by the customer in 29377174-hc, quoting:

>I didn't see the little dots on the right corner of each payment (they are not very visible in light grey on the white background). 

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by inaikem** [comment]
Thanks for the report @zdenys.

Closing in favour of: https://github.com/Automattic/wp-calypso/issues/43227
