### ISSUE TITLE
Activity Log: Restore/download buttons become squished for detailed events

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#56823]
### Quick summary

This comes as a result of this issue: https://github.com/Automattic/wp-calypso/issues/49528

### Steps to reproduce

![image](https://user-images.githubusercontent.com/6737345/136179250-21997ed9-9b33-444c-8083-cfe7a0818e76.png)

### What you expected to happen

To have the buttons keep their dimensions while the logs description increasing height.

### What actually happened

Check screenshot

### Theme-specific issue?

Atomic

**Comment by nelsonec87** [comment]
It seems the issue cannot be reproduced anymore. It just works as expected on different window widths and title lengths.

![image](https://user-images.githubusercontent.com/3801502/138930094-55398ba3-c7c0-4157-8bbf-f0ec9a185d72.png)

@Robertght also tried to reproduce it again, but without success:
![image](https://user-images.githubusercontent.com/3801502/138930180-aeda68d5-8769-4361-8287-552069bd6f91.png)
