### ISSUE TITLE
Design Picker: Loading screen experience needs improvement

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#56831]
A minor issue. It feels a bit strange to have step 1 of 1 …

![image](https://user-images.githubusercontent.com/545779/136226520-4f99e366-804a-4aa9-a5e1-50919283069d.png)

![image](https://user-images.githubusercontent.com/545779/136226556-e6cc6322-e300-46fc-a939-f32f277fc9b4.png)

… on these screens. Especially since they come so close to each other.

**Comment by autumnfjeld** [comment]
Related to improving the UX of our loading screens. THe Woo loading screens use really cute language
pdhcfv-3R-p2 go to video time 1:12

![image](https://user-images.githubusercontent.com/5665959/136621688-f42049db-ee81-4374-a84e-6ce80499a13e.png)
![image](https://user-images.githubusercontent.com/5665959/136621716-a2701591-a17a-449f-9828-2ccc641360f4.png)

**Comment by autumnfjeld** [comment]
This ticket will now be for the new loading screen/UI that @ollierozdarz  is working on.
p1633912473067400-slack-C029SB8JT8S
p1633926667085300-slack-C029SB8JT8S

**Comment by autumnfjeld** [comment]
@ollierozdarz Adding comments from slack:

From @p-jackson 
Static (W) logo, but with css to make it fade in and out a little bit? That way no JS needed.

From @ianstewart 
* Step 1 of 1 is weird. You don’t need to label steps if there’s only one step. :slightly_smiling_face:
* Having two screens saying step 1 of 1 so close to each other.

From @simison 

* Hide step 1 of 1" when there's just one step. Quickie.
* Try removing "jump" through two loading screens (loading bar & W) — you would need this anyway for applying any new design. Probably a rabbit hole?
* Consider adding more made up "steps", like "applying colours" or something fun. Would show only to people to whom it take longer to load. Quickie.

**Comment by ollierozdarz** [comment]
Thanks @autumnfjeld 🙂

We're going to roll with two scenarios:

1. A spinner (shown between `/start` and `/hero` — replacing ‘Building your site’ and the ‘W’ logo loading screens) 
2. An updated progress bar loader (shown at the end of the `/write` flow):
- The idea (originally from @ianstewart) is to have many snippets of text that we can progressively hide and show. Each time we show a new snippet of text, the progress bar can go from 0% > 100% smoothly. We'll also remove the 'Step 1 of 1' and any indication of steps.

**Comment by p-jackson** [comment]
#57051 merged: adds ellipsis loading animation and longer list of loading messages
#57050 in progress: replace the (W) logo with the ellipsis animation

**Comment by autumnfjeld** [comment]
@p-jackson @roo2   Final snippets in [this doc.](https://docs.google.com/document/d/1wRdkYL4QvSQlHwg0dRHwvgaOCaApdleaJRY9syz_k0o/edit#)

Screenshot of doc contents:
![image](https://user-images.githubusercontent.com/5665959/138184142-a1a6c8ed-6f80-4bd7-9c9b-8d63a114490f.png)


For the timings: the times listed are just a rough guide.  Use your judgement. :) 
Hopefully easy to implement the set time per snippet, having variable times will make it feel more dynamic and "authentic".

**Comment by p-jackson** [comment]
> For the timings: the times listed are just a rough guide. Use your judgement. :)
> Hopefully easy to implement the set time per snippet, having variable times will make it feel more dynamic and "authentic".

I vote we change the text in one PR and implement custom timings in a follow up.

**Comment by roo2** [comment]
@autumnfjeld do you still think we should add the custom timings?

**Comment by autumnfjeld** [comment]
I’d think this is a nice to have.  Not critical. If it was say 30 minutes
of work , then yes.

We can always come back to it.

**Comment by roo2** [comment]
@autumnfjeld oh yes I think it will be straightforward to implement if we just use hardcoded times in javascript 👍

**Comment by roo2** [comment]
Added custom timings here https://github.com/Automattic/wp-calypso/pull/57897
