### ISSUE TITLE
Design Picker: Twenty Fifteen preview appears broken

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#56837]
To reproduce hover to allow the preview to scroll up.

- Twenty Fifteen
- Twenty Sixteen
- Rockfield

![image](https://user-images.githubusercontent.com/545779/136242346-57a921ef-3eed-4449-bc8a-5aedc5248178.png)

![image](https://user-images.githubusercontent.com/545779/136242543-178b84d4-9c2e-425a-a17a-723d1ba45543.png)

![image](https://user-images.githubusercontent.com/545779/136242654-cafe6b03-daa6-4b39-b4b1-d41b51f3b6eb.png)

**Comment by autumnfjeld** [comment]
@ianstewart I believe these are no longer valid issues because we have replaced preview-on-hover with a click-thru to preview.  Those "full" previews look good to me.

I checked on:
Twenty Fifteen
Twenty Sixteen
Rockfield
