### ISSUE TITLE
Design Picker: Quadrat Demo content needs updating

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#56833]
There are lots of images being added when you select the Quadrat design. 

We may need to clean this up. **Ref:** p6nuNy-UH-p2

![image](https://user-images.githubusercontent.com/545779/136227979-46bac763-3969-4d63-8843-f7c4d0e0caef.png)

Quadrat probably does not need so many demo posts to make the design look like it does for a user and we’re likely adding too many to new to sites.

![image](https://user-images.githubusercontent.com/545779/136228567-cd6cb680-e75a-4aef-98ed-446e538f6de9.png)

Finally, something is broken in some of the content for Quadrat.

![image](https://user-images.githubusercontent.com/545779/136228814-59048777-2ebd-4d6d-aa2f-0e015a8d2b48.png)

![image](https://user-images.githubusercontent.com/545779/136228834-6d9fff07-6b41-4ed6-8064-97468b5c6350.png)

Tasks:

- Work with @alaczek and @kjellr to modify the demo site if needed and/or the Headstart content.
- Then make any modifications needed to any checklists around creating demo sites on dotcom if needed.

**Comment by p-jackson** [comment]
> Quadrat probably does not need so many demo posts to make the design look like it does for a user and we’re likely adding too many to new to sites.

Since D68118-code and #56926 deployed, we now only the first 3 blog posts

**Comment by alaczek** [comment]
@p-jackson does this mean the issue can be closed or is there something more to do here?

**Comment by p-jackson** [comment]
@alaczek I'm still seeing the broken block issue; I just reproduced in in the About page at least

> Finally, something is broken in some of the content for Quadrat.
>
> ![image](https://user-images.githubusercontent.com/545779/136228834-6d9fff07-6b41-4ed6-8064-97468b5c6350.png)

**Comment by alaczek** [comment]
I looked into the broken blocks issue and I was not able to figure out why this is happening on the About me page. 

This issue usually happens when there are some unsupported properties set on any of the blocks. But the setup on the About page is pretty straightforward, with text and images nested inside the columns block. The broken block message is only in the right column so I assume it has to be something about the heading or paragraph, but I don't know what. Maybe we could try swapping the columns block for Media & Text block and see if that helps? I tried it and visually it looked the same.

On the Home page, I suspect the issue is in nested heading and paragraph inside the Cover block. My suggestion would be to change the Cover to a Group block. We can't set min-height on the Group block, but with some extra top/bottom padding I think we're going to get a very similar look. 

cc @kjellr for feedback.

**Comment by beafialho** [comment]
> Quadrat probably does not need so many demo posts to make the design look like it does for a user and we’re likely adding too many to new to sites.

The reason why there are many posts is that in Quadrat, only the episodes show up in the Podcast page, while the "Behind the Episodes" show up in the Blog.

> Maybe we could try swapping the columns block for Media & Text block and see if that helps? I tried it and visually it looked the same.

I replaced the columns for Media & Text and it looks similar. My only concern is the lack of spacing here in smaller screen sizes:

<img width="568" alt="Captura de ecrã 2021-10-13, às 15 21 09" src="https://user-images.githubusercontent.com/65220155/137151989-07194613-a931-4490-9202-b82365b43bad.png">

> On the Home page, I suspect the issue is in nested heading and paragraph inside the Cover block. My suggestion would be to change the Cover to a Group block. We can't set min-height on the Group block, but with some extra top/bottom padding I think we're going to get a very similar look.

I've tried the approach suggested by @alaczek and see this:

<img width="1145" alt="Captura de ecrã 2021-10-13, às 15 16 48" src="https://user-images.githubusercontent.com/65220155/137151354-be5cda51-d13a-4a0e-be2b-e5fa48795d66.png">

How does it look on your end @ianstewart?

**Comment by alaczek** [comment]
This was an issue with the original setup as well but it's "patched" by adding a custom CSS class `mt-0` to the Group or Cover block. I don't know exactly where this class is coming from though, I don't think it's built into the theme.

**Comment by kjellr** [comment]
That's weird, I've never heard of that class. 🤔 @scruffian/@MaggieCabrera do either of you happen to know where that comes from?

**Comment by MaggieCabrera** [comment]
> That's weird, I've never heard of that class. 🤔 @scruffian/@MaggieCabrera do either of you happen to know where that comes from?

it's actually an utility class added via the advanced options of the block in the sidebar. The class lives in blockbase, [here](https://github.com/Automattic/themes/blob/f33d548de14fedb7c95b3af88b9c680a740a258b/blockbase/sass/base/_utility.scss#L17).

**Comment by kjellr** [comment]
Ah, interesting. Could that instead be added via block markup in the pattern in this case?

e.g. `<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px"}}} /-->`

**Comment by MaggieCabrera** [comment]
> Ah, interesting. Could that instead be added via block markup in the pattern in this case?
> 
> e.g. `<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px"}}} /-->`

it's not on the group block but the cover block, and that doesn't support margins yet, I don't think

**Comment by kjellr** [comment]
Argh ok. Everything should just support margins at this point!

**Comment by alaczek** [comment]
> Everything should just support margins at this point!

Amen to that! But for now, shall we add the class?

@p-jackson what about the media files? Are those trimmed automatically as well to only include media used in posts/pages?

**Comment by p-jackson** [comment]
> Are those trimmed automatically as well to only include media used in posts/pages?

Yes just to confirm: when pages/posts are trimmed, the media that's only used in those pages/posts is also trimmed.

**Comment by alaczek** [comment]
Hmm... so I tested this by generating annotation from the updated demo site, and the broken blocks message is still there on the Home page. I don't have any other ideas as to what might be wrong with this setup :| 
The About page is fixed.

**Comment by MaggieCabrera** [comment]
> Argh ok. Everything should just support margins at this point!

Apparently, I'm wrong! Looks like you can use margin on other blocks after all, I opened [this PR](https://github.com/Automattic/themes/pull/4847) to remove the utility class from the pattern.

**Comment by MaggieCabrera** [comment]
D68653-code

I tweaked the headstart annotation, if you would be so kind to review and let me know if it needs anything else?

**Comment by scruffian** [comment]
This has now been deployed

**Comment by autumnfjeld** [comment]
@ianstewart @p-jackson I believe we can close this, correct?

**Comment by alaczek** [comment]
Looks like this is a part of the larger issue we're having with headstart content and it's still not resolved: https://github.com/Automattic/wp-calypso/issues/57837#issuecomment-974863601
