### ISSUE TITLE
Error when attempting to create subdomains with 1-2 characters

### ISSUE THREAD

**Issue by IoanaAMuresan** [Automattic/wp-calypso#56838]
### Quick summary

Chat user could not add a subdomain using the format fr.example.com (or any 1-2 character subdomains). Tested on our end (help in Slack p1633517492039700-slack-C03TY6J1A ) and replicated the issue. 

### Steps to reproduce

1. Start at Upgrades -> Domains -> Add a domain to this site -> Use a domain I own
2. Add any 1-2 letter subdomains (ex. fr.example.com) 
3. Error: 'Are you sure you mean fr.example.com? This is not a valid domain.'

<img width="1509" alt="Screenshot 2021-10-06 at 19 26 02" src="https://user-images.githubusercontent.com/19170278/136254314-1e66a376-928c-4251-82cf-c05f226c8bd4.png">

<img width="1509" alt="Screenshot 2021-10-06 at 19 32 29" src="https://user-images.githubusercontent.com/19170278/136254429-5c1867a6-ec52-4203-8e3d-51295d56a1ce.png">

### What you expected to happen

I would expect for the subdomain to be created. 

### What actually happened

The action yielded the error: 'Are you sure you mean fr.example.com? This is not a valid domain.' Could not continue. 

### Context

I could create the subdomains internally for the customer. 

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Both

### Theme-specific issue?

Unlikely - domain-related. 

### Other notes

I included info on the operating sys etc. from my own setup - I do not have the customer's. The issue was also tested by another a11n - not sure of the setup. 

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

I managed to create the subdomains for the user, but since they were using country codes, this may come up again in the context of localization.

**Comment by arunsathiya** [comment]
I can reproduce the same issue.

![image](https://user-images.githubusercontent.com/18581859/136317608-6e3c2cb1-9240-4618-b066-71c0cfc3e15d.png)

![image](https://user-images.githubusercontent.com/18581859/136317622-8aac7e9b-7e10-4c7f-91dd-3b9f6f8cfb1b.png)

**Comment by IoanaAMuresan** [comment]
Here's the interaction 32058061-hc, for further reference.

**Comment by Robertght** [comment]
Thank you for reporting this folks! @Automattic/pod-domains is this something that you can look into?

**Comment by delputnam** [comment]
Updated the regex to address this in #56907.
