### ISSUE TITLE
Design Picker: Spearhead demo content needs clean up

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#56836]
The spearhead content created through the design picker leaves users with far more blog posts than needed to create the design.

![image](https://user-images.githubusercontent.com/545779/136239979-6ea5f3f4-3481-436e-bce7-39c1d268f96b.png)

**Comment by p-jackson** [comment]
D68118-code and #56926 trim starter content on sites created with the design picker so that they have a maximum of 3 posts.
