### ISSUE TITLE
Design Picker: Add random sort to selections

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#56832]
It would be good to have these designs randomly sorted. Probably with the exception of Blank Canvas. When we launch categories it’d be nice to have the designs in each category randomly sorted as well. We can use the data later to add in a trending sort to produce a better offering and also for theme and pattern design. (I think all the code needed already exists in the wp.com/new design picker.)

![image](https://user-images.githubusercontent.com/545779/136227429-f4b1a853-2551-469b-a02b-111a70683694.png)

**Comment by p-jackson** [comment]
Implementation note: take a look at the `randomize` param of the `getAvailableDesigns()` function to see the existing code for this.
