### ISSUE TITLE
Themes Showcase: Only show theme beta badges on sites that are FSE eligible

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#56854]
### Quick summary

Currently, beta badges are displayed as long as full site editing is activated on a site and disabled otherwise. Instead, we want beta badges to be displayed on _any_ site that is full site editing eligible, regardless of whether or not the full site editor is activated.

### Steps to reproduce

1. Create a full site editing enabled site
2. Navigate to Appearance > Site editor
3. Disable the full site editor
4. Note that all beta badges disappear

### What you expected to happen

Beta badges remain associated with respective themes as long as the site is full site editing eligible

### What actually happened

Beta badges disappear

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by creativecoder** [comment]
Note that the wpcom/v2/sites/block-editor endpoint is now available to retrieve FSE eligibility for a site. @zaguiini is working in https://github.com/Automattic/wp-calypso/pull/56670 on client side code to use the eligibility flag, and the `useBlockEditorSettingsQuery` hook added there should be useful for addressing this issue.

**Comment by jeyip** [comment]
> Note that the wpcom/v2/sites/block-editor endpoint is now available to retrieve FSE eligibility for a site. @zaguiini is working in #56670 on client side code to use the eligibility flag, and the useBlockEditorSettingsQuery hook added there should be useful for addressing this issue.

Thanks for the heads up! I went ahead and created a draft PR based off of his work that only displays beta badges for FSE eligible sites. https://github.com/Automattic/wp-calypso/pull/56916
