### ISSUE TITLE
FSE beta: update the after theme switch modal primary button

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#56873]
### Details

Update the after theme switch modal primary button for FSE Beta sites to always say "Edit site" or "Design your site" and link to the Site Editor, rather than the Customizer or page editor.

<img width="303" alt="132928110-e675de1f-740d-46a8-b923-fa896f8daaf0" src="https://user-images.githubusercontent.com/1182160/136422596-1664f21f-f17e-4376-8691-9976b09f7a03.png">

### Related

https://github.com/Automattic/wp-calypso/issues/54462

**Comment by olaolusoga** [comment]
"Edit Site" 👍
