### ISSUE TITLE
Navigation: Search icon when switching sites is not within search box

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5687]
When switching a site from WordPress.com Calypso the search icon is outside the search box when it should be within the search box:

![search icon](https://cloud.githubusercontent.com/assets/128826/15666034/da925b9a-2751-11e6-9763-4ccf8ebea801.png)

Found via #dogfooding

**Comment by lancewillett** [comment]
Hi @alisterscott can you please include browser / OS details and maybe a full viewport screenshot?

**Comment by lancewillett** [comment]
I tested in Firefox latest, Chrome latest, and Safari 9.1 on OS X 10.11.4 and could not repeat this issue — using 1024 by 768 px viewport with `wpcalypso` and these steps:

1. Log in to wpcalypso
2. Click "My Sites"
3. Click "Switch Site" at top left
4. See the search bar appear at top

<img width="1024" alt="screen shot 2016-05-31 at 08 43 55" src="https://cloud.githubusercontent.com/assets/66797/15680799/dde5f702-270b-11e6-97d4-32f4264b2580.png">

**Comment by lancewillett** [comment]
Chatting with @rachelmcr she mentioned she saw this earlier today in Mac-n-Chrome, but it's since been resolved. I'm going to close as "works for me", but feel free to re-open if you see it again.

Hopefully fixed in a merge sometime in between.

**Comment by alisterscott** [comment]
This was fixed by reverting the issue in #5690
