### ISSUE TITLE
Page verbiage update: Replace Mapping with Connection

### ISSUE THREAD

**Issue by kimerlin81** [Automattic/wp-calypso#56874]
### Quick summary

This is not a bug - but a WordPress.com content update request.
When users add a new site they are led to [this page](https://wordpress.com/start/domains/use-your-domain?source=https://wordpress.com/new/domains) which shows "mapping" terms instead of "connecting"

It's also in the video used here: https://wordpress.com/support/domains/connect-existing-domain/#video-overview-getting-started-with-domain-connection

### Steps to reproduce

1. Click "Add a site"
2. Routed to [this page](https://wordpress.com/new/domains). Choose "use a domain I already own"
3. Routed [here](https://wordpress.com/start/domains/use-your-domain?source=https://wordpress.com/new/domains).

### What you expected to happen

Map should be replaced with Connect
Mapping should be replaced with Connecting
![Screenshot on 2021-10-07 at 11-53-30](https://user-images.githubusercontent.com/83732167/136422817-79942536-be9c-430a-bd4c-b3b90072f467.png)

### What actually happened

"Mapping" terms appear in place of "connecting"

**Comment by Robertght** [comment]
Thank you for reporting this @kimerlin81 ! I've also reported this here a while back: p2-pcYYhz-kY
This is part of an older flow.

@delputnam  Should we keep this report for now?

**Comment by delputnam** [comment]
@Robertght This flow is still shown in both the onboarding flow and the new site flow. We're currently actively working on replacing it with the new flow. It's just taking longer than expected.

So, we're aware and in the process of addressing this.  I think we can close this report.

**Comment by dpasque** [comment]
@delputnam Will that include an updated video in the support guides? If that's a separate process, we could keep this open to track the video piece!

**Comment by carinapilar** [comment]
Also noticed today that the option to remove it still mentions _"domain mapping"_:

![Connected Domain Settings](https://user-images.githubusercontent.com/16104522/137800782-72a1a6ef-c07e-4f7f-bdf1-80f7e06683cb.jpg)

**Comment by obenland** [comment]
The Connect/Transfer step described in the issue description now looks like this, correctly using connect instead of map:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/1398304/196534735-35e6c1a2-13d0-4a32-a515-f76a0f2a73c5.png">

I could also no longer find the video on [the linked support page](https://wordpress.com/support/domains/connect-existing-domain/#video-overview-getting-started-with-domain-connection).

@kimerlin81 @carinapilar Is it okay to close this? It doesn't look like any of the reported issues still exist?

**Comment by carinapilar** [comment]
Looks good to me now, with the new workflow. 🙂
