### ISSUE TITLE
Email Templates: Verify all new templates have a settings link.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56884]
Let's verify that all seven of the new email templates we're launching have a link to adjust notification settings.

- [x] Confirmation request: introduced in D66481-code.
- [x] Welcome email: introduced in D66421-code.
- [x] New post: Introduced in D66573-code.
- [x] New comment: Introduced in D66917-code and improved in D67598-code.
- [x] Like a comment: Introduced in D67263-code.
- [x] Like a post: Introduced in D67694-code.
- [x] New WP.com follower: Introduced in D67392-code.

**Comment by andres-blanco** [comment]
It seems to be missing on the Like templates.
 - **Like a comment**: I don't think there's a place where you can configure if you want or not this notifications, so I don't know where the `settings` link should point. @saygunnyc @inaikem can you add something to this?
 - **Like a post**: this email only gets to the author so a link to settings will make sense here, I will get to it.

**Comment by inaikem** [comment]
> Like a comment: I don't think there's a place where you can configure if you want or not this notifications, so I don't know where the settings link should point. @saygunnyc @inaikem can you add something to this?

I don't have access to Phabricator to check specifics but based on the context it'd make most sense to me for this to live with other comment subscriptions settings under https://wordpress.com/me/notifications/comments.

**Comment by andres-blanco** [comment]
Thanks @inaikem that link should do it! Thanks for the feedback 🙌

**Comment by andres-blanco** [comment]
Like comment diff: D68340-code

**Comment by andres-blanco** [comment]
Like Post already has a link to settings:
![image](https://user-images.githubusercontent.com/375980/137151018-f6148c63-17df-4014-b346-704587ec4108.png)
