### ISSUE TITLE
Marketplace: Translate the remaining extensions

### ISSUE THREAD

**Issue by dlind1** [Automattic/wp-calypso#56902]
See https://wp.me/pdh6GB-2M-p2#comment-107, plus troubleshoot the translations for Table Rate Shipping

**Comment by dlind1** [comment]
Pinged the teams about Xero and Table Rate Shipping/Shipment Tracking translation support.

**Comment by dlind1** [comment]
For Xero there is an open PR to add translation support https://github.com/woocommerce/woocommerce-xero/pull/263
Opened issue for Shipment Tracking - https://github.com/woocommerce/woocommerce-shipment-tracking/issues/154
Opened issue for Table Rate Shipping - https://github.com/woocommerce/woocommerce-table-rate-shipping/issues/153

**Comment by dlind1** [comment]
Originals for Shipment Tracking were imported into the [translation project](https://translate.wordpress.com/projects/woocommerce/extensions/woocommerce-shipment-tracking/) and would be sent for translation on Monday.

**Comment by dlind1** [comment]
Still waiting for merged PR for Xero, support for other extensions was added, but there are currently some issues with generating the language packs (probably due to the PHP 7.4 upgrade) which we're currently troubleshooting.

**Comment by dlind1** [comment]
All the extensions should now be updated to include the `languages` folder in the release (see pcShBQ-aN-p2). This is currently in progress.

**Comment by dlind1** [comment]
woocommerce-shipment-tracking and woocommerce-table-rate-shipping were updated, the language packs were generated and new version with working translations was released.
woocommerce-xero is waiting for the PR to be merged.

**Comment by cpapazoglou** [comment]
woocommerce-xero is in testing phase and will be merged soon. Closing this issue as there is nothing to be done here.
