### ISSUE TITLE
FSE beta: always open Site Editor in Gutenframe

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#56906]
### Details

Prior to Screen Options for choosing between wp-admin and Calypso for each page, we had a global Dashboard Appearance toggle. That toggle UI has been removed in the meantime, but the option still persists in the background for users that have set it before. As a consequence, they'll be forced to wp-admin view of the Site Editor and won't get things like Calypso Media Library and Feedback form (see [here](https://github.com/Automattic/wp-calypso/pull/56667#issuecomment-938744680)).

I think that we should force Gutenframe (`/site-editor` path) for that link regardless, and only fall back to wp-admin in usual cases (when iframe can't be loaded or if there are conflicting plugins on Atomic).

To reproduce, you can manually set your user attribute for `calypso_preferences['linkDestination'] = true` on Dotcom side.

**Comment by creativecoder** [comment]
I believe this issue was resolved by https://github.com/Automattic/jetpack/pull/21691
