### ISSUE TITLE
FSE beta: point front end Customize link to Site Editor

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#56908]
### Details

Customize link from the front end action menu is still pointing to the Customizer. For sites that have FSE active we should redirect it Site Editor and probably change this title to `Design Site` or similar. The title should be consistent with the one that appears after theme switching in https://github.com/Automattic/wp-calypso/issues/56873.

<img width="320" alt="Screenshot 2021-10-08 at 14 58 56" src="https://user-images.githubusercontent.com/1182160/136587487-79ab8f94-9be4-49cc-99c1-94f91e9e6633.png">

**Comment by mattwiebe** [comment]
I have a patch for this in D70179-code

Note that it says "Edit Site"

**Comment by mattwiebe** [comment]
D70179-code has shipped with the fix
