### ISSUE TITLE
Theme Switch Modal: Intermittently missing on Theme Switch

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#56904]
The theme switch modal that appears on theme switch for recommended themes on dotcom, asking you how you'd like to set up your theme (keep your homepage content or grab the template from the demo site) is intermittently missing when switching themes creating an inconsistent and confusing experience.

#### Steps to reproduce

Some example steps to reproduce, not limited to any recommended theme in particular. In this case the bug happens with Twenty Fifteen. But it can happen with other recommended themes. (Reproduced with Hemingway Rewritten for example.)

- Create a new site with the blank theme.
- Switch to “quadrat” theme.
- You will get prompted if you want to replace your content with the Quadrat Homepage. Do it.
- Switch to “Hever” theme.
- You will get prompted if you want to replace your content with the Hever Homepage. Do it.
- Switch to “Twenty Fifteen” theme.
- **BUG:** Nothing gets asked.
- Switch to blank theme, get asked and use demo content.
- Switch to Quadrat theme, get asked and use demo content.
- Switch Hever theme, get asked and use demo content.
- **Example of intermittency:** Change to twenty fifteen…. get asked and use demo content!

**Ref:** p2EDhh-1lv-p2

**Comment by fushar** [comment]
We have "fixed" this issue by showing the modal in all cases. For more reference, see:

- #79294

cc @Automattic/lego
