### ISSUE TITLE
Rebalance theme: Post Carousel block display broken if "Pages" are selected

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#56910]
### Quick summary

If you set up a Post Carousel block on the Rebalance theme, and allow it to display Pages (alone or with other content types), the block displays well in the editor, the preview, and on smaller devices. However, on larger devices, the featured images appear shifted.

### Steps to reproduce

1. Activate the `Rebalance` theme on your site.
2. On a new page, add the `Post Carousel` block. (Note: This bug is **not** present on posts.)
3. In the block settings panel, under "Post Types," select `Pages`.
4. To ensure a page displays, use the "Choose Specific Posts" setting to specify at least one page on your site.
5. Save changes.

### What you expected to happen

I expected the Post Carousel to display on the live site exactly as it does in the editor:
<img width="852" alt="Markup 2021-10-08 at 13 16 12" src="https://user-images.githubusercontent.com/5630717/136597017-32d31bd3-c9af-4e8c-a2fa-22db08e218f2.png">

### What actually happened

On larger screens *only*, it instead displays with the featured image shifted:

https://user-images.githubusercontent.com/5630717/136597165-baa0a45c-1ae5-408f-a3ce-5fa253d1b44d.mp4

### Context

4359830-zen
User had a Post Carousel block set to display a handful of specific pages on their site. It works perfectly on mobile devices, but not on a desktop/laptop.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Specific to Rebalance, as far as I can tell. Tested on Twenty Twenty One, and couldn't replicate it there.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by kosiew** [comment]
Hi @jp-imagines ,

Thanks for reporting this and the detailed steps.

I could not reproduce this on a Simple site - pbeVss-x-p2

Can you add more information on how this can be reproduced?

**Comment by jp-imagines** [comment]
@kosiew Thanks for your example! I just realized that this apparently works as expected on posts (as in your example), but not on a page.

You can see it on a page on a test site here: Pd3rCh-1F-p2
...and the exact same block (copy/pasted) into a fresh post, which works as expected, here: pd3rCh-21-p2

Updated the original issue to reflect that.

**Comment by kosiew** [comment]
Thanks for the additional context.

Triaging for developers' further investigation.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by vajrasar** [comment]
📌 SCRUBBING : RESULT
- Tested on P2 - N/A
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Could Not Replicate
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO

The Post Carousel block, as reported, is either showing the featured image with reduced width (on Simple Site) or not showing at all (in my case on AT site) when the theme Rebalance is selected, and the block is showing a page with featured image. 

I was able to replicate the issue between Simple and AT using Rebalance theme. 

I checked other themes including TT2, and Zoologist but could not replicate the issue on them.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Normal` to better reflect it's status in the larger context of open bugs in the repo
- Needs retest. If still happening _only_ in Rebalance, we can transfer this to the /themes repo and add to the Bug Scrub Planning board
