### ISSUE TITLE
Social Profiles block, add TikTok

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#56921]
### What

Add TikTok as an option to Social Profiles block

### Why

TikTok is not currently possible to add to the Social Profiles block. It is not one of the available social media options. User requested HC-32115763

**Comment by Greatdane** [comment]
@Camaropilot could you clarify the Social Profiles block? 

Tiktok is available on the [Social Icons block](https://wordpress.com/support/wordpress-editor/blocks/social-links-block/).

<img width="302" alt="Markup 2021-10-11 at 09 58 51" src="https://user-images.githubusercontent.com/5075840/136719724-9b5160a2-70a8-4ee0-8331-a99232ecb3f8.png">

**Comment by Greatdane** [comment]
Closing for now. Tiktok icon is available via Social Icons block.

**Comment by Greatdane** [comment]
After speaking with @Camaropilot more, I now see that 'Social Profiles' is part of the coblocks plugin.

Suggested a opening an issue here; https://github.com/godaddy-wordpress/coblocks/issues

**Comment by Greatdane** [comment]
Added to Coblocks; https://github.com/godaddy-wordpress/coblocks/issues/2100

**Comment by dpasque** [comment]
This issue is tracking an issue in another repository. All +1's of end-user reports should be done on this issue, while any discussion related to the issue itself and its fix should be done on the issue in the outside repository.

**Comment by Greatdane** [comment]
@Camaropilot TikTok is now added!

<img width="755" alt="Markup 2021-11-04 at 15 23 41" src="https://user-images.githubusercontent.com/5075840/140267545-83054642-d5de-4da2-8006-20b94a88e6bc.png">
