### ISSUE TITLE
Jetpack: can not manually add Jetpack Search subscriptions to an AT site in SA.

### ISSUE THREAD

**Issue by sharonlaker19** [Automattic/wp-calypso#56929]
### Quick summary

A user on an AT site asked to change their Jetpack Search subscription from monthly to annual billing.

Adding the sub in SA gives this error: `Jetpack plans are not allowed on an Atomic site.`

### Steps to reproduce

1. Go to SA and pick any Atomic site.
2. Pick the Jetpack Search product (monthly or annual plan).
3. Click "Add Subscription"

### What you expected to happen

I expected a new annual subscription to be created and attached to the selected Atomic site.

### What actually happened

I received this error message: `Jetpack plans are not allowed on an Atomic site.`

<img width="445" alt="Jetpack plans are not allowed on an Atomic site" src="https://user-images.githubusercontent.com/71630911/136730726-88154cb9-4d79-4395-93f6-61c555e66f17.png">

### Context

- A user bought the Jetpack Search monthly option for their website.
- They asked to change to the annual version. 
- I thought I could add it manually in SA and update the expiry date to be the same as the paid-for monthly plan.
- There doesn’t seem to be an option to update from monthly to annual within their purchase settings in Calypso either.

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

- The alternative, for now, is to ask the user to cancel the monthly plan on their end and sign up again for the annual version.
- This is the direct link to sign up for Jetpack Search annual that you can share with them: https://wordpress.com/checkout/jetpack_search#step2

**Comment by kosiew** [comment]
Hi @sharonlaker19 ,

Thanks for reporting this and the detailed steps.

I managed to reproduce this for my test AT site - wpstore101.wpcomstaging.com

Triaging for developers' further investigation.
@Robertght for Flow attention.

**Comment by JoshuaGoode** [comment]
The WPCOM version of the product is Jetpack Search for WordPress.com, `wp-search-yearly`

However, it cannot be added via SA and our internal error is `This upgrade is not available for an Atomic site.`

Related threads:

* p1646147296531719-slack-C02BEP610
* p9F6qB-8IT-p2

**Comment by DavidRothstein** [comment]
This is an internal issue, not a Calypso issue, but I guess it's OK to track here.

Assuming that "Jetpack Search for WordPress.com" is the one that is supposed to be used on Atomic sites (and I guess it is if that is what people are buying in Calypso and it's working there?) then I think it just needs to be added to the list of products in Store Admin that are supported on Atomic sites.  This would need to be done for both `WPCOM_SEARCH` and `WPCOM_SEARCH_MONTHLY`.

(Coming here from: pNPgK-5Gu-p2)

**Comment by martian77** [comment]
It looks like rather than adding the WPCOM_SEARCH item to a list in Store Admin we actually need to implement `has_feature` on `Store_Product_Jetpack_Search`. Still a quick fix, just need to check what Calypso is using to find the products and check nothing else gets broken.

**Comment by martian77** [comment]
Diff at D79732-code

**Comment by martian77** [comment]
Actually, rethought that. I'm not sure where else the `has_feature` flag is used, so probably safer to just add it to the list in `is_atomic_blog_allowed_product()` instead. Same diff: D79732-code
