### ISSUE TITLE
Domains: don't suggest Premium Domains that aren't available for sale

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#56924]
### What

Aside from .blog, Premium domain is not supported, so it should not come up in the domains suggestions, especially not if the Premium domain is already registered. https://wordpress.com/support/premium-domains/

### Why

It's misleading:

* regular pricing is shown instead of the more expensive Premium one
* user has option to register even if the Premium domain is registered elsewhere

Example with `icloud.casa`.

From https://wordpress.com/domains/add/
![image](https://user-images.githubusercontent.com/15944096/136690394-d2e5b433-134a-41e1-8fdc-f29f7d280480.jpg)

From https://wordpress.com/domains/get/casa, it's stuck with `checking availability`:
![image](https://user-images.githubusercontent.com/15944096/136690416-feb13752-f24f-499d-a55a-463d851a0cda.jpg)

How it's shown at other registrars.

Google, https://domains.google.com/registrar/search?searchTerm=icloud.casa
![image](https://user-images.githubusercontent.com/15944096/136690480-2f0a7628-2f8e-4c63-87b9-f1a41619c16f.jpg)

Namecheap, https://www.namecheap.com/domains/registration/results/?domain=icloud.casa
![troubleshooting](https://user-images.githubusercontent.com/15944096/136690758-ee311246-c85c-4594-9df4-a867361020e9.gif)

User report: 4359773-zd-woothemes

**Comment by delputnam** [comment]
Thanks for posting about this @formosattic. We sorry this experience was not good for this customer.

Currently, we rely on a third party to ensure that the domains shown in our suggestions are correctly marked as available and premium. Occasionally, there are mistakes which cause domains to be tagged incorrectly and this leads to the exact type of error you mention here.

We have a project on the roadmap to improve and expand our premium domains offering which should help mitigate most of these experiences.
