### ISSUE TITLE
Amazon Embed - read.amazon.com.au refused to connect

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#56931]
### Quick summary

Amazon embeds are currently displaying an error message `read.amazon.com.au refused to connect.`

### Steps to reproduce

1. Go to a page or post.
2. Embed an amazon link - for example https://www.amazon.com/Woman-Splendor-Sorrow-Poems-Poetic/dp/1737296500
3. Publish page/post
4. View page, there is an error on the Amazon embed - `read.amazon.com.au refused to connect.`

### What you expected to happen

A preview of the Amazon book.

### What actually happened

An error message showed: `read.amazon.com.au refused to connect.`

![image](https://user-images.githubusercontent.com/15944096/136740369-003fe1d1-20d2-47c4-977d-ea15e26d6c9d.jpg)

### Context

I received a report from a user that their Amazon embeds are no longer working on their posts: 32134116-hc

- I tested embedding the Amazon link on both pages and posts. 
- I can reproduce the issue on both AT and simple sites consistently. 

**Slack thread**: p1633927094067800-slack-C03TY6J1A 

**Looks like this may be a widespread issue**: p1633927556067900/1633927094.067800-slack-C03TY6J1A

Reported elsewhere: https://www.reddit.com/r/Wordpress/comments/q5a658/anyone_know_why_amazon_kindle_embeds_may_be_doing/

### Operating System

Windows

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

**Comment by dev-sabbir** [comment]
Got a user here with similar issue: 4366751-zd-woothemes

**Comment by retnonindya** [comment]
Another report: 4363056-zd-woothemes

**Comment by erricgunawan** [comment]
Got a report here: 32134001-hc

Follow-ed up here: 4366685-zen

**Comment by i11za** [comment]
Another report: 4363828-zd-woothemes

**Comment by rinazrina** [comment]
Another one: 28734410-hc

**Comment by Greatdane** [comment]
Another report: 4362665-zd-woothemes

**Comment by adelineyaw** [comment]
Another report: 32132319-hc
Follow up: 4366540-zen

**Comment by yashitamittal11** [comment]
Another report- #4361111-zen

**Comment by Sandkorner** [comment]
ZEN-4362925
Seems to be the same issue.

**Comment by jamiepalatnik** [comment]
Another report: 2738542-hc

**Comment by thisissandip** [comment]
Another report: 3720547-HC

Trying to embed this book: https://www.amazon.com/Means-Grace-Seven-Ways-Grow/dp/B09FC8923R/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1633958034&sr=8-1

**Comment by mxhassani** [comment]
Reported here too: 31643534-hc

**Comment by sharonlaker19** [comment]
Another one: 32142270-hc

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
I think this is an issue from Amazon's end.

Although oEmbed API service works:

![image](https://user-images.githubusercontent.com/1287077/136817441-48809583-41e9-40ea-948a-9d98ef189c91.png)

Their iframe request is set to **SAMEORIGIN**, which is the problem here:

![image](https://user-images.githubusercontent.com/1287077/136817327-bee7d4b5-676f-48b6-9fd5-d4ac545196c5.png)

Need to reach out to the Amazon folks.

**Comment by kuropixel** [comment]
Another report. 4362785-zd

**Comment by goblinartificer** [comment]
19898067-hc

**Comment by alshakero** [comment]
I can confirm that it's 100% an Amazon issue. To reproduce on Amazon

1. Go to https://www.amazon.com/Woman-Splendor-Sorrow-Poems-Poetic/dp/1737296500
2. Click Embed 
![image](https://user-images.githubusercontent.com/17054134/136941655-f7af82d9-42ce-4e18-b923-f8f911835020.png)
3. Pick "HTML". You'll see the same issue. 
![image](https://user-images.githubusercontent.com/17054134/136942354-f6abb0ba-9e6b-4538-88ec-eca95195fc2a.png)

**Comment by alshakero** [comment]
I contacted support and waiting for their response.

**Comment by sophiegyo** [comment]
Another case in 32159515-hc - I let the user know it's on Amazon's side and suggested they use image blocks linking to the product pages as an alternative for now.

**Comment by khristiansnyder** [comment]
Another case on 32167242-hc

**Comment by thekingsprojects** [comment]
Another in 31997870-hc

**Comment by arunsathiya** [comment]
32169706-hc. Let them know that we are waiting on Amazon to respond/advise. Followup is 4366712-zen.

**Comment by hacchism** [comment]
Another case on 4369243-zen.

**Comment by yansern** [comment]
Related P2: p7fD6U-4M4-p2

**Comment by adelineyaw** [comment]
Another case: 32190716-hc
Follow up: 4375255-zen

**Comment by essleeung** [comment]
Another case: 4374151-zd-woothemes

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/amazon-kindle-preview-error/?view=all

**Comment by yansern** [comment]
Amazon embeds are now working again.
![image](https://user-images.githubusercontent.com/1287077/138668906-a910b586-b25b-4cad-a51e-3b4c1e17e10d.png)

**Comment by inaikem** [comment]
Noting that @Automattic/bug-herders have this on our radar for bulk reply: p1635217243062100-slack-C01UW7SB411 🙏

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/bug-herders have finished following up with affected users reported in this thread.

Thanks for all the reports!

**Comment by sophiegyo** [comment]
EDIT: never mind, I was wrong. This isn't the issue I thought it was. Closing again!
