### ISSUE TITLE
WordPress.com Editing Toolkit: Not able to select or exit pre-defined layout when Creating a New Page on AT sites with error 404

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#56930]
### Quick summary

When attempting to select pre-defined layouts or blank page in creating new pages, nothing happens. Could not exit and continue creating new pages.

### Steps to reproduce

1. Deactivate Gutenberg, activate WordPress.com Editing Toolkit plugin
2. Visit "My Site > Pages", select "Add New" - (wp-admin/post-new.php?post_type=page)
2. Either either one of pre-defined layouts, or "Blank Page"
3. Select 'x' to edit creating new page template.

### What you expected to happen

Able to exit the page template, or select pre-defined layouts

### What actually happened

Nothing is happening. The template page could not exit. Web consoles shows error 404 there

![image](https://user-images.githubusercontent.com/34882260/136732939-50796cf6-efce-4e6d-b84e-b7e0c57f8efb.png)

### Context

Logs shown on web console.

```
react-dom.min.js?ver=16.13.1:32 Uncaught TypeError: n is not a function
    at Object.onClose (starter-page-templates.js?ver=1632417492:6)
    at v.setPattern (starter-page-templates.js?ver=1632417492:6)
    at onClick (starter-page-templates.js?ver=1632417492:6)
    at Object.ki (react-dom.min.js?ver=16.13.1:176)
    at ji (react-dom.min.js?ver=16.13.1:13)
    at mi (react-dom.min.js?ver=16.13.1:13)
    at lf (react-dom.min.js?ver=16.13.1:13)
    at wi (react-dom.min.js?ver=16.13.1:187)
    at Kd (react-dom.min.js?ver=16.13.1:32)
    at pc (react-dom.min.js?ver=16.13.1:32)
```

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

You can either 

- Reactivate Gutenberg plugin
- Deactivate WordPress.com Editing Toolkit plugin
- Downgrade WordPress.com Editing Toolkit plugin to version 3.15741 as below:

```
wp plugin delete full-site-editing
wp plugin install full-site-editing --version=3.15741 --force
```

**Comment by edwinho89** [comment]
Reported in 31708221-hc
Followup on 4366615-zd-woothemes

**Comment by yashitamittal11** [comment]
Also reported here- #4366745-zen

**Comment by alshakero** [comment]
[This is](https://github.com/Automattic/wp-calypso/blob/94fe59f75d919c439f182764eed7d86f1f63da48/apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-patterns-plugin.tsx#L99) the line that's throwing. `setUsedPageOrPatternsModal` is not a function.

**Comment by alshakero** [comment]
This is another instance of the issue https://wordpress.org/support/topic/new-page-editing-conflict-error-in-version-3-16467/

**Comment by alshakero** [comment]
With help from @edwinho89 I managed to repro, it seems the entire `dist/wpcom-block-editor-nux.js` entire script isn't being loaded.

**Comment by Sandkorner** [comment]
32139242-HC 
Had a user where they could not access some of the admin area left sidebar like plugins, which led them to a 404 page, this is not for sure exactly the same as here I guess, but deactivating the  WordPress.com Editing Toolkit plugin, solved the issue. 
Just mentioning if that might be relevant.

**Comment by alshakero** [comment]
Note that this issue is only reproducible when Gutenberg is disabled.

**Comment by alshakero** [comment]
Alright, it seems the JS needed to control the Modal opening state (`wpcom-block-editor-nux-script`) isn’t being enqueued at all [here](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wpcom-block-editor-nux.php#L49-L55). I presume due to missing dependencies, the Modal JS depends on

```sh
'a8c-fse-common-data-stores',
'lodash',
'react',
'wp-api-fetch',
'wp-components',
'wp-compose',
'wp-data',
'wp-data-controls',
'wp-element',
'wp-hooks',
'wp-i18n',
'wp-nux', // <------------------
'wp-plugins',
'wp-polyfill',
'wp-primitives',
'wp-react-i18n',
'wp-url'
```
And it turned out that wp-nux is missing, wp-nux is part of Gutenberg, and since the `automattic/wpcom-welcome-guide` depends on wp-nux, it will only work if Gutenberg is enabled. What remains a mystery is why reverting to 3.15741 fixes the issue?

Here is a full diff between 3.15741 and 3.16467, the only difference I could see was removing React imports from TypeScript files by @vindl in #56692. Is there any possibility this could be related?

[out.diff.zip](https://github.com/Automattic/wp-calypso/files/7322632/out.diff.zip)

**Comment by katiebethbrown** [comment]
Another report in 30230561-hc.

Reactivated Gutenberg for them and things are working again now.

**Comment by yashitamittal11** [comment]
Another report- #4362975-zen

**Comment by formosattic** [comment]
31911693-hc

Enabling Gutenberg worked.

**Comment by jackiejade** [comment]
10760291-hc

Downgraded the full-site-editing plugin and it works

**Comment by davipontesblog** [comment]
Added "Priority: High" as this is likely affecting lots and lots of users. Several reports here already.

**Comment by sajmes** [comment]
Another report here 4370914-zd-woothemes

Activating Gutenberg fixed this. I could replicate on my own AT site.

**Comment by sajmes** [comment]
32162419-hc

Enabling Gutenberg fixed this one too.

**Comment by poeticabdul** [comment]
Reported here: 32162372-hc

Follow-up: 4371152-zd-woothemes

Downgrading WordPress.com Editing Toolkit plugin to version 3.15741 helped.

**Comment by dev-sabbir** [comment]
Reported here: 32172183-hc

**Comment by alshakero** [comment]
This is now fixed and live. Feel free to inform users.
