### ISSUE TITLE
 Build & Write intent gathering flow: Replace icons and Ollie's feedback on the

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#56957]
Design Feedback on the Blogger Pod Build & Write flow
Main umbrella issue for the flow: https://github.com/Automattic/wp-calypso/issues/55603

Per slack convo p1633912375066300-slack-C029SB8JT8S
Ollie has annotated the figma file with changes he'd like, see in Figma:  EuqfSnWpfYx8fgiBlVmbuA-fi-2875%3A1519

**Comment by autumnfjeld** [comment]
@roo2 I turned your note into an issue. 😄

**Comment by arthur791004** [comment]
https://github.com/Automattic/wp-calypso/issues/56957 has updated the design changed in figma
