### ISSUE TITLE
Marketplace: Create a modal introducing the new Plugins landing page

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#56955]
With the introduction of the Marketplace we are making a few changes in the UI / UX of plugins list, details, and installation flow. Moreover, we will force Atomic users to to the Calypso plugins page when they click "Add New" plugin from the sidebar. We will need to make them aware of these changes and the "why" behind them.

Let's create some content for the modal component we already have in Calypso. This way we can pop it up, once the User has reached the Plugins page and educate them.

- [x] Design
- [x] Development

**Comment by JanaMW27** [comment]
Here is the modal. The illustration is still WIP hopefully is done by the time this goes live; if not, we will use one of the old illustrations.

<img width="864" alt="Screenshot 2021-10-12 at 17 21 57" src="https://user-images.githubusercontent.com/71137829/136984209-8bb2b99d-fac5-44ad-8665-fc0b69500035.png">

Design can be found [here](https://www.figma.com/file/oU6nEIeiKSg8CayhEtgR6b/Marketplace-flow?node-id=6693%3A53628)
