### ISSUE TITLE
Atomic Downgrade: Refactor downgrade process

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#56956]
Our current automated Atomic downgrade process of (1) lossless revert + (2) plan deactivation is prone to race conditions problems, so @jmdodd has suggested to swap the order and change it to (1) plan deactivation + (2) lossless revert. 

To do so, we need:
- Make sure that requests to `wpcom/v2/purchases/cancel` and `wpcom/v2/purchases/delete` immediately deactivate the given purchase for Atomic sites. The `queued` status is no longer returned.
- Hook into the `removed_subscription` action, and trigger the lossless revert. This should cover both self-cancellations and automated cancellations after plan expiration (effectively solving https://github.com/Automattic/wp-calypso/issues/56060).
- Change the JITM message added in https://github.com/Automattic/wp-calypso/issues/56421 to omit anything mentioning that we're deactivating the plan, and replace it with a more specific message indicating that a lossless revert is in progress.
- Allow users to contact support via chat if the lossless revert has failed (otherwise, they won't be able since the paid plan is no longer active).
- Make sure that video content is imported into the reverted free site.
- Remove the mechanism that locks a subscription and hides its management, since we no longer need to lock a subscription as it's immediately deactivated.

**Comment by mmtr** [comment]
> Allow users to contact support via chat if the lossless revert has failed (otherwise, they won't be able since the paid plan is no longer active).

This is covered in D68510-code

**Comment by mmtr** [comment]
> Make sure that video content is imported into the reverted free site.

D68291-code

**Comment by mmtr** [comment]
> - Make sure that requests to `wpcom/v2/purchases/cancel` and `wpcom/v2/purchases/delete` immediately deactivate the given purchase for Atomic sites. The `queued` status is no longer returned.
> - Hook into the `removed_subscription` action, and trigger the lossless revert. This should cover both self-cancellations and automated cancellations after plan expiration (effectively solving https://github.com/Automattic/wp-calypso/issues/56060).

D68425-code and D68501-code

**Comment by BogdanUngureanu** [comment]
Deployed the self cancellation refactor in rWP233583.

**Comment by mmtr** [comment]
> Change the JITM message added in https://github.com/Automattic/wp-calypso/issues/56421 to omit anything mentioning that we're deactivating the plan, and replace it with a more specific message indicating that a lossless revert is in progress.

D68739-code

**Comment by mmtr** [comment]
> Remove the mechanism that locks a subscription and hides its management, since we no longer need to lock a subscription as it's immediately deactivated.

D68749-code and https://github.com/Automattic/wp-calypso/pull/57235
