### ISSUE TITLE
Customizer: Background patterns display vertically

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#56965]
### Quick summary

I noticed that on some themes(older ones especially) the background patterns aren't displayed horizontally but vertically.

### Steps to reproduce

1. Activate Pique or Apostrophe 2

2. Check the Colors&Background > Background.

 

### What you expected to happen

To have them horizontal

### What actually happened

![image](https://user-images.githubusercontent.com/6737345/137008218-9a6e48f1-55f3-48e9-a5a1-395d60a35ecd.png)

### Context

I noticed this while testing another feature.

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I only tested this using Pique and Apostrophe 2, but it doesn't happen with Hever for instance

### Other notes

I asked in slack-C029FM1EH/p1634020560377000, but I'm posting here as a recommendation from @jeffikus 

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
@yansern or @sixhours is this something you could look into?

**Comment by sixhours** [comment]
Closing the loop for posterity, this was fixed in D68799-code
