### ISSUE TITLE
Email Templates: Ads are not appearing in New Post templates.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56968]
I received New Post email notifications today for two accounts, one opted in to the new templates, and one not. The account that was not opted in included an injected ad – we'll need to see how to duplicate this for the new templates.

| New | Original |
| -- | --- |
| <img width="674" alt="Screen Shot 2021-10-12 at 12 48 00 PM" src="https://user-images.githubusercontent.com/349751/137020042-6f17429a-b065-465e-9004-1360f9a3b665.png"> | <img width="681" alt="Screen Shot 2021-10-12 at 12 47 47 PM" src="https://user-images.githubusercontent.com/349751/137020050-ba25840c-f695-4693-a4d0-38ae2153b26c.png"> |

**Comment by andres-blanco** [comment]
D68349-code
