### ISSUE TITLE
Email Templates: The welcome template site title is not bold.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56971]
The welcome template site title is not bold. This should be solved by removing the `strong` tag surrounding the title.
<img width="500" alt="Screen Shot 2021-10-12 at 1 35 35 PM" src="https://user-images.githubusercontent.com/349751/137025574-251fc5e8-c47e-461f-a758-ef97a3f4f7ae.png">

**Comment by andres-blanco** [comment]
D68343-code
