### ISSUE TITLE
Atomic Downgrade Feedback: Add a persistent message until the process is complete

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#56988]
Currently we display a JITM message during the downgrade process ( #56421) that can be dismissed. The only other indicator that a revert is complete is the email we intend to send.

Since there are many actions a user might take that can be removed or cause issues once the final process completes it would be good to handle this by showing a persistent message or even a progress bar of some variety.

Source: p7DVsv-cQC-p2#comment-37969

**Comment by kdevnel** [comment]
Additional discussion: p1634118924038600-slack-C029N3D2ZHR

**Comment by mmtr** [comment]
D68739-code
