### ISSUE TITLE
Feature to display random published post on a block

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#57002]
### What

To allow a block to display random published post

### Why

Something like [Related Posts Block ](https://wordpress.com/support/wordpress-editor/blocks/related-posts-block/), however it will be displaying contents from any random posts randomly.

### How

Works similar as this plugin: https://wordpress.org/plugins/advanced-random-posts-widget/

You can find some other recommendations listed in https://wpguideline.com/plugins/best-free-random-posts-plugins-for-wordpress/

**Comment by edwinho89** [comment]
Requested from 19753606-hc

**Comment by Greatdane** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/56370
