### ISSUE TITLE
Theme Showcase: Add a maximum width to theme pages

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#5700]
On wide screens, the theme pages fill the entire width, which has several side effects:
- the line lengths become long, making the text hard to read. Example:

![p2 theme wordpress com](https://cloud.githubusercontent.com/assets/7662449/15685210/be6ca790-2738-11e6-89e8-1f276859744e.png)

From: https://wpcalypso.wordpress.com/theme/p2-breathe
- white space increases around narrower images in the main column to the point where the content in the main column can look lopsided. Examples:

![theme wordpress com-5](https://cloud.githubusercontent.com/assets/7662449/15685249/e2b41368-2738-11e6-8336-e0bd6ad25eb4.png)

From: https://wpcalypso.wordpress.com/theme/edin

![theme wordpress com-6](https://cloud.githubusercontent.com/assets/7662449/15685283/0328b860-2739-11e6-9e5f-c23d16392d6b.png)

From: https://wpcalypso.wordpress.com/theme/edin
- featured images that weren't originally uploaded at a very large size appear pixillated and blurry. Example (open large version to see the issue):

![p2 theme wordpress com-1](https://cloud.githubusercontent.com/assets/7662449/15685331/3d5b3490-2739-11e6-845e-3804f291c73d.png)

From: https://wpcalypso.wordpress.com/theme/p2-breathe

All screenshots taken in Firefox 46.0.1 at:
2404px wide
1134px high

Adding a `max-width` on the whole content area could prevent these issues.

**Comment by jasmussen** [comment]
Noting for the record that I've written a little bit of CSS to override the themes page when Support Chat is open. Details here: https://github.com/Automattic/wp-calypso/pull/8320
