### ISSUE TITLE
[Bug]: Latest Blog Posts Block causes formatting issues below

### ISSUE THREAD

**Issue by Gilmoursa** [Automattic/wp-calypso#57006]
### Quick summary

When adding the latest blog posts block, the blocks below the latest blog posts block lack padding and have alignment issues. 

### Steps to reproduce

1. Create a page
2. Add the Latest Blog posts block
3. Add a block below it

### What you expected to happen

Expect the padding and alignment of the blocks to be consistent with other blocks
Screenshots:
1. adding an image block below the latest blog posts block:
https://d.pr/i/befyVP/g8g7TZ32PE

2. "+" to add a block is appearing on top of the latest blog posts block:
https://d.pr/i/5j7ZDs/nYQzkLC3sr

### What actually happened

Observe the editor screen or preview and you will see padding and alignment issues.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Use the "Blog Posts Block" instead

**Comment by inaikem** [comment]
I tested and replicated the bug in a Simple site on Chrome 94 on macOS 11.6. 

However, @cuemarie was not able to do so in Firefox 93 and macOS 11.5.2. See the screenshot below for the FF example:
&nbsp;

<img width="843" alt="Markup 2021-10-13 at 19 47 02" src="https://user-images.githubusercontent.com/66711744/137242214-55c62b89-6346-4248-9257-0e5a14ff1fd6.png">

&nbsp;

@Gilmoursa, regards the image links you shared above, please upload media directly into Github in future (if you're able to edit the above issue, or add them here as a comment, that would be appreciated!)


pbg9X-fWF-p2

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by alshakero** [comment]
I can't reproduce this. Can anyone share the theme this occurs under?

**Comment by jordesign** [comment]
I'n not able to recreate this any more on a Simple site in Chrome - closing the issue.
