### ISSUE TITLE
Jetpack Plans: Autoupdates toggle doesn't reflect plugin settings after configuration

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#5701]
1. Start the plugins install & configuration process at `/plugins/setup/$site`, for a site without Akismet
2. Akismet is installed and configured, but the "autoupdates" toggle is off.

![screen shot 2016-05-31 at 2 35 15 pm](https://cloud.githubusercontent.com/assets/541093/15686126/e5bfdad4-273c-11e6-8c68-e64974f34502.png)

3. Go to plugins list, Akismet's autoupdates are enabled.

We can fix the autoupdates toggle on this card, or remove it -- the toggle is informational only, even though it looks like you can disable it.

cc @rickybanister

**Comment by rickybanister** [comment]
I think we should fix the autoupdates toggle to make it functional. We should turn on autoupdates for the user if possible, but it's up to them whether to toggle it off. 

Essentially, this card should be functionally the same as its counterpart in `/plugins`.

**Comment by ryelle** [comment]
> I think we should fix the autoupdates toggle to make it functional.

I think that's harder than it sounds due to the Flux-vs-Redux implementation. I can take another look at this tomorrow morning, but that's why my first response was to just remove it.

**Comment by rickybanister** [comment]
As discussed, let's remove the toggles for now and instead indicate that the plugins have been activated in the compact notices.

**Comment by ryelle** [comment]
Do you meant to replace the "Successfully configured" message, or are we adding a new notice where the toggles were?

Toggles removed with message slightly tweaked:

![screen shot 2016-06-01 at 10 30 43 am](https://cloud.githubusercontent.com/assets/541093/15713315/f572f298-27e3-11e6-8959-3308e8d90d6e.png)

**Comment by rickybanister** [comment]
That message seems fine, no need to do anything else!

**Comment by johnHackworth** [comment]
I'm getting one of those child-without-key warnings:

![image](https://cloud.githubusercontent.com/assets/1554855/15739448/64ab64e8-28b0-11e6-9d71-3892e7f1e0df.png)


but otherwise, looks great!!
