### ISSUE TITLE
Launch Bar: Mobile styles need love.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57010]
The mobile styles for the Blogger Experience launch bar need to be fixed according to designs by @ollierozdarz .

See: EuqfSnWpfYx8fgiBlVmbuA-fi-2119%3A1113

| Current | Figma |
| --- | --- |
| <img width="415" alt="Screen Shot 2021-10-13 at 12 14 08 PM" src="https://user-images.githubusercontent.com/349751/137198854-11c620d3-0605-4aba-b46b-e82d276bf2ed.png"> | <img width="415" alt="Screen Shot 2021-10-13 at 12 16 39 PM" src="https://user-images.githubusercontent.com/349751/137198867-439055e5-2f49-4576-8c92-73b0a6abdaa2.png"> |

**Comment by andres-blanco** [comment]
@ollierozdarz I notice that the `Change theme` button on mobile reads `Change`. Is this expected or should it read `Theme` on mobile?

**Comment by kwight** [comment]
Completed in D68457-code.
