### ISSUE TITLE
Reader: Unseen post count does not decrease after reading posts

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#57015]
### Quick summary

After reading a post from a followed blog in Reader, the count of unread posts does not decrease.

### Steps to reproduce

1. Go to wordpress.com/read with at least one blog followed, and choose a feed to read.
2. Read posts: scroll through the reader, click on a post to open it and read it in full, etc.

### What you expected to happen

The number of unread posts in that feed/all feeds should go down.

### What actually happened

Reading the post does not mark the post as seen/gray it out, and the unread count on the left never goes down.

### Context

4364364-zen

All of the HEs who have worked on the ticket so far are able to replicate this while logged in as this user. One HE also noticed this on his account; I don't notice it with my own A8C account. (I also see that I have additional options for manually marking posts as seen. Are general users supposed to have those? If they are, the user in the ticket does not.)

I can replicate when I log into a non-A8C personal account, however—no controls for marking posts as seen, and my unread count doesn't go down when I read a post.

**Comment by Greatdane** [comment]
I can also replicate this on my personal account, but not on A8C Account.

A GIF showing this is here (can't post direct to GitHub due to file size: https://d.pr/i/FsHERs)

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by goblinartificer** [comment]
related incident in 4458062-zen

**Comment by arcangelini** [comment]
After some digging it looks like it boils down to the following function - https://github.com/Automattic/wp-calypso/blob/trunk/client/reader/get-helpers.js#L118

I am not familiar with the prop `isWPForTeamsItem` or what its use is, but that is returning _false_ which is causing the seen/unseen feature from being added to the `reader-post-card`. I am going to see where this prop is being set and try to understand why it is returning false.

**Comment by arcangelini** [comment]
**UPDATE**

I think the problem is not what we think it is. Originally the issue described is that the "unseen" feature of the reader is not functioning properly for non-A8C users. In actuality, the issue is that this feature as a whole should not be visible to non-A8C users in the reader at all. More details here - p9lV3a-1UT-p2

With that information I am going to see why the counts are appearing at all, and how we can get them disabled so they do not appear.

**Comment by yansern** [comment]
@unDemian and @aerych, any thoughts on this issue and this PR https://github.com/Automattic/wp-calypso/pull/58324 based on the prior discussions on p9lV3a-1UT-p2#comment-2717?

**Comment by aerych** [comment]
I'll defer to @unDemian as I'm a bit out of the loop these days.  cc @develric just in case there is anything relevant to y'all's interest here.

**Comment by unDemian** [comment]
Sorry for the late response, I was AFK, I commented on https://github.com/Automattic/wp-calypso/pull/58324

**Comment by arcangelini** [comment]
Fix has been published and everything should be resolved. Tested and verified.

To clarify, the only scenario that should show the UNSEEN count is for P2 and A12 sites. Otherwise, no count should show.
