### ISSUE TITLE
Preview Button Not Working in Gutenframed Editor on Atomic Sites

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#57011]
### Quick summary

Clicking the `Preview` button in the gutenframed ditor has no effect on Atomic sites.

### Steps to reproduce

1. Open the editor from Calypso on an Atomic site
2. Add content
3. Click on Preview

### What you expected to happen

To see the dropdown menu to select which view to preview, like this:

(this is how it functions on the same post when opened from wp-admin)

![preview](https://user-images.githubusercontent.com/42279181/137199009-efce33bd-b786-4963-aca6-ac9a6e6897ad.gif)

### What actually happened

When the post editor is opened from Calypso, nothing happens when the Preview button is clicked. It grays for a second and then go back to normal:

![nopreview](https://user-images.githubusercontent.com/42279181/137198661-b90fdb45-6522-49ed-a812-71e813e1a36a.gif)

### Context

I noticed it on my test site, and we had a user report here: p1634149464114200-slack-C03TY6J1A

There is a 400 error on the autosave call to the API showing in the console:

<img width="996" alt="autosave400" src="https://user-images.githubusercontent.com/42279181/137199432-2a0cd063-187b-42d3-a497-68ad3f1a125c.png">

### Simple, Atomic or both?

Atomic

### Severity

Impacts all atomic sites opening the editor from Calypso.

### Available workarounds?

Yes, easy to implement

### Workaround details

Open the editor from wp-admin.

**Comment by katiebethbrown** [comment]
Could be related to this merge possibly?

https://github.com/Automattic/wp-calypso/pull/56899

**Comment by yansern** [comment]
Given the way the cache timestamp of the WBE script is served, there only quick solution is to get Opers to purge the cache on `https://widgets.wp.com/wpcom-block-editor/calypso.editor.min.js?ver=20211013` and for HEs to ask users to hit Hard Refresh if their browser is loading the old script. Slack context: p1634155337063400/1634153350.061300-slack-C02FMH4G8

Right now, I haven't gotten any response from Opers yet. Slack context: p1634155968280900-slack-C02AVAR9B

If no Opers get to this, this issue will only last for the next 12+ hours.

**Comment by yansern** [comment]
Cache is now invalidated. For the next 12+ hours, if there are user reports coming in, ask them to hit Hard Refresh (CMD/CTRL+SHIFT+R).

**Comment by Gustavo-Hilario** [comment]
A few hours ago I had three users reporting similar issues on Simple sites and using Safari: 4374777-zen , 4374527-zen , and 4374592-zen .

I tried to reproduce on a test site, but I was unable to. I'm suggested trying clearing their browser cache or hit Hard Refresh.

**Comment by jackiejade** [comment]
32219576-hc Is another one that is still having this trouble. They are running Linux and using Brave as their browser, they have tried in Chrome as well. (https://www.whatsmybrowser.org/b/GIV6Y)

The user has tried:
- clearing cache
- looking in an incognito window
- restarting computer and router
- trying another browser
- hard refresh

I'm not able to reproduce, the preview is working fine on my end so I think it's something with their browser, but none of the typical "Tricks" are working.

**Comment by radtechgh** [comment]
27903460-HC, 4377092-ZD another with same issue, user can't preview pages as they edit them. Asking for browser info, and try hard refresh.

**Comment by metabreakr** [comment]
32223047-hc 
https://www.whatsmybrowser.org/b/ZM57C

It's a simple site. Could this be related to https://github.com/Automattic/wp-calypso/issues/54107?

User wishes to be kept updated.

**Comment by katiebethbrown** [comment]
@jackiejade  @Camaropilot  & @jonny-a8c   - This should be resolved. If you have users still seeing issues with preview a good next step might be asking them to check/confirm that third-party cookies are enabled correctly. There's an automated check here:

https://wordpress.com/support/third-party-cookies/

**Comment by metabreakr** [comment]
@katiebethbrown Does this also apply to simple sites?

**Comment by formosattic** [comment]
From my testing, Preview works ok on Simple sites. 

I'll go ahead an close this, but open if it happens again.
