### ISSUE TITLE
FSE beta: update support tools references to Legacy FSE

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#57024]
### Details

@synora pointed out the following:

"I do recall when a legacy FSE user came into chat, there was an FSE sticker next to their username, just like the “AT” sticker seen when an Atomic user comes into chat."

We should probably update these references to make it clear that they are related to Legacy FSE. Otherwise they can cause confusion when supporting the new FSE beta users.

**Comment by Addison-Stavlo** [comment]
I think 1196-gh-Automattic/happychat-hud may have solved this issue, unless there were more tools in need of updating?

**Comment by zaguiini** [comment]
> I think 1196-gh-Automattic/happychat-hud may have solved this issue, unless there were more tools in need of updating?

@vindl ☝️ is it true? Is this issue still valid? How can I test it?

**Comment by vindl** [comment]
Yes, the PR linked above resolves this issue. Thanks for pointing it out.
