### ISSUE TITLE
Site Editor Beta Flow: Missing Themes, Missing Screenshot

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#57027]
Issues:

- Blockbase has wrong screenshot in beta signup flow.
- Zoologist, Quadrat, Geologist missing from beta signup flow.

Blockbase should look like this:

![image](https://user-images.githubusercontent.com/545779/137344131-2a81dd3b-9994-4ae9-839d-d9e5c4d77ec0.png)

It looks like we may be using Blockbase as an alternative for the Blank Canvas theme. If we need a "Blank Canvas" theme in beta signup we should create a Block Theme version of Blank Canvas.

Missing themes in signup:

![image](https://user-images.githubusercontent.com/545779/137344355-99ce0977-075c-40b6-9ebb-1b0190700dbd.png)

These are the missing ones. :)

**Comment by mattwiebe** [comment]
The Blockbase screenshot was pulling from the empty `blockbasestarter` site so I just made us fall back to the demo site in D68445-code

**Comment by mattwiebe** [comment]
The above is already deployed, Zoologist's lack of `beta` was a result of missing a Showcase tag, and #56876 has fixed the rest
