### ISSUE TITLE
Site Editor Beta labelling in Calypso

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#57028]
Minor issues related to the Beta tag:

- Label is beta in sidebar and Beta in theme showcase.
- If I manually activate an FSE theme on Atomic I get a filled-in primary colour Beta tag BUT if I get myself into our Beta flow on Dotcom I get an outlined gold beta tag.

Label capitalization:

![image](https://user-images.githubusercontent.com/545779/137345028-926a1a92-74ac-488a-830f-825944fd494c.png)

Example of label colour in nav sidebar on manual FSE activation:

![image](https://user-images.githubusercontent.com/545779/137345172-70f602a8-ac5f-422b-98fc-8f415fa2a76f.png)

**Comment by vindl** [comment]
cc @onuro @jeyip

**Comment by jeyip** [comment]
I'm assuming we'd prefer the gold outline for all instances of the beta tag Onur?
