### ISSUE TITLE
GB 11.7: Font in editor changed and doesn't match front end

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#57043]
### Quick summary

The font used in the editor for sites with certain themes changed today so it no longer matches the front-end font. So far this is reported in:

* Hemingway Rewritten
* Nucleare
* The Journalist 
* Independent Publisher 2

### Steps to reproduce

1. Change theme on simple site to one of the themes listed
2. Edit post
3. View the font style

### What you expected to happen

I expected the font to match the default font set for the site

### What actually happened

The font was set to `serif`

### Context

I cannot confirm that it used to always match whatever font was selected for the site, but it definitely changed from a sans serif style font to a serif style font today.

4377593-zen

The front end display is not affected.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Hemingway Rewritten

### Workaround details

Go to `Preferences` in the editor (three dot menu) and turn of the `Use Theme Styles`.
![image](https://user-images.githubusercontent.com/15944096/137848957-4ca8ae63-6a8b-4bbe-a2f6-4d25a5d61793.png)

**Comment by Robertght** [comment]
Thank you for reporting this @ccwalburn ! 

What I'm experiencing right now is the font display a serif font in the editor, whereas the frontend displays the one set in the Customizer. Is that happening for you as well?

**Comment by ccwalburn** [comment]
Hey @Robertght Yes, that is what I see, too. @nickpagz discovered that you can bring back the system font by turning off the **Use theme styles** toggle on the Preferences screen in the editor (click the three dots to the right of the Jetpack icon, and then select **Preferences**)

**Comment by sajmes** [comment]
I encountered this here 4377459-zd-woothemes with theme The Journalist v1.9

I worked around it as suggested in the comment above.

**Comment by jordesign** [comment]
Update this issue to cover the various themes affected so far. If more are reported - please add the to the main issue (top comment).

**Comment by chad1008** [comment]
I was able to reproduce this in vanilla Gutenberg, specifically using Nucleare, so I've reported over in the wordpress/Gutenberg repo:
https://github.com/WordPress/gutenberg/issues/35730

**Comment by philnick206** [comment]
Have a report in #4384710-zen with the theme Independent Publisher 2

**Comment by Sandkorner** [comment]
31653255-HC Edin theme.

**Comment by ckmccoy2** [comment]
I'm not sure if this is exactly the same issue, this user was also having issues when trying to change the font color by highlighting the text, clicking on the down arrow in the menu that appears, selecting "Highlight" and then changing the color. It initially seems to work, but when the user previews, the front end just shows black text with yellow highlighting.

20616038-hc Theme: Nucleare

Similar thing was happening for this user: font color was not updating on front end via the same method
322655090-hc Theme: edin

**Comment by formosattic** [comment]
Updated initial post with workaround.

Go to `Preferences` in the editor (three dot menu) and turn of the `User Theme Styles`.
![image](https://user-images.githubusercontent.com/15944096/137848957-4ca8ae63-6a8b-4bbe-a2f6-4d25a5d61793.png)

Also looks like this was an issue that was previously closed, https://github.com/Automattic/themes/issues/3280

**Comment by Robertght** [comment]
Checking with Flow Patrol in Slack for now: p1634804533002100-slack-C029HCKPXP0

**Comment by cuemarie** [comment]
Another report: 4378950-zd-woothemes
Personal Plan, Theme: Rowling

The user's editor preferences are set to "Use theme styles" already, and the font still appears as `serif` in the editor.

Left a comment on [Multiple Themes: Editor font styles not loading in Gutenberg v9.9.3](https://github.com/Automattic/themes/issues/3280) as well - not sure exactly where is the best place to report.

**Comment by ccwalburn** [comment]
Hey @cuemarie ! The fix is to uncheck the "Use theme styles" checkbox.

**Comment by jordesign** [comment]
I'm consolidating the interaction references from https://github.com/Automattic/themes/issues/3280 to track everything in a single location. I'm just bringing over the reports from the last week (after that issue was re-opened).

It looks like a fix is being worked on in https://github.com/WordPress/gutenberg/issues/35730 so we'll keep an eye on that:

* 4382863-zd
* 4383731-zd
* 32272678-hc
* https://wordpress.com/forums/topic/very-small-font-size-again-in-the-editor/?view=all
* 4378950-zd

**Comment by jordesign** [comment]
Another report in 4386306-zen

**Comment by hideandgeek404** [comment]
Another report in 4419422-zen using the Ryu theme

**Comment by sajmes** [comment]
32585656-hc Rebalance theme.

**Comment by yashitamittal11** [comment]
Another one- #32955829-hc

**Comment by Greatdane** [comment]
@ccwalburn - I think this issue may be fixed - can I confirm the issue is no longer present for you?

**Comment by ccwalburn** [comment]
Hey @Greatdane I tested on _Hemingway Rewritten_ and _Rowling_ and the editor font does not match the font I selected in the Customizer. However, I don't have the option to access Preferences from the three dots in the editor anymore so I can't tell if the **Use Theme Styles** option is selected or not.

**Comment by Greatdane** [comment]
Strange! I still see the **Use Theme Styles** option on my test sites. I am going to close this for now then. If any more reports come up we can open. 

For the PA Triagers, I will not batch reply to this issue, as the most recent one is from Nov 2021, nearly 6 months ago. I think this is too old now to randomly reply to a user saying we fixed a bug 6 months later.

**Comment by ccwalburn** [comment]
I got another report on this and did some testing on my own and still see this issue so I am re-opening it.

I tested on a Simple site (Personal) and it occurs for both Karuna and Hew; but not for newer themes like Hever and Russell. The "Twenty" themes all seem to work, though...even the older ones like Twenty Eleven.

5675661-zen

**Comment by zdenys** [comment]
3274950-hc where I had to suggest turning off Theme styles to increase the font size in the Editor since it was too tiny and unstyled with their [Independent Publisher 2](https://wordpress.com/theme/independent-publisher-2/) theme and Gutenberg: v14.7.3 on Simple Site.

**Comment by ccwalburn** [comment]
Another instance here:
40432970-hc
Theme: Yuga
Atomic Site

**Comment by csabarakasz** [comment]
p1678005345692659-slack-C03TY6J1A

Atomic site
Theme: Libretto

**Comment by rw-ye** [comment]
5966311-zd-woothemes

Atomic site
Theme: Libretto

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Uncertain
- Tested on Atomic – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
- On WPcom Simple and AT sites, I could only replicate this on some older classic themes (Libretto, Independent Publisher 2, Cerauno, Twenty-Eleven) but not others (Yuga, Twenty Fifteen, Twenty Twenty, Twenty Twenty-One)
- Outside of WordPress.com, Libretto did not present the issue on Gutenberg 15.4.0, nor on 15.5.0.

Based on these tests, this doesn't look like a regression.  Closing this issue in favor of a new report

📌 ACTIONS
- Closed as no longer relevant (not a regression)
- Opened new report: https://github.com/Automattic/themes/issues/6999

📌 Message to Author
- I'll share the most recent reports of this on the new report.  HEs, please track any issues on the new report for clarity and troubleshooting. Thanks!

**Comment by cuemarie** [comment]
@ccwalburn I wasn't able to replicate the font issue on Yuga on an AT site:


https://user-images.githubusercontent.com/27249804/230177110-25d30cd1-afe2-48af-b0af-aea7e001a406.mov

I do see the issue is present on the customer's site still; I think that may need some plugin conflict testing next instead.  With that in mind, I did not share this specific report on the new issue I created.
