### ISSUE TITLE
Marketplace: New plugin cards

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#57067]
## Quick summary

We need to update the plugin cards' design based on the Marketplace new designs.

Figma designs:
Desktop: oU6nEIeiKSg8CayhEtgR6b-fi-6693%3A53309
Mobile: oU6nEIeiKSg8CayhEtgR6b-fi-6569%3A51677

Note: **Let's avoid adding any pricing details for the time being. Paid plugins will be part of Marketplace V1, while this is part of V0.5**

Plugins landing page:
![image](https://user-images.githubusercontent.com/11555574/137518069-3443a2d9-c47b-4277-8b99-21925ace01ac.png)

Search results page:
![image](https://user-images.githubusercontent.com/11555574/137517934-7987b2cb-e6ab-4ec4-a40a-2acb80dc41d7.png)

**Comment by cpapazoglou** [comment]
I would suggest creating a new variant `detailed` vs the current `minimal` for the `PluginsBrowserListElement` component. This way we can load any of two variants depending on the feature flag.
