### ISSUE TITLE
CoBlocks: Slowing down the Editor to almost a crawl

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#57060]
### Quick summary

The editor was almost unusable for the user when CoBlocks plugin was active. I wasn't able to reproduce the issue but they've sent the video together with their browser/OS. When we disabled the CoBlocks plugin, it started working for them without any issues.

### Steps to reproduce 

Only able to reproduce on user site:

1. Open any posts on user's site (see 4378694-zd-woothemes)
2. The editor is almost unusable when they start typing

### What you expected to happen

The block editor should be used normally, without any issues

### What actually happened

See 4378694-zd-woothemes for video.

They mentioned this happens to only in the Editor, not on live chat, and nowhere else. Just inside WordPress.com editor.

### Context

Chat: 32213277-hc
Ticket: 4378694-zd-woothemes

I am not able to reproduce this on my end, but this is their OS/Browser setup (one of them, they tried more, and the issue persisted until CoBlocks plugin was deactivated).

Browser: Firefox 93
Operating system: Ubuntu

### Operating System

Linux

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Atomic

### Severity

One

**Comment by formosattic** [comment]
Unable to reproduce as well.

Contacted user for more info.

**Comment by Robertght** [comment]
We haven't heard back in two weeks so I'm closing this one for now, but please open it again if needed.
