### ISSUE TITLE
Posts: javascript error loading /posts/:site with empty localstorage

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5708]
I'm getting this error in the console when loading the posts page with empty localstorage. I see this consistently.

![javascript error](https://cloudup.com/clYcwMNmMdh+)

FWIW, I do not see an error like this in the the reader or in `/pages/:site`.

cc @retrofox

**Comment by lancewillett** [comment]
Would this be a common occurrence or something an end user would run into without clearing local storage in dev console?

Closing for now since it seems developer-centric — feel free to re-open if you want to keep track of it for maintenance reasons.
