### ISSUE TITLE
Geologist Theme: Border at bottom of blog page splits onto two lines

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#57091]
### Quick summary

At the bottom of the Blog page on the Geologist demo, there's a border that splits onto two lines - is that a bug?

### Steps to reproduce

Visit Blog page on Geologist demo and look near the bottom of the page:

`https://geologistdemo.wordpress.com/blog/` 

### What you expected to happen

I'm not sure what's the intended display, but perhaps the border is meant to stay on one line?

### What actually happened

Border splits onto two lines:

![Blog_–_Geologist](https://user-images.githubusercontent.com/7662449/137644567-e7d3d04c-defa-40e5-a839-c07cbeb9bd1f.jpg)
.

### Context

Found while preparing test site for WordPress.com webinar

### Operating System

macOS

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Theme-specific issue?

Geologist

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

CSS could be used to hide the border for customers with a Premium plan or above

**Comment by jordesign** [comment]
I'm no longer able to reproduce this in the demo site, or in my own tests. It appears it has been resolved by prior development work.

Closing this ticket.
