### ISSUE TITLE
Paragraph: inline custom colors are being replaced with a yellow highlight 

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#57090]
### Quick summary

When editing a paragraph block and trying to set a different color to a specific text, the text and background colors are replaced with a yellow highlight.

### Steps to reproduce

1. Create or edit a blog post or page.
2. Add a paragraph with some sentences.
3. Select any words/sentences to highlight using the top toolbar menu.
4. Preview the page/post and the inline custom colors will be replaced with a yellow highlight.
5. If you save the changes and refresh the editor, you'll see the customization is gone there too.

**[Check this screencast!](https://d.pr/v/q8dl4c)**

### What you expected to happen

The color customization to be preserved either on the published page and in the editor.

### What actually happened

The customization is lost and replaced with a fixed yellow highlight in the editor and in the published page/post.

### Context

Customer report on 4378950-zen

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by vinnykaur** [comment]
I can replicate the same on my test site, Personal plan.

https://user-images.githubusercontent.com/49183855/137711584-04a1826b-5a8e-4676-ad0f-b957615d0aaa.mp4


Also, another user reported the same thing here in zd-4383306

**Comment by sbathompson-he** [comment]
Reported here as well: 30204700-hc

**Comment by marutim** [comment]
Another report here: 32274012-hc

**Comment by formosattic** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/57036

Here's a CSS workaround:

```
mark {
  color: unset !important;
  background-color: unset !important;
}
```

**Comment by annbingle** [comment]
Hi there! 

Got another report here 4386485-zd. I provided the CSS workaround for now.
