### ISSUE TITLE
CoBlocks Form block: Response not sent to email

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#57095]
### Quick summary

CoBlocks Form block doesn't send email notification when a reply is sent.

Just did a quick test, haven't had a chance to test on a .org site yet.
CoBlocks repo: https://github.com/godaddy-wordpress/coblocks

Note that the Form block from WordPress.com and CoBlocks are named the same, but can be differentiated by their icon.
![image](https://user-images.githubusercontent.com/15944096/137670544-9942e4af-d0ca-4d28-9902-9edd636ef6ae.png)

### Steps to reproduce

On an atomic site:

* Add a CoBlocks Form block
* Test the form by filling-it out
* Check mail inbox

### What you expected to happen

Get a email notification of form reply.

### What actually happened

No mail notification

### Context

4384412-zd-woothemes

### Simple, Atomic or both?

Atomic

### Available workarounds?

Yes, easy to implement

### Workaround details

Use Form block from WordPress.com, http://en.support.wordpress.com/wordpress-editor/blocks/form-block/

**Comment by Robertght** [comment]
I tested this and it worked out for me without an issue. 

@formosattic are there other details you can provide? I also checked the ticket and I don't see if the user has tried another email address in the process.(maybe I missed that)

**Comment by formosattic** [comment]
Thanks for checking @robertbpugh.
Not sure if this got fixed since, but I'm no longer able to reproduce the issue.
User hasn't followed-up with updates, so I'll go ahead and close.
