### ISSUE TITLE
Locale suggestion bar icon rendering is broken when using a RTL language in Safari

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#5710]
The icon is rendered at the top of the bar, rather than at the correct vertical position:

<img width="270" alt="screen shot 2016-05-31 at 17 57 39" src="https://cloud.githubusercontent.com/assets/418473/15690317/5bde2308-2759-11e6-851b-7c30826ae20b.png">

This doesn't happen in any of the other major browsers, and actually seems to be caused by a bug in Webkit, related to `padding-top` and `padding-left ` on SVG elements. I filed a bug report at their bug tracker: [Bug 158234](https://bugs.webkit.org/show_bug.cgi?id=158234)

While we wait for the fix, we might want to work around this by specifying a `1px` value for `padding-left` on RTL locales (and maybe a negative margin to compensate for it?).

Related PR: #5567

**Comment by coreh** [comment]
WebKit [Bug 158234](https://bugs.webkit.org/show_bug.cgi?id=158234) is now fixed, but we still need the workaround for now.

**Comment by hoverduck** [comment]
#bug-scrub

Closing, looks good now:

<img width="530" alt="screen shot 2016-10-17 at 3 27 25 pm" src="https://cloud.githubusercontent.com/assets/7233112/19452228/442e241e-947e-11e6-9d54-b874bd192810.png">
