### ISSUE TITLE
Font sizes in editor different from public page

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#57106]
### Quick summary

If you highlight some text in the editor and set the font to "standard" and then to "normal 16", it shows no change in the editor of the font size.
However, if you look at the page preview "normal 16" is much bigger than standard on the published page.

WHAT I FOUND:
Personal plan so no CSS option to fix.
Same occurs on a test site. 

### Steps to reproduce

If you highlight some text in the editor and set the font to "standard" and then to "normal 16", it shows no change in the editor of the font size.
However, if you look at the page preview "normal 16" is much bigger than standard on the published page.

WHAT I FOUND:
Personal plan so no CSS option to fix.
Same occurs on a test site. 

### What you expected to happen

Font in the editor to be the same as the public site

### What actually happened

Nothing changes in the editor but it does on the public site

### Context

4383891-zd

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Ryu theme

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
It looks like this one might be directly influenced by the theme and/or this one: 

https://github.com/WordPress/gutenberg/issues/35730

My results with Ryu:

![image](https://user-images.githubusercontent.com/6737345/138549870-0b0bb739-b448-4807-a394-006798231a07.png)


I also tested with Barnsbury and the results are these:

![image](https://user-images.githubusercontent.com/6737345/138549791-10afeb61-87c0-4676-9269-ec4c602ec7d6.png)

@richardmorrison was this issue discovered with the Theme styles being turned off or on?

![image](https://user-images.githubusercontent.com/6737345/138549894-bcb96403-cc3e-4904-8121-52e48de6b2bd.png)

**Comment by Robertght** [comment]
Closing this one due to inactivity
