### ISSUE TITLE
Marketplace: Support a minimal theme variant for the pagination component

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57100]
### What

Pagination component should support a minimal theme

### Why

The new Marketplace (oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A49151) is based on a white background with the pagination being more minimal

### How

Let's introduce a `variant` prop with `outlined`, `minimal` possible values

**Comment by WBerredo** [comment]
@JanaMW27 the minimal variant will use the selected theme colors or it will always use the black and gray colors?
