### ISSUE TITLE
Launch Bar: Correct the icons.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57123]
We're currently using Gridicons, but these don't match the Figma design:

<img width="795" alt="Screen Shot 2021-10-18 at 1 05 07 PM" src="https://user-images.githubusercontent.com/349751/137799287-5cfc0c4e-2f1f-462c-b217-b73e6a974cea.png">

Let's pull the SVG icons directly from Figma to fix them up.

**Comment by kwight** [comment]
D68593-code

**Comment by blackjackkent** [comment]
Diff open at D68593-code
