### ISSUE TITLE
[Bug]: Dyad 2 Mobile menu isn't responsive

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/wp-calypso#57120]
### Quick summary

Site: 24peluches.com

### Steps to reproduce

Open 24peluches.com on mobile, or chrome developer tools mobile simulation
Click mobile responsive hamburger menu.

### What you expected to happen

Expected menu to open

### What actually happened

Clicking the hamburger icon does nothing visibly.

### Context

zd-4386510

### Browser

Google Chrome/Chromium

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

One

**Comment by Greatdane** [comment]
I cannot reproduce this and it looks like the initial site issue was solved; 4405470-zd-woothemes

I suspect it was some CSS or AMP options causing the menu not to appear. Closing for now.
