### ISSUE TITLE
Launch Bar: Test our recommended themes.

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#57143]
### Details

A list of our recommended themes to check the Launch Bar against. We should probably check at across different viewport/screen sizes.

### Checklist

- [x] Blank Canvas
- [x] Zoologist
- [x] Quadrat
- [x] Geologist
- [x] Bantry
- [x] Laporte
- [x] Sigler
- [x] Antin
- [x] Bingely
- [x] Glen
- [x] Miller
- [x] Pollard
- [x] Paxton
- [x] Jones
- [x] Bradford
- [x] Baker
- [x] Twenty Twenty One
- [x] Seedlet
- [x] Twenty Twenty
- [x] Barnsbury
- [x] Rivington
- [x] Maywood
- [x] Shawburn
- [x] Alves
- [x] Exford
- [ ] Rockfield
- [x] Coutouire
- [x] Morden
- [x] Stow
- [x] Hever
- [x] Independent Publisher 2
- [x] Twenty Sixteen
- [x] Twenty Fifteen
- [x] Hemingway Rewritten
- [x] Ryu

### Related

https://github.com/Automattic/wp-calypso/issues/56769

**Comment by kwight** [comment]
@jordesign @provenself Can I leave this one to you two?

**Comment by jordesign** [comment]
Absolutely! I'll plan on trying to plough through these tomorrow (my time).

**Comment by jordesign** [comment]
A bit of an oddity in Rockfield with the fixed header.

https://user-images.githubusercontent.com/1842363/138196692-1e82ce8c-e2aa-43b2-a132-a2dbb6151034.mp4

**Comment by jordesign** [comment]
Apart from the oddity with Rockfield (noted above) the rest of our 'Recommended Themes' work well on Simple Sites across all viewports 👍

**Comment by kwight** [comment]
> Apart from the oddity with Rockfield (noted above) the rest of our 'Recommended Themes' work well on Simple Sites across all viewports.

Fantastic, thanks @jordesign for the testing! We'll track the Rockfield issue in https://github.com/Automattic/wp-calypso/issues/57230, so we can close this now. 👍
