### ISSUE TITLE
[Bug]: Highlight option for Text selection inside Paragraph block doesn't work

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#57148]
### Quick summary

When a user selects some text inside a paragraph block and tries to add color to the text via the Highlight option, it doesn't work. It shows the appropriate color in edit mode for the first time. If you update the page and reload the page in editing mode again it shows the default highlight color for the theme. In preview mode or publish mode it always shows the default highlight color(for most cases yellow).

### Steps to reproduce

1. Start editing a page.
2. Add a paragraph block.
3. Add some text inside that paragraph block and make a selection to change the text color for the selection.
![add_selection_text_color](https://d.pr/QXNdih+) **Image Link:** https://d.pr/QXNdih
4. Observe that the text color change is visible in edit mode.
![edit_mode_correct_text_color](https://d.pr/i/Sexe27+) **Image Link:** https://d.pr/i/Sexe27
5. Update the page and open that page in preview mode in a new tab.
6. Observe that the selected text has a default background color(by default it is yellow, for some theme configurations it can be different).
![default_background_in_preview_mode](https://d.pr/Jqa7QS+) **Image Link:** https://d.pr/Jqa7QS
7. Now go back to the edit page tab and reload that tab and observe that the text has the default background color like in the preview mode.

### What you expected to happen

Selected text color should be persistent and not overridden by the default text color 

### What actually happened

The color was getting removed from the selected part of the text.

### Context

4387822-zd-woothemes

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Other notes

It seems the inline style from the mark element is not getting saved somehow.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by fresatomica** [comment]
Reported by a user on the forums: https://wordpress.com/forums/topic/tertiary-text-colour-not-holding/?view=all

**Comment by supernovia** [comment]
Noting I ran into a similar case, where someone was upset that highlighted text did not highlight in their style in the reader. I'm wondering if highlight is the right way to go.

**Comment by cuemarie** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/57036 which has been solved.
