### ISSUE TITLE
FSE Site Editor: Layout Grid Mobile Preview

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#57158]
### Quick summary

Selecting the mobile preview in the Site Editor isn't stacking the elements of a Layout Grid. However, it appears as expected when you view the site's front end. Originally reported in p9bqti-1eo-p2#comment-2745 (also mentions tablet view) and I can still replicate this. 

https://user-images.githubusercontent.com/10015451/137959268-8e3b4189-3278-427a-9441-0cb265cc26b3.mp4

### Steps to reproduce

1. On an Atomic site, install and activate Seedlet (Blocks), the Gutenberg plugin, and make sure the Site Editor is enabled. 
2. Open the Site Editor and add a three-column Layout Grid. Each column should contain one Image and one Paragraph Block (add content). 
3. Save the changes and preview the content using the mobile preview option within the Site Editor

### What you expected to happen

For the Layout Grid's contents to be stacked for mobile during preview just like it on the front end. 

https://user-images.githubusercontent.com/10015451/137959354-99eb95b3-8864-4538-a326-04549fd50314.mp4

### What actually happened

Layout remains the same in preview though when viewing the site on a mobile device or viewport, the stacked contnet is seen. 

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

I used Seedlet Blocks but it's worth checking the other Universal Themes. 

### Other notes

The mobile preview for the Layout Grid is working just fine in the page/post editor. The trouble seems to just be with the Site Editor. 

https://user-images.githubusercontent.com/10015451/137959463-98eaf037-50ae-4d3d-9eec-a50c5d979dd9.mp4

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
Thank you @synora !

I know the Preview behavior is still being looked into. I'm flagging this for @Automattic/flow-patrol-create

**Comment by Robertght** [comment]
Also, tagging @Automattic/cylon for a second look.

**Comment by jeyip** [comment]
I can confirm this bug on **_both_** simple and atomic sites after following the "Steps to Reproduce" in google chrome.

**Comment by creativecoder** [comment]
I'm guessing this has to do with how the smaller preview is generated in the editor, since it works as expected in the editor (collapsing columns) if you resize the browser window itself. We'll likely need to address this in Gutenberg, as it doesn't appear to be WP.com specific.

**Comment by zaguiini** [comment]
Looks like the ["Layout Grid" block](https://github.com/automattic/block-experiments) is forcing a viewport definition inside the `Responsive Breakpoints` setting, which only affects preview.

The responsive breakpoints setting is _not_ applied to the live site.

We found out that we're ignoring the FSE preview device setting when it changes, thus causing the block not to react to that change. It only happens on the site editor.

More information and a fix to the problem: https://github.com/Automattic/block-experiments/pull/247
