### ISSUE TITLE
Launch Bar: The bar is hidden behind the Admin Bar when refreshing after a dismissal.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57156]
The dismissal only works for the current page load, so refreshing will bring the Launch Bar back into the DOM. However, for some reason, the page loads scrolled a little down, leaving the bar hidden behind the Admin Bar (and it's pretty jittery too).

![2021-10-19 09 43 57](https://user-images.githubusercontent.com/349751/137956750-d90a7531-2fb8-4386-a5d3-1f9673cc2c15.gif)

**Comment by andres-blanco** [comment]
D68684-code
