### ISSUE TITLE
Site Editor: Back to wp-admin instead of Calypso

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#57159]
### Quick summary

When leaving the Site Editor, it takes you back to wp-admin, rather than Calypso. 
Reported in p9bUq0-34e-p2#comment-5369

### Steps to reproduce

1. On an Atomic site, install and a Universal theme (I used Seedlet Blocks), the Gutenberg plugin, and make sure the Site Editor is enabled.
2. Check to make sure the "default view" is chosen in Screen Options. 
3. Enter the Site Editor, then leave it. 
4. Notice that you'll end up in wp-admin instead of Calypso. 

### What you expected to happen

To return back to Calypso.

### What actually happened

I end up in the Dashboard of wp-admin. 

### Context

https://user-images.githubusercontent.com/10015451/137961726-5161cfd4-6fda-48ec-a7f5-362c9ecac7b8.mp4

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by Addison-Stavlo** [comment]
this has since been resolved as far as I can tell. Please reopen if not the case.
