### ISSUE TITLE
Site Title Block within the FSE Site Editor: Editing Clarity 

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#57160]
### What

Trouble selecting and editing the site title. It isn’t clear when it’s selected and ready for me to type, and I couldn’t get the cursor where I wanted to easily

### Why

What's currently happening:

![Screen Capture on 2021-08-31 at 12-32-55](https://user-images.githubusercontent.com/1842363/138990527-3fb491f2-1c00-4075-84f4-29a0c800a434.gif)

Originally reported in p7DVsv-cAa-p2#comment-37482

**Comment by jordesign** [comment]
@synora - it looks like this video is of the WP Admin  redirect from another GH issue.

I've included this GIF from the testing report. Does that seem right?

![Screen Capture on 2021-08-31 at 12-32-55](https://user-images.githubusercontent.com/1842363/138990527-3fb491f2-1c00-4075-84f4-29a0c800a434.gif)

**Comment by synora** [comment]
Hi Jordan, 

🤦‍♀️ Yes yours is the correct video. Thanks for catching that. I was on a bug filing sprint that day. 😆

**Comment by creativecoder** [comment]
> Yes yours is the correct video.

Thanks for clarifying! I updated the issue description with the correct visual.

**Comment by jeyip** [comment]
I'm having a tougher time replicating this problem. I tried to do so in production on FSE beta enabled themes (Quadrat, Blockbase, and Zoologist). I also tried testing Mayland Blocks locally with no luck. 🤔

**Comment by creativecoder** [comment]
I've seen the cursor disappear intermittently like this, but it's hard to replicate (I usually use Firefox... not sure if it's browser specific or not). Also, I don't think this is specific to the Site Title block (though I could be wrong!)

**Comment by synora** [comment]
I agree, it does appear to be intermittent. I've tried again with Blockbase (using Chome) and I'm unable to replicate this.

**Comment by jeyip** [comment]
Since we can't replicate this reliably, how do we feel about closing this issue for now and reopening it reoccurs more often for folks?

@creativecoder @zaguiini @synora

**Comment by Addison-Stavlo** [comment]
It looks like this may have been fixed upstream, closing the issue as we cannot repro anymore. If it persists, please feel free to reopen!
