### ISSUE TITLE
[Bug]: Can't exit the Gutenberg on WPcom editor when viewing it on a mobile device 

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#57164]
### Quick summary

Curerntly if you try to edit the page or post via the mobile editor there is no way to exit and go back to the dashboard. 

You see
<img src="https://user-images.githubusercontent.com/115071/137967716-e0758928-3062-4958-9c96-ad4ffe4d47fd.png" width="300" />

### Steps to reproduce

Go to https://wordpress.com/page/examplesite.wordpress.com/5
On your mobile device and notice that you can't exit the editor. 
This doesn't happen on wp-admin since there is an admin bar present.

There is no admin bar and in that view.

### What you expected to happen

To be able to exit the editor.

### What actually happened

There is no way to exit this view. 

### Browser

iOS Safari

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

### Workaround details

You can use the browser back button or visit the site through the url.

**Comment by simison** [comment]
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/51162

Looks like that has fallen through a bit — let's get the regular mobile masterbar visible on editor at all times just like on .org, as discussed in that issue.
