### ISSUE TITLE
Masterbar: The bar is wrapping on mobile for some sites.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57167]
The Masterbar seems to be wrapping on mobile for some sites. This might be related to the FSE Beta rollout.

<img width="503" alt="Screen Shot 2021-10-19 at 12 56 46 PM" src="https://user-images.githubusercontent.com/349751/137981693-a97a8a0a-d780-461d-93c0-addd2c7878f3.png">

**Comment by sixhours** [comment]
Closing as a duplicate of #57352
