### ISSUE TITLE
Launch Bar: Move styles to `style.css`.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57162]
Because of testing, we've been using a separate `styles2021.css` file for the new Launch Bar styles. Once we've launched the update (see D68664-code), let's merge those styles to the one `style.css` stylesheet.

**Comment by andres-blanco** [comment]
Two diffs will be issued:
#### First diff
copy styles2021.css > styles.css
deploy styles.css (this file is not being used rn)
#### Second diff
switch the stylesheet (bump version number)

**Comment by andres-blanco** [comment]
First diff: D68770-code
Second diff: D68772-code

**Comment by kwight** [comment]
Done in the above diffs.
