### ISSUE TITLE
Page List Block Formatting/Alignment Settings

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#57163]
### What

This blocks lacks alignment and formatting. It would be nice to have more controls like alignment settings and color changes

### Why

This block seems like a close relative to the List Block-which offers a variety of settings, including the ability to adjust colors. 
<img width="969" alt="Screen Shot on 2021-10-19 at 13-54-43" src="https://user-images.githubusercontent.com/10015451/137964990-005562c9-b177-4625-9ce2-b063540b5e5c.png">

versus the Page List Block

<img width="1187" alt="Screen Shot on 2021-10-19 at 13-55-33" src="https://user-images.githubusercontent.com/10015451/137965076-1b148aa2-0bdf-47ec-84d2-0413374b4716.png">

More formatting/alignment options will give our users greater customization power when this block is on a post/page.

**Comment by creativecoder** [comment]
Note that these formatting options for the List block come from the `RichText` component (https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/rich-text) from the `@wordpress/block-editor` package.

We could propose adding some of these options to the Page List block in the Gutenberg plugin, though I think only a small subset of them make sense, like bold, italics, and underline. Adding inline code or strike-through options to a list of pages doesn't make much sense, in my opinion.

Also, the list of pages is generated dynamically, so it probably makes more sense to use block styles, such that any style options selected apply to all pages in the list. This would mean using the Block supports API, instead, for example: https://github.com/WordPress/gutenberg/blob/1b0ff7e8606cde2b71270f7744897eb2819eecd7/packages/block-library/src/post-title/block.json#L41

<img width="268" alt="image" src="https://user-images.githubusercontent.com/1699996/140396401-6918ad48-5717-44cc-8ff5-babdbbc70848.png">

**Comment by Addison-Stavlo** [comment]
There is a related core issue/request here - https://github.com/WordPress/gutenberg/issues/36537 

Cylon is not currently working towards this and I'm going to remove it from our board.

**Comment by zachspears** [comment]
This has popped back up in the PA Triage board, given the related core issue and that this functionality is no longer handled within wp-calypso, I am closing the issue for now.
