### ISSUE TITLE
Header and Footer Block in FSE Site Editor: Background Color Behavior

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#57174]
### Quick summary

Changing and saving the background color of the Footer Block within the Site Editor isn't appearing on the front end of the site. This is happening with Seedlet Blocks, Zoologist, Geologist, and potentially more.

### Steps to reproduce

"When editing the Footer Block, I selected a background color for the whole block. In the preview, it looks fine. I save the changes and then on the actual site the background is still white: https://d.pr/v/IaX6R8/E3sgjOeRIF

I also noticed if I reload the Site Editor, the Footer block goes back to how it was (without a background color)"

https://user-images.githubusercontent.com/10015451/138010112-1acf8638-7b0f-4a70-85cf-247499095dde.mp4

### What you expected to happen

The background color changes to appear on the site as expected. 

### What actually happened

The Footer Block's background color remains white. 

### Context

Original report in p9b1hy-1ST-p2#comment-4912

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Seedlet Blocks

### Reproducibility

Consistent

**Comment by Robertght** [comment]
Adding this one to @Automattic/cylon but please let me know if there's a better place for it.

**Comment by jeyip** [comment]
Neither the footer _nor_ header block persist changes to background color. Confirmed on simple sites for Geologist and Zoologist.

**Comment by Addison-Stavlo** [comment]
I just tested and was able to repro on my local Gutenberg with tt1-blocks.  Updating to the most recent `trunk` of Gutenberg resolved the issue.  I think this was a temporary regression and should be resolved when the next Gutenberg version lands on dotcom.

**Comment by jeyip** [comment]
~11.8.1 just landed and it appears that dotcom simple sites still suffer from this problem.~

I can confirm that the problem is fixed in the `11.9.0-rc.2` Gutenberg release. Let's close this when this version is released to all simple sites.

**Comment by jeyip** [comment]
**Status update:**

`11.9.1` is now on production, but the problem doesn't appear to be fixed. Would love a confidence check from someone else though. One thing to note is that the problem is not reproducible for core Gutenberg.

**Comment by Addison-Stavlo** [comment]
I am not able to repro on 11.9 or the 12.0-rc.

I change my header to a custom color, save, and reload the editor.  The custom color is there.
I check the front end, the custom color is now there as well.

**Comment by jeyip** [comment]
I circled back and tried it again. Not sure what I was doing wrong before, but I changed the background color on both the footer and header. I was mistaken -- the customizations  _do_ appear to be working 👍

Closing this ticket.
