### ISSUE TITLE
Refunds on charges with comma separator from SA

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#57181]
### Quick summary

When a refund is given for a user whose currency uses a comma marker (17,000 vs 17000) only the amount before the comma is refunded

This means that if a user has a currency with a comma, the HE can't just click refund to do a full refund, instead they have to manually remove the comma first. This can lead to inaccurate refunds and frustration for users. 

### Steps to reproduce

1. open SA for a user with a purchase whose value includes a comma
2. click refund to try and refund the whole amount
3. see that only amount before the comma is refunded

### What you expected to happen

If you aren't manually putting in a number, hitting refund should refund the whole purchase

### What actually happened

The comma was automatically inserted and only part of the refund was processed

### Context

32298063-hc

### Simple, Atomic or both?

Simple, Atomic

**Comment by Greatdane** [comment]
I have also just experienced this with a JPY refund. It only refunded the value before the comma. Had to go to PA to issue refund.

**Comment by DavidRothstein** [comment]
Closing since this is an internal issue (not Calypso related), being handled at pNPgK-5zM-p2.

It looks like it only happens in rare circumstances, but we do have an idea of how to reproduce it now.
