### ISSUE TITLE
Cart: Trash Icon Stopped Working

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#57180]
### Quick summary

The trash icon to remove an item on the cart stopped working.

### Steps to reproduce

1. Add an upgrade to the cart, a plan, a domain, etc
2. Go to a page where the Cart shows up, such as Upgrades > Plan for example
3. Click on the Cart icon and try to remove the upgrade from it

### What you expected to happen

To remove the upgrade, as it used to do.

### What actually happened

Nothing happens.

### Context

It's this trash icon here that stopped working:

![CartTrashIcon](https://user-images.githubusercontent.com/16104522/138079680-c91ca721-704a-4594-b9cb-78952da2a062.jpg)

The Console shows the following error when you click on the trash icon:

![CartTrashIconError](https://user-images.githubusercontent.com/16104522/138080473-7cf9fc8f-8236-4e8d-8de5-87111f148e9f.jpg)

**Comment by carinapilar** [comment]
Coincidentally, got now a user on 4389582-zd-woothemes reporting this.

**Comment by carinapilar** [comment]
Seems to be working again. 😌

**Comment by Robertght** [comment]
It works for me too so I'm going to close it for now, but please open it again if it becomes a problem.
