### ISSUE TITLE
Add hardcoded `short_description` in featured plugins

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57189]
The endpoint is `https://public-api.wordpress.com/wpcom/v2/plugins/featured endpoint`

### Why
The new marketplace designs have short descriptions in the plugin browser list (oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A49151). While wp.org results already contain it, the featured plugins list doesn't contain them yet in the response.

**Comment by WBerredo** [comment]
Code diff at D68744-code

**Comment by cpapazoglou** [comment]
Deployed r233613-wpcom
