### ISSUE TITLE
Editor: Paste as Text message is long across screen and x is obscured

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5718]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/ (Editor)
2. Click 'Paste as Text' button on editor toolbar

#### What I expected

Nicely formatted information message about how this works which ability to close it

#### What happened instead

The information is extremely wide, and the 'X' (dismiss) on the right looks like it is obscuring something else

#### Browser / OS version

Chrome Latest OSX 10.11.2, also tested Firefox latest which has same issue

#### Screenshot / Video

![screen shot 2016-06-01 at 10 23 53 am](https://cloud.githubusercontent.com/assets/128826/15694667/1800e38e-27e3-11e6-9bb8-70eb4bc27c93.png)

#dogfooding

**Comment by lancewillett** [comment]
That labeling was me testing Waffle.io integration — I dragged this issue around in the columns. :)
