### ISSUE TITLE
Launch Bar: Remove the Blog RC blog sticker setting.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57197]
Once the new Launch Bar is launched and unlikely to be reverted, let's clean up the Blog RC blog sticker setting for testing.

<img width="500" alt="Screen Shot 2021-10-20 at 8 45 31 AM" src="https://user-images.githubusercontent.com/349751/138126518-7ab9e871-dd25-42f4-8205-e35731316d54.png">

**Comment by andres-blanco** [comment]
D68768-code

**Comment by kwight** [comment]
Closed in D68768-code.
