### ISSUE TITLE
Template and Template Part Slug Updates Not Saving

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#57199]
### Quick summary

"Can’t edit the template slug from the Quick Edit link under my custom template part in WP Admin (but can edit the slug in the editor) However, when I changed the template slug name in the editor, the name didn’t save. It kept reverting to the slug name that the editor had chosen"

Originally reported at p9b1hy-1ST-p2#comment-4912 and this can still be replicated. 

### Steps to reproduce

1. With the Site Editor enabled, head to Appearance > Template Parts, hover over a template part and select "Quick Edit".
2. You'll notice there's no option to edit the URL slug there. 
3. Click on "Edit" to open the template part and attempt tp edit the URL slug from the template settings.
4. Click "Update" to save the changes. 
5. Go back to Appearance > Template Parts and you'll notice the slug changes were not saved. 

This also occurs with templates in Appearance > Templates which is seen in this video: 

https://user-images.githubusercontent.com/10015451/138133647-01df2c1c-f331-4b04-b40f-67e61363119c.mp4

### What you expected to happen

Expected the update URL slug to be seen.

### What actually happened

The URL slug reverts back to its default name.

### Context

I tested with Mayland Blocks but it's possible this happens with other Universal themes. 

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

**Comment by Addison-Stavlo** [comment]
Closing this issue as out of date, as this screen is no longer used for templates and template parts.
