### ISSUE TITLE
E2E: Add test for the admin bar presence when in editor

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#57190]
In https://github.com/Automattic/wp-calypso/issues/57164 we have a situation where the admin bar is not present on Simple sites for some reason. We should be catching that with our E2E tests.

/cc @worldomonation @dpasque

**Comment by worldomonation** [comment]
@WunderBart I believe there is an issue for this filed earlier than the one you're referencing.

**Comment by WunderBart** [comment]
> @WunderBart I believe there is an issue for this filed earlier than the one you're referencing.

Got it! 👉 https://github.com/Automattic/wp-calypso/issues/51162#issuecomment-948314423
