### ISSUE TITLE
Welcome Tour: Align the mobile app banner with the welcome tour

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#57192]
### Details

@poligilad-auto shared the idea of changing the current app banner into something more aligned with the welcome tour. See video below.

- More context in Slack: p1633639019052300-slack-C01VA0R5NKY
- More context on functionality in Slack: p1634738497202200-slack-C029WSAQMT9 (note that we still show app banner outside the editor)
- Some potential conflict with #57140 (fixes the logic for displaying the banner)
- @poligilad-auto suggested updating the media to be a GIF of using the app instead

https://user-images.githubusercontent.com/1705499/138111776-99bab644-d336-45a1-ac80-89537a885bd4.mov

### Checklist

- [ ] Ask for the relevant media files from @poligilad-auto 
- [ ] Show the mobile app banner as "part" of the tour, as in the design demo.
    - [ ] Proceed with the first slide (from previous) in the tour when the user clicks "No thanks".

Functionality **to be confirmed** (as currently implemented in #57140):
- [ ] In Calypso, show the mobile app banner immediately for all sites, including the ones that haven't been launched. 
- [ ] In page/post editor, show the banner [after 30 minutes following site creation](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wp-rest-wpcom-block-editor-nux-status-controller.php#L91-L92) and only if the Welcome Tour has been dismissed.

### Related

#57140, #54948

**Comment by enejb** [comment]
Would it be possible to just make the mobile modal just be part of the tour experience instead of adding it on top? 

It would also be great to have the content of the modal be mobile editor-specific. Since some of the images that we show to the user will not be that helpful since they show the desktop UI which is quite different from the mobile one.

**Comment by chriskmnds** [comment]
> Would it be possible to just make the mobile modal just be part of the tour experience instead of adding it on top?

Thanks for the comment @enejb! For the moment, we decided to not align the two this way. So we'll be keeping the banner as-is design-wise. There may be some logic changes on when the banner shows, etc. but will close this issue for now.

@poligilad-auto for more :-)
