### ISSUE TITLE
Launch Bar: 404 pages show an Edit button with an invalid link.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57202]
The Launch Bar still displays for 404 pages, but shouldn't have an Edit button. Currently, an Edit button is still rendered, and will link to `https://wordpress.com//<domain>/0` – which is invalid (and will be in turn redirected to My Home). Let's not render the Edit button if we don't have specific post or page data.

<img width="850" alt="Screen Shot 2021-10-20 at 10 55 22 AM" src="https://user-images.githubusercontent.com/349751/138145872-3513bfd4-49a9-4c76-b660-d8debd14a2c5.png">

**Comment by amustaque97** [comment]
@kwight, I'm able to reproduce this issue locally and would love to work on this issue.

**Comment by kwight** [comment]
@amustaque97 Unfortunately, the fix for this is server-side (and not in Calypso itself), but we appreciate the offer! Thanks for all your help with Calypso, I can see you've got a few things in already. 🚀

**Comment by kwight** [comment]
Fix at D68791-code (also for any archive view, like tag or category archives).

**Comment by kwight** [comment]
An alternative approach is to always have the button, but have a target fallback – I just think the UX will be confusing (why would that post open when viewing a tag's posts?..).

**Comment by kwight** [comment]
Fixed in D68791-code.
