### ISSUE TITLE
Empathy Flow Testing – What happens after creating new site with paid plan

### ISSUE THREAD

**Issue by hanananah** [Automattic/wp-calypso#57206]
### Quick summary

After purchasing a plan & domain during the new site creation process, we were taken to a list of all sites on the account. After selecting the new site, we were directed straight to creating a new page from scratch. It wasn't clear if a homepage had already been created automatically, and there was no context as to what page we were supposed to be creating, so we inadvertently created a duplicate homepage.

We feel this process may be a bit confusing to users, as they probably expect to be taken to their new site immediately after the site creation flow / plan purchase. A user may also be confused about being thrown directly into creating a new page. Perhaps being redirected into the existing homepage editor would be less confusing.

Note: Creating a new site on the Free plan took us directly to the site's Calypso dashboard, rather than the site list or new page editor.

### Steps to reproduce

1. Add new site
2. Proceed with new site creation flow
3. Select a paid plan
4. Checkout

### What you expected to happen

Be redirected to the Calypso dashboard for the new site

### What actually happened

Redirected to list of all sites on the account.

Clicking on any of the sites took us to create a new page from scratch without context of which pages already existed.

### Context

Empathy flow testing during Beaker's weekly team meeting

**Comment by Robertght** [comment]
Thank you for reporting this @hgwaltney !

I wasn't able to replicate this on my end as I was redirected to the Home page after the website creation process.

Could you share a video capture of the issue with us?

**Comment by hanananah** [comment]
Sorry for the delay! I just tested this again and after purchasing the plan and domain, I was immediately put into the homepage editor for the new site. It is clear this time that it's the homepage I'm editing, and the theme's homepage demo content is already there. I wonder if whatever happened during our team testing was just a fluke!

**Comment by Robertght** [comment]
I can't see other reports for now so I'm going to close this one but feel free to open it again.
