### ISSUE TITLE
FSE: Link to the site editor (instead of customizer) when appropriate in 'plans' section

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#57210]
### Details

As we were updating the theme changed modal on #57125, @creativecoder spotted an issue where the behavior will not match whenever someone upgrades the plan and has an FSE theme active.

Currently, it links the customer either to the Gutenberg front page editor or to the customizer URL, however:
- the copies are hardcoded with the word "customizer" in it, meaning it's not accounting for Gutenberg page editor, which looks like a leftover;
- it's not accounting for upgrades where an FSE theme is active.

![image](https://user-images.githubusercontent.com/26530524/138170458-110921d9-5289-4ec6-b04c-0c232337f418.png)

### Additional information
Component name: `PremiumPlanDetails`

### Checklist

- [ ] Rename selector from `getCustomizeOrEditFrontPageUrl` to something that makes more sense now that we are including `isFSEActive` to the arguments and decision making;
- [ ] Customize copy depending on the result of `customizeUrl`.

### Related

#57125

**Comment by Addison-Stavlo** [comment]
Are we still talking about the theme changed modal having inconsistencies in this state? Or a different section altogether?

In your screenshot, is that link on MyHome or somewhere else?

**Comment by creativecoder** [comment]
That screenshot is a features list on the checkout page that you see after you upgrade a plan, showing the features that come with the plan. You can also see it at `https://wordpress.com/plans/my-plan/{site}`

**Comment by Addison-Stavlo** [comment]
Ah yes, that makes sense.

Even with the new plans I am seeing this at `https://wordpress.com/plans/my-plan/{site}` : 

![Screen Shot 2022-05-25 at 12 33 46 PM](https://user-images.githubusercontent.com/28742426/170315043-a38d2759-2362-4cb6-b9ba-4637971f6a17.png)

Where we are surfacing the customizer for these actions when on an FSE theme.

**Comment by creativecoder** [comment]
Let's hold this for Anthony next week (can't find a Github handle?), I think it would be a good initial Calypso issue for onboarding.

**Comment by creativecoder** [comment]
cc @agrullon95

**Comment by creativecoder** [comment]
Resolved by https://github.com/Automattic/wp-calypso/pull/64423
