### ISSUE TITLE
Resonar: Menu Missing on Mobile (Atomic Only)

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#57215]
### Quick summary

On the mobile version of atomic sites with the Resonar theme, the menu is not visible.

### Steps to reproduce

1. Assign a primary menu to an atomic site with the Resonar theme
2. View the site on mobile

### What you expected to happen

I expected to see the menu toggle in the upper left corner, similar to how it looks on simple sites.

### What actually happened

The mobile menu is not showing on atomic sites at all.

### Context

User report in #32311266-hc. 

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Resonar

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

When adding this custom CSS, the menu returns:

```
/*  fix bug with menu missing on mobile */
.no-js .sidebar-toggle {
	display: block;
}
```

Not sure why it's set to display: none in the theme.

**Comment by edequalsawesome** [comment]
In doing some testing on this, it looks like it might be an issue with a CoBlocks update from yesterday -- disabling that resolved the mobile menu issue on a CSS request I was helping with: p1634836232367100-slack-wpcom-support

I'll need to do more digging to verify what's going on (although it's the second instance today where the `no-js` class wasn't removed correctly and CoBlocks was behind it), but so far it looks like disabling CoBlocks resolves the issue!

**Comment by JoshuaGoode** [comment]
Related to this p9F6qB-7AP-p2

**Comment by JoshuaGoode** [comment]
This issue also impacts other themes such as Luxury.

The CoBlocks team is aware and appears to be working on a revert and update deploy. 

Once the fix is published, users will need to wait for the CoBlocks plugin update that has the fix.  

Then, if deactivated, they can reactivate it again.

Re: https://github.com/godaddy-wordpress/coblocks/issues/2112

Internal notes:
 p9F6qB-7AP-p2
