### ISSUE TITLE
Should 'Add new WordPress' be changed to say site?

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#5722]
At the bottom of the menu of your sites is an encouragement to 'Add a new WordPress'. This feels weird in the use of the word WordPress as we don't use that anywhere else.

For example:

<img width="307" alt="2016-06-01 at 12 22" src="https://cloud.githubusercontent.com/assets/253067/15707993/c6ab5012-27f3-11e6-83b4-f64c327b6502.png">

I would recommend it should say 'Add a new site' or even 'Add a new WordPress site'. I would not suggest this if we set up the language like this in other places, but we don't. As a result this is a confusing use of the word WordPress.

**Comment by lancewillett** [comment]
I think the reason was to normalize WP.com versus WP.org and site versus blog and just have a new noun called "a WordPress."

**Comment by karmatosed** [comment]
I'd maybe suggest 'site' then as 'a WordPress' I'd suggest probably makes not much sense to users. That is unless there is some marketing/ campaign to set that as a term. Of course, maybe I'm assuming it doesn't and it does.

**Comment by meremagee** [comment]
On April 14, we moved the "add new {thing}" to the bottom of the menu bar. At this point, we changed the verbiage from "Add new WordPress" to "Add new site" for _new_ users (in [SidebarFooter](https://github.com/Automattic/wp-calypso/blob/b4c5d7cfc108b65606a01e7ef4a6b7509d161738/client/my-sites/sidebar/sidebar.jsx#L676)), but it looks like it was not implemented for existing users (in [SiteSelector](https://github.com/Automattic/wp-calypso/blob/b4c5d7cfc108b65606a01e7ef4a6b7509d161738/client/components/site-selector/index.jsx#L108)).

New user example (site count = 1), created today:
![](https://cloudup.com/cfbeOi9skiR+)

After much back and forth and deliberation, and much confusion among users unintentionally creating multiple sites when trying to create new posts or pages, I would like to see it changed to "Add New Site" everywhere. This is much clearer and still gives us a fairly agnostic way to frame website vs blog vs portfolio vs store.

**Comment by marekhrabe** [comment]
I would also be for usage of Site — either with "WordPress" in front of it or without. It just seems more clear to me. And it should be synced to all places, as @meremagee mentions.

**Comment by ianstewart** [comment]
> I would like to see it changed to "Add New Site" everywhere

❤️ 

Emphasis on the everywhere. cc @michaeldcain since I bug him about this. :)

**Comment by michaeldcain** [comment]
All blogs (squares) are sites (rectangles). I think users would understand that they'd be adding another site to their WordPress account. Let's just be consistent _everywhere_. #KeepWordPressProper

**Comment by michaeldcain** [comment]
If we're worried that users might not understand site vs. blog vs. WordPress, we're definitely not helping by calling it different things within our own UI.

**Comment by nylen** [comment]
This has bothered me for a while.  PR up at #7147.
