### ISSUE TITLE
Post editor showing incorrect styles in Apostrophe 2 theme

### ISSUE THREAD

**Issue by hideandgeek404** [Automattic/wp-calypso#57221]
### Quick summary

Following reports of the post editor not showing correctly I have now tested this myself. While in the editor the font is showing as a standard serif font unless changing the option in preferences to not use the site style which then ignores the site styling completely. This also affects some spacing and makes it difficult to add blocks.

### Steps to reproduce

1. Change to Apostrophe 2 theme
2. Add new post
3. Add paragraph block
4. type and you should notice that the font is not that of the site styles

### What you expected to happen

The editor should be mirroring the styles of the front end of the site but this has been tested with both the default site font and Montserrat being set in the Customizer > Fonts options.

### What actually happened

The font and some spacing in the post editor do not mirror the site.

### Context

Reported on 4386306-zen

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Apostrophe 2

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

1. Open post in editor
2. Click the three dots (option) in the top right
3. Click Preferences
4. Toggle "Use theme styles" to off

**Comment by jordesign** [comment]
Thanks for the report @hideandgeek404  - it looks like this is the same issue reported in https://github.com/Automattic/wp-calypso/issues/57043. There's a fix in Gutenberg which has been released - and we'll need to check when it lands in WPCOM.

I"ll add this interaction to the master list on that issue.
