### ISSUE TITLE
Launch Bar: Bar scrolls unpredictably with the Rockfield theme.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57230]
The Launch Bar scrolls unpredictably with the Rockfield theme. It may also have styling issues with the dismissal button.

Reported by @jordesign in https://github.com/Automattic/wp-calypso/issues/57143#issuecomment-948180928

https://user-images.githubusercontent.com/1842363/138196692-1e82ce8c-e2aa-43b2-a132-a2dbb6151034.mp4

**Comment by blackjackkent** [comment]
Kirk and I discussed this earlier - the issue is both extremely baffling and intermittent, making it hard to track down and identify a cause. I timeboxed some investigation on this but wasn't able to find anything concrete; I have however opened  D69064-code to address the button styling issue.

**Comment by kwight** [comment]
I think this might be a problem with all themes that have a fixed header (and may require a refactor of the launch bar to actually correct). 😬

**Comment by sixhours** [comment]
Since this hasn't been reported by users, closing as wontfix.
