### ISSUE TITLE
CoBlocks plugin causing menu bar to disappear

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#57232]
### Quick summary

Found an issue where when the CoBlocks plugin is activated the menu bar disappears. The menu items and logo do not show.

### Steps to reproduce

1. SU to the site `marinawalkerphotocom.wpcomstaging.com`
2. Activate the CoBlocks plugin
3. Check the live site and notice the menu bar has disappeared

### What you expected to happen

The menu bar should be present when the plugin is activated.

### What actually happened

When the plugin is activated, the menu bar disappears

### Simple/Atomic

Site is AT

### Other notes

Reported here 32321127-hc
Follow-up: 4394644-zd-woothemes

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Deactivating the CoBlocks causes the menu bar to appear.

**Comment by sharonlaker19** [comment]
I had a similar report today at 32132186-hc

**Comment by poeticabdul** [comment]
Reported here 31885067-hc
Follow-up: 4395048-zd-woothemes

**Comment by jp-imagines** [comment]
Another report in 30821939-hc.

**Comment by jp-imagines** [comment]
...and another in 31058725-hc.

**Comment by Robertght** [comment]
It appears this was fixed by the latest update of the Coblocks plugin:

https://github.com/godaddy-wordpress/coblocks/issues/2112

@poeticabdul @jp-imagines @sharonlaker19 can you check with your users please? :) 

I'm going to mark this as closed for now.

**Comment by jp-imagines** [comment]
Checked in with my two reports in 4403104-zen and 4403118-zen advising they can reactivate CoBlocks now. Will respond here if there's any further concerns about this.

**Comment by poeticabdul** [comment]
Checked in with my two reports here 4395048-zd-woothemes and 4394644-zd-woothemes

**Comment by sharonlaker19** [comment]
Updated mine too at 4406880-zen
