### ISSUE TITLE
Launch Bar: Action buttons are off-center.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57233]
The action buttons are slightly off-center, because we're using flexbox, and the My Home button is bigger than the dismissal button. Growing the dismissal button's space (without growing the button itself) should clean it up.

<img width="1324" alt="Screen Shot 2021-10-21 at 8 51 48 AM" src="https://user-images.githubusercontent.com/349751/138313226-650b4112-d76a-439b-9b29-a479603a952b.png">

**Comment by blackjackkent** [comment]
Addressed in D68994-code

**Comment by kwight** [comment]
Closed in D68994-code
