### ISSUE TITLE
Launch Bar: Mobile padding of My Home and dismissal are inconsistent.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57242]
The mobile padding of My Home and the dismissal button are inconsistent, with My Home having a 12px padding, and the dismiss button having 20px of padding. Let's verify according to Figma what the correct value is, and adjust.

<img width="420" alt="Screen Shot 2021-10-21 at 12 06 29 PM" src="https://user-images.githubusercontent.com/349751/138341750-3bd3d27f-7041-4f21-ba7a-f0e739f37fe7.png">

**Comment by blackjackkent** [comment]
Addressed in D68994-code

**Comment by kwight** [comment]
Closed in D68994-code
