### ISSUE TITLE
Videos UI: Determine the minimum functionality needed to manage courses.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57246]
If we want to avoid needing a dev with a sandbox to add and manage courses and their videos (and we want to!), we'll need a minimal asset management system that any Automattician can access and use. What are the basic operations we would need to support?

**Comment by kwight** [comment]
Idea for minimal operations:
* Add a video (with meta data like title, description).
* Add a course (with meta data).
* Add a video to a course.
* Sequence the videos in a course.
* Delete a video or course.

One option is to use a blog with Custom Post Types, the same way the Theme Showcase manages its themes. One question about the CPT approach: how would content get translated (if it's post content)?

**Comment by kwight** [comment]
Let's put up a post with initial findings and questions this sprint.

> how would content get translated (if it's post content)?
This can be done with Linguine (like in the Theme Showcase).

We'll focus first on a hardcoded array in the library, and do more courses management (likely with a CPT) at a later point.

**Comment by kwight** [comment]
@provenself I've added you as an admin to wpcourses.com, an existing course management system we may be able to use – could I get you to take a quick look through there, maybe add a test course, and see if there's enough for what we need? A key thing to check is if we can publish a course there for free (no registration, etc).

**Comment by provenself** [comment]
@kwight on it! will dig in this week.

**Comment by kwight** [comment]
We looked at re-using WP Courses' back-end, but felt that a standalone version particular to this project would be more appropriate. @provenself remind me if I've missed anything.

**Comment by provenself** [comment]
> We looked at re-using WP Courses' back-end, but felt that a standalone version particular to this project would be more appropriate. @provenself remind me if I've missed anything.

That's right! Courses back-end was far too big/templated for what we needed.

**Comment by kwight** [comment]
We've determined that we need a non-dev to be able to:

* upload a video,
* create, update, sequence, and delete a course,
* add videos to courses.
