### ISSUE TITLE
Launch Bar: Adapt the Edit button to Full Site Editing.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57243]
Full Site Editing (FSE) is currently in a limited release beta on WP.com, and allows users to edit more than just content in the editor. We're in the process of removing the Launch Bar Edit button if the user isn't on a clear singular view (#57202), but let's bring it back as a potential FSE-related button once the feature is more rolled out.

See: pdgK6S-gb-p2

**Comment by kwight** [comment]
cc/ @ollierozdarz @ianstewart @jordesign to kick off discussion of what the Edit button could link to in what contexts.

**Comment by sixhours** [comment]
I'm calling this a wontfix since it's been well over a year since this was opened, and the chances of someone seeing the edit button on a 404 page on an unlaunched site are probably small for most users. Feel free to reopen if you disagree!
