### ISSUE TITLE
[Vimeo Block] Private/Paywalled/Live Vimeo Videos do not embed. 

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#57257]
### Quick summary

Vimeo videos that have a secondary slash in the URL do not work on WordPress.com using the Vimeo block, instead a blank section is shown.
An example of a live video would be https://vimeo.com/635643256/b6a59a4d1e
An example of a video to purchase would be https://vimeo.com/555942796/e712a2e45d

Interestingly, for the on-demand videos, removing the secondary slash from the URL and embedding seems to fix the issues, but not for live videos.
(on the example above, changing the URL from `https://vimeo.com/555942796/e712a2e45d` to `https://vimeo.com/555942796` will make the embed work)

See p9F6qB-7AN-p2 and 4394244-zd-woothemes

### Steps to reproduce

1. Embed a Private/Paywalled/Live Vimeo video on a blog post/page.
2. The video will show up in the editor. 
3. Publish/Preview the page.
4. The Video will now show up on the live site. 

### What you expected to happen

I expect the video th work on the live site. 

### What actually happened

Video does not display on live site.

HTML shows the following;
```
<div class="wp-block-embed__wrapper">
<!-- vimeo error: not a vimeo video -->
</div>
```

### Context

User Report; 4394244-zd-woothemes

### Reproducibility

Consistent

### Severity

All

### Workaround details

Partial workaround by removing the second slash from the URL. Does not always work.

**Comment by Greatdane** [comment]
As a further note, this does work on self-hosted sites (well, the second video says it cannot be played), so seems to be a WordPress.com issue. 

See: 
<img width="759" alt="Markup 2021-10-22 at 14 13 05" src="https://user-images.githubusercontent.com/5075840/138396864-f7465007-e14e-44fb-baa3-4bfd05b81b0a.png">

**Comment by filipanoscampos** [comment]
This user came back to chat today to demand a solution: 32318926-hc
In the meantime, I also tested all this on one of my test sites and can confirm the embed is not working and that I can see an error in the Inspector saying:

![Screenshot 2021-10-22 at 11 58 43](https://user-images.githubusercontent.com/2540430/138443031-e94aab76-8849-439c-b78d-9a6371ce66fc.png)

The workaround did not solve the issue, either.

**Comment by Gustavo-Hilario** [comment]
The same above user contacted us again on 4396874-zen . I have made some tests, but I couldn't reproduce the issue on **Simple sites**.

**Comment by filipanoscampos** [comment]
The user came back to chat, 32341687-hc
They are now using iframe to temporarily solve their issue, but are really insisting on receiving an update on this ASAP.
Thank you!

**Comment by JoshuaGoode** [comment]
For now, the original user is using Custom HTML / iframe embeds as a workaround.

I asked the user to keep additional communication on the ticket but noted it might be marked as solved and we would follow up with them once we have an update.

4394244-zd-woothemes

**Comment by Greatdane** [comment]
Noting that this seems to be an Atomic only issue. It is working on Simple sites.

**Comment by JoshuaGoode** [comment]
This appears to be a conflict with the Jetpack shortcodes module.

If we deactivate the shortcodes module, the videos should load as expected.

**Comment by JoshuaGoode** [comment]
This actually appears to be this: https://github.com/Automattic/jetpack/issues/10529

Deactivating the Jetpack Shortcodes module or adjusting the link, until it works, are workarounds.

**Comment by jeherve** [comment]
> This actually appears to be this: Automattic/jetpack#10529

👍

Closing this issue as duplicate.
