### ISSUE TITLE
Atomic Downgrade: Warn about defaulting Atomic reverted sites to private

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#57278]
As of https://github.com/Automattic/wp-calypso/issues/55452 (more context in p7DVsv-cXE-p2), Atomic reverted sites are made private by default.

Uses are not currently aware about that change before we perform the Atomic revert, so it'd be good if we can include a warning message in both the self-service cancellation flow (possibly under the "Proceed with caution" step) and the email notice sent due to plan expiry.

**Comment by dsas** [comment]
Possibly also in the "expiration email" for when we revert due to plan expiry.

**Comment by mmtr** [comment]
> Possibly also in the "expiration email" for when we revert due to plan expiry.

Right, don't know why I wrongly assumed we were already warning users in those emails. Updated the issue to reflect that we need to include a warning in both cases.

**Comment by spraveenitpro** [comment]
Hi @mmtr I would like to work on this, Hope that is fine. : )

**Comment by mmtr** [comment]
@spraveenitpro sure thing! This will need changes in both Calypso and the emails, do you want to work on both them? Are you planning to work on this immediately? Let us know if you need any help!

**Comment by DustyReagan** [comment]
I had a go at this. The plan expiring email update is here D82674-code and the Calypso update here [#64674](https://github.com/Automattic/wp-calypso/pull/64674).
