### ISSUE TITLE
Email Notifications Not Received When Using Yahoo Mail to Receive Contact Form Responses

### ISSUE THREAD

**Issue by allanftd** [Automattic/wp-calypso#57277]
### Quick summary

When setting up a contact form on an Atomic site, the form submission notifications will not be received if a Yahoo email address is used. If other email address like Gmail is used, notifications will be received. I was able to reproduce on my own test AT site. Junk/Spam folders were also checked but to no avail.
Issue only happens on AT sites.

### Steps to reproduce

1. Add an online form block to a page
2. Use Yahoo email address in "Email address to send to" under Form Settings (see [screenshot](https://d.pr/i/w9Q1SW))
3. Save the page.
4. Go to the live page and use the form. Submit an entry.
5. Yahoo email address will not receive any notification.
6. Repeat steps 2 to 4 but this time change Yahoo email address to a different provider like Gmail
7. Gmail address will receive the notification this time.

### What you expected to happen

Receive the email notification that a new form submission has been received when using Yahoo email address.

### What actually happened

No email notifications that a new form submission were received when using Yahoo email address.

### Context

4394731-zen

### Operating System

Windows, macOS

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Other notes

Happens only on AT sites. Simple sites are not affected.

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Use non-Yahoo email address like Gmail which works.

**Comment by Robertght** [comment]
Thank you for reporting this @devNigel !

**Comment by dpasque** [comment]
Marking High priority if this affects all of yahoo email, but if it only affects one or a subset, the priority could be lowered.

**Comment by sixhours** [comment]
~~I can reproduce this on a WordPress.com Simple site with a Premium subscription as well.~~

I suspect this is related to intentional throttling on Yahoo's end (MailPoet is experiencing similar issues, tracked here: pcD9cT-jv-p2)

I'm going to investigate our email logs to confirm the error is not on our end.

**Comment by sixhours** [comment]
I do eventually get the results from the contact form on my Atomic site, but they go to Spam, and with a couple hours' delay: 
<img width="854" alt="Screen Shot 2021-11-15 at 8 09 18 PM" src="https://user-images.githubusercontent.com/2124984/142001081-05d6421e-b679-4716-9e8d-f35dde95eff5.png">
<img width="857" alt="Screen Shot 2021-11-16 at 9 13 21 AM" src="https://user-images.githubusercontent.com/2124984/142001487-a3c9ffb0-bdd3-413c-b1ad-7a3e2a866c04.png">

Our logs show those emails are successfully sent, so unfortunately this isn't something we can fix. The best workaround is to recommend a different mail provider like Google, or to make sure to check the Spam folder.

**Comment by formosattic** [comment]
+1 5288416-zd-woothemes
Suggested using non Yahoo address.
