### ISSUE TITLE
Twenty Fifteen Download link is broken in Theme Info

### ISSUE THREAD

**Issue by kimerlin81** [Automattic/wp-calypso#57296]
### Quick summary

When the Download button at the bottom of the Twenty Fifteen Theme info page is clicked, all users see the 401 - page cannot be found error.

Download button links to https://public-api.wordpress.com/rest/v1/themes/download/twentyfifteen.zip

Workaround - download theme from https://wordpress.org/themes/twentyfifteen/

### Steps to reproduce

1. Start at the themes showcase of any site
Example: https://wordpress.com/theme/twentyfifteen/lspenceatomic.wpcomstaging.com
2. Click the Info button
3. Scroll to the bottom of the page and click the "Download" button that appears next to:
"This theme is available for download to be used on your WordPress self-hosted installation."

### What you expected to happen

I expect the Twenty Fifteen theme zip file to start downloading

### What actually happened

I receive a 401 error:
This site can’t be reached. The webpage at https://public-api.wordpress.com/rest/v1/themes/download/twentyfifteen.zip might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

### Context

I can reproduce this, as well as others.
Link just needs to be updated on the info page.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Twenty Fifteen

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

download theme from https://wordpress.org/themes/twentyfifteen/

**Comment by Robertght** [comment]
I asked in p1635324360196300-slack-C029FM1EH for a double check on this one as I couldn't find the place to adjust that link

**Comment by Robertght** [comment]
Fixed by @scruffian in the slack thread above.
