### ISSUE TITLE
Jetpack Plans: Error message is unhelpful when we can't install plugins

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#5729]
1. Try to run the plugins install & config on a Jetpack site where we can't install plugins (ex: a multisite subsite): `/plugins/setup/$site`
2. See this screen, and be sad, because you don't know how to get the things you've just paid for.

![](https://cldup.com/_pL6pb38IL.png)

My suggestion:

![](https://cldup.com/ZwxoZ7UXf0.png)

cc @rickybanister

**Comment by rickybanister** [comment]
Could we detect this on the receipt screen? Or perhaps try to install and redirect them back to the receipt screen, swapping the primary button for the manual instructions link? That screen has helpful links to get support on it, etc. (while we're planning to have support be available everywhere, we haven't done so yet).

**Comment by ryelle** [comment]
Good idea, I think we _can_ detect this on the receipt. So drop "You can also perform a manual installation by following these instructions." and use that link for the button?

**Comment by rickybanister** [comment]
Yup, that should do it!

**Comment by ryelle** [comment]
Hmm, the rest of the text is misleading now:

> We are about to install Akismet and VaultPress for your site, which will automatically protect your site from spam and data loss. If you have any questions along the way, we're here to help!
>
> [Set up your plan]

We aren't about to install anything, and we know it. Maybe leaving the old receipt content here makes sense:

> **Set up your VaultPress and Akismet accounts**
> We emailed you at %(email)s with information for setting up Akismet and VaultPress on your site. Follow the instructions in the email to get started.

Or writing new copy (open to better suggestions):

> You can now install Akismet and VaultPress, which will automatically protect your site from spam and data loss. If you have any questions along the way, we're here to help!
>
> [Installation Instructions]

**Comment by rickybanister** [comment]
The latter suggestion looks good to me!
