### ISSUE TITLE
Image blocks with www links append the site's base URL to the link.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#57305]
### Quick summary

If you add a link to an image in Gutenberg with the www subdomain, the link will appear on the live site with the base URL of the WordPress site appended to the link address.

### Steps to reproduce

1. Create an image block in the editor. Link it as so (www.speedtest.net is used as an example here):
<img width="763" alt="Image Link Bug Simple Link Cap" src="https://user-images.githubusercontent.com/49131029/138613130-b96987e5-5158-413f-9a72-568cf6a5c2eb.png">
2. Go into preview or the live site, and hover over the image:
<img width="340" alt="Link Bug end result" src="https://user-images.githubusercontent.com/49131029/138613151-58ca8d48-6cfb-4380-b274-982f6275aa9c.png">
3. Clicking the link will result in a 404 error on the wordpress site, as it tries to go to: https://wordpress-site/www.speedtest.net

### What you expected to happen

The link should follow the same behaviour as links added in paragraph blocks: The www. site should be linked correctly.

### What actually happened

The link 404's as the base wordpress site URL is appended to the beginning of the link.

### Context

A user discovered this behaviour here: 4024683-hc

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Removing the link from the image block, and then re-adding it as https://www.link.com will work.

Removing the image block and re-adding it may be necessary.

**Comment by Robertght** [comment]
Thank you for reporting this @KirkwallDay !

It looks like this is Gutenberg-related as I was able to replicate it on a self-hosted environment as well: 

https://github.com/WordPress/gutenberg/issues/35910

**Comment by dpasque** [comment]
This issue is tracking an issue in another repository. All +1's of end-user reports should be done on this issue, while any discussion related to the issue itself and its fix should be done on the issue in the outside repository.

**Comment by yansern** [comment]
This is default browser behaviour. WP or Gutenberg just outputs the link as-is.

You can test this on all other browsers (tested on Chrome, Firefox & Safari).
https://jsbin.com/yeroretoma/edit?html,output

The user should add protocols to the image link. Marking this as Won't Fix.
