### ISSUE TITLE
Milestone notification says "You've made 0 posts on ...." when account language is set to Japanese

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#57302]
### Quick summary

When account interface language is set to Japanese, a milestone notification says "You've made 0 posts on ...." no matter how many posts a user publishes. 

### Steps to reproduce

1. Go to https://wordpress.com/me/account and select Japanese for interface language.
2. Create a new site and publish a new post.
3. Click on a bell icon on the top-right to check notifications.

### What you expected to happen

See a milestone notification that says `"SITE_TITLE"で1件目の投稿を公開しました。`(that means "You've made your first post on ..." in English).

![Screen Shot on 2021-10-24 at 13:29:06](https://user-images.githubusercontent.com/32432463/138581311-d5adc7e3-05a6-4aa6-8244-df6a34832873.png)

### What actually happened

See a milestone notification that says `"SITE_TITLE"で0件目の投稿を公開しました。`(that means "You've made 0 posts on ...." in English), which makes no sense.

![Screen Shot on 2021-10-24 at 13:30:47](https://user-images.githubusercontent.com/32432463/138581320-006692ef-37ca-4660-aea1-6cba6c0adbee.png)

### Other notes

I checked it with some other languages(Chinese, Korean, Italian and Spanish) but couldn't replicate the issue. So it seems this is just for Japanese.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by jordesign** [comment]
Scrubbed and can confirm this behaviour

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by alshakero** [comment]
It seems this is a bug in the [translation of the string](https://translate.wordpress.com/projects/wpcom/ja/default?filters%5Bterm%5D=+made+your+first+post+on). The translation is the same for “your first post”, and “your nth post”, causing the translation to look like “You posted your 0th post” when users post their first post.

**Comment by emilyaudela** [comment]
The translation was using the wrong placeholder variable (`%1$d` instead of `%1$s`) which was causing it to break. I have updated the translation with the correct placeholder and it looks like it's fixed now. 

<img width="373" alt="Screen Shot 2021-11-08 at 6 01 59 PM" src="https://user-images.githubusercontent.com/36699353/140785875-069999b2-797a-4635-a6aa-92bbaf4159c6.png">
