### ISSUE TITLE
Document flow for adding new product to the marketplace endpoint

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57318]

**Comment by gavande1** [comment]
Document created/update at PCYsg-CJy-p2

**Comment by cpapazoglou** [comment]
I have added "Dotcom Marketplace" as the parent page and changed the template to "Sidebar with subpages". 

<img width="292" alt="SS 2021-11-01 at 15 37 10" src="https://user-images.githubusercontent.com/12430020/139680679-67e6bb3f-0d3e-42eb-b574-cfbd5ac6b7e1.png">

Thanks @gavande1 !
