### ISSUE TITLE
[Bug]: No error message when leaving the "Cardholder name" field blank when adding a credit card

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#57323]
### Quick summary

The "Cardholder name" field on the credit card form is required, but when you leave it blank the form submission just hangs.

### Steps to reproduce

1. Go to add a credit card anywhere (for example https://wordpress.com/me/purchases/add-payment-method), including during checkout.
2. Fill it in with test data (you can use https://stripe.com/docs/testing to get test credit cards, which actually should work if you're in store sandbox mode) but leave the "Cardholder name" field blank.
3. Submit the form.

### What you expected to happen

Some kind of error message about the cardholder name field being required.

### What actually happened

The form submission hangs and nothing happens.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

People can probably figure the issue out on their own, even without an error message.  However, there is no real indication anywhere that the field is required.

**Comment by tameryldz** [comment]
> ### Hızlı özet
> Kredi kartı formundaki "Kart sahibi adı" alanı zorunludur, ancak boş bıraktığınızda form gönderimi askıda kalıyor.
> 
> ### Çoğaltma adımları
> 1. Ödeme sırasında da dahil olmak üzere herhangi bir yere (örneğin https://wordpress.com/me/purchases/add-payment-method ) bir kredi kartı eklemek için gidin .
> 2. Test verileriyle doldurun ( test kredi kartlarını almak için [https://stripe.com/docs/testing adresini](https://stripe.com/docs/testing) kullanabilirsiniz , bu aslında mağaza sanal alan modundaysanız çalışması gerekir) ancak "Kart sahibi adı" alanını boş bırakın.
> 3. Formu gönderin.
> 
> ### Ne olmasını bekliyordun
> Gerekli olan kart sahibi adı alanı hakkında bir tür hata mesajı.
> 
> ### Gerçekte ne oldu
> Form gönderimi askıda kalıyor ve hiçbir şey olmuyor.
> 
> ### Bağlam
> _Cevap yok_
> 
> ### Tarayıcı
> _Cevap yok_
> 
> ### Basit/Atomik
> _Cevap yok_
> 
> ### Diğer notlar
> _Cevap yok_
> 
> ### Yeniden üretilebilirlik
> Tutarlı
> 
> ### önem
> Bazıları (< %50)
> 
> ### Kullanılabilir geçici çözümler?
> Evet, uygulaması kolay
> 
> ### Geçici çözüm ayrıntıları
> İnsanlar muhtemelen bir hata mesajı olmadan bile sorunu kendi başlarına çözebilirler. Ancak, alanın gerekli olduğuna dair hiçbir yerde gerçek bir gösterge yoktur.

**Comment by jjchrisdiehl** [comment]
@DavidRothstein I cannot reproduce this issue from either the Add Payment Method page or the Checkout card form. When I leave the Cardholder Name field blank, then hit submit, in both cases the Cardholder Name field turns red and has an error message.

It looks like this specific check is run, though it has technically been around for two years https://github.com/Automattic/wp-calypso/blob/53d3a6a3dc731479e57b63e9b0fb46760ef93848/client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.tsx#L54

Are you still able to reproduce this on your end?

Maybe @sirbrillig knows a bit more about this validation.

Example 
![image](https://user-images.githubusercontent.com/16580129/176310943-bdc525d6-9f92-4bae-bd17-da2ac2dbcf5f.png)

**Comment by sirbrillig** [comment]
Yes, the cardholder name field is supposed to have an error displayed by [this code](https://github.com/Automattic/wp-calypso/blob/53d3a6a3dc731479e57b63e9b0fb46760ef93848/client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.tsx#L141) (inside the `isCreditCardFormValid()` check that Chris linked to above). 

I think this may have been fixed by https://github.com/Automattic/wp-calypso/pull/60854 so I'm going to mark it as resolved.
