### ISSUE TITLE
Videos UI: Add a new card to the My Home carousel for our MVP.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57326]
We need to add a new card to the carousel in My Home, from which the Video UI modal will pop up. We can conveniently use the existing "courses" visual, and the card should only display for English language users (`EN`, `EN-GB`).

<img width="1668" alt="Screen Shot 2021-10-26 at 2 55 36 pm" src="https://user-images.githubusercontent.com/349751/138904892-a821cd44-addf-48cb-bbed-24329973ebbe.png">

**Comment by kwight** [comment]
@provenself Can we ask you to come up with what the copy would be for these three text fragments please?

**Comment by kwight** [comment]
@blackjackkent we can use this PR as our testing gate: being the only UI linking to the Videos UI, people can test the feature with this PR's calypso.live link.

**Comment by kwight** [comment]
I've updated the screenshot to match recent work by @ollierozdarz 🚀

Ollie, I'm assuming the card is to be part of the existing My Home carousel at that location?

<img width="730" alt="Screen Shot 2021-10-25 at 10 27 55 AM" src="https://user-images.githubusercontent.com/349751/138905043-34dcb847-e67d-4f37-b5e0-054dc719e41b.png">

We can get the graphic from the Figma: EuqfSnWpfYx8fgiBlVmbuA-fi-3273%3A1563

@ianstewart mentioned it might be nice to have the graphic more like VideoPress instead of YouTube (a grey-ish overlay with no circle around the arrow).

**Comment by ollierozdarz** [comment]
@kwight yes please, in the same carousel. My bad for not mocking it up with the dots and control.

For the image, I've updated it in the design in [Figma](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/Blogger-Experience?node-id=3273%3A1563). It's similar enough to the other graphics used there.


<img width="711" alt="Screen Shot 2021-10-28 at 2 41 50 pm" src="https://user-images.githubusercontent.com/67085494/139188219-31880eae-a7f4-4cc1-ade9-4180708c4300.png">

**Comment by provenself** [comment]
The original, followed by three all-new options. These fragments can largely be mixed and matched, if there are any phrasings that people particularly like:

_**Original**_
**Save yourself hours and blog like an expert**
Learn the blogging basics from our quick and easy video lessons and set yourself up for success.
Start learning

**_Option 1_**
**Blog like an expert from day one**
Learn the fundamentals from our bite-sized video course—you'll be up and running in just nine minutes.
_Start the course_

**_Option 2_**
**Save yourself hours with our blogging how-to videos**
Five quick lessons teach you the basics so you can get started today.
_Get started_

**_Option 3_**
**Supercharge your blogging ASAP**
Get hours of learning in just nine minutes with our quick video course
_Watch the videos_

**Comment by kwight** [comment]
> The original, followed by three all-new options.

@blackjackkent Just go with number one, so that we have something and don't need to wait for any debate that might come up.

**Comment by blackjackkent** [comment]
Made progress on this today (using option #1 from Peter, as mentioned above); should have a PR in on Monday.

**Comment by blackjackkent** [comment]
Server-side component deployed in D69391-code.

**Comment by kwight** [comment]
With #57515 being our deploy mechanism for the feature, let's call this done.
