### ISSUE TITLE
Videos UI: Determine first course video titles and descriptions.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57327]
We'll need copy for the first five videos: titles and descriptions for each, plus a call-to-action line and button text for when the user finishes the videos.

<img width="489" alt="Screen Shot 2021-10-25 at 10 36 00 AM" src="https://user-images.githubusercontent.com/349751/138743374-05eb2bf7-4c31-4954-8cc3-55bc2a7850be.png">

**Comment by provenself** [comment]
Proposed copy! (Please note that the CTA buttons should probably stay neutral/consistent, just to keep the information density manageable.)

### **Video 1**
**Title:** 1. Find a theme you like
**Description:** It all starts with choosing a theme. We'll show you how to navigate your My Home area and sift through the options, so you can find the theme that suits your blog best. (Don't worry, you can always change it later.)
**CTA/Button text:** Watch the video

### **Video 2**
**Title:** 2. Customize your blog's appearance
**Description:** A theme is just the starting point. Learn how to use the Customizer to add a logo, change your blog's color scheme, set up your menu, and use widgets. 
**CTA/Button text:** Watch the video

### **Video 3**
**Title:** 3. Add your first blog post
**Description:** This video walks you through the post creation process, from categories to adding a featured image. You can use WordPress' powerful block editor to insert design elements, or just start typing.
**CTA/Button text:** Watch the video

### **Video 4**
**Title:** 4. Launch your site
**Description:** You've got your blog looking the way you want, and you've written a post. Now let's share it with the world. Here's how to take your site live.
**CTA/Button text:** Watch the video

### **Video 5**
**Title:** 5. Add social sharing buttons
**Description:** Make it easy for people to amplify your content—learn how to add sharing buttons so your readers can circulate your work on any social platform.
**CTA/Button text:** Watch the video

**Comment by andres-blanco** [comment]
> Video 5
Title: 5. Add social sharing buttons
Description: Make it easy for people to amplify your content—learn how to add sharing buttons so your readers can circulate your work on any social platform.
CTA/Button text: Watch the video

@provenself the part of the description that reads "content—learn" is correct or is it a typo?

**Comment by provenself** [comment]
@andres-blanco no, that's correct! However, Automattic style uses spaces around the em-dash, so should actually be:

> Make it easy for people to amplify your content — learn how to add sharing buttons so your readers can circulate your work on any social platform.

**Comment by provenself** [comment]
Updated Video 4 has been uploaded to the media library—that's all of it!

**Comment by kwight** [comment]
The first course will be called "Blogging Quick Start" (p1635870290408700/1635868542.407800-slack-C029SB8JT8S).
