### ISSUE TITLE
Widget Visibility - unable to update and save

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#57339]
### Quick summary

User is unable to update visibility for "Recent Posts" widget to show only on Blog page. I was also unable to update.

### Steps to reproduce

1. Start at https://kristininholland.com/ (theme is Shawburn)
2. Going to Widgets - "Recent Posts" in Footer
3. Click Visibility to "Show" if "Page" is "Blog"
4. Also tried to "Show if "Page" is "Posts (Post Types Archive)"
5. Click Update to save

### What you expected to happen

The Recent Posts widget should not show on static pages. 

### What actually happened

Clicking the Update button does not save the settings.

**Comment by supernovia** [comment]
Another report here:
https://wordpress.com/forums/topic/block-widgets-widget-disappearance-and-visibility-issues/

**Comment by mreishus** [comment]
Possibly related: #57330
Potential workaround: Change visibility settings using the customizer instead of widgets.php

**Comment by ghost** [comment]
Thanks for the workaround using customizer instead of widgets.php.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by supernovia** [comment]
From one of our forum volunteers ([link](https://wordpress.com/forums/topic/block-widgets-widget-disappearance-and-visibility-issues/page/2/?view=all#post-3752326))

> Just one clarification: in my case the Widget Group block visibility setting was originally set in the Customizer, not in widgets.php. Regardless of this, that setting kept flipping back to Show rather than Hide. Thanks again.

**Comment by mreishus** [comment]
This may be fixed when https://github.com/Automattic/jetpack/pull/21549 is merged.

**Comment by carinapilar** [comment]
Reported on here too: https://wordpress.com/pt-br/forums/topic/regaras-de-visibilidade-dos-widget-mailchimp-nao-salvam-ou-funcionam - the Customizer workaround doesn't work because there's no visibility option showing for the blocks.

**Comment by mreishus** [comment]
@lunasera41 , can you verify if this is still an issue or if it's fixed (or anyone else?). In my testing, it looks like both block widget visibility and legacy widget visibility are now saving correctly on wpcom simple sites.

**Comment by carinapilar** [comment]
@mreishus, I tested now on a WordPress.com Simple test site, and the issue still happens. I'm adding the Mailchimp block from Appearance > Widgets (which opens WP-Admin), I'm able to add a visibility rule and save it, but if I check the site I can see that it didn't work, and once I refresh WP-Admin, the rule is gone.

**Comment by isocialtish** [comment]
Another report in #32491956-hc when using wp-admin but it works in the Customizer.

**Comment by ghost** [comment]
@mreishus, I tested on a WordPress.com simple business test site, and I was able to save the visibility rule.

**Comment by yansern** [comment]
Unable to replicate this issue as I believe https://github.com/Automattic/jetpack/pull/21549 has fixed it. Closing this issue.

**Comment by jerrysarcastic** [comment]
Hmm... this issue still seems to be happening, as reported in https://wordpress.com/forums/topic/block-widgets-widget-disappearance-and-visibility-issues/page/2/?view=all#post-3761364

I can also confirm that if I make any changes in the customizer (or just reload it) the previous visibility setting is lost.

You can see this behavior in the following video, where I add a visibility rule, then save my changes.  If I reload the customizer that visibility rule remains but the has changed from "hide" to "show"



https://user-images.githubusercontent.com/1967448/142781318-a864aee6-20b8-4b01-9300-3f041e4048f0.mp4

**Comment by csonnek** [comment]
Our forums volunteer has even more testing data here: https://wordpress.com/forums/topic/block-widgets-widget-disappearance-and-visibility-issues/page/2/?view=all#post-3761673

**Comment by nickpagz** [comment]
Similar issue in 4624365-zd. Visibility settings are saved in widgets.php, but don't take effect on the live site. Changing the settings in the Customizer works as expected. In other other words, setting a visibility rule in widgets.php for a widget is saved but has not effect. Go into the customizer, and the rule is the same. Change the rule (to trigger a change), set it back to the same rule made in widgets.php, and the rules are then applied and works on the live site.

Theme is retired, Prosperity, and there are **many** widgets on this site - all using different visibility rules. Some of the blocks are 3rd party, but don't seem to change the outcome if made inactive.

**Comment by ccwalburn** [comment]
Another report here: 4638925-zen
Customizer workaround didn't work

**Comment by Sandkorner** [comment]
4765054-ZEN
Customiser workaround does not work and my Personal plan test site had the same issue.

**Comment by cuemarie** [comment]
Retested today and I am not able to replicate any issues with Visibility Settings across the Customizer or wp-admin Widgets.

Tested Simple site with Theme: Twenty Twenty-One

- Created a Widget via the Customizer set to SHOW only on the Posts Page
- Created a Widget via the wp-admin set to SHOW only on the Front Page
- Edited one widget to HIDE only on the Front page

All Visibility Rules tracked across both environments, and appeared as expected on the live site:

![Markup on 2023-07-27 at 13:58:55](https://github.com/Automattic/wp-calypso/assets/27249804/272fa42e-e3b6-4e8f-8f8b-539c03feb508)

![Markup on 2023-07-27 at 14:00:13](https://github.com/Automattic/wp-calypso/assets/27249804/0c22cde3-f393-4029-92bc-3155d32fe2b1)


https://github.com/Automattic/wp-calypso/assets/27249804/88eb6f63-01c9-45f9-9481-b7eaeb316efd

---
Since it's been quite a long time since we've had any reports of this issue, and I cannot replicate, I'm closing this as resolved/cannot replicate.

📌 ACTIONS
- Closed as resolved / no longer reproducible.

📌 Message to HEs
- This report contained a few different variations of Visibility issues. If a new issue occurs, please open a new report via Bugomattic specific to that issue. Thank you!
