### ISSUE TITLE
Design Picker: "Update homepage" button on My Home can lead to a broken page (if the user is fast enough)

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#57335]
#### Steps to reproduce

1. Be an a11n with lots of testing sites
2. Create a new free site at `wpcalypso.wordpress.com/start`
3. When you get to the Design Picker don't skip, select an option
4. Once My Home, quickly! Click the "Update homepage" button in the checklist!

#### What I expected

The homepage should load in the page editor. Specifically, the homepage that looks like the one you selected in the design picker.

#### What happened instead

![image](https://user-images.githubusercontent.com/1500769/138763824-dd4f0bd0-c9b0-4e7c-b5c6-909ee337e29f.png)

When the main Calypso dashboard loads we load all the user's sites from `/sites`. This gets us the `page_on_front` option which is used to generate the link for the "Update homepage" button. If the user has a lot of sites this can take a while to load, which means that the `page_on_front` option that the user will currently have in the redux store (which we've cached locally) is the one that was returned by `/sites/new`.

#### Context / Source

Reported:
p1634923255115300-slack-C029SB8JT8S

The bug manifests in the same way as #56533, but I believe the fix is different. #56533 fixed a selector which was wrong regardless of whether the data had finished loading from the server or not. In this situation, it's a timing issue. The user just has to be faster than the `/sites` request that Calypso does on page load.

Since it's the `/theme-setup` endpoint that's invalidating the old `page_on_front` id, maybe `/theme-setup` should be returning an updated copy of the site object so we can update the redux store.

Because the site list is huge, Calypso doesn't automatically keep it up to date. Other than page load and site creation, it's up to the actions that modify sites to make sure the site list is updated p4TIVU-9OT-p2. So I think `/theme-setup` returning the updated site object fits into the framework nicely

**Comment by arthur791004** [comment]
Yep, I think it still has a chance that the user clicks “Update the homepage” before we get the response from `/sites` API. Then, `page_on_front` will be the incorrect one. But I think this one might be the corner case as `/sites` API returns immediately for the new user. Also, if I were the new user, I won't click “Update the homepage” so fast 🤣

**Comment by roo2** [comment]
just a note from discussing this, we set it to Low priority becasue we it appears that this will mostly only affect a12s as this only happens if the user clicks the link before the call to `/sites`  completes, and `/sites` call is only slow if the user has many ~100+ sites

**Comment by fushar** [comment]
This issue will not happen anymore, as we only show block themes for new site creation. After site creation, we will be redirected to site editor and the Update homepage button will lead to the site editor as well, which does not depend on `page_on_front` anymore.

Closing this issue!
