### ISSUE TITLE
[Bug]: Block Widgets: New widgets added via widget.php are not saved

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#57330]
### Quick summary

Block Widgets: New widgets added via widget.php are not saved

Possibly related issue: #57170. However, provisional fixes we've found for this issue do not effect #57170, maybe they're not as related as they seem..

### Steps to reproduce

Steps:
* Have a simple site using the hever theme
* Add at least one widget using the customizer
* Visit https://[SITE].wordpress.com/wp-admin/widgets.php
* Add a new paragraph widget, type text into it
* Click the update button in the top right, wait for save to complete
* Press f5 to reload. 
* The widgets page reloads and your new widget is missing.

### What you expected to happen

* The widgets page reloads and your new widget is visible.

### What actually happened

* The widgets page reloads and your new widget is missing.

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by mreishus** [comment]
D68981-code stops this issue from happening, but isn't a practical fix since it modifies core without really understanding why, or respecting the original intent of the code commented out (chesterton's fence). However, it does illustrate something is happening differently between .com and .org and might be instrumental in developing a real fix. Additionally, this may be also related to the original issue of all widgets disappearing in certain circumstances, but I'm not certain yet.

**Comment by mreishus** [comment]
@david-binda Offers D68973-code which fixes the issue in my testing. The core cause is still a little bit mysterious to me.

**Comment by david-binda** [comment]
I have updated the D68973-code to actually address the issue cleanly, instead of the original hacky and mysterious approach :)

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by sixhours** [comment]
Was this fixed by D68973-code and https://github.com/Automattic/jetpack/pull/21549?

**Comment by mreishus** [comment]
Fixed by D69021-code
