### ISSUE TITLE
FSE: Site Editor Revision History

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#57349]
### What

I'm not sure it's possible but a revision history within the Site Editor would be nice to have. 

### Why

This would allow users to revert to a previous version of what they've created within the Site Editor. 

### How

It's currently available for pages and posts: 

https://user-images.githubusercontent.com/10015451/138853280-db39b147-f500-40b0-8662-cd44df1abef8.mp4

But not within the Site Editor: 

https://user-images.githubusercontent.com/10015451/138853364-4de3e591-ec55-4f0e-a5c5-863ccfc5f1f1.mp4

**Comment by jordesign** [comment]
Awesome suggestion - I've added an issue in the Gutenberg Repo for consideration.
https://github.com/WordPress/gutenberg/issues/36060
