### ISSUE TITLE
First Post congrats Modal appears in Page Editor.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#57356]
To reproduce create a new blog and publish a new page as your first action.

![image](https://user-images.githubusercontent.com/545779/138918714-22c22e01-be1e-4aad-aaa9-45c0c6b8df28.png)

You'll see a first post congrats message when you publish your first page.

Fix: Post Publish Modal should adapt to Post Type (Post, Page, Custom Post Type, etc.) or only appear in Post Editor view.

**Comment by autumnfjeld** [comment]
@ianstewart  @arthur791004 @roo2  I believe this modal should only show in the Blogger flow, so it should only show in the post-Editor not the page-Editor.

**Comment by roo2** [comment]
@autumnfjeld it is currently for any flow. The feature works by setting a site option on new sites `has_never_published_post`. It's set on site creation with the `wp_initialize_site` action so it is set on all new sites. It looks like we missed the check for it being a post when showing the modal, I've created a PR to add that check in https://github.com/Automattic/wp-calypso/pull/57375/files. 

Do you think that after fixing this bug we still should make the modal display only for people who selected the "write" intention?

**Comment by p-jackson** [comment]
> I believe this modal should only show in the Blogger flow

What do you mean "in the Blogger flow"? Does it mean that the modal would only show if the user wrote and published the post all in one sitting without ever leaving the editor? Personally, I feel like that would be a pretty big ask, and that we should expect users to be able to save their post as a draft, come back later to publish, and when they do to see the modal.
(which is what #57375 does)

**Comment by autumnfjeld** [comment]
@roo2 I do think this is only meant for users who have gone through the blogger flow.  So we could use the blogger intent flag (see D68408-code )  to determine whether we would show this modal.

**Comment by roo2** [comment]
I discussed this on a call with @autumnfjeld, we do want to limit the First Post Congrats Modal to only show for bloggers

**Comment by arthur791004** [comment]
I've asked a similar question p1634800345008200/1634613714.476700-slack-C029SB8JT8S to @ollierozdarz, and the modal can show to anyone who publishes the first post. IMO, this modal is the congrats modal and it can improve the experience for the user who published the first post. Thus, I think we can show the modal no matter what the intent is. Does it make sense 🤔

**Comment by roo2** [comment]
@arthur791004 thanks for the link! At first I thought the same, that it would be useful for anyone who published a first post. But I wonder if this congratulations modal would be appropriate for ecommerce sites. I haven't tested but I wonder if it could show "your first post is published" when they have uploaded their first product? (sorry, I should investigate that first... maybe it's not an issue)

Also I know that currently there's an issue that stops this from showing on atomic sites p1635987439075900-slack-CRWCHQGUB

**Comment by arthur791004** [comment]
> But I wonder if this congratulations modal would be appropriate for ecommerce sites.

I think intent and plan should be different things. For example, if the user selects `write` intent but not publish the post immediately. Then, they upgrade the plan to ecommerce and go back to finish the post. Should we show the congrats modal?

> Also I know that currently there's an issue that stops this from showing on atomic sites p1635987439075900-slack-CRWCHQGUB

Yep, I'm thinking how to make it works.

**Comment by autumnfjeld** [comment]
@arthur791004 I think these are great things to be aware of, but wondering if this is an edge case that isn't too critical.   It would be ok if the user switched to eCommerce and saw the congrats modal.  There wouldn't be any confusion or harm done.

**Comment by roo2** [comment]
from my comment earlier: 

>  I haven't tested but I wonder if it could show "your first post is published" when they have uploaded their first product? 

I tested this and products are indeed saved as `post_type=product` so this shouldn't be an issue 👍

**Comment by roo2** [comment]
@arthur791004 from that thread p1634800345008200/1634613714.476700-slack-C029SB8JT8S I don't think he explicitly said that we shouldn't limit it to the `site_intent=write` blogger flow, just that we shouldn't worry about limiting it to the site owner or show it when publishing a scheduled post. I agree that it probably won't hurt site building or other users to see this modal 🤷 

@autumnfjeld what do you think, should we add the check that the user came from the blogger flow or just continue showing it on first post for all new sites?

**Comment by autumnfjeld** [comment]
@roo2 @arthur791004  Let's only show the the "Your first post is published" modal for the Blogger/Write flow.   It's a part of the Blogger flow, and while it wouldn't be a critical issue if it is shown to non-bloggers , I think we should keep it out of other experiences since we can easily use the `site_intent=write` flag to control who sees the modal.  So let's only show it to users who go through the write flow.

Side commentary:  I personally think more thought needs to go into what happens after user clicks "publish" for their first draft.  There is the modal, and the side bar, a lot going on and I think we can make this post-launch moment better, a more unified UI experience.   We are just at the beginning of the big picture for the blogger experience, so it's ok that we try new things like this modal, but it may change in the near future.  This is my two cents. 😄

**Comment by autumnfjeld** [comment]
Make new issue for  site_intent=write flag to control who sees the modal. and then close this.

**Comment by autumnfjeld** [comment]
Closing this issue, which was fixed in https://github.com/Automattic/wp-calypso/pull/57375

 Opened https://github.com/Automattic/wp-calypso/issues/57855 to handle the `site_intent=write` task.
