### ISSUE TITLE
HeroFlow: Signup with plan leads to BSOD

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57357]
* New user
* personal or premium plan
*

ISSUE: Blank Screen of Death after payment (paid with credits), 
![image](https://user-images.githubusercontent.com/5665959/138923085-da9fdb6c-cde1-4f60-92c7-c2c4343c2bc2.png)

on this url:

https://wordpress.com/start/setup-site/design-setup-site?siteId=199168198&flags=signup%2Fhero-flow&notice=purchase-success

I was able to duplicate this.

**Comment by roo2** [comment]
I wasn't able to reproduce this with an existing user from `/start?signup/hero-flow` I tried purchasing a domain and the premium plan. Do you have any more information on reproducing this? It made me think of the WSOD issue I found earlier that can happen when restarting the flow https://github.com/Automattic/wp-calypso/pull/56848

**Comment by arthur791004** [comment]
I think this is more like p1632898918267200-slack-C029SB8JT8S but it should be fixed in https://github.com/Automattic/wp-calypso/pull/56677 🤔

**Comment by arthur791004** [comment]
Oh, I found this error but it might be this one is not my site.
> 62761.66f3c52692f3bbe1179f.min.js:2 Error: setup-site did not provide the query dependencies [siteSlug] it is configured to.
    at _e._assertFlowProvidedDependenciesFromConfig

 However, I think this happens only when the domain is still not ready, so we cannot get the `siteSlug` and the validation fail 😞
See: https://github.com/Automattic/wp-calypso/blob/952ecdcad5b343bfdd9d7550c844d13ec2c71a6d/client/lib/signup/flow-controller.ts#L135

**Comment by arthur791004** [comment]
I can reproduce this problem now but it seems to be **production** only. In this case, it calls `https://public-api.wordpress.com/rest/v1.2/sites/null/domains?http_envelope=1`, and then it cannot get the correct site info.

**Comment by autumnfjeld** [comment]
I went to reproduce this again, but instead of getting WSOD I got the Design Picker when I was expecting the Hero Flow:

New user
Free domain
Personal Plan
Landed on Design Picker, instead of Hero flow at this url: 
https://wordpress.com/start/setup-site/design-setup-site?siteSlug=auttest27foct.wordpress.com&loading_ellipsis=1&flags=signup%2Fhero-flow&notice=purchase-success

**Comment by arthur791004** [comment]
https://github.com/Automattic/wp-calypso/pull/57386 has deployed. I have tested with paid domain and paid plan on production about 5 times, but the BSOD doesn't appear.

**Comment by arthur791004** [comment]
> I went to reproduce this again, but instead of getting WSOD I got the Design Picker when I was expecting the Hero Flow:
> 
> New user Free domain Personal Plan Landed on Design Picker, instead of Hero flow at this url: https://wordpress.com/start/setup-site/design-setup-site?siteSlug=auttest27foct.wordpress.com&loading_ellipsis=1&flags=signup%2Fhero-flow&notice=purchase-success

After the checkout is completed, we use `page.redirect` to `/start/setup-stie?flags=signup/hero-flow` and it would not trigger the page reload, so the flags didn't work at that time. I think we don't need to fix this problem as `signup/hero-flow` is enabled on https://wpcalypso.wordpress.com/ and the user won't encounter this situation when testing.
