### ISSUE TITLE
Add a Domain dropdown loads in top left of dashboard

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#57368]
### Quick summary

Clicking the Add a Domain button loads the popover/dropdwon menu in the top left of the dashboard and not below the button.

### Steps to reproduce

1. Navigate to the Domains page and click the Add a Domain button.
2. The dropdown loads in the top left.

### What you expected to happen

I expect the dropdown to load below the button

### What actually happened

The dropdown loads in the top left of the dashboard.
<img width="1003" alt="Markup 2021-10-26 at 14 32 00" src="https://user-images.githubusercontent.com/41035049/138965246-1a8ff5e7-e055-48be-986a-6507534c6855.png">

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Other notes

Noticed it in a Support Session but can recreate it in my own dashboard. Confirmed with others in Slack.

### Reproducibility

Consistent

**Comment by jordesign** [comment]
Verified this behaviour in Chrome and Safari on Desktop sizes. It appears to be broken on any screen size greater than 480px.
