### ISSUE TITLE
Mobile menu does not work with Page Optimize plugin

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#57369]
### Quick summary

User on 32360075-hc couldn't get their mobile menu to work on their site. When deactivating Page Optimize plugin, the menu worked. They were using Button 2 theme. 
I was able to replicate that on a test site https://thelocalgardening.wpcomstaging.com/ and @carinapilar  also replicated the same issue with Hemingway Rewritten on test site https://at.mytestsite.blog/

### Steps to reproduce

1. Activate Page Optimize on a AT site
2. Enable a theme like Button 2 or Hemingway Rewritten
3. Check the menu on mobile. The menu burger icon doesn't work. It doesn't get expanded when tapped from mobile. 
4. Deactive Page Optimize. Make sure to clear cache and reload your site on mobile (this tends to get cached on mobile)
5. The menu on mobile now works. 

### What you expected to happen

The menu on mobile should work even with Page Optimize plugin

### What actually happened

The menu on mobile doesn't work with Page optimize plugin enabled 

### Theme-specific issue?

so far, it is happening on Button 2 and Hemingway Rewritten

### Reproducibility

Intermittent

**Comment by Robertght** [comment]
Thank you for reporting this @carladoria!

I tried to replicate this on my Android 11 device and I couldn't replicate this with or without Page optimize turned on.(on the testing site and on the user's site)

This is a known issue with AMP sometimes and switching that to a different mode helps, but I don't see AMP turned on for the user's site.

Could you share a little bit more details about your mobile devices? cc @carinapilar

**Comment by carladoria** [comment]
@Robertght we tried different AMP modes on their site and the menu was still not clickable. After deactivating Page Optimize plugin, the issue was fixed, but then it seems they had a new issue with submenus (not showing) and probably that is the reason why they ended up deactivating AMP altogether. 

I'm using iOS 15.0.2, iPhone 8

**Comment by carinapilar** [comment]
Interesting, on my test site, with the Hemingway Rewritten theme, it does seem to be an issue with AMP, when deactivating the plugin the menu starts working, even with Page Optimize active. This doesn't happen with the same theme the user has, Button 2, even after deactivating the AMP plugin, the mobile menu still doesn't work.

I'm using iOS 14.8, iPhone XS.

**Comment by Robertght** [comment]
Thank you both!

I'm not entirely sure Page Optimize is the culprit here, as I couldn't replicate it after the report, but I'm wondering if this is something more related to AMP or a combo of sorts. cc @jordesign as it appears to be related to specific themes only

**Comment by Robertght** [comment]
I'm going to mark this as low priority for now, but please share your cases here.

**Comment by ClassicRKR27** [comment]
I have another instance here where deactivating Page Optimize cleared the issue immediately: 31107895-hc

**Comment by dolgelukkig** [comment]
Another one with theme Hemingway Rewritten. I deactivated Page Optimize and AMP and that solved the issue
33037355-hc

**Comment by JoshuaGoode** [comment]
Related:

https://github.com/Automattic/wp-calypso/issues/56927

https://github.com/Automattic/page-optimize/issues/55

**Comment by carinapilar** [comment]
Another one on 33506759-hc with Radcliffe 2 - fixed deactivating the AMP plugin.

**Comment by brinbliss** [comment]
4678742-ZD using the Alves theme. Page Optimize -> disabling Optimize Concatenate scripts and Concatenate styles restores AMP menus.

Seems to be related to #56927 as well.

**Comment by carinapilar** [comment]
Another case on 33777379-hc - with the Ovation theme.

**Comment by dcoleonline** [comment]
34217565-hc Stratford theme

**Comment by jp-imagines** [comment]
Another case in 8508701-zd-a8c. Twenty Seventeen theme, AMP plugin not installed. Deactivating Page Optimize resolved the issue, as did keeping Page Optimize active but disabling _Concatenate scripts_ at `/wp-admin/options-general.php?page=page-optimize`. Reproducible on iPhone, iPad, Android, and in mobile browser previews.

Adding this to The One Board for re-triaging.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tried to replicate this with a clean Atomic site, and I'm not able to reproduce this.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
I suspect that there's a plugin conflict in this case, and not an issue with the Page Optimize plugin itself. Thanks for adding it to the board, tough!
