### ISSUE TITLE
Widgets: Search Widget not saving on Personal Plan site

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#57361]
### Quick summary

Search Widget not saving on user's simple site with Personal Plan

### Steps to reproduce

1. Open Simple Site
2. Go to Appearance > Widgets
3. Add "Search" widget
4. Select "Update"
5. Refresh

### What you expected to happen

The search widget saves in the widget area and can be edited from there

### What actually happened

The added search widget disappears

### Context

Customer report, could recreate on their site and on a test site with Personal plan.

https://user-images.githubusercontent.com/27249804/138942014-8350d850-c2c3-4ccd-afdb-06251c952d1d.mov

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

1. Adding the widget in the Appearance > Customize > Widgets area did not work on user's site, but did work on test site
2. Search Block works on pages on my test site, but this would not work for users with latest post homepages

**Comment by cuemarie** [comment]
User's theme was Twenty Sixteen, test site was Rowling

**Comment by Robertght** [comment]
Thank you for reporting this @cuemarie !

Could you include the ticket/chat ID as well? 

I tried to replicate this today but I had no luck. Could you give it a try as well and let us know if that is still an issue for you?

**Comment by cuemarie** [comment]
Hey @Robertght ! Thank you for the ping - can't believe I forgot to include the original interaction! :D 
chat: 31998758-hc // follow up ticket: 4406916-zd-woothemes

I was able to replicate this issue the day it happened, but I just tried again on my Personal plan test site and the issue didn't recur. I'll go ahead and reach out to the user and ask them to give it another try to see if it's still happening.  Thank you!

**Comment by dev-sabbir** [comment]
> Hey @Robertght ! Thank you for the ping - can't believe I forgot to include the original interaction! :D chat: 31998758-hc // follow up ticket: 4406916-zd-woothemes
> 
> I was able to replicate this issue the day it happened, but I just tried again on my Personal plan test site and the issue didn't recur. I'll go ahead and reach out to the user and ask them to give it another try to see if it's still happening. Thank you!

The issue is resolved for the user as well.

**Comment by Robertght** [comment]
Thank you for confirming! I'm going o close this one now, but please open it again in cases there are other cases.
