### ISSUE TITLE
Navigation Block:  Dropdown display disappears on Luxury theme

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#57360]
### Quick summary

When you add dropdown Menu using Navigation block on Luxury theme, the drop down menu disappears and doesn't let you select the options (menu items) from it.

### Steps to reproduce

Step 1: Activate the Luxury theme on your site.
Step 2: Add Navigation block to your Page with a dropdown option.
Step 3: Check this Menu on the Live site.

### What you expected to happen

**Expected**: The dropdown Menu added using the Navigation block will show the options to select from.

### What actually happened

**Actual**: You can't select anything from Dropdown Menu because it disappears.

### Theme-specific issue?

I tested the same page using the 2021 theme and it worked fine. I'm not able to decide if this would be a theme issue or a Navigation block issue. I'm tempted to believe it's a theme issue.

### Workaround details

I've got this CSS to help for now:

```
ul.wp-block-navigation__container li {
  margin: 0;
  padding-bottom: 5px
}

ul.wp-block-navigation__container li li {
  padding-bottom: 0;
}

.wp-block-navigation.has-background .has-child .wp-block-navigation__submenu-container {
  top: 18px;
  z-index: 999;
}
```

**Comment by formosattic** [comment]
Thanks @nerdysandy for the report and sharing a CSS fix.

Could you share screenshots of how the drop-down option is set?

I tested with a menu with a drop-down (set in Customize), and a Navigation block with the add submenu:
<img width="779" alt="Markup 2021-10-31 at 16 29 05" src="https://user-images.githubusercontent.com/15944096/139574555-ebbfa908-6d26-4049-9b65-edf3a797ea1c.png">

But whether with Twenty Twenty or Luxury:

* the drop-down set in Customize doesn't display correctly in the Navigation block
* using add submenu work fine with both themes

![troubleshooting](https://user-images.githubusercontent.com/15944096/139574674-db657cee-99e8-4081-9852-20dd06d9d247.gif)

**Comment by Robertght** [comment]
I cannot replicate this anymore. I've tested it using Luxury:

![image](https://user-images.githubusercontent.com/6737345/145368289-9102de10-ad75-4f42-81f0-9e9494132f69.png)

**Comment by ai2n** [comment]
@Robertght I don't think this has been resolved, ran into the same issue today with Archeo theme as well. #36418572-hc

**Comment by ai2n** [comment]
Left a comment here since that other issue seems to be open https://github.com/Automattic/wp-calypso/issues/62017#issuecomment-1211206637

**Comment by Robertght** [comment]
Thank you for the ping @ai2n !

Luxury is a classic retired Premium theme. Archeo is an FSE theme and it fits the case from https://github.com/Automattic/wp-calypso/issues/62017#issuecomment-1211206637.
