### ISSUE TITLE
Intent gathering step is skipped for existing users when an upsel is shown

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#57372]
#### Steps to reproduce
on the `/start?flags=signup/hero-flow` flow, 
* log in with an _existing_ user, 
* choose a *.blog domain. 
* select the "Personal" plan.

You will be prompted to upgrade your plan 
<img width="758" alt="Screen Shot 2021-10-27 at 9 04 49 am" src="https://user-images.githubusercontent.com/22446385/138973764-8ef23e98-6047-42c2-aa5b-b42402384bb8.png">
* Select "No thanks, I don't need plugins"

#### Expected
You will land on the intent-gathering screen

#### What happened instead
You will be taken directly to the theme picker screen
<img width="1792" alt="Screen Shot 2021-10-27 at 9 05 06 am" src="https://user-images.githubusercontent.com/22446385/138973863-4d4449b8-e312-4815-bff1-38399dd45408.png">

It seems to be another manifestation of this original bug https://github.com/Automattic/wp-calypso/issues/56303 that didn't get fixed when we transitioned to the hero flow.

It looks like its related to passing the `?flags=signup/hero-flow` parameter, which I thought I'd fixed in https://github.com/Automattic/wp-calypso/pull/56813 but this still seems to be happening

**Comment by roo2** [comment]
It looks like this is caused by feature flags in the query string and won't affect the feature once it goes live p1635921625070100-slack-CRWCHQGUB

**Comment by autumnfjeld** [comment]
@roo2 Given your above comment can we close this?
