### ISSUE TITLE
Guided Tours: Previewing site in Safari iOS crashes Safari

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5739]
#### Steps to reproduce
1. Starting at URL: https://href.li/?https://wpcalypso.wordpress.com?tour=main in Safari on iOS
2. Continue until you get to the preview step

#### What I expected

Preview site to be shown with guided tour

#### What happened instead

Safari Crashes and Reloads

#### Browser / OS version

iPhone 6 Plus - iOS 9.3.2

#### Screenshot / Video

Video: https://cloudup.com/cYEb1CLzQSy

![preview - 1](https://cloud.githubusercontent.com/assets/128826/15730547/f8a38568-28b0-11e6-9d91-16752da009af.jpg)

cc: @ehg

**Comment by lsinger** [comment]
I failed to reproduce on an iPhone 6 running iOS 9.3.2. Our current suspicion is that this was an outlier with a device that was already RAM-constrained when preview was opened. 

We'll close for now, but re-open if this becomes an issue for more people.
