### ISSUE TITLE
Masterbar Notifications - text being cut off with long temporary site names

### ISSUE THREAD

**Issue by joelwills** [Automattic/wp-calypso#57398]
### Quick summary

I started a new Business site and received this notification:

> 🎉 Congrats! testingthedowngrade102721 is getting noticed. Joel has started receiving...

However clicking on the notification doesn't tell me more. What have I started receiving?! 

<img width="819" alt="Screen Shot 2021-10-27 at 09 15 26" src="https://user-images.githubusercontent.com/3228004/139107079-52a87d06-b8a1-4edf-9ba3-23170c360dc1.png">

This is possibly due to the length of my site name. 

### Steps to reproduce

1. Start a new Business site (in my case, perhaps any site will work).
2. Check your notifications and see that you get one where the text is cut off.

### What you expected to happen

I should be able to either see more text in the notification, or clicking on it, it should expand so I can read what the text is meant to say.

### What actually happened

I can't find where I can read the rest of the test after the ... 

What have I started receiving? The site was set to Private so I'm not sure it can be visitors/hits or Likes? Then what?

### Context

Discovered during my testing of the automated Atomic downgrade. 

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Reproducibility

Once

### Severity

All

**Comment by ivan-ottinger** [comment]
**Solution 1**

The simplest solution could be to change

```css
.wpnc__main .wpnc__list-view .wpnc__text-summary .wpnc__subject {
	max-height: 3em;
	-webkit-line-clamp: 2;
}
```
to

```css
.wpnc__main .wpnc__list-view .wpnc__text-summary .wpnc__subject {
	max-height: 4em;
	-webkit-line-clamp: 3;
}
```

Result:
![Markup on 2021-11-05 at 12:22:36](https://user-images.githubusercontent.com/25105483/140503251-d3221e38-b5a4-49e3-b8a2-bbdfc60e422d.png)

---

**Solution 2**

I have also experimented with other approach where we would display the full text once the user clicks on the notification:

![Markup on 2021-11-05 at 12:14:33](https://user-images.githubusercontent.com/25105483/140503783-faed40d7-556a-40d6-9af5-656f8dab033a.png)

This would apply to _follow_ notifications only.

Which option do you prefer? I would vote for the Solution 1 - as it is much simpler.

For completeness, here's the diff I would be happy to turn into PR if we decide to go with the Solution 2:

```diff
diff --git a/apps/notifications/src/panel/boot/stylesheets/main.scss b/apps/notifications/src/panel/boot/stylesheets/main.scss
index 4e3ea3af1e..93a46e7e47 100644
--- a/apps/notifications/src/panel/boot/stylesheets/main.scss
+++ b/apps/notifications/src/panel/boot/stylesheets/main.scss
@@ -137,7 +137,8 @@
 	}
 
 	.wpnc__user__username,
-	span.wpnc__user {
+	span.wpnc__user,
+	span.wpnc__site {
 		font-weight: 600;
 		a.wpnc__user__home {
 			color: var( --color-neutral-70 );
diff --git a/apps/notifications/src/panel/templates/block-user.jsx b/apps/notifications/src/panel/templates/block-user.jsx
index 883e6e01d6..96efdb0e94 100644
--- a/apps/notifications/src/panel/templates/block-user.jsx
+++ b/apps/notifications/src/panel/templates/block-user.jsx
@@ -5,6 +5,8 @@ import { connect } from 'react-redux';
 import getIsNoteApproved from '../state/selectors/get-is-note-approved';
 import FollowLink from './follow-link';
 import { linkProps } from './functions';
+import { html } from '../indices-to-html';
+import { p } from './functions';
 
 function getDisplayURL( url ) {
 	const parser = document.createElement( 'a' );
@@ -63,6 +65,7 @@ export class UserBlock extends Component {
 		let timeIndicator;
 		let homeTemplate;
 		let followLink;
+		let followNotificationSubject = '';
 
 		if ( this.props.block.meta ) {
 			if ( this.props.block.meta.links ) {
@@ -135,6 +138,10 @@ export class UserBlock extends Component {
 			);
 		}
 
+		if ( 'follow' === this.props.note.type ) {
+			followNotificationSubject = p( html( this.props.note.subject[ 0 ], { links: false } ) );
+		}
+
 		if ( home_url ) {
 			return (
 				<div className="wpnc__user">
@@ -147,6 +154,7 @@ export class UserBlock extends Component {
 						</a>
 					</span>
 					{ homeTemplate }
+					{ followNotificationSubject }
 					{ followLink }
 				</div>
 			);
```

**Comment by ivan-ottinger** [comment]
Just noting here that I have already crated a PR (https://github.com/Automattic/wp-calypso/pull/57697) for the Solution 1. But we can still explore Solution 2 later.

**Comment by joelwills** [comment]
Thanks, those look great! When the issue first occurred, I expected the answer to be what you are showing in Solution 2. However I think it would be good to not even need to do that, which you do with Solution 1. Other notifications (or at least mentions and new comments) are four lines in total, two for the person and post title and then two lines for the start of the comment. Like notifications are two lines, so these occasionally being three when there is a long site title wouldn't feel too visually different to me. I guess it's more of a UX/design decision.

As this will only affect follow notifications (and not all) Solution 1 makes sense to me. I appreciate it, thanks again!

**Comment by ivan-ottinger** [comment]
Thank you for your feedback @joelwills! I will merge and deploy the CSS change once it is reviewed. Probably early next week.

**Comment by ivan-ottinger** [comment]
Successfully deployed to WPCOM.
