### ISSUE TITLE
Editor: Sharing connection monitoring is fragile

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#574]
Since the editor opens a popup window to connect a new sharing service, then only monitors that specific window for changes when it is closed, this flow is a bit fragile.  For example:
- Open the sharing popup and connect a new service
- Refresh the editor page; the connected service appears
- In the same sharing popup, disconnect the service.
- Close the popup and note that the sharing accordion is not immediately refreshed (because the connection between the editor and the popup window has been broken).

Perhaps rather than waiting for a specific window to close, it would be better to use `postMessage` to do live monitoring of changes here.

**Comment by jkudish** [comment]
The polling that was removed in 12550-pre-oss would have addressed edge cases like this. So maybe there's a future where we can re-implement that.

**Comment by nylen** [comment]
FWIW I find that shorthand for GitHub links pretty annoying.  It's pretty obvious to anyone reading it what it means, so there are no advantages to using it, and it has the disadvantage of requiring extra steps for people with access to the private repos to view it.  This is better for us, and not any worse for public readers and contributors:  Automattic/calypso-pre-oss#12550

**Comment by lancewillett** [comment]
Changed to enhancement as future consideration.

**Comment by lancewillett** [comment]
See also #11099

**Comment by cathymcbride** [comment]
Sharing now opens in a new window. Closing...
