### ISSUE TITLE
Guided Tours: Clicking the ellipsis next to site name breaks guided tour

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5740]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/?tour=main
2. Continue on the tour until you get to the preview site
3. Don't click the dot, instead click the ellipsis between the bubble and the dot
4. Close the ellipsis

#### What I expected

Guided tour to continue - or be able to escape the tour at least

#### What happened instead

See video below - the guided tour is broken now and I couldn't work out a way to dismiss the tour - I tried pressing the `esc` key but I can't get rid of it, besides hard refreshing window

#### Browser / OS version

Chrome OSX 10.11.2

#### Screenshot / Video

![preview site](https://cloud.githubusercontent.com/assets/128826/15730895/f2c075fe-28b3-11e6-896e-d802461b2c2e.gif)

cc: @ehg

**Comment by lsinger** [comment]
This doesn't seem to be the case anymore. Closing for now.
