### ISSUE TITLE
Woo Installer: Landing page redesign

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#57419]
Redesign the /woocommerce-installation/ landing page based on the design in figma r6eTqDpL2GGk96hcPLhsBb-fi-0%3A1

I believe the images were placeholders so please confirm copy / images are good to use before starting (cc @JanaMW27)

Currently only business sites on atomic can load the [existing page](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/woocommerce). The existing page renders a confirmation screen and then takes you through a plugin installation process. Eventually this will be completely replaced by the new onboarding flow leaving only your new landing page in its place. 

The navigation menu is controlled by Jetpack and wpcomsh, it is currently only shown to atomic sites using wpcomsh. You can enable displaying the menu navigation item by adding the 'woop' flag in blogrc or using wpsh to add the site sticker.

For now we just need the landing page redesigned for these business+atomic site users, we will later swap out the installation step with the new onboarding flow under `/start/*`

Implementation suggestion: Build this as a standalone new component under `client/my-sites/woocommerce/some-new-landing-page-thing` as we should be able to remove everything else that is currently in there once the new onboarding flow is completed. 

For now you should be able to import your new landing page component into this [render function](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx#L480-L501) and pass in `startSetup` as the CTA handler.

- [x] Redesign the landing page.
- [x] Hide/Show Navigation Button when scrolling past the CTA Button.
- [x] Create WaveImageMasonry component (right-side component with web images).
- [x] Design Titles and CTA Button.
- [x] Make the new landing page responsive.
- [x] Add back `<SetupNotices />`

Screenshot from figma (see there for more variations, ignore the premium plan upgrade stuff for now)
![Screenshot(45)](https://user-images.githubusercontent.com/811776/139239156-03a60470-cfde-4d5e-931d-01beb6affc91.png)

**Comment by lsl** [comment]
Use top part only for now

**Comment by allilevine** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/58179 but we may want to add additional content in the future.
