### ISSUE TITLE
Woo Installer: Tell us about your business step

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#57422]
Create the about your business step in the new woo installer. seen in Figma r6eTqDpL2GGk96hcPLhsBb-fi-0%3A1

This component needs to:
- [ ] Ask the same questions as the woocommerce onboarding wizard (triggered on plugin install) (defined in the [woocommerce-admin plugin](https://github.com/woocommerce/woocommerce-admin/tree/main/client/profile-wizard)) (warning this form is dynamic, questions change based on the answers you give, ideally try to flatten this out for usability)
- [ ] In a format matching core woo's save the form data to signup state, we need to set this data as wp site options on the atomic site post transfer. (Approach TBD, tracking here https://github.com/Automattic/wp-calypso/issues/59481)

r6eTqDpL2GGk96hcPLhsBb-fi-0%3A1
![Screenshot(47)](https://user-images.githubusercontent.com/811776/139242738-b0bb1a21-66aa-4748-a8d7-f607fb4ba93c.png)

**Comment by obenland** [comment]
It looks like the current version of the Woo flow has the product type as a checkbox list. Let's figure out how we want to go about that in Calypso.

<img width="1020" alt="Screenshot on 2022-01-03 at 15-25-00" src="https://user-images.githubusercontent.com/1398304/147982795-68d5535d-0195-4a6a-ae9e-52297f9d5d9a.png">

**Comment by allilevine** [comment]
Does this step need to include a question about Industry?

<img width="577" alt="Screen Shot 2022-01-04 at 9 34 24 AM" src="https://user-images.githubusercontent.com/1689238/148075834-fc856977-d758-4253-8e37-79d969895ca4.png">

**Comment by retrofox** [comment]
Do we know how the data is structured into the site options? Some of them are pretty simple like Dusty explains [here](https://github.com/Automattic/wp-calypso/issues/59481#issuecomment-1004414672).

**Comment by retrofox** [comment]
> Do we know how the data is structured into the site options? Some of them are pretty simple like Dusty explains [here](https://github.com/Automattic/wp-calypso/issues/59481#issuecomment-1004414672).

oh right, it's stored in the `woocommerce_onboarding_profile` option.

**Comment by Rolilink** [comment]
In the original flow there are two tabs for the Business Details - Step should the Free Features one be included? It seems to be optional tho.

![Screen Shot 2022-01-04 at 3 24 58 PM](https://user-images.githubusercontent.com/1035546/148120566-0f06eae3-07f4-4590-8baa-4330a5a7dae4.png)

**Comment by allilevine** [comment]
> In the original flow there are two tabs for the Business Details - Step should the Free Features one be included? It seems to be optional tho.

@Rolilink I missed that! One of the features is Woo Payments, which we're already installing in this flow. It might be cool to install more plugins based on customer answers in a future iteration but for now I don't think we need the Free Features tab to accomplish our goal of getting some customer information.

<img width="507" alt="Screen Shot 2022-01-04 at 4 16 17 PM" src="https://user-images.githubusercontent.com/1689238/148125283-c0e88769-485f-44df-ab2d-9f45d313994e.png">

**Comment by lsl** [comment]
> Does this step need to include a question about Industry?

I think you're aware already now, this question was only being used for marketing purposes so we dropped it in order to limiting ourselves to things that configure woo.

> In the original flow there are two tabs for the Business Details - Step should the Free Features one be included? It seems to be optional tho.

No need for a question about what to install, anything required for the baseline woo experience should be included by default for all plans (like wc pay), anything optional can be installed on a business plan / via marketplace.
