### ISSUE TITLE
Query Loop Block: Images loading in different size formats

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#57431]
### Quick summary

Query Loop Block is loading Featured Images in an incorrect format size for some blog posts, they are showing as 100x100, whereas they should be loading in a larger version. View on homepage of site [here](https://holywhiskblog.com/).

![egg_frontend](https://user-images.githubusercontent.com/44442769/139267886-6d311a0f-743a-4831-9526-f34dfbdb5931.png)

These Featured Images can also be seen with an incorrect size from the blog post editor, from the Featured Image area in the sidebar
<img width="715" alt="egg_editor" src="https://user-images.githubusercontent.com/44442769/139267757-1d78c708-5d11-4b3e-b668-91f8e392c3e4.png">

 

### Steps to reproduce

1. Create a new page with the Query Loop Block with the theme Canard
2. The block will pull in the Featured Images from posts and some are shown incorrectly with the format size 100x100 
3. When uploading a new image to a blog post, the Featured Image thumbnail is also incorrect.

Have not yet found a pattern as to why is happens to some images and not others. 
Testing with the image https://i0.wp.com/holywhiskblog.com/wp-content/uploads/2021/01/Easter-Egg-Pastry-3-100x100.jpg?ssl=1
The issue can be seen on the homepage of this [site](https://holywhiskblog.com/).

### What you expected to happen

I would expect the Feature Images within the Query Loop Block to not be resized and be shown correctly, as here:
<img width="979" alt="egg-correct" src="https://user-images.githubusercontent.com/44442769/139268515-795ba6f2-298a-4f49-83ac-60d55b17b972.png">
 

### What actually happened

When the Featured Image is uploaded, it is being resized to 100x100 and showing smaller on the site.

### Context

User reported the issue here: #4408595-zen

Issue appears to be only on Canard, when tested in TwentyTwenty, it does allow you to upload and use the image without any problem. 
With the theme Canard, the error is on simple sites and AT.

Issue could be related to image size coming from here
![egg-size](https://user-images.githubusercontent.com/44442769/139269445-747060e3-0934-4574-8a88-d219038a6592.png)

Image: https://i0.wp.com/holywhiskblog.com/wp-content/uploads/2021/01/Easter-Egg-Pastry-3-100x100.jpg?ssl=1

Activating Gutenberg seems to trigger unexpected behavior as well.

@Robertght & Adrian

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Theme-specific issue?

Canard

### Reproducibility

Intermittent

**Comment by Robertght** [comment]
Flagging this for @Automattic/cylon for a second look as I'm not 100% sure what's going on.

**Comment by daria2303** [comment]
user would like to be updated when resolved

**Comment by Copons** [comment]
> Flagging this for @Automattic/cylon for a second look as I'm not 100% sure what's going on.

Hi @Robertght, neither the site nor the Canard theme use FSE so I'm afraid we won't be of great help here.

As far as I can see, the theme hasn't been touched in a while, probably long before the Query Loop block. 🤔 
It might be a matter of updating the styles (cc @Automattic/theam).

Or... the site has quite a lot of plugins related to a (unused) third-party theme. Wonder if they are getting in the way somehow.

**Comment by thekingsprojects** [comment]
Hello! I'm just commenting to check in and see if anyone has had any ideas about this yet? The user would appreciate any sort of update or workaround, if at all possible.

**Comment by Addison-Stavlo** [comment]
I am unable to repro. Given Jacopo's [comment above](https://github.com/Automattic/wp-calypso/issues/57431#issuecomment-954072581) regarding that site not being FSE, an old theme, and much related work to the query block done since this issue was created, im going to close this.
