### ISSUE TITLE
Playwright: Flakiness in invite revoke spec - can't find invite email

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57439]
### Details

TeamCity mobile build no. 6117.

`wp-invite__revoke.ts`

```
Error: No matching messages found in time. By default, only messages received in the last hour are checked (use receivedAfter to override this).
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/mailosaur/lib/operations/messages.js:415:24
    at IncomingMessage.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/mailosaur/lib/request.js:94:9)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by worldomonation** [comment]
My opinion is to wait a bit more before looking to implement a fix for this.

Logstash reports that in any given day, most errors related to keyword `*login` are for the magic link. 

Anecdotally, my friend also used a magic link but when he clicked on the link it told him the link was expired.

**Comment by worldomonation** [comment]
Propose monitoring for a bit more to see if the failure rates become unacceptable.

**Comment by worldomonation** [comment]
Failure incidence rate is _really_ low for this test, yet TeamCity has the audacity! to mark this as a flakey test.
![image](https://user-images.githubusercontent.com/6549265/139512941-e1f8eadd-3781-48f3-aa39-d02d8f7473e0.png)

**Comment by worldomonation** [comment]
Monitoring for another 4 days to make two weeks; if no more occurrences I would chalk this up to a random failure.

**Comment by worldomonation** [comment]
Closing as the issue has not recurred.
