### ISSUE TITLE
Playwright: Flaky invite revoke spec when trying to revoke invite

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57438]
### Details

See mobile TC build no. 6111

`wp-invite__revoke.ts`

```
page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
at PeoplePage.selectInvitedUser (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/people-page.ts:127:14)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-invite__revoke.ts:76:20)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
```

**Comment by worldomonation** [comment]
Some other failed runs:
https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop/6901682
https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/6901688

**Comment by worldomonation** [comment]
I think we need to wait until the entire list is loaded, and the performance on this page can quickly deteriorate if more than a certain number of invites are pending.

**Comment by worldomonation** [comment]
Taking over investigation.

**Comment by worldomonation** [comment]
Trace: https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Playwright_desktop/6901682:id/trace/ensure-invite-link-is-no-longer-valid-2021-10-28T14-03-32.zip
