### ISSUE TITLE
Videos UI: Pull data from the endpoint.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57448]
Our component currently displays dummy data; let's update it to use our new endpoint at `https://public-api.wordpress.com/wpcom/v2/courses?course_slug=<slug>`.

<img width="622" alt="Screen Shot 2021-10-28 at 10 21 11 AM" src="https://user-images.githubusercontent.com/349751/139304942-06917d47-a849-4e8f-9a3e-4d3c22aac6cf.png">

We also need to pull user attribute data from the API; this is how we'll get the user's video completion data (although this part is not necessary for the MVP).

**Comment by enejb** [comment]
I think this is really great to add the course data via an endpoint. This way we can populate the course data based on the user's specific requirements/situation. 

For example, we could show different visuals if the user is on mobile web vs desktop web since the UI is often so different. :)

**Comment by kwight** [comment]
We'll also need to update the course descriptions and data from https://github.com/Automattic/wp-calypso/issues/57327.

**Comment by kwight** [comment]
> For example, we could show different visuals if the user is on mobile web vs desktop web since the UI is often so different. :)

True! And we do have proper mobile web styles coming: #57446
