### ISSUE TITLE
Playwright: Why do we get blank pages post-login?

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57440]
### Details

Any test can intermittently fail due to only seeing a blank white page upon login.

For example, you can check mobile build no. 5605, and desktop build no. 6899.

![blank_login](https://user-images.githubusercontent.com/26772342/139285624-334c32cf-fbf5-4e61-82b1-cc7d15be3c5b.png)

### Checklist

- [ ] Figure out what is causing this
- [ ] Assign to fix

**Comment by dpasque** [comment]
p1635269273006000-slack-C02DQP0FP

**Comment by worldomonation** [comment]
One instance: https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/6870962?buildTab=overview#%2Fscreenshots;%2Ftrace

**Comment by worldomonation** [comment]
I think this can be mitigated by saving the login cookie and creating new BrowserContexts using the cookie, thereby bypassing the login process.

**Comment by worldomonation** [comment]
Haven't seen this occur since the login cookies were saved.

**Comment by worldomonation** [comment]
I think we can close this for now.
