### ISSUE TITLE
Show name servers and A records on Connected Domain Settings screen

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#57444]
### What

Can we show a Quicklink to a card that displays name servers and A records on Connected Domain Settings screen

### Why

I had a user in chat who said they had a hard time finding their A records to connect their domain. The domain however was connected already, but the user had no way to refer to the A records to double check.

**Comment by delputnam** [comment]
We're currently working on a complete redesign of the domains management pages. (pcYYhz-o2-p2) Hopefully this will help alleviate issue such as these.
