### ISSUE TITLE
[PAUSED] Hero Flow: remove character, pen, and plane illustrations

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57458]
### Details

Due to some last minute changes by broader design team, we can't ship the current illustrations.  We will get new illustrations in the (hopefully near) future, but that is still TBD.

@ollierozdarz will provide screenshots and further details to show what need to be removed.

Dev team should let Ollie & Autumn know the expected work to do this, e.g. will there time consuming styling issues since images are removed.  

### Checklist

- [ ] item 1
- [ ]

### Related

https://github.com/Automattic/wp-calypso/issues/55603

**Comment by ollierozdarz** [comment]
Thanks, @autumnfjeld!

Updated screenshots below. Originals can be found in the relevant Figma pages in the [Blogger onboarding](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/Blogger-Experience?node-id=3351%3A1624) file. 

- Multi intent ([screenshot](https://d.pr/i/lSPVOc))
- Blog name ([screenshot](https://d.pr/i/QjvCAF))
- Starting point ([screenshot](https://d.pr/i/SRs2kh))
- First post modal ([screenshot](https://d.pr/i/Oj0vAq))
- Post published modal ([screenshot](https://d.pr/i/EVL315))

**Comment by autumnfjeld** [comment]
Removing the illustrations is paused for now.  We'll wait for more feedback from Design.

**Comment by ollierozdarz** [comment]
Plot twist 🎥

**Comment by arthur791004** [comment]
Close this one in favor of https://github.com/Automattic/wp-calypso/pull/58213
