### ISSUE TITLE
Videos UI: Add unit tests for the library.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57456]
Let's make sure we've got good code coverage for the server-side library.

**Comment by kwight** [comment]
Duplicate of #57454.

**Comment by kwight** [comment]
Oh dang, not a duplicate at all – two different things. 🙃  We still need unit test coverage for the library.

**Comment by sixhours** [comment]
Pretty sure I worked on this for 20% time a few weeks ago; will add the diff here and see if there are other functions I didn't cover with that work.

**Comment by sixhours** [comment]
Some work was done on this in D74627-code

I'll go through the library again and see what cases/functions still need tests.

**Comment by sixhours** [comment]
Looks like we still need tests for `fetch_courses`, `fetch_videos`, and `parse_video`

**Comment by sixhours** [comment]
Started working on this here: D77761-code

But I'm a bit blocked, because all these functions refer to/get data directly from the production blog ID, which (as far as I can tell) is inaccessible within the testing framework. More thoughts in that diff.

**Comment by sixhours** [comment]
Chatted with @andres-blanco and we agreed refactoring the courses lib to filter the blog ID would be a good approach, so I've done this in D77761-code

**Comment by sixhours** [comment]
The only function remaining without a test is `parse_video`, but it uses VideoPress functions that make direct database queries to a table that doesn't exist in the testing environment.

I may need to wrap those functions in a separate method to make them mock-able for unit testing. We don't really want to test the individual VideoPress functions, only ensure their return data is parsed into the correct format. I did some MGSing and found @mmtr had to do this for one of the same functions: p7H4VZ-2bw-p2#comment-7380

I think that's the approach I'll take here.

**Comment by sixhours** [comment]
`parse_video` addressed here: D77979-code

**Comment by sixhours** [comment]
With D77979-code landed, the Videos UI library has pretty good coverage. I think we can call this done!
