### ISSUE TITLE
Theme Showcase: Upside-down quote marks

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#5746]
There are some upside-down opening quote marks in the text on some themes, for example, Forefront:

https://horizon.wordpress.com/theme/forefront

![forefront theme wordpress com](https://cloud.githubusercontent.com/assets/7662449/15746452/95fc40b4-28a4-11e6-931d-7b6ecd6234dc.png)

This is also the case on WP Calypso:

https://wpcalypso.wordpress.com/theme/forefront/

But the quotes are OK on showcase v2 here: https://theme.wordpress.com/themes/forefront/

This isn't consistent, the quote marks are right-side up in other places, and on other themes. For example, quotes are not upside-down on Goran:

https://horizon.wordpress.com/theme/goran
![goran theme wordpress com](https://cloud.githubusercontent.com/assets/7662449/15746641/6b3645c2-28a5-11e6-92ac-b84834565ab3.png)

I thought I'd also spotted some upside-down single quotes but I can't find them now - if I can locate them again, will update this ticket.

**Comment by folletto** [comment]
Fascinating. There seems to be a conversion somewhere in the API then. As a first guess, it seems that the ones that are generic quotes `"` get converted to that, otherwise if they are already the right quotes (i.e. `“`), they stay the same.

**Comment by folletto** [comment]
I did a quick check again, and seems fixed on https://wordpress.com/theme/forefront/setup

Screenshot:

  
![screen shot 2017-01-18 at 17 29 44](https://cloud.githubusercontent.com/assets/4389/22075428/db97f30c-dda3-11e6-90a9-7e725829b820.png)


Can you cross-check?

**Comment by kathrynwp** [comment]
Yep - looks fixed to me and I haven't seen this come up again lately. I think this can be closed.

**Comment by folletto** [comment]
Thank you!
