### ISSUE TITLE
Libre 2: Duplicates Fixed Post on List of Posts

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#57469]
### Quick summary

The theme shows a fixed post on the list of posts, even if the fixed post is also shown on the top.

### Steps to reproduce

1. Work on a site with about 5 posts for example
2. Set the oldest post as sticky
3. Set on the Writing settings to display 3 posts per page
4. Go to your site, which should show 3 posts and the sticky one at the top
5. Click to load older posts

### What you expected to happen

When loading older posts, the oldest one set as sticky shouldn't show on the list of posts.

### What actually happened

Since this theme loads more posts within the same page, it duplicates the sticky post, it keeps showing it on the top, and shows on the list of loaded posts too.

### Context

The difference from the other themes is that they usually add `page/2/` to the URL, loading another page, where the sticky post doesn't show, showing it just on the list of posts. Since Libre 2 loads the new posts within the same page, it keeps the sticky post at the top, and loads the post again on the list, as expected.

From the steps above for example, if you set to show 6 posts on a blog page, it would only show the sticky post on the top, and not on the list of posts, so it wouldn't duplicate it.

Reported here: 4412561-zd-woothemes

**Comment by Greatdane** [comment]
@carinapilar Testing on other themes, the sticky post stills shows for me again as the oldest post - the only difference with LIbre 2 is because there is no pagination, the post appears twice on the _same_ page, but it does not behave any different than other themes (other than the lack of pagination).

Closing, unless I have misunderstood - in which case, please let me know!

**Comment by carinapilar** [comment]
@Greatdane, yes, that's what happens. Libre 2 is different because there's no pagination, so the user complained that the post is duplicated. In my opinion, although it does seem expected, doesn't feel like an ideal behavior, if the theme loads the posts on the same page, it shouldn't load the sticky post again - or hide it from the top. But since that's the behavior for pagination, I guess it's not a bug? Not sure, but it does feel like an unfortunate behavior. Maybe we could call this a conflict with this WordPress feature.
