### ISSUE TITLE
[Bug]: Possible race condition when refreshing site address changer leads to uncaught error

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#57461]
### Quick summary

Found an error on a possible race condition when refreshing the site address changer page which leads to the following error on the development environment using the trunk branch:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at ChangeSiteAddress.render (index.jsx:65)
    at finishClassComponent (react-dom.development.js:17485)
    at updateClassComponent (react-dom.development.js:17435)
    at beginWork (react-dom.development.js:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23959)
    at performUnitOfWork (react-dom.development.js:22771)
    at workLoopSync (react-dom.development.js:22702)
```
So far haven't been able to replicate it on production.

### Steps to reproduce

1. Open a simple site without a domain
2. Navigate to Upgrades > Domains.
3. Click on Manage > Change site address.
4. Hard Refresh (CMD + SHIFT + R) the site multiple times until you get the error.

### What you expected to happen

The page should correctly show the site address changer like this:
![Screen Shot 2021-10-28 at 7 00 22 PM](https://user-images.githubusercontent.com/1035546/139352470-5a4a65c4-918c-42ff-bcbe-a3ceca6f1bc2.png)

### What actually happened

The page breaks and just shows a white screen with an error message in the console like this:
![Screen Shot 2021-10-28 at 7 00 55 PM](https://user-images.githubusercontent.com/1035546/139353270-ddf15146-9cc4-4313-bf98-c24c40d6a843.png)

### Context

Found the bug while working on a fix for #55306

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Intermittent

### Available workarounds?

Yes, easy to implement

### Workaround details

My guess is that the component is being rendered before domain data is available leading to an error here: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/domains/domain-management/change-site-address/index.jsx#L44

Replacing `domain.name` with `get( domain, 'name', '' )` should fix this one, I am researching a little more and will send a commit with a fix.

**Comment by allilevine** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/57561
