### ISSUE TITLE
Geologist: Layout Change on Header

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#57481]
### Quick summary

User reported that the positioning of elements in the header recently changed.

### Steps to reproduce

1. Activate the Geologist theme on your site
2. Check the live site

### What you expected to happen

For the site's title and tagline to be shown on the same line, as it shows on the theme page here: https://wordpress.com/theme/geologist

### What actually happened

The tagline shows on a new line, as it's now showing on the theme's demonstration page here: https://geologistdemo.wordpress.com/

### Context

Reported here: 4415469-zd-woothemes

The user said they didn’t change anything, so I checked for theme and CSS changes, and nothing should have affected that. But when I check their theme, Geologist, I found that [the preview screenshot](https://wordpress.com/theme/geologist) shows as they said it was. When checking posts about the launching of this theme, it also shows the header as the user mentioned, and it shows correctly on the WordPress.org theme showcase, and on its preview there (I also installed it on a WordPress.org site and it worked as expected).

It seems to have changed only on WordPress.com sites.

### Workaround details

At the moment, we don't have a CSS to fix this for now.

**Comment by JoshuaGoode** [comment]
The default template parts for the header did receive some light tweaks recently.  (D69262)

cc: @scruffian

**Comment by JoshuaGoode** [comment]
Re: https://github.com/Automattic/themes/pull/4928

**Comment by JoshuaGoode** [comment]
Seems it is related to recent Blockbase changes: https://github.com/Automattic/themes/pull/4928

**Comment by carinapilar** [comment]
CSS workaround for now:

```
/* Site branding / XXXXXX-HC (MI) */
.site-header > .wp-block-group {
  display: flex;
  align-items: center;
}

.wp-block-site-title {
  padding-right: 16px;
}
```

**Comment by scruffian** [comment]
This has been reverted.
