### ISSUE TITLE
Classic blocks do not display content in preview for mobile or tablet in Calypso

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#57489]
### Quick summary

Content inside a classic block does not display when users click "Preview" in the editor and choose mobile or tablet view. Instead, there is only a gray box showing "Classic".

### Steps to reproduce

1. Open a post or page in the editor.
2. Make sure there is a classic block with content inside
3. Click Preview> Mobile or tablet

### What you expected to happen

The content inside the classic block should be displayed.

### What actually happened

Just a gray bar showing "Classic"

### Context

4417421-zd, also tested on my own sites both simple and Atomic.

### Operating System

macOS

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

User will need to use the block editor/blocks and not classic blocks if they want to see previews of the content in mobile/tablet view.

**Comment by kuropixel** [comment]
Adding video recording.
https://user-images.githubusercontent.com/83020905/139570411-e76722b1-9454-4c5c-8387-64549f0182cb.mov

**Comment by retnonindya** [comment]
Another report:
4417496-zd-woothemes

This causing confusion and concerns on users (they thought their (live) site won't be visible on mobile and tablet)

**Comment by Robertght** [comment]
Thank you for reporting this. I asked [here](p58i-bmT-p2#comment-52200) as well. 

LE: https://github.com/Automattic/wp-calypso/issues/57304

**Comment by kuropixel** [comment]
Another report:
4419031-zd

**Comment by benchilcote** [comment]
Another report: 4430937-zd

**Comment by kspilarski** [comment]
4434500-zd

**Comment by yansern** [comment]
Calypso preview modal has been removed in favour of Gutenberg's native preview and therefore this is no longer fixable.
User is advised to use the "Preview In New Tab" option instead.
