### ISSUE TITLE
Block Widget: Archives widget throwing error when Visibility feature is active.

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#57493]
### Quick summary

When activating Visibility for widget Archives on Block Widget, the widget crashed with error `Error loading block: Invalid parameter(s): attributes`

### Steps to reproduce

1. Open the website's Customize > Widgets, or go directly to /wp-admin/widgets.php
2. Add Archive widget block
3. On the widget block's settings, click tab "Advanced", then click "Visibility"
4. As soon as the button "Visibility" is clicked, the Archive widget crashes

![Screenshot 2021-11-01 at 9 57 46 AM](https://user-images.githubusercontent.com/44726232/139611299-d06f077a-bd2e-46c2-a7e6-b7944c7a4e73.png)

GIF (Screen recording):

![Nov-01-2021 09-57-29](https://user-images.githubusercontent.com/44726232/139611330-0b62795b-8738-484a-8855-e555f8c74a9a.gif)

### What you expected to happen

For the Archive widget to stay and work properly, and users can set visibility on the widget

### What actually happened

The widget crashes with warning `Error loading block: Invalid parameter(s): attributes`

### Context

Customer report and I am able to replicate it on my test site (Premium plan, simple site)

### Severity

All

### Workaround details

Not exactly using Archive widget, but maybe using archive-related widgets such as Latest Posts widget, etc.

**Comment by Greatdane** [comment]
@retnonindya I am only able to replicate this on Simple sites, is this the same for you?

**Comment by retnonindya** [comment]
@Greatdane David! Yep, I managed to replicate this on Simple site, and it seems like this happens on Simple site only

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment]
This seems to affect all dynamic blocks - blocks that requires server-side rendering. Calendar block is also another one of them that is affected.

What seems to be going on is that `rest_validate_object_value_from_schema()` is trying to validate block attributes against schema described in `block.json` files. And in those schema files, attributes related to block visibility do not exist, e.g. `conditions` property.

What needs to be done is to ensure block schema is extended on top of some base schema where block visibility attributes are.

**Comment by tellisbethel** [comment]
Hi there, @yansern! Thanks for your input above! Could what you described be the same issue that's happening with in this more recent report? https://github.com/Automattic/wp-calypso/issues/60372 

The user is looking for an update and time would be saved if it turned out that this was the same problem. 

Thanks!

**Comment by nagpai** [comment]
I am closing the ticket - 4664133-zd 

Once the issue is resolved, please reopen a followup and let the user know that it is fixed.

**Comment by formosattic** [comment]
Error message is now: `This block has encountered an error and can't be previewed.`

Other user reports (from [here](https://github.com/Automattic/wp-calypso/issues/60372)):
* 4664133-zd-woothemes
* 4794738-zd-woothemes

Please notify once this fixed.

https://user-images.githubusercontent.com/15944096/156324226-118d9a8c-7703-4877-b525-e17450cff29b.mov

**Comment by rachelwinspear** [comment]
Is there any update on this issue? 
34972031-hc

**Comment by renata-franco** [comment]
I got a chat here with this issue: 35747805-hc
No updates?
