### ISSUE TITLE
Error after clicking "Add Email" Upsel from the congratulations page

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#57490]
#### Steps to reproduce

1. Starting at URL: `/domains/add/mapping/YOUR_SITE.wordpress.com`
2. type in a *.blog domain
3. Complete the Checkout
4. You will see a congratulations page
<img width="847" alt="Screen Shot 2021-10-31 at 9 23 13 pm" src="https://user-images.githubusercontent.com/22446385/139580708-1f2f9fcd-66b7-4d31-a96b-2117ab39a51c.png">
5. Click on "Add Email"

#### What I expected
You would be taken to the titan email page

#### What happened instead
The page fails to load with a javascript error on the console 
<img width="1567" alt="Screen Shot 2021-10-31 at 9 23 44 pm" src="https://user-images.githubusercontent.com/22446385/139580749-7f9ad7a8-819d-40c4-aa79-93abc26180a4.png">

Refreshing the page fixes the error, and the page loads correcly
#### Browser / OS version
Chrome on osx

**Comment by autumnfjeld** [comment]
I could also duplicate this issue.  

![image](https://user-images.githubusercontent.com/5665959/139722970-2692ace5-251e-4d42-8457-baa5280da71f.png)

cc: @daledupreez

**Comment by daledupreez** [comment]
Thanks for the report, @roo2 and the ping, @autumnfjeld!

We'll tackle this one tomorrow -- it looks like we're not loading some state that we need, or are not checking for it still being loaded.

cc @Automattic/letero

**Comment by daledupreez** [comment]
@roo2 and/or @autumnfjeld, as a quick follow-up, how quickly are you clicking on the "Add email" button? I am wondering whether this is strictly on the front end, or if we may be seeing a side-effect of some work from @Automattic/nomado to shift some aspects of the domain provisioning process to be asynchronous.

**Comment by daledupreez** [comment]
Fixed by #57565.

**Comment by autumnfjeld** [comment]
@daledupreez I'd say not at all quickly, I was meandering around...it would have been 5-10 seconds or more. Definitely not immediately after page load.
