### ISSUE TITLE
Missing post categories

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#57496]
### Quick summary

My Site > Posts > Categories is showing less number of categories than the user has. When you search for a "missing" category on the category page, the "missing" category shows up.

When editing a post, these "missing" categories are not part of the category options to select.

### Steps to reproduce

1. SU to user's dashboard
2. Go to Posts > Categories. Notice there are only a few categories
3. Search for a category `furniture` which is "missing" in the search bar, notice it shows up: Some missing categories: `Design Awards`, `Furniture Design`, `Graphic Design`

### What you expected to happen

All created categories should show up without searching for them

### What actually happened

Some categories are missing and posts cannot be assigned to them

### Context

Reported here 32506021-hc. Follow-up 4420023-zen

### Other notes

Site was a Simple Business site. The issue persisted even after making it Atomic.

### Reproducibility

Consistent

### Workaround details

There's no workaround that I found.

**Comment by helenaartmann** [comment]
The theme is a retired Premium theme IPPO

**Comment by mikeicode** [comment]
Solved in the ticket:

>  there were some items that were listed as sub-items of themselves, and when this occurred, anything else that was a sub-type of these would not show either

I'll close this.
