### ISSUE TITLE
The Service Worker should be decoupled from the Push Notifications library

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#5750]
A static Service Worker [file](https://github.com/Automattic/wp-calypso/blob/afe723f7939ea155949a6798072846d2389d0584/client/lib/push-notifications/service-worker.js) was added as a part of supporting browser push notifications (#4987). The code is tightly-coupled to the [push-notifications library](https://github.com/Automattic/wp-calypso/blob/afe723f7939ea155949a6798072846d2389d0584/client/lib/push-notifications/index.js#L43-L63) as-is.

Since service workers are unique per origin (unless we get creative with [scope urls](https://www.w3.org/TR/service-workers/#dfn-scope-url)), new features that make use of a service worker will need to add their code to this file.

Consequently, we should use a `service-worker`-specific library and move the Push Notifications listener function there.

A "Nice-to-have" would be to leverage our build system such that we can modularly add to the service worker javascript file we serve & use ES6+ syntax, imports, etc.

Related #2718

**Comment by ehg** [comment]
Looping in @rralian, as I know this is something you guys were looking at earlier in the year.

**Comment by jonathansadowski** [comment]
Just wanted to add a note from Mozilla's [docs on service workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers):

> If your service worker has previously been installed, but then a new version of the worker is available on refresh or page load, the new version is installed in the background, but not yet activated. It is only activated when there are no longer any pages loaded that are still using the old service worker. As soon as there are no more such pages still loaded, the new service worker activates.

I don't think this is something we necessarily need to worry about until we have another desired use for service workers... but it should be kept in mind (and maybe something we could work-around if we were creative enough with `importScripts`, for example).
