### ISSUE TITLE
Inconsistent italics in editor

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#57517]
### Quick summary

Italics are not applying consistently to selected text in posts and pages.

### Steps to reproduce

1. Start new draft of post or page in Gutenberg editor.
2. Type a few lines of text.
3. Highlight a portion of the text.
4. Click the _**I**_ (italic) button in the toolbar, or press Ctrl-I/Cmd-I.

### What you expected to happen

The highlighted text should all be italicized.

### What actually happened

Part of the highlighted text is italicized, but part is not:

![image](https://user-images.githubusercontent.com/79414372/139745333-a843cd20-729c-44d6-82d1-017f5ff8e5e7.png)

### Context

Customer report.

Premium plan, Simple site, Independent Publisher 2 theme.

### Operating System

Windows, macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Available workarounds?

Yes, difficult to implement

### Workaround details

User types text in offline word processing application (MS Word), then pastes into editor. If changes need to be made, user changes in Word, then pastes into editor over previous text.

**Comment by Greatdane** [comment]
@the-misha - I am unable to replicate this;

![Screen Capture on 2021-11-02 at 14-50-47](https://user-images.githubusercontent.com/5075840/139793468-f47ca77d-ee06-4f2e-8370-7ca00ecb07f9.gif)

I have tested this on various sites and themes (including Independent Publisher 2). Could you let me know some more information on what setting you used?
