### ISSUE TITLE
Design Picker: when selecting Spearhead the new site will have no homepage, but My Home has an "Update homepage" button

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#57521]
When a user selects a theme with no homepage (e.g. Spearhead) and lands on My Home, the site setup checklist has a button to "Update homepage", but there's no homepage to update. This is a bit weird.

pdgK6S-gm-p2#comment-568

**Comment by arthur791004** [comment]
When I select `Spearhead` and land on My Home, the "Update homepage" isn't shown on the site setup checklist now.

**Comment by autumnfjeld** [comment]
I will close this issue.
