### ISSUE TITLE
Karuna: Featured images of post excerpt shows unrelated images if using "Automatically use first image in post"

### ISSUE THREAD

**Issue by essleeung** [Automattic/wp-calypso#57524]
### Quick summary

User reported that the featured image is completely unrelated to the images in the post if the following options are selected in the customizer > content options

1. Blog display- post excerpt
2. Featured images- display on blog & archives / automatically use first image in post

Screenshot of settings
<img width="322" alt="Markup 2021-11-02 at 07 26 06" src="https://user-images.githubusercontent.com/39225086/139797905-6c432117-e6f7-4188-a6be-76edca006588.png">

[Image on posts page shows "Approved armature comp"](https://armaturenine.wordpress.com/2012/11/page/2/)
<img width="979" alt="Markup 2021-11-02 at 09 32 42" src="https://user-images.githubusercontent.com/39225086/139798335-7b59f145-d256-4f73-af7a-5633d657ddea.png">

[Actual image in 'Giving out free minis' post shows a 2.5" figure](p8iBdF-VA-p2)
<img width="1046" alt="Markup 2021-11-02 at 09 36 23" src="https://user-images.githubusercontent.com/39225086/139798230-0215a30e-a059-43f7-8625-07738aaacc7b.png">

Other examples: 
* https://armaturenine.wordpress.com/2019/8/ (Reindeer picture above Body 3D Scan post)
* https://armaturenine.wordpress.com/2013/11/ (Guy with wings above Photo Library Update post)

### Steps to reproduce

I couldn't reproduce on my own test site, but I also have very few posts. The user has over 1000 posts. 

1. Set theme to Karuna. 
2. Go to Appearance > Customize > Homepage Settings. Select "Your latest posts". 
3. Go to Appearance > Customize > Content Options. Select "post excerpt" under Blog display, "display on blog and archives" and "automatically use first image in post" under Featured images. 

### What you expected to happen

The featured post should pick the first image in the post. 

### What actually happened

The featured image shows a completely unrelated image from the archives.

### Context

Ticket: 4422201-zd-woothemes
Chat: 30909191-hc

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Karuna

### Reproducibility

Once

### Severity

One

**Comment by Greatdane** [comment]
User replied with more info;

> I learned that the issue persists if I display full posts (not excerpt). So I’ve turned off excerpt and turned off to feature first image as feature image.

**Comment by Greatdane** [comment]
It looks like after further communication, the issue may be more related to the images being loaded from an external WordPress.com site as the pages were imported. Going to close this as unable to replicate.

**Comment by cuemarie** [comment]
This looks it matches this open bug: https://github.com/Automattic/themes/issues/6000

Leaving closed in favor of the open thread
