### ISSUE TITLE
Domain Management: DNS: Prompt to delete email forwards when removing MX records

### ISSUE THREAD

**Issue by rads** [Automattic/wp-calypso#5752]
As part of @matthusby's suggestion to fix an earlier StoreP2 issue (p2MSmN-4Qx-p2), we need to create a new prompt in the DNS editor. When the user tries to remove all their existing WPCOM MX records, we should ask if they want to also delete all their email forwards. This ensures that the WPCOM MX records do not get automatically added again by our system later on.

I'm still thinking about what UI component we should use for the prompt. The copy would look something like this:

```
To delete your WordPress.com MX records, you must also deactivate your Email Forwards.

[Deactivate Email Forwards] [Keep Existing DNS Records]
```

It seems like this would work best as a separate card similar to the [IcannVerificationCard](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/domain-management/components/icann-verification/icann-verification-card.jsx).

**Comment by breezyskies** [comment]
This should probably use the confirmation modal -- similar to what's used for cancelation and delete site:

<img width="400" alt="screen shot 2016-06-16 at 3 21 56 pm" src="https://cloud.githubusercontent.com/assets/3011211/16131847/190263f8-33d6-11e6-9971-5d87e011a87d.png">

cc: @ranh for copy review.

**Comment by ranh** [comment]
Seems that the flow would be clearer if there was a toggle for using wpcom MX records, similar to the  toggle for using wpcom name servers or custom name servers.

Otherwise, re. the message, let me know if this sounds right:

> Removing these records will make your current email forwards stop working. 
> [Deactivate email forwards and remove records] [Keep records and email forwards]

**Comment by rads** [comment]
@ranh:

> Seems that the flow would be clearer if there was a toggle for using wpcom MX records, similar to the toggle for using wpcom name servers or custom name servers.

Here's the fundamental problem. We currently have four possible states:

1. The user has Email Forwards and uses WPCOM MX records.  
2. The user has Email Forwards and uses custom MX records.
3. The user doesn't have Email Forwards and uses custom MX records.  
4. The user doesn't have Email Forwards and uses WPCOM MX records.

In reality we only need two of those states:

1. The user has Email Forwards and uses WPCOM MX records.
2. The user doesn't have Email Forwards and uses custom MX records.

If we can ensure that the user's account will always be in those two states instead of four, it makes the code simpler and reduces potential for error.

What you're suggesting is more about simplifying the UI for editing records, which is different from what the confirmation model is trying to accomplish. Even if we implement an OFF/ON toggle, we still need to ask the user if they want to remove their Email Forwards when they set it to OFF. Otherwise they're going to go to their Email Forwards page and see entries that are misleading.

Since it's too dangerous for us to delete the Email Forwards automatically, I think it makes sense to make the user aware there's no point in having both custom MX records and Email Forwards at the same time.
