### ISSUE TITLE
Verticals: Pull a list of the verticals from the verticals API into MC

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#57542]
We're fetching the list of verticals from the API at `/lib/nux-helpers/all-verticals.php`

Ideally this list should be searchable since it's quite long, so we're investigating jquery ui autocomplete library to assist.

**Comment by mreishus** [comment]
This is done w/ jquery autocomplete library.
Note that the google doc of verticals does not match the `verticals-master.csv` on the wpcom codebase
* google doc
  * 1100 verticals
  * includes priority information 
* verticals-master.csv
  * ~1650 verticals
  * Does not include priority information
