### ISSUE TITLE
Verticals: Store image selections to wpcomverticals

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#57545]
Once we've selected images from Pexels, clicking a "Save" button should send that data to our private storage site's media library at wpcomverticals.wordpress.com.

The images should be loaded into the media library with post meta data for their vertical flag, orientation, copyright, Author, etc.

**Comment by mreishus** [comment]
This is done in conjunction with D69577-code, but it's possible to save duplicates.

**Comment by sixhours** [comment]
Calling this done! We can resolve the duplicates if we need to in a separate sprint/PR.
