### ISSUE TITLE
Playwright: Redesign signup flows to account for new blogger experience onboarding

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57550]
### Details

Details of project: p9Jlb4-31T-p2

Onboarding is getting a new set of flows! These make some pretty significant changes such that we'll need to redesign our flows to...
1. Ensure the right coverage of the new onboarding branching paths
2. Handle loading and navigation across screens and for initial site creation

This issue will track the process of redesigning those tests!

**Comment by dpasque** [comment]
Alright, after gathering feedback from the team and looking at existing scripts, I wanted to propose a test plan map for the `signup__free` and `signup_paid` scripts.

The goal here is to get as much coverage in as few of flows and sites created. I'm also trying to balance out the scripts so that they have generally the same amount of content (one is not a lot longer than the other).

The current proposal adds a little bit more validation to these scripts, but I think it's worth it. Signup is arguably the most important thing for our product right now, and we should try to ensure good coverage there.

### Coverage

#### Free Spec
- Choosing free options
- `Write` hero flow, ultimately using the "Draft First Post" option
- Launching a site

#### Paid Spec
- Purchasing a plan (will do what we do now too and add a domain initially, but remove it from the cart)
- 'Build" hero flow


### Flows

#### Free Spec
Go to `/start` 
>> Pick a free domain 
>> Pick a free plan 
>> `Write` hero flow 
>> Enter site title and tagline 
>> Pick "Choose a Design" 
>> Go backwards 
>> Pick "Draft your first post" 
>> Land in editor 
>> Go to settings 
>> Validate the title and tagline 
>> Validate "Coming Soon" in new page 
>> Launch the site 
>> Delete the site

#### Paid Spec
Go to `/start` 
>> Pick a domain 
>> Pick a plan 
>> Remove domain from cart 
>> Checkout 
>> `Build` hero flow 
>> Preview a design 
>> Start with that design 
>> Land on home/admin page 
>> Validate theme
>> Cancel plan 
>> Delete site

In the end, I think these will roughly have comparable runtimes.

### Feedback

What do you think @worldomonation @arthur791004 @p-jackson  ??

**Comment by worldomonation** [comment]
I think the outline generally looks good to me!
