### ISSUE TITLE
Verticals: Add ability to flag images for different orientations

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#57557]
Ideally, as we curate images, we'll flag them as being useful for specific crops (portrait, landscape, square) so we aren't trying to fit portrait-focused images into landscape-sized spaces, for example.

A second UI that shows each selected image, cropped to the desired orientation, with the ability to select which ones work would be useful. 

Rough wireframe of this concept in action:

![images](https://user-images.githubusercontent.com/2124984/139881838-5fd2a457-f16a-40e3-b5ad-5e439c158f26.png)

Pexels already provides portrait, landscape, and square crops via their API. I imagine we'd add an "orientation" flag to the image's post meta that contains a list of the approved orientations for that image.

This is considered a "nice to have" if we have time for v1.

**Comment by nelsonec87** [comment]
@sixhours I believe it's coved by the current version :)

**Comment by sixhours** [comment]
Yep, this has been added! :D
