### ISSUE TITLE
Videos UI: Add a loading state while waiting for the course endpoint results.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57567]
We should have a pulsing loading state for the course content while waiting for endpoint results.

<img width="700" alt="Screen Shot 2021-11-02 at 9 58 24 AM" src="https://user-images.githubusercontent.com/349751/139911079-3e88cfc1-96db-434b-9adc-224020554966.png">

**Comment by kwight** [comment]
@ollie any preferences for this? I know we use pulses in places like the editor:

<img width="600" alt="Screen Shot 2021-11-02 at 10 04 41 AM (2)" src="https://user-images.githubusercontent.com/349751/139912421-2c4014c7-6b1a-42ce-9979-fc00406572ef.png">

Are spinners still a thing in Calypso?.. 🤔 

For the sake of the call-for-testing, we can do a simple pulse, and then update whenever there's something more concrete.

**Comment by ollie** [comment]
@kwight I think you meant to mention somebody else, but you have a thumbs up from me because of the kittie.

**Comment by kwight** [comment]
> I think you meant to mention somebody else

Doh! Sorry, I meant @ollierozdarz 🙃 But I agree, the kitty makes everything better. 🐈

**Comment by kwight** [comment]
Check for an existing loading indicator in the new "hero flow".

**Comment by ollierozdarz** [comment]
@kwight we now have a three dot loader in the blogger flow. Would be happy to reuse that. We could either make it white and place it over the dark Grey page background, or use the existing loading pattern (light Grey page background and dark grey loader).
