### ISSUE TITLE
Videos UI: Trigger a new video to play when clicking a "Play" button.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57574]
We need to wire up a Play button for each video that loads and plays that video.

<img width="912" alt="Screen Shot 2021-11-02 at 11 59 56 AM" src="https://user-images.githubusercontent.com/349751/139928242-c6f3048b-3877-4615-aed1-a0005bfdf901.png">

**Comment by andres-blanco** [comment]
closing, addressed in #57614
