### ISSUE TITLE
Videos UI: Consider giving video Play buttons a hover state.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57583]
The standard `<Button>` component has only a subtle border change for its hover state, which is not very effective with the darker background – let's consider adding a more visible hover state. It would also apply to the call-for-action button at the bottom of the UI.

<img width="912" alt="Screen Shot 2021-11-02 at 11 59 56 AM" src="https://user-images.githubusercontent.com/349751/139956882-417c2558-7dce-4d6d-9135-e9edcd1ef116.png">

<img width="1584" alt="Screen Shot 2021-11-01 at 10 15 38 AM" src="https://user-images.githubusercontent.com/349751/139956903-00180916-ba55-472f-b8fd-a14a0bd6e942.png">

**Comment by kwight** [comment]
What do you think @ollierozdarz ? We won't get to it before the call-for-testing, but certainly can as followup next week.

**Comment by ollierozdarz** [comment]
@kwight let's do it. How can I access this UI in the browser so I can provide some styles?

**Comment by kwight** [comment]
@ollierozdarz We just have a couple of fixes to https://github.com/Automattic/wp-calypso/pull/57515 in the next couple of hours, and then you'll be able to use that branch locally (or the calypso.live link).

**Comment by kwight** [comment]
@ollierozdarz it's been updated: https://calypso.live/?image=registry.a8c.com/calypso/app:build-18345

**Comment by kwight** [comment]
@ollierozdarz I just noticed this in the Figma; is the white background button supposed to be the hover of the darker one?

| Standard | Hover |
| --- | --- |
| <img width="488" alt="Screen Shot 2021-11-08 at 2 47 01 PM" src="https://user-images.githubusercontent.com/349751/140830450-2fd6c0b5-92f4-4dcb-90ac-3e8bcb648fe9.png"> | <img width="472" alt="Screen Shot 2021-11-08 at 2 47 09 PM" src="https://user-images.githubusercontent.com/349751/140830460-2533893a-b4a4-499e-bf2c-9a2ad1ee17aa.png"> |

**Comment by ollierozdarz** [comment]
@kwight the dark button is meant to be the state once a video is played. We had the idea of being able to check off the videos once someone has watched them, so basically applying a special class to the button to show it's been played. 

https://d.pr/i/i2Xld5

**Comment by ollierozdarz** [comment]
As for Hover, if we haven't implemented anything yet, a simple bump in opacity down to 80% on the white button would be sufficient.

**Comment by kwight** [comment]
> the dark button is meant to be the state once a video is played

Ah! Got it.

> a simple bump in opacity down to 80% on the white button would be sufficient

Great – so the 80% would be the regular, and the 100% would be the hover? (So the button gets brighter on hover.)
