### ISSUE TITLE
WordAds Breaking Mobile Posts Formatting

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#57585]
### Quick summary

With Baskerville 2 active, WordAds is breaking the formatting of blog posts on mobile on the posts page.

### Steps to reproduce

1. With Baskerville 2 active and WordAds fully active, set the homepage to show the latest posts
2. Once ads are loading, check the mobile version of the page (be sure to refresh)
3.  Notice the bottom of the post is cut off.

### What you expected to happen

I expect the full blog card to load with margin before the next post.

### What actually happened

Posts overlap, hiding the Continue Reading button and the ad.

### Context

Reported in #4424819-zen

Cannot confirm if this is just a theme-specific issue, but turning off WordAds does allow that to load correctly (after 2 refreshes).

With WordAds on:

![Markup 2021-11-02 at 15 50 24](https://user-images.githubusercontent.com/41035049/139962594-128c72d4-d7d2-4a30-bcbe-b2bfa0d3c49b.png)

With WordAds off:
![Markup 2021-11-02 at 15 51 12](https://user-images.githubusercontent.com/41035049/139962563-0bf1c1cf-c911-4664-8470-23ea228c00ac.png)
 

Screenshot of desktop version with ad:

![Markup on 2021-11-02 at 15:53:27](https://user-images.githubusercontent.com/41035049/139963803-befa0e23-4154-47f0-942f-76a9db0ba2b6.png)

### Operating System

macOS

### Browser

Google Chrome/Chromium, Apple Safari

### Theme-specific issue?

Unknown, but seems related to Baskerville 2.

### Reproducibility

Consistent

**Comment by Greatdane** [comment]
@khristiansnyder I am unable to replicate this on my or the user's site; 

<img width="536" alt="Markup 2021-11-04 at 14 46 07 (1)" src="https://user-images.githubusercontent.com/5075840/140264288-10da3b07-53d3-415b-bd6e-b1b260d78a0e.png">

Not sure if the user changed something.
