### ISSUE TITLE
Blogger Flow: Update copy on starting-point screen

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57582]
# Blogger Flow: Update copy on starting-point screen
Part of Hero Flow: Write & Build intent screen #55603
![image](https://user-images.githubusercontent.com/5665959/139954978-2c8bc4e7-1527-4989-b401-16e4421aeaf1.png)

## Description
There are a couple issues with the current copy, which is "Nice job! Lastly, pick a starting point.":
* “Lastly” and “starting point” seem conflicting, and I don’t think "Lastly" really applies because the blogger is still on their journey. (Last would be clicking publish or launching.)
*  user already sees "Start" in two screens in signup/onboarding
![image](https://user-images.githubusercontent.com/5665959/139954705-2e07aab5-0218-471f-a540-3fe59f639696.png)
![image](https://user-images.githubusercontent.com/5665959/139954733-cdba6442-ec47-4c0c-8c34-0ee933287b65.png)

### Before (Current)
![image](https://user-images.githubusercontent.com/5665959/139954928-2399db24-7ac5-4f6d-adc5-d15f177616b5.png)

### After:
use this copy: "Nice job!  Now it’s time to get creative."

**Comment by autumnfjeld** [comment]
@arthur791004 @ @roo2  FYI to do this before shipping, but not critical for HE testing. :)

**Comment by roo2** [comment]
@autumnfjeld, I created https://github.com/Automattic/wp-calypso/pull/57586 to change the copy, one question is that the original copy had an explicit line break `Nice job! Lastly<br/> pick a starting point`. 
I didn't add one to the new copy, do you think it is ok on the different screens?

<img width="576" alt="Screen Shot 2021-11-03 at 9 29 19 am" src="https://user-images.githubusercontent.com/22446385/139965929-870711aa-d8ee-4ffa-a8de-3fd34edf83e2.png">
<img width="1299" alt="Screen Shot 2021-11-03 at 9 29 04 am" src="https://user-images.githubusercontent.com/22446385/139965933-ea44a54a-218d-4957-b6f1-ea7b3d1b1494.png">
<img width="380" alt="Screen Shot 2021-11-03 at 9 29 31 am" src="https://user-images.githubusercontent.com/22446385/139965916-a0c908ef-0b6b-4b7e-98b5-f0b54d4fca06.png">

**Comment by autumnfjeld** [comment]
Seems like a line break after "it's" makes sense .  Makes the line lengths balanced

**Comment by p-jackson** [comment]
I'm trying to think about how translators will interpret the `{{br}}{{/br}}` in the text that needs to be translated. Maybe they'll try and place it at the same point in the sentence, but that isn't right. Since they don't have a dev environment they don't really have a way to know where the right place to put the line break would be.

@ollierozdarz asked for an explicit line break in the design picker, [which I implemented this hacky way](https://github.com/Automattic/wp-calypso/pull/56814/commits/6c454422871201caf0940c19b971e6c557995440). Tbh I'm not a massive fan of these English-only tweaks, but at least keeping the line breaks out of the translated string makes it more explicit that this is an English-only tweak, and not something we can expect translators to do for us.

**Comment by arthur791004** [comment]
I agree with @autumnfjeld that we use the line break to make the line lengths balanced. So I don't think it should be English-only tweak. But as you said, the translator might try to place it at the same point in the sentence and the line lengths would not balance. Maybe we should use another way such as max-width to control the line lengths balance.

**Comment by p-jackson** [comment]
> Maybe we should use another way such as max-width to control the line lengths balance.

The thing is that we do want all of that space to be available for the text (except for some small amount of margin on the right-hand side). The German translation for instance could be much longer than English, and we wouldn't want it to prematurely wrap or hyphenate words when there's clearly more space for the words to fit into if it weren't for a max-width we'd set.

**Comment by autumnfjeld** [comment]
Let's not let this block shipping the new text.  We can come back to line break discussions if this is taking too long.

**Comment by jordesign** [comment]
Closing this - as we've moved on and this can be handled separately if any further changes are needed.
