### ISSUE TITLE
Design Picker: Sometimes it would redirect to checkout page again

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#57595]
#### Steps to reproduce

1. Go to `/start`
2. Select paid plan
3. Complete the checkout
4. When you get to the Design Picker, select an option or skip

#### What I expected

Redirect to My Home

#### What happened instead

Sometimes you will redirect to the checkout page again and show that you don't have any items in your cart. However, it's not easy to reproduce this situation.

![image](https://user-images.githubusercontent.com/13596067/140023625-b8ce327d-f901-42a7-97be-67f2c5ff631a.png)

**Comment by autumnfjeld** [comment]
@arthur791004  Do you think we can close this?  Or would it be good to flag with Team Vertex for their work pdDR7T-1l-p2

**Comment by arthur791004** [comment]
I think we could close it as there is no related report for a long time.
