### ISSUE TITLE
Professional mail password field Italian error message translation issue

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#57601]
### Quick summary

The password field when signing up for Titan mail has a minimum 10 character limit, the error message in Italian is incorrect (it says the opposite).

### Steps to reproduce

1. Set your WordPress.com account to Italian
2. Start adding Professional mail: Upgrades > Emails
3. Try a password less than 10 characters, view error message

### What you expected to happen

Translation should say it can't be "shorter than" 10 characters.

The error message in English:

>This field can't be shorter than 10 characters.

![Screen Shot on 2021-11-03 at 09:20:17](https://user-images.githubusercontent.com/10353785/140068232-8dfd8c1f-cce9-4fb5-b7de-d0b2f23363dd.png)

### What actually happened

When your account is set to Italian the message says the opposite:

>Questo campo non può contenere più di 10 caratteri.

Translation:

>This field cannot contain more than 10 characters. 

![Screen Shot on 2021-11-03 at 09:19:43](https://user-images.githubusercontent.com/10353785/140068281-eff7d5cd-be8d-4d7b-a966-1688d8390a54.png)

### Context

4425947-zd-woothemes

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

This shouldn't stop a user from signing up if they try a long enough password, but the message is incorrect so they might not try that.

**Comment by emilyaudela** [comment]
I have updated this in GlotPress from "più" to "meno", so it says "less than 10 characters" instead of "more than 10 characters".

<img width="430" alt="Screen Shot 2021-11-05 at 4 38 38 PM" src="https://user-images.githubusercontent.com/36699353/140537608-34f1fb0e-1495-4ce3-a239-7788a7895889.png">
