### ISSUE TITLE
Stats link in Customize Toolbar redirecting incorrectly to Editor page

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/wp-calypso#57641]
### Quick summary

Stats link in the Customize Toolbar redirects incorrectly to the Editor page URL.

### Steps to reproduce

1. Go to `cristiankuhn.wordpress.com`
2. Scroll down the homepage until the floating Customize Toolbar appears (bottom right corner)
3. Click on (or hover) the Stats link
4. I am taken to the Editor link (and not the Stats page)

### What you expected to happen

I expected to be taken to the Stats page which is [https://wordpress.com/stats/day/cristiankuhn.wordpress.com](https://wordpress.com/stats/day/cristiankuhn.wordpress.com)

### What actually happened

I am redirected to the Editor link: [https://wordpress.com/page/cristiankuhn.wordpress.com/5](https://wordpress.com/page/cristiankuhn.wordpress.com/5)

### Context

<img width="1536" alt="Markup 2021-11-04 at 20 26 30" src="https://user-images.githubusercontent.com/7424885/140298852-832b5fa1-bdc9-4126-a898-d29f7a875147.png">

I've also tested on my simple sites with the same results.

### Operating System

macOS

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple, Atomic or both?

Simple

### Available workarounds?

Yes, easy to implement

### Workaround details

Users should log into WP.com, then access their Stats page from the main menu within their Dashboard.

**Comment by blackjackkent** [comment]
Nice catch - I've opened a diff to fix this at D69646-code

**Comment by blackjackkent** [comment]
This fix has been deployed! @adelineyaw please let me know if you're still seeing any issue with it. :)

**Comment by Robertght** [comment]
Hey @blackjackkent!

Now it redirects me to the specific page/post stats. Is this the intended behavior?

**Comment by blackjackkent** [comment]
That is the behavior that it had previous to the bug being introduced, so that was the fix I implemented, yes. Obviously it can be further changed if needed though. 🙂

**Comment by Robertght** [comment]
Thank you @blackjackkent ! 

I'm going to mark this one as fixed for now.

**Comment by adelineyaw** [comment]
Thank you @blackjackkent! I've checked the user's site (PchyB6-5-p2) and now only the three dots icon is shown and the Customize, Edit and Stats links are no longer visible. Is this to be expected with the latest fix?


<img width="261" alt="Markup 2021-11-06 at 20 43 14" src="https://user-images.githubusercontent.com/7424885/140605334-9af155e1-9370-47a6-a8b6-e89e45f763a3.png">

On other test sites, there should be a pencil icon to indicate the edit options (ie. Customize, Edit and Stats).

Follow up: 4428691-zen

**Comment by adelineyaw** [comment]
Closing issue as user replied 4428691-zen saying their Stats are working fine again.
