### ISSUE TITLE
Videos UI: Make the My Home card first in the display sequence.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57663]
Let's make the My Home card first in the display sequence. First we'll need to verify that the cards we're bumping aren't important calls-to-action that would affect revenue, or cards that are part of ongoing A/B testing.

**Comment by kwight** [comment]
Ping martech for some background.

**Comment by blackjackkent** [comment]
I made a post on Martech's P2 at pau2Xa-3Bb-p2 asking for their feedback on this change. I've opened a diff at D69835-code which should implement the change, but it should not be merged until we've heard back from MarTech appropriately.

**Comment by andres-blanco** [comment]
Closed by: D69835-code
