### ISSUE TITLE
Media & Text block: Allow more freedom to use different image-related blocks

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#57664]
### What

Allow to convert Media part of the Media & Text block into other Media related blocks like the Image Compare block

### Why

To allow more flexibility:

>we can make it so that the blocks can be more dynamic like that. You can mix them and stuff

32569003-hc

**Comment by Greatdane** [comment]
Closing - it is already possible to transform the media section of this block to an image - once transformed to an image, it can be then transformed further. 
(due to the way image-compare works, it cannot be transformed into any other type of image block)
