### ISSUE TITLE
[Bug]: Zoologist "Replace my homepage content" preview is misleading

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#57670]
### Quick summary

If I switch to a theme that displays posts on the Home page and select to use the theme's content, the preview shows looks different that the result.

**Preview**

<img width="350" alt="Screen Shot 2021-11-04 at 13 28 10" src="https://user-images.githubusercontent.com/1699996/140401187-46f21f07-fe1e-486f-a84a-d99df106574c.png">

**Result**

<img width="400" alt="  " src="https://user-images.githubusercontent.com/1699996/140401214-e9476e8b-8f45-4aba-85d8-cb3b46b9d46c.png">

### Steps to reproduce

- On a site with one or more posts, activate the Zoologist theme
- When prompted, select "Replace my homepage content..." before activating the theme
- After the new theme is activated, view the Home page of your site

### What you expected to happen

My homepage would look like the preview.

### What actually happened

It doesn't look like the preview, because it's using my posts rather than the sample content.

I think it's reasonable to _not_ replace my content with sample posts (which would be odd), but I'd expect to see that reflected in the preview before I switch. Maybe this can be addressed by using my posts in the preview, rather that the sample content?

### Context

Related to #57133

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

This may be higher severity, now that we are using Zoologist as the default theme for new sites.

**Comment by fushar** [comment]
We have removed the preview from the modal (as it is often misleading). See:

- #77881

To compensate this, we will implement a real "Live Preview" button. See:

- #79219

Additionally, we also have fixed the theme switch logic so that it will always set the correct homepage for Zoologist. See:

- #79167

With that, we'll close this issue. Cheers! cc: @Automattic/lego
