### ISSUE TITLE
Domains: Redirect secondary domains to a specific page or URL

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#57680]
### What

Customer wants to redirect secondary domains to a specific page or URL of the primary domain

### Why

This came up before in

p7DVsv-6DY
p7DVsv-6Ir 
pKdGS-1Ow

but I don't see this in GitHub. So making this feature request here via Bugomattic.

User report: 4430312-zen

**Comment by happychait** [comment]
A customer asked about it in 33878296-hc

**Comment by goblinartificer** [comment]
Very big +1. Twice this week I've been in the position of explaining that something pretty basic at most registrars is something we can't do here, and people have very reasonably been confused about why it would be _harder_ to do this by purchasing a domain here than by purchasing one elsewhere. I feel embarrassed having to explain it!

**Comment by goblinartificer** [comment]
and again in 33816111-hc

**Comment by rw-ye** [comment]
Another customer asking about it here: 19814760-hc

**Comment by cuemarie** [comment]
Requested here: 35550279-hc

**Comment by Greatdane** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/53027

Moved requests over to the other issue.
