### ISSUE TITLE
DevDocs: Update references to wpcalypso.wordpress.com

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/wp-calypso#577]
We're still linking to some private documentation on `wpcalypso.wordpress.com`, for example in [components's README.md](https://github.com/Automattic/wp-calypso/blob/master/client/components/README.md), we're linking to https://wpcalypso.wordpress.com/devdocs/design which is private. EDIT: Just requires login actually.

_[Reported on Hacker News by vineet](https://news.ycombinator.com/item?id=10617314)_

**Comment by rralian** [comment]
But `/devdocs/design` isn't meant to be private is it? I was about to file an issue that this page should not require a login... oh... unless some of the components require a logged-in user to render them. Is that the case @nb?

**Comment by lancewillett** [comment]
It's not private — just requires a valid login, right?

**Comment by mtias** [comment]
Not meant to be private, though we could also tweak the link to point locally. We don't have a canonical "demo" resource defined.

**Comment by Viper007Bond** [comment]
> It's not private — just requires a valid login, right?

You're right! Of course it requires being logged in because it's Calypso-powered. Oops. :)

However we should probably move it somewhere where it can be seen without a login.

**Comment by mtias** [comment]
That's outside of the fact some component currently require user/site data to render.

**Comment by vineet-sinha** [comment]
For large parts of the web, 'requires login' = is private.

I am not suggesting that this is a high priority bug, but it is easier to place bets on tools that line up with the open web.

**Comment by nb** [comment]
@vineet-sinha it’s more of a technical issue than a philosophical one. As @mtias mentioned, some of the components there may require user data. We’d love to make it available without login. And of course, you can access the same functionality if you [run Calypso locally](http://www.markforrester.co.za/2015/11/04/automattic-grand-meetup/#) and open `/devdocs/design` there.
