### ISSUE TITLE
Welcome Tour showing behind "Your first post is published" modal

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57702]
# Description
 In new Blogger/Write flow: Welcome Tour appeared 

![image](https://user-images.githubusercontent.com/5665959/140522265-e3af348a-c2b3-4f8e-b934-4025522f54f1.png?width=200)

### Steps to reproduce
* Go through Blogger Flow from intent screen: 
* click write > 
* Blog name > 
* Draft First post > 
* Land in editor > 
* Write stuff in the editor > 
* click Publish  > 
*  **NOTE: The "first post is published" modal appears and immediately after so does the Welcome Tour**

## What I expected to happen
To see only the "Your first post is published" modal and NOT the Welcome Tour

## What happened 
I saw both the  "Your first post is published" modal AND the Welcome Tour

### Related
A bug reported about the Welcome Tour appearing even  after dismissing it: https://github.com/Automattic/wp-calypso/issues/57660.  I don't think the cause of the issue reported above and #57660 are the same, but might make sense to tackle them together.

**Comment by arthur791004** [comment]
> Go through Blogger Flow from intent screen: click write > Blog name > Draft First post > Land in editor > Write stuff in the editor > click Publish >
> The "first post is published" modal appears and immediately after so does the Welcome Tour

Hmmm...I'm not sure it's a bug or not. In this flow, the Welcome Tour shows when you land on the editor. Should we need to hide the modal after "first post is published" modal appears and show it again after "first post is published" modal is close? Or you don't see the "Welcome Tour" at the beginning and it shows suddenly after you publish the post? (But I cannot reproduce this cases)

**Comment by autumnfjeld** [comment]
* Welcome Tour should NOT show behind any of the Blogger flow modals
* The Welcome Tour should NOT show in this  blogger flow which includes: Draft post modal > writing in the editor > clicking publish > seeing the congratulations "First post modal"  
* Nice to have: The Welcome Tour could show on the 2nd time the blogger opens the editor, because in this case the modals will not show and there isn't the visual conflict. However we can make a separate issue for this, to do in the future.

If you can't reproduce the issue, we can just wait and see if anyone reports this again.

**Comment by arthur791004** [comment]
Okay. Let's wait and see if anyone encounters this again!

**Comment by roo2** [comment]
it looks like https://github.com/Automattic/wp-calypso/pull/57982/files is a potential fix, right @arthur791004. I couldn't reproduce it, but the theory that the iframe url was changing right after publishing  sounds plausible, I think we should deploy it and then see if this keeps coming up

**Comment by arthur791004** [comment]
Yep, it might be the potential fix. But I'm not sure it's the same situation or not.

**Comment by autumnfjeld** [comment]
I'll go ahead and close this.  We know to keep an eye out if it happens in the future.
