### ISSUE TITLE
Cover Block Overlay – Color no longer applied when adding / editing Cover blocks

### ISSUE THREAD

**Issue by hanananah** [Automattic/wp-calypso#57711]
### Quick summary

According to the [Cover Block support doc in the Overlay section](https://wordpress.com/support/wordpress-editor/blocks/cover-block/#overlay-color), the overlay color should default to grey. When adding new Cover blocks or editing existing ones, the overlay color is removed/unset and needs to be manually selected to add/restore overlay feature.

### Steps to reproduce

1. Open post editor (new or existing)
2. Add new Cover block

OR

1. Open post editor (new or existing)
2. Edit existing Cover block

### What you expected to happen

Overlay settings should default to grey color.

OR

Overlay settings should still hold previously set color.

### What actually happened

No overlay color is selected by default. Increasing / decreasing opacity setting affects cover block text, but not the image overlay.

Existing Cover blocks no longer hold previously set color, as color selected is somehow deselected.

### Context

#4431371-zen

### Simple, Atomic or both?

Simple, Atomic

### Available workarounds?

Yes, easy to implement

### Workaround details

The Cover block overlay color can be reselected in the block settings.

**Comment by Robertght** [comment]
Thank you for flagging this @hgwaltney !

I think this was changed in a previous release of Gutenberg as I can't replicate it with 11.7.1, but I can't pinpoint when was this changed.

cc @Automattic/flow-patrol-create 

I also asked here: p1636178892096800-slack-CBTN58FTJ

**Comment by sarahcada** [comment]
Adding another report at 4433797-zd-woothemes
For now the customer used the Overlay setting for each block in their newest post.

**Comment by filipanoscampos** [comment]
The user replied on this ticket: #4431371-zen
Unhappy with the suggested workaround. I tried to look for CSS to give a site-wide workaround but couldn't find any posts without the overlay.

I have asked the user to send an example and maybe we can look into a CSS workaround if the issue persists.

**Comment by benchilcote** [comment]
I responded as well to user in #4431371-zen.  They have thousands of posts on their site, so this issue affects them in a substantial way. 

Also - I did some of my own testing and was not able to reproduce the issue.  I created a test post on an Atomic site, added a cover block with a color overlay, and with nested paragraph and heading blocks, then published it.  After reloading the post on the front end and the post in the editor, the color overlay remained intact.

**Comment by AtrumGeost** [comment]
The user from 4431371-zd-woothemes shared a video and more details:

https://user-images.githubusercontent.com/3696121/140613889-cb270bfe-1fdd-478c-921b-e6ea01623a6c.mov


> I just clicked a random one Godzilla v. kong in science fiction and in the editor the filter on the blocks is gone brighter and the text is black for some reason
> 
> Yet when I click on the review from the non-editor section how a reader would see it like the 2nd part of the video shows it shows like normal how it’s supposed to with the dark filter and white text
> 
> So the problem is in the editor it’s removing the dark filter itself and making the text black and this is only a change happening in the last few days not over years I’ve been using the site

**Comment by LauraSWP** [comment]
Another case here, text color could not be changed 28161311-hc
Had to use a custom CSS class and a tempo CSS fix.

**Comment by WunderBart** [comment]
Created an upstream issue: https://github.com/WordPress/gutenberg/issues/36310

**Comment by donalirl** [comment]
Seen in #4440019-zen. The Cover blocks use the `is-style-hover-reveal` class on the Dalston theme. With the latest update, the overlay is faded grey by default. Before, the overlay appeared faded only on hover.

### Before (normal behavior):
![normal hover](https://user-images.githubusercontent.com/30727666/140834472-bc4a4af4-f0dc-4364-9d99-d6137aa9ba7e.gif)


### After (with the bug making it always appear faded):
![Screen Recording 2021-11-09 at 10 18 56 13 AM](https://user-images.githubusercontent.com/30727666/140834498-5d0f3cc4-72a7-4020-9c9e-387e531dddb6.gif)

**Comment by sajmes** [comment]
Another report here: 32646497-hc

Text color was also affected but using the highlight option in the block settings allowed us to set the text color properly.

**Comment by cometgrrl** [comment]
This issue is tracking an issue in another repository. All +1's of end-user reports should be done on this issue, while any discussion related to the issue itself and its fix should be done on the issue in the outside repository.

**Comment by paxblueribbon** [comment]
reported in zd-4439451

**Comment by AtrumGeost** [comment]
Got another report of a website with the Dalston theme having issues with the `is-style-hover-reveal` cover block style:

4441395-zd-woothemes

We have another issue possibly related:

p9cu9o-34L-p2

**Comment by cuemarie** [comment]
Another possible instance here: 30507333-hc

**Comment by bobmatyas** [comment]
Another report: 4441977-zen

**Comment by eduardozulian** [comment]
Another report: 32665748-hc 

For my case, the following CSS helped me force a 0 opacity to the cover block image while changing it to .8 when we hover over:

```
.wp-block-cover.is-style-hover-reveal .wp-block-cover__gradient-background.has-background-dim {
  opacity: 0;
}

.wp-block-cover.is-style-hover-reveal:hover .wp-block-cover__gradient-background.has-background-dim {
  opacity: 0.8;
}
```

**Comment by bobmatyas** [comment]
Another report: p1636470933430900-slack-C03TY6J1A

**Comment by bobmatyas** [comment]
Another report: 4431371-zd-woothemes

**Comment by emilyaudela** [comment]
Many theme demos have also broken causing low color contrast, especially the contact sections. For example, in [Maywood demo](https://maywooddemo.wordpress.com/):

<img width="400" alt="Screen Shot 2021-11-10 at 5 36 50 PM" src="https://user-images.githubusercontent.com/36699353/141154369-0b6134ce-64d7-42c3-86d8-bef58060d32a.png">

**Comment by AtrumGeost** [comment]
That's odd! Not sure if related to current issues on the Cover Block:

https://github.com/Automattic/wp-calypso/issues/57711

**Comment by JoshuaGoode** [comment]
Encountered on 4445479-zd-woothemes

Provided user with some CSS to get all of their cover blocks back to the default 0.5 opacity. 

User will want an update when this is fixed and when they can remove the custom CSS.

**Comment by kylemcph** [comment]
Another report on #4447491-zen. I asked them to wait for the Gutenberg 11.9 release which should fix this per https://github.com/WordPress/gutenberg/issues/36274.

**Comment by kavyagokul** [comment]
Another one in 31681229-hc

Told them to wait for the 11.9 update and shared some workaround css with them

**Comment by Rahii9** [comment]
Another report received on 32701393-hc

Temporary fix provided.

**Comment by filipanoscampos** [comment]
Another case of this bug here: 32699872-hc.

I followed up via ticket 4449926-zd-woothemes and provided CSS workaround.

**Comment by jamiepalatnik** [comment]
Possibly related: 32720468-hc
Making a change, then resaving the page resolved the issue. No follow-up needed.

**Comment by Greatdane** [comment]
Another: 32734720-hc

**Comment by freelylovinglife** [comment]
Another report - 4456677-ZD The issue is with a contact form field text that changed to black font.

**Comment by eduardozulian** [comment]
Another report in 32535221-hc. I shared a generic CSS with them.

**Comment by WunderBart** [comment]
> Another report on #4447491-zen. I asked them to wait for the Gutenberg 11.9 release which should fix this per [WordPress/gutenberg#36274](https://github.com/WordPress/gutenberg/issues/36274).

This regression will actually be fixed via another PR: https://github.com/WordPress/gutenberg/pull/36406. It will most probably be included in a v11.9.x patch release as the v11.9.0 has already been released. We're currently in the middle of the v11.9 upgrade in WPCOM, so please follow the [tracking issue](https://github.com/Automattic/wp-calypso/issues/57451) for more info. /cc @fullofcaffeine @chad1008  @glendaviesnz

**Comment by AtrumGeost** [comment]
Another report here:

32766296-hc

Asked for some CSS help

**Comment by kathrynwp** [comment]
Here's the CSS workaround I provided for the above interaction, which can be targetted to specific pages if needed. With a custom CSS class added to only specific cover blocks, it could also be adjusted to target only those.

```
.wp-block-cover img.wp-block-cover__image-background {
  opacity: 0.5;
}
```

**Comment by desnum** [comment]
Another case here: 30464893-hc
User had a Personal plan, so I manually re-adjusted the overlay and text colors in the editor.

**Comment by wprhunt** [comment]
Same as 30464893-hc
I found that for form blocks in the cover block, since they don't have color options the solution is to select the column block they are in and set the text color for the column to white:
![Edit Page ‹ — WordPress com 2021-11-16 15-29-26](https://user-images.githubusercontent.com/16481427/142069439-2a6ce02b-a9c6-4764-be3e-2c32dd7cbe25.jpg)

**Comment by essleeung** [comment]
Adding another report - 31707985-hc 
User is using Alves theme.
User has decided to edit to different backgrounds for now instead of getting a temp CSS fix. 
Please notify user when fix has been released.

**Comment by WunderBart** [comment]
> > Another report on #4447491-zen. I asked them to wait for the Gutenberg 11.9 release which should fix this per [WordPress/gutenberg#36274](https://github.com/WordPress/gutenberg/issues/36274).
> 
> This regression will actually be fixed via another PR: [WordPress/gutenberg#36406](https://github.com/WordPress/gutenberg/pull/36406). It will most probably be included in a v11.9.x patch release as the v11.9.0 has already been released. We're currently in the middle of the v11.9 upgrade in WPCOM, so please follow the [tracking issue](https://github.com/Automattic/wp-calypso/issues/57451) for more info. /cc @fullofcaffeine @chad1008 @glendaviesnz

The fix was included in the [v11.9.1 patch release](https://github.com/WordPress/gutenberg/releases/tag/v11.9.1) and it should be deployed to Simple and Atomic sites later today.

**Comment by Gustavo-Hilario** [comment]
Another report here: 4466102-zd-woothemes

**Comment by inaikem** [comment]
@WunderBart, would you be able to help us confirm if the fix was deployed as expected? 

Taking 4449926-zd-woothemes as an example, I'm seeing the correct `has-background-dim-XY` set on their homepage cover blocks, however, the opacity is still set to 0.5 regardless of their editor settings:

- Cover block 1: Editor opacity at 70%
- Cover Block 2: Editor opacity at 30%
- Cover Block 3: Editor opacity at 20%
- Cover Block 4: Editor opacity at 60%
- Cover Block 5: Editor opacity at 30%
- Cover Block 6: Editor opacity at 32%

I should note that I'm unable to replicate this particular issue on a test site.

Thanks for your help!

@Automattic/bug-herders, I've added this to our bulk reply queue for us to deal with when we have a confirmed fix! 🙏

**Comment by essleeung** [comment]
Another case of Dalston blocks having the opacity set by default, instead of only on hover.  32849972-hc
<img width="1303" alt="Screenshot 2021-11-22 at 11 20 02 AM" src="https://user-images.githubusercontent.com/39225086/142796328-3ac82d3d-b4f4-4717-8ceb-b2874979535d.png">

Please contact the user when fix is complete. F/U ticket here: 4535296-zd-woothemes

**Comment by eduardozulian** [comment]
It appears that this issue is also affecting the Group Block.

- 32821733-hc.
- Theme: Twenty Twenty (something is forcing an `!important` in `.has-primary-color`.
- CSS workaround:

```
/* Cover Block: temp fix for 57711-wp-calypso-gh 32884974-hc (EZ) */
.wp-block-cover__inner-container .has-primary-color,
.wp-block-group__inner-container .has-primary-color {
  color: #000 !important;
}
```

**Comment by kathrynwp** [comment]
Ran into this in 30888354-hc

Showed how to use the Highlight tool to make the text on the cover block white that way.

**Comment by paxblueribbon** [comment]
Had something similar in 32927342-hc / 4548270-zd

They don't have the Cover Block at all though, they have the group block.  Not sure if this is the same bug or not.

**Comment by eduardozulian** [comment]
@pbking as you mentioned in https://github.com/Automattic/themes/issues/5011, do you believe that this issue is also part of a larger problem?

**Comment by freelylovinglife** [comment]
Another report 4549872- ZD

**Comment by stronenv** [comment]
The issue seems to be resolved for 4449926-zd-woothemes :

- Color changes are saved and displayed correctly on the page and in the Editor.
- Opacity changes are saved and displayed correctly on the page and in the Editor. 

Unsure which release actually did the fixing since 4449926-zd-woothemes has been on hold for a while.

**Comment by TeniCola** [comment]
Another report in 30053228-hc -- white default text in the editor view, but dark grey on live site, which made it illegible against the background.

I advised the user that the workaround solution was to manually apply the text color to their blocks inside the Cover block.

**Comment by jordesign** [comment]
Another interaction from #4448278-zd

**Comment by WunderBart** [comment]
> @WunderBart, would you be able to help us confirm if the fix was deployed as expected?
> 
> Taking 4449926-zd-woothemes as an example, I'm seeing the correct `has-background-dim-XY` set on their homepage cover blocks, however, the opacity is still set to 0.5 regardless of their editor settings:
> 
> * Cover block 1: Editor opacity at 70%
> * Cover Block 2: Editor opacity at 30%
> * Cover Block 3: Editor opacity at 20%
> * Cover Block 4: Editor opacity at 60%
> * Cover Block 5: Editor opacity at 30%
> * Cover Block 6: Editor opacity at 32%
> 
> I should note that I'm unable to replicate this particular issue on a test site.
> 
> Thanks for your help!
> 
> @Automattic/bug-herders, I've added this to our bulk reply queue for us to deal with when we have a confirmed fix! 🙏

Sorry for the late reply, totally missed your ping, @inaikem! 🙈 AFAIK, the fix has been deployed as expected. Although, since the markup of the Cover block has changed, similar issue(s) might be appearing for some themes that provide customized styles for the Cover block. Would you be able to verify if the reporting user uses a specific theme that it might be related to? /cc @chad1008

**Comment by carladoria** [comment]
Another report in [4638455-zen](4638455-zd-woothemes)

**Comment by essleeung** [comment]
Another report here: 4722065-zd-woothemes
I wasn't able to replicate this on my test site. The user adds a cover block and it looks fine in the preview, but the live site shows opacity as 0.5-1.0 and you can't see the image underneath the overlay. 

| Expected      | Actual |
| ----------- | ----------- |
| <img width="1157" alt="Screenshot 2022-01-27 at 10 23 20 PM" src="https://user-images.githubusercontent.com/39225086/151378145-9f13535f-85f2-4a1b-b71c-04e6abaa181f.png"> | <img width="823" alt="Screenshot 2022-01-27 at 10 26 20 PM" src="https://user-images.githubusercontent.com/39225086/151378250-81aed14d-80ed-4bc7-b2b3-88c542e79402.png"> |

**Comment by glendaviesnz** [comment]
@essleeung I wasn't able to replicate this either. Is the issue visible on a public page on the users site?

**Comment by essleeung** [comment]
@glendaviesnz They had it set in their drafts for us to test and didn't want it on their live site.

**Comment by sguzovskaia** [comment]
User affected by the issue reported that the temporal CSS fix they were given is not working anymore.
hc-32839164/zen-4440019
Follow-up ticket zen-4821687

**Comment by janmckell** [comment]
Another user affected by this: 4895541-zen

Gave CSS code for a temp fix:
.wp-block-cover.is-style-hover-reveal .has-background-dim {
  opacity: 0;
  transition: .3s;
}

.wp-block-cover.is-style-hover-reveal:hover .has-background-dim {
  opacity: 0.6;
}

**Comment by ClassicRKR27** [comment]
I've got another instance here: 34895673-hc

**Comment by Robertght** [comment]
I have tested this with several themes, older and newer and I can't replicate this anymore. 

I'm closing this for now as per p1653547485419459-slack-C01UW7SB411, but please reopen if you encounter other cases.

cc @Automattic/dotcom-pa-group
