### ISSUE TITLE
Customization: Improve "customizer couldn't load" error message

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#5772]
If your internet blips or is super slow, the Customizer times out after 25 seconds and displays this message:

![2016-05-23-at-18-431](https://cloud.githubusercontent.com/assets/2846578/15765368/164c9d24-2902-11e6-98f5-e5c8c05b0223.png)

We can make this message more clear. How about something like this?

> We had some trouble loading the Customizer. Never fear, your site is still okay! We recommend trying to load the Customizer again.
> 
> [Try Again]
> 
> If you're still having trouble, [please get in touch with our support team].

Might be too frivolous. ¯_(ツ)_/¯

Props @karmatosed for reporting the issue internally.

**Comment by davidakennedy** [comment]
A few slightly shorter suggestions. Some of these may be too alarmist:

```The customization tools didn’t load.

Uh oh! The customization tools didn’t load.

Bummer! The customization tools didn’t load.

Looks like the customization tools didn’t load.```

I think we can cut the "still" from this as well: `Never fear, your site is still okay!`.
