### ISSUE TITLE
Unable to add new Text widget to a simple site

### ISSUE THREAD

**Issue by sharonlaker19** [Automattic/wp-calypso#57725]
### Quick summary

A user on [this site](https://classicalpianists.wordpress.com/) is unable to add new Text widgets.

We've tried both the Block and Classic widget editors but the changes don't stick.

### Steps to reproduce

1. Go to https://classicalpianists.wordpress.com/
2. Navigate to Appearance > Customize > Widgets and choose any sidebar option.
3. Add a new Text widget with a title and some example content.

### What you expected to happen

The title will stick after adding content to the text widget and you'll be able to save your changes and have them appear on the front end.

### What actually happened

Clicking to add content causes the text widget title to disappear, and when you save the changes without the title, the text widget itself disappears as well.

### Context

Other widgets seem to be saving okay, and I wasn't able to reproduce the issue on my test site with the same theme and site plan.

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

One

**Comment by sharonlaker19** [comment]
Ticket: 4433312-zen

**Comment by daria2303** [comment]
* cache clearing doesn't solve it

**Comment by IoanaAMuresan** [comment]
Hi, just letting you know that the customer reached out wondering how long finding a fix for this issue might take. They feel stuck in using their site - say they can't really advance without this feature... I replied with an apology and trying to buy some time - is there a timeline, or any other info on this?

**Comment by dpasque** [comment]
In the vein of trying to get the user up and going as quickly as possible... Would it be too disruptive to enable block widgets on their site? (It looks like its currently turned off for their site.) They should be able to accomplish what they need with either a Paragraph or HTML block in the block widgets, and they should be able to use the legacy widgets block if they needed for some backwards compatibility!

**Comment by daria2303** [comment]
Hi @dpasque we had tried it before but widgets are not visible in the editor (I believe I saw a bug like this already) but if clicked in the right place they appear, user's description: "I’ve waited several minutes and they won’t even load. All I see is a white screen where some grey spinning circles appear from time to time."

**Comment by Nic-Sevic** [comment]
Some additional info here: the user has 340 text widgets in their content sidebar along with 22 nav menu widgets in the primary sidebar. 

Could this be related to a memory issue tied to the significant number of widgets loading?

**Comment by filipanoscampos** [comment]
The user wrote back adding that although they have 340 text widgets, only one of each is set to display on any given page on the site.
They highlight that they were only able to edit their Wirdgtes with the Classic Editor and that, from Nov.5, changes are no longer being saved.

They also added that they suspect the number of widgets may be why the Block editor wasn't working as expected and asked if there is any hope the coming WordPress.com update scheduled for December 14th will solve this issue for them?

Thanks!

**Comment by Greatdane** [comment]
The user is back again asking for an update. 

I can see they are using the widgets as basically a secondary menu. I wonder if we can find a way/workaround to move the **content sidebar** widgets (all 340+ of them) to the menu section, thus reducing the widget load. I am not sure if this will then break the menu section though 😅. 

(cc: @dpasque)

**Comment by mriyazuddin** [comment]
I see user has a number of inactive widgets too. I'm asking them to remove those widgets and then try adding a new one.

**Comment by arcangelini** [comment]
I have been investigating this issue and it appears that it is only affecting this site. I have not been able to replicate this on another test site. Here is what I have found.

1. This is only affecting the Text widget on this site. **As a workaround** they should have no trouble using the CUSTOM HTML widget to continue building. I had no trouble adding a Custom HTML widget to the content sidebar while testing.
2. My initial thought is that there is some sort of limit that has been reached based on the quantity of the specific widget.
3. When you delete one of the currently working Text widgets and add a NEW text widget this functions properly. However, adding another in addition to that one results in the same trouble.

Here are the screenshots of the requests being sent with each save that I tested.

## Working text widget save
<img width="1212" alt="Markup 2021-11-30 at 20 44 17" src="https://user-images.githubusercontent.com/33258733/144118029-4675a5b1-0ccb-4dc1-aaa2-420ee46ccaca.png">

## Working Custom HTML widget save
<img width="533" alt="Markup 2021-11-30 at 20 48 08" src="https://user-images.githubusercontent.com/33258733/144118106-3a46f661-ef5d-4472-af4d-ad597224aa83.png">

## Broken NEW text widget save
<img width="658" alt="Markup 2021-11-30 at 20 45 38" src="https://user-images.githubusercontent.com/33258733/144118287-c26e09d6-a0a6-4688-8d48-9cb3874c58a6.png">

I will take a closer look tomorrow in hopes of narrowing in on what is specifically causing this.

**Comment by arcangelini** [comment]
I am still not seeing what is the issue here, but I would speculate they are being limited on how many of these widgets can be added. Maybe the next best step would be to try and replicate or duplicate the site to see if that is the case. In the meantime, they are welcome to use the Custom HTML widget or the Nav Menu widget as suggested before.

Closing for now, but please reopen if you are able to replicate this on other sites.
