### ISSUE TITLE
Zoologist as default: Styling for default theme doesn't match showcase

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#57723]
### Quick summary

When a new site is started with Zoologist (which is the default) the styling of fonts and colors doesn't match the showcase. It also feels a little messier than expected.

### Steps to reproduce

1. go to https://wordpress.com/start/
2. Start a site without selecting a theme - or by *specifically* selecting Zoologist
3. View site

Example site from this process:
PdvmeS-6-p2

### What you expected to happen

The general appearance of fonts and styling should match the theme demo 

### What actually happened

Font colors seem to be default blue for links - and the spacing feels too tight.

<img width="1104" alt="Screen Shot 2021-11-07 at 6 37 58 am" src="https://user-images.githubusercontent.com/1842363/140623977-fdd37f9c-8f41-40ec-83e5-bb430bd71d76.png">

In the Customizer I can confirm the colors are not set as per the demo
<img width="1557" alt="Screen Shot 2021-11-07 at 8 16 04 am" src="https://user-images.githubusercontent.com/1842363/140624007-0d49aedf-7287-4bcd-b8a5-9673c9a03130.png">

When adding a featured image (which isn't included in the initial setup) it looks a *little* better
<img width="813" alt="Screen Shot 2021-11-07 at 8 00 00 am" src="https://user-images.githubusercontent.com/1842363/140624042-b60a1f43-eebb-4100-8486-51e7680a6a9f.png">

I also noticed in the new Design Picker that the theme preview shows with the incorrect colors:

<img width="788" alt="Screen Shot 2021-11-07 at 8 04 55 am" src="https://user-images.githubusercontent.com/1842363/140624088-7736a4cb-6055-4f0f-908e-8861f4b20537.png">

### Context

General onboarding testing

### Operating System

macOS

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Zoologist

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

This won't be noticed by many users - as they will select other themes in the Gutenboarding Design Picker. But for those who have this trouble - HEs can help with a manual Headstart

**Comment by jordesign** [comment]
@alaczek @ianstewart @p-jackson Can you please take a look to see if anything Design Picker/Default theme is causing Zoologist to come through incorrectly?

**Comment by MaggieCabrera** [comment]
I don't know what's causing this. I could reproduce with the same steps you recommend and then if I switch to Quadrat or Geologist those work fine, but going back again to Zoologist breaks the styles of the theme again:

<img width="730" alt="Screenshot 2021-11-08 at 10 14 34" src="https://user-images.githubusercontent.com/3593343/140715319-ed372b9b-e0f8-4985-bc83-9ec2e53036a5.png">

About the color selection, beware that there's a known issue with the [customizer color preview](https://github.com/Automattic/themes/issues/4996).
