### ISSUE TITLE
WooCommerce blocks - Order by Menu not working

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#57727]
### Quick summary

When you add a sortable woocommerce block to a page and select order by menu order from the sidebar options, the order does not match the menu order

### Steps to reproduce

1. add any sortable woocommerce block 
2. select sort by menu order
3. see that some other order given

### What you expected to happen

the order should match the menu order in customizer

### What actually happened

settings in editor: 
![2021-11-07 at 11 42](https://user-images.githubusercontent.com/47717887/140640048-c85b41c3-ee05-48d7-b972-6bc5aa89427d.jpg)

order in menu:
![2021-11-07 at 11 44](https://user-images.githubusercontent.com/47717887/140640085-e42c99df-951c-4992-b96a-b7b1058d5768.jpg)

### Context

4434971-zd-woothemes

**Comment by Robertght** [comment]
Thank you for the report @Nic-Sevic ! I reported it further here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5138
