### ISSUE TITLE
FSE beta: Footer credit setting in Customizer not applied

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#57739]
The current footer credit setting in the Customizer is not reflected on FSE beta sites. 

Workaround: users must enable Site Editor, then manually edit or delete the block. 

We should find a way to make this consistent.

**Comment by formosattic** [comment]
+1 4437250-zd-woothemes

**Comment by MaggieCabrera** [comment]
781-gh-Automattic/wpcomsh should fix this, as far as I know this only fails on Atomic sites.

**Comment by aleone89** [comment]
Another report of this here hc-22181186

**Comment by Addison-Stavlo** [comment]
It looks like the footer credit settings between the customizer and front-end work, however the site editor's representation seems stale and disconnected from this system. 🤔

**Comment by Addison-Stavlo** [comment]
In testing the footer credit setting from the customizer is correctly applied to the front-end. I believe this was updated in wpcomSH and has resolved this discrepency.
