### ISSUE TITLE
Zooligist: reports of heading font changing

### ISSUE THREAD

**Issue by hideandgeek404** [Automattic/wp-calypso#57736]
### Quick summary

I have seen multiple reports of this but I put the other down to changes made by the user.

However, as this is the third I have seen I think it needs reported as a bug.

Reports suggest that, without any changes from the user, the headings on the Zoologist theme become smaller and less bold.

4434813-zen is one example of this.

### Steps to reproduce

I have been unable to reproduce this further than seeing it on sites where it has changed however there are some steps below that I have tried.

1. Installed new site choosing Zoologist at site creation
2. This then seemed to reproduce the issue reported on 57723-gh-Automattic/wp-calypso where the fonts are incorrect to the showcase
3. Nothing I changed including font choice has caused the headings to change. 
4. Something I did notice though is that on my brand new site, the headings had an inline style of font-size: 64px which was not present on the affected site.

### What you expected to happen

The headings should not have changed in size and should match the showcase

### What actually happened

Headings are much smaller (28px) and seem to align to a font setting var(--wp--preset--font-size--large)

### Context

4434813-zen

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Zoologist

### Reproducibility

Intermittent

**Comment by Greatdane** [comment]
This might have been fixed by https://github.com/Automattic/themes/pull/5004

The user also replied saying the titles are suddenly back to normal without changing anything, so marking this as closed for now.
