### ISSUE TITLE
Plugin Details: Add star icons to plugin rating info

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#57746]
Update the Plugin Details page to show the rating information with stars next to the rating value.

### Demo

<img width="160" alt="Screen Shot 2021-11-08 at 10 25 31" src="https://user-images.githubusercontent.com/5039531/140759289-618a5435-1933-4b12-920e-ba4276e879b9.png">

### Position

<img width="668" alt="Screen Shot 2021-11-08 at 10 26 26" src="https://user-images.githubusercontent.com/5039531/140759474-ab57ddc6-b043-48c3-8086-a4fdae4e897c.png">

**Comment by cpapazoglou** [comment]
Let's move the Ratings component we already have in the new plugin details page. We can later decide if we are using a static `yellow` color or theme-dependent color.
