### ISSUE TITLE
Marketplace: Taxes for paid products

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57754]
- Check whether we need to charge taxes for selling WOO extensions or any other product.
- Is there a mechanism that handles taxes automatically depending on billing address?
- Document the outcome.

**Comment by gcsecsey** [comment]
Reached out to the #tax-team on Slack, waiting for their response. p1637090095141100-slack-CPSFQ1KJR

**Comment by gcsecsey** [comment]
I've posted the findings in [this P2](pdt2If-z-p2), let's continue the discussion there.
