### ISSUE TITLE
Plugin Details: Check / add the USPs under the CTA for a free and paid plugin

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57759]
Designs oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A46946

- Add the USPs (unique selling point) to the plugin details page
- Refine the copy. Let's see if we can remove any billing period references so that they are more abstract and we reduce complexity

<img width="795" alt="SS 2021-11-18 at 12 28 31" src="https://user-images.githubusercontent.com/12430020/142398414-5b22e4db-5b9d-4192-b11f-e78f963fdfb9.png">

![SS 2021-11-08 at 17 19 02](https://user-images.githubusercontent.com/12430020/140768709-3730802b-b49b-4e72-802c-03e8be03cc95.png)

**Comment by cpapazoglou** [comment]
@emmnyc85 can you chime in here regarding the copy?

**Comment by emmnyc85** [comment]
Typo on the first bullet in the red box. Should read: "1 year of plugin updates" instead of "plugins updates"

**Comment by cpapazoglou** [comment]
> Typo on the first bullet in the red box. Should read: "1 year of plugin updates" instead of "plugins updates"

@emmnyc85, can we revise the copy so that it doesn't include the `1 year` so that we can use it both in yearly and monthly subscriptions?

**Comment by emmnyc85** [comment]
Good catch. Can the language dynamically adapt based on whether it's a monthly or annual plan, @cpapazoglou?

**Comment by cpapazoglou** [comment]
> Good catch. Can the language dynamically adapt based on whether it's a monthly or annual plan, @cpapazoglou?

Sure it can, I was just wondering whether we can simplify it. If not, we can code it so that it adapts based on the monthly/ annual switcher value.

**Comment by emmnyc85** [comment]
I looked a few other similar platforms for how they do this. Only woo is presenting these 'features' front and center. The length (i.e. 1-year) is probably redundant as it should be obvious you will get these items for as long as you are paying. So, we could remove them. If we want to maintain consistency with Woo, though, I think it's fine keeping them - FYI, @cpapazoglou

**Comment by cpapazoglou** [comment]
Scenarios:

**Low Tier Plan & Free Plugin**
<img width="277" alt="SS 2021-12-01 at 14 25 00" src="https://user-images.githubusercontent.com/12430020/144234002-4a813290-8c88-4465-96ac-f153c89b05d9.png">
- Show the domain USP only for FREE sites

**Low Tier Plan & Paid Plugin**
You get everything. @SaxonF, can you please advise here cause we are going to show 6 USPs in that case.
-  Show "Plan upgrade required".
- Show the domain USP only for FREE sites

**Premium Tier Plan & Free Plugin**
- Display nothing

**Premium Tier Plan & Paid Plugin**
<img width="280" alt="SS 2021-12-01 at 14 30 44" src="https://user-images.githubusercontent.com/12430020/144234783-a111fbac-76e4-4534-83f9-1a15727c551d.png">

**Jetpack & Free Plugin**
- Display nothing

**Jetpack & Paid Plugin**
<img width="280" alt="SS 2021-12-01 at 14 30 44" src="https://user-images.githubusercontent.com/12430020/144234783-a111fbac-76e4-4534-83f9-1a15727c551d.png">
