### ISSUE TITLE
Marketplace: Statistics for Marketplace Sales through WPCOM

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57762]
Provide an easy way to create reports for Marketplace products sold through WPCOM. Reports should include:
- site id
- user id
- current plan
- the plugin slug of the product bought

**Comment by gavande1** [comment]
My finding are described here: pdh6GB-9G-p2

**Comment by gavande1** [comment]
As per discussion with the team, we also need to have the following queries:

- share of each product between all active marketplace subscriptions. 
- number of sites with active marketplace subscriptions.
- have a price at the time of purchase in results

**Comment by cpapazoglou** [comment]
After preparing the the queries, let's connect with the Data team so that they prepare a scorecard for better visualization. We can later show Marketplace progress / performance by embedding this scorecard in our reports. 

Scorecards:
- Marketplace gross sales
- Marketplace active users 
- Number of Marketplace items sold

**Comment by cpapazoglou** [comment]
It would also be great aggregating which checkouts did occur a direct business plan upsell? In that case, the business plan will be included in the same receipt id as `wp-bundle-business-[interval]`

**Comment by cpapazoglou** [comment]
We shall not forget filtering out a12s from our queries.

Related convo: p1642080971039000-slack-C02JPCHEKDY

**Comment by cpapazoglou** [comment]
As per p1642483663013800-slack-C08JMM3LN

There are scorecards created for `wordpress-com` and `product=wp-marketplace`. 

For the time being reports attribute 100% in WordPress.com but this will be fixed to attribute 30% to WordPress.com and 30% to 3pd (including WooCommerce.com).
