### ISSUE TITLE
Blogger Flows: calypso_signup_start & calypso_signup_step_start  not firing as expected

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57779]
# Description
An audit of signup flows flow=onboarding and flow=setup-site showed that :
- [ ] calypso_signup_start[flow=onboarding] DID NOT FIRE
- [ ] calypso_signup_start[flow=setup-site] DID NOT FIRE
- [ ] calypso_signup_step_start [flow=setup-site, step=starting-point] DID NOT FIRE
- [ ] calypso_signup_design_preview_select DID NOT FIRE on the DP screen (in the intent=build flow)
- [ ] calypso_signup_select_design DID NOT FIRE on the DP preview screen (in the intent=build flow)

I recorded the event logging via Tracks Vigilante in this [doc](https://docs.google.com/document/d/1NnuDoHKPFA2OxGBSE2fxcyaJ6RgfUWGyMxudhiTRAig/edit#)

## Steps to reproduce
Starting from existing user with free site and no custom domain
Intent Screen > Click Write > Blog Name > Starting Point > Click Skip to My Home

It would be good to verify calypso_signup_step_start in all the branches and all the steps of the flow=setup-site.  Also making sure the `intent` and the `starting_point` props are included as needed to differentiate shared steps, like the Design Picker.

**Comment by arthur791004** [comment]
> Calypso_signup_design_preview_select DID NOT FIRE on the DP screen (in the intent=build flow)
> Calypso_signup_design_preview_select DID NOT FIRE on the DP preview screen (in the intent=build flow)

I'm not sure but I think this one should be `calypso_signup_select_design` when you click `Start with Shawburn` and `calypso_signup_design_preview_select` when you click `Preview Shawburn`. Also, I think we cannot rely on Tracks Vigilante as I found that sometimes I can see the event fired via it but sometimes I can't. So, I think validating the events via Devtool Network Tab would be better.

Maybe the problem might be [here](https://github.com/Automattic/tracks-chrome-extension/blob/30fed0939e7cb45b1135477d8b0f7a93d8b34aef/Tracks%20Vigilante/service-worker.js#L40). `Tracks Vigilante` relies on `webRequest.onCompleted` event and set to storage. But if the two events fired at the same time, one of them might be gone. As they got the same `url_array`, the data would be overwritten by the latter one.

## Network 

calypso_signup_start[flow=onboarding] DID NOT FIRE
![image](https://user-images.githubusercontent.com/13596067/140852303-4e439dbe-7c4e-4275-a3e3-03c4523aad32.png)

calypso_signup_start[flow=setup-site] DID FIRE
![image](https://user-images.githubusercontent.com/13596067/140852367-787df9a0-f41c-4677-a5ac-a8be90414157.png)

calypso_signup_step_start [flow=setup-site, step=starting-point] DID FIRE
![image](https://user-images.githubusercontent.com/13596067/140852457-a9b5dfc5-e5f5-4c40-a081-6c24243f4fa5.png)

calypso_signup_select_design DID FIRE on the DP screen (in the intent=build flow)
![image](https://user-images.githubusercontent.com/13596067/140853455-e987c7a1-52d9-4db3-aa8e-7bd1294d72ac.png)

calypso_signup_design_preview_select DID FIRE on the DP preview screen (in the intent=build flow)
![image](https://user-images.githubusercontent.com/13596067/140852529-22a85980-deb6-4850-9c98-bfd41c2d35a9.png)

## Tracks Vigilante

calypso_signup_start[flow=onboarding] DID NOT FIRE but sometimes I cannot see it fired via Tracks Vigilante
![image](https://user-images.githubusercontent.com/13596067/140854096-634d0b0b-b2ce-4352-94cc-5690a2bb4b06.png)

calypso_signup_start[flow=setup-site] DID FIRE
![image](https://user-images.githubusercontent.com/13596067/140853144-2d2acaf3-8c87-413a-8c33-4698df9fa236.png)

calypso_signup_step_start [flow=setup-site, step=starting-point] DID FIRE but sometimes I cannot see it fired via Tracks Vigilante
![image](https://user-images.githubusercontent.com/13596067/140853794-9d2e6c26-dff9-41ad-a9f3-c378fec044df.png)

calypso_signup_select_design DID FIRE on the DP screen (in the intent=build flow)
![image](https://user-images.githubusercontent.com/13596067/140853384-7d376f9c-d54d-44a8-89bf-29556b59a2db.png)

calypso_signup_design_preview_select DID FIRE on the DP preview screen (in the intent=build flow)
![image](https://user-images.githubusercontent.com/13596067/140852833-0cdb3f1b-0fe9-49e1-a6e4-94c6a732bedf.png)

**Comment by autumnfjeld** [comment]
> I'm not sure but I think this one should be calypso_signup_select_design when you click Start with Shawburn and calypso_signup_design_preview_select when you click Preview Shawburn. 

Yes, you are correct.  I meant calypso_signup_select_design

**Comment by autumnfjeld** [comment]
Thank you so much for investigating the Tracks Vigilante @arthur791004 !!

I did another audit, this time watching in the console.  I observed all the events firing, so that was good news.  I do have a request for adding props:

- [ ] Please add intent prop to **every event** that is firing in flow=setup-site.   This will make it 100% clear to people where events are firing and it will be especially important for all the design picker events.   And by **every event** I mean both the pre-existing calypso_signup_* events and all the events we have created for these flows. 


In the Figma ( 58MP46f44oGKl5Bin5bSp1-fi-0%3A1 ) I've put a star next to every event that is firing correctly with all the correct props.  

As more "intent" flows are built out (DIFM, Importers) I imagine the intent prop will be become critical to analytics, which is another reason to include it on every event that is firing.

**Comment by arthur791004** [comment]
As the following PRs are deployed, I think all of the `calypso_signup_*` events contain the `intent` now!

- [x] https://github.com/Automattic/wp-calypso/pull/57809
- [x] https://github.com/Automattic/wp-calypso/pull/57810
- [x] https://github.com/Automattic/wp-calypso/pull/57887

**Comment by arthur791004** [comment]
Close the issue as we verify the events as followed and they look good!
* https://github.com/Automattic/wp-calypso/issues/57488#issuecomment-971340391
* https://github.com/Automattic/wp-calypso/issues/57488#issuecomment-972359935
