### ISSUE TITLE
Stats: Ads section empty

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#57775]
### Quick summary

Right now it seems that any site's stats display may be completely blank for the ads section if they have WordAds enabled and are receiving impressions.

### Steps to reproduce

1. Navigate to My Site > Stats > Ads
2. Check for some data in the charge

### What you expected to happen

To see some data, even if it says zero

### What actually happened

It shows completely blank, even if there are impressions and earnings on the site.

<img width="1079" alt="Screen Shot 2021-11-08 at 1 13 13 PM" src="https://user-images.githubusercontent.com/31680407/140795611-144931fc-fbd6-4b34-8e9e-102adc3e35cc.png">

### Context

reported by customers in 

32630437-hc
27510796-hc
32629491-hc

Reproducible on any site I have right now

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by nicolynramos** [comment]
Another instance: 30105566-hc

**Comment by khristiansnyder** [comment]
Another in #4439332-zen

**Comment by mikeicode** [comment]
31464029-hc

**Comment by masperber** [comment]
31843892-hc

**Comment by nickpagz** [comment]
Got another...
32632296-hc

**Comment by KirkwallDay** [comment]
Two more instances:
4439219-zen
4439623-zen

**Comment by wprhunt** [comment]
One more:
31435975-hc

**Comment by happychait** [comment]
31692260-hc

**Comment by Gustavo-Hilario** [comment]
Another report here: 4439702-zd-woothemes

**Comment by happychait** [comment]
32581613-hc

**Comment by cuemarie** [comment]
26156839-hc

**Comment by thekingsprojects** [comment]
Another report from 17969185-hc

**Comment by KirkwallDay** [comment]
Another report here: 32633286-hc

**Comment by thekingsprojects** [comment]
And here 32631764-hc

**Comment by arinoch** [comment]
Reported as well in 21856637-hc.

**Comment by wprhunt** [comment]
Another two:
4439510-zen
4439749-zen

**Comment by formosattic** [comment]
+1 21022664-hc

**Comment by inaikem** [comment]
@Automattic/flowpatrol would you be able to help look into this? 

Noting 21 user interactions/reports documented up to this point over the past 8 hours.

Cc: @Robertght

**Comment by dev-sabbir** [comment]
Another instance here: 32364855-hc

**Comment by fashuvo** [comment]
Another report at #4440073-zen

**Comment by dev-sabbir** [comment]
Another one here: 29195223-hc

**Comment by dev-sabbir** [comment]
Another one : 32358032-hc

**Comment by retnonindya** [comment]
Another one: 19698301-hc

**Comment by Greatdane** [comment]
Another one: 32637274-hc

**Comment by pauloeaquino** [comment]
Encountered in 6206254-hc

**Comment by devNigel** [comment]
14937183-hc

**Comment by devNigel** [comment]
Got another chat: 31670045-hc

In this case, the earnings calculation is showing $0. The user says it used to be around $1.8. Though WordAds Admin shows $0 outstanding amount, it shows revenue earnings that sum up to around $1.8. Not sure if that is related to this bug.

**Comment by kavyagokul** [comment]
Also reported in 8289599-hc

**Comment by mrsjaved** [comment]
Another report here: 4438400-zd-woothemes

**Comment by mriyazuddin** [comment]
32638582-hc

**Comment by wprhunt** [comment]
One more for the pile:
4439865-zd

**Comment by dev-sabbir** [comment]
Another one here: 27592822-hc

**Comment by kuropixel** [comment]
Another one: 32173772-hc

**Comment by devNigel** [comment]
Another one: 25474705-hc

**Comment by flameslash** [comment]
Reporting this as well: 32639293-hc

**Comment by mrsjaved** [comment]
another one: 4433399-zd-woothemes

**Comment by Robertght** [comment]
4440701-zen

**Comment by Greatdane** [comment]
4439294-zd-woothemes

**Comment by Greatdane** [comment]
4439302-zd-woothemes

**Comment by tyxla** [comment]
I'm working on a fix.

**Comment by jromales** [comment]
+1 30678579-hc

**Comment by kylemcph** [comment]
4439034-zd-woothemes

**Comment by tyxla** [comment]
Fix here: https://github.com/Automattic/wp-calypso/pull/57814

**Comment by tyxla** [comment]
Just landed this one, it will be in production within the next 15 minutes.

**Comment by tyxla** [comment]
The fix is in production! Please feel free to ping me if you see anything suspicious that's related.

**Comment by Thelmachido** [comment]
Thank you for working on this, the same issue yesterday +22237175 -hc  

Edit::: Oh I can see the stats now, thank you

**Comment by inaikem** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/bug-herders are starting to work on email replies to affected users reported in this thread.

If you encounter any users still experiencing this issue. Please verify via support session and confirm they have cleared their cache before reporting the interaction here 🙏
