### ISSUE TITLE
Blogger Flow: hide floating FAB

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57787]
## Description
We want to hide the floating FAB in the Hero Flow onboarding screens.
This is high priority but NOT a blocker for shipping to users.

Slack decision making: p1636381518129000-slack-C029SB8JT8S
![image](https://user-images.githubusercontent.com/5665959/140817894-0269d23e-64c9-4ea8-ad14-8456eeb372d1.png)

Also, slack advice 😆 :
![image](https://user-images.githubusercontent.com/5665959/140818156-3cf8ac2e-1f31-4597-abc1-f97c3da6c6c5.png)

#### Steps to reproduce

1. Starting at Intent Screen
2. See FAB
3. See FAB on subsequent screens

#### What we want
To hide the FAB on all Hero Flow screens

Note that in the future we may want to include a "Need help?" link for users who have chose a paid plan. I will note this in the [Blogger Flow CfT Triage sheet.](https://docs.google.com/spreadsheets/d/1nFwbm8dhKIXTBpda-nMWjvIlOlK-ulcvLUfOIJfUIlM/edit#gid=0)

**Comment by arthur791004** [comment]
Do we also need to hide the FAB on the desktop? The reason that the FAB is higher than normal is that we don't have a better way to deal with the FAB and navigation bar stuck to the footer. Thus, we move up the FAB on the mobile 😅

**Comment by autumnfjeld** [comment]
@arthur791004  Removing the FAB is more about controlling the user experience (its not as much about the Visual aspect of the positioning of the FAB).   We intend for the Blogger flow to be a clear flow for the user, the purpose is to guide the user through a specific path and thus we can make an assumption that we don't need to show the help FAB. 

For now, we are making a decision to not show the FAB during the Blogger Flow.  It will show again in the Editor, so the user can access the help after the Write flow or the Blogger flow if they need help.

Let's remove it for both mobile and desktop.   Do you agree @ollierozdarz

**Comment by ollierozdarz** [comment]
@autumnfjeld I agree! Let's remove it!

**Comment by arthur791004** [comment]
Close this issue as https://github.com/Automattic/wp-calypso/pull/57989 has already removed the FAB.
