### ISSUE TITLE
Jetpack Download Stats not being tracked

### ISSUE THREAD

**Issue by benchilcote** [Automattic/wp-calypso#57781]
### Quick summary

Downloaded files are not being tracked and displayed in Jetpack stats under File Downloads.

### Steps to reproduce

1. Create a post or page and add a file block
2. Add a supported file to the block and publish the page or post
3. From another browser, while not logged in as Admin, click the download link and save a file to your computer

### What you expected to happen

I would expect the File Download stats to show 1 download for each instance a file is downloaded.

### What actually happened

The File Download stats remains blank no matter how many times I download files from my test page.

### Context

A customer discovered this and reported it.   I tested this using both an mp3 and pdf file.  While my visits to the website are tracked, multiple downloads of each file were not tracked.  At least one other person tested this with the same result. 

4438206-zen

### Reproducibility

Consistent

**Comment by the-misha** [comment]
Another user report: 29967624-hc

**Comment by thekingsprojects** [comment]
Another report here: 32631632-hc

**Comment by AtrumGeost** [comment]
We got another report here:

4438599-zd-woothemes

**Comment by jordesign** [comment]
With some checking - can confirm that the file downloads *are* being tracked by the system/API. The issue appears to be in pulling that information *in* to Calypso

**Comment by dcoleonline** [comment]
Also in 4440039-zen 

They mentioned that their Search Terms went missing too. I'm not sure if anyone else has seen the same.

**Comment by TeniCola** [comment]
Another case in 4439391-zen -- I advised them of the ongoing report, they may ask for a follow-up once this is resolved.

**Comment by inaikem** [comment]
Closing in favour of #57782.

**Comment by inaikem** [comment]
@Automattic/bug-herders, Adding this to our bulk reply board. Interaction links from #57782: 32631632-hc

**Comment by kuropixel** [comment]
22007823-hc for simple site. "No files downloaded" showing in dashboard and stats also none showing for previous months.

**Comment by KokkieH** [comment]
Another in https://wordpress.com/forums/topic/download-stats/?view=all

**Comment by KokkieH** [comment]
Update: The user reported they're back now, and when I checked stats for [another site someone reported the issue on](https://wordpress.com/forums/topic/download-stats-gone/?view=all#post-3757011), I can now see them there as well. So this issue might have resolved on its own.

**Comment by inaikem** [comment]
Resolved by #57814. Thank you for confirming, @tyxla!

 @Automattic/bug-herders are starting to work on email replies to affected users reported in this thread.

If you encounter any users still experiencing this issue. Please verify via support session and confirm they have cleared their cache before reporting the interaction here 🙏

**Comment by kerrynicl** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/bug-herders have finished following up with affected users reported in this thread.

Thanks for all the reports!
