### ISSUE TITLE
Sidebar: Stats calendar arrows show over sidebar on small screen

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#5778]
#### Steps to reproduce
1. Open site stats on any site
2. Reduce width of window so the sidebar disappears (becomes an overlay)
3. Open sidebar
#### What I expected

Sidebar shows up without any problem
#### What happened instead

Stats's calendar arrows pop over the sidebar (see screenshot). The arrows are clickable, which causes the calendar to change in the background.
#### Browser / OS version

Firefox 46.0.1 / OS X 11.11.5

Works fine on Chrome. 
#### Screenshot / Video

![screen shot 2016-06-03 at 09 24 23](https://cloud.githubusercontent.com/assets/184938/15770584/8915600a-296d-11e6-9e1c-3da0ef8f6dbb.png)

**Comment by timmyc** [comment]
I can no longer reproduce this issue on `master` closing out.

**Comment by timmyc** [comment]
Scratch that, missed the "Firefox" part :) - still an issue and will clean up for hackday.
