### ISSUE TITLE
Chat Warning for WP-Admin: Showing Incorrectly

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#57780]
### Quick summary

We've been hearing reports from customers that they are unable to scroll down in some pages or sections of their dashboard if they are in chat, and were finally able to pin it down to this warning we added when someone tries to go to wp-admin, I believe it was this: https://github.com/Automattic/wp-calypso/pull/50236

However, this is displaying without the customer clicking any wp-admin links. We have seen this on the Purchases page, Plans page, and Activity Log for the ones we can reproduce.

### Steps to reproduce

1. Start a live chat with WordPress.com support
2. Navigate to the Plans page or Activity Log

### What you expected to happen

just for it to open that page

### What actually happened

The page opens, seems to freeze a little, and stops letting you scroll down. Then it shows this warning:

<img width="969" alt="Screen Shot 2021-11-08 at 2 06 16 PM" src="https://user-images.githubusercontent.com/31680407/140804444-235c0fdd-1d8f-4d1e-a7cf-e2580be56daa.png">

That particular page is https://wordpress.com/plans and nothing was clicked on the page yet when the warning popped up

### Context

Customer reports

### Simple, Atomic or both?

Simple, Atomic

### Other notes

The customer has to be in live chat, so it may be difficult to reproduce. We can't tell how many people it's affecting yet, but have been getting the reports that customers are having trouble scrolling down for a few days. However, once we got someone in chat, it was easily reproducible on a random site.

In addition to it popping up seemingly at random, the Continue button seems to take them to a random page. So far we have seen it bring us to AMP settings or Crowdsignal plugin settings.

### Severity

Some (< 50%)

**Comment by katiebethbrown** [comment]
I have had three reports:

32630994-hc

15611464-hc

32348799-hc

**Comment by klimeryk** [comment]
Thanks for creating the issue and the detailed description, @msilbers! It seems I misunderstood the nature of the issue in the beginning, but it's clearer now. I'm looking into it right now, as the stats after the weekend clearly show there's been some sort of change that triggered this behaviour (and I can easily reproduce it).

**Comment by klimeryk** [comment]
@mmtr, I think your PR https://github.com/Automattic/wp-calypso/pull/57642 introduced this regression, could you please have a look? This is a high priority issue and the number of affected users (and HEs) are rising 🙇‍♂️

**Comment by mmtr** [comment]
Thanks for the ping @klimeryk. It was indeed caused by that PR, so I reverted it since it as a low priority change. The issue should be fixed now. Will investigate what was the underlying issue afterwards.

**Comment by klimeryk** [comment]
Thanks for the quick revert! ❤️
