### ISSUE TITLE
Verticals: Add management UI to MC tool

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#57788]
Add a "Manage" tab to the UI where we show existing images stored for each vertical (will depend on #57785) and a button to delete them from the storage site.
D69884-code

**Comment by sixhours** [comment]
This was partially added in r234736-wpcom D69815-code

**Comment by sixhours** [comment]
Delete button functionality is in progress.

**Comment by nelsonec87** [comment]
Added remove functionality on D69884-code
