### ISSUE TITLE
Jetpack Stats: File download stats missing from Stats and Insights

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#57782]
### Quick summary

The "File downloads" section of the Stats and Insights page on Simple sites shows "no files downloaded", even when there should be downloads/were downloads visible. This happens when viewing today's stats as well as previous days/years/etc..

### Steps to reproduce

1. Log into a WordPress.com Simple site (Personal, Premium, etc.) that has had files downloaded in the past
2. Check the "File downloads" section
3. View the stats for a previous date or span (several days back, stats for 2020, etc.)
4. Check the "File downloads" section

### What you expected to happen

The File downloads section should show a list of files that have been downloaded, along with the number of times each has been downloaded.

### What actually happened

The section shows the message "No files downloaded", even if there were previously downloads made.

### Context

Reported in 32631632-hc

Screenshot (blurred) of the customer's stats from 2020 as an example—most other stats seem to be fine and have content, but File Downloads is empty.

<img width="1053" alt="Customer's Jetpack stats—File downloads stats section shows 'no files downloaded'" src="https://user-images.githubusercontent.com/82622339/140811488-795a6f72-63a5-479a-9439-bdb2a662f974.png">

**Comment by thekingsprojects** [comment]
Whoops, missed that this was already reported while I was writing this up: https://github.com/Automattic/wp-calypso/issues/57781

This can be closed/merged in favor of that issue.

**Comment by inaikem** [comment]
Closing in favour of #@57781 🙏

@thekingsprojects, please feel free to to the same in the future. There's no problem with you closing an issue in that manner 👍
