### ISSUE TITLE
 Site Editing: Hide page title a  Gutenberg issue

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57791]
## Helping out with dot org Gutenberg issue
#28564 Site Editing: Hide page title
https://github.com/WordPress/gutenberg/issues/28564

It’s tricky because it’s 3 features in one; sets the visible page/post title on some themes,  sets the <title> for SEO/social media/browser tab, generates the pretty URL

p58i-aJq-p2#comment-51784
p1629299093134800/1629170341.058200-slack-C029SB8JT8S

Just mentioned again by Dave Martin in recent walk through with Matt:  [Building Customer Empathy – Stormy Walkthrough](p58i-bqh-p2)

**Comment by jordesign** [comment]
Closing this issue - as Full Site Editing now allows the Page title to be removed from displaying on templates.
Left the GB issue open - in case there are things to do for older, non-FSE themes,
