### ISSUE TITLE
[Bug]: Stripe link for Payments is showing a TEST subdirectory https://dashboard.stripe.com/test/

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/wp-calypso#57804]
### Quick summary

In Calypso > Tools > Earn > Payments, the payment details link are showing a https://dashboard.stripe.com/test/ instead of https://dashboard.stripe.com/.

The URL seems to be hardcoded here:
https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/client/my-sites/earn/memberships/index.jsx#L440

### Steps to reproduce

1. Go to calypso > tools > earn > Payments (for Stripe connected sites that has existing payments)
2. Click on _See transactions in Stripe Dashboard_ for the payments

### What you expected to happen

The dashboard URL should be https://dashboard.stripe.com/

### What actually happened

The dashboard URL is https://dashboard.stripe.com/test/

### Context

4438731-zen

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes but the platform is still usable

### Workaround details

Remove the `/test` from the URL manually.

**Comment by Robertght** [comment]
@Automattic/shilling is this something you can look into?

**Comment by chrisfromthelc** [comment]
I saw this pop up, so I updated the URL here: https://github.com/Automattic/wp-calypso/pull/58840
