### ISSUE TITLE
Import: Can't see connected Tumblr blogs 

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#57803]
### Quick summary

We have a few reports of users being unable to import Tumblr blogs. They go to the import page, click Tumblr, connect to their account and.... nothing. I confirmed this with my own site and account.

### Steps to reproduce

- **Prep:** Make sure you're logged into tumblr and have a site there with posts to import
- Start at https://wordpress.com/import
- Click _Choose from Full List_
- Click _Run Importer_ under Tumblr
- Click to allow the connection

### What you expected to happen

I should see a list of blogs from that account so I can choose one.

### What actually happened

I just get disconnect option without any blogs there. I tried disconnecting and reconnecting. No dice.

### Context

Customer reports in the forums. I tested and confirmed.

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Theme-specific issue?

No

### Other notes

Did not test Atomic, but it probably really doesn't matter what browser one uses in this case.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

None; they'll need to wait to import. I don't know how many users are trying to import from Tumblr to WordPress now, but it would affect all of them.

**Comment by jerrysarcastic** [comment]
Wanted to note that this was reported in https://wordpress.com/forums/topic/importing-from-tumblr-96/ and I can also confirm that if I try to import from Tumblr on a test site, after connecting I see no sites listed as expected.
<img width="1084" alt="Screen Shot 2021-11-10 at 3 46 45 PM" src="https://user-images.githubusercontent.com/1967448/141211778-04a15ca0-b608-4efa-bc2b-283d8dfae64a.png">

**Comment by vishnugopal** [comment]
A fix is up at D70009-code, this will be reviewed and deployed soon.

**Comment by supernovia** [comment]
Thank you!

**Comment by supernovia** [comment]
Another case here, so we can followup when this is resolved:
https://wordpress.com/forums/topic/tumblr-import-370/

**Comment by vishnugopal** [comment]
A fix for this should now be deployed! @supernovia please confirm and close! 🙏🏽

**Comment by supernovia** [comment]
Thank you! I can see my connected blog now. I disconnected and reconnected to ensure that's working, too, and finally ran an import of the most recent stuff I've posted on tumblr. Everything looks good. Closing this up and reaching out to the users. Cheers!
