### ISSUE TITLE
Marketplace: add a separate dropdown in Store Admin for marketplace products

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57817]
Since marketplace products will be too many, it would be great if we could add a separate dropdown in Store Admin for adding subscriptions for the marketplace and remove the marketplace subscriptions from the default "Product" dropdown.

![SS 2021-11-09 at 11 41 52](https://user-images.githubusercontent.com/12430020/140900400-73036fa2-5554-493e-bd45-9ce328118e26.png)

**Comment by cpapazoglou** [comment]
Let's use `Select2` https://select2.org/dropdown to offer a search in the dropdown.
<img width="1111" alt="SS 2021-12-09 at 14 49 55" src="https://user-images.githubusercontent.com/12430020/145399564-08b15c32-246c-4c1b-8647-28e80b0bfb72.png">

**Comment by allilevine** [comment]
This may be difficult to align with a Marketplace UI sprint goal. It's not something we can ship to users.

**Comment by allilevine** [comment]
Low priority for HEs for now, but needs to be addressed eventually. See p1645133818142119-slack-C029JEQRVRT

**Comment by BogdanUngureanu** [comment]
Opened a new diff that adds the new Marketplace product dropdown: D85868-code.

Besides this change, I've also converted the existing Product dropdown to use select2, since that would make searching for products easier.

Also, I've added an extra Expiry field for the Marketplace Product dropdown, since reusing the existing Expiry field would complicate the code and it might not be intuitive enough.

**Comment by sirbrillig** [comment]
Note that the existing product dropdown already uses select2 as of D85511-code (cc @JessBoctor) and I know there's some ongoing work there to improve the searching even further. I just wanted to mention it in case the work you're doing collides with that.

**Comment by JessBoctor** [comment]
The diffs for the improved searching are in D85857-code and D85784-code.

I also have a WIP in diff D85673-code that is working on reducing the number of times the product lists are being looped through.

Some elements of your code would directly conflict with these. If we continued with having a second and separate select2 for the marketplace products, we should discuss the best way to move forward with the goal of simplifying the UI and codebase. 

If you feel strongly that searching through the select2 is not enough and a shortened product list is the best solution, we may want to return to the [original idea](https://github.com/Automattic/payments-shilling/issues/1061#issuecomment-1205606436) shared in issue [1061](https://github.com/Automattic/payments-shilling/issues/1061) where we used a second select to filter the products list by type (ie, wpcom, jetpack, marketplace, etc)

**Comment by BogdanUngureanu** [comment]
@sirbrillig @JessBoctor Thanks for the input! I wasn't aware that you also had something in progress in Shilling.

I think we should opt for your generic solution, that would cover multiple types of products. If @cpapazoglou agrees, I would like to close this task and abandon my diff in favour of yours. Our implementation was low priority any way. :)

**Comment by cpapazoglou** [comment]
Thanks everybody for chiming in, the solution that is already in production is tackling this issue with success!

![CleanShot 2022-08-16 at 12 49 38@2x](https://user-images.githubusercontent.com/12430020/184850798-cb7723eb-e78e-409e-a603-0795692055af.png)
