### ISSUE TITLE
Marketplace: Translate Extensions title, description, short description

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57816]
We need to start translating the title and the descriptions of all the extensions supported in the WPCOM Marketplace in all WPCOM languages.

eg https://woocommerce.com/de-de/products/woocommerce-subscriptions/?quid=7c9602124304c317595e7f60f642ddd8

**Comment by cpapazoglou** [comment]
@dlind1 is this an issue you can start wrangling?

**Comment by dlind1** [comment]
Sorry for the delay. Is the idea to translate it in the same way the other content on woocommerce.com is translated, or should it be specific to the WPCOM Marketplace? If it's the first time, then it'd require coordination with woocommerce.com to add translation support for these (i.e. more uncertainty). If it's the second one then we could implement some processes and add a translation project just for the titles/descriptions, which would require more effort, but could be done quicker. Or we could just send the 6 titles/descriptions for translation while the support is added on woocommerce.com and hardcoded the translations in the API response.

**Comment by cpapazoglou** [comment]
@dlind1, no worries! 

I lean towards to 
> translate it in the same way the other content on woocommerce.com is translated
so that we start having a central storage for that content. We can then decide how we can utilize it.

cc: @ianstewart, @bgrgicak

**Comment by bgrgicak** [comment]
You can review the [WCCOM i18n implementation here](https://github.com/Automattic/woocommerce.com/blob/5cada2b05d9d9c69652e79f6d6ddaf018d3496ce/plugins/wccom-plugins/i18n/README.md#L1) (private repo).

If you have any questions, could you please P2 about it to include other Alpha members?

cc @denho @mattyza

**Comment by cpapazoglou** [comment]
@dlind1 this issue aims in having translations ready for the WPCOM Marketplace, not creating the mechanism. Let's create the translations for the woocommerce.com and then we will find a way how to reuse them in WPCOM Marketplace. Probably we can start with our current supported extensions and our next batch (pdh6GB-9D-p2#comment-335).

**Comment by dlind1** [comment]
Strings for all the extensions were [sent for translation](p4DzFg-1x2-p2) into German, Italian and Brazilian Portuguese (job 8561). French and Spanish translations should be already available.
