### ISSUE TITLE
Pay with PayPal Legacy Widget - Create new product within widget area

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#57838]
### Quick summary

When trying to add a Pay with PayPal Legacy Widget in the sidebar, it was not possible to create the new product directly, but only possible to select already created products from a dropdown.

User has to create the Pay with PayPal Block within a page to be able to then add it as a widget.

### Steps to reproduce

1. Create a Pay with PayPal Block within a page - save
2. Go to widgets and add a Pay with PayPal Legacy Widget
3. From the Pay with PayPal Legacy Widget you are able to select the payment block you made within the page in step one - but there is no way to edit or add a new Pay with PayPal Block from the widget area.
4. There is an option to direct you to the Customizer to make changes, but it is not possible to make the change from the customizer.
![Annotation on 2021-11-09 at 17-53-08](https://user-images.githubusercontent.com/44442769/140968812-c2cd342b-81bd-4d37-a31c-d8f50c20e405.png)

![Annotation on 2021-11-09 at 17-31-53](https://user-images.githubusercontent.com/44442769/140969438-6e20ea15-3034-4cda-8f21-33aeb55e6e01.png)

### What you expected to happen

I expect to be able to add/edit a new Pay with PayPal product from within the widget area, not have to make it within a page beforehand.

### What actually happened

From the widget area it is not possible to add a Pay with PayPal button directly, the legacy widget needs to be used, and the Pay with PayPal block needs to be created before entering the widget area.

### Context

#4441294-zen

**Comment by joweber123** [comment]
Another report of this on 4499665-zen.

**Comment by arcangelini** [comment]
It looks like this widget can be retired from the Legacy Widget block in favor of the [Pay with PayPal](https://wordpress.com/support/pay-with-paypal/) block.

I will work on this and get it retired similar to the other widgets that have been retired - Automattic/jetpack/issues/21069
