### ISSUE TITLE
FSE beta: remove W toggle override code

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#57834]
After the removal of the browsing sidebar in core (https://github.com/WordPress/gutenberg/pull/36194) we no longer need to override the behavior of this button. We should spin up a janitorial PR to clean up our custom code.

**Comment by Addison-Stavlo** [comment]
I opened a quick PR for this. @zaguiini noted the override is working again with the latest changes in Gutenberg `trunk`, so it seems more important to get rid of this code before that change makes its way to dotcom. 

https://github.com/Automattic/wp-calypso/pull/61368
