### ISSUE TITLE
Blogger Flow: only show "First post published" modal for  the Write Flow, e.g. site_intent=write 

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57855]
## Description
The "First post published" congratulatory modal should only show to users who have chosen the Write flow.   More specifically, this modal can be conditionally show via the  `site_intent=write` flag.

![image](https://user-images.githubusercontent.com/5665959/140996452-4afbfad5-6a9c-4d70-ab03-bde57f03ff3d.png)

## Dev tasks
- [ ] use the `site_intent` flag to ensure the "First post published modal only shows for sites with `site_intent = write`

**Comment by arthur791004** [comment]
Close this as https://github.com/Automattic/wp-calypso/pull/57894 merged. Also, I've posted the current situation of the first post published modal at pdgK6S-mb-p2. Now, the modal won't show on the atomic sites even if the user has the “write” intent. If this case is important, we would come back to fix it.
