### ISSUE TITLE
Videos UI: 375px content width needs to match the Figma mockup.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57868]
The Figma mobile mockup was designed at a content width of 375px (with a 20px margin down the sides). Let's match our layout proportions (margins, padding) to the mockup at that width.

**Comment by kwight** [comment]
Some guidelines provided by @ianstewart :

![image](https://user-images.githubusercontent.com/349751/141212547-d9bdfe2c-476f-4baf-84a0-60f5a59e23e9.png)

**Comment by kwight** [comment]
Also: EuqfSnWpfYx8fgiBlVmbuA-fi-3649%3A1636

**Comment by andres-blanco** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/57924
