### ISSUE TITLE
Videos UI: Verify behaviour on Firefox, Safari and Edge.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57869]
We've had reports in the call for testing that browsers other than Chrome might have some issues – let's verify the big (other) three.

**Comment by andres-blanco** [comment]
On firefox & safari I get this error. I will be investigating on this issue

![image](https://user-images.githubusercontent.com/375980/141514905-b44312f3-0200-447e-8d52-6647183e610c.png)

**Comment by andres-blanco** [comment]
API endpoint `https://public-api.wordpress.com/wpcom/v2/courses?course_slug=blogging-quick-start` is returning `403 Forbidden` when consumed from Firefox

**Comment by andres-blanco** [comment]
This seems to be fixed by ~D70072-code~ D70085-code

**Comment by kwight** [comment]
With the lates changes, I've verified look and behaviour on Firefox, Safari, and Edge. 👍
