### ISSUE TITLE
Videos UI: Play buttons are very big at wider single-column widths.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57865]
Play buttons are very big at wider single-column widths (we stay single-column until 1080px to not crowd the player and sections side-by-side).

<img width="1185" alt="Screen Shot 2021-11-09 at 2 09 44 PM" src="https://user-images.githubusercontent.com/349751/141013057-53230677-71e4-4e92-8073-810d5fe5cae5.png">

**Comment by kwight** [comment]
@ollie I'm wondering if maybe over a certain width, we make the button centered and `max-width: 40%` or something (up to 1080 where we split)?..

**Comment by ollie** [comment]
Sounds good but I'm not sure about centering it, it breaks away from the flow of the text and me personally might miss it, on the other hand it might look silly on the left. 🤔

**Comment by kwight** [comment]
Oh sure – let's start with it justified and see how we like it.
