### ISSUE TITLE
Videos UI: When one video finishes, it does not autoplay the next video.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57873]
As a video ends, we should automatically open the next video section and play its video; A user should be able to start the first video and watch all of them straight through with no interaction.

**Comment by kwight** [comment]
Hm, should we actually do this? There's something to be said for never autoplaying a video. 🤔 cc/ @ianstewart @ollierozdarz

**Comment by ollierozdarz** [comment]
I think it's nice if we do it. Since we're indicating in the header 'Watch five videos. Save yourself hours', it would be good to take all the friction out of the page/flow. Massive bonus is we can add some CSS easing to things like the next panel opening etc.

**Comment by sixhours** [comment]
We're not likely to work on this in the next year, so closing for now.
