### ISSUE TITLE
Videos UI: Consider an additional video section button for the related area of Calypso.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#57871]
For videos about themes, it could be nice to give users another button (or link) to the appropriate section of our admin UI. Proposed in pdgK6S-jM-p2#comment-647.

![annotation-on-2021-11-09-at-14-02-42](https://user-images.githubusercontent.com/349751/141017538-7aed8b83-6b0e-4973-b195-62c6dbc4dc8b.png)

**Comment by kwight** [comment]
cc/ @ollierozdarz @ianstewart

**Comment by ollierozdarz** [comment]
Great suggestion, @kwight! Let's sit on this as a potential idea for the first iteration of this page once it's fully out.

**Comment by sixhours** [comment]
This seems like a low priority enhancement. Closing as wontfix, but feel free to reopen if you feel differently.
