### ISSUE TITLE
GuidedTours: external link should dismiss the dialog

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#5788]
In the final dialog of the "main" guided tour would be nice that the external link "Learn more" could dismiss the dialog as well, so the user when switching back from the newly opened tab finds the site ready.

![screen shot 2016-06-03 at 17 06 28](https://cloud.githubusercontent.com/assets/4389/15785112/8889dcc0-29ad-11e6-8866-6f13c89d8938.png)

---

From comments on #5689: 

> Folletto: When clicked on "Learn more" in the final dialog the dialog didn't close once I got back to it. I felt it should have closed, but that might be by choice. I felt it was worth mentioning.
 
> Shaun: I don't have a strong opinion either way.

**Comment by lsinger** [comment]
Since the a/b test determined that the main tour won't go into production and I believe the behavior of the link would need to be determined on a tour-by-tour basis, I'm closing this for now.
