### ISSUE TITLE
FEEDBACK REQUEST: FSE beta -- Activity log

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#57880]
Hi, awesome FSE team! This is not a bug report; more a feature request -- and this is not super urgent, so feel free to take your time.

Now that we have FSE on WordPress.com and we have 10% of our customers having it, we can expect to see the numbers increasing as we improve FSE. With that in mind, can we have FSE-related log on:

- Blog RC (internal tool, for HEs), or...
- Jetpack Activity (user-facing)

(or maybe both? Please?)

The log would not be anything super detailed about FSE; I'm actually wondering if we can have this kind of log:

```
FSE activated MM/DD/YY UTC HOUR
FSE deactivated MM/DD/YY UTC HOUR
```

Just to check whether FSE is active/inactive, and if there were some reactivate/deactivate processes prior to any issues that might arise. Just an example; a couple of days ago, I had an inquiry from a customer about their page template changing -- and I noticed Site Editor was off on their site 😅 The customer seemed unaware about Site Editor, though. Having this log will be useful for HEs in assisting our customers and taking quick action.

Thank you! If you need more context or information, feel free to ping me! :) 

#anecdote #user-report

**Comment by synora** [comment]
p1636352724065700-slack-C0160HSMDQV for context.

**Comment by klimeryk** [comment]
cc @Automattic/cylon 🙏

**Comment by Addison-Stavlo** [comment]
👋  Sorry for the late reply here, but we did add an "FSE" card to the blog-RC to tell whether or not FSE is active:

![Screen Shot 2022-04-27 at 8 49 14 AM](https://user-images.githubusercontent.com/28742426/165559255-7e300985-9e73-433b-a4c1-115f8b446377.png)

It lives near the bottom of the RC on the right hand column.
