### ISSUE TITLE
Design Picker: add title and subtitle

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57915]
## Description
Update the Design Picker screen to include the title and sub title.  Since we do not yet have the categories UI, the title should go above the grid of designs (similar to mobile view).

![image](https://user-images.githubusercontent.com/5665959/141148278-eeb85387-1064-4a19-b5b5-9629d0626b67.png)

Until we ship the categories UI, we will need to put the title above the designs.
![image](https://user-images.githubusercontent.com/5665959/141148664-464fb432-dc0e-4fd4-b1c0-9b77ff5413f9.png)

## Related

https://github.com/Automattic/wp-calypso/issues/55603
#56567
Figma: https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/?node-id=2119%3A1108

**Comment by p-jackson** [comment]
Oops, seems like I've introduced a regression. The design picker currently looks like this in production, with no title.


<img width="2032" alt="Screenshot 2021-11-11 at 10 55 07 AM" src="https://user-images.githubusercontent.com/1500769/141199814-1562ade1-f752-4f64-ab84-0e5d11b49f91.png">

**Comment by p-jackson** [comment]
I introduced this bug in #56814 by not testing the "category picker hidden" case enough.
