### ISSUE TITLE
Post count in WordPress.com view doesn't match post count in Classic view

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#57919]
### Quick summary

When viewing Posts in WordPress.com view, an incorrect number of published posts is displayed, while Classic view displays the correct number of published posts.

### Steps to reproduce

I haven't discovered the cause, so I don't know that this can be reproduced on a test site.

### What you expected to happen

The post count in WordPress.com should show the actual correct number of posts.

### What actually happened

Only Classic view shows the correct number of posts.

### Context

Customer report 32666913-hc

I believe that I have seen this issue in the wild before. I wasn't able to find another report on Slack or MGS.

Jetpack sync does not resolve the issue. 

### Simple, Atomic or both?

Atomic

### Severity

Some (< 50%)

### Workaround details

Use Classic view as a workaround.

**Comment by masperber** [comment]
10954297-hc the customer isn't able to see all of their published pages in WordPress.com view. All pages are visible in Classic Vew. Asked them to use Classic view as a workaround.

**Comment by Robertght** [comment]
Thank you for your report @masperber !

For the first example, a Jetpack sync didn't do the trick, but I don't see a conflict test. This can be affected by one of the plugins, a mix of some or the theme. I recommend reaching out to the website owner for further debugging for now.

On the second case, I just checked and the counts on both dashboards are the same.

**Comment by Robertght** [comment]
I'm going to mark this as solved for now as we have not got other reports but feel free to reopen. cc @masperber
