### ISSUE TITLE
Signup form fade in interrupted on IE11, form remains almost completely transparent

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#5793]
<img width="1278" alt="screen shot 2016-06-03 at 15 19 12" src="https://cloud.githubusercontent.com/assets/418473/15788662/f9d56b9c-299e-11e6-91f3-99f5161a770d.png">

Couldn't reproduce this consistently, but I got into this weird state where the form wouldn't fade in, and remained almost completely transparent.

The inspector showed a warning about `setState()` on an unmounted component.

I believe this might be a race condition related to adding/removing the `.signup__step-enter-active`, `.signup__step-leave-active` classes.

**Comment by lancewillett** [comment]
I ran through a bunch of signup tests in Windows 10 today with IE11 (emulation) and couldn't repeat the state.

Let's re-open if it happens again in a consistent way.

**Comment by lancewillett** [comment]
One side note: at the end of signup for a new user and new site, starting from `calypso.live/start/developer/user` — the end resulting page after site creation was odd, it looked old and not Calypso-ish:

<img width="1395" alt="screen shot 2016-10-13 at 13 26 42" src="https://cloud.githubusercontent.com/assets/66797/19365749/0ac0991a-9149-11e6-99d4-2346af435add.png">

<img width="1395" alt="screen shot 2016-10-13 at 13 26 55" src="https://cloud.githubusercontent.com/assets/66797/19365750/0ad63dce-9149-11e6-814d-228fa3a4b1de.png">

**Comment by lancewillett** [comment]
Same flow as a logged-in user worked as expected, ending up at `devdocs/welcome`.

**Comment by lsinger** [comment]
@lancewillett I just used an incognito window, created a new user and site, and then got redirected to `devdocs/welcome` after signup. In other words, I can't reproduce anymore. OK to close?

**Comment by lsinger** [comment]
@lancewillett Sorry — just realized that it is already closed. Nevermind. :)
