### ISSUE TITLE
Video Course: Typo on Video 3

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#57935]
We accidentally a word in the second sentence.

![image](https://user-images.githubusercontent.com/545779/141208350-b6ec065c-147c-4af1-ae92-f8545ae1488f.png)

> You can use WordPress powerful block editor …

Should be "WordPress' powerful block editor" or "the powerful WordPress block editor" or something to that effect.

**Comment by kwight** [comment]
D70185-code
