### ISSUE TITLE
Plans: No link to My Plan from plans page.

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#5796]
#### What I expected

To be able to get access to the "My Plan" page from an obvious button on the plan I am subscribed to on the plans page.

#### What happened instead

I could not get access to it, without hitting the plan sidebar link.

**Comment by gwwar** [comment]
@adambbecker @drw158  do you have any ideas on where we might comfortably place this link? A button to the my plan page will optionally display when the current site has a Business or Premium plan.

**Comment by mtias** [comment]
Seems like this button should link there:

![image](https://cloud.githubusercontent.com/assets/548849/15832843/56e5839e-2c24-11e6-93a6-1ce210bdf2e4.png)

But probably worth having #5212 in before that.

**Comment by artpi** [comment]
Is that still the case? Can we close this? 
<img width="1118" alt="zrzut ekranu 2016-08-31 o 07 53 04" src="https://cloud.githubusercontent.com/assets/3775068/18133622/340c0d06-6f50-11e6-9d5b-f670e52451fc.png">

**Comment by apeatling** [comment]
Yes
