### ISSUE TITLE
Signup Hero Flow: On write path, sometimes editor won't load

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57962]
### Quick summary

We've had a couple of our E2E tests fail in the new Signup hero flow after going down the "Write" >> "Draft your first post" path.

When they land in the editor, they get just a blank white screen and some console errors. 

This does not always happen, it is only intermittently reproducible.

### Steps to reproduce

1. `/start`
2. Choose "Start writing"
3. Enter a name/tagline, continue
4. Choose "Start writing" (Next to "Draft your first post")

### What you expected to happen

Editor loads.

### What actually happened

After loading indicator went away, just got a blank white screen - looked like a crashed editor.

### Context

Failing E2E test (`wp-signup__free.ts`), see related issue #57959 which has details on the TeamCity failure.

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Other notes

Console errors on blank page:

```
post-new.php?calypsoify=1&block-editor=1&frame-nonce=c937778142&origin=https%3A%2F%2Fwpcalypso.wordpress.com&environment-id=wpcalypso&support_user&_support_token:0

Access to fetch at 'https://public-api.wordpress.com/wp/v2/types?context=edit&_locale=user' from origin 'Pdw3Tn-2-p2' has been blocked by CORS policy: Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.

types?context=edit&_locale=user:0Failed to load resource: net::ERR_FAILED

Object
post-new.php?calypsoify=1&block-editor=1&frame-nonce=c937778142&origin=https%3A%2F%2Fwpcalypso.wordpress.com&environment-id=wpcalypso&support_user&_support_token:0

Access to fetch at 'https://public-api.wordpress.com/wp/v2/types/post?context=edit&_locale=user' from origin 'Pdw3Tn-2-p2' has been blocked by CORS policy: Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.
post?context=edit&_locale=user:0

Failed to load resource: net::ERR_FAILED

Failed to register a ServiceWorker for scope ('https://e2eflowtesting1636630106046893.wordpress.com/wp-admin/') with script ('https://e2eflowtesting1636630106046893.wordpress.com/wp-admin/?frame-nonce=c937778142?service-worker'): The script has an unsupported MIME type ('text/html').
```

### Reproducibility

Intermittent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

When we re-logged in as the test users that were created, we were able to use the editor just fine and didn't see this error. So the user should be able to close the browser and re-log and continue on with using their site.

**Comment by dpasque** [comment]
Sending to Blogger Experience Pod initially  as a heads up as it came from tests using the new Hero flow!

**Comment by worldomonation** [comment]
I investigated other builds that ran around the same time as this failure was observed (November 11 @ 0330 PST/1130 UTC), and found the following builds that exhibited the same issue:

E2E mobile - 6968416
E2E desktop - 6968405

Looking at the video recording, screenshot and the trace files for clues, it is apparent that these issues are all identical.

Screenshot:

![image](https://user-images.githubusercontent.com/6549265/141347793-c2da9e9b-63a9-41dc-8fe9-a4e1f48d0daa.png)

Video:

https://user-images.githubusercontent.com/6549265/141348348-d2f51d78-d888-4016-b773-a646b9267d5e.mp4

**Comment by dpasque** [comment]
It looks like this isn't just associated with the new Hero flow, so removing from Blogger Experience and passing along to @Automattic/flow-patrol-create .

Also pinging @fullofcaffeine as I know he's done work with the iframe to see if anything stands out from these errors.

**Comment by worldomonation** [comment]
Looks to be resolved as per p58i-bt1-p2. It was an outage due to undeclared dependency.
