### ISSUE TITLE
Site Editor loading - wp-admin nav menu present during loading process.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#57971]
This was not an issue with previous versions and is not reproducible on 11.8.*.

However, with the v11.9.* releases, we have an issue where loading the site editor shows the wp-admin menu for few seconds while it is loading.  This is an issue because the user can interact with this menu and then navigate throughout wp-admin while locked in the site-editor calypso iframe URL.

With v11.9.0:

![wp-admin-menu](https://user-images.githubusercontent.com/28742426/141361701-fb854740-ffb0-44df-9fa6-b8e3baea1835.gif)

Notice the editor starts loading, then shows the wp-admin menu briefly, then finishes loading.
As opposed to v11.8.3 where there is no admin menu in this loading process:

![no-admin-menu](https://user-images.githubusercontent.com/28742426/141362113-a92badd5-074c-4475-bd95-d296ab0769a4.gif)

**Comment by Addison-Stavlo** [comment]
Added an issue in Gutenberg repo since this is reproducible there - https://github.com/WordPress/gutenberg/issues/36445

**Comment by Addison-Stavlo** [comment]
A proposed solution - https://github.com/WordPress/gutenberg/pull/36455

**Comment by fullofcaffeine** [comment]
@Addison-Stavlo Can we close this one?

**Comment by Addison-Stavlo** [comment]
Yes we can, thanks!  Forgot I had the issue both here and in gutenberg repo 😅
