### ISSUE TITLE
Improper syntax for some @keyframe animations

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#5797]
While working with @dereksmart in `dops-components` we ended up following a trail back to calypso and finding some `@keyframe` animations with improper syntax. My guess is that these aren't working at all due to the quotations, and are throwing some scss errors somewhere - I haven't tested it.

https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/_animation.scss#L231

**Problem:**
On lines 232, 241, 245, and 251, the `@keyframes` animation names are wrapped in quotes and shouldn't be. (unless there's some black magic occurring I'm not aware of)

**Fix:**
Remove quotes around keyframe animation names.

Visual:
![screen shot 2016-06-03 at 4 04 12 pm](https://cloud.githubusercontent.com/assets/214813/15791212/f0d7a80c-29a3-11e6-9f4b-541cca33363b.png)

**Comment by lancewillett** [comment]
Fixed in https://github.com/Automattic/wp-calypso/commit/7d14601a1848eba1902e8c3e6691fff5af87669e
