### ISSUE TITLE
Launch Bar: The "My Home" label wraps poorly in Spanish

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#57984]
The link back to the Calypso dashboard in the Launch Bar doesn't deal well with long label text. Maybe the link element is fixed width? This means if a translation is longer than expected then it'll wrap poorly and be difficult to read.

**Steps**
1. Test an unlaunched site
2. Change _site language_ to Spanish (not the language in `/me`, the one in `/settings/general/:site`
3. View the front end of the test site

<img width="1424" alt="Screenshot 2021-11-12 at 4 01 04 PM" src="https://user-images.githubusercontent.com/1500769/141401976-bea266a0-c5fa-4fa2-a268-4f2144a396c7.png">

**Comment by kwight** [comment]
The fix for https://github.com/Automattic/wp-calypso/pull/58078 will probably be helpful.

**Comment by kwight** [comment]
Fix in D70182-code for review (on Serenity's board).
