### ISSUE TITLE
Sensei LMS - Color of module titles in editor 

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#57988]
### Quick summary

When you create a new module the title of that module appears as black text on a black screen. Screencapture here - 

https://user-images.githubusercontent.com/13706336/141439780-b27293d1-f7dc-4bdd-926c-1ad8816775ec.mp4

### Steps to reproduce

Click to add a module in Sensei in the course list page.
The title area appears with a black background. As you type the text is black on black.
You can only see the writing when you change the colors on that block.

### What you expected to happen

To be able to see the title as you type it.

### What actually happened

Black text on a black background

### Context

Site: https://richardmidson.com/wp-admin/post.php?post=2042&action=edit
### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Other notes

Here is a screenshot of the console errors in case it helps. It mentions the stylesheet not adding properly.

<img width="906" alt="Markup 2021-11-12 at 08 39 22" src="https://user-images.githubusercontent.com/13706336/141439998-de9b4bfa-6628-454c-a262-4840eeaa01e2.png">

### Reproducibility

Consistent

### Severity

One

**Comment by Robertght** [comment]
I think this is Sensei related. @jeherve is this suitable for https://github.com/Automattic/sensei/issues ?

**Comment by jeherve** [comment]
Yup, that would be the right place for it I think.

**Comment by Robertght** [comment]
Thank you for the confirmation Jeremy & Rick for reporting this. I'm closing it in favor of this https://github.com/Automattic/sensei/issues/4419
