### ISSUE TITLE
Theme Showcase: List of sites cut off 

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#5798]
1. Starting at All my Sites, navigate to Themes and then to any theme, for example: 
https://wordpress.com/theme/twentysixteen
2. Click "Pick this design" or pick "Live Preview" and "Try and Customize" 
3. If you have a lot of sites, the dropdown menu is cut off by the bottom of the browser window: 

<img width="765" alt="screen shot 2016-06-03 at 2 41 17 pm" src="https://cloud.githubusercontent.com/assets/8698879/15792511/eaeaecf0-299a-11e6-890b-c4421bfdfb7d.png">

OS X 10.11.1 in Chrome 50, Firefox 46, and Safari 9.1

**Comment by ockham** [comment]
Thanks for reporting -- this is already being tracked in #1886, so I'm closing this issue.
