### ISSUE TITLE
Fortune theme: Block widgets aren't visible on wp-admin dashboard but appear fine on Customizer

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#57985]
### Quick summary

Block widgets added to a site are visible only on the Customizer, not on the wp-admin widgets view.

### Steps to reproduce

- Activate Fortune theme (latest version is 1.0-wpcom) on a WordPress.com site.
- Add some widgets using the Customizer.
- Visit widgets area on the wp-admin dashboard. Notice that widgets are missing.

### What you expected to happen

Widgets appear fine on wp-admin dashboard too.

### What actually happened

Widgets appear only on Customizer view, never on wp-admin dashboard.

### Context

Found during a customer interaction: 4446501-zen.

### Operating System

Windows, macOS, Linux, Android, iOS

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Microsoft Edge (legacy), Apple Safari

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Yes, tested with Fortune. Not sure if all pre-block themes are affected.

### Other notes

I think this would be closed as a `won't fixed` due to the retired nature of this theme, but if a fix could be pushed out at all, it'd benefit all Fortune users on WordPress.com.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Access widgets on Customizer view instead of wp-admin dashboard.

**Comment by arunsathiya** [comment]
For some extra clarity, I have tested only on Atomic, not on Simple.

**Comment by arunsathiya** [comment]
Related conversation: pcmoY8-3V-p2#comment-445

**Comment by kerrynicl** [comment]
Hi Arun, Due to the theme being retired and I'm not able to replicate this issue on my end I'm just going to close this for now

**Comment by arunsathiya** [comment]
@kerrynicl Thanks for taking a look. Should we move this to https://github.com/Automattic/themes/issues?

**Comment by inaikem** [comment]
@arunsathiya, if you've not already done so, I'd suggest doing that in case there's the capacity to roll out a fix.
