### ISSUE TITLE
Renamed Tags are not updated properly causing AMP live tests to fail

### ISSUE THREAD

**Issue by kimerlin81** [Automattic/wp-calypso#57996]
### Quick summary

In Calypso, when a tag is renamed, the URL for "View posts" does not update. Also, the page source code of tagged posts still reflects the old tag name even though it shows correctly in the tag section of the page settings.

https://user-images.githubusercontent.com/83732167/141463191-58d29bc4-98ce-4334-9ab7-6538fb6739f8.mp4

Page Source Screenshot:
![Screenshot on 2021-11-12 at 06-56-03](https://user-images.githubusercontent.com/83732167/141463552-a1431abb-21c1-49c3-9ba5-4bf15d35601e.png)

### Steps to reproduce

1. Create a tag
2. Assign a post to the tag
3. Rename the tag
4. Notice that the "View posts" URL reflects the old tag name
5. Check the tag section of the post within post settings and see that it shows the updated name
6. View the page source code to see that it's still referencing the old tag name

### What you expected to happen

I expect the "View posts" URL and the post source code to update and match the edited tag name.

### What actually happened

The "View posts" URL and the post source code still show the original tag name.
When AMP live tests are run the for the associated URLs they fail because the tag cannot be found.

### Context

Affected user: 4420123-zd-woothemes

As noted in the ticket, because the page source and Google seem to reference the old tag name, AMP live tests were failing due to the missing article tag.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Instead of renaming a tag, create a new tag and reassign posts.

**Comment by cometgrrl** [comment]
Pending closure, since we are not installing AMP on sites anymore. If users choose to install AMP and have an issue, AMP needs to resolve it.

Additional context: p1662141166197659/1662070111.766319-slack-C03G2H51WJX

**Comment by cometgrrl** [comment]
This works as designed. Calypso UI exposes only the tag name, not the slug. To edit the slug, you have to use wp-admin. 

If something related to AMP is failing, I think that's an issue AMP should fix.
