### ISSUE TITLE
Plugin Install: refresh the site plugins after plugin installation with upgrade

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#57999]
### Details

Installing a plugin to a Simple site (eg Business Simple) leads to an Atomic transfer. It seems that after transfer & installation site plugins are not fetched again which results in:
- "Manage Plugin" still animating
- Plugin appearing as not installed yet when navigating back in Plugins Browser (without a page refresh, by clicking Explore or the X button)

![image](https://user-images.githubusercontent.com/12430020/142161760-6cfc91b1-3215-4b0a-b42b-5f8c229c5fd8.png)

related convo: p58i-brP-p2#comment-52450

**Comment by cpapazoglou** [comment]
👋  @jordesign, while I initially thought I knew the root of the problem finally I couldn't reproduce it. Can you please share more details about your case?

1. Plugin
2. Site plan before upgrade
3. Is there a chance it was Atomic before upgrade?

If you can still reproduce it, can you please take a video?

Moreover, after upgrading your site you would also need to re-apply `wpcom-marketplace` blog sticker so that the menu gets the correct order.

**Comment by jordesign** [comment]
@cpapazoglou  Hmm - let me see.

1. Yoast SEO
2. 99% sure it was on a free plan
3. Very unlikely

---
I've just run through testing again installing Yoast and recreated.

Site SImple/Free before upgrade:

<img width="1742" alt="Screen Shot 2021-11-17 at 12 18 11 pm" src="https://user-images.githubusercontent.com/1842363/142092885-4181cf7b-c60c-44f7-b6aa-a98235def67c.png">

Purchasing/Upgrading to Business:

<img width="1117" alt="Screen Shot 2021-11-17 at 12 19 12 pm" src="https://user-images.githubusercontent.com/1842363/142093060-a9505e31-4ef5-4614-b7e1-06e1362ba833.png">

Oddity - after install the 'Manage Plugin' button was still animating and couldn't be clicked (even after a few minutes). I had to click the 'Explore Plugins' button instead.
<img width="1199" alt="Screen Shot 2021-11-17 at 12 21 55 pm" src="https://user-images.githubusercontent.com/1842363/142093987-b1e23a73-9ee3-4321-9842-240af4a2fd68.png">

Once again - plugin menu items inactive:
<img width="1745" alt="Screen Shot 2021-11-17 at 12 22 37 pm" src="https://user-images.githubusercontent.com/1842363/142096434-ea0be0c3-a475-43f6-b246-0fc9acc0754b.png">

**Comment by cpapazoglou** [comment]
Thanks @jordesign for the detailed steps! They are very helpful!

> Once again - plugin menu items inactive:

This is expected in this testing phase, after upgrading your site you would also need to re-apply `wpcom-marketplace` blog sticker so that the Plugin menu gets fixed.

**What doesn't work well though**, is that site plugins are not "refreshed" after the transfer which results in:
- "Manage Plugin" still animating
- Plugin appearing as not installed yet
