### ISSUE TITLE
CMP Banner: Can't Close It

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#58004]
### Quick summary

You aren't able to close the CMP (Consent Management Provider) banner on free sites.

### Steps to reproduce

1. Check one of your free sites.
2. Look for the CMP banner in the footer
3. Click on "Close and Accept"

### What you expected to happen

To close the banner reload the page.

### What actually happened

It reloads the page but the banner is still there.

### Context

The banner's layout seems a bit off too. I was able to replicate this issue on free sites using different themes, such as Independent Publisher 2, Leven, Zoologist, Geologist, and on Chrome, Firefox, and Safari.

I remember reading about this feature here: pMyNb-55B-p2
This has been reported here: https://wordpress.com/pt-br/forums/topic/aviso-de-cookies/

### Reproducibility

Consistent

**Comment by Robertght** [comment]
I can't seem to replicate this on my free sites at the moment. Is it possible to share a quick video capture from your end @carinapilar ?

**Comment by carinapilar** [comment]
@Robertght, I think this is fixed already, I can't replicate it anymore, might have been related to a recent outage. I'll close it. Thanks! 🙂
