### ISSUE TITLE
Domains: Missing Navigation Header on DNS Page

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#58017]
### Quick summary

The navigation header isn't showing up on the DNS page.

### Steps to reproduce

1. Select a site where you have a custom domain.
2. Go to Upgrades > Domains.
3. Select your domain.
4. Click on _"Change your name servers & DNS records"_.
5. Click on _"DNS records"_.

### What you expected to happen

To see a navigation header as the previous page had.

### What actually happened

There's no navigation header, so you can't go back to the previous page.

### Context

Here's how the _"Change your name servers & DNS records"_ page looks like:

![NameServersDNSPage](https://user-images.githubusercontent.com/16104522/141510442-798aefd1-ea7a-4db1-ab9b-c01d0aa55b59.jpg)

And how the _"DNS Records"_ page is:

![DNSPage](https://user-images.githubusercontent.com/16104522/141510474-f6b1e8fa-5aa8-4002-9bc7-b8fffe1b7925.jpg)

**Comment by Robertght** [comment]
Thank you @carinapilar ! I pinged here: p1636754368013400-slack-C014TPFLP4Z

**Comment by leonardost** [comment]
Hi @carinapilar, thank you for reporting this! We just deployed #58027 that corrects this, so I'll close this issue 🙂
