### ISSUE TITLE
WordPress.com doesn't load on Safari 12

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#58012]
### Quick summary

When trying to visit WordPress.com on Safari 12, all that appears is a blank page with a WordPress logo.

### Steps to reproduce

Go to WordPress.com
Blank page appears with WordPress logo.

### What you expected to happen

WordPress.com login page to appear

### What actually happened

![Markup 2021-11-12 at 14 33 46](https://user-images.githubusercontent.com/13706336/141498411-bead54aa-43e2-45b0-8dc8-95a395f335d6.png)

### Context

#4450431-zd

### Operating System

macOS

### Browser

Apple Safari

### Other notes

Whatsmybrowser details - https://www.whatsmybrowser.org/b/JJNVU
Recreated with the same combination on Browserstack. Same thing occurs.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
Thank you @rickmgithub!

I'm going to close this in favor of this one: https://github.com/Automattic/wp-calypso/issues/57379
