### ISSUE TITLE
Blog Posts Block: Portfolio links not clickable when displayed along site posts

### ISSUE THREAD

**Issue by mrsjaved** [Automattic/wp-calypso#58038]
### Quick summary

Portfolio detailed page link does not work on load more when displayed along side posts and only when clicked on load more posts button.

### Steps to reproduce

1. Open your WP.com simple site. 
2. Enable projects/portfoliios from settings -> writing if not enabled already.
3. Make sure you have a couple of portfolios and posts. Atleast six for testing.
4. Add blog posts block to a page.
5. Enable load more posts option (the site must be public for this option). 
6. Set per page limit to three (3) and disable page excerpts and featured images for faster testing.
7. Important step, check "Posts" and "Projects" from the Posts types section of the block settings.  
8. View the page. Links to portfolio works, good for now.
9. Click on load more, find portfolio/projects in the list.
10. Try to click on portfolio-title which is not clickable. 

### What you expected to happen

It should add a link to the portfolio title after loading more too similar to posts. 

### What actually happened

No portfolio link after load more on portfolio/projects.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Works on Atomic in my case. 

### Reproducibility

Consistent

Ticket: 4449321-zd-woothemes

**Comment by Robertght** [comment]
Thank you for the report @mrsjaved ! 

I tried to replicate it on a Simple site but I had no luck. I could see it on the user's site though.

Could you share an example from your test site please?

**Comment by Robertght** [comment]
Closing this one due to inactivity.

Please reopen if other cases arise.
