### ISSUE TITLE
Theme Showcase: Narrower browser window changes button behavior 

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#5803]
1. Navigate to a theme description page, for example: https://wordpress.com/theme/shoreditch/overview

2. Note that the entire button for "Pick this design Free" opens the site picker, as expected.

3. Drag your browser window narrower until the right pane of the showcase page disappears, about 924px wide (which, side note, should there still be some way to get to the live preview once that right side collapses in the narrower view? I think live preview is pretty important). 

4. The "Pick this design Free" button now links to two different places: the "pick this" half of the button links to the site picker, as expected, but the "design Free" half of the button links back to https://wordpress.com/design

<img width="931" alt="screen shot 2016-06-03 at 3 14 15 pm" src="https://cloud.githubusercontent.com/assets/8698879/15793107/fcace782-299e-11e6-982a-9d9bd8d3efc8.png">

In: OS X 10.11.1 in Chrome 50, Firefox 46, and Safari 9.1

**Comment by folletto** [comment]
Apparently `HeaderCake` does something there...

<img width="511" alt="screen shot 2016-06-08 at 17 54 40" src="https://cloud.githubusercontent.com/assets/4389/15901223/abc4a29e-2da2-11e6-9b8b-a314145f477c.png">

**Comment by folletto** [comment]
Quick hack might be adding `z-index: 1` at `.themes__sheet-primary-button`.

**Comment by seear** [comment]
> about 924px wide (which, side note, should there still be some way to get to the live preview once that right side collapses in the narrower view? I think live preview is pretty important).

Ooh, good point, I didn't spot this when first reading through this issue. The preview icon doesn't appear in the bottom left of the screenshot until we go narrower than 661px:

![screen shot 2016-06-22 at 10 58 17](https://cloud.githubusercontent.com/assets/7767559/16262643/6a8814ca-3868-11e6-8e3c-d25c2a42b1cf.png)

**Comment by lancewillett** [comment]
Fixed in https://github.com/Automattic/wp-calypso/commit/3e97bdcb91551942019528ad7afd20e21a97ab97
