### ISSUE TITLE
Dummy Bug Report

### ISSUE THREAD

**Issue by kimerlin81** [Automattic/wp-calypso#58035]
### Quick summary

Mic check 1 2 1 2. This Bug Herders Test Issue is brought to you by the creators of all things Happy.

### Steps to reproduce

1. This message will self destruct in 5
2. 4
3. 3
4. 2
5. Psych

### What you expected to happen

Everything

### What actually happened

Absolutely nothing

### Context

NA

**Comment by inaikem** [comment]
Internal discussion thread: p1636940698032300-slack-C02E2V9A8BF
