### ISSUE TITLE
Site Picker: Switching sites on mobile shows the stats page instead of site menu

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5804]
Regression introduced in #5583 

#### Steps to reproduce
1. Starting at URL:  https://wordpress.com _in mobile view_
2. Click "My Sites"
3. Click "Switch Sites"
4. Choose a site, or "all sites"

#### What I expected

Mobile menu for that site, or all sites, shown

#### What happened instead

Stats page shown

#### Browser / OS version

Chrome OSX Mobile View

#### Before PR 5583

![previous behaviour](https://cloud.githubusercontent.com/assets/128826/15793889/4f8d32d2-2a2a-11e6-8a5d-f6f04c9a8e90.gif)

#### After PR 5583

![new behaviour](https://cloud.githubusercontent.com/assets/128826/15793906/5e0afc0e-2a2a-11e6-9421-13d939a4e8bf.gif)

**Comment by ockham** [comment]
cc @marekhrabe

**Comment by marekhrabe** [comment]
On it
