### ISSUE TITLE
[Bug]: Unable to signup on iOS devices

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#58061]
### Quick summary

I tried signing up on WordPress.com on an iOS device using an online simulator, and each time I was redirected to an "Unsupported browser" page. 

### Steps to reproduce

**Using Chrome's "Toggle device" feature in the developer toolbar**

1. Open https://wordpress.com with the user agent set to an iPhone device - iPhone 6/7/8 or iPhone X
2. Proceed to signup as a new user. On the domain step, click "View plans", and on the plan step, select any paid plan.

**Using browserstack.com**

1. Open https://wordpress.com on an iOS device. I tried iPhone 12 pro max, iPhone 12, and iPhone X.
2. Proceed to signup as a new user. On the domain step, click "View plans", and on the plan step, select any paid plan.

### What you expected to happen

I expected to be taken to the checkout page

### What actually happened

One of two things happen to me, and this varies a bit each time. I'm either to to a "Browser unsupported" page, like this:
<img width="1442" alt="Screenshot 2021-11-15 at 7 48 58 PM" src="https://user-images.githubusercontent.com/1269602/141815893-c80e1324-6f13-4a8d-b832-650b0a4deb67.png">

Or I'm taken to the checkout page, and exiting the checkout page takes to the unsupported browser page:

https://user-images.githubusercontent.com/1269602/141816486-3ec68493-85bd-421d-837f-21fbddbdee9f.mov

### Browser

Google Chrome/Chromium

On my computer, I use the latest Chrome version Version 95.0.4638.69

On browserstack.com, the Chrome version on the iPhone 12 pro device was version 86:

<img width="360" alt="Screenshot 2021-11-15 at 8 03 50 PM" src="https://user-images.githubusercontent.com/1269602/141817079-39679416-6460-4cdb-8ce7-1b1d83f45821.png">

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by enejb** [comment]
This should now be fixed via #58066. 

Thanks for reporting it @niranjan-uma-shankar !

**Comment by niranjan-uma-shankar** [comment]
Thanks for jumping in and fixing this quickly @enejb !
