### ISSUE TITLE
Videos UI: Videos don't have a poster.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58074]
All of the course videos should have a poster, so that users have some positive feedback of what video they're about to watch (instead of blank first frames).

<img width="1402" alt="Screen Shot 2021-11-15 at 12 26 29 PM" src="https://user-images.githubusercontent.com/349751/141849476-762c090a-0115-4c5b-8285-f91eb06d0022.png">

**Comment by andres-blanco** [comment]
There are two alternatives:
 * Use the [poster attribute for the video tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-poster): we would need to take screenshots, host them somewhere, link to them.
 * Set an offset to the first video so the browsers pick up a frame with the title, this feels much simpler. There's a diff for this here: D70152-code

**Comment by kwight** [comment]
I'd much prefer option one – the user still experiences the music beginning and the title animation of the card that way.

**Comment by andres-blanco** [comment]
@kwight where should poster imaged should be hosted?

**Comment by kwight** [comment]
> where should poster imaged should be hosted?

Same site as the videos themselves, I'd think. 👍
