### ISSUE TITLE
Site Editor Tracking - track closing the site editor

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#58123]
We previously made sure that the wpcom_block_editor_close_click [did not fire when opening the navigation panel](https://github.com/Automattic/wp-calypso/blob/326876bc04cd400ec56428b0974882603cb4e229/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-close-click.js#L11).  Since the navigation panel was recently removed, we should update our tracking system to be able to track when the site editor is closed by the "W" logo close link in the top left of the editor.

It may make sense to use the [wpcom-block-editor-close-click](https://github.com/Automattic/wp-calypso/blob/07193a8f10458dad2450e921164d7a68404c5e2f/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-close-click.js#L8-L14) event for this, however since it has been around for a while, is not a verified event, seems to only fire on atomic, etc. it may make sense to create a new one specific for the site editor such as `wpcom_block_editor_site_editor_close` or something similar.

**Comment by p-jackson** [comment]
@danielbachhuber this could be a useful thing you could implement to learn about `wpcom-block-editor` while at the same time do Cylon a favour.

**Comment by danielbachhuber** [comment]
@Addison-Stavlo Could you clarify what you mean by the following?

> Since the navigation panel was recently removed, we should update our tracking system to be able to track when the site editor is closed by the "W" logo close link in the top left of the editor.

I still experience what I assume is the Navigation Panel when I click on the "W" logo:

https://user-images.githubusercontent.com/36432/171647486-75da53de-a19a-4ebd-a895-1e73a7af40b3.mp4

Thanks!

**Comment by Addison-Stavlo** [comment]
Hi @danielbachhuber!

My apologies as you have found a stale outdated issue. The navigation panel was removed for a period of time, but was revised and rereleased before we shipped FSE to users on dotcom.

**Comment by Addison-Stavlo** [comment]
Im unsure if there is a close event in the site editor in the new form (i dont think so?), but adding one to the '< Dashboard' button in the navigation panel could make sense.  

Also note that the fill we use for that component may move soon so it works in wp-admin and not just in the calypso iframe - related : https://github.com/Automattic/wp-calypso/issues/64131 (as i think our options to add a tracking event for this could be to either to send the event from our [fill component itself](https://github.com/Automattic/wp-calypso/blob/6cb33027cd048e31c0fbd065317cd4b9e17001e1/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L486-L494)  OR track via [the selector tracking system](https://github.com/Automattic/wp-calypso/tree/trunk/apps/wpcom-block-editor/src/wpcom/features/tracking) and the case for the former is getting stronger since we are planning to move that to also run in wp-admin views)

**Comment by danielbachhuber** [comment]
@Addison-Stavlo Is #64594 roughly what you wanted?

**Comment by Addison-Stavlo** [comment]
Looks good. Thank you!

**Comment by danielbachhuber** [comment]
Shipped! 🚢 🚢 🚢
