### ISSUE TITLE
Add raw transform for spoiler block

### ISSUE THREAD

**Issue by AetherUnbound** [Automattic/wp-calypso#58144]
It would be useful to add a transformation for the Spoiler block which converts the [collapsible content Markdown syntax](https://about.gitlab.com/handbook/markdown-guide/#collapse) into a Spoiler.

#### Steps to reproduce

1. Start on any post
2. Paste the following content: `<details> <summary>Title here</summary> content here </details>`

#### What I expected

A Spoiler block is created with the `summary` as the Spoiler summary and everything else in the details as the inner content.

#### What happened instead

The tags get removed and the text is all added by itself.

#### Browser / OS version

Firefox 94.0, Xubuntu 18.04

#### Context / Source

The transform would likely need to be added here: https://github.com/Automattic/wp-calypso/blob/trunk/apps/o2-blocks/src/spoiler/editor.jsx#L84-L100

#dogfooding

**Comment by dmsnell** [comment]
for whoever comes and picks this up, I found that this transform roughly does what I expect

```ts
export const transforms = {
	from: [
		{
			type: 'raw',
			isMatch: ( node ) => {
				return (
					node.nodeName === 'DETAILS' &&
					node.querySelector( 'summary' ) !== null
				);
			},
			schema: ( { phrasingContentSchema } ) => ( {
				details: {
					children: {
						...phrasingContentSchema,
						summary: { children: phrasingContentSchema },
					},
				},
			} ),
			transform( node ) {
				const summary = node.querySelector( 'summary' );
				node.removeChild( summary );
				console.log( summary.innerHTML );
				console.log( node.innerHTML );

				return createBlock(
					'core/spoiler',
					{
						summary: summary.innerHTML,
					},
					rawHandler( { HTML: node.innerHTML } )
				);
			},
		},
	],
};
```
