### ISSUE TITLE
Block Patterns Showing Unexpected or Invalid Content Error

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#58150]
### Quick summary

Several block patterns show the following error message:

"This block contains unexpected or invalid content"

### Steps to reproduce

1. In the editor, click the + block inserter
2. Click the Patterns tab
3. In the dropdown, choose Columns
4. Scroll down to the pattern called Pricing Table that shows the error in both the preview and when adding it to the page:
![Screenshot on 2021-11-17 at 11_23_12](https://user-images.githubusercontent.com/30727666/142089649-d7d9a08f-1188-4666-a36e-84bb70d99ff5.png)

### What you expected to happen

I expected to see the patterns without errors.

### What actually happened

The patterns show errors. I mentioned the Pricing Table pattern above but it seems to be affecting several patterns. I went through each category and here's a list: 

* Headers - Event (where Headers is the category and Event is the pattern name)
* Columns - Pricing Table
* Images - Image and quote on a background
* Images - Image on solid color with description

In the few that I tried, clicking the 'Attempt Block Recovery' button fixes it, but it would be good to avoid the error from showing at all.

### Context

Noticed during regular use.

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by dpasque** [comment]
Jumping up the priority a level. While normal fits in the matrix, a broken block in such a high visibility area that we are working on seems to warrant the attention.

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by creativecoder** [comment]
Related, though I'm not sure if this other issue has the same underlying cause, or not: https://github.com/Automattic/wp-calypso/issues/57837

**Comment by arcangelini** [comment]
I am still trying to track this down but here is what I got so far. I am not sure where this is coming from exactly but it is safe to say there is a discrepancy somewhere in how the block is being rendered. The block is rendering with a padding element that segregated like this `padding-top:2em;padding-right:2em;padding-bottom:2em;padding-left:2em` but the block save is expecting it to appear with a consolidated padding like this `padding:2em`. I will keep looking and see what I can find.

I have tracked down the original pattern and there do not seem to be any issues there.

**Comment by creativecoder** [comment]
Related discussion: p7H4VZ-3f8-p2

Possible fix: D70425-code

**Comment by p-jackson** [comment]
D70425-code has been deployed. I ran through the steps to reproduce and didn't get any validation errors, but I also never saw the issue to begin with. Would you mind retesting @donalirl ?

**Comment by arcangelini** [comment]
Tested on WordPress.com and not seeing the issue anymore. Closing, but feel free to open again if it is still having.

<img width="342" alt="Markup 2021-12-01 at 18 56 37" src="https://user-images.githubusercontent.com/33258733/144287936-2fd48018-461f-49d6-a5a9-c848e1e162a7.png">

**Comment by donalirl** [comment]
> D70425-code has been deployed. I ran through the steps to reproduce and didn't get any validation errors, but I also never saw the issue to begin with. Would you mind retesting @donalirl ?

Yes, the errors are gone now on all four patterns I reported 👍
