### ISSUE TITLE
Can't Upload Media files Using Google Chrome Browser

### ISSUE THREAD

**Issue by jromales** [Automattic/wp-calypso#58152]
### Quick summary

Uploading Media files does not work both in Calypso and WP-Admin (And in both Simple and Atomic sites). The issue seems to happen when using the Google Chrome browser. It works using Firefox or other browsers. 

### Steps to reproduce

1. In Calypso, go to Sites > Media and click "Add New" button.
![Screen Shot 2021-11-17 at 11 52 23 AM](https://user-images.githubusercontent.com/89536719/142131555-624db5bb-1b83-44b8-9ae6-e658e1f27b36.png)

2. In Classic View, go to Media > Library > Click "Add New" > Click "Select Files".
![Screen Shot 2021-11-17 at 12 02 54 PM](https://user-images.githubusercontent.com/89536719/142132561-8088d164-e11e-4f4b-989b-d8bee38b90aa.png)

### What you expected to happen

It should open a pop-up window where you can select files from your computer.
![Screen Shot 2021-11-17 at 12 04 09 PM](https://user-images.githubusercontent.com/89536719/142132669-fbcd4701-e424-4f39-9d90-db93415af2eb.png)

### What actually happened

Clicking the "Add New" button does not do anything. 

### Context

32363602-hc 

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Other notes

No console errors or log errors

### Reproducibility

Consistent

### Workaround details

Use a different browser (like Firefox, Safari, Opera) temporarily.

**Comment by Robertght** [comment]
@jromales this works ok on my end.

Were you able to check with other browser extensions as well?

**Comment by jromales** [comment]
@Robertght I haven't checked browser extensions, but I updated my Chrome browser from version 95 to Version 96 and I no longer experience the issue. 

![Screen Shot 2021-11-18 at 10 07 40 PM](https://user-images.githubusercontent.com/89536719/142430649-e119a8fa-0070-4346-b3d8-7097cefed1b3.png)

I'll recommend user to update their browser and see how that goes.

**Comment by Robertght** [comment]
As there were no other reports, I'm closing this, but please reopen if needed.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 ACTIONS
- Closed as not reproducible / no longer relevant
