### ISSUE TITLE
Import onboarding flow: "Enter your site address" not visible in full on mobile widths

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#58160]
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/start/importer/capture?siteSlug=slug.wordpress.com (replace slug.wordpress.com) with your WPcom site address
2. Reduce the screen dimensions to mobile width

#### What I expected

`Enter your site address` is visible in full.

#### What happened instead

It's not visible in full.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/18581859/142168316-e871e96f-1847-4cbf-b693-c3098bd02030.png">

**Comment by Robertght** [comment]
cc @bogiii

**Comment by bogiii** [comment]
The issue has been fixed. Thank you for reporting it! 🙏
