### ISSUE TITLE
[Bug]: Unable to remove Google Workspace subscription from Purchases page

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#58167]
### Quick summary

Users cannot remove a Google Workspace subscription from their list of purchases because nothing happens when they confirm the removal.

### Steps to reproduce

1. Log into a WordPress.com account that has a site with a Google Workspace account
2. Navigate to the [`Purchases` page](https://wordpress.com/purchases/subscriptions)
3. Click the Google Workspace Business Starter subscription
4. Click the `Remove Google Workspace Business Starter` option*
5. Click the `Next Step` button in the modal that just appeared
6. Select any radio button, then click the `Remove Now` button

> \* Note I've only tested the case where auto-renew was already off.

### What you expected to happen

To be redirected to the `Purchases` page with a success message.

### What actually happened

Well, nothing. Once I click the `Remove Now` button in the survey it freezes:

![image](https://user-images.githubusercontent.com/594356/142185406-b552a47e-8d9e-49dd-95cd-fd266172a764.png)

The following error is thrown in the browser's console:

![image](https://user-images.githubusercontent.com/594356/142185495-3a3ab53c-2f92-4cd0-98cf-8ec734079618.png)

![image](https://user-images.githubusercontent.com/594356/142185511-00745ae3-6eaf-45f2-972f-ab533fc6e121.png)

### Reproducibility

Consistent

**Comment by stephanethomas** [comment]
I've confirmed that the API endpoint returns a success flag set to `true`, and that `res` has `success` set to true here:

https://github.com/Automattic/wp-calypso/blob/7c6845443d578bd736c8ac0bcdbbe2ad7f4f0f3e/client/lib/purchases/actions.js#L35

I'm not sure why `response` is undefined here though:

https://github.com/Automattic/wp-calypso/blob/338dc0e6a9e1af565f6300fff9622fbe447cc8c0/client/components/marketing-survey/gsuite-cancel-purchase-dialog/index.jsx#L102

This code was refactored a month ago in https://github.com/Automattic/wp-calypso/pull/57141. Maybe @jsnajdr may know what's going on?

**Comment by jsnajdr** [comment]
> Maybe @jsnajdr may know what's going on?

Oops that was a regression 🙁 Please have a look at #58170, that should fix it.
