### ISSUE TITLE
[Bug]: Import onboarding flow: Importer shows a deleted WPcom site can be built, but it's not possible

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#58162]
### Quick summary

On the new `Import onboarding flow` (https://wpcalypso.wordpress.com/start/importer/capture?siteSlug=slug.wordpress.com), enter a WPcom site address that's deleted. The importer shows it can be built becuase it's already on WPcom, but the importer must show the site's already deleted. 

### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/start/importer/capture?siteSlug=slug.wordpress.com (replace slug.wordpress.com) with your WPcom site address
2. Enter a WPcom site address that is deleted, example `personalwpcomarun.wordpress.com`

### What you expected to happen

Importer shows that the site is deleted, so no imports can be processed at this stage.

### What actually happened

Importer reports that site is already on WPcom and shows a "Start building" button.

![image (12)](https://user-images.githubusercontent.com/18581859/142169778-07057aae-acad-425f-87ba-515da449787c.png)

### Context

Manual testing: pcmemI-dX-p2

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

NA

### Reproducibility

Consistent

### Severity

All

**Comment by bogiii** [comment]
@vishnugopal can we extend the `wpcom/v2/imports/analyze-url` endpoint with the additional information if the website is available?

For example, extending `platformData` field with a field `available`.
```
{
    platform: string;
    platform_data: {
        is_wpcom: boolean
        available: boolean; // <-- new field
    }
}
```

**Comment by vishnugopal** [comment]
Fixed in D70481-code
