### ISSUE TITLE
[Bug]: Import onboarding flow: Non-existent WPcom site cannot be imported but importer shows it can be imported, with a 404 preview

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#58161]
### Quick summary

On the new `Import onboarding flow` (https://wpcalypso.wordpress.com/start/importer/capture?siteSlug=slug.wordpress.com), enter a WPcom site address that does not exist. Example: `premiumwpcomarunn.wordpress.com`. The importer reports it can be imported, and shows a 404 "site not found" preview.

### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/start/importer/capture?siteSlug=slug.wordpress.com (replace slug.wordpress.com) with your WPcom site address
2. Enter a WPcom site address that does not exist, like `premiumwpcomarunn.wordpress.com`

### What you expected to happen

Importer must report that the site cannot be imported.

### What actually happened

Importer reports that site can be imported and shows a 404.
![image (10)](https://user-images.githubusercontent.com/18581859/142169089-c4787c72-c182-46d8-bc3b-b9e50d91ffdd.png)

![image (11)](https://user-images.githubusercontent.com/18581859/142169067-0088dd58-9e5a-4938-961a-64f4af367c83.png)

### Context

Manual testing: pcmemI-dX-p2

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

I tested importing to a simple site (which is the only type supported at the moment on the onboarding flow, I believe)

### Reproducibility

Consistent

### Severity

All

**Comment by bogiii** [comment]
@vishnugopal, could you please take a look and see is there anything that we can do to improve the `wpcom/v2/imports/analyze-url` endpoint and cover this case?

**Comment by vishnugopal** [comment]
Fixed in D70481-code
