### ISSUE TITLE
Blog Posts block becomes invisible with All in One SEO plugin.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#58164]
### Quick summary

When the Exford theme and All in One SEO plugin are active, the Blog Posts block is not showing up on the live page. I was able to reproduce this issue on test Atomic sites and self-hosted sites as well.

But it was not possible to reproduce the issue with other themes such as Twenty Twenty one.

I believe the issue is with the theme rather than the All in One SEO plugin since it is working fine with other themes.

### Steps to reproduce

1. In an AT site, create a page and add a Blog Posts block.
2. Make sure the site has Exford theme active.
3. Install the All in One SEO plugin and activate it.
4. You will notice that the Blog Posts block is no longer rendered on the live page.

### What you expected to happen

The Blog Posts block should render with Exford theme when All in One SEO plugin is active just like how it works properly with other themes.

### What actually happened

The Blog Posts block was not rendered with Exford theme and All in One SEO plugin.

### Context

Chat: 30074486-hc
Follow up: 4462000-zen

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Yes, Exford.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by JoshuaGoode** [comment]
I think this is beyond just that theme and a general conflict between the block and that plugin. 

A report on an Atomic site with Verity here: p9F6qB-7GS-p2 

Another internal report for another site with another theme and similar issue (the block wasn't missing it just wasn't displaying the correct posts):  p1637174078278700-slack-C03TY6J1A

**Comment by JoshuaGoode** [comment]
Renaming to remove specific Exford title.

**Comment by JoshuaGoode** [comment]
Closing this in favor of the internal report at p9F6qB-7GS-p2

**Comment by devNigel** [comment]
Interesting. The block was rendering with other themes like Twenty Twenty when I tested.
