### ISSUE TITLE
Videos UI: The play button hover state is too dark.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58181]
The Play buttons' hover state is now `opacity: 1%`.

<img width="614" alt="Screen Shot 2021-11-17 at 8 24 10 AM (2)" src="https://user-images.githubusercontent.com/349751/142240151-1ea62a74-5adc-45ae-9381-a4f3b9de52d0.png">

**Comment by blackjackkent** [comment]
I can't reproduce this. 🤔 I checked out the most recent version of trunk just now and see it going between 100% and 80% as expected.

**Comment by andres-blanco** [comment]
I can reproduce on WP.com production, on dev it works as expected.

**Comment by blackjackkent** [comment]
Huh. Yeah, you're correct. That's super weird. 🤔 Looking further.
