### ISSUE TITLE
Videos UI: We need to acknowledge non-English users of the videos being English only.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58206]
Brought up by @ianstewart : it would be considerate when displaying these videos to non-English users to visually inform them that the videos are in English. We could also give them a way to somehow request translation in their own language.

Note that the videos UI is currently only available to English users only, gated by the display of the educational card on My Home.

**Comment by kwight** [comment]
@ollierozdarz Would you have any ideas or preferences for what this would look like?

**Comment by ollierozdarz** [comment]
Good idea. I'll add this to the list of priorities.

**Comment by kwight** [comment]
Any progress on this @ollierozdarz ? If not, just let us know, and we can come up with something too. 👍

**Comment by ollierozdarz** [comment]
Nothing on it yet from my end @kwight. Happy to collaborate ideas back and forth.

**Comment by kwight** [comment]
@ollierozdarz @blackjackkent How about we pop up an [info notice](https://wpcalypso.wordpress.com/devdocs/client/components/notice/README.md?term=notice) upon opening the UI in a language other than English? It could say, "We're sorry, these videos are only available in English at this time. Please let us know at support@wordpress.com if you would like them translated to your language." Super long for a notice... 🤔 

It seems like it should be something that overlays the UI somehow, and can be dismissed – a modal over the UI (can we even do that?). 🙃 @blackjackkent feel free to see what you can come up with.

**Comment by ollierozdarz** [comment]
@kwight that sounds like a pretty good idea. Do you know where I can see a demo of that info notice? I was thinking something like a snackbar-esqe notice that's not incredibly in your face and dismissible would do the job.

Some further simplification to that wording could be:

"These videos are currently only available in English. Please [let us know](support@wordpress.com) if you would like them translated."

**Comment by arthur791004** [comment]
@ollierozdarz I think you can see the notice component [here](https://wpcalypso.wordpress.com/devdocs/design/notice) or maybe we can use the [banner component](https://wpcalypso.wordpress.com/devdocs/design/banner) stick to the top or bottom of the video section.

**Comment by blackjackkent** [comment]
@ollierozdarz I took @arthur791004 's suggestion of using the notice component and put this together: 

![image](https://user-images.githubusercontent.com/13437011/145894330-ff2d3611-0b36-4f85-9642-ab2caeef7b80.png)

What are your thoughts on this solution?

/cc @kwight

**Comment by kwight** [comment]
Let's leave this open until it's actually readable in the mag16 languages.

**Comment by ollierozdarz** [comment]
@kwight I think this solution will be fine. Are we able to move it to the top of the page please? (see below).

<img width="1672" alt="Screen Shot 2021-12-16 at 4 04 36 pm" src="https://user-images.githubusercontent.com/67085494/146317185-a87f6a9c-f297-4cc1-b9d8-df0a88a03dbc.png">

Also if we're open to adjusting the styles (since this screen is largely new), see above. [Figma](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/Blogger-Experience?node-id=2119%3A1111)

**Comment by kwight** [comment]
@ollierozdarz Sure, none of that should be a problem – @blackjackkent can you prepare a PR please?

**Comment by kwight** [comment]
The above PR is waiting on translations to ship.

**Comment by kwight** [comment]
Closed in #59675 .
