### ISSUE TITLE
Videos UI: We no longer have a "draft new post" link on desktop.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58205]
When we replaced the top right "draft new post" link with a "close" button, we lost that writing option for the user – unless they're on mobile, which still has the link (because we're still using a "back" link on mobile)

| Mobile | Desktop |
| --- | --- |
| <img width="376" alt="Screen Shot 2021-11-17 at 2 36 58 PM" src="https://user-images.githubusercontent.com/349751/142293750-eddc65d9-320f-42b3-b246-0d62315e169e.png"> | <img width="1690" alt="Screen Shot 2021-11-17 at 2 36 26 PM" src="https://user-images.githubusercontent.com/349751/142293759-fb0ed1de-9881-4f09-ba43-c80131447b29.png"> |

**Comment by kwight** [comment]
@ollierozdarz @ianstewart I'm just double-checking this is what we want?..

**Comment by ollierozdarz** [comment]
@kwight we only want this for when the user views this from My Home. When they view it during the onboarding flow, we still want the 'Draft your first post' link.

**Comment by kwight** [comment]
Closing in favour of removing the mobile "draft post" link in https://github.com/Automattic/wp-calypso/issues/58207.
