### ISSUE TITLE
Woo Installer: Add setTimeout delay to transfer step to avoid plugin install timing issues

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#58226]
Once the installers transfer completes we redirect to **wc**-admin, sometimes, this fails to load with permission errors as the plugin has not yet been installed, other times it redirects to the wrong wp-admin page (crowdsignal wp-admin?)

This is due to post transfer provisioning callbacks taking place in async jobs, this same issue will continue with the new plugin install flow coming in D70119-code.  

We need to add a some kind of delay before redirecting the user to wc-admin. This could be a complicated polling for plugin status or what I'm suggesting right now, adding a slight delay with a setTimeout in the transfer step. I think you could probably set something up with the progress bar so that the final 5% is this new delay.

- [ ] Add a delay to the [transfer step](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/woocommerce-install/transfer/index.tsx#L81)

**Comment by allilevine** [comment]
We've also previously addressed the permission error by pre-logging in the user. See https://github.com/Automattic/wp-calypso/pull/55029

**Comment by lsl** [comment]
Not something I'm willing to bet on but I'm pretty sure the permission error is a bit of a red herring, you can still get into wp-admin, its just that the woo plugin hasn't been installed so wp-admins default response to accessing a page that doesn't exist is shown.

**Comment by lsl** [comment]
Probably don't need this anymore but keeping it round as a fallback approach.

**Comment by retrofox** [comment]
should we close it?

**Comment by lsl** [comment]
I think we ended up with something like this anyway for UI effects but we don't require it anymore.
