### ISSUE TITLE
Woo Installer: plugin install and activate

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#58227]
The [woocommerce-installer](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/woocommerce-install/)'s transfer step needs to make use of our new api endpoints (12-gh-Automattic/woo-on-plans) to ensure woo + wc pay is installed and active.

The transfer step should:
- [x] Check if woo + wc pay is installed
- [x] Install them if they are not
- [x] Activate them if they are not

To implement this it's expected we'll replace our current usage of initiate-transfer with the new endpoint that can "repair" site state with atomic transfer and or install plugins as needed. The new endpoint will need to be polled until it returns a success status.

**Comment by allilevine** [comment]
See:

https://github.com/Automattic/wp-calypso/blob/5ce4b66ec705232f53c8a383d636cb730b9fdb5d/client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx#L321

and https://github.com/Automattic/wp-calypso/blob/a87658f46866d2455eb5d8f8c02df4da284cf014/client/state/plugins/installed/README.md

**Comment by allilevine** [comment]
Closed by #58848
