### ISSUE TITLE
Videos UI: Implement course management.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58249]
We need to implement course management for non-developers. The system will need to allow at least:

* creating and removing courses,
* adding and removing videos to courses,
* specific ordering of videos.

See: https://github.com/Automattic/wp-calypso/issues/56888

**Comment by kwight** [comment]
This has been mostly accomplished in:

* D71461-code
* D71681-code
*D71617-code
* D71649-code
* D71552-code

... and [others](https://github.com/orgs/Automattic/projects/148#column-17091266). The main piece remaining is translation of the post content for the management site.

**Comment by andres-blanco** [comment]
Closing, translation is already supported. PCYsg-DgC-p2
