### ISSUE TITLE
Videos UI: Implement user progress tracking.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58248]
We've launched without user progress tracking – let's get it added in. We need to be able to track a user's video views, and determine when they've watched all the videos in a given course (so that we can display calls-to-action to them in the UI).

We already have the ability to mark videos as viewed in the back-end by saving to user attributes. We also need to determine how to:

* save a user's place at what timestamp,
* trigger the "mark viewed" call from the UI on completion of a video,
* make the next video active on component load.

See: https://github.com/Automattic/wp-calypso/issues/56888

<img width="500" alt="Screen Shot 2021-11-18 at 11 54 26 AM" src="https://user-images.githubusercontent.com/349751/142487434-f2e5ae82-50e0-470f-ba77-1acfdbd40d2a.png">

**Comment by kwight** [comment]
Let's mark a video as watched at 10-20 seconds before the end (let's do a quick visual check of the existing course to confirm).

**Comment by kwight** [comment]
It looks like we should be able to use the `video` tag's [`timeupdate` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/timeupdate_event) to keep track of a user's progress through a playing video.

<img width="872" alt="Screen Shot 2021-11-22 at 2 38 35 PM" src="https://user-images.githubusercontent.com/349751/142945591-c090bdf4-e4d6-4254-b3a7-8c951107a638.png">

I checked our existing videos and ~10s before the end was generally good for all the videos, except the one 24s one. 🙃 This makes me think we should simply specify the "done" timestamp for each video individually, on the back-end. On the front-end, we have an event listener on `timeupdate` that watches for that timestamp, and when it's reached, we give the checkmark and inform the back-end that the video is considered complete.

**Comment by andres-blanco** [comment]
Actually the `timeupdate` event should be used in combination with [currentTime](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime) since the `timeStamp` property is an epoch timestamp.

**Comment by andres-blanco** [comment]
I've added two issues to complete this functionality.
* https://github.com/Automattic/wp-calypso/issues/58587
* https://github.com/Automattic/wp-calypso/issues/58588
