### ISSUE TITLE
Force Sells extension (Woo): Code snippet to force sell one product triggers critical error when trying to clear the cart

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#58241]
### Quick summary

If a user uses the [Force Sells](https://woocommerce.com/products/force-sells/?aff=10486&cid=1131038) extension in WooCommerce, and adds the recommended code designed to "Only force sell one product", attempting to remove an item from the cart after it is added will result in a critical error.

### Steps to reproduce

1. Activate the Force Sells extension;
2. Add a product to the *Synced Force Sells* option enabled by the Force Sells extension in the main product's *Linked Products* section;
3. Add the recommended code to "[Only force sell one product](https://woocommerce.com/document/force-sells/#only-force-sell-one-product)" using a plugin like Code Snippets to ensure that the "force sell" item only shows a quantity of `1` regardless of the quantity of the main product;
4. On the front end of the site, add the main product to the cart (you'll see that the "force sell" product is added correctly);
5. In the cart, attempt to remove the main product from the cart (nothing will appear to happen);
6. If you load another page, and attempt to empty the cart by hovering over the cart icon, the site will display a critical error message - "There has been a critical error on this website.", like this:

https://user-images.githubusercontent.com/2912202/142439430-1bf57359-560e-4904-af03-ffcb59a42d78.mp4

Note, I was able to reproduce this issue by deactivating all plugins except for the following:

1. Akismet
2. Code Snippets
3. Jetpack
4. WooCommerce
5. WooCommerce Subscriptions
6. Force Sells

The site has Storefront enabled.

Here is a demo of the issue:

https://user-images.githubusercontent.com/2912202/142441636-e91da2d1-49ed-46a3-ac42-20c70fb5f309.mp4

### What you expected to happen

I expected to be able to remove items from the cart as I can if I don't use the "[Only force sell one product](https://woocommerce.com/document/force-sells/#only-force-sell-one-product)" code.

If I don't add this code, the quantity count for the "force sell" item will increment in line with the main product quantity, even though the value of the "force sell" item will not increase.

### What actually happened

Adding the "[Only force sell one product](https://woocommerce.com/document/force-sells/#only-force-sell-one-product)" code leads to a critical error if you attempt to empty the cart.

### Context

I came across this while testing a solution for a customer.

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Other notes

Error in CLI:

```
[18-Nov-2021 14:37:57 UTC] PHP Notice:  is_singular was called <strong>incorrectly</strong>. Conditional query tags do not work before the queryis run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in /wordpress/core/5.8.2/wp-includes/functions.php on line 5663
```

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is to not use the "[Only force sell one product](https://woocommerce.com/document/force-sells/#only-force-sell-one-product)" code, and bear with the incremented quantity for the "force sell" item.

**Comment by kosiew** [comment]
Hi @pauljacobson ,

Thanks for reporting this and the detailed steps.

I would like to report this at https://github.com/woocommerce/woocommerce-force-sells/issues/new

Can you include the SSR for your test site?

**Comment by pauljacobson** [comment]
Hi there @kosiew, yes sure.

1. SSR - 2ac6e-pb/
2. Fatal error logs after reproducing the error - 2ac6f-pb/
3. Active code in Code Snippets - 2ac70-pb/

**Comment by kosiew** [comment]
Transferred to https://github.com/woocommerce/woocommerce-force-sells/issues/56
