### ISSUE TITLE
Launch Bar: Verify its layout and behaviour in non-EN and RTL languages.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58250]
With the launch bar being translated the past couple of weeks, let's verify its layout and behaviour again in non-EN and RTL languages. Non-EN LTR should be fine with D70182-code now deployed.

**Comment by andres-blanco** [comment]
In Arabic the Launch Bar looks completely broken:
<img width="1731" alt="image" src="https://user-images.githubusercontent.com/375980/160674716-9a944695-99b1-49b3-83ab-76d82dd0a4b0.png">

**Comment by sixhours** [comment]
Started a diff in D78118-code

**Comment by sixhours** [comment]
Fixed in D78118-code
