### ISSUE TITLE
Videos UI: Fetch user attributes to determine progress.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58256]
A user's progress is stored in a user attribute called `courses`. We'll need to fetch this for the current user when mounting the component.

Part of https://github.com/Automattic/wp-calypso/issues/58248.

**Comment by kwight** [comment]
There should already exist an endpoint for getting user attributes, since they're used often in Calypso.

**Comment by blackjackkent** [comment]
It doesn't seem like there's an existing endpoint for getting any random user attribute by key, but we do have an endpoint at `/wpcom-json-endpoints/class.wpcom-json-api-me-settings-v1-1-endpoint.php` which seems to have whitelisted keys that can be requested; seems like our best bet might be to add something there for our purposes?

**Comment by kwight** [comment]
> we do have an endpoint at /wpcom-json-endpoints/class.wpcom-json-api-me-settings-v1-1-endpoint.php

Yep, that sounds like it. I imagine there's a query component for it, so we would add that query component to our component to make sure the data is in state for us to use.

**Comment by andres-blanco** [comment]
functionality added in https://github.com/Automattic/wp-calypso/pull/58432
