### ISSUE TITLE
Videos UI: Show the course call-to-action on completion of all videos.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58259]
When a user has completed all of a course's videos, the course's call to action should be displayed.

<img width="1596" alt="Screen Shot 2021-11-18 at 1 55 45 PM" src="https://user-images.githubusercontent.com/349751/142503221-1e325e27-689d-4c50-a719-f790b2fd4643.png">

**Comment by andres-blanco** [comment]
This should be done after https://github.com/Automattic/wp-calypso/pull/58534 is merged
