### ISSUE TITLE
Widgets landing page doesn't take to Customizer, shows an image at the moment

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#58269]
Similar to links `https://wordpress.com/menus` and `https://wordpress.com/themes`, I am expecting `https://wordpress.com/widgets` to show the widgets area. It should show a list of sites, following which it must take one to the respective site's Customizer with widgets area focused. 

But right now, it redirects to this image file: https://wpcom.files.wordpress.com/2021/05/widgets.png

```
➜  ~ curl -LIX GET 'https://wordpress.com/widgets'
HTTP/2 301
server: nginx
date: Fri, 19 Nov 2021 01:25:24 GMT
content-type: text/html; charset=UTF-8
location: https://wordpress.com/widgets/
vary: Cookie
x-hacker: If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.
host-header: WordPress.com
x-frame-options: SAMEORIGIN
x-redirect-by: WordPress
x-ac: 1.bom _dca
strict-transport-security: max-age=15552000; preload

HTTP/2 302
server: nginx
date: Fri, 19 Nov 2021 01:25:25 GMT
content-type: text/html; charset=UTF-8
location: https://wpcom.files.wordpress.com/2021/05/widgets.png
vary: Cookie
x-hacker: If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.
host-header: WordPress.com
x-frame-options: SAMEORIGIN
link: <a1-1dAIa-p2>; rel=shortlink
x-redirect-by: WordPress
x-ac: 1.bom _dca
strict-transport-security: max-age=15552000; preload

HTTP/2 200
server: nginx
date: Fri, 19 Nov 2021 01:25:25 GMT
content-type: image/png
content-length: 7766
last-modified: Thu, 06 May 2021 11:53:25 GMT
expires: Tue, 14 Dec 2021 06:33:39 GMT
x-orig-src: 01_mogdir
accept-ranges: bytes
access-control-allow-credentials: true
access-control-allow-origin: uRxj-p2
vary: Origin
x-nc: MISS bom 28 np
x-content-type-options: nosniff
```

~I believe this is incorrect.~

**Note**: This is my assumption/understanding of how the link used to work in the past, not that it is how things must be. If this was never the case, feel free to let me know/close issue.

**Comment by mreishus** [comment]
I believe this would be adding a new section to calypso, which I've never done before and might be feature territory and not a bug. Does @Automattic/team-calypso have any guidance on how this should be handled?

My questions:
- Would there be links to this anywhere, or is it only for users typing "wordpress.com/widgets" into their address bar?
- Would the new section redirect to wp-admin/widgets.php or the customizer? Widgets.php is newer and I think we're trying to eventually get away from the customizer with FSE.
- Or would there be a calypso specific widgets page?

**Comment by noahtallen** [comment]
> Widgets.php is newer and I think we're trying to eventually get away from the customizer with FSE.

This sounds right to me. I would probably try to find who is working on the widgets integration for wpcom, and see what they think. (I'm not sure exactly who that is, though)

**Comment by mreishus** [comment]
@obenland Any input on where an issue related to widget integration for wpcom should go?

**Comment by obenland** [comment]
Could we start by examining the base assumption first?

> I am expecting https://wordpress.com/widgets to show the widgets area

@arunsathiya Could you help me understand how you arrived at that expectation? Did we use to link to `/widgets` at any point before?

**Comment by arunsathiya** [comment]
@obenland I am sorry, I don't have a documentation to back up my assumption with. I usually share these links on my chat with customers, which shows them a site picker, and eventually redirects to the corresponding part of Calypso or Customizer. `https://wordpress.com/menus` does that at the moment, and I remember that being the case for `https://wordpress.com/widgets` too but I could totally be misremembering.

I have updated the original post to reflect that this is my assumption at the moment.

**Comment by arunsathiya** [comment]
Since my original assumption was incorrect/the current behavior is expected, I'll close this issue. Feel free to reopen if something needs to be addressed here.
