### ISSUE TITLE
Plugin Details: Last updated formatting 

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58285]
### Details

Could we reformat the last updated date to reflect the site’s date format preference? It feels like an easy win to make this more accessible to customers and not have it feel unnecessarily technical.

![image](https://user-images.githubusercontent.com/12430020/142631374-bdc5ea0a-7534-402a-ae73-490f2ef66708.png)

**Comment by spraveenitpro** [comment]
Hi @cpapazoglou , Are you saying that the date should be in the format of November 11, 2021 just to confirm?

**Comment by cpapazoglou** [comment]
> Hi @cpapazoglou , Are you saying that the date should be in the format of November 11, 2021 just to confirm?

Yes, `November 16, 2021` would be far better or `1 week ago`
