### ISSUE TITLE
Plugin Installation: Revisit Thank You page designs

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58281]
While we have initially developed the thank you page as designed, the designs have changed. Let's make sure that we implement what we actually want.

Developed: https://wordpress.com/marketplace/thank-you/test
Designs: oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A46946

Also, the OK sign graphic has some [negative connotations](https://en.wikipedia.org/wiki/OK_gesture#Negative_connotations). 
![image](https://user-images.githubusercontent.com/12430020/142629781-33d347b8-db03-4e9f-af25-4f218937d86f.png)

- [x] Let's look into replacing the image for not wporg plugins
- [x] Let's try using the plugin icon for wporg plugins
- [x] Are we keeping the blue background or not?

Related: pdh6GB-6h-p2#comment-315

**Comment by cpapazoglou** [comment]
In the `thank-you` page we do a request
`https://public-api.wordpress.com/rest/v1.1/sites/[SITE_ID]/plugins?`
to get the results which don't include the plugin icon. We can either:

- enhance the API to include the icon
- or do another API call to the .org plugins (or .com) repo to get the icon

**Comment by SaxonF** [comment]
![image](https://user-images.githubusercontent.com/1072756/142977636-735a89d8-4096-4803-ba95-9fbeb2509126.png)


Now might be a good opportunity to start to align with some of the recent onboarding work. This removes the blue background and pulls in the plugin icon if available.

**Comment by cpapazoglou** [comment]
Thanks @SaxonF, the new design seems nice. Can you share the figma link?

Regarding the icon, the problem is, when a user uploads a plugin without an icon or not found in the wporg repo (eg a custom plugin). In these cases, we can show a default icon but the current one (OK sign) isn't the best solution. Can you supply as with a good replacement?

**Comment by SaxonF** [comment]
![image](https://user-images.githubusercontent.com/1072756/143157510-8b1c9be7-ed74-4071-b546-a0f892c2b29f.png)

@cpapazoglou for now a check icon might be ok. We have an illustrator we are working with who might be able to produce a "success" illustration for us at some point. Figma link [here](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=0%3A1)
