### ISSUE TITLE
Plugin Browser: Search results with 1 item

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58292]
### Details

When there’s one result, I see confusing placeholders (a box and lines):

![image](https://user-images.githubusercontent.com/12430020/142633430-13c150cd-4351-4327-ad6e-8ab4a95c8627.png)

### Tasklist

- [ ] Note “1 plugins” (remove s).
- [ ] Remove the stale / empty placeholder

### Related

pdh6GB-6h-p2#comment-315

**Comment by WBerredo** [comment]
> 1 plugins” (remove s)

This should be as simple as adding a singular and plural version of this text on the `translate` function.

https://github.com/Automattic/wp-calypso/blob/08961f239b9c353bb0b44983d9f7b014db038133/client/my-sites/plugins/plugins-browser/index.jsx#L227-L233

Should be replaced to: 
```js
this.props.translate( '%(total)s plugin', '%(total)s plugins', {
    count: pluginsPagination.results,
    textOnly: true,
    args: {
        total: pluginsPagination.results,
    },
} );
```

---

> Remove the stale / empty placeholder

The simplest solution would be adding `display: none` when the `.plugins-browser-item` div is empty

https://github.com/Automattic/wp-calypso/blob/303717a91628186becb560952d31116356d13306/client/my-sites/plugins/plugins-browser-item/style.scss#L15-L17

But a more complete solution would be to stop creating those elements at all as they are *intentionally* created here:
https://github.com/Automattic/wp-calypso/blob/038f3877a3e639dceda8ba5e5dcbf6bc18d94632/client/my-sites/plugins/plugins-browser-list/index.jsx#L47-L54

So removing those lines should do the work. But do we still *need to complete the list with empty elements to keep the grid drawn*?

**Comment by cpapazoglou** [comment]
> But a more complete solution would be to stop creating those elements at all as they are intentionally created here:

This code is > 5 years old, I assume this was needed for the CSS used at that time. By removing the JS we can also remove the CSS `.is-empty` rules. 

cc @gcsecsey in case he has any reason for not removing this.

**Comment by gcsecsey** [comment]
I think these placeholders were mainly there to pad out the Featured, Popular and New sections in the old designs. Now they don't seem to serve any purpose anymore from a UX standpoint, so I think we can safely remove them. 👍
