### ISSUE TITLE
Plugin Details: Sections dropdown on mobile polish

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58290]
### Details

It looks like the Description “tab” on mobile needs some attention in some color schemes and alignment adjustment with the other tabs?

![image](https://user-images.githubusercontent.com/12430020/142633096-d3aa4cbb-14c9-48dd-9d74-646d436fee76.png)

### Checklist

- [x] Fix the alignment
- [x] Review in all color schemes

### Related

pdh6GB-6h-p2#comment-315

**Comment by WBerredo** [comment]
I had checked the color schemes and the ones with darker backgrounds (Contrast, nightfall, and powder snow) need some additional work:

![Screen Shot 2021-11-29 at 09 12 38](https://user-images.githubusercontent.com/5039531/143876153-bba7fd10-8d6d-4a4c-bd89-ea90316287d5.png)


@SaxonF do you have any suggestions about those cases?

**Comment by WBerredo** [comment]
Another option is to remove the specific colors as specified on the figma layout and let the component handle the color scheme according the selected theme.  This was the selected approach on #58577 but we can discuss further solutions on this issue.

Ex: 

|Desktop | Mobile|
|-------|------|
|![Screen Shot 2021-11-30 at 10 04 21](https://user-images.githubusercontent.com/5039531/144066891-c933df45-bbae-43d5-8256-d63d91d87ba7.png)|![Screen Shot 2021-11-30 at 10 19 08](https://user-images.githubusercontent.com/5039531/144066836-e1aab889-40b0-4414-96e3-8a8ea5b07ffa.png)|
