### ISSUE TITLE
Blogger Experience: tailoring My Home  support articles

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58302]
### Background
We now have a [site_intent flag that is set](https://github.com/Automattic/wp-calypso/blob/8243889761d48643be746ddefd67b3ad3a5c5be2/client/lib/signup/step-actions/index.js) when the user selects their option from the Intent screen. See [site_intent types ](https://github.com/Automattic/wp-calypso/blob/c23d48f4c2b7878a4cd3712e9f3e7ea5286adf5f/client/signup/steps/intent/types.ts) for allowed values.  

We can use `site_intent=write` to conditionally show specific Support articles on My Home, tailored to bloggers' needs. 

This is the current Support Articles list
![image](https://user-images.githubusercontent.com/5665959/142666632-36a84d3c-44c3-4568-8db8-41f4860bf710.png)

### Goals
Provide the most relevant support articles to bloggers.
@jordesign and @kristastevens  can identify the docs/articles that we should show.
In the My Home Pod Seth McLellan compiled this[ list of /go articles for eCommercce & Bloggers](https://docs.google.com/spreadsheets/d/1mI6Wdo1H0zDu7dV6xlqvSi2uUfkU-zv7OfDU3xwSGa4/edit#gid=0)
Additionally, I recently came across this[ list of articles](https://docs.google.com/spreadsheets/d/1iur4ZptOSy_LyXpU5XtWcHBxqDOMSEGDvJdthdavfRI/edit#gid=1649656136) , maybe it is useful, maybe not. :)

### Dev Tasks
- [x] https://github.com/Automattic/wp-calypso/pull/58486

### Related
[Blogger Flow Project Thread](pdgK6S-78-p2)

**Comment by jordesign** [comment]
Love this - I'll put some time away tomorrow to come up with a suggested list of docs.

just one point of clarification - the current list is JUST support docs (as this is the 'Help' section).
Changing this to /go or other articles would be a functional change to they type of docs that are shown in this section - are we ok with this being inconsistent?

**Comment by kristastevens** [comment]
One question came to mind as I started to think about what might work well here. Is the list limited to support documents because of translation? Another way to word the question: is this My Home section shown to English language users?

**Comment by autumnfjeld** [comment]
@jordesign  Great question! And now that you asked that, I am remembering that [we used the /go list to create new "Grow & Learn" cards for eCommerce sites](https://github.com/Automattic/wp-calypso/issues/54863) - the list wasn't used for Support articles.  

So let's stick to /support articles.  I will edit the description of this issue.

@kristastevens  We would need to use support docs that are translated into our supported languages.  
The My Home section is translated and when users link out they see support doc in the language of their user settings (the language that My Home is shown in).

**Comment by autumnfjeld** [comment]
@jordesign  Having said that, if you think there are some cool /go articles that should be turned into Grow & Learn cards, we could open an issue for that. 

![bitmoji](https://sdk.bitmoji.com/render/panel/95caaa1e-9572-4e53-8013-e3e6215ae489-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=40)

**Comment by jordesign** [comment]
> So let's stick to /support articles. I will edit the description of this issue.

Good call! Here's the ones I'd call out. They're all focused on creating content, sharing it, and helping get traffic to the site.

In looking at them - the actual Titles used on the support doc aren't really helpful at all. I've added (in brackets) proposed strings of text we could use (seeing as the list is manually curated). Love your input on these @kristastevens 

* https://wordpress.com/support/sharing/ (Let others share your content)
* https://wordpress.com/support/publicize/ (Share your content to Social Media automatically)
* https://wordpress.com/support/subscriptions-and-newsletters/ (Let visitors subscribe to your content)
* https://wordpress.com/support/seo/ Learn about Search Engine Optimisation)
* https://wordpress.com/support/posts/ (All about Blog Posts)
* https://wordpress.com/support/site-verification-services/ (Verify your site with Google and other services)

**Comment by kristastevens** [comment]
@jordesign this is a great list! This is just a suggestion for the potential order they could appear in and some suggestions on the text in brackets. Let me know what you think. 

- https://wordpress.com/support/posts/ (All about blog posts)
- https://wordpress.com/support/subscriptions-and-newsletters/ (Encourage visitors to subscribe to your content)
- https://wordpress.com/support/publicize/ (Share your content to social media automatically)
- https://wordpress.com/support/sharing/ (Encourage visitors to share your content)
- https://wordpress.com/support/seo/ (Learn about how to get noticed by search engines)
- https://wordpress.com/support/site-verification-services/ (Verify your site with Google and other services)

**Comment by arthur791004** [comment]
@jordesign @kristastevens  Now the support articles would be

| Default | The user with write intent |
| - | - |
| ![image](https://user-images.githubusercontent.com/13596067/143409664-8a6dc64d-f0f5-42c1-ae8a-21ccec854bc8.png) | ![image](https://user-images.githubusercontent.com/13596067/143409620-2cf28fa6-f8bc-407c-be7b-36edb917e694.png) |

**Comment by kristastevens** [comment]
Looks good to me, @arthur791004!

**Comment by arthur791004** [comment]
Close it as https://github.com/Automattic/wp-calypso/pull/58486 is shipped!
