### ISSUE TITLE
Screen Options missing for the new Plugins browser page.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#58319]
### Quick summary

We recently introduced a new update that directs `Plugins > Add New` destination to point to Calypso Plugins page for Atomic sites.

Ref: p7DVsv-d0A-p2

The Calypso plugins search page lacks details like active installation number, and if it's compatible or untested, or reviews written by other users on clicking plugin details page.

The new Calypso Plugins page is surely a downgrade for those who are used to the WP Admin plugin browser page. We have an older report here: #43332

An easy way to fix this gap is to introduce the `Screen Options` for the new Calypso page so that users can easily switch to WP Admin page. 

### Steps to reproduce

1. Open an atomic site.
2. Go to `Plugins > Add new` and search for a plugin.
3. Search results lack lots of details that are available on WP Admin plugin search page.
on

### What you expected to happen

The Calypso plugin search page should include all necessary details that were present WP Admin page.

### What actually happened

The Calypso plugin search page lacks crucial details and makes it difficult for users to browse the plugins.

### Context

User report: 4530120-zen

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Users have to remember or bookmark the wp-admin plugin search page: `wp-admin/plugin-install.php`.

An easy alternative that we can implement is to add the Screen Options to switch to Classic view on the new Plugins page.

**Comment by Robertght** [comment]
cc @cpapazoglou in case this is related to the recent updates.

**Comment by arunsathiya** [comment]
One more report: 4532038-zen.

**Comment by cpapazoglou** [comment]
We would want to avoid redirecting users to Wordpress Core pages for installing plugins. What we can do though is enhance our Calypso screens. 

@SaxonF can we look into adding all relevant data from WP Core Plugins page to Calypso Plugins page?

|WP Core | Calypso|
|-------|------|
|<img width="606" alt="SS 2021-11-22 at 17 59 49" src="https://user-images.githubusercontent.com/12430020/142894142-55366aeb-c6da-44fa-8018-3e6761a885ba.png">|<img width="1081" alt="SS 2021-11-22 at 18 00 07" src="https://user-images.githubusercontent.com/12430020/142894197-815a6b96-4108-4c0a-bf17-5b7a9c403d46.png">|

**Comment by SaxonF** [comment]
Hi @cpapazoglou , a couple options for you.

![image](https://user-images.githubusercontent.com/1072756/142972024-eac3e475-5875-4505-9fe3-4a02513a2c92.png)
This shows install count by default. I'm also wondering whether we only need to highlight if a plugin is incompatible.

![image](https://user-images.githubusercontent.com/1072756/142972502-2f36dde0-c4ba-445f-9b79-4401774d3a28.png)
This condenses metadata by using icons and always shows compatibility.

![image](https://user-images.githubusercontent.com/1072756/142972039-67777446-7465-4e38-b4a2-edc382793de4.png)
This hides install count on hover. The thinking is that the number of reviews plus date updated give _some_ indication of popularity/social cred.

**Comment by cpapazoglou** [comment]
> Hi @cpapazoglou , a couple options for you.
> 
> ![image](https://user-images.githubusercontent.com/1072756/142972024-eac3e475-5875-4505-9fe3-4a02513a2c92.png) This shows install count by default. I'm also wondering whether we only need to highlight if a plugin is incompatible.
> 
> ![image](https://user-images.githubusercontent.com/1072756/142972502-2f36dde0-c4ba-445f-9b79-4401774d3a28.png) This condenses metadata by using icons and always shows compatibility.
> 
> ![image](https://user-images.githubusercontent.com/1072756/142972039-67777446-7465-4e38-b4a2-edc382793de4.png) This hides install count on hover. The thinking is that the number of reviews plus date updated give _some_ indication of popularity/social cred.

Thanks for the new designs @SaxonF! 

> I'm also wondering whether we only need to highlight if a plugin is incompatible.

At this point, we probably not but it's nice to have it for future versions. I think this version
![image](https://user-images.githubusercontent.com/12430020/143016895-decfd241-3e2a-4310-a1e1-3041b35b6c09.png)

is verbose and pleasant to the eye too. It includes rating, active installations and last updated. Can you share the figma link?

**Comment by SaxonF** [comment]
Apologies @cpapazoglou , Figma can be found [here](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=0%3A1)

**Comment by gavande1** [comment]
The sentence  `incompatible with your version of WordPress` is checked with the help of the [is_wp_version_compatible](https://developer.wordpress.org/reference/functions/is_wp_version_compatible/) function.

**Comment by kerrynicl** [comment]
28000157-HC User requesting redesign as above as
> The one showing now does not provide an efficient overview of items such as compatibility, rating, last updates for plugins

**Comment by JoshuaGoode** [comment]
If a user absolutely needs the core `Add New` plugin page, and they are Atomic, they can navigate directly to `wp-admin/plugin-install.php`
