### ISSUE TITLE
FSE beta: Footer template broken

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#58329]
#### Steps to reproduce

1. Starting at URL: https://domain.com/wp-admin/edit.php?post_type=wp_template_part
2. Design a footer template.
3. Add it to the Index template from the Site Editor.
4. Publish the Index template including the Footer template.

#### What I expected

The footer to appear as I designed in the Footer template.

#### What happened instead

Footer looks broken.

#### Screenshots demonstrating the problem

Footer templates in the editor:
![Footer Template in the Site Editor](https://user-images.githubusercontent.com/1519466/142779353-27e4d9d2-e051-47da-b5a5-8fc1b1434215.png)
![Footer Template in the Editor](https://user-images.githubusercontent.com/1519466/142779365-6ec874c4-8a1e-49cb-bfcf-3ef12ce7047c.png)

Footer [on the site](https://chait.blog/about/):
![Footer on the site](https://user-images.githubusercontent.com/1519466/142779374-e42c6ae0-fc09-42e0-99db-25c3d7ce461f.png)

**Comment by Addison-Stavlo** [comment]
I am not currently able to repro and think this has been resolved in the last 7+ months.
