### ISSUE TITLE
FSE: Update link for "Edit homepage" checklist task

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#58328]
### What

Update the "Edit homepage" checklist task to direct to the Site editor rather than the post editor

### Why

Give access to FSE features for editing the home page, including header and footer editing.

### How

<img width="757" alt="image" src="https://user-images.githubusercontent.com/1699996/142772797-4d5069ff-f0d9-48ce-a73e-14779e48f34b.png">

**Comment by davipontesblog** [comment]
This is what I see now with WordPress 5.9 in WordPress.com simple site:

<img width="955" alt="Screen Shot on 2022-01-26 at 11-14-31" src="https://user-images.githubusercontent.com/31009008/151202016-e6c30c87-c49c-400c-aad4-f54380e1735b.png">

It does take me to the site editor too. Closing this as done.

**Comment by creativecoder** [comment]
Thanks @davipontesblog !

This was updated in https://github.com/Automattic/wp-calypso/pull/59745
