### ISSUE TITLE
Advanced SEO: Preview custom meta changes

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#5833]
In #5757 we opened up the ability for users to modify the site meta information available to search engines. Unfortunately, there's no clear connection displayed between those changes and how the search results are likely to appear.

A simple display could close that gap by "previewing" in real-time the way the changes are anticipated to impact the search results.

![](https://cldup.com/OXThr1r4IW.png)

**Vocabulary**
In order to keep communication clear, I have borrowed the vocabulary found [in one of Google's pages](https://support.google.com/websearch/answer/35891?hl=en)

 - **Title**: The first blue line of any search result is the title of the webpage. Click the title to go to the site.
 - **URL**: In green, you'll see the web address of the web page.
 - **Snippet**: Below the URL is text that helps show how the page relates to your query. The words you search for will show in bold to make it easier for you to decide if the page has what you're looking for.

**Comment by drw158** [comment]
For the preview, I think it should be wrapped in a preview "box" like in Sharing:

![screen shot 2016-06-06 at 4 57 06 pm](https://cloud.githubusercontent.com/assets/618551/15839313/538f1244-2c08-11e6-964e-5c829b4c5016.png)

I don't think it's a component.

Instead of "Preview" it should read "Google Preview" I think.

**Comment by dmsnell** [comment]
thanks @drw158 - here is an update!

![screen shot 2016-06-06 at 3 23 35 pm](https://cloud.githubusercontent.com/assets/5431237/15839838/b4ad0206-2bfa-11e6-9ef1-de6a3b4eacb1.png)

it raises the question of whether we should adopt a similar UX to sharing with the callout boxes, like "Edit description" and such. I'm not sure I think it's a good idea because it involves more clicks and what not, but maybe come the time we have three separate text fields it might feel more natural with the callout boxes.

**Comment by drw158** [comment]
> it raises the question of whether we should adopt a similar UX to sharing with the callout boxes, like "Edit description" and such.

Possibly...I don't think we should do that for this round though.

**Comment by dmsnell** [comment]
@drw158 + @roundhill in the next iteration of this, we could actually make an API call for the title and content of the first blog post on a given site and show the _real_ preview based on that information. The only problem is that there might be a delay in loading it and it could get out of sync with what's being typed. Hrm... maybe that's not so good of an idea.
