### ISSUE TITLE
[Bug]: refreshing at design picker step at onboarding shows white screen

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#58339]
### Quick summary

When refreshing the page when at design picker, onboarding breaks.

### Steps to reproduce

1. Create a new site from `/start` as logged in user, and pass domains, plans
2. At write/build question, note URL and answer build
   
    <img width="1005" alt="Screenshot 2021-11-22 at 10 55 23" src="https://user-images.githubusercontent.com/87168/142832300-01940106-6a63-4e5d-8f1c-3a31b3962491.png">
 
3. At design picker, note how URL has lost site URL
    <img width="601" alt="Screenshot 2021-11-22 at 10 55 34" src="https://user-images.githubusercontent.com/87168/142832338-bd029131-2ada-4de6-8cb9-3428fd94f6e6.png">

4. Refresh the page, get error in console:
    <img width="1383" alt="Screenshot 2021-11-22 at 10 55 45" src="https://user-images.githubusercontent.com/87168/142832410-f46a3465-f157-4d8b-b19d-7f67e247c9f0.png">
  

### What you expected to happen

Refresh to just work.

### What actually happened

White screen.

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Consistent

cc @autumnfjeld  for triage.

**Comment by autumnfjeld** [comment]
Note for Ganon: Consider  that a fix might also address launch flow fix.
