### ISSUE TITLE
Videos UI: Enable for non-English users.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58364]
The videos UI was launched for English users only. Let's enable it for everyone.

- [ ] Verify translations for the mag16 are ready.
- [ ] Do additional non-EN and RTL testing.
- [x] https://github.com/Automattic/wp-calypso/issues/58206
- [ ] Remove the EN-only gate in My Home.

**Comment by blackjackkent** [comment]
This check is added server-side at `wp-content/lib/home/cards.php`. I think we should be able to safely remove it, but let's make sure we test thoroughly in multiple languages to make sure the experience is solid.

**Comment by andres-blanco** [comment]
I think everything in the list is done. The gate seems to only be up for Japanese: `wp-content/lib/home/cards.php?r=90e61e33#99`. I will look into the status on this translations.

**Comment by andres-blanco** [comment]
It looks pretty much done in Japanese also
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/375980/160449050-bbf6e180-5ec1-4607-8367-d44cf34103e9.png">

I will setup a diff to remove the JP gate.

**Comment by andres-blanco** [comment]
D77686-code
