### ISSUE TITLE
Advanced SEO: Add Post/Page Title Formatting Tool

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5836]
Enhance the `settings/seo` page with new tabs that will allow a user to customize how their titles appear on their site, in order to tweak how they appear in search results.

At a minimum we should support rearranging the `Site Title`, `Tagline` and `Post Title`, along with separator characters. We could use 'chips' to make it easy to rearrange the bits of the site title.

Early design:
![artboard copy 12](https://cloud.githubusercontent.com/assets/618551/15902277/c2e5cdb2-2d6c-11e6-92b5-42e62541ea70.png)

**Comment by drw158** [comment]
My first idea was to include the meta description as well, so that users could alter the default description for all of their posts/pages/etc. After thinking about it, that doesn't make much sense, because their description should just be the content of the page. Of course, they can provide a custom one in the new editor description box.

**Comment by drw158** [comment]
Some more thoughts:

With the new Search Preview #5839, users will instantly see the result of their meta changes, at least for the front page. This should include changes to the proposed meta title field.

I think editing the meta title for any page should be a paid feature. This includes all of the segmented control options shown in the mockup (Front Page, Posts, Pages, etc). It should look disabled for free users. Free users _can_ change the title by updating their site title and tagline, but they won't be able to do anything custom.

**Comment by drw158** [comment]
About the concern of editing the meta title in 2 places: general settings and SEO settings:

I don't think this is much of an issue, with the new UI we are proposing. I don't think of the new "Title Format" field as overriding an existing meta title field in general settings. I think of this new field as the "canonical" one that is just using the `site title` and the `tagline` as parameters, forming the meta title tag. 

It makes more sense if you think of the Site Title as "Site Name". Site Name is a generic setting that we just happen to use for the meta title tag. Also the site name and tagline are unique in that they are displayed on the front end of the site.

**Comment by dmsnell** [comment]
This is a per-post setting, right? I think that part is a bit confusing with it being in the post editor. If it's per-post, maybe some clarification in the accordion would help with that; it per-site, I'm not sure how to follow the connection in the editor.

**Comment by drw158** [comment]
The settings shown in the mockup above are site settings, the title format for posts, pages, etc.

The the title input in the accordion shown in #6069 actually can't be edited, but the user can either modify their post title, or go to Settings > SEO and change the format using the chips.

**Comment by drw158** [comment]
I'll add another concern here: allowing the user to insert plain text for the Post (and maybe others) title input could be damaging. For example, I could just type in `Dinner Recipe` in the Post title input (ignoring the chips) and that would be by meta title for every one of my posts. That'd be very harmful to their SEO I think.

**Comment by dmsnell** [comment]
> allowing the user to insert plain text for the Post (and maybe others) title input could be damaging

do you recommend adding just a few separators then?

**Comment by drw158** [comment]
In the case of the Post Title format, we could just do something like: if the Post Title chip is not present in the input, then show a warning.

**Comment by drw158** [comment]
My ideas for the different chips are shown above https://github.com/Automattic/wp-calypso/issues/5836#issuecomment-224304691

but, some don't make sense for certain meta titles; You wouldn't want a Post Title for the Front Page, for example.

We could either not show certain chips, or we could show them as "disabled".
