### ISSUE TITLE
Videos UI: The bottom footer is not fixed on mobile.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58366]
The mobile footer should be fixed, so that the Back button is always visible, regardless of screen size or content.

<img width="326" alt="Screen Shot 2021-11-22 at 1 54 43 PM" src="https://user-images.githubusercontent.com/349751/142940830-1b33573c-702d-462f-9dc0-fed8c809082a.png">

**Comment by kwight** [comment]
Now I'm not sure; the mockup on the left implies it's not fixed, while the one on the right implies it is – @ollierozdarz which do you prefer?

<img width="800" alt="Screen Shot 2021-11-22 at 1 52 50 PM" src="https://user-images.githubusercontent.com/349751/142941003-f4b4f2b8-9188-4577-8705-f1dad67d5b5a.png">

**Comment by ollierozdarz** [comment]
@kwight the intent for this was to be fixed to the bottom only for mobile viewports.
