### ISSUE TITLE
Gravatar.com: Website Images broken

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#58371]
### Quick summary

The website images on Gravatar.com are not loading within the account, or on the site when visited. It seems these images may only display on mobile/tablet sized devices, but they currently all appear broken, for all accounts.

In account on Gravatar.com:
<img width="767" alt="Screen Shot 2021-11-22 at 5 10 53 PM" src="https://user-images.githubusercontent.com/31680407/142942654-8e1d727f-dc74-400e-97c3-3e22f15f9bed.png">

Live site: 

![259557314_285744136813117_5990655900697158711_n](https://user-images.githubusercontent.com/31680407/142942930-513c6cd7-5b7d-449b-99b6-b2a6a5761b02.jpg)

Reported by a WordPress.com customer in 29844088-hc

### Steps to reproduce

1. Log in at Gravatar.com
2. Click My Profile at the top
3. Try to add a website

### What you expected to happen

That the thumbnails would display

### What actually happened

There are broken  images

### Context

Reported by a WordPress.com customer in 29844088-hc
This may not be the correct repo so please move as needed

### Reproducibility

Consistent

### Severity

All

**Comment by happychait** [comment]
Also website preview doesn't seem to come up on the profile page, for example, at http://en.gravatar.com/happychait despite having a site attached to the profile.

**Comment by Robertght** [comment]
I can't seem to replicate this with my test sites, on your accounts, or the user's. 

Could you double-check if this is still happening on your ends @msilbers @happychait ?

**Comment by msilbers** [comment]
@Robertght this was resolved by Greenhouse without the issue, I'll close it now
