### ISSUE TITLE
Blogger Experience: tailored prompt text in the editor

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58374]
## Blogger Experience: provide a more inviting prompt to new bloggers
We now have a [site_intent flag](https://github.com/Automattic/wp-calypso/blob/8243889761d48643be746ddefd67b3ad3a5c5be2/client/lib/signup/step-actions/index.js) that is set when the user selects their option from the Intent screen. See [site_intent types](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/intent/types.ts) for allowed values.  We can use this to customize the editor experience.

CURRENT/BEFORE
![image](https://user-images.githubusercontent.com/5665959/142947944-3f1e70ab-dc06-4bc9-878e-7846795c874d.png)

AFTER
![image](https://user-images.githubusercontent.com/5665959/142947829-67eec5a0-7429-4dfa-b7c0-82dd24c1a763.png)

See A friendlier way to post: p9Jlb4-2XM-p2

## User facing criteria
* ToDo: finalize design specs for this
* ToDo: finalize copy

## Dev tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/58741

## Related
A friendlier way to post: p9Jlb4-2XM-p2
More advanced versions of the concept of welcoming new bloggers: Your first post made easy

**Comment by ollierozdarz** [comment]
I think from a design point of view we keep it incredibly simple and just change the placeholder text and title text initially, keeping the interaction design the same. The big win is that if we create a framework for this change, we can then have a way to iterate on it over time.

Note: Let's keep this under the ('write') flag. We'll then be able to have something to compare it to for performance. 

<img width="1680" alt="Friendlier-wording" src="https://user-images.githubusercontent.com/67085494/143953702-455f578f-390d-4204-811b-4935c287c6fa.png">

<img width="1680" alt="Friendlier-wording-spec" src="https://user-images.githubusercontent.com/67085494/143953814-40900525-fdf7-4f35-bc3d-17185cd63315.png">

**Comment by arthur791004** [comment]
@ollierozdarz I saw p9Jlb4-2XM-p2, and it showed the two cases for the placeholder text as followed:
* “Write your post“ if all of the lines are empty
* ”Type ‘/’ to insert a block, or continue writing” if one of the lines is not empty

I just want to confirm that we only need to change the text to “Start writing or type ‘/’ to insert a block” for the “post” no matter the user types any text or not, right?

If not, it might not easy to change the placeholder dynamically and we need to do some investigation.

> We'll then be able to have something to compare it to for performance.

Besides, I'm not sure how to compare the performance before and after 🤔

**Comment by arthur791004** [comment]
Close it as https://github.com/Automattic/wp-calypso/pull/58741 is merged!
