### ISSUE TITLE
Videos UI: Add a "completed" timestamp to each existing course video.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58373]
We need to keep track of users' progress through the videos, but we all know that many people don't watch a video until its very last second – but can certainly consider the video "completed". Since all videos are unique, with different cutoff points for meaningful content, let's add a specific timestamp to the video definitions in the `courses` library server-side. This will be watched for on the front-end by a `timeupdate` event listener.

See: https://github.com/Automattic/wp-calypso/issues/58248#issuecomment-975981590

**Comment by andres-blanco** [comment]
D70522-code
