### ISSUE TITLE
Woo Installer: Implement calypso fetch code for new public-api transfer endpoint

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#58384]
We're modifying an existing endpoint to handle woo transfer and installation 12-gh-Automattic/woo-on-plans. The patch is here: D70745-code We need a calypso fetch and response implementation under `client/state` for use with redux. 

We're adding an additional endpoint to handle woo installation on Atomic. The patch is here: D70860-code

The current [fetch transfer status](https://github.com/Automattic/wp-calypso/blob/32e9210d0dea12db56c29a4c523ccfb37768c9ef/client/state/automated-transfer/actions.js#L39) action has some polling logic behind it we could model this after, but ideally we would do something with async functions that re-poll in a loop instead.

- [x] Can fetch transfer + plugin state
- [x] Can initiate transfer 
- [x] Can initiate plugin repair (same as transfer but might need extra params?)

**Comment by allilevine** [comment]
Closed by #58709
