### ISSUE TITLE
Woo Installer: Implement mobile ux and new design

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#58387]
Implement [new design](https://github.com/Automattic/wp-calypso/pull/58024#issuecomment-977556114) for the steps in /signup/steps/woocommerce-install.

- [x]  #58468
- [x] #58470

**Comment by lsl** [comment]
Some mobile designs to work from, cc @SaxonF 

pdhcfv-5D-p2#comment-120
r6eTqDpL2GGk96hcPLhsBb-fi-431%3A2447
https://github.com/Automattic/wp-calypso/pull/58024#issuecomment-977556114

**Comment by Rolilink** [comment]
I am a little confused on what each check of this entails in the Figma design Maybe we can divide this ticket per screen @allilevine?

I can totally create a new ticket for the Confirm/warning step with this design r6eTqDpL2GGk96hcPLhsBb-fi-431%3A2447.

**Comment by allilevine** [comment]
> I am a little confused on what each check of this entails in the Figma design Maybe we can divide this ticket per screen @allilevine?
> 
> I can totally create a new ticket for the Confirm/warning step with this design

@Rolilink I updated the description to clarify, but feel free to make edits / open additional issues. I think starting with the Confirm/warning step would be great.

**Comment by Rolilink** [comment]
@allilevine added new issue #58468 and assigned it to me.

**Comment by Rolilink** [comment]
@SaxonF added #58470 to discuss any changes needed for the transfer step / progress bar

**Comment by pablinos** [comment]
Closing this for now. We open separate issues for the new landing page design and any specific problems we find.
