### ISSUE TITLE
Woo Landing: Point the landing page at the new installer

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#58385]
Point the landing page CTA's at the new installer

- [ ] Business simple sites => installer confirm step (warnings)
- [ ] Business atomic sites => installer confirm step (double check displayed when already atomic transfer)
- [ ] Non business => checkout upgrade with redirect => installer confirm step (warnings)

**Comment by retrofox** [comment]
[This PR](https://github.com/Automattic/wp-calypso/pull/58702) takes over the first and third items from the list. I'm sorry of overlapping efforts here :-(
For the second one, it is possible that the new transferring endpoint will tackle it? cc @DustyReagan @pablinos

**Comment by lsl** [comment]
Yes but I think for now we can keep the second flow running through storeSetup in the old installer until its ready.

If there are no warnings/eligibility checks needed I think the confirm step can just auto confirm and move to transfer. Was there some reason not to do that? (I seem to recall thinking maybe we wanted a confirmation step regardless but I'm struggling to think what the message on screen would be given the context the user just clicked a button and is wondering why it isn't doing the thing yet.)

**Comment by retrofox** [comment]
> If there are no warnings/eligibility checks needed I think the confirm step can just auto confirm and move to transfer. Was there some reason not to do that?

From a technical perspective, I don't think so. I thought it was part of the initial design when there were a couple of screens/steps. Each step had a confirm button with different text.
We can skip it in case everything is ok.

**Comment by allilevine** [comment]
Latest PR: https://github.com/Automattic/wp-calypso/pull/59274

**Comment by allilevine** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/59274
