### ISSUE TITLE
Not able to map domain without a paid plan.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#58394]
### Quick summary

Previously, it was possible to map a domain to a free site by paying 13 USD. 

WordPress.com also says

`Domains purchased on a free site will get redirected to 1234testbing.wordpress.com. If you upgrade to the Personal plan, you can use your own domain name instead of having WordPress.com in your URL.`

However, with the new Domain Connection flow, it is not possible to map a custom domain to a free site. Trying to map a domain automatically adds the WordPress.com Premium plan to the cart. When removing the WordPress.com Premium plan, it also removed the custom domain.

### Steps to reproduce

1. Open a free site without any custom domain added to it.
2. Go to Upgrades > Domains > Just search for a domain.
3. Enter a domain that you already own.
4. Scroll down and select `Already own a domain? You can use it as your site’s address`.
5. Click Select on `Connect your domain`.
6. You will notice WordPress.com Premium plan is automatically added to the cart.
7. Click on `Remove from cart` and the cart gets emptied.

Screenshot:

![image](https://user-images.githubusercontent.com/33957570/143013872-8f2e7445-629c-48b9-b2d6-5900aee75e14.png)

### What you expected to happen

It should be possible to map a domain without purchasing a plan.

### What actually happened

It was not possible to map the domain.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
Thank you for reporting this @devNigel !

I was able to replicate the behavior where the Premium plan is added to the cart when trying to connect a domain.
However, a connected/mapped domain will only work if there's at least the Personal plan present.

cc @Automattic/pod-domains for a second look.

**Comment by devNigel** [comment]
>However, a connected/mapped domain will only work if there's at least the Personal plan present.

Yes, we also clarify that to the user. There's a notice on the page to search domain.

**Comment by devNigel** [comment]
~~Looks like the issue has been resolved. No longer able to reproduce it.~~

**Comment by devNigel** [comment]
The issue is still there: 34802247-hc

**Comment by delputnam** [comment]
@devNigel This is the expected behavior. The user is not PWPO exempt, thus they will need to purchase a paid plan in order to map a domain.  Please see: P6Ya1B-zK-p2 for information about this policy.

**Comment by devNigel** [comment]
@delputnam AFAIK, PWPO is about setting domain primary without a paid plan. As seen in this notice, it should be possible to map a domain without a plan and have it redirected to the free address. 

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/33957570/162136308-dfe5d4fa-b864-4aeb-8cc1-6436555f0501.png">

`Domains purchased on a free site will get redirected to 1234testbing.wordpress.com`

**Comment by devNigel** [comment]
I reviewed the [P2 carefully](p7DVsv-8uh-p2) and looks like it is no longer possible to have a new DWPO ( which is what I was trying to do ). 

Closing this.
