### ISSUE TITLE
Reader: when a wordpress.com site is deleted, it continues to be shown in the following list

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5840]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Follow a test WordPress.com site (eg. testinghots3.wordpress.com)
3. Delete the test WordPress.com site
#### What I expected

I shouldn't be following this site in the Reader any more as it is deleted
#### What happened instead

The Reader shows this deleted site in following list
#### Browser / OS version

OSX 10.11.2 Chrome
#### Screenshot / Video

<img width="641" alt="screen shot 2016-06-07 at 8 00 05 am" src="https://cloud.githubusercontent.com/assets/128826/15839267/cea0b276-2c85-11e6-8d76-f96fb2d79d44.png">

<img width="741" alt="screen shot 2016-06-07 at 7 55 25 am" src="https://cloud.githubusercontent.com/assets/128826/15839278/dc3e69a0-2c85-11e6-9f2f-b217d3d8615e.png">
# dogfooding #manual-testing

**Comment by lancewillett** [comment]
Testing this today in a bug scrub. The flow is still not ideal.

When you delete the site — the subscriptions (Reader Follows) still persist. They should be removed.

Here's a visual record.

![screen shot 2016-10-13 at 15 08 53](https://cloud.githubusercontent.com/assets/66797/19368989/bac220e6-9157-11e6-90c5-b3c129d8e806.png)
![screen shot 2016-10-13 at 15 09 16](https://cloud.githubusercontent.com/assets/66797/19368992/bac67eb6-9157-11e6-916c-698f41abc607.png)
![screen shot 2016-10-13 at 15 09 19](https://cloud.githubusercontent.com/assets/66797/19368990/bac26862-9157-11e6-85f2-bc14096e250f.png)
![screen shot 2016-10-13 at 15 09 49](https://cloud.githubusercontent.com/assets/66797/19368991/bac4d2be-9157-11e6-8649-fb71e6ae6b9e.png)
![screen shot 2016-10-13 at 15 09 56](https://cloud.githubusercontent.com/assets/66797/19368994/bac6cc22-9157-11e6-8eae-725431ca24da.png)
![screen shot 2016-10-13 at 15 10 01](https://cloud.githubusercontent.com/assets/66797/19368993/bac6b174-9157-11e6-981b-23318a7ca3e8.png)
![screen shot 2016-10-13 at 15 10 18](https://cloud.githubusercontent.com/assets/66797/19368995/bad4e8a2-9157-11e6-920d-84dcbb451151.png)
![screen shot 2016-10-13 at 15 10 47](https://cloud.githubusercontent.com/assets/66797/19368998/bad65944-9157-11e6-8cd4-8c1670850834.png)
![screen shot 2016-10-13 at 15 11 16](https://cloud.githubusercontent.com/assets/66797/19368997/bad631bc-9157-11e6-8ec1-ce9d30cbc6a7.png)
<img width="872" alt="screen shot 2016-10-13 at 15 11 41" src="https://cloud.githubusercontent.com/assets/66797/19368996/bad5e8f6-9157-11e6-88ca-affa6247a6d1.png">
<img width="851" alt="screen shot 2016-10-13 at 15 11 59" src="https://cloud.githubusercontent.com/assets/66797/19368999/bad989f2-9157-11e6-9c0d-640196188b61.png">

**Comment by ChrissiePollock** [comment]
A user brought this up. Her list of sites followed shows blanks. When I did an export, the sites showed up there. The one I checked was a deleted site. 
![screen shot 2017-10-11 at 10 13 55 am](https://user-images.githubusercontent.com/2545184/31447597-661310d2-ae70-11e7-9fc7-66f611e300bd.png)

**Comment by fraying** [comment]
Re: the original bug: "when a wordpress.com site is deleted, related subscribers should be removed", I just want to make sure we don't delete followers when the site just moved to another place. Remember that Reader can follow sites on any host so long as they have an RSS feed. It's not uncommon for a wp.com site to get a custom domain, get a bunch of followers, and then move to a self-install or AT or other host. We want to preserve their followers no matter where they go.

**Comment by blowery** [comment]
@fraying possibly. Need to dive in more to see what's going on there.

**Comment by blowery** [comment]
access via the `/read/blogs` link has since been fixed. see https://wordpress.com/read/blogs/104049876

**Comment by blowery** [comment]
This is still open because it's a little complicated. 

If the site in question is a *.wordpress.com site, we can and should just unsub the followers.

If the site has a domain mapping, we should not unsub the followers, as the site may just be moving elsewhere. 

If a user is currently subscribed to a site that has been deleted and the sub_matrix record is a *.wordpress.com domain, we should unsub them.

**Comment by gemmagarner** [comment]
Report of this in 969818-zen. I was able to unfollow the blog for my user by searching for the site address and clicking the unfollow link under the search box.

**Comment by bluefuton** [comment]
Two side effects of this:
- subscription count can include deleted sites
- Blogs I Follow widget can include deleted sites

![screen shot 2018-03-08 at 15 58 33](https://user-images.githubusercontent.com/17325/37161055-9e3b9c66-22e9-11e8-9b0d-be48ca96dcca.png)

**Comment by gwwar** [comment]
@bluefuton is the summary up to date for this one? If this is rather complex what we can do is open up individual issues for each case.

**Comment by bluefuton** [comment]
@gwwar the original issue as reported by @alisterscott is resolved (see #19328) so I've renamed the issue to better reflect the original report and will close this one 👍 

I'll create three new issues to cover the outstanding problems.

**Comment by bluefuton** [comment]
New issues:
- clean up subscribers when a site is deleted: #23426
- subscription count is incorrect when subscriptions contain deleted sites: https://github.com/Automattic/wp-calypso/issues/23427
- Blogs I Follow widget shows deleted sites: 8027-wpcom
