### ISSUE TITLE
Design Picker: make Blank Canvas option a button, remove it from the list of selectable designs

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58429]
## Design Picker:
Make Blank Canvas part of the design/theme shuffle.  Slack convo: p1637678243115700/1637664255.109200-slack-C029SB8JT8S

Examination of user selection of themes in the Design Picker (see Tracks Trends calypso_signup_select_design) shows that the Blank Canvas theme is chosen more than other themes by an order of magnitude.  The Blank Canvas is not currently part of the shuffle of the designs, it is stuck prominently  to the top of the DP and this could be causing an over-selection of this theme.

![image](https://user-images.githubusercontent.com/5665959/143134281-a2623e60-5ebe-4c7a-894a-fc83b8b9937e.png)

### Current
Existing "Blank Canvas" in DP:
![image](https://user-images.githubusercontent.com/5665959/143136254-3ac58bd5-05c5-4564-8fdf-b3ff80fe70f1.png)

### Proposed
* Remove Blank Canvas from the list/grid of designs
* Add "Blank canvas" button 
See the [final designs posted in Ollie's comment below](https://github.com/Automattic/wp-calypso/issues/58429#issuecomment-979471989)

## Criteria for Completion 
- [x] @ollierozdarz will provide designs for adding a "Blank site" button similar to the "Add a new Page" see [designs posted in comment below](https://github.com/Automattic/wp-calypso/issues/58429#issuecomment-979471989)
- [x] include track events for the new "Use Blank Canvas" button
- [x] Document in the FG that designs are shuffled  PCYsg-D3C-p2
- [x] Add PR & merge date to ship table: pdgK6S-iY-p2 

## Post Shipping
- P2 about metrics results, e.g. that we expect  to see selection of Blank Canvas drop significantly after shipping this change

## Dev Tasks/PRs
- [x] #58565
- [x] https://github.com/Automattic/wp-calypso/pull/58796

## Related
Design Picker: update Blank Canvas theme #58431

**Comment by autumnfjeld** [comment]
@p-jackson @roo2 @arthur791004  I put this at the top of "Ready for Dev" for whoever is ready for their next ticket.   

To help spread the metrics love around 😆 I also included the metrics analysis as part of the issue, so whoever takes this issue is  responsible not only for dev work but also following through with A/B monitoring and P2ing about the results.   Is this cool with y'all?   Of course we'll all help anyone who needs to get up to speed with A/B experiments PCYsg-tdK-p2

cc: @simison @ianstewart

**Comment by arthur791004** [comment]
I think I can pick this one. Let me learn how to do A/B experiments first 😄

**Comment by simison** [comment]
> I suppose I don’t understand how, to the user, “consistently a few rows down” is any different than “random”.    A user will see this screen once. 

Sure! That can be the case, happy to hear more arguments on why it's still ok experience. :-) My reasoning for random feeling off was that "blank" is not a design as much as it is customer opting into a different kind of experience in lack of suitable designs to start with. You can imply that difference in experience by placement (outside the grid, first in the grid) or by adding context around it with copy/screenshot. [Squarespace templates](https://www.squarespace.com/templates) does the latter for example:


https://user-images.githubusercontent.com/87168/143269688-7da57443-3343-4fb7-884a-5990a4236ba4.mov

**Comment by autumnfjeld** [comment]
@simison I agree with you. :).   Thanks for the extra explantation.

@ollierozdarz will suggest some designs similar to 
![image](https://user-images.githubusercontent.com/5665959/143323858-3f751932-ffa3-4633-8439-bed1c6fbc0e6.png)

**Comment by arthur791004** [comment]
Yeah, I totally agree with @simison. 

> CONVERSELY: we could do without an A/B test, but the metrics analysis still needs to be via funnels/track events. Please use your discretion on that.

@autumnfjeld In my opinion, I think we don't need an A/B test anymore as the user can still select the blank canvas at a first glimpse when they land on the Design Picker. Thus, the step conversion rate or flow completion rate won't be affected. But I'll take care of the metrics after shipping this change.

**Comment by ollierozdarz** [comment]
Let's use the following designs. 

By placing the button below the categories, we're de-emphasizing it enough to not be the first logical element to click. Also, showing the button above categories on mobile just feels like the wrong decision (I also don't think the current 50/50 button & category split on the 'Insert blank page' provides the best experience).

I removed the (i) tooltip, I think at least initially until we learn more, it's obvious enough.

<img width="1680" alt="Use Blank Desktop" src="https://user-images.githubusercontent.com/67085494/143500219-a10b0c03-0cbb-427c-91eb-e925a053a89e.png">
<img width="551" alt="Use Blank Mobile" src="https://user-images.githubusercontent.com/67085494/143500230-30f40de0-0475-40cf-a811-452136a1e31c.png">

**Comment by autumnfjeld** [comment]
@arthur791004  
>  I think we don't need an A/B test anymore as the user can still select the blank canvas at a first glimpse when they land on the Design Picker.

Agreed. We can get the information we need from a track event analysis.   We will want to watch if users select "Blank Canvas" less once it is taken out of the grid/list of designs.

**Comment by autumnfjeld** [comment]
I've updated the issue description above to reflect the decisions made in the above discussion.   ![bitmoji](https://sdk.bitmoji.com/render/panel/9ff55377-6e8f-4a55-9baf-471d1ee75e6a-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)

**Comment by arthur791004** [comment]
Close this issue as we have already shipped it and I've also updated the document in FG: PCYsg-D3C-p2.
