### ISSUE TITLE
Advanced SEO: Content Feedback

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5842]
As part of Advanced SEO we should add `Content Feedback`, a tool that will give you warnings and tips on how your post should perform with search engines. 

For inspiration on things that we could crawl (_ha!_) the content for, check this post: http://www.openvine.com/small-business-internet-blog/6-ways-to-optimize-your-blog-posts-for-seo

**Comment by drw158** [comment]
Also this article https://yoast.com/use-content-analysis-yoast-seo/

It looks like all of these features require the user to do a lot of research and come up with a keyword to use in their post. Without the user doing their part, it doesn't seem like a content analyzer would do anything.

Also, I'm not sure what a MVP would look like. Maybe just making sure that they have alt tags on their images?

**Comment by roundhill** [comment]
Placing this as lower priority, since it is a `nice to have` for the Advanced SEO project.

**Comment by brbrr** [comment]
I doing to close is due to inactivity. Please re-open it if its still needed!
