### ISSUE TITLE
Woop: keep descriptive text in one place

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#58430]
### Details

Follow-up to https://github.com/Automattic/wp-calypso/pull/58024

Keep all of the descriptive text in one place, rather than passing in props.

https://github.com/Automattic/wp-calypso/blob/7f2b40b1fcb8126eefb45317bfb6990876dca09c/client/signup/config/steps-pure.js#L787-L796

### Checklist

- [ ] Move descriptive text
- [ ] Remove props

**Comment by obenland** [comment]
Where should that text live instead?

**Comment by allilevine** [comment]
> Where should that text live instead?

@obenland In the step itself, as opposed to this config file for the steps. I should've linked to [the comment](https://github.com/Automattic/wp-calypso/pull/58024#discussion_r755124589) that prompted this.
