### ISSUE TITLE
Woop: check for eligibility substep

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#58433]
### Details

This will render if we have an unknown step section name. Let's be more explicit here and check that we are on the eligibility substep.

If it's an unknown section name we could either show an error, or log it and move along.

https://github.com/Automattic/wp-calypso/blob/7f2b40b1fcb8126eefb45317bfb6990876dca09c/client/signup/steps/woocommerce-install/confirm/index.tsx#L84

### Checklist

See https://github.com/Automattic/wp-calypso/pull/58024/files#r755129446

- [ ] Add check for eligibility substep.
- [ ] Show an error if it's an unknown section name.

**Comment by obenland** [comment]
Discussed in State of the Board and it looks like we don't use subsets anymore. Closing.
p1643144965204000-slack-C029UPVMGTW
