### ISSUE TITLE
[Bug]: Site editor row block has excessive layout shifting 

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#58437]
### Quick summary

There’s significant content shifting when we justify items in the row block (center, right, left, and space between) and select it. I tested the behavior with 1, 2 and 3 block children.

![2021-11-18 23 18 00](https://user-images.githubusercontent.com/5414230/143145425-c7568065-2e9c-4d57-a4a8-1d437c8a8beb.gif)

### Steps to reproduce

1. Enable full site editing by activating the Gutenberg plugin and an FSE enabled theme (Ex. Quadrat)
2. Navigate to the site editor
3. Add a row block
4. Add two items into the row block
5. Open the row block settings sidebar
6. Change the content justification to `space between`
7. Unselect the row block
8. Reselect it and verify that the content jumps

### What you expected to happen

I would expect no layout shifting when selecting a row block with content

### What actually happened

There _was_ layout shifting when selecting a row block with content

### Browser

Google Chrome/Chromium

### Simple/Atomic

Reproduced on simple sites

### Reproducibility

Consistent

**Comment by mtias** [comment]
This should be addressed in gutenberg trunk. Can you check?

**Comment by jeyip** [comment]
@mtias Those we’re my exact thoughts as well, and I did check in my core Gutenberg dev environment before drafting this issue. I was only able to reproduce the problem on dotcom.

Hopefully the fix is already in core Gutenberg, and it’s simply a matter of waiting for a future Gutenberg release on dotcom to resolve everything 🤞

**Comment by jeyip** [comment]
I did some css debugging. The reason we only see it on Dotcom is because [a fix](https://github.com/WordPress/gutenberg/pull/36605) was merged into core Gutenberg a week ago.

It doesn’t look like the fix made it into Gutenberg v12, but it should be resolved by v13.

**Comment by mtias** [comment]
Yes, it should come with 12.1.

**Comment by jeyip** [comment]
Solved with the release of 12.1 on simple sites
