### ISSUE TITLE
File download stats unavailable in Atomic sites

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#58459]
### What

Add file download stats to Atomic sites

### Why

From our [documentation](https://wordpress.com/support/stats/#file-downloads):

> File Download Stats is currently unavailable for sites using third-party plugins or themes on websites with Business or eCommerce plans.

This is a feature gap when moving from simple to Atomic. I couldn't find another issue reporting this, so am creating this new one. 

Advising users to use Google Analytics and Google Tag Manager, or a plugin such as MonsterInsights, isn't the best way to address this feature gap.

**Comment by jartes** [comment]
@metabreakr Thanks for reporting! This is already reported and it's a duplicate of #36197 so I'll close this one :) 

Also, if you had any interaction regarding this, please, add it to #36197. Thanks!
