### ISSUE TITLE
Implement a way to allow 3pd to support WordPress.com users

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58457]
3pd (third party developers) should have a way to promptly respond to WordPress.com users having problems with using their plugins bought from WordPress.com.

**Comment by cpapazoglou** [comment]
@vajrasar can you please help us with an optimum solution here? Can we use zendesk to forward issues to 3pd?

**Comment by vajrasar** [comment]
We can take the following approach

- We generate tickets related to the user query in ZD and route it to the platform that the third-party support team uses to provide support to the users.
- There exists a macro in ZD related to the third-party that helps with adding relevant tags, and note template.
- We establish a way on how the third-party can send the email back to us (if the user asks any WordPress.com-related question) and on those tickets we have some identifier for the HEs so they know that the ticket is coming from third-party and we need to support the user.

**Comment by cpapazoglou** [comment]
@vajrasar can we assign this task to someone who can undertake the above tasks (creating macros etc)

**Comment by cpapazoglou** [comment]
@vajrasar any updates here?

**Comment by vajrasar** [comment]
@galakhyati can you check further on this? 

@cpapazoglou apologies for missing pings on this. @galakhyati should be able to investigate on this.

**Comment by galakhyati** [comment]
Sorry for missing the ping as well. I'll check on with the team who can help creating the macro and get back once I have some updates.

**Comment by galakhyati** [comment]
I've pinged Kris Karkoski for helping in creating the macro for the 3PD as we are doing to create a ticket for reaching out to 3PD for any Woo.com extension. Reached out to him here: p1651226829717699-slack-C029JEQRVRT

**Comment by cpapazoglou** [comment]
I believe this is tackled by now. Let's reopen if needed.
