### ISSUE TITLE
Images won't load for users with the Viewer role on Safari when the "Prevent Cross-Site Tracking" option is enabled

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#58462]
### Quick summary

Users with the viewer role won't be able to see images on WordPress.com websites. The image sources will return a 403 error. This affects Safari both on desktop and mobile:

![Screen Shot 2021-11-24 at 11 58 28](https://user-images.githubusercontent.com/3696121/143282252-53d777f8-3cc7-429e-87ca-03509cd97d48.png)

### Steps to reproduce

1. Get added to a **Private** site as a **Viewer**
2. Make sure the "Prevent Cross-Site Tracking" option is enabled on Safari (either on mobile or desktop)
3. Try accessing a page or post with images on it
4. Log in as a Viewer
5. Notice the images are not loading

### What you expected to happen

This behavior depends more on the Safari settings. But it would be really useful if the Viewer user would get a notice asking them to disable the "Prevent Cross-Site Tracking" option. Not sure if related to this:

https://wordpress.com/support/remote-login-permission/

### What actually happened

The images are not displayed and user don't know why

### Context

User report: 32011615-hc

### Operating System

macOS, iOS

### Browser

Apple Safari

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Turn off the "Prevent Cross-Site Tracking" option in the browser settings

**Comment by tellisbethel** [comment]
Just came across this issue in a chat where a user came in specifically asking for a way to deal with this issue without needing to tell their users to turn off the `Prevent Cross-Site Tracking` option in their settings. I let them know the bug was recently surfaced and that turning off the setting was the only workaround at the moment.

Could we notify this user once the issue is resolved please?

Interaction: 32951052-hc

**Comment by zdenys** [comment]
Is this the same as https://github.com/Automattic/wp-calypso/issues/53102? There are more reports there so merging into that one makes sense.

**Comment by cuemarie** [comment]
This seems like a dupe of https://github.com/Automattic/wp-calypso/issues/53102 - closing in favor of that report.
