### ISSUE TITLE
Woo Installer: Implement mobile ux and new design - Confirm Step

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#58468]
### Details

Implement the new design for Confirm Step #58387.
Figma: r6eTqDpL2GGk96hcPLhsBb-fi-431%3A2447

### Info, warnings, and blockers.

![image](https://user-images.githubusercontent.com/77539/143877400-98eb8df6-de4a-4538-85f3-b9905755c849.png)

According to the design above, we need to reorganize the eligibility data in order to apply and handle the different areas in:

* WPCom subdomain warning: first area _New Store Domain_ area
* Generic warnings:  second area _Thins you should be aware of_
* Blockers: third area: error message.

Also, some blockers will be handled before landing here; for instance when the site doesn't have the proper plan.

Eligibility Warnings | Area / Action to take
-----|------
WPCom subdomain | First area
plugins: an array of unsupported plugins that are used on current blog. | Second Area
widgets: an array of unsupported widgets that are used on current blog. | Second Area

Eligibility Errors | Area / Action to take
-------|--------
`TRANSFER_ALREADY_EXISTS` | -> hit the endpoint
`NO_JETPACK_SITES` | Third area
`EXCESSIVE_DISK_SPACE` | Third area
`NO_BUSINESS_PLAN` | -> redirect to landing page
`NO_VIP_SITES` | Third area
`SITE_PRIVATE` | Third area
`SITE_GRAYLISTED` | Third area
`EMAIL_UNVERIFIED` | Third area
`NON_ADMIN_USER` | Third area
`NOT_RESOLVING_TO_WPCOM` | Third area
`NO_SSL_CERTIFICATE` | Third area
`EXCESSIVE_DISK_SPACE` | Third area
`BLOCKED_ATOMIC_TRANSFER` | Third area

### Checklist

- [x] Implement desktop ux
- [x] Implement mobile ux

### Related
New Design PR: #58527
Plan Issue PR: #58581

**Comment by retrofox** [comment]
Handling plan issue here https://github.com/Automattic/wp-calypso/issues/58581

**Comment by Rolilink** [comment]
Handling new design here #58527
