### ISSUE TITLE
Woo Installer: Implement mobile ux and new design - Transfer step

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#58470]
### Details

Implement the new design for the transfer step. #58387
Figma Design: r6eTqDpL2GGk96hcPLhsBb-fi-0%3A1

### Checklist

- [x] Check if desktop design is okay (?)
- [x] Check if mobile design is okay (?)

**Comment by Rolilink** [comment]
Mobile UX seems okay to me! cc: @SaxonF @allilevine 

![Screen Shot 2021-11-24 at 3 36 09 PM](https://user-images.githubusercontent.com/1035546/143311739-b25790b9-1b96-4d27-a891-87d1f033fd40.png)

**Comment by Rolilink** [comment]
This is done, is just a ticket to review the progress bar ... will leave it on needs review until we are ready to merge the deliverables for this cycle.

**Comment by retrofox** [comment]
Is this issue done?

**Comment by Rolilink** [comment]
@retrofox I added this issue to track any design change the transfer step will need on the previous cycle but it seems we never had one. I don't know if any changes on the progress bar this cycle will make this issue relevant again? maybe something to discuss on the state of the board.

**Comment by retrofox** [comment]
> maybe something to discuss on the state of the board.
sounds like a good plan. Then we can decide what else we need, or otherwise close it?

**Comment by pablinos** [comment]
This seems done. We can open separate issues for any specific problems we find.
