### ISSUE TITLE
E2E: Add tests for "Image Replace" and "Cover Styles" CoBlocks extensions

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#58492]
Our custom CoBlocks build for Simple sites provides the following extensions to the Gutenberg editor:

- Attributes (support for extra attributes, necessary for e.g. the Gutter Control extension)
- Cover Styles (visual style for the Cover block, e.g. “Top Wave”)
- Replace Image (adds the “Replace” button to the Image block)
- Gutter Control (additional gutter controls for various blocks, e.g. the Collage gallery)

We're already [testing the Gutter Control](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-playwright/wp-blocks__coblocks-gutter-spec.ts) (along with the Attributes ext.), so all we need are tests for the image's `Replace` button and the custom Cover block styles (e.g. "Top Wave") and we're all set. 👍

---

For more information about CoBlocks see PCYsg-nRb-p2

**Comment by cpapazoglou** [comment]
@WunderBart is this still relevant?

**Comment by WunderBart** [comment]
I don't think we'll want to add any more CoBlocks tests since we've decided to cut them off for new users. Closing!

/cc @fullofcaffeine
