### ISSUE TITLE
Conditional Payments and Shipping: PHP Fatal error: Uncaught Error: Call to a member function get_cart() on null

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#58497]
### Quick summary

Our customer reported a 404 error that occurs when the user proceeds to Checkout on a site that has the [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/?aff=10486&cid=1131038) extension, WPML Multilingual CMS and WooCommerce Multilingual plugins enabled.

This issue only occurs when proceeding to checkout using a language that is not the default language (in this particular case, the error occurs when attempting a purchase when the site is set to English (by way of the WPML framework).

### Steps to reproduce

1. Browse to https://shop.dolcinonnavincenza.com/en and select a product;
2. Add the product to the cart, and proceed to checkout;
3. With browser devtools open, you'll see a 404 error much like this: 2ac9b-pb/
4. The payment methods will also be unavailable.

### What you expected to happen

Regardless of the language chosen, customers ought to be able to proceed to, and complete checkout.

### What actually happened

Proceeding to checkout produces the 404 error described above, and the customer sees the following:

https://user-images.githubusercontent.com/2912202/143437643-dccec965-15a7-447d-a6da-8438ba782cb0.mp4

### Context

I was able to reproduce this issue in my browser.

I also came across two seemingly related reports that suggest that this issue may not be specific to the Conditional Payments and Shipping extension:

- [Fatal error: Uncaught Error: Call to a member function get_payment_method() on null · Issue #25490 · woocommerce/woocommerce](https://github.com/woocommerce/woocommerce/issues/25490)
- [Fatal error when installed with WPML plugin | WordPress.org](https://wordpress.org/support/topic/fatal-error-when-installed-with-wpml-plugin/)

### Operating System

macOS

### Browser

Mozilla Firefox

### Theme-specific issue?

Likely not theme-specific.

### Other notes

Console log errors here: 2ac9b-pb/ (same errors that I shared above)

Our customer also shared the following PHP errors:

```
Stack trace:
#0 /home/asevwfnh/shop.dolcinonnavincenza.com/wp-content/plugins/woocommerce-conditional-shipping-and-payments/includes/restrictions/class-wc-csp-restrict-shipping-countries.php(613): WC_CSP_Restrict_Shipping_Countries->check_restriction('notice')
#1 /home/asevwfnh/shop.dolcinonnavincenza.com/wp-content/plugins/woocommerce-conditional-shipping-and-payments/includes/class-wc-csp-restrictions.php(214): WC_CSP_Restrict_Shipping_Countries->validate_cart()
#2 /home/asevwfnh/shop.dolcinonnavincenza.com/wp-includes/class-wp-hook.php(303): WC_CSP_Restrictions->validate_cart('')
#3 /home/asevwfnh/shop.dolcinonnavincenza.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /home/asevwfnh/shop.dolcinonnavincenza.com/wp-includes/plugin.php(470): in /home/asevwfnh/shop.dolcinonnavincenza.com/wp-content/plugins/woocommerce-conditional-shipping-and-payments/includes/restrictions/class-wc-csp-restrict-shipping-countries.php on line 371
[24-Nov-2021 12:14:21 UTC] PHP Fatal error: Uncaught Error: Call to a member function get_cart() on null in /home/asevwfnh/shop.dolcinonnavincenza.com/wp-content/plugins/woocommerce-conditional-shipping-and-payments/includes/restrictions/class-wc-csp-restrict-shipping-countries.php:371
```

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by Robertght** [comment]
I have reported this in the plugin repository for further debugging so I'm closing this one.
