### ISSUE TITLE
New announcement modal, announcing paid plugins

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58505]
Let's update our announcement modal for the plugins page with new copy and illustration regarding the paid plugins!

https://github.com/Automattic/wp-calypso/blob/08961f239b9c353bb0b44983d9f7b014db038133/client/my-sites/plugins/plugins-browser/index.jsx#L517-L521

<img width="442" alt="SS 2021-11-25 at 14 23 55" src="https://user-images.githubusercontent.com/12430020/143441243-00de3659-addb-4b06-8b52-f37cfaf8de16.png">

figma design: oU6nEIeiKSg8CayhEtgR6b-fi-6693%3A53628

**Comment by cpapazoglou** [comment]
@emmnyc85 and @SaxonF, can you provide us with the copy and the illustration for the announcement modal of the launch of paid plugins?

**Comment by emmnyc85** [comment]
@SaxonF - Do you want to draft up a V1 and then we'll input the copy. Thinking along the lines of
**Title:** Buy the best plugins
**Subheader:** Now you can purchase plugins right on WordPress.com to help improve your website's capabilities. From scheduling appointments to managing subscriptions (and more!), we've got you covered.
**CTA:** Let's explore!

**Comment by gavande1** [comment]
The destination for the CTA will be the add new plugin page. @cpapazoglou Please correct me if I'm wrong.

**Comment by gavande1** [comment]
Reserved for onboarding.

**Comment by SaxonF** [comment]
Hey y'all, design using @emmnyc85 copy above. I'm assuming components for all this already exists.

![image](https://user-images.githubusercontent.com/1072756/146307614-10350c72-25ec-4d0d-b25c-a9d16b211beb.png)

**SVG for illustration**
```
<svg width="134" height="152" viewBox="0 0 134 152" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M17.5434 86.3293C16.4036 87.754 16.6271 89.8466 18.0798 90.9819C28.2035 98.8846 64.4523 126.978 68.6761 126.867C72.8329 126.756 108.523 98.9514 119.518 90.314C121.172 89.0229 121.194 86.5296 119.563 85.194L112.3 79.1834C100.232 69.2104 85.0574 63.7563 69.3913 63.7563H64.6535C46.3056 63.7563 28.9857 72.0598 17.5434 86.3293Z" fill="#DCF1FF"/>
<path d="M61.1 147.77L2.01123 88.9338H131.989L72.9222 147.77C69.6593 151.043 64.3628 151.043 61.1 147.77Z" stroke="#003C65" stroke-width="1.8" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M30.6619 88.9338L67.0001 150.219L100.902 88.9338L67.0001 53.1599L30.6619 88.9338Z" stroke="#003C65" stroke-width="1.8" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M131.989 88.9337H2.01123L36.4946 53.0708H94.5106L131.989 88.9337Z" stroke="#003C65" stroke-width="1.8" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M19.7783 12.1768L38.8637 33.4808" stroke="#003C65" stroke-width="1.8" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M108.858 12.1768L89.7727 33.4808" stroke="#003C65" stroke-width="1.8" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M65.7708 2.00366V27.1144" stroke="#003C65" stroke-width="1.8" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

```

**Comment by emmnyc85** [comment]
Thanks, @SaxonF. Looks good, but it's too long. Can we try just the following text?
`Now you can purchase plugins right on WordPress.com to extend your website's capabilities.`

**Comment by SaxonF** [comment]
@emmnyc85 much better :) 
![image](https://user-images.githubusercontent.com/1072756/146347204-4633f2d7-a9e8-4628-913b-e7beeb264488.png)

**Comment by emmnyc85** [comment]
Looks great!

**Comment by cpapazoglou** [comment]
@emmnyc85 any ideas on which pages the new announcement modal should appear?

Currently it will show up only in `Plugins` page. I was wondering whether it makes sense showing it also in `Home`? I am only worried it might be too obtrusive.
