### ISSUE TITLE
Make sure that plugins short description doesn't have widowed words.

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58506]
Let's use the preventWidows function so that no word is windowed in a new line in the plugin description.

https://github.com/Automattic/wp-calypso/blob/26b626c2da1e079a3ebf62f6c0fced059d60cc5e/client/lib/formatting/prevent-widows.js#L10-L15

![SS 2021-11-25 at 14 26 44](https://user-images.githubusercontent.com/12430020/143441593-e6dbbed9-5dc4-4d82-9fed-3b4e14ac532e.png)

**Comment by gavande1** [comment]
Reserved for onboarding.
