### ISSUE TITLE
Plugin Upload: not possible to upgrade / downgrade plugins by uploading a zip file

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#58508]
### Quick summary

On the new Plugin Marketplace is not possible to update custom plugins by uploading a zip file with the new version 

### Steps to reproduce

1. On an Atomic site, install a custom plugin. You test it with this one: [my-custom-plugin.zip](https://github.com/Automattic/wp-calypso/files/7603262/my-custom-plugin.zip)
2. Then, try to update it by uploading the new version in a zip file via the Marketplace. This is the 1.1 version of the previous plugin: 
[my-custom-plugin.zip](https://github.com/Automattic/wp-calypso/files/7603308/my-custom-plugin.zip)

### What you expected to happen

Land in a page, like it's happening on WP Admin, indicating that the plugin already exists, and allowing to update it: 

![Markup on 2021-11-25 at 14:34:28](https://user-images.githubusercontent.com/1046943/143451152-cdab6aa1-e23e-40d2-a594-5f37c6aea964.png)

### What actually happened

Got the error that the plugin is already installed on the site:

![Markup on 2021-11-25 at 14:31:55](https://user-images.githubusercontent.com/1046943/143451195-242959ff-e06f-4545-93c2-04f9f51fd92a.png)

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

As mentioned on #58322, users can use the WP Admin URL: `/wp-admin/plugin-install.php`.

**Comment by Robertght** [comment]
cc @cpapazoglou for this one

**Comment by Sandkorner** [comment]
Just commenting to say that had a user in chat as well with the issue. 32958538-HC

/wp-admin/plugin-install.php. helped the user out.

**Comment by cpapazoglou** [comment]
Let's identify these scenarios and ask the user:

- (if plugin not already activated) Do you want to activate the plugin? -> activates the plugin
- Do you want to replace the plugin? -> redirects to WP Admin
