### ISSUE TITLE
Plugin browser item: add "Installed on # sites" on multi-site view

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#58504]
On Plugins Browser multi-site view. As per figma design oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A47242

![Screen Shot 2021-11-25 at 08 20 58](https://user-images.githubusercontent.com/5039531/143440982-dd817a6c-57d9-4674-a1fe-fb143c6b04b3.png)

**Comment by cpapazoglou** [comment]
This data is already available in Plugin Details page
