### ISSUE TITLE
Watson theme doens't infinite scroll on atomic sites.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#58517]
### Quick summary

Using the Watson theme on an atomic site with Jetpack Infinite Scroll enabled does not work. The loading spinner will spin endlessly when you reach the bottom of the page.

### Steps to reproduce

1. Have an Atomic site and set the theme to Watson.
2. Ensure "Latest Posts" is set as the homepage and have 10 or more posts.
3. Ensure Jetpack Infinite Scroll is on.
4. Visit the homepage and scroll down. The next posts will not load.

### What you expected to happen

More posts should load as I scroll down.

### What actually happened

A loading flywheel appears and spins endlessly.

### Context

User reported here: 32899944-hc

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Watson

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The only workaround is to disable infinite scroll.

**Comment by kosiew** [comment]
Hi @KirkwallDay ,

Thanks for reporting this.

Since this is a retired theme, I propose closing this without further action.

Please feel free to re-open if you have further findings to add.
