### ISSUE TITLE
Plugin Browser: show inactive state on plugin card

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#58539]
In the Plugins Browser, plugins that are installed but deactivated are shown with the green `Installed` badge (eg. on the images below, Yoast SEO is installed but not currently active). This is a bit misleading UX, as the user won't be able to find the installed plugins on the sidebar or use them.

![image](https://user-images.githubusercontent.com/11555574/143565180-8c84ea72-79f6-445d-86cc-de89820af1ae.png)

![image](https://user-images.githubusercontent.com/11555574/143565127-da0a04a5-008b-47a6-8eb3-6bddec012a02.png)

We could add a third state to the indicator with a different color, which would show that the plugin is installed but not currently active. An 'Activate' CTA button could also be added to the plugin page in this state.

**Comment by cpapazoglou** [comment]
@SaxonF can you please chime in here?

**Comment by SaxonF** [comment]
Add an active and inactive badge under installed with a stronger border color.

Could we break out "activate" action into a separate issue?


f84fqtCG4pCnCh2Hq0But5-fi-593%3A13170

![image](https://user-images.githubusercontent.com/1072756/154412213-4b529a98-8c28-4098-aaa3-63e4d6329da4.png)


Acceptance criteria:
- On plugins that are installed and active, we show an "Active" `badge` underneath the installed label
- On plugins that are installed but not active, we show an "Inactive" badge
- On plugins that aren't installed, we keep them the same (either Free or price)
- Checkmark is centered with "Installed" status
