### ISSUE TITLE
Selected Video Thumbnails don't appear when in Media & Text blocks

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#58556]
### Quick summary

Any videos that have a custom thumbnail set in the media library will not display those thumbnails when the video is inside a Media & Text block. 

### Steps to reproduce

1. Assign a custom thumbnail or specific video frame for thumbnail in media library
2. Use a Media & Text block and add video from library or by uploading.
3. Video does not display the set thumbnail in editor or live page.

### What you expected to happen

The set thumbnail in media library should be displayed within the Media & Text block.

### What actually happened

Video in the Media & Text block is just using the first frame instead of a set thumbnail.

### Context

The video shows the first frame as the thumbnail.
I've not been able to get this to work on both test Simple and Atomic sites.
Also reported: 4550108-zen

### Operating System

Windows, macOS

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Workaround details

For now, using columns block to add a separate video and text block.
## Screenshots
![1](https://user-images.githubusercontent.com/83020905/143733403-1aca0db0-c20f-4ed4-a087-195c247b5f05.png)
![2](https://user-images.githubusercontent.com/83020905/143733406-f8b44c60-43f4-4693-af1f-3ac5b386a57b.png)

**Comment by kosiew** [comment]
Hi @kuropixel ,

Thanks for reporting this and the detailed steps.
I checked this for you and found a similar issue.

Closing this in favour of  https://github.com/Automattic/jetpack/issues/13239

**Comment by kuropixel** [comment]
@kosiew Thank you! I saw that report but figured it was only for mobile view.
