### ISSUE TITLE
USPS Shipping Method: Additional weight in requests when using the Pack into Boxes method

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#58557]
### Quick summary

While investigating a customer's query regarding logs for the USPS Shipping Method, I noticed that requests for shipping rates when using the recommended *Pack into boxes* method added one pound to the shipping rate used to calculate shipping rates.

I'd like to clarify if this is intended, or whether this is a bug as this additional pound does not seem to be included when using the weight-based method.

### Steps to reproduce

1. While signed in as an Admin user, head to https://letsbeepositive.com and select a single item to add to the cart;
2. In my tests, I tested the [Sling Back Pack with Let’s Bee Positive logo, Sammie the Bee, on the front](https://letsbeepositive.com/product/bkpk1/) and the [Multi-use Pen and Black Velvet sleeve](https://letsbeepositive.com/product/multi-use-pen-and-black-velvet-sleeve/);
3. The logs for the bag (2acd7-pb/) included a request where the weight of the package was 1 pound and 0.7 ounces (the product initially reflected the weight as `.6`oz, and I believe that not setting that as `0.6`oz caused a little confusion);
4. Similarly, when I obtained a shipping rate when I only had the pen in the cart, the request added a pound to the pen's `0.5`oz (I adjusted this from `.5`oz). You can see that in the logs here: 2acd8-pb/
5. By contrast, when I changed the USPS shipping method to a weight-based calculation method, the request in the logs used the correct weight for the product (in this case, the same bag), as you can see here: 2acd9-pb/
6. In other words, when using the *Pack into boxes* shipping calculation method, the requests that the extension sends seem to add one pound to the shipping weight. 

### What you expected to happen

I'd expect the shipping weight in the requests sent to USPS to specify the correct weights for shipping rate calculations.

### What actually happened

When  using the *Pack into boxes* shipping calculation method, the requests that the extension sends seem to add one pound to the shipping weight. 

### Context

This is based on a ticket, 4539345-zen

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

I haven't tested whether the theme is a factor. The site uses Storefront.

### Other notes

One observation is that when I tested the pen, I also noticed that the shipping rate that I see in the cart is $8.70 for just the pen, [here](https://cln.sh/lh98Cxw1CHjntp1XXdjB):

![Capture_2021-11-28 at 10 01 18](https://user-images.githubusercontent.com/2912202/143735993-178c3ebc-a066-45f4-847d-ad4a252914e0.jpeg)

This seems to be correct based on Priority Mail 1-Day envelope rates on the USPS site, [here](https://cln.sh/q5wFz3eVJlLv9mAgy2It):

![Capture_2021-11-28 at 10 02 28](https://user-images.githubusercontent.com/2912202/143736026-037998c5-a076-4520-be61-0758fc82f1c4.jpeg)

To arrive at these rate calculations, I used the options you see [here](https://cln.sh/xTNbJ7l90Emg02QOwU47):

![Capture_2021-11-28 at 10 03 55](https://user-images.githubusercontent.com/2912202/143736045-ad2a8a3d-72cd-4ce9-b97b-698cccbc5102.jpeg)

I also noticed that both products used the same box, namely the `B-14x10x6`, despite the other box (or even an envelope) being a better option for the pen. These are the boxes the site currently has:

![Capture_2021-11-28 at 09 58 01](https://user-images.githubusercontent.com/2912202/143736088-01961b7b-3897-4dae-a5c0-66066e00ce80.jpeg)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by kosiew** [comment]
Hi @pauljacobson ,

Thanks for reporting this and the detailed steps.
I found a related Slack discussion and transferred this to 336-gh-woocommerce/woocommerce-shipping-usps
