### ISSUE TITLE
Make Sync Trouble Warnings More Obvious

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#58555]
### What

Customer requested that warnings about syncing become more obvious.

### Why

I got really unlucky that it happened, I should have noticed that small icon indicating it's struggling to save note for far longer than usual and stop typing, but I haven't and unaware continued for few hours. Perhaps Simplenote can pop up a more explicit warning saying it has a problem with connecting to server or something, so this would prevent people from precipitating to their own disaster.

Requested in #4453459-zen

**Comment by kimerlin81** [comment]
This FR has been reported directly to Simplenote. Pinged HE.
