### ISSUE TITLE
Testing: Make sure we always use test env config when running client tests

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#5856]
Part of #4915.

At the moment we use test env config only when running tests on Circle CI. When developing code locally we use the last generated config file, which usually means we are testing our code using development env config. We should fix that.

Possible solution might be to use generated file for WebPack build, and use on the fly approach when running tests. It should be quite easy to achieve if we teach regenerate script to create `client/config/data.js` file instead of `client/config/index.js` and load it inside new created `client/config/index.js` file with extracted config interface.

**Comment by samouri** [comment]
If we end up merging in https://github.com/Automattic/wp-calypso/pull/11352 then it should take care of this issue (very similar to on-the-fly config generation)

**Comment by samouri** [comment]
@gziolo, we have landed #11352, is it ok to close this now?

**Comment by gziolo** [comment]
Sure, it's more sophisticated solution which covers the same use case ;)
