### ISSUE TITLE
[Bug]: Domain modal overlaps with Nav-unification in paid-upgrades.php

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#58572]
### Quick summary

Domains edit modal overlaps nav unification in paid-upgrades.php. This happens because the modal does not account for the increased size of nav-unification. 

However, it should be noted that it only happens for HEs and only for sites that they are part of (have at least one capability). 

cc @shamserSuzon

### Steps to reproduce

1. Go to Store Admin
2. Search a user by Username/Email
3.  Click the "My Domains" button beside the domain name
4.  My Domains page will appear and now click the "Edit Domain" button >> A pop-up will appear regarding that specific domain's detail information.

![Screen Shot on 2021-11-15 at 16:57:36](https://user-images.githubusercontent.com/4452464/141813902-88e4ab3a-96ef-4cb1-8d18-f0bed86bf1ab.png)

![Edit Domain](https://user-images.githubusercontent.com/53257625/122767056-0e48b100-d2c4-11eb-840a-1410c3425f67.png)

### What you expected to happen

The entire modal should be displayed.

### What actually happened

![Screenshot_5](https://user-images.githubusercontent.com/53257625/122767082-17398280-d2c4-11eb-9a70-5dc32e84ffb1.png)

### Reproducibility

Consistent

**Comment by rcrdortiz** [comment]
I've prepared a diff to solve the issue, you can find it here: D70757-code.
