### ISSUE TITLE
Videos UI: Trigger API endpoint when specific timestamp is reached

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#58587]
An API request should be made when the `completed_seconds` attribute value is reached for a given video.

`completed_seconds`: introduced in D70522-code

Main issue: https://github.com/Automattic/wp-calypso/issues/58248

**Comment by kwight** [comment]
This should happen here: https://github.com/Automattic/wp-calypso/blob/trunk/client/components/videos-ui/video-player.jsx#L17

**Comment by andres-blanco** [comment]
closed by: https://github.com/Automattic/wp-calypso/pull/58727
