### ISSUE TITLE
Atomic / Akismet: Calypso alerts that "Your site needs an antispam key" on WPCOM sites with provisioned keys

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#58599]
### Workaround

Users can ignore this notice. Please do not provide the user any API keys. This is mostly a visual bug with Calypso and sites still have active Akismet protection.

Jetpack’s `wp-admin/admin.php?page=jetpack#/settings` page can be checked and shared with the user to demonstrate that it has a valid key.

### Quick summary

Thanks to @edequalsawesome for providing an initial overview and demonstrating this issue is widespread.

Recently, Calypso's My Site > Settings > Security page has started alerting that `Your site needs an Anitspam key` on most WordPress.con on Atomic sites. 

This is something that the platform and WordPress.com plans provide so should not be visible to the user.

From a quick investigation, it appears Akismet is still working and has a valid key set but Calypso does not see this. 

Please see internal notes for extended details:  p9F6qB-7Kz-p2#comment-43882

![missing-key](https://user-images.githubusercontent.com/4887830/143921671-896a965b-89b4-4f7b-b4ba-dcba5d2b38fb.png)

### Steps to reproduce

On a WordPress.com on Atomic site...

1. Visit My Site > Settings > Security

### What you expected to happen

No Antispam options and no alert that the site needs an Antispam key. 

### What actually happened

Sites are alerting that `Your site needs an Antispam key.`

![Screen Shot on 2021-11-29 at 13:20:06](https://user-images.githubusercontent.com/4887830/143921841-eba2d910-f4b7-491c-b20b-4a03143b950b.png)

It also notes `Please enter a valid Antispam API key.` and allows the user to enter one + provides instructions for acquiring one directly from Akismet.com.

### Context

p9F6qB-7Kz-p2#comment-43882

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by JoshuaGoode** [comment]
Noting that Jetpack’s `wp-admin/admin.php?page=jetpack#/settings` page shows the sites have a valid API key. This is from a [change made in 2020](https://github.com/Automattic/jetpack/pull/16542) to support sites that have a globally set key.

So, this issue is specifically with Calypso.

![Screen Shot on 2021-11-30 at 15:33:56](https://user-images.githubusercontent.com/4887830/144124117-876c0c5b-8c84-4657-95a8-0f7b0c085d56.png)

**Comment by i11za** [comment]
One more report in 33287867-hc

**Comment by brinbliss** [comment]
Another at 33585495-HC

**Comment by jenhooks** [comment]
4686437-zen | chyp.com

**Comment by flameslash** [comment]
Reporting this for 4682909-zd-woothemes

**Comment by jartes** [comment]
Another one on: 33923468-hc

**Comment by brinbliss** [comment]
Found another at 33958191-HC

**Comment by i11za** [comment]
Another report in 32132964-hc

**Comment by i11za** [comment]
Another report in 34051051-hc (user reached out regarding another unrelated issue)

**Comment by jromales** [comment]
+1 on 34180000-hc 

This user reached out regarding a different issue on Jetpack, and I saw the warning `Your site needs an Antispam key` in security settings.

**Comment by mxhassani** [comment]
Same report 34185194-hc

**Comment by marutim** [comment]
Another report here: 34318181-hc

**Comment by mmtr** [comment]
I think this has been fixed by https://github.com/Automattic/wp-calypso/pull/61200.

Apparently the issue was that Calypso failed to consider the site as an Atomic site and as result it displayed the Anti-spam settings which are only intended for self-hosted Jetpack sites:

https://github.com/Automattic/wp-calypso/blob/e32a8cc05b5e944fea0c2070f927d03ffc8d051d/client/my-sites/site-settings/form-security.jsx#L65

However, the PR above fixed the issue by correctly setting the `isAtomic` property:

https://github.com/Automattic/wp-calypso/commit/0cc1c2443ff08946ff63d70ddc8a1f2c34dafd5b#diff-4833dcb4ba276bb540a0ff706bb1188b5471d86200d38fe876e00a5ba495d463R100

Thanks @arcangelini!
