### ISSUE TITLE
Reader page shown with opacity: 0.5

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#58596]
### Quick summary

On some linked pages within the Reader are showing with an `opacity: 0.5` for the article content.

### Steps to reproduce

1. Go to any blog post with the Reader
2. Click on the Star Like button to view other users who have liked the post
3. Click on the username of another user who has liked the blog post
4. You will be directed to this other users Reader page, but content shows with `opacity: 0.5`

### What you expected to happen

I would expect the page to load fully visible, without any opacity.

### What actually happened

The content is shown within the Reader with a `opacity: 0.5`.
![Annotation on 2021-11-29 at 18-53-12](https://user-images.githubusercontent.com/44442769/143918988-7828b8e8-2579-49b8-9fb7-330216cd5e53.png)

Video example: 

![Screenshot](https://d.pr/i/kLKci1+)
*If you are unable to see this image, please click [here](https://d.pr/i/kLKci1)*

### Context

Customer report: 
- 32953382-hc 
- 4554073-zen

**Comment by devNigel** [comment]
As a workaround, I suggested using the following CSS using browser extension such as User CSS:

```
.reader-post-card.card.is-seen {
    opacity: 1;
}
```

**Comment by davemart-in** [comment]
Hmm... I followed the steps mentioned and could not seem to replicate this in FireFox, Safari, or Chrome. Perhaps this has been fixed? Closing for now. Please feel free to re-open if you're still seeing the issue. Thanks!
