### ISSUE TITLE
Navigation Block: Vertical Orientation Displays Horizontally on Preview

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#58611]
### Quick summary

Adding a Navigation Block and setting it to Vertical displays the menu vertically in the editor, but not in the preview. If I change the Justification to Center and then back to Left, then it will display vertically in both the editor and preview.

### Steps to reproduce

1. Create a new page
2. Add Navigation block
3. Select an existing menu
4. Set Orientation to Vertical
5. Click Preview in another tab

### What you expected to happen

I expected the menu to display vertically and left-aligned.

### What actually happened

The menu displayed horizontally.

If I went back to the editor and changed the justification to Center and then back to Left, then it would display vertically in the preview.

### Context

4532405-zen

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I used Independent Publisher 2 on my test site.
User used Dyad 2

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Change the Justification to Center and then back to Left, then it will display vertically in the preview.

**Comment by Robertght** [comment]
Thank you for reporting this @ccwalburn ! I was able to replicate this. Moreover, the orientation didn't work for me in the frontend either, but I belive it could be related to this core Gutenberg issue:

https://github.com/WordPress/gutenberg/issues/36902

**Comment by retnonindya** [comment]
For a note; this issue happens on wpcourses.com website too, on the FAQ section 
https://wpcourses.com/faq/

However, I can't use the workaround provided (the issue persists.)

**Comment by Greatdane** [comment]
Closing, this was fixed here; https://github.com/WordPress/gutenberg/pull/37009
