### ISSUE TITLE
Tour Kit: Release to NPM

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#58646]
### What

Publish the package to NPM.

### Why

Because the world needs it :D

**Comment by chihsuan** [comment]
Hey @chriskmnds Do we have a timeline for this? We're implementing a woo spotlight component based on this Tour Kit.

- https://github.com/woocommerce/woocommerce/issues/32892

**Comment by chriskmnds** [comment]
> Hey @chriskmnds Do we have a timeline for this? We're implementing a woo spotlight component based on this Tour Kit.

Hey @chihsuan . Thanks for the ping. That's fantastic! I am not actively involved with the library right now, but I think functionality-wise it should be ready for release to NPM. I am not familiar with the process though and what needs to be done for that. Might be worth pinging someone from #team-calypso (Slack) to offer some guidance? (maybe @jsnajdr or @tyxla or @noahtallen ? )

A couple of comments from me:

- Do we need to update all the ["workspace:^" dependencies](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tour-kit/package.json) to the actual versions on NPM? Maybe similarly also update where Tour Kit is imported as a "workspace" dependency to point to the NPM version once released? 
- Part of this work we also extracted [pagination-control](https://github.com/Automattic/wp-calypso/tree/trunk/packages/components/src/pagination-control) into `packages/components` - not sure if we need to confirm that's pulled from the respective NPM version once/if updated?

**Comment by jsnajdr** [comment]
The publishing process is documented [here](https://github.com/Automattic/wp-calypso/blob/trunk/docs/monorepo.md#publishing).

> Do we need to update all the ["workspace:^" dependencies](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tour-kit/package.json) to the actual versions on NPM

No, Yarn will do this automatically when publishing, using the versions of the local linked packages.

> Part of this work we also extracted [pagination-control](https://github.com/Automattic/wp-calypso/tree/trunk/packages/components/src/pagination-control) into packages/components

Seems you just need to make sure to publish a new version of `@automattic/components` first, after bumping its version, and then publishing the `tour-kit` package will add the new version of `@automattic/components` as a dependency. All that should ensure that the dependency points to a sufficiently new version of the package.

**Comment by noahtallen** [comment]
> No, Yarn will do this automatically when publishing, using the versions of the local linked packages.

A small clarification on this point is that you must use the `yarn` variant of the publish command, because yarn is the thing updating all the workspace links. I think that's covered in the docs as well

**Comment by chihsuan** [comment]
> The publishing process is documented [here](https://github.com/Automattic/wp-calypso/blob/trunk/docs/monorepo.md#publishing).

Thanks @chriskmnds @jsnajdr @noahtallen. I'll check the publishing process and see if I can publish the package.

**Comment by chihsuan** [comment]
> Seems you just need to make sure to publish a new version of @automattic/components first, after bumping its version, and then publishing the tour-kit package will add the new version of @automattic/components as a dependency. 

Hi, @jsnajdr or @noahtallen. I just noticed that the last version of `@automattic/components` is published 2 years ago. Would you like to release a new version or do you think it's okay that Ghidorah handles it?

**Comment by chihsuan** [comment]
Thanks folks! Package is published 🎉  https://www.npmjs.com/package/@automattic/tour-kit

**Comment by chriskmnds** [comment]
Oh! Excellent work @chihsuan ! 🎉
