### ISSUE TITLE
Marketplace: add tax categories to products

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#58651]
Following the initial investigation (pdt2If-z-p2), we've found that we should follow the method of adding tax support described in this FG page (PCYsg-rD-p2).

The tax service has an array (linked in FG) in which all products are mapped to a tax category. Instead of manually adding each marketplace product to this array, we should consider creating some logic that does this automatically.

**Comment by gcsecsey** [comment]
As we're already storing (pdh6GB-1A-p2#comment-144) product data in a WooCommerce backend, I think we could utilize the tax classes of WooCommerce products, and have them act as a map to the WP.com tax classes.

**Comment by cpapazoglou** [comment]
Related diff D71420-code.

**Comment by gavande1** [comment]
Deployed r236534-wpcom
