### ISSUE TITLE
FSE Beta: Add themes to Design step in onboarding

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#58663]
### What

Add new block themes to design picker

**Existing step**

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1699996/144090231-1354f307-c674-4f80-813f-da4c719ef87f.png">

### Why

We need more design choices.

The following themes are ready to add:

- Arbutus
- Russell

These themes should also be added, but first need to be network activated:

- TT2
- Universal Blank

All of themes need testing with our FSE onboarding flow.

#### Testing with FSE beta

- [x] Arbutus (@jeyip + @zaguiini)
- [x] Russell (@jeyip)
- [x] TT2
- [x] Universal Blank (@zaguiini)

(add your username to the theme if you are taking on a testing task)

**Comment by jeyip** [comment]
Could you elaborate on what the difference between "ready to add" vs. "ready, though aren't network activated yet"?

It sounds like:
- network activated = displays in the showcase
- ready to add = production ready

**Comment by creativecoder** [comment]
Per the discussion from our meeting, I've updated the issue description to indicate we shouldn't add any themes to the design picker step that are not yet network activated--this is to avoid the situation that a theme selected during onboarding would disappear when a user switches to a different theme, and can only be switched back by contacting support because it wouldn't show in the themes showcase.

**Comment by jeyip** [comment]
If someone starts testing Russell before I do, you can run [this PR](https://github.com/Automattic/wp-calypso/pull/58695) locally, spin up calypso dev, and walk through FSE onboarding to enable it / start smoke testing

**Comment by jeyip** [comment]
## Testing Arbutus
### Requirements

Tested both the editor + frontend

Default Content
- [x] Default content loaded for Arbutus matches the Arbutus demo site
- [x] No broken blocks on initial load 

Block Patterns
- [x] "Gallery with description and a button" pattern looks like its preview
- [x] "Link in Bio" pattern looks like its preview
- [x] "Talk to the host" pattern looks like its preview
- [x] No theme specific block patterns to test 

Global Styles
- [x] Typography font size, line height, and font weight changes behave as expected
- [x] Background color, text color, and link colors changes behave as expected
- [x] Per block global styles (typography + colors) for the Post title block behave as expected

Block Settings
- [x] Typography font size, line height, and font weight block settings changes behave as expected
- [x] Background color, text color, and link color block settings changes behave as expected

### Browsers

Smoke tested frontend in every browser. Smoke tested the editor in chrome.

- [x] Edge
- [x] Firefox
- [x] Safari
- [x] Chrome

### Notes
Each pattern had issues unrelated to the theme. 
- "Gallery with description and a button" pattern didn't have content padding in the editor
- "Link in Bio" pattern, when inserted, didn't have its social media icons centered in the editor
- "Talk to the host" pattern didn't behave responsively and had overflow when the viewport width was <1080px in the frontend

**Comment by jeyip** [comment]
## Testing Russell
### Requirements

Tested both the editor + frontend

Default Content
- [ ] Default content loaded for Arbutus matches the Arbutus demo site
- [ ] ❌ No broken blocks on initial load

<img width="1279" alt="Screen Shot 2021-12-01 at 3 48 10 PM" src="https://user-images.githubusercontent.com/5414230/144333067-46395678-b9f7-4c49-89a4-6f1d9eab7a38.png">

Block Patterns
- [x] "Gallery with description and a button" pattern looks like its preview
- [x] "Link in Bio" pattern looks like its preview
- [x] "Talk to the host" pattern looks like its preview
- [ ] Theme specific block patterns work as expected

Global Styles
- [x] Typography font size, line height, and font weight changes behave as expected
- [x] Background color, text color, and link colors changes behave as expected
- [x] Per block global styles (typography + colors) for the Post title block behave as expected

Block Settings
- [x] Typography font size, line height, and font weight block settings changes behave as expected
- [x] Background color, text color, and link color block settings changes behave as expected

### Browsers

Smoke tested frontend in every browser. Smoke tested the editor in chrome.

- [x] Edge
- [ ] Firefox
- [ ] Safari
- [x] Chrome

**Comment by jeyip** [comment]
I created an issue to track the block errors with Russell

**Comment by zaguiini** [comment]
I'm planning on testing `Universal Blank` today. Any concerns?

**Comment by creativecoder** [comment]
> I'm planning on testing Universal Blank today. Any concerns?

Sounds good! The "Blank Canvas" theme from the normal (non-FSE) `/new` flow might be a good reference point to test against:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/1699996/144888103-b054c643-d5f8-4f00-b583-add1a4fb9b95.png">

**Comment by zaguiini** [comment]
## Testing Universal Blank
### Requirements

Tested both the editor + frontend

Default Content
- [x] Default content loaded for Universal Blank matches the Blank Canvas demo site (there is no demo site for Universal Blank yet)
- [x] No broken blocks on initial load 

Block Patterns
- [x] "Footer" pattern looks like its preview
- [x] "Gallery" pattern looks like its preview
- [x] "Link in bio" pattern looks like its preview
- [x] "Coming soon" pattern looks like its preview
- [x] No theme specific block patterns to test 

Global Styles
- [x] Typography font size, line height, and font weight changes behave as expected
- [x] Background color, text color, and link colors changes behave as expected
- [x] Per block global styles (typography + colors) for the Post title block behave as expected

Block Settings
- [x] Typography font size, line height, and font weight block settings changes behave as expected
- [x] Background color, text color, and link color block settings changes behave as expected

### Browsers

Smoke tested frontend in every browser. Smoke tested the editor in chrome.

- [x] Edge
- [x] Firefox
- [x] Safari
- [x] Chrome

### Notes
Each pattern had issues unrelated to the theme. 
- "Coming soon" pattern displays the contact form on preview but displays the` jetpack_subscription_form` shortcode on the live version of the site. Is it expected? Shouldn't Jetpack be installed for simple sites?

**Comment by zaguiini** [comment]
Add Blank Canvas 2 to FSE Design Picker: https://github.com/Automattic/wp-calypso/pull/58869

**Comment by zaguiini** [comment]
## Testing TT2

### Requirements

Tested both the editor + frontend

### Default Content

- [x] Default content loaded for TT2 matches the TT2 demo site
- [x] No broken blocks on initial load

### Blocks

All blocks are working as expected. The ones that are problematic, are not TT2 related ✅ 

- https://github.com/Automattic/block-experiments/issues/250;
- https://github.com/Automattic/jetpack/issues/15227.

### Block Settings

- [x] Typography font size, line height, and font-weight block settings changes behave as expected
- [x] Background color, text color, and link color block settings changes behave as expected

### Patterns

No theme-related pattern issues. I did find some problematic patterns that are using some blocks:

- Jetpack `Contact Form`, all of them have styling problems:
- - https://github.com/Automattic/jetpack/issues/19462;
- - https://github.com/Automattic/jetpack/issues/18404.
- https://github.com/Automattic/wp-calypso/issues/59084.

### Browsers

Smoke-tested frontend in every browser. Smoke-tested the editor in chrome.

- [x] Edge
- [x] Firefox
- [x] Safari
- [x] Chrome

### Additional information

- https://github.com/WordPress/twentytwentytwo/issues/299.

**Comment by zaguiini** [comment]
So the only thing missing is TT2 now, right?

**Comment by creativecoder** [comment]
> So the only thing missing is TT2 now, right?

For this issue, yes.

**Comment by zaguiini** [comment]
I'll work on adding TT2 right now.
