### ISSUE TITLE
Theme Showcase: Remove/disable/reroute references to individual premium theme sales

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#58670]
When viewing a premium theme in the Showcase (not available right now, you have to fake it), there's a legacy "Purchase" link in the three-dots menu.

This used to point to a URL like http://calypso.localhost:3000/checkout/[siteurl.wordpress.com]/theme:russell where the individual theme would be added to the cart.

Links like this need to be redirected to add a Premium plan to checkout, or removed if necessary.

**Comment by mreishus** [comment]
https://github.com/Automattic/wp-calypso/blob/a621f56c587177b2351efc758a04be8b7484d899/client/my-sites/theme/main.jsx#L817-L828

**Comment by sixhours** [comment]
This is probably related; when I'm viewing a premium theme on a Business plan / Atomic site and click "Pick this design" from the individual theme sheet, we attempt to add a Jetpack plan `jetpack_security_realtime` to the cart:

<img width="1445" alt="Screen Shot 2021-12-01 at 11 13 12 AM" src="https://user-images.githubusercontent.com/2124984/144271079-925c8559-1ba4-4af1-98c8-6062bcee058b.png">

Atomic/Business plan sites should already have access to premium themes, no need to checkout. I'm not sure if this is because we're testing against retired themes or if the logic needs to be updated for Atomic/Business plan sites.

**Comment by sixhours** [comment]
We're leaving individual purchases alone for now! Closing this.
