### ISSUE TITLE
Purchases: "Upgrade is not cancellable" message when trying to cancel Jetpack Business

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#5867]
#### Steps to reproduce

1. Start at wordpress.com/purchases
2. Click a Jetpack Business plan
3. Click "Subscription and Refund"
4. Click "Cancel Subscription and Refund" Button
5. Click "Yes, Cancel Now" button is overlay
6. See "Upgrade is not cancellable" error in top-right; upgrade is not canceled and no further instructions are provided

#### What I expected

Upgrade to be canceled and refunded

#### What happened instead

"Upgrade is not cancellable" error with no further information on how to cancel

#### Browser / OS version

Chrome 50/OS X 10.11

#### Screenshot / Video

![screen shot 2016-06-07 at 1 54 03 pm](https://cloud.githubusercontent.com/assets/1900444/15868788/54e7e94a-2cb7-11e6-9c33-3db510e7471d.png)

#### Context / Source

#user-report #2690377-t

**Comment by lancewillett** [comment]
I wasn't able to reproduce this in the newer UI — I was able to add and remove a Jetpack Premium upgrade from a test site easily.
