### ISSUE TITLE
Site Editor: Don't hide by default for block only themes

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#58675]
### What

Show the site editor for block-based themes that aren't universal

### Why

Twenty Twenty Two theme will be available on WP.com soon. Right now we hide the Site editor for all sites, by default, unless they opt in to the FSE beta.

This makes sense for universal themes which can use the Customizer, but for block only themes, not having access to the Site editor severely limits the theme.

### How

Use the `wpcom_is_fse_activated` option to hide the site editor only for universal themes. Block only themes should use the unmodified behavior from Gutenberg + Core (remove the Customizer and add the Site editor in the Appearance menu).

**Comment by mattwiebe** [comment]
If I were doing this, I'd probably modify the `A8C\FSE\is_core_fse_active` function to simply add a check for Blockbase as the parent theme ( `pub/blockase' === get_option( 'template' )` ) and only require the `wpcom_is_fse_activated` option in that case.
