### ISSUE TITLE
Navigation Menu Block mobile menu page jumps do not work.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#58686]
### Quick summary

When using the mobile menu on the navigation block, page jumps on the same page being viewed will not work. The menu will be non-responsive.

### Steps to reproduce

1. On a page, create a navigation menu block and have one of the links go to a page jump on the same page.
2. View the page on mobile
3. Open the menu and click the link to go to the page jump on the same page.

### What you expected to happen

The menu should close and take me to the area of the page the page jump links to.

### What actually happened

The menu is non-responsive and my view doesn't change at all.

### Context

4558575-zen

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Happens on two themes I tried. Blank Canvas and Arbutus, possibly happens on all themes.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

The way to work around this is to turn off the mobile menu. However this means that the desktop menu is displayed on all devices for that navigation block.

**Comment by Greatdane** [comment]
Confirmed. 

This could be a core Gutenberg issue as I also could not get it to work on as self-hosted site.

**Comment by cometgrrl** [comment]
Filed issue: https://github.com/WordPress/gutenberg/issues/37387

This issue is tracking an issue in another repository. All +1's of end-user reports should be done on this issue, while any discussion related to the issue itself and its fix should be done on the issue in the outside repository.

**Comment by KirkwallDay** [comment]
Just a note that I cannot reproduce this on any theme anymore, so it looks like it was fixed! Closing this issue!
