### ISSUE TITLE
FSE Beta: hide the Customizer for FSE beta sites using universal themes

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#58680]
### What

Currently FSE beta sites with universal themes show both the Site editor and the Customizer. Instead, hide the customizer for FSE beta sites with universal theme.

### Why

Showing only one editing interface is intended to

- Help surface gaps in the Site editor where we need to add features currently available in the Customizer, but not the Site editor
- Simplify the experience so users aren't presented with 2 different design editing interfaces without clear guidance on which one to use

### How

We'll need to detect if a site is in the FSE beta and remove the override that shows the Customizer for a block-based theme (which Gutenberg/Core normally hides)

**Comment by creativecoder** [comment]
> We'll need to detect if a site is in the FSE beta and remove the override that shows the Customizer for a block-based theme (which Gutenberg/Core normally hides)

Alternatively, it might be simpler just to use the `wpcom_is_fse_activated` option as a flag... when it's true, show the Site editor and hide the Customizer... when false, hide the Site editor and show the Customizer

**Comment by creativecoder** [comment]
Example of a gap where we depend on the Customizer: https://github.com/Automattic/wp-calypso/issues/58798

**Comment by Addison-Stavlo** [comment]
Another gap where we depend on the customizer is for setting the heading and base font groups.

**Comment by zdenys** [comment]
On AT site with Geologist theme, there is a mismatch of how Menus preview between Customizer and Site Editor.

![image](https://user-images.githubusercontent.com/39308239/147761712-270c0cb0-0c4d-4830-848f-9394dad0b7a1.png)

Also, notice that [Subscription Form Block](https://wordpress.com/support/wordpress-editor/blocks/subscription-form-block/) by Jetpack doesn't render properly in Customizer and appears as a shortcode.

**Comment by zaguiini** [comment]
I'm not sure about this. What if the user doesn't want to use FSE? Having the option to opt out of it seems better to me.

**Comment by creativecoder** [comment]
I'm going to close this, as Core has settled on showing the Customizer based on if there are functions hooked into `customize_register` or not (https://make.wordpress.org/core/2022/01/07/state-of-the-customizer-with-block-themes-in-wordpress-5-9/), and I think we should stick with that.

I do think we need to clean up some related code in ETK, which I've created a separate issue for here: https://github.com/Automattic/wp-calypso/issues/60064.
