### ISSUE TITLE
Task: Help test Twenty Twenty Two theme on WP.com

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#58682]
### Details

We're in the planning stage for testing TT2 on WordPress.com. Let's help test how it would work outside of the FSE beta.

### Checklist

- [ ] Activate TT2 (`pub/twentytwentytwo`) and test it

### Related

https://github.com/Automattic/wp-calypso/issues/58675

**Comment by creativecoder** [comment]
cc @zaguiini @jeyip Let's have each of us spend some time testing TT2

**Comment by zaguiini** [comment]
You can activate the theme by running the following command inside your sandbox:

```sh
wp theme activate pub/twentytwentytwo --url=<SITE-URL>
```

Passing the site URL is important.

**Comment by zaguiini** [comment]
I believe we can close this now.
