### ISSUE TITLE
Switching themes and electing to change homepage possibly not setting _wp_page_template

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#58693]
### Details

-> `wp headstart run --url=site-here --user=username --theme=pub/payton --delete-content`
Correctly sets the homepage `_wp_page_template` of the homepage to `header-footer-only`

We think that using "theme switch, change homepage" does not apply this setting.

**Comment by mreishus** [comment]
![2021-11-30_16-33](https://user-images.githubusercontent.com/937354/144143834-7dd75e5c-17e9-455d-a648-89191df347fa.png)
![switch-theme-4b](https://user-images.githubusercontent.com/937354/144143847-74f4b23e-208f-4cc9-9864-529046d4325b.png)
![switch-theme-4c](https://user-images.githubusercontent.com/937354/144143854-faf9b49d-87f5-493b-8642-b1a73d9ea8fd.png)

**Comment by mreishus** [comment]
Created D70901-code

**Comment by simison** [comment]
FYI @Automattic/cylon

**Comment by mreishus** [comment]
@alaczek: We've addressed this and theme switch should now be setting the template properly. Let me know if it's still not working.
