### ISSUE TITLE
Redirection to themes page from wp-admin dashboard broken

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#58704]
### Quick summary

On a simple site (not reproducible on Atomic sites), clicking on the "Themes" option from wp-admin dashboard redirects to a broken page.

### Steps to reproduce

- Start with a simple WordPress.com site (any WordPress.com site without third-party themes or plugins installed)
- Visit the wp-admin dashboard page, like wp-admin widgets: domain.com/wp-admin/widgets.php?calypsoify=0 
- Click on "Themes" from the left menu.

### What you expected to happen

Themes page loads fine.

### What actually happened

Redirects to a broken page. In my case, these links:

- https://wordpress.com/themeswpcomarun.wordpress.com
- https://wordpress.com/themeswpcomarunblog.wordpress.com

The redirection is visible on network requests panel of dev tools too:

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/18581859/144245467-02d18cab-c710-4a30-8f68-094a6c93f2b9.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18581859/144245502-f816ee01-83d6-459f-8e95-69081147310f.png">

### Context

Found by manual testing.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No.

### Browser, operating system and other notes

- Firefox 94.0.2, MacOS 12.0.1.
- Issue is not visible when starting on a different Calypso page like https://wordpress.com/settings/general, it's happening only on visits from wp-admin dashboard.
- Atomic sites are fine.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

**Comment by Robertght** [comment]
I can't seem to replicate this anymore. Could you give this another go @arunsathiya ?

**Comment by arunsathiya** [comment]
@Robertght I can consistently reproduce the issue! It happens on Firefox, Edge, Safari, regular and private window, and even on a different device without work proxy or ad/tracker-blockers.

**Comment by arunsathiya** [comment]
This is a video of what I see: we can note that the issue occurs when leaving from wp-admin dashboard to themes page, but not from Calypso to themes page.

https://user-images.githubusercontent.com/18581859/144602545-a1c79ea3-13f5-4e2d-bac9-f4dc157884ba.mov

**Comment by Robertght** [comment]
I had another go at this and I can't replicate it in either Firefox(fresh installation) or Chrome. 

@jordesign tested this as well but no dice

@mmtr for a second look if you have the bandwidth(thanks!)

**Comment by mmtr** [comment]
Cannot reproduce either, don't know what's causing this issue 🤔 

This is the exact line of code where we modify the "Appearance > Themes" submenu: 

https://github.com/Automattic/jetpack/blob/ec5d8c7ffa4e33c0b8c918eea36fbf826e6e63c4/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L343

Note how the slash (`/`) between `wordpress.com/themes` and the site domain is hardcoded there. Seems something is stripping out that slash for @arunsathiya, but I have no idea what could be the culprit.

**Comment by arunsathiya** [comment]
Thanks for testing, @mmtr! @jordesign, @Robertght and I spoke here on Slack: p1638941988427700-slack-C01UW7SB411

We have narrowed down the issue to site addresses starting with `premium` and `free`. `personal`, `business` and `eCommerce` are fine. Example links:

- premiumtest974580663.wordpress.com
- free826406317.wordpress.com

These are fine:

- personal960590923.wordpress.com
- ecommerce962997588.wordpress.com
- businesstime557251258.wordpress.com
- premiumwpcomjordan.wordpress.com

Let me know if I could help with anything more.

**Comment by jordesign** [comment]
@kwight @sixhours is it possible that the old URL routing/filtering for the Theme showcase used /free/ and /premium/ to show those sets of themes (before we removed premium themes) and those strings are now being removed on the Theme showcase?

**Comment by kwight** [comment]
I can reproduce this by just trying to load `https://wordpress.com/themes/premium.wordpress.com`.

I'm 99% sure this problem is coming from here: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/themes/index.node.js#L24 but I'm having a hard time creating and testing a fix; I think it needs something like this:

<img width="394" alt="Screen Shot 2021-12-08 at 8 56 18 AM" src="https://user-images.githubusercontent.com/349751/145250250-ec9e6342-caad-44cc-935c-c190abccfeae.png">

I'll see if I can pair with @mreishus who might have some experience with showcase testing from the Design Selection pod days.

**Comment by jordesign** [comment]
Thanks @kwight  - much appreciated.
