### ISSUE TITLE
Domain Search: Redux overrides network errors

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#5870]
If you go to Domain Management -> Add domain and cut the network off; when you search for something you'll get the initial suggestions and nothing about the connection error. 

I think this was introduced in #5738 

/cc @gwwar 

ps: I'm working on some refactoring around domain search (lib/components/domains/*), so if this change requires a lot of changes around those files, it might be a good idea to hold working on this until later this week :)

**Comment by gwwar** [comment]
Thanks for ping. I'll keep this in mind when you're done refactoring. I was planning to refactor domains search to use the QueryDomainsSuggestions, versus the bare wpcomjs calls we make.

**Comment by gwwar** [comment]
I'll see if I can find a simple fix in the meantime.

**Comment by klimeryk** [comment]
@gwwar: wondering what's the status of this issue? I see some work has been done in #5873 and closed without merging - was there something wrong with that approach or it just got stale? I wonder if we could resurrect it and merge :)

**Comment by gwwar** [comment]
It was mostly closed out due to staleness, and since it was unrelated to the query component refactoring. It's a simple issue to fix, but we should update this issue with what the expected error state should look like.

**Comment by klimeryk** [comment]
Marking as wontfix. This does not seem to be generating any noticeable customer issues - and I'd rely first on the OS' notifications for losing network connection.
