### ISSUE TITLE
WPCOM Plugins Api: add documentation and demo urls

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58701]
Let's add 
- `demo_url`
- `documentation_url`
![SS 2021-12-01 at 14 14 35](https://user-images.githubusercontent.com/12430020/144232752-844660c4-2425-46c1-a86a-17f3b8a81175.png)

Related to https://github.com/Automattic/wp-calypso/issues/57758#issuecomment-983581918

**Comment by cpapazoglou** [comment]
After a walkthrough to the woocomerce.com interface it seems that the demo url is not required, but it is optional and up to the vendor to include it.

**Comment by gavande1** [comment]
Reserved for onboarding!

**Comment by gavande1** [comment]
Diff created:  D72233-code

**Comment by gavande1** [comment]
Deployed at r237280-wpcom
