### ISSUE TITLE
Allow Disable Plugins Bulk Action

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#58712]
### What

In WordPress Core, there is an option to disable multiple plugins through the bulk actions dropdown.

![disable-all-plugins](https://user-images.githubusercontent.com/12906034/144295716-9acf5204-00aa-41ad-9ce3-c4107fb8c0fb.gif)

On Atomic sites, this feature is not available.

<img width="1267" alt="Screen Shot 2021-12-01 at 1 49 32 PM" src="https://user-images.githubusercontent.com/12906034/144295759-01d96332-9350-4820-a16e-27014754cc8d.png">

### Why

User in 4561158-zen would like to have this feature available. This would save them several clicks when deactivating multiple plugins.

**Comment by JoshuaGoode** [comment]
Thanks for the report! Closing in favor of https://github.com/Automattic/wp-calypso/issues/56923 

Your screenshots help paint a better picture, though.  Can you copy over your notes to a comment on that issue @masperber ?

**Comment by masperber** [comment]
@JoshuaGoode comments and images copied. Thank you!
