### ISSUE TITLE
Widget Customization Error: "The editor has encountered an unexpected error."

### ISSUE THREAD

**Issue by mlanasa** [Automattic/wp-calypso#58716]
### Quick summary

User reported in a ticket that they were having problems with updating widgets in the customizer. User describes being able to make successful updates via the desktop application but not through a browser.

### Steps to reproduce

1. Please watch this video for reproducing the error:
https://user-images.githubusercontent.com/95254246/144301953-d2bb8f86-20ae-427b-bcc5-73a7c84d9ec4.mp4

 

### What you expected to happen

The updates to the widget should have taken effect and saved.

### What actually happened

An error screen appeared in place of the customization tab.

### Context

4553339-zd-woothemes

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

User mentions being able to successfully update widgets via the desktop app (opposed to the browser where the problem is occurring).

**Comment by Robertght** [comment]
I'm going to close this in favor of this one for now: https://github.com/Automattic/wp-calypso/issues/58594
