### ISSUE TITLE
On the domains security screen in Calypso, the support links are irrelevant to domain security

### ISSUE THREAD

**Issue by emilyaudela** [Automattic/wp-calypso#58729]
### Quick summary

In the [domains>manage -->](https://wordpress.com/domains/manage/) screen in Calypso, when you go to Security, there are 2 links to support documents after the HTTPS encryption information. The two links are about the eCommerce plan and forms, which are irrelevant to the content on the page itself. 

![Markup on 2021-12-01 at 18:23:58](https://user-images.githubusercontent.com/36699353/144340507-1e5b7fe2-e552-4c62-a3fa-4388186ba562.png)

### Steps to reproduce

1. Start at https://wordpress.com/domains/manage/.
2. In the 3 dots menu, select Security. 
3. On the Security page, there are 2 links to support docs that are irrelevant to the content on the Security screen in Calypso.

### What you expected to happen

I would expect the support links to relate to https encryption or domains, such as: https://wordpress.com/support/https-ssl/

### What actually happened

I saw the following links "Learn more about selling products on WordPress.com" and "Learn more about forms on WordPress.com".

**Comment by Robertght** [comment]
Thank you for reporting this @emilyaudela !

I can confirm this is a thing on my end as well.

LE: Circling back to this, the resources are somewhat related, but I'm wondering if there would be a better fit.

**Comment by cometgrrl** [comment]
@Robertght Should we classify this as an improvement? I'm not sure it's a bug.

**Comment by delputnam** [comment]
This page shouldn't be accessible any longer. The SSL status is now just a sub-section on the management page with a single "Learn more" link that goes to: https://wordpress.com/support/https-ssl/

<img width="1052" alt="Domains_‹_A8C_Test_Site_—_WordPress_com" src="https://user-images.githubusercontent.com/1379730/173922096-d0bddda8-54c1-4701-9610-bf915223e2cb.png">

I'll mark this closed, but if I'm missing something please re-open and let me know.
