### ISSUE TITLE
Additional theme price cleanup

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#58726]
### Details

After #58677, I realized there are more references to theme price we might be able to get rid of:
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/components/themes-list/index.jsx#L28
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/components/themes-list/index.jsx#L47
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/components/themes-list/index.jsx#L87
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/my-sites/themes/themes-selection.jsx#L165
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/my-sites/themes/themes-selection.jsx#L185-L187
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/my-sites/themes/themes-selection.jsx#L242
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/my-sites/themes/themes-selection.jsx#L14
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/my-sites/themes/themes-selection.jsx#L42
https://github.com/Automattic/wp-calypso/blob/0ebe5406d2b77f85a70566441124cfd4bd745b56/client/state/themes/selectors/get-premium-theme-price.js#L1-L33

**Comment by sixhours** [comment]
Since we're leaving individual prices for now, let's close this out.
