### ISSUE TITLE
Blank box on search result for specific plugin keywords

### ISSUE THREAD

**Issue by vajrasar** [Automattic/wp-calypso#58734]
### Quick summary

If you search for `lightweight sidebar manager` plugin on your atomic site, you should see any issue where a big blank black box is shown in the search result before the actual list of results.

### Steps to reproduce

1. Plugins > Add New
2. Search for `lightweight sidebar manager`

### What you expected to happen

To see the list of plugins under `lightweight sidebar manager`

### What actually happened

A blank black box followed by actual list of plugin results

### Context

I found this issue while helping a user on the chat. 

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Screenshot

![Here](https://iamgroot01.blog/wp-content/uploads/2021/12/Screen-Shot-2021-12-02-at-10.58.59.png)

**Comment by inaikem** [comment]
Screenshot: 
<img width="1338" alt="Screen Shot 2021-12-02 at 2 45 33 PM" src="https://user-images.githubusercontent.com/66711744/144371850-a7fef364-249d-4fce-b264-453f8e6d9c71.png">

&nbsp;
Note: the grey box above extends well below the fold (the above is a comp based on two screenshots)

On scroll, the grey box overlaps the header above it:

<img width="1229" alt="Screen Shot 2021-12-02 at 2 51 39 PM" src="https://user-images.githubusercontent.com/66711744/144372484-e0a7f12a-2dac-4723-9687-d9c49eb1af0d.png">

&nbsp;

@Robertght, it feels this might be something @Automattic/flowpatrol could help with. What do you think?

**Comment by Robertght** [comment]
I was going to ping @cpapazoglou but he was way faster. :)
