### ISSUE TITLE
Has anyone even gotten this shit to work?

### ISSUE THREAD

**Issue by muffeeee** [Automattic/wp-calypso#5874]
I've been struggling with this crap for weeks. It looks really slick and nice, but the installation progress is the shittiest ever.

After needing to run ´npm install´ manually to install all dependencies, wp-calypso is still filled with deprecated and non-compitable packages.

I still get errors with babel-runtime (which fails to install, by the way):
´´´
ERROR in ./client/lib/upgrades/actions/index.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/interop-export-wildcard' in /home/muffe/wp-calypso/client/lib/upgrades/actions
resolve module babel-runtime/helpers/interop-export-wildcard in /home/muffe/wp-calypso/client/lib/upgrades/actions
  looking for modules in /home/muffe/wp-calypso/client
    /home/muffe/wp-calypso/client/babel-runtime doesn't exist (module as directory)
  looking for modules in /home/muffe/wp-calypso/node_modules
    resolve 'file' or 'directory' helpers/interop-export-wildcard in /home/muffe/wp-calypso/node_modules/babel-runtime
      resolve file
        /home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard doesn't exist
        /home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard.json doesn't exist
        /home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard.js doesn't exist
        /home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard.jsx doesn't exist
      resolve directory
        /home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard doesn't exist (directory default file)
        /home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard/package.json doesn't exist (directory description file)
[/home/muffe/wp-calypso/client/babel-runtime]
[/home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard]
[/home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard.json]
[/home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard.js]
[/home/muffe/wp-calypso/node_modules/babel-runtime/helpers/interop-export-wildcard.jsx]
 @ ./client/lib/upgrades/actions/index.js 7:29-85
´´´

Calypso still (somehow) thinks everything is OK and moves on with whatever it's doing. Upon visiting the WP-calypso URL, I'm presented with a Wordpress logo and a bug tracking icon on the lower left corner. Absolutely nothing else, and completely useless.

Now, look, I'm not trying to bash this shit completely, because I actually do believe in calypso and really want to use it - but it just simply fails to work, and continues to be the oddest nodejs project I have ever seen.

Anyway, since the installation guide sucks (I mean, it is obviously outdated), has anyone gotten this shit to even work and function at all? The fact that Wordpress.com is using this in production really concerns me, considering the high amount of issues and problems this project has.

**Comment by klimeryk** [comment]
Thank you for your bug report! However, based on the information you've provided, I cannot reproduce your issue. Please make sure you have the newest recommended `node` (`v5.11.1` [at the moment](https://github.com/Automattic/wp-calypso/blob/59e44d07a569cce3677c8b48fa77cf86b4aa18eb/package.json#L118)) and try again with clean `node_modules`.
