### ISSUE TITLE
Ability to import DNS records

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#58755]
### What

An ability to import DNS records when moving from another DNS host to WordPress.com would be nice.

### Why

Today, we preserve the same nameservers when the domain is transferred-in to WordPress.com. But there's a toggle within Calypso to change nameservers to WordPress.com's, which when activated means their old DNS host's records aren't valid anymore. This results in accessory products/services' failure, like email outage or webmaster tools (Google Search Console as an example) verification failure.

### How

When transferring-in the domain, it'd be nice to have a screen that asks the customer if they'd like old host's records imported over to WordPress.com.

**Comment by delputnam** [comment]
I can't really think of a good reliable way to do this now that almost everyone has disabled AXFR. We can fairly easily get the records on the root zone, but this will miss any records that are set on a subdomain. And there's really no reliable way that I know of to get these subdomain records.

If we could somehow get the users to export their DNS from their current name service in a common format (like BIND) then we could import that, but I fear this is probably beyond the scope of what most users will know how to do correctly and may not even be available to them on many DNS providers anyway.

I guess that my main fear is that we won't be able to implement this reliable, and it will give users a false sense that we have imported all of their records, but some will be missed and then their services will be broken.

I'm wondering if it might be better to focus on expanding our ability to automatically generate DNS records for popular services (ex.: google workspace, microsoft o365, etc)

**Comment by arunsathiya** [comment]
>If we could somehow get the users to export their DNS from their current name service in a common format (like BIND) then we could import that, but I fear this is probably beyond the scope of what most users will know how to do correctly and may not even be available to them on many DNS providers anyway.

I agree. 👍🏽 The only provider that I know of offering a BIND export is Cloudflare, and the only two support BIND imports are Cloudflare and [Bunny](https://panel.bunny.net/dnszones). 

I have seen a small uptick in customers moving to WPcom DNS but losing their third-party email records in the last few months, thus the feature request here. If this isn't worth our effort/time, happy for this issue to be closed. We can continue guiding customers to get the necessary records from the respective providers and help add at our end.

>I'm wondering if it might be better to focus on expanding our ability to automatically generate DNS records for popular services (ex.: google workspace, microsoft o365, etc)

I know that we already do this for Google Workspace, Office 365 and Zoho:

- https://wordpress.com/support/add-email/add-email-through-google-workspace/#set-up-google-workspace-with-a-txt-record
- https://wordpress.com/support/add-email/add-email-through-office-365/#set-up-your-dns-records-on-word-press-com
- https://wordpress.com/support/add-email/add-email-through-zoho-mail/#connect-zoho-mail-to-your-word-press-domain

I am not aware of any other email providers that we set up DNS for, but Google Workspace and Office 365 are what we commonly see.

**Comment by delputnam** [comment]
Yep.  Those are the only ones we have currently (introduced in 2017 😬). If you have any additional data on which email providers users who have "lost" their email records are using, there might be a way we can add those as well.

One other idea is to look specifically for the DNS records related to these popular services and attempt to copy them. It's likely there is still enough variation between versions of systems that we might get something wrong, but if this problem is common enough it's potentially worth some additional investigation.

I'll close this issue and add a task to our (Nomado's) list to do some more investigation on this and see if there's something we can do to improve this.
