### ISSUE TITLE
My Home: image is cut off in blogger card in Grow & Learn carousel

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58763]
### Description
The graphic in the Grow & Learn card is cut off.   Going forward & back in the carousel causes the graphic to show normally. Originally [reported here](p1638456174347100-slack-C029SB8JT8S).

![image](https://user-images.githubusercontent.com/5665959/144457275-639e8b52-9ba0-48b7-a837-9a207c521599.png)

https://user-images.githubusercontent.com/5665959/144457607-6bc81e1d-6e50-4af4-92f3-f2824079ba1b.mov

#### Steps to reproduce

1. On a blogger site, go to My Home
2. See the Grow & Learn Carousel, as pictured above
3. See it is cut off

#### What I expected
Graphic should not be cut off

#### What happened instead
Graphic is cut off.

Additionally let's update the graphic, as @ollierozdarz shared in the comments below.  Figma file linked in the comment.

![image](https://user-images.githubusercontent.com/5665959/146971349-db7fc26f-ca98-4c54-9d6f-08f908de525b.png)

**Comment by ollierozdarz** [comment]
Thanks @autumnfjeld. I say lets get this one resolved then I can look at designing something nicer as I clear my plate 🙂

**Comment by ollierozdarz** [comment]
<img width="745" alt="Screen Shot 2021-12-16 at 4 36 17 pm" src="https://user-images.githubusercontent.com/67085494/146320516-85280188-05da-450a-b06a-dee34a2d17b5.png">


@autumnfjeld how about this?

[Figma](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/Blogger-Experience?node-id=3273%3A1563)

**Comment by arthur791004** [comment]
https://github.com/Automattic/wp-calypso/pull/59645 is working on this.

**Comment by arthur791004** [comment]
Close it as https://github.com/Automattic/wp-calypso/pull/59645 is shipped!
