### ISSUE TITLE
Videos UI: Update the Field Guide page.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58777]
The Field Guide page at PCYsg-DgC-p2 will need updating with at least:

* the newest Tracks events,
* notes on the header and footer component props.

**Comment by andres-blanco** [comment]
`wpcom_courses_course_complete` Track event: https://github.com/Automattic/wp-calypso/issues/58812

**Comment by sixhours** [comment]
It looks like `wpcom_courses_course_complete` has been added to the list of Tracks events. I'll look into the Header/Footer component props.

**Comment by sixhours** [comment]
It looks like info about the Header/Footer component props have been added to the Videos UI README in #62467 so rather than duplicate that info in the FG I say we link to the README from the FG and call it good. I'll do that and close this out.
