### ISSUE TITLE
Videos UI: Consider a snackbar notice to better celebrate video and course completions.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58776]
Brought up by @ianstewart :

To better celebrate video and course completions, we should consider showing a snackbar in addition to the checkmark updating.

cc/ @ollierozdarz

**Comment by kwight** [comment]
"Congratulations on completing the course!"?

**Comment by sixhours** [comment]
We're not likely to work on this in the next year, so closing for now.
