### ISSUE TITLE
Videos UI: If the UI is closed then re-opened, its progress values are those from the original page load.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58774]
If the UI is closed then re-opened, its progress values are those from the original page load. So if a user has three videos complete when they load their page, and then:

* open the UI,
* complete a video,
* close the UI,
* then open the UI again without a page load,

... the UI will show only the original three videos as complete (and not count the video just watched). This will correct itself with another page load.

**Comment by andres-blanco** [comment]
This is related to the way we are consuming course progressions. I will move the course completions information to the `/courses` endpoint.

**Comment by andres-blanco** [comment]
D71027-code
