### ISSUE TITLE
Reader: No Left Margin on Followed Sites Options on Mobile

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#5878]
Steps to Reproduce

1. Visit https://wordpress.com/following/edit on a mobile browser app (preferably a small-screen mobile device/phone)
2. Tap on the " > " beside any followed site
3. Note the missing left margin beside "Emails for new posts" and "Emails for new comments"

![](https://cldup.com/JmU7wyy9bi.png)

Happens in iOS (iPhone 6s+ Safari/Chrome) and Android (Samsung S7 Edge Chrome/Firefox).

**Comment by jeremeylduvall** [comment]
Closed via #6257.
