### ISSUE TITLE
[Bug]: Page Layout Picker sometimes will not close.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#58786]
### Quick summary

I experienced this on a legacy dotcom FSE site (deprecated experience from the editing toolkit), but am not yet sure if it is present outside of legacy FSE.

Sometimes when creating a new page, the page layout picker will not close:

![legacy-fse-page-layout](https://user-images.githubusercontent.com/28742426/144496804-cd81bc1a-a386-4604-a593-b65374dc43c6.gif)

### Steps to reproduce

I am not entirely sure how to reproduce this consistently.  I have encountered it twice today when creating a new page in a legacy FSE site.  Since I cannot reproduce it consistently there, I am unsure whether or not it is present outside of legacy FSE.

1.  Create a new page on a legacy FSE site.
2.  Pick a design in the page layout picker or hit the "x" button.
3.  (Maybe?) Notice that the page layout picker will not close.

### What you expected to happen

The page layout picker should close when a design is selected or the X button is pressed.

### What actually happened

See the gif above.

### Reproducibility

Intermittent

### Workaround details

The only work around is to hit the browser's back button, try to create a new page again, and hope the issue doesn't happen the next time.

**Comment by msilbers** [comment]
reported in #33620567-hc

**Comment by renata-franco** [comment]
Hello there. I worked with the user from the chat mentioned above today and it looks like the issue is that they had the Gutenberg plugin deactivated. Once I activated the pages can be created once again. Ticket with the resolution: 5172512-zd-woothemes

**Comment by Addison-Stavlo** [comment]
Closing this as duplicate in favor of https://github.com/Automattic/wp-calypso/issues/62788
