### ISSUE TITLE
[Bug]: Russell Theme renders block errors in the site editor on initial load

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#58787]
### Quick summary

When loading the Russell theme for the first time in the site editor, it renders with block errors.

<img width="1279" alt="Screen Shot 2021-12-01 at 3 48 10 PM" src="https://user-images.githubusercontent.com/5414230/144333067-46395678-b9f7-4c49-89a4-6f1d9eab7a38.png">

### Steps to reproduce

1. Apply branch to local calypso dev environment
2. Visit http://calypso.localhost:3000/new/beta
3. Enroll in the FSE beta
4. Pick a free test domain
5. Verify that Arbutus is a selectable theme
6. Create a site with Arbutus enabled and smoke test the theme

### What you expected to happen

On initial load, there are no block errors

### What actually happened

On initial load, there _are_ block errors

### Reproducibility

Consistent

### Notes

Related to https://github.com/Automattic/wp-calypso/issues/58663

**Comment by creativecoder** [comment]
Potential fix at D71041-code.

Note that it's very possible this issue exists with other themes with starter content saved before Nov 28th, when D70425-code was deployed. cc @Automattic/theam

**Comment by creativecoder** [comment]
Resolved by D71041-code

**Comment by creativecoder** [comment]
Reopening, as there's another error showing for the Post Title block

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1699996/144897817-3de40584-05f3-4dd2-9022-7c49cbaf19ed.png">

```
TypeError: can't access property "rendered", h is undefined
    edit https://s0.wp.com/_static/??-eJylUe1uwyAMfKERL91X92Pas0CwIqcGMgz9ePu5mrJVmmhW7R/HnY8zB4fZDCkWjAVmriNFgbEqdJhHZTLCvt90910PrhJ7cJyGnWFy2eYTUPR47ALFbpI7uNVrEf3PBT0VI1Twtw/FgatHgUmgKpnlPN9SODvsXIpNXmEtxFfoNYegWa0JySNLS6M7z5ysh5CO1HT6Vi2HlnCSFDerLnq/avRRURuvpMGqNIP9yCTlYh1f/wxkDOemL4Gx0Wsce8J8+2ygMdvyt0eVu8StGTuTyah7SVMyMM0u2dz8va/m94SHpfj38NY/P7xstk/bx9fpE5ynTEM=:74
    Le https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7
    Pj https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:10
    di https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8
    Nj https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8
    sc https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8
```

**Comment by zaguiini** [comment]
> Reopening, as there's another error showing for the Post Title block

That is fixed in the latest version of Gutenberg. I saw that and simply running trunk fixes the problem. Other themes suffer from the same issue if the page title is empty or undefined.

**Comment by creativecoder** [comment]
Thanks so much @zaguiini !

I've confirmed that when running Gutenberg trunk on the site I don't see the error... seems I can keep this closed after all.
