### ISSUE TITLE
Find a way to 'soft-launch' new premium themes

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#58792]
### Details

Find a way to 'soft-launch' new premium themes: Make them available for testing without making them available for the general public.

Since themes can be browsed in Calypso or WP-Admin, this might have to be an API mu-plugin that checks if you're A8C.

**Comment by sixhours** [comment]
We may be able to ping @mattwiebe to help/brainstorm with this since he's working on a similar issue with Twenty Twenty Two.

**Comment by sixhours** [comment]
Potential/partial solution started in D71093-code

**Comment by sixhours** [comment]
This has been done! 🥳 r236255-wpcom
