### ISSUE TITLE
Posts: support custom post types

### ISSUE THREAD

**Issue by diddledan** [Automattic/wp-calypso#588]
Currently the CPT support in Calypso seems to be link-only which opens a browser to the site's wp-admin. Ideally the Calypso UI should be able to interact with CPTs directly.

See also #587

**Comment by chuckreynolds** [comment]
yeah... unfortunately that's a deal breaker. Looking forward to this in future release. :+1:

**Comment by amandarush** [comment]
Post types also do not seem to be supported when using the editor from wordpress.com, at least with a screen reader. Looking forward to this becoming a feature as one of my sites is pretty dependent on CPTs.

**Comment by aidanlane** [comment]
+1 for this, as CPT support is incredibly important for us.

**Comment by abdusfauzi** [comment]
+1

**Comment by jeherve** [comment]
Also suggested here:
http://wptavern.com/automattic-unveils-open-source-wordpress-desktop-application-for-the-mac/comment-page-1#comment-107928

**Comment by johndnixon** [comment]
+1

**Comment by jeherve** [comment]
Also suggested here:
http://halfelf.org/2015/calypso/

**Comment by macmanx2** [comment]
Also requested at https://wordpress.org/support/topic/add-editing-custom-post-types-in-wp-desktop-or-calypso

**Comment by ntpixels** [comment]
Also requested in #2493190-t

**Comment by ReessKennedy** [comment]
+1

**Comment by rveitch** [comment]
+1

**Comment by sandrahuber** [comment]
+ 1

**Comment by Asitis** [comment]
+1

**Comment by rubenlangius** [comment]
+1

**Comment by dre1080** [comment]
+1

**Comment by alexclst** [comment]
+1. I'm a technology consultant helping run a number of WP sites, one of which is extremely dependent on CPTs. I _love_ using Calypso for most of my WP content editing these days, and truly miss it on that one site. Please add this feature.

**Comment by andrewvorobyov** [comment]
+1

**Comment by nathandao** [comment]
+1

**Comment by igolden** [comment]
+1

**Comment by wpnzach** [comment]
+1

**Comment by moisb** [comment]
That would be wonderful! Including option to edit/add custom fields!

**Comment by codebykat** [comment]
Support for custom post types is launching soon! There's a call for testing over on our Horizon site: https://horizonfeedback.wordpress.com/2016/08/10/call-for-testing-custom-content-types-in-calypso/

If anyone here would like to take it for a spin, we'd love to hear how it works for you. :)

**Comment by moisb** [comment]
Hello Kat. This is great news. Thank you very much!

Att,

     *Moisés B. Böll*
      (48) 8825-5068 ou (48) 3034-1702.
      moises.back

2016-08-11 14:32 GMT-03:00 Kat Hagan <notifications@github.com>:

**Comment by aduth** [comment]
Hi folks, as a follow-on to [@codebykat's previous comment](https://github.com/Automattic/wp-calypso/issues/588#issuecomment-239232500), we've now enabled custom post type support for all users in production environments.

As described in the Call for Testing caveats, if you're using Calypso for your own self-hosted site running Jetpack, you will need to whitelist any post types you'd like to manage in Calypso. This is a consequence of privacy considerations we had made in requiring site owners to opt in to their site's custom post types being made available from the [WordPress.com REST API](https://developer.wordpress.com/docs/api/). For more information about the REST API and custom post types, refer to our [original developer site announcement post](https://developer.wordpress.com/2013/04/26/custom-post-type-and-metadata-support-in-the-rest-api/).

You can enable support by adding a filter like the following to your theme's theme's `functions.php`, or the plugin enabling the custom post type:

```php
function mytheme_restapi_allowed_types( $types ) {
    $types[] = 'my-custom-type'; // Replace with name of CPT
    return $types;
}
add_filter( 'rest_api_allowed_post_types', 'mytheme_restapi_allowed_types' );
```

It is not currently possible to enable or disable Portfolio or Testimonial custom content types for Jetpack sites (part of the "Custom Content Types" module). We will enable these shortly after the release of Jetpack 4.2.

**Comment by aidanlane** [comment]
Now looking forward to #587, which will go quite nicely with this 😃

**Comment by alexclst** [comment]
Aside from looking forward to #587 I'm also looking forward to whenever the WP iOS app gets updated to support CPT editing. I see the WordPress.com website showing the post types' content editable, but on my phone it doesn't even list the custom post types yet. I hope an update is planned to enable this as it is one of the major reasons to have the post types be exposed to the REST API.

**Comment by codebykat** [comment]
CPT editing in the apps is tracked in their own repos. Please do follow along and/or +1 those issues. :)

Android: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/114
iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/500

**Comment by sarahdenise** [comment]
+1
