### ISSUE TITLE
Gutenberg Camel Case typography doesn't work when the text is typed in uppercase.

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#58800]
### Quick summary

The typography setting on a Paragraph Block normally allows text to be converted to uppercase, to lowercase, or to camel case. Text that is natively typed in uppercase cannot be converted to camel case.

### Steps to reproduce

1. Insert a Paragraph Block.
2. Type text in all uppercase.
3. Attempt to convert the text to camel case.

https://user-images.githubusercontent.com/12906034/144537146-fed20074-f727-44cf-9ada-0e0bfc4fbf9b.mp4

### What you expected to happen

Any text should be able to be converted to camel case.

### What actually happened

Text that is natively typed in uppercase cannot be converted to camel case.

### Context

Customer report: 33024050-hc

I reproduced the issue on the customer's simple site. I reproduced the issue again on my Atomic test site.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

I suspect that this would affect relatively few users because it's rare for users to type natively in all uppercase. As a workaround, users could convert the text case externally on a site such as https://convertcase.net/

**Comment by Robertght** [comment]
I was able to replicate this on a self-hosted site as well so I've reported it here:

https://github.com/WordPress/gutenberg/issues/37095

**Comment by Robertght** [comment]
This appears to be the expected behavior so I'll close it for now.

Ref: https://github.com/WordPress/gutenberg/issues/37095#issuecomment-986368214
