### ISSUE TITLE
[Bug]: blue Start flow plans grid has wrong color "free" link

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#58806]
### Quick summary

When I went through importer flow, I saw blue plans grid and visually broken free link:

<img width="1520" alt="Screenshot 2021-12-03 at 12 56 42" src="https://user-images.githubusercontent.com/87168/144591326-042be2b0-75c4-4d7f-b264-b22010721a8c.png">

### Steps to reproduce

1. Start at https://wordpress.com/start/import/from-url?ref=compare%2Fwix-lp
2. You can add my Wix site in the URL `https://mikael393.wixsite.com/website-8`
3. Pick free domain
4. See the plans grid & free link on top 

### What you expected to happen

White link.

### What actually happened

Grey link.

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

Could be just class missing either from HTML or [from SCSS](https://github.com/Automattic/wp-calypso/blob/666e1bf13f78b4304de41d7a5a666d6ec8d9d6df/client/signup/steps/plans/style.scss)?

```diff
-.signup__step.is-plans .formatted-header__subtitle .button.is-borderless,
-.signup__step.is-plans-launch .formatted-header__subtitle .button.is-borderless {
-       padding: 0;
-       color: inherit;
-       font-size: inherit;
-       font-weight: inherit;
-       line-height: inherit;
-       text-decoration: underline;
+.signup__step {
+       &.is-plans,
+       &.is-plans-launch,
+       &.is-plans-import {
+               .formatted-header__subtitle .button.is-borderless {
+                       padding: 0;
+                       color: inherit;
+                       font-size: inherit;
+                       font-weight: inherit;
+                       line-height: inherit;
+                       text-decoration: underline;
+               }
+       }
 }
```

### Reproducibility

Consistent

cc @vishnugopal @jaswrks

**Comment by jaswrks** [comment]
Thank you for reporting. @southp Can Decepticons assist with this please?
