### ISSUE TITLE
No option to add the Cookies and Consent Banner on Universal Themes without Widget Areas

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#58819]
### Quick summary

While having a Universal Theme without Widgets active (which I think is any of the themes we have recently added starting with Geologist) the users won't have the option to add the Cookies and Consent Banner widget. Even when having FSE active.

### Steps to reproduce

1. Activate any of the recent themes starting with Geologist
2. Try adding the Cookies and Consent Banner
3. Notice no widget areas are available and that in the Site Editor when trying to add a block to the footer the Cookies & Consent Banner cannot be found

![Screen Shot on 2021-12-03 at 12:24:17](https://user-images.githubusercontent.com/3696121/144645868-e0436ee7-fa44-4e5e-9352-5ae871faf3b6.png)

### What you expected to happen

To be able to add the Cookies and Consent Banner.

### What actually happened

There was no option. And when trying to copy the Cookies and Consent Banner widget block from another website got this message:

>Your site doesn’t include support for the “core/legacy-widget” block. You can leave this block intact or remove it entirely.

### Context

User report: 29598980-hc
Possibly related: 146-gh-Automattic/dotcom-manage
Slack convo: p1638547654041400-slack-C029FM1EH

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Any of the recent themes starting with Geologist

### Browser, operating system and other notes

Chrome Version 96.0.4664.55 (Official Build) (x86_64)
macOS Monterey 12.0.1 (21A559)

### Reproducibility

Consistent

### Severity

All

**Comment by Robertght** [comment]
cc @jeffikus or @Automattic/flow-patrol-create

**Comment by hngdny** [comment]
This affected two Simple site users:

4601862-zen (workaround: theme change)
4605320-zen

**Comment by arcangelini** [comment]
By default, the Legacy Widget block is not enabled in all editors, only `widgets.php` and `customizer.php`. In order to get this block to appear it would require manually applying all the `wp-widgets` scripts/styles and registering the block. [The process is outlined in the support doc](https://developer.wordpress.org/block-editor/how-to-guides/widgets/legacy-widget-block/#using-the-legacy-widget-block-in-other-block-editors-advanced). I am not sure how FSE or Universal themes are planning on working with widgets so it may be best to get some details from @jeffikus or @scruffian 

If we for sure want to keep the Legacy Widget block included I would be happy to work on implementing this, I would just need a little guidance on where it would make the most sense to add.

**Comment by scruffian** [comment]
There is no plan to add widgets to universal themes.

**Comment by arcangelini** [comment]
It may be best to work on a replacement block to allow this feature to be used moving forward. @Robertght I would suggest maybe creating a feature request for a cookie and consent block. It may also be helpful to ask the FSE team to see if they are aware that the Legacy Widget block isn't enabled in the editor. Maybe @vindl has some insight?

**Comment by scruffian** [comment]
I agree a new block would be the way to go here.

**Comment by vindl** [comment]
> It may also be helpful to ask the FSE team to see if they are aware that the Legacy Widget block isn't enabled in the editor. Maybe @vindl has some insight?

Thanks for reporting this, we were not aware of this gap. I don't have any additional insights to add, besides what was already pointed out above. We likely need a new block to handle this and it might be worthwhile to start a feature request for it in the Gutenberg repo, so I imagine this is something that self-hosted sites might need too.

**Comment by inaikem** [comment]
@vindl, thank you! 👋  IIRC the Cookie & Consents Banner is a Jetpack widget, so would probably be best created there vs in Gutenberg directly. Cc @jeherve for a quick confidence check.

**Comment by jeherve** [comment]
This is a more general question about the future of some of our Legacy widgets in this new FSE world. This is discussed in pdf5j4-7f-p2 (as well as panfyZ-8L-p2 and pdf5j4-4C-p2 )

The future of the Cookie & Consents Banner is something that is tracked in #52100 at the moment. Maybe we should close this issue in favor of the other one?

*** 

Other related issue and discussion: #56292

**Comment by ivan-ottinger** [comment]
> Maybe we should close this issue in favor of the other one?

I agree that we could close this issue and leave #52100 as the main one to discuss the future of the Cookie & Consents Banner widget.

**Comment by dolgelukkig** [comment]
4700339-zd
Theme AltoFocus
Although there is a Footer widget area, anything added to that widget area will not show up on the site

**Comment by scruffian** [comment]
Closing in favour of #52100
