### ISSUE TITLE
Can't comment with Social Media accounts on Atomic sites.

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#58839]
### Steps to reproduce

1. Open the Discussion settings of the Atomic site:
2. In the `Comments` section enable the `Let visitors use a WordPress.com, Twitter, Facebook, or Google account to comment.` option.
3. Click the `Save settings` button.
4. Open a post to comment.

### What you expected to happen

The comment form should show the options to comment with Google, Facebook and Twitter accounts as well.

### What actually happened

Only the WordPress.com login option is shown in the comment box.

### Context

33028383-hc

p9F6qB-7Ma/#comment-44015

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

**Comment by happychait** [comment]
Seems to be a Jetpack issue as a couple of us found out by testing further in p9F6qB-7Ma/#comment-44018

**Comment by JoshuaGoode** [comment]
This appears to be theme-specific or another conflict as I cannot reproduce on my test sites.  I can try testing more later.

**Comment by happychait** [comment]
Closing this as non-issue.

Chrome was blocking cookies. Enabling `Allow cookies` brought back the social options on the comments form in Chrome. 

Works in Firefox too.
