### ISSUE TITLE
JavaScript when displayed on a Posts Page

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#58837]
### Quick summary

JavaScript code does not seem to work when displayed on a site's Posts Page.

Here is a picture of my test site's Posts Page:

<img width="1264" alt="Screen Shot 2021-12-04 at 2 15 38 PM" src="https://user-images.githubusercontent.com/12906034/144721855-230dd6ce-df36-49ef-9c21-04964c549a66.png">

Here is a picture showing the individual post:

<img width="1267" alt="Screen Shot 2021-12-04 at 2 16 21 PM" src="https://user-images.githubusercontent.com/12906034/144721876-3758a61f-7493-499d-b2fa-db31187865ca.png">

The sample code I used can be found here: 33050911-hc

The custom HTML displays fine on the Posts Page, but the JS does not.

### Steps to reproduce

1. Add JavaScript to a Post on an Atomic site.
2. Set the site's homepage to display latest posts.
3. View the site's homepage.
4. View the individual post.

### What you expected to happen

JavaScript should display correctly on the Posts Page.

### What actually happened

JavaScript does not display.

### Context

This was discovered as I was trying to make customer JS work in 33050911-hc

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

There is a partial workaround for this issue. If the user is able to use JS on a Page instead of a Post, then they can avoid the issue.

Alternatively, the user could create a static page with a Blog Posts Block to set as their blog page.

However, if the user wants JS to appear on a Post and is using the automatically generated Posts Page, there does not appear to be a workaround.

**Comment by Robertght** [comment]
@masperber Custom code is allowed on Atomic sites, however, the current code is quite custom. 

For further troubleshooting, the user will need the assistance of a developer, in this case, however, they can also consider using a plugin as a solution.

Ref: https://www.wpbeginner.com/wp-tutorials/how-to-easily-add-javascript-in-wordpress-pages-or-posts/
