### ISSUE TITLE
Unable to register domain via "Best Alternative" at https://wordpress.com/domains/get/com

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#58836]
### Quick summary

At the moment doesn't seem possible to register a domain by selecting "Best Alternative" via https://wordpress.com/domains/get/com . This was reported via 4566906-zen and we were able to reproduce it.

The console shows the following:

```
This step (domain-only) provides an unspecified dependency [siteUrl]. Make sure to specify it in /signup/config/steps-pure.js, using the providesDependencies property.
    at d (27658.3c9405e2dee04f1cef2e.min.js:1)
    at _ (27658.3c9405e2dee04f1cef2e.min.js:1)
    at Object.r.<computed> [as submitSignupStep] (77140.0e26df14a32cebe1a41d.min.js:1)
    at new oe (async-load-signup-steps-domains.f069ff1e57a47eedc94f.min.js:1)
    at _s (70520.2fe237417a4e92059f39.min.js:2)
    at Wa (70520.2fe237417a4e92059f39.min.js:2)
    at Gi (70520.2fe237417a4e92059f39.min.js:2)
    at Al (70520.2fe237417a4e92059f39.min.js:2)
    at Ol (70520.2fe237417a4e92059f39.min.js:2)
    at Cl (70520.2fe237417a4e92059f39.min.js:2)
```

### Steps to reproduce

1 - Go to https://wordpress.com/domains/get/com
2 - Enter the domain testnewtest.com. (Checking availability sometimes enters on a loop)
3 - Select the `Best Alternative`, and you will only see a blue screen

### What you expected to happen

Be able to register a domain

### What actually happened

A blue screen ( the WordPress.com screen background ) appears, but nothing else loads.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

**Comment by Robertght** [comment]
@Automattic/pod-domains is this something that can be looked into by your team?

**Comment by rafaelgallani** [comment]
I managed to reproduce it locally - it was apparently introduced by #54641, after adding `siteUrl` as one of the `providedDependencies` items. I'll create a PR to fix it.

**Comment by rafaelgallani** [comment]
The PR has just been merged. 
I retested it following the described steps and it looks like it has been fixed 😸 
@Robertght @iamgabrielma could you take a final look at it before closing it?

**Comment by delputnam** [comment]
I can confirm that this fixes the issue.  I'll go ahead and close this one, but please feel free to re-open if you see anything else wrong.
