### ISSUE TITLE
Customizer menu editor hangs on load

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#58844]
### Quick summary

When user selects Primary menu in the Customizer →  Menus, entire Customizer hangs, with no further interaction possible on the page, "Page Unresponsive" error message. Error duplicates this reliably, page reload required to get out of the hang. Other menus can be edited in the Customizer without a problem, and Primary menu can be edited from Appearance → Menus.

### Steps to reproduce

1. Start at https://wordpress.com/home/serevitaliser.fr
2. Click on Appearance → Customize.
3. Click on Menus.
4. Click on Primary.
5. See error.

### What you expected to happen

Primary menu should open in Customizer sidebar.

### What actually happened

Entire Customizer hangs, with "Page Unresponsive" error message and no further interaction possible on the page. Manual reload required to get out of hang.

### Context

Customer report

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Unknown. Site uses Balasana (Varia child).

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Edit menus under Appearance → Menus instead of in Customizer.

**Comment by Robertght** [comment]
Hey @the-misha ! 

Thank you for reporting this!
I haven't seen other similar cases, however, could you share with us the following:

- Was a conflict test run in the process? 
- Were you able to replicate this on a test website?
- If this doesn't help, could you include the interaction ID?

**Comment by the-misha** [comment]
Hi, @Robertght! I did run conflict testing, and wasn't able to replicate the issue on a test site. However, the issue appears to have fixed itself in the intervening 24 hours. :)
