### ISSUE TITLE
FSE Beta: Add Seedlet (Blocks) and Mayland (Blocks) themes

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#58870]
### What

Add Seedlet (Blocks) and Mayland (Blocks) and themes as FSE Beta design choices. These are related to the original Seedlet and Mayland themes, but use Blockbase as a parent theme so they are "universal" and compatible with the Site editor in the FSE Beta.

### Why

Continue to increase the number of design choices for the FSE Beta.

### How

- Network activate themes (requires discussion and planning, e.g. do we deprecate the previous Seedlet and Mayland themes first?)
- Add to the FSE Beta `/new` flow design picker

**Comment by creativecoder** [comment]
Related discussion: pNEWy-exw-p2

**Comment by jeyip** [comment]
Documentation about the process of Network Activating themes: PNEWy-e5f-p2

**Comment by creativecoder** [comment]
See pNEWy-exw-p2#comment-54040

We're going to forego launching these themes and use them as the base for similar replacements, instead.

Closing this issue; I'll open a separate one when the new themes are ready.
