### ISSUE TITLE
Refactor the styles of Design Picker in Hero Flow into the package as we want to make it consistent in our site

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58879]
## Refactor Design Picker Styles

The following description was taken from https://github.com/Automattic/wp-calypso/pull/58622#pullrequestreview-823479835

I noticed in Ollie's mockups he's generally using two columns of thumbnails, and the width of the category sidebar is wider, like we use in /start. Since we're unifying the styles, this could be a good time to roll the style overrides we do in client/signup/steps/design-picker/style.scss into the base @automattic/design-picker package. So anyone using the picker would get the 2-column of thumbnails by default. I guess we don't need to do this all in this one PR, but it seems like the idea here is to remove some of our unnecessary variations in signup, so pushing our Hero Flow style changes back into the base package could be good.

When we do this we should also use the highResThumbnails prop for <DesignPicker> since the thumbnails will be larger and we don't want them to be blurry.

## Task/PR List
- [x] https://github.com/Automattic/wp-calypso/pull/59750

**Comment by autumnfjeld** [comment]
@arthur791004 @p-jackson I copied details from Phil's comment into the issue description. Will let you guys update it if needed.    I think this isn't addressing bugs or user facing issues, so it is probably lower priority than feature work.  But of course please let me know if you have different opinions. :)

**Comment by arthur791004** [comment]
Close it as https://github.com/Automattic/wp-calypso/pull/59750 is shipped!
