### ISSUE TITLE
why is socket.io a devDependency?

### ISSUE THREAD

**Issue by tjwebb** [Automattic/wp-calypso#589]
https://github.com/Automattic/wp-calypso/blob/master/package.json#L127

It seems unlikely to me that this is correct

**Comment by Tug** [comment]
Socket.io is not used on WordPress.com in production. It is used only in development for hot reloading of our modules bundled with Webpack.
If you are interested, I believe our integration is based on https://github.com/webpack/webpack-dev-server

**Comment by nb** [comment]
We’re not using the server for the bundling in development, but the [middleware(]https://github.com/webpack/webpack-dev-middleware).

As for `socket.io`, @Tug is right, it’s used in the [hot reloading parts of the dev environment](https://github.com/Automattic/wp-calypso/blob/bac373ae91f2d7a489eee9b53ad3da9c7c1194fa/server/bundler/hot-reloader.js#L6).
