### ISSUE TITLE
FSE Beta: Move/rename the Site editor option menu item

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#58911]
### What

Since the Site Editor wp-admin menu item was renamed to "Editor" and moved to the Appearance section, we have this situation

<img width="180" alt="Screen Shot 2021-12-06 at 14 44 07" src="https://user-images.githubusercontent.com/1699996/145072010-ec36d848-b46f-42fc-9b66-35eece52b3f2.png">

Note that the "Site Editor (beta)" item shows up only for proxied users on Simple sites, but for all users on Atomic sites.

Let's move and/or rename the "Site Editor (beta)" menu item + option screen.

### Why

To reduce confusion.

### How

- Rename to Full Site Editing (beta)
- Move to Settings section (rather than Appearance)

**Comment by creativecoder** [comment]
Pinging @Automattic/cylon for ideas.

Maybe renaming this to something like "Full Site Editing (beta)"? What do you think?

**Comment by creativecoder** [comment]
Maybe also moving the Site Editor (beta) screen with the option to the Settings menu? What do you think, @mattwiebe ?

**Comment by Addison-Stavlo** [comment]
> Maybe renaming this to something like "Full Site Editing (beta)"? What do you think?
> Maybe also moving to the Settings menu?

I think these both make sense and would be an improvement.

**Comment by mattwiebe** [comment]
plus one to both 👍

**Comment by creativecoder** [comment]
Thanks for the input! I've updated the issue description and moved this into our backlog.
