### ISSUE TITLE
Jetpack Connect: users end flow on 'My Plan' page

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#5892]
If a user selects the 'Free' Plan they should immediately land on the 'My Plan' page and see links to:

* Enable plugin auto-updates
* Browse Stats
* Try out the new editor
* Download WordPress.com apps (https://apps.wordpress.com/)
* Return to wp-admin
* Any questions? (link to jetpack.com/support ? or wordpress.com/me/help ?)

Premium Plan:

* VaultPress Dashboard
* Akismet Dashboard
* Enable plugin auto-updates
* Browse Stats
* Try out the new editor
* Download WordPress.com apps (https://apps.wordpress.com/)
* Return to wp-admin
* Any questions? (link to jetpack.com/support ? or wordpress.com/me/help ?)

Professional Plan:

* VaultPress Dashboard
* Akismet Dashboard
* Polldaddy Dashboard
* In the future we need a way to let these users add two more sites to their account
* Enable plugin auto-updates
* Browse Stats
* Try out the new editor
* Download WordPress.com apps (https://apps.wordpress.com/)
* Return to wp-admin
* Any questions? (link to jetpack.com/support ? or wordpress.com/me/help ?)

cc @richardmuscat @ryelle @johnHackworth

**Comment by richardmuscat** [comment]
This looks really good!

**Comment by ryelle** [comment]
This ends up being an awful lot of cards on one page when they're all listed out: https://cloudup.com/cCiESWibXWm (with some lorem ipsum just to get a feel of how it would look - we would need 2ish sentences about each topic written up)

Maybe the "calypso features" could be merged into 1 card? I mean these:

- Enable plugin auto-updates
- Browse Stats
- Try out the new editor
- Download WordPress.com apps (https://apps.wordpress.com/)

Then even the longest, Professional, would only have 6 cards.

**Comment by rickybanister** [comment]
That sounds smart, especially as Guided Tours roll out, we don't need to do as much intra-calypso hand holding.

**Comment by ryelle** [comment]
I've started a PR for this with placeholder content in #6295
