### ISSUE TITLE
Plugins: Installs currently throw errors in Marketplace

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#58923]
## Workaround

If the site is already Atomic, users can visit the WordPress core plugins page at `/wp-admin/plugin-install.php` to search for and install plugins.

---

### Quick summary

Customers cannot install plugins right now from the Plugins page/marketplace view.

### Steps to reproduce

1. Navigate to Plugins > Add New
2. Search for or click any plugin
3. Click on Install and Activate

### What you expected to happen

The plugin to install and activate

### What actually happened

An error occurred

 "This URL should not be accessed directly. Please click the Install button on the plugin page."

<img width="736" alt="Screen Shot 2021-12-07 at 3 02 41 PM" src="https://user-images.githubusercontent.com/31680407/145098096-62ed783b-fa00-4951-860b-1dd148769baf.png">

### Context

Two customer reports in  33056124-hc and then in 32571118-hc 
reproduced by HEs

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

The customer can navigate to WordPress.org/plugins, find and download the zip file, then upload it, to get it on the site

**Comment by sstabrizi** [comment]
Another report in 32066768-hc

**Comment by Robertght** [comment]
I can confirm this is an issue. cc @cpapazoglou

**Comment by ClassicRKR27** [comment]
Have two reports: 32860896-hc 4577410-zd-woothemes

**Comment by desnum** [comment]
Another case in 32571118-hc

**Comment by CodeAllNightNDay** [comment]
Another case here 33101764-hc

**Comment by JoshuaGoode** [comment]
#### Updated Workaround

If the site is already Atomic, users can visit the WordPress core plugins page at  `/wp-admin/plugin-install.php` to search for and install plugins.

**Comment by sstabrizi** [comment]
Another report here 33101632-hc

**Comment by ghost** [comment]
Another report here 4577346-zd-woothemes
Asked user to use workaround of accessing through ```/wp-admin/plugin-install.php```

**Comment by kriskorn** [comment]
Fixed via [Dispatch action to recognize plugin click on installation flow. #58926](https://github.com/Automattic/wp-calypso/pull/58926). 
Closing the issue.

**Comment by ClassicRKR27** [comment]
Let me know if I need to create a new GH issue for this, but I have another report of this happening here: 30905638-hc

**Comment by ClassicRKR27** [comment]
I've got another instance here: 18816813-hc

Seems to be happening with the Elementor Pro plugin exclusively so far; not sure if it is affecting other plugin uploads.

**Comment by kathleenjross** [comment]
User had something similar in 31061287-hc when trying to install Popup Builder. The `/wp-admin/plugin-install.php` workaround worked.

**Comment by dcoleonline** [comment]
Another in 33908238-hc

**Comment by dcoleonline** [comment]
Also 4740572-zen

**Comment by donalirl** [comment]
#33977242-hc

**Comment by wprhunt** [comment]
4740989-zen

**Comment by wprhunt** [comment]
4741065-zen
Elementor Pro mentioned as the last plugin before the issue

**Comment by Greatdane** [comment]
Another; 33980753-hc
a WooCommerce plugin they purchased through us.

**Comment by essleeung** [comment]
Another here: 33980737-hc
Elementor pro & Category and Taxonomy Image

**Comment by Greatdane** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/60748

**Comment by sharonlaker19** [comment]
I got two more today at 34513530-hc and 34516200-hc, both saying `Installation in progress. Just a minute! Please wait until the installation is finished, then try again.` 
The suggested workaround to access the plugins page directly at `/wp-admin/plugin-install.php` worked. 
Please let me know if I need to open a new bug report. Thanks!

**Comment by gcsecsey** [comment]
We've looked into this issue with @epeicher. It seems that this issue only surfaces for a few seconds after the Automated transfer is completed.

On the UI, we use this logic to show the eligibility warnings before proceeding with the installation:
https://github.com/Automattic/wp-calypso/blob/2d1c79bd9670336227288f3c57a9c2cf3e775ba4/client/my-sites/plugins/plugin-details.jsx#L110-L111

**If the site is a simple site**
 - Site is not a Jetpack site yet
 - `eligibilityHolds` contains the `NO_BUSINESS_PLAN` hold
so the standard eligibility warnings should be shown:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/11555574/157242484-4af8db49-de4f-4559-bde6-8a7512ab40a9.png">

**If the site is an Atomic site**
- site is a Jetpack site
- `eligibilityHolds` contains the `TRANSFER_ALREADY_EXISTS` hold
so there should be no eligibility warnings shown.

However, after the automated transfer is done, there's a short period of time, while jetpack sync is running on the site, when the site isn't a Jetpack site yet. This can be seen from the audit trail:
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/11555574/157242080-7f3322ba-fe48-4627-a953-4303b6499f61.png">

**Comment by epeicher** [comment]
After some investigation we have found that the issue can be **reproduced following these steps**:

- Navigate or create a Simple site. Make sure it is not a Jetpack site.
- Purchase a paid plugin and accept to upgrade the plan to a Business site and _quickly_ 
- Purchase another plugin.
  ⚠️ Please note that the time between upgrading the plan and purchasing a plugin is crucial here as, during that short period, the site is considered non-Jetpack site.

Once the user enters into the Plugin details screen following the steps above, the user can try multiple times and the ` Installation in progress.` message will always appear as the screen has an incorrect state that is not changed until further actions are taken. The actions to change the `state` could be either refreshing the page or trying again in a new chrome tab.
