### ISSUE TITLE
FSE Beta: Recommended and Full Site Editing tabs are duplicated in the Themes showcase

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#58930]
### What

**Current**

<img width="400" alt="Screen Shot 2021-12-06 at 14 43 28" src="https://user-images.githubusercontent.com/1699996/145072982-eed96c77-2a63-4033-8f2a-ec5b9028eac1.png">

The "Full Site Editing (beta)" and "Recommended" tabs in the Theme showcase currently show the same things for FSE Beta sites. This seems unnecessary.

How about removing the extra tab and renaming "Recommended" so there's just one tab? This would be only for Sites that are FSE eligible (in the FSE Beta).

**Simplified**

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1699996/145120757-3d21b700-eef2-407b-8f14-1fcc65d3a8a8.png">

### Why

To simplify the Themes showcase, and make it clear the Recommended themes are all FSE compatible themes.

**Comment by creativecoder** [comment]
Pinging @Automattic/cylon for any feedback or additional ideas.

**Comment by Addison-Stavlo** [comment]
I thought that recommended section was supposed to show either:
A ) Normal recommended themes + FSE beta themes - IF the site is running on a non-FSE theme.
B ) Just FSE themes - IF the site is running on an FSE theme.

But it looks like it is just showing B in all cases, which as you point out is a bit redundant with the FSE tab. 🤔

**Comment by zaguiini** [comment]
I'd prefer keeping `Recommended` and removing the `Full Site Editing` tab if running an FSE theme.

We might decide to show more than block-based themes in that tab so naming back-and-forth would hurt UX.

**Comment by Addison-Stavlo** [comment]
Why not just have `Recommended` always show the same recommended themes, and the "Full Site Editing" tab only FSE. That way it would not be redundant, and the recommendations would always be consistent.

**Comment by jeyip** [comment]
I vaguely remember working on something related a few months ago when I was making modifications to the theme showcase beta badges. In fact, I'm trying to find discussions related to this but am having some trouble. I'll update with comments if I uncover any links

> A ) Normal recommended themes + FSE beta themes - IF the site is running on a non-FSE theme.
> B ) Just FSE themes - IF the site is running on an FSE theme.

If I recall correctly, "A" was the ideal state.

If normal recommended themes + FSE beta themes in `Recommended` is something that isn't too critical to support, I agree with Addie in this case. Keeping both tabs and having `Recommended` continue to display the same recommended themes would feel like the most consistent UX for our users.

**Comment by creativecoder** [comment]
I think the end goal is for all "Recommended" themes to support FSE features, be it universal or block-only. Once we get past FSE being in beta, all new sites will use these themes, and we'll want to encourage existing sites to adopt them as well, to benefit from FSE.

So if that's the end goal, I think FSE Beta sites should reflect that now (all Recommended themes support FSE), since a primary goal of the Beta is testing and feedback for the way things will be when FSE is available for all sites.

**Comment by Addison-Stavlo** [comment]
> So if that's the end goal, I think FSE Beta sites should reflect that now (all Recommended themes support FSE), since a primary goal of the Beta is testing and feedback for the way things will be when FSE is available for all sites.

Hrm, that is a good point! My counter argument is that recommended themes are the themes WordPress.com knows give users the best possible experience when building their site. Whether a user is on the beta or not, this should still be the purpose of the recommended tab. Therefore, we shouldn't show only FSE themes in the recommended tab for beta users until we are confident that they present a better experience than the longer tested non-FSE themes that would normally show up there. Until we can confidently say that, I think the "FSE beta" tab can allow us to split those concerns quite well.

**Comment by creativecoder** [comment]
I'm thinking we should go ahead with this now that we're rapidly rolling out FSE for new sites: https://github.com/Automattic/wp-calypso/pull/60642
