### ISSUE TITLE
Improve messaging for plugin upload failures that are due to Jetpack Scan

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#58942]
### Quick summary

For plugin uploads that fail due to Jetpack Scan's vulnerabilities check, we could improve the messaging on the Calypso notification. At this time, it says "Upload problem: Invalid plugin"

### Steps to reproduce

- Get a plugin file that fails Jetpack Scan's checks. (related conversation here: p1638946968328900-slack-C029JEQRVRT)
- Upload at https://wordpress.com/plugins/upload

### What you expected to happen

Messaging could be improved to actually describe what happened.

### What actually happened

Message reads "Upload problem: Invalid plugin" at the moment: 

![image](https://user-images.githubusercontent.com/18581859/145188316-4f09f13c-19b2-4e25-8e67-f83ce221472d.png)

### Context

Slack chat: p1638946968328900-slack-C029JEQRVRT

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No.

### Browser, operating system and other notes

All devices.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by Greatdane** [comment]
@cpapazoglou does this need moving to the Jetpack Repo or is it OK here?

**Comment by cpapazoglou** [comment]
It should be OK here since we need to change `class.jetpack-client.php` that resides in wpcom and not in Jetpack. Thanks for checking.

**Comment by cpapazoglou** [comment]
We can add a key returned by the error and provide a more meaningful message to the user, suggesting that they can use WP Admin if they insist uploading it.

**Comment by rw-ye** [comment]
Will need to re-open ticket with user: 4578518-zd-woothemes after a change is deployed.
