### ISSUE TITLE
Billing: remove "pending payments" code

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#58965]
From https://github.com/Automattic/wp-calypso/pull/46546#issuecomment-976710285, we can probably go ahead and remove any code from the "Pending Payments" feature, since it's been disabled for more than a year and we don't have any short-term plans to implement those payment methods.

**Comment by tyxla** [comment]
I accidentally got to work on this one as a side task, so I'll be filing a PR.

**Comment by tyxla** [comment]
Addressed in #59447.
