### ISSUE TITLE
Plugin conflict causing Fatal Error with Google Sitekit when the Site Editing beta is switched on

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#58971]
### Quick summary

If using the ETK plugin, Gutenberg plugin, then activating the new Full Site Editor beta, a critical error occurs related to Site Kit.

### Steps to reproduce

1. Install and Activate the Full Site Editor and Gutenberg plugin.
2. Activate a block-based theme, such as Zoologist.
3. Enable 'Site Editor' via Appearance > Site Editor (beta)
4. Install and Activate Site Kit by Google.

### What you expected to happen

That the Site Editor should be able to be used - even though Google Sitekit is installed

### What actually happened

A fatal error

```
08-Dec-2021 06:08:16 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Google\Site_Kit\Core\Admin\Screens::Google\Site_Kit\Core\Admin\{closure}() must be of the type array, null given, called in /wordpress/core/5.8.2/wp-includes/class-wp-hook.php on line 303 and defined in /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Admin/Screens.php:154
Stack trace:
#0 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(303): Google\Site_Kit\Core\Admin\Screens->Google\Site_Kit\Core\Admin\{closure}(NULL)
#1 /wordpress/core/5.8.2/wp-includes/plugin.php(189): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.8.2/wp-admin/includes/menu.php(279): apply_filters('menu_order', Array)
#3 /wordpress/core/5.8.2/wp-admin/menu.php(341): require_once('/wordpress/core...')
#4 /wordpress/core/5.8.2/wp-admin/admin.php(158): require('/wordpress/core...')
#5 /wordpress/core/5.8.2/wp-admin/index.php(10): require_once('/wordpress/core...')
#6 {main}
  thrown in /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Admin/Screens.php on line 154
```

### Context

Customer report

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by jordesign** [comment]
Suggestion from the relate Sitekit issue.
https://github.com/google/site-kit-wp/issues/4485


> with reference to fixing the problem for you specifically, check all of the plugins and theme you are using for usage of the menu_order filter. It is highly likely a callback hooked to menu_order isn't returning as expected

**Comment by Greatdane** [comment]
Also this comment;

> This happens because the anonymous function argument in `Screens.php` has an `array` type declaration applied to it. If an external theme or plugin author did the following, for example, a fatal error would occur in Site Kit because the passed string would violate the expected array type:
> 
> ```
> add_filter(
>     'menu_order',
>     function ( $menu_order ) {
>         return 'I am a string';
>     },
>     1
> );
> ```
> 
> If Site Kit was the only user of the `menu_order` filter, this problem could be avoided but the hook is available to code external to Site Kit. The solution is to not type hint the function argument in this context.

**Comment by Robertght** [comment]
another case in 4604832-zen

**Comment by KirkwallDay** [comment]
Another case at 32398606-hc

However, they did not have Google Site Kit installed, it was just Full Site Editing conflicting with Gutenberg.

**Comment by Greatdane** [comment]
Google replied with these questions; 

_Check all of the plugins and theme you are using for usage of the menu_order filter. It is highly likely a callback hooked to menu_order isn't returning as expected_

_Which other plugins do you have active on the site? Is there a chance one of them is using the filter incorrectly? We should report it there when we identify one._

Does Gutenburg use any of these?

**Comment by goblinartificer** [comment]
4717341-zen and 4717256-zen reports today

**Comment by retnonindya** [comment]
Another incident:
33585425-hc

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/60462 should fix this issue.
