### ISSUE TITLE
Maywood: Missing edit links on frontend when site is loaded in Mobile

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#58985]
### Quick summary

The edit links on pages and posts of the site is missing for Maywood theme when the site is Atomic despite having third-party cookies enabled.

### Steps to reproduce

1. On an Atomic site, activate the Maywood theme.
2. On a mobile device, login to the WordPress.com account and then visit a page or post on the site.
3. You will notice that the edit link is missing.

If you test the same on Simple site, the edit links are there.

### What you expected to happen

The edit link should be available on front end if the user is logged into WordPress.com.

### What actually happened

The edit links were missing.

### Context

4580673-zen

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Maywood

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by kerrynicl** [comment]
When using mobile APP Issue not specific to Maywood. Was able to reproduce on Varia, TwentyTwentyOne and Russell

**Comment by romitgithub** [comment]
I can't install the Atomic plugin on my local to test and fix this issue. How do I proceed?

@devNigel

**Comment by devNigel** [comment]
@romitgithub I am not sure about the development side or testing Atomic in local, perhaps check with Reactor ( reactorp2 ) ?  🤔

**Comment by cometgrrl** [comment]
This no longer reproduces. Please re-open if we have additional information or reports.
