### ISSUE TITLE
Marketplace: Allow paid plugins in lower tier than Business plan

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58998]
Marketplace plugins shouldn't require a plan upgrade since they do need a paid plugin subscription. Let's use a feature flag `marketplace-all-plans`.

- [ ] Remove all calypso requirements or references to buy a business plan (only for paid plugins)
- [ ] Remove the backend guard that doesn't allow users to buy a marketplace plugin if not on a biz / ecom plan (`shopping-cart.php`)

![CleanShot 2022-02-21 at 14 35 37@2x](https://user-images.githubusercontent.com/12430020/154956410-831408c8-70aa-46fb-babb-d2df2592f94c.png)

![CleanShot 2022-02-21 at 14 36 39@2x](https://user-images.githubusercontent.com/12430020/154956570-a643d8c4-4f67-41a8-a2a0-e0457c8c5d67.png)

https://github.com/Automattic/wp-calypso/blob/34d1247c460e14cc515b1e7283ee7bb09a984064/client/my-sites/plugins/plugin-details-CTA/index.jsx#L366-L386

**Comment by mreishus** [comment]
Limited atomic has modified these checks after this ticket was created:

### Front-end, calypso

`shouldUpgrade` and `upgradeAndInstall` are now true[ if the site does not have the `FEATURE_INSTALL_PLUGINS` feature](https://github.com/Automattic/wp-calypso/blob/8a5af3cb5e97fa1daf8a57c1624899205917e2f1/client/my-sites/plugins/plugin-details-CTA/index.jsx#L55-L58). If the feature is missing, it now [adds the pro plan](https://github.com/Automattic/wp-calypso/blob/8a5af3cb5e97fa1daf8a57c1624899205917e2f1/client/lib/plugins/utils.js#L341-L343) to your cart.

### Backend guard

We changed `validate_marketplace_plugin_product()` in `default-shopping-cart-validator.php` in D79044-code. To have a marketplace plugin in the cart, you must have a site that has the `ATOMIC` feature, or another product in the cart that provides the `ATOMIC` feature.

### Conclusion

As we add the `ATOMIC` and `FEATURE_INSTALL_PLUGINS` features to more plans, they will also be able to purchase marketplace addons. 
_(Trying this out in D82976-code)._

**Comment by mreishus** [comment]
@obenland and I also talked about splitting `INSTALL_PLUGINS` into two features: `INSTALL_PLUGINS` and `INSTALL_PURCHASED_PLUGINS`.

Adding the feature

- :heavy_check_mark: Backend: D82978-code
- :heavy_check_mark: Calypso: https://github.com/Automattic/wp-calypso/pull/64832



Making the feature work

- :heavy_check_mark: Calypso: #64910
- :heavy_check_mark: wpcomsh: 1003-gh-Automattic/wpcomsh
- :heavy_check_mark: 1004-gh-Automattic/wpcomsh ( Filter [all_plugins](https://github.com/Automattic/jetpack/blob/2447e267e40f2d133a5c15c2320b776e4c395ec8/projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php#L339) )
- :heavy_check_mark: #64940
-  :heavy_check_mark: #64942
- #65013

Adding the feature to a plan

- Calypso: #64908
- Backend: D82976-code

Conditionally adding the feature to a plan for testing

- :heavy_check_mark: D83198-code
- :heavy_check_mark: 1010-gh-Automattic/wpcomsh

Todo?

- :heavy_check_mark: https://github.com/Automattic/wp-calypso/issues/55917
- :heavy_check_mark: https://github.com/Automattic/wp-calypso/pull/64958
- :heavy_check_mark: Don't show Upgrades screen on lower-tier plan sites. 1005-gh-Automattic/wpcomsh
- ~~Comments: D83195-code~~
- ~~`/plugins/manage/<site>` can redirect you off [Link](https://github.com/Automattic/wp-calypso/blob/0e75034d5245e5944e3c02b2e3b426877f90c7d1/client/my-sites/plugins/main.jsx#L88-L90)~~

CFT pdtkmj-dL-p2

**Comment by obenland** [comment]
This is now in production.
