### ISSUE TITLE
Reader feed not updating with new posts

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#59020]
### Quick summary

User in 4569346-zen has a site that isn't showing the most recent posts in the Reader, or in Feed Lookup. Older posts (e.g. Nov. 2021 and earlier) are still visible.

Newer posts are only visible in the Reader when the feed URL is directly accessed. 

When creating a test site on the user's account, Feed Lookup shows `No items found for http://inserttesturlhere.wordpress.com.` despite having two fresh posts, and discarding feed history has no effect. 

During troubleshooting, a test site was created on another WordPress.com account and this issue did not present itself. 

Not sure if this is just limited to this particular user or if other users are effected. Creating this issue to track if other users are experiencing a similar anomaly. 

### Steps to reproduce

1. Login as an affected user
2. Publish a new test post
3. Observe that it cannot be found in the Reader other than directly visiting the feed URL
4. Observe that new posts do not show up in the Feed Lookup tool

### What you expected to happen

I expected new posts to show in the Reader under https://wordpress.com/read

### What actually happened

New posts can only be seen on https://wordpress.com/read/feeds/123456789

### Context

4569346-zen

### Simple, Atomic or both?

Simple

**Comment by Robertght** [comment]
This issue seems specific to this website. @bluefuton or @Automattic/flow-patrol-create do you have the bandwidth to look into this a little closer?

**Comment by cometgrrl** [comment]
> This issue seems specific to this website. @bluefuton or @Automattic/flow-patrol-create do you have the bandwidth to look into this a little closer?

It would be great if we could at least check and see if this is possibly affecting others.  If it is, the priority would be higher.

**Comment by bluefuton** [comment]
@metabreakr it sounds like this affects one specific website, so a post on +readersquad P2 with all the details is probably the best next step. There is also a Support FAQ there entitled "Posts missing or slow to appear?".

**Comment by metabreakr** [comment]
Posted to p5PDj3-4ZQ-p2
