### ISSUE TITLE
Stats: "no posts" message for site with posts

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#5902]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/insights/leif.me
#### What I expected

I expected the insights page to know that I'd published posts before. 
#### What happened instead

I got the "You haven't published any posts yet." message. 
#### Screenshot

![screen shot 2016-06-08 at 10 48 45 pm](https://cloud.githubusercontent.com/assets/23619/15910499/69b0882c-2dcb-11e6-95c1-7d2c86d05bcd.png)
#### Context / Source

Jetpack site, leif.me.

**Comment by catkit** [comment]
Another user reported this same issue using Chrome on Windows. I could reproduce it in Chrome 51.0.2704.103 (64-bit) on Ubuntu 14.04.
.

**Comment by timmyc** [comment]
I can not reproduce this issue, closing it out.
