### ISSUE TITLE
Plans: Plan purchase back button doesn't go to my-plan page

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#5903]
#### Steps to reproduce
1. You must purchase a plan through the NUX
2. On the thank you page, hit the "Back to my site" link
3. I see the /plans page

#### What I expected

I expected to see the "My Plan" page, which is actually kind of odd, because it replicates the "Thank you " page. I think these two things should be merged, and a thank you message added to the to of the my-plan page. That is probably a separate thing.

#### What happened instead

I saw the plans page, showing me the different plans, not the one I was on.

#### Browser / OS version

Chrome Mac latest

#### Screenshot / Video

This site, see the back link near the top:

<img width="818" alt="screen shot 2016-06-08 at 1 58 51 pm" src="https://cloud.githubusercontent.com/assets/1464705/15910931/28ae145a-2d82-11e6-9941-d70dc67db7c5.png">

**Comment by retrofox** [comment]
> I expected to see the "My Plan" page, which is actually kind of odd, because it replicates the "Thank you " page. I think these two things should be merged, and a thank you message added to the to of the my-plan page. That is probably a separate thing.

Hi @apeatling I've created #6523 which only changes the url. Still we'll have to work on get a way to merge both pages.
