### ISSUE TITLE
Make a integration test for the WordPress importer

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#59038]
- [x] Basic flow, content only (see `small-export.xml` and `large-export.xml`)
- [x] Remove async-job custom filter and add async flag to queue import
- [x] Mock `wp_remote_get` and similar net functions
- [x] Mock `wp-import` enabling attachments
- [x] Advanced flow, import everything
- [x] D76226-code
- [x] D76923-code

Optional
- [x] Compare `wordpress-importer` plugin with recent version
- [x] Align core test `wordpress-importer` plugin with `async-job` version (the one actually used)

**Comment by jeroenpf** [comment]
So far, I have been able to get an import running, but no assertions have been added yet. The attachments are also not yet working. A parameter to enable attachment imports needs to be set but I haven't been able to find out exactly how/where to set it. 

The WXR probably needs to be expanded a bit to allow for more test cases (e.g. tags, categories, non-image attachments,  different types of posts, and pages).

**Comment by vishnugopal** [comment]
@zaerl Would be nice to have a roadmap here in the [main description](https://github.com/Automattic/wp-calypso/issues/59038#issue-1076456133) that'll show our progress here.

**Comment by vishnugopal** [comment]
Discussion:
- The currently written test works except for attachments.
- There is an obselete WordPress importer plugin in the codebase. There is a lot of custom code in the plugin (code specific for WordPress.com with forking et. al). It's a bit hard to update this.
- Let's try to keep the plugin as is. 
- Let's try the flag on queue_import, and if it doesn't work, get the change on async-job reviewed from outside the team (Alex would be fine)
- The priority is to get WordPress import integration tested first, and then move on to the other importers.

**Comment by vishnugopal** [comment]
Discussion:
- We have one diff up with the content flow for WordPress mocked.
- Let's get the diff merged with the WordPress content flow.
- The other content importers are somewhat easier to do since we've done the WordPress content importer so we'll tackle this next.
- We'll try to get the WordPress migrator after that. This requires an Atomic destination site. 
- Not sure how to verify and assert on destination content as well for WordPress migrator.

**Comment by vishnugopal** [comment]
Discussion:
* Waiting for Francesco to update work here.

**Comment by vishnugopal** [comment]
Discussion:

* Planning to merge one diff for WordPress importer.
* Working on  Wix, mocking before the AWS call.
* wordpress-importer version differences can be reconciled.

**Comment by vishnugopal** [comment]
Discussion:
- 2 diffs here: D76226-code D76923-code
- Will be done soon!

**Comment by zaerl** [comment]
@vishnugopal the two diffs have been deployed, we can close.
