### ISSUE TITLE
Forms: Tweak Counted Textarea Footer Color

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#5904]
Per https://github.com/Automattic/wp-calypso/pull/5839#issuecomment-224405810, we should lighten up the background color of the `counted textarea` component.

It should match the search preview color shown here:
<img width="662" alt="screen shot 2016-06-08 at 2 07 05 pm" src="https://cloud.githubusercontent.com/assets/789137/15910949/4fdbc0d6-2d82-11e6-91b2-70608a390ad5.png">

**Comment by drw158** [comment]
Here is my suggestion:

![screen shot 2016-06-08 at 4 19 14 pm](https://cloud.githubusercontent.com/assets/618551/15911298/d8952482-2d94-11e6-9701-16e0add0c285.png)

Background: $gray-light
text color: $gray-dark
