### ISSUE TITLE
[Bug]: Stale content under /help/courses

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#59055]
### Quick summary

The content under `/help/courses` hasn't been updated in a few years, and one of the Youtube videos is no longer available.

### Steps to reproduce

1. Go to wordpress.com/help/courses
2. See the second video is shown as unavailable

### What you expected to happen

I expected to see a valid video.

### What actually happened

The second video shows as unavailable.

### Other notes

It may make sense to consider redirecting this page to a more current list of courses and/or webinars.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- WordPress.com/help/courses shows:

![Markup on 2023-07-18 at 15:37:55](https://github.com/Automattic/wp-calypso/assets/27249804/2cf5197b-9f0a-4fd1-83d7-190303f2e8cb)

The link to **Courses** under /help > "More Resources" directs to https://wordpress.com/learn/courses, so the above link should probably redirect there as well. 

📌 ACTIONS
- Assigned to @Automattic/vertex
