### ISSUE TITLE
FSE Beta: Site Editor entry point not apparent to users

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#59075]
Whether FSE site creation lands on "My Home" or in the Site Editor, it is not clear to users how to find an enter this editor (currently hidden under "Appearance" -> "Editor (beta)").

In our future efforts for FSE onboarding and new user guidance, we should find a way to educate users about the site editor and where they can access it.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1699996/145606694-3c75be4c-2de9-46d4-86dd-2fb60a287e81.png">

**How do I edit my site design?**

**Comment by vindl** [comment]
Given the scope of our beta, I think the existing users should have some expectations and knowledge about that already. If they are used to Customizer, they will most likely check out the `Appearance` sub-menu and stumble upon the `Editor (beta)` that way.

Even without that, anyone intending to change their website's design is likely to pick Appearance or Pages.

Some things we could do to make things less confusing:

- Add the `Edit Site` option to the top of the Quick Links section for FSE Beta sites.
- Remove the `Customize theme` entry from Quick links.
- Remove Customizer item from Appearance sub-menu.
