### ISSUE TITLE
Videos UI: Use the video meta duration instead of a user-given value.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59131]
With getting our video meta data from actual media videos in `wpcommedia`, we won't need a `duration` field for course management. We'll still need the `duration_completed` value, which should fall back to 90% of the video duration.

**Comment by andres-blanco** [comment]
This is implemented in D71461-code and the duration metadata is removed in D71617-code

**Comment by kwight** [comment]
Done. 👍
