### ISSUE TITLE
My Home: The Earn card needs to be aware of "seller experience" efforts.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59145]
Our highest-clicked card from the My Home primary carousel is the Earn card, which links to `/earn/:site`. None of its content is yet aware or taking advantage of seller experience work or Woo integration.

![earn](https://user-images.githubusercontent.com/349751/145885822-a9b35dde-8f3a-4f71-80be-107628834c70.png)

**Comment by kwight** [comment]
@ianstewart @SaxonF Any ideas on how to start spreading the word around Calypso once we've got the MVP launched? I wonder how good or bad an idea it would be to allow users to go straight to the intent flow with existing sites. 🤔

**Comment by sixhours** [comment]
This is super old! Closing since we'll likely have new ideas about how to better integrate with Woo/Woo Express/ecommerce plans/trials.
