### ISSUE TITLE
Feature Request: SyntaxHighlighter dark mode

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#59142]
### What

A dark mode for the `SyntaxHighlighter` block when the container (e.g. page or group) has a dark background.

### Why

Introducing a `SyntaxHighlighter` block on darker backgrounds causes unnecessary contrast between the page's background and the block's background.

![image](https://user-images.githubusercontent.com/26530524/145872656-3cf1d80a-04d1-4f36-8e1f-70a01c7a73b4.png)

**Comment by Robertght** [comment]
I encountered this and I'll close it in favor of https://github.com/Automattic/wp-calypso/issues/53317
