### ISSUE TITLE
Atomic: Premium themes don't work after activation

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59153]
You can activate a premium theme on an Atomic site, but trying to Customize it or edit its appearance will revert your site to the default theme:

https://user-images.githubusercontent.com/2124984/145892775-bf4ffaeb-8240-4638-be8b-327da202a792.mov

Customizing it shows this message and offers a clue:

<img width="801" alt="Screen Shot 2021-12-13 at 4 32 55 PM" src="https://user-images.githubusercontent.com/2124984/145892747-1938fdbe-2353-4bdd-9a78-25f05617655b.png">

I think we need to ensure that the parent theme (Blockbase) is also available/downloaded to the site when they try to activate one of its children.

**Comment by sixhours** [comment]
Experiments happening in 792-gh-Automattic/wpcomsh

**Comment by mreishus** [comment]
Some discussions of alternate methods here: pdgA0m-aH-p2
Our current proposed solution is to make a premium/blockbase-premium theme.

**Comment by sixhours** [comment]
`premium/blockbase-premium` theme created and working in D72750-code, we can close this! 🥳
