### ISSUE TITLE
Theme Showcase: Baxter's screenshot is broken on the individual theme sheet

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59152]
Skivers and Byrne are fine, but Baxter's theme screenshot is broken in both `/wp-admin/themes.php` and at `/theme/baxter/` in Calypso:
<img width="1438" alt="Screen Shot 2021-12-13 at 4 29 17 PM" src="https://user-images.githubusercontent.com/2124984/145891908-823ccc7e-c6fc-4c5a-97a7-eae33cba69ee.png">
<img width="377" alt="Screen Shot 2021-12-13 at 4 29 55 PM" src="https://user-images.githubusercontent.com/2124984/145891909-8ab2fa03-9985-4467-ba94-7d165ec7571c.png">

**Comment by sixhours** [comment]
I suspected this was an issue with a corrupt featured image, so I re-uploaded a new one and it works:

<img width="1668" alt="Screen Shot 2021-12-13 at 6 31 47 PM" src="https://user-images.githubusercontent.com/2124984/145905694-87368396-a7d0-4499-b4c0-be19beefa29d.png">

Obviously it's not the right dimensions. :) /cc @onuro @alaczek could you try re-uploading and re-setting the featured image for Baxter's showcase page?

**Comment by alaczek** [comment]
Fixed!
