### ISSUE TITLE
Question: Access to calypso.localhost:3000 just hangs, "waiting for calypso.localhost..."

### ISSUE THREAD

**Issue by jcarpe** [Automattic/wp-calypso#5915]
#### Steps to reproduce
1. run `make run`
2. navigate to `http://calypso.localhost:3000/` in browser (Chrome)

#### What I expected
The default page to load

#### What happened instead
Nothing loads, and the browser just continues to wait, displaying the message "waiting for calypso.localhost..." I have added `127.0.0.1 calypso.localhost` to my hosts file. I have tried this in NodeJS versions 5.11.1, 5.3.0, and 4.3.0, all with the same results. The strange thing is that it never errors or times out. It just hangs and waits.

#### Browser / OS version
Chrome - Version 51.0.2704.79 (64-bit)
OSX - Version 10.10.5

#### Context / Source
I couldn't find anyone else with this same issue, though I found a few folks that had configuration errors, but that always seemed to result in the "W" blank page. My gut tells me I also have a configuration problem, however I haven't touched anything in the project. I've tried a couple versions of Node though. I was prompted to try this because at one point I was prompted with this message during the run command:

```
wp-calypso requires node 5.11.1 and npm 3.8.6, found node v5.3.0 and npm 3.5.2
 Please switch using nvm or n! Or see https://nodejs.org for instructions.
```

But this seems contradictory to the install instructions that state Node version 4.3.0.

**Comment by jcarpe** [comment]
Additionally - I updated my NVM, from 0.30.0 to 0.31.1 as I've heard30.0 to be unreliable, but I get the same results as explained above.

**Comment by lamosty** [comment]
Hi jcarpe, you're cool for trying Calypso. :)

So, to recap:

- You've cloned Calypso and run `make run` with `node --version` of `5.11.1` and `npm --version` of `3.8.6`;
- You've put `127.0.0.1 calypso.localhost` in your hosts file and flushed DNS cache (`chrome://net-internals/#sockets` and click on 'Flush socket pools` and `chrome://net-internals/#dns` and click on `Clear host cache`)

Could you please try running `make distclean` and `make clean`? It will remove `node_modules` in Calypso folder and some build files. Alternatively, try deleting and cloning the Calypso repo again.

When you load `http://calypso.localhost:3000/` in your browser and open Dev Console (right click anywhere on page and "Inspect") and then go to the 'Console' tab, do you see any JS errors? If yes, please make a screenshot and attach it to this issue. Also, make a screenshot after running `make run`.

Thanks!

**Comment by jcarpe** [comment]
I'll give your suggestions a shot, though I do want you to be aware I am not seeing JS errors, but I wouldn't expect to see any. Nothing actually resolves to load.

**Comment by jcarpe** [comment]
A bit delayed here, but it seems I had an odd configuration specifically on port 3000. I'll go ahead and close. Thanks!
