### ISSUE TITLE
Editor: Drag and drop sometimes open file in tab

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#5918]
A Happiness Engineer reported that a user was having issues with uploading PDF files. Each time that the user drug a file onto the editor, the file was opened in the tab instead of uploading.

![editor_pdf_test](https://cloud.githubusercontent.com/assets/1126811/15918147/69a05364-2dc9-11e6-9f3d-71c2e48309bd.gif)
[Higher resolution video](https://cloudup.com/cEnISoayb7v)

I would expect that if the blue modal that says "Drop files to upload" is displayed, that we should upload the file.

**Comment by lancewillett** [comment]
I tested this today with Safari 10.0 on OS X 10.12 — and dragging in a PDF file worked exactly as expected.

![screen shot 2016-10-13 at 14 45 59](https://cloud.githubusercontent.com/assets/66797/19368212/e165b3a6-9153-11e6-9048-8e2d750bdc89.png)

![screen shot 2016-10-13 at 14 46 18](https://cloud.githubusercontent.com/assets/66797/19368214/e52e71d0-9153-11e6-8907-0643bc24a9a6.png)
