### ISSUE TITLE
Plugin Details: add missing fields to Marketplace plugins

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#59195]
While testing #59181 I've found that a number of fields are either missing or have different names/structure than in the WPcom API response. These cause some UI elements to not render on the page.

### Missing fields from WPcom

These fields are completely missing from the WPcom API response:

```diff
+ // WPorg API fields
- // WPcom API fields

+ "tags": {
+         "e-commerce": "e-commerce",
+         "sales": "sales",
+         "sell": "sell",
+         "store": "store",
+         "woo": "woo"
+ },
```

### Description field

Currently, there's a top-level description field in the response, which renders the description correctly. However, we could also move the `description` key  under the `sections` key and add other sections later.

```diff
- "description": "",
+ "sections": {
+        "changelog": "",
+        "description": "",
+        "faq": "",
+        "reviews": "",
+        "screenshots": "",
+    },
```

### Icon field

Currently, the response contains one icon URL for a plugin. This could be updated to use the same structure as the WPorg response, and to contain different resolutions.

```diff
- "icon": "https://wordpress.com/wp-content/lib/marketplace-images/woocommerce-subscriptions.png",
+ "icons": {
+         "1x": "https://ps.w.org/woocommerce/assets/icon-128x128.png?rev=2366418",
+         "2x": "https://ps.w.org/woocommerce/assets/icon-256x256.png?rev=2366418"
+ },
```

### Author field

Currently, only the author name is returned. If we want to link to the author page, we should either add the `author_url` value, or include a markup version of the author URL.

```diff
- "author": "Woocommerce",
- "author_name": "Woocommerce",
- "author_url": "",
+ "author": "<a href=\"https://woocommerce.com\">Automattic</a>",
+ "author_profile": "https://profiles.wordpress.org/woothemes",
```

If we don't want to directly link to the author's page, we can just use the author field to link to all plugins by that author in #57749

**Comment by gcsecsey** [comment]
We don't need the following fields in Marketplace products responses:

- `num_ratings` and `ratings`: The number of rating will always be low, we only need the final score
- `banners`: We will show a banner video instead
- `requires`, `requires_php`, and `tested`: Marketplace products are tested and working with WP.com
- `sections.installation`: The user won't need an install guide on WP.com

I've removed these fields from the issue description.

### Author field

We only need the slug to be able to search for all the plugins from the author on WP.com. We should check if that is already in the response.

### Icons field
We won't need an additional icon, but we can change the structure to make it the same as WP.org

**Comment by gavande1** [comment]
Diff created at D72248-code

**Comment by gavande1** [comment]
Deployed r237402-wpcom
