### ISSUE TITLE
Kerr: Theme screenshot.jpg is corrupt/0B file size

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59205]
Not sure if it didn't get uploaded or what:

<img width="746" alt="Screen Shot 2021-12-14 at 3 44 02 PM" src="https://user-images.githubusercontent.com/2124984/146076692-45976c11-ea93-4c90-8c93-507198084fdf.png">

I think it's also supposed to be `screenshot.png` but I do not know for sure. /cc'ing @onuro and @alaczek to take a look.

**Comment by alaczek** [comment]
Fixed!
