### ISSUE TITLE
2FA: Intermittent `Your session has expired, please go back to the login screen.` upon TOTP code entry.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#59211]
### Quick summary

Intermittently the MFA page displays an error banner stating that `Your session has expired, please go back to the login screen.` even when a valid TOTP code is entered.

This has been observed at a low-intermittent frequency in CI tests.

### Steps to reproduce

1. navigate to /log-in.
2. log in as a user with MFA set up with an authenticator app.
3. submit a valid TOTP code.

### What you expected to happen

TOTP code is accepted.
User is redirected to the home dashboard (new login) or the previous page they tried to access.

### What actually happened

`Your session has expired, please go back to the login screen.` error banner is shown.
Login attempt is rejected.

![image](https://user-images.githubusercontent.com/6549265/146090279-ae6c6ad1-d8e7-4e55-827c-10ba32a0b5ea.png)

https://user-images.githubusercontent.com/6549265/146090689-69a59556-75a6-42c0-adf7-687fc5b9f570.mp4

### Context

Automated end to end tests for P2.

### Other notes

Upon submission of the TOTP code, the following is logged in the developer console:

```Failed to load resource: the server responded with a status of 400 () wp-login.php?action=two-step-authentication-endpoint:0```

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Have to return to /log-in and retry the attempt.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 Message to Author
- Hey @worldomonation ! Not sure if this is still relevant. In terms of reproing - I log in with an MFA app daily (often to P2s first), and have never seen this. 
- It also looks like this could have been improved by this https://github.com/Automattic/wp-calypso/pull/59074
- What do you think about closing, or (if keeping) the need to try to repro?
     - Same questions for https://github.com/Automattic/wp-calypso/issues/59923

**Comment by worldomonation** [comment]
> In terms of reproing - I log in with an MFA app daily (often to P2s first), and have never seen this.

Right, it was only ever reproducible on automated tests, and I don't think I've seen this in about a year. 

I think we can close both this and the related issue.
