### ISSUE TITLE
Marketplace: don't allow Jetpack self hosted to buy plugins

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59232]
Currently paid plugins are installed as managed plugins through the activate function of a subscription. As a result they are not compatible with Jetpack self hosted sites. In https://github.com/Automattic/wp-calypso/pull/59191 we will make sure we don't display them but also let's make sure that users landing to paid plugin details page get a nice messaging like "Paid plugins are not yet available for Jetpack sites" instead of the CTA

![SS 2021-12-15 at 11 50 32](https://user-images.githubusercontent.com/12430020/146164247-e9b07e97-e6e9-4f72-b958-246d211a9499.png)

**Comment by cpapazoglou** [comment]
Let's disable the CTA with a messaging

cc @emmnyc85

**Comment by emmnyc85** [comment]
> Thanks for your interest. Paid plugins are not yet available for Jetpack sites. Stay tuned for updates.

Are we able to collect email addresses from customers who are interested and then upsell them once this is ready? If so we can adjust this to gather a list that we can later activate against. @cpapazoglou

**Comment by cpapazoglou** [comment]
Good idea @emmnyc85!

We can add a tracking event and collect UserIds which we can later use to target and show an announcement modal or extract and find their emails for email campaigns.

**Comment by emmnyc85** [comment]
Can we say the following and add a check box so we have permission?
> Thanks for your interest. Paid plugins are not yet available for Jetpack sites. Please check the box below if you'd like us to keep you updated.

When we do the design, we can play around with how best to communicate this message (i.e. 'Please check the box below if you'd like us to keep you updated.' There are variations to how we can present this')

**Comment by gavande1** [comment]
@SaxonF Can you provide designs for `please check the box below if you'd like us to keep you updated` as @emmnyc85 mentioned above?

**Comment by SaxonF** [comment]
A few options for us to consider.

Hide button and use a toggle to capture interest
![image](https://user-images.githubusercontent.com/1072756/148718243-de16488e-8c5b-48d5-80ea-7a906ef4c7e4.png)

Keep button but in a disabled state
![image](https://user-images.githubusercontent.com/1072756/148718256-f1cf0180-0e1f-4ca6-96b7-960af793e1f1.png)

Keep the button in an active state but show dialog on click. The only reason this is an option is that it may help to track more accurate purchase intent.
![image](https://user-images.githubusercontent.com/1072756/148718660-4dd75b9b-c929-45d3-adad-1730240feb88.png)

Personal opinion is option 2 as we could combine it with page views to gauge level of interest.

**Comment by emmnyc85** [comment]
Option 2 looks great. I like that it defaults to giving us the opportunity to reach out to customers again to drive marketplace awareness and sales. I think Option 1 is too hidden. Thanks @SaxonF
