### ISSUE TITLE
Themes: Add Videomaker to softlaunch list, add to store, and Network Activate it

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59245]
Holding off on this until after the new year, there are a handful of sites already using `pub/videomaker`, some of which are Atomic and therefore affected by #59153 and we don't want to break things pre-holidays. Slack convo: p1639671491203600/1639670049.196400-slack-C029FM1EH

- [x] Add, commit, and deploy `premium/videomaker` to the softlaunch list (D71695-code)
- [x] Add Videomaker to store tables (follow process outlined here: pdgA0m-90-p2)
- [x] Add Videomaker to store mappings (example diff here: D71526-code)
- [ ] Publish Theme Showcase page
- [ ] Network activate Videomaker (make sure it's the right version of the theme before you do - there may be a version in `/pub` and a version in `/premium`)

**Comment by mreishus** [comment]
* videomaker (but not videomaker-white) is in the softlaunch list
* @scruffian added videomaker and videomaker-white to the store tables, unsure if they're synced to production yet
* Mappings added here: D73577-code

**Comment by scruffian** [comment]
There are synced to production. I think they are ready to launch

**Comment by sixhours** [comment]
@scruffian took care of this and both Videomaker and Videomaker White are launched! 🥳
