### ISSUE TITLE
Importer Message: The address you entered is not valid. Please try again.

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#59247]

**Comment by autumnfjeld** [comment]
I tried the new importer flow using my own personal website autumnfjeld.com and got what I feel is an incorrect message, because the address is indeed valid.    (FYI: I didn't expect the import to work, because it is a custom built site, but I was curious what the flow would be like)

![image](https://user-images.githubusercontent.com/5665959/146232286-497ae33e-4dbc-452a-a7b2-56336cf2b3ab.png)

**Comment by autumnfjeld** [comment]
cc: @vishnugopal  :)

**Comment by vishnugopal** [comment]
Interestingly, entering `http://autumnfjeld.com/` works!

Added to sprint to double-check cause.

**Comment by vishnugopal** [comment]
This should work like it does in any browser. Try `https://` first, and then `http://`. This is probably a backend change.

**Comment by zaerl** [comment]
See D75705-code for a fix.
