### ISSUE TITLE
Videos UI: Mousing over the My Home card does not prefetch the `courses` API call.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59246]
Calypso has a mechanism that will prefetch an API call on mouse hover – this would be great for the "Start learning" link on the My Home card for the Blogging Quick Start video, which currently only makes the API call as the UI is opening after click.

<img width="761" alt="Screen Shot 2021-12-15 at 8 40 37 AM" src="https://user-images.githubusercontent.com/349751/146227610-28a98062-79e7-4eb9-96e9-4c1ce4d0fe4c.png">

**Comment by andres-blanco** [comment]
Probably not worthwhile the effort, the endpoint being hit is just ~2KB of data.

Discussion: p1648575337851629-slack-C7YPUHBB2
