### ISSUE TITLE
Zoologist sets logo to 64px width regardless of logo size used

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#59256]
### Quick summary

When a logo is added to a site using Zoologist (or a site using another theme has a logo added and then switches to Zoologist), the logo is resized to 64px wide, regardless of whether the user tries to change this or use a larger image.

If the logo is then replaced with a larger version, it appears as the expected size in the customizer but still shows at the smaller 64px wide size on the live site. 

Unclear to what extent this is expected behavior. 

### Steps to reproduce

1. Add a logo of any size (either large or within recommended parameters) to a simple site from the customizer.
2. If Zoologist is active, just view the live site.
3. If Zoologist is not active, switch to Zoologist and then view live site. 
4. Try replacing the logo with a larger version in the customizer - it should appear at that size when previewing in the customizer. 

### What you expected to happen

The logo would change size according to the image uploaded. 

### What actually happened

The logo does not change size, regardless of what size logo is uploaded. 

### Context

This was reported here: 4600840-zd-woothemes

The user switched to Zoologist on Nov 3 2021. They report this logo resizing was an unexpected change and they seem to have not seen this happen immediately upon switching.

Wayback Machine from 2 days after the change (11/5/21) shows the logo at a larger size: https://web.archive.org/web/20211105053108/https://ponderoku.com/

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I did not test other themes. 

### Browser, operating system and other notes

Chrome Version 96.0.4664.93
Mac OS 11.6

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by kosiew** [comment]
Hi @sajmes ,

Thanks for reporting this and the detailed steps.
This is similar to

https://github.com/Automattic/themes/issues/4852

Closing
