### ISSUE TITLE
Atomic Transfers Endpoint: Remove the GET check for the site being Atomic

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#59265]
After requesting a transfer to Atomic we would like to be able to poll the
status of the transfer. Currently the check will return 400 while the site
is not Atomic, so we can't get information about the current transfer. It
also means that when a site is reverted, we can't get information about
its latest transfer too.

D71691-code is the patch to remove that check.

**Comment by retrofox** [comment]
Closing because of D71691-code
