### ISSUE TITLE
FSE Beta: content loss after Undo

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#59260]
### Quick summary

The Post Content disappears from the site editor once you insert a block to the Document level and then Undo that operation.

### Steps to reproduce

1. Start at `https://wordpress.com/site-editor/{site-url}`
2. Insert any block to the top level of the template (Document).
3. Press Undo.
4. Notice that the whole Post Content section has disappeared.

### What you expected to happen

The inserted block should have been removed while the rest of the page remains intact.

### What actually happened

Post Content was deleted.

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by zaguiini** [comment]
For me, the contents of the `Header` disappeared. I guess it's something with template parts?

~Maybe https://github.com/WordPress/gutenberg/issues/36788 will fix this problem.~ It did not.

**Comment by zaguiini** [comment]
### Tests

- ❌  `v12.0.0`;
- ✅ `v12.3.0-rc.1` (`gutenberg-edge` sticker applied);
- ✅  `trunk`.

Fixed by https://github.com/WordPress/gutenberg/pull/37484.
