### ISSUE TITLE
Themes: Payton thumbnail is missing

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#59318]
### Details
Thumbnail for the Payton premium theme is not available, `400` response.

`https://wordpress.com/themes/<site>`

![image](https://user-images.githubusercontent.com/3801502/146425920-85762968-31dd-472a-bee9-02b7a695b5e5.png)

![image](https://user-images.githubusercontent.com/3801502/146426194-7ad8171c-a65f-4bfd-ba1b-cbc153b073a7.png)

**Comment by sixhours** [comment]
Fix for this in D71780-code

I think what's happening is folks working with these diffs need to use `arc patch-image` when they're applying the diff to their sandbox for deployment; `arc patch` won't bring over the image files.

**Comment by sixhours** [comment]
Fixed in D71780-code
