### ISSUE TITLE
Videos UI: A call to the courses API is being made when closing the UI.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59316]
An unnecessary call to the courses API is being made when closing the videos UI.

**Comment by sixhours** [comment]
I'm not seeing this behavior upon closing the videos UI; I do see a call to the block editor API but that's prevalent across My Home. Is it possible this was already fixed?

https://user-images.githubusercontent.com/2124984/160473835-fad6c714-f434-46a3-9ad5-d5a2f196036d.mov

**Comment by sixhours** [comment]
Seeing this behavior on older versions of Calypso (ie. https://github.com/Automattic/wp-calypso/pull/59252) so I think this was fixed in a previous commit; will see if I can trace it back.

**Comment by sixhours** [comment]
Looks like this was fixed as part of the switch to a custom hook in #59514, so I'm going to mark this as closed!
