### ISSUE TITLE
New sites with custom domains might not be properly logged in.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59315]
Reported by @ianstewart 

> I have a brand new site with a custom domain. But I don’t see the launch banner and my home page. I just see the coming soon page.

**Comment by kwight** [comment]
This may be related to domains or something: p1639671882216800-slack-C029SB8JT8S

Let's verify that when we are certainly logged in, we see the launch bar as expected.

**Comment by dpasque** [comment]
It sounds like this needs to be tested for reproducibility, and based on that might be able to be closed or have its priority lowered. I'm not entirely sure what the full workflow is from the comments above though, awaiting more input on that!

**Comment by kwight** [comment]
To replicate:

* Create a new free site.
* Upgrade to a Business plan.
* Install a plugin (to trigger an Atomic transfer, and a new site domain).
* Go directly to the front-end in a new tab – notice the "Coming soon" (which is a logged-out view of an unlaunched site).
* Go back to the site's Home, and click "WP Admin Dashboard" under the Quick Links.
* Load the front-end in a new tab, and see the proper front-end with a launch bar at the top.

This has something to do with cookies needing to be set for an "auto-login" experience, which doesn't happen if we go straight to site's front-end after the domain change. I don't think there's anything to be done here, closing.
