### ISSUE TITLE
Videos UI: Post content from the course management system is not translated.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59325]
With our new course management system, the text displayed in the UI comes from post content – this will need special consideration to be translated. We can look to the [Theme Showcase](https://theme.wordpress.com/wp-admin/edit.php?post_type=themedoc) as inspiration, since it's a similar situation.

**Comment by kwight** [comment]
We should also reach out to the i18n team to see how best to proceed.

**Comment by sixhours** [comment]
This is still an issue; for the Theme Showcase, we send some of the text input for translation via Linguine. As Kirk said, we'd want to work with i18n to figure out a workflow for translating text in the videos UI.

**Comment by andres-blanco** [comment]
This is already done. PCYsg-DgC-p2
