### ISSUE TITLE
Themes: Missing premium theme from feature list

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#59320]
### Details

Missing "premium themes" feature from Plans page feature list.

1. Open a free site, use the `themes/premium` feature flag.
2. Go to Appearance -> Themes
3. Click the Upsell banner:
![image](https://user-images.githubusercontent.com/3801502/146429559-71fa3e05-a41e-4c2a-8486-eb5195b44c82.png)

4. Plans page is loaded, but the premium theme feature is missing

![image](https://user-images.githubusercontent.com/3801502/146429785-3242ec5b-558a-46ed-9305-2d7bbb58857c.png)

**Comment by sixhours** [comment]
I think this will be fixed by #59006

**Comment by sixhours** [comment]
Confirmed this was fixed by #59006
