### ISSUE TITLE
Videos UI: The Blogging Quick Start slugs filter needs to have limited loading.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59322]
The filter that converts our course management video slugs to the original hard-coded slugs is located in `mu-plugins`, so that it can be effective for the library and the API. But it currently also gets loaded on all front-ends, so the file should bail loading if not in one of our needed contexts.

**Comment by sixhours** [comment]
We're not likely to work on this in the next year, so closing for now.
