### ISSUE TITLE
[Bug]: Paid plans don't take to the blogger onboarding flow

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#59351]
### Quick summary

As a new user signing up on wordpress.com/start, purchasing a Personal, Premium or Business plan takes to a "Thank you" page instead of the blogger onboarding flow.
 
A note on Premium plan purchase - selecting "No" on the upsell that appears right after a Premium plan purchase correctly takes to the blogger onboarding flow, however purchasing the upsell takes to a Thank You page.

**Personal plan purchase**

https://user-images.githubusercontent.com/1269602/146544592-34a97745-961e-4207-9363-3c4df0b3e2fd.mov

**Premium plan purchase, followed by upgrading to Business from the upsell**

https://user-images.githubusercontent.com/1269602/146544744-b1860a30-1ff9-4016-9264-1bd147a28ae3.mov

### Steps to reproduce

1. Go to wordpress.com/start and signup as a new user
2. Select the Personal plan 
3. Proceed to the checkout and complete purchase of the plan

### What you expected to happen

After purchase completes, I expected to be taken to the blogger onboarding flow

### What actually happened

I was taken to a "Thank you" page.

### Reproducibility

Consistent

**Comment by roo2** [comment]
looks related to https://github.com/Automattic/wp-calypso/issues/56303, I thought this was only affecting existing users

**Comment by niranjan-uma-shankar** [comment]
This seems to be a regression, since paid plan purchase as a new user appears to have worked earlier. e.g. p58i-bpK-p2#comment-52457 and p58i-bpK-p2#comment-52482.

**Comment by roo2** [comment]
I have a (draft) PR to fix this  https://github.com/Automattic/wp-calypso/pull/59493

**Comment by roo2** [comment]
fixed by #59499
