### ISSUE TITLE
Anchor FM banner at my home doesn't open in new tab

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#59367]
All the other "external" banners at my home open in a new tab — except AnchorFM. Let's have it open in a new tab as well.

There's some confusion introduced by new banners, but it's also common confusion to close the page when the brand has changed entirely (from WP.com to AnchorFM) and then they've accidentally closed their way back to WP.com as well.

<img width="1066" alt="Screenshot 2021-12-18 at 01 30 25" src="https://user-images.githubusercontent.com/87168/146619357-e7cc5c0a-f277-4d22-bfda-c44826fc61b2.png">

### Related

Walkthrough p58i-bIN-p2

**Comment by autumnfjeld** [comment]
Ganon will take this for a "new dev" issue.
