### ISSUE TITLE
[Bug]: Navigation: unread comments indicator broken hover state

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#59379]
### Quick summary

In the wp-admin version of unified navigation, unread comments bubble looks broken when hovering it:

<img width="168" alt="Screenshot 2021-12-18 at 23 54 23" src="https://user-images.githubusercontent.com/87168/146656445-3a5eef61-dcb8-4cda-9263-0034b00c87f9.png">

<img width="166" alt="image" src="https://user-images.githubusercontent.com/87168/146656452-2b8b0925-8593-4bce-b648-12aa5dcffc42.png">

### Steps to reproduce

Have unread comment, hover over navigation.

### What you expected to happen

Readable unread comments bubble.

### What actually happened

White text on white bubble.

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

![Ko3RTu.gif](https://github.com/Automattic/wp-calypso/assets/27249804/916ab6cf-eafc-4d73-af02-aa817b49a72f)

📌 ACTIONS
- Closed as not reproducible / no longer relevant
