### ISSUE TITLE
Media & Text: Image size isn't changing according to the selected option

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#59372]
### Quick summary

After adding the `Media & Text` block, we have an option to choose the image size, but that isn't working and doesn't make any difference to the image size users see on their pages.

### Steps to reproduce

1. Start by creating a new page on a simple site
2. Add the `Media & Text` block
3. Upload or select one of the images from your `Media Library`
4. Click on the image, and you will see the `Image Size` option
5. Now, try to test different images sizes. When you preview the page, you will see that this option doesn't make any difference to the image size

### What you expected to happen

I expected the image to reduce or increase in size when checking the preview or published page.

### What actually happened

I got different outcomes on different tests that I made. Sometimes, selecting an image size doesn't make any difference, and other times the image quality decrease or increases according to the option I choose. Maybe that's what this option is about. If that's the case, I'd suggest using a different name for it, perhaps `Image Quality`.

### Context

The user here was expecting the size of their images to change: 4578522-zen

Maybe the user here is also expecting the same: https://github.com/Automattic/jetpack/issues/21887

### Reproducibility

Intermittent

**Comment by Greatdane** [comment]
Reproduced. As noted, changing the image size does seem to affect the quality/resolution of the image, but not the actual size.

**Comment by cometgrrl** [comment]
This appears to me to be the same as [Automattic/jetpack#21887](https://github.com/Automattic/jetpack/issues/21887).  I will move this to cross-repro tracking.

All +1's of end-user reports should be done on this issue, while any discussion related to the issue itself and its fix should be done on the issue in the outside repository.

**Comment by Gustavo-Hilario** [comment]
Another instance of this issue but now using the `Gallery` block: 5211171-zen

**Comment by jeherve** [comment]
This is currently discussed here:

https://github.com/WordPress/gutenberg/issues/29362
