### ISSUE TITLE
Feature Request: combine "about" and "link in bio" categories

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#59383]
### What

While we don't have that many link-in-bio and about page templates, we could consider combining these into one "about" category.

Alternatively, we could surface link-in-bio also in about but that seems excessive? One of the templates already shows up in both.

<img width="1930" alt="Screenshot 2021-12-19 at 01 01 01" src="https://user-images.githubusercontent.com/87168/146657786-7986b184-eaee-48d1-920a-84cd27449717.png">
<img width="1937" alt="Screenshot 2021-12-19 at 01 00 52" src="https://user-images.githubusercontent.com/87168/146657789-64210c60-d38f-4257-8619-bf9359919c10.png">

### Why

Better discoverability.

**Comment by mtias** [comment]
It could be combined in name "About & Link in Bio" or "About & Bio". I don't mind extra categories, though it seems reasonable they'd be one after the other in that case.

**Comment by ianstewart** [comment]
Combining them makes sense, keeping the full "Link in Bio" phrasing.

**Comment by autumnfjeld** [comment]
To confirm, we will

* combine the About & Link in Bio categories into a single category
* this combined category will be titled "About & Link in Bio"

Putting this in our up next @Automattic/ganon-bloggers  :)

**Comment by fushar** [comment]
This is done. For more details, see the discussion on: pbxlJb-WA-p2.
