### ISSUE TITLE
[Bug]: Page template picker: doesn't scroll to up when changing categories

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#59382]
### Quick summary

Page template picker doesn't scroll up when changing categories.

https://user-images.githubusercontent.com/87168/146657671-28c231ee-6524-4c0b-b604-2da62d5030a5.mov

### Steps to reproduce

- Create a new page
- See page template picker
- Scroll down in one category
- Pick another category
- Stays scrolled down in new category

### What you expected to happen

Jump up.

### What actually happened

Stayed down.

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Page pattern selector scrolled back to top with each new category selected.

https://github.com/Automattic/wp-calypso/assets/27249804/d99dfef1-947f-43c1-97d9-66c697f5a208

📌 ACTIONS
- Closed as not reproducible / no longer relevant
