### ISSUE TITLE
Editor: Pasting into title causes issues with undo stack

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#5938]
Because of code introduced in https://github.com/Automattic/wp-calypso/pull/4826 (needed to prevent users from pasting newlines into post titles), pasting into the title field breaks the undo stack.

Here is a recording in Chrome of me typing, then cut/pasting some text, and then hitting undo/redo.

![editor-multiline-titles-chrome](https://cloud.githubusercontent.com/assets/227022/15874272/ff27adea-2cc7-11e6-8143-e92642670e5b.gif)

The undo stack is differently broken in Safari (only the paste event is retained, which I guess is not as bad).

Everything seems fine in Firefox.

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue.

#bug-scrub #pre-gutenburg-bug-purge
