### ISSUE TITLE
Feature Request: allow resetting the site

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#59384]
### What

Add a feature that allows you to "clear all you've done" for the site and reset it to the state where it was when we created it.

### Why

Sites with paid Activity log feature can revert to any point, but we could offer a simplified version for everyone which allows returning to the starting point.

Knowing you can easily "reset" the site can make it easier to try things out, and makes it easier to start over for a site.

Currently, customers either go through a very manual process (as described in [docs](https://wordpress.com/support/empty-site/)) or contact support:

![image](https://user-images.githubusercontent.com/87168/146658417-a236a8fa-a296-44ab-b041-027065141941.png)

Related "headstart on demand" https://github.com/Automattic/wp-calypso/issues/52760

**Comment by jordesign** [comment]
Closing this in favour of the existing open issue - https://github.com/Automattic/wp-calypso/issues/32792
