### ISSUE TITLE
Some images on reader disappear when you open a post

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#5939]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/discover
2. Scroll down until you reach this post: ![](https://cldup.com/J4FXs62W1J.png)
3. Click on it to expand

#### What I expected

The image to either expand and be bigger, or still be visible on the post body.

#### What happened instead

The image is gone: ![](https://cldup.com/kZ2nTRUAnM.png)

**Comment by lancewillett** [comment]
I can't reproduce this now — feel free to re-open if you see it happen again.
