### ISSUE TITLE
Marketplace: Add filter for marketplace products on MC pricing page

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#59399]
### Details

We need to have a filter that will allow us to see marketplace product's price on mc page. See pdh6GB-a7-p2#comment-358 for more context.

![CleanShot 2022-02-21 at 14 09 37@2x](https://user-images.githubusercontent.com/12430020/154952869-c788b561-ea54-4bd5-ac3b-4279f67ba761.png)

the codebase is in the sandbox `missioncontrol` PCYsg-306-p2#troubleshooting-mc-issues-on-sandbox

**Comment by lukaszwilczakwilnet** [comment]
PR for change: D82252-code

**Comment by dsas** [comment]
@lukaszwilczakwilnet for wpcom issues, we leave the issue in In Progress and open a draft github issue with the phab details

**Comment by Copons** [comment]
Closed by D82252-code
