### ISSUE TITLE
Site editor: add plugin info to options menu

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#59391]
### What

In the post editor, we display plugin info about Gutenberg, ETK, etc, in the options menu (3 dots at the top right of the screen)

<img width="317" alt="image" src="https://user-images.githubusercontent.com/1699996/146697907-da39e081-b6dd-4e3b-b4f1-9c71d4c8f115.png">

Let's add this to the Site editor, as well.

### Why

As more users use the Site editor, and we continue to debug more issues, it will be very helpful to have this info at hand.

One example is quickly copying the Gutenberg version when filing issues in Github.

**Comment by zaguiini** [comment]
Done in D72561-code.

**Comment by creativecoder** [comment]
Thanks @zaguiini !
