### ISSUE TITLE
Videos UI: Create documentation for course management.

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#59417]
Once everything is tied up together documentation should be written covering at least this topics:
 * Course management overview.
 * Course creation.
 * Course metadata.
 * Assigning and ordering videos to courses.
 * Video metadata.
 * I18n.

**Comment by kwight** [comment]
Let's also add a demo walkthrough video: #59685

**Comment by kwight** [comment]
The Field Guide has been updated as much as possible; we'll add the walkthrough video whenever that's done. PCYsg-DgC-p2
