### ISSUE TITLE
Reader: Newly Followed Site displayed twice under /following/manage

### ISSUE THREAD

**Issue by dcalhoun** [Automattic/wp-calypso#59421]
_This issue was found in a recent backlog sweep, and updated to only reflect 1 issue at a time.  2nd issue opened and linked in comments below._

### Quick summary

Following a site can sometimes result in the site's posts missing from the Reader posts list and the site displayed twice under "Manage" followed sites. 

### Steps to reproduce

1. Log in to a WordPress.com account. 
2. Visit the [_Managed Followed Sites_](https://wordpress.com/following/manage) page. 
3. In a new tab, visit https://automattic.design. 
4. Follow the https://automattic.design from the floating toolbar in the bottom-right corner. 
5. Switch to the first tab with _Managed Followed Sites_. 
6. Refresh the page. 

### What you expected to happen

Automattic Design is listed _once_ within the Manage Followed Sites list. Posts from Automattic Design are present within the Reader posts list. 

### What actually happened

Automattic Design is listed _twice_ within the Manage Followed Sites list. Posts from Automattic Design are not present within the Reader posts list. 

### Browser

Google Chrome/Chromium, Apple Safari

### Simple/Atomic

Simple

### Other notes

<details><summary>Screenshot of Duplicate Followed Site</summary>

<img width="1180" alt="reader-duplicative-missing-subscription" src="https://user-images.githubusercontent.com/438664/146810942-8c583abe-dc06-4466-914a-b3c0a3d1df56.png">

</details>

<details><summary>Video of Reproduction</summary>

https://user-images.githubusercontent.com/438664/146810990-588f8623-73ce-4575-8d06-8812608a3865.mov

</details>

### Reproducibility

Consistent

### Available workarounds?

No but the platform is still usable

### Workaround details

One may visit the site directly outside of the Reader, but that defeats the purpose of the Reader providing access to the latest posts from followed sites.

**Comment by aleone89** [comment]
Another report of this here: hc-35244013

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested with `automattic.design` - **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- `https://wordpress.com/following/manage` shows the newly followed site twice.  This page is not very accessible anymore in the reader, so I'm not sure how users get to this anymore, but the duplicated site is clear:

![Markup on 2023-06-28 at 14:34:25](https://github.com/Automattic/wp-calypso/assets/27249804/dc7a9109-7f84-41b3-a672-6adc606a614a)

The accessible page to manage followed sites is now: `https://wordpress.com/read/subscriptions`, which does not show the site duplicated:

https://github.com/Automattic/wp-calypso/assets/27249804/485814a9-ba80-480f-bcca-6cf3818bdf1f

📌 ACTIONS
- Assigned to @Automattic/loop 
- Opening new issue for 2nd issue reported here: https://github.com/Automattic/wp-calypso/issues/78757

**Comment by davemart-in** [comment]
https://wordpress.com/following/manage is being replaced with https://wordpress.com/read/subscriptions which is currently behind a feature flag. I tried replicating this same issue on https://wordpress.com/read/subscriptions, but was unable to. @cuemarie mind double checking? I suspect this new UI will be release in like the next week, so I marked this as won't fix.

**Comment by cuemarie** [comment]
Thanks @davemart-in ! I saw the same - no issue in `/read/subscriptions`, only in the outgoing `following/manage`. Thank you for labeling as such!  I think it's best we close this out 👍
