### ISSUE TITLE
Update calypso links to use primary domain, such that we don't link to unresolved newly registered domains

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#59428]
## Description

Some TDL can take up to 30/40 minutes (tens of minutes) to register.   In Dec 2021, D71776-code addressed this issue by ensuring that we don't set a user's primary domein to their custom domain unti the DNS for that domain resolves.   See slack convo: p1639684065272700/1639671882.216800-slack-C029SB8JT8S

From @p-jackson  p1639686740275000/1639671882.216800-slack-C029SB8JT8S
> But that only works in the hero flow, as you point out it wouldn’t help when it comes time to use wp-admin links and the like.

As a follow up, we need to ensure that links in Calypso that lead to a site's front end point to the site's primary domain (and NOT to a newly registered domain that might not have yet resolved).

## Dev Tasks
- [ ] Add clarity to the above description if needed (in case my summary is inacurate) 
- [ ] Ensure links in calypso lead to the site's primary domain, and NOT the registered domain
- [ ] another task.....
- [ ] ping @delputnam for a review 

## Related

* Sites created as Atomic with async TLDs (.ca, .blog) are non-functional after purchase #51121 (open issue)
* Domains: Don't automatically set the primary domain for a site until the DNS resolves back to WPCOM infrastructure: D71776-code (this fix was implemented)
*  slack convo: p1639684065272700/1639671882.216800-slack-C029SB8JT8S

**Comment by roo2** [comment]
As far as I can find out, All of the links in calypso are already using the _Primary_ domain, and so, no further action is needed since @delputnam's fix here D71776-code
