### ISSUE TITLE
Duplicated password visibility icons on IE/Edge on Windows 10

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#5942]
On Windows 10, both on IE/Edge we get two password visibility icons. This happens because the native password field already has the feature on these browsers.

![](https://cldup.com/J_kEH284tw.png)

We should probably disable our implementation, and let the native one.

**Comment by lancewillett** [comment]
I couldn't repeat this — testing Windows 10 with IE Edge today.

<img width="1395" alt="screen shot 2016-10-14 at 11 36 35" src="https://cloud.githubusercontent.com/assets/66797/19398653/81cb6670-9202-11e6-998f-446e36307e8a.png">
