### ISSUE TITLE
Marketplace: Remove option will remove plugin from site while subscription being active

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#59444]
### Details
When paid plugin is installed, if the user clicks on the remove button then the plugin will be removed from the user's site. This function appears to be working fine but it leaves the subscription dangling. 

![](https://cloudup.com/cwI2UikF7JN+)

### Possible Solutions
- We should alert users that you will lose access to the plugin while the subscription is active and it will keep renewing until the user manually removes the subscription.  
- We should remove the button to prevent this action.

**Please suggest your ideas if this needs to be fixed.**

**Comment by cpapazoglou** [comment]
> We should remove the button to prevent this action.

This is the solution. The same should happen with "Autoupdates", since it's a managed plugin you can't control the autoupdates.
