### ISSUE TITLE
[Bug]: Paxon theme info page links to the wrong demo site

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#59477]
### Quick summary

Paxton theme info page has the wrong demo site link

<img width="1553" alt="Screenshot 2021-12-22 at 4 05 59 PM" src="https://user-images.githubusercontent.com/1500769/147030895-9026eb7e-71fb-4a93-ad5c-13892091aaa5.png">

This is probably driven by the fact that the Theme API is returning the wrong `demo_uri` for Paxton.

### Steps to reproduce

1. Visit Paxton theme info at `/theme/paxton/{{ site slug }}`
2. Hover over the "Open live demo" button

### What you expected to happen

Should be a link to https://paxtondemo.wordpress.com/

### What actually happened

Links to cainsnuxtest21090225591.wordpress.com

### Context

p1633446049102100-slack-C9EJ7KSGH

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by michaeldcain** [comment]
This should be fixed now. Lots of discussion in the following:

- p1633446049102100-slack-C9EJ7KSGH
- p1640193676083500-slack-C02JQ08G0
