### ISSUE TITLE
Pressing "Export" on Mobile Safari results in a success message, but no export

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#5948]
#### Steps to reproduce
1. Starting at URL (in Mobile Safari): https://wordpress.com/following/edit
2. Tap "Export"
#### What happened

A success message, but no export

![img_3466](https://cloud.githubusercontent.com/assets/418473/15946401/2280aa20-2e6d-11e6-9e5e-63a6750ea332.PNG)

Since mobile safari doesn't support downloads, we should probably display a notice instructing the user to use a desktop/laptop computer.
#### Browser / OS version

iOS 9.3.2

**Comment by lancewillett** [comment]
Why wouldn't Mobile Safari prompt to save the file? Would be nice to still allow it in case iOS users want to import / export using their phone or tablet.

**Comment by jancavan** [comment]
The Manage Following page is being revamped and we're dropping the Import/Export buttons in viewports `<660px` so I'm closing this issue.
