### ISSUE TITLE
Investigation: Save woo onbarding answers to the site post install

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#59481]
Initial idea is to thread the site options to both the transfer and install endpoints and save them against the site post transfer.

There is also talk of creating a new Woo endpoint to formalize this onboarding data https://github.com/Automattic/wc-calypso-bridge/issues/769#issuecomment-992052733. We would then need to call this on the backend as users won't have auth cookies by the time we want to set this info. (before we redirect to site)  (cc @joshuatf)

@DustyReagan may also have other ideas about how best to do this.

- [ ] Investigate best approach to solve this
- [ ] Create new tickets once we've decided on approach. (Both for wpcom rest api and calypso data-layer changes as required)

**Comment by retrofox** [comment]
I'm researching the site options/settings approach.

**Comment by obenland** [comment]
Checking with Atomic team if we can add these options to the option allow-list for atomic transfers: p9o2xV-1L5-p2

**Comment by DustyReagan** [comment]
For reference the fields were looking at saving when going from simple to Atomic are:

```
'woocommerce_store_address',
'woocommerce_store_address_2',
'woocommerce_store_city',
'woocommerce_default_country',
'woocommerce_store_postcode',
'woocommerce_onboarding_profile', // This is all the business profile data serialized.
```

The idea is we'll save these fields in wp_options while the site is Simple and mark them to be transferred when the site goes Atomic. WooCommerce will see these fields already exist once installed and use them.

**Comment by DustyReagan** [comment]
D72489-code adds these fields to the whitelist.

**Comment by obenland** [comment]
Fixed in D72489-code.
