### ISSUE TITLE
Investigation: Iterate on woop confirm step CTA text

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#59485]
"Sounds Good" for something potentially destructive isn't great copy. We should aim to make the copy more serious at least e.g. "Confirm". Another option is to make it more dynamic to account for the warnings in play. "Change Domain & Install", "Upgrade & Install".

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/1398304/149399970-62193716-302c-4412-b6bd-ea881a7be2ab.png">

**Comment by obenland** [comment]
@SaxonF Do you have any thoughts on a less casual button text for this screen?

**Comment by lsl** [comment]
From @SaxonF change the headings to read: "Plan upgrade required"  and "Domain change required". This aligns both things as "warnings" and makes it more clear / hints that "somethings up" / needs attention.

I think this copy makes the most sense and we can probably leave the CTA as is.

**Comment by SaxonF** [comment]
@lsl we could probably also change the CTA to "Confirm" as you suggested so that its more task orientated just to be safe. What do you think?

**Comment by lsl** [comment]
Sounds good.
