### ISSUE TITLE
Uppercase button doesn't work on simple sites.

### ISSUE THREAD

**Issue by fresatomica** [Automattic/wp-calypso#59494]
### Quick summary

When formatting text in any block, the uppercase button does not work. You can see the CSS class in the inspector, but the text appears in lowercase.

### Steps to reproduce

1. Create a post and add some text.
2. Highlight the text and from the block toolbar choose the option "Uppercase".
3. Preview or publish the site.

### What you expected to happen

The selected text should be in uppercase.

### What actually happened

The selected text doesn't change although you'll see the _uppercase_ class in the CSS.

### Context

Reported on the forums: https://wordpress.com/forums/topic/upper-case-button-not-working/.

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by as-esu** [comment]
4667643-zen
Suggested writing text in uppercase manually or capitalizing the words in another editor and pasting them into the block editor.

**Comment by fresatomica** [comment]
Another report: https://wordpress.com/forums/topic/colors-and-capitals/?view=all

**Comment by cuemarie** [comment]
Closing in favor of duplicate: https://github.com/Automattic/wp-calypso/issues/72822
