### ISSUE TITLE
FSE Beta: Footer Template/Area Isn't Full Width 

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#59503]
### Quick summary

It doesn't seem the Footer Template/Area can be set as Full Width.

### Steps to reproduce

1. Open the Site Editor
2. Click on the Footer area/template (it won't offer any settings)
3. Select the Group block inside the Footer area/template
4. Set a color background on that Group block
5. On its Layout setting, set it as 100% wide

### What you expected to happen

To get a Full Width footer area.

### What actually happened

The footer shows blank areas on both sides.

### Context

It feels to me that users would want to set a different color on the footer, and expect that the color will take the whole footer area when set as full width. But it's like an area inside a footer area, because it seems there's another background color/pattern behind it.

This is the result you get:

![FooterTemplate](https://user-images.githubusercontent.com/16104522/147140538-2e165673-0ab3-4c89-a8ce-a9791965a803.jpg)

**Comment by formosattic** [comment]
> On its Layout setting, set it as 100% wide

@carinapilar, not sure if this has changed but I'm only seeing an option to set width in `px`.
![image1](https://user-images.githubusercontent.com/15944096/147549742-959b1bd8-91c0-46b8-a753-1ec5e8e2aed1.png)

I agree with the issue that there's so obvious ways to set the footer to full-width.

I find that a confusing part is that the Group block doesn't consistently offers the option of setting the block width. It's not clear why the option is available or not, as shown here:
![troubleshooting](https://user-images.githubusercontent.com/15944096/147551158-dcf21668-16c7-4a56-b279-f3f27a19cf1a.gif)

I was able to achieve that by tinkering around, but it's not intuitive:

1. Creating a nested Group block, where I'm allowed to set it full-width
2. In List View, drag the full width Group block to the footer area. (Dragging from the editor wouldn't work)

The full-with isn't reflected in the editor though.

| Editor  | Live site |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/147551630-5a09e67b-b448-42cf-9e1d-02e95335ddfb.png) | ![image2](https://user-images.githubusercontent.com/15944096/147551708-f125912f-530a-471a-88c1-d73dc3ce0119.png)  |

**Comment by carinapilar** [comment]
> I'm only seeing an option to set width in px.

Yeah, it's very confusing, you need to click on that little `px` indicator to change it to `%`. I wasn't able to get the full-width option on a Group block. 😕

**Comment by formosattic** [comment]
Thanks, I see it now, and yeah, setting it 100% doesn't work for me either.

![image1](https://user-images.githubusercontent.com/15944096/147556326-b913cbf5-f468-41e7-afa7-08cbd362f2a5.png)

**Comment by jordesign** [comment]
Hey @carinapilar  - were you using a Blockbase child theme for this? Sounds like it might be 
https://github.com/Automattic/themes/issues/5180

**Comment by carinapilar** [comment]
It seems to be the same thing @jordesign, yes. Since there are no background color options for the template parts, I set that up on a Group block inside of it, which will then make visible the padding mentioned on the other issue.

**Comment by jordesign** [comment]
OK thanks for clarifying - looks that way to me too. I'll close this issue in favor of https://github.com/Automattic/themes/issues/5180 - which _is_ on the list of fixes to hopefully come soon.

**Comment by Addison-Stavlo** [comment]
> I'll close this issue in favor of https://github.com/Automattic/themes/issues/5180 - which is on the list of fixes to hopefully come soon.
