### ISSUE TITLE
WSOD for Blockbase themes on Atomic sites

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#59513]
### Quick summary

With any Blockbase theme active on an Atomic Site - no content loads on any pages. Just a blank white page.

### Steps to reproduce

1. Activate a Blockbase child theme (Russell etc) on an Atomic Site
2. View site

### What you expected to happen

Site to load with the theme active

### What actually happened

White screen is displayed

### Context

Customer report: 33311940-hc

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Blockbase child themes

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by annbingle** [comment]
Got this issue here in 33326436-hc The site loads just fine on Twenty Twenty One but not on Blockbase.

**Comment by pauloeaquino** [comment]
Encountered in 32804082-hc

**Comment by jordesign** [comment]
This has been resolved with a revert of GB 12.2.2
