### ISSUE TITLE
Woo Landing page selected site not tracking changes to selected site

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#59516]
You can get in a situation where the landing page sends you to the wrong installer flow if you switch sites before clicking on the CTA.

Update: the original issue referenced here is no longer happening but we do seem to have a similar issue that needs resolving: https://github.com/Automattic/wp-calypso/issues/59516#issuecomment-1018928262

**Comment by DustyReagan** [comment]
Tried reproducing but I'm seeing a white screen on site switching. Will investigate further.

https://user-images.githubusercontent.com/140841/150578233-046199e4-5cde-46b3-a1f2-cbd9d73bc1d2.mp4

**Comment by DustyReagan** [comment]
Discussion about the blank screen when switching sites here: p1642787762096000-slack-C029UPVMGTW
PR with the fix here: [Woo installer: Remove plugins loaded check #60348](https://github.com/Automattic/wp-calypso/pull/60348)

There does still seem to be an issue with business profile data not switching when the site switches, so this issue remains open.

**Comment by DustyReagan** [comment]
How to reproduce the bug. You need 2 similar sites ready to install WooCommerce (I used simple Business sites on Calypso trunk).

1. Start installing WooCommerce on site A, "Continue" all the way to "One final step" and the use the "back" link to go back to your dashboard.
2. "Switch sites" and select your site B.
3. Start installing WooCommerce on site B, "Continue" all the way to "One final step" and the use the "back" link to go back to your dashboard. You are now back on site A.

Video of bug with narration below! 🎤 😅 🔉

https://user-images.githubusercontent.com/140841/150610627-1f6cd5c5-a49b-40be-a652-a3d0ec8d2126.mp4

**Comment by DustyReagan** [comment]
A final note before the weekend. I'm seeing the wrong siteId first appear [here](https://github.com/Automattic/wp-calypso/blob/29291fd2a64b741e5eb9110eebea0efca9d6313a/client/signup/steps/woocommerce-install/step-store-address/index.tsx#L49) right before the address step moves on to the info step.

**Comment by lsl** [comment]
Oh wow, it's worse than I thought. :smile: 

We might need to switch to using the `site` [dependency value](https://github.com/Automattic/wp-calypso/blame/a5f7a48b6fb8af29e0f12540aec5ff8eb0608f85/client/signup/controller.js#L357) all the way through. I thought the issue was in the landing page but it looks like its actually in the signup framework.

**Comment by lsl** [comment]
@DustyReagan I noticed we're not limiting the hook's update tracking state to site id, maybe that's being copied over? 

e.g. if true, this might fix https://github.com/Automattic/wp-calypso/pull/60383

**Comment by DustyReagan** [comment]
I feel like it's happening outside of `useSiteSettings`, because it looks like it's being passed the wrong `siteId` as a parameter when the switch happens. But I'm not sure. 😞 I was thinking maybe it has something to do with the [flow-controler](https://github.com/Automattic/wp-calypso/blob/0011565890b9f25695b74c59d0c6dee4218e1446/client/lib/signup/flow-controller.ts). Just a hunch at this point. I left a note about it here too: p1643066735152500-slack-C029UPVMGTW
