### ISSUE TITLE
FSE beta: Changing fonts in Customizer and previewing are inconsistent

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#59528]
### Quick summary

Navigating to a different page in Customizer after saving fonts results in the old font in the Preview panel.

### Steps to reproduce

1. Go to My Site → Appearance → Customize → Fonts 
2. Chose a different font for either Body or Heading
3. See the preview of the new font on the right side
4. Navigate to a different page of the site withing Preview on the right
5. Save changes
6. Navigate to a different page of the site withing Preview on the right

https://user-images.githubusercontent.com/39308239/147237886-226f2b02-1c85-4931-8cb1-7e5c31fba6a8.mov

### What you expected to happen

Continue to see the chosen font in Preview

### What actually happened

I see the default theme font instead.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Tested with Quadrat so far

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

Fonts can be set globally in Site Editor within Styles. So the setting for setting Fonts in Customizer should be deactivated or redirected to Site Editor.

![image](https://user-images.githubusercontent.com/39308239/147238225-ec2c882c-2c03-43c5-a287-4a99bc41708a.png)

**Comment by kosiew** [comment]
Hi @zdenys ,

Thanks for reporting this and the detailed steps.

This issue is fixed already.

![Screen Capture on 2021-12-31 at 15-12-19](https://user-images.githubusercontent.com/29057562/147809329-9a9cd08a-62db-4e2d-b773-f55dee8769eb.gif)
