### ISSUE TITLE
[Bug]: Theme selection: replacing home page doesn't work

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#59524]
### Quick summary

When changing themes, we give customers the option to replace their entire homepage with the sample content that each theme brings in.

In my testing, selecting this option didn't have any effect on the homepage's content nor was there a draft with my old homepage.

#### Video

https://user-images.githubusercontent.com/390760/147229170-8577b183-fc48-4207-9dc7-593f7ce25155.mov

### Steps to reproduce

1. Start at wordpress.com/themes/SITE_URL.
2. Pick a theme you like; e.g.: Geologist - Blue.
3. When in wordpress.com/theme/geologist-slate/SITE_URL, click "Activate this design".
4. In the dialog that pops up, select the option to “Replace my homepage”.
5. Press “Activate”.

### What you expected to happen

- My homepage to be entirely replaced by the content shown in the preview.
- My old homepage to be under Pages → Drafts.

### What actually happened

- Homepage content didn't change.
- There are no drafts.

### Reproducibility

Consistent

**Comment by michaeldcain** [comment]
@alaczek @kjellr: IIRC, themes with a blog homepage (e.g. Geologist) require the `blog-homepage` tag to work properly on theme switch. I've added the tag to the Geologist (and variants) and Zoologist showcase pages, but they'll need to be added to the stylesheets too.

**Comment by kjellr** [comment]
Ah ok cool, thanks @michaeldcain. I'll add this to the theme dev team's board so they can be aware and make updates to Geologist and its variants.
