### ISSUE TITLE
FSE: Update Global Styles Welcome Guide Docs URL

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#59526]
Update: The link now works, but lets update it to point to dotcom docs - https://github.com/Automattic/wp-calypso/issues/59526#issuecomment-1180763386

### Quick summary

The `Learn more` screen of the Style Welcome Guide has the hyperlinked text `Here’s a detailed guide to learn how to make the most of it.` that points to https://wordpress.org/support/article/styles-overview/ That page loads "Oops! That page can’t be found." message.

### Steps to reproduce

1. Open Site Editor
2. Click the Styles icon on top right
3. Click three dots menu and then `Welcome Guide`
4. Click `Next` until you land on the last tab `Learn more` of the guide
5. Click the link `Here’s a detailed guide to learn how to make the most of it.`

![image](https://user-images.githubusercontent.com/39308239/147231835-c8ce6329-310c-47bc-9c05-7960facaa657.png)

![image](https://user-images.githubusercontent.com/39308239/147232633-651c6d5b-c092-49b2-b1f4-524823d2649b.png)

### What you expected to happen

One of these options (with 2 being a preferred one):

1. A page that doesn't display `Oops! That page can’t be found.` message at https://wordpress.org/support/article/styles-overview/
2. A page hosted on WordPress.com with the related guide about styles

### What actually happened

https://wordpress.org/support/article/styles-overview/ page loads "Oops! That page can’t be found." message.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by formosattic** [comment]
Issue is still happening.
![troubleshooting](https://user-images.githubusercontent.com/15944096/147553213-c5804cb9-cfec-420a-b302-45a2a166f3b9.gif)

**Comment by cometgrrl** [comment]
Per https://github.com/WordPress/gutenberg/pull/37176#issuecomment-988425669, this page has not been made live yet by the core team.

Moving to the cross-repo tracking board.

**Comment by zdenys** [comment]
@cometgrrl as an FYI, we now have a WordPress.com version of the guide about Styles: https://wordpress.com/support/using-styles/ 

So I think we should use that link instead of the WordPress.org one https://wordpress.org/support/article/styles-overview/.

**Comment by arunsathiya** [comment]
@cometgrrl Came cross this issue as part of my guided triage work: pc4f5j-1Tr-p2. Do you know if we have plans to update that link to WordPress.com's as Denys noted above? Not sure if this falls under @Automattic/team-calypso's work, but tagging them too.

**Comment by noahtallen** [comment]
@Automattic/cylon might have some ideas, since they've worked on the FSE/global styles integration on dotcom

**Comment by Addison-Stavlo** [comment]
It looks like that page link is now live, so there is no longer an error / 404.

Regarding updating the link to redirect to wpcom documentation instead of org, ive seen this sort of thing handled via ETK  in the past (ex - https://github.com/Automattic/wp-calypso/pull/62498/files)

**Comment by Addison-Stavlo** [comment]
Updating the title of this issue to reflect its current state.

Lets update this link now point to dotcoms documentation. https://wordpress.com/support/using-styles/

**Comment by jeyip** [comment]
Holding this as an issue that @edanzer and I can tackle in onboarding

**Comment by jeyip** [comment]
Verified that links are now pointing to wpcom on a simple + atomic test site
