### ISSUE TITLE
[Bug]: Onboarding: Arial showing up instead of System Font

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#59521]
### Quick summary

After going through the first steps of the Onboarding process, Arial is displayed in the domain selection screen instead of the system font.

![image](https://user-images.githubusercontent.com/390760/147221424-5999117c-c304-4e21-bfd1-366ba56e8d6b.png)

### More details

Note: this issue is likely to NOT show up on all browsers and configurations, and even affect different parts of Calypso.

This seems to be caused by an incomplete reset of CSS styles, since the issue only happens in certain elements (e.g.: `button`). For instance, if I add `button` to the reset styles here the problem goes away:

https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/assets/stylesheets/shared/_reset.scss#L56-L64

Moreso, note that we're not resetting the button `font-family`:

https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/assets/stylesheets/shared/_reset.scss#L123-L131

When normalize.css, for example, does it:

https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L160-L169

### Steps to reproduce

1. Start at wordpress.com/new.
2. Select a name for your site.
3. On the domain step, notice that Arial is displayed.

### What you expected to happen

The system font to be used everywhere equally.

### What actually happened

Arial is being displayed instead.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Firefox 114 - Could not replicate
- Tested on Chrome Version 114.0.5735.133 - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on Firefox and Chrome (Mac OS), and both browsers showed System Font.

![Markup on 2023-06-28 at 12:33:08](https://github.com/Automattic/wp-calypso/assets/27249804/793e17fc-af09-4b08-9c1f-8e12ca6016f1)

📌 ACTIONS
- Given the age of the report, closing this as no longer relevant/not reproducible
