### ISSUE TITLE
[Bug]: Onboarding: Themes order is random

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#59523]
### Quick summary

When trying out different themes by going back and forth between the theme list and the larger previews, the themes order is reset and appears to be random.

This makes the UI behave in unpredictable ways, which is super frustrating if you're going through all themes and trying to keep track which ones you've already tried.

Related: https://github.com/Automattic/wp-calypso/issues/59522

#### Video

https://user-images.githubusercontent.com/390760/147227877-24a72420-eccf-4759-a8b5-35f11c6bbe38.mov

Notice how the order keeps changing in the video above:
1. Bowen, Edison, Cassel
2. Edison, Cassel, Bowen
3. Cassel, Edison, Bowen
4. Cassel, Bowen, Edison

### Steps to reproduce

1. Start at wordpress.com/new.
1. Go through the initial steps until you reach theme selection.
1. Select a category; e.g.: Blog.
1. Select a theme; e.g.: Cassel.
1. Click the Go Back link.
1. Select the same category; e.g.: Blog.

### What you expected to happen

The themes to retain some order (even if it's not alphabetical) to make the UI a bit more predictable.

### What actually happened

The theme order is reset every time.

### Reproducibility

Consistent

**Comment by simison** [comment]
Random order was on purpose but something has broken to stop order being remembered between sessions.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on New Site - **Replicated** somewhat 

📌 FINDINGS/SCREENSHOTS/VIDEO
- In the latest iteration of the design selection flow, moving around among the categories does not alone cause the themes to reshuffle - but viewing a "Choose your own design" / Pattern Assembler theme then going "back" does cause the themes to show up in a new order.

Example 1:

https://github.com/Automattic/wp-calypso/assets/27249804/4a03384a-537a-4ac6-8055-a95f5ff5ccb8

Example 2:

https://github.com/Automattic/wp-calypso/assets/27249804/7701d560-6f0d-4258-84b3-2f98e48a687f

📌 ACTIONS
- Assigned to @Automattic/lego

**Comment by taipeicoder** [comment]
The ordering of themes in the design picker is now manually curated (see: paYJgx-3Eb-p2). There is still some shuffling mechanism, but it no longer affects the above-the-fold experience of the design picker. Let's reopen this issue if it pops-up again in the future.
