### ISSUE TITLE
Blockbase theme not saving color customization changes

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#59542]
### Quick summary

On a site with Blockbase installed, changes made under Appearance > Customize > Colors are not preserved after moving away from the page or refreshing the customizer.

### Steps to reproduce

1. Open a site with Blockbase theme
2. Head to Appearance > Customize > Colors
3. Change primary and secondary colors
4. Save Changes
5. Refresh customizer

### What you expected to happen

Colors should be preserved

### What actually happened

Colors reset to Blockbase defaults

### Context

Encountered here: 33337092-hc

I was working in Blockbase yesterday (Wednesday) and wasn't encountering this issue

The problem persists across my test sites with the Site Editor enabled and disabled.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Blockbase

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by KirkwallDay** [comment]
This doesn't seem to replicate on simple sites, so this could be an Atomic only issue.

**Comment by cuemarie** [comment]
Agreed, just was returning to say this isn't present on my Simple site. Thanks @KirkwallDay !

**Comment by cuemarie** [comment]
Looks like this was solved with the redeployment of Gutenberg v12.2.0 on the Atomic platform. Discussed here: p1640295784107400/1640295514.106300-slack-CB0B2G43X

Closing now!
