### ISSUE TITLE
Unable to permanently close "If you want to edit the gallery you just added in the mobile app, please make sure you use version 18.2 of the app or above, to avoid losing any data" messages

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#59560]
### Quick summary

The new Gallery block displays the message "If you want to edit the gallery you just added in the mobile app, please make sure you use version 18.2 of the app or above, to avoid losing any data".

We've had a user report to us a few times that they're unable to close out of these error messages, after a week or so of hitting 'X' on all the posts where they appear.

![Markup on 2021-12-24 at 09:49:54](https://user-images.githubusercontent.com/27249804/147365655-3a809d67-1776-4cd7-ad84-664ce356f52b.png)

### Steps to reproduce

Unable to reproduce thus far on my end. User is working in Edge 96 on Windows 10. 

Browser info can be found here: p1640298927444000/1640297514.440000-slack-C03TY6J1A

They open their posts with gallery blocks to edit, and the message continues to repopulate every few minutes, even after they close out all boxes.

### What you expected to happen

Once they close out of all messages on a post using the Gallery block, the messages should not reappear.

### What actually happened

The messages continue to repopulate for the user, making it difficult to edit the page/post.

### Context

First reported here: 33230297-hc on 2021-12-15

>  It started a few weeks ago, but once i deleted them I could edit, but today after deletion they keep re populating.

> When i open the page, it's populated with those messages. As of today it keep re populating as i type.

Reported again: 33338129-hc on 2021-12-23

### Simple, Atomic or both?

Simple

### Browser, operating system and other notes

They're using Edge 96 on Windows 10 

They had no other browsers they could try, but it was replicable for them across 2 devices with the same browser & OS.

### Severity

One

### Available workarounds?

No but the platform is still usable

### Workaround details

I've asked this user to consider downloading another browser to try. They seem very hesitant to download anything on their device, which stops our ability to test across browsers for them.

**Comment by cuemarie** [comment]
This may be a single user issue, but I wanted to create a separate place to track it, as currently we're trying to track it in the comments of https://github.com/Automattic/wp-calypso/issues/58450 , and that's causing some confusion. 

Wondering if anyone with Edge 96 + Win 10 recreate this issue?

**Comment by kelasante** [comment]
This issue occurred again in 31830429-hc. The user has the WordPress app installed on their device (version 18.8). They mentioned that they do not use the mobile app to edit their pages. They use their Mac to edit. However, every time they try and add a gallery block on their Mac, they see this message:

<img width="753" alt="Markup 2021-12-28 at 08 26 54" src="https://user-images.githubusercontent.com/74204272/147585381-55c0bfd4-62ca-47d5-91b2-5f28425cffb0.png">

**Comment by danielk-am** [comment]
This issue also occurred on 28169261-hc.

Current workaround:
What I did was to deactivate CoBlocks plugin, and reactivate it, and the errors no longer show up on both the user's and my side.

**Comment by kosiew** [comment]
Hi @cuemarie,

Thanks for reporting this and the detailed steps.

I, however, could not reproduce this on a Simple site on a Microsoft Edge on a Windows 10 machine.

Microsoft Edge 96.0.1054.62

@kelasante,

I also could not reproduce this on Google Chrome.


In both Chrome and Edge, I see the the message once and after I click on `x`, it does not appear again on editing the posts or creating new galleries.


Can you gather more information on how to reproduce this?

**Comment by cuemarie** [comment]
Hey @kosiew! Thanks for taking a look at this. Given our inability to reproduce, my gut here is that this was a single user issue, in the instance I reported.

This user is with us a lot, so I've scanned their last few interactions with us since their original reports, and as far as I can tell they haven't brought it up again.  Do you think this is worth opening up with them further, or would you tend to assume good news if we haven't heard about it?

**Comment by donalirl** [comment]
Another case in #4666576-zen. I can successfully recreate by:

1. Editing the post
2. Selecting the gallery block
3. Adding an additional image via the media library to the gallery

Like other cases, the user does not use the WP mobile app at all, only desktop web.

However, the error messages can be closed, so maybe the title of this issue can be updated if that is consistent with other experiences. The error can be closed, but reappears again, stacking on top of each other:

![Annotation on 2022-01-08 at 16-31-26](https://user-images.githubusercontent.com/30727666/148632930-fb7e8ffb-9a39-4e1f-870e-39fcf403bda5.png)

**Comment by glendaviesnz** [comment]
Thanks for reporting this. We were unable to replicate this at all across various browsers and different installs. It is very strange that this happens to just a very small number of users. For some reason it appears that the toggle that turns the notice off after the first display is not working, but because we can't replicate it, it is hard to come up with a reliable fix. 

Given that number of users still on mobile app < 18.2 should have reduced significantly since the warning was added, the  confusion to users experiencing this issue is potentially greater than than the potential risk reduction for mobile app users on the older versions, so we will probably get this removed rather than try and rectify it - https://github.com/WordPress/gutenberg/pull/37842

**Comment by masperber** [comment]
Another report here: 28749386-hc

I tried to deactivate and activate CoBlocks as another HE suggested, but this didn't resolve the issue.

The error messages appeared only on a specific page.

Workaround: I copied all of content on the page that was producing the issue and copied it to a new page. This new page didn't produce the error messages.

**Comment by glendaviesnz** [comment]
The fix at https://github.com/WordPress/gutenberg/pull/37842 has been merged, so this issue should be resolved once the next release of Gutenberg gets deployed.
