### ISSUE TITLE
FSE beta: Custom colors added in Styles > Colors > Palette disappear after clicking Done

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#59565]
### Quick summary

Custom colors added to Styles > Colors > Palette disappear after clicking Done

### Steps to reproduce

- Open Site Editor
- Click Styles > Colors > Palettes
- Click + next to Custom section
- Add at least one color
- Click Done

### What you expected to happen

Colors added should stay

### What actually happened

Colors added disappear

https://user-images.githubusercontent.com/39308239/147387728-abb67bfc-9259-4347-8440-fcc667b82705.mov

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Tested with Quadrat so far

### Browser, operating system and other notes

Chrome 96 on macOS Big Sur 11.6

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by formosattic** [comment]
Was able to reproduce as well.

**Comment by zdenys** [comment]
I can no longer reproduce with Gutenberg: v12.5.4 on WordPress.com. So I assume it's been fixed in core (possibly here https://github.com/WordPress/gutenberg/issues/38185). Closing for now.

https://user-images.githubusercontent.com/39308239/153622862-303b6d9f-387d-4f14-98b0-768e3fcca70e.mp4
