### ISSUE TITLE
Plugins Browser: Fix plugins search pagination

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#59567]
Currently the plugins search is the union of paid and free plugins, which is made in two different requests. The paid plugins results always prepends the free ones independent of which page. Given this behavior we need to address some points:

1. Should the paid results be fixed on the top? Ex: when we are on the second (third, etc) page we are still seeing the same paid plugins we saw on the first page.
2. The last plugins are not being showed when we have paid plugins. Ex: when we have 3 paid plugins on our search, the last 3 free plugins of each page will not be showed. - https://github.com/Automattic/wp-calypso/pull/59592
3. We must address the future pagination of paid plugins (possibly a follow-up)

---

Related to #58654

**Comment by cpapazoglou** [comment]
I have create a PR to fix (1) & (2) https://github.com/Automattic/wp-calypso/pull/59592 which is currently a blocker.

We can then follow up on (3).
