### ISSUE TITLE
FSE Beta: GIF block display 

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#59563]
### Steps to reproduce

1. Activate FSE Beta
2. Add a GIF block

### What you expected to happen

Expected view. 

It should look similar to what happens on a .org (self-hosted site) with [FSE/WordPress.com Editing Toolkit plugin](https://wordpress.org/plugins/full-site-editing/)

![image2](https://user-images.githubusercontent.com/15944096/147381425-10227f8b-3cb9-4823-b392-41ce5b7f8dc8.png)

### What actually happened

On Simple, and Atomic sites (regardless of WordPress.com Editing Toolkit activated or not), , thumbnails are tiny, and there's a huge blank space.
![image1](https://user-images.githubusercontent.com/15944096/147381408-5b3608c5-a6dd-40b7-8ea6-f9d2aef6a07f.png)

### Context

Testing FSE Beta.

### Theme-specific issue?

Tested with Quadrat.

**Comment by cometgrrl** [comment]
@formosattic Based on your callout that you tested on .org and simple for the expected, does that mean this is reproducible only on atomic sites?

**Comment by formosattic** [comment]
@cometgrrl, yes, I updated the initial post for clarity. 

The issue happens on Simple, and Atomic sites (regardless of WordPress.com Editing Toolkit activated or not).

My testing on a .org self-hosted site with FSE Beta works fine and shows what's expected.

**Comment by cometgrrl** [comment]
@formosattic thanks for clarifying!

**Comment by creativecoder** [comment]
It look like this might be fixed now? Testing on a Simple site:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1699996/156256553-c7316764-f127-4971-a530-93bbaa187152.png">

**Comment by Addison-Stavlo** [comment]
Closing as it looks to be fixed while testing. Although please re-open if you still encounter this.
