### ISSUE TITLE
Plugin Details: Replace `author_link` with `author_profile` after adding missing fields in api endpoint

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#59571]
### Details
With the issue https://github.com/Automattic/wp-calypso/issues/59195 being merged in, we need to change the properties on the frontend as well.

We need to replace followings on frontend:

`author_link` -> `author_profile`

**Comment by cpapazoglou** [comment]
It seems that Calypso doesn't use `author_profile`. Or `author` related info are extracted from `author`
https://github.com/Automattic/wp-calypso/blob/28d742ee438b6d829599306cabc71f0a986ca96f/client/lib/plugins/utils.js#L172-L176
