### ISSUE TITLE
Navigation Block: Cannot Remove Menu Copies on non-FSE themes, wp_navigation not accessible

### ISSUE THREAD

**Issue by NoHopeRadio** [Automattic/wp-calypso#59595]
### Quick summary

When adding a menu to the navigation block, if you select a classic menu, it creates a new copy of that menu.

<img width="727" alt="Image of a Navigation Block showing two menu items followed by Classic option" src="https://user-images.githubusercontent.com/71042895/147598012-4df9044b-e117-437a-a655-2a7950bc9918.png">
<img width="571" alt="After selecting the option in the classic option, there are three identical menu options to select from" src="https://user-images.githubusercontent.com/71042895/147598052-6466a915-b335-42b6-92a7-f463bbae76d2.png">

If you want to manage menus to remove these extra copies, you are directed to the `/wp-admin/edit.php?post_type=wp_navigation` part of the site. On themes that are not FSE-capable, this will result in an error, "Sorry, you are not allowed to edit posts in this post type"

<img width="801" alt="Image showing error message: Sorry, you are not allowed to edit posts in this post type" src="https://user-images.githubusercontent.com/71042895/147598208-e8579759-7afc-49e6-88fb-8194ab9d30a5.png">

As such, the only way to remove these extra menu copies is to switch to an FSE-compatible theme and switch back.

### Steps to reproduce

1) Enable an older theme like Resonar
2) Create a menu
3) Add navigation block to page or post
4) Select a classic menu
5) Choose from menu options select Manage menus
6) See error after confirming a few dialogue boxes

### What you expected to happen

I expected some way to remove these extra menus.

### What actually happened

`/wp-admin/edit.php?post_type=wp_navigation` was not available until I switched to a newer theme.

### Context

4640652-zd
p2EDhh-1o5-p2

### Workaround details

Selecting an FSE-compatible theme enables this menu.

**Comment by kimerlin81** [comment]
@NoHopeRadio  - Thanks! I was able to reproduce this on simple and atomic sites.

**Comment by getdave** [comment]
Actually you can delete Menus from the Nav block interface. I've had this question a few times so I made [a video to document it](https://www.youtube.com/watch?v=cWd1EXYhMQY&t=60s).

**Comment by creativecoder** [comment]
Bigger picture, this needs improvement in Gutenberg, for example, see https://github.com/WordPress/gutenberg/issues/39489

But the immediate problem seems to be with the Calypso editor iframe, as I think it prevents navigating to the wp_navigation post management interface from the Site editor--this is something we need to fix on WP.com.

**Comment by getdave** [comment]
It could be improve yes, but Gutenberg actually provides the ability to manage these. Calypso isn't exposing the screen due to Nav Unification configuration. Suggest reaching out to someone who worked on that who works on Dotcom to get it fixed. 

Also there is a workaround - you can select the offending menus in a Nav block and then delete them as shown here.

https://www.youtube.com/watch?v=cWd1EXYhMQY

**Comment by ccwalburn** [comment]
Another report here: 34982755-hc
I showed them how to delete them one by one from the Nav block.

**Comment by Addison-Stavlo** [comment]
We did recently fix a bug regarding the "Manage Menus" button accessed here.

I am now testing on a classic theme and "Manage Menus" is bringing me to the wp-admin menus management screen with no access error (testing on Twenty Sixteen).

Can folks still reproduce this?

**Comment by creativecoder** [comment]
> I am now testing on a classic theme and "Manage Menus" is bringing me to the wp-admin menus management screen with no access error

Same for me (tested on a Simple site). Can now access `/wp-admin/edit.php?post_type=wp_navigation` coming from the Site editor.

**Comment by Addison-Stavlo** [comment]
Closing now as we can no longer repro after recent enhancements.
