### ISSUE TITLE
Calypso: Unable to install plugin from Plugins area

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#59607]
### Quick summary

Happens both on Simple site (when they are trying to install a plugin) and on AT site (when they are trying to install a plugin)

### Steps to reproduce

1. Go to Plugins: https://wordpress.com/plugins/DOMAIN
2. Choose the plugin you want to install
3. Click "Install and activate"
4. Page redirecting to https://wordpress.com/marketplace/PLUGINSLUG/install/DOMAIN?retry=1
5. Error "We're sorry, but an unexpected error has occurred"
6. Error on console: `TypeError: Cannot use ‘in’ operator to search for ‘id’ in undefined`

### What you expected to happen

For users to be able to install and activate plugins from Plugin section

### What actually happened

Errors

### Context

Customer report and HEs

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

For AT sites, we can install the plugins from CLI (from HE's end). For Simple site, we can AT-ed it first (using Jetpack Backup or Hosting Config, I guess?) then install the plugin from CLI.

A bit of note, @sirbrillig is updated on this as we feel this is related to this issue: https://github.com/Automattic/wp-calypso/issues/59605

**Comment by flameslash** [comment]
reporting for 4644200-zd-woothemes

**Comment by sirbrillig** [comment]
Hopefully will be fixed by https://github.com/Automattic/wp-calypso/pull/59608
