### ISSUE TITLE
Editor header: buttons background colors not following the color scheme

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#59617]
### Quick summary

The "Block inserter" and the "Publish/Update" buttons are not following the "dashboard color scheme" that is set under the account settings page (https://wordpress.com/me/account), and their background color is always pink (`#c9356e`) regardless of the color scheme that is selected: 

![Markup on 2021-12-29 at 16:48:17](https://user-images.githubusercontent.com/1046943/147679937-bb4c6454-216c-4e30-a377-85d0b091f198.png)

Please, note that the "Publish" button in this screenshot is disabled (with the proper color) but when it's active, it's pink.

![Markup on 2021-12-29 at 16:51:21](https://user-images.githubusercontent.com/1046943/147679992-866b599e-046d-4871-afaa-acff8f094750.png)

### Steps to reproduce

1. On a Simple or Atomic site, create a new page or post. 
2. Check the "Block inserter" or "Publish" button.

### What you expected to happen

Have both buttons the background color according to the color scheme selected on the account settings.

### What actually happened

The buttons are having a background button that looks is coming from the default color scheme.

### Context

Reported in chat here: 33400166-hc (follow-up on 4644942-zd-woothemes)

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by formosattic** [comment]
Looks like this is now fixed.

What I see with Classic Blue color scheme:
![image1](https://user-images.githubusercontent.com/15944096/148034245-b56f8bda-9e9b-496b-bf20-46bdfa12c15e.png)

Closing, but open if it happens again.
