### ISSUE TITLE
Videos UI: Include translations in wpcom.

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#59615]
For translated strings from the project `wpcom/video-courses` can be used from wpcom they must be added as a `supplemental_glotpress_project` here: `wp-content/lib/i18n-deploy/includes/projects/project-wpcom.php?r=228174#13`.

This was discussed here: p1640193144191700/1639754484.172000-slack-C02AED43D

**Comment by kwight** [comment]
D72326-code

**Comment by kwight** [comment]
Closed in D72326-code.
