### ISSUE TITLE
Marketplace: paid plugin details has broken ui when currency symbol is big

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#59628]

**Comment by gavande1** [comment]
### Details

The UI is kind of broken when there big currency symbol on the plugin details page and a `plan upgrade required` message needs to be displayed.

![](https://cldup.com/74V5j4Ipob.png)

**Comment by cpapazoglou** [comment]
I think that moving the `Plan upgrade required` to a separate line is the safest solution
<img width="368" alt="SS 2021-12-30 at 10 40 11" src="https://user-images.githubusercontent.com/12430020/147735580-9b517c17-6649-46b5-bd1a-00ee725d6767.png">
