### ISSUE TITLE
Show an upsell message or error when users embed custom code in simple site

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#59627]
### What

Users are not shown any message that custom code is stripped when they try to copy it. the result is just some awkward code appearing on the front end.

### Why

Simple sites do not permit custom embeds / scripts. 

User has suggested here that there should be an error message shown. I think it can be an interesting upsell opportunity

31193174-hc

**Comment by arinoch** [comment]
See also: #56742

**Comment by kerrynicl** [comment]
Closing in favour of [#56742](https://github.com/Automattic/wp-calypso/issues/56742)
