### ISSUE TITLE
Sidebar: Clicking site link at top of sidebar does nothing

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#5963]
@dcoleonline reported that clicking the home link in the sidebar doesn't work properly in Chrome.

![screen shot 2016-06-10 at 2 01 42 pm](https://cloud.githubusercontent.com/assets/1126811/15975627/f6cf7468-2f13-11e6-8eb8-6c09127d71d8.png)

@dcoleonline reported that he would get a modal when clicking the link in Safari.

![slack-imgs com](https://cloud.githubusercontent.com/assets/1126811/15975663/287e26a8-2f14-11e6-911f-a8b5848628ec.png)

But, when I tested with Safari `Version 9.1.1 (11601.6.17)`, nothing happened.

The only error I see in the console is this, which I don't believe is related.

![screen shot 2016-06-10 at 2 04 44 pm](https://cloud.githubusercontent.com/assets/1126811/15975680/539c1354-2f14-11e6-9a15-992d768cbf74.png)

**Comment by lamosty** [comment]
Thanks for reporting the issue. It was caused by my PR #5628. Sorry for the trouble, reverting it now.
