### ISSUE TITLE
Block color options cut off for right to left (RTL) languages

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#59646]
### Quick summary

If you select a right-to-left (RTL) language as your _Interface Language_, the user interface is horizontally flipped: elements which appear on the right are on the left, and vice versa.

In the block editor, after selecting a block with color controls, these settings are found in the left-hand side settings pane. However, the color options and the color picker dialog are completely cut off, as they default to expanding to the left (i.e. off the page).

### Steps to reproduce

1. In your account settings, change your _Interface language_ to an RTL language, such as Arabic.
2. Navigate to the block editor for a post or page on your site.
3. Click on a block with color controls, such as a Paragraph block.
4. In the block settings pane (now on the left), open the "Color" settings and click on one of the color options.

### What you expected to happen

The color settings should be fully visible and selectable. 

### What actually happened

The color selection and color picker dialogs expand out to the left, causing them to become partially inaccessible:

![color1](https://user-images.githubusercontent.com/5630717/147783396-c0777199-af74-4acc-99b7-1b0ee5e2b139.png)
![color2](https://user-images.githubusercontent.com/5630717/147783398-1a56376a-69b1-44ba-b62d-55272dde9fbc.png)

This is true regardless of browser zoom level. Only four "theme" colors are accessible, and the color picker dialog is effectively useless, with even the "advanced" option (hex codes) inacessible.

### Context

29968961-hc / 4648223-zen

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Tested on both Chrome and Firefox.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by kerrynicl** [comment]
Hi @jp-imagines . Can you confirm if this issue has been resolved on your testing site? I've tested with my own site and the user's and I was not able to replicate as the options load to the right of the setting pane
![RTL block options](https://user-images.githubusercontent.com/83325600/149764425-ca9c9a92-2287-4d31-8738-b276b774ffa4.png)

**Comment by jp-imagines** [comment]
@kerrynicl Looks like this has been fixed! I checked on my test account, and I'm seeing the same as in your screenshot now.

I'm following up with the original user now, and I'll mark this issue closed.
