### ISSUE TITLE
Marketplace: when rewinding use a hook to remove paid plugin if subscription is not currently active

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59658]
When a marketplace subscription has expired, and after say a day the user restores the site back to the date when they had the subscription (purchased via Dotcom Marketplace) active the plugin should not get restored.

**Comment by cpapazoglou** [comment]
Proposed solutions:
- by using a hook after rewind completes with success we can check for active subscriptions and remove the rest marketplace plugins

**Comment by gavande1** [comment]
Diff created: D72736-code

**Comment by gavande1** [comment]
Deployed r238080-wpcom
