### ISSUE TITLE
Marketplace: research a recommendation / search engine (eg algolia / Jetpack search )

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59671]
Adding some prior art 
p9xfpQ-gB-p2

**Comment by gcsecsey** [comment]
Find a solution that returns the most relevant products to the user, either from recommendations or search.

We could feed some preferences from the onboarding choices to the recommendation engine.

WC.com already uses algolia, which can serve a mechanism for both requirements. An added benefit of algolia is that it's completely hosted, and WC.com has already created some components to interact with its API. The question is whether we can find a better or cheaper alternative.

Jetpack search also has some extension to recommend plugins.

The research task consists of:
- [ ] finding out which parameters to feed to the recommendation/search algorithm
- [ ] deciding whether we can use algolia or something cheaper (maybe going through WC.com?)

**Comment by cpapazoglou** [comment]
Before diving into third parties, it might worth exploring an in-house solution that never made it to production
p9xfpQ-gH-p2

**Comment by cpapazoglou** [comment]
Jetpack Search related thread pdh6GB-kb-p2
Algolia related thread p6JqRr-5yD-p2

**Comment by gcsecsey** [comment]
I think we can close this ticket in favor of the Marketplace Search milestones: https://github.com/Automattic/wp-calypso/milestone/396
