### ISSUE TITLE
Marketplace: collect jetpack self hosted intentions to buy a plugin

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59670]
Jetpack self hosted users are not able to buy wpcom plugins yet. This a feature for the future 🤣! Right now we are blocking them with a message `This plugin is supported only in WordPress.com sites for the moment.`. It would be great if we could collect users intentions so that we target them when the feature is actually supported.

Can we say the following and add a check box so we have permission?

> Thanks for your interest. Paid plugins are not yet available for Jetpack sites. Please check the box below if you'd like us to keep you updated.

When we do the design, we can play around with how best to communicate this message (i.e. 'Please check the box below if you'd like us to keep you updated.' )

![SS 2022-01-03 at 16 23 30](https://user-images.githubusercontent.com/12430020/147941709-0373d751-0654-4abd-9c63-5de76f968cd6.png)

Related: https://github.com/Automattic/wp-calypso/issues/59232

**Comment by cpapazoglou** [comment]
A few options for us to consider.

Hide button and use a toggle to capture interest
![image](https://user-images.githubusercontent.com/1072756/148718243-de16488e-8c5b-48d5-80ea-7a906ef4c7e4.png)

Keep button but in a disabled state
![image](https://user-images.githubusercontent.com/1072756/148718256-f1cf0180-0e1f-4ca6-96b7-960af793e1f1.png)

Keep the button in an active state but show dialog on click. The only reason this is an option is that it may help to track more accurate purchase intent.
![image](https://user-images.githubusercontent.com/1072756/148718660-4dd75b9b-c929-45d3-adad-1730240feb88.png)

Personal opinion is option 2 as we could combine it with page views to gauge level of interest.

_Originally posted by @SaxonF in https://github.com/Automattic/wp-calypso/issues/59232#issuecomment-1008538010_

**Comment by WBerredo** [comment]
Design at: f84fqtCG4pCnCh2Hq0But5-fi-301%3A1775
