### ISSUE TITLE
Marketplace: When installing a free plugin, a Business monthly plan is being added  in checkout instead of annual

### ISSUE THREAD

**Issue by flameslash** [Automattic/wp-calypso#59696]
### Quick summary

If you are on a Premium plan or lower and try to install a free plugin, the Business plan upgrade added to checkout is on monthly instead of annual.

### Steps to reproduce

1. Open a site with Premium plan
2. Go to the Plugins Marketplace and select one of the free plugins (I selected Yoast SEO)
3. Click Upgrade and Activate
4. Business upgrade modal will show - click Upgrade and Continue

Video: https://d.pr/i/fHUMM4

### What you expected to happen

Business plan added to cart should be annual

### What actually happened

Business plan added is monthly

### Context

Discovered during call to testing

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by cpapazoglou** [comment]
👋 @flameslash! Thanks for testing this! Can you elaborate why the plan added to cart **should be** annual rather than monthly? The idea here is letting the user continue with a low upfront cost, after 1 month they can decide to renew to annual.

**Comment by cpapazoglou** [comment]
Let's add the Billing interval switcher to free plugins too.
https://github.com/Automattic/wp-calypso/blob/72ce1941439b08128fb68842f7524c152d2618a1/client/my-sites/plugins/plugin-details.jsx#L221-L230

Also, the redirect to checkout should respect the the billing interval switcher state here

https://github.com/Automattic/wp-calypso/blob/b16a0769a4d4df7c0656b9fbf830e489441579da/client/my-sites/plugins/plugin-details-CTA/index.jsx#L315-L322

**Comment by gcsecsey** [comment]
Currently on free plugins the billing period switcher isn't displayed.

| Free plugin | Paid plugin |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11555574/148384296-d090f920-a4b2-45d4-b413-b3af15bba91e.png) | ![image](https://user-images.githubusercontent.com/11555574/148384331-19105c01-cab5-41b5-85af-b0cc08783535.png) | 

We could add it to free plugin pages as well to streamline the billing period selection.
