### ISSUE TITLE
Modal to upgrade to Business plan could indicate the price and duration of the Business plan

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#59691]
### Quick summary

While on the premium plan, the modal to upgrade to Business could indicate the price of the Business plan being added. Indicate if the plan is monthly/annual

![Markup 2022-01-04 at 13 36 58](https://user-images.githubusercontent.com/21261509/148015767-c66f5120-5e71-4d77-a259-db060d7242ef.png)

### Steps to reproduce

1. Create/open a site on a Premium plan. 
1. Select a plugin from the **Plugins Marketplace**.
2. Click on '**Purchase and Activate**'
3. Can't see if the Business plan is monthly/annual and no price indicated on the modal.

### What you expected to happen

Show price and the duration of the plan inside the modal. 

### What actually happened

The price and duration of the plan are not shown. 

### Context

A potential improvement was discovered while team testing. 

### Simple, Atomic or both?

Simple

**Comment by obenland** [comment]
@SaxonF Is there any existing work that we could use as inspiration for how to display that pricing and term length information?

**Comment by allilevine** [comment]
Do we need the modal? The price is already in the CTA, could we add duration there?
<img width="334" alt="Screen Shot 2022-02-17 at 11 36 34 AM" src="https://user-images.githubusercontent.com/1689238/154528022-3c518de7-af60-4e93-bae0-0370175193b8.png">
Otherwise seems like a good, low impact fix we can ship to users.

**Comment by cpapazoglou** [comment]
This seems resolved now 

<img width="833" alt="CleanShot 2022-10-10 at 16 09 40@2x" src="https://user-images.githubusercontent.com/12430020/194873852-99716652-c4ad-4483-ace8-980d4f0ff653.png">
