### ISSUE TITLE
Sidebar: Preview screen nav menu incorrectly linking

### ISSUE THREAD

**Issue by AinslieK** [Automattic/wp-calypso#5970]
#### Steps to reproduce
1. Click preview link (directly under "My Site" in Calypso)
2. Select "blog" navigation menu item in preview (whichever page is set to recent posts)
3. This page will not display correctly in the preview, but displays correctly on the live site
4. Found on user site and then recreated on two test sites. Using the Libre theme.

#### What I expected
The recent posts page in the navigation menu of the preview page does not display correctly. All other pages display correctly when accessed through the nav.

#### What happened instead
Any page set as the recent posts page did not display correctly in the preview.

#### Browser / OS version
Chrome most recent

#### Screenshot / Video
This is what displays when you select "Blog" from the preview nav menu. This is the "About" page and is broken. You can see the sidebar at the bottom and the cut off comments box:

<img width="1240" alt="screen shot 2016-06-10 at 2 42 09 pm" src="https://cloud.githubusercontent.com/assets/13279752/15979572/a434c9aa-2f19-11e6-94ab-aa18172f1716.png">

**Comment by ehg** [comment]
Thanks!

Addressing this in D1998-code.

**Comment by lsinger** [comment]
Accepted the revision.

**Comment by ehg** [comment]
Deployed. Should be fixed now!
