### ISSUE TITLE
Tour Kit: Multiple custom CSS classes for each step

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#59710]
### Details

Until now, we could provide a custom CSS class (in the config) to be applied to a particular step or to the parent class under [config.options](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tour-kit/src/types.ts#L16-L18)
This could be improved giving the possibility to pass an array or CSV of CSS classes.

**Comment by chriskmnds** [comment]
Same also for the parent/frame class under `config.options`. 

Let's also bump the priority to `high` (and update the Project Thread P2 to move under ms 2).

**Comment by arcangelini** [comment]
[It looks like the `classnames` package we use for this already handles arrays being passed to it](https://www.npmjs.com/package/classnames#user-content-usage). Would this mean we just need to update the config interface to accept either/or ⇢ `className?: string | string[];` or is there a piece that I am missing.

Let me know and I would be happy to update this 👍 

<img width="901" alt="Markup 2022-01-13 at 17 23 48" src="https://user-images.githubusercontent.com/33258733/149368773-92476468-7cc8-4a5a-b53b-6ceb1437dd41.png">

**Comment by escapemanuele** [comment]
Thanks for researching on this @arcangelini! 😄 

I updated the issue, as we want to update the [parent optional CSS class](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tour-kit/src/types.ts#L16-L18) as well.

So, as you can see [here](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tour-kit/src/components/tour-kit-step.tsx#L28),  that frame CSS class is used for applying `[Frame Class]__step` classes to the single steps (as `wpcom-editor-welcome-tour__step` in your screenshot). I think that this would need some changes to work correctly 🤔 

Moreover, we should consider offering the possibility to add a CSV of classes ( like "class1,class2,class3" ), maybe the `classnames` package already supports that? Otherwise, we should see if we can do something on our side 😄
