### ISSUE TITLE
Plugin Details: show "Description" header tab only when there are more tabs

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59711]
In Plugin Details page we render the plugin sections like Description, Installation, FAQ etc.
When there is only a Description tab, the Header seems obsolete. 
Let's remove it.

![image](https://user-images.githubusercontent.com/12430020/148076179-05d2961c-1f0a-4af5-97e9-7b374adc61ea.png)

**Comment by gcsecsey** [comment]
Let's also remove the margin/padding below the tabs, when no tabs are displayed.
