### ISSUE TITLE
Videos UI: Consider removing the chapter animation when loading.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59729]
If only some videos have been completed, the chapters section will animate open on load. It can feel a little janky, but doesn't hurt anything – @ollierozdarz , any preference? Should we remove any initial animation on page load?

**Comment by ollierozdarz** [comment]
Good catch @kwight. 

> Should we remove any initial animation on page load?

Yeah, I think this would be the best solution and feel the least clunky. I was just playing around with it a little and the ideal scenario would be for it to be loaded with the next available chapter open.
