### ISSUE TITLE
Limited Atomic: Plugins page

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#59734]
### Details

A couple of issues here:

- [ ] The Calypso Plugins page should still be shown to premium plans on atomic, attempting to install a plugin should require a marketplace purchase or a business plan upgrade like normal (minus the AT step).
- [ ] The wp-admin plugin page should redirect to calypso when a user attempts to load the page on a premium atomic site.

**Comment by gavande1** [comment]
Related WPCOMSH PR: 811-gh-Automattic/wpcomsh
