### ISSUE TITLE
Seller Experience: Document how to create a new intent in the signup framework.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59737]
While we're adding a new intent for sellers, we can rely on the prior art of the Blogger Experience pod that created the Build and Write intents. Let's augment the existing Field Guide page with step by step instructions for adding a new intent to the "hero flow".

See: PCYsg-D3I-p2

**Comment by andres-blanco** [comment]
I've updated PCYsg-D3I-p2
