### ISSUE TITLE
Anchor: Signup from Anchor is broken.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59738]
Attempting to sign up for WordPress.com coming from Anchor is completely broken, showing a block error with a console message of `cannot set properties of undefined (setting 'anchorFmPodcastId')`.

<img width="1720" alt="Screen Shot 2022-01-04 at 2 10 28 PM" src="https://user-images.githubusercontent.com/349751/148130905-4c19be37-61ce-4dfd-9843-382fbaa135f5.png">

Reported by @hacchism in p1641247316007400-slack-C01FD4FGD7X

**Comment by sirbrillig** [comment]
Based on that error, this could be related to https://github.com/Automattic/wp-calypso/pull/59547 and this line: https://github.com/Automattic/wp-calypso/blob/f9a4773683019b3d52177a1a9dd4ac05acd4db58/client/landing/gutenboarding/hooks/use-step-navigation.ts#L78

**Comment by sirbrillig** [comment]
I believe this is fixed now but please re-open if the issue persists.

**Comment by kwight** [comment]
Yep, all good again – thanks @sirbrillig !

<img width="1271" alt="Screen Shot 2022-01-05 at 8 02 38 AM" src="https://user-images.githubusercontent.com/349751/148249104-4fc85507-e0d8-406c-8544-03911c0ac739.png">
