### ISSUE TITLE
Feature request: to be able to send out blog post emails based on category

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#59759]
### What

Users would like to send out default blog post emails (powered by Jetpack) based on categories.

### Why

Visitors don't want to receive all blog posts, rather only categories that they are interested in. At this time, it's not possible to achieve that using WordPress.com default emails, rather have to use a third-party service like Mailchimp and Mailerlite, which is cumbersome because emails have to be created manually.

### How

On the live site, there would be a dropdown that visitors can choose categories from, and admins can manage the list of subscribers and categories on Calypso dashboard.

**Comment by arunsathiya** [comment]
Requested here: 33490023-hc.

**Comment by Greatdane** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/59654
