### ISSUE TITLE
Marketplace: Paid plugins stats

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59752]
On the main plugins page (e.g., https://wordpress.com/plugins/), the Featured plugins (or so-called paid extensions) have low or no star ratings. On the other hand, Popular (or so-called free/ freemium plugins) have a higher star rating. Also, some plugins include the number of ratings and the number of installations, but those are missing for the Featured plugins. It would be great if we can have some consistency. Maybe we should remove the ratings altogether from all the plugins under the Featured list.

![image](https://user-images.githubusercontent.com/12430020/148204668-d66bfffd-8bfc-4e01-a992-33b62a421b2d.png)

WooCommerce Bookings has only two star ratings and also we cannot click the ratings to view who rated it.

![image](https://user-images.githubusercontent.com/12430020/148207341-8ae2b74a-df64-4e45-8cbc-bc9dbf277d9d.png)

related convo: pdtkmj-2M-p2#comment-76

**Comment by cpapazoglou** [comment]
@SaxonF maybe https://github.com/Automattic/wp-calypso/issues/43230 is more relevant than ever, could it be our magical solution here?

**Comment by SaxonF** [comment]
@cpapazoglou as mentioned in Slack I think for now we could remove ratings within the featured list as per you suggestion but keep them on the single plugin page. We should think more deeply about this as part of the featured plugin section iteration coming up.

**Comment by ianstewart** [comment]
Plus one on the short-term solution and long term suggestion @SaxonF .
