### ISSUE TITLE
Marketplace: live chat isn't supported on monthly plans

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59753]
The plugin details page mentions Live chat support 24 x 7 but the checkout page for the same plugin mention Customer support via email. This inconsistency can cause confusion for the user.

|Plugin Details | Checkout|
|-------|------|
|![image](https://user-images.githubusercontent.com/12430020/148205311-b1225690-bd5d-4c86-bf4d-67d097e82843.png)|![image](https://user-images.githubusercontent.com/12430020/148205475-05dc7e21-9f18-4a7d-b0bb-f70cb7be2cdd.png)|

related convo: pdtkmj-2M-p2#comment-76

**Comment by cpapazoglou** [comment]
In my opinion, whoever buys a plan & a marketplace product, they should get live chat support regardless of plan interval (monthly or annual).

In that case we should be adjusting the checkout usps to reflect that they will be getting live chat support on top of customer support via e-mail.

**Comment by cpapazoglou** [comment]
Discussed this again in a pod call, we will be offering only `Unlimited Email Support` for monthly plans - if user doesn't have annual plan they don't get live chat support. Let's update the plugin details page.

**Comment by cpapazoglou** [comment]
Reserved for onboarding

**Comment by epeicher** [comment]
This task will change the plugin details page. The related task #61207 will change the **checkout** page
