### ISSUE TITLE
Tour Kit / Welcome Tour: Extract pagination component into a package

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#59757]
### Details

The [pagination component](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/pagination.js) used in the welcome tour was borrowed/copied from the Gutenberg [Guide](https://github.com/WordPress/gutenberg/tree/4bbfbc13603d28fcc45368c529954164bf8581de/packages/components/src/guide) component (as per the comment in the file - verify) and is a fairly standalone component.

Let's extract it into a package with all the bells and whistles (types, storybook, themable, etc).

Note: ~this may migrate to "Tour Kit" before this extraction/packaging happens.~

### Checklist

Rough sketch:

- [x] Extract pagination into `packages/components` (but explore the possibility of `@wordpress/componens`)
- [x] Explore how it is currently being used, if any references need to be updated/created, if any other instances of similar page controls (@arcangelini 's explorations below)
- [x] Explore ways to make this "themable" e.g. with wpcom color variables when used/imported
- [ ] Add storybook demos
- [ ] Ensure typing
- [x] Update translation source (currently "full-site-editing")

**Comment by chriskmnds** [comment]
bumping this to `[Pri] High` cause we need this extracted and  cleaned up as part of the variant extraction.

**Comment by arcangelini** [comment]
I spent some time browsing around WordPress.com to see if there were other versions of the `. . .` page controls. It would be helpful to know all the areas where this could be utilized to help shape the package/component. Here is what I found:

### DotPager
This is a component this is strictly being used on the home page of WordPress.com as a slider for the content. [You can see the code for this *here*](https://github.com/Automattic/wp-calypso/blob/e2e9876c56a38ba83fb5d1a002bb117bd7c6aebf/client/components/dot-pager/index.jsx#L28). It seems like they bundled the dots into the same `ul` as the Next and Prev buttons. 

<img width="1084" alt="Markup 2022-01-20 at 11 15 27" src="https://user-images.githubusercontent.com/33258733/150319175-10468076-caf5-4855-8c9f-43231aa2ad05.png">

With that being said it seems like it could be helpful to make that an option as well? So the base return of the component will be just the dots, but you have the option to enable the arrow buttons `⇠  ⇢` and with that the option to enable the labels ` ⇠ Prev Next ⇢ `. This would make the component a match for two packages right out the gate. Do you think this is a good addition? @chriskmnds

**Comment by chriskmnds** [comment]
Nice finding @arcangelini ! Yes, the more we can abstract and reuse these things the better. We could also explore making these buttons customizable/replaceable I guess - since we also render back/next buttons at the same place? But small steps, could be a follow-up :-)

p.s. I think another option could be to also focus on Gutenberg and see if we can extract a component from Guide directly into `@wordpress/components`. You can check the Storybook demo for Guide [here](https://wordpress.github.io/gutenberg/?path=/docs/components-guide--default). It will probably be a slower process, but also great if we can contribute upstream in any sort of way. The downside is we may lose a bit of control, but if something gets released past "Experimental" then it's supposed to be stable, so less subject to changes. I don't have experience with this, but might be worth exploring a bit to see if potential. We can also nudge team IO for perspective 🤔

Either option should be fine though / good step! 😃

**Comment by arcangelini** [comment]
For the sake of getting this done sooner than later, I may stick with the original plan. Maybe if we get a good package built we could look on extracting it again and working for Gutenberg? It would be a double extraction haha

**Comment by arcangelini** [comment]
OK, the first PR is published and ready for review. I decided to break this into chunks, let me know your thoughts on this.

### PR 1

* Create the package with basic functions
* Update the Welcome Guide to use this new package and remove the original pagination

### PR 2

* Incorporate into DotPager
* Add storybook
* Add testing
