### ISSUE TITLE
Woo Installer: Industry Step

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#59766]
Create the about your business step in the new woo installer. seen in the original flow
![Screen Shot 2022-01-04 at 11 58 41 AM](https://user-images.githubusercontent.com/1035546/148240061-20ac0c37-809d-4550-8538-c6757c4d6143.png)

This component needs to:
- [ ] Show a list of industries so the user can select multiple ones.
- [ ] Save the user selection.
- [ ] Show the user selection when visited after the user have saved a selection (?).
- [ ] Let the user add its own industries using the "other" option with details.

This component also probably needs some design feedback @SaxonF.

Branch/Draft PR: https://github.com/Automattic/wp-calypso/pull/59826

**Comment by SaxonF** [comment]
@Rolilink some options for you

![image](https://user-images.githubusercontent.com/1072756/148727979-b2861add-944f-446d-8ded-8c16231e30e6.png)
![image](https://user-images.githubusercontent.com/1072756/148727991-89961ae3-6db8-4992-a862-ad93cf270bfb.png)
![image](https://user-images.githubusercontent.com/1072756/148727986-8a4f5be7-0961-46b2-a69b-4a4e4e53f0b0.png)

What Might be useful is if we build this out as a single checkbox component that can handle all variants e.g. via props like
- boxed (bool) that wraps the checkbox and label in a box. Use this when putting more emphasis on options e.g. during onboarding
- icon (element) that adds the icon to the checkbox and by default turns it into a boxed variant as seen in the screenshot above

**Comment by obenland** [comment]
Let's check with Zé from Woo how it's used and if this is strictly needed before moving forward.

**Comment by obenland** [comment]
Blocking until we learned about the above ^

**Comment by obenland** [comment]
@josemarques We're currently rebuilding WooCommerce's onboarding flow in Calypso to solidify WP.com customers' intent to create a store before moving them onto Atomic. Could you help us understand how the industry information is used and if it's strictly needed to be replicated in the Calypso version of that flow?

**Comment by josemarques** [comment]
@obenland this data should help to inform the next steps regarding features and which themes to suggest, although I'm not sure we're doing much with it atm. Regarding marketing it helps to target specific segments of merchants. 

pinging @pmcpinto that might provide better insights on why we ask for this data.

**Comment by pmcpinto** [comment]
Thanks for the ping.

>  although I'm not sure we're doing much with it atm.

Correct. Currently, we're only triggering 1-2 inbox notifications based on the industry. And this data point is also useful to understand the types of users who are starting a store with Woo. However, the degree of usefulness of this data point will probably increase in the coming quarters

**Comment by obenland** [comment]
Thanks so much! That sounds to me like we could probably launch without it for now?

**Comment by pmcpinto** [comment]
Yes
