### ISSUE TITLE
Investigate cart not updating post-checkout if using 3DS in signup

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#59773]
From https://github.com/Automattic/wp-calypso/pull/59746#issuecomment-1005966624

> I also tried a 3DS purchase from signup. The only odd thing I noticed is that the masterbar cart is full after navigating to the site dashboard from the page editor after checkout completes, and doesn't empty until I reload the page or rerender the masterbar (e.g. by hovering over or clicking on it). That's probably an issue for another PR.

**Comment by DavidRothstein** [comment]
Discussion: This is reproducible from the new site signup flow specifically.

**Comment by sirbrillig** [comment]
This is probably the same bug that caused me to revert the original masterbar cart PR. You can read about it here: https://github.com/Automattic/wp-calypso/pull/59732 I'm pretty sure [signup uses the site slug](https://github.com/Automattic/wp-calypso/blob/6319d8a6dd0186c53fc2055624291d32e8322f6a/client/lib/signup/step-actions/index.js#L479) and not the site ID for the cart.

> This is a second attempt at #58467 which was reverted because the mini-cart was using the site slug as the cart key for the shopping-cart manager, but the rest of calypso uses the site ID for this purpose. As a result, the cart manager thought there were two different carts. 

> In many cases this difference is not important because the server will treat them as the same and will return the same data, but if you modify the cart (eg: adding items or removing them), the cart manager for the site slug version of the cart _won't be updated_ until you reload the page (or otherwise trigger a fetch like by refocusing the window after a delay).

> That issue can make it appear that you have items in your cart when you do not, or that you don't have items in your cart when you do.

**Comment by sirbrillig** [comment]
I started trying to create tests to reproduce this bug in D72869-code but I'm a little stuck. If someone else gets to this before me, feel free to take over.

**Comment by sirbrillig** [comment]
It'd be nice if there was some way for the ShoppingCartManager to know that a site ID and its site slug are the same cart like the server does.

If the client fetches the cart using a site slug (ignoring the special slugs like `no-site` for the time being), then the returned cart will have the site ID in both the `cart_key` and `blog_id` properties of the response (at least in my testing; we should verify that this is true). So perhaps when the ShoppingCartManager could be aware that they are the same. I'll see if I can make that happen.

**Comment by sirbrillig** [comment]
This may be fixed by #60100.

**Comment by sirbrillig** [comment]
This might actually be a more fundamental issue of async payment methods and checkout thank-you pages: If you are directed to a thank-you page other than the pending page, then it's likely the next page will load before the purchase actually completes. Because of this, any data fetched by that page (eg: the cart) will not be aware of the completed purchase.

That said, I wasn't able to reproduce this specific bug in signup currently. There's a lot of UX that occurs before we are dumped into a calypso view that has a masterbar cart, so it may be that this is just a race condition that we're winning, but in any case I'm going to close this unless we can reproduce again.
