### ISSUE TITLE
Masterbar should probably not be visible on post-checkout pending page

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#59774]
Split from https://github.com/Automattic/wp-calypso/pull/59746

**Comment by DavidRothstein** [comment]
Note: This is specifically for the page shown after a pending payment (e.g. 3DS).

Discussion: Make it look the same as the checkout page bar, but without the X.

**Comment by nbloomf** [comment]
Here's a screenshot of what the page looks like with the masterbar:

<img width="992" alt="Screen Shot 2022-01-05 at 12 06 52 PM" src="https://user-images.githubusercontent.com/9310939/148978737-2e8f444f-d99d-4d48-9f2e-d2cd4aa278d6.png">

**Comment by DavidRothstein** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/45077 (which even has a design).
