### ISSUE TITLE
Cover block with Duotone filter doesn't show background image in Firefox

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#59777]
### Quick summary

On a site with the Barnsbury theme active, cover blocks with a Duotone filter don't show the background image in Firefox.

This is the cover block in the editor:

![Duotone 01](https://user-images.githubusercontent.com/4965723/148282075-f732175b-8763-477f-af79-4d4e0e55e632.png)

This is the cover block when viewing the page:

![Duotone 02](https://user-images.githubusercontent.com/4965723/148282128-2caea709-a95c-4041-92fd-a4fc578b9272.png)

 

### Steps to reproduce

1. Using Firefox, activate the Barnsbury theme.
2. Create a page.
3. Insert a cover block.
4. Select an image as the cover block background.
5. Set a Duotone filter on the cover block.
6. Preview or publish the page.

### What you expected to happen

The cover block should show the background image with a Duotone filter applied.

### What actually happened

The cover block shows a solid color background.

### Context

This was reported on 33497137-hc.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Barnsbury.

### Browser, operating system and other notes

The issue affects Firefox.

### Reproducibility

Consistent

**Comment by Greatdane** [comment]
Closing in favor of https://github.com/Automattic/themes/issues/5302
