### ISSUE TITLE
Manage Reusable Blocks causes Grey Screen of Death

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#59794]
### Quick summary

4659976-zen / 33326429-hc
Choosing `Manage Reusable Blocks` from the block options menu causes a grey screen of death with `<site> refused to connect`

https://user-images.githubusercontent.com/12906034/148331454-f5536af7-efe5-4ace-a9b0-26d3b6819462.mp4

Other methods of reaching the Manage Reusable Blocks page do not cause this issue.

### Steps to reproduce

1. Open a Post with a reusable post on the affected site.
2. Select the reusable block.
3. Select `Manage Reusable Blocks`

### What you expected to happen

User should be taken to the Manage Reusable Blocks page.

### What actually happened

User receives a grey screen of death with `<site> refused to connect`

### Context

Customer report. I was not able to reproduce on my test site.

I noticed that one of the user's reusable blocks itself contains a reusable block. In my testing I tried creating a reusable block within a reusable block in the same way, but I still could not reproduce the issue.

I didn't attempt to alter the user's reusable blocks in any way, as I'm not sure whether both versions of the reusable block are used somewhere on the site.

### Simple, Atomic or both?

Simple

### Reproducibility

Once

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

User can also access the Manage Reusable Blocks page from the settings menu from the three dots in the upper right corner or the Add Block plus sign in the upper right corner of the editor. Using these methods do not cause the issue.

**Comment by retnonindya** [comment]
So! The ticket reopened (4659976-zd-woothemes)

I'm interested in Michael's hunch here:
> I noticed that one of the user's reusable blocks itself contains a reusable block. In my testing I tried creating a reusable block within a reusable block in the same way, but I still could not reproduce the issue.

I understand the issue can't be reproduced -- but I feel Michael's hunch here is correct: Blockception is the cause.

I asked the user to either delete the problematic Reusable Block: "Join /Trips and Give /Give Now 2" or edit the said block by converting the Reusable Block INSIDE the block (I lost count of how many times I said "blocks" 🥲) to regular block (to avoid blockception.) 

I'm setting the ticket back to On-Hold.

**Comment by elazzabi** [comment]
Hello,

I can reproduce this issue, and I'm not using any blocks inside my block.

I'm using a custom domain on my site and using the `.com` editor. So my edit screen URL is something like: `https://wordpress.com/page/mydomain.com/2186`.

When I click on 'Manage Reusable Blocks', I get redirected to `the_site_name.wordpress.com.`, which is clearly not my custom domain. And the console shows:

```
Refused to display 'https://the_site_name.wordpress.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

I believe it has something to do with a custom domain vs default domain 🤔

**Comment by Greatdane** [comment]
Nice sleuthing @elazzabi ! 

I can also reproduce using a custom domain name, which looks to be the issue (same error message as above) - WordPress.com won't display the page (I guess for security reasons) as the domain names do not match.

**Comment by gius80** [comment]
@Greatdane  I don't think this is a domain issue. I suppose the problem here is that the url in  "Manage Reusable Blocks" button points to a `wp-admin` page (so not in calypso), which is a subdomain of wordpress.com, and because of the SAME ORIGIN policy, cannot be opened inside the iframe.

@cometgrrl

**Comment by chad1008** [comment]
I'm able to reproduce with and without a custom domain. I'm not seeing a connection to any of the recent Gutenberg releases, going back as far as 12.0

**Comment by mxhassani** [comment]
Another report here 34209686-hc

Opening the link in a new tab (with a middle mouseclick) didn't show any errors, both for the wp-admin and Calypso versions.  

Using `target="_blank"` on the links may solve this, and arguably make for a better feature (not having to close the current window)

**Comment by noahtallen** [comment]
This bit of code manages the reusable blocks href: https://github.com/Automattic/wp-calypso/blob/ecac55f67bc323bf52e8d40046d0e59c4b174f0d/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L764-L786

> the url in "Manage Reusable Blocks" button points to a wp-admin page (so not in calypso), which is a subdomain of wordpress.com, and because of the SAME ORIGIN policy, cannot be opened inside the iframe.

Interestingly, the code above is supposed to update the link to point to a Calypso page (iirc). Plus, the code does `hyperlink.target = '_top';` to make sure the link opens in the `wordpress.com` bit of the page. 

There are unfortunately a lot of places where this handling could be going wrong 🤔

**Comment by yansern** [comment]
The `moreMenuManageReusableBlocksObserver` is targeting the "Manage Resusable Blocks" link on the block sidebar, it doesn't target the menu item on the block toolbar.

This part in the iframe bridge server just needs add support for the menu item on the block toolbar.

**Comment by donalirl** [comment]
I'm experiencing this on several WordPress.com sites now (simple, not atomic.)
