### ISSUE TITLE
Editor: persist resume draft across sessions

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5979]
![resume draft](https://cloudup.com/c5TDm06rQXh+)

The "resume draft" feature is great. Can we make it persist across sessions? I think having a quick way to get back to your draft across sessions is where this actually shines the most. @aduth @mtias

**Comment by aduth** [comment]
I don't feel particularly strongly one way or the other, and I suppose it's a question of how much a permanent fixture do we want this button to be? The original intent was to be very much situationally relevant; that is, perusing the application after having started and saved a draft. Would increasing its duration help or hurt the likelihood that someone would click it and continue with their draft? Is it a pain point or failure of expectations that the button is not visible on later sessions?

**Comment by mtias** [comment]
I was thinking perhaps we can display the message when hovering the "new post" button after a session. That way you still have access to your most recent draft, but it's not always in your face.

- Permanently shown during a session.
- Shown on hover afterwards.

**Comment by rachelmcr** [comment]
There's now a persistent "Recent Drafts" dropdown next to the New Post button:

<img width="318" alt="screenshot 2018-01-02 16 01 06" src="https://user-images.githubusercontent.com/8658164/34501815-2ba06916-efd6-11e7-849c-ee184de68483.png">

I'll close this issue as this dropdown provides "a quick way to get back to your draft across sessions" as described in the original issue, but please reopen if you think we should consider doing more/persisting the "continue editing" message specifically.

#bug-scrub #pre-gutenburg-bug-purge
