### ISSUE TITLE
Editor Keeps Scrolling Up

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#59801]
### Quick summary

When you have a specific combination of blocks, you can't scroll down, once you do the page jumps up.

### Steps to reproduce

1. Create a new post
2. Add a Carousel block, select the Full Scroll variation when creating the block
3. Select some images, and choose the XL Size option in the settings
4. Add some Paragraph blocks under the Carousel block
5. Add a Spacer block at the end
6. Save the draft, close the editor
7. Open the draft in the editor again, and scroll down

### What you expected to happen

To be able to scroll down the editor.

### What actually happened

It keeps jumping up.

### Context

The Carousel comes from CoBlocks, it seems to be in some sort of conflict with that Spacer block at the end.

Reported on 33512532-hc

### Browser, operating system and other notes

I was able to replicate on Firefox, not Chrome.

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

User would need to use Chrome, or deactivate CoBlocks and use built-in gallery blocks, or a carousel plugin.

## User feedback

When this is fixed please let the user know at 4664512-zd-woothemes. They are aware this may take time to fix but asked we follow up when it does get fixed please.

**Comment by Greatdane** [comment]
Can confirm on firefox only.

Video;

https://user-images.githubusercontent.com/5075840/149272057-3dc7efbb-8af5-4a11-a8ae-d881b50a9d96.mp4

**Comment by cometgrrl** [comment]
Given that there are some simple workarounds, a lot of specifics required to hit this bug, I'm reducing the priority to low.

**Comment by Addison-Stavlo** [comment]
Unable to replicate, and this issue seems quiet. It seems like this has been resolved so im going to close.

**Comment by carinapilar** [comment]
> Unable to replicate, and this issue seems quiet.

@Addison-Stavlo, my guess is that since we have removed CoBlocks from WordPress.com, we shouldn't be seeing new reports - since it was a conflict between Gutenberg and the Carousel from CoBlocks.
