### ISSUE TITLE
Simple Sites Only: Unable to edit page/post that has no content

### ISSUE THREAD

**Issue by kimerlin81** [Automattic/wp-calypso#59805]
### Quick summary

When you create a new page or post where the content area is empty, you will not be able to load the page and edit it afterward.  This is currently only happening on simple sites.

### Steps to reproduce

1. Add new Page/Post
2. Insert a title
3. Save as draft or publish page
4. Click Edit page
5. Notice the page never loads (see video below)

https://user-images.githubusercontent.com/83732167/148384116-93317955-51c0-45f4-b02d-78cadcbae55b.mp4

### What you expected to happen

I expect the page to load the editor.

### What actually happened

The page never loads and the majority of it appears blank

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No, changing themes does not affect the end result.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Switching to WP-Admin view allows these pages/post to display as normal as shown in the video.
Alternately, they can add something in the content entry field like a period so that the page can load when editing.

**Comment by kimerlin81** [comment]
Affected user - 4664361-zd-woothemes

**Comment by marianearchimbaud** [comment]
I faced the same issue with this user 30018712-hc

**Comment by nickpagz** [comment]
Another report in 17636354-hc

Additional testing notes from a slack thread:
"It’s still happening on my test site as well, so definitely seems to be a different issue. It also seems the post or page can be published or draft, and have a page title - but as long as the content area is empty, the editor won’t load from calypso."

"Interestingly, adding any content fixes it, even if the content is then removed."

**Comment by ClassicRKR27** [comment]
Had another incident here where the Drafts were not visible until switching to Classic View: 33158110-hc

The issue is now resolved for this user.

**Comment by LauraSWP** [comment]
These users had similar issues and clearing cache fixed it:
- 28592169-hc
- 33516961-hc
- 33513649-hc

**Comment by mikeicode** [comment]
I’ve run into this on multiple sites today. I’m building new DIFM-L sites and start by creating blank pages. Then when I returned to edit the page it wouldn’t load. FF & Chrome. Tried clearing the cache in Chrome, no change.

**Comment by sguzovskaia** [comment]
Another one: 16272182-hc
Creating a new blank page or trying to edit the draft without content results in this bug.
Workaround in this case: creating another page with the Coming soon template worked.

**Comment by sguzovskaia** [comment]
4666024-zen
Site is on Business plan pre-Atomic: homepage without content is not opening to edit. Going AT resolved this.

**Comment by donalirl** [comment]
Seen in #33503649-hc / #4666467-zen Confirmed in Support Session. Clearing cache on user end did not help.

**Comment by arthur791004** [comment]
I'm sorry about this as I shipped https://github.com/Automattic/wp-calypso/pull/59525 yesterday to avoid the white screen between loading placeholder and loaded editor. However, it only works when the page/post is new (without title and content) or the page/post has any content. Otherwise, the page/post will keep showing the loading placeholder. I'll fix this issue soon 🙇

**Comment by arthur791004** [comment]
This issue should be fixed. Could you help me to check it, thanks!

**Comment by nickpagz** [comment]
@arthur791004 I'm on weekend so can't do much testing atm, but I tried again on my test site where I first tested this and it seems to be working now without any issues. Seems to be fixed now, though I've only tested on a simple site. Not able to test on Atomic atm.

**Comment by donalirl** [comment]
@arthur791004 It is indeed working again for the simple site case I reported - thank you!

**Comment by arthur791004** [comment]
Thank you for checking again 👍

**Comment by kimerlin81** [comment]
Update: Where this wasn't an issue affecting Atomic sites yesterday, it seems to now only be affecting Atomic sites. 
This issue is now fixed on Simple sites. I've confirmed by checking pages created yesterday on my simple test sites and on sites from various user reports. I also created new pages on Simple sites today (following the steps above) and they load fully after a slight delay.

**Comment by kimerlin81** [comment]
4666917-zd-woothemes reported, but when I just tested on their end this issue seems to be resolved.
However, I can still reproduce this on my Atomic test sites after clearing cache so I don't believe this is fully resolved.
I'm not sure why some Atomic users are not affected by this.

**Comment by fullofcaffeine** [comment]
It looks like it was indeed related to something in GB 12.2. After we upgraded WPCOM to 12.3, this stopped happening. 

> I can still reproduce this on my Atomic test sites after clearing cache so I don't believe this is fully resolved.
I'm not sure why some Atomic users are not affected by this.

Atomic sites didn't have GB 12.3 when you tested. It has been upgraded there recently. I tested again now and I couldn't reproduce, so everything looks good! I'll close this issue.

Thanks for the report and for following up on it, @kimerlin81!

**Comment by fullofcaffeine** [comment]
**UPDATE:** I spent some time trying to find the culprit for this issue and found out it's not related to Gutenberg, but was instead introduced [in this PR](https://github.com/Automattic/wp-calypso/pull/59525) and solved when @Addison-Stavlo [reverted](https://github.com/Automattic/wp-calypso/pull/59859) it earlier today. It's easily verifiable if you checkout 3624ae0393 locally, build Calypso, refresh and follow the steps to reproduce mentioned in this issue. 

More information in the following Slack thread: p1641580610027900/1641482343.001600-slack-CBTN58FTJ.

**Comment by arthur791004** [comment]
@fullofcaffeine Thank you for updating the status of this issue 👍
