### ISSUE TITLE
Videos UI: Long titles can be cut off.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#59808]
Video titles can be cut off, if long enough – which can happen with certain languages that tend to have more characters than English. A long English title can be made more concise in the management system, but this isn't an option for translations.

Reported by @emilyaudela in pdgK6S-jM-p2#comment-763

![long-titles](https://user-images.githubusercontent.com/349751/148393061-bb8ad474-8925-47bd-a832-9c17e06789fd.png)

**Comment by kwight** [comment]
@ollierozdarz How do you feel about multiple lines vs. the ellipsis approach?

**Comment by ollierozdarz** [comment]
@kwight, I think that will be fine 🙂

Here's what we can do:

<img width="429" alt="Screen Shot 2022-01-10 at 1 47 34 pm" src="https://user-images.githubusercontent.com/67085494/148716344-6c97c269-ddf4-47bd-8c0f-df6cee9c6509.png">


<img width="429" alt="Screen Shot 2022-01-10 at 1 47 43 pm" src="https://user-images.githubusercontent.com/67085494/148716365-2cec9dde-0576-4d31-bbde-c0e66a3b1298.png">

First image shows two lines of text. Second image shows two lines which are truncated (lets never show more than two lines).

**Comment by blackjackkent** [comment]
@kwight @ollierozdarz I've done a considerable amount of digging and CSS-wise, this is harder to achieve than it seems. The only reliable, cross-browser way that seems to be available is a mechanism that involves absolutely positioning the ellipsis at the end of the container. This works consistently, but does have the downside of adding some extra spacing depending on the length of the words involved.

Ex:
![image](https://user-images.githubusercontent.com/13437011/149217574-191ea11a-5035-4f04-b759-e4fe20bd37f8.png)

There are also a few Javascript packages available that can handle this use case, but I don't know if we want to add another dependency just for this purpose.

Thoughts?

**Comment by kwight** [comment]
Hm, I don't like the floating ellipsis effect myself (and adding a JS dependency seems like super overkill, particularly when we're actively trying to _minimize_ our deps in Calypso). I think I'd vote to just remove the ellipsis handling (so display the full title always), and leave it up to the judgement of the person managing the course to decide what a reasonable length title would be.

**Comment by blackjackkent** [comment]
> I think I'd vote to just remove the ellipsis handling (so display the full title always), and leave it up to the judgement of the person managing the course to decide what a reasonable length title would be.

OK, I've opened a PR with this approach at #60051 . (@ollierozdarz please let us know if you have any further thoughts on this. :) )

**Comment by ollierozdarz** [comment]
Thanks for the info @blackjackkent! 

> Hm, I don't like the floating ellipsis effect myself (and adding a JS dependency seems like super overkill, particularly when we're actively trying to minimize our deps in Calypso). I think I'd vote to just remove the ellipsis handling (so display the full title always), and leave it up to the judgement of the person managing the course to decide what a reasonable length title would be.

Yeah, the best CSS solution outlined feels a bit clunky, and probably not worth all the extra work. Let's just show the full title to the authors discretion.

**Comment by arthur791004** [comment]
I think we can just use the line-clamp property to do the multiline truncation with ellipsis. See https://css-tricks.com/almanac/properties/l/line-clamp/. If the browser doesn't support this property, then fall back to show the full title.

**Comment by kwight** [comment]
> I think we can just use the line-clamp property

Ooooh, great suggestion @arthur791004 ! @blackjackkent let's give it a shot, support looks fine these days.

**Comment by blackjackkent** [comment]
Updated #60051 to use the line-clamp approach. Thanks for the suggestion, Arthur! 😄
