### ISSUE TITLE
[Bug]: Hello! The write post button isn’t working https://wordpress.com/read 

### ISSUE THREAD

**Issue by backwardstruck** [Automattic/wp-calypso#59830]
### Quick summary

The write post button isn’t working for me on https://wordpress.com/read 

@astralbodies was also able to confirm.

It's happening on Chrome and Safari so far. With AutoProxxy turned on.

If I right click and open the link in a new tab (while hovering over the button) I can still get to the form. So the Gutenberg editor is still fine. It looks like the button itself is broken. It's also not showing my drafts count.

<img width="169" alt="Screen Shot 2022-01-06 at 4 44 45 PM" src="https://user-images.githubusercontent.com/947561/148456430-4b1784a3-eeb6-4cdd-bb9d-06b5936aa402.png">

### Steps to reproduce

1. Be on Autoproxxy
2. On Chrome or Safari go to https://wordpress.com/read
3. Log in if necessary
3. Click on the `Write` button on the upper right

### What you expected to happen

It should open up the new post form with Gutenberg editor:
https://wordpress.com/post/

### What actually happened

Nothing :(

### Context

Happened when I was trying to draft a post on P2

### Browser

Google Chrome/Chromium, Apple Safari

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

You can go to this link directly, but you need to know to right click to get there:
https://wordpress.com/post/

**Comment by worldomonation** [comment]
I attempted to reproduce this.

Browser: Google Chrome 97.0.4692.99
Autoproxxy: 1.9.0

There are two scenarios as far as I can tell - accounts with only one site, and accounts with multiple sites.

## Single site

https://user-images.githubusercontent.com/6549265/151086711-45b3ee1d-2d4c-4562-a982-9201b16a1f54.mov

## Multiple site
https://user-images.githubusercontent.com/6549265/151086583-dc03a666-93c6-4ea1-81d4-f398da22c838.mov

In both cases, clicking on the `write` button eventually took me to the editor. For multi-site account there was an intermediate step where I was asked to select the target site.

**Comment by cometgrrl** [comment]
@backwardstruck Can you see if this is still reproducible for you? If so, we'll need more details, as it's working for us.

**Comment by backwardstruck** [comment]
Hi! Thank you for looking into this issue. I feel like it was still
happening last week but I just tested again. It seems to be working fine
now. Feel free to close the ticket.
