### ISSUE TITLE
Woo Installer: Address Step - Add Country/Region Dropdown

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#59833]
<img width="647" alt="Screen Shot 2022-01-06 at 4 15 25 PM" src="https://user-images.githubusercontent.com/1035546/148460619-83187363-c0be-47cd-8bac-c521b61c2fda.png">

- [ ] Country dropdown should show both country and region like in the original wizard.
- [ ] It should save `woocommerce_default_country` as a `country_code:state_code` pair.

related convo: p1641503438069500-slack-C029UPVMGTW

**Comment by obenland** [comment]
Fixed in #59876.
