### ISSUE TITLE
Limited Atomic: Ensure downgrade path from business to premium works smoothly

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#59835]
Ensure downgrade path from business to premium works smoothly as HE's will need this option

**Comment by zdenys** [comment]
In 4851556-zd-woothemes the customer would have benefited from a self-serve option to downgrade from Atomic Business Plan to Premium Plan.

**Comment by obenland** [comment]
Closing this as there is no specific action that needs to be taken for this one. The downgrade routine in D81926-code will enable a smooth downgrade from any plan.
