### ISSUE TITLE
Multiple themes: Spacer block crashes

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#59846]
### Quick summary

The "Spacer" block crashes on adding to a page or post with Hemingway Rewritten theme.

### Steps to reproduce

- Start with a WordPress.com site.
- Activate Hemingway Rewritten theme on it.
- Create a page or a post.
- Add a "Spacer" block.
- See that it crashes on adding to the page/post.

### What you expected to happen

The block does not crash.

### What actually happened

The block crashes. 

<img width="982" alt="image" src="https://user-images.githubusercontent.com/18581859/148529617-d3abe275-28b2-4753-88d2-9ddddece738e.png">

The console reads:

```
TypeError: Oe.useSetting(...).filter is not a function
```

### Context

Customer report: 4666985-zen.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Hemingway Rewritten

### Browser, operating system and other notes

- All browsers, OS.
- This happens only on Simple, **not on Atomic**.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No and the platform is unusable

**Comment by marutim** [comment]
I can replicate the same issue with Dara theme. 

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/3498917/148535376-5169d538-f426-4b71-b839-dbbf8a919e7a.png">

**Comment by samvaidya** [comment]
Another user reporting this issue on the Hive theme (retired).  

Follow-up ticket:  4668513-zen

**Comment by hacchism** [comment]
Another user reporting this on the Gateway theme.

Follow-up ticket: 4669094-zen

Also, I've set this as a High priority considering the impact on users(Followed the chart in p7DVsv-d1T-p2)

**Comment by edwinho89** [comment]
33345583-hc . User is on AT site, and using Apostrophe 2 theme. 

I'm able to reproduce this on my test AT site, using Storefront theme as well.

Deactivating Gutenberg (currently v12.3.0) plugin on both AT site does fix the issue.

**Comment by sarahcada** [comment]
Listing reports from #59855:

28311339-hc: Libretto theme. Simple site only.
335393000-hc: 3rd-party theme, and on a test Atomic site (retired Patch theme), reported by @thekingsprojects 
32466914-hc: Ixion, reported by @allanftd

**Comment by sarahcada** [comment]
A couple more reports: 
4669149-zd-woothemes: Corporate (retired) theme
4669612-zd-woothemes: Suits (retired) theme

**Comment by filipanoscampos** [comment]
Another report here: 4660627-zd-woothemes.
The user is using a retired Premium theme, Photographer.

**Comment by mrsjaved** [comment]
Another report here:
4669949-zd-woothemes

Using Plane theme.

**Comment by susanjanec** [comment]
Another report in 4666823-zd-woothemes

Using Twenty Fifteen theme

**Comment by synora** [comment]
Another Atomic site report: 4670442-zd-woothemes
Using the Bloggy(retired theme)

**Comment by nickpagz** [comment]
Simple site, Rebalance theme. 4670402-zen

**Comment by suyogyashukla** [comment]
Another report in 4670108-zen, multiple sites. Themes: Redhill and Gateway and Shoreditch.

**Comment by masperber** [comment]
33549426-hc. AT site, Radcliffe 2 theme

**Comment by khristiansnyder** [comment]
#33553316-hc 
At 
Twenty Fourteen

**Comment by syedshaon** [comment]
#4671099-hc
Nikau Theme

**Comment by retnonindya** [comment]
4667552-zd-woothemes
Theme Beacon (retired Premium theme)

**Comment by syedshaon** [comment]
#4671247-zen
Theme: Attache

**Comment by dolgelukkig** [comment]
Simple site
4666321-zen
Theme: Twenty Twenty-One

**Comment by wprhunt** [comment]
Simple site
4672889-zen
Theme: Apostrophe2

**Comment by KirkwallDay** [comment]
Another instance here: 33565797-hc
Atomic
Theme: Twenty Seventeen

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/this-block-has-encountered-an-error-spacer-block-only/

Simple site
Theme: Dara

**Comment by jordesign** [comment]
Also reported in 4672183-zd-woothemes
Simple site - Canard theme

**Comment by kathrynwp** [comment]
Another report in 4673087-zen

Simple site, Moka theme

**Comment by kathrynwp** [comment]
Another report in 33260326-hc 
TwentySixteen theme - Simple site

@NoHopeRadio - moved here from #59855 since that was closed as a dupe!

**Comment by ramonjd** [comment]
Hmm, it looks like this PR will address the issue based on the reported JS error:

https://github.com/WordPress/gutenberg/pull/37774

**Comment by jordesign** [comment]
Thanks @ramonjd  - just noting the Gutenberg Issue for our reference to track as well.
https://github.com/WordPress/gutenberg/issues/37758

**Comment by thebud15** [comment]
Came up in #33569153-hc
Simple site
Theme: Radcliffe 2

**Comment by formosattic** [comment]
+1 26384477-hc
Simple site
Theme (retired): Romero

**Comment by inaikem** [comment]
User report in 4674003-zen (Twenty Thirteen).

Confirmed as  affecting the following themes:

- Twenty Eleven
- Twenty Twelve
- Twenty Thirteen
- Twenty Fourteen
- Twenty Fifteen
- Twenty Sixteen
- Twenty Seventeen
- Twenty Nineteen
- Twenty Twenty

I reported in #59896 before being pointed here.

**Comment by NatzJoy** [comment]
Another report in 33575341-hc

Atomic site using the Stratford theme.

**Comment by kingsleyinfo** [comment]
I just came across this bug and was able to replicate it on my own site. However, adding the Spacer block when the block settings toolbar is not toggled does not throw an error
Recording here: 

https://user-images.githubusercontent.com/12503321/148760673-2ffcafec-6b62-4d9d-878e-7db8d75eb720.mp4

+1 33316541-hc

**Comment by dragstor** [comment]
Reported by the user from 33402750-HC as well.

I suggested the workaround by @kingsleyinfo :)

**Comment by ccwalburn** [comment]
Another report here 33578535-hc
Deactivating Gutenberg fixed it for this user.
Atomic Site using Baskerville 2 child theme

**Comment by rachelwinspear** [comment]
Simple site: 27630439-hc
Theme: Hive - Retired.

**Comment by nickpagz** [comment]
Atomic, dyad 2 child theme. 33497028-hc

**Comment by cuemarie** [comment]
Simple site: 30043802-hc
Theme: Nikau (Retired)

**Comment by jackiejade** [comment]
Another: 32613955-hc
Theme: Twenty Sixteen

**Comment by maciejpilarski** [comment]
Another: 4674255-zd
Theme: ZoxPress

**Comment by fullofcaffeine** [comment]
This should be fixed in Gutenberg 12.3.2, which has just been released on WPCOM.

**Comment by inaikem** [comment]
Thanks @fullofcaffeine. 

Cc @Automattic/dotcom-pa-group to start the bulk reply process 🙏

**Comment by inaikem** [comment]
Via @formosattic: 4676893-zd-woothemes

**Comment by Thelmachido** [comment]
Another report here: 33598836 -hc

**Comment by edwinho89** [comment]
4673091-zd-woothemes

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
