### ISSUE TITLE
Spacer block not working on sites using multiple themes

### ISSUE THREAD

**Issue by allanftd** [Automattic/wp-calypso#59855]
### Quick summary

When adding a Spacer block on pages or posts of sites using Ixion theme, it displays an error "This block has encountered an error and cannot be previewed."

32466914-hc

### Steps to reproduce

1. Edit a page or post
2. Add a Spacer block
3. The error message "This block has encountered an error and cannot be previewed." shows up where the Spacer block was added. There's no way to adjust the height of the spacer.
4. When previewed on a new tab, the error does not show up and a space is added as expected.

### What you expected to happen

I expect the Spacer block to be added in the editor and spacer height should be adjustable.

### What actually happened

The error message "This block has encountered an error and cannot be previewed." shows up where the Spacer block was added. There's no way to adjust the height of the spacer.

### Context

I was able to reproduce this on my own test site using Ixion theme. I tried using a few other themes and I was not able to reproduce the error.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Ixion

### Reproducibility

Consistent

**Comment by thekingsprojects** [comment]
Another case here: 335393000-hc (3rd-party theme), and on my test Atomic site (retired Patch theme). When I switched to Quadrat Green on my test site they seemed fine, though. So it seems like it affects more than just Ixion, but not every theme.

User has a workaround of their own (Elementor includes some spacer blocks that mostly work) for the time being.

**Comment by sarahcada** [comment]
Another case at 28311339-hc (Libretto theme). I was able to replicate on my Simple test site, but not on Atomic. It seems that this may be limited to just Simple sites.

**Comment by sarahcada** [comment]
Closing this in favor of #59846

**Comment by NoHopeRadio** [comment]
Another report in 33260326-hc (TwentySixteen theme) Business plan, not atomic.

**Comment by kathrynwp** [comment]
Another report in 4673087-zen

Simple site, Moka theme
