### ISSUE TITLE
Kingsley theme: Updating failed: Invalid parameters template

### ISSUE THREAD

**Issue by carladoria** [Automattic/wp-calypso#59865]
### Quick summary

User in 4659213-zd-woothemes doesn't like the gap that shows in between their menu and the homepage content as seen in blue in 
![Markup 2022-01-07 at 11 54 05](https://user-images.githubusercontent.com/23703267/148585127-4f2580c2-02ba-40ea-bcd3-7d65d3834957.png)
The theme's demo PdAUX2-2-p2d doesn't show it since it is using a Footer only template. The spacing seems to be a block template by using the browser inspector. We pointed to switching templates, but they get an error "Updating failed: Invalid parameters template" I was able to reproduce this in a test site with the same theme. 

### Steps to reproduce

1.  Activate Kingsley theme on a test site
2.  Set up a static front page
3. Go to templates inside the homepage and change to "Footer only" template. 
4. You will see error "Updating failed: Invalid parameters template"

### What you expected to happen

To be able to change to the footer only template so they avoid that space gap at the top

### What actually happened

You can't change to the footer only template, only the default one. 

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Kingsley

### Browser, operating system and other notes

Chrome

### Reproducibility

Consistent

### Workaround details

You could remove that gap with CSS but user is on Personal plan.

**Comment by Robertght** [comment]
I tried to replicate this but I wasn't able to, however, I noticed this issue: https://github.com/Automattic/wp-calypso/issues/59570 which was already fixed a few days ago.

Note: I have tested this with FSE on and FSE off and I couldn't see the error.

If there are more reports, please reopen the issue.
