### ISSUE TITLE
Blockbase and its child themes: Color Customization not saving

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#59886]
### Quick summary

Color Customization cannot be saved in Customizer for Blockbase and its child themes

https://user-images.githubusercontent.com/39308239/148636501-68e7f309-0936-4d06-9cee-e10a2df1be57.mov

### Steps to reproduce

1. Activate Blockbase or any of its child theme (Zoologist)
2. Visit My Site → Appearance → Customize → Colors
3. Change any of the colors (Primary, Secondary, etc.)
4. Click `Save Changes`

### What you expected to happen

Changes should be saved.

### What actually happened

The following messages appear:

```
Looks like something’s gone wrong. Wait a couple seconds, and then try again.
```

By the way, notice that `of` is missing after the word `couple`. It should be `a couple of seconds`.

```
The previous set of changes has already been published. Please try saving your current set of changes again.
```

![image](https://user-images.githubusercontent.com/39308239/148636455-0675a770-7b14-4b7c-930b-4985b7c50e4b.png)

### Context

Customer report: 4667485-zd-woothemes

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Blockbase and its child themes

### Browser, operating system and other notes

macOS BigSur 11.6 with Chrome 97

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by Robertght** [comment]
Thank you for reporting this @zdenys !

I have pinged here as well for a second look: p1641628637072800-slack-C0113HTN28N

**Comment by zdenys** [comment]
The most recent intervention around the same issue is this one https://github.com/Automattic/themes/issues/5001 or maybe this one https://github.com/Automattic/themes/issues/5261

**Comment by syds87** [comment]
Another case with the same issue on Quadrat theme was reported in #4669592-zd

**Comment by Gustavo-Hilario** [comment]
Another report here using the `Quadrat Black` theme: 4668262-zd-woothemes

**Comment by thekingsprojects** [comment]
Another case with Quadrat here: 33552853-hc

Was able to give the user a CSS workaround for now.

**Comment by khristiansnyder** [comment]
Another case in #4669301-zen.

Console error has:` Failed to load resource: the server responded with a status of 500 ()`

**Comment by aleone89** [comment]
To note, users experiencing this issue here: https://github.com/Automattic/themes/pull/5262 (WSOD) when FSE, would need to save fonts in the customizer in order to get FSE working on their site, this particular bug would hinder the above fix.

**Comment by nicolynramos** [comment]
Another case on 4682409-zen on Zoologist theme, however, no error message is shown- changes are made but do not save. User would also like to be notified if a fix is put in place.

**Comment by Greatdane** [comment]
Another: 4680383-zd-woothemes

**Comment by scruffian** [comment]
This should now be fixed

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by ewebber** [comment]
This is happening to me today, I cannot update the font or colors. Custom CSS says it's not updating but it is intermittently.
In Blockbase / Gutenberg / WordPress 5.8.3 
![Screenshot 2022-01-17 at 11 51 56](https://user-images.githubusercontent.com/1002019/149764889-ad957789-7823-4197-8ae8-178eb2b0bd4d.png)

**Comment by scruffian** [comment]
@ewebber what site is this on?

**Comment by ewebber** [comment]
Hey @scruffian it's a new site and not ready to share publicly, can I send you the link privately? Thanks.
