### ISSUE TITLE
Marketplace: don't query the product list on every navigation

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59899]
Navigating in Plugins Browser and any Plugin Details initiates a new network request to the product list. These requests seems to be using enough resources 

size: 14kb (and it will soon get bigger by adding more products)
time: 1.3s - 1.6s for me  (and it will soon get bigger by adding more products)

https://github.com/Automattic/wp-calypso/blob/39be4be432483bd2e9b3172bb6f6de9e7fc048e8/client/my-sites/plugins/plugins-browser/index.jsx#L219

https://github.com/Automattic/wp-calypso/blob/1949d94f805a46f9d7fc52d8fb7ba5bfb872e0e4/client/my-sites/plugins/plugin-details.jsx#L220

![SS 2022-01-10 at 11 17 18](https://user-images.githubusercontent.com/12430020/148742856-dd37d539-47bd-47ec-adc3-f52b6b5b0fcc.gif)

**Comment by gcsecsey** [comment]
I've opened a discussion about the caching strategy [in this P2 thread](p7H4VZ-3lT-p2).As a temporary solution, I'm raising a PR which just avoids re-fetching the data on each page load by utilizing the Redux store.
