### ISSUE TITLE
Add Field guide page for woo on plans

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#59891]
We need to document how the the woo installer works in the FG. (what endpoints, what code)

We should also document tracks events and funnels we use to track woop metrics.

e.g. https://wp.me/PCYsg-CqB

**Comment by allilevine** [comment]
I started documenting woop metrics here: PCYsg-Ega-p2

**Comment by obenland** [comment]
Discussed with @ianstewart, let's consider PCYsg-Ega-p2 as completing this task.
