### ISSUE TITLE
Marketplace: place currency symbol as prefix for INR currency

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#59902]
The currency symbol is displayed as a suffix instead of the prefix for INR currency.

Before: 
![](https://cloudup.com/cMkLGUjePqk+)

Desired:
![](https://cloudup.com/cqqhe8edvKU+)

**Comment by cpapazoglou** [comment]
@michaeldcain do we support prefixing with the symbol for certain currencies?

**Comment by michaeldcain** [comment]
Thanks for flagging this. I've created a patch to update the INR currency format in D73674-code

**Comment by michaeldcain** [comment]
Fixed:
<img width="1083" alt="Screen Shot 2022-01-24 at 5 12 42 PM" src="https://user-images.githubusercontent.com/942359/150873673-184d0112-c229-4faa-8985-542c209d98c1.png">

**Comment by cpapazoglou** [comment]
My original question didn't mean to put you in the spot 😅..
Thanks a ton @michaeldcain!
