### ISSUE TITLE
Investigate woo transfer failures

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#59926]
There is a significant portion of users who successfully kick off a transfer or install process but never reach the wc admin setup wizard.

Determine:
- Is the wc admin setup wizard always being shown?
- Is there any errors in the install / transfer flow?
- Is there a difference between drop offs on transfer vs install?

Note there is no major warning signal in the `calypso_atomic_transfer_inititate_failure` and `calypso_atomic_software_install_inititate_failure` failure modes.

I suspect we might need new event tracking to figure out where the issue is.

- [ ] Determine the problem (if there is one)
- [ ] Add finer grained logging / tracking to help understand the issue

**Comment by DustyReagan** [comment]
Possibly related issue: p1642601539457200-slack-C029UPVMGTW

**Comment by obenland** [comment]
Define done:

- [x] Add tracks event for hit a snag
- [x] Add tracks event for about to redirect
- [x] Add tracks event for wc-admin loading (if there isn't one we can use)

**Comment by allilevine** [comment]
> Possibly related issue: p1642601539457200-slack-C029UPVMGTW

Opened https://github.com/Automattic/wp-calypso/issues/60318

**Comment by Rolilink** [comment]
To track the `wc-admin` loading we can use the `wcadmin_page_view` event with the path attribute being `home_screen`.
