### ISSUE TITLE
2FA: Intermittent `the server responded with a status of 403` upon entering TOTP code.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#59923]
### Quick summary

This is an issue that is intermittently observed on the P2 E2E tests against production.

### Steps to reproduce

1. navigate to `/log-in`.
2. enter credentials to log in as `p2User`.
3. using the TOTP secret key under the key `p2UserTOTP`, generate a code.
4. enter the code.

### What you expected to happen

`p2User` is permitted to log in.

### What actually happened

Login attempt is rejected with an error message on the frontend:
```
Hmm, that's not a valid verification code. Please double-check your app and try again.
```

### Context

Automated end to end tests.

### Other notes

Console logs:
```
Failed to load resource: the server responded with a status of 403 ()
wp-login.php?action=two-step-authentication-endpoint:0
```
Response headers:
```
Response Headers
server: nginx
date: Wed, 05 Jan 2022 18:01:20 GMT
content-type: application/json; charset=UTF-8
vary: Accept-Encoding
vary: Origin
x-hacker: If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.
host-header: WordPress.com
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
set-cookie: wordpress_test_cookie=WP%20Cookie%20check; path=/; domain=.wordpress.com; secure
x-frame-options: SAMEORIGIN
access-control-allow-credentials: true
access-control-allow-origin: https://wpcalypso.wordpress.com
content-encoding: br
x-ac: 2.dfw _dfw
strict-transport-security: max-age=15552000; preload
```

Response body:
```
{
  "success": false,
  "data": {
    "two_step_nonce": "b8a6eee4f0f21cf6e735878351866039",
    "errors": [
      {
        "code": "invalid_two_step_code",
        "message": "Hmm, that's not a valid verification code. Please double-check your app and try again."
      }
    ]
  }
}
```

The request and response body can be observed by downloading [this file](https://teamcity.a8c.com/repository/download/calypso_P2E2ETests/7205331:id/trace/p2-post-log-in.zip) then uploading the downloaded trace file to https://trace.playwright.dev/. Please note, the trace file contains usernames and passwords used by the test user.

### Reproducibility

Intermittent

**Comment by worldomonation** [comment]
This appears to be related to #59211.

#59211 also arose from automated P2 E2E tests.

**Comment by worldomonation** [comment]
As far as I can tell, the TOTP setting used by `@automattic/calypso-e2e` which derives from [TOTP-generator](https://github.com/bellstrand/totp-generator) is as follows:
- 30 second interval
- `Date.now()`

The secret is stored as an alphanumeric string in lowercase letters.

I think this eliminates the possibility that:
- the token is generated using wrong interval
- token is expired due to wrong timestamp

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

See discussion here: https://github.com/Automattic/wp-calypso/issues/59211#issuecomment-1642688434

**Comment by worldomonation** [comment]
Oh dear, did I file two issues within a month of each other? 😬
