### ISSUE TITLE
Marketplace: Make sure we are fetching / showing the latest data from woocommerce.com

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59938]
[Subscriptions extension](https://woocommerce.com/products/woocommerce-subscriptions/?quid=006223cb39b0c2ae5526ae8b4710a712) used to contain the following text
> Need any more reason to buy? Subscriptions is built by Prospress, a leading WooCommerce.com Extension developer, so you can trust you’re getting high quality code backed with first-class support.

The text has been removed from the [woocommerce.com](https://woocommerce.com/products/woocommerce-subscriptions/?quid=006223cb39b0c2ae5526ae8b4710a712) page but it still displays in [wordpress.com](https://wordpress.com/plugins/woocommerce-subscriptions). The reason is that we are caching the `description` both in 

WPCOM (1d)
```
// if description is available then cache
if ( $description ) {
  wp_cache_set( $key, $description, '', DAY_IN_SECONDS );
}
```

and Calypso (1d)
https://github.com/Automattic/wp-calypso/blob/c568872778f1e1cae7537cae7c9d21caa842ef9e/client/data/marketplace/use-wpcom-plugins-query.ts#L36

since caching non-critical data (eg we are not caching the price) for 1d seems logical to me to either:
- wait (max 2d) for cache to clear
- implement a cache busting strategy

**Comment by gcsecsey** [comment]
I think that as a simpler solution, we could also set lower stale times (eg. 6 hours) to make sure that even non-critical data is updated more regularly. This may not be an option, though, if the woocommerce.com API's usage limits don't allow it.

On implementing a cache busting strategy, I think we would need to re-fetch the query only when a particular set of the non-critical fields are updated (description, rating, etc.). I don't think we could implement this dynamically, at the very least a timestamp should be added separately that stores when the data was last updated. We could then use this timestamp value in both cache keys to determine whether to re-fetch the original query.

**Comment by cpapazoglou** [comment]
Demoting this to normal as:
- WPCOM cache has already cleared `https://public-api.wordpress.com/wpcom/v2/marketplace/products/902` 
- Calypso cache impacts only users who have already seen that text which got cached. Deleting the `query-state-[siteId]` from the indexed db results in fetching the new (updated) data
![SS 2022-01-11 at 15 41 20](https://user-images.githubusercontent.com/12430020/148953359-9ccb206f-e7f5-4c48-aca7-2ee221102785.png)

**Comment by cpapazoglou** [comment]
- There is a mechanism to delete the cache in the backend by `wp_cache_delete` the appropriate key that can be triggered manually. Let's also create a marketplace CLI tool that clears the cache for a given plugin slug or all
- We can lower the Calypso cache stale time to 2h

**Comment by JulianBustamante** [comment]
Diff created D73549-code

**Comment by JulianBustamante** [comment]
Deployed r239000-wpcom
