### ISSUE TITLE
Payments Blocks: users with expired eligible plan can no longer manage Stripe account

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#59937]
### Quick summary

Based on a user report.

After having removed the Premium plan, the Premium Content subscription was still billing people.

But since the Premium plan was removed, they no longer had access to disconnect the Stripe connection.

### Steps to reproduce

I haven't reproduced this myself.

1. Create site with Premium Content
2. Connect to Stripe account
3. Use a test card to subscribe to premium content
4. Remove Premium plan

### What you expected to happen

That Premium Content no longer works, and doesn't bill people (Stripe should be auto-disconnected).

### What actually happened

Premium Content still billed people.

Support had to put the Premium plan back in order for user to disconnect Stripe.

### Context

User: 4676873-zd-woothemes

**Comment by Greatdane** [comment]
Another report: 4674199-zd-woothemes

**Comment by DavidRothstein** [comment]
I think this may be the same issue as 613-gh-Automattic/payments-shilling.

**Comment by michaeldcain** [comment]
@DavidRothstein's correct that it's related to the same bug in 613-gh-Automattic/payments-shilling, where we decided that the higher commission we charge for users in this situation is fine for the time being, but this issue uncovers the additional problem that a user without an eligible plan can no longer access the Earn management features:

<img width="1435" alt="Screen Shot 2022-02-05 at 2 18 49 PM" src="https://user-images.githubusercontent.com/942359/152655798-bd216a5e-9d34-4d95-9b40-5ebde7f9a537.png">

If we're willing to leave Payments Blocks in place and working (I don't see a compelling reason not to, given the higher commission and the possibility that we might allow this in the future) after a plan expires, we should retitle this issue and gate the management pages to "premium plan _or_ connected stripe account" (which would cover existing users).

/cc @Copons for thoughts

**Comment by Copons** [comment]
@michaeldcain Thanks for the ping (and apologies for the late answer).
I agree with you (and @artpi) that there really is no reason to stop folks from using Payment Blocks after their plan expires, besides also saving us some massive headaches.

We can definitely update the checks to access the Earn section, where we would then restrict the items displayed.
Unless I'm missing something, for users with **no >= Premium but a connected Stripe account**, we should:
- Keep the "manage" items where folks can check their earnings and disconnect Stripe if they want.
- Hide everything that's not directly related to the Stripe account.
- And I'm not sure about the referral program. 🤔 

<img width="1070" alt="Screenshot 2022-02-11 at 18 51 39" src="https://user-images.githubusercontent.com/2070010/153652187-a4d97dda-c8ad-4657-8538-6057294d0626.png">

**Comment by DavidRothstein** [comment]
This seems like it could become obsolete via p58i-c1P-p2 (note in particular the discussion of payments blocks there)?

**Comment by Copons** [comment]
@DavidRothstein I'm not sure I get which discussion you are referring to, but I guess that with the proposed plans changes we'd need to expose this screen to most users _even more_?

**Comment by DavidRothstein** [comment]
Well, I guess "become obsolete" wasn't necessarily the best way to phrase it -- I should have said that it may automatically be fixed as a side effect of that work (or specifically, whoever works on that will have to make it possible for users without a plan to manage their Stripe account, and that should either fix the scenario here also, or at least come extremely close to fixing it).
