### ISSUE TITLE
Marketplace: handle disconnected wpcom jetpack sites

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#59943]
If a wpcom site is unreachable or the jetpack connection is broken, we will need to figure out which strategy we will follow since:
1. we won't have any data about currently installed plugins 
2. wporg plugin installs will fail
3. wpcom plugin checkouts will result in the plugin being installed (since we are depending on Atomic jobs there) but plugin will be shown as not installed again due to Jetpack connection

**Steps to reproduce on an Atomic site**:
- Follow the instructions here to set your Atomic site as a developer blog p9o2xV-1r2-p2
- Install a paid plugin
- Go to `https://wordpress.com/plugins/[Domain]` and verify plugin is installed
- Sftp into that site and on `wp-content/mu-plugins/wpcomsh-loader.php` add `die;` in the top
- refresh `https://wordpress.com/plugins/[Domain]`, verify that plugin is not shown an installed 
- going to the plugin details and clicking to buy it again will result in buying a renewal
- trying to install any free plugin will result to failure

**Steps to reproduce for Jetpack Self Hosted**:
- [Setup your local jetpack site with jurassic tube](https://github.com/Automattic/jetpack/blob/6181b57645b99a760e5afaceec99d61e10f483c7/docs/quick-start.md#L41)
- Connect it to WordPress.com
- shut down the tube connection by `jetpack docker jt-down`
- visit `https://wordpress.com/plugins/woocommerce/[DOMAIN]`
- you will clearly see on the top left that `This site cannot be accessed` but plugin install button is active and clicking it will result to an error

![SS 2022-01-24 at 16 29 19](https://user-images.githubusercontent.com/12430020/150801725-a7e58b9f-0bc2-4952-ac77-f0dfd67911e9.png)

<img width="1587" alt="SS 2022-01-24 at 16 31 03" src="https://user-images.githubusercontent.com/12430020/150801997-acd050b4-e07c-4f2b-89d7-cff0567b0dcb.png">

**Generally:**
If jetpack is not connected https://github.com/Automattic/wp-calypso/blob/7655b6d1f326371990851da10ebb97f133fbdc17/client/state/selectors/get-site-connection-status.js#L11-L13 
- we shouldn't allow the user to proceed in clicking any button in plugin details page, prior art https://github.com/Automattic/wp-calypso/blob/c1f968a0e0cb0f5a54e5ad9dace504c5a451d405/client/my-sites/plugins/plugin-install-button/index.jsx#L212-L229
- in plugins list we should add a notice on top of the page like that site is unreachable, like https://wpcalypso.wordpress.com/devdocs/design/notice

Related convo: p1641895924018200/1641849758.014300-slack-C029JEQRVRT

**Comment by JulianBustamante** [comment]
@cpapazoglou Could I have the steps to reproduce this issue added to the description?

**Comment by cpapazoglou** [comment]
This messaging and call to action seems appropriate 
https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/client/my-sites/site-indicator/index.jsx#L194-L216
