### ISSUE TITLE
Spacer block: atomic only, "This block has encountered an error and cannot be previewed."

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#59941]
### Quick summary

On atomic sites with Gutenberg active, Spacer block crashes in the editor with notice:

`This block has encountered an error and cannot be previewed.`

The Spacer block is still present in the live view though.

### Steps to reproduce

1. On atomic site with Gutenberg active
2. Add a Spacer block

### What you expected to happen

![image2](https://user-images.githubusercontent.com/15944096/148915077-cdf4acf7-23c1-4fb7-a670-3a864ceba743.png)

### What actually happened

![image1](https://user-images.githubusercontent.com/15944096/148914940-8a6898d6-fa3d-4ea4-8c73-014a9fb9fd6b.png)

### Context

Ticket: 4676893-zd-woothemes

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Turn off Gutenberg.

**Comment by inaikem** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/59846
