### ISSUE TITLE
Welcome Tour: usePrefetchTourAssets refactor 

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#59955]
### Details

[usePrefetchTourAssets](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/hooks/use-prefetch-tour-assets.tsx) needs to be refactored to take into consideration future tour-kit variants. 
Things to work on:
- `imgSrc` will be optional, because a tour could be without images. It'd currently break our hook.
- `imgSrc.desktop` is assumed to be present and the default value, but it will need to be optional.

imgSrc (inside meta) type will be something like:

```
meta: {
	heading: string | null;
	descriptions: {
		desktop: string | null;
		mobile: string | null;
	};
	imgSrc?: {
		desktop?: {
			src: string;
			type: string;
		};
		mobile?: {
			src: string;
			type: string;
		};
	};
};
```

**Comment by StephNathai** [comment]
Can I take a stab at this?

**Comment by alshakero** [comment]
Hi @StephNathai! Yes please do. If you need any help, feel free to reach out!

**Comment by StephNathai** [comment]
Hi @alshakero. I have a solution for this but unfortunately due to my companies proxy settings, I am unable to complete the install to run the repo/run the tests. My code is only adding null checks to account for the optional scenarios. Will creating a PR run the tests automatically? If so, please let me know if it's ok to proceed with the PR or if I should pass on this issue, thanks.

**Comment by halleshubham** [comment]
Let me know, if I can give try @StephNathai

**Comment by StephNathai** [comment]
Hi @halleshubham sure, all yours.

**Comment by halleshubham** [comment]
If I'm not wrong, seems like it's already done by now, 

https://github.com/Automattic/wp-calypso/blob/89b10bccbb313c441e60d5ce0a7ec59dbba741d7/packages/tour-kit/src/types.ts#L117-L135

@StephNathai  @alshakero

**Comment by halleshubham** [comment]
@tyxla I think this one can be closed, ain't it?

**Comment by tyxla** [comment]
@halleshubham I think so, but I'll let @escapemanuele @alshakero confirm that there's nothing else to be done on it before closing.

**Comment by escapemanuele** [comment]
Yes, this can be closed!

**Comment by escapemanuele** [comment]
Already taken care of
