### ISSUE TITLE
Theme Showcase: Add badge indicating premium themes for premium or greater plans

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59966]
The Showcase does not highlight premium themes as premium once you've upgraded to a Premium or higher plan. It would be nice to add an indicator to show the value add, even post-upgrade. This may need some design thinking.

Free plan:

<img width="1184" alt="Screen Shot 2022-01-11 at 4 31 42 PM" src="https://user-images.githubusercontent.com/2124984/149024788-51be0861-12f7-4116-b137-647f66d3fdd3.png">

Premium plan:
<img width="1180" alt="Screen Shot 2022-01-11 at 4 31 57 PM" src="https://user-images.githubusercontent.com/2124984/149024807-07f5b9dc-db51-419d-85e1-d7acaccceab0.png">

**Comment by alaczek** [comment]
While we're at it, could we also fix some (glaring) design issues?

The star and the price and aligned:
![image](https://user-images.githubusercontent.com/4550351/149051859-1fab653a-c6bf-4486-a2a4-6267bf9aa0f0.png)

Both the star and the price are unreadable with active theme selection styling:
![image](https://user-images.githubusercontent.com/4550351/149052419-49f44701-0801-4ed1-8946-e3508defef6d.png)

**Comment by sixhours** [comment]
This was closed in #59678
