### ISSUE TITLE
Atomic: Update Doc Links on Settings > Performance

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#59976]
### Quick summary

There are three "Learn more" links under Settings > Performance on atomic sites. It would be more helpful to link to the WordPress.com doc because this contains information specific to a .com website.

### Steps to reproduce

1. Go to Settings > Performance on an atomic site.
2. Click the (i) icon next to three settings: site accelerator, lazy load images, fast ad-free video hosting.
3. Click Learn more and Privacy Information.

![image](https://user-images.githubusercontent.com/30727666/149076887-1fc63096-4a17-40c6-8bd0-fb5bb886f8d6.png)

### What you expected to happen

I expected to be taken to a WordPress.com help resource.

### What actually happened

I arrived at a Jetpack doc for self-hosted sites. The Learn more links can be updated to:

Site Accelerator: https://wordpress.com/support/settings/performance-settings/#performance-amp-speed

Lazy Load Images: https://wordpress.com/support/settings/performance-settings/#performance-amp-speed

Fast ad-free video hosting: https://wordpress.com/support/videopress/

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by formosattic** [comment]
This makes a lot of sense as our doc is adapted to the experience on WordPress.com.

I updated the initial post with the Jetpack links.

Also, emphasizing that we only want to change link for **Learn More**, the links for **Privacy Information** can stay as is.
