### ISSUE TITLE
"Filter by" section on the Activity log page has misaligned elements

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#59978]
### Quick summary

Right now if we check the Activity log and pick a filter, we can see some misalignment going on:

![image](https://user-images.githubusercontent.com/6737345/149087820-05e7db92-aec8-4f1e-9824-f7c0ac1c6d89.png)

Also the X button appears to be not part of the filter(?)

### Steps to reproduce

1. Access the Jetpack > Activity log on an Atomic site
2. Select an activity type

### What you expected to happen

To have the elements aligned

### What actually happened

They appear misaligned.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

Chrome 97, MacOS 12.1

### Reproducibility

Consistent

### Severity

All

**Comment by Greatdane** [comment]
@Robertght I am not experiencing this problem on Chrome 97. Can you check again now? Does it happen on all sites for you? 

<img width="1126" alt="Markup 2022-02-02 at 14 21 00" src="https://user-images.githubusercontent.com/5075840/152097529-89c134ba-865c-4dc5-ade9-7b7888254ea0.png">

**Comment by Robertght** [comment]
Hey! I cannot replicate it anymore. I think it was fixed by some mysterious beings. Closing.
