### ISSUE TITLE
Replace SSO Jetpack Doc with WordPress.com Doc

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#59975]
### Quick summary

On WordPress.com atomic sites, the WordPress.com Log In settings (SSO) links to a Jetpack doc. It is more helpful to link to the WordPress.com doc because this contains information specific to a .com website.

### Steps to reproduce

1. Go to Settings > Security
2. Under WordPress.com log in, click the (i) icon.
3. View the Learn More and Privacy Information links.

"Learn more" should link to https://wordpress.com/support/wordpress-com-secure-sign-on-sso/

"Privacy Information" can be removed for WordPress.com sites.

### What you expected to happen

I expected to be taken to a WordPress.com help resource.

### What actually happened

I arrived at a Jetpack doc for self-hosted sites, https://jetpack.com/support/sso/

![image](https://user-images.githubusercontent.com/30727666/149076325-637c771c-0122-4995-98b1-578ea82bc96f.png)

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by formosattic** [comment]
This makes a lot of sense as our doc is adapted to the experience on WordPress.com.
I updated the initial post with the Jetpack link.

**Comment by annacmc** [comment]
Swapping the Jetpack link for the WordPress.com one for all sites would be a quick fix, but my question here is: does it make sense to also switch it out for all sites, including Jetpack connected ones? Or should this be a change intended only on WordPress.com sites? I can see points for both approaches here. What did you have in mind @donalirl & @formosattic ? 

If we want to swap it out for everyone, then the link can be updated in the `client/my-sites/site-settings/sso.jsx` file, line `43`

>"Privacy Information" can be removed for WordPress.com sites.

Is there a different privacy page we should link to for WordPress.com sites?

**Comment by donalirl** [comment]
I would say this change should only be **for WordPress.com sites**. 

The dotcom doc is specifically written to provide help and information for dotcom atomic sites - and this information would not apply to self-hosted JP sites. 

The JP doc would be most helpful for JP-connected sites, and much less helpful for atomic sites. 

So, let's make sure the correct environment (atomic or JP-connected) sees their respective doc :)

> Is there a different privacy page we should link to for WordPress.com sites?

We don't have this for WordPress.com sites, so ideally the privacy link would just be hidden on dotcom sites but remain for JP sites.

**Comment by donalirl** [comment]
Sorry to re-open but I just want to double-check as I'm getting an error on non-English interface languages.

In an English interface, the link works. However, switch to Dutch for example and the link leads to a page not found error at this URL:

https://wordpress.com/nl/en/support/wordpress-com-secure-sign-on-sso/

...notice the `/nl/en/`

The doc has an nl version: https://wordpress.com/nl/support/wordpress-com-secure-sign-on-sso/

It looks like in English we link to `https://wordpress.com/en/support/wordpress-com-secure-sign-on-sso/` but perhaps that /en/ isn't necessary as it also works without it: https://wordpress.com/support/wordpress-com-secure-sign-on-sso/

cc @arcangelini
