### ISSUE TITLE
Customer sees duplicate sites on their account

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#59972]
### Quick summary

See #4678481-zen
Customer reports they see duplicate sites in their account

### Steps to reproduce

SU to user account.

### What you expected to happen

See only 1 site

### What actually happened

There are duplicate sites

### Simple, Atomic or both?

Simple

**Comment by formosattic** [comment]
Discussing this internally: p2EDhh-1qG-p2

**Comment by cometgrrl** [comment]
This seems like an edge case so I am going to close it for now.
