### ISSUE TITLE
Update Doc Links on Settings > Writing

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#59977]
### Quick summary

There are several "Learn more" links under Settings > Writing on both simple and atomic sites. It would be more helpful to link to the WordPress.com doc because this contains information specific to a .com website.

### Steps to reproduce

1. Go to Settings > Writing 
2. Click the (i) icon next to the various settings
3. Note that most of the Learn more links lead to a doc on Jetpack.com

![image](https://user-images.githubusercontent.com/30727666/149077997-0836caa5-526d-4455-95d3-1e658e1610f8.png)

### What you expected to happen

I expected to be taken to a WordPress.com help resource. Here are the relevant WordPress.com doc links:

* LaTeX markup language: https://wordpress.com/support/latex/
* Shortcodes: https://wordpress.com/support/shortcodes/
* Testimonials: https://wordpress.com/support/testimonials/
* Portfolios: https://wordpress.com/support/portfolios
* Infinite Scroll: https://wordpress.com/support/infinite-scroll/ (atomic only)
* Custom CSS panel: https://wordpress.com/support/custom-css/
* Widget visibility: https://wordpress.com/support/widgets/#widget-visibility
* Post by email: https://wordpress.com/support/post-by-email

"Privacy information" does not seem relevant to .com sites, but we can check on that.

### What actually happened

I arrived at a Jetpack doc for self-hosted sites.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by cometgrrl** [comment]
The ⓘ has been replaced by "learn more" links that all point to wordpress.com articles. This is no longer reproducible as written.

**Comment by donalirl** [comment]
Re-opening for two reasons:

1. On Simple sites, 'Testimonials' and 'Portfolios' still link to a Jetpack doc on custom post types, when they should link to their respective WordPress.com docs on Testimonials and Portfolios.
2. On Atomic, no changes appear to have been made. Issue still reproducible.

cc @cometgrrl

**Comment by cometgrrl** [comment]
Ah, I see what happened. 

This is what I see at settings -> writing on my simple site:

<img width="600" alt="Screen Shot 2022-01-31 at 10 41 28 AM" src="https://user-images.githubusercontent.com/86427589/151853398-defeefe7-8b0c-48dc-a19b-697c6e49e569.png">

The "learn more" directly to the right of "Enable Testimonials for this site." goes to https://wordpress.com/support/testimonials/, however, there's a learn more just above next to "Use these settings to display different types of content on your site." (circled on my screenshot) and that link is going to the Jetpack doc. 

And I did not check Atomic, I will remember to do that in the future.

**Comment by donalirl** [comment]
Hmm, that looks like you are switched to the Classic WP Admin view. However, it's the Default Calypso view this is concerned with:
![image](https://user-images.githubusercontent.com/30727666/151900631-2090ba5d-c53f-41a2-aadd-c34466db0261.png)

To get back to that view, you can click on Screen Options in the top right corner, and select 'Default View'.

**Comment by cometgrrl** [comment]
That makes so much sense. I must have changed to WP Admin view at some point, and forgotten. Another thing to add to my checklist. Thanks for the help!

**Comment by arcangelini** [comment]
Just reaching out to come to an understanding. I have read conflicting suggestions on how to handle the "Privacy Information". I do not believe there is a relevant privacy section for all these settings and this applies as well to the other pages - #59975 and #59976 

The PR's I currently have will fix the links and preserve the privacy links pointing to the Jetpack privacy information. Should we remove the Privacy Information altogether for WordPress.com sites?

@donalirl @cometgrrl

**Comment by cometgrrl** [comment]
I think @simison would be the best person to answer.

**Comment by donalirl** [comment]
Asked for any context we may be missing: p1645150864876209-slack-C2LPC2EMN

**Comment by simison** [comment]
There was some project at Jetpack long ago to add privacy info links to all features across the UI, but we don't have the same in WP.com.

We can keep these links hidden on Atomic & Simple sites on WP.com, and visible for Jetpack sites.

![image](https://user-images.githubusercontent.com/87168/154654699-9432f970-c89c-408a-bd4d-565aea11eb02.png)


@arcangelini I understood what this is about only when I saw the above screenshot from @donalirl  — recommend to include screenshots to support convo, usually helps. :-) Thanks for the ping!
