### ISSUE TITLE
Theme Showcase: Remove forum references under Support tab for premium themes

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59988]
We won't have individual support forums for these themes, so this reference should be removed or re-pointed to the general support forums:

<img width="652" alt="Screen Shot 2022-01-12 at 10 10 32 AM" src="https://user-images.githubusercontent.com/2124984/149167936-abc9f6a9-c825-4ca5-b4bf-2318d52e58e7.png">

**Comment by mreishus** [comment]
Fixed via #60000
