### ISSUE TITLE
Theme Showcase: Contact Us option does not show for Atomic sites

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59989]
Simple sites show an option to Contact us under the Support tab on individual theme screens:

<img width="825" alt="Screen Shot 2022-01-12 at 10 41 25 AM" src="https://user-images.githubusercontent.com/2124984/149173790-0ebf7a27-7b28-43f5-8d6c-e5afa182ff13.png">

But Atomic sites do not:

<img width="1039" alt="Screen Shot 2022-01-12 at 10 43 04 AM" src="https://user-images.githubusercontent.com/2124984/149173806-8809de21-97b5-4291-9b68-587b8119c44d.png">

Not sure why the discrepancy.

**Comment by mreishus** [comment]
Looks like it was added here:
https://github.com/Automattic/wp-calypso/pull/11294/files#diff-7877a61be37fa221346040d61b2baaf95670966105578f6625760f3c57b0b0c9R357-R358

It excludes Jetpack sites, but since Atomic sites are also technically Jetpack sites, those are also excluded.

**Comment by mreishus** [comment]
Fixed via #59995
