### ISSUE TITLE
[Bug]: Unable to close Google Photos or Pexels modal Windows while editing content

### ISSUE THREAD

**Issue by nickpagz** [Automattic/wp-calypso#59985]
### Quick summary

It is currently impossible to close the modal/popup windows when inserting an image in the editor if you choose Google Photos or Pexels Free Photos to insert an image. 

### Steps to reproduce

1. Start a new page or post.
2. Insert an image block.
3. Click on "Select Image".
4. Choose Google Photos or Pexels Free Photos.
5. Try to close the modal window by clicking on the "close dialog" **X** button in the top right of the modal window.

### What you expected to happen

The window to close.

### What actually happened

Google Photos modal does not close if you are not connected to the service.
Pexels modal does not close unless you choose and insert an image.

### Context

Discovered by accident while writing a blog post and trying to insert an image from my media library. I accidentally clicked the Google Photos link instead and was unable to close the modal window.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Workaround details

The only option is to refresh the page. There's an extremely high likelihood of content loss doing this due to unsaved changes.

**Comment by Greatdane** [comment]
@nickpagz - for future reference, please be sure to report bugs through the Buggomatic workflow, thanks!

**Comment by jartes** [comment]
Another report on 33739949-hc. Follow-up: 4700710-zd-woothemes

**Comment by msilbers** [comment]
+1 from me. Experienced this on my own site trying to set up a page

**Comment by ahmadbaig1** [comment]
+1. Experienced the same while testing FSE. The only way to recover was to reload the page.

**Comment by KokkieH** [comment]
+1. Just ran into it myself on my blog.

**Comment by rw-ye** [comment]
I ran into this issue while using my testing site.

## Another Workaround 

Set the `display` property of the `components-modal__screen-overlay` class to `none`.


Run the following in the browser console:

```
document.querySelector('.components-modal__screen-overlay').style.display = 'none';
```

- We can then '**Update**' the page, without losing any unsaved changes.


https://user-images.githubusercontent.com/21261509/151482642-abceca6a-4eca-4c3b-8a6e-3d2ab20b3a4d.mov

**Comment by worldomonation** [comment]
Still reproducible.

This is an user-facing issue that potentially leaves users with a poor experience of our platform. My opinion is that a bugfix for this should be prioritized.

**Comment by sharonlaker19** [comment]
+1 at 28584868-hc and I'm able to reproduce on my test sites too.
