### ISSUE TITLE
Premium themes: Try & Customize can lead to infinite loop between cart and Customizer

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59999]
Previewing a premium theme and starting the checkout process, then quitting the checkout process, can leave you going back and forth between the Customizer and checkout, with no way to get out except to open a new tab/window.

**Video demo:**

https://user-images.githubusercontent.com/2124984/149184496-30deecc5-c2b9-43b1-be6e-d0fceee8ec05.mov

**Steps to reproduce:**

1) On a site with the free plan, go to `/themes/[site]/?flags=themes/premium`
2) Click on the three-dots menu for a premium theme, and click "Live demo"
3) Click the "Try & Customize" button at the top of the preview window
4) Click "Purchase" in the Customizer
5) Remove the premium theme from your cart; you'll be redirected back to the Customizer
6) Try to exit the Customizer by clicking the X in the upper left corner
7) You'll be brought to checkout with an empty cart
8) Try to exit the cart by either clicking the X in the upper left corner, or click the "Go back" primary action button
9) You'll be brought to the Customizer
10) Repeat steps 6 - 9 forever

This could be solved by not allowing folks to "Try & Customize" premium themes, as noted in #59991

**Comment by mreishus** [comment]
May be solved by #60251

**Comment by sixhours** [comment]
#60251 doesn't necessarily solve the issue, but it makes it much less likely a user will encounter it (and the chances were probably slim to begin with), which is probably good enough for now.

**Comment by sixhours** [comment]
Calling this fixed by #60251
