### ISSUE TITLE
Theme Showcase: Vertical alignment of star icon and price needs design tweaks

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#59993]
<img width="268" alt="Screen Shot 2022-01-12 at 11 09 45 AM" src="https://user-images.githubusercontent.com/2124984/149177980-699594cf-18ef-4312-9f1c-f119dc1de106.png">

The price and star icon are vertically off center here. The star also looks off center within its circle.

**To reproduce**

1. Visit the Theme Showcase with a free simple site
2. Make sure the `?flags=themes/premium` flag is present in the URL
3. Note visual wonkiness

**Comment by mreishus** [comment]
Gave it a try here but I'm not really sure about the correct approach: #60009
Open to suggestions / revisions etc (or entirely new PRs approaching it differently). Note that this does not address the star within the circle

**Comment by jordesign** [comment]
I came across this in testing too - and noted the alignment of the star _in_ the circle. I imagine that it is the SVG trying to render in pixels that is throwing it off?
<img width="477" alt="Screen Shot 2022-01-13 at 1 15 15 pm" src="https://user-images.githubusercontent.com/1842363/149254918-6b09a032-6473-49d4-a01b-476c1b543052.png">

**Comment by sixhours** [comment]
Fixed by #60009. The star remains a little wonky but we're looking at a redesign of the theme price in upcoming revisions to the Showcase so I'm not going to worry about it for launch. In my testing, adjusting it 1px in the opposite direction still makes it look off-center. ;P
