### ISSUE TITLE
Pay with Paypal: navigation confirmation dialog is triggered constantly

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#60014]
### Quick summary

With the `Pay with Paypal` block added to the Gutenberg editor, navigating away form the editor in any form (return to dashboard, visit published page, etc) **consistently** triggers a navigation confirmation dialog.

### Steps to reproduce

1. start new post.
2. add the `Pay with Paypal` block.
3. fill out required details (name, price, email)
4. publish post.
5. once published, elect to view the published page.

### What you expected to happen

Browser navigates to the published page.

### What actually happened

Browser displays a navigation confirmation dialog.
This implies that some data has not been saved.

https://user-images.githubusercontent.com/6549265/149249928-18d831cb-713c-4308-8588-8f7987e6a94d.mov

### Context

Automated end to end tests.

### Simple/Atomic

Simple

### Other notes

Network request to `admin-ajax.php` shows the following in the request:

```
-----------------------------19391938392122733722345709053
Content-Disposition: form-data; name="action"

wp-remove-post-lock
-----------------------------19391938392122733722345709053
Content-Disposition: form-data; name="_wpnonce"

861f944a83
-----------------------------19391938392122733722345709053
Content-Disposition: form-data; name="post_ID"

1013
-----------------------------19391938392122733722345709053
Content-Disposition: form-data; name="active_post_lock"

1642037296:6321460
-----------------------------19391938392122733722345709053--

```

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/27249804/10c45e68-9a04-4df8-b347-a3ca062444a6

📌 ACTIONS
- Closed as no longer relevant/not reproducible
