### ISSUE TITLE
Plugin Content Breaks Simple Site Editor

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#60039]
### Quick summary

When Atomic, if you create content with the _"Stackable - Gutenberg Blocks"_ plugin, once the site is reverted the plugin's content breaks the editor.

### Steps to reproduce

1. On an AT site, install the _"Stackable - Gutenberg Blocks"_ plugin
2. Create a couple of pages using the plugin's blocks
3. Cancel the plan and revert the site
4. Edit the pages again after the site is back to Simple

### What you expected to happen

The editor to load.

### What actually happened

It loads sometimes, but not always, it just shows a blank screen.

### Context

Reported on: 4679125-zd-woothemes

Console shows the following error when trying to open the editor:

![ConsoleError](https://user-images.githubusercontent.com/16104522/149335939-e6668e2c-6398-4019-9118-bc1887f15d02.jpg)

### Reproducibility

Intermittent

### Available workarounds?

Yes, difficult to implement

### Workaround details

User would need to edit the pages using the Classic Editor, and remove the content from the plugin.

**Comment by Greatdane** [comment]
Tested this. Editor always loads but has different results, such as this;

<img width="746" alt="Markup 2022-02-03 at 13 55 50" src="https://user-images.githubusercontent.com/5075840/152283639-b8836017-182d-4e8e-b696-39ea99cf8216.png">

But this is true for all plugins, including Elementor. 

I am going to close this for now, but if we see more issues we can always re-open. I would expect pages with plugin content to have issues however.

**Comment by carinapilar** [comment]
> But this is true for all plugins, including Elementor.

I agree, the main issue here though is that for this user the editor breaks, so they can't access their content anymore. That's what I think we should troubleshoot further.
