### ISSUE TITLE
Marketplace: check copy and data fetched from woocommerce for all paid plugins

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#60033]
Let's check if data for all 6 extensions are correct

- [x] Title
- [x] Short Description
- [x] Description
- [x] Tags
- [x] Ratings
- [x] Author
- [x] Last Updated
- [x] Version

@gavande1 I think it would make sense utilizing the "fetch description" mechanism to fetch most of the above data, right? It would also help with adding more extensions. Anyway, the priority here is to catch anything not in order like it did happen here:

https://github.com/Automattic/wp-calypso/issues/59752
D72912-code

**Comment by cpapazoglou** [comment]
@JulianBustamante is this still in progress or ready for review?

**Comment by JulianBustamante** [comment]
@cpapazoglou Diff created: D73235-code

**Comment by JulianBustamante** [comment]
Deployed r238660-wpcom

**Comment by cpapazoglou** [comment]
Backend deployed, closing this.
