### ISSUE TITLE
[Bug]: Username and Site URL Change on Atomic Sites

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#60031]
### Quick summary

When changing a username on an Atomic site that **has a matching WordPress.com site URL**, then the below two options should not be shown, as an underlying site address cannot be done:

* Yes, change atsiteurl.wordpress.com to match my new username and discard the old address
* Yes, change atsiteurl.wordpress.com to match my new username and create an empty blog with the old address
---
![atsiteurlchange](https://user-images.githubusercontent.com/12064241/149324018-1a81d5ca-6c6c-4951-b114-f57b8de98bae.png)

### Steps to reproduce

1. Have a WordPress.com site which can use custom plugins and themes.
2. Go to https://wordpress.com/me/account and start an account username change.
3. Observe that some options are available that do not apply for Atomic sites.

### What you expected to happen

The below two options to not show for Atomic Sites:

* Yes, change atsiteurl.wordpress.com to match my new username and discard the old address
* Yes, change atsiteurl.wordpress.com to match my new username and create an empty blog with the old address

### What actually happened

The above options are shown on Atomic sites. 
However, when choosing either of them, the underlying site address is not changed.

I chose the "_Yes, change atsiteurl.wordpress.com to match my new username and discard the old address_" option and did the change. However, the underlying site URL stayed the same:

![atsiteurlchangedone](https://user-images.githubusercontent.com/12064241/149325091-66109623-82fa-4b6c-921b-5b047f0c0d75.png)

### Simple/Atomic

Atomic

### Other notes

The above two options only seem to be showing up for **a site that has the exact matching username**. For example:

* if you have a site called **testing.wordpress.com** and username **testing**, then the above options show. 
* However, if you have a site called **testing.wordpress.com** and username **testing2**, then those options are not shown. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by vykes-mac** [comment]
I have created a fix here D80695-code
