### ISSUE TITLE
Task: Add learn more icon to Woo Install title

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60049]
### Details

It would be good to add a "learn more" explainer to the WooCommerce title. Example of how this works now with the Domains screen:

![image](https://user-images.githubusercontent.com/545779/148991450-be7cf030-c5e6-4bed-996d-daae64e5c9aa.png)

### Checklist

- [ ] Linking to https://wordpress.com/support/introduction-to-woocommerce/

**Comment by SaxonF** [comment]
Given that we are working on an iteration to the WooCommerce landing page, and the page itself is the explainer, I think we can close this one off for now.
