### ISSUE TITLE
Videos UI: User progression for multiple courses seems unpredictable.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60056]
While preparing the walkthrough in p58i-bQA-p2, I was having trouble with predictable user progress checkmarks displaying when they should on a Calypso branch. I think we need to double-verify that user progress tracking is working as expected, regardless of the number of courses active.

**Comment by kwight** [comment]
In fact, the first step to this issue is library unit tests for user progression tracking – I don't believe we have any yet.

**Comment by sixhours** [comment]
I started working on more unit tests for the library functions here: D74627-code

**Comment by kwight** [comment]
Let's add coverage for the "mark video as complete" function in the library.

**Comment by kwight** [comment]
The issues I had were what seemed like inconsistent behaviour of watched videos being recorded as complete, but only when there were two active courses in production (currently, we only have the one, "Blogging Quick Start", where I never noticed any problems). By inconsistency, I mean videos not being marked as complete in the UI when I thought the should be, and completed videos no longer being marked as complete on revisiting at a later point. It could have been my testing or sandboxing. ¯\_(ツ)_/¯ 

By having good test coverage of the affected library functions, and some more hands-on testing of local Calypso with a new test course, we should be able to determine if there are any actual bugs. Instructions for adding and managing courses can be found in the [Field Guide](PCYsg-DgC-p2).

**Comment by andres-blanco** [comment]
I changed my local Calypso to point to the `connecting-the-dots` course. I saw no inconsistencies while marking videos as viewed from my local Calypso and from wordpress.com (on the `blogging-quick-start` course).

@kwight , do you remember the specific setup you where using when this happened to you?

**Comment by valterlorran** [comment]
Closing this as I tested again, and I couldn't find any inconsistencies.
