### ISSUE TITLE
FSE Beta - Zoologist: The fonts are not easy to change

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#60058]
### Quick summary

It is not very intuitive the option to change fonts since it relays on the Customizer

### Steps to reproduce

1. Inside the Site Editor try changing fonts by going to **"Styles" > Typography > Text**.
2. Notice the only font options are: Default, Body, Heading.
3. To actually change fonts you'll need to go to **"My Site" > Appearance > Customize > Fonts**

https://user-images.githubusercontent.com/3696121/149392873-da516fe8-1b1b-4e35-bf63-558b8ffa7a6d.mp4

### What you expected to happen

To be able to change fonts directly in the Site Editor.

### What actually happened

I needed to go to the Customizer, change fonts and then go to the Site Editor.

### Context

Dogfooding

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I tested using the Zoologist theme

### Browser, operating system and other notes

macOS Monterey 12.1 (21C52)
Chrome Version 97.0.4692.71 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Use the Customizer

**Comment by jordesign** [comment]
Thanks to @scruffian for the assist - the handling of fonts in the site editor is a know issue - and is addressed in this PR

https://github.com/WordPress/gutenberg/pull/36394

**Comment by KokkieH** [comment]
Noting a user report of this in Twenty Twenty-Two in https://wordpress.com/forums/topic/twenty-twenty-two-theme-fonts/?view=all

In the case of Twenty Twenty-Two there is no Fonts section in the Customizer, so the workaround isn't available.

**Comment by Addison-Stavlo** [comment]
I think we can close this one now that customizer font settings for these themes have been migrated to the GLobal Styles with google fonts options.
