### ISSUE TITLE
FSE Beta: Custom palette colors go away when saving a change in the Customizer

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#60057]
### Quick summary

The custom palette disappears when saving a change in the Customizer

### Steps to reproduce

1. Set a custom color inside FSE using the **"Styles" > Colors > Palette > Custom** option
2. Assign the color
3. Save the changes
4. Preview the site. All good!
5. Go to the Customizer and make a change, like the font, and save changes
6. Notice the custom color is gone

https://user-images.githubusercontent.com/3696121/149391819-b0dd8897-caf5-49f3-9749-b9c39041fa07.mp4

### What you expected to happen

For the custom colors to be preserved.

### What actually happened

The custom colors were lost.

### Context

Dogfooding

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I tested using the Zoologist theme

### Browser, operating system and other notes

macOS Monterey 12.1 (21C52)
Chrome Version 97.0.4692.71 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Greatdane** [comment]
Closing this now as Customizer is no longer accessible on FSE sites.

**Comment by mikeicode** [comment]
@Greatdane I'm going to reopen this, I ran into it working on an AT site, and just tested on a Simple site and see the same thing. I have access to Customizer on both, should I not be able to? If not how would custom CSS be added?

Create custom color:

![Screen Shot on 2022-03-21 at 10:45:36](https://user-images.githubusercontent.com/10353785/159286587-103b86d3-ce2d-4c27-8bb2-fc7c429d4dc4.png)

Add CSS via Appearance > Customize:

![Screen Shot on 2022-03-21 at 10:46:14](https://user-images.githubusercontent.com/10353785/159286649-feddba19-f89a-40ff-a8f2-4992bf8a63dd.png)

Custom color is removed:

![Screen Shot on 2022-03-21 at 10:49:26](https://user-images.githubusercontent.com/10353785/159286818-0ff5dce7-718c-41de-887e-a860485d070b.png)

**Comment by edequalsawesome** [comment]
I tested this with Twenty Twenty-Two on a simple and self-hosted site, and wasn't able to duplicate with those themes, but *was* able to duplicate with Blockbase, so I think this is an issue with the universal themes and how they save information -- transferring to the Themes repo!
