### ISSUE TITLE
Videos UI: We do not have event tracking for the i18n prompt link.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60055]
We do not have Tracks event tracking for the i18n prompt link – let's add it.

<img width="1382" alt="Screen Shot 2022-01-13 at 10 31 01 AM" src="https://user-images.githubusercontent.com/349751/149389691-043f00fb-ea36-42f1-9f45-fd2189deffe3.png">

**Comment by autumnfjeld** [comment]
@kwight Would you mind if Ganon takes this issue, we have two new Ganon devs and this looks like a great introductory issue. :)

**Comment by kwight** [comment]
@autumnfjeld Sure, go for it. 👍

**Comment by taipeicoder** [comment]
The event has been added with the name `calypso_courses_translation_support_link_click`!
