### ISSUE TITLE
ETK plugin: update for Core FSE

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#60064]
### Details

There are are a number of places the ETK plugin needs an update to stay current with Core + Gutenberg FSE features. Here's what I found so far:

### Checklist

- [x] [`remove_wp_admin_menu_items()`](https://github.com/Automattic/wp-calypso/blob/d265b765aa7086b5d58cbd62acdd1b1750a2c1c8/apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/class-full-site-editing.php#L583) can be removed as WordPress will limit what Appearance menu items are shown based on what the theme supports (e.g. https://make.wordpress.org/core/2022/01/07/state-of-the-customizer-with-block-themes-in-wordpress-5-9/)
- [x] [`load_core_fse()`](https://github.com/Automattic/wp-calypso/blob/34c861c5e512a59fc7e3d657e373804ffefea091/apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php#L86) and [`unload_core_fse()`](https://github.com/Automattic/wp-calypso/blob/34c861c5e512a59fc7e3d657e373804ffefea091/apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php#L103) need to be audited to see what hooks still need to be removed/added
- [x] We may not need `hide_fse_blocks()`, `hide_template_editing()`, and `hide_template_cpts()` any longer https://github.com/Automattic/wp-calypso/blob/34c861c5e512a59fc7e3d657e373804ffefea091/apps/editing-toolkit/editing-toolkit-plugin/wpcom-universal-themes/index.php#L214
- [x] Remove the [`wpcom-site-editor`](https://github.com/Automattic/wp-calypso/tree/34c861c5e512a59fc7e3d657e373804ffefea091/apps/editing-toolkit/editing-toolkit-plugin/wpcom-site-editor) folder, since we no longer have any overrides for the site editor.

There may be others, but this is what I found in an initial search.

**Comment by Addison-Stavlo** [comment]
Looking back at these items now we seem to have addressed these issues.
