### ISSUE TITLE
File blocks show error in editor when added in columns without file name

### ISSUE THREAD

**Issue by nicolynramos** [Automattic/wp-calypso#60062]
### Quick summary

When you add a File block inside of a column and leave the file name blank, returning to the editor shows an error "This block contains unexpected or invalid content" with a button to "Attempt Block Recovery".

<img width="843" alt="Screenshot on 2022-01-13 at 16-01-28" src="https://user-images.githubusercontent.com/71851343/149417337-d3e734a2-4407-4bcf-902b-6847db07d9da.png">

### Steps to reproduce

1. Add a Columns block to a page
2. Add a File block inside one of the columns
3. Select a file either from the Media Library or upload
4. Remove the file name added next to the Download button
5. Save and reload editor page

### What you expected to happen

The File block should show the same way it does when you add the block originally.

### What actually happened

The block shows an error message: "This block contains unexpected or invalid content" with a button to "Attempt Block Recovery".

### Context

I was working with a user who reported the bug here: 33640478-hc
It looks like the blocks are functioning fine on the live site but show error in the editor side. I did some testing and it happens across all themes I tried, but only inside of a column with no file name specified. The block works as expected outside of a column and/or when a file name is added. The type of file doesn't seem to matter either as all file types I tried came up with the same error. I also tested on both Atomic and Simple sites, no difference in outcome.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Not theme-specific, all themes affected

### Reproducibility

Consistent

### Severity

All

**Comment by kosiew** [comment]
Hi @nicolynramos ,

Thanks for reporting this and the detailed steps.

I could reproduce this too.
Triaging for developers' further investigation.

**Comment by cometgrrl** [comment]
This is reproducible on jurassic.ninja, and a core bug and needs to be filed in the [WordPress/gutenberg](https://github.com/WordPress/gutenberg/) repro.

**Comment by ccwalburn** [comment]
This user wants to be notified when this is resolved. 4684463-zen

**Comment by kerrynicl** [comment]
Refiled bug report on Gutenberg Repo - [GH- 39057](https://github.com/WordPress/gutenberg/issues/39057)

**Comment by annezazu** [comment]
Closing this out as https://github.com/WordPress/gutenberg/issues/39057 was previously fixed directly in Gutenberg.
