### ISSUE TITLE
Site Redirect appends "/" to the destination URL

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#60072]
### Quick summary

When you set up a Site Redirection for a destination such as `http://aozhou10btn.com/who-invented-the-internet.html` , WordPress.com automatically appends "/" to the URL.

 This causes 404 issues on servers that are not configured to automatically redirect to the correct URL on their end.

WordPress.com also does not allow users to prevent appending of "/" to the destination URL. 

### Steps to reproduce

1. Create a Site Redirect subscription from [here](https://wordpress.com/domains/add/site-redirect/)
2. Enter destination URL as http://aozhou10btn.com/who-invented-the-internet.html
3. Try visiting the custom domain, WordPress.com will send you to `http://aozhou10btn.com/who-invented-the-internet.html/` instead of `http://aozhou10btn.com/who-invented-the-internet.html` which gives 404 error.

If you check the redirection settings, you will not find any trailing `/`.

![image](https://user-images.githubusercontent.com/33957570/149454413-e662e18f-159f-43a9-9406-5950d90d6d52.png)

### What you expected to happen

WordPress.com should redirect to the correct URL without appending `/`.

### What actually happened

A `/` gets appended to the URL.

### Context

Chat: 33648197-hc
Follow up: 4685859-zen
Slack discussion: p1642128829211400-slack-C03TY6J1A

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

### Workaround details

No workaround apart from setting another redirection in destination servers ( which is not possible for the user in most cases) . The site redirection feature is unusable for users if they redirect to URLs like the one mentioned in this issue.

**Comment by cometgrrl** [comment]
After chatting with @delputnam, it seems this behavior is working as designed. The redirect is intended to be to a domain or directory path, not a file (as in this example, it's redirecting to a .html file).

More context here: p2MSmN-1kA-p2#comment-3401

**Comment by inaikem** [comment]
Docs update request:

1427-gh-Automattic/en.support-docs-content

**Comment by Greatdane** [comment]
@cometgrrl, @delputnam, we have recently had another example of a user not wanting to share a file directly, but a google doc. Because the URL does not end in a "/" the redirect is not working.

See; p2EDhh-1qV-p2

An example would be this text page URL
https://docs.google.com/spreadsheets/d/e/2PACX-1vT3ohhKd2BxUinxkgSln6OG_l3ln5njr1tROtGgM3OhYOhJGCO1Z8uZwcMDBcjvzvMoKD-3Y8KRu_Ut/pubhtml?gid=0&single=true

**Comment by devNigel** [comment]
Re-opened this issue. I think we should revisit the use-case of Site Redirect subscription. It does not make sense to assume Site Redirect will be only used by users to point to a WordPress site hosted elsewhere. That comment is also almost 8 years old and WordPress.com has come a long way since then.

**Comment by delputnam** [comment]
Nomado will add this to our backlog for consideration in a future sprint later in 2022. But as we have a very full roadmap, this one is likely to remain a low priority for the time being.

If there are additional reports of this issue, it would be helpful to note them here to aid in prioritization.

**Comment by cometgrrl** [comment]
> @cometgrrl, @delputnam, we have recently had another example of a user not wanting to share a file directly, but a google doc. Because the URL does not end in a "/" the redirect is not working.
> 
> See; p2EDhh-1qV-p2
> 
> An example would be this text page URL
> https://docs.google.com/spreadsheets/d/e/2PACX-1vT3ohhKd2BxUinxkgSln6OG_l3ln5njr1tROtGgM3OhYOhJGCO1Z8uZwcMDBcjvzvMoKD-3Y8KRu_Ut/pubhtml?gid=0&single=true

This is very interesting. It does seem like a corner case, I wonder how many people use site redirects in this manner?

**Comment by syds87** [comment]
I got a similar report here: 4864591-zen

In this case, the user has a site on square.site and it seems like the trailing / is causing a multiple redirect and would show a blank screen.

A temporary workaround that seems to be helpful in this case was suggesting adding a ? at the end of the Redirection URL. In this case, the redirect is working on my test site.

**Comment by mdtanjid0** [comment]
- [ ] 6083768-zen ( needs to follow up ). 

I got another report here and suggested the workaround as @syds87 suggested, which didn't work for this user. 
I checked that too, and it's the same for me!

**Comment by lsl** [comment]
This was fixed a while ago.

![Image](https://github.com/user-attachments/assets/2e26395c-8c27-44cd-bcbe-79e9f0ba74d0)

**Comment by lsl** [comment]
Github bug? I didn't remove any of those, just tried to add groundskeeping.
