### ISSUE TITLE
Domains: Design for domain credit with DWPO

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#6009]
Currently, when the user is in plansOnly group and have domain credit, they see the a-la-carte domain pricing scratched off and says "Free with your plan". However, they were not able to buy their first domain a-la-carte anyway. I think it might a good improvement to change the presentation that doesn't mention a-la-carte prices.

![image](https://cloud.githubusercontent.com/assets/991022/16026520/fd9cac44-3183-11e6-9e8c-12e19258a522.png)

/cc: @breezyskies

**Comment by klimeryk** [comment]
Fixed by #6059.
