### ISSUE TITLE
FSE: Template > Template Part: back button/link disappears when editing a template part

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#60103]
### Quick summary

When editing a _template part_ from a _template_, the **Back** button disappears when you try to access block settings or make any edition. Therefore, there is no easy way to return to the template after editing a template part.

### Steps to reproduce

1. Edit or start a new _template_.
2. Edit a _template part_ from there.
3. When the template part loads, you’ll see a _Back_ button on the top-left corner of the editor.
4. If you click on one block in the _List View_ or make any edition, the Back button will disappear.

Screencast:

https://user-images.githubusercontent.com/50875131/149626432-f0b3fc06-7d15-4496-aff2-5a61b01f3e7f.mp4

### What you expected to happen

The button should stick there so we could quickly return to the _template_ and continue editing.

### What actually happened

The back button goes away as soon you start editing the template part.

### Context

FSE training and testing.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

**Comment by khristiansnyder** [comment]
I've encountered this as well. There is no way to return back to the template editor after editing a template part. Clicking Site stays on the template part editor and doesn't return to the template/site editor:
![Markup on 2022-02-08 at 10:54:15](https://user-images.githubusercontent.com/41035049/153046968-f0a86b6a-2ab4-4940-b31a-4eef72efc27f.png)

**Comment by creativecoder** [comment]
This doesn't appear to be WP.com specific. I opened an issue in Gutenberg: https://github.com/WordPress/gutenberg/issues/39149

**Comment by Addison-Stavlo** [comment]
> I opened an issue in Gutenberg: https://github.com/WordPress/gutenberg/issues/39149

This has since been resolved and is working well on dotcom.
