### ISSUE TITLE
Posts List: "Me" and "Everyone" tooltip shows extra information

### ISSUE THREAD

**Issue by jordwest** [Automattic/wp-calypso#6010]
Possibly related: #1433

Hovering over "Me" from the Blog Posts page shows the tooltip "Me,[object Object]", while "Everyone" shows "Everyone,false"

<img width="846" alt="screen_shot_2016-06-14_at_12_19_36_pm" src="https://cloud.githubusercontent.com/assets/416133/16029266/dabdbbda-322a-11e6-8ba4-5988f253a5d6.png">

<img width="904" alt="screen shot 2016-06-14 at 12 19 50 pm" src="https://cloud.githubusercontent.com/assets/416133/16029275/ec7387e2-322a-11e6-9c54-67858955c7ad.png">

**Comment by jeremeylduvall** [comment]
Fixed in #6118.
