### ISSUE TITLE
Pullquote block Shoreditch theme: Font size changes not showing on live site

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#60138]
### Quick summary

When a site has the Shoreditch active, changes made to the typography size are not showing on the live site even after they are published.

### Steps to reproduce

1. From the page or post editor on a site with the Shoreditch theme active, either Simple or Atomic;
2. Add a Pullquote Block;
3. Change the font size settings by either choosing from the listed options or adding a custom one;
4. Update the changes and preview the page or post;
5. They won't display on the live site or page preview.

### What you expected to happen

I expected my font size settings of the Pullquote block to apply and be visible on the published page or post.
![Screenshot 2022-01-17 at 16 26 36](https://user-images.githubusercontent.com/2540430/149806503-6fcfcf53-21e5-44a7-ba1c-855b4353f424.png)

### What actually happened

The font size settings of the Pullquote block are not visible on the published post/page.
![Screenshot 2022-01-17 at 16 26 45](https://user-images.githubusercontent.com/2540430/149806987-92d33dcf-49f0-4e03-a54b-1036218afa48.png)
t 16.26.45.png…]()

### Context

Customer reported this here: 469237-zen, and I was able to reproduce it on both Simple and Atomic sites.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

**Comment by edwinho89** [comment]
Also reproducible on Karuna theme in 5347358-zd-woothemes

Maybe related to https://github.com/Automattic/wp-calypso/issues/60747 ?

Possible CSS workaround to inherit changes made on editor:

```
.wp-block-pullquote blockquote {
    font-size: inherit;
    font-style: inherit;
    font-weight: inherit;
}
```

**Comment by aisajib** [comment]
Just noting that I added this to the HE triaging board (as I think it might not have been created via Bugomattic, so it didn't get triaged till now).

**Comment by Joshgrygiel** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on P2 - N/A
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can confirm the typography of the Pull Quote block does not get reflected within the Preview or Live view of a page or post on both the Karuna and Shoreditch themes.
- The CSS workaround here does seem to resolve the issue:
```
.wp-block-pullquote blockquote {
    font-size: inherit;
    font-style: inherit;
    font-weight: inherit;
}
```

📌 ACTIONS
- Closed as duplicate of: https://github.com/Automattic/wp-calypso/issues/60747
