### ISSUE TITLE
Search Block:  Displaying HTML tags <em></em> 

### ISSUE THREAD

**Issue by Thelmachido** [Automattic/wp-calypso#60130]
### Quick summary

When you add the Search Block to a page the label will be wrapped in <em> tags as shown in the screenshot below: 

![Screenshot on 2022-01-17 at 16_51_58](https://user-images.githubusercontent.com/41231764/149795045-76b3fcdc-e597-48c6-8e12-fa786f09eca2.png)

### Steps to reproduce

1. Create a site with a Business Plan 
2. Activate Jetpack 
3. Add the [Search Block ](https://wordpress.com/support/wordpress-editor/blocks/search-block/)to a page/post and add a label to it 
4. The blocks label will be wrapped in <em> HTML tags 

### What you expected to happen

HTML tags shouldn't visible as shown below
<img width="851" alt="Screenshot 2022-01-17 at 17 17 09" src="https://user-images.githubusercontent.com/41231764/149795853-d056fc7c-d5d6-48b6-a1f8-06c4168c943e.png">
.

### What actually happened

HTML tags <em></em> are displayed on the blocks label.

### Context

33701967-hc

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by cintacks** [comment]
I'm not sure if this has been fixed or is a non-issue at this point. Tried to replicate and the search bar functionality is working as intended: https://prnt.sc/26fng9o

**Comment by filipanoscampos** [comment]
The user came to chat and I found the HTML tag was coming from the italics applied to the text "Looking back at the GDA archive".

Removing them solved it for now, yet this is something that shouldn't be happening given that the users have the option to edit the appearance of that text.

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS

    Tested on Simple – Not reproduced
    Tested on Atomic – Not reproduced
    Replicable on self-hosted sites – 

📌 FINDINGS/SCREENSHOTS/VIDEO

    The issue cannot be reproduced on Simple, Atomic or self-hosted sites with Jetpack activated.

**Simple**
<img width="691" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/aaea456b-b248-4554-b629-148d64d5cb89">

**Atomic**
<img width="563" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/8a898ccc-a561-49cc-a92c-26d7a6ca0990">

**Self-hosted**
<img width="691" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/8f4212e5-e5e1-4666-9785-638b2ec0e519">

📌 ACTIONS

Closed as non-reproducible, but please feel free to re-open.
