### ISSUE TITLE
Masterbar Cart: Cannot Scroll 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#60132]
### Quick summary

Scrolling is not possible with multiple items in the cart.

### Steps to reproduce

1. go to Upgrades > Domains 
2. select multiple domains to add to the cart  
3. click the masterbar cart 
4. scroll down to view all domains added in the cart. 

### What you expected to happen

Scrolling will be possible regardless of the number of items in the cart. 

### What actually happened

With multiple items in the cart, it's not possible to scroll. 

### Context

User report 4694319-zen (20 domains in cart) and testing on my test sites. 

Screen recording from my test site (20 domains): 

https://user-images.githubusercontent.com/36863633/149795731-147825c7-dd6f-4e17-a277-12448f17bad4.mov

Scrolling is also not possible with 9 domains (or up until the number of items in the cart has reached the bottom part of the screen): 

https://user-images.githubusercontent.com/36863633/149796441-4781fe17-a202-4468-b582-19fa3a74efdb.mov

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Firefox 96, Mac OS 12.1

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Go to checkout page to view all items in the cart.

**Comment by DavidRothstein** [comment]
Discussion: Also makes it impossible to go to checkout from the masterbar cart.
