### ISSUE TITLE
Invites: Accepting an invite occasionally logs user out signing up

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#6014]
There's a very intermittent error on accepting an invite where the user is somehow immediately logged out after entering their new account details.

1. Invite new user as follower
2. New user visits URL and enters account name and password and submits
3. The user then occasionally sees the login form with an error `ERROR: The password field is empty.`

The error thrown by Calypso is:

`ERROR: The password field is empty.`

This only happens occasionally but fails the e2e tests when this happens.

Raising here as an official bug in the hope that @ebinnion may have some insight into why this is happening.

![loggedout](https://cloud.githubusercontent.com/assets/128826/16031878/d1a3f8e8-3243-11e6-9629-953c4ffd49e2.png)

#automated-testing

**Comment by kriskarkoski** [comment]
@alisterscott Are you still seeing this issue in our tests? If so, do you have an estimate on how frequent it's happening? I'm leaning towards closing given the lack of movement or further reports, especially if we're only noticing it during e2e tests.

**Comment by alisterscott** [comment]
Yes it still happens occasionally. Since we don't have user reports I will close this for now.
