### ISSUE TITLE
Confirm the emails mentioned in the woo setup modal are being sent to users.

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60143]
Confirm the emails mentioned in the woo setup modal (after onboarding) are being sent to users.

<img width="555" alt="screen_shot_2022-01-17_at_4 19 04_pm" src="https://user-images.githubusercontent.com/1398304/149838110-3dba4b79-6403-4f32-9f65-2b8dc251eae4.png">

**Comment by obenland** [comment]
Let's find out if this will be a blocker for launching the onboarding flow in Calypso

**Comment by obenland** [comment]
Let's check with Leif from Woo if this is needed before moving forward.

**Comment by allilevine** [comment]
Hi @lsinger 👋 We're currently rebuilding WooCommerce's onboarding flow in Calypso to solidify WP.com customers' intent to create a store before moving them onto Atomic. At the end of the flow we'll mark their onboarding profile as completed, and send them directly to the WooCommerce admin, skipping the WooCommerce setup wizard. Can you help us understand if that will affect the emails users receive (as described in the modal)?

**Comment by lsinger** [comment]
I'm not intimately familiar with the codebase, so I"m not sure if I'm the best person to ping. Adding @Automattic/proton and @Automattic/solaris to the conversation. 

I took a look around myself and found the `WC_Emails` class, which does send a few kinds of emails, but I didn't find a reference to those described in the modals -- those sound like they might be marketing drip emails sent to the person setting up the store. 

The WooCommerce codebase doesn't even contain the string "relevant advice", so I my next best guess is that it might be coming from an external service or a different codebase. 🤔

**Comment by barryhughes** [comment]
In this case I don't *think* that the inbox is a traditional email inbox, but instead it is referring to the message inbox that appears within the **WooCommerce ▸ Home** screen:

<img width="726" alt="woocommerce-home-inbox" src="https://user-images.githubusercontent.com/3594411/150150619-69806fe5-d55b-463a-aabe-635199e0eebb.png">

This as well as the [message you shared](https://github.com/woocommerce/woocommerce-admin/blob/38fbb4aedd0f21cf21ddaa6af93e48564fd35324/client/homescreen/welcome-modal/index.js#L37-L46) comes from the [WC Admin package](https://github.com/woocommerce/woocommerce-admin/), so it may be worth reaching out to someone from that team to see what if any impact your changes will have :-)

**Comment by allilevine** [comment]
Thank you! 🙌 Sounds like we wouldn't need to worry about emails in that case.

> This as well as the [message you shared](https://github.com/woocommerce/woocommerce-admin/blob/38fbb4aedd0f21cf21ddaa6af93e48564fd35324/client/homescreen/welcome-modal/index.js#L37-L46) comes from the [WC Admin package](https://github.com/woocommerce/woocommerce-admin/), so it may be worth reaching out to someone from that team to see what if any impact your changes will have :-)

@Automattic/isotope 👋 Can you help us confirm whether there will be any impact to this messaging or other communications from skipping the WooCommerce setup wizard?

**Comment by lsinger** [comment]
Looping in @garethallison as there's the possibility that this is connected to the onboarding email series.

**Comment by ilyasfoo** [comment]
> In this case I don't think that the inbox is a traditional email inbox, but instead it is referring to the message inbox that appears within the WooCommerce ▸ Home screen:

This is correct.

> We're currently rebuilding WooCommerce's onboarding flow in Calypso to solidify WP.com customers' intent to create a store before moving them onto Atomic. At the end of the flow we'll mark their onboarding profile as completed, and send them directly to the WooCommerce admin, skipping the WooCommerce setup wizard.

>@Automattic/isotope 👋 Can you help us confirm whether there will be any impact to this messaging or other communications from skipping the WooCommerce setup wizard?

Perhaps @pmcpinto or @jarekmorawski may be able to answer that

**Comment by pmcpinto** [comment]
> @Automattic/isotope 👋 Can you help us confirm whether there will be any impact to this messaging or other communications from skipping the WooCommerce setup wizard?

The trigger some Inbox (in-product) messages based on information collected through the profiler. But they're mainly educational content. It's ok to skip the profiler/wizard

**Comment by allilevine** [comment]
> The trigger some Inbox (in-product) messages based on information collected through the profiler. But they're mainly educational content. It's ok to skip the profiler/wizard

Thanks! To clarify, we're still collecting most of the same information, just in Calypso / WordPress.com rather than the WooCommerce wizard. You can take a look at the questions by starting the flow at /woocommerce-installation/< site id > and enabling the "woop" flag: `?flags=woop`.

I'll close this issue for now but feel free to re-open if any other possibilities come up.
