### ISSUE TITLE
Marketplace: Don't redirect user to calypso when using /wp-admin/plugin-install.php screen

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60179]
### Details
Right now, we are redirecting users to the calypso plugin screen if they want to install a new plugin. However, users can still access the WP-Admin screen via the `/wp-admin/plugin-install.php` URL to install the plugin. So, when users use the WP-Admin screen to install a new plugin they are being wrongly redirected to the calypso screen when they click on the `Featured | Popular | Recommended | Favorites` tabs. 

We should not redirect users to the calypso screen when the user is trying to access the following tabs. 

![](https://cloudup.com/c8W-bQoEnpQ+)

**Comment by gavande1** [comment]
Related slack convo: p1642485410090800-slack-C029JEQRVRT

**Comment by cpapazoglou** [comment]
Probably we will need to change the following condition inside the `wpcomsh_update_plugin_link_destination` function in wpcomsh
```
function wpcomsh_update_plugin_link_destination( $url, $path, $scheme ) {
	// Run only for plugin-install.php links.
	if ( ! strpos( $url, '/plugin-install.php' ) ) {
		return $url;
	}

	return 'https://wordpress.com/plugins/' . ( new Automattic\Jetpack\Status() )->get_site_suffix();
}
```

**Comment by allilevine** [comment]
This is still the current behavior. It seems like a good fix to ship to users, but will require wpcomsh knowledge and a release.

**Comment by cpapazoglou** [comment]
Resolved by 824-gh-Automattic/wpcomsh
