### ISSUE TITLE
Design Picker Thumbnail Translations

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#60170]
## Details

The Design Picker in the `/start` onboarding flow is translated, but many of the thumbnails aren't.

<img width="1834" alt="Screenshot 2022-01-19 at 8 14 30 PM" src="https://user-images.githubusercontent.com/1500769/150082861-1d2e2768-70c5-4be7-9fd5-9ac188f7541e.png">

Some thumbnails look like they've been translated but the text rendering is broken in non-latin scripts. E.g. Twenty Twenty One in Japanese

<img width="593" alt="Screenshot 2022-01-19 at 8 17 07 PM" src="https://user-images.githubusercontent.com/1500769/150083182-81c32b4c-c5ed-450c-8b44-c9d5c257d194.png">

The thumbnails are translated using the Patterns Toolkit (PTK PCYsg-t0i-p2). The features are all there, but this umbrella issue is to implement the pipeline that will get theme demo sites into the [Glotpress project](https://translate.wordpress.com/projects/wpcom/block-patterns/) that provides the translations.

Some details about the thumbnail translation process: PCYsg-D3C-p2 PCYsg-t0E-p2

## Tasks

- [x] #60282
- [x] #60471
- [ ] ~Fix issue with non-latin characters in thumbnails~ superseded by #61351
- [ ] ~Query block content isn't being translated by PTK~ [won't fix right now](https://github.com/Automattic/wp-calypso/issues/60170#issuecomment-1047366917)

**Comment by autumnfjeld** [comment]
* Non-latin characters in thumbnails is an mShots issue, which requires 1) getting mShot works on new Apple M1 2) fixing the actual font issue in mShots @p-jackson  will create follow up issue or describe specifically in the comments here
* won't fix query block specifically, it will be absorbed into the Verticals work

**Comment by p-jackson** [comment]
Crossed out the last two remaining tasks.
