### ISSUE TITLE
Replace product type dropdown with checkboxes

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60171]
The "Which products will be listed" dropdown usage is confusing here, checkboxes make more sense. I think the design intention was to condense the two steps. Since we only have two supported options for now (physical and digital download) we have enough space on this step to show them along side the other options. Lets fix the UX for now, an extra step or more checkboxes for upsells can be added later.

- [ ] Change dropdown to checkboxes
- [ ] The product_types result should be saved as an array

[New design](https://github.com/Automattic/wp-calypso/pull/59837) to change: 

![Screenshot 2022-01-18 at 14-23-11 Add WooCommerce to your site — WordPress com](https://user-images.githubusercontent.com/811776/149865463-fd1a972b-5239-4de6-b9ae-95d32d323210.png)

Woo setup wizard for reference including all the extra upsells we aren't yet looking at for the woo on plans flow.

![Screenshot 2022-01-18 at 14-22-54 Setup Wizard ‹ WooCommerce ‹ wooptestupgrade — WooCommerce](https://user-images.githubusercontent.com/811776/149865467-2b5408b4-4b57-4448-8afe-79b99c2c3b40.png)

**Comment by lsl** [comment]
@SaxonF does this sound about right?

**Comment by SaxonF** [comment]
@lsl so you just mean changing the select to two checkboxes? That sounds fine to me.

**Comment by DustyReagan** [comment]
Just a note the `product_types` should be [saved as an array](https://github.com/Automattic/wp-calypso/issues/60172#issuecomment-1015899831). I wonder if that comes for free by switching from a dropdown to checkboxes?

**Comment by lsl** [comment]
Added as a task in the issue description.
