### ISSUE TITLE
Jetpack support wording on AT sites

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#60185]
### Quick summary

Just a slight wording disparity on Atomic WordPress.com sites. On the Jetpack pages below the help section is directing to "prioritized Jetpack support". We may want this to refer to WordPress.com support instead. The link does appear to direct to the WordPress.com support pages.

{site address}/wp-admin/admin.php?page=jetpack#/my-plan
{site address}/wp-admin/admin.php?page=jetpack#/dashboard

### Steps to reproduce

1. open AT site and go to Jetpack page
2. see support section on dashboard and my plan pages

### What you expected to happen

should refer to WordPress.com support?

### What actually happened

![2022-01-18 at 13 35](https://user-images.githubusercontent.com/47717887/149930199-c2e03bf2-dea0-45e6-abbe-8ef5bf1014cc.jpg)

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

no

### Reproducibility

Consistent

**Comment by Greatdane** [comment]
@Nic-Sevic To confirm, the issue is just the wording? `Your paid plan gives you access to prioritized Jetpack support.` should be `Your paid plan gives you access to prioritized WordPress.com support.`?

The URL takes me to the correct WordPress.com support (https://wordpress.com/help?site=URL)

**Comment by Nic-Sevic** [comment]
@Greatdane - Yes, just to clarify which support they should be reaching out to. If they turn to Jetpack they'll just get sent back to wpcom since it's hosted by us for these sites
