### ISSUE TITLE
Purchases: Can't refund domains purchased with plan after plan gets refunded

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#602]
Steps to reproduce:
1. Purchase any plan.
2. Add free domain to the plan.
3. Cancel and Refund plan but keep the domain.
4. Go to Manage purchase domain for kept domain.
5. There is only Cancel Purchase link.

There should Cancel and Refund link instead if purchase is within refund period.

**Comment by scruffian** [comment]
I talked to @peterbutler about how to achieve this; his idea was that when we cancel the domain subscription we check for the original plan transaction and refund it.

**Comment by fabianapsimoes** [comment]
Moved to code-T431, since this mostly back-end fix.
