### ISSUE TITLE
Footer Credit not displaying on Personal plan website

### ISSUE THREAD

**Issue by renata-franco** [Automattic/wp-calypso#60200]
### Quick summary

We are working on a ticket of a user that has Personal plan, and has always had this plan for this site, and the footer credit is not displayed. 

I am the third HE going through testing on this and we cannot find the issue. So, I decided to report this as some kind of bug. 

Edit: User reported that their site https://rosajiro.com/ also has this problem and uses the same theme: Balasana, 

Ticket: 4694834-zd-woothemes

### Steps to reproduce

We actually haven't been able to reproduce this. 

### What you expected to happen

When going to  My Site → Appearance → Customize → Site Identity → Foot Credit, we should get the WordPress.com logo, or similar. 

### What actually happened

No matter what option you click on the footer credit, nothing is displayed in the footer, only the Title of the site. 

See attached image. 
![Markup on 2022-01-18 at 17:15:01](https://user-images.githubusercontent.com/81378719/149975541-d19474e9-2dc3-4563-bae5-5ffbf357c015.png)

### Context

- We tried changing themes in case it was Balasana. 
- The site is in Spanish. I changed the theme's language and nothing.
- I tried to add the theme Balasana on a Spanish test site and account and nothing. 
- Tried changing the homepage to another page, still the same. 

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I do not think so. I changed the theme from Balasana, which is the one the user has right now, to Blank Canvas and others and nothing changed. 

### Severity

Two

**Comment by kimerlin81** [comment]
Unable to replicate. Notified @renata-franco via slack. P2 remains open for any findings to be reported.

**Comment by Greatdane** [comment]
As we are unable to replicate, and it only affects one user (two sites), we can leave this closed. Have advised the user to try another theme for now.

**Comment by kimerlin81** [comment]
This is not a bug. Brown flagged/Mature sites do not display the footer credit.
