### ISSUE TITLE
Import Everything - Missing step for upgrading to the Business plan

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#60238]
See more at: pcmemI-kH-p2#comment-496

**Comment by vishnugopal** [comment]
Discussion:
- Saygun has suggestions that it might be possible for us to skip the checkout process entirely.
- But the infrastructure for this (Pay later) is not in place yet, so this looks unlikely.
- So the most likely scenario here is that we'll just display a simpler Plans page (which just has the Business plan) and then redirect to checkout.
- See more: pcmemI-kH-p2#comment-513
