### ISSUE TITLE
FSE: The alignment option is missing from the toolbar for blocks in Template Editor view

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#60249]
### Quick summary

For blocks that have an alignment option in the block toolbar (e.g. Media & Text) disappears in the Template editing screen

Editor | Template Editor 
--- | --- 
![image](https://user-images.githubusercontent.com/39308239/150157394-f42091df-5f0c-4f30-b38f-93c222d069b7.png) |  ![image](https://user-images.githubusercontent.com/39308239/150157696-b1916682-1bbd-4480-a9b7-02e5faab48b7.png)

### Steps to reproduce

1. Create a post with [Media & Text Block](https://wordpress.com/en/support/wordpress-editor/blocks/media-text-block/) or any other that has the alignment option to set the width of the block
![image](https://user-images.githubusercontent.com/39308239/150157968-87347b3b-94da-4957-a9e8-182b4473a3d9.png)
2. On the right-side panel click Post > Template > Edit
3. Select the block you added above and look at its block toolbar

https://user-images.githubusercontent.com/39308239/150162614-bc50cb23-9629-4ef0-a4ae-f0aff2376244.mov

### What you expected to happen

See the alignment option

![image](https://user-images.githubusercontent.com/39308239/150157394-f42091df-5f0c-4f30-b38f-93c222d069b7.png)

### What actually happened

The alignment option is missing

![image](https://user-images.githubusercontent.com/39308239/150157696-b1916682-1bbd-4480-a9b7-02e5faab48b7.png)

### Context

Team testing 

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.1 with Chrome 97

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment]
Unable to replicate this - I see it in both editors; 


https://user-images.githubusercontent.com/5075840/152286698-29c7d44e-acdc-40ec-93d2-4016f67731f2.mp4



@zdenys are you still experiencing this problem on FSE? (please be sure to try a new site rather than an old FSE beta enabled site).

**Comment by zdenys** [comment]
I can no longer reproduce either.

**Comment by Greatdane** [comment]
Thanks! Looks like it has been solved and we can leave this closed then.
