### ISSUE TITLE
Mobile menu not working in Storefront with AMP in standard mode

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#60240]
### Quick summary

The mobile menu is not working in Storefront.

### Steps to reproduce

Activate the theme Storefront.
Add a Primary menu and also check the Handheld menu option
When visiting the site the mobile menu button is showing but not responding when clicked.

### What you expected to happen

I would expect the menu to open when the menu button is clicked on mobile devices.

### What actually happened

Clicking the button shows no difference. Nothing seems to happen.

### Context

4700188-zd-woothemes

### Theme-specific issue?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Change the AMP setting to Reader and pick one of the themes under Reader Theme. Like here: https://github.com/Automattic/wp-calypso/issues/56586#issuecomment-962236475

**Comment by kathrynwp** [comment]
Also encountered in 4719818-zen

Switched to Reader mode as workaround

**Comment by Greatdane** [comment]
@daria2303 - I am unable to replicate this with the storefront theme and primary menu;

<img width="448" alt="Markup 2022-02-03 at 14 16 10" src="https://user-images.githubusercontent.com/5075840/152285502-aca19f74-e81a-4c3a-a354-d59d90278da0.png">

Video;

https://user-images.githubusercontent.com/5075840/152285726-21a5490d-1c00-41a4-aea6-ac977e7f22d4.mp4

Are we sure this is not an AMP setting? Could you please explain in more detail how you are able to replicate this?

Thanks!

**Comment by daria2303** [comment]
@Greatdane Hi, sure, so I can still replicate it on Android when AMP is on with Standard mode, when is off, Reader, Transitional it is working. After changing AMP setting I flush cache. 
Sending video from my onlygrass.blog - you can check the site too, I will not edit it for now. It doesn't look like a setting to me, it would be rather strange not to be able to open menu.
I reported it also based on this request https://github.com/Automattic/wp-calypso/issues/56586#issuecomment-962544057

https://user-images.githubusercontent.com/11535091/152304252-df0b6988-2b73-41ee-99e6-0213ff645daa.mp4

**Comment by Greatdane** [comment]
@daria2303 Thanks, so the issue does look to be with AMP, when it is in standard mode?

I can also replicate menu not working with AMP in the standard mode setting. 

With AMP turned off, or on any other mode, the menu works fine, correct?

**Comment by daria2303** [comment]
Correct

**Comment by edwinho89** [comment]
33730815-hc

Applied workaround by switching to Reader mode on AMP fixed it.

Issue remains reproducible on Transitional and Standard mode on affected user's site.

**Comment by ClassicRKR27** [comment]
32280363-hc

Another example here, but the only way to resolve the issue with this site was to deactivate AMP completely; Reader mode still didn't work

**Comment by zaguiini** [comment]
>the only way to resolve the issue with this site was to deactivate AMP completely

Not too bad considering [we're moving away from AMP](pdKhl6-48-p2)...

**Comment by p-jackson** [comment]
Still relevant since Storefront users are likely on WoA where (1) existing sites will keep AMP, and (2) new sites can still choose to install AMP if they want to. Luckily since they have the full AMP plugin experience they can switch modes to fix things.

**Comment by danielbachhuber** [comment]
I spent a bit of time debugging this today.

In my local test environment, I:
1. Installed and activated WooCommerce via git clone: `git clone git@github.com:woocommerce/woocommerce.git`
2. Installed and activated the Storefront theme via git clone: `git@github.com:woocommerce/storefront.git`
3. Installed and activated the latest version of the AMP plugin: `wp plugin install --activate amp`
4. Viewed my Hello World blog post in Chrome with 'iPhone 12 Pro' as the device. 
5. Observed the mobile nav menu work as expected: https://user-images.githubusercontent.com/36432/173921911-5d00a0fb-31ed-4453-a694-5756159e0ea7.mp4
6. Switched from "Reader" to "Standard" Template Mode in AMP Settings: https://user-images.githubusercontent.com/36432/173924098-b9d333a5-ca08-4de3-aa61-2593b7e258ca.png
7. Observed the mobile nav menu no longer works as expected (with no JavaScript errors in the console): https://user-images.githubusercontent.com/36432/173922321-4a2b1bef-7899-4ffc-bf1a-24fd812a98cf.mp4

Here is my diagnosis:
* The show/hide toggle behavior in non-AMP is provided by `navigation.js`: https://github.com/woocommerce/storefront/blob/1f8f36a8145b4b60a044b0c28a0c84913d7aa7ed/assets/js/navigation.js
* `navigation.js` isn't loaded when AMP is in "Standard" Template Mode.

Fortunately, the AMP plugin makes it pretty simple for us to fix the issue: https://github.com/woocommerce/storefront/pull/1992

**Comment by danielbachhuber** [comment]
https://github.com/woocommerce/storefront/pull/1992 was merged! The fix should be released with the theme in the next week or two (conversation in p1656369306404089-slack-C02SGH7JBGS)
