### ISSUE TITLE
FSE Rollout: assign 10% of /start customers to FSE

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#60255]
### Details

The goal of this task is to roll out FSE Beta to 10% of customers that enter the `/start` flow. Here are some requirements and constraints:

- no opt-in screen.
- We still show classic and universal themes in the design selection step. 10% of users will get FSE if they pick the Universal Theme. If not, they'll still get the FSE sticker and be able to switch to the block-based theme from the theme showcase.
- we need to keep recording the same track stats that we've been using for FSE beta so far for consistent reporting.
- Users assigned to the 10% variant get Blank Canvas Blocks when they click on `Use a blank theme` button.
- Users assigned to the 10% variant see Twenty Twenty-Two and other available block-based themes in the design selection step.

### Checklist

- [x] FSE sticker automatically applied to 10% of customers that enter the `/start` flow
- [x] We keep recording the same stats for FSE Beta split as we've done so far. Opt-in will be `true` for 10% of allocated customerss, otherwise `false`.
- [x] FSE Beta customers get Blank Canvas Blocks when they click on `Use a blank theme` button.
- [x] FSE Beta customers see Twenty Twenty-Two and other block-based thems in the design selection step.
- [x] Land users in the Site Editor after completing the signup

**Comment by autumnfjeld** [comment]
@vindl  Some newbie questions. :). Is the following correct:
* 100% of users will see the mix of classic + universal themes (obviously 😄 ) 
* of the users that select a universal theme, 10% of these will be defaulted to the FSE editor
* 100% of of all users will get the FSE sticker so that they can select block-based themes (did you also mean so that these users can switch to using the FSE editor?

Not sure I got that last one right, because even without an FSE sticker, right now users can still pick a block-based theme. I think it has something to do with https://github.com/Automattic/themes/pull/4206
![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)

**Comment by vindl** [comment]
Hi @autumnfjeld:

> 100% of users will see the mix of classic + universal themes (obviously 😄 )

Correct! 😄 

> of the users that select a universal theme, 10% of these will be defaulted to the FSE editor

Yes. These users will get the `fse-eligible` sticker (adapting the Theme Showcase etc) and `wpcom_is_fse_activated` option set to `true` to activate the Site Editor for Universal themes.

> 100% of of all users will get the FSE sticker so that they can select block-based themes (did you also mean so that these users can switch to using the FSE editor?

I'm leaning towards limiting the sticker to 10% to keep things consistent with the existing FSE Beta rollout in `/new`. It will also make things easier to track since we won't miss users "silently" switching to FSE by changing themes.

~For easier tracking, we should automatically record `calypso_fse_beta_opt_in` -> `true` even for sites that belong to 10% group, and `false` otherwise.~

We changed the above event to `calypso_fse_enrolled` since the opt-in screen is removed now.

**Comment by p-jackson** [comment]
@vindl is Twenty Twenty-Two the only theme that will need to be specifically added for `fse-eligible` users? I'm guessing that all other themes are universal, so we can show them to everyone regardless of their eligibility. But I don't think the Twenty Twenty-Two theme is universal right? So may need to be hard-coded into the design picker.

Edit: actually, perhaps the Theme API returns different results depending on the logged-in user ...

**Comment by creativecoder** [comment]
I've created an initial PR for this at https://github.com/Automattic/wp-calypso/pull/60330

So far it covers

- Adding the specified percentage of users to the FSE beta (creates their site as an FSE site by adding the `fse-eligible` sticker and setting the `wpcom_is_fse_activated` option)
- Redirecting to the Site editor after site setup, when the theme supports it

**Comment by creativecoder** [comment]
> is Twenty Twenty-Two the only theme that will need to be specifically added for fse-eligible users? I'm guessing that all other themes are universal, so we can show them to everyone regardless of their eligibility. But I don't think the Twenty Twenty-Two theme is universal right? So may need to be hard-coded into the design picker.

@p-jackson There are plans for more "block-only" themes that require the Site editor, besides Twenty Twenty Two, but none have launched on WP.com yet, to my knowledge.

You can identify these themes by looking for the `block-templates` tag, indicating they support FSE features, and that they do not have a stylesheet or template of `blockbase` (are **not** children of blockbase or blockbase, itself), meaning the are not universal themes.

Right now we have some logic in the `/rest/v1.2/themes` endpoint that doesn't return block-only themes unless you explicitly filter for them (e.g. `/rest/v1.2/themes?filter=block-templates`), so we'll have to reconcile this somehow for showing them in the design picker.

**Comment by p-jackson** [comment]
> Right now we have some logic in the /rest/v1.2/themes endpoint that doesn't return block-only themes unless you explicitly filter for them

@creativecoder Great! I was just able to achieve that locally by specifying the extra filter here:

https://github.com/Automattic/wp-calypso/blob/39467cea5d88fe61ee55147968e46fea5cfbf6db/client/signup/steps/design-picker/index.jsx#L62

Like this:

```javascript
	const { data: apiThemes = [] } = useThemeDesignsQuery(
		{
			filter: 'auto-loading-homepage,block-templates',
			tier: isPremiumThemesAvailable ? 'all' : 'free',
		},
		{ enabled: ! props.useDIFMThemes }
	);
```

There's something wrong with the Twenty Twenty-Two thumbnail though, so I'll dig into that.

<img width="1250" alt="Screenshot 2022-01-21 at 5 22 55 PM" src="https://user-images.githubusercontent.com/1500769/150465433-b0a4e537-072b-42b1-837c-b76fdb56ec33.png">

Edit: The demo site has been launched p1642741941081400-slack-C029FM1EH. The thumbnail will update after the 24-hour cache has expired.

**Comment by vindl** [comment]
> @vindl is Twenty Twenty-Two the only theme that will need to be specifically added for fse-eligible users? I'm guessing that all other themes are universal, so we can show them to everyone regardless of their eligibility

Pretty much what Grant said already. That's currently the case, but in the future, all of the themes will be like TT2 (block-based, non-Universal), while Universal themes are more of an intermediate concept for an easier transition during the rollout.

**Comment by creativecoder** [comment]
> FSE Beta customers see Twenty Twenty-Two and other block-based thems in the design selection step.

@vindl Clarification question about this requirement... should FSE enrolled users see

1. All themes + "block-only" themes like Twenty Twenty Two, or
2. Only block themes (a.k.a. Blockbase universal themes + block-only themes like Twenty Twenty Two)?

The way the v1.2/themes endpoint is implemented right now is a bit limiting and doesn't support getting classic and block themes in a single request. If it's option "1.", I think we'll need to adjust that.

**Comment by p-jackson** [comment]
If it's "1." (which was my understanding from the issue description) could we also exclude "block-only" for now and protect the shipping date. And then follow soon afterwards with a change to the themes endpoint so it can return _all_ themes? Splitting seems like it'd de-risk both features and I think the FSE changes to `/start` still make sense without Twenty Twenty-Two.

**Comment by vindl** [comment]
> The way the v1.2/themes endpoint is implemented right now is a bit limiting and doesn't support getting classic and block themes in a single request. If it's option "1.", I think we'll need to adjust that.

@creativecoder In that case we can proceed with option 2. The way tracking is currently set up in the PR, `calypso_fse_enrolled` will fire after leaving the plans screen and before the design selection step. With option 1, we could record some users as FSE-enrolled, but they might pick a classic theme and effectively opt-out (note that this can still happen later in the Theme Showcase, but it's less likely since they are hidden from the Recommended tab).

Some other pros of this option:
- it's the end state that we are aiming to reach (remove classic themes from signup);
- it unblocks the current approach for shipping. We can switch to option 1 later if necessary;

The only con I see is having fewer themes to choose from initially, but that's not as noticeable as before, and we are adding more every week.

> If it's "1." (which was my understanding from the issue description) could we also exclude "block-only" for now and protect the shipping date. And then follow soon afterwards with a change to the themes endpoint so it can return all themes? Splitting seems like it'd de-risk both features and I think the FSE changes to /start still make sense without Twenty Twenty-Two.

@p-jackson This is a good trade-off too, especially considering that it's only Twenty Twenty-Two (still to be released on WP.com). But I think it complicates matters a bit with tracking the stats and comparing the two experiences based on them. That's why I have a slight preference for the option above.

Let me know if I missed anything.

**Comment by creativecoder** [comment]
PR now updated

- Triggers `calypso_fse_enrolled` for all new sites, adding the `site_enrolled` property as true/false, depending on fse enrollment for the user.
- Show only block-based theme (universal and block-only) in the design picker step for FSE enrolled users/sites

**Comment by vindl** [comment]
All tasks done.

**Comment by p-jackson** [comment]
> All tasks done

Is there a tracking issue for allowing enrolled users to choose classic themes? Or are we just happy that this will happen naturally when we get to 100% rollout?
