### ISSUE TITLE
FSE rollout: add tracking for page and block edits

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#60254]
### Details

Currently, `wpcom_page_edit` events are fired only for the `Post Content` block within the Site Editor, which underestimates these activation metrics and makes it harder to compare them with the classic experience.

~We need to ensure that these events fire on Template and Template Part post type saves too. I think that we should keep the above events to have aggregate stats for FSE, but also add separate ones to be able to track edits to template (part) areas separately.~

We decided to record a new event that will be triggered on Site Editor save action. That's the closest Site Editor analog of the `wpcom_page_edit` that we could think of that's suitable for comparison.

As for the `wpcom_block_edit` event, I verified that it's already fired from the existing code regardless of the post type (`post_type` as passed as the event prop).

### Checklist

- [ ] Add an event that tracks the Save action in the Site Editor. It should fire just once even if multiple entities are being saved.
- ~Add new events to track Template and Template Part block edits separately.~

**Comment by jeyip** [comment]
This draft PR adds a hook that would allow us to send a tracks event whenever template / parts are created or updated.

https://github.com/WordPress/gutenberg/pull/38097

**Comment by jeyip** [comment]
Draft PR for a dotcom specific temporary solution D73505-code. I'm pausing work on this briefly to shepherd https://github.com/Automattic/wp-calypso/pull/60271

**Comment by jeyip** [comment]
` Ensure that wpcom_page_edit and wpcom_block_edit events fire for Template and Template Part save actions in the Site Editor.`

This should be handled by the current state of D73505-code.

`Add new events to track Template and Template Part block edits separately.`

This still needs to be done.

@creativecoder @zaguiini

**Comment by jeyip** [comment]
Second phab diff attempt
D73604-code

**Comment by Addison-Stavlo** [comment]
>  wpcom_page_edit and wpcom_block_edit events

Note that neither of these events are registered in tracks so all descriptions, notes, property descriptions, etc. are all blank making it a little difficult to interpret some of the intended functionality here.

One thing I notice is that `wpcom_page_edit` and `wpcom_post_edit` are completely separate events.  The `post_type` event property is always `page` for the page event and always `post` for the post event. Given this it doesn't seem to make sense to update the `wpcom_page_edit` event to also handle templates and template parts, but probably makes more sense to create similar but separate `wpcom_template_edit` / `wpcom_template_part_edit` events.  

The `wpcom_block_edit` event seems to distinguish between page/post types and used for both, so for this event it probably would make sense to update it to include templates/parts and not creating new events for them.


> makes it harder to compare them with the classic experience.

Until these new events are added and depending on what we are trying to determine, we may already have some existing events that may help give us some idea of template/part edit saves. The `wpcom_block_editor_edited_entity_saved` event with the `entity_type` property of `wp_template` or `wp_template_part` can tell us when these entities are edited and saved from within the block editor. They are triggered by the save action tied to the multi-entity-save panel which is currently the only way I know of saving updates to template and template parts both within the site editor as well as the page/post editor's template editor flavor. They do not, however, currently tell us about what was changed (content vs. titles etc.) or which blocks were changed (although we could always work to make additions there if necessary). These also don't account for any methods of updating these items from outside the block editors (although Im not sure if there is a way to do this currently beyond maybe a 3rd party plugin), so appropriate backend events would be more robust in the long term as well.

**Comment by vindl** [comment]
I'll update the issue summary to reflect some of the changes in tasks based on our latest discussions.

**Comment by vindl** [comment]
Leaving these here for future reference

> but probably makes more sense to create similar but separate wpcom_template_edit / wpcom_template_part_edit events.

These events are already recorded in `wpcom_page_edit` with prop `post_type = wp_template` and `post_type = wp_template_part`. We could add a separate event for them for convenience, but it's not strictly necessary.

> The wpcom_block_edit event seems to distinguish between page/post types and used for both, so for this event it probably would make sense to update it to include templates/parts and not creating new events for them.

After looking into the code I agree that we don't need to add new events for this. `wpcom_block_edit` will already be recorded for Templates and Template Part edits, with a different `post_type` prop recorded which can be used to filter things further.

**Comment by Addison-Stavlo** [comment]
> Add an event that tracks the Save action in the Site Editor. It should fire just once even if multiple entities are being saved.

@jeyip opened this PR earlier today for this: https://github.com/Automattic/wp-calypso/pull/60408 

It is working well 😁

**Comment by creativecoder** [comment]
> We decided to record a new event that will be triggered on Site Editor save action. That's the closest Site Editor analog of the wpcom_page_edit that we could think of that's suitable for comparison.

I don't think comparing a client side event (in the Site editor) with a server side event is generally a good idea... there may be discrepancies between the events that we're missing, like how generally some % of client side events are going to be blocked by various ad blocking/tracker blocking browser extensions.

If we're looking to compare user engagement with content in FSE vs classic, I think we need events that are triggered in the same way on both types of sites. Maybe we can register a similar event in the page/post editor as well (or change it to be the same event with an editor_type property to track the editor it comes from), and then compare those events on sites that have FSE on vs. not.

**Comment by creativecoder** [comment]
Note that @jeyip [followed up here](https://github.com/Automattic/wp-calypso/pull/60463) to get this working in the Page and Post editors, as well (in addition to the Site editor).
