### ISSUE TITLE
Anchor: Verify Anchor docs about Atomic support.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60270]
Currently, [Anchor's docs](https://href.li/?https://help.anchor.fm/hc/en-us/articles/360060866231-Errors-Connecting-Your-WordPress-com-Blog) about the integration say that Jetpack and Atomic are not supported – let's verify if this is true across the board, and let them know if any changes are required.

See: pc4f5j-13S-p2

**Comment by arinoch** [comment]
If user verifications count as verifications, I have one in 4747952-zd-woothemes. They upgraded to Business, went atomic, and can no longer connect to Anchor. Currently telling them we're investigating.

**Comment by kwight** [comment]
I fix has been identified, and is slowly and carefully being rolled out over the next week or two (it ended up being fairly complicated). Once we know existing sites have been corrected, and new sites moving to WoA are behaving properly, we'll reach out to Anchor to remove the Atomic reference. cc/ @andres-blanco 

See: paYKcK-1j9-p2

**Comment by kwight** [comment]
Fixes have been rolled out – I've informed Anchor, waiting for confirmation: p1646167605904859-slack-C033YABM42V

**Comment by andres-blanco** [comment]
@arinoch the kind of errors reported in 4747952-zd-woothemes where being tracked in [this issue](https://github.com/Automattic/wp-calypso/issues/50560). The user's site should be working now 👍 .

**Comment by andres-blanco** [comment]
Added more details to the changes needed for the docs p1647610919421119/1647278438.244149-slack-C033YABM42V

**Comment by andres-blanco** [comment]
The docs are now updated 🎉 
https://help.anchor.fm/hc/en-us/articles/360060866231-Errors-Connecting-Your-WordPress-com-Blog
