### ISSUE TITLE
Publicize: Not able to connect to Facebook

### ISSUE THREAD

**Issue by yashitamittal11** [Automattic/wp-calypso#60286]
### Quick summary

User is not able to connect to Facebook via Publicize.

### Steps to reproduce

1- Try to connect Facebook on Tools > Marketing > Connections

### What you expected to happen

I expect to be able to connect to Facebook.

### What actually happened

I am not able to connect to Facebook and see an error.
<img width="874" alt="Facebook error" src="https://user-images.githubusercontent.com/21078987/150318040-a9808d00-603d-418f-8ea1-5020fd2bb8d7.png">

### Context

This issue is discussed here- p1642646176203100-slack-C02AVAR9B

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by inaikem** [comment]
Further internal discussion here: p1642669356163700-slack-CB0B2G43X

**Comment by nagpai** [comment]
User report - #4703767-zen

**Comment by pablinos** [comment]
Fix being worked on here D73451-code

**Comment by pablinos** [comment]
Fix deployed r238579-wpcom

**Comment by Greatdane** [comment]
4703767-zd-woothemes has been replied to, thanks all for the quick team effort!
