### ISSUE TITLE
Marketplace: Implement fail safe mechanism when fetching description from WCCOM

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60283]
### Details

When we are fetching descriptions from WCCOM API, we catch the response for 24 hours. This mechanism prevents repeated calls to WCCOM API. But it will keep making calls to WCCOM API if the server is down. So we need to update the cache mechanism to support failures. If the request fails, make sure it won’t be retried after a given amount of time has passed. If it fails consecutively, exponentially increases the wait time between attempts

Related P2: pdt2If-2J-p2
Related Convo: p1642616220032100-slack-C096PD42U

**Comment by gavande1** [comment]
WIP Diff created: D73444-code

**Comment by gavande1** [comment]
Waiting for the diff D73710-code to merged in.

**Comment by cpapazoglou** [comment]
Just noticed that D73710-code seems merged

**Comment by cpapazoglou** [comment]
Diff is deployed
