### ISSUE TITLE
Domains: Show information about purchased Google Apps licenses on Email tab

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#603]
We show the same screen for the user even if they have already purchased Google Apps licenses for any domain connected with their site:

![9a584706-5312-11e5-8f87-1a34f03c638d](https://cloud.githubusercontent.com/assets/699132/11361497/3cc9ecb4-928e-11e5-87ee-f8b205af72ba.png)

We agreed in a team chat we should change that:
> We don't show a list of users because there is no particular domain selected at this point. One option to help with this would be to also show a list of domains where Google Apps is enabled that the user can click on to manage their email addresses for that domain.

**Comment by breezyskies** [comment]
> We don't show a list of users because there is no particular domain selected at this point.

There's no particular reason we need a domain selected at this point, given that the "add Google Apps" flow allows users to select any domain (or even add emails to multiple domains in the same flow). 

Also, unlike email forwarding, there are no limits per domain, so I would recommend just showing Google Apps for all domains for the site:

Single Domain | Email Tab
------------ | -------------
<img width="743" alt="screen shot 2015-12-30 at 1 55 41 pm" src="https://cloud.githubusercontent.com/assets/3011211/12058154/ebaa35f0-aefd-11e5-84b4-edce1b859a71.png"> | <img width="742" alt="screen shot 2015-12-30 at 1 57 38 pm" src="https://cloud.githubusercontent.com/assets/3011211/12058155/ebad14b4-aefd-11e5-8d6c-1ab1dd04047c.png">

Note that I've also updated the design to make it more consistent with newer Calypso UI patterns. cc: @mikeshelton1503 @danhauk for design feedback (in particular, I wasn't sure about the use of Merriweather for email addresses -- seems like it could be considered "user generated content" but it's borderline). 

Ideally we can implement both the design updates and the Email tab updates at the same time.

**Comment by breezyskies** [comment]
After discussing with @mikeshelton1503 and @danhauk, we decided against using Merriweather for the emails here. Design updated:

<img width="743" alt="screen shot 2016-01-05 at 11 42 51 am" src="https://cloud.githubusercontent.com/assets/3011211/12125684/928bccf6-b3a1-11e5-95fd-1cedc7f2ad5d.png">
