### ISSUE TITLE
Domains: Mappable domain notice copy (DWPO)

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#6030]
When you search for a domain that is already registered, we show a notice that is saying the domain is registered but they map it for $X.

**Example:**

![image](https://cloud.githubusercontent.com/assets/991022/16053651/9406fb2c-321e-11e6-881f-baf9fed1ea05.png)

When you have some domain credit – whether through a site with a plan or a plan in cart – and do the search above, we still show individual prices but in reality it would be free.

We should update the copy to reflect this.

**Comment by klimeryk** [comment]
Fixed by #6056.
