### ISSUE TITLE
Notifications: Add Notification for Invites

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#60302]
We can improve the UX of our Invite system by using User Notifications for **the invitee**.

When a **site owner** invites someone we alert the site owner that an invitation was successfully sent.

![image](https://user-images.githubusercontent.com/545779/150378793-2172518b-67d7-482f-90af-1ca1dbb5107e.png)

We'll send the invitee an email to let them know they've been invited.

![image](https://user-images.githubusercontent.com/545779/150379139-26a6dd16-4881-404c-9c2b-c438ef150bdf.png)

But if that invitee is already a Dotcom user we do NOT give them a notification. Notification of the invite WILL NOT appear in the UI shown below.

![image](https://user-images.githubusercontent.com/545779/150379686-ab35835e-06a5-44cf-9009-7093e2f975b0.png)

The task is to correct that and provide notification of the invite through this UI to improve the UX and smooth the invite acceptance process.

**Note:**

Before starting in on this task let's check for Tracks Events for Invite click throughs off the email so that we'll know we have something to compare against post launch for this improvement.

**Comment by cpapazoglou** [comment]
Here is a fieldguide for notifications PCYsg-g8e-p2

**Comment by cpapazoglou** [comment]
👋 @yaelirub I saw you have assigned this issue to @emilylaguna, will your team be working on this?

**Comment by emilylaguna** [comment]
👋 @cpapazoglou Yes, I'll be working on this, this week.

**Comment by cpapazoglou** [comment]
That's great! While in Bespin we have no **Notifications** expertise, please let us know if we can help!

**Comment by emilylaguna** [comment]
Will do! In the meantime I did a write up on the process required to add a new WP.com notification in case you ever need to do so in the future as well: pbArwn-1JG-p2

**Comment by emilylaguna** [comment]
👋 I am closing this because this has been deployed on the server side. Reference: D73727-code
