### ISSUE TITLE
FSE: Customizer Link Removed When WooCommerce is Active

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#60317]
### Quick summary

By default, FSE on WordPress.com still shows the link to the Customizer -- however, if WooCommerce is active, it overrides that to replace it with a "Customize WooCommerce" link, which eliminates the Customizer link.

### Steps to reproduce

1. Create a new site with the WordPress.com Business plan
2. Make the site AT from `Settings > Hosting Configuration`
3. Activate Blockbase (or a Blockbase child theme) and FSE from `Settings > Full Site Editing`
4. See the link to the Customizer in `Appearance > Customize`
5. Activate WooCommerce

### What you expected to happen

The Customize item in the `Appearance` menu would still be there, allowing access to settings like changing the site footer credit:

<img width="507" alt="Markup 2022-01-20 at 16 33 26" src="https://user-images.githubusercontent.com/4000628/150428396-b7c10cab-c904-455a-9c39-b19b40bb6121.png">

### What actually happened

The Customize link is replaced with a Customize WooCommerce link, which takes you directly to the WooCommerce panel of the Customizer:

<img width="272" alt="Markup 2022-01-20 at 16 55 51" src="https://user-images.githubusercontent.com/4000628/150428563-f137e2fe-9185-485d-918a-9d413e6b361d.png">

This is likely due to the fix here: https://github.com/woocommerce/woocommerce/pull/30044

Choosing Customize WooCommerce only brings up the WooCommerce panel, and no back button to get to the rest of the settings that remain in the Customizer.

### Context

Troubleshooting a bug

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by cometgrrl** [comment]
I'm putting this at low priority, as it's my understanding that ultimately FSE replaces the customizer, and the behavior described here would be correct.

See paYE8P-1rh-p2.

**Comment by aleone89** [comment]
To note, I've just experienced this, and this button doesn't actually do anything here, please see a screenshot: 

https://d.pr/v/GnCExA 

> as it's my understanding that ultimately FSE replaces the customizer

Currently, with WooCommerce and FSE, it's not possible to make any changes to things like WooCommerce colour pallet settings (if powerpack is installed), product sorting and product image cropping in the WooCommerce template legacy block - this has to be done via the customizer. 

Also to note, with this bug in play, if other theme related settings, like additional CSS are required for a site, then you need to access the customizer, which is now not present unless I physically append /wp-admin/customize.php to the site being worked on...

**Comment by arunsathiya** [comment]
Closing this report as I cannot reproduce this anymore. Please reopen if anyone find a different result!

<img width="895" alt="image" src="https://user-images.githubusercontent.com/18581859/169391550-fa22a22d-45fa-44e3-9019-0a4fb2439024.png">

**Comment by arunsathiya** [comment]
@aleone89, that video seems to have expired. Any chance you still have it? Could you upload it natively to GitHub if you do? And, based on your report, the Customizer isn't available altogether for a FSE-theme enabled WooCommerce site? If I understand that part correctly, please open a new report via Bugomattic and we'll triage from there, thanks!
