### ISSUE TITLE
Woo Installer: User saw "We've hit a snag" error

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#60318]
### Quick summary

See: p1642572097155400-slack-C02DQP0FP
The user saw [the "We've hit a snag" error](https://d.pr/i/nW6hSB) when going through the Woo installer flow.

What we know:
- The user previously had WooCommerce installed
- Deactivating all plugins didn't resolve the issue.
- Manually installing WooCommerce did resolve the issue, but skipped the installer.

### Steps to reproduce

TBD

### What you expected to happen

The flow should recover.

### What actually happened

An error was shown.

**Comment by obenland** [comment]
Let's timebox the effort to reproduce the error to an hour.

**Comment by allilevine** [comment]
Follow-up: log as a Calypso error.

**Comment by lsl** [comment]
Wasn't sure how to do this so had a look around, we can use [logToLogstash](https://github.com/Automattic/wp-calypso/blob/67f067558c8611a57cf442b34f33dd8608e0e324/client/lib/logstash/index.ts#L25), [usage example](https://github.com/Automattic/wp-calypso/blob/ed45bf41db2431314b08d786405223cfcd7ce0ab/client/my-sites/checkout/checkout-system-decider.js#L17). 

https://github.com/Automattic/wp-calypso/pull/60796

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/pull/60796
