### ISSUE TITLE
Drafts: add ellipsis menu for draft actions

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6033]
Once work on custom post types completes we can add an ellipsis menu to the right of each draft in the posts list third column. They will allow users to trash, publish, view, etc. each draft without leaving the list view. Currently it's a trash icon on hover, but that doesn't seem like it would be the primary action. Having the ellipsis menu offers more efficiency and versatility to the drafts column.

cc @mtias

**Comment by alisterscott** [comment]
Drafts now has a pop out menu so closing this enhancement.
