### ISSUE TITLE
Woo installer text color on inputs

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60331]
![Screenshot 2022-01-21 at 15-15-21 Add WooCommerce to your site — WordPress com](https://user-images.githubusercontent.com/811776/150464872-6a3646fd-6c24-40d7-a67e-621d6bc79e17.png)

Input fields are using black while the rest of the page uses a grey.

@SaxonF Is this something we should change?

**Comment by allilevine** [comment]
This is the color I see on other /start inputs:
`var( --color-neutral-70 )`
