### ISSUE TITLE
FSE Rollout: remove AMP and Menus from Appearance menu

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#60339]
Currently, these two items are present in the Appearance menu and they don't appear in Core. AMP doesn't work as expected and leads to a non-existing Customizer page, and we don't really need Menus anymore. Let's remove them both:

<img width="437" alt="Screenshot 2022-01-21 at 12 38 12" src="https://user-images.githubusercontent.com/1182160/150520947-835da06d-3c33-4ead-91cc-ab51f384f56f.png">

**Comment by jeyip** [comment]
D74698-code
