### ISSUE TITLE
Woo installer: remove unused code

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#60349]
### Details

We've added a new WooCommerce install flow so we can remove most of /my-sites/woocommerce (except the new landing page, `WoopLandingPage`). 

### Checklist

- [x] Check with Matt Sherman about removing required-plugins-install-view.jsx.
- [x] Test that the new flow starting at /woocommerce-installation/< site id > still works and doesn't throw errors.
- [ ] Follow up: move the landing page out of /my-sites/woocommerce.

**Comment by lsl** [comment]
> Check with Matt Sherman about removing [required-plugins-install-view.jsx](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx).

@mattsherman just in case, but this should be fine, the code is leftover from the old store on wpcom feature, its not in use and now that we've [re-implemented](https://github.com/Automattic/wp-calypso/tree/trunk/client/signup/steps/woocommerce-install) the functionality under /start it can be deleted.

**Comment by allilevine** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/60784
