### ISSUE TITLE
Drafts: display draft meta info in ellipsis menu popup

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6034]
I mentioned adding an ellipsis menu with draft actions (trash, view, publish, etc) in #6033. To take that idea a bit further, we could add a view of meta info about each draft on hover or in a tooltip. The relevant meta info would be Author (avatar and name), date created/scheduled, and any other at-a-glance information that is pertinent. Design forthcoming.

cc @mtias

**Comment by alisterscott** [comment]
Drafts now has a pop out menu so closing this enhancement.
