### ISSUE TITLE
Tour Kit/Welcome Tour: Introduce mobile & desktop classNames for Steps

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#60345]
### What

Introduce mobile & desktop classes for Steps to manage better what CSS style to apply to a specific step based on the viewport.

So, what we want is to have more granular className definitions, something like:
```
// Step:
...
options: {
  className: {
	  desktop: 'is-with-extra-padding',
	  mobile: undefined,
  },
},
```

With that, it should be easier for the consumer to customize the appearance.

- Make granular desktop/mobile CSS classes possible for Steps
- Update the Welcome Tour config
- Update the Welcome Tour style to reflect that

**Note**: Let's only apply this to Steps for now, not the main/parent component. Let's also not remove `is-mobile/desktop` modifiers added to the parent component.

**Comment by chriskmnds** [comment]
@escapemanuele I've updated the description and title on this.

I thought about this some more, mainly in the context of our recent chat in the other PR. This is ok to work on for now, as it will help with a further refactor next. However, I think Tour Kit should not control things this way (mobile/desktop) next, but instead just let the consumer decide what steps/classes to include in a single config. So a single className, a single heading in meta, etc. Consumers can orchestrate the steps to provide in a mobile or desktop context and give Tour Kit a single config to render with. (will rethink a little more, but it feels like the more sensible approach right now)

So let's do the refactor and clean up the CSS parts that rely on `is-mobile`/`is-desktop` to use these new classes. Then moving to a single† className from there will be easier. :-)

† _"single" as in one-dimensional, CSV string or Array - just not separated across mobile/desktop_
