### ISSUE TITLE
Domains: DNS records management should not show for free site addresses

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#60358]
### Steps to reproduce

*   On a Free Plan site navigate to `https://wordpress.com/domains/manage/{FREESITEURL}/edit/{FREESITEURL}`
*   Alternatively, go to Upgrades > Domains > three dots next to the free site address > Change site address and then click Back at the top to end up on the same screen

![DNS-free-site-address](https://user-images.githubusercontent.com/39308239/150638129-e0f48f87-a6ba-49bc-ab38-f8be4e9609f7.png)
.

### What you expected to happen

See no DNS records tile since it makes no sense for a free site address, but only for custom domains.

### What actually happened

DNS records tile is displayed and has the Manage button that leads to a page that allows me to add DNS records but throws errors when I try.

https://user-images.githubusercontent.com/39308239/150638284-5913224c-e1e4-43c6-b258-297c8578a3f3.mov

### Simple, Atomic or both?

Simple

### Browser, operating system and other notes

macOS Monterrey 12.1 with Chrome 97

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by delputnam** [comment]
Thank you for the report @zdenys! Nomado will work on a fix asap.

**Comment by delputnam** [comment]
It appears that you could get to the settings page for a free URL subdomain by either manually typing in the full path of the URL or by using the back button from the change site address page. The back button should really take you back to the domain list again.

#60365 Fixes both the back button and prevents access to the page by typing in the full path. In both cases, you will now be redirected to the domains list page for the site.
