### ISSUE TITLE
Blocks and Widgets are not displayed when Visibility rules are set on themes with Widget areas in Simple sites

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#60355]
### Quick summary

https://user-images.githubusercontent.com/92185881/150633437-bf3d3654-ccd7-45e3-8b9b-1a1ad2d037cc.mp4

https://user-images.githubusercontent.com/92185881/150633455-b80aa9e1-0683-44d9-8ff7-a1e0212e8a5a.mp4

Blocks and Widgets are not displayed when Visibility rules are set on themes with Widget areas in Simple sites.

The first screen recording shows the visibility rules that were set for a Legacy Widget (Navigation Menu) and an Image Block.

The second screen recording shows the front-end, with the visibility rules not being followed.

Tested and found the issue to be consistent across Simple sites, with themes that have Widget areas.

### Steps to reproduce

1. Select any theme that has Widget areas (Footer or Left/Right Sidebar).
2. Add any block and set visibility rules (example: is_page = 'about').
3. Save and view on the front-end (does not follow the visibility rules).

### What you expected to happen

Front-end to follow the visibility rules.

### What actually happened

Visibility rules were not followed. Widget and block not displayed at all.

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by danielk-am** [comment]
First encountered in 4705683-zen. The user claimed that the visibility rules issue first started about 24 hours ago (which is, Jan 21, 2022).

**Comment by kavyagokul** [comment]
Also seen in 4709322-zen.

**Comment by benchilcote** [comment]
I did some testing and could not reproduce consistently.  I tested with Twenty Fourteen and could not reproduce.  I added the Follow Blog and a custom navigation widget and in both cases, visibility settings were followed.  I tested with showing / hiding if page is front page. 

Might also be related to https://github.com/Automattic/wp-calypso/issues/60352

**Comment by benchilcote** [comment]
Another report 4707259-zen

**Comment by retnonindya** [comment]
Another report:
4710583-zd-woothemes

**Comment by syedshaon** [comment]
Another issue 4709789-zen

**Comment by yoavf** [comment]
This should be fixed now with D73402-code
