### ISSUE TITLE
Widget Visibility: Widget disappears if set to Static Page

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#60352]
### Quick summary

This is a relatively recent bug, the report came from someone who had the widget visibility set and everything working as expected about a month ago. 

### Steps to reproduce

1. Select a theme with a widget area (Edin, Plane and Storefront were tested)
2. Add a widget (tested with Nav Widget, and Image widget) and modify the widget visibility to only show on a specific static page

### What you expected to happen

The widget should only show on the static page chosen. 

### What actually happened

The widget completely disappeared in the customizer, as well as on the live site when the changes were saved. 

### Context

Customer report #4709203-zen. 

I also noticed the issue does _not_ occur if you choose the front page or blog page, or any of the post type options. 

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround for the case I'm reporting was to remove the visibility rules, temporarily, so the nav menu would show up.

**Comment by yoavf** [comment]
This should be fixed now with D73402-code

**Comment by Greatdane** [comment]
Closing, can no longer replicate after fix.
