### ISSUE TITLE
Professional Email: Shows for free site addresses but cannot be added

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#60357]
### Quick summary

https://user-images.githubusercontent.com/39308239/150637998-d480d48c-44f6-415f-a491-27bface4f034.mov

### Steps to reproduce

- On a Free Plan site navigate to `https://wordpress.com/domains/manage/{FREESITEURL}/edit/{FREESITEURL}`
- Alternatively, go to Upgrades > Domains > three dots next to the free site address > Change site address and then click Back at the top to end up on the same screen.

### What you expected to happen

See no Professional Email offering at all since it cannot be added for the free site addresses. 

### What actually happened

I see Professional Email offering tile but I cannot actually create a mailbox.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.1 with Chrome 97

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by formosattic** [comment]
This is fixed now. I checked around, and not seeing any options to add an email if the site is on a Free plan.

https://user-images.githubusercontent.com/15944096/154034445-32075634-6c63-4e19-9455-ce0b422ee886.mov
