### ISSUE TITLE
Jetpack: Add Jetpack Search Widget should not be displayed for themes that don't support widgets

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#60362]
### Quick summary

If the site's theme doesn't support widgets (such as all the new Full Site Editing themes), having the link `Add Jetpack Search Widget` at `{SITEURL}/wp-admin/admin.php?page=jetpack#/performance` makes no sense. It attempts to open `{SITEURL}/wp-admin/customize.php?autofocus[panel]=widgets` but opens the Customizer and since there is no Widget section, it is confusing.

https://user-images.githubusercontent.com/39308239/150641851-a82d271d-6ba0-4566-bdde-d3bb4a07755d.mov

### Steps to reproduce

1. Activate a theme that doesn't support widgets (such as [Blockbase](https://wordpress.org/themes/blockbase/))
2. Got to Jetpack > Settings > Performance
3. Click Add Jetpack Search Widget 

### What you expected to happen

The button `Add Jetpack Search Widget` should not show at all

### What actually happened

It attempts to open `{SITEURL}/wp-admin/customize.php?autofocus[panel]=widgets` but opens the Customizer and since there is no Widget section, it is confusing.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Yes. It applies to all themes that don't support widgets.

### Browser, operating system and other notes

macOS Monterrey 12.1 with Chrome 97

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment]
Not sure if the @Automattic/jetpack team are aware of this. 

I assume this affects all WordPress instances, so let me know if this should be transferred to the Jetpack repo.
