### ISSUE TITLE
Can't Disable Auto-Renew on Domain

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#60366]
### Quick summary

When I try to disable the domain auto-renew on a Premium Site, it tells me the renewal is off, yet it's still there even after refreshing the page.

Screencast is too large to add. It's on https://d.pr/i/X2NMWz

![screenshot from https://d.pr/i/X2NMWz](https://d.pr/i/X2NMWz+)

### Steps to reproduce

1. Click on a domain from Upgrades>Domains
2. Turn off auto-renew
3. Give a reason or skip when it asks why you are disabling the auto-renew (the issue remains with both)
4. Note that it says auto-renew is off.
5. Also note it really isn't

### What you expected to happen

I expected to see auto-renew disabled.

### What actually happened

It remained enabled

### Context

I was working on docs and noticed it by accident.

**Comment by kerrynicl** [comment]
Hi There! @ChrissiePollock  Can you see if this still exists for you? I'm not able to replicate on my test sites:
![Screen Capture on 2022-01-24 at 10-50-19](https://user-images.githubusercontent.com/83325600/150818302-ef425abb-cf38-491b-a32b-eb0625a5a21a.gif)

**Comment by delputnam** [comment]
I cannot replicate this issue either.

**Comment by ChrissiePollock** [comment]
{code: 200, headers: [{name: "Content-Type", value: "application/json"}],…}
body: {success: true, upgrade: {ID: "10823473", user_id: "27047333", blog_id: "72350984", product_id: "6",…}}
success: true
upgrade: {ID: "10823473", user_id: "27047333", blog_id: "72350984", product_id: "6",…}
ID: "10823473"
active: "1"
amount: 18
attached_to_purchase_id: "10708692"
auto_renew: "0"
bill_period_label: ""
blog_created_date: "2014-08-04T15:01:35+00:00"
blog_id: "72350984"
blogname: ""
can_disable_auto_renew: false
can_explicit_renew: true
can_reenable_auto_renewal: false
check_dns: true
cost: 18
currency_code: "USD"
currency_symbol: "$"
current_price_tier_slug: null
current_price_tier_usage_quantity: null
description: "<p>The domain upgrade replaces your site's default address with a custom domain of your choice. Instead of P4TzNm-4NU-p2, this upgrade makes your site available at http://myclptest.com/.</p><p>You can manage your domain in <a href=\"/my-domains/\">My Domains</a>. From there you can add more domains to your site, specify the primary domain to use, or edit your domains settings.</p><p>See our support pages for more information:</p><ul><li><a href=\"http://en.support.wordpress.com/domain-mapping/\" target=\"_blank\">Domains</a></li><li><a href=\"http://en.support.wordpress.com/domain-mapping/domain-management/\" target=\"_blank\">Domain Management</a></li></ul>"
domain: "premiumtestclp.wordpress.com"
domain_registration_agreement_url: "https://wordpress.com/automattic-domain-name-registration-agreement/"
expiry_date: "2022-07-03T00:00:00+00:00"
expiry_message: ""
expiry_status: "included"
expiry_sub_message: null
has_private_registration: false
included_domain: ""
included_domain_purchase_amount: 0
is_cancelable: false
is_domain: "true"
is_domain_registration: "true"
is_refundable: false
is_renewable: false
is_renewal: false
meta: "myclptest.com"
most_recent_renew_date: "2021-05-31T18:21:20+00:00"
notification: {status: "success", message: "You successfully disabled auto renew for <em>myclptest.com</em>."}
ownership_id: "13653337"
pending_transfer: false
price_text: "Included with plan"
product_id: "6"
product_name: "Domain Registration"
product_slug: "domain_reg"
refund_amount: 0
refund_currency_symbol: "$"
refund_options: null
refund_period_in_days: 4
refund_text: "$0"
regular_price_text: "$18"
renew: "1"
renew_date: "2025-05-17T00:00:00+00:00"
renewal_price_tier_slug: null
renewal_price_tier_usage_quantity: null
subscribed_date: "2018-07-03T12:34:16+00:00"
subscription_status: "active"
tag_line: "Domain Registration"
total_refund_amount: 0
total_refund_text: "$0"
user_id: "27047333"
code: 200
headers: [{name: "Content-Type", value: "application/json"}]

**Comment by delputnam** [comment]
Thanks for walking me through this @ChrissiePollock 

To summarize the issue we found: the domain in this test renews with the plan so it's not possible to enable/disable auto-renew for the domain separately.  In this case, we shouldn't be showing the auto-renew toggle at all.

Nomado will add this to our next sprint and will update this issue when we deploy a fix.

**Comment by delputnam** [comment]
After a lot of working through various solutions and a good deal of investigation. It seems that this issue is caused when a domain is not unbundled from a plan due to manually extending the expiry date of the plan. Normally the domain would be unbundled from the plan at renewal and the two subscriptions would have separate renewal schedules after that. But if the plan does not go through the normal renewal cycle, the subscriptions are not unbundled and auto-renew will fail to be set properly on the domain subscription.

It seems the number of cases for this is very small and are mostly related to automatticians test accounts (though we did find at least one where a plan was gifted to an organization for several years).

The fix for this issue is to manually unbundle the domain from the plan using internal tools or by contacting Nomado and asking the team to do this.

I'll go ahead and close this issue now.

**Comment by leonardost** [comment]
We looked at the remaining bundled domains in this situation (around 100) and it seems most of them had a plan expiration date manually extended by HEs in the past. As they are very few and these problems don't arise frequently, we decided it's better to leave them as-is and handle problems manually when they occur. More info on p2MSmN-9iN-p2#comment-47320.
