### ISSUE TITLE
Extract out common bits from each file importer

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#60371]
- [x] Reuse the logic of [handling job transition](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/import-from/wix/index.tsx#L34-L36)
- [x] Consume existing **SitesItem** type instead of newly introduced **Site** | #60459
- [x] Prepare params method should map existing `supportedContent`, `unsupportedContent` (see the current implementation)

**Comment by bogiii** [comment]
> Prepare params method should map existing supportedContent, unsupportedContent (see the current implementation)

Hey @vishnugopal @jeroenpf,

During development, we left fields `supportedContent` and `unsupportedContent` empty. You can see the example: [WordPress prepareParams](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/import-from/wordpress/import-content-only/index.tsx#L66-L67) and [Wix prepareParams](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/import-from/wix/index.tsx#L79-L80) methods.

The current imports send mentioned fields getting from the [is-site-importable endpoint](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/imports/site-importer/actions.js#L180-L189).
It is something similar to what we now have with the `analyze-url` endpoint.

My question here is, should we extend `analyze-url` to support `supported and unsupported content` fields?

cc @zaerl

**Comment by vishnugopal** [comment]
I need a little bit more context here about what `supportedContent` and `unsupportedContent` is here to make a call. Let's discuss during team meeting today.

**Comment by vishnugopal** [comment]
Let's look into what this is: `supportedContent`, and then if needed, add it back to `analyze-url`.

**Comment by vishnugopal** [comment]
Discussion:
- `supportedContent` is only for Wix. 
- It's also used only for logging. Do we need this data in the future? (probably not)
- This was used at some point of time to see what list of apps (widgets/blocks equivalent) are there in Wix.
- Maybe let's ignore this for now. In the future, we can have this in the future if necessary.
- So let's remove this from the frontend if possible (or make it optional!)

**Comment by bogiii** [comment]
I will close this issue without removing the `supportedContent` and `unsupportedContent` fields. It required fields, so we need to leave it as it is.
