### ISSUE TITLE
Forge Data Onboarding

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#60379]
## Forge Data Onboarding

To be done sometime in Feb or March 2022.

To help smooth the data learning process for new devs, Kurt Rimbach has just created a great Data Onboarding Guide: PdqkMK-2u-p2

Please take a day or two to run through the document and do the Data Exercise (copied from the Guide) for a part of the Blogger or Build Flows. 

### Data Exercise
The data exercise below runs through a few of the key tools highlighted above.

- [x] Run through a user journey of your choice in the Hero Flow onboarding and fire a few Calypso events yourself. Check that they fired in any of the monitoring tools (Tracks Live View, Network Mode, Chrome Plugin etc.)
- [x]  Look up these events in the Tracks Events Directory
- [x]  Create a funnel with these events
- [x] Segment a funnel step with a ‘Custom Event Property’
- [x] Segment a funnel against a ‘Global Event Property’
- [x] Create a cohort of users that dropped out at a point in your funnel
- [x] Calculate the Conversion Rate Trends for the Funnel
- [x] Explore the Forge Health Metrics dashboard (Monthly | Daily)
- [x] Open the Looks Folder link on the dashboard – open a Look of your choice
- [x] Explore the Filters, Visualisation and Data areas of the Look interface.
- [x] Optional: Run a Hue query. Hints: Tracks Events data is in wyeast.tracks.prod_events, User features can be found in users.features.

**Comment by taipeicoder** [comment]
Tracking my progress here:

- [x] Run through a user journey of your choice in the Hero Flow onboarding and fire a few Calypso events yourself. Check that they fired in any of the monitoring tools (Tracks Live View, Network Mode, Chrome Plugin etc.)
- [x]  Look up these events in the Tracks Events Directory
- [x]  Create a funnel with these events
- [x] Segment a funnel step with a ‘Custom Event Property’
- [x] Segment a funnel against a ‘Global Event Property’
- [x] Create a cohort of users that dropped out at a point in your funnel
- [x] Calculate the Conversion Rate Trends for the Funnel
- [x] Explore the Forge Health Metrics dashboard (Monthly | Daily)
- [x] Open the Looks Folder link on the dashboard – open a Look of your choice
- [x] Explore the Filters, Visualisation and Data areas of the Look interface.
- [x] Optional: Run a Hue query. Hints: Tracks Events data is in wyeast.tracks.prod_events, User features can be found in users.features.

**Comment by fushar** [comment]
I'm done as well!
