### ISSUE TITLE
Email notifications: add option to not send notifications for specific posts

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#60377]
### What

Users regularly, though maybe not that frequently, ask about publishing a post without sending notifications to users.

Related interactions:

* https://wordpress.com/forums/topic/how-to-publish-without-notifying-subscribers-2/
* https://wordpress.com/forums/topic/can-i-publish-a-post-without-notifying-my-blog-followers/
* https://wordpress.com/forums/topic/how-to-post-without-sending-emails-to-subscribers/
*  33589070-hc

### Why

Various reasons:

* avoid spamming their followers' inboxes
* have better control over content (post sent to email can't be edited by site author)

Right now, we suggest this cumbersome workaround:

1.	Make the site private
2.	Publish the post (post must be Public, else if it's Private, then made Public later, a notification will show)
3.	Make the site public again

Email notifications are hard to troubleshoot. And if the workaround isn't properly followed, the mistake is pretty unforgiving.

Also, plugin solutions outlined at https://www.mailpoet.com/blog/wordpress-post-notifications-plugins/

**Comment by tehjaymo** [comment]
This request is also covered in this issue from 2020: https://github.com/Automattic/wp-calypso/issues/44263

**Comment by formosattic** [comment]
Thanks @tehjaymo!

Closing this in favor of https://github.com/Automattic/wp-calypso/issues/44263
