### ISSUE TITLE
Non-verified wpcom user limitations do not seem to apply to jetpack sites

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#6037]
Steps to reproduce:
- log out of your wordpress.com account
- go to wordpress.com/jetpack/connect
- enter the URL of an unconnected Jetpack site and click 'Connect Now'
- create a brand new wpcom account and click 'Sign up and Connect Jetpack'
- Boom! you are connected and can now browse your newly connected site in Calypso
- You'll see a notice to verify your email address, however you can still fully manage the site before you verify
- Click the link in your inbox to verify your Email address
- you'll see this message after you verify "Email confirmed! Now that you've confirmed your email address you can publish posts on your blog."

This leads me to believe that we should be applying limitations to Jetpack sites.

<img width="1365" alt="screen shot 2016-06-14 at 3 33 04 pm" src="https://cloud.githubusercontent.com/assets/2694219/16057011/ff3ed08c-3245-11e6-97cd-9907021a7d5d.png">

<img width="1365" alt="screen shot 2016-06-14 at 3 33 44 pm" src="https://cloud.githubusercontent.com/assets/2694219/16057014/02e1c12c-3246-11e6-8038-5fe2bdf8d836.png">

**Comment by johnHackworth** [comment]
This is far beyond of our NUX flow ... it's a problem that affects all jetpack manage. I'm taking it out of your NUX milestones.

So ... should we talk about this? @samhotchkiss @lezama @rickybanister

**Comment by rickybanister** [comment]
I would love to see us use the 'first look' component for this to 'brick' the ui and in a nice way ask people to confirm their email (or something like that). 

I'd also love to pull in @meremagee to get a .com opinion here.

**Comment by lancewillett** [comment]
I'm going to close this for now — not something we have time to work on as it's low priority. We can revisit later and re-open if it becomes a priority again.
