### ISSUE TITLE
Block Widgets encountering errors when setting visibility.

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#60372]
### Quick summary

When setting visibility for a Block Widget the block will error out with "This block has encountered an error and can't be previewed."

This issue does not apply to all blocks. I have not had the chance to set all blocks but here are a few examples:
- Tag Cloud Block: ✓
- Archive Block: ✓
- Paragraph Block: ×
- List Block: ×

### Steps to reproduce

1. Create or edit a Simple site. 
2. Add a new Tag Cloud Block Widget. 
3. Add a visibility setting under Settings > Block > Advanced > Visibility. 

### What you expected to happen

The Block should only display per the new visibility setting. 

### What actually happened

Added block errors out with "This block has encountered an error and can't be previewed."

### Context

Reported in this ticket: 4664133-zd-woothemes

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

### Available workarounds?

No but the platform is still usable

**Comment by KirkwallDay** [comment]
Legacy Widget "Top Posts & Pages" also gets moved to the inactive widget area when visibility settings are applied. From the same user as the original report.

**Comment by freelylovinglife** [comment]
Issue happening with recent comment widget with this user: ZD-4794738

**Comment by formosattic** [comment]
Closing this in favor of 8https://github.com/Automattic/wp-calypso/issues/57493

Add users' report at https://github.com/Automattic/wp-calypso/issues/57493#issuecomment-1056564014
