### ISSUE TITLE
Retired themes: Warn before we let the user switch out.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#60376]
### What

display a warning when a user is on a retired theme and wants to switch to a newer/different theme advising that the theme they're currently using is retired, and if they leave, they can't go back.

### Why

We're negatively impacting user experience presently by keeping the fact their theme is retired away from them. A user in 4710869-zd-woothemes found out their theme was retired because we told them. We told them after they'd already changed to a different theme (I don't think this was intentional) and couldn't switch back.

### How

Either or both of:

1: A marker next to the active theme to indicate the theme is retired, like we do to indicate the theme is active.

2: A warning when the user switches themes that the theme they're leaving is retired, and if they switch away, that's all she wrote.

**Comment by kerrynicl** [comment]
> We're negatively impacting user experience presently by keeping the fact their theme is retired away from them.

We don't really keep it from users, They would just have to click on the theme's info (see screenshot)
<img width="864" alt="Markup 2022-01-24 at 10 05 08" src="https://user-images.githubusercontent.com/83325600/150808379-9052b8f2-7be0-4384-a933-5d29f3d27b0b.png">
> A marker next to the active theme to indicate the theme is retired, like we do to indicate the theme is active.

But I do see what you are saying so i suppose you mean another sticker right here to say that is retired? 
<img width="1051" alt="Markup 2022-01-24 at 10 06 34" src="https://user-images.githubusercontent.com/83325600/150808678-ba8ab5d9-7fd9-4ade-a457-9b7f1600759a.png">

**Comment by Aurorum** [comment]
We did a lot of work around this in https://github.com/Automattic/wp-calypso/pull/40793, but it was ultimately decided that this feature should not proceed. I can't recall the details, but I think it was partly about encouraging users to switch from retired themes rather than adding obstacles/warnings.

If that decision has been reversed, I’d be happy to restart the PR again. Otherwise, it might just be worth only adding the label instead.

**Comment by Robertght** [comment]
I'm going to close this in favor of this report: https://github.com/Automattic/wp-calypso/issues/78604 but please reopen if needed.
