### ISSUE TITLE
Navigation Block: Menu list not being updated in the "Select Menu" part.

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#60385]
### Quick summary

The navigation block was not able to select/show the correct list of menus on the site on the Editor, or on the Live Site.
When I selected the "Primary" from the "Select Menu" part of the Navigation block, no menu item was showing on the editor. 
This is mostly because the menu "Primary" had already been deleted, and there was a new menu "Primary New" that was not showing up in the list of menus.

Attaching a video file for demonstration

https://user-images.githubusercontent.com/40609190/150740262-59348a6a-8b31-4895-8e8e-d0aa0a6389fb.mp4

### Steps to reproduce

I'm not 100% sure if this is reproducible.
1. Open the FSE Editor- Appearance -> Editor (beta).
2. Add Navigation block to the Header.
3. Select Primary Menu
4. Save Changes, check site.

### What you expected to happen

I expect the current set of menus to show up when I click on "Select menu".

### What actually happened

The menu list is not updated and it is showing old menus that may have been deleted already.

### Context

Found this while testing FSE on Horizon.

### Simple, Atomic or both?

Simple

### Reproducibility

Intermittent

### Available workarounds?

Not sure.

### Workaround details

Not sure.

**Comment by happychait** [comment]
I recently came across very similar issue on a customer's site.

The `Select Menu` option on the Navigation Menu block had three `Main` menus:
<img width="943" alt="Three Main menus" src="https://user-images.githubusercontent.com/1519466/153525706-9f078366-6550-4f86-b8a6-08cbb1ad6ff8.png">

The List View of the Header template shows the expected menu items, **but the site wouldn't show the same menu items**:
![The List View of the Header template shows the expected menu items](https://user-images.githubusercontent.com/1519466/153525735-2746155f-a186-4f1d-ab7e-c2f210751281.jpeg)

I renamed one `Main` to `Main-dupe` and selected the first `Main` menu **and that fixed the problem.**

I see the renamed menu at /wp-admin/edit.php?post_type=wp_navigation as well:
![Captured at 04-02-2022 at 15 00 01](https://user-images.githubusercontent.com/1519466/153525939-7e4306a5-979e-44cc-8d80-03a26687de5c.jpeg)

**Comment by ai2n** [comment]
Similar issue on #34204337-hc

**Comment by ai2n** [comment]
Similar issue on a customer's site, in 34204337-hc

**Comment by desnum** [comment]
This might be related: 34231950-hc

There were two menus with the same name. The one built in the editor had several pages and the one built in the customizer had invalid links. It's possible that the two having the same name is causing an issue with the menu being displayed on the frontend. I advised that they change the name of the menu they want to use, and remove the duplicates.

**Comment by Greatdane** [comment]
I think there is some confusion with all the different menu locations. @ahmadbaig1 - the menu located in the customizer is is the 'Classic' menu, but it still should show up. 

As Chait mentioned the new menus location in `/wp-admin/edit.php?post_type=wp_navigation` should show up. I am going to close this for now, but we can re-open if we can replicate consistently.
