### ISSUE TITLE
[Bug]: The Marketplace plugin install thank you page doesn't scroll

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#60386]
### Quick summary

After installing a plugin on my Atomic site, I see a Thank You page which doesn't scroll, although it has content that overflows:

<img width="872" alt="Screenshot 2022-01-24 at 10 02 07" src="https://user-images.githubusercontent.com/664258/150753801-75b3e5f7-ab38-4063-b4d4-2f3fb1f6acdf.png">

### Steps to reproduce

1. Go to Plugins section of an Atomic site.
2. Upload a plugin file.
3. After the installation is finished, you'll see a Thank You page.

### What you expected to happen

I can scroll down to see the entire page content.

### What actually happened

That Thank You page is not scrollable.

### Reproducibility

Consistent

**Comment by cpapazoglou** [comment]
Also, let's see what's going wrong with "Back to plugins" which should be aligned to the left like 
<img width="1596" alt="SS 2022-01-24 at 11 17 54" src="https://user-images.githubusercontent.com/12430020/150754847-25524106-be0a-4201-a376-de59c01f38cb.png">
