### ISSUE TITLE
Sharing: Hide No Ads banner on /sharing if they are using WordAds

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#6039]
Right now we show No Ads in a banner ad to users on /sharing to promote our premium plan:
![screen shot 2016-06-14 at 12 53 21 pm](https://cloud.githubusercontent.com/assets/8921630/16057645/de060630-322f-11e6-925f-c538a76e4ef1.png)

@mjangda noticed that it shows up on sites with the WordAds upgrade that still use the free plan - which could be confusing since they specifically applied to show Ads.

I'd suggest removing it for this subset of folks - with both the free plan and WordAds.

The other option would be to make it focused on a different feature of Premium, but that might be more work for minimal return.

**Comment by mtias** [comment]
@artpi there should be an easy way to detect wordads enabled sites, right? Whatever we used for the sidebar item, for instance.

**Comment by jeremeylduvall** [comment]
Addressed in #6175.
