### ISSUE TITLE
Marketplace: fix `accounting_product_variation_slug` for Yoast Premium Yearly Plan

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60438]
### Details

Right now, the `accounting_product_variation_slug` is set to `yoast-premium` for the yearly plan. We need to update it to `yoast-premium-yearly` for better visibility. 

We probably need to have a utility script to fix the slug. e.g. D65487-code

**Comment by JulianBustamante** [comment]
Diff created D74410-code

**Comment by JulianBustamante** [comment]
This ticket is closed since instead of modifying the slug of an existing product, a new product must be created to avoid issues with products that have already been sold on production. More details can be found on D74410-code

New Yoast Premium product and plans are created in #60437
