### ISSUE TITLE
FSE: Pagination Block: Setting the pagination to "Arrow" and "Chevron" causing raw HTML code displayed

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#60431]
### Quick summary

On Pagination Block (Query Pagination Block,) when the pagination is set to use "Arrow" or "Chevron", the pagination will have raw HTML displayed on the live site.

### Steps to reproduce

- Open Editor, then check Query Loop Block. The block usually has Pagination Block. If it does not have any Pagination Block, you can add one.

- Then, on the block sidebar, set the pagination's arrow settings to be displayed using "Arrow" or Chevron" option, like this one:
![Screenshot 2022-01-25 at 3 25 18 PM](https://user-images.githubusercontent.com/44726232/150930407-4d1644b9-fad9-48d2-8fa7-8adab33fe4d2.png)

- Things look good on the editor, but this how it looks like on the live site:
<img width="1363" alt="Screenshot 2022-01-25 at 3 26 58 PM" src="https://user-images.githubusercontent.com/44726232/150930526-75db4f57-05fd-4d7d-a1de-06f19288762c.png">

### What you expected to happen

For the raw HTML code to not appear and display the pagination as expected (i.e. "Next Page »")

### What actually happened

The pagination will have string like this on the live site

```
Next Page<span class='wp-block-query-pagination-next-arrow is-arrow-chevron'>»</span>
```

### Context

Personal blog

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Not sure, but most probably Blockbase-themes. I'm using Quadrat.

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Not using "Arrow" or "Chevron". Set the arrow settings to "None" (although this might be not ideal for folks who prefer to use arrow or chevron)

**Comment by Greatdane** [comment]
I can no longer replicate this? I would if it has been patched with the other recent HTML issues? @retnonindya can you please check again?

**Comment by retnonindya** [comment]
@Greatdane It is! It's fixed! 🎉  Thanks for keeping me in the loop, David! Yep, I can confirm there is no raw HTML appearing when the pagination is set to arrow or chevron! ✨  I'm going to close this GH. Thanks again!
