### ISSUE TITLE
Redundant notice in Media Library following removal of legacy unlimited upload plan

### ISSUE THREAD

**Issue by i11za** [Automattic/wp-calypso#60433]
### Quick summary

A site had a legacy "unlimited upload space" Business plan, until the plan was adjusted to monthly billing, and as a result the legacy plan was removed, leaving the site in the general 200GB max like everyone else. 

They're above max storage, and this notice is showing on their Media Library: 

![image](https://user-images.githubusercontent.com/84193945/150933411-40d6d781-cf34-4050-8d65-31fe418b5670.png)

This message no longer makes sense because:

- They are already on a Business plan.
- They have hit a hard limit and can not get any extra storage.
- They were already able to upload audio files.

### Steps to reproduce

This requires very specific parameters, so I haven't been able to test and see if I could reproduce, but it should be the following: 

1. Remove a legacy "unlimited upload space" Business plan on a site with over 200GB in storage.
2. Replace it with regular Business plan.
3. The notice above should appear in the Media Library. 

### What you expected to happen

Since they're already on a Business plan, upgrading is not a solution. The notice should reflect the fact that they've hit a hard limit and can not get any extra storage, or at least say that there has been an issue, and to reach out to support. 

### What actually happened

A redundant notice is displayed in Media Library (see screenshot above). 

### Context

Customer report: 33801094-hc / 4712061-zd-woothemes
Internal discussion: p7DVsv-9r5-p2#comment-39287

Related issue: [Uploads: Removing a legacy unlimited upload plan will leave the site with limited upload space. ](https://github.com/Automattic/wp-calypso/issues/52204)

### Simple, Atomic or both?

Simple

### Reproducibility

Once

### Severity

One

**Comment by kerrynicl** [comment]
Not able to reproduce, but worth checking if that notice can be modified

**Comment by mmtr** [comment]
D80667-code should fix this

**Comment by sejas** [comment]
The diff is merged: D80667-code, so I'm closing this issue.
