### ISSUE TITLE
Signup: Domains: It's possible to select Free plan when buying Domain Mapping during signup on DWPO

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#6043]
In the `plansOnly` variation (aka DWPO), during signup, when you select to map a domain, you are presented with the plan selection view. However, the Free plan is also listed there - allowing you to circumvent DWPO 😱 

/cc @rodrigoi @umurkontaci

**Comment by bisko** [comment]
This is more of a "visual" bug. Even if you choose the Free plan, after the signup is complete, the cart is pre-filled with the Premium plan.

**Comment by klimeryk** [comment]
Good to know 😌 (for some reason I did not finish signup when testing). Still, definitely worth a fix, since it might be very confusing to users and could lead to complaints ("I select Free during signup, but I was charged for Premium!").

**Comment by umurkontaci** [comment]
I think this is fixed
