### ISSUE TITLE
Marketplace: Add/update pricing for Yoast premium plugin

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60437]
### Details
Yoast premium is already added to store products in WPCOM. We need:
- add a monthly plan for the Yoast premium to WPCOM Store. We also need to update the yearly pricing. 
- update the annual price

You can find pricing information: pdh6GB-cN-p2
More on adding / updating store products here: PCYsg-rD-p2 and PCYsg-CJy-p2

**Comment by JulianBustamante** [comment]
Instead of updating the existing Yoast Premium product, a new product will be created due to the `product_slug` should not be modified/updated.

**Comment by JulianBustamante** [comment]
Diff created D74704-code

**Comment by JulianBustamante** [comment]
Deployed r239848-wpcom
