### ISSUE TITLE
Marketplace: Support adding a domain in the purchase flow

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60444]
### Details

This is front-end issue is where we need to handle purchase flow for Yoast Premium. It's worth noting that, the Yoast Plugin requires to have a **primary domain** when purchased. So, we need to allow users to purchase a domain along with the plugin. This would be our first bundled product in Marketplace. 

The purchase flow is already built earlier, but we need to make adjustments according to the changes we've done in previous iterations.

**Comment by cpapazoglou** [comment]
@SaxonF are we going to use the figma designs / flow here oU6nEIeiKSg8CayhEtgR6b-fi-6450%3A42026 ?

Also, can you suggest how users will buy a new domain in this flow? Are we redirecting them to the domains page?
<img width="1581" alt="SS 2022-01-25 at 15 28 41" src="https://user-images.githubusercontent.com/12430020/150985666-863f12b9-6a93-4805-93ae-ad15dbde36db.png">

or do we have a more standalone domain selection page?

**Comment by SaxonF** [comment]
Good questions @cpapazoglou . I'm off today but can look at this tomorrow .

**Comment by SaxonF** [comment]
@cpapazoglou @gavande1 as a first release, do we need to package up domain purchase with Yoast or can we simply point people to domain management screen if they want to change their domain first? Once they purchase their domain they will have to make their way back to the plugins page but I'm assuming that might be an edge case, especially if we direct people to add a domain first as part of onboarding.

e.g.
![image](https://user-images.githubusercontent.com/1072756/151299794-11900cac-d42d-4114-a24d-32db65c67b25.png)

or a warning pre purchase
![image](https://user-images.githubusercontent.com/1072756/151299888-b85d0835-5798-48bb-b40e-100ddb1ca63f.png)


This also feels like something that should happen post plugin install as part of Yoast's onboarding but I'm assuming we don't have any control over that.

> Are we redirecting them to the domains page?
To answer this question though I think yes we should keep them separate at least for the time being.

_Edit: We may want to include links to any relevant articles about domains or SEO._

**Comment by cpapazoglou** [comment]
@SaxonF can you let us know when this is ready for development?

**Comment by SaxonF** [comment]
Ok so based on previous conversations I think we've come to the agreement that we should provide some guidance within a confirmation step before installing Yoast SEO but rely on the existing manage domains experience as a first step.

Ideally we build this in a way that can be used for other plugins that may require certain conditions to be met.

**User doesn't have a custom domain**
![image](https://user-images.githubusercontent.com/1072756/151901696-b06008ae-a5fd-45aa-96d0-54e55d4b2f80.png)

**User has a custom domain but it isn't set as primary**
![image](https://user-images.githubusercontent.com/1072756/151901708-4507648f-0832-4091-93ac-f10ffbabe51e.png)

Manage domains takes the user to the domains screen while "Install Yoast SEO" proceeds with installation. "Learn more" opens up a support article outlining why a domain is required.

f84fqtCG4pCnCh2Hq0But5-fi-360%3A3635

**Comment by gcsecsey** [comment]
I searched the existing support pages, and I've found this article on setting up primary domains: https://wordpress.com/support/domains/#set-a-primary-address

@cpapazoglou @SaxonF Do you think this would be a good article to redirect to from the modal, or should we create a new article that highlights the importance of a primary domain?

**Comment by cpapazoglou** [comment]
> I searched the existing support pages, and I've found this article on setting up primary domains: https://wordpress.com/support/domains/#set-a-primary-address
> 
> @cpapazoglou @SaxonF Do you think this would be a good article to redirect to from the modal, or should we create a new article that highlights the importance of a primary domain?

Probably a new educating article would be better. @vajrasar any ideas who can pick up this task of creating some education material regarding SEO and domains?

**Comment by gcsecsey** [comment]
@SaxonF I'm in a bit of a dilemma about which way to go with the dialog design, could you please help to decide which way to go?

Looking at the Figma designs, they seem to differ a bit from the default styles of the existing Dialog components. The main differences are:
- modal window: `border-radius`, `box-shadow`, and `padding`
- buttons bar: separate section or not, separator line, `padding` 
- buttons: alignment and `font-weight`

Implementing the Figma design correctly takes a bit of custom code, and makes this one dialog visually different from the rest of the dialogs within Calypso. We could apply the changes to all Dialogs, but as this component is already reused in many places, it would require vigorous testing to check that nothing broke.

To show the differences, I've created some variations, going from the default dialog style (least amount of custom code) to the Figma design (most amount of custom code):

#### Default dialog style
This is another dialog, I'm adding it here just for reference:
![image](https://user-images.githubusercontent.com/11555574/152376550-983d02fa-515b-4dfa-a402-4149cdff1507.png)

#### Default style with the current description
On this one, I haven't touched the Dialog component, only the contents are styled. The buttons are added as standard buttons:
![image](https://user-images.githubusercontent.com/11555574/152379332-0263c9fb-86fe-452d-be10-53d2a6a07624.png)

#### Reusing defaults with minimal custom code
Here the buttons are still using the default component, I've just added some CSS on top of that:
![image](https://user-images.githubusercontent.com/11555574/152377285-4084d8cb-2895-4d9a-87dc-5e60c0ae4ead.png)

#### Custom implementation
I've tried following the Figma designs as close as possible here. The modal window has custom styles, the default button row is removed, and the buttons are added onto the content of the dialog:
![image](https://user-images.githubusercontent.com/11555574/152377175-8fa3c92e-d713-4487-a16b-c24251367bd3.png)

What do you think, how could we make it visually consistent with the rest of the application?

**Comment by gcsecsey** [comment]
Currently, only the domains of the site are checked, and the popup window is shown, if the primary domain is not a custom domain. I'd like to restrict this further to only run this check if the plugin requires a custom primary domain. The question is where to store the lists of plugins that have this requirement, especially as this list is expected to grow later?

As one option, I think we could store this info on the backend, as the API response already contains a `requirements` section, which we could extend. AFAIK so far, this has only been used to track dependencies between plugins, eg:
```json
"requirements": {
    "plugins": [
        "plugins/woocommerce"
    ]
},
```

As an alternative, we could also create a static list on the UI and extend it as needed.

I think the drawback with both solutions is the additional overhead, as the requirement will need to be added manually. I've looked at the WPOrg API response and I think there's no set of fields based on which we could derive this.

@gavande1 @cpapazoglou What do you think would be a good way to scale this to later additions to the marketplace?

**Comment by cpapazoglou** [comment]
> AFAIK

`requirements` is our own invention and can be used in any way we want. Initially, it was for plugins & themes mainly but it allows for any object keys on purpose.

It seems that @JulianBustamante has already added `'required_primary_domain' => true,` in the `requirements` for yoast in D74219-code. Have you tried that?

**Comment by SaxonF** [comment]
Apologies @gcsecsey! Thanks for taking the time to explore the different possibilities. Let's stick with the first option for now for consistency.

**Comment by gcsecsey** [comment]
> It seems that @JulianBustamante has already added 'required_primary_domain' => true, in the requirements for yoast in D74219-code. Have you tried that?

Great tip @cpapazoglou, thanks! I've added this check to the UI.

> Let's stick with the first option for now for consistency.

Thanks for weighing in @SaxonF, I've updated the UI to use this option! 👍

**Comment by gcsecsey** [comment]
> any ideas who can pick up this task of creating some education material regarding SEO and domains?

@vajrasar could you please weigh in here? We can also remove the `Learn more` button until some education material is ready.

**Comment by vajrasar** [comment]
@gcsecsey If still required, @galakhyati should be able to help weight in here.
