### ISSUE TITLE
Marketplace: Verify License provisioning for Yoast Premium plugin

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60441]
### Details

We need to check if License provisioning is still working as expected. The current implementation for provisional licenses for Yoast Premium is located here: `async-jobs/includes/wpcom-marketplace.php`

**Comment by cpapazoglou** [comment]
Here is an interesting thread regarding provisioning pcSRhZ-Y-p2

**Comment by JulianBustamante** [comment]
Diff created D75129-code

**Comment by JulianBustamante** [comment]
Deployed r240502-wpcom
