### ISSUE TITLE
Marketplace: Update the plugins screens to accommodate new plugins.

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60443]
### Details

Right now, we have only 6 plugins on Marketplace and all of them are featured right now. Now on, we are going to add a few plugins in Marketplace every two weeks. That's great! However, there is a problem that we can't display all paid plugins in the featured section. we probably need a page where we can display all paid plugins. 

We should also add the button `View All` or something similar so that users can browse all paid plugins.

**Comment by cpapazoglou** [comment]
Related P2 pdh6GB-gN-p2

**Comment by allilevine** [comment]
For design see "Collection foundations" in the linked P2.

**Comment by lsl** [comment]
Featured bool, paid/free, category/collection/tag, sorting by date, sorting by downloads (popular)

**Comment by allilevine** [comment]
Either hardcode page using search layout with query for featured plugin, or adjust current search results page to accept featured query param. Look at featured components and we can re-use as first step.

**Comment by allilevine** [comment]
Goal: user can browse all premium and free plugins on a page.

**Comment by cpapazoglou** [comment]
`featured` already exists for paid plugins as a `type` parameter 

https://github.com/Automattic/wp-calypso/blob/08c583c6287e59734ad43ec1fc9692ed5cf73bde/client/data/marketplace/use-wpcom-plugins-query.ts#L5-L23

we can probably refactor it to boolean, no blockers if we need to.

**Comment by SaxonF** [comment]
So just to confirm what a user should expect to see once this is shipped.

- There is a browse all link to the top featured/premium section that will link off to a page showing all premium plugins. 
- The premium plugins page will utilise the existing search view as shown below
- The title of this page will be "All premium plugins"
- Optional: The breadcrumb will show `Plugins -> Premium`. If this is too difficult we can leave it as "Search Results"

![image](https://user-images.githubusercontent.com/1072756/153983954-8c3f8a6c-4a91-4642-aa90-102599babb43.png)
![image](https://user-images.githubusercontent.com/1072756/153983777-dc7d4b1d-3e0a-4d8b-8fd4-ac7f0331707b.png)

**Comment by lsl** [comment]
Thanks, that helps a bit.

> The title of this page will be "All premium plugins"
> Optional: The breadcrumb will show Plugins -> Premium. If this is too difficult we can leave it as "Search Results"

If we're changing the title we'll probably want to add new routes to the search page so changing breadcrumbs won't be much of an issue to do as well.

**Comment by SaxonF** [comment]
@lsl we could also leave title but unsure how that would work with filters? Maybe `Search results for type:featured`?

**Comment by lsl** [comment]
I think it's ok I was going to hide the "search results..." text for these pages too. That should only show when a user runs a search.

**Comment by lsl** [comment]
There was some existing/dead? code I was able to leverage to get this close to something shippable pretty quickly in https://github.com/Automattic/wp-calypso/pull/61102.

- [x] There is a browse all link to the top featured/premium section that will link off to a page showing all premium plugins.
- [x] The premium plugins page will utilise the existing search view as shown below
- [x] Optional: The breadcrumb will show Plugins -> Premium. If this is too difficult we can leave it as "Search Results"
 
Notes:
- The browse all link won't show for paid section as there isn't more than 6 plugins. The link will only show on sections with more items than [`SHORT_LIST_LENGTH`](https://github.com/Automattic/wp-calypso/blob/7d72f2fcfeac3012822d471de8834008dda3912c/client/my-sites/plugins/plugins-browser/index.jsx#L558). I've suggested we remove this limit for simplicity in https://github.com/Automattic/wp-calypso/pull/61102.
- This code should be extendable to more/dynamic categories in future but it's [hard coded to the three](https://github.com/Automattic/wp-calypso/blob/5350205bea48efed3bb5f63b77dd18b49f768297/client/my-sites/plugins/controller.js#L17) at the moment.

Heads up for those walking into this code, the [single plugin url route](https://github.com/Automattic/wp-calypso/blob/0b1198ce5237a2540aaeeff024da4d5532a84acb/client/my-sites/plugins/index.js#L108) is doing double duty for category browsing.

There is a fair bit to fix / do in https://github.com/Automattic/wp-calypso/pull/61102 to get it shipped so lets do these in follow up issues:

- [x] The title of this page will be "All premium plugins"
- [ ] @SaxonF might want a back button on this? (take the calypso.live link for a whirl on https://github.com/Automattic/wp-calypso/pull/61102.)

**Comment by lsl** [comment]
Breadcrumbs was easy enough but need fallback text for when its unknown. For now I'm using "Plugins" - should never be shown to users but would rather this code didn't throw an error if it ever is.

**Comment by lsl** [comment]
Closing with https://github.com/Automattic/wp-calypso/pull/61102. There is some follow ups I'd like to do but set up tickets for those on [the board](https://github.com/orgs/Automattic/projects/290/views/20).
