### ISSUE TITLE
Marketplace: Add Yoast Premium to the Marketplace Endpoint

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60442]
### Details

In order to sell Yoast Premium, we need to show the product on the front end. To show products on the front end, we need the product information on the API endpoint `https://public-api.wordpress.com/wpcom/v2/marketplace/products`.

While adding products, we need to take care of the following:
- [ ] Add yoast premium plugin definition (statically) (let's ask marketing for content). Yoast premium has yoast free as requirement.
- [ ]  Put the product behind the `is_automattician` check. So the product is only displayed to a12s.
- [ ] Add `is_featured` property to the response and filter by this property when `type` parameter is passed, so that it can be displayed in appropriate sections on the frontend. We are already passing that `type` parameter here https://github.com/Automattic/wp-calypso/blob/c568872778f1e1cae7537cae7c9d21caa842ef9e/client/data/marketplace/use-wpcom-plugins-query.ts#L33-L51
- [ ] Add `required_primary_domain` property to requirements array of the plugin definition so we can handle purchase flow in a better way

**Comment by JulianBustamante** [comment]
Diff Created D74219-code

**Comment by JulianBustamante** [comment]
Deployed r239812-wpcom
