### ISSUE TITLE
On macOS Sierra, Safari suggests user's mailing addresses on the "Site address" signup field

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#6045]
Safari 10 suggested my actual, mailing addresses on the site address signup field.

Here's a screenshot with the addresses redacted:

<img width="473" alt="address" src="https://cloud.githubusercontent.com/assets/418473/16061814/ac67b05c-3265-11e6-87c3-b209a444edc4.png">

**Comment by lancewillett** [comment]
I couldn't repeat this using Safari 10.0 on OS X 10.12 today with `https://calypso.live/start/domains/en` as the URL.

The HTML of the form element is `search` type, not `address` as I might have thought.

```
<input type="search" id="search-component-3" class="search__input ltr" placeholder="Enter a domain or keyword" role="search" value="" aria-hidden="false" autocapitalize="none" dir="ltr" maxlength="60">
```
