### ISSUE TITLE
Gallery: Unable to rearrange images by dragging and dropping in "Edit gallery" modal

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#60469]
### Quick summary

Slideshow gallery blocks (possibly also other gallery blocks), as well as galleries added to a Classic block, cannot have their images arranged by dragging and dropping in the "Edit gallery" modal (the wp-admin–style verison).

### Steps to reproduce

1. Add a gallery to a page (example: Slideshow block) and add images to it.
2. Save the page and leave the editor.
3. If you're using the Calypso view, use Screen Options to switch to Classic/WP-admin view.
4. Edit the page and use the pencil icon to open the Edit gallery modal.
5. Attempt to change the images' positions with drag and drop.

### What you expected to happen

The images should be able to be rearranged—dropping a dragged image should insert it into a different place in the image order.

### What actually happened

You can "pick up" and drag an image, but attempting to "drop" it in a different position does nothing.

### Context

Two customer reports:

33432183-hc (using Slideshow block)
33858586-hc (using gallery inside Classic block)

Both Simple sites. Am also able to replicate on my Simple site, but not on Atomic so far.

GIF:

![ezgif-3-a663296493](https://user-images.githubusercontent.com/82622339/151070575-b40d3d59-c3b6-43e8-82ba-1b0af204a17f.gif)

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by ClassicRKR27** [comment]
I've got another report here: 33364218-hc

**Comment by tellisbethel** [comment]
Another report here: 4723208-zd-woothemes
Suggested user try the Block Editor which they're fine with now, but would like to know when a fix will become available.

**Comment by druesome** [comment]
Reported here as well: 4724475-zd-woothemes

Offered workaround for user which involves converting the slideshow to a gallery block, reordering them, then converting back to a slideshow.

Feel free to share this screencast:

https://d.pr/i/MkOrTt

**Comment by darnelldibbles** [comment]
Another report in the forums: https://wordpress.com/forums/topic/edit-54/?view=all

**Comment by jerrysarcastic** [comment]
Another report here, and confirming this bug also affects editing and reorganizing images in galleries created in the classic editor:  https://wordpress.com/forums/topic/problem-with-editing-galleries

Also noting that this seems to be reported to WordPress core here:  https://core.trac.wordpress.org/ticket/54902

**Comment by jartes** [comment]
Another reports on

- 4725719-zd-woothemes
- 4729380-zd-woothemes

**Comment by filipanoscampos** [comment]
Another case here:
4725596-zd-woothemes

**Comment by tellisbethel** [comment]
Another report here: 4719838-zd-woothemes
Follow-up/check-in from user here: 33951067-hc

**Comment by philnick206** [comment]
Reported here: 4720318-zen

**Comment by filipanoscampos** [comment]
Apparently, this is also affecting audio playlists.

Here is an example:
31580021-hc

**Comment by yaelirub** [comment]
Another report in the form of app review, even though its on mobile web 
<img width="647" alt="Screen Shot 2022-01-31 at 2 04 41 PM" src="https://user-images.githubusercontent.com/1335657/152036199-76a06bc2-31bd-405c-a90c-fed44a9dcf90.png">

**Comment by Gilmoursa** [comment]
Another report in 4740679-zd

**Comment by liviopv** [comment]
4742554-zen

**Comment by metabreakr** [comment]
https://wordpress.com/forums/topic/dragging-and-dropping-images-with-the-classic-editor/

**Comment by donalirl** [comment]
Another report in #15150005-hc with a gallery inside of the Classic block. Follow-up: 4745061-zen

Update: Followed up now that it's fixed.

**Comment by daria2303** [comment]
4746071-zd-woothemes gallery inside of the Classic block too

**Comment by filipanoscampos** [comment]
This is reported here, affecting the audio playlist:
4742076-zd-woothemes

There appears to be another [bug report specific to the Audio Playlists](https://github.com/Automattic/wp-calypso/issues/60648).

**Comment by tommusrhodus** [comment]
Another report of this in 4731465-zen

**Comment by alliebbush2** [comment]
Reported in 4746097-zen (please add to bulk replies)

**Comment by liviopv** [comment]
Another 33448965-hc

**Comment by thekingsprojects** [comment]
Another case here: 33382092-hc (Follow-up here: 4751263-zen )

**Comment by flameslash** [comment]
Reporting this here 4748769-zd-woothemes

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/gallery-widget-not-working/?view=all

**Comment by renata-franco** [comment]
Another one on Classic Editor: 4742302-zd-woothemes

**Comment by Greatdane** [comment]
Another report here; 4755686-zd-woothemes

**Comment by zdenys** [comment]
4760273-zd-woothemes

**Comment by rachelwinspear** [comment]
Another report here: 4755422-zen

**Workaround**
The drop and drag issue is visible in the Classic View (WP Admin), I asked the user to switch to the Default view, this way they have some control over the image order.

<img width="300" alt="Screenshot on 2022-02-08 at 17-41-38" src="https://user-images.githubusercontent.com/44442769/153034489-dec5c2ae-e0f8-4dab-ab8f-531084931e65.png">

<img width="1347" alt="Screenshot on 2022-02-08 at 17-44-06" src="https://user-images.githubusercontent.com/44442769/153034532-8762e03b-1221-4e5a-b6ea-1697a0d7212b.png">

**Comment by ClassicRKR27** [comment]
Another report here: 34074983-hc

In the Slack thread about this, @jp-imagines noticed that when accessing the page from Calypso it still directs to a `/wp-admin/` page so I'm not sure if the above workaround will fix it for all users.

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/cant-reorder-images/?view=all

**Comment by louinel** [comment]
Another case here: #4766389-zen

**Comment by markbiek** [comment]
Another report: 4767070-zd-woothemes

**Comment by nagpai** [comment]
It looks like this is a core WP.org issue that has been identified and fixed here 
https://core.trac.wordpress.org/ticket/54902

It will be released as a part of WP 5.9.1 (based on the milestone I see on the ticket)

(Props @jerrysarcastic )

**Comment by aleone89** [comment]
Another report here: zen-4746097 (Sketch)

Also further reports here: https://github.com/Automattic/themes/issues/5451

**Comment by MaxPhilip** [comment]
Another one 4770658-ZD

**Comment by masperber** [comment]
Another report: 33748925-hc

**Comment by donalirl** [comment]
Gallery within a classic block: #33861148-hc

Update: Followed up now that it's fixed: 4804568-zd-woothemes

**Comment by monicamardari** [comment]
Another case 4758039-zen

**Comment by ezebecke** [comment]
Another report: 34207537-hc

**Comment by zdenys** [comment]
Another case 4774755-zd-woothemes. Suggested the workaround from [above](https://github.com/Automattic/wp-calypso/issues/60469#issuecomment-1022992827).

**Comment by ClassicRKR27** [comment]
Another report here: 28719851-hc

User would like to be notified when it's fixed if possible. [SA](https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=hdluzagreb)

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/dragging-and-dropping-images-in-a-gallery/?view=all

**Comment by edwinho89** [comment]
4783584-zd-woothemes

**Comment by kingsleyinfo** [comment]
Another report here: 4783584-zd-woothemes

**Comment by JessBoctor** [comment]
I ran into this issue with a customer who was only using the Classic Editor, not switching from blocks: 
21659148-HC

**Comment by ariel-maidana** [comment]
Another report here: 20263327-hc

**Comment by villanovachile** [comment]
Another report 4789364-zen

**Comment by aleone89** [comment]
Another report hc-34089789

**Comment by the-misha** [comment]
Another report: 20166877-hc

User would like to be contacted when this is resolved: 4793056-zd-woothemes

**Comment by Greatdane** [comment]
Setting this to high priority based on the number of affected users.

**Comment by xuexue28** [comment]
Another report here: 4789672-hc

**Comment by villanovachile** [comment]
This issue should now be resolved with the release of 5.9.1: p9o2xV-1TP-p2

**Comment by KokkieH** [comment]
Confirmed it's now working for me.

I've followed up on the forum threads reported above.

**Comment by KokkieH** [comment]
A user in https://wordpress.com/forums/topic/problem-with-editing-galleries/ confirmed that it's now working for them as well.

**Comment by Greatdane** [comment]
Tested and can also confirm it is back working. @Automattic/dotcom-pa-group will now reply to all users noted on this issue. 👍

**Comment by jordesign** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.
Thanks for the reports, please let us know here if you see any future recurrence of the issue.
