### ISSUE TITLE
Live Chat blocks "Add record" on domain records page

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#60478]
### Quick summary

A user in live chat brought to my attention that the "Add record" button when managing domain records is hidden when live chat is open. 

### Steps to reproduce

1. Have live chat open as a user
2. Navigate to domains, then go to manage records page
3. The "Add a record" button is hidden because of the live chat window.

### What you expected to happen

Users should still be able to see the "Add a record" button with live chat open.

### What actually happened

No button is visible on the page.

### Context

A user reported in chat that they were't able to see the button and I did my own test with happy chat, confirming this is an issue.
![Markup on 2022-01-26 at 11:34:05](https://user-images.githubusercontent.com/83020905/151094670-ab3ca33f-29ca-45aa-93df-72878df3f1af.png)

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The live chat has to be closed for the button to appear, which is not a good experience if the user is hunting for a UI element.

**Comment by delputnam** [comment]
Nomado is tracking this on our Asana sprint board now.  We'll update the issue once we've merged a fix.
