### ISSUE TITLE
AMP: turn off "Redirect mobile visitors to AMP" on Atomic sites by default

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#60483]
### What

When a site is moved to the Atomic platform, the AMP plugin is automatically installed and configured to `Redirect mobile visitors to AMP` on AMP > Settings > Other with no warning to the user.

This feature makes the site load only AMP versions on mobile, which can cause numerous issues considering the number of plugins and themes that are not compatible with AMP.
![Markup on 2022-01-26 at 10:35:02](https://user-images.githubusercontent.com/14153300/151148000-5f3a31ea-3e2d-49c6-96b8-61399ec6fc9e.png)

### Why

The number of plugins and themes that are not compatible with AMP has increased, including Elementor, WPForms, the Varia themes and more. Because we don't explain what's AMP and how aggressive AMP settings can be, users are usually unaware of this until they try to load their site on mobile, which usually leads to complaints that the site is "broken" since the AMP version is unable to load JS and certain CSS files.

Checking the recent chats tagged with the `seo_amp` tag shows how prevalent the issue is on support.

**Comment by liviopv** [comment]
33604686-hc

**Comment by khristiansnyder** [comment]
I agree with this as well. I have had quite a few users in chat lately wondering why their mobile site doesn't match their desktop site's theme.

**Comment by liviopv** [comment]
4724908-zen

**Comment by liviopv** [comment]
33913047-hc

**Comment by Greatdane** [comment]
@liviopv I agree with this, but are we sure when going Atomic, all sites have this turned on by default? I looked at a recent test site of mine and the setting is OFF.

**Comment by jartes** [comment]
Another one on 32910506-hc

**Comment by zdenys** [comment]
Another case 4801498-zd-woothemes User doesn't like how the WooCommerce Checkout Page appears when AMP is active, but when they exit the mobile version, it looks good and they like it.

**Comment by nagpai** [comment]
34322040-hc - Images were not appearing in AMP mode and it seems `Redirect mobile visitors to AMP` was enforced. Disabling this option set it right.

**Comment by nagpai** [comment]
33737724-hc - disabled redirect and switched to reader mode. Site had Varia theme base which is incompatible with AMP.

**Comment by zdenys** [comment]
4805532-zd-woothemes On a site with Storefront theme, the Standard mode in AMP stopped the menu button and checkout button from working on the mobile version. I recommended turning off AMP altogether.

**Comment by nagpai** [comment]
34128628-hc

**Comment by nagpai** [comment]
34371220-hc

**Comment by nagpai** [comment]
34232070-hc - We should at least put the option `Redirect mobile visitors to AMP` in a more visible spot. It is currently hidden within the last tab - `Other`.

**Comment by Greatdane** [comment]
4843219-zd-woothemes - another user's pages broken by AMP

**Comment by mcampal** [comment]
4848606-zen

**Comment by Greatdane** [comment]
34602216-hc

**Comment by nagpai** [comment]
4867320-zen

**Comment by Greatdane** [comment]
34313977-hc

**Comment by zdenys** [comment]
4874347-zd-woothemes

**Comment by syhussaini** [comment]
Another 35085939-hc interaction where the user did not like the site when AMP was active.
They loved the site after disabling the AMP.

The site was using an Astra theme.

**Comment by danielk-am** [comment]
> since your browser does not support JavaScript, or it is disabled, please ensure you click the Update Totals button before placing your order. You may be charged more than the amount stated above if you fail to do so.

Deactivated AMP fixed the WooCommerce's checkout page (Storefront theme).

35086502-hc

**Comment by zdenys** [comment]
4932184-zd-woothemes with Astra theme

**Comment by zdenys** [comment]
In a [wider context](https://wptavern.com/duckduckgo-and-brave-move-to-bypass-google-amp-pages-by-default):

>DuckDuckGo and the Brave browser announced they will be bypassing Accelerated Mobile Pages (AMP) in favor of serving publishers’ content on the original URL

**Comment by zdenys** [comment]
4963054-zd-woothemes

**Comment by vykes-mac** [comment]
I'm closing this issue as there is an ongoing project to remove AMP and doing this now will result in unnecessary work.

For more information on the AMP Removal project see: pdKhl6-48-p2
