### ISSUE TITLE
Marketplace: support Vendor information for each wpcom store product

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#60493]
For attributing revenue to the correct vendor of each product we will need a way to link each product with their vendor (eg `woocommerce`, `yoast`).

Related convo: pdh6GB-1b-p2#comment-514

**Comment by cpapazoglou** [comment]
@michaeldcain can we go ahead and add a `vendor` column in the `store_products` table?

**Comment by michaeldcain** [comment]
To circle back: we ended up having this conversation on the linked P2 and additionally in Slack (p1643907635701219-slack-C0117V2PCAE), opting for two new tables to separate product-specific logic from Store logic.

**Comment by cpapazoglou** [comment]
Created a systems request here pMz3w-eDW-p2

**Comment by cpapazoglou** [comment]
https://opengrok.a8c.com/source/search?project=calypso&project=jetpack&project=matticspace&project=mc&project=trunk&full=test

**Comment by cpapazoglou** [comment]
Tables are created here D75033-code

**Comment by cpapazoglou** [comment]
Added the vendor information for the current marketplace items
