### ISSUE TITLE
Google Apps: Enable Google Apps for Mapped Domains

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#605]
We disabled `Google Apps` purchase for `Mapped Domains`. It wasn't working properly when user didn't provide user address during checkout.

The goal of this task is enable back `Google Apps` for `Mapped Domains`. This time we need to make sure that user address is always provided when we purchase `Google Apps`. That means if users didn't provide their address before, they need to provide it before finishing checkout.

Comment from @Lochlaer:

> Just wanted to note here that these are what Google requires in order to fully provision a domain for Google Apps:
> 
> FirstName
> LastName
> OrganizationName
> AlternateEmail
> Address*
> CountryCode
> PostalCode
> Username**
> 
> *Google has previously announced that they were no longer requiring address validation in the Gapps signup flow, but that seems to be broken at the moment. Every time I manually provision a domain, it kicks back an error message when I don't enter an address. Dennis James at Google has been notified, and he's looking into it.
> 
> *\* This refers to the username they want for their Google Apps domain, e.g., _john_ if they want _john@mydomain.com_, etc.
> 
> For more information on what the API requires, please refer to [here](https://developers.google.com/admin-sdk/reseller/v1/how-tos/manage_customers).

**Comment by breezyskies** [comment]
After another look at this, I think we should be able to handle this without using the domain registration details form data:

> FirstName
> LastName

We're currently using placeholders for this even with registered domains, so no change here.

> OrganizationName

This seems like an optional field (given that it's optional in our domain registration details). At a minimum, we must already have a fallback in place.

> AlternateEmail

We should automatically be sending their account email address for this.

> CountryCode
> PostalCode

I'm guessing we're currently sending the data we collect in the domain registration form, but we collect both of these in the checkout form too. 

> Username**

We collect this in the Google Apps form.

> Address*

As @Lochlaer mentioned above, this is supposed to be no longer required (and seem to be the case according to their docs. 

----

A last option would be to have conditional fields for the Google Apps for when a user is missing certain info, or use a minified version of the `Domain Registration Details` for collecting that info separately, but I think given the breakdown above, we should be okay to relaunch without any design changes. 

Thoughts?

**Comment by klimeryk** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/10843 🎉
