### ISSUE TITLE
Color Picker for Paragraph Block: Hex Color code input not working as expected

### ISSUE THREAD

**Issue by jackiejade** [Automattic/wp-calypso#60507]
### Quick summary

When going to edit the color of text in a paragraph in the page/post editor, if you want to put in your own hex color code, you are unable to type into the box. The box keeps defaulting to #000000 As seen in this screencast:
https://d.pr/i/sxLf0K

### Steps to reproduce

1. Write a new paragraph of text using a Paragraph block
2. Highlight a word that you'd like to change color
3. Click on Highlight, then click on the little picker icon
4. Try to input your own color code by typing
<img width="443" alt="Screen Shot 2022-01-26 at 2 43 40 PM" src="https://user-images.githubusercontent.com/8549154/151235252-53ce2691-772d-48ea-9a52-38b0afd72c54.png">

### What you expected to happen

I expect to be able to type my own hex color code in. 

### What actually happened

Not able to type in the box, it just keeps defaulting to #000000; 

### Context

You **can** copy/paste the hex code in, but this is not always something a user might know to do. It also doesn't look like it's sticking if you paste it in. 

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

I tested on Mac in Firefox, but my user who had this was in Windows on Chrome. 

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

You can put in a hex code by copy/pasting in the box, but it still doesn't look like it worked - even though it does work.

**Comment by jackiejade** [comment]
Forgot to put the user transcript: 33875036-hc

**Comment by dcoleonline** [comment]
another in 4725572-zen
we should notify them once this is fixed.

**Comment by formosattic** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/59566 , and will track the user reports on it.
