### ISSUE TITLE
Seller Experience: Simple versus power choice buttons are incorrectly aligned.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60517]
The buttons are currently aligned to the top of their section, whereas in the Figma, they're aligned to the top of the description section.

| Current | Figma |
| --- | --- |
| <img width="662" alt="Screen Shot 2022-01-26 at 2 40 21 PM" src="https://user-images.githubusercontent.com/349751/151259673-e47c5e0b-8a72-4424-8c45-ecf9c5381ce4.png"> | <img width="638" alt="Screen Shot 2022-01-26 at 2 40 28 PM" src="https://user-images.githubusercontent.com/349751/151259679-fecdb959-8e8c-4a74-af5b-6b4c50487c77.png"> |

**Comment by kwight** [comment]
I'm not sure which this should be – it looks like the intent selection (the same component we're using for the simple vs. power choice) has the button aligned at the top:

<img width="642" alt="Screen Shot 2022-01-26 at 2 44 02 PM" src="https://user-images.githubusercontent.com/349751/151259886-437e0091-9ca7-4c84-b4f2-dad55760bde2.png">

@SaxonF do you prefer we stick with the existing component alignment, or change it to match the Figma?

**Comment by SaxonF** [comment]
@kwight Let's stick with existing component alignment. Thanks!
