### ISSUE TITLE
Stewart: Group block in demo content shows error

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#60510]
### Quick summary

After activating Stewart and choosing to use its demo content on a Simple WordPress.com site, the group block below the Site Title displays a block error.

### Steps to reproduce

1. Activate Stewart on a Simple site
2. Choose the option to replace the homepage content with the demo content

### What you expected to happen

No block errors should be present

### What actually happened

Just below the Site Title, the group block displayed an error:

> This block contains invalid or unexpected content
![New_‹_Site_Title_—_WordPress_com](https://user-images.githubusercontent.com/7662449/151239941-667d2cdb-449e-4521-bd47-21194a54770f.jpg)

### Context

Testing, no user report.

### Theme-specific issue?

Stewart

### Browser, operating system and other notes

Firefox 96.0.2
MacOS 2.0.1

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
Hey @kathrynwp! Thank you for reporting this!

I'm not able to replicate the issue anymore. Could you double-check if it's still happening, please?

**Comment by kathrynwp** [comment]
@Robertght Thanks for trying to replicate! 

Strangely, I'm no longer able to get **Stewart** to come up, in order to try activating it on another site. I've tried several different sites now:

![WordPress_Themes_‹_Global_Styles_Demo_—_WordPress_com](https://user-images.githubusercontent.com/7662449/151708723-9fe23162-a000-4d8d-9597-9c48a41d3a8c.jpg)

**Comment by kathrynwp** [comment]
I was finally able to re-activate Stewart by switching to another theme, adding the `fse-eligible` sticker to the site, clicking the FSE - Beta tab in the showcase, and scrolling down to find Stewart.

I was **not** able to replicate the issue, so will go ahead and close this.
