### ISSUE TITLE
Add data-hello="world" attribute to the wp-admin options screen in order to test wpcom deployment process

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#60523]
You can access the wp-admin options screen by:
Opening a sandboxed test site.
Going to settings->general 
Opening "Screen Options" in the top right corner of the screen
Selecting "Classic View"
<img width="1100" alt="Screen Shot 2022-01-27 at 10 27 04 am" src="https://user-images.githubusercontent.com/22446385/151269746-deafc167-cbc8-4bc7-81ca-e763edae88e7.png">

You will then be taken to the wp-admin options screen.
Note that the URL has changed, you are no longer on wordpress.com, but are now on your sandboxed test site's domain, in the old `wp-admin` options page.
<img width="1728" alt="Screen Shot 2022-01-27 at 10 29 25 am" src="https://user-images.githubusercontent.com/22446385/151269763-102756ec-faa0-40e8-b79d-76042c6948e3.png">

The task is to add another `data-hello="world"` attribute to the `#options-general` element

**Comment by roo2** [comment]
reopening this issue for @bangank36  and @miksansegundo

**Comment by bangank36** [comment]
Diff D79572-code

**Comment by miksansegundo** [comment]
@roo2 Here is the Diff D79681-code
