### ISSUE TITLE
Marketplace: don't show Marketplace products on Jetpack sites

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#60552]
The plugins browser has a guard condition to prevent showing Marketplace products on Jetpack sites:
https://github.com/Automattic/wp-calypso/blob/b04a7ff6afb3475990589b9d1efd55af67ea92d3/client/my-sites/plugins/plugins-browser/index.jsx#L221

However, when searching for plugins, the search results still contain Marketplace products:
![image](https://user-images.githubusercontent.com/11555574/151387421-f1e76f6b-c5f2-422b-9000-584de2d6715d.png)

We should add the same guard condition to avoid showing Marketplace products on Jetpack sites anywhere for now.

**Comment by cpapazoglou** [comment]
What if we allow the search visibility so that users have a chance to check "Keep me updated" as @WBerredo  suggested?

<img width="1095" alt="SS 2022-01-31 at 16 15 14" src="https://user-images.githubusercontent.com/12430020/151809309-16abc956-401c-47e6-b095-c375ad2bfe9c.png">
