### ISSUE TITLE
Marketplace: Featured WP.com and WP.org products in plugins browser

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#60553]
We are currently showing a featured section with paid plugins and we have hidden the featured free plugins. Should we try enabling again the featured free plugins?

section missing
![SS 2022-02-03 at 11 02 08](https://user-images.githubusercontent.com/12430020/152311961-29dce466-3ed6-4ec4-8f02-07936a902ec7.png)

**Comment by SaxonF** [comment]
Could you expand on this a little bit @gcsecsey ? By `plugins browser page` do you mean in wp-admin?

**Comment by gcsecsey** [comment]
We've discussed this as a follow-up ticket to #59899 on last week's demo (the recording's [linked on this P2](pd8D2H-Z1-p2), this discussion starts at 7:50).

Sorry @SaxonF, I've rewatched the recording now, and we might be only meant to create a segment for the marketplace products within the API response. @cpapazoglou could you please clarify, I may have misunderstood on the call? 🙂

**Comment by cpapazoglou** [comment]
@SaxonF can we reframe this issue to

“We are currently showing a featured section with **paid** plugins and we have hidden the featured **free** plugins”, should we try enabling again the featured free plugins?

**Comment by gcsecsey** [comment]
Thanks for the update @cpapazoglou, I've also changed the issue description for clarity.

**Comment by SaxonF** [comment]
Thanks for clarifying! I've added to the [design backlog](https://github.com/orgs/Automattic/projects/346/views/4)

**Comment by obenland** [comment]
[Let's go with the titles "Featured Premium Plugins" and "Featured Free Plugins"](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/plugins-browser/index.jsx#L456-L463) and [move the block of featured free plugins out of the `jetpackNonAtomic` check to show them again to everyone](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/plugins-browser/index.jsx#L556-L560).

@gcsecsey Did I get those code references right?

**Comment by SaxonF** [comment]
Until we have the ability to mix in free plugins with paid, a slightly alternative to what's proposed here is to create two groups under the featured collection. (excuse the dummy content).

![image](https://user-images.githubusercontent.com/1072756/153125857-b32aa936-da23-4a46-8fa8-d5d259c3c632.png)

**Comment by obenland** [comment]
Is that a _possible_ alternative or what should be built?

For context, bringing back that section without change is a matter of minutes—creating something like what is shown in that image multiple days of work. Which is fine, I just want to be clear about the expectations

**Comment by SaxonF** [comment]
@obenland could we bring back the free section without change as a first step, and then move it into the featured section + update featured card design as part of the `3. Feature prominence` release in the `upcoming-marketplace-releases` post?

**Comment by allilevine** [comment]
First section is "Premium", add second "category" called "Featured".

**Comment by lsl** [comment]
For added context, we're scoping this to:

- [ ] Renaming "Featured" (currently only paid plugins) to "Premium" and 
- [ ] "bringing back that section without change" under the heading "Featured"

**Comment by cpapazoglou** [comment]
After bringing back the free featured, please make sure popular plugins are filtered with 

https://github.com/Automattic/wp-calypso/blob/5de2130570dc8df22ee4c653b8ec25550b01eacf/client/my-sites/plugins/plugins-browser/index.jsx#L710

**Comment by lsl** [comment]
@cpapazoglou apologies, I saw your comment then proceeded to forget while I was merging the other PR's I had open, I ended up shipping #61098 as is. I've added a follow up https://github.com/Automattic/wp-calypso/pull/61144 to always filter the popular plugins and remove duplicates.
