### ISSUE TITLE
Playwright: Refactor `CloseAccountFlow` to use `visit` instead of UI navigation.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#60572]
### Details

We are seeing increased occurrences of the CloseAccountFlow flaking out in recent days, especially after https://github.com/Automattic/wp-calypso/pull/60329 has been merged in to fix the failing Pre-Release Tests build.

With recent changes to the framework, we are in a good state to move off of purely UI navigations. Consider:
- using a `visit` method to navigate to the `/me` endpoint.

### Related

https://github.com/Automattic/wp-calypso/issues/60555

**Comment by worldomonation** [comment]
Duplicate of #60555.

**Comment by worldomonation** [comment]
@dpasque I'm going to re-open this issue, since I think the changes I proposed is still worth doing to make this flow behave more reliably.

**Comment by dpasque** [comment]
Oh yes, good call! I had considered doing this at the time, but I wasn't sure we wanted to do this for all the flows and wanted to get that quick fix out asap. I really like this idea!

**Comment by youbrokesomething** [comment]
This was done in #60835
