### ISSUE TITLE
Woo installer: "Please select an item in the list" error on business info step

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#60588]
<img width="483" alt="Screen Shot 2022-01-27 at 4 33 42 PM" src="https://user-images.githubusercontent.com/1689238/151447449-411fc087-cea5-406b-9a21-0a19376c9984.png">

To reproduce:
- Go through the Woo installer flow and don't select anything for "Which platform is the store using?"
- Click Continue

**Comment by obenland** [comment]
With the forms now being converted to actual forms, I recon we could probably remove the manual validation we're doing and rely on `required` attributes in inputs? cc @lsl

**Comment by lsl** [comment]
My first pass at validation on these screens was to turn them into forms and add `required`. :smile: 

The issue with that approach was that we can't style those errors in the same way as the rest of calypso, e.g. settings screen:

![Screenshot 2022-01-28 at 14-02-32 My Profile — WordPress com](https://user-images.githubusercontent.com/811776/151480068-febeb151-0fb0-458e-b972-dc2bafced122.png)

---
In this case, we have a sneaky `required` value [on the dropdown](https://github.com/Automattic/wp-calypso/blob/177bfb4905aac1e8c8460a946ee12c359b99f400/client/signup/steps/woocommerce-install/step-business-info/index.tsx#L208). Fix here: https://github.com/Automattic/wp-calypso/pull/60607

**Comment by lsl** [comment]
#60607
