### ISSUE TITLE
Seller experience: Consider incorporating the videos UI for education.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60580]
We now have a videos UI feature that could help educate sellers going through the seller experience onboarding. Let's consider how we can incorporate it, and what videos we have underway that could be appropriate.

See: p1643295428315000/1643266622.311500-slack-C029UPVMGTW

**Comment by valterlorran** [comment]
An educational video was added to the modal that pops up when we click the "Learn more" button on `/woocommerce-installation/YOUR-SITE-SLUG` page. 
<img width="1009" alt="Screen Shot 2023-03-16 at 16 19 48" src="https://user-images.githubusercontent.com/1234758/225755180-ba759bbd-0787-41ad-9d79-91cf5c4130b7.png">
