### ISSUE TITLE
Video in Cover block not displaying on mobile

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#60597]
### Quick summary

Video in Cover block on homepage displays correctly on desktop site, but shows as a black block on mobile (iPhone).

### Steps to reproduce

Load site on iPhone.

### What you expected to happen

Video in Cover block should autoplay.

### What actually happened

Site displays a black rectangle where the Cover block video should be.

### Context

Customer report: 4726583-zd-woothemes. Reproduced on my personal device.

### Simple, Atomic or both?

Atomic

### Browser, operating system and other notes

iPhone 11 / Safari mobile browser.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by cuemarie** [comment]
Hey! I was able to get a Cover Block with video content to respond appropriately on mobile. AT site.

On my iPhone+Safari browser it took a little time to load before it played, but the image appeared right away. On my iPhone + Chrome browser it loaded right away, see brief recording below:

https://user-images.githubusercontent.com/27249804/152208886-badc2a6b-ecbc-45af-8e17-770edaf78dcd.mp4

I ran this test after playing into the ticket and responding with some workaround options, but perhaps there's something particular to their site that can be tested?

The video I used was downloaded from Pexels free media library; details here: 

![Markup on 2022-02-02 at 10:48:53](https://user-images.githubusercontent.com/27249804/152209193-8a18f6ac-4653-42d4-956f-d7d951c4a282.png)

**Comment by sajmes** [comment]
It's possible this is down to the video file itself. I added the user's .mp4 version next to a Pexels .mp4 on a test AT site here: https://2twentythree2021.wpcomstaging.com/24-2/

The top video (user's) does not load on mobile, while the bottom video (Pexel) does. Both were uploaded to the Media Library and then added to a Cover Block.

I thought this could just be due to size but the Pexels is 7.3MB while the user's is 10.6MB. Asked for a different version of video.

**Comment by arunsathiya** [comment]
4770116-zen; offered to followup once we have an update.

**Comment by jp-imagines** [comment]
I came across what I think is an instance of this in 36336520-hc, but it's a simple site.

On my phone, I saw a black rectangle (the user said they saw a white background on their phone). It sometimes had a "glitchy" colored appearance on my end, though I wasn't able to get a screenshot of that in time.

Video worked just fine in a Video block.
Changing file type (.mov to .mp4) didn't help.

**Comment by lupus2k** [comment]
After some deep tests, we closed this issue because it is working without problems.

Slack discussion: p1673568463199649-slack-C01LXBU1N21
