### ISSUE TITLE
Investigate FSE Compatibility

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#60608]
### **Are imported sites FSE enabled?**
Importing a site does not change the FSE status of a site. Whether or not a site supports FSE depends on which theme is selected. If an FSE theme is selected, it automatically enables the editor. Importers (except the full site migration) do not affect anything related to themes and theme settings.

### **If they are not, what does it take to enable FSE on them?**
Confusingly, at this time, the `is_fse_eligble` sticker is shown on the Blogs RC. It must be noted that this sticker is deprecated. All sites do now support FSE if an appropriate theme is activated.

### **When we import (via WP migration) from an external WP site, is the imported site FSE?**
Only if an FSE enabled theme is selected. In case of doing a full site migration from a site that has an FSE theme activated, the target site will also have the FSE theme selected and the editor can be used.

### **When we import (via WXR upload) from an external WP site, is the imported site FSE?**
WXR uploads do not affect themes and settings related to themes. WXR (and importers that use WXR under the hood) only import content (posts, tags, categories, attachments) and meta data. 

### **How many of our non-WordPress importers can generate an FSE-compatible site?**
None - our importers only import content and do not affect which theme is activated or settings related to themes.

### **Of the ones that are not compatible, what is the quantum of work required to make them FSE compatible?**
No further work is required.

## Tests to be done: ##

- [x] Check if WordPress sites that are not hosted on Jurassic Ninja are properly migrated.
- [x] Look at some recent migrations by random users to see if template issues are happening for others.
- [x] Migrating site with FSE template activated to a new site through the new onboarding flow.
- [x] Migrating site with FSE template activated to a new site through the /new add new site flow.
- [x] Migrating site with FSE templated activated to an old atomic site.
- [x] Migrating a site with a non-FSE template activated to an atomic site that has FSE activated.
- [x] Conclude the investigation into issues with full site migrations from Jurassic Ninja sites. pcmemI-ol-p2

Under the hood, the migration logic should be working exactly the same regardless of which flow is used. We need to verify that:

- If an FSE theme is migrated, the 'editor' option under 'appearance' should be visible.
- Going to the Appearance -> Editor page should display the correct theme without any errors and it should be possible to successfully make changes.
- Viewing the website should display the correct theme. The style should be correctly applied and all pages should work properly.
- If a non-FSE theme is migrated, it should be selected and there should NOT be an 'editor' menu option under 'appearance'.
- If a non-FSE theme is migrated, it should be possible to switch to an FSE theme under  Appearance -> Themes, if such theme is available in the list.

**Comment by vishnugopal** [comment]
Discussion:
* Maybe we want to enable Full Site Editing when we migrate a FSE theme from a Jurassic Ninja site.
* P2 post incoming with observations.
* View Site is coming up empty, at the end of the page! [after the import happens]
* This happens even with new Atomic sites.
* All other imports (aside from migration) should not be affected.
* Please check Wix as well. This should work fine because only post content is changing, not themes etc.

**Comment by vishnugopal** [comment]
We're blocked on themes not being migrated at all (either FSE or not FSE).

**Comment by vishnugopal** [comment]
Discussion:
- Turns out after further testing that migrating a theme that does not exist on WP.COM Atomic does not work.
- The theme simply doesn't exist. More here: pcmemI-ol-p2
- Plugins seem to be fine, just themes don't seem to work.
- Even custom themes (that are not in the WPCOM directory, and just in the dotOrg repo) are not being transferred over.
- Could this be a problem with Jurassic Ninja sites?
- Let's test this with a real site hosted somewhere else (not on WPCOM, maybe some other provider)

**Comment by jeroenpf** [comment]
While we are still waiting for feedback regarding issues with theme installations during the migration (pcmemI-ol-p2), I have tested the other importers.

The conclusion is that all importers other than the full site migration, do not affect anything related to FSE. Site settings, theme settings, colors, etc. are not influenced by importers. Under the hood, all these importers convert their content into WXR and finally use the same logic to insert this content at the target site. This is independent of what flow is used (onboarding vs. selecting tools -> import vs wp-admin).

**Comment by jeroenpf** [comment]
The pending issues with migrating themes has been resolved. We were not able to replicate this issue.

Further details: pcmemI-p9-p2#comment-560
