### ISSUE TITLE
Add warning when deleting payment method assigned to a subscription

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#60629]
When a payment method is removed, it will be removed from any active subscriptions that it is assigned to. However, this could be confusing for users if they don't realize that this may cause their subscription not to auto-renew. 

It may be a good idea to warn a user before the payment method is deleted, perhaps with a confirmation modal, that the payment method is assigned to something.

**Comment by DavidRothstein** [comment]
Somewhat related internal issue: 265-gh-Automattic/payments-shilling

Also some discussion in the recent Slack thread (p1643386707312529/1643360903.748149-slack-C0117V2PCAE), including @sirbrillig's point about the need to consider backup payment methods in any messaging here.

**Comment by DavidRothstein** [comment]
From pNPgK-6Dr-p2 we should make sure that any warning here also somehow references subscriptions that the payment method is assigned to but that are from a service that is **not** otherwise managed on WordPress.com (for example, something other than WPCOM/Jetpack/Akismet).

**Comment by Aurorum** [comment]
I tried exploring this a little in #95176.

<img width="745" alt="Screenshot 2024-10-06 at 23 44 27" src="https://github.com/user-attachments/assets/73611abd-8f4f-4c3f-bf38-ff78072dd63e">
