### ISSUE TITLE
No validation error for empty cardholder name on add-card form

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#60628]
Originally reported by @vitozev in Slack.
![Screen Capture on 2022-01-28 at 10-15-08](https://user-images.githubusercontent.com/2036909/151581758-cb9373d5-3371-4c21-b1a8-a84fa9ddfda0.gif)

**Comment by DavidRothstein** [comment]
We can hopefully just throw an exception when there is no cardholder name (similar to what we do for country/postal code).

**Comment by sirbrillig** [comment]
Worth noting that this issue also exists in the checkout new card form.

I think this may have been an accidental regression caused by https://github.com/Automattic/wp-calypso/pull/57212, specifically this removal:

https://github.com/Automattic/wp-calypso/blob/d42ff0aeb7ef8e0b21f585b637a885e57a5fa5e9/client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-fields.js#L37-L39

We removed the `isRequired` machinery because it is no longer needed by the contact details fields, but there are other fields which may have relied on it.

There are several places to restore this error by making `cardholderName` a special case (which it already is), but this did lead me to investigate how validation for other non-contact fields is supposed to work: the `validatePaymentDetails` function which predates the checkout redesign.

https://github.com/Automattic/wp-calypso/blob/9b99572e443410da5e45dac96e0f74be01939f8b/client/lib/checkout/validation.js#L333-L347

https://github.com/Automattic/wp-calypso/blob/9b99572e443410da5e45dac96e0f74be01939f8b/client/lib/checkout/validation.js#L63-L68

While we are using that function in the [ebanx form](https://github.com/Automattic/wp-calypso/blob/9b99572e443410da5e45dac96e0f74be01939f8b/client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.js#L142), we are not using it for the Stripe fields. This is probably because we can no longer read the card number, expiry, and CVV data (it's all handled internally by Stripe) so we must rely on different machinery to display those errors:

https://github.com/Automattic/wp-calypso/blob/9b99572e443410da5e45dac96e0f74be01939f8b/client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-fields.js#L65-L83

I wonder if there's a way to utilize `validatePaymentDetails` for the cardholder name as well? In any case https://github.com/Automattic/wp-calypso/pull/60854 should resolve the immediate problem.
