### ISSUE TITLE
Checkout: Can't use PayPal to pay for Jetpack Plan

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#6062]
#### Steps to reproduce
1. Add a new Jetpack Plan to your cart
2. Proceed to checkout
3. Only presented with credit card as an option: 
   ![screen shot 2016-06-15 at 1 01 54 pm](https://cloud.githubusercontent.com/assets/831377/16089946/70055538-32fb-11e6-910f-05f1fd80419d.png)
#### What I expected

As with a WordPress.com plan purchase, you should be able to click a "Use PayPal" link instead.
![screen shot 2016-06-15 at 1 04 02 pm](https://cloud.githubusercontent.com/assets/831377/16089973/8913cf14-32fb-11e6-9a49-1f556e02d07c.png)

**Comment by jeherve** [comment]
Also reported in 2935055-t

**Comment by jeherve** [comment]
Also in 2943232-t

**Comment by richardmtl** [comment]
3034254-t

**Comment by tmmbecker** [comment]
3057476-t

**Comment by jeherve** [comment]
This was fixed; one can now use Paypal to purchase a Jetpack plan:
https://jetpack.com/2017/03/06/now-accepting-paypal/
