### ISSUE TITLE
Invalid SSL certificate at domain wpcomjs.com

### ISSUE THREAD

**Issue by fjorgemota** [Automattic/wp-calypso#60621]
### Quick summary

The SSL certificate of the domain wpcomjs.com linked at the README of this repository is invalid. It looks like a generic SSL certificate valid only for wordpress.com and its subdomains.

### Steps to reproduce

1. Visit the README of this project;
2. Click on the wpcomjs.com link at the top of the README;

### What you expected to happen

The browser redirected to https://www.npmjs.com/package/wpcom properly, without any SSL errors.

### What actually happened

The browser warned about an SSL certificate error.

### Context

Nothing, really, I was just reading a bit more about wp-calypso and found this small error. :)

### Reproducibility

Consistent

### Workaround details

You can inform the browser to ignore the the SSL certificate error, and then the redirect works properly.

**Comment by edequalsawesome** [comment]
This is now fixed! p1645742790853769-slack-opers

**Comment by fjorgemota** [comment]
Nice! Closing the issue then =)
