### ISSUE TITLE
Themes: Try & Customize not available on all themes

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#60623]
### Quick summary

As discussed in p1643257193253600-slack-C029FM1EH, I'm raising this as a report so it can be looked into going forward.

### Steps to reproduce

Some themes have the Try & Customize options while others, especially new ones(Varia/Blocksbase) do not.

### What you expected to happen

See it as others that have it

### What actually happened

No option is provided

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Yes

**Comment by mreishus** [comment]
Hello,
We did this intentionally in this issue: https://github.com/Automattic/wp-calypso/issues/59991
I believe it's related to the FSE changes. [From this WordPress.org blogpost](https://make.wordpress.org/core/2022/01/07/state-of-the-customizer-with-block-themes-in-wordpress-5-9/)
>"WordPress removes the Customizer from the Appearance menu if a block theme is enabled." 

I believe we're trying to stay consistent with that. @sixhours would know more but isn't available today.

**Comment by sixhours** [comment]
👋 In #60251 I updated the logic to hide "Try & customize" when viewing the site preview ("Live demo") to be consistent with the existing behavior. "Try & customize" has been hidden for newer themes (ones tagged "global-styles" or "auto-loading-homepage") since 2019 in #37378

**Comment by msilbers** [comment]
This is a bad experience for customers! I have one who is now afraid to change themes. 33911246-hc
I have provided the workaround to click Preview from wp-admin, which I don't see explained anywhere for a customer who was used to Try & Customize

**Comment by kspilarski** [comment]
I have the same user case in `4761509-zd`. User cannot try and customize. The three dots next to the theme name and the live demo used to have "try and customize", now it's only "Activate".

**Comment by monicamardari** [comment]
Another case here 4786128-zen

**Comment by kerrynicl** [comment]
Preview from wp-admin does allow some "Try and Customize" experience for users,  Is it possible to reinstate that with a notification that the theme is a FSE theme so customizations will need to be done in site editor once activated

https://user-images.githubusercontent.com/83325600/155574064-be642a68-bbb0-45c0-bb58-96623b7584fe.mp4

**Comment by gabriel-fuentes** [comment]
Another one here: 4815590-zen

**Comment by gabriel-fuentes** [comment]
Another case here: 4829211-zen

**Comment by ai2n** [comment]
Another one 33786695-hc

**Comment by jamiepalatnik** [comment]
Another request: 34616692-hc

**Comment by mdtanjid0** [comment]
35261790-hc

**Comment by rw-ye** [comment]
Another report here: 5198285-zd-woothemes

**Comment by jp-imagines** [comment]
Another report in 5199169-zd-woothemes.
This user isn't on a block/FSE theme and isn't necessarily looking to switch to FSE. They just want to look at other themes with their content without needing to make changes to their live site (and then have to go through time-consuming site restores if they don't like the change). 

---

I know FSE themes rely on the Customizer, but newer classic themes (like Twenty Twenty One and Varia child themes) should still have this option available.

On Simple sites, the WP Admin theme page (`/wp-admin/themes.php`) seems to allow you to preview _any_ installed theme, including block themes.
On Atomic sites, the WP Admin theme page allows a preview of any installed classic theme (but not block themes).

Installing a .com theme without activating it isn't something users can easily do independently, so this requires HE intervention.

**Comment by jp-imagines** [comment]
And another in 5201094-zd-woothemes

From the user: 
> none of the themes are giving me an option to preview with my site before activating. I don't want to activate blind.

**Comment by sharonlaker19** [comment]
+1 at 35815640-hc

Edited to add: I've run multiple tests, and the workaround to use the wp-admin view doesn't work for FSE and hybrid themes.

**Comment by jp-imagines** [comment]
Another report in here: 36541582-hc – user was confused by the missing "Try & Customize" option on our Recommended (FSE/block) themes.

**Comment by tanjoymor** [comment]
Another report here: 36645800-hc – user was also looking for the Try & Customize option. I offered the alternative to use the "Preview" feature under the Classic View, however, that is not currently working (even though it was in the recent past), it's loading the Customizer and the sidebar, but a blank screen in the main panel.

**Comment by Addison-Stavlo** [comment]
Im going to bump this back to the triaging column and out of Cylon team. cc @cometgrrl 

Im really not sure what we are expected to do here, it seems in the  comments above ([1](https://github.com/Automattic/wp-calypso/issues/60623#issuecomment-1024314783) and [2](https://github.com/Automattic/wp-calypso/issues/60623#issuecomment-1025850208)) this consistent with / due to core functionality - and im not entirely sure when/how we can get to this.

That being said, I imagine new Marvel group now focusing more on the theme experience, this might be a good fit there? cc @ianstewart

**Comment by cuemarie** [comment]
@Addison-Stavlo Are you looking for another round of triaging (trying to replicate) here, or just for a new conversation and focus on the issue?

For now, I've moved to `Prioritize & Assign` to get looked at by the Quality Squad.

I've also tagged this as a Feature Request - my understanding is that not all themes have this feature, so rather than reporting a bug where something _should_ be working, we're discussing adding this capability to all themes.

**Comment by staproehl** [comment]
8317392-zen

**Comment by supernovia** [comment]
Can we just make sure that all FSE themes have the Preview and Customize option now? Most of ours do, but Twenty Twenty Four did not in this interaction. 8317392-zd-a8c

**Comment by ianstewart** [comment]
@okmttdhr @taipeicoder would you be able to take a quick look here to see if this is a quick bug fix or something that needs more attention.

**Comment by okmttdhr** [comment]
“Try & Customize” is no longer accessible anywhere on Calypso currently since we removed the More menu. We should consider adding it to the Theme Details page behind the “Demo site” button, similar to what we're trying to do for the “Preview & Customize” button. pbxlJb-5HI-p2#comment-3724

**Comment by okmttdhr** [comment]
> Can we just make sure that all FSE themes have the Preview and Customize option now? Most of ours do, but Twenty Twenty Four did not in this interaction, nor did Baskerville 2. It would be nice if the option were consistently available. 8317392-zd-a8c

Thanks for reporting. I created the separate issue: https://github.com/Automattic/wp-calypso/issues/92198

**Comment by annezazu** [comment]
Closing this out as nothing actionable remains and https://github.com/Automattic/wp-calypso/issues/92198 has been opened to follow up on ensuring it's available for all themes. Let me know if I got that wrong at all but I want these issues with the full site editor label to be as up to date as possible.
