### ISSUE TITLE
Sharing Buttons: "Official Buttons" style causing buttons to not display or flash

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#60637]
### Quick summary

There seems to be some errors generated when using the "official" sharing buttons, particularly for Facebook. 

The user who I spoke with said that their Facebook sharing button did not display at all on the live site and was absent in the Sharing Buttons settings page.

On my device (in Chrome and Firefox), the Facebook sharing button "flashes" a few times before loading fully on the live site. On the settings page, all social media sharing buttons were invisible or not present.

@ash1eygrace tested this on a test site and saw that Twitter and Facebook sharing buttons were just delayed to load on the live site.

### Steps to reproduce

1. Navigate to Tools > Marketing > Sharing Buttons.
2. Click the "edit" button to add Twitter and Facebook.
3. Select "Official Buttons" style. Save changes.
4. View the button previews on that page, as well as on the live site.

### What you expected to happen

Sharing buttons should load quickly and without flashing on both the settings page and the live site.

### What actually happened

Varying buggy behavior. For the user, the Facebook button did not appear at all on the live site or the settings page.

On @ash1eygrace's test site, both buttons are slow to load (Facebook is notably delayed):
https://user-images.githubusercontent.com/5630717/151620143-19da041a-609c-430d-b406-c5e6aa85d3d9.mp4

When I viewed the user's site, the Facebook button flashes:
https://user-images.githubusercontent.com/5630717/151620282-4c24a81e-077e-43fa-86b5-eed0b009a3b8.mp4

On a simple test site of my own, the Facebook button doesn't load on the live site.

### Context

33912883-hc / 4729786-zen

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Inconsistent observations across sites and browsers (tested simple and AT on Chrome and Firefox).

On the Sharing Buttons settings page, I occasionally saw this console error:
`Access to XMLHttpRequest at 'https://public-api.wordpress.com/rest/v1.1/meta/sharing-buttons' from origin 'https://widgets.wp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

On live sites, I occasionally saw this console error:
`Refused to display 'https://www.facebook.com/' in a frame because it set 'X-Frame-Options' to 'deny'.`

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Choosing any other "style" of sharing button resolves the issues.

**Comment by kerrynicl** [comment]
I'm able to reproduce the delay in loading buttons but not flashing

https://user-images.githubusercontent.com/83325600/155562781-79328b59-ba4e-4810-86de-238016b6dd42.mp4

**Comment by edwinho89** [comment]
I think this bug report is similar as https://github.com/Automattic/wp-calypso/issues/47992

**Comment by CodeAllNightNDay** [comment]
Had the issue come up today here:
6752412-zen
