### ISSUE TITLE
Playwright: Investigate cookie authentication with stale cookies

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#60630]
### Details

I've noticed when running locally that sometimes when using older cookies I had locally on my machine, the tests are getting redirected to login, and then failing because it's not expecting that.

We might be missing some error checking/handling when looking for cookies in our set-up authentication functions.

**Comment by worldomonation** [comment]
Solution: stale definition in Playwright framework is defined as being 3 days, but in actuality the cookies on disk expire in 2 days.

**Comment by worldomonation** [comment]
Since the change to define stale cookie as 2 days, I think we've seen the behavior improve here. Closing for now.
