### ISSUE TITLE
dotcom: Custom Domain Upsell code impacting PHP load times

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#60639]
## Some simple sites load slower than others

On WordPress.com, I noticed one of my simple sites has various URLs loading significantly slower than other sites.
* `/wp-admin`
* `/wp-admin/?service-worker`
* `/wp-admin/post-new.php` (used by https://wordpress.com/post/<SITE>).

For example, `/wp-admin/?service-worker` loads in 8 seconds on one of my simple sites, and in less than 1 second on most of my other sites. It looks to be related to the `$domain_upsell_generator` in D69690-code.

## Code trace

* `wp-admin/admin.php` calls `require ABSPATH . 'wp-admin/menu.php';`
* `wp-admin/menu.php` calls `equire_once ABSPATH . 'wp-admin/includes/menu.php';`
* `wp-admin/includes/menu.php` calls `do_action( 'admin_menu', '' );`
* The slow hook is `72 		add_action( 'admin_menu', array( $this, 'reregister_menu_items' ), 99998 );` in `class-base-admin-menu.php `
* This ends up calling `$nudge = $this->get_upsell_nudge();` in `class-wpcom-admin-menu.php`.
* The slow line in that function is `get_top_messages()` in `jitm-engine.php`.
* This processes 85 different rules, but the `$domain_upsell_generator` inside `jitm-engine.php`, when it decides to render, is slow. The call to `$products      = get_product_price_list( $currency_code, get_current_blog_id() );` takes ~7.5 seconds to fetch 435 products.

## Editor impacted?

Since this also loads in post-new.php, I believe it impacts editor loading times for sites matching the criteria:
>If the user is on a wpcom or atomic site, doesn't have domain credit, and hasn't registered a domain for                              
>the site within the last seven days, prompt them to register another.         

## Timing tests

I did some testing:
BEGIN: timing with https://wordpress.com/post/<site> in the URL bar when pressing ENTER
Network tab in Firefox is open with "Disable cache" checked

END: As soon as I can see the 'Add title' text rendered in the editor

CONTROL:
2021-01-28 code with some debug logging added, public-api+sitesandboxed
22.9  seconds
22.87
23.87
25.56

EXPERIMENT:
With $domain_upsell_generator in lib/jetpack-jitm/jitm-engine.php modified to be
`function() { return 'upsell message;' }`
4 trials:

14.83 seconds
15.08
14.91
14.95    

These aren't necessarily reflective of real users without sandboxes and without debugging code, but it should point to a potential improvement of unknown magnitude in production.

## Possible solutions:

- Remove the upsell
- Change the upsell message generator to fetch less product price data
- Change the upsell message generator to cache calculated price (first load would still be slow, which isn't ideal)
- Reduce the scope of the upsell message generator, for example, stop it from running on `post-new.php` or `/wp-admin/?service-worker`

Chat log of me discovering the issue is in p1643402661193369-slack-C02V49GM0PN

**Comment by obenland** [comment]
@Copons This seems to be a result of D69690-code. Any chance it could find its way into your next sprint?

**Comment by Copons** [comment]
Thanks for pointing this out, I've added it to our next sprint's backlog!

**Comment by mreishus** [comment]
I looked into `/wp-admin/?service-worker` specifically, and it seems to be its own separate issue: It renders menus even though it doesn't need menus. I think that part can be dropped from this issue, and I've written more about it here: p55Cj4-1xc-p2

**Comment by dsas** [comment]
> takes ~7.5 seconds to fetch 435 products.

317 of those are domain products, but we can quite easily stop worrying about the other 118. This goes from ~7.5 seconds to 4-5 seconds. It's an improvement but not sufficient. See D74917-code

**Comment by mreishus** [comment]
Found another source while reviewing D74917: D75009-code

**Comment by dsas** [comment]
I've deployed D74917-code

**Comment by mreishus** [comment]
This looks to be solved with both patches now deployed.
