### ISSUE TITLE
Widgets > Music Player (Legacy): Unable to reorder tracks

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#60648]
### Quick summary

Users cannot drag and drop to reorder songs on their `Music Player` block.

### Steps to reproduce

1. Go to WordPress.com > My Sites > Appearance > Customize > Widgets.
2. Add the `Music Player` block and add some audios there.
3. Drag and drop an audio file and you won't be able to change the order.

### What you expected to happen

I expected to be able to order the audios as mentioned in the playlist gallery: `Drag and drop to reorder tracks.`

### What actually happened

I couldn't reorder the audios.

### Context

User report: 4729897-zen

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

We can reorder the songs by reordering the songs IDs. Here is a screencast:

https://user-images.githubusercontent.com/50875131/151675846-91607353-9b60-4273-9b59-9f15a370945f.mp4

**Comment by MaxPhilip** [comment]
Another case here ZD-4734532

**Comment by druesome** [comment]
Another report 4742076-zen

Moreover, going to Appearance > Widgets and then clicking on "Choose Songs" on the Music Player widget does not bring up the dialog to add or edit tracks.  Nothing happens when you click on it.

Screencast: https://d.pr/i/3qgn5z

**Comment by filipanoscampos** [comment]
Hi! I think this is the same bug:
https://github.com/Automattic/wp-calypso/issues/60469#issuecomment-1028964487

**Comment by edequalsawesome** [comment]
I was able to reorder the music tracks in the Widget panel of the Customizer, so that's been resolved, and I'm going to close this issue.

@druesome There was a different issue for the Choose Song link not working, so I copied your report over to there: https://github.com/Automattic/wp-calypso/issues/57226
