### ISSUE TITLE
[Bug]: Pause button visible on playing videos on mobile devices

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#60650]
### Quick summary

On mobile devices, the pause button is shown at the center of playing videos. The pause button is supposed to disappear when the video is playing and reappear when the screen is touched. This happens regardless of the theme.

![Screenshot_20220130-152333](https://user-images.githubusercontent.com/4719037/151697749-65e66704-f4b5-43c7-9b42-86d563ed34f7.jpg)

### Steps to reproduce

1. Upload a video using the video block to a page or post
2. Publish the post/page and view it on mobile
3. Notice the pause button is present throughout the playing mode of the video

### What you expected to happen

The pause button is supposed to disappear when the video is playing and reappear when the screen is touched.

### What actually happened

The pause button doesn't disappear when the video is playing. It's visible at the center of the video.

### Context

Reported here 33563729-hc

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by philnick206** [comment]
Reported in #4736178-zen for Chrome on Android

I cannot repro this on iOS with Firefox or Chrome.

**Comment by jgcaruso** [comment]
Currently investigating this in 545-gh-Automattic/videopress

Should have a fix for this today.

**Comment by cometgrrl** [comment]
See linked issue 545-gh-Automattic/videopress for fix.
