### ISSUE TITLE
Include more currencies in the revenue dropdown

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60655]
- [ ] Expand the number of currencies supported by the revenue dropdown 

https://github.com/Automattic/wp-calypso/blob/10ce7ed85b9c2e679f40274757b88d8814822904/client/signup/steps/woocommerce-install/step-business-info/revenue-options.js#L6-L20

Context https://github.com/Automattic/wp-calypso/pull/60066#pullrequestreview-859985725

**Comment by allilevine** [comment]
Needs upstream WooCommerce fix.

**Comment by lsl** [comment]
Closing for now. Not a priority.
