### ISSUE TITLE
Marketplace: Sync WP.com purchases with WC.com

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#60661]
> Normally, when merchants purchase an extension on WooCommerce.com Marketplace, the purchased extensions will show as well here: WP Admin > WooCommerce > Extensions > My Subscriptions.

Related convo: pdtkmj-2M-p2#comment-91
Suggested solution: pdtkmj-2M-p2#comment-97

- [x] Record the transaction order at WooCommerce.com, with an additional meta field that the order originates from WordPress.com. If you’re using the host plans API, this is already included.
- [ ] Add a small helper plugin alongside WooCommerce to adjust the display of this button inside the “WooCommerce > Extensions > My Subscriptions” screen, replacing it with “Included with your plan”, or other such wording.
- [ ] At WooCommerce.com, a user would still be able to download the code they have purchased. Add an adjustment to WooCommerce.com to do the same button replacement as above.
- [x] When a subscription is cancelled, cancel the corresponding transaction order at WooCommerce.com.
- [x] When a site URL changes, update the corresponding transaction order at WooCommerce.com.

Host plan API for provisioning licenses WC.com/tree/trunk/plugins/wccom-plugins/host-plan

**Comment by lsl** [comment]
Do we need this sync? I was thinking we could disable the Woo extension page on wpcom unless they already have a wccom extension installed.

Main reason is to reduce confusion with the wpcom marketplace because the extension page funnels users to woocommerce.com which is not what we want. 

It also needs to be disabled for woo's usage on limited atomic as those users can't install plugins via the purchase > download flow wccom makes use of.

We could also update the page to filter out marketplace plugins from view based on the marketplace category being discussed here: 12392-gh-Automattic/woocommerce.com#issuecomment-1046822236.

**Comment by cpapazoglou** [comment]
> Do we need this sync? I was thinking we could disable the Woo extension page on wpcom unless they already have a wccom extension installed.

yeah, we can explore that. In the long term, there is no point having two Marketplaces. The problem is that now, we don't offer all plugins that are currently offered through wccom marketplace.

**Comment by lsl** [comment]
> The problem is that now, we don't offer all plugins that are currently offered through wccom marketplace.

We can keep the page visible for now but I'm still not sure why we want wpcom purchases/subscriptions showing up on the extensions page. Do we need this?

**Comment by cpapazoglou** [comment]
If there is a way to make a distinction between wpcom and wccom purchases, we could hide the wpcom purchases. But, I imagine a user trying to follow docs, or getting help from support and not being able to find what they need. Hiding purchases will make things more obscure while following the **default** way to provision woo licenses (which tried to avoid initially) will simplify things for end users and HEs.

**Comment by lsl** [comment]
> If there is a way to make a distinction between wpcom and wccom purchases, we could hide the wpcom purchases.

Not syncing them should have that effect.

I'm still not clear on why we need this purchase sync, isn't it going to confuse (or double count) woocommerce.com reporting data? 

Re documentation I understand there might be some confusion in existing documentation but that seems more easily fixed by updating the documentation.

**Comment by cpapazoglou** [comment]
The scope of this issue is resolving the first task and opening the rest of the tasks as issues.

**Comment by JulianBustamante** [comment]
Diff created D81754-code

**Comment by JulianBustamante** [comment]
I created a diff which is successfully creating the order on WC.com but I'm still working on saving the data returned by the Host API for each order so that each subscription can be cancelled individually.

**Comment by JulianBustamante** [comment]
Deployed r249709-wpcom

**Comment by cpapazoglou** [comment]
Children issues to resolve this issue:
- https://github.com/Automattic/wp-calypso/issues/65683
- https://github.com/Automattic/wp-calypso/issues/65563
- https://github.com/Automattic/wp-calypso/issues/65898
- https://github.com/Automattic/wp-calypso/issues/65682

**Comment by solstudioim** [comment]
I am assuming this is not implemented yet @cpapazoglou 

Got another confused WPCOM Business Plan user, who saw their monthly extension invalid notice: ![A3rQDr.png](https://user-images.githubusercontent.com/17371139/192129074-63e22af2-707e-4c96-915b-dd4ad37f8b2f.png)

Ticket 5582567-zd-woothemes

Personally, I was able to replicate on my test AT Site with the Business Plan.

**Comment by cpapazoglou** [comment]
Paging here @JulianBustamante who worked on this. 

I am not sure if this is still behind a feature flag which we should remove or if it's related to an older purchase that we haven't synced yet.

**Comment by JulianBustamante** [comment]
@solstudioim This feature has not been released yet and is behind a preview flag since there is a remaining task - [Marketplace: Create a script to sync existing woo subscriptions to wc.com](https://github.com/Automattic/wp-calypso/issues/65563)
