### ISSUE TITLE
Seller Experience: Move user into the editor with the block inserter open.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60675]
Once the user selects a theme, let's drop them into the editor with a new page, and the block inserter open, pointing to payments blocks.

<img width="963" alt="Screen Shot 2022-01-31 at 8 39 58 AM" src="https://user-images.githubusercontent.com/349751/151835102-8a19e0f8-3039-4240-8259-b8468b9c5402.png">

**Comment by kwight** [comment]
Another option for this is to open the page with a Payments block already inserted (we're not teaching the user to fish, but it's another step reduced). @SaxonF @ianstewart any preference here?

**Comment by SaxonF** [comment]
Related discussion here https://wp.me/paYKcK-1dX#comment-1124

I think block insertion requires more education but I do agree in the long run guiding people towards doing it themselves is the better option (e.g. via tour kit). For now though, I do think starting with payment block already inserted is the better experience to start with.

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/60717
