### ISSUE TITLE
[Bug]: "Display" and "Activity" buttons not visible in full after completing WooCommerce installation flow

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#60676]
### Quick summary

After completing installation of WooCommerce from the "WooCommerce" menu on the left, the "Display" and "Activity" options at the top right of the WooCommerce Home page are not visible entirely. The installation flow may not be relevant/necessary here, but I wanted to make a note.

### Steps to reproduce

- Start with a WordPress.com site on the WordPress.com Business plan or higher
- Install WooCommerce from the WooCommerce menu on the left.
- Complete installation/process of going Atomic.
- See "Display" and "Activity" tabs at the top right on WooCommerce Home page, or on WooCommerce stats page.

### What you expected to happen

The buttons are visible.

### What actually happened

The buttons are not visible in full.

<img width="1440" alt="Screenshot 2022-01-31 at 10 25 55 PM" src="https://user-images.githubusercontent.com/18581859/151838767-0b1b3b36-7b5a-4036-92f7-667575747f12.png">
<img width="1166" alt="Screenshot 2022-01-31 at 10 26 24 PM" src="https://user-images.githubusercontent.com/18581859/151838789-0764c21a-f15f-4a00-9a38-95f919ff771f.png">
<img width="1170" alt="Screenshot 2022-01-31 at 10 26 12 PM" src="https://user-images.githubusercontent.com/18581859/151838793-6b337c28-ea21-4e59-af5c-854a5f1e7834.png">
<img width="385" alt="Screenshot 2022-01-31 at 10 26 04 PM" src="https://user-images.githubusercontent.com/18581859/151838800-b506f01e-8849-4c30-ad9e-f9268f583f13.png">

### Context

Manual testing

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – not applicable.
Tested on Atomic – not reproducible.
Replicable outside of Dotcom – not applicable.

📌 FINDINGS/SCREENSHOTS/VIDEO
**AT**
<img width="556" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/7bde0b34-a62d-4616-875a-6071316835da">

Note on the top right the Preview/Display/Help buttons are visible fully. This is regardless of the viewport width.


https://github.com/Automattic/wp-calypso/assets/6549265/b99d4f17-0153-4dfb-84fd-5cd34d73b791



📌 ACTIONS
- close as Not Reproducible.
