### ISSUE TITLE
Back button on "Contact support" view of the "WooCommerce on plans" installation flow doesn't lead back to the expected page

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#60678]
### Quick summary

On the "WooCommerce on plans" installation flow, click on "Contact support" and then click on "Back". It's expected that the back action leads back to the last view/page, but it shows the final confirmation screen to go Atomic.

### Steps to reproduce

- Start with a WordPress.com Business plan site or higher.
- Click on WooCommerce menu on the left.
- When the "WooCommerce on plans" installation flow appears, click on "contact support" 
- Click on "Back"

### What you expected to happen

Taken back to the last step of the installation flow.

### What actually happened

Taken to the confirmation screen of the installation flow. Here's a video of what happens:

https://user-images.githubusercontent.com/18581859/151840138-f2092e92-fc78-4888-b9f3-7b167f50dec7.mov

### Context

Manual testing. cc @allilevine 

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by allilevine** [comment]
Thanks for catching this @arunsathiya! It looks like the link is hard-coded here:
https://github.com/Automattic/wp-calypso/blob/21f7f7b865bb2aa5a210289115c6ce0f04f71c6d/client/signup/steps/woocommerce-install/components/support-card/index.tsx#L33

**Comment by allilevine** [comment]
Maybe we could change this to have query params like the link to checkout:

https://github.com/Automattic/wp-calypso/blob/d52b28102f86507d5a025c962e2041763122ab89/client/signup/steps/woocommerce-install/hooks/use-woop-handling/index.ts#L181

**Comment by arunsathiya** [comment]
@allilevine I am not too sure I understand this idea, but I'll give a fresh look tomorrow morning. For now, I have a `window.location.pathname`-based approach that works: https://github.com/Automattic/wp-calypso/pull/60682 

If the other idea is preferred, or if you have anything else to share, let me know! Feedback welcome!

**Comment by allilevine** [comment]
> @allilevine I am not too sure I understand this idea, but I'll give a fresh look tomorrow morning. For now, I have a `window.location.pathname`-based approach that works: #60682
> 
> If the other idea is preferred, or if you have anything else to share, let me know! Feedback welcome!

@arunsathiya That was my mistake, I missed that we were already adding query params to this link. 🤦‍♀️ Your PR looks great and I've approved it.
