### ISSUE TITLE
[Bug]: wrong parameters name

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#60677]
### Quick summary

In a JSX svg a `fill-rule` property must be written as `fillRule`. See https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/login/two-factor-authentication/push-notification-illustration.jsx#L39-L58

### Steps to reproduce

1. Visit /log-in/push
2. Check the JS console

### What you expected to happen

1. The JS console to not print an error

### What actually happened

1. The JS console print an error

### Reproducibility

Consistent

**Comment by mpkelly** [comment]
I've run the "Unknown attribute" inspection in WebStorm for the whole project. It finds a bunch of issues so we can maybe address some of those too. There are some that look like false positives but there are others like this one where the case is wrong for SVG attributes that are used in JSX components. 

![image](https://user-images.githubusercontent.com/6851384/175554410-3abe22d3-74f9-4250-9ba4-d7246cf989e7.png)
