### ISSUE TITLE
Larger Alt text box in Media Library

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#60685]
### What

A client says the one-line "Alt text" box, when editing an image from the Media Library, makes it difficult to edit and suggests a larger box, the same size of the "Description" text box.

![imagen](https://user-images.githubusercontent.com/4965723/151864556-12fce262-1c5c-4f0e-a053-198375892233.png)

### Why

This could make it easier for the users to edit alt text.

### How

Changing the site of the Alt box to a three lines box (like the Description box) that is shown when we open an image for edit in the media library.

**Comment by ariel-maidana** [comment]
33952206-hc

**Comment by Greatdane** [comment]
It [looks like](https://www.w3.org/WAI/GL/WCAG20/tests/test3.html) the recommended max ALT text length is about 100 characters. Just like the title, it is supposed to be short, and not too descriptive. 

Closing this one for now.
