### ISSUE TITLE
Yoast wpseo_installation_successful page has no right padding

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#60699]
It looks like `/wp-admin/admin.php?page=wpseo_installation_successful` page in  Yoast Premium doesn't display well in some breakpoints:

![SS 2022-02-01 at 11 01 33](https://user-images.githubusercontent.com/12430020/151939791-8a77672e-2342-4d8b-9675-5ed1843d952b.png)

related convo: p1643666403243409-slack-C029JEQRVRT

**Comment by cpapazoglou** [comment]
Asked Yoast for resolution here pcSRhZ-3B-p2

**Comment by BobRademaker** [comment]
Forwarded this to our plugin team to see if we can fix this in a future release.

**Comment by cpapazoglou** [comment]
Closing this as Yoast will be shipping fix in their next release pcSRhZ-3B-p2#comment-119
