### ISSUE TITLE
Page Layout options - not visible on smaller screens

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/wp-calypso#60695]
### Quick summary

It’s not possible to see all page layout options on some screen resolutions.

### Steps to reproduce

1). Go to My Site(s) → Pages.
2). Click on Add new page.

### What you expected to happen

I expect to see all Page Layout options as seen here: [https://wordpress.com/support/page-layouts/#viewing-page-layouts](https://wordpress.com/support/page-layouts/#viewing-page-layouts)

### What actually happened

I can only see 8 options and can’t scroll down to see more.

![c-1](https://user-images.githubusercontent.com/7424885/151907627-90bb032f-c678-4974-beb4-10b79f28a326.png)

### Context

Originally reported here: pd4QKa-sG-p2

### Browser, operating system and other notes

Firefox 96 / Windows 7 / Screen resolution 1366 x 768

### Workaround details

Click CTRL - to zoom out of your browser, will show all page layout options.

![d-2](https://user-images.githubusercontent.com/7424885/151907874-3f895bea-43cf-4e42-ac70-939d74f6e765.png)

**Comment by roo2** [comment]
hmm interesting, ok, I can see that if someone was using a phone on landscape mode or just had created a browser window to unusual dimensions this becomes an issue.

I think we could solve this by making the left panel scroll-able (only when neccessary, so we don't have a scroll bar all of the time) It might be a tricky bit of CSS.

Let's save this for our new ganon dev's starting in the next few weeks.

**Comment by arthur791004** [comment]
@roo2 Do we still need to save this for our new dev?

**Comment by roo2** [comment]
nope, I think it's fair game now for anyone who can fix it!

**Comment by miksansegundo** [comment]
@roo2 How can test the modal `Add a page` in my localhost Calypso?  I tried it but I'm being redirected to wordpress.com. Maybe it has to be tested on the sandbox?

**Comment by arthur791004** [comment]
@miksansegundo You have to

* Sandbox your API and ensure your siteSlug domain point to your sandbox
* Go to `apps/editing-toolkit`
* Run `yarn dev --sync` to sync the change of the ETK plugin to your sandbox
