### ISSUE TITLE
Seller Experience: Go from the "simple vs. more" screen to the site editor.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60717]
We will be dropping the theme selection step from the MVP, so we need to take a user that selects the "simple" path and drop them into the site editor (note that's the _site_ editor, not a page editor, now that FSE is active). There will be separate issues for wiring up a Payments block pattern in that editor.

We'll need to automatically assign a theme at this step; let's assign Zoologist for now (@alaczek may choose a different theme at some point).

See: paYKcK-1fc-p2

**Comment by sixhours** [comment]
Closed by #60772
