### ISSUE TITLE
Marketplace: Yoast Onboarding not filled after subscription is added manually

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60718]
### What

On a test site I added a Yoast Premium subscription to transfer a sub-business plan site to Atomic. After navigating to the Yoast dashboard I noticed a banner informing about the need to configure Yoast SEO.

<img width="806" alt="Screen Shot 2022-02-01 at 9 46 12 AM" src="https://user-images.githubusercontent.com/1398304/152030200-d2a77a24-75db-4366-86b3-5caf35798490.png">

**I don't know if we link to it when customers will purchase the product from the marketplace, if we don't maybe we could consider it?**

It's understandable that they'll have to set it up manually when the subscription was added manually.

### Why

It feels like something that should be a smooth experience, timed with when they first decide to use the feature.

**Comment by cpapazoglou** [comment]
We haven't create any special flows for Yoast Premium. We were relying on the `action_links.Settings` plugins that `https://public-api.wordpress.com/rest/v1.1/sites/:site/plugins` return for a given site.

It seems though that neither Yoast nor Yoast Premium include such a link in their response

```
active: false
author: "Team Yoast"
author_url: "https://yoa.st/2jc"
autoupdate: false
description: "The first true all-in-one SEO solution for WordPress, including on-page content analysis, XML sitemaps and much more."
id: "wordpress-seo-premium/wp-seo-premium"
name: "Yoast SEO Premium"
network: false
plugin_url: "https://yoa.st/2jc"
slug: "wordpress-seo-premium"
version: "18.0"
```

**We can add `setup_url` in our `https://public-api.wordpress.com/wpcom/v2/marketplace/products` endpoint that will act as fallback if `action_links.Settings` is not present in the `https://public-api.wordpress.com/rest/v1.1/sites/:site/plugins` response.**

For Yoast we could use `/wp-admin/admin.php?page=wpseo_workouts` as a `setup_url`

**Comment by gcsecsey** [comment]
Diff created: D75013-code

**Comment by cpapazoglou** [comment]
@gcsecsey can you also create the calypso code changes so that we can resolve this issue?

**Comment by gcsecsey** [comment]
Yep, I've opened this PR with the Calypso changes: https://github.com/Automattic/wp-calypso/pull/61127

**Comment by gcsecsey** [comment]
Deployed changeset r240191-wpcom
