### ISSUE TITLE
Seller Experience: The simple path is not free.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60710]
We currently show the simple path (which uses Payments blocks) as being free, but to use a Payment block or any sort, you need to be on a paid plan. Let's duplicate the markup for the Woo path, but change it to "paid" (linking to the same place, the `/plans/` page.

<img width="616" alt="Screen Shot 2022-02-01 at 7 49 24 AM" src="https://user-images.githubusercontent.com/349751/152002257-571276a5-a1d9-412d-b7a3-0153c153ef6e.png">

**Comment by nelsonec87** [comment]
I think we should link to `/plans/<site-slug>` instead of `/plans/` in both cases, otherwise the user is sent to "Select a site to open Plans" page.

**Comment by kwight** [comment]
> I think we should link to /plans/<site-slug> instead of /plans/ in both cases

Yes! I wasn't sure if we have it at this point, but yes, we do.

@nelsonec87 another thing to add to this, which should probably just be the same PR: it's possible that a user arrives at this point already having a paid plan, in which case we should change the text for both choices to "Included in your plan".

**Comment by kwight** [comment]
> in which case we should change the text for both choices to "Included in your plan"

@nelsonec87 Oh, this isn't quite correct; the simple flow is included in any paid plan, the Woo flow is included in any Business or Ecommerce plan.
