### ISSUE TITLE
Marketplace: Yoast Premium warns of "Huge SEO issue" on sites with coming soon mode

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60714]
### Quick summary

On a test site I added a Yoast Premium subscription to transfer a sub-business plan site to Atomic. After navigating to the Yoast dashboard I noticed a banner informing about a huge SEO issue because robots are blocked.

<img width="804" alt="Screen Shot 2022-02-01 at 9 46 26 AM" src="https://user-images.githubusercontent.com/1398304/152022708-cdad1bad-41a5-4ed4-9a28-731f67bec5cf.png">

That banner should probably not be there or be reworded to account for a site's coming soon status and link to the correct place to launch a site.

### Steps to reproduce

1. Create a test site.
2. Navigate to your user's store admin
3. Add a Toast Premium subscription to the test site
4. Navigate to Toast Dashboard at wp-admin/admin.php?page=wpseo_dashboard#top#dashboard
5. Notice the notification banner

### What you expected to happen

For that banner to be more context specific

### What actually happened

It wasn't.

### Reproducibility

Once

**Comment by chickee0311** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Removing the redirects for premium theme pages #60716](https://trello.com/c/MNSn8U4x/70-removing-the-redirects-for-premium-theme-pages-60716)

**Comment by cpapazoglou** [comment]
> For that banner to be more context specific"

@obenland can you elaborate on that?

**Comment by obenland** [comment]
More specific to the context of the site being in coming soon mode.

> That banner should probably not be there or be reworded to account for a site's coming soon status and link to the correct place to launch a site.

**Comment by gcsecsey** [comment]
We've discussed on the Backlog Grooming session, that looking at the Yoast source code, it checks the `ignore_search_engines_discouraged_notice` WP option. We could enable this option when a site is set to Coming Soon mode, to make the notice disappear.

**Comment by gcsecsey** [comment]
I've looked into this a bit further, and the `ignore_search_engines_discouraged_notice` option seems to only control whether the user has dismissed the notice before:
wordpress-seo-premium/admin/class-admin-init.php#L433

The check for search engine visibility is done via the `blog_public` option, if this option is set to `0`, that means that the site is public, but indexing is discouraged. This state is also a prerequisite for the Coming Soon mode itself: PCYsg-u4S-p2

> That banner should probably not be there or be reworded to account for a site's coming soon status and link to the correct place to launch a site.

Yoast is technically correct to show this notice in this state. Coming Soon mode is WPCOM specific, and we can't require the plugin to cater to this case, but if the Yoast notice is hidden, we can add a different notice in its place. This would have the same overall effect as rewording the banner, and it could also link to the correct place to launch the site.

We can detect coming soon mode on our side and based on that:
- hide the Yoast notice
- show a new custom notice that's specific to Coming Soon mode

**Comment by cpapazoglou** [comment]
Sounds like a plan @gcsecsey, we should just add to that condition that `wordpress-seo-premium` plugin is active.

**Comment by gcsecsey** [comment]
I've raised a draft PR with the proposed changes: 846-gh-Automattic/wpcomsh I'll update the formatting and add testing steps.

As discussed, I've added a new notice, which we can word specifically to the Coming Soon mode:
846-gh-Automattic/wpcomsh/files#diff-72a90974334352a3550e414b468439db0dff4263126064095ff8dcfcc57ff357R88
@cpapazoglou @obenland, could you please help with what the correct wording should be?

**Comment by cpapazoglou** [comment]
I like the `Heads up! Your site is currently in Coming Soon mode. %1$sClick here%2$s to change your site\'s privacy settings` you have already used.

Perhaps we can update it to `Heads up! Your site is currently in Coming Soon mode. If you want search engines to show this site in their search results you have to launch your site. %1$sClick here%2$s to change your site\'s privacy settings.`

**Comment by gcsecsey** [comment]
I've created the wpcomsh release. The changes will be deployed when monitoring picks up the new release.
