### ISSUE TITLE
Marketplace: Yoast Premium needs to reprocess SEO data after activation

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60713]
### Quick summary

On a test site I added a Toast Premium subscription to transfer a sub-business plan site to Atomic. After navigating to the Coast dashboard I noticed a banner informing about the need to reprocess SEO data because permalink changed.

WP.com doesn't allow changing permalinks, so I wonder if that SEO data processing can be automated after transfer?

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/1398304/152021893-2af7a955-d79a-46e2-9814-ee6df440c23e.png">

### Steps to reproduce

1. Create a test site.
2. Navigate to your user's store admin
3. Add a Toast Premium subscription to the test site
4. Navigate to Toast Dashboard at `wp-admin/admin.php?page=wpseo_dashboard#top#dashboard`
5. Notice the notification banner 

### What you expected to happen

Not to see a banner to reprocess SEO data

### What actually happened

See a banner to reprocess SEO data

### Reproducibility

Once

**Comment by cpapazoglou** [comment]
> WP.com doesn't allow changing permalinks, so I wonder if that SEO data processing can be automated after transfer?

@obenland, by going to `/wp-admin/options-permalink.php` I could change permalinks, isn't that expected?

**Comment by obenland** [comment]
Indeed, that's right! However at the moment that notice is shown the customer hasn't touched permalinks yet.

**Comment by gcsecsey** [comment]
We've discussed on the Backlog Grooming session, that probably the notice is shown because of the domain change, when transferring the site to atomic. We could follow up with Yoast whether in this case, it's correct to show this notice, and if so, whether we can automate running this process.

**Comment by cpapazoglou** [comment]
Let's timebox this to find out what exactly is going on and whether we can suggest a solution to Yoast.

**Comment by obenland** [comment]
Do these not show up anymore?
