### ISSUE TITLE
Editor: Settings sidebar broken when a Slideshow block is added to Layout Grid

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#60724]
### Quick summary

Adding a Slideshow block inside a Layout Grid column causes the Editor to break. The editor's sidebar settings panel disappears and the page becomes too wide to handle!
A video on how to replicate and the issue-

https://user-images.githubusercontent.com/40609190/152040045-72a917a3-b05f-4d36-9461-9f2bd96ebd5b.mp4

If you check with browser inspect you'll see that the Slideshow block becomes just too wide-
![image (2)](https://user-images.githubusercontent.com/40609190/152040094-26e151c0-de04-4c35-9d30-fe0beb95b5b2.png)

This happens on both simple and AT sites.

On AT sites, disabling the Layout Grid plugin helps bring the editor settings sidebar back.

### Steps to reproduce

1. Create a page/post, add a Layout Grid and add a Column.
2. Add a Jetpack Slideshow block inside the column and add a few images.
3. Voila, the editor breaks.

### What you expected to happen

I expected the editor to not break and the Editor settings sidebar to be visible.

### What actually happened

The sidebar disappears immediately and the editor page becomes too wide to handle.

### Context

We got two reports of the editor sidebar settings disappearing from two users. zen-4724756 and zen-4738719
On the AT site, we first did a plugin conflict test and disabling the layout grid block helped.
Then we checked other pages and found only particular pages were facing the issue.
Thom and Nic narrowed it down to the Slideshow block inside the Layout editor being the cause.

I tested it on a couple of my test sites (both simple and AT) and could replicate it consistently. 

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Nope.

### Browser, operating system and other notes

Tested in Chrome.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Disabling the Layout Grid block helps.
Or, moving the Slideshow out of the Layout Grid helps. 
Using Column blocks with Slideshow works fine.

**Comment by ahmadbaig1** [comment]
I just found out that this has been already reported here- https://github.com/Automattic/wp-calypso/issues/39956
Can someone please merge the two issues?

**Comment by stefancln** [comment]
Found another case 4743111-HC

**Comment by Abdul-Elsayed** [comment]
This issue was reported here:  4775902-HC

**Comment by mxhassani** [comment]
Similar issue: 34248460-hc

**Comment by tanjoymor** [comment]
Another case here 4792060-zen
I've also run into this issue on my own sites.

**Comment by Greatdane** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/39956
