### ISSUE TITLE
Limited Atomic: videopress_post_transfer_set_blog_upload_space() should look for videopress capability

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#60727]
In `woa-post-transfer.php`, `videopress_post_transfer_set_blog_upload_space()` checks `woa_has_atomic_subscription( $blog_id )` and if it passes, it updates the site's blog_upload_space to 2TB to allow for unlimited videopress uploads.

This function is operating off the logic: "If we have an atomic subscription, which is a Business, Ecommerce plan, or Marketplace addons product, then allow for unlimited videopress uploads".  Instead, it should be checking to see if their plan has the actual videopress product.

**Comment by obenland** [comment]
There's also `videopress_post_transfer_set_meta()` that should be looked at

**Comment by obenland** [comment]
Patch in D81591-code

**Comment by obenland** [comment]
Fixed in D81591-code
