### ISSUE TITLE
FSE: show block-based themes in the showcase for all users

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#60723]
### Details

As the next step of the rollout, we need to show block-based themes to all users. If they activate such a theme, they should get the FSE experience. The same goes for activating universal themes, the only difference being that they were already visible in the showcase.

Potential ways to approach this:

- Stop hiding FSE themes for non-enrolled sites.
- Make sure that sites get stickered during the theme switch.
- In the case of a universal theme, make sure that the FSE activation option is set to true during activation.

Or remove the FSE sticker check altogether making all of the sites eligible:

- This will require some modification in existing screens in Calypso that relied on the sticker to show up.
- We would still need to handle the FSE activation option for universal themes.

**Comment by Addison-Stavlo** [comment]
To clarify, is the goal for all universal themes to run in FSE mode? So the main differences between universal and standard block-based themes is the extra goo we enable for universal such as the customizer? And would it be ok to turn on FSE for everyone currently running a universal theme in classic mode?

If that all is the case, I think either approach allows us to get rid of the site option for FSE activation as well.  So we could get rid of the site options, stickers, and show all themes to all users - every theme that can support FSE would then just run it without any need to consider site options or stickers.

Do we need to add any stickers to new sites opting into FSE in any of these ways for traceability reasons? Or are we beyond that at this point?

**Comment by vindl** [comment]
> To clarify, is the goal for all universal themes to run in FSE mode?

Yes, but... 

> And would it be ok to turn on FSE for everyone currently running a universal theme in classic mode?

I was thinking only for sites that make a theme switch to a universal theme. We'll enable it to everyone at some point after that, but we need to run some email/marketing announcements prior to switching them. 

> Do we need to add any stickers to new sites opting into FSE in any of these ways for traceability reasons? Or are we beyond that at this point?

We could add a `calypso_fse_enrolled` event for them to track them, but I don't think we'll need a separate sticker anymore?

**Comment by vindl** [comment]
> I was thinking only for sites that make a theme switch to a universal theme.

After thinking about this some more, this might complicate things technically. If that turns out to be the case we can postpone this step for when we deal with the rest of the existing Universal theme sites.

**Comment by Addison-Stavlo** [comment]
D74449-code should enable this.

**Comment by creativecoder** [comment]
More discussion on how we could roll this out: paYE8P-1rh-p2

**Comment by creativecoder** [comment]
Should we close this now that D74449-code has landed?

**Comment by Addison-Stavlo** [comment]
> Should we close this now that D74449-code has landed?

I considered it still open since the universal themes part of it is still unresolved.  Although its up to how we want to track it, we can always create another issue for that.

 https://github.com/Automattic/wp-calypso/pull/61040 and D74666-code should hopefully resolve the universal themes case, and after that it just comes down to some code cleanup I think. 🤞

**Comment by Addison-Stavlo** [comment]
Probably safe to close this now. 😁
