### ISSUE TITLE
FSE: Customize menu option not available on atomic sites.

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#60732]
EDIT - As it seems some functionalities have been updated since original ticket creation. At this point a main issue is that `customize` button does not show up consistently for Atomic sites when running any FSE themes, even if they are running plugins or themes that add customizer settings. 

Customize should always be available when any theme or plugin is active that adds features to the customizer.

-----------------
Prior art:
-----------------

### Quick summary 
The customize button only appears and works intermittently when working with a Universal theme, depending on the context. As long as Customize is required, it should show up and work consistently. 

### Steps to reproduce
1. Activate a Universal theme like Blockbase on a Simple, Atomic, and Jetpack-connected .org site
2. Go to https://wordpress.com/themes/ and select the site
3. View /wp-admin/themes.php for the same site

### What you expected to happen
As long as Customize is required to manage some aspect of a theme (like the site footer credit), it should show up and work consistently. 

### What actually happened
**The Theme page is inconsistent between Calypso (Default View) and /wp-admin (Classic View)**
🙃 Simple shows an Edit button at /themes/ and a Customize button in /wp-admin/themes.php
🙃 Atomic shows an Edit button at /themes/ and a Customize button in /wp-admin/themes.php
✅ .org shows a Customize button at /themes/ and a Customize button in /wp-admin/themes.php

**The Customize button sometimes goes to the Site Editor
✅ On Simple, the Edit button goes to the Site Editor, and the Customize links go to Customize
🙃 On Atomic, Edit and Customize both go to the Site Editor
🙃 On .org's /themes/ and wp-admin/themes.php pages, Customize goes to the Site Editor

Noting the Customize menu icon works consistently wherever it exists.

**The menus are inconsistent between Simple and Atomic**
🙃 Simple shows Customize in the menu, whether I'm using Classic View or Default View
🙃 Atomic does not show Customize in the menu, whether I'm using Classic View or Default View
✅ .org shows a Customize option in Calypsos menu, as well as in the menu for /wp-admin

You can see a video here, but I didn't realize yet that the Customize links were broken on .org and Atomic

https://user-images.githubusercontent.com/3476361/172525707-2bdc33ea-7a79-4c7c-9068-9e1813322d6f.mov

### Context
notes from @AtrumGeost  Friend report; was able to reproduce on my end.

### Simple, Atomic or both?
It's inconsistent on both, but works fine on .org

### Theme-specific issue?
This seems specific to Blockbase themes, because they use FSE as well as Customize.

### Browser, operating system and other notes
n/a

### Reproducibility
Consistent

### Severity
Some (< 50%)

### Available workarounds?
Anyone can visit /wp-admin/customize.php directly

### Workaround details
Add /wp-admin/customize.php to the end of the site URL to find the Customizer

**Comment by formosattic** [comment]
This looks fixed. Tested with themes Payton, Zoologist, and `Customize` shows for me. 

Reopen if the issue still happens.

![image1](https://user-images.githubusercontent.com/15944096/156130521-0f95b8ef-b12f-4d63-962b-f2e60d4167c2.png)

**Comment by masperber** [comment]
Reopening this. On several themes, such as Kerr, the Customize button does not appear.

The Customize button needs to appear because some options are still only accessible there, including the option to change the Footer Credit under Site Identity.

35671426-hc as an example of where this was a problem.

As a workaround, customers can to to Appearance > Additional CSS, then go back one level to get to Site Identity, but this is confusing and requires an extra click.

**Comment by inaikem** [comment]
@jordesign, quick confidence check 🙏

Do you think the above will be resolved by this: pNEWy-f1z-p2#comment-54652 ? I've not looked into it in too much detail yet.

**Comment by jordesign** [comment]
I wouldn't expect that to impact it directly - no.
That change would mean there are *less* reasons to need the customizer - but for the other reasons mentioned in this thread - users may still need to access it.

**Comment by supernovia** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core: No

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
On WordPress.com, we have a Calypso view and a wp-admin classic view, as well as menus. 

**The Theme page is inconsistent between Calypso (Default View) and /wp-admin (Classic View)**
🙃 Simple shows an Edit button at /themes/ and a Customize button in /wp-admin/themes.php
🙃 Atomic shows an Edit button at /themes/ and a Customize button in /wp-admin/themes.php

**The menus are inconsistent between Simple and Atomic**
🙃 Simple shows Customize in the menu, whether I'm using Classic View or Default View
🙃 Atomic _does not_ show Customize in the menu, whether I'm using Classic View or Default View

**Customize shows in the menu on .org, and on the themes page, whether in Calypso /themes/ or /wp-admin**
✅ .org shows a **Customize** button at /themes/ and a **Customize** button in /wp-admin/themes.php
✅  .org shows a Customize option in Calypsos menu, as well as in the menu for /wp-admin

Here's a video if it helps:

https://user-images.githubusercontent.com/3476361/172525707-2bdc33ea-7a79-4c7c-9068-9e1813322d6f.mov

📌 ACTIONS
- Editing the original issue to clarify we do want Customize for Universal themes and it should be consistent
- Marked as Triaged for Quality Squad review
- Added to 'HE User Waiting (Need bulk replies)' project board
- Feature request kept/closed

📌 Message to Author - n/a

**Comment by supernovia** [comment]
^^ Sorry my drag-and-drop was being fussy.

Also, this is probably related. cc @Robertght  again 😅 
https://github.com/Automattic/wp-calypso/issues/62755

**Comment by masperber** [comment]
35750982-hc Twenty Twenty Two theme. Another instance where there is no link to the Customizer, but the customer needed to use the Customizer to change a setting. In this case, the setting was the WooCommerce Store Notice.

**Comment by arunsathiya** [comment]
- [ ] Another case of Customize missing on the sidebar on Payton: 5307053-zen

It was needed because Colors option on the Customizer shows some settings that are available only there. The option we see there does not match what we have on Global Styles on FSE/Site Editor. So, the only way to update the primary/secondary colors is to visit the Customizer: https://wordpress.com/customize or via https://domain.com/wp-admin/customize.php 

Here's what we have via Customizer: 

<img width="633" alt="image" src="https://user-images.githubusercontent.com/18581859/174439829-019a3794-2d77-4e05-88cb-7d8c96299c00.png">

Does not match what we have on the FSE/Site Editor:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/18581859/174439839-35e44ec1-d9c3-4218-a6bc-db56bb8ed24e.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/18581859/174439842-4f67f716-38e2-4e6d-8445-8fc463f5b6ad.png">

<img width="382" alt="image" src="https://user-images.githubusercontent.com/18581859/174439847-232f33cc-ebf8-416f-ab02-1911f0627989.png">

**Comment by Addison-Stavlo** [comment]
Looking into the current state of things, it seems like the 'Customize' button not appearing when it should is only happening on atmoic sites. It also seems like when it isn't present, this absence is consistent across wp-admin and calypso. Is this correct?

A temporary workaround should be that "Additional CSS" should always be available and opens the customizer from the same menu location.

**Comment by pauloeaquino** [comment]
5498906-zen
A case where the user wanted to disable the WooCommerce store notice, but had no means of doing so, since access to the Customizer is required. For reference, FSE theme "Russell" was the active theme. For the time being, I just provided a direct link to the Customizer.

**Comment by masperber** [comment]
> Looking into the current state of things, it seems like the 'Customize' button not appearing when it should is only happening on atmoic sites. It also seems like when it isn't present, this absence is consistent across wp-admin and calypso. Is this correct?

@Addison-Stavlo Correct, the missing Customize link only happens on Atomic sites.

> A temporary workaround should be that "Additional CSS" should always be available and opens the customizer from the same menu location.

This workaround does the trick, but it's a bit confusing because you have to click on the back arrow button from Additional CSS before you can access other Customizer functions.

**Comment by Addison-Stavlo** [comment]
Thanks for confirming @masperber -  I updated the title and added a quick edit at the top of the original description since the state of things has changed a bit since it was written.

**Comment by jeyip** [comment]
### Technical Notes

- Consider looking for [remove_submenu_page](https://developer.wordpress.org/reference/functions/remove_submenu_page/) hooks that only apply to atomic sites
- Consider looking for [add_submenu_page](https://developer.wordpress.org/reference/functions/add_submenu_page/) hooks that only apply to simple sites
- The [customize_register](https://developer.wordpress.org/reference/hooks/customize_register/) hook might also be a culprit
- Maybe the issue is in [the wpcomsh repo](https://github.com/Automattic/wpcomsh)?

**Comment by jartes** [comment]
Had another instance of this issue, where a user was trying to access a plugin setting that was only available on the Customizer 37480384-hc

**Comment by mattwiebe** [comment]
Ok, I've finally gotten to the bottom of this one, it was introduced by Automattic/jetpack#23670 ([here](https://github.com/Automattic/jetpack/pull/23670/files#diff-b4bf77ba29e28d691158c77aecd1d7a6d8040521e5400d857989392f837bf6c9R49-R66))

I'll see about removing the removal. It was done to try to reduce confusion for users using block-based themes, but it's acting like the "Additional CSS" module is the only thing that might use the Customizer, which is not going to be the case on Atomic.

I'll open a PR to fix this.

**Comment by mattwiebe** [comment]
Note that although this was closed by automation, the issue will persist until these changes ship via Jetpack
