### ISSUE TITLE
Simple sites only: CSS Gap Property Being Stripped From Customizer

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#60741]
### Quick summary

Custom CSS containing the `gap` property is stripped from simple sites on save.

### Steps to reproduce

1. Edit the additional CSS on a simple site.
2. Set the gap property.
3. Save.

ie:

<img width="297" alt="CleanShot 2022-02-01 at 16 09 04@2x" src="https://user-images.githubusercontent.com/42279181/152066832-27a21752-36b0-4787-aa5d-d785b8a85696.png">

```
.wp-container-61f9a960702ac {
   gap: 0 !important;
}
```

### What you expected to happen

The CSS to remain in the way I saved it.

### What actually happened

The CSS saves, and there is no obvious error, but once the page is refreshed you can see that the `gap` property was stripped.

<img width="300" alt="CleanShot 2022-02-01 at 16 08 13@2x" src="https://user-images.githubusercontent.com/42279181/152066741-ad822744-8402-4407-abc0-55ee9fcbc226.png">

### Context

We ran into this when working on a Team51 project.

CSS Tidy doesn't explicitly allow for the gap property so it gets removed on save, but no error displays.

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

All

### Workaround details

It is possible to set the gap on some blocks in the block settings using the `Dimensions` settings, but no way to set it site-wide. It's also a bit hidden in the Dimensions, and not called Gap there. (It's under Dimensions > Block Spacing for anyone looking.)

**Comment by katiebethbrown** [comment]
Also CSS Tidy Related:
- https://github.com/Automattic/wp-calypso/issues/59568

**Comment by formosattic** [comment]
Confirming that the issue still happens on Simple sites. 

On atomic sites, the `gap` property saves OK.

https://user-images.githubusercontent.com/15944096/156131842-c3c9b4f9-8b80-4150-a3f4-a0ba422f00e6.mov

**Comment by mxhassani** [comment]
Meeting the same blocker when trying to offer a workaround for its other issue:
Automattic/themes#5698

Update: 
`column-gap`, `grid-gap`,  `grid-column-gap`, `grid-row-gap` Seem to be a suitable working alternative for that propriety

**Comment by arunsathiya** [comment]
For columns block that needs a gap, this PR released in Gutenberg 13.0.0 makes it possible without CSS:

- https://github.com/WordPress/gutenberg/pull/40122

**Comment by katiebethbrown** [comment]
> Confirming that the issue still happens on Simple sites.
> On atomic sites, the gap property saves OK.

@formosattic - This is because CSS Tidy (the code that strips this out) only runs on simple sites.

**Comment by Addison-Stavlo** [comment]
related to the other issue and comment here - https://github.com/Automattic/wp-calypso/issues/66936#issuecomment-1238090537  - CSS tidy may be removed completely from simple sites.

**Comment by Addison-Stavlo** [comment]
Retested and this seems to have been resolved now.
