### ISSUE TITLE
FSE / Calypso : Theme filter for FSE themes needed

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#60750]
### What

The calypso theme library (for WPcom sites) does not seem to have any filter for FSE compatible sites. 

### Why

I had a couple of users trying to enable FSE on incompatible themes and wondering where the feature is. 

#32886047-hc

**Comment by donalirl** [comment]
I would like to suggest calling the filter "Site Editor" as that is the same term used in the interface. The terms "Full Site Editing" and "FSE" wouldn't be immediately recognizable to most users.

**Comment by kwight** [comment]
Hm, definitely something odd going on; we _do_ have an FSE tab already, that was added in https://github.com/Automattic/wp-calypso/pull/55043 (in fact, I swear I saw it a couple of days ago). 🙃 So it exists, there has to be a bug not showing it (tested today with a new FSE site):

<img width="800" alt="Screen Shot 2022-02-03 at 8 17 42 AM" src="https://user-images.githubusercontent.com/349751/152383079-c71547eb-d511-4ce1-921c-4f0265704e57.png">

**Comment by sixhours** [comment]
It sounds like the FSE tab was removed on purpose recently; I initially heard about it here: p1643727468688389/1643719471.281689-slack-C01DF571R5Y

And it looks like that was done today in #60642

**Comment by sixhours** [comment]
@Automattic/cylon does it make sense to re-add a tab that only shows FSE themes? See above concerns from HEs/users for context.

**Comment by creativecoder** [comment]
Note that the filter "block templates" will display only FSE themes.

We're actually already using this filter within the Recommended tab in the Theme showcase for FSE sites, but that's not apparent.

Here's a change that updates the labeling to make that more obvious: https://github.com/Automattic/wp-calypso/pull/60834

I'm open to other suggestions!

**Comment by jordesign** [comment]
At the moment the 'block templates' filter doesn't appear to show as an autocomplete when searching for themes.

Additionally - whilst it is a good descriptive slug - it isn't clear to users that this is related to Full Site Editing. Could we adjust the search mechanism there to:

1. Include the filter as an autocomplete
2. Get it to match for broader terms related to Full Site Editing?

**Comment by Greatdane** [comment]
Yes, 'block templates' does not work for me (doesn't show up in search and manually using `https://wordpress.com/themes/filter/block-templates/mysite.wordpress.com` does not work either)

**Comment by kathrynwp** [comment]
> At the moment the 'block templates' filter doesn't appear to show as an autocomplete when searching for themes.

> Yes, 'block templates' does not work for me (doesn't show up in search

Right now, I think this theme filter is **only** available to site stickered as `fse-eligible`.

**Comment by kathrynwp** [comment]
See also this Slack thread where I brought up a similar issue a few days back.

p1643739385414689-slack-C029FM1EH

**Comment by jeyip** [comment]
> Right now, I think this theme filter is only available to site stickered as fse-eligible.

That's what I'm seeing as well. I'm starting to investigate why the theme filter is _not_ working for non-stickered sites.

**Comment by jeyip** [comment]
The `block-templates` filter should now be available on sites still on the classic experience. One thing to note is that for those sites still on classic, the search term will only display FSE block themes and _not_ FSE universal themes. More information about the differences here pNEWy-eIk-p2

All FSE themes will be displayed shortly as we complete the rollout.
