### ISSUE TITLE
Reblog button copies all images to the reblogger's Media Library

### ISSUE THREAD

**Issue by fstath** [Automattic/wp-calypso#60758]
### Quick summary

When a user is reblogging using the Reblog button at the end of a post, all of that post's images are copied to the reblogger's Media Library. It has been reported by one of our forum volunteers as a possible copyright issue.

### Steps to reproduce

1. Go to a post that has the reblog option enabled.
2. Click on the Reblog button and publish the post on your own blog.
3. Open your blog's Media Library and noticed that all that post's images have been copied over.

### What you expected to happen

According to the volunteer the images should be linked, not copied.

### What actually happened

The images are copied to the rebloggers Media Library.

### Context

Forum thread where this is reported:
https://wordpress.com/forums/topic/reblog-button-and-images/

It has been discussed in the forum again a few years ago. Here's that thread too:
https://wordpress.com/forums/topic/reblogging-automatically-uploads-all-images-in-the-post-to-your-media-library/

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by fresatomica** [comment]
A user published a post about how they got sued because of this. The full post is[ here](https://hughsviewsandnews.com/2022/01/31/why-i-was-threatened-with-legal-action-after-reblogging-on-wordpress-a-true-story-and-guest-post-by-deborah-jay-deborahjay2/).

**Comment by kerrynicl** [comment]
I can reproduce this on my test sites.

**Comment by wojtekn** [comment]
I worked with @zaguiini on this issue (D81228-code), and we changed that behavior for two cases: **images that are included in the post content (case 1)** and **the featured image (case 2)**:

- removed the code that copies the post content’s images from the source site to the destination site and leaves them pointing to the source site.
- added support for using a featured image directly from the source site - it saves URL as post meta, then hooks into code that displays reblogged post thumbnail and displays that image.

None of those images are copied to the reblogged site’s Media anymore.

Based on the code review we performed, we can see that there is still code that handles use cases that should be reviewed:

**Reblogging post that includes “gallery” shortcode (case 3)**

The reblogging plugin supports reblogging the gallery added using a shortcode in the classic editor. It parses `[gallery]` shortcode, iterates through all media IDs, copies each to the destination blog, and saves `[gallery]` shortcode with the new IDs.

However, the gallery is not displayed in the reblogged post snapshot on the destination site. The shortcode is removed inside the `clean_up_shortcodes()` function.

As the `[gallery]` shortcode is not displayed there, we could fix this use case by completely removing the code responsible for copying gallery shortcode images to the destination blog.

Additionally, to improve user experience, we could get the URL of the first image from the source gallery, and include it in snapshotted content as a `<img>` tag pointing to the image on the source site.

**Reblogging attachment post that has mime_type = image (case 4)**

Code review uncovered the fourth use case in which an image is copied from source to destination. It handles post that has `post_type` = "attachment" and `post_mime_type` starting with the "image". For such a case, it copies the attached image to the destination "Media" and fills the generated snapshot HTML code with a `<img>` tag that points to the copied image URL. We can fix it by:

- removing the code that copies the image and
- modifying generated `<img>` tag to use source blog as image source

The fix looks straightforward. However, I couldn’t reproduce this case.

We would appreciate feedback from teams @Automattic/build and @Automattic/cylon (and maybe the original author of the shortcode part, @jblz) on the proposed fix for **case 3** and for the clue on how to reproduce **case 4**.

**Comment by wojtekn** [comment]
We have checked this request more and agreed that the current behavior works well according to the [Terms of Service](https://wordpress.com/tos/).

I would also like to point out that blog owners can disable the Reblog feature in the "WP Admin -> Tools -> Marketing -> Sharing Buttons” to prevent users from reblogging the content.

Making the image hotlink would introduce a significant potential for abuse and perhaps even greater liability for individual users.

I will close the issue.

p1g6FD-4I2-p2
