### ISSUE TITLE
Testing: Bring back Mocha integration with IDEs

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#6076]
Part of #4915.

We had working integration with tooling such as Webstorm. It no longer works properly when you execute command like:
`NODE_ENV=test NODE_PATH=client:test node_modules/.bin/mocha test/run-mocha.js`

Latest code looks like:
https://github.com/Automattic/wp-calypso/blob/db8925cb20a8744c07be8c82dc7e4edfb086fbc6/test/run-mocha.js

It would be great to bring integration back and make sure [documentation](https://github.com/Automattic/wp-calypso/blob/2da3f53b9120268cca2bd39108843a0f89c6eeed/test/README.md#how-to-run-mocha-directly) is up to date.

**Comment by umurkontaci** [comment]
I think the regression might be introduced in 336f74b , it's the commit where the script started to return `0 passing` messages. Hope this helps ✌️

**Comment by gziolo** [comment]
Yup, that should be it, I execute Mocha from terminal integration in PhpStorm, so I never played with this script ;)

**Comment by umurkontaci** [comment]
Oh I see, are you able to get the parsed and categorized results displayed inside the IDE with terminal integration?

**Comment by gziolo** [comment]
Nope, that's why I'm interested in learning how to integrate it better :D

**Comment by umurkontaci** [comment]
Gotcha, hope to see it back soon :)

**Comment by samouri** [comment]
Do we need an extra file for IDE integration? Could we run the line:
`NODE_ENV=test NODE_PATH=test:client TEST_ROOT=client test/runner.js`

**Comment by gziolo** [comment]
does it work this way?

**Comment by samouri** [comment]
Yessir :) -- this way we don't need to maintain any extra files.  
If you check out the scripts in package.json you can see exactly what is being run when we type npm run test-client: https://github.com/Automattic/wp-calypso/blob/master/package.json#L135-L138

**Comment by gziolo** [comment]
I might be wrong, but I don't think it's enough to integrate with PhpStorm or Webstorm, the way @umurkontaci previously did it. It looks like to make it happen you need to have script executed by the `node_modules/mocha/bin/_mocha` test runner which. It is required to use `PhpStorm2016.1/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js` reporter.

**Comment by gziolo** [comment]
Related PR for reference: #4111.

**Comment by umurkontaci** [comment]
You are indeed right @gziolo , the entrypoint has to be the mocha executable and the first argument is the script has includes all the tests. 

I think there are a couple of approaches here, if we are to remove the secondary file, we might do a [check](http://stackoverflow.com/questions/4981891/node-js-equivalent-of-pythons-if-name-main) to see if the script is being imported or running standalone.

That being said, we now have a pretty structured test folder structure, we might be able to have one script that does the environment setup with `mocha --require` and use a pattern like `.*\/test\/.+.jsx?` as the test parameter and mocha can do it's own discovery. 

The second approach still requires maintaining another file or a piece of code, but it'll also let us run tests selectively within integrations.

**Comment by samouri** [comment]
Thanks @umurkontaci / @gziolo, you two were very right.  I was able to get IDE integration by following the first approach (performing the referenced check).    While it forces us to 'require' every test file, we can pass in configurations to only run specific test-suites.  Here is an example of only running PostEditor tests:

![screen shot 2016-06-17 at 11 44 43 am](https://cloud.githubusercontent.com/assets/4656974/16156197/ff3bfa3c-3480-11e6-86dc-8f23b0c92eab.png)
![screen shot 2016-06-17 at 11 44 17 am](https://cloud.githubusercontent.com/assets/4656974/16156199/01864d24-3481-11e6-8f78-8a87f898ebe7.png)

**Comment by gziolo** [comment]
It's no longer an issue since we migrated to Jest. See #16943.
