### ISSUE TITLE
Add a Search&Replace option for links

### ISSUE THREAD

**Issue by fresatomica** [Automattic/wp-calypso#60765]
### What

A user suggested adding an option to search&replace links on the site automatically, rather than having to do it manually

### Why

It would save time when having to change links that changed on old posts:
https://wordpress.com/forums/topic/convert-all-download-links-from-http-to-https/.

**Comment by Greatdane** [comment]
I doubt this will be implemented in Simple sites (WordPress doesn't have its own search function anyway, it just uses the browser), but there are plugins that have this functionality. 

Eg, https://wordpress.org/plugins/search-replace/

Another option would be for the user to go to the code editor, copy all the code, paste it into a text editor, then do find and replace, before pasting it back into the WordPress code editor. 

There are also various browser extensions that offer find and replace functionality.
