### ISSUE TITLE
Turkish Characters Don't Appear in Search

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#60770]
### Quick summary

When one searches for a product using non-English characters, the search yields no result.

![HTlJyR](https://user-images.githubusercontent.com/2545184/152181491-2b5ed51a-794c-417c-8bfd-26b138a0dfda.png)

![PgyShR](https://user-images.githubusercontent.com/2545184/152181531-ebdd80e8-9e13-452d-b689-ca48d55e77bc.png)

### Steps to reproduce

1. Create a product with a non-English name with characters.
2. Search for the product.

### What you expected to happen

I expect to see the product in search results.

### What actually happened

It showed no matching products.

### Context

#4743206-zen

### Simple, Atomic or both?

Atomic

**Comment by Sandkorner** [comment]
As I had a discussion here as well, going deeper a bit into the issue, I open this ticket: 4742579-ZEN

**Comment by kriskorn** [comment]
User error: p9F6qB-8ml-p2#comment-45323
Closed.
