### ISSUE TITLE
Woo landing: Icon alignment + mobile

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60788]
Make the icons in footer section align with text as shown in figma 

r6eTqDpL2GGk96hcPLhsBb-fi-877%3A2069

Before
![Screenshot 2022-02-03 at 10-59-24 WooCommerce — WordPress com](https://user-images.githubusercontent.com/811776/152258004-109b94bb-b337-4628-8325-257163a6dde3.png)

**Comment by SaxonF** [comment]
I think this is ok for now @lsl . It's certainly better than what's currently live. For the next iteration we can look at the icon alignment possibly using something other than the promo section component.

**Comment by SaxonF** [comment]
Unless its an easy fix to move the icons next to the header, they by all means go for it :D

**Comment by obenland** [comment]
> Unless its an easy fix to move the icons next to the header

It doesn't look to be, the icon is in a separate div and the component seems to be adamant about not floating it on small screens.

With it not being a high priority for @SaxonF, let's close as `wontfix`.

**Comment by lsl** [comment]
While looking at how to fix margin / line-height issues after making a minor font size correction I found a relatively easy way to do this in https://github.com/Automattic/wp-calypso/pull/60838 (that also solved my problem with the font size change)
