### ISSUE TITLE
Radcliffe 2: Tag cloud styles not applied

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#60785]
### Quick summary

In the Radcliffe 2 theme, the tag cloud does not render with outlines despite being set in the block setting. 

### Steps to reproduce

1. Activate Radcliffe 2
2. Create a new page, adding the tag cloud block
3. Ensure that the block is styled with outlines
4. Observe on the rendered page that the outlines are not present

### What you expected to happen

I expected this:

![Annotation on 2022-02-02 at 15-57-58](https://user-images.githubusercontent.com/39252765/152251908-5c36c25a-28a2-46c8-ae63-f7505294a0da.png)

### What actually happened

I got this instead: 

<img width="467" alt="Screen Shot 2022-02-02 at 3 56 07 PM" src="https://user-images.githubusercontent.com/39252765/152251936-000c358b-d33c-42f3-9b8c-e5c2d8696655.png">

### Context

https://wordpress.com/forums/topic/tag-cloud-radcliffe-2-theme/

### Theme-specific issue?

Radcliffe 2

**Comment by Robertght** [comment]
Thank you for reporting this @metabreakr !

It looks like it's a general issue with Gutenberg at the moment. Closing it in favor of https://github.com/Automattic/wp-calypso/issues/60347
