### ISSUE TITLE
Woo landing: 720 breakpoint

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60789]
PromoCards probably shouldn't stack at 720p, I think they're doing it because they don't have quite enough space with the image padding so this might be fixed by https://github.com/Automattic/wp-calypso/issues/60788

![Screenshot 2022-02-03 at 11-30-18 WooCommerce — WordPress com](https://user-images.githubusercontent.com/811776/152260916-b53bc4d2-b5fe-408b-875b-7f9b59995599.png)

**Comment by obenland** [comment]
They start stacking for me at 1280px, albeit at full width. I've not been able to reproduce them being cut off like this

**Comment by obenland** [comment]
I just noticed the sidebar being cut off, too, which shouldn't be the case.

Are there steps to reproduce this that you can share?

**Comment by lsl** [comment]
> I just noticed the sidebar being cut off, too, which shouldn't be the case.

Like screenshot? That's just an artifact of firefox screenshot "all page" option - not something users see.

There is some weirdness with the sidebar when you change vertical window size while being scrolled down on a long page I've documented somewhere before... (nope cant find might have been on p2)

**Comment by lsl** [comment]
Fix coming in https://github.com/Automattic/wp-calypso/pull/60838

**Comment by lsl** [comment]
Figured out what caused this stacking on 720p screens, there is a flex rule coming from the promo section. [Fixed here](https://github.com/Automattic/wp-calypso/pull/60838/files#diff-9e23959469626859bb1dd6c22b069321bd57c3cc4feb23ba20bb9073e910a50eR94). (I think)
