### ISSUE TITLE
Header heading alignment with footer heading

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60790]
Keep page header left justified, it's stretching with page size.

![Screenshot(59)](https://user-images.githubusercontent.com/811776/152261019-e82ad715-dafc-4520-8dd7-8e9329c2d661.png)

**Comment by lsl** [comment]
@SaxonF do you think we need this change? In isolation it makes sense but I'm looking at other pages (Plugins, Pages) and seeing compact views. Maybe we should condense the footer content with a 1024 max width too?

**Comment by lsl** [comment]
Attempting to change the footer width instead https://github.com/Automattic/wp-calypso/pull/60799, it doesn't quite look right either. For now we're going to leave this as is but this inconsistency with other pages is something that needs a fix at some point.

Lets leave this open until design is able to make a judgement call on which approach makes sense.

**Comment by lsl** [comment]
Tagging this as on hold, ~assuming https://github.com/Automattic/wp-calypso/issues/60789 is in the same boat.~ unrelated.

**Comment by lsl** [comment]
When / if we change this, [the code here](https://github.com/Automattic/wp-calypso/pull/60838/files#diff-9e23959469626859bb1dd6c22b069321bd57c3cc4feb23ba20bb9073e910a50eR20-R25) can be removed to have the footer section content align with the header text. You'll need to add a margin at some breakpoint (I think we're removing it elsewhere.)

**Comment by SaxonF** [comment]
@lsl let's leave consistent with other pages for now (e.g. domains). I need to chat with design team about the evolution of the page header and breadcrumbs.

**Comment by lsl** [comment]
This seems like a wider issue, closing for now.
