### ISSUE TITLE
Woo landing: Remove _blank from target on Learn More

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60792]
For Learn More links around calypso we normally use an inline help component we should either:
- Implement the inline help component https://github.com/Automattic/wp-calypso/pull/60787
- ~Remove _blank~
- ~Add an external link icon to the link~

**Comment by lsl** [comment]
I think https://github.com/Automattic/wp-calypso/pull/60787 is the way to go here, we can close this issue after that merges.

**Comment by allilevine** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/60787
