### ISSUE TITLE
Investigate: Include metadata (like color themes) from websites during Light import.

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#60803]
Let's have an idea of:

1. How this will be presented to the user.
2. What does this involve in terms of customizing the imported site

**Comment by vishnugopal** [comment]
How do you put the colors into the custom color palette?
<img width="266" alt="CleanShot 2022-02-16 at 12 36 36@2x" src="https://user-images.githubusercontent.com/533/154213719-2d3f9012-e267-407d-bc5a-b1ed3e28da7a.png">

**Comment by vishnugopal** [comment]
Only 3 color items need to be extracted right now:

<img width="273" alt="CleanShot 2022-02-16 at 12 46 07@2x" src="https://user-images.githubusercontent.com/533/154214896-c266c704-be32-4f5e-a7f7-23d9108b8670.png">

**Comment by bogiii** [comment]
More info here: `pcmemI-pn-p2`
