### ISSUE TITLE
Let’s ensure that only one import at a time to a destination site is allowed.

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#60804]
This needs to be investigated both at the backend and the frontend. Let's test and understand behaviour.

Currently only imports of one type is allowed at a time from the frontend.

**Comment by bogiii** [comment]
Scenarios for running two imports for the same destination site simultaneously.

**WP and Wix:**
- started an import on the WP -> content only flow (in progress screen is visible)
- in the second tab, started a Wix import (the error screen is there saying "Oops, something went wrong; Try again soon or contact support for help)

**Wix and WP:**
- started an import of the Wix site (in progress screen is visible)
- in the second tab, tried to upload an XML file for the WP -> content only flow (the error message is there saying "Simultaneous imports are not permitted."

**Comment by vishnugopal** [comment]
Can we also check how the WP migration flow behaves?

**Comment by vishnugopal** [comment]
Discussion:
- All cases seem to be covered here, and this seems to be working as intended!
