### ISSUE TITLE
[Bug]: Atomic: Jetpack plugin is disabled when using Jetpack Beta Tester on free sites

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#60814]
### Quick summary

Jetpack plugin remains disabled on subscription removal/expiration when the site has Jetpack Beta tester plugin installed and enabled. 

### Steps to reproduce

1. Get an Atomic site with Jetpack Beta tester installed
2. Use Jetpack Beta tester to switch to Bleeding edge version of Jetpack
3. Go to Store Admin and remove the subscription the Atomic site
4. Go back to Atomic WP-Admin and notice that Jetpack is no longer installed (Nav-unification is disabled, no menu in the navigation)
5. Go to Calypso and notice that admin-menu API endpoint now returns 404 since there's no endpoint defined for it in the Atomic instance (since Jetpack plugin is disabled).

### What you expected to happen

Jetpack Beta tester should be disabled and Jetpack plugin enabled.

### What actually happened

Both Jetpack Beta tester and Jetpack plugins were disabled.

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

You'll need to go to _cli and enable Jetpack: `wp plugin activate jetpack`

**Comment by obenland** [comment]
Let's verify that that the free site plugin set gets activated again when sites lose access to MANAGE_PLUGINS.

**Comment by obenland** [comment]
Diff in D82580-code

**Comment by obenland** [comment]
Fixed in Diff in D82580-code
