### ISSUE TITLE
Ability to revoke Jetpack credentials on AT sites

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#60820]
### Quick summary

The ability to revoke credentials appears on WoA sites. This allows the user to break their jetpack in a way that they cannot fix without support help. 

When this happens we can fix it with the `Autodetect main credentials` option in the VaultPress dashboard but it would be better to hide the ability in the first place

### Steps to reproduce

1. Go to https://wordpress.com/settings/jetpack/
2. click the backups and security section dropdown
3. see the revoke credentials option

### What you expected to happen

the revoke credentials option should never appear for AT sites, only external Jetpack sites

### What actually happened

ability to revoke credentials appears and allows user to revoke, which prevents user from being able to reconnect without HE intervention
![revoke credentials](https://user-images.githubusercontent.com/47717887/152393262-b1ffe705-8052-4216-8f36-0b7bac0fc3f1.gif)

### Context

p9F6qB-6Yh-p2
p1643905521964639-slack-C03TY6J1A

### Simple, Atomic or both?

Atomic

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

those with vmpc access can fix it with the `Autodetect main credentials` option in the VaultPress dashboard

**Comment by JoshuaGoode** [comment]
Old internal discussion for additional context: p9F6qB-6Yh-p2

**Comment by kriskorn** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/62607. Closed.
