### ISSUE TITLE
Signup continues using LayoutLoggedOut after logging in

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#60823]
### Quick summary

While investigating why inline help form was not shown in signup, I've noticed that after the first step of signup (choosing login, password, etc.), the main layout stays [`LayoutLoggedOut`](https://github.com/Automattic/wp-calypso/blob/trunk/client/layout/logged-out.jsx). However, the user _is_ logged in at that point - which can be verified by simply refreshing the page. The page will then be rendered using [`Layout`](https://github.com/Automattic/wp-calypso/blob/trunk/client/layout/index.jsx).

### Steps to reproduce

1. Start at https://wordpress.com/start/ logged out.
2. Verify that the layout is using `LayoutLoggedOut` (requires dev version of Calypso, of course).
3. Sign-up on the first step.

### What you expected to happen

That the layout component is switched to `Layout`. Which has logic to show inline help form:
https://github.com/Automattic/wp-calypso/blob/e7f9bfb6bd08b40aecd2fda722da4877b55ea4f3/client/layout/index.jsx#L172

### What actually happened

`LayoutLoggedOut` stayed active. This creates an inconsistent and confusing behaviour: `Layout` has logic for showing the inline help form, but `LayoutLoggedOut` does not. I could add the same logic to `LayoutLoggedOut`, but that seems to be the incorrect solution. Since we don't have a need right now to show inline help form for logged out users.
However, depending on the implementation details (I'm guessing the root problem here is SSR that's used for logged out users?), that might be needed. If that's the case, at the very least, it'd be good to document it. I'd love @Automattic/team-calypso's input here 🙏 

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Refresh after the first step - it switches to the correct layout: `Layout`. But it's not realistic to expect any user to do that (they might do it on their own, for various reasons, though).

**Comment by tyxla** [comment]
We've had that problem before in other areas, and IIRC the consensus was that it's much harder to prepare Calypso for a switch of the current user (including logging in or out) than to just reload the page or redirect to the next step (rather than just navigating to it). 

The `SignupForm` block doesn't handle the redirect (unless in some specific conditions) and nor does the user signup step, apparently. 

Currently, `goToNextStep()` likely does a `page()` to the next step. I could recommend that instead of `page()` in that case, we do a `window.location.href = ...`. Have you tried that?

**Comment by klimeryk** [comment]
Hah, hadn't thought of that simple solution 😅 I'll give it a try, thank you for the suggestion!

**Comment by klimeryk** [comment]
Marking as resolved as this is no longer needed for the feature and the workaround mentioned above could be good enough if needed 🙇
