### ISSUE TITLE
Review & fix content of "What can be imported?" modals

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#60839]
For e.g. the WordPress migrator has wrong information:

<img width="1901" alt="CleanShot 2022-02-04 at 10 45 15@2x" src="https://user-images.githubusercontent.com/533/152476113-ea948212-e3e5-465e-8134-74fd2fb68dae.png">

**Comment by bogiii** [comment]
I've left the comment with a question on pcmemI-kH-p2#comment-520

**Comment by vishnugopal** [comment]
This requires design input.
