### ISSUE TITLE
[Bug]: FSE: Unexpected/Invalid content when editing Twenty Twenty Two, only on WP.com

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#60837]
### Quick summary

Some block combinations will save and display properly, but when I try to edit the site again, I get an error about unexpected or invalid content, and am asked if I want to attempt block recovery.

Block recovery works I save, I view the site, but the next time I try to edit the header, the error is back.

### Steps to reproduce

1. Activate Twenty Twenty Two
2. Edit Site
3. Use List view to click on the Group inside Header
4. Click three dots > Insert Before
5. Type /cover
6. Select an image
7. Nest the header group under the cover block
8. Save
9. Exit the editor
10. View the site (note the block works fine)
11. Edit Site again

### What you expected to happen

I don't want to have to recover the block every time I edit site.

### What actually happened

I have to recover the block every time I edit site.

### Context

My own tests

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Other notes

I tested a handful of themes. This only happens with Twenty Twenty Two so far as I can tell.

So I was going to file an issue with the theme, but I tested on WordPress.org as well, with and without the Gutenberg plugin, and in beta. I could not duplicate the error there.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Click Attempt Block Recovery every time you edit the site.  It's not so difficult as it is unnerving.

Uploading Screen Recording 2022-01-31 at 7.29.42 PM.mov…

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – not reproducible
Tested on Atomic – not reproducible
Replicable outside of Dotcom – n/a

📌 FINDINGS/SCREENSHOTS/VIDEO
**Simple**
1. added a Cover block above the Header, inserted an image, then moved the entire Header into the Cover block.
<img width="1156" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/7adade55-46c2-4443-adf9-9d99c40581ea">

2. view the site.
<img width="1378" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/39b05314-67c7-43ae-abd7-23f27ee5b9ed">

3. open FSE again.
<img width="1155" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/8d6c7d59-4f4a-4117-bbd8-11077d1a1311">

**AT**

https://github.com/Automattic/wp-calypso/assets/6549265/9f4a8cd7-8de6-4b15-8db5-63c7f94605b6

📌 ACTIONS
- close as Not Reproducible.

If you disagree, please feel free to reopen and leave a comment with updated steps to reproduce with screencaps and/or a video!
