### ISSUE TITLE
Store: WordPress.com branding removal (aka hide Footer Credit) not listed as plan feature

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#60848]
#### Steps to reproduce

1. Pick a site under a Business plan
2. Make a `GET` request to the `/rest/v1.1/sites/:site/features` endpoint
3. Check response.

<img src="https://user-images.githubusercontent.com/1233880/152543966-c188928d-d5bb-4c24-b411-a506ef5f5861.png" width=400>

#### What I expected

The WordPress.com branding removal to be included in the list of active features.

#### What happened instead

It's missing.

#### Context / Source

This is forcing us to do plan checks (e.g. `has_business_plan() || has_ecommerce_plan()`) every time we need to determine whether the site is elegible for removing the footer credit in WP.com or in `wpcomsh`, resulting in more effort for developers since we have to maintain the logic duplicated across many places and repositories.

**Comment by mmtr** [comment]
Prepared a WP.com diff that adds a new WP.com branding removal feature to the Business and eCommerce plans: D74448-code

**Comment by mreishus** [comment]
D74448-code is working properly for me on simple sites.
Note that it doesn't change the behavior of Atomic sites, which are controlled by `footer-credit/theme-optimizations.php` in wpcomsh, which is checking for business bundle directly (and not doing a feature check).

Here, it doesn't seem adding an API call is appropriate to me? It's too much extra work. This is probably a good place to explore if persistent data (as mentioned by @obenland in pdG1ka-17-p2) is a good way to go.

Thinking about it, we need the mapping of "Plan -> Features", which does not vary per site. I believe persistent data varies per site, and is stored for each atomic site. If there was something like "Global Persistent Data" which existed for all atomic sites, we'd only have to push to it in one place, than rather making sure we push to it for each site.
This is a good opportunity for us to find a strategy for checking features/capabilities that works across both simple+atomic.

**Comment by mmtr** [comment]
> Note that it doesn't change the behavior of Atomic sites, which are controlled by footer-credit/theme-optimizations.php in wpcomsh, which is checking for business bundle directly (and not doing a feature check).

Yup, that'd come on a follow-up change. See my comment here: 807-gh-Automattic/wpcomsh#discussion_r798699146. Ideally we want to replace all the plan checks in `wpcomsh` with feature checks in order to avoid maintaining duplicated code across Simple and Atomic.

> If there was something like "Global Persistent Data" which existed for all atomic sites, we'd only have to push to it in one place, than rather making sure we push to it for each site.

That would indeed come in handy! Although the purpose of the Atomic infra is to have sites running separately and isolated, so I'm not sure if the concept of a shared read-only data pool is something technically viable. Without that, an API endpoint which is not site specific (e.g. like the existing `wpcom/v2/plans` endpoint) is somehow conceptually similar.

**Comment by mmtr** [comment]
Closing this one out since, as per discussion in pdG1ka-17-p2, we're finally opting out for not using the features API to perform feature eligibility checks.
