### ISSUE TITLE
Latest Post Block More Tag showing Code

### ISSUE THREAD

**Issue by jackiejade** [Automattic/wp-calypso#60849]
### Quick summary

In Varia themes, the latest post block is not working correctly. 

The "continue reading" is showing as a code in the latest post block instead of just showing the link. 

### Steps to reproduce

1. Switch theme to a varia theme (Tried Hever and Exford) 
2. Create a new page with a Latest Post block
3. Under Post Content settings, enable Excerpt
4. Publish page

### What you expected to happen

I expect the Latest Post block to show the excerpt of the blog post followed by a Continue Reading link. 

### What actually happened

The post excerpt is shown but the Continue Reading link is showing the full code for the link instead of just a link. 
Here's a screenshot:
<img width="879" alt="Screen Shot 2022-02-04 at 10 12 54 AM" src="https://user-images.githubusercontent.com/8549154/152553429-5ab667f9-89ad-4cba-a67c-9995097445ad.png">

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I tried in Varia themes (Hever and Exford) and it showed there. 

Did not show in Blank Canvas, so I'm thinking it's just Varia themes. 

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

As a workaround, you can use the Blog Post block instead and set it to display the excerpt.

**Comment by galakhyati** [comment]
I was able to replicate the issue on an AT test site too with Varia-based themes (checked with Hever, Russell themes). 

User report: (27947292-hc), follow-up ticket: 4749028-zen

**Comment by kerrynicl** [comment]
User reported here as well 34029806- HC

**Comment by carinapilar** [comment]
Another report on the forums: https://wordpress.com/pt-br/forums/topic/desconfiguracao-do-layout-do-tema-libre-2 - they are using Libre 2 and I was able to replicate the issue on a Simple site using Twenty Twenty-One.

The workaround this user used was to disable the option to show the post content on the Latest Posts block.

**Comment by carinapilar** [comment]
I found this report first, but it seems it was already reported one day before this one, here: https://github.com/Automattic/wp-calypso/issues/60849

**Comment by louinel** [comment]
New case here: #4751222-zen

**Comment by syedshaon** [comment]
Another case #4753169-zen
Twenty Seventeen theme.

**Comment by mustu** [comment]
[4751919](https://woothemes.zendesk.com/agent/tickets/4751919)
Theme: Morden

**Comment by arinoch** [comment]
+1 in 4747697-zd-woothemes

Theme: Alves

**Comment by syedshaon** [comment]
Another case #4755024-zen
Libre 2 theme

**Comment by stefancln** [comment]
Another case #4753181-zen  Twenty Seventeen theme

**Comment by cometgrrl** [comment]
This should be fixed with the latest GB update 12.5.3. p1644249951168499/1643982221.485819-slack-CBTN58FTJ

**Comment by syedshaon** [comment]
Another issue 4748475-zen 
Theme: Seedlet

**Comment by fresatomica** [comment]
Another report: https://wordpress.com/es/forums/topic/de-repente-no-funciona-bien-el-bloque-ultimas-entradas/?view=all

**Comment by supernovia** [comment]
Many more reports here:
https://github.com/Automattic/wp-calypso/issues/60832

**Comment by formosattic** [comment]
Closing this in favor of #60832, and we'll follow-up on the cases reported in this thread.

Issue already has a fix deployed.
