### ISSUE TITLE
Jetpack Connect: site installed in directory gets wpcom warning when trying to connect

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#6085]
#### Steps to reproduce
1. Set up a self-hosted site that's installed inside of a folder, so that the URL to see the site is:

```
mysite.com/wp
```

and the dashboard is found at:

```
mysite.com/wp/wp-admin
```
1. Install Jetpack and activate Jetpack. Do not connect Jetpack yet.
2. Go to https://wordpress.com/jetpack/connect
3. Enter your site URL `mysite.com/wp` in the url field and click 'Connect Now'
4. See this warning:

<img width="523" alt="screen shot 2016-06-16 at 9 11 07 am" src="https://cloud.githubusercontent.com/assets/11487924/16117880/56ff3868-33a2-11e6-9042-841654682f2e.png">
#### What I expected

I expected to be able to connect the site
#### What happened instead

I was not able to connect and I got a strange warning about the site being part of WP.com
#### Browser / OS version

Chrome 51, Mac OS X

**Comment by designsimply** [comment]
Tested and confirmed that trying to connect a self-hosted WordPress site setup in a `wp` subfolder using https://wordpress.com/jetpack/connect results in the following error: 

> That's a WordPress.com site, so you don't need to connect it.

![screen shot 2016-11-28 at mon nov 28 6 45 20 pm](https://cloud.githubusercontent.com/assets/1119271/20693470/ce52e236-b59b-11e6-8332-43e6a614636f.png)
<sup>Seen at https://wordpress.com/jetpack/connect using Chrome 54.0.2840.98 on Mac OS X 10.12<sup>

Out of curiosity, how is https://wordpress.com/jetpack/connect different than clicking the "Connect to WordPress.com" button in the `wp-admin` dashboard and why is it needed?

**Comment by v18** [comment]
> Out of curiosity, how is https://wordpress.com/jetpack/connect different than clicking the "Connect to WordPress.com" button in the wp-admin dashboard and why is it needed?

@designsimply the process is the same for both. The connect button is used for people connecting through the plugin, and the direct link is used when we link people to the connection process directly (through support, emails, other documentation, etc).

**Comment by designsimply** [comment]
Cool, thanks for the explanation!

**Comment by BandonRandon** [comment]
I tried to replicate this today and got the error "Not a WordPress site" and not the WordPress.com warning above. However, when I entered the correct subdirectory for WordPress the install process succeeded.  

I'm closing this one in favor of #10980 as the error message has changed slightly and entering the Site URL does work, just not the home directory.
