### ISSUE TITLE
Some Users Are Automatically Unfollowed When They Leave A Comment In Reader

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/wp-calypso#60858]
### Quick summary

 Customer is reporting that some of their followers tell them that every time they leave a comment, they are automatically unfollowed from this site.  I tested this with my account and didn't experience it, but when I look at the user RC for the users mentioned, I do see that they repeatedly unfollow and then follow blogs in a way consistent with what the customer is reporting.

### Steps to reproduce

1. Follow the blog
2. Leave a comment on the blog.

### What you expected to happen

You should still be following the blog.

### What actually happened

In some cases you will no longer be following the blog.

### Context

More details at z[4750747].  Please reply to customer there with any questions or when this is resolved.

### Simple, Atomic or both?

Simple

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
This sounds very similar to this: https://github.com/Automattic/wp-calypso/issues/51787 or at least a potential cause.

cc @Greatdane @kwight

**Comment by autumnfjeld** [comment]
@paxblueribbon. Thanks for reporting this.   What we have been tracking in #51787 is related to the action of following, not commenting.   We recently submitted a [fix for the follow widget.](https://github.com/Automattic/wp-calypso/issues/51787#issuecomment-1047476745)  Also see pbxlJb-UZ-p2#comment-1128

If we are seeing issues strictly related to user being dropped from a blog after making a comment, we can look into that specific mechanism. cc: @arthur791004

**Comment by kerrynicl** [comment]
Not able to replicate but I'll keep this open to be investigated as the URC linked in user report is consistent with behaviour described

**Comment by autumnfjeld** [comment]
I believe this is fixed
https://github.com/Automattic/wp-calypso/issues/51787
https://github.com/Automattic/wp-calypso/issues/51787#issuecomment-1063521107
pbxlJb-UZ-p2

**Comment by igotdes** [comment]
A WordPress mobile app user reported this same issue in #5310330-zen. Specifically, they noted that they were being removed as a follower from certain blogs, and so, they've had to keep re-following the blogs.

I asked if they might have been commenting before being removed. They have just confirmed that to be the case.

Please let me know if there's any other information we can ask the user to help investigate!

**Comment by davemart-in** [comment]
Sounds like this is fixed. Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
