### ISSUE TITLE
Playwright: refactor GutenbergEditorPage into smaller components.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#60868]
### Details

The current iteration of the GutenbergEditorPage for the Playwright framework has been around for the longest time, since April 2021 when the project kicked off. All of us participating in this project has learned a lot on how best to structure a framework since then. 

However, this file is still stuck with the way I had initially set up the structure and this has contributed to the significant bloating of the file. At current count, it has exceeded 600 lines, and changes to its behavior is already beginning to require careful handling.

Not helping matters are the selectors, whose names are odd and do not follow our current conventions. These selectors typically date from the early days of the project.

I propose that current GutenbergEditorPage be split into smaller constituent parts. It can look something like:

- GutenbergEditor(Page|Component): the core iframed portion of the editor, interacting with the block.
- PublishChecklistPanelComponent: component to interact with the publish checklist panel.
- EditorToolbarComponent: component to interact with the top editor toolbar.
- EditorNavSidebarCompoonent: component to interact with the left-hand sidebar.

Combined with existing sub-component `EditorSettingSidebarComponent`, this should nicely divide up the core functionality of the editor into more manageable size.

**Comment by worldomonation** [comment]
@dpasque I'd love to hear your thoughts on this.

It was prompted by my experience in https://github.com/Automattic/wp-calypso/pull/60864 where I tried to make a few changes to the selectors and the draft/publish behavior and found it to be increasingly burdendsome.

Keeping in mind the [single responsibility principle](https://stackoverflow.com/questions/4338831/when-is-a-class-too-big), I think the current iteration of `GutenbergEditorPage` is beginning to violate the said principle.

**Comment by dpasque** [comment]
💯  Definitely agree - I think this would be a very worthwhile refactor!

Clarifying question: in the final iteration, would test scripts instantiate and interact directly with the sub-component POM classes, or would they still interact with the `GutenbergEditorPage` class that is then composed on calls to the sub-component classes?

I've seen it designed both ways before, where you either interact with the modularized sub-components directly, or you only interact with the "parent" POM page classes, which are composed of these smaller sub-components.

I think both approaches are great, and am down for whichever you want to do! 👍

**Comment by worldomonation** [comment]
Glad you're on board ✋ 5️⃣ 

> would test scripts instantiate and interact directly with the sub-component POM classes, or would they still interact with the GutenbergEditorPage class that is then composed on calls to the sub-component classes?

I hadn't really thought about it until you posed the question. 
I've mapped out the advantages and disadvantages of both approaches - let me know if this sounds right.

### Test scripts instantiate subcomponents
**Advantage**
- maximum reduction in the scope of GutenbergEditorPage.
- more 'direct' control provides more granularity for test script writers.
- subcomponents and behavior of the subcomponents can be modified without impacting GutenbergEditorPage.

**Disadvantages**
- difficult to enforce structure for 'flows' that require actions in certain sequence.
- potential overload for test script writers.

### GutenbergEditorPage instantiates and handles subcomponents
**Advantage**
- easier to enforce some structure.
- can present a more unified interface, reducing burden on test writers.

**Disadvantage**
- couples several classes together reasonably tightly.
- refactoring can remain just as difficult as it is now.

For the second approach, perhaps we might even be better served by further refactoring the editor-related functionality of the current `GutenbergEditorPage` into a new subcomponent called `EditorComponent`. This way, GutenbergEditorPage can be the one interface that test script writers interact with. 

---

I'm personally starting to lean towards the second approach. It will be technically slightly more complex to implement, but I think the enforcement of some structure and reduction of test script writer overhead would pay off in the end.

What do you think about the points I've raised? Do they sound accurate?

**Comment by dpasque** [comment]
That is a fantastic pro/con write up! I very much agree with all the points you raised.

>For the second approach, perhaps we might even be better served by further refactoring the editor-related functionality of the current GutenbergEditorPage into a new subcomponent called EditorComponent. This way, GutenbergEditorPage can be the one interface that test script writers interact with.

This ^^ is a great idea! I like this because it effectively combines both options and gets us the best of both worlds. What if we renamed `GutenbergEditorPage` to `EditorFlows` to more match with our syntax? That `EditorFlows` class would then be the one interface test writers would interact with for most of the time, but in one-off cases they can also instantiate the components they need! Stylistically, this also fits all the patterns for POM classes we have laid out elsewhere.

**Comment by worldomonation** [comment]
> What if we renamed GutenbergEditorPage to EditorFlows to more match with our syntax?

This leads a bit into another point of contention that I'm brooding over - that we should discourage any more new `flows` from being added. 

Reason being:
- it makes it too easy for folks to dump everything into a `flow` instead of `component`/`page`.
- flows are a bit brittle by the nature of our UI based test.

But on the other hand, flows like `CloseAccountFlow` does an excellent job of hiding the complex series of steps involved in closing an account. Expecting the test writer to string together the series of steps in the _exact same way each time_ is not realistic, for example. Having the `CloseAccountFlow` helps to standardize how these operations are handled.

I'll start this refactor by going with the name `EditorFlow` for now, but will continue to think about the naming aspect of it.

**Comment by dpasque** [comment]
Yeah, the flows are a tricky area for sure! I agree that they can be wayyyy overused, which is just unhelpful! I do think that the editor might be one area where they are useful though because there's a lot of common re-used actions in the editor that might be used across a lot of different specs

**Comment by worldomonation** [comment]
@dpasque As I progress through this, I noticed you mentioned that it could be a good idea to refactor the editor component into a separate component class.

What do you think about the block inserter itself? I'm debating whether I'd like to extract the block inserter panel into its own class, or keep it as part of the EditorComponent (tentative) class.

Brain dump of my thoughts: below.

### Extract block inserter into its own class
- block inserter is quite complex.
- block inserter supports many actions (blocks, patterns, reusable blocks).
- block inserter is visually a separate component of the overall editing experience.

### Keep it part of EditorComponent
- block inserter works closely with the editor itself, so a standalone block inserter component would introduce unnecessary friction between interaction of the two.

Do you have any thoughts on this matter?

**Comment by dpasque** [comment]
>What do you think about the block inserter itself? 

I'm in favor of pulling it out into it's own class! Like you said, the details of interacting with it involve a decent amount of direct DOM interaction that might be nice to abstract into its own component class. I think that the block inserter is pretty comparable to the settings sidebar, which we also are making its own component class.

That said, I don't think it's absolutely critical if you don't want to do it to start!

@worldomonation

**Comment by worldomonation** [comment]
> I'm in favor of pulling it out into it's own class! Like you said, the details of interacting with it involve a decent amount of direct DOM interaction that might be nice to abstract into its own component class. I think that the block inserter is pretty comparable to the settings sidebar, which we also are making its own component class.

I've started the decoupling of editor components from the (current) `GutenbergEditorPage` class, making the decision to keep the Block Inserter features within the editor component class for now. 

However the way it's structured means it should be quite straightforward to decouple the Block Inserter from the Editor Component class in the future.

**Comment by worldomonation** [comment]
With the last piece merged, I think we can call this project as done.
