### ISSUE TITLE
Allow Atomic sites ability to add demo content from themes like simple sites

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#60875]
### What

Atomic sites should also feature the option given to Simple sites when switching themes for adding demo content. Similar to how we explain it for simple site users in our documentation: https://wordpress.com/support/themes/add-demo-content/#how-to-add-demo-content

### Why

New Atomic users are being confused when they switch themes and they don't see any difference on their site. The only clue for the site are YouTube videos seen from the themes page. It would be a tremendous boost for new users getting started if they could switch to themes and have the option to use the theme content to work from.

### How

![Markup on 2022-02-07 at 15:45:05](https://user-images.githubusercontent.com/83020905/152738177-f67ae5a2-4f98-4cca-a8f1-7e93649831da.png)
Users could be presented with this choice after switching to a theme developed by Automattic, similar to how it works on simple sites.

**Comment by i11za** [comment]
Another request/report here: 35265234-hc

**Comment by hanananah** [comment]
Another request/report: 5170707-zen

**Comment by jamiepalatnik** [comment]
Another user reporting that not seeing any demo content when they switch themes is a confusing experience: 35331632-hc

**Comment by aisajib** [comment]
The user on 35228712-hc was having trouble with this as they thought the theme wasn't being activated, and we had to manually copy-paste the content over from the demo site.

**Comment by sharonlaker19** [comment]
+1 at 5191752-zen, manually imported the content for the Alonso theme to their site.

**Comment by jp-imagines** [comment]
+1 from me as well. Had a user in 5209388-zd-woothemes who wanted newly activated themes to look like the theme demo image, which currently requires us to manually export/import demo site content for AT sites.

**Comment by jp-imagines** [comment]
Closing in favor of an older issue with some more discussion: #56869
