### ISSUE TITLE
Task: Add Subtitles and Learn More Links to Several Calypso Pages

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#60876]
### Details

On 25+ screens in Calypso, there is a subtitle followed by a Learn more link that leads to a support doc. Example from Stats:
![image](https://user-images.githubusercontent.com/30727666/152490861-f9e71ce4-cbee-4aba-be59-32dbc161cace.png)

Subtitle: Learn more about the activity and behavior of your site's visitors. 
Doc link: https://wordpress.com/support/stats/

Here are the remaining Calypso screens that we would like to add subtitles and links to.

### Checklist

*Has a subtitle, needs a Learn more link:*
- [x] Settings > [Performance](https://wordpress.com/settings/performance): `https://wordpress.com/support/settings/performance-settings/`
- [x] Users > [Followers](https://wordpress.com/people/followers): `https://wordpress.com/support/followers/`
- [x] Users> [Email Followers](https://wordpress.com/people/email-followers): `https://wordpress.com/support/followers/`
- [x] Users > [Invites](https://wordpress.com/people/invites/): `https://wordpress.com/support/user-roles/#adding-users-to-your-site`

*Needs a subtitle and learn more link:*

- [x] Posts > [Categories](https://wordpress.com/settings/taxonomies/category): Create, edit, and manage the categories on your site. `https://wordpress.com/support/posts/categories/`
- [x] Posts > [Tags](https://wordpress.com/settings/taxonomies/tags): Create, edit, and manage the tags on your site. `https://wordpress.com/support/posts/tags/`
- [x] Me > [My Profile](https://wordpress.com/me): Set your name, bio, and other public-facing information. `https://wordpress.com/support/manage-my-profile/`
- [x] Me > [Account Settings](https://wordpress.com/me/account): Adjust your account information and interface settings. `https://wordpress.com/support/account-settings/`
- [x] [Reusable blocks](https://wordpress.com/types/wp_block/): Create, edit, and manage the reusable blocks on your site. `https://wordpress.com/support/wordpress-editor/blocks/reusable-block/`
- [x] Upgrades > [Email](https://wordpress.com/email/): Add a custom email address to your domain. `https://wordpress.com/support/add-email/`
- [x] Jetpack > [Backups ](https://wordpress.com/backup/)(atomic only): Restore or download a backup of your site from a specific moment in time.  `https://wordpress.com/support/restore/`
- [ ] [Plugins](https://wordpress.com/plugins/): Add new functionality and integrations to your site with plugins. `https://wordpress.com/support/plugins/`

*These currently share the same tagline as 'Marketing Tools'. Instead, we'll have specific taglines and Learn more links for each tab:*
- [x] Tools > Marketing > [Traffic](https://wordpress.com/marketing/traffic/): Manage settings and tools related to the traffic your website receives. `https://wordpress.com/support/traffic/`
- [x] Tools > Marketing > [Connections](https://wordpress.com/marketing/connections): Connect your site to social networks and other services. `https://wordpress.com/support/publicize/`
- [x] Tools > Marketing > [Sharing Buttons](https://wordpress.com/marketing/sharing-buttons): Make it easy for your readers to share your content online. `https://wordpress.com/support/sharing/`

### Related

https://github.com/Automattic/wp-calypso/pull/55078

**Comment by jordesign** [comment]
I've taken the initiative to just add this straight to Vertex's board - this would be a great addition.

**Comment by jordesign** [comment]
I've tried a PR for the first 4 items - but it looks like the link is persisting between different sections of the 'People section even though it is set to be different...
https://github.com/Automattic/wp-calypso/pull/61813

**Comment by arcangelini** [comment]
OK, I started working on this and we may need someone from design to weigh in on what we should do with the taxonomy pages (Tags and Categories) and Plugins page. Currently, there is no space at the top to add the subtitle and link. It doesn't look like the other pages.

<img width="786" alt="Markup 2022-03-11 at 18 31 31" src="https://user-images.githubusercontent.com/33258733/157918935-c2ea5f59-5e4c-445c-b512-b49e48d00aa9.png">

<img width="1099" alt="Markup 2022-03-11 at 18 34 00" src="https://user-images.githubusercontent.com/33258733/157919019-d1412327-4b02-4e68-8b5a-d8f3f051e2e3.png">

All of the others should be simple and I will begin working on them. I am not sure who I should reach out to specifically so I am going to ping @simison

**Comment by jordesign** [comment]
Ooh true - as it isn't really a 'settings' section of Calypso. It's housed with the post/page content kind of areas.... Good catch.

Maybe that one sits on the backburner until we can get some design input.

**Comment by arcangelini** [comment]
Some clarification would be helpful for the Email page. I am seeing 2 different pages depending on what site I am using and both have support/guidance links.

<img width="1160" alt="Markup 2022-03-24 at 11 39 08" src="https://user-images.githubusercontent.com/33258733/159900700-acd08a31-ae82-4f9b-8d39-d7a559c45e4e.png">

**Comment by donalirl** [comment]
> Some clarification would be helpful for the Email page. I am seeing 2 different pages depending on what site I am using and both have support/guidance links.

I'm seeing it there too now. I found this other interface shows up on some sites:
![image](https://user-images.githubusercontent.com/30727666/160042648-d0d15463-2ad2-4eed-9b51-6125950c32a5.png)

but considering this screen is intended to drive purchase, adding a support doc link might just distract. I would vote to leave the email screen as is.

**Comment by arcangelini** [comment]
All of these have been accounted for except Plugins. That header is incorporated into a few other components and is not able to be formatted like the others. If someone from design wants to propose a solution then we may be able to move forward with something. I am going to close this now as we are all 🚀  done

**Comment by donalirl** [comment]
I tested the newly added links and they work well!

It doesn't look like Categories and Tags have received subtitles and links. Neither have the three subpages in the Marketing tab:

- Tools > Marketing > [Traffic](https://wordpress.com/marketing/traffic/):
-  Tools > Marketing > [Connections](https://wordpress.com/marketing/connections):
-  Tools > Marketing > [Sharing Buttons](https://wordpress.com/marketing/sharing-buttons)

Can those be added?

**Comment by arcangelini** [comment]
Yes, there are still 3 PRs awaiting approval to address these including jetpack backups. #62210 #62261 #62226

**Comment by arcangelini** [comment]
Closing again now that everything has shipped 🚢
