### ISSUE TITLE
Domains: Icon on Delete button on domain manage /domains/manage/ looks broken

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#60878]
### Quick summary

The trash can icon on the Delete button on ` /domains/manage/`  looks broken.

![CleanShot 2022-02-07 at 08 51 13@2x](https://user-images.githubusercontent.com/51966986/152755819-d7d0b837-6386-4aae-8c6b-82c914914d03.png)

### Steps to reproduce

1. Go to non-primary domain settings

### What you expected to happen

Delete button should be formatted correctly

### What actually happened

Delete button look broken

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Firefox and Chrome on MacOS

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

**Comment by formosattic** [comment]
The trash icon doesn't show now, though still appears in the code if I read it correctly.

Aside from that, the Delete button works fine.

![image1](https://user-images.githubusercontent.com/15944096/154037349-04ed2d12-e5b8-446d-a86e-c25aa97c55c8.png)

**Comment by delputnam** [comment]
The button appeared broken due to a PR that added the icon to a component that is used in multiple places. We (Nomado) removed the icon when it is used in the domain management pages during our last sprint.
