### ISSUE TITLE
Theme Instructions Wrong on Quadrat

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#60873]
### Quick summary

When looking at theme options, the instructions say to go to Appearance>Customize.

<img width="640" alt="Screen Shot 2022-02-06 at 12 37 05" src="https://user-images.githubusercontent.com/2545184/152693626-1e60aa1b-19d6-4dcd-b9e0-1cfb6ad7632d.png">

This is not an option for some:

<img width="640" alt="Screen Shot 2022-02-06 at 12 37 05" src="https://user-images.githubusercontent.com/2545184/152693666-38f5a05d-9642-43c6-bfb8-dac3ca26a2bf.png">

### Steps to reproduce

1. Activate Quadrat on a site. 
2. Go to Appearance>Themes>Info
3. Note that it refers to Appearance>Customize
4. Note there is no option like that on the site

### What you expected to happen

I expect the instructions to be accurate. 

### What actually happened

They were inaccurate.

### Context

I found this while helping a customer.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Quadrat

### Reproducibility

Consistent

### Severity

All

### Workaround details

Go straight to https://whatever.wordpress.com/wp-admin/customize.php in a browser.

**Comment by Robertght** [comment]
The Appearance > Customize appears to be a valid one now, however, if this keeps resurfacing, please open the report.
