### ISSUE TITLE
Reader: Platform script for Twitter appearing in some full posts

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#6089]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/blogs/1065188/posts/513006
2. Notice all the script urls to platform.js
3. Be happy you're not stuck in a hole like Ryan.

#### What I expected
To not see the script links

#### What happened instead
I saw them and I was sad.

#### Browser / OS version
Chrome / Mac

#### Screenshot / Video
<img width="647" alt="screen shot 2016-06-16 at 9 59 56 am" src="https://cloud.githubusercontent.com/assets/14350/16119366/29c8c4fc-33a9-11e6-863a-836b711d2cdb.png">

**Comment by suryagh** [comment]
@blowery would you be able to provide the steps to reproduce this locally.

**Comment by blowery** [comment]
These instructions should work if you just replace wordpress.com with calypso.localhost:3000

**Comment by lancewillett** [comment]
I couldn't repeat this one — let's re-open if it happens again in the future.
