### ISSUE TITLE
Accessibility: question on branching

### ISSUE THREAD

**Issue by amandarush** [Automattic/wp-calypso#609]
Since accessibility is not a feature, or if it's considered a feature for the purposes of contributing to Calypso, would be huge, how should this be branched?

**Comment by lancewillett** [comment]
Let's open new issues for separate a11y concerns: https://github.com/Automattic/wp-calypso/issues?q=is%3Aopen+is%3Aissue+label%3AAccessibility

Keeping them small and actionable.
