### ISSUE TITLE
Subscription Form block: Changed Success Message text doesn't get displayed

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#60909]
### Quick summary

The changes made to the Success Message text on the Subscription Form block aren't showing up. 

Instead, the default message is being shown, which is "Success! An email was just sent to confirm your subscription. Please find the email now and click 'Confirm Follow' to start subscribing."

### Steps to reproduce

1. Add a new page.
2. Add Subscription Form block and edit the Success Message text to a custom message. I set the message to 
```
Success! 

An email was just sent to confirm your subscription. Please find the email now and click 'Confirm Follow' to start subscribing.

Here is the latest copy of the Healthy Society Magazine for you to look over, we hope to welcome you soon.

https://healthysociety.com.au/wp-content/uploads/2022/02/HS-Magazine.pdf


Stay Fit and Stay Healthy

The HS Team
```
3. Visit the front end of the page and submit the Form
4. The success message shown is "Success! An email was just sent to confirm your subscription. Please find the email now and click 'Confirm Follow' to start subscribing." and not the ones I had set. 

### What you expected to happen

Expected the message to be:

```
Success! 

An email was just sent to confirm your subscription. Please find the email now and click 'Confirm Follow' to start subscribing.

Here is the latest copy of the Healthy Society Magazine for you to look over, we hope to welcome you soon.

https://healthysociety.com.au/wp-content/uploads/2022/02/HS-Magazine.pdf


Stay Fit and Stay Healthy

The HS Team
```

### What actually happened

The default success message was shown:

```
Success! An email was just sent to confirm your subscription. Please find the email now and click 'Confirm Follow' to start subscribing.
```

### Context

Customer report: 34081594-hc
Follow up: 4760233-zd-woothemes

I was able to replicate the issue on my Atomic test site.

Related issue found: https://github.com/Automattic/jetpack/issues/22193

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by Greatdane** [comment]
I tried to replicate this, but changing the success message worked for me. I got the correct message (I made sure I was logged out and used another email address);

<img width="577" alt="Markup 2022-02-17 at 14 54 34" src="https://user-images.githubusercontent.com/5075840/154414329-8f9c8105-3489-41b1-a20f-2459a0f42895.png">

This was on an Atomic site with the Blockbase theme.

@galakhyati - are you still able to replicate? if so, could you provide more information, please? Theme used etc?

**Comment by Robertght** [comment]
I cannot replicate this anymore. Please re-open if you see more cases.
