### ISSUE TITLE
My home carousel: Hide this popup should hide on swipe events

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60905]
The "Hide this" pop up sticks around even after you swipe left or right. On mobile when you touch on one of the cards while this pop up is present the whole card goes white. (Can't see this on laptop but do see it on mobile android/firefox)

https://user-images.githubusercontent.com/811776/152894119-836b3dfd-da28-492f-8df5-f29bbb39d385.mp4

**Comment by lsl** [comment]
@autumnfjeld does @Automattic/ganon still own this?

**Comment by autumnfjeld** [comment]
Added to Ganon board. :)
