### ISSUE TITLE
Notification wording for new comment on followed post

### ISSUE THREAD

**Issue by AliSoftware** [Automattic/wp-calypso#60922]
### Quick summary

The wording for a notification about a new comment on a post you follow seems to have recently changed, and currently uses a surprising wording:
![image](https://user-images.githubusercontent.com/216089/152995152-de38116f-dac0-40d1-a74c-c29f5d843e10.png)

I'm pretty sure the wording we use everywhere else is about "comments" not "remarks", and that it should read "X commented on Y" rather than "X remarked on Y"

[Internal reference of the comment this notification was about: p8Qyks-2nl-p2#comment-830]

### Steps to reproduce

1. Follow a post authored by someone else
2. Wait for someone to comment on said post
3. Open the Notifications list
4. Find the notification about that new comment that was recently added to that post you followed.

### What you expected to happen

The notification wording should read "X commented on Y" (and the corresponding translations in other locales)

### What actually happened

The notification wording reads "X remarked on Y" in English.

(and corresponding translations in other locales; at least in French it similarly says "X a publié une remarque sur" rather than "X a commenté sur")

### Context

#dogfooding 

### Browser

Google Chrome/Chromium, iOS Safari

Note that the issue is also present on the mobile app (WordPress iOS) as well (which is not surprising given iinm, the content of the notifications shown in the mobile apps come from the back-end)

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – not reproducible
Tested on Atomic – 
Replicable outside of Dotcom – not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO
**Simple**
<img width="318" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/5c3cd6c8-2cc1-4db1-aff3-402e3a02072c">

**AT**
<img width="331" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/4c62b0b6-607d-4fd5-9146-e3da3158ca66">


📌 ACTIONS
- closing as Not Reproducible.

📌 NOTES

I also tested using en-GB, but the same term is used ("comment").

If you disagree, please feel free to reopen and leave a comment with updated steps to reproduce with screencaps and/or a video!
