### ISSUE TITLE
[Block] Navigation  - Settings > Advanced > "manage menus" fails to open WP-Admin Menus page, FSE and Classic Themes

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#60932]
#### Steps to reproduce

* Visit the site editor
* select a navigation menu
* in the block toolbar open the "Select Menu" dropdown.
* Select the "manage menus" option:

![Screen Shot 2022-02-08 at 3 00 08 PM](https://user-images.githubusercontent.com/28742426/153067299-9f81bcd9-cc1d-4502-b03c-9c004bbc56b0.png)

This option by default links to wp-admin, which is not allowed from our calypso editor integration resulting in the gray screen:

![image](https://user-images.githubusercontent.com/28742426/153067404-23dfd848-ac27-4353-ba2a-2afe598856b4.png)

#### What I expected

No gray screen and proper navigation to the selected interface.

#### What happened instead

Gray screen 😞

**Comment by jeyip** [comment]
@Addison-Stavlo @creativecoder @zaguiini Are any of you still able to reproduce this? Here's what I'm seeing on a full site editing enabled dotcom simple site.

![2022-03-03 15 32 39](https://user-images.githubusercontent.com/5414230/156670879-aa0154a8-363f-49b9-8484-e06983539c47.gif)

**Comment by arinoch** [comment]
Can we arrange to update the user in 4801735-zd-woothemes if this issue is fixed? I'm closing this ticket as it's been open since February 22.

**Comment by Jaccuse** [comment]
Another case in 34463900-hc

I was able to reproduce the bug on my Simple site, `right-click` -> `open in new tab` worked for me and worked for the user in my case

**Comment by jeyip** [comment]
I can reproduce this consistently. The problem is that the iframe attempts to navigate itself to a different origin than the page in which it is embedded .

Ex. The page origin is `https://wordpress.com/site-editor/testsite.wordpress.com`, but the embedded iframe wants to navigate to  `https://testsite.wordpress.com/wp-admin`. Working on a fix now.

**Comment by jeyip** [comment]
@arinoch @Jaccuse tested on dotcom and this should be fixed now

**Comment by carinapilar** [comment]
@jeyip, I'm afraid this issue is back, I'm seeing this on my test sites.

The workaround `right-click` -> `open in new tab` did the trick.

**Comment by druesome** [comment]
Another report: 5578307-zen

Right-clicking on the link to open in a new tab works.  However, I wonder what the linked page is for?  All that can be done is move the menu to trash and not really "manage" or edit it.

<img src="https://d.pr/i/dU3Yv4+" width="600" />

**Comment by ha-un** [comment]
Another report: 38312803-hc

**Comment by ccwalburn** [comment]
Another instance here: 5958010-zen

Gave them the direct link and the right-click workaround

**Comment by cuemarie** [comment]
This was escalated here: p1676582124204579-slack-C0160HSMDQV with the note that it's impacting every theme tried so far, so I've updated the labeling to get it triaged, since user reports are starting to come in as well.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Could Not Replicate**
- Tested on AT: **Could Not Replicate**

https://user-images.githubusercontent.com/27249804/221081243-0135f8f1-bef0-4802-a3b1-1fd098c68f0f.mov

📌 FINDINGS/SCREENSHOTS/VIDEO
- It appears that recent updates have resolved this. I have no option to `Select Menu` _from the floating block toolbar_ across any of my test sites - in each test, a brand new navigation menu only allows me to find **Manage Menus** in the block settings sidebar, where we don't run into the iframe issue that the in-editor link was having. 
- The timing of these seems to indicate Gutenberg v15.0 or .1 may have this resolved, though I can't see an exact fix in the changelogs.
- Is anyone here able to replicate any longer?

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

**Comment by cuemarie** [comment]
Reopening as @ccwalburn can still replicate this issue in the theme **Apostrophe 2**, from the sidebar.

https://user-images.githubusercontent.com/27249804/221670089-c6a04c42-e2a3-46a6-a177-7950fd24e4b2.mp4

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: ~~Replicated~~ Could Not Replicate
- Replicable on Core? ~~Yes~~ No (updated per [this comment](https://github.com/Automattic/wp-calypso/issues/60932#issuecomment-1489408216))

📌 FINDINGS/SCREENSHOTS/VIDEO
- Steps taken to replicate:

1. On a test site, in a page, post, or template, add the Navigation Block.
     - Note - do not use a Page List, but an editable menu, or else the Nav Block > Settings > Advanced > "Manage Menus" link won't appear
3. Select the Navigation Block, then the gear icon (Settings)
4. Open the Advanced Module, and select "Manage Menus"

**Other Testing Notes**

- Google Chrome shows the error `....wordpress.com refused to connect`
- Firefox shows `Firefox Can’t Open This Page`, but provides a link to `Open Site in New Window`, which does work.
- **Twenty Twenty Two** on an AT site worked as expected - no errors. 

**AT Example - Classic Theme, Post Editing**
Theme: _Twenty Twenty-One_

https://user-images.githubusercontent.com/27249804/224509872-8716656d-1dee-4748-9d17-ccbdf5f96fdb.mov

---

**Simple Example - FSE Theme, Template Editing**
Theme: _Tú_

https://user-images.githubusercontent.com/27249804/224509432-76932b05-e821-4259-aa75-3014b50edabe.mp4

---

**Self-Hosted Example - Classic Theme, Page Editing**
Theme: _Hemingway Rewritten_

https://user-images.githubusercontent.com/27249804/224509411-33c13758-570a-4559-bed3-ac0ce762163d.mp4

---

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Updated title to better reflect the issue
- Reported here: p1678573076229239-slack-C01LXBU1N21

**Comment by Addison-Stavlo** [comment]
Updating here, I think the Iframe removal should resolve these issues on dotcom once and for all - p58i-eb7-p2

@cuemarie , im slightly confused regarding the last replication prompt you posted:

> Replicable on Core? Yes

This looks to be dotcom specific, am I wrong? ` ....wordpress.com refused to connect` should technically not happen on core itself since core replication test shouldn't be associated with any dotcom environment.

It seems these links refuse to connect because they are trying to navigate internal to the iframe where it lacks permission/support (hence why "different tab" seems to be the work around). Am I missing something else where this is replicated in core?

**Comment by cuemarie** [comment]
Hey @Addison-Stavlo , thanks for following up!  I'm thinking I was confused myself on that last bit 😊 Just tested again, and in my self-hosted environment, I'm not seeing the issue; the Site/Page Editor > Header > Navigation Block > Settings > Advanced > `Manage Menus` directs me straight over to `/wp-admin/edit.php?post_type=wp_navigation` without issue.

I've edited the triage notes above to avoid future confusion!

**Comment by cuemarie** [comment]
I'm no longer able to replicate this across AT and Simple. Tested with Gutenberg 16.2.1 and 16.3:

Simple:

https://github.com/Automattic/wp-calypso/assets/27249804/18c31625-e15d-4f7b-a903-3be5c35bad9c

AT: 

https://github.com/Automattic/wp-calypso/assets/27249804/fadada59-6ceb-476b-af32-68f083401aa0

📌 ACTIONS
- Closing as resolved / no longer relevant
