### ISSUE TITLE
Blogger.com import doesn't associate tags with posts despite importing them

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#60953]
### Quick summary

Importing an xml export from Blogger.com that has tags (labels) associated with posts results in tags being imported but not associated with the respective posts.

### Steps to reproduce

1. Create a new Blogger.com site with at least a few posts that have at least a few labels/tags (in my case I created 3 posts with 6 labels) 
![image](https://user-images.githubusercontent.com/39308239/153184042-662ac4b6-22cb-4701-aff4-5fc0e0fa2601.png)
2. [Export the backup](https://support.google.com/blogger/answer/41387?hl=en) xml file
3. Import as in [Import from Blogger](https://wordpress.com/en/support/import/coming-from-blogger/)
4. Open any of the imported posts

### What you expected to happen

See the same tags that the post used to have at Blogger.com

### What actually happened

Imported posts have no tags, despite all tags being imported and seen in Posts > Tags

![image](https://user-images.githubusercontent.com/39308239/153184299-d09b3a9d-4a01-4b61-b6b5-09e673960b0d.png)

![image](https://user-images.githubusercontent.com/39308239/153183968-5427b169-5d87-48a4-a6c6-a0e64be654f4.png)

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Add the tags manually to the posts

**Comment by formosattic** [comment]
Thanks @zdenys!

I confirm the same is happening with my test site.

![image1](https://user-images.githubusercontent.com/15944096/154015921-a3b77d82-f59a-47e8-b33a-b0827c51ae6f.png) 

![image2](https://user-images.githubusercontent.com/15944096/154015978-6d94e2cc-abda-453d-b189-18b038e4e584.png)

**Comment by vishnugopal** [comment]
A diff is up here now for review: D75608-code

**Comment by vishnugopal** [comment]
The diff is now deployed. This should be fixed!
