### ISSUE TITLE
Atomic: Add purchase information to Persistent Data

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#60965]
### What

Let's add site-based purchase information to Persistent Data and find a way to keep that up to date with future purchases.
I'm not sure how much we need to account for the Product Registry (pbOQVh-1xl-p2) work for this, it might be a bit too early for that.

### Why

Sites will have the ability to make add-on purchases beyond a plan. We'll need to be able to determine the features a site has access to on the Atomic side, so paired with a features list this new field in Persistent Data will allow us to create a full picture.

### How

We might be able to take inspiration from how the plan slug is kept in sync with Persistent Data. Searching Opengrok for `atomic_persist_data` shows its current use.

**Comment by mmtr** [comment]
D74991-code

**Comment by DustyReagan** [comment]
(Just a note for tracking.) D74991-code is accounting for purchase changes on the Atomic side. What do we need to do to account for changes coming from Store Admin?

**Comment by mmtr** [comment]
Nice catch @DustyReagan! I'll create a new diff to handle that.

I also noticed that we need to sync the purchases data after an Atomic transfer, which will be covered on a new diff as well.

**Comment by mmtr** [comment]
Just created D75328-code which should cover the remaining scenarios.
