### ISSUE TITLE
Hero flows: Multiple intents leaves some rendered below the fold.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#60975]
The mobile view of the intents selection step really only shows the first two options, unless the user scrolls down – but contains some wasted whitespace. This layout could be improved, and will be very useful for the seller experience intent.

![img-8734](https://user-images.githubusercontent.com/349751/153281673-01c64938-0a1d-47c9-88cf-e6b4b9a8e4f0.png)

**Comment by kwight** [comment]
A first step here is to track down a Figma from the Blogging Experience and verify what the whitespace measurements should be (to see if we even have a problem here).

**Comment by sixhours** [comment]
Checking it against the Figma, looks like we could reduce the whitespace a bit:
<img width="400" alt="Screen Shot 2022-02-16 at 10 50 11 AM" src="https://user-images.githubusercontent.com/2124984/154302699-4f38bda2-bba8-404a-9ccf-3b49b33e86bf.png">

But I'm not sure that will be enough to bring the seller experience above the fold. Will tinker with it and find out.

**Comment by sixhours** [comment]
![IMG_4A0FEA81916E-1](https://user-images.githubusercontent.com/2124984/154307341-0d32bc92-eeb1-43e5-b6ba-861e4d4049cc.jpeg)

Hmm, the spacing looks correct in my browser when using the mobile emulator, and on my iPhone (screenshot above) in both Safari and Chrome. Not enough to keep Sell above the fold, though. We would need design input on how to redesign the layout to fit everything on one vertical screen.

**Comment by sixhours** [comment]
@kwight What phone/browser combo is shown in the screenshot in the OP? Trying to figure out if the spacing shown there is a bug because I'm not able to reproduce it.

**Comment by kwight** [comment]
@sixhours I think that would have been an iPhone 8 in the Chrome devtools mobile view (or just 375px wide responsive).

As long as the mobile layout is reasonably matching the Figma, that was my biggest concern – we don't need to make changes at this point to keep Sell above the fold. Side note, I wonder if tiles (two across) would help? ¯\_(ツ)_/¯ 

Closing for now, it'll come up again if it's a problem as we go forward.
