### ISSUE TITLE
[Bug]: Shopping cart popup doesn't look quite right

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#60970]
### Quick summary

The current when I have placed something in the shopping card I see the following popup. 

<img width="579" alt="Screen Shot 2022-02-09 at 11 21 13 AM" src="https://user-images.githubusercontent.com/115071/153274610-4dedd627-075a-40d4-ae10-2b98db5b9e3d.png">

Notice the right border next to the nubmer. 

### Steps to reproduce

Add plan to card but don't pay for it. 

### What you expected to happen

To not see the border next to the number.

### What actually happened

<img width="509" alt="Screen Shot 2022-02-09 at 11 17 39 AM" src="https://user-images.githubusercontent.com/115071/153274772-c7f65d50-ea13-45c7-9af3-597e2dd84f19.png">

### Context

empathy testing

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic - could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

<img width="339" alt="Screenshot 2023-06-14 at 4 22 02 PM" src="https://github.com/Automattic/wp-calypso/assets/27249804/f7db3f7c-597e-4dff-995c-50f843849037">

📌 ACTIONS
- Closed as not reproducible
