### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#60988]
### Quick summary

The `calypso_signup_plan_change` event's parameters are not _snake_case_.

See: https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/analytics/signup.js#L179-L187

### Steps to reproduce

1. Open a page that generates a `calypso_signup_plan_change` event.
2. See the error is displayed on the console.

### What you expected to happen

The event must be ignored only because is not a listed exception.

### What actually happened

The event is ignored because it does not match `/^calypso(?:_[a-z0-9]+){2,}$/` and is not a listed exception.

**Comment by arthur791004** [comment]
Oops, the reason is that the event name ended with a space 😅

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/60989

**Comment by zaerl** [comment]
@arthur791004 👍
