### ISSUE TITLE
Limited Atomic: Can't buy another paid plugin once site is Atomic

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#60992]
### Details
You can't buy another paid plugin if your site is already Atomic but without a supported plan. What happening here is, when you try to buy the paid plugin, it also adds a business plan. Somehow the business plan is getting removed from the cart. The result is you get the following message. Note that the plan was not removed manually. 

<img width="1308" alt="Screenshot 2022-02-10 at 3 44 03 PM" src="https://user-images.githubusercontent.com/86406124/153386498-6bb6e1c6-6c63-491f-9ac6-24666a2658c6.png">

**Comment by obenland** [comment]
This seems to be fixed now, I assume after we moved the cart validator to using feature checks
