### ISSUE TITLE
Seller Experience: Minor copy fixes needed

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#61009]
Typo in this paragraph, "than" should be "then".

![image](https://user-images.githubusercontent.com/2124984/153462099-aa2f4a84-9faf-43b1-851f-3ae96b3e2bd0.png)

The headings at the store intent step "Start simple" and "More Power" are inconsistent about capitalization. We should pick one. :)

**Comment by kwight** [comment]
> The headings at the store intent step "Start simple" and "More Power" are inconsistent about capitalization.

Let's go with the former (change "More Power" to "More power").
