### ISSUE TITLE
Themes doc link focuses on classic experience instead of FSE

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#61007]
### What

When I have FSE site with FSE theme, and I go to /themes page, I see docs link next to my theme:

![image](https://user-images.githubusercontent.com/87168/153445871-8f54d796-b199-444a-ae5f-34967eeb68f0.png)

There's another "Learn More" link right under "Themes" heading.

They open up classic theme docs:

<img width="1075" alt="Screenshot 2022-02-10 at 17 57 13" src="https://user-images.githubusercontent.com/87168/153445956-3b846b3b-0d0e-42c1-9d07-814e5d6994bb.png">

![image](https://user-images.githubusercontent.com/87168/153446353-4607d201-d28a-4ac0-b23d-3da1292139f4.png)

"Setting up theme" link here specifically is about customizer.

I would expect more FSE focused docs. cc @dona

### Why

FSE rollout :-)

**Comment by Addison-Stavlo** [comment]
There is now information about block based themes in this section. 

Im going to remove this issue from our board since there doesn't seem like much for us to action here.

Can we close this at this point @simison ?

**Comment by simison** [comment]
If it's sorted, yep feel free to close these in future 👍
