### ISSUE TITLE
Seller experience: The simple product page has a confusing "Home" title and placeholder image.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61014]
The simple product page has a "Home" title and placeholder image, making it look rather awkward and junky. Let's remove them (users would likely change or remove them anyways).

<img width="1411" alt="Screen Shot 2022-02-10 at 11 33 35 AM" src="https://user-images.githubusercontent.com/349751/153483880-8cbba50c-ff1f-4b30-a430-47c920b33ab5.png">

**Comment by kwight** [comment]
@SaxonF @alaczek Any thoughts here? Simply removing them seems the easiest and quickest way forward (we still want to get the MVP out to then do further iteration).

See: paYKcK-1hA-p2 at 15:19 for discussion

**Comment by SaxonF** [comment]
I'd +1 removing for now. For V2 we should consider utilising our vertical content to pre-fill images and text so it feels more like a website, as well as a template that's appropriate for a one-pager. e.g.

![image](https://user-images.githubusercontent.com/1072756/153506207-f025008a-aad0-499e-b9a7-f0fef0b8e2d5.png)
![image](https://user-images.githubusercontent.com/1072756/153506243-4cb643f4-e063-4bf6-8f28-f76dcbbabd88.png) 
![image](https://user-images.githubusercontent.com/1072756/153506124-cfeb1182-b2b0-412c-9c45-3ec64d432b34.png)

**Comment by alaczek** [comment]
+1 to everything @SaxonF said :) We can remove the page title by switching to the Header and Footer only page template:
![image](https://user-images.githubusercontent.com/4550351/153507488-61b8ba0e-eea2-4c85-b191-08b805f6638d.png)

**Comment by alaczek** [comment]
We chatted with @SaxonF and we both thought the default pattern is too blank. So I created a new one, based on the two layouts (pictured above) that Saxon's been using. This is the design from Figma:
![Frame 4265](https://user-images.githubusercontent.com/4550351/153541360-cbc3c153-7a7f-444a-9488-e6f97b9f852d.png)

From this, for the MVP we'd only use the product pattern (and we can later launch the whole thing as a theme). I built it o the source site here (unpublished, because I wanted your or @ianstewart eyes on it, but feel free to publish it). Here's the preview from the source site:
![image](https://user-images.githubusercontent.com/4550351/153541585-9b4205bd-5d95-4885-8276-15b67016e8e8.png)

...and here's the preview when dropped on a site using Zoologist (page with Header and Footer Only template):

![image](https://user-images.githubusercontent.com/4550351/153541750-9b9c6b54-cf8d-48dc-b15d-da1a565124da.png)

**Comment by alaczek** [comment]
Now that I look at it, I wonder if we should fill in the details (item name, price, description). It looks a bit weird with opinonated image and background, but using generic text.

**Comment by ianstewart** [comment]
I think either fill in the the details to be more opinionated or make the pattern less opinionated and more of a template like so:

![image](https://user-images.githubusercontent.com/545779/153617885-00f03ae2-dd76-4d95-9e36-8aa51e18d727.png)

**Comment by iamtakashi** [comment]
<img width="1141" alt="Screenshot 2022-02-14 at 13 04 22" src="https://user-images.githubusercontent.com/908665/153870358-99f37420-5b84-4e84-b3f9-3daf0aa6235d.png">

What do the social icons do? If the viewer can share the product by clicking those icons, it makes sense to be there. But if they are just links to social media profiles of the shop, I'm not sure if we need those...

**Comment by kwight** [comment]
> I think either fill in the details to be more opinionated or make the pattern less opinionated and more of a template

@alaczek Which approach do you feel is best? I like the idea of it all being more generic – the user would be replacing it all anyways, and it's simpler and quicker to implement. Happy to do whatever you think is best though.

> What do the social icons do? If the viewer can share the product by clicking those icons, it makes sense to be there. But if they are just links to social media profiles of the shop, I'm not sure if we need those...

Hm, true – but I also like the idea of showing the user the _potential_ of something. Curious what @SaxonF and Ola prefer.

**Comment by SaxonF** [comment]
>  it's simpler and quicker to implement

Based on the discussion @kwight and @ianstewart and I had around verticalisation I would agree that if its easier to start generic then let's do that.

We can work towards showing an image that's related to the industry they are in, along with the product name and price they entered previously in the flow (if they didn't skip).

**Comment by SaxonF** [comment]
![image](https://user-images.githubusercontent.com/1072756/153967941-d1324c6a-5926-480e-aa74-559fc2494bd6.png)


We could use something more abstract like the above or just a placeholder image like the below

![image](https://user-images.githubusercontent.com/1072756/153968008-94e3cc6f-5b12-4d27-8f2b-ef647250c725.png)

**Comment by alaczek** [comment]
Ok, I made changes based on all the feedback:
* used a placeholder image (as per @SaxonF's mockup above).
* changed background to light grey.
* removed social media icons.

I decided to update the original pattern - so it's already, published, updated & ready to go.
https://dotcompatterns.wordpress.com/2022/02/03/single-product/

**Comment by sixhours** [comment]
Going to close this out since the Home/featured image issue has been fixed by #61085. I'll follow up with the pattern updates in #61087!
