### ISSUE TITLE
Seller experience: The simple path is disabled after clicking Back from the "more power" path.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61016]
The simple path cannot be chosen after clicking Back from the "more power" path. It works fine on a first selection.

![2022-02-10 11 55 24](https://user-images.githubusercontent.com/349751/153486647-5a5f5424-a047-47a2-9583-2eb17ca2ae26.gif)

**Comment by sixhours** [comment]
I noticed as I was testing this that both simple *and* powerful options are disabled after clicking back! Not sure if that's helpful in solving this but something to keep an eye on. :)

**Comment by nelsonec87** [comment]
Strange, for me the powerful button keeps working but, if:
1. I go back a few more times
2. Try go go through the seller flow again (without refreshing or anything)

The flow finishes _before_ asking the type of store.

I'm now investigating if there's a problem in the flow's step stack
