### ISSUE TITLE
Seller experience: WP.com footer may not be appropriate.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61017]
We add a WordPress.com footer to new sites, such as "Blog at WordPress.com", that might not be suitable for a new e-commerce site (Maybe something like "Start selling on WordPress.com." would be better).

<img width="1137" alt="Screen Shot 2022-02-10 at 12 02 21 PM" src="https://user-images.githubusercontent.com/349751/153487461-56eeaae0-53b5-42b5-b092-6ac3490e46e6.png">

**Comment by kwight** [comment]
There would be a few steps to this:

* Find out if these footers are still randomly-generated (or are they all fixed for new sites).
* See how we can specify a footer link for new sites from the seller experience flow.
* Determine where it should link to (do we have e-commerce landing pages?).

**Comment by nelsonec87** [comment]
We could take advantage of this feature:

![image](https://user-images.githubusercontent.com/3801502/154321307-bcda8a35-4d15-411b-a94d-18b20b99a751.png)

Use the `WordPress.com Logo` for example, or add a new option focused on e-commerce sites.

This setting is not available on calypso. It redirects users to the customizer.

**Comment by nelsonec87** [comment]
This information is stored in the `footercredit` option.

Is creating a new endpoint for setting this option a good choice?

**Comment by kwight** [comment]
Hm, right, it sounds like adding a new commerce-focused value ("Start a store on WordPress.com") and then setting that value by API during our flow would be a good approach (likely one diff for adding the value, and another for adding the endpoint that sets the setting).

**Comment by kwight** [comment]
D75180-code for adding the new value.

**Comment by nelsonec87** [comment]
D75294-code for setting the option.
