### ISSUE TITLE
Seller experience: The empty image placeholder on the Payment block can be improved.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61015]
The empty placeholder image for the Payment block could be a confusing first impression to a new user, and leaves an unbalanced whitespace area on the front-end. Let's consider adding some sort of default image (even just a grey box).

| Editor | Desktop Front-End |
| --- | --- |
| <img width="1193" alt="Screen Shot 2022-02-10 at 11 40 26 AM" src="https://user-images.githubusercontent.com/349751/153485469-edf0a6c3-60e0-4ab2-ba7f-a7b73d723b3a.png"> | <img width="1190" alt="Screen Shot 2022-02-10 at 11 51 10 AM" src="https://user-images.githubusercontent.com/349751/153485720-e72ea48b-8cfe-45ed-aab5-e55c17a3207b.png"> |

**Comment by kwight** [comment]
@alaczek see: paYKcK-1hA-p2 at 16:07 for discussion

**Comment by kwight** [comment]
See also https://github.com/Automattic/wp-calypso/issues/61014#issuecomment-1036322201

**Comment by sixhours** [comment]
Fixed by #61087
