### ISSUE TITLE
Seller experience: Update onboarding images.

### ISSUE THREAD

**Issue by SaxonF** [Automattic/wp-calypso#61026]
### Details

- Remove image from "Set up your store"
- Replace the image on "First let's give your store a name" to this SVG

![store-name](https://user-images.githubusercontent.com/1072756/153527506-31bde236-a851-4f29-b477-c3586f34017c.svg)

**Comment by kwight** [comment]
We'll split this into two separate issues: the image change, and the content changes (the text changes will need to be added to the preemptive translations file, and then we'll merge that when translated).

**Comment by kwight** [comment]
Content changes will be handled in https://github.com/Automattic/wp-calypso/issues/61082
