### ISSUE TITLE
Seller experience: Investigate other placeholder methods for the pattern content.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61021]
Our commerce pattern content acts as a placeholder for a user's new home page, which they would need to replace. Instead of using content, we might be able to use other Gutenberg-native placeholder abilities.

**Comment by kwight** [comment]
I couldn't find any way in the editor itself to set a placeholder for content, but there is the `placeholder` property when [defining block templates](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/). @obenland you mentioned it was available to only headings and paragraphs; is it the latter you were referring to?

**Comment by obenland** [comment]
Sounds likely, yes. I did use it in the updates template, so that makes sense.

**Comment by kwight** [comment]
Cool, so this is an option (being followed by @sixhours in #61137).
