### ISSUE TITLE
[Bug]: Seedlet and Mayland show up in onboarding

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#61038]
slack p1644577717086629-slack-cylon

### Quick summary

Seeldet and Mayland show up at /start onboarding design picker, they shouldn't:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/87168/153627992-e2d7192d-92ed-4894-a068-62a78f3910e2.png">

These themes were meant for migration purposes (I assume). 

When chosen, they show up in editor broken:

![image](https://user-images.githubusercontent.com/87168/153628199-b5f0ef3a-ea78-4be9-ac32-052c4ea55178.png)

### Steps to reproduce

- /start
- Look at themes step
- pick seedlet or mayland (they shouldn't be here)
- Land in editor, no theme applied

### What you expected to happen

No themes.

### What actually happened

—

### Reproducibility

Consistent

### Severity

All

**Comment by Addison-Stavlo** [comment]
Note - these are also available in the theme showcase.

I network deactivated these themes this morning, but they still seem to be showing up. Perhaps this is due to cache or maybe there is another issue in the mix.

**Comment by creativecoder** [comment]
I set the theme.wordpress.com posts for these themes to draft, and that seems to address the issue by removing theme from the design picker (along with removing them from the theme showcase).

Asked if we should fully retire them here: pNEWy-eIE-p2

**Comment by simison** [comment]
This can be closed I suppose?
