### ISSUE TITLE
Marketplace: Partners landing page

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61032]
Let's check how we can update https://wordpress.com/partners/ to suit the Marketplace needs

- [ ] Should we link to the Marketplace terms too? (pdh6GB-7N-p2#comment-697)
- [x] Determine how to update the contact form auto-reply content based on input from @emmnyc85
- [x] Implement auto-reply content updates https://github.com/Automattic/wp-calypso/issues/61772
- [ ] Design task to figure out what copy/content changes we need to make to this landing page.
- [ ] Design task to update the branding to be more in line with the rest of Dotcom. I’d prefer to keep it simple as I don’t know yet how valuable this page will be.
- [ ] Implement design updates.

Acceptance criteria:
- [ ] New design is implemented, Figma (still in progress): SJ6I0rUUtHNdHMF2KMMJig-fi-456%3A10269
    - If the design isn't ready, we can take the interim step of replacing the contact form with an "Apply now" call to action
- [ ] The contact form has been replaced with a link to [the partner signup form](https://woocommerce.com/partner-signup/)

related convos: pdh6GB-uc-p2 and pdh6GB-TW-p2

**Comment by emmnyc85** [comment]
@allilevine - Can we re-engage on making copy changes to /partners? I've made recommended edits here: (drive link removed, see https://github.com/Automattic/wp-calypso/issues/62641) We let this slip through the cracks and want to prioritize getting this done over the next couple weeks please.

Once we have basic copy changes done, we can evaluate other changes to make. cc: @cpapazoglou

**Comment by allilevine** [comment]
> @allilevine - Can we re-engage on making copy changes to /partners? 
> 
> Once we have basic copy changes done, we can evaluate other changes to make. cc: @cpapazoglou

@emmnyc85 Thanks for sharing the edits! My understanding was that we needed to redesign this page completely. I've put it on @vinimotaa's radar and I'm going to get a project thread ready for when we have designs. 

I'd like to approach updating this flow holistically, working on this as the same time as https://github.com/Automattic/wp-calypso/issues/61617 so that the design, content, and functionality are all in step with each other. But let me know if I'm missing any immediate business needs for copy changes.

**Comment by emmnyc85** [comment]
Thanks, @allilevine. My intention is not to force a total redesign. My goal is just to focus on the copy for now if possible. Maybe @vinimotaa can look at the copy changes and see if we can leverage the existing design for now please. we want to make this lightweight and just make sure 1/ partners have the right expectations when they arrive at /partners and 2/ we can gather interest for marketplace. Just clarifying all this to make sure we are all aligned :)

**Comment by allilevine** [comment]
> Thanks, @allilevine. My intention is not to force a total redesign. My goal is just to focus on the copy for now if possible. Maybe @vinimotaa can look at the copy changes and see if we can leverage the existing design for now please. we want to make this lightweight and just make sure 1/ partners have the right expectations when they arrive at /partners and 2/ we can gather interest for marketplace. Just clarifying all this to make sure we are all aligned :)

@emmnyc85 Got it, thanks for clarifying! That sounds great to me.

**Comment by allilevine** [comment]
@emmnyc85 @cpapazoglou I opened a separate issue for copy changes: https://github.com/Automattic/wp-calypso/issues/62641

**Comment by paulopmt1** [comment]
This is the main change for the next sprint: pdh6GB-TW-p2.
Here are some tips on how to rebuild CSS for /partners page: D78736-code. Please look at the `How to test` section.

![image](https://user-images.githubusercontent.com/1044309/170585491-0911f60f-e815-4eb0-9d40-aa818e993106.png)

**Comment by lsl** [comment]
Confirming acceptance criteria for this in our next sprint is something like:
- [ ] The contact form has been replaced images seen in design [above](https://github.com/Automattic/wp-calypso/issues/61032#issuecomment-1139087070)
- [ ] Contact us copy has been replaced, with new CTA section header and link to https://woocommerce.com/partner-signup

Will these changes allow us to close this issue?

**Comment by allilevine** [comment]
> Confirming acceptance criteria for this in our next sprint is something like:
> 
> * [ ]  The contact form has been replaced images seen in design [above](https://github.com/Automattic/wp-calypso/issues/61032#issuecomment-1139087070)
> 
> * [ ]  Contact us copy has been replaced, with new CTA section header and link to https://woocommerce.com/partner-signup
> 
> 
> Will these changes allow us to close this issue?

@vinimotaa Does that sound right to you or are additional changes needed?

**Comment by vinimotaa** [comment]
Hi @allilevine that sounds right - the major change will be to replace that entire section and redirect both CTAs (first fold CTA also change its copy to "Apply now") to the Partners page.

**Comment by lsl** [comment]
Closing, replacement issue here: https://github.com/Automattic/wp-calypso/issues/64512
