### ISSUE TITLE
[Bug]: three consecutive banners when landing in FSE

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#61036]
### Quick summary

There are three upsells/banners in the editor and at least two of them are conflicting with each other (core banner and WPCOM banner). 

See p1644591908914389-slack-C01DF571R5Y for context.

### What to do:

Quoting @simison :
1. Mobile banner shows up too early and then hides; it should be visible in the editor first thing, just like in post/page editor. => PR for this: https://github.com/Automattic/wp-calypso/pull/61134
2. We should show one tour. I’d say let’s show the .com one but no biggie if it’s easier to just show the core one. We’ll do some changes here soon anyway.
3. Let's also ensure we can separate site-editor mobile banner in tracks events from page/post editors. But check first with apps team if that's ok and expected

### Steps to reproduce

See p1644591908914389-slack-C01DF571R5Y for context.

### What you expected to happen

We should show one tour.

### What actually happened

Two tours are showing.

### Context

Discussion about the two modals (the Welcome Tour and the Core modal) is here: pbAok1-2vM-p2

### Browser

iOS Safari

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
Let's also ensure we can separate site-editor mobile banner in tracks events from page/post editors. But check first with apps team if that's ok and expected.

**Comment by escapemanuele** [comment]
Discussion about the two modals (the Welcome Tour and the Core modal) is here: pbAok1-2vM-p2
