### ISSUE TITLE
Plugin Browser: search icon miss-alignment in mobile

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61033]
![image](https://user-images.githubusercontent.com/12430020/153604200-72c92e55-b56c-4a52-a184-ad01dd120f26.png)

**Comment by ianstewart** [comment]
I can reproduce with a new site on my iPhone.

![image](https://user-images.githubusercontent.com/545779/153614778-bbe87267-f23d-4f3e-b8e2-a0648aa69ab8.png)
