### ISSUE TITLE
WPCOM Atomic / Ownership Transfer: User facing ownership transfers

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#61041]
### What

_Please reach out to @Automattic/reactor members, or myself, for questions or concerns about this request._ 

A user-facing ownership transfer option for WPCOM Atomic sites that takes care of the following transfers between users.

1. Selected subscriptions.
2. Site ownership.
3. The primary Jetpack connection owner.
4. Jetpack Backup (VaultPress) owner. (~Requires escalated support privileges for current transfers, has an endpoint available.~ Internal HE tool now provisioned.)

### Why

**_A8C: Please refer to internal documentation for the steps required for every Atomic ownership transfer: P9HQHe-kd-p2_**

At this time, transferring ownership of a WordPress.com Atomic site is a very manual task that requires contacting support. An HE then has to take ~7 extensive steps for the user.

It also requires that HEs reach out to a handful of escalated Atomic support HEs to handle a specific part of the transfer.

There is not a user-facing option for a full ownership transfer that takes care of subscriptions in addition to the following.

1. The transfer of the site owner.
2. The transfer of the site's primary Jetpack connection/connection owner.
3. Jetpack Backup (VaultPress) owner. (~Requires escalated support privileges for current transfers, has an endpoint available.~ Internal HE tool now provisioned.)

### How

For the Jetpack Backups (VaultPress) ownership transfer, utilize the endpoint that was made for this issue.

* ~If the rest of this cannot be implemented quickly, an HE-facing tool could be made for this Jetpack Backup/VP owner transfers.  Such a tool could be a temporary workaround that would save users and HEs time and reduce the need for escalated assistance.~ Internal HE tool now provisioned.

* pIFnH-6Ca-p2#comment-27364
* pbuNQi-19S-p2

The transfer process should include options to confirm the site and subscriptions that need to be transferred.

It also needs to gracefully change the primary Jetpack connection owner without disconnecting other users on the site.

**Comment by JoshuaGoode** [comment]
Noting that an internal VaultPress/Jetpack ownership transfer was provisioned but the rest of the steps are still quite manual, generate long support interactions.

**Comment by katinthehatsite** [comment]
Hi @JoshuaGoode , we have added this option in https://github.com/Automattic/dotcom-forge/issues/2563 and it will go out for testing today so I am going to close this as completed.
