### ISSUE TITLE
CPT: Display notice after post actions succeed or fail

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#6104]
Currently, there's no indication of success or failure when trashing a post from the custom post type listing screen. The post simply disappears. We should display a notice to inform the user whether their action succeeded or failed.

**Comment by nylen** [comment]
Related: #6306, #6536

The immediate disappearance of the post from the list is a bit jarring IMO - this could use an animation to make it more clear what is going on.

**Comment by aduth** [comment]
>The immediate disappearance of the post from the list is a bit jarring IMO

Hmm, it may be possible to use [React's `CSSTransitionGroup` component](https://facebook.github.io/react/docs/animation.html) to apply a transition as the post is being removed from the list. I might even imagine a few variations of this to reflect the type of action taking place - a disappearing post on trash, a "stamp of approval" on publish. Maybe I'm getting a bit carried away 😄  cc @hugobaeta

**Comment by hugobaeta** [comment]
I think for now it should mimic whatever happens for Blog Posts and Pages. If we iterate, we should iterate across all of these.

**Comment by nylen** [comment]
The experience on those listing pages is already quite different:

![trash-post-fixed](https://cloud.githubusercontent.com/assets/227022/16789917/11ae2758-4877-11e6-9e27-f743f1938f32.gif)

The immediate "optimistic" update in the CPT listing screen is what makes me think an animation would help.

**Comment by aduth** [comment]
The initial goal of this issue is now satisfied, notably by the following related PRs:

- #6306
- #6530
- #6645
- #6723

There's some room for improvement here around notice text (including more details about the post) and multiple actions, e.g. #6855 . Additional enhancements should be filed as separate issues.
