### ISSUE TITLE
Navigation Block: Add ability to add button inside of the navigation block

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#61058]
### What

It would be great to be able to add a button inside of the navigation block.  

### Why

Often users want to add a button to their menu, which is styled differently from other menu items.  This is often used for a donation or login link.  This is currently not possible without adding in custom CSS.

![Markup on 2022-02-13 at 13:45:11](https://user-images.githubusercontent.com/24914028/153739099-d9071505-1c73-45b2-8323-8da4fa9d2b21.png)

A user _could_  add a button block next to the navigation block to achieve this on desktop, but on mobile, this formatting would not allow the button to be inside of the **mobile** navigation

![Markup on 2022-02-13 at 13:54:30](https://user-images.githubusercontent.com/24914028/153739266-aabcf926-b0dd-4e68-8359-ffc2dd2dc235.png)

![Screen Capture on 2022-02-13 at 13-53-17](https://user-images.githubusercontent.com/24914028/153739246-fd41bc12-8173-4ac9-9104-eab56dc36b51.gif)

### How

We could add in a button option here when adding in a new menu link.

![Markup on 2022-02-13 at 13:55:51](https://user-images.githubusercontent.com/24914028/153739331-f068c9a1-c4b5-4062-b612-fa8cd9d69805.png)

**Comment by edequalsawesome** [comment]
1. Yes please
2. This is a core issue that's reported here! https://github.com/WordPress/gutenberg/issues/35924

**Comment by csabarakasz** [comment]
Same request here:

- [ ] 5619504-zd-woothemes

This would be awesome!

**Comment by masperber** [comment]
Same request here 43477696-hc

This would be a great feature addition!

**Comment by filipanoscampos** [comment]
Also requested here: [6661441-zen](https://a8c.zendesk.com/agent/tickets/6661441)

**Comment by filipanoscampos** [comment]
6661441-zen

**Comment by annezazu** [comment]
Closing this out as this was implemented previously in Core 🥳  https://github.com/WordPress/gutenberg/issues/35924
