### ISSUE TITLE
Map block: Map does not render on the live site if more than 55 locations are added

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#61051]
### Quick summary

On the map block, the first 55 locations render the map fine on the live site. Anything beyond that fails and the locations appear as a list on the live site. Editor view is fine.

### Steps to reproduce

- Add the map block to a post/page.
- Add 55 locations.
- See that the map block renders okay on the live site.
- Add one or more locations to the same block.
- Map does not render.

### What you expected to happen

Map renders irrespective of location count, because I don't see a limit mentioned:

https://wordpress.com/support/wordpress-editor/blocks/map-block/

### What actually happened

Map does not render, locations appear as a list.

### Context

User report: 4770985-zen.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I don't think so.

### Browser, operating system and other notes

- Happens only on simple sites. Atomic fine.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No and the platform is unusable

**Comment by kerrynicl** [comment]
Another report here but map does not render at all even at 3 locations  Zen- 4778669 
[Screengrab](https://d.pr/i/Tmnliz)

**Comment by edequalsawesome** [comment]
This is also reported here: 268-gh-Automattic/view-design

Closing in favor of that issue!
