### ISSUE TITLE
Highlights Not Affecting File Block

### ISSUE THREAD

**Issue by Jaccuse** [Automattic/wp-calypso#61056]
### Quick summary

The Highlight feature is available on the File Block, but it doesn't seem to do anything. You can change the text or background color and it will not affect the File Block. I have seen this on a Simple and an Atomic site.

![image](https://user-images.githubusercontent.com/31910936/153730823-dfd0634a-64e1-4615-837d-4e9e41b8f00d.png)

### Steps to reproduce

1. Add file block to page or post
2. Open Highlight settings in the block toolbar
3. Select a specific color for `Text` or `Background`
4. The color should not be applied to either the file block's text or button

### What you expected to happen

I'm not sure if the highlights would apply to the hyperlinked text above or the button below in the file block, but I would expect that the text highlight would change the text for the top link and the button, then the background highlight would affect the button's background.

### What actually happened

Changing the highlights doesn't have any visual effect and the highlight settings get un-set immediately.

### Context

I ran across this originally in 34164686-hc

### Simple, Atomic or both?

Simple, Atomic

**Comment by edequalsawesome** [comment]
> I'm not sure if the highlights would apply to the hyperlinked text above or the button below in the file block, but I would expect that the text highlight would change the text for the top link and the button, then the background highlight would affect the button's background.

Highlight is intended to highlight particular text that you've selected, not the general color and background of a particular element of a block -- you can see what I mean in the GIF below:

![2022-03-02 17 35 59](https://user-images.githubusercontent.com/4000628/156461795-43376e0c-389a-455d-a63e-feb2f7b75553.gif)

This is working as expected, so I'm going to close this for now :)
