### ISSUE TITLE
FSE: Template Part fails to save if the name contains an emoji

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#61052]
### Steps to reproduce

1. Create a new Template Part via SIte Editor > Template Parts > Add New
2. Include an emoji (such as 💚) in the name and click Create
3. Add any block to the template part
4. Click Save

### What you expected to happen

Emoji should either be supported in the Template Part's name or validation should be implemented for the Template Part name at the time of its creation.

### What actually happened

`Saving failed.` message is displayed.

### Context

https://user-images.githubusercontent.com/39308239/153716804-9a24ce2b-3c55-4004-a869-2f0e6d6ed175.mov

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Any FSE compatible theme. I tested with Twenty Twenty-Two and Kerr.

### Browser, operating system and other notes

macOS Monterrey 12.2.1 with Chrome 98

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by edequalsawesome** [comment]
Duplicated on a self-hosted site, reported to Gutenberg repo: https://github.com/WordPress/gutenberg/issues/39174

**Comment by sanjeev00733** [comment]
Tested this on my test site (simple) with `twenty twentytwo` and `remote` themea and I am able to create new template parts with emojis in the title. 

![image](https://user-images.githubusercontent.com/18581859/173980656-734cad28-eed6-4e71-a8d4-28643cba7814.png)
