### ISSUE TITLE
Backup: Improve UX, disable all Restore buttons if a restore is ongoing

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#61066]
### Quick summary

When there's an ongoing Restore, `Jetpack > Backup` will still show the option to start a new Restore, which is misleading for users.

It should be like `Jetpack > Activity Log` where all Restore buttons are disabled.

This appears to just be an issue on the front-end. On the back-end, if there's an ongoing restore, a new one won't get started simultaneously. 

Enhancement suggestions for `Jetpack > Backup`, when a restore is ongoing: 

* All Restore button should be disabled (greyed out), just like in Activity Log
* Have the below progress area show automatically
![image1](https://user-images.githubusercontent.com/15944096/153744368-7c08034a-1de9-4783-8249-3d6a2ce2a225.png)

### Steps to reproduce

1. Start a Restore from `Jetpack > Backup` or `Jetpack > Activity Log`
2. Go to `Jetpack > Backup`, then check different backup, the Restore button is active

### What you expected to happen

Restore button should be all disabled (greyed out), just like in Activity Log.

### What actually happened

Restore button is active under `Jetpack > Backup`.

We can click the Restore of any backup, though it looks like the progress bar reflects the current restore ongoing, but it's confusing since the restore date doesn't match (see example in video, restored date is Feb 13, towards end I select a restore for Feb 10) 

https://user-images.githubusercontent.com/15944096/153744044-18c3a401-e45d-4662-85a0-0b4d57caba95.mov

### Context

Just testing around.

Test on self-hosted site, same happens. Will transfer to Jetpack repo.

### Simple, Atomic or both?

Atomic

**Comment by manzoorwanijk** [comment]
Added this to Voyager Maintenance 1164141197617539-as-1201825952025343/f
