### ISSUE TITLE
Reader: Writing a comment on a post causes an alert popup to appear on the screen

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#61063]
### Quick summary

While writing a comment on a post in the [Reader](https://wordpress.com/read), an alert popup message will appear with the following message: `You have unsaved changes. Are you sure you want to leave this page?`

![reader-popup](https://user-images.githubusercontent.com/21261509/153803907-a7c94bf7-39ee-474b-bc03-b155d2af66ea.png)

Here is a video of the issue:

https://user-images.githubusercontent.com/21261509/153804092-a172e99f-5370-4fe0-9795-10ce9fb672a4.mov

### Steps to reproduce

1. Go to the Reader: https://wordpress.com/read
2. Select a post with comments enabled.
3. Start writing a comment.
4. While you are writing a comment, an alert popup will appear on the screen. (If you click on 'OK' you will be redirected to another post).

### What you expected to happen

To be able to write a comment on the post without any alert popups. 

### What actually happened

An alert popped up while I was writing a comment on a post.

### Context

I recently came across two user report of this issue:

4773909-zd-woothemes
4773452-zd-woothemes

[Slack thread 🧵 ](p1644810795140839-slack-C03TY6J1A)

Special thanks to:
@jromales  and @kuropixel for testing!

### Browser, operating system and other notes

Google Chrome: Version 98.0.4758.80
Microsoft Edge: Version 98.0.1108.51

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The workaround is copy/pasting the comment from a text/word editor and then pasting it into the comment box.

**Comment by simranvijwani** [comment]
another one 4775534-zd

**Comment by fresatomica** [comment]
This was also reported here: https://wordpress.com/forums/topic/wordpress-reader-34/?view=all

It looks like there are some keyboard shortcuts active on Reader. Press L will like the post, J and K will move you to the next or previous post. It's not possible to write a comment while those are active.

**Comment by ktyfuller604** [comment]
Another report here 34191923-hc

They said their entire community is discussing this issue. They are currently using the workaround.

**Comment by ktyfuller604** [comment]
Another report here 34193911-hc

**Comment by bluefuton** [comment]
@Automattic/team-calypso looks like this could be a regression related to https://github.com/Automattic/wp-calypso/pull/60812?

**Comment by sirbrillig** [comment]
Confirmed: this only happens when typing `j` or `k` (also when you press `l` it toggles liking the post). Definitely a regression from #60812

**Comment by bluefuton** [comment]
I have a revert ready in https://github.com/Automattic/wp-calypso/pull/61091 👍

**Comment by bluefuton** [comment]
Reverted and now appears to be fixed. 

cc @tyxla for followup

**Comment by donalirl** [comment]
Had a report of this in #34189896-hc. They tried again just now and confirmed it's working. They mentioned the issue only happened when typing the letter j or k, which I thought I'd share here just in case.

**Comment by bluefuton** [comment]
@donalirl thanks for the report. The keyboard shortcuts navigate to the previous or next page when using `j` or `k`, so entering those letters in a comment input led the browser to try and navigate pages (hence the popup warning). Pressing the letter `l` could also accidentally like the post.

**Comment by tyxla** [comment]
Thanks everyone for the reports, and for reverting the offending commit. I'll make sure to test thoroughly with comments 👍

**Comment by tyxla** [comment]
I've opened a take 2 of this in #61112.
