### ISSUE TITLE
Marketplace: Add WooCommerce Points and Rewards and WooCommerce Deposits

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61073]
- [x] Adding in `store_products`
- [x] Adding in `https://public-api.wordpress.com/wpcom/v2/marketplace/products` endpoint (`featured: false`)

Let's add them behind a feature flag, and smoke test them with a12s.

**Comment by gcsecsey** [comment]
In the WC.com repository, both plugins just have the woocommerce icon:
![woocommerce-icon](https://woocommerce.com/wp-content/uploads/woocommerce_uploads/2019/06/WooCommerce-icon-160x160-1-3o68ab.jpg)

@SaxonF similarly to the [convo on previous Woo extensions](https://github.com/Automattic/wp-calypso/issues/57751#issuecomment-971195970), could you please provide temporary icons we can use in the marketplace?

**Comment by gcsecsey** [comment]
@cpapazoglou what should be the prices of the yearly and monthly products?

**Comment by cpapazoglou** [comment]
> @cpapazoglou what should be the prices of the yearly and monthly products?

Prices can be found in the spreadsheet of next woo extensions (Pdh6GB-2Y-p2)

**Comment by gcsecsey** [comment]
@SaxonF could you please help with the icons for these products? According to Figma (SVrZV9r5Hzb0bW2YHpDWgX-fi-2%3A3) and [this gsheet](https://docs.google.com/spreadsheets/d/1IP-lsojFX2F3bM1lltT4Ag3pJR4s4LcruQjNc3k8FkY/edit#gid=0&range=B58), should we proceed with using the Woo logo?

**Comment by gcsecsey** [comment]
Diffs for this issue:
- Adding the category product -> `store_products` mappings: D75174-code
- Adding the products to the marketplace endpoint (behind `is_automattician` flag): D75357-code

**Comment by cpapazoglou** [comment]
This should be closed now, right @gcsecsey? 

I have tested buying both and they got installed as expected. I would suggest:
- marking them as featured so that they appear in the "Browse All" page
![CleanShot 2022-03-02 at 13 25 50](https://user-images.githubusercontent.com/12430020/156353049-71b5c5af-e474-42a1-a6d7-5f5cd4e2f3ad.gif)
- removing the a11n check and launching them

**Comment by gcsecsey** [comment]
Yep, I think we can close this issue now.

Thanks for testing the changes 🎉  I'll add a new issue to track launching these plugins.
