### ISSUE TITLE
FSE: The Navigation Block in Header section doesn't autoupdate the changes made to Menu in the Customiser

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#61072]
### Quick summary

If you select one of your already created Menus (under Customiser) to be added to the Header section of FSE Header ->Navigation section, you will notice that this section doesn't update automatically when you make any changes to the Menu under Customiser. 

<img width="892" alt="Screenshot 2022-02-14 at 8 19 41 AM" src="https://user-images.githubusercontent.com/16509219/153871842-4f5f6b69-af58-4537-b406-2aacb163d2e0.png">

The Pages are deleted here ^

<img width="918" alt="Screenshot 2022-02-14 at 8 21 37 AM" src="https://user-images.githubusercontent.com/16509219/153871974-c161e20c-25d4-49c6-aa48-9976b18c8809.png">

But they continue to show here in the Template ^

<img width="948" alt="Screenshot 2022-02-14 at 8 22 15 AM" src="https://user-images.githubusercontent.com/16509219/153872094-aa41e21d-92ee-48b7-9d1a-029a645be64f.png">

It's updated on the Live site though as expected for the Deleted pages but did not update to show the new Page (Shop) that I added to the Menu under Customiser.

### Steps to reproduce

1 - Go to Appearance ->Customise ->Menus and create a Menu for your site and save it.
2 - Go to your FSE Template. In the Header section, add the Navigation block and select the Menu you created in Step 1 above.
3 - Go to your Menu under Customiser -> add one more Page -> Save Changes.
4 - Go to Pages ->All Pages section and Trash some of the Page that you might have added to your Menu in Step 1.

### What you expected to happen

I expected the Menu items in the Template header section to be updated based on the changes I was making to the Menu under Customiser because it was the same Menu that I called in the Template Header section.

### What actually happened

The Template Header section kept showing the same Menu items and did not update. However, it updated on the Live Site though. So, that bit worked as expected.

### Context

This leads to confusion for the users because they wonder why the Menu items they see in the Template Header section don't show it on the Live site.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No, this is FSE core functionality I believe.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

The users can create their own Menu in the Template instead of using the one they created under Customiser.

**Comment by nerdysandy** [comment]
Reported on # 4771586-zen

**Comment by edequalsawesome** [comment]
Issue is part of the core Gutenberg plugin -- reported here: https://github.com/WordPress/gutenberg/issues/39175

**Comment by Greatdane** [comment]
Closing as per https://github.com/WordPress/gutenberg/issues/39175
