### ISSUE TITLE
Atomic: Backfill Persistent Data for existing WoA sites

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#61086]
Create a script to add purchase information to Persistent Data for existing sites. See pdG1ka-17-p2#comment-19

There is an existing script that we might be able to build on, see `atomic_set_persistent_plan_data()` in Opengrok.

**Comment by mmtr** [comment]
D75072-code

**Comment by mmtr** [comment]
As noted in p1645540400624339/1645539860.904549-slack-C02ECE3ML, it's recommended to use an async job to run a backfill task, so I created D75452-code to move the script added in D75072-code to an async job.

**Comment by mmtr** [comment]
D75452-code has landed, and the backfill script is running now. We expect it to finish in a few hours.

More info: p1645693769406369-slack-C02V49GM0PN

**Comment by obenland** [comment]
Backfill is complete (p1645728008228899-slack-C02V49GM0PN)
