### ISSUE TITLE
Seller experience: Updated content and translations are needed.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61082]
Originally reported in https://github.com/Automattic/wp-calypso/issues/61026 by @SaxonF , let's change secondary text of the "Set up your store" step from "Let's create a website that suits your needs" to "Let's make sure you have everything you need to sell online".

<img width="1337" alt="Screen Shot 2022-02-14 at 10 06 30 AM" src="https://user-images.githubusercontent.com/349751/153921304-5aec1f82-b2fa-4623-ab78-c03862db19cd.png">

**Comment by kwight** [comment]
This first needs to be added to the preemptive translations file and then once that's been translated, we can do the proper PR to update it for production.

**Comment by blackjackkent** [comment]
Preemptive translation PR open at #61129 - will open another PR to change this text in the flow as soon as that's been merged and translated.

**Comment by andres-blanco** [comment]
I guess then that https://github.com/Automattic/wp-calypso/issues/61023 should be postponed?

**Comment by kwight** [comment]
> I guess then that https://github.com/Automattic/wp-calypso/issues/61023 should be postponed?

Yes, and in fact, I'll just remove the issue entirely – we know we have a second iteration coming up soon, so we can just keep the file and replace it with fresh strings when @SaxonF posts his designs for v2.
