### ISSUE TITLE
File Block: Opening editor with File block causes its file ID to get updated automatically

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#61104]
### Quick summary

When you open a post or a page that contains a File block, it causes its file ID to get updated automatically. This triggers Update button to get activated automatically without the user making any edits on the page.

If the post or page does not contain File block, that does not happen. I was able to reproduce this behavior on both Simple and Atomic site.

### Steps to reproduce

1. Create a post or page.
2. Add File block and add a PDF or another document to it.
3. Publish it.
4. Close the editor and open the same post or page editor.
5. You will notice that Update button is enabled despite not making any changes.

If you Update it and check the revision history, it shows that the file ID got updated.

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/33957570/154019752-44a979e0-8ab1-4467-a56d-2dee31b75358.png">

### What you expected to happen

Opening an editor with existing File block should not be changing its ID and trigger the Update button.an 

### What actually happened

  The File block ID was automatically updated and it enabled the Update button.

### Context

User report: 4775880-zen

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

No

### Reproducibility

Consistent

### Available workarounds?

No but the platform is still usable

**Comment by devNigel** [comment]
I can confirm it is happening on self-hosted WordPress sites as well.

**Comment by Greatdane** [comment]
Confirmed on AT, Simple and Core. 

@devNigel - are you able to add an issue on Gutenberg core as well please;
https://github.com/WordPress/gutenberg/issues

**Comment by devNigel** [comment]
Reported here: https://github.com/WordPress/gutenberg/issues/39154

**Comment by dpasque** [comment]
This issue is tracking an issue in another repository. All +1's of end-user reports should be done on this issue, while any discussion related to the issue itself and its fix should be done on the issue in the outside repository.

**Comment by yansern** [comment]
Issue is now fixed in Gutenberg 12.8. Tested and no longer seeing this issue.

**Comment by yansern** [comment]
https://github.com/WordPress/gutenberg/pull/39088
