### ISSUE TITLE
Contact Form does not render on FSE when home page is set to last blog post.

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#61103]
### Quick summary

User placed a Contact Form on the Index Template page with FSE. In Editor, the contact form renders as expected. On the live site, it only shows short code.

The user did not set the home page correctly. It was set to last blogs posts, which they did not have any. The site still showed the Index Template but the contact form did not render. When I created a new template with the same content as the Index template, including the contact form, and set it as home page, the contact form rendered correctly.

Also, interesting that if a site's homepage is marked as "Your latest posts", the "Index" template loads the design of the homepage?

<img width="500" alt="slack-imgs com" src="https://user-images.githubusercontent.com/84539773/154007244-177687b9-6dc5-47b1-91a2-514f32a45a86.png">

### Steps to reproduce

Created an index Template.
Created Contact Form on Index Template.
In Customizer, Home Page setting is on "Last Blog Posts".
The site shows the Index Template as a home page.
Contact Form is not rendering.
Copying the Index Template content to a new Template.
Naming new Template Home Page.
Setting the new Template as Home Page in Customizer.
Contact form renders correctly.

### What you expected to happen

Contact form rendering even if the home page settings is wrong.

### What actually happened

Contact form did not render.

### Context

Slack: p1644395794117579-slack-C03TY6J1A
Ticket: 4762945-zd-woothemes , message from February 9th at 11:03

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Creating a new Template as a home page.

**Comment by katiebethbrown** [comment]
Related:
- https://github.com/Automattic/jetpack/issues/22749

**Comment by edequalsawesome** [comment]
This is the same issue in the Jetpack repo that Katie mentioned -- I dropped the ticket in as a comment there, and will close this in favor of that issue :)
