### ISSUE TITLE
FSE: update the messaging during FSE theme activation

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#61119]
This is what we currently show when someone switches to an FSE theme:

![screenshot-2022-02-11-at-15 50 13-1-edited](https://user-images.githubusercontent.com/1182160/154077998-ce3408bb-f512-4ad5-a93d-c13fc2e2d71b.png)

@poligilad-auto proposed that we add the following text here:

> This theme has full site editing. Now you can design everything on your site, from the header right down to the footer, using blocks.

You can check out the discussion in this thread for more context: paYE8P-1rO-p2

**Comment by poligilad-auto** [comment]
It can look something like this ([Figma file](p3jbtC4W1tDu7z5uhvtry5-fi-176%3A7746)):

<img width="337" alt="image" src="https://user-images.githubusercontent.com/83961704/154090552-d525fb83-2857-4bca-8b54-67315bab0e0a.png">
