### ISSUE TITLE
FSE: Show a modal informing the customers about FSE activation

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#61118]
As part of the FSE rollout, sites with Universal theme active will be automatically converted to FSE sites. This will introduce some changes that might not be immediately obvious, such as the addition of the Site Editor in the Appearance menu. In order to inform the users about the changes, we'd like to add a modal that will be displayed once they land on the My Home page.

Here are some additional requirements:
- I think we should show this only once. I'm curious if there are other opinions though.
- @poligilad-auto requested that we align the background color of the similar modal in Plugins to the designs proposed here.

![intoducing-full-site-editing](https://user-images.githubusercontent.com/1182160/154077335-80c29fb4-8fda-4bf5-9668-2200ede37c0b.png)

Check out the discussion in this thread for more context: paYE8P-1rO-p2
Figma with designs is available [here](https://www.figma.com/file/p3jbtC4W1tDu7z5uhvtry5/Help-%26-Guidance?node-id=156%3A3936).

**Comment by poligilad-auto** [comment]
This is the illustration, could you make it 170px wide please?

![Create a site](https://user-images.githubusercontent.com/83961704/154089863-84175520-9326-42a2-9821-9df749067874.svg)

**Comment by poligilad-auto** [comment]
@vindl can we momentarily pause on this? Gathering some extra feedback from the design perspective.

**Comment by zaguiini** [comment]
@poligilad-auto is this ready to be worked on?

**Comment by poligilad-auto** [comment]
@zaguiini there is a discussion on it here: paYE8P-1rO-p2
