### ISSUE TITLE
Triforce: SVG isn't full-width in Safari

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#6111]
![slack-imgs](https://cloud.githubusercontent.com/assets/2846578/16134724/d437d6d8-33ec-11e6-83fa-df293fc71adb.png)

I tried looking into how to fix it, but couldn't figure it out. I found a couple ideas though: 
- https://benfrain.com/attempting-to-fix-responsive-svgs-in-desktop-safari/
- http://www.scriptscoop2.com/t/70fd082d505c/html-responsive-svg-not-getting-full-width-in-safari.html
- http://stackoverflow.com/questions/16813829/responsive-inline-svg-content-of-svg-must-fill-parent-width

Originally reported by @meremagee

**Comment by MichaelArestad** [comment]
Add a `width: 100%` to `.design-type__choice svg` like this: 
![image](https://cloud.githubusercontent.com/assets/1123119/16424142/2bdab102-3d1c-11e6-87ce-94335a0d1531.png)
