### ISSUE TITLE
Widgets: No effect when changing images' settings

### ISSUE THREAD

**Issue by burgerberg** [Automattic/wp-calypso#61139]
### Quick summary

Changing settings of an Image block in the widget editor won't have any effect.

### Steps to reproduce

1. Go to _Appearence → Widgets_ and add an image to a widget area.
2. Click the settings icon (gear) to open the image block's settings.
3. Change the image's style, size, and/or dimension.
4. Save changes 
5. Check the front end result.

### What you expected to happen

The style, size, and/or dimension of the image in the front end should reflect the block's settings.

### What actually happened

The front end shows the image under the default settings.

### Context

Issue came up on this ticket: 4648308-zd-woothemes

### Reproducibility

Consistent

**Comment by Greatdane** [comment]
@burgerberg Could it be related to a particular theme? I added an image and was able to change the style and size on an example theme - Apostrophe 2

**Comment by Robertght** [comment]
I cannot replicate this. Closing.
