### ISSUE TITLE
Plugins: Jetpack notice banner margins

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61142]
Jetpack notices need spacing

- View the plugin screen with a Jetpack (non atomic) site, likely needs a free plan. [Jurassic.ninja](https://jurassic.ninja/) sites work.

![Screenshot 2022-02-16 at 15-23-36 Plugins ‹ test — WordPress com](https://user-images.githubusercontent.com/811776/154195867-a1c411a4-6be8-4113-bf8d-b740ff9ae392.png)

Should match our other notices:
![Screenshot 2022-02-16 at 16-38-22 Plugins ‹ test — WordPress com](https://user-images.githubusercontent.com/811776/154203104-5098aee9-ab9e-434c-a8ba-0fc6ca8ac53e.png)

**Comment by allilevine** [comment]
Closed via https://github.com/Automattic/wp-calypso/pull/61765
