### ISSUE TITLE
Plugins: Append .org data to .com responses and replace v1.2 endpoint usage with v2

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61147]
Plugin information is loaded using two different api endpoints, a "v1.2" and a "v2". The v2 endpoint is being used (was created for?) paid marketplace plugins. The browser list code is fragmenting as a result.

I think we should consider moving all plugin data lookups to v2 and appending the extra information required (currently the v2 endpoint is missing a fair bit of extra field from v1.2 - not sure how much is used but I'm guessing some).

Context https://github.com/Automattic/wp-calypso/pull/61102/files#r807561348

Two api response examples to show the differences:
```
// v2
// name	"Yoast SEO"
// author	"<a href=\"https://yoast.com/\">Team Yoast</a>"
// rating	98
// icons	Object { 1x: "https://ps.w.org/wordpress-seo/assets/icon-128x128.png?rev=1550389", 2x: "https://ps.w.org/wordpress-seo/assets/icon-256x256.png?rev=1550389" }
// slug	"wordpress-seo"
// short_description	"Improve your WordPress SEO: Write better content and have a fully optimized WordPress site using the Yoast SEO plugin."

// v1.2
// name	"ChatBot Sessions"
// slug	"wpbot"
// version	"0.9.3"
// author	"<a href=\"https://www.quantumcloud.com/\">Quantumcloud</a>"
// author_profile	"https://profiles.wordpress.org/quantumcloud/"
// tested	"5.9"
// rating	0
// num_ratings	0
// support_threads	0
// support_threads_resolved	0
// active_installs	0
// last_updated	"2022-02-15 9:20am GMT"
// short_description	"WPBot records and display all the ChatBot sessions completed on the WPBot chatbot"
// download_link	"https://downloads.wordpress.org/plugin/wpbot.0.9.3.zip"
// icons	Object { default: "https://s.w.org/plugins/geopattern-icon/wpbot.svg" }
```

**Comment by lsl** [comment]
Added this via the explorers board but this might be something better for bespin to tackle.

**Comment by cpapazoglou** [comment]
The .org plugins results come from a different host `https://api.wordpress.org/plugins/info/1.2/` while marketplace plugins from `https://public-api.wordpress.com/wpcom/v2/marketplace/products`. 

Consolidating the two endpoints into one, would require proxying all the .org plugins through WPCOM. Since we have an outstanding issue for using:
(a) woocommerce.com api to get marketplace plugins(12392-gh-Automattic/woocommerce.com)
(b) [search / indexing engine](https://github.com/Automattic/wp-calypso/issues/59671)
we decided that didn't worth that effort. Bearing in mind that both of the above might need 1-2 months to be resolved, if you have any low effort solution in mind we can discuss it!

**Comment by lsl** [comment]
> we decided that didn't worth that effort. 

Definitely a valid call, code fragmentation is justifiable if we're ok with keeping the sources of truth separate.

My question is does that scale long term with say thousands of paid marketplace plugins?

How do we intend to serve search results?

I think we'd need to make secondary requests client side for any results in order to overlay prices.

We'd also be relying 100% on wordpress.org boosting / search configuration - something I don't think really works for us long term.

Low effort solution would be to proxy search queries through .com to do the price overlay and any other kind of plugin promotion in one easy to modify place.

A .com index of all .org plugins + .com price information overlaid during ingestion would be a longer term optimization to improve search result speed.

**Comment by cpapazoglou** [comment]
> My question is does that scale long term with say thousands of paid marketplace plugins?
> How do we intend to serve search results?

We already plan to tackle these by the mentioned pull requests: 12392-gh-Automattic/woocommerce.com and https://github.com/Automattic/wp-calypso/issues/59671

**Comment by allilevine** [comment]
> > My question is does that scale long term with say thousands of paid marketplace plugins?
> > How do we intend to serve search results?
> 
> We already plan to tackle these by the mentioned pull requests: 12392-gh-Automattic/woocommerce.com and #59671

@cpapazoglou I think we're missing some context here. 🤔 I understand how adding an indexing engine will help us with serving search results, but how is filtering for WCCOM plugins related to how we pull in .org plugin data?

**Comment by lsl** [comment]
I'm not sure about their plans but the .org plugin data could be added to the index along with the wpcom plugin data, merged at index build time. We could dump all that back out with the search results (well, maybe, depends what we're using for search I guess.)

**Comment by cpapazoglou** [comment]
The plan is to index all plugins (wporg & wpcom) in one engine and use this engine for all of our needs to retrieve plugin data in Calypso (search, plugins list, plugin details).

For context, here is a plan pdh6GB-gc-p2#comment-617 which will utilise Jetpack search. I will be having a call with Greg next week to unwrap this. I have invited you in case you wanna attend.

The priority in the Dotcom Marketplace is to move all paid plugins data to woocommerce.com and use the woocommerce.com api to retrieve them in Calypso. This will allow us to (1) use translations of plugins (that already exist in woocommerce.com) and (2) make the addition of a new plugin easier through WP Admin interfaces.

Then, we will want to index the paid plugins together with the wporg plugins. This will:
(1) allow us to mix paid with free results
(2) use only one unique endpoint in the frontend (will help with pagination in search results too)
(3) recommend plugins to users based on their needs

**Comment by lsl** [comment]
LGTM, sounds like a solid plan.

> I have invited you in case you wanna attend.

3.30 am my time but thanks for the invite! Looks like a few other explorers will be joining you.

**Comment by cpapazoglou** [comment]
Closing this as we are currently looking into using elastic search https://github.com/Automattic/wp-calypso/pull/62777
