### ISSUE TITLE
Import: post_modified date not imported

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#61145]
### Quick summary

When importing a WordPress XML export file, the `post_modified` and `post_modified_gmt` dates are rewritten to be the same as the `post_date` and `post_date_gmt`.

### Steps to reproduce

1. Make a modification to an existing post, so the last modified date is different from the publication date
2. Export the post. Check the XML file and make sure the `post_date` and `post_modified` date/timestamps are different
3. Import the post to another site
4. On the new site, either check the `post_modified` date via the REST API (we don't display it anywhere user-facing on WordPress.com), or create a new export of the post and compare dates in the XML file.

### What you expected to happen

For the `post_modified` date on the imported post to be the same as the exported post

### What actually happened

On the imported post, the `post_modified` date is the same as the `post_date`, even though the post was modified after that.

### Context

Made aware of this by a user in https://wordpress.com/forums/topic/post-modification-dates-not-imported/?view=all

Some discussion in p1644962138889439-slack-C01A60HCGUA

cc @vishnugopal 

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

n/a

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by vishnugopal** [comment]
This has been fixed in the mainline wordpress-importer 0.7.0

**Comment by vishnugopal** [comment]
[Backporting this fix](https://github.com/Automattic/wp-calypso/issues/62009) should be easy!

**Comment by zaerl** [comment]
@KokkieH see D77277-code

**Comment by KokkieH** [comment]
Apparently I don't have permission to view that diff :)

**Comment by zaerl** [comment]
@KokkieH it's ok. We wait for a review and then we can deploy.

**Comment by zaerl** [comment]
@KokkieH the review is ok, the fix is online.

**Comment by KokkieH** [comment]
Thank you! I've let the user know.

**Comment by EatonZ** [comment]
(this is the user👋)
Hi, it appears this did not fix the problem. Is there a staged rollout with your updates or should the fix be live now?

**Comment by zaerl** [comment]
Can you please try again? The land didn't work the first time and I didn't notice.

**Comment by EatonZ** [comment]
@zaerl Ah, it's working now. Thanks!

**Comment by zaerl** [comment]
👍
