### ISSUE TITLE
Breadcrumb styling should match domains pages

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61143]
Plugins, domains, and woo landing pages should should all use the same header component or at least match the look. cc @SaxonF 

Plugins page bold the root heading
![Screenshot 2022-02-16 at 13-40-21 WooCommerce Subscriptions Plugin ‹ c3po - Simple Site - Mapped — WordPress com](https://user-images.githubusercontent.com/811776/154195964-9d28aa5f-cef0-48d9-98ff-6d937173ef83.png)

Domains pages bold the current page heading
![Screenshot 2022-02-16 at 13-40-09 Domains ‹ c3po - Simple Site - Mapped — WordPress com](https://user-images.githubusercontent.com/811776/154195968-bd08f96c-d800-4e4f-a0e0-23287d6b5da8.png)

**Comment by lsl** [comment]
Might be able to fix both https://github.com/Automattic/wp-calypso/issues/61143 and https://github.com/Automattic/wp-calypso/issues/61218 with one PR to use a single header component between the two pages.

**Comment by gcsecsey** [comment]
Currently, clicking a domain makes the breadcrumbs root smaller and hides the question mark icon:
![image](https://user-images.githubusercontent.com/11555574/156569495-afa2088f-f7e5-43e0-ba42-52705635ef25.png)
![image](https://user-images.githubusercontent.com/11555574/156569503-84c9fe11-ea5b-4643-ab63-c0c28819ad83.png)

@vinimotaa should we update this UX perhaps?

**Comment by SaxonF** [comment]
Could we update plugins to use the existing breadcrumb component used on domains as a first step? We can spin up a separate issue refining page headers / breadcrumbs after chatting with the wider design team.

**Comment by cpapazoglou** [comment]
> Could we update plugins to use the existing breadcrumb component used on domains as a first step? We can spin up a separate issue refining page headers / breadcrumbs after chatting with the wider design team.

No, please don't that. 

https://github.com/Automattic/wp-calypso/blob/71b006c6d2df064bd638444add1e6b1136a46d6a/client/components/breadcrumb/index.tsx#L1-L77

Has been built in a more abstract way, is already in typescript, uses styled components, has a readme, an example and its already exposed in devdocs for further usage. What we should do, is updating this component to match the Domains one UI wise and then replace the Domains one with `/components/breadcrumb`.
