### ISSUE TITLE
[Bug]: Jetpack blocks showing up first in global styles panel

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#61150]
### Quick summary

Instead of the expected order, Jetpack blocks are showing up first in the Global styles panel:

<img src="https://user-images.githubusercontent.com/87168/154216226-50dbdee9-76ee-4061-b0f6-77d8a4f81034.png" width="300" />

Instead, the most important block should come first:

<img src="https://user-images.githubusercontent.com/87168/154216233-13d6b16c-7174-4bbd-bbda-e1d790ae7434.png" width="300" />

This might be caused by some special way we register or sort Jetpack block categories on .com.

Reported at Slack

### Steps to reproduce

1. In the site editor https://wordpress.com/site-editor/SITE_URL
2. Open global styles from the header
    <img src="https://user-images.githubusercontent.com/87168/154216398-a770897b-afb1-40f6-a4ff-1c468f449857.png" width="300" />
3. Pick "blocks"

### What you expected to happen

Important blocks (such as paragraph) first.

### What actually happened

Jetpack blocks are first.

### Reproducibility

Consistent

**Comment by yansern** [comment]
Preliminary investigation shows that Jetpack blocks are being registered first before core blocks, hence it is showing first on the global styles panel.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/1287077/155509482-1f6a0ae3-6c7f-46c0-80d1-a0696e3b5c25.png">
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/1287077/155509450-46fc1355-e566-488e-b256-9d340d5a1b7d.png">

@ivan-ottinger also discovered that only blocks with block supports declared in the block metadata shows up on the global styles list.;

**Comment by yansern** [comment]
To answer as to why only blocks with block supports show up, it's because of the additional filtering.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/1287077/155541941-84dc1c4c-007f-4f46-b276-b27f442f4228.png">

**Comment by yansern** [comment]
As for the fix, instead of using `getBlockTypes()`, use `getInserterItems()` instead.

`getInserterItems()` sorts by core and then non-core, which is used for the inserter panel on the left.

The fix should be done in Gutenberg core.

**Comment by yansern** [comment]
Using `getInserterItems()` work. After some cleanup, we'll create a PR at Gutenberg. cc @Automattic/apex 

<img width="336" alt="image" src="https://user-images.githubusercontent.com/1287077/155542815-4964a66c-1e43-4b47-86ce-6920d286ca3a.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1287077/155542827-5d491ca0-376c-41ed-821a-46212a991716.png">

**Comment by mashikag** [comment]
I created [the PR](https://github.com/WordPress/gutenberg/pull/39093) in WP/gutenberg but all the credit for the code change should go to @yansern 🏅

**Comment by mashikag** [comment]
[The PR](https://github.com/WordPress/gutenberg/pull/39093) addressing this issue was merged into [Wordpress/gutenberg](https://github.com/WordPress/gutenberg) trunk yesterday. 

The last released version of gutenberg right now is [12.7.0](https://github.com/WordPress/gutenberg/releases/tag/v12.7.0). I expect the fix to be included in the next release. The gutenberg releases can be previewed [here](https://github.com/WordPress/gutenberg/releases).
