### ISSUE TITLE
PW Spec Migration: Editor tracking

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#61166]
### Details

There remains on the old Selenium framework three specs related to testing event tracking in the editor:

- `wp-calypso-gutenberg-page-editor-tracking-spec.js`
- `wp-calypso-gutenberg-post-editor-tracking-spec.js`
- `wp-calypso-gutenberg-site-editor-tracking-spec.js`

We need to find a way to migrate these off Selenium. 

We should use this chance to evaluate the test strategy of event tracking, and see if we can't move some pieces of the testing down the pyramid. This might be hard as a lot of these events require the integrated WordPress.com environment.

**Comment by worldomonation** [comment]
@dpasque With your Editor Tracking project winding down, would you say these have been completed?

**Comment by dpasque** [comment]
@worldomonation yep! Thanks :) Closing as fixed!
