### ISSUE TITLE
PW Spec Migration: Migrate the Jetpack Scripts

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#61168]
### Details

Right now, there are a handful of specs on the Selenium framework in `specs-jetpack` that cover some jetpack integration on WordPress.com. We should understand the future of these specs and migrate them off of Selenium.

### Checklist

- [ ] Identify stakeholders for the tests
- [ ] Identify target end use case of these scripts
- [ ] Map desired coverage and create test plan map
- [ ] Work with stakeholders to make necessary migrations to Playwright.

**Comment by worldomonation** [comment]
Done - see pciE2j-NW-p2.
