### ISSUE TITLE
Full Site Editing: use `full-site-editing` tag for Core FSE in the theme showcase

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#61167]
### Details

Our Legacy FSE implementation is camped out on the `full-site-editing` tag from the theme showcase. It is used to preferentially show these themes to sites with Legacy FSE active. As the name implies, Legacy FSE is not under active development, and these sites will soon be migrated to Core FSE.

### Checklist

- [x] Assign `full-site-editing` tag to all Core FSE themes (that currently have the `block-templates` tag)
- [x] Remove the `full-site-editing` tag from Legacy FSE themes
- [x] Update Calypso to use the `full-site-editing` tag rather than `block-templates` 

After this point, sites with Legacy FSE active will be shown Core FSE themes in Recommended. Sites with Core FSE active will still be shown Core FSE themes, only now under the hood Calypso will be requesting the `full-site-editing` tag for the latter.

- [x] Remove the `block-templates` tag from Core FSE themes

We will wait a bit on this last task as the change is communicated internally.

**Comment by zdenys** [comment]
I've asked in p1645281008673749-slack-C029FM1EH if they can update this public-facing page: P2gHKz-nDl-p2 to include the above change. I'm not sure if that falls under your tasks though, so I thought I'd ping here just in case, @mattwiebe.
