### ISSUE TITLE
FSE: deprecate all classic themes

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#61205]
As part of the FSE rollout, consider deprecating all classic themes so that it's possible to switch only to an FSE theme. We should have a discussion and decision re-evaluated with stakeholders and the Themes team when we are ready to start working on this. It depends on how good we feel about our FSE theme selection at that point in time.

**Comment by Addison-Stavlo** [comment]
cc @simison - We don't think this necessarily makes sense anymore, but any other thoughts regarding this?
