### ISSUE TITLE
CPT: Reconcile last page / found posts with user capabilities

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#6120]
When receiving a post counts response from the REST API, counts for statuses on the `all` property do not consider whether the requesting user has capabilities for editing those posts. This is arguably the correct behavior, but might be misleading when used in the context of post counts on status tabs in Calypso. This is true for [the existing posts screen](https://wordpress.com/post), where as a contributor I could see "50" draft posts, and when clicking the draft status, I'm presented with a "No drafts found" warning.

The bigger issue, however, is the lack of accurate `found` on the posts response when drafts cannot be edited. Note in the following request made in the [developer site console](https://developer.wordpress.com/docs/api/console/) that an empty posts array is returned, despite providing a `found` of `36`:

![image](https://cloud.githubusercontent.com/assets/1779930/16152771/576e2370-3471-11e6-9c00-98e3ae0a871f.png)

Posts are not included in the response because, as a contributor where all drafts on this site were authored by an administrator, [I do not have access to edit these posts](https://github.com/Automattic/jetpack/blob/f29523daa3f6b5bb7768aa9b89653ade52f44b15/json-endpoints/class.wpcom-json-api-post-endpoint.php#L158-L163) (note `context` in request). The implementation of the posts listing endpoint _should_ be accounting for this already, [decrementing these posts from the returned `found` count](https://github.com/Automattic/jetpack/blob/f29523daa3f6b5bb7768aa9b89653ade52f44b15/json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php#L283).

I'm not sure yet whether this is an issue of the REST API, or if we need to handle this better in Calypso, but because [the `getSitePostsLastPageForQuery` selector](https://github.com/Automattic/wp-calypso/blob/576ae10deb8f63522a6bb92a8d80169a18b082cb/client/state/posts/selectors.js#L104-L119) is driven by the found count associated with a query ([see `PaginatedQueryManager#getNumberOfPages`](https://github.com/Automattic/wp-calypso/blob/576ae10deb8f63522a6bb92a8d80169a18b082cb/client/lib/query-manager/paginated/index.js#L89-L104)), the [custom post types listing screen](https://wpcalypso.wordpress.com/types/post) is rendering under the assumption that this contributor should expect to receive multiple pages of data.

Ref: 279-gh-io cc @codebykat

**Comment by aduth** [comment]
Scenario where this had an undesirable effect: https://github.com/Automattic/wp-calypso/pull/5995#issuecomment-226778131

**Comment by aduth** [comment]
Found count discrepancies resolved as of #6556 . Remaining issue is that filter tab counts don't consider user capabilities. Not an easy problem to solve.

**Comment by lancewillett** [comment]
@aduth Have you had a chance to consider the user capabilities challenge? Should we close this and revisit in the future?

**Comment by aduth** [comment]
No, I've not. I'm fine to close for now.
