### ISSUE TITLE
Marketplace: Installing Yoast Premium on a site with no custom domain works

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#61209]
### Quick summary

For a site with no custom domain when I try to purchase Yoast Premium plugin, and click on `Install Yoast Premium` button only adds the Yoast Premium to the cart. 

Uploading Screen Capture on 2022-02-17 at 18-46-21.mp4…

### Steps to reproduce

1. Go to My Site → Plugins → Add New
2. Search for Yoast Premium
3. Click on the Purchase and Activate button 
4. Takes to a dialogue box where click on the `Install Yoast Premium` button. 

### What you expected to happen

The `Install Yoast Premium` button is to be inactive until a custom domain is added to the site.

### What actually happened

It allowed to add Yoast Premium to the cart.

### Simple, Atomic or both?

Atomic

**Comment by Greatdane** [comment]
@galakhyati can't see your screenshot, but according to this thread; pdtkmj-4i-p2 this looks to be intended, we should see this dialogue

![wordpress com_plugins_wordpress-seo-premium_theexperiencestoretestdomain blog_](https://user-images.githubusercontent.com/5075840/155461951-c0a38373-5d61-4b21-9b61-5ce197ac7c9f.png)

Are you seeing something or referring to something different?

**Comment by galakhyati** [comment]
https://user-images.githubusercontent.com/7382505/164006098-b8c2bac8-8038-497f-aa02-e032eaaf9e83.mp4

Here is my screencast video.

**Comment by cpapazoglou** [comment]
> @galakhyati can't see your screenshot, but according to this thread; pdtkmj-4i-p2 this looks to be intended, we should see this dialogue
> 
> ![wordpress com_plugins_wordpress-seo-premium_theexperiencestoretestdomain blog_](https://user-images.githubusercontent.com/5075840/155461951-c0a38373-5d61-4b21-9b61-5ce197ac7c9f.png)
> 
> Are you seeing something or referring to something different?

Indeed, that is the expected experience. Instead of forcing the user to bundle a domain we now try to educate them about the value of the custom domain. Closing now, please reopen if that's not the case.
