### ISSUE TITLE
Seller experience: Investigate adding a new PayPal block that is just the button.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61217]
Our existing PayPal block isn't just the required transaction button, but the entire layout (and having been built before blocks were really composable in patterns, the layout is not modifiable). While work is planned down the road to deconstruct the existing block, let's investigate creating a new Gutenberg block that is just the button, so that it could be used in composable patterns for commerce. Consider this a spike on what a "PayPal MVP button" would be.

cc/ @SaxonF

**Comment by sixhours** [comment]
Closing since this is well out of date. We may consider doing this or something similar as part of the new Bazaar efforts, in which case we'll create a new issue.
