### ISSUE TITLE
Signup: Site building notifications may have inconsistent styling.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61219]
While running through signup, @ianstewart noticed that we might have inconsistent styling in the site building process (maybe a different font size or shade of black).

<img width="1091" alt="Screen Shot 2022-02-17 at 2 16 02 PM" src="https://user-images.githubusercontent.com/349751/154580153-0ec1d529-ae70-45bd-be43-747484d748ab.png">

**Comment by valterlorran** [comment]
This flow has been changed several times, and I couldn't reproduce this on my tests.

<img width="743" alt="Screen Shot 2023-03-16 at 16 32 18" src="https://user-images.githubusercontent.com/1234758/225757418-f74d0a06-a721-4499-bb54-4d55c4ba5d45.png">
