### ISSUE TITLE
Marketplace: add FedEx Shipping Method and WooCommerce One Page Checkout

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61249]
- [x] Adding in `store_products`. Prices can be found in the spreadsheet of next woo extensions (Pdh6GB-2Y-p2)
- [x] Adding in `https://public-api.wordpress.com/wpcom/v2/marketplace/products` endpoint (`featured: false`)

We will need plugin icons from the design team.

@emmnyc85 can we add tags for each a8c plugin in the google sheet?

Documentation: PCYsg-AhH-p2

**Comment by cpapazoglou** [comment]
@SaxonF can we generate icons for all upcoming woo extensions?

**Comment by gcsecsey** [comment]
The FedEx shipping method may not need a new icon as it's already distinct from the rest of the WC extensions. In the WCCOM response it has the FedEx logo as an icon:
![fedex logo](https://woocommerce.com/wp-content/uploads/woocommerce_uploads/2013/01/woo-FedEx-auxjb7.png)

**Comment by SaxonF** [comment]
Some discussion here around using a generic Woo icon for Woo related plugins that don't have an icon C029JEQRVRT/p1646709488402109
![woo-icon](https://user-images.githubusercontent.com/1072756/157172615-d1c0e68b-87de-4cd2-a183-836a51d80e97.png)

Makes sense to use the Fedex icon @gcsecsey mentioned above for Fedex Shipping

**Comment by WBerredo** [comment]
Adding in store_products. Prices can be found in the spreadsheet of next woo extensions (Pdh6GB-2Y-p2)

WP.com change: D76245-code
Deployed: r241307-wpcom

**Comment by WBerredo** [comment]
Adding in https://public-api.wordpress.com/wpcom/v2/marketplace/products endpoint (featured: false)

WP.com diff: D76274-code
Deployed: r241398-wpcom

**Comment by cpapazoglou** [comment]
Let's test that buying each variation of these Plugins work as expected (plugin gets installed in the site) and then launch them by removing the `a12n` check and turning `is_featured` to `true`.

**Comment by WBerredo** [comment]
Fix of FedEx Shipping Method plugin: D76511-code
