### ISSUE TITLE
Playwright: Replace config with env vars, only encrypt secrets and accounts

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#61258]
### Details

Right now, the configuration set up for E2E testing is a bit confusing for a couple reasons...
1. It is split between ENV variables and config files
2. The config files often confuse people in how they work together and how to combine them to get the desired configuration
3. The config files are full of unused, undocumented properties
4. We have to do semi-gross things in the TeamCity scripts like setting ENV vars to JSON text.

Looking at the current state of Playwright, I see an opportunity to simplify and streamline this significantly!

1. All "configuration" (as in variables that may change between different runs and environments) should be in ENV variables. Right now, the only one we have to move over is the Calypso base URL! 
2. We have one encrypted file that has test account details and any other needed secrets.
3. We ditch the `config` npm package, the idea of multiple configs, and having to set the `NODE_CONFIG_ENV` variable. Instead, the `decryptconfig` script should always just output to the same, fixed, gitignored JSON file. 
4. We can now add typing for that JSON file in our code too!

**Comment by worldomonation** [comment]
If we ditch `config`, it would likely affect how `DataHelper` obtains values from the decrypted and public configuration files. Would there be a safe-ish replacement for it?

**Comment by dpasque** [comment]
> If we ditch config, it would likely affect how DataHelper obtains values from the decrypted and public configuration files. Would there be a safe-ish replacement for it?

Yeah, for sure!

So in this case, we would only be left with one decrypted file (as there's no public configuration anymore).

What I would recommend we do is create a typing to reflect the structure of that decrypted JSON file, and a file/module to wrap fetching those values from configuration. We could also include some existence and type checking on startup like we do with our ENV variables!
