### ISSUE TITLE
Move spotlight component into Paid list

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#61264]
https://github.com/Automattic/wp-calypso/pull/61185#discussion_r809622650

@SaxonF: Are we able to move this under the "paid" list? (previously called featured).

Not so sure about the difference between the "Premium" and "Paid" lists

**Comment by SaxonF** [comment]
@Rolilink i believe they are the same :D I think it's "paid" in code and Premium as the title

**Comment by Rolilink** [comment]
Oh I was confusing "Premium" and "Featured" nvm that is quickly addressable! gonna close this one
