### ISSUE TITLE
Add tracking events to the Spotlight component

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#61266]
https://github.com/Automattic/wp-calypso/pull/61185#discussion_r810112392

Since we are creating this new shiny component, I think it would worth also adding some track events for users who have clicked through it. This way we can measure the performance (click through rate) and run A/B tests later.

An example can be found here
https://github.com/Automattic/wp-calypso/blob/0178a4ae1aa2031071dc846cfc0344b353fd233e/client/blocks/announcement-modal/index.jsx#L52-L56

**Comment by allilevine** [comment]
We specifically want to track click-through rate here, so clicks on the CTA.
