### ISSUE TITLE
Calypso Media Library (Simple sites only): Unable to edit images, "We were unable to process this media item"

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/wp-calypso#61297]
### Quick summary

On a simple site, using Spearhead theme and trying to edit an image results an error saying `We were unable to process this media item`. The error occurs while editing the image within a post as well as directly in the Media library. I was able to duplicate this issue on a test site as well. Upon checking the browser inspector I'm seeing Console errors.

![image1](https://user-images.githubusercontent.com/15944096/156146175-f94276d0-7c95-4e66-ade3-189a92a959a8.jpg)

https://user-images.githubusercontent.com/49064126/154827132-28c97af3-e020-4d3f-8e5c-8ac81628cc1c.mp4

On AT sites the images do get edited fine as expected.

### Steps to reproduce

Create a page/post, insert an image block, try to crop it before inserting or try cropping the image directly from Media library.

### What you expected to happen

The image should have gotten cropped.

### What actually happened

The image didn't get cropped and an error saying `We were unable to process this media item` appears.

### Context

#4790446-zd

### Simple, Atomic or both?

Simple

### Theme-specific issue?

The issue occurs with this theme on Simple sites and not on AT sites.

### Browser, operating system and other notes

Google Chrome Version 98.0.4758.102 (Official Build) (x86_64)
Mac OS Monterey Version 12.1

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes.

### Workaround details

Switch to Classic View, [see guide](https://wordpress.com/support/dashboard/), and edit from WP Admin.

**Comment by paxblueribbon** [comment]
hc33978495 seeing this with the Apostrophe 2 theme as well.

**Comment by carinapilar** [comment]
This doesn't seem to be specific to a theme, I was able to replicate with Quadrat and Hemingway Rewritten, from the Media Library on Calypso. The workaround is to edit the image through WP-Admin.

Got a report on 4794495-zd-woothemes

**Comment by csabarakasz** [comment]
Same thing here: 4797233-zd-woothemes

Suggested WP-Admin workaround for now!

**Comment by burgerberg** [comment]
Another one came up here: 4793362-zd-woothemes

I could reproduce the issue with another site as well. 
WP-Admin workaround works fine.

**Comment by arinoch** [comment]
User in 4797233-zd-woothemes would like updated when the issue is fixed. workaround will do in the meantime.

**Comment by inaikem** [comment]
User in 34356631-HC would also like a follow up once resolved via 4808129-ZD. Thanks!

**Comment by KokkieH** [comment]
Three more reports in https://wordpress.com/forums/topic/we-were-unable-to-process-this-media-item/?view=all

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/modify-a-media/?view=all

**Comment by Agepeuve** [comment]
Another report in https://wordpress.com/es/forums/topic/fotos-19/

**Comment by druesome** [comment]
Another report: 4817551-zen

As a workaround, you can ask the user to visit the Classic view of their Media Library and edit the images from there.

**Comment by jordesign** [comment]
Another instance of this with the Colinear theme.
34431772-hc

**Comment by formosattic** [comment]
Updated initial report with the workaround to edit via WP Admin/Classic view.

Strangely, I'm unable to reproduce this because the **Edit Image** option is missing.

Has something changed in between or is this a new issue? 
I'll let @Automattic/dotcom-triage-pa-group take another look.

Expected:
![image1](https://user-images.githubusercontent.com/15944096/156148697-d6e94235-73d9-433c-b24e-6937219baa78.png)

What happened:


https://user-images.githubusercontent.com/15944096/156149354-60cdcfb3-bffc-40a2-bff7-f56932a49dac.mov

**Comment by carinapilar** [comment]
> I'm unable to reproduce this because the Edit Image option is missing.

I bumped into that too, @formosattic, I'm not sure I understand why, but the Edit Image option only shows on the Media Library if the site is set as Public.

**Comment by kerrynicl** [comment]
I'm not able to reproduce the error. I'm able to crop the image in a post but unable to edit from the Calypso media library. However it is possible to apparently edit image in the library only when the site is public... 
 
Current Status - Unable to Edit Image in Calypso Media Library when site is Private

**Comment by KokkieH** [comment]
@formosattic  @carinapilar  The Edit Image option hasn't been available if a site is set to private for quite some time. See #25115

@kerrynicl The users who have been reporting the issue here have public sites, so it's unlikely to be the same issue.

**Comment by kerrynicl** [comment]
@KokkieH  Thanks for pointing that out. Are you able to replicate this on your side? We're not able to see that error - "We were unable to process this media item"

**Comment by KokkieH** [comment]
@kerrynicl I can replicate, yes.

![Screen Capture on 2022-03-01 at 17-59-31](https://user-images.githubusercontent.com/11873759/156203511-8606849b-5c2c-4ec8-93e4-561fb6c05998.gif)

I see this on public sites in both my a11n account and a different test account.

**Comment by KokkieH** [comment]
Console shows the following:
<img width="1040" alt="Media_‹_Shift_to_the_left_—_WordPress_com" src="https://user-images.githubusercontent.com/11873759/156203945-aa3b5e81-f7c2-4abd-95db-ec855a5e25c9.png">

**Comment by csonnek** [comment]
Another report in https://wordpress.com/forums/topic/edit-function-3/?view=all

**Comment by MaxPhilip** [comment]
Another report in 4823076-ZD

**Comment by syedshaon** [comment]
Another Repost zd#4836780 Baskerville 2  theme.

**Comment by formosattic** [comment]
+1 4837217-zd-woothemes

**Comment by sharonlaker19** [comment]
4836097-zen would like an update when the bug is fixed, we've already shared the workaround with them. Thanks!

**Comment by fetenlakhal** [comment]
4836766-zen. The rounded image is a square in the live website

**Comment by fetenlakhal** [comment]
4848101-zen Stow theme

**Comment by jp-imagines** [comment]
Another in `4847570-zd-woothemes`

Also closed duplicate issue #5605 with these reports:
4816961-zd-woothemes
4817151-zd-woothemes

**Comment by formosattic** [comment]
4853483-zd-woothemes

**Comment by sharonlaker19** [comment]
Another one at 25860813-hc

**Comment by janmckell** [comment]
4850011-Zen

**Comment by vykes-mac** [comment]
I have tested this issue with themes TT2, Apostrophe 2 and Spearhead following the steps provided 
by @mriyazuddin and was not able to reproduced it. 

I'm going to close this issue but it can be reopened if anyone is still facing the issue.

Please provide detail testing instructions and a possible test site if this issue continues to occur.

**Comment by essleeung** [comment]
Another encounter [here](5655314-zd-woothemes) on the Modern theme. 
I provided the workaround to use the Classic View.

**Comment by sourourn** [comment]
Another encounter in #37578457-hc on the Alves theme.
I provided the workaround to use the Classic View.

**Comment by carinapilar** [comment]
The new reports might not be the same issue?

I got a report today, but it's not showing the same error message (or errors on Console). So I created a new GH report here: https://github.com/Automattic/wp-calypso/issues/69441

**Comment by vykes-mac** [comment]
closing issue as resolved in relation to #69441 , feel free to reopen if issue continues.
