### ISSUE TITLE
Editor: Exception when going back to listing from Editor

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#6131]
Originally reported [here](https://github.com/Automattic/wp-calypso/pull/5995#issuecomment-225951608) and experienced while reviewing #5995

#### Steps to reproduce
1. View CPT listing page
2. Click Add in the sidebar for that post type
3. Add a title, some content, wait for autosave to trigger
4. Click back button at the top of the editor sidebar

Periodically then the following error is thrown:

<img width="1243" alt="testimonials_ _testingtimmy2_wordpress_com_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/22080/16052231/243141a0-3218-11e6-9d67-1feece58735c.png">

the line it is failing on

<img width="586" alt="testimonials_ _testingtimmy2_wordpress_com_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/22080/16052250/37300138-3218-11e6-89a6-fd0191ec8fd7.png">

#### Browser / OS version
Mac / Chrome

**Comment by timmyc** [comment]
`saveRawContent` is called via `debouncedSaveRawContent` throughout the `post-editor.jsx`, but there is one spot where it is called directly in `autosave`.  Like most elusive bugs, anytime I _try_ to get this to break it will not.  But the one time I was able to re-create it was an autosave event that triggered after the component was no longer mounted.  So it seems event though we call `this.debouncedAutosave.cancel();` in `componentWillUnmount` there can at times be instances where this still does execute.

**Comment by aduth** [comment]
Is this specific to custom post types? Or should we change label to Editor?

**Comment by timmyc** [comment]
Correct I have seen this in just the editor - changed the labels.

**Comment by lancewillett** [comment]
I tried to repeat this today using the above steps in wpcalypso with Testimonials and Portfolio CPTs, and couldn't get the errors to show up in the Chrome dev tools JS console.

Feel free to re-open if you see it again.
