### ISSUE TITLE
Prevent yost premium WPCOM plugin network call for non a11n

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#61323]
https://github.com/Automattic/wp-calypso/pull/61185#discussion_r810721196

**Comment by allilevine** [comment]
We are seeing a warning that is displayed when a non automattician calls an http endpoint.
We need to find a way to not execute that http call, possibly with a feature flag. We'll need to modify the `useWPCOMPlugin` hook. Timebox an investigation.

**Comment by Rolilink** [comment]
Seems like we can use [Dependant Queries](https://react-query.tanstack.com/guides/dependent-queries) to address this one!
