### ISSUE TITLE
Atomic Activity Log / Themes: Hide Activity Log theme update notices for managed themes

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#61331]
### What

Hide update notifications in the Jetpack Activity Log for managed symlinked themes on WordPress.com Atomic sites.

WPCOM Atomic already hides these notifications on the individual theme management (`/wp-admin/themes.php?theme=twentyseventeen`) and updates (`/wp-admin/update-core.php`) pages.

However, the Activity Log will continue to log update notices when a version change is detected.

### Why

Some of the managed/symlinked themes on WPCOM are the same as, or share the slug of, WordPress.org repo themes. 

In some cases, the repo version of the theme will receive a new version which then leads to update notifications in the Activity Log.  The user will not be able to update the theme as it is managed by the platform. 

HEs confused by the issue might attempt to update it via CLI but this will fail as it is symlinked. 

A current example of this is Twenty Seventeen.  By installing the WordPress.com version on a WPCOM Atomic site, a user will begin to receive `Theme update available` notices in the Activity Log.

![Screen Shot on 2022-02-21 at 11:40:26](https://user-images.githubusercontent.com/4887830/154996403-d8fa8bf9-0b8f-4db0-b0a8-dc94da706eed.png)

A recent internal example: p1645460941311929-slack-C03TY6J1A

### How

Filter out `Theme update available` items in the Activity Log for managed/symlinked themes on WPCOM Atomic.

**Comment by vykes-mac** [comment]
Code fix done here D81524-code
