### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61343]
This plugin 404's, guessing due to the name somehow.

https://wordpress.org/plugins/hide-wp-admin-wp-login-php/

![Screenshot 2022-02-22 at 07-55-11 Plugin — WordPress com](https://user-images.githubusercontent.com/811776/155025217-98106d5f-e646-4dc3-bdd5-c34070a23189.png)

This issue should track fixing the plugin loading, I've created a separate issue to add a 404 page. https://github.com/Automattic/wp-calypso/issues/61342

**Comment by cpapazoglou** [comment]
That's interesting, the request Calypso fires (and gets 404) is 
```
https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request%5Bslug%5D=hide-wp-admin-wp-login&request%5Blocale%5D=en_US&request%5Bfields%5D=icons%2Cshort_description%2Ccontributors%2C-added%2C-donate_link%2C-homepage
```

it has removed the `php` suffix from the slug. `hide-wp-admin-wp-login` instead of `hide-wp-admin-wp-login-php`.

**Comment by WBerredo** [comment]
WPcom: D75879-code
Calypso: #61580

**Comment by WBerredo** [comment]
WPCom deployed: r241084-wpcom
