### ISSUE TITLE
Add 1040 maxwidth to woo landing page footer section

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61345]
The footer section should match the max-width with our other pages. This will also align with the header text at the top of the page.

![Screenshot(69)](https://user-images.githubusercontent.com/811776/155025758-dab20e83-4799-4f77-b2a5-d38e15eada82.png)

- [ ] Add 1040 maxwidth to woo landing page footer section

p1645441249043699/1643696370.245229-slack-C02PMG4B19P

**Comment by allilevine** [comment]
Timebox to 30 minutes, might be a wider Calypso issue (not currently a component). Needs some dotcom systems thinking.

**Comment by lsl** [comment]
Had my wires crossed, the component thing I was thinking about was actually one: https://github.com/Automattic/wp-calypso/issues/61491 (though whatever comes of that was ideally going to be used here too)
