### ISSUE TITLE
[Bug]: locale switcher does not change page content

### ISSUE THREAD

**Issue by annemirasol** [Automattic/wp-calypso#61358]
### Quick summary

The locale switcher banner -- the one that says `Also available in English` or equivalent -- changes the URL but not the page content. I am guessing a reload is needed, but either it does not perform one or it fails while doing so.

### Steps to reproduce

1. While logged out (e.g. in a fresh incognito window), navigate to `https://wordpress.com/log-in/<locale>`, where `<locale>` is some locale different from your browser settings. e.g. https://wordpress.com/log-in/fr (French)
2. You should get the WordPress.com login page, in the locale chosen, with a switcher banner at the top of the form. If not, maybe try another locale.
3. Click the locale switcher.
4. Notice the page did not change.
5. If you check the URL, the locale slug got switched.

### What you expected to happen

I expected the page contents to update to my chosen language when I clicked the switcher.

### What actually happened

The URL got updated, but no reload happened, and no page change happened.

### Context

Discovered while accepting a user invite while logged out

### Browser

Google Chrome/Chromium, Apple Safari

### Simple/Atomic

Simple

### Other notes

This also applies to other paths where the locale switcher pops up, e.g. `https://wordpress.com/accept-invite/<blog-id>/<invite-key>/<locale>` (while logged out).

No browser console errors observed.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Since the URL is already correct, the user can manually load this to get the correctly translated page.

**Comment by sejas** [comment]
Reopening because we had to revert #63271 since it caused an infinite loop when accessing https://wordpress.com/log-in/en with unauthenticated users.
