### ISSUE TITLE
Sharing Buttons:  Disabling Like button also disables Reblog button

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#6136]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/sharing/buttons/
2. Deselect "Show like button" option
3. Leave "Show reblog button" option active
#### What I expected

Post to display Reblog button, but no like button
#### What happened instead

Neither button is visible
#### Screenshot / Video

https://cloudup.com/c6RGR5b7c90
#### Context / Source

Reported in 2705796-t

**Comment by RealCarFax** [comment]
I am also now running across this exact same issue with a user's site: https://musicenthusiast.net/2016/07/17/tres-songs-mini-set-2/

Enabling both Like and Reblog buttons will allow both to show. Only enabling the Reblog button shows neither.

**Comment by alexjgustafson** [comment]
Also reported in 2744396-t

**Comment by lancewillett** [comment]
This requires fixes on the REST API side of things (not in Calypso). Closing in favor of internal ticket 7550-wpcom.
