### ISSUE TITLE
Publicize: Disabling Sharing  Doesn't Work for Portfolio Projects

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#61377]
### Quick summary

When you disable _"Share when publishing"_ when publishing Portfolio Projects, it still shares through Publicize.

### Steps to reproduce

1. Connect Twitter to publicize, from Tools > Marketing
2. Start a new Portfolio Project
3. From Jetpack settings in the editor, disable the _"Share when publishing"_ option
4. Publish the Portfolio Project

### What you expected to happen

To not have the Portfolio Project shared on Twitter.

### What actually happened

It shares the Portfolio Project on Twitter, even if _"Share when publishing"_ is disabled. This doesn't happen with Posts, it seems to be working in there.

This is the option:

![SharingOption_1](https://user-images.githubusercontent.com/16104522/155200575-dbfc1fca-779b-45c7-9e5a-c094b00a0f82.jpg)

### Context

Reported on 34310097-hc

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

You need to disable the Twitter option too.

**Comment by kimerlin81** [comment]
Thanks @carinapilar! This issue has been triaged, and it seems to only be affecting Simple sites.

Notes: I was able to reproduce this behavior on a Simple test site today. The Portfolio posted to Twitter when I left the Twitter option enabled and toggled off "Share when publishing".
The workaround still applies.
Cannot replicate on an Atomic test site.

**Comment by zaguiini** [comment]
Related diff, fixing the issue: D81551-code
