### ISSUE TITLE
Customizer: Widgets panel not working on classic themes

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#61397]
### Quick summary

The widgets panel in the Customizer isn't working on any classic theme, including Varia and Seedlet child themes, and default themes up to Twenty Nineteen

### Steps to reproduce

1. Activate any theme in the showcase starting from Spearhead or older.
2. Go to Appearance ->Customize
3. Click on Widgets
4. if the theme supports multiple widget areas, select a specific widget area

### What you expected to happen

To see the block widgets interface in the Customizer sidebar, allowing you to add/edit widgets on the site.

### What actually happened

No widget editing interface loads. The panel just remains blank:
![2014, 2016](https://user-images.githubusercontent.com/11873759/155270965-b761d0b6-b9a9-44c4-9a6d-29b69ddf9d8c.png)

### Context

Reported in https://wordpress.com/forums/topic/widgets-in-primary-side-bar/?view=all

The user reports this was still working yesterday, so this is likely caused by a recent change. The 5.9.1 merge, perhaps? cc @david-binda 

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Affecting all classic themes I've checked, including Varia and Seedlet (classic) children.

Affecting all default themes up to Twenty Nineteen

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The Widgets page at Appearance ->Widgets still appear to work normally.

**Comment by Robertght** [comment]
I also asked here: p1645600271357269-slack-C02DQP0FP

**Comment by filipanoscampos** [comment]
This user has reported another case of this bug, here: 4805334-zd-woothemes

**Comment by david-binda** [comment]
Thanks for the ping! It might be related to 5.9.1 merge, but the root cause, IMHO, lies in some other code. It's being worked on in D75545-code

**Comment by KokkieH** [comment]
Thanks for the quick fix. I've let the users mentioned above know.
