### ISSUE TITLE
Indiana phone number not validating 2FA possible 463 area code issue

### ISSUE THREAD

**Issue by noteeth** [Automattic/wp-calypso#61392]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/me/security/two-step
2. Select US for country code
3. add  phone number 4632105111
4. Click "verify by SMS"

#### What I expected

To be prompted to complete the verification process.

#### What happened instead
I saw the error, “That phone number does not appear to be valid”.

#### Screenshot / Video

<img width="1092" alt="Screen Shot 2022-02-22 at 5 28 14 PM" src="https://user-images.githubusercontent.com/16570939/155250687-7372409e-4eaf-4800-b167-a378fd1fbd5a.png">

#### Context / Source

4804444-zen
User mentioned that 463 is a new area code for Indiana, so wondering if it isn't validating correctly yet in calypso.

**Comment by masperber** [comment]
33280681-hc another issue with a 463 area code not being accepted as a 2FA method

**Comment by lynnbgriffith** [comment]
Submitted a patch upstream that should address this problem:
https://github.com/AfterShip/phone/pull/291
Once merged, we'll bump Calypso to the new version and update this issue.

**Comment by lynnbgriffith** [comment]
Fixed in #63104.
