### ISSUE TITLE
Post Carousel block does not display author names when typed in the Author field in Settings

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/wp-calypso#61398]
### Quick summary

On simple sites, the Post Carousel block doesn't display the author names in the Author field when we start typing in it. Even if you type the full name of the author it doesn't seem to take it and posts from other authors are also displayed in the carousel.

### Steps to reproduce

1. Creat a page, add Post Carousel block.
2. Try adding an author name in the block settings bar.

https://user-images.githubusercontent.com/49064126/155277605-e13e6520-08cd-471d-832b-beb9d0e5a146.mp4

### What you expected to happen

The Authors field should display the author names in a list and display the post from that author in the carousel block.

### What actually happened

The author list does not appear. The posts in the carousel remain unchanged.

### Context

#4803611-zd

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Nope.

### Browser, operating system and other notes

NA

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

In the block settings, turning on Choose Specific Posts and manually specifying the posts from a particular author works but not very practical, especially if the author has a large number of posts. Also, the list has to be manually updated everytime a new post is published by that author.

**Comment by Prin-S** [comment]
Reported in 4816974-zd also.

**Comment by Greatdane** [comment]
I can't get it to work on AT sites also.

**Comment by jordesign** [comment]
This is a CoBlocks block - can we please triage again on a self-hosted site with CoBlocks installed to see if the issue occurs in that instance?

If so - we'll need to open an issue in the CoBlocks repo
https://github.com/godaddy-wordpress/coblocks

**Comment by Greatdane** [comment]
Self-hosted Post Carousel block does not have author option;

<img width="2549" alt="Markup 2022-04-06 at 13 57 39" src="https://user-images.githubusercontent.com/5075840/161898957-2a0a0e08-4465-438b-bc5d-de1343b0805c.png">

Keeping in Calypso and added coblocks label.

**Comment by wojtekn** [comment]
This is fixed now.
