### ISSUE TITLE
Masonry block editing crashes editor 

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#61403]
### Quick summary

When we are editing Masonry block editor clashes. 

https://user-images.githubusercontent.com/11535091/155294527-91505dfc-54d7-4bb1-8d1c-ad586d0da718.mp4

### Steps to reproduce

1. Add Masonry on Atomic site 
2. Try to edit it as if you wanted to transform it but don't click anther block just yet
3. Wait a moment
4. "The editor has encountered an unexpected error" 

### What you expected to happen

Masonry can be edited, user especially wishes to transform it into another gallery type block. 

### What actually happened

We get "The editor has encountered an unexpected error" 

### Context

4805254-zd-woothemes

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

no

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Reload and transform it faster than the editor occurs (but the user's impression is really bad)

**Comment by Greatdane** [comment]
Closing this in favour of https://github.com/Automattic/wp-calypso/issues/56559
