### ISSUE TITLE
Implement MVP to inject vertical images into themes

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#61401]
## Description

After investigation of https://github.com/Automattic/wp-calypso/issues/61399 and https://github.com/Automattic/wp-calypso/issues/61400, we can provide the MVP to demo the output and verify the result is what we want or not.

## Acceptance Criteria

I think we can implement the PHP function to provide an MVP

### Create a PHP function and use unit tests to verify the result

Input: The raw content of theme content and vertical slug
Output: The new content and its images are replaced with the vertical images

---

If we have time, we can continue to apply the above function into real use cases as followed. If not, we can split them into other tasks.

### Insert the images into the static themes in the Design Picker

Apply the above PHP function to the static themes including pages and related posts

### Insert the images into the generated themes

Apply the above PHP function to the generated themes if https://github.com/Automattic/wp-calypso/issues/61198 are ready

### Make an MC tool (Optional)

In further, we can also make an MC tool to provide visual results. For example, we can select a vertical and a static theme, and it will generate the preview.

---

If you have any questions, feel to let me know.

## Related

* Project Thread: pNEWy-eFy-p2
* Vertical Image Curator: p9Jlb4-3ph-p2

**Comment by autumnfjeld** [comment]
> Make an MC tool (Optional)
In further, we can also make an MC tool to provide visual results. For example, we can select a vertical and a static theme, and it will generate the preview.

This is an excellent idea @arthur791004 .  In fact, could we build a Generated Design MC tool that would mimic what we want to do in onboarding?  Then we have a playground for the progression of our tech work _and_  a designer could use it to test out their ideas.   cc: @Automattic/ganon

**Comment by arthur791004** [comment]
Here is the MVP: D76068-code and you could see the result from
* pbxlJb-190-p2
* pbxlJb-1l7-p2
* pbxlJb-1ow-p2
