### ISSUE TITLE
FSE: Consolidate Edit page / Edit Site / Edit buttons on the frontend

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#61409]
### What

Currently, when viewing an FSE site one sees the `Edit page` button at the top, and then there are two more links in the Action Bar at the bottom right: `Edit Site` and just `Edit`.

![Edit page, site, action bar](https://user-images.githubusercontent.com/39308239/155346648-16af6620-1984-4bc4-b1da-4e7df3638494.png)
 

### Why

It's confusing to have multiple buttons.

### How

Consolidate the buttons. For example, move the `Edit Site` from the Action Bar to the top, next to the `Edit page`. And also remove the `Edit` from the Action Bar.

**Comment by Addison-Stavlo** [comment]
these seem to be consolidated now:
![Screen Shot 2022-07-20 at 11 42 50 AM](https://user-images.githubusercontent.com/28742426/180025415-76fd1d14-d3eb-4703-9fbb-967b36bd3465.png)
