### ISSUE TITLE
FSE: Managing menus shows refused to connect page

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#61405]
### Quick summary

When in Site Editor and I click on manage menus in the navigation block, I get a refused to connect page.

![Screenshot at Feb 23 10-41-40](https://user-images.githubusercontent.com/4719037/155303885-1c01bf92-3e91-46f6-90b6-5cfc7338c311.png)

![Screenshot at Feb 23 10-43-21](https://user-images.githubusercontent.com/4719037/155304007-ff2117ce-ee3a-4019-bfed-8ace65f3925e.png)

### Steps to reproduce

1. Go to Appearance > Editor
2. Add a navigation block
3. Select a menu for the navigation block
4. Go back to navigation block, click on "Select Menu" and scroll down to select "Manage menus"
5. You'll see a prompt to leave the site. Click to leave site
6. Notice the issue

### What you expected to happen

Clicking on Manage menus should send me to the menus to manage them

### What actually happened

Clicking on manage menus saw the page refusing to connect

### Context

User reported a related issue here 4801735-zen. I however didn't get the exact issue as the user reported.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

So far tested on Twenty Twenty-Two (Blue) and Blockbase 

### Reproducibility

Consistent

### Severity

All

**Comment by Greatdane** [comment]
Closing in favour of; https://github.com/Automattic/wp-calypso/issues/60932
