### ISSUE TITLE
2FA: Instructions for editing two-factor phone number are incorrect

### ISSUE THREAD

**Issue by cfinke** [Automattic/wp-calypso#6141]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/security/checkup
2. See instructions: "To edit your SMS Number, go to Two-Step Authentication."
3. Go to "Two-Step Authentication." (https://wordpress.com/me/security/two-step)
4. See no way to edit my SMS number.
#### What I expected

I expected to be able to edit my SMS phone number.
#### What happened instead

I took a guess that the phone number cannot be edited while 2FA is active, so I disabled it and was able to edit my number. This is fine, but that should be made clear in the instructions.

Resolving issue #19 would likely fix this issue as well, although I was not actually switching to a new device, just changing from my Google Voice number to my actual cell number.

**Comment by rachelmcr** [comment]
Bug scrub: I tested this issue and there's no longer a "checkup" section at https://wordpress.com/me/security/checkup. Instead, there is an "Account Recovery" section at https://wordpress.com/me/security/account-recovery with the option to add a Recover SMS Number separate from your 2FA number:

![screen shot 2017-08-28 at 6 06 55 pm](https://user-images.githubusercontent.com/8658164/29784401-bc770efa-8c1b-11e7-8f47-2cd48ea69155.png)

Given that we no longer have incorrect instructions for editing the 2FA number, I think we can close this issue. Enhancements related to changing the 2FA number can be tracked with #19.

**Comment by rachelmcr** [comment]
In addition, the 2FA settings screen currently includes clear instructions for changing the phone number being used:

> Authentication codes are currently being sent to #########. If you wish to change this number, please disable Two-Step Authentication, then go through the setup wizard again.
