### ISSUE TITLE
Seller Experience - Provide more obvious "next step" after upgrading account from Payment Block

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61421]
After the user has selected "Upgrade" from the Payment Block while on a free site, and passed through the upgrade to a personal plan, they are returned to the block editor but without any noticeable call to action. We should provide a more direct "next step" to bring the user back into the "Sell" intent process.

![image](https://user-images.githubusercontent.com/13437011/155407412-d3ee2edf-dea6-47f4-b1fa-fb4b28336ae5.png)
![image](https://user-images.githubusercontent.com/13437011/155407439-d33ec0fe-b547-4670-9382-6ee0a0c3755a.png)
![image](https://user-images.githubusercontent.com/13437011/155407517-a37f0896-4fa9-4ce0-950c-6cb2e61e9b2d.png)

The `?notice=purchase-success` seems potentially like something we could hang this off of.

**Comment by michaeldcain** [comment]
> The `?notice=purchase-success` seems potentially like something we could hang this off of

This was added by Marketing for redirects to Calypso (where they show a simple notice), but should be pretty reliable for any situation where Checkout uses the `redirect_to` query param (as this does).

**Comment by kwight** [comment]
@SaxonF Can you give some design guidance here as to what we should be showing?

**Comment by SaxonF** [comment]
Couple of thoughts. 

It would be nice to get to a point where plan upgrades can happen without leaving the editor or other flows like onboarding. 
![image](https://user-images.githubusercontent.com/1072756/168202710-10a95ca8-f36e-44be-9fb7-3ebdf7b5ad09.png)

I think in situations like this we could probably lean more heavily into the help and guidance work. e.g. a help tour explaining the product block should be aware of plan upgrades and continue the tour once the upgrade is complete. 
![image](https://user-images.githubusercontent.com/1072756/168204922-ace7c24f-bd81-42f5-ba16-6b0c6dbba651.png)

I'm not sure if we need to do anything right now other than maybe selecting the block if that's possible?

**Comment by blackjackkent** [comment]
@SaxonF To confirm, you're saying this issue doesn't have any work needed and the idea should be forwarded to an eventual redesign of the in-editor checkout flow?

Is that a project that is definitely being planned or is this speculation?

/cc @ianstewart

**Comment by SaxonF** [comment]
@blackjackkent after our discussion I do think the [Snackbar](https://wordpress.github.io/gutenberg/?path=/story/components-snackbar--default) component is the right one to use here for the time being. After redirecting back to editor we can trigger the message. This should eventually tie into the welcome tour where we can highlight the product block with next steps, but that's not something we can do right now :)

"Welcome to the pro plan! Premium blocks are now available to use."

**Comment by valterlorran** [comment]
Hey @SaxonF, do you have a preference for the position of the Snackbar? I was considering adding it centered on the bottom.

**Comment by SaxonF** [comment]
@valterlorran +1 on Centered bottom as I think that's the standard editor position

**Comment by markbiek** [comment]
Quick update. We're having some issues deploying the ETK to Atomic.

Detailed discussion: p1656601485245469-slack-C0Q664T29
Request for help: p1656614773446789-slack-C02DQP0FP
