### ISSUE TITLE
Themes Showcase - Remove categories from logged out view

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61424]
Currently the logged-out view of the theme showcase has an extra "categories" section that has unreliable behavior and doesn't match anything on the logged-in side; consequently, we should remove it and adjust the design as necessary to make it look clean.

![image](https://user-images.githubusercontent.com/13437011/155413051-8c04640d-24f8-44fc-bc22-0c42c2edc1c3.png)

cf. pdF78r-aq-p2#comment-170 "We should probably remove the categories from the top of the logged-out Showcase. It’s not a pattern shared with the logged-in Showcase, they don’t seem very accurate with Free themes, and they’re worthless for Premium themes:"

**Comment by blackjackkent** [comment]
Grabbing this to work on at the start of the coming sprint. /cc @SaxonF - can we touch base to discuss any potential design tweaks around this change?

**Comment by SaxonF** [comment]
Will start thinking about this first thing Monday @blackjackkent

**Comment by markbiek** [comment]
This seemed like it was going to be as simple as just removing
```
{ ! isLoggedIn && (
	<SubMasterbarNav
		options={ headerIcons }
		fallback={ headerIcons[ 0 ] }
		uri={ this.constructUrl() }
	/>
) }
```

from the `ThemeShowcase` component but there's some magic happening behind the scenes.

If the `SubMasterbarNav` component is deleted is deleted, something else ends up creating that markup and then the contents of the `themes__content` div gets moved up into the `sub-masterbar-nav` div.

See it in action!

https://user-images.githubusercontent.com/917632/156256845-e1ec5407-0bca-4cc3-9528-2d9fb5f477eb.mp4

Will keep poking around to see where that's all happening.

**Comment by markbiek** [comment]
I think the weirdness I was seeing yesterday was some glitch with the local SSR stuff. I did a full clean & rebuild and everything is appearing as expected now.
