### ISSUE TITLE
Seller Experience - Include "Connect to Stripe" menu item on sub-blocks of Payment Block

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61422]
When navigating the Payment Block in the block editor with a paid plan, the user's main visual cue is the button block, which is actually a sub-block of the Payment block as a whole. However, only the wrapper block has the "Connect to Stripe" menu prompt, but it is hard/unintuitive for the user to navigate to that particular level of the block hierarchy.

![image](https://user-images.githubusercontent.com/13437011/155408141-ecd4f6ba-2724-4bfb-91f3-910db822aab7.png)

We should make the "Connect to Stripe" option a part of the button block's tool menu as well (or make the distinction between the button and its container more obvious).

**Comment by Copons** [comment]
I haven't tested it, but this might be solved with `supports: { __experimentalExposeControlsToChildren: true }`.
It's currently used by the Buttons and Social Links blocks in Core Gutenberg to expose the parent's alignment controls in the children's toolbars.

See PR when it was introduced: https://github.com/WordPress/gutenberg/pull/33955
