### ISSUE TITLE
Make wpcom_site_has_feature() globally accessible

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#61425]
D75219-code introduced `wpcom_site_has_feature()` as a library function, which means that every time it's used it has to be preceded by a call to load the library (see `mu-plugins/footer-credit/customizer.php`).

To enable more liberal use of the function I'd suggest we move the folder that contains `wpcom_site_has_feature()` to `mu-plugins` so it can also be used in all places. Same for wpcomsh, where I'd suggest we bring it back to `wpcomsh.php` and loaded it there early.

See 814-gh-Automattic/wpcomsh.

**Comment by DustyReagan** [comment]
This is addressed in WPCOMSH with:

- 828-gh-Automattic/wpcomsh

And in WPCOM with:

1. D75828-code
2. D75939-code
3. D75965-code
4. D76006-code

**Comment by obenland** [comment]
Nice work @DustyReagan, thank you for taking this on!
