### ISSUE TITLE
Plugin search input is sluggish on mobile android/FF

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61435]
Might just be me, see if you can replicate.

Typing in the search box sort of lags like its doing a lookup between each keystroke and that lookup is preventing rendering the next keystroke from being rendered.

Couldn't replicate on desktop.

**Comment by cpapazoglou** [comment]
FF means Firefox? Does it work OK for chrome?

For reference, works fine in iPhone 12 with Safari.

**Comment by lsl** [comment]
> FF means Firefox? 

Yes

> Does it work OK for chrome?

Nope, same issue.

It's something to do with the auto search, it blocks rendering of the input while it sets up a search.

Typing "ecommerce" the "e" gets searched for and then "comm" renders all at once and then "ecommerce" gets searched for in the second update.

Same goes if you hold the delete key down on the word "ecommerce", it will hang momentarily on the final "e".

Same issue on firefox/iphone but less noticeable, probably down to being a more powerful chip than my android. Safari was almost unnoticeable but definitely still hung on deleting the final "e" when backspacing to empty, but again, it was less pronounced.

It doesn't look network speed related, more likely something cpu bound.
