### ISSUE TITLE
Theme File Editor and User Editor in WP-Admin Dashboard broken

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#61449]
### Quick summary

I had two users back to back in chat. One was trying to edit their custom built theme using Appearance > Theme File Editor
Now they are trying to access the header.php it takes them to plugins page: https://wordpress.com/plugins/ and second has a LMS plugin and they were trying to edit their users in WP-Admin Dashboard User's tab and on editing the user it takes them to plugins page: https://wordpress.com/plugins/

I can replicate them on my test site too.

### Steps to reproduce

Go to Theme File Editor in WP-Admin Dashboard or Users tab in WP-Admin Dashboard and try to click on a theme file or try to edit a user

### What you expected to happen

User and I expected the theme file code to open or the user edit screen to open

### What actually happened

It takes both user and I to plugins page: https://wordpress.com/plugins/

### Available workarounds?
(Updated by @JoshuaGoode) Use SFTP

**Comment by ghost** [comment]
Cases hc-29445880 and hc-34313443

**Comment by JoshuaGoode** [comment]
Potentially due to 825-gh-Automattic/wpcomsh ?

This started after `wpcomsh` 2.8.72 was deployed @Automattic/bespin 

Dropped a line internally: p1645717375472069-slack-C02JPCHEKDY

**Comment by inaikem** [comment]
I can confirm this is also affecting user edit links in WP Admin on AT sites. 

Cc @Automattic/quality-squad + @simison

**Comment by inaikem** [comment]
Thanks @JoshuaGoode. Your comment above just loaded in for me. I've also reported it here in the meantime: p1645717767520539-slack-C02FMH4G8

**Comment by JoshuaGoode** [comment]
Users can utilize SFTP in the meantime.

**Comment by JoshuaGoode** [comment]
It seems this also impacts the WP-Admin User list.  

Accessing a specific user in the WP-Admin user list redirects to wrodrepss.com/plugins as well, as reported on p1645718431756679-slack-C03TY6J1A

Edit: Ah, I see this was already covered briefly in the title and initial description 😄

**Comment by desnum** [comment]
Cases: 34365386-hc and 34366286-hc

**Comment by poeticabdul** [comment]
Reported here 34366965-hc . Follow up 4809739-zen

**Comment by JoshuaGoode** [comment]
`wpcomsh` 2.8.73` is deploying now and will be on all servers shortly.  It includes a fix. 827-gh-Automattic/wpcomsh

Thank you @cpapazoglou & @epeicher 

I'll loop back once we're fully deployed.

**Comment by ccwalburn** [comment]
Another case here: 34365548-hc / 4809533-zen

**Comment by JoshuaGoode** [comment]
Fix is fully deployed.  Tested a few sites to confirm things are working properly now.

**Comment by ccwalburn** [comment]
Works for my reported case, too!

**Comment by cpapazoglou** [comment]
Fixed by 827-gh-Automattic/wpcomsh
