### ISSUE TITLE
[Bug]:  Better error messages on the “Use a domain I own” page for domains that can’t be transferred.

### ISSUE THREAD

**Issue by spraveenitpro** [Automattic/wp-calypso#61463]
### Quick summary

When you try to search for a domain from `Upgrades >> Domain >> Add a Domain >> Use a domain I own` followed by typing a domain name with TLD `.nl`, we get a error message: `This domain cannot be transferred.`

![](https://d.pr/i/6CrlVS+)
[Direct Link](https://d.pr/i/6CrlVS+)

This is not very useful or intuitive, we need error messages that are more descriptive like it is shown on `Upgrades >> Add a Domain >> Search for a domain`:

![](https://d.pr/i/JcdH2G+)
[Direct Link](https://d.pr/i/JcdH2G+)

We see the following message on the `search for a domain` page which is much better

`.nl domains are not available for registration on WordPress.com. If you purchased hotel.nl elsewhere, you can [connect it](http://calypso.localhost:3000/domains/add/hotel720166405.wordpress.com#) with WordPress.com Premium.

### Steps to reproduce

1. Goto /domains/add/use-my-domain/:site 
2. Enter a domain with a TLD `.nl` and click `next`
3.  We will see 2 cards, in the second one, we see the subheading `This domain cannot be transferred.` , this message needs to be more intuitive/elaborated. ![](https://d.pr/i/SSUBVF+)
[Direct Link](https://d.pr/i/SSUBVF+)

### What you expected to happen

Change the messaging from `This domain cannot be transfered.` to something like `.nl domains are not available for registration on WordPress.com. If you purchased hotel.nl elsewhere, you can connect it with WordPress.com Premium.`

### What actually happened

![](https://d.pr/i/6CrlVS+)
[Direct Link](https://d.pr/i/6CrlVS+)

 @delputnam

**Comment by delputnam** [comment]
Thank you for addressing this issue @spraveenitpro! 🙇 

I think this looks like a really good solution.  The only change I would make is to the specifics of the message to show on the Use a domain I own page.  For this case, we'll already show that you will be able to connect the domain in the card directly above the transfer card, so I think we could limit the message to the reason why the domain cannot be transferred. For example: `We don't currently support transfer of .nl domains to WordPress.com.`

**Comment by tyxla** [comment]
Addressed by #61827.
