### ISSUE TITLE
Seller Experience - Add a new Seller-related step to the editor welcome tour

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61466]
When first landing in the editor after picking the simple pathway, a user is greeted with a generic in-editor tour. Let’s add a step that is payment block specific.

When first entering the editor, I should be greeted with the in-editor tour. The second-to-last step in the tour should be focused on the Payments Block for users who arrived in the site editor as a seller who followed the "Start Simple" onboarding pathway.
Clicking “Learn more” in this step should open up a new tab and takes the user to https://wordpress.com/support/video-tutorials-add-payments-features-to-your-site-with-our-guides/#how-to-use-the-payments-block-video.

![image](https://user-images.githubusercontent.com/13437011/155620511-1ad4b45c-6ee7-4028-99aa-620212f98d53.png)

**Comment by kwight** [comment]
This will also need an appropriate gif – @SaxonF can you set us up here?

**Comment by nelsonec87** [comment]
A couple of questions about the expected behavior:

- Should the new step be visible for everyone or just for people coming from simple seller flow?
- When coming from simple seller flow, which step should be active, the first or the payment one?

**Comment by blackjackkent** [comment]
@nelsonec87 The step should only be visible to users who came from the simple seller flow, and they should still start from the first slide in the guide; we're just adding an extra slide for them towards the end. 😄
