### ISSUE TITLE
Seller Experience - Capture industry vertical as part of Seller onboarding flow.

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61465]
As a user going through onboarding I want to enter my industry so that I can see and use more relevant designs.

Add a required searchable dropdown "Industry" field to the screen that currently captures a user's store name and description; populate this dropdown with values from [Stripe’s merchant categories](https://stripe.com/docs/issuing/categories).

![image](https://user-images.githubusercontent.com/13437011/155620062-1a1009e6-a30a-4b80-bf01-4e9e40b62b55.png)

**Comment by blackjackkent** [comment]
This has turned out to be a more complicated issue than it appears at first glance. There's been quite a bit of discussion as a result at p1646166925722759-slack-C0Q664T29 regarding the proper source of truth for a list of verticals and how to coordinate this among the projects of multiple teams. (We have (re)opened a channel for further discussion on this subject at `#vertical-content`).

This issue might have to be put on hold until that discussion is hashed out; we'll be meeting sometime this week for the purpose.

/cc @ianstewart

**Comment by blackjackkent** [comment]
It looks like Ganon not only implemented the API but also added a new step to the flow in Stepper (before intent capture, as the first step in `site-setup`) with vertical capture:

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/13437011/162768931-060c3bc0-c86b-4feb-8bc7-1eaf8aa6bc8d.png">

Let's verify that this is hooked up and properly conveying its data to subsequent steps, and if so, we can close out this issue.

**Comment by blackjackkent** [comment]
(Update - Ganon has put the dropdown behind a feature flag - see p1649817121328769-slack-CDPL9US68 for info.)

**Comment by sixhours** [comment]
I see a `site_vertical_id` under the site's `options`, with an integer that I think corresponds to the site vertical I picked ("Dogs", in this case):

<img width="247" alt="Screen Shot 2022-04-25 at 12 30 09 PM" src="https://user-images.githubusercontent.com/2124984/165133348-49a0d9ff-7bce-472e-a736-28b0cfc5800b.png">

I need to confirm this ID matches what we're using in the store of verticals, but I think the data is being passed through properly.

**Comment by sixhours** [comment]
Yep, `886` matches the Google AdWords data on which the new verticals API is based, so I think we can close this out:

<img width="490" alt="Screen Shot 2022-04-25 at 12 39 51 PM" src="https://user-images.githubusercontent.com/2124984/165134536-ca9f5a80-dd6b-4499-9540-99d47d632885.png">

API ref: pbxlJb-1oG-p2
