### ISSUE TITLE
Seller Experience - Add educational panel for users with "Sell" intent

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61467]
Within My Home we currently show a couple of educational panels that link off to support articles and video courses. Let’s add a seller specific panel that does the same.

As a user who has selected sell intent, show a seller focused panel on the My Home screen. Clicking learn more within this panel should open up [https://wordpress.com/support/video-tutorials-add-payments-features-to-your-site-with-our-guides/ in a new tab.

![image](https://user-images.githubusercontent.com/13437011/155620825-1b1c5527-6fc0-4099-a962-72269cdbd220.png)

**Comment by sixhours** [comment]
Deployed in #61586 and D75890-code
