### ISSUE TITLE
Seller Experience - Customize Woo landing page for Sell users

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61472]
For "Sell" users that have a launched site that is using a product block (i.e. they took the "Start Simple" path during onboarding), we should display customized content on the Woo landing page - CTA text “Upgrade your store” with a sub message “Need more out of your store? Unlock the tools needed to manage products, orders, shipping and more.”

![image](https://user-images.githubusercontent.com/13437011/155622983-00e3926b-c93c-4418-ae6e-916cc666efa7.png)

**Comment by markbiek** [comment]
As part of #61471, I'm going to be implementing a check to see if someone is a "simple seller". We'll be able to leverage that same check here.

**Comment by kwight** [comment]
Figma is linked in the Seller Experience v2 post.
