### ISSUE TITLE
Seller Experience - Add Woo upsell to My Home banner

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61471]
For "Sell" users that have a launched site that is using a product block (i.e. they took the "Start Simple" path during onboarding), we should display an upsell banner within My Home that directs them to the in-product Woo landing page.

Clicking “Learn more” should take the user to the Woo landing page (`http://wordpress.com/woocommerce-installation/{site-url}`). The user can close this banner via the “Hide this” button. The banner should utilize existing banners components used in My Home.

![image](https://user-images.githubusercontent.com/917632/156621130-36fd5145-586e-4497-b065-fc21b957e5e5.png)

**Comment by markbiek** [comment]
Opened translation PR #61606

**Comment by markbiek** [comment]
@SaxonF The normal behavior for these kinds of notices is that they appear in a carousel with all the notices and the user can click through them like so:

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/917632/156451254-6b555c8f-7c7c-4727-9ecb-220399cd0ee6.png">

Do we want this upsell banner to work the same way or do we want it to be a stand-alone thing?

**Comment by SaxonF** [comment]
@markbiek let's stick with the carousel. Thanks!

**Comment by markbiek** [comment]
I think this can be closed. It doesn't really seem to apply any more.
