### ISSUE TITLE
Stats: Day, Month, Year view does not show stats when language is set to Arabic

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#6147]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Change language to be Arabic
3. View single site stats page and choose day, month, or yearly view
4. The blocks below do not display data while the graph at the top does

I've tried other languages including other RTL languages and this still seems to work. It is just Arabic which seems to have the issue.

#### What I expected
I expect that the data displayed would be the same regardless of language. Sections like Countries, Posts & Pages etc would display the data

#### What happened instead
Instead these items displayed no data with messages such as No countries recorded or No posts or pages viewed

#### Tested In
Firefox Mac / Windows Chrome
There didn't appear to be any additional errors in the console which weren't there when the language was set to one which was working.

#### Screenshot / Video
<img width="811" alt="arabic-stats" src="https://cloud.githubusercontent.com/assets/1326294/16194376/a8fdf46c-36ca-11e6-8eb3-9bba3dcc4594.png">

#### Context / Source

This was first reported by a user and then tested on a test account as well #user-report

**Comment by chrisfromthelc** [comment]
I had a chat user with the same identical issue, but their interface language is set to Persian (fa). I believe their browser language my be set to Persian as well. This tiny screenshot is all I could get them to provide, since there was a language barrier.

![image-wordpress-bis](https://cloud.githubusercontent.com/assets/8002138/16324765/4a9e83ce-396c-11e6-96cd-26f2f0190178.jpg)

**Comment by AinslieK** [comment]
I also have the same issue with a user in Arabic. Stats will display if the interface is in English but not in Arabic.
<img width="300" src="https://cloud.githubusercontent.com/assets/13279752/16326836/f5eea774-397e-11e6-8925-6eef77ba69d5.png">

**Comment by yoavf** [comment]
See #6263

**Comment by jeremeylduvall** [comment]
I think this is fixed now that #6263 has been merged (seems fixed in my testing as well). Definitely reopen if necessary.
