### ISSUE TITLE
Seller Experience - Add Design Picker back into the Seller onboarding flow.

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61470]
As a user going through onboarding I want to be able to choose a design for my product so that it best suits my needs.

If the user selects "Start Simple" in the Sell intent onboarding flow, they are directed to the design picker step; the "Store" category and its accompanyhing themes should be displayed by default.

Hovering over each theme shows “start with” and “preview” buttons. Clicking "preview" on a particular theme takes the user to the preview theme screen for that theme. Clicking “start with” a particular theme drops the user into the full site editor with that theme enabled and its payment block visible.

Hitting “Use a blank theme” should send the user into the editor using the default block theme (existing behavior).

**Comment by sixhours** [comment]
This was done in #61545
