### ISSUE TITLE
Footer credit: "Hide (requires Business plan)" still shows even on sites with a Business plan

### ISSUE THREAD

**Issue by hideandgeek404** [Automattic/wp-calypso#61486]
### Quick summary

When choosing the "Hide Footer" option within the Customizer the dropdown options show "Hide (Business Plan Required)" despite the site being on the correct plan for this functionality. You can then not save the option to see if it is just visual.

### Steps to reproduce

1. Click `Appearance > Customize`
2. Click `Site Identity`
3. Scroll to the bottom of the options and click the Footer Credit dropdown
4. Note how the dropdown says `Hide (Business Plan Required)`

<img width="328" alt="Screenshot 2022-02-25 at 13 44 27" src="https://user-images.githubusercontent.com/81396999/155727597-005f8cfd-6694-4882-bde2-0498e9d7f1e2.png">

### What you expected to happen

I would expect to be able to choose the Hide option without it asking me to upgrade to a package I already have.

### What actually happened

Clicking on the `Hide` option creates a prompt to upgrade

<img width="334" alt="Screenshot 2022-02-25 at 13 59 35" src="https://user-images.githubusercontent.com/81396999/155727765-a59f9c31-be5d-44d5-9f48-03a32530e526.png">
 

### Context

Customer initially reported on 4812306-zen and I have managed to replicate on my own test site, but setting up a new test site did not have the same issue.

I can only really confirm I've seen this on Atomic, but it might be valid on Simple sites too. 

### Simple, Atomic or both?

Atomic

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

If site has custom CSS option, use it to manually hide the footer credits.

**Comment by marianearchimbaud** [comment]
I have found the same issue on this interaction : 4816118-zen
Theme: Baskerville 2
Atomic Site

**Comment by inaikem** [comment]
Another user report: 34413584-hc

Provided a CSS workaround: Atomic + Seedlet

**Comment by kerrynicl** [comment]
Another report here - 4820223-ZD
Theme : Maywood 
Atomic

**Comment by Nic-Sevic** [comment]
4820299-zd-woothemes
theme: shoreditch
Atomic > fixed after @jmdodd refreshed plan data

**Comment by msilbers** [comment]
reported in 4822785-zd
Atomic site, Byrne theme

will provide CSS as a workaround

**Comment by arunsathiya** [comment]
Also in 4824298-zen. Stow theme, gave CSS:

```
.site-info .comma, .site-info a:last-child {
	display: none;
}
```

**Comment by KirkwallDay** [comment]
Another instance here with Blank Canvas: 32187287-hc

Used a CSS work around.

**Comment by desnum** [comment]
Another instance here: 28301129-hc
Shared CSS workaround

**Comment by edwinho89** [comment]
4831000-zd-woothemes

**Comment by Robertght** [comment]
34308629-hc

**Comment by edequalsawesome** [comment]
FSE themes will require different CSS than the code posted above -- generally this should work, though!

```
/* hide site footer credit | XXXXXX-hc eD */
.site-footer-container + .wp-block-group {
	display: none;
}
```

**Comment by wprhunt** [comment]
4839125-zd-woothemes

**Comment by thekingsprojects** [comment]
Another case here: 33496708-hc

Barnsbury theme + Atomic. Provided CSS to hide it as a workaround.

**Comment by devNigel** [comment]
Another case: 32734183-hc

Baskerville 2 + Atomic. Shared the following CSS:

```
.credits-left {
    display:none;
}
```

**Comment by dragstor** [comment]
Another AT one on Blank Canvas: 32595969-HC

Used this to hide it:
```
.site-info .comma, .site-info a:last-child {
	display: none;
}
```

**Comment by JoshuaGoode** [comment]
Related to recent limited Atomic changes

814-gh-Automattic/wpcomsh

p1646753970870009-slack-C02V49GM0PN

**Comment by obenland** [comment]
Fixed after completing the script in D76265-code.

**Comment by JoshuaGoode** [comment]
#### Recap

Tested and confirmed this is now resolved via script completion, D76265-code.

Impacted users can now manage their footer, CSS, and permalinks as expected.  Ready for emails to waiting users.

**Internal context**
Related to limited Atomic work

p1646753970870009-slack-C02V49GM0PN

**Related issues now resolved** 
https://github.com/Automattic/wp-calypso/issues/61486 - 814-gh-Automattic/wpcomsh
https://github.com/Automattic/wp-calypso/issues/61738 - 833-gh-Automattic/wpcomsh
https://github.com/Automattic/wp-calypso/issues/61675 - 835-gh-Automattic/wpcomsh

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
