### ISSUE TITLE
Marketplace: deprecate Yoast product with product_id 900

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61484]
Since we created two new monthly and annual Yoast products, we will have to deprecate the `Yoast Premium` subscription with product_id = 900. Right not it is surfacing in Store Admin and people can select the deprecated subscription.

![CleanShot 2022-02-25 at 14 37 44@2x](https://user-images.githubusercontent.com/12430020/155716438-5fbafeb8-f608-4a77-b55b-2fd838ef45d9.png)

**Comment by cpapazoglou** [comment]
@JulianBustamante you mentioned there is a way to hide a product. Can you share more details?

**Comment by epeicher** [comment]
### Changes done:

The following SQL have been executed in my sandbox to _disable_ the Yoast with product_id = 900:

2be24-pb

### Testing instructions:
- Go to any Store Admin, e.g. navigate to https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=<your username> replacing `<your username>` with a valid username
- Expand the Product: dropdown and make sure there are no two occurrences of `Yoast Premium` product 
![CleanShot 2022-03-08 at 19 15 44@2x](https://user-images.githubusercontent.com/3519124/157300465-6642756f-ddcb-40db-95cd-bbb9437ab4ea.png)

**Comment by cpapazoglou** [comment]
Thanks @epeicher, it works as expected! Closing it!
