### ISSUE TITLE
Reader: When you click on blank space in Sidebar, it will scroll to top of the page

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#6149]
#### Steps to reproduce
1. Starting at URL: Reader - https://wordpress.com/ or http://calypso.localhost:3000/
2. Scroll down in posts
3. Click blank space in sidebar 

#### What I expected
I expect exactly nothing to happen.

#### What happened instead
The whole page scrolls to the top.

#### Browser / OS version
Anything should work the same.

#### Screenshot / Video

![scroll-to-top](https://cloud.githubusercontent.com/assets/156676/16198647/e7788d1a-3706-11e6-8a76-c2840a7a7cdd.gif)

#### Context / Source

#manual-testing

Found out while I was debugging loosely related #5860.

This behavior was introduced here https://github.com/Automattic/wp-calypso/commit/efb65c29#diff-d891509bba2775d10dbe5c88650e72acR79

Shouldn't that handler be called only when the event target is some kind of link?

cc: @bluefuton & @blowery

**Comment by bluefuton** [comment]
Well spotted @marekhrabe! Taking a look now.
