### ISSUE TITLE
Marketplace: Yoast Premium seems not getting installed 

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61493]
Following the comments of the CFT pdtkmj-4i-p2#comment-99, I tried to install Yoast Premium by using the following methods:

- Checkout from wordpress.com
- Adding the subscription from Store Admin

either way, neither Yoast premium nor Yoast got installed in my site.

**Comment by cpapazoglou** [comment]
Perhaps, the problem is the API `/api/provisioning/downloads/currentZip` (pcSRhZ-Y-p2) that Atomic infrastructure uses to download and install the latest version.

**Comment by cpapazoglou** [comment]
@jmdodd can you confirm whether `wordpress-seo` and `wordpress-seo-premium` are registered as **managed plugins**? Is there a way to cross check this on our own?

**Comment by jmdodd** [comment]
Yes, both of these plugins are available as managed plugins.

**Comment by cpapazoglou** [comment]
@jmdodd can you confirm that you are using `/api/provisioning/downloads/currentZip` (pcSRhZ-Y-p2) for installing the latest version as mentioned here p9o2xV-1A4-p2#comment-4954

> Yoast with HTTP auth. URL to find version. URL to download zip. Zip packaged as dotorg plugin zip should be.

If you do so, can you update your user / pass since we have updated `MARKETPLACE_YOAST_PREMIUM_USERNAME_STAGING` and `MARKETPLACE_YOAST_PREMIUM_TOKEN_STAGING`?

@JulianBustamante I don't get any error or success logs in `log2stash`. I guess that `marketplace_post_transfer_manage_software` is interrupted. Perhaps because `$this->add_yoast_premium_product();` is behind a `is_automattician()` check and when / where is atomic job runs it returns `false` and thus yoast is not registered as a product in the catalog.

```
$product = $marketplace->get_product_by_id( $subscription->product_id );

// continue to the next item if product is not one of the marketplace product
if ( ! $product ) {
  continue;
}
```

**Comment by jmdodd** [comment]
Per Slack; the existing script and authentication methods for platform install are working as expected.

**Comment by cpapazoglou** [comment]
Ok, I dug this a little more and the `is_automattician()` check is not a problem. The problem is that the `activate` function for the subscription is not triggered at all. 

**Proof that `is_automattician()` is not a problem** 
- With Yoast subscription added go ahead and add one more marketplace subscription
- The activate function will run for that new subscription
- It will queue `marketplace_post_transfer_manage_software`
- Which in turn fetches ALL subscriptions and for any of them being a marketplace subscription it triggers `WPCOM_Sites_on_Atomic::site_manage_software`
- Yoast SEO and Yoast SEO Premium will get installed together with the other marketplace plugin you have chosen in first step

While sandboxed (sandboxing `wordpress.com`) I get the following warning by monitoring the error log (`tail -f /tmp/php-errors`)
`###### BD WARNING Renewal was loaded without having a renewal price set feature="renewal_loaded_without_renewal_price"`

I suppose that after this warning the `activation` function of that subscription is not triggered.

**Comment by sirbrillig** [comment]
> While sandboxed (sandboxing wordpress.com) I get the following warning by monitoring the error log
> ###### BD WARNING Renewal was loaded without having a renewal price set feature="renewal_loaded_without_renewal_price"

🤔  Hm... I haven't tested this but I think this makes sense if you've added an ownership directly to your account (using SA) without purchasing it. We cannot renew a product that has no price to charge.

However, if I understand this issue correctly (and I may be wrong), the problem you're having is with the provisioning process after an initial purchase, not with a renewal. So this could be a red herring unless the renewal info is being queried during the provisioning process. I don't know much about that process (the `activate` function you mention above), but I'll look into it to see if I can figure out where it should be called and what might be stopping it from being called in this instance.

**Comment by cpapazoglou** [comment]
Well, found the root cause. We were using specific `Store_Product_Marketplace_Yoast` class for the product which didn't have the correct `activation` function. For all marketplace products (at least plugins for the moment) `Store_Product_Marketplace_Plugins` should be used.

diff here D76455-code

**Comment by cpapazoglou** [comment]
Deployed r241470-wpcom
