### ISSUE TITLE
Purchases: Allow to select PayPal in Edit Payment Method

### ISSUE THREAD

**Issue by melanieharari** [Automattic/wp-calypso#6150]
When you click Add Payment Method or Edit Payment Method, it only allows you to change to a new Payment Card, not PayPal. 

<img width="791" alt="screen shot 2016-06-20 at 8 21 53 am" src="https://cloud.githubusercontent.com/assets/7796153/16199910/37ebe73e-36c0-11e6-8842-d37b2107bcb9.png">

**Comment by fabianapsimoes** [comment]
I talked to Peter about that before, and it seems that's not possible. There’s no way to create a new PayPal billing agreement without a new payment, so the only way to change to PayPal would be through a renewal.
