### ISSUE TITLE
There should be no "My Themes" tab on sub Business plan Atomic sites.

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#61509]
### What plan tier(s) are affected?

Free, Personal, Premium

### Steps to Reproduce

Go to https://wordpress.com/themes/ on a Simple Free site and on an Atomic Free site. There should not be a "My Themes" tab on the Atomic Free site because uploads are not allowed on plans below Business.

### Expected (Simple)

![no-my-themes-tab-free-simple](https://user-images.githubusercontent.com/140841/155828888-1d0a1d78-6b95-4578-b180-1bcd5b2e9918.png)

### Expected (Atomic)

There should be no "My Themes" tab in the "Themes" section on plans that don't allow theme uploads. (Currently plans below Business.)

### Actual

![my-themes-tab-free-atomic](https://user-images.githubusercontent.com/140841/155828901-d76e76f8-6b6f-4f6f-8e5e-f98b31a9d659.png)

**Comment by obenland** [comment]
@DustyReagan Did #61468 fix this issue?

**Comment by DustyReagan** [comment]
No it did not.

**Comment by obenland** [comment]
> There should not be a "My Themes" tab on the Atomic Free site because uploads are not allowed on plans below Business.

What if a site has installed themes from a time where the site could install them? Shouldn't they still have access to them?

**Comment by mmtr** [comment]
_(Copied from https://github.com/Automattic/wp-calypso/pull/61928#discussion_r828893030)_

Oh right, I guess it would depend on how we sell the Business plan.

If we say that users are only allowed to **use** custom themes on the Business plan, I think we shouldn't differentiate between install/upload/switch, and instead create a more generic feature/capability that includes the whole management of custom themes. That new generic feature/capability is the one we should check everywhere to prevent users from installing/uploading/activating custom themes if the site doesn't have the required upgrade.

On the other hand, if we say that users cannot **upload** custom themes on the Business plan but they are free to **activate** the ones they uploaded while the site had the Business plan active, then we should check `switch_themes` which would keep My Themes available even if the site doesn't have the required upgrade.

**Comment by mmtr** [comment]
Thinking more about this.

When a customer cancels the Business plan on an Atomic site that has a third-party theme active, we automatically change the site theme to a first-party theme, so for consistency, I think we shouldn't allow access to My Themes if they don't have a Business plan, and make sure that any third-party theme installed in the site is not _activatable_.

**Comment by obenland** [comment]
In that case `install_themes` feels most appropriate. Thanks for talking this through with me!
