### ISSUE TITLE
[Bug]: External icons overlapping when sites menu collapsed

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#61504]
### Quick summary

See this screenshot, taken from https://wordpress.com/stats/day/eric.blog

<img width="118" alt="Screen Shot 2022-02-25 at 1 59 45 PM" src="https://user-images.githubusercontent.com/1126811/155787754-01366270-f8af-4f61-82f2-20aae1476fc7.png">

### Steps to reproduce

1. Start at /stats/day/$site_slug, for a Jetpack and likely Atomic site
2. Collapse menu
3. Observe external icons overlapping menu icons

### What you expected to happen

No overlapping. Maybe this means no external icon?

### What actually happened

Overlapping

### Browser

Google Chrome/Chromium

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on SH - could not repro

📌 FINDINGS/SCREENSHOTS/VIDEO

![NCeqoG.gif](https://github.com/Automattic/wp-calypso/assets/27249804/6bccec30-6431-4c60-a323-a4f402b2d7d2)

📌 ACTIONS
- Closed as not reproducible
