### ISSUE TITLE
Limited Atomic: Use feature checks for unsupported features

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#61506]
### Details

There are four feature checks in wpcomsh's `/feature-plugins/unsupported-feature-mods.php`. Let's move them away from plan checks to feature checks.

Bonus: Maybe we can find a way to consolidate that file with `/feature-manager` and `/wpcom-features`. It's probably a better place for it than `/feature-plugins`.

**Comment by DustyReagan** [comment]
To tackle this I'm thinking each feature will get it's own PR converting the plan check to a feature check to make reviewing easier. Then once that's done we rename `unsupported-feature-mods.php` to `feature-hooks.php` and move it to the `/feature-manager` folder.

**Comment by mmtr** [comment]
@DustyReagan FYI, just to make sure we don't overlap, I've started to work on the next feature(s) which are the restricted files.
