### ISSUE TITLE
Limited Atomic: Use feature check to gate Additional CSS

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#61500]
### Details

Let's move `Manage_Additional_CSS_Feature` from using a plan check to using a feature check.

Let's use `CUSTOM_DESIGN` as the underlying feature. While Additional CSS is gated to Business plans and higher on wpcomsh, it's premium or higher on wpcom, just like Custom Design.

Bonus: Maybe we can use this opportunity to move `/wpcom-features` to `/feature-manager` or vice versa?

**Comment by obenland** [comment]
Custom Design used to be a bundle of features (custom background color, text color, etc) that was sold as an upgrade and then deprecated. Let's double-check that it's the right feature to check for.

**Comment by obenland** [comment]
@ianstewart Is `CUSTOM_DESIGN` a feature that we can/should still use to feature-gate Additional CSS?

**Comment by gavande1** [comment]
Based on my findings, It appears that custom design is the feature that we use for gating Additional CSS feature. The checks are placed on `wp-content/mu-plugins/custom-css-in-customizer.php?r=c8138e41#9`.

**Comment by mmtr** [comment]
@gavande1 that looks right to me after taking a look as well.

**Comment by obenland** [comment]
Fixed in 835-gh-Automattic/wpcomsh
