### ISSUE TITLE
New page Publish panel shows "This post will be sent to" blog readers.

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#61515]
### Steps to reproduce

1. Start in the new Page editor.
2. Add content and click Publish button at the top right.

### What you expected to happen

Since the pages can't be notified to subscribers, there should be no heads-up that the page will be sent to blog readers.

And once the page is published, the **What's next?** section shouldn't say this post has been sent to subscribers.

### What actually happened

The publishing confirmation panel says, _This post will be sent to readers_:
![Subscribers panel in the new page editor](https://user-images.githubusercontent.com/1519466/155865440-08117969-ae3d-4e5b-a075-5d0d3a78f907.png)
And after publishing the page the **What's next?** section shouldn't display _This post has been sent to the readers_.
![Page sent to subscribers](https://user-images.githubusercontent.com/1519466/155865449-87d73123-bb33-4294-90bd-4faeed43c4be.png)

### Context

User report in 33908962-hc

_No response_

### Reproducibility

Consistent

### Available workarounds?

There is no user impact

**Comment by kimerlin81** [comment]
Thanks @happychait! This issue has been triaged as a bug since I was able to reproduce it on both Atomic and Simple test sites.

**Comment by goblinartificer** [comment]
Also in 10629239-hc

**Comment by louinel** [comment]
New case here: 4848937-woothemes-zen

**Comment by kriskarkoski** [comment]
+1, noticed this over the weekend while adding a page to my website

**Comment by edwinho89** [comment]
30847607-hc

**Comment by ccwalburn** [comment]
Another report here: 34839746-hc

**Comment by arinoch** [comment]
+1 in 4899578-zd-woothemes

**Comment by louinel** [comment]
New case here: 4910119-woothemes-zen

**Comment by jeherve** [comment]
this should be fixed as https://github.com/Automattic/jetpack/pull/23692. I'll close it now, do not hesitate to reopen if this happens again.
