### ISSUE TITLE
Publicize - Can't change Custom Message when using Classic Editor 

### ISSUE THREAD

**Issue by syds87** [Automattic/wp-calypso#61518]
### Quick summary

After enabling Publicize on a website, edit a post with Classic Editor. 

On the right-hand sidebar, click Publicize > Edit to edit the Custom message, set the post status to Pending Review and click Save as Pending. 

The new Custom Message will not be saved and you will still see the old one.

### Steps to reproduce

1. Connect the site to a social account at WordPress.com > Tools > Marketing > Connections (I've tried both Twitter and LinkedIn)
2. Install and activate the Classic Editor plugin
3. Go to Posts > Add New
4. Type something as title and text
5. On the right-hand sidebar, click Publicize Edit and type something in the Custom Message:
![Screen Capture on 2022-02-27 at 16-55-38](https://user-images.githubusercontent.com/70008187/155891747-b681d4c8-3b0b-4f87-9f8f-41cc36024387.gif)
6. Set the post status to Pending review.
7. Click Save as Pending

### What you expected to happen

I would expect the new Custom Message to be saved.

### What actually happened

I can see the previous Custom message, as if the new one doesn't get saved, when I click Save as Pending.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

**Comment by inaikem** [comment]
Additional user report here: 30700617-hc

Advised them to enable the Block Editor and set, then publish content via that view as a workaround.

**Comment by inaikem** [comment]
See this comment from @pablinos: pbg9X-gVH-p2#comment-67809

The issue will be resolved in the next JP release on March 1st: https://github.com/Automattic/jetpack/pull/23103

The only workaround currently would be to use the block editor to Publicize the post if a custom message is required.

**Comment by yashitamittal11** [comment]
Another user reported here- #4818185-zen
I checked the issue on my test site with multiple themes and Classic Editor active. The Custom message field is grayed out, and I cannot select/deselect the social media connections.

Screenshot from the user's site-
![publicize settings](https://user-images.githubusercontent.com/21078987/156317269-d770bbc2-1f8c-47fc-a611-97d02bdf28ff.png)

**Comment by dpasque** [comment]
Just tested, and it looks like with the new Jetpack update, this is now fixed! 🎉
