### ISSUE TITLE
Calypso - Change links to WordPress.com support documentation

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#61513]
### What

In calypso, to learn about tools or what certain things are, there's a link to 'Learn more' about it. Some of those links go to WordPress.org documentation, while some go to WordPress.com documentation. 

### Why

Instructions in WordPress.org have different wording than the actual settings at WordPress.com. 
And having all links go to WordPress.com will create uniformity. 

### How

- Change links to WordPress.com documentation: https://wordpress.com/support/

### Example: Post

Permalinks has `The last part of the URL. Read about permalinks` (that opens to WordPress.org): https://wordpress.org/support/article/writing-posts/#post-field-descriptions

<img width="365" alt="Screen Shot 2022-02-26 at 6 03 50 PM" src="https://user-images.githubusercontent.com/36863633/155852093-720abfc2-4ad2-45c7-8e4b-88ea0cb27821.png">

WordPress.com support link to Permalinks documentation is: https://wordpress.com/support/permalinks-and-slugs/

---

Tags has `Build your audience with tags` (WordPress.com documentation): 
https://wordpress.com/support/posts/tags/

<img width="306" alt="Screen Shot 2022-02-26 at 6 08 13 PM" src="https://user-images.githubusercontent.com/36863633/155852224-444c0530-9613-44dd-ad4b-b8c5ba97cceb.png">

---

Excerpt: `Learn more about manual excerpts`: 
https://wordpress.org/support/article/excerpt/

<img width="381" alt="Screen Shot 2022-02-26 at 6 09 15 PM" src="https://user-images.githubusercontent.com/36863633/155852277-9bd589b5-25bb-438e-8f27-b1f526c8eeed.png">

WordPress.com support link to Excerpt documentation is: https://wordpress.com/support/excerpts/ 

---

User case: 4815215-zd

**Comment by jordesign** [comment]
Adding this to Vertex's board
