### ISSUE TITLE
Slideshow breaks Editor when placed inside the Layout Grid. Super wide width.

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#61520]
### Quick summary

When the Slideshow block is placed inside the Layout grid, in Editor it will show with an extremely long width. Live view is okay but the Editor is totally broken.

https://d.pr/v/mfSqCL

4777593-zd-woothemes

### Steps to reproduce

Create layout grid
Add slideshow

### What you expected to happen

It will show correctly in Editore

### What actually happened

It breaks the Editor and shows giant width.

### Simple, Atomic or both?

Simple

### Available workarounds?

Yes, easy to implement

### Workaround details

When you take out the slideshow from the layout grid it will appear normally in the Editor as well. You can use Columns instead of the layout grid.

**Comment by ahmadbaig1** [comment]
Has been reported here- #39956 
This can be closed in favour of the above.

**Comment by edequalsawesome** [comment]
Closing in favor of other issue :)
