### ISSUE TITLE
Marketplace: Add Business plan to cart from All Sites view

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#61522]
### What

If the site does not have a Business plan, add a link to plans page or add both Yoast Premium + Business plan in the cart. 

### Why

Adding Yoast Premium to a site without the Business plan shows "Yoast Premium removed from your cart because it is no longer valid (you may have removed the associated business plan).
Clicking 'Go Back' button returns to the Plugin page and the list of sites are shown. But it does not specify which sites have the Business plan or not. Some users may not know where to buy a plan, so it'll be handy to give them the option where to get the Business plan from, or add Yoast Premium + Business plan in the cart together. 

### How

Adding Yoast Premium to a site without Business plan: 

<img width="1277" alt="Screen Shot 2022-02-26 at 12 57 51 PM" src="https://user-images.githubusercontent.com/36863633/155893643-2504adf2-4929-4157-bd2e-38573d0efe2a.png">

"Go back" button takes you to the Plugin section `https://wordpress.com/plugins/wordpress-seo-premium` again. There's a list of sites to choose from, but it does not specify which sites have the Business plan or not: 

<img width="1010" alt="Screen Shot 2022-02-27 at 6 53 17 PM" src="https://user-images.githubusercontent.com/36863633/155893747-480e8bee-de57-4271-851b-165d6548bc1b.png">

**Comment by cpapazoglou** [comment]
> If the site does not have a Business plan, add a link to plans page or add both Yoast Premium + Business plan in the cart.

@kspilarski this is what we do when you visit the plugin page from a single site

<img width="604" alt="CleanShot 2022-02-28 at 14 43 48@2x" src="https://user-images.githubusercontent.com/12430020/155985521-5180be0f-2592-4d3c-b355-cfdd63e4b53f.png">

From all sites **Plugins** page, we normally offer only the already eligible sites. I wonder, which of your sites is "eligible" but didn't have the correct plan. Can you share more details in a slack message please?

Perhaps though, we can also show a "Upgrade needed" section (just like "Available on") which will add a plan and the plugin to cart.

**Comment by cpapazoglou** [comment]
Putting this to high priority while figuring if it's a bug or not. If it's not a bug, we can move it to "Normal"

**Comment by kspilarski** [comment]
Thanks! I'll ping you in slack!

**Comment by dpasque** [comment]
@cpapazoglou Any update on whether this was a bug or not? Thanks! 😄

**Comment by cpapazoglou** [comment]
It's definitely a bug but and edge case where you try to install a plugin in an Atomic site that doesn't have a biz / ecom plan.

**Comment by WBerredo** [comment]
There are some cases where a site is being shown as **Eligible** but doesn't have an e-commerce or biz plan. 
We are working with the hypothesis of this to be happing when the site is atomic but doesn't have an eligible plan (TO BE CONFIRMED).

The next steps will be:
- [ ] Track when this bug is happening and fix it to only show eligible sites (ecom and biz) on the **Available on** list
- [ ] Add a new list called **Upgrade needed** with all sites that aren't eligible (nor ecom or biz). There will be a button called `Upgrade and activate` which will redirect to the cart with the bundle **plan + plugin**.
