### ISSUE TITLE
Marketplace: How can we streamline adding a product to the WPCOM store

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61531]
Currently adding a product to the dotcom marketplace consists of two big tasks (PCYsg-CJy-p2):

- Add product to the `Product Store` 
- ~~Add product to the Endpoint~~ this will be resolved by the Woo Integration

**Add product to the `Product Store`** 
We will still need this step even after the Woo Integration cause the product is actually sold from WP.com and that's why WP.com needs a reference to it. Currently, the process is cumbersome. While there a CLI tool for adding products to the store, we still need to manually answer to the CLI prompts and there is always a chance we make mistakes in `slugs`. 

_One idea_ would be to create a wrapper CLI tool (specific to the marketplace), with arguments `Product Name`, `Product slug`, `Monthly Price`, `Annual Price` and the result would be creating two products with the correct slugs in the store. We could later use that CLI to provision (and link) WP.com store products when products are created in Woocommerce.com.

**Comment by cpapazoglou** [comment]
Why do we use the legacy store? Is there a newer simpler way to add products to WordPress.com Marketplace?

**Comment by lsl** [comment]
> Is there a newer simpler way to add products to WordPress.com

It might be worth looking at how domains are doing this, they don't need to create catalog id constants or any kind of mapping step.

**Comment by cpapazoglou** [comment]
This is now handled in pdh6GB-PL-p2
