### ISSUE TITLE
Marketplace: Update static woo extensions data

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61534]
Since we have added the woo extensions to the Marketplace some data have changed and we need to keep up. Let's revise the following for all plugins:

- Version
- Last Update
- Documentation URL (lot of resources here https://woocommerce.com/document/woocommerce-points-and-rewards/)
- Live Demo URL
- Tags - Related convo (p1646049465177339-slack-C029JEQRVRT)
- Review rating

**Comment by epeicher** [comment]
Diff created D76152-code

**Comment by cpapazoglou** [comment]
Deployed r241466-wpcom
