### ISSUE TITLE
Marketplace: add WooCommerce Min/Max Quantities, Product Vendors

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61537]
### Details

- [x] Adding in `store_products`. Prices can be found in the spreadsheet of next woo extensions (Pdh6GB-2Y-p2)
- [x] Adding in `https://public-api.wordpress.com/wpcom/v2/marketplace/products` endpoint (`featured: false`)

@SaxonF, We will need plugin icons from the design team

Documentation: PCYsg-AhH-p2

**Comment by allilevine** [comment]
Opened https://github.com/Automattic/wp-calypso/issues/61548 for WooCommerce Pre-Orders.

**Comment by SaxonF** [comment]
Some discussion here around using a generic Woo icon for Woo related plugins C029JEQRVRT/p1646709488402109
![woo-icon](https://user-images.githubusercontent.com/1072756/157172615-d1c0e68b-87de-4cd2-a183-836a51d80e97.png)

**Comment by WBerredo** [comment]
Adding the products to the store and mapping them on WP.com: D77110-code
Fixed at: D77190-code

**Comment by WBerredo** [comment]
Adding the products to the Marketplace products endpoint (/marketplace/products): D77216-code

**Comment by WBerredo** [comment]
The plugins were added as managed plugin and can already be purchased and installed.

Request: Add Min/Max Quantities and Product Vendors as Managed Plugins: p9o2xV-1YJ-p2
