### ISSUE TITLE
Marketplace: Feature additional plugins in Spotlight

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#61549]
We need to feature additional plugins in the Spotlight. Let's statically add Sensei Pro and feature it for Sensei users once launched. We can also feature it when Yoast is already installed.

See: https://github.com/Automattic/wp-calypso/pull/61185

We'll eventually be improving how we spotlight multiple plugins and cases using JITMS: https://github.com/Automattic/wp-calypso/issues/61492

**Comment by Rolilink** [comment]
🧵 p1646926976601659-slack-C029JEQRVRT
