### ISSUE TITLE
Seller experience: Change "start from scratch" destination to My Home.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61543]
The "start from scratch" destination on the intent screen goes to `/wp-admin`, which can be confusing as we generally funnel people to My Home. Let's set the destination to My Home for now for consistency's sake, and revisit later as to how to better use this link. Tracks events should _not_ be changed at all.

![image (1)](https://user-images.githubusercontent.com/349751/156018059-eda25b40-4698-4ecf-9fb8-918d20d4775f.png)

**Comment by sixhours** [comment]
Closed in #61585
