### ISSUE TITLE
Marketplace: add WooCommerce Pre-Orders

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#61548]
### Details
Prices can be found in the spreadsheet of next woo extensions, link in Pdh6GB-2Y-p2, see "a8c Plugin Punchlist" tab.
Documentation: PCYsg-AhH-p2

For the most part these steps need to be completed in order:

- [x] https://github.com/Automattic/wp-calypso/issues/61884
- [x] https://github.com/Automattic/wp-calypso/issues/61885
- [x] https://github.com/Automattic/wp-calypso/issues/61886
- [x] https://github.com/Automattic/wp-calypso/issues/61895
- [x] https://github.com/Automattic/wp-calypso/issues/61887
- [x] https://github.com/Automattic/wp-calypso/issues/61888
- [x] https://github.com/Automattic/wp-calypso/issues/61889
- [x] https://github.com/Automattic/wp-calypso/issues/61890
- [x] https://github.com/Automattic/wp-calypso/issues/61891
- [x] https://github.com/Automattic/wp-calypso/issues/61892
- [x] https://github.com/Automattic/wp-calypso/issues/61893

**Comment by allilevine** [comment]
@SaxonF 👋 We'll need an icon for this plugin as well.

**Comment by lsl** [comment]
edit: list updated in ticket

**Comment by SaxonF** [comment]
Some discussion here around using a generic Woo icon for Woo related plugins C029JEQRVRT/p1646709488402109

![woo-icon](https://user-images.githubusercontent.com/1072756/157172524-3c04677c-fa36-4e13-9209-4deac51a391b.png)

**Comment by lsl** [comment]
@vinimotaa Could you find me a higher res image? Looks ok on desktop but mobile is stretched and a bit blurred

![Screenshot_2022-03-14_17-58-58](https://user-images.githubusercontent.com/811776/158120695-49d62cf8-1d95-44b6-b39e-54c7c73ab70d.png)

**Comment by lsl** [comment]
@allilevine I broke this down into pretty small tasks geared towards onboarding, maybe @paulopmt1 or @lupus2k want to try adding a plugin to the marketplace?

In future I think we can break this up into some larger chunks but this is probably the level you need to go to for onboarding any devs who are new to the process.

**Comment by vinimotaa** [comment]
@lsl are we using PNGs or SVGs for those icons?

**Comment by lsl** [comment]
Either is fine, we used SVG for [sensei pro](https://wordpress.com/wp-content/lib/marketplace-images/sensei-pro.svg) (D76441-code), if required we can upload as part of https://github.com/Automattic/wp-calypso/issues/61889

**Comment by vinimotaa** [comment]
@lsl @paulopmt1

![woo_icon](https://user-images.githubusercontent.com/97929097/158908406-cf503fab-bc49-475d-9cc2-0270d63bf0cd.svg)

Hi both, sorry the dealy here - I'm on my own covering different things across teams. Find attached the SVG version of this logo. I think is a good practice if we could always (as much as we can) upload SVGs into the system so we don't have resolution loss. 

Let me know if that helps, and please shout if you need anything! :)

**Comment by lsl** [comment]
No worries, and thank you! We might end up with png in there for pre orders but I'll update both to svg in the later UPS commit. (using same image)

**Comment by paulopmt1** [comment]
Thanks, @vinimotaa! Fortunately @lsl, I was able to add it in the same review here: D77093-code

**Comment by lsl** [comment]
Shipped D77093-code, you'll now need a new diff (https://github.com/Automattic/wp-calypso/issues/61892) to move the add_product call out of the a11n flag check and do some final testing with a non a11n user. (https://github.com/Automattic/wp-calypso/issues/61893)

**Comment by lsl** [comment]
Shipped, tested non a11n purchase on prod with credits.
