### ISSUE TITLE
Limited Atomic: Remove legacy feature map

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#61542]
### Details

Remove the map of plans to features in `store-products-list.php`, `Store_Product_List::get_feature_list()`.

Let's start by moving `::get_site_specific_features_data()` away from using `::get_feature_list()`.

**Comment by mreishus** [comment]
~~D76177-code~~ (Deployed) ->  ~~D76198-code~~ (Deployed) -> ~~D76205-code~~ (Deployed) -> ~~D76135-code~~ (Deployed) -> ~~D76232-code~~ (Deployed)

Bonus: ~~D76202-code~~ (Deployed) and ~~D76233-code~~ (Deployed)
