### ISSUE TITLE
Site Snapshots: migrate sql engine to trino

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#61556]
# Description 
Some foundational work is needed to update the tool to run sql queries from https://trino.io/ 
For background p4qSXL-49o-p2 & p4qSXL-4jI-p2
Reach out to #data-engineering for any help getting started.

# Acceptance Criteria
- [x] migrate the tool from Impala to Trino p4qSXL-4jI-p2
- [x] end user experience will not change

# Dev Tasks & PRs
 - [x] D75898-code
 - [x] Mark the task as complete on p4qSXL-4jI-p2 after it's shipped
 
# Related
Automattic/ganon-issues#5

**Comment by p-jackson** [comment]
Approved D75898-code 

Added a task to remember to tick it off the list over at p4qSXL-4jI-p2
