### ISSUE TITLE
Seller experience: Open the store selection doc links in a new tab.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61552]
The doc links on this screen could open in a new tab, to allow the user an easy way back to their onboarding experience.

See: paYKcK-1jS-p2#comment-1196

![image-5](https://user-images.githubusercontent.com/349751/156072981-041d6dff-231f-4d01-adff-480cba6c4e4c.png)

**Comment by andres-blanco** [comment]
This is already happening. Nothing to do here :)

**Comment by andres-blanco** [comment]
![2022-03-02 14 34 08](https://user-images.githubusercontent.com/375980/156416586-950f4f85-7cea-4970-80ca-f36b9b76e096.gif)
