### ISSUE TITLE
Seller experience: The Jetpack connection screen introduces friction.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61551]
As mentioned by @ianstewart , the Woo flow can include a Jetpack connection screen that is confusing and could prompt bailing from the flow. 

![image-4](https://user-images.githubusercontent.com/349751/156072388-06074b55-ab15-44aa-8dad-853a9df0dda8.png)

To reproduce:

* Create a brand-new WordPress.com account but do *not* verify your email address.
* Go through the flow at `/start` to create a new site and choose the Woo-capable plan
* Select Sell at the intent step
* Select More power at the seller intent step
* You'll be put into the Woo onboarding flow
* Put in your address and business info
* Confirm the URL change
* You'll see the above interstitial.

See: paYKcK-1jS-p2#comment-1194
See: p1645135600149819-slack-C0Q664T29

**Comment by kwight** [comment]
@ianstewart was right: this screen only appears if the email hasn't yet been verified (I thought it would still appear regardless). The user is dropped at `/wp-admin/admin.php?page=wc-admin&from-calypso` if the email is verified.

The Woo flow is accessible basically at any time through the "WooCommerce" sidebar menu item, so sites may or may not have verified their email. If they've arrived at the Woo flow through seller experience, however, they very likely will not have verified their email. So, keeping in mind that any changes to the Woo flow itself have to be valid regardless of the site's age and status, there are three options I can see.

* Add a step (or a modal?) to the Woo flow before they get forwarded to WC Admin that lets the user know to go and verify their email "for the smoothest experience".
* Add a notice (or modal? 🙃 ) at the store selection step, so that before sending the user to the Woo flow, we prompt them to verify their email (again, for the smoothest experience).
* Somehow remove the need for email verification. This is, I think, a terrible idea: we would be opening up a special-case hole in the entire auth process that we rely on (not even sure if we'd be able to technically do it from a Jetpack SSO point of view).

Hm, looking further, number 1 looks like a not-great idea too. If an email is unverified, the WooP flow in the sidebar menu is blocked, prompting the user to verify (so adding more email verification handling within the flow itself seems silly):

<img width="1531" alt="Screen Shot 2022-03-03 at 2 03 46 PM" src="https://user-images.githubusercontent.com/349751/156660703-f34a0a31-1a3e-42b8-b5aa-9a9a95bc1658.png">

I think #1 is the winner: let's add a notice similar to that above on the store selection page (blocking the "Upgrade" button until the email is verified).

@Automattic/serenity @SaxonF @obenland curious if anyone sees any better options.

**Comment by kwight** [comment]
Pinging @vinimotaa for design feedback in place of Saxon.

**Comment by vinimotaa** [comment]
Hi @kwight still trying to understand what is the challenge here - is there a place where I can get more context to this so I'll be able to support?

**Comment by blackjackkent** [comment]
As of today we will be holding off on this issue for next sprint in order to build it on top of the Stepper framework rather than write code that will need to be migrated anyway.

**Comment by vinimotaa** [comment]
Hi folks, 

will leave this link here where I started looking into a solution to this:
https://www.figma.com/file/DekZ88lDqG8Je04SyG1ZBK/Seller-Pathway?node-id=0%3A1

*this needs to be discussed and refined

**Comment by SaxonF** [comment]
@blackjackkent piggy backing off Vini's comment, I think one of the first things we could do is to make sure that the verify email link that is sent to the customer contains a redirect which takes them back to where they were previously. I don't believe this is the case right now but could be wrong. 

I'm also assuming this is more so related to plan upgrade (which triggers atomic) rather than Woo?

**Comment by blackjackkent** [comment]
> I'm also assuming this is more so related to plan upgrade (which triggers atomic) rather than Woo?

This is probably true.

> I think one of the first things we could do is to make sure that the verify email link that is sent to the customer contains a redirect which takes them back to where they were previously

Based on the investigation Caroline and I just did, if we follow the placement of that screen in Vini's design, the email shouldn't have to be updated, because it takes the user to My Home which is where we would be sending them anyway.
