### ISSUE TITLE
Export: Date filters for range exports are not properly internationalized

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#6156]
#### Steps to reproduce
1. Load https://horizon.wordpress.com/me/account.
2. Change your interface language to a language other than English.
3. Go back to a site and then Settings -> Export
4. Click the down arrow to the right of the Export button to expand selection form controls.
5. Choose posts or pages.
6. Click one of the date selectors.
#### What I expected

The month/year display should be localized.
#### What happened instead

I see dates in English date formats.
#### Browser / OS version

All
#### Screenshot / Video

![export-date-i18n](https://cloud.githubusercontent.com/assets/2738252/16206365/1b9587bc-36f6-11e6-9bb6-fdd300a63b46.gif)

I believe we may need to fix this in the REST API, in which we're using `date_i18n( 'M Y' )` to internationalize these strings, rather than in the client, but I prefer reporting it here to reporting it in an internal issue tracker.

Cc @yoavf @hewsut for feedback on whether we're just doing it wrong in the REST API and how we might improve the approach.

**Comment by yoavf** [comment]
Discussion recap: client request needs `withLocale()` added, but REST API needs some updates as well.
