### ISSUE TITLE
Marketplace: provision monthly Yoast premium plans

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61563]
We will have to enhance `WPCOM_Marketplace_Yoast_Premium_Plan_Manager` so that it supports two variations depending on the billing interval the user has selected for their subscription. Currently it supports only annual plans.

`productCode`:
Annual : `Yoast SEO Premium + Academy`
Monthly: `Yoast SEO Premium (monthly)`

Related convo: pcSRhZ-1Q-p2#comment-63
Swagger API documentation: pcSRhZ-Y-p2

**Comment by JulianBustamante** [comment]
Diff created D75976-code

**Comment by JulianBustamante** [comment]
Deployed r241914-wpcom
