### ISSUE TITLE
Uploading images into a Gallery block results in duplicates

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#61578]
### Quick summary

Images can be uploaded into a Gallery block in two ways: using the "Upload" button or drag-and-dropping from a folder on your computer.

Both options, at times, seem to result in images becoming duplicated during the uploading process at random.

### Steps to reproduce

1. Create a new post or page
2. Add a Gallery block
3. Upload multiple images at once to the block – this can be done using the "Upload" button or drag and dropping multiple files at once (**not** one at a time).
4. Watch the gallery as the images upload

### What you expected to happen

The uploaded images should populate into the gallery once each.

### What actually happened

In my tests, it seems that some of the first images to upload are randomly highlighted as if I've selected them, and then as other images upload, the selected images are "overwritten" by the new uploads.

Checking the Code Editor confirms that these are _identical_ image files/IDs, not multiple copies of the same image file being uploaded.

Screen recording of the issue (oddities start at about 1:20):

https://user-images.githubusercontent.com/5630717/156233515-014c86cf-bcf8-4125-90db-bdbba4100104.mp4

### Context

34442492-hc / 4823165-zen (**User has requested a follow-up when this is resolved**)

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Selecting images from the media gallery isn't affected, so it should still be possible to upload the images to the media gallery directly and then select them in the Gallery block.

If images are bulk-uploaded to a Gallery, you can edit the Gallery to deselect the duplicate (may need to deselect multiple times) and then select the other images that need to be added in their place.

**Comment by kimerlin81** [comment]
@jp-imagines  Thanks for submitting this detailed report!

This issue has been triaged as I was able to reproduce this behavior on a Simple test site several times.
The number of images uploaded does not seem to matter as duplication happened when as little as 3 images were added.
Not theme-specific either.

**Comment by wpshellbelle** [comment]
Another report at 10224999-hc

**Comment by sharonlaker19** [comment]
+1 at 4875773-zen
suggested workaround for now

**Comment by kdevnel** [comment]
Confirmed another in 4898166-zd-woothemes
Workaround shared

**Comment by tvolpert** [comment]
Another report here 13494298-hc; I gave them the workaround

**Comment by danielbachhuber** [comment]
Thanks for the reports, everyone.

It seems like this was fixed in Gutenberg 12.9. [Here's a similar report](https://github.com/WordPress/gutenberg/issues/39847) and [here's the fix for that report](https://github.com/WordPress/gutenberg/pull/39269).

I wasn't able to reproduce the bug on my Simple site:

https://user-images.githubusercontent.com/36432/178492163-ac1cc1ed-5f6b-4aac-8947-c6bce7c278b4.mp4

Closing for now, but feel free to re-open if you receive a new report.
