### ISSUE TITLE
They would like to hide pages like upgrade.php, readme.html, license.txt

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#61594]
### What

User
 would like to hide pages like upgrade.php, readme.html, license.txt

### Why

User thinks this is insecure. There were some more requests like that described in At. P2

**Comment by kerrynicl** [comment]
Hi There @daria2303  Would you mind sharing a few links to the p2 posts / user interaction?

**Comment by daria2303** [comment]
Sure, here is the interaction 34451684-hc
I didn't P2 it as I found 
p1642432008136400-slack-C03TY6J1A
p9F6qB-7v9-p2
and assumed this is not available.

**Comment by inaikem** [comment]
Thank you, @daria2303. I'm marking this as closed for now.
