### ISSUE TITLE
Plugin Upload: Uploading large plugins fails

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#61609]
### Quick summary

Users may encounter `We're sorry, but an unexpected error has occurred` when manually uploading larger plugins.

Seems that the marketplace plugin installer at https://wordpress.com/marketplace/install/ runs into issues when dealing with larger .ZIP files.

The marketplace uploader is hitting a server file size limit when users attempt to upload larger plugins.

We're responding with a 413 for requests like this one:

* POST to https://public-api.wordpress.com/rest/v1.1/sites/XXXX/plugins/new?http_envelope=1
* 33.9 MB .zip file

Left an internal note with Bespin, p1646165376325499-slack-C02JPCHEKDY

This issue is being opened in place of https://github.com/Automattic/wp-calypso/issues/60748 -- as that report was originally for a separate issue that has been resolved. 

### Steps to reproduce

1. Navigate to My Site > Plugins > Upload
2. Attempt to upload a larger plugin. Example:  The 33.9 MB Astra Premium Sites plugin .zip.

### What you expected to happen

Plugin to upload.

### What actually happened

Request is 413'd

![image](https://user-images.githubusercontent.com/4887830/156408427-d694ab65-2677-493c-9b26-66c8713e7f13.png)

### Context

p1646162323784859-slack-C03TY6J1A

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

User can upload plugins by going directly to `/wp-admin/plugin-install.php`

Or, HE an can have user upload file to their media library and force install the plugin via WP-CLI via `plugin install URL-TO-FILE --force` 

The `--force` is generally optional if the plugin hasn't been installed before.

**Comment by gcsecsey** [comment]
Based on the backlog grooming session:
- Let's find the limit and increase it (eg. 100MBs)
- Only apply this higher limit on the `sites/XXX/plugins/new` endpoint

**Comment by WBerredo** [comment]
A System Request was opened to increase the limit. Increase size limit on POST /sites/%s/plugins/new: pMz3w-eRU-p2

On Calypso, we'll show an option to go to WP Admin when the user tries to upload a plugin bigger than the limit. #62022
