### ISSUE TITLE
Social Icons Block: Difficult to add additional icons

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#61612]
### Quick summary

Based on [what we have documented here as the expected experience using this block](https://wordpress.com/support/wordpress-editor/blocks/social-links-block/#add-new-icons), it seems like there is a bug preventing the + icon to show in the editor canvas when adding a new social icon, which makes you have to go back up one level to the Social Icons block, so that the + icon will appear to select a new icon to insert.

### Steps to reproduce

1. With a block theme, start at the site editor
2. Add a social icons block somewhere in the editor canvas
3. Add a social icon
4. Look for the + icon to add more social icons

### What you expected to happen

For the + to be showing always.

### What actually happened

it only shows if your focus point is the parent Social Icons block, not a child social icon added.

### Available workarounds?

Yes, easy to implement

### Workaround details

Click the parent social icons block and the + comes back up.

**Comment by Greatdane** [comment]
This behavior is consistent with other blocks across Gutenberg, so I am not sure its a bug. For example, you have to click on the parent block when adding an image to the Gallery block, or adding another field to a Form Block. 

I have also tested this on all platforms (Simple, Atomic and self-hosted) and non FSE themes. 

Closing this for now, but we could add this suggestion as a feature request in core Gutenberg for all blocks.
