### ISSUE TITLE
Marketplace: Sign up flow for 3pd (partners)

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61617]
Let's try enhancing / reusing the WooCommerce.com partners onboarding flow. 

- [ ] The flow should also contain a checkbox for accepting the WP.com Marketplace Vendor terms which can be published in P2gHKz-oRE-p2
- [ ] The content of the terms accepted by each vendor should be saved somewhere for future reference (pdh6GB-7N-p2#comment-1149)
- [ ] The flow should contain a vendor registration form for Tipalti (pdh6GB-7N-p2#comment-1077) for receiving the payments. The Tipalti vendor ID should be saved in a (new) column in `store_vendors` wpcom table (p6VJlg-1pK-p2#comment-3181)

Related convo: pdh6GB-7N-p2#comment-874

**Comment by allilevine** [comment]
@cpapazoglou Is this required for an MVP?

> The flow should contain a vendor registration form for Tipalti (pdh6GB-7N-p2#comment-1077) for receiving the payments. The Tipalti vendor ID should be saved in a (new) column in store_vendors wpcom table (p6VJlg-1pK-p2#comment-3181)

**Comment by cpapazoglou** [comment]
No @allilevine  it's not required for an MVP. It can become a blocker when vendors request their payout.

**Comment by cpapazoglou** [comment]
> The flow should contain a vendor registration form for Tipalti (pdh6GB-7N-p2#comment-1077) for receiving the payments. The Tipalti vendor ID should be saved in a (new) column in store_vendors wpcom table (p6VJlg-1pK-p2#comment-3181)

Since the vendor registration form for Tipalti might make the vendors drop off before completing sign-up, we can move the whole step after the registration or even after the product submission launch.
