### ISSUE TITLE
FSE: Options to have Sticky/Transparent Header

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#61622]
### What

The FSE Header template does not seem to have an option to make it sticky/fixed to the top. Or to make it transparent when at the top.

Example of earlier WordPress.com theme with Fixed Menu option-
https://twentyseventeendemo.wordpress.com/
https://shoreditchdemo.wordpress.com/

Example of a theme with transparent Header which becomes opaque on scrolling-
https://www.ravin.ai/

### Why

Well, these are nice to have layout enhancements for a user to make the site more beautiful. These options are readily available on third-party themes.

**Comment by jordesign** [comment]
This is an excellent Feature Request - good news is we have an open request (with some work on it in progress in the Gutenberg repo)
https://github.com/WordPress/gutenberg/issues/30121
