### ISSUE TITLE
FSE: Need a Spacer Block to add Horizontal space in Row block

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#61623]
### What

Just as we use Spacer block to add extra space (height) in the regular flow of blocks, I am requesting a Spacer block that would also help add space horizontally (width).

Spacer block- https://wordpress.com/support/wordpress-editor/blocks/spacer-block/ 

### Why

The use case for the horizontal space between blocks comes into the picture when we consider the Row block and its usage in the Header template in FSE.

To add more space between two blocks inside a row block, there is currently nothing that can be used other than an empty paragraph block.

**Comment by jordesign** [comment]
@ahmadbaig1  is this the kind of thing you mean?
https://github.com/WordPress/gutenberg/issues/38022

**Comment by ahmadbaig1** [comment]
Kind of yes. This [#38022](https://github.com/WordPress/gutenberg/issues/38022) achieves a similar/better result than what I am requesting! However, it is a different thing :) 
What I am looking for is just a spacer block with horizontal spacing capability that could add mandatory space between two blocks inside a Row block, if needed.

**Comment by jordesign** [comment]
OK cool - that being the case, I've just opened a Feature REquest on the Gutenberg repo for this :) Thanks for reporting!

https://github.com/WordPress/gutenberg/issues/39206
