### ISSUE TITLE
Only on Editor view: Label for the Radio block within the Form block is smaller than other block labels

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#61630]
### Quick summary

For a `Form` block, add a `Radio` block within it and you can see that its label font size is smaller than the rest of the form block labels. This happens only on the editor view.

### Steps to reproduce

- Add a `Form` block to any page. (any theme will do)
- Add a `Radio` block within that form block.
- See that its label size is smaller than the rest of the form block labels.

### What you expected to happen

The label size matches the rest of the form block labels. Also that the radio block label size matches what we see on preview/live site.

### What actually happened

Difference in label font size. Compare "Phone number" and "I will attend on" below:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/18581859/156491252-8816471a-a51f-4eca-9b21-fa58211c5747.png">

Live page is fine:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/18581859/156491326-1970fed8-ff28-4c75-9288-1bc6b274f17f.png">

### Context

User report: 4820668-zen.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Not a theme-specific issue as far as I can tell. These are some themes I tested:

| Theme | Image |
|------|------| 
|Hari|<img width="779" alt="image" src="https://user-images.githubusercontent.com/18581859/156491252-8816471a-a51f-4eca-9b21-fa58211c5747.png">|
|Barnsbury|<img width="773" alt="image" src="https://user-images.githubusercontent.com/18581859/156491555-8b900e1f-cc04-40fa-a6f0-8ff0ee53277f.png">|
|Marl|<img width="739" alt="image" src="https://user-images.githubusercontent.com/18581859/156491591-43ad2b9b-fb79-47c1-9901-3e8afaa7d527.png">|

### Browser, operating system and other notes

- Firefox.
- Mac OS.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by arunsathiya** [comment]
Some notes:

- I am assigning a low priority because it's affecting only the editor view.
- I think this can be moved to Jetpack repository because Form block comes from it? I am not too sure though because this is on Calypso at the moment: Automattic/jetpack#23437

**Comment by formosattic** [comment]
Thanks @arunsathiya  for the extra notes.

I was able to reproduce it on self-hosted. Closing this in favor of the bug you linked and will transfer to Jetpack.

![image1](https://user-images.githubusercontent.com/15944096/158331660-d9742831-3b78-4775-b4c3-1178e6052b4f.png)
