### ISSUE TITLE
Product short descriptions need translating

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61632]
Probably just need wrapping in translation functions but not sure on the context these are used, hopefully user context. 

A fix is out of scope for this issue but lets check if the descriptions pulled from wccom can be translated too, will need to rework the caching if so so create new issues to suit.

See `short_descriptions` entries in `class-marketplace-product-catalog.php`

**Comment by cpapazoglou** [comment]
Content translations will be delivered from the Woo Integration. We have already tackled [Marketplace: Support retrieving product presentation page translations from the WooCommerce.com API](12388-gh-Automattic/woocommerce.com) so that we can retrieve them. I think we can close this.
