### ISSUE TITLE
Site Editor - Update help link to use WPcom docs.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#61648]
The help link in the Site Editor currently takes users to the core documentation: https://wordpress.org/support/article/site-editor/

We should update this to send users to our WPcom documentation: https://wordpress.com/support/site-editor/ 

We should ensure this is handled gracefully, and add a filter or slot to override in Gutenberg if necessary.

![image](https://user-images.githubusercontent.com/28742426/156632893-7f30d43b-c74f-4267-abb9-ae36feefde10.png)

**Comment by jeyip** [comment]
Planning to work on this with @vykes-mac during his onboarding
