### ISSUE TITLE
WooCommerce Cart Icon Disappears from the Menu in all FSE Themes

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#61660]
### Quick summary

The WooCommerce shopping cart icon does not appear in the menu if an FSE theme is active. 

With Hever active:
<img width="530" alt="Screen Shot 2022-03-04 at 10 19 49 AM" src="https://user-images.githubusercontent.com/12906034/156790221-53698abe-b5f4-4e87-9410-5098535d9d2e.png">

With Attar active:
<img width="394" alt="Screen Shot 2022-03-04 at 10 20 11 AM" src="https://user-images.githubusercontent.com/12906034/156790261-ce639745-40a1-4584-bfc2-07ff8160cd8a.png">

### Steps to reproduce

1. Create a site and install a non-FSE theme (example: Hever)
2. Install the WooCommerce plugin and set up the shop/
3. Add all WooCommerce pages to the menu.
4. Observe that the shopping cart icon appears in the menu.
5. Switch to an FSE theme (example: Attar)
6. Observe that the shopping cart icon disappears.

### What you expected to happen

The shopping cart icon should remain when switching to an FSE theme.

### What actually happened

The shopping cart icon disappears.

### Context

Customer report: 34492453-hc

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

This issue is related to all FSE themes.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

There's no workaround that I was able to find other than switching to a non-FSE theme.

**Comment by masperber** [comment]
Opened followup ticket with customer so that we can let them know when this is resolved: 4831752-zen

**Comment by Robertght** [comment]
Thank you for the report, @masperber !

This is not a theme limitation because there is a need for an additional block from WooCommerce in order to the cart displayed:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4138

@Aljullu are there further updates on the Mini Cart block?

**Comment by Aljullu** [comment]
> @Aljullu are there further updates on the Mini Cart block?

We are currently targeting WC Blocks 7.3.0 and WC core 6.5.0 for public release. That's March 21st in WC Blocks and May 10th in WC core.

**Comment by Robertght** [comment]
This shouldn't be an issue anymore so I'm closing it.

Ref: https://woocommerce.com/document/mini-cart/

**Comment by csabarakasz** [comment]
user looking for this: 

- [x] 36994590-hc

Told them to use https://woocommerce.com/document/mini-cart-for-woocommerce/ Thanks.
