### ISSUE TITLE
Atomic: Permalinks Option Missing from `Settings` in Unified Nav

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#61675]
### Quick summary

There is no way to access the Permalink options page `/wp-admin/options-permalink.php` via Unified Nav on WordPress.com

Accessing the URL to the permalinks option page directly still works.

### Steps to reproduce

1. Open an Atomic Site
2. Go hover or click on the `Settings` option
3. `Permalinks` is not included in the list of pages to navigate to

### What you expected to happen

There should be a link to the permalink options page in `wp-admin/options-permalink.php` 

### What actually happened

The link is missing.

<img width="1427" alt="Screen Shot 2022-03-05 at 8 43 28 AM" src="https://user-images.githubusercontent.com/12505355/156893150-d80b4a69-8b65-423f-8d55-e44fe071289f.png">

### Context

This was reported by a customer  in 4834060-zen and was replicable in test Atomic sites. 

I tried to get the Permalink setting back on my Atomic site with the following
- Turning off SSO and logging in WP Admin directly
- Changing from an FSE theme to TwentyNineteen
- Deactivating all plugins, including Jetpack and Full Site Editing inidividually
- Logging in via an incognito browser
- Clearing the site cache

None of these have worked. I checked with colleagues and have mixed results of being able to see the Permalinks in their settings section. 
- One using WP 5.9 on a self-hosted site said they could see it
- One using WP 5.9 on a Pressable site said they couldn't
- One report of still seeing Permalinks on an AT site when logged into WP Admin

Possibly related were reports of menu items missing from the `Appearance` section

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

I was using Mac OS 12.2 with Chrome 98

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Providing the user with the direct URL to the options page gives them access:
`https://EXAMPLE.COM/wp-admin/options-permalink.php`

**Comment by tvolpert** [comment]
I'm not sure if these are related or not, but I have two cases of other menu items going missing from the sidebar. I tried all the same troubleshooting steps as described above, except for SSO on the simple site. 

- This user is missing `Menus` from under `Appearance` 4832859-zen
  - this one is a simple site,  for what that's worth
- one of [my own test sites](https://timothyvolpert.wpcomstaging.com/) is missing `Additional CSS` from `Appearance`

**Comment by rw-ye** [comment]
Another report here: 4835242-zd-woothemes

My AT test sites also do not have `Permalinks` displayed in the `Settings`.

**Comment by formosattic** [comment]
This seems to affect recent sites?

I notice the Permalinks link is missing from my recent atomic test sites, but not on the older ones.

The Permalink doesn't come up even after switching to Classic View.

**Comment by dolgelukkig** [comment]
Another report here: 34532688-hc

The user is not seeing the item in their menu, and when I shared the direct link they didn't have access to the page.

**Comment by kylemcph** [comment]
Another report here: 4838048-zen

Sent the direct link workaround.

**Comment by arinoch** [comment]
Another report. 4840289-zd-woothemes

Direct link sent.

**Comment by JoshuaGoode** [comment]
Likely related to limited Atomic adjustments

833-gh-Automattic/wpcomsh 

Dropped a line internally, p1646753970870009-slack-C02V49GM0PN

**Comment by mmtr** [comment]
It should be fixed once the new version of `wpcomsh` is deployed to Atomic sites.

**Comment by JoshuaGoode** [comment]
#### Recap

Tested and confirmed this is now resolved via script completion, D76265-code.

Impacted users can now manage their footer, CSS, and permalinks as expected.  Ready for emails to waiting users.

**Internal context**
Related to limited Atomic work

p1646753970870009-slack-C02V49GM0PN

**Related issues now resolved** 
https://github.com/Automattic/wp-calypso/issues/61486 - 814-gh-Automattic/wpcomsh
https://github.com/Automattic/wp-calypso/issues/61738 - 833-gh-Automattic/wpcomsh
https://github.com/Automattic/wp-calypso/issues/61675 - 835-gh-Automattic/wpcomsh

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
