### ISSUE TITLE
Plans: checkout doesn't load if item is in cart pre-signup

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#6167]
When signing up from an "upgrade" call to action, like "Start with Premium" or "Start with Business," the plan is added to the user's cart so that they are not presented the `plans` step in signup. After the user registration and site setup is complete, users with paid upgrades in their carts get taken to checkout. In the last day, this flow has broken for users with something in their cart pre-signup.

video of issue: https://cloudup.com/c0MKdK94vTC

#### Steps to reproduce
1. Starting at URL: wordpress.com/create
2. Click "start with premium" or "start with business" to add plan to cart and start signup
3. Complete signup
4. Click "continue" on the post-signup processing screen to go to checkout
5. Notice that checkout placeholder loads then you're quickly taken to the /plans page instead
6. After some time or after a refresh, notice that 1 item is in your cart

#### Expected behavior
After signup post-processing screen ("Continue"), user should be taken to checkout to complete plan purchase.

Looking through the GH history, it appears that a few updates were made to plans by @gwwar & @lamosty in https://github.com/Automattic/wp-calypso/pull/6002. I am not savvy enough to know if that's the culprit, but it would be worth a look ASAP.

cc @bisko

**Comment by bisko** [comment]
Fixed in #6170.
