### ISSUE TITLE
Themes: Theme type select list isn't usable until all themes have loaded

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#6168]
cc: @hoverduck 
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/
2. As the themes are loading, try to use the theme type select list to choose "Free" or "Premium"
#### What I expected

Should be able to select "Free" or "Premium"
#### What happened instead

Select list is unusable until every theme has loaded
#### Browser / OS version

Chrome OSX Latest
#### Screenshot / Video

![themeselect](https://cloud.githubusercontent.com/assets/128826/16219623/fbc30916-37ca-11e6-8d34-b5f5253a4a69.gif)
#### Context / Source

 #dogfooding #automated-testing

**Comment by folletto** [comment]
I assigned this to the `M5-MagicSearch` milestone since we are going to rewrite the search bar entirely then.
