### ISSUE TITLE
Arbutus Theme Footer Credit Block not Appearing.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#61682]
### Quick summary

On Atomic sites with Arbutus and FSE, the footer credit block doesn't appear to remove it. It will either be removed if the footer credit was off, or will be there.

Even if it is removed from customizer, the space where the credit would be still shows up on the site.

### Steps to reproduce

1. Start an Atomic site with FSE and the Arbutus theme.
2. In the site editor, check the footer section, the footer credit will not be there.
3. On the live site, the footer credit will appear, but it can only be removed with CSS.

### What you expected to happen

The footer credit should be available in the site editor to be removed.

### What actually happened

The footer credit does not appear, and even if removed in Customizer.php, a white line will remain where the footer credit was:
<img width="1255" alt="Screen Shot 2022-03-06 at 1 00 16 PM" src="https://user-images.githubusercontent.com/49131029/156940005-6d6594fe-e2c1-4869-ac2e-64836c867f0b.png">
 

### Context

4832578-zd

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Arbutus

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

This CSS can be used to remove the area, but it's not ideal as it might end up unintentionally hiding other blocks:

```
.page .wp-site-blocks > div:last-child {
  display:none;
}
```

**Comment by Robertght** [comment]
Hey @KirkwallDay ! Thank you for reporting this. I tested this on the users's site and it appears they've chosen a different path.

Do you remember which was the footer template part/structure used in that test?

**Comment by KirkwallDay** [comment]
Hi @Robertght , it happens on my test site as well, using the Footer Template Part.  I just made a test footer and the white space still appears below:
<img width="988" alt="Screen Shot 2022-03-09 at 3 31 53 PM" src="https://user-images.githubusercontent.com/49131029/157549888-084d36ee-18f0-46fb-8337-08d5945b7942.png">

When I check the HTML source, it shows up as a blank paragraph block with an empty link but this blank block doesn't show up anywhere in the site editor or footer template part:
<img width="1015" alt="Screen Shot 2022-03-09 at 3 32 20 PM" src="https://user-images.githubusercontent.com/49131029/157549998-a9f49407-8c4c-4b51-86a9-ab5c49dcfc62.png">

**Comment by Robertght** [comment]
I'm still unable to replicate this and I don't see any other reports.

I'll close this one for now, but if there are other reports, please reopen the issue.
