### ISSUE TITLE
Navigation block: Add option to customize text and set Typography settings for Overlay Menu text and icon

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#61689]
### What

Currently there is no option to edit the text or format the text of "Menu" that is used for the Overlay Menu on the Navigation Block as shown here:

![CleanShot 2022-03-07 at 12 27 53](https://user-images.githubusercontent.com/51966986/157034643-5f735dd7-d596-4742-91ad-ed02c5185668.png)

### Why

The text formatting for the overlay menu often needs to be adjusted to stand out and be more readable depending on the context. Additionally, it would be better if the text "Menu" could be customized with a custom text label.

### How

The overlay menu could have its own section within the Navigation block and have its own Typography options.

**Comment by kerrynicl** [comment]
@philnick206  This type of customization can be done from the block settings so I'll be closing this feature request for now but feel free to reopen if there is a specific detail you would like to highlight 
<img width="1899" alt="Markup 2022-03-09 at 10 54 37" src="https://user-images.githubusercontent.com/83325600/157478791-59b7a21d-c86b-4a05-9df7-b6d224a91166.png">
