### ISSUE TITLE
Menu navigation links for drafted pages show up in the Beta Editor and create confusion for some users. 

### ISSUE THREAD

**Issue by saraita-git** [Automattic/wp-calypso#61686]
### Quick summary

Menu navigation links for drafted pages show up in the Beta editor. This can be a bit confusing for the user, that in most cases, they expect to see what they see in the Beta editor on their website. 

### Steps to reproduce

1. Publish a page.
2. Create a primary menu in Customizer, selecting the created page.
3. Go to Appearance - Editor Beta.
4. Add a navigation block and select your primary menu. 
5. Switch the published page to a draft. 
6. See that the page will show in the Beta Editor navigation, but not on your site. 

### What you expected to happen

I would expect the Beta Editor to reflect what it will be shown on my website. 
I would expect not to see the drafted page in the Beta Editor navigation in this specific case, or there can be clearly shown that they are drafted, so they will need to publish them to show them on the website. 

### What actually happened

I can see the drafted page in the Beta Editor navigation, but not on my website:

https://d.pr/i/HTLvFA

### Context

Related Slack Convo: p1646643672866919-slack-C03TY6J1A

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Available workarounds?

There is no user impact

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – not reproduced
Tested on Atomic – not reproduced
Replicable outside of Dotcom – 

📌 FINDINGS/SCREENSHOTS/VIDEO
**Simple**
1. published page (`Some Page`) and added to the navigation link.
<img width="1361" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/4e88b7b3-9c7b-45e2-9ce3-7b94b62455ed">

2. after unpublishing the `Some Page` page.
<img width="1235" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/d8b3caf9-e328-4a88-ac2d-cf94f635252e">

**AT** 
1. published page (`Some Page`) added to navigation link.
<img width="692" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/b884becb-bb04-4c62-a9ce-18fd5017b9dd">

2. after unpublishing the page.
<img width="590" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/268a42f7-87d5-49f3-b8f7-0e72f492b882">


📌 ACTIONS
- close issue as Not Reproducible.

If you disagree, please feel free to reopen and leave a comment with updated steps to reproduce with screencaps and/or a video!
