### ISSUE TITLE
Email Templates: Add Site icon to the new template header (all emails)

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#61694]
### Details

The goal is to add Site icon to all the following emails:
- Confirmation Request (sent to the subscriber - asking them to confirm the subscription)
- Subscriber Welcome (sent to the subscriber that just subscribed)
- New Post
- New Comment
- Liked Comment
- Liked Post
- New WP.com Follower (sent to the site owner)

If the Site icon isn't set, the default WordPress.com / Jetpack icon should be used instead.

### Related

- Project thread: pdDOJh-99-p2

**Comment by ivan-ottinger** [comment]
Initial patch (work in progress): D76230-code.

**Comment by ivan-ottinger** [comment]
Updated the issue description.

**Comment by ivan-ottinger** [comment]
Changes divided into multiple patches. The initial patch is ready for review: D76667-code.

**Comment by yansern** [comment]
Once D77150-code is reviewed & merged this issue can be closed.

**Comment by ivan-ottinger** [comment]
The Site icon is now displayed in all emails (new template). → Closing this issue.
