### ISSUE TITLE
Email Templates: Add "reply-by-email" nudge (New Post & New Comment emails)

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#61697]
### Details

Current "New Post" and "New Comment" notification emails include the following nudge:

![Markup on 2022-03-09 at 11:53:52](https://user-images.githubusercontent.com/25105483/157427769-9b6886f8-113d-4093-89eb-b272b20e8635.png)

It would be great to have similar information in the new email template, e.g.:

![Markup on 2022-03-09 at 11:47:39](https://user-images.githubusercontent.com/25105483/157427050-879d84d1-b90d-44d1-9fe1-6104e5df270a.png)

### Related

- Project thread: pdDOJh-99-p2
- Related discussion: pdgv5Y-lA-p2#comment-139

**Comment by ivan-ottinger** [comment]
Updated the issue description and started investigating.

**Comment by ivan-ottinger** [comment]
Initial patch (work in progress): D76349-code.

**Comment by ivan-ottinger** [comment]
Asked for the cool lightbulb icon: pdgv5Y-lA-p2#comment-159 so we can use it in the email template.

**Comment by ivan-ottinger** [comment]
Patch ready for review: D76349-code.

**Comment by yansern** [comment]
Completed.
