### ISSUE TITLE
[New Post] Account for cases where the author doesn’t have an avatar set.

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#61699]
### Details

Details to be added.

**Comment by ivan-ottinger** [comment]
I have tested a couple of scenarios and when the user doesn't have custom avatar set, the automatically-generated one is used instead. But this has nothing to do with the email templates:

| New post | New comment | New like |
| ------------- | ------------- | ------------- |
| ![Markup on 2022-03-16 at 11:21:41](https://user-images.githubusercontent.com/25105483/158571169-d2ac7424-f43e-4043-9211-bcd5c437f9f2.png) | ![Markup on 2022-03-16 at 11:24:02](https://user-images.githubusercontent.com/25105483/158571185-0f617830-2c00-4853-822a-ba83eaaadb04.png) | ![Markup on 2022-03-16 at 11:25:48](https://user-images.githubusercontent.com/25105483/158571189-b1d23816-cb0d-4bd1-91c0-cf835200f578.png) |

@yansern @mashikag Do you know about any other case where the missing avatar could be an issue? 🤔 

Btw, I have reviewed the related P2 posts as well:
- pdgv5Y-hH-p2
- pdgv5Y-lA-p2

**Comment by yansern** [comment]
The old e-mail template uses `get_avatar()`, whereas the new e-mail template uses `wpcom_get_avatar_url()`. Looking at `get_avatar()`, there isn't any fallback mechanism in place.

`Subscription_Mailer` class uses `wpcom_get_avatar_url()` and doesn't pass anything to the `default` param. When the `default` param is empty, it will fallback to the value `identicon`, which renders this quilt-like icon.

Closing this issue as this is already solved in new email template.

**Comment by ivan-ottinger** [comment]
Thank you for digging into this!
