### ISSUE TITLE
[New Subscriber] Include link within the copy to the subscriber's site if they are a WP.com user.

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#61696]
### Details

Details to be added.

This is how the new email template looks like before any changes as part of this ticket are made:
![Screenshot 2022-03-21 at 19 30 51](https://user-images.githubusercontent.com/2019970/159340525-c7bd2593-f883-4676-83b5-343874975b9e.png)
Important to mention that the current implementation uses one email template for both WP and non-WP users. As per the designs the final goal is to have two different emails for both cases.

### Checklist

> You might want to go see what they're up to! Perhaps you will like their blog as much as they liked yours.

- [x] Display the above paragraph in the "new subscriber" email **only if** the new subscriber is wp.com user and they have at least one blog.
- [x] `their blog` in the above paragraph should be a hyperlink to the subscriber's wp.com site

### Related

Design @ p58i-c0s-p2#new-email-follower-non-wp-com-user

Phab patch: D77351-code

**Comment by yansern** [comment]
What is **subscriber site** here?

**Comment by mashikag** [comment]
> What is **subscriber site** here?

The subscriber in this context refers to wp.com user who has just subscribed to your site.

Then the subscriber site is one of the subscriber's wp.com sites. 

I had a brief look at what is there in the old templates (the currently released ones). There was no such paragraph in the email's content. I will need to figure out how to access the subscriber's site.

When it comes to edge cases I make my own assumptions here. 
1. When subscriber is wp.com user but has no site, we shall not include the paragraph in the email.
2. When subscriber is wp.com user but has more than one **published** site, we shall pick a random one from a list of their published sites.

**Comment by yansern** [comment]
> I will need to figure out how to access the subscriber's site.

You can try `get_blogs_of_user()`. https://developer.wordpress.org/reference/functions/get_blogs_of_user/

> When subscriber is wp.com user but has more than one published site, we shall pick a random one from a list of their published sites.

You can look at how `choose_primary_blog()` works (this returns HTML though), seems it is getting the value from the `primary_blog` user meta. https://developer.wordpress.org/reference/functions/choose_primary_blog/

**Comment by yansern** [comment]
Renamed the issue title from "subscriber site" to "subscriber's site" for clarity.

**Comment by mashikag** [comment]
The related phab patch is D77351-code
