### ISSUE TITLE
[Bug]: Different patterns in pattern library depending upon url

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#61709]
### Quick summary

I've got a bunch of sites that use wp-admin for the posts page, rather than Calypso. When I follow the menu links to create a new post it goes to https://EXAMPLE.wordpress.com/wp-admin/post-new.php?post_type=post&calypsoify=1 and I get a small number of patterns.

If I change the view option to use calypso then a new post will go to https://wordpress.com/post/EXAMPLE.wordpress.com and I have a large number of patterns.

Interestingly, when I switch the view option back again, I keep the large number of patterns, even on the same URL that was showing a small amount before.

### Steps to reproduce

1. ??? Have a site that uses wp-admin for the posts screens, that probably never has accessed the patterns library
2. Go to Posts -> Add new in the menu
3. Click on the big plus at the top of the screen
4. Choose 'Patterns'
5. Choose 'Explore'

### What you expected to happen

A big list of pattern categories including e.g simple product

### What actually happened

A short list of pattern categories, not including simple product

### Simple/Atomic

Simple, Atomic

### Other notes

See 
![image](https://user-images.githubusercontent.com/93301/157076808-25b82d40-1563-4ca7-9f5a-763045be873b.png)

The window on the left had the same categories as the window on the right until I changed the view options in the window on the right.

### Reproducibility

Intermittent - on some sites I can reproduce it every time, until I change the view options and then I can't reproduce it again.

### Available workarounds?

Yes, easy to implement

### Workaround details

1. Go to Posts in the menu
2. Choose 'View' from the top right drop down
3. Choose 'Default view'

It now works even if you switch back to 'Classic'

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
- On a couple different new sites (where patterns have not been accessed yet), I saw the same list of patterns whether I accessed them from from `https://SITE_ADDRESS/wp-admin/post-new.php` or `https://wordpress.com/post/SITE_ADDRESS`

Example: 

https://github.com/Automattic/wp-calypso/assets/27249804/a8c725cd-0bd7-4686-b2fa-87b713b0930c

📌 ACTIONS
- Closing as unable to replicate
