### ISSUE TITLE
Stow: Styles on Image block have no effect

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#61710]
### Quick summary

Applying different styles to images using the Image block options shows properly in editor but does not show on the live site.

![CleanShot 2022-03-07 at 16 51 28](https://user-images.githubusercontent.com/51966986/157080336-ab015785-e6eb-47ef-97da-7612c9da30af.png)

![CleanShot 2022-03-07 at 16 53 24](https://user-images.githubusercontent.com/51966986/157080369-e9a1b99c-9c75-461b-b46e-e8da8b138a7b.png)

### Steps to reproduce

1. Add an Image
2. Choose a style from the block options
3. Preview page/post

### What you expected to happen

Image should have the style showing on the page/post

### What actually happened

Image does not have the style showing on the page/post

### Context

#4838272-zen

### Theme-specific issue?

Stow

**Comment by Robertght** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/61725
