### ISSUE TITLE
Image block's rounded style settings does not display the rounded image in the front end when image alignment is specified

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#61725]
### Quick summary

On themes that were not built around block editor rounded image style is not visible in front-end when image alignment is specified in Image block toolbar.

### Steps to reproduce

1. Activate a theme such as Rowling or Morden or Lodestar.
2. Add an Image block and set alignment option in block toolbar.
3. In block settings under Styles select the Rounded option.
4. Preview the changes.

### What you expected to happen

To see the image with rounded corners.

### What actually happened

The image is displayed squared.
![image-aligmnet-is-specified](https://user-images.githubusercontent.com/1519466/157161423-82ab2ad9-aac2-4778-bdb4-635ff074320a.jpeg)

### Context

Screenshot
![ima-block-google-chrome-2022-03-07-14 24 28](https://user-images.githubusercontent.com/1519466/157161488-1ce278d8-9dad-448f-a038-cf58ea9e8adc.jpg)

4824904-zen
4836604-zen

### Theme-specific issue?

Rowling, Morden, Lodestar

### Browser, operating system and other notes

Themes: Rowling, Morden. No issues when using Blank Canvas theme.
OS: Windows 10 64-bit.
Browsers: Chrome Version 98.0.4758.102
Firefox: 97.0.2

### Available workarounds?

Yes, easy to implement

### Workaround details

Do **not** set image alignment in the Image block toolbar.

**Comment by Robertght** [comment]
Another case using  Button 2: 4836726-zen

And one with Colinear: 4835150-zen

**Comment by kuropixel** [comment]
Seeing this on Karuna theme. 4839846-zen

**Comment by Robertght** [comment]
GB core issue: https://github.com/WordPress/gutenberg/issues/39242

**Comment by philnick206** [comment]
I logged an issue for this yesterday that looks the same: https://github.com/Automattic/wp-calypso/issues/61710

Reported in #4838272-zen

**Comment by fashuvo** [comment]
Another report with Anemone theme: #4831831-zen

**Comment by Robertght** [comment]
4835944-zen

**Comment by kylemcph** [comment]
4832784-zen

Theme: Storefront Child

Workaround of removing image alignment worked.

**Comment by fashuvo** [comment]
Another report at #4837892-zen, Button 2 theme.

**Comment by fashuvo** [comment]
Another report at #4841574-zen, Sobe theme.

**Comment by glendaviesnz** [comment]
There is a potential fix for this here https://github.com/WordPress/gutenberg/pull/39295, and for those sites that can added custom css it can be fixed by adding the following in the meantime:

```css
.wp-block-image .is-style-rounded img{
	border-radius: 9999px;
}
```

**Comment by ezebecke** [comment]
#4761934-zd, intergalactic-2 theme

**Comment by glendaviesnz** [comment]
@happychait - it looks like this is fixed on simple sites now, and should be on atomic sites once Gutenberg 12.7.1 is deployed there.

**Comment by sanjeev00733** [comment]
Another report in #34558655-hc

**Comment by Robertght** [comment]
This has been fixed in the recent release https://github.com/WordPress/gutenberg/releases/tag/v12.7.1

Closing.
