### ISSUE TITLE
Plugins: plugin page shows update error

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#61720]
### Quick summary

<img width="439" alt="Screen Shot 2022-03-07 at 4 44 26 PM" src="https://user-images.githubusercontent.com/1689238/157128182-0296a74c-92e3-4e60-a4f9-9565b04ee6a6.png">

I see this error when opening plugin details pages from the plugin browser: "An error occurred while updating { blank } on { site name }".

It might be coming from here:
https://github.com/Automattic/wp-calypso/blob/7c72b388bb5d90cca1b3cbe47840ddcab1cd01ab/client/my-sites/plugins/notices.jsx#L867

### Steps to reproduce

- Click on a dotorg plugin from /plugins on an Atomic site.

### What you expected to happen

Just an update, no error.

### What actually happened

The error shows up.

**Comment by cpapazoglou** [comment]
@allilevine can't reproduce on my ecom site. Are there perhaps more concrete steps to follow?

**Comment by allilevine** [comment]
> @allilevine can't reproduce on my ecom site. Are there perhaps more concrete steps to follow?

Looks like it's a problem with my test site. Closing for now, thanks for checking!
