### ISSUE TITLE
Atomic: Customize > CSS displaying plan upgrade notice regardless of plan

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#61738]
### Quick summary

Starting on March 8th, 2022, My Site > Customize > CSS may display a notice requesting a user upgrade to the Business plan.  Even if the site has the necessary plan.

<img width="365" alt="Screen Shot 2022-03-08 at 10 01 15" src="https://user-images.githubusercontent.com/4887830/157264708-845738d2-d380-49f0-bb7c-35647180c8e3.png">

Internal discussion: p1646750128809469-slack-C02V49GM0PN

### Steps to reproduce

1. Create a WPCOM Atomic site with a BIZ plan
2. Navigate to Customize > CSS
3. Under the right conditions, see error

### What you expected to happen

Access Customize > CSS

### What actually happened

Upgrade prompt. 

### Context

Customer and HE reports.

Examples

p1646750560386449-slack-C03TY6J1A

p1646751214835079-slack-C03TY6J1A

### Simple, Atomic or both?

Atomic

### Reproducibility

Intermittent

### Severity

Some (< 50%)

**Comment by carladoria** [comment]
reported on 33969757-hc, follow up ticket 4842235-zd-woothemes

**Comment by masperber** [comment]
Also reported on 21400021-hc, follow up 48422570-zen

**Comment by ghost** [comment]
Also reported on 34555922-hc and follow up ticket zd-4842285
Also reported on 34555451-hc and follow up ticket zd-4842301

**Comment by benchilcote** [comment]
Reported in 34556159-hc following up at 4842325-zen

**Comment by jorpdesigns** [comment]
Reported in 34555901-hc, follow up: 4842336-zen

EDIT: I have followed up with user.

**Comment by kimerlin81** [comment]
Another one: 4842300-zd-woothemes

**Comment by kimerlin81** [comment]
Triaging this issue as I can reproduce and it seems to be affected a good amount of users

**Comment by mmtr** [comment]
Likely caused by 835-gh-Automattic/wpcomsh, let's prepare a revert. cc @gavande1

**Comment by masperber** [comment]
Another one: 34536170-hc / 4842446-zen

**Comment by mmtr** [comment]
It should be fixed once the new version of `wpcomsh` is deployed to Atomic sites.

**Comment by dolgelukkig** [comment]
one more: 33531951-hc

**Comment by ccwalburn** [comment]
Another report here: 33878485-hc / 4842757-zen

**Comment by JoshuaGoode** [comment]
#### Recap

Tested and confirmed this is now resolved, initially via `wpcomsh` rollback and then via script completion, D76265-code.

Impacted users can now manage their footer, CSS, and permalinks as expected.  Ready for emails to waiting users.

**Internal context**
Related to limited Atomic work

p1646753970870009-slack-C02V49GM0PN

**Related issues now resolved** 
https://github.com/Automattic/wp-calypso/issues/61486 - 814-gh-Automattic/wpcomsh
https://github.com/Automattic/wp-calypso/issues/61738 - 833-gh-Automattic/wpcomsh
https://github.com/Automattic/wp-calypso/issues/61675 - 835-gh-Automattic/wpcomsh

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
