### ISSUE TITLE
Plugin browse all pagination missing

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61748]
There used to be infinite scroll pagination on plugin results for the browse all category links (e.g. wordpress.com/plugins/new)

Now we just show an initial page worth of plugin results and don't have any way to view more of the category.

Probably due to this change #61501

- [x] We need to make infinite scroll work in category pages - #62519
- [x] We need to change from pager to infinite scroll in search results - #62533

**Comment by cpapazoglou** [comment]
@vinimotaa can we decide on either inifinite scroll or pagination for plugin list pages (eg new, popular, search results)?

**Comment by vinimotaa** [comment]
@cpapazoglou all the way infinite scroll, no pagination needed when having control of categories and filters

**Comment by WBerredo** [comment]
As the WP.org requests are being done via react query, an implementation of the `useInfiniteQuery` hook is needed.
Reference: https://react-query.tanstack.com/guides/infinite-queries
