### ISSUE TITLE
Creating new template part shows warning in the template editor

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#61754]
### Quick summary

After creating a custom template part, I can see the following warning is shown at the top of the page.

`The "wpcom-block-editor-nux" plugin has encountered an error and cannot be rendered.`

![Screenshot on 2022-03-09 at 14-10-15](https://user-images.githubusercontent.com/5733224/157414716-55214162-949d-4ae5-8ae6-06b2a4ddc502.png)

Error on the browser's console:

![Screenshot on 2022-03-09 at 15-06-58](https://user-images.githubusercontent.com/5733224/157414865-604b1028-75bf-4743-a69f-c848ba541a1f.png)

### Steps to reproduce

1. Create a new site with the BlockBase theme.
2. Navigate to Appearance > Editor(Beta) > Browse All Templates > Template Parts(from the left sidebar).
3. Create a new template part
4. You should see a warning similar to the following screenshot.

![Screenshot on 2022-03-09 at 14-10-15](https://user-images.githubusercontent.com/5733224/157414716-55214162-949d-4ae5-8ae6-06b2a4ddc502.png)

### What you expected to happen

There should be no warning.

### What actually happened

We have seen the following warning, `The "wpcom-block-editor-nux" plugin has encountered an error and cannot be rendered.`

Found the following error on the browser console.

![Screenshot on 2022-03-09 at 15-06-58](https://user-images.githubusercontent.com/5733224/157414865-604b1028-75bf-4743-a69f-c848ba541a1f.png)

### Simple, Atomic or both?

Both

### Theme-specific issue?

- BlockBase
- Quadrat Red

### Reproducibility

Consistent

**Comment by Robertght** [comment]
This appears to be happening regardless of the theme(FSE compatible).

**Comment by simison** [comment]
Pinged few teams at slack p1646819362211679-slack-dotcom-fse
