### ISSUE TITLE
Marketplace: spotlight yoast in stats page

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61753]
By using JiTMs we can target the **stats page** and if the site has **low traffic** show the Yoast Seo Premium in spotlight

![CleanShot 2022-03-09 at 11 09 40@2x](https://user-images.githubusercontent.com/12430020/157409612-7c88af84-b026-4029-9f60-883f7c9e1580.png)

- [ ] Add a rule in JITMs that can check against current site stats. specific rule TBD
- [ ] Add a JiTM in `https://wordpress.com/stats/day/` route using the above rule + yoast seo premium is not installed condition
- [ ] Add a dismiss option to the spotlight so that users can remove that specific JiTM and never see it again. JiTMs have a dismiss mechanism so `backend wise` we should be OK.
- [ ] Add the JiTM powered spotlight in `https://wordpress.com/stats/day/` page

related convo: p7DVsv-e33-p2#comment-39842
props: @simison

**Comment by cpapazoglou** [comment]
@allilevine this is another issue explorers could explore 😄 after resolving JiTM usage.

**Comment by allilevine** [comment]
We may need to fix JITM placement on the page, see: p7DVsv-e33-p2#comment-39873

**Comment by cpapazoglou** [comment]
Closing this as duplicate of https://github.com/Automattic/wp-calypso/issues/62977
