### ISSUE TITLE
Floating/Sticky Header in FSE

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#61756]
### What

I would like to have the option to enable or disable the Floating/Sticky header in the FSE Editor. There should also be options to drop shadow below the header area that can make it look stand out from the rest of the page if both the page and the menu background are set to the same color.

### Why

With the Floating/Sticky header, the site visitors will have a fantastic user experience as the menu remains visible all the time. The business's branding remains on the top, adding more charm to the user experience.

### How

The WooCommerce.com site currently has this kind of header on the Mobile version. 

Please [click here](https://d.pr/i/MW0e6C) to see the GIF image for reference.
Additionally, the following themes on WooCommerce also have a Floating/Sticky Header.

https://themes.woocommerce.com/proshop/
https://themes.woocommerce.com/outlet/

_They also have the header banner image added in the floating area._

The layout of the same themes looks something like the following:

<img width="1287" alt="Header-Layouts" src="https://user-images.githubusercontent.com/8070771/157417197-db9f08df-5640-47c7-ba61-3cc0430f1c9d.png">

We can have different options to set the layouts for the Header.

**Comment by annbingle** [comment]
I got the same request in my chat here 35407283-hc

**Comment by jp-imagines** [comment]
Had another similar request in 36958084-hc.

**Comment by filipanoscampos** [comment]
Another one, here:
5693749-zd-woothemes

**Comment by sharonlaker19** [comment]
- [ ] 5706951-zen

**Comment by Robertght** [comment]
We have a request raised here: https://github.com/Automattic/wp-calypso/issues/86286

I'm going to close for now so we can keep better track of it.
