### ISSUE TITLE
Marketplace: Update partners contact message sent copy

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#61772]
See https://github.com/Automattic/wp-calypso/issues/61032

![CleanShot 2022-03-14 at 19 00 03@2x](https://user-images.githubusercontent.com/12430020/158223509-02562665-8deb-4c8d-9f54-e1911e74788c.png)

The code lives in WPCOM `class-partners-page.php`
Page: https://wordpress.com/partners/

- [x] Get the copy from @emmnyc85 - `Thank you! We’ll be in touch as we build out our plans further.` - related convo pdh6GB-uc-p2
- [x] Implement changes.

**Comment by epeicher** [comment]
Diff created D77943-code

**Comment by emmnyc85** [comment]
@allilevine - Thank you. I commented [here](https://github.com/Automattic/wp-calypso/issues/61032#issuecomment-1090186659)
Please let me know any questions for driving this forward. cc: @cpapazoglou

**Comment by allilevine** [comment]
@epeicher 👋 Was this issue completed by D77943-code ?

**Comment by epeicher** [comment]
It was indeed so the new message should be in Production now. I am closing the task. Thanks for notifying!
