### ISSUE TITLE
Remove Site Editor Feedback Form

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#61774]
We can now remove the Site Editor beta feedback form/plugin. This is registered through the wpcom-block-editor and communicates with Calypso through the iframe-bridge-server.

![image](https://user-images.githubusercontent.com/28742426/157508258-bfa7ae96-edee-42d0-a89c-566b44e9d166.png)

When we do this we should ensure we remove references to this from user facing documentation as seen here: https://wordpress.com/support/site-editor/#how-to-give-feedback

**Comment by jeyip** [comment]
Will work on this with Kenroy during his onboarding

**Comment by Addison-Stavlo** [comment]
> Will work on this with Kenroy during his onboarding

Awesome, this seems like a good fit for that. 😁
