### ISSUE TITLE
AMP settings not showing in Customizer on simple site

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/wp-calypso#61781]
### Quick summary

On a simple site, the AMP link is not showing up in the customizer after clicking on it under Appearance. I was able to replicate on my simple test site on Independent Publisher 2, Coutoire, Toujours - it seems to be any theme that is not an FSE theme. This does not affect AT sites.

Screenshot:

![Markup on 2022-03-09 at 17:07:49](https://user-images.githubusercontent.com/5779512/157544939-1e3903e6-a24a-48fb-818a-10200babac32.png)

### Steps to reproduce

1. In the WPcom dashboard on a simple site, activate Independent Publisher 2
2. Then go to Appearance and click on AMP
3. You will be redirected to the customizer but there is no link for AMP settings

### What you expected to happen

I expected to see the AMP settings or be redirected to the AMP settings directly in the customizer.

### What actually happened

I was redirected to the customizer but there was no AMP link or any way to change the settings there.

### Context

Customer report - #4814980-zd

### Simple, Atomic or both?

Simple

### Theme-specific issue?

It seems to affect any of our themes that are not FSE themes

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by edequalsawesome** [comment]
Initially I was able to duplicate this, but once I allowed my site to be indexed by search engines and verified that AMP was enabled through the `Settings > Performance` area, I was able to get it to work -- @gwensmithx was your test site set to public/able to be indexed when you saw the issue?

**Comment by Greatdane** [comment]
Closing this as no response from @gwensmithx and unable to replicate.

**Comment by masperber** [comment]
I'm reopening this, as Team Aquila was assigned the [initial report P2 post](p2EDhh-1uP-p2).

I was able to reproduce on a Simple site with Independent Publisher 2 activated. I noted @edequalsawesome 's comment, and I verified that AMP is enabled and search engines are allowed to index [my test site](masperberpm.wordpress.com).

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Themes Tested: Karuna, Independent Publisher 2, Twenty Eleven

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate this issue only when my test sites were not indexable. When that was corrected, an AMP module appeared within the Customizer.

- Free Site, Twenty Eleven, Coming Soon: https://d.pr/v/3r51a5
- Free Site, Twenty Eleven, Public & Indexable: https://d.pr/v/B2DjqW

- Premium Site, Independent Publisher 2, Discourage Search Engines: https://d.pr/v/vMH6nh
- Premium Site, Independent Publisher 2, Allow Search Engines: https://d.pr/v/KAnhG7
 
📌 ACTIONS
- Await author feedback

@masperber - can you try following the same steps in my recording and let me know if you still don't see the **AMP** option in customizer with your test site Public & Indexable?  Be sure this setting is also enabled under Settings > Performance: https://d.pr/i/FOoIak

**Comment by inaikem** [comment]
Closing as unreproducible. If the issue is reported again, please test using the latest guidance provided in the comment above and reopen as needed!
