### ISSUE TITLE
MC Tool for Generated Vertical Designs

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#61788]
## Description

Part of Verticals in Onboarding project.
Build a Generated Vertical Design preview tool that will essentially mimic the process that will happen in onboarding that produces a user's verticalized design preview in the Design Picker.  This work will be dependent on the progress of #61228 and #61198 and continued work beyond the spike phase.  

The tool should be useful to devs, designers, block pattern creators, such that content creators can preview how an image or block or page layout will look in a verticalized context.  

## Acceptance Criteria

The definiton of this tool is still under discussion, please update the AC as we define what the v1 of the tool should do
- [x] user selects a theme and a set of block patterns and previews the result
- [x] user selects a theme and a single page layout and previews the result (check with OlaB)
- [x] user can change the language and site title for the preview.

## Track Ideas for v2
* user sees a preview of the design with images sourced from the vertical image source site

## Related

Project Thread:
pNEWy-eFy-p2

**Comment by fushar** [comment]
PR for the create recipe page: D77449-code

**Comment by autumnfjeld** [comment]
FYI @fushar :  This issue is still open, but it was moved to Done.

We have automation set up so that when you close an issue, it will automattically move to Done.  Thus the process is just to close the issue. 😄 

Also nice to check off all the items in the AC (Acceptance Criteria) to make it clear that the items are done. 😄

**Comment by fushar** [comment]
@autumnfjeld: Ah sorry, I thought moving it to Done will auto-close the issue 🤦 

Checked all ACs and closing this issue!
