### ISSUE TITLE
Marketplace: Launch FedEx Shipping Method and WooCommerce One Page Checkout

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#61793]
Complement of: #61249
- [x] Get the plugin added as Managed Plugin (p9o2xV-1Wy-p2)
- [x] Test all versions (monthly, annual) can be purchased, installed, and activated.
- [x] Lanch this product for all users (even non-a12s) and make it `featured`. (D76516-code)

**Comment by cpapazoglou** [comment]
Tested all variations of both plugins and they are installed and activated as expected 🚢

**Comment by WBerredo** [comment]
Launched at r241574-wpcom
