### ISSUE TITLE
Theme Showcase: WP.org themes are showing a WP.com contact button.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#61805]
There's a "Contact us" button on WP.org themes in the Theme Showcase that sends the user to our WP.com support – even though WP.org themes are not supported by us.

See: p1646914375829829-slack-C029FM1EH

<img width="1213" alt="Screen Shot 2022-03-10 at 8 15 37 AM" src="https://user-images.githubusercontent.com/349751/157706930-cd4d31a0-89b4-4899-8628-bb7fce0792f0.png">

**Comment by kwight** [comment]
I imagine a straight-forward fix would be hiding that contact card for any WP.org theme.

**Comment by kwight** [comment]
> I imagine a straight-forward fix would be hiding that contact card for any WP.org theme.

@Robertght What would the correct logic be for hiding the contact button, do you think: _hide if the theme is not dotcom, and if site is not atomic_? I'm not sure if we do support Atomic users with dotorg themes or not. 🤔

**Comment by Robertght** [comment]
@kwight We don't offer support for other themes than the ones from WordPress.com so hiding the contact button for any non-wpcom themes should be ok. :)

**Comment by Robertght** [comment]
Correction on the above. I just realized, I forgot to mention Storefront. That's also supported by us and Woo.

**Comment by markbiek** [comment]
I think checking for either `isWpcomTheme || author === 'Automattic'` covers it. Just pushed an update.
