### ISSUE TITLE
Reader Cold Start: featured posts do not load in Safari until after refresh

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#6181]
Reported by @shaunandrews.

#### Steps to reproduce
1. Starting at URL: http://wpcalypso.wordpress.com/read/start

#### What I expected

Full post cards load, including featured post.

#### What happened instead

Featured posts do not load. Mostly appears after refresh.

Works fine in Chrome.

#### Browser / OS version

Safari OS X

#### Screenshot / Video

![screen-shot-2016-06-21-at-12-21-18-am](https://cloud.githubusercontent.com/assets/17325/16236427/4691df4e-37d0-11e6-87a6-af0cc03bb4bd.png)

**Comment by blowery** [comment]
I can get it to break on refresh in Safari too

**Comment by jancavan** [comment]
I was able to reproduce the issue. The `<header>` tag is followed by `<article>`, but in Safari it seems like it's being stripped out?

![screenshot 2016-06-21 14 06 07](https://cloud.githubusercontent.com/assets/4924246/16246271/50d93d74-37b9-11e6-9723-94da9f4333f2.png)

**Comment by bluefuton** [comment]
It looks like it's failing to retrieve the post object, or failing to re-render when the post object is retrieved.
