### ISSUE TITLE
Anchor.fm - Move Gutenboarding onboarding process to /start framework

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61818]
With Gutenboarding (hopefully) going the way of the dinosaur shortly, Anchor.fm onboarding needs to be moved into the /start framework flow. 

(If any pricing-related changes are involved, this should be coordinated with the pricing and packaging team; P2 is at dgrnI-p2 and contact point is Paul Bonahara. However, it seems like this shouldn't be an issue.)

**Comment by blackjackkent** [comment]
As of today we will be holding off on this issue for next sprint in order to build it on top of the Stepper framework rather than write code that will need to be migrated anyway.

**Comment by andres-blanco** [comment]
paYKcK-1rX-p2

**Comment by blackjackkent** [comment]
Closing this issue in favor of more individual tasks created elsewhere. (See Anchor FM label in GH.)
