### ISSUE TITLE
Reader Cold Start: excerpt line clamp does not work in Firefox

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#6182]
Reported by @westi.

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/read/start

#### What I expected

Excerpt length in Firefox is 3 lines, just like Chrome.

#### What happened instead

Excerpt is heaps longer in Firefox. Looks like `-webkit-line-clamp` is not honoured by FF.

#### Browser / OS version

Firefox OS X

#### Screenshot / Video

![screen_shot_2016-06-21_at_16 36 53_720](https://cloud.githubusercontent.com/assets/17325/16236557/b1e88982-37d0-11e6-8512-1e67e159158f.png)

#### Context / Source

#manual-testing

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/6186
