### ISSUE TITLE
Seller Exp - SPIKE: Verify and analyze Seller Experience Tracks information

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#61820]
We need to verify and refine the tracks information recorded during the Seller Experience onboarding process; specifically, we should establish events and funnels to help answer the following questions:

- What percentage of users complete the Seller Experience flow?
- What percentage choose "Start Simple" vs "More Power"?
- Where do people leave the Seller Experience when they do not complete it?

**Comment by ianstewart** [comment]
- Completion rates for Start Simple vs More Power
- Completion of steps/screens while in the /start framework for Seller Exp
- 1 hour and 7 day plan conversion within each flow

**Comment by blackjackkent** [comment]
Occurrence of "back" bug in More Power flow

**Comment by sixhours** [comment]
Initial P2 post is here with answers to these questions (and more!): paYKcK-1sA-p2 

We can probably close this until the next round of analysis. :)
