### ISSUE TITLE
Blockbase: Separator block (dots style) breaks to two lines

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#61853]
### Quick summary

When adding a separator block to Blockbase, the dots style is not aligned in a row, breaking it to two separate lines as noted here: https://github.com/Automattic/themes/issues/4710#issuecomment-1064906199

Screenshot: 

<img width="1180" alt="156605249-9f1b083a-311c-4993-82d4-2aa306c411c7" src="https://user-images.githubusercontent.com/39252765/157910486-eac2f34c-c984-4484-b92f-8f1553a97b73.png">

### Steps to reproduce

1. Activate Blockbase
2. Add a separator block, setting it to "dots" style
3. Observe that the dots are not aligned in a single row

### What you expected to happen

I expected three dots, side-by-side.

### What actually happened

A single dot appeared (misaligned) above to other dots, as in the screenshot above. 

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Blockbase

### Reproducibility

Consistent

**Comment by mikeicode** [comment]
I run into this every time I try to use this when building DIFM-L sites on Blockbase themes, usually on the Russell theme. If used inside a Media / Text block is breaks onto 2 lines, when used outside that block  it's not centered.

![Screen Shot on 2022-03-14 at 13:44:47](https://user-images.githubusercontent.com/10353785/158230781-6943307f-38a1-4f57-82fa-ffc486b20b63.png)

**Comment by formosattic** [comment]
Was able to reproduce it with Geologist, Quadrat.

It's also happening on self-hosted, I tested with:
* Blockbase: https://pcm.wordpress.org/themes/blockbase/
* Quadrat: https://pcm.wordpress.org/themes/quadrat/

**Comment by formosattic** [comment]
Actually, will close this in favor of https://github.com/Automattic/themes/issues/5582
