### ISSUE TITLE
Theme Showcase: Try & Customize is shown instead of Live Demo for sites without the FSE Editor active

### ISSUE THREAD

**Issue by lizswafford** [Automattic/wp-calypso#61861]
### Quick summary

An AT Business plan site that _does not_ have the new Full Site Editor (beta) active will see the [Theme Showcase](https://wordpress.com/themes) offer a "Try & Customize" option to preview a theme instead of "Live Demo". 

If the user chooses Try & Customize they end up at the Customizer. The Customizer sidebar loads, with the options like Site Info. But, the rest of the screen is blank - the theme preview is missing.

Viewing Payton Theme: 
<img width="758" alt="try_and_customize" src="https://user-images.githubusercontent.com/33204818/157966020-4ff48705-9167-4258-90f9-eaf1bae83a81.png">
Result in Customizer: 
<img width="1347" alt="Customizer_view_blank" src="https://user-images.githubusercontent.com/33204818/157966167-138c6ce5-c4bb-455f-83c9-d3852312eab3.png">
Site doesn't have FSE Editor active: 
<img width="530" alt="No FSE Editor" src="https://user-images.githubusercontent.com/33204818/157966432-f07aa8dc-1102-4b7a-8249-4367191ea12f.png">

### Steps to reproduce

1. On a Business plan without FSE active, visit the Theme Showcase. 
2. Scroll down to see the image thumbnails for the themes
3. On a FSE theme, such as Payton or Marl, click on the three dots to view more options
4. Choose "Try & Customize" 
5. The customizer will load, but the theme will not be shown

### What you expected to happen

Sites that do not have the FSE Editor active should be able to view a theme's Live Demo.
Then, be offered an option to switch to the new editor.

View of live demo option on an account with FSE Editor activated: 
<img width="514" alt="livedemo_onFSEactive" src="https://user-images.githubusercontent.com/33204818/157967993-70a37022-f9c7-4e6f-817e-dbae439e4f1a.png">
 

### What actually happened

Loading the Customizer shows the Customizer sidebar, then an empty space where the theme content should be. 

The "Activate & Save" option in Customizer does work. 

I was able to activate the theme on my test site, exit Customizer, then open Customizer again. 
The theme was visible. Also, the Appearance > Editor (beta) or FSE option was activated.

### Context

#4846596-zen

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Any theme tagged with FSE.

### Reproducibility

Consistent

### Severity

One

### Workaround details

Not exactly a workaround - but you can go to the Theme Thumbnail, click on Info. 
On the [theme page](https://wordpress.com/theme/payton/), click "Open Live Demo" to view a preview of the theme.

**Comment by kimerlin81** [comment]
Thanks for submitting this detailed bug report @lizswafford ! This issue has been triaged, as I was able to reproduce this behavior when attempting to "Try & Customize" the Bennett theme. Non-FSE themes like Wilson, load the theme preview in the Customizer just fine.

**Comment by cometgrrl** [comment]
This seems to be resolved. I do not see "Try & Customize" as an option for FSE themes.
<img width="285" alt="Screen Shot 2022-04-06 at 2 37 53 PM" src="https://user-images.githubusercontent.com/86427589/162076075-d749da83-6048-4975-84a0-f00d533219ed.png">

@lizswafford please re-open if you're able to reproduce this still.
