### ISSUE TITLE
Arbutus: Social media icons not showing in Social Menu

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#61877]
### Quick summary

Social media icons are not showing for social media links set correctly in menu.
![Annotation on 2022-03-13 at 10-40-38](https://user-images.githubusercontent.com/44442769/158053793-01ed9c2d-0ca6-4aae-b850-572ed1850999.png)

### Steps to reproduce

1. Activate theme Arbutus
2. Add Social Media menu and add links to social platforms 
3. Save and icons are not shown correctly

### What you expected to happen

I would expect the social media icons to display correctly and are clickable

### What actually happened

Incorrect default social media icon is shown, but is correctly clickable

### Context

4855942-zen

### Browser, operating system and other notes

Could be related to this issue: https://github.com/Automattic/themes/issues/5337

### Reproducibility

Consistent

**Comment by fetenlakhal** [comment]
zen-4862199

**Comment by Robertght** [comment]
Thank you for reporting this! I'm closing it favor of https://github.com/Automattic/themes/issues/5673
