### ISSUE TITLE
Missing translation string in Jetpack comment form: "Address never made public"

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#61874]
### Quick summary

In the Jetpack comment form for users that are not logged in, the text "Address never made public" does not appear as a translation string in the plugin Loco Translate, so it is not possible to change it using this plugin. 

### Steps to reproduce

1. Go to [Glotpress for Jetpack](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/en-gb/default/)
2. Use the filter to search for [Address never made public](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/en-gb/default/?filters%5Bterm%5D=address+never+made+public&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

### What you expected to happen

I expected this text to appear as a string that can be translated since it is a public-facing string.

### What actually happened

It shows "No translations were found!" So it will also not appear in the Loco Translate plugin.

### Context

User report: 34394125-hc

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

@jeherve is this best kept here in GH, or should that string be submitted to the [WordPress translation projec](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/en-gb/default/)t for future translation?

**Comment by jeherve** [comment]
> does not appear as a translation string in the plugin Loco Translate, so it is not possible to change it using this plugin.

That is indeed to be expected. Jetpack's Comment form loads a brand new form in an iFrame that is hosted on WordPress.com. The whole comment form is consequently hosted on WordPress.com, and translated there. Folks will not be able to customize the contents of the iFrame using third-party plugins like Loco Translate.
