### ISSUE TITLE
Layout Grid block conversion to Columns creates nested Layout Grid

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#61873]
### Quick summary

I was going to suggest to a user that they try to switch to the Columns block while facing an issue with the Layout Grid, but when I clicked it to see how it would look before suggesting it, a new Layout Grid block with the content got nested inside a Column block instead of doing a full conversion.

### Steps to reproduce

1. Open any page and add a Layout Grid
2. Once you have a Layout Grid set up, click the Layout Grid icon and select the Columns option
3. You should see that the Layout Grid you had created gets nested within the Columns block instead of simply replacing the Layout Grid

### What you expected to happen

The Layout Grid would be fully replaced by the Columns block.

### What actually happened

The Layout Grid gets nested within the columns block.

### Context

https://user-images.githubusercontent.com/51870544/158034952-ed18ed1c-3e3a-4fe6-bd25-10cec3bc5791.mp4

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Happens no matter which theme I try.

### Browser, operating system and other notes

Happens consistently across all browsers. I have not found a workaround.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by formosattic** [comment]
Thanks @ClassicRKR27 for the clear report!
I'm able to reproduce it as well.

I see the Layout Grid block is maintained in the Block Experiments repo, https://github.com/automattic/block-experiments but not sure if we have to transfer there.

Internal ping: p1647395915980129-slack-C029FPKAY

**Comment by johngodley** [comment]
This doesn't really sound like a bug - the block is doing exactly what it is supposed to do - but a feature request, which is already being tracked here:

https://github.com/Automattic/block-experiments/issues/171

>  while facing an issue with the Layout Grid

This sounds like something that should be reported as a bug?

**Comment by Greatdane** [comment]
Going to close this then in favour of https://github.com/Automattic/block-experiments/issues/171
