### ISSUE TITLE
Sensei Pro: Confirm plugin can be purchased and installed

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61882]
- [x] Confirm Sensei Pro can be purchased as a11n user
- [x] Confirm Sensei Pro can be purchased as non a11n user
- [x] Confirm Sensei Pro is installed after making the purchase

**Comment by lsl** [comment]
Progress update on managed plugin front p9o2xV-1Wj-p2#comment-5674

**Comment by lsl** [comment]
potentially progress? p9o2xV-1Wj-p2#comment-5749

**Comment by lsl** [comment]
Sensei Pro should be flagged as a managed plugin and installs via calypso/async job can now be retested.

**Comment by paulopmt1** [comment]
I can buy it from a11n user and it installs :)
Still investigating the problem while buying with a non a11n user:

![image](https://user-images.githubusercontent.com/1044309/162225790-89c3e27f-f659-4461-b953-85068c81c966.png)

**Comment by paulopmt1** [comment]
Successfully tested with a11n and non-a11n user on monthly and yearly plans :)
Great job, @lsl!
