### ISSUE TITLE
Woo Pre-Orders: Add marketplace product entry

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61889]
- [x] Add marketplace [`/marketplace/products`](https://public-api.wordpress.com/wpcom/v2/marketplace/products) entry behind a11n flag
- [x] [If required](https://github.com/Automattic/wp-calypso/issues/61548#issuecomment-1067458074), include the icon image in `wp-content/lib/marketplace-images/<imagename>` available at `https://wordpress.com/wp-content/lib/marketplace-images/<imagename>`

You can add the newly created product/plans to the marketplace by updating the marketplace endpoint to include the product information decided on and confirmed in the preflight p2 post https://github.com/Automattic/wp-calypso/issues/61884, you can also reference the woocommerce.com [product listing](https://woocommerce.com/products/woocommerce-pre-orders/).

The new product information should be hidden behind an a11n only `is_automattician` check so we can test the installation process, plugin info, images etc before making it available for purchase to everyone.

This task maps to step 2 in the documentation PCYsg-CJy-p2 but I suggest following the existing examples in code as the documentation needs updating to reference newer fields since added.

Example D76441-code, feel free to click "Edit Revision" to copy the test plan, it should be mostly applicable to all marketplace plugins.

**Comment by paulopmt1** [comment]
Phabricator code here: D77093-code

**Comment by lsl** [comment]
Merged ![Screenshot 2022-03-21 at 14-21-43 Plugins — WordPress com](https://user-images.githubusercontent.com/811776/159201177-7976c3b2-3e97-452a-80ec-0e9747837b89.png)
