### ISSUE TITLE
Sidebar: Site Card: Clicking Updates open preview

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#6188]
Today, I noticed when I click the "There is a plugin update available" link in the site card of the sidebar, that it loads a site preview instead of sending the user to `/plugins`.

![calypso_sidebar_updates_broken](https://cloud.githubusercontent.com/assets/1126811/16241843/32162180-37b5-11e6-819f-ef115bc47ac0.gif)
[Higher resolution video](https://cloudup.com/cRkOXyPbA8k)

cc @lamosty as I believe he has been in this area recently.

**Comment by lamosty** [comment]
@ebinnion Sorry, but I was not in this area recently. The one PR which caused a bug with site preview was reverted in #5966.

Maybe I'm missing some other PR. Could you add a link to it? Why do you suppose I was there recently?

**Comment by ebinnion** [comment]
My apologies then. I just remembered the preview issue from before.

**Comment by lamosty** [comment]
No problem. :) I just wasn't sure which PR are you referring to because you haven't included a link.

On the other hand, the issue is still there..

**Comment by lancewillett** [comment]
I can't repeat this one, testing the same flow today the link opens wp-admin as expected.
