### ISSUE TITLE
Woo Pre-Orders: Create catalog product and plans (yearly and monthly)

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61885]
See documentation PCYsg-CJy-p2 for more detailed instructions, script commands to run and example output to expect.

This issue covers the first half of step 1 in the documentation, we're creating the new billing system products, plans, and syncing them to production tables. If a mistake is made or you get lost, you can reach out to #payments-dev for help.

- [x] Create a yearly "billing catalog product" and "billing catalog plan" in the test tables
- [x] Create the monthly plan against the previously created product
- [x] Sync both of these to production

----

### Product creation and Yearly Plan:

Running the `create-plans-prior-to-store-product` command outlined in the docs will prompt you with a series of questions, use this table to fill things out as you go:

| Question  | Answer | Notes |
| ------------- | ------------- | ------------- |
| product name  | WooCommerce Pre-Orders  | |
| product slug  | woocommerce-pre-orders  | Should match woocommerce.com changelog slug |
| interval unit  | 2 | Create the yearly plan first for consistency | 
| years | 1 | 1 year option |
| name pattern | Hit enter to select the default | Use the default value |
| slug pattern | Hit enter to select the default | Use the default value |
| brand | 1 | WooCommerce plugins go under the wordpress-com brand |
| bd_slug | wp-marketplace | All marketplace plugin plans go under this parent slug |
| bd_variation_slug | woocommerce-pre-orders-yearly | Match the product slug with the plan duration appended |
| p2 post | todo | Link to p2 post written in https://github.com/Automattic/wp-calypso/issues/61884 | 
| USD Price | 116 | See spreadsheet for pricing, a8c punchlist tab Pdh6GB-2Y-p2, in this case it's 116 USD |
| Final confirmation | y | This inserts the information into the new billing tables |

### Monthly Plan:

You need to query the db to get the product id created in the previous step, see docs for the query and example for how to run it from a sandbox. You then need to pass that id to the `create-plans-prior-to-store` command via the `--catalog-product-id=` arg. Doing this re-uses the same product for the new monthly plan. The rest of the questions are mostly the same.

| Question  | Answer | Notes |
| ------------- | ------------- | ------------- |
| interval unit  | 1 | Select monthly this time | 
| name pattern | Hit enter to select the default | Use the default value |
| slug pattern | Hit enter to select the default | Use the default value |
| brand | 1 | WooCommerce plugins go under the wordpress-com brand |
| bd_slug | wp-marketplace | All marketplace plugin plans go under this parent slug |
| bd_variation_slug | woocommerce-pre-orders-monthly | Match the product slug with the plan duration appended |
| p2 post | todo | Link to p2 post written in https://github.com/Automattic/wp-calypso/issues/61884 | 
| USD Price | 11 | See spreadsheet for pricing, a8c punchlist tab Pdh6GB-2Y-p2, in this case it's 11 USD |
| Final confirmation | y | This inserts the information into the new billing tables |

### Sync to production:

The `sync-production` command takes what we created in the previous steps and copies them (id's and all) over to the production tables. The script also prompts a series of questions:

| Question | Answer | Notes |
| ------------- | ------------- | ------------- |
| continue | y | Basically a "should we start this process" check |
| sync `product name`?  | 1 | Read the question carefully, if it is talking about your product, select 1, if not 2 |
| sync `product name`? | 2 | Answer 2 to anything that is not yours, this question repeats. |
| `product info` | Hit enter | To show plan info |
| `plan info` | | Repeat until final confirmation |
| Final confirmation | y | This copies all selected products and plans to production tables |

**Comment by paulopmt1** [comment]
### How to validate

1. Make sure the product is on the production table: `gpr select * from billing_products where product_slug='woocommerce-pre-orders'`. 

3. Make sure the billing plans (Monthly and Yearly) are in the production tables and with the correct USD value: 
- Monthly: `gpr select * from billing_plans where accounting_product_variation_slug like 'woocommerce-pre-orders-monthly%'`
- Yearly: `gpr select * from billing_plans where accounting_product_variation_slug like 'woocommerce-pre-orders-yearly%'`

**Comment by lsl** [comment]
LGTM
