### ISSUE TITLE
Woo Pre-Orders: Reserve store_product plan id's

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61886]
Choose the next two new store_product id's for WooCommerce Pre-Orders, these should be in the 900s like our other marketplace plugins. History on why we use meaningful ids here: PCYsg-rD-p2#requirements-for-a-new-store_product

For this task we need to choose the id's and get a diff merged with those ID's as constants, we can then use these ID's / constants in our other diffs without worrying about bespin using them for another new product at the same time.

- [x] Create a diff to reserve the store product id's in code

Example D76056-code

**Comment by paulopmt1** [comment]
Phabricator: https://code.a8c.com/D76804

**Comment by paulopmt1** [comment]
Diff code in Phabricator: D76804-code
