### ISSUE TITLE
Woo Pre-Orders: Add store_product to billing catalog mapping

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61895]
In this step we need to map the new billing catalog plans we created in https://github.com/Automattic/wp-calypso/issues/61885 to the legacy `store_products` we will generate in https://github.com/Automattic/wp-calypso/issues/61887. 

To do this we map **both** `store_product` ID constants we chose in https://github.com/Automattic/wp-calypso/issues/61886 to the billing catalog product (not plan) slug.

- [x] Create / merge diff to map the products across new and legacy systems

Example D76057-code

**Comment by paulopmt1** [comment]
Phabricator: D76811-code

**Comment by paulopmt1** [comment]
Diff code in Phabricator: D76811-code
