### ISSUE TITLE
Woo Pre-Orders: Remove a11n flags

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61892]
https://github.com/Automattic/wp-calypso/issues/61889 added WooCommerce Pre-Orders product information to the marketplace product catalog behind an `is_automattician` check.

- [x] Remove the a11n check to launch the plugin for sale

**Comment by paulopmt1** [comment]
Code in Phabricator: D77405-code

**Comment by lsl** [comment]
Merged your other one instead D77424-code
