### ISSUE TITLE
Purchased Retired Premium Themes - Users can't activate on their own

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#61897]
### Steps to reproduce

Can't reproduce as retired premium theme can't be bought as standalone anymore.

But here's what the steps would be:

* Buy an old/retired Premium theme as a standalone
* Switch to another theme
* Try to activate the retired theme again

### What you expected to happen

The retired theme should still come up in the catalog.

### What actually happened

The retired theme doesn't come up

### Context

Ticket: 4857615-zd-woothemes

### Theme-specific issue?

Any retired Premium themes

### Workaround details

User has to contact support to have the theme manually activated.

**Comment by kimerlin81** [comment]
Hi @formosattic! Thanks for submitting this bug report. From what I gather after reading [this P2](pbg9X-g9x-p2), this doesn't appear to be a bug. Instead, it seems to be the way things have been designed to work as of 9/1/2021.

As per the HE FAQs:

> If someone had purchased a theme individually in the past, will they keep access to that theme even if it is retired or they switch to a different theme temporarily?

A: If that theme is active they will still have access to it, and if they switch to a different theme and want to go back, we made a tool for that too. The tool allows us to activate themes, including retired premium themes. 

So, I'll close this issue, but you're more than welcome to reply if you have any questions.
