### ISSUE TITLE
Woo Pre-Orders: Post a managed plugin request on atomic p2

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61891]
- [x] Post a managed plugin request on atomic p2

While marketplace plugins can be purchased as soon as it's available in the `/products` endpoint (https://github.com/Automattic/wp-calypso/issues/61889), the install process that happens on purchase won't succeed until it's been flagged as a managed plugin.

Example p9o2xV-1Wj-p2

**Comment by lsl** [comment]
@cpapazoglou can you confirm if WooCommerce Pre-Orders should be installed via github releases or the woocommerce.com link we used for sensei pro?

**Comment by cpapazoglou** [comment]
Searching in the woo repos I can see `woocommerce-pre-orders exists and has a proper versioning systems with releases.

https://github.com/orgs/woocommerce/repositories?q=order&type=all&language=&sort=

In which case, the GH repo is preferable.

**Comment by paulopmt1** [comment]
Request made here: p9o2xV-1XQ-p2

**Comment by lsl** [comment]
Thanks! I updated that post to reference github releases for installation. There is a bit of a problem with using the woocommerce.com storage approach we tried with sensei (currently blocking release of sensei) see comments, p9o2xV-1Wj-p2

**Comment by paulopmt1** [comment]
Thanks @lsl !
