### ISSUE TITLE
Marketplace: Plugins Browser featured list regression

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61900]
[https://wordpress.com/plugins](https://wordpress.com/plugins) is currently showing a duplicate list for featured plugins.

![image](https://user-images.githubusercontent.com/12430020/158143876-39750dac-27bd-48cd-ae6e-92f54938fa52.png)

This is a regression. `Featured` plugins are WPCOM plugins that are returned from

https://github.com/Automattic/wp-calypso/blob/be3471079690b93424c3c331f9ef3151dcb5638b/client/state/plugins/wporg/actions.js#L117

Clicking `Browse All`, also returns .org featured plugins while it should use WPCOM featured.

Let's add an e2e test case validating that we show correct plugins.

**Comment by lsl** [comment]
This might be related to https://github.com/Automattic/wp-calypso/issues/61894#issuecomment-1067273807 though it might not be in scope of this issue. 

Created a new issue to track in https://github.com/Automattic/wp-calypso/issues/61933, if it can be fixed in one, feel free to close both out.
