### ISSUE TITLE
Payments: Check that donation products are handled appropriately

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#61909]
### What

Make sure products of type donation are handled appropriately by the off-site UI (confirmation messages and emails, receipts, notifications, etc.).

### Why

See paYJgx-1SL-p2

### How

Follow up to https://github.com/Automattic/wp-calypso/issues/61908

**Comment by BogdanUngureanu** [comment]
Closed since we don't need to make any changes for this. The implementation for donations already existed, we exposed the donation type in the API.
