### ISSUE TITLE
Twenty Twenty Theme Documentation error

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#61913]
### What

Theme 2020

When you go into the theme documentation for Twenty Twenty in the list of Quick Specs, bullet point 3, “The recommended Featured Image size is 2000px wide by 1200px high.”

Scroll down to the section on “Featured images,” and it says - “The recommended Featured Image size is 1980px wide by 1485px high.”

### Why

It contradicts itself.

### How

4855437-zd

**Comment by kjellr** [comment]
I think the `2000px wide by 1200px high` one is a copy/paste typo in the WordPress.com theme docs. The official WP.org guideline only includes the `1980px wide by 1485px high` recommendation. 

https://wordpress.org/support/article/twenty-twenty/#quick-specs

**Comment by Robertght** [comment]
Thank you! I've updated the doc to reflect this.

Waiting on some info.

**Comment by Robertght** [comment]
Fixed by @jeffikus.
