### ISSUE TITLE
Marketplace: Add WooCommerce UPS Extension

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#61918]
### Details
Extension: https://woocommerce.com/products/ups-shipping-method/
Prices can be found in the spreadsheet of next woo extensions, link in Pdh6GB-2Y-p2, see "a8c Plugin Punchlist" tab.
Documentation: PCYsg-AhH-p2

- [x] Break this down into plugin add steps like https://github.com/Automattic/wp-calypso/issues/61548
- [x] https://github.com/Automattic/wp-calypso/issues/61941
- [x] https://github.com/Automattic/wp-calypso/issues/61942
- [x] https://github.com/Automattic/wp-calypso/issues/61943
- [x] https://github.com/Automattic/wp-calypso/issues/61944
- [x] https://github.com/Automattic/wp-calypso/issues/61945

**Comment by lsl** [comment]
update: newer / improved example of this in https://github.com/Automattic/wp-calypso/issues/62005#issue-1171891204 

Tried to chunk this a little more strategically, still 5 tasks but the work is sort of grouped into these phases in practice.

Preflight https://github.com/Automattic/wp-calypso/issues/61941

Create catalog products https://github.com/Automattic/wp-calypso/issues/61942
- [x] Catalog Product
- [x] Yearly plan
- [x] Monhtly plan

Create store products https://github.com/Automattic/wp-calypso/issues/61943
- [x] Reserve store product ID's
- [x] Add catalog mapping
- [x] Generate store products
- [x] Add store product translation

Add marketplace product entry https://github.com/Automattic/wp-calypso/issues/61944
- [x] Add marketplace product entry to endpoint
- [x] Insert vendor product info
- [x] Post on atomicp2

Release WooCommerce UPS https://github.com/Automattic/wp-calypso/issues/61945
- [x] Create diff to remove a11n only flag (ready for launch)
- [x] Confirm plugin can be purchased and installed by non a11n users
- [x] Merge diff

**Comment by lsl** [comment]
Lets leave this open til complete

**Comment by paulopmt1** [comment]
Waiting for the review of Phabricator diff: D77315-code
After it, I'll test the installation, and we probably won't need the P2 post anymore.

**Comment by lsl** [comment]
Shipped, tested non a11n purchase on prod with credits.
