### ISSUE TITLE
Cold Start - One card is on top of another card

### ISSUE THREAD

**Issue by stevekaeser** [Automattic/wp-calypso#6192]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/read/start
2. Click on card with title "Fcuk Pretty"
3. Go back to list of cards
4. Click on card with title "Doggy Bag"
5. Go back to list of cards
#### What I expected

I expected recommendations to be added with proper formatting
#### What happened instead

Two cards were added, but the second is sitting on top of the bottom of the first
#### Browser / OS version

Mac OS X El Capitan
Version 51.0.2704.84 (64-bit)
#### Screenshot / Video

![screen shot 2016-06-21 at 3 25 05 pm](https://cloud.githubusercontent.com/assets/1377746/16243551/cfd1804e-37c5-11e6-99e5-46ab645df54e.png)

**Comment by jancavan** [comment]
I was able to reproduce the issue. It doesn't seem to happen with other cards - only when you click on "Fcuk Pretty" then "Doggy bag":

![screenshot 2016-06-21 13 49 01](https://cloud.githubusercontent.com/assets/4924246/16245871/a52ec1f2-37b7-11e6-83ff-6ea4013cfc48.png)

**Comment by jancavan** [comment]
Re-opening this issue as we noticed it's still happening. Also noticed this happens on mobile, but can't seem to reproduce:

<img width="345" alt="screenshot 2016-07-06 13 25 40" src="https://cloud.githubusercontent.com/assets/4924246/16633246/348bb3a2-437d-11e6-9a16-f0189ef5fa3e.png">

**Comment by jancavan** [comment]
Cold Start no longer exist so I'm closing this issue.
