### ISSUE TITLE
Gallery Block: Uploading multiple picture replaces some of the photos inside the page with one photo

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#61924]
### Quick summary

When a user tries to upload multiple images for a Gallery Block from their PC all of the images don't end up shown in the gallery. Some of the pictures get replaced by one picture.

![ezgif-4-366ae45aac](https://user-images.githubusercontent.com/5733224/158231855-399130cb-4b48-4eab-b6c0-ab2a5402db38.gif)

### Steps to reproduce

1. Add a Gallery block on a page
2. Upload multiple distinct image files at the same time
3. After all of the files are uploaded, observe that some of the images are duplicate images

### What you expected to happen

We should see all the distinct images on the gallery block.

### What actually happened

Some of the images inside the Gallery Block gets replaced by one single image.get

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Intermittent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by kimerlin81** [comment]
Thanks for submitting this bug report @InsomniacSabbir. I will be closing this report in favor of the duplicate issue which was created 15 days ago: https://github.com/Automattic/wp-calypso/issues/61578
