### ISSUE TITLE
Browse All Paid not showing all paid plugins

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61933]
There seems to be a bug where clicking "Browse All" on the paid (premium) plugin section loads only featured plugins from the endpoint. It's likely using the same query/response as is used for the front page and needs to be changed when on the view all page.

Context pdh6GB-tx-p2#comment-925 and possibly related https://github.com/Automattic/wp-calypso/issues/61900

**Comment by gcsecsey** [comment]
Backlog grooming:
For the time being, we should remove the filtering on the `Browse All` option. Long term, we'd like to utilize pagination on the backend.
