### ISSUE TITLE
Component: Sidebar render() assumes this.props.children is Array

### ISSUE THREAD

**Issue by coderkevin** [Automattic/wp-calypso#6194]
#### Steps to reproduce
Use Sidebar component with a single child component.

#### What I expected
Sidebar to render correctly

#### What happened instead
`Uncaught TypeError: this.props.children.some is not a function`

#### Browser / OS version
N/A

#### Screenshot / Video
N/A

#### Context / Source
Using Calypso as a Framework, I added a single SidebarMenu component to a Sidebar component.
From the [React Docs](https://facebook.github.io/react/tips/children-props-type.html), it says "...when there is only a single child, this.props.children will be the single child component itself without the array wrapper."

In the render() function of sidebar/index.jsx:
```let hasRegions = this.props.children.some( el => el.type === SidebarRegion );```

This causes the problem. The React docs recommend using [React.Children as an alternative](https://facebook.github.io/react/docs/top-level-api.html#react.children)

**Comment by coderkevin** [comment]
This can be reproduced with the wp-calypso project itself by editing client/reader/sidebar, and removing all but one child component in the Sidebar component.

**Comment by lancewillett** [comment]
Fixed in https://github.com/Automattic/wp-calypso/commit/dfa3a601eccc6603c4a055053f5884f9c93a5cfb
