### ISSUE TITLE
WooCommerce UPS: Add marketplace entry

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61944]
Add marketplace product entry
- [x] Add store product translation, example D76326-code
- [x] Add marketplace product entry to endpoint (and image if required), example D76441-code
- [x] Insert vendor product info, documentation: PCYsg-CJy-p2
- [x] Post on atomicp2, example p9o2xV-1Wj-p2

**Comment by lsl** [comment]
- [x] Translation D76709-code
- [x] Marketplace entry D76710-code
- [x] Atomic p2 request draft: ~9o2xV-p2 ?p=7524~ link not working, see slack for working draft link. p1647842329179439-slack-C029JEQRVRT

**Comment by lsl** [comment]
~Waiting on an [updated image](https://github.com/Automattic/wp-calypso/issues/61548), using the png as a placeholder for now.~ replaced with svg.

**Comment by lsl** [comment]
Need reviews on the now updated D76709-code and D76710-code

**Comment by paulopmt1** [comment]
Those diffs are now in production.
I'll track the P2 request on the [main task](https://github.com/Automattic/wp-calypso/issues/61918). Moving this one to complete.
