### ISSUE TITLE
Jetpack Plans: use select menu for monthly/yearly billing options

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6195]
Recently we launched Monthly pricing. A link toggles prices from monthly to yearly. This link is above the plans and easy to miss. It's also not a form field and thus not part of the 'form' of selecting and submitting a plan.

Instead, let's swap the plan subheading with a select menu like this:

<img width="718" alt="screen shot 2016-06-21 at 2 49 25 pm" src="https://cloud.githubusercontent.com/assets/437258/16245651/d9578320-37cf-11e6-9e3e-87e4b8f67c31.png">

(The screenshot shows the new version of the plans page, but the dropdown will fit in the current design as well.)

The price will be shown 'per billing cycle' so cost-per-month for monthly and cost-per-year for yearly. We will need to perform the cost-savings calculations as well. 

cc @johnHackworth

**Comment by tyxla** [comment]
I'm closing this one in favor of https://github.com/Automattic/wp-calypso/issues/6301, where @rickybanister has expanded the idea and suggested using a segmented control instead of a select menu.
