### ISSUE TITLE
[Bug]: CoBlocks Masonry images disappear in mobile/tablet preview

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#61961]
### Quick summary

When adding pictures to a page or post using **CoBlocks**'s _Masonry_ block, the pictures will disappear and show a blank page in the mobile and tablet preview. Here's a recording of the issue:

https://user-images.githubusercontent.com/6737345/159865638-89580854-84de-4c94-9196-719cfd6d595c.mp4

### Steps to reproduce

1. Create a new page/post on an AT site at WordPress.com.
2. Add the _Masonry_ block with some pictures.
3. Click the _Preview_ button and choose either the mobile or tablet option.
4. Notice the pictures disappear.
5. Switch back to the desktop preview and the pictures will be visible again.

### What you expected to happen

I expected the pictures would stay in the preview window instead of disappearing.

### What actually happened

- The pictures added to the block disappear leaving a blank space on the mobile/tablet preview. Adding the block again in the preview mode gives you the option to upload another picture, but as soon as it's loaded, it disappears as well.
- Although images disappear from the preview, they are still visible on the live site on mobile/tablet.

### Context

Customer report

### Simple/Atomic

Atomic

### Other notes

This doesn't happen on a regular WordPress site.

### Reproducibility

Consistent

### Severity

All

**Comment by Robertght** [comment]
Installing the latest version of the plugin got rid of the issue.

Similar fix to this: https://github.com/Automattic/wp-calypso/issues/60353#issuecomment-1072968422

**Comment by JoshuaGoode** [comment]
Discussed managed Atomic version updates internally.

p9o2xV-1Yw-p2

**Comment by Robertght** [comment]
Closing this one as it's already fixed.
