### ISSUE TITLE
Wording change on the Domain Connection settings screen.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#61999]
### What

Currently the wording on the Domain Settings page at Upgrades > Domains > Click 3 dots and "View Settings" always says "Domain Connection Expires on..." :

![Annotation on 2022-03-16 at 16-03-30](https://user-images.githubusercontent.com/49131029/158698899-21378a28-cd1d-43b9-8b91-543d9e28c4b2.png)

This creates some confusion when on the Purchases screen the plan says "Auto Renews on..."

![Annotation on 2022-03-16 at 16-05-34](https://user-images.githubusercontent.com/49131029/158699136-b521acd3-0846-4dcd-bda4-5fe9b0a53b56.png)

It would be ideal if they both communicated the same wording to avoid confusion.

Customer reported here: 4860688-zen

### Why

It can be confusing to users to see that their plan is setup to auto-renew but the domain connection then says it will expire with the plan instead.

### How

It would require changing the Domain Connection screen so it can detect if the plan is going to auto-renew and then adjust the wording appropriately.

**Comment by delputnam** [comment]
This is a great suggestion. Thank you for the feedback. I'll create a task for us (Nomado) to handle this in a future sprint. We'll update this issue once we have deployed the update.

**Comment by daledupreez** [comment]
Closing this issue as it was fixed by #62514.
