### ISSUE TITLE
Mayland (Blocks) not showing social icons on Social Navigation menu location

### ISSUE THREAD

**Issue by wiesenhauss** [Automattic/wp-calypso#61996]
### Quick summary

When using the Mayland (Blocks) theme, the social icons are not displayed when social links are used in the Social Navigation menu location:
<img width="305" alt="Screen Shot 2022-03-16 at 16 57 32" src="https://user-images.githubusercontent.com/99455043/158679432-e3246e55-0bde-4f7b-8485-38b3dffbc4d1.png">

### Steps to reproduce

1. Create new menu 
2. Set menu location to "Social Navigation"
3. Add custom link with any social media URL (e.g. https://www.facebook.com/socialprofile)
4. Save menu and preview site

### What you expected to happen

Custom social media links should display a social media icon when the menu location is set to "Social Navigation", just like in the theme preview image: https://br.wordpress.org/themes/mayland-blocks/

### What actually happened

Social icons are not displayed. Instead, a generic "sharing" icon appears: 

<img width="305" alt="Screen Shot 2022-03-16 at 16 57 32" src="https://user-images.githubusercontent.com/99455043/158679432-e3246e55-0bde-4f7b-8485-38b3dffbc4d1.png">

When changing the theme to [Mayland](https://wordpress.com/theme/mayland), the social icons are correctly displayed:

<img width="338" alt="Screen Shot 2022-03-16 at 17 04 29" src="https://user-images.githubusercontent.com/99455043/158681154-23058c7e-de5a-4c97-877c-2bc5d1ebe59e.png">

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Mayland (Blocks)

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

When changing the theme to [Mayland](https://wordpress.com/theme/mayland), another version of Mayland (Blocks), the social icons are correctly displayed.

**Comment by Robertght** [comment]
Thank you for reporting this! I'm closing it favor of https://github.com/Automattic/themes/issues/5673
