### ISSUE TITLE
Marketplace: Add WooCommerce USPS

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#62005]
Add USPS Shipping method extension to the marketplace

Documentation: PCYsg-AhH-p2
URL https://woocommerce.com/products/usps-shipping-method/
Slug: `woocommerce-shipping-usps`
Name: `WooCommerce USPS Shipping Method`

### Add billing products
 - [x] Post preflight p2, example pdh6GB-vf-p2
 - [x] Add product, yearly, monthly plans see docs PCYsg-CJy-p2

### Create store products
 - [x] Reserve store product ID's, example D76056-code
 - [x] Add catalog mapping, example D76057-code
 - [x] Generate store products, docs PCYsg-CJy-p2
 - [x] Add store product translation, example D76326-code
 - [x] Add marketplace product entry to endpoint (and image if required), example D76441-code
 - [x] Insert vendor product info, documentation: PCYsg-CJy-p2
 - [ ] ~Post on atomicp2, example p9o2xV-1Wj-p2~ don't need this p1647967541159849/1647967069.454849-slack-C029JEQRVRT

### ~Release~
- [ ] ~Create diff to remove a11n only flag (ready for launch), example D76705-code~
- [x] ~Confirm plugin can be purchased and installed by non a11n users~
- [ ] ~Merge diff~

^ Can skip last steps by merging D77429-code without the a11n check, it's already managed so we don't really need to do the extra steps.

**Comment by lsl** [comment]
- [x] Preflight pdh6GB-vf-p2

**Comment by paulopmt1** [comment]
- [x] Reserve store product IDs. Phabricator code here: D77209-code

**Comment by paulopmt1** [comment]
- [x] Add catalog mapping. Phabricator code here: D77212-code

**Comment by paulopmt1** [comment]
- [x] Add WooCommerce Shipping USPS translation mapping. Phabricator code here: D77328-code

**Comment by paulopmt1** [comment]
- [x] Add marketplace product entry to endpoint. Phabricator code here: D77429-code

**Comment by lsl** [comment]
We can skip the release steps by merging D77429-code without the a11n check, it's already managed so we don't really need to do the extra steps. p1647967541159849/1647967069.454849-slack-C029JEQRVRT

In other words this task only has one step left:

- [x] Add catalog info, making the plugin available for purchase to all users (D77429-code)

**Comment by lsl** [comment]
FYI D77429-code should be fine, there is a failing jetpack test but it looks flaky, just rerun the build from phabricator until it passes. ("Restart build" on the right sidebar of the build page)

**Comment by paulopmt1** [comment]
Deployed and tested on prod with a non a11n with @allilevine.
