### ISSUE TITLE
Kerr preview in Design Picker is broken

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#62004]
### Observed
Broken layout
![image](https://user-images.githubusercontent.com/5665959/158722791-ef436963-e26b-4b39-91fd-6cff917fb243.png)
![image](https://user-images.githubusercontent.com/5665959/158722807-749e08df-36fd-428c-9683-095422d3c69d.png)

### Expected
To be like demo site
![image](https://user-images.githubusercontent.com/5665959/158722948-5cb23d0f-8c43-4447-8caf-9907ed092b60.png)

## Related
possibly related https://github.com/Automattic/wp-calypso/issues/61661

**Comment by fushar** [comment]
Fixed on D76934-code.

**Comment by fushar** [comment]
Kerr on Design Picker after shipping the fix:

![image](https://user-images.githubusercontent.com/1525580/158737028-0ebd851a-8d38-4bf7-b569-dc38a931c7eb.png)
