### ISSUE TITLE
Storefront: Subscription forms Cut Off at the Bottom

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#62002]
### Quick summary

The subscription form block is cut off when using the Storefront theme. Changing the block settings does nothing. Does not happen on other themes.

### Steps to reproduce

1. Install and activate the Storefront theme on an atomic site.
2. Create a new post or page, or edit an existing one.
3. Add, optionally inside a cover block, the subscription form to that post or page.

### What you expected to happen

The subscription form should be fully viewable.

### What actually happened

Border is cut off at the bottom.

### Context

Reported in 4867718-zd-woothemes and tested by another HE (their notes are in the interaction).

![image](https://user-images.githubusercontent.com/6737345/159782135-c79122d9-51b4-4d40-8c6e-2526fcc11877.png)

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Storefront

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

There is no user impact

**Comment by Robertght** [comment]
Hey @arinoch !

Thank you for reporting this!

I am unable to replicate this issue with Storefront at the moment and I cannot see the issue on the user's site either. I'm going to close this, but please re-open if needed.
