### ISSUE TITLE
WordPress.com editor promo has English "Try it Out!" button in German language version

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#62008]
### Quick summary

When opening a new post/page for the first time, there is usually a promo window with a small introduction to the block editor/WordPress.com editor. In the German version of this, the "Try it out" button is in English and not localized.
![Markup on 2022-03-17 at 13:24:54](https://user-images.githubusercontent.com/83020905/158760115-79a680bf-0f68-430e-abab-3b626c3d5f05.png)
.
![Markup on 2022-03-17 at 13:45:43](https://user-images.githubusercontent.com/83020905/158760130-380df6e3-18b9-449d-8b58-34a5b7191123.png)

### Steps to reproduce

1. Set UI to German
2. Be on a recently made site
3. Add a new post/page
4. Message will pop up and the "Try it out" button is not localized

### What you expected to happen

"Try it out!" button should be localized into German

### What actually happened

"Try it out!" is in English without localization.

### Context

Discovered this when working on a user's site. Reproduced on a new test site with language set to German.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by formosattic** [comment]
Hi @kuropixel , thanks for the report, it looks like this string wasn't part of the translation we take care in-house, and indeed show untranslated:

 * https://translate.wordpress.com/projects/wpcom/de/default/?filters%5Bterm%5D=Try+it+Out&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

This is something that we welcome users to translate, see https://wordpress.com/support/language-settings/#translating-your-site-interface-amp-admin-screens

That said, it's a string we probably want translated across all languages I've pinged i18n to review and handle this internally, see p1648545971261839-slack-C02AED43D 

Will close as this is a translation request, not really a bug.
