### ISSUE TITLE
Public API [Bug]: Theme search for "twentytwo" returns no results

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#62016]
### Quick summary

When searching for "twentytwo" (or "twenty-two") using the `/rest/v1.2/themes` endpoint, we get no results

### Steps to reproduce

1. Visit https://public-api.wordpress.com/rest/v1.2/themes?http_envelope=1&search=twentytwo&page=1&tier=&filter=&number=100
2. Visit https://public-api.wordpress.com/rest/v1.2/themes?http_envelope=1&search=twenty-two&page=1&tier=&filter=&number=100

### What you expected to happen

I expected to see the Twenty Twenty Two theme in the results.

### What actually happened

No results.

Visiting https://public-api.wordpress.com/rest/v1.2/themes?http_envelope=1&search=twentytw&page=1&tier=&filter=&number=100 (search for "twentytw") _does_ include the Twenty Twenty Two theme in the results.

### Reproducibility

Consistent

**Comment by markbiek** [comment]
Not sure what the fix is but I have a little more information.

I think the issue is because we're using [Match phrase prefix](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase-prefix.html) when we query Elasticsearch.

The short version of how `phrase_prefix` search work is 
> Returns documents that contain the words of a provided text, in the same order as provided. The last term of the provided text is treated as a [prefix](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html), matching any words that begin with that term.

I believe that's why the search `twentytwo` doesn't return anything but `twentytwe` _does_ return results. If you look at the theme `slug` field, the latter is matching `twentytwenty` but the former doesn't match anything because it's not searching far enough into the `slug` field.

Some additional query and testing details here:
p1647879717466529-slack-C0Q664T29

**Comment by markbiek** [comment]
A [`query_string`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) query seems to produce better results:
```
{
	"query": {
		"query_string": {
			"query": "*twentytwo*",
			"fields": [
				"name^20",
				"slug^20",
				"taxonomy.theme_subject.name^15",
				"taxonomy.theme_feature.name^10",
				"taxonomy.theme_color.name^10",
				"taxonomy.theme_style.name^10",
				"taxonomy.theme_column.name^10",
				"taxonomy.theme_layout.name^10",
				"author^10",
				"description_long"
			]
		}
	}
}
```

The `es-search-api.php` already supports `query_string`s so I'm investigating how we might leverage that in the theme search API call.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 ACTIONS
- Closing based on the status updates in the history of the issue.
