### ISSUE TITLE
Stats Insights - Comments by Author counts are wrong

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#62035]
### Quick summary

I received a report of a site where the stats in the **Comments by Author** section on the **Stats > Insights** tab do not match the number of comments found for that author in the **Comments** section of the dashboard.
See slack discussion: p1647552043886979-slack-C02DQP0FP

### Steps to reproduce

I have not reproduced this but have an example of a site where this is occurring.

### What you expected to happen

I would expect the count shown in the **Comments by Author** section to match the counts for that author in the **Comments** section of the dashboard.

### What actually happened

The counts in the **Comments by Author** section were much less.

### Context

4869407-zen
slack: p1647552043886979-slack-C02DQP0FP

### Simple, Atomic or both?

Simple

**Comment by aidvu** [comment]
Fixed. The Comments by Author section was approximate (looking only at most recent comments). I've updated the code to show correct counts.
