### ISSUE TITLE
Plugin installed badges: Alignment between paid / free

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#62038]
On https://wordpress.com/plugins, the free rating bar should be inline with the paid one. Also the rating bar looks like it's not vertically centered with the text but that's pretty minor.

![Screenshot(74)](https://user-images.githubusercontent.com/811776/158915025-58d97ae1-6ea4-4b7a-bdd3-cc95738bf0aa.png)

- [ ] Align free rating bar with paid
- [ ] Align rating stars with text

**Comment by gcsecsey** [comment]
I think we need a design decision to resolve this issue, as both the description and footer heights are dynamic.

Currently, there's a `margin-top: auto` rule on the additional info row. If we were to update that to `margin-bottom: auto`, it would fix the original scenario:
![image](https://user-images.githubusercontent.com/11555574/162427860-b3866740-b8e6-4d49-b3cb-8779d3517b3d.png)

However, it would cause a similar issue, when two plugins' descriptions are not the same length:
![image](https://user-images.githubusercontent.com/11555574/162427934-b2d106d6-eaf2-4a1c-a011-ebae56639403.png)

Maybe a good overall solution could be to inline the `Active`/`Inactive` labels. That would make it easy to display the rating bar the same way, even if the descriptions are different heights.
<img width="940" alt="image" src="https://user-images.githubusercontent.com/11555574/162429122-027e863d-e7ea-4ba3-b292-f12759fcd1eb.png">
<img width="937" alt="image" src="https://user-images.githubusercontent.com/11555574/162429533-40846cca-4206-4b8a-b928-9ef003b2fe0e.png">

**Comment by lsl** [comment]
@vinimotaa / @SaxonF, I'm thinking sticky these to the bottom of each card and truncate long descriptions. Thoughts? Decisions?

**Comment by vinimotaa** [comment]
hey @lsl I think is a good solution for the time being! At some point we'll slightly update these card designs with all the edge cases we're identifying.

**Comment by WBerredo** [comment]
Is this still an issue after pdh6GB-2At-p2?

**Comment by vinimotaa** [comment]
@WBerredo def. not W.!

**Comment by WBerredo** [comment]
Not an issue anymore after pdh6GB-2At-p2
