### ISSUE TITLE
Post Carousel Block image glitch on AutoPlay in Safari 

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#62036]
### Quick summary

Images in Post Carousel block glitch briefly as they scroll to the next image in the Safari browser.  This happens when the autoplay setting is enabled. 

### Steps to reproduce

1. Add a Post Carousel block to a page and add images. 
2. Turn autoplay on.
3. View page in Safari

### What you expected to happen

The Block seamlessly autoplay to the next image

### What actually happened

There is a flash when it auto-plays to the next image. 

https://user-images.githubusercontent.com/74204272/158906529-d224c540-0763-4b35-957f-e121e0b27053.mov

### Context

A user came to chat (34729793-hc) and mentioned that there was a glitch with the Post Carousel block on the homepage. I was able to recreate the same issue on my test site. 

The user had InterGalatic 2 theme. However, my test site currently has a different theme, SkatePark and the issue still persists. 

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Safari 

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is turning autoplay off but does not really fix the issue. Also, the carousel block seems fine on other browsers

**Comment by galakhyati** [comment]
Unable to replicate the issue on Atomic as well as on Simple sites. Tested both the sites on Intergalactic 2 theme. Checked on Safari as well as on Chrome, worked fine on both the browsers. Closing the issue.
