### ISSUE TITLE
Marketplace: Icons from JITM are not consistent

### ISSUE THREAD

**Issue by lupus2k** [Automattic/wp-calypso#62032]
### Details

Messages in Jetpack/Atomic sites or simple sites result differently as Jetpack uses some internal logic to render icons before returning the JSON.

#### Simple sites ####
It returns a string as an icon
<img width="665" alt="image" src="https://user-images.githubusercontent.com/402286/158886394-5401942c-ef87-4b27-b1f6-8f262e41803e.png">

#### Atomic/Jetpack sites ####
Returns a div with the icon in SVG but only for `jetpack` or `woocommerce` icons, otherwise, it returns empty.
![image](https://user-images.githubusercontent.com/402286/158885691-a1749390-b302-4f85-8fd9-a9adbae60bbe.png)

Because there are a lot of sites using different versions of jetpack and to avoid modifications within jetpack on each new plugin, I proposed to add the field `iconPath` within the content of the JITM message.

### Checklist

- [x] Add the field `iconPath` in the content of the jitm-message
- [x] Add `with_icon_path` function to jitm-engine
- [x] Implement `iconPath` instead of `icon` for spotlight template
- [x] Add `iconPath` to Spotlight JITM rules

**Comment by lupus2k** [comment]
1 and 2 from the checklist are resolved here: D77013-code

**Comment by allilevine** [comment]
Closed by D77013-code and #62077
