### ISSUE TITLE
Domain Management: Improve visibility when an email forwarding is setup

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#6203]
If email forwarding is already setup, when going to the Domain Settings page, and clicking on Email, I expect to see the current mail configuration in place.
<img width="676" alt="screen_shot_2016-06-22_at_14_50_49" src="https://cloud.githubusercontent.com/assets/15944096/16257297/39d22650-388a-11e6-991b-d1ac81b7f593.png">

Instead I have this below. The **Add Email Forwarding** button is a bit misleading, as it gives me the impression that no email forwarding is setup already:
<img width="677" alt="screen_shot_2016-06-22_at_14_50_57" src="https://cloud.githubusercontent.com/assets/15944096/16257383/d62e6478-388a-11e6-9877-d13f9cdd5c60.png">

Clicking on **Add Email Forwarding** does take me to the current email forwarding setup though.
<img width="673" alt="screen_shot_2016-06-22_at_14_51_07" src="https://cloud.githubusercontent.com/assets/15944096/16257435/34faf3f4-388b-11e6-9c6d-3ca63cbfd180.png">

To avoid some confusion, we could: display the email forwarding settings on the Email page (second image), while also offering some brief information about the advantages of switching to a full email hosting, with a link to https://en.support.wordpress.com/add-email/.

**Comment by kriskarkoski** [comment]
This has changed somewhat but is still less than ideal. It now shows you have forwards active and prompts you to manage them:

<img width="721" alt="Screen Shot 2020-06-10 at 11 29 51 PM" src="https://user-images.githubusercontent.com/1900444/84341946-5e9a1880-ab72-11ea-9cd4-8c0bdee19f0c.png">

But clicking this shows a prompt for G Suite with an additional click on Email Forwarding required to actually manage them. Linking directly to /email/domain/forwarding/ with an integrated upsell would be better for ease of use.

**Comment by klimeryk** [comment]
As Kris mentioned above, it's a bit better now and the email forwards are mentioned in the overview of all domains and in the domain's details page as well.

<img width="1064" alt="Screenshot 2021-02-02 at 11 27 21" src="https://user-images.githubusercontent.com/3392497/106594174-a75f7100-6549-11eb-9d69-b7611da27e38.png">


But it's still a bit PITA to get to the manage email forwarding page - you have to notice the "Manage email forwarding" button:

<img width="1061" alt="Screenshot 2021-02-02 at 11 27 03" src="https://user-images.githubusercontent.com/3392497/106594160-a1699000-6549-11eb-897c-22a8fabba99e.png">

However, as we're pushing towards W Email solution, I'm afraid that's the best we can do right now, so closing as wontfix 🙇
