### ISSUE TITLE
Text blocks’  (ie.: Paragraph, Heading, Quote, List) Toolbar Appearance settings, forcibly overwrites the Sidebar Appearance settings

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#62047]
### Quick summary

Screen recording: https://cln.sh/tKZt85

### Steps to reproduce

Steps:
- Add any of these blocks: Paragraph, Heading, Quote, List
- In the Hovering Toolbar, if you use either the Bold or Italics feature,
![CleanShot 2022-03-17 at 12 03 37](https://user-images.githubusercontent.com/84539773/158983446-9663c7a7-7560-466d-8858-1a9d54358da1.jpeg)
- It will always forcibly overwrites the Appearance settings in the sidebar.

### What you expected to happen

Even though I use the Bold or Italic font settings in the hover toolbar, it should not overwrite the Appearance settings in the sidebar. This can be confusing. If the Toolbar Bold setting is selected, when I change it to a non-bold setting in the Appearance, it should disable the Toolbar Bold setting.

### What actually happened

Toolbar options forcibly overwrite the settings.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

You will need to disable the Toolbar settings first to apply the other settings.

**Comment by Greatdane** [comment]
Confirmed. 

Above video for reference;

https://user-images.githubusercontent.com/5075840/160982955-461c682e-7f6d-4764-8cea-98f4345b147b.mp4

**Comment by jordesign** [comment]
Popping this back into the Triage queue - can we please check in a self-hosted install and if it occurs there, report in the Gutenberg repo.

**Comment by Greatdane** [comment]
Actually going to close this now as can no longer reproduce.
