### ISSUE TITLE
FSE: Site logo does not center in Editor, but it respects it on the live site

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#62043]
### Quick summary

Recording: https://cln.sh/oLvgS0

Steps:
- Insert Site logo
- Align to the middle (does not show in Editor)
- Save/ save changes
- Alignment applied on the live site

### Steps to reproduce

Steps:
- Insert Site logo
- Align to the middle (does not show in Editor)
- Save/ save changes
- Alignment applied on the live site

### What you expected to happen

The center alignment would show up in the Editor as well, not only on the live site.

### What actually happened

The Editor does not show the center alignment setting.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

No workaround is needed because the alignment is applied, but it is confusing.

**Comment by Greatdane** [comment]
This seems to happen on Calypso only, core Gutenberg editor (self-hosted) works as intended.

**Comment by Greatdane** [comment]
Above video:

https://user-images.githubusercontent.com/5075840/160982419-189ff543-c670-40e2-9d95-03103559bb95.mp4

**Comment by arunsathiya** [comment]
Something is off with my test site. I don't see "Site logo"'s alignment options. 🤔 I tried Hari and Heiwa themes.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/18581859/170665409-9083ea9e-81f2-49f7-871b-a71a3698d426.png">

Do you mind testing once again, @csabarakasz or @Greatdane?

**Comment by csabarakasz** [comment]
@arunsathiya I could not reproduce this error again on my test site.

**Comment by Addison-Stavlo** [comment]
> Something is off with my test site. I don't see "Site logo"'s alignment options. 🤔 I tried Hari and Heiwa themes.

I think you might need to put it inside a container block (group, template part, etc.) to get that alignment option currently.

> @arunsathiya I could not reproduce this error again on my test site.

It looks good to me now as well. The logo centers visually in the editor with the option, and that is reflected correctly on the front end.

Feel free to re-open if still experiencing.
