### ISSUE TITLE
FSE: Timeline block alignment settings show up wrong with the Alternate feature

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#62044]
### Quick summary

Recording of the issue: https://cln.sh/eNqCP3

Steps

- Add a new timeline block
- First, the Alternate feature alignment settings show up (without it turned on) 
- Turn on the Alternate items feature
- The alignment setting works
- When we turn off the Alternate feature now, it will not show the alignment settings as expected

### Steps to reproduce

Steps

- Add a new timeline block
- First, the Alternate feature alignment settings show up (without it turned on) 
- Turn on the Alternate items feature
- The alignment setting works
- When we turn off the Alternate feature now, it will not show the alignment settings as expected

### What you expected to happen

It should not show the alignment settings when the alternate items feature is not turned on.

### What actually happened

When you first insert a Timeline block, the alternate settings show up, even though it is not applicable. 

### Context

It is confusing.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/61490
