### ISSUE TITLE
[Bug]: Block previews not being displayed in block inserter panel

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#62055]
### Quick summary

Block previews are missing from the block inserter panel in the page/post editor. 

### Steps to reproduce

1. Toggle the block inserter
2. Mouse over a block icon
3. Notice that there are no block previews loading

### What you expected to happen

Previously, hovering your mouse over a block icon toggled a block preview, much like this:

![Capture_2022-03-17 at 11 37 57](https://user-images.githubusercontent.com/2912202/158996350-c379752b-7b35-48a6-a0d0-b8d771826ee4.gif)

Note: This GIF demonstrates a separate issue I intended to report when hovering over the Tiled Gallery Block.

### What actually happened

Hovering over a block icon does not trigger a block preview. See here:

![Capture_2022-03-18 at 11 33 46](https://user-images.githubusercontent.com/2912202/158996577-13820d6d-f542-43c6-9a5d-ee378fdea642.gif)

### Context

Internal testing and reporting

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Other notes

Gutenberg 12.8.0 was released on 2022-03-17 and seems to have resulted in this change.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by brinbliss** [comment]
Report from 4886246-ZD about this bug as well.

**Comment by edequalsawesome** [comment]
This is a bug with the latest release of Gutenberg -- it's been reported here! https://github.com/WordPress/gutenberg/issues/39699

**Comment by talldan** [comment]
It should be fixed by this PR - https://github.com/WordPress/gutenberg/pull/39620

The original bug report is here - https://github.com/WordPress/gutenberg/issues/39582.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- https://github.com/WordPress/gutenberg/pull/39620 was merged

📌 ACTIONS
- Closing as Fixed
