### ISSUE TITLE
[Bug]: Global Styles missing from the page template editor in the Page editor

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#62058]
### Quick summary

The Global Styles panel is not available when enabling the template editor from the Page editor. It is, however, available when editing the template from _Appearance_ > _Site Editor_ > _Templates_. See here:

https://user-images.githubusercontent.com/2912202/159001539-75fb8c4b-ce21-4552-98ab-a5f365f5ab26.mp4

### Steps to reproduce

1. In a Page editor window, click to edit the applicable template in the editor sidebar.
2. Observe that there is no Global Styles toggle in the upper right.
3. Head to _Appearance_ > _Site Editor_ > _Templates_ and open a template to edit.
4. Observe that Global Styles is available in the upper right.

### What you expected to happen

I expected a consistent experience in that the Global Styles option should be available when editing a template through a Page editor.

### What actually happened

The Global Styles toggle is not available when editing a template through the Page editor, but it is available when editing a template through _Appearance_ > _Site Editor_ > _Templates_.

### Context

Internal testing and reporting

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment]
This happens on self-hosted as well, so posted as a core Gutenberg issue here;
https://github.com/WordPress/gutenberg/issues/40125

Added to Cross-repo Watchlist
