### ISSUE TITLE
Users are taken to the Posts section instead of My Home after accepting invites to manage new FSE sites

### ISSUE THREAD

**Issue by sguzovskaia** [Automattic/wp-calypso#62053]
### Quick summary

1. After accepting an invite to manage a site, users are taken to the Posts section instead of My Home

![Markup on 2022-03-17 at 10:40:23](https://user-images.githubusercontent.com/47414943/158984588-dedb48a7-2997-46fb-a284-bd651a54aa8f.png)

2. The notification has a link to the old [Learn WordPress](http://learn.wordpress.com/) site.

`Not sure where to start? Head on over to Learn WordPress.`

### Steps to reproduce

1. Invite a second account to the site as admin
2. Accept invite either through notification center or email notification
3. After accepting the invite, the user is taken to the Posts section

### What you expected to happen

1. I was expected to be taken to My Home section.

The notification states:

`This is your site dashboard where you will be able to manage all aspects of fsesandbox`

The message is confusing since the site dashboard is clearly not the Posts section. My Home is a more logical place to start with your site.

2. Since all new sites are automatically set up with Site Editor and Block theme, I expected to be taken to the FSE support article or tutorial after clicking the link in the message `Not sure where to start? Head on over to Learn WordPress.`

### What actually happened

1. After accepting an invite to manage a site, I was taken to the Posts section.

2. Clicking on the link in the notification message took me to the old Learn WordPress site (http://learn.wordpress.com/), which is focused on sites using old themes and Customizer.

`Not sure where to start? Head on over to Learn WordPress.`

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

**Comment by Greatdane** [comment]
Confirmed on Simple and Atomic; https://d.pr/i/zBtFaZ

**However**, I don't think it is related to FSE. I invited an admin to an old site with an old theme, and still arrived in the post section.
