### ISSUE TITLE
Remove retired theme mentions from learn.wordpress.com

### ISSUE THREAD

**Issue by geekinthegirl** [Automattic/wp-calypso#62057]
### What

Retired themes are mentioned and previewed on our learn.wordpress.com resource - specifically the Natural theme, on the 'Get Configured' page: https://wordpress.com/learn/get-configured/

<img width="1443" alt="Screenshot 2022-03-18 at 11 47 58" src="https://user-images.githubusercontent.com/22247240/159000096-83c5fb9f-84de-46be-97fd-5f9705aa439d.png">

It may also be worth updating the view of the theme gallery here: https://wordpress.com/learn/get-personality/

### Why

If we direct users to this resource, showing them screenshots of retired themes they can no longer use isn't ideal - they'll be unable to find or use retired themes from the theme gallery directly.

### How

Take new screenshots of the theme gallery and a custom header theme, and replace existing screenshots on the site.

**Comment by Robertght** [comment]
Closing in favor of this 1508-gh-Automattic/en.support-docs-content
