### ISSUE TITLE
Devdocs App Components are broken

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#6205]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/devdocs;
2. Click on App Components in left sidebar;
3. See blank page;
4. Open Dev Console and see errors.

#### What I expected

Page displaying App Components

#### What happened instead

Blank page

#### Browser / OS version

Latest Chrome, Ubuntu 16.04.

#### Screenshot / Video

![selection_045](https://cloud.githubusercontent.com/assets/4988512/16262092/7f5b35e8-386e-11e6-8da3-1634dba72dfb.jpg)

#### Context / Source

Happens on https://wpcalypso.wordpress.com/devdocs too.

cc @blowery as the error is coming from `PostCards` devdocs file and you are on git blame list of authors. :) (maybe you'll know better what is happening)

**Comment by blowery** [comment]
Looking
