### ISSUE TITLE
Marketplace: Plugin installation progress bar

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#62067]
The progress bar in plugin installation seems not progressing in Step 2 and goes directly to Step 3. This happens especially when site is transferred to Atomic at that point of time.

**Steps to reproduce:**
- On your simple business site
- Go to plugins
- Pick any free plugin and proceed to installation

**Result:**
The progress bar simulates to step 1 and 2, then it gets stuck to 2 (66.6%?) for some seconds and then suddenly goes to 3. 

**Note:**
This is mostly a problem when sites move from simple to Atomic infrastructure. This process might even take 1 minute (or more in edge cases with sites having a lot of content).

**Suggestion:**
Can we find a silver lining in simulating this progress bar or even notifying the user that the operation is still in progress?

cc: @vinimotaa , @SaxonF 

related convo: pdt2If-6r-p2

**Comment by cpapazoglou** [comment]
Generally, at any point that a site needs to go Atomic we have no indication of that process percentage completion. @jmdodd am I missing something? Is there a way to evaluate the time needed for a site to be transferred to Atomic or adding a `completion` percentage to `/sites/${ siteId }/automated-transfers/status` API?

**Comment by gcsecsey** [comment]
@SaxonF could you please take a look at this?

**Comment by gcsecsey** [comment]
@jmdodd could you please help us find a way to estimate the time needed for the Atomic transfer?

@SaxonF could you please help us decide what would be a good visual feedback for the users?

**Comment by SaxonF** [comment]
Apologies for missing this @gcsecsey . Couple of suggestions.

Add a subtle loading animation to progress bar e.g. https://codepen.io/saxonfletcher/pen/JjpRwed

If we expect an action to take longer than say 7 seconds, maybe we can rotate between labels? We do something similar during site creation. So each step in the loading component would accept either a string or an array of strings that are rotated between every 7 seconds. e.g. ["Installing plugin", "Connecting the dots", "Still working...", "Wheels are in motion", "Working magic"]

**Comment by gcsecsey** [comment]
@SaxonF sounds great, thanks!
