### ISSUE TITLE
Design Picker: Add tracks events for Upgrade Button on Premium Themes

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#62074]
I think we will need/want two events here.

1. Design picker grid upgrade button, prop for theme.
2. Design preview upgrade button, prop for theme.

**Design picker grid upgrade button, prop for theme**

![image](https://user-images.githubusercontent.com/545779/159049275-898cc2e8-b238-44fc-a6fb-da6aed800edd.png)

**Design preview upgrade button, prop for theme**

![image](https://user-images.githubusercontent.com/545779/159049336-e2e272c6-bbfb-4452-b8a6-f4e215c18491.png)

**Comment by nelsonec87** [comment]
@blackjackkent Is [registering the events](PCYsg-mUj-p2) something I can do, or it should be done by a different team?
