### ISSUE TITLE
Tortuga: Preview of embedded link is not working on some page

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#62082]
### Quick summary

The user has Tortuga theme on their site. They have [this link](https://doltd.blog/2020/02/21/opinion-why-you-should-subscribe-to-dip-for-5-99-monthly-by-s-j-thorley/) embedded in the sidebar using Embed block.

On some pages, the preview of embed is not showing up.

e.g: 
https://doltd.blog/contact-us/
https://doltd.blog/

### Steps to reproduce

Was not able to reproduce it on my test site.

### What you expected to happen

![image](https://user-images.githubusercontent.com/33957570/159113315-4e943452-8941-4af1-9e94-d7d42c70c5db.png)

### What actually happened

![image](https://user-images.githubusercontent.com/33957570/159113320-4ed11d2c-bb41-46fe-93a6-a7be7f0f7e2c.png)

### Context

Ticket: 4873835-zen

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Tortuga

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
What I did was to remove the last "/" from that embed block and that worked, but I think that's a glitch considering how many widgets there are on the website.

I'm going to close this one for now.
