### ISSUE TITLE
[Bug]: Pre-Publish Check sidebar refreshes and removes Tags & Categories cards

### ISSUE THREAD

**Issue by fresatomica** [Automattic/wp-calypso#62091]
### Quick summary

When playing around with the Social Preview for too long, it eventually refreshes, and when that happens, the boxes to add tags and categories disappear. If you close the preview, though, the tags you've added are still on the post.

### Steps to reproduce

1. Create a post
2. Click the "Publish" button and wait for the Social Preview to appear
3. Play around for a couple of minutes and wait for the whole sidebar to refresh
4. Look for Tags/Categories - they are nowhere to be found

### What you expected to happen

The sidebar shouldn't randomly refresh, and everything should look just like before, even if it does.

### What actually happened

The sidebar refreshes and you are no longer able to add tags or categories unless you close the preview and go back to post editing. The user caught it on a screencast here: https://gyazo.com/97ce0ad119a61e5c0f4fd9dca2f81c1a.

### Context

Reported here: https://wordpress.com/forums/topic/pre-publish-checks-sidebar-and-jetpack-iframe-conflict/?view=all

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - **Replicated**
- Tested on Atomic - **Replicated**
- Replicated outside of Dotcom? - **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated just as described! Upon the refresh of the social preview sidebar, the `Suggestion: Add tags` and `Suggestion: Assign a category` modals are missing. Cancelling and clicking "Publish" again doesn't restore them:

**Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/4125bea4-6ba7-40e5-9529-3a0145b78fdb

**Simple**

https://github.com/Automattic/wp-calypso/assets/27249804/b8da8d6b-7ef9-4fac-93b1-4181f825e83e

**Self-Hosted**

https://github.com/Automattic/wp-calypso/assets/27249804/20dcf1ac-08ae-47be-a42d-f3fbcbd92aba


📌 ACTIONS
- Other
- Reported in `/gutenberg`: https://github.com/WordPress/gutenberg/issues/51024

**Comment by cuemarie** [comment]
This has been fixed by https://github.com/WordPress/gutenberg/pull/52208 , which will reach WPcom on Gutenberg 16.2

**Comment by cuemarie** [comment]
Retested today and could not replicate - this looks fixed thanks to https://github.com/WordPress/gutenberg/pull/52208 . 

📌 ACTIONS
- Closed fixed
