### ISSUE TITLE
Domains: Cannot modify DNS settings on mapped domains

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#62109]
### Quick summary

Users with mapped domains cannot modify DNS records via normal flow.

![Screen Shot on 2022-03-21 at 14:52:07](https://user-images.githubusercontent.com/4887830/159344067-1f21d81c-85e3-406b-bdab-f958ad9a2b69.png)

Internal: p2MSmN-9uW-p2

@rafaelgalani noted that this was due to https://github.com/Automattic/wp-calypso/pull/61963

### Steps to reproduce

1. Add mapped domain / Domain Connection
2. Access My Site > Domains > [domain] > View Settings > DNS Records
3. See error

### What you expected to happen

Ability to see records, manage records

### What actually happened

Error

### Context

p1647887460744689-slack-C03TY6J1A via @cuemarie 
p1647887947431429-slack-C0BNMNMNG
p2MSmN-9uW-p2

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Many users

### Available workarounds?

None

**Comment by JoshuaGoode** [comment]
A revert of https://github.com/Automattic/wp-calypso/pull/61963 is coming via https://github.com/Automattic/wp-calypso/pull/62108

**Comment by delputnam** [comment]
I'll close this since it was fixed by the revert.
