### ISSUE TITLE
Change link paths from absolute to relative in Spotlight JITM rules

### ISSUE THREAD

**Issue by lupus2k** [Automattic/wp-calypso#62105]
### Details

When clicking on the Spotlight message, it loads all the page because we are using an absolute path on plugin links. Changing links to use relative path will make it look faster and more consistent with calypso usage.

### Checklist

- [x] Change link paths from absolute to relative in Spotlight JITM rules

**Comment by lupus2k** [comment]
Need review on D77116-code

**Comment by allilevine** [comment]
Closed by D77116-code
