### ISSUE TITLE
RTL punctuation positioned wrongly

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#62102]
### Quick summary

When entering a full stop on an RTL language in a mixed RTL/LTR page, the punctuation at the end of the sentence goes in the wrong place. 

### Steps to reproduce

Please see video

https://user-images.githubusercontent.com/13706336/159273904-a4e7e2b8-93a0-4857-b7c0-8a471c408b21.mp4

### What you expected to happen

The full stop should be in position (2) not (1).
<img width="952" alt="Markup 2022-03-21 at 13 39 17" src="https://user-images.githubusercontent.com/13706336/159274053-48e3f0f9-ab9e-4989-8ff2-6feae3171936.png">

### What actually happened

The full stop goes in the wrong place

### Context

Initial report 4878224-zd but this site used retired Nikau theme. However, I replicated it on FSE theme and the issue still occurred so it's not theme specific.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

Tried using the steps found on Google here - https://rayed.com/posts/2013/08/supporting-right-to-left-writing-for-arabic-in-wordpress-the-easy-way/

But this also didn't work.

Also found this issue which may be related - https://github.com/wordpress-mobile/WordPress-iOS/issues/17479

**Comment by kerrynicl** [comment]
Closing in favour of - #61740
