### ISSUE TITLE
Account Recovery: The form says the contact email matches the lost account, but it doesn't

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#62113]
### Quick summary

The account recovery form says the email address and username match, even when they don't, which makes the form not submit.

![account recovery email issue](https://user-images.githubusercontent.com/3476361/159381228-b3034a73-b1d1-4160-8bbe-2a3a9dfe61cb.png)

### Steps to reproduce

1. From an incognito (or logged in!) window, head to https://wordpress.com/wp-login.php?action=recovery
2.  Enter details for the _lost_ account.
3. For the contact address, enter a current address that exists on a different account in our system
4. Submit!

Note the message at the top:

> You should be able to recover your account simply by filling out the [lost password](https://wordpress.com/wp-login.php?action=lostpassword) form with the email address you've provided. Please check your spam folder for the reset email.
> 
> If you still can't log in after another reset attempt and checking your spam folder, please resubmit the form below and we'll try to lend a hand.

### What you expected to happen

For now, we just shouldn't say the email address matches if it doesn't 😅 Let the form continue.

As for what we could do instead: we could only display that message if they really do match, or trigger an automatic reset or something. We'd need to think things through though re: security, 2FA, etc. and test a few cases to make sure it works smoothly.

### What actually happened

I tested this with what combinations I could, and pretty consistently, it would just say the email address was a match. And it wasn't.

> You should be able to recover your account simply by filling out the [lost password](https://wordpress.com/wp-login.php?action=lostpassword) form with the email address you've provided. Please check your spam folder for the reset email.
> 
> If you still can't log in after another reset attempt and checking your spam folder, please resubmit the form below and we'll try to lend a hand.

If they just submit the form again, it seems to work. But how many users would follow the instructions to use the password reset link, and then come back and fill in the form fresh? The form only goes through on the second submit.

### Context

When they've lost access to their account, users will [often](https://wordpress.com/forums/topic-tag/account-recovery) create a new account to ask for help regaining access. We send them to the account recovery form. Usually, we don't hear back. If we do, sometimes we'll share the direct email address.

Today, a user who recovered their account mentioned this error. It sounded off so I looked into it.
https://wordpress.com/forums/topic/unable-to-connect-to-my-site-modula9-net/

I don't have an atomic account I can test this with. I assume the password reset process is the same, though.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

n/a

### Browser, operating system and other notes

n/a

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Not sure whether to mark difficult or not. It's easy _if they know what to do_: the user has to know to submit the form twice, instead of following our implicit instructions to leave the page and use the password reset by email option.

Instead, they create a new account and contact Happiness. Happiness then has to tell them to submit the form twice. Difficult? Maybe not, but it's definitely a barrier.

Noting too, I don't know how the password reset by email form behaves if the user is logged in; that could be another issue to look into.

**Comment by supernovia** [comment]
Also noting the user reported a slightly different message. I'm not sure whether they were paraphrasing:

> Your contact email is the same as your account – if you can receive emails you should try the password reset form instead.

**Comment by supernovia** [comment]
See also https://github.com/Automattic/wp-calypso/issues/62356

**Comment by daledupreez** [comment]
This code runs on the back end, so I am working on addressing this issue.

**Comment by daledupreez** [comment]
My proposed back end changes are in D77946-code and are being discussed internally: pbMDNC-z5-p2

**Comment by daledupreez** [comment]
The fix in D77946-code has now been deployed to production.

The changes it includes are as follows:

* Improve the styling for error messages so they are more prominent and easier to read when there are multiple paragraphs
* Improves the handling for situations where the contact email is not linked to the account being recovered
* Adds more guidance when users enter the same value for the login and contact fields, and when users enter the login and its linked email address
