### ISSUE TITLE
Upsell Banner: button text is formatted poorly in CJK languages

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#62112]
### Quick summary

The Upsell banner in Calypso has a button which is formatted poorly in CJK languages.

![Screen Shot 2022-03-21 at 12 42 39 PM](https://user-images.githubusercontent.com/6549265/159368818-05a7f634-72d0-439f-9f01-36a946e0e9c4.png)

### Steps to reproduce

Prefix each step below with adjustments to the UI language of your choice, out of Japanese, Chinese (Simplified/Traditional) and Korean.

1. log in as a user that has the following upsell banner: `Start collecting feedback from your visitors to improve your WordPress site`.
2. navigate to `/home`.
3. view the banner in the sidebar.

### What you expected to happen

The upsell banner text and action button is formatted in an easy-to-read manner.

For example, see the following English screenshot:

![image](https://user-images.githubusercontent.com/6549265/159369209-22ec1fda-83e9-4ac4-8683-ab62be1ea112.png)

### What actually happened

The upsell banner action button is poorly formatted, in many instances splitting into newlines every 1-3 characters.

It makes the button difficult to read, as well as leaving a very poor first impression.

![Screen Shot 2022-03-21 at 12 43 31 PM](https://user-images.githubusercontent.com/6549265/159369353-8078ce70-b85f-4078-a4d4-ab75b294f015.png)
![Screen Shot 2022-03-21 at 12 42 39 PM](https://user-images.githubusercontent.com/6549265/159369354-f78d39ed-5361-4962-9421-d0fd3cb1bcdf.png)
![Screen Shot 2022-03-21 at 12 41 02 PM](https://user-images.githubusercontent.com/6549265/159369355-d09f8ce2-ad0f-4b13-8452-2e618027c45e.png)

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge

### Simple/Atomic

Simple

### Other notes

Note that other non-Latin scripts such as NE or HE do not experience this issue.

### Reproducibility

Consistent

**Comment by obenland** [comment]
It doesn't look much better in German:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/1398304/182483845-fc99dc05-473a-4e67-8be9-cb560d9c107e.png">

Maybe we could lose that dismiss X to give the rest of the banner text more room?

**Comment by obenland** [comment]
Introduced in D72131-code. @withinboredom Any chance this could be revisited in the context of i18n?

**Comment by mtias** [comment]
@obenland @withinboredom Was there any follow up here?

**Comment by withinboredom** [comment]
Just brought it up in p1664353639939619-slack-CAMDXNE57

**Comment by digitalwaveride** [comment]
Looking at the [German version here](https://github.com/Automattic/wp-calypso/issues/62112#issuecomment-1203273001), the translation of that message is very bad, and maybe even a bigger issue than the broken formatting! 
What's the process behind these translations? "Ad copy" has additional challenges, especially in restricted space.

As a side note: We will stop the Crowdsignal related campaigns.

**Comment by daledupreez** [comment]
Noting that the specific message/CTA that is long in English has been removed as of D88739-code.

**Comment by mtias** [comment]
Thanks for the follow up
