### ISSUE TITLE
[Spike] mShots Performance with Verticalized Designs

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#62115]
# Description

We want to understand performance issues in the full Generated Design "pipeline".  At a high level it could be described by these steps:

* User selects vertical in vertical screen
* Block patterns assembled from recipe (or a page layout / demo site is used as is currently done)
* Images inserted into block patterns
* Copy inserted into block patterns
* **Thumbnail generated by mShots** 
* User sees Generated Designs in the Design Picker (or PTK tool)

The one thing we have not yet spiked is generation of thumbnails. 

Suggested by Ashar:

Can use my preview endpoint, see D77136-code,  with bunch of query params to mShots? Would that be fine caching/performance -wise ?

For example: should we also put the replaced image urls / texts as part of the query param, so that when we change the texts/images, the thumbnails will be refreshed instantly? Or should we just put a vertical_id param to the url and have the backend compute the design?

Also need help to check the mShots preview loading bug in the mc tool (as we saw earlier) . This happens when changing the  theme, the page must be refreshed to correctly see thumbnails.
 
 One way to approach this is to build out the "Design tab" in Ashar's proposal. Is this worthwhile?
pbxlJb-1k2-p2
![image](https://user-images.githubusercontent.com/5665959/159390985-632b81eb-88a3-451d-9a17-2bbcfd0aff24.png)

# Learnings to report on
* Is the delay to generate a thumbnail of a Generated Vertical Design significant?
* Do we need to tell Saygun to design a loading/waiting screen?
* How does this overlap with Caribou's importer & mShots work  (maybe this spike can be done with Caribou)
* What else?

# Related
Caribou info
Verticals Sync with Ganon & Caribou: pbxlJb-17l-p2
pcmemI-p2-p2#comment-561
MC Tool for Generated Vertical Designs #61788
Add wpcom/v2/block-previews endpoints D77136-code

cc @jeroenpf

**Comment by roo2** [comment]
Wrote up my investigation here pbxlJb-1sw-p2

**Comment by roo2** [comment]
I just want to get these performance testing scripts merged to mshots and then let's close this spike https://github.com/Automattic/mShots/pull/61
