### ISSUE TITLE
Update Emails: Unsubscribe link is broken in our last email

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#62111]
### Quick summary

The unsubscribe link at the bottom of our most recent update email seems to be broken. There's no href there.  We should make sure this is fixed for new emails.

### Steps to reproduce

You have to be subscribed to our marketing updates to see this. Open the email titled "ICYMI: Powerful New Tools" and try to click the unsubscribe link. There's an `<a>` but no `href=`

<img width="1484" alt="Screen Shot 2022-03-21 at 3 01 34 PM" src="https://user-images.githubusercontent.com/3476361/159365391-6ee61414-b51a-4a82-a8b4-dca1df3fa885.png">

### What you expected to happen

An unsubscribe link should be clickable.

### What actually happened

The link does not have an href so it can't be clicked.

### Context

Someone who wanted to unsubscribe reached out over twitter DM. We gave them https://wordpress.com/me/notifications as a workaround. Also, I assume that is not client-specific since it's in the HTML, but it is happening in my gmail.

Because that will affect many of our users, and because we probably don't want to send out another email without fixing this, I'm giving it a high priority.

### Theme-specific issue?

n/a

### Browser, operating system and other notes

n/a

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

We have to tell people to log in and use https://wordpress.com/me/notifications to unsubscribe. That's easy enough, but needing to request support to unsubscribe isn't ideal.

**Comment by supernovia** [comment]
I wasn't sure where to file this. But I've also left a link here for now:
pd0D4C-sK-p2#comment-1514

**Comment by fabiocchetti** [comment]
This issue was specific to the "ICYMI: Powerful New Tools" email and should already be fixed on upcoming emails. My bad, sorry about that!
