### ISSUE TITLE
Office 365 email auto DNS configuration not adding MX record value properly

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#62126]
### Quick summary

When setting up the DNS settings automatically for Office 365 email for a `.co.uk` domain, the MX record value is not correct leading to not receiving email.

### Steps to reproduce

1. Go to **Upgrades** → **Domains**, and click on any registered or connected domain. 
2. Click on **DNS Records** and then on the **Manage** button.
3. Click on the **Email Setup** option.
4. Click on the **Office 365** tab.
5. Add valid Verification Token from Office 365. For testing, `MS=ms00000000` can be used.

**Video recording**

https://user-images.githubusercontent.com/1046943/159466887-fc3c6fae-9b03-496a-b8a2-a246a5b4b104.mov

### What you expected to happen

Have a valid MX record value, like: `example-co-uk.mail.protection.outlook.com`

### What actually happened

Having an MX record value: `example-co.uk.mail.protection.outlook.com` that is incorrect (is not resolving). Please, note the first part: `example-co.uk`

### Context

Customer reports on 33703096-hc and 34796248-hc

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Rename the MX DNS record value from: 

`example-co.uk.mail.protection.outlook.com`

to: 

`example-co-uk.mail.protection.outlook.com`

**Comment by Greatdane** [comment]
This looks to work correctly for top level domains, but not Second-level domains (like `.co.uk`, `.co.jp` etc)

**Comment by Greatdane** [comment]
@Automattic/nomado may be interested in this

**Comment by delputnam** [comment]
Really good catch @jartes Thanks for the report. I'll create a task for Nomado to investigate this and we'll report back here.
