### ISSUE TITLE
Stats: Weekly view showing no data if other interface language than en is used

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#6214]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Set account language to any language other than English (en - en-gb also exhibits the bug)
3. View single site stats page and switch to weekly view
4. The graph displays data, but the options below the graph are blank and cannot be switched, and the other modules on the stats page is empty. Day and Year views appear to be unaffected.

![stats_ _kokkiestrialtestsite_ _wordpress_com](https://cloud.githubusercontent.com/assets/11873759/16268158/7e1619a4-388d-11e6-80ea-d42d49b164ff.png)

Possibly related to #6147

#### Context / Source

Reported by a user using Dutch as their interface language in the public forums 746921-f. Also confirmed with several other languages.

**Comment by yoavf** [comment]
See #6263

**Comment by jeremeylduvall** [comment]
Looks like this should be fixed by #6263 since it's merged now. @KokkieH, I replied back to the user. Will close this here, but we can reopen if the user is still having an issue.

**Comment by KokkieH** [comment]
Works for me as well. @jeremeylduvall thanks for following up with the user.
