### ISSUE TITLE
Tax Location: Don't show the tax location in checkout for existing payment methods

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#62143]
### Quick summary

Somewhere along the way (I think https://github.com/Automattic/wp-calypso/pull/57807) we started showing the tax location for existing cards during checkout.  But we probably shouldn't do that because the tax location is going to get overwritten by the user-entered billing details (in the section above) after they submit anyway?   So it's really not clear to the user what the two locations mean and which one is actually being used:

![Screenshot from 2022-03-22 15-36-39](https://user-images.githubusercontent.com/235183/159564035-0202bf9c-f63d-4b5b-bc78-d07b5ea2ed7b.png)

(In reality, only the one at the top is being used, for taxes and otherwise.)

I guess you could imagine leaving the bottom one there in some fashion (if it's useful for the user to see what they previously had saved for this credit card), but it's confusing as is and it would be simplest to just drop it.  Also, that was the plan that came out of discussions with the tax team previously (pNPgK-5vg-p2#comment-22353):

>When changing the payment method on an existing subscription, it would be nice to show the country and ZIP code for each existing payment method in the list (so the user can see what the billing addresses of their old payment methods actually are); **this is not necessary in checkout, however (and would actually be confusing there), since the user can already edit the address.**

### Steps to reproduce

1. Have an existing credit card on your account.
2. Put something in your shopping cart.
3. Edit the billing information section to a new country or postal code, if desired.

### What you expected to happen

I expected it to be clear that the country/postal code entered in the billing information section would be used.

### What actually happened

It was not clear, since two separate country/postal code pairs were shown on the screen.

### Reproducibility

Consistent

**Comment by sirbrillig** [comment]
Certainly. This was just a side effect of that PR and is easily removed.

**Comment by sirbrillig** [comment]
Should be fixed by https://github.com/Automattic/wp-calypso/pull/62144
