### ISSUE TITLE
Themes: Normalize theme sheet URL by removing `/overview` on main page

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#6216]
It would be ideal if the "root" URL of the theme sheet would be cleaner, thus without `/overview`. This to avoid confusion before root `/$theme` and `/$theme/overview` as well as for SEO reasons (not major, just cleaner).

Before:

* `/theme/mood/` opens Sheet "Overview"
* `/theme/mood/overview` opens Sheet "Overview"

Change suggested:

* `/theme/mood/` opens Sheet "Overview"
* `/theme/mood/overview` redirects to `/theme/mood` (or invalid route?)

Note: the analytics entry should likely get in sync with this change ([ref](https://github.com/Automattic/wp-calypso/pull/6005#discussion_r67407025)).

**Comment by ockham** [comment]
I think I've found a pattern for our `theme/index.{node|web}.js` route definitions that might work:

```
/theme/:slug/:section(setup|support)?/:site_id?
```

Try at http://forbeslindesay.github.io/express-route-tester/

**Comment by folletto** [comment]
If I'm getting that tool correctly, it seems working... except on the path without section (i.e. `/theme/mood/example.wordpress.com`), but maybe it's because it's handled separately in the code?
