### ISSUE TITLE
Marketplace: Investigate how to add Jetpack Search

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62177]
### Details

See relevant PT comment: pdh6GB-s7-p2#comment-958
Documentation: PCYsg-AhH-p2

Acceptance criteria:
- [x] We have a clear path forward for adding Jetpack Search

### Related

#62025

**Comment by lsl** [comment]
Not much we can do here yet, p2 needs more discussion / clarification. I want to avoid Jetpack Search specific code inside the plugin browser one way or another but we can't make a decision on how to do that until the goals for adding this non plugin to the plugin marketplace are understood.

If it's just Jetpack Search product promotion we can do that with JITM's and avoid weakening marketplace boundaries, if it's to handle all non plan wpcom/jetpack features then we really need to have a wider discussion with design about how these should be treated in the plugins browser (/plugins) - i.e. the active/inactive thing doesn't make sense, "plugins" that won't show on the manage plugin screen etc.

**Comment by allilevine** [comment]
See: pdh6GB-s7-p2#comment-1081
We're going to wait until Jetpack Search is available as a standalone plugin. 
In the meantime, we can add a JITM: https://github.com/Automattic/wp-calypso/issues/62355

**Comment by vinimotaa** [comment]
hey @allilevine and @lsl thanks for the discussion here around Jetpack!

What do we need from the Design team at this point? I understand that Jetpack isn't yet a conventional plugin, so for that reason, there are concerns about how we should still list it within the Marketplace?

Would that make sense to use the same card design as any other plugin, and just hide the info that doesn't apply to it (active)? Then on the details page, we elaborate further around how it works?

**Comment by allilevine** [comment]
> What do we need from the Design team at this point? I understand that Jetpack isn't yet a conventional plugin, so for that reason, there are concerns about how we should still list it within the Marketplace?

@vinimotaa That's correct, we want to show Jetpack Search in search results, but it's not yet a standalone plugin. This is an example of how we show that in wp-admin: pdh6GB-s7-p2#comment-1081

> Would that make sense to use the same card design as any other plugin, and just hide the info that doesn't apply to it (active)? Then on the details page, we elaborate further around how it works?

That makes sense. We're just wary of confusing users by making this look like a plugin when it's not. But making changes to the card and clarifying on the details page sounds like it would help.
