### ISSUE TITLE
Abbreviate large follower numbers 

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#6217]
@jeherve suggests: 

> Should we round those numbers, to avoid cutting off “followers”? I think that past a thousand, “1K” gives me as much as information as “1,000”. Facebook does that for example.

![screen-shot-2016-06-22-at-11-36-42-am](https://cloud.githubusercontent.com/assets/17325/16271398/bb9e6b06-3891-11e6-9590-c2b230777083.png)

**Comment by jancavan** [comment]
I think we discussed this in Stats before and IIRC, there were some i18n issues so we decided not to pursue it.

**Comment by blowery** [comment]
I think if we stick with ISO abbreviations and localized placeholders, we'll be ok. 

@jancavan what were the i18n issues?

**Comment by blowery** [comment]
As a nice feature, add a `title` attribute with the full text, in a locale-specific format.

**Comment by blowery** [comment]
Perhaps https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

**Comment by jancavan** [comment]
@timmyc Do you remember we didn't pursue truncating numbers? I remember it was an i18n issue, but don't recall exactly why.

**Comment by timmyc** [comment]
So from the past discussion on i18n - there is support for these abbreviations in [cldr](http://cldr.unicode.org/translation/number-patterns) but I believe those translations are not in our json files yet.

Getting those translations into the various language files would be the first step, then adding support in https://github.com/Automattic/i18n-calypso for translating seems like a good route.

**Comment by bluefuton** [comment]
This lib looks promising: https://github.com/foretagsplatsen/numbro
