### ISSUE TITLE
Reader: new user getting emails confirming subscription in Cold Start

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#6218]
Reported by @shaunandrews 

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/read/start
2. Follow a site
3. Receive confirmed email subscription in email

#### What I expected
To not get emails confirming subscription

#### What happened instead
Received email confirming subscription instead

#### Screenshot / Video
![screen_shot_2016-06-21_at_10 19 41_pm](https://cloud.githubusercontent.com/assets/4924246/16271509/24215a1e-384f-11e6-864d-af0776213398.png)

It's also possible that @shaunandrews may have clicked the "OK, I'm all set" button already then visited https://wpcalypso.wordpress.com/read/start again.

**Comment by bluefuton** [comment]
We haven't implemented this yet :)

It's part of the signup process. For users who are put into cold start, their email delivery will be turned off.

@stevekaeser has made the necessary changes to the new user endpoint, but we need to integrate it into Calypso.
