### ISSUE TITLE
☂️  Update Vertical Image Curator with additional tagging

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#62194]
## Description

The Vertical Image Curator Tool is an MC tool at mc-url/verticals

As pbxlJb-1lY-p2 mentioned, we need to tag the vertical images (portrait, vacation, hero-image, blog-featured-image, etc) so that we could find the best substitutions. Besides, sometimes we might probably have some fancy images suitable for specific verticals and we want to upload those images manually.

Images are stored here: PduBjF-5-p2  , can we upload new images directly there with tagging features available, or is a new way of uploading & tagging needed?

![image](https://user-images.githubusercontent.com/5665959/163111026-3361a426-4739-48c7-b539-5321a925bb59.png)

## Acceptance Criteria (AC)
Part 1
- [x] Instructions are added to the mc tool so users know how to upload an image (for instance the tool is not intuitive since first user must select a vertical then they see the rest of the UI, so instructions are needed.).
  - [x] D78355-code
- [x] Instructions are added to the mc tool so that users know how to tag an image.
  - [x] D78355-code
- [x] Verticals list is fetched from the new vertical API.
  - [x] https://github.com/Automattic/wp-calypso/issues/62377
- [x] People can tag the images from Vertical Image Curator.
  - [x] D77653-code
- [x] People can upload the images for a specific vertical.
  - [x] D77653-code
- [x] User can  upload any image from their local computer (not just pexels images).
  - [x] D77653-code
- [ ] OlaB or Mike have tested the work, given their approval 

Part 2
- [x] Provide input for credit of the image (meaning the photographer or creator) is saved with the image (work with @alaczek on this)
  - [x] #62760
- [x] Add a comment in the instructions "Be sure all uploaded images are copyright free" (Low Priority)
  - [x] https://github.com/Automattic/wp-calypso/issues/62846
- [x] Vertical Image Curator has to fetch the tags from somewhere to make sure the consistency of the tags (or in early ver
  - [x] https://github.com/Automattic/wp-calypso/issues/62653
- [x] Support editing the orientations of the image
  - [x] https://github.com/Automattic/wp-calypso/issues/62819
- [ ] OlaB or Mike have tested the work, given their approval 

## Related

* pbxlJb-1re-p2
* Approaching a Generated Design in MVP: pbxlJb-1qE-p2

**Comment by autumnfjeld** [comment]
@arthur791004 I pulled this into "Ready for dev" as it is high priority work.   If you think you could use help with this, let @fushar know.    

This is one of the pieces that are really important for the first simple Generated Design as outlined in pbxlJb-1qE-p2

**Comment by arthur791004** [comment]
We already shipped the new version to support tagging. See D77653-code.

**Comment by autumnfjeld** [comment]
@arthur791004 

Do these instructions from D77653 apply to what is actually working at mc tool /verticals/images/
* Go to  mc tool /verticals/images/
* Select any vertical
* Click Upload button to upload vertical images and you could see the image is added to the selected vertical
* Select any images to edit
* Click Edit to add tags and you could see the tags are added to specified image


Because this isn't working for me, I can't upload an image to Accounting. See video:

https://d.pr/i/P0IZVG


I updated the AC above and thought it was smart to break it into two parts as I think Part 1 is very easy to complete. Do you agree?

To clarify the state of this work could you:
* check off any AC items in the description above that are complete
* Please verify the acceptance criteria make sense - you and I can work together to improve the AC as needed
* In the comments, give an estimate of when Part 1 of this might be finished and any blockers for Part 1

Thank you!!! 😄

**Comment by arthur791004** [comment]
@autumnfjeld I just found an issue that the uploaded images would be stored in my test sites. See the comment on D77819-code. But I have shipped the fixed version and also migrated the vertical list to the new one, you could try the instructions you mentioned again and check the result, thanks!

> Instructions are added to the mc tool so users know how to upload an image (for instance the tool is not intuitive since first user must select a vertical then they see the rest of the UI, so instructions are needed.)
>
> Instructions are added to the mc tool so that users know how to tag an image

I'll add the short instructions to guide the user on how to use it and link to the FG (PCYsg-CME-p2) for more details.

>  People can upload any image that is copy right free (not just pexels images)

I'm not sure what do we need to do for this. Do you have more details? Thanks!

> In the comments, give an estimate of when Part 1 of this might be finished and any blockers for Part 1

I'll create a PR this week including updating the FG (PCYsg-CME-p2) and deprecating the old one. And I think it could be shipped on next Monday or Tuesday once the reviewer approves my PR.

**Comment by arthur791004** [comment]
I have already updated PCYsg-CME-p2 and here is the change for adding the short instructions. See D78355-code

**Comment by autumnfjeld** [comment]
> >People can upload any image that is copy right free (not just pexels images)

>I'm not sure what do we need to do for this. Do you have more details? Thanks!

I reworded this to "users can upload any image from their local computer".

Users should only upload copyright free, but we won't build any blocking mechanism.  Maybe we can add a comment in the instructions "Be sure your image is copyright free". Low priority.

**Comment by arthur791004** [comment]
Close it as all of the tasks are finished. We'll continue to iterate it based on the feedback. See https://github.com/Automattic/wp-calypso/issues/62369
