### ISSUE TITLE
[Bug]: Atomic site creation (ecom plan) results in a broken experience

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#62207]
### Quick summary

After investigating a bug with a plugin not being installed as expected, I found out that the site creation flow for an ecommerce site seems (is?) broken. While the site is created successfully, it seems that Jetpack is not connected properly resulting to Jetpack `Safe Mode has been activated` in WP Admin 

<img width="1630" alt="CleanShot 2022-03-24 at 12 19 12@2x" src="https://user-images.githubusercontent.com/12430020/159895159-7614bb7b-3885-4863-be53-6787d9927f9d.png">

even after selecting "Move your settings", my site isn't displayed in Calypso with a console error `User or Token does not have access to specified site`. 

Blog Card reports the following 
`The current site is part of a WordPress multi site install and the main network site ( ) doesn't match the site url ( https://[domain].wpcomstaging.com/ )`
`The connection is NOT HEALTHY`

### Steps to reproduce

1. As an existing user, start at [https://wordpress.com/new?ref=calypso-selector](https://wordpress.com/new?ref=calypso-selector)
2. Create a site by selecting the ecommerce plan
3. After being redirected to WP Admin, skip the store setup
4. Go to `/wp-admin`
5. You should get the Jetpack `Safe Mode has been activated` error
6. Proceed with `Move your settings`
7. Visit Calypso (eg click `Posts`)
8. You will land to the site switcher

### What you expected to happen

After creating a new ecom site Jetpack shouldn't be in safe mode and site should be accessible from Calypso.

### What actually happened

Jetpack was in safe mode and site was not accessible from Calypso.

### Context

Check the following video:
p1648114157932629/1648110864.091759-slack-CDLH4C1UZ

### Browser

Google Chrome/Chromium

### Simple/Atomic

Atomic

### Other notes

Related convo p1648110864091759-slack-CDLH4C1UZ

### Reproducibility

Once

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by JoshuaGoode** [comment]
Doesn't appear to be plan specific, can occur across any Atomic plan right now. Seems the `home` option isn't always updated fast enough.  Internal discussion: p9F6qB-90M-p2

**Comment by obenland** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/64101
