### ISSUE TITLE
Marketplace: plugin installation / activation error (Jetpack CRM)

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#62206]
While trying to install Jetpack CRM `zero-bs-crm` on an ecom site, I get stuck to the activation screen
<img width="1601" alt="CleanShot 2022-03-24 at 11 46 32@2x" src="https://user-images.githubusercontent.com/12430020/159888985-9421616d-5f0b-4df9-9d71-04644502b9b9.png">

The network request to `install` it has been successful but subsequent request to `https://public-api.wordpress.com/rest/v1.1/sites/[SITE_ID]/plugins/zero-bs-crm%2FZeroBSCRM?http_envelope=` returns
```
{
    "code": 400,
    "headers": [
        {
            "name": "Content-Type",
            "value": "application/json"
        }
    ],
    "body": {
        "error": "jetpack_error",
        "message": "The Jetpack site is inaccessible or returned an error: parse error (local). not well formed [-32710]"
    }
}
```

Steps to repro:
- On an Atomic site
- Go to Plugins
- Select Jetpack CRM
- Open the console
- Click `Install & Activate`
- Observe the error

**Comment by cpapazoglou** [comment]
FWIW, other plugins are installed with success. Probably something goes wrong with the slug?

**Comment by epeicher** [comment]
The error is raised because the following line is returning `false`  

2c084-pb

And the message that was passed to that function is

2c085-pb

I will continue investigating why that is happening

**Comment by epeicher** [comment]
When trying to activate the plugin using the `wp` cli, an error is returned. That could be the cause of the error: 2c0bc-pb
Additionally, the plugin is activated in spite of the error.

**Comment by cpapazoglou** [comment]
> When trying to activate the plugin using the `wp` cli, an error is returned. That could be the cause of the error: 2c0bc-pb Additionally, the plugin is activated in spite of the error.

Nice sleuthing @epeicher. I can see that after activation `zerobscrm-dash` tries to do a redirect which is probably not expected when plugins are installed via CLI (related https://wordpress.org/support/topic/redirect-after-enabling-plugin-kills-wp-cli/).

@cleacos should we add a return early statement for CLI requests too here?
https://github.com/Automattic/zero-bs-crm/blob/4.10.1/includes/ZeroBSCRM.Core.php#L1943-L1945

**Comment by cleacos** [comment]
@cpapazoglou Thanks

Yes, we could check for `WP_CLI` in that condition too. Added the issue to fix it.

**Comment by cleacos** [comment]
On the next release, we will add this too. (maybe this week, depending on other hotfixes we have to do)

**Comment by cpapazoglou** [comment]
> We should add this to the public guidelines. Seems like a good improvement for all users of WP CLI and popular plugins.

**Comment by cleacos** [comment]
Done, the release is already out!

**Comment by epeicher** [comment]
Thank you very much @cleacos! Installing the plugin through the `wp` cli works as expected now.

Additionally, when testing using calypso we have found that the above error installing the plugin is still returned. Following the steps in the description returns the same error (now probably due to other logic).

After further investigations we have found (thanks to @cpapazoglou) that the following extra condition `wp_is_xml_request()` would fix the error. Please see suggested code below 
```php
if ( wp_is_json_request() || wp_doing_ajax() || ( defined( 'WP_CLI' ) && WP_CLI ) || wp_is_xml_request() ) {
            return;
}
```
Should we add that extra condition here?
https://github.com/Automattic/zero-bs-crm/blob/cc0d78382a60531ed358469c5af85f611ce6eba4/includes/ZeroBSCRM.Core.php#L1943-L1945

**Comment by cleacos** [comment]
Okay, thank you @epeicher 

Yes, we will add this extra condition.

... an XML request! does it still exist? 🙂

**Comment by cpapazoglou** [comment]
Sadly, many requests from WPCOM to Jetpack sites are xml-rpc requests @cleacos

**Comment by cleacos** [comment]
Good to know it 👍

**Comment by cleacos** [comment]
We've released a new JPCRM version with all these fixes. @cpapazoglou @epeicher

**Comment by epeicher** [comment]
I tested and works as expected. Thanks @cleacos !

|Installing/Activating | Deactivating|
|-------|------|
|![CleanShot 2022-03-30 at 21 28 01](https://user-images.githubusercontent.com/3519124/160915407-6cd44bbc-d83b-4d8d-9a7f-0132a9b666fd.gif)|![CleanShot 2022-03-30 at 21 24 33](https://user-images.githubusercontent.com/3519124/160914967-71d638b7-8c0b-4dce-be01-121c2c3743b3.gif)|

**Comment by cleacos** [comment]
Great!

**Comment by cleacos** [comment]
@epeicher Do you know if we have an event ( `wpcom_****` )to be able to track the JPCRM activations via Atomic site?

**Comment by cpapazoglou** [comment]
We don't track plugin activations through WP Admin. From Calypso though we have `calypso_plugin_activate_click` and `calypso_plugin_activated_success` which you may find useful when adding `plugin` as a property

<img width="1578" alt="CleanShot 2022-03-31 at 13 22 52@2x" src="https://user-images.githubusercontent.com/12430020/161033890-23481fea-fa08-4884-92b5-07b675e6f47a.png">

It seems like we did a lot of testing on Mar 29 ;-)

**Comment by cleacos** [comment]
Thank you! I see... we can say 0-3 activations per day. 

Just exploring business opportunities on WP.com

**Comment by cpapazoglou** [comment]
Another case https://wordpress.org/support/topic/error-warning-when-activated-through-api-cli/
