### ISSUE TITLE
Block Editor :: Layout Grid :: Image Block :: breaks with preview tool on Tablet and phone.

### ISSUE THREAD

**Issue by mdtanjid0** [Automattic/wp-calypso#62213]
### Quick summary

If we take a Layout Grid Block, and Image blocks within the Layout Grid, it breaks with the Preview tool when we check that on *Tablet* and *Phone* preview only on Editor. 

It works fine on the front end. 

I have created a short video: 

https://user-images.githubusercontent.com/54123436/159915466-ee182110-545a-46d5-ae2c-5fbb0b96593d.mp4

 

### Steps to reproduce

1. Take a Grid layout. 
2. Select 3 columns, for example. 
3. And then add Images on the Gird layout blocks. 
4. Check with the Preview tool on *Tablet* and *Phone*.

### What you expected to happen

It should show the same as the frontend; here is the expected result:

***Tablet***:

<img width="788" alt="Markup 2022-03-24 at 18 39 17" src="https://user-images.githubusercontent.com/54123436/159918082-cee03f58-c4a7-4c0c-b6e6-63ceaf3cbab9.png">

***Phone***
<img width="509" alt="Markup 2022-03-24 at 18 43 01" src="https://user-images.githubusercontent.com/54123436/159918784-f0210c0c-76d6-4f9c-a97d-9271b858a5d8.png">

### What actually happened

It breaks on small devices on the Editor. 

***Tablet***
<img width="989" alt="Markup 2022-03-24 at 18 45 27" src="https://user-images.githubusercontent.com/54123436/159919971-6d779621-dea8-4c22-b4a5-54955dea9f13.png">

***Phone***

<img width="690" alt="Markup 2022-03-24 at 18 45 12" src="https://user-images.githubusercontent.com/54123436/159919934-3abb64bb-7ffc-48a4-a6f0-fe9197bc3c3a.png">

### Context

4888407-zen

The user started seeing this week. They said that it was working before as expected. 

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
I wanted to note that this happens with the columns block as well, especially with the images which are resized through the pointers. 

Another ref: https://github.com/WordPress/gutenberg/issues/38381#issuecomment-1097661873

**Comment by manuelrebollo-a11y** [comment]
I found a very similar issue on a customer's site using theme **Shawburn**: 32165136-hc

The only difference is the content structure. **List View** shows `Columns > Column > Blog Posts`.

I reproduced the issue on a test site using the same theme, while the issue is not present with **Twenty Twenty-Two**:

![desktop-preview](https://user-images.githubusercontent.com/92953443/163597514-eaa48532-6f37-4550-879b-3dbc2ee87391.png)

![tablet-preview](https://user-images.githubusercontent.com/92953443/163597529-47e633b8-23f7-4676-97e4-655cb47187ac.png)

**Comment by candy02058912** [comment]
This ticket is old, so I did a retest on Simple and Atomic sites, with the Columns and Layout Grid, and the issue isn't reproducible anymore.

## Layout Grid
https://github.com/Automattic/wp-calypso/assets/6586048/71afb1f5-ffb9-4cfb-876b-cae01d00301a


## Columns
https://github.com/Automattic/wp-calypso/assets/6586048/bd277838-0bd5-4961-9f2b-7277b00820b2

Hence, closing it as fixed.
