### ISSUE TITLE
Themes: change default action from "Live Demo" to "Info"

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#6221]
Currently "Live Demo" (was: "Preview"), and opens the `WebPreview`:

![screen shot 2016-06-27 at 20 17 03](https://cloud.githubusercontent.com/assets/4389/16392510/347d036e-3ca4-11e6-8367-3ef3d3734ee4.png)

Change to "Info", and open the theme sheet:

![screen shot 2016-06-27 at 20 17 14](https://cloud.githubusercontent.com/assets/4389/16392515/3a03275a-3ca4-11e6-8da2-cd5916d2f906.png)

This is to be done after M4 goes live.
Fixes #5160.

**Comment by melchoyce** [comment]
"Details" is kind of a weird word; it has more than one meaning that could potentially confuse people — does it mean the visual details for the theme? "Detailing" as in "I detailed my car?" I know we've been using this word for a while but I'm wondering if it might be better to change it to something like "Info" or "Information." What do you think?

**Comment by folletto** [comment]
I'm 100% on board, I struggled a bit in finding an alternative, and "Detail" doesn't satisfy me at all, but I wanted to have a first iteration... so I'm happy you commented. :) 

"Info" seems similar to "Details" here, but I rely on your sensibility here to discriminate between the two.

Would be even better if we had a more "active" verb, like "Open" but more contextual to that action, but I couldn't find any. Advice welcome. Let's go with "Info" otherwise.

**Comment by sirbrillig** [comment]
I assume that the text this issue is looking to change is the hover text on each theme in the `/design` route (which currently reads "Live Demo" rather than "Preview")?

<img width="272" alt="screen shot 2016-06-27 at 3 09 48 pm" src="https://cloud.githubusercontent.com/assets/2036909/16392367/93778522-3c79-11e6-8592-435ccfef8234.png">

**Comment by folletto** [comment]
> I assume that the text this issue is looking to change is the hover text on each theme in the /design route (which currently reads "Live Demo" rather than "Preview")?

Yes, that was changed in #6249 merged recently. So it's currently from "Live Demo" to "Info". :) 

I updated the first post to reflect the discussion and updates up until now. 👍
