### ISSUE TITLE
Marketplace: Add WooCommerce Canada Post

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62227]
Add Canada Post Shipping method extension to the marketplace. Use WooCommerce extension logo.

Documentation: PCYsg-AhH-p2
URL: pdh6GB-y3-p2
Slug: woocommerce-shipping-canada-post
Name: WooCommerce Canada Post Shipping Method

### Add billing products
 - [x] Post preflight p2, example pdh6GB-vf-p2
 - [x] Add product, yearly, monthly plans see docs PCYsg-CJy-p2

### Create store products
 - [x] Reserve store product ID's, example D76056-code
 - [x] Add catalog mapping, example D76057-code
 - [x] Generate store products, docs PCYsg-CJy-p2
 - [x] Add store product translation, example D76326-code
 - [x] Add marketplace product entry to endpoint (and image if required), example D77429-code
 - [x] Insert vendor product info, documentation: PCYsg-CJy-p2
 - [x] Confirm plugin can be purchased and installed by non a11n users

**Comment by lsl** [comment]
- [x] Preflight  pdh6GB-y3-p2

**Comment by lupus2k** [comment]
- [x] Reserve store product ids D77792-code
- [x] Catalog Mapping D77773-code
- [x] Generate store products
- [x] Generate legacy store product
- [x] Product translation D77931-code
- [x] Product endpoint D77873-code
