### ISSUE TITLE
☂️  Design Picker for Verticalized Designs

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#62237]
# Description
We want to showcase verticalized designs in a "special" version of the Design Picker (v13n DP).
![image](https://user-images.githubusercontent.com/5665959/165203584-6d0bc80f-e6d6-4931-8a41-237c770eecea.png)

### Designs
[Figma](42PgVsdlQ1v2wpk6lmmrnq-fi-1601%3A59509)  See the "60 Sec Preview" page.
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/5665959/165205771-5a841734-f980-417e-9af6-2e0ceee6eb9a.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/5665959/165205817-d16658f6-6f13-4225-9236-03afac34d1f5.png">
<img width="156" alt="image" src="https://user-images.githubusercontent.com/5665959/165205878-a851330c-cbfd-4ab9-aa74-3049726e8b97.png">

### Overview of user flow
* User picks a vertical from the vertical list
* User choses Build (we are only offering the v13n Design Picker in the build flow)
* If images exist for the chosen vertical (or parent vertical) the user will see the v13n DP
  * If user choses a vertical for which we do not have images, they will see the standard DP
* In the v13n DP, the user will see three layouts (Blog, Business site, Portfolio) that contain images related to their chosen vertical
* The user can select one of the thumbnails on the left to preview the design
* The user can select one of these or can skip design selection, or can choose "View more options"

# Acceptance Criteria   (WIP, more to come)
### MVP
- [x] User can select thumbnail previews (probably mShot thumbnails like existing DP) to change 
- [x] Tracks events
- [ ] Tested on real mobile device - ask Autumn or Zach or HE for informal testing as needed

### Further iterations
These may be part of MVP depending on difficulty of implementation
- [x] Responsive thumbnail previews
- [ ] Scrollable thumbnail previews (like in Calypo's "Add a page" gallery)

# Related
* Verticals: How to start? pbAok1-2AH-p2
* Vertical question step in onboarding #61526

**Comment by autumnfjeld** [comment]
@fushar & @Automattic/ganon 

Just a heads up that we may try to deliver a "fancy version" of the DP for the Vertical Designs for MVP. It is not yet decided, but I'll present this in the MVP post.  It is work we would do in a month or so, nothing to worry about now, and I'll create an issue for it when the time comes.   The work @fushar  is doing in #62400 is still relevant for this stage of the project. 

Example of possible "fancy version" 🙂
![image](https://user-images.githubusercontent.com/5665959/161702736-2d0f6bd1-55d9-4a23-a243-afc404dc7ca8.png)

**Comment by taipeicoder** [comment]
Closing this one as we have completed the initial work, and will be creating task-specific issues for the verticalized design picker moving forward.
