### ISSUE TITLE
Push Notifications: Re-allowing permissions doesn't clear the DISABLED warning without page refresh

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#6223]
#### Steps to reproduce
1. Enable Push Notifications in Firefox
2. Disable the notifications permissions from the Lock icon on the site
3. Refresh/load https://wordpress.com/me/notifications
4. Verify push notifications are marked as DISABLED, with instructions to re-allow
5. Follow said instructions

#### What I expected
The warning label to go away

#### What happened instead
I clicked around inside Calypso and went back to /me/notifications and the warning was still there.  A full page refresh was needed to remove it.  Maybe there should just be a note on the instructions saying to refresh?  Not technically necessary to enable notifs, but it would clear up the confusion.

#### Browser / OS version
OSX 10.11.5 Firefox 46.0

#manual-testing

**Comment by designsimply** [comment]
Tested and confirmed using Chrome 51.0.2704.84 on Mac OS X 10.11.5

**Comment by mjuhasz** [comment]
New site permission settings take effect after reloading the page. Chrome clearly indicates this, and also provides us with a reload button.

<img width="1439" alt="screen shot 2016-06-24 at 12 00 52 am" src="https://cloud.githubusercontent.com/assets/1017839/16321744/ee5420c8-399e-11e6-871f-c8341eecabca.png">

Firefox does not display a similar warning, but reloading the page is still necessary.
