### ISSUE TITLE
Improve color kind detection accuracy for url-analyzer

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#62242]
Currently the mShots url-analyzer API returns a bag of colors. We need the API to return a bucketed list of colors in three categories: background, text color, and link color.

**Comment by vishnugopal** [comment]
Discussion:
- There might not be a perfect solution, but maybe we can get this to be better.
- Maybe we can see a frequency of colors, colors that are used a lot is probably the "most important"
- Perhaps, turn of all images, take a screenshot of the page, analyze the most dominant color.

**Comment by vishnugopal** [comment]
- We had some ideas for improvement here, that will be tackled next. pcmemI-ys-p2#comment-645

**Comment by vishnugopal** [comment]
For background this is very hard to do to find the most likely background color. It's hard to say which element is the background. Let's pick the 4/5 most popular background colors and then pick from link and text colors that are complimentary

**Comment by jeroenpf** [comment]
- Implemented improved color detection. The background color is now detected from taking a screenshot. Link & text colors are ordered by frequency to get the colors that are most likely to work.
- A preferred palette is suggested based on combining background, link, and text colors that match and satisfy the WCAG accessibility constraints (AA).
- Added a preview page for local testing with visualized results.
- Improved local development environment by using a container with a watcher for automatic compilation of .ts files upon file changes.
