### ISSUE TITLE
Cannot select payments plan for Payments Button block widget

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#62269]
### Quick summary

When adding a Payments Button block through either _Appearance → Widgets_ or _Appearance → Customize → Widgets_, it is not possible to select a payment plan. Though it's possible to add the widget, it does not render on the frontend because a plan has not been selected. 

### Steps to reproduce

1. Activate a universal theme, such as Twenty Nineteen
2. Go to _Appearance → Widgets_ and add Payments Button block
3. If needed, connect with Stripe (this is what I did on my test site, which wasn't connected previously)
4. Create a payment plan, and add the button
5. Try selecting a payment plan, and observe that it remains deselected
6. Any changes involving a change to the payment plan are not registered, and the "Update" button for block widgets remains greyed out — you can still change button text, however the button's HTML is not rendered in a widget location:

<img width="1604" alt="Markup 2022-03-25 at 09 01 50" src="https://user-images.githubusercontent.com/39252765/160193245-1f14ed3e-8f5d-4f39-82ba-a5415b853b0b.png">

Screencast:

https://user-images.githubusercontent.com/39252765/160193354-b249aa7b-ea35-4a99-9b8e-4c0d51857f78.mp4

### What you expected to happen

I expected to add the Payments Block widget and select an appropriate payment plan without issue.

### What actually happened

The Payments Block widget could not be saved and the button did not render.

### Context

https://wordpress.com/forums/topic/despite-selecting-a-payment-plan-i-cant-make-the-payments-button-block-work/?view=all

### Reproducibility

Consistent

**Comment by supernovia** [comment]
Hey there, the payment button block has seen some updates since then. I can't seem to duplicate this issue. Can you confirm whether you're still running into this?

**Comment by supernovia** [comment]
It looks like this block had a UI update, and I can't duplicate this anymore.  I'll close this out, but let us know if you're seeing it still. Thanks!
