### ISSUE TITLE
Marketplace: Add categories to Marketplace

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62264]
Implement categories and a menu to use them, for the Marketplace.

See walkthrough: p1648749511112799-slack-C029JEQRVRT
Categories post: pdh6GB-Cq-p2
PT: pdh6GB-AJ-p2
Design walk-through: pdh6GB-Cq-p2

Acceptance criteria:
- [ ] Localization in place: add strings first.
- [ ] There's a "Discover" section under the Search Header containing a categories menu, number of results, and links to popular categories (can hand pick for now).
- [ ] Clicking an item in the Discover section or categories menu loads plugins with that tag.
- [ ] We're tracking how these categories are used.

Before:
<img width="1140" alt="Screen Shot 2022-04-05 at 4 25 05 PM" src="https://user-images.githubusercontent.com/1689238/161842954-3a64bb06-6404-4bdf-8a64-50fcbfe2e859.png">

After:
<img width="972" alt="Screen Shot 2022-04-05 at 4 21 01 PM" src="https://user-images.githubusercontent.com/1689238/161842374-0b5ac703-4246-4487-a8d1-fc38a0c77980.png">

**Comment by lsl** [comment]
WIP in https://github.com/Automattic/wp-calypso/pull/62685. Using category list cleaned up from p2 / https://github.com/Automattic/wp-calypso/issues/62638#issuecomment-1095940991

**Comment by lsl** [comment]
Going to break this one up into a few PR's, https://github.com/Automattic/wp-calypso/pull/62685#issuecomment-1096217584

Breaking it down like this:
- Header + dropdown selector - https://github.com/Automattic/wp-calypso/pull/62685
- Category cards selector - TBD, partially implemented in https://github.com/Automattic/wp-calypso/pull/62685 but likely going to move that into a new PR
- Searching using category slug instead of a search term - TBD

**Comment by lsl** [comment]
Locking in categories for now as:

`Analytics, Business, Customer Service, Design, Ecommerce, Education, Finance, Marketing, Search Optimization, Photo & Video, Social, Widgets, Email, Security, Posts & Posting`

Along with options to pick:

`All Categories, Top free plugins, Top premium plugins, and Editor’s pick.`

![Screenshot 2022-04-13 at 08-32-18 Marketplace Plugin Categories](https://user-images.githubusercontent.com/811776/163065497-2a6df8af-84de-45ef-a044-a458ba8c82d9.png)

**Comment by allilevine** [comment]
> Locking in categories for now as:

@lsl @Rolilink Do we have a PR to add the strings, or are we still waiting for input?

**Comment by lsl** [comment]
The [PR here](https://github.com/Automattic/wp-calypso/pull/62685/files#diff-2a3f538d6d0056cd45d1482c83c382cb3d4df097d897ff93cefaf96648b784d8R22-R134) has the categories in but would be good to get the descriptions done at the same time before tagging with string freeze label.

I might try and get a PR up today with just the categories / known text in so we can get translations going. (thinking about the afk)

**Comment by allilevine** [comment]
Task list from SOTB:

- [x] Preemptive strings https://github.com/Automattic/wp-calypso/issues/62796
- [ ] Discover "cards" are not yet showing. @vinimotaa Are we still working on icons/copy for these?
- [ ] CSS on dropdown
- [ ] Remove selected category on search
- [ ] Confirm the categories & tags on each category
- [ ] 4 items before the ------- on the dropdown

**Comment by lupus2k** [comment]
All these are added to #62685 
- `Discover` already shows categories, still needs CSS
- CSS on dropdown is done but please check 
- Remove Selected category on search

**Comment by lsl** [comment]
Meant to close https://github.com/Automattic/wp-calypso/pull/62685. Please see the note [here](https://github.com/Automattic/wp-calypso/pull/62685#issuecomment-1102332757).

Added a new PR (https://github.com/Automattic/wp-calypso/pull/62873) to handle just the category switcher addition. This should be good to merge after review. Tested against site, no site, jetpack site. I noticed a couple of quirks with search but they match production and our changes coming soon should fix.

> - CSS on dropdown is done but please check

Thanks, this looks great! This and whatever else I could got included in #62873.

**Comment by lsl** [comment]
Follow up PR https://github.com/Automattic/wp-calypso/pull/62881 to merge in all the tag search stuff on top of https://github.com/Automattic/wp-calypso/pull/62873. Looks like it needs an e2e test fix but its working really well - nice work @Rolilink / @lupus2k!

**Comment by allilevine** [comment]
I've opened https://github.com/Automattic/wp-calypso/issues/62891 to add the category cards.

**Comment by Rolilink** [comment]
Merged the new categories so closing this one 🎉
