### ISSUE TITLE
Do It For Me: Change wording in Site Information 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#62277]
### What

In https://wordpress.com/start/do-it-for-me/site-info-collection, change the wording: **_Name of your business `Required`_** and its description: **_Please enter the name of your business as you want it to appear on your new site._**

### Why

Users without businesses thought that it's only for businesses and not for individuals, so they get stuck in this step. 

### How

<img width="1545" alt="name of your business" src="https://user-images.githubusercontent.com/36863633/160236662-0efabbad-c04a-49bf-bb84-d10de7fbc9d1.png">

User report: 4895089-zd

**Comment by aneeshd16** [comment]
Thanks for reporting this! We are tracking this issue here: pdh1Xd-LF-p2

This screen will be replaced soon (~1 week), so we will be making these changes to the new screen. More details here: pdh1Xd-LF-p2#comment-1015

**Comment by aneeshd16** [comment]
We shipped this on 8th April (https://github.com/Automattic/wp-calypso/pull/62593#event-6395446518), closing this issue. Thanks for the feedback and please feel free to tag me in any future issues. 🙂
