### ISSUE TITLE
Plans: Blogger plan no longer allows uploading audio

### ISSUE THREAD

**Issue by villanovachile** [Automattic/wp-calypso#62282]
### Quick summary

The Blogger plan, now deprecated, no longer allows uploading audio files such as MP3s. This was working as recently as a month ago, but something has changed in the last month or so.

### Steps to reproduce

1. In the WordPress.com Dashboard go to Media, then click Add new.
2. Audio files are not selectable from the file selection dialogue.
3. Click the Audio tab in the Media Library, and you are prompted to upgrade to upload audio files, even if audio files are present in the library already.
4. Switch to WP-Admin view, go to Media Library, Add New, and Audio file types are not listed under allowed file types.

### What you expected to happen

I expected to be able to upload audio files on the Blogger plan.

### What actually happened

![image](https://user-images.githubusercontent.com/65082164/160258243-152518fb-47f5-4834-bd27-377fb4439214.png)

![image](https://user-images.githubusercontent.com/65082164/160258249-bbd9cc49-a4d7-4904-ab9d-f709c4f5dc9d.png)

### Context

Customer report

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Other notes

Subscription renewal notice still mentions ability to upload audio:

```
Your plan gives you some awesome features

* Best plan for Bloggers.
* Access to email support.
* 6 GB of storage space for images, documents, audio, and more.
```

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by mmtr** [comment]
Probably caused by D76467-code which wasn't aware that the Blogger plan allowed audio uploads. Will take a look at this shortly.

**Comment by mmtr** [comment]
Created D77727-code to fix this.
