### ISSUE TITLE
Add Additional Support Links to Block Card Description 

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#62284]
_This is a follow-up to #56091 to add documentation links to the remainder of the blocks._

Has nested blocks:

- [x] [Media & Text Block](https://wordpress.com/support/wordpress-editor/blocks/media-text-block/) - core/media-text
- [x] [Payments](https://wordpress.com/support/wordpress-editor/blocks/payments/) - jetpack/payments-intro (has a support link already, but could be updated to match the format of the rest of them.)
- [x] [Query Loop Block](https://wordpress.com/support/full-site-editing/theme-blocks/query-loop-block/) - core/query
- [x] [Contact Info Block](https://wordpress.com/support/wordpress-editor/blocks/contact-info-block/) - jetpack/contact-info

No nested blocks:

- [x] [Ad Block](https://wordpress.com/support/wordpress-editor/blocks/ad-block/) - jetpack/wordads
- [x] [Business Hours Block](https://wordpress.com/support/wordpress-editor/blocks/business-hours-block/) - jetpack/business-hours
- [x] [Calendly Block](https://wordpress.com/support/wordpress-editor/blocks/calendly-block/) - jetpack/calendly
- [x] [Donations Form Block](https://wordpress.com/support/wordpress-editor/blocks/donations/) - jetpack/donations
- [x] [Event Countdown Block](https://wordpress.com/support/wordpress-editor/blocks/event-countdown-block/) - jetpack/event-countdown
- [x] [GIF Block](https://wordpress.com/support/wordpress-editor/blocks/gif-block/) - jetpack/gif
- [x] [Image Compare Block](https://wordpress.com/support/wordpress-editor/blocks/image-compare-block/) - jetpack/image-compare
- [x] [Map Block](https://wordpress.com/support/wordpress-editor/blocks/map-block/) - jetpack/map
- [x] [Markdown Block](https://wordpress.com/support/wordpress-editor/blocks/markdown-block/) - jetpack/markdown
- [x] [Related Posts Block](https://wordpress.com/support/wordpress-editor/blocks/related-posts-block/) - jetpack/related-posts
- [x] [OpenTable Block](https://wordpress.com/support/wordpress-editor/blocks/opentable-block/) - jetpack/opentable
- [x] [Podcast Player Block](https://wordpress.com/support/wordpress-editor/blocks/podcast-player-block/) - jetpack/podcast-player
- [x] [Repeat Visitor Block](https://wordpress.com/support/wordpress-editor/blocks/repeat-visitor-block/) - jetpack/repeat-visitor
- [x] [Story Block](https://wordpress.com/support/wordpress-editor/blocks/story-block/) - jetpack/story
- [x] [Timeline Block](https://wordpress.com/support/wordpress-editor/blocks/timeline-block/) - jetpack/timeline
- [x] [WhatsApp Button Block](https://wordpress.com/support/wordpress-editor/blocks/whatsapp-button-block/) - jetpack/send-a-message
- [x] [Ratings Block](https://wordpress.com/support/wordpress-editor/blocks/ratings-block/) - jetpack/rating-star
- [x] [Revue Block](https://wordpress.com/support/wordpress-editor/blocks/revue-block/) - jetpack/revue
- [x] [Post Carousel Block](https://wordpress.com/support/wordpress-editor/blocks/posts-carousel-block/) - a8c/posts-carousel
- [x] [Feedback Button Block](https://wordpress.com/support/wordpress-editor/blocks/feedback-button-block/) - crowdsignal-forms/feedback
- [x] [Measure NPS Block](https://wordpress.com/support/wordpress-editor/blocks/measure-nps-block/) - crowdsignal-forms/nps
- [x] [Poll Block](https://wordpress.com/support/wordpress-editor/blocks/poll-block/) - crowdsignal-forms/poll
- [x] [Vote Block](https://wordpress.com/support/wordpress-editor/blocks/vote-block/) - crowdsignal-forms/vote
- [x] [SyntaxHighlighter Code Block](https://wordpress.com/support/wordpress-editor/blocks/syntax-highlighter-code-block/) - syntaxhighlighter/code
- [x] [Archives Block](https://wordpress.com/support/wordpress-editor/blocks/archives-block/) - core/archives
- [x] [Audio Block](https://wordpress.com/support/wordpress-editor/blocks/audio-block/) - core/audio
- [x] [Calendar Block](https://wordpress.com/support/wordpress-editor/blocks/calendar-block/) - core/calendar
- [x] [Categories Block](https://wordpress.com/support/wordpress-editor/blocks/categories-block/) - core/categories
- [x] [Classic Block](https://wordpress.com/support/wordpress-editor/blocks/classic-block/) - core/freeform
- [x] [Code Block](https://wordpress.com/support/wordpress-editor/blocks/code-block/) - core/code
- [x] [Custom HTML Block](https://wordpress.com/support/wordpress-editor/blocks/custom-html-block/) - core/html
- [x] [Embed Block](https://wordpress.com/support/wordpress-editor/blocks/embed-block/) - core/embed
- [x] [File Block](https://wordpress.com/support/wordpress-editor/blocks/file-block/) - core/file
- [x] [Heading Block](https://wordpress.com/support/wordpress-editor/blocks/heading-block/) - core/heading
- [x] [Latest Comments Block](https://wordpress.com/support/wordpress-editor/blocks/latest-comments-block/) - core/latest-comments
- [x] [Latest Posts Block](https://wordpress.com/support/wordpress-editor/blocks/latest-posts-block/) - core/latest-posts
- [x] [List Block](https://wordpress.com/support/wordpress-editor/blocks/list-block/) - core/list
- [x] [More Block](https://wordpress.com/support/wordpress-editor/blocks/more-block/) - core/more
- [x] [Page Break Block](https://wordpress.com/support/wordpress-editor/blocks/page-break-block/) - core/nextpage
- [x] [Paragraph Block](https://wordpress.com/support/wordpress-editor/blocks/paragraph-block/) - core/paragraph
- [x] [Preformatted Block](https://wordpress.com/support/wordpress-editor/blocks/preformatted-block/) - core/preformatted
- [x] [Pullquote Block](https://wordpress.com/support/wordpress-editor/blocks/pullquote-block/) - core/pullquote
- [x] [Quote Block](https://wordpress.com/support/wordpress-editor/blocks/quote-block/) - core/quote
- [x] [Tag Cloud Block](https://wordpress.com/support/wordpress-editor/blocks/tag-cloud-block/) - core/tag-cloud
- [x] [Reusable Block](https://wordpress.com/support/wordpress-editor/blocks/reusable-block/) - core/block
- [x] [Row Block](https://wordpress.com/support/wordpress-editor/blocks/row-block/) - core/group (might not be possible to separate Group and Row?)
- [x] [RSS Block](https://wordpress.com/support/wordpress-editor/blocks/rss-block/) - core/rss
- [x] [Search Block](https://wordpress.com/support/wordpress-editor/blocks/search-block/) - core/search
- [x] [Separator Block](https://wordpress.com/support/wordpress-editor/blocks/separator-block/) - core/separator
- [x] [Shortcode Block](https://wordpress.com/support/wordpress-editor/blocks/shortcode-block/) - core/shortcode
- [x] [Spacer Block](https://wordpress.com/support/wordpress-editor/blocks/spacer-block/) - core/spacer
- [x] [Verse Block](https://wordpress.com/support/wordpress-editor/blocks/verse-block/) - core/verse
- [x] [Video Block](https://wordpress.com/support/wordpress-editor/blocks/video-block/) - core/video
- [x] [Login/Out Block](https://wordpress.com/support/full-site-editing/theme-blocks/login-out-block/) - core/loginout
- [x] [Page List Block](https://wordpress.com/support/full-site-editing/theme-blocks/page-list-block/) - core/page-list
- [x] [Site Logo Block](https://wordpress.com/support/full-site-editing/theme-blocks/site-logo-block/) - core/site-logo
- [x] [Site Tagline Block](https://wordpress.com/support/full-site-editing/theme-blocks/site-tagline-block/) - core/site-tagline
- [x] [Site Title Block](https://wordpress.com/support/full-site-editing/theme-blocks/site-title-block/) - core/site-title
- [x] [Template Part Block](https://wordpress.com/support/full-site-editing/theme-blocks/template-part-block/) - core/template-part

cc @arcangelini As the list is quite long, let me know if you would like to put them in more of a priority order, sorted by highest impact.

I left out these blocks that are basically just embeds of different content:

[Loom Block](https://wordpress.com/support/wordpress-editor/blocks/loom-block/)
[Reddit Embed Block](https://wordpress.com/support/wordpress-editor/blocks/reddit-embed-block/)
[TikTok Block](https://wordpress.com/support/wordpress-editor/blocks/tiktok-block/)
[Twitter Block](https://wordpress.com/support/wordpress-editor/blocks/twitter-block/)
[YouTube Block](https://wordpress.com/support/wordpress-editor/blocks/youtube-block/)
[Eventbrite Block](https://wordpress.com/support/wordpress-editor/blocks/eventbrite-block/)

**Comment by arcangelini** [comment]
OK here are the troubles I ran into:

1. Markdown block already has a support link.
2. Group, Row and Reusable have variations so it does not allow me to extend the description.
3. Page break is not allowing the extension.

I will let you know when this is live, you may need to test the links just to be sure. Haha, I checked all the descriptions to make sure they appear correctly.
