### ISSUE TITLE
[Bug]: Blog posts block not retrieving posts

### ISSUE THREAD

**Issue by helenaartmann** [Automattic/wp-calypso#62290]
### Quick summary

User came to chat complaining about the latest posts not showing up on their homepage. They are using the blog posts block and when I checked on the editor all the posts were there, but not on the homepage. I tried reproducing it on my test Business site and was able to. So, the blog posts block is not retrieving the posts and not even showing up on the live site. 

I added the Query Loop block and my posts started showing up, confirming it was an issue with the blog posts block. 

### Steps to reproduce

- Go to edit your homepage
- Add the blog posts block 
- Check if the block is displaying your posts - it is not! 
- Go to the live site and refresh the page to see if you can see the posts 

### What you expected to happen

Posts should show up. 

### What actually happened

Nothing was visible. Not even an empty space for the added block. 

### Context

4898863-zn

### Browser

Google Chrome/Chromium

### Simple/Atomic

Atomic

### Other notes

I tried with different themes, Stanford, 2021 and 2012 as it was the one I was testing before, all with the same result. 

We ruled out plugin conflict as well. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by thekingsprojects** [comment]
Another case here in this follow-up ticket: 4933076-zen

User's "My Words" page has a Blog Posts block on it that stopped showing posts (I inspected the page, and there's no HTML for the block at all). I checked for plugin and theme conflicts, and the posts still did not appear. Their current theme is Coutoire, but the posts don't appear when switching to Twenty Twenty-One either.

Strangely, I *can't* replicate this on my Atomic test site. Even copying the contents of their post directly with the HTML/code editor and pasting it into my page, and using Coutoire as well, my Blog Posts block is just fine.

As a workaround, they're just using the "Set as posts page" feature instead.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Could Not Replicate**
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Test environments: 
     - AT site, Twenty Twenty-One theme, Blog Posts block added to static homepage. Appeared without issue in editor and live site
     - Simple site, Coutoire theme, Blog posts block added to static homepage. Appeared without issue in editor and live site.

*Example*
![Markup on 2022-10-25 at 18:52:55](https://user-images.githubusercontent.com/27249804/197915966-e9354cbb-27ad-450b-a3e4-b43f415e426f.png)

![Markup on 2022-10-25 at 18:52:07](https://user-images.githubusercontent.com/27249804/197915976-659e11b1-1e4c-4e2a-91e7-e3ab005e70cc.png)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @helenaartmann and @thekingsprojects , I wasn't able to replicate this issue in a test environment. As this report is fairly old, it's probably safe to assume this has resolved anyway.
