### ISSUE TITLE
Marketplace: Indicate that paid plugins require a plan upgrade

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#62299]
Currently all plugins require a plan upgrade to business or ecommerce plan but we don't do a good job at indicating that for paid plugins

![CleanShot 2022-03-28 at 15 20 21@2x](https://user-images.githubusercontent.com/12430020/160396789-601ea0e6-3d51-4eb2-8735-338a0da6a038.png)

What would be the best design & language to make sure users understand that paid plugins also need a plan upgrade?

**Comment by gcsecsey** [comment]
@vinimotaa could you please help us with the design on this one?

**Comment by cpapazoglou** [comment]
This seems resolved



![Image](https://user-images.githubusercontent.com/12430020/187205829-baf10389-2466-42d5-a2ab-a5b89efaad76.png)
