### ISSUE TITLE
Twenty Twenty : Image block rounding not working

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#62300]
### Quick summary

Add an image block within a column in a group to a site with Twenty Twenty

Set it to be rounded. 

The image shows elongated and not round as it does in the editor.

### Steps to reproduce

* There is an image of the user. It shows as a circle in the editor like this.
<img width="452" alt="Markup 2022-03-28 at 14 40 10" src="https://user-images.githubusercontent.com/13706336/160411651-5edb8331-c1ec-4016-9d22-bf17afa358e0.png">
* But on the published page it shows elongated like this - 
<img width="1095" alt="Markup 2022-03-28 at 14 40 39" src="https://user-images.githubusercontent.com/13706336/160411760-a733e55e-8fbc-4002-baa5-9d984076cfae.png">

### What you expected to happen

The site to reflect the editor

### What actually happened

The image on the public site is different

### Context

4899339-zd

### Theme-specific issue?

Twenty Twenty as it worked on Skatepark

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is to make a square source image. The rounding seems to be trying to match the ratio of the source image. This doesn't occur on skatepark

**Comment by upwardmomentum84** [comment]
Ran across this here in this ticket 4900721-zd-woothemes

The user is using Byrne theme.

**Comment by Greatdane** [comment]
@rickmgithub you mention skatepark and Twenty Twenty - is it happening on both?

Actually, any theme I choose the rounding seems to take the dimension of the image, so it is not always round

**Comment by Greatdane** [comment]
@rickmgithub closing this for now as no reply and unable to replicate.
