### ISSUE TITLE
Marketplace: Add marketplace CTA on /marketing/tools

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62308]
Adjust CTA on /marketing/tools to focus on premium plugins, and link to the Marketplace. New copy:

> **Explore our premium plugins**
> We've added premium plugins to boost your site's capabilities. From bookings and subscriptions to email marketing and SEO tools, we have you covered.
> Explore now

<img width="1074" alt="Screen Shot 2022-03-28 at 11 51 36 AM" src="https://user-images.githubusercontent.com/1689238/160438419-c26cdfd6-afc8-4ba4-8d8e-5225b1fd30fe.png">

Acceptance criteria:
- [ ] CTA button links to the Marketplace
- [ ] Copy is updated.
- [ ] @emmnyc85 approval.

Change copy for now; could be JITM if we were changing it.

**Comment by emmnyc85** [comment]
Thanks, @allilevine! Let's actually adjust as follows:

**Explore our premium plugins**
We've added premium plugins to boost your site's capabilities. From bookings and subscriptions to email marketing and SEO tools, we have you covered.
Explore now

**Comment by allilevine** [comment]
> Thanks, @allilevine! Let's add an exclamation point after explore now. 'Explore now!'

@emmnyc85 Thanks, added!

**Comment by allilevine** [comment]
@vinimotaa I've added this to the design board in case you want to weigh in / swap out the graphic.

**Comment by emmnyc85** [comment]
One item of note is that we are 1-2 weeks away from Yoast SEO Premium launching so the SEO tools comment is technically not accurate yet. We may want to shift that to.. 'email marketing and shipment tracking'. We can then change it once Yoast SEO Premium launches

**Comment by emmnyc85** [comment]
> > Thanks, @allilevine! Let's add an exclamation point after explore now. 'Explore now!'
> 
> @emmnyc85 Thanks, added!

just adding that I changed this comment: https://github.com/Automattic/wp-calypso/issues/62308#issuecomment-1080829935

Up to @vinimotaa on whether an exclamation point looks good in a CTA

**Comment by vinimotaa** [comment]
hey @allilevine, exclamation should be fine, we would need to update this illustration with an existing style we're working with. Let me reach out to one of our designers on this. When do we need this?

**Comment by allilevine** [comment]
> hey @allilevine, exclamation should be fine, we would need to update this illustration with an existing style we're working with. Let me reach out to one of our designers on this. When do we need this?

@vinimotaa Thank you! I put it in "Next" on the Expand Design board. @emmnyc85 Do you have a preferred timeline?

I'll remove it from this sprint for now since it needs the new illustration.

**Comment by emmnyc85** [comment]
@allilevine  / @vinimotaa - Thank you! Not urgent  - Within next two weeks?

**Comment by vinimotaa** [comment]
Hey @allilevine @emmnyc85 I requested a new illustration for this - in case we don't get it in time, let's just keep the one we have in place then we can replace it in the future.

**Comment by vinimotaa** [comment]
I designed this card to be more aligned with our overall new look&feel - I'll add the illustrations once that is ready!

<img width="848" alt="image" src="https://user-images.githubusercontent.com/97929097/162038849-ee4e3c12-6ce7-4dbb-bd76-dd69234e6492.png">

[Figma](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5?node-id=593:12805#176135037)

**Comment by emmnyc85** [comment]
These look great, @vinimotaa!

**Comment by emmnyc85** [comment]
@allilevine can we make this only visible to ecomm, biz and pro customers? I feel we may overcomplicate things for Free, premium or personal customers given they can't currently purchase premium plugins

**Comment by vinimotaa** [comment]
Hi folks, after a few rounds of feedback/iterations, here are two options we could consider for the illustrations.

Option A
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/97929097/163247267-bf2f87d2-c6c5-4a20-8083-9ea8a4d2c65e.png">

Option B
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/97929097/163247313-d39eca2c-828d-4cb4-913a-c3d4ba69093a.png">

@ianstewart has already pointed the option B as his favorite, but I'd like to also hear from @emmnyc85 and @allilevine?

**Comment by allilevine** [comment]
> @allilevine can we make this only visible to ecomm, biz and pro customers? I feel we may overcomplicate things for Free, premium or personal customers given they can't currently purchase premium plugins

@emmnyc85 Would we show the old CTA to free/premium/personal? I was thinking it would be an upsell, like other gated feature CTAs we show. 

> @ianstewart has already pointed the option B as his favorite, but I'd like to also hear from @emmnyc85 and @allilevine?

@vinimotaa I like both, but I'm leaning towards option A because it looks more like an app store to me.

**Comment by emmnyc85** [comment]
Nice work, @vinimotaa.
- I worry that 'A' may be misleading. For example, we aren't really driving them towards FB and Google plugins. By showcasing those, their expectations won't be aligned correctly with our offerings. For that reason, I recommend 'B'
- @allilevine - I'm not sure what to do here regarding showcasing to al customers or just Pro/Biz/eComm. I trust your perspective here given how we've handled for similar offerings/products in the past. So, if it works as an upsell in addition to a path just to purchasing plugins for pro/biz/ecomm, then let's go with that

**Comment by allilevine** [comment]
> I worry that 'A' may be misleading. For example, we aren't really driving them towards FB and Google plugins. By showcasing those, their expectations won't be aligned correctly with our offerings. For that reason, I recommend 'B'

@vinimotaa B it is! 🙂 

> @allilevine - I'm not sure what to do here regarding showcasing to al customers or just Pro/Biz/eComm. I trust your perspective here given how we've handled for similar offerings/products in the past. So, if it works as an upsell in addition to a path just to purchasing plugins for pro/biz/ecomm, then let's go with that

@emmnyc85 If we don't see a value in directing customers to Marketplace Tools, let's change it for all customers. But let me know if I'm missing something there.

**Comment by emmnyc85** [comment]
@allilevine  Some customers are getting value but i worry that non Pro customers will be disappointed when they get to the marketplace given they can't purchase anything. That's all I'm saying. So I don't want to totally redirect if it may not be a positive experience for all customers

**Comment by emmnyc85** [comment]
Thinking about this again, @allilevine. You are right. I think we can change for everyone. That existing CTA goes to /billing-tools and that gets <100 visits/month according to GA https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a10673494w77576050p202759623/_u.date00=20220301&_u.date01=20220331&explorer-table.filter=business-tools&explorer-table.plotKeys=%5B%5D/

**Comment by allilevine** [comment]
> Thinking about this again, @allilevine. I think we can change for everyone. That existing CTA goes to /billing-tools and that gets <100 visits/month according to GA https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a10673494w77576050p202759623/_u.date00=20220301&_u.date01=20220331&explorer-table.filter=business-tools&explorer-table.plotKeys=%5B%5D/

Okay! cc @lupus2k since it looks like you started work on this, also @galakhyati in case you can weigh in on this user experience.

**Comment by galakhyati** [comment]
From my experience, I've rarely seen users clicking through the Marketing CTA and using the Business tools listed on the page. 

I think we should redirect the CTA to all WordPress.com users to our Marketplace plugins. This can act as any upgrade CTA in case the user is on the Free/Personal/Premium plan.

**Comment by lupus2k** [comment]
PR updated here #62789
