### ISSUE TITLE
Marketplace: Add marketplace CTAs to /posts and /pages

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62309]
Integrate a dismissable notice on /posts or /pages or in site editor for users who 1) have not visited /plugins in the past 30d, and 2) have created but not yet launched their site.

**Comment by vinimotaa** [comment]
hey @allilevine!

Is the requirement here to design another modal window like the one from #58505?

**Comment by allilevine** [comment]
@vinimotaa @emmnyc85 From the discussion here: pdh6GB-uo-p2#comment-1086 it should be a one-time dismissable notice. 

Sorry about the confusing link to the modal! I hadn't updated the description.

**Comment by vinimotaa** [comment]
got it @allilevine! is there any design requirement here? or the team is going to implement the modal we already designed?

**Comment by allilevine** [comment]
> got it @allilevine! is there any design requirement here? or the team is going to implement the modal we already designed?

@vinimotaa The design need here is for a decision: is adding a dismissable notice here the right course? Is it too disruptive?

I'm not sure we can use the modal for a notice but @emmnyc85 let us know if that's what you had in mind.

**Comment by emmnyc85** [comment]
Thank you both. A few thoughts to add: 

(1) can we make this only visible/eligible to Biz, eComm and Pro Plan customers to avoid a confusing product experience? And if the person sees the pop-up on /posts, then they don't see it on /pages and vice-versa? If too complicated, let's just plan to do it on /posts as there are more unique page views for that [per GA](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a10673494w77576050p202759623/_u.date00=20220301&_u.date01=20220331/)

(2) I think the existing design is fine to use

(3)  - we have some feedback from Mary so let's wait to see if there's anything further from Mary here before shipping anything: https://dotcommarketplacep2.wordpress.com/2022/03/15/marketplace-owned-property-marketing-dynamic-ctas-and-jitms-modals/#comment-1215

cc: @vinimotaa @allilevine

**Comment by cpapazoglou** [comment]
We will try to leverage more specific flows than just "advertising" the marketplace in our current users.
