### ISSUE TITLE
Marketplace: Add WooCommerce Product Add-ons

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62311]
Add Product Add-ons extension to the marketplace. Use WooCommerce extension logo.
https://woocommerce.com/products/product-add-ons/

Documentation: PCYsg-AhH-p2
URL: pdh6GB-yt-p2
Slug: woocommerce-product-addons
Name: WooCommerce Product Add-Ons

### Add billing products
 - [x] Post preflight p2, example pdh6GB-vf-p2
 - [x] Add product, yearly, monthly plans see docs PCYsg-CJy-p2

### Create store products
 - [x] Reserve store product ID's, example D76056-code
 - [x] Add catalog mapping, example D76057-code
 - [x] Generate store products, docs PCYsg-CJy-p2
 - [x] Add store product translation, example D76326-code
 - [x] Add marketplace product entry to endpoint (and image if required), example D77429-code
 - [x] Insert vendor product info, documentation: PCYsg-CJy-p2
 - [x] Confirm plugin can be purchased and installed by non a11n users

**Comment by paulopmt1** [comment]
Preflight: pdh6GB-yt-p2

**Comment by paulopmt1** [comment]
Reserve store product ID's: D77792-code

**Comment by paulopmt1** [comment]
Product catalog: D77773-code

**Comment by paulopmt1** [comment]
Product translation: https://code.a8c.com/D77927

**Comment by paulopmt1** [comment]
Product translation: D77927-code

**Comment by paulopmt1** [comment]
Product entry: D77960-code
