### ISSUE TITLE
[Bug]: Confusing wording for one-off premium-content payments

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#62329]
### Quick summary

The wording for one-off payments is possibly a little bit confusing on the /earn page. Is subscription the best description for a one-off payment to access premium content?

![image](https://user-images.githubusercontent.com/93301/160564394-8a47799d-51f8-4cce-887b-e5b1a2c39f61.png)

### Steps to reproduce

1.  Setup a wp.com simple or atomic site
2.  Go to wordpress.com/earn, connect to stripe etc, add a one-off payment plan
3.  Add a premium content block
4.  Choose the already created one-off payment plan
5.  Publish the post
6.  Open the site in a different browser, where you're not logged in
7.  Press subscribe and fill out the form
8.  I get a message about making a one-off payment
9.  I can see the content
10.  As the subscriber, I can see the payment in https://wordpress.com/me/purchases/

### What you expected to happen

When I click on the payment as a subscriber I expected to see details of the payment that's well worded.

### What actually happened

The wording is a bit confused, it says 'Subscription Details' at the top and 'Stop one-off subscription' seems awkward.

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by Copons** [comment]
If the product is a one-time payment, we should:

- Change the screen title from `Subscription Details` to `Product Details`.
- Change the `Stop Foobar subscription.` message to `Remove Foobar product.`.

For all products we should:

- Change the browser tab title to `Product Details`.
  - Let's double-check if we have access to the product type at this point in the render. In that case we can also only replace this if it's a one-time payment.

**Comment by Copons** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/62604
