### ISSUE TITLE
Argent theme: WooCommerce product page lost its margins and alignment

### ISSUE THREAD

**Issue by sharonlaker19** [Automattic/wp-calypso#62327]
### Quick summary

The product pages don't have margins on the Argent theme.

![product page argent theme](https://user-images.githubusercontent.com/71630911/160545382-fdb2fdaa-0853-4b4c-b666-896388d940cd.jpg)

### Steps to reproduce

1. Start with any website that already has some products created.
2. Switch the theme to Argent.
3. Check the product page layout on the new theme.

### What you expected to happen

To have a neatly aligned product page with margins on the sides of the page. For example, this is how the product page displays on the Storefront theme:

![storefront product page example](https://user-images.githubusercontent.com/71630911/160545996-08a985eb-d19d-4427-b564-5c5123700831.jpg)

### What actually happened

The text extends all the way to the end of the screen and has no spacing. The rest of the page is misaligned as well.

![argent theme product page](https://user-images.githubusercontent.com/71630911/160544479-1a4d1a42-059f-4bc7-beae-0fb6549c9f72.jpg)

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Yes, Argent theme.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

I recommended they switch to a different theme.

**Comment by Robertght** [comment]
Thank you for reporting this @sharonlaker19 !

It looks like there's a duplicate. I'm closing it in favor of this one: https://github.com/Automattic/wp-calypso/issues/62327

**Comment by sharonlaker19** [comment]
Thanks, @Robertght looks like you've linked to the same report though. Can you share the open issue here to close the loop, please? Thanks!

**Comment by Robertght** [comment]
Apologies! Copy-pasta error here. 

https://github.com/Automattic/themes/issues/2412
