### ISSUE TITLE
Share Media from other apps to a post with the block added

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#62358]
### What

From a customer in #33138327-HC: 

I would like to hit the share button on the voice memmo: 
- Hit word press on the share sheet, 
- Have a new post come up in the WordPress app with the M4a file already in the audio block

### Why

From the customer: 
 I regularly post audio from my Voice Memos app. I have to save it from Voice Memos to the Files app, and then create a WordPress post in the WordPress app, and then choose from the iOS files app. This is doable but a lot of work.

**Comment by supernovia** [comment]
Right now Voice Memos _does_ let me share to WordPress. It creates a new post, but does not upload the media, even on a plan that allows audio uploads.

**Comment by inaikem** [comment]
Pinged Interstellar asking for a confidence check on next steps: p1650349282203829-slack-C03B55A0PAR

Possible next steps: open an issue in `wordpress-mobile/WordPress-iOS` and move this issue to the [HE User Waiting](https://github.com/Automattic/wp-calypso/projects/112) board.

**UPDATE:**
Recreating this as a feature request in the app repo as suggested in the discussion thread above.

**Comment by inaikem** [comment]
I created a feature request in the `wordpress-mobile/WordPress-iOS` repo (above). Closing this issue and making a note in the [HE Cross-repo Watchlist](https://github.com/Automattic/wp-calypso/projects/116#card-80802245).

@JessBoctor would you like to update the user directly to let them know this is being handled in the app repo?
