### ISSUE TITLE
Feedback: Vertical Images Curator

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#62369]
# Description
Collecting feedback for the Vertical Images Tool  See mc tools verticals/#/images
Add feedback in the comments and Ganon will triage and prioritize features. ❗ If possible PLEASE INDICATE YOUR REQUESTS AS
1.   I need this fix/feature to use this tool effectively & efficently
or 
3. This is a nice-to-have feature

# Do for MVP (keep updating this as feedback rolls in)
- [x] It is not clear that we can actually select the images in Pexels tab and import the images. Suggestion: Add a paragraph, something like: "Select images to import ...."
  - [x] Make the Pexels tab a button named “Select Pexels Image”. See https://github.com/Automattic/wp-calypso/issues/63481
- [x] I click on Pexels tab > select a vertical > see images > select a new vertical > click the X in the dropdown list > tab gets switched to WordPress - can we fix this so it stays on Pexels?
  - [x] We don't have tabs after https://github.com/Automattic/wp-calypso/issues/63481 is shipped.
- [x] Bump up to the parent vertical images
  - [x]  https://github.com/Automattic/wp-calypso/issues/63323
- [x] Don't use cropped square thumbnail under WordPress tab
  - [x] https://github.com/Automattic/wp-calypso/issues/63368
- [x] Show more info about the image such as file size, dimensions, and file type
  - [x] https://github.com/Automattic/wp-calypso/issues/63368
- [x] When selecting an image in the Pexels tab, can we preselect the orientation which is present in the current filter? E.g. when I click the "landscape" filter, if I then select an image there, the landscape checkbox should (ideally) be already ticked.
  - [x] See D77653-code
- [x] We need guidance on the image tool itself: Image size should be less than X KB. See discussion: D80152-code
  - [x] 32-gh-Automattic/ganon-issues

# Other feedback

- [x] After uploading an image, there is no information on how the caption, description, tags etc are being used in the final verticalized designs. Suggestion: add hints/helper text on the input fields?
- [x] It is not clear how to "unselect" images in the Pexels tab.
  - Now, we remove the “Select Orientation” step for Pexels images, so we just need to click again to unselect.
- [x] When selecting an image in the Pexels tab, can we preselect the orientation which is present in the current filter? E.g. when I click the "landscape" filter, if I then select an image there, the landscape checkbox should (ideally) be already ticked.
- [x] Should we change "Wordpress" tab to something else? Maybe "Curated Images" or ????
  - We remove the tabs and show the "Curated Images" directly

**Comment by arthur791004** [comment]
Also, we might need

* View by tags

**Comment by autumnfjeld** [comment]
Adding some requests from this post from @that-mike-bal 👍  pbxlJb-1Ga-p2#comment-1480

*  basic cropping/focal point adjusting tools when uploading photos
* It would also be great to be able to drag and drop multiple photos for uploading in the tool. I think editing them one by one is fine but from a workflow standpoint, most people will download several from a site and then go to upload them.

**Comment by that-mike-bal** [comment]
It would also be great if there was a way to "fork" or duplicate an image so we could have multiple versions. That would also require some kind of logic for knowing

- When to pull which variation - maybe orientation for now
- Not using multiple variations of the same image when populating a recipe

**Comment by roo2** [comment]
Also linking some discussion around issues I found here p1650283374220129-slack-CRWCHQGUB
Summary: 
**Currently Firefox isn't supported. We can't edit or delete images in FF**
For now we're only supporting chrome

**I personally can't delete images from the images tool**
I get 403 errors but this doesn't seem to affect other people, may be something particular to my setup

**I think that the multiple selection and edit mechanism is confusing**
p1650283635343059/1650283374.220129-slack-CRWCHQGUB

**Comment by arthur791004** [comment]
> I think that the multiple selection and edit mechanism is confusing

I just follow the mechanism from WP.com 😂

**Comment by autumnfjeld** [comment]
Show vertical heirarchy in the tool.  pbxlJb-1CZ-p2#comment-1460   It isn't clear to me why this is really needed, so we should discuss more with Mike in the future. 

EDIT: I think Arthur already figured this out! 🚀

**Comment by iamtakashi** [comment]
<img width="1438" alt="Screenshot 2022-05-04 at 14 07 35" src="https://user-images.githubusercontent.com/908665/166687722-42c571d7-0c44-4dbc-95bf-cabcb845e742.png">

This is likely following the design of the WP.com media library, but the cropped square thumbnail makes it difficult to know the image proportion and orientation. The design used for the Pexel tab is better.

<img width="1439" alt="Screenshot 2022-05-04 at 14 07 45" src="https://user-images.githubusercontent.com/908665/166687769-486bfb39-3289-4859-b086-7cc2efab3599.png">

**Comment by iamtakashi** [comment]
![mc a8c com_verticals_](https://user-images.githubusercontent.com/908665/166688013-35345f6f-605d-4e54-a23e-4c32e9b9d33b.png)

Can we have more info about the image such as file size, dimensions, and file type? I think it'll be useful.

**Comment by arthur791004** [comment]
> This is likely following the design of the WP.com media library, but the cropped square thumbnail makes it difficult to know the image proportion and orientation. The design used for the Pexel tab is better.

Yes, this follows the design of the WP.com and I'll change to the design used for the Pexel tab

> Can we have more info about the image such as file size, dimensions, and file type? I think it'll be useful.

Okay, I could align the info with the WP.com media library.

![image](https://user-images.githubusercontent.com/13596067/166857231-6058ffd9-1bcd-4621-a520-d1223941915e.png)

**Comment by iamtakashi** [comment]
Thank you, @arthur791004!

**Comment by arthur791004** [comment]
@iamtakashi I've changed to show the own orientation of the image in the WordPess tab and add more file info when you edit the image!

**Comment by iamtakashi** [comment]
That was quick! It's much better now. Thank you @arthur791004!

**Comment by arthur791004** [comment]
@that-mike-bal @iamtakashi I'm trying to improve the experience of the Vertical Images Tool. Here are some changes

* Make a hierarchical vertical list in the sidebar and you can select the vertical or expand to select the descendant one.
* Remove the tabs and show the images with a specific vertical directly. And anyone won't be confused about the meaning of the tabs. Then, you can import the Pexels Images by clicking the “Select Pexels Images” button.
* Besides, you don't need to select the orientation when you want to import the Pexels Images. We use the orientation of the src image by default. But you can still update the orientations when you edit the images.

Do you think it's easier to use?

![image](https://user-images.githubusercontent.com/13596067/167616828-09dc6f84-8af1-49dd-96df-84d770e786b5.png)

**Comment by arthur791004** [comment]
@that-mike-bal @iamtakashi [The above improvement](https://github.com/Automattic/wp-calypso/issues/62369#issuecomment-1122262789) is shipped 🚢

**Comment by iamtakashi** [comment]
@arthur791004  I only have noticed this after using it, but it's difficult now to find the vertical that I'm looking for. Seeing the hierarchy might help for something, but It was easy when I just needed to start typing the name of the vertical in the input field.

**Comment by arthur791004** [comment]
@iamtakashi Yep, we could add the search bar in the future. But AFAIK we start from the top-level verticals and then move down. So, I think it's enough for now. What do you think?

**Comment by autumnfjeld** [comment]
@arthur791004 I think your insight is correct for this stage of the project.   The common usage for the people that will do image sourcing is that they will be given instructions for which verticals to populate (starting at higher levels and then going down to children).   @that-mike-bal can let us know if that is correct. 🙂

But......if it is easy to add the search back in, maybe we should just go ahead and add it back.

**Comment by that-mike-bal** [comment]
That's right, we've got a list we can work down so we should be able to find those. I think the other use case is those wanting to add to what we already have and maybe not knowing which exact term they are looking for but we can probably tackle that later.

**Comment by iamtakashi** [comment]
> Yep, we could add the search bar in the future. But AFAIK we start from the top-level verticals and then move down. So, I think it's enough for now. What do you think?

That makes sense. Thank you all for the info!

**Comment by arthur791004** [comment]
I have filed issues for the rest of the feedback as follows
* 33-gh-Automattic/ganon-issues
* 34-gh-Automattic/ganon-issues
* 35-gh-Automattic/ganon-issues
* 36-gh-Automattic/ganon-issues

Once 32-gh-Automattic/ganon-issues and 37-gh-Automattic/ganon-issues are done, we can close this issue.

**Comment by arthur791004** [comment]
Close it as 32-gh-Automattic/ganon-issues and 37-gh-Automattic/ganon-issues are done. Feel free to raise any feedback to https://github.com/Automattic/ganon-issues/issues
