### ISSUE TITLE
Account: Sometimes account verification emails aren't sent, or don't reach the customer

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#62371]
### Quick summary

Account: Sometimes account verification emails aren't sent, or don't reach the customer. We should identify the underlying bug and fix it.

### Steps to reproduce

Don't have steps to reproduce here. Sign up for an account and see if you get a confirmation email.

### Context

- Came up in this discussion: p1648621206052699/1648617130.364579-slack-C02AVAR9B
- We can use this GitHub issue to track such reports.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Not applicable.

### Browser, operating system and other notes

Not applicable.

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by supernovia** [comment]
I've added a note to the conversation in slack. We'll wait for a reply there.
p1650332433823219/1648617130.364579-slack-C02AVAR9B

**Comment by inaikem** [comment]
Pinged Slack for an update/next step on this discussion: p1654053259762919/1648617130.364579-slack-C02AVAR9B

**Comment by arunsathiya** [comment]
Closing this in favor of a new button on the account page to resend verification email:

- https://github.com/Automattic/wp-calypso/issues/64345
