### ISSUE TITLE
Flaky E2E: Advanced post flow needs to retry on publishing posts

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#62383]
### Spec file

editor__post-advanced-flow.ts

### TeamCity ID

7656326

### Logs

The published post launched in a new browser shows "oops, that couldn't be found", which means we had a race condition before the post was saved to the database.

We should just add the retry and reload to that function!

**Comment by worldomonation** [comment]
I think this is no longer relevant now, as we have retries in the initial posting of the post:
https://github.com/Automattic/wp-calypso/blob/79b523ffc7916f62b3799b6ecfe194ee87cf2c1b/test/e2e/specs/editor/editor__post-advanced-flow.ts#L73-L81
