### ISSUE TITLE
Calypso on Vagrant

### ISSUE THREAD

**Issue by Glis** [Automattic/wp-calypso#624]
I was actually wondering about the Vagrantfiles I found in the repository root.
When I hear about wp-calypso I wanted to test it. I always use vagrant for development, so I pulled one of my vagrantboxes with node/npm/apache2 installed and tried to clone/make there but it didn't work right out of the box, even if I have port 3000 forwarded. 

What else do I need to do tomake it work? or it's currently not supported? what changes do I need to do in the hostfile of Guest or the Host? Do I need to serve the public folder with apache/nginx?

Thank you in advance.

**Comment by nb** [comment]
Hey @Glis, we have an internal vagrant environment for Calypso, which we are working on open-sourcing, it should be out in the next week or two.

**Comment by bfirsh** [comment]
@nb Quite curious to see this! Any news on when it might be available?

Out of interest - does the Vagrant setup use Docker/boot2docker like the Vagrantfile in the repo? Did you consider using Docker Toolbox/Compose for this, or is there a reason why you didn't do it that way?

**Comment by nb** [comment]
@bfirsh I guess I was optimistic about the timeline :-) No new timeline, but we’ll try to prioritize it. It’s not using Docker, because this way we’re avoiding an extra level of abstraction.
