### ISSUE TITLE
My Sites: don't autoplay media in Calypso posts / pages list

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#6241]
#### Steps to repeat
1. Starting at URL: WordPress.com
2. Publish a post or page with a media file that audio plays, video and audio both produce this effect (add autoplay=true to the shortcode to make it play automatically)
3. Make sure this post or page appears on your front page (static front page or latest posts works)
4. Load WordPress.com and choose the site
5. The audio will play from the clip

The same thing happens for any portion of my sites - such as /people or /pages, once you first click on that site, the audio plays

Feel free to use the spncr.live test site if you want
#### What I expected

Media should only play when the site itself is loaded, not My Sites
#### What happened instead

Audio plays when I load My Sites or any other pane 
#### Browser / OS version

Tested on Safari Firefox and Chrome - same effect
#### Screenshot / Video

https://cloudup.com/cpNVuj2TcDp
#### Context / Source

This came from a me testing autoplay for a user, since we don't show how to do it in the documentation, I tested it on my own site. The resulting bug was found afterwards when returning to test other things.

**Comment by rachelmcr** [comment]
#bug-scrub

I tested this issue with the steps provided and could no longer reproduce.
