### ISSUE TITLE
Live chat FAB: My Home section should have the FAB icon

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#62416]
### What

When you go to the My Home section of your site at https://wordpress.com/home/siteurl, you will notice that there is no FAB icon at the bottom right corner. Whereas if you go to any other page/section like Pages, Posts, etc, they all have the FAB icon. We should add the FAB icon to My Home section too.

### Why

To keep it as a uniform experience throughout the product for our users. We decided on this based on the Live Chat Audit Experiment.

### How

<img width="874" alt="Screenshot 2022-03-31 at 9 19 18 AM" src="https://user-images.githubusercontent.com/16509219/161064545-dfea0e97-52bc-4cb1-9693-f19f1f157104.png">
It should be added here like other sections.

**Comment by inaikem** [comment]
Great suggestion! Moving across for prioritisation.

**Comment by jordesign** [comment]
Closing this as the FAB is being removed as part of the upcoming Help Center work.
