### ISSUE TITLE
More Fonts for test sites

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#62412]
A request from p9Jlb4-44k-p2

We want to make it easier for other A12s to test out other fonts we don't yet supply to users, a good way to do this could be gating the registration behind a new site sticker and adding a toggle to the RC. For starters we should look at registering all of google fonts behind a sticker check.

**Comment by Addison-Stavlo** [comment]
Diff to add loading logic:  D80004-code ✅ 

Diff to enable sticker toggle in RC: D80323-code ✅

**Comment by simison** [comment]
@Addison-Stavlo this feels like it deserves some publicity via P2ing? e.g. at dotcomdesign p2 or themedev p2

**Comment by Addison-Stavlo** [comment]
> @Addison-Stavlo this feels like it deserves some publicity via P2ing? e.g. at dotcomdesign p2 or themedev p2

I responded on the original P2 yesterday and cc'd both theme and design teams in the response. Im seeing likes as folks catch up on p2 notifications, do you think a separate p2 is beneficial here @simison ?
