### ISSUE TITLE
Pro: Unable to complete a site creation flow when connecting a subdomain

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#62428]
#### Steps to reproduce

- Start at https://wordpress.com/start
- Choose the option to use a domain you own.
- Enter a subdomain like `new-pro-plan.workroom.blog`
- When prompted to choose a plan, choose `Pro` plan as that supports domains.

#### What I expected

Able to complete site creation flow and have the domain connected.

#### What happened instead

The site creation flow gets stuck in a loop.

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/18581859/161101879-4842afc5-b266-41e8-bb31-d4906684c365.png">

Video of the issue:

https://user-images.githubusercontent.com/18581859/161101950-2a8e6c08-dee6-4460-a813-4aff70eec755.mov

**Comment by arunsathiya** [comment]
I am not sure what the behavior is when attempting to connect a root domain. I don't have one to test with at the moment.

**Comment by arunsathiya** [comment]
Seeing a similar behaviour if I choose the Free plan after entering the subdomain to connect. 



https://user-images.githubusercontent.com/18581859/161102649-34065e73-b742-4df3-9164-e03e60182503.mov


Since domains are available only on the Pro plan, I believe we shouldn't show the plan selection screen, should add the Pro plan directly to cart.

**Comment by delputnam** [comment]
Domains _can_ be used with the free plan.  They just can't be made primary.  This is the same as it has been in the past and there is no change to this policy.

We will have a look at the issue with the subdomain though.

**Comment by DavidRothstein** [comment]
>Since domains are available only on the Pro plan, I believe we shouldn't show the plan selection screen

I think this meant to say "Since domain **connections** are available only on the Pro plan", right?

In which case, I think it's actually a valid point?  (If you select Free on that page, the end result, I believe, is that it will add Pro to the cart for you anyway... so it's not a real choice :smile: )

**Comment by delputnam** [comment]
Yes.  Sorry.  I wasn't clear with my response either.  We're looking at the subdomain issues. (both the message and plan selection)

**Comment by delputnam** [comment]
We've deployed D78079-code which fixes the issue related to showing the error about the .blog subdomain.

**Comment by formosattic** [comment]
I tested, and was able to get through to checkout.

Closing, but open if issue still happens.
