### ISSUE TITLE
Espied Theme Portfolio Images Left Margin on size-big class images too far left

### ISSUE THREAD

**Issue by zoetropeexplosn** [Automattic/wp-calypso#62424]
### Quick summary

While working on this ticket: 4908542-zd-woothemes I found that the Espied theme's portfolio project page shows images that are unaligned in the block editor as running off the left side of the screen when viewing the live page. When images are center aligned in the block editor, they show as left-aligned on the live page. This seems to stem from a class `size-big` being added to large images. 

### Steps to reproduce

1. Create a portfolio page with the theme Espied set for the site. 
2. Add images and captions to the portfolio page.  
3. Publish page.
4. View live page. 

Alternatively:
1. Center align images on portfolio page in the block editor. 
2. View live page.

### What you expected to happen

The images should be visible entirely on screen and left-aligned if alignment is not set. If center alignment is set, the images should display centered on the page. 

### What actually happened

Images appear far left and hanging off the screen when unaligned. When center aligned, the images show up farther left of center. 

### Context

This CSS code appears to repair the issue:

`/* remove negative margin on large images that are center aligned | XXXXXX-hc eD */
.aligncenter .size-big {
	margin-left: unset;
}`
`/* center align captions in centered images | XXXXXX-hc eD */
.aligncenter figcaption {
	text-align: center;
}`

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Espied

### Browser, operating system and other notes

All browsers, all operating systems. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

This CSS code appears to repair the issue:

`/* remove negative margin on large images that are center aligned | XXXXXX-hc eD */
.aligncenter .size-big {
	margin-left: unset;
}`
`/* center align captions in centered images | XXXXXX-hc eD */
.aligncenter figcaption {
	text-align: center;
}`

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Seems this is now working as expected - no issues with unaligned or aligned images on a Portfolio Project post type with the theme Espied activated. 

**Simple**

https://github.com/Automattic/wp-calypso/assets/27249804/6c5fde37-85dd-41c8-8e39-eb1723d0841a

**Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/5ea8eed1-0b78-49b8-a9b5-d10e01bb170c

📌 ACTIONS
- Closing as not reproducible
