### ISSUE TITLE
Anchor.fm: Clicking on Convert to blog post creates new sites

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#62435]
@sixhours [noted](D77876-code) that using the Anchor.fm 'Convert to blog post' functionality on different episodes of the same podcast doesn't add posts to the same blog but instead tries to create new sites.

**Comment by sixhours** [comment]
For reference, this is the step-by-step to reproduce the issue:

1) Create a new episode for an existing podcast that's already connected to WordPress.com
2) Publish the episode
3) You'll be shown a modal like this one:
<img width="636" alt="Screen Shot 2022-03-31 at 3 09 28 PM" src="https://user-images.githubusercontent.com/2124984/161131342-5d1d5a92-992f-403d-bab7-18d9071bdce0.png">
4) Click "Convert to blog post"
5) Which lands on a URL like:

`https://wordpress.com/new?anchor_episode=[episode_id]&anchor_podcast=[podcast_id]&spotify_url=[spotify_url]`

Which puts you in the Anchor new site setup flow and creates a new site.

**Comment by sixhours** [comment]
This randomly started working as expected for me yesterday. Instead of creating a new site, it dropped me into the editor with my new episode. We may be able to close this as a fluke. 🤷‍♀️

**Comment by blackjackkent** [comment]
Closing since we can no longer reproduce. (Maybe something was fixed on Anchor's end.)
