### ISSUE TITLE
[Bug]: Monthly toggle showing for the Pro plan on the Plugins page: Conditionally remove it

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#62437]
### Quick summary

This was deliberately removed in https://github.com/Automattic/wp-calypso/pull/62276, but may have removed too much, since the Marketplace Plugins themselves are supposed to be sold monthly: p1648748611396109-slack-C031TFM2NKC.  It has now been reverted in https://github.com/Automattic/wp-calypso/pull/62434.

I am not sure all the details of how this worked before, but my rough sense is that the toggle should always be there, **except in the case where you're looking at a Free plugin that requires the Pro plan (because then it really is only yearly)**.

Otherwise:
- For a paid Marketplace plugin, you should get the toggle.
- For a paid Marketplace plugin that requires the Pro plan (e..g if you're on a free site currently) then you should get the toggle, but toggling it should only toggle the Marketplace product - the Pro plan should remain at the annual price.  So if you toggle to monthly and then checkout, you'd be expected to get a monthly Marketplace plugin and an annual Pro plan in the shopping cart

(I think both of the above are how it's working now after the revert.)

### Steps to reproduce

1. Go to https://wordpress.com/plugins/wordpress-seo/[site] on a site that has the Free plan.
2. Notice there's now a monthly/annually price toggle there, which does nothing because the Pro plan is only sold annually.

![Screenshot from 2022-03-31 15-51-55](https://user-images.githubusercontent.com/235183/161137798-21595c9e-be3f-4f02-91bf-ecb1883a27dd.png)

### What you expected to happen

No toggle in the above scenario (same as after the original fix in https://github.com/Automattic/wp-calypso/pull/62276).

### What actually happened

The toggle was there.

### Reproducibility

Consistent

**Comment by cpapazoglou** [comment]
@WBerredo added this on our current sprint in case it's related to the feature checks you will be introducing.

**Comment by gcsecsey** [comment]
@DavidRothstein I've tested the scenarios you've listed above, and I think the PR covers all cases. Nonetheless, please take a look at it just to be sure! 🙂
