### ISSUE TITLE
Themes: analytics tracking of WebPreview / ThemePreview events

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#6244]
We should be tracking with analytics the `WebPreview` and/or `ThemePreview` component with:
- Open events (from where?)
- Close events
- Pop-up external in new tab
- Responsive icons switches
- Taps on the button to the right (i.e. "Pick this theme")

This would be useful to improve the component, and see the flows that pass through that for important actions.

/cc @ehg FYI

**Comment by ehg** [comment]
> Open events (from where?)

These should be done from `WebPreview` wrappers.

> Close events

Probably also from `WebPreview` wrappers?

> Pop-up external in new tab
> Responsive icons switches

Probably best in `WebPreview`.

> Taps on the button to the right (i.e. "Pick this theme")

Wrappers again :)

Aside: It'd be really nice to consolidate all the various previews into the preview layout at some point.

**Comment by folletto** [comment]
> Aside: It'd be really nice to consolidate all the various previews into the preview layout at some point.

👍
