### ISSUE TITLE
Marketplace: Unable to install WPML OTGS Plugin ( Malicious Error )

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#62459]
### Quick summary

When uploading the WPML OTGS installer plugin via https://wordpress.com/plugins/upload/ a malicious error is shown:
> This plugin is identified as malicious. If you still insist to install the plugin, please continue by uploading the plugin again from WP Admin.

![otgs-plugin-malicious-error](https://user-images.githubusercontent.com/12064241/161253273-fc0ecf3c-0de9-4842-8a29-cb1473e51ff3.png)

### Steps to reproduce

1. Go to https://wordpress.com/plugins/upload/
2. Grab the `otgs-installer-plugin.3.0.1.zip` plugin file from scHVmr-wpml-p2#comment-135
3. Upload on the first link and receive the above error. 

### What you expected to happen

The plugin to be uploaded without issues. 

### What actually happened

The below error is shown: 
> This plugin is identified as malicious. If you still insist to install the plugin, please continue by uploading the plugin again from WP Admin.

### Context

More context can be found in Slack: p1648810362158449-slack-dotcom-marketplace

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

NA

### Browser, operating system and other notes

NA

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Upload the plugin via `/wp-admin/plugin-install.php?tab=upload `URL

**Comment by JoshuaGoode** [comment]
The uploader checks Scan for signatures so this seems to be something we need our Scan & Security friends to review with us.  Seems it might be hitting a false positive. 

p1650475862250939-slack-CEYCDRUL9
scHVmr-wpml-p2#comment-141

**Comment by kriskorn** [comment]
This issue has been patched by the Jetpack Security team here: r244606-wpcom
Solved.
