### ISSUE TITLE
Update a Link on the Import Content Page

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#62452]
### Quick summary

We have reorganized our docs on importing, and there's a doc link in the content importing screen on Calypso that needs a change.

### Steps to reproduce

1. Go to Tools → Import
2. Click "upload it to import content" link
3. Click "Need help exporting your content?" link

![image](https://user-images.githubusercontent.com/30727666/161214190-b78c191d-a53d-4d17-8a65-ad8d21ecdfd8.png)

### New link

Please update the link to: https://wordpress.com/support/export/

### Context

1475-gh-Automattic/en.support-docs-content

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

**Comment by mhaider97** [comment]
@donalirl Can I work on this issue?

**Comment by donalirl** [comment]
@thedevhaider Yes! This isn't something I need to give permission for. It's important that _someone_ gets it done ASAP :)

**Comment by mhaider97** [comment]
@donalirl Sure, I have attached the PR. As I am a first-time contributor, I need some approvals to run the workflows. Could you please guide me for the same?

**Comment by tyxla** [comment]
> @donalirl Sure, I have attached the PR. As I am a first-time contributor, I need some approvals to run the workflows. Could you please guide me for the same?

I'm on it @thedevhaider. Thanks for your contribution 🙌

**Comment by mhaider97** [comment]
Thanks, @tyxla, and @donalirl ❤️

**Comment by donalirl** [comment]
Re-opening, as the modal still shows the old doc:

![image](https://user-images.githubusercontent.com/30727666/161671163-9c137933-dae4-4df4-9391-171a7f4ac711.png)

When you click Visit Article in the modal, the link goes to the correct doc. But the modal that appears first still shows the old content.

To make sure this wasn't cached, I checked in another account that hadn't opened that link before.

**Comment by tyxla** [comment]
Oh, you're right. We didn't update the article ID, let me file a quick fix for that.

**Comment by tyxla** [comment]
Fixed in #62509. Let me know if there are any other troubles.

**Comment by mhaider97** [comment]
Ah! Missed it. Just saw the thread. Thanks, @tyxla for the quick fix ❤️

**Comment by tyxla** [comment]
Missed it myself too the first time 🤦 Thanks again @thedevhaider for contributing to Calypso 🙌
