### ISSUE TITLE
Zoologist: Navigation block hidden by controls

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#62460]
### Quick summary

When adding a navigation block, the item in the block are hidden by the block pop-up overlay controls

### Steps to reproduce

* Set site as Zoologist
* Go home page->edit template (set as head and footer only)->Add a Navigation block or use existing and try to add an item
* The result is this - 
<img width="797" alt="Markup 2022-04-01 at 12 24 27" src="https://user-images.githubusercontent.com/13706336/161255161-289765a1-2eef-485d-b725-60f404592016.png">
* Issue replicated on another test site too
<img width="1219" alt="Markup 2022-04-01 at 12 23 01" src="https://user-images.githubusercontent.com/13706336/161255225-65e431b1-3fbb-43b9-b804-86fc008b025d.png">

* Happens on home page and head and footer only template
* Prem plan
* Doesn't occur when changing theme to Skatepark

### What you expected to happen

To be able to see what I was adding into the block

### What actually happened

The buttons you add are obscured by the block pop up controls

### Context

4913089-zd

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Zoologist. It worked on Skatepark

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
Thank you for reporting this!

I wasn't able to replicate this issue anymore.
