### ISSUE TITLE
Seller Experience: User with Pro plan is prompted to upgrade

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#62468]
Going trough the `/start` flow with a Pro Plan in the seller intent prompts the user to 'Upgrade' if they want to choose the `More power` option. This shouldn't be the case because Woo is included in the Pro Plan.

What I see is:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/375980/161321176-6b5e7ad8-44e3-43ee-b64b-6dc79186d867.png">

I expected to see `Continue` instead of `Upgrade` in the "More power" option.

**Comment by pauljacobson** [comment]
This may be related to #62486
