### ISSUE TITLE
Domain-only site cannot launch free site

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#62462]
### Quick summary

Right now, if you have a domain-only connection, and try to launch a free site, it keeps redirecting to the domain's parked page, and does not add a site.

Note: It does work if you add a Pro plan and go through checkout, but not for a free site.

### Steps to reproduce

1. Start at wordpress.com/domains
2. Register a domain only, no site
3. Try to launch a free site (you may need to wait 30 minutes for the domain to resolve)

### What you expected to happen

To add a site to the domain

### What actually happened

It redirected to the parked domain, with no site added. It includes another "Start a site" button there, which also does not work

### Context

reported by a customer in 31903176-hc
reproducible by HE

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

HEs can add then remove the Pro plan in the SA, this will make the free site available.

**Comment by danielk-am** [comment]
Something similar where the user wants to transfer an existing plan to their domain-only site right now.
4914872-zen

**Comment by jordesign** [comment]
Scrubbed this and can confirm the behaviour (screencast attached). Things appear to work fine when adding the Pro plan - but *not* when trying with a free plan.

https://user-images.githubusercontent.com/1842363/161401767-e208640b-4a95-4c99-b0c6-511ec99d1d63.mov

**Comment by delputnam** [comment]
Thanks for the report.  We're (Nomado) already working on this.  We'll post an update here once this is fixed.

**Comment by jordesign** [comment]
Thanks Del!

**Comment by formosattic** [comment]
Updated the initial report with a workaround: HEs can add then remove the Pro plan in the SA, this will make the free site available.

+1 4916305-zd-woothemes

**Comment by masperber** [comment]
I ran into this bug on 35701615-hc as well. The workaround mentioned by @formosattic is no longer available now that the Starter plan has replaced the Free plan in the Pricing rundown.

Now the only available workaround is to add free or paid credits to the customer's account.

**Comment by delputnam** [comment]
Thanks for the report @masperber.  I'll add a task for us (Nomado) to update this.
