### ISSUE TITLE
Activity Log doesn't log changes to templates in FSE sites

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#62475]
### Quick summary

On FSE sites, important parts of the site are in the templates or template parts, not in the pages. If the Activity Log doesn't log changes to templates or template parts, important changes made to the site will not be accessible by users.

### Steps to reproduce

1. Open the Site Editor (Appearance ---> Editor).
2. Make a change to a template.
3. Go to Jetpack ---> Activity Log.
4. Look for the recent changes.

### What you expected to happen

To see the change in the Activity Log.

### What actually happened

No reference to the change in the Activity Log.

### Context

34990448-hc

### Simple, Atomic or both?

Simple, Atomic

**Comment by inaikem** [comment]
There are not currently any template/part revisions…but there is an open feature request for that!

- Relabelling this as a feature request.
- Closing in favour of: https://github.com/Automattic/wp-calypso/issues/57198
- Leaving a note there to echo the above sentiments.
