### ISSUE TITLE
Desktop MacOS App: error 310 when viewing Page

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#62477]
### Quick summary

When viewing Page on the Desktop App, it displays the following error message as below

![image](https://user-images.githubusercontent.com/34882260/161370624-42fa8710-07f7-49d1-8dee-a77f918eda08.png)

```
WordPress.com ran into an error! (code 310)
```

In Bugomattic, there's a similar GH issue in https://github.com/Automattic/wp-desktop/issues/759 , but I'm not able to view nor access it.

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/34882260/161370741-5255d93c-66e0-4636-9cbe-5079069c9bf6.png">

### Steps to reproduce

Visit Pages on the desktop app

### What you expected to happen

User is able to view list of pages

### What actually happened

The error message on desktop app occurs (screenshot above)

### Context

Reported in 4906246-zd-woothemes, issue appears to be user specific.

### Simple, Atomic or both?

Atomic

### Browser, operating system and other notes

App version: 7.2.0
macOS Monterey 12.1

### Reproducibility

Once

### Severity

One

**Comment by filipanoscampos** [comment]
The user came to chat to ask for updates about this.
35021637-hc.

**Comment by inaikem** [comment]
Pinged Quality Squad to see if we can track down the 404ing issue and progress this: p1650354933893929-slack-CQD1HH4MA.

Leaving the issue in the new queue while we wait for an update there.

**Comment by inaikem** [comment]
- Cleared user logged in sessions and revoked app permissions.
- Asked them to clear caches, completely remove and then reinstall the app and, if they encounter the same error, to try a totally different network connection. Ticket: 4906246-zd-woothemes

Await feedback.

**Comment by jordesign** [comment]
User's problem ended up getting resolved - so closing this issue.
