### ISSUE TITLE
Reader Search: Clicking "Search" in Sidebar Makes Results Disappear

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#6248]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/read/search
2. Enter a search term
3. Get some results
4. Click on "Search" in sidebar

#### What I expected

Scroll to top of page with results still in place.

#### What happened instead

Results disappeared.

#### Browser / OS version

Apple OSX Safari, latest versions of all

**Comment by baumant** [comment]
I also noticed that once you click search while on the search page, it leaves your search in the bar but hitting enter does nothing you have to erase the term, re-write it, and hit enter again

**Comment by gibrown** [comment]
@fraying is this all cleaned up now. I also added #6796 which is kinda related
