### ISSUE TITLE
User asked to Upgrade again when using Import Everything from self-hosted WordPress site on Pro plan

### ISSUE THREAD

**Issue by sguzovskaia** [Automattic/wp-calypso#62486]
### Quick summary

User created the new site life11mumbai.wordpress.com and upgraded it to Pro plan. When trying to Import Everything from their self-hosted WordPress site, the user is asked to Upgrade again and is taken to the checkout page to purchase a Business plan.

### Steps to reproduce

1. Go to Tools → [Import](https://wordpress.com/import/). Under “I want to import content from:” select WordPress.
2. Enter the public site address for the self-hosted WordPress site. In the user's case, it's https://life11.org/
3. After clicking on Continue, the option to Import Everything is selected by default which means that all criteria are met to use the Everything option. However, the **Upgrade** notice is visible near Everything:
![Markup on 2022-04-04 at 12:52:57](https://user-images.githubusercontent.com/47414943/161543528-834e6c2f-9482-4574-b72d-0d8a36a296b9.png)

4. After clicking on Continue, you’ll see the message about what will happen next and the warning that a Pro plan is required to import everything:
<img width="916" alt="Markup 2022-04-04 at 14 30 16" src="https://user-images.githubusercontent.com/47414943/161544515-341f65df-fcc9-489b-aab1-133463b63a18.png">

5. Clicking on **Import Everything** and **Import and overwrite** to start the import process is taking you to the page with **A Pro plan is required to import everything**:
![Markup on 2022-04-04 at 14:36:54](https://user-images.githubusercontent.com/47414943/161545093-54b31e44-16d6-4ff5-a2de-b9bb5cd7b34e.png)

### What you expected to happen

I expected the import process to start after clicking **Import Everything** and then **Import and overwrite**, not to be asked to upgrade to the Pro plan again.

### What actually happened

Clicking on **Upgrade and import** takes you to the checkout page where you're prompted to purchase a Business plan:
![Markup on 2022-04-04 at 14:39:43](https://user-images.githubusercontent.com/47414943/161545488-f6ff670b-9891-4b8c-ab39-868743f09f59.png)

### Context

Customer report hc-365758

### Simple/Atomic

Simple

### Other notes

The site is not yet Atomic as the business features were not activated yet. I suspect this might be the issue.
I'll ask the user to activate the hosting access to see if it helps. 

### Reproducibility

Consistent

### Severity

All

**Comment by sguzovskaia** [comment]
Followed up with the user in zen-4919742 and asked them to activate the hosting access to see if it helps.

**Comment by pauljacobson** [comment]
I have another instance of this issue here: #62488 with additional screenshots, and a suggested workaround.

**Comment by ClassicRKR27** [comment]
> Followed up with the user in zen-4919742 and asked them to activate the hosting access to see if it helps.

I played into 4919742-zd-woothemes - site is now AT but is still not allowing for the transfer without prompting for the upgrade. I tried disconnecting/reconnecting Jetpack but this didn't resolve the issue.

**Comment by syds87** [comment]
I have a similar case reported in 4920605-zd-woothemes - the site is AT, but it's asking to upgrade to Pro when trying to import.

**Comment by nagpai** [comment]
Workaround for now is to add Business Plan, in addition to the Pro plan on the site (maybe for a 5 day validity). The import works after that. 

4922680-zd

**Comment by JoshuaGoode** [comment]
Added internal report: 

* pdgrnI-Be-p2 
* p1649169219267069-slack-C031TFM2NKC

Video:

https://user-images.githubusercontent.com/4887830/161775267-35b5a27f-d06f-4279-9e84-ef996c4a01e2.mp4

**Comment by JoshuaGoode** [comment]
Resolved by the following

https://github.com/Automattic/wp-calypso/pull/62524
https://github.com/Automattic/wp-calypso/pull/62529
