### ISSUE TITLE
504 errors on images in Media Library for AT sites when Photon/CDN is active

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#62481]
### Quick summary

Multiple reports of users who can't upload images in Editor/Calypso. When checking the media library the images show up as blank grey boxes. Appears there are 504/timeout errors when requesting the images.
![Uploading Screen Shot 2022-04-04 at 10.31.30 am.png…]()

### Steps to reproduce

For affected sites - check the Media Library

### What you expected to happen

All thumbnails should appear

### What actually happened

Grey boxes appear - thumbnails do not load.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

It seems this can be mitigated by turning off photon/CDN in the Jetpack settings.

**Comment by jordesign** [comment]
Also noting that we can't recreate this consistently - maybe one of the photon/CDN servers is down regionally?

**Comment by khristiansnyder** [comment]
I started to see this in chat around 23 UTC, April 2nd. 

Users reported issues after trying to upload images, showing a broken link. Example:
![Markup on 2022-04-03 at 17:38:52](https://user-images.githubusercontent.com/41035049/161456522-f4560a37-9233-4dbe-80e2-151ae8c8ee25.png)

Starting to see some tickets with the issue being reported on simple sites as well, but I cannot replicate this at all on my end. The fix has been to turn off Image CDN. 

#35034824-hc 
#32674230-hc

**Comment by jordesign** [comment]
Some other interactions:
#4918897-zen
#4918859-zen
#4918834-zen

**Comment by donalirl** [comment]
#34079307-hc
#35034892-hc

**Comment by Greatdane** [comment]
35035340-hc

**Comment by jordesign** [comment]
4918935-zd-woothemes
4918957-zd-woothemes
4918967-zd-woothemes
4918859-zd-woothemes

**Comment by flameslash** [comment]
4919008-zd-woothemes
4919035-zd-woothemes

**Comment by donalirl** [comment]
#35035552-hc
#33467613-hc

**Comment by flameslash** [comment]
32128731-hc
35035814-hc

**Comment by inaikem** [comment]
#29700712-hc
#35035702-hc

**Comment by Greatdane** [comment]
4918791-zd-woothemes

**Comment by danielk-am** [comment]
35035532-hc
35024418-hc
35035831-hc

**Comment by mdtanjid0** [comment]
35035483-hc
4919007-zen

**Comment by Greatdane** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by dolgelukkig** [comment]
36292139-hc
Setting the site to public and turning off CDN Jetpack settings solved the issue. Images disappeared again after setting the site back to private. Site is now public with a maintenance plugin protecting it from being viewed.
