### ISSUE TITLE
Layout Grid Tablet and Mobile Breakpoint Buttons Not Working

### ISSUE THREAD

**Issue by jorpdesigns** [Automattic/wp-calypso#62485]
### Quick summary

When using the Layout Grid block, the buttons used to switch to the Tablet and Mobile breakpoints do not work.

The buttons are referenced in the guide here: https://wordpress.com/support/wordpress-editor/blocks/layout-grid-block/#resizing-the-grid

### Steps to reproduce

1. Create a new page or edit an existing one. Based on previous tests, the theme or site plan is irrelevant.
2. Add the Layout Grid block.
3. Attempt to switch to either the Tablet or Mobile breakpoint by clicking the appropriate button.

### What you expected to happen

The Layout Grid block should resize based on the selected breakpoint.

### What actually happened

Clicking either button does nothing visibly.

### Context

Reported in 4886034-zd

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Use the Preview link in the top right corner (next to the Publish / Update button) to switch to tablet and mobile views.

**Comment by inaikem** [comment]
I was able to replicate the issue on my AT site. Per [our support doc](https://wordpress.com/support/wordpress-editor/blocks/layout-grid-block/#:~:text=Using%20the%20block%20settings%20sidebar%20you%20can%20switch%20between%20desktop%2C%20tablet%2C%20and%20mobile%20breakpoints%20by%20clicking%20the%20appropriate%20buttons.), "Using the block settings sidebar you can switch between desktop, tablet, and mobile breakpoints by clicking the appropriate buttons."

This does not happen. Desktop breakpoints are selected by default. It is only possible to view and edit Tablet and Mobile breakpoints by first selecting "Preview", then selecting the device type from the drop down.

This video shows the behaviour in action

https://user-images.githubusercontent.com/66711744/163966313-51857824-961a-4bd0-a46a-1effbe65abf7.mp4

**Comment by Addison-Stavlo** [comment]
Noting this works as expected in the FSE / Site Editor. However seems to be broken in the post/page editor.

**Comment by jeyip** [comment]
Logic that handles the click event ( [link 1](https://github.com/Automattic/block-experiments/blob/3aaa592d0d83da7dc3180a757e9d71b17e7c8b72/blocks/layout-grid/src/grid/edit.js#L447-L451) & [link 2](https://github.com/Automattic/block-experiments/blob/3aaa592d0d83da7dc3180a757e9d71b17e7c8b72/blocks/layout-grid/src/grid/edit.js#L210-L217) )
