### ISSUE TITLE
Marketplace: Add search by category

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62494]
Implement a category drop-down search tool for the Marketplace.

Acceptance criteria:
- [ ] There's a category drop-down on search pages that allows you to change from searching in "All Categories" to a specific category. Then the search results only load plugins with that category tag.

Screenshot:
<img width="955" alt="Screen Shot 2022-04-05 at 4 29 51 PM" src="https://user-images.githubusercontent.com/1689238/161843691-ff0298ed-1d32-47d0-be40-c0ed15140ef9.png">

**Comment by lupus2k** [comment]
Waiting for review on [this](D78826-code) to close this issue

**Comment by lupus2k** [comment]
This issue only refers to the backend search, the calypso search is already updated in #62685

**Comment by lsl** [comment]
Should we wait for the outcome of pdh6GB-Ax-p2 before attempting this one?

**Comment by cpapazoglou** [comment]
@vinimotaa are we still pursuing this?

**Comment by vinimotaa** [comment]
@cpapazoglou not at all!
