### ISSUE TITLE
Marketplace: Add loading spinner to search input

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62496]
Acceptance Criteria:
- [ ] There is a loading spinner that appears in the search field when a popular search term is clicked or enter is pressed. The spinner replaces the search icon.
<img width="532" alt="Screen Shot 2022-04-05 at 4 34 58 PM" src="https://user-images.githubusercontent.com/1689238/161844457-5893a6eb-f481-441a-8f34-9ffee4ce9ac6.png">

Let's see if we can re-use a spinner component.

**Comment by lupus2k** [comment]
What do you think if we add this spinner not just when clicking popular search but when searching anything and hit enter (or click search)

**Comment by allilevine** [comment]
> What do you think if we add this spinner not just when clicking popular search but when searching anything and hit enter (or click search)

@lupus2k Did we make a decision about that in planning? If not, can we check with @vinimotaa ?

**Comment by allilevine** [comment]
> > What do you think if we add this spinner not just when clicking popular search but when searching anything and hit enter (or click search)
> 
> @lupus2k Did we make a decision about that in planning? If not, can we check with @vinimotaa ?

We decided in SOTB to show the spinner for all searches, with review by @vinimotaa

**Comment by allilevine** [comment]
If we can't add this to all Calypso search inputs, let's use a prop to only show it on /plugins.

**Comment by Rolilink** [comment]
> If we can't add this to all Calypso search inputs, let's use a prop to only show it on /plugins.

@allilevine @lsl actually the `<Spinner/>` component is already in the `Search` one, I just needed to pass the `searching` prop to enable it.
