### ISSUE TITLE
Marketplace: Change /plugins navigation sections

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62495]
New landing page sections (also new search categories, except Discover):

**Discover** - this is the landing page.
**Top free plugins** - this is a page where we'll display the Free Plugins by active installs data.
**Top premium plugins** - Premium plugins by active installs data.
**Editor's pick** - Handpicked.
**All categories** - Everything we have.

Hardcoded like current /plugins categories.
Categories post: pdh6GB-Cq-p2

Acceptance Criteria:
- [x] The plugin sections have been updated.
- [x] Each section links to a page to see more plugins in that category.

**Comment by allilevine** [comment]
@vinimotaa to determine editor's pick plugins.

**Comment by vinimotaa** [comment]
[Started a conversation here!](https://a8c.slack.com/archives/C029JEQRVRT/p1649718103638669)

**Comment by allilevine** [comment]
> [Started a conversation here!](p1649718103638669-slack-C029JEQRVRT)

We're going with the current "Featured" section.
We can also use the premium/popular categories we already have backend code for.

**Comment by allilevine** [comment]
After discussing with @paulopmt1 we're going with these sections (renamed):

- Top Premium Plugins
- Editor’s Pick
- Top Free plugins

**Comment by paulopmt1** [comment]
[Fixed here](https://github.com/Automattic/wp-calypso/pull/62873/files#diff-6750c272a1df0c496a26adc7ae59a20a6f9a7f1ca37f751b869ee40714e355f6R89) by @lsl, closing it.
