### ISSUE TITLE
Marketplace: Research how we'll use plugin tags as categories

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62497]
To support https://github.com/Automattic/wp-calypso/issues/62264 and https://github.com/Automattic/wp-calypso/issues/62494 pre Woo integration we'll need to use tags as categories in the Marketplace. 

We can likely use WooCommerce.com search api's or see if `wp_query` is an option.

Acceptance criteria:
- [ ] p2 a plan to use plugin tags, with implementation details -- for example, what new endpoints are needed if any

**Comment by lsl** [comment]
Fair bit of discussion in this p2, this comment kind of sums up where we're at: pdh6GB-Cq-p2#comment-1230

@lupus2k if you're taking this one on it would be good to get a p2 post up defining what your planning to add to the marketplace endpoints (either by modifying what's there or adding a new endpoint) - once that's defined we can start working on it on the calypso side.

**Comment by lupus2k** [comment]
Research post here: pb5gDS-1In-p2

**Comment by lupus2k** [comment]
@Rolilink make some tests and the search from `dotorg` is searching using `OR` instead of `AND`. (p1649887054533639/1649886884.089389-slack-C029JEQRVRT)

I confirm this and to make it search using `AND` we have to make some changes on `dotorg`.

**Comment by allilevine** [comment]
Closed by pb5gDS-1In-p2
Search follow-up to be addressed in https://github.com/Automattic/wp-calypso/issues/62494
