### ISSUE TITLE
Marketplace: Indicate that popular search term has been clicked 

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62490]
When a popular search term is clicked and we land on the results page, that search term word should no longer be a link. It should be unclickable with no underline. From pdh6GB-AJ-p2#comment-1158

<img width="646" alt="Screen Shot 2022-04-04 at 9 35 52 AM" src="https://user-images.githubusercontent.com/1689238/161556086-b03cb4d8-1b42-43ba-a4bc-e826e4b97a2c.png">

Acceptance criteria:
- [x] The search term that results are displayed for is no longer clickable.
- [x] The search term becomes clickable again after any change to the search field, or clicking on another search term.

**Comment by lupus2k** [comment]
What do you think about making the selected one **bold**?

Like this (bolded): 
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/402286/161634130-5ffc6401-fc3d-4ab1-b1ab-43cf0c3be025.png">

Or this:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/402286/161634637-fec1a72e-50d1-4ece-bff0-48f07523fc9d.png">

**Comment by allilevine** [comment]
> What do you think about making the selected one **bold**?

@lupus2k I'd lean towards not bolding in case it shifts the other terms over. Do you have a branch where we can see it in action?
