### ISSUE TITLE
Marketplace: remove spaces between commas from popular search terms

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62539]
The spacing between commas was in the original design, but @vinimotaa has approved removing them.

**Comment by lsl** [comment]
From @vinimotaa - Lets remove the spacing. (Had a slack ping in flight while this was in draft)

**Comment by vinimotaa** [comment]
@allilevine @Rolilink 

Hey folx! What I discussed with @lsl was to remove the spacing in between the comas, but keeping the words seprate from each other:

Original design: shipping , seo , portfolio , chat , mailchimp
Oow it is: shipping,seo,portfolio,chat,mailchimp
How it should be: shipping, seo, portfolio, chat, mailchimp

I hope this makes sense! :)

**Comment by lsl** [comment]
Updated https://github.com/Automattic/wp-calypso/pull/62575
