### ISSUE TITLE
Marketplace: Remove hyperlink from search button

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62540]
The search icon in the Marketplace search header should not be a link or button. Requested by design.

We don't want to change the Search component to make this change, so it may need to be a CSS solution.

**Comment by lsl** [comment]
@vinimotaa Is this about the blue line box shadow or the mouse cursor / clickability? both?

![Screenshot 2022-04-06 at 13-42-00 Plugins ‹ Site Title — WordPress com](https://user-images.githubusercontent.com/811776/161891439-cdc66bc9-20fd-40a3-ab26-54c98d5ad31b.png)

**Comment by lsl** [comment]
Potential fix in #62547 but I'm not sure if it's suitable as the button is still there / interactive.

Test with [calypso.live](https://calypso.live/?image=registry.a8c.com/calypso/app:commit-89ad88f6764392703f0725c6722e8186f0e63dd2).
