### ISSUE TITLE
Marketplace: Clicking on search results doesn't navigate into search results

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62541]
When searching and then clicking on a plugin, then clicking on “Search Results” on the header navigation breadcrumb it doesn’t instantly navigate back to the search results page. You have to click it twice.

**Comment by lsl** [comment]
Found while testing: When you click the plugins in the header link the search term isn't cleared. Could be related or at least fix adjacent.

**Comment by lupus2k** [comment]
Re-open

**Comment by lsl** [comment]
Not related to debouncing like I thought. Might be something in the header component.

**Comment by lsl** [comment]
Probably good enough for now fix in https://github.com/Automattic/wp-calypso/pull/62583
