### ISSUE TITLE
Signup: entering signup from wordpress.com/create as premium or business should show domains is included, not extra upgrades

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#6255]
cc: @meremagee @bisko 
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/create
2. Choose "Start with Premium" or "Start with Business"
3. Continue through to domains step 
4. Enter a domain name you would like to register
#### What happened

The buttons against paid domains show "Upgrade" and the text shows "Included in WordPress.com Premium", but since the user has already selected premium/business on the /create page, this doesn't really make sense - especially if the user selected business previously where the domain is already included. If the user does select a domain via business, the cart still shows business rather than premium
#### What I expected

Show 'Select' text on the buttons next to each paid domain, and the text to show "This is included in the plan you have selected."
#### Screenshot / Video

https://cloudup.com/cmnowMQB4xx
#### Context / Source

 #dogfooding, #manual-testing, #automated-testing

**Comment by lancewillett** [comment]
I was able to repeat this.

![screen shot 2016-10-14 at 12 26 05](https://cloud.githubusercontent.com/assets/66797/19400088/62fbd8e0-9209-11e6-8aad-945213a1d5a0.png)

All these blue "Upgrade" buttons should say "Select" instead. CC @meremagee

**Comment by alisterscott** [comment]
This has been fixed by changes since:

<img width="984" alt="screen shot 2017-07-18 at 12 29 10 pm" src="https://user-images.githubusercontent.com/128826/28298102-c07a5c8c-6bb4-11e7-9141-a54ed15ef4de.png">
