### ISSUE TITLE
Checking out with multiple product only installs one of them

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#62558]
The checkout page lets users exit it while keeping some items in the cart. Using this method, one can check out with multiple marketplace subscriptions. However, only the first plugin on the checkout page will get installed.

This is confusing, especially as the checkout page will get the redirect URL from the last checkout attempt. The Thank You page will show an endlessly loading button, as the installation of the other plugins will never be started in the background.

### Steps to reproduce:

- check out with plugin A
- leave the checkout page by clicking the X button in the top-left corner, and select `Leave items` on the dialog
- check out with plugin B, complete the checkout
  ![image](https://user-images.githubusercontent.com/11555574/161982660-04295ad9-0fac-4ba9-8c45-ede90267b164.png)
- verify that the thank you page has the redirect url to plugin A, and that the `Manage plugin` button won't finish loading
  ![image](https://user-images.githubusercontent.com/11555574/161982683-9a7b6197-39f1-4cd4-bf3a-51fd03590e4a.png)
- visit `/wp-admin/plugins.php`
- verify that only plugin B is installed
  ![image](https://user-images.githubusercontent.com/11555574/161982923-906cba51-5e0f-449a-8a29-678b987dfe8c.png)

Is this a use case that we should handle? As an alternative, should the cart always be emptied when navigating to the checkout page form a marketplace product page, and then trying to leave?

**Comment by cpapazoglou** [comment]
@vinimotaa , @SaxonF how would this page look like for multiple purchases?

**Comment by cpapazoglou** [comment]
Let's resolve as high priority why plugins are not getting installed. Since paid plugins installation depends on subscription activation it shouldn't be an issue here.

**Comment by WBerredo** [comment]
I was not able to replicate the bug per see, as all the plugins are being installed after the purchase (there was some discussion here: p1651057225961259-slack-C029JEQRVRT).

We are still facing the issue where we only display the last selected plugin on the thank you page. This will be tracked on this new issue #63151 with an accordingly priority.
