### ISSUE TITLE
Refactor EditorGroundControl not to take user and userUtils as properties

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#6256]
Refactor `EditorGroundControl` so that we no longer take `user` and `userUtils` as properties. Ideally we'd use the references in the redux tree, and also move the `needsVerificationForSite` method into `client/state/current-user/selectors.js`.

**Comment by lsinger** [comment]
From @coreh: 

> we're passing a model to this component directly instead of grabbing it from redux; but user is not reduxified, so it would still be a hack

If I understand this correctly, the benefit here is that it would be a small step on the reduxification of everything, so leaving this open for now with the above gotcha.

**Comment by alisterscott** [comment]
Is this still to be done, or was it covered by #6230?

**Comment by lsinger** [comment]
Fixed by @jsnajdr in #22734. Props! 🎉
