### ISSUE TITLE
Marketplace: Include Documentation Throughout Purchase Flow

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#62578]
### What

When purchasing a plugin in the marketplace, we could better highlight documentation for each plugin in the following places:

### Plugin Page in Calypso
Examples:
https://wordpress.com/plugins/woocommerce-product-vendors/
https://wordpress.com/plugins/woocommerce-pre-orders/
https://wordpress.com/plugins/wordpress-seo-premium/
https://wordpress.com/plugins/woothemes-sensei

A logical spot for this would be in the support section:
![Annotation on 2022-04-07 at 11-46-44](https://user-images.githubusercontent.com/30727666/162103833-a40bbb51-3bba-4dc9-94e6-06a1e12d2d0b.png)

Suggested copy:

'View documentation' that links to that specific plugin's docs.

### Purchase Confirmation Screen

Example: https://wordpress.com/marketplace/thank-you/woocommerce-product-vendors

We could include the documentation link for the purchased plugin as the first item in 'What's Next':
![Screenshot on 2022-04-07 at 11_48_02](https://user-images.githubusercontent.com/30727666/162103974-c0cf3860-b3d5-405b-b23a-c067a614095c.png)

Suggested copy:

**Documentation**
Visit the step-by-step guide to learn how to use this plugin.
Button text: Visit Guide

Also on the thank you screen, there is a link for `View support documentation`:
![image](https://user-images.githubusercontent.com/30727666/162104383-1930811e-c91a-4c7b-9fb3-f4a8a709556b.png)

However, this just links to https://wordpress.com/support/ which will not contain any information on how to use the plugin they just purchased. I propose this link is replaced with a link to the docs for the specific plugin they just purchased, or updated to include both like this:

[View plugin documentation](https://woocommerce.com/document/product-vendors/) | [View WordPress.com support guides](https://wordpress.com/support/)

### Why

When a user first installs a marketplace plugin, they are left to figure out for themselves how to use it. This can lead to confusion, or even to abandoning the plugin and refunding their purchase, costing us revenue. 

Alternatively, they may contact us to learn how to use it which increases the burden on support. 

We can increase a user's chance of succeeding with their new purchase by better highlighting the docs throughout the purchase flow.

### How

Every plugin currently in marketplace has documentation. This could be integrated for all existing plugins as well as plugins added in the future.

**Comment by simison** [comment]
@ianstewart @cpapazoglou this seems like a good small improvement for the Marketplace teams.

**Comment by cpapazoglou** [comment]
Thanks for reporting, actually we do have added documentation links in the past but they don't appear now. Seems like a regression
![image](https://user-images.githubusercontent.com/12430020/165088990-05adb74e-4d39-4fa9-8585-b1177a4d51d1.png)

- [x] Find out what is causing the regression and fix it - #63025
- [x] Add documentation copy & links in thank you page - #63051
