### ISSUE TITLE
List View: Blocks disappear when too many are shown

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#62571]
### Quick summary

It seems that a recent change has made the List View pane open with all parent blocks "collapsed" by default. If you expand the hierarchy and the pane "fills up" (i.e. there are as many blocks showing as can be seen without scrolling), blocks lower down on the page disappear from the List View.

### Steps to reproduce

1. Navigate to any editor which supports the List View (Gutenberg/block editor, site editor, template editor)
2. Open the List View pane
3. Add many blocks to the page. Ideally, add nested blocks so you can expand/collapse the hierarchy in the List View pane.
4. Expand/collapse the hierarchy once the view is "full"

### What you expected to happen

All blocks on the page should display, with the option to scroll down when the list is too long.

### What actually happened

The scrollbar is available, but some blocks disappear if the list becomes too long.

Example:

https://user-images.githubusercontent.com/5630717/162026188-60865361-b67d-436e-b94d-ebcc7fc215b3.mp4

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Any block that has disappeared will display again if other blocks above it are "collapsed" to create more space in the list.

**Comment by kerrynicl** [comment]
Hi @jp-imagines  I've not been able to replicate this on any of my test sites. Would you mind sharing yours to investigate further?

**Comment by Greatdane** [comment]
There looks to be something weird happening yea, but it is hard to reproduce, and moving up and down the list view (or closing some nested blocks) looks to bring back the 'missing' blocks'.

I managed to catch the footer disappearing on this video;

https://user-images.githubusercontent.com/5075840/162356738-0ee56ff4-5fd4-44e1-9f23-b5c6f1e1f0a1.mp4

**Comment by Greatdane** [comment]
I have now been able to reproduce on self-hosted as well. Moved this to Gutenberg core; https://github.com/WordPress/gutenberg/issues/40173

**Comment by jp-imagines** [comment]
Forgot to circle back here to note that I chatted with @kerrynicl about this yesterday. I was able to reproduce it again (along with another teammate) on Firefox and Chrome. I posted another video (outside the Site Editor) in WordPress/gutenberg#40173 

Thanks @Greatdane!

**Comment by masperber** [comment]
I found an instance of this issue here: 35159666-hc

I starred a link to the page where the issue is present.

**Comment by daledupreez** [comment]
It looks like the Gutenberg issue has been closed as of [this comment](https://github.com/WordPress/gutenberg/issues/40173#issuecomment-1257729482), with a possible fix being included in Gutenberg 14.1.1. I am not seeing the issue repeated, but would love confirmation from someone who had a reliable reproduction.

**Comment by annezazu** [comment]
Closing this out as I can't replicate and, two years on, haven't seen further reports.
