### ISSUE TITLE
Reduce brittleness in managed plugin handling

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#62577]
While trying to get Sensei Pro in the list of managed plugins we uncovered a lot of complexity in the process p9o2xV-1Wj-p2#comment-5781

For the future I think we need to lay out some really clear rules about what constitutes a github release that atomic will accept and any plugin that wishes to be in the marketplace must follow those rules even if it means they have to create a new mirrored repo for this purpose.

If that isn't feasible we may need to move atomic away from querying  github releases directly and instead either revert back to using woocommerce release files or hitting a new public-api endpoint for release information. This way we can come up with whatever rules necessary to accommodate different plugin release conventions.

**Comment by cpapazoglou** [comment]
> For the future I think we need to lay out some really clear rules about what constitutes a github release that atomic will accept and any plugin that wishes to be in the marketplace must follow those rules even if it means they have to create a new mirrored repo for this purpose.

We already have clear rules (p9o2xV-1A4-p2#comment-4954). 

Vendors should provide us with GH repo and share an access token for accessing it (reading it). We find the latest release, using the version number of that release. These need to use version numbered releases, and the zips be packaged just like a dotorg repo plugin or theme zip.
