### ISSUE TITLE
Retrieve feature checks for all sites in a single request

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#62599]
Currently to retrieve the feature checks we have to do one request per site: https://public-api.wordpress.com/rest/v1.1/sites/{site_id}/features

We want to retrieve the feature checks for all sites of a user in a single request.

For more context: https://github.com/Automattic/wp-calypso/pull/62472

**Comment by cpapazoglou** [comment]
@WBerredo does this still stand after merging https://github.com/Automattic/wp-calypso/issues/62912?

**Comment by WBerredo** [comment]
After merging #63161, we shouldn't be facing this scenario.

Closing this issue.
