### ISSUE TITLE
Marketplace: Trigger Yoast Premium license provision on plugin installation

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#62592]
In order to get a license from the Yoast API, the async job `wpcom_job_marketplace_provision_yoast_plan_for_blog` needs to be called after the Yoast Premium plugin is activated/installed. Currently, the async job `wpj_wpcom_marketplace_atomic_site_provisioned` is added from the async job `wpcom-marketplace.php` but is not called from anywhere in the code.

**Comment by cpapazoglou** [comment]
Let's also cleanup the code from other instances calling `WPCOM_Marketplace_Yoast_Premium_Plan_Manager`

**Comment by JulianBustamante** [comment]
Diff created D80127-code

**Comment by cpapazoglou** [comment]
Can this be merged now?

**Comment by JulianBustamante** [comment]
Deployed r245724-wpcom
