### ISSUE TITLE
Full importer: Upgrade plan: change wording from `See plans` to `See plan`

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#62600]
We have recently changed our plan list to have only the Pro plan.
<img width="755" alt="Screenshot 2022-04-07 at 17 17 21" src="https://user-images.githubusercontent.com/1241413/162421696-5db7648c-0ae5-4056-a64c-bbb06d07d000.png">

**Comment by vishnugopal** [comment]
cc @saygunnyc What should be the new text here?

**Comment by saygunnyc** [comment]
"Music Page | WordPress Pro"
Is that what you asked for?

**Comment by bogiii** [comment]
@saygunnyc, we are talking about the button text. Currently, the button says 'See plans' (see screenshot above), but we only have one plan.

The question is, should we change to 'See plan', 'View plan details', or something else?

**Comment by saygunnyc** [comment]
Thank you for clarifying @bogiii! 
I think we're not changing the name of the plans page, and soon we will have add ons with plans. I think it's fine to keep it as is. "See Plans"

<img width="1192" alt="Screen Shot 2022-04-11 at 5 14 27 PM" src="https://user-images.githubusercontent.com/78876323/162834600-1c7dcd75-c801-4b69-bb09-4c8e053bdf91.png">
