### ISSUE TITLE
Add Site Vertical to Blog Report Card

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#62613]
Per this suggestion from @nerdysandy 

<img width="733" alt="image" src="https://user-images.githubusercontent.com/5665959/162352144-d9c5c9f6-50d3-45cd-af7b-0aeb4dd3809f.png">

NOTE: If we make this a new dev issue we need to add some nice guiding instructions on how to start, e.g. where Blog Report Card code lives, how site preferences work, etc.

## Acceptance Criteria
- [x] Blog Report card shows a field with the site vertical (pulled from the site perferences)
- [ ] Maybe: allow the field to be editable by HEs - need discussion on this .  Maybe can only be editible for sites that do not have a vertical value

**Comment by autumnfjeld** [comment]
A related comment from James Weber (don't know his github handle)
We should think about what else could be helpful in the Blog RC for the future (revisit this idea in 2022 Q3 or Q4):

<img width="780" alt="image" src="https://user-images.githubusercontent.com/5665959/165202157-fc396dcf-0366-4390-a315-b5ed1fc39287.png">

**Comment by arthur791004** [comment]
> Maybe: allow the field to be editable by HEs - need discussion on this . Maybe can only be editible for sites that do not have a vertical value

As this one might need a discussion, I create another issue for it. See https://github.com/Automattic/wp-calypso/issues/64436

**Comment by arthur791004** [comment]
Close it as D82183-code is shipped and we can see the site vertical on the Blog Report Card.
