### ISSUE TITLE
[Bug]: Medium exported images are not imported

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#62622]
Medium export sometimes embeds some corrupted images files in the resulting `.zip` file. Confirmed that the images’ URLs are indeed corrupted in the exported .zip file.

See: `https://cdn-images-1.medium.com/fit/t/NaN/NaN/1*B4gAUyyY_0KhqRXPlJw8EQ.jpeg`

`/fit/t/NaN/NaN` is a "command" like `desat/multiply/red/60` that you can pass to the Medium CDN in order to generate thumbnails. That "command" resizes the image.

Removing that string generates a valid URL: `https://cdn-images-1.medium.com/1*B4gAUyyY_0KhqRXPlJw8EQ.jpeg`

As well if you put valid numbers: `https://cdn-images-1.medium.com/fit/t/256/256/1*B4gAUyyY_0KhqRXPlJw8EQ.jpeg`

NaN is “not a number” which means that Medium tried to export something that has no dimensions. On [source article](https://href.li/?https://medium.com/p/9aa71e2673fc), that image is not displayed. Maybe there was an image in the past that has been removed (or something like that).

Maybe every time we find an URL with the string `fit/t/NaN/NaN/`, we can remove that "command". We will embed (and import) a full-size image, but IMHO is better than not embedding an image. After a Medium site is removed, all the images are lost.

See: pdtkmj-4U-p2#comment-153

### Steps to reproduce

1. Get the Medium exported file found here: pdtkmj-4U-p2#comment-149
2. Import it
3. Open `/2014/03/10/behind-every-snap-theres-a-story/` on exported site
4. Inside that article you will find 2 images:
    1. Have not been imported
    2. Do indeed point to a Medium CDN image that is not valid

### What you expected to happen

That all the images are imported.

### What actually happened

All images with corrupted URLs are not imported

**Comment by vishnugopal** [comment]
Duplicate of https://github.com/Automattic/wp-calypso/issues/62845
