### ISSUE TITLE
Marketplace: Improve feedback screen after installing a plugin

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#62634]
### Details

When we install a new plugin, the installation page redirects us to the "thank you" page, with the message "All ready to go!". This page is with the button `Manage plugin` on the loading state, and it finishes it after a few seconds (usually about 10 seconds).

## The problem 1

After installing [a paid plugin](https://wordpress.com/plugins/paid), we aren't in the "All ready to go" stage. We are on the "Installing your plugin state", but the screen shows the opposite. 

**To reproduce**: Just install [a paid plugin](https://wordpress.com/plugins/paid).

### Current "thank you" page state with installing plugin process

![image](https://user-images.githubusercontent.com/1044309/162490987-d07c91b3-a8d1-4c7a-9d7c-bef8938fcef1.png)

### Current plugin installed state

![image](https://user-images.githubusercontent.com/1044309/162491854-3297631f-c3d3-4bea-9317-50aaacedde70.png)

## Problem 2
The installation process from a free plugin differs from the paid ones. 

### For free plugins, the experience is different

**During the installation (we don't see this for paid plugins)**:

![image](https://user-images.githubusercontent.com/1044309/162492477-bc95a05e-6928-4c03-90fd-c374aaa4e998.png)

**After the installation**:

![image](https://user-images.githubusercontent.com/1044309/162492547-2341d458-f3f4-4575-becf-f496d71f3d55.png)

## Problem 3

After installing any paid plugin, the `Manage plugin` button redirects us to [all plugins page](https://politicaemvideira.com/wp-admin/plugins.php). It would be better if it redirects the user to the specific, recently installed, plugin page.

### Checklist

- [ ] Make sure we correctly inform the plugin installing state to users
- [ ] Review why the installation screens are different from free to paid plugins. 
- [ ] After installing any plugin, the button `Manage plugin` should redirect to the recently installed plugin.

**Comment by paulopmt1** [comment]
Hey @vinimotaa. I would appreciate your view here :)

**Comment by cpapazoglou** [comment]
This has already be resolved by showing the same progress bar for paid plugins too.
