### ISSUE TITLE
New properties to add for CSS-Tidy

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#62631]
### What

With FSE and Gutenberg, there's a number of properties being used in our themes and various blocks that can't be overridden on simple sites because they're not allowed in CSS-Tidy:

* gap
* aspect-ratio
* accent-color
* text-underline-offset
* hex alpha transparency for colors
* declaring css variables (they’re used in a lot of newer themes, so being able to override them directly would be extremely helpful!)

When these are added on a simple site, after clicking the Save Changes button, the code will be removed without any warning (and only visible after refreshing the page), which can cause frustration.

![2022-04-08 12 24 46](https://user-images.githubusercontent.com/4000628/162483360-837b4bbd-329b-4f04-aad3-8f1d84325964.gif)

### Why

This will allow users and Happiness Engineers to provide more effective overrides for elements in themes or blocks

### How

p1649334591409609-slack-team-calypso

**Comment by inaikem** [comment]
@fullofcaffeine 👋 Just a quick nudge from me on this. 

I'm marking as triaged for now so we can get this prioritised!

**Comment by brookewp** [comment]
Hey @edequalsawesome, thanks for the issue! We are working on adding the new properties you've shared, but I successfully added hex codes with alpha values before making any changes. Do you have an example of where it can't be applied? 

Here is what I tested in the customizer:
<img width="1298" alt="Screen Shot 2022-04-21 at 1 11 44 PM" src="https://user-images.githubusercontent.com/35543432/164544976-2f751eda-2a37-4c7b-a325-40f245f107ee.png">
And the result on the front-end: 
<img width="1513" alt="Screen Shot 2022-04-21 at 1 13 45 PM" src="https://user-images.githubusercontent.com/35543432/164544987-2e71f82e-cb93-429b-9fe7-837396ac0982.png">

**Comment by edequalsawesome** [comment]
@brookewp Hey! It looks like it's a combo of things (and not really hex transparency at all, sorry about that!) -- the original CSS that was used was this:

```
/* Set the page background colour semi-opaquee */
#page {
    background: rgb(255 255 255 / 88%);
}
```

That value should have been `rgba(255 255 255 / 88%)`, which *does* work, so the `hex alpha transparency for colors` request can be ignored 😄

**Comment by edequalsawesome** [comment]
The pull request was merged and I was able to save these properties in the Customizer without any issue on my test simple site, so I'm going to close this 🥳 

![2022-05-13 16 07 59](https://user-images.githubusercontent.com/4000628/168385066-28745762-d182-4f61-a106-22dad3f9b234.gif)
