### ISSUE TITLE
Marketplace: Find 20-30 most commonly used plugin tags

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62638]
Acceptance criteria:
- [x] Query for `hot_tags`: http://dd32.id.au/projects/wordpressorg-plugin-information-api-docs/
- [x] P2 20-30 of the top tags.

See p1649423763879979/1649360717.118219-slack-C029JEQRVRT
We can also check https://wordpress.org/plugins/browse/popular/

**Comment by lsl** [comment]
pdh6GB-Cq-p2#comment-1202

Also, if we ever want to do this in an endpoint, there's a wrapper function in core we can probably use https://developer.wordpress.org/reference/functions/plugins_api/
