### ISSUE TITLE
Legacy plan simple site showing as free, user's actions are limited

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#62649]
### Quick summary

A user has a Premium plan on their site (4935731-zen) but the dashboard is acting like the site is a free plan. As a result, the user is unable to change themes or possibly other changes to their site. There doesn't seem to be any issues via Blog RC regarding sticker plans either.

### Steps to reproduce

1. Access the user's SA and confirm there is a paid legacy plan (Premium)
2. SU into dashboard and see that the site is not recognized as having a plan
3. Attempting to change a theme results in a message saying to contact support.

### What you expected to happen

User should see their site's plan as Premium and be able to make changes to theme or site without hinderance.

### What actually happened

Site is not recognized as Premium and won't allow user to change themes.

### Context

4935731-zen

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by kerrynicl** [comment]
Hi @kuropixel  There seems to a be JP identity Crisis in Darc for that user's domain that when fixed, resolves the plan slug issue on the site. Doesn't seems bug related so I'll be closing this for now
