### ISSUE TITLE
Marketplace: Update Partners landing page copy and form

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62641]
We need to update https://wordpress.com/partners/ to suit Marketplace needs and communication with 3rd-party plugin vendors. The code lives in WPCOM: `class-partners-page.php`

Current | Updated
------- | -------
Let’s partner to make the web a better place. | Let’s partner to build a marketplace for the WordPress.com community.
If you’ve got an idea, a product, or a business that can make the web a better place to publish and share, we’re all ears. | If you’re a WordPress plugin or theme developer, or you provide professional services for WordPress users, we’d love to hear from you.
As an open source platform, collaboration has been the bedrock of our growth, ensuring a strong community and product. We continue this model by partnering with companies, organizations, and individuals in a variety of ways. If you have technology or product features, are a marketing or publishing platform, offer a service our customers might benefit from, or simply want to discuss something else, we’d love to hear about it. | As an open source platform, collaboration has been the bedrock of our growth, ensuring a strong community and product. We continue this model by partnering with companies, organizations, and individuals that also support the open source community. If you’re a WordPress plugin or theme developer, or you provide professional services for WordPress users, we’d love to hear from you. We’ll then have your information as we expand our plans to offer paid plugins, themes and services to WordPress.com customers. [Read more about this here](https://wordpress.com/blog/2022/03/08/the-future-of-plugin-themes-and-services-purchases-on-wordpress-com/).
Please tell us more about yourself and your interest in partnering with WordPress.com. We review every single inquiry and should respond to you within a week. | Please tell us more about your plugin, themes or service offering so we can assess how we can understand more about your business. We’ll respond as we further [develop our plans in this space](https://wordpress.com/blog/2022/03/08/the-future-of-plugin-themes-and-services-purchases-on-wordpress-com/).
Please contact our [WordPress.com VIP](https://wpvip.com/?ref=partners-lp), [Jetpack](https://jetpack.com/for/hosts/?ref=partners-lp), or [WooCommerce](https://woocommerce.com/?ref=partners-lp) teams directly. To learn more about building a WordPress.com integration, visit our [Developer page](P2gHKz-1qL-p2?ref=partners-lp). To become an affiliate, please visit our [Affiliate Program](https://refer.wordpress.com/?ref=partners-lp). … and thanks! | Please contact our [WordPress.com VIP](https://wpvip.com/?ref=partners-lp), [Jetpack](https://jetpack.com/for/hosts/?ref=partners-lp), or [WooCommerce](https://woocommerce.com/?ref=partners-lp) teams directly. To learn more about building a WordPress.com integration, visit our [Developer page](P2gHKz-1qL-p2?ref=partners-lp). … and thanks!
Form fields | Replace with [this form](https://wordpress.com/blog/2022/03/08/the-future-of-plugin-themes-and-services-purchases-on-wordpress-com/)
Thank you! We'll be in touch within a week. | Thank you! We’ll be in touch as we build out our plans further.

Acceptance criteria:
- [ ] Approval from @emmnyc85 

See https://github.com/Automattic/wp-calypso/issues/61032#issuecomment-1090348179

**Comment by emmnyc85** [comment]
Thanks, @allilevine! Can we please make one minor change below? (edited copy provided below)

Let’s partner to build a marketplace for the WordPress.com community.

If this doesn't look good, we can switch back to: Let’s partner to build a marketplace for WordPress.com.

cc: @vinimotaa

**Comment by allilevine** [comment]
> Thanks, @allilevine! Can we please make one minor change below? (edited copy provided below)

@emmnyc85 Thanks, updated in the description!

**Comment by lsl** [comment]
Whoever gets to this please get a review from someone on martech before deploying. I think some of these pages need extra build/deploy steps (although that might have changed since then).

**Comment by paulopmt1** [comment]
Hey @emmnyc85, I'll appreciate your feedback on the screenshots of my changes here: D78736-code

**Comment by emmnyc85** [comment]
@paulopmt1 - Thanks for sharing. As mentioned over Slack, I'm having trouble accessing Phabricator. Will connect with you via Slack to help resolve this.
