### ISSUE TITLE
Marketplace: Spotlight Sensei Pro with a JITM

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62640]
Acceptance criteria:
- [ ] Enable the Spotlight JITM we added, with this logic: if Sensei is installed, spotlight Sensei Pro (for all site types).

Remove a11n check.

See https://github.com/Automattic/wp-calypso/issues/61492

**Comment by lupus2k** [comment]
Needs review on D79053-code

**Comment by allilevine** [comment]
We're keeping this issue open because we enabled the Spotlight JITM, but it's not disabling when Sensei Pro is installed (or when Sensei is removed).

**Comment by allilevine** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/63179

The Spotlight JITM was enabled for Sensei Pro in D79053-code
