### ISSUE TITLE
Atomic, WooCommerce: error "Nonce verification fails" when leaving a product review and Jetpack is active

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#62646]
### Quick summary

When Jetpack is connected and active, the review for the WooCommerce product fails to post. You will encounter `Nonce verification failed`.

### Steps to reproduce

1. On a WordPress.com Atomic site with WooCommerce products, try to post a review for a product.
2. You will encounter `Nonce verification failed`.
3. If you deactivate Jetpack plugin and try again, the review will get posted without any issues.

### What you expected to happen

The review should get submitted even with the Jetpack plugin active and connected.

### What actually happened

Encountered `Nonce verification failed` error when Jetpack plugin was connected.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/33957570/162555895-dbef4df3-1a75-4025-806d-fe13e8568e1d.png">

### Context

User report: 4928270-zen

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Was able to reproduce with multiple themes.

### Reproducibility

Consistent

### Severity

All

**Comment by tvolpert** [comment]
Another report here: 35102924-hc

**Comment by dragstor** [comment]
Another one: 4937885-zd

**Comment by aleone89** [comment]
Another report of this here hc-28467535

**Comment by formosattic** [comment]
I was able to reproduce this on an atomic site.

Also tested on self-hosted with WooCommerce and Jetpack connected, but it worked fine there.

**Comment by senff** [comment]
Reported in 4937001-zd.

**Comment by nixiack** [comment]
Reported in 4939044-zd as well.

**Comment by JessBoctor** [comment]
I have another report in 21950551-HC

**Comment by wpshellbelle** [comment]
Another report at 33855231-hc / 4945993-zen

**Comment by cometgrrl** [comment]
Jetpack team says they will [have a fix](https://github.com/Automattic/jetpack/pull/23944) for this soon. p1649892098202479-slack-CBG1CP4EN

**Comment by cometgrrl** [comment]
Workaround: disable this setting in https://wordpress.com/settings/discussion/

![image](https://user-images.githubusercontent.com/86427589/163296117-dbc54ea1-f64a-44ac-9e7a-67fbdc63aaba.png)

**Comment by thisissandip** [comment]
4932959-zen

**Comment by jorpdesigns** [comment]
Reported in 4945585-zen. Shared workaround from [this comment](https://github.com/Automattic/wp-calypso/issues/62646#issuecomment-1098623338).

**Comment by thesacredpath** [comment]
Another report here: 4945993-zen

**Comment by samiff** [comment]
Jetpack version 10.9-a.5 has been deployed to WoA sites which should correct this issue.

**Comment by darnelldibbles** [comment]
Another report from Twitter: https://twitter.com/UnwantedLife_Me/status/1527940257089523715

**Comment by jartes** [comment]
Another one on 40084073-hc but this was for posts, not for products.

**Comment by mmtr** [comment]
> Jetpack version 10.9-a.5 has been deployed to WoA sites which should correct this issue.

Seems to be fixed now, I'm unable to replicate the issue any longer (video below) so I'm closing this one out. Feel free to re-open if the issue still persists.


https://github.com/user-attachments/assets/6c77c302-9e57-4479-9960-1473e711b8bf
