### ISSUE TITLE
WooCommerce Stepper Onboarding - Research submission process and create issues

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#62671]
We need to acquire further information regarding what `/start` is currently doing when submitting the WooCommerce onboarding flow, so we can effectively replicate it in our Stepper implementation. Deliverable here is a set of new GitHub issues dividing up the work necessary to make the WC Stepper flow submittable.

**Comment by andres-blanco** [comment]
P2 detailing the process. paYKcK-1xp-p2

**Comment by andres-blanco** [comment]
Here is a list of potential issues to break this up.
* Replicate a Progress bar component in the stepper: `client/signup/steps/woocommerce-install/transfer/progress.tsx`
* Replicate an Error component in the stepper: `client/signup/steps/woocommerce-install/transfer/error.tsx`
* Audit in detail all track events triggered. Multiple of these where seen in the code for different purpouses (redirects, errors, success).
* Replicate `client/signup/steps/woocommerce-install/confirm/index.tsx` component in stepper
* Replicate `client/signup/steps/woocommerce-install/transfer/transfer-site.tsx` component. Basically this should trigger Atomic transfer and WooCommerce plugin install, update a progressbar and redirect when ready.
* Replicate `client/signup/steps/woocommerce-install/transfer/install-plugins.tsx` component. This should trigger plugin install, update a progressbar and redirect when ready
* Replicate `client/signup/steps/woocommerce-install/transfer/index.tsx` to decide which of the the 2 previous components should be used and handle common errors.

**Comment by andres-blanco** [comment]
The issues where created and are linked above.
