### ISSUE TITLE
[E-mails] [Subscriber welcome] Revamp welcome email.

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#62679]
### Details

Subscriber welcome email should match the designs provided below.

Originally reported in: pdtkmj-73-p2#comment-160

### Related

D78623-code

**Comment by mashikag** [comment]
Hey @mtias ! 👋  

I am working on this ticket at the moment. One of the tasks to be done as part of this is to update the footer content. If you look at the footer content in the provided designs there is a point which says:

> Click on the unsubscribe link at the bottom of every email

However there is no unsubscribe link at the bottom of the email. 

Is there any more up-to-date designs on it? Or would you have any proposal on what should we do about this? 

cc @yansern

**Comment by yansern** [comment]
Closing.
