### ISSUE TITLE
Tooling: Improved Anchor.fm developer documentation

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#62701]
### Overview

While there is some information about the Anchor.fm _integration_, there isn't much developer-focused documentation.

We should write a Field Guide page which outlines the architecture of the integration, where all of the code lives, pitfalls of development, etc.

**Comment by sixhours** [comment]
Some things to add:

* How to find the Anchor podcast ID
* How to find a podcast episode ID
* How to access the Anchor flow, either directly via URI or from calls to action on the Anchor side.

**Comment by sixhours** [comment]
Something to add when we take this up: Tracks event names for the Anchor flow have changed as a result of moving to the Stepper framework from Gutenboarding. When the new flow is deployed, we'll want to note the date that change happened and the past Tracks event names (found in #63066) in case we need to check flow data from before the changeover.

**Comment by sixhours** [comment]
Have a good start on this on the existing Anchor FG page: PCYsg-vWu-p2

**Comment by markbiek** [comment]
That was a really good explanation of how all the pieces together.

A couple of minor things I noticed:

![image](https://user-images.githubusercontent.com/917632/167941040-ebdf8933-bd46-40b9-a1c6-aa4408f36971.png)
Is that `, and` supposed to be there?

![image](https://user-images.githubusercontent.com/917632/167941451-b46054ab-cc16-4df8-b5a4-683444873d8a.png)
Is `#3` meant to be blank?

**Comment by sixhours** [comment]
Good catches, all should be fixed!

I'm putting this up for review, please let me know if anything is unclear or if there's information I've left out.

The section on WordPress.com -> Anchor.fm is pretty sparse because we haven't worked on that as part of this project. I tried to convert a blog post to an episode yesterday and it didn't work, so we may need to investigate that after launching the updated signup flow. 🙃

**Comment by markbiek** [comment]
I fixed that trailing `, and` plus a couple other teeny-tiny typos.

**Comment by andres-blanco** [comment]
I have never been able to set up an account to show me this component:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/375980/168610774-b771cc3a-dbe0-4772-91d9-ec4705b032de.png">

Is there a reliable way to get to that screen? If there is not, maybe it would be good to add a note in the FG.

**Comment by sixhours** [comment]
> I have never been able to set up an account to show me this component:

> Is there a reliable way to get to that screen? If there is not, maybe it would be good to add a note in the FG.

Hrm, I don't know. 🤔 If you add the query param `?wpshare=2` to the end of the Anchor dashboard URL after creating a new episode, does it show? If not, I wonder if it's a localization issue, since AFAIK we only offer the full Anchor connection to EN locales.

**Comment by andres-blanco** [comment]
> > I have never been able to set up an account to show me this component:
> 
> > Is there a reliable way to get to that screen? If there is not, maybe it would be good to add a note in the FG.
> 
> Hrm, I don't know. 🤔 If you add the query param `?wpshare=2` to the end of the Anchor dashboard URL after creating a new episode, does it show? If not, I wonder if it's a localization issue, since AFAIK we only offer the full Anchor connection to EN locales.

It might be due to localization since I've seen messages of things not being available on my location. Maybe just adding a message in the FG stating that it *might* not appear is enough, since you can always just follow the link

**Comment by andres-blanco** [comment]
This FG is great! It will be very useful moving forward. Thanks ❤️

**Comment by sixhours** [comment]
Calling this closed for this sprint. We will need to update the docs again to account for signup/login steps next sprint.
