### ISSUE TITLE
Stepper: Create an Error component for the WooCommerce flow

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#62712]
On `/start` there's a custom Error component: https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/woocommerce-install/transfer/error.tsx. 

We should see if there's already something like this that can be adapted to on the Stepper or if a new one should be made.

Related: https://github.com/Automattic/wp-calypso/issues/62671

**Comment by blackjackkent** [comment]
Closed by #62772
