### ISSUE TITLE
Seller Experience: Replicate WooCommerce confirm step on stepper

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#62714]
This is the current component: https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/woocommerce-install/confirm/index.tsx.

We should replicate this on the stepper. For more info on this component refer to paYKcK-1xp-p2.

The original component looks like this:
![image](https://user-images.githubusercontent.com/917632/163581517-3bc51df6-472d-484e-968f-d27f362afa4b.png)

Related to: https://github.com/Automattic/wp-calypso/issues/62671

**Comment by markbiek** [comment]
Got the work I did and Andres did together into a single PR and the component & styles are in good shape.

Now I'm working on pulling in the data the component needs. I'm creating a data store for the product list and then creating another one for the eligibility stuff the component needs.

**Comment by markbiek** [comment]
I've got a chain of 3 PRs for this issue:

1. #62862 (ready for review/merge, merges into the branch for the next PR)
1. #62861 (wip, merges into the branch for the next PR)
1. #62821 (wip, merges into trunk)
