### ISSUE TITLE
Seller Experience: Audit which tracks are being fired in the WooCommerce last step

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#62713]
We should find out which track events are being fired in the Confirm and Transfer steps on the `/start` WooCommerce flow.

The output of this issue is a p2 detailing when/where/what tracks are being called.

Related: https://github.com/Automattic/wp-calypso/issues/62671

**Comment by sixhours** [comment]
Posted here: paYKcK-1AT-p2
