### ISSUE TITLE
Earn: Update cards copy

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#62721]
Proposed changes:

### Payment Button Card

| Site | Title | Body | Primary | Secondary |
| - | - | - | - | - |
| Free | **Collect payments** | Let visitors pay for digital goods and services or make quick, pre-set donations by enabling the Payment Button block.<br>_Available with any paid plan — no plugin required._ | Unlock this feature | [Learn more](https://wordpress.com/payments-donations/) |
| Paid (Stripe disconnected) | " | " | Enable Payment Button | " |
| Any (Stripe connected) | " | Let visitors pay for digital goods and services or make quick, pre-set donations by inserting the Payment Button block.<br>_Available with any paid plan — no plugin required._ | Manage Payment Button | [Support documentation](https://wordpress.com/support/wordpress-editor/blocks/payments/#payment-button-block) |

### Donations Form Card

| Site | Title | Body | Primary | Secondary |
| - | - | - | - | - |
| Free | **Accept donations and tips** | Accept one-time and recurring donations by enabling the Donations Form block.<br>_Available with any paid plan — no plugin required._ | Unlock this feature | [Learn more](https://wordpress.com/payments-donations/) |
| Paid (Stripe disconnected) | " | " | Enable Donations Form | " |
| Any (Stripe connected) | " | Accept one-time and recurring donations by inserting the Donations Form block.<br>_Available with any paid plan — no plugin required._ | Manage Donations Form | [Support documentation](https://wordpress.com/support/wordpress-editor/blocks/donations/) |

### Premium Content Card

| Site | Title | Body | Primary | Secondary |
| - | - | - | - | - |
| Free | **Profit from subscriber-only content** | Create paid subscriptions so only subscribers can see selected content on your site — everyone else will see a paywall.<br>_Available with any paid plan — no plugin required._ | Unlock this feature | [Learn more](https://wordpress.com/support/wordpress-editor/blocks/premium-content-block/) |
| Paid (Stripe disconnected) | " | " | Enable Premium Content | " |
| Any (Stripe connected) | " | " | Manage Premium Content | [Support documentation](https://wordpress.com/support/wordpress-editor/blocks/premium-content-block/) |

## Payments Screen `/earn/payments`

This is only for sites with Stripe disconnected.
Paid and free sites have the same copy, with one single exception:
- Paid sites have a CTA button, while free sites show an upgrade banner instead.

> ## Accept payments on your website
>
> Our payments blocks make it easy to add a buy button for digital goods or services, collect donations via a form, or limit access for specific content to subscribers-only.
>
> The Payment Button, Donations Form, and Premium Content blocks all require you to first connect your bank account details with our secure payment processor, Stripe.
>
> | Site | Primary Button | Upgrade Banner |
> | - | - | - |
> | Free | | **Upgrade to the Pro plan**<br>Upgrade to enable Payment Blocks |
> | Paid | Connect Stripe to Get Started | |
>
> All credit and debit card payments made through these blocks are securely and seamlessly processed by Stripe.
>
> ### No plugin required
> No additional installs or purchases. Simply connect your banking details with our payment processor, Stripe, and insert a block to get started.
>
> ### One-time and recurring options
> Accept one-time, monthly, and yearly payments from your visitors. This is perfect for a single purchase or tip — or a recurring donation, membership fee, or subscription.
>
> ### No membership fees
> No monthly or annual fees charged.
>
> ### Join thousands of others
> Sites that actively promoted their businesses and causes on social media, email, and other platforms have collected tens of thousands of dollars through these blocks.

### Earn Tools Card

> # Monetize your site
>
> Accept payments or donations with our native payment blocks, limit content to paid subscribers only, opt into our ad network to earn revenue, and refer friends to WordPress.com for credits.
>
> **Start earning**

---

See: pdfrp0-o5-p2

**Comment by dsas** [comment]
@Copons / @sethmclellana8c, can I just check I'm reading the table above correctly? Does use of " mean 'same as above'?

I'm asking because it seems that for sites that are connected to stripe already we're going to say:

> Let visitors pay for digital goods and services or make quick, pre-set donations by enabling the Payment Button block.
> Available with any paid plan — no plugin required. 

It seems a bit odd to me to say _enabling the Payment Button block_ when they're already connected with stripe because:
 * The wording seems like it's leading to an 'Enable Payment Button block' CTA, when the CTA is 'Manage'
 * Perhaps it seems to the user that they haven't already enabled payments, and they could worry something has broken.

**Comment by Copons** [comment]
In addition to what @dsas said, the PR (I think accidentally) added the same `Available with any paid plan — no plugin required` text to the Newsletter card.

<img width="528" alt="Screenshot 2022-04-29 at 12 15 19" src="https://user-images.githubusercontent.com/2070010/165934404-02e65d39-56c1-44bb-ae72-3cf0e8343fd7.png">

This wasn't specifically requested, but I think it makes sense to have, since the Newsletter card revolves around the Premium Content block anyway. 🤔 

Any thoughts @sethmclellana8c?

**Comment by Copons** [comment]
Closed by #63130
