### ISSUE TITLE
Support injecting patterns into themes with query blocks in the homepage

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#62724]
### Steps to reproduce

1. Open the internal vertical recipe tool.
2. Create a recipe with Geologist theme.
3. Add some patterns.

### Expected

The preview shows the patterns instead of the posts in the default Geologist's homepage

### Actual

In the preview, we still see the posts in the default Geologist's homepage:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/1525580/163132369-844e0d33-65a3-4a85-8fbf-79a5d4e91589.png">

### Notes

Check other themes which might be impacted as well.

**Comment by autumnfjeld** [comment]
@fushar  I'm wondering if this work is needed at this time:

* Initially, for MVP we are only going to use the three new themes that are currently under development (see [figma](xjXEAnOQeTReSqfVmnTqlH-fi-1%3A56))
* [Geologist has a query block built into it](https://github.com/Automattic/themes/blob/trunk/geologist-blue/block-templates/index.html), other themes might have blocks "built in" to the theme , perhaps these sorts of themes are not appropriate for verticalization - I don't know I'm just calling that out for awareness
* For our purposes now, while we work towards MVP, perhaps we should choose to only play with themes that work "out of the box" 
* If needed, we could put a warning message at the top of the Verticals tool about this "Please use the following themes......"

@alaczek might have thoughts about Geologist, or at least she might be able to explain better than I about themes that have blocks built into the theme like Geologist does.

cc: @Automattic/ganon

**Comment by fushar** [comment]
I believe @roo2 has already investigated this (CMIIW), could you confirm?

@autumnfjeld -- correct, this might not be needed for MVP.
