### ISSUE TITLE
Marketplace: find a metric that defines successful searches

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#62727]
As part of [PT: Use a search engine to power plugin results in Calypso.](pdh6GB-Ax-p2), we will need to:

- [x] make sure we have added all relevant track events in Calypso interface
- [x] create funnels
- [ ] create an A / B experiment

**Comment by WBerredo** [comment]
Search Plugins > Plugin Details CTA (install/purchase) funnel created. You can find it at Tracks funnels.

**Comment by cpapazoglou** [comment]
I think we can close this for now and just create the A / B experiment when we need it.
