### ISSUE TITLE
[Bug]: Changing site address when changing username can lead to unintentionally deleted sites

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#62720]
### Quick summary

In testing username/sitename changes and the legacy free plan, I noted that this page leads to some serious confusion and does not seem to work correctly on https://wordpress.com/me/account/

Specifically, when changing username, you are presented with two options to select a matching sitename

1. Yes, change `OLDUSER.WORDPRESS.COM` to match my new username and discard the old address
2. Yes, change `OLDUSER.WORDPRESS.COM` to match my new username and create an empty blog with the old address

<img width="1060" alt="Markup 2022-04-12 at 14 14 42" src="https://user-images.githubusercontent.com/1967448/163055796-36014ab2-de17-41ae-957a-1cd2e5863142.png">

### Steps to reproduce

On test account go to https://wordpress.com/me/account/ and change your username.  The behaviour is different based on the option you choose, I'll detail how to reproduce each below

If you choose the option: **Yes, change `OLDUSER.WORDPRESS.COM` to match my new username and discard the old address**
- Expected: `OLDUSER.WORDPRESS.COM` is deleted (via name change) and new site `NEWUSER.WORDPRESS.COM` is created, and inherits the legacy features of the `OLDUSER` site.  Specifically on free sites I would expect the new site to have a 3GB storage limit
- Observed: `OLDUSER.WORDPRESS.COM` is deleted and has 1GB storage limit, `NEWUSER.WORDPRESS.COM` is created, and has 1GB storage limit.  The aspects of the legacy free site are lost in the switch for _both sites_.

If you choose the option: **Yes, change `OLDUSER.WORDPRESS.COM` to match my new username and create an empty blog with the old address**
- Expected: `OLDUSER.WORDPRESS.COM` is emptied and new site `NEWUSER.WORDPRESS.COM` is created.
- Observed: `OLDUSER.WORDPRESS.COM` is deleted and has 1GB storage limit, `NEWUSER.WORDPRESS.COM` is created, but the user is not added as admin and the site does not appear under their account.

### What you expected to happen

See above

### What actually happened

See above

### Context

https://wordpress.com/forums/topic/changed-username-lost-2gb-media-storage/

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

Given that this seems to affect users with legacy free sites (who expect those features to persist) it seems like the best and easiest solution would be to remove both of these options.  Allow users to change their username, and prompt them to visit their site settings if they want to change their site address to suit.

Standard address changes (on legacy free sites) retain all the legacy features as expected, so it would be best to point users to that flow to be safe:  https://en.support.wordpress.com/changing-site-address/

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Ask user to change their username only, then in a separate step change their site address (for existing sites) or create a new site with matching address.

**Comment by jerrysarcastic** [comment]
Also noting this related issue regarding username changes on atomic sites:  https://github.com/Automattic/wp-calypso/issues/60031

**Comment by vykes-mac** [comment]
I have created a fix for testing here D80695-code
