### ISSUE TITLE
Marketplace: Plugin activation scripts do not run when plugins are installed via Calypso

### ISSUE THREAD

**Issue by hideandgeek404** [Automattic/wp-calypso#62739]
### Quick summary

We have found two instances where activation code (one using `register_activation_hook()` and another using `admin_init`) does not run when plugins are installed on WordPress.com but do work fine on self-hosted sites. I suspect that it has something to do with Calypso generating redirects and losing information prior to any code running.

However, once the plugin is installed, if you visit the Plugins screen and deactivate then reactivate the plugins the activation code works.

### Steps to reproduce

1. Start with any WordPress.com site that has the ability to use plugins
2. Click Plugins > Add New
3. Search for `Simple Ajax Chat`
4. Click `Simple Ajax Chat` By Jeff Starr
5. Click "Install and activate" button
6. Once the Thank You screen is shown, check the database and you'll see there is no `wp_ajax_chat` table created.
7. Click "Manage Plugin" button
8. Click "Deactivate" on Simple Ajax Chat
9. Click "Activate" on Simple Ajax Chat
10. Recheck the database and see that the activation script has now run and the database table `wp_ajax_chat` has been created.

### What you expected to happen

I expected the tables to be created during the original "Install and Activate" process as this is outlined in an activation script `sac_create_table()` found in `simple-ajax-chat.php` in the plugin (line 105 in the current version)

### What actually happened

The tables were not created during the initial "Install and activate" process and I needed to manually deactivate and activate the plugin for the activation script to run.

### Context

4943375-zen

### Simple, Atomic or both?

Atomic

### Browser, operating system and other notes

The reproduction above is using the Simple Ajax Chat plugin. However, you can also find the same issue for the FloThemes Flo Forms Pro plugin at 4716060-zen. That one uses the `register_activation_hook()` method instead. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is not ideal and probably not intuitive, but it would be to install the plugin as normal and then deactivate and reactivate the plugin to get the plugin activation to run.

**Comment by JoshuaGoode** [comment]
Re: p9F6qB-95E-p2#comment-46663

Perhaps @Automattic/bespin can check and see if it's related to how the new marketplace UX is activating plugins?

**Comment by jmdodd** [comment]
"do work fine on self-hosted sites" -- This seems to be reproduceable on a self-hosted, Jetpack-connected site.

Steps:
- Visit https://wordpress.com/plugins/simple-ajax-chat/[JETPACK SITE DOMAIN HERE]
- Click "Install and Activate"
- See: (After several step screens) "All ready to go! Simple Ajax Chat has been installed."

In WP CLI for the site:
```
$ wp plugin list
+--------------------------+----------+--------+----------+
| name                     | status   | update | version  |
+--------------------------+----------+--------+----------+
| akismet                  | active   | none   | 4.2.2    |
| hello                    | inactive | none   | 1.7.2    |
| jetpack                  | active   | none   | 10.8     |
| simple-ajax-chat         | active   | none   | 20220216 |
+--------------------------+----------+--------+----------+
$ wp db query "SHOW TABLES;" | grep ajax
$ wp db query "SHOW TABLES;" | grep options
wp_options
```

**Comment by epeicher** [comment]
A P2 has been created with alternatives pdh6GB-S1-p2 a great suggestion in the comments pdh6GB-S1-p2#comment-1579 that is worth exploring

**Comment by epeicher** [comment]
After some investigations and discussions, we have identified that those plugins are not following the recommended best practices. The suggestions are:

### For Simple Ajax Chat:

Remove [the following condition](https://plugins.trac.wordpress.org/browser/simple-ajax-chat/trunk/simple-ajax-chat.php#L112):

```php
if (isset($_GET['activate']) && $_GET['activate'] === 'true') {
```
And use `register_activation_hook` instead of `admin_init`, like:
```php
// Use this
register_activation_hook(__FILE__, 'sac_create_table'); 
 
// Instead of the existing
add_action('admin_init', 'sac_create_table');
```

### For Flo Forms:

[The following condition ](https://href.li/?https://plugins.trac.wordpress.org/browser/flo-forms/trunk/flo-forms.php#L41)is preventing the [licensing mechanism to run](https://plugins.trac.wordpress.org/browser/flo-forms/trunk/flo-forms.php#L60) so it could be removed or only use for other scenarios other than running activation functionality:

```php
// The code under this condition will not run when installing plugins from other context than the wp-admin screen
if(is_admin()) { 
```

Related pdh6GB-S1-p2#comment-1712

**Comment by epeicher** [comment]
@hideandgeek404 I have posted some suggestions to third party developers in my previous comment. Please let me know if I should contact the developers of those plugins and the best way to do it.

I asked a similar question here p1653902914502719-slack-C03TY6J1A

**Comment by JoshuaGoode** [comment]
Thanks, @epeicher we can track our outreach internally.

 p9F6qB-9xp-p2
