### ISSUE TITLE
Site Vertical Screen: Track user input vs. the selected vertical

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#62754]
## Description 

At the moment, the site vertical screen tracks and stores the vertical data the user has selected from the suggestion dropdown. It would be great if we can track and compare if users are finding what they originally intended to find. We should add another event that tracks what the user has typed in compared to the vertical they ended up choosing.

For instance:
* User has typed in "Lego".
* The suggestion dropdown suggests "Toys", "Education", and "Children"
* User selects "Toys".

The event should reflect that the user intended to find "Lego" but selected "Toys" instead as the closest result.

## Acceptance Criteria
- [ ] Create a new event that tracks user input vs. the selected vertical.
- [ ] The event should also work in the case a user typed in something and selected "Something Else" option.
- [ ] The event should be registered and visible on Tracks.

## Related
* p1649912054979639/1649835630.656169-slack-CRWCHQGUB
* #61526
* https://github.com/Automattic/wp-calypso/pull/62611

**Comment by autumnfjeld** [comment]
@taipeicoder  We've already added `calypso_signup_site_vertical_submit` in #62611  , do we just want to add a prop to this event?
e.g. `user_input` or whatever makes sense.

Checking with @that-mike-bal here p1649980844435679/1649835630.656169-slack-CRWCHQGUB
