### ISSUE TITLE
Atomic: "Edit Site" button doesn't update after theme switch to/from FSE

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#62755]
### Quick summary

When someone installs a theme that requires a site builder(e.g. Elementor) like Hello Elementor, the "Edit site" button will link to this:

https://SITENAME/wp-admin/themes.php?page=gutenberg-edit-site

This will render this message:

`"Sorry, you do not have permission to access this page."
`

### Steps to reproduce

1. Go to https://wordpress.com/home/sitename
2. Click on "Edit site" on the right sidebar
![image](https://user-images.githubusercontent.com/6737345/163330625-ca0021d9-4e54-454f-a1a1-d11f87074dc4.png)

### What you expected to happen

Be forwarded to the Pages section at least or wp-admin/Pages

### What actually happened

I saw this:

![image](https://user-images.githubusercontent.com/6737345/163330737-e317cb43-4566-4927-b938-6b38e41e5298.png)

### Context

4946414-zen

### Theme-specific issue?

This appears to be dependent on the theme installed, but only those that require a site builder.(Elementor, Astra, etc)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Go through wp-admin instead

**Comment by Robertght** [comment]
4944953-zen

**Comment by tyxla** [comment]
Originally introduced in https://github.com/Automattic/wp-calypso/pull/59329 cc @Automattic/cylon

**Comment by Addison-Stavlo** [comment]
I can repro that this 'Edit Site' button shows up under some unexpected circumstances regardless of the 3rd party themes. But this seems to be larger issue with the "Quick Links" in MyHome not updating as expected on atomic.

To Repro:
* Create a new test site with an FSE theme (like twenty-twenty-two)
* Upgrade the plan and install a plugin to transfer to Atomic.
* Once transfered, switch theme to a non-FSE theme (like twenty-twenty)
* Notice "Edit Site" button in my home still exists (unexpected) while the actual appearance menu entry point is gone (expected).

Also:
* Take an existing Atomic site that was transfered on a non-FSE theme.
* After the transfer switch to an FSE theme.
* Notice the 'Edit Site' button is not in myhome quick-links (unexpected), while the entry point under appearance is available (expected).

This seems that the quicklinks stay under whatever state was in place at the time of transfer or something? And don't update accordingly on theme switch.... 🤔  cc @tyxla

**Comment by Addison-Stavlo** [comment]
Looking further it seems like its an issue with `is_fse_active` property from the block-editor-settings endpoint.  Same repro as my comment above but I tried this out specifically in the API console for `is_fse_active` from this endpoint.

`is_fse_active` is always returning `true` for an atomic site that was transferred with an FSE theme, even after they switch to a non-fse theme. (and always `false` if transfered with non-FSE, even after switching to FSE).

I can see this oddity happening from the RC as well in these cases:

![Screen Shot 2022-04-14 at 11 51 49 AM](https://user-images.githubusercontent.com/28742426/163427058-eee7e293-3856-4b0e-857f-64ff46b1379e.png)
 (obviously 'skatepark' IS fse) 🤔 

cc @creativecoder @jeyip if you have any thoughts here.

**Comment by edequalsawesome** [comment]
Also reported in 34963107-hc

**Comment by jeyip** [comment]
> Looking further it seems like its an issue with is_fse_active property from the block-editor-settings endpoint. Same repro as my comment above but I tried this out specifically in the API console for is_fse_active from this endpoint.

> is_fse_active is always returning true for an atomic site that was transferred with an FSE theme, even after they switch to a non-fse theme. (and always false if transfered with non-FSE, even after switching to FSE).

@Addison-Stavlo There might be a number of issues at play, but one thing to note is that this looks to be partially related to a previous discussion p1646421387522829/1646421378.255859-slack-CHN6J22MP

In essence, `is_fse_active` and the block editor settings endpoint might return stale data for some period of time.

> Atomic sites are depending on Jetpack sync to get the updated data after theme switch

> The alternative would be to add the API endpoint to Atomic sites, through Jetpack… that would allow wpcom to query the Atomic site directly, rather than relying on the synced data. Not too hard, but requires some work.

@mattwiebe we punted work on the aforementioned API endpoint because we didn't have concrete use cases at the time. This might be a legitimate use case. Alternatively, we could hide the Edit site button UI, but that feels non-optimal.

**Comment by Addison-Stavlo** [comment]
>  block editor settings endpoint might return stale data for some period of time.

I just retested the sites I noted above and can confirm this is the case. After the time has passed, they are now returning the correct data.

**Comment by Robertght** [comment]
Another case with Astra/Elementor in 5179996-zen

**Comment by creativecoder** [comment]
I think the most direct way to fix this would be to know from the site's REST API if the theme supports block templates (which is the check used when the Site editor is loaded). That way we aren't waiting for data to sync behind the scenes that might be out of date, like what's happening right now.

I poked around and found that theme support data for the current theme is provided from the Core endpoint `/wp-json/wp/v2/themes?status=active`, but `block-templates` is missing!

I opened a trac issue and submitted a fix: https://core.trac.wordpress.org/ticket/55681

If we can get this issue fixed in Core, it should be relatively simple to use this data in Calypso for displaying the Site editor link.

**Comment by rinazrina** [comment]
Another report with Hever theme: #5215044-zen

**Comment by cuemarie** [comment]
Ran into this with a user on Dara theme: 35514472-hc

- `Edit site` on dashboard's My Home https://wordpress.com/home/
- `Edit` button on Themes page https://wordpress.com/themes/, and 
- `Customize site` button on the theme's info page https://wordpress.com/theme/dara/ 

all try to open https://wordpress.com/site-editor/ instead of the Customizer, resulting in:

```
Sorry, you are not allowed to access this page.
```

Workaround: Asked user to go directly to Appearance > Customize for now

**Comment by cuemarie** [comment]
Just ran into this again with a user with a third party theme, Sydney, here: 35536878-hc

Edit button links to: `https://XXXXXXX.com/wp-admin/themes.php?page=gutenberg-edit-site` which leads to 

```
Sorry, you are not allowed to access this page.
```

**Comment by Robertght** [comment]
> https://core.trac.wordpress.org/ticket/55681

Thank you @creativecoder !

As per the above ticket, this might land in WordPress 6.0.1.

**Comment by jorpdesigns** [comment]
Noticed a slightly different issue in 35634051-hc (followed up in 5249314-zen).

In this case, the site was using a 3PD theme (Vara) and the referral link was the "Edit" button on the Themes page.

<img width="1507" alt="Screen Shot 2022-05-27 at 13 44 52" src="https://user-images.githubusercontent.com/40006288/170709593-48d956aa-0e4d-4b13-a9ec-4ce57048cf2d.png">

That link goes to https://SITENAME/wp-admin/themes.php?page=gutenberg-edit-site as well. The settings for this particular theme are in the Customizer so clicking the link should redirect you to the Customizer instead.

I also noticed that when you load the Themes page (Appearance → Themes), the correct Customizer link (https://SITENAME/wp-admin/customize.php) shows for a brief second (the button label is Personalize) and then it switches to the "Edit" button.

**Comment by Addison-Stavlo** [comment]
Thanks for reporting @jorpdesigns !

I think what you are describing is a result of the same underlying cause here. Those buttons are being influenced by stale data, which we should be able to fix and reliably deliver accurately by incorporating the core change that @creativecoder [describes above](https://github.com/Automattic/wp-calypso/issues/62755#issuecomment-1117943409).

**Comment by sharonlaker19** [comment]
More reports at 35723620-hc and 35718416-hc

**Comment by creativecoder** [comment]
I'm not sure of the timing of the WP 6.0.1 release, but @agrullon95 and I are going to ready a fix that we can use as soon as the release happens.

**Comment by jorpdesigns** [comment]
Also reported in 35616593-hc. 

The site is using a 3PD theme (JackRyan) and the "Edit Site" link goes to the site editor (leading to the error message).

The "Edit" button on the Themes page goes to the site editor as well.

- [ ] Please follow up in 5278002-zd.

**Comment by creativecoder** [comment]
Here's the draft PR for the fix: https://github.com/Automattic/wp-calypso/pull/64497

**Comment by thekingsprojects** [comment]
- [ ] Another case here: 5307838-zen

Gave user the option to edit with Appearance > Customize instead.

**Comment by jorpdesigns** [comment]
Another case here (using the Astra theme): 35828823-hc.

They were able to access theme options from Appearance → Customize.

- [ ] Follow up ticket created in 5311123-zen.

**Comment by masperber** [comment]
35854285-hc

Another case, using the third-party Shoptimizer theme. No follow-up needed.

**Comment by masperber** [comment]
35805605-hc

Another case, using the Storefront theme. They were able to access theme options from Appearance → Customize. No follow-up needed.

**Comment by jp-imagines** [comment]
Another in 35895076-hc. User had switched to a third-party theme with its own version of the Site Editor, and were confused when the "Edit Site" link wasn't working.
No follow-up needed.

**Comment by nagpai** [comment]
5322058-zd 

No followup needed. `Edit site` instead of `Edit homepage` showing on a non FSE themed site. Clicking `Edit site` takes to `Sorry you are not allowed`

**Comment by villanovachile** [comment]
Another report 5326375-zen

**Comment by kimerlin81** [comment]
Just reported on AT site using Hever theme; Suggested WO (Appearance -> Customizer)
Button remains as Edit instead of changing to Customize

- [ ]  please follow up in 5327636-zd-woothemes once resolved

**Comment by creativecoder** [comment]
It looks like the WP 6.0.1 release is [scheduled for July 12th](https://make.wordpress.org/core/2022/06/25/wordpress-6-0-x-release-team-and-6-0-1-schedule/). We should be able to get the fix in https://github.com/Automattic/wp-calypso/pull/64497 released shortly after that.

**Comment by edwinho89** [comment]
35952011-hc

User is on Twenty Twenty Two theme, and experienced the same issue as well. Guided user to access site editor from the nav bar.

**Comment by jp-imagines** [comment]
- [ ] Another in 5344761-zd-woothemes

In Safari, this user was actually seeing a `load cannot follow more than 20 redirections` error when trying to use the "Edit Site" link in My Home on an unsupported theme.

**Comment by jamiepalatnik** [comment]
Another report: 35979045-hc

Edit button on Themes page links to /themes.php?page=gutenberg-edit-site with error "Sorry, you are not allowed to access this page."

Storefront theme. Advised to go to Appearance > Customize to access Customizer instead.

**Comment by kuropixel** [comment]
- [ ] Another report. 5352251-zen

Third party theme "Node". Advised to use Customizer via Appearance > Customize as a workaround.

**Comment by jromales** [comment]
Another report in 5352281-zd-woothemes. They're using 3rd party `Neve` theme and I shared the workaround to access through Appearance → Customize

**Comment by jromales** [comment]
Another report in 35973630-hc using 3rd party `ExpertHive` theme. I shared the workaround to access through Appearance → Customize in the meantime

**Comment by cuemarie** [comment]
Another report: 35999719-hc

Third party theme `Dhor`. Sent to Appearance > Customize instead.

**Comment by hacchism** [comment]
36002816-hc

Another report AT site using Dyad 2.

**Comment by devNigel** [comment]
Another one: 35998041-hc

They are using third-party theme `Bosa Shopper`

- [ ] Followup: 5355430-zd-woothemes

**Comment by rw-ye** [comment]
5362374-zd-woothemes

Theme: eighties

Advised user to access the customizer via Appearance > Customize.

**Comment by donalirl** [comment]
Seen in #5362860-zen with wpcom Libretto theme

**Comment by sharonlaker19** [comment]
+1 in 36038792-hc using the Dara theme. Recommended Appearance > Customize.

**Comment by sharonlaker19** [comment]
5365720-zen, Storezia theme.

**Comment by rinazrina** [comment]
Another one: 36051202-hc using NewsCard (3rd party theme)

**Comment by csabarakasz** [comment]
Another report using Hever theme

- [ ] 25978377-hc

**Comment by creativecoder** [comment]
https://github.com/Automattic/wp-calypso/pull/64497 has been deployed, so this should be fixed. I'm going to close this issue, but please reopen if you see this issue persist.

**Comment by sharonlaker19** [comment]
I got a new report today in 36091830-hc

**Comment by Robertght** [comment]
5411195-zen

**Comment by rw-ye** [comment]
5412143-zd-woothemes

Theme: Hemingway Rewritten

**Comment by Addison-Stavlo** [comment]
After reading the reports that are still incoming, it looks like this is still failing at this specific edit button:

![Screen Shot 2022-07-21 at 8 15 02 AM](https://user-images.githubusercontent.com/28742426/180211435-af604e16-2d38-4155-a363-320a029e8e97.png)

As you can see above on my atomic test site, I enabled a classic theme (twenty nineteen), yet I have the Edit button directing me to the Site Editor instead of Customize.  cc @agrullon95 @creativecoder 

Note that the original issue description pointed to a button in "MyHome" This part does seem to be resolved as it properly changed "Edit Site" to "Edit Homepage". Upon further inspection all other "Edit Site" / Customizer conditional entry points that I can find seem to be working as expected (the theme switch modal, myhome, nav sidebar, etc. all update appropriately for the customizer).

**Comment by creativecoder** [comment]
That makes sense, as so far we've only migrated the logic for "Edit site" on My Home to use the Core endpoint for detecting FSE.

We're tracking other uses of `is_fse_active` in https://github.com/Automattic/wp-calypso/issues/65697, that @agrullon95 is currently working on, so this should be resolved soon.

**Comment by jp-imagines** [comment]
Just noting I had another instance of this (the "Edit" button appearing instead of "Customize" at _Appearance > Themes_) in 36000379-hc for a third-party theme.

On my end, I saw the button "flicker" between Customize/Edit before settling on the incorrect "Edit" button.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on P2 - N/A 
- Tested on Simple ✅
- Tested on AT ✅ 
- Tested on Self-hosted - N/A 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to recreate this on Atomic. When I activated the FSE theme Pendant, I see Customize on the Themes page instead of Edit as expected. Screenshot: <img width="929" alt="Customize" src="https://user-images.githubusercontent.com/30788962/180360068-b1f1d358-529e-4af5-8c4f-07d18818c62f.png">
- I also think I saw the button flicker between Edit and Customize at one point, but couldn't recreate this consistently.
- Marking this as Triaged since I can recreate and it looks like this is already being investigated as well. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
"Edit" appearing in place of "Customize" for third party non-fse theme `Marketplace`, here: 36188777-hc

<img width="1101" alt="Screen Shot 2022-07-25 at 2 56 37 PM" src="https://user-images.githubusercontent.com/27249804/180880621-6de302cb-bd54-4717-874b-5db7aae81eaa.png">

I see the button flick between Edit & Customize when I load the page. Clicking "Edit" leads to: 

```
Sorry, you are not allowed to access this page.
```

Directed user to Appearance > Customize for now; no follow up needed.

**Comment by creativecoder** [comment]
Possibly related: https://github.com/Automattic/wp-calypso/issues/65955

**Comment by Addison-Stavlo** [comment]
I believe the remaining issues have been resolved with https://github.com/Automattic/wp-calypso/pull/65850

**Comment by cuemarie** [comment]
@Addison-Stavlo I ran into a report of this from a user today - they are using a custom child theme of Divi on v4.18.1.

Both Quick Links > Edit Site and `Customize Site` from the theme info page link to the site editor, not the customizer.

They don't have the `gutenberg` plugin installed, is that where this fix was deployed? Or is it possible this has reoccurred?

Chat: 36597744-hc
Follow Up (if needed): 5904864-zd-woothemes

Any insight you have would be appreciated!

**Comment by Addison-Stavlo** [comment]
Hi @cuemarie - I believe `Customize Site` on the theme info page is intended to go to the site editor here.

Are they able to go to `Appearance` -> `Customize` and access the customizer that way?

**Comment by cuemarie** [comment]
Hey @Addison-Stavlo ! They were able to access `Appearance > Customize` as expected, yes! 

On a plugin-enabled test site of mine, when I have a classic theme activated, **Theme Info > Customize Site** button leads to the Customizer, not the Site editor, and **My Home > Quicklinks** contains a link to "Edit Homepage", as shown below: 

### Test Site Example, Theme: Twenty Twenty

![Markup on 2023-02-02 at 10:20:12](https://user-images.githubusercontent.com/27249804/216396464-e48b90fe-b77a-4abe-aef1-851bc7963fbe.png)

![Markup on 2023-02-02 at 10:21:48](https://user-images.githubusercontent.com/27249804/216396838-20eccf37-839f-4f1a-aaa4-0cfbe465d80e.png)


---

By comparison, the user site in question seems to reflect the original bug:

### User site, Child Theme of Divi

![Markup on 2023-02-02 at 10:18:10](https://user-images.githubusercontent.com/27249804/216397020-5885f75a-f715-461a-b0ed-2a75fa2bad31.png)

<img width="1480" alt="Markup 2023-02-02 at 10 18 41" src="https://user-images.githubusercontent.com/27249804/216397296-50d7ac8a-e8c1-43db-8f0a-0760ab9444b7.png">

---

Thanks for looking into it!

**Comment by Addison-Stavlo** [comment]
> Test Site Example, Theme: Twenty Twenty

This is not an FSE theme, so we would expect "Customize" from the theme info to lead to the customizer in this case.

> User site, Child Theme of Divi

This seems to be an FSE theme, and thus links to the site editor as expected.

Is there something else that needs to be resolved here?  The original issue was related to different buttons, and improperly linking to the wrong places for the wrong themes. In this circumstance, it seems the buttons are linking where they are expected for the type of theme.

**Comment by cuemarie** [comment]
>This seems to be an FSE theme, and thus links to the site editor as expected.

Ahhh, this is the point of confusion I think. Where do you see that this is an FSE theme?  

Their Divi theme loads in the Customizer, and by comparison, loads the following error when they try to open the Site Editor through those links, so I assumed the third party theme was not an FSE-compatible theme, thus reflecting the issue reported above: 

![Markup on 2023-02-08 at 14:06:41](https://user-images.githubusercontent.com/27249804/217650957-f5d2f25c-5745-45b4-8da5-a38e7c838cf6.png)

**Comment by cuemarie** [comment]
This bug has been solved for WPcom themes, but was re-opened **by me** for a specific user using a custom child theme of Divi, which does not use the Site Editor, but is running into the issue from the original report.

@ianstewart I see you're working on debugging this here: p1677507825624849-slack-C0160HSMDQV

Would you like to keep the issue open for now? Anything you need further to support that?

**Comment by paulopmt1** [comment]
Thanks for reopening it @cuemarie! I could reproduce it with the Divi theme.

In summary, the root cause is our API /themes endpoint is returning the wrong information about the theme having or not FSE capability. It uses a different (and simple) check to define if a theme has block-templates or not. 

We need more investigation to understand why and what is the best fix for it. Here we have more details: p1678452716408409/1678373232.124809-slack-CKZHG0QCR

**Comment by paulopmt1** [comment]
Diff created here: D105875-code

**Comment by cuemarie** [comment]
Thanks for that update @paulopmt1 , and awesome find! 

📌 ACTION
- moving to **Other** now that this has 👀 on it. Feel free to move to a better column if needed!

**Comment by paulopmt1** [comment]
The current strategy didn't work as expected, we need an alternative approach, here is the review feedback: p1679676755161469/1679611536.074369-slack-CKZHG0QCR

Explorers plan to prioritize it at the end of our current sprint, so if anyone prefers to tackle it, please continue.

**Comment by paulopmt1** [comment]
The current strategy didn't work as expected, we need an alternative approach, here is the review feedback: p1679676755161469/1679611536.074369-slack-CKZHG0QCR

Explorers plan to prioritize it next sprint, so if anyone prefers to tackle it, please continue.

**Comment by creativecoder** [comment]
@paulopmt1 It looks like Core introduced a new theme supports that indicates support for the Site editor, `block-template-parts`, whereas Calypso is still relying on `block-templates`.

Here's a PR that updates that: https://github.com/Automattic/wp-calypso/pull/75639
 
Would appreciate if you can help test it!

**Comment by paulopmt1** [comment]
> 

Thanks for working on it @creativecoder! Will review it by tomorrow morning :)

**Comment by creativecoder** [comment]
My solution in https://github.com/Automattic/wp-calypso/pull/75639 was not viable, as the `block-template-parts` theme support [doesn't seem to be used consistently
](https://github.com/Automattic/wp-calypso/pull/75639#issuecomment-1505920721).

I submitted a [Core ticket ](https://github.com/Automattic/wp-calypso/pull/75639)and [accompanying PR ](https://github.com/WordPress/wordpress-develop/pull/4323) that would add the result of `wp_is_block_theme` to the wp/v2/themes API response, which should work as a better indication of theme support for the site editor.

**Comment by creativecoder** [comment]
In case the Core change takes a long time or is rejected, here is [a Jetpack change](https://github.com/Automattic/jetpack/pull/30144) that will supply the same information in the wp/v2/themes response.

As soon as this lands on WP.com sites, we can [update Calypso](https://github.com/Automattic/wp-calypso/pull/75850) to use the new theme field.

**Comment by cuemarie** [comment]
Just encountered another user with a third party classic theme that shows the "Edit Site" option under Quick links: 42825551-hc

I see https://github.com/Automattic/jetpack/pull/30144 is merged, but https://github.com/Automattic/wp-calypso/pull/75850 is still in tests, so this seems expected for now.

Glad a WPcom fix is on the way - thanks for puzzling this one out, @creativecoder !

**Comment by creativecoder** [comment]
Yes, still waiting for https://github.com/Automattic/jetpack/pull/30144 to land on wpcom (Simple sites) and Atomic, then I'll merge https://github.com/Automattic/wp-calypso/pull/75850 to fix the bug. Should be sometime next week.

**Comment by creativecoder** [comment]
Update: the Jetpack changes have landed on wpcom. I'm working to resolve an issue with Core unit tests in D108111-code. After that I'll get the Calypso change merged.

**Comment by creativecoder** [comment]
D108111-code and https://github.com/Automattic/wp-calypso/pull/75850 are now deployed. This issue should finally be resolved--but please reopen if you find it pops up again.

**Comment by Greatdane** [comment]
I think this is related to a bug I just opened regarding Launchpad; https://github.com/Automattic/wp-calypso/issues/76819

Will reopen, but please close if you think the bug is different (the search "The theme you are currently using is not compatible with the Site Editor" brought me here)

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS

- Tested on Simple – **Could Not Replicate**
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO

- The "Edit Site" button is not available in the Quick Links section if the theme used is non-FSE. 

**FSE theme**
![Screenshot 2023-05-12 at 13 41 24](https://github.com/Automattic/wp-calypso/assets/67279475/355e3607-461e-42a3-924f-fa4c3c8db7bf)

**Non-FSE theme**
![Screenshot 2023-05-12 at 13 41 47](https://github.com/Automattic/wp-calypso/assets/67279475/4c26e391-6aef-491b-80ff-813fbe36c494)

📌 ACTIONS

- Closed as could not replicate (please reopen if the issue reoccurs)
