### ISSUE TITLE
Site.options.unmapped_url missing for a Jetpack site

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#6276]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/ (note this issue happens on prod and was reported by a user);
2. Su a user (contact me personally for more details);
3. Get JS error about `site.options.unmapped_url` missing (not present in the data from the API).

#### What I expected

wp.com working normally.

#### What happened instead

No sites are displayed/loaded.

#### Browser / OS version

Latest Chrome on Ubuntu 16.04 but happens also elsewhere (probably Windows).

#### Screenshot / Video

This is what I get when I put a breakpoint in `client/lib/site/utils.js` on line 162 (sensitive parts redacted, contact me personally for more details):

![selection_021](https://cloud.githubusercontent.com/assets/4988512/16313405/5f5c540a-3979-11e6-98a6-a46859545893.jpg)

This is the stack trace:

![selection_022](https://cloud.githubusercontent.com/assets/4988512/16313517/d2e06736-3979-11e6-94d1-3649b0460295.jpg)

**Comment by gravityrail** [comment]
It's probably worth noting that in this particular case the user had a role of "None" on the site in question, leading to the sites endpoint refusing to rendering things like options. In this case the API did the right thing as far as I can tell.
