### ISSUE TITLE
Admin Bar is missing on the front end for atomic sites on the Pro plan.

### ISSUE THREAD

**Issue by jorpdesigns** [Automattic/wp-calypso#62762]
### Quick summary

Atomic sites on the new WordPress.com Pro plan seem to be missing the Admin Bar on the front end.

The bar displays for atomic sites on the biz and eCom plans. I and a few other HEs are able to reproduce but some other HEs aren't, not sure why.

I checked in Safari, Firefox and Chrome without any luck.

### Steps to reproduce

1. Set up a test site, add the Pro plan and make the site atomic.
2. View the site from the front end (you might need to launch the site).

### What you expected to happen

The admin bar should be visible:

<img width="1547" alt="abv" src="https://user-images.githubusercontent.com/40006288/163351782-16bfef32-5f04-4c92-b777-033638ed86d0.png">

### What actually happened

The admin bar is missing:

<img width="1543" alt="abm" src="https://user-images.githubusercontent.com/40006288/163350593-9d7cb494-7a42-499a-8076-45946266e3e5.png">

### Context

Reported here: 35074857-hc. Follow up ticket: 4945162-zd

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by cuemarie** [comment]
**Replicated?** ✅ 
**Browser(s) Tested:** Firefox, Chrome

 **Screenshots from Test** WPcom admin bar appears on Simple Pro site: 

<img width="1254" alt="Markup 2022-04-19 at 11 53 43" src="https://user-images.githubusercontent.com/27249804/164076150-5bb033e8-b3d1-4ff8-85a4-ec10ac785216.png">

After activating hosting features, I see the WPorg admin bar:

<img width="1252" alt="Screen Shot 2022-04-19 at 11 55 22 AM" src="https://user-images.githubusercontent.com/27249804/164076234-02b8c56b-b154-431b-81c2-8a61646a3835.png">

---

It appears this is related to this issue: https://github.com/Automattic/wp-calypso/issues/52046#issuecomment-824643372

> In other words, the WordPress.org toolbar will be the one you see on the front end of the site until you visit WP Admin at least once.

I tested this on my newly AT Pro site pictured above by going to Jetpack > Dashboard (a `/wp-admin` page), then refreshing the live site. Now the WPcom admin bar is visible.  

I also ran into the WPorg bar on a Legacy Business and eCommerce site until I visited a `/wp-admin` page, and then the issue resolved.

Going to close this issue in favor of https://github.com/Automattic/wp-calypso/issues/52046
