### ISSUE TITLE
[Bug]: Core Styles Adding Unremovable Gap Between Header and Content

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/wp-calypso#62782]
### Quick summary

Default CSS adds gap between header and content that can't be removed.

Tested with Twenty Twenty Two theme.

### Steps to reproduce

1. Create a template
2. Add header
3. Add block such as a "Cover Block" that you want to line up against header with post content
4. Observe gap between blocks 

### What you expected to happen

I shouldn't have a gap between elements or if there is, I should be able to edit it without CSS.

I can't edit without CSS because core styles are applied:

```
.wp-site-blocks > * + * {
  margin-block-start: var( --wp--style--block-gap );
}
```

### What actually happened

There is a gap that can't be removed between header and site content.

## Editor View:
<img width="1702" alt="Screenshot on 2022-04-14 at 12-11-54" src="https://user-images.githubusercontent.com/45246438/163430452-ee155524-cf0f-4b4b-b6fb-54252b8dc76b.png">

## Frontend:

![Annotation on 2022-04-14 at 12-10-55](https://user-images.githubusercontent.com/45246438/163430312-a9fa756e-3ad7-414d-ba0a-6c220c28a964.png)

### Context

I encountered this while doing FSE testing to build a custom "post in a series" view

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

Can't be fixed on plans without CSS editing.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Can use this in Custom CSS:

```
.wp-site-blocks > * + * {
    margin-block-start: 0;
}
```

**Comment by edequalsawesome** [comment]
Came up in 35997697-hc

**Comment by jordesign** [comment]
Closing this to consolidate into #64438
