### ISSUE TITLE
Editing Toolkit / Atomic: Cannot select layout/template or close out of Add a Page when Gutenberg is inactive

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#62788]
### Quick summary

WPCOM Pro/BIZ/ECOM sites on the hosted platform (Atomic) can experience issues with the starter layout/template selector.

Sites that have the WordPress.com Editing Toolkit (full-site-editing) plugin active but the Gutenberg plugin inactive cannot proceed by the Add a Page template selector

![Screen Shot on 2022-04-14 at 14:58:26](https://user-images.githubusercontent.com/4887830/163458388-05d438fa-ca20-4183-b34a-92de4955c876.png)
.

### Steps to reproduce

1. Start with a WPCOM Pro/BIZ/ECOM site with a plugin installed or hosting configuration features activated (Atomic)
2. Deactivate Gutenberg
3. Add a new page
4. Attempt to exit "Add a Page" dialogue, select a template, or select the blank page option
5. See error, cannot proceed 

### What you expected to happen

To be able to proceed with exiting the dialogue or selecting a layout.

### What actually happened

Cannot proceed. 

### Context

p1649960073209529-slack-C03TY6J1A

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Activate the Gutenberg plugin

**Comment by Gustavo-Hilario** [comment]
Another report here: 35151425-hc

**Comment by thesacredpath** [comment]
Report here as well: 4948629-zen

(edit) User wants to know when the fix has been released.

**Comment by tvolpert** [comment]
Another report: 35171057-hc

**Comment by tvolpert** [comment]
And here: 34937970-hc

**Comment by tvolpert** [comment]
one more: 35182158-hc

**Comment by syhussaini** [comment]
One more 4953566-zen

I was able to replicate the issue from my end.
The pop-up window that appears when creating a new page cannot be closed. I tried to select a different theme; that didn't work either.

**Comment by nagpai** [comment]
35207260-hc

**Comment by nagpai** [comment]
![image](https://user-images.githubusercontent.com/4162931/163982091-474adb1f-254d-4f82-b647-32a6faab2c46.png)

**Comment by sophiegyo** [comment]
Another incident in 16601533-hc for me.
I was able to replicate on my own AT site:
![image (1)](https://user-images.githubusercontent.com/36608681/164165175-e8e9f99f-8e22-4042-8572-e73aa02a5b27.png)

Both sites using Gutenberg 13.0.0, but two different (?) versions of the WordPress.com Editing Toolkit:

* User: WordPress.com Editing Toolkit 3.30687
* Me: WordPress.com Editing Toolkit 3.31093

Nearly forgot to mention, I posted in Slack before being pointed here:
p1650368496318549-slack-CBTN58FTJ

@noahtallen made some findings in the Slack thread:

>So it seems that when ETK is loaded in WordPress 5.9 with Gutenberg disabled, a couple of these stores aren’t defined. In particular this one:
[https://github.com/Automattic/wp-calypso/blob/94fe59f75d919c439f182764eed7d86f1f63[…]-toolkit-plugin/starter-page-templates/page-patterns-plugin.tsx](https://github.com/Automattic/wp-calypso/blob/94fe59f75d919c439f182764eed7d86f1f63da48/apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-patterns-plugin.tsx#L20)
Though it also seems that wordpress/nux , used a few lines later, is also not defined.

**Comment by danielk-am** [comment]
Another one was caught at 4953809-zen.

**Comment by thesacredpath** [comment]
Another report here: 4953554-zen

**Comment by sanjeev00733** [comment]
Another report in #33458462-hc

**Comment by sanjeev00733** [comment]
One more report today in #31123303-hc

**Comment by IoanaAMuresan** [comment]
One more instance of this: #4964320-zen

**Comment by daria2303** [comment]
4964395-zd-woothemes

**Comment by nagpai** [comment]
#4963556-zen

The site here does not have Gutenberg plugin. Deactivated WordPress Editing Toolkit plugin to mitigate the error.

**Comment by Greatdane** [comment]
This doesn't have an effective workaround (other than enabling Gutenberg, but we can assume a user wanted it disabled for a reason), and it is generating quite a few reports, so I have changed priority to high.

**Comment by sarahcada** [comment]
Another at 5161341-zd-woothemes
The workaround of enabling Gutenberg helped.

**Comment by Gustavo-Hilario** [comment]
Another case on 35292375-hc

**Comment by tvolpert** [comment]
Another one here: 35293158-hc

**Comment by aisajib** [comment]
Ran into it here: 35143390-hc

The site didn't even have Gutenberg installed for some reason. Running `plugin symlink gutenberg --activate` in CLI fixed the issue.

**Comment by sanjeev00733** [comment]
Another one in #35298623-hc

**Comment by thekingsprojects** [comment]
Another case in 35304953-hc . Reactivating Gutenberg fixed it.

**Comment by Addison-Stavlo** [comment]
From the code side this seems to be deeper than the starter page templates. It seems the welcome-tour store may not be initializing on atomic sans Gutenberg. You can notice nothing happens when you select "Welcome Guide" from the top toolbar ellipses menu in this state. With gutenberg disabled, it silently fails. With Gutenberg enabled, it works fine.

Looking at the error from these starter page templates it seems to say that [this is not a function](https://github.com/Automattic/wp-calypso/blob/f94ff293bdff7327ca791e20f276828fb8756899/apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-patterns-plugin.tsx#L99). That function comes from the welcome tour store, which seems to be problematic in this state as noted above. 🤔  cc @Automattic/team-calypso-platform  @alshakero if you have ideas about what may be causing this recently.

**Comment by noahtallen** [comment]
Copy/pasting another comment here: @p-jackson found that when you register a script, but WP can’t find one of the requested dependencies, it fails to load the script. Wpcom NUX seems to rely on a script that isn’t present when gutenberg is deactivated (wp-react-i18n). So the next step would be figuring out if we can get wpcom-nux to stop relying on that script since there’s no guarantee that our projects in ETK will run with the Gutenberg plugin on Atomic

**Comment by sajmes** [comment]
35071083-hc

**Comment by masperber** [comment]
Another report here 35079601-hc

**Comment by arthur791004** [comment]
I think we encounter a similar issue in https://github.com/Automattic/wp-calypso/pull/56750 as we introduced the `useI18n` from `@wordpress/react-i18n` and fix it by replacing `useI18n` with `__` from `@wordpress/i18n` in https://github.com/Automattic/wp-calypso/pull/56977. So, we might introduce something again to make the plugin be broken when the Gutenberg is deactivated.

**Comment by kylemcph** [comment]
Another report here: 33967410-hc

**Comment by noahtallen** [comment]
Thanks for the tip, it does indeed look like it was the same issue: #56930

**Comment by kimerlin81** [comment]
reported [here](5184675-zd-woothemes), but workaround is acceptable for the user

**Comment by sophiegyo** [comment]
Another one in 5166076-zen but it looks like the user had already activated Gutenberg before I got to the ticket.
