### ISSUE TITLE
Theme Pages: Purchase Now Bar Showing in Previews

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/wp-calypso#6279]
#### Steps to reproduce
1. Starting at URL (Look at Premium themes): https://wordpress.com/design/type/premium
2. Click a theme to preview it. I choose Gema.
3. Click a link, like a post, in the preview.
4. The Purchase Now bar shows up. See: http://cl.ly/gXDj

#### What I expected

The Purchase Now bar shouldn't show on pages I click in the preview.

#### What happened instead

The Purchase Now bar shows on pages I click in the preview.

#### Browser / OS version

Mac OS X with Chrome

#### Screenshot / Video

<img width="1436" alt="image 2016-06-23 at 11 36 28 am" src="https://cloud.githubusercontent.com/assets/4389/16567802/0982d72c-4223-11e6-802b-d8df7a6e65ad.png">

Reported by WordPress.com seller, Array Themes.

**Comment by folletto** [comment]
For reference, this isn't strictly Calypso, nor strictly Themes, but it touches a few things:

1. Calypso opens a preview with a special query argument in the URL  (some background in #5666) 
2. The preview is a standard website, thus navigating away removes the query arguments in the URL
3. Without these, the standard items show up again

Also: the same problem might be showing up on the native apps too, given the use the same mechanism.

So, it's a bit of a crossover. The cleanest way I can think of is to make sure that the PHP plugin deals with the query parameters properly and preserve them on navigation.

**Comment by lancewillett** [comment]
Testing this today in Safari 10.0 on OS X 10.12 with `https://wpcalypso.wordpress.com/theme/gema/example.wordpress.com` — same steps as above, entering preview from `https://wpcalypso.wordpress.com/design/premium?s=gema` and clicking the theme thumbnail, then "Open Live Demo" link.

Works as expected: no purchase bar visible.
