### ISSUE TITLE
Marketplace: Add categories strings to be translated

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#62796]
## Acceptance criteria

- Make a js file with translations strings, following [this pattern](https://github.com/Automattic/wp-calypso/pull/60417/files).
- Add these categories strings for a preemptive translation:

Discover
Top free plugins
Top paid plugins
Editor’s pick
——————–
All Categories
Analytics
Business
Customer Service
Design
Ecommerce
Education
Email
Financial
Marketing
Search Optimization
Security
Photo & Video
Posts & Posting
Social
Widgets

**Comment by allilevine** [comment]
From SOTB, we need a PR like this one: https://github.com/Automattic/wp-calypso/pull/60417
