### ISSUE TITLE
Docker setup is broken

### ISSUE THREAD

**Issue by lyrixx** [Automattic/wp-calypso#628]
Hello.

See https://github.com/Automattic/wp-calypso/blob/79535ba04e2fbae6e2422cb3667b2b09b40e1d7f/Dockerfile#L8-L9
=> the file `env-config.sh` does not exist. I searched in the repository and in the git history, and I was not able to find it.

**Comment by xkidro** [comment]
Yes I noticed this also, really wanted to start it with docker but I have no ideea what env-config.sh is supose to contain, I am guessing it just sets up the ENV vars, however I did not try it.

**Comment by nb** [comment]
Hi, @lyrixx, thanks for the question.

The `Dockerfile` is rarely used for local development, more often for deployment. Still, if you’re curious, add an empty `env-config.sh` and it should work. There may be more roadblocks ahead, though.

**Comment by nb** [comment]
@xkidro yeah, it’s mostly environment variables, but they are server-specific and the file is kept in the deployment repository.

**Comment by xkidro** [comment]
Can we at least get a sample ? with sample values ? so we know which ones to configure ? I did setup ENV CALYPSO_ENV production however it does not work....

**Comment by nb** [comment]
@xkidro production is not meant to work locally – it needs extra setup, which is not trivial – requests has to come from the wordpress.com domain, user bootstrap requires a way to make an API request for any user (and a special token), there’s probably something else that I’m forgetting.

**Comment by andrewmclagan** [comment]
Id disagree with that 

>> production is not meant to work locally

One of the core premise of Docker is the concept that production is development. Your always running in as close to a production environment as possible - because you can.
