### ISSUE TITLE
[Bug]: WC plugins from WP.com Marketplace don't have download links/access

### ISSUE THREAD

**Issue by shaunkuschel** [Automattic/wp-calypso#62809]
### Quick summary

When a WooCommerce extension (like WooCommerce Bookings, AutomateWoo, etc) are purchased from the WordPress.com Marketplace, the plugins are installed at the time of the purchase. However, if that plugin is deleted from the site, there does not appear to be any way for the user to download the plugin file (so it can be re-installed).

### Steps to reproduce

1. Purchase a WooCommerce extension from the WordPress.com Marketplace
2. Delete that plugin from the **Plugins** page
3. Notice that if you go to https://wordpress.com/me/purchases you will see the purchase but there is no download link
4. Notice that WooCommerce.com doesn't show a record of that purchase (so there is no download link there)
5. Notice that connecting the purchasing account on the **WooCommerce > Extensions > My Subscriptions** page doesn't show that purchase (so there is no download link there)
6. View the product again in the WordPress.com Marketplace
7. Notice that the presented option is to re-purchase that same plugin, rather than downloading/re-installing

### What you expected to happen

After purchasing a WooCommerce product in the WordPress.com Marketplace, there should be a download link somewhere that is accessible.

Additionally, it would be helpful if the subscription/purchase info is shown on WooCommerce.com account pages (in addition to WordPress.com pages).

### What actually happened

After deleting the purchased product, the only way to get access to that plugin is to contact support.

### Context

It isn't uncommon to delete plugins and re-install them, especially in cases where the initial install experiences an issue.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple/Atomic

Atomic

### Other notes

This was reported by a user and I was able to reproduce the problem.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

### Workaround details

The workaround is for support to verify the purchase of the product and provide a copy of the file to the user. However, until that is done, it is not possible to use that product.

**Comment by allilevine** [comment]
I was able to reproduce this. I think ideally deleting the plugin without removing the purchase wouldn't be possible. They should be "managed plugins" like Jetpack, that you can't delete and which show this notice in wp-admin:
<img width="286" alt="Screen Shot 2022-04-19 at 2 07 11 PM" src="https://user-images.githubusercontent.com/1689238/164068265-113e2c27-252f-4e60-95d5-eb0641848172.png">

@ianstewart @cpapazoglou What are your thoughts?

**Comment by cpapazoglou** [comment]
> I was able to reproduce this. I think ideally deleting the plugin without removing the purchase wouldn't be possible. They should be "managed plugins" like Jetpack, that you can't delete and which show this notice in wp-admin: <img alt="Screen Shot 2022-04-19 at 2 07 11 PM" width="286" src="https://user-images.githubusercontent.com/1689238/164068265-113e2c27-252f-4e60-95d5-eb0641848172.png">
> 
> @ianstewart @cpapazoglou What are your thoughts?

Totally agree that Marketplace plugins shouldn't be _deletable_. @jmdodd is there a way to make Marketplace managed plugins behave the same as "Jetpack"?

**Comment by cpapazoglou** [comment]
We will need to add relevant code in wpcomsh. There is already a `wpcomsh_is_managed_plugin()` which we can use to hide `Delete`, `Update` buttons and show a notice `%s is automatically managed for you. You can remove this plugin by removing your subscription [here](wordpress.com link with that site subscriptions)`

<img width="1317" alt="CleanShot 2022-04-27 at 14 30 23@2x" src="https://user-images.githubusercontent.com/12430020/165508818-b0224aee-ae61-4b08-b8bf-d98e9c00badc.png">

In `wpcomsh_managed_plugins_action_links()` we can loop through `$all_plugins = array_keys( get_plugins() );` and act only if that plugin has `wpcom_purchase` with product type is `marketplace_plugin`. 
Here is how we can get wpcom purchases 920-gh-Automattic/wpcomsh/files
and here is a diff D79608-code for adding `is_wpcom_marketplace` to purchases.
