### ISSUE TITLE
Skatepark: Archive template issue (Template Archive has "Inherit query from template" OFF by default)

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#62817]
### Quick summary

On theme Skatepark, the template Archive has "Inherit query from template" set to OFF by default. This makes no matter what month or what year the page Archive is/page with template Archive is, it will always display the *latest posts*.

### Steps to reproduce

1. Have a test site ready.
2. Make sure the test site has enough number of posts. It's better if the posts are from different months and years. Make sure the latest posts are recent (since this GH is written on April, make sure the latest posts are from April 2022.)
3. Activate theme Skatepark
4. Access the archive page. Say... websiteaddress.com/2022/01 
5. Expect to see posts from January 2022 will appear
6. Nope. It displays posts from April 2022 instead.
7. Search other months or other years. April 2022 posts still visible.

### What you expected to happen

For archive page to respect the year and the month of the posts that we choose.

### What actually happened

It displays latest posts instead, not respecting the month and the year.

How? Because of this:

![Screenshot 2022-04-15 at 5 10 06 PM](https://user-images.githubusercontent.com/44726232/163551774-746d93d7-19b7-428a-b721-25d7fdfcaaf5.png)

The option "Inherit query from template" is set to OFF by default. I can confirm this because when I checked the template Archive, there is no indicator that the template has been customized (small dot thingy next to the template name.) 

### Context

Customer report and personal test.

### Theme-specific issue?

Skatepark

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Workaround: 
- Go to Editor/FSE
- Choose template Archive
- Click Query Loop Block
- On the block sidebar, make sure the option "Inherit query from template" under Settings is ACTIVE/ON.

**Comment by Robertght** [comment]
Thank you for reporting this @retnonindya !

I'm closing this in favor of https://github.com/Automattic/themes/issues/5890
