### ISSUE TITLE
WooCommerce Blocks JS (wc-settings.js) being called even when plugin is not installed

### ISSUE THREAD

**Issue by cintacks** [Automattic/wp-calypso#62815]
### Quick summary

Came across a user's site where their sidebar wasn't loading for Woo pages. It seemed related to this issue:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6260

There's a 404 for `/packages/woocommerce-blocks/build/wc-settings.js`, but woocommerce-blocks was not installed on the store. I'm not sure where that reference is coming from in the first place so more investigation needed. 

### Steps to reproduce

*This may be intermittent*

1. Install Woo 6.4
2. Check Woo pages and see if sidebar is not loading (check console errors for missing JS file)
3. Install WooCommerce Blocks plugin to alleviate issue (workaround)

### What you expected to happen

Presumably, Woo shouldn't be dependent on WooCommerce Blocks being installed/activated - Sidebar should load normally. 

### What actually happened

Sidebar was blank due to missing JS file. 

### Simple, Atomic or both?

Atomic

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Install WooCommerce Blocks https://woocommerce.com/products/woocommerce-gutenberg-products-block/ and activate.

**Comment by Robertght** [comment]
I'm not able to replicate this anymore. 

@kettultim can you see if this is still an issue on your end?

**Comment by cecilearkay** [comment]
@Robertght Pretty sure this got fixed with: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6260 so I'll close it.
