### ISSUE TITLE
Menus: Add All items to link to Post Formats Archives page

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#6281]
When editing Menus via WP Admin or Customizer there's an option to add a link to testimonials or portfolio archive page. It's called All Testimonials and All Projects.
This option is absent from Calypso.
#### Steps to reproduce
1. Activate the post types via WP Admin > Settings > Writing (if on WordPress.com)
2. Add a few test posts for the custom post types
3. Go to Menus: https://wordpress.com/menus/
4. Try to add a post type item. It only lists the individual published posts, there isn't an 'All posttypename' to link to post type archives page.
#### What I expected

That there was an option to add an item to all posts of that type, that is, a link to that post type archives page.
#### What happened instead

None was present
#### Screenshot / Video

https://cloudup.com/cYd8qq2slCc
#### Context / Source

WordPress.com user tried to add a link to the Archives page and wasn't able to. They contacted Live Chat to get help.
# user-report

This should be considered at least an enhancement because it is available through WP Admin and Customizer.

**Comment by timmyc** [comment]
It appears the logic in wp-admin is keying off of the post types `has_archive` attribute to show the "All Projects" option, which is setting a link to the post type's archive page.  Currently, the post-types endpoint does not return the `has_archive` attribute, or the archive page link - so to add in support for this feature, we would like need to update the API to include those attributes.

One possible work-around for this feature would be to create a "Link" menu item in calypso with the archive page as the link address.  So for an "All Portfolio" page you would do the following:

<img width="741" alt="menus_ _testingtimmy2_wordpress_com_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/22080/17421887/39623e04-5a62-11e6-8c0f-bc42f60f9040.png">

/cc @folletto for any input or backstory on why the "All" option was left out.

**Comment by folletto** [comment]
> for any input or backstory on why the "All" option was left out.

Not much of a backstory I'm afraid. Menus implementation was a MVP for the v1 and the support for CPTs is basic. It has still a long way to go to be complete.

**Comment by lancewillett** [comment]
Closing as Calypso menus we be replaced by Customizer menus, see #4610.
