### ISSUE TITLE
Form Block: Not able to add Submit button once removed

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#62816]
### Quick summary

The Form blocks come with submit button that you can customize. Once you remove the button from the editor, it is not possible to add it back.

But on the live page, you will notice that the button still shows up. Essentially, a user loses the ability to customize the submit button if they accidentally delete it. They will have to recreate the form from scratch.

### Steps to reproduce

1. On a Simple or Atomic site, open the post or page editor and add any type of Form block.
2. Remove the Button that is inside the Form block.
3. You will notice it is not possible to add back the button using `+` icon.
4. If you check the preview or live page, a default button will still be there.

Screen recording: https://user-images.githubusercontent.com/33957570/163551884-bf350144-5092-48c2-8914-5aa6b0298a1f.mp4

### What you expected to happen

It should be possible to add submit button to the Form block once removed.

### What actually happened

There was no way to add submit button inside the Form block.

### Context

Ticket: 4932999-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

User can undo the button removal but that is not practical in all cases, especially, if they don't notice that button was removed.

They will have to recreate the form from scratch.

**Comment by vajrasar** [comment]
Hey @devNigel thanks for the report.

I can confirm the issue on my Simple, AT, and self-hosted installation.

**Comment by cometgrrl** [comment]
@yansern one more bug for the contact form!

**Comment by vykes-mac** [comment]
@Automattic/jetpack-crew Looking at this I realise that this is the case for all forms that are apart of the Form Block. No button is listed as one of the child blocks for the forms and the button is created when only when any of the form variation is selected. I'm wondering if this is by design?

**Comment by kraftbj** [comment]
By design or not, definitely sounds like a bad flow. Even with the form self-populating a button, it should still be able to customize the button.

Feel free to move this to the Jetpack repo for tracking since the PR to resolve will need to land there.

**Comment by jeherve** [comment]
This is currently tracked here:
https://github.com/Automattic/jetpack/issues/16303

Closing this issue as duplicate.
