### ISSUE TITLE
[Bug]: Public API template call throws 500 error when the anchor_podcast id is invalid

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#62827]
### Quick summary

The public api template endpoint doesn't return anything when the anchor_podcast id is invalid.

### Steps to reproduce

Go to the template endpoint and specify an `anchor_podcast` id that doesn't exist.

https://public-api.wordpress.com/rest/v1/template/demo/mayland/hannah/?language=en&site_title=Mumbai&font_headings=Space%20Mono&font_base=Roboto&anchor_podcast=74835

### What you expected to happen

Some sort of error message response seems more appropriate.

### What actually happened

You'll just get a white screen and a 500 error.

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
Closing this given this context: p7fD6U-9EZ-p2
