### ISSUE TITLE
NUX: with /new, every theme looks like Zoologist

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#62839]
### Quick summary

When going through the /new signup, the design page offers several themes to our users, but all of them look like Zoologist.

### Steps to reproduce

1. Start at wordpress.com/new
2. Choose a site name
3. Choose a domain
4. On the design step, look at the themes offered. 

### What you expected to happen

I'd expect several theme options

### What actually happened

Every theme shows the Zoologist preview. Here's a video.

https://user-images.githubusercontent.com/3476361/163722364-972acab9-3e15-4a87-8803-dfca077e89b1.mov

### Context

I was testing this bug report from a volunteer ( https://github.com/Automattic/wp-calypso/issues/62838 )when I noticed the first non-blank theme listed looked just like Zoologist. I scrolled and realized all of them do.

### Theme-specific issue?

n/a

### Browser, operating system and other notes

n/a

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

They could use a different signup flow (if they know of it).

**Comment by Robertght** [comment]
Pinged here: p1650385699101919-slack-C7YPUHBB2

**Comment by simison** [comment]
There are no customers going into /new flow other than Anchor FM folks, and for those the design picker works — tested just now:

<img width="1908" alt="image" src="https://user-images.githubusercontent.com/87168/164192234-50c4e0ec-f872-4dbc-889e-211746650bbf.png">

You can test using URL `https://wordpress.com/new?anchor_podcast=PODCAST_ID` (see test ID from p58i-a3Z-p2)

Testing regularly via /new indeed looks like design picker is busted, but not a biggie:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/87168/164192667-938b0bbd-8441-42fa-892c-abe96c1d0b69.png">

FYI @ianstewart in case this comes up.
