### ISSUE TITLE
Domains: Warning is displayed for domains owned by other users 

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/wp-calypso#6283]
User sees `sometestingdomain.com is about to expire`, clicks on `Renew it now`, but then gets a strange message that one would not expect in this context. 

#### Steps to reproduce
1. User X creates a site Z.wordpress.com, buys the domain sometestingdomain.com, then maps the domain to the site. 
2. User Y is added to the site, given admin permissions.
3. The domain is nearing expiration.
4. User Y opens up https://WordPress.com, is logged in, clicks on 'My Sites'.
5. User Y sees that renewal is needed, clicks 'Renew it now'.

![renew-now1](https://cloud.githubusercontent.com/assets/8835135/16322591/c03b04dc-3993-11e6-891d-81c9bbe72af0.png)

 6. User Y gets `Looking to upgrade?`

![renew-now2](https://cloud.githubusercontent.com/assets/8835135/16322662/4695f0f0-3994-11e6-82db-9e1aeccb32ca.png)

#### What I expected
That I could renew.

#### What happened instead
I got a strange message, like I cannot renew. 

#### Browser / OS version
Firefox 45 

#### Context / Source

This was originally reported by a user. 

#user-report

**Comment by fabianapsimoes** [comment]
We don't display subscriptions belonging to another user in `/purchases`, because it's not possible to renew them. So `/purchases` behaves as expected.

Seems that banner is only displayed for expiring / expired domains. @klimeryk do you think this is something Cobalt can take a look at?

**Comment by klimeryk** [comment]
Yup - @aidvu should start working on fixing all the inconsistencies in the UI for non-owner users 👍

**Comment by klimeryk** [comment]
Fixed by #6940 🎉
