### ISSUE TITLE
NUX: /new displays legacy plans

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#62838]
### Quick summary

Legacy plans are offered when starting from wordpress.com/new

### Steps to reproduce

1. Start at wordpress.com/new
2. Name a site
3. Pick a domain
4. Choose a theme*
5. Choose a legacy plan

### What you expected to happen

If we intended to leave this route to legacy offerings, cool. Still, I would at least expect "Free" to have the correct info.

*There's [another bug](https://github.com/Automattic/wp-calypso/issues/62839) in the step where we choose a theme. I'll mention it in a different issue.

### What actually happened

If I choose Free, I get a free site with the new free limits.

If I choose a legacy paid plan, I'm taken to checkout for it. I had to cut this short, but you'll see what I mean:

https://user-images.githubusercontent.com/3476361/163722364-972acab9-3e15-4a87-8803-dfca077e89b1.mov

### Context

A volunteer asked about this here: p8HJWS-Zx-p2

I tested logged in and logged out.

### Theme-specific issue?

n/a

### Browser, operating system and other notes

n/a

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Other signup routes seem okay.

Also, while this would impact all customers who use /new, I've no idea how many that might be.

**Comment by Robertght** [comment]
Pinged here: p1650385699101919-slack-C7YPUHBB2

**Comment by simison** [comment]
There's no traffic going into this flow since March, apart from AnchorFM folks and those won't see the plans grid at all.
