### ISSUE TITLE
[Bug]: Kingsley - "Header and Footer Only" Template Turns Main Sub-Menu White

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/wp-calypso#62858]
### Quick summary

On Atomic sites using "Kingsley" theme, pages created using "Header and Footer Only" template don't render the navigation menu properly. The sub-menu renders with a white background which is unreadable.

### Steps to reproduce

1. Create a Pro/Atomic site
2. Select "Kingsley" theme
3. Create several pages with child pages
4. Add to menu

### What you expected to happen

Sub-page menu should not render white.

### What actually happened

Some sub-pages render the menu white:

https://user-images.githubusercontent.com/45246438/163842273-5cf0bbc1-b7f9-47b1-937d-700911451d99.mp4

### Context

4951176-zen

### Browser

Mozilla Firefox

### Simple/Atomic

Atomic

### Other notes

Initially when I tested the new pages were being created by default with "Header and Footer Only" template

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Can fix by:

- Changing page to  "Default" templace
- Using CSS

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Kingsley's dropdown menus did not default to white backgrounds on the `Header and Footer Only` template

![Markup on 2023-05-23 at 15:16:12](https://github.com/Automattic/wp-calypso/assets/27249804/c5230a5d-5a63-422f-a1f3-c5dc852e44e8)

📌 ACTIONS
- Closed as not reproducible
