### ISSUE TITLE
Purchases: Domains past 30 days expired not renewable

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#6286]
This mostly applies to WWD domains

#### Steps to reproduce
1. WordPress.com/purchases
2. Make sure the account has a domain mapping+registration upgrade beyond 30 days expired
3. refresh, It will not be renewable
4. Make both mappign+reg subscriptions less than 30 days expired
5. Refresh, It will be renewable

#### What I expected
To see the upgrade in /purchases

#### What happened instead
It disappears completely on day 31 from /purchases

#### Context / Source
Found via some live chats when a user couldn't renew themselves.

####Proposed solution
Because domains past 19 days expired require a late fee, we should make a complete alteration to how we handle domains in this case.

I'd suggest as a first iteration:
1) Make domains present in /purchases beyond the 30 day window, at least until day 43, but ideally through the entire process (73 days)
2) Make a new warning that states "This domain is X days expired, please contact support to renew, a late fee will be required" - this should go into effect on Day 19 - because that is the day the redemption phase begins
3) In the future, I'd love to automate this fee, especially for days 19-43 (when we can automate recovery), but we can discuss that below.

**Comment by fabianapsimoes** [comment]
> This mostly applies to WWD domains

Which parts of it apply only to non-WWD domains?

> Make sure the account has a domain mapping+registration upgrade beyond 30 days expired
> refresh, It will not be renewable

Can you share a screenshot of a domain in that state? Also, how have you adjusted the subscription dates for the testing instructions?

> 1) Make domains present in /purchases beyond the 30 day window, at least until day 43, but ideally through the entire process (73 days)

That's the case, no? Are you saying the domain subscriptions disappear from `/purchases` on day 30?

How many of these do we have per day, in average?

>  3) In the future, I'd love to automate this fee, especially for days 19-43 (when we can automate recovery), but we can discuss that below.

I checked in with @scruffian and it seems we do have redemption in Calypso. Does this happens to all domains over day 30, consistently?

Also, cc @aidvu @schwuk in case there was some change that might have caused a regression of this.

**Comment by spncrb** [comment]
> Which parts of it apply only to non-WWD domains?

The process should apply to all domains - only non-WWD domains have the auto-renew behavior

> Can you share a screenshot of a domain in that state? Also, how have you adjusted the subscription dates for the testing instructions?

It is completely absent from /purchases, so imagine purchases without any domain in it, even though the sub exists.

I adjusted the dates manually for the subscription, after getting some feedback that users couldn't renew domains in this timeframe.  I'd love to get more information on the code itself and what behavior it is intended to have, which was part of why I opened this issue.

> That's the case, no? Are you saying the domain subscriptions disappear from /purchases on day 30?

That is exactly what I am saying.

> How many of these do we have per day, in average?

We don't have that many coming in right now, but the big issue is that we aren't treating domains in between days 19-30 like they are in redemption - the user can renew them without the fee. This is inconsistent with our policies and allows user to circumvent the redemption process, potentially at our loss.

> I checked in with @scruffian and it seems we do have redemption in Calypso. Does this happens to all domains over day 30, consistently?

Maybe we can talk about better ways to test this?  As usual, domains have so many moving parts, testing their expiration cycle is tricky.

**Comment by spncrb** [comment]
Just to add clarity here from some recent conversations, it looks like we have two issues:
1) Domains not showing renew at all or being completely absent from /purchases. It looks like this may be related to free trials, the date of renewal, and payment method.
2) Domains 19+ days expired not showing the redemption fee. It looks like the logic is in place but implemented yet.

**Comment by scruffian** [comment]
I chatted more to @spncrb about this (p1468265348001638-slack) and to cut a long story short we are closing this as won't fix. The first issue is hard to replicate reliably and the second is not an issue that we should be solving.
