### ISSUE TITLE
Display anchor link (or ID) for Group blocks in List View

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#62872]
### What

I would like an anchor link (or ID) added to the Group block to be displayed in List View. This would be similar to how the Heading block works right now.

### Why

This might make it easier to identify each "section" of the page/layout in the List View. Also, might be better for page jumps to occur at the group level than adding it to the heading as users can set padding to the group block, making text easier to read on the screen.

Thank you! 🙏

**Comment by inaikem** [comment]
Tested on P2, Simple, AT and Self-Hosted sites (thank you, @supernovia!)

As this is a request that affects all instances of WP and not just WPcom, we raised it as a request in the core Gutenberg repo here: https://github.com/WordPress/gutenberg/issues/40456

Closing this issue and creating a reference in the [HE Cross-repo Watchlist](https://github.com/Automattic/wp-calypso/projects/116).
