### ISSUE TITLE
Remove "new masterbar" popover for new users

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#62878]
See quote below:

> Thanks for working on this. 

> I found that when you create a brand new user that just created a brand new site you end up with a double notice on the editor.

See
<img width="300" src="https://user-images.githubusercontent.com/115071/163891291-2237fdfc-d609-4dc2-89fb-99b2b5706abd.PNG" />

Can we remove the master bar notice, since for that user everything is new so there is no need to tell them about the new mobile toolbar.

_Originally posted by @enejb in https://github.com/Automattic/wp-calypso/issues/62605#issuecomment-1101843205_

**Comment by enejb** [comment]
Thanks for fixing this. 
I tested this fix and it worked as expected for me.
