### ISSUE TITLE
Dorna: Some elements on comments form overlapping on mobile devices

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#62882]
### Quick summary

On a site using the Dorna theme, some elements on the comments form are overlapping on mobile devices, particularly the checkboxes for "Notify me of new comments via email." and "Notify me of new posts via email."

Logged in view:

<img src="https://d.pr/i/34tpFg+" width="300" />

Logged out view:

<img src="https://d.pr/i/eAxE8L+" width="300" />

Ticket: 4954454-zen

### Steps to reproduce

1. Activate Dorna theme
2. Publish a blog post
3. Visit blog post on mobile device (Chrome or Safari)
4. Scroll down to see comments form

### What you expected to happen

For the checkboxes for "Notify me of new comments via email." and "Notify me of new posts via email." to line up neatly.

### What actually happened

They are overlapping on top of each other.

### Browser

iOS Safari, Android Chrome

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

This CSS code would fix it:

```
.wp-block-post-comments form {
    display: block;
}
```

But this requires a purchase of the Premium or Pro plan.

**Comment by Robertght** [comment]
Thank you for reporting this @druesome ! I'm closing it in favor of this one: https://github.com/Automattic/themes/issues/5894
