### ISSUE TITLE
Payment blocks product management: "Add new subscription" should open the add payment modal

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#62888]
### What

When the user is in Customizer and clicks the "Add new subscription" from the payment block product management (in editor), they are currently redirected to /earn/payment-plans. 

Besides doing this, we should also open the add payment plan modal so that the user shouldn't need to click again on the button

### Why

It avoids requiring the user to click again on the button from the /earn page.

[context](https://github.com/Automattic/jetpack/pull/23979#issuecomment-1102491864)

**Comment by lukaszwilczakwilnet** [comment]
PR in Jetpack: https://github.com/Automattic/jetpack/pull/24670

**Comment by lukaszwilczakwilnet** [comment]
PR in WP-Calypso https://github.com/Automattic/wp-calypso/pull/64460
