### ISSUE TITLE
FSE theme is replacing images upon size change

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#62894]
### Quick summary

I played into this ticket and it's a bit of a strange issue; one that I haven't been able to replicate on my own sites but we do have clear evidence of it happening here. Essentially, when trying to switch their site to an FSE theme, some of the single image blocks completely change the image when trying to resize them. Here is a video of the issue in action for for this post(p1w0iN-2Ei-p2):

https://user-images.githubusercontent.com/6737345/164159015-353fcd1a-c3ad-430a-a7e2-22b529a1c682.mp4

### Steps to reproduce

1. Go to this post: p1w0iN-2Ei-p2
2. Try to resize the image

### What you expected to happen

The image would get resized

### What actually happened

The image changes to something else entirely

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

They said that it has happened with multiple FSE themes, but currently they have it set to Twenty Twenty Two - without the ability to replicate it I can't say if it's happening on other themes.

### Reproducibility

Once

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
@ClassicRKR27 it looks like a glitch indeed, but I cannot replicate this on my end at the moment.

I noticed the src of that thumbnail gets changed to this for some reason: db5ac-e5d_2012_08_12_1391.jpg?w=300

The site in question appears to be a Simple one.

I believe it may be a glitch with the current image ID.

Have we suggested to delete that image and to add it again?

**Comment by IoanaAMuresan** [comment]
Customer in this ticket 4958975-zd is back, asking to be kept in the loop when we have a fix on this.

**Comment by jordesign** [comment]
@ClassicRKR27 as this seems like a one-off issue - open a Happiness Feedback P2 to continue research there, instead of treating it as a bug. Thanks!

**Comment by Robertght** [comment]
@ClassicRKR27 I'm going to close this one for now, but please take Jordan's advice for next steps.
