### ISSUE TITLE
Marketplace: Add category cards

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62891]
We need to move the Marketplace categories from the dropdown into a visible toggle group.
P2: pdh6GB-Mu-p2
Figma: https://href.li/?f84fqtCG4pCnCh2Hq0But5-fi-1810%3A22660

Before:
<img width="1134" alt="Screen Shot 2022-05-09 at 2 17 18 PM" src="https://user-images.githubusercontent.com/1689238/167472091-3110af9b-eb09-42db-bcc0-61995117a9b1.png">

After:
![image-4](https://user-images.githubusercontent.com/1689238/167471460-29775eae-7c3f-4ac7-b0fc-3bf7108b6422.svg)

Acceptance criteria:
- [ ] Built using components that can be re-used for the theme Marketplace -- "a more general filter bar pattern."
- [ ] When first visiting the plugins page I see a horizontal list of our primary categories, with the first and selected option being “All".
- [ ] The category list scales with size of the viewport. Categories that don’t fit are nested under a “more” option. This is essentially a responsive [toggle group](https://href.li/?https://wordpress.github.io/gutenberg/?path=/story/components-toolbargroup--default) (WordPress component). For a better idea how this works in practice see [AirBnB](https://href.li/?https://www.airbnb.com.au/s/homes?refinement_paths%5B%5D=%2Fhomes&date_picker_type=flexible_dates&search_mode=flex_destinations_search&search_type=AUTOSUGGEST). 
- [ ] Clicking “more” triggers a dropdown menu showing all remaining categories. There are existing component options in Calypso or [wordpress/components](https://href.li/?https://wordpress.github.io/gutenberg/?path=/story/components-dropdownmenu--default) for this.
- [ ] If “All” is selected, we show the same sections (e.g. top paid) below as we currently do.
- [ ] Selecting a category shows all plugins within that category. If a category is selected, no collections are shown and instead we show number of results with the category name. When using the search field I see the same thing.
- [ ] When a category is selected, it's highlighted in the toggle group.
- [ ] On mobile, rather than using a dropdown, all categories are shown in a horizontally scrolling list.

Follow-ups:
- https://github.com/Automattic/wp-calypso/issues/63460
- https://github.com/Automattic/wp-calypso/issues/63461

**Comment by allilevine** [comment]
Calypso: /pages and click More menu.

**Comment by allilevine** [comment]
To do: split "clear" button and sticky categories into separate issues.

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/pull/63592
https://github.com/Automattic/wp-calypso/pull/63787
