### ISSUE TITLE
Support unique block pattern source site for verticalization

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#62898]
We want to have a unique patterns source site for the block patterns which will be used to create v13n recipes.

slack discussion around supporting only one pattern source site p1650359918242949/1650352427.538429-slack-CRWCHQGUB

### block-patterns API diff
D79074-code

### mc recipe tool diff
D79177-code

### Calypso diff
TBA

**Comment by arthur791004** [comment]
Close as all are shipped 🚢
