### ISSUE TITLE
Media Library: Video file accepted on WP Admin but not through Calypso

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#62903]
### Quick summary

A user reported a file that they couldn't upload through Calypso in the Media Library. I have a copy of the file and can confirm this is the case.

### Steps to reproduce

1. Visit Media Library in Calypso
2. Upload the media file
3. See the error
4. Attempt via Classic View/WP Admin and the file is accepted
EDIT: the cause seems to be special characters, specifically `'` in the filename of the video.

### What you expected to happen

The video file should be accepted on both Calypso and WP Admin

### What actually happened

Calypso doesn't accept the file type and generates the following error:

```
Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://public-api.wordpress.com/rest/v1.1/video-uploads/104315152/, response code: 403, response text: {"success":false,"data":{"error":"Access Forbidden","message":"Invalid Mime"}}, request id: n/a)
    c https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    r https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    n https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    r https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    value https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    value https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    promise callback*value https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    value https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    value https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    promise callback*value https://wordpress.com/calypso/evergreen/50830.d021039faa205975b883.min.js:2
    F https://wordpress.com/calypso/evergreen/99423.2ea48666ea20515c44d5.min.js:2
    promise callback*../packages/wpcom.js/src/index.js/F/</< https://wordpress.com/calypso/evergreen/99423.2ea48666ea20515c44d5.min.js:2
    F https://wordpress.com/calypso/evergreen/99423.2ea48666ea20515c44d5.min.js:2
    promise callback*../packages/wpcom.js/src/index.js/F/</< https://wordpress.com/calypso/evergreen/99423.2ea48666ea20515c44d5.min.js:2
    F https://wordpress.com/calypso/evergreen/99423.2ea48666ea20515c44d5.min.js:2
    addFiles https://wordpress.com/calypso/evergreen/99423.2ea48666ea20515c44d5.min.js:2
    addMediaFiles https://wordpress.com/calypso/evergreen/99423.2ea48666ea20515c44d5.min.js:2
    c https://wordpress.com/calypso/evergreen/7801.f83f3a802d1e0132e1f6.min.js:1
    a https://wordpress.com/calypso/evergreen/7801.f83f3a802d1e0132e1f6.min.js:1
    fn https://wordpress.com/calypso/evergreen/88716.14c8bc68b5b7393335d3.min.js:1
    c https://wordpress.com/calypso/evergreen/88716.14c8bc68b5b7393335d3.min.js:1
    l https://wordpress.com/calypso/evergreen/88716.14c8bc68b5b7393335d3.min.js:1
    executeMutation https://wordpress.com/calypso/evergreen/88716.14c8bc68b5b7393335d3.min.js:1
    a https://wordpress.com/calypso/evergreen/88716.14c8bc68b5b7393335d3.min.js:1
    promise callback*../node_modules/react-query/es/core/mutation.js/e.execute https://wordpress.com/calypso/evergreen/88716.14c8bc68b5b7393335d3.min.js:1
    mutate https://wordpress.com/calypso/evergreen/88716.14c8bc68b5b7393335d3.min.js:1
    l https://wordpress.com/calypso/evergreen/7801.f83f3a802d1e0132e1f6.min.js:1
    d https://wordpress.com/calypso/evergreen/7801.f83f3a802d1e0132e1f6.min.js:1
    g https://wordpress.com/calypso/evergreen/45423.51a6e374927b31cda1e3.min.js:1
    u
```

### Context

Customer report - 4952508-zd-woothemes

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Switching to WP Admin allows the file to work.

**Comment by Robertght** [comment]
~It could be related to the recent Jetpack update. Similar case: p9o2xV-21I-p2#comment-5794~

~Recent update: p9o2xV-236-p2~

~cc @coder-karen @sdixon194~

---

Oh, ignore! it's not Vaultpress related.

**Comment by janmckell** [comment]
Update about a workaround from 4952508-ZD:

"...tried using the 'media with text' option, and it allowed me to upload the video right there, so I am thinking the issue is isolated to the videopress option."

**Comment by Robertght** [comment]
I tried to replicate this and it looks like I was only able to replicate it with the user's video(attached in the ticket) 

The closest previous thing I could find is this: https://github.com/Automattic/wp-calypso/issues/5435 but it doesn't appear to be relevant anymore.

I believe this needs more troubleshooting. Here are more details we could gather:

 - What device was this video made on?
 - Is that the only video that's causing an issue or are there others?

**Comment by Greatdane** [comment]
I also had an error with the video provided in the ticket, however, I think it relates to the naming of the file, rather than the file itself. The name was very long and contained a number of non-alpha characters. Changing the name of the file allowed a successful upload. 

Console Error:

```
88716.14c8bc68b5b7393335d3.min.js:1 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://public-api.wordpress.com/rest/v1.1/video-uploads/197615244/, response code: 403, response text: {"success":false,"data":{"error":"Access Forbidden","message":"Invalid Mime"}}, request id: n/a)
    at a.value (50830.d021039faa205975b883.min.js:2:262999)
    at 50830.d021039faa205975b883.min.js:2:264871
(anonymous) @ 88716.14c8bc68b5b7393335d3.min.js:1
50830.d021039faa205975b883.min.js:2 Uncaught (in promise) Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://public-api.wordpress.com/rest/v1.1/video-uploads/197615244/, response code: 403, response text: {"success":false,"data":{"error":"Access Forbidden","message":"Invalid Mime"}}, request id: n/a)
    at a.value (50830.d021039faa205975b883.min.js:2:262999)
    at 50830.d021039faa205975b883.min.js:2:264871
```

**Edit:** It looks like videos with the character `'`will not upload to calpyso!

**Comment by cometgrrl** [comment]
Putting this at low priority since it seems related to the special characters in the filename, which seems like it would be a) rare and b) has an easy workaround.

**Comment by simison** [comment]
@roundhill hi! Would handling special characters correctly on video uploads be good one for VideoPress team to fix?

**Comment by roundhill** [comment]
Yes, we created the resumable uploader. We'll look into this next week!

**Comment by jgcaruso** [comment]
Created D80573-code to address this

**Comment by jgcaruso** [comment]
The fix has been deployed!

I'll leave the issue open since I'm not sure about Calypso's tracking workflow.

**Comment by kdevnel** [comment]
Let original customer know - 5209301-zd-woothemes

**Comment by simison** [comment]
> I'll leave the issue open since I'm not sure about Calypso's tracking workflow.

@jgcaruso feel free to close when fixed elsewhere than calypso repo. It got reported here because the issue appeared on .com. cc @cometgrrl
