### ISSUE TITLE
Edit Site front-end admin link broken in some cases.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#62915]
It was reported that our "Edit Site" admin button / link on the front-end of sites does not always lead to where expected.  (p1650392267606899-slack-C01DF571R5Y)

![image](https://user-images.githubusercontent.com/28742426/164270830-5536d5ae-4d93-425c-a99f-e4ef3b748ee5.png)

Instead of leading to the expected `wordpress.com/site-editor/{siteUrl}`, it has reported in some circumstances to lead to a white screen at `wordpress.com/site-editor?site={siteUrl}` (on a simple FSE site with TT2 theme).

I am currently unable to reproduce this on my test sites, but we should investigate what causes this to happen. cc @annezazu if you can still reproduice this issue or have any more details of the site where this errored (TT2 + FSE + ?)

**Comment by creativecoder** [comment]
I think this is a duplicate of #61953?

**Comment by Addison-Stavlo** [comment]
> I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/61953?

seems to be. I will close this one in favor of that issue. thanks!
