### ISSUE TITLE
Route for Checkout-thank-you

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#6291]
Currently to test NUX flow you have to create a new page which makes testing that much harder.
When something is hard, we tend to do that less.

We need a **route for "Thank you" page after successful checkout.**

In the midst of Plans redesign efforts, it would be good to be able to easily test plans page for new users.
The best way to do that would be to have a dedicated URL

Currently to test it, we need to go through whole flow. That page requires receipt id to even be displayed.
Would be nice to be able to quickly test it without going through whole signup flow.

CC @rralian

**Comment by bisko** [comment]
We are currently working on migrating the `SignupDependencyStore` to Redux, which may make testing easier by allowing setting of the necessary data directly in the store. The PR is here: #6124

**Comment by lsinger** [comment]
Are you referring to the `/checkout/thank-you/SITE_SLUG/RECEIPT_ID` page? 

We do need the receipt data to display the correct thank you page (plan, layout, ...) afaik. 

What would you want to display when we don't have any data? And — if that were static and didn't get data from a receipt — would that still a thing that we should rely on for testing?

**Comment by artpi** [comment]
Honestly, that stopped being useful long time ago since we are not working on plans page any more.
