### ISSUE TITLE
Plugin Uploads / Atomic Transfer: Plugin upload installation fails when transferring private Simple sites

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#62928]
### Quick summary

***Since the process transfers the site to Atomic, users can try uploading the plugin again and it will not be impacted by this issue.***

Simple sites can transfer to the Atomic platform in various ways, one is by uploading a plugin manually via My Sites > Plugins > Upload.  

Uploading a plugin there initiates an Atomic transfer and the marketplace-styled installer. 

In the background, the site will transfer to Atomic successfully but the plugin installation process will fail.

Sometimes, the user may encounter an error while waiting for the plugin installer to finish on `https://wordpress.com/plugins/upload/SITE_DOMAIN`

`This URL should not be accessed directly. Please try to upload the plugin again. - Go to the the upload page`
![Screen Shot on 2022-04-20 at 13:02:43](https://user-images.githubusercontent.com/4887830/164308447-64e6f5be-a786-4000-a600-2719e690a447.png)

### Steps to reproduce

1. Start with a Simple site with an Atomic compatible plan
2. Set site to Private under My Sites > Settings > General
3. Navigate to My Sites > Plugins > Upload
3. Attempt to upload a plugin, such as Elementor, manually via a .zip file.
4. See error, check site's Installed Plugins to find the plugin was not installed

### What you expected to happen

Plugin to install and activate, no errors

### What actually happened

Errors, plugin did not install

### Context

Internal testing, p1650481191135179/1650469650.753789-slack-C036E4KFP2L

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

After failure, user can try again and the plugin should install properly

**Comment by Greatdane** [comment]
Confirmed, thanks for the super clear steps!

<img width="976" alt="Markup 2022-04-21 at 14 20 54" src="https://user-images.githubusercontent.com/5075840/164378833-e257d4f4-ab0e-4ef4-946c-1432e0f004b9.png">

**Comment by gcsecsey** [comment]
Backlog grooming:
When transferring to Atomic, the site's primary domain changes. Check if the primary domain check is the root of the problem. Try identifying the site in another way.

https://github.com/Automattic/wp-calypso/blob/0f5d51add1beccbf3a08f3e9d0cc654a87ae7a7e/client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx#L103-L118
