### ISSUE TITLE
Marketplace: Search on enter mobile usability

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#62933]
We recently merged a [search on enter](https://href.li/?https://github.com/Automattic/wp-calypso/pull/62573) change and while testing I noticed the mobile flow might need something more.

It’s hard to see it when testing on a desktop browser using mobile views because the onscreen keyboard doesn’t show up. On mobile you end up getting very little feedback a search has completed and it almost looks like the search didn’t execute, with the upgrade nudge pushing results below the keyboard fold you also don’t really get any hint there are results to scroll to unless you know.

A couple of options to fix might be to:

- Hide the keyboard on enter
- Scroll to search results on enter

https://user-images.githubusercontent.com/811776/164364395-0fd8c270-131e-4a0a-ae09-118bfc626e04.mp4

p2 context pdh6GB-AJ-p2#comment-1233

**Comment by cpapazoglou** [comment]
Maybe it would also be beneficial having a Submit icon (both on desktop and mobile) cc @galakhyati

**Comment by SaxonF** [comment]
> Hide the keyboard on enter

This sounds good to me and consistent with how native apps work

**Comment by cpapazoglou** [comment]
I agree with @SaxonF, let's hide the keyboard on enter.
