### ISSUE TITLE
Podcast Block not showing new episodes

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#62942]
### Quick summary

When a new podcast is released on Podbean/Anchor.FM (it may include other external podcast hosts) the new episode does not show up as an option in the podcast player block.

### Steps to reproduce

Podcasters adds a new episode at their remote host.
The episode appears in the RSS feed.
It does not show as an option to select in the podcast player block or appear as the lastest episode if more than one episode is shown.
I can see the episode is in the RSS feed but it's not appearing as an option.

### What you expected to happen

That the new episode should appear straight away or within an hour or so.

### What actually happened

The new episode does not show

### Context

4936393-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

On AT sites (such as my own) in order to update the list I go into CLI every time and do a cache flush. This updates the list straight away. 

For simple sites however, this isn't an option.

One HE suggested using https://crowcollectiveworkshops.com/flesh-cricket-podcast/?clearmemcache=brisket

But this didn't work.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Cache flush in CLI for AT Sites. User can contact support to enable the option ([see doc](https://wordpress.com/support/clear-your-sites-cache/#why-do-i-have-to-contact-you-to-turn-it-on)).

**Comment by formosattic** [comment]
Will close this in favor of https://github.com/Automattic/wp-calypso/issues/50740 , I've added the clear cache workaround in the other issue.

Will add this report to the other thread.
