### ISSUE TITLE
Domains: `Cancel transfer` link is not working for inbound domain transfer

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#62941]
### Quick summary

The `Cancel transfer` link in Calypso for an inbound domain transfer is not functional/clickable. The HTML code doesn't even have an <a> tag.

![image](https://user-images.githubusercontent.com/39308239/164412704-bb93cab4-656e-4c53-8696-d3079f6fadd7.png)

### Steps to reproduce

Check the Calypso domain page for a domain in `pending_start` status.

### What you expected to happen

A working `Cancel transfer` link

### What actually happened

`Cancel transfer` is not a link, so there is no way to cancel the inbound domain transfer.

### Context

Initially reported in p1648645854517919-slack-C0761SX4K. I think it falls under @Automattic/nomado?

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.3 with Google Chrome Version 100.0.4896.127 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Domain transfer can be removed via the Purchases https://wordpress.com/me/purchases

**Comment by zdenys** [comment]
4951952-zd-woothemes

**Comment by delputnam** [comment]
Thanks for the report @zdenys. We (Nomado) are working on it.
