### ISSUE TITLE
Activity Log: Some theme link directly to Github, .org instead of the Theme Info page

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#62954]
### Quick summary

Under Jetpack > Activity Log, the link to the theme `Stow` directs to `https://github.com/Automattic/themes/tree/master/stow` instead of the usual `https://wordpress.com/theme/stow/` info page

<img width="941" alt="Markup 2022-04-21 at 07 06 56" src="https://user-images.githubusercontent.com/27249804/164476916-3815ec1e-593e-4b1f-934b-6aef8bb52af0.png">

### Steps to reproduce

1. Open a Test Site
2. Activate the theme Stow
3. View Jetpack > Activity Log (it may take a few minutes for the Theme switch to appear)
4. Click on Stow link in Activity Log

### What you expected to happen

To be directed to the WordPress.com info page for Stow, like all other WordPress.com themes

### What actually happened

Instead the link directs to https://github.com/Automattic/themes/tree/trunk/stow in a new tab. That page also shows a message at the top of the page: 

```
Branch not found, redirected to default branch.
```

<img width="1237" alt="Markup 2022-04-21 at 07 10 50" src="https://user-images.githubusercontent.com/27249804/164476869-24094208-9a63-416e-bc47-0ebf511c1515.png">

### Context

Noticed this when helping a user discover which theme they were using in their past. The GH page would be a confusing area to land on 

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Stow

### Browser, operating system and other notes

Tested on Simple and AT sites
Firefox 99 on MacOS 12.3.1

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Customers can return to their themes screen and find the info page for Stow.

This likely would just lead to confusion were someone to click the link from their Activity Log.

**Comment by formosattic** [comment]
This is possibly an issue for a few other themes themes, I noticed the same with all the themes I tested:
* Twenty Twenty-Two (Blue) links to https://github.com/wordpress/twentytwentytwo/
* Dalston links to https://github.com/Automattic/themes/dalston
* Archeo links to https://github.com/Automattic/themes/tree/trunk/archeo
* Remote links to https://github.com/Automattic/themes/tree/trunk/remote

One odd one is Twenty Nineteen linking to https://wordpress.org/themes/twentynineteen/

Some older themes link fine:
* Illustratr links to https://wordpress.com/theme/illustratr/example.blog
* Sketch links to https://wordpress.com/theme/sketch/example.blog

**Comment by wojtekn** [comment]
I've checked this issue, and I couldn't reproduce it for any listed themes. It would mean that we fixed the problem in the meantime.

I spent some time confirming that - I reviewed the code and the repository history and tracked it down. I see @markbiek  fixed it on May 25th, 2022 for all affected themes:

https://github.com/Automattic/themes/pull/6033/files

D81489-code

It was also reported under https://github.com/Automattic/wp-calypso/issues/55383

I'm closing it as it is not an issue anymore.

**Comment by aetta** [comment]
Hey folks! this seems to still be happening, I noticed this in two themes:

- Adventurer linking to https://github.com/Automattic/themes/tree/trunk/adventurer
- Blank Canvas linking to https://github.com/automattic/themes/tree/trunk/blank-canvas-3

Reproduced on all plans except for Biz.

**Comment by wojtekn** [comment]
@chiape, thanks for reporting it!

I fixed it in https://github.com/Automattic/themes/pull/6969 and deployed (D106978-code)
