### ISSUE TITLE
FSE > Template Part: Adding an option to make site's header and footer to stick

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#62961]
### What

I wish we could implement a way to create sticky headers and footers on block-based themes.

### Why

Help pings to create sticky headers/menus is a common request we get in the CSS Guild, but it is still not possible with Full Site Editing. This feature would give users a feature that is so common across websites.

### How

I'm not sure if that would be something possible to implement for all cases and themes. 

I think adding an option like this to the `Header` and `Footer` would be great:

![Markup on 2022-04-21 at 15:06:07](https://user-images.githubusercontent.com/50875131/164543992-289271c7-8fc7-4f1f-8955-287745aeff95.png)

We will probably need to add some CSS properties like `position, padding, margin, and z-index` to the template parts to achieve this.

**Comment by Greatdane** [comment]
Closing, duplicate issue; https://github.com/Automattic/wp-calypso/issues/61756
