### ISSUE TITLE
Marketplace: Add Yoast upsell to marketing/traffic and /stats

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62977]
We'd like to add an upsell banner for Yoast SEO Premium to:
- Tools -> Marketing -> Traffic
- Stats (/stats/day), replacing the Parse.ly banner

<img width="1130" alt="Screen Shot 2022-07-07 at 2 44 49 PM" src="https://user-images.githubusercontent.com/1689238/177846952-afb33635-faf8-4111-b12a-afa3986bdda7.png">

We'll add the same banner in both places.

If https://github.com/Automattic/wp-calypso/issues/63179 has been fixed, we can use a JITM. Alternatively, since Yoast is a product and not a feature, a feature check may not be appropriate here, but we could possibly check if Yoast is returned by [getSitePurchases](https://github.com/Automattic/wp-calypso/blob/7655b6d1f326371990851da10ebb97f133fbdc17/client/state/purchases/selectors/get-site-purchases.ts#L14).

Acceptance Criteria:
- [x] The banner CTA links to Yoast in the Dotcom Marketplace.
- [x] The link opens in the same window.
- [x] The click is tracked with a unique event.
- [x] The banner matches the Figma: f84fqtCG4pCnCh2Hq0But5-fi-2442%3A33337
- [x] There's a period at the end of "Purchase Yoast SEO Premium to ensure that more people find your incredible content"
- [x] The banner only shows for users who don't already have Yoast SEO Premium installed.

**Comment by vinimotaa** [comment]
Hey folks!

After having a quick chat with Jeremy, I decided to give a crack on the permanent banners for both Traffic and Stats.

![Light mode](https://user-images.githubusercontent.com/97929097/176247228-eda18198-c232-4e2b-8159-f3fc6cebc37e.png)

Let me know your thoughts!

**Comment by vinimotaa** [comment]
I'm also exploring the design for a "spotlight" card for Yoast (and other future big launchings) on Marketplace;

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/97929097/176252520-743e447a-96bd-4962-935c-737104783659.png">


This is what we currently have in place - which I don't think drives much attention;

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/97929097/176252240-df30c526-a03e-4707-b953-6def2e04b04e.png">

Thoughts?

**Comment by jeremyanderberg** [comment]
@vinimotaa I agree! I think for big launches, like this one, we can do a big card like what you've proposed. Inside the marketplace, I might go with the Yoast logo instead of the search icon.. 

@emmnyc85, do you have any further thoughts?

**Comment by emmnyc85** [comment]
@jeremyanderberg - can we get the text to 2 lines? 3 feels like a lot and is a heavy burden for the customer to read

**Comment by jeremyanderberg** [comment]
@emmnyc85 Yes, good call! 

@vinimotaa Can we change the second sentence to: "An array of tools ensures that more people can find your incredible content." 

Let's see how that'll look. Thanks!

**Comment by vinimotaa** [comment]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/97929097/176475111-b007b099-d6d9-4e00-83a8-116284125f93.png">


@emmnyc85 @jeremyanderberg

**Comment by jeremyanderberg** [comment]
@vinimotaa Ah, I meant to say we should keep the first sentence. So the whole thing will read: 

"Yoast SEO Premium is the go-to plugin to optimize your website for search engines. An array of tools ensures that more people can find your incredible content." 

And we can we use the Yoast logo as the icon?

**Comment by emmnyc85** [comment]
Looks great BUT... my feedback below

We need to make Yoast SEO Premium more visible

Change headline to
Increase site visitors with Yoast SEO Premium

Change copy to
Purchase Yoast SEO Premium to ensure that more people find your incredible content

CTA: Learn more (I assume this will go to the product listing page?

**Comment by jeremyanderberg** [comment]
@emmnyc85 Appreciate the feedback! Yes, my intent with the button was to direct people to the product page itself.

**Comment by vinimotaa** [comment]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/97929097/176534672-764db95b-8793-409e-b018-b2520b5e57ca.png">

@jeremyanderberg 
@emmnyc85 

Just keep in mind that the overall sizing (1 line/2 lines) might change once this is implemented.

To @jeremyanderberg's comment on Yoast icon, I had a chat with @SaxonF yesterday on this detail, and we should leave the overall Yoast product branding to its product page. Having something to illustrate the value/function of what we're proposing is more aligned/consistent with the rest of the platform.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/97929097/176535221-e2298162-ca52-46d5-a6e1-538bd0d4088b.png">

I'm placing this here for us to look at it and make a decision, but to me, it feels a lot more "advertising" than "adding a functionality/value to my site". I hope this makes sense

**Comment by emmnyc85** [comment]
Great feedback. @vinimotaa. I recommend the first one so it feels more organic and less like advertising

**Comment by jeremyanderberg** [comment]
@vinimotaa @emmnyc85 I definitely agree. I'd say let's roll with your recommendation there! Thanks for work on this — I think it'll have a big impact.

**Comment by vinimotaa** [comment]
@jeremyanderberg @emmnyc85 cool - let me know if there is anything I can support with!

Just an important reminder - let's make sure these banners (entry points) have been tracked in terms of interaction and conversion. We recently figured out that important nudges for Plan Upgrade haven't been properly tracked, so we can't measure conversion from there either.

Thanks!

**Comment by vinimotaa** [comment]
[Link to Figma file](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=2353%3A25060)

**Comment by allilevine** [comment]
@vinimotaa Just double-checking, is the lack of a period at the end of "Purchase Yoast SEO Premium to ensure that more people find your incredible content" intentional?

**Comment by vinimotaa** [comment]
Good question! @jeremyanderberg thoughts?

**Comment by jeremyanderberg** [comment]
@allilevine @vinimotaa That is a good question. :) Not sure it matters much here, but let's add it in to be safe. Thanks for pointing out!
