### ISSUE TITLE
[E-mails] [New post] Show post shortlink

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#62986]
### What

Request to show the post's shortlink on "New post" email template. The old template does, example:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/18581859/164884622-e4186e93-2756-44fe-977e-f6b7d5880907.png">

The refresh does not show it:

![image](https://user-images.githubusercontent.com/18581859/164884680-4e57ddcb-c1f0-45a8-8b70-9a6ccd055682.png)

### Why

No specific reason given in the customer report, but I guess there are various users that like to type this out on a new device, vs clicking on the post email within the same device they received the email on. In that regard, shortlink helps.

**Comment by arunsathiya** [comment]
Got the request in 5088534-zen.

**Comment by arunsathiya** [comment]
@Automattic/dotcom-triage-pa-group, I'll let you triage as needed, but FYI: I have added it to Apex's Email templates board for now.

**Comment by JessBoctor** [comment]
I had a user come in and request this as well. 35259635-HC. They are specifically looking to be able to see the three most recent posts from a user that has liked their content when they click on a link.

For context, the reason they want this added back in: 

> I have people that come and like some things I have posted and having samples at the bottom lets me find out if I like their writing without have to go separately to the reader.

**Comment by JessBoctor** [comment]
Moved my comment to a new GH Issue, since this is separate from the shortlink issue. https://github.com/Automattic/wp-calypso/issues/62989

**Comment by formosattic** [comment]
Note to @Automattic/dotcom-triage-pa-group: looks like this will need to be transferred to  Jetpack, see https://github.com/Automattic/jetpack/issues/24036.

**Comment by mashikag** [comment]
Hey @mtias ! 👋  What do you think of this request? 

We would need design input if this was to be implemented. Where and how we would like the short link to be included in the email.

**Comment by mtias** [comment]
There's a design proposal that includes it on notification posts as a fallback but it's not finished.

**Comment by mashikag** [comment]
I believe this issue is not of the highest priority so we may as well put it on hold until proper designs including this short link are ready. It would be beneficial if we could assign the ticket to someone who is working/will work on the designs till then, so they could change the status of the ticket once it's ready to be implemented.

**Comment by mashikag** [comment]
The new design dropped the usage of shortlink. Hence closing the issue. @mtias can correct if I am wrong.
