### ISSUE TITLE
Jetpack Search filtering functionality not returning intended results 

### ISSUE THREAD

**Issue by cintacks** [Automattic/wp-calypso#62987]
### Quick summary

Please note: This is possibly site-specific. 

blog.podbean.com has a Jetpack Search widget installed in their sidebar that returns incorrect results based on post type filters. 

- Assumed functionality: filter by `post`, `page`, and `media` would return results matching `post` OR `page` OR `media`
- Actual functionality (on [blog.podbean.com](http://blog.podbean.com/)) appears to be: results returned matching `post` AND `page` AND `media`, which renders nothing.

### Steps to reproduce

1. Login to blog.podbean.com
2. Go to https://blog.podbean.com/wp-admin/widgets.php
3. Uncheck `testimonials` from post type filters under Search (Jetpack) widget
4. Try search term from sidebar widget in frontend (tested with `monetization`)

See screencast for what happens: https://d.pr/v/vyFwma

### What you expected to happen

Assumed functionality: filter by `post`, `page`, and `media` would return results matching `post` OR `page` OR `media`

### What actually happened

Actual functionality (on [blog.podbean.com](http://blog.podbean.com/)) appears to be: results returned matching `post` AND `page` AND `media`, which renders nothing.

### Context

4962512-zd-woothemes

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Could be theme-specific but I don't know.. There are quite a few PHP errors regarding their theme:

Twenty-Seventeen

### Reproducibility

Consistent

### Severity

One

### Workaround details

Enabling all post type filters "fixes" the search results page.

**Comment by rw-ye** [comment]
Another user report here:
5171006-zd-woothemes

**Theme**: Twenty Sixteen

I suggested the workaround by enabling all post-type filters. 

I could also reproduce it on my own test site using a different theme: Toujours

**Comment by KirkwallDay** [comment]
Another instance here: 34536599-hc

**Comment by Greatdane** [comment]
I was able to reproduce but only on mobile view (it worked on desktop)

Issue is with the URL parameters that are added (for example `&post_type=post%2Cpage`)

**Comment by Greatdane** [comment]
cc: @Automattic/jetpack - not sure if you manage the legacy **Search (Jetpack) widget**.

**Comment by jp-imagines** [comment]
Another report in 5241135-zd-woothemes. I was able to reproduce the issue on a site of my own as well (and the "workaround" of enabling all post types does work.)
