### ISSUE TITLE
Plans Redesign: domains and google analytics should use wide layout with new plans page

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6298]
With the new plans page enabled `ENABLE_FEATURES=manage/plan-features make run`
1. Navigate to /plans
2. Toggle between plans, domains, and google ads
Domains and Google Ads headers shouldn't have a smaller header.
<img width="195" alt="screen shot 2016-06-24 at 11 11 56 am" src="https://cloud.githubusercontent.com/assets/1270189/16346498/83abede2-39fc-11e6-915c-ffe437652810.png">

With the new plans page disabled `make run`
1. Navigate to /plans
2. Toggle between plans, domains, and google ads
Plans, Domains and Google Ads should have the same size header.

The Issue in Action:
![layout](https://cloud.githubusercontent.com/assets/1270189/16420193/4ee23aa6-3d05-11e6-85e2-64998e6e5727.gif)

**Comment by lamosty** [comment]
I'm not sure I can reproduce this or maybe I just don't understand what you mean.

This is how Domains tab looks like with plan-features **enabled**:

![selection_026](https://cloud.githubusercontent.com/assets/4988512/16418507/64e0508c-3d4a-11e6-86d4-9c4c9d2b5fdc.jpg)

And this is how it looks like with plan-features **disabled**:

![selection_029](https://cloud.githubusercontent.com/assets/4988512/16418521/7547a704-3d4a-11e6-894b-41238a142b5e.jpg)

Looks the same to me.

Could you please provide some screenshots of the issue?

**Comment by gwwar** [comment]
@lamosty I've added a gif that shows the behavior. Remember that we are using a much wider layout on the new plans page.

**Comment by lamosty** [comment]
I see now. I thought that by saying: 
> Domains and Google Ads headers shouldn't have a smaller header.

you actually mean that the header text is smaller. :D
