### ISSUE TITLE
[E-mails] [New comment] [New like] Should include "Great posts worth seeing from user" paragraph 

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#62989]
### What

The new liked and comments post notifications no longer include a preview of content from the user who is liking or commenting. I had customer come into chat requesting that the `Great posts worth seeing from {user}:` section be added back. Here is a screenshot from the old email notification:

![Great-posts-from](https://user-images.githubusercontent.com/12505355/164945243-caffdc8f-2151-4553-ac14-4846e742c1cb.png)
 
 
 Chat: 35259635-hc

### Why

Here is their specific request: 

>I have people that come and like some things I have posted and having samples at the bottom lets me find out if I like their writing without have to go separately to the reader.

**Comment by formosattic** [comment]
Note to @Automattic/dotcom-triage-pa-group: looks like this will need to be transferred to  Jetpack, see https://github.com/Automattic/jetpack/issues/24036.

**Comment by yansern** [comment]
1. The section is showing, but the posts entries are empty. (Verify if that is the case or the person modified the screenshot). TODO: Find out where the link is.

2. The section doesn't show at all. Find out what are the exact situations, is it because there are no posts, or there are posts but some glitch caused it not to show.

**Comment by fredrikekelund** [comment]
5162715-zen

**Comment by fresatomica** [comment]
Reported here: https://wordpress.com/forums/topic/new-like-notification-email-lacking-vital-information/?view=all

**Comment by formosattic** [comment]
> The section is showing, but the posts entries are empty. (Verify if that is the case or the person modified the screenshot). TODO: Find out where the link is.

Could this be related to https://github.com/Automattic/wp-calypso/issues/62995#issuecomment-1109554544

> The section doesn't show at all. Find out what are the exact situations, is it because there are no posts, or there are posts but some glitch caused it not to show.

I tested by liking and commenting, and made sure that my visitor account had some live posts in its primary site, but still not seeing any section `Great posts worth seeing from {user}:`

| Comment  | Like |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/165273904-49f52ea4-5a9f-4d17-8cf4-87aaa95f7f60.png)  | ![image2](https://user-images.githubusercontent.com/15944096/165273997-65b0f3aa-a2e1-4b8f-8938-de6e6e739c53.png)  |

**Comment by mashikag** [comment]
> 1. The section is showing, but the posts entries are empty. (Verify if that is the case or the person modified the screenshot). TODO: Find out where the link is.

@yansern in the issue description it says:

>  Here is a screenshot from the old email notification:

This would imply this is a screenshot from when it worked properly. This means the user had to modify the picture himself. 🙂

**Comment by mashikag** [comment]
> I tested by liking and commenting, and made sure that my visitor account had some live posts in its primary site, but still not seeing any section `Great posts worth seeing from {user}:`

Can you share with me the site from which you expected the posts to be included in the email? There is multiple criteria that need to be met, just as there used to be, for the posts to be listed.

The site for which you expect its content to be shared in those emails needs to be your user's, you are commetning with or liking with, primary site. Then the site has to be `Public` and has not to be marked as `Discourage search engines from indexing this site`.
![Screenshot 2022-04-28 at 20 19 05](https://user-images.githubusercontent.com/2019970/165820688-f0476e69-fac1-4cbc-9cb2-97195f796ec2.png)

**Comment by sophiegyo** [comment]
Additional feedback from 5164849-zen - screenshots in the ticket show the "great posts worth seeing" section simply doesn't appear in the new template. The user submitting the report wants them back, or an easy way to reach the site of the person who liked/commented on their post. Related: #62992

**Comment by mashikag** [comment]
**Re @yansern:**
> 2. The section doesn't show at all. Find out what are the exact situations, is it because there are no posts, or there are posts but some glitch caused it not to show.

I just had a look, and the new templates do not include the `Great posts worth seeing from user` paragraph at all for "New comment", "Post liked" or "Comment liked" templates. It was neither mentioned in designs. 

@mtias should we just include the paragraph at the bottom of the email's body, just above the footer, or you would prefer for this to go through design first?

**Comment by formosattic** [comment]
+1  5181732-zd-woothemes

> If it included links to the person's blog, as the old one did, I'd be able to pay a return visit--something I'd think you want to encourage.

**Comment by kimerlin81** [comment]
Please update [this affected user](4965283-zd-woothemes) once this has been resolved. Thanks!

**Comment by vinnykaur** [comment]
Another one reported here - zd-5178546

**Comment by mashikag** [comment]
Closing this ticket as the new e-mail templates for "New comment", "Pingback" and "New like" were all reverted for now. The old template is applied for those.
