### ISSUE TITLE
[E-mails] [New comment] [Pingback] Bring back or make it easier to find the commenter's profile and primary site

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#62992]
### What

Context: 4964208-zd-woothemes

> it doesn't include a link to the commenter's own profile or site, it just has their name. This makes it difficult to visit the commenter to reciprocate with my own like or comment. It's especially inconvenient if the notification is for a 'Like'.... the 'Likes' on my post are just a string of Gravatars and I have no idea which Gravatar belongs to which notification.

Note to @Automattic/dotcom-triage-pa-group: looks like this may need to be transferred to Jetpack, see https://github.com/Automattic/jetpack/issues/24036.

### Why

No clear info on the commenter, so author can't easily interact with them.

| Old  | New |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/164971508-a41ee957-ea77-46fb-b006-40718564f2db.png)  | ![image2](https://user-images.githubusercontent.com/15944096/164971504-9715ebba-5b66-4613-987e-7709326160af.png)  |

### How

Bring back, or make it easier to find info that was under `More information about`.

**Comment by isocialtish** [comment]
This also came up in 5163951-zen

**Comment by isocialtish** [comment]
Another instance of a user missing the section with more info about the person commenting: 5164300-zen (this person was using the email address field to then send an email)

**Comment by Babylon1999** [comment]
Another report about this here: zendesk-5162274

**Comment by sstabrizi** [comment]
I have another report of a user requesting the commenters' info back as well. They were using the email address for the commenter to reply without having to view the comments directly. Essentially, it was a time-saver to have it listed in the email.

33627678-hc

**Comment by formosattic** [comment]
Checked this again, it looks like a fix would be to have the Gravatar or user name clickable (see https://github.com/Automattic/wp-calypso/issues/63029), but even so, having the info (commenter's email, primary site) right into the email seems more convenient for blog owners.

![image1](https://user-images.githubusercontent.com/15944096/165255418-c4113ba0-62a0-4127-9aa1-86e1ab5b6821.png)

**Comment by sophiegyo** [comment]
Additional feedback from 5164849-zen - the user submitting the report wants an easy way to reach the site of the person who liked/commented on their post. Related: #62989

**Comment by csabarakasz** [comment]
13657252-hc same feature request here. The user would like to have a quick link to reply to the commenter via their email!

**Comment by metabreakr** [comment]
5164946-zen

**Comment by inaikem** [comment]
@Automattic/dotcom-triage-pa-group, I've added this to our bulk reply board 🙏

**Comment by mashikag** [comment]
I closed the following issue as duplicate: https://github.com/Automattic/wp-calypso/issues/63029

The report was to make the commenter's name/username clickable like it used to be in the previous versions. This relates the "New comment" and "Pingback" emails.

> Previous Email (with commenter hyperlink):
> 
> <img width="788" alt="Markup 2022-04-25 at 18 55 01" src="https://user-images.githubusercontent.com/25855381/165197761-f1152ff8-ca95-4e03-b021-1bd3a8407793.png">
> 
> ![Annotation on 2022-04-25 at 18-56-28](https://user-images.githubusercontent.com/25855381/165197938-19ad6212-ec6f-4dbb-8d74-64dd2b46bb29.png)
> 
> New Email (no clickable username):
> 
> <img width="807" alt="Markup 2022-04-25 at 18 58 06" src="https://user-images.githubusercontent.com/25855381/165198080-0e91009b-f333-49f9-8ca4-f6fa0828de89.png">
> 
> <img width="767" alt="Markup 2022-04-25 at 18 58 42" src="https://user-images.githubusercontent.com/25855381/165198094-c0fedaf9-8d51-44f9-88f6-89633b507907.png">

Note that there was some technical investigation done on the issue too: https://github.com/Automattic/wp-calypso/issues/63029#issuecomment-1117436570

**Comment by ccwalburn** [comment]
A repeat request for this to be fixed 35282567-hc. 
Adding to help increase priority.

**Comment by mashikag** [comment]
Closing this ticket as the new e-mail templates for "New comment", "Pingback" and "New like" were all reverted for now. The old template is applied for those.
