### ISSUE TITLE
[E-mails] [New post] Featured image is not showing

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#62994]
### Quick summary

When a new post is published with a Featured Image, the image does not show in the post content in the email.

Featured Image added:
![CleanShot 2022-04-24 at 15 05 18](https://user-images.githubusercontent.com/84539773/164978144-a7f98b3e-8922-4c64-a0fd-d6e5f15b57eb.jpeg)

Image not included in the mail.
![CleanShot 2022-04-24 at 15 06 43](https://user-images.githubusercontent.com/84539773/164978154-77abe4c9-f3c1-4256-8fe4-c395e7d367b2.jpeg)

### Steps to reproduce

1. Create a new post
2. Set Featured image
3. Publish the new post
4. Email does not contain image.

### What you expected to happen

Image would be in the email content

### What actually happened

Image was not included. 

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No.

### Reproducibility

Consistent

### Severity

All

**Comment by csabarakasz** [comment]
Image not showing 4961553-zd-woothemes
Image not showing 4964624-zd-woothemes AT site, theme: MH magazine

**Comment by formosattic** [comment]
Confirming this is still happening.
![image1](https://user-images.githubusercontent.com/15944096/165263050-7bec5767-1718-41b0-9fdc-fc2718890a5e.png)

Related: https://github.com/Automattic/jetpack/issues/24036

**Comment by mashikag** [comment]
@mtias I checked the designs and there is an image in "New Post" email notification design. However it is not 100% clear to me whether the image is a featured image, or just an image block that is part of the post. I have also put a comment in relation to that in the figma designs. Feel free to reply directly there.

**Comment by mtias** [comment]
@mashikag yes, that's meant to be the featured image or first content image if one is set towards the top of a post.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/548849/166062051-b33abbe0-ec0c-497e-8bec-15e6769b1ef3.png">

**Comment by StefMattana** [comment]
Another potential report here: https://wordpress.org/support/topic/subscriber-emails-no-longer-display-images/
Users can't see images via laptop and mobile (Samsung and iPhone)

**Comment by TonyKent88** [comment]
> Another potential report here: https://wordpress.org/support/topic/subscriber-emails-no-longer-display-images/ Users can't see images via laptop and mobile (Samsung and iPhone)

Hi - I posted another entry to my blog this morning.  The notification email to my iPhone is still not showing any images.  Thanks, Tony

**Comment by StefMattana** [comment]
>Hi - I posted another entry to my blog this morning. The notification email to my iPhone is still not showing any images. Thanks, Tony

I can confirm no images appears also at my end, not even on mobile or desktop (I subscribed to this blog to check that)

**Comment by bobmatyas** [comment]
Another report on 5195389-zen

**Comment by msilbers** [comment]
reported in 32297903-zen that no images show when new post emails go out for the set featured image

**Comment by phcp** [comment]
The patch (D80381-code) fixing this issue is now deployed to production.

**Comment by TonyKent88** [comment]
Hi there - I don't know at what stage this is at in terms of release.  There is no change on my iPhone (i.e. still no images showing).  However, something has changed on my PC.  It is now showing the featured image despite me selecting the post option to only show featured image in the single post view.  This seems to be a recent change by WP so maybe your software has not picked it up.
![IMG_1904](https://user-images.githubusercontent.com/104977772/168098931-9d72181a-04ef-4d50-bb06-abd389500a36.JPG)
![IMG_1905](https://user-images.githubusercontent.com/104977772/168098951-b83a8f9a-6ab5-499f-a6e0-a05c69976be4.JPG)

**Comment by ivan-ottinger** [comment]
Hi Tony 👋🏼 

Thank you for sharing your screenshots and details with us.

> I don't know at what stage this is at in terms of release. There is no change on my iPhone (i.e. still no images showing).

It looks like there was a confusion in regards this specific GitHub issue. The issue was originally targeted at the missing Featured image only. Then there were other reports/comments added on missing images in general. 

To help separate the two issues, I created a new dedicated issue just for the missing images: https://github.com/Automattic/wp-calypso/issues/63604. This will help us keep the discussion specific.

> However, something has changed on my PC. It is now showing the featured image despite me selecting the post option to only show featured image in the single post view. This seems to be a recent change by WP so maybe your software has not picked it up.

The Featured image in the "New Post" email is currently displaying regardless of the any other setting. The `Show featured image in the posts lists only, but hide it in the single post view` setting visible in the screenshot above seems to be coming from a third-party plugin or a theme we don't have control over. However, we may consider investigating a possibility of hiding the Featured image from the "New Post" email when the [Display on single posts](https://jetpack.com/support/content-options/) setting is disabled:
![Markup on 2022-05-13 at 14:42:37](https://user-images.githubusercontent.com/25105483/168285572-3742328a-40db-449b-843b-b43686bee3e1.png)

**Comment by phcp** [comment]
Hey Tony! 

![image](https://user-images.githubusercontent.com/3113712/168291866-29e99965-186f-46e2-a5c3-b4c892f703be.png)

On your screenshot, the featured image overflows the grey area. We can use this issue to follow with additional investigations for this specific bug. Could you let us know which e-mail client did you use in the screenshots?

Thank you!

**Comment by TonyKent88** [comment]
> Hey Tony!
> 
> ![image](https://user-images.githubusercontent.com/3113712/168291866-29e99965-186f-46e2-a5c3-b4c892f703be.png)
> 
> On your screenshot, the featured image overflows the grey area. We can use this issue to follow with additional investigations for this specific bug. Could you let us know which e-mail client did you use in the screenshots?
> 
> Thank you!

Hi - My PC is old so still running Windows 7 with Windows Live Mail 2012.  Thanks, Tony

**Comment by TonyKent88** [comment]
> Hi Tony 👋🏼
> 
> Thank you for sharing your screenshots and details with us.
> 
> > I don't know at what stage this is at in terms of release. There is no change on my iPhone (i.e. still no images showing).
> 
> It looks like there was a confusion in regards this specific GitHub issue. The issue was originally targeted at the missing Featured image only. Then there were other reports/comments added on missing images in general.
> 
> To help separate the two issues, I created a new dedicated issue just for the missing images: #63604. This will help us keep the discussion specific.
> 
> > However, something has changed on my PC. It is now showing the featured image despite me selecting the post option to only show featured image in the single post view. This seems to be a recent change by WP so maybe your software has not picked it up.
> 
> The Featured image in the "New Post" email is currently displaying regardless of the any other setting. The `Show featured image in the posts lists only, but hide it in the single post view` setting visible in the screenshot above seems to be coming from a third-party plugin or a theme we don't have control over. However, we may consider investigating a possibility of hiding the Featured image from the "New Post" email when the [Display on single posts](https://jetpack.com/support/content-options/) setting is disabled: ![Markup on 2022-05-13 at 14:42:37](https://user-images.githubusercontent.com/25105483/168285572-3742328a-40db-449b-843b-b43686bee3e1.png)

Thanks Ivan.  My site uses the Astra theme.

**Comment by ivan-ottinger** [comment]
After evaluating the feedback and considering the options, we have pulled out the change that had added the Featured image to the _New Post_ email notification.

If there's a need to add an image to the top of the email notification, it can be added to the post body directly - using the Image block. This approach maintains flexibility for users that don't wish to have the Featured image displayed in the email notification.

D80920-code | p1652564518537289-slack-C02TCEHP3HA

**Comment by sophiegyo** [comment]
Just dropping feedback here from 35552287-hc that it'd be nice to have the featured image back in the New Post emails. The user has been working around the lack by adding the image into the post body but they'd like to not have to do that.

**Comment by DowswellDigital** [comment]
Adding to @sophiegyo -- my clients were working around the lack before the feature was introduced, and happily backdated a lot of their old post to make use of the featured image again. Going back to them to say the feature had been turned off was a considerable disappointment. This really should be a standard feature and not something to be worked around.

**Comment by rinazrina** [comment]
I got another user who expects the featured image to be displayed on new post notification emails: #5833127-zen

**Comment by Hime100** [comment]
Hi, my jetpack subscriber emails don’t show the images in my blog post if you’re reading the email from an iPhone (not sure about other phones). If you’re on a computer, it seems to work fine. Can you help me … I’ve looked all over trying to find an answer to this issue. I need my subscriber emails to include the images.  It seems to be a jetpack issue not a phone settings issue bc it happens to everyone reading from a phone. Please help.

**Comment by TonyKent88** [comment]
> Hi, my jetpack subscriber emails don’t show the images in my blog post if you’re reading the email from an iPhone (not sure about other phones). If you’re on a computer, it seems to work fine. Can you help me … I’ve looked all over trying to find an answer to this issue. I need my subscriber emails to include the images. It seems to be a jetpack issue not a phone settings issue bc it happens to everyone reading from a phone. Please help.

I have had this problem for almost a year now.  Jetpack say it is a Bluehost / Apple problem.  Bluehost say it's not their problem,  Without any resolution, I will have to look for another subscriber plugin.

**Comment by ivan-ottinger** [comment]
> Hi, my jetpack subscriber emails don’t show the images in my blog post if you’re reading the email from an iPhone (not sure about other phones). If you’re on a computer, it seems to work fine. Can you help me … I’ve looked all over trying to find an answer to this issue. I need my subscriber emails to include the images. It seems to be a jetpack issue not a phone settings issue bc it happens to everyone reading from a phone. Please help.

Hello @Hime100 👋🏼 Thanks for reporting the issue. If your site is hosted with Bluehost, the issue is likely the same as discussed earlier.

If you like, you can try to follow [these steps](https://github.com/Automattic/wp-calypso/issues/63604#issuecomment-1128569715) to confirm the issue is present in _all_ emails that include images hosted on Bluehost when opened on iPhone.

**Comment by pamgrieco** [comment]
@TonyKent88 I just started having this problem myself with my Bluehost Site.  Were you ever able to get a resolution?

**Comment by TonyKent88** [comment]
No.  Bluehost said they were unable to replicate the problem, so I’m stuck.Sent from my iPhoneOn 8 Mar 2023, at 03:52, pamgrieco ***@***.***> wrote:﻿
@TonyKent88 I just started having this problem myself with my Bluehost Site.  Were you ever able to get a resolution?

**Comment by Hime100** [comment]
I haven’t gotten a resolution yet but Wordpress is helping me. We’re testing a privacy setting on iPhone to see if that changes anything. 

Does anyone know if the subscriber images show up in a gmail on the gmail app?

**Comment by TonyKent88** [comment]
I tested the privacy setting and no change.The photos do not display in gmail either.Sent from my iPhoneOn 8 Mar 2023, at 15:24, Hime100 ***@***.***> wrote:﻿
I haven’t gotten a resolution yet but Wordpress is helping me. We’re testing a privacy setting on iPhone to see if that changes anything.
Does anyone know if the subscriber images show up in a gmail on the gmail app?

**Comment by pamgrieco** [comment]
ios Mail app - but a gmail acct, no pictures
gmail app - pictures appear
logging into gmail on Safari, Edge - pictures appear
ios Mail app - Yahoo acct - no pictures
ios Mail app - outlook acct - no pictures

**Comment by Hime100** [comment]
Here’s the latest email from Wordpress below  … I feel like I’m at a dead end bc I can’t do all of this. If someone else wants to try, let me know if you find out anything. Also I’m using the AshePro theme in WP. Are any of you using that theme or different themes? Was wondering if that’s causing it? 
…

Hi again Jaime,
 
Thank you for checking your settings and confirming the issue.
 
I tried to reproduce the issue on my site. I activated Image Accelerator and uploaded images to my new post body. I then checked the blog subscription newsletter in my Mail client on my desktop, my mail client on my iPhone, and my Gmail account. They appeared correclty in each case.
It looks like something specific to your setup plays its role here.
 
Is there something else to try?

 
Testing that further on your live site seems complicated, as it may affect your subscribers. I would recommend creating a staging copy of your site. If your host doesn't offer that option, we recommend the free [WP Staging plugin](https://wordpress.org/plugins/wp-staging/) for quickly spinning up a new test site. 
Once you staging site is set up, please create a new Jetpack connection and subscribe to your site with your email address.
As the next step, deactivate all plugins except Jetpack and switch your theme to one of the default Twenty themes (for instance, Twenty Twenty-One). 
Publish a new post with images, and check your emails. Please let us know how it goes.
 
Thank you. We will be standing by for your response.
Best regards,

Pajka

**Comment by chuckpearson** [comment]
I am having the same issue where the featured image is not being included in the Jetpack email newsletter even though the option to include it is enabled in JP > settings > newsletter. Is there a fix for this yet?
