### ISSUE TITLE
[E-mails] [New post] Post content either missing new lines or excessive new lines or whitespace.

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#62990]
### Quick summary

Following the visual refresh, see pdDOJh-fZ-p2, the blank lines in a comment are being skipped/eaten in the email notification.

Note to @Automattic/dotcom-triage-pa-group: looks like this will need to be transferred to Jetpack, see https://github.com/Automattic/jetpack/issues/24036.

### Steps to reproduce

1. Enable comment notification on a test site
2. Comment on a post with some blank lines

### What you expected to happen

The blank lines should be reflected in the email notification.

### What actually happened

The blank lines are removed, the text shows as in big paragraph.

| Expected  | What happened |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/164953215-ce44b3df-b553-4c21-a4ea-e41a5fd29b22.png) | ![image2](https://user-images.githubusercontent.com/15944096/164953126-ec8cba05-2025-49c1-8e18-db5865e57e47.png) |

### Context

User report: 5162465-zd-woothemes

**Comment by yansern** [comment]
Similarly, review post content paragraph / line-break parsing/styling. pdDOJh-fZ-p2#comment-175

**Comment by sophiegyo** [comment]
Possibly related - missing external link "button" in the new post email. Reported in: 5182954-zen

User report includes two screenshots showing 1) missing author Gravatar and 2) missing Patreon link.
The Patreon link (and normal Gravatar) can be seen in the post in the Reader:
https://wordpress.com/read/feeds/98177303/posts/3986875636

**Comment by christianguerrag** [comment]
Another report of this happening in 5580972-zen

**Comment by mashikag** [comment]
We are suspecting an issue where third party plugin block results in strangely formatted html. 

Next person picking up the issue should explore the different cases in the mentioned tickets above.

If the issue relates to verse plugins, maybe suggests usage of our verse block.
