### ISSUE TITLE
Email template refresh: Remove "Comment" & "Like" button when Comments, Likes are disabled 

### ISSUE THREAD

**Issue by sourourn** [Automattic/wp-calypso#62997]
### What

User has disabled comments on all posts. However when they publish a new post, there is a "comment" button that shows at the bottom of new post notifications. See screenshot: https://d.pr/i/hhRc54

### Why

User would like to not show the option to comment anywhere on the post, including in the post notification email. Right now when someone clicks on "Comment" it leads to the full post but there is no comment section.

**Comment by yansern** [comment]
Also disable like button when like is disabled.

**Comment by jeherve** [comment]
Also in 

4963821-zd-woothemes
4962551-zd-woothemes
4962942-zd-woothemes

**Comment by mashikag** [comment]
This issue was addressed in D79437-code and should be now resolved

**Comment by shykonessy** [comment]
Hello the comment button is still on the email templates, kindly forward the issue to the team working on the email designs to assist to remove it, or have it a less boldened at the bottom of the templates. Thanks
