### ISSUE TITLE
Email template visual refresh: Link to gravatar

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#62999]
### Quick summary

The new liked and comments post notifications no longer link the user profile picture of the user who is liking or commenting to their Gravatar profile. 

![image](https://user-images.githubusercontent.com/81776920/165024302-88415029-897e-4e24-93d0-abfc3ebdaa7a.png)

### Context

Had a user in 32722498-hc mentioning that there is no way to learn more about the subscriber from the emails. 
This is amplified by #62989

**Comment by yansern** [comment]
Marking as duplicate of https://github.com/Automattic/wp-calypso/issues/62996
