### ISSUE TITLE
[E-mails] Commenter's language being used in New Comment mail.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#63004]
See pdDOJh-fZ-p2#comment-172

**Comment by zdenys** [comment]
I'm not 100% sure this is related, but it's the closest match I found. In 5196787-zd-woothemes the user reports that for New post notification email, the subscription shortcode `[blog_subscription_post]` is rendered in Russian, despite the rest of the content being in English.
![image001](https://user-images.githubusercontent.com/39308239/167248036-9778a37a-193c-46dd-a2e0-27fa4cefba5a.png)

**Comment by zdenys** [comment]
Upon our recommendation, the user from the [above's comment](https://github.com/Automattic/wp-calypso/issues/63004#issuecomment-1120173813) (5196787-zd-woothemes)  changed their shortcode block `[blog_subscription_post]` with the [Subscribe Block](https://wordpress.com/en/support/wordpress-editor/blocks/subscribe-block/). Nevertheless, the issue remains as the content is still rendered in Russian despite the rest of the content being in English:

![image](https://user-images.githubusercontent.com/39308239/168416785-013fabe4-762b-46a1-8611-aa4e68ffacd9.png)

---

In addition to that, the [Subscribe Block](https://wordpress.com/en/support/wordpress-editor/blocks/subscribe-block/) is not rendered properly/nicely in the notification email (compared to the frontend).

Frontend | Notification email
--- | --- 
![image](https://user-images.githubusercontent.com/39308239/168416936-4dba7902-99c3-4eef-a008-0146852ec1ec.png) | ![image](https://user-images.githubusercontent.com/39308239/168416959-c613f1b4-7a52-41db-8906-7ba0f0476b1d.png)

Reported here:

- https://github.com/Automattic/wp-calypso/issues/63628

**Comment by mashikag** [comment]
Closing this ticket as the new e-mail templates for "New comment", "Pingback" and "New like" were all reverted for now. The old template is applied for those.
