### ISSUE TITLE
Theme: Hemingway Rewritten code editor text is white, rendering it "invisible"

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#63007]
### Quick summary

The Block Editor's Code Editor View's `textarea` content is styled as white, leading to text appearing invisible to users unless highlighted.

### Steps to reproduce

1. Install Hemingway Rewritten on an Atomic site
2. Open a page or post and click into the Code Editor View.
3.  Enter text. The text is white.

### What you expected to happen

I expected the text to be grey.

### What actually happened

I the text is white, making it "invisible" unless highlighted.

### Context

User interaction: 5164630-zd-woothemes

I tested on the above site, as well as a test Atomic site and could replicate the report.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Hemingway-Rewritten

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
It looks like the user switched to Baskerville 2.

I tried to replicate this but I wasn't able to in the end. I believe this may have been a combination of colors/settings or a plugin causing this, but I know we also have this which is slightly related: 

https://github.com/Automattic/themes/issues/3480

I'm going to close this one for now as the theme is also retired.
