### ISSUE TITLE
[E-mails] [New post] Missing tags

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#63002]
See https://wordpress.com/forums/topic/new-format-for-emailed-blog-entries-missing-tags/.

**Comment by mashikag** [comment]
Another report [here](https://github.com/Automattic/wp-calypso/issues/63152#issuecomment-1113731001).

**Comment by mashikag** [comment]
The new design of the email template has dropped inclusion of the tags. 

cc @mtias  for awarness
