### ISSUE TITLE
Plans: new Plans Page Jetpack FAQ

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6300]
With the new plans page enabled `ENABLE_FEATURES=manage/plan-features make run` make sure that the we have Jetpack specific FAQ content for Jetpack sites.

1. Navigate to `/plans` 
2. Switch to a Jetpack Site
3. Examine FAQ content

If FAQ content is not ready, disable wpcom FAQ from rendering. Also see: p1HpG7-3na-p2

**Comment by gwwar** [comment]
cc @rickybanister

**Comment by lamosty** [comment]
@bubel:
> I can start working on this for you; is Monday or Tuesday okay to have some copy?

What's the status of this? :) Should I disable the FAQ from rendering for Jetpack sites or is there some FAQ content ready (or will be)? Thanks!

**Comment by bubel** [comment]
@lamosty Working on these today, should have content ready tomorrow.

**Comment by bubel** [comment]
@lamosty I have some FAQ content ready to go. What shall I do with it?

**Comment by lamosty** [comment]
@bubel great! Well, if you feel like it, you can add it to code. If not, just send me the content on Slack and I'll do it. :)
