### ISSUE TITLE
Plans: Jetpack Monthly and Annual Plans Toggle

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6301]
With the new plans page enabled `ENABLE_FEATURES=manage/plan-features make run` make sure that we have some way of toggling between monthly and annual plans Jetpack plans.

1. Navigate to /plans
2. Switch to a Jetpack Site

The current plans page uses a link toggle, but @rickybanister may have some better ideas.
<img width="823" alt="screen shot 2016-06-24 at 11 25 55 am" src="https://cloud.githubusercontent.com/assets/1270189/16346877/7660c052-39fe-11e6-8b85-865a999e3282.png">

**Comment by rickybanister** [comment]
cc @johnHackworth 

Here's my ugly mockup:

<img width="718" alt="screen shot 2016-06-21 at 2 49 25 pm" src="https://cloud.githubusercontent.com/assets/437258/16347150/2e43b138-3a19-11e6-98b8-395428836c95.png">

**Comment by gwwar** [comment]
Thanks @rickybanister. What does the non-toggled state look like?

**Comment by rickybanister** [comment]
You mean when the select menu is not open? It would just self-label with the selected item and say 'Billed Monthly' (or Yearly).

**Comment by gwwar** [comment]
@rickybanister To clarify, what I clicking that's displaying a dropdown?

**Comment by rickybanister** [comment]
It would always be a dropdown. 

This is only for the Jetpack plans at this point.

**Comment by rickybanister** [comment]
After further discussion, we're going to try a segmented control for this:

![img_6136](https://cloud.githubusercontent.com/assets/437258/16383533/84d29744-3c53-11e6-8737-4eb22d5aa2e1.JPG)

**Comment by rickybanister** [comment]
cc @roccotripaldi can we implement this instead of the solution in #7276?

**Comment by rickybanister** [comment]
This toggle should also appear on the plans page when it appears in the Jetpack Connect flow.

**Comment by roccotripaldi** [comment]
> cc @roccotripaldi can we implement this instead of the solution in #7276?
yeah, sure thing @rickybanister

**Comment by johnHackworth** [comment]
@tyxla  is going to take this issue, so if you are ok with it, @gwwar , I'm going to change the milestone to 'Jetpack NUX m1' so it's easy for us (luna) to track it :)

**Comment by gwwar** [comment]
>  I'm going to change the milestone to 'Jetpack NUX m1' so it's easy for us (luna) to track it :)

Go for it 😄

**Comment by tyxla** [comment]
The new toggle is live: https://github.com/Automattic/wp-calypso/pull/7402.
