### ISSUE TITLE
Plans Redesign: new Plans NUX

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6302]
With the new plans page enabled `ENABLE_FEATURES=manage/plan-features make run` walk through the new user flow.

1. As a logged out user navigate to /start
2. Follow steps
3. On plans page make sure we see the new plans pge, and that flows work well. ( Free plan should be an option in this flow ).

**Comment by gwwar** [comment]
On the plans may see 3 or 4 plans. We see 3 when the user has chosen a domain, and 4 when we pick a free subdomain.

**Comment by lamosty** [comment]
Fixed by #6376.
