### ISSUE TITLE
WP-Admin shows plan expiration banner for monthly plans

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#63027]
### Quick summary

Monthly business plan customers are seeing a notice about plan expiration in WP-Admin, which is misleading as auto-renew is enabled then, in this case, the customer just renewed a couple of days ago. 

#5162147-zen
#5165138-zen

1. Have a site on a monthly biz plan 
2. Check renewal notice on WP-Admin pages

### What you expected to happen

I expect the notice to not be there, per: https://wp.me/p7DVsv-9l8

> Monthly Business plan customers are excluded from this because their renewal date is always one month out

There is another report on that same post from today, so might be a new bug?

### What actually happened

The expiration notice still shows:
![Markup on 2022-04-25 at 15:42:55](https://user-images.githubusercontent.com/41035049/165186550-621b8ad8-3bbb-4a4b-bf89-1d6c8d34623b.png)
 

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

**Comment by DustyReagan** [comment]
This should be fixed and rolling out to production soon with 921-gh-Automattic/wpcomsh.
