### ISSUE TITLE
[E-mails] [New Comment] [Pingback] Make commenters' name/username clickable like it used to be in previous versions.

### ISSUE THREAD

**Issue by sstabrizi** [Automattic/wp-calypso#63029]
### What

Some users would like the username of the commenter to be clickable like it use to be in previous versions. 

### Why

This is a convenience feature and was useful to see information about the individual that commented on the site.

### How

Previous Email (with commenter hyperlink):

<img width="788" alt="Markup 2022-04-25 at 18 55 01" src="https://user-images.githubusercontent.com/25855381/165197761-f1152ff8-ca95-4e03-b021-1bd3a8407793.png">

![Annotation on 2022-04-25 at 18-56-28](https://user-images.githubusercontent.com/25855381/165197938-19ad6212-ec6f-4dbb-8d74-64dd2b46bb29.png)

New Email (no clickable username):

<img width="807" alt="Markup 2022-04-25 at 18 58 06" src="https://user-images.githubusercontent.com/25855381/165198080-0e91009b-f333-49f9-8ca4-f6fa0828de89.png">

<img width="767" alt="Markup 2022-04-25 at 18 58 42" src="https://user-images.githubusercontent.com/25855381/165198094-c0fedaf9-8d51-44f9-88f6-89633b507907.png">

**Comment by sstabrizi** [comment]
This was reported in 33627678-hc and 5167888-zen.

**Comment by formosattic** [comment]
This is closely related to the request of making it easier to find the commenter's email and primary site in https://github.com/Automattic/wp-calypso/issues/62992 , but will keep this separate right now as this is more specific.

Related: https://github.com/Automattic/jetpack/issues/24036

**Comment by lakellie** [comment]
Another user report in 5172602-zen

**Comment by mashikag** [comment]
The link on the username used to point to a user's "Web address", that can be set at their wpcom user's setting.
![Markup 2022-05-04 at 16 53 14](https://user-images.githubusercontent.com/2019970/166708894-81c4cc18-34d3-4d78-af6a-7300e82f0170.png)

As part of investigating the issue we also noticed that the username was displayed as an anchor even, when they had no web address set at their wpcom profile. This is a minor issue but could also be addressed if this was to be done.

Now, question to you @mtias. If we were to make the username an anchor, this would mean that now there would be three anchor's in the entry paragraph like so:
![Screenshot 2022-05-04 at 16 58 52](https://user-images.githubusercontent.com/2019970/166709611-88499209-1b8d-468f-8949-d81adc6d1886.png)
I believe this should be addressed by a designer first.

It is also worth to mention that people are asking for another paragraph to be added to the "New Comment" emails in [this issue](https://github.com/Automattic/wp-calypso/issues/62989). The paragraph is meant to add a way for the comment receiver and the comment author to connect with each other, just as the link does.

**Comment by mashikag** [comment]
I just noticed this issue is very closely related to the following issue: https://github.com/Automattic/wp-calypso/issues/62992. 

I am closing this issue as a duplicate of https://github.com/Automattic/wp-calypso/issues/62992. The https://github.com/Automattic/wp-calypso/issues/62992 issue is more generic, and creating a fix for it should address the reports of this issue too.
