### ISSUE TITLE
Design pickers: Mobile web design picker should show mobile designs as default, not desktop

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#63031]
# Description

Currently, the Design Picker on mobile web shows desktop thumbnails.  We should be showing mobile layouts.  I think this means we need to generate mShots preview for a mobile viewport. See 42PgVsdlQ1v2wpk6lmmrnq-fi-1697%3A54129

### Current (before)
Note the preview on the right shows the mobile layout.  
<img width="392" alt="image" src="https://user-images.githubusercontent.com/5665959/165206214-be0acf3f-76b4-4dae-bf56-0428b92e04ca.png">

### Desired (after)
Similar to this design of the v13n Design Picker #62237
<img width="743" alt="image" src="https://user-images.githubusercontent.com/5665959/165206408-e1887a97-3ea0-4e13-9016-a6103d1155f2.png">

# Acceptance Criteria
- [x] Increase mobile thumbnail height of existing design picker to match with the one in the v13n design picker.
- [x] In both design pickers, on mobile resolution the thumbnail images should be of mobile designs.
- [ ] Tested on real mobile device - ask Autumn or Zach or HE for informal testing as needed
- [ ] Design review & approved by @saygunnyc 

# Dev Tasks

- [x] https://github.com/Automattic/wp-calypso/pull/63603
- [x] https://github.com/Automattic/wp-calypso/pull/63653

**Comment by arthur791004** [comment]
@taipeicoder @autumnfjeld Do you have more details for “Increase mobile thumbnail height of existing design picker to match with the one in the v13n design picker.” I'm not sure it's which part in the Figma 🤔

**Comment by autumnfjeld** [comment]
Ahhh ha. @arthur791004  I was literally writing the same time you posted the message above.
@arthur791004 & @taipeicoder please ask at @saygunnyc  to review this.  He'll be able to off any further details or let you know that it satisfies what he wants.

@zachspears you could also give this a spin on a mobile device.   We are changing the design picker on mobile so it shows mobile previews of the designs (before it showed desktop previews on mobile devices, which of course makes no sense.) :)

Feedback can be posted in the comments of this issue.

**Comment by autumnfjeld** [comment]
And remember to test on real mobile devices. 📱

**Comment by taipeicoder** [comment]
@arthur791004 I think this is the note where @saygunnyc talks about increasing the height to show more of the design:
![Screen Shot 2022-05-16 at 2 26 14 PM](https://user-images.githubusercontent.com/797888/168532228-46a8a1f4-0119-4338-9f68-2f708052e189.png)

You can also watch the 2022-04-26 cross-discipline sync around 39:00 where Saygun provides more context about increasing the image to be square:
![Screen Shot 2022-05-16 at 2 30 52 PM](https://user-images.githubusercontent.com/797888/168532499-bc9483ef-01b4-46e5-8dce-904df95ef439.png)

**Comment by arthur791004** [comment]
@saygunnyc After the adjustment, the UI of the Static Design Picker doesn't look like the Figma and the user might only see **1** design in the viewport rather than **1+** designs. The reason is as followed
* We have the categories selector
* The description “Choose a starting theme. You can change it later.” might probably break into two lines because we're using `-apple-system` instead of `SF Pro Display` (looks like we don't use `SF Pro Display` in WP.com). Even if we use the same font, the issue might still occur in different languages.

| Generated Design Picker | Static Design Picker |
| - | - |
| ![image](https://user-images.githubusercontent.com/13596067/168574407-c8571e66-f260-45c3-ab22-7faa98d77c10.png) | ![image](https://user-images.githubusercontent.com/13596067/168569959-510a673f-eebc-4ba2-bda9-f18b164d113a.png) |

**Comment by saygunnyc** [comment]
Hey there all!
@taipeicoder Thank you for jumping ahead and pulling in the right design from Figma! 🙌 
@arthur791004 Great work! And thank you for all the details provided. Generated Design Picker looks good.

I wasn't actually intending to redesign Static Design Picker, as @SaxonF is currently designing it. 😃 
@SaxonF do you see an issue in shipping the Static Design Picker as shared above? Maybe we can find a better place for a filter icon that could trigger a more robust filtering interface _–as in your initial designs._ so we can save that real estate for displaying more designs?

**Comment by SaxonF** [comment]
@saygunnyc @taipeicoder I don't see any issue pushing this but might want to monitor post release via Full Story to make sure people are scrolling on mobile.

**Comment by arthur791004** [comment]
Close it as it's shipped 🚢
