### ISSUE TITLE
Plans Redesign: new Plans site creation

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6303]
With the new plans page enabled `ENABLE_FEATURES=manage/plan-features make run` walk through the adding a new site to an existing user.

1. Click on this button at the bottom left of the screen
<img width="271" alt="screen shot 2016-06-24 at 11 32 42 am" src="https://cloud.githubusercontent.com/assets/1270189/16347046/673a4e76-39ff-11e6-8bd6-2b108b944002.png">
2. Walk through the new site flow
3. On the plans page make sure we see the new plans page. (Free site should be an option here)

**Comment by lamosty** [comment]
I'm trying this from `add/plan-features-nux` branch (#6376) and it looks/works almost good except that it works with the last selected site's data. E.g., when I had a Premium site selected before clicking on "Add new WordPress", this is what happens in the flow:

![selection_022](https://cloud.githubusercontent.com/assets/4988512/16564838/056129e6-420a-11e6-9ee4-43b1203c180c.jpg)

This when a Business site was selected:

![selection_023](https://cloud.githubusercontent.com/assets/4988512/16564854/155c5730-420a-11e6-9038-5707ed01edab.jpg)

I'll create a new PR on top of #6376 and will fix this.

**Comment by lamosty** [comment]
Closing in favor of #6302.
