### ISSUE TITLE
Plan Checkout: remove intervalType from url

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6304]
#### Steps to reproduce
1. Starting at URL: /plans
2. Upgrade to Business or Premium Plan
3. View Receipt
4. Click 'Back to my site' headerCake
5. End up in plans page nowhere loading infinite stuck place with `:intervalType` in the url undefined

#### What I expected

I expected to go back to my site

#### What happened instead

I got a non-state error

This is related to the changes to Jetpack plans offering monthly or yearly billing options. I don't think the interval belongs in the url, we should probably fetch your interval choice from the database and load a placeholder until we know what type of plan you purchased. I did a drawing of a dropdown selector on the plans to toggle between monthly/yearly instead of the current global toggle link that was hacked in by @bubel. 

CC @rralian @johnHackworth

**Comment by bubel** [comment]
The interval enters play with you toggle the "monthly" plans for a Jetpack site (.../plans/monthly/...), but this should probably be completely ignored for that link and removed from the URL - for wpcom and Jetpack purchases alike (the same error described here happens for Jetpack sites, as well). I don't see it being necessary there; but @eoigal wrote the code, so he may be best to comment.
