### ISSUE TITLE
My Plan: plans sectionNav should link to My Plan

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6305]
#### Steps to reproduce
1. Starting at URL: /domains/manage/
2. Click 'Plans' in sectionNav
3. End up on plans comparison with 'Plan' in sidebar highlighted
4. Click 'Plan' in sidebar, end up on My Plan page
5. You can no longer access the Domains or Google Apps page

#### What I expected

I expected inter-navigability between pages within a 'section'. At the very least, clicking 'Plans' in the sectionNav should take me to the same place as clicking 'Plans' in the sidebar. 

#### What happened instead

See for yourself

cc @rralian @mtias

**Comment by lamosty** [comment]
I think this was fixed by @mtias in #6622. Can you confirm, please?

**Comment by rickybanister** [comment]
Yes it is, this will be closed by #6622
