### ISSUE TITLE
[E-mails] [New post] RTL subscription emails sent LTR aligned

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/wp-calypso#63063]
### Quick summary

Since the redesign of subscriptions, new post emails sent in Hebrew (Right to Left) are sent Left to Right

### Steps to reproduce

1. Set blog language to Hebrew
2. Add Hebrew language content to post
3. Observe that new post email is sent with improper text direction

### What you expected to happen

Emails should respect proper RTL/LTR direction based on site's language setting

## Post:
<img width="763" alt="Screenshot on 2022-04-26 at 13-50-04" src="https://user-images.githubusercontent.com/45246438/165361653-ea77587b-ac8a-4b19-aba3-2c6720bee41c.png">

## Email:

<img width="648" alt="Screenshot on 2022-04-26 at 13-49-33" src="https://user-images.githubusercontent.com/45246438/165361684-0e3def18-9d91-466e-aaf2-e724f34f0a28.png">

### Context

Reported via forums: https://wordpress.org/support/topic/hebrew-email-arrived-ltr-aligned-instead-of-rtl/?view=all

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by mashikag** [comment]
~~Seems like it is not a regression. Old e-mail templates used to behave the same way (given my RTL setup is correct). Never-the-less it is an issue that should be addressed.~~

~~Here is my sample Hebrew site post:~~
![Screenshot 2022-05-08 at 09 38 57](https://user-images.githubusercontent.com/2019970/167286647-9ae3a30b-be00-4442-b8b2-0db7b8f533e8.png)

~~Here is "New post" old template e-mail:~~
![Screenshot 2022-05-08 at 09 38 45](https://user-images.githubusercontent.com/2019970/167286659-44eaf71a-50ca-4a1a-88d5-373b0dbac9ea.png)

**Comment by mashikag** [comment]
I was wrong with the above message. There was an RTL implementation in the old e-mail templates. 

![Screenshot 2022-05-08 at 11 08 48](https://user-images.githubusercontent.com/2019970/167289467-48acaf40-ab56-4069-bdea-880bbadc2063.png)


However if the "New post" e-mail is sent to an e-mail address associated with a wpcom user, the locale settings of the user will be used, incl. LTR/RTL. 
Otherwise if there is no user associated with the email account the "New post" e-mail is sent to, the locale of the blog will be used.

This is why I got the above old e-mail template in LTR - because the e-mail address I sent it to was associated with a wpcom user whose locale (en) uses LTR.

**Comment by mashikag** [comment]
More in depth issue investigation: pdWOS1-B-p2

**Comment by mashikag** [comment]
Fixed in: D80544-code

**Comment by drorsnir** [comment]
@mashikag, thanks!
As I don't know your process - when are fixes deployed?

**Comment by mashikag** [comment]
@FreedomFighterSparrow so sorry to reply only now! I just remembered you asked the question. 🙈 

The fix is already deployed. 🙂

**Comment by drorsnir** [comment]
@mashikag, thank you! I'm very happy to hear that.
Compared with what I'm used to, this is an extremely fast response :-)

**Comment by drorsnir** [comment]
Also, I have to say this has been a great experience, from start to finish - from @bobmatyas responding to my initial forum question, debugging and starting this very clear issue - to the very prompt resolution by you. Thank you, guys!

**Comment by drorsnir** [comment]
Hi,
Unfortunately, the latest email still arrived LTR-aligned - any idea what could be wrong? Is there a setting missing on my end? Thanks!

![Screenshot 2022-06-12 at 10-04-14 פוסט חדש והימים ימי ראשית הקיץ ומה אתם יודעים על הזכויות שלכם - dror snir@kolzchut org il - Kol-Zchut Ltd  (CIC) Mail](https://user-images.githubusercontent.com/3416107/173221649-6fb3e15c-fdad-489a-b19b-7c36aae12378.png)

**Comment by mashikag** [comment]
> any idea what could be wrong? Is there a setting missing on my end? Thanks!

Hi again! 😃  The subscription e-mail was sent to an e-mail address associated with a wpcom address? If so what is the user's language preference?

<img width="1027" alt="Screenshot 2022-06-12 at 11 47 32" src="https://user-images.githubusercontent.com/2019970/173227492-ccb7b4e9-181e-4fc5-a156-fbbb5a62d893.png">
 

Subscriber's language preferences override language site's preferences.

**Comment by drorsnir** [comment]
No, it's a general google group as well as some other non-wp users.

By the way, even though that's changing backward comptability - why does it make sense to align the mail according to the user's language? I understand aligning the "frame" of the email, but not the headline and the text itself.

**Comment by mashikag** [comment]
> why does it make sense to align the mail according to the user's language?

Very good question. I am not able to answer this myself. I share your point of view. I tried not to question the implementation, instead I just ensured the RTL styling is applied to the new e-mail templates the same way it was applied to the old ones. I am not RTL user myself, and it is hard for me to argue about this one. 

Never-the-less we have an issue that the RTL styling is not applied at all as per what you say. Let me recap on the logic that is used to determine whether RTL e-mail styling should be applied for "New post notification" e-mails.

**If** the destination e-mail belongs to wpcom user and they have their language preferences set, then apply RTL only if the language is set to one that is considered RTL.
**Else if** the site, of the new post, has `Language` configuration set in `General settings` then use the one.
**Else** apply `EN GB` as default, i.e. LTR.

If it seems like the above logic is not being applied correctly then is there any chance you, @FreedomFighterSparrow, could share with me the url of the site where this happens?

**Comment by drorsnir** [comment]
You're right, it's best not to open a wider front...

Our blog is here: blog.kolzchut.org.il
It seems like the language is correctly set:
![image](https://user-images.githubusercontent.com/3416107/173398806-2bedf4e7-447f-40b9-b62d-ce8b52ecfd39.png)

Looking at the email's source, I do not see any dir/direction/lang instructions anywhere - please find attached (files renamed as .txt to bypass GitHub's restrictions):
[blog_post_notification.html.txt](https://github.com/Automattic/wp-calypso/files/8892878/blog_post_notification.html.txt)
[blog_post_notification.eml.txt](https://github.com/Automattic/wp-calypso/files/8892937/blog_post_notification.eml.txt)

Thank you for your help!

**Comment by drorsnir** [comment]
Hi @mashikag, any updates on this? Can this issue be reopened? Thank you!

**Comment by sharonlaker19** [comment]
I have another report of the emails showing LTR in 5313948-zen.

**Comment by mashikag** [comment]
Hi @FreedomFighterSparrow and @sharonlaker19 ! 👋 

I am sorry again @FreedomFighterSparrow for taking so long to reply on the issue. I was kept extremely busing working on another feature. 

Let's re-open the issue and I will investigate it first thing tomorrow.

**Comment by drorsnir** [comment]
Thank you, @mashikag :-)

**Comment by mashikag** [comment]
@FreedomFighterSparrow Thanks for sharing the blog with me! 🙇  I confirm that I can reproduce the issue with your site. I am looking into the issue now. 👍

**Comment by mashikag** [comment]
Fix patch created: D83276-code.

I will close this issue once the above patch is reviewed, tested, merged and deployed.

**Comment by yansern** [comment]
This patch is now merged & deployed.

**Comment by drorsnir** [comment]
Thank you, guys! We will test soon :-)

**Comment by drorsnir** [comment]
As far as I can tell, this is working well now. Thank you very much!

**Comment by mashikag** [comment]
> As far as I can tell, this is working well now. Thank you very much!

Great to hear @FreedomFighterSparrow ! :)
