### ISSUE TITLE
FSE Template Parts: On mobile viewport, long usernames run over "actions" button

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#63062]
### Quick summary

In the Template Parts list in the FSE, if you have a longer username, it will run over the three-dots "actions" button on mobile viewports.

The button is still clickable, it's just hard to see.

![Screen Shot 2022-04-26 at 11 51 45 AM](https://user-images.githubusercontent.com/26772342/165354109-945ed552-068b-4606-abab-37978884c1e6.png)

### Steps to reproduce

1. Go to the site editor
2. Go to Template Parts (from nav sidebar)
3. Have a long username (you can just update the DOM directly in dev tools if needed).

### What you expected to happen

Some kind of clipped `overflow-x` style here. I think its more important to clearly show the actions button rather than the full username.

### What actually happened

The user name runs over the actions button.

### Context

An E2E test found this, actually!

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Chrome

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

There is no user impact

### Workaround details

Button still actionable, just hard to see!

**Comment by Greatdane** [comment]
Also replicable on self-hosted sites.

Created a Core Gutenberg Issue here; https://github.com/WordPress/gutenberg/issues/40673

**Comment by Addison-Stavlo** [comment]
closing since the core issue has been resolved
