### ISSUE TITLE
FSE: Site Editor page title incorrect in Calypso

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#63078]
### Quick summary

When you load the site editor on a simple site/in calypso the page title (what you see in the browser tab) shows incorrectly, it is labeled as 'new' rather than 'site editor' 

This just happens on Simple sites as Atomic sites are directed towards `wp-admin` page, while simple stays as `https://wordpress.com/site-editor/SITENAME`

Calypso;

<img width="911" alt="Markup 2022-04-27 at 15 19 47" src="https://user-images.githubusercontent.com/5075840/165454019-2144e681-3d83-4d76-bc5c-9495138d5ca5.png">

WP-Admin;

<img width="1247" alt="Markup 2022-04-27 at 15 20 26" src="https://user-images.githubusercontent.com/5075840/165454047-e7f1578e-0e5d-42f7-89e4-3f9591322f4a.png">

### Steps to reproduce

1. On a Simple Site, go to the site editor with an FSE enabled theme
2. The URL should be `https://wordpress.com/site-editor/SITENAME`
3. The title of the page will show as `New < SITENAME`, rather than `Editor (beta) < SITENAME` like wp-admin does.

### What you expected to happen

The title should be more descriptive to what the site editor/page actually does. It should at the least be the same title as `wp-admin` (which is `Editor (beta)`

It is confusing when you see 'new' - you might think you are creating a new page/post rather than in the site editor. 

### What actually happened

The title of the page will show as `New < SITENAME`, rather than `Editor (beta) < SITENAME` like wp-admin does.

### Context

Found during testing. 

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

**Comment by zachspears** [comment]
Was able to replicate, agree that tab title should be consistent.

**Comment by Addison-Stavlo** [comment]
This should resolve by default once we remove the calypsoify iframe for the editors in the near future.

**Comment by annezazu** [comment]
![Screenshot 2024-08-29 at 2 48 09 PM](https://github.com/user-attachments/assets/e59d3268-6098-4c86-946b-7746f717aa41)

Closing this out as I can't replicate this on my simple site on WordPress.com. Also if you go to https://wordpress.com/site-editor/SITENAME, it automatically redirects to wp-admin :)
