### ISSUE TITLE
i18n Verticals List API & UI

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#63076]
# Description
Note: We will ship MVP to English only users, but soon after ship to all languages.

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5665959/169082560-5211a44d-be56-4ac7-a5a4-fbe097e7fc30.png">

The foundations of the v13n UI & API are now in place. See CfT pbxlJb-1Fl-p2 for background) and now we can begin work on these features for i18n.  This could get complicated! 😆    We may want to break the work down by language groups as there are likely to be unique issues with symbol languages, non-latin languages, and RTL languages.  Luckily Ganon has some valueable resources: people that are native in some of these languages!!  🥳    Still, we will rely heavily on Team Global for help with this work.

Back in March Yuliyan Slavchev reached out to ask if we needed help p1648039123055139-slack-CRWCHQGUB. This is the best place to start with this effort.

This issue is likely to be as much about coordination with Team Global as actual dev work.

### The verticals list to be translated
* Verticals list: /trunk/wp-content/lib/verticals/datasource/all-verticals-v2.php

### i18n Resources & Help
* i18n Field Guide:  PCYsg-2sk-p2  
* a8c support 16 Magnificent Languages PCYsg-9nE-p2
* PCYsg-sgj-p2
* P2 post discussion prior translation problems that might serve as a helpful guide pdgK6S-qu-p2
* There are many i18n slack channels, for example #i18n, #i18n-devs  reach out in #i18n for questions 😄 
*  @roo2  & @arthur791004 are both experienced in the translation process and can help with any questions
*  @lsl is a former Ganon memeber and a former Team Global member who can also be used a resource 

# Acceptance criteria
- [x] We **DO NOT** need to have the more "sophisticated" synonym/hyponym functionality that we have implemented for English, make a judgement based on our resources/time
- [x] Basic type ahead matching should work for all 16 mag languages (I am guessing this is possible)
- [x] Drop downs working properly for all languages 
- [x] Do a CfT similar to the English one, find Automatticians that speak the 16 mag languages or ask Team Global for help with UI testing

# Dev Task List
Please update this as the work is defined.
- [ ] task1

# Related
* April 2022 CfT: pbxlJb-1Fl-p2

**Comment by autumnfjeld** [comment]
@miksansegundo  I added some additional help points in the description above.

As we discussed in Ganon sync today, one way you can start your "i18n journey" is to try the v13n flow in a non-english language. You should see that all the standard screen text should already be translated, as @arthur791004 showed in this screenshot:


![Image](https://user-images.githubusercontent.com/5665959/171133529-63efc452-e2ae-40b7-b28e-ac562d7830aa.png)

If you find any standard screen text (by standard I mean not the v13n drop down list) that isn't translated, you can open an issue and track down why it isn't translated.   The first step in searching for strings that have failed translation is to look here:   mc tool /linguine/review/ or via https://translate.wordpress.com/developer/griffithchen - for this you need to know who did the PR that had the string to be translated, in this example @taipeicoder 😄

**Comment by roo2** [comment]
One things related to this, currently the text used by the block patterns is not scheduled for translation. I'm not sure if this is something that we need to be translated or if it's better to wait for after the MVP when we look at implementing verticalizing text content?

<img width="903" alt="Screen Shot 2022-06-02 at 2 01 02 pm" src="https://user-images.githubusercontent.com/22446385/171550459-f18f0bcb-e5d0-4ce3-a028-21a962957273.png">

Also the title set on the preview does not appear to be translated. I believe it makes sense to look into getting the titles translated now, as they are not as likely to change.

cc @autumnfjeld @miksansegundo @that-mike-bal

**Comment by roo2** [comment]
I fixed the site title issue. It is now translated if available 🎉 .

There appear to be further issues with translation of the previews. 

* Arthur pointed out here https://github.com/Automattic/wp-calypso/pull/64282#issuecomment-1144611311 that some of the iframe preview content is not translated, while the mshots preview of the same text was translated. 

<img width="891" alt="Screen Shot 2022-06-03 at 12 00 12 pm" src="https://user-images.githubusercontent.com/22446385/171772254-f2473f75-9a82-44b1-8b09-502182e32438.png">

* I could not reproduce this issue immediately myself, but found that there is an issue related to many string existing in glotpress with a different capitalization ("Title Case" vs "Sentence case") and thus not being translated. I reached out to the i18n team for help with this pxLjZ-758-p2.
<img width="1364" alt="Screen Shot 2022-06-03 at 11 31 06 am" src="https://user-images.githubusercontent.com/22446385/171772315-3d0688c1-71c5-4816-a30a-169a913ff7c6.png">

**Comment by miksansegundo** [comment]
We still have strings pending for translation:
 
<img width="1484" alt="Screen Shot 2565-06-20 at 12 44 48" src="https://user-images.githubusercontent.com/1881481/174585368-14f8e347-c609-45f7-a778-02e794a9bb31.png">

<img width="1481" alt="Screen Shot 2565-06-20 at 12 42 32" src="https://user-images.githubusercontent.com/1881481/174584959-a32ebf87-86c7-40dd-a3c2-ccac09a7ffeb.png">

I have checked mc tool /linguine/review/ to try to find other pending translations related to the verticalization but I couldn't find a way to filter them in Linguine. @roo2 Maybe you know how to find them and check the status? All the posts in dotcomverticalposts.wordpress.com have to be translated.

**Comment by miksansegundo** [comment]
We can keep track of the status of the translations for each post in [dotcomverticalposts.wordpress.com](http://dotcomverticalposts.wordpress.com/) in the MC patterns-toolkit/block-patterns/index.php?site=dotcomverticalposts.wordpress.com. For now, we have about 50% translated.

**Comment by miksansegundo** [comment]
We have landed the issue [Pattern i18n - Translate dynamic post content in the query blocks ](87-gh-Automattic/ganon-issues) and an existing LTR issue has been solved too in 465-gh-Automattic/i18n-issues.

We still have pending the following issues:
- Missing design translations on the header and/or footer 84-gh-Automattic/ganon-issues
- Missing vertical suggestion translations for some locales intentionally preserved in English

**Comment by autumnfjeld** [comment]
@miksansegundo  LEt's close this issue, it is complete and any remaining items should have new issues, which i see in 84-gh-Automattic/ganon-issues

It seems like this isn't an open issue, correct?
> Missing vertical suggestion translations for some locales intentionally preserved in English
Are these strings intentionally left in English, meaning no translation needed , so no further work regarding these particular strings?

**Comment by miksansegundo** [comment]
> It seems like this isn't an open issue, correct?

Correct. That is not an open issue but something we could consider improving because our use case for the verticals might be an exception. The convo is [here](p1657525729304139/1657525269.185889-slack-CRWCHQGUB).
