### ISSUE TITLE
[Bug]: Crowdsignal blocks appear uncategorized

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#63081]
### Quick summary

When opening site editor (e.e. `https://wordpress.com/site-editor/SITE`), I see warnings at console:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/87168/165473086-e21c8849-a8f9-4bda-8053-4280d746ac93.png">

When opening block sidebar, I see all the blocks as uncategorized:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/87168/165473605-e61aabb9-c32c-47a0-87a4-b6c3a7c6e85d.png">

FYI @Automattic/crowdsignal 

Tested with sites using Gutenberg v13.1.0-rc.1 (edge stickered site) and Gutenberg v13.0.

Note that category works in the regular post/page editor:

<img width="610" alt="Screenshot 2022-04-28 at 11 59 53" src="https://user-images.githubusercontent.com/87168/165717321-ea26fbce-59f5-440e-a1da-7677711f863f.png">

### Steps to reproduce

- Open homepage in site editor console open
- Observe console

### What you expected to happen

No warnings at console, blocks appear "uncategorized".

### What actually happened

Despite warnings, blocks still register fine:

<img width="304" alt="Screenshot 2022-04-27 at 11 16 20" src="https://user-images.githubusercontent.com/87168/165473514-5ac0be22-7eda-41e6-a518-2c0a664b5387.png">

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by CGastrell** [comment]
Hey! Trying to understand here how is it that the blocks don't show the same issue on the regular post/page editor. Is there anything special we need to do from Crowdsignal side?

**Comment by CGastrell** [comment]
Should be fixed now, it would be good to have someone else to confirm before closing it

**Comment by simison** [comment]
Yep! Works now on site editor at simple site:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/87168/166822123-2a174282-c162-4985-9bb3-a0b42ac0229a.png">

Tested also post and page editor 👍
