### ISSUE TITLE
Editor: Errors embedding Tumblr posts

### ISSUE THREAD

**Issue by tellyworth** [Automattic/wp-calypso#63090]
I'm unable to embed some Tumblr posts in wordpress.com posts. The problem seems limited to specific sites (perhaps only one). It produces console errors and the editor becomes unresponsive.

#### Steps to reproduce

1. Start a new post at https://wordpress.com/post on a test site
2. In the content, post the URL `https://bookshelfporn.com/post/70949053173` or `https://bookshelfporn.com/post/59996349372/follow-bookshelf-porn`

#### What I expected

Embedded content

#### What happened instead

No content is embedded. The editor becomes unresponsive to typing. There are browser console errors:

```
Error: Warning processing windowTypes: This property is deprecated [global.min.js:250](moz-extension://a50bea63-fd8f-1b4f-bfec-99a6defe526f/global.min.js)
    a moz-extension://a50bea63-fd8f-1b4f-bfec-99a6defe526f/global.min.js:250
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
4 common.js:4
Error: Warning processing windowTypes: This property is deprecated global.min.js:250
Promise resolved after context unloaded
content.bundle.js:1
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
content.bundle.js:61
a is undefined global.min.js:250
Unchecked lastError value: Error: Invalid window ID: 476 global.min.js:250
Error: Warning processing windowTypes: This property is deprecated [global.min.js:250](moz-extension://a50bea63-fd8f-1b4f-bfec-99a6defe526f/global.min.js)
```

#### Browser / OS version

Firefox 99.0.1 on macos 12.3.1

#### Context / Source

I was #dogfooding this on a personal wp.com blog. Tested it on a second dotcomblog as well with the same result.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - **Could Not Replicate** with a standard Tumblr account

📌 FINDINGS/SCREENSHOTS/VIDEO
- This seems specific to the build of that site - possibly a hosted site built with Tumblr's open source framework?
- I'm able to embed a post from tumblr.com/staff as expected, but not the sample site provided

https://github.com/Automattic/wp-calypso/assets/27249804/f502699d-3403-4a3a-bdba-2369fb68aef9

I think the provided blog is built on tumlbr code but is standalone, and thus works differently with our embed block. Seeing the following within scripts when inspecting the site:

```
src="https://assets.tumblr.com/client/prod/standalone/tumblelog/index.build.js..."
```

📌 ACTIONS
- Closed as could not replicate (with a standard Tumblr post)
