### ISSUE TITLE
FSE / Atomic: Theme paths sometimes fail to transform on transfer, can break references to Header and Footer template parts

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#63106]
### Quick summary

**_Additional testing is necessary to determine if this is intermittent or consistent._**

**_A workaround is available, see below._**

**_a11ns, see p9F6qB-9aB-p2#comment-46790 for extended notes and details._** 

---

When Simple sites go Atomic, we attempt to update theme paths in the DB ( r225839-wpcom / D60384-code ).

> Because wpcom themes are in nested directories such as pub and premium, but dotorg installs do not use nested paths, we need to remove that prefix in the db in places used by full site editing themes:

> * The themes attribute in the template part block, stored in the post_content of wp_template and wp_template_part post types.
> * The name and slug of terms in the wp_theme taxonomy.

However, this does not always work as expected and some sites can end up with the incorrect path for things such as their Header and Footer template parts.

In my testing, this impacted Blank Cavnas and the Home and Page templates. Other templates loaded the Header and Footer template parts properly.

### Steps to reproduce

1. Start with a Simple site with Blank Canvas (can impact other themes)
2. Create custom Header and Footer template parts. Ensure they are in place on the Home and Page templates.
3. Transfer site to Atomic
4. Open the Home and/or Page templates and inspect the Header and Footer parts.
5.  See error.

### What you expected to happen

Template parts to load as expected after transfer.

```
/wp-json/wp/v2/template-parts/blank-canvas-blocks//header?context=edit&_locale=user
```

(There is an extra `/` in this path but it still works)

### What actually happened

Header and Footer template parts can sometimes have the incorrect path and fail to load w/404

```
VM1465:1 GET SITE/wp-json/wp/v2/template-parts/pub/blank-canvas-blocks//header?context=edit&_locale=user 404
```

The `/pub/` in this path is incorrect on Atomic.

In the editor we see:

`Template part has been deleted or is unavailable: header`
`Template part has been deleted or is unavailable: footer`

![Screen Shot on 2022-04-27 at 11:56:57](https://user-images.githubusercontent.com/4887830/165561000-04bb8161-5b25-45ce-bd44-66840b9c68ff.png)
.

### Context

p9F6qB-9aB-p2#comment-46788 and threaded comments.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

FSE compatible themes

### Reproducibility

Unsure, consistent in my testing but might be intermittent.  

### Severity

At least Some (< 50%), maybe more

### Available workarounds?

Yes, easy to implement

### Workaround details

The template parts are still in the database, the path to them just needs to be updated.

A quick fix is to switch to the code editor and correct the path by removing `pub/` or `premium/` -- see specifics on https://github.com/Automattic/wp-calypso/issues/63106#issuecomment-1111521482

Another workaround is to remove and re-add the template parts to the templates having issues loading them.

**Comment by JoshuaGoode** [comment]
I've reproduced consistently so far.  It continues to only impact certain templates such as Home and Page on my sites using Blank Canvas.

However, this may be a race condition.

I've not looked at the code just yet.

**Comment by JoshuaGoode** [comment]
@creativecoder identified issues with a regex query, p9F6qB-9aB-p2#comment-46829

**Comment by creativecoder** [comment]
Attempting a fix in D79640-code

**Comment by creativecoder** [comment]
Fix has been deployed.

**Comment by creativecoder** [comment]
For anyone that runs into this and the site is already transferred, you can easily fix it by doing the following

- Open the Site editor
- Select the "Code editor" view from the "Options" menu (three dots in the upper right)
- Look for the Template Part block, `<!-- wp:template-part {"slug":"header","theme":"pub/remote","tagName":"header"} /-->`
- Remove the `pub/` or `premium/` prefix from the theme slug, e.g. change `pub/remote` to `remote`
- Repeat for any other template parts in the template (usually a header and footer)

![Screen Recording 2022-04-27 at 16 56 31](https://user-images.githubusercontent.com/1699996/165638180-173f03e6-1ab1-4e12-a430-eeb0786ace49.gif)

**Comment by JoshuaGoode** [comment]
Tested and works as expected. 

Updating the original report to include [the better workaround](https://github.com/Automattic/wp-calypso/issues/63106#issuecomment-1111521482) and closing this report.
