### ISSUE TITLE
Onboarding Progress Bar [save for Ngan]

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#63118]
# Description
Currently the user has no signal of progress as they move through steps in the FTM onboarding flows.   Let's fix that with an onboarding progress bar.
This work is not needed for v13n Build Flow MVP.

See blue progress bar along top of screen.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/5665959/165669774-d2e7ab67-3b31-41b2-b85c-53262071b5ce.png">

# Acceptance Criteria
When the time comes to start this, please work with @saygunnyc  to finalize this AC list.
- [ ] Useable in every FTM flow
- [ ] Flexible/useable regardless of number of steps in a flow
- [ ] Sits at top of screen
- [ ] Tested on real mobile device - ask Autumn or Zach or HE for informal testing as needed

**Comment by arthur791004** [comment]
More context: p1655427741505269-slack-CRWCHQGUB

**Comment by autumnfjeld** [comment]
@bangank36 Don't forget to move the issue into the same column as the PR.   For example, this PR for this work  #64586 is in "Review in Progress".  This issue should also be moved to "Review in Progress".    Thank you. :)

**Comment by bangank36** [comment]
I'm closing this because the feature has been shipped
