### ISSUE TITLE
Woo Flow: Button styles misaligned

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#63113]
These buttons …

![image](https://user-images.githubusercontent.com/545779/165590407-d4a49ba7-6c1a-47a6-a4a0-51f91ab1a4d3.png)

Are missing spacing between them on this screen …

![image](https://user-images.githubusercontent.com/545779/165590354-f93df338-ce1d-47a7-9f51-782a65b0f2bf.png)

**Comment by markbiek** [comment]
@ianstewart When I go to this page, this is what I'm currently seeing:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/917632/167712242-1dcc745f-8b55-4460-b1f7-cdb9473d3fdd.png">

Is it possible this has already been addressed or are you still seeing the layout you posted originally?
