### ISSUE TITLE
i18n for patternboilerplates

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#63119]
# Description
We will ship MVP to English only users, and soon after ship to all languages.

The foundations of the v13n project are now well understood, thus as we wrap up work for the core MVP product we can begin work on v13n features for i18n.

Ensure that we are handling translation for patterns in dM0oz-p2.  This will require coordination with @iamtakashi  and @that-mike-bal and other theme designers as needed. See slack conversation about PTK & source sites: p1651027873414889-slack-CRWCHQGUB

One problem with the patternboilerplate site dM0oz-p2 is that most of the patterns won't be used in MVP v13n layouts/recipes - so we don't need to translate them.  Translation is expensive so we want to solve this problem. Either remove non-MVP patterns to another site, or come up with a **simple** technical solution that translates only select patterns.  (As a backup solution we can always move  MPV patterns to dotcompatterns.wordpress.com if this is the most sensible solution.)

# Acceptance Criteria
- [ ] Deal with "excess patterns" problems
- [ ] Patterns in the Recipe Tool are translated to mag 16 languages PCYsg-9nE-p2
- [ ] Patterns in the v13n Design Picker are translated to all mag-16 languages
- [ ] Starter sites are translated to mag-16 languages
- [ ] query block and post content is translated

# Related
* https://github.com/Automattic/wp-calypso/issues/63076
* slack convo p1651027873414889-slack-CRWCHQGUB

**Comment by autumnfjeld** [comment]
@roo2 I wrote this ticket up last month and since you're already diving in (pxLjZ-758-p2)  I'm moving it to In Progress.  
Also adding your P2s for reference

Case sensitivity issue with translating block patterns from patternboilerplates.wordpress.com  pxLjZ-758-p2
Translating patterns from patternboilerplates.wordpress.com pxLjZ-76c-p2

The reason I made two separate i18n tickets (this one and #63076) is I anticipated a special set of problems with the patterns, which you are already sorting out. 🙏. I think it makes sense to keep this ticket active, ya?

**Comment by roo2** [comment]
hmm I just haven't been able to view dM0oz-p2, I'm getting a 403 error there but I caught up on the thread p1651027873414889-slack-CRWCHQGUB. 

I've added patternboilerplates.wordpress.com to  the list of sites being translated in the block-patterns project in D82185-code after discussion pxLjZ-76c-p2 I made them aware of the issue with the duplicate titles, "Contact 7" etc, but they didn't object to having them included. 

I can see that some translations are starting to come. I did notice that new translations have the "not covered by weekly kit" label, but it appears that so do older translations from other starter sites, so I think this is ok.

The only thing left for me to do is add dotcomverticalposts.wordpress.com to be translated, now that it is used for starter posts D82270-code. I'll do this now 👍 

I don't anticipate any problems! 🤞

**Comment by roo2** [comment]
diff to add dotcomverticalposts.wordpress.com to be translated D82515-code.

**Comment by roo2** [comment]
D82515-code merged ✅ , we now just need to wait until all content has been translated

**Comment by roo2** [comment]
it looks like everything's been translated for the mag-16 languages in glotpress except for the new philosopher quotes used by the example posts, which is queued for translation 👍 
pxLjZ-76c-p2#comment-19153

**Comment by taipeicoder** [comment]
@roo2 seems that this is completed, feel free to close this one if that's the case 🙂
