### ISSUE TITLE
Improve experience of mShots preview during URL import

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#63121]
Improve the timing of taking the screenshot, or replace with an iframe.

Try angrybirds.com and see if it generates a preview.

**Comment by bogiii** [comment]
> Improve the timing of taking the screenshot

I've tried screenshot initialization right before running the scanning process, but it doesn't improve the UX. I gave up with that solution, and I'd try an alternative, for example, previewing a website in an iframe.

**Comment by vishnugopal** [comment]
@bogiii We might take a look at what Ganon is doing here, as they are also doing something similar for the design picker!
