### ISSUE TITLE
[Bug]: Form response "Export as CSV" button doesn't work

### ISSUE THREAD

**Issue by desnum** [Automattic/wp-calypso#63150]
### Quick summary

The user is unable to "Export responses as CSV" at the bottom of the Feedback tab.

### Steps to reproduce

1. Start at http://arnostifarmconnections.com/wp-admin
2. Click on the Feedback tab
3. Click the "Export responses as CSV" at the bottom of the page

### What you expected to happen

A CSV file should begin to download

### What actually happened

Clicking on the button does nothing visually for me. The user reports seeing the error message:

> This site can’t be reached
The webpage at https://arnostifarmconnections.wordpress.com/wp-admin/admin-post.php might be temporarily down or it may have moved permanently to a new web address.

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

There is an open feature request for form responses to be downloaded in filtered lists: https://github.com/Automattic/wp-calypso/issues/61815

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

While the feedback responses can be downloaded as an xml file from the Tools > Export page, this doesn't help someone needing a spreadsheet.

**Comment by desnum** [comment]
Another HE reported the same issue for a different user, with this screenshot:

<img width="666" alt="feedbackformerrormessage" src="https://user-images.githubusercontent.com/43796228/165814270-afaa29bf-17ab-4b56-9282-2e6e88396218.png">

**Comment by marianearchimbaud** [comment]
I am facing the exact same issue here: 32192453-hc

**Comment by desnum** [comment]
Ah, we may need to merge into Automattic/jetpack#24170

**Comment by marianearchimbaud** [comment]
Closing this in favor of Automattic/jetpack#24170
