### ISSUE TITLE
[E-mails] Hide mobile app store icons when email directed at non-wpcom user

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/wp-calypso#63152]
### What

Remove the app icons from the emails to subscribers that don't also run their own site.

![Annotation on 2022-04-28 at 14-30-00](https://user-images.githubusercontent.com/45246438/165822187-f9ea404f-5925-407f-9410-42238122d8b4.png)

### Why

- App icons aren't relevant to all subscribers

**Comment by bobmatyas** [comment]
Requested in 4963821-zen

**Comment by shykonessy** [comment]
Please return the category and tags section at the bottom of the email templates. Or, revert to the old email template all together. Kindly.

**Comment by mashikag** [comment]
Hi @shykonessy ! 👋  Thank you for your feedback. There is another GH issue already created for missing tags, [here](https://github.com/Automattic/wp-calypso/issues/63002). The new e-mails design did  not include the tags and categories but the ticket was created based on users feedback. It is now up to design to part of our team to decide on how to the tags should be incorporated into the new design.

**Comment by yansern** [comment]
It is alright to use WP app for its Reader function without owning a site. Hence, closing this issue.
