### ISSUE TITLE
Marketplace: Thank you page for multiple products

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#63151]
Currently, it is possible to purchase multiple plugins at once as described here #62558.

But the Thank you page shown after the purchase only displays the last selected plugin. Ex:

![](https://user-images.githubusercontent.com/11555574/161982683-9a7b6197-39f1-4cd4-bf3a-51fd03590e4a.png)

We have to find a way to display multiple plugins results at this thank you page.

**Comment by cpapazoglou** [comment]
@SaxonF, while it's possible to checkout with multiple items in the cart eg Domain, Plan, 2 Marketplace Plugins, we only have 1 checkout thank you page. Depending on the user flow, we might show the domain, the plan, or the marketplace thank you page. On top of that, if you land in the marketplace thank you page, we only support 1 plugin in the design. So, we actually have two problems:

- Supporting more than 1 plugin in the marketplace thank you page
- How do we handle carts that contain multiple products that each of them might have different thank you pages?

**Comment by gcsecsey** [comment]
@SaxonF ping on the above questions

**Comment by vinimotaa** [comment]
Hi folks, I'm currently looking at this issue.

I did the steps of adding and purchasing multiple plugins, and I couldn't see the issue of any/some of these plugins not being installed. After payment, all the plugins I selected were installed correctly. Is this still an issue for some of you? 

As per the "Thank your page" design, I'll work on something to cater to one and multiple products and revert back to you soon!

**Comment by cpapazoglou** [comment]
> Hi folks, I'm currently looking at this issue.
> 
> I did the steps of adding and purchasing multiple plugins, and I couldn't see the issue of any/some of these plugins not being installed. After payment, all the plugins I selected were installed correctly. Is this still an issue for some of you?
> 
> As per the "Thank your page" design, I'll work on something to cater to one and multiple products and revert back to you soon!

Yes, that's the expected behaviour - all plugins get installed. What is also expected but considered a UX bug is that the thank you page is oriented to the last plugin you added to your cart.

**Comment by vinimotaa** [comment]
Hi folks, I have opened a solution/discussion space for us to tackle this. Please feel free to leave your feedback or input on what we're suggesting as we need to ensure everything in there makes sense and is technically feasible. 

https://dotcommarketplacep2.wordpress.com/2022/06/01/marketplace-plugin-post-purchase-experience/

Thank you!

**Comment by vinimotaa** [comment]
@cpapazoglou any feedback/thoughts on this C.?

I am [leaving the Figma file here](https://www.figma.com/file/HOg65lHD0QOfaq0QtzKQbC/Dog-Fooding?node-id=37%3A1366) for further discussions!

**Comment by cpapazoglou** [comment]
> @cpapazoglou any feedback/thoughts on this C.?
> 
> I am [leaving the Figma file here](HOg65lHD0QOfaq0QtzKQbC-fi-37%3A1366) for further discussions!

Hey @vinimotaa this is my backlog for reviewing, I will let you know this week!

**Comment by cpapazoglou** [comment]
This is still under discussion pdh6GB-11q-p2#comment-1946

**Comment by cpapazoglou** [comment]
Here are the new designs pdh6GB-2vX-p2.

**Comment by cpapazoglou** [comment]
Duplicate https://github.com/Automattic/wp-calypso/issues/71675
