### ISSUE TITLE
Marketplace search: Display fallback pattern for products without icons

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#63169]
The index contains icon file names in a serialized PHP array. These are deserialized and appended to the WPORG image host (`https://ps.w.org`).

For plugins that don't have icons uploaded to WPORG, the PHP array is empty, so icon URLs can't be produced just from the index response. WPORG generates a geopattern as the icon for these plugins (eg. [here](https://wordpress.org/plugins/slideshare/)).

**To reproduce:** try searching for `WooTcsShipmentMaker`

| Search results (index) | Plugin details page (WPORG) |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/11555574/165253817-dfc5ab8b-1394-4789-a717-4d4692a6ffec.png) | ![image](https://user-images.githubusercontent.com/11555574/165253859-668568c0-fb22-43cb-a670-d2da8c6f9630.png) |

The icons are generated by [this method](https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/class-template.php#L507), and generated icons can be accessed on [this URL](https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/class-plugin-directory.php#L538), colors can also be customized: `https://s.w.org/plugins/geopattern-icon/{$plugin->post_name}{$color}.svg`

This URL works for any name, so this could be used as a fallback on the marketplace too, eg. https://s.w.org/plugins/geopattern-icon/woocommerce_aa00aa.svg

**Comment by epeicher** [comment]
This task has been solved as part of #65249 because it was similar functionality.
