### ISSUE TITLE
Marketplace search: use new endpoint to fetch search results in Calypso

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#63166]
#62777 uses the v1 POST endpoint, which accepts options in the body. The v1.3 GET endpoint supports querying multiple indexes at the same time, and also contains some filtering, so we could reduce the size of the client as well as support more features by utilizing it.

We can reuse some parts of [the jetpack instant-search api lib](https://github.com/Automattic/jetpack/blob/3d17f431c4cf4ae01e10d6436e99b8e71e0a311d/projects/packages/search/src/instant-search/lib/api.js#L393). Jetpack search has some fields, filters, and sort options hardcoded, so using it as a dependency is not feasible.

**Comment by gcsecsey** [comment]
We will be forking the v1.3 endpoint in https://github.com/Automattic/wp-calypso/issues/63902 to customize it to our use cases. Once the new endpoint is deployed, we can create the API client based on the https://github.com/Automattic/wp-calypso/pull/63243 draft.

**Comment by gcsecsey** [comment]
Moving this back to the Backlog as we first need to have the index and the API layer ready. Thread: pdh6GB-Ax-p2#comment-1649

**Comment by cpapazoglou** [comment]
Let's get a WIP from https://github.com/Automattic/wp-calypso/issues/63902 and get this started asap.

**Comment by epeicher** [comment]
We have decided to wait for the diff D81357-code to land before progressing with this task. The diff is starting the review process so it should not take long.

**Comment by gcsecsey** [comment]
D81357-code is now landed and deployed: r247247-wpcom
