### ISSUE TITLE
Marketplace search: Return all plugin details page fields from the API

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#63171]
We can query for an exact match on the product slug from the index, which would let us get the same data to display on the plugin details page. However, as the plugin details page uses more fields from the WPORG response, we should investigate whether we need all the required fields to display the plugin page.

**Comment by gcsecsey** [comment]
By now, all WP.org fields have been added to the index in D81205-code and D82452-code.

We've added #63903 to track adding the WC.com fields.

The list of required fields are stored/updated here: pdh6GB-Mm-p2#comment-1970

Within the scope of this ticket, we need to make sure that all required fields are returnable from the API.

**Comment by cpapazoglou** [comment]
Depending on https://github.com/Automattic/wp-calypso/issues/64891

**Comment by cpapazoglou** [comment]
We have switched to using the shadow DB instead of ES for the plugin details page.
