### ISSUE TITLE
[Bug]: Migrate Testing from Enzyme to Jest and React testing library for the FollowButton block

### ISSUE THREAD

**Issue by spraveenitpro** [Automattic/wp-calypso#63194]
### Quick summary

The follow-button component is using the enzyme framework for testing,  We need to migrate it to React-testing-library and jext

### Steps to reproduce

1. We will have to refactor the code in the test folder within the component folder.

### What you expected to happen

After migration we should see that React-testing library and Jest are used to make the assertions and test

**Comment by cuemarie** [comment]
https://github.com/Automattic/wp-calypso/pull/63195 Was merged and committed; closing as solved.
