### ISSUE TITLE
Profile Photo: Can't update when "Hide my Gravatar profile" is toggled ON

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#63199]
### Quick summary

User reported and tested on my own site as well.

It seems like when an account wants toggles the **Hide my Gravatar profile** option at https://wordpress.com/me, they won't be able to update their profile photo.

Error:

```
Hmm, your new profile photo was not saved. Please try uploading again.
```

Untoggled: I can update photo.
![CleanShot 2022-05-01 at 14 46 56](https://user-images.githubusercontent.com/84539773/166146852-54dbcf49-b47c-4882-ac61-1ea7354fa731.jpeg)

Toggled. I can't update photo:
![CleanShot 2022-05-01 at 14 47 56](https://user-images.githubusercontent.com/84539773/166147010-5384135d-98eb-4abb-8d2b-94ca84fd6c1f.jpeg)

### Steps to reproduce

1. set the **Hide my Gravatar profile** option to untoggled at https://wordpress.com/me
2. try uploading an image
3. Image can be updated.
4. toggle the option **Hide my Gravatar profile** (so it is blue)
5. Try uploading an image.
6. Error message received `Hmm, your new profile photo was not saved. Please try uploading again.`

### What you expected to happen

It would work either way.

### What actually happened

Users who wish to hide Gravatar photo, cannot update photo.

### Available workarounds?

Yes, easy to implement

### Workaround details

Set the Gravatar option to untoggled.

**Comment by csabarakasz** [comment]
5182077-zd-woothemes

**Comment by zachspears** [comment]
Tested uploading a new profile image but was able to do so successfully. Leaving in the triage queue for another HE to test. 
![Annotation on 2022-05-06 at 01-10-02](https://user-images.githubusercontent.com/10124024/167084386-f454f6b7-fe2f-4964-8f94-47b7cf006fd1.png)

**Comment by formosattic** [comment]
Thanks for the detailed report @csabarakasz , I was able to reproduce it too.

@zachspears : I notice your `Save profile details` isn't greyed out, meaning that the `Hide my Gravatar profile` setting is likely still toggled off, hence, why you're able to upload it.

**Comment by essleeung** [comment]
This ticket's user couldn't upload a profile photo and I tried it too and also couldn't. It was very odd, but when I toggled it to hide my gravatar that's when it let me upload the image. 5235556-zd-woothemes

![image](https://user-images.githubusercontent.com/39225086/170039026-68070398-2415-44f5-875c-ce92ec548987.png)
This setting lets me upload.

**Comment by wojtekn** [comment]
I've reviewed this issue and reproduced it. The feature behavior and messaging may be confusing.

### Background

The toggle feature enables/disables the Gravatar profile completely, and this change happens on the Gravatar service side. The photo upload feature uses Gravatar service to upload images and there is no alternative there. When a user tries uploading a photo while Gravatar is disabled, Calypso still tries to upload it to Gravatar. The API returns an error, and Calypso shows the "Hmm, your new profile photo was not saved. Please try uploading again." message.

### Proposed fix

In this case, I would propose making the following changes:

**1. Adjust messaging to clearly say that it is about disabling the photo completely**

We could modify the TLDR part of the label to explicitly say it hides the user's photo, and not only the Gravatar profile. The same is explained in the text that follows the label:

> **Hide my photo and Gravatar profile.** This will prevent your Gravatar profile and photo from appearing on any site. It may take some time for the changes to take effect. Gravatar profiles can be deleted at Gravatar.com.

Another option would be to explicitly say that we disable the profile, not hide it. This is the wording that is actually used on the Gravatar side. It could be **Hide my photo and disable Gravatar profile.** or just **Disable my Gravatar profile.** 

**2. Disable image upload completely when Gravatar profile and photo are hidden**

We would disable the "Click to change photo" image selector completely when Gravatar is disabled. This way user wouldn't try uploading an image when the Gravatar profile was disabled.

I would appreciate more feedback here.

**Comment by cuemarie** [comment]
Ran into this issue again here: 35241120-hc

I think your proposed solution @wojtekn would help a lot! It's definitely not clear to me that Gravatar is _necessary_ for you to have a profile photo at all - I misunderstood it to function more like an optional integrated service. It would also be great to link to our Gravatar support document from here, to help users find more info on this! (-> https://wordpress.com/support/gravatars/ )

**Comment by csabarakasz** [comment]
Same:  35857735-hc

**Comment by danielbachhuber** [comment]
@wojtekn I like your proposed solution!

Building on what you've suggested...

> **2. Disable image upload completely when Gravatar profile and photo are hidden**
> 
> We would disable the "Click to change photo" image selector completely when Gravatar is disabled. This way user wouldn't try uploading an image when the Gravatar profile was disabled.

The `ImageEditor` component doesn't appear to support a `disabled` attribute. I think it might be confusing to have a disabled element (i.e. forcing the user to think "why is this disabled?").

An alternative to consider would be slightly different UI (rough mockup, open to suggestions on language):

<img width="890" alt="image" src="https://user-images.githubusercontent.com/36432/176025164-5679fc42-85d7-4bbe-b197-43c222f990a7.png">

**Comment by csabarakasz** [comment]
Hmm, seems like it wasn't clear enough for some users: 28440419-hc The new description text was there, but the user is still "struggling with this for weeks". :/

**Comment by csabarakasz** [comment]
About the previous issue. The photo worked after the user created a Gravatar profile. I wonder if we could include a sentence about that too. What do you think @danielbachhuber ?

**Comment by danielbachhuber** [comment]
@csabarakasz Is there a specific change you'd suggest?

**Comment by wojtekn** [comment]
@csabarakasz @danielbachhuber I've tested the workflow for the WP.com account that uses an email address not registered with Gravatar, and it worked fine for me - I was able to upload my photo to WP.com without creating a Gravatar profile.
