### ISSUE TITLE
Marketplace: Breakdown PluginBrowser children into independent components

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#63191]
Due to the `PluginBrowser` file becoming to large (700+ LOC) we want to divide it into smaller components and move them into different files.

As a first step, we should share a plan for improving reusability and readability of these components and tag Explorers and Bespin for review.

**Comment by Rolilink** [comment]
@lsl will love your input on this one.

**Comment by lsl** [comment]
Looks good, here's some more ideas :smile: 

I'd love if this code didn't exist, or was moved into a hook:

- https://github.com/Automattic/wp-calypso/blob/9fb7ac149e55361c0c3a9639ad0caa5e15fc88b0/client/my-sites/plugins/plugins-browser/index.jsx#L540-L553
- https://github.com/Automattic/wp-calypso/blob/9fb7ac149e55361c0c3a9639ad0caa5e15fc88b0/client/my-sites/plugins/plugins-browser/index.jsx#L481-L497

This should probably just be in the browser:

- https://github.com/Automattic/wp-calypso/blob/9fb7ac149e55361c0c3a9639ad0caa5e15fc88b0/client/my-sites/plugins/plugins-browser/index.jsx#L579-L601

I don't like these different view things, can't we just have one "view" and pass the plugins into it? (`PluginsBrowserList` looks like what I'm talking about but it hasn't worked out that way in practice) 

- `SearchListView`
- `SingleListView`
- `FullListView`

I don't have a good solution for you, I think maybe try squashing as much as you can into the `PluginsBrowserList` and moving everything else up to the browser level? Not a good ideal but probably better than what we have. 

We can always extract something like the existing views back out with better abstractions after.

**Comment by Rolilink** [comment]
The first two points I have in mind working them on the `usePlugins` hook!

> I don't like these different view things, can't we just have one "view" and pass the plugins into it? (PluginsBrowserList looks like what I'm talking about but it hasn't worked out that way in practice).

I will prefer not moving stuff into the browser since this will cause a lot of conditional fetching, I will prefer having smart components like `SearchResults` (fetches and render results), `CategoriesResults` (fetches and render results) and `DiscoveryView` (fetches and render the main page sections). That way the data fetching is way more predictable and easier to find where we need to do changes.

Right now the Browser haves a lot of responsibilities, including conditionally fetching data and conditionally rendering it. I think that the Browser only responsibilities should be:
1. Defining the `onSearch` method.
2. Passing down the selected site and site type.
3. Conditionally rendering stuff that fetches its own data.

**Comment by lsl** [comment]
LGTM

**Comment by allilevine** [comment]
First step is a p2 post, see p1653330277142129/1653267414.312709-slack-C03FE3T479R

**Comment by Rolilink** [comment]
Posted a P2 post with my findings pdh6GB-14m-p2 and Added phases as milestones:
https://github.com/Automattic/wp-calypso/milestone/400
https://github.com/Automattic/wp-calypso/milestone/401
https://github.com/Automattic/wp-calypso/milestone/402
https://github.com/Automattic/wp-calypso/milestone/403
