### ISSUE TITLE
Marketplace: Add usePlugins hook

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#63192]
There is a lot of conditional plugin fetching through different children of the PluginBrowser component like [here](https://github.com/Automattic/wp-calypso/blob/115363bdb05ae5e986486b41fbd2b64c21ceb26e/client/my-sites/plugins/plugins-browser/index.jsx#L112-L117), [here](https://github.com/Automattic/wp-calypso/blob/115363bdb05ae5e986486b41fbd2b64c21ceb26e/client/my-sites/plugins/plugins-browser/index.jsx#L337-L358) and [here](https://github.com/Automattic/wp-calypso/blob/115363bdb05ae5e986486b41fbd2b64c21ceb26e/client/my-sites/plugins/plugins-browser/index.jsx#L446-L478). Let's create a hook that conditionally fetches plugins based on the received category, tags or search term.

- [x] It supports tag.
- [x] It supports categories and translate them to tags when it is necessary.
- [x] It returns plugin with the same schema and is performant (useMemo and updateWpComRating).
- [x] It conditionally triggers `useWPCOMPlugins` or `useWPORGPlugins`.
- [x] It supports infinite fetching of plugins through `useWPORGInfinitePlugins`.
- [x] It haves documentation
- [x] It haves correct typing

**Comment by cpapazoglou** [comment]
ccing @gcsecsey since he is working on those files and it would be better to avoid a rebase hell 😅

**Comment by Rolilink** [comment]
@cpapazoglou will add @gcsecsey as a reviewer :) !
