### ISSUE TITLE
Hash symbol creates issues on alt-text for images 

### ISSUE THREAD

**Issue by tavilla61** [Automattic/wp-calypso#63201]
### Quick summary

User reported that using a hashtag symbol in alt text on their images results in the text becoming "mangled" and generating a broken code below the image, instead of the description of the image. 

### Steps to reproduce

1. http://transponderingsblog.wpcomstaging.com/
2. I wasn't able to reproduce the issue, but the user said they saw it anywhere they tried to use alt text. 
3. Libre 2 Theme - I tried reproducing it on a test site, but didn't see any issues. 
4. Tried adding the text with a hashtag, and without, but didn't see a difference. 

### What you expected to happen

Text should appear as a description under the image. 

### What actually happened

I didn't see any text appear under the image I added to a post.

This may not be an issue and might be behaving the way it's meant to. 

### Context

Ticket for reference: 5176024-zen 

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Libre 2 

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

User said they could use a double hash symbol, and that worked better than using just a # symbol.

**Comment by vajrasar** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Tested on Libre2 theme on WordPress.com (Simple, AT), and Libre theme (self-hosted).

📌 FINDINGS/SCREENSHOTS/VIDEO
- Cannot replicate the issue

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
@tavilla61 Thanks for the report. I was not able to replicate the issue on my sites. Closing this, but please feel free to open if the issue appears again.

Additionally, we can ask the user for any live link of the page where the issue can be seen on the site and the steps they are using to add the image (which results in the issue). If they provide the link and the issue can be seen, please try to replicate the exact steps and re-open this if you can replicate.
