### ISSUE TITLE
Backup and Restore: Incomplete and inconsistent backup restores when posts include Forminator content

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#63203]
### Quick summary

Our user has a series of posts with embedded [Forminator](https://wordpress.org/plugins/forminator/) polls. They restored two sets of backups, and noticed that the restores inconsistently restored Forminator polls to their posts on one of the days they restored from, while whole posts were missing on another day.

### Steps to reproduce

1. The user restored posts from 29 and 30 April 2022
2. The restore from 29 April is missing more Forminator polls, although most posts were restored
3. For the restore from 30 April, fewer posts were restored, although more Forminator polls were restored.

### What you expected to happen

Consistent, and complete backups of all content that could be correctly, and completely restored using the Jetpack Restore feature.

### What actually happened

Inconsistent, and incomplete restores for both posts and Forminator polls embedded in the user's posts.

### Context

User report in 5181238-zen

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Unclear whether this is theme-specific. The site is using Twenty Twenty-Two.

### Browser, operating system and other notes

I checked the logs for the backups on the two days, and noticed this information notice in the logs:

>info: Saw no files for plugin: forminator@1.15.12

I also noticed a series of errors that have the `wp_frmt_form_` prefix in the restore logs. I'm unsure if this is an identifier for the Forminator plugin, though.

Links to logs in notes on the user's report.

### Reproducibility

Consistent

### Available workarounds?

No and the platform is unusable

### Workaround details

Not aware of any workaround except manually reconstituting posts and content.

**Comment by formosattic** [comment]
I'm not sure if this should really be treated as a bug, pinging internally for a check: p1652770002791919-slack-C036E4KFP2L

I did a quick test by deleting a few posts, and two that included 2 Forminator polls, and all were restored fine.

Closing and reposting internally at p9F6qB-9ov-p2
