### ISSUE TITLE
WordPress Importer: Fails to detect Jetpack plan

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#63202]

**Comment by vishnugopal** [comment]
See: p1651264773045379-slack-C01A60HCGUA

**Comment by bogiii** [comment]
Answer: p1651489253296669/1651264773.045379-slack-C01A60HCGUA

**Comment by vishnugopal** [comment]
Discussion:
- Hard to figure out what's going on here.
- Can't su to Automattic users so can't replicate behaviour.
- Action item: let's see what is returned from the backend and how.
- We might try to ping Jetpack team if we can't figure this out.

**Comment by vishnugopal** [comment]
Discussion:
- Was trying to find out what's happening under the hood.
- Endpoints in some scenarios are cached. (Shadow endpoint?) Because of the caching, it might return an older result.
- We need to dig into this more.

**Comment by vishnugopal** [comment]
Discussion:
* It seems like there is something wrong with the Jetpack connection as the API endpoint returns info from WPCOM.
* Discussion with Jetpack team might be an avenue to explore once we do more investigation.

**Comment by vishnugopal** [comment]
Discussion:
* No progress. Brie replied saying that it's not a jetpack site: p1652488926197109/1651264773.045379-slack-C01A60HCGUA 
* We need to take a look at the Jetpack site conditions and then forward to the Jetpack team if necessary.

**Comment by zaerl** [comment]
See p1657642907423269/1651264773.045379-slack-C01A60HCGUA

**Comment by vishnugopal** [comment]
This seems to be fixed as per comment here: pciE2j-1fY-p2#comment-1067:~:text=an%20error%20screen.-,Also%2C%20I%20entered%20cometgrrl.com%20without%20the%20www%20as%20the%20domain%20to%20import%2C%20so%20that%20seems%20to%20be%20a%20non%2Dissue%20as%20well.,-I%20will%20note
