### ISSUE TITLE
Pro plan unable to access chat when language not English

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#63206]
### Quick summary

User with a pro plan is not able to access chat when the profile (not site) language is set to Spanish

I tried to replicate this on a test site but was unable to. I could consistently reproduce on the user's site though

Possibly related issue here: https://github.com/Automattic/wp-calypso/issues/52315

### Steps to reproduce

1. Try to access chat from help bubble with profile language set to spanish
2. see only email option
3. change profile language to english
4. see chat available

### What you expected to happen

Chat should be available regardless of profile language; should depend on plan only

### What actually happened

User was only able to access after language changed to English

### Context

5183870-zd-woothemes

![2022-05-02 at 16 08](https://user-images.githubusercontent.com/47717887/166240452-965f11a7-9180-47f6-b27a-695a97d31061.jpg)
![2022-05-02 at 16 07](https://user-images.githubusercontent.com/47717887/166240476-40b9e727-53a9-459e-920c-7f43379e360e.jpg)

Site did experience a Jetpack ID crisis at the same time but issue persisted after this was resolved

### Simple, Atomic or both?

Atomic

### Available workarounds?

Yes, easy to implement

### Workaround details

Switching the language to English allowed them chat access

**Comment by zachspears** [comment]
I have tested this but was not able to replicate it. When you do not input any help text, the button is deactivated, but if you type anything into the box, it activates as expected:
<img width="1096" alt="Screen Shot 2022-05-11 at 6 10 35 PM" src="https://user-images.githubusercontent.com/10124024/167967264-7ea604ce-2e63-408f-bae9-880945510e9a.png">
<img width="1096" alt="Screen Shot 2022-05-11 at 6 10 58 PM" src="https://user-images.githubusercontent.com/10124024/167967280-81e48ca4-edc4-4eda-b38a-2e27af6008c7.png">

Additionally, this appears to be consistent behavior with English: 
<img width="1096" alt="Screen Shot 2022-05-11 at 6 11 36 PM" src="https://user-images.githubusercontent.com/10124024/167967348-ada38b35-40ad-4889-be19-21511f52fa13.png">

Leaving for another Bug Herder to test, before removing bug report in case I missed something.

**Comment by Greatdane** [comment]
Closing this as well, unable to reproduce. 

<img width="919" alt="Markup 2022-05-12 at 14 39 11 (1)" src="https://user-images.githubusercontent.com/5075840/167999621-320f95ca-7cb8-4383-b870-e761dcefbf61.png">

**Comment by Greatdane** [comment]
Re-opening this. IT user with Pro plan only has no access to chat. Confirmed;
5241955-zd-woothemes

Edit: when I set the language to English, chat option shows up, so this would be a **work-around**.

**Comment by jordesign** [comment]
Treating this as scrubbed and triaged - based on @Greatdane's experience.

**Comment by heavyweight** [comment]
Couldn't replicate this issue.

Setting the language preference to either IT or ES does not affect the chat availability. 
Looking into 5241955-zd-woothemes the issue is not replicate able for the user as well, probably because the plan is not active anymore.

We tested from proxied and non-proxied and from a non automattician user.

Will close this for now. Until we get more detailed steps or a new report.
