### ISSUE TITLE
Unable to access chat with broken Jetpack connection

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#63210]
### Quick summary

When a user has a single site with chat permissions and the Jetpack connection is broken they are not able to access chat to get help fixing the connection or otherwise. It does not matter if they have other sites that don't have chat access or not.

### Steps to reproduce

1. Set up a user with an AT site and plan that includes chat support (pro/bus/ecom)
3. verify that chat available
4. break Jetpack connection for user on site above
5. make sure that user not connected to any other sites with chat access
6. verify that chat no longer accessible (can try to access via profile area)

### What you expected to happen

Users that are admins on sites with chat access should retain that access even if/especially when Jetpack breaks

### What actually happened

If only a single site has chat permissions and the connection breaks the user loses chat access
If user has multiple sites with chat access and one breaks, chat access remains

When connected as JP user to site with chat access: 
![2022-05-02 at 16 46](https://user-images.githubusercontent.com/47717887/166251612-98097204-8e86-4bfa-b976-2385d870ed37.jpg)

When disconnected but still admin:
![2022-05-02 at 16 47](https://user-images.githubusercontent.com/47717887/166251692-26e8bddc-97dc-4e21-b881-a237a0fb1d4a.jpg)

### Context

Historical user report: 4901544-zd-woothemes 
Related issue: https://github.com/Automattic/wp-calypso/issues/49899

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

No way for the user to get chat access, only email

**Comment by Greatdane** [comment]
Seen an issue like this before (or at least chatter). It does not happen all the time as we have all had many users in chat with broken Jetpack connections. I am not sure the specific circumstances it happens. 

@Automattic/happops - can I check if this is an internal issue that may be best on your own repo?

**Comment by Nic-Sevic** [comment]
@Greatdane This issue only occurs if the user has a single site that is Chat eligible with a broken connection. Many users have multiple sites that are eligible (for example a Premium an a Bus site) and as long as one of those is live, chat will work fine. However, if they only have a single site, they will be unable to access chat

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on P2 - No
- Tested on Simple - No
- Tested on AT ✅ 
- Tested on Self-hosted - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context - I was able to replicate this where the only contact method was via email where the only site on the account was Pro, there were chat slots available but there was no option to chat

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by vykes-mac** [comment]
@Nic-Sevic The as you mention when the user has a single site and that connection is broken then Calypso cannot read that users site hence the user is loaded as not having any sites. Although the user does is eligible for chat, if calypso cannot load any sites for them then chat won't work. Removing the check for existing sites will make that chat works, although there are other conditions such as happy chat is available. 

The fix is to remove the check that ensure the user has existing sites before establishing a check connection, however I'm not certain if this might cause other issues at the moment, I'm still doing some additional tests.

**Comment by vykes-mac** [comment]
fixed in this PR https://github.com/Automattic/wp-calypso/pull/65141
