### ISSUE TITLE
Pricing discrepancy on Jetpack Search

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#63233]
### Quick summary

When I tried to add Jetpack Search to my site, it says it’s $3/mth billed annually. But when it’s added to my cart it’s charging $144 (CAD)

### Steps to reproduce

1. On an AT site with currency set as CAD, go to Jetpack > Settings > Performance
2. Click the Upgrade option for Jetpack Search
3. Page displays an introductory price of $3/month billed yearly (discounted from $6/month)
4. Proceed to checkout and the amount in the checkout is $144 (though you may have to have clicked the Upgrade button twice)

https://user-images.githubusercontent.com/42655541/166343818-899c28aa-34c6-41b1-b713-85eed26639f8.mp4

Another test on USD site, after first click of the upgrade button - it's not reflecting the discounted price, but is still the right regular price:

https://user-images.githubusercontent.com/42655541/166343937-761c873b-4acd-4e28-88fb-df8427fd4ec2.mp4

After second click of the upgrade button, the cost doubles the regular annual price:

https://user-images.githubusercontent.com/42655541/166343950-9b71b412-c2f4-4acf-aa92-912102001e06.mp4

In both cases we chose to "Empty cart" when leaving the checkout.

### What you expected to happen

I expected the checkout to reflect $36CAD when I added it to my cart. (And $30USD on the second example.)

### What actually happened

The cart reflected double the price of the regular, non-discounted cost.

### Context

Stumbled on this because of internal testing for another purpose.

I'm not sure what to mark severity as but I suspect this might be happening for anyone trying to add Jetpack Search?

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

**Comment by andrii-lysenko** [comment]
Thank you for the detailed description. The task was created and we will keep this issue updated.
