### ISSUE TITLE
Editor: pasting image URL into editor on Safari/Chrome doesn't display image

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#6323]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post in Safari or Chrome (desktop)
2. Paste an image URL into the editor

#### What I expected

Image is displayed in editor (Firefox works correctly)

#### What happened instead

Nothing - the image has been inserted but not shown - unusual behaviour - the remove image cross appears - switching to HTML view and back displays the image

#### Browser / OS version

OSX 10.11.5 Chrome Latest Safari Latest

#### Screenshot / Video

**Safari**

![insert image url](https://cloud.githubusercontent.com/assets/128826/16367966/909f252e-3c6c-11e6-9dba-7ff875f16899.gif)

**Firefox OK**

![firefox](https://cloud.githubusercontent.com/assets/128826/16367996/d60c1202-3c6c-11e6-8090-6c931bd8c29a.gif)

#### Context / Source
 #dogfooding

**Comment by kristarella** [comment]
Seconded. I just had this happen to me while testing something else.

**Comment by lancewillett** [comment]
I tried this today with Safari 10.0 on OS X 10.12 and the image URL paste worked as expected. 👍 

Feel free to re-open if you can still repeat it the original issue.
