### ISSUE TITLE
Pages: for a new page, Comments and Pingbacks checkboxes in More Options should be unchecked to start

### ISSUE THREAD

**Issue by hafizrahman** [Automattic/wp-calypso#6324]
#### Steps to reproduce
1. Check site setting and make sure comments and pingbacks are enabled
2. Start a new Page at https://wordpress.com/page/ , enter some random title and content
3. Expand the "More Options" tab on the sidebar, to make sure that "Allow Comments" and "Allow Pingbacks & Trackbacks" are both checked.
4. Click "Save" or wait a little bit until the editor autosaves itself.
5. Check the "More Options" tab again. "Allow Comments" and "Allow Pingbacks & Trackbacks" are both now un-checked.

Interestingly this only happens for Pages and not on Posts.

This also does not happen if you edit an existing Page and updates it.
#### What I expected

"Allow Comments" and "Allow Pingbacks & Trackbacks" should not be un-checked after saving/autosave.
#### What happened instead

"Allow Comments" and "Allow Pingbacks & Trackbacks" are both un-checked after saving/autosave.
#### Browser / OS version

Tested on Chrome OS X, latest version.

 #user-report 2714578-t

**Comment by jeremeylduvall** [comment]
This also happens in wp-admin as well as in Core. My hunch is that pages ignore the default comment/pingback settings and default to false. In that case, the fix here would be to default the boxes to unchecked on a page.

**Comment by jeremeylduvall** [comment]
Yep—It looks like this is expected occurrence from Core:

https://make.wordpress.org/core/2015/07/06/comments-are-now-turned-off-on-pages-by-default/

It looks like we need to uncheck these boxes by default if we're loading a page.

**Comment by lancewillett** [comment]
Per the original title:

> Pages: Comments and Pingbacks automatically disabled when a new Page is saved

I think we should reflect default WordPress behavior here, as per the criteria laid out in that post by Mel.

As Jeremey says, the solution for a better UX would be to uncheck those options in the Calypso Editor by default. I'm updating the title here to make it more actionable.

**Comment by lancewillett** [comment]
This came up again in a conversation about NUX (new user experience) — it's confusing when you have a new page and it allows comments, especially if you don't intend to have a blog or community specifically. You might just want a simple landing page with static content.
