### ISSUE TITLE
Seller Exp - Refactor thunk usage in onboarding to latest version of wp-data

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#63246]
Once #60161 is merged in, we can remove and refine our usages of wp-data in stepper onboarding to more cleanly use the thunk architecture without the experimental flag.

A good example of what this looks like in practice is the [getAutomatedTransferEligibility](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/automated-transfer-eligibility/resolvers.ts#L9) resolver in the `automated-transfer-eligibility` data-store.

Top priority resolvers to refactor are:

* [`site` data-store](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/site/resolvers.ts)
* [`products-list` data-store](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/products-list/resolvers.ts)

Time-permitting, we could look at other pre-existing stores to see if we want to tackle those.

**Comment by blackjackkent** [comment]
Tagging @alshakero and @Automattic/vertex - is this something that you're aware of or already working on? Or are you all right with Serenity taking the lead on doing this refactoring?

**Comment by alshakero** [comment]
Hi @blackjackkent! Not only alright with you taking the lead, I'd appreciate it a lot!

It's worth mentioning that often, `react-query` proved better than WP stores (and I love WP stores), so definitely worth considering. [This is a small PR refactoring from a store property to a query](https://github.com/Automattic/wp-calypso/pull/63241/files), please take a look and do whatever you see fit 👍🏼 

I'm also happy to review your PRs if needed.

**Comment by markbiek** [comment]
@Automattic/serenity I'm going to tackle the products-list refactoring since it's a nice, self-contained little thing.

**Comment by markbiek** [comment]
@Automattic/serenity Starting on the site data-store resolvers.

**Comment by markbiek** [comment]
Products-list data store update is done and merged. Site data store is out for review.

Not sure what data-stores we may want to tackle after this but I'm unassigning myself for now.

**Comment by blackjackkent** [comment]
@markbiek Are those the only stores relevant to our Woo work specifically? If so, I think we can go ahead and close this when the relevant PRs are merged.

**Comment by markbiek** [comment]
> @markbiek Are those the only stores relevant to our Woo work specifically? If so, I think we can go ahead and close this when the relevant PRs are merged.

Those seem to be the only stores with resolvers that are relevant.

I've updated #63472 so that it will close this issue as well as #63468
