### ISSUE TITLE
Patterns: Core patterns are not available on simple sites

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#63245]
### Quick summary

On some simple sites, core patterns (those that come from WordPress.org) are missing in the editor.

What's more confusing is that this doesn't seem to be 100% reproducible.

This was first noticed[ from this test failing](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/editor-tracking/editor-tracking__pattern-events.ts). While it fails the majority of times on trunk CI, it has also passed a few times, meaning the pattern was present. While testing on my own personal simple sites, I am unable to find core patterns.

### Steps to reproduce

1. Go to the page/post editor
2. Open the sidebar inserter
3. Search for "Two columns of text and title" -- A core pattern
4. Search for "Heading and text in two columns" -- An A8c pattern

### What you expected to happen

Both patterns are available.

### What actually happened

On simple sites, the core pattern is not visible. 

### Context

[Failing E2E test](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/editor-tracking/editor-tracking__pattern-events.ts).

### Simple, Atomic or both?

Simple

### Reproducibility

Intermittent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

No real work around that I can find.

**Comment by Greatdane** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by dpasque** [comment]
@ianstewart -- on this comment on this post: pdqkMK-nr-p2#comment-368, you mentioned that pattern maintenance falls under the purview of Expand. I saw this issue was sitting in the "other" category -- should it go under one of the Expand team columns?

**Comment by cometgrrl** [comment]
@autumnfjeld Could Lego take a look at this?

**Comment by autumnfjeld** [comment]
> While testing on my own personal simple sites, I am unable to find core patterns

Could you share these sites @dpasque? In case that is helpful to our troubleshooting.  Thankyou.

**Comment by taipeicoder** [comment]
@dpasque @Greatdane since this is an old issue, would you be able to check if this issue is still reproducible? Thank you!

**Comment by miksansegundo** [comment]
The core patterns from the Dotorg Pattern Directory [wordpress.org/patterns](https://wordpress.org/patterns) are patterns submitted by the user [WordPress.org](https://wordpress.org/patterns/author/wordpressdotorg/) and fetched from the endpoint `/wp/v2/pattern-directory/patterns`. 

We do not show those patterns on simple sites, only on Atomic sites. I think this is not a bug, it's a feature request. cc: @taipeicoder @autumnfjeld 

I don't see any core patterns being added in the [test](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/editor-tracking/editor-tracking__pattern-events.ts) mentioned in the description. I see patterns from the Dotcom Library. The pattern `a8c/simple-two-column-layout` in the test "From the sidebar inserter" and `a8c/about-me-card` in the test "From the inline inserter". cc: @arthur791004

**Comment by autumnfjeld** [comment]
@dpasque I'm changing the title of this issue to remove the word "some".

**Comment by miksansegundo** [comment]
@autumnfjeld a more accurate title would be "Patterns: Core patterns are missing on simple sites"

**Comment by autumnfjeld** [comment]
FYI: @cometgrrl  Removing the Pri High label because this isn't breaking anything and isn't degrading the user experience IMO.    See slack convo p1684289687191959/1684221763.696889-slack-CRWCHQGUB on needing to understand if we actually want to surface .org Pattern Directory Patterns.   This could have been a deliberate feature decision.

To learn more:  have a read  on @miksansegundo's Core Patterns on Dotcom sites pekYwv-Ca-p2

**Comment by dpasque** [comment]
Sorry everyone, just catching up on this issue thread right now! 🙇 

Thank you so much for the extra info and context! I'll be honest -- I didn't know a lot of the nuance of all these pattern categories and their existing limitations on Simple sites.  (I think I mostly got thrown off by the prefixes.) All the info you provided is so helpful! 😄 

I'm totally comfortable with setting this as a normal priority feature request, and I personally do not think it warrants any kind of further urgent attention. 👍 Cc @autumnfjeld & 

Just to double check, are you also comfortable with that @cometgrrl ? I'll go ahead and update the labels now, but feel free 
to undo any of those changes if you disagree!

**Comment by cometgrrl** [comment]
@dpasque @autumnfjeld  This works for me! I agree with you both, thanks for the context in all the comments, it's very helpful.

**Comment by arthur791004** [comment]
Closing it as it's completed via D110980-code.
