### ISSUE TITLE
Plans overhaul: Cleanup - revisit use of "Flexible" in plans logic

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#63249]
### Details

A lot of logic for the new plans is built around the term `FLEXIBLE` e.g. stemming from [product constants](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-products/src/constants/wpcom.ts). The new free plan is effectively treated as a Flexible plan type right now, albeit not sure if there's anything "flexible" in it (especially with the Starter plan coming at play).

We ought to revisit and clean these at some point as/when we finalize these new plans.

**Comment by southp** [comment]
Ah, great point, @chriskmnds . Thanks for raising it and documenting it here.
I'm moving it into the Backlog for now since I feel it can be done after the current phase is done. However, please let me know if you feel the other way :)

**Comment by chriskmnds** [comment]
> I'm moving it into the Backlog for now since I feel it can be done after the current phase is done. However, please let me know if you feel the other way :)

Sounds perfect. Definitely more of a later phase cleanup.
