### ISSUE TITLE
Libre 2 showing galleries incorrectly

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#63269]
### Quick summary

* Theme is Libre 2
* The home page is set to latest posts
* On this theme when you add a gallery to a post, it should show on the home page in the same format as the gallery was set in the post itself. e.g. if images were side by side they should show side by side.
* This occurs on posts above the "older posts" button but not underneath it. Here the galleries have been stacked
* Personal plan (no plugins, no third party code)

### Steps to reproduce

Go to - empireoflights.com
Scroll down
Click older posts
Scroll down to Black Mirror III
The images are stacked on top of each other
Go to the actual post
The images are in a gallery side by side
 

### What you expected to happen

The site to work like the theme does

### What actually happened

The images stack

### Context

5186729-zd

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Libre 2

### Severity

One

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context- seems to have been fixed as its now appearing correctly for me - 
<img width="1548" alt="Markup 2022-05-12 at 13 12 58" src="https://user-images.githubusercontent.com/83325600/168141408-f9fb467e-5f7a-44f5-941b-4a6bc82ed0fc.png">

📌 ACTIONS
- Closed as no longer relevant/Fixed

**Comment by kerrynicl** [comment]
How post used to appear -
<img width="861" alt="Markup 2022-05-12 at 13 16 16" src="https://user-images.githubusercontent.com/83325600/168142011-7602a4b8-1709-48c0-ba51-44ba1fef1b0b.png">
