### ISSUE TITLE
One-time donation incorrectly displays a notification for a 'next payment'

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#63267]
### Quick summary

The user reached out to us about the following notification they see for a one-time donation they received. The message states that `your next payment is on 04 May 2022` even though it is not a re-occurring donation. 

<img width="651" alt="Markup 2022-05-04 at 14 52 59" src="https://user-images.githubusercontent.com/21261509/166625135-366422e5-75d1-48ae-8c12-a6af13778c1f.png">
 
I have checked the purchase history of the user who donated and can confirm that it was just a one-time donation. However, the notification sent to the owner states that there is a 'next payment'. 

### Steps to reproduce

1. A user made a one-time donation via the Donations Form.
2. The owner of the site receiving the donation checks their notification and can see the following message: 

```
Your first subscriber, [username], purchased your One-time donation at [sitename]! This subscription was sold for US$100.00, and your next payment is on 04 May 2022.
```

### What you expected to happen

The same notification without the `and your next payment is on 04 May 2022`.

### What actually happened

A message stating when the next payment is. 

### Context

The user reached out in chat:

35373830-hc

Follow-up ticket: 5188534-zd-woothemes

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by Greatdane** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No - WordPress.com specific issue (donation block)

📌 SCRUBBING
- Tested on AT ✅  - can confirm on AT site, assumed calypso-wide. 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context (your findings and where were you able to replicate the issue) 
- Uploaded file (if needed)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Greatdane** [comment]
One-time donations also show as a subscription, which is confusing;

<img width="763" alt="Markup 2022-05-13 at 13 46 56" src="https://user-images.githubusercontent.com/5075840/168213062-7885b6d0-5f94-45ee-8197-17964ac44cf5.png">

**Comment by Greatdane** [comment]
Note: I have closed the original ticket, but please reach out to user once the issue is resolved.

**Comment by rcrdortiz** [comment]
> One-time donations also show as a subscription, which is confusing;

This seems like a different issue not related to the original issue. 

> One-time donations also show as a subscription, which is confusing;
> 
> <img alt="Markup 2022-05-13 at 13 46 56" width="763" src="https://user-images.githubusercontent.com/5075840/168213062-7885b6d0-5f94-45ee-8197-17964ac44cf5.png">

This seems like a different issue not related to the original problem. I've created [a separate issue for it.](https://github.com/Automattic/wp-calypso/issues/64600)

**Comment by rcrdortiz** [comment]
@Greatdane & @rw-ye This issue has been solved, feel free to reach out to the user.
