### ISSUE TITLE
CPT: Expand thumbnail on clicking in list view

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#6327]
As in the [drafts list](https://wpcalypso.wordpress.com/drafts), the post's thumbnail should act as a toggle for expanding its size. When hovering a post item's thumbnail in the list view, the cursor should change to a zoom-in magnifying glass (`cursor: zoom-in`). Upon clicking, the thumbnail should expand to embiggen itself. When next hovering the thumbnail, the cursor should change to a zoom-out magnifying glass (`cursor: zoom-out`).

![zoom](https://cloud.githubusercontent.com/assets/1779930/16379447/a28532a6-3c3f-11e6-8114-61f81e13a726.gif)

_Note: This preview shows the drafts list, not custom post types list._

**Comment by folletto** [comment]
I had a chat with @mtias about this feature, and I feel the current design shouldn't be implemented as is. It was a bit of a patch to provide the feature quickly, so, here's an updated design:

![post-zoom-i2-zoom](https://cloud.githubusercontent.com/assets/4389/16733857/2adc9284-477b-11e6-96f8-acfe2e431c44.png)

Initial state:

1. On desktop, the lens icon appears only on `:hover`, but hovering on the whole card, not just the thumbnail, which helps discoverability (currently lacking, I wasn't even aware the thing was there!).
2. On mobile, the lens is always visible.
3. Tapping on the thumbnail triggers the zoomed state.

Zoomed state:

1. Proportions of the image are preserved, to some sensible minimum we should define.
2. Contains the title of the post, thus the Editor is still fully accessible.
3. The actions are to the right, where the user just clicked, thus minimizing mouse movement.
4. The actions are: edit the featured image, delete it, and zoom out.
5. The top part with title and icons has a black gradient to enhance contrast on white images.
6. Notice a 1px border on the edge of the image, to hint it's still inside the card.

Ideally, the `gridicon-search` and `gridicon-cross` icons should be replaced with proper `zoom-in` and `zoom-out` Gridicons. We could alternatively use the full screen icon (see [thread](https://github.com/Automattic/gridicons/issues/40)).

**Comment by aduth** [comment]
Does the post card's height expand to show more of the image? Or is the image overlapping post cards below?

>The actions are: edit the featured image, delete it, and zoom out.

These actions are specific to the thumbnail? Do you think there could be confusion that these would act on the post itself (i.e. edit the post, delete the post)?

>Proportions of the image are preserved, to some sensible minimum we should define.

From the concept, it looks like the image is being cropped some. Is this intended (setting a max-height)?

/cc @hugobaeta

**Comment by hugobaeta** [comment]
> From the concept, it looks like the image is being cropped some. Is this intended (setting a max-height)?

@folletto this should probably be consistent with what we do elsewhere, but I'd say the height should be constrained to the same dimension as width, since we're cropping the image here to a square. do you agree?

**Comment by folletto** [comment]
> These actions are specific to the thumbnail? Do you think there could be confusion that these would act on the post itself (i.e. edit the post, delete the post)?

Good point. The idea is having them related to the image. The edit specifically opens the Featured Image editing, so it should be ok, deleting might be far more ambiguous tho. Maybe we can remove delete? Any idea to make it more clear?

> Does the post card's height expand to show more of the image? Or is the image overlapping post cards below?

Ah sorry, it's not super clear from the mock. The idea is that the card expands to fit the image vertically, so all the other cards are pushed down. In practice the list still works as a fully working list.

> but I'd say the height should be constrained to the same dimension as width, since we're cropping the image here to a square. do you agree?

Since this is effectively a zoom feature and not a preview like the thumbnail, I'd say that the image shouldn't be cropped. The thing I'm not sure how to deal with is for images that are too thin in one of the two dimensions.

**Comment by aduth** [comment]
>The idea is having them related to the image.

Speaking for myself, my expectation on seeing these is that they'd open the editor or delete the post. As for making it clearer... maybe use a different icon for this interaction, like `<Gridicon icon="image" />` ? We should also think through how this will work. Will the media modal appear on the list screen for them to choose a different thumbnail? If so, it's worth pointing out that there may be some technical challenges in using the media modal outside the editor (hopefully few, as it was designed to be standalone).

Also, more as an FYI in case it's not already obvious, but the image is not always the featured image of the post. It may instead be an image extracted from post contents if a featured image is not explicitly set. It's meant to be the canonical image of the post.

**Comment by folletto** [comment]
> Speaking for myself, my expectation on seeing these is that they'd open the editor or delete the post.

I think this has to be evaluated not in isolation, but in the flow: imagine that you just clicked on the image. So the context might already clarify this enough. Keyword being: _might_.

> Will the media modal appear on the list screen for them to choose a different thumbnail? If so, it's worth pointing out that there may be some technical challenges in using the media modal outside the editor (hopefully few, as it was designed to be standalone).

Good pointing out. Let's take the design as something "ready" to allow that flow, even if we don't do that in the first iteration. I don't think it's a must have.

> the image is not always the featured image of the post

Thanks for pointing this out too.

This is probably a broader discussion, so while I don't think it should be anything but the featured image (the admin interface should be in total user control, not a fuzzy algorithm like the Reader – which is instead perfect for the reader), I'm also ok in not discussing the whys and the possible alternative approaches now.
