### ISSUE TITLE
Insert button (+) symbol hovering on content.

### ISSUE THREAD

**Issue by annbingle** [Automattic/wp-calypso#63279]
### Quick summary

The user reported that the + symbol (insert block) is hovering on the content unlike before.

The + symbol still works but the user is not happy with the blue line overlapping on the   content.

I tested it from my test site and I can replicate the issue as well.

Issue is seen on both Simple and AT site.

### Steps to reproduce

1. Create a content with any block then hover the cursor at the bottom of the block.

https://user-images.githubusercontent.com/40605613/166676991-42aeaff7-6906-46ea-ba55-4c83f0add0bf.mp4

### What you expected to happen

Once you hover your cursor under the block, the + symbol should be displayed at the bottom of the block.

### What actually happened

Instead of the + sign appearing at the bottom, it appears overlapping at the top block.

### Context

34648280-hc

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No. Tested it on different themes and same issue is seen.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

I don't see any other workarounds.

**Comment by adelineyaw** [comment]
User report: 35383144-hc
User report: 35442734-hc

Issue can be seen in Chrome and Firefox

**Comment by happychait** [comment]
User report in 35386239-hc

**Comment by jordesign** [comment]
An additional internal report in https://github.com/Automattic/wp-calypso/issues/63333

**Comment by fullofcaffeine** [comment]
Hi! 👋🏻 Thanks for reporting this. I tested and this also happens in a vanilla WPorg instance (`wp-env`) running GB 13.1.0 (the current version we have in WPCOM simple/AT at the time I write this) so it looks like a GB core bug. Could you please report it as an [issue in the Gutenberg GH repository](https://github.com/WordPress/gutenberg/issues)? 

https://user-images.githubusercontent.com/81248/167216640-bb578a12-0136-42e8-8984-40c7ce446265.mp4

**Comment by creativecoder** [comment]
It appears this issue was introduced by https://github.com/WordPress/gutenberg/pull/40441

cc @youknowriad

**Comment by annbingle** [comment]
Another report here 5195875-zd

**Comment by annbingle** [comment]
Hi @fullofcaffeine Thank you for your response. Based on the comment from @creativecoder this has already been introduced in https://github.com/WordPress/gutenberg/pull/40441 . Would you like me to still move it to  Gutenberg GH repository?

**Comment by formosattic** [comment]
User reports from https://github.com/Automattic/wp-calypso/issues/63282:

* 35381367-hc
* 5187733-zen
* 5189591-zen

**Comment by zyousafi** [comment]
Another report here #5198955-zen

**Comment by talldan** [comment]
> Would you like me to still move it to Gutenberg GH repository?

This has already been reported to the Gutenberg repo - https://github.com/WordPress/gutenberg/issues/40738. No need to make another issue.

**Comment by youknowriad** [comment]
Hi folks! sorry for the regression here, I'm happy to take a look.

**Comment by youknowriad** [comment]
I've opened [WordPress/gutenberg#40919](https://github.com/WordPress/gutenberg/pull/40919) which solves the issue in my testing but I'd appreciate help confirming that.

**Comment by jamiepalatnik** [comment]
Another report: 35431962-hc

**Comment by cuemarie** [comment]
Just FYI to HEs who run into this, looks like https://github.com/WordPress/gutenberg/pull/40919 will resolve this issue and has been merged to Gutenberg 13.3. That means we can expect to see that fix in around 2 weeks for AT sites, and a little longer for Simple sites.

Thanks @youknowriad for the quick fix!

**Comment by Greatdane** [comment]
Another report; 5203200-zd-woothemes

**Comment by wiesenhauss** [comment]
Something I noticed: this bug appears depending on the browser window size. For higher resolution screens and bigger browser windows, the insert button and blue line are in the right place. For smaller windows, the bug appears. Example:

**3000x1600 browser window:**

<img width="703" alt="Screen Shot 2022-05-14 at 07 54 56" src="https://user-images.githubusercontent.com/99455043/168422814-47843d4b-d851-4eab-a343-614dbe237d7f.png">


**1600x1000 browser window:**

<img width="701" alt="Screen Shot 2022-05-14 at 07 55 09" src="https://user-images.githubusercontent.com/99455043/168422822-5272ed73-e14f-4a26-a95f-d07d0f14f56b.png">


This explains why some people can reproduce this and others can't. Also, it doesn't happen for every paragraph/block - usually just the middle ones.

**Comment by jordesign** [comment]
Another case in 5217339-zd-woothemes - to let user know once it is resolved on Simple Sites.

**Comment by dolgelukkig** [comment]
Another example 5217915-zen, user would like to be updated once it's resolved.

**Comment by arinoch** [comment]
One more. 5206188-zd-woothemes

**Comment by danielbachhuber** [comment]
Fix [released in Gutenberg v13.2.1](https://github.com/WordPress/gutenberg/releases/tag/v13.2.1). I replied on the open Zendesk tickets accordingly.

**Comment by cuemarie** [comment]
_Decision was made here: p1683245378229639-slack-C0160HSMDQV that batch replies for users impacted by this issue will not be sent out._

**Comment by youknowriad** [comment]
@cuemarie Thanks for your comment but please be aware that this is a WordPress repository and that internal codes or links should ideally not be shared here. Thank you.
