### ISSUE TITLE
Add block button preventing text editing

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#63282]
### Quick summary

In the gutenberg editor, the add block button will sometimes overlap text that you are trying to select and edit. This happens inconsistently. 

Not sure if this is a p2 issue, a theme issue, or a gutenberg issue. We didn't find any recent merges that seemed obviously related

### Steps to reproduce

1. edit a post or page in gutenberg editor on a p2
2. click around until the add block gets in the way
3. if you hover to get the add block to show you can also see how it overlaps with the content above

### What you expected to happen

this button and the placeholder should appear in the space beneath blocks

### What actually happened

add block placeholder is in the way

![Screenshot 2022-05-04 at 15 59 21](https://user-images.githubusercontent.com/12064241/166686180-91f40a45-f762-4629-b610-6fe7eb31c090.png)

Happens at last second
![2022-05-04 at 14 21](https://user-images.githubusercontent.com/47717887/166685434-27fb4026-8db9-49e2-b449-c9d0d58fca13.gif)

### Context

while editing p2 posts

### Theme-specific issue?

maybe p2020? It's inconsistent so hard to tell

### Browser, operating system and other notes

for sure Chrome

### Reproducibility

Intermittent

**Comment by radtechgh** [comment]
possible issue match reported here: 5187733-zen

**Comment by brittanygray902** [comment]
Seeing the same issue here: 35381367-hc

Theme: Apostrophe 2

Add block button is preventing editing, as seen here:

<img width="704" alt="Screen Shot 2022-05-04 at 5 45 26 PM" src="https://user-images.githubusercontent.com/80774825/166849014-d99f5cb4-1d8b-4b8b-ab17-4d4e080be9b4.png">

AT or Simple? - Simple site


Was able to replicate this issue by adding the same theme & attempting to add a block. 

User mentioned this was seen on both Firefox & Safari

**Comment by radtechgh** [comment]
Another report: 5189591-zd

**Comment by cuemarie** [comment]
Thanks for these reports! Merging this report over here: https://github.com/Automattic/wp-calypso/issues/63279
