### ISSUE TITLE
[Bug]: Galleries with captions are not formatted correctly in emails

### ISSUE THREAD

**Issue by robfelty** [Automattic/wp-calypso#63297]
### Quick summary

If a post has a gallery with captions on the images, the captions end up in boxes next to the image and are not readable. I have seen this now on emails from [butterfly mind site](https://andreabadgley.blog/2022/05/04/a-walk-through-nice/) as well as my own personal site fedibblety.com

Here is a screenshot of the issue from an email I received recently from the above butterfly mind post:
<img width="385" alt="Bildschirmfoto 2022-05-04 um 15 39 50" src="https://user-images.githubusercontent.com/19924/166726441-f03ab034-84c0-4ad9-9555-94938dbaf7a7.png">

### Steps to reproduce

1. Subscribe to fedibblety.com
2. Wait for an email after a post is published

### What you expected to happen

I expect that the captions on the images in galleries are formatted in a nice way, such that the caption is readable

### What actually happened

The gallery does not look very good, and the captions are pretty much not readable.

### Browser

Mozilla Firefox

### Other notes

Here is another screenshot. You can see that individual images are fine, but that galleries are not
<img width="1082" alt="Bildschirmfoto 2022-05-04 um 18 26 41" src="https://user-images.githubusercontent.com/19924/166727135-3b248f71-ca3c-44eb-a223-74629e7f882c.png">

I use the standard Gmail browser based email client.

When viewing using Apple mail on my iPhone, it looks better (not great, but better)

I think the issue might have to do with galleries set to multiple columns - when formatted for phone they are in one column and look okay, but gmail on the web seems to be an intermediate width which does not look good.

Here is on my iphone:
![IMG_0049](https://user-images.githubusercontent.com/19924/166728143-99529ed5-a5b6-4be0-9908-7f40d6f8ed94.jpg)

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
Another case in #5200305-zen

![image](https://user-images.githubusercontent.com/6737345/167542944-08bcb913-b233-4bcb-a565-731ce63585dc.png)

![image](https://user-images.githubusercontent.com/6737345/167542962-a78d83f7-a450-4367-925c-06d2f35b7181.png)

**Comment by edequalsawesome** [comment]
Another case in 5292396-zen

**Comment by robfelty** [comment]
Any updates on this bug?

**Comment by TimBroddin** [comment]
@robfelty  This bug is now fixed and deployed!
