### ISSUE TITLE
Dotcom Marketplace Onboarding: Add "Conditional Shipping and Payments" to the Dotcom Marketplace

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#63300]
#We'll add the **[Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/)** Woo extension to the marketplace

FG page with all the instructions - PCYsg-AhC-p2

Here are 2 examples (one from Bespin and one from Explorers) of recent integration works:
https://github.com/Automattic/wp-calypso/issues/62302
https://github.com/Automattic/wp-calypso/issues/62311

It might be good to pair up, and work closely together — and have extensive public (threaded) chats on Slack, so that pairs can learn from each others.

Code changes:

* Add constants: D80207-code
* Add mapping: D80209-code
* Add feature check: D80218-code / 937-gh-Automattic/wpcomsh
* Add translation: D80236-code
* Add product entry: D80435-code
* Remove a12 flag: D81089-code

**Comment by rcrdortiz** [comment]
Blocked until we resolve 615-gh-Automattic/dotcom-manage
