### ISSUE TITLE
Classic Block Quote Button Not Working With Multiple Paragraphs Selected

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#63302]
### Quick summary

When using the Classic block and you have multiple paragraphs selected, the "quote" button only applies to one of the paragraphs. The "quote" button works as expected when individual paragraphs are selected.

### Steps to reproduce

1. Create a new post.
2. Add the Classic block
3. Add 3+ paragraphs to the Classic block.
4. Select multiple paragrahs
5. Click the "quote" button in the toolbar.

https://user-images.githubusercontent.com/93800099/166806762-f661a72b-ad48-4edb-90e9-d9690830671e.mp4

### What you expected to happen

All selected paragraphs would have the "quote" button applied.

### What actually happened

Only one paragraph has the "quote" button applied.

### Context

Discovered here:  5187300-zd-woothemes

Tested on a test site and was able to reproduce consistently.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Regular blocks such as Quote or Pullquote could be used in place in quoted text in the Classic block.

**Comment by Greatdane** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS
- Closing, as I believe it relates to the same issue on core; https://github.com/WordPress/gutenberg/issues/40676
- Added the video above and information to the core issue. 

📌 ACTIONS
- Closed as duplicate of #000000
- Closed as no longer relevant (issue resolved by #000000)
