### ISSUE TITLE
Marketplace: Infinite requests on `dotorg` when filter plugin by author

### ISSUE THREAD

**Issue by lupus2k** [Automattic/wp-calypso#63315]
When filtering plugins by author, sometimes enter in a loop requesting pages to `dotorg` infinitely.
I found the problem does not affect all authors, and I selected some authors to make tests.

##### Affected by the issue 
`mailpoet`, `wpforms`, `yaniiliev`, `elemntor`

##### Not affected by the issue
`google`, `azaozz`, `yoast`, `takayukister`

#### Steps to reproduce

1. On your browser, open the `developer tools` and go to the Network tab.
2. Go to `/plugins/:site?s=developer:"mailpoet"` (replace :`site` with your site).
3. You will see infinite requests to `https://api.wordpress.org/plugins/info/1.2/?action=query_plugins`

**Comment by allilevine** [comment]
From planning: May be fixed by refactoring.
