### ISSUE TITLE
[Bug]: Activating marketplace plugin doesn't report status accurately

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#63329]
### Quick summary

In `marketplace_post_transfer_manage_software` on wpcom assumes that if `woa_async_ssh_command` doesn't return a WP_Error then the command succeeded. This isn't the case, a WP_Error means it couldn't run the command, not that the command ran successfully.

### Steps to reproduce

Intermittent, depends upon other issues, modifying the command to run to be e.g. `ls z` should work as an artificial example.

### What you expected to happen

A log message to be made when there are errors with the command with an appropriate level, e.g. at least notice.

### What actually happened

An info level message was recorded saying 'Software activation success'

### Context

Discovered while testing marketplace products

### Simple/Atomic

Atomic

### Other notes

The code should check the `status` (exit code) field returned from `woa_async_ssh_command` in addition to the WP_Error checks.

### Reproducibility

Intermittent

**Comment by BogdanUngureanu** [comment]
Handled in D80817-code (RfR).

**Comment by BogdanUngureanu** [comment]
r246115-wpcom
