### ISSUE TITLE
Videos with ' and " could not be uploaded to media library

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#63326]
### Quick summary

When uploading video names

The issue appears to be occurring specifically to video files. Attempted uploading image with similar file names is not affected

### Steps to reproduce

1. Visit https://wordpress.com/media/
2. Upload a video where the video file name contains either `'` or `"` characters

### What you expected to happen

VIdeos can be uploaded successfully without any issues

### What actually happened

The "1 file could not be uploaded because an error occurred while uploading." error appears on media library, with 

### Context

The following errors are visible when viewing on browser console.

```
96235.f76a0b03de7e71152e18.min.js:1 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://public-api.wordpress.com/rest/v1.1/video-uploads/137160641/, response code: 403, response text: {"success":false,"data":{"error":"Access Forbidden","message":"Invalid Mime"}}, request id: n/a)
    at i.value (89564.627acc0912f7ed4cdb8c.min.js:2:265405)
    at 89564.627acc0912f7ed4cdb8c.min.js:2:267277

7801.2154582fcb6dba044003.min.js:1 Uncaught (in promise) Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://public-api.wordpress.com/rest/v1.1/video-uploads/137160641/, response code: 403, response text: {"success":false,"data":{"error":"Access Forbidden","message":"Invalid Mime"}}, request id: n/a)
    at i.value (89564.627acc0912f7ed4cdb8c.min.js:2:265405)
    at 89564.627acc0912f7ed4cdb8c.min.js:2:267277
```

![image](https://user-images.githubusercontent.com/34882260/166905787-3f452ba3-f0cc-49b2-a54c-bd6b286ff340.png)

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

- Upload video from wp-admin
- Remove `'` and `"` characters from the video file name.

**Comment by edwinho89** [comment]
Maybe a similar issue to https://github.com/Automattic/wp-calypso/issues/50928 ?

**Comment by Robertght** [comment]
I can confirm this is an issue with video files containing & as well. 

#5196950-zen

cc @coder-karen or @brandonpayton

**Comment by coder-karen** [comment]
I don't seem to notice an issue on Jetpack connected sites, also uploading via WordPress.com (using Chrome). But then, also couldn't replicate on Atomic, using `"` and `&` in the file names (for a `.mov` file). I'm not sure what the expected behaviour is though - it may be better if someone from the VideoPress team takes a look at this - cc @roundhill @pgk perhaps. Otherwise the Calypso team may have some insight.

**Comment by jgcaruso** [comment]
Hi there, this has been addressed in https://github.com/Automattic/wp-calypso/issues/62903

We deployed a fix and files with special characters should be able to be uploaded.
