### ISSUE TITLE
[Bug]: Editor sibling inserter appears in wrong place

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#63333]
### Quick summary

Sometimes it is possible to get the sibling inserter to appear in the wrong place:

![image](https://user-images.githubusercontent.com/1277682/166918915-01b72679-ec9e-4a51-8d21-8ea715b0c040.png)

This seems to be content specific.

This may be a general Gutenberg problem, but I'm unable to reproduce it outside of wp.com so I'm filing it here to start with.

### Steps to reproduce

1. Use Twenty twenty Two
2. Start a new post, add a title, add an image, and add two more paragraphs
![image](https://user-images.githubusercontent.com/1277682/166918989-69797a06-1d5b-49cc-8046-1ea4e482dd77.png)
3. Place cursor in the first paragraph
5. Try and hover over the sibling inserter. It should appear over the first paragraph, not below it
![image](https://user-images.githubusercontent.com/1277682/166918915-01b72679-ec9e-4a51-8d21-8ea715b0c040.png)
7. Position cursor on second paragraph
8. Try and hover over the sibling inserter. It now appears at the bottom of the image
![image](https://user-images.githubusercontent.com/1277682/166919118-fbc07465-dd44-4dff-828b-d602bfe01fe4.png)

### What you expected to happen

It to appear in the right place

### What actually happened

It appeared in the wrong place.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by jordesign** [comment]
Thanks for reporting @johngodley  - I'm just going to merge this additional report into our existing user reports of the issue 👍
https://github.com/Automattic/wp-calypso/issues/63279

**Comment by johngodley** [comment]
Ah, sorry for the duplicate - I searched for different terms!
