### ISSUE TITLE
Marketplace: Plugin gets installed but not activated, review marketplace plugin activation flow to see how it works.

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#63330]
### Problem summary
When installing the Product Bundles WooCommerce plugin without WooCommerce installed WooCommerce gets installed and then the plugin gets installed but not activated.

This doesn't happen if WooCommerce is installed before the plugin is bought from the Marketplace.

### Investigation
The 'Software activation success' log message (see https://github.com/Automattic/wp-calypso/issues/63329 for making this less misleading) includes this detail:
```
{
    "exec": "REDACTED",
    "command": "wp plugin activate woocommerce-product-bundles --skip-plugins=$(wp plugin list --field=name | grep -v '^woocommerce$' | tr '\\n' ',') --skip-themes ",
    "stdout": "",
    "stderr": "Warning: The 'woocommerce-product-bundles' plugin could not be found.\nError: No plugins activated.",
    "status": 1
}
```

i.e. the plugin can't be activated because it isn't installed.

It appears that there is a race condition between installing plugins and activating them. We think this is the cause of the problem but it is perhaps odd that it is triggering consistently on this plugin but no others.

Installation and activation happen within `marketplace_post_transfer_manage_software` on wpcom

Installation uses `WPCOM_Sites_on_Atomic::site_manage_software`, which uses the `site-manage-software` atomic API (see `site_manage_software_endpoint`). This queues an async job to install the software:
```
$job_id = $this->atomic->queue_async_job(
	(object) array(
		'atomic_site_id' => $site->atomic_site_id,
		'actions' => $actions,
	),
	'site_manage_software',
	$server->server_name
);
```

and then later `marketplace_post_transfer_manage_software` uses `woa_async_ssh_command` to synchronously activate the plugin.

This means if the installation of a plugin, and it's dependencies is slow then the activation might fail.

### Workaround
The user can go to the installed plugins page and manually activate the plugin

**Comment by BogdanUngureanu** [comment]
Fixed in D80817-code (RfR).

**Comment by BogdanUngureanu** [comment]
r246115-wpcom
