### ISSUE TITLE
Renewal Email Notification Missing Subject Line

### ISSUE THREAD

**Issue by zyousafi** [Automattic/wp-calypso#63347]
### Quick summary

The user got an email notification from us about a renewal, but the email notification was missing a **Subject** line so the user thought it was a fake email.  They've renewed, but they said it didn't look good and I agree with them.  I checked **Logstash**, and the user was right.  We sent an email without a **Subject** line, and the date and time of the email on **Logstash** is messed up as well

Note from @michaeldcain: I redacted most of this issue's details because it contained private data. The original is here: 2c9df-pb

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Updated main description of report - No


📌 FINDINGS/SCREENSHOTS/VIDEO
I'm not even sure how this can be replicated but definitely some further investigation is needed as I'm seeing the log with the empty subject line:

<img width="371" alt="Markup 2022-05-18 at 15 47 42" src="https://user-images.githubusercontent.com/83325600/169158366-ff11ce42-5ccf-4290-a8ba-e170234d45eb.png">
📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cometgrrl** [comment]
@michaeldcain would this be a shillings bug? 

It's unclear how reproducible it is, and I'm not sure how easy it would be to check if we can see other cases of it happening.

**Comment by michaeldcain** [comment]
@cometgrrl: I've added this to the Shilling Inbox

**Comment by deancroyal** [comment]
User returned to let us know that, again, the most recent renewal email contained no subject line. Moreover, the user shared that the body copy was lacking in an explanation of what the renewal was for. hc-35701205

**Comment by michaeldcain** [comment]
@zyousafi: I edited most of this issue content to remove private information. There's a FG page about what kind of information should be shared in public repos: PCYsg-68j-p2

**Comment by DavidRothstein** [comment]
Previously reported: pNPgK-5JQ-p2

**Comment by michaeldcain** [comment]
@DavidRothstein noted that this might be related to Professional Email subscriptions - additional information being added to the P2 post.

**Comment by DavidRothstein** [comment]
Note this also causes the first paragraph of the email (the one that would explain the product that is being renewed) to go missing as well.

**Comment by michaeldcain** [comment]
Adding defaults in D82966-code
