### ISSUE TITLE
Anchor: Custom Podcast title does not get saved/carried over to new site

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#63348]
If you set a new site title in the podcast title step (different from the one auto-filled by Anchor during signup) it does not show up for the new site when you land in the editor. Not sure if this is an error on the front end with the store/site creation, or something on the back end. Needs investigation.

**Comment by sixhours** [comment]
👋 @valterlorran are you still looking into this one?

**Comment by valterlorran** [comment]
Not at the moment. Feel free to assume it!

**Comment by sixhours** [comment]
I'm not convinced this is a bug after looking at the code; the podcast title (not the site title) is shown in the content when the site is created, and this is how it's worked since launch:

`/wp-content/mu-plugins/anchor.php#59`

I don't think we should change this unless it's caused confusion among actual users.
