### ISSUE TITLE
Seller Exp - WooCommerce onboarding should include help link

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#63354]
The existing WooCommerce onboarding behavior in /start has a help link in the bottom right of all screens; when clicked it opens an in-screen help menu:

![CleanShot 2022-05-05 at 15 17 52@2x](https://user-images.githubusercontent.com/13437011/167018649-e6881329-d59c-45f2-80f4-edbd4616d05c.png)

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/13437011/167018772-43421f47-4be9-4951-a478-37c902e572ee.png">

We need to implement this in the stepper

**Comment by simison** [comment]
👋  Let's add this back everywhere else in the flows as well if it was previously, not just Seller.

**Comment by andres-blanco** [comment]
> 👋 Let's add this back everywhere else in the flows as well if it was previously, not just Seller.

Yes! Once https://github.com/Automattic/wp-calypso/pull/63470 is merged it will appear on every step of the flow.
