### ISSUE TITLE
Customizer: Update FSE support link to use .com instead of .org docs

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#63351]
### Quick summary

AFAIK, on all WordPress.com, we use the `wp-admin` page for the customizer. 

If you're on an FSE theme, there's a little banner guiding you to use the site editor. The link there for support documentation takes you to .org docs. We should take the user to our slightly more focused .com docs!

### Steps to reproduce

1. Have an FSE theme on the site (I used twenty twenty-two (blue) )
2. Go to Customizer
3. Click on the link in the top left:
![Screen Shot 2022-05-05 at 12 50 51 PM](https://user-images.githubusercontent.com/26772342/166983431-3a917fcc-cf6f-481b-8cbe-2c06e79eb575.png)

### What you expected to happen

I land at https://wordpress.com/support/site-editor/

### What actually happened

I landed at https://wordpress.org/support/article/site-editor/

### Context

Empathy challenge

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Not entirely, just need one that is FSE but also still has Customizer.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Those docs are still relevant, and it's easy to go to our .com docs anyway.

**Comment by Greatdane** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on TT2, but customizer only seems to show on Simple sites;

<img width="1409" alt="Markup 2022-05-13 at 14 22 10" src="https://user-images.githubusercontent.com/5075840/168216436-e72b5db5-150c-4d81-bb36-39fee7598133.png">


📌 ACTIONS
- Marked as Triaged for Quality Squad review
