### ISSUE TITLE
Discounts not being applied to the Pro plan at checkout

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#63365]
### Quick summary

When a user is eligible for a discount, the discount rate is not applied when they complete payment.

### Steps to reproduce

1. Go through the checkout flow as a new user eligible for any current discounts on the Pro plan.
2. Checkout will show you the discounted price. Click to pay that price.
3. Check your billing receipt.

### What you expected to happen

Discount should be applied.

### What actually happened

Checkout shows the discount, but full price is charged.

### Context

Reported in 32790489-hc.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Users will need to raise an issue with happiness, who can see the current discount if any on the user's checkout page. Happiness can then issue a refund to reflect the amount the user should have been charged.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- This is likely too far out of date, as now the Pro plan is legacy. However, I did add a Pro plan to my cart and tried applying a coupon, and it correctly notified me that the plan was not eligible for the discount - preventing me from purchasing something at a higher cost than what checkout was telling me.

📌 ACTIONS
- Closing as not reproducible
