### ISSUE TITLE
Plans Overhaul: Update checkout thank-you pages for Starter & Pro plans

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#63376]
### Details

Apparently, after a user upgrades to a paid plan (from `/plans`) they get redirected to a "thank you" post-checkout page. These pages are tailored per plan and highlight the various features their new plan offers. Example from Pro plan checkout:

<img width="1128" alt="Screenshot 2022-05-05 at 1 59 37 PM" src="https://user-images.githubusercontent.com/1705499/167115893-814d0817-eab6-438c-8d80-ba21ff2b4f49.png">

We ought to introduce one for the Starter plan, and potentially revise/update the one for Pro (as per @lucasmendes-design). More context in P2 chat: pdgrnI-WP-p2#comment-1721

### Checklist

- [ ] Add/update thank you checkout pages in [client/my-sites/checkout/checkout-thank-you](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/checkout/checkout-thank-you)
- [ ] Confirm upgrading to Starter and Pro from `/plans` renders these new pages after checkout

**Comment by claudiucelfilip** [comment]
Opened https://github.com/Automattic/wp-calypso/pull/63446 to add the Thank you page. It's changes based on the #63247 because we need the Starter plan configs and checks to enable the page.
