### ISSUE TITLE
Emails: Comment moderation email design does not match other emails

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#63399]
### What

The comment-moderation email does not match the look and layout of the newly redesigned notification emails

### Why

The design of emails related to site/blog management was recently overhauled, but this one appears to have been missed.

### How

The comment moderation email still looks like this:

![_Kathryn_Presner__Please_moderate___From_Jupiter_to_Comet__-_kathryn_a8c_com_-_Automattic_Mail](https://user-images.githubusercontent.com/7662449/167298727-c32cebbb-9e64-43ac-894f-a4aeea0bc628.jpg)
 
But it should match the new email design, more like this:

![_Kathryn_Presner__Comment___From_Jupiter_to_Comet__-_kathryn_a8c_com_-_Automattic_Mail](https://user-images.githubusercontent.com/7662449/167298760-886579e3-9767-46b4-aeb1-4973b326ff27.jpg)

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context - I was able to replicate in testing 
<img width="607" alt="Markup 2022-05-12 at 13 41 28" src="https://user-images.githubusercontent.com/83325600/168146148-274c2f77-b50d-49b7-b83f-c3f5f79d495f.png">


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by mashikag** [comment]
This was done as part of pdDOJh-wY-p2
