### ISSUE TITLE
Editor: Can't remove link with inline dialog

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#634]
The close icon is being covered by a gradient [here](https://github.com/Automattic/wp-calypso/blob/a7478174b0441760c332fcb4b8c454f5b8d73dfc/client/components/tinymce/style.scss#L381-L383).

<img width="180" alt="screen shot 2015-11-24 at 9 29 51 am" src="https://cloud.githubusercontent.com/assets/5835847/11370231/c9ce1f66-9290-11e5-827b-f6e2ba4541e6.png">

**Comment by timmyc** [comment]
Does this only happen in a particular browser?  Looks like this was either fixed, or I can not re-create it in Chrome.

**Comment by kellychoffman** [comment]
It was in Chrome but it doesn't seem to be happening anymore. Going to close this.
