### ISSUE TITLE
Map block: Access token required to use Map Block when it should not be required

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#63400]
### Quick summary

When trying to insert a Map block in a page or post, the block shows a message "To use the map block, you need an Access Token."

![CleanShot 2022-05-08 at 15 41 20](https://user-images.githubusercontent.com/51966986/167302219-fd32a3c2-8392-4492-9b14-07356af07ba0.png)

### Steps to reproduce

1. Create a new page/post
2. Add a Map Block

### What you expected to happen

The Map block should display a map and allow the addition of markers, changing settings, etc

### What actually happened

The Map block prompts for an access token.

### Context

Reported in 35420568-hc

### Simple, Atomic or both?

Atomic

### Severity

One

**Comment by philnick206** [comment]
Also see p1652022582869259-slack-C0CMN0V97

**Comment by Greatdane** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ❌  
- Tested on AT ❌
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tried on several WordPress.com test sites (Simple and AT) without issue. Self-hosted sites ask for a key. Perhaps it was a temporary issue? 

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
