### ISSUE TITLE
Admin bar: The admin bar hides the top line of text when following an anchor link

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#63406]
### Quick summary

When clicking on a anchor/page-jump link, the heading/text being linked to is obscured by the admin bar.

This was previously reported in 6781-wpcom, but that issue was closed as the fix for this had to come from Core.

As of WordPress 5.9 this issue has been [fixed in Core](https://core.trac.wordpress.org/ticket/46371), but it's still present on WordPress.com simple sites.

### Steps to reproduce

1. Create a post or page and add some content.
2. Somewhere in the content, add a heading, and give it a HTML anchor under the Advanced tab of the block settings.
3. At the top of the post, add a link targeting that HTML anchor
4. Publish the post. Then visit it and click the link

### What you expected to happen

For the target heading to be positioned just below the admin bar, as happens on a self-hosted or Atomic site:

![Screen Capture on 2022-05-09 at 09-19-41](https://user-images.githubusercontent.com/11873759/167361502-9b89eda4-2d96-4f0e-ad6c-643ee13d0593.gif)

### What actually happened

The target heading gets obscured by the WordPress.com admin bar

![Screen Capture on 2022-05-09 at 09-14-10(1)](https://user-images.githubusercontent.com/11873759/167362365-75dd196a-659e-4b90-8e58-046cfc39fe86.gif)

**Note:** I'm not able to replicate the issue on a Jetpack site with the wpcom toolbar setting enabled either. I'm only able to replicate on a simple site.

### Context

Reported by a customer in https://wordpress.com/forums/topic/anchor-bug/?view=all

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Add a spacer block with a height of 1px directly above the element that's the target of the anchor link, and add the id attribute to the spacer block instead. This way the spacer block appears behind the admin bar, with the heading appearing directly below.

**Comment by Greatdane** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Confirmed on Simple sites

<img width="859" alt="Markup 2022-05-25 at 14 02 02" src="https://user-images.githubusercontent.com/5075840/170183500-f75ae9f5-c731-4fe8-8ea3-5fd813693499.png">

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by vykes-mac** [comment]
Based on the fix that was done in [core](https://core.trac.wordpress.org/changeset/52198). It seems the issue relates to our themes, If we use themes twentyseventeen,T16 the issue does not appear on simple sites. I will continue to look further into this

@KokkieH what theme did you use to reproduce the issue?

**Comment by KokkieH** [comment]
@vykes-mac My test site was on Hever when I made that screen recording, but I'm not able to replicate it in that theme any more. Also checked Maywood - working correctly there as well.

I can still replicate it in Blask, Gateway.

**Comment by vykes-mac** [comment]
I have created a fix here D82416-code

**Comment by vykes-mac** [comment]
fix shipped here D82416-code

**Comment by KokkieH** [comment]
Thank you!
