### ISSUE TITLE
Classic Block: Inconsistent results when cutting content from the block using keyboard shortcuts

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#63403]
### Quick summary

Cutting multiple paragraphs of text from the Classic Block using keyboard shortcuts (CMD+X / CTRL+X) provides an inconsistent experience:

Highlighted text across multiple paragraphs is intermittently removed when "cut" using a keyboard screenshot. 

Other times, the highlight applied to the text is removed when "cut" using a keyboard screenshot but the text remains visible.

In all cases, text is still added to the device clipboard.

### Steps to reproduce

1. Create some dummy text in a Classic Block spanning multiple paragraphs consisting of single or multiple lines of content each.
2. Experiment with highlighting multiple paragraphs (all/some) and using a keyboard shortcut to copy, cut or paste the content. The experience is inconsistent but repeatable.

### What you expected to happen

I expected to be able to cut multiple paragraphs of content using a standard keyboard shortcut.

### What actually happened

I was not able to consistently cut multiple paragraphs of content using a standard keyboard shortcut.

### Context

5199775-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

Not reproducible on self-hosted sites.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

- Using the right click menu to cut content.
- Still using keyboard shortcuts: first cut a single paragraph, pasting it back in, and then selecting multiple paragraphs.

**Comment by Greatdane** [comment]
Going to close this, as I think it relates to the same issue on core; https://github.com/WordPress/gutenberg/issues/40676
