### ISSUE TITLE
Inconsistent cursor placement and incomplete selection in editor

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#63421]
### Quick summary

When trying to select text in the editor, sometimes you are not able to click to move the cursor. Then, when you try to click and drag to select text it the selection will start from where the cursor is stuck, making it difficult to select at all or to select the correct/entire text as intended. 

I've also seen something similar happen on the front end of published p2 posts but I haven't been able to capture that yet.

### Steps to reproduce

1. open the editor
2. add some content (seems to happen more commonly when text in group blocks/lists)
3. try to select text 

### What you expected to happen

You should always be able to click and move the cursor and when moved you should be able to select until you're done dragging without the selection getting cut off or unselecting.

### What actually happened

Sometimes the cursor can't be moved on the line and when a selection is attempted you can't select the whole line.

![2022-05-09 at 17 22](https://user-images.githubusercontent.com/47717887/167433828-e6d454e5-2b0a-4d29-bb85-63e6a33784ec.gif)

### Browser, operating system and other notes

Chrome Version 100.0.4896.127
Mac monterey 12.3.1 

### Reproducibility

Intermittent

**Comment by Greatdane** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to replicate

📌 ACTIONS
- Await author feedback

📌 Message to Author
 - @Nic-Sevic Could you provide any more info on how to replicate this? Certain themes or blocks? I am unable to replicate this (tried list block as you have, along with FSE and classic thems).

**Comment by Nic-Sevic** [comment]
@Greatdane 
Unfortunately I do not have much more information than above. This happens inconsistently but often enough to be super annoying.

It seems to happen in all types of blocks and the places I'm noticing it most are when editing posts in the block editor for 9F6qB-p2, P9HQHe-9-p2, or dtR3Z-p2

In addition, when it happens I typically can't delete the selection

**Comment by JoshuaGoode** [comment]
I encounter this or something similar regularly, will try to reproduce later.  Some of it seems it might be P2 specific. 

Here's another similar report I encounter sometimes:

https://github.com/WordPress/gutenberg/issues/41003

**Comment by inaikem** [comment]
Based on the above, I'm leaving this in the `Needs Author/HE Reply` queue. 

@JoshuaGoode, if you are able to reproduce this, please move this back into the `Needs triage` column of the `HE Triaging Board (new bugs)` board, thanks!

**Comment by Joshgrygiel** [comment]
📌 ACTIONS
Based on the conversation above, issue may be related to https://github.com/WordPress/gutenberg/issues/41003 and has gone a bit stale. Trying to reliably reproduce this on my end has been unsuccessful as well.

@JoshuaGoode @Nic-Sevic if you are able to reproduce this at all please feel free to re-open this report 👍
