### ISSUE TITLE
Twenty Fifteen Theme: Post list returns to classic view when clicking "all posts" link from within editor.

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#63422]
### Quick summary

When the default view is set on the site, it is reverting to the classic view when navigating from a post where changes have just been made. The link from within the editor used is the "View Posts" link. This issue is intermittent and doesn't happen every time.

5201097-zen

### Steps to reproduce

1. Open any post on https://zompocshinobi.com/
2. Make an edit and save the post.
3. Exit to the post list using the "View Posts" link
<img width="294" alt="Screen Shot 2022-05-09 at 11 28 43 AM" src="https://user-images.githubusercontent.com/34966264/167444180-f94159a2-7c2a-4b79-bf42-9025eaea2629.png">
.

### What you expected to happen

For the post list to show in the default view when exiting the editor via the "View Posts" link after a post is updated.

### What actually happened

The view shown for the post list sometimes reverts to the classic view.

### Context

The issue does not happen every time you exit an updated post via the "view posts" link. It happens roughly 1/2 to 1/3 of the time. 

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Atomic. The theme is Twenty Fifteen but I have not been able to reproduce it on test sites with any theme.

### Browser, operating system and other notes

This happens to the user on Firefox. I can also confirm it happens on Chrome.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No but the platform is still usable

### Workaround details

No known workaround other than continuing to have to switch the dashboard back to the default view.

**Comment by Robertght** [comment]
@CodeAllNightNDay I cannot replicate this either.

Because this is site-specific at the moment, please publish it as a P2 post in +happinessfeedback. 

Closing this for now.
