### ISSUE TITLE
Block Editor: Add Block Unexpected behaviors

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#63437]
### Quick summary

The "Add Block" + icon on the Editor is causing some unexpected behavior such as showing line over the previous block and jumping to the next paragraph/element after clicking it. 

I was able to reproduce this on both Simple and Atomic regardless of the theme

### Steps to reproduce

Issue:#1

1. Create a new page on a Simple or Atomic site.
2. Add different blocks such as headings and paragraphs on the editor.
3. Save the changes and reload the editor.
4. Observe the position of line introduced by "+" icon. On some sections, the line is overlapping the previous block.

Issue #2

1. Create a new page on a Simple or Atomic site.
2. Add different blocks such as headings and paragraphs on the editor.
3. Add a large image or a paragraph after the heading block.
4. Save the changes and reload the editor.
5. Click on the line introduced by "+" icon. You will notice that the editor jumps to end of the next section.

### What you expected to happen

1. The line should not be overlapping the previous block.
2. Clicking on the line should not make the editor jump to a lower section of the content.

### What actually happened

Screenshots / recordings:

1. 

<img width="965" alt="image" src="https://user-images.githubusercontent.com/33957570/167532929-81130c2c-1361-42d8-b78a-28bfa2aba7dc.png">

<img width="869" alt="image" src="https://user-images.githubusercontent.com/33957570/167532980-ae28b971-c911-4408-ac33-17b4b07fc18c.png">

2. 
![Uploading Screen Capture on 2022-05-10 at 08-26-54.gif…]()

Upload to Github is not working. Here's the screen recording: https://d.pr/i/HWYkXp

### Context

User report: [35437387](35437387-hc)
Followup: 5202473-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by msilbers** [comment]
I am also seeing this pretty consistently, and have had at least 2 reports before I found the issue reported. I can see it in my own sites as well, regardless of theme.

**Comment by arunsathiya** [comment]
- This is being tracked here: https://github.com/Automattic/wp-calypso/issues/63279 I think we can close the current report in favor of the other one.
- And a fix is already merged on core: https://github.com/WordPress/gutenberg/pull/40919
- It'll be available on Gutenberg 13.3.0.

**Comment by arunsathiya** [comment]
Closing in favor for the other report.
