### ISSUE TITLE
Theme Showcase: Download link on theme showcase page returns error 404

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#63434]
### Quick summary

We recently launched a few themes on WordPress.com only, without plans to submit them to WordPress.org. The problem is the theme download link that gets appended to the bottom of the showcase pages goes to WordPress.org and returns the 404 error. As a workaround, we manually added a download link to the individual theme showcase pages, but that results in two download links, one of which is broken.

### Steps to reproduce

1. Go to the theme showcase page for [Marl](https://wordpress.com/theme/marl/).
2. Scroll down to the bottom. Note there are two "Download" sections.
3. Click on the first "Download Marl" button - note it points to the .zip file hosted on WordPress.com.
4. Click on the second "Download" button (at the bottom of the page). Note it goes to WordPress.org and the page returns a 404 File not found.

![image](https://user-images.githubusercontent.com/4550351/167515610-089d1eae-9dd3-4f58-b61e-7c9a5f69925b.png)

### What you expected to happen

It would be great if we could fix the logic behind the auto-generated download link so that it points to WordPress.org for themes submitted to .org, and otherwise points to the .zip hosted on WordPress.com (if the .zip file exists).

### What actually happened

The auto-generated download section points to WordPress.org, resulting in the file not found error.

### Context

Initial report: https://github.com/Automattic/themes/issues/5672

### Reproducibility

Consistent

**Comment by nelsonec87** [comment]
Hi @alaczek!
I've tried to reproduce it with Marl and several other themes as well, but I always get the download link pointing to .com.
Can you still reproduce it?

**Comment by alaczek** [comment]
Marl download seems to be working now, but I can still see the issue on [Hari](https://wordpress.com/theme/hari/).

**Comment by sixhours** [comment]
I fixed Hari by generating the theme download in MC -- there was no ZIP generated until now. Closing this out!
