### ISSUE TITLE
Editor: inline colors on links not respected

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#63440]
### Quick summary

It's not possible to set a custom color on specific links using the "Highlight" option in the block toolbar. Whatever global style is set in the site editor overrides it.

### Steps to reproduce

1. Create a new post and add a paragraph, including some linked text
2. Change the one paragraph block's text color. The linked text will remain black
3. Highlight the linked text (and some adjoining words on either end, just to see this more clearly), and try to change the text to another colour using the Highlight button in the block toolbar.

### What you expected to happen

For the highlighted text to change to the new colour.

### What actually happened

Adding a custom color to the link directly has no effect.
<img width="473" alt="Cursor_and_Edit_Post_‹_kokkiestrialtestsite_—_WordPress_com" src="https://user-images.githubusercontent.com/11873759/167557095-e15a7b9e-8753-40b0-84e9-733c972e7eae.png">

Put differently, the link displays the colour set in Global Styles (be it via site editor or Customizer), or via the block colour controls, but not inline colours.

### Context

Reported by a user in https://wordpress.com/forums/topic/anchor-bug/?view=all

Found https://github.com/WordPress/gutenberg/issues/40214 which might be related.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

User who reported this is using Ames

I also confirmed on Archeo, Hari, Stow, so multiple themes are affected.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

It still works to change link color for an entire block via the block colour controls in the editor sidebar. But this workaround won't help if someone wants to change only a single link in a particular block.

**Comment by Greatdane** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - **Yes**

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Confirmed on core. Add to HE Cross-repo Watchlist.
- Core issue; https://github.com/WordPress/gutenberg/issues/40214

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Added to 'HE Cross-repo Watchlist' project board

**Comment by annezazu** [comment]
I couldn't replicate this as I found adding a highlight color remains when set, even if you change the overall paragraph color later. This is in line with how the styling hierarchy works:

https://github.com/user-attachments/assets/a3232bfd-fe37-43d4-8036-4432f77e5712
