### ISSUE TITLE
Plans Redesign: new plans upgrade button display

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6345]
We should only render an "upgrade now" button when the site can upgrade to that plan. We don't support self-service downgrades at the moment, so this means if I have a free plan I can upgrade to (Personal, Premium and Business). When I have a Premium plan I can only upgrade to Business.

For reference:

A site with a Business Plan:
<img width="758" alt="screen shot 2016-06-27 at 1 29 27 pm" src="https://cloud.githubusercontent.com/assets/1270189/16394690/520f47e0-3c6b-11e6-9489-6684e065a006.png">

A site with a Premium Plan
<img width="741" alt="screen shot 2016-06-27 at 1 29 39 pm" src="https://cloud.githubusercontent.com/assets/1270189/16394698/582c82e6-3c6b-11e6-97d8-02dae36d8393.png">

With the new plans page enabled `ENABLE_FEATURES=manage/plan-features make run`

Navigate to /plans.
Make sure the following views look correct:
- Select a site with a free plan
- Select a site with a personal plan
- Select a site with a premium plan
- Select a site with a personal plan
- Select a site with a business plan
- Select a Jetpack Site with a free plan
- Select a Jetpack Site with a premium (monthly or annual) plan
- Select a Jetpack Site with a professional (monthly or annual ) plan

**Comment by lamosty** [comment]
Hmm, so users can't downgrade to the Free plan by themselves? What if they cancel the Premium sub?

**Comment by gwwar** [comment]
> Hmm, so users can't downgrade to the Free plan by themselves? 

I should clarify that we don't allow downgrades on this `/plans` page. You can cancel/refund from purchases if its been recent enough.

**Comment by lamosty** [comment]
Alright, clarified. :)

**Comment by jeremeylduvall** [comment]
Fixed in #6469.
