### ISSUE TITLE
Marketplace: Show on the SearchBar that an action is required to search

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#63451]
### Problem

On the Plugins Browser page, if the user is trying to search plugins, there is no indication an additional action(press enter) is needed to search. It can be more confusing as in the past the search was executed without this action.

<img width="764" alt="Screen Shot 2022-05-10 at 09 11 53" src="https://user-images.githubusercontent.com/5039531/167636320-ca10a322-0840-42ce-8d2e-66c4dd2dc827.png">

### Suggestion
Instead of an `X` there should be a button to actually search. This way the user could use the mouse to execute the search and this same button could be "pressed" with the `Enter` key. 

----

Suggestion from: @galakhyati

**Comment by cpapazoglou** [comment]
@vinimotaa can we have your input here?

**Comment by cpapazoglou** [comment]
Related P2 pdh6GB-2Is-p2

**Comment by WBerredo** [comment]
All the following states should be implemented.

<img width="2399" alt="image-1" src="https://user-images.githubusercontent.com/5039531/226366215-c4930199-74cb-4673-9a52-1f3a53e3916e.png">

Figma link: f84fqtCG4pCnCh2Hq0But5-fi-6117%3A42880
