### ISSUE TITLE
Typo in SSL certificate pending section

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#63467]
### Quick summary

A customer shared that the word "hours" appears twice in the SSL pending message:

> It may take up to a few **hours hours** to add an SSL certificate to your site. If you are not seeing it yet, give it some time to take effect.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/3505172/167680786-1a8fe52a-bcf6-4d20-a0ff-7eff5e91b5ad.png">

### Steps to reproduce

I haven't been able to replicate this as I don't have an external domain to try it with. Also, I tried with a domain registered via wpcom, but the ssl was instantly active.

1. Connect a domain
2. Check SSL status at `https://wordpress.com/domains/manage/[DOMAIN HERE]/edit/[DOMAIN HERE]`
3. See the typo in the messaging before SSL is active

### What you expected to happen

There would be no typo.

### What actually happened

The typo appeared.

I'm not sure if it is simple/atomic/both

### Context

reported in 35443695-hc, no follow up ticket

**Comment by jordesign** [comment]
Confirmed this typo is in place - I can see it in the Calypso repo.

**Comment by jordesign** [comment]
@Automattic/nomado  As this is a simple typo change - I've put together a PR - would love your review

**Comment by delputnam** [comment]
This was fixed in #64000
