### ISSUE TITLE
Anchor: Check usage of generators in the related stores and refactor to thunks if necessary

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#63468]
Generators should be replaced with thunks following updates to the WP data store. I *think* all stores for Anchor are already accounted for (the flow uses the onboarding store and the site store IIRC) but we need to double check. Related to #63246

**Comment by markbiek** [comment]
@sixhours The site store will be taken care of once #63472 is merged.

The onboard store doesn't have any resolvers to update so I think we're good.
