### ISSUE TITLE
Marketplace: Add Clear button when category selected

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#63461]
See https://github.com/Automattic/wp-calypso/issues/62891
<img width="1141" alt="Screen Shot 2022-05-10 at 11 45 17 AM" src="https://user-images.githubusercontent.com/1689238/167669170-d1b27765-4873-4172-84c5-fb050ea3a5e1.png">

Acceptance criteria:
- [ ] We also show a “clear” text button that basically just takes us home (clears filters/search)

**Comment by lsl** [comment]
Going to close this with https://github.com/Automattic/wp-calypso/pull/63645 (once its merged), we just need to hook the `categoryName` ([see](https://github.com/Automattic/wp-calypso/pull/63645/files#diff-6750c272a1df0c496a26adc7ae59a20a6f9a7f1ca37f751b869ee40714e355f6R391)) up to it when we implement the new selector cc @Rolilink

**Comment by Rolilink** [comment]
> Going to close this with #63645 (once its merged), we just need to hook the `categoryName` ([see](https://github.com/Automattic/wp-calypso/pull/63645/files#diff-6750c272a1df0c496a26adc7ae59a20a6f9a7f1ca37f751b869ee40714e355f6R391)) up to it when we implement the new selector cc @Rolilink

Nice sounds good! A little lost but which new selector?

**Comment by lsl** [comment]
The category selector (not react selector)
