### ISSUE TITLE
Follower email customized text ignored in confirmation emails

### ISSUE THREAD

**Issue by syds87** [Automattic/wp-calypso#63495]
### Quick summary

After adding a custom text in `Settings > Reading > Blog Follow email text` and saving the settings, new subscribers will still see the default text for subscription emails, instead of the one saved in the settings.

### Steps to reproduce

1. Go to `Settings > Reading`
2. Type some custom text in `Blog Follow email text`
3. Click Save Changes
4. Try subscribing to that blog with your email address.

### What you expected to happen

I expected to see my custom text in the confirmation email I will receive at my address.

### What actually happened

I received the standard confirmation email test, instead.

This is the custom text I've added to my settings:

<img width="748" alt="Screen Shot 2022-05-11 at 10 52 19" src="https://user-images.githubusercontent.com/70008187/167836868-4d7c7060-e459-43cf-9e89-04ea2b359ab6.png">

These are the emails I got when signing up:

<img width="865" alt="Screen Shot 2022-05-11 at 10 53 06" src="https://user-images.githubusercontent.com/70008187/167836959-fa868a05-c9e3-41a8-94ed-0febb73b01e7.png">

<img width="842" alt="Screen Shot 2022-05-11 at 10 53 32" src="https://user-images.githubusercontent.com/70008187/167836970-16678d54-36af-4cec-85d5-3ea3e91d40f4.png">

### Context

I've tried this on my test account for both a simple and an Atomic site.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

**Comment by galakhyati** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ❌ The `Reading` >`Blog Follow email text` option isn't available on the self-hosted site. Checked on Jurassic.ninja site. 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested on a simple as well as on an Atomic site and I was able to change the text, then when I subscribed to the site, I got the email showing the changed text on the setting.
- 
<img width="987" alt="Markup 2022-05-25 at 17 25 45" src="https://user-images.githubusercontent.com/7382505/170261402-a256d18e-28b9-49ba-8a3f-b7afac3114a0.png">

![Markup on 2022-05-25 at 17:47:03](https://user-images.githubusercontent.com/7382505/170261882-77d1a2c7-0a0e-4974-b2f8-9013239b59ab.png)



📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
