### ISSUE TITLE
Plans Overhaul: Confirm price displays in grid (decimals and yearly sums)

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#63501]
We need to confirm if the Plan prices ought to include decimals and yearly sums in the description (as per the design mocks):

- Confirm and update price displays (there are decimals in the design mocks e.g. $5.00 pdgrnI-WP-p2)
- Confirm and update including yearly price in plan description (per month, billed $60 yearly in design mocks pdgrnI-WP-p2)

_Originally posted by @chriskmnds in https://github.com/Automattic/wp-calypso/issues/63247#issuecomment-1123696377_

**Comment by chriskmnds** [comment]
Probably not as high priority as the same goes for Landpack changes and elsewhere (l believe neither include decimals and yearly sums in the updates either).

**Comment by southp** [comment]
It's a good thing to confirm as part of implementing the new design in the next phase for sure. Thanks for raising it :)

**Comment by gmovr** [comment]
Closing this due to revert :)
