### ISSUE TITLE
Overlay menu does not work for same page anchor links on Blockbase themes

### ISSUE THREAD

**Issue by nicolynramos** [Automattic/wp-calypso#63527]
### Quick summary

When using the overlay menu on FSE/Blockbase themes with menu items linking to anchor tags on the same page, the menu links do not work.

### Steps to reproduce

1. Add anchor tags to items on a single page
2. Add links to navigation menu to the anchors on the same page
3. Enable the overlay menu on mobile-only or always
4. View overlay menu on live site and see that the links to anchor tags on the same page do not work

### What you expected to happen

The overlay menu should function the same as the standard menu- anchor links should jump to the corresponding block on the same page.

### What actually happened

Clicking menu items in overlay menu either causes menu to flash or no response at all. The menu remains open and the links do not take you anywhere.

### Context

I found a very similar report from last year on Varia themes here: https://github.com/Automattic/themes/issues/3520. Links to anchor tags on other pages not affected- only same page tags. Reported this time on 5204564-zen.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Blockbase themes

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Using a link shortener option such as bitly.com to replace the links in the menu works as a workaround.

**Comment by Robertght** [comment]
Thank you for reporting his @nicolynramos !

I cannot replicate this on my end. Is this happening with Blockbase and its child themes or a different theme?

**Comment by inaikem** [comment]
@nicolynramos, if you can provide the above context, we'll be able to get triage on this purchase forward, thanks! 🙏

**Comment by nicolynramos** [comment]
Sorry for missing this. Yes, Blockbase and it's child themes. Here are some screen recordings I took of the behavior with Blockbase activate and again with Hari.

https://user-images.githubusercontent.com/71851343/171438369-08fa6872-ecb8-4441-96ee-aa7411eb86bc.mp4


https://user-images.githubusercontent.com/71851343/171438383-c13c3526-31dd-4d43-9f46-c7b2d4f7301f.mp4

**Comment by Robertght** [comment]
I'm moving this to Needs Author/HE Reply for now and troubleshooting it outside GitHub. Will update the report once I'm done.

**Comment by Robertght** [comment]
@nicolynramos I have tested this and I can only replicate it on your website, but I'm not 100% why. I did find another report [here](https://github.com/WordPress/gutenberg/issues/37387) which is an indication it's more of an editor problem, not a theme-specific one.

Closing this for now.
