### ISSUE TITLE
Marketplace: Add submission success page

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#63554]
Add Marketplace submission success page at route /marketplace/submission-success (no site selector needed).
See pdh6GB-Ne-p2 ("We'll be in touch" design)

Acceptance criteria:
- [x] There is a Marketplace submission success page at /marketplace/submission-success
- [x] Clicking continue in the learn more section takes me to P2gHKz-oRE-p2
- [x] Clicking continue in the view the marketplace section takes me to [my plugins page](https://wordpress.com/plugins)

**Comment by allilevine** [comment]
@SaxonF Is there a Figma or image asset we can use? Is the design based on an existing page?

**Comment by SaxonF** [comment]
@allilevine I believe this layout has already been built, possibly as a success message after installing a plugin? SJ6I0rUUtHNdHMF2KMMJig-fi-311%3A5435

**Comment by allilevine** [comment]
Closed in https://github.com/Automattic/wp-calypso/pull/63680
