### ISSUE TITLE
Generated design picker: Responsive thumbnail height

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#63588]
## Description
Currently, thumbnails in the generated design picker have fixed height. We want to best make use of the vertical space in order to show as much of the design as possible, which is why we are interested in making the thumbnail height responsive to the viewport height. Note that this only applies to desktop resolution. 

See Figma 42PgVsdlQ1v2wpk6lmmrnq-fi-1697%3A54129 for reference.
Example screenshots:

100px (min-height): 
![Image](https://user-images.githubusercontent.com/797888/168206958-a742d267-1990-4882-8d48-811ac9bdfab6.png)

300px (max-height):
![Image](https://user-images.githubusercontent.com/797888/168207038-1d6f3067-0274-4941-80b0-e7ff94131193.png)

## Acceptance Criteria
* Make the thumbnails fit the remaining of the viewport height.
* As I resize the viewport, the height of the thumbnails should change accordingly to the updated viewport height.
* The "view more options" button height should remain fixed, and visible in the viewport.

## Dev tasks
* [x] Change the height of thumbnails to be responsive to viewport space
* [x] Responsive thumbnail height should have a minimum height of 100px.
* [x] Responsive thumbnail height should have a maximum height of 300px.
* [x] The "view more options" button should have 48px spacing under it.

**Comment by arthur791004** [comment]
Close as it's shipped 🚢
