### ISSUE TITLE
[Post by Voice] feature not successfully creating posts or adding media to library

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#63583]
### Quick summary

The "Post By Voice" feature appears to have stopped working entirely. The automated voice system, and phone call generation portion of the feature still works, but nothing happens on the site where a recorded post should land.

### Steps to reproduce

1. Visit your WP Admin Dashboard by adding /wp-admin/ to the end of your site’s url (e.g.: example.wordpress.com/wp-admin)
2. Click on Dashboard → My Blogs.
3. Click the Enable button under Post by Voice on the site you want to enable this feature for.
4. Call the generated phone number and enter your key
5. leave a message after the beep, and press # or hangup to end the message.

### What you expected to happen

According to our [Public guide doc](https://wordpress.com/support/post-by-voice/): Once you are done, a new post titled “Audio Post” will be published to your site. It will be assigned the default category and tagged with “Post by Voice”. The audio file itself will be stored in your Media Gallery and named audio-post-yyyy-mm-dd-unique-identifier.mp3 where the the italicized part of the file name will be replaced with the date of the post and a unique numeric identifier. 

### What actually happened

Nothing

### Context

Reported in the forums here: https://wordpress.com/forums/topic/post-by-voice-calls-are-not-being-routed-currently/?view=all

- This user reported that their last successful call was on **4-27-22**
- Some discussion ensued here: p1652394327067639-slack-C03TY6J1A

---

I then tested on 4 test sites, and the same error occurred across all of them: 

- Free Plan site
- Personal Plan site
- Business Plan site with no plugins installed
- Pro Plan site with no plugins installed

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No

### Workaround details

No workarounds for being able to post by voice

**Comment by cuemarie** [comment]
If you take a look at the link shared here: p1652397588079429/1652394327.067639-slack-C03TY6J1A - it appears that no posts by voice have successfully made it to WPcom since **2022-04-27**

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested Post By Voice and it worked for me on my test site. I'm also seeing new posts from other users from May 20th on.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

**Comment by dcoleonline** [comment]
Reopening

The last post by voice shows a date of July 13.
I tried this today on my test site roughly 20 minutes ago. No post has been created. No audio was uploaded.

The customer who reached out in chat has tried to record posts between July 13 and July 22 with no success.
Could someone take a look? We'll need to follow up with the customer once it is working again.

- [ ] 5416827-zen

**Comment by sophiegyo** [comment]
Another report in 5413039-zen

I tested it on a free site of my own and I also found it did not work.

**Comment by devNigel** [comment]
Another report: 5423141-zen

**Comment by happychait** [comment]
Another report in

- [ ] 5429535-zen

**Comment by renata-franco** [comment]
📌 SCRUBBING

- Tested on Simple ✅ 


------

📌 FINDINGS/SCREENSHOTS/VIDEO

I tried this on a Simple site only. I was able to replicate using the method explained [in the documentation.](https://wordpress.com/support/post-by-voice/)

I gave the process around 10 minutes to see if the MP3 or the post would be created, but nothing. 


------

📌 ACTIONS

- Marked as Triaged for Quality Squad review

**Comment by msilbers** [comment]
Adding a +1 because I also can't use this feature right now. It's particularly bad because theres no indication it's not working when recording the post

**Comment by obenland** [comment]
I spent some time today investigating what might have caused it. Just posted a summary of my findings and suggested next steps, including a road block I encountered here: pMz3w-gce-p2

**Comment by obenland** [comment]
Looks like Twilio now requires basic auth when requesting the voicemail file.

Fixed in r254647-wpcom.
