### ISSUE TITLE
Request: Site Statistic (Visitor Counter) Widget

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#63584]
### What

A new Widget for sites that provide Site Statistics such as page views.

### Why

Users really enjoy the ability to track and display site/page views and described in the following ticket. 
5210255-zd-woothemes

**Comment by Greatdane** [comment]
Basically, a public-facing visitor counter widget?

**Comment by Aurorum** [comment]
I'm a little lost having read this ticket - could the user not just add the Blog Stats widget for their use case? They don't seem to seek the unique visitors count. 

https://jetpack.com/support/extra-sidebar-widgets/blog-stats-widget/

**Comment by Greatdane** [comment]
@Aurorum it looks like the Blog Stats widget is a classic widget? Is there a block version of it for FSE themes that no longer have widgets enabled?

**Comment by Aurorum** [comment]
Ah, apologies, I misunderstood! Yes, I don’t think there’s a block equivalent.

@jeherve do you think this is something which would be worth converting into a Jetpack block? I imagine that it could be a fairly simple one.

**Comment by jeherve** [comment]
Yes, that would definitely be interesting! It's been requested in the past in https://github.com/Automattic/jetpack/issues/17588 so I'll close this issue as duplicate.
