### ISSUE TITLE
[Pro Plan Only] webp files receive an upload error when adding to media library 

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#63595]
### Quick summary

I only encounter this on the Pro plan when adding a webp file to the media library; 

`1 file could not be uploaded because an error occurred while uploading.`

<img width="789" alt="Markup 2022-05-13 at 16 26 06" src="https://user-images.githubusercontent.com/5075840/168233040-ca96c798-cd0f-4ee4-b5ec-0f6121c9c6de.png">

Note, that the file does upload successfully when you refresh the page. 

### Steps to reproduce

1. Have a site with the Pro Plan
2. Go the My Site → Media
3. Upload a `.webp` image. 

### What you expected to happen

The image should upload without an error message, like on all other plansany

### What actually happened

Received the error message `1 file could not be uploaded because an error occurred while uploading.`

### Context

User report; 35303430-hc

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

### Workaround details

User `wp-admin` or just refresh the page.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on Simple and AT, default and classic view, could not replicate.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

**Comment by Greatdane** [comment]
@jamiepalatnik I still get an error as of today - did you try on the Pro plan specifically? 

Today; 

<img width="802" alt="Markup 2022-05-26 at 16 08 05" src="https://user-images.githubusercontent.com/5075840/170436521-57e87f92-a321-46b2-af95-4fc6d897c7f8.png">

**Comment by jamiepalatnik** [comment]
@Greatdane Yes, I tested on the Pro plan simple and AT, default and classic view, and didn't see any errors.

Will leave this open in case someone else is able to test.

**Comment by Greatdane** [comment]
@jamiepalatnik I wonder if it is just certain webp files then. Are you able to try the file in the original chat (link is in the notes). 🙇

**Comment by jamiepalatnik** [comment]
> @jamiepalatnik I wonder if it is just certain webp files then. Are you able to try the file in the original chat (link is in the notes). 🙇

Sure, I tested with the file from the chat and got the error you reported. Seems like it could be an issue with that file, unless we can recreate with other webp files. It also doesn't seem to be only a Pro plan issue—I got the same error when testing uploading that file on another AT site with the Business plan, but not a simple site.

**Comment by jamiepalatnik** [comment]
📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
 - I am going to go ahead and close this since it seems like this issue is only happening with that specific file from the user report and does not depend on the site plan. I was not able to replicate with other webp files. If you can reproduce this issue with other webp files on a test site or if there are other user reports, please feel free to reopen with more details.
