### ISSUE TITLE
Unable to access Page Optimize plugin from Nav Unification

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#63627]
### Quick summary

It's currently not possible to access the Page Optimize plugin from the unified navigation dashboard. Based on this support document, it should be understand Performance tab, but under wp-admin dashboard design, but there's no way to switch to it:

https://wordpress.com/support/page-optimize/

>To add something to the exclusion list, click Settings > Performance on your wp-admin panel.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18581859/168416203-e87f8a63-7f3d-4870-b4ed-f304438f5dbc.png">

I remember Page Optimize being available under "Tools" tab but it's not available there either.

The only way to access Page Optimize is using the direct path at the moment: `/wp-admin/options-general.php?page=page-optimize` h/t @kdevnel 

### Steps to reproduce

- Start with an Atomic site, which has Page Optimize installed by default.
- Look for Page Optimize on the Calypso or wp-admin dashboard settings.

### What you expected to happen

Page Optimize should be visible somewhere on Calypso or wp-admin dsahboard.

### What actually happened

Page Optimize is not visible.

### Context

Found when working with a customer.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No.

### Browser, operating system and other notes

All.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Visit `/wp-admin/options-general.php?page=page-optimize`

**Comment by arunsathiya** [comment]
4942880-zen.

**Comment by jordesign** [comment]
Interestingly - when I check an Atomic site - I see this option in the Settings > Performance section - which links through to where I can manage the exclusions. I see this on both Pro and Business Plan sites..

<img width="692" alt="Screen Shot 2022-05-25 at 5 32 36 pm" src="https://user-images.githubusercontent.com/1842363/170206834-fed6bc9c-5fec-4118-b0eb-d486bf38fc1a.png">

@arunsathiya  Are you able to confirm if there was anything different or specific about your test site, and if you can recreate in multiple instances?

**Comment by inaikem** [comment]
@arunsathiya - checking in with you on the above request 🙏

**Comment by arunsathiya** [comment]
Sorry about the delay, y'all. Been traveling for a week and just got caught up with these pings. You are right, @jordesign, the option is indeed available on the Calypso performance page. It just wasn't visible on my test site because page-optimize was inactive. I see it after activating it. Closing this report as invalid.
