### ISSUE TITLE
Themes: change "Details" to "Info" in the current theme card

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#6363]
Current:

![screen shot 2016-06-28 at 11 52 44](https://cloud.githubusercontent.com/assets/4389/16412956/e4919ec2-3d26-11e6-94f4-bf808e20bb5e.png)

Change to:

![screen shot 2016-06-28 at 11 53 36](https://cloud.githubusercontent.com/assets/4389/16412970/f5af2ed6-3d26-11e6-8e65-5053348c2b91.png)

This to align it with #6342. 

/cc @melchoyce

**Comment by melchoyce** [comment]
It matches the icon better now 😄

**Comment by jeremeylduvall** [comment]
Closed via #6412.
