### ISSUE TITLE
Dyad 2: Not honoring use first image setting

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#63632]
### Quick summary

The Dyad 2 theme has a customizer setting to Automattically use first image in post, but it's not being honored and instead the site is displaying the second image in the post. 

<img width="1750" alt="Markup 2022-05-14 at 15 06 53" src="https://user-images.githubusercontent.com/42655541/168448198-44ffaee3-705b-4408-9e23-065cc17ff44c.png">

There is no Featured Image set on the posts.

When a Featured Image is set on the posts, the Featured Image overrides the "use first image in post" setting.

### Steps to reproduce

1. Simple site, Premium plan, Dyad 2 theme
2. Create a post with no featured image and include 2 images in the posts
3. Check off all of the boxes in the Customizer under the Content Settings for the Featured Image
4. Make sure the Homepage Settings is set to display Latest Posts

### What you expected to happen

I expected the first image in the post to display on the Homepage.

### What actually happened

The first image in the post is ignored.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Dyad 2

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

The work around isn't really "difficult" but with over 400 posts, setting the featured image on each of them is extremely labor intensive. However, setting the featured image would resolve the issue.

**Comment by cuemarie** [comment]
This report matches an open bug here: https://github.com/Automattic/themes/issues/6000

Closing in favor of that thread and sharing notes on this report over there
