### ISSUE TITLE
Enable native ActivityPub support for WordPress.com sites

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#63636]
### What

The ActivityPub protocol can be supported on WordPress sites through the use of this plugin: https://wordpress.org/plugins/activitypub/

However, there has been a request for WordPress.com to support this natively (for non-paid plans that don't have access to plugins). 

ActivityPub is a protocol for federated platforms such as:
[Mastodon](https://joinmastodon.org/)
[Pleroma](https://pleroma.social/)
[Friendica](https://friendi.ca/)
[HubZilla](https://hubzilla.org/)
[Pixelfed](https://pixelfed.org/)
[SocialHome](https://socialhome.network/)
[Misskey](https://join.misskey.page/)

### Why

Requested in: 5213999-zd

**Comment by jordesign** [comment]
+1 this would be a great feature to add in to help the democratization of publishing.

**Comment by pfefferle** [comment]
This is now possible 🎉

Announcement post: https://wordpress.com/blog/2023/10/11/activitypub/
Support page: https://wordpress.com/support/enter-the-fediverse/
