### ISSUE TITLE
[Bug]: Onboarding email preview starts with 'SET IN TEMPLATE'

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#63644]
### Quick summary

I recently received an onboarding email with the subject 'Boost your site traffic via social media'. 

In my email client, the preview text started with 'SET IN TEMPLATE', which was unexpected. It looks like the 'preheader' is not set in the template and Gmail is using this as the preview.

<img width="711" alt="Screen Shot 2022-05-16 at 16 47 14" src="https://user-images.githubusercontent.com/17325/168521904-27e00e34-e187-457c-827c-eda8c4962cf8.png">

### Steps to reproduce

1. Sign up for a new Pro account on dotcom.
2. Wait for the social media onboarding email to arrive after a few days.
3. Note that the preview in your email client starts with the text SET IN TEMPLATE.

### What you expected to happen

Email client preview should begin "Drive traffic using social media".

### What actually happened

Email client preview begins `SET IN TEMPLATE`.

<img width="1377" alt="Screen Shot 2022-05-16 at 16 46 35" src="https://user-images.githubusercontent.com/17325/168521830-bf0e8c23-5385-47ea-b820-a1eb4a280b39.png">

### Context

Set up a new blog for personal use

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by bluefuton** [comment]
This is the email in question:

<img width="741" alt="Screen Shot 2022-05-16 at 16 46 24" src="https://user-images.githubusercontent.com/17325/168522105-1ee0b77b-97fb-4b1f-a1ba-bfde097cfb85.png">

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I've created a new Pro site today - so I'll set this bug to "Need author/HE reply" for the moment and keep an eye out for that email.
- Also tried crowdsourcing the issue here, in case others who have recently created a Pro site might have examples: p1654114465552349-slack-C03TY6J1A

📌 ACTIONS
- Awaiting marketing email in a few days - on hold (in Needs author/HE reply) until then

**Comment by cuemarie** [comment]
**Triage update** - I still haven't received any emails with "Boost your site traffic via social media"  in the subject - however, my crowdsourcing worked, and @happychait shared that they received this email on June 1, and it did contain `SET IN TEMPLATE` at the beginning of the message preview:

![Markup on 2022-06-09 at 16:51:43](https://user-images.githubusercontent.com/27249804/172963623-08ea20e1-e501-429d-9c0e-936a7b58f382.png)

Browser Inspector information:

![yBdvdOoMrqq2ATPDDkBYTFjJRHmD7gRAXCpnXmFD](https://user-images.githubusercontent.com/27249804/172963677-1c91b49c-2389-48c4-9cc7-d77c68ed3539.jpeg)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by JoshuaGoode** [comment]
Received this email today, `SET IN TEMPLATE` was in preview

`calypso:marketing-onboarding-starter-3`

**Comment by JoshuaGoode** [comment]
Perhaps someone from @Automattic/martech  can take a look, forward along to the right place.

**Comment by dzver** [comment]
Tagging @bubel because he contributed to this work and might be the best to check it out.

**Comment by bubel** [comment]
Thanks for the ping. I'll take a look.

**Comment by bubel** [comment]
This has been resolved.

**Comment by bluefuton** [comment]
Thanks for fixing this @bubel!

Can we refer to the changeset here so others can see how it was resolved?
