### ISSUE TITLE
Plugin Details: billing interval switcher - convert to radio

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63684]
- [ ] Covert `BillingIntervalSwitcher` to a radio (or add variation depending on https://github.com/Automattic/wp-calypso/issues/63684#issuecomment-1128014918)
- [ ] Move it from the header to below the price

|Before | After|
|-------|------|
|![CleanShot 2022-05-16 at 21 40 25@2x](https://user-images.githubusercontent.com/12430020/168660442-e8222866-78ab-46b1-82a0-7c68e0b0b0c7.png)|![CleanShot 2022-05-16 at 21 40 43@2x](https://user-images.githubusercontent.com/12430020/168660497-7dfa0705-1a95-4ce9-9c07-ba2710758225.png)|

Epic Issue: https://github.com/Automattic/wp-calypso/issues/43332
P2: pdh6GB-sk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi

**Comment by cpapazoglou** [comment]
@SaxonF should we also use the radio component in the plugin browser?
![CleanShot 2022-05-16 at 21 45 07@2x](https://user-images.githubusercontent.com/12430020/168661222-b6f069fb-2a04-4860-8d74-8cedb2325e47.png)

**Comment by SaxonF** [comment]
@cpapazoglou what do you think about removing the price toggle completely from the list page? If someone changes the price setting from within a plugin, that will also be reflected in the list page. We would default to monthly.

**Comment by cpapazoglou** [comment]
> @cpapazoglou what do you think about removing the price toggle completely from the list page? If someone changes the price setting from within a plugin, that will also be reflected in the list page. We would default to monthly.

That's a very good idea, billing interval choice doesn't have to be so early in the flow.

**Comment by gcsecsey** [comment]
Grooming discussion:
- we should default to monthly price on the list page
- if the billing interval is updated on the plugins page, it should be reflected on the list page as well
- we shopuld investigate what the wrapped selector component renders, maybe it can already render a radio selector
