### ISSUE TITLE
Blockbase Theme: Text on top of each other

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#63691]
### Quick summary

Visiting the mobile version of the post page using the Blockbase theme or a child theme, like Marl:

![image](https://user-images.githubusercontent.com/3801502/169615346-9bcb6363-d63b-4a11-bfad-0848d4910147.png)

![image](https://user-images.githubusercontent.com/3801502/168684394-6d4ea635-f776-498e-b36b-3e8828a1be4f.png)

### Steps to reproduce

1. Select the Marl Theme
2. Open the blog in a Post page in mobile mode.

### What you expected to happen

The text should be readable.

### What actually happened

![image](https://user-images.githubusercontent.com/3801502/168684394-6d4ea635-f776-498e-b36b-3e8828a1be4f.png)

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by nelsonec87** [comment]
The issue seems to be an incompatibility between the theme and the `subscribe-to-blogs` mu-plugin.
The plugin adds the form fields, and the theme's style puts all in the same `grid-area`, which makes them overlap.

It's possible to fix changing the theme's css, but I'm not sure this fix belongs there since the problem is dotcom related.

![image](https://user-images.githubusercontent.com/3801502/169615926-0192ef0a-c232-4a21-b25e-cd4727863e87.png)

**Comment by blackjackkent** [comment]
Question for followup - is there a way to add wpcom-specific CSS for a theme? If not, we might not have much we can do here.

**Comment by blackjackkent** [comment]
@nelsonec87 spoke with the Themes team (@jeffikus) regarding this issue and they will be taking a look at it on their end after they are back from a meetup.

**Comment by pbking** [comment]
I believe we eliminated the grid CSS that we were using for non-wpcom comment forms and that resulted in this working as expected for wpcom comment forms.  This looks correct to me now; Can you confirm?

<img width="380" alt="image" src="https://user-images.githubusercontent.com/146530/206240386-a4da8a63-2435-4309-ab4f-a2596b27b36f.png">

**Comment by nelsonec87** [comment]
![image](https://user-images.githubusercontent.com/3801502/206255777-af9c534f-5ed6-4652-9527-8520d1ff221f.png)
Seems fine now! 🥳
