### ISSUE TITLE
Set up your store step - suggestion to review copy

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wp-calypso#63703]
I think the copy of this step can be improved to make sure that users know what to expect from each option. Especially the More Power title/section

![Screenshot on 2022-05-17 at 11_19_18](https://user-images.githubusercontent.com/3380168/168794020-3fc8a462-e1eb-4059-8ef9-546a32e93559.png)

**Comment by blackjackkent** [comment]
As part of our further seller experience redesigns as described in paYKcK-1Hs-p2, this screen will ultimately be going away entirely, so I'm going to close this issue.
