### ISSUE TITLE
Store details - update redirect

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wp-calypso#63704]
The store details task is redirecting the user to the WooCommerce Profiler. However, the WP.com customer probably never saw the WC Profiler because they went through the WP.com stepper. This can cause some confusion, so it would be better to redirect the store details task to the WP.com stepper or hide the task.

<img width="1040" alt="Captura de ecrã 2022-05-17, às 11 51 42" src="https://user-images.githubusercontent.com/3380168/168795108-55a25e5e-9706-4dcd-986a-6b1e60bb0b9d.png">

**Comment by andres-blanco** [comment]
Hey @pmcpinto! Can you explain a little bit further? Are you saying that when the user clicks on this button 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/375980/170029647-a4ce1dcd-89f7-4efa-ad8f-e325db29bd38.png">
on a WooCommerce site it should redirect to the onboarding flow where this data is initially loaded?

**Comment by pmcpinto** [comment]
Sorry if it wasn't 100% clear. I'm talking about the "Store details" task in the task list. Let me know if you have any questions.

**Comment by blackjackkent** [comment]
@pmcpinto What are the routes by which a user can arrive at this screen? It seems based on our research for https://github.com/Automattic/wp-calypso/pull/63965, that screen is the destination point *after* the user has gone through the WooCommerce onboarding process.

I guess the idea is that if the user clicks on Store Details again, they restart onboarding from the store address step?

/cc @andres-blanco

**Comment by pmcpinto** [comment]
> @pmcpinto What are the routes by which a user can arrive at this screen? It seems based on our research for https://github.com/Automattic/wp-calypso/pull/63965, that screen is the destination point after the user has gone through the WooCommerce onboarding process.

We display the setup task list on the home screen when a new store is created.

> I guess the idea is that if the user clicks on Store Details again, they restart onboarding from the store address step?

If they click "Store Details" they'll see the store profiler with the information they provided before. But in wordpress.com case they never saw the store profiler flow (displayed below) because is being replaced by the wp.com stepper.

<img width="1439" alt="Captura de ecrã 2022-05-26, às 11 00 42" src="https://user-images.githubusercontent.com/3380168/170465883-d1441f0f-a793-4f05-8b31-78f007d68054.png">

**Comment by valterlorran** [comment]
@pmcpinto Thanks for the clarification!

**Comment by rjchow** [comment]
Confirmed that this can be reproduced with a WooCommerce shop admin that was created through wordpress.com

**Comment by andres-blanco** [comment]
Relevant conversation about this: p1653929634390569-slack-C7U3Y3VMY

**Comment by andres-blanco** [comment]
This will probably be included in release 6.8 on August 9. https://github.com/woocommerce/woocommerce/issues/33267#issuecomment-1170872005

**Comment by valterlorran** [comment]
Closing this, version 6.8 has been released p1660114148538759-slack-CB37YNEH1.
