### ISSUE TITLE
Plugin Details: add manage purchases to the header

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63711]
- [ ] Remove the `Manage subscription` from the dropdown in installed plugins 
<img width="1159" alt="CleanShot 2022-05-17 at 17 26 01@2x" src="https://user-images.githubusercontent.com/12430020/168835211-ff78c331-cf2a-490e-844d-729fd8cf4344.png">

- [ ] Add `Manage Purchases` to the header

<img width="920" alt="CleanShot 2022-05-17 at 17 23 37@2x" src="https://user-images.githubusercontent.com/12430020/168834546-678acc57-afd7-47ca-a49c-91eed3150db2.png">

Epic Issue: https://github.com/Automattic/wp-calypso/issues/43332
P2: pdh6GB-sk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi

**Comment by cpapazoglou** [comment]
@SaxonF how will "Manage Purchases" actually work? I assume that it will be visible regardless of the installation status and that it will redirect to `https://wordpress.com/purchases/subscriptions/:site_id` where all current site subscriptions can be found?

**Comment by SaxonF** [comment]
@cpapazoglou this was actually unintentional so we can remove this issue. I've updated P2
