### ISSUE TITLE
Plugin Details: sidebar redesign

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63714]
- [ ] style changes
- [ ] add "Requires plan upgrade" 
- [ ] add "Plugin Updates" usp
- [ ] in mobile breakpoints the ups are collapsible

Note: Premium version available will be tacked in another issue https://github.com/Automattic/wp-calypso/issues/60769

<img width="890" alt="CleanShot 2022-05-17 at 17 35 59@2x" src="https://user-images.githubusercontent.com/12430020/168837521-92b1e38b-d4b2-43d4-ba45-a09c01ea94e6.png">

Epic Issue: https://github.com/Automattic/wp-calypso/issues/43332
P2: pdh6GB-sk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi

**Comment by cpapazoglou** [comment]
@SaxonF 

- can you confirm that we are removing "Best-in-class hosting" from the usps?
- how we might fit the "Your store foundations" usp that appears in Woo extensions? 
- we are statically using the blue color for the CTA instead of the selected theme CTA color?

![CleanShot 2022-05-17 at 17 42 13@2x](https://user-images.githubusercontent.com/12430020/168839012-83a5154a-53eb-4bba-a270-f78b4510b5cd.png)

**Comment by SaxonF** [comment]
@cpapazoglou let's keep whatever related info we have in there at the moment , so this task is really just wrapping in the sidebar which is a dependant of https://github.com/Automattic/wp-calypso/issues/63684
![image](https://user-images.githubusercontent.com/1072756/169738210-d66d4370-f0bd-4ed1-a7b6-2cc82646b6b4.png)

**Comment by SaxonF** [comment]
Regarding CTA button we should keep current theme colour
