### ISSUE TITLE
Plugin Details: add search bar to the header

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63713]
- [ ] add search bar to the header
- [ ] triggering a search will redirect to `https://wordpress.com/plugins/:site_id?s=:search_term`
- [ ] add track events

![CleanShot 2022-05-17 at 17 33 46@2x](https://user-images.githubusercontent.com/12430020/168837012-5648e5bb-7d01-42a8-bef1-1122340a5726.png)

Epic Issue: https://github.com/Automattic/wp-calypso/issues/43332
P2: pdh6GB-sk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi

**Comment by SaxonF** [comment]
We can remove this one for now too @cpapazoglou .
