### ISSUE TITLE
Plugin Details: redesign plugin header details

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63715]
<img width="939" alt="CleanShot 2022-05-17 at 17 50 10@2x" src="https://user-images.githubusercontent.com/12430020/168840876-738b5924-40c3-4faa-9314-4232dbc9be8e.png">

Related to https://github.com/Automattic/wp-calypso/issues/60769
Epic Issue: https://github.com/Automattic/wp-calypso/issues/43332
P2: pdh6GB-sk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi

**Comment by cpapazoglou** [comment]
@SaxonF can you confirm we are removing the plugin tags?
![CleanShot 2022-05-17 at 17 49 28@2x](https://user-images.githubusercontent.com/12430020/168840706-817a35d6-fa99-4327-b6df-f1a2aaa3f873.png)

**Comment by SaxonF** [comment]
happy to keep it if you think it's helpful. This was before my time so missing some context. If a plugin is part of a category we could show category name with link to the category instead.

**Comment by cpapazoglou** [comment]
> happy to keep it if you think it's helpful. This was before my time so missing some context. If a plugin is part of a category we could show category name with link to the category instead.

@Automattic/explorers I believe can we map tags to category links, right?

**Comment by allilevine** [comment]
> > happy to keep it if you think it's helpful. This was before my time so missing some context. If a plugin is part of a category we could show category name with link to the category instead.
> 
> @Automattic/explorers I believe can we map tags to category links, right?

@cpapazoglou Yes, that's [what we did](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plugins/categories) for the categories menu. So here we would show the tags as categories, if they match? cc @lsl @Rolilink

**Comment by cpapazoglou** [comment]
> So here we would show the tags as categories, if they match? 

Yes, we can show them as links only if the match and ignore the rest that don't match.

**Comment by SaxonF** [comment]
@cpapazoglou @allilevine Made some updates here to better align with Woo's marketplace .

Changes:
- If we can, let's include a primary category (possibly just first?) in breadcrumbs
- All categories listed out as badges in header linking off to each category list
- Kept existing meta data format with added active install metric
- Moved featured image into header (I'd like to see this with prod data before shipping)

![image](https://user-images.githubusercontent.com/1072756/170155270-1e3b4972-0c44-4acb-b3e4-33aa07b5ebd6.png)

**Comment by lsl** [comment]
Do we have issues open for the right-sidebar content changes?

**Comment by cpapazoglou** [comment]
> Do we have issues open for the right-sidebar content changes?

Yep, here https://github.com/Automattic/wp-calypso/issues/63714

All related issues should be under this Milestone https://github.com/Automattic/wp-calypso/milestone/395

**Comment by WBerredo** [comment]
> All categories listed out as badges in header linking off to each category list

Yes, we can do that.

>  let's include a primary category (possibly just first?) in breadcrumbs

With the current structure of our requests, we don't have a way to know which one is the primary category. 
We can use the first as you suggested, but I don't know how accurate it would be, as we have some tags as `automattic` for example.

cc: @SaxonF

**Comment by lsl** [comment]
> If we can, let's include a primary category (possibly just first?) in breadcrumbs

Breadcrumb implementation isn't setup well to handle this, its built like a page history tracker or something resembling that. Doing this is likely a task to redo the whole thing in more explicit terms. (Specify the whole list of breadcrumbs for each page view type) - this is actually something I'd like to do, the breadcrumb.push() thing is quite broken in places.

Please create a new issue if you want this.

**Comment by SaxonF** [comment]
@lsl sounds good. Let's leave out for now.
