### ISSUE TITLE
Plugin Details: redesign main content section

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63716]
This mainly relates to the tabbed navigation component

<img width="561" alt="CleanShot 2022-05-17 at 17 51 55@2x" src="https://user-images.githubusercontent.com/12430020/168841293-e09131a4-065c-413d-9eaa-ccf8939eddf0.png">

Epic Issue: https://github.com/Automattic/wp-calypso/issues/43332
P2: pdh6GB-sk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi

**Comment by SaxonF** [comment]
We'll want to do a cleanup on plugin content typography at some point but I'd like to have a broader discussion around standardising our type scales across the entire platform first

**Comment by gcsecsey** [comment]
Grooming discussion:
 - we can push this change without any dependencies, as it's definitely better than what we currently have
