### ISSUE TITLE
[Bug]: Payment Button and Premium Content Blocks Don't Show UI and Cause Error in Editor

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#63723]
### Quick summary

The Payment Button and Premium Content Blocks are not showing the block-specific UI to add payment details and display an error when added on a Simple site (they seem to function normally on Atomic).

<img width="882" alt="Screen Shot 2022-05-17 at 10 50 49 AM" src="https://user-images.githubusercontent.com/1900444/168857542-61613c84-27f9-416e-a585-4aa77adee491.png">

### Steps to reproduce

1. On a site with access to payment blocks add a Payment Button or Premium Content Block
2. See the error Cannot read properties of undefined (reading 'id'), no message to connect Stripe if not connected, and no UI to configure the block

### What you expected to happen

To see the UI shown in https://wordpress.com/support/wordpress-editor/blocks/payments/#payment-button-block, including a prompt to connect Stripe and UI to setup the block

### What actually happened

An error appears, the message to connect Stripe is missing, and the UI to configure the block is absent as well

### Context

Testing

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

**Comment by vinnykaur** [comment]
Another one reported at hc-35002305

**Comment by kriskarkoski** [comment]
Thanks for the fix, can confirm I'm seeing the Connect with Stripe button now when adding them.
