### ISSUE TITLE
Guided Tour (Help Center V1)

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#63721]
### What

Establish a “Next Steps” help center section to provide in-app guidance tours in the Site Editor. Initialize the first iteration of guided steps within the editor, while leaving the next steps easily alterable and extendable for future developers.

### Why

This fits in with a wider effort to improve new user experience (or the first ten minutes experience pbAok1-2n6-p2 by guiding users through the most necessary steps and tools they will need to feel comfortable launching their site.

### How
- [x] Tourkit spike
- [x] Add help center components to site editor

### Notes
- @creativecoder brought up great observations about our past attempts to implement something similar. We'll want to consider how difficult maintenance may or may not be, especially if we're relying on brittle dom selectors to spotlight specific items in the editor.

**Comment by Addison-Stavlo** [comment]
Im going to close this in favor of our tracking issue here - https://github.com/Automattic/wp-calypso/issues/64080
