### ISSUE TITLE
[Mobile only] Latest Posts lists should have no right margin

### ISSUE THREAD

**Issue by cintacks** [Automattic/wp-calypso#63750]
### Quick summary

The *Latest Posts* Block has a right margin, which doesn't look correct on mobile. There should be a CSS media query in place to account for this. 

### Steps to reproduce

1. Add a *Latest Posts* Block in FSE
2. View how the list stacks/appears on mobile

Example: 

https://user-images.githubusercontent.com/18581859/169451608-2a262da4-1538-4e6b-b92a-6cea1052d47b.mp4

### What you expected to happen

The images should span the full width of the content.

### What actually happened

There's a right margin, making the content look pushed to the left.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

A quick CSS media query fix:

```
@media screen and (max-width: 768px) {
	.wp-block-latest-posts.is-grid li {
		margin-right:0;
	}
}
```

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested across Self-hosted, Atomic, and Simple, and could not replicate the issue.
- In each environment, the Latest Posts block honored the inherited page width and margins, like other blocks on the page.  Examples:

<img width="550" alt="screenshot" src="https://user-images.githubusercontent.com/27249804/171502681-27818a47-e653-4d52-b930-185efdb7dd96.png">

<img width="550" alt="screenshot" src="https://user-images.githubusercontent.com/27249804/171502738-0d4c31cb-bfff-4234-9309-7238f425c756.png">

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
