### ISSUE TITLE
"Post author name" block not visible on the frontend of a site, on Gutenberg 13.2.0 and higher

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#63756]
### Quick summary

"Post author name" block is not visible on the frontend of a site, on Gutenberg 13.2.0 and higher. I can see it fine on Gutenberg 13.1.0 and Gutenberg 13.0.0. Tested with various themes.

### Steps to reproduce

- On a site with Gutenberg 13.2.0, add the `Post author name` block to a page.
- Optionally, mark that block to link out to the author archive.
- Publish the page.
- See that the block is not visible on the live page.

### What you expected to happen

Author name to be visible.

### What actually happened

Author name is not visible.

### Context

User report.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No.

### Browser, operating system and other notes

All.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No and the platform is unusable

**Comment by arunsathiya** [comment]
- It's reported on core already: https://github.com/WordPress/gutenberg/issues/41135
- Adding to cross-post watchlist.

**Comment by Greatdane** [comment]
Another user report: 5226399-zd-woothemes

**Comment by arunsathiya** [comment]
Some updates: 

- Gutenberg 13.2.2 fixed this bug: https://github.com/WordPress/gutenberg/issues/41135#issuecomment-1131923762
- Gutenberg 13.2.2 was pushed to WordPress.com sites (both simple sites and those with a plugin installed, AKA Atomic sites) at 1800 UTC on May 20, 2022: p1653069685523539-slack-CB0B2G43X

**Comment by arunsathiya** [comment]
Customer on 5226399-zen that's noted on [this comment](https://github.com/Automattic/wp-calypso/issues/63756#issuecomment-1131148859) is informed already. ✅
