### ISSUE TITLE
Navigation Block sub-menu spills off page in mobile mode view with Overlay off.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#63781]
### Quick summary

The navigation block will spill off the page in mobile mode when using sub-menus on certain themes in mobile mode (mobile menu off in the block settings)

### Steps to reproduce

1. Setup an FSE site and add a navigation block to the header.
2. Setup some sub-menus on the block.
3. Make sure the Overlay Menu setting is turned off in the navigation block settings.
4. View the site in a browsers responsive mode or on a phone.

### What you expected to happen

The sub-menus should stay on the screen.

### What actually happened

The sub-menus show up off the screen:
![Screen Shot 2022-05-18 at 2 37 41 PM](https://user-images.githubusercontent.com/49131029/169153788-a7e5c5a4-4fce-4fb0-9279-6ccbbb69cb73.png)

### Context

35526640-hc

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Some themes seem to lay the header out differently on mobile so it's less of an issue, however, any theme that has the block at the edge of the screen has this problem.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

The only workaround is to enable the overlay menu, however, this is not a full workaround as the overlay menu does not allow for collapsable sub-menus.

**Comment by simison** [comment]
@KirkwallDay Has this been tested with core Gutenberg, and is there an issue at Gutenberg repo? See PCYsg-hT7-p2 (Minding our etiquette of course pb6Nl-dyI-p2)

**Comment by KirkwallDay** [comment]
@simison I tried testing this with just core Gutenberg but was unable to re-produce, I tested with Block Base there. However, I wasn't able to test with Arbutus or Blank Canvas, both themes give errors when trying to activate them on a basic WordPress install with only Gutenberg active. I was using Jurassic Ninja for this:

![Screen Shot 2022-05-19 at 8 29 35 AM](https://user-images.githubusercontent.com/49131029/169320290-2f394825-d02c-4963-afc5-fd5ecfc76ef0.png)

I'll try again later on today and let you know if I keep having issues.

**Comment by KirkwallDay** [comment]
Hi @simison I tried on a self-hosted site as well and couldn't get Arbutus or the Blank Canvas Block Base version to work there either. I get the error `om themes if ( is_admin() ) include dirname( __FILE__ ) . '/inc/updater.php';` and the Full Site editor just shows up blank. On the base Block Base theme, it seems to be fine so it might just be occurring with Block Base children. I think it's because the menu is changing position on mobile view. On desktop, the menu is on the right side, and then on mobile, it shifts to the lower left side:

Desktop View: 
![Screen Shot 2022-05-19 at 10 08 30 AM copy](https://user-images.githubusercontent.com/49131029/169347987-72bc5b42-e7e1-4978-8c20-cc490591f069.png)


Mobile View:
![Screen Shot 2022-05-19 at 10 08 45 AM](https://user-images.githubusercontent.com/49131029/169347751-4d8dc484-9ec2-49e8-8560-61718b2aa524.png)

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Didn't test this yet

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- So far I tested Arbutus and Blank Canvas themes on simple and AT. I wasn't able to recreate the issue yet. I'm out of time to test this further now, so leaving this open for someone else to take a second look.

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
Could not replicate on any of my testing sites using  Blank Canvas or Arbutus or Archeo

<img width="377" alt="Screenshot on 2022-06-02 at 10-59-33" src="https://user-images.githubusercontent.com/83325600/171673654-12f99e4e-bb74-43f3-a599-1a9929e0052b.png">

📌 ACTIONS
- Marked as Triaged 
- Closed as could not replicate, please reopen this issue if it reoccurs
