### ISSUE TITLE
Generated design picker: Adding desktop view breakpoints

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#63795]
## Description 

In the current iteration of the generated design picker, there is only one breakpoint that differentiate between mobile and desktop views. We want to add more breakpoints in the desktop view to improve the user experience in larger horizontal resolutions.

![Image](https://user-images.githubusercontent.com/797888/170169106-ed22f4ac-d8a1-4a01-8080-2f61f04058a8.png)

## Acceptance Criteria
- [ ] Add a new endpoint for w1280px.
- [ ] Add a new endpoint for w1400px.
- [ ] Add a new endpoint for w1920px.
- [ ] Add a new endpoint for w2560px.

**Comment by taipeicoder** [comment]
@saygunnyc we will be tracking the introduction of more breakpoints here.

**Comment by saygunnyc** [comment]
> ## Description
> In the current iteration of the generated design picker, there is only one breakpoint that differentiate between mobile and desktop views. We want to add more breakpoints in the desktop view to improve the user experience in smaller horizontal resolutions.
> 
> This task is currently waiting on design details.
> 
> ## Acceptance Criteria
> * [ ]  Breakpoint 1
> * [ ]  Breakpoint 2
> * [ ]  ...

Just leaving a note here that, it's also the bigger resolutions. Allow me to track common resolutions from onboarding and will fill you in over here.

**Comment by roo2** [comment]
it may be worth waiting for sticky thumbnails change to land  before working on this, as they both deal with design and may touch the same code files https://github.com/Automattic/wp-calypso/pull/64110/files

**Comment by taipeicoder** [comment]
Closing as it's shipped.
