### ISSUE TITLE
Generated design picker: Sticky thumbnails in desktop view

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#63794]
## Description

In the current iteration of the generated design picker, we will only show 3 thumbnails on the left side of the screen while showing the full design preview on the right side (desktop view). As result, when users scroll down to see more of the full preview, the thumbnails will be scrolled out of the viewport. We want to make the thumbnail section sticky so that it's always visible to the user. 

## Acceptance Criteria
- [x] As users scroll down the screen, the thumbnail section should be sticky so that it's always in the viewport. 
- [x] When sticky, there should be a 48px vertical spacing relative to the top of the viewport.
- [x] When not sticky, the thumbnail section should remain as Figma design, unaffected by this change.

## Depends On
* #63588

**Comment by taipeicoder** [comment]
@saygunnyc LMK if the 48px of vertical space when sticky seems good to you.

**Comment by saygunnyc** [comment]
I am sharing this image and some more notes to clarify the behavior. 

<img width="1773" alt="Sticky" src="https://user-images.githubusercontent.com/78876323/169572926-34ebc62e-7670-4448-947a-00f079b0b8c3.png">

- Once the user scrolls down, we'd like to keep the header sticky, so users always have access to "Back" CTA and "Skip".
- The spacing between header and thumbnails should be 48px.
- The spacing between "Continue" CTA on the bottom and the bottom of the page should also be 48px.
- That would be great to have the browser header over the design preview to be sticky as well.

Hope this makes sense. Please let me know if anything feels off. Or if there's any missing information.

**Comment by arthur791004** [comment]
> Once the user scrolls down, we'd like to keep the header sticky, so users always have access to "Back" CTA and "Skip".

@saygunnyc I think this one has to be another feature as the header won't sticky there in any other steps. If we make it sticky on the Design Picker step, its behavior is not consistent. So, I prefer to have another task to make the header always sticky in all of the steps. What do you think?

**Comment by arthur791004** [comment]
Besides, if we want lots of elements sticky, I'm curious about why not let people scroll inside large preview (iframe) just like the current behavior of the design preview? Then, we can also specify the size of the large preview to general screen size (maybe 1366 x 768) and people would feel like they're previewing in the real browser. I'm sorry if I missed any context.

**Comment by autumnfjeld** [comment]
@arthur791004 @saygunnyc  I like Arthur's idea.   Let's just make the iFrame scrollable.   😃

https://a8c.slack.com/archives/D02APE24EQ2/p1653566868469089

**Comment by that-mike-bal** [comment]
I think it's the same end result if we go the route @arthur791004  suggests. The goal is to let the user scroll to see the rest of the design that is being presented while maintaining view of the header and the other thumbnails on the left. If we just make the iframe area scrollable, we achieve the "stickiness" of everything else without having to actually do the engineering work for it. 

@saygunnyc let us know if there's an interaction or experience trade off we're not thinking of here but I think your "sticky" is ultimately the same as it not moving.

**Comment by taipeicoder** [comment]
While discussing making iframe scrollable, we should also consider the left side thumbnail section height since it might overflow the viewport height (even when we make thumbnail height responsive). Without making most of the elements sticky, we would have to make the thumbnail section scrollable.

**Comment by arthur791004** [comment]
I try to make the demo of these two approaches.

### Sticky Elements

https://user-images.githubusercontent.com/13596067/170673786-29c0a328-3774-4e2c-9c44-e3b93cd35d5b.mov

### Scrolling inside the iframe

https://user-images.githubusercontent.com/13596067/170673809-3af855cc-094d-43e0-a1c5-7a2a100feb9e.mov

Note that this might not look good when the height of the window is too small as we don't have responsive thumbnails yet.

And you can check the details at https://github.com/Automattic/wp-calypso/pull/64110 and https://github.com/Automattic/wp-calypso/pull/64112

What do you think?

**Comment by arthur791004** [comment]
> While discussing making iframe scrollable, we should also consider the left side thumbnail section height since it might overflow the viewport height (even when we make thumbnail height responsive). Without making most of the elements sticky, we would have to make the thumbnail section scrollable.

@taipeicoder Yep, if the height of the window is too small, the thumbnails might be out of the viewport. But I think it's acceptable to let users scroll the page at that time because I think the user with that screen size might not be too much. Or we can make the responsive thumbnails support the height of the window to `720px` which might be the smallest screen size we track.

**Comment by saygunnyc** [comment]
@arthur791004 awesome job with the videos!! Super helpful ❤️ 
I am loving the "Sticky Elements" version _–The first video_ as it provides much more vertical space for the user when it comes to scrolling. And it matches my initial intention. To me, there's no point in getting the customer stuck in that small iframe window, esp considering customers with lower resolution devices.

Let me know if you disagree for some reason that I might be missing.

**Comment by arthur791004** [comment]
Shipped 🚢
