### ISSUE TITLE
Reader: choose from followed tags to add to a list

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#638]
When setting up a new list, it should be possible to choose from the current user's followed tags to add to the list.

<img width="1003" alt="17235 copy" src="https://cloud.githubusercontent.com/assets/66797/11371932/1b95ce38-9288-11e5-9ffb-9353faec35fe.png">

**Comment by alisterscott** [comment]
Lists are unavailable for customers without lists, and existing lists users can't manage these lists any more, so closing this issue as no longer applicable. See `p5PDj3-1Fg-p2`
