### ISSUE TITLE
FSE: Site Editor shows an unhelpful error for non-FSE themes

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#63802]
### What

When you visit the Site Editor URL directly with a theme active that doesn't support FSE, you end up with a generic error:

> Sorry, you do not have permission to access this page.

Adding a more descriptive error directly at this point would be more immediately useful to users. 

### Why

If a user has switched from an FSE theme, this may not be immediately obvious why that error is appearing, unless they have the direct knowledge that Site Editor requires an FSE theme. We already hide the link the WP Admin interface and Calypso but a user who has had an FSE theme may have previously bookmarked the direct URL of the Site Editor making it quite easy to see this error.

**Comment by supernovia** [comment]
Thank you for reporting this!

Closing for this issue & we'll note this case. https://github.com/Automattic/wp-calypso/issues/63479
