### ISSUE TITLE
Figure out how to persist colors and images to a generated theme in Gutenberg editor

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#63804]
The goal is to populate the Background, Text, and Link color settings in the site editor. Below is a screenshot of the feature in the site editor that allows you to set global color values.

![Image](https://user-images.githubusercontent.com/10244734/175247042-20ce13e9-57e1-487a-abe4-7ecd511cd0e0.png)

To achieve this, the colors that we extracted from the user's existing website need to be added to a custom palette color palette.

When the colors have been added, we need to assign these colors to the appropriate global color (Background, Text, or Link). 

The best thing to do is probably send the picked colors (if they differ from the default colors) with the theme-setup endpoint that is called when a theme is picked. The endpoint headstarts the site with appropriate vertical details such as patterns.

**Comment by vishnugopal** [comment]
Discussion:
- We should emulate what Ganon is doing here.
- We also need to be certain how we're doing this: [style variations](https://make.wordpress.org/core/2022/05/03/global-styles-variations-in-wordpress-6-0/) is one option (not live in WPCOM right now), custom colors.

**Comment by jeroenpf** [comment]
A note regarding the way we currently generate custom color theme previews:

We currently override existing CSS variables. However, the color picker in the site editor directly applies colors to the body and link elements. E.g. background and text color is applied to the `body` element and the link color is applied to `a` elements. 

**We should make sure to change the way we apply the colors to the theme preview so it is the same as how colors picked in the site editor are applied.**

**Comment by jeroenpf** [comment]
After a talk with @bogiii we have decided to use existing endpoints instead of introducing a new one or adding functionality to the theme-setup endpoint.

The global-styles endpoint allows us to create the custom color palette and assign the colors in that palette as global styles (background, text, link).

**Comment by vishnugopal** [comment]
Closing as this is an old project.
