### ISSUE TITLE
Test & integrate Colors API in Calypso Light Importer flow

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#63806]

**Comment by vishnugopal** [comment]
@zaerl to provide some sites that always timeout here.

**Comment by vishnugopal** [comment]
Discussion:
- As part of frontend implementation here, we'll create smaller @wordpress/data stores just for the light importer work.
- The idea is that we'll extract state from the Calypso global store in the future.
- We'll hydrate the static design with live content from the APIs and provide feedback.
- Currently the API blocks and returns the result only after X seconds. It does not have processing, queued states.
- We may very well want to cache the API response, especially during development.
- We can use mocks for development in the frontend.

**Comment by vishnugopal** [comment]
Try out:
`angrybirds.com`

**Comment by vishnugopal** [comment]
Discussion:
- Better to have a separate data store `analyzer`.
- Lots of bootstrapping involved here related to `@wordpress/data` resolvers etc.
- Will try to connect the current screens to this data store.

**Comment by bogiii** [comment]
The colors API has been tested and introduced in the Analyzer data store. The code is under the `update/import-light-screens` branch.

The rest work related to the first phase of Light importer (importing colors) can be tracked under the umbrella issue: https://github.com/Automattic/wp-calypso/issues/64774

cc @vishnugopal
