### ISSUE TITLE
Extend MC Verticals Recipe builder to take a URL and integrate with the preview (images + colors)

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#63805]

**Comment by vishnugopal** [comment]
Discussion:
- Maybe we'll have to create another tab only for this.
- Don't want to create confusion with Team Ganon.
- Since it's not difficult to create a new tab, let's do this!
- Going to write a P2 post detailing this.
- The preview is created by calling an API that generates HTML. It takes template parts and block names, etc. and generates a theme. This is being studied right now.

**Comment by zaerl** [comment]
The last diffs have been deployed. This issue can be closed.
