### ISSUE TITLE
Site Stats: Discrepancy between country count and views by country

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#63812]
### Quick summary

One of our users reported an inconsistency between the number of _Visitors_ reported by Site Stats, and the number of countries listed in the _Views by Country_ panel -

>Have noticed that for the last 4-5 days the visitor count is not working accurately. eg visitors from several countries but visitors counted = 1

While the number of reported views for a given time period seem to correspond with the number of views listed by country, this is not the case when trying to correlate _visitors_ with the number of countries represented in the Stats. Here are two examples:

![Capture_2022-05-19 at 14 14 47@2x](https://user-images.githubusercontent.com/2912202/169282348-1ede8204-048e-4802-91ea-d30128c84880.png)
![Capture_2022-05-19 at 14 15 25@2x](https://user-images.githubusercontent.com/2912202/169282361-e130ce0b-2269-43ff-a5b7-ad8b3f925e52.png)

### Steps to reproduce

1. Head to _Stats_ in the WordPress.com dashboard;
2. Select days or other time periods in the Stats graph; and
3. Compare the number of visitors to the _country count_ to see where the number of visitors does not correlate with the number of countries listed as sources of those visitors (particularly where there are more countries listed than visitors).

### What you expected to happen

The number of visitors should equal or exceed the number of countries listed as traffic sources.

### What actually happened

It's possible for the number of countries to exceed the number of visitors.

### Context

Customer report in 5226146-zen

### Simple, Atomic or both?

Simple

### Theme-specific issue?

This is unclear, although probably not.

### Browser, operating system and other notes

This doesn't seem to be affected by operating system or browser details.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

I'm not aware of a workaround for this.

**Comment by Jaykame** [comment]
I have a customer here with the same duplicate discrepancy on their site.

- [x] Ref: 5228572-zen

**Comment by nagpai** [comment]
User here mentioning discrepancy too 

- [x] 5223157-zen

User will need a followup once this is resolved.

**Comment by nagpai** [comment]
Another issue 

- [x] 5239206-zen

The day they have shown is within 24 hours though, and I have let the user known that we need time to correlate. If that is indeed the case, then it would be a good idea to show some indication to the user that the stats are still being worked upon for that date and may not be accurate.

**Comment by Jaykame** [comment]
- [x] 5233939-zd-woothemes

Another case with the same discrepancy. 

Previously reported in p2EDhh-1Cb-p2

**Comment by Greatdane** [comment]
Is this something @Automattic/jetpack might be able to take a look at?

**Comment by jeherve** [comment]
That's not really something anyone in the division is familiar with, I'm afraid. :( I don't really have any good recommendations, short of posting on +serenityofdata, where someone may be familiar with that type of problem.

I looked for recent changes to the country views stats API endpoints as well as general changes to the way stats are calculated, but I didn't find any recent related changes.  I also do not see any recent changes to our IP to location setup.

Given that we know it started happening quite recently, a better recommendation may be to turn to +devopsp2, where someone may have an idea of a recent (6-7 days ago) change that may have impacted country visit aggregations.

**Comment by devNigel** [comment]
- [x] Since the bug report is now triaged, I have closed this ticket: 5239206-zd-woothemes

We should update the user on a new ticket once the issue is resolved. TIA!

**Comment by Greatdane** [comment]
Just an update to say I reached out to +devopsp2 (and +serenityofdata) for help here; p3topS-16z-p2
🤞

**Comment by KokkieH** [comment]
Another report in https://wordpress.com/forums/topic/stats-has-stopped-recording-site-visitors-correctly/?view=all

**Comment by edwinho89** [comment]
- [x] 5248621-zd-woothemes

Another report where the issue is identical with others above.

**Comment by formosattic** [comment]
- [x] 5244557-zd-woothemes, User also noticed a drop. Wants to be notified.

**Comment by rw-ye** [comment]
- [x] I have closed this ticket 5223157-zd-woothemes as there is no ETA. Please re-open a new ticket when we have more to share.

**Comment by pauljacobson** [comment]
- [x] We have what seems to be another instance of this here: 5261433-zen , they want to notified once it 's fixed.

**Comment by bperson** [comment]
This should be fixed in the next couple of hours.

We had to change the way uniques / visitors were computed ( move from one tech stack to another ) and this is a regression from that move. The impact should be on all sites that are based in UTC+ timezones: we were not computing uniques until you were on the same day as UTC. The further you are in the future compared to UTC, the more uniques you would loose: for instance - in Australia ( AEST ) - you would loose all uniques / visitors in the first 10h of your day.

For the date range May 16th - Jun 6th, all uniques data for those websites will be recomputed in the next days / weeks ( no ETA ).

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with the affected users reported in this thread.

Thanks for the reports. Please let us know if you see any future recurrence of the issue.

**Comment by jorpdesigns** [comment]
- [ ]  Just spotted another occurrence of this issue in 5317344-zen

When the user wrote in, there were 3 visitors but views were being recorded from 4 countries.

![Screen Shot on 2022-06-22 at 14:59:50](https://user-images.githubusercontent.com/40006288/175048005-032ee216-b6b1-4511-9156-2034a3a6f7d7.png)

At the moment, the number of visitors is 6 and the amount of countries shown is 4 which looks okay. Maybe we could look into this again?

**Comment by bperson** [comment]
@jorpdesigns This should be fixed

**Comment by bperson** [comment]
Tentatively resolving this. Feel free to reopen if it happens again

**Comment by tellisbethel** [comment]
- [ ] This seems to have cropped up again: 5333190-zd-woothemes

From the user: "July 6th 2022, there were total of 2 visitors only but the country of origin of those 2 visitors involve 4 different countries, i.e. India, Malaysia, Romania and United States."

![image](https://user-images.githubusercontent.com/1767799/178143296-03d25dab-6b02-4185-a1c0-57411eb0b161.png)

**Comment by bperson** [comment]
@tellisbethel Sadly, this is another (old) stats issue where - if a logged in user visits from a VPN ( or through multiple IPs that are geolocated in different parts of the globe ) - we'll end up with those discrepancies between countries and visitors. There is no plan to work on that in the near future.
