### ISSUE TITLE
[All] Increase content width for email notifications on desktop

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#63819]
### What

On desktop, it would make for a more pleasant reading experience if the content width of email notifications was a bit wider.

## Current - 680px max-width

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/36432/169314758-23c4f9fb-a05d-41a4-839b-7996464b9ee4.png">

## Proposed - 800px max-width (similar to P2 emails)

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/36432/169314668-d9404b1d-bf73-4b74-86bd-eb0c17ba9c06.png">

### Why

The narrower email content feels too tight and makes it more difficult to read.

**Comment by zachspears** [comment]
I like this idea, as it would provide better readability and consistency for our emails.

**Comment by danielbachhuber** [comment]
Put together a patch with D83342-code

## Before

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/36432/176288667-d88beffa-4bfc-4e6d-bb40-45766e9bfc2d.png">

## After

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/36432/176288694-3faee7b6-0a6a-4d07-97cd-5aa5696b1b35.png">

---

This _seems_ like a fairly safe change, particularly because `wp-for-teams/css/style.css` is already using it.

@Automattic/apex Any dragons I should be aware of? Thanks!

**Comment by ivan-ottinger** [comment]
Hey @danielbachhuber 👋🏼 

> Any dragons I should be aware of? Thanks!

Thank you for pinging Apex! The proposed change looks good to me. 👍🏼 

I would just check with @mtias too - as he was in charge of the new email templates design.

**Comment by saygunnyc** [comment]
I wanted to add a note here and mention that currently, the width for new post emails is at 752 px (larger) while other informative ones (new subscriber, confirmation, etc.) are at 600px over designs – similar to P2 emails if I'm not wrong. 

<img width="826" alt="Screen Shot 2022-06-29 at 12 14 11 PM" src="https://user-images.githubusercontent.com/78876323/176485287-db9a0234-469d-4fa7-b94c-95d8e7d31747.png">


<img width="692" alt="Screen Shot 2022-06-29 at 12 14 22 PM" src="https://user-images.githubusercontent.com/78876323/176485306-4519e2a6-91b7-4840-80f8-30fc858a8fdb.png">



We can align them all to be 800px if there's a lean towards it. However, I'd like us to be **wary of device resolutions** when it comes to rendering emails. I believe the acceptable optimum still is **600px**. Sharing an example from Mailchimp below. Also, I am seeing the same sentiment communicated widely after doing brief research. 

> Mailchimp templates are designed to be no greater than 600px wide to fit the display capabilities of most email clients.

https://mailchimp.com/help/about-template-widths/#:~:text=Mailchimp%20templates%20are%20designed%20to,capabilities%20of%20most%20email%20clients.&text=The%20underlying%20code%20for%20the,setting%20in%20the%20Campaign%20Builder.

**Comment by danielbachhuber** [comment]
@saygunnyc Thanks for the feedback!

Are the Mailchimp guidelines inclusive of the padding on the container (i.e. representative of the full width of the whitespace), or specific to the width of the content?

If I had to take a guess, my hunch is that the 600px guideline is to mitigate unexpected wrapping in the content. If this is the case, it doesn't seem like it will be a problem with our templates.

@lamosty Any insight that you could share about P2's switch to 800px wide?

**Comment by lamosty** [comment]
> @lamosty Any insight that you could share about P2's switch to 800px wide?

Hi. Pinging our designer @david-gonzalez-a8c for more info. :)

**Comment by mtias** [comment]
I think some of the measurements don't account for padding. It looks like it'd be fine to increase a bit, or to settle on the larger version consistently as well.

**Comment by danielbachhuber** [comment]
@mtias @lamosty @saygunnyc Could one of you make a final call on: 1) whether my change as proposed is sufficient, or 2) whether there's additional work you'd like done (and what that work should be)? Thanks!

**Comment by mtias** [comment]
What's the character per line we are achieving on new post emails?

**Comment by pablohoneyhoney** [comment]
For context:

Though it's a bit sloppy actually, Substack uses these widths:
- Browser/desktop: 728 width / 609 image width
- Email/desktop: 550 width 

@saygunnyc:

- Let's set the content width to be wider than 488 in desktop. Considering content width as the text and images box, not the white container. The white container needs to grow as well alongside the content width. 
- Let's make sure all email templates have the same 2 (max 3) breakpoints. Email view / Mobile browser view / Desktop browser view. Share the specs for each. 
- Let's make those widths multiples of 8 and rounded numbers. Like 720 instead of 728, or 560 instead of 550. There's a beauty in everything : ) 
- Let's make sure all blocks and content types are well visualized.
- Let's try to not get to more than 15 words per line. Longer lines affect negatively reading and scanning.

**Comment by saygunnyc** [comment]
Based on @pablohoneyhoney 's feedback above, sharing specs for each below.
As summary,

- Adjusted all emails to have the same content width and margins. –New post was larger than the others originally.
- Using **720 px** for desktop browser and **640 px** for desktop email. And keeping mobile the same _–**327 px** with **24 px margins**._

Link to Figma – c5bt2O2vWhTlhSREC89Bw2-fi-1045%3A9272

![Sizes](https://user-images.githubusercontent.com/78876323/178518816-d98130a2-3eed-4b4a-ad3c-5df44165781a.jpg)

Despite Substack and Mailchimp's desktop email specs, I kept the 640px size as-is for now. Let's keep an eye on feedback. 
cc @yansern @ivan-ottinger

**Comment by danielbachhuber** [comment]
@saygunnyc Thanks! Those look great.

I only started in May so I'm not super clear on what changes you'd like me to me, and to which emails. Would you be able to list those specific changes for me?

Happy to work through this 1-on-1 too, if you want to ping me in Slack.

**Comment by saygunnyc** [comment]
Thank you @danielbachhuber ! Pinging @phcp and @yansern here as they have been working on the emails.

**Comment by phcp** [comment]
Hey @danielbachhuber!

The **New Post**, **New Subscriber**, **Confirm Subscription**, and **Welcome e-mail** are in production (more details here: pdgv5Y-lA-p2), so those would be a good starting point. The width changes should follow [Saygun specs above](https://github.com/Automattic/wp-calypso/issues/63819#issuecomment-1181860518). It'd be nice to have a single solution for all templates, as they intend to have the same width.

Here is documentation with more details on how to work with e-mail templates: PdDOJh-9q-p2

Let us know if you need additional details.

**Comment by danielbachhuber** [comment]
@yansern @ivan-ottinger Unassigning myself from this issue. Feel free to loop me in however is helpful, though.

**Comment by ivan-ottinger** [comment]
Hey @saygunnyc 👋🏼 

I have been looking into the template widths and how the breakpoints are currently implemented.

Question: How important is to have different widths specified at breakpoints Browser/desktop and Email/desktop?

The reason I am asking is because we could change the maximum content width to the one specified for Browser/desktop: 720 px (832 px including 56 px margins) and then leave the content width adjust smoothly as the screen width gets lower - until it reaches mobile width - where the layout would be switched to mobile:

https://user-images.githubusercontent.com/25105483/183054310-cf62be67-16fb-490a-b320-4861bd7d6f63.mp4

What do you think?

Note: The breakpoint for mobile is currently set at 620 px. The e-mail client used in the recording above is macOS Mail app.

**Comment by ivan-ottinger** [comment]
Patch in work: D85441-code.

**Comment by yansern** [comment]
> then leave the content width adjust smoothly as the screen width gets lower - until it reaches mobile width - where the layout would be switched to mobile

From this sentence were you implying that it was going to be 3 different fixed widths?

IMO it is implied that will resize smoothly between the 3 new breakpoints with new widths & margins.

**Comment by ivan-ottinger** [comment]
The way I understood [Saygun's comment](https://github.com/Automattic/wp-calypso/issues/63819#issuecomment-1181860518) above was that there should be three different breakpoints for the email width.

But then, when I was experimenting with the actual code, it should be necessary just to change the `max-width` of the main `.container` to `832px` (as can be seen in the D85441-code patch) and we will get good results without specifying extra email width for the Email/desktop breakpoint. In the proposed changes the width will nicely adjust itself as can be seen in the screen recording above.

**Comment by ivan-ottinger** [comment]
D85441-code is now deployed to production. The email templates have the new width.

**Comment by saygunnyc** [comment]
Late to the party here. The above looked good to me. 👍

**Comment by mtias** [comment]
Thanks for following through with this @ivan-ottinger
