### ISSUE TITLE
Plans Redesign: Design Tweaks

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#6381]
![plans-design-tweaks](https://cloud.githubusercontent.com/assets/1464705/16429708/0fa252cc-3d2d-11e6-8141-62a45a98049d.png)

**Changes**

* Move explantion text and buttons to below each plan header. These sections should *always be equal height* across plans so that everything aligns.
* Modify the paragraph of text for each plan, so they are similar lengths.
* Change the button on a lower plan to say "Downgrade Plan", and make it a secondary button.
* Change "Upgrade" on primary buttons to "Upgrade Plan".
* Keep a single button at the bottom of each plan so there is a call to action after scrolling.
* Re-order the plan features so that they are in a more compelling waterfall format
* Change the wording on some plan features to make them more understandable.
* Bold features that are an upgrade on a smaller plan, so they stand out as upgrades.
* Added information bubbles to each feature entry that will give a little more information about a feature when clicked.
* Removed the "Free Site" entry, because that is basically a given, although I am happy to hear arguments the other way :)
* Tweak the header design, PR here: https://github.com/Automattic/wp-calypso/pull/6375

**Comment by lamosty** [comment]
Nice work @apeatling. Do we need the bottom action buttons now that we have ones in the top of the plans? Seems a bit crowded to me.

**Comment by apeatling** [comment]
I think it's best to keep the call to action at the bottom, after they have gone through and decided on a plan, it's right there. Also for some resolutions, the top buttons will be off screen once you hit the bottom.

**Comment by lamosty** [comment]
I see and agree. One more argument for the above: if they read FAQ which is/will be located below the plans and they decide to upgrade, they would have to scroll a lot to get to the top buttons.

**Comment by apeatling** [comment]
I've updated this to show information bubble access. They show on every feature entry here, so there is some duplication. I think it is necessary here otherwise we're making people think and have to look across to a cheaper plan to get the info bubble.

I will work on some text for each one.

**Comment by gwwar** [comment]
@apeatling could we add the downgrade functionality in another iteration? This isn't implemented yet and would take some time.

**Comment by gwwar** [comment]
> Modify the paragraph of text for each plan, so they are similar lengths.

We can optimize for `en`, but I wouldn't expect this to happen for all locale translations. We should make sure that the vertical alignment looks correct when we do have paragraphs that are different lengths.

**Comment by shaunandrews** [comment]
> These sections should always be equal height across plans so that everything aligns.
> Modify the paragraph of text for each plan, so they are similar lengths.

I think these two things are gonna cause some trouble when considering translations. Its not very "bulletproof" to try and contain the height of columns like that—even if we give it a fixed-height in CSS there's still a possibility of text overflowing and being hidden.

> Removed the "Free Site" entry, because that is basically a given, although I am happy to hear arguments the other way :)

I'm not sure what you mean by "a given." If I'm on the free plan is there no indication of what plan I'm on? Are we attempting to remove the notion of a free "plan," perhaps replacing it with a "plan-less" account?

**Comment by rralian** [comment]
@shaunandrews he's talking about having removed this bullet-point, which is added to each plan card.
![free site](https://cloudup.com/cgpIvyO_Vmn+)

**Comment by apeatling** [comment]
@shaunandrews That was unclear, yes I meant exactly as bob posted above. On the paragraph height issue, you're correct. We definitely need these to line up somehow, otherwise it is going to feel messy and confusing. I'm sure there is some JS magic we can work out to make sure all columns align to the largest paragraph section? /cc @gwwar

**Comment by gwwar** [comment]
![finn_has_a_wand](https://cloud.githubusercontent.com/assets/1270189/16469291/0e296c54-3e05-11e6-9d29-e1086335bd0e.gif)

I'm pretty sure there's a CSS fix. Most likely with the child elements also using `display:flex`

**Comment by shaunandrews** [comment]
Ah, I'm a fool. Ignore me. :)

**Comment by gwwar** [comment]
cc @bubel I think we'll be needing Jetpack copy for the info popups
<img width="914" alt="screen shot 2016-06-30 at 8 22 21 am" src="https://cloud.githubusercontent.com/assets/1270189/16493832/d3aed1ee-3e9b-11e6-8e62-ff2440e76ddd.png">

**Comment by gwwar** [comment]
We can break out work on this in 2 pieces:

- The new info popup on the feature items (with the required copy)
- The new call to action on the header / text alignment ( @gwwar )

**Comment by bubel** [comment]
@gwwar Roger that, I'll get working on it.

**Comment by gwwar** [comment]
Thanks @bubel ❤️

**Comment by bubel** [comment]
@gwwar I have the feature descriptions ready to go. Where shall I put them?

**Comment by gwwar** [comment]
Thanks @bubel feel free to put them in this issue or ping @retrofox in slack

**Comment by retrofox** [comment]
Just FYI @bubel I've created #6476
