### ISSUE TITLE
Marketplace: Add E2E Tests for the categories menu

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#63835]
Let's add some E2E test to ensure the correct working of the categories menu

- [ ] Add a test to check the menu is being rendered with the correct categories.
- [ ] Add a test that ensures clicking the category sends the user to the correct page.
- [ ] Add a test that ensures clicking the category on the dropdown menu sends the user to the correct page.

**Comment by lsl** [comment]
I suggest holding off on this for a little bit, lots of changes coming soon see https://github.com/Automattic/wp-calypso/pull/63846

**Comment by lsl** [comment]
New titles are shown in https://github.com/Automattic/wp-calypso/pull/63892 however @SaxonF [mentioned we might end up changing this](https://github.com/Automattic/wp-calypso/issues/63893#issuecomment-1134238907) quite a bit. 

Not sure if we want to move a head with these yet.

**Comment by Rolilink** [comment]
I don't think that title changing is a hard blocker for this one, we can always update the E2E test selector

**Comment by lsl** [comment]
Design changes coming:

https://github.com/Automattic/wp-calypso/issues/64058
https://github.com/Automattic/wp-calypso/issues/64057
https://github.com/Automattic/wp-calypso/issues/64055

As long as we stick to the selector only https://github.com/Automattic/wp-calypso/issues/64058 should interfere with the e2e tests so yea, probably not a hard blocker at this point.
