### ISSUE TITLE
Woo Onboarding - verify redirect behavior

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#63830]
When the Woo stepper onboarding process completes, currently the user is forwarded into a different woocommerce onboarding process that asks a lot of the same questions. Can we find out what the existing behavior is in this regard in /start? And can we instead forward the user directly to the WooCommerce homepage?

**Comment by andres-blanco** [comment]
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/375980/169865714-f8a8199f-3c80-4c63-9e66-606bdef8e890.png">

This is where we end up now

**Comment by andres-blanco** [comment]
On the current Stepper flow we end up here: 
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/375980/170044710-64f91b75-c25c-4fcd-8e44-f79dab9d38cc.png">
