### ISSUE TITLE
Marketplace: Add the background change on content to the marketplace to match design

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#63837]
![image (2)](https://user-images.githubusercontent.com/1072756/170167509-6dfae67b-a606-467b-a1ea-93d136387854.png)

Figma File: [f84fqtCG4pCnCh2Hq0But5-fi-2011%3A26631](https://href.li/?https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/?node-id=2011%3A26631)

- [x] Search header and Categories should have `#FFFFFF` background color.
- [x] Plugin list should have `#FDFDFD` background color.
- [x] Top border should be noticeable per figma

**Comment by Rolilink** [comment]
Open this image to see the difference.

![Image](https://user-images.githubusercontent.com/1035546/169419157-763cc1df-1c6a-4210-8f28-c2295338e399.png)

- [ ] Search header should have `#FFFFFF` background color.
- [ ] Categories and Plugin list should have `#FDFDFD` background color.

**Comment by lupus2k** [comment]
@SaxonF made a few little design refinements

#### Old design
![old design](https://user-images.githubusercontent.com/811776/169758399-1cc9dc23-700c-460e-90ff-c8ab6ac63784.png)

#### New Design
![new design](https://user-images.githubusercontent.com/1072756/170167509-6dfae67b-a606-467b-a1ea-93d136387854.png)

- [ ] Search header and Categories should have #FFFFFF background color.
- [ ] Plugin list should have #FDFDFD background color.

**Comment by allilevine** [comment]
@lupus2k Can we close this issue?

**Comment by lupus2k** [comment]
Closed because of this PR: #64274
