### ISSUE TITLE
Marketplace: Add scrollbar back to mobile category selector?

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#63831]
We removed this in https://github.com/Automattic/wp-calypso/pull/63787#issuecomment-1131862134 for a couple of reasons, wondering if its worth adding it back for ux reasons (with better spacing), if not just close this.

- [ ] Add styled scrollbar

**Comment by paulopmt1** [comment]
I see it as a good improvement to have it back with better spacing.

**Comment by lsl** [comment]
Me too. Could we confirm assumptions with tracks data? (compare mobile selector usage vs desktop)
