### ISSUE TITLE
Marketplace: Don't trigger animation when clicking the select category

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#63840]

**Comment by lsl** [comment]
I think I suggested this, imo we can skip this, I think having the feedback is better than not at this stage. Removing the focus made it way less jarring.

**Comment by allilevine** [comment]
> I think I suggested this, imo we can skip this, I think having the feedback is better than not at this stage. Removing the focus made it way less jarring.

Closing.
