### ISSUE TITLE
Missing space between buttons on the Calypso media uploader screen

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#63849]
### Quick summary

Missing space between buttons on the Calypso media uploader screen. I am not sure if this is happening only on this screen, or if this is a Button component-level issue. Tracking what I found for now.

### Steps to reproduce

- Start with a WordPress.com site.
- Visit the media library https://wordpress.com/media
- Click on the add new button
- Notice that there is no space between `Upload media` and `Browse free images`

### What you expected to happen

There is space between the two buttons.

### What actually happened

There is no space between the two buttons.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/18581859/169463586-bcda2f4c-f986-4c0d-830b-5949595f544b.png">

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/18581859/169463603-a8d2d8b7-c349-4ff3-a961-f1aa0c4147b5.png">

### Context

Manual testing.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No.

### Browser, operating system and other notes

All.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

**Comment by ghost** [comment]
Since both buttons are working, it is more of an enhancement request to add a space and make it look neater.

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING

- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Not applicable

📌 SCRUBBING

- Tested on P2 - Not applicable
- Tested on Simple - Not applicable
- Tested on AT - Not applicable
- Tested on Self-hosted - Not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

Shared above. I was the OP.

📌 ACTIONS

- Pretty sure we had a space in the past, so this is a bug/regression.
- Flagging this for @Automattic/team-calypso, would one of you be able to check if something about the Button component changed that caused this spacing issue?
- Or, is it just this instance on the media library that's broken?

**Comment by tyxla** [comment]
Thanks for the ping @arunsathiya! 

Looking at the components, this doesn't seem to be related to the button component at all and occurs only in the media library. 

It's not immediately clear where / when it was introduced.

For fixing it, I'd recommend going to https://github.com/Automattic/wp-calypso/blob/dac30586cd5253c2bf463635e869a364e24bcdcc/client/my-sites/media-library/style.scss#L22 and adding `.media-library__upload-button` there, so it also has a `margin-right: 8px` as well. Should be a straightforward fix IMHO.

I'm happy to help with reviews or anything else you folks might need.

**Comment by arunsathiya** [comment]
Thanks for the pointer, @tyxla! I was just triaging it as part of my Dotcom PA work. :) My schedule is a bit packed, and I don't have a local Calypso installation either these days. Could your team take over this issue?

**Comment by arunsathiya** [comment]
Oh actually, this seems fixed both on the block-level popup and on the media library at https://wordpress.com/media

<img width="581" alt="image" src="https://user-images.githubusercontent.com/18581859/174323879-1b664bc5-645a-44d0-8b9c-d08f021751ad.png">


<img width="1030" alt="image" src="https://user-images.githubusercontent.com/18581859/174323916-f6cf50fd-fd27-47a8-a7d0-4320c92c435a.png">

Marking as resolved.
