### ISSUE TITLE
Incorrect "Custom design" upgrade upsell in classic dashboard theme activation flow

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#63856]
### Quick summary

There's an upsell flow for "Custom design" upgrades on the classic dashboard's theme activation flow.

I believe we should be removing it as it's no longer sold:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/18581859/169496870-a38886fa-a017-4c5c-824e-c4c76d604533.png">

### Steps to reproduce

- Start at https://wordpress.com/themes 
- Switch to classic dashboard using "view" at the top right
- Activate a theme like Twenty Twenty-Two 
- See the upsell to buy "Custom design" upgrade.

### What you expected to happen

"Custom design" upgrade should not be advertised.

### What actually happened

"Custom design" upgrade is advertised.

### Context

Manual testing.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

I tested with various themes on a simple site (does not happen on Atomic site) and I can see the upsell for all.

### Browser, operating system and other notes

All.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

**Comment by arunsathiya** [comment]
I am not too sure if we should move this to `Automattic/themes`. I'll let you decide, @Automattic/dotcom-pqa-group.

**Comment by simison** [comment]
@paulbonahora can you help redirect this for pricing & packaging engineers? Thx!

**Comment by simison** [comment]
There could be more of these around? https://github.com/Automattic/wp-calypso/search?q=%22custom+design%22

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this on a **Simple site**. Clicking the `Custom Design` link leads back to the https://wordpress.com/pricing/ page, which I agree should be removed to avoid confusion for users.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by nelsonec87** [comment]
This diff removes the upsell from the theme activation flow: D97385-code

**Comment by nelsonec87** [comment]
Closed by D97385-code
