### ISSUE TITLE
[Bug]: Marketplace post-purchase CTA broken

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#63853]
### Quick summary

When purchasing Woo Shipment Tracking plugin from the marketplace for my Simple site on Pro plan,

Not sure if the domain change has something to do with the error:

<img width="1455" alt="Screenshot 2022-05-20 at 11 56 01" src="https://user-images.githubusercontent.com/87168/169493315-39302812-1702-4469-b08b-eccf5982b0b6.png">

### Steps to reproduce

1. Have simple Site with pro plan
2. Go to marketplace
3. Purchase plugin
4. See domain change notification
5. Purchase with credits at checkout
6. Land at thank you page where main CTA keeps loading, with errors at console
    <img width="1450" alt="Screenshot 2022-05-20 at 11 57 03" src="https://user-images.githubusercontent.com/87168/169493724-264d7810-c521-4acd-8df0-aedfb5784a7d.png">
7. When refreshing the page, CTA became active and linking to `https://testing588416597.wpcomstaging.com/wp-admin/plugins.php` but I still see the error:
    <img width="1830" alt="Screenshot 2022-05-20 at 11 57 23" src="https://user-images.githubusercontent.com/87168/169493774-a452053f-a3f3-4316-a694-deb7f4de02a5.png">
    
The API that was 404'ing was `https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request[slug]=woocommerce-shipment-tracking&request[locale]=en_US&request[fields]=icons,short_description,contributors,-added,-donate_link,-homepage`

### What you expected to happen

CTA be functional right away

### What actually happened

Infinitely loading CTA

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by simison** [comment]
From the functioning CTA I ended up at plugin management page, which felt a bit hectic. I expected landing at plugin's own management page instead:

<img width="1697" alt="Screenshot 2022-05-20 at 12 38 48" src="https://user-images.githubusercontent.com/87168/169503559-96c0168d-a840-4169-87b8-554ed1b3f0b1.png">


cc @SaxonF @ianstewart

**Comment by cpapazoglou** [comment]
> From the functioning CTA I ended up at plugin management page, which felt a bit hectic. I expected landing at plugin's own management page instead:
> 
> <img alt="Screenshot 2022-05-20 at 12 38 48" width="1697" src="https://user-images.githubusercontent.com/87168/169503559-96c0168d-a840-4169-87b8-554ed1b3f0b1.png">
> 
> cc @SaxonF @ianstewart

This depends on each plugin **having** and **registering** a setup page. If it doesn't have such a URL we default to `wp-admin/plugins.php` in case there and WP Admin notices as next actions.

Probably it worths:
1) Mentioning this setup page as a prerequisite for all plugins in our development guidelines
2) Checking why some woo extensions don't have one

**Comment by cpapazoglou** [comment]
I suspect that the errors (which should be resolved) are unrelated to the broken CTA. It should be the Atomic transfer progress taking longer time. If you stayed in the same page without reloading the page you should have had the same results. 

Here is a related issue https://github.com/Automattic/wp-calypso/issues/62067 to the time needed for a site to go Atomic. Perhaps it worths adding a progress bar in case of an Atomic transfer.

**Comment by simison** [comment]
> This depends on each plugin having and registering a setup page. If it doesn't have such a URL we default to wp-admin/plugins.php in case there and WP Admin notices as next actions.

Gotcha, yeah for internal plugins a setup page should always be there. Looks like the plugin also didn't get activated by default:

<img width="1198" alt="Screenshot 2022-05-20 at 14 44 50" src="https://user-images.githubusercontent.com/87168/169522110-760d7a6f-147e-4deb-9966-ec531a4e74b0.png">

I activated it but I'm still unsure where to go to setup it.

**Comment by epeicher** [comment]
The errors at the console are fixed by the linked PR #64127, the plugin can be successfully installed and activated. Next step will be to check why some extensions do not have a setup page.

**Comment by epeicher** [comment]
As described by @cpapazoglou, the Settings page needs to be registered by the extensions, for example the `woocommerce subscription` plugin registers it correctly.

The extensions that do not register it properly will default to the `wp-admin/plugins.php` page as a fallback.
