### ISSUE TITLE
Marketplace: cancel Yoast before refund

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63854]
### Details

We ’ve got a class that handles cancellations and we trigger the refund API if the subscription is refundable. What we don’t do is cancel the subscription.
```
public function handle( Store_Subscription $subscription ): void {
	if ( $subscription->is_refundable() ) {
		$job_data = (object) array(
			'blog_id' => $subscription->blog_id,
		);

		queue_async_job( $job_data, 'marketplace_yoast_premium_subscription_refund' );
	}
}
```

Before `if ( $subscription->is_refundable() ) {` we should first cancel the subscription.

**Comment by JulianBustamante** [comment]
I'm still investigating the cancellation hook that will be used to trigger the async job. When the user cancels a subscription the auto renew is disabled but the subscription is not cancelled until the last day of the subscription.

**Comment by cpapazoglou** [comment]
@JulianBustamante, does this mean that we need a hook that runs on expiry day rather on cancellation day?

**Comment by cpapazoglou** [comment]
@Automattic/shilling, is there a hook that runs when a subscription has eventually expired?

**Comment by danielmx-dev** [comment]
> @Automattic/shilling, is there a hook that runs when a subscription has eventually expired?

You could use the ~`subscription_removed`~ `removed_subscription` hook. It is called when either the subscription is cancelled or when it automatically expires. 

Please let me know if that works for this particular use case.

**Comment by DavidRothstein** [comment]
I think you mean `removed_subscription` actually, but yes -- that's the one that should be run whenever the subscription is removed (for any reason).  It has nothing to do with turning off auto-renew, which is a separate action.

**Comment by JulianBustamante** [comment]
Diff created D82269-code

**Comment by cpapazoglou** [comment]
This is ready to be merged.

**Comment by JulianBustamante** [comment]
Deployed r247296-wpcom
