### ISSUE TITLE
Marketplace: Yoast site url change on domain change

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63855]
After a domain change we should update the license information on Yoast side 

**Testing Instuctions**
- Sandbox public-api
- Buy a Yoast subscription (see pcSRhZ-40-p2 on getting an active subscription)
- Go to WordPress.com and buy a domain. You can buy a personal .blog domain, if you need to retry (switching primary domains) you can use a subdomain and avoid buying new domains.
- Switch that domain to primary through `https://wordpress.com/domains/manage`
![CleanShot 2022-05-27 at 19 21 09@2x](https://user-images.githubusercontent.com/12430020/170739467-f5a6837b-bfd7-427d-af4a-c875110bdc52.png)

- Make sure that the new domain is the default domain of your site and it works
- Make sure that Yoast subscription is still active by visiting wp-admin/plugins.php

**Comment by cpapazoglou** [comment]
When a domain is set as primary the `wpcom_makeprimaryblog` action is triggered which contains the `blog_id` in WPCOM.

**Comment by cpapazoglou** [comment]
Actually, there is a better action `atomic_primary_domain_changed` which runs only if the domain change is successful. This action contains the following arguments `$blog_id`, `$domain`, `$previous_domain` and is already used to run `woocommerce_primary_domain_changed` which notifies WC.com about the domain change.

**Comment by cpapazoglou** [comment]
WIP Diff created D81402-code, I will need your help here @JulianBustamante! Is the approach correct?

**Comment by JulianBustamante** [comment]
Deployed r246698-wpcom
