### ISSUE TITLE
`Browse premium themes` under `My Plan` should link to Premium theme selection

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#63868]
### What

On Premium, Business, eCommerce, and Pro Plan sites, at _My Site → Upgrades → Plans → My Plan_ there is a tile called **Try a premium theme**. It has the button `Browse premium themes` that links to https://wordpress.com/themes/. Instead, it should link to https://wordpress.com/themes/premium/

![image](https://user-images.githubusercontent.com/39308239/169546673-1d16eb98-db39-4506-828f-d0a61b2e1810.png)

### Why

Since we have the deep link https://wordpress.com/themes/premium/, we should use it.

### How

Replace the Url from https://wordpress.com/themes/ to https://wordpress.com/themes/premium/

**Comment by ghost** [comment]
Great find. This looks like a simple link change and it affects all paid users, so marked as priority normal

**Comment by jordesign** [comment]
Hey folks - rolled up a PR for this one - would appreciate a review:
https://github.com/Automattic/wp-calypso/pull/64221

**Comment by wojtekn** [comment]
@jordesign I reviewed your PR, looks good.

**Comment by jordesign** [comment]
Thanks @wojtekn - will get it deployed soonish

**Comment by jordesign** [comment]
Fix is deployed now
