### ISSUE TITLE
Trying to upgrade a legacy plan sends you to customer support. Can we just upgrade them?

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#63875]
Users on legacy plans are asked to contact customer support to switch to a Pro plan on the [Plans page](https://wordpress.com/plans/). (They can also switch to a higher legacy plan.) However, user's with a Premium or lower legacy plan can switch themselves to a Pro plan from the banner on the [Plugins page](https://wordpress.com/plugins/).

Plans Page | Plugins Page
--|--
![contact-support-banner](https://user-images.githubusercontent.com/140841/170310668-7eda5eb0-a428-4b61-96b2-689bd798a99a.png)  | ![upgrade-pro-banner](https://user-images.githubusercontent.com/140841/170310638-3eaa7edf-0c3b-45cb-b50c-4f3bce83a90f.png)

Proposal: Can we show the new plans page to legacy plan user's (with a banner about their site being on a legacy plan) and allow them to self-upgrade their legacy plan to a "higher" contemporary plan (Starter or Pro).

<img src="https://user-images.githubusercontent.com/140841/170313452-754a83d0-a5ca-4f57-ba1f-b4e68ba5007f.png" width="400" />

**Comment by obenland** [comment]
@DustyReagan I converted this note into an issue. Could I ask you to add steps to reproduce this issue so we can determine whether it needs addressing as part of Limited Atomic?

**Comment by DustyReagan** [comment]
I just updated the issue, @obenland. I feel like we could replace the legacy Plans page all together with the new Plans page if we throw in a bit of logic on which plan they can upgrade to.

**Comment by obenland** [comment]
Thank you! Would it be fair to say that this might be a better fit for the Plans & Pricing team than Limited Atomic?

**Comment by DustyReagan** [comment]
> Thank you! Would it be fair to say that this might be a better fit for the Plans & Pricing team than Limited Atomic?

Yes, I think it would.

**Comment by gmovr** [comment]
Closing due to revert.

**Comment by DustyReagan** [comment]
I think the revert might be postponed? p58i-cxt-p2 Feel free to close again if I'm mistaken. 😅
