### ISSUE TITLE
Atomic: Space Quota

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#63878]
- [ ] Decide how a site should behave when it hits the quota. Soft limit? Hard limit? 
- [ ] Implement it in a way that does not ping systems when a site on atomic uses 90% of available disk quota on atomic.

----

- [x] Start with defining a function that determines space for a site to be provisioned during transfer
  - [x] Helper: D81431-code : Adds `get_network_default_blog_upload_space()`
  - [x] D81323-code : Adds `get_blog_space_info()`
    - Note: This does not compute VideoPress space.
    - Note: The function does not run on atomic, since bundle_product_id information is not available (But does it need to?)
- [x] (1) Atomic sites should be provisioned with plan appropriate disk quotas instead of always 200GB.
  - [x] Adjust the space on the Atomic site according to the space allowed by the plan: D82458-code
  - [x] Update Atomic space quota asynchronously and consider space used: D82923-code, D82926-code, D82714-code
  - [x] Avoid changing the Atomic space quota after a product deactivation that triggers the revert process: D83095-code
  - [x] Remove user gate check: D82929-code
- [x] (2) Back-end: All space-limited atomic transfers should be automatically prevented.
  - Checks should be added to `wp-content/lib/atomic/woa.php`'s `woa_transfer_validate()` function and `class-transfer-manager.php`'s `can_be_transferred()` function
  - [x] Extracted checks to: `woa_is_space_used_excessive()`: D81915-code + D81604-code.
  - [x] Make `woa_is_space_used_excessive()` check info returned by `get_blog_space_info()` instead of a hardcoded limit. D82107-code
- [x] (3) Front-end: Space-limited atomic transfers that can’t happen should be reported to the user.
  - [x] Transfers prevented by excessive disk space are reported to the user.
  - [x] ...but the message is vague and does not include upsells. ( https://github.com/Automattic/wp-calypso/pull/64388 )
  - We can refine `wp-content/lib/atomic/eligibility.php`'s `get_status_for_site()` function, which changes what's reported to Calypso. 
  - In calypso, we can modify `hold-list.tsx` to change the message that is displayed. [Link](https://github.com/Automattic/wp-calypso/blob/d8ded990ee801c77728c7bc5d16de1f769ef406d/client/blocks/eligibility-warnings/hold-list.tsx#L87-L93)
    - I think the message must be static. We might want to make it report specifics, like "You're using 8.9G of your 8G plan". Or maybe it could link to a storage upsell page?
    - Other Calypso links: [Link 1](https://github.com/Automattic/wp-calypso/blob/d8ded990ee801c77728c7bc5d16de1f769ef406d/client/my-sites/hosting/main.js#L195) | [Link 2](https://github.com/Automattic/wp-calypso/blob/d8ded990ee801c77728c7bc5d16de1f769ef406d/packages/data-stores/src/automated-transfer-eligibility/selectors.ts#L10) | [Link 3](https://github.com/Automattic/wp-calypso/blob/d8ded990ee801c77728c7bc5d16de1f769ef406d/packages/data-stores/src/automated-transfer-eligibility/constants.ts#L31-L44)
 - [x] (4) Front-end: Atomic users nearing their disk quota should be notified and prompted to buy more space.
   - [x] 965-gh-Automattic/wpcomsh : Create a more prominent storage notice
   - [x] Upload.php uploads prevented. ( 966-gh-Automattic/wpcomsh )
   - [x] Calypso media library uploads prevented. ( 832-gh-Automattic/wpcomsh )

--

- Misc:
  - References to 200GB in `import_wxr_to_simple_site()` and `sideload_wxr_to_simple_site()` - unsure what these are and if they need to be updated.

**Comment by mreishus** [comment]
Start with defining a function that determines space for a site to be provisioned during transfer
* D81323-code + D81431-code

**Comment by mmtr** [comment]
Just deployed the last diff (D82929-code) that removes the temporary user gate check, so the Atomic space quota is now adjusted according to the site purchases for all users.
