### ISSUE TITLE
Plugin Details: Manage plugin in sidebar

### ISSUE THREAD

**Issue by SaxonF** [Automattic/wp-calypso#63887]
### Details

When in a single site and viewing a plugin that has been installed, I want to be able to control the status of that plugin.

This task takes the actions from the existing "Installed on" table within the plugin detail page and moves them into the sidebar, replacing the purchase button. 

![image](https://user-images.githubusercontent.com/1072756/169743740-497af161-f9bf-4e58-8ff5-6e7549a1f824.png)

**Acceptance**
- If a plugin is installed the purchase button is replaced with an activate/deactivate button
- If a plugin is active, the label above the button becomes "Installed and active" and the button becomes "Deactivate"
- Clicking Deactivate will deactivate the plugin
- If a plugin is inactive, the label above the button becomes "Installed but inactive" and the button becomes "Activate"
- Clicking Activate will activate the plugin
- I can toggle auto update on/off via the toggle under the activate/deactivate button
- Clicking the more ellipsis triggers a dropdown menu with options
- If relevant, a "settings" option is visible and takes me to the plugin settings page
- A "Remove" option is visible and triggers the existing plugin removal modal

### Checklist

- [ ] 
- [ ]

**Comment by gcsecsey** [comment]
Grooming discussion:
 - make these changes behind a feature flag
 - we have another story for handling multiple sites with the installed plugin https://github.com/Automattic/wp-calypso/issues/63888
