### ISSUE TITLE
Embed Block: Featured Images hidden by Lazy Load when embedding posts from same site

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#63881]
### Quick summary

Got a user report that when using an embed block that links to another post on the site, the featured image doesn't show.

### Steps to reproduce

1. Create a post with a Featured Image
2. Create another post and add an Embed block using the URL of the post created in step 1

### What you expected to happen

The Featured Image should show

### What actually happened

The Featured Image doesn't show:
<img width="1440" alt="Markup 2022-05-21 at 13 40 44" src="https://user-images.githubusercontent.com/51870544/169663726-df6ba208-72c8-472a-a2ea-2cc41ff516fd.png">

### Context

29588733-hc

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Disabling Jetpack Lazy Load resolves the issue.

**Comment by thekingsprojects** [comment]
Another case here: 5233159-zen

Gave them the Lazy Load workaround to see if it helps.

I was also able to replicate this issue on a Simple test site. In my case this happened both with the above user's embedded post and a post from WP Tavern, so it seems to affect embeds from multiple/any WP site.

Checking the inspector, it looks like it may be trying to display a 1x1 pixel image (see screenshot).

<img width="1353" alt="Markup 2022-05-21 at 15 06 31" src="https://user-images.githubusercontent.com/82622339/169666715-3f01f96c-107e-4182-bf89-1c34c2bc585a.png">

**Comment by formosattic** [comment]
+1 5233352-zen

**Comment by vinnykaur** [comment]
One more - 35099419-hc

**Comment by jromales** [comment]
another report in 5239232-zd-woothemes. I disabled Jetpack Lazy Load as workaround

**Comment by rw-ye** [comment]
5239071-zd-woothemes - shared workaround in chat.

**Comment by jp-imagines** [comment]
Another in 5241174-zd-woothemes. Disabled lazy images to resolve.

**Comment by the-misha** [comment]
User in 5239071-zd-woothemes came back to chat 35596739-hc to report that the workaround has stopped working around, and is just displaying links or the title linked to the embedded file.

**Comment by jromales** [comment]
Another one in 31762543-hc and I advised user to disable JP Lazy Load

**Comment by Jaykame** [comment]
Another one: 5233736-zd and gave the user lazy load workaround.

**Comment by vinnykaur** [comment]
hc-35133048 . Gave the workaround.

**Comment by manuelrebollo-a11y** [comment]
Another occurrence in 5265816-zd-woothemes
Provided the workaround.

**Comment by ghost** [comment]
In my opinion the Embed block is useful to embed content from another site. This is what the [documentation](https://wordpress.com/support/wordpress-editor/blocks/embed-block/#how-to-embed-content) says as well. 

Wouldn't a Blog Posts Block be a better suggestion for folks who want to showcase their posts on a different page of the same site? I am not sure why we are not explaining to them what the Embed block is for and not suggesting Blog Posts Block for the same. @ClassicRKR27 since you filed the original issue, could you shed some light?

**Comment by poeticabdul** [comment]
Another report here 5274654-zen . Suggested the work around

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- On my Simple and Self-hosted test sites, the Featured Image displayed without issue in the Embed block, while Lazy Load was on. i.e. - not replicated.
- On AT sites, using the Embed block with Lazy Load ON hides the featured image in both the editor and the live site, while turning Lazy Load OFF displays the featured image in both the editor and the live site.

**Simple**
<img width="600" alt="Screen Shot 2022-06-07 at 10 38 05 AM" src="https://user-images.githubusercontent.com/27249804/172447247-6be76bc4-fd24-4049-83cd-1565c616041b.png">

**Self-Hosted**
<img width="600" alt="Screen Shot 2022-06-07 at 10 37 35 AM" src="https://user-images.githubusercontent.com/27249804/172447157-57558b8d-2253-4260-a9cf-91599beb3e1b.png">

### AT: Lazy Load On:

**Editor:**
<img width="600" alt="Screen Shot 2022-06-07 at 10 40 23 AM" src="https://user-images.githubusercontent.com/27249804/172447617-f5f99f36-5056-45e9-aafd-d64a63eede16.png">

**Live Site:**
<img width="600" alt="Screen Shot 2022-06-07 at 10 40 40 AM" src="https://user-images.githubusercontent.com/27249804/172447671-d4bc5109-db90-4df7-ae16-dac887ccebb9.png">

### AT: Lazy Load Off: 

**Editor:**
<img width="1010" alt="Screen Shot 2022-06-07 at 10 39 57 AM" src="https://user-images.githubusercontent.com/27249804/172447549-ef7c8049-cc28-4710-aeca-ae36da06b6bf.png">

**Live Site:**
<img width="1456" alt="Screen Shot 2022-06-07 at 10 39 27 AM" src="https://user-images.githubusercontent.com/27249804/172447467-bfa66ab9-0918-4cba-9dbe-71f011e076e3.png">

📌 WORKAROUND NOTES
- As @rambogenius suggests, the Blog Posts Block can be used to display only specific chosen posts, so this is another workaround that will give the user more control over the appearance of their 'embedded' post.
- Still, not sure why Lazy Load impacts the appearance of the featured image within the embed block on AT sites in this way.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
One other note: on my AT test site with Lazy Load ON, embedded posts from an external site _do_ display their featured images, while the post from the same site's featured image is hidden.

<img width="600" alt="Screen Shot 2022-06-07 at 10 48 22 AM" src="https://user-images.githubusercontent.com/27249804/172448984-6e4efff6-08d6-4b04-9343-e2c8c7a05b87.png">

**Comment by edwinho89** [comment]
5292468-zd-woothemes

**Comment by jorpdesigns** [comment]
- [ ] Reported in 5292470-zd. Suggested disabling JP Lazy-load.

Also, I discovered the issue also occurs when embedding a post from another site. I had to disable JP Lazy-load on the site I was embedding from.

**Comment by jorpdesigns** [comment]
- [ ] Reported in 5283077-zd. User later disabled JP Lazy-load and the issue has been resolved.

**Comment by ClassicRKR27** [comment]
> In my opinion the Embed block is useful to embed content from another site. This is what the [documentation](https://wordpress.com/support/wordpress-editor/blocks/embed-block/#how-to-embed-content) says as well.
> 
> Wouldn't a Blog Posts Block be a better suggestion for folks who want to showcase their posts on a different page of the same site? I am not sure why we are not explaining to them what the Embed block is for and not suggesting Blog Posts Block for the same. @ClassicRKR27 since you filed the original issue, could you shed some light?

@rambogenius sorry for the late reply (I missed it), but honestly I hadn't thought of that - I wasn't aware of that part of the documentation for the Embed Block so I didn't think to suggest it. Though some of the replies since then seem to suggest that it's happening for outside sources as well.

**Comment by sudeepbaral** [comment]
- [ ] Reported in 5348960-zd, the user embedded posts from their own site

Suggested the user to disable Jetpack Lazy Load for Images

**Comment by danielbachhuber** [comment]
This issue was fixed in https://github.com/Automattic/jetpack/pull/24989, and is slated to be released in Jetpack 11.2
