### ISSUE TITLE
[AT]Customizer: Colors & Backgrounds color bullets cut by the section below when selected

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#63880]
### Quick summary

![image](https://user-images.githubusercontent.com/6737345/169649766-315dc9bd-7cbd-47a5-b0b3-0837c7112650.png)

### Steps to reproduce

1. Activate a theme with Colors & Background in the Customizer(e.g. Apostrophe 2, Rebalance, Twenty Eleven)
2. Click o one of the color bullets

### What you expected to happen

To see the section below the bullets

### What actually happened

The section underneath cover half the bullets.

### Context

This is what causes the issue:

![image](https://user-images.githubusercontent.com/6737345/169649706-f75cedb7-f753-48ec-aaf2-76600db1e0d8.png)

Path: `wp-content/mu-plugins/wpcomsh/custom-colors/css/colors-control.css?ver=5.9.3`

Slack: p1653131853268759-slack-C02FMH4G8

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
@jeffikus anything recently changed Themes where this feature is coming from? Could theme team have a look?

**Comment by Robertght** [comment]
I'm moving this to Triaged as I've already tested it.

**Comment by mpkelly** [comment]
I am looking at this now. I was able to reproduce it using the steps above. Even after removing the `margin-top: 20px` there is still an issue with wrapping on smaller screens:
![image](https://user-images.githubusercontent.com/6851384/177994055-d60765cf-fa8d-407e-b8db-200bf46833c0.png)

**Comment by mpkelly** [comment]
I've taken another look at this and identified a potential fix which allows for any number of colour under the **Colours** section without them being cut off or overflowing into the section below. 

The main issue I can see is the use of a fixed height without any way to handle overflow e.g. `overflow: auto`. But it also looks like the `margin-left` and `padding` can be removed too:

**Before**

![image](https://user-images.githubusercontent.com/6851384/178224106-bc948080-a02d-4a8c-aef2-c235460b4680.png)

**After**
![image](https://user-images.githubusercontent.com/6851384/178224193-f5e95ae9-15f2-43d8-ba6b-94f2909d868c.png)

The class that would be changed is at /wp-content/mu-plugins/colors/css/colors-control.css (line 90). 

The git log doesn't give me any clues as to why this became broken and before making a change I need to understand if anything else is impacted.

**Comment by mpkelly** [comment]
As per discussion with @creativecoder and @daledupreez, code exists separately for Simple and Atomic sites. The issue is reported and confirmed for Atomic sites, and I have also checked the Customizer for Simple sites. The spacing is a bit tight, but the colours overflow correctly. So I plan to fix this for Atomic sites. 

![image](https://user-images.githubusercontent.com/6851384/178711072-4a200e95-7e46-4b1f-8db3-381818468225.png)

**Comment by mpkelly** [comment]
Update: this has been fixed and should be rolling out shortly.

**Comment by Robertght** [comment]
@mpkelly I'm still able to replicate this on my end. Here's one example with Spearhead/Seedlet:

![image](https://user-images.githubusercontent.com/6737345/183712899-7ed37a83-d1f8-497a-bc5b-a3702c0a026b.png)


Has this already been merged?

**Comment by mpkelly** [comment]
Hi @Robertght, this is on an Atomic site, right? If you go to `/wp-admin/plugins.php` can you see **WordPress.com Site Helper** listed? If so, what is the version number?

I will try and reproduce it at my end and confirm that this has been released to Atomic sites. I will provide another update today.

**Comment by mpkelly** [comment]
I have reproduced this on a WoA site using Twenty Eleven. The CSS looks like it did before I made the fix, so it looks like the change didn't get released, or the change has been lost in a later release. I am still investigating, @Robertght.

**Comment by creativecoder** [comment]
Thanks for reporting, @Robertght !

I've redeployed the fix for Atomic sites--so that should fix the issue (again). Can you please check and let me know what you're seeing now?

**Comment by mpkelly** [comment]
Thanks, @creativecoder for getting your PR out quickly!

I also did some testing and I found the following:

- Existing Atomic site: fixed
- WoA site created yesterday: still has old/broken CSS
- WoA site created today: fixed

So all good as far as I am concerned. 

@Robertght, @creativecoder's PR also inlines the `custom-colors` module dependency, so regressions like this, where a later `wpcomsh` build mapped to an older version of `custom-colors` should not happen again in future.

**Comment by Robertght** [comment]
Thank you! 

It looks better now, however, I found this:

![image](https://user-images.githubusercontent.com/6737345/184071613-b30e8733-d8c2-436e-8471-af1c64c19e18.png)

The background picker is wider than it should be until you pick a color. Then it fixes itself.

The color picker on some themes looks like this now:

![image](https://user-images.githubusercontent.com/6737345/184072035-5725f75b-b792-40a6-91bd-5ca5d56cd133.png)


Initially, they were stacked 3 and 2 and were center aligned as far as I remember.

**Comment by mpkelly** [comment]
Hi @Robertght, the spacing change was intentional - see @creativecoder's comment [here](29-gh-Automattic/custom-colors#pullrequestreview-1051775728). 

The issue with the background change was not though. My view would be to create a separate issue for that and close this one. What do you think?

(p.s. please tag me in replies because I get notifications when tagged - thanks!)

**Comment by Robertght** [comment]
Sure @mpkelly ! Created one here: https://github.com/Automattic/wp-calypso/issues/66518 

Thank you!

**Comment by mpkelly** [comment]
> Sure @mpkelly ! Created one here: https://github.com/Automattic/wp-calypso/issues/66518 
> 
> Thank you! 

Thanks!
