### ISSUE TITLE
Marketplace: Make most popular searches one line

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#63897]
- [ ] Most popular searches can be bumped to one line

![image (2)](https://user-images.githubusercontent.com/811776/169758399-1cc9dc23-700c-460e-90ff-c8ab6ac63784.png)

**Comment by allilevine** [comment]
@vinimotaa @SaxonF Can we have your input on whether the text "Most popular searches" should be on one line with the search keywords?

**Comment by lsl** [comment]
And if mobile should wrap one line or keep multiline as it is now?

**Comment by SaxonF** [comment]
With the introduction of the categories bar I think we should stick to one line but can keep multi on mobile. We might decide its not even worth showing on mobile later.

**Comment by cpapazoglou** [comment]
These are now removed



![Image](https://user-images.githubusercontent.com/12430020/211634351-a9afbec1-a4ca-4712-a853-691a361bacb6.png)
