### ISSUE TITLE
Marketplace: Dont hide categories on search results / top paid / top free pages

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#63893]
Context: https://github.com/Automattic/wp-calypso/pull/63846#issuecomment-1134211561

I'm wondering how we can show the category bar on search results or "top paid" / "popular" pages. 

Right now we're hiding it which is a bit jarring.

We could add in a "Search" "category" in slot 0 when a search is active. or "Top Paid" when that is in view. 

- [x] Needs design - see below for follow ups now in place

**Comment by SaxonF** [comment]
@lsl like you mentioned the filter bar should be persistent and eventually also include search.

Thinking something like the below where if someone performs a search, clicks a category, or scrolls past category list/filter bar, search is added to the bar. This is essentially the search page. In the case of collections like "Top Premium" we may want to differentiate these slightly from generic searches using a title and description.

![image](https://user-images.githubusercontent.com/1072756/169757231-47fd92ff-1166-46b7-83da-69e059bda154.png)
![image](https://user-images.githubusercontent.com/1072756/169757272-cd87d079-54fa-4e8e-a21e-e35994e7e38b.png)
![image](https://user-images.githubusercontent.com/1072756/169757291-029eff83-5629-48aa-b151-2cce56a56e11.png)

**Comment by lsl** [comment]
At the moment I've dropped these titles in favor of treating them like any other categories: see after shot here https://github.com/Automattic/wp-calypso/pull/63892

![Screenshot 2022-05-23 at 15-46-53 Plugins — WordPress com](https://user-images.githubusercontent.com/811776/169751672-c2af7122-2f5d-4509-b1fc-19489cdd57c4.png)

Should we change this title to be a normal title for all categories or just top paid / top popular?

**Comment by SaxonF** [comment]
> Should we change this title to be a normal title for all categories or just top paid / top popular?

I think we can reserve titles for special categories like top paid / top popular and any other hand curated collections we create. 

When clicking on a category or performing a search or diving into a collection (e.g. top paid), what I'm proposing is to just minimize the top search section so that it becomes part of the filter/category bar. This becomes the search template that we use for all types of searches

What do you think?

**Comment by lsl** [comment]
I don't think these special categories are all that special. 

They've also made quite a mess in the code. Anything we can do to limit the amount of branching we do around these things would be helpful. 

Re the top bar category + search, looks good but I want to see what mobile needs to look like before we do anything as its going to need a bit of a shuffle to get everything in the right place across both modes / scroll positions.

**Comment by SaxonF** [comment]
Will work on that tomorrow @lsl

**Comment by SaxonF** [comment]
@lsl screens below include a few little design refinements.

**Home**
Default home/discover page remains the same. Top section has white background and includes categories list. Bottom section uses slight grey found in onboarding ( I think `#fdfdfd`) with a border 
![image](https://user-images.githubusercontent.com/1072756/170167509-6dfae67b-a606-467b-a1ea-93d136387854.png)

**Category**
When selecting a category we show more opinionated formatted results header including title, optional description, and number of plugins . I'll need to work on these with marketing but would be nice to set it up now.
![image](https://user-images.githubusercontent.com/1072756/170167595-91ae563f-2828-43ec-9152-60457afaddf8.png)
![image](https://user-images.githubusercontent.com/1072756/170169058-fbb34e88-b029-4b79-9cd4-0d44065bf880.png)

**Top paid plugins**
The sections found in home/discover are treated like any other category when clicking on "browse all". Could we also re-add "Top paid" + other discover groups into the categories list under more which is similar to your original suggestion?
![image](https://user-images.githubusercontent.com/1072756/170167532-81144d0f-8017-484b-8c33-d9c9dea687df.png)

**Search**
Search behaves much like categories, just putting a little less emphasis on title
![image](https://user-images.githubusercontent.com/1072756/170168920-d595a4aa-76e0-4687-8923-884baa049e67.png)

**Scroll**
Scrolling behaviour is what we've discussed in the past, just moving categories into fixed header with search. 
![image](https://user-images.githubusercontent.com/1072756/170167764-36c1324b-f517-4bf3-b92e-fde46a5cc51c.png)

Figma can be found here f84fqtCG4pCnCh2Hq0But5-fi-2011%3A26631

**Comment by lsl** [comment]
Moved all these to issues, couple of them need further clarification (clear button, scrolled view)

- Home / section grey https://github.com/Automattic/wp-calypso/issues/63837
- Category descriptions https://github.com/Automattic/wp-calypso/issues/64055 **(Needs design, see ticket)**
- Add top paid / popular as categories https://github.com/Automattic/wp-calypso/issues/64056
- Search result text https://github.com/Automattic/wp-calypso/issues/64057 **(Needs design, see ticket)**
- Moving category selector into the fixed header https://github.com/Automattic/wp-calypso/issues/64058 **(Needs design, see ticket)**

**Comment by lsl** [comment]
Closing this out in favor of https://github.com/Automattic/wp-calypso/issues/64056 (added subtask to show the category bar on all category pages)
