### ISSUE TITLE
Purchases: Misleading description on domain purchase details.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#63891]
### Quick summary

The description for domain registration purchase is misleading.

> Replaces your site's free address, subdomain. wordpress.com, with the domain, making it easier to remember and easier to share.

Purchasing or registering a domain is not enough to replace the free site address. Users also need paid plan or addon.

### Steps to reproduce

1. Go to the Purchases page in an account with a domain.
2. Check details of domain registration purchase.

### What you expected to happen

The description should not be misleading.

### What actually happened

The description is misleading for new users. It sets wrong expectations and leads to them writing nasty messages to the Happiness team and bad impression of the company.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/33957570/169747902-5af2e68e-5a3c-4640-98e4-45ed132dee61.png">

### Context

5218510-zen

This is just one of the recent interactions but it is a pretty common occurrence where new users expect to use a custom domain without a paid plan or addon ( upcoming ).

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by vajrasar** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Able to replicate and Simple and AT. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by jordesign** [comment]
Pinging @Automattic/editorial  for some advice on how to word this accurately?

**Comment by daledupreez** [comment]
I am going to ping @Automattic/nomado, @wensco, and @semihakocer on this issue, as they're the team with the best insight into how we're currently communicating domain-related details to users.

**Comment by SeywardDarby** [comment]
Editorial team here — I am happy to propose language, but I want to make sure I've got this right: Registering a domain will only replace the free address *if* the user also has a paid plan or an add-on. What add-on(s) are we talking about?

**Comment by wensco** [comment]
Looking at /purchases, I'm not really sure that this copy blurb adds much value. I don't think a lot of users are ending up looking at their purchases to clarify what a custom domain does. I think they would be more inclined to look at https://wordpress.com/domains/manage/ but we don't have any similar language there at all - nor under domain settings.

One option would be to simply remove it. This might be the simplest solution unless folks think this adds enough value for us to tweak it and keep it. 

If we want to keep it, we can perhaps modify it to something like:

> When used with a paid plan or add-on, your custom domain can replace your site's free address, [wpcom sudomain], with [custom domain name], making it easier to remember and easier to share.

TBD on the add-on since I'm not sure at this time how paid add-ons will impact primary domain behavior without a paid plan. Perhaps @SeywardDarby has some better suggestions - this one was just off the top of my head so feel free to ignore it!

**Comment by jordesign** [comment]
> Looking at /purchases, I'm not really sure that this copy blurb adds much value.

> One option would be to simply remove it.

+1 to this - I think just removing it would be ok.

Especially when you consider that for some users - the domain registration is not actually *for* replacing their site URL - they've got it pointed somewhere else.

**Comment by semihakocer** [comment]
This copy is proof of product to make sure customers understand the product value and keep renewing under the purchases page. This is the only page they'll review after purchase/at renewal time/cancellation etc.
I'd vote against removing the copy in this case and move on with @wensco suggestions listed [here](https://github.com/Automattic/wp-calypso/issues/63891#issuecomment-1158035458).

**Comment by mpkelly** [comment]
The [wording change](https://github.com/Automattic/wp-calypso/pull/66260) has now been deployed.

**Comment by daledupreez** [comment]
Marking this issue as resolved now that #66260 has been deployed.
