### ISSUE TITLE
Reader: remove existing feed or topic from list

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#639]
If a user has added content to a Reader list (either tags or feeds), it should be possible to remove each one.

<img width="981" alt="17325 copy" src="https://cloud.githubusercontent.com/assets/66797/11372020/90148894-9288-11e5-92eb-49805200ba1b.png">

**Comment by alisterscott** [comment]
Lists are unavailable for customers without lists, and existing lists users can't manage these lists any more, so closing this issue as no longer applicable. See `p5PDj3-1Fg-p2`
