### ISSUE TITLE
Marketplace search: get all search results with one request (mixing .org and .com results)

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#63905]
Support querying for both WC.com and WP.org results on the endpoint.

**Comment by gcsecsey** [comment]
Backlog Grooming: We should complete https://github.com/Automattic/wp-calypso/milestone/396 before estimating this ticket.

**Comment by gcsecsey** [comment]
Once WC.com results are added to the API, we can test getting mixed results by sending queries with the `marketplace` group ID.

We need to make sure that the ranking between WP.org and WC.com results is consistent, and for a given search term we're receiving equally relevant matches from both sources.

**Comment by gcsecsey** [comment]
The config in Calypso will also need to be updated. The groupId needs to be changed from `wporg` to `marketplace` to include results from both sources.

**Comment by gcsecsey** [comment]
I've started working on this issue and found some outstanding issues. Some of these are already tracked in GitHub:

1. Prices aren't shown for search results: https://github.com/Automattic/wp-calypso/issues/70479
2. Icons aren't always shown for search results: https://github.com/Automattic/wp-calypso/issues/70233
3. Products that are not yet added to the Marketplace are shown: https://github.com/Automattic/wp-calypso/issues/69370
4. Author/vendor names are mismatched or missing: https://github.com/Automattic/wp-calypso/issues/70781

Example for 1., 2. and 4.:
![Image](https://user-images.githubusercontent.com/11555574/203054935-ddfbabed-6a8b-4fd1-8e78-87b99b99993f.png)

Example for 3. and 4.:
![Image](https://user-images.githubusercontent.com/11555574/203054838-c8699c45-3910-4c46-846c-6914230ebef8.png)

I've raised a draft PR where I'm working on fixing these issues, I'll try creating smaller PRs from it that are easier to review and cover one of the tracked issues separately: https://github.com/Automattic/wp-calypso/pull/70234

**Comment by cpapazoglou** [comment]
It seems that we still need to wrangle https://github.com/Automattic/wp-calypso/issues/70781.
We have also raised D95306-code regarding the plugin order

**Comment by epeicher** [comment]
The author issue dependency has been done:
- https://github.com/Automattic/wp-calypso/issues/70781

**Comment by gcsecsey** [comment]
I've tested these changes again, and found that:
- Author names work as expected on a test index, but are not yet re-indexed to the `jetpack-search` index:
  ![Image](https://user-images.githubusercontent.com/11555574/210071531-e64716a6-6dc2-4aee-b324-3b6a0a810b2e.png)
  @robfelty is there perhaps a new version of the `jetpack-search` index planned to be built, or should we go ahead and re-index WP.com products on version 26?
- Product icons (the `_app_icon` meta field) are not synced to Jetpack, therefore not stored in ES either yet for these products:
  - ~~calendar-booking-wpcom~~ fixed
  - ~~automatewoo~~ fixed
  - ~~woocommerce-back-in-stock-notifications~~ fixed
  - ~~woocommerce-one-page-checkout~~ fixed
- the `product_slug` field is missing for these products:
  - ~~woothemes-sensei~~ fixed
  - ~~presto-player-pro~~ fixed

**Comment by cpapazoglou** [comment]
While trying to wrangle @gcsecsey findings above, I have also noticed that we use the WC.com permalink slug for building the Calypso URL. example:

- wrong `https://wordpress.com/plugins/woocommerce-paid-courses`
- correct `https://wordpress.com/plugins/woothemes-sensei`

**Comment by cpapazoglou** [comment]
Regarding the icons:
- the field accepts only `80x80` or `160x160`
- for `automatewoo` I just downloaded it and uploaded again.

**Comment by cpapazoglou** [comment]
author names seem working for me now ( I haven't touched anything )

**Comment by gcsecsey** [comment]
> While trying to wrangle @gcsecsey findings above, I have also noticed that we use the WC.com permalink slug for building the Calypso URL. example:
> 
> * wrong `https://wordpress.com/plugins/woocommerce-paid-courses`
> * correct `https://wordpress.com/plugins/woothemes-sensei`

Currently, Calypso builds the URL from the `plugin.slug` field: https://github.com/Automattic/wp-calypso/blob/f95292a082b3c0b964d3c45acfd14037baa7ff26/client/my-sites/plugins/plugins-browser-item/index.jsx#L74

I think for Marketplace products, we should either send the `product_slug` field from the API and build the URL with that value in Calypso, or directly send that value in the `plugin.slug` field from the API. AFAIK the WC.com slug won't be used in Calypso for other purposes, right?

**Comment by cpapazoglou** [comment]
> directly send `product_slug` value in the plugin.slug field from the API

this would be more consistent with the .org plugins and preferable to me. 

> AFAIK the WC.com slug won't be used in Calypso for other purposes, right?

no, it's not used at all ( and shouldn't ).

**Comment by gcsecsey** [comment]
Diff created for the slug issue: D97350-code

**Comment by gcsecsey** [comment]
Backend changes deployed in revision r259040-wpcom

**Comment by robfelty** [comment]
>     * Author names work as expected on a test index, but are not yet re-indexed to the `jetpack-search` index:
>       ![Image](https://user-images.githubusercontent.com/11555574/210071531-e64716a6-6dc2-4aee-b324-3b6a0a810b2e.png)
>       @robfelty is there perhaps a new version of the `jetpack-search` index planned to be built, or should we go ahead and re-index WP.com products on version 26?
If there are no mapping changes (only doc builder changes), then re-indexing version 26 should be fine. If there are also mapping updates necessary, we probably need to create a version 27.

**Comment by gcsecsey** [comment]
> If there are no mapping changes (only doc builder changes), then re-indexing version 26 should be fine. If there are also mapping updates necessary, we probably need to create a version 27.

This was the diff that updated the field, there are no mapping changes: D95901-code

Thanks @robfelty I think version 26 is fine too. I've done some example searches and the author names are now working as expected! 🎉

**Comment by gcsecsey** [comment]
I've raised a PR to update the FF on the environments, but E2E test currently fail on it. When running E2E tests, Royal Mail is being downranked because of a low install count, so it doesn't appear on the results page:
<img width="531" alt="CleanShot 2023-01-10 at 15 46 26@2x" src="https://user-images.githubusercontent.com/11555574/211597078-caa40c56-e1bc-46e1-9ec0-e13eb5a35f5b.png">

I think the low install count is caused by the indexer using the WC.com slug to get install data instead of the `product_slug`, similarly to the issue here: https://github.com/Automattic/wp-calypso/issues/63905#issuecomment-1375657137 I'll raise a diff to update the indexer.

**Comment by gcsecsey** [comment]
Diff created: D97495-code

**Comment by gcsecsey** [comment]
Changes are deployed with r259297-wpcom
