### ISSUE TITLE
Tour Kit: Add ability to remove minimize functionality

### ISSUE THREAD

**Issue by adrianduffell** [Automattic/wp-calypso#63909]
## User Story

As a WooCommerce developer, I want to hide the minimize button and disable its functionality, so that I can provide a consistent Woo UI.

## Acceptance Criteria

* Provide a way to disable the minimize functionality through a configuration option.

**Comment by chihsuan** [comment]
@adrianduffell, I just checked the Tour Kit. I think it already has a way for the user to decide whether to have a minimize button or not.

If we don't want it, we just do not provide a minimize button in the `config.renderers.tourStep` component when we create our Woo variant component.

For example, The minimize button will not be displayed, If we remove `<button onClick={ onMinimize }>Minimize</button> ` (line 82) and update tourMinimized to return `null` in the **storybook**.

https://github.com/Automattic/wp-calypso/blob/6a02f2d82c1b8260c0b09fbe388840585329cc2b/packages/tour-kit/src/storybook/index.stories.tsx#L68-L106

cc @Automattic/ghidorah

**Comment by adrianduffell** [comment]
That's pretty neat, thanks for exploring this @chihsuan !

I think we can close this out then, so I'll do that 😃
