### ISSUE TITLE
Quadrat White - No Comments via Post Comment Block

### ISSUE THREAD

**Issue by janmckell** [Automattic/wp-calypso#63901]
### Quick summary

This occurs on Quadrat White theme with the Post Comments Form on the Single Post template.

When that template is used for a post, no comments show up on the form.

When the 'Post Comments' block is used, it shows up, but the 'Post Comments Form' block does not show when used.

Two tests resulted in the same result.

I could not replicate this a third time, but posting it even still.

### Steps to reproduce

1. Add a Post Comments Form block to the 'Single Post Template' in the Full Site Editor for a site using the Quadrat White theme
2. Ensure that a new post, uses that single post template and that the post is published.
3. Preview post on the site - the Post Comments Form block does not show.
4. If a 'Post Comments' block is added, the Comments Form shows as part of it, but when a 'Post Comments Form' block is used independently,  the Comments do not show in the front end.

![Markup 2022-05-20 at 14 23 00](https://user-images.githubusercontent.com/84089207/169790371-e06d2371-819e-40f8-973b-fec1dde1615a.png)

![Markup 2022-05-20 at 14 23 17](https://user-images.githubusercontent.com/84089207/169790377-2f98ccf5-0cbd-442e-a356-7c793c462c2e.png)

### What you expected to happen

That both post comment form and the entire comments block would show, in the location it was placed in, via the Single Post Template, on the live preview of the post.

### What actually happened

Only the post comment form shows. The comments themselves do not.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

I'm not sure.

### Browser, operating system and other notes

The test was done on two different computers.

### Reproducibility

Intermittent

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I have tested this with Quadrat and Quadrat White and I cannot replicate this


📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs


📌 Message to Author
 - I can see the Post comments block is now deprecated and we can use the Comments block instead.
