### ISSUE TITLE
Marketplace search: Add WC.com product fields to the `jetpack-search` index

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#63903]
Since was deployed, WC product results started being indexed to the `jetpack-search` index, and some fields can already be queried.

Example query: https://public-api.wordpress.com/rest/v1.3/marketplace/search?group_id=woocommerce&query=woocommerce&fields[0]=slug&fields[1]=author&fields[2]=title.default

### Search results
I've updated the table of fields needed for search results with the JP search index column, but we still need to add the fields that are marked with ❌: pdh6GB-Mm-p2#comment-1632

### Plugin details page
I've also added a new table with the fields required to be able to display the plugin details page: pdh6GB-Mm-p2#comment-1970

**Comment by gcsecsey** [comment]
Backlog Grooming: We should complete https://github.com/Automattic/wp-calypso/milestone/396 before estimating this ticket.

**Comment by gcsecsey** [comment]
This issue might still be blocked by some meta fields not being synced: pdh6GB-Ax-p2#comment-2104

**Comment by gcsecsey** [comment]
## Resolving the sync issues to unblock indexing

Based on the discussions on this thread (pdh6GB-Ax-p2#comment-2104), to sync the required fields, we will need to enable sync for additional meta fields and taxonomies. I've broken down the steps to do so below.

### Meta fields
Based on: pdh6GB-Ax-p2#comment-2504

**Steps:**
- add the new meta field to the allowlist
- deploy the changes
- run a full sync
- verify data from site explorer or DB

**Required fields**
 - product video – `_featured_product_video` meta field
 - product icon – `_app_icon` meta field
 - WP.org slug – `wpcom_marketplace_org_slug` meta field

### Taxonomies
Based on: pdh6GB-Ax-p2#comment-2503

**Steps:**
- add the new taxonomy to the allowlist
- deploy the changes
- run a full sync
- verify data in the index

**Example PRs:**
- WPCOM: D76393-code
- Jetpack: https://github.com/Automattic/jetpack/pull/23333

**Required fields**
 - product categories – `wpcom_marketplace_categories` taxonomy
 - product tags – `product_cat` taxonomy

**Comment by gcsecsey** [comment]
Created WPCOM diff: D85227-code
Created Jetpack PR: https://github.com/Automattic/jetpack/pull/25376

**Comment by gcsecsey** [comment]
Based on the discussion on #60769, we'll also need to sync the `wpcom_marketplace_org_slug` meta field:
https://github.com/Automattic/wp-calypso/issues/60769#issuecomment-1209158455

**Comment by cpapazoglou** [comment]
Whats blocks us from adding it to D85227-code?

**Comment by gcsecsey** [comment]
> Whats blocks us from adding it to D85227-code?

From my earlier discussions on this issue with Kernel, there has been a new thread created: p9dueE-5AB-p2

I wanted to clarify that these changes are still needed based on the discussion on the project thread: pdh6GB-Ax-p2#comment-2503

I'll move forward with updating the diff, and adding reviewers from these teams.

**Comment by gcsecsey** [comment]
I've added the `wpcom_marketplace_org_slug` to the diffs:
- WP.com diff: D85227-code
- Jetpack PR: https://github.com/Automattic/jetpack/pull/25376

**Comment by gavande1** [comment]
Deployed r251257-wpcom
