### ISSUE TITLE
Dotcom Marketplace: Add "Composite Products" to the Dotcom Marketplace

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#63919]
We'll add the **[Composite Products](https://woocommerce.com/products/composite-products/)** Woo extension to the marketplace

FG page with all the instructions - PCYsg-AhC-p2

Here are 2 examples of recent integration works:
https://github.com/Automattic/wp-calypso/issues/63083
https://github.com/Automattic/wp-calypso/issues/63300

**Comment by BogdanUngureanu** [comment]
Product constants added in r246227-wpcom

**Comment by BogdanUngureanu** [comment]
Product mappings added in r246315-wpcom

**Comment by lukaszwilczakwilnet** [comment]
Feature checks added in D81568-code

**Comment by lukaszwilczakwilnet** [comment]
Translations added in D81702-code

**Comment by lukaszwilczakwilnet** [comment]
Marketplace enpoint added in D81774-code

**Comment by lukaszwilczakwilnet** [comment]
Remove flags here: D81845-code

**Comment by lukaszwilczakwilnet** [comment]
Updated version of plugin D81854-code

**Comment by Copons** [comment]
Confirmed it's working for non-a11n users!
