### ISSUE TITLE
Stepper Onboarding - Establish requirements for help icon behavior

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#63925]
In Slack discussions relating to https://github.com/Automattic/wp-calypso/pull/63870, it was determined that implementation of the floating Help icon (Inline Help) in Stepper onboarding has overarching design concerns. Let's follow up on establishing more concrete requirements on how (or if) we should be re-introducing this component into the onboarding experience.

**Comment by andres-blanco** [comment]
If we want to add the help icon it should leverage the new Help Center instead the inline help component used in that PR. Closing this because this button is probably not needed in the user experience.
