### ISSUE TITLE
Marketplace: Combine search and category browsing routes

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#63940]
- [x] Move plugin categories under `/plugins/browse/:category` routes and out of `/plugins/:pluginOrSiteOrCategory`
- [ ] Try to simplify [this code](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L133)

Suggestion from https://github.com/Automattic/wp-calypso/issues/63030

**Comment by allilevine** [comment]
Related bug report that would be fixed by this change: p1653510919454469-slack-C029JEQRVRT

**Comment by Rolilink** [comment]
Like this one but have my reservations due to the idea of the marketplace being public one day and SEO. Maybe adding a `/plugins/browse/:category` route will achieve the same without affecting SEO in the future?

**Comment by lsl** [comment]
I don't think there is much of an seo concern using query params vs pretty urls?

For me it comes down to how much filtering we want to put in to search. I was sort of aiming for running everything through the search route with categories just being a filter on search.

**Comment by Rolilink** [comment]
> I don't think there is much of an seo concern using query params vs pretty urls?

Should we ask someone about this?

>For me it comes down to how much filtering we want to put in to search. I was sort of aiming for running everything through the search route with categories just being a filter on search.

I see categories more like collection pages than filters, I am not 100% sure but I think is a good idea is that this pages could appear on search results as sub-pages when the marketplace is public.

**Comment by lsl** [comment]
This isn't something I feel strongly about, main issue for me is getting complexity out of the main `/plugins/:something` route, updated acceptance to use `/plugins/browse/:category` instead.
