### ISSUE TITLE
Reader: scheduling a previously published post moves it to the top of the Reader stream

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#6394]
If you re-schedule an already-published post, it will move to the top of the Reader list.

Steps to reproduce:
1. Log in as user 1 and follow user 2's blog
2. Log in as user 2 and publish two new posts a few minutes apart
3. Update the publish time for the first post, or for any past post on the blog, to a few min in the future
4. Wait until the scheduled time passes
5. Log in as user 1 and check to see if the first post appears in its original place in the Reader stream or if it has been moved to the top of the list

<strong>Result:</strong> re-scheduling a previously published posts moves it to the top of the Reader stream.

/hat tip @rwaynick for the original report

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed that this is still an issue as described above.  But I'm not entirely sure it's a problem...Wouldn't you want the Reader to show your post at its current published time, whether that was the original time or updated?

**Comment by rwaynick** [comment]
The concern is that a user will constantly change the published time to get more exposure.

**Comment by bluefuton** [comment]
Reopening as the related support issue has not yet been resolved (p5PDj3-Vg).

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it. 

To me the root level solution would be to simply unfollow the person who is spamming you.
