### ISSUE TITLE
[Gutenberg 13.3.0-rc.1] FSE: The Site Editor does not load

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#63944]
### Quick summary

During our team testing, we found that the site editor does not load while using an FSE-compatible theme. 

<img width="1792" alt="Markup 2022-05-24 at 12 37 01" src="https://user-images.githubusercontent.com/21261509/169937252-29171316-91b7-4a79-9d0c-ff1e16aa0bcd.png">

- Self-hosted sites are working normally.
- Non-a11n accounts are also impacted.  

**Error in Console**

```
??-eJytVNGSmzAM/KEal…Pzt5fTL+tvH9w=:1028 Uncaught TypeError: (0 , c.dispatch)(...).setDefaultComplementaryArea is not a function
    at fo (??-eJytVNGSmzAM/KEal…TL+tvH9w=:1028:1510)
    at Module.Eo (??-eJytVNGSmzAM/KEal…TL+tvH9w=:1028:2321)
    at HTMLDocument.<anonymous> (VM1642 themes.php:16355:17)
fo	@	??-eJytVNGSmzAM/KEal…Pzt5fTL+tvH9w=:1028
Eo	@	??-eJytVNGSmzAM/KEal…Pzt5fTL+tvH9w=:1028
(anonymous)	@	VM1642 themes.php:16355
```

### Steps to reproduce

1. Activate an FSE compatible theme: https://wordpress.com/themes/filter/full-site-editing
2. Open the site editor.
3. The site editor does not load.

### What you expected to happen

The site editor to load.

### What actually happened

The site editor did not load.

### Context

During team testing of Gutenberg.

### Browser, operating system and other notes

Chrome

**Comment by sudeepbaral** [comment]
Site editor did not load for me as well. I tried in non-a8c account too and the issue persists. This happens across both simple and atomic sites. Error in Console:

```
Uncaught TypeError: (0 , c.dispatch)(...).setDefaultComplementaryArea is not a function

at fo (??-eJytVNGSmzAM/KEal…TL+tvH9w=:1028:1510)
at Module.Eo (??-eJytVNGSmzAM/KEal…TL+tvH9w=:1028:2321)
at HTMLDocument.<anonymous> (VM2997 themes.php:16371:17)
fo    @    ??-eJytVNGSmzAM/KEal…Pzt5fTL+tvH9w=:1028
Eo    @    ??-eJytVNGSmzAM/KEal…Pzt5fTL+tvH9w=:1028
(anonymous)    @    VM2997 themes.php:
```

**Comment by Addison-Stavlo** [comment]
suggested fix at https://github.com/Automattic/wp-calypso/pull/64093
