### ISSUE TITLE
Anchor FM - Site not visible after creating a new account and connecting 

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#63946]
### Quick summary

Difficult to reproduce. I have seen isolated incidents, especially with Atomic sites. Users try to create a new account and link their WordPress.com sites with it. They are unable to see the site within the Anchor FM account. 

Anchor FM support responds by saying they do not support Jetpack sites. Are these sites caught as self hosted sites?

Ticket 
5229334-zd

Tickets may autoclose and we can reply once the issue is resolved. 

### Steps to reproduce

Difficult to reproduce since issue may be account specific. I had a similar issue way in the past, but unable to get the link to that at the moment.

### What you expected to happen

Anchor should show the site

### What actually happened

Anchor did not show the site. 

### Context

5229334-zd

Tickets may autoclose and we can reply once the issue is resolved.

**Comment by inaikem** [comment]
Pinged @Automattic/serenity for a confidence check here: p1654058887690669-slack-C0Q664T29

**Comment by andres-blanco** [comment]
This is not an occurrence of the previous bug it's a different issue.

There’s a mismatch between the `external_user_code` on the token and the meta `jetpack_json_api_70956` on the AT site. 

Waiting for confirmation to attempt to run a fix on the slack thread mentioned above.

**Comment by andres-blanco** [comment]
@nagpai a fix attempt was made. We need to reach out to the user to confirm if it worked or not, she needs to see if the Anchor.fm import is working.

Basically I updated the user meta on the AT site to the value that was set on the `external_user_code` column on WP.com side. This is the command that was run on the AT site:
```sh
wp user meta update [USER_ID] jetpack_json_api_70956 [SECRET_TOKEN]
```

**Comment by andres-blanco** [comment]
The problem was resolved.

5229334-zd-woothemes
