### ISSUE TITLE
Jetpack connect: Jetpack version dettection failing in some cases

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#6397]
From @ryelle : 
I just found an issue with connect's detection of whether I have Jetpack installed. I have a nginx server with default permalinks (that is, no rewrites, just ?p=2 etc). trying to fetch the jetpack readme ​_doesn't_​ return an error code, so `getJetpackVersion` falls through to `true` – and i get an " You must update Jetpack before connecting" error which is incorrect.

If I switch on pretty permalinks, WP knows that `/wp-content/plugins/jetpack/readme.txt` doesn't exist, and correctly detects that I have no jetpack.

**Comment by tyxla** [comment]
Work is in progress here: #D2406-code

**Comment by tyxla** [comment]
Fixed in #r139700-wpcom
