### ISSUE TITLE
Invite Email to Subscriber is worded similarly to Contributor invite email 

### ISSUE THREAD

**Issue by NatzJoy** [Automattic/wp-calypso#63978]
### Quick summary

When sending an Invitation to someone via the Users tab in the WordPress.com dashboard, you have the option of selecting the role of the person you are inviting. The roles are as follows: 

* Administrator
* Editor
* Author
* Contributor 
* Follower 
* Subscriber

### An email goes out to the person you are inviting which describes why you're inviting them. In this specific user's case (5235454-zen), the wording in the Subscriber invitation email below...

![Subscriber Email sent](https://user-images.githubusercontent.com/66021614/170089650-59527705-b0f3-4843-98b6-385807f8625b.png)

### ...is worded similarly to the Contributor's invitation email: 

![Contributor Email Sent](https://user-images.githubusercontent.com/66021614/170090438-776b39a0-cb75-4ac1-a72e-39cd32af04e4.png)

The title of the email on both invitations reads XXX has invited you to contribute to XXX.

The issue appears to be isolated to this specific user at this stage. I tested it on my own site and the wording should read as follows:

* **Subscriber**: _Username has invited you to follow Site Link_. 
* **Contributor**: _Username has invited you to contribute to Site Link_.

### Steps to reproduce

1. Switch to User via Store Admin.
2. Navigate to the Users tab in the WP.com dashboard.
3. Click Invite+ in the top right-hand corner of the User section.
4. On the next page, type an email address or WP.com username in the Usernames or emails space.
5. Then select user role from the options available. I selected **Subscriber**.
6. Type a short message (optional), I typed _I'd like you to follow my blog_.
7. Send Invitation.

After completing the above Invitation, I followed Steps 1 to 5 again, this time selecting **Contributor**. I did not type a message and sent the invitation.

### What you expected to happen

**I expected the emails to read as follows:**

* **Subscriber**: Username _has invited you to **follow**_ Site Link. 
* **Contributor**: Username _has invited you to **contribute** to_ Site Link.

### What actually happened

The invitation emails that are sent to Subscribers are worded similarly to the invitation emails that are sent to Contributors.

### **Contributor Invitation Email:**

![CleanShot 2022-05-24 at 18 51 00@2x](https://user-images.githubusercontent.com/66021614/170120211-7003db04-0359-40f6-8c15-c8a12d81f632.png)

### **Subscriber Invitation Email:**

![CleanShot 2022-05-24 at 18 43 57@2x](https://user-images.githubusercontent.com/66021614/170120395-639f88a8-ba39-436e-9d71-55c1e0bf3d39.png)

### Context

The customer reached out to us via chat to inform us of this issue, 34825163-HC. I created a ticket for the issue, tested it on one of my sites, and then on the user's site. The issue appears to be specific to the user only. 

### Simple, Atomic or both?

Atomic

### Browser, operating system and other notes

The issue is not browser specific and is currently affecting only this one user as far as we know.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, difficult to implement

### Workaround details

The user has a Business Plan, so they can download a plugin such as [**Invite Anyone**](https://wordpress.org/plugins/invite-anyone/#description) which is available in the WordPress.org plugin directory. 

### Invite Anyone Plugin description

_The plugin provides the ability to invite members to the site by email. The plugin creates a tab on each member’s Profile page called “Send Invites”, which contains a form where users can invite outsiders to join the site. There is a field for a custom message._

**Comment by happychait** [comment]
- [ ] Another report in 5354848-zen

**Comment by happychait** [comment]
This happens in the Jetpack app as well, as shown in this video: 

https://user-images.githubusercontent.com/1519466/207214470-d26497ad-4971-48d2-b1fc-2d1255c917a6.MP4

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could Not Replicate
- Tested on Atomic - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- The way that subscribers are added to a site now differs from team members; when inviting a User to the site as part of the team, Subscriber is not an option.

📌 ACTIONS
- Closing as not relevant
