### ISSUE TITLE
Add an Icon Block

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#63973]
### What

It would be useful to have an "Icon Block" that made freely-available icons available in the Block Editor.

[Noun Project](https://thenounproject.com/) is one such source of icons. [Heroicons](https://heroicons.com/) is another.

### Why

In 5240894-zen, a user wanted to build something similar to this screenshot:

![image](https://user-images.githubusercontent.com/36432/170096579-c9a28198-ab1c-4b4f-941f-1a829d907a0a.png)

I pointed them to the Noun Project. It would be a better user experience if I could say "Use the Icon Block".

**Comment by pablohoneyhoney** [comment]
Note that there's this happening in Gutenberg https://github.com/WordPress/gutenberg/issues/16484 to possibly contribute to. 

cc @vindl @SaxonF

**Comment by zachspears** [comment]
I really love this idea! Since this is already in the works at https://github.com/WordPress/gutenberg/issues/16484 as noted by @pablohoneyhoney I am going to close this issue.
