### ISSUE TITLE
Jetpack connect: Regular authorisation flow

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#6399]
A main purpose of JPC was to eventually replace the old flow. This is it! We are going to prepare the new JPC authorization screen to replace the old one.

The entry point will be the “authorisation step” (user may need to create a new account as per usual flow). On completion, we will need to send the user back to wp-admin. We should do this project in the way we’ve previously discussed of redirecting only a % of users (say 10% to start) to the new flow

**Comment by johnHackworth** [comment]
@richardmuscat should we redirect the users back to their wp-admin just after authorization is successful or should we show the plans selection page and redirect them once they choose one (if they choose the free one)?

**Comment by richardmuscat** [comment]
@johnHackworth: definitely show the plans page and redirect as you suggest based on plan selection
