### ISSUE TITLE
AMP: Use default dev tools visibility for Atomic users where the extension isn't managed by us

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64007]
`amp-wp` 2.0 introduced dev tools which were enabled by default. We didn't want it enabled by default so in 514-gh-Automattic/wpcomsh we overrode the default.

In `amp-wp` 2.0.1 an official filter was added to override the default (https://github.com/ampproject/amp-wp/pull/5333) so our special override is no longer necessary and we can use the official filter instead.

We should decide whether we want the dev tools to start appearing for users on Atomic who have installed AMP. In my opinion, we want the AMP experience to be as vanilla as possible, which means either rolling back 514-gh-Automattic/wpcomsh or using the official `amp_dev_tools_user_default_enabled` filter to only disable the tools by default if the plugin has been marked as "managed by the platform"

See project thread: pdKhl6-48-p2

**Comment by p-jackson** [comment]
Just for extra context, we've decided that the plugin will continue to be managed by us by default (pdKhl6-ds-p2). That still leaves a question about whether we should change the default visibility of the dev tools.

**Comment by vykes-mac** [comment]
@p-jackson was any decision taken re your question? since we decided to leave AMP to be managed by us, do we keep the devtools as it is or remove our override to use the newly introduced filter?

**Comment by p-jackson** [comment]
The plugin can be either in a managed or unmanaged state. And that isn't going to change, the decision in pdKhl6-ds-p2 was about whether we still want it to be _possible_ for the plugin to be managed. Which we do. But we can still "unmanage" the plugin by either installing AMP via a zip file, or by using the CLI, which is something link `wp plugin symlink amp` from memory.

That being said, no decision has been made about whether we should change the default visibility of the dev tools. Would you be able to take that on? I think the @Automattic/reactor team would be a good place to start that conversation.

**Comment by vykes-mac** [comment]
Issue fixed here 971-gh-Automattic/wpcomsh
