### ISSUE TITLE
Stats: Incorrect calculation for "All-time" views

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#64009]
### Quick summary

Our user reported that their "All-time" views are not correctly reflected in their site stats when viewed in the WordPress.com dashboard. It's unclear whether the stats are correct when viewed in the mobile app.

Currently, the "All-time" views under the _Insights_ tab reflect that the site has had roughly 1,014,069 views, as you can see here:

![Capture_2022-05-25 at 10 33 01](https://user-images.githubusercontent.com/2912202/170208464-0fc2d7be-f948-4565-a112-f855d10715e1.jpeg)

I captured this screenshot today.

By contrast, if I total their views since 2016, they have close to three million views, as you can see here:

![Capture_2022-05-25 at 10 36 42](https://user-images.githubusercontent.com/2912202/170208672-edab78c6-c723-4905-a182-f830414d9b51.jpeg)

I initially thought that the value there was just for the current year, but that isn't correct either. The user reported that they are pretty sure they saw the correct value at one point, and then something changed.

### Steps to reproduce

1. Head to the user's Stats page in their dashboard
2. Compare annual totals to the "All-time" views on the stats page.

### What you expected to happen

The "All-time" views should accurately reflect the total views for the site for "all -time".

### What actually happened

The "All-time" views are inaccurate.

### Context

A user's report in 5236694-zen

### Simple, Atomic or both?

Simple

### Theme-specific issue?

This is unclear. The user is using the Stow theme.

### Browser, operating system and other notes

This doesn't seem to be influenced by browser or operating system. I was able to see this in Microsoft Edge v101.0.1210.53 on macOS 12.3.1

### Reproducibility

Once

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by aidvu** [comment]
Hi @pauljacobson. Checked a subsample of all blogs, and found only this one, which is now fixed. Will keep an eye for them, and this one can be closed.
