### ISSUE TITLE
AMP: Disable AMP on 2% of existing simple sites

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64003]
Once AMP has been disabled for all new sites in #64002 we

**Tasks**
- [x] Update AMP eligibility logic so that 2% of "old" sites can't use AMP
   - e.g. `blogId % 100 < 2` (we can update this expression as we roll out to higher and higher percentages)

See project thread: pdKhl6-48-p2

**Comment by wojtekn** [comment]
I've created a diff D82438-code

**Comment by danielbachhuber** [comment]
@p-jackson @wojtekn We'll want to solve #64579 before landing this patch.

**Comment by vindl** [comment]
@p-jackson What do you think about reducing this to 5% to start with? (or even lower, ramping up is the easy part 😄 )

**Comment by p-jackson** [comment]
@vindl If we're worried about a dip in blog traffic then a very small rollout will make that difficult to see. But in principle, I'm fine with it. We can ramp up in arbitrarily large jumps so it ultimately doesn't slow down the rollout if we don't want it to.

I'll update the task description to 2%

**Comment by wojtekn** [comment]
I've updated the diff according to the discussion above.

**Comment by vindl** [comment]
> @vindl If we're worried about a dip in blog traffic then a very small rollout will make that difficult to see.

I'm more worried about causing errors for some edge cases that we missed. Once that's cleared, we can ramp up more to monitor traffic.
