### ISSUE TITLE
AMP: Remove the AMP plugin from WordPress.com

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64004]
Placeholder task for now.

As the project (pdKhl6-48-p2) progresses we'll figure out whether we want to remove the AMP code entirely from the WordPress.com repo. This will mean none of our marketing landing pages will be able to use AMP.

**Comment by vindl** [comment]
Following the discussion and decision in pau2Xa-4Cu-p2 we can remove AMP completely. I'm moving this from `Hold` to `Low` priority for now. If/When we pick it up, let's make sure to coordinate the removal with Martech teams.

**Comment by danielbachhuber** [comment]
AMP was removed with pesfPa-yZ-p2
