### ISSUE TITLE
[FSE Themes] - Hamburger menu does not open in Safari

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#64021]
### Quick summary

I have tested several FSE themes on a simple site and the hamburger menu does not open when viewing the site from Safari.

Console log: 

```
[Error] Failed to load resource: the server responded with a status of 400 () (view-modal.min.js.map;, line 0)
```

The issue only seems to impact Simple sites and FSE themes. I was not able to reproduce the issue on an AT site or with other browsers such as Google Chrome. 

https://user-images.githubusercontent.com/21261509/170261562-8bb36c19-0eb2-4e61-bf75-73a72b5a46bc.mp4

So far I have tested on the following themes:

- Archeo
- Twenty Twenty-Two
- Heiwa

### Steps to reproduce

1. Open/create a simple site.
2. Activate an FSE theme: https://wordpress.com/themes/filter/full-site-editing
3. Ensure that you have a menu added and it's displaying on your site.
4. View your site in Safari and resize the browser window so that the hamburger menu shows.
5. Click on the hamburger menu. It will not open. 

### What you expected to happen

The hamburger menu to open and display all my menu items.

### What actually happened

The hamburger menu did not open.

### Context

A slack discussion started here as a user was reporting this issue:

p1653477906379349-slack-C03TY6J1A

User report: 5241884-zd-woothemes

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Seems to impact only FSE themes.

### Browser, operating system and other notes

- Safari
- macOS and iOS

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?
None

### Workaround details

**Comment by simison** [comment]
cc @Automattic/team-calypso-platform recent regression due Guten update?

**Comment by pauljacobson** [comment]
The user mentioned that they are using an iPhone SE running iOS 15.4.1. They also said it works fine for them in Safari for macOS. They shared that they are using Safari 15 on macOS 10.15.7.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I cannot replicate this so I'm checking with the user is they are still having issues.
- I tested this on my iPhone 13 and through Browserstack and I couldn't replicate it.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
