### ISSUE TITLE
Plans overhaul: CTA alignment on localized tables

### ISSUE THREAD

**Issue by paulbonahora** [Automattic/wp-calypso#64020]
CTA's and pricing on the pricing tables should be aligned regardless of the number of description lines of the plans in localizations. [Screenshot](https://d.pr/i/jtNU1s).

**Comment by gmovr** [comment]
Also mentioned here: https://wp.me/pdtkmj-ax/#comment-257

**Comment by claudiucelfilip** [comment]
Changes for the fix are pushed to:
- wp-calypso PR: https://github.com/Automattic/wp-calypso/pull/64071
- WPCOM H4 diff: D81569-code
- H4 legacy diff: D81766-code
- Landpack PR: 1055-landpack
- WPCOM Landpack diff: D81644-code

**Comment by gmovr** [comment]
@claudiucelfilip I approved the H4 diff and Landpack. Once you have the diff with the Landpack code for WPCOM I'm happy to do another review.

**Comment by claudiucelfilip** [comment]
@gmovr Thanks for the reviews!
I pushed the WPCOM Landpack code to this diff: D81644-code

**Comment by gmovr** [comment]
Great! I've tested and approved it. @claudiucelfilip

**Comment by claudiucelfilip** [comment]
I forgot to regenerate the CSS for the legacy H4 pages and the ~~LOHP~~.
Here's the diff to include these changes: D81766-code

There's another batch of changes waiting to be deployed to the LOHP, in D81626-code. We'll come back to this page when it's done.

**Comment by claudiucelfilip** [comment]
Move this back because the [Calyso fix](https://github.com/Automattic/wp-calypso/pull/64071) was causing layout issues on Firefox and needed to [be reverted](https://github.com/Automattic/wp-calypso/pull/64193).

**Comment by claudiucelfilip** [comment]
@gmovr The changes needed to get the fix into the Calypso plan grid may prove to be more complicated and hacky because we're using HTML tables.
Since we already need to rewrite the pricing grid for the new design, I'd suggest we make the fix then.

Aside from this, now we only need to update the LOHP with the fix. I've been holding off from doing this because there's a new Announcement banner pending deployment in D81626-code.

**Comment by gmovr** [comment]
Closing this as we're reverting
