### ISSUE TITLE
Stepper: Processing step content is not centered in the screen

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#64039]
Noticed this on `trunk` as I was working on Anchor stuff:

<img width="1765" alt="Screen Shot 2022-05-25 at 1 50 10 PM" src="https://user-images.githubusercontent.com/2124984/170352880-55a14477-ac65-441b-8afb-a0d1c99a13e8.png">

**Comment by markbiek** [comment]
@sixhours I wasn't able to reproduce this by going directly to http://calypso.localhost:3000/setup/processing?siteSlug=<whatever>.

Do you have any additional steps you can share?

**Comment by sixhours** [comment]
Hrm, I think it might be specific to Anchor! It does appear to be working when I go to the step by itself under the regular flow, but if you add `?anchor_podcast=[your podcast id]` instead of `?siteSlug` it looks broken.

**Comment by sixhours** [comment]
Aha, it looks like at some point a specific selector was added to make sure the processing step content took up 100% width, but only for the `site-setup` flow:

https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/style.scss#L52-L54

 Since Anchor has a different flow and flow container selector, it didn't benefit from the 100% width, so it defaulted to `auto`. Proposed a fix in #64160
