### ISSUE TITLE
Categories / Blog taxonomies issues with WP 6.0 release on Atomic sites

### ISSUE THREAD

**Issue by kerrynicl** [Automattic/wp-calypso#64037]
### Quick summary
SEE [P2](p9F6qB-9s1-p2) for more details and discussions 

I've encountered an instance where:
 
The hierarchy of categories is not sticking,
The selection of categories from within the post, when editing, doesn't stick, after saving the post.

### Steps to reproduce

Try to update a post by adding a category or changing the category in the editor

### What you expected to happen

Post to be updated with the correct category chosen

### What actually happened

Post did not update with newly selected category and reverted to the last option

https://user-images.githubusercontent.com/83325600/170338032-572a04c1-0253-4587-9e11-78a7a2cad561.mp4

 Category had also been removed from the parent category - not respecting hierarchy 

### Context

HC-35455343

### Simple, Atomic or both?

Atomic

### Reproducibility

Intermittent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

See P2-p9F6qB-9s1#comment-47301 

* Access WP-CLI for the site and run the following
  * `--skip-plugins --skip-themes option set finished_splitting_shared_terms 0`
  * `--skip-plugins --skip-themes cron event schedule wp_split_shared_term_batch`
  * `--skip-plugins --skip-themes cron event run wp_split_shared_term_batch` — this will run the event immediately and remove it from the cron event list.
    * If the `cron event run ` command completes the job, it should return something like `Executed the cron event 'wp_split_shared_term_batch' in 0.093s.`
    * The event may also run prior to you being able to use the run command. This will result in an error, `Error: Invalid cron event 'wp_split_shared_term_batch' `. This is normal and you can proceed.
  * Run `--skip-plugins --skip-themes cache flush` after the cron event completes.
  * Check the site. If this is not resolved and you received` Error: Invalid cron event 'wp_split_shared_term_batch' `, try again.

**Comment by JoshuaGoode** [comment]
A fix is now in place that will prevent his issue on new sites from transferring to Atomic.

**Comment by Jaykame** [comment]
Another case here: 35190309-hc and the workaround fixed it.

**Comment by arinoch** [comment]
35654455-hc - Editing posts does not trigger this bug, adding new posts does. Applied the workaround as described above.

**Comment by Jaykame** [comment]
5251334-zd. Applied Workaround.

**Comment by Jaykame** [comment]
5347860-zd applied workaround and it works after that.

**Comment by syds87** [comment]
5372663-zd had the same issue. I've applied the workaround and it works after that!

**Comment by wpshellbelle** [comment]
30091976-hc
Workaround worked for this user.

**Comment by wpshellbelle** [comment]
Another report at 29645852-hc

**Comment by candy02058912** [comment]
I can't reproduce this error in WP 6.5.5.
All WP.com sites should have an updated version of WP core.
As there haven't been any reports for over a year, this issue can be closed.
