### ISSUE TITLE
Free label shows first even for paid themes

### ISSUE THREAD

**Issue by budzanowski** [Automattic/wp-calypso#6403]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/hammer
#### What I expected

`Pick this design` button shows price
#### What happened instead

`Pick this design` button first shows Free label and then price after some time.
#### Screenshot / Video

![free](https://cloud.githubusercontent.com/assets/17271089/16450136/accfe392-3dfb-11e6-8f93-3fea3133bc03.gif)

**Comment by designsimply** [comment]
Tested and confirmed using Chrome 51.0.2704.84 on Mac OS X 10.11.5. @budzanowski, I noticed the word "free" only appears when no other information about the theme has appeared yet on the page, because of that would you agree this issue is low priority?

**Comment by budzanowski** [comment]
Yes, this is low.

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue, even with my network speed slowed down. The first time the button text loads it includes the theme price. Closing optimistically as resolved. :)
