### ISSUE TITLE
Update metrics so that it works with Goals effort

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#64053]
See: p1653494420950989/1653343958.317979-slack-C02TCEHP3HA

**Comment by jimmy319** [comment]
According to Apex's P2 - pdDOJh-qI-p2, `calypso_signup_intent_select` is the only current event affected by the Goals effort changes. This event is fired when users trigger the submit action on the `GoalSetup` and the legacy `IntentSelection` pages. After going through all the metrics of the import flow, we don't track this event in the import flow so there are no further changes we need to make accordingly.

**Comment by vishnugopal** [comment]
I'll take a look at this ticket and make sure that the funnels are working ok! At first glance, the track events are all good!

**Comment by yansern** [comment]
Hi there, despite saying that `import` will be deprecated, in the end `import` is still recorded as an intent. So likely there is no change needed. Everything as is. :)

**Comment by vishnugopal** [comment]
I forgot to close this!
