### ISSUE TITLE
Marketplace: Add top paid / popular categories to the selector

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#64056]
https://github.com/Automattic/wp-calypso/issues/63893#issuecomment-1136664229

Top paid plugins
The sections found in home/discover are treated like any other category when clicking on "browse all". Could we also re-add "Top paid" + other discover groups into the categories list under more which is similar to your original suggestion?

- [ ] Add top paid and popular categories to the list of categories displayed in the selector
- [ ] Add them to the end of the list so they're under "More" by default
- [ ] Show the category bar on all category pages.

**Comment by Rolilink** [comment]
Not so sure about this one, but will like @SaxonF input on this one. I think top/featured plugins sound more like curated lists than categories.

**Comment by lsl** [comment]
See comment above, I think that's the idea, we're making all categories feel like curated lists.
