### ISSUE TITLE
FSE: Allow for viewport sized typography.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#64051]
### What

Allow for variations in text font size dependent on the viewport in use, a la what can be done currently [with CSS](https://css-tricks.com/viewport-sized-typography/).

### Why

Will fill a user need that we can't fill as HEs for users on the Pro, Personal, Starter or Free plans. See 35596747-hc for context.

**Comment by simison** [comment]
Hi! Viewport size dependant typography should be worked on core.

Here are a couple of issues to follow:

https://github.com/WordPress/gutenberg/issues/24480
https://github.com/WordPress/gutenberg/issues/34641
