### ISSUE TITLE
Task: Mobile nav bar improvements

### ISSUE THREAD

**Issue by poligilad-auto** [Automattic/wp-calypso#64064]
### Details

A list of improvements to the new mobile nav bar

### Checklist

- [ ] When viewing a site in "site preview" mode (the frontend of the site) we are still using the old mobile menu, we should change this to the new nav bar. [Image](https://d.pr/i/aW4Nyk) (You can see this when: opening the left nav menu > clicking on the site name > clicking on "visit site")
- [ ] Remove the initial "selected" state from the "W" menu. This makes sense on desktop as the "My sites" left nav menu is open, but on mobile it should be "selected" only when opening the menu. [Image](https://d.pr/i/oyzp0U)
- [ ] I saw yesterday that the new "hamburger" menu was "flickering" when I opened/closed it. I can't reproduce this today.
- [ ] The background color of the the new open "hamburger" menu should be the same background color as the left nav menu (depending on the theme). It's currently not. [Image](https://d.pr/i/ap30aK)
- [ ] When opening the left nav menu > opening the new "hamburger menu": Can we first close the left nav menu and then open the "hamburger" menu? Currently they overlap
- [ ] Can we make the fonts size of the new "hamburger" menu and the spacing between the icons and text the same as the left nav menu? [Image](https://d.pr/i/gaz6hl)

**Comment by escapemanuele** [comment]
No more actual
