### ISSUE TITLE
FSE: Menu option not appearing under the Appearance menu in Dashboard when FSE theme is active with Elementor plugin

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#64068]
### Quick summary

When an FSE theme is active on the site the My Site → Appearance → Menus is no longer being shown.

When using a plugin like Elementor, which is still relying on the WordPress menu, there is no way to manage the menu links on the site. 

The issue happens on a self-hosted site as well, so not sure if it's a core thing or a theme thing.

### Steps to reproduce

1. Activate FSE themes like Blank Canvas, Twenty Twenty-Two (Red), or similar 
2. The My Site → Appearance → Menus is no longer available.
3. Install and activate the Elementor plugin
4. The My Site → Appearance → Menus is still not available to manage the menus.

### What you expected to happen

When we have plugins installed that still rely on Classic menus, we should still have access to the Menus page to manage them.

### What actually happened

The Menu page is hidden.

### Context

Customer report: 5220543-zd-woothemes

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

They can directly access the Menu page (`/wp-admin/nav-menus.ph`) from backend to access it and manage the menus from there.

**Comment by Robertght** [comment]
I'm not sure how to better support our users here, however, would @Automattic/cylon know more about this? Should this be a thing Elementor needs to adjust on their end as it's an issue on self-hosted site as well?

**Comment by Addison-Stavlo** [comment]
I don't think there is much we can do here. By default FSE themes don't support `Appearance -> Menus`.

If a Plugin or Theme wants to surface `Appearance -> Menus` in FSE, it needs to add the code to enable that themselves. Similar to how our 'Blockbase' theme and its children re-add this menu. 

So for this, an update needs to be made on Elementor's end if they want `Appearance -> Menus` to be accessible on FSE themes.

**Comment by Robertght** [comment]
Thank you @Addison-Stavlo ! I'm closing this for now.

As a workaround, we can also encourage the users to activate a non-FSE theme.
