### ISSUE TITLE
Starter Plan: Resharing posts in Calypso says it requires Premium Plan 

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#64098]
### Quick summary

When on the Starter plan and looking to reshare a post - I am prompted to upgrade to the Premium Plan (instead of Pro plan)

### Steps to reproduce

1. Start with a site on the Starter Plan
2. Go to the Post list, click the three dots next to a post and choose the 'share' option

### What you expected to happen

A prompt to upgrade to the Pro plan in order to reshare

### What actually happened

I see a prompt to upgrade to the Premium Plan
<img width="1483" alt="Screen Shot 2022-05-27 at 10 29 19 am" src="https://user-images.githubusercontent.com/1842363/170606382-11e80d9c-2352-447b-95a4-19a923208055.png">

### Context

Product Testing - appears on both Simple and Atomic sites when on the Starter plan

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by inaikem** [comment]
Unable to reproduce. Closing.

**Comment by mriyazuddin** [comment]
I was able to duplicate this on my test site. See this screenshot below for the upgrade prompt I received:

<img width="1439" alt="Markup 2022-06-07 at 14 32 28" src="https://user-images.githubusercontent.com/49064126/172341246-83edf852-9391-4e58-bf0c-cb260fab2013.png">

The only difference between mine and Mo's site is my site was created with Starter plan and Mo's site was upgraded from Free to Starter.

**Comment by inaikem** [comment]
Thanks Riyaz. Makring this as triaged now!

**Comment by marcuswisecaesar** [comment]
Unable to reproduce on my Limited Atomic Test Site, plan progression being: Free - eCommerce - Starter 

![image](https://user-images.githubusercontent.com/36801460/175314906-a8893c1f-bbcd-4b5e-a568-7a8e0ee1f2f8.png)

Unable to reproduce on my Starter Test Site, plan progression being: Free - Starter 

![image](https://user-images.githubusercontent.com/36801460/175314795-ed961a0f-144a-4a4e-8879-d701dceb2853.png)

Therefore, I am closing with this comment.
