### ISSUE TITLE
Limited Atomic: Hosting Features shows notice about needing Pro plan

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#64096]
### Quick summary

When I view the 'Hosting Configuration' page while Atomic on a Starter plan - a notice is shown saying Pro plan is needed, even though the site is Atomic.
<img width="1044" alt="Screen Shot 2022-05-27 at 10 04 28 am" src="https://user-images.githubusercontent.com/1842363/170603394-fc7f157f-2464-4b50-bbc6-4832ddab7585.png">

### Steps to reproduce

With a Limited Atomic site (Atomic on Starter Plan:

* Go to Settings > Hosting Configuration

### What you expected to happen

To be able to access the Hosting Features as I would on any other Atomic Site

### What actually happened

I see a notice saying a Pro Plan is required

### Simple/Atomic

Atomic

### Reproducibility

Consistent

**Comment by jordesign** [comment]
Or, on thinking about it... Maybe I shouldn't have access to this on a lower plan?

**Comment by ghost** [comment]
I think this behavior of prompting for upgrade is likely to happen. I see that my WordPress.com Premium plan site has the same as well.

**Comment by obenland** [comment]
This is working as expected. Hosting Configuration is a feature only available on higher-tier plans.
