### ISSUE TITLE
Reader: delete an existing list

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#641]
A user should be able to delete one of their existing lists.

<img width="1027" alt="c9f1fc7c-7992-11e5-8c82-2be8d6451404" src="https://cloud.githubusercontent.com/assets/17325/10705572/b3efe42e-7993-11e5-8fe9-4df208cdb361.png">

**Comment by alisterscott** [comment]
Lists are unavailable for customers without lists, and existing lists users can't manage these lists any more, so closing this issue as no longer applicable. See `p5PDj3-1Fg-p2`
