### ISSUE TITLE
Limited Atomic: Jetpack Backup operational (instead of requiring upgrade

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#64102]
### Quick summary

When using an Atomic Site on a Starter Plan (Limited Atomic) Jetpack Backups show as available and running.

By comparison, a Simple Site on the starter plan shows a prompt to upgrade.

### Steps to reproduce

On a Limited Atomic site (Atomic with Starter Plan):

* Open Jetpack > Backups in the main menu

### What you expected to happen

To see a prompt to upgrade to Pro (as is shown on Simple Sites on Starter plan)
![Uploading Screen Shot 2022-05-27 at 11.10.44 am.png…]()

### What actually happened

I see Jetpack Backups as active 
<img width="1502" alt="Screen Shot 2022-05-27 at 11 09 50 am" src="https://user-images.githubusercontent.com/1842363/170608834-d4ac36cd-b411-49fb-b3e2-95d13993c484.png">

### Context

Product Testing

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

**Comment by zachspears** [comment]
Hey, @jordesign can you clarify how a site would become Limited Atomic? I am having trouble activating Atomic without adding the Pro plan. Thanks!

**Comment by jordesign** [comment]
Hey Zach - feel free to move this one to Triaged - it will be dealt with directly by the Limited Atomic team

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING

- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Not applicable

📌 SCRUBBING

- Tested on P2 - Not applicable
- Tested on Simple - Not applicable
- Tested on AT - Issue says Limited Atomic but I am not sure how to create such a site
- Tested on Self-hosted - Not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

None.

📌 ACTIONS

- Moving to Triaged column of the board per [this comment](https://github.com/Automattic/wp-calypso/issues/64102#issuecomment-1150588973).

📌 Message to Author

None.

**Comment by JoshuaGoode** [comment]
This appears to be resolved but will test again later. Added limited Atomic label.

**Comment by obenland** [comment]
Yes, this should be fixed.

![Untitled](https://user-images.githubusercontent.com/1398304/176004762-d1c6c1ce-c2b9-4b44-b4f7-2a0d416efde8.jpg)
