### ISSUE TITLE
AMP: Allow error incorrect plugin slug error message to appear

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64104]
The AMP plugin displays an error message in the dashboard when it's installed incorrectly.

<img width="982" alt="Screenshot 2022-05-27 at 3 46 43 PM" src="https://user-images.githubusercontent.com/1500769/170628467-d2bdfa6e-2c3c-47ce-9853-cc563fffff3e.png">

The code is here: https://github.com/ampproject/amp-wp/blob/develop/amp.php#L249

We disabled that error message because the method it's using gives a false positive when symlinks are used. See 222-gh-Automattic/wpcomsh. However, disabling it entirely is too aggressive. A user who is manually managing the AMP plugin should get the error messages.

It's possible to test whether the plugin is managed using `wpcomsh_is_managed_plugin( 'amp/amp.php' )`

**Acceptance Criteria**
- [ ] You _should not_ see the error message if the AMP plugin is managed
- [ ] You _should not_ see the error message after installing the AMP plugin via zip (so that it's unmanaged)
- [ ] You _should_ see the error message if you rename an unmanaged AMP plugin via FTP
- [ ] You _should_ see the error message if you rename a managed AMP plugin via FTP

See project thread: pdKhl6-48-p2

**Comment by vykes-mac** [comment]
Based on the discussion on this [issue](https://github.com/Automattic/wp-calypso/issues/64007) it seems the plugin will remain as managed. @p-jackson does that affect this issue or they are not necessarily related?

**Comment by p-jackson** [comment]
The plugin can be either in a managed or unmanaged state. And that isn't going to change, the decision in pdKhl6-ds-p2 was about whether we still want it to be _possible_ for the plugin to be managed. Which we do. But we can still "unmanage" the plugin by either installing AMP via a zip file, or by using the CLI, which is something link `wp plugin symlink amp` from memory.

So yep we can change the AMP error behaviour based on whether the plugin is managed.

**Comment by zaguiini** [comment]
Using `wpcomsh_is_managed_plugin( 'amp/amp.php' )` still gives me the error message. Here's my draft PR: 967-gh-Automattic/wpcomsh.

I have installed AMP through the plugin dashboard and then renamed the folder to `amp-ok`. When I `ls -n` the plugins directory, I'm getting:

```
149699690@abaliamoier.wpcomstaging.com:/$ ls -n ~/wp-content/plugins
total 8
lrwxrwxrwx 1 149699690 149699690 44 Jan 25 14:43 akismet -> ../../../../wordpress/plugins/akismet/latest
lrwxrwxrwx 1 149699690 149699690 40 May 30 20:45 amp-ok -> ../../../../wordpress/plugins/amp/latest
```

So it should not yield a false positive. Maybe the problem is that we're hardcoding the plugin path to be `amp/amp.php`?  I played around with it, and I came with `ccdb198e8df813eafbf19ca94c8b814501af9db7` (commit on the PR). Let me know if this makes sense.

**Comment by p-jackson** [comment]
But if the user renames a symlinked folder, don't we want the message to appear?

I think this is the behaviour we want in the end. In the case where it's symlinked and named `amp-ok` the `wpcomsh_is_managed_plugin( 'amp/amp.php' )` call will return false which means we won't remove AMP's default error message handling. It'll end up showing the error message. For a weird reason (since we checked whether a non-existent plugin was managed), but it'll still end up with the correct behaviour?

<table>
<tr>
	<td>
	<td><b>Symlinked</b>
	<td><b>Not-symlinked</b>
<tr>
	<td><b>Named <code>amp</code></b>
	<td>No error
	<td>No error
<tr>
	<td><b>Named <code>amp-ok</code></b>
	<td>Show error
	<td>Show error
</table>

Edit: Actually I better add the fourth case to the acceptance criteria

**Comment by zaguiini** [comment]
Yeah but even with the symlinked renamed it still shows “managed by host” on the right. That was the rationale of my proposed changes.

**Comment by p-jackson** [comment]
I think I caused confusion due to my misunderstanding of what "managed" means on Atomic 😅
My rationale was to roll back some of the customisations we make to the AMP experience on Atomic. So the goal was to try and retain the original intention behind the AMP error message: to help users know they've configured the plugin incorrectly.

**Comment by p-jackson** [comment]
In saying that, I guess there's a balance here. I want to make the AMP experience more vanilla, but I also want to reduce the amount of AMP specific code we're supporting. So if making the error messages work in the way I outlined in the table above actually requires a lot more code to be added, then perhaps on balance it's better to stick with the status quo.

**Comment by zaguiini** [comment]
Gotcha 👍 I think that the behavior defined in the PR before the 3rd commit makes sense, then? I'll remove it.
