### ISSUE TITLE
Limited Atomic: Jetpack Dashboard available and showing error about Safe Mode

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#64101]
### Quick summary

When using an Atomic Site on a Starter Plan (Limited Atomic) it is possible to access the Jetpack Dashboard. Additionally the site seems confused between site URLs and loads in 'Safe mode'
<img width="1640" alt="Screen Shot 2022-05-27 at 10 59 15 am" src="https://user-images.githubusercontent.com/1842363/170607691-1faf03d3-af86-43fc-b1b0-6780beb14600.png">

### Steps to reproduce

On a Limited Atomic site (Atomic with Starter Plan):

* go to the main Jetpack menu item on the main menu.

### What you expected to happen

To be redirected to Jetpack Activity feed (as happens on simple sites)

### What actually happened

I was directed to the Jetpack dashboard page - but it appeared to have an error between the *.wordpress.com address and the *.wpcomstaging.com addresses.

### Context

Product Testing

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING

- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Not applicable

📌 SCRUBBING

- Tested on P2 - Not applicable
- Tested on Simple - Not applicable
- Tested on AT - Issue says Limited Atomic but I am not sure how to create such a site
- Tested on Self-hosted - Not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

None.

📌 ACTIONS

- Pinging OP for reproduction steps: @jordesign, could you help me understand how one can create a Limited Atomic site? 
- Similar to [your other comment here](https://github.com/Automattic/wp-calypso/issues/64102#issuecomment-1150588973), I am moving this to triaged column of the board.

📌 Message to Author

- Covered above in "Actions"

**Comment by jordesign** [comment]
@arunsathiya  It was set up to test following these instructions:
pdLHpo-1q-p2

For the purposes of it being worked on - we can consider it triaged though.

**Comment by obenland** [comment]
@jordesign Is there a reliable way to reproduce this?
I tried following the instructions in pdLHpo-1q-p2 to make a new site Atomic via enabling/disabling an eCommerce plan, but that left me with a clean state for Jetpack

**Comment by jordesign** [comment]
@obenland Interesting - I can no longer recreate using the same process either. I just sent an invitation to the site which *does* display that behaviour in case that helps. But if it was just a once-off I guess we can close this.

**Comment by mmtr** [comment]
Looks like this is a duplicated of https://github.com/Automattic/wp-calypso/issues/62207, which apparently has been mitigated according to p9F6qB-90M-p2#comment-46672

**Comment by obenland** [comment]
I did some more research for the specific example of the test blog that prompted this ticket. It looks like sync checks were fired off before the site was fully provisioned, which resulted in the error state . It eventually sorted itself out and syncs started as usual (2cba5-pb) but it looks like the `jetpack_sync_error_idc ` option was then not deleted (p9F6qB-90M-p2#comment-46617). 

@kbrown9 When syncs start to get allowed (2cba6-pb), I wonder if we could check whether we're on a WoA site and then attempt to delete that `jetpack_sync_error_idc ` option remotely?

**Comment by kbrown9** [comment]
Hi @obenland! I'm not working on Sync and IDCs now, so I'm not up-to-date with what's going on there. @fgiannar and @sergeymitr might be better able to answer your question.

**Comment by fgiannar** [comment]
Hi @obenland, thanks for your suggestion!

This is a known issue, which I'm afraid was not resolved by https://href.li/?p9F6qB-90M-p2#comment-46672 unfortunately.

We had been discussing it in [this slack thread](p1648110864091759-slack-CDLH4C1UZ) as well, where we decided that the issue is not Sync related, rather affected by AT domain mapping.

It seems that trying to fix the cause itself might be [rather complicated](p1649939725153989/1648110864.091759-slack-CDLH4C1UZ) so we could start by at least attempting to fix the symptom.

I think that while your suggestion makes lots of sense, it might be actually easier to block the IDC from being generated on WPCOM in the first place.

For now, we can start by adding logging only in order to verify that logged IDCs on **new** AT sites occur while the site is still being provisioned.

I have created a corresponding diff in D83082-code.

I plan to monitor logs after deploying it and report here my findings on whether the solution I have in mind is indeed applicable.

**Comment by marcuswisecaesar** [comment]
Thanks for your work on this! 

I've tested this on my Limited Atomic test Site, plan progression Free → eCommerce → Starter to activate Limited atomic, and though I cannot see Jetpack options, instead I see an empty screen.  

However, I do see notifications to finish setting up eCommerce plugins TaxJar etc.  Is this expected/related behavior? 

![image](https://user-images.githubusercontent.com/36801460/175315741-1d2e7d82-d052-4cfd-afe1-8975c9284259.png)

### Steps to reproduce
1. Upgrade a Free Site to eCommerce (takes the site atomic) then downgrade to Starter

2. You're now on the Limited Atomic site (Atomic with Starter Plan):

3. Go to the main Jetpack menu item on the main menu.

### What you expected to happen
- To be redirected to Jetpack Activity feed (as happens on simple sites)
- Not to see plugin notifications

### What actually happened
- I was directed to the Jetpack dashboard page - but nothing appeared, and plugin settings notifications appeared for plugins installed by default in the eCommerce plan. 

### Context
- Product Testing

### Simple, Atomic or both?
- Atomic

**Comment by fgiannar** [comment]
What I can confirm with confidence is that your site went into IDC while provisioning! 

This is a good thing because it was confirmed via logging and it's exactly what I intend to fix :)

However, I can not say for sure that the empty screen issue will be solved by fixing the IDC issue.

I'll push the fix tomorrow and let you know accordingly to check if the issue you report is still reproducible. Sounds ok?

**Comment by obenland** [comment]
Fantastic, thanks so much for your help on this @fgiannar!

**Comment by fgiannar** [comment]
Fix is deployed :)

@marcuswisecaesar Could you please test the [aforementioned issue](https://github.com/Automattic/wp-calypso/issues/64101#issuecomment-1164439995) and let me know if it's resolved?

I have also updated the corresponding discussion here: p9F6qB-90M-p2#comment-47735, where you can find detailed information on the fix and how to track the AT sites that it has already been applied to.

**Comment by marcuswisecaesar** [comment]
@fgiannar Thanks for your hard work on this! 

I'm testing on the site I used previously Free → eCommerce → Starter, and the plugin notices remain: 

![image](https://user-images.githubusercontent.com/36801460/175558382-d8f86d73-e1bb-4b20-bece-47d43a53150b.png)

On my Free → Starter, plan site the plugin notices do not appear.

![image](https://user-images.githubusercontent.com/36801460/175558992-c0157242-d9b3-41e3-b979-f9a22abc6ae7.png)

**Comment by fgiannar** [comment]
Thanks for testing @marcuswisecaesar !

I believe since the fix affects newly created Atomic sites (while provisioning occurs) we need to test with a site that will be provisioned to AT after the fix was live today.
From what I understand both those sites were provisioned before, right?

**Comment by marcuswisecaesar** [comment]
>From what I understand both those sites were provisioned before, right?

This site - Free → eCommerce → Starter was provisioned following the testing steps here - p7DVsv-eHx-p2

However, I realize that the Free → Starter plan site here:
![image](https://user-images.githubusercontent.com/36801460/175605716-0a54d293-bc92-4b52-b74f-b949bbdd192c.png)

Has not been provisioned Atomic

**Comment by obenland** [comment]
Those plugin banners should be unrelated to Safe Mode, they appear when the plugins get first activated on a site

**Comment by obenland** [comment]
@fgiannar @marcuswisecaesar Have we received any additional reports or can this be closed now?

**Comment by fgiannar** [comment]
@obenland I've asked for additional reporting of IDCs in newly created AT sites here: p9F6qB-90M-p2#comment-47735

So far no such cases have been reported, so I believe we can close this if @marcuswisecaesar also agrees.

**Comment by marcuswisecaesar** [comment]
We can close this, thank you @fgiannar !

**Comment by obenland** [comment]
Great! Thanks so much for all your work on this!
