### ISSUE TITLE
[Bug]: No access to Security settings on limited atomic site

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#64118]
### Quick summary

The My Site → Settings → Security page shows `No security configuration is required. Security management is automatic for WordPress.com sites.` message. 

When using plugins like membership, we’ll need to disable SSO, but that option isn’t available to disable.

### Steps to reproduce

1. While on a limited atomic site, go to My Site → Settings → Security page
2. You won't be able to see any settings. Rather will be shown the message `No security configuration is required. Security management is automatic for WordPress.com sites.`.

### What you expected to happen

We should have access to some security settings like SSO 

### What actually happened

No access to any settings on the page while the site is on the Starter plan.

### Reproducibility

Consistent

**Comment by obenland** [comment]
Did you access that page directly? I could not find a link to it in my menu on a site with a Personal plan.

> When using plugins like membership, we’ll need to disable SSO

Sites on lower-tier plans, which don't have access to Security settings, would also not be able to install/activate plugins. Would you still need access to SSO under those circumstances?

**Comment by obenland** [comment]
@galakhyati Have you had a chance to review my comment from earlier?

**Comment by obenland** [comment]
Closing for now. Please feel free to reopen if expectations around SSO are different from the above.
