### ISSUE TITLE
[Bug]: Unable to access SFTP access on limited atomic site

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#64117]
### Quick summary

Since my site is already atomic, I’m expecting to have SFTP access to my site. It is asking to upgrade to the Pro plan to access the feature.

### Steps to reproduce

1. After going atomic
2. Replace the plan with the Starter plan.
3. When going to My Site → Settings → Hosting Configuration page, it prompts to upgrade to the Pro plan.

### What you expected to happen

I'd be able to access SFTP without being prompted to upgrade since my site is already atomic.

### What actually happened

The site prompted me to upgrade the plan to the Pro plan.

### Reproducibility

Consistent

**Comment by obenland** [comment]
I'd consider that expected behavior. SFTP access is only granted on higher-tier plans, in this case Pro.

/cc @ianstewart in case this should be available to lower-tier plans.
