### ISSUE TITLE
[Bug]: Unable to purchase Premium theme

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#64119]
### Quick summary

Purchasing a Premium theme isn’t supported on limited atomic site

### Steps to reproduce

1. While on a limited atomic site with the Starter plan, go to My Site → Appearance → Themes
2. Go to Premium theme
3. Try purchasing a premium theme
4. The checkout page shows the purchase is not supported.

### What you expected to happen

The site should be able to purchase the theme without facing any issues.

### What actually happened

I wasn't able to purchase a premium theme.
I'm suspecting this could be a Starter plan issue.

### Simple/Atomic

Atomic

### Reproducibility

Consistent

**Comment by obenland** [comment]
Confirmed. I assume there's a cart validator that's removing the purchase from the cart?

**Comment by obenland** [comment]
Reverted in https://github.com/Automattic/wp-calypso/pull/64792
