### ISSUE TITLE
Add-on: Signup flow, implement step on Free sites to sell add-ons

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#64121]
### Details

Design mockup to follow + P2 post. Users choosing to start a Free site should see add-on upsells in a new step in the signup flow.

Originally posted by @gmovr and transferred here

### Checklist

- [ ]
- [ ]

### Related

761-gh-Automattic/martech

**Comment by gmovr** [comment]
@chriskmnds  Mockups shared here pdgrnI-1bS-p2

**Comment by claudiucelfilip** [comment]
WIP changes are pushed to this PR: https://github.com/Automattic/wp-calypso/pull/64451

**Comment by gmovr** [comment]
@paulbonahora @victorespigares  @lucasmendes-design  -- Could we get some design review and content for this screen - ref the PR posted above.

In the above free flow, we're checking for a config flag, gating it from the regular `/free/` signup flow. This should be ready to be deployed soon, so we can test in parallel with the rest of the changes. :) 

cc: @chriskmnds

**Comment by lucasmendes-design** [comment]
> WIP changes are pushed to this PR: https://github.com/Automattic/wp-calypso/pull/64451 

Hi @claudiucelfilip @gmovr, I tried to test it, but the add-on step didn't appear. I followed these instructions: 

Proposed Changes
WIP

Addresses https://github.com/Automattic/wp-calypso/issues/64121

Testing Instructions
Go to /start/plans?flags=signup/addons-step

Select a Free plan

You should see the Addons step

Select a few addons and continue

You should see the addons in your Shopping cart, on the Checkout page

Selecting a Paid plan should not show you the Addons step

**Comment by claudiucelfilip** [comment]
Hey @lucasmendes-design. I'm not sure what happened, probably the `/start/plans?flags=signup/addons-step` flag I mentioned didn't work.
I pushed some recent changes and updated the flag: `/start/plans?flags=signup/add-ons` 
Here's a short screen recording of the current functionality: https://d.pr/v/XbMdUD

**Comment by lucasmendes-design** [comment]
Thanks Claudiu for sharing the recording 👍🏼 I did the same thing you did, I also cleaned the cache and tested in the incognito tab as well without success 😐. 

**Design review:**

- [Change the text alignment inside the card to top algiment](https://d.pr/i/bdcFEs). I believe is center right now.
- I used the [same pattern of Plugin page](https://d.pr/i/8yxt1l): two lines of text, [increase the padding](https://d.pr/i/r8jjtu) inside the card, and [increase the space between cards](https://d.pr/i/F6sEoO), [increase the rounded corner](https://d.pr/i/4xS8EY). 
- I wondering if we decided to show the [full price per year or "X$/month, billed yearly"](https://d.pr/i/OgL0tb)
- The button "Select all add-ons" is [slightly different as well](https://d.pr/i/VeZ92r) maybe if we change the font size and weight ([Intent page](https://d.pr/i4ihvB) and [pricing page](https://d.pr/i/hP5aUI) examples). 
- I would [increase the space between the icon and the title](https://d.pr/i/pc35RI)
- It could be the recording but the [color of the subtitle here is different](https://d.pr/i/kbzxV6) from the original design.

**Comment by chriskmnds** [comment]
> Thanks Claudiu for sharing the recording 👍🏼 I did the same thing you did, I also cleaned the cache and tested in the incognito tab as well without success 😐.
> 
> **Design review:**
> 
> * [Change the text alignment inside the card to top algiment](https://d.pr/i/bdcFEs). I believe is center right now.
> * I used the [same pattern of Plugin page](https://d.pr/i/8yxt1l): two lines of text, [increase the padding](https://d.pr/i/r8jjtu) inside the card, and [increase the space between cards](https://d.pr/i/F6sEoO), [increase the rounded corner](https://d.pr/i/4xS8EY).
> * I wondering if we decided to show the [full price per year or "X$/month, billed yearly"](https://d.pr/i/OgL0tb)
> * The button "Select all add-ons" is [slightly different as well](https://d.pr/i/VeZ92r) maybe if we change the font size and weight ([Intent page](https://d.pr/i4ihvB) and [pricing page](https://d.pr/i/hP5aUI) examples).
> * I would [increase the space between the icon and the title](https://d.pr/i/pc35RI)
> * It could be the recording but the [color of the subtitle here is different](https://d.pr/i/kbzxV6) from the original design.

Addressed most of these points in the [base PR](https://github.com/Automattic/wp-calypso/pull/64289). Let's create issues to see how we'll handle these mainly (the rest can be tuned further easy):

- two lines of text
- I wonder if we decided to show the [full price per year or "X$/month, billed yearly"](https://d.pr/i/OgL0tb)

what it looks like now in admin:

<img width="714" alt="Screenshot 2022-06-24 at 4 12 23 PM" src="https://user-images.githubusercontent.com/1705499/175544006-0117528d-872d-4cfb-ba1c-392bb9b4ad4e.png">

and the view through to mobile:

![Kapture 2022-06-24 at 16 11 03](https://user-images.githubusercontent.com/1705499/175544332-879bc05d-89fd-48e1-a567-3993125fffaa.gif)

@lucasmendes-design @claudiucelfilip

**Comment by claudiucelfilip** [comment]
@chriskmnds Thanks for the updates and improvements!
I integrated the changes with the start flow page and pushed the changes. This is how it works now:


![Image](https://user-images.githubusercontent.com/2749938/175960705-9c919c40-1714-49b0-985c-06b9534c5ac4.gif)

FYI there's a [P2 here](https://wp.me/pdgrnI-1m8) for the rest of the copy needed.

**Comment by lucasmendes-design** [comment]
Just a quick feedback on the title. Here are some links. 

[Figma link](KHxmM5VwfMr8z8RYGslV0H-fi-2826%3A10197) | P2: pdgrnI-1bS-p2#comment-2385
![image](https://user-images.githubusercontent.com/98343583/175965066-0fbc75d4-405d-4bc8-8876-148f5292070a.png)

**Comment by gmovr** [comment]
Deployed with  `"signup/add-ons": false` -- we'll flip this switch once experiment is ready

**Comment by gmovr** [comment]
Ref Experiment: 834-gh-Automattic/martech
