### ISSUE TITLE
Refactor marketplace software installation

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#64128]
### Context

When someone installs a marketplace plugin on a simple site, after checkout it will transfer them to Atomic and file a job (marketplace_post_transfer_manage_software) to install software afterwards. The plugin should be installed and activated automatically.

### Problem

The plugins are then installed by sshing to the site and running a big fat shell command that will first try symlinking the plugin, and if not it will install it. If either work then it will activate the plugin. 

The problem with this approach, is that when it goes wrong, it's hard to debug what exactly has gone wrong. 

### Solution

We should remove the big fat shell command, and instead do something that's more loggable and debuggable.

This could be by running several ssh commands and logging in between, or it could by adding a new wp-cli command to wpcomsh.

**Comment by rcrdortiz** [comment]
We should also take into account Marketplace theme installations.

**Comment by dsas** [comment]
I'm not sure that's strictly relevant to this ticket. Installing plugins on an already atomic site doesn't follow this code path, it's only used for installing plugins as part of the atomic transfer. Installing a premium theme won't take a site atomic.

**Comment by rcrdortiz** [comment]
The Software Installation component should not depend on who/what code path is calling it. At the moment it's only being called from the atomic transfer but isn't limited to it.

**Comment by dsas** [comment]
Now I've looked at it, it looks like I'm wrong anyway - Store_Product_Marketplace_Plugins goes via a different route but does queue the same `marketplace_post_transfer_manage_software` async job.

> The Software Installation component should not depend on who/what code path is calling it

I agree with that in theory, but that assumes the correct model is a single "marketplace software installation component", and I don't know whether I agree with that.

**Comment by rcrdortiz** [comment]
> I agree with that in theory, but that assumes the correct model is a single "marketplace software installation component", and I don't know whether I agree with that.

If the component can't install themes it should be named Marketplace plugin installation instead of software. If I recall correctly, that specific naming was chosen because of it being able to install themes in the future and not just being limited to plugins, at least that was the answer I got when I was reviewing the feature. So the agreement on the model is implicit, at least at a team level.

A single component doesn't necessarily mean having one access point to the domain. We could have an install plugin and install theme methods exposed publicly.

**Comment by dsas** [comment]
All of that might be fine. What this ticket is about though is refactoring the implementation detail of installing plugins. How installing themes is modelled and implemented is somewhat related, but definitely feels like a separate ticket.
