### ISSUE TITLE
Jetpack Open Graph Tags Don't Reflect Featured Image and Excerpt on WooCommerce Shop Page

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#64134]
### Quick summary

Setting a featured image and excerpt on the WooCommerce Shop page does not update the Jetpack Open Graph tags.

- The `og:description` always remains set to "This is where you can browse products in this store."
- The `og:image` always uses the site icon.

<img width="638" alt="CleanShot 2022-05-27 at 14 14 16@2x" src="https://user-images.githubusercontent.com/42279181/170783496-4302af77-5d4a-4a5f-a739-3004b2b7d0fd.png">

### Steps to reproduce

1. Edit the shop page in the editor.
2. Add a featured image.
3. Set an excerpt.

### What you expected to happen

For the featured image and the excerpt text to be used in the Jetpack Open Graph tags.

### What actually happened

The Open Graph tags show the site icon and the static text `"This is where you can browse products in this store."`

The site icon is often small, and doesn't make for a visually acceptable image for social sharing. The description used is also less than desirable for social sharing for most stores.

### Context

We've run up against this on several Team 51 partner sites.

The description text is coming from
https://github.com/woocommerce/woocommerce/blob/efdaf77d806b46aea9655f64958450fc77f3032f/plugins/woocommerce/includes/class-wc-post-types.php#L347

### Workaround Options:
- Install Yoast which is able to correctly set the text and image.
- Hard code the image and description, which makes it difficult to update.

**Comment by JoshuaGoode** [comment]
Duplicate on the Jetpack repo: https://github.com/Automattic/jetpack/issues/18071

**Comment by arunsathiya** [comment]
- Since this is already being tracked on Jetpack, I'll close this issue. https://github.com/Automattic/jetpack/issues/18071
- Feel free to reopen if I missed something.
