### ISSUE TITLE
WooCommerce Subscriptions not showing a valid license in SSR when purchased through WordPress.com Marketplace

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#64132]
### Quick summary

Purchasing WooCommerce Subscriptions through the WordPress.com Marketplace doesn't change the active license information in the site's system status report, which can lead to confusion about updates

### Steps to reproduce

1. Set up a new WordPress.com site on the Pro plan
2. Purchase WooCommerce Subscriptions (this might also apply to other WooCommerce extensions, but I haven't checked)
3. Check the system status report from `WooCommerce > Status > System Status`

### What you expected to happen

Under the Subscriptions panel, I'd be shown as having an Active Product Key

### What actually happened

The site is shown as not having an active product key

![Markup on 2022-05-27 at 15:48:25](https://user-images.githubusercontent.com/4000628/170780281-a5807246-e879-434f-ad8d-f2b225d849e7.png)

### Context

35570520-hc

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

This really is only going to cause confusion if someone checks their system status report or they go to `WooCommerce > Extensions > My Subscriptions` to activate licenses for other extensions, since that will also show that there's no active license for WooCommerce Subscriptions: 

![image](https://user-images.githubusercontent.com/4000628/170781534-84d3e2b6-d534-4f80-9fe9-e0e8a269b777.png)

**Comment by edequalsawesome** [comment]
Fwiw there's a discussion about this here that might be more relevant than my issue, but I'll let y'all decide that 😄 https://github.com/Automattic/wp-calypso/issues/60661

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING

- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

- Did not do anything here.

📌 ACTIONS

- Closing this in favor of the work that's happening at https://github.com/Automattic/wp-calypso/issues/60661

📌 Message to Author

Thanks for that link, @edequalsawesome!
