### ISSUE TITLE
[Bug]: Image in Cover Block not aligning to the right

### ISSUE THREAD

**Issue by flameslash** [Automattic/wp-calypso#64139]
### Quick summary

If I add an image to the cover block and align it to the right, it appears correct on the editor.

<img width="1397" alt="Markup 2022-05-30 at 10 23 12" src="https://user-images.githubusercontent.com/35950523/170910901-d32d1154-0bdd-4409-883b-02df929d4ada.png">

However, if you preview it, it appears on the left side instead

<img width="1348" alt="Markup 2022-05-30 at 10 24 07" src="https://user-images.githubusercontent.com/35950523/170911238-442449ca-607e-46bf-8b03-69ab77d97e1a.png">

### Steps to reproduce

1. Create a cover block select an image and set it to full width.
2. Add an image block inside the cover block
3. Align the image to the right

### What you expected to happen

Preview should show the image block on the right

### What actually happened

The image block appears on the left side of the preview instead

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

### Severity

One

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can still replicate this but I can see it's a longstanding issue here: https://github.com/WordPress/gutenberg/issues/36624

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Seems this issue may be resolved.
- The linked Core issue is also closed, as of last week: https://github.com/WordPress/gutenberg/issues/36624

📌 ACTIONS
- Closing this as well! 🎉
