### ISSUE TITLE
Unclickable Visual editor upon adding 'wpview-body' div class

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#6415]
When the following code snippet is added to the HTML section of the editor:

```
<div class="wpview-body">
...
</div>
```

All the text outside this div becomes unclickable via mouse. Can't select any text or move the cursor using 'mouse'.

WP-Admin Visual editor is not affected.
#### Steps to reproduce
1. Create a new page/post
2. Write any random lines
3. Add the snippet above to 'HTML' tab
4. Switch back to Visual and use mouse pointer to select text
#### Browser / OS version

Tested on Windows:
Firefox 46/47
Chrome 51
#### Screenshot / Video

![Unclickable area](https://cldup.com/Do6o_W8b3j.gif)
#### Context / Source

User got in touch in #409291-chat, able to verify and replicate.

**Comment by lancewillett** [comment]
Thanks for this report — I don't think we should fix it, though; it's too specific to something that'll rarely occur in normal usage. Let's re-open if anyone else reports it (or a similar bug with specific HTML code snippets).

**Comment by juliasydnor** [comment]
Another report of this in a chat on: https://junquillalecoresort.com/rates/

I corrected it by removing <div class="wpview-body"> in the HTML editor, and was able to reproduce it on a test site.

Video in case you need it: https://cloudup.com/ceL0Qm6aAWv

**Comment by thehenrybyrd** [comment]
Another report in 2267025-hc, on bradleyday.net.
I was also able to reproduce on a test site.

The code in question was

<div class="wpview-body">
<div class="wpview-content wpview-type-contact-form">Name<em> (required)</em>
Email<em> (required)</em>
Website
Booking details or comment<em> (required)</em>
Telephone No.<em> (required)</em>
Area or Region<em> (required)</em>
Submit</div>
</div>

I've followed up in 1078696-zd-woothemes to let them know how to fix it.
