### ISSUE TITLE
Woo Email Confirmation - Add interstitial screen behind feature flag

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#64159]
After the Woo onboarding precheck screen and checkout, we need to add an interstitial step behind a feature flag which will be used for a celebration/prompt to confirm email if the user has not yet done so.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/13437011/171033809-a62044b9-19e9-48d1-be25-0864dc2dd403.png">

(For this issue, deliverable is just a step with placeholder content that appears in the flow after site is finalized but before redirect, only if the user has not confirmed their email.) 

See DekZ88lDqG8Je04SyG1ZBK-fi-0%3A1 for the full new intended flow.

**Comment by andres-blanco** [comment]
Which email should be confirmed in this case? The one loaded in the address step or the WP.com user one?
