### ISSUE TITLE
[Bug]: Not possible to purchase recently added marketplace plugins

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#64161]
### Quick summary

It's not possible to view the plugin details page (the one with the buy button) immediately after a marketplace plugin has been added, if you already have visited the marketplace recently, however it is possible to see it in search results.

### Steps to reproduce

1. View the marketplace page
2. Add a new paid marketplace plugin (devs only)
3. View the marketplace page
4. Search the plugin
5. Click on the plugin

### What you expected to happen

The plugin details page (https://wordpress.com/plugins/:plugin-slug/:site) to load and be populated with data about the plugin, including a nice big buy button

### What actually happened

The plugin details page is blank and never changes, there's a request for plugin details to the dotorg api, which doesn't work as the plugin isn't kept there.

### Context

Found while adding a marketplace plugin, see p1653572554097819-slack-C029JEQRVRT

### Other notes

This is caused by checking in the cached productList state for the plugin which doesn’t contain the new plugin yet.

_Perhaps_ [this persist](https://github.com/Automattic/wp-calypso/blob/861d28d49a6aff3dbda1b9a97ca135f19659cf34/client/my-sites/plugins/plugins-browser/index.jsx#L221) is the problem 

### Reproducibility

Consistent

### Available workarounds?

Yes, difficult to implement

### Workaround details

Clear the IndexedDB using browser dev tools, or open a new browser or incognito/private window.

**Comment by cpapazoglou** [comment]
That's probably due to wpcom `products` still cached in Calypso Indexed DB. @WBerredo , @gcsecsey any ideas here?
