### ISSUE TITLE
Woo Email Confirmation - Calypso home should have "verify email address" before "finish store setup"

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#64166]
We need to update the behavior of the user checklist for Sell users so that if they have not confirmed their email, they are prompted to do so before being prompted to "Finish Store Setup".

![CleanShot 2022-05-30 at 12 30 04@2x](https://user-images.githubusercontent.com/13437011/171038684-14fca10a-0a91-4162-a46f-c98896c314bf.png)

See DekZ88lDqG8Je04SyG1ZBK-fi-0%3A1 for full flow information.

**Comment by sixhours** [comment]
We don't need to wait to ship this behind a feature flag, we can ship it ASAP.

**Comment by sixhours** [comment]
This is being worked on in D82158-code

**Comment by sixhours** [comment]
Closed in D82158-code
