### ISSUE TITLE
Anchor: Launch!

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#64169]
Open new setup flow to incoming Anchor users by disabling `is_automattician()` check on the back-end and enabling the feature flag on the front end.

**Comment by sixhours** [comment]
Front-end PR is at #64157 
Back-end diff is at D81728-code

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Anchor Agent  On LIVE SUPPORT [LIVE CHAT ](https://annchorprotocols.org/)

**Comment by sixhours** [comment]
Deployed in #64157 and D81728-code!
