### ISSUE TITLE
Woo Email Confirmation - Update Woo Calypso homepage for non-verified users

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#64165]
If the user reaches Calypso and clicks on WooCommerce, but has not yet verified their account email, we should modify the information displayed to them to prompt them to confirm their email before they progress.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/13437011/171038462-fd87473d-15bf-4a06-89dd-3445689fb00f.png">

See DekZ88lDqG8Je04SyG1ZBK-fi-0%3A1 for full flow information.

**Comment by sixhours** [comment]
"Edit email address" should point to `/me/account` in this case.
