### ISSUE TITLE
Generated design picker: Responsive thumbnails being resized incorrectly

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64178]
## Description

Now that the generated design picker has responsive thumbnails (issue #63588, PR #63952), we have an issue where in some occasions the responsive thumbnails are not resized correctly. See recording: 

https://user-images.githubusercontent.com/797888/171083835-0a1bd5f8-8899-47ce-8379-79c7c961906e.mp4

Steps to reproduce:
1. Scroll down the page (in the recording, I scrolled all the way to the bottom).
2. Resize the browser in any direction.
3. Observe as the responsive thumbnails are resized incorrectly.

## Acceptance Criteria
- [ ] The height of the thumbnails should be resized as defined in the issue #63588.
- [ ] Resizing the browser should not affect the resizing requirement.
- [ ] Thumbnails are not to be responsive on mobile (from @arthur791004)

**Comment by arthur791004** [comment]
The responsive effect should not apply to mobile, I'll fix it too.

**Comment by arthur791004** [comment]
Close it as it's shipped 🚢
