### ISSUE TITLE
[Spike] Generated design picker: Resize iframe without altering the embedded page's layout

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64179]
## Description
In the current implementation, generated design previews are shown embedded in iframes. One of the concerns (see p1653471969945019-slack-CRWCHQGUB) is that the width of the iframe affects how the embedded page preview is rendered. For instance, in smaller resolutions, the iframe shows the preview in what it looks like a tablet view. This creates a discrepancy between the thumbnail and the preview:

![Image](https://user-images.githubusercontent.com/797888/171087232-2509cf8f-a26b-479c-b229-af817df1549c.png)

One possible solution to this issue is to handle iframe resizing using scaling instead of being directly related to the viewport width. This way, the iframe can have a fixed width to render the desktop view, while at the same time responsive to the viewport width. 

Keep in mind that the generated design picker will likely undergo many iterations. For the moment, we're only interested in an estimate of the level of effort it would take to implement this, as a reference for future discussions and decision-making.

cc: @saygunnyc

**Comment by saygunnyc** [comment]
Thank you @taipeicoder! I kind of liked the responsiveness of the iframe **as a designer.** As it allowed me to play around with the browser width to see how it would behave on different resolutions.

On the other hand, I understand this creates a bit of discrepancy between the thumbnail and the preview. If we are to go down the route of scaling the image down as @iamtakashi I believe suggested, then I am for adding a preview link next to the continue CTA so it takes the user into the Preview page where there are controls to switch between mobile, tablet and desktop. Sharing the design below.

<img width="1456" alt="Preview CTA" src="https://user-images.githubusercontent.com/78876323/171437385-a794a439-ce1c-41df-9e33-6051f4e56d8a.png">



We can move forward with either one and then track, decide on a fallback or re-iterate. 


_______

Also not related to this PR but let's change the body copy of the step here to be "Based on your input, these designs have been tailored for you. You can always change later." cc @autumnfjeld

**Comment by miksansegundo** [comment]
After a few tries, we have found a solution that works for scaling the iframe down to keep consistent the thumbnail and the preview.

We have also added a `Preview` link on the header and the footer next to the continue CTA. I'm still figuring out [how to show the controls](https://github.com/Automattic/wp-calypso/pull/64316/files#r888610973) to switch between mobile, tablet and desktop. 

The [code](https://github.com/Automattic/wp-calypso/pull/64316) is now ready for code review and we could be merging it in the following days for testing.

**Comment by taipeicoder** [comment]
> Thank you @taipeicoder! I kind of liked the responsiveness of the iframe **as a designer.** As it allowed me to play around with the browser width to see how it would behave on different resolutions.
> 
> On the other hand, I understand this creates a bit of discrepancy between the thumbnail and the preview. If we are to go down the route of scaling the image down as @iamtakashi I believe suggested, then I am for adding a preview link next to the continue CTA so it takes the user into the Preview page where there are controls to switch between mobile, tablet and desktop. Sharing the design below.
> 
> <img alt="Preview CTA" width="1456" src="https://user-images.githubusercontent.com/78876323/171437385-a794a439-ce1c-41df-9e33-6051f4e56d8a.png">
> 
> We can move forward with either one and then track, decide on a fallback or re-iterate.
> 
> Also not related to this PR but let's change the body copy of the step here to be "Based on your input, these designs have been tailored for you. You can always change later." cc @autumnfjeld

Thanks for the feedback @saygunnyc! With the Preview page you mean the way current traditional design picker implements previewing? See screenshot below to see what I'm referring to:
![Screen Shot 2022-06-06 at 9 51 39 AM](https://user-images.githubusercontent.com/797888/172081661-d0b1b885-c5a3-4271-886e-ba6eb3b5f514.png)

**Comment by taipeicoder** [comment]
Closing as it's shipped 🚢

**Comment by saygunnyc** [comment]
> Thanks for the feedback @saygunnyc! With the Preview page you mean the way current traditional design picker implements previewing? See screenshot below to see what I'm referring to

Yes, although this would work much better once we switch to a new window and full-screen preview. Sharing @SaxonF 's current/latest design below. Not sure about the latest on device previews there though.

<img width="955" alt="Screen Shot 2022-06-15 at 5 04 37 PM" src="https://user-images.githubusercontent.com/78876323/173929727-c1079716-6d5b-4257-b525-e0eb4537ed2d.png">
