### ISSUE TITLE
Generated design picker: Switching back to the generated design picker briefly reveals the sticky footer

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64188]
## Description
In the current implementation, customers can switch to the traditional design picker by clicking the "View more options" button. Meanwhile, in the traditional design picker, customers can switch back to the generated design picker by clicking the "Back" button in the top navigation bar.

As seen from the recording below, when customers switch from the traditional design picker to the generated design picker, the sticky footer shows up briefly only to disappear again. Note that this doesn't happen when entering the generated design picker page from the intent screen.

https://user-images.githubusercontent.com/797888/171142298-df60eab8-fa0a-45fc-89f1-f305185f4be4.mp4

## Acceptance criteria
- [x] As customers switch back to the generated design picker, the sticky footer should not show up at all.

**Comment by arthur791004** [comment]
Close as it's shipped 🚢
