### ISSUE TITLE
Fix same origin x-frame-options for previews during import

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#64182]
![Image](https://user-images.githubusercontent.com/533/172751556-c564703a-1a86-46d7-a31c-a9e749808702.png)

![Image](https://user-images.githubusercontent.com/533/171094484-eeac8fd5-79a6-4291-8cf6-b6aad3f59051.png)

(for make.wordpress.org from the Full Import flow)

**Comment by vishnugopal** [comment]
We may need to revert back to the old mShots-based implementation here as there's no way to work around browser security.

Just FYI, using iframes for external website previews may be a bad idea in the future. cc @simison

**Comment by simison** [comment]
Honestly mshots is way too slow for this, so it might make sense to chance the design then.

**Comment by vishnugopal** [comment]
^ cc @saygunnyc 

I'll revert to mShots for now because a broken preview is worse than a slow one imo.

**Comment by saygunnyc** [comment]
Yes, let's 💯 plan on re-visiting this design. I also am not fully convinced if the preview is adding value other than confirming it's the right site address.

**Comment by ouikhuan** [comment]
We’ve reverted to the mShots implementation so closing this issue.
