### ISSUE TITLE
[Bug]: "Included with your purchase" section in checkout is empty for certain products

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#64203]
### Quick summary

@claudiucelfilip noticed this bug for the upcoming No Ads product, but it occurs for some existing products too:  The "Included with your purchase" section in checkout is completely empty.

### Steps to reproduce

Easiest to reproduce with Search since it's already for sale:

1. Go to https://cloud.jetpack.com/pricing
2. Choose the Site Search product
3. Select an existing site (can be a WordPress.com site or a Jetpack site)
4. Look for the empty section in checkout

### What you expected to happen

Either the section to not appear at all (if there's nothing in it), or otherwise some basic text to be displayed.

Perhaps for many products, we can add similar text to what we do for domains (basically, one bullet point about the product, and one about the refund window), but then also make it disappear automatically for any products where we didn't do that.

Domains:

![domains](https://user-images.githubusercontent.com/235183/171232372-680571ce-cd6f-448c-afc5-01706794659f.png)

### What actually happened

The section is empty:

![Screenshot from 2022-05-31 12-57-27](https://user-images.githubusercontent.com/235183/171232389-89e9595e-11ff-42d4-8f3d-812eac25edae.png)

### Reproducibility

Consistent

**Comment by michaeldcain** [comment]
From the planning call, we need to:

- Short term: hide it if it's empty
- Long term: audit the products to find which ones don't have Checkout features, settle on features worth promoting, and update the feature list

**Comment by DavidRothstein** [comment]
This is mostly but not entirely addressed by https://github.com/Automattic/wp-calypso/pull/64328.  The things it doesn't do:
- Doesn't actually guarantee that the "Included with your purchase" section will never be empty, but almost does.  Two cases where it's still empty, for example, are signing up for a free trial of Professional Email (when you already have a domain), and paying for a chargeback fee when nothing else is in your cart.  So to go further (especially for the latter case, where there's really nothing to say about the purchase) it would need to also force that section to be completely hidden if empty.
- Doesn't touch the long term task mentioned above of "settle on features worth promoting, and update the feature list".

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
Tested on Atomic - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Adding Jetpack Search to my cart shows a nice list of features now

![Markup on 2023-05-17 at 14:20:44](https://github.com/Automattic/wp-calypso/assets/27249804/9216431c-db55-41bb-bf55-be757326ec8c)

📌 ACTIONS
- Leaving open per the previous comment, but low priority as this seems mostly resolved

**Comment by michaeldcain** [comment]
Confirmed that the email free-trial now shows the default customer service/refund messaging, and fixed the Chargeback cart in #87229. Closing.

<img width="1105" alt="Screenshot 2024-02-06 at 9 30 40 AM" src="https://github.com/Automattic/wp-calypso/assets/942359/c7cbc206-0cce-428e-ac0f-82d0e8c7a549">
