### ISSUE TITLE
Woo Onboarding: Do we need the email address field?

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#64202]
On the address step of the Woo flow, we ask for an email address:

<img width="1135" alt="Screen Shot 2022-05-31 at 12 20 29 PM" src="https://user-images.githubusercontent.com/2124984/171223643-2658285f-d8c2-455a-8caa-f7fe9ce7fcad.png">

* At this point in the flow, shouldn't we already have the user's email address? Don't they have to be signed in to see this screen?
* What purpose does this field serve for Woo onboarding itself?
* Can/should we auto-populate this field with existing user data?
* Or can we remove it entirely?

We should do a quick spike to answer these questions. This may involve checking in with Woo folks.

**Comment by andres-blanco** [comment]
I think that this email corresponds to the store, not the user. [This is the PR](https://github.com/Automattic/wp-calypso/pull/59970) that added this field in the previous onboarding implementation.

I will ping someone from WC to verify this.

**Comment by andres-blanco** [comment]
@pmcpinto Can you give us a little more info on what's the purpose of this email field? I think that it's the store email and if that is the case the label should read something like `Store email address` to prevent confusion with the user email address.

**Comment by pmcpinto** [comment]
Sure. This email field is used for marketing purposes. So that our Marketing team can send emails to Woo users about our marketplace, useful extensions, etc. 
In this case, I'm not sure if it makes sense to keep it because I'm assuming that Dotcom is targeting users with similar emails. @Timstreep what do you think?

**Comment by Timstreep** [comment]
@pmcpinto I don't think we're collecting email addresses from the Dotcom flow. Can you confirm if that is the case?

**Comment by pmcpinto** [comment]
@Timstreep AFAIK we're collecting emails even if the users are Dotcom customers:

![image 114](https://user-images.githubusercontent.com/3380168/171915782-685ff0eb-0fff-4550-984d-24055a432561.png)

The Dotcom team is replacing this part of the Woo flow and we're assessing whether it makes sense to keep the email address field.

**Comment by Timstreep** [comment]
Thanks for the explanation @pmcpinto. It makes sense to keep it in place. We have Woo-specific education about onboarding etc. that we want users to be a part of. This is also a way for us to communicate other updates (like core plugin updates and other helpful info).

**Comment by andres-blanco** [comment]
> 

Do you think it would be correct to rename this email field to something like `Store email`, at least in the WP.com onboarding flow? 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/375980/172168103-4653ec78-7e94-4ac9-ba55-c83d8fb0a3ec.png">

When coming to Woo from WordPress.com it's a little confusing because you have an email linked to your account, and if you are a new user you've just gone through the WP.com signup process.

If we can't rename, is there some already done text that describes the purpose for this field?

**Comment by pmcpinto** [comment]
> When coming to Woo from WordPress.com it's a little confusing because you have an email linked to your account, and if you are a new user you've just gone through the WP.com signup process.

I agree that it can be confusing. 

Perhaps something similar to what we have in the Woo profiler can work well:

<img width="529" alt="Captura de ecrã 2022-06-07, às 10 54 28" src="https://user-images.githubusercontent.com/3380168/172352147-0692286d-3fe2-4e64-a0b3-53b6456068b1.png">

The copy can be tweaked to "Get Commerce tips, product updates and inspiration straight to your mailbox." and the Mailchimp mention can be removed (this was a .org requirement to be included in the plugin).

cc @Timstreep

**Comment by Timstreep** [comment]
Agreed @pmcpinto - the additional context would be helpful. I would also mention WooCommerce specifically. e.g.

'Get tips, product updates, and inspiration from WooCommerce straight to your inbox.'

We can leave out the 'Powered by Mailchimp'.

**Comment by sixhours** [comment]
It sounds like the answer to the original question is "yes, we need to keep the email field." Good to know! We might want to consider changing the field title to be more specific ("Store email"?) but if not, I think we can close this.

I would hold off on adding more steps/fields to this flow for now. /cc @ianstewart let us know what you think about adding the above checkbox to the WooCommerce onboarding flow in a future sprint.

**Comment by markbiek** [comment]
Noting some ideas we kicked around here during our sprint demo:

@andres-blanco suggests updating the label to make it clear that this is the _payment_ email and not related to the WordPress.com account email.

@blackjackkent also had the idea of having a button that says "Use my WordPress.com email". Clicking the button would pre-fill the email address box with the user's current email.

----

@Timstreep @pmcpinto Does the above sound like a reasonable approach?

**Comment by pmcpinto** [comment]
Sorry, I missed this ping last week as I was AFK:

> @andres-blanco suggests updating the label to make it clear that this is the payment email and not related to the WordPress.com account email.

I think that calling this payment email can be confusing as we'll only use it for email marketing. What about something more descriptive like "Get Commerce tips straight to your inbox."

> @blackjackkent also had the idea of having a button that says "Use my WordPress.com email". Clicking the button would pre-fill the email address box with the user's current email.

That can work. An alternative can be prefilling the input with the user's current email and marking the field as optional.

**Comment by blackjackkent** [comment]
I think combining these ideas might be best. A label that says the "get tips sent to your inbox" thing, followed by clickable text "Use your WordPress.com email." This efficiently communicates to the user that the two emails are not equivalent.

**Comment by markbiek** [comment]
@pmcpinto @blackjackkent  Here's a _rough_ pass at what this could look like. Do you have any suggestions?

<img width="646" alt="image" src="https://user-images.githubusercontent.com/917632/176001877-243ad5c1-97ab-40f6-8a91-1e2d19dcdfcb.png">

**Comment by pmcpinto** [comment]
Looks good to me. Thanks for sharing the screenshot
