### ISSUE TITLE
Make sure all signup URLs point to the new plans features signup flow

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#6420]
In #6376 I added a new signup flow called `plans-features` which uses the `plansFeatures` step instead of the `plans` one (plans redesign).

Now, at all the places where you can sign up, the signup URL is loaded from a config file with `config( 'signup_url' )`. However, this URL points to the current signup flow with `plans` step. If plan features are enabled, we need to switch this URL to the new one I created: `/start/plans-features`.

What's the best way to do that? Add a new config entry to each config file called `plan-features_signup_url` and use this if `manage/plan-features` are enabled? Or hard-code it into all the places where `signup_url` is used if `manage/plan-features` are enabled?

This touches #6376 as well as #6303 and other places where users can sign up we have not yet talked about (e.g.: logged-out users on Calypso landing page, in masterbar, etc).

cc @gwwar

**Comment by gwwar** [comment]
Let me check in with nux, but I would imagine that we wouldn't want to touch existing routes, and probably switch this on the component level in the plans step.

**Comment by gwwar** [comment]
Looking at the code further @lamosty I think we'll want to flag on the existing plans step. We have a number of flows that use the plans step, and this will ensure that we see the correct behavior on any other flows.

**Comment by lamosty** [comment]
Closing this as I've refactored the `plansFeatures` step into the `plans` step as per @gwwar suggestion.
