### ISSUE TITLE
Launch: "Back to My Sites" link incorrect when coming from "Settings -> General"

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#64211]
### Quick summary

When a user clicks "Launch site" from "General -> Settings", the "Back to My Sites" link on the next screen incorrectly links to `https://wordpress.com/sites/`. It should link to `https://wordpress.com/settings/general/<domain>` and say "Back to My Settings".

### Steps to reproduce

1. Create a new Simple site.
2. Navigate to "General -> Settings".
3. Click on the "Launch site" button.

  <img width="793" alt="image" src="https://user-images.githubusercontent.com/36432/171287985-deab2081-b36e-442c-a69d-1b8fe4089f2d.png">

4. Observe that the "Back to My Sites" button links to `https://wordpress.com/sites/`:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/36432/171288090-d0026efe-df24-43f2-9298-4d14207dc533.png">
<img width="287" alt="image" src="https://user-images.githubusercontent.com/36432/171288130-c2b436f4-7e1c-4be2-9c02-407d90e2e681.png">

### What you expected to happen

I expected the "Back to My Sites" link to go to "Settings -> General" (i.e. where I was previously).

### What actually happened

The "Back to My Sites" button links to `https://wordpress.com/sites/`.

### Simple, Atomic or both?

Simple

**Comment by p-jackson** [comment]
There are a number of ways into the launch flow. The original bug fix addressed the issue where the user entered the launch flow from the General Settings page in Calypso, but #64922 now also includes fixes for the cases where the user enters the launch flow from checklist on My Home, and the launch banner on the front end.

- [x] #64292 
- [x] Launch banner on simple sites passes `source=site` query param to the launch flow D82017-code
- [x] Launch banner in `wpcomsh` passes `source=site` query param to the launch flow 979-gh-Automattic/wpcomsh

**Comment by danielbachhuber** [comment]
@p-jackson Created the `wpcomsh` pull request: 979-gh-Automattic/wpcomsh

_However_, I wasn't able to genuinely recreate the scenario where the banner actually displays on my WOA site.

By commenting some code, I was able to get the banner to render in the DOM, although it doesn't actually display:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/36432/171883274-8656a296-b997-4ffc-93d7-30ea8630ac07.png">

Are we sure the banner actually displays on Atomic sites? Or could it simply be dead code?

**Comment by vykes-mac** [comment]
@danielbachhuber I encountered similar issue when looking at this. When the page is first loaded click anywhere on the masterbar and the option with launch site should slide down. It seems its not visible by default.

**Comment by p-jackson** [comment]
> Are we sure the banner actually displays on Atomic sites?

It's definitely supposed to appear on Atomic. You might need to create a new un-launched WoA site from scratch though because I don't think all the relevant settings are stored as site options the same way they are on simple sites.

>  When the page is first loaded click anywhere on the masterbar and the option with launch site should slide down.

Is this just an issue with the initial scroll position? @andres-blanco I think I remember we had an issue with the scroll position of the launch banner at some point. Was that issue fixed on Atomic as well as Simple?

**Comment by andres-blanco** [comment]
> Is this just an issue with the initial scroll position? @andres-blanco I think I remember we had an issue with the scroll position of the launch banner at some point. Was that issue fixed on Atomic as well as Simple?

The issue on Simple seems to have been fixed by D71444-code. The line of code removed is still on wpcomsh at `private-site/logged-in-banner.php#L153`.
It looks like it was fixed on Simple but not on Atomic.

**Comment by p-jackson** [comment]
Thanks @andres-blanco! I _thought_ I remembered that issue from the blogger pod work :)

I've created a new issue (#64426) on the Build team's board, which is basically just to roll out the D71444-code fix for Atomic sites too. The Build team has the capacity at the moment to fix it, but if Serenity would prefer to that's fine too. CC @blackjackkent

**Comment by andres-blanco** [comment]
The fix is relatively easy, the difficulty is testing and verifying that we don't break more than we fix. 

CC @sixhours since Ros is AFK.

**Comment by sixhours** [comment]
@p-jackson If y'all have the capacity I say go for it! 👍

**Comment by danielbachhuber** [comment]
> * Launch banner in `wpcomsh` passes `source=site` query param to the launch flow 979-gh-Automattic/wpcomsh

This is now shipped with wpcomsh v2.9.23
