### ISSUE TITLE
Enable signup + v13n onboarding testing

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#64226]
# Description

We are ready to put our feature on horizon for full signup + v13n testing.
See info on horizon: PCYsg-5bh-p2
Note: we won't do a CfT on horizon P2, because we're already doing a feature CfT.  I jsut wanted to provide the link so it is clear that horizon is meant for public testing.

# Dev Tasks
ToDo: please flesh out tech details
- [x] enable the v13n flag(s) in horizon

# Follow up
Once the whole flow can be tested on horizon we will need to have testing within Ganon of course, but possible with an HE or two. We can decide how to do this, perhaps just ping a few people and have them add comments to this git issue or another git issue.

**Comment by taipeicoder** [comment]
Closing, and will be reporting new issues independently.
