### ISSUE TITLE
Jetpack Plugins page fails to load on Chrome v44 and below

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#6422]
#### Steps to reproduce
1. Load URL for a Jetpack site: https://wordpress.com/plugins/example.jetpacksite.com

#### What I expected
A list of installed plugins, which is what I see on Chrome v45 and up

#### What happened instead
A pulsing list of placeholders and the following error in the JS console:

```
Uncaught TypeError: config(...).find is not a function
plugins.e524d43eb45d4219cd6c.min.js:4 Uncaught TypeError: config(...).find is not a functiongetWporgLocaleCode @ plugins.e524d43eb45d4219cd6c.min.js:4fetchPluginInformation @ plugins.e524d43eb45d4219cd6c.min.js:4(anonymous function) @ plugins.e524d43eb45d4219cd6c.min.js:4(anonymous function) @ build-production.6961e55e1583221eb0c6.min.js:74store.dispatch @ build-production.6961e55e1583221eb0c6.min.js:49(anonymous function) @ build-production.6961e55e1583221eb0c6.min.js:74(anonymous function) @ plugins.e524d43eb45d4219cd6c.min.js:8addWporgDataToPlugins @ plugins.e524d43eb45d4219cd6c.min.js:8getPluginsFromStore @ plugins.e524d43eb45d4219cd6c.min.js:8getPluginsState @ plugins.e524d43eb45d4219cd6c.min.js:8refreshPlugins @ plugins.e524d43eb45d4219cd6c.min.js:8EventEmitter.emit @ build-production.6961e55e1583221eb0c6.min.js:14SitesList.sync @ build-production.6961e55e1583221eb0c6.min.js:49(anonymous function) @ build-production.6961e55e1583221eb0c6.min.js:49(anonymous function) @ vendor.6961e55e1583221eb0c6.min.js:4onload @ build-production.6961e55e1583221eb0c6.min.js:34resolve @ build-production.6961e55e1583221eb0c6.min.js:35onmessage @ build-production.6961e55e1583221eb0c6.min.js:35
```

#### Browser / OS version
Seen in Windows and Linux with Chrome v44 and v43

#### Screenshot / Video

![screen shot 2016-06-29 at 1 36 40 pm](https://cloud.githubusercontent.com/assets/7233112/16462286/8c8d2740-3dfe-11e6-81c3-8cb4cd1cef01.png)

#### Context / Source
#automated-testing  -- Since June 14th our CI system has been running a new version of Chrome, which doesn't have this problem.  Today I had to switch back to v43 in order to solve a different issue, and this problem popped up.  So it could've been broken at any point since then.

**Comment by gwwar** [comment]
Find is not polyfilled, so this will break on Chrome < 45, FF< 25 and IE  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find
