### ISSUE TITLE
Theme Showcase: 'Premium' filter not active when linking directly to Premium Themes list

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#64222]
### Quick summary

When linking directly to the list of premium themes (https://WordPress.com/themes/premium/) the filter for Premium themes does not appear to be active.

### Steps to reproduce

1. Visit https://WordPress.com/themes/premium/
2. Check the filters at top right of the showcase

### What you expected to happen

For the 'Premium' filter to be displayed as active (as it is when clicking on the filter)

### What actually happened

The filter button remains inactive.

<img width="1663" alt="Screen Shot 2022-06-01 at 9 52 03 am" src="https://user-images.githubusercontent.com/1842363/171326240-ed971439-9a4d-42c4-a089-243492480ecf.png">

### Context

Testing a different PR 

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context: I can confirm this happens, however, I'm adding the screenshot here
![image](https://user-images.githubusercontent.com/6737345/172047595-f28d2634-dfbf-42c7-9bcf-db7981515f45.png)



📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Robertght** [comment]
cc @Automattic/serenity

**Comment by jordesign** [comment]
Noting this is also the case for the 'Free' Filter. Therefore...

/themes/premium/{SITE_URL} or /themes/free/{SITE_URL}

**Comment by blackjackkent** [comment]
Pulled this into Serenity's board - we'll look into it next sprint. :)
