### ISSUE TITLE
Theme: Blank Canvas + Meraki - When homepage is set to 'password protected', page remains publicly accessible.

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#64228]
### Quick summary

With this theme, any page with a password set shows the password prompt as expected.

However, when a password-protected page is set as a static front page, the page content is visible without the need to enter a password.

This is not the case on other themes I have tested (Appleton, TT2)

### Steps to reproduce

1. Create and publish a page.
2. Set as PAssword protected.
3. View page, confirm password protection is active.
4. Set the page as your static homepage.
5. the page is not publicly accessible

### What you expected to happen

I expected the page to continue respecting the visibility settings I saved.

### What actually happened

The page no longer respected the visibility settings I saved.

### Context

Interaction: 5256783-zen
Internal discussion: p1654068486613169-slack-C03TY6J1A

The user's site is using Blank Canvas

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Blank Canvas, Meraki

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
I'm unable to replicate this right now, when using Blank Canvas, Blockbase or a a child theme of either themes.

Marking this as "Needs Author Reply" for now.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Closing as we cannot replicate the issue anymore.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
