### ISSUE TITLE
Classic form inside classic block not submitting

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#64236]
### Quick summary

When trying to submit a classic form entry the message appears that you still need to fill in a field.

Example -
![Uploading Markup on 2022-06-01 at 11:55:26.png…]()
 

### Steps to reproduce

1. Add the following code to a page. 

<img class="wp-image-15 aligncenter" src="" alt="Logo - " width="453" height="194">
[contact-form to='help@wordpress.com' subject='Enquiries'][contact-field label='Name' type='name' required='1'/][contact-field label='Email' type='email' required='1'/][contact-field label='Enquiry type' type='checkbox-multiple' required='1' options='Animal Encounters,Reptile Consultancy,TV,Media Work,Other (please state in your message)'/][contact-field label='Comment' type='textarea' required='1'/][/contact-form]

2. Try to submit the form
3. It shows an error. 
4. Looking at browser console it says 
"window.rltInjectToken @ rlt-proxy.js:13
​ Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://public-api.wordpress.com') does not match the recipient window's origin ('https://widgets.wp.com')."

### What you expected to happen

The form to submit

### What actually happened

The error mentioned above appears

### Context

5261247-zd

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Tried on two different themes. Results is consistent.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Use a form block instead of the old style form shortcodes.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I believe this is related to this: https://github.com/Automattic/jetpack/issues/24625#issuecomment-1147129112
I was not able to replicate it so I'm closing it for now.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
