### ISSUE TITLE
Anchor: Create separate step for design selection

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#64247]
### What

The design selection step has evolved considerably since we first moved Anchor to the Stepper framework. It probably makes sense to give Anchor its own theme selection step rather than leveraging the additional logic in `design-setup`.

### Why

The Anchor flow only shows three themes and therefore doesn't require as complex an interface as we currently have for design selection in the other flows, and Stepper makes it quite simple to create new steps for individual flows.

**Comment by sixhours** [comment]
This will be closed by #64653

**Comment by blackjackkent** [comment]
Closing, since #64653 has been merged.
