### ISSUE TITLE
Site Launch: Plan selection screen does not always appear.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#64248]
### Quick summary

In some cases, the Plan selection screen does not appear when launching a site.

### Steps to reproduce

Steps are taken from the `SIgnup: Free` spec in CI but the exact conditions are unknown.

1. sign up for an account from `/start` and go through the flow.
2. once in the `/home` dashboard, navigate to Settings on the sidebar.
3. scroll down and locate the Launch button.
4. when prompted to purchase a domain, scroll down and decline.

### What you expected to happen

The Plan selection screen should be shown at this time.

### What actually happened

The Plans selection screen is skipped entirely.

https://user-images.githubusercontent.com/6549265/171458942-d31caef6-c58e-46bc-86c5-1b7cecb62bc6.mp4

### Context

Manual & Automated testing.

p1654033059549799-slack-C031TFM2NKC

### Simple/Atomic

Simple

### Other notes

Factors that I tested locally on my machine to eliminate:
- user agent (e2e tests use `wp-e2e-tests`
- blog name (there is special filtering for sites that start with `e2eflowtesting`)
- proxy (on/off makes no difference)
- endpoint (wpcalypso/staging makes no difference)
- browser (edge/firefox/chrome makes no difference)
- third-party cookies (on/off makes no difference)

### Reproducibility

Intermittent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Launched a Free Plan site via Site > Settings, declined to purchase a domain, and was taken to `https://wordpress.com/start/launch-site/plans-launch?siteSlug=SITE_ADDRESS` next
- Between the work on the Launchpad and the updates to domain availability on free sites, seems this is resolved

📌 ACTIONS
- Closing as resolved
