### ISSUE TITLE
Adding additional fonts for dyslexia/accessibility

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/wp-calypso#64240]
### What

I had a request today for adding additional fonts on the Free Plan for dyslexia/accessibility. Going through the list here: https://accessibe.com/blog/knowledgebase/dyslexia-fonts-helping-the-web-read-better it looks like we only have one that is available from that list (Open Sans).

### Why

It adds options for making websites more accessible on the Free Plan (since plugins are not available to add additional fonts).

**Comment by supernovia** [comment]
👋  Hi! @gwensmithx!  We currently support Google Fonts, but just a curated set of them, so I've been checking to see if there are any others that could be added to the collection. Open Sans was the only one on the list that's there that I could see so far.

The article suggests sans-serif is good. Google Fonts has several of those, though I'm not sure which ones would be best for this need:
https://fonts.google.com/?category=Sans+Serif&preview.text=Easier%20to%20read&preview.text_type=custom

Would any of those work well, or are we looking more to add the fonts mentioned in the article?

If we can add a few specific fonts to this issue, especially if they are Google Fonts, that would help.

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Closing report due to stale conversation. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
