### ISSUE TITLE
Tutorials: Create endpoint in ETK

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#64252]
### Details

Requires #64251

The Help Center's "Next Steps" project requires 3 Tutorials (formerly checklists) each of which:

1. contains 1 or more **tasks**
2. each **task** may have 1 or more **steps** associated with it (this will be defined client-side, rendered through `TourKit`, and is not a part of the endpoint proper)
3. Each Tutorial **task** can be marked with the following statuses: `complete`, `skipped`. An uncompleted task will have no stored status. A completed task marked incomplete will remove its status.

The existing checklist API does not support multiple lists, nor Atomic, so we will not use it, other than as a source of lessons to learn.

Although our direction has evolved from it already quite substantially, there is more context in the investigatory Spike: paYE8P-1Dc-p2

API endpoint pseudo-structure:

```
// GET /wpcom/v2/tutorials
-> { /* List of available Tutorial IDs */ }

// GET /wpcom/v2/tutorials/TUTORIAL_ID
-> {
 id: TUTORIAL_ID,
 tasks: [/* Tutorial tasks with completion state */ ]
}

// Tutorial task:
{
 id: "blogname_set",
 status: 'complete|skipped|pending',
}

// POST /wpcom/v2/tutorials/TUTORIAL_ID
POST BODY:
{
 tasks: [ {
  id: 'complete_this_task', 
	status: 'complete'
 }, {
	id: 'skip_this_task',
	status: 'skipped',
 }, {
	id: 'uncheck_this_task',
	status: 'pending',
 } ]
}
```

The API endpoint will live in ETK so that Atomic sites can make a local (ie non `public-api`) call to it and store completion data locally.

**Comment by miksansegundo** [comment]
Hi @mattwiebe, is it okay if I deploy the ETK including these changes? I have something else to deploy.
