### ISSUE TITLE
Toolbar covers over menu creation options in some cases when trying to edit or create a menu.

### ISSUE THREAD

**Issue by CompChris** [Automattic/wp-calypso#64257]
### Quick summary

When editing the navigation menu in at least the theme Byrne (but possibly others), the toolbar covers over the menu options and makes it difficult or impossible to edit the site's menu. 

https://user-images.githubusercontent.com/6847710/171488894-580c6971-8ae8-4133-915a-c7895c2d60f0.mp4

### Steps to reproduce

1. Navigate to the Editor
2. Click on the Navigation Menu
3. Try to add menu pages to menu 

### What you expected to happen

The menubar should move away from the menu so that it can be edited.

### What actually happened

The menubar covers the menu, and makes it near impossible to edit the site menu without workarounds

### Context

Worked with customer in live chat. #31518281-hc

### Simple, Atomic or both?

Simple

### Theme-specific issue?

(Maybe) Byrne

### Browser, operating system and other notes

I'm using Edge 100.0.1185.50. 

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Workaround I found while doing this was to resize the browser window to push the menu onto the next line. This allowed me to put in menu items, and save these.

**Comment by ktyfuller604** [comment]
I ended up guiding someone through editing their menus in the Customizer, although we started in the Site Editor.

Theme: Russell
Reference: 5256264-zd

**Comment by Robertght** [comment]
Thank you for reporting this @CompChris ! I noticed this too late, but I reported it here: https://github.com/Automattic/wp-calypso/issues/64396 and it was reported to Core: https://github.com/WordPress/gutenberg/issues/41575

The workaround, for the time being, is to enable the 'top toolbar' mode there.
