### ISSUE TITLE
Fix link for "other" importer not redirecting to correct location

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#64277]
Start from: 

![Image](https://user-images.githubusercontent.com/533/171554223-4a13ac97-8588-413b-b5c8-551011c02a44.png)

and click on Import content, the link does not redirect to the correct location, instead back to the intent screen.

Example link:

https://wordpress.com/setup/importReady?siteSlug=<slug>&from=https://make.wordpress.org/&run=true

**Comment by jimmy319** [comment]
Related [PR](https://github.com/Automattic/wp-calypso/pull/64931) is merged and deployed to production. The changes have been verified in production so close it.
