### ISSUE TITLE
Update the first onboarding step after sign-up to be the vertical question screen

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64275]
## Description
Now that we have enabled the vertical question screen and generated design picker in the horizon environment, we can test the sign-up + onboarding flow end to end. We found that after sign-up, customers would land on the intent screen instead of the vertical question screen. See recording:

https://user-images.githubusercontent.com/797888/171531296-c0bb39e8-7643-4efc-aadc-d171629bec92.mp4
 
## Acceptance criteria
- [x] When v13n-related flags are enabled by default, customers should land on the vertical question screen after sign-up.
- [x] When v13n-related flags are not enabled by default, customers should land on the site intent screen after sign-up.

**Comment by arthur791004** [comment]
Close as it's shipped 🚢
