### ISSUE TITLE
Add-ons: Implement parts reusable for signup step and my-sites page (cards, grid, etc.)

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#64288]
The new my-sites section for add-ons and the signup step contain a lot of the same structure/data: the individual cards for the add-ons and the overall grid for instance. We ought to explore how we can make those reusable across VS implementing on separate ends.

So this is to gauge thinking around implementing those parts with reusability in mind. 

My initial thinking is to implement a `components/add-ons-grid.tsx` and a `components/add-ons-card.tsx` under the new my-sites section (`client/my-sites/add-ons`) and pass through conditionals as props (so don't make the actual components "over-smart") e.g. pass the respective callbacks for the actions from the point of use (for my-sites it would redirect to checkout, for signup, it would add to cart). and things like that.

I haven't looked any closer, so there may be hidden dragons!

Respective [figma mocks](https://www.figma.com/proto/KHxmM5VwfMr8z8RYGslV0H/Add-ons?page-id=2826%3A10197&node-id=2826%3A11756&viewport=356%2C48%2C0.23&scaling=min-zoom&starting-point-node-id=2826%3A10749&show-proto-sidebar=1).

**Comment by chriskmnds** [comment]
cc @claudiucelfilip @gmovr (added you both as assignees to get the ping I guess 😁)

**Comment by gmovr** [comment]
https://github.com/Automattic/wp-calypso/pull/64289

**Comment by gmovr** [comment]
@paulbonahora @victorespigares  @lucasmendes-design  -- Could we get some design review and content for this screen?

@chriskmnds -- We'll launch with premium themes, custom CSS, and no-ads at first, so we don't have to worry about the storage requirements (space selection etc), so it will limit scope of the UI a bit. We can revisit storage.

**Comment by gmovr** [comment]
This code is contained here: 64289-gh-Automattic/wp-calypso
