### ISSUE TITLE
Task: Update URLs to Domains Docs

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#64285]
### Details

Our domain-related documentation pages are being reorganized and I've identified some links that need to be updated in Calypso. I put this list together by reviewing every domain-related screen I could find in Calypso, and also by checking this file: https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/url/support.js

Is there a more complete way to check for existing URLs, that I may have missed? The main changes to note are any links to specific sections of this page `https://wordpress.com/support/domains/` using jump links. Examples:
* https://wordpress.com/support/domains/#set-a-primary-address
* https://wordpress.com/support/domains/#cancel-a-domain-name
* https://wordpress.com/support/domains/#renew-a-domain-name

These now have dedicated pages:

* https://wordpress.com/support/domains/set-a-primary-address/
* https://wordpress.com/support/domains/cancel-refund-a-domain/
* https://wordpress.com/support/domains/renew-a-domain/

In addition, any links to this jump link to the section about _transferring a domain to another site_ `https://wordpress.com/support/domains/transfer-a-domain-to-another-wordpress-com-account/#transfer-domain-to-another-site-you-own` now has it's own dedicated page to use instead:

https://wordpress.com/support/move-a-domain-to-another-wordpress-com-site/

FYI: Some of the current URLs I've listed still work, but they will stop working soon. We are waiting to push the changes live once these URL changes have been made.

### Checklist

- [ ] Connect a domain → Start setup → Advanced setup:
![image](https://user-images.githubusercontent.com/30727666/171606439-1d5810a4-0385-43f5-9354-8148852acf47.png)

Correct URL: https://wordpress.com/support/domains/connect-existing-domain/#connect-with-a-records

- [ ] Upgrades → Domains  → choose a registered domain → Name Servers → turn off "use WordPress.com name servers":
![image](https://user-images.githubusercontent.com/30727666/171607211-afde26aa-25d6-4941-bdb1-6d542dcd3948.png)

Correct URL: https://wordpress.com/support/domains/change-name-servers/#find-your-new-name-servers

- [ ] In [this file](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/url/support.js), several URLs need changing. I've listed the line number of the incorrect URL, followed by the correct URL:

6: https://wordpress.com/support/domains/change-name-servers/
7: https://wordpress.com/support/domains/change-name-servers/#find-your-new-name-servers
16: https://wordpress.com/support/domains/cancel-refund-a-domain/
30: https://wordpress.com/support/domains/incoming-domain-transfer/#faq-and-troubleshooting
48: https://wordpress.com/support/domains/connect-existing-domain/#option-2-contact-nbsp-your-nbsp-domain-nbsp-registrar
49: https://wordpress.com/support/domains/connect-existing-domain/#connect-with-a-records
50: https://wordpress.com/support/domains/connect-subdomain/
57: https://wordpress.com/support/domains/set-a-primary-address/
63: https://wordpress.com/support/change-name-servers/

### Related

https://github.com/Automattic/en.support-docs-content/issues/1532

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

- Not applicable

📌 ACTIONS

- Assigning this to @Automattic/nomado.

**Comment by arunsathiya** [comment]
For some reason, I am not able to assign a group. Wonder if GitHub stopped offering that option? 🤔 Assigning this to Del for now.

**Comment by delputnam** [comment]
I'll create a task for us to handle this during our next sprint.

**Comment by rafaelgallani** [comment]
☝🏻 This should fix it. 
Please note that I also updated other few outdated links:

- `INCOMING_DOMAIN_TRANSFER_PREPARE_UNLOCK` and `INCOMING_DOMAIN_TRANSFER_PREPARE_AUTH_CODE` - lines 28 and 29;
- `MAP_EXISTING_DOMAIN_UPDATE_DNS` - line 48, should point to the "Update Name Servers Yourself" section;
- `MAP_SUBDOMAIN_WITH_CNAME_RECORDS` and `MAP_DOMAIN_CHANGE_NAME_SERVERS` - lines 51 and 52, updated path from `map-*` to `connect-*`

**Comment by rafaelgallani** [comment]
Just deployed the PR above. It should be good now, so I'll mark this issue as closed. 
Please let us know if there's any other change needed 😄
