### ISSUE TITLE
The form block's checkbox group field is not submitting selected values on Simple sites

### ISSUE THREAD

**Issue by jorpdesigns** [Automattic/wp-calypso#64294]
### Quick summary

When filling a form that has Checkbox Group fields, the choices selected in this field are not being submitted.

I checked the Form Responses page and can see there is no value submitted for this field. Infact, the entries are not displayed among the summary of submitted fields (if this is the selected **On Submission** option). 

Values are submitted for the normal checkbox field (i.e. single checkbox).

The issue appears to happen on Simple sites only. I checked on an atomic test site and the Checkbox Group field values were submitted.

### Steps to reproduce

1. Set up a simple test site. The issue does not appear to be theme dependent.
2. Create a test page and add a Form block.
3. Add the Checkbox Group field and include some options.
4. Publish the page and submit the form. (Ensure to fill the Checkbox Group field.)

### What you expected to happen

I expect all values to be submitted, including the Checkbox Group field.

### What actually happened

The selected Checkbox Group field options were not submitted. 

The values for other fields were however submitted.
![Screen Shot on 2022-06-02 at 14:23:20](https://user-images.githubusercontent.com/40006288/171639161-33e92f37-0281-493c-8529-454f1a4d6e1c.png)

### Context

Reported in 5262419-zen

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

For now, users can replace the field with a Message field and ask visitors to add their choices there (manually).

**Comment by kimerlin81** [comment]
Another case reported here - 5265498-zd-woothemes
Workaround - switch checkbox group items to regular checkboxes. 
Testing results: checkbox group is not recording values on simple sites only

- [ ] Follow up ticket created. Please notify once fixed: 5265982-zd-woothemes

**Comment by kimerlin81** [comment]
@jorpdesigns Thanks for submitting this report! This issue has been tested and triaged for developer review.

**Comment by thekingsprojects** [comment]
Another case here: 5267464-zen (and also replicated on a Personal test site)

Suggested that the user either try a message field or individual checkboxes as a workaround.

If it's helpful at all, when going through the user's Feedback section, I noticed that the last form submission they received with working checkbox groups was May 26th. The next one, from June 1, and all subsequent submissions don't show any checkbox group results.

**Comment by janmckell** [comment]
Another case here: 5265727-zen

Recreated a Classic form for a user, and had to avoid using checkbox group, in lieu of using single checkbox instead.

**Comment by formosattic** [comment]
Seems related to https://github.com/Automattic/jetpack/issues/24625 and https://github.com/Automattic/wp-calypso/issues/64305

**Comment by Robertght** [comment]
35721025-hc in my case, the checkbox options were not passed to email.

@jeherve I'm not sure if this is tied to https://github.com/Automattic/jetpack/issues/24625, but should we move this to Jetpack as well?

**Comment by jeherve** [comment]
That seems to be the same issue. Closing as duplicate.

**Comment by jeherve** [comment]
The problem should now be fixed on WordPress.com, as of r246875-wpcom.
