### ISSUE TITLE
Marketplace: Add hover state to dropdown menu items

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#64299]
Right know we don't  have any hover behavior on the list that is shown when the "More" button is shown. We need to implement it to provide a visual cue to the user on which item is selecting.

- [ ] Design: Decide which color to use as background of each item on hover.
- [ ] Add styles for the hover

**Comment by lsl** [comment]
Designs here p1658814319620279/1658765251.733379-slack-C03FE3T479R
