### ISSUE TITLE
Anchor.fm: Update text in help article

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#64291]
We should ping Anchor.fm team since this article https://help.anchor.fm/hc/en-us/articles/360060866231-Errors-Connecting-Your-WordPress-com-Blog is out of date.

The current status is that the connection works for all WordPress.com sites, wether they are using Jetpack or not. There might be issues with standalone sites using Jetpack.

**Comment by blackjackkent** [comment]
This has been updated; closing this issue.
