### ISSUE TITLE
Reader: show followers for a list

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#643]
For a Reader list that already exists, a user should be able to view the people who are following it.

<img width="1034" alt="17325-following copy" src="https://cloud.githubusercontent.com/assets/66797/11372192/5b51f8b6-9289-11e5-9023-abcfdae1fc5d.png">

Note: the follow buttons may not be included in v1, as it's not currently possible to follow a _user_ in Reader. We could potentially offer a follow of their primary blog though.

**Comment by alisterscott** [comment]
Lists aren't being worked on for Reader at present. Closing.
