### ISSUE TITLE
Unable to edit WordPress Footer Credit in the Site Editor

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#64301]
### Quick summary

It is not possible to edit the Powered by WordPress footer credit through the Site Editor. Instead, if you visit Settings → General → Edit Footer Credit, you are taken to the Customizer. Which does not appear for Site Editor themes in the Appearance menu. 

### Steps to reproduce

1. Start on a Site Editor theme (Appleton for example)
2. Go to the Site Editor, edit the footer template
3. Look for a way to change the WordPress Footer Credit

### What you expected to happen

Depending on the plan of the site, I should either be able to change the footer credit, or remove it completely. 

### What actually happened

There is no evidence of a WordPress Footer Credit in the Footer template. Instead, to edit the WordPress Footer Credit, you have to go to Settings → General → Edit Footer Credit, which takes you to the Customizer. This introduces Site Editor users to the Customizer when they should not need to use it at all. 

### Context

Discovered while working on updating support documentation with the correct steps for editing the footer credit. 

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

While it's easy to guide a user to the option in Settings, I marked it as difficult because it introduces new users to the Customizer and could cause a lot of confusion with the other options that exist in the Customizer with no way to get back to them since it doesn't show up under Appearance.

**Comment by cuemarie** [comment]
Thanks for this report, @ktyfuller604 ! This reflects the discussion and work being done on an existing issue, so I'll close this in favor of that one. https://github.com/Automattic/wp-calypso/issues/59363
