### ISSUE TITLE
Form with required checkbox group unable to submit. "... requires at least one selection"

### ISSUE THREAD

**Issue by avantegarde** [Automattic/wp-calypso#64305]
### Quick summary

When creating a contact form with the built in Gutenberg form block, if you add a "Checkbox Group" field and set it to required, you will be unable to submit the form. Even if you have any number of items selected in the checkbox group. You will get a "{field title} requires at least one selection" error when trying to submit the form.

### Steps to reproduce

1. Create a post or a page
2. Add the "Form" block
3. Select "Contact Form"
4. Add a "Checkbox Group" block to the form
5. Add items to the "Checkbox Group" field
6. Make the "Checkbox Group" field required
7. Save/update/publish
8. View page/post
9. Try to submit form with any of the items in the checkbox selected
10. You will get an error. "... requires at least one selection"

Video of the steps above: https://jmp.sh/PiUAQfC

### What you expected to happen

I expect the form to submit successfully as long as one or more items are selected in the "Checkbox Group"

### What actually happened

The form fails to submit and produces an error. "{field title} requires at least one selection"

### Context

I ran into this while trying to help a customer create their forms in live chat. I then tested this functionality on my own WP.com site and can confirm it's the same behaviour. So it's not theme specific and is happening in multiple browsers.

Ticket -> #5265728-zen
Video of bug in action: https://jmp.sh/PiUAQfC

### Simple, Atomic or both?

Simple

### Browser, operating system and other notes

MacOS Monterey (Version 12.4)
Chrome - 102.0.5005.61 (Official Build) (x86_64)
Firefox - 101.0 (64-bit)
Safari - 15.5 (17613.2.7.1.8)

Same behaviour in all browsers listed above.

Video of bug in action: https://jmp.sh/PiUAQfC

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Use Google Forms embed, https://wordpress.com/support/google-docs/#forms

**Comment by happychait** [comment]
Another report in 22520255-hc

**Comment by cuemarie** [comment]
This looks to be the same as: https://github.com/Automattic/jetpack/issues/24625

Leaving this open for the moment but we may close this in favor of tracking all issues on that report instead.

**Comment by formosattic** [comment]
+1 5270805-zd-woothemes

Updated initial post with workaround of using Google Forms embed, https://wordpress.com/support/google-docs/#forms.

**Comment by Robertght** [comment]
@cuemarie is correct. Closing in favor of https://github.com/Automattic/jetpack/issues/24625
