### ISSUE TITLE
Task: Replace videopress_jetpack_has_capped_storage_complete_plan() with feature check

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#64310]
### Details

We should be able to replace that with a feature check for `VIDEOPRESS_UNLIMITED_STORAGE`.

### Related

https://github.com/Automattic/wp-calypso/issues/64309, https://github.com/Automattic/wp-calypso/issues/64311

**Comment by DustyReagan** [comment]
Patch here: ⚙ D82265-code Remove videopress_jetpack_has_capped_storage_complete_plan
