### ISSUE TITLE
Editor: preferences not persisting across sessions

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#64324]
### Quick summary

We've had some reports from users that editor preferences aren't persisting. This includes the Welcome Tour, but also other settings like the Top Toolbar setting and Prepublish Checklist preferences.

The occurrence of the issue appears to coincide with the launch of Gutenberg 13.2.2, which changed from storing editor preferences via a browser cookie, to storing them in the site database.

So far all the reports we've seen are from Windows 10 users, and started after clearing browser cookies or reinstalling the OS. The issue occurs across all browsers and even the desktop app on a particular computer, while preferences save just fine if the same user logs in using a different computer. So it appears to be device-specific.

There's some similarity to #57660, but this feels like a different issue.

p7H4VZ-3CN-p2 is possibly related.

### Steps to reproduce

This appears to be affecting random Windows users, with no specific steps to replicate.

One a11n has been able to replicate in p1653532494212969/1653510918.568739-slack-C03UXG192

### What you expected to happen

For the Welcome Tour to not reappear once dismissed, and for editor preferences to persist.

### What actually happened

The welcome tour keeps coming back, and editor preference don't persist.

### Context

Three reports in the forums so far:

* https://wordpress.com/forums/topic/unstoppable-tour
* https://wordpress.com/forums/topic/problem-with-setting-on-the-editor-page/?view=all
* https://wordpress.com/forums/topic/getting-rid-of-prepublish-checklist/?view=all

### Simple, Atomic or both?

Simple

### Reproducibility

Once

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by arunsathiya** [comment]
- [ ] Another report of welcome tour at the bottom left on the editor not going away: 5288361-zen

**Comment by arunsathiya** [comment]
- Quick note that I can consistently reproduce this issue on WordPress.org sites too, so I created an upstream issue here: https://github.com/WordPress/gutenberg/issues/41676

**Comment by thekingsprojects** [comment]
- [ ] Another user report here: 5290231-zen

They shared browser details (and do appear to be using Win10): https://www.whatsmybrowser.org/b/67OBE

**Comment by arunsathiya** [comment]
Update to my [previous comment here](https://github.com/Automattic/wp-calypso/issues/64324#issuecomment-1152969148): it's not happening on core, I was [testing incorrectly earlier](https://github.com/WordPress/gutenberg/issues/41676#issuecomment-1156268422). It's happening just on WPcom.

Also flagged at p1655393301515619-slack-CBTN58FTJ

**Comment by kimerlin81** [comment]
Welcome tour modal reappearing after being completed and dismissed reported

- [ ] Once fixed, please follow up with user in ticket [p7DVsv-eD3-p2](5307577-zd-woothemes)

**Comment by thekingsprojects** [comment]
- [ ] Another report of the modal reappearing when dismissed, and request for follow-up: 5307692-zen

**Comment by darnelldibbles** [comment]
The user is experiencing this issue on an Amazon Fire 10, 9th generation

Fire OS 7.3.2.3 /Android 9.

https://wordpress.com/forums/topic/welcome-to-wordpress-pop-up/?view=all#post-3835514

**Comment by csonnek** [comment]
Looks like there's another older issue tracking this in #57660

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/constant-pop-up

Chrome 102/Windows 10

The user would like a follow-up when this is resolved

**Comment by st8matrix** [comment]
Another user reported the issue here: 5319366-zen

Chrome 100

**Comment by fstath** [comment]
Another report in the forums:
https://wordpress.com/forums/topic/welcome-message-2/

OS: Windows 10
Browser: Chrome 103

**Comment by inaikem** [comment]
@alshakero, is there anything we can do to help get a review of this prioritised? I'm also experiencing this myself (macOS), with editor settings not persisting past a single page reload).

**Comment by cuemarie** [comment]
User on Windows encountered here: 4610790-hc  Follow up ticket created for bulk reply: 

- [ ] 5661961-zd-woothemes

**Comment by villanovachile** [comment]
Another report here 5664158-zd

Editor Preferences are not saved,i.e., unchecking "Use theme styles".

**Comment by cuemarie** [comment]
Bumped up the priority on this as we continue to see reports from users, and I'm running into more bug reports that look like they reflect this same issue (⬆️)

**Comment by cuemarie** [comment]
User Report from #69789 , specifically within Baskerville 2: 

- [ ] 5681323-zd-woothemes

**Comment by ccwalburn** [comment]
Another report here 37655855-hc

Editor Preferences are not saved (i.e., unchecking "Use theme styles")
Theme: Sela
Plan: Personal

I can recreate the issue when going to their dashboard from here.
However, I tried to recreate the issue on my own Personal plan test site using the Sela theme but cannot.

**Comment by aleone89** [comment]
Another report here: https://wordpress.com/forums/topic/preferences-wont-stay/?view=all

Editor: Editor Preferences are not saved (i.e., unchecking "Use theme styles")
Theme: Penscratch 2
Plan: Free 

Can replicate.

**Comment by happychait** [comment]
Another user reported this issue in 5757459-zen

Attached the video of the problem.

https://user-images.githubusercontent.com/1519466/205473015-faad19db-b8a0-4ea0-9937-8686f0929da5.mp4

**Comment by sophiegyo** [comment]
Another user in the same topic Adam linked before: https://wordpress.com/forums/topic/preferences-wont-stay/?view=all#post-3895821

Theme: Quintus
Plan: Free

**Comment by sophiegyo** [comment]
Forum post: https://wordpress.com/forums/topic/how-to-permanently-turn-off-use-theme-styles/?view=all
Theme: Sapor
Plan: free

**Comment by iamjohnrex** [comment]
Another report here 5811812-zd

Editor Preferences are not saved,i.e., unchecking "Use theme styles"

**Comment by zdenys** [comment]
5810980-zd-woothemes

>post setting preferences are always collapsed except for Summary when in the Block Editor

**Comment by ai2n** [comment]
Another one: #39108117-hc
unchecking "Use theme styles" does not persist

**Comment by iamjohnrex** [comment]
5821128-zd-woothemes
unchecking "Use theme styles" does not persist

**Comment by iamjohnrex** [comment]
Another report: 5831391-zd-woothemes

**Comment by danielbachhuber** [comment]
Some internal experience with this in p1673374961019329-slack-C9EJ7KSGH

**Comment by vykes-mac** [comment]
There is currently a rule that always forces the editor in the iframe/calypso to open in fullscreen mode, so even if we save the preference it will always open in fullscreen.

see `wp-content/admin-plugins/calypsoify/mods-gutenberg.js`

**Comment by danielbachhuber** [comment]
> There is currently a rule that always forces the editor in the iframe/calypso to open in fullscreen mode, so even if we save the preference it will always open in fullscreen.

@vykes-mac What's the history of the rule? How would you suggest resolving it?

**Comment by vykes-mac** [comment]
@danielbachhuber I haven't gotten back to look at this, I had ask about the rule [here](p1674141481231349-slack-C01LXBU1N21) but was working on a related issue before getting back to this one. I added my findings so that if anyone else pick it up they would have a starting point. I probably continue looking at this in my 20% time.

**Comment by kozer** [comment]
@danielbachhuber , @vykes-mac 
I investigated it a bit more and found D40831-code

It states the following:

```
Forces the fullscreen mode in a similar way that we do for post editor.

Note: this will only ensure that it's toggled on the first load. Hiding the option to disable the fullscreen mode from more menus will be handled separately.
```

I'll take a look on the post-editor now, and post here my findings

**UPDATE:**

I didn't know you can blame the code in `phabricator`. I have found that you can do that, and land to this diff:
D20055-code

It doesn't seem that there is a solid reason for that "feature" in the first place. In that diff, exists a p2 post that describes what was the plan, but there is no mention of the fullscreen part of the code.

@vindl may have some insights on that.

**UPDATE 2:**

Unfortunately, I couldn't replicate the issue. What I have tried so far. (The persistence issue, the fullscreen is replicable as described above):
- Sessions
- Created a new blog and tried to replicate the issue, as described, both in staging and prod. Also tried with different browsers (firefox, chrome) and different themes (that have been reported). No success either.
- Downgrade Gutenberg. No success.

Do we know any way to consistently replicate that?

**Comment by vykes-mac** [comment]
@kozer comment out the line in `wp-content/admin-plugins/calypsoify/mods-gutenberg.js` that always forces fullscreen, that will fix the original issue, the preference is being persisted but the force fullscreen was always overwriting it so it appears as if it wasn't being persisted.

remove the comment and it will always open fullscreen even if you turn off fullscreen.

**Comment by danielbachhuber** [comment]
@vindl @Addison-Stavlo Do either of you recall _why_ D40831-code was added? Maybe we could remove it now?

**Comment by kozer** [comment]
@danielbachhuber This was added as a continuation to the post-editor (as it's stated in the diff). The real question, at least for me, is why the full screen was added in the post-editor, in the first place. (D20055-code)

**Comment by danielbachhuber** [comment]
Continuing the conversation in pdqkMK-T3-p2#comment-1136

**Comment by danielbachhuber** [comment]
Fullscreen mode is hidden again with D100815-code

Because we `<iframe>` the Post Editor, it's not possible to navigate away to a `*.wordpress.com` URL (the browser restricts it). As such, we can't offer any sidebar navigation links.

Unfortunately, "Unchecking 'Use theme styles' does not persist" seems to be an entirely different issue that we need to track down reproduction steps for.

**Comment by danielbachhuber** [comment]
> is there anything we can do to help get a review of this prioritised? I'm also experiencing this myself (macOS), with editor settings not persisting past a single page reload).

@inaikem @cuemarie @happychait Can any of you reproduce this issue on your own?

My best guess is that it's something browser-specific, or a race condition between API requests (request A completes after request B and overwrites the changes in request B).

**Comment by christianguerrag** [comment]
The user reached out as the problem with unchecking "Use theme styles" not persisting, came back. It solved itself before.
New ticket 6009283-zen

**Comment by lupus2k** [comment]
I investigated it and found the problem is caused by an empty `serverData` when initializing the `preferencesPersistence` [here](https://github.com/WordPress/gutenberg/blob/3f20fdc09293020ab350ca8e95621ce06b092acf/lib/compat/wordpress-6.1/persisted-preferences.php#L58)

If the user does not have the `WP_PREFERENCES_USER_$USERID` localStorage, the settings are loaded from the `/sites/$blogId/users/me` endpoint (`meta.persisted_preferences`), but if the localStorage exists, it compares the `modified` parameter of `serverData` and the `localData` (from LocalStorage), and as the `serverData` is null, the `localData` always "win" and the settings are loaded from the localStorage.

I noticed the site editor searches for a different `meta_key` than the `/sites/$blogId/users/me` endpoint, and I think the problem could come from there.

As an alternative solution, I suggest [removing the cache](https://github.com/WordPress/gutenberg/blob/3f20fdc09293020ab350ca8e95621ce06b092acf/packages/preferences-persistence/src/create/index.js#L40-L42), the only problem could be all editors will call `/sites/$blogId/users/me` on load to get the settings.

**Comment by lupus2k** [comment]
What do you think about [this](https://github.com/Automattic/wp-calypso/issues/64324#issuecomment-1462869564), @danielbachhuber ?

**Comment by danielbachhuber** [comment]
@lupus2k I don't have any mental bandwidth for this today or tomorrow. Want to pair on it Monday or Tuesday? Ping me in Slack and we can set up a time.

**Comment by danielbachhuber** [comment]
@lupus2k did a great job debugging this.

Here's how to reproduce:
1. Open a post in wp-admin in one browser and change a preference.
2. Refresh the page.
3. Open a post in wp-admin in another browser and change a different preference.
4. Refresh the first window and observe that the preference is incorrect.

Gutenberg has some fanciness to make sure that any changes in the second browser are applied to the first browser: https://github.com/WordPress/gutenberg/blob/7d99c49fd267de4c1cccda0224f35a20c8e887f6/lib/compat/wordpress-6.1/persisted-preferences.php#L46-L75

For `gutenberg_configure_persisted_preferences()`, `$wpdb->get_blog_prefix()` uses the correct blog ID. However, when the user meta is registered in `gutenberg_register_persisted_preferences_meta()`, the blog prefix is incorrect: it's referencing `public-api`.

Thus, `serverData` isn't ever populated:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/36432/224839149-f24b8c32-008b-40a1-9149-d12ad8cfe4b6.png">

We need to make sure `register_meta()` registers a meta key with the correct blog ID. Once that's done, `serverData` should be populated as expected.

**Comment by creativecoder** [comment]
@lupus2k @danielbachhuber Nice sleuthing!

This has been a common problem with the Gutenberg integration for Simple sites. Take a look at the prior art in `wpcom-gutenberg-load.php`. Unhooking `gutenberg_register_persisted_preferences_meta` from `init` and adding it back on another hook like `restapi_theme_init` may fix the issue.

**Comment by creativecoder** [comment]
`rest_api_switched_to_blog` may be a better hook to use, since the issue is with the blog prefix, and not the theme.

**Comment by danielbachhuber** [comment]
@lupus2k Need any help landing your fix?

**Comment by lupus2k** [comment]
Sorry, @danielbachhuber, I was AFK until today, I will submit this on the next days 😉

**Comment by lupus2k** [comment]
I created a PR on Gutenberg to fix this issue: https://github.com/WordPress/gutenberg/pull/50005

**Comment by lupus2k** [comment]
Created this diff: D108772-code

**Comment by lupus2k** [comment]
> I created a PR on Gutenberg to fix this issue: [WordPress/gutenberg#50005](https://github.com/WordPress/gutenberg/pull/50005)

We closed this in favor of @creativecoder suggestion [here](https://github.com/Automattic/wp-calypso/issues/64324#issuecomment-1467028176).
Thanks @danielbachhuber, for noticing this.

**Comment by danielbachhuber** [comment]
Started a conversation about seeing if we can catch these issues more proactively p1682347976509179-slack-CBTN58FTJ

**Comment by lupus2k** [comment]
Thanks for catching this @danielbachhuber, it a great idea!

**Comment by lupus2k** [comment]
We merged the fix (D108772-code) and the problem should be solved

**Comment by cuemarie** [comment]
@lupus2k @danielbachhuber it appears this issue may have returned. it was reported here: https://github.com/Automattic/wp-calypso/issues/80852

and I was able to reproduce following [your steps above](https://github.com/Automattic/wp-calypso/issues/64324#issuecomment-1467011892) on Simple Site only:

https://github.com/Automattic/wp-calypso/assets/27249804/43f4267e-563a-4195-8046-2e507052822e

Are y'all available to take a look to see if something regressed here?

**Comment by cuemarie** [comment]
User report from #80852 : 

- 6689722-zen

**Comment by cuemarie** [comment]
@danielbachhuber Would you prefer that we look into this as a new report as well, rather than reopening this one? (If so, I can take care of spinning up that new issue instead!)

**Comment by danielbachhuber** [comment]
@cuemarie Yes, please. Thanks!

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closed in favor of new report: https://github.com/Automattic/wp-calypso/issues/80852
