### ISSUE TITLE
Legacy plan price on /plans page is incorrect in INR, MXN, and PHP

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#64320]
### Quick summary

The legacy plan prices listed in Calypso's `/plans` page is incorrect in INR, MXN, and PHP. These prices can only be seen by users who are on a legacy plan. 

### Steps to reproduce

1. Signup for a new account by proxying via an Indian IP address (proxy.bom.xxxx.xxx if you're using AutoProxxy).
2. Purchase a legacy Personal plan by following the instructions in 2c97d-pb.
3. Go to `/plans` page and look at the plan prices.

### What you expected to happen

1. I expected to see the upgrade prices for the Premium, Business, and eCommerce plan to reflect the actual costs seen in checkout. 
2. The crossed-out price and listed price should be different.

### What actually happened

**The upgrade prices listed for Premium, Business, and eCommerce are incorrect.**

Example, when on the Personal plan, the upgrade price listed for the Premium plan is INR 3360. But on the checkout page, the price listed is INR 1800. The checkout page price is correct, the `/plans` page price is wrong.

<img width="1149" alt="Screenshot 2022-06-03 at 11 52 14 AM" src="https://user-images.githubusercontent.com/1269602/171815114-75bbcd0b-75a8-4e85-bac8-adbf15e73a63.png">

<img width="573" alt="Screenshot 2022-06-03 at 12 10 04 PM" src="https://user-images.githubusercontent.com/1269602/171815235-5cefdc85-1585-47c7-b896-f7dc70505fcb.png">

**Crossed-out price and listed price are the same**

The listed price should be the discounted price after pro-rata credits are applied.

<img width="751" alt="Screenshot 2022-06-03 at 12 11 21 PM" src="https://user-images.githubusercontent.com/1269602/171815403-18973f72-051c-40c4-a860-f395334ab090.png">

<img width="1118" alt="Screenshot 2022-06-03 at 12 15 04 PM" src="https://user-images.githubusercontent.com/1269602/171816028-b4201ef1-8e81-4253-aacd-7b7c7426f301.png">

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic - Could Not Replicate

📌 ACTIONS
- Closing as resolved
