### ISSUE TITLE
[Bug]: New line prevented after adding a user mention

### ISSUE THREAD

**Issue by annemirasol** [Automattic/wp-calypso#64326]
### Quick summary

After entering a user @-mention via autocompleter, no matter how many times `ENTER` is hit, new lines do not get added.

### Steps to reproduce

1. Start at any simple site with `v13.4.0-rc.1` enabled (`gutenberg-edge` at time of writing).
2. Type in a few things, then start adding a user mention, and use the aucompleter when it pops up.
3. New lines are afterwards prevented.

### What you expected to happen

I should be able to enter a new line after typing in a user mention.

### What actually happened

No matter how many times I hit `ENTER`, no new lines.

https://user-images.githubusercontent.com/730823/171856322-472b9937-b202-4b8c-a21c-52b9bf059ecc.mov

### Context

Gutenberg Edge testing

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Other notes

Gutenberg: v13.4.0-rc.1
Editing Toolkit: 3.34442
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.2

### Reproducibility

Intermittent

### Severity

Most (> 50%)

**Comment by chad1008** [comment]
I've tracked the source of this down to[ a recent PR of mine](https://github.com/WordPress/gutenberg/pull/41382), sorry for the inconvenience!

I've also confirmed this new bug is present in core, so an issue has been opened there as well:
https://github.com/WordPress/gutenberg/issues/41724

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple & SH: Could Not Replicate

📌 ACTIONS
- Closed as Resolved
