### ISSUE TITLE
Jetpack NUX: if auto-config fails, provide path to support

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6432]
If installation of a plugin fails on auto-config, we currently show a blue notice that mentions there was a problem, and directs you to look at each plugin card to see the error. 

This notice should be red, and can be more actionable. Let's make it red, let's provide any known reasons for the failure, and let's provide links to the manual instructions and to contact Jetpack support:

<img width="758" alt="screen shot 2016-06-29 at 4 01 42 pm" src="https://cloud.githubusercontent.com/assets/437258/16466984/32579106-3e13-11e6-8b72-dcbd51dec265.png">

**Comment by v18** [comment]
Let's also show links to support on this page, for .org premium/business sites:

<img width="836" alt="screen shot 2016-06-29 at 3 16 57 pm" src="https://cloud.githubusercontent.com/assets/11487924/16467267/98109b18-3e14-11e6-9bab-34610f44b6c3.png">

**Comment by rickybanister** [comment]
In those cases it would be a primary button, but yeah, that makes sense!

**Comment by v18** [comment]
These are the errors we should list:

- when `DISALLOW_FILE_MODS` is set to true
- when `DISALLOW_FILE_EDITS` is set to true
- WordPress is under version control
- when there’s a conflicting plugin (which one is conflicting? that’ll help us figure things out faster in support)

All others should not display the phrase 'because %reason%'.

**Comment by ryelle** [comment]
> This notice should be red, and can be more actionable. Let's make it red, let's provide any known reasons for the failure, and let's provide links to the manual instructions and to contact Jetpack support:

There could be multiple reasons, if more than 1 plugin failed. How would you feel about just adding a support link to the big notice, and in the plugin errors we list the reason? Like so (but with better text):

![screen shot 2016-07-01 at 11 19 40 am](https://cloud.githubusercontent.com/assets/541093/16526143/c13d03f4-3f7d-11e6-809b-90ba2693d781.png)

**Comment by rickybanister** [comment]
I agree with you, but I don't like using the catch-all so much. In your example it mentions 'issues' but there is only one issue—with VaultPress. 

The only other thing I don't love is that the notice is not dismissable—you have to contact support to dismiss it, even if you know how to bypass the problem yourself. That's kind of why I went with the inline links in my mockup.

**Comment by ryelle** [comment]
>  In your example it mentions 'issues' but there is only one issue—with VaultPress.

That's easy enough to fix, I wouldn't get hung up on the text there.

> The only other thing I don't love is that the notice is not dismissable—you have to contact support to dismiss it

Why does it need to be dismissable?

**Comment by rickybanister** [comment]
I suppose it doesn't need to be dismissable, I just didn't want people to feel compelled to contact support. I guess I also feel sort of caught up in the generality of our discussion. Are the four error types @v18 listed above the only possibles?

**Comment by ryelle** [comment]
> Are the four error types @v18 listed above the only possibles?

Probably not- the first 3 are "we can't install" states (and not all of them, it could also be a WP network or multisite). The last is the most likely "we can't activate" error. We could also have trouble installing (a broken folder exists where we want to install, maybe if the plugin was improperly removed), or trouble configuring (the VaultPress issue from the testing thread, where the site was previously using VaultPress).

There are so many ways people can install & misconfigure WordPress that I don't think I could make an exhaustive list.

**Comment by rickybanister** [comment]
Ok, taking a step back:

I don't think the main notice _needs_ to be dismissable, it just seemed like a nice option and also offered an opportunity to provide more than one action as inline links. I do think that getting help from support should be the top priority, so making it a notice action is probably ideal. 

Since manual install may be an option for users, we can likely still link to the support doc from the main notice's body text.

And if it makes sense for the plugin-specific notices, it would be good for them to have notice-actions with some pathway as well (manual install link I suppose). 

That last item I think is where we point the 'contact support' link to—I believe we've been pointing to jetpack.com/support, but the calypso help form handles requests for jetpack sites. We should point there to keep the user within calypso.

**Comment by ryelle** [comment]
So you're saying that for the main notice, Contact Support stays as the NoticeAction, but we'll also link to Manual Install in the text of the notice, right? Like this, perhaps:

![screen shot 2016-07-01 at 2 40 05 pm](https://cloud.githubusercontent.com/assets/541093/16531271/bd870cc0-3f99-11e6-83a9-b952d3ba925c.png)

And for each plugin notice, we'll keep what they are now?

![screen shot 2016-07-01 at 2 38 11 pm](https://cloud.githubusercontent.com/assets/541093/16531223/758504a4-3f99-11e6-90eb-5a56b8d9c9e7.png)

> That last item I think is where we point the 'contact support' link to

Yeah that's already been updated in the PR I started for this: #6480, which is pulling the link updates from the My Plans PR #6295.

**Comment by rickybanister** [comment]
That looks great. I think it hits everything. 

The only remaining question/concern I have is if we can be more specific about the error that occured when activating VaultPress? Do you think any of it is helpful to display?

What of this information gets logged? Will the HE the user contacts have any debugging info or way to help without the user spelling it all out for them? That would certainly be outside the scope of this PR, just curious though.

**Comment by ryelle** [comment]
>  if we can be more specific about the error that occured when activating VaultPress?

It's generally not a useful error, like `MkdirFailedCopyDirError: mkdir_failed_copy_dir`. We _are_ at least saying where in the process it failed (installing, activating, configuring).

> What of this information gets logged?

The errors are logged in tracks, but not anywhere in the site meta or anything like that.

**Comment by rickybanister** [comment]
I wonder if these errors can be logged/stored along with the other 'sync' data and be displayed some day in the 'activity log' for a site. After all, it's the same if we install/update/activate a plugin or if they do. 

cc @lezama and @enejb for some insight
