### ISSUE TITLE
Atomic: Renewal notice keeps displaying after renewal

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#64333]
When a customer has renewed their site’s plan WPCOM_PURCHASES persistent data does not get the updated date after renewal, which then continues to show a renewal banner for customers in WP Admin.

![Image](https://user-images.githubusercontent.com/1398304/171902438-4075c313-28a9-46fd-a2a8-b0037d9f7003.png)

See pdG1ka-8b-p2

**Comment by obenland** [comment]
It looks like we need to add the renewal date for each purchase to the purchase data object and check for that as well.

**Comment by obenland** [comment]
Fix in D82039-code

**Comment by DustyReagan** [comment]
More thoughts on this bug here: p1655761742822029-slack-C02V49GM0PN

**Comment by obenland** [comment]
I mean that feels like a pretty strong possibility. I'd be fine with deferring the purchase update job by 10 seconds or something and have the job itself use `send_reads_to_masters` to improve the likelihood of renewal purchases being synced after the DB update.

**Comment by mmtr** [comment]
> I'd be fine with deferring the purchase update job by 10 seconds or something and have the job itself use `send_reads_to_masters` to improve the likelihood of renewal purchases being synced after the DB update.

Created D82940-code to add these changes.

**Comment by mmtr** [comment]
Just deployed D82940-code which delays the sync of purchases by 5 seconds, so let's close this one out for now. Feel free to re-open if we receive new reports of outdated `WPCOM_PURCHASES` persistent data.
