### ISSUE TITLE
Site Preview link in My Sites Menu is potentially confusing

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#6433]
New users may find it unclear what the sitecard link in the My Sites menu does.

Currently it opens a preview modal with a tooltip that says, ""View [sitetitle]."

![](https://cldup.com/7z5VTEGofW.png)

**Suggested improvements:**
1. Add a descriptive label like, "Preview your site."
2. Make the tooltip more direct by changing it to, "Preview your site."

**Comment by lancewillett** [comment]
@ianstewart Thanks again for your suggestion — we have a change ready for you to review in #9095 when you have time. (There's a handy Live Branch link there to spin it up.)
