### ISSUE TITLE
Self-service button to resend verification email for an unverified, new account

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#64345]
### What

At this time, we don't have a button on Calypso to resend the verification email for an unverified, new account. In the rare chance that the new customer deletes that email, the only option is for a staff at WordPress.com to verify the account manually and that involves an email handshake (WordPress.com to send the email to the customer, and customer has to reply to it from the same address) to process the verification.

### Why

Having a self-service button within Calypso will prevent the need to reach out to the WordPress.com staff. 

### How

Ideally, this button would be on the https://wordpress.com/me/account page.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/18581859/171982485-5a9fb667-d408-4dea-852f-47689670eb90.png">

As we can see on the image above, there's no indication that the account is no verified, nor a button to resend the verification email.

**Comment by zachspears** [comment]
This is an important addition to make it easier HE's to help users get verified in this unique case. Given the rarity of the occurrence, I am setting this to Low Priority.

If many cases are added, we can adjust the priority accordingly.
