### ISSUE TITLE
Marketplace: When searching for a plugin, it says 4 Results found but doesn't show any plugin to select from.

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#64340]
## Steps to replicate

 - Click on Plugins. ->Add new
 - Search for "Xendit" plugin

## Result

It says " 4 Results found" but doesn't have any list of plugins to select from. It's a blank page.

<img width="1800" alt="Screenshot 2022-06-03 at 2 04 03 PM" src="https://user-images.githubusercontent.com/16509219/171921251-feefc58a-0c9b-48d6-8d7f-1c00a2b95cc8.png">

## Expected

It should either say "No results" or show the list of plugins to select from

Workaround:

The plugin showed fine when searching from the WP-Admin dashboard.

<img width="2077" alt="Screenshot 2022-06-03 at 2 05 28 PM" src="https://user-images.githubusercontent.com/16509219/171921363-b1100fd8-3e0c-40f0-83a9-bfacf195c227.png">

* User report: 35699202-hc 

No follow up needed because the user was able to install the plugin fine from the WP-Admin dashboard.

**Comment by cuemarie** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- **Could not replicate.** I tested this on AT, Simple, and Self-Hosted (just in case), and I was able to see search results in all three scenarios. Example below from my AT test site: 

![Markup on 2022-06-14 at 09:33:20](https://user-images.githubusercontent.com/27249804/173629714-6ba85723-961e-489c-aaf4-3ef924d59ce3.png)


📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author
- @nerdysandy I recognize the behavior in your screenshot from helping a user once whose site was encountering some Jetpack issues - I wonder if they had recently gone AT, switched their primary domain, or taken another action that might have resulted in a delay within Calypso, perhaps? (I did take a quick look at their SA, but it appears they've cancelled their plan with us).
