### ISSUE TITLE
Revision history for style switches and global font changes

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#64348]
### What

With style switches being a prominent feature on WordPress 6.0, more themes are likely to adopt that functionality soon. Global fonts is already available. Revision history for these two features would be nice, allowing users to undo/review the changes.

### Why

Like post/page content revisions, being able to undo design changes would be a nice-to-have.

**Comment by supernovia** [comment]
@arunsathiya would this fit under this more general request for an FSE revision history?
https://github.com/WordPress/gutenberg/issues/36060 _(edited; wrong link initially!)_

I think it would, and I'm asking on that issue if those would be included, but if you think there's an extra case for having these separate, we can re-open this. In any case, a revision history for all FSE changes is definitely needed. If it doesn't become part of Core, we should probably work to make it an option here at least.
