### ISSUE TITLE
Be able to get to Style Switcher from a post or page editor

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#64350]
### What

An option to access the Style Switcher from the post/page editor, or being directed to the Site Editor from the post/page editor would be nice.

### Why

Currently, Style Switcher is hidden inside the Site Editor. From a technical standpoint, it makes because customizations are a site-level functionality. Previously it was on the Customizer, now on Site Editor. But, for a website owner that's mostly spending time on a page or a post editor, making that option visible on the post/page editor feels better.

**Comment by Robertght** [comment]
I believe this will happen here:

The great unification  - https://github.com/WordPress/gutenberg/issues/41717
