### ISSUE TITLE
Skip the WordPress Migration selector for WP imports starting from "I don't have a website"

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#64364]
https://user-images.githubusercontent.com/533/172102757-059a9732-fd0a-484b-8fed-b978f0c09f60.mp4

Skip the "Everything selector" screen when in this flow as it doesn't make sense.

**Comment by ouikhuan** [comment]
It's been deployed and fixed so I'll close the issue for now.
