### ISSUE TITLE
Revalidate and add new track events for the Full Importer flow

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#64365]
See Full Importer Metrics here: PcmemI-6i-p2

Fix all the red items (by recording track events manually), and revalidate all the green ones in the `/setup` flow.

To revalidate, start from `https://wordpress.com/start`. The Tracks Vigilante extension is super helpful: PCYsg-cae-p2

**Comment by jimmy319** [comment]
## Result of revalidation

| step  | event | valid |
| ------------- |:-------------:|:-------------:|
| URL Capture      | calypso_signup_step_start [flow=importer step=capture]     | X |
| Scanning      | calypso_signup_step_start [flow=importer step=capture action=scanning]     | O |
| Preview Page      | calypso_signup_step_start [flow=importer step=ready action=preview platform=wix...]     | O |
| Back (preview -> URL capture)      | calypso_signup_previous_step_button_click     | O |
| Scanning Error      | calypso_signup_step_start [flow=importer step=capture action=scanning-error error=stringifyErrorObj]     | O |
| Site is already on WPCOM      | calypso_signup_step_start [flow=importer step=ready action=already-wpcom platform=wix...]     | O |
| Back (site is already on WPCOM -> URL capture)      | calypso_signup_previous_step_button_click     | O |
| Importer List      | calypso_signup_step_start [flow=importer step=list ]     | X |
| Ready Page      | calypso_signup_step_start [flow=importer step=ready action=regular platform=wix...]     | O |
| Back (ready page -> importer)      | calypso_signup_previous_step_button_click [flow=importer step=ready]     | X |
| Import Guide on Preview Page      | calypso_signup_step_start [flow=importer step=ready action=guide-modal platofrm=wix...]     | O |
| Import Guide on Ready Page      | calypso_signup_step_start [flow=importer step=ready action=guide-modal platofrm=wix...]     | X |
| File Import Selector      | calypso_site_importer_start_import_request [site_engine=wordpress...]     | O |
| Back (file import selector -> capture)      | calypso_signup_previous_step_button_click [step=importer-step]     | O |
| Back (author mapper -> capture)      | calypso_signup_previous_step_button_click [step=importer-step]     | O |
| Migration Import Selector      | calypso_signup_actions_submit_step [intent=import step=importReadyPreview]     | X |
| Setup Jetpack (external)      | calypso_page_view [path=/jetpack/connect]     | O |
| Checkout Screen (external)      | calypso_signup_actions_submit_step [step=importerWordpress type=redirect] calypso_checkout_composite_payment_complete calypso_checkout_payment_success calypso_checkout_payment_failure     | O |
| Dashboard View Site      | calypso_signup_actions_submit_step [step=importerWordpress type=redirect]     | O |
