### ISSUE TITLE
Vertical Question Screen: Add "X" to clear the v13n input box

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#64371]
# Description

User should be able to easily clear their input. This is a common UI feature in an entry box.  See CfT [discussion](pdtkmj-ba-p2#comment-276).  

Add an "X" next to the drop down caret - please get input from @saygunnyc on the visual.

This can be in addition to work done in #64284

![Image](https://user-images.githubusercontent.com/5665959/172141908-9c73bb52-3435-4091-90bb-965e3c2d5169.png)

# Dev Tasks
- [ ] task1

**Comment by saygunnyc** [comment]
Sharing below:

<img width="2041" alt="ClearCTA" src="https://user-images.githubusercontent.com/78876323/173931696-35bf874d-7d9f-408e-8587-308e148669b8.png">


Here's a link to the Figma 42PgVsdlQ1v2wpk6lmmrnq-fi-2834%3A66374

**Comment by arthur791004** [comment]
Close it as it's shipped 🚢
