### ISSUE TITLE
Reusable Blocks: Add focus to `Create Reusable block` on open

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#64373]
### What

When the `Create Reusable block` modal is triggered via the `Add to Reusable blocks` menu in Gutenberg, it would be fantastic to have the cursor focused in the text field of the modal.

### Why

Usability and accessibility. It feels like having the field focused is expected. When you see the modal you want to type in it immediately. 

Note: It takes two tabs to move focus to the field.

### How

See "What" 🙏

**Comment by zachspears** [comment]
This is a great idea, and I agree with the usability implications. Marking as Normal Priority!

**Comment by zachspears** [comment]
_[Moved to Gutenberg Repo](https://github.com/WordPress/gutenberg/issues/41927)_
