### ISSUE TITLE
Seller Experience: Audit flows for references to Pro/Starter plans

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#64382]
As part of an upcoming revert we should be aware of any hard-coded references to the Pro or Starter plans in our flows. Gather those instances in this ticket so we can address them at a future date TBD.

p58i-cuY-p2#comment-54335

**Comment by andres-blanco** [comment]
There is some usage of the `isElegibleForProPlan` selector in [this file](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/index.tsx#L291) to form the link to checkout. I don't know how the revert is going to roll out, but if the flag `'plans/pro-plan'` is turned off there will be nothing to do here.

**Comment by andres-blanco** [comment]
There's a reference to Pro Plan [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/woo-confirm/index.tsx#L171).

**Comment by sixhours** [comment]
Looks like these changes should take effect June 16, so we should plan to roll out any copy/wording changes shortly after: p7DVsv-eGr-p2

**Comment by blackjackkent** [comment]
Follow up in plans working group channel in Slack with any changes that will be necessary for this process.

**Comment by andres-blanco** [comment]
The two references mentioned above no longer exist.
