### ISSUE TITLE
FSE: Image forced resized when align was set.

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#64398]
### Quick summary

https://user-images.githubusercontent.com/92185881/172321082-570fb7b4-54b7-4704-96a3-e958c6c815f8.mp4

Images with an _align_ set were automatically resized on the front end when it was set to Full Size in the Editor, with the Videomaker theme active.

The issue does not happen on a different FSE theme (tested with Archeo).

### Steps to reproduce

1. Activate Videomaker theme.
2. Add an image with align set (eg: right), even when the Image size was set to Full Size.
3. Preview displays a resized version of the image.

### What you expected to happen

The image to inherit the "Full Size" or "100%" from the Image block settings.

### What actually happened

The preview displayed a resized version of the image.

### Context

First encountered at 5258858-zen. Suggested a workaround, which was to set the alignment to default or none.

### Theme-specific issue?

Videomaker

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Setting the alignment to default or none seems to work for this.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- This appears to be an issue with FSE in general. Here are my results with Blockbase and Twenty Twenty Two:

![image](https://user-images.githubusercontent.com/6737345/172332410-97234f4d-2cae-4f69-8e3c-2db242f90d23.png)

![image](https://user-images.githubusercontent.com/6737345/172332624-3ed9eb94-52ec-4e38-9d6f-e379969d9b87.png)

I believe this is not 100% theme-related, but FSE/editor-related.

@Automattic/cylon can we get more insights on how the images should behave please?

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Addison-Stavlo** [comment]
This was likely a core editor issue.

Testing now Im seeing a full-sized aligned image properly displaying without getting re-sized:

![Screenshot 2023-03-22 at 12 33 05 PM](https://user-images.githubusercontent.com/28742426/226973902-e7412104-b342-4574-866f-07b0b1031a44.png)
