### ISSUE TITLE
Generated design picker: Switching to the static design picker and clicking "Skip for now" leads to FSE with generated design

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64391]
## Description
In the generated design picker, when the user click on "View more options" the UI switches to the static design picker. While in the static design picker, if the user click on "Skip for now" they will be redirected to the FSE, but a generated design instead of a placeholder design. See screenshot below for the placeholder FSE experience:

![Screen Shot 2022-06-07 at 1 27 23 PM](https://user-images.githubusercontent.com/797888/172304098-c6e4db50-b57d-4fc1-9f8a-fe20fe47b20e.png)

## Acceptance Criteria
- [ ] Clicking the "Skip for now" button in the static design picker should redirect users to the FSE with a placeholder/boilerplate design.

**Comment by taipeicoder** [comment]
@arthur791004 not sure if it's related to this issue, but it seems that with the "Skip for now" button, the image replacement are always food images. This is a recording of the issue, where having "News" vertical, I changed it to "Finance" but clicking the "Skip for now" button I get Food images.

https://user-images.githubusercontent.com/797888/172328736-5b2e3c5e-6621-4982-97d0-0ff73afa86c4.mp4

Let me know if it makes to open up a separate issue for this. Thanks!

**Comment by arthur791004** [comment]
I think it's the original design you choose. That being said, you select the “Food” related vertical before and pick the one of the generated design. So, the home page of your site is replaced with the generated design with “Food” related vertical at that time. That's why you get Food images. Actually, “Skip for now” does nothing. Our new site starts with “Zoologist” by default. And if you never select the generated design or static design, you will land on the FSE with “Zoologist” and it's the current behavior.

https://user-images.githubusercontent.com/13596067/172334016-929d1312-a90b-4b46-b886-689edb87d7db.mov

**Comment by arthur791004** [comment]
> While in the static design picker, if the user click on "Skip for now" they will be redirected to the FSE, but a generated design instead of a placeholder design

Did you get the generated design while clicking on “Skip for now” on the new site? I tested on the new site but I got the placeholder design, and I think it's the correct behavior, right?

**Comment by taipeicoder** [comment]
> > While in the static design picker, if the user click on "Skip for now" they will be redirected to the FSE, but a generated design instead of a placeholder design
> 
> Did you get the generated design while clicking on “Skip for now” on the new site? I tested on the new site but I got the placeholder design, and I think it's the correct behavior, right?

Ah, so what I saw was my previous edit... 😅 That makes a lot of sense!

**Comment by arthur791004** [comment]
So, I think we can close this issue as the current behavior is correct. What do you think?

**Comment by taipeicoder** [comment]
Yes, I just tried the flow with a new site, and it works as intended with the placeholder design. Thanks for the troubleshoot!
