### ISSUE TITLE
Marketplace - Bring in Classic view for Plugin installs 

### ISSUE THREAD

**Issue by nagpai** [Automattic/wp-calypso#64392]
### What

We may want to add a `View > Classic View / WP.com view` toggle for the Add new plugins page too which is currently forced to the Marketplace view.  

### Why

We may need to do this for users seeking parity with standard .org WP admin, and not wanting to see our paid recommendations on top. Users should have this choice. 

Context : 
[35730542-hc](35730542-hc)

**Comment by nagpai** [comment]
Calypso Plugin install page was drawing a blank due to Perfmatters performance plugin . User had to fall back on WP admin plugins page to install plugins 
28412938-hc

**Comment by nagpai** [comment]
35985044-hc

**Comment by cpapazoglou** [comment]
Closing this, as it doesn't fall in into the guiding principles of untangling Calypso fsHM7-p2
