### ISSUE TITLE
Generated design picker: Make mobile thumbnails auto-scroll on hover/press

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64390]
## Description
We want to make mobile thumbnail's image to auto-scroll while being hovering/pressed. This is so that the user is able to easily preview the design without needing to click the thumbnail and entering the preview mode. See recording for the expected behavior:

https://user-images.githubusercontent.com/797888/172279881-d5fa0955-b801-42ab-a4dc-d17a65f7f3ef.mp4

## Acceptance Criteria
- [ ] Mobile thumbnail image auto-scrolls when mouse cursor hover over it.
- [ ] Mobile thumbnail image auto-scrolls when user presses it.
- [ ] Auto-scroll should scroll through the design entirely from top to bottom.

**Comment by arthur791004** [comment]
I think hovering/pressed might be not easy to know or use on mobile. Maybe we can auto-scroll the first thumbnail that is fully in the viewport. What do you think?

**Comment by taipeicoder** [comment]
Sorry, I meant to say scroll the thumbnail design while the user has their finger pressed. This idea was from the design spec:
![Screen Shot 2022-06-07 at 10 48 30 AM](https://user-images.githubusercontent.com/797888/172285470-f49bb950-ff11-4a6a-ac83-720928057aaa.png)

I think auto-scrolling the first thumbnail is a good visual guidance that the thumbnails are scrollable 👍 
My concern is that some users might think it's a bug, maybe I'm overthinking it!
cc: @saygunnyc

**Comment by roo2** [comment]
For reference we implemented scroll on hover in the preveiws in the `/new` flow already. https://wordpress.com/new

**Comment by taipeicoder** [comment]
> For reference we implemented scroll on hover in the preveiws in the `/new` flow already. https://wordpress.com/new

Yes! The component we're using already [supports](https://github.com/Automattic/wp-calypso/blob/e9d2f791cb8f207a10f80e251cec8e309e5d1963/packages/onboarding/src/mshots-image/index.tsx#L13) as `scrollable` prop. This task is mostly about making sure it works with the generated design picker's layout/CSS and that the scroll covers the entirety of the design.

**Comment by autumnfjeld** [comment]
My comments below are for viewing this feature on a **mobile device**:


On mobile: I just tried the wordpress.com/new flow to see how intuitive it is and it is easy to figure out that the thumbnails scroll.  Though it kind of made me dizzy.  I would set the scroll a bit slower.

It's definitely an odd feature.....personally I think clicking on it and making it open up into a full screen view on mobile device is much better:
* user gets to control scrolling up and down
* user can see more of the mobile site and it is more representative of how it actually looks on a mobile device.

Here is my experience at wordpress.com/new

https://user-images.githubusercontent.com/5665959/172338726-3b685e43-f59e-4a4a-a3b1-1636a6006795.MP4

**Comment by autumnfjeld** [comment]
This is the standard DP on mobile.  In my opinion clicking on the thumbnail should open the design full screen  or at least more full screen than is currently happening - we are wasting space

https://user-images.githubusercontent.com/5665959/172341388-3328f8d4-4b6e-4789-81e1-e17dae9f371b.MP4

**Comment by saygunnyc** [comment]
Sharing thoughts below:

> Though it kind of made me dizzy. I would set the scroll a bit slower.

💯 @autumnfjeld I think it should be much slower. I also think we should get rid of the reverse scroll animation once the user is out. It's a bit too much_–two scrolls up and down at the same time_. Instead, we could perhaps quickly fade to the initial state?


> I think auto-scrolling the first thumbnail is a good visual guidance that the thumbnails are scrollable.

I am not sure if we need this as it's to me almost impossible to not trigger the scroll as you scroll down checking the options. 


> This is the standard DP on mobile. In my opinion clicking on the thumbnail should open the design full screen or at least more full screen than is currently happening - we are wasting space

@autumnfjeld I agree, let's also create a task redesign this along with the fullscreen preview on Desktop. cc @taipeicoder

**Comment by autumnfjeld** [comment]
Closing this as there is much discussion going on with DP iterations, so we will wait for what comes next.
