### ISSUE TITLE
Generated design picker: While resizing the browser, pre-selecting a thumbnail causes layout issues in mobile view

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64401]
## Description
Currently, the generated design picker stores the last thumbnail selection so that when users re-enter the screen, they can see what they previously chose. This causes a problem where the mobile view doesn't enter the preview mode even though there is already a design selected, creating the following layout issue:

https://user-images.githubusercontent.com/797888/172325372-61784be2-7f93-428e-8056-2e68da1efd10.mp4

## Acceptance Criteria
- [x] Ensure that when a thumbnail has been explicitly selected (not selected by default), the mobile view renders preview mode.

**Comment by arthur791004** [comment]
Close it as it's shipped 🚢
