### ISSUE TITLE
Playwright: show path to the locally captured artifacts if a test fails.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#64429]
### Details

Currently, it is difficult to know which directory within `test/e2e/results` is the most recent run that failed locally.

At a minimum, print the path to the folder, either at beginning of the test or at end of the test.

### Checklist

- [ ] Investigate the file structure of `packages/calypso-e2e`.
- [ ] Identify a suitable location to make this change.
- [ ] Determine the scope of change to be made. Just a link to the folder perhaps? Or something more fancy?

**Comment by worldomonation** [comment]
@john-legg I've assigned this as the third possible piece of work you can look at.

This one is a relatively simple change, but to identify the where to add this could be challenging to figure out. After this task, you will likely have a much better understanding of how different parts of Jest interact with each other, and how we configure Jest within `packages/calypso-e2e`.

**Comment by john-legg** [comment]
The [PR](https://github.com/Automattic/wp-calypso/pull/68419) has been merged. Thanks again for the help @worldomonation and @dpasque! 😄
