### ISSUE TITLE
Launch Bar: On Atomic, the bar is visible only if the users scrolls up

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64426]
Sometimes when loading a view with the launch bar, the page is scrolled down enough to hide the launch bar behind the admin bar.

This is the same as the same bug as #58355, which has been fixed on simple sites. This issue is to address the issue on WoA sites.

Raised in this issue thread #64211. The simple site fix: D71444-code.

It's worth being aware that this fix involves rolling back another fix. The the fix we're reverting is less impactful than the one we're fixing. See the discussion in #58355.

**Comment by danielbachhuber** [comment]
Fixed with 982-gh-Automattic/wpcomsh
