### ISSUE TITLE
Blog Report Card: Allow site vertical editable by HEs

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#64436]
## Description

Currently, we show the site vertical on the Blog Report Card. We might also need to provide the ability to edit the field such as “Change Blog Vertical”. Still need a discussion on this. Maybe can only be editable for sites that do not have a vertical value

## Acceptance Criteria

- [ ] Allow the site vertical to be editable by HEs on the Blog Report Card

## Related

https://github.com/Automattic/wp-calypso/issues/62613

**Comment by autumnfjeld** [comment]
This needs a P2 and wider discussion on if we want HEs to be able to change the site vertical.   Perhaps we'd also want the user to be able to change it, for instance in my home.  Should be discussed.

**Comment by autumnfjeld** [comment]
Closing this.  Not applicable unless vertical becomes more import to user or site experience.
