### ISSUE TITLE
Marketplace: Partners Create account rebranding

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#64439]
We're rebranding the login screen in 13520-gh-Automattic/woocommerce.com but also require the same treatment to the create account flow for wpcc.

https://user-images.githubusercontent.com/811776/172550442-fdca1f7d-e975-4167-8f4d-222f73a20004.mp4

(you can ignore the woo header appearing during page load ([bug](https://github.com/Automattic/wp-calypso/pull/64362/files#r891964275)))

- [ ] Rebrand the wpcc woo branded create account step
- [ ] Remove the temporary fix put in place for the woo header text flashing mentioned here https://github.com/Automattic/wp-calypso/pull/64362/files#r893102196

See `/start/user` for design

![Screenshot 2022-06-15 at 14-55-28 Create a site — WordPress com](https://user-images.githubusercontent.com/811776/173739618-e6e20e90-feaf-45dc-bc70-60720b5c6dee.png)

**Comment by lsl** [comment]
Made a very minor start on this in https://github.com/Automattic/wp-calypso/pull/64477 branched off from https://github.com/Automattic/wp-calypso/pull/64362 while wondering if I could switch over which step styling is being applied but it looks a bit more complicated than that (the style is chosen way further up the stack and I'm hesitant to keep adding "isPartnerSignup" everywhere.

Wondering if its worth creating a separate /start/ signup flow just for this user type.

**Comment by cpapazoglou** [comment]
Closing this for the time being.
