### ISSUE TITLE
Pique > Buttons > Mobile: buttons aren't centered and text is wrapping into multiple lines

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#64431]
### Quick summary

When setting buttons to be centered on the editor, it doesn't work on smaller screens. The button text is also breaking into multiple lines.

### Steps to reproduce

1. Activate the Pique theme.
2. Create a new post or page.
3. Add the `Buttons` block, and some text and set the button to be centered.
4. Check the button on your mobile.

You should see something like this:

![IMG_A3B4A976DB4B-1](https://user-images.githubusercontent.com/50875131/172507217-055db20b-af2f-4c8f-839b-9e0ef9ba23e6.jpeg)

### What you expected to happen

I expect the buttons to be centered and a better text wrapping as there is available space within the button.

### What actually happened

Buttons aren't centered, and text is breaking into new lines earlier as it isn't using the whole available space within the button.

### Context

Customer Report: 5278468-zen

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Yes. Pique.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

This CSS code will overwrite the width limitation that the theme is creating:

```
wp-block-button a.wp-block-button__link {
  width:unset;
}
```

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context. I found another case here: https://github.com/Automattic/themes/issues/2044

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/themes/issues/2044
