### ISSUE TITLE
Snaps: Can't center Vimeo Embeds

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#64437]
### Quick summary

With the Snaps theme, a Vimeo video can't be centered even if the center alignment option is selected.

### Steps to reproduce

1. Activate the Snaps theme.
2. Create a new page.
3. Add a Vimeo block.
4. Select the center alignment option.

![Screen Shot on 2022-06-08 at 14:04:20](https://user-images.githubusercontent.com/32432463/172535779-2b8e14fa-5fa9-4922-8f3d-c82eb99931ce.png)

### What you expected to happen

To have the video(s) centered.

### What actually happened

The video(s) is left-aligned. 

![Screen Shot on 2022-06-08 at 14:10:52](https://user-images.githubusercontent.com/32432463/172536450-ea4ab8f1-85e3-4154-af04-f892fad4ecf2.png)

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

We can use this CSS code as a temp fix but we can offer CSS only to limited customers. 

```
.embed-vimeo iframe {
    margin: 0 auto !important;
}
```

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - no

📌 FINDINGS/SCREENSHOTS/VIDEO
- Context. I'm not able to replicate this and alignment worked ok regardless of the option.  Here's the center-aligned option:

![image](https://user-images.githubusercontent.com/6737345/173901319-28cf1d18-79a3-4438-bf60-3010fbde8b35.png)


📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs


📌 Message to Author
 - Please reopen if it's still an issue.
