### ISSUE TITLE
Stats - Sudden spike on the number of Views in one day from one country (Russia)

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#64432]
### Quick summary

We couldn't determine how this site received a sudden spike on the number of views from Russia on June 7, 2022. 

<img width="874" alt="Screen Shot 2022-06-08 at 09 22 25" src="https://user-images.githubusercontent.com/9984867/172512624-e9088fb4-8414-4226-bc56-d1e76dabec63.png">

Page Views, Link Clicks and Referrers are all less than 100. 

<img width="1034" alt="Screen Shot 2022-06-08 at 09 38 35" src="https://user-images.githubusercontent.com/9984867/172512827-8023369d-6ac1-4389-99bf-31f9ecb48997.png">

Author Views is 1K+, but the user is not from Russia. 

-----

URL - auntiemoon.com
HC- 35686202
ZD-5279360

### Steps to reproduce

1 . Head to Stats in the WordPress.com dashboard;
2. Go to the date - June 7, 2022. 

### What you expected to happen

View stats that match the page views. 

### What actually happened

Seeing unusual number of views from specific country - Russia

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by bazza** [comment]
If the site is not private then it can receive traffic from anywhere in the world without any need for permission or explanation. 
 As such, I don't think this is a valid bug report.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 ACTIONS
- Closing per comment above.
