### ISSUE TITLE
Vertical question screen: Dropdown is cut-off in mobile view

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64441]
## Description
The vertical question screen dropdown can be too tall for smaller mobile devices, causing some dropdown options hard to select. Also, option text colors are blue instead of the design spec: 42PgVsdlQ1v2wpk6lmmrnq-fi-1334%3A44563 

See recording:
https://user-images.githubusercontent.com/797888/172563992-3c9d0ccc-f30f-45e9-a1e0-58c9083b260f.mp4

## Acceptance Criteria
- [x] The suggestion dropdown should have a maximum height relative to the viewport, and scrollable if exceeds it.
- [x] The option text color should be as per design spec.

## Dev Tasks

- [x] https://github.com/Automattic/wp-calypso/pull/64485
- [x] https://github.com/Automattic/wp-calypso/pull/64572

**Comment by arthur791004** [comment]
Hmmm...it might still be not easy to use on mobile devices. For example, if the height of the dropdown list is related to the viewport, it will only show 3 suggestions in the viewport at the beginning. And when the user scrolls down, we might need to adjust the height to show more results. Also, there is a virtual keyboard on the mobile device when you focus on the search input and I remember that the viewport won't change at that time 🥲

<img src="https://user-images.githubusercontent.com/13596067/172803023-c793e92e-f0d3-4432-953c-2d5e847d2de5.png" width="300" />

Maybe we have to show the full-screen search input and suggestion list like what google does in the future. But it might be more complicated. What do you think? cc @saygunnyc 

https://user-images.githubusercontent.com/13596067/172800709-b427ad5f-3b3f-48e9-8c6a-82166d54aa80.mp4

**Comment by arthur791004** [comment]
I propose a quick fix to adjust the height of the dropdown based on the visual viewport. See https://github.com/Automattic/wp-calypso/pull/64485

**Comment by arthur791004** [comment]
Close it as all of the tasks are done 🎉

**Comment by saygunnyc** [comment]
> See https://github.com/Automattic/wp-calypso/pull/64485

This is great for now. The Google example is def a better mobile user experience. Let's work on improving after the MVP.  I will provide designs.
