### ISSUE TITLE
Jetpack Social: make confirmation dialog more compact

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#64452]
Upon selecting a social media account and giving permissions of the app, back on Jetpack cloud, this is the confirmation dialog:

![image](https://user-images.githubusercontent.com/390760/172640682-de4d071f-8106-45d9-9efb-1d9f719bc3f9.png)

The modal is very large right now, taking almost the entire available width. We should make that more compact.

**Comment by gmjuhasz** [comment]
Hey @keoshi, do you have a recommendation for size on this?

**Comment by keoshi** [comment]
@gmjuhasz and I chatted briefly in Slack — sorry I missed your initial ping.

After a quick investigation it seems that we don't have any internal standardized sizes for modals, but other solutions like Boostrap [document a few](https://getbootstrap.com/docs/4.2/components/modal/#optional-sizes).

`800px` seems to hit a sweet spot and Gergely found a few instances across the code, so we agreed to go with that.
