### ISSUE TITLE
Update  isEligibleForProPlan selector to check if siteId is Pro as well

### ISSUE THREAD

**Issue by gmovr** [Automattic/wp-calypso#64450]
We should update [the selector](https://github.com/Automattic/wp-calypso/blob/7230004683df9f72426fb675298801fba91f3da0/client/my-sites/plans-comparison/is-eligible-for-pro-plan.ts#L7-L17) ` isEligibleForProPlan` to also return `true` if the current site is on a pro plan. 

As an extra check, to not just rely on the `isEnabled( 'plans/pro-plan' );`

**Comment by gmovr** [comment]
cc: @cpapazoglou

**Comment by claudiucelfilip** [comment]
Changes have been pushed to: https://github.com/Automattic/wp-calypso/pull/64457
