### ISSUE TITLE
Stepper: Create an hook to redirect users

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#64459]
We should have a hook to redirect the user instead of repeating the function in every component that we need it.

https://github.com/Automattic/wp-calypso/blob/ae525099b3679d28f330562d36e5c8d8af7547ba/client/landing/stepper/declarative-flow/internals/steps-repository/woo-verify-email/index.tsx#L15-L17

**Comment by markbiek** [comment]
@valterlorran There are a few places where we wouldn't be able to use a hook (like `anchor-fm-flow.ts` and `site-setup-flow.ts`).

What do you think about if we add a redirect function to one of the existings packages in `calypso/lib`? Maybe in the `navigate` package?

**Comment by valterlorran** [comment]
I think it's a great idea 👍

**Comment by markbiek** [comment]
Oh, wait! There's already a `redirect` function in `steps-repository/import/util.ts` that we can use!
