### ISSUE TITLE
Jetpack NUX: notification for successful first backup

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6446]
To round-out the Jetpack Plans purchase flow, after VaultPress is auto-configured, it would offer nice peace of mind if we fired off a WordPress.com notification letting the user know that their first backup completed successfully. 

cc @ryelle

**Comment by rickybanister** [comment]
@MichaelArestad obviously this ticket is not going to be relevant with Rewind, but let's make sure we have some similar mechanism in place.

**Comment by MichaelArestad** [comment]
@rickybanister already implemented.
