### ISSUE TITLE
[Bug]: Theme Showcase: "Free" and "Premium" filters are not selected when page is loaded by direct link

### ISSUE THREAD

**Issue by wojtekn** [Automattic/wp-calypso#64479]
### Quick summary

We can use a filter to switch between Free and Premium themes on the Theme Showcase page. There is also an option that allows showing All themes. The filter works well - when it's clicked, the URL of the page changes, the themes are filtered according to the selection, and the proper filter is marked as active. However, the filter is not marked as active when the pre-filtered page is loaded directly.

### Steps to reproduce

1. Navigate to `/themes/premium/{SITE_URL}` or `/themes/free/{SITE_URL}`

### What you expected to happen

* "Premium" or "Free" filter is marked as active accordingly

### What actually happened

* "Premium" (or "Free") filter is not marked as active and the "All" filter is marked as active each time

### Context

Brought by @andres-blanco under https://github.com/Automattic/wp-calypso/pull/64221

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jordesign** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/64222
