### ISSUE TITLE
Marketplace: Edit marketplace CTA on /marketing/tools

### ISSUE THREAD

**Issue by vinimotaa** [Automattic/wp-calypso#64474]
This is a quick fix on the Marketplace CTA on /marketing/tools.

_Current design:_
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/97929097/172737713-c37ee133-3444-4949-b4a8-e14a8dc4dbf1.png">

1 - We need to change the title colour from this light grey to #101517
2 - We need to replace this illustration. The new one can be [found here](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=1601%3A13181)

_Expected design:_
<img width="915" alt="image" src="https://user-images.githubusercontent.com/97929097/172738387-41a58edc-adf0-49bc-96c4-21058397bc58.png">

Here is the Figma file:
https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5?node-id=593:12805#176135037

**Comment by allilevine** [comment]
Thanks @vinimotaa! Added this to our next sprint items.

**Comment by lsl** [comment]
- Assuming the button color should remain the same (based on user theme selection).
- #101517 == `--studio-gray-100`
- Image:
![Frame](https://user-images.githubusercontent.com/811776/173480767-e9c2e2e9-41b8-4767-9afd-58f792bf804d.svg)

**Comment by allilevine** [comment]
We missed a change here, or maybe we weren't ready to add it yet: `shipment tracking` should be `SEO tools`.
