### ISSUE TITLE
Vertical Question Screen: Update copy above the verticals list input field

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#64489]
# Description
Part of Verticals in Onboarding project.
See slack convo: p1654780247602049/1654775253.343659-slack-CRWCHQGUB and CfT feedback pdtkmj-ba-p2

Let's make it clear to users they can both type and select in this input field:
![image](https://user-images.githubusercontent.com/5665959/172855959-39ceadfc-368c-445b-ac80-4544ddbc1054.png)

<img width="976" alt="image" src="https://user-images.githubusercontent.com/5665959/172856094-209a46bb-b4ab-4fe6-bb2b-702ac2df8143.png">

Project Thread: pbxlJb-XO-p2

# Acceptance Criteria
- [x] Check with @saygunnyc for ideas to update the copy above the input box
- [ ] Approved by Saygun

# Dev Tasks
- [x]  https://github.com/Automattic/wp-calypso/pull/64728

## Related

**Comment by saygunnyc** [comment]
I have 3 suggestions to make it more obvious that the user can type.
1. Start typing to find your category (This feels a bit like the user has to type)
2. Search for a category (This feels most natural)
3. Type in/select a category (This looks clear however they better eventually select one and not just type in)

![01](https://user-images.githubusercontent.com/78876323/173919877-dd33ce7b-8df1-40aa-a5bb-2860d957ccfc.png)
![02](https://user-images.githubusercontent.com/78876323/173919879-637d0afb-00b3-472e-b49f-20b971e887c3.png)
![03](https://user-images.githubusercontent.com/78876323/173919880-e64e8b4f-d3d8-4880-b13e-9f8fa1519254.png)


I'm leaning towards 3 or 2. Let me know which one you are leaning towards. @taipeicoder @autumnfjeld

**Comment by taipeicoder** [comment]
Personally, I like the simplicity of 2, but I feel that we will have to make it extra obvious to the customers that they can type in. Option 3 gets my vote. @roo2 @arthur791004 @miksansegundo  @bangank36 let me know what you think!

**Comment by arthur791004** [comment]
I'm leaning towards 2. And maybe we can change the placeholder of the input to 1 to let users know they can type in!

**Comment by saygunnyc** [comment]
> placeholder of the input to 1 to let users know they can type in!

Let's keep it as that's the only place we give users an idea about what they can write _–Cafes, Education, Photography..._ Ideally we update these with top selected categories.

**Comment by miksansegundo** [comment]
My vote is for option 2 because `Search for` sounds very common for a search box.

Maybe it could sound more engaging by using _your_ in `Search for your category`.

**Comment by taipeicoder** [comment]
How about we go with option 2 and also consider @roo2 suggestion of highlighting the input field text on focus, and even when users click on the chevron to show the dropdown?

**Comment by autumnfjeld** [comment]
My vote is also 2 : "Search for a category"

Remember that thing called Google 🤣 , it's called search, and it is all about typing stuff in.  So search seems an appropriate word.

A blinking cursor (or a static cursor) in the input field is a good indicator that the field can take typed input.

**Comment by arthur791004** [comment]
I think we can go with option 2 and see is there any further feedback!

> also consider @roo2 suggestion of highlighting the input field text on focus, and even when users click on the chevron to show the dropdown?

I think maybe we don't need the chevron icon as the suggestions will show automatically when you focus on the input 🤔

**Comment by autumnfjeld** [comment]
I believe this issue is `In Progress` so moving it out of `Ready for Dev`

**Comment by arthur791004** [comment]
@saygunnyc As most of us are leaning toward option 2, so I've shipped with "Search for a category". Let's see if any feedback!

**Comment by arthur791004** [comment]
Close it as it's shipped!

**Comment by saygunnyc** [comment]
2 is the right choice. Thanks for participating all! 😄
