### ISSUE TITLE
Preview button on My Sites can cause shares to come from different URL

### ISSUE THREAD

**Issue by ashercantrell** [Automattic/wp-calypso#6449]
The Preview button (previously the Home button) on the My Sites menu can mess with sharing to social networks on sites with custom domains.

**Steps to reproduce**
1. Starting at URL: WordPress.com/posts (or any other Calypso dashboard page)
2. Click blavatar, which turns into a Home icon
3. Preview pane loads
4. Click a sharing button

**What I expected**

Post/page shares to Facebook/Twitter/etc. from mygroovysite.com/2016/06/30/example-post/

**What happened instead**

Post/page shares to social network from https://mygroovysite.wordpress.com/2016/06/30/example-post/?iframe=true&theme_preview=true&share=facebook&nb=1 (Replace facebook with whichever social media site)

**Context / Source**

Users with custom domains are likely to expect always seeing their custom domain instead of their .wordpress.com address. Users who are unfamiliar with their .wordpress.com address might be alarmed by this and think something is wrong. A lot of users are also not familiar with the Preview window yet and are still used to clicking the Home icon to open their site.

**Comment by lancewillett** [comment]
Thanks for the feedback.
