### ISSUE TITLE
Reader: Remove from list option from within the stream with an option in popup menu

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#645]
Raised by @shaunandrews 

> I've got a Reader list called "comics," that I've been reading for a few weeks. There's a site I want to remove from this list after I notice a bunch of non-comic posts. It'd be great if I could do this right in the stream with an options in this menu:

<img width="705" alt="screen shot 2015-09-18 at 2 29 54 pm" src="https://cloud.githubusercontent.com/assets/191598/9967645/d380c292-5e11-11e5-8700-a312bb8cbf53.png">

Something like this:

![screen shot 2015-09-25 at 10 23 02 am](https://cloud.githubusercontent.com/assets/191598/10102981/7cd07d76-636f-11e5-8a4c-e8227d46323c.png)

**Comment by alisterscott** [comment]
Lists are unavailable for customers without lists, and existing lists users can't manage these lists any more, so closing this issue as no longer applicable. See `p5PDj3-1Fg-p2`
