### ISSUE TITLE
Add `--force` option to the `wp headstart run` command

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#64507]
### Details

Let's add `--force` option to `wp headstart run`. 

Specifying this option will allow running headstart on theme demo sites.

If `--force` is present, we should let the user know which applicable target checks are being skipped and ask for additional confirmation.

See `class-headstart-helpers.php` line 131 for where the check is occurring.

**Comment by andres-blanco** [comment]
Closed by D82626-code
