### ISSUE TITLE
AMP: Update support docs after feature is removed

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64516]
The support site has a page about AMP.
https://wordpress.com/support/amp-accelerated-mobile-pages/

The page is split into two sections: one for managing AMP on Simple sites, and one for managing on WoA.

Once AMP has been removed from Simple sites we need to update the support site to reflect this.

**Comment by p-jackson** [comment]
Change request has already been made: 1603-gh-Automattic/en.support-docs-content 🎉

**Comment by wojtekn** [comment]
@p-jackson changes are live now 🙂

**Comment by p-jackson** [comment]
🥳
