### ISSUE TITLE
Marketplace: Replace form and update contact us in Partners landing page

### ISSUE THREAD

**Issue by lupus2k** [Automattic/wp-calypso#64512]
Let's check how we can update https://wordpress.com/partners/ to match Figma design
Figma: SJ6I0rUUtHNdHMF2KMMJig-fi-456%3A10269

Changes here: D82360-code

#### Screenshot
![image](https://user-images.githubusercontent.com/1044309/170585491-0911f60f-e815-4eb0-9d40-aa818e993106.png)

#### Tasks
- [ ] The contact form has been replaced images seen in design [above](https://github.com/Automattic/wp-calypso/issues/61032#issuecomment-1139087070)
- [ ] Contact us copy has been replaced, with new CTA section header and link to https://woocommerce.com/partner-signup

Related to #61032

**Comment by lupus2k** [comment]
Hey, @SaxonF or @vinimotaa can you provide us both images from the new section for retina devices? If I export them from Figma there are small for retina devices.

I already uploaded 2x images but are just resized from the original and don't look good on retina.

**Comment by cpapazoglou** [comment]
Closing this for now.
