### ISSUE TITLE
Clicking "Upgrade to the Pro Plan" banner on "Settings -> Hosting Configuration" unexpectedly ends up in Site Switcher

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#64527]
### Quick summary

When I click on the "Upgrade to the Pro Plan" banner on "Settings -> Hosting Configuration":

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/36432/173118505-1c76584a-034d-4b4c-81ba-b38864288f3a.png">

I unexpectedly see "Select a site to open Checkout":

<img width="689" alt="image" src="https://user-images.githubusercontent.com/36432/173118579-5f89ec6e-caa3-48db-a746-c9e99a335e09.png">

I expected to end up in the checkout flow.

Notably, the banner URL is `https://wordpress.com/checkout/<blog-id>/pro`, so not sure what's happening there.

### Steps to reproduce

1. Create a new Starter site.
2. Navigate to "Settings -> Hosting Configuration".
3. Click on the "Upgrade to the Pro Plan" banner.

### What you expected to happen

I expected to already be on the checkout page for the site.

### What actually happened

I ended up on the Site Switcher, where I needed to re-select my site.

### Simple, Atomic or both?

Simple

**Comment by gmovr** [comment]
This is true for all plans -- I was noticing it the other day. The site (current site) has to be passed in, example below:

https://wordpress.com/checkout/site.wpcomstaging.com/pro

I think it's just this CTA (I went through ~~all~~ the ones I could find the other day). :)

**Comment by danielbachhuber** [comment]
@gmovr Do you think fixing this will be impacted by the plan changes, or is it safe to prepare the fix at this time?

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT - N/A
- Tested on Self-hosted - N/A

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested clicking the "Upgrade to the Pro Plan" banner on "Settings > Hosting Configuration" on a site with the free plan, Starter plan, and Premium plan. In each case, I was taken to the site switcher. This did not happen on other pages like the Plugins page. 
- I'm also not sure if this will be affected by upcoming changes as mentioned in [this comment](https://github.com/Automattic/wp-calypso/issues/64527#issuecomment-1157671955), but marking as triaged for now for further review.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by gmovr** [comment]
@danielbachhuber -- Yes, it will (the name of the plan), but we can still fix this prior. It will work if we later decide to set it ot a legacy plan. 👍 

cc: @chickee0311  Can you take a look at this one? We'll sort it for the Pro plan for now. I _think_ just removing the `href` prop will then default to the Pro plan, but I haven't looked too closely.

**Comment by creativecoder** [comment]
👋🏼 this looks like a good "first issue" for a new developer on my team, so I'd like to have @mpkelly take this on, if you don't mind!

**Comment by danielbachhuber** [comment]
Thanks for the assist, @mpkelly !
