### ISSUE TITLE
Block Widget: text in block layout is stretched when in mobile layout 

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#64535]
### Quick summary

The block inserter in Block Widget editor is poorly formatted and difficult to use when in mobile layout.
![Screen Shot 2022-06-10 at 12 56 44 PM](https://user-images.githubusercontent.com/6549265/173141927-dc0bbe94-77cd-4c4e-b0d0-d18ca4d5abce.png)

### Steps to reproduce

prereq. use a mobile device or mobile layout emulation in Developer Tools.
1. log in.
2. navigate to Appearance > Widget.
3. click on the `+` button twice (which is a separate bug on its own filed in https://github.com/Automattic/wp-calypso/issues/64536).

### What you expected to happen

The block inserter is similar to the one shown in the Editor when drafting a new post/page.

![Uploading image.png…]()

### What actually happened

The block inserter only takes up the left 20% of the page, resulting in text label for every block item being compressed vertically.

### Context

Manual testing.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

### Workaround details

Workaround is to use the Desktop viewport.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- while triaging https://github.com/Automattic/wp-calypso/issues/64536 , I can see that the issue reported here is no longer occurring.

https://github.com/Automattic/wp-calypso/assets/27249804/4e4b8b88-c22b-421d-8894-11b9c91768d1

📌 ACTIONS
- Closed as could not replicate
