### ISSUE TITLE
Bell notifications: Newly published posts show in full

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#64558]
### Quick summary

If you're subscribed to a blog, and not set to be notified about the new posts, the notifications will show the post in full even.
It'll show in full even if the More block is used, or if the theme has excerpt by default (like Barnbsbury)

I'm not sure if this is a bug or should be a feature request.

Some ideas for improvements:

* Have Reader option to only show excerpts in the notifications
* Have the notifications respect the excerpt settings of the post

### Steps to reproduce

1. Follow one of your test site
2. From test site, publish a new post
3. Check the bell notification

### What you expected to happen

To only see an excerpt of the new post.

### What actually happened

Full post shows:
![image1](https://user-images.githubusercontent.com/15944096/173223516-8d652cda-d4c0-4a50-a540-7dcf61cf515e.png)

### Context

5288573-zd-woothemes

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - not tested

📌 SCRUBBING

- Tested on Simple ✅ 


📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm unable to replicate this at the moment on my end on Simple sites.

📌 ACTIONS
- Await author feedback


📌 Message to Author
 - Could you share more details about the testing sites used and the notification settings at the time? Also, has the follower  subscribed through the email or using the action bar?

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Closing report due to stale conversation. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
