### ISSUE TITLE
Legacy widgets: Follow Blog is missing

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#64559]
### Steps to reproduce

In widgets, search for `Legacy` or add a `Legacy Widget` block, look for Follow Blog ([see doc](https://web.archive.org/web/20211027085408/https://wordpress.com/support/widgets/follow-blog-widget/)).

### What you expected to happen

Follow Blog should be in the options, although not sure if it's missing on purpose.

### What actually happened

Follow Blog is missing.

![image1](https://user-images.githubusercontent.com/15944096/173226633-86177193-4966-46b7-bac8-5bb4fb3aaf04.png)

### Context

Noticed in 5190440-zd-woothemes

### Workaround details

* Option 1: Use Follow Button block.
* Option 2: Paste the code for Follow Blog:

`<!-- wp:legacy-widget {"idBase":"blog_subscription","instance":{"encoded":"YTo2OntzOjU6InRpdGxlIjtzOjIxOiJGb2xsb3cgQmxvZyB2aWEgRW1haWwiO3M6MTU6InRpdGxlX2ZvbGxvd2luZyI7czoyNzoiWW91IGFyZSBmb2xsb3dpbmcgdGhpcyBibG9nIjtzOjE0OiJzdWJzY3JpYmVfdGV4dCI7czo5MzoiRW50ZXIgeW91ciBlbWFpbCBhZGRyZXNzIHRvIGZvbGxvdyB0aGlzIGJsb2cgYW5kIHJlY2VpdmUgbm90aWZpY2F0aW9ucyBvZiBuZXcgcG9zdHMgYnkgZW1haWwuIjtzOjE5OiJzdWJzY3JpYmVfbG9nZ2VkX2luIjtzOjc0OiJDbGljayB0byBmb2xsb3cgdGhpcyBibG9nIGFuZCByZWNlaXZlIG5vdGlmaWNhdGlvbnMgb2YgbmV3IHBvc3RzIGJ5IGVtYWlsLiI7czoxNjoic3Vic2NyaWJlX2J1dHRvbiI7czo2OiJGb2xsb3ciO3M6MjI6InNob3dfc3Vic2NyaWJlcnNfdG90YWwiO2I6MTt9","hash":"4221063f057a22c965fe964f4df4e3ab","raw":{"title":"Follow Blog via Email","title_following":"You are following this blog","subscribe_text":"Enter your email address to follow this blog and receive notifications of new posts by email.","subscribe_logged_in":"Click to follow this blog and receive notifications of new posts by email.","subscribe_button":"Follow","show_subscribers_total":true}}} /-->`

**Comment by Robertght** [comment]
The Follow Blog widget was retired a while back and we have a PR in place here:

https://github.com/Automattic/jetpack/pull/21184/

pdf5j4-4C-p2
