### ISSUE TITLE
Add Block modal from the + icon in the Editor does not load properly on mobile view 

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#64551]
### Quick summary

The Add Block modal that opens up on clicking + icon on the browser does not show properly. The issue can be reproduced in mobile browsers or by resizing desktop browser when in the editor.the 

### Steps to reproduce

1. Open WordPress editor in a mobile browser or desktop browser resized to mobile widths.
2. Click on + icon on the editor.
3. You will notice that the Add Block modal is congested.

Screen recording:

![Screen Capture on 2022-06-11 at 10-50-52](https://user-images.githubusercontent.com/33957570/173174021-724bd7b9-15d3-4433-bcd1-dc426ed8d12a.gif)

### What you expected to happen

The Add Block modal should load properly.

### What actually happened

The Add Block modal was congested.

### Context

User report: 5282388-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

I was able to confirm on following browsers.

Google Chrome 102.0.5005.98 Android 12
Google Chrome 102.0.5005.61 macOS Monterey

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Use the + icon on the top left corner.

**Comment by renata-franco** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate this issue on WordPress.com, but not on Self-Hosted. The Self-Hosted site loads the block differently. See GIF below. It has an easy workaround: installing the app and adding the blocks from there. Screenshot below. I used Firefox 100. 

**WordPress.com app**

![image](https://user-images.githubusercontent.com/81378719/174107377-64786eae-934d-4760-ab89-b06ec9432edf.png)


**Simple Site**
![image](https://user-images.githubusercontent.com/81378719/174105662-23c659ec-1492-48d5-8095-87ae8f20ed83.png)


**AT Site**
![image](https://user-images.githubusercontent.com/81378719/174105540-391c120f-76e7-429c-bc76-e56c848f265b.png)

**Self-Hosted**

![CleanShot 2022-06-16 at 17 29 22](https://user-images.githubusercontent.com/81378719/174106079-736b914d-b34b-4d5e-8940-3a0a283b6016.gif)





📌 ACTIONS

- Marked as Triaged for Quality Squad review.

**Comment by jordesign** [comment]
Hey @renata-franco  - could you please clarify what you mean by 'core but not self-hosted' ?

**Comment by renata-franco** [comment]
> Hey @renata-franco - could you please clarify what you mean by 'core but not self-hosted' ?

I wrote that incorrectly. I meant: 

`I was able to replicate this issue on WordPress.com, but not on Self-Hosted`


I've updated the comment.

**Comment by jordesign** [comment]
Awesome - thanks Renata :)

**Comment by agrullon95** [comment]
I tested on Simple Site + Atomic Site and was not able to replicate this issue:

Simple Site: 

<img width="560" alt="Simple Site - FSE Add block" src="https://user-images.githubusercontent.com/10482592/197803886-464b2fc2-b8a1-45c0-b379-c49a6e523ab4.png">


Atomic Site: 

<img width="515" alt="Atomic Site - FSE Add block" src="https://user-images.githubusercontent.com/10482592/197803913-09411846-1660-466b-8206-71e6dbc19834.png">

I will close this issue. We can reopen this if the issue reoccurs.
