### ISSUE TITLE
FSE Welcome Tour reopens after page refresh

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#64555]
### Quick summary

When on a simple site with a WordPress.com Pro plan, the Welcome Tour modal will re-open when the page is refreshed, regardless of how it is closed.

### Steps to reproduce

1. Create a new site with a WordPress.com Pro plan
2. Set the site theme to an FSE theme
3. Go to `Appearance > Editor`
4. Close the Welcome Tour modal
5. Refresh the page, with or without making changes to the template you're working on

### What you expected to happen

I would expect that the Welcome Tour modal would recognize that I've closed it, and wouldn't reappear when the page is refreshed, which is what happens when the site is AT'd

![2022-06-11 15 39 36](https://user-images.githubusercontent.com/4000628/173202611-b825737e-28ee-4a61-bf68-e973f61f6e75.gif)

### What actually happened

The Welcome Tour modal re-opens every time you refresh the page

![2022-06-11 15 37 21](https://user-images.githubusercontent.com/4000628/173202658-5caff8b7-525a-4a9c-a488-ca393d3d2e4c.gif)

### Context

5289290-zen

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by arunsathiya** [comment]
- I'll close this as we are tracking this here already: https://github.com/Automattic/wp-calypso/issues/57660
- There's also this one that feels like a larger issue: https://github.com/Automattic/wp-calypso/issues/64324
