### ISSUE TITLE
Notifications: in Classic View, the orange dot shows even when there's no Unread

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#64568]
### Quick summary

![image1](https://user-images.githubusercontent.com/15944096/173311406-7dec84f9-0f5d-492a-bfb6-1ceee6e6deec.png)

I'm not sure if the orange dot is controlled in Calypso or Jetpack, searching for `<span id="wpnt-notes-unread-count"` doesn't yield a clear answer, https://github.com/search?p=1&q=org%3AAutomattic+wpnt-notes-unread-count&type=Code

Pinged on Slack for more pointers: p1655178888761399-slack-C0CMN0V97

### Steps to reproduce

Can't reproduce on own site, can only reproduce on user's site (5289834-zd-woothemes).

Go to the Posts page, switch between Classic and Default view.

### What you expected to happen

Bell should only show orange dot if there's new notifications.

### What actually happened

The orange dot shows all the time in Classic view.

### Context

Ticket: 5289834-zd-woothemes

**Comment by Joshgrygiel** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Tested on User Site  ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I could not validate this issue on either my test sites or on the user's site through the Classic View:

![Annotation on 2022-06-14 at 12-17-15](https://user-images.githubusercontent.com/88345647/173638060-5e98d6ad-8796-4429-9d9e-662c0d21f07c.png)

📌 ACTIONS

- Closed as could not replicate, please reopen this issue if it reoccurs

📌 Message to Author - @formosattic I could not recreate the issue on the user's site or on any of my test sites. I switched to the "Classic View" on the pages/posts page, and accessed the /wp-admin view directly and did not see the orange notification alert on my end.

**Comment by youbrokesomething** [comment]
I can't reproduce this issue, please re-open if a user experiences this issue again.
