### ISSUE TITLE
Exiting editor results pages/posts show in classic view despite user preferences

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#64561]
### Quick summary

When a user edits their pages/posts from Calypso, and then chooses to close the editor, they are returned to the _classic view_. This is despite their preference set to _default view_.

https://user-images.githubusercontent.com/39252765/173252434-daea1cb5-2918-48f7-9fae-aec6cd40bf2c.mp4

### Steps to reproduce

1. Browse pages/posts in the default view (i.e. Calypso)
2. Edit a post
3. Exit the editor
4. Observe that the pages/posts screen is now in classic view (i.e. wp-admin)

Note: couldn't reproduce on my own test AT site. 

### What you expected to happen

I expected to return to the default view.

### What actually happened

I found myself in the classic view, despite setting preferences otherwise. 

### Context

5291550-zen

### Theme-specific issue?

Twenty Fifteen

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on AT ✅ 


📌 FINDINGS/SCREENSHOTS/VIDEO
- Seems like it's indeed an issue only on some sites only. Closing in favor of https://github.com/Automattic/wp-calypso/issues/49486

📌 ACTIONS
- Closed as duplicate of #49486
