### ISSUE TITLE
Theme Editor: Broken image icon appears before emojis when Syntax Highlighting is enabled

### ISSUE THREAD

**Issue by zyousafi** [Automattic/wp-calypso#64560]
### Quick summary

When using the Theme Editor on a WordPress.com site, emojis appear but they show a broken image icon before the emoji itself in the editor.  This only happens when **Syntax Highlighting** has been enabled via the `wp-admin/profile.php` page  Here's an example of what that looks like:

![Google Chrome 2022-06-06 000453](https://user-images.githubusercontent.com/36741730/173235313-fb69687a-e5fc-43ca-ba8f-1e58c5a5f241.jpeg)

This does not happen on a self-hosted WordPress.org site:

<img width="1145" alt="Screen Shot 2022-06-12 at 14 11 29" src="https://user-images.githubusercontent.com/36741730/173235607-77bca5aa-d1cc-403a-9b8f-f8e28287f198.png">

### Steps to reproduce

1. On a WordPress.com site, navigate to `wp-admin/profile.php` in the dashboard and enable **Syntax Highlighting**
2. Navigate to `wp-admin/theme-editor.php` in the dashboard, and add an emoji in the editor for any file you've picked from the available options in the sidebar

### What you expected to happen

I expected an emoji to show up without the broken image icon as is the case on a self-hosted WordPress.org site.  Please see the screenshot here:

<img width="1145" alt="Screen Shot 2022-06-12 at 14 11 29" src="https://user-images.githubusercontent.com/36741730/173236346-48e2ea65-da3f-4550-9607-67de69f8e5cb.png">

### What actually happened

The emoji showed up immediately following a broken image icon.  Please see the screenshot here:

![Google Chrome 2022-06-06 000453](https://user-images.githubusercontent.com/36741730/173236276-71bc27a6-8f15-4ad7-a927-b57e81c7336c.jpeg)

### Context

Customer report

### Browser

Google Chrome/Chromium

### Simple/Atomic

Atomic

### Other notes

Upon further inspection, the broken image icon seems to be coming from here: `https://twemoji.maxcdn.com/v/14.0.2/1f44b.svg`

This is a 404 in the **Twemoji** library.  It seems, by default, that the **Twemoji** library is available on self-hosted WordPress.org sites but not WordPress.com site

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

On a WordPress.com site, navigate to `wp-admin/profile.php` and enable the **Disable syntax highlighting when editing code** setting.  The downside is that **Syntax Highlighting** is disabled, but emojis do appear without broken image icons

**Comment by connorhipps** [comment]
The user returned to chat for an update on this. It appears that the issue continues. 36003487-hc

I've created a follow-up ticket for us to update the user once we have a fix. 5359647-zd-woothemes

**Comment by pauljacobson** [comment]
I encountered a similar report, and opened a related issue here: https://github.com/Automattic/wp-calypso/issues/71697

**Comment by the-misha** [comment]
User in 5829864-zen has provided additional comments with their observations.

**Comment by cuemarie** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/71697
