### ISSUE TITLE
AMP: Redirect legacy AMP URLs to their non-AMP equivalent

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#64579]
Unfortunately, WordPress' canonical redirect doesn't handle automatically redirecting AMP URLs to their non-AMP equivalents.

Thus, we'll need to write some code to redirect legacy AMP URLs to their non-AMP equivalents (e.g. `/2012/08/09/hello-world/amp/` -> `/2012/08/09/hello-world/`).

To make matters more challenging, we'll need to support the various permalink structures WordPress supports.

A clever solution might be to:
1. If a site previously had AMP enabled, re-register the AMP rewrite rules.
2. Use the presence of the rewrite rule match to identify a URL that might need to be redirected.

Also, to protect against SEO problems, we should probably run this as a 302 redirect for a week or two, before making it a 301 redirect.

**Done is:**
* On a site that previously ran AMP, legacy AMP URLs redirect to their non-AMP equivalents.

**Comment by p-jackson** [comment]
Thanks for testing! This is definitely not something we want to happen. We've tested and talked about this p7DVsv-eFN-p2#comment-41061 and p58i-cbk-p2#comment-53891 and found that redirection was working on Simple sites and only Atomic was affected. But since we're not removing the plugin on existing AMP sites they wouldn't be affected.

What sort of site did you discover this on? It's not something I want to accidentally break!

**Comment by danielbachhuber** [comment]
> What sort of site did you discover this on? It's not something I want to accidentally break!

It was the first Simple site I listed in D82438-code

> We've tested and talked about this p7DVsv-eFN-p2#comment-41061 and p58i-cbk-p2#comment-53891 and found that redirection was working on Simple sites and only Atomic was affected.

It might be helpful to track down the exact code handling the redirection to confirm. When I worked on this previously (removing AMP from a VIP Go site), core didn't handle the redirect automatically, and I had to write custom code for it.

**Comment by p-jackson** [comment]
Documenting a conversation with @danielbachhuber today:
- It could be a good idea to use temporary 302s initially during the rollout phase, only switching to permanent 301s after we're 100% confident everything has gone smoothly.
- Just rendering the non-AMP version of a page at the `/amp` URL and returning 200 is a bad idea, duplicating content on a site is an SEO no no—we don't want Google to think these sites are content farms

**Comment by danielbachhuber** [comment]
Also worth noting: because we only need to set up redirects on Simple sites, and Simple sites only have one permalink structure, we can use a regex approach instead of re-registering `add_rewrite_endpoint()`. The latter would be more helpful for supporting multiple permalink structures.

**Comment by p-jackson** [comment]
Fixed in D82861-code
The reason we were seeing different redirect behaviour was that it depended on whether AMP happened to be enabled or disabled at the time it was deprecated for a particular site.
