### ISSUE TITLE
Marketplace Search API: fix locale support 

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#64571]
D81357-code is landed with the following issue:

> mixed lang results. this may be a bug, but that example is also returning title.default rather than the title_html.en which should actually be the correct locale.

We should update the endpoint to return fields with the correct locale based on the `lang` query parameter. We can validate this functionality via adding unit tests in `MarketplaceSearchTest.php`.

**Comment by cpapazoglou** [comment]
Let's test if this related diff D82452-code fixes the issue

**Comment by gcsecsey** [comment]
Currently, the translations of the multilanguage fields are added to the index, and can be queried as an object. However, fields in a given translation cannot yet be fetched. (eg. we have to select the `plugin.title.de_DE` field even if the `lang=de_DE` parameter is provided)

Eg. specifying the `plugin.title` field:

query:
`https://public-api.wordpress.com/rest/v1.3/marketplace/search?group_id=wporg&query=woocommerce&fields[0]=plugin.title&lang=fa_IR`

a result from the response:
```json
{
    "_score": 238.07642,
    "fields": {
        "date": "2019-03-27 18:09:05",
        "post_id": 98821,
        "blog_id": 108986944,
        "plugin": {
            "title": {
                "ru_RU": "WooCommerce Admin",
                "fr_CA": "WooCommerce Admin",
                "es_VE": "WooCommerce Admin",
                "fa_IR": "مدیر ووکامرس",
                "tr_TR": "WooCommerce Admin",
                "en": "WooCommerce Admin",
                "pt_BR": "WooCommerce Admin",
                "cs_CZ": "WooCommerce Admin",
                "de_DE": "WooCommerce Admin",
                "ja": "WooCommerce Admin",
                "es_MX": "WooCommerce Admin",
                "es_CO": "WooCommerce Admin",
                "es_ES": "WooCommerce Admin",
                "zh_CN": "WooCommerce Admin",
                "nl_NL": "WooCommerce Admin"
            }
        }
    },
    "result_type": "post",
    "railcar": {
        "railcar": "RAxy^&bGb$RJ",
        "fetch_algo": "marketplace:search/1-score_default",
        "fetch_position": 0,
        "rec_blog_id": 108986944,
        "rec_post_id": 98821,
        "fetch_lang": "fa_IR",
        "fetch_query": "woocommerce",
        "session_id": "sRzb6i"
    }
}
```

**Next steps**

- add the multilanguage fields to the `returnable_fields` array, to be able to query for only a given translation (eg.  `plugin\.title_html\..*`)
- add some logic to query the correct language based on the `lang` parameter: eg. if the query is `?lang=de_DE&fields[0]=plugin.title_html`, then the ES query should contain the `plugin.title_html.de_DE` field
- add unit tests for these cases

**Comment by gcsecsey** [comment]
Diff created: D83978-code

**Comment by gcsecsey** [comment]
WPCOM changes deployed: r248930-wpcom

**Comment by gcsecsey** [comment]
While working on the Calypso part, I've found out that the language codes doesn't match between Calypso and WPCOM. I've created this diff to resolve the issue: D84165-code
