### ISSUE TITLE
Marketplace search: adopt WP.org ranking

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#64573]
D81357-code is landed with the following issue:

When searching for eg. "woocommerce", the WooCommerce plugin is not being returned as the no.1 result. This is because the Jetpack Search algorithm is not the same as the search algorithm for wp.org:

> "woocommerce" not being at the top is because the Jetpack Search alg is not the same as the search alg for wp.org. We need to port this search alg: https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/libs/site-search/jetpack-search.php#L1047 However that is also heavily based on active installs which may or may not work for mixing results from WC.com and any custom WP.com plugins. I think we should do this separately though. We'll almost certainly need to iterate on the alg a fair bit over time (and add some machine learning to rerank results and increase sales), but duplicating the .org ranking is a good starting point.

As a first step, we need to replicate the ranking of WP.org.

**Comment by cpapazoglou** [comment]
Let's see if D82452-code fixes the ranking or else adjust the boost in fields.

**Comment by gcsecsey** [comment]
To be able to effectively compare results from WP.org and marketplace search, I've created a Postman collection, it can be imported by clicking to **Import -> Link** and pasting this link : https://www.getpostman.com/collections/cc97cb0fbb0475925cd0

Running the "WP.org query" request will save the list of slugs the WP.org API is returning to a collection variable. Then, running the "Marketplace search query" request will test its result against the saved variable. The search term can be updated on both queries, so we can compare multiple searches.

This way, it's easy to compare the ranking of the two APIs by looking at the Tests tab of the "Marketplace search query" request:

![Image](https://user-images.githubusercontent.com/11555574/180010072-cb8f4744-8c26-4405-9cac-4efd51b1698d.png)

**Comment by gcsecsey** [comment]
I've also looked into some differences between the two queries.

The WP.org API mainly uses a bool query:

https://github.com/WordPress/wordpress.org/blob/ebbbd4848b1302424e7b406267165d51e7c0cc63/wordpress.org/public_html/wp-content/plugins/plugin-directory/libs/site-search/jetpack-search.php#L890-L948

But it also uses a function_score query to increase the score of more recent plugins:

https://github.com/WordPress/wordpress.org/blob/ebbbd4848b1302424e7b406267165d51e7c0cc63/wordpress.org/public_html/wp-content/plugins/plugin-directory/libs/site-search/jetpack-search.php#L1040-L1122

The Marketplace search API a similar bool query, and adds rank_feature queries to reorder the results based on some criteria:

```json
"query": {
    "bool": {
        "must": [
            {
                "multi_match": {
                    "fields": [
                        "plugin.all_content.en^0.1",
                        "plugin.all_content.en.engram^0.1",
                        "all_content.en.engram^0.1"
                    ],
                    "query": "jetpack",
                    "operator": "and"
                }
            }
        ],
        "should": [
            {
                "multi_match": {
                    "fields": [
                        "plugin.title.en^10",
                        "plugin.excerpt.en^1",
                        "plugin.content.en^2",
                        "author_login^2",
                        "plugin.author^4",
                        "plugin.contributors^4",
                        "taxonomy.plugin_category.name",
                        "taxonomy.plugin_tags.name"
                    ],
                    "query": "jetpack",
                    "operator": "and",
                    "type": "most_fields"
                }
            },
            {
                "multi_match": {
                    "fields": [
                        "plugin.title.en^10",
                        "plugin.excerpt.en^1",
                        "plugin.content.en^2",
                        "author_login^2",
                        "plugin.author^4",
                        "plugin.contributors^4",
                        "taxonomy.plugin_category.name",
                        "taxonomy.plugin_tags.name"
                    ],
                    "query": "jetpack",
                    "operator": "and",
                    "type": "phrase"
                }
            },
            {
                "rank_feature": {
                    "field": "plugin.features.rating",
                    "saturation": {
                        "pivot": 3
                    }
                }
            },
            {
                "rank_feature": {
                    "field": "plugin.features.num_ratings",
                    "log": {
                        "scaling_factor": 2
                    }
                }
            },
            {
                "rank_feature": {
                    "field": "features.wc.percent_of_sales",
                    "saturation": {
                        "pivot": 0.01
                    }
                }
            },
            {
                "rank_feature": {
                    "field": "plugin.features.active_installs",
                    "log": {
                        "scaling_factor": 2
                    },
                    "boost": 10
                }
            },
            {
                "rank_feature": {
                    "field": "plugin.features.support_resolution_percentage",
                    "saturation": {
                        "pivot": 0.5
                    }
                }
            },
            {
                "rank_feature": {
                    "field": "plugin.features.support_threads_resolved",
                    "log": {
                        "scaling_factor": 2
                    }
                }
            }
        ]
    }
},
``` 

I've experimented with adding some additional rank_feature queries or updating the existing one to create similar ranking to the original function_score query. As the two types of queries work differently in ES, it will definitely take some trial and error to get it right.

**Comment by gcsecsey** [comment]
I've updated some of the factors of the boost fields to more closely match the ones in the WP.org query, but the results are still far from identical:
![Image](https://user-images.githubusercontent.com/11555574/180474868-c321c513-42b2-4400-a931-40f0497df00f.png)

I'll be AFK next week, so I've created a diff with these changes: D84722-code

**Comment by epeicher** [comment]
After some investigation, it looks difficult to have the exact same results between _wporg_ and _wpcom_ but it is worth noting that the principles of getting results to the top should be similar and based on:
- Search phrase as the main criteria
- Lots of active installs
- Good user reviews

More context here: p1658912237306409/1658911357.117719-slack-C02JPCHEKDY

Please note that I have removed from the list `number of downloads` because it is not returned by _wpcom_ and it is similar to `active installs`

**Comment by epeicher** [comment]
Deployed r249810-wpcom
