### ISSUE TITLE
Woo Email Verification: Email notification should go to My Home rather than `/plans`

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#64587]
Was testing the flow and I noticed that the link in the email to confirm the email address redirects to `/plans/my-plan/[siteSlug]` rather than `/home/[siteSlug]`:

<img width="955" alt="Screen Shot 2022-06-13 at 1 35 26 PM" src="https://user-images.githubusercontent.com/2124984/173413584-26507729-0ee4-4bc3-bd90-418113d77df9.png">

This may mean changing that link for everyone since this is a common email.

**Comment by sixhours** [comment]
Digging into this deeper, it looks like the email link points to a specific URL that handles the verification, then redirects to `/plans`. We need to change that redirect behavior rather than the link in the email.

**Comment by sixhours** [comment]
Think I found the redirect's source at `wpcom/wp-activate.php#296`; that line is checking for the eCommerce plan and redirects to WooCommerce admin; if not on the eComm plan, it redirects to `/plans/my-plan`.

So it looks like we need to check against the site intent rather than the plan purchased, and update that redirect to point to My Home rather than the WC admin.

**Comment by valterlorran** [comment]
Closed in D82567-code
