### ISSUE TITLE
Reader: create a new list

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#646]
Add the ability to create a new list.

<img width="1027" alt="screen shot 2015-10-23 at 14 31 21" src="https://cloud.githubusercontent.com/assets/17325/10705453/c9f1fc7c-7992-11e5-8c82-2be8d6451404.png">

The user should enter name and description initially, then be guided to populate the list with content.

**Comment by alisterscott** [comment]
Lists are unavailable for customers without lists, and existing lists users can't manage these lists any more, so closing this issue as no longer applicable. See `p5PDj3-1Fg-p2`
