### ISSUE TITLE
Limited AT: User can change Permalinks

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#64629]
### Quick summary

When a site is AT'd with a lower plan, the permalinks for the site can be changed regardless of the plan used

### Steps to reproduce

With a Limited AT Site:

1. Go to `Settings > Permalinks`
2. Change the Permalink structure

### What you expected to happen

The `Settings > Permalinks` area of WP Admin wouldn't be available, as changing the permalinks is limited to Business and eCommerce plans

### What actually happened

We were able to change the permalink structure

### Context

Internal testing

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

**Comment by renata-franco** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING

- Tested on AT ✅ (with Premium plan) 

📌 FINDINGS/SCREENSHOTS/VIDEO

On my end, I was able to downgrade a Business AT site to Premium from SA, while keeping the site AT. I do not see the `Settings > Permalink` option available, though, as you can see here: 

![image](https://user-images.githubusercontent.com/81378719/175321075-7791c8bc-3e0a-4dbf-9eb2-fb13fc32cd63.png)

Now, however, if I go to the direct WP-admin link to change the Permalinks, I still have access to it. The link would look like this: 

`https://testingsite.com/wp-admin/options-permalink.php`

And here is a screenshot of what that looks like on the Dashboard. It shows that it's in the Settings, but it does not appear listed in Calypso: 

![image](https://user-images.githubusercontent.com/81378719/175321526-3cb22b73-1a7e-4eff-b7c1-91c1ae6fa6b2.png)

Also, I changed the permalink structure on this site, and it works normally! The permalinks changed in the site from having "Day and Name" to "Post Name".  

📌 ACTIONS

- Await author feedback

📌 Message to Author - @edequalsawesome Do you see the direct link for the Permalinks on Calypso on the site where you saw this issue? Or, like my test site, the Permalinks are not displayed on the Settings?

**Comment by obenland** [comment]
Access to permalink settings for sites that don't have the OPTIONS_PERMALINKS feature is limited to proxied requests. The second banner in the screenshot from is meant to provide that context. Which means end users should not be able to see it or access the page.
