### ISSUE TITLE
My Sites: Sidebar external links overlap awkwardly with collapsed sidebar

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#64633]
### Quick summary

When going to the my sites view, something like `/stats/day/$site`, and with a collapsed sidebar, the external link icon overlays that regular icon which doesn't look great.
<img width="744" alt="Screen Shot 2022-06-14 at 3 50 47 PM" src="https://user-images.githubusercontent.com/1126811/173686562-ec9679a5-0549-41b3-904f-86f7c7dd1e75.png">

### Steps to reproduce

1. Spin up a Jetpack, and likely Atomic, site
2. Go to `wordpress.com/stats/day/$site`
3. Collapse sidebar if it is not already
4. Ensure that the external icon is overlapping the icon

### What you expected to happen

The external icon to disappear or be formatted better

### What actually happened

The weird overlapping

**Comment by zachspears** [comment]
I was able to reproduce this, I am thinking the external link should be removed when the sidebar is collapsed. Marking low priority since it does not cause any obstructions.
