### ISSUE TITLE
Gallery block: Carousel feature is missing when gallery is within a Reusable block

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#64638]
### Quick summary

When a `Gallery` block is within a `Reusable` block, the carousel feature can't be used.

### Steps to reproduce

1. Create a new page/post.
2. Add a Gallery block. Add some images to the Gallery block.
3. Turn the Gallery block into a `Reusable` block.
4. Save the change and preview the page.
5. Click on one of the images from the Gallery block.

Here is a screencast:

https://user-images.githubusercontent.com/50875131/173709674-34902fe2-968c-4d78-b7ed-070261ef7d68.mp4

### What you expected to happen

I would expect the `Gallery` block to behave the same independently if it is placed within a `Reusable` block or not. We should still be able to see the image carousel when clicking on the images.

### What actually happened

Gallery images aren't displayed in a carousel.

### Context

Customer report: 5297347-zen

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by ai2n** [comment]
Same issue here #35824034-hc except it was with social links inside a reusable block. They were missing entirely, and visible only when converted to regular blocks.

Sounds like the reusable block itself might have a problem. Bumping priority as this is going to be really painful if that's the case.

**Comment by renata-franco** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate this issue. I cannot even open the images to view them in a large size. This is a video of the issue on my end on a Simple site, but the same happened on a Business AT site. 


https://user-images.githubusercontent.com/81378719/175335269-c6005dcf-6a34-4747-9d06-47485a0cc456.mp4

Please note that the Display as Carousel is selected on the Reusable Block as well, which can be seen here: 

![image](https://user-images.githubusercontent.com/81378719/175338671-659c9bb0-1c11-460e-a1cd-0f424dd97ed3.png)

On self-hosted, the gallery does not show the images as a carousel on the original block or the reusable one. 

A good workaround (thanks @ai2n) would be turning the Reusable Block into a Regular one: https://wordpress.com/support/wordpress-editor/blocks/reusable-block/#convert-to-regular-blocks


📌 ACTIONS

- Marked as Triaged for Quality Squad review

**Comment by mpkelly** [comment]
I am taking a look at this now.

**Comment by daledupreez** [comment]
As a quick note, this issue also applies to the Tiled Gallery block from Jetpack.
