### ISSUE TITLE
Limited Atomic: Performance & Speed settings are still available

### ISSUE THREAD

**Issue by marianearchimbaud** [Automattic/wp-calypso#64635]
### Quick summary

AT'd site with Premium plan still show option to 
Enable or disable site accelerator (Speed up image load times, Speed up static file load times) and enable or disable Lazy load images.
<img width="647" alt="Screenshot on 2022-06-14 at 18-15-52" src="https://user-images.githubusercontent.com/72237737/173704647-c9a3f6ac-3a78-422a-88b8-7361fcdb7fe2.png">

### Steps to reproduce

Visit Settings > Performance.

### What you expected to happen

I was expecting to see this instead: 
<img width="597" alt="Screenshot on 2022-06-14 at 18-28-38" src="https://user-images.githubusercontent.com/72237737/173705752-e025e2fd-9622-42e7-9fc8-ae1f9f0eca82.png">

### What actually happened

I am seeing this:
<img width="806" alt="Screenshot on 2022-06-14 at 18-30-53" src="https://user-images.githubusercontent.com/72237737/173705984-905a4663-197b-4e2b-9a15-39f925cae522.png">

### Simple/Atomic

Atomic

### Reproducibility

Consistent

**Comment by renata-franco** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 


📌 FINDINGS/SCREENSHOTS/VIDEO

Looks like a similar issue was opened before, and closed: https://github.com/Automattic/wp-calypso/issues/36370
Not exactly the same, but similar. 

And it looks like The "Media" options should not appear either on a Limited AT site, just like the "Performance & Speed" option. 

Here is a Premium plan site that still is AT: 

![image](https://user-images.githubusercontent.com/81378719/175330601-ff13518e-82d4-4540-b417-41de02d65b53.png)

And here is a Simple Starter site: 

![image](https://user-images.githubusercontent.com/81378719/175330673-aafa3934-8f25-4502-b38a-b1236cf98177.png)

A Business AT site: 

![image](https://user-images.githubusercontent.com/81378719/175330857-e17fe651-56b3-4b98-9096-d8a034ffc27a.png)

A workaround would be reverting the site but, we would need to find it first. 



📌 ACTIONS

- Marked as Triaged for Quality Squad review
