### ISSUE TITLE
Limited Atomic: Local users can be created in WP Admin

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#64630]
### Quick summary

When a site is AT with a lower plan, local users for WP Admin can be added that aren't connected to WordPress.com

### Steps to reproduce

On a Limited AT site:
1. Go to Users > All Users
2. Change the view to Classic View from the View tab at the top right
3. Add a new local user

### What you expected to happen

All accounts would be added using the WordPress.com interface to ensure SSO is used

### What actually happened

A new user was able to be created

### Context

Internal testing

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

**Comment by renata-franco** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅  (with Premium plan)
- Tested on AT ✅ 


📌 FINDINGS/SCREENSHOTS/VIDEO

This can be replicated on a normal Business AT site as well as an AT site with Premium or Personal plan. 
And it looks like this issue has been opened before, see here: 225-gh-Automattic/atomic


📌 ACTIONS

- Closed as duplicate of 225-gh-Automattic/atomic

📌 Message to Author - Here is the info we have about this back in December 2021: 


> We do not have a good solution at the moment with SSO for memberships sites and things have worked quite alright for the past couple of years for users who have to disable SSO. Going to close this issue for now. More context regarding this can be found here (link in the issue above)
