### ISSUE TITLE
Limited Atomic: Storage limits are not being updated after removing the atomic plan 

### ISSUE THREAD

**Issue by marianearchimbaud** [Automattic/wp-calypso#64636]
### Quick summary

The site used to have an eCommerce site and then a Premium plan was applied.
I was expecting to see a storage limit downgrade from 200 GB to 13 GB.

### Steps to reproduce

Visit the Media Library to review the see the used and available storage limits

### What you expected to happen

13 GB of storage limit 
![Uploading Screenshot on 2022-06-14 at 18-50-58.png…]()

### What actually happened

200 GB of storage limit

<img width="1031" alt="Screenshot on 2022-06-14 at 18-51-34" src="https://user-images.githubusercontent.com/72237737/173708015-39b6e8b5-b721-4e8c-9180-d8eaa6cfb451.png">

### Simple/Atomic

Atomic

### Reproducibility

Consistent

**Comment by obenland** [comment]
@mmtr Is this something that might have been fixed by your recent work on space matters?

**Comment by mmtr** [comment]
Correct, this is fixed after the work done in https://github.com/Automattic/wp-calypso/issues/63878. I tried to replicate the issue, and verified that the storage limit displayed in Calypso is updated correctly after a plan change on an Atomic site.
