### ISSUE TITLE
Reader: Collapsed sidebar is confusing and cannot be expanded

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#64632]
### Quick summary

When I go to the reader at wordpress.com/read, I see something like this:

<img width="187" alt="Screen Shot 2022-06-14 at 3 43 27 PM" src="https://user-images.githubusercontent.com/1126811/173685113-05514940-ba3f-4758-a609-281ed4f4a9dc.png">

From my perspective, it's just a bunch of icons that I'm not even sure what they do. Each icon seems to represent a site that I follow though. But, it's unclear just looking at it.

When I expand tags that I follow, I get this:
<img width="179" alt="Screen Shot 2022-06-14 at 3 45 10 PM" src="https://user-images.githubusercontent.com/1126811/173685404-69c874ba-5f5c-4bab-a121-8989978bf37d.png">

When I expand lists, I get this:
<img width="188" alt="Screen Shot 2022-06-14 at 3 45 31 PM" src="https://user-images.githubusercontent.com/1126811/173685459-776d718c-4ef3-4988-a9ac-b57afb6e2287.png">

When I try to uncollapse the sidebar to make it more usable, I am not able to as I don't see the icon, which is seemingly only in the My Sites view.

### Steps to reproduce

1. Go to wordpress.com/stats/day/$site_slug
2. In the sidebar, click the arrow to compact the sidebar if it's not already compact
3. Go to wordpress.com/read

### What you expected to happen

That the text fits the area allowed in the compact sidebar and that the icons were more understandable

### What actually happened

I was generally confused and unsure how to fix it for a bit

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

**Comment by renata-franco** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 


📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate this on Simple and AT sites. And it's very strange. I also get another issue that when I click on one of the lists of the things in my reader, the page jumps to the top. 

I recorded a video of the whole issue. 


https://user-images.githubusercontent.com/81378719/175328744-4a1ebf3e-0381-4ea0-93d4-f53bb13e778d.mp4

A **workaround** would be clicking on "My Sites" on the top left and clicking on the button to un-collapse the menu and go back to the reader. 


📌 ACTIONS

- Marked as Triaged for Quality Squad review

**Comment by halleshubham** [comment]
@tyxla I'm currently into this issue, thinking of possible solution to be: Make sidebar open in "Reader" irrespective of it's position in "My Sites". (is it fine?)

While trying to access the selector getIsSidebarCollapsed, it errors out saying - "Invalid Hook Call Warning"
Also, I noticed that the version of react in Reader is older one (uses React Component) than the one used in "My Sites".

Can you suggest / point me to similar example where we've captured some data from newer react (My Sites) to older react (Reader)?

**Comment by halleshubham** [comment]
@jordesign may be you can help?

**Comment by tyxla** [comment]
> @tyxla I'm currently into this issue, thinking of possible solution to be: Make sidebar open in "Reader" irrespective of it's position in "My Sites". (is it fine?)

Yes, that sounds like it makes sense. 

> While trying to access the selector getIsSidebarCollapsed, it errors out saying - "Invalid Hook Call Warning"

Yeah, that's likely because we're trying to use a hook in a `Component` class, and that's not allowed in React. 

> Can you suggest / point me to similar example where we've captured some data from newer react (My Sites) to older react (Reader)?

I'm not sure what you mean, could you please elaborate?

**Comment by halleshubham** [comment]
Another possible quick solution could be to append Collapse-Sidebar in reader menu, what do you think 
@tyxla  ?

I've tried it on my machine, works quite smoothly.
<img width="761" alt="Screenshot 2022-07-14 at 3 58 40 PM" src="https://user-images.githubusercontent.com/3984908/178962512-c9092cd7-9299-48e6-9396-eb4e4f0faba4.png">


<img width="783" alt="Screenshot 2022-07-14 at 3 58 27 PM" src="https://user-images.githubusercontent.com/3984908/178962525-317d8dbc-eb4b-4674-9b7c-1b4934c327fb.png">

**Comment by jordesign** [comment]
Thanks for jumping into this folks - I'm afraid the technical aspects are a little above my head - but the theory of trying to have the sidebar *always* open in reader sounds like a good one to me.

**Comment by halleshubham** [comment]
@tyxla 
Regarding:
> I'm not sure what you mean, could you please elaborate?

I'm trying to find a way in order to capture-update the Sidebar's collapsed / open state, which is seemingly maintained in Newer ways of React & causing Hook issue while accessing / updating it. Wanted to understand how can we achieve that?

**Comment by tyxla** [comment]
Is this still a problem if we want to maintain an always-open sidebar for the Reader? If it is, perhaps it might be better if we have a PR in which to continue the discussion - it could provide us with a better context of where the problem is.

**Comment by halleshubham** [comment]
@tyxla I've done changes, this concept of React HOC was totally new to me. 

I've basically wrapped Sidebar component into a funtional react, which updates the sidebar collapsed state before loading of Sidebar component.

Please have a look if it's the rightful way. Here is PR: https://github.com/halleshubham/wp-calypso/pull/new/fix/64632-reader-collapsed-sidebar-issue

**Comment by tyxla** [comment]
@halleshubham thanks for that! Do you mind opening the PR - this page seems to be the screen to add a new PR.

**Comment by halleshubham** [comment]
I think it's automatically tracked by github, here: https://github.com/halleshubham/wp-calypso/commit/769117f3d4e642d22ac6e80a633a85c4e69a0edd
![Uploading Screenshot 2022-07-14 at 6.32.57 PM.png…]()

**Comment by halleshubham** [comment]
@tyxla sorry for that, I mis read stuff. :-)
