### ISSUE TITLE
Seller Experience: Improve the search in the country dropdown

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#64677]
It's challenging to find a state since it uses "—" to separate the country from the state, which is not a simple "-" and if you type for example "Brazil São Paulo" it won't find it because it's missing the "—". It's probably because the search is trying to match precisely "Brazil — São Paulo". 
We should improve the pattern matching to allow us to find the country/state without having to add "—" in the search.

**Comment by markbiek** [comment]
See paYKcK-1OO-p2 for full details of the discussion surrounding this.

The short version is that it doesn't seem fixable using `onFilterValueChange` so I've made an update to the underlying component.

PR is in the gutenberg project, [#41952](https://github.com/WordPress/gutenberg/pull/41952)

**Comment by markbiek** [comment]
I've implemented the hyphen normalization discussed in https://github.com/WordPress/gutenberg/pull/41952 as PR https://github.com/WordPress/gutenberg/pull/42942.

@blackjackkent If we want to continue trying to fix the original issue described above, we're not going to be able to use the `ComboboxControl` to do it and will have to do something different.

**Comment by blackjackkent** [comment]
Closing for now - will reopen if it's re-raised as a major issue.
