### ISSUE TITLE
[Spike] Generated design picker: Browser back button should behave as the screen back button

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64688]
## Description
There are some parts in the generated design picker where the browser back button behavior doesn't match the screen back button. These are the two instances of when it happens:

1. When users switch to the static design picker via the "View more options" button.
  * Screen back button: Goes back to the generated design picker.
  * Browser back button: Goes back to the intent capture screen.
2. In mobile view, when users click on a design thumbnail and enters the design preview mode.
  * Screen back button: Goes back to the list view of design thumbnails.
  * Browser back button: Goes back to the intent capture screen.

## Acceptance Criteria
- [ ] In both of the scenarios described above, change the browser back button behavior to match the screen back button.
- [ ] (Optional) Scenario 2 also happens for the static design picker, update it as well if possible.

**Comment by arthur791004** [comment]
If we want their behaviors to be the same, we have to update the URL when the content of the step is changed.

Here is my thought

```js
/**
 * One way is to define the sub-routes for the Design Picker
 */
<Switch>
  <Route path="/designSetup/vertical">
    <VerticalDesignPicker />
  </Route>
  <Route path="/designSetup/vertical/:designSlug">
    <VerticalDesignPickerPreview />
  </Route>
  <Route path="/designSetup/standard">
    <StandardDesignPicker />
  </Route>
  <Route path="/designSetup/standard/:designSlug">
    <StandardDesignPickerPreview />
  </Route>
</Switch>

// When the user selects a vertical design or clicks a "View more options" button, we need to do
history.push( `/designSetup/vertical/${selectedDesign.slug}` );
history.push( '/designSetup/standard' );

// Besides, we also need to update the selected design whenever the `designSlug` changes so that the selected design would be updated when the user clicks the browser back button
useEffect( () => {
  // update selected design
}, [ designSlug ] );


/**
 * Another way is to update the route whenever the content changed
 */
page( addQueryArgs( { designSlug: selectedDesign.slug }, url ) ); // Select a design
page( addQueryArgs( { stepSectionName: 'standard' }, url ) ); // Clicks the "View more options"
page( removeQueryArgs( url, 'stepSectionName' ) ); // Back from Standard Design Picker
...

// Then, we need to check `stepSectionName` to decide which one to render
const stepSectionName = useQuery().get( 'stepSectionName' );

if ( stepSectionName === 'standard' ) {
  ...
}

// Also, we need to update the selected design whenever `designSlug` in the query string is changed
const designSlug = useQuery().get( 'designSlug' );

useEffect( () => {
 // update selected design
}, [ designSlug ] );
```

**Comment by miksansegundo** [comment]
Thanks @arthur791004 for these detailed examples. 

These changes will delay the deployment because of the testing. Do you think they are worth it?  I like the option with sub-routes because adds clarity to the paths that we have in the code.   

Another option is rewording the "back" button which is a much safer option and simpler option. @taipeicoder I would do the simplest to play safe. What do you think?

**Comment by taipeicoder** [comment]
Seems that the level of effort for this task is relatively significant for what's (IMO) a nice enhancement. Shall we go with a simpler solution for now (rewording the button text) or leave it as it is? cc: @saygunnyc

**Comment by miksansegundo** [comment]
We have ready a [PR](https://github.com/Automattic/wp-calypso/pull/64709) with the simplest solution. There are screenshots showing how it looks. cc: @saygunnyc

**Comment by saygunnyc** [comment]
> leave it as it is?

I'm leaning towards leaving it as is until we fix the browser button behavior as I believe the issue is not how the "< Back" button on UI works –it works as expected, it is how the browser back functions. cc @taipeicoder @miksansegundo

**Comment by taipeicoder** [comment]
Closing the issue for now, as per Saygun's comment.

**Comment by autumnfjeld** [comment]
>  I believe the issue is not how the "< Back" button on UI works –it works as expected, it is how the browser back functions. 

THIS.
