### ISSUE TITLE
Reader: add feed URL to list

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#647]
It should be possible to add a new feed URL to a Reader list.

<img width="1008" alt="17325-feed copy" src="https://cloud.githubusercontent.com/assets/66797/11372932/42795d26-928d-11e5-8532-335c8ce639f2.png">

**Comment by lancewillett** [comment]
See also #648 — using same input, but to add a tag to a list.

**Comment by alisterscott** [comment]
Lists are unavailable for customers without lists, and existing lists users can't manage these lists any more, so closing this issue as no longer applicable. See `p5PDj3-1Fg-p2`
