### ISSUE TITLE
Pay with PayPal block: Configuration error — "Error:SP22" when trying to check out

### ISSUE THREAD

**Issue by alinclamba** [Automattic/wp-calypso#64702]
### Quick summary

Using Pay with PayPal block, when checking out, I get the following error: 

`We are sorry, there was a configuration problem. Please contact the site owner. Error:SP22`

I thought it was related to [this issue](https://github.com/Automattic/jetpack/issues/25011), but it looks like it's a different bug. 

The issue was reported here: 5300383-zd-woothemes, but I was able to replicate it on a JN site as described below. 

### Steps to reproduce

1. Use the "Pay with Paypal" block to add a product and publish the post/page. 

<img width="1058" alt="Screenshot on 2022-06-16 at 15-05-11" src="https://user-images.githubusercontent.com/6790170/174065996-019786b8-858b-49b1-87a7-df370e6bd3f7.png">

2. Click the "Pay with Paypal" button to checkout and you will get the error:

![Screen Capture on 2022-06-16 at 15-07-27](https://user-images.githubusercontent.com/6790170/174066622-17562b69-1d01-46b4-be29-bbdccf62e3f3.gif)

### What you expected to happen

I expect to checkout without any issues. 

### What actually happened

Instead of checkout, I get the error mentioned above. I'm attaching a screenshot with the browser's console:

<img width="1154" alt="Screenshot on 2022-06-16 at 15-11-23" src="https://user-images.githubusercontent.com/6790170/174067508-83fd1e5d-62ad-4cc8-8ee3-de63e3308a04.png">

### Browser

Tested with the latest Chrome, Safari, and Firefox. 

### Other notes

As I mentioned above, I thought it was related to [this issue](https://github.com/Automattic/jetpack/issues/25011), and [I was asked](https://github.com/Automattic/jetpack/issues/25011) to follow [these steps](https://github.com/Automattic/jetpack/issues/25011), which I did,  with no success. 

I tested this on a newly created JN test site:
- WordPress 6.0
- JPDB green, no JP sync or other issues. 
- Jetpack 11.0 (the only plugin active)

### Reproducibility

Consistent

**Comment by dsas** [comment]
Looks like this is a longstanding bug in security tier 1 and security tier 2 plans (D78341-code) which has been replicated in the new feature checking system (D76205-code).

According to the [plan comparison](https://jetpack.com/features/comparison/) and the [support page](https://jetpack.com/support/jetpack-blocks/pay-with-paypal/), all current security and complete plans do support payment blocks, so we’ll have to make the code match that -  but current back-up plans (t1 etc) do not

**Comment by alinclamba** [comment]
Hi @dsas, 

Do we have any updates on this? Just to know what to reply to the user.

**Comment by dsas** [comment]
@alinclamba I'll be working on a fix today

**Comment by dsas** [comment]
Opened D82928-code for review

**Comment by dsas** [comment]
Hey @alinclamba the fix has been deployed, let me know if the SP22 error happens again.

**Comment by alinclamba** [comment]
Hi @dsas, it works now. Thank you!
