### ISSUE TITLE
Change plan upgrade back to the old legacy plans

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#64700]
See: pdtkmj-c5-p2

**Comment by bogiii** [comment]
Import onboarding:
- I've made a change to upgrade the plan to Business: https://github.com/Automattic/wp-calypso/commit/73ea8b08fd965411d9443fa2486b7798825c2e24

- But, there is even better solution, but I'm not sure are we going to turn off Pro plan from the environment configuration. If so, we don't need to introduce any change: https://github.com/Automattic/wp-calypso/blob/trunk/config/development.json#L117

cc @vishnugopal

**Comment by vishnugopal** [comment]
Let's hold off on committing anything, it seems the change might not go through after all: p58i-cxt-p2

**Comment by vishnugopal** [comment]
Closing this for now, see: p58i-cxt-p2#comment-54562
