### ISSUE TITLE
Editor: Introductory tour doesn't dismiss

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#64723]
### Quick summary

When I go to create a post at `wordpress.com/post/$site` I see a tutorial at the bottom. I can't seem to dismiss thing thing so that it doesn't show up on subsequent page loads whether I click the X, skip, or go through the tutorial.

[Video demo](https://user-images.githubusercontent.com/1126811/174205132-4e82b1df-aedc-4bc1-8a69-33e4544f3d16.mov)

### Steps to reproduce

1. Go to `wordpress.com/post/$site`
2. Verify that tutorial shows up in bottom left
3. Click `x` OR go through tutorial OR click the skip buton
4. Reload editor
5. Verify that tutorial still shows

### What you expected to happen

The tutorial to not show up on every page load

### What actually happened

The tutorial continued to show up on subsequent page loads

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

- Can reproduce the error.

📌 ACTIONS

- Closing in favor of the known report here: https://github.com/Automattic/wp-calypso/issues/57660
