### ISSUE TITLE
Dotcom Marketplace: Add "All Products for WooCommerce Subscriptions" to the Dotcom Marketplace

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#64738]
We'll add the **[All Products for WooCommerce Subscriptions](https://woocommerce.com/products/all-products-for-woocommerce-subscriptions/)** Woo extension to the marketplace

FG page with all the instructions - PCYsg-AhC-p2

Here are 2 examples of recent integration works:
https://github.com/Automattic/wp-calypso/issues/63083
https://github.com/Automattic/wp-calypso/issues/63300

- [x] Preflight: pdh6GB-1fc-p2
- [x] Add constants
- [x] Add mapping
- [x] Add feature checks
- [x] Add translation
- [x] Add product entry
- [x] Remove flags

**Comment by rcrdortiz** [comment]
The old checklist doesn't apply anymore. Checking all the necessary items for competition.

**Comment by rcrdortiz** [comment]
D84398-code
1044-gh-Automattic/wpcomsh

**Comment by rcrdortiz** [comment]
p9o2xV-2h0-p2

**Comment by rcrdortiz** [comment]
735-gh-Automattic/dotcom-manage
