### ISSUE TITLE
AMP: Extra <amp-consent> rendered above <html> causing invalid AMP

### ISSUE THREAD

**Issue by wongasy** [Automattic/wp-calypso#64747]
### Quick summary

AMP post markup is malformed for all posts on some sites. Specifically there's an extra `<amp-consent>` node rendered above the start of the HTML document, which results in failure in [AMP validation](https://validator.ampproject.org/). 

**Problem Markup:**
<img width="1053" alt="invalid-amp-consent" src="https://user-images.githubusercontent.com/104910361/174354655-fc9b6f7c-fb0d-4e83-9d9a-f76c21812fd8.png">

 

### Steps to reproduce

1. Go to the AMP validator: https://validator.ampproject.org/
2. Paste the post URL to be validated in to the "URL" box: https://awongtest529603467.wordpress.com/2022/05/16/adventure-awaits/amp/
3. Click the "Validate" button

### What you expected to happen

Receive a `PASS` for Validation status:

<img width="598" alt="Screen Shot 2022-06-17 at 2 20 43 PM" src="https://user-images.githubusercontent.com/104910361/174355665-ba864ed2-2931-48b6-aaa3-e58d7b98abdb.png">

### What actually happened

Receive a `FAIL` for Validation status, with a bunch of AMP errors:

<img width="733" alt="Screen Shot 2022-06-17 at 2 14 38 PM" src="https://user-images.githubusercontent.com/104910361/174354892-a22d86d7-0516-4297-8fcc-ce82cca89581.png">

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Not entirely sure. From the testing I have done so far, I was able to reproduce the issue with the following themes:
* Chronicle
* Russel 

What's worth noting is that, in the case of the Chronicle theme, it was applied to two different simple sites with the same setting. Yet AMP failed for one site but not the other. For more details, please see 5304815-zd-woothemes

### Reproducibility

Consistent

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 


📌 FINDINGS/SCREENSHOTS/VIDEO
I'm also getting mixed results on my test sites so this may need to be investigated further. 


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by daledupreez** [comment]
Does it make sense to assign this issue to @Automattic/build given that you're working on AMP at the moment?

**Comment by p-jackson** [comment]
Since this is reportedly only happening on simple sites, then I don't think we should attempt to fix this at all given that we're hoping that AMP will be removed from all simple sites very soon.

**Comment by vindl** [comment]
I'll still pull it to our board so that we can keep track of it and close it once the removal is done.

**Comment by wojtekn** [comment]
We removed AMP support for Simple sites on July 11th, 2022 so this issue is not actual anymore. pdKhl6-lx-p2#comment-368

URLs like `/2022/05/16/foo-bar/amp/` are redirected to non-AMP versions, e.g. `/2022/05/16/foo-bar/`, and they don't serve AMP-related content anymore.
