### ISSUE TITLE
Buttons Block: Open in new tab option de-selects itself when adding link

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#64758]
### Quick summary

When adding a link to a button in the Buttons block, confirming the link can de-select the "Open in new tab" option if it was already selected.

### Steps to reproduce

1. Create a page or post and add a Buttons block to it. Add some text to the button.
2. Click on the "link" icon in the toolbar to choose what the button links to.
3. Paste or type in a link or page name, but don't click any of the options to confirm it/the suggested pages yet.
4. Toggle on the "Open in new tab" option.
5. Press the "return"/"curved arrow" button to confirm that you'd like to use the page/link you entered.

### What you expected to happen

The link should be added to the button, and the "Open in new tab option" should stay active.

### What actually happened

The link is added to the button, but the "Open in new tab" option visibly turns itself off.

GIF:
![button-link-bug](https://user-images.githubusercontent.com/82622339/174418652-82ab3099-811a-46c7-9d02-a484840d9a45.gif)

### Context

Customer reported this issue in chat ( 35832955-hc , follow-up 5306770-zen ) and said they're fairly confident it's never done this before. They included a video they made themselves, demonstrating the issue; I made my own recording on a test site to protect their data. I've confirmed that it happens on both Simple and Atomic test sites.

Other options for confirming the chosen link, such as pressing the Enter/Return key on the keyboard or clicking one of the suggested links/pages, do not do this; only the "return arrow" button causes this effect.

This also doesn't happen when adding links to paragraph text.

This is a very tiny issue and likely not a high priority fix at all, but it is an odd inconsistency so I figured I'd report it to be safe.

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

All workarounds are extremely simple:

1. Use one of the other options to confirm the link you want to use (Enter/Return keyboard key, click on a suggestion).
2. Don't click the "Open in new tab" option until after the link has been confirmed.

And other similar options.

**Comment by syhussaini** [comment]
Just check if we have any updates on this subject.

**Comment by Greatdane** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Confirmed. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Created a Calypso bug report here; https://github.com/WordPress/gutenberg/issues/42032
- Added to cross-repo watch list.

**Comment by daledupreez** [comment]
This issue was addressed by WordPress/gutenberg#42073, which made it into Gutenberg 13.7. As of yesterday, we're running Gutenberg 13.7.3 on WordPress.com, so we can mark this issue as resolved.
