### ISSUE TITLE
Media: Image Privacy setting doesn't save

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#64760]
### Steps to reproduce

1. In Calypso, go to Media
2. Edit an Image
3. Set the Privacy to **Public** or **Private**
4. Click Done

![image1](https://user-images.githubusercontent.com/15944096/174431393-ea2f2aa6-b61d-48dc-ac40-14d6d75095f0.png)

### What you expected to happen

Privacy status to be be saved.

### What actually happened

Privacy status goes back to **Site Default**.

### Context

Noticed while peer reviewing this chat 35765691-hc

### Workaround details

If site is atomic, and the goal is to hide the media pages then can use this https://wordpress.org/plugins/disable-media-pages/

**Comment by kerrynicl** [comment]
Was able to reproduce this issue

https://user-images.githubusercontent.com/83325600/176568580-7cf558a8-1295-4964-87a3-4d96975d039a.mp4

**Comment by xue28** [comment]
Another ticket here: 5404779-zen

Plan: Personal

**Comment by wojtekn** [comment]
I've reproduced this issue. Then I checked the Calypso code and the API route that handles it, and it seems that the `privacy_setting` is supported only for videos. We don't save it for images at all, and as far as I see, we don't use it as well. I tried to save it for the video, and it worked fine.

This would mean that we shouldn't fix saving it for images, but we should ensure that we don't display this field for images at all. I see that [Media Libary](https://wordpress.com/support/media/) documentation show the image edit UI and it doesn't include privacy field.

@formosattic could you please confirm that this is the correct approach?

**Comment by formosattic** [comment]
Thanks @wojtekn! Yes I believe that is right, as that field appears to be the "[VideoPress: Video Privacy](https://jetpack.com/support/video-privacy/)" option, so it shouldn't be there for images or videos uploaded directly to the server.

The option **must only show for VideoPress videos**.

On self-hosted with VideoPress, from `WP Admin > Media`, it only shows a privacy field for VideoPress videos.

| VideoPress. Privacy option. | Videos. No Privacy option. | Image. No Privacy option. |
| ------------- | ------------- | ------------- |
| ![](https://user-images.githubusercontent.com/15944096/183583893-ea5061f8-3c7f-4be0-b199-d3c97537d526.png)  | ![](https://user-images.githubusercontent.com/15944096/183585058-3f3cddf9-e587-49bf-9a44-89918c2a434a.png) | ![](https://user-images.githubusercontent.com/15944096/183583879-011d2280-13ca-4a9d-aa1c-4ed345e36507.png)  |

**Comment by sejas** [comment]
- Fixed on https://github.com/Automattic/wp-calypso/pull/66390
