### ISSUE TITLE
2FA: No prompt to enter the SMS code when logging into your account.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#64764]
### Quick summary

Users are not getting prompted for the 2FA codes we send them via SMS. This is impacting things such as account recovery, as it is also preventing them from using their backup codes.

### Steps to reproduce

1. Create an account on WordPress.com, plus site.
2. Enable SMS-based 2FA.
3. Log out of that account, or try to log into that account in another browser/an incognito window.

### What you expected to happen

You should be prompted for your 2FA code.

### What actually happened

You're told a code has been sent, but there's nowhere to enter it.

### Context

Reported so far in 5309092-zd-woothemes, 5307864-zd-woothemes, and 5308941-zd-woothemes.

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Edge

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Users can try another browser and will not see this issue. So far, Firefox is not impacted.

**Comment by arinoch** [comment]
- [x] One more in 5308067-zd-woothemes.

**Comment by kuropixel** [comment]
- [x] Adding info for 5309092-zen: User mentioned they tried with Firefox and it worked instead of Edge.

(This ticket is covered in the original post)

**Comment by arinoch** [comment]
Updated the main issue to specify so far Edge is affected. May also be Chrome, but that's pending.

**Comment by ckmccoy2** [comment]
- [ ] 5308941-zen (one of the cases mentioned above) is also reporting that they are able to login in, but seem to get timed out after varying amounts of time.

**Comment by poeticabdul** [comment]
- [x] Reported here 5309426-zen

**Comment by metabreakr** [comment]
- [x] Possible report in 5307570-zen

**Comment by metabreakr** [comment]
Another in 35752735-hc

**Comment by arinoch** [comment]
Update: User in 5308067-zd-woothemes says it happens in firefox as well. I'm going to ask for more detailed FF browser info.

**Comment by kuropixel** [comment]
Update: User in 5308941-zen mentioned they've tried with both Chrome and Firefox, but no luck.

**Comment by essleeung** [comment]
Another case here: 5314299-zd-woothemes 
User doesn't get the popup in Chrome, but gets in in Edge. They turned it off for now. 

- [x] Please update user once a fix is in place so they can enable 2FA

**Comment by essleeung** [comment]
Another case here: [5314721-zd-woothemes](5314721-zd-woothemes)
Normally user uses Chrome, Firefox seemed to have worked. 

- [x] Please update user once a fix is in place.

**Comment by devNigel** [comment]
Another report: 5313150-zd-woothemes

User tried Chrome and Edge. Asked them to try on Firefox.

 

- [x] Please update user once a fix is in place.

**Comment by arunsathiya** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

- Not applicable. Several user reports above are sufficient.

📌 ACTIONS

- Some discussion here: p1655862627824049-slack-C029GN3KD. Waiting for an outcome on that thread.

**Comment by kuropixel** [comment]
5315474-zen

User reported not seeing where to enter 2FA code. Asked for browser info and suggested to try in latest version of Firefox.

**Comment by arunsathiya** [comment]
Not closing this just yet but this is most-likely resolved: p1655867066545129/1655862627.824049-slack-C029GN3KD. Reaching out to a few customers (those in the original report) to confirm for now.

**Comment by lsl** [comment]
Merged and deployed a revert in https://github.com/Automattic/wp-calypso/pull/64839. We know a bit more about what went wrong now and this should be a complete fix. Please re-open if you encounter anything indicating otherwise.

**Comment by vajrasar** [comment]
> * 5308941-zen

@ckmccoy2 this issue does not seem related. Am I missing anything?

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with the affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
