### ISSUE TITLE
Cookie acceptance widget [Customizer]: Make the cookie acceptance widget a separate section, not a widget

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#64768]
### What

User request: 5296745-zen

Current status:

In order to add a cookie acceptance widget, it needs to be added under Customize > Widgets > widget area.
https://en.support.wordpress.com/widgets/cookie-widget/

User's suggestion:

Create a dedicated section in the Customizer for managing the cookie widget, so that it doesn't get hidden/forgotten under Widgets > whichever widget area was selected. 
Also, add it as a separate menu item under the Appearance menu (like Widgets and Menus).

The user's point is that they don't see it as a "widget" but as a required default functionality.

My own addition:

Might be good to have a block/template part for this, for Site Editor themes.

### Why

A dedicated section directly in the main Customizer panel would have the advantage of additional visibility for users.

A dedicated block and/or template part would be good for future-proofing sites; especially since Blockbase and other Site Editor themes don't necessarily have a dedicated widget area.

**Comment by simison** [comment]
Should get covered by https://github.com/Automattic/wp-calypso/issues/52100
