### ISSUE TITLE
Jetpack CDN: GIF timing not preserved with optimization

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/wp-calypso#64767]
### Steps to reproduce

1. Upload a GIF with two frames, with variable timing between them (i.e. one frame lasts longer than the other)
2. Check the post/page preview with and without the Jetpack CDN enabled. 

### What you expected to happen

The GIF should display with its original timing. 

(Note: It does display correctly for a test GIF on my site linked below, made in Procreate. It does not for a user's GIF, also linked.)

### What actually happened

The GIF displays with both frames evenly-spaced in timing. 

### Context

Originally #34371003-hc ⁠— if you have SSP, you can see the CDN image and original post link on my private test post here: https://yetanothertestsitedotblog.wpcomstaging.com/2022/06/20/1890/ 

This seems tricky to reproduce ⁠— it might be a bug, or it might be a quirk of this specific GIF! I'd appreciate eyes on it either way. 

### Simple, Atomic or both?

Atomic

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Disabling the CDN works fine and the user was happy with that.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - N/A
- Tested on Simple - N/A 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested with the user GIF on an AT site and was not able to recreate any difference with Jetpack CDN enabled or disabled. The GIF displays with both frames evenly spaced in timing whether Jetpack CDN is enabled or disabled. 
- I tested with this GIF on a self-hosted site and the GIF didn't animate at all.
- I do not have Photoshop to create a two-frame GIF and was not able to find any in an online search with variable timing to use in a test.

📌 ACTIONS
- Await author feedback

📌 Message to Author
 - @goblinartificer This seems like a very specific edge case and I wasn't able to recreate any issues specifically related to Jetpack CDN so I think it might be appropriate to close the issue, but I wanted to check with you if you were able to recreate this with any other two-frame GIFs.

**Comment by goblinartificer** [comment]
Wow, that's super weird. I'll do some further testing when I get the time ⁠— I should be able to make a GIF or two of my own with a few settings. It does seem like an edge case, but I'd still like to see what else I can find out!

**Comment by cuemarie** [comment]
@goblinartificer Were you ever able to return to this for further testing? For the moment I'll close this out (just doing some clean-up on standing reports), but feel free to reopen if you're able to get those GIFs for further testing!
