### ISSUE TITLE
Seller Experience - Add modal popup when user must upgrade to select theme

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#64783]
Following on from https://github.com/Automattic/wp-calypso/issues/64717, as part of the new Seller Experience theme picker designs described in paYKcK-1Hs-p2, we need to add a modal which will appear when the user must upgrade their plan in order to use the selected theme: 

(NOTE: This should be behind a feature flag separate from the one governing our theme picker updates as a whole, as we would like to deploy this as a separate subsequent change in order to analyze the modal's impact on conversion.)

<img width="858" alt="image" src="https://user-images.githubusercontent.com/13437011/174882920-f7566cc0-d545-40fc-9bb4-3fe7b4ca21e5.png">

Requirements:
* If the user's plan does not support enabling this theme by default, the button should prompt them to "Unlock Theme"
    * Button should say "Continue" otherwise
* If user clicks "Unlock Theme", a modal popup should display with more detailed information about the necessity of upgrading.
* Clicking "Upgrade Plan" from the modal popup should take the user into the checkout flow (following current behavior)
* Clicking cancel should close the modal.
* All buttons on the modal should have relevant tracks events.

Figma: 0EogtxvlmxMGcnEEaMVECv-fi

**Comment by sixhours** [comment]
This has been deployed behind a feature flag `signup/seller-upgrade-modal` in #64868
