### ISSUE TITLE
Google Sign-in: Introduce authorization code exchange endpoint in WPCOM

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#64787]
### Details

Part of https://github.com/Automattic/wp-calypso/issues/64538.

The starting point is to introduce an endpoint where we can exchange the auth code (the response of the Google authorization process) for tokens in the back-end.

This endpoint will receive the auth code in its body (for security reasons) and exchange it for tokens (access and ID tokens) with the Google APIs. Here's an example snippet of the process: D82597-code.

**Comment by zaguiini** [comment]
Diff for review: D82912-code.

**Comment by zaguiini** [comment]
<p>I was bothered by the necessity of a new endpoint to exchange the authorization code for tokens, and the fact that it needed to be two separate endpoints (one for exchanging the code for tokens, one for finalizing the authentication flow) while those tasks could easily be merged into a single endpoint.</p>


Context: right now, I'm planning to create an extra endpoint that we can use to exchange the auth code for an ID token.

The flow in the front-end:
- request to Google APIs to get the auth code
- request to WPCOM API to exchange the code for an ID token
- request to WPCOM API with the ID token to complete the flow in the back-end

That's by far the simplest implementation and one that would not change anything that already exists. However, this might bring a problem for intermittent connections where the first request to WPCOM API succeeds, but the second one does not.

There's a solution to this problem, which is slightly more complex:
- request to Google APIs to get the auth code
- request to WPCOM API with the auth code
    - exchange the code for an ID token
    - use the ID token to retrieve user information

Personally, I prefer this one as it hides that complexity from the front-end and, typically, requests between servers are not only faster but more reliable.


<p>I personally prefer having a single endpoint that handles both auth code and tokens, whichever are passed, as it hides that complexity from the front-end and, typically, requests between servers are not only faster but more reliable.</p>



<p>I spent my day researching how we could simplify it to a single endpoint, mostly reusing the ones that already exist (did you know we have three separate endpoints that do mostly the same thing?) by allowing passing the auth code instead of the ID token as a parameter.</p>



<p>It is technically possible, but we'd need to include a lot of changes and it's hard to track exactly where the endpoints are called and which arguments, so it's just simpler to add the new endpoint and exchange the code there, keeping all existing endpoints as they are.</p>



<p>Note that the changes would not only apply to the back-end: the Jetpack connection iframe, for example, pass the ID token around several times, including a retry mechanism in case the user is not yet registered in WPCOM. As I said, it's technically possible, but doing so would require more time and more resources (both my hands and reviewers' eyes) and, as we're doing Janitorial work, the smaller the scope, the better.</p>



<p>And honestly, my main argument for that case is not even that strong because we're already doing that kind of two-step exchange right now as Google does exactly that when we call <code>GoogleUser.getAuthResponse</code> in Calypso: it fetches tokens from the Google APIs in the front-end, so it's still a double request: one to fetch the tokens (created by Google), one to finish the flow (dispatched to WPCOM with the tokens). We're just changing the target of that first request 🤷‍♂️</p>



<p>But my paranoid approach for weak internet connections stands: one thing we could do is to retry the auth code exchange request in case the first attempt fails. I updated the ticket to include that item in the acceptance criteria.</p>

**Comment by p-jackson** [comment]
> one thing we could do is to retry the auth code exchange request in case the first attempt fails

I think this retry mechanism is already built into Calypso's network stack right? So this might already be done.

Personally, I would worry that much about the situation where the second API call fails. The user experience is going to be the same whether it's a single endpoint that can fail or two endpoints where only one call fails. There'll be an error in the UI and then the user will press submit again, and it'll work.

> it's technically possible, but doing so would require more time and more resources (both my hands and reviewers' eyes) and, as we're doing Janitorial work, the smaller the scope, the better.

This is the way I'm leaning. Moving the logic to the backend does make more sense to me, and it _should_ be easy i.e. it should be easy for our new endpoint and the existing social login endpoint to share the same PHP library code behind the scenes. But if "we'd need to include a lot of changes and it's hard to track exactly where the endpoints are called and which arguments" then it doesn't sound like the PHP code is that easy to share, and so it's better to stick with the smaller scope.
