### ISSUE TITLE
Seller Experience - Add Design Preview info dropdown

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#64782]
Following on from https://github.com/Automattic/wp-calypso/issues/64717, as part of the new Seller Experience theme picker designs described in paYKcK-1Hs-p2, we need to add a dropdown to the design preview screen with information about the selected theme:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/13437011/174882159-083c392d-b6dc-4dc7-a873-912ffedea207.png">

Requirements: 
* Dropdown toggled when user clicks on information button in top right of preview screen
* Ignore updated time, star rating, and bundled plugins in existing mockup for now

Figma: 0EogtxvlmxMGcnEEaMVECv-fi

**Comment by markbiek** [comment]
@valterlorran I've got this pretty much done but you & I will probably need to coordinate wiring up the button in the header that shows and hides this.

**Comment by nelsonec87** [comment]
@markbiek the button is also done [here](https://github.com/Automattic/wp-calypso/pull/64864)!
I'm just rebasing from the new picker branch now
