### ISSUE TITLE
Image Compare Block: Block Width setting missing on Atomic sites when CoBlocks is active

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#64796]
### Quick summary

Image Compare Block is missing width settings on Atomic sites. They are available on simple sites.

### Steps to reproduce

1. On an AT site, create a new page.
2. Add Image Compare block, you will notice that it does not have Block Width options.

1. On a Simple site, create a new page.
2. Add Image Compare block, you will notice that it has Block Width options.

### What you expected to happen

Image Compare block should have Block Width options.

Screenshot from AT site:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/33957570/174699253-a02bec92-9c93-4641-9038-fc64b051ba1e.png">

Screenshot from Simple site: 

<img width="956" alt="image" src="https://user-images.githubusercontent.com/33957570/174699469-ac035ef4-0be0-4716-a323-f87e51ddf878.png">

### What actually happened

Image Compare block on AT site is missing Block width option.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/33957570/174699253-a02bec92-9c93-4641-9038-fc64b051ba1e.png">

### Context

User report: 5306666-zd-woothemes

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No. Was able to reproduce with multiple themes.

### Reproducibility

Consistent

### Severity

All

### Workaround details

Deactivate CoBlocks

**Comment by devNigel** [comment]
After I deactivated CoBlocks, the block width options appeared. 

I activated CoBlocks again and the block width option is still there. Weird.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to replicate this on my sites. I believe this might've been a one-time glitch.

📌 ACTIONS

- Closed as could not replicate, please reopen this issue if it reoccurs
