### ISSUE TITLE
Dimensions block setting on Cover Block doesn't allow changing of unit type when unlinked.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#64794]
### Quick summary

When trying to add padding or margin to a cover block, the dimension unit will not be set if the settings are unlinked.

These are the settings I'm referring to:
![Screen Shot 2022-06-20 at 3 25 07 PM](https://user-images.githubusercontent.com/49131029/174679711-e8c9d78a-c881-40ec-966c-c687a248f4bb.png)
 
This also affects "Post Featured Image", blocks as these appear to be cover blocks as well.

### Steps to reproduce

1. Insert a cover block on any site or theme.
2. On the right sidebar, under dimensions unlink the padding or margin settings to create 4 boxes, one for each side of the block.
3. Try to change the unit in one of the boxes (IE: set it to %, EM... Etc)

### What you expected to happen

The units should change in one or all of the boxes.

### What actually happened

The unit resets to its previous selection.

### Context

Discovered while helping a user here: 5312619-zen (They do not need to be notified)

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Make sure the dimensions are linked, and then change the unit in the single box, and then unlink them again.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted  - no

📌 FINDINGS/SCREENSHOTS/VIDEO
- I have tested this with Gutenberg 13.5.2 and I couldn't replicate the issue. I tested with various themes as well.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs


📌 Message to Author
 - Please reopen if this occurs again.
