### ISSUE TITLE
Marketplace: Add a required checkbox in the Checkout 

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#64799]
### What

Add a required checkbox in the checkout stating
"By clicking here, you agree that an account may be created on a third party developer’s site related to the products you have purchased."
![CleanShot 2022-06-21 at 07 38 43@2x](https://user-images.githubusercontent.com/12430020/174717534-1238eb72-76d7-4a0b-bc07-761e2b9bda20.png)

This checkbox should appear only if the checkout contains marketplace products.

### Why

Vendors might create an account for users who have purchased a marketplace 3pd product. User should understand that such an account might be created pdh6GB-16g-p2#comment-1898

**Comment by epeicher** [comment]
Hi @vinimotaa, @SaxonF,

Please find a screenshot with an initial version of the checkbox, please note that until the user does not tick the checkbox the button will not be enabled. 

Any comments? 😄  
|Unticked | Ticked|
|-------|------|
|![CleanShot 2022-07-12 at 16 24 00@2x](https://user-images.githubusercontent.com/3519124/178513484-88c9f08a-cbc3-4c66-bc6b-61ee2f58c6b6.png)|![CleanShot 2022-07-12 at 16 20 58@2x](https://user-images.githubusercontent.com/3519124/178513311-a4176f86-fb9a-4081-a69d-7c4836b8a3eb.png)|

Also please find the before and after the change:
|Before | After|
|-------|------|
|![CleanShot 2022-07-13 at 10 44 59@2x](https://user-images.githubusercontent.com/3519124/178691569-11212a2e-8149-4375-9834-71cef213a485.png)|![CleanShot 2022-07-13 at 10 47 19@2x](https://user-images.githubusercontent.com/3519124/178691762-bab6b7d6-bcd0-4739-9c16-12bf6884d9cb.png)|

**Comment by epeicher** [comment]
Additional note:
> Can we include the product name in the copy? So that users are aware the term is bound to that specific product if the cart contains multiple products?

**Comment by epeicher** [comment]
The following P2 pdt2If-e4-p2 has been created for discussion

**Comment by obenland** [comment]
@epeicher When there's a PR to test out, could you ping @ Automattic/editorial for a review of the wording?
They're generally a great resource for all things wording/editorial related.

**Comment by epeicher** [comment]
The approach has been slightly changed to what is described in the following comment pdt2If-e4-p2#comment-160 and the checkout flow can be found in a `gif` in this comment pdt2If-e4-p2#comment-163. The [linked PR](https://github.com/Automattic/wp-calypso/pull/65414) is ready for review.
