### ISSUE TITLE
Reader: add tag to list

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#648]
It should be possible to add a new tag to a Reader list.

<img width="1008" alt="17325-feed copy" src="https://cloud.githubusercontent.com/assets/66797/11373022/995dee2c-928d-11e5-807b-2de7905da257.png">

**Comment by alisterscott** [comment]
Lists are unavailable for customers without lists, and existing lists users can't manage these lists any more, so closing this issue as no longer applicable. See `p5PDj3-1Fg-p2`
