### ISSUE TITLE
Premium Themes Not Showing On Atomic Site

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#64830]
### Quick summary

On Atomic sites, some Premium themes do not show up in search. 

### Steps to reproduce

1. On an Atomic site, go to Appearance > Themes.
2. Search for a theme such as "Maywood", "Skivers" or "Kerr". (these were the ones not working on my site but there may be more or different ones for you).
3. 

### What you expected to happen

The theme to show below like it does with the Premium plan simple sites:

![Markup on 2022-06-21 at 14:49:07](https://user-images.githubusercontent.com/93800099/174876830-50d55320-3521-478d-8ab8-470bb4c6731b.png)

### What actually happened

No themes show:

![Markup 2022-06-21 at 14 48 35](https://user-images.githubusercontent.com/93800099/174876895-57d7f3e2-16fc-4c9b-9bfe-6dfc68f6b7fd.png)

### Context

35865091-hc

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

These are the themes I found the issue with in my testing: "Maywood", "Skivers" or "Kerr". There may be more than this.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

For HEs - you can symlink the theme (and any parent theme) in CLI and then it will show in the dashboard.

For the user - They can go to https://wordpress.com/theme/[THEME SLUG] and then choose a site OR upload the theme zip file. Neither of these would be straightforward for the user to figure out.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2  no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted no

📌 FINDINGS/SCREENSHOTS/VIDEO
- I believe this was an issue caused by #64840.

📌 ACTIONS
- Closed as duplicate of #64840

📌 Message to Author
 - If this is not the same issue, please re-open.
