### ISSUE TITLE
AMP: Switch 302 redirects to 301

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64844]
### Details

Once we're convinced that the AMP rollout has gone well we should change the redirects from temporary `302`s to permanent `301`s. This will instruct search engines to update their indexes.

See https://github.com/Automattic/wp-calypso/issues/64579#issuecomment-1156005926
> It could be a good idea to use temporary 302s initially during the rollout phase, only switching to permanent 301s after we're 100% confident everything has gone smoothly.

The redirecting code was done in D82861-code, so that's where it can be modified.

### Checklist

- [x] Change redirects for AMP pages on simple sites from `302` to `301`

**Comment by wojtekn** [comment]
Hold for onboarding.
