### ISSUE TITLE
Theme Showcase: Filters not impacting theme list

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#64840]
### Quick summary

When using the Theme showcase on an Atomic site - the filters (All/Free/Premium) have no impact on the list of themes shown.

### Steps to reproduce

1. Start with an Atomic Site
2. Go to the theme showcase
3. Use the filters at the top (to the right of the search bar)

### What you expected to happen

The list of posts to be filtered

### What actually happened

Nothing

### Context

User report - #35867879-hc

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Refresh the page once the filter has been selected.

**Comment by arunsathiya** [comment]
For the next triager, there's a discussion here: p1655883892864299/1655865772.124599-slack-C029GN3KD

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- 
📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple - no 
- Tested on AT ✅ 
- Tested on Self-hosted - no
- 
📌 FINDINGS/SCREENSHOTS/VIDEO
- Already reverted and it looks like it's already working. 

📌 ACTIONS
- Closed as no longer relevant (issue resolved by #000000)
