### ISSUE TITLE
AMP: Add tracks events to help us monitor how the AMP deprecation message performs

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64842]
### Details

Depends on the UI being implemented in #64731.

From https://github.com/Automattic/wp-calypso/issues/64731#issuecomment-1160879749, we want to use tracks to help us answer 3 questions:

1. how many users click on it?
2. what's the percentage of users that click after seeing the nudge?
3. what's the percentage of users that end up upgrading after clicking on the nudge?

We'll need a new track event to record [1] (unless there's an existing generic "upsell" event). [2] will also need a new event to be recorded when the message is mounted. We can't use the existing `calypso_page_view` event and just assume everyone who lands on `/settings/performance/:site` sees the message, because it'll be hidden sometimes (depending on site settings). We don't need any extra events for [3] because there are existing events that record successful purchases.

See PCYsg-dot-p2 for info on event naming conventions and more.

### Checklist

- [x] add a new tracks event to record upsell clicks on the AMP message in performance settings
- [x] add a new tracks event to record "impressions" of the AMP message
- [x] register these new tracks events PCYsg-mUj-p2

**Comment by wojtekn** [comment]
@p-jackson I will assign this one to myself for now. It looks like that nudge component may support that OOTB.

**Comment by wojtekn** [comment]
@p-jackson I've configured impression and click events using UpsellNudge attributes: https://github.com/Automattic/wp-calypso/pull/64889

I'm holding on registering those until we have that PR reviewed and closer to being merged. The tracks can still be checked and tested before they are registered.
