### ISSUE TITLE
Baskerville 2: Post Carousel Block generated JS loading error when added on the homepage

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#64856]
### Quick summary

There appears to be a conflict with Baskerville 2 theme, Post Carousel Block and Atomic that can lead to resources not loading correctly on a page and possibly leading to intermittent failures of the carousel functionality.

### Steps to reproduce

1. Use an Atomic Site
2. Activate Baskerville 2
3. Create a Post Carousel Block on the homepage - tested by pulling in specific pages with featured images

### What you expected to happen

The carousel to always work and no JS errors

### What actually happened

- Load the page in various browsers to see if the carousel works (inconsistent results)
- Check the console for a 400 error on the resource /_static/index.min.js.map

### Context

Reported in chat, discussed at length here - p1655902011837689-slack-C03TY6J1A

Followup created here - 5314480-zen

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Baskerville 2

### Browser, operating system and other notes

Seems to impact all browsers but Safari may be more susceptible

### Reproducibility

Intermittent

### Severity

One

### Available workarounds?

No but the platform is still usable

### Workaround details

Changing to a different theme or not using this block are the only options I've found so far.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no 
- Tested on Simple - no
- Tested on AT ✅ 
- Tested on Self-hosted - no 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I could replicate it on Safari, but I saw no errors or usability issues. 
- Also, the links in the report do not seem to be valid.

📌 ACTIONS
- Await author feedback


📌 Message to Author
 - Could you share what was the issue with the Post Carousel block @kdevnel ?

**Comment by kdevnel** [comment]
> Could you share what was the issue with the Post Carousel block @kdevnel ?

In the case of the user, the carousel wouldn't move between posts and it stayed on the first post slide.

**Comment by Robertght** [comment]
Apologies for the delay here @kdevnel ! 

Unfortunately, I'm unable to replicate this. 
The user also switched the theme to a different one.
I have updated the ticket and slack ref in this report so we can find it easily in the future.

Closing, but please reopen if needed.
