### ISSUE TITLE
Cookies & Consents Banner Widget missing from Starter plan sites

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#64869]
### Quick summary

The Cookies & Consents Banner widget is not available when searching for widgets on sites using the Starter plan.

### Steps to reproduce

1. Create a site using the Starter plan
2. Select a non-FSE theme that has a widget area (I used Karuna and Radcliffe 2)
3. Open Customizer > Widgets
4. Search for Cookies & Consents Banner widget

### What you expected to happen

I expected to see the widget in the Widgets section like this:

![Cookies banner there](https://user-images.githubusercontent.com/32983813/175089742-c2a4325d-cb11-42e7-8f04-b28fb6317353.png)

### What actually happened

I did not see the widget in the Widgets section:

<img width="666" alt="Cookies not there" src="https://user-images.githubusercontent.com/32983813/175090878-db174460-44b4-4f1e-87d7-3b58d818565a.png">

### Context

Reported by user and recreated on my test site
5315169-zen

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

**Comment by dcoleonline** [comment]
Also in zd-5318732

We would like the customer to be notified of the fix

**Comment by ccwalburn** [comment]
I discovered that the widget is not available because the Starter plan does not block ads. If I add the No Ads add-on, then the Cookies & Consents widget displays. So, I think the issue may be that the banner does not display automatically as it does for free sites.

**Comment by Gustavo-Hilario** [comment]
Hey y'all. The user from 5318732-zen is back. They are still trying to add the widget to their site. I suggested adding the No Ads add-on, but they didn't want this solution. If we won't allow users to use that widget at any point, could you please share more details about this? I think that Starter plans sites were supposed to have ads on them, so having the widget would create a duplication. Is that why the widget isn't available?

**Comment by essleeung** [comment]
Another one here- 5365919-zd-woothemes

**Comment by ccwalburn** [comment]
It's been determined that this is not a bug. The Cookies and Consents banner is not available by design.

Because the Starter plan does not include the No Ads feature, we manage the consent banners based on whether or not ads are displayed. When ads are displayed on a site and the site is viewed by visitors from GDPR (General Data Protection Regulation) IP addreses, we will automatically display a full-featured Consent Management Provider banner. For visitors from non-GDPR IP addresses, the Cookies and Consents banner will be displayed. We usually don't display ads on sites that are less than 30 days old so the banner will not appear on brand new Starter plan sites.

If someone really wants to be able to add the Cookies and Consents widget, they can purchase the No Ads addon, and then the widget will be available.

Followed up with the users here:

5369303-zd
5365919-zd

The site related to this report has been deleted so I did not notify them:

5315169-zen
