### ISSUE TITLE
Layout: .wp-content div's overflow:hidden cuts off content

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6486]
#### Steps to reproduce
1. Starting at URL: /help/contact
2. Click the site picker dropdown
3. The dropdown is clipped by the `overflow:hidden` property on the `.wp-content` div
#### What I expected

I expected to see the entire contents of the div

<img width="663" alt="screen shot 2016-07-01 at 2 04 46 pm" src="https://cloud.githubusercontent.com/assets/437258/16530201/f5d3c69a-3f94-11e6-8dce-21096ed0af27.png">
#### What happened instead

It was truncated

<img width="669" alt="screen shot 2016-07-01 at 2 05 41 pm" src="https://cloud.githubusercontent.com/assets/437258/16530197/ee9ac554-3f94-11e6-9e8a-204bea5afb60.png">
#### Browser / OS version

All browsers

cc @mtias

**Comment by rachelmcr** [comment]
Bug scrub: I confirmed that this issue is still present on the contact form on Mac OSX 10.12.6 in Chrome 60.

In Safari 10.1.12 and Firefox 55.0.3 the entire site picker dropdown is shown as expected.

**Comment by rickybanister** [comment]
I just re-encountered this again today coincidentally :(

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

This issue is still reproducible as of this date. 

![image](https://user-images.githubusercontent.com/6549265/106517911-f942c100-648d-11eb-98d0-25bdc00f0124.png)

**Comment by Robertght** [comment]
This is no longer an issue with Chrome 96.
