### ISSUE TITLE
Marketplace search: Use Icons from search response

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#64885]
The Marketplace search endpoint needs to read the Icon from the response and use it in the Plugin details. Currently, the Icon is not populated.

**Comment by gcsecsey** [comment]
D82452-code added the icons object as a serialized JSON object to the index:

```json
"plugin": {
    "icons": "{\"icon-128x128.png\":{\"filename\":\"icon-128x128.png\",\"revision\":2413881,\"resolution\":\"128x128\",\"location\":\"assets\",\"locale\":\"\"},\"icon-256x256.png\":{\"filename\":\"icon-256x256.png\",\"revision\":2413881,\"resolution\":\"256x256\",\"location\":\"assets\",\"locale\":\"\"}}"
}
```

We can either:
- parse this JSON on the client and choose an optimal icon from it, or fall back to #63169 if there's no uploaded icon
- process this object on the API and return an icon field that only contains the URL of the best version
