### ISSUE TITLE
Marketplace: renewal event handler

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#64886]
### Details

WP.com subscription can also be renewed either automatically or manually. In these cases we should alert vendors about the renewal.

### Checklist

- [ ] We have to add a renewal event in `Subscription_Events_Handlers`
- [ ] Trigger the renewal Yoast endpoint

**Comment by JulianBustamante** [comment]
Diff created D83150-code

**Comment by JulianBustamante** [comment]
Deployed r247961-wpcom
