### ISSUE TITLE
Help Center: Introduce the new help center

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#64892]
### What

When the Help Center is available everywhere, we’ll show a tooltip pointing to the new help center, informing customers that they can find their help resources there

<img width="690" alt="image" src="https://user-images.githubusercontent.com/52076348/175279069-0800cf8a-068d-44f7-8a79-ba042360d0cf.png">

<img width="186" alt="image" src="https://user-images.githubusercontent.com/52076348/175279105-7ab8f54a-e717-418b-b987-28b84ff43dca.png">

**Comment by arcangelini** [comment]
This is being addressed here ⇢ https://github.com/Automattic/wp-calypso/issues/69617
