### ISSUE TITLE
Reader: choose from followed feeds to add to a list

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#649]
When setting up a new list, it should be possible to choose from the current user's followed feeds to add to the list.

<img width="1003" alt="17325-tag copy" src="https://cloud.githubusercontent.com/assets/66797/11373122/fcf5db5c-928d-11e5-945d-7255c0403137.png">

**Comment by alisterscott** [comment]
Lists aren't being worked on in the Reader at present. Closing.
