### ISSUE TITLE
Reader: Cold Start not available for the indecisive user

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#6490]
Hi there,

Found a bug where a user is brought to Cold Start, follows and unfollows sites, and will not be directed to Cold Start again.
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/recommendations/start
2. Follow a site
3. Unfollow the same site (net 0 sites followed)
4. Click on a sidebar item
5. Click on Followed Sites (https://wpcalypso.wordpress.com/) and the user is not redirected to Cold Start
#### What I expected

Click on Followed Sites (as a user with no additional followed sites) and be directed back to Cold Start (https://wpcalypso.wordpress.com/recommendations/start).
#### What happened instead

Click on Followed Sites (as a user with no additional followed sites) and see a feed of my own posts.
#### Browser / OS version

Google Chrome Version 51.0.2704.103 (64-bit) / OS X El Capitan 10.11.5

**Comment by jancavan** [comment]
We've taken down Cold Start so closing this issue.
