### ISSUE TITLE
Buttons block: altered styling(colors, padding, border-radius)

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#64917]
### Quick summary

Had a user report that their buttons were missing from multiple sites that are all using the `Canape` theme which seems to be a new bug.

### Steps to reproduce

1. Switch your theme to `Canape` or `Coherent`
2. Make sure that the background color of the theme is set to `white`
3. Add a button block and make sure that the `Style` is set to `Fill` without selecting any colors

### What you expected to happen

The button should turn to a lighter shade of the color specified by the theme.

### What actually happened

The button turns white regardless unless you change the color settings on the individual button (this is also reflected within the Editor as well as you'll see in the video below). You also can't see the button text that you're writing unless the button is not selected.

### Context

35886225-hc

https://user-images.githubusercontent.com/51870544/175398188-17ce808b-6261-42d4-b61e-614c482326eb.mp4

https://user-images.githubusercontent.com/51870544/175398317-2c8bbd4a-44ba-42f7-8da4-af125662b4f2.mp4

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

So far I've found this happens for both `Canape` and `Coherent`, though it may be affecting others. Does not seem to be affecting and FSE sites based on my testing but I can't guarantee that.

### Browser, operating system and other notes

Consistent across Chrome, Safari, and Firefox

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Currently the only consistent workaround I've found that is applicable to both Simple and AT sites is that you need to change the Styles option from `Fill` to `Outline`. There are CSS options, but it seems like this only works if you select the individual element (I've tried several variations of CSS selectors and couldn't get anything to work unless it was specifically called out for a single element).

Video of CSS issue:

https://user-images.githubusercontent.com/51870544/175397009-b8a3f2ff-1831-42ea-8874-c10b072e9f10.mp4

**Comment by edequalsawesome** [comment]
I was able to duplicate this on a site with a third-party theme as well, and the buttons didn't display correctly on the front-end anymore:

![2022-06-23 16 12 50](https://user-images.githubusercontent.com/4000628/175398932-5f1e1b7b-954d-454c-bc21-da12a2c4fda2.gif)

The Internet Archive version of this customer's site had the buttons showing as expected on May 24th, though, so this is likely due to the Gutenberg 13.5 update: https://web.archive.org/web/20220524123225/https://edwincarcano.com/mundo-generacional-emprender-en-tiempos-de-conflictos-armados/

Provided CSS to resolve this in 5321543-zen

**Comment by happychait** [comment]
I had the same user in 5322223-zen with a similar issue but the custom CSS we provided earlier didn't help. 

https://user-images.githubusercontent.com/1519466/175459457-76446850-3caf-427a-8154-b8a73d11804a.mp4

I suggested a more straightforward workaround: you can edit the button in the Outline mode, and once you are done editing, you can check the button style to Fill as following:
![Captured at 24-06-2022 at 15 49 47](https://user-images.githubusercontent.com/1519466/175459746-f3112058-8b2d-48cf-adcb-1af824ddae9c.jpeg)

**Comment by khristiansnyder** [comment]
I've encountered a few instances of button formatting changing after the latest GB update. 

My findings so far:
* The cases I have had have been button blocks all with the `.wp-block-button__link` class
* The buttons lose their padding and usually the radius that was set.
* Seems to happen on AT and simple sites and most themes including third-party.

Screenshot. Left is current, right side is using Wayback machine showing the proper padding for that button:

![Markup 2022-06-24 at 11 24 36](https://user-images.githubusercontent.com/41035049/175644221-099e8924-d963-4a5c-b8b1-bcff3dd32fa7.png)

Workaround: I have been providing CSS to return padding to that CSS class, such as:

```
.wp-block-button__link {
    padding: calc(0.667em + 2px) calc(1.333em + 2px);
}

```

**Comment by poeticabdul** [comment]
Reported here 6127121-hc 

Followup 5323598-zen

**Comment by jp-imagines** [comment]
Reported in 34937445-hc. Third-party theme. One Buttons block (2 buttons) were affected (turned white on white background) when hovered over. Advised user to switch to a different "style" (Outline) for now.

- [ ] Follow-up: 5324135-zd-woothemes

**Comment by edequalsawesome** [comment]
Also reported in 5323732-zen, provided CSS workaround

**Comment by hanananah** [comment]
Reported in 5324212-zen

**Comment by edwinho89** [comment]
A little far-fetched, but this chat in 35888729-hc had its button border radius removed, and may be related altogether.

**Comment by Robertght** [comment]
Another case in here(#5323361-zen) with the missing padding:
![image](https://user-images.githubusercontent.com/6737345/175763172-9f941523-65ac-4758-805d-366caa19559a.png)

Left: incorrect/current state
Right: correct/previous state

Theme: Sequential 
The user stated the change happened yesterday.

- [ ] Follow-up: #5323361-zen

**Comment by Robertght** [comment]
Pinging in p1656142029379519-slack-C02FMH4G8

**Comment by filipanoscampos** [comment]
Another case was reported in 5323571-zd-woothemesand here 5325320-zd-woothemes

Please follow up:
- [ ]  5323571-zd-woothemes
- [ ] 5325320-zd-woothemes

Thanks!

**Comment by kerrynicl** [comment]
Another case report - HC-35902169

**Comment by helenaartmann** [comment]
Another case - 5325246-zd. Please follow up. 

- [ ] 5325246-zd

**Comment by isocialtish** [comment]
Another report of this with Social Media icons missing 5326590-zd. Disabled Gutenberg for now. Please follow up to re-enable the plugin.

**Comment by sudeepbaral** [comment]
Another case here: `5309318-zd`  I suggested them to switch the button style to Outline and shared the CSS workaround.

**Comment by IoanaAMuresan** [comment]
Another report here: `5323639-zd` simple site (Personal plan) -> suggeste the Fill to Outline workaround + creating a Reusable block they can use to more easily replace them.

**Comment by i11za** [comment]
Another report here: 5326449-zd-woothemes
- Simple site (Personal plan)
- Theme: Plane
- Suggested the Fill to Outline workaround. 
Please follow up once there's a fix. Thanks!

**Comment by i11za** [comment]
Another report: 5327309-zd-woothemes
- Simple site (Premium plan)
- Theme: Scratchpad

All buttons on the site were set to 36px radius, but have been reset. 
They're using reusable blocks already to update, but have a lot of buttons to fix. I shared the following CSS which seems to be working: 

```
.wp-block-button__link {
	padding: calc(0.667em + 2px) calc(1.333em + 2px);
	border-radius: 36px;
}
```

**Comment by anuguywp** [comment]
Another case here: 35914739-HC

Provided CSS put together by previous comment:

```
.wp-block-button__link {
	padding: calc(0.667em + 2px) calc(1.333em + 2px);
	border-radius: 36px;
}
```

- [ ] 5330360-ZEN Please follow up.

**Comment by sharonlaker19** [comment]
+1 at 35509748-hc, shared CSS workaround in 5332545-zen

**Comment by kerrynicl** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicable on Simple and AT 
📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Robertght** [comment]
This should be fixed here(p1656418840448029/1656142029.379519-slack-C02FMH4G8) and the last report from @sharonlaker19 will be fixed here: https://github.com/WordPress/gutenberg/pull/42012/files

I'm going to close this for now to avoid more confusion. If other padding issues show up, please report them here:

https://github.com/Automattic/wp-calypso/issues/65033

cc @kerrynicl @chad1008 @scruffian

**Comment by Robertght** [comment]
Reopening for bulk replies cc @vajrasar

**Comment by cecilearkay** [comment]
Another one on the FR forums: https://wordpress.com/fr/forums/topic/probleme-daffichage-des-boutons/

**Comment by arunsathiya** [comment]
- Quick clarifying note that this will be fixed only when https://github.com/WordPress/gutenberg/pull/42012 is merged. Related chat with @scruffian here: p1656579562681109/1656575923.679859-slack-C034TMVE5CM cc @Robertght 
- We'll leave this open for a bit more and track customer reports.

**Comment by helenaartmann** [comment]
Another report: 
- [ ] 5339955-zen

**Comment by edwinho89** [comment]
- [ ] 5338841-zd-woothemes

**Comment by becdetat** [comment]
- [ ] Another report: 5338885-zd-woothemes

The user's theme is Cerauno.

Text is "invisible" - same background and foreground - even with the Default colours selected.

**Comment by ghost** [comment]
Another report 35969016-hc

**Comment by dcoleonline** [comment]
I believe this was also the issue in 5365410-zd
They've manually fixed it on their site.

**Comment by msilbers** [comment]
- [ ] 5372892-zd-woothemes

**Comment by Jaykame** [comment]
5426069-zen Applied the CSS workaround but this site has a custom CSS add-on and is not atomic. Cross reported here: https://github.com/Automattic/wp-calypso/issues/64880 

I added the plain old and it worked:

```
.wp-block-button__link {
    padding: 1em; 
}
```

**Comment by jp-imagines** [comment]
I think the user in 31797310-hc had experienced this too (Gateway theme).

All buttons were black with white text, but three were changed to white with black text (and white text on hover, turning them fully invisible); the other one was changed to gray with black text for some reason. No settings in the block editor indicated any changed/custom colors on all four buttons.

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group has finished following up with the affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by Joshgrygiel** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple: Yes
- Tested on AT: Yes
- Tested on Self-Hosted: Yes
- Tested on P2: No
- Replicable on Core: No

📌 FINDINGS/SCREENSHOTS/VIDEO

RESULT: I can confirm the button appears invisible when added to the Canape theme:

ATOMIC:
![BUTTON_AT](https://user-images.githubusercontent.com/88345647/188937834-7a9368fd-c5b7-4abd-9538-0854d75c21b4.png)

SIMPLE:
![BUTTON_SIMPLE](https://user-images.githubusercontent.com/88345647/188937839-170e9290-e1e5-43da-a358-fb35a8df2c1d.png)

Self Hosted (Not replicable):
![BUTTON_SH](https://user-images.githubusercontent.com/88345647/188937902-34a461fb-bc03-4a8a-9c33-5c6bf4c27081.png)

📌 ACTIONS

Reopened report

**Comment by scruffian** [comment]
I created a fix for this here: https://github.com/WordPress/gutenberg/pull/43981
