### ISSUE TITLE
Reader: site's text color is not using Reader styles

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#6491]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/feeds/21108255
2. Click on one of their posts to view full-post
3. This particular site's (AP Images Blog) text color is `#000000` instead of using `darken( $gray, 30% )`
#### What I expected

For text color to be `darken( $gray, 30% )`
#### What happened instead

Text color is set to `#000000`
#### Browser / OS version

Chrome Version 51.0.2704.103
Mac OSX 10.11.3
#### Screenshot / Video

![screenshot 2016-07-01 13 19 03](https://cloud.githubusercontent.com/assets/4924246/16533561/762e3f02-3f8e-11e6-86dc-0a3b73c15b61.png)

**Comment by fraying** [comment]
No longer happening.
