### ISSUE TITLE
Gutenberg plugin: changes to RTL image margin CSS breaking layout

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#64927]
### Quick summary

It appears that the latest Gutenberg plugin makes changes to default styles for image margins, and in this specific case that appears to break a page layout without an obvious solution.

### Steps to reproduce

1. Add columns block
2. Insert images into the column blocks
3. Toggle Gutenberg on and off to see the difference in styles

### What you expected to happen

The styles shouldn't have changed in this way

### What actually happened

It appears that the images are no longer having some margin styles applied:

Without Gutenberg:
![Markup on 2022-06-24 at 09:40:12](https://user-images.githubusercontent.com/22053773/175488515-c443a1d2-8518-4d66-a63b-f931c866073c.png)

With Gutenberg 13.5.0:
![Markup on 2022-06-24 at 09:39:52](https://user-images.githubusercontent.com/22053773/175488537-cc0ace55-5023-40dc-a92a-382fb1319074.png)

### Context

5321874-zd-woothemes

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Only workaround I could think of involves CSS, something like this:

```
.wp-block-column figure {
  margin: 0;
    margin-bottom: 0px;
}
```

**Comment by Greatdane** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - No 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate only on **Atomic**. 
- Self-hosted with Version 13.5.2 seems to show no changes. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Greatdane** [comment]
Asked for more eyes here;
p1656558063049479-slack-CBTN58FTJ

**Comment by Greatdane** [comment]
Closing this as it relates to the broader issue here; https://github.com/Automattic/wp-calypso/issues/64964
