### ISSUE TITLE
Button 2 Blog Posts Block ignoring images on public view

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#64937]
### Quick summary

Featured images appear in Blog posts block in the editor but do not appear on the public site.

### Steps to reproduce

1. Personal plan
2. Add a blog posts block in a grid format with featured images show in a post (note user case is in a post) 
3. Look at the preview, the featured images are missing

### What you expected to happen

The featured image to show

### What actually happened

The featured images are missing

### Context

5320700-zd

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Button 2

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - no

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate and it's a known thing with the older themes.

📌 ACTIONS

- Closed as duplicate of https://github.com/Automattic/themes/issues/4324 and https://github.com/Automattic/newspack-blocks/issues/399
