### ISSUE TITLE
Marketplace search: Filter by Author returning different results than wporg

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#64939]
This is a follow-up of the task https://github.com/Automattic/wp-calypso/issues/64801 and the PR https://github.com/Automattic/wp-calypso/pull/64848#pullrequestreview-1017442611 . Filtering by author in wp.org returns different results than filtering by author using `jetpack-search`.

It is not clear how the [`wporg` API handles author names](https://github.com/WordPress/wordpress.org/blob/b6a4561cc3918c5b6a17d8cb860542715769a1f5/wordpress.org/public_html/wp-content/plugins/plugin-directory/libs/site-search/jetpack-search.php#L744) so this should be investigated.

**Comment by gcsecsey** [comment]
I've investigated searching in multiple fields with the current index, using `litespeedtech` as a test based on [this finding](https://github.com/Automattic/wp-calypso/pull/64848#pullrequestreview-1017442611).

There are no results for this query on the index:

```json
GET jetpack-search-20/_search?routing=108986944-0
{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "plugin.author": {
              "value": "litespeedtech"
            }
          }
        },
        {
          "term": {
            "author_login": {
              "value": "litespeedtech"
            }
          }
        }
      ]
    }
  }
}
```

The plugins themselves are in the index though, but they contain `Lightspeed Technologies` in the `plugin.author` field.

```json
GET jetpack-search-20/_search?routing=108986944-0
{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "slug": {
              "value": "dash-notifier"
            }
          }
        }
      ]
    }
  }
}
```

The results also contains `_souce.taxonomy.plugin_contributors` and `_souce.taxonomy.plugin_committers` with the correct value `litespeedtech`. Based on these, maybe we should update the filter logic to also use these fields as a fallback.

**Comment by gcsecsey** [comment]
This issue may have the same root cause: https://github.com/Automattic/wp-calypso/issues/66159

**Comment by gcsecsey** [comment]
Backlog grooming: let's timebox the investigation for this issue (2).

**Comment by epeicher** [comment]
After some investigation, the results returned by ES seem to be expected **but** they do not correspond to the search in `wp.org`. The following query does not return any results because there are no plugins with `author = litespeedtech`
```
GET jetpack-search-21/_search
{
	"query": {
		"bool": {
		  "must": [
		    {
		      "term": {
		        "blog_id": 108986944
		      }
		    },
		    {
		      "match": {
		        "author": "litespeedtech"
		      }
		    }
		  ]
		}
},
"fields": [
  "title.default", 
  "author", 
  "plugin.author"
  ],
"_source": false
}
```
But if instead we search by `litespeed`, some results are returned because the author name matches either `litespeed` or `technologies` but not a mix of both
```
GET jetpack-search-21/_search
{
	"query": {
		"bool": {
		  "must": [
		    {
		      "term": {
		        "blog_id": 108986944
		      }
		    },
		    {
		      "match": {
		        "author": "litespeed"
		      }
		    }
		  ]
		}
},
"fields": [
  "title.default", 
  "author", 
  "plugin.author"
  ],
"_source": false
}
```
The problem here is that this query to `wp.org` actually return results:
```
https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request[page]=1&request[per_page]=24&request[fields]=icons,last_updated,rating,active_installs,tested,-downloaded,-ratings,-requires,-requires_php,-contributors,-added,-donate_link,-homepage&request[locale]=en_US&request[author]=litespeedtech
```
because it seems to be matching `request[author]=litespeedtech` to `LiteSpeed Tech`

@robfelty Do you think the above behaviour is expected? Or should we try to match the same results returned by `wporg`?

**Comment by epeicher** [comment]
Further investigations revealed that the match in `wporg` is probably because the `author_profile` contains the value `litespeedtech`:
```
"author_profile": "https://profiles.wordpress.org/litespeedtech/",
```

While ES results return the `author_login` 
```
          "author_login": [
            "LiteSpeedTech"
          ],
```
that contains that value **but** it is not an _analyzed_ field as indicated in the documentation P2gHKz-1wf-p2#es-mapping-post-author. I do not think changing the mapping of the `author_login` here is an option from `not analyzed` to `analyzed` so we could:
- Include the `author_login` in the search but that should be **case sensitive**. This would imply a search like `developer:"LiteSpeedTech"` which is not very user friendly for a search term.
- Accept that the author should be searched by name but **not** by login. For example approximate terms like `litespeed` or `technologies` would work but `litespeedtech` would not.

**Comment by robfelty** [comment]
If filtering by author, I recommend actually doing a facet, like Jetpack Search does.

Otherwise, just adding the author or author_login to the search query should be sufficient, as they are indexed into the all_content field.

**Comment by epeicher** [comment]
The linked commit https://github.com/Automattic/wp-calypso/pull/67327/commits/3c0238c72c5e0d6d3c8b4378becfb7fa85593cd2 uses `author.raw` to do an exact match query and it fixes the issue searching for `litespeedtech` plugin but it _breaks_ other searches like searching for `developer:"Team Yoast"` which will only return one result.

I am going to investigate alternatives.

To summarise, the current production query uses `plugin.author` and works for Yoast
```
filter[bool][must][][term][plugin.author]: Yoast
```
but it does **not** work for `litespeedtech`
```
filter[bool][must][][term][plugin.author]: litespeedtech
```

**Comment by gcsecsey** [comment]
I also investigated this a bit. I think the linked commit is a good interim solution, and we can iterate further.

#### WP.org

We have several fields that could serve as the source of truth for the author for WP.org plugins. The `author` field seems to consistently contain the author display name, while `author_login` contains the username. The `plugin.author` field is currently mapped from the `header_author` meta field in the `WPES_WPCOM_Plugin_Post_Field_Builder`, and that can contain different names from the `author` field.

Eg. filtering for Yoast on the `author` field:

```json
"hits": [
      {
        "_index": "jetpack-search-21",
        "_type": "_doc",
        "_id": "108986944-p-119548",
        "_score": 14.287711,
        "_routing": "108986944-1",
        "fields": {
          "author_login": [
            "Yoast"
          ],
          "plugin.author": [
            "Team Yoast"
          ],
          "author": [
            "Yoast"
          ],
          "slug": [
            "yoast-test-helper"
          ],
          "author.raw": [
            "Yoast"
          ]
        }
      },
      {
        "_index": "jetpack-search-21",
        "_type": "_doc",
        "_id": "108986944-p-677",
        "_score": 11.95332,
        "_routing": "108986944-0",
        "fields": {
          "author_login": [
            "Yoast"
          ],
          "plugin.author": [
            "Joost de Valk"
          ],
          "author": [
            "Yoast"
          ],
          "slug": [
            "breadcrumbs"
          ],
          "author.raw": [
            "Yoast"
          ]
        }
      },
]
```

#### WC.com

For WC.com products, even on WC.com not all products have an author displayed. For those which have it, the displayed name seems to be coming from the `wcpv_product_vendors` taxonomy. Eg. for `teams-woocommerce-memberships"`:

```json
{
            "wcpv_product_vendors": [
              {
                "name": "SkyVerge",
                "slug": "skyverge",
                "term_id": "1895",
                "slug_slash_name": "skyverge/SkyVerge"
              }
            ]
}
```

So, the `header_author` can contain multiple names in WP.org and we'll definitely use another field in WC.com to get the author name. I think it would be best to map these fields to the `plugin.author` field in the index, and use that field for filtering.

**Comment by epeicher** [comment]
I have iterated over the linked PR and I have found a solution that seems to be working. I will test it more and adding it for review. Commit here https://github.com/Automattic/wp-calypso/pull/67327/commits/c178d189d676e97ddcfeb70b477fc6e27566d3bc

The solution builds a query based on `plugin.author.raw`, so the query will be 
```
bool: {
    must: [ { term: { 'plugin.author.raw': author } } ],
}
```

I have tested and it returns results for queries like:
- `developer:"Automattic"`
- `developer:"Team Yoast"`
- `developer:"LiteSpeed Technologies"`
