### ISSUE TITLE
Unify loading screens in all onboarding flows

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#64960]
# Description

This issue may need cleanup/more definition and collaboration with other Create teams. 

We need to unify the loading screens that users see in signup & onboarding (from the first account screen through to any of the FTM onboarding flows).

Per this P2 convo, pdDOJh-sJ-p2#comment-346,  I pulled these problems:

- From Goals screen, clicking “Hire our experts” (difm) : see interstitial screen says “Laying the foundations”
- From Domains screen to Goals Scree: see “Applying Design” , user has not yet seen design step
- Mismatch in loading UIs: the loading/progress bar shown between domains step and goals is different to the loading screen we see at the end of the flow

See design specs here: pbAok1-2RP-p2#loaders

<img width="550" alt="image" src="https://user-images.githubusercontent.com/5665959/175773806-f5faf35d-e40a-45e9-a4ee-32d0f96fbbde.png">

<img width="547" alt="image" src="https://user-images.githubusercontent.com/5665959/175773816-7afe2b6f-3283-46ee-a987-3ad8097f48c0.png">

<img width="546" alt="image" src="https://user-images.githubusercontent.com/5665959/175773836-9cd02703-7c68-48e6-800f-e7d5d0f6d9c9.png">

# Acceptance Criteria
- [ ] All loading screens in onboarding conform to a specific design standard
- [ ] This issue is fixed https://github.com/Automattic/wp-calypso/issues/65024
- [ ] Check with @saygunnyc  for design specs

# Dev Tasks
- [x] Retrieve intent and currentStep value on Stepper's processing step
- [x] Improve DIFM flow loading screen ( Goals -> Hire our experts )
- [x] Improve loading screen from Domain -> Goals
- [x] Improve loading screen on /wooConfirm step of sell flow, it saying 'Laying the foundations' when navigate to /checkout
- [x] Improve loading screen on /wooConfirm step when data is loading
- [x] Improve loading screen on /importerWordpress to prevent overlapping with the onboarding progress bar on top of screen #64586 

# Testing Instructions
* Start with new account at /start
* Go through each flow from the Goals screen to check consistency of screens (@autumnfjeld  can help with testing)

# Related
https://github.com/Automattic/wp-calypso/issues/65024

**Comment by bangank36** [comment]
I update dev tasks for tracking implementation progress
- Retrieve intent and currentStep value on Stepper's processing step
- Improve DIFM flow loading screen ( Goals -> Hire our experts )
- Improve loading screen from Domain -> Goals
- Improve loading screen on /wooConfirm step of sell flow, it saying 'Laying the foundations' when navigate to /checkout

**Comment by autumnfjeld** [comment]
@bangank36 & @taipeicoder  It might be a good idea to specify the tasks for each loading screen either as clear separate tasks in the issue description or create new separate git issues - so that multiple people could work on this if needed.   If that makes sense......

**Comment by BeyondspaceTeam** [comment]
> @bangank36 & @taipeicoder It might be a good idea to specify the tasks for each loading screen either as clear separate tasks in the issue description or create new separate git issues - so that multiple people could work on this if needed. If that makes sense......

I'll update the tasks in the issue description and update ballpark estimate

**Comment by taipeicoder** [comment]
@bangank36 could you provide ballpark estimates?

**Comment by bangank36** [comment]
> @bangank36 could you provide ballpark estimates?

Hi @taipeicoder, I am about to make it ready for review today, there is some issues with local enviroment, but thanks to your help i have got rid of them

**Comment by bangank36** [comment]
Closed as shipped
