### ISSUE TITLE
[Bug]: CTA for CDN upsells is not precise

### ISSUE THREAD

**Issue by wojtekn** [Automattic/wp-calypso#64975]
### Quick summary

"Available on the Pro plan" CTA points to the plan selector page which allows choosing wrong plan during the flow. 

### Steps to reproduce

1. Create a simple blog
2. Navigate to WP Admin -> Settings -> Performance
3. Click "Available on the Pro plan" action either in CDN or Cloudflare CDN block

### What you expected to happen

I see the checkout for the Pro plan:

`/checkout/{$siteSlug}/pro`

### What actually happened

I see the plan comparison:

`/plans/{$siteSlug}?customerType=business`

### Context

Brought by @sejas under https://github.com/Automattic/wp-calypso/pull/64889

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by wojtekn** [comment]
We could fix it by changing the upsell nudge configuration from:

```
href={ upgradeLink }
```

to:

```
plan={ PLAN_WPCOM_PRO }
```

However, we need to review the context more.

**Comment by Greatdane** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Confirmed. The error looks to be in the slug being incorrect; `https://wordpress.com/plans/site.wordpress.com?customerType=business`

📌 ACTIONS
- Marked as Triaged for Quality Squad review
