### ISSUE TITLE
Ship all FTM flows to all languages

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#64978]
# Description

All recent FTM ship events, as shown in pbAok1-2MG-p2, have initially shipped to english users only. Now it's time to ship to all users!   

Once all translations have been verified for all flows:

# Acceptance criteria & ToDos
- [ ] https://github.com/Automattic/wp-calypso/issues/63076 is done
- [ ] https://github.com/Automattic/wp-calypso/issues/63119 is done
- [x] Coordinate with  Caribou (@vishnugopal ) and  @Automattic/apex  (@yansern) as needed to ensure their screens & flows are fully translated
- [x] Probably want to ship to horizon to make testing easy
- [x] Post on CfT dtkmj-p2 , here's a similar example: pdtkmj-1y-p2 , make sure to have a group of specific people to ping to get a minimum feedback. People who speak 16 Magnificent Languages PCYsg-9nE-p2  :)  Check with @zachspears  if he can help recruit non-english HEs

# Dev Tasks
- [ ] #65399
- [ ] #64978

# Related
https://github.com/Automattic/wp-calypso/issues/63076
https://github.com/Automattic/wp-calypso/issues/64185
https://github.com/Automattic/wp-calypso/issues/64978#issue-1285628446

**Comment by miksansegundo** [comment]
There are still pending **Swedish** translations for the [vertical posts](https://dotcomverticalposts.wordpress.com/):

- [Sweet success](https://mc.a8c.com/patterns-toolkit/block-patterns/index.php?site=dotcomverticalposts.wordpress.com&theme=Hever&pattern=30&language=sv) is 89% done.
- [Sweet success 2](https://mc.a8c.com/patterns-toolkit/block-patterns/index.php?site=dotcomverticalposts.wordpress.com&theme=Hever&pattern=34&language=sv) is 78% done.
- [Getting started can be the hardest part](https://mc.a8c.com/patterns-toolkit/block-patterns/index.php?site=dotcomverticalposts.wordpress.com&theme=Hever&pattern=18&language=sv) is 71% done.
- [Work hard. Work smart](https://mc.a8c.com/patterns-toolkit/block-patterns/index.php?site=dotcomverticalposts.wordpress.com&theme=Hever&pattern=15&language=sv) is 88% done.

**Comment by miksansegundo** [comment]
There are still pending **Swedish** translations for some vertical posts:

- "Sweet success" is 89% done.
- "Sweet success 2" is 78% done.
- "Getting started can be the hardest part" is 71% done.
- "Work hard. Work smart" is 88% done.

**Comment by miksansegundo** [comment]
There are still pending translations for FR, HE, JA:

[Choose a category that defines your website the best.](https://translate.wordpress.com/projects/wpcom/-all-translated/828361)
[What’s your website about?](https://translate.wordpress.com/projects/wpcom/-all-translated/828360)
[We will use this information to guide you towards next steps.](https://translate.wordpress.com/projects/wpcom/-all-translated/828359)
[Ex. Cafe, Education, Photography](https://translate.wordpress.com/projects/wpcom/-all-translated/828358)

I have already contacted the i18n team.

**Comment by autumnfjeld** [comment]
@miksansegundo I think this issue should be in "In Progess", ya? Can you update it on the Ganon Board.

**Comment by miksansegundo** [comment]
@autumnfjeld done 👍

**Comment by miksansegundo** [comment]
There is still an open issue causing RTL CSS issues. I have created an [i18n issue](465-gh-Automattic/i18n-issues) and xposted it.

**Comment by taipeicoder** [comment]
Closing this one as it's been shipped, announcement [here](p7DVsv-eZD-p2).
Follow-up tasks will be split into individual issues.
