### ISSUE TITLE
Marketplace: announcement modal for Starter plan eligibility 

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#64972]
### Details

Launching premium plugins on Starter plan is something we want to broadly announce (pdG1ka-at-p2). Let's figure out the best way to do so, probably by using the announcement modal component.

- [x] Only shown to sites with starter plan.
- [x] Shown in plugins page and home page.

**Comment by cpapazoglou** [comment]
@vinimotaa  can you provide the design and the copy?

**Comment by emmnyc85** [comment]
I am holding off on providing an update on copy until we address this: pdgrnI-1mi-p2#comment-2372

tl;dr - are we going to build a plan for launching buying marketplace products on all plans in July? If so, we will rework the marketing plan

**Comment by vinimotaa** [comment]
@cpapazoglou @emmnyc85 

We'll probably follow @SaxonF 's suggestion - design-wise we'll follow something we already have in place. So we're just depending on the content/CTAs so the we can design a few variations and have a discussion

**Comment by emmnyc85** [comment]
My recommended language is as follows. We'll be able to use this as well for the other plans when they launch with limited atomic too.

Option 1:

You can now extend your site's capabilities with premium themes and plugins. Available for purchase in our marketplace.

CTA: Explore now

Option 2:

We've made both premium themes and plugins available for purchase in our marketplace.

CTA: Explore now

Feedback from me:
- I think Option 1 is more effective as it focuses more on user value
- In Option 1, I included 'available for purchase in our marketplace' so that customers are not surprised to learn they need to pay for these

**Comment by vinimotaa** [comment]
Hi @emmnyc85, thanks for the content.

For this broad announcement this is what we can do; follow a similar approach we had when we launched the Marketplace.

- One-time popup window for returning users
- One-time popup window once a logged-in user goes to any part of WordPress.com
- A CTA that will take users to the Marketplace
- (Suggestion) A CTA that can take users to our Blog Post
- A "close" button to dismiss the notification

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/97929097/176467734-9697ebcd-bdbf-4b93-b571-49a31cff176e.png">

Please let me know your thoughts!

cc @cpapazoglou @SaxonF

**Comment by emmnyc85** [comment]
Thanks, @vinimotaa. Some items below:

**Copy:** I realize it's very redundant. 
- Title: Install plugins and themes for your site!
- Copy: You can now extend your site's capabilities with premium themes and plugins. Available for purchase in our marketplace.
- CTA: Explore now

**Your suggestions:** I'm not fully following. For now, we just want these popup modal(s) to generate awareness and drive people to the plugin page (once limited atomic launches for them). at the moment, there's no need to think about driving customers to a blog post - that will come later.
- How do you first two items listed differ?
- No need for the additional CTAs at the moment unless you have a strong POV and want to share about where this or thede would go.

Thanks again!

**Comment by vinimotaa** [comment]
Thanks @emmnyc85!

Here's the iteration;

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/97929097/176470419-f0caea55-a7d8-4c4e-91ef-35b2c609d505.png">

The suggestion to take them to a blog post was to give them a bit more of context to what that means - going from an assumption a user isn't fully aware of our different "ifs" when it comes to different plans/permissions :)

**Comment by emmnyc85** [comment]
Thank you!
- Looks good
- I hear you on blog post but we won't have that ready yet. At the moment this is a limited launch to people on specific plans vs. an all out announcement, the latter of which will come later

**Comment by emmnyc85** [comment]
Maybe we should add a banner in the /plugins page to drive better awareness? What could that look like @vinimotaa? That could reiterate the message that this is available for premium plugins and themes and avoid confusion about that

**Comment by emmnyc85** [comment]
Also - can we change your image to read 'premium plugins and themes' instead of 'premium themes and plugin' please, @vinimotaa? 🙏  Thank you!

**Comment by vinimotaa** [comment]
Hey @emmnyc85 

This is also something I worked on as an alternative to the pop up - copy and CTA not final.

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/97929097/176477953-f141b123-59c6-4dca-a66d-d92622b641da.png">

Will tag @SaxonF for feedback as we discussed that this might not be the best spot to handle this messaging.

**Comment by vinimotaa** [comment]
This is the updated version of our pop up design;

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/97929097/176478320-d83688d9-e77b-4d73-a33b-36402305ea06.png">


Source can be found on [this Figma file](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=2353%3A25135)

**Comment by emmnyc85** [comment]
Thanks, @vinimotaa 

For the messaging within /plugins, we could the title/header to: Install premium plugins and themes for your site.
Then the CTA takes them right to the premium / paid selection

I do worry about customer confusion with these updates and not realizing that they can't purchase or use free plugins

**Comment by vinimotaa** [comment]
@emmnyc85 I think this is how we have now on this design? Is there anything else to be changed?

![image](https://user-images.githubusercontent.com/97929097/176533936-41277dd5-0033-4835-9ce8-70c9a8d37578.png)

**Comment by cpapazoglou** [comment]
> @emmnyc85 I think this is how we have now on this design? Is there anything else to be changed?
> 
> ![image](https://user-images.githubusercontent.com/97929097/176533936-41277dd5-0033-4835-9ce8-70c9a8d37578.png)

@vinimotaa The announcement modal is still available (https://wpcalypso.wordpress.com/devdocs/blocks). Do you prefer using a modal or this banner? Can you provide the component name for this banner?

**Comment by SaxonF** [comment]
I would lean towards just using the modal for the announcement. The banner feels too intrusive but we could look at doing something inline attached to the "top premium plugins" section if we thought it was completely necessary e.g. a "new" badge next to the header or similar. I'm not convinced it would make a tangible difference though.

In terms of copy, is "themes" necessary here? Are we announcing anything new with themes? I also don't know if we are ready to position themes as included in the marketplace just yet.

**Comment by emmnyc85** [comment]
@SaxonF - we are planning to announce that they can purchase first party themes. 

However, to keep things simple and make sure the premium angle is clear..let's go with adjusting the title as follows
Title: Install premium plugins on your site
Copy: [keep as is]
CTA: [keep as is]

When we do the broader/bigger announcement to all customers, we will make it clear about 1st party / premium themes

Given both @SaxonF's and @cpapazoglou's feedback, let's not to do in-product CTA and only focus on the modal

**Comment by vinimotaa** [comment]
Thank you for your feedback everyone!

Here's the iterated version;

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/97929097/176922669-e6562e1a-03c4-4d6b-9bd4-3a7fd53826fb.png">

[
Figma Link](**url**)

**Comment by cpapazoglou** [comment]
Let's remove "themes" from the copy and hold off merging it after pdtkmj-dL-p2 is launched.

**Comment by cpapazoglou** [comment]
@emmnyc85 I believe we should only target the following segment?:
- starter plan sites

**Comment by emmnyc85** [comment]
Correct, @cpapazoglou. Let's aim for 7/13 launch as that's a week after the product change occurs, and we want to ensure it functions effectively first

**Comment by vinimotaa** [comment]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/97929097/177347807-5912df22-4b8e-4e51-842b-b336a9212a60.png">

Would that be something like this?

@cpapazoglou @emmnyc85

**Comment by emmnyc85** [comment]
Thanks, @vinimotaa. Let's please remove 'You can now' and just start with 'Extend' and see if that gets us to 2 lines, instead of 3 :)

**Comment by vinimotaa** [comment]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/97929097/177367047-7e99babb-00c4-4ff3-b08c-3ada98e5cebd.png">

Nice!

My only thought on this is that - from this copy, it doesn't sound like a "benefit was unlocked" for me, but more like, "oh, by the way, you can purchase our plugins".

Any thoughts?

**Comment by emmnyc85** [comment]
Thanks, @vinimotaa. How would you adjust? I wrote this to make it clear that they need to purchase vs setting the wrong expectations. I'm sure there are better ways to approach though. Interested for your thoughts

**Comment by vinimotaa** [comment]
Access to Figma:

https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=2442%3A35703

**Comment by emmnyc85** [comment]
Thanks, @vinimotaa. What are our copy recommendations? It says new right above the headline text too

**Comment by emmnyc85** [comment]
Just to keep track:
- We removed 'and themes'
- I just **added a comment / ask** to change 'in our marketplace' to 'on the plugins page' as that is clearer for the customers. They have no knowledge of a marketplace or where it lives cc: @vinimotaa

**Comment by vinimotaa** [comment]
![modal](https://user-images.githubusercontent.com/97929097/178278216-bc216107-7eeb-4955-b849-99b58de06bb8.png)

Copy updated @emmnyc85!

https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=2442%3A35703

**Comment by emmnyc85** [comment]
Thanks, @vinimotaa. Should the plugins page be hyperlinked just in case that's where a user decides to try to click? Or will drawing attention to that cause confusion?

**Comment by vinimotaa** [comment]
@emmnyc85 I don't think is needed - generally, a modal has only one goal and the main CTA. I'd rather simplify to;

- When a user clicks on "Explore" they go to the Marketplace
- When a user clicks on "x" or outside the modal, it dismiss it

**Comment by emmnyc85** [comment]
Got it - thanks for clarifying!

**Comment by cpapazoglou** [comment]
@vinimotaa I noticed that typography and the background color of the image are different than the original `AnnouncementModal` component found here https://wpcalypso.wordpress.com/devdocs/blocks. Is that on purpose? If yes, can we make sure that:

1. When the design of the component changes, communicate clearly which are the changes. We might need a separate issue for this.
2. Use colors found in our design systems, I can see `#F0F7FC` for the background but don't know to what it matches on our design system

FWIW, it looks like this without any design change

<img width="1326" alt="CleanShot 2022-07-12 at 15 52 40@2x" src="https://user-images.githubusercontent.com/12430020/178494413-bc06b83f-631b-44a7-95a2-348fdd99b635.png">

**Comment by emmnyc85** [comment]
@vinimotaa - What @cpapazoglou  shared above doesn't render great. The text is off. Let's make sure it looks [like your version](https://github.com/Automattic/wp-calypso/issues/64972#issuecomment-1180428309)

**Comment by vinimotaa** [comment]
@cpapazoglou - thanks for highlighting the blue, and that's fine to keep the one we have in place. As per typography size, I've been using the size and type from our design system. What I have changed from the original modal overall was the title size to accommodate longer titles. The first modal (you can see below) uses a 44px font which I think is way too big for the size of the title we have. 

Would that be ok to keep these 2 modal versions? So we have them for 2 different cases?

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/97929097/178511789-5eed763a-0fe0-4313-b7df-be0b8807bc88.png">

Another detail we can improve on is the proportion of the copy side (white column) and make it bigger. Not sure if you work with proportion or pixel for this, but this could be 60%/40%?

What is the best way I can share the specs with you?

**Comment by vinimotaa** [comment]
Using the original Figma component, this is how it would look like:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/97929097/178515068-c5ce1b49-78a9-49a8-9ba9-262186d0b9e3.png">

**Comment by emmnyc85** [comment]
can we make the header look better please? it's over 4 lines and should be on 2-3 probably, @vinimotaa

**Comment by cpapazoglou** [comment]
@emmnyc85 I will change the `font-size` and proportion of the copy side and we should be OK.

@vinimotaa, for the future a figma link with notes for each change should be enough.

**Comment by emmnyc85** [comment]
@cpapazoglou thank you! will you please share an updated image here? I need it for a separate P2 update too ;)

**Comment by cpapazoglou** [comment]
Here you are @emmnyc85 

![CleanShot 2022-07-14 at 14 15 50@2x](https://user-images.githubusercontent.com/12430020/178970534-ad426ae2-b55a-4b3b-b692-c1d32da24726.png)

**Comment by emmnyc85** [comment]
Thanks, @cpapazoglou.
A couple last min considerations:
- Should we change the image on the right to something celebratory a la 🎉 
- The 2nd and 3rd lines of text plugins to Available don't look great. Should there be a tiny increase in space between the two?

cc: @vinimotaa

**Comment by cpapazoglou** [comment]
> The 2nd and 3rd lines of text plugins to Available don't look great. Should there be a tiny increase in space between the two? 

I am not sure what you mean, this is one paragraph. I think we are over optimising for english texts.

**Comment by vinimotaa** [comment]
Hey folks, I think if we increase bit the text box it would help. It seems we have some real estate available on the white hand side;

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/97929097/178976301-88d0f237-e441-4b98-8b58-d68640f2fcf3.png">

**Comment by emmnyc85** [comment]
Understood, @cpapazoglou. Will leave to our expert, @vinimotaa, to make any adjustments

@vinimotaa  if you make any changes, will you please share the final version here?

**Comment by cpapazoglou** [comment]
@vinimotaa this is the text box area

<img width="796" alt="CleanShot 2022-07-14 at 14 55 00@2x" src="https://user-images.githubusercontent.com/12430020/178976772-a58e89cc-00fe-47d3-8653-24c0bd9461ac.png">

Again, we should avoid optimising the designs for each new announcement. The design should be universal and adapt well for all languages.

**Comment by vinimotaa** [comment]
Got it @cpapazoglou - that looks fine to me. This should be able to host any announcement/message we might have in the future.

@emmnyc85 for illustrations, this is the closest we have to illustrate this message. It seems we won't be able to make any illustration request as of now.

**Comment by emmnyc85** [comment]
Thank you both!

**Comment by vinimotaa** [comment]
@cpapazoglou @emmnyc85 

Hey folks, I just came across the modal pop-up we implemented - is the "Explore" button working on your end? It seems I clicked on "Explore" and the modal simply closed - is that intentional to use the "Explore" button to close the modal? Or the plan is to take users to the Plugins page?

**Comment by emmnyc85** [comment]
We should take the users to the plugin page

**Comment by emmnyc85** [comment]
*PAID plugins page :)
