### ISSUE TITLE
Jetpack: handle annual vs monthly plan changes

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6499]
Investigate what flows make the most sense when a user has an annual Jetpack plan and decides to switch to a monthly plan or vice versa. We currently treat our annual and monthly plans like separate products, so users can incorrectly purchase multiple plans.

**Comment by lamosty** [comment]
> Investigate what flows make the most sense

What do you mean by this? I'm not too versed in Jetpack plans but I think we should simply fix the fact that user can purchase multiple Jetpack plans.

Fix it like:

1. Have annual plan and switches to monthly in 30 days after purchase of the annual plan -> annual plan is refunded and monthly plan is subscribed/purchased.
2. Do the same vice-versa.
3. Before refunding, verify whether user has already switched between plans and was refunded in the last year. If yes, warn him and if agrees, don't refund and switch to the desired plan.

What do you think?

**Comment by rickybanister** [comment]
cc @johnHackworth @roccotripaldi 

Let's make sure you can't go back to the plans page, toggle to monthly from yearly and purchase the same plan you already have.

**Comment by bubel** [comment]
In my testing, the "Upgrade" button appears to be removed from the monthly/annual counterpart of any given plan that a user has purchased. This was a problem in the past Plans page, but the recent-ish update seems to have resolved it. 

Please confirm:

1) Purchase a monthly or annual Jetpack plan.
2) Go to /plans/ and toggle the annual/monthly option.
3) You should only see the "Upgrade" button attached to the Professional subscription if you are currently on the Premium. It should not appear anywhere else.

**Comment by sirreal** [comment]
Monthly/yearly plan switching will be handled by #12746

**Comment by johnHackworth** [comment]
@sirreal that issue left the monthly/yearly toggle out of scope, since the backend wasn't ready yet. So I'm going to reopen this one and use it for that feature :ghost:

**Comment by johnHackworth** [comment]
This is the design, though:
![image](https://cloud.githubusercontent.com/assets/1554855/26351091/43d7d346-3fb6-11e7-82d4-966279e39ec8.png)

**Comment by tyxla** [comment]
I've started working on this one in terms of upgrading from a monthly to yearly plan:

* #14856 - allows user to upgrade from a monthly to a yearly plan in the Purchase Details page.
* #14850 - allows user to upgrade from a monthly to a yearly plan in the Plans page.
* D5920-code - introduces a relevant discount when upgrading from a monthly to a yearly plan.

**Comment by tyxla** [comment]
All three of the above have landed.

AFAIK we're not planning any yearly-to-monthly downgrading or any other plan (down|up)grades that are currently not supported, so I'm closing this one.
