### ISSUE TITLE
Unified Design Picker

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#64998]
# Description
We were given the go ahead to start foundational work on the unified design picker.  (It is expected that this will deprecate the combo of v13n DP & standard DP).   A wireframe prototype is proposed here Combined Design Picker: Early Beginnings pbAok1-2WW-p2. While this is NOT a final design, it is enough for us to get started on the structure, and then loop back with @saygunnyc and @nuriapenya .  Note that while Saygun is AFK, Núria can answer any design questions and @simison can guide with any scope questions while Autumn is AFK.

![image](https://user-images.githubusercontent.com/5665959/177328337-78c6848c-488d-4635-a881-fcf909c6d402.png)

**One criteria of this work is to be very economical with dev time:**
* reused existing components
* evaluate dev time vs user value
* discuss with designers if some small details are overly complicated 

**Some notes to help guide this tech foundation work**
* No need for a carousel, we have only 3 verticalized designs to start with.
* Allowing tall thumbnails for regular themes isn't necessary, can use current size format, but if easy to extend thumbnail height then go ahead
* Category component exists in calypso /plugins screen already.
* Current design is wireframe, so don't spend time on small UI details until Saygun has detailed designs ready

 
## Design Specs
Design Specs yet to be finalized.  Additionally changes in the DP may be impacted by data collected after MVP Launch

# Acceptance Criteria
The unified DP should
- [ ]  show a section of verticialized designs 
- [ ]  show a section of traditional themes, just as the existing standard DP  (some of these themes may be verticalized per 77-gh-Automattic/ganon-issues)
- [ ] have a horizontal category selector (use existing component from plugins see example UI )
- [ ] Please work with Saygun on these criteria

# Dev Tasks

# Related

**Comment by autumnfjeld** [comment]
@fushar and @taipeicoder   After talking to @simison today  I fleshed out this issue and we have go ahead on the technical foundations.  Ashar: please make the  research on the API a priority and comment in pbAok1-2WW-p2 as we discussed in Ganon sync.   Mikael can answer questions if you need additional guidance. :)

**Comment by taipeicoder** [comment]
Confirmed with @saygunnyc and @simison on these points:

- We will implement Approach 1.
- Leave carousel for later and only show 3 designs.
- Leave tall standard theme cards for later and use the current height.
- Leave preview window as we currently have it.

**Comment by simison** [comment]
>Leave tall standard theme cards for later and use the current height.

Tall cards for first 3 generated designs are still important, though! The designs are more similar to each other by their nature, hence taller preview will be helpful. For regular themes old preview size works fine.

**Comment by roo2** [comment]
Posting my dev todo list here for more visibility on progress:
- [x] Add unified design picker and feature flag (copy static design picker)
- [x] Remove redundant code and features
- [x] Restyle and update text to match new layout
- [x] Implement categories with new component
- [x] Update categories to use data structure from new API
- [x] Add generated designs
  - [x] Display generated designs
  - [x] Preview, generated designs
  - [x] Select generated designs
- [x] Ensure preview and design selection works
- [ ] ~Update style to closely match designs~
    note: since designs weren't finalized, we're just trying to match existing UI style.
- [x] Update to use new API
- [x] Ensure recommended category feature works 
- [ ] ~See if we can implement the dynamic heading "Preferred by {_travel_} {_bloggers_}"~ won't have time for this
- [x] Get back button working correctly
- [x] Test other features
  - [x] Premium themes upsel
  - [x] Different copy depending on write or build goal
  - [x] ~`newDesignEnabled` feature https://github.com/Automattic/wp-calypso/pull/65320~
      note: gnereated designs don't support previews being optional when this feature is disabled
  - [x] Ensure other design pickers work when flag is disabled
  - [x] Tracking
    - [x] On page load `calypso_signup_unified_design_picker_view` is sent once
    - [x] On design preview `calypso_signup_design_preview_select` is sent
    - [x] On design select `calypso_signup_design_type_submit` and `calypso_signup_select_design` are sent
    - [x] On skip button click `calypso_signup_skip_step` is sent 
    - [x] On first scroll on mobile `calypso_signup_scroll_page` is sent once
  - [x] Seller flow work (whatever's implemented so far)
    - [x] Seller upgrade modal ( `"signup/seller-upgrade-modal` )
  - [x] Non-english users
  - [ ] Other features...

**Comment by taipeicoder** [comment]
@roo2 I think we can close this one.

**Comment by arthur791004** [comment]
Close it as it's shipped 🎉
