### ISSUE TITLE
Marketplace: Add back 2fa branding

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#64992]
We added dotcom branding to the Woo 2fa screen: https://github.com/Automattic/wp-calypso/pull/64716
And reverted it: https://github.com/Automattic/wp-calypso/pull/64839

We need to add back branding following the recommendations here: p58i-cye-p2

Acceptance criteria:
- [ ] When logging in as a dotcom partner, the branding on the 2fa screen stays consistent with the log-in branding.

**Comment by lsl** [comment]
FYI 2fa tests being added here https://github.com/Automattic/wp-calypso/pull/65068
