### ISSUE TITLE
Marketplace: June search data snapshot report

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#64995]
Repeat pdh6GB-1bw-p2 for June by following this guide: PCYsg-ID9-p2

Acceptance criteria:
- [x] p2 report posted

**Comment by lsl** [comment]
Might also be able to do this at the same time: https://github.com/Automattic/wp-calypso/issues/65278

**Comment by allilevine** [comment]
I started running queries for this but I couldn't get data for June 28-30. I got a `Cannot cast 'test' to INT` error.

Posted some results through the 27th here: pdh6GB-1kr-p2#comment-2200

**Comment by allilevine** [comment]
It turns out there was an event where the `results_count` was `test`. Asked about it here: p1657565533967789-slack-C029JEQRVRT

I added `and element_at(eventprops, 'results_count') != 'test'` to the query to work around it.

**Comment by allilevine** [comment]
Snapshot posted: pdh6GB-1yg-p2
