### ISSUE TITLE
Analyse and create a list of issues for https://dotcommarketplacep2.wordpress.com/2022/06/14/products-licensing-take-2/#comment-1951

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#65004]
After analysing pdh6GB-1dL-p2#comment-1951, we created following GH issues.

- [ ] https://github.com/Automattic/wp-calypso/issues/65345
- [ ] https://github.com/Automattic/wp-calypso/issues/65346
- [ ] https://github.com/Automattic/wp-calypso/issues/65347
- [ ] https://github.com/Automattic/wp-calypso/issues/65348
- [ ] https://github.com/Automattic/wp-calypso/issues/65349
- [ ] https://github.com/Automattic/wp-calypso/issues/65351
- [ ] https://github.com/Automattic/wp-calypso/issues/65518

**Comment by cpapazoglou** [comment]
I have also added a docs issue. I think this is now completed?

**Comment by gavande1** [comment]
Yes. I am marking as completed. If child issues are needed in any case then you created them under above tasks.
