### ISSUE TITLE
Calypso version of tag and category editing is missing error warnings

### ISSUE THREAD

**Issue by kristinaquinones** [Automattic/wp-calypso#65008]
### Quick summary

When a user is on a Simple site using the Calypso view and they attempt to make a disallowed edit to their tags, the UI appears to "hang", but there is no indication to the user about what the error might actually be. Sometimes (but not always) the user might see the "Name already exists" error, but this doesn't seem to show up consistently _in time_ to prevent the user's attempt to rename the tag.
 
If the user happens to switch to WP-Admin view under **View**, then in that case, they'd see the following error upon their attempt to save a duplicate: 
`The slug "slug" is already in use by another term.`

### Steps to reproduce

1. Have a Simple site
2. Create a few tags
3. Try to change an existing one so that it's a duplicate of one of the other tags

### What you expected to happen

Either
- consistently display the error(s) that would indicate the duplication issue
or
- allow for duplicate titles with unique slugs (though I suppose this would require the ability to edit slugs on Simple, eh?)

### What actually happened

This is not consistently replicable, but as the customer reported, and as I initially experienced, attempting a disallowed change to the tag would result in the page "hanging" with a grayed out save button, but no indication of action failure.

### Context

5330775-zd
34965174-hc

### Simple, Atomic or both?

Simple

### Reproducibility

Intermittent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround would be to edit one's other tags first, or perhaps simply moving posts to the tag you want to "keep"

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- On WP Admin, when I use Quick Edit and try to rename a tag to a name matching an existing tag, I see the error "The slug “slug” is already in use by another term." When I use Edit, I see a more generic error: "Tag not updated."
- On Calypso, when I try to rename a tag to a name matching an existing tag, I immediately see the error "Name already exists". I was not able to recreate the hanging error. 
- I tested on simple and Atomic, Chrome and Safari.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
