### ISSUE TITLE
Plans Redesign: conditionally display plan features

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6500]
Some plan features are still being abtested (like wordads), we should conditionally display these features on the PlanFeatures component. We can see which abtests are active in `client/lib/abtest/active-tests.js`

To see the new plans page, start Calypso with `ENABLE_FEATURES=manage/plan-features make run` and navigate to http://calypso.localhost:3000/plans

**Comment by lamosty** [comment]
List of active tests that touch plans in some way:

- `wordadsInstantActivation`;
- `googleVouchers`;
- `wordpressAdCredits`.

**Comment by lamosty** [comment]
We will need to add the description of Premium plan with `wordadsInstantActivation` enabled.

**Comment by lamosty** [comment]
Fixed in #6567.
