### ISSUE TITLE
Plans Redesign: conditionally display personal plans

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6501]
Personal plans is still being tested, so we should only display this in the PlanFeatures component when it matches our abtest variant.

This means that the http://calypso.localhost:3000/plans may show 2-3 plans, while a nux flow would display between 3-4 plans.

To see the new plans page, start Calypso with `ENABLE_FEATURES=manage/plan-features make run` and navigate to http://calypso.localhost:3000/plans

**Comment by lamosty** [comment]
![selection_029](https://cloud.githubusercontent.com/assets/4988512/16566772/d6cab40e-4217-11e6-9132-f9e9d3483888.jpg)

Fixed in #6376.
