### ISSUE TITLE
EligibilityWarnings component displays confusing message on sub-business plans

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#65013]
### Steps to Reproduce

When an Atomic site, with a sub-Business plan, has the 'atomic' feature, but not the 'upload-plugins' feature, the [EligibilityWarnings](https://github.com/Automattic/wp-calypso/blob/78f4c49d39513187377d48db0ce35b91fc58a315/client/my-sites/plugins/plugin-upload/index.jsx#L109) component displays a confusing message about "Installation in progress." on the /plugins/upload/{site_slug} page.

I believe there are plan checks that need to be converted to feature checks inside the component. https://github.com/Automattic/wp-calypso/blob/2d31a9636cd58d74518c34511a2aceca43169db9/client/blocks/eligibility-warnings/hold-list.tsx#L181-L187

To reproduce: In WPCOM add the 'atomic' feature to Premium plans. Make sure Premium plans do not have the 'upload-plugins' feature. Apply the diff below (to prevent redirects and always show the EligibilityWarnings component), sandbox the API, and go to /plugins/upload/{site_slug}

```
diff --git a/client/my-sites/plugins/plugin-upload/index.jsx b/client/my-sites/plugins/plugin-upload/index.jsx
index 7e0697fae0..be0b9d1a0e 100644
--- a/client/my-sites/plugins/plugin-upload/index.jsx
+++ b/client/my-sites/plugins/plugin-upload/index.jsx
@@ -99,17 +99,13 @@ class PluginUpload extends Component {
                const { translate, isJetpackMultisite, siteId, siteSlug, hasUploadPlugins } = this.props;
                const { showEligibility } = this.state;
 
-               if ( ! hasUploadPlugins ) {
-                       page( `/plugins/${ siteSlug }` );
-               }
-
                return (
                        <Main>
                                <PageViewTracker path="/plugins/upload/:site" title="Plugins > Upload" />
                                <QueryEligibility siteId={ siteId } />
                                <HeaderCake onClick={ this.back }>{ translate( 'Install plugin' ) }</HeaderCake>
                                { isJetpackMultisite && this.renderNotAvailableForMultisite() }
-                               { showEligibility && (
+                               { true && (
                                        <EligibilityWarnings
                                                backUrl={ `/plugins/${ siteSlug }` }
                                                onProceed={ this.onProceedClick }

```
 

### Expected (Simple)

Simple sites look correct and show a warning about going Atomic.

### Expected (Atomic)

Atomic sites should show the upload box and not show an eligibility warning to upload plugins.

### Actual

![175618960-12985e7c-83a1-4bf2-8933-c0f982deda3b](https://user-images.githubusercontent.com/140841/176034806-d3b78a3d-5484-4dc3-856e-40fffea9be85.png)

**Comment by obenland** [comment]
On the backend this is already a feature check (2cc5b-pb), so this might have been or will be fixed with D83198-code?

**Comment by mreishus** [comment]
On my starter plan sites, I no longer see an "Upload" button on the top right of `/plugins/<site>?flags=marketplace-starter-plan`. Only "Installed plugins" for an atomic starter site, and no button at all for a simple starter site.

![2022-06-27_17-25](https://user-images.githubusercontent.com/937354/176046086-23989eae-889e-4485-bda2-361f85378ffc.png)

So I can't find a way to get to this screen at all.

**Comment by mmtr** [comment]
> So I can't find a way to get to this screen at all.

Yeah, the motivation here is that we might want to show the Upload button on all sites in order to expose a new upsell. See [this comment](https://github.com/Automattic/wp-calypso/pull/64942#issuecomment-1167860521) from @DustyReagan :

> I initially created this PR with the aims of restoring the "Uploads" button on all plans/sites so as to expose the upsell on the uploads page. However, it seems the [<EligibilityWarnings](https://github.com/Automattic/wp-calypso/blob/78f4c49d39513187377d48db0ce35b91fc58a315/client/my-sites/plugins/plugin-upload/index.jsx#L109) component needs some non-trivial refactoring to get that working.

**Comment by mmtr** [comment]
> When an Atomic site, with a sub-Business plan, has the 'atomic' feature, but not the 'upload-plugins' feature

I'm closing this one, since I don't think this is applicable anymore now that we moved out the atomic feature from the lower-tier plans to the marketplace plugins: D83396-code.

Feel free to reopen if I missed something!
