### ISSUE TITLE
Paid plugins feature is not highlighted in the plans comparison page

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65029]
### Quick summary

The Starter plan will allow users to purchase and install paid plugins, but that feature is not highlighted in the plans comparison page. We might need to also amend the "Sell products with WooCommerce" feature, since that's will be possible on the Starter plan as long as they purchase a WooCommerce paid subscription.

<img width="500" alt="Screen Shot 2022-06-28 at 11 31 41" src="https://user-images.githubusercontent.com/1233880/176145904-49e123b4-da8f-4dcf-a949-bf4f879d800d.png">

### Steps to reproduce

- Go to https://wordpress.com/plans
- Select any site
- Check the features

### What you expected to happen

Support of paid plugins should be listed as a feature of the Starter plan.

### What actually happened

The feature is missing.

**Comment by obenland** [comment]
In the context of the extended rollout plan (pdgrnI-1mi-p2#comment-2391) I'm not sure we need to add those here?

**Comment by mmtr** [comment]
You're right, especially if the feature is eventually included in the Free plan. Let's close this for now.
