### ISSUE TITLE
Get rid of "Applying design" in the loading screen before Goals screen

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#65024]
# Description

The loading screen shows two strings on text between the Signup screens and before checkout (or before Goals if user doesn't go thru checkout).  The "Applying design" string doesn't make sense at this point in the flow, because user has not seen the DP. 

![Image](https://user-images.githubusercontent.com/5665959/176166883-16ae0354-ee8e-4fd2-8925-05c4aee9c4a5.png)

# Acceptance Criteria 
- [ ] only show strings that make sense for this point in the onboarding flow

# Related
[Unify loading screens in all onboarding flows](https://github.com/Automattic/wp-calypso/issues/64960)

**Comment by autumnfjeld** [comment]
@arthur791004  Can we also add:
“Making you cookies”
“Planning the next chess move”

to this list https://github.com/Automattic/wp-calypso/blob/e7ed29a9fcf5a6345cdbcdb0eb50716f26ad20b6/client/signup/reskinned-processing-screen/index.jsx#L40

cc: @that-mike-bal  😄

**Comment by arthur791004** [comment]
Sure! We can add in the follow-up PR and wait for the translation!

**Comment by arthur791004** [comment]
@autumnfjeld Do you have any preference on the order? Here is the current behavior

https://user-images.githubusercontent.com/13596067/176587382-3e853cf4-b267-4090-a9fb-e9a43a8df812.mov

**Comment by taipeicoder** [comment]
Closing, thanks @arthur791004 !
