### ISSUE TITLE
WooCommerce is not activated after purchasing a WooCommerce paid extension

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65027]
### Quick summary

We should automatically activate WooCommerce when a user purchases a WooCommerce paid extension form the WP.com Marketplace.

See these two comments from @ianstewart (pdG1ka-a5-p2#comment-207, pdG1ka-a5-p2#comment-218):
> this, in effect, brings Woo (with&nbsp;WCPay&nbsp;as the default processor) to the <s>Premium</s> Starter Plan&nbsp;<strong>IF</strong>&nbsp;you purchase a premium plugin subscription that extends it

> when you purchase a subscription to a premium plugin that&nbsp;<strong>extends</strong>&nbsp;a free one (like Woo) we would include the activation of the base plugin, in order to make your plugin purchase worthwhile.

### Steps to reproduce

- Go to https://wordpress.com/plugins?flags=marketplace-starter-plan
- Switch to a site with a Free plan
- Purchase any WooCommerce paid extension

### What you expected to happen

The WooCommerce base plugin should be installed and activated as well.

### What actually happened

The WooCommerce base plugin it is not installed/activated.

**Comment by mmtr** [comment]
I gave this a spin and created D83310-code with a rough implementation that it doesn't work yet, but should give us an idea about whether that's the direction we want to take. @obenland would you mind taking it a look? It's mostly based on your work on the Atomic upgrade routines. You're also welcome to take it over if you want!

**Comment by mmtr** [comment]
Oh, [this comment](pdtkmj-dL-p2#comment-404) from @Nic-Sevic is interesting!

> I could install another marketplace plugin with no problem (also, FWIW core WooCommerce did install and activate when woocommerce-subscriptions was added) but in the marketplace these core plugins (woocommerce and yoast) appear not be installed and still allow you to upgrade to pro to user them (even though they were both already installed and activated because of the wc extension and Yoast premium)

So apparently we are installing and activating WooCommerce but we show them as uninstalled in Calypso?

**Comment by obenland** [comment]
> So apparently we are installing and activating WooCommerce but we show them as uninstalled in Calypso?

Yes, there is a filter introduced in 1004-gh-Automattic/wpcomsh that limits the plugins we show on sites without INSTALL_PLUGINS to only the ones they purchased. Not sure how we'd be able to show plugin dependencies, tbh. I imagine it being the same with Yoast SEO Premium and Yoast SEO.

**Comment by obenland** [comment]
More generally: I was surprised to see D83310-code, it feels like that should be working already. It did in my testing

**Comment by mmtr** [comment]
I think we can close this one out. Looks like we are actually installing the base plugins, but I wrongly assumed we don't because I couldn't see them in the UI.

Active plugins visible to user | Actual active plugins
--- | ---
<img width="1257" alt="Screen Shot 2022-06-29 at 11 34 45" src="https://user-images.githubusercontent.com/1233880/176404328-07b7e2c0-edec-4ff6-ba78-a9e2f72b7dbe.png"> | <img width="835" alt="Screen Shot 2022-06-29 at 11 35 42" src="https://user-images.githubusercontent.com/1233880/176404486-429993da-7c3d-4787-9b3d-8660f5afd972.png">
