### ISSUE TITLE
Paid plugins results do not mention that a plan upgrade is required

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65026]
### Quick summary

Paid plugins displayed in the Plugins list page do not display any information mentioning that a plan upgrade is required, unlike the free plugins:
<img width="1277" alt="Screen Shot 2022-06-28 at 10 57 51" src="https://user-images.githubusercontent.com/1233880/176142180-d122bebc-a3c1-414c-83dc-9c2c762b4fb4.png">

### Steps to reproduce

- Go to https://wordpress.com/plugins?flags=marketplace-starter-plan
- Switch to a site with a Free plan
- Search "woocommerce"

### What you expected to happen

Paid plugins results should include a "Requires a plan upgrade" label, just like the free plugins results.

### What actually happened

Paid plugins results do not include a "Requires a plan upgrade" label.

**Comment by obenland** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/65059
