### ISSUE TITLE
Paid plugins cannot be deactivated on the Starter plan

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65028]
### Quick summary

Users can purchase several paid plugins on sites with a Starter plan and they may need to eventually deactivate one or a few of them. Right now, we are not allowing users to do that.

<img width="980" alt="Screen Shot 2022-06-28 at 11 26 27" src="https://user-images.githubusercontent.com/1233880/176145166-bce2f05e-7ef4-4b82-8c73-ae30a71877dc.png">

### Steps to reproduce

- Go to https://wordpress.com/plugins?flags=marketplace-starter-plan
- Switch to a site with a Free plan
- Purchase any paid plugin
- Wait for the plugin to be activated
- Click on the "Manage plugin" button
- Deactivate the plugin

### What you expected to happen

The plugin should be deactivated successfully. 

### What actually happened

We block the deactivation and display an error.

**Comment by obenland** [comment]
To stay in line with the expectations from pdG1ka-8n-p2#comment-187, we should probably just disable the toggles in the UI, just like Autoupdates is disabled (and should be turned on by default).

**Comment by mmtr** [comment]
In that case, since no actions can be performed in that screen, I wonder if it'd be better to just block the access to `/plugins/manage` if the site doesn't have the `MANAGE_PLUGINS` feature?

I also found confusing that we're hiding from that page the base plugins (e.g. WooCommerce) automatically installed after activating a paid extension (e.g. WooCommerce Subscriptions), so blocking access to the list of installed plugins page may also help removing that confusion.

**Comment by mreishus** [comment]
If it's blocked, I'm worried that there's no where to see what marketplace plugins you have paid for and installed. It feels pretty bad to have paid for something and not to see it on your "Plugins" page. 
The `/plugins/<site>` has an "Installed Plugins" button in the top right, which links to `/plugins/manage/<site>` and displays all of your active purchases; I don't think there's any other way to see that information.

**Comment by mmtr** [comment]
>  It feels pretty bad to have paid for something and not to see it on your "Plugins" page.

They would be listed in the Upgrades > Purchases screen though, but I see your point. I'm ok with just hiding the toggle/buttons 👍

**Comment by mmtr** [comment]
This should've been fixed in https://github.com/Automattic/wp-calypso/pull/65065
