### ISSUE TITLE
Change default theme to Livro

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#65035]
The goal of this issue is to have a discussion needed in order to switch the default theme from the current `zoologist` to `stewart` or `livro` that may be better suite for bloggers. The default theme is used when a new WPCOM site is created and the user doesn't specify any other theme during the site setup flow.

---

We paired with @phcp today and found the following together:

1. Changing the default theme is quite straightforward and an example issue and PR can be found below:
- https://github.com/Automattic/wp-calypso/issues/55277
- https://github.com/Automattic/wp-calypso/pull/57134

Generally, in order to change the default theme, we need to replace the [theme slug in two files](https://github.com/Automattic/wp-calypso/pull/57134/files
).

There's also a possibility to switch the default theme depending on the site Intent or user-selected site Goals - if there's a need for that:

e.g.:
```ts
const isWriteIntent = intent === SiteIntent.Write;
const defaultTheme = isWriteIntent ? 'livro' : 'zoologist';
```

2. The Livro theme has dark colors. If we would like to have the Livro as the default theme in light colors, it might make sense to first create [theme variant](pNEWy-exE-p2) e.g. "Livro - light" - in a similar way as we currently have with themes like Quadrat:
![Markup on 2022-06-28 at 17:12:44](https://user-images.githubusercontent.com/25105483/176215662-e7efe165-4ae3-4a68-97b0-3e5b352c4051.png)

---

#### Pre-development check-list
- [x] decide which theme to use as the new default
- [x] decide if we want to use additional logic (e.g. choosing the default theme depending on site Intent / Goals)
- [x] Which questions should we ask ourselves in terms of metrics? What we want to learn and track?

#### Development check-list
- [x] create PR with the change
- [ ] check the new default theme annotations (example: D69509-code)
- [x] inform Happiness before at least 24 h before shipping the change (more info with details: p1657267739664859/1657183599.640279-slack-C02TCEHP3HA)
- [x] deploy the change

---

If you have any thoughts / comments / ideas on the topic, feel free to share them. Cheers! @Automattic/apex

**Comment by yansern** [comment]
> decide which theme to use as the new default

Livro, even though it's dark. Context: p1657186628974399/1657105135.538679-slack-C02M88KJ684

> decide if we want to use additional logic (e.g. choosing the default theme depending on site Intent / Goals)

For `write` intent.

> Which questions should we ask ourselves in terms of metrics? What we want to learn and track?

@simison has got this set up in one of his fantastic spreadsheet (onebin link). 2cd81-pb/

**Comment by ivan-ottinger** [comment]
> @simison has got this set up in one of his fantastic spreadsheet (onebin link). 2cd81-pb/

To make sure I understand correctly: there's no need to implement anything extra in the code, right? 🤔

**Comment by yansern** [comment]
> To make sure I understand correctly: there's no need to implement anything extra in the code, right?

Yup, this means Mikael has gotten the things he needs in Tracks set up to build that spreadsheet.

**Comment by ivan-ottinger** [comment]
Hey @p-jackson 👋🏼 I see you worked on the D69509-code patch when the default theme was set to `zoologist`.

I wonder if there are any instructions on how to create a similar patch for the `livro` theme (which we want to set as the new default). Thank you.

**Comment by p-jackson** [comment]
👋 
This page (PaWIov-3k-p2) has instructions on how to use the `wp linguine send-file` command to kick off the translation process.

It'll return an ID that you can use to track the task, and once complete, run the `wp linguine headstart-deploy` command you see in D69509-code.
