### ISSUE TITLE
Plans: remove unused signup flows

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6503]
Our active signup flows are configured in `client/signup/config/flows`. There are currently 35 flows which is a lot to keep track of. Investigate to see if any of these flows can be removed. Some flows receive very little traffic. Any links pointing to removed flows would default to the main flow.

**Comment by meremagee** [comment]
Thanks for the ticket and the ping! I'll take a peek at the current flows this week and write up some notes. Some flows seem redundant in form but actually kick of different things (like segmented drip emails) after the signup process completes. It's an imperfect way to segment users, but the overhead of refactoring in the short term may not make sense when weighed against implementing a longer term solution.

**Comment by gwwar** [comment]
Thanks @meremagee, if we still have a use for all of these, maybe we could add some additional comments/documentation in the code for where these are being used. This can be helpful when folks who aren't familiar are diving into the code.

**Comment by rralian** [comment]
@meremagee I think we should keep in mind what's in active use. I checked google analytics and out of a sample of over a million NUX landing pages over the past few weeks, only 11 different flows were visited. And 4 of those had 40 visits or fewer (less than 0.00% of all visits). Ping me if you want a link/screenshot. If we dropped down to the top 7, that would simplify things quite a bit.

**Comment by lsinger** [comment]
@rralian can you send me recent data / a recent screenshot?

**Comment by alisterscott** [comment]
Are we still looking to consolidate these?

**Comment by gwwar** [comment]
This likely requires large refactors to how we handle abtests and use this config. Feel free to break out additional issues as needed.

**Comment by mattwiebe** [comment]
Current status: 35 possible flows in `client/signup/config/flows-pure.js`.

In June 2018, 30/35 flows were accessed at least once. The following were not accessed at all and will be eliminated:

```
surveystep
test-site
pressable
get-dot-blog
test-plans
```

These flows brought in very little traffic and $0 (in order of decreasing traffic)

```
subdomain
pressable-nux
jetpack
rebrand-cities
delta-discover
developer
rewind-auto-config
creative-mornings
clone-site
rewind-setup
rewind-switch
store
portfolio
```

The `rewind-*` ones will stay. I will investigate if we are actively sending traffic to any of the others.

**Comment by mattwiebe** [comment]
The list of maybes to remove. Checked = keep it.

- [ ] subdomain
- [ ] pressable-nux
- [ ] jetpack
- [ ] rebrand-cities
- [ ] delta-discover
- [ ] developer
- [ ] creative-mornings
- [ ] clone-site
- [ ] store
- [ ] portfolio

**Comment by mattwiebe** [comment]
After the investigation above, we can remove the following flows:

```
surveystep
test-site
pressable
get-dot-blog
test-plans
jetpack (not used any more)
store (identitical to main, nothing links there)
portfolio (no traffic)
```
