### ISSUE TITLE
[Bug]: Premium themes not working after going Atomic

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#65037]
### Quick summary

I purchased and activated a premium theme (Videomaker White) when the site was simple. Then activated a free theme and went AT with a marketplace purchase. After site was AT I get `Theme not yet available for this site` when I try to activate it. 

When I try to purchase a new premium theme (tested with Kerr and a few others) I get `Sorry, that product is not compatible with sites hosted on WordPress.com.`

### Steps to reproduce

1. Purchase and activate prem theme while simple
2. switch to non premium theme
3. go atomic with plugin install
4. try to reactivate purchased theme > fail
5. try to purchase new prem theme > fail

### What you expected to happen

I should be able to reactivate the theme I previously purchased as well as purchase new premium themes.

### What actually happened

I couldn't reactivate or purchase a new prem theme.

### Simple/Atomic

Atomic

### Reproducibility

Consistent

**Comment by obenland** [comment]
Oh, that's an annoying bug, nice find!

**Comment by mreishus** [comment]
Fix is in wpcomsh v2.9.38 (currently not yet deployed).

**Comment by mreishus** [comment]
Fix is now deployed and I've retested the steps with success. Please re-open if you continue to have issues :)
