### ISSUE TITLE
[Bug]: Removing WooCommerce extension/yoast premium subscription doesn't remove the required (.org) plugin on non eligible plans

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#65039]
### Quick summary

When I cancel the WooCommerce subscriptions plugin, the core plugin stays behind and is accessible (maybe because we're assuming they have orders/customer data they shouldn't lose?)

Except, the same happens with the core yoast plugin

### Steps to reproduce

1. on site with woocommerce extension, cancel the extension
2. check cli and see that core plugin still there and active
3. check core plugin settings and see that can still access
4. duplicate with yoast premium
5. make sure all marketplace purchases removed and see that still Atomic
6. after all is checked maybe also remove the starter plan

### What you expected to happen

When the last extension to whatever core plugin is removed the core should also be removed

When all marketplace add-ons are removed I would also expect the site to go back simple (but maybe it's not because of other add-on possibilities?)

### What actually happened

the core plugins remained and site stayed Atomic

When the starter plan is removed the site is immediately reverted **but the revert warning and confirmation is not show** (and any lingering plugin subscriptions are cancelled as well)

### Reproducibility

Consistent

**Comment by cpapazoglou** [comment]
> When all marketplace add-ons are removed I would also expect the site to go back simple (but maybe it's not because of other add-on possibilities?)

This is what should actually happen. Removing the core (required) plugin shouldn't be automated but if the site isn't eligible to be on Atomic then the site should be reverted to Simple. 

The tricky case is when **the site is on a plan that doesn't support plugin installations from the directory**. On those cases, when the marketplace plugin is removed, the required plugin should also get removed. This check can happen on `Store_Product_Marketplace_Plugins::deactivate`

cc @obenland

**Comment by mmtr** [comment]
> if the site isn't eligible to be on Atomic then the site should be reverted to Simple.

This is not happening at the moment when testing the paid plugins on a site with the Starter plan, but it's because we have a "is proxied" check (D83198-code) which fails during the deactivation of the last marketplace paid plugin because it's a async job.

It should work in production in theory once we remove the "is proxied" check, but would be great if we can come up with something to test it before.

**Comment by mmtr** [comment]
Created D83380-code to fix this.
