### ISSUE TITLE
Nav Unification disabled in wp-admin after restoring the Jetpack connection

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#65040]
### Quick summary

When visiting the plugin settings pages I was getting stuck in the wp-admin dashboard pages and could not get back to calypso without directing accessing a calypso URL. 

I noticed this after I had started testing removing the purchased plugins but before all were removed. I'm not sure if it was happening before then or not

### Steps to reproduce

1. break the Jetpack connection and restore it.
1. visit a wp-admin screen
3. try to get back to calypso pages via sidebar links

### What you expected to happen

Should be able to get back to calypso by going to the dashboard link or one of the jetpack pages at least

### What actually happened

couldn't get back to calypso until I accessed a page directly with the URL

![Screen Capture on 2022-06-28 at 18-45-01](https://user-images.githubusercontent.com/47717887/176223199-9920d9d5-902c-4ad5-a52d-eece4f84a853.gif)

### Simple/Atomic
Atomic

**Comment by obenland** [comment]
It looks like Nav Unification was not active. Did this happen after you deactivated/reactivated Jetpack as reported in #65038?

**Comment by Nic-Sevic** [comment]
Yes, after the Jetpack connection testing

**Comment by mmtr** [comment]
> after the Jetpack connection testing

Was the connection fully restored when you experienced this issue? We check whether the Jetpack user is correctly connected to WP.com (641-gh-Automattic/wpcomsh) before activating Nav Unification on Atomic sites, so maybe is that?

**Comment by Nic-Sevic** [comment]
Yes, I reconnected via the UI flow and made sure everything looked good in debugger. The site I was testing on is reverted now but I can send it back or create a new one and try again if it helps?

**Comment by mmtr** [comment]
>  I can send it back or create a new one and try again if it helps?

Yeah, either option would be helpful to see if we can reproduce this reliably.

Anyway, I don't think this is urgent (looks like an edge case), and it's definitely unrelated to the Limited Atomic work, so I edited the issue to better reflect that this is a Nav Unification issue caused after restoring a Jetpack connection.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tried breaking & repairing JP in 2 ways:

1. Broke and repaired JP via JP Debugger, then visited a wp-admin page in my dashboard.  Nav Unification was present.
2. Broke JP via CLI, and repaired via my site's "Set Up Jetpack" flow.  Once this connected, I landed on the Jetpack Dashboard page with Nav Unification present there as well.

![Markup on 2023-05-03 at 17:00:51](https://user-images.githubusercontent.com/27249804/236076188-230813bf-a3ba-4450-bf91-ea3216f34e65.png)

📌 ACTIONS
- Closing as not reproducible. Please reopen if anyone is able to replicate this again following a JP restoration. Thanks!
