### ISSUE TITLE
Unwanted Button Block Keeps Reappearing Upon Page Edit

### ISSUE THREAD

**Issue by kristinaquinones** [Automattic/wp-calypso#65044]
### Quick summary

A user has reported a consistent issue with unwanted Button blocks being added to their site (adjacent to an existing button block).

(Side note: I've experienced this myself, and it does appear to be limited to Simple sites. The site I experienced this on used a different theme from what the reporting customer is using. I tried looking via Bugomattic and MGS, but I wasn't able to locate a matching bug.)

### Steps to reproduce

1. Create a page on a Simple site, include a button block, save
2. Edit the page

Example affected page: https://wordpress.com/page/sow.zone/4198

### What you expected to happen

Upon opening the page to edit, the page content should be as it was last saved, with no unexpected blocks "added".

### What actually happened

Upon opening the page to edit, an unwanted button block - not added by the user - appears

<img width="1013" alt="Edit_Page_‹_SOW_—_WordPress_com" src="https://user-images.githubusercontent.com/5562083/176247925-26f83d1a-0855-4bbf-b7f5-bf049733c7c6.png">
.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

This doesn't appear to be the case.

### Reproducibility

Intermittent

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is to delete the unwanted Button block prior to saving. The problem is that this does not prevent the issue from happening again— e.g. when they go back to edit this page, the unwanted block is likely to make another appearance.

**Comment by kristinaquinones** [comment]
35927697-hc

**Comment by renata-franco** [comment]
📌 SCRUBBING

- Tested on Simple ✅ 
- Replicable on Core - No

------

📌 FINDINGS/SCREENSHOTS/VIDEO

I cannot replicate this on simple sites. I also checked the chat and the site of the user reporting this and they have an extra empty button block in the code of the post. From what I read in the conversation in Happy Chat, the user duplicates the same post/page again and again and this includes the extra code. See here: 

<img width="1306" alt="imagen" src="https://user-images.githubusercontent.com/81378719/177812107-2cabd05c-f2c9-4ba0-ab50-0413be296a47.png">


------

📌 ACTIONS

- Closed as could not replicate (please reopen the issue reoccurs)

-------

📌 Message to Author

I could not replicate it, but if you are able to replicate it on your end, send us a video to see the process. Thank you!
