### ISSUE TITLE
[Bug]: New feature announcement close button caption is truncated

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#65069]
### Quick summary

When shown a new feature announcement for Professional Email, the close button has a caption that appears when hovering over it.

In Firefox, the caption reads "Clo" rather than "Close" because it is hidden behind another element.

### Steps to reproduce

Sorry - I'm not sure how to trigger this specific message. Does it appear on a brand new account too?

### What you expected to happen

I should be able to read the word "Close".

### What actually happened

The close button caption reads "Clo". The rest is hidden.

<img width="797" alt="Screen Shot 2022-06-29 at 10 57 41" src="https://user-images.githubusercontent.com/17325/176321947-9440c3f2-40d7-4144-b60b-4b2b0c4a278b.png">
<img width="137" alt="Screen Shot 2022-06-29 at 10 57 46" src="https://user-images.githubusercontent.com/17325/176321960-8cbc15dc-bb3c-4e02-9414-48f7f5af69ff.png">

### Context

During testing for another bug

### Browser

Mozilla Firefox

### Reproducibility

Consistent

**Comment by arunsathiya** [comment]
Quick note for @Automattic/dotcom-pqa-group that run into this: there's an ongoing discussion here: p1656488104122729/1656452253.118529-slack-C01TJT42PMM
