### ISSUE TITLE
[Bug]: Settings - Performance page not showing all options on Jetpack-connected sites

### ISSUE THREAD

**Issue by coder-karen** [Automattic/wp-calypso#65077]
### Quick summary

Navigating to Settings > Performance for a Jetpack-connected site, the only thing on display is Jetpack Search.

With some testing it looks like this PR - https://github.com/Automattic/wp-calypso/pull/65010 - may be the cause here?

Reported here: p1656470885243409-slack-CBG1CP4EN

### Steps to reproduce

1. Navigating to Settings > Performance for a Jetpack-connected site (`https://wordpress.com/settings/performance/jetpackexamplesite.com`)
2. The only item on that page is likely to be Jetpack Search

### What you expected to happen

Navigating to Settings > Performance with a Jetpack connected site I'd expect to see all performance options as were showing earlier yesterday, including 'Performance & speed', 'Media', 'Accelerated Mobile Pages'.

### What actually happened

Only 'Jetpack Search' is visible on the Settings > Performance page for a Jetpack-connected site.

### Browser

Google Chrome/Chromium

### Other notes

What was showing before the issue appeared:
<img width="825" alt="Screenshot 2022-06-29 at 08 48 26" src="https://user-images.githubusercontent.com/16754605/176382668-895871bb-e4e2-40a8-91de-3b66a8a7cf44.png">

How it looks now:
<img width="845" alt="Screenshot 2022-06-29 at 08 48 17" src="https://user-images.githubusercontent.com/16754605/176382607-7b691131-3cb6-48eb-85fc-72001eaf5d9c.png">

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by lakellie** [comment]
Flagged this with the team who's working on the project on Slack so they can have a look: p1656520653292369-slack-C02V49GM0PN
