### ISSUE TITLE
Task: Test marketplace plugin cancellation

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#65070]
### Details

When a marketplace plugin subscription gets cancelled it should delete the associated plugin.
If the site is on a Starter plan, it should also be reverted (unless it has other marketplace plugins).

**Comment by mmtr** [comment]
> If the site is on a Starter plan, it should also be reverted (unless it has other marketplace plugins).

This may need to adapt our is proxied check that dynamically adds the Atomic / Marketplace plugins features to the Starter plan, since that doesn't work in the async job context where all these cancellations are handled.

**Comment by mmtr** [comment]
> When a marketplace plugin subscription gets cancelled it should delete the associated plugin.

D83380-code should handle this.

**Comment by mmtr** [comment]
> If the site is on a Starter plan, it should also be reverted (unless it has other marketplace plugins).

Changes from D83396-code solves this.
