### ISSUE TITLE
All suggested verticals should lead to v13n DP

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#65075]
# Description

In the Verticals Screen we prompt with a list of 10 verticals when user first clicks in the search field. All of these should be  whitelisted (see whitelist in wpcom/wp-content/lib/verticals/image-verticalizer.php), so that the user sees the v13n DP if they select one of these options.

Specifically, the following verticals don't land in the v13n DP and need to be added to the whitelist:
* Marketing --> change to Advertising & Marketing since we have images there  /verticals/#/images?vertical_id=25
* Web Design & Development 
* Restaurants 

![Image](https://user-images.githubusercontent.com/5665959/176379460-93c4b835-b800-4520-8408-63c57a824b17.png)

# Acceptance Criteria
- [x] All 10 verticals that show in the suggested verticals list  should have images (Autumn will do image sourcing)
- [x] In the drop down list, change "Marketing" to "Advertising & Marketing" since we have images for Advertising & Marketing 
- [x] Make sure selecting Web Design & Development  leads user to see v13n DP
- [x] Make sure selecting Restaurants  leads user to see v13n DP
- [x] All 10 verticals that show in the suggested verticals list should be whitelisted

# Testing
- [ ] Go through v13n flow and ensure each of the suggested/popular verticals lead to the v13n DP (Autumn can help)

cc: @that-mike-bal

**Comment by autumnfjeld** [comment]
I've finished the image sourcing for:
* Web Design & Development
* Restaurants

These verticals can now be whitelisted.

**Comment by autumnfjeld** [comment]
@miksansegundo I've just updated the Acceptance Criteria to make this work clearer.  I have already done the image sourcing necessary for this work.  Essentially the dev work is just making changes to the white list as Griffith said [here](p1658126401233769/1658118879.005949-slack-CRWCHQGUB)
>  Include their vertical ID in this list /wpcom/wp-content/lib/verticals/image-verticalizer.php?r=7cffd98c#18

**Comment by miksansegundo** [comment]
Done ✅

I have made the changes on the API side following the checkboxes for the acceptance criteria and tested that Web Design & Development, and Restaurants leads users to see v13n DP.

The list of suggestions with `Marketing` has been updated:

<img width="549" alt="Screen Shot 2565-07-19 at 18 10 33" src="https://user-images.githubusercontent.com/1881481/179736788-6c57ef86-6451-48d8-b59a-937531b84ac4.png">

The v13n Design Picker is shown for `Web Design & Development`:

<img width="1354" alt="Screen Shot 2565-07-19 at 18 02 13" src="https://user-images.githubusercontent.com/1881481/179735982-227f621d-3cec-48e9-932c-ccc6b0806af4.png">

The v13n Design Picker is shown for `Restaurants`:

<img width="1360" alt="Screen Shot 2565-07-19 at 18 01 32" src="https://user-images.githubusercontent.com/1881481/179736001-59a8dffb-c648-4d28-bc4c-5061eefefc30.png">

**Comment by miksansegundo** [comment]
D84444-code
