### ISSUE TITLE
Marketplace: Yoast not correctly licensed when transferring to Atomic

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#65080]
### Quick summary

When purchasing `Yoast SEO Premium` in a Simple site with a free `*.wordpress.com` domain, it is not correctly licensed.

### Steps to reproduce

1. Go to `/plugins` in simple site with a `*.wordpress.com` domain. For example https://wordpress.com/plugins/your-site.wordpress.com
2. Search `Yoast SEO Premium`, open details page and click on `Purchase
 and activate`
3. In the next dialog window, click on `Install Yoast SEO Premium`
4. Another dialog window will be displayed indicating that your domain will be changed from `your-site.wordpress.com` to `your-site.wpcomstaging.com`. Click on `Continue`. 
5. In the next window, click on `Pay` to purchase the plugin

### Expected result

- The list of installed plugins https://your-site.wpcomstaging.com/wp-admin/plugins.php should list `Yoast SEO Premium` as active 
<img width="392" alt="CleanShot 2022-06-29 at 11 54 45@2x" src="https://user-images.githubusercontent.com/3519124/176408444-037e7ede-3a62-4c59-baff-621a03d8179a.png">

- The Blog RC should contain a section in the `WPCOM Marketplace` area with the `Yoast Premium` information and status as _active_

### Actual result

- The list of installed plugins shows `Yoast SEO Premium` as active but indicating to `Activate your subscription` 
<img width="326" alt="CleanShot 2022-06-29 at 11 58 24@2x" src="https://user-images.githubusercontent.com/3519124/176409238-a819285f-a99a-4e9f-8c58-10e9865bb920.png">

- The Blog RC does not contain a section of the Yoast license 
<img width="599" alt="CleanShot 2022-06-29 at 11 58 59@2x" src="https://user-images.githubusercontent.com/3519124/176409399-4b1eef33-613a-45d6-b908-bef4d73fc9af.png">

### Simple/Atomic

This has been observed when purchasing the plugin and in that transaction, the site is transferred from Simple to Atomic. When the site is already in the Atomic infrastructure, the licensing works as expected.

**Comment by gavande1** [comment]
Diff created at: D83452-code

**Comment by gavande1** [comment]
Deployed r248248-wpcom
