### ISSUE TITLE
Upsell nudges in Jetpack Dashboard link to wrong plan for Atomic sites w/ Starter plan

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65085]
### Quick summary

When visiting the Jetpack Dashboard (`wp-admin/admin.php?page=jetpack#/dashboard`) of an Atomic site with the Starter plan, all the upsell nudges of features requiring an upgrade (Backups, VideoPress, Ads, etc) try to upsell a Jetpack plan which is not compatible with the Atomic site.

### Steps to reproduce

- Visit the Jetpack Dashboard (`wp-admin/admin.php?page=jetpack#/dashboard`) of an Atomic site with the Starter plan.
- Click on any upsell nudge.

### What you expected to happen

It should upsell a WP.com plan.

### What actually happened

It upsells a Jetpack plan.

**Comment by obenland** [comment]
From #65097:


![Screenshot of erroneous VideoPress upgrade option on a limited Atomic site](https://user-images.githubusercontent.com/4887830/176513551-266f0a88-2b4d-4023-b19d-73e37ed5e9e1.png)

![Screenshot of a Jetpack VideoPress upgrade description on a Limited Atomic site.](https://user-images.githubusercontent.com/4887830/176513692-aa4289e6-30ab-48ef-a9c8-c3d84446800b.png)

![Screenshot of empty WPCOM cart and Sorry, that product is not compatible with sites hosted on WordPress.com](https://user-images.githubusercontent.com/4887830/176513721-ba13d1da-51f2-4d82-835d-492b3337ca1f.png)



### Steps to reproduce

Start with a limited Atomic site

1. Navigate to My Sites > Jetpack > Dashboard > Performance (**_Not_** My Site > Settings > Performance) - wp-admin/admin.php?page=jetpack#/performance
2. Observe Media section and VideoPress Upgrade option.
3. Click Upgrade, be directed to `wp-admin/admin.php?page=jetpack#/product/videopress`
4. click `Add Jetpack VideoPress`
5. See empty cart message and/or  `Sorry, that product is not compatible with sites hosted on WordPress.com.`

### What you expected to happen

Not to be offered the standalone VideoPress upgrade, to be offered a Pro or another upgrade instead.

### What actually happened

Was offered an incompatible Jetpack VideoPress upgrade.

**Comment by mmtr** [comment]
Since we may need to add WP.com exceptions to the Jetpack codebase to handle this, which is something that the Jetpack team encourages to avoid, I published a P2 post (pdG1ka-aS-p2) to coordinate with them.

**Comment by obenland** [comment]
Would it be an option to not show the Jetpack Dashboard on Starter plan sites, and instead have the Jetpack menu item (and submenu items) work in the same way as they do on Simple?

**Comment by mmtr** [comment]
That's one of the options I suggested in pdG1ka-aS-p2 🙂

**Comment by obenland** [comment]
Let's go with that then! :)
