### ISSUE TITLE
[Bug]: Jetpack Ads setting offers Jetpack Security Daily upgrade to Limited Atomic WPCOM sites

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#65096]
### Quick summary

Limited Atomic sites currently have an offer to `Generate income with high-quality ads.` via an Upgrade within Jetpack's settings.

![Screen Shot of Jetpack Ads settings page on a Limited Atomic Site](https://user-images.githubusercontent.com/4887830/176512095-35eca282-9cf3-4d34-9bb3-965466417e0b.png)

![Screen Shot of WPCOM error message stating Sorry, that product is not compatible with sites hosted on WordPress.com](https://user-images.githubusercontent.com/4887830/176512266-e8416bd1-7ed1-48eb-8c7f-2d58f68067f8.png)

### Steps to reproduce

Start with a limited Atomic site...

1. Access Jetpack > Dashboard > Settings > Traffic: `/wp-admin/admin.php?page=jetpack#/traffic`
2. Click Upgrade button next to `Generate income with high-quality ads.`
3. This attempts to add a Jetpack Security Daily upgrade.
4. See empty cart message and `Sorry, that product is not compatible with sites hosted on WordPress.com.` error.

### What you expected to happen

Not to be offered an incompatible upgrade, offer a Pro or other type of upgrade instead.

### What actually happened

Was offered a Jetpack Security Daily upgrade

### Context

Testing

### Reproducibility

Consistent

**Comment by obenland** [comment]
Thank you! Closing in favor of #65085.
