### ISSUE TITLE
[Bug]: Jetpack Performance Settings offer standalone VideoPress upgrade to Limited Atomic WPCOM sites

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#65097]
### Quick summary

Essentially https://github.com/Automattic/wp-calypso/issues/64950 but within Jetpack's Performance settings at `wp-admin/admin.php?page=jetpack#/performance` rather than Calypso's at `/settings/performance/`

![Screenshot of erroneous VideoPress upgrade option on a limited Atomic site](https://user-images.githubusercontent.com/4887830/176513551-266f0a88-2b4d-4023-b19d-73e37ed5e9e1.png)

![Screenshot of a Jetpack VideoPress upgrade description on a Limited Atomic site.](https://user-images.githubusercontent.com/4887830/176513692-aa4289e6-30ab-48ef-a9c8-c3d84446800b.png)

![Screenshot of empty WPCOM cart and Sorry, that product is not compatible with sites hosted on WordPress.com](https://user-images.githubusercontent.com/4887830/176513721-ba13d1da-51f2-4d82-835d-492b3337ca1f.png)

### Steps to reproduce

Start with a limited Atomic site

1. Navigate to My Sites > Jetpack > Dashboard > Performance (**_Not_** My Site > Settings > Performance) - wp-admin/admin.php?page=jetpack#/performance
2. Observe Media section and VideoPress Upgrade option.
3. Click Upgrade, be directed to `wp-admin/admin.php?page=jetpack#/product/videopress`
4. click `Add Jetpack VideoPress`
5. See empty cart message and/or  `Sorry, that product is not compatible with sites hosted on WordPress.com.`

### What you expected to happen

Not to be offered the standalone VideoPress upgrade, to be offered a Pro or another upgrade instead.

### What actually happened

Was offered an incompatible Jetpack VideoPress upgrade.

**Comment by obenland** [comment]
Thank you for the detailed steps! Closing in favor of #65085.
