### ISSUE TITLE
[Bug]: Plugin list links and icons for WooCommerce paid plugins on "Installed Plugins" page are broken

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#65102]
### Quick summary

The plugins list on the "Installed Plugins" /plugins/manage/{site_slug} page contain broken links and icons for WooCommerce paid plugins.

![plugins-link-wrong](https://user-images.githubusercontent.com/140841/176542754-7d7dd5a0-0aad-45df-9bf8-07d18c051494.png)

### Steps to reproduce

Go to /plugins/manage/{site_slug} on a site with the WooCommerce Subscription plugin installed. Observer the icon is a placeholder icon. Click on the plugin's name and see the link goes to the wrong URL. 

### What you expected to happen

The plugin icon should match the icon on the Browser Plugins page and the link should take you to the plugin details page.

### What actually happened

Broken icon, broken links.

### Reproducibility

Consistent

**Comment by obenland** [comment]
I'm not sure this is a Limited Atomic regression. The plugin information is pulled from the plugin directory directly. Since these paid plugins are not in the directory, it returns a "Plugin not found" error.

**Comment by mmtr** [comment]
I cannot reproduce this one 🤔 Has been fixed in the meantime?

<img width="1031" alt="Screen Shot 2022-06-30 at 16 00 30" src="https://user-images.githubusercontent.com/1233880/176697048-74f5a621-88c4-437d-b3c5-164a74e2e610.png">

**Comment by obenland** [comment]
Yes, links work for me as well

**Comment by mmtr** [comment]
Let's close it for now then.
