### ISSUE TITLE
Empty "Installed Plugins" page on Atomic needs a call-to-action

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#65101]
### What

Going to /plugins/manage/{site_slug} on an Atomic site with the INSTALL_PURCHASED_PLUGINS and no installed plugins show a mostly empty page. There should be call-to-action or upsell here.

![plugins-upsell](https://user-images.githubusercontent.com/140841/176541736-acc322cb-dbd7-44d1-90a3-2a25a0f2431b.png)

### Why

Landing on this empty page is confusing. We should direct the user on what they should do next. Something like "You have no plugins installed. Purchase a plugin from the Plugins page to enhance your site."

**Comment by mmtr** [comment]
There shouldn't be anything in the UI that points to `/plugins/manage` if no plugins are installed, so I guess this is rather low priority.
