### ISSUE TITLE
[Bug]: Gutenberg Version 13.5.2 conflicts with Elementor elements causing Preview & Live Site to not match

### ISSUE THREAD

**Issue by essleeung** [Automattic/wp-calypso#65109]
### Quick summary

Pages in Elementor preview do not match the live site when Gutenberg plugin is turned on (when unproxied). 

A user reported that their site is intermittently losing color, text, font selections and menu bar. Clearing the browser and site cache and reinstalling Elementor did not resolve the issue. The pages in the Elementor editor do not match the live site. When viewing the site proxied, it looks okay and will match the preview. 

### Steps to reproduce

This is difficult to reproduce as you need to set up other plugins. 

In this case, the user is using Elementor Pro and HT Mega – Absolute Addons for Elementor Page Builder to build their pages. 

- The menu is missing on the live site. 

![missingmenu](https://user-images.githubusercontent.com/39225086/176601345-d615a416-7696-4b24-8430-20f24e577b25.jpeg)

- The footer text is a different color and the social icons are missing the blue circle background. 

![footerwrongcolors](https://user-images.githubusercontent.com/39225086/176601358-71e412a8-a93e-43f2-a8dd-0dbdebd5d42d.jpeg)

### What you expected to happen

The preview to match the live site. 

- Menu shown on home page: 

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/39225086/176601646-25e153f5-84ab-4e1f-be70-1a82718c198e.png">

- Footer has yellow text and social icons have blue circle backgrounds.

![image](https://user-images.githubusercontent.com/39225086/176601833-25450147-8362-477d-903b-e08a0ae39ad9.png)

### What actually happened

The preview will match the live site when proxied, but not unproxied. 

### Context

Customer report here: 35941050-hc / followup ticket here: 5337159-zd-woothemes

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge

### Simple/Atomic

Atomic

### Reproducibility

Once

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Disable the Gutenburg plugin and the live site will match the preview.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on AT: **Could not replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- When testing on an AT test site, leaving Gutenberg activated had no impact on content built through Elementor, whether I was proxied or unproxied.
- Gutenberg is now up to v 14.0.2, and Elementor is on v 3.7.4, so it's quite likely this issue is no longer applicable.

📌 ACTIONS
- Closed as could not replicate / no longer relevant (please reopen with steps to replicate if the issue reoccurs)
