### ISSUE TITLE
[Bug]: theme picker during onboarding has weird looking tooltips for premium badge

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#65114]
### Quick summary

Hovering premium badges during onboarding when picking a theme, they look off:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/87168/176618948-4692a0bf-0cca-4425-b5f4-570e75b9fabe.png">

### Steps to reproduce

1. Go to /start
2. Pick other goal
3. Pick e.g. food vertical
4. Click "view more options"
    <img width="360" alt="image" src="https://user-images.githubusercontent.com/87168/176619185-e12228dc-ddbd-4012-a2de-ca34ed836698.png">
5. Find premium badge and hover it

### What you expected to happen

Wider tooltip

### What actually happened

Narrow tooltip

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Looks like this has been addressed in more recent updates:

![Markup on 2023-05-03 at 13:41:01](https://user-images.githubusercontent.com/27249804/236044823-398dac20-5b19-4e9d-b504-57b2f935ba39.png)

📌 ACTIONS
- Closed as no longer relevant
