### ISSUE TITLE
Generated design picker: Large previews fail to show after user refreshes the page while previewing a design in the static design picker

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#65118]
## Description
In the current implementation, both static and generated design picker share the same state for selected designs for previewing. An issue occurs when users switch to the static design picker, previews one of the designs, and refreshes the page.

When that happens, users will land back to the generated design picker, but this time the large preview is hidden since the selected design from the static design picker doesn't match with any of the thumbnails from the generated design picker.

## Acceptance Criteria 
- [ ] Whenever a pre-selected design doesn't match with a generated design thumbnail, default to the topmost thumbnail.

**Comment by autumnfjeld** [comment]
@taipeicoder I added label [Pri] High, but if you don't feel that is the case, go ahead and change it.

**Comment by taipeicoder** [comment]
Shipped, closing.
