### ISSUE TITLE
Purchases: Refund Survey: Unable to view text entered into second text box on Nexus 6

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#6511]
While testing #4838 on my Nexus 6: I attempted to enter an answer for the second question in the refund survey - **Where is your next adventure taking you?** - but the keyboard covered the text box and it was impossible to scroll down to view what I was entering.

#### Steps to reproduce
1. Add any upgrade of your choosing to a WordPress.com site.
2. Navigate to **/purchases** and select your newly added upgrade.
3. Select the option to remove the upgrade.
4. The refund survey will appear in a new window with two questions: **Please tell us why you are canceling** and **Where is your next adventure taking you?**
5. Under the first question in the survey, check a box and enter an answer into the text field.
6. Replicate the above for the second question in the survey: Check a box and attempt to enter an answer into the text field.
#### What I expected

After selecting the text box, I expected to be able to be able to view my answer as I entered it.
#### What happened instead

The phone's keyboard covered the text box and it was impossible to scroll down to view what I was entering. 
#### Browser / OS version

Chrome on Android 6.0.1.
#### Screenshot / Video

This is the view I was stuck on after selecting a text box under the second question:

![screenshot_20160703-154436](https://cloud.githubusercontent.com/assets/2998162/16546213/00c07164-413b-11e6-8700-88c3ee5a294d.png)
#### Context / Source
# reallife #manual-testing

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue as described above.  Tested using Chrome on a Nexus 6P, Android 7.1.1
