### ISSUE TITLE
Theme Deploy Support: Create new private repo for Premium themes

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#65110]
As part of Serenity's work in supporting the themes team with new theme development, we need a new GitHub repo (private, under the A8C organization and accessible by all members of the org) which will be used to store premium themes and accept contributions from contracted theme developers.

This repo should also include a version of the script found at https://github.com/Automattic/themes/blob/trunk/theme-utils.mjs, which is used to deploy themes to a sandbox to get them into the wpcom git/svn repo. (If possible, it would be nice to get this script into a centralized form where the same code can be used for both free and premium themes.)

**Comment by andres-blanco** [comment]
We should figure out how syncing between wpcom <-> github is done currently for public themes.

**Comment by valterlorran** [comment]
> If possible, it would be nice to get this script into a centralized form where the same code can be used for both free and premium themes.

I thought that we maybe could create a private repo to act as an npm package. What do you think?

**Comment by andres-blanco** [comment]
Progress was made here: p1657305456885959/1657289218.505249-slack-C0Q664T29. Once a P2 is created detailing the flow it will be linked from here.

**Comment by valterlorran** [comment]
Closing this issue: https://github.com/Automattic/themes/pull/6205#issuecomment-1201491414
