### ISSUE TITLE
Parent theme does not install when child theme is installed on WoA

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#65128]
### Quick summary

In certain circumstances, installing a child theme on a WoA site will not install the parent theme, which causes a critical error. It seems that this can happen for various reasons. One cause that has been identified so far is a situation where the parent theme has already been installed once and then later deleted. There may also be other causes that haven't been documented yet.

p9F6qB-9J5-p2

Per @JoshuaGoode:

> It seems that `aa2dc102c7751c3c3ecda4e76b8349f87ad8094c/wpcomsh.php#L906-gh-Automattic/blob` and `aa2dc102c7751c3c3ecda4e76b8349f87ad8094c/functions.php#L250-gh-Automattic/blob` aren't properly checking if the children exist. They will prevent deletion (of the parent theme) if a child is active but not if another unrelated theme is active.

This leads to a situation where a child theme can be activated without the parent theme installed.

### Steps to reproduce

1. Activate Stratford (or another type of child theme)
2. Activate Twentytwenty (or another theme that doesn't rely on the same parent)
3. Delete Varia (or the parent)
4. Activate Stratford (or the child)

### What you expected to happen

When activating the child theme, the parent theme should be installed.

### What actually happened

The parent theme was not installed, leading to a situation with no active theme and a critical error on the site.

### Context

Customer reports:
14627617-hc
35894682-hc
35917072-hc

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

This will only affect child themes. Some examples from recent customer reports include Stratford, Cubic, or Meraki.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The parent theme must be installed or symlinked in CLI.

**Comment by masperber** [comment]
- [ ] 5329760-zen needs customer followup when resolved

**Comment by JoshuaGoode** [comment]
See the Atomic Request for more internal details & discussion:  p9F6qB-9J5-p2

**Comment by brandonpayton** [comment]
This has been fixed via 1017-gh-Automattic/wpcomsh.
