### ISSUE TITLE
Seller Experience SPIKE: Investigation/knowledge transfer for moving to subscription-based theme purchases

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#65133]
One of Serenity's next main objectives is to implement the transition to allowing subscription-based purchases of individual themes during signup (and after). Since we haven't done much direct work with purchasing/products thus far, this issue is focused on the research and knowledge transfer necessary to effect this implementation completely and safely.

Questions that should be investigated:

* Backend Research
        - How to create new subscription products
        - How to enable/disable products in testing vs development
        - How to disable existing one-time purchase themes while grandfathering in users that have already purchased them
* Frontend Research
        - How to fetch available subscription theme products from the API
        - Do we have to change the information we are sending to the checkout page in any way?

(Feel free to update this list with other questions if they arise in the course of research)

Deliverables:
* P2 post summarizing the work that will need to be done to effect this change
* New issues created in GitHub for initial work items

@michaeldcain , Shilling's knowledge and input here would be invaluable! Other teams present in the #dotcom-marketplace channel on Slack will also probably be able to provide insight.

**Comment by andres-blanco** [comment]
Context: paYKcK-1yx-p2

**Comment by andres-blanco** [comment]
do not assume that the purchasable themes lives exclusively on Simple. They might be managed products in the same way as marketplace products are.

**Comment by nelsonec87** [comment]
Findings here: paYKcK-1Qr-p2
