### ISSUE TITLE
Editor: Double-clicking image captions selects the entire caption, not just the word

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#6513]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Create a new post and add an image.
3. Give the image a caption containing several words
4. Double-click a word in the caption.
#### What I expected

Normal behaviour for double-click is that the word is selected. Triple-click should select the entire paragraph.
#### What happened instead

Double-click selects the entire caption/paragraph.
#### Browser / OS version

Tested in Firefox on Mac, and user who reported it has Chrome on Windows.
#### Screenshot / Video

![caption](https://cloud.githubusercontent.com/assets/11873759/16558827/c0043e68-41e8-11e6-808f-811d90478970.gif)
#### Context / Source

Reported by a user in 751267-f

**Comment by lancewillett** [comment]
I can confirm this is broken, testing with Mac-n-Chrome.

**Comment by rachelmcr** [comment]
This will be resolved with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
