### ISSUE TITLE
Empty Atomic transfer warning modal

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65153]
### Quick summary

Looks like we still display the Atomic transfer warning modal even for sites totally eligibles:

<img width="1285" alt="Screen Shot 2022-07-01 at 11 47 37" src="https://user-images.githubusercontent.com/1233880/176871475-2694a5b7-fe7b-42ec-bba7-dd6dacb0e467.png">
 

### Steps to reproduce

- Go to https://wpcalypso.wordpress.com
- Switch to a Simple site
- Purchase a Starter plan and set up a custom domain as the primary address
- Go to Plugins
- Select a paid plugin
- Click on the "Purchase and activate" button

### What you expected to happen

I should land on the checkout page to proceed with my purchase

### What actually happened

We display an empty modal

**Comment by obenland** [comment]
It looks like this is another symptom of Starter plans not being eligible for Atomic. #65092 added an exception for it, but that exception gets checked inside that modal, not before it's loaded.
