### ISSUE TITLE
Provide one-off backups of Atomic sites on lower-tier plans

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65151]
Backups are not available on Atomic sites with a lower-tier plan (e.g. Starter) since they require Pro/Business/eCommerce plan.

However, under some circumstances (e.g. after suspending a site for a TOS violation) we need to provide a backup to site owners.

One possible way of doing this is by offering a one-off backup in the Rewind Debugger.

More context: p7DVsv-eMq-p2#comment-41208.

**Comment by mmtr** [comment]
Created D83634-code to solve this.

**Comment by obenland** [comment]
> Backups are not available on Atomic sites with a lower-tier plan

Is that the case? Looking at the rewind debugger for a Starter plan site that was transferred on June 28, it looks like it does get a daily backup done. 2cd1a-pb/#plain

**Comment by mmtr** [comment]
Yeah, I noticed that too. Looks like there is a cron job making backups on those sites, and the only restriction was the inability to trigger a one-off backup which is what D83634-code covers.
