### ISSUE TITLE
Help: Improve language detection of help language notification

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#6516]
1. Change locale to en-gb.
2. Go to https://wordpress.com/help/contact/

Results: You'll see this notice about the language:

![contact](https://cloud.githubusercontent.com/assets/2738252/16561749/de43445c-41c8-11e6-9a35-f95334f05deb.png)

Expected: This should display only for non-en languages, as people who speak UK (and other variants) of English in general should be able to communicate pretty well with our English-speaking Happiness Engineers. :)
#### Browser / OS version

Any

Cc @SiobhyB, who reported this initially.

**Comment by southp** [comment]
We did have considered the approach to query for support language availability via language code despite the location code back then. Our concerns were that dropping location codes might be an overlook of the potential language differences in different locations. e.g. zh-TW, zh-CN and zh-HK are quite different, and pt vs pt-br.

I have two proposals to approach this:

1. Dropping location codes of `en` variations looks safe. We can make a special case for `en` variations.
1. Querying support languages in a hierarchical way:
    1. Query if there is a match for the whole locale code. Return if yes.
    1. If not, drop the location code and query if there is a match for the language code.

I personally prefer the 2nd. However, I am not sure if I have overlooked something. Would it be possible if anyone from the i18n team to verify it?

**Comment by yoavf** [comment]
There's no locale fallback system at this time, though we wish we had ([core does too](https://core.trac.wordpress.org/ticket/28197)). 

Doing this hierarchically is possible, but you'd need to make sure you get the wording right. I.e, assuming we offer support in pt-br, users with locale 'pt' would need to see something like:

"Support is available in Português do Brasil and English"

If we offer support in Spanish (es), we'd show this to users with other Spanish variants:
"Support is available in Español and English"

^ in both cases I'd remove the word "only"

For a user with an unsupported locale, I'd keep the current wording.

**Comment by southp** [comment]
@yoavf That sounds great. I like the idea of informing users when we are doing a locale fallback.

It looks like we already have the wording for each locale code:
![image](https://cloud.githubusercontent.com/assets/1842898/16610801/315f52de-4390-11e6-828a-0fe8e5119ec6.png)

So I think it will be doable.

**Comment by SiobhyB** [comment]
It looks like this was fixed somewhere along the line. :) I no longer see that note when visiting **/help/contact** with my interface language set to **English (UK)**.
