### ISSUE TITLE
Sites Management Dashboard: create a list view for sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65166]
Depends on: https://github.com/Automattic/wp-calypso/issues/65163.

Once the https://github.com/Automattic/wp-calypso/issues/65163 is done we can use the Main Section to implement the List View of sites with the dummy data.

<img width="833" alt="Screenshot 2022-07-01 at 22 39 43" src="https://user-images.githubusercontent.com/1182160/176965332-928156cc-3055-4b0d-8558-957125ddf692.png">

Done is:
- [ ] The UI matches the designs.
- [ ] All four columns should be included. 
- [ ] It works as designed for smaller screen sizes.
- [ ] The implementation relies on core components where possible, or introduces the new ones in Calypso `/packages/components`.
- [x] Clicking the url under site name should open a new tab with the url as the address
- [x] Clicking the site name should take you to single site's My Home page.
- [x] The icon represents the site status. @SaxonF to provide icons for launched, coming soon and private
- [x] The site thumbnail shows something like the site icon

Not required:
- Can be populated from dummy data
- Ellipses menu can be empty for now
- The list has no handling for empty states.
- The thumbnail doesn't need to be a real thumbnail

**Comment by SaxonF** [comment]
Some other criteria

- [x] Clicking the url under site name should open a new tab with the url as the address
- [x] Clicking the site name should take you to the single site view of that site. 
- [x] The icon represents the site status. @SaxonF to provide icons for launched, coming soon and private
- [x] The site thumbnail can use the existing icon but can replaced once https://github.com/Automattic/wp-calypso/issues/65172 is completed

**Comment by danielbachhuber** [comment]
@SaxonF @vindl @p-jackson Couple of implementation questions:
1. Is it fine to use `site.plan.product_name_short`, or do we need to generate our own Plan labels?
2. Should the site thumbnail link to anything?

Also, I'm uncertain how well `<table>` will serve us on desktop and mobile, but I suppose we'll see...

**Comment by SaxonF** [comment]
> site.plan.product_name_short

Do you hav an example of what this looks like?

> Should the site thumbnail link to anything?

Same as title, let's link it off to the single site admin

**Comment by danielbachhuber** [comment]
> > Should the site thumbnail link to anything?
> 
> Same as title, let's link it off to the single site admin

Sounds good 👍 

> > site.plan.product_name_short
> 
> Do you hav an example of what this looks like?

Here's what I see on my dashboard:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/36432/177425029-f62e31a0-0ef8-4923-8661-08c5d3839b59.png">

I'm not sure what all of the potential values are. Someone might have easy access to that, or we could do a research spike to figure it out.

**Comment by SaxonF** [comment]
We should use whatever logic is currently being used on My Plan page, which maybe is the same?

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/1072756/177471029-d345e9e2-e019-4dc8-93da-5a9b5a36ae5a.png">

**Comment by danielbachhuber** [comment]
> We should use whatever logic is currently being used on My Plan page, which maybe is the same?

It looks like the 'My Plan' page displays the `<MyPlanCard>` with a `currentPlan`:

https://github.com/Automattic/wp-calypso/blob/40156979bf8342920559ce02e5acd2802c118013/client/my-sites/plans/current-plan/purchases-listing.jsx#L336-L361

The `currentPlan` can be pulled from the `site` object:

https://github.com/Automattic/wp-calypso/blob/7655b6d1f326371990851da10ebb97f133fbdc17/client/state/sites/plans/selectors/get-current-plan.js#L19-L22

We're using `site.plan.product_name_short`, so it seems like this is the _roughly_ same data.

However, there's a little bit of logic we need to apply:

https://github.com/Automattic/wp-calypso/blob/40156979bf8342920559ce02e5acd2802c118013/client/my-sites/plans/current-plan/purchases-listing.jsx#L114-L124

I'll do so in the next PR.

**Comment by danielbachhuber** [comment]
> I'll do so in the next PR.

I tried with the following:

```js
let planName = site.plan.product_name_short;
const currentPlan = useSelector( ( state ) => {
	return getCurrentPlan( state, site.ID );
} );
if ( currentPlan ) {
	const planObject = getPlan( currentPlan.productSlug );
	if ( planObject ) {
		planName = planObject.getTitle().toString();
		if ( planObject.term === TERM_MONTHLY ) {
			planName += ' ' + __( 'monthly' );
		}
	}
}
```

However, I discovered `getCurrentPlan()` returned `null` for all of my sites. This leads me to believe some additional data hydration needs to happen (aka more API requests).

Until we decide the additional API requests are necessary, I think we should stick with `site.plan.product_name_short` (which was probably created for this purpose).

**Comment by SaxonF** [comment]
@danielbachhuber I'm going to request an annoying change, especially after looking into the icons, and that is to bring back the old "P2" and site status labels instead of icons. My thought process is that this is a more familiar interface for people initially and doesn't detract from other important information right now. We may want to revisit when we look at monitoring tools.

What do you think?

![image](https://user-images.githubusercontent.com/1072756/177711124-74908ba8-cee2-448a-a0c6-696db9cc29d6.png)

**Comment by danielbachhuber** [comment]
> I'm going to request an annoying change, especially after looking into the icons, and that is to bring back the old "P2" and site status labels instead of icons. My thought process is that this is a more familiar interface for people initially and doesn't detract from other important information right now. We may want to revisit when we look at monitoring tools.

@SaxonF I'm open to it! I'll put together a pull request for it. The labels are certainly clearer than the icons.

**Comment by p-jackson** [comment]
> I think we should stick with `site.plan.product_name_short` (which was probably created for this purpose).

Yeah, the "short name" is human-readable, so I think it's the right one to use here.

**Comment by danielbachhuber** [comment]
@SaxonF @vindl I _think_ I have a reasonably solid pass on all elements of the Sites Table. You can see all of the latest on horizon.

A couple of questions:
1. Do we want to keep this issue open for polish work, or should we create separate follow-up issues?
2. Is there anything else you'd like to see for this issue?

**Comment by vindl** [comment]
@danielbachhuber 

1. Let's create follow-up issues.
2. We can consider this done and close it. It went above the initial requirements, so you should check whether we should close https://github.com/Automattic/wp-calypso/issues/65167 based on the work shipped here.
