### ISSUE TITLE
Sites Management Dashboard: technical exploration for generating site thumbnails

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65170]
In order to generate the thumbnail view for the sites, we need to have a performant mechanism for generating and storing the screenshots of the homepage.

![image](https://user-images.githubusercontent.com/1182160/176973174-bc44877c-9379-4ab9-af8e-5c156a3fa5b0.png)

We used mShots internally for similar tasks, but that might be too slow to handle the volume on WP.com. In case of mShots thumbnails, so far we relied on the fact that there is a limited number of demo thumbnails to be generated, and that they didn't change often allowing for easier caching. Another potential option that was discussed was using live block previews, but this is likely limited to FSE sites, and folks encountered performance problems in the past when trying to generate thumbnail previews for many pages with complex layouts in the same view.

There's some caching built into mShots, but we should consider how quickly we want that cache to be invalidated for our use case. For instance: if I change the theme used by my site, or do a major update of the homepage content, how quickly would I expect that change to be reflected in the dashboard thumbnail? Instantly? Within a few hours?

Let's conduct a technical exploration and try to find a path forward.

Done is:
- [x] Document the results of the technical exploration in a P2 post on buildp2.
- [x] Outline different approaches and their pros and cons.
- [x] Select your preferred approach based on the trade-offs presented above.

**Comment by danielbachhuber** [comment]
> Let's conduct a technical exploration and try to find a path forward.

@vindl Is there a point of reference you can share regarding what you'd expect out of a technical exploration?

**Comment by danielbachhuber** [comment]
Also, a couple more ideas to throw into the mix:
* Pull the `og:image` from the site's homepage.
* Overlay the site icon on the primary background color for the site.

To support the evaluation process, it might be helpful to:
1. Identify a few representative WordPress.com users.
2. For each user, prepare mockups of each thumbnail approach — to let us see what they would see.

**Comment by vindl** [comment]
> @vindl Is there a point of reference you can share regarding what you'd expect out of a technical exploration?

I'm not sure if I understand the question. Are you asking for similar posts to use as a reference point or something else?

**Comment by danielbachhuber** [comment]
> I'm not sure if I understand the question. Are you asking for similar posts to use as a reference point or something else?

@vindl Yes — essentially greater clarity on what you were looking for, regarding format, content, comprehensiveness, etc.

In the interest of keeping things moving along, I did my best guess: pdKhl6-su-p2

Happy to take any feedback you might have!

**Comment by vykes-mac** [comment]
@vindl does considering third party services out of the scope here?

**Comment by vindl** [comment]
> @vindl does considering third party services out of the scope here?

@vykes-mac any alternative idea that you have and that looks viable is very much in scope. The point is to gather as many as possible and to pick the best one, or give up on the implementation if nothing looks feasible or worth it.

**Comment by vindl** [comment]
> @vindl Yes — essentially greater clarity on what you were looking for, regarding format, content, comprehensiveness, etc. In the interest of keeping things moving along, I did my best guess: pdKhl6-su-p2

That P2 post is a good start! I think the high-level summary of what I was looking for is outlined in the `Done Is` criteria.

A more detailed version of the post format that I had in mind:
- Description of the problem that you are trying to solve.
- List of a potential solutions that you considered.
  - Outline which solutions are blocked or not viable, and provide rationale.
  - If they seem viable, provide a high-level implementation plan.
- For the remaining viable solutions (if any), summarize the pros and cons.
- Based on the pros and cons, recommend the approach that we should adopt.

@danielbachhuber let me know if this answers your question?

**Comment by danielbachhuber** [comment]
Closing — I think the P2 post and ensuing comments present a pretty thorough discovery pdKhl6-su-p2
