### ISSUE TITLE
Sites Management Dashboard: implement the designs and handling for empty states

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65173]
Depends on: https://github.com/Automattic/wp-calypso/issues/65167

Let's handle the empty states in the sites list properly.

![image](https://user-images.githubusercontent.com/1182160/176974466-1a5dba4e-6f5d-49b8-b5d4-5b089b5568f8.png)
<br>
![image](https://user-images.githubusercontent.com/1182160/176974509-d2fb24cd-75a9-45c0-83a8-746da34653f8.png)

Done is:

- [ ] The UI matches the designs.
- [ ] The implementation relies on core components where possible or introduces the new ones in Calypso `/packages/components`.

**Comment by danielbachhuber** [comment]
@SaxonF Could we also get a "No Search Results found" state?

**Comment by zaguiini** [comment]
Thanks, @danielbachhuber. This state is particularly useful for https://github.com/Automattic/wp-calypso/issues/65169.
