### ISSUE TITLE
Sites Management Dashboard: gathering feedback and promoting a new feature

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65175]
We discussed options for gathering feedback and introducing this feature when the user lands on the page for the first time.

We still need to come up with designs for this and the exact questions that we want to be answered.

cc @SaxonF

**Comment by SaxonF** [comment]
@vindl @danielbachhuber I'd love to get to a point where we have a globally persistent way of collecting feedback that is contextually aware e.g. we can map url to questions. 

In the meantime, I'm thinking we can keep feedback trigger within the site management page and highlight it as part of announcing. We can combine this with actively interviewing customers who are in the segment's we want to target.

https://user-images.githubusercontent.com/1072756/177078483-41e9cb71-544d-41c0-813e-e9cfe44f18a9.mp4

**Comment by vindl** [comment]
Thanks, @SaxonF! I'm moving this to the dev view.

**Comment by danielbachhuber** [comment]
I looked into some potential approaches we could take.

In #65191, I discovered a feedback form tied to the cancellation workflow:

![image](https://user-images.githubusercontent.com/36432/178370671-bbc5fb15-0932-4d96-bc9f-02d3ad82d01d.png)

It connects to a `submitSurvey` action:

https://github.com/Automattic/wp-calypso/blob/86c748a2a368a4f7b119debfff8ba234ed4a2af9/client/components/marketing-survey/cancel-purchase-form/index.jsx#L309-L334

https://github.com/Automattic/wp-calypso/blob/ea5e2ba59306c8bce4cd5fb4932903a5dfdc11d1/client/lib/purchases/actions.js#L28-L42

On the backend, the endpoint calls to `Marketing_Survey::submit_survey()`, which stores in the `marketing_survey_responses` table. The table is five years old pMz3w-5Cf-p2

There doesn't appear to be a reporting interface, so we'll need to figure out how to deliver responses.

I think `marketing_survey_responses` is the most appropriate approach, but here's some more recent exploration (including Crowdsignal, etc.) we may want to consider instead: paJDYF-1Vp-p2#comment-6633

**Comment by vindl** [comment]
@danielbachhuber here is another recent example from the Site Editor feedback form: https://github.com/Automattic/wp-calypso/pull/56667. The responses from it ended up in a separate Zendesk queue.

**Comment by danielbachhuber** [comment]
@SaxonF Another approach to consider: linking to a Calendly (or SavvyCal) link from the Sites Management Page. If we only display it to WordPress.com users fitting our ICP, it might be a useful way to get a constant drip of interviews.

While I'm on the thought, we could potentially wire up something similar with HappyChat: when a WordPress.com user matching our ICP shows up in chat, indicate as such to the Happiness Engineer.

**Comment by SaxonF** [comment]
Revisiting this issue. I think if we could re-use the cancellation form page for our purposes which we'd link to via the feedback button above, that would at least give us a channel to collect customer feedback and find people to chat further to. @vindl thoughts on prioritising this post launch?

![image](https://user-images.githubusercontent.com/1072756/184298380-cb28bb7a-f20e-4ffe-82f3-268dd429a80b.png)

**Comment by vindl** [comment]
> @vindl thoughts on prioritising this post launch?

We can include this in the i2 scope.

**Comment by p-jackson** [comment]
We might come back to it, but no immediate plans to implement this p1664836628656469-slack-C0347E545HR
