### ISSUE TITLE
Sites Management Dashboard: implement the solution for generating site thumbnails

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65172]
Depends on: https://github.com/Automattic/wp-calypso/issues/65170

Provided that the research in https://github.com/Automattic/wp-calypso/issues/65170 yields a viable solution, we can continue with the work for showing the thumbnail view. If there is no viable technical solution, this issue should be closed and the work punted until further notice.

More details will be added here once the technical exploration is complete.

Done is:
- TBD.

**Comment by vindl** [comment]
Reopening this since it's not fully resolved with #65868. We still need the backend pieces.

**Comment by danielbachhuber** [comment]
> We still need the backend pieces.

@vindl Which backend pieces are you referring to?

**Comment by vindl** [comment]
> @vindl Which backend pieces are you referring to?

@danielbachhuber, I thought we'll need some backend/code handling to determine when to refresh the generated thumbnail. After chatting with folks, we concluded that this issue can be closed in favor of the other open one, but I forgot to circle back and close it.
