### ISSUE TITLE
Add hotjar and fullstory scripts to all onboarding screens.

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#65185]
# Description
a8c has a hotjar account to see how users interact with UI screens, and I'd like to use this to look at the new onboarding screens.  As far as I understand ( p1656921618725409/1656401763.910439-slack-CRNF6A9DX) hotjar scripts need to be added to pages, to new stepper framework.

Here's an example of a working heatmap on wordpress.com landing page
<img width="904" alt="image" src="https://user-images.githubusercontent.com/5665959/177110981-bb165cdf-6cf5-4cee-8a15-d9969950fb60.png">

Here's an example of what happens when I look at wordpress.com/setup/vertical
<img width="916" alt="image" src="https://user-images.githubusercontent.com/5665959/177111533-5695162d-7755-45fa-865a-a99d2afc8d06.png">

See:
https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/analytics/with-tracking-tool/README.md
https://github.com/Automattic/wp-calypso/tree/trunk/client/state/analytics
https://help.hotjar.com/hc/en-us/articles/115009336727-How-to-Install-your-Hotjar-Tracking-Code

My hotjar login if anyone wants to test:
autumn.fjeld@automattic.com
pw: 2cd10-pb/ (link to onebin)
view for Goals screen heatmap: https://hotjar.com/l/pwMPWb

# AC / ToDo
- [x] Add hotjar scripts, such that all onboarding screens can be viewed in hotjar
- [x] verify scripts work by logging into hotjar and viewing Goals heatmap (https://hotjar.com/l/pwMPWb) -- or ask Autumn to verify this.
- [ ] I don't yet know how fulllstory scripts work, but if you see evidence in the code of fullstory scripts , please report in the comments below.  Background: p58i-aCK-p2#comment-54565

**Comment by taipeicoder** [comment]
HotJar and FullStory scripts are live in production. That being said, FullStory data capture is currently paused due to account limitations. Given that we can already see interaction sessions via HotJar, should we just use that and remove FullStory?

**Comment by taipeicoder** [comment]
Closing as FullStory doesn't meet our use needs for the moment due to restrictive data capturing protocol.
