### ISSUE TITLE
Sites Management Dashboard: allow user to return to dashboard after clicking "New site" button

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#65183]
The "New site" button added in https://github.com/Automattic/wp-calypso/pull/65182 takes the user from the dashboard to the site creation flow. But the button in the top left of the flow that's supposed to return the user to where they came from isn't taking the user back to the dashboard.

<img src="https://user-images.githubusercontent.com/1500769/177098841-55aa4b67-5611-4171-8f2c-cd2d97725563.png" width="50%">

The site creation flow may already support a query parameter that allows the back URL to be set, but I'm not sure.

Done is:
- When coming from the dashboard the back button label should say "Back to All My Sites" (which is what the link in the site switcher says)
- It should return the user to the sites dashboard.

**Comment by danielbachhuber** [comment]
@p-jackson In my testing, the user is taken back to `/sites`:

https://user-images.githubusercontent.com/36432/178018222-8cf4f20a-f3ae-4a6f-8386-0867a5a52ab2.mp4

Given `/sites-dashboard` will shortly become `/sites`, shouldn't we keep the current behavior?

Also, in my opinion, "Back to My Sites" makes more sense than "Back to All My Sites"...

**Comment by p-jackson** [comment]
Technically **My Sites** is the proper noun for the main Calypso area
<img src="https://user-images.githubusercontent.com/1500769/178184244-795b1886-0d02-4a37-be85-16378c589760.png" alt="CleanShot 2022-07-11 at 15 37 51@2x" width="50%">

But you make a good point, it does sort of work good enough at the moment. The confusion isn't helped by the fact the title of the dashboard is **My Sites** 😅
<img src="https://user-images.githubusercontent.com/1500769/178184877-9db56903-a18f-4b49-bcd4-e4ae1f9dae57.png" alt="CleanShot 2022-07-11 at 15 46 59@2x" width="50%">

I wonder how well it works in other languages. Like, maybe the label is rendered using `"Back to %s"` and whatever we use consistently for **My Sites** in other languages might not be as generic as it is in English?

Maybe we should leave this ticket on the back burner for a bit to see whether the inconsistencies in the title get worked out, maybe as part of #65162? @SaxonF

**Comment by wojtekn** [comment]
I see we didn't agree about the final wording for the back link yet, but I went ahead and opened PR that lets users go back to the Sites Dashboard from the New Sites flow as this part is clear. We can adjust the link label later.

I think that "My Sites" makes sense there. I would treat "All" and "Back to" as words that describe the CTA target and "My Sites" as the CTA target:

* All "My Sites"
* Back to "My Sites"
