### ISSUE TITLE
Sites Management Dashboard: navigate to dashboard from the "All My Sites" button in the Calypso sidebar

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#65181]
Users will eventually access the sites management dashboard via the "All My Sites" button in the site switcher that appears in the Calypso sidebar.

![Image](https://user-images.githubusercontent.com/1500769/177084207-15ce1626-9aee-44e2-92fe-f5b19a8b37fd.gif)

We will be launching the dashboard to customers as a separate task, so initially this will be behind a feature flag.

Depends on https://github.com/Automattic/wp-calypso/issues/65166 and #65169, otherwise it'll be a worse experience for users where the feature flag is enabled (i.e. a12s)

Done is:
- [ ] The `/sites` URL points at the sites management dashboard
- [x] The "All My Sites" button in the Calypso sidebar links to `/sites`
- [x] This change is enabled for environments where the `build/sites-dashboard` feature flag is enabled i.e. so all developers will see the change

Not required:
- This task doesn't include any design changes to the sidebar itself (e.g. any reordering of elements we decide to do. See https://github.com/Automattic/wp-calypso/issues/65162
- The existing site picker UI that currently appears at `/sites` is used as a fallback of sorts when a site can't be found. We don't need the dashboard to be that fallback UI.

**Comment by wojtekn** [comment]
@p-jackson I started reviewing this one and found that the Switch Site selector has more responsibilities. It's not only used to switch sites in the default context, but it supports other contexts too: switching sites from `/media/`, `comments/all`, and more. Thus I tried to hook our dashboard into the current selector logic:

https://github.com/Automattic/wp-calypso/pull/65462

It works, but we will still need to add a few missing points to fully replace the features fulfilled by the current selector (filling site base path, changing page title). 

> The /sites URL points at the sites management dashboard

It looks internally `/home` is used, and `/sites` redirects there. Do we want to serve the new Sites Dashboard using the `/home` URL instead of `/sites`?

> The existing site picker UI that currently appears at /sites is used as a fallback of sorts when a site can't be found. We don't need the dashboard to be that fallback UI.

With the selected approach, it works OOTB.

**Comment by p-jackson** [comment]
I had a conversation about this somewhere with @SaxonF and @vindl but frustratingly I can't find the link now 😩

Personally, I'm _not_ in favour of just replacing the fallback site switcher with our multi-site dashboard. At least not in a way that drops the entire dashboard in where the fallback site switcher used to be

When you navigate to `/sites-dashboard` (later, `/sites`) you aren't in the middle of trying to achieve another task. So we show you some helpful dashboard type UI: like quick actions in the meatball menu, like the new site button, maybe in the future some timely alerts about your sites.

When you accidentally navigate to `/comments/all` without a site slug it means you're in the middle of trying to moderate your comments. We don't want to distract you with alerts, or with the ability to create a new site. You've probably already got the site that you want to switch to as top of mind and you just want to find it quickly.

So to me
- `/home` => fallback site switcher (treat it as if the user forgot to add the site slug in the URL)
- `/sites` => sites dashboard

I'd rather have a dedicated fallback site switcher view. It'd still be composed from the same components (so it'd re-use the main `<SitesTable>` for instance). But it wouldn't be the exact same view. To me replacing the site switcher is another project.

**Comment by SaxonF** [comment]
Agreed. I'd like to see us look more holistically at the global navigation and IA at some point, and that would include a refresh of the "site switcher"

![image](https://user-images.githubusercontent.com/1072756/178406091-faedeb04-b54f-443f-bd05-7a47406ca376.png)

**Comment by wojtekn** [comment]
@p-jackson @SaxonF, thanks for your feedback. I understand that our new Sites Dashboard is not a replacement for the current site switcher, and then the dropdown menu shown in the previous comment will perform that function instead.

I should clarify my previous comment - currently, I hooked our new dashboard into the "All My Sites" link that is available in the current switcher. I didn't replace the current sidebar switcher with the new dashboard. I replaced the full-page switcher, which we could also access by the `/sites` link. It works as follows:

![Screen Capture on 2022-07-12 at 08-36-05](https://user-images.githubusercontent.com/727413/178428545-0cd064de-418e-45f1-b60d-ab64f8a1bb5a.gif)

Note that at this point, I’m not trying to clarify what we should serve using direct `/home` or `/sites` links. I try to clarify how should we implement the main change we planned to do in the scope of this ticket which is:

> The "All My Sites" button in the Calypso sidebar links to /sites

By replacing the page served from this link, we step into the current site selector ground and modify its behavior. If we intend to show the new dashboard using this link, I see those approaches:

1. We replace the “All My Sites” page in all cases, regardless of the context. Thus we would show it for the user who navigates from `/home`, but also from `/media`, `/comments/all`, and more. Our new Site Dashboard would support contextual links, e.g. the following workflow:

- user is on the Media page of his blog
- they click on "Switch Site”,  then “All My Sites”
- new Sites Dashboard is displayed
- user chooses the new site
- user lands on the Media page of the new site

2. Alternatively, we would replace only the `/home` context. That way, when users click “All My Sites”, they will navigate to the new Sites Dashboard if they are in the `/home` context. If they were already working on `/comments/all`, they would see the old selector, and the behavior wouldn’t change.

3. Another way is to explore another entry point for the new Sites Dashboard on the design level.

I think that the first approach makes sense as an intermediate step. When a user clicks “Switch Sites” on any context, he would still see the sidebar site selector. Only when he clicked “All My Sites” would he see the new Sites Dashboard. In the future, the top selector would replace the sidebar selector, along with the “View All” link replacing the “All My Sites” functionality. My PR goes in that direction - the new selector is shown for all contexts, however, support for context is not finished yet on the Sites Dashboard page - regardless of the source context, the user will land on `/home` for the selected page.

**Comment by p-jackson** [comment]
Thanks for taking the time to explain @wojtekn. TBH I read your initial comment too quickly, and I should have slowed down to fully understand. But the way you've laid out the 3 options is very useful.

I agree with you on option (1). Since we're planning on making more drastic changes later, it makes sense that we would keep something closer to the current behaviour for now.

**Comment by p-jackson** [comment]
#65524 has merged which addresses this issue.

> - [ ] The `/sites` URL points at the sites management dashboard

The above criteria hasn't been met, but we discovered that it's not so easy to do (we can't use feature flags within `section.js` where sections are defined). But that's ok. I think it's ok for us to change the URL as part of the feature rollout.

It may still be possible to change the section definitions using a feature flag, but it might require a little hacking of the server code (e.g. maybe we change the section details at runtime _after_ reading them out of `section.js`?)

**Comment by wojtekn** [comment]
> It may still be possible to change the section definitions using a feature flag, but it might require a little hacking of the server code (e.g. maybe we change the section details at runtime after reading them out of section.js?)

When I was reviewing this, I found [a comment that provides more information about using config in `sections.js`](https://github.com/Automattic/wp-calypso/issues/61347#issuecomment-1047764063).
