### ISSUE TITLE
VideoPress: Upgrade prompt still appears on atomic sites.

### ISSUE THREAD

**Issue by jorpdesigns** [Automattic/wp-calypso#65192]
### Quick summary

Even though VideoPress is included by default on atomic sites, there is still an upgrade prompt visible in Jetpack performance settings.

I was able to reproduce on Business, eCommerce and Pro atomic sites. I couldn't reproduce on simple sites (i.e. Premium and simple Business plans) as Jetpack performance settings are inaccessible.

Slack thread: p1656925986266089-slack-C03TY6J1A

### Steps to reproduce

1. Access any existing atomic site or set up a new one. 
2. Navigate to Jetpack → Settings → Performance and scroll to the **Media** section at the bottom of the page where you will see a VideoPress upgrade prompt.
<img width="1261" alt="Screen Shot 2022-07-04 at 12 49 05" src="https://user-images.githubusercontent.com/40006288/177149049-4995b3b2-5ef5-4f07-861a-59a511e17fa2.png">

### What you expected to happen

There shouldn't be an upgrade prompt since VideoPress is included on Business, eCommerce and Pro plans.

### What actually happened

There is an upgrade button and clicking it leads you to a page asking you to purchase Jetpack VideoPress.

<img width="1096" alt="Screen Shot on 2022-07-04 at 10-46-35" src="https://user-images.githubusercontent.com/40006288/177149929-fe793a42-07bb-4710-91fe-a2c6103c9c52.png">

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

There is no user impact

**Comment by Nic-Sevic** [comment]
This was addressed in part for simple sites here btw: https://github.com/Automattic/wp-calypso/issues/64950
also it looks like this old issue might rely on the same checks? https://github.com/Automattic/jetpack/issues/21562

**Comment by cecilearkay** [comment]
Reported in 35709254-hc

**Comment by Joshgrygiel** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - NO
- Tested on Simple - NO
- Tested on AT ✅ 
- Tested on Self-hosted - N/A

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can confirm the VideoPress upgrade prompt does show within JetPack settings on all atomic plans

📌 ACTIONS
- Closed as duplicate in favor of this report: https://github.com/Automattic/jetpack/issues/21562
