### ISSUE TITLE
Sites Management Dashboard: technical exploration of Jetpack's dashboard

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65197]
Let's investigate the [cloud.jetpack.com](cloud.jetpack.com) dashboard to determine if their approach to loading sites can be extended to fit our use case. This would mainly entail expanding it to work with simple sites.

We should compare it with the existing way of loading the site data in Calypso and weigh the trade-offs. Feel free to propose another solution/alternative if you have more ideas.

You can use these posts as starting points:
- p1HpG7-fhc-p2
- pbtFFM-1X5-p2

The exploration should answer the following questions:

- can we reuse and extend the endpoints that are used for the Jetpack Cloud dashboard?
- can we reuse and extend some of the front-end components that they are using? (check if these are `@wordpress/components` or `@automattic/components`)

Done is:

- [ ] Document the results of the technical exploration in a P2 post on buildp2.
- [ ] Outline different approaches and their pros and cons.
- [ ] Select your preferred approach based on the trade-offs presented above.

**Comment by danielbachhuber** [comment]
@vindl Given we're already pulling live data into the dashboard, is there a specific problem you'd like to solve by using Jetpack's approach instead?

**Comment by vindl** [comment]
@danielbachhuber I think they chose their approach due to performance concerns in cases when there are hundreds of sites. So mostly uncovering if we need that right now, or if we can get by with the existing sites list in Calypso.

For some additional context, more long-term, we might need to consolidate the two dashboards, which will be easier to do if we have the same approach (i.e. by relying on the same endpoints to fetch the list).

Does that help clarify?

**Comment by danielbachhuber** [comment]
@vindl Yep, makes sense!

**Comment by danielbachhuber** [comment]
@zaguiini When you document your findings, here's a post format you could use:

- Description of the problem that you are trying to solve.
- List of a potential solutions that you considered.
  - Outline which solutions are blocked or not viable, and provide rationale.
  - If they seem viable, provide a high-level implementation plan.
- For the remaining viable solutions (if any), summarize the pros and cons.
- Based on the pros and cons, recommend the approach that we should adopt.

From https://github.com/Automattic/wp-calypso/issues/65170#issuecomment-1179205250

**Comment by zaguiini** [comment]
>can we reuse and extend the endpoints that are used for the Jetpack Cloud dashboard?

Replied in pdKhl6-sZ-p2.

**Comment by zaguiini** [comment]
>can we reuse and extend some of the front-end components that they are using?

Replied in pdKhl6-ty-p2.
