### ISSUE TITLE
Sites Management Dashboard: restore the ability to connect a Jetpack site

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65198]
We had the ability to connect a Jetpack site from Calypso, but that has been removed since. Let's explore the option of adding it back as a continuation of `+ New Site` efforts in the dashboard.

Check this comment and discussion above for more details: pbNhbs-1Yo-p2#comment-9228

cc @SaxonF

**Comment by SaxonF** [comment]
Left a comment here pbNhbs-1Yo-p2#comment-7355

**Comment by vindl** [comment]
Thanks @SaxonF! We can use the designs provided in the P2 post here: pdKhl6-HA-p2

![image-6](https://user-images.githubusercontent.com/1182160/189644391-d0649324-c01f-4ebb-a0ef-773744bde123.png)

With a caveat that we should present it as [a split button](https://web.dev/building-a-split-button-component/).

I'll close this issue and open up two separate tasks for development.
