### ISSUE TITLE
Limited Atomic post-revert emails have incorrect wording

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65194]
### Quick summary

After automatically reverting an Atomic site when a user cancels the last purchase that supports the Atomic feature, we send an email notifying that the revert has been completed.

This email assumes that (1) we have deactivated a plan, (2) the site is now on a Free plan, and (3) it can restores a backup. All of them are wrong when cancelling a marketplace plugin from an Atomic site on the Starter plan, so we need to amend the wording of that email.

<img width="500" alt="Screen Shot 2022-07-04 at 15 23 47" src="https://user-images.githubusercontent.com/1233880/177164456-3f418d54-c298-4a90-bd8e-8c54feab9294.png">

### Steps to reproduce

- Go to https://wpcalypso.wordpress.com
- Switch to an Atomic with a Starter plan
- Go to Upgrades > Purchases
- Cancel all the marketplace plugins
- Wait for the Atomic revert to be completed

### What you expected to happen

To receive an email indicating that the marketplace plugin has been deactivated

### What actually happened

I receive an email indicating some false statements:
- That I deactivated a plan while I deactivated a marketplace plugin
- That I'm now on the Free plan while I'm still on the Starter plan
- That I can restore my previous content from a backup, but the Starter plan doesn't provide backups

**Comment by obenland** [comment]
Patch in D83666-code

**Comment by obenland** [comment]
Diff in D83666-code

**Comment by obenland** [comment]
Fixed in D83666-code
