### ISSUE TITLE
Post Excerpt Block: Allow Manual Excerpts

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#65209]
### What

Right now, it seems that the Post Excerpt block will not use manual excerpts customers set, and so manual excerpts can't really be used on FSE sites.

Our docs do say:

> Take into account that not all themes support excerpts. You can consider using [More Blocks](https://wordpress.com/support/wordpress-editor/blocks/more-block/) as another solution.

But since this seems true for all FSE themes, it would be great if we had another option here. The More Block would display the beginning of each post and does not make it easy to set a custom excerpt.

### Why

It seems like we're missing a feature for FSE themes that is simple on older themes, and it's being requested.

one request in 5343140-zd

**Comment by vajrasar** [comment]
Hey @msilbers 👋 

I checked by creating a custom template > Query Block > adding Posts Excerpt block > and I can see that it shows the manual excerpts set on the posts for me.

I checked this on Livro theme. Can you please check on few other themes and share which of those are not working as expected with the Posts Excerpt block?

**Comment by cuemarie** [comment]
📌 Notes
-
- Double checked this on another test site using **Blockbase** and **Quadrat White**, and the manual excerpts are pulled into the Post Excerpts block.

![Markup on 2022-08-23 at 18:16:38](https://user-images.githubusercontent.com/27249804/186296274-75d98c5e-15c6-4b91-8fc7-bbc16dbb9595.png)


- It's possible this feature has been added, so closing out. Feel free to reopen and share any specific FSE themes where this is still missing.  Thanks!
