### ISSUE TITLE
Console errors and problems viewing WordPress.com on iPad Pro.

### ISSUE THREAD

**Issue by aerych** [Automattic/wp-calypso#6520]
This originates from a [user report in the iOS forums](https://ios.forums.wordpress.org/topic/ipad-problems-online).  First time loading wpcom and trying to view my post/page list results in no immediate content change, and there are errors reported in the console. Not sure if this accounts for what our user is seeing but that's how we got here. Grats @SergioEstevao, @frosty, and @nheagy for some practical testing that revealed what we first thought was some lag was actually something more.  

### Before you start:
1. Enable the Developer menu in desktop Safari 
2. Clear your browser cache in Safari on an iPad Pro, or in an iOS iPad Pro Simulator.
3. If using an actual device, usb tether.

#### Steps to reproduce
1. Load wordpress.com in mobile Safari
2. In desktop Safari, use the Developer menu to launch the debug console for mobile Safari.
3. Sign in to your wpcom account.
4. Switch from the Reader to My Sites
5. Try switching from Stats to Blog Posts. Notice there are errors in the console and the stats screen is still displayed.
6. Try tapping Pages. Notice there are errors in the console and the stats screen is still displayed.
7. Try tapping Blog Posts.  Notice it now loads, and there are no new errors.
8. Try tapping Pages. Notice it now loads, and there are no new errors.

[Gist of the console log](https://gist.github.com/aerych/ccd5c64fd868c8a7999c2d19d8654762)

#### What I expected
To view posts / pages the first time I clicked on the menu item.

#### What happened instead
There were console errors and content did not immediately load.

#### Browser / OS version
iOS 9.3 iPad Pro 

#### Screenshot / Video
<img width="1241" alt="screen shot 2016-07-04 at 10 08 57 am" src="https://cloud.githubusercontent.com/assets/1435271/16565056/803cb7dc-41d0-11e6-9fa6-77f3f59de762.png">

#### Context / Source
#user-report 
https://ios.forums.wordpress.org/topic/ipad-problems-online

**Comment by yoavf** [comment]
As per #6570, part of this doesn't seem to happen with iPad pro only

**Comment by yoavf** [comment]
Was able do reproduce the i18n-calypso TypeError, but no success in debugging yet. cc @Tug - should we open this in [i18n-calypso](https://github.com/Automattic/i18n-calypso)?

**Comment by Tug** [comment]
Yep it seems to be related to the `Localize` module in `i18n-calypso`. I bet this component is being unmounted twice or something like that.
![image](https://cloud.githubusercontent.com/assets/230230/16750705/f1bfba86-47d3-11e6-8dfc-4432412820cd.png)

Opening an issue for this in `i18n-calypso`!
