### ISSUE TITLE
Seller experience: create funnel to track current premium themes trend

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#65204]
We should create a funnel to see our current stats on Premium Themes purchases. That way we can measure the impact when we implement the subscription model.

Once the funnel is created it should be added to the FG.

Related to https://github.com/Automattic/wp-calypso/issues/65133

**Comment by andres-blanco** [comment]
@valterlorran can you follow up with your findings here?

**Comment by valterlorran** [comment]
I noticed that we have two funnels that we could use, instead of creating a new one. More context here: p1657050795979579-slack-C0Q664T29

**Comment by andres-blanco** [comment]
A new funnel was created and the link can be found here p1657290414468079/1657050795.979579-slack-C0Q664T29.
