### ISSUE TITLE
Marketplace: Update cats

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#65219]
As part of https://github.com/Automattic/wp-calypso/issues/64995

Update categories as required, per pdh6GB-1kr-p2, likely:

- [x] Add `live-chat` and `crm` tags to customer service category and rename it to `Live Chat & CRM`.
- [x] Add `Events Calendar` category, see pdh6GB-1kr-p2#comment-2208
- [x] Update Booking & Scheduling category tags, see pdh6GB-1kr-p2#comment-2208
- [x] Rename Education to "Online Courses", see pdh6GB-1kr-p2#comment-2208
- [x] Rename donation to "Crowdfunding", see pdh6GB-1kr-p2#comment-2208
- [ ] Bump up the SEO category so that it's always visible, and bump down a less popular category into the dropdown. pdh6GB-1kr-p2#comment-2237
- [x] Make a new github issue for the last part of pdh6GB-1kr-p2#comment-2208

**Comment by lsl** [comment]
>  Bump up the SEO category so that it's always visible, and bump down a less popular category into the dropdown.

@allilevine this list is in alphabetical order are we making this based on usage frequency instead?

**Comment by lsl** [comment]
Moved "Add `blocks` and `editor` tags to `Design` category per pdh6GB-1kr-p2#comment-2270" to a separate issue https://github.com/Automattic/wp-calypso/issues/65811

**Comment by lsl** [comment]
Dropping "bookings-plugin"/"booking-plugin" and "appointment-booking-system" as they lack results / should be covered by the others. Actual diff ended up just removing "reservations" as "reservation" already covered the same results. :shrug:

**Comment by lsl** [comment]
Went with "Learning management systems" after finding hardly any results under "online courses". Guess I was right about me not knowing this space :smile:

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/pull/65812 for most of the items in the list.

@allilevine Made a number of tweaks to what was planned based on what I found when loading the categories and digging into everything a bit further. Would you be able to review and afterward tag the PR with "String Freeze" label? Would like to wait for translation on this one.

**Comment by lsl** [comment]
Added new issue for the "last part" https://github.com/Automattic/wp-calypso/issues/65818

**Comment by allilevine** [comment]
> > Bump up the SEO category so that it's always visible, and bump down a less popular category into the dropdown.
> 
> @allilevine this list is in alphabetical order are we making this based on usage frequency instead?

@lsl What was the reason for ordering it alphabetically?

> Guess I was right about me not knowing this space 😄

Thanks for diving into the unknown. 😅

**Comment by lsl** [comment]
> @lsl What was the reason for ordering it alphabetically?

You'd have to ask @SaxonF for that. I assumed it was a UX choice, especially for the mobile slider and if we add more categories in future. Could make the case either way though I think.

**Comment by SaxonF** [comment]
I don't have strong opinions here. 

Alphabetical is better if someone knows what sort of plug-in they are looking for.

Popularity might be better when browsing .

**Comment by lsl** [comment]
Lets change to popularity and see what happens, if no improvement go back to alpha?

**Comment by allilevine** [comment]
> Lets change to popularity and see what happens, if no improvement go back to alpha?

@lsl Thanks, let's try it! Can you open a PR?

**Comment by lsl** [comment]
Sure, did the whole list based on p2, or did you mean just seo? (can change if yes) https://github.com/Automattic/wp-calypso/pull/65919
