### ISSUE TITLE
Marketplace: Improve explanation about github release URL

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#65217]
The FG page lists "Github Release URL" as required information, PCYsg-IFB-p2

There is an explanation provided but it's not entirely clear that we use this release mechanism for plugin installation and updates as a managed atomic plugin.

- [x] Update the release url explanation with more context
- [x] Cross reference PCYsg-IVH-p2 (using the github access token / url) inside the review phase checklist: PCYsg-IHt-p2

**Comment by lsl** [comment]
Partly explained this internally here PCYsg-IVH-p2 would be good to cross reference this in the submission flow as well. (added task above)

**Comment by allilevine** [comment]
We'll also need to document that a process for dotorg plugins with SaaS is TBD: p1657807549258009/1657806333.925859-slack-C029JEQRVRT

**Comment by lsl** [comment]
Put something in the warning notice re that situation. That should be enough to make us look at it again when we go to try remove that warning notice. I think we need to wait for resolution on the "licensing type 3" 13864-gh-Automattic/woocommerce.com
