### ISSUE TITLE
Marketplace: Investigate translation techniques in premium plugins

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#65221]
In order to understand how to support i18n users in the marketplace we need to know how 3pd's are currently managing translation in the wild. We want to know whether we need to provide auxiliary support through community, machine or paid translation.

We need a general idea about answers to the following questions across multiple plugins from external 3pd's:

- [ ] What languages/locales does the product support? 
- [ ] How do the translators manage the translations (community vs professional translations, continuously/tied to a release/one-off projects)?
- [ ] Where are they being hosted? 
- [ ] How are the translation files being delivered to the product users?

Spend some time looking at existing zip files from non a8c owned plugins on WooCommerce.com to get a general idea of how 3pd's are approaching translation of their plugins.

**Comment by allilevine** [comment]
@lsl How would you say this fits into our priorities, for adding 3PD plugins? Is it up to the 3PD partner to decide what translations to offer, or something that should be enforced?

**Comment by lsl** [comment]
We discussed this a lot more on p2 in the end pdh6GB-IF-p2, lets close in favor of https://github.com/Automattic/wp-calypso/issues/65331 which is a lot more concrete as far as first steps go. 

I don't think this falls directly on our priority list anytime soon - not a blocker for adding 3pd plugins.
