### ISSUE TITLE
Reader: WP audio playlists not clickable

### ISSUE THREAD

**Issue by dsmithweb** [Automattic/wp-calypso#6522]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/feeds/48967583
2. WordPress.com playlist embeds (made via wp-admin) are not clickable/playable from within Reader
#### What I expected

To be able to click "play" arrow on playlists
#### What happened instead

Play arrow is unclickable.
#### Browser / OS version

Windows 10--    Chrome 51.0.2704.103  and Microsoft Edge 25
#### Screenshot / Video

![audio playlists](https://cloud.githubusercontent.com/assets/20285748/16568593/ce8fc7aa-41f1-11e6-8812-0f613b1c0630.jpg)
#### Context / Source

User who consistently embeds single-item playlists brought it to my attention in livechat:
https://www.olark.com/transcripts/show/P6V6Xmq83NCXEiDn3Y9pJ3zbDTW21y2z 
# user-report

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed the issue exists as described above.  The Reader link no longer works, though, so here's a new one: https://wordpress.com/read/blogs/99123800/posts/132

Tested in OSX Chrome v54
