### ISSUE TITLE
Pricing grid overlaps table in Firefox when setting the top part of the grid to flex

### ISSUE THREAD

**Issue by gmovr** [Automattic/wp-calypso#65233]
Related to https://github.com/Automattic/wp-calypso/pull/65188

Setting a flex wrapper works in most browsers (Chrome, Safari, etc.) -- but in Firefox, this causes the top section to overlay the table (see screenshot below).

![Image](https://user-images.githubusercontent.com/52675688/177315916-97c1fab4-7bd5-4674-9a9d-8b1e72b5fe4a.png)

By having this flex container, we can have the call to action buttons aligned across locales. I.e. in Spanish where the content in one column is quite a bit larger than the other.

In p1657018736636569-slack-C031TFM2NKC @mtias suggested a solution to move the bottom half (price, call to action) into its own table row, but it would need a slight code refactor.

**Comment by ciprianimike** [comment]
I cut the branch update/plan-grid-flex-design and create a PR from [update/plan-grid-flex-design-extra-row](https://github.com/Automattic/wp-calypso/tree/update/plan-grid-flex-design-extra-row) into [update/plan-grid-flex-design](https://github.com/Automattic/wp-calypso/tree/update/plan-grid-flex-design).

I successfully split the price and button contents into a new component: `PlansComparisonColCTA` and added them in the new table row.

It still requires some CSS tweaks based on breakpoints and cross-browser tests but it should be straightforward at this point.
<img width="933" alt="Screenshot 2022-07-06 at 18 12 18" src="https://user-images.githubusercontent.com/5706607/177596186-de276b2f-fdc4-4364-a919-234fdda0f1c4.png">

**Comment by ciprianimike** [comment]
PR ready for review: https://github.com/Automattic/wp-calypso/pull/65302

**Comment by gmovr** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/65188/ @chriskmnds  @ciprianimike

**Comment by gmovr** [comment]
@mtias
