### ISSUE TITLE
create-marketplace-product command doesn't execute create_store_product_entry_from_plan non-interactively

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#65243]
The create-marketplace-product command calls `create_store_product_entry_from_plan` which has interactive prompts. We should make this non-interactive too.

Simply passing --yes to the `create_store_product_entry_from_plan` call will not suffice as some of the questions are not yes/no and one of those that are should always be answered with a no ('multi')

**Comment by rcrdortiz** [comment]
Set as a blocker since this requested feature blocks testing the new CLI command.

**Comment by rcrdortiz** [comment]
Fixed in: D83764-code
