### ISSUE TITLE
Redundant scrollbar in Goals Capture screen

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#65241]
There’s a small scrollbar visible for no good reason on Chrome at popular screen size pdDOJh-sJ-p2#comment-355

**Comment by TimBroddin** [comment]
By default 60px padding is added underneath `.step-container.layout.is-horizontal-layout.has-navigation`. I think we can safely remove this.

**Comment by TimBroddin** [comment]
I couldn't replicate this, seems like the screen changes quite a bit since July 2022 😀
