### ISSUE TITLE
Add align tool (wide & full) to Form block

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#65248]
Created from a draft note from `Apex: Inbox (Backlog)` project.

**Comment by TimBroddin** [comment]
Add the align tool to the Form Block, similar to https://github.com/Automattic/jetpack/pull/22703 and https://github.com/Automattic/jetpack/pull/22645

- [ ] add the Align support with Wide & Full Width options
  - [ ]  if needed add "inner-container" div - to make sure all inner blocks can be aligned on their own. Similarly to how the core Group block works 
- [ ] if block's DOM structure was modified then deprecate the current block version as version v1 and adjust fixtures

**Comment by TimBroddin** [comment]
https://github.com/Automattic/jetpack/pull/26988

**Comment by TimBroddin** [comment]
Duplicate: https://github.com/Automattic/jetpack/pull/27151
