### ISSUE TITLE
Theme Showcase: Theme upload upgrade button asks for site before checkout

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#65267]
#### Steps to reproduce

1. Starting at theme showcase on a free site
2. Click upload button
3. Click banner suggesting a plan upgrade
4. BUG: See "Select a site to open Checkout"

#### What I expected

To go to checkout.

#### What happened instead

I saw this screen.

![image](https://user-images.githubusercontent.com/545779/177421148-4ed4effb-e558-4c76-a26b-d67788b8b4e4.png)

**Comment by andres-blanco** [comment]
If you change the link to use the `site_slug` instead of `site_id` it works as expected.
