### ISSUE TITLE
[Bug]: Limited Atomic - Setting up already activated WooCommerce on a Starter Plan leads to a prompt to upgrade to Pro and install Woocommerce

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/wp-calypso#65264]
### Quick summary

After installing the WooCommerce Bookings extension I began setting up WooCommerce with my basic store information. Once I reached step 3 of the 4 step process I was prompted to install WooCommerce and upgrade to the Pro plan.  I had already installed WooCommerce Bookings and did not expect this. 

### Steps to reproduce

1. Start with a Starter Plan site with the [Marketplace Plugins toggle activated.](https://wordpress.com/?flags=marketplace-starter-plan)
2. Navigate to Plugins
Install a WooCommerce extension.
3. Verify the WooCommerce menu is active.
4. Click on WooCommerce and Begin setting up your test store. 
5. Reach step 3 and be prompted to install the Pro plan and activate WooCommerce.

### What you expected to happen

I expected to be able to set up my WooCommerce store since WooCommerce was already activated and WooCommerce Bookings was activated.

### What actually happened

I was prompted to purchase and install WooCommerce and activate the Pro Plan. 

![image](https://user-images.githubusercontent.com/36801460/177401298-3a2400fa-c45b-4405-ac39-a6db9ba3af48.png)

### Context

Team Testing

### Browser

Google Chrome/Chromium

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Installing Woo and upgrading to the Pro plan will allow you to move forward.

**Comment by obenland** [comment]
Based on the screenshot it looks like you were in the `woocommerce-installation` flow in Calypso. The WooCommerce menu item should stop linking to that flow when the WooCommerce plugin is active.

Is it possible this might be a timing issue where the site has not fully transferred and the plugin is not active yet?
Alternatively, it's also possible the admin menu hasn't refreshed after the transfer and plugin installation, keeping that old URL.

**Comment by obenland** [comment]
It makes sense to refresh admin-menu after a plugin was activated either way. I'm not sure we do that after a transfer though?
