### ISSUE TITLE
[Bug]: Prompted to Upgrade to install WooCommerce on Starter, after installing WooCommerce Extension

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/wp-calypso#65263]
### Quick summary

When testing the Marketplace Plugins on the Starter Plan, I am able to successfully install the WooCommerce Bookings.  But under Plugins - WooCommerce is listed as Free and available if I upgrade to the Pro Plan, even though it is already installed and active.  I know that core Woo is not included in the Marketplace but shouldn't it be removed from the options if it's already installed with an extension? 

### Steps to reproduce

1. Start with a Starter Plan site with the [Marketplace Plugins toggle activated.](https://wordpress.com/?flags=marketplace-starter-plan) 
2. Navigate to Plugins
3. Install a WooCommerce extension. 
4. Verify the WooCommerce menu is active. 
5. Navigate to Plugins
6. Click on the WooCommerce plugin

### What you expected to happen

WooCommerce because it is already active, should not be an option to install. 

### What actually happened

I was prompted to install WooCommerce by upgrading to the Pro Plan. 

![image](https://user-images.githubusercontent.com/36801460/177399563-9b225618-cf76-43e3-aa83-7016c5ede85c.png)

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Upgrade to the Pro Plan and have access to all plugins.

**Comment by obenland** [comment]
@mreishus I wonder if we should add an exception for WooCommerce in `maybe_limit_to_marketplace_plugins()`?

It won't help with any other plugin dependencies but at least it would cover most of the paid plugins we have available now.

**Comment by mreishus** [comment]
I think that's a good idea.

**Comment by mreishus** [comment]
When I tried it, it removed Woocommerce from the "Editor's pick:" section:
![2022-07-05_15-25](https://user-images.githubusercontent.com/937354/177410460-fc03ed1b-4e28-4f46-bbb6-3a5f30d21d31.png)

On `/plugins/woocommerce/<site>`, you're not prompted to buy anything. There's one slider which we could lock down
![2022-07-05_15-26](https://user-images.githubusercontent.com/937354/177410491-06bf7d86-73fe-4ff9-81c3-9dfc5dd4366f.png)

**Comment by obenland** [comment]
Yes, let's add that exception and handle the toggle

**Comment by obenland** [comment]
@mreishus The merged PRs have fixed this issue?

**Comment by mreishus** [comment]
Yes, I believed they fixed it. Note that a WoA Dev site might not have the latest wpcomsh on it and needs to either be manually updated or reverted/retransferred. Should we close?

**Comment by obenland** [comment]
Yes, WooCommerce now shows up in the Installed Plugins Screen and the toggles are gone in the single plugin screen:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/1398304/177588626-d78f3b7e-1508-4b9b-a9a6-4bd2e9b49bce.png">

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1398304/177588493-8faf527b-45cc-4f7b-b052-0c1eba62bc94.png">
