### ISSUE TITLE
Plugins > Installed Plugins > Add New Redirects to Calypso for Local Users

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#65289]
### Quick summary

Local users on atomic sites (i.e. users created without a WordPress.com account, while SSO is off) are redirected to Calypso, but cannot use Calypso screens without a WordPress.com account.

### Steps to reproduce

1. On an atomic site, turn off SSO
2. Go to SITE-URL/wp-admin/users.php
3. Click Add New and invite a new local user
4. In an incognito window, log into SITE-URL/wp-admin with the local user credentials
5. Go to Plugins → Installed Plugins and click the Add New button
6. Notice the redirect to https://wordpress.com/plugins?site=SITE-URL

### What you expected to happen

I expected to be taken to SITE_URL/wp-admin/plugin-install.php

### What actually happened

I was redirected to https://wordpress.com/plugins?site=SITE-URL and therefore cannot install a plugin on the site.

### Context

#35975989-hc

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

You can successfully go to Plugins → Add New as a local user and install a plugin.

However, we should have consistency with other buttons for adding a plugin, so it would be best to give Plugins → Installed Plugins → Add New the correct behavior.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple - no
- Tested on AT ✅ 
- Tested on Self-hosted - no

📌 FINDINGS/SCREENSHOTS/VIDEO
- I cannot replicate this on my end.

📌 ACTIONS
- Await author feedback


📌 Message to Author
 - Could you check if this is still an issue for you @donalirl ?

**Comment by donalirl** [comment]
Hi @Robertght , yes it's still an issue. I recorded a video to show what happens when clicking Add New after logging in as a local user on an atomic site:

https://user-images.githubusercontent.com/30727666/178961911-981a29a8-cdad-41c3-97ab-2e7de8024bc3.mp4

Maybe you were navigating to Plugins → Add New? To clarify, you need to navigate to Plugins, and then click the 'Add New' button at the top of that screen.

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Moving this back to `Needs Triage` to get retriaged with the updated information above.

**Comment by zachspears** [comment]
Able to reproduce, changed Priority to low due to easy workaround and low impact.

**Comment by cpapazoglou** [comment]
We can probably check whether the user is a local user and escape early in wpcomsh `feature-plugins/masterbar.php:235` `wpcomsh_update_plugin_link_destination()`

**Comment by nelsonec87** [comment]
Notes:
- `wp-admin/plugins.php:729` calls `self_admin_url( 'plugin-install.php' )`
- `self_admin_url()` triggers `self_admin_url` filter
- the filter is added by `wpcomsh/feature-plugins/masterbar.php:262`
- `wpcomsh_update_plugin_link_destination( $url, $path )` is triggered by the filter
- this function replaces the `wp-admin` path with the calypso path regardless of whether the user is local or not.

I believe the approach suggested by @cpapazoglou is the best way to fix this.

**Comment by nelsonec87** [comment]
I've found an (apparently) simpler way to fix this and implemented it on this PR https://github.com/Automattic/wpcomsh/pull/1218

It checks if the SSO module is active or not. It not, keeps the user in `wp-admin`.

**Comment by nelsonec87** [comment]
Fixed in https://github.com/Automattic/wpcomsh/pull/1218
