### ISSUE TITLE
Goals Capture: DIFM first, Import second.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#65281]
For the Goals Capture i2 screen.
As long as DIFM is chosen, go to DIFM.
Else, as long as Import is chosen, go to Import flow.

**Comment by ivan-ottinger** [comment]
> As long as DIFM is chosen, go to DIFM.
> Else, as long as Import is chosen, go to Import flow.

This means that:
- when the goal combination user selected includes DIFM, the Intent should be set to DIFM (regardless of other goals selected)
- when the goals combination user selected includes Import, the Intent should be set to Import (regardless of other goals selected)
- if both: DIFM and Import goals are selected at the same time, DIFM has the priority and the DIFM Intent will be set.

Do I understand the logic correctly?

**Comment by yansern** [comment]
> Do I understand the logic correctly?

Yes that's right.

**Comment by ivan-ottinger** [comment]
Thanks for confirming Yan. This should be a simple change - since we will likely only need to change the order of existing `goalsToIntent()` conditions in `packages/data-stores/src/onboard/utils.ts` (when the `signup/goals-step-2` feature flag is enabled):

```js
	// For Plan B, clicking on Import link supercedes everything.
	if ( goals.includes( SiteGoal.Import ) ) {
		return SiteIntent.Import;
	}

	// Including DIFM goal overwrites any other goal selection made
	if ( goals.includes( SiteGoal.DIFM ) ) {
		return SiteIntent.DIFM;
	}
```

I will test it out and create a PR.

**Comment by ivan-ottinger** [comment]
> This should be a simple change - since we will likely only need to change the order of existing `goalsToIntent()` conditions in `packages/data-stores/src/onboard/utils.ts` (when the `signup/goals-step-2` feature flag is enabled):

At the end it wasn't necessary to check for the `signup/goals-step-2` feature flag - as both goals (DIFM and Import) can be selected simultaneously on the Goals Capture i2 screen only. Goals Capture i1 screen is navigating to DIFM and Import flows using direct links.
