### ISSUE TITLE
[Bug]: WooCommerce Subscriptions in staging mode after install

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#65310]
### Quick summary

When purchasing the WooCommerce Subscriptions plugin on a site without a custom domain it displays an error message in wp-admin about the site being a duplicate and the plugin being in staging mode.

### Steps to reproduce

1. Create a new site on a Starter plan or Pro plan (no custom domain).
2. Purchase WooCommerce Subscriptions from the Marketplace
3. Click "Manage Plugin" after the Atomic transfer completed.
4. Note the error message 
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/1398304/177614124-206c820b-dd3b-449a-a08e-018a22655a64.png">

### What you expected to happen

No error message.

### What actually happened

Error message.

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Following the steps above, my site AT'd and activated Woo Subscriptions without getting stuck in staging mode
- At the beginning of the process, when I clicked **Install and Activate**, I was prompted about the subdomain change.
- At the end, no duplicate site error found when I opened `/wp-admin/edit.php?post_type=shop_subscription`

![Markup on 2023-05-03 at 13:35:24](https://user-images.githubusercontent.com/27249804/236043895-63095e1e-4e38-4647-bd9e-b3d1acfbd72f.png)

**After installing and activating (thus transferring site to Atomic)**

![Markup on 2023-05-03 at 13:36:21](https://user-images.githubusercontent.com/27249804/236043948-8a8cbe5d-a243-4c0d-ad06-6c63b1f7bc7a.png)

📌 ACTIONS
- Closed as not reproducible (please reopen if the issue reoccurs)
