### ISSUE TITLE
[All] Define and add link descriptors to Great Posts links

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65313]
### Details

This is a follow-up issue from the patch D81824-code. On Subscriber Welcome email there is a list of top posts from the blog, this task meant to add the link-desc for these links. The list is rendered on `HTML_Email` class, inside the`blog_top_posts` property. This list will also be used on the new Emails i2 templates.

![Image](https://user-images.githubusercontent.com/3113712/177620050-a730fdc3-d977-4501-aebc-53ba5d66aec1.png)

**Reference:** D81824-code#1737108

### Checklist
- [x] Define a link descriptors for the links in the blog_top_posts
- [x] Verify possible naming collisions
- [x] Include data-tracks-link-desc on links
- [x] Verify if the descriptor is available in the URL event data

**Comment by mashikag** [comment]
✅ Done: D85005-code
