### ISSUE TITLE
[Subscriber Welcome] Investigate missing link-desc for Unsubscribe button

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65312]
### Quick Summary

This is a follow-up issue from the patch D81824-code. The link description on Subscriber Welcome templates was added in this patch, but based on review comments one link-desc is missing. The Unsubscribe link, has the description defined on code, but in some scenarios it may not add to the data in the URL. It requires a quick investigation to make sure it's still an issue or not.

Reference: D81824-code#1737108

**Comment by TimBroddin** [comment]
It seems that link_description is present. Closing this ticket.

<img width="781" alt="CleanShot 2022-09-21 at 09 48 58@2x" src="https://user-images.githubusercontent.com/528287/191446370-3d8e8f92-6a92-4f08-a787-ac1ff5cd1eae.png">
