### ISSUE TITLE
Posts: Page is misleading when you have drafts but no published posts

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#6531]
Currently, the page is off when you have drafts, but no published posts:

<img width="987" alt="screen shot 2016-07-05 at 11 19 46 am" src="https://cloud.githubusercontent.com/assets/5835847/16593420/7353114c-42a2-11e6-8a0f-c3e18f15fa88.png">

I think if there's posts, even in a draft state, we shouldn't show the `You haven't published any posts yet.` UI. Its misleading.

**Comment by alisterscott** [comment]
Current message:

![Uploading Screen Shot 2017-12-21 at 9.20.17 am.png…]()
