### ISSUE TITLE
Titan Mail: dialog is not formatted for mobile viewport size

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#65324]
### Quick summary

Titan Mail dialog appears in mobile sized viewport as a full-sized desktop dialog and thus is indismissable.

From: p1657140943900189-slack-C029GN3KD

### Steps to reproduce

1. Using mobile browser (or a simulated mobile browser via Developer Console), sign up for Titan Mail.
2. visit `/home`.

### What you expected to happen

Dialog boxes that appear when using a mobile-sized viewport are sized accordingly.

### What actually happened

Dialog box is desktop-sized.

![image](https://user-images.githubusercontent.com/6549265/177642319-ecc0a3d7-1503-4dc3-9739-7c746e7a17b4.png)

### Reproducibility

Consistent

**Comment by wongasy** [comment]
@worldomonation The issue should be fixed now! 

![jtim-mobile](https://user-images.githubusercontent.com/104910361/177759410-c5b253e0-9c01-45d1-9251-b4d00f413b66.jpeg)
