### ISSUE TITLE
Sites Management Dashboard: Manage filter state through query parameters

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#65323]
### What

It should be possible to open the sites list (`/sites-dashboard`) in a certain state.

### Why

This would allow for a better user experience: imagine scenarios where people bookmark the sites list link at a certain state and they want to quickly apply the same filters.

Another very common scenario is to share a link with the filters so other people could see the same page as the sender.

### How

The easiest and most practical way would be to parse query parameters on page load while updating them on every filter update in the UI.

### Example usage

The idea that came up in https://github.com/Automattic/wp-calypso/pull/65296#discussion_r915008706 makes it possible to:

1. open the sites list;
2. change filters;
3. grab the URI in the address bar;
4. open the same link elsewhere...

And see the same filters being applied to the sites list.

### Acceptance criteria

- [ ] The app reads query parameters and applies the filters to the site list on load
- [ ] Changing a filter in the sites list updates the query parameters

**Comment by p-jackson** [comment]
Good idea! I also like the idea of a `?s=` query param that remembers the search field. We do that in Calypso views like:
- `/posts/{ siteSlug }?s=search+term`
- `/themes/{ siteSlug }?s=search+term

Would it be nicer to just use a path slug to represent the tab? e.g. `/sites-dashboard/coming-soon`. That way we don't have to decide what the name of the query param would be 😄 i.e. would it be like `?launch-status=`? What if one day we want to have a tab for something that's not about launch status?

I see the theme UI has filter and searching, but I think it's URL looks a bit strange e.g. `/themes/filter/column:one-column+blog-excerpts/{ siteSlug }?s=search+term`.
