### ISSUE TITLE
Understand current state of design for Superstack

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#65339]

**Comment by bogiii** [comment]
**Our entry FE work here can be broken down:**
- Register library package: `@automattic/subscriber`
- Build a simple HTML form for adding subscribers
- Hydrate screen with adding form validation
- Add **Upload a CSV file** functionality
- Decide how we are going to send **the email list** from the uploaded file (uploading to the server and doing everything on the WPCOM BE side, or read a file locally by JS)
- Are we going to validate CSV file locally? If so, we need to decide what is the format of the file content.

For now, there are two available screens:

<img width="878" alt="Screenshot 2022-07-08 at 15 46 33" src="https://user-images.githubusercontent.com/1241413/178004540-27fad185-76b2-4fde-b2c2-6b7e606eaf89.png">

<img width="878" alt="Screenshot 2022-07-08 at 15 46 52" src="https://user-images.githubusercontent.com/1241413/178004555-1318c483-abd9-4a25-990d-692571331aa1.png">
