### ISSUE TITLE
Marketplace: Product Licensing - Sync vendor webhook url 

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#65345]
## Summary

We are planning to reuse existing infra on WCCOM for onboarding vendors and gathering their information. WCCOM also allows 3PD to get their API/Secret keys from dashboard to call relevant api. This API/Secret key are also used for authentication. We need to implement mechanism of syncing API/Secret keys and basic info about vendor to WPCOM on WCCOM side. 

Related to pdh6GB-1dL-p2#comment-1951

**Comment by gcsecsey** [comment]
Backlog grooming: we've discussed to only estimate the investigation part of this ticket

**Comment by cpapazoglou** [comment]
- [x] new WP page (if a relevant doesn’t exist)
- [x] API key generation from interface
- [x] webhook url field
- [x] saving to user meta (vendor meta)
- [x] creating a WPCOM route that WC.com can call to sync vendor info
- [x] calling WPCOM to save this fields
- [x] storing them in WPCOM

**Comment by cpapazoglou** [comment]
Updated the points for resolving this.

**Comment by allilevine** [comment]
> webhook url field
> saving to user meta (vendor meta)

@cpapazoglou Created an issue for these, feel free to change it: 13954-gh-Automattic/woocommerce.com

**Comment by cpapazoglou** [comment]
@JulianBustamante is there any update here? Can you share a diff?

**Comment by gavande1** [comment]
I am not 100% sure but it seems D86085-code to close

**Comment by cpapazoglou** [comment]
Yeah just found it too
D86085-code - creating a WPCOM route that WC.com can call to sync vendor info

**Comment by obenland** [comment]
Also 14172-gh-Automattic/woocommerce.com

**Comment by JulianBustamante** [comment]
Deployed r251070-wpcom

**Comment by obenland** [comment]
With the merge of 14172-gh-Automattic/woocommerce.com this should be complete. @JulianBustamante could you confirm?

**Comment by JulianBustamante** [comment]
@obenland Sure! Let me check how can I confirm this on prod.

**Comment by JulianBustamante** [comment]
@obenland I tested it on production updating `woocommerce-bookings` and it worked as expected. 🎉

**Comment by obenland** [comment]
Amazing. Thanks!
