### ISSUE TITLE
Seller Experience: Info button is always on "modal opened" state

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#65356]
Currently the info button is in it's opened state all the time. 

The button should look like this 
<img width="837" alt="image" src="https://user-images.githubusercontent.com/375980/177784555-87580c61-3835-4cf0-9dcf-fa702ad35fe7.png">
 when the modal is closed and like this 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/375980/177784804-a63e448e-d838-43dc-be34-05dd7048a968.png">
when the modal is open.

See the figma for more info: 0EogtxvlmxMGcnEEaMVECv-fi-143%3A11771

**Comment by andres-blanco** [comment]
I will keep this in the inbox for later, but it wont be necessary since we are temporarily removing the [i] button. p1657205822497629/1657140724.592239-slack-C0Q664T29

https://github.com/Automattic/wp-calypso/issues/65360

**Comment by blackjackkent** [comment]
Let's reconsider this when we have Woo-specific themes.

**Comment by andres-blanco** [comment]
The info button was dropped and a new design was implemented for picking color schemes.
<img width="312" alt="image" src="https://user-images.githubusercontent.com/375980/225757402-d06cd8a2-da16-4364-b85c-5d9cbfc87e1d.png">
