### ISSUE TITLE
Seller Experience: The preview in design picker is not full screen

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#65361]
What we have now:
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/375980/177787216-d58733a8-d628-4468-9b36-363e9d5daaec.png">

vs what's in the Figma:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/375980/177787553-6dd70416-84e2-42cb-aa38-9049704c9a07.png">

Notice how there's not a device picker and a no browser URL bar.

ref: 0EogtxvlmxMGcnEEaMVECv-fi-143%3A11771

**Comment by valterlorran** [comment]
I looked at the component that renders the preview, and there's no simple way to make it fullscreen and hide for example, the navigation bar. It's also worth mentioning that the issue that we initially worked on had the following note:

> Should display site preview in the same manner as existing behavior

https://github.com/Automattic/wp-calypso/issues/64717

How should we proceed, @andres-blanco?

**Comment by andres-blanco** [comment]
Closing this issue for the time being since more changes might be inline for this component. Context: p1657140724592239-slack-C0Q664T29
