### ISSUE TITLE
Sites Management Dashboard: cross-browser testing

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#65367]
Once the i1 of the project is completed and before we release it to customers, let's do cross-browser testing.

Browser list:
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Safari
- [x] Opera
- [x] Microsoft Edge

List based on https://wordpress.com/support/browser-issues/.

**Comment by p-jackson** [comment]
Tested on Windows with Browserstack
- Edge
- Opera
- Chrome

Tested on Mac natively
- Chrome
- Firefox
- Safari

Tried IE just to see what would happen, but I even struggled to log in
