### ISSUE TITLE
Reader: Placeholder never updates after following site

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#6537]
Today, I noticed that when I attempt to follow a site by going to https://wordpress.com/following/edit and then adding the site's URL in the top input, that a placeholder is added to the list, but the placeholder never updates.

Here's a video of the bug:

https://cloudup.com/cbahbaTicUJ

**Comment by jancavan** [comment]
I also noticed that the disabled button when a URL isn’t valid is clickable now, although disabled styles are still being applied to it:

![screenshot 2016-07-05 13 43 31](https://cloud.githubusercontent.com/assets/4924246/16599287/7da6ad34-42b6-11e6-8b07-48cf0f05b41f.png)

**Comment by bluefuton** [comment]
@jancavan that should be fixed in #6743 :)

**Comment by bluefuton** [comment]
@ebinnion I have seen this happen occasionally, but don't have a consistent repro. Is there a certain feed URL you've used that triggers it?

**Comment by bluefuton** [comment]
Looks like it happens when the API endpoint doesn't hand us back the new subscription in `action.data.subscription`. When it's empty, handleAdd() is never triggered and `isAttemptingFollow` stays true, which means the placeholder never vanishes.

Investigating why we don't always get a subscription in the response.

**Comment by bluefuton** [comment]
Looks like a URL mismatch. The feed URL for the subscription is "http://jessicalawlor.com", but the actual feed URL in the user's subscriptions is "http://jessicalawlor.com/feed". The endpoint attempts to find an exact match, and fails in this case.

**Comment by bluefuton** [comment]
Internal API patch fixing this is D2274.

**Comment by bluefuton** [comment]
Fixed in wpcom-r138689.

**Comment by jancavan** [comment]
Nice work @bluefuton 👍
