### ISSUE TITLE
No indication that required plan is charged yearly when display monthly price for paid plugin

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#65386]
### Quick summary

When the "Monthly Price" option is toggled, there's no mention that the required Starter plan is charged on a yearly basis.
<img width="927" alt="Screen Shot 2022-07-07 at 12 44 38 PM" src="https://user-images.githubusercontent.com/11635760/177859193-a6c0fbd6-4eeb-4cf8-b379-6104f920c1be.png">

### Steps to reproduce

1. Go to https://wpcalypso.wordpress.com/plugins/woocommerce-subscriptions/
2. Select the Monthly Price option in the dropdown menu at the top right.

### What you expected to happen

Some sort of wording that makes it clear that the Starter plan is going to be a yearly charge despite the "Monthly price" option displaying the paid plugin's monthly charge.

### What actually happened

The wording about the price of the Starter plan stayed the same regardless of switching between "Monthly price" and "Yearly price."

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- UI has been updated a bit; plan suggestion now matches the Monthly/Annually selection for the plugin.

![YjYLOu.gif](https://user-images.githubusercontent.com/27249804/236036641-20abfb72-bb97-4203-8e5d-7e5a1e4e51f7.gif)

📌 ACTIONS
- Closed as no longer relevant
