### ISSUE TITLE
Apostrophe-2 Theme: Featured images are not shown in Blog Posts Block

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#65394]
### Quick summary

When you add a blog posts block to a page while using the Apostrophe-2 theme, the featured images are not displayed

### Steps to reproduce

1. Start with a site with published blog posts with featured images
2. Create a page and add the blog posts block
3. Choose to display the images, in any position
4. Publish page, you will see the images
5. Activate https://wordpress.com/theme/apostrophe-2/
6. Images no longer appear

### What you expected to happen

The images should still be visible

### What actually happened

The images are missing. They do not show up in the code base either. It appears that the js files for the block won't load. I see this error in the console: 

```
DevTools failed to load source map: Could not load content for https://anotherproplansandboxjba8c.com/_static/blog-posts-block-view.min.js.map;: HTTP error: status code 400, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://anotherproplansandboxjba8c.com/_static/latest.css.map: HTTP error: status code 400, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Context

Customer report in #36009244-HC

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

https://wordpress.com/theme/apostrophe-2/

### Browser, operating system and other notes

Chrome, MacOS

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The workaround is to change the theme, which is not ideal for most users.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- It appears that the Featured images can be visible on the blog posts block, but only if the Featured images are set to be displayed on Pages from the Customizer > Content options:

![image](https://user-images.githubusercontent.com/6737345/178566718-6bb73e57-1b72-4acb-8e23-6d5ff7cab80c.png)


📌 ACTIONS

- Closed as no longer relevant 

📌 Message to Author
 - I'm going to close this for now, but please reopen it if there are other requests about this.
