### ISSUE TITLE
Header missing on homepage and header settings missing from customizer

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#65405]
### Quick summary

All pages show header and navigation except for the homepage, and #header is missing entirely in the HTML on the homepage. 
There is no `<header>` section at all on the homepage. There is an `entry-header` but no `header`.

Header settings are missing from the Customizer

Theme: Morden

### Steps to reproduce

1. Site was imported from AIOWPM / Theme: Morden
2. The homepage does not show Header, other pages do show the header
3. If we move the content of the homepage to a new page, Header is showing correctly
4. When we go to set the new pages as a homepage, the homepage settings are not showing in the Customizer
5. When we managed to set the new page as the homepage, Header content is missing again

We have tested further by deactivating all the plugins.

The following settings are not visible in the customizer: 
<img width="451" alt="slack-imgs" src="https://user-images.githubusercontent.com/44442769/177994351-712b26b4-64c1-4c9e-bd5b-6976646411c6.png">

### What you expected to happen

- Would expect the Header area to display correctly on the homepage
- Would expect the correct settings to show in the customizer to set the Homepage

### What actually happened

- Header not showing on homepage
- Settings within Customizer > Homepage Settings are missing

### Context

Chat: #36010615-hc
Ticket: #5357590-zen

### Workaround details

`homepage settings` does exist in the HTML code for the page at https://elanelectricinc.com/wp-admin/customize.php but the option is hidden. 
Homepage settings option has been changed manually in the database - but this is not a long term solution as the settings should work correctly.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - np
- Tested on Simple - no
- Tested on AT ✅ 
- Tested on Self-hosted - no 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I have created two new websites and activated Morden on the source site. I have exported and imported the site in a new on using AIOWPM and couldn't replicate the issue, which means this is probably a one-time glitch and potentially needs a permanent fix in the database. 


cc @Automattic/reactor 

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs


📌 Message to Author
 - Please open this again if you find more cases.
