### ISSUE TITLE
CPT: List View: Ellipsis more popover should have actions in the same order as Blog Posts actions

### ISSUE THREAD

**Issue by hugobaeta** [Automattic/wp-calypso#6540]
On Blog Posts we have the actions in the following order:

<img width="742" alt="postslist-actions" src="https://cloud.githubusercontent.com/assets/1514660/16597449/dca60638-42f0-11e6-8df4-3efb6466f225.png">

I think the CPT posts list popover menu should be ordered in the same way (and eventually have the same actions): Edit, View, Stats, and Trash.

![cpt-list-more](https://cloud.githubusercontent.com/assets/1514660/16597471/04161c94-42f1-11e6-98a4-a74ca0563ef6.png)

cc/ @aduth

**Comment by aduth** [comment]
@timmyc : Is the stats post detail screen capable of handling custom post types if we're to start directing traffic there?

**Comment by hugobaeta** [comment]
Just to be clear, the point of this issue is to make sure the actions are **ordered** the same way (and give a nudge to an eventual "stats" item). "View" should come first since it's also the primary action when you click the title in the list, "View" next, and so on ;)

**Comment by timmyc** [comment]
> Is the stats post detail screen capable of handling custom post types if we're to start directing traffic there?

CPT stats can be seen on the standard "post detail" page.  The path is the same ( no change based on post type ):

https://wordpress.com/stats/post/`postID`/`site.wordpress.com`
