### ISSUE TITLE
Consider incorporating Payments Setup into My Home Checklist

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#65446]
Starting a site with a Payments Block pre-added to your home page adds a card to My Home about "How to set up an online store" but does not add it to the checklist.

![image](https://user-images.githubusercontent.com/545779/178284597-ed0734de-326e-432e-860a-6789c28a5618.png)

Task: Consider how this task might be connected to the checklist instead.

**Comment by andres-blanco** [comment]
This doesn't look relevant anymore given all the changes that happened on My Home in the last 1.5 year. Closing.
