### ISSUE TITLE
Plugins: Incompatible plugins should not be featured as prominently as they are

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#65457]
It shouldn't be as easy as it is to find incompatible plugins. Perhaps they should only be appearing with searches that directly match the name?

## Example

Two incompatible plugins appear here:

![image](https://user-images.githubusercontent.com/545779/178304552-4144b41c-16b1-473c-b68c-d7943d8fb07f.png)

**Comment by ianstewart** [comment]
Another example:

![image](https://user-images.githubusercontent.com/545779/178305154-fd717bdb-e243-427b-8528-41327aa5aafd.png)

**Comment by cpapazoglou** [comment]
Loosely related to https://github.com/Automattic/wp-calypso/issues/65459

**Comment by allilevine** [comment]
@cpapazoglou I remember you had reservations about hiding these and user trust. Should we hide them short-term and look for another solution with Elastic Search?

**Comment by cpapazoglou** [comment]
> @cpapazoglou I remember you had reservations about hiding these and user trust. 

That's correct. We shouldn't totally hide them, we can though make them less prominent like moving them to the bottom of a search list. Also, we can avoid showing them in categories.

It seems like we should move the [incompatiblePlugins](https://github.com/Automattic/wp-calypso/blob/a0d28efdd4d19513e4b201b6701045906473ed53/client/my-sites/plugins/plugin-compatibility.js#L1-L136) in WPCOM and use them in ES indexing so that they are negatively boosted and fall to the bottom of searches. @gcsecsey  does this sound reasonable?

> Should we hide them short-term and look for another solution with Elastic Search?

We can already try poking with ES endpoint in `class.wpcom-json-api-marketplace-search-endpoint.php` and using `marketplace-jetpack-plugin-search` flag in Calypso. Not sure though if we can achieve what we want without altering the index. 

I think though, this is a low priority and we can avoid focusing in a short-term solution except it's like 1-2h work.

**Comment by allilevine** [comment]
> > Should we hide them short-term and look for another solution with Elastic Search?
> 
> We can already try poking with ES endpoint in `class.wpcom-json-api-marketplace-search-endpoint.php` and using `marketplace-jetpack-plugin-search` flag in Calypso. Not sure though if we can achieve what we want without altering the index.
> 
> I think though, this is a low priority and we can avoid focusing in a short-term solution except it's like 1-2h work.

@cpapazoglou Thanks! I think showing the most useful search results to the user is a high priority. Is there a 1-2h short-term solution?

@vinimotaa Do you have any design recommendations here, to make these less prominent?

**Comment by cpapazoglou** [comment]
> @cpapazoglou Thanks! I think showing the most useful search results to the user is a high priority. Is there a 1-2h short-term solution?

Nope, we can try removing them totally from categories by using the hard coded list and move them to the bottom of searches by changing their priority in ES.

**Comment by gcsecsey** [comment]
> It seems like we should move the [incompatiblePlugins](https://github.com/Automattic/wp-calypso/blob/a0d28efdd4d19513e4b201b6701045906473ed53/client/my-sites/plugins/plugin-compatibility.js#L1-L136) in WPCOM and use them in ES indexing so that they are negatively boosted and fall to the bottom of searches. @gcsecsey does this sound reasonable?

The overall approach seems all right to me, however having tried for a while, I'm uncertain if it's easy to implement such a query.

I've tried adding a should clause with a minimal boost value, but I'm only getting documents that match the must clause. Also, to be able to match multiple slugs from the blocklist (with a logical OR), am I right in thinking we can't use an array on the should term, but add each blocked slug as a separate term?

cc @gibrown 

```json
GET jetpack-search-21/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "blog_id": {
              "value": "108986944"
            }
          }
        },
        {
          "term": {
            "slug": {
              "value": "woocommerce"
            }
          }
        }
      ],
      "should": [
        {
          "term": {
            "slug": {
              "value": "wp-statistics", # can't we use ["wp-statistics", "wp-slimstat"] here?
              "boost": 0.00001
            }
          }
        }
        ]
    }
  },
  "_source": false,
  "fields": ["slug"]
}

{
  "took": 205,
  "timed_out": false,
  "_shards": {
    "total": 100,
    "successful": 100,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 12.96918,
    "hits": [
      {
        "_index": "jetpack-search-21",
        "_type": "_doc",
        "_id": "108986944-p-163",
        "_score": 12.96918,
        "_routing": "108986944-0",
        "fields": {
          "slug": [
            "woocommerce"
          ]
        }
      }
    ]
  }
}
```

**Comment by gibrown** [comment]
Use a terms query: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-terms-query.html

For playing with scoring you should also try out using the explain api to understand how the scores are calculated: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-explain.html

**Comment by gcsecsey** [comment]
Thanks for the quick help @gibrown!

I've managed to put together a function_score query that uses a terms query to score the block listed plugin slugs lower. Even if we try to match for a phrase that's in the plugin name, eg. `analytics`, the block listed plugins will show up at the end of the results:

```json
GET jetpack-search-21/_search
{
  "query": {
    "function_score": {
      "boost_mode": "multiply",
      "query": {
        "bool": {
          "must": [
            {
              "term": {
                "blog_id": {
                  "value": "108986944"
                }
              }
            },
            {
              "match": {
                "title.default": "slimstat"
              }
            }
          ]
        }
      },
      "functions": [
        {
          "filter": {
            "terms": {
              "slug": [
                "wp-slimstat",
                "wp-statistics"
              ]
            }
          },
          "weight": 0.000005
        }
      ]
    }
  },
  "_source": false,
  "fields": [
    "slug",
    "title.default"
  ]
}

{
  "took": 11,
  "timed_out": false,
  "_shards": {
    "total": 100,
    "successful": 100,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": 14.444826,
    "hits": [
      {
        "_index": "jetpack-search-21",
        "_type": "_doc",
        "_id": "108986944-p-48834",
        "_score": 14.444826,
        "_routing": "108986944-0",
        "fields": {
          "title.default": [
            "Post Pay Counter - WP-Slimstat visits"
          ],
          "slug": [
            "post-pay-counter-wp-slimstat-visits"
          ]
        }
      },
      {
        "_index": "jetpack-search-21",
        "_type": "_doc",
        "_id": "108986944-p-308",
        "_score": 0.000092687726,
        "_routing": "108986944-0",
        "fields": {
          "title.default": [
            "Slimstat Analytics"
          ],
          "slug": [
            "wp-slimstat"
          ]
        }
      }
    ]
  }
}
``` 

As the `Jetpack_WPES_Query_Builder` class wraps the query in a function_score query, I think it should be fairly easy to add a filter function that lowers the score of the incompatible plugins.

**Comment by gcsecsey** [comment]
Based on the above query, I think we can pick this up in our next sprint and implement it using the incompatible plugins list on WPCOM.

**Comment by gcsecsey** [comment]
Diff raised: D89948-code

It's ready for review.

**Comment by gcsecsey** [comment]
Changes deployed in r254520-wpcom
