### ISSUE TITLE
TourKit: one gif has the wrong highlight colour

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#65450]
One gif in the Editor Tourkit has the wrong colour of buttons. Or, at least, all the other ones are blue.

This one is pink.

![image](https://user-images.githubusercontent.com/545779/178288836-bfe599ae-f447-473b-8114-18046175116f.png)

The previous one is blue.

![image](https://user-images.githubusercontent.com/545779/178288894-f5ddf731-771b-4382-97a3-5dbea4e271d8.png)

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tour Kit / "Welcome Guide" does still show a mix of Blue & Pink in the guidance gifs (though my editing space now uses Pink everywhere, not blue):

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/236033283-395fecb0-05b3-4b45-8945-40e528f9be32.mp4

#### Steps to Replicate

1. Open Editor on a site
2. Select `...` at top right, and select **Welcome Guide** to trigger Tour Kit portal
3. Click through guide

📌 ACTIONS
- Assigned to @Automattic/vertex

**Comment by escapemanuele** [comment]
We could easily change the gif, but we need a new one for this.

I'm going to tag @donalirl, but I don't remember if it was him providing gifs in the welcome tour.

**Comment by escapemanuele** [comment]
This has been fixed by @agrullon95
