### ISSUE TITLE
Plugins: Installed on card border should be full-width

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#65464]
The bottom border here is not full-width. It seems as if it should be.

![image](https://user-images.githubusercontent.com/545779/178312995-f9844f5e-46d3-4763-8ef1-255d051f44dd.png)

**Comment by cpapazoglou** [comment]
This is not relative anymore with the new design



![Image](https://user-images.githubusercontent.com/12430020/187210886-7df3d8ff-514b-4bf0-83f1-2f44b6a25892.png)
