### ISSUE TITLE
[New Liked Comment] Display Great Posts on template

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65472]
### Details
The New Liked Comment template should display the **Great Posts** list, which will be placed bellow the content, in the email body. There is an existing layout for this on `new-follower.php` → `missed-content-container`, it can used as a starting point.

![Image](https://user-images.githubusercontent.com/3113712/179616269-082b7d15-4f79-4ee0-ae04-d66bed5bfb84.png)

**Figma reference:** c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A17275

### Checklist
- [ ] Create the Great Posts list on New Liked Comment

**Comment by mashikag** [comment]
✅ Done: D84301-code
