### ISSUE TITLE
Marketplace: replace paid plugins references to premium plugins

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#65487]
### What

We should move away from calling them paid plugins and relabel them as premium plugins. These are all handpicked, and we expect to maintain a high bar for quality so customers should see these all as premium. Paid is a result of these being premium

### Why

Related convo: pdh6GB-1yG-p2

### How

Searching for `paid plugins` in Calypso and replacing it with `premium plugins` should be enough.

**Comment by WBerredo** [comment]
On #66585 was handled only the visual mentions to Paid plugins. 

There are still other mentions to `paid` plugins as:
* variable names
* URL routes
* Comments
* Requests sent to the backend (not sure)

A follow-up task is needed for those items or it shouldn't be changed yet? 

As a dive-in is needed, if we choose to do this now, I anticipate it taking more than 1 point.

**Comment by cpapazoglou** [comment]
> On #66585 was handled only the visual mentions to Paid plugins.
> 
> There are still other mentions to `paid` plugins as:
> 
> * variable names
> * URL routes
> * Comments
> * Requests sent to the backend (not sure)
> 
> A follow-up task is needed for those items or it shouldn't be changed yet?
> 
> As a dive-in is needed, if we choose to do this now, I anticipate it taking more than 1 point.

URL routes could also be changed but they are already shared in media. I think we are ok with https://github.com/Automattic/wp-calypso/pull/66585
