### ISSUE TITLE
The button text overlapping on mobile

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#65495]
### Quick summary

The buttons block placed on the page when viewed from a mobile browser, the text on the button is a little long and it results in overlapping text.

### Steps to reproduce

1. Add multiple buttons in a single row.
2. Add the text on the buttons a little longer text.
3. View the page on a mobile browser.
4. The button text overlaps.

### What you expected to happen

I expect the left/right padding to collapse in order to support the buttons better on mobile.

### What actually happened

The button text was overlapping with each other.

### Context

Customer report
Live chat: 36042828-hc
Follow up ticket: 5366994-zd-woothemes
Screenshot: 
![Screenshot_2022-07-12-09-32-33-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/7382505/178505183-0a33a2a2-db85-4004-a772-cda0b71f516a.jpg)

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

This CSS helped in this case: 

```
.wp-block-button .wp-block-button__link {
	padding: 0.7em 0;
}
```

**Comment by Joshgrygiel** [comment]
📌 SCRUBBING
- Tested on P2 - N/A
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on Twenty Twenty Two theme, added multiple buttons through the `Buttons Block` within a `Row` as seen here:

![buttonstest](https://user-images.githubusercontent.com/88345647/178532742-6e34f897-f1c3-4846-acf3-9558a0718ae2.png)

This resulted in the following on mobile, which appears to be as expected:

![mobilerender](https://user-images.githubusercontent.com/88345647/178532830-cb1880bc-a522-49d6-b938-9ce2aebcf6c8.png)


📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)


📌 Message to Author
- @galakhyati I was unable to replicate the issue on the 2022 theme on my end, so I'm closing out this report. Does this issue seem to only occur on a specific theme, or on a user's site specifically?

**Comment by hacchism** [comment]
I had a chance to test this further as I got the same user reporting the issue again.

According to my further testing, it appears this is specific to Twenty Seventeen and related to https://github.com/Automattic/themes/issues/6023/.
