### ISSUE TITLE
Sites Management Dashboard: select only used fields when requesting `/me/sites`

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#65490]
### Details

As a result of the exploration done in pdKhl6-sZ-p2, @vykes-mac proposed selecting only a subset of the fields when requesting `/me/sites`. That will greatly decrease the average response time for that specific endpoint, resulting in a faster experience for the end-user.

Some preliminary tests (10 requests sample) showed that requesting only the used fields would almost halve the response time from `1.4` seconds to `0.8` -- yes, we are getting into the milliseconds range. Remember to unproxy yourself (or apply the same proportions) when running your tests.

We already have the infrastructure to query for a subset of the fields in the `/me/sites` endpoint, so it's a matter of selecting which fields to retrieve in the front-end.

#### Which fields are currently being used

I've played with [`client/state/sites/constants.js`](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/sites/constants.js) and came up with the following list after browsing the `client/sites-dashboard` module in Calypso:

```js
export const SITE_REQUEST_FIELDS = [
	'ID',
	'URL',
	'is_coming_soon',
	'is_private',
	'launch_status',
	'slug',
	'icon',
	'name',
	'options',
	'plan',
].join();

export const SITE_REQUEST_OPTIONS = [ 'is_wpforteams_site' ].join();
```

But obviously modifying that list is not a good idea since a lot of pages are querying for the sites list.

#### Implementation suggestion

Modify the [`requestSites` action](https://github.com/Automattic/wp-calypso/blob/8bd818b/client/state/sites/actions.js#L77) to accept the list of `fields` and `options` as an argument (defaulting to `SITE_REQUEST_FIELDS` and `SITE_REQUEST_OPTIONS` respectively.

Then, modify the [`<QuerySites />` component](https://github.com/Automattic/wp-calypso/blob/8bd818b/client/components/data/query-sites/index.jsx#L75) to accept the list of fields.

The `<Layout />` component should also accept the list of fields and options as part of the `context` argument. The `client/sites-dashboard` then would add the said list as a property to `context`.

Finally, we'll also need to create a subtype of `SiteData` so we can have type checking working properly.

#### Bonus task

We could go even further and try to understand why the average is `0.6` seconds despite requesting only the ID field... That's probably a back-end bottleneck at this point. This task includes researching why that's the case and, if easily fixable, creating a diff. You could also try looking for alternatives such as caching based on the selected fields and options.

### Done is

- [x] The request time for `/me/sites` is decreased
- [ ] Clicking `View Dashboard` from SMD correctly opens the single site, meaning it won't break anything
- [x] A diff with changes in the `/me/sites` endpoint or a P2 post describing the blockers

**Comment by danielbachhuber** [comment]
> * A diff with changes in the `/me/sites` endpoint or a P2 post describing the blockers

Did a performance analysis with pdKhl6-v6-p2

**Comment by danielbachhuber** [comment]
@Automattic/build @zaguiini @p-jackson There's one remaining piece to fix on this issue...

If you delete `calypso_store` in IndexDB and refresh the page, the dashboard links are incorrect (`http://calypso.localhost:3000/home/undefined`):

<img width="611" alt="image" src="https://user-images.githubusercontent.com/36432/179751722-90db21d5-0cce-4f26-9f48-d6344533a6a3.png">

This is because `getDashboardUrl` uses `slug`, which is a computed property:

https://github.com/Automattic/wp-calypso/blob/a3bd28f2b761eab7aeef2cdd17f97d5c0b4d3106/client/sites-dashboard/components/sites-table-row.tsx#L55-L57

https://github.com/Automattic/wp-calypso/blob/2a012af405964741086cab1818eddc09b17e40eb/client/state/sites/selectors/get-site-computed-attributes.js#L24-L29

When we switched to `react-query` in #65690, we're no longer necessarily using Redux store data (and have access to computed properties).

However, we don't want to call `getSiteComputedAttributes` for our new data, however, because it calls `getRawSite` and would add a bunch of API requests.

Couple of options:
1. It's possible to build dashboard URLs as `/home/<blog-id>` instead, but those are a bit ugly.
2. We can call `urlToSlug` directly to generate the slug. However, doing so would miss [this condition](https://github.com/Automattic/wp-calypso/blob/18ff765697cd7b8f81e4aa818a456d10e628f862/client/state/sites/selectors/get-site-slug.js#L23-L25), which I'm not sure whether is important.

```diff
diff --git a/client/sites-dashboard/components/sites-table-row.tsx b/client/sites-dashboard/components/sites-table-row.tsx
index a64a69cf94..bbb75ce522 100644
--- a/client/sites-dashboard/components/sites-table-row.tsx
+++ b/client/sites-dashboard/components/sites-table-row.tsx
@@ -4,6 +4,7 @@ import { useI18n } from '@wordpress/react-i18n';
 import SiteIcon from 'calypso/blocks/site-icon';
 import EllipsisMenu from 'calypso/components/ellipsis-menu';
 import PopoverMenuItem from 'calypso/components/popover-menu/item';
+import { urlToSlug } from 'calypso/lib/url';
 import SitesLaunchStatusBadge from './sites-launch-status-badge';
 import SitesP2Badge from './sites-p2-badge';
 import type { SiteExcerptData } from 'calypso/data/sites/use-site-excerpts-query';
@@ -52,7 +53,8 @@ const SiteUrl = styled.a`
 	}
 `;
 
-const getDashboardUrl = ( slug: string ) => {
+const getDashboardUrl = ( URL: string ) => {
+	const slug = urlToSlug( URL );
 	return '/home/' + slug;
 };
 
@@ -63,9 +65,7 @@ const displaySiteUrl = ( siteUrl: string ) => {
 const VisitDashboardItem = ( { site }: { site: SiteExcerptData } ) => {
 	const { __ } = useI18n();
 	return (
-		<PopoverMenuItem href={ getDashboardUrl( site.slug ) }>
-			{ __( 'Visit Dashboard' ) }
-		</PopoverMenuItem>
+		<PopoverMenuItem href={ getDashboardUrl( site.URL ) }>{ __( 'Visit Dashboard' ) }</PopoverMenuItem>
 	);
 };
 
@@ -83,7 +83,7 @@ export default function SitesTableRow( { site }: SiteTableRowProps ) {
 					leading={
 						<a
 							style={ { display: 'block' } }
-							href={ getDashboardUrl( site.slug ) }
+							href={ getDashboardUrl( site.URL ) }
 							title={ __( 'Visit Dashboard' ) }
 						>
 							<SiteIcon siteId={ site.ID } size={ 50 } />
@@ -92,7 +92,7 @@ export default function SitesTableRow( { site }: SiteTableRowProps ) {
 					title={
 						<div style={ { display: 'flex', alignItems: 'center', marginBottom: '8px' } }>
 							<SiteName style={ { marginRight: '8px' } }>
-								<a href={ getDashboardUrl( site.slug ) } title={ __( 'Visit Dashboard' ) }>
+								<a href={ getDashboardUrl( site.URL ) } title={ __( 'Visit Dashboard' ) }>
 									{ site.name ? site.name : __( '(No Site Title)' ) }
 								</a>
 							</SiteName>
```

Ideas?

**Comment by danielbachhuber** [comment]
> 2. We can call `urlToSlug` directly to generate the slug.

I put together an improved version of this approach with #65736

I think it's appropriate for the hydration to live in `useSiteExcerptsQuery` (instead of `getDashboardUrl`) because `SiteExcerptData` is expected to return a `slug` on the object.

**Comment by danielbachhuber** [comment]
Closing in favor of #65767 for the remaining link issues.
