### ISSUE TITLE
CSS upgrade isn't removed after downgrade from atomic plan

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#65498]
### Quick summary

Came across a case here where the CSS upgrade wasn't removed after the pro plan was cancelled and site reverted: p1657582838702019-slack-C03TY6J1A

Discussed with @jmdodd here: p1657620528009779-slack-C036E4KFP2L
Key points:
- no check to see if it actually deleted the option: (see links to code in thread above)
- This probably needs to be retroactively fixed for any sites that had a bundle that included css and didn't undergo a lossless import

Conclusion was that :

1. Site purchases Custom CSS upgrade while Simple.
2. Upgrade is stored in blog option .
3. Site goes Atomic. Upgrade is still in archived Simple tables blog option.
4. On Atomic, upgrade is controlled by purchases so it continues working.
5. Plan is removed. Option is removed (if it even exists) from Jetpack cache tables (while the site is still Atomic), not from Simple tables.
6. Site reverts; Simple tables become primary again.
7. Option is still present in Simple tables.

This seems to not be an issue when a lossless import happens though (by my testing)
- also seems to happen for any atomic plan

### Steps to reproduce

I tried to replicate this by:
1. adding pro to a site that had never had a plan
2. adding custom css
3. going atomic
4. adding more css
5. cancelling the plan from the user dash 
Result: no access to css

1. Readded pro plan to same site
2. re-transferred to atomic
3. cancelled sub from SA
4. css access immediately went away (even before reverting)
5. reverted with no lossless import
6. CSS available again because simple table with option was restored
Result: access to css

### What you expected to happen

CSS upgrade should depend on a feature check not a plan > this way it's always removed regardless of simple/atomic

### What actually happened

Seems like in this case it wasn't removed, because it's still checking the plan?

### Context

5363754-zd-woothemes

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

Add and remove the Custom Design upgrade from SA.

**Comment by michaeldcain** [comment]
From planning:

If we switch this to use WPcom_Feature (?) gating, then we won't need to deal with the outdated options. After we fix this, let's open an issue to track an enhancement that nudges the CSS Add-on for users that had access via a plan and now no longer do.

**Comment by Robertght** [comment]
I've updated the Workaround details for now:

>Add and remove the Custom Design upgrade from SA.

**Comment by martian77** [comment]
I think D85282-code changes this to a feature check - still working on testing.

**Comment by martian77** [comment]
Ok, I'm struggling to test the flow of events listed above via sandbox. This diff removes the reliance on the database option, so should fix it, and I think it'll be much easier to test after merging!

D85282-code

**Comment by martian77** [comment]
Out of time before AFK. I tried to rush improving the tests and made some linting errors that I don't have time to fix!

**Comment by martian77** [comment]
Fixed the linting errors, added a dataprovider to test different product purchases, tidied up some disused code. Hopefully should be good to go. D85282-code

**Comment by sirbrillig** [comment]
Looks like a good fix!
