### ISSUE TITLE
Premium Theme: Cultivate

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#65496]
The Cultivate premium theme needs the following:

* [x] Headstart annotations (don't forget to submit for translation)
* [x] Demo site creation
* [x] GlotPress Project creation
* [x] Launch process

Cheat sheet: paYKcK-1Pt-p2 

Premium theme launch guide: PNEWy-eBM-p2

Slack request: p1657517600657999-slack-C0Q664T29

**Comment by alaczek** [comment]
Thanks, Caroline! For the record, this theme needs all the steps listed here: paYKcK-1Pt-p2 :)

**Comment by sixhours** [comment]
> Thanks, Caroline! For the record, this theme needs all the steps listed here

Ahh, so it's not quite launch ready, gotcha. 👍

**Comment by alaczek** [comment]
Hi all! It's been a little while - are there any blockers to launching this one?

**Comment by valterlorran** [comment]
Hey @alaczek, yes! I started working on the problem you mentioned, D84560-code#1769561. I just finished the diff to fix it: D85195-code

**Comment by sixhours** [comment]
Added GlotPress project and pot file diff in D85744-code

**Comment by valterlorran** [comment]
Waiting the translations to launch the theme p1660152713374689-slack-C02AED43D

**Comment by alaczek** [comment]
Normally we don't wait for that, it's enough that you run the command to send for translation.

**Comment by valterlorran** [comment]
Hey, I'm working on launching it today p1660574013916319-slack-C0117V2PCAE

**Comment by valterlorran** [comment]
I'm still facing some problems launching it. The discussion is here: p1660669607362549-slack-C0117V2PCAE

**Comment by valterlorran** [comment]
Cultivate was launched yesterday.
