### ISSUE TITLE
Enhancement: Option to override currency during signup

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#6550]
We currently don't have a way to override the currency during signup - besides using a VPN to change location which isn't quick and easy. 

For testing and development purposes it would be much easier to have a way in calypso to override the currency. 

This could be done in a number of ways, for example:
- via query string
- via browser cookie
- via localstorage value

This should work for non-logged in users, that is users coming through Signup/NUX. Logged in users currently have a currency set for their account, this could optionally override that?

**Comment by alisterscott** [comment]
@bisko raised this here as an enhancement

**Comment by alisterscott** [comment]
Still not supported

**Comment by alisterscott** [comment]
Some groundwork being done on this: `T578-code`

**Comment by yoavf** [comment]
@alisterscott For testing purposes, it is possible to override the currency using a browser cookie: `landingpage_currency`

**Comment by alisterscott** [comment]
Closing as this is resolved 👍
