### ISSUE TITLE
[Bug]: page template on scheduled post leads to publishing before scheduled date

### ISSUE THREAD

**Issue by tellyworth** [Automattic/wp-calypso#65511]
### Quick summary

In a nutshell: creating a template from a future scheduled post seems to cause two problems:

1. An error message and apparent "stuck" state when attempting to schedule the post.
2. (High priority) The post is published immediately even though the scheduled date is in the future and the UI indicades the post has not been published yet.

This happened on my personal dotcom blog, I'll use live example links.

### Steps to reproduce

1. Start on https://wordpress.com/post/flightpath.blog
2. Click "publish immediately" and the scheduled date to a month in the future.
3. Add an empty image block to the post.
4. Click "template none"
5. Click the button to create a new template. 
6. Call it "test template" and click Create.
7. Click the "Back" link in the editor UI to return to the post.
8. Add some test content to the post.
9. Click Schedule, then Schedule again to confirm that you want to schedule the future post.

### What you expected to happen

The post should be scheduled for 1 month in the future.

### What actually happened

Several incorrect behaviours:

1. An error message appears, "Scheduling failed. Invalid parameter(s): template".
<img width="1508" alt="Screen Shot 2022-07-13 at 11 15 02 am" src="https://user-images.githubusercontent.com/7200686/178628620-59dc0c6f-36c8-4050-a710-715144e3d688.png">

2. The post was published, even though it's well before the schedule date. In my case it was published at https://flightpath.blog/2022/07/13/sweet-spring-deals/. Notice that the screenshot says "Publish: July 25", but the permalink is July 13 (today).

3. Attempting to re-save the post by clicking Schedule again gives the same error.

4. It's now impossible to remove the "test template" from the post. If I click on the template selector link again there is no way to select "no template". The X button simply closes the modal.
<img width="321" alt="Screen Shot 2022-07-13 at 11 30 59 am" src="https://user-images.githubusercontent.com/7200686/178629287-aa8a8135-3db5-40af-a006-fc6bea15202d.png">

I'm leaving the prematurely published post up for now.

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

I haven't yet tried reproducing this on a test site. I think the steps to repro should be detailed enough.

### Reproducibility

Once

### Severity

Some (< 50%)

**Comment by adelineyaw** [comment]
User report: 38948245-hc - in this instance, scheduled blog post for 16:10 ended up being published earlier at 11:10am.

**Comment by pauljacobson** [comment]
Just adding a note here that there may be a related issue here: #https://github.com/Automattic/wp-calypso/issues/71529

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on P2 - Could Not Replicate 
- Tested on Simple - Could Not Replicate 
- Tested on AT - Could Not Replicate 
- Tested on Self-hosted - Could Not Replicate 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm unable to replicate this with Blank canvas on simple and business.
- I tested with the theme on the OP's blog, and the template option doesn't appear for posts
- When creating a new template from the editor's right side, without touching the scheduling options, the issue of not being able to change the template still happens, with pages and posts,(Separate bug filed for this https://github.com/Automattic/wp-calypso/issues/73579 )

📌 ACTIONS
- Await author feedback

📌 Message to Author
@tellyworth Can you share more details, specifically:

- Which theme were you using at the time of testing(your current theme is 2021, which doesn't seem to show a template option for posts)
- Have you been able to replicate on a test site?
Thanks!

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Closing report due to stale conversation and inability to reproduce. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
