### ISSUE TITLE
Activity Panel: Empty column appearing on right side of WooCommerce product pages.

### ISSUE THREAD

**Issue by rakshitwesley** [Automattic/wp-calypso#65522]
### Quick summary

WooCommerce product pages display an empty column on the right side. This only happens when SSO is disabled. 
![download](https://user-images.githubusercontent.com/95758851/178689063-f3b8259a-c831-477e-9203-9950af9976f2.png)
.

### Steps to reproduce

1. Navigate to WooCommerce products page (wp-admin/edit.php?post_type=product) or product editor

### What you expected to happen

Complete page to be displayed.

### What actually happened

An empty column appeared on the right side. Blocking the "Update" button on the orders page.
![download](https://user-images.githubusercontent.com/95758851/178716624-cbbb80bb-f9ec-449e-aedb-b593fce29f5b.png)

### Context

This only seems to appear when SSO is disabled. Enabling SSO seems to fix the issue.

https://user-images.githubusercontent.com/95758851/178691145-fa57005a-f16e-432f-9088-4f00ae933ac5.mov

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Enable SSO. But this might cause issues with sites where visitors are expected to login.

**Comment by rakshitwesley** [comment]
Reported here: 36055022-hc

- [x] 5370848-zd-woothemes

**Comment by rakshitwesley** [comment]
36054494-hc

- [x] 5370741-zd-woothemes

**Comment by neilmccreadie** [comment]
Another instance in 36055657-hc,  toggling SSO resolved this.

**Comment by rakshitwesley** [comment]
5375411-zd-woothemes

**Comment by Gustavo-Hilario** [comment]
- [x] Another report here 5375411-zen. Suggested enabling SSO.

**Comment by JessBoctor** [comment]
I had a report of this in 4698240-HC. Activated SSO for the customer.

**Comment by danielk-am** [comment]
Another report of this at 36023195-hc. Membership website. SSO has to be off.

**Comment by ajaykj** [comment]
Another report of this in 36074614-hc.

- [x] [5380778](5380778-zen)

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple - no
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Pinging here p1657874078342039-slack-C02FMH4G8 as I could replicate it with .com sites only.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by druesome** [comment]
Just wanted to add that the issue is related to this PR:

https://github.com/woocommerce/woocommerce-admin/issues/7035

Specifically when this CSS:
```
.woocommerce-layout__header { width: calc( 100% - 160px); }
```
was changed to 
```
.woocommerce-layout__header { width: calc( 100% - 272px); }
```

**Comment by synora** [comment]
Another report at 5381371-zen but SSO is on for the user.

**Comment by lupus2k** [comment]
I commented @druesome [here](https://github.com/Automattic/wp-calypso/issues/65522#issuecomment-1185342505), the problem came from [this file](https://github.com/Automattic/wc-calypso-bridge/blob/master/store-on-wpcom/assets/css/admin/nav-unification.css).

Changing this:
```
	.jetpack-connected .woocommerce-layout__header {
		width: calc( 100% - 272px );
	}
```
to this:
```
	.jetpack-connected.is-nav-unification .woocommerce-layout__header {
		width: calc( 100% - 272px );
	}
```
Should fix the problem.

**Comment by moon0326** [comment]
Thank you, everyone! 

The fix is included in [wpcomsh 2.5.0](https://github.com/Automattic/wpcomsh/releases/tag/v2.9.50), and it'll be released as soon as possible.

**Comment by moon0326** [comment]
Thank you, everyone!

The fix is included in wpcomsh 2.9.50 and we'll release it as soon as possible.

Update: The fix has been deployed.

**Comment by hacchism** [comment]
Another report in 36081415-hc after the comment @moon0326 above. SSO is on for the user.

- [x] 5386532-zen

**Comment by moon0326** [comment]
> Another report in 36081415-hc after the comment @moon0326 above. SSO is on for the user.
> 
> * [x]  5386532-zen

✋ 

I've left a comment on the issue.

**Comment by hacchism** [comment]
> I've left a comment on the issue.

Thanks @moon0326✨ I checked your comment on the ticket but adding the CSS code in `Appearance -> Additional CSS` wouldn't help as the issue is not on the front-end. For now, I'm going to suggest deactivating the problematic plugin👍

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by csabarakasz** [comment]
A user reported the same issue. Report: 34773636-hc

SSO is on. Clearing browser cache didn't help.

It seems like the .woocommerce-layout__activity-panel-wrapper class' `height: calc(100vh - 92px);` value is causing the issue. 

- [ ] followup ticket: 5389565-zd-woothemes

**Comment by vajrasar** [comment]
> A user reported the same issue. Report: 34773636-hc
> 
> SSO is on. Clearing browser cache didn't help.
> 
> It seems like the .woocommerce-layout__activity-panel-wrapper class' `height: calc(100vh - 92px);` value is causing the issue.
> 
> * [ ]  followup ticket: 5389565-zd-woothemes

cc @moon0326

**Comment by moon0326** [comment]
> > A user reported the same issue. Report: 34773636-hc
> > SSO is on. Clearing browser cache didn't help.
> > It seems like the .woocommerce-layout__activity-panel-wrapper class' `height: calc(100vh - 92px);` value is causing the issue.
> > 
> > * [ ]   followup ticket: 5389565-zd-woothemes
> 
> cc @moon0326

Hi ✋ 

I've left a comment on the ticket. ~I'm not sure if there was a change, but I wasn't able to reproduce.~ I was able to reproduce it by collapsing the sidebar. I've left another comment with a workaround for now. I'll release a new fix tomorrow.

**Comment by moon0326** [comment]
> > I've left a comment on the issue.
> 
> Thanks @moon0326✨ I checked your comment on the ticket but adding the CSS code in `Appearance -> Additional CSS` wouldn't help as the issue is not on the front-end. For now, I'm going to suggest deactivating the problematic plugin👍

Thank you! In that case, we can suggest plugins such as https://wordpress.org/plugins/admin-css-mu/ to apply custom styles to the admin area.

**Comment by thekingsprojects** [comment]
> Another report at 5381371-zen but SSO is on for the user.

This same user wrote back saying that the issue is still happening for them, and I've confirmed the issue is still present.

For now I've let them know a fix is coming, and suggested that they click the Activity button to expand the panel if they need to access the right edge of the screen.

- [ ] Follow-up: 5381371-zen

**Comment by moon0326** [comment]
> * 5381371-zen

Thank you. The user can also expand the sidebar as a workaround. That might be easier.
![Screen Shot 2022-07-16 at 4 54 39 PM](https://user-images.githubusercontent.com/4723145/179375427-a87a8ad3-8d06-47b5-9dd2-fae2e374a85f.jpg)

**Comment by csabarakasz** [comment]
- [ ] 5389565-zd-woothemes
Suggested the collapse menu workaround for now!

Thank you!

**Comment by tavilla61** [comment]
Another instance today, #5621550-zen

The collapse-menu option helped, but it isn't working as well as they would like.

**Comment by wpshellbelle** [comment]
Hi @moon0326!

This issue seems present still. 

A workaround is hard to implement. SSO is enabled. See:

https://{domainhere}/wp-admin/edit.php?post_type=product

<img width="1644" alt="Screen Shot 2023-02-15 at 1 08 23 PM" src="https://user-images.githubusercontent.com/77413972/219119868-a73318c3-b7e3-4dd0-b86e-df5f0c929771.png">



User report: 40088522-hc / 5961660-zen

I recommended some CSS using: 

https://wordpress.com/plugins/admin-css-mu

**Comment by moon0326** [comment]
> Hi @moon0326!
> 
> This issue seems present still.
> 
> A workaround is hard to implement. SSO is enabled. See:
> 
> https://{domainhere}/wp-admin/edit.php?post_type=product
> 
> <img alt="Screen Shot 2023-02-15 at 1 08 23 PM" width="1644" src="https://user-images.githubusercontent.com/77413972/219119868-a73318c3-b7e3-4dd0-b86e-df5f0c929771.png">
> 
> User report: 40088522-hc / 5961660-zen
> 
> I recommended some CSS using:
> 
> https://wordpress.com/plugins/admin-css-mu

Thank you for the report. I'll look into.

Hey @ilyasfoo, could you look at it as a porter when you get a chance?

I've tested it with new ECOM and business sites, but I couldn't reproduce it. The navigation (enabled via settings -> features) is disabled by default on a new site. I think it only happens on some old sites with the new navigation enabled. I'll look into it later this week if you don't get to chance to look at it.

**Comment by hngdny** [comment]
One example of this here 38559627-hc

Workaround: Resize browser window to reduce width

**Comment by ilyasfoo** [comment]
> Hey @ilyasfoo, could you look at it as a porter when you get a chance?

Hey, @moon0326. I was able to reproduce it by going to `wp-admin/options.php` and manually setting the value for `woocommerce_navigation_enabled` option to `yes` in an ecommerce site.

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/3747241/219250618-4a64dda9-292d-4687-af16-bcd3cd6c29e7.png">

I've created a fix PR here: https://github.com/Automattic/wc-calypso-bridge/pull/952

**Comment by kaushikasomaiya** [comment]
38536778-hc

This was appearing on all Woo admin pages - disabling the new navigation experience fixed the issue.

**Comment by rakshitwesley** [comment]
Reported here: 39649944-hc

User wants to be notified when this issue is resolved: 5963650-zd-woothemes

**Comment by ariel-maidana** [comment]
Another report: 5963867-zd-woothemes

**Comment by ilyasfoo** [comment]
I've deployed a fix, but we'll need to wait until atomic picks it up. I'll keep you posted

**Comment by ariel-maidana** [comment]
5964118-zd-woothemes

**Comment by stuartduff** [comment]
Another report from the Orders screen 5962616-zen

**Comment by poeticabdul** [comment]
Another report 5964024-zen

**Comment by ilyasfoo** [comment]
The fix is deployed. Please reopen if users still observe the issue

**Comment by ilyasfoo** [comment]
There a regression when navigation is collapsed and site is using non-RTL language, incoming fix: https://github.com/Automattic/wc-calypso-bridge/pull/1535
