### ISSUE TITLE
Cutoff when Adding Menu on Navigation block with "always" Overlay Menu

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#65526]
### Quick summary

With "Always" setting on overlay menu under navigation block, the popup to insert link is hidden or cutoff to the left.

- [ ] 5369973-zd-woothemes

### Steps to reproduce

1. On Site Editor or Page, add a navigation block
2. Set "Overlay menu" on navigation block as "always"
3. Click on the hamburger icon on navigation block to view menu
4. Click 'plus' icon to insert new menu item

### What you expected to happen

Behaviour would be similar when adding a new menu item without overlay menu option

### What actually happened

Result:

![image](https://user-images.githubusercontent.com/34882260/178698953-c59cf419-cef6-48e7-b74f-0b8efbee52a7.png)

With list view expanded:

![image](https://user-images.githubusercontent.com/34882260/178699396-61c318f8-c144-4b0e-9ce4-ce5aacea15c4.png)

### Context

Also a separate issue: Expanding list view on page covers the overlay menu items on navigation

![image](https://d.pr/i/vO4bpe+)

Gif: https://d.pr/i/vO4bpe

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Switch overlay setting on navigation block to "mobile" or "off".

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I noticed a general inconsistency with this and other blocks as well. Seems to be an issue with other blocks as well but it's edge cases.

@annezazu do you know if this would fall into any ongoing PRs? 


📌 ACTIONS
- On-hold for now

📌 Message to Author
 - For the other issue could you open another report @edwinho89 ?

**Comment by edwinho89** [comment]
> * For the other issue could you open another report @edwinho89 ?

Created https://github.com/Automattic/wp-calypso/issues/65667 !

**Comment by annezazu** [comment]
>@annezazu do you know if this would fall into any ongoing PRs?

@Robertght thanks for tagging me in 🤠 I think this most closely overlaps (get it) with this issue: https://github.com/WordPress/gutenberg/issues/40382 and this work in progress PR: https://github.com/WordPress/gutenberg/pull/40625
