### ISSUE TITLE
Plugin installation via 'set up marketing tools' fails

### ISSUE THREAD

**Issue by janmckell** [Automattic/wp-calypso#65528]
### Quick summary

Going through the WooCommerce setup asks if we want to install plugins, via 'Set up marketing tools', like MailPoet, but then says we’re not allowed to manage plugins, once we click into it.

### Steps to reproduce

1. Started at WooCommerce option (in WP dashboard)
2. Began quick WooCommerce install flow
3. When clicking on 'set up marketing tools', I'm taken to a screen that recommends marketing extensions, but then I cannot install, re: MailPoet, for example.

### What you expected to happen

I'd be able to install a marketing extension.

### What actually happened

I was unable to make the purchase, since an error message popped up at the bottom of the screen, indicating that I could not install the plugin.

![Markup on 2022-07-13 at 05:29:43](https://user-images.githubusercontent.com/84089207/178700995-b922752c-142b-4143-a6a1-67c97b447c43.png)

### Browser

Mozilla Firefox

### Reproducibility

Once

**Comment by cpapazoglou** [comment]
@ianstewart it seems that WooCommerce is very dependant on other plugins. I can think of 2 different solutions:

- Hide sections that lead to installing non-marketplace plugins
- Change the messaging, including "Installing free plugins is available only in X, Y plans. Click here to upgrade."

**Comment by cpapazoglou** [comment]
Same happens with the onboarding flow and when trying to buy - install through WC.com
<img width="1371" alt="CleanShot 2022-07-28 at 13 13 20@2x" src="https://user-images.githubusercontent.com/12430020/181481487-1273271e-ae0e-4ace-b4b0-7ccfde2747e7.png">

<img width="1118" alt="CleanShot 2022-07-28 at 13 16 03@2x" src="https://user-images.githubusercontent.com/12430020/181482017-ba4ddc92-10f2-495e-b003-c2c9636046f9.png">

I believe the best course of action here is to update the code making sure that user has permissions to install plugins before suggesting so. @bgrgicak can you point us to the teams that could handle this in woocommerce and WC.com?

**Comment by bgrgicak** [comment]
> @bgrgicak can you point us to the teams that could handle this in woocommerce and WC.com?

Team Alpha is responsible for the auto-install flow in Woo and on WCCOM.

**Comment by cpapazoglou** [comment]
Created a P2 p6JqRr-6Zk-p2 to discuss further.

**Comment by cuemarie** [comment]
Adding to Dotcom Bug Prioritization Board > `ON HOLD`, as the work around WooCommerce on lower tier plans is paused for now.

Installing plugins from the Woo setup flow **on an AT site** still [works as expected](https://user-images.githubusercontent.com/27249804/236029288-e40287c9-e353-48b6-8346-1377a7322458.mp4)

**Comment by cpapazoglou** [comment]
Closing this as it's not applicable anymore. We don't allow any plugin or `woocommerce` in lower plans.
