### ISSUE TITLE
[New Liked Comment] Update template layout

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65538]
### Context
The New Liked Comment template should be updated on top of the initial version `wpcom-notifications/html/comment-like.php`. The visual changes are listed below and the styling details are available in Figma.

**Figma reference:** c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A21504

#### Existing layout (production)
<img width="442" alt="image" src="https://user-images.githubusercontent.com/3113712/180325979-5fa24fed-577f-4f14-856a-3a772f26f5b0.png">

#### Implemented layout
<img width="625" alt="Screen Shot 2022-07-21 at 19 35 28" src="https://user-images.githubusercontent.com/3113712/180329520-fe1020d6-2b90-4393-b43e-6527e210668d.png">

#### New layout
<img width="613" alt="Screen Shot 2022-07-21 at 20 04 52" src="https://user-images.githubusercontent.com/3113712/180329596-0f413af2-a9fd-4332-963f-23c0281e86f2.png">

#### [1] Display site title in the header
- Should remove the **"New like on"** copy from the header → `template-header` file

#### [2] Display New Like heading
- Should display the New Like! heading in the template body → `comment-like` file
- Text style (more details on Figma):
    - Weight: 900
    - Size: 40px
    - Line height: 48px

#### [3] Update Liker heading
- Should be a single line text
- Text style (more details on Figma):
    - Weight: 400
    - Size: 16px
    - Line height: 24px
- Alignment with the picture:
    - On desktop, vertically centered
    - On mobile, top aligned
- The copy has the following structure: "{user} just liked your comment on {post_title}."
- If the post has no title the copy should look like "{user} liked your comment."

#### [4] Remove View Post button
- Should remove the **View Post** button from the already implemented code → `comment-like` file
- The View Post button isn't used in the production version (old layout)

#### ~~[5] Display "You might want to go see... their blog" link~~
- ~~Should display a link to the Liker's blog, using the sentence below:~~
    - ~~"You might want to go see what they’re up to! Perhaps you will like _their blog_ as much as they liked yours."~~
- ~~The "their blog" should be a link to the liker's blog~~
- ~~Do not display this copy if the liker has no public blog/site~~
- Moved to #65937

#### [6] Update Unsubscribe footer
- Should update the Unsubscribe footer to display "**Want less email?** Modify your _email notification settings_."
- The "email notification settings" should be a link to the subscription management

####  [7] Display "Trouble clicking?" footer
- Should display the copy below for trouble clicking:
    - "Trouble clicking? Copy and paste this URL into your browser: 
{url}"
- This template already exists on `template-footer-url` file and can be reused 

### Quality Check
- [ ] Validate layout on desktop screens
- [ ] Validate layout on mobile screens
- [ ] Validate accessibility aspects
- [ ] Verify localization support

### 🔴 Out of Scope
- Add Great Posts area → #65472
- Update footer layout → #65710

**Comment by ivan-ottinger** [comment]
D84748-code patch is now deployed to production. Changeset: r249876-wpcom.
