### ISSUE TITLE
[New Liked Comment] Update email subject

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65541]
### Context
**Email Templates I2** project will provide a visual refresh to Like and Comment emails. This task proposes to update the subject on New Like on a Comment emails to the following format: 

**[`{SITE_NAME}`] `{USER}` liked your comment on `{POST_TITLE}`**

Layout reference: c5bt2O2vWhTlhSREC89Bw2-fi-2169%3A12886

**Comment by mashikag** [comment]
The current titles for the email are as follow.

If post has no title:
[{SiteName}] {LikerName} liked one of your comments

Else if post has a title:
[{SiteName}] {LikerName} liked your comment on "{PostName}"

This means that the difference here is the missing quotation marks `"` around PostName. 

Waiting for response on figma.

**Comment by phcp** [comment]
As Saygun mentioned in Figma, let's keep the subject as it is, so no additional work is required. We could either delete or move the task to done. @mashikag any preference when it comes to the board management?

**Comment by mashikag** [comment]
I would much prefer to have it just closed. It is good to keep it for future reference. 🙂

**Comment by mashikag** [comment]
Closing this issue as the current subject implementation is satisfactory. Hence no work required.
