### ISSUE TITLE
Theme/Plugin Bundling: Data file to map plugins to stepper steps

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#65556]
Related to #65100

We need to have a data file in the stepper which contains a mapping of plugin slugs and the stepper steps needed to go through for each plugin. 

For example
```
{
	"woocommerce": [
		"storeAddress",
		"businessInfo",
		"wooConfirm",
		"processing"
	]
}
```

**Comment by mreishus** [comment]
Would this be used in the new flow `plugin-bundle-flow` ( #65557 ) to determine the result of the useSteps() function?

**Comment by markbiek** [comment]
> Would this be used in the new flow `plugin-bundle-flow` ( #65557 ) to determine the result of the useSteps() function?

@mreishus Yes, that's correct!  Open to any suggestions you may have.
