### ISSUE TITLE
Theme/Plugin Bundling: Verify new taxonomy is present in the theme detail API

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#65555]
Related to #65100

After #65553 is complete, we need to verify that the new taxonomy is included in API calls to get the theme details. If it's not present, we'll need to update the API call to include it.

**Comment by mreishus** [comment]
With D85956-code applied, I added the `test-plugin` plugin to the baxter theme.

### Individual Theme Details

Now when I check 1.2 `/themes/baxter`, I see it in the results, inside the taxonomy key:
![2022-08-15_14-52](https://user-images.githubusercontent.com/937354/184707460-456139e7-b3c5-42e1-9e3b-01c0fac4dab3.png)

### Theme List

I also see it on the general theme list:
![2022-08-15_14-54](https://user-images.githubusercontent.com/937354/184707783-88f91b92-1fbe-479f-88c2-e4ff24cac696.png)

**Comment by mreishus** [comment]
With D85956-code deployed, I'm seeing the results in the API calls as described above. I assume this is sufficient.

**Comment by mreishus** [comment]
I'm now working on making sure this information is present inside `site-setup-flow.ts`, so it can correctly hand off to the new flow.

**Comment by mreishus** [comment]
We need the information to be available in `/sites/<SITE>/themes/mine`.
There are three ways to get themes:
* (1) Individual theme details
* (2) Theme search
* (3) Details of the theme I am currently using

Taxonomies were added to (1) and (2), but not (3). In #66780, I'm using (3) to get the details of the current theme (it only seems natural), but taxonomies are not included.  So I either need to modify (3) to include taxonomy information, or change the frontend to use (3) to figure out which theme is being used, then offer an additional request to (1).

Some references
-----------------------
D7407-code
pNEWy-9OC-p2
commit ffe8703b from 29-Sep-2017 - Phab diff strangely not included in commit message

**Comment by mreishus** [comment]
Created D86303-code
