### ISSUE TITLE
Theme/Plugin Bundling: Add plugins taxonomy to the theme showcase

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#65553]
Related to #65100

In order to store a theme's bundled plugins, we're going to add a new "plugins" taxonomy to the theme showcase.

Any themes with associated plugins can have a new term added to them with the plugin slug. For the initial implementation, most themes will likely have only a single plugin term and that term will be “woo-commerce”.

We also need to make sure that the terms can be ordered. This ensures that, if there are multiple plugins, they get installed in the correct order. For example, if we have a theme that bundles WooCommerce and several WooCommerce extensions, the term ordering ensures that WooCommerce gets installed first.

The format of the taxonomy could be a simple array of plugin slugs or something like
```
[
	'woocommerce-bookings' => 'WooCommerce Bookings'
]
```

See 12685-gh-Automattic/woocommerce.com for discussion which format to use.

**Comment by markbiek** [comment]
If we take the approach of modifying `/atomic/transfers` as described by @obenland on paYKcK-1R4-p2, we don't have to worry about the order of the plugins in the taxonomy. 

The Atomic API will automatically handle installing everything in the correct order.

**Comment by obenland** [comment]
> The Atomic API will automatically handle installing everything in the correct order.

I don't know exactly how it works, but I imagine it activates these plugins through WP CLI, never triggering a request that would care about the order plugins are installed/activated in.

But yes, the order of plugins should not be a concern.

**Comment by mreishus** [comment]
Examples of currently existing theme taxonomies: pd2qbF-az-p2#comment-215

**Comment by mreishus** [comment]
This might be where the theme taxonomies are defined: 2d2a3-pb line 78

**Comment by mreishus** [comment]
Prospective patch in D85956-code

**Comment by mreishus** [comment]
Deployed D85956-code. I believe this solves the issue, but if it's not sufficient, we can re-open.

**Comment by markbiek** [comment]
> Deployed D85956-code. I believe this solves the issue, but if it's not sufficient, we can re-open.

I think that should cover it. The only potential change I see is if we _can't_ leverage the Atomic API's ability to handle plugin install. In that case, we'd need to add an "Install Order" field as part of the new taxonomy so we can manual specify the order plugins will be installed.
