### ISSUE TITLE
Theme/Plugin Bundling: Create themeInstallation step

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#65559]
Related to #65100

Similar to the existing `processing` step, this theme will install the specified plugin in the background. TDB if this new step will be called _before_ moving into installing bundled plugins or if it will happen at the end of the process.

**Comment by markbiek** [comment]
This may not be necessary if we can modify `/atomic/transfers` as described by @obenland on paYKcK-1R4-p2.

**Comment by obenland** [comment]
Yes, this can be skipped and folded into the step that kicks of the Atomic transfer

**Comment by markbiek** [comment]
Closing this since it's not necessary.
