### ISSUE TITLE
Theme Subscription: Gather information about the future subscriptions

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#65565]
To implement single theme subscriptions, we need to define the subscription periods and prices so that we can create the billing plans.

*Each different period translates to one new billing plan for each currency.

Related to https://github.com/Automattic/wp-calypso/issues/65133

**Comment by sixhours** [comment]
Theme pricing is here: pdgrnI-1dr-p2#comment-2386

**Comment by sixhours** [comment]
Since we have the pricing (above P2) and terms (yearly/monthly) can we close this out?

**Comment by blackjackkent** [comment]
I would say so, yes - that should be the information we need for this purpose. :)
