### ISSUE TITLE
Marketplace: Create script to sync existing woo subscriptions to wc.com

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#65563]
WooCommerce extensions purchased through the WP.com Marketplace are going to be also registered into WooCommerce.com. There is an integration #60661 that registers all the new WooCommerce subscriptions on the Marketplace.

A one time script is required to register all the existing WooCommerce extensions subscriptions created before releasing the #60661.

**Comment by JulianBustamante** [comment]
Diff created D96773-code

**Comment by JulianBustamante** [comment]
The diff is updated and functional. It is still pending of batch processing implementation.

**Comment by cpapazoglou** [comment]
> It is still pending of batch processing implementation.

You mean reviewing it and running it?

**Comment by JulianBustamante** [comment]
Deployed r260354-wpcom

**Comment by JulianBustamante** [comment]
The script was executed and all the WooCommerce plugins subscriptions on WPCOM got synced to WCCOM
