### ISSUE TITLE
Business plan still offered when upselling the Footer Credit removal

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65586]
### Quick summary

Both Simple sites and Atomic sites on a non-legacy plan (Free, Starter) are asked to upgrade to the Business plan when trying to hide the footer credit.

<img width="300" alt="Screen Shot 2022-07-14 at 10 46 17" src="https://user-images.githubusercontent.com/1233880/178942537-5829fff1-71a0-4b0d-a08e-58ffd33d5d6d.png">

They should be asked to upgrade to the Pro plan instead.

### Steps to reproduce

- Go to https://wordpress.com
- Switch to a site with a Free plan or Starter plan
- Go to Appearance > Customize > Site identity
- Under the "Footer Credit" section, select the "Hide" option

### What you expected to happen

I should be asked to upgrade to the Pro plan

### What actually happened

I'm asked to upgrade to the Business plan

### Platform (Simple, Atomic, or both?)

Simple, Atomic

**Comment by obenland** [comment]
This can probably be abandoned with the Business plan now being available again.
