### ISSUE TITLE
Research on if it's possible to skip the screen where the customer picks the Free plan

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#65585]
### Issues
After Jetpack is installed and connected, we will be brought to the Jetpack pricing page without any instructions, which is pretty confusing. Users might not know which plan they have to pick as well.
### Objective
We can consider adding the Jetpack Free plan for users by default if there's no active plan and maybe skip the Jetpack Plans page at all.
### Approach
- [x] See if there's a possibility to add a Jetpack free plan by default if there's no active plan.
- [x] Research how we can cover this for a paid plan that doesn't have a backup.

**Comment by ouikhuan** [comment]
### See if there's a possibility to add a Jetpack free plan by default if there's no active plan
As soon as we connect with a user account (click the Approve button) during the authorization step, we'll be assigned to Jetpack Free Plan by default.

###  Research how we can cover this for a paid plan that doesn't have a backup.
There's no need for a paid plan to include backup functionality to start import everything.
