### ISSUE TITLE
Premium Theme: Yuga

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#65597]
The Yuga premium theme needs the following:

* [x] Sync Yuga to WP.com (**pending Theam approval**)
* [x] Demo site creation
* [x] Theme showcase draft
* [x] Headstart annotations (don't forget to submit for translation)
* [x] GlotPress Project creation
* [x] Launch process

Cheat sheet: paYKcK-1Pt-p2 

Premium theme launch guide: PNEWy-eBM-p2

Slack request: p1657517600657999-slack-C0Q664T29

**Comment by alaczek** [comment]
I asked in Slack and the review seems to be wrapped up: p1658884368161419-slack-C029FM1EH

**Comment by valterlorran** [comment]
I was asked to put this on hold for now: p1660591229431069-slack-C0Q664T29

**Comment by alaczek** [comment]
Hey, @valterlorran I appreciate your patience! This theme is a go now for launch!

**Comment by valterlorran** [comment]
We created the headstart annotation D86476-code and the POT file D86480-code.

**Comment by iamtakashi** [comment]
@valterlorran I'm so sorry, but I need to make a last-minute change to the theme and the demo. I'll let you know here when I'm done with the change. Does that sound ok?

**Comment by iamtakashi** [comment]
> I'll let you know here when I'm done with the change.

The change is minor, and I expect to finish it by the end of today. Sorry again!

**Comment by iamtakashi** [comment]
@valterlorran, OK, I'm done with the demo, please regenerate the annotation for headstart and the POT file. Any problem, let me know. Thank you!

**Comment by valterlorran** [comment]
@iamtakashi done! :)

**Comment by iamtakashi** [comment]
Since the essential part of the demo content was exported as a Headstart annotation, I'm going to add more contents that were removed to obey the limit of an annotation.

What's left to launch?

**Comment by valterlorran** [comment]
We need a review of the headstart annotation and the POT file to proceed with the launch. D86476-code / D86480-code

**Comment by iamtakashi** [comment]
Nice, both diffs have been reviewed and landed. Thank you!

I saw @alaczek had worked on the draft for a showcase page (thanks!)  When are we looking to launch it? Can I help with something?

**Comment by valterlorran** [comment]
@iamtakashi I (soft)launched it today. For now, the theme is only available to Automatticians. I will be launching it to the public on Monday.

**Comment by iamtakashi** [comment]
@valterlorran Nice! Thank you so much for your help. I just saw the demo site, and I noticed the button in the header is too large. It seems to be a WP.com issue. 

I opened an issue. Is there any chance you can take a look at what's causing the issue?
https://github.com/Automattic/wp-calypso/issues/67428

**Comment by valterlorran** [comment]
@iamtakashi I will take a look at it today. I'll fix it before launching Yuga.

**Comment by valterlorran** [comment]
@iamtakashi I will close this issue because I launched it already. It seems that the button issue is not related to Yuga, but I'll need to investigate more. Let's keep the discussion on your issue.

**Comment by iamtakashi** [comment]
> It seems that the button issue is not related to Yuga

Yes, it's not a Yuga-specific issue. Thanks for launching the theme and also thanks for looking into the button issue.
