### ISSUE TITLE
Framework: Move components and libs to `shared/` 

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#656]
We are going to need a couple of components as well as stuff from `client/lib` for server-side rendering, some of which are fortunately already independent of the DOM/BOM, while others will need tweaking. Starting a list:

* [ ] components/data/store-connection
* [ ] components/data/screen-title
* [ ] my-sites/empty-content (related to 10207-gh-calypso-pre-oss) 

No DOM/BOM dependencies:
- [x] EmptyContent
- [x] Gridicon
- [x] lib/url
- [x] Card
- [x] Dispatcher
- [x] emitter

Themes related: 
- [x] Theme
- [x] ThemesList
- [x] ThemesListFetcher
- [x] lib/themes to shared/
- [x] my-sites/themes to shared/

Components that depend on the BOM/DOM in some way, and need to be looked at more closely (and maybe modified) when we move them:-
- [ ] interpolate-components
- [ ] lib/warn
- [ ] components/search
- [ ] SelectDropdown
- [ ] SectionNav
- [ ] StickyPanel
- [ ] InfiniteList
- [ ] lib/mixins/i18n
- [ ] viewport
- [ ] UrlSearch
- [ ] Popover
- [ ] analytics
- [ ] config

**Comment by ehg** [comment]
Closing, as we're getting rid of the `shared` directory. https://github.com/Automattic/wp-calypso/issues/1594
