### ISSUE TITLE
Sites Management Dashboard: display amount of search results for query

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#65606]
### Details

Extends https://github.com/Automattic/wp-calypso/pull/65505.

We should either update the count in the tabs or display a message alongside the search input informing the user of the number of sites that were returned according to their search.

@SaxonF, please let us know which approach is better for this case.

### Done is

- [ ] The user knows how many sites were returned from their search

**Comment by danielbachhuber** [comment]
To whomever picks this up: this issue is probably impacted by #65644, so might want to wait until that lands.

**Comment by sejas** [comment]
@zaguiini @danielbachhuber ,

I've found that the search input doesn't persist the value when changing the tabs.

Do you know if this is a good issue to add this fix?

https://user-images.githubusercontent.com/779993/179541518-199ca2c4-fdb1-486e-b94f-5cc55839bf3e.mp4

**Comment by danielbachhuber** [comment]
> I've found that the search input doesn't persist the value when changing the tabs.

@sejas Isn't this fixed by #65644?

**Comment by sejas** [comment]
In https://github.com/Automattic/wp-calypso/pull/65644 the value is persisted on the URL, but not in the text input nor in the results.

**Comment by danielbachhuber** [comment]
> In https://github.com/Automattic/wp-calypso/pull/65644 the value is persisted on the URL, but not in the text input nor in the results.

@sejas Oh, you're right. It was working for me the other day, but now it's not. I'll see about fixing that.

**Comment by danielbachhuber** [comment]
> In #65644 the value is persisted on the URL, but not in the text input nor in the results.

@sejas This is now implemented with #65732
