### ISSUE TITLE
Marketplace: install premium plugins popup close title text cut off

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#65619]
This "Close" title text is being clipped by the border of this popup.

![Screenshot_2022-07-15_13-04-08](https://user-images.githubusercontent.com/811776/179141854-2980c06e-bf4a-4564-aa79-2a1e21e9a4dc.png)

- [ ] Make sure the title text is fully visible

**Comment by cpapazoglou** [comment]
Not sure how, but this is fixed now 🙈

<img width="922" alt="CleanShot 2022-07-19 at 10 21 11@2x" src="https://user-images.githubusercontent.com/12430020/179691434-9985ddb4-4c07-4732-97fd-13b8110285f0.png">
