### ISSUE TITLE
Categories not updating 

### ISSUE THREAD

**Issue by AMcGrady** [Automattic/wp-calypso#65616]
### Quick summary

Regarding site: https://naomimoriyama.com/

Issue 1: User is unable to remove the Books category from the published post: "Love at first sight. Punkaharju Esker". It can be removed in the post editor or from the Quick Edit action in the classic view listing all posts. However once the change is updated the Books category is re-checked.

Issue 2: These 2 posts:
https://naomimoriyama.com/2022/04/10/press-kaleva-2/
https://naomimoriyama.com/2022/04/10/press-kaleva/

have had the Books category successfully removed but they are still showing up on the live site's Books category page:
https://naomimoriyama.com/category/books/

### Steps to reproduce

Issue 1:
1. Go the the user dashboard. 
2. Go to the editor for post "Love at first sight. Punkaharju Esker":
https://naomimoriyama.com/wp-admin/post.php?post=590&action=edit
3. Remove the Books Category and Update the page.

Issue 2:
1. Go to site https://naomimoriyama.com/
2. Click on Books in the menu to go to:
https://naomimoriyama.com/category/books/

### What you expected to happen

Issue 1: I expected the Books Category to be removed from the post.

Issue 2: Expect not to see posts Lehdistö: KALEVA and Press: Kaleva on the Books Category page.

### What actually happened

Issue 1: The Books Category is not removed.

Issue 2: The posts do show up on the Books category page even though they no longer have the Books category.

### Platform (Simple, Atomic, or both?)

Atomic

**Comment by JoshuaGoode** [comment]
Hi @AMcGrady 

Feel free to reach out internally, to at-help, about things like this. Or post on the internal requests P2. We 

This can be fixed:

p9F6qB-9s1-p2#comment-47301

**Comment by Robertght** [comment]
I have applied that fix for now, and I'm closing this one.

cc @AMcGrady 

LE: Made the author aware of Buggomatic and how to escalate things in the future.
