### ISSUE TITLE
Plugin Details: Sidebar actions

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#65611]
Implement the sidebar actions similar to the SiteList component:

- [ ] Activate button
- [ ] Deactivate button
- [ ] Autoupdate toggle
- [ ] Menu to other actions (delete, etc)

The actions should be the same as in #63888

![Image](https://user-images.githubusercontent.com/5039531/179050654-f6bcb11b-8c5e-44f1-84d8-6d0b203a377c.png)

![Image](https://user-images.githubusercontent.com/5039531/179050726-f5cd0a18-5ef9-4421-be0d-de7bd546fc4e.png)

Epic Issue: https://github.com/Automattic/wp-calypso/issues/43332
P2: pdh6GB-sk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi

**Comment by cpapazoglou** [comment]
Is this a duplicate https://github.com/Automattic/wp-calypso/issues/63887?

**Comment by WBerredo** [comment]
Yes, and its better described as well :)

I'll close both after the merge of the PR.
