### ISSUE TITLE
[Bug]: Possible to delete certain dotcom marketplace plugins

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#65634]
### Quick summary

dotcom marketplace plugins are blocked from being deleted, this is because once deleted, purchasers can't reinstall them without renewing.

This only affects pro, business and ecommerce plans - other plans don't have the manage plugins capability.

The mechanism that prevents deletion [0] doesn't work for the minority of plugins which have differing plugin slugs and store slugs. This is because the logic relies on the product slug starting with the plugin slug. This isn't always the case for plugins with long slugs, due to limitation in the wpcom store [1]. The approach we've been taking in other parts of the system is to change the logic to compare to the correct thing - store_products.billing_product_slug for marketplace products. 

[0] See `wpcomsh_managed_plugins_action_links` in wpcomsh

[1] pdh6GB-Pq-p2

### Steps to reproduce

1. Find WooCommerce Product CSV Import Suite in the [dotcom marketplace](https://wordpress.com/plugins)
2. Purchase and install it to a site on the pro plan
3. Go to /wp-admin/plugins.php
4. Deactivate WooCommerce Product CSV Import Suite

### What you expected to happen

The plugin to be deactivated, with no delete link displayed

### What actually happened

The plugin was deactivated but also displayed a delete link, clicking the link deleted the plugin.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, difficult to implement

### Workaround details

1. Buy/renew the plugin via Calypso again
2. Ask a HE to reinstall the plugin (P9HQHe-18l-p2) so it can be activated again from the UI
3. Remove subscription from Store Admin and add it again

**Comment by cpapazoglou** [comment]
This check is happening in `wpcomsh.php#L383`

**Comment by dsas** [comment]
This has been discussed here: p1657798282113709/1657791814.481889-slack-CJS75TX3R. To summarise, maybe we can install something in atomic metadata, or record the slugs in a new APD (most likely).

**Comment by mmtr** [comment]
I had one thought yesterday: what if we allow marketplace plugins to be reinstalled from Calypso if they have been purchased? That way we wouldn’t need to hide the delete link and thus we won’t need to maintain any marketplace plugins catalog data in wpcomsh, right?

**Comment by rcrdortiz** [comment]
> I had one thought yesterday: what if we allow marketplace plugins to be reinstalled from Calypso if they have been purchased? That way we wouldn’t need to hide the delete link and thus we won’t need to maintain any marketplace plugins catalog data in wpcomsh, right?

It could work yes. I have some questions not meant to challenge your hypothesis, it's simply things unknown to me. Does the FE store the purchases made by the user? Are they stored in calypso_store or somewhere else?

**Comment by mmtr** [comment]
> Does the FE store the purchases made by the user? Are they stored in calypso_store or somewhere else?

Yes, we use this component to fetch them: https://github.com/Automattic/wp-calypso/tree/trunk/client/components/data/query-site-purchases

**Comment by mmtr** [comment]
> what if we allow marketplace plugins to be reinstalled from Calypso if they have been purchased?

I explored this in https://github.com/Automattic/wp-calypso/pull/65738 but looks like it needs more work because currently premium plugins can be installed only during checkout.

AFAICS there are no endpoints we can call from Calypso to install a plugin from the marketplace (@cpapazoglou can you confirm?), so we either work on that or switch back to our initial plan of maintaining a marketplace catalog in wpcomsh.

**Comment by cpapazoglou** [comment]
> AFAICS there are no endpoints we can call from Calypso to install a plugin from the marketplace

That's correct, there is no way to trigger an installation without going through checkout.

**Comment by cpapazoglou** [comment]
> switch back to our initial plan of maintaining a marketplace catalog in wpcomsh.

can the purchase include the original product slug and not the truncated one?

**Comment by mmtr** [comment]
> can the purchase include the original product slug and not the truncated one?

Yes, but I wouldn't recommend it as discussed in p1657798282113709/1657791814.481889-slack-CJS75TX3R:

> my main point was to don’t use `WPCOM_PURCHASES` because it’s not immediately obvious why someone needs to read `WPCOM_PURCHASES` to know if a plugin comes from the marketplace

> a purchase always has a link to a product, but it won’t be always linked to a plugin. hiding the delete link shouldn’t rely on the purchases info, since that’s dictated by the nature of the plugin

> it doesn’t matter whether a plugin is installed because it has been purchased, what matters is whether the plugin is a marketplace plugin and that’s not coupled to the site purchases

**Comment by mmtr** [comment]
In other words, looks like the only reason to add the plugin slug to the purchases stored in the Atomic persistent data is to bypass the lack of a marketplace catalog in wpcomsh. I feel that falls into "selfish code" (p7H4VZ-2Vx-p2) since it just helps us to avoid writing less code, but it makes things harder for folks trying to learn and understand how wpcomsh works when reading the code.

**Comment by cpapazoglou** [comment]
> it doesn’t matter whether a plugin is installed because it has been purchased, what matters is whether the plugin is a marketplace plugin and that’s not coupled to the site purchases

That's not accurate. We wouldn't want to hide the delete link or alter anything for plugins installed (uploaded) not from WordPress.com. The fact that they are purchased from WordPress.com makes them "special". But another way to figure this out without having the catalog in wcpomsh, is to check if that current plugin is managed from the Atomic infra.

**Comment by mmtr** [comment]
> But another way to figure this out without having the catalog in wcpomsh, is to check if that current plugin is managed from the Atomic infra.

We still need to differentiate managed marketplace plugins from managed non-marketplace plugins, since we allow (some) managed non-marketplace plugins to be deleted.

**Comment by mmtr** [comment]
> what if we allow marketplace plugins to be reinstalled from Calypso if they have been purchased? That way we wouldn’t need to hide the delete link and thus we won’t need to maintain any marketplace plugins catalog data in wpcomsh, right?

Turns out that we also need to determine whether a plugin has been installed from the marketplace to only show those on sites without the `INSTALL_PLUGINS` feature (1004-gh-Automattic/wpcomsh) so we are going to need that catalog anyway.

I'll publish a post today to align with the Atomic team about the approach to take.

**Comment by mmtr** [comment]
> I'll publish a post today to align with the Atomic team about the approach to take.

p9o2xV-2gS-p2

**Comment by mmtr** [comment]
This has been fixed by D84996-code and 1053-gh-Automattic/wpcomsh
