### ISSUE TITLE
[Bug]: Missing content/functionality when visiting /themes while logged out

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#65645]
### Quick summary

When visiting `/themes`  _while logged out_ and the search bar is attached to the top of the screen.

There is also functionality for theme searching/filtering that's not visible when logged out, though this may be by design.

![image](https://user-images.githubusercontent.com/917632/179288094-68d89c59-a156-4b24-9132-82b25eed7a28.png)

### Steps to reproduce

Visit `/themes` on mobile while logged out. This was originally reported regarding Safari mobile but was also reproduced on mobile Firefox.

Initial report in p1657882449004999-slack-C02KBT54T9T

**Comment by markbiek** [comment]
As noted by @donlair , this could be a good opportunity to add a header footer that matches the rest of the logged out experience (items 1 and 2 on pcOTDw-gx-p2).

**Comment by blackjackkent** [comment]
> As noted by @donlair , this could be a good opportunity to add a header footer that matches the rest of the logged out experience (items 1 and 2 on pcOTDw-gx-p2).

For our purposes for this issue, let's just focus on the functionality fix; other design updates will be in the works separately.

**Comment by markbiek** [comment]
Fixed by #65743
