### ISSUE TITLE
Social Authentication: Distinguish authentication flow when emitting Tracks events

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#65649]
### Details

We have three separate authentication flows where we're handling social connections:
- log in (`/log-in`);
- sign up (`/start/user`);
- account linking (`/me/security/social-login`).

Right now, it's not possible to distinguish on Tracks from which flow the events are being fired.

The goal of this task is to add an event property (i.e. `flow_name`) where we can identify and filter those events on Tracks. 

### Done is

- [x] All `calypso_login_social_*` events are recorded on Tracks with a property identifying the social authentication flow

Related to p1657653656323599/1657543719.065669-slack-C0347E545HR.

**Comment by p-jackson** [comment]
I'd recommend a property name that isn't called "flow". Signups already have a very well-understood meaning for the word "flow" so it could trip some people up. Maybe it's something like "initiator"?

**Comment by zaguiini** [comment]
Or `origin`. Something like that...

**Comment by danielbachhuber** [comment]
Going with `starting_point`.

**Comment by zaguiini** [comment]
I recommend we go this route, @danielbachhuber:

If we search for usages of the [`<GoogleLoginButton />` component](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/social-buttons/google.js), we'll see that it's used in the exact three places where we're aiming to understand the origin of the events:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/26530524/180307478-f2e528ea-4e9b-41f4-8d61-8b0f6ab60fa9.png">

So how about adding a new prop called `startingPoint` to `GoogleLoginButton` that identifies the starting point, then passing this prop in the places where the component is used?

We could use the prop in `GoogleLoginButton` and add this additional event prop on every `recordTracksEvent` call inside the component.


### Breakdown of the changes

#### `client/components/social-buttons/google.js`

This is the component that handles the Google auth process. Here, we'll need to accept a prop called `startingPoint` and pass it as an event prop to all `recordTracksEvent` calls. It should cover all failures related to Google authorization.

On a second PR, we need to redefine the event names that are associated with this component. They're all namespaced to `calypso_login` but that's inaccurate -- `<GoogleLoginButton />` is also used in sign-up and social connection. I would even go one step further and rename it to `<GoogleSocialButton />` so it's unrelated to a specific flow.

If you're looking for suggestions on the event namespace, I'd go for something like `calypso_social_button`. That'd be far more accurate and decoupled from login.

Finally, on a third PR, we should create an event called `calypso_social_button_auth_code_exchange_success` to give a counterpart so we can relatively understand how much the failures are impacting us.

#### `client/blocks/login/social.jsx`

That's the login flow. Apart from adding the `startingPoint` prop to the `<GoogleSocialButton />` ~instance, we also need to modify the `recordEvent` method to include it as an event parameter, just like `social_account_type` is there~ not necessary because it's already implied in the event name. This should cover the failures and successes of social login.

#### `client/me/social-login/action-button.jsx`

This one is responsible for socially linking an existing WPCOM account to the social service. Only adding the `startingPoint` prop to the `<GoogleSocialButton />` instance won't be enough because there are no other events, so it isn't possible to see the full picture (i.e. create a funnel). So we could first work on the `google.js` file (first point) and then modify https://github.com/Automattic/wp-calypso/pull/65839 to add the events just like you did there. 

#### `client/blocks/signup-form/social.jsx` 

This is the sign up flow. Apart from adding the `startingPoint` prop to the `<GoogleLoginButton />` instance, we also need to identify the flow in `calypso_login_social_button_click`, rename this event to `calypso_signup_social_button_click` and add a new event called `calypso_signup_social_success` to the `handleGoogleResponse` method just before it calls the `props.handleResponse` method, so we know that the social service authentication worked properly.

That's a different event because authenticating with the social service doesn't mean that the sign-up process was successful, but checking that the whole process was successful would fall out of scope.

This component is a "tricky" one because we have 3 places where this component is instantiated:

- `<CrowdsignalSignupForm />`;
- `<SignupForm />`;
- `<P2SignupForm />`.

So we should accept a prop on `<SocialSignupForm />` that allows passing the initiator, then on those components above, set the initiator as a prop of `<SocialSignupForm />`, and finally consume it inside the `SocialSignupForm` events...

---

Whew, that's a mouthful. And that's only for Google. We need to do basically the same thing for Apple! But then you should be pretty familiar with that already since it's basically the same thing.
