### ISSUE TITLE
User needs to use log in button to read premium content

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#65658]
### Quick summary

When subscribers to premium content receive an email and click through to read the content they need to click the login button on the premium content block before being able to read the content even though they are already logged into WordPress.com. 

### Steps to reproduce

- User posts a new post with premium content
- Subscriber receives an email with a preview and link to the new post
- Subscriber clicks on the link to read the full post
- Subscriber needs to click the login button on the premium content block even though they are already logged in to WordPress.com
Screenshot:
![subscribe to get access](https://user-images.githubusercontent.com/5507879/179389944-ad239203-3c74-418d-a2a1-e7e791f375d6.png)

### What you expected to happen

I expected the premium content to be immediately available as I am logged in to my account. 

### What actually happened

I needed to click the log in button on the premium content block. log-in

### Context

5391905-zd

### Platform (Simple, Atomic, or both?)

Atomic

### Browser, operating system and other notes

I think it's created this way but I do understand the user's frustration and confusion.

I tested it on my own site and it's showing the exact same behaviour. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

I advised the user to add the info about clicking on the login button to read the content to their Premium content block or to the email confirmation.

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- This seems to be the same issue as 458-gh-Automattic/payments-shilling
- Will close this issue in favor of that open issue.

📌 ACTIONS
- Closed as duplicate of 458-gh-Automattic/payments-shilling
