### ISSUE TITLE
Social Login: Offer to create a new account if it doesn't exist

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#65651]
### Details

If you try to social login (https://wordpress.com/log-in) using a social account (i.e. Google) that is not registered in WordPress.com, you'll get an error message saying that the account doesn't exist:

![image](https://user-images.githubusercontent.com/26530524/179310902-7bc60d99-35ab-48a6-b22c-86ece9e58a50.png)

While that's accurate, it's a below-average user experience because we have the data to create an account for the user as they're already socially authorized into WP.com. Let's take this opportunity to suggest that they can create an account and take the action accordingly.

### Done is

- [ ] The account is created if the user clicks the CTA
- [ ] The UI reflects this new account creation (i.e. redirected to `/home`)
- [ ] The tracks events related to social authorization are fired

### Related

p1657729373359479/1657702289.138929-slack-C0347E545HR.

**Comment by danielbachhuber** [comment]
After some discussion:
1. We'll add a "Would you like to create a new account?" link.
2. If they click the link, they'll be taken to `https://wordpress.com/start/user?launch=google`, which will launch the Sign Up with Google popup.

**Comment by zaguiini** [comment]
After discussions, we decided that this (`unknown_user`) is not an error, but an _attempt_ to log in. So we decided to treat them as such. We'll create a new event prefixed `_attempt` and we'll replace the failure event with this attempt.

More: p1658441604524419-slack-C0347E545HR.
