### ISSUE TITLE
Social Sign Up: Warn the user about an already existing account

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#65654]
### Details

If the user tries to log in with a social account, but that e-mail address is already associated, we display a message:

![image](https://user-images.githubusercontent.com/26530524/179317132-92a3f2d3-4d67-4b66-a325-5d1f4cae6203.png)

That's very good because then the user knows that they already have an account with us.

However, doing the same thing in `/start/user` produces a very different result:

- the user is redirected to `/start/domains` while we're validating his sign-up attempt;
- then after a moment they're redirected to `/log-in` with no indication of what happened, just an empty log-in form:

![image](https://user-images.githubusercontent.com/26530524/179317409-231c5f4d-05d4-4400-bb4b-55509b0f1f88.png)

### Done is

- [x] There's an alert saying that an account already exists with this e-mail
- [x] The alert contains a link to the log-in page
- [x] When clicking the link, the e-mail is pre-filled and the only thing the user needs to do is to type the password

### Related

p1657729373359479/1657702289.138929-slack-C0347E545HR.

**Comment by danielbachhuber** [comment]
👍 This makes sense as explained.

**Comment by zaguiini** [comment]
After discussions, we decided that this (`user_exists`) is not an error, but an _attempt_ to sign up. So we decided to treat them as such. We'll create a new event prefixed `_attempt` and we'll replace the failure event with this attempt.

More: p1658441604524419-slack-C0347E545HR.

**Comment by danielbachhuber** [comment]
Fixed with #65908
