### ISSUE TITLE
Plans: Add "Remove WordPress.com Branding" to Business plan

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#6566]
For the business plan, we now offer the ability to remove the "Powered by WordPress.com" branding in the footer of your site. This should be added to the plans page as a feature for the Business plan.

Name: Remove WordPress.com Branding
Description: Remove the "Powered by WordPress.com" branding in the footer of your website.

**Comment by lamosty** [comment]
Fixed in #6573.
