### ISSUE TITLE
Sites Management Dashboard: Filtering `sites` in the `SitesDashboard` component

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#65674]
In https://github.com/Automattic/wp-calypso/pull/65644#discussion_r923078035, @p-jackson sez:

> The dashboard components would be more easily embeddable in other contexts if they didn't use `window.location` and `page()` directly but instead called up to their parent. But we can also figure that out when we refactor the components back into `@automattic/components` again.

After I submitted the pull request on Friday, I had some later reflection wondering if the filtering of `SiteData[]` is happening at the right level.

To me, it seems like the application of `queryParams` should happen in `<SitesDashboard>`, and then the filtered `SiteData[]` passed into the child components.

At the moment, `SiteData[]` is first filtered in `<SitesTableFilterTabs>`, which then calls `<SitesContainer>`, which then filters `SiteData[]` again in `<SearchableSitesTable>`.

@Automattic/build Thoughts?

**Comment by p-jackson** [comment]
Implementing this refactor here: #65769

**Comment by p-jackson** [comment]
As of #65769 our core `<SitesDashboard>` component is now responsible for the main features of our dashboard: filtering, searching, sorting.
