### ISSUE TITLE
Seller Experience - Establish tracks funnel for user progression through design picker

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#65688]
Let's set up a tracks funnel to analyze user behavior when selecting a theme in onboarding. This will be necessary to do the comparisons regarding conversion after deploying https://github.com/Automattic/wp-calypso/issues/65138.

**Comment by andres-blanco** [comment]
This funnel: p1658164788203519/1658163818.150829-slack-C0Q664T29 measures "Premium Theme Purchase in Stepper Design Picker".
