### ISSUE TITLE
Task: Update how we determine that FSE is active on a site

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#65697]
### Details

To determine if a site supports FSE features, so far, we've been using a custom endpoint: `/sites/${ site?.ID }/block-editor` and its `is_fse_active` property to determine theme support for FSE. [But as of WP 6.0.1](https://github.com/WordPress/wordpress-develop/pull/2675), we have a way to determine if the active theme uses full site editing by looking for the `block-templates` theme support.

Using the `/wp-json/wp/v2/themes?status=active` (mapped to `/wp/v2/sites/{site}/themes?status=active` for public-api.wordpress.com), the `theme_supports` property returns `true|false` for the `block-templates`, indicating whether the theme has block based templates and can use the Site editor.

With the Core endpoint (`/sites/${ siteId }/themes?status=active`) now available, I propose we switch to using it instead. One primary benefit is for Jetpack sites: right now `is_fse_active` value depends on syncing information from the remote site, [which has caused bugs](https://github.com/Automattic/wp-calypso/issues/62755) because there's a delay in the data being updated after a theme switch. Using the Core endpoint, we query the Jetpack site directly and there's no delay.

### Checklist

(https://github.com/Automattic/wp-calypso/search?q=is_fse_active)

Replace all uses of `useFSEStatus` and `useBlockEditorSettingsQuery` components that use `is_fse_active`

- [ ] https://github.com/Automattic/wp-calypso/blob/1acdeee0811db7f62be4536c607cc645e57722e1/client/landing/stepper/hooks/use-fse-status.ts
- [ ] https://github.com/Automattic/wp-calypso/blob/1acdeee0811db7f62be4536c607cc645e57722e1/client/data/block-editor/use-block-editor-settings-query.ts

Here are results for an `is_fse_active` search

- [x] https://github.com/Automattic/wp-calypso/blob/1d97ffeb2820c43dc1edfe1f6966876bc454c238/client/blocks/product-purchase-features-list/customize-theme.jsx#L12
- [x] https://github.com/Automattic/wp-calypso/blob/eccc3bd4b83ea35721bd27b6c3587180d721b7df/packages/data-stores/src/site/actions.ts#L318
- [x] https://github.com/Automattic/wp-calypso/blob/40b81766871cd19e04f9abe5886fb133bed2cbec/client/my-sites/themes/theme-options.js#L34
- [x] https://github.com/Automattic/wp-calypso/blob/eccc3bd4b83ea35721bd27b6c3587180d721b7df/packages/data-stores/src/site/test/selectors.ts#L271
- [x] https://github.com/Automattic/wp-calypso/blob/6d2004c8824d242e8af4832d5fb82f78a93ba8a2/packages/data-stores/src/site/types.ts#L104
- [x] https://github.com/Automattic/wp-calypso/blob/6302aab91b2bba39a06da98e909fcd876ff6d229/client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx#L344
- [x] https://github.com/Automattic/wp-calypso/blob/75708e35531d792c582ca393729e17e57f66d9ee/client/lib/signup/step-actions/index.js#L439

### Related

FSE Cleanup: https://github.com/Automattic/wp-calypso/issues/61107 

First PR that started using /themes?status=active and introduced a query component for it: https://github.com/Automattic/wp-calypso/pull/64497

**Comment by creativecoder** [comment]
Noting that it looks like `useFSEStatus` [is no longer used](https://github.com/Automattic/wp-calypso/pull/65145/files#diff-614cccce787b17e46e84a16af7865700992dfd374e701239023fd2e1feaa12a1L195) and can be removed all-together.

**Comment by creativecoder** [comment]
@agrullon95 Assuming that the changes from #66028 will be merged in their current state, the only task I see left for Calypso is to remove `is_fse_active` from the `BlockEditorSettings` type in [use-block-editor-settings-query.ts](https://github.com/Automattic/wp-calypso/blob/1acdeee0811db7f62be4536c607cc645e57722e1/client/data/block-editor/use-block-editor-settings-query.ts)

Since it's deprecated, let's discourage using it by removing it and adding a comment about it being deprecated. (Maybe you want to do that in #66028?)

---

Another WP.com thing I'd like to clean up are the various FSE related properties on the v1.1 /sites API endpoint. But that is a separate task.

**Comment by agrullon95** [comment]
The changes to update how we determine FSE is active on a site have been made in these two pull requests:
https://github.com/Automattic/wp-calypso/pull/65850
https://github.com/Automattic/wp-calypso/pull/66028 (@creativecoder - I removed `is_fse_active` in this PR).

We still need to address the FSE v1.1 /sites API endpoint clean up in a separate task.

**Comment by creativecoder** [comment]
Thanks @agrullon95 , it's good to see this area of the code cleaned up!

> We still need to address the FSE v1.1 /sites API endpoint clean up in a separate task.

I think the main barrier to just removing the old properties is not wanting to break any clients that might be using them. The main concern it the mobile apps, so I've asked about them here: paYE8P-1Pu-p2#comment-1681
