### ISSUE TITLE
Theme card: Show subscription price

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#65698]
The theme card for a premium theme should show subscription price followed by plan upgrade nudge. Clicking on this text should lead to checkout.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/375980/179590286-5eeef905-e009-4076-ae13-81ace15a0d44.png">

This depends on design input in how to handle different pricing models (monthly, yearly).

Part of https://github.com/Automattic/wp-calypso/issues/65567

**Comment by valterlorran** [comment]
@andres-blanco @SaxonF it's not clear to me if we are going to increase the size of the preview as shown here. Can you clarify?
Currently the preview is around 577x375px:
<img width="455" alt="Screen Shot 2022-07-22 at 10 24 56" src="https://user-images.githubusercontent.com/1234758/180448495-2f4a9184-9708-48cb-9629-5124245a7b31.png">

**Comment by andres-blanco** [comment]
If I understand correctly this is the theme-card, not the preview screen.

**Comment by valterlorran** [comment]
Regarding the FSE badge, we should consider what we discussed here p1658256698659569-slack-C0Q664T29, and maybe remove it from the design. 
Related to #65753

**Comment by andres-blanco** [comment]
> Regarding the FSE badge, we should consider what we discussed here p1658256698659569-slack-C0Q664T29, and maybe remove it from the design. Related to #65753

The badge was already removed here: https://github.com/Automattic/wp-calypso/pull/65753

**Comment by SaxonF** [comment]
@valterlorran let's stick with the existing card size for this project. In further showcase iterations we can change the size and aspect ratio
