### ISSUE TITLE
Reader: Improve the browsing experience for lists of sites in Edit Followed, Edit List, and Recommendations

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#657]
Raised by @shaunandrews 

There are many places in Reader where you're looking at a list of sites; Edit Followed, Edit List, and Recommendations all feature a simple list of sites. Here's what the Edit Followed screens looks like on wpcalypso:

<img width="1115" alt="screen shot 2015-09-24 at 10 48 38 am" src="https://cloud.githubusercontent.com/assets/191598/10076597/5d3e0674-62aa-11e5-80a8-304a673c8409.png">

Its great that I can quickly see the sites I already follow—I can unfollow, or click/tap on the site name to view the site details, which shows me the site description, number of followers, and the latest posts:

<img width="1115" alt="screen shot 2015-09-24 at 10 48 44 am" src="https://cloud.githubusercontent.com/assets/191598/10076628/75349234-62aa-11e5-83b1-859e2bc5a237.png">

This is ok as a set of discrete screens, but the flow between them—which involves a "refresh" of content, scroll-jump to the top, and no sense of location in the IA—is broken. You can still use your back button, but it breaks what could be a seamless flow of browsing sites:
- Scroll through a list of sites
- Click/Tap on one that catches your eye
- Look at site description, and scroll through their posts
- Either Follow the site, or go back to the list.

The current flow is actually OK up until that last bit—getting back to the list can a bit confusing. A site preview, that loads within the current visible screen, could help fix the flow by making it easy to get back—you'll never leave.

Here's a quick mockup of a site details "pane:"

![followed site](https://cloud.githubusercontent.com/assets/191598/10076830/7cee0fa4-62ab-11e5-9c41-ba2c49c7a456.png)

In this mockup, the site pane would slide in much like the Notifications pane. You could quickly "check out" a site, and get back to browsing the list.

Q: How would this work on mobile or narrow viewports?
A: At a certain width, this overlay would take over the full screen and work exactly like our full post view does today.

Alternate idea raised by @apeatling is to more match the rest of the style of Calypso using a kind of modal view.

> I say that because I like the "peek" setting in iOS 9 with 3D touch and the way it shows front and center in a modal style, and we have precedent for a modal like that already in Calypso.

@folletto Notes that his team has a Web Preview component design with a modular top bar borrowed from the Reader, and a form of it is being built inside the Editor. (Note: mockup needed here.)

**Comment by lancewillett** [comment]
Anecdotal evidence, added feedback from @apeatling 

If I am looking at recommendations, and I click a site title to find out more about that site, there is no way to get back to the list of recommendations. The recommendations sidebar also is not highlighted. The whole flow feels very disconnected.

I wonder if there is a way to introduce a back link in this flow, or show the site in a modal (kind of like a peek of the content). I think the recommendations sidebar should stay highlighted throughout the flow.

![animation](https://cloud.githubusercontent.com/assets/1464705/10106832/d2236dbe-636b-11e5-8eee-1493e93b01a1.gif)

**Comment by folletto** [comment]
> Notes that his team has a Web Preview component design with a modular top bar borrowed from the Reader, and a form of it is being built inside the Editor. (Note: mockup needed here.)

The component has been built in the meantime, so it's live: it's the preview post or the theme preview. Screenshot:

![screen shot 2015-11-25 at 18 47 45](https://cloud.githubusercontent.com/assets/4389/11406439/0d05faaa-93a5-11e5-890a-ae3ced7a0d5d.png)

As things stand now, it's probably a different component. We should however try to keep the top bar consistent in terms of design. :)
