### ISSUE TITLE
Theme Showcase: theme cards should show premium badge

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#65705]
Theme cards within the showcase show a premium badge rather than the price. Hovering over this badge reveals pricing details as shown in image.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/375980/179601322-c9d3e527-efe1-4c60-8930-30c9721525c0.png">

Part of https://github.com/Automattic/wp-calypso/issues/65567

**Comment by valterlorran** [comment]
@SaxonF, could you provide me with the normal state of the star(without the hovering)?

**Comment by valterlorran** [comment]
@SaxonF, can you also check the design when the theme is active?
![Screen Shot 2022-07-19 at 15 55 16](https://user-images.githubusercontent.com/1234758/179827933-881000bb-0139-4f0b-aff2-87ab89bb9949.png)

**Comment by SaxonF** [comment]
@valterlorran let's just stick with current behaviour for now, so no premium badge on active theme card

<img width="299" alt="image" src="https://user-images.githubusercontent.com/1072756/179924517-dcc2b64d-0ae8-4471-ae4a-18cf79afdbc4.png">
