### ISSUE TITLE
Checkout Modal: Revert to Recoleta font

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#65701]
Revert preview header back to original Recoleta font.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/375980/179599405-0adf3582-82ff-40c1-8f0a-b2fea40c177b.png">

Part of https://github.com/Automattic/wp-calypso/issues/65567

**Comment by sixhours** [comment]
Should this change be behind the feature flag, or can we just ship it as-is?

**Comment by andres-blanco** [comment]
I think it would be better to ship it as-is, it doesn't seem related at all with theme subscriptions. What I don't know is if we should add the premium badge next to the title 🤔

**Comment by sixhours** [comment]
Cool, sounds good. We can make a separate issue for the badge if need be!

**Comment by andres-blanco** [comment]
Sounds great. We could keep this issue to track the font change. I'll ping Saxon on Slack to see if we need the premium badge there.
