### ISSUE TITLE
Purchases page lacks pagination, attempts and fails to load direct links

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#65717]
### Quick summary

For accounts which own large quantities of upgrades the https://wordpress.com/me/purchases fails to load. The page will attempt to load (displaying flashing grey elements on it) but will ultimately display no purchases and a "Looking to upgrade?" message:

![Screen Shot 2022-07-16 at 1 05 29 AM](https://user-images.githubusercontent.com/33190975/179679557-d807affe-f0a0-4572-9d2d-1ca1c976a1eb.jpg)

Things like pagination and/or a search bar could make it possible to load this page.

### Steps to reproduce

The Team 51 account is a fine example, though this account acts as an a12s account and cannot be accessed by SU. We're glad to provide videos or any other relevant data for troubleshooting this.

### What you expected to happen

We should be able to view and manage all Purchases and load specific purchase pages from within the account https://wordpress.com/me/purchases screen.

### What actually happened

The general account Purchases page and direct links to manage specific purchases fail to load.

### Context

Team 51 experience.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Workaround details

Store admin and other internal tools. No Calypso/customer-facing solution; however this problem likely only exists for Automattic-owned accounts due to the high "purchase" quantities needed to cause the failure to happen. (_Note_: I am not sure how many purchases are needed to cause the wordpress.com/me/purchases page to fail to load.)

**Comment by DavidRothstein** [comment]
Likely related to 1018-gh-Automattic/payments-shilling.

**Comment by michaeldcain** [comment]
We're going to try to resolve 1018-gh-Automattic/payments-shilling before revisiting the performance of this page.

**Comment by renata-franco** [comment]
📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 

------

📌 FINDINGS/SCREENSHOTS/VIDEO

I was not able to replicate this. I have around 20 purchases on my account and the page loads correctly. 

------

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

-------

📌 Message to Author


You said `large quantities of upgrades the [wordpress.com/me/purchases](https://wordpress.com/me/purchases) fails to load.'. 

I was wondering what you exactly mean by "large". How many does the example have? And could you please provide a video showing the issue, please? 

Also seems like this is being worked on here: 1018-gh-Automattic/payments-shilling so I will be closing this one.

**Comment by xpurichan** [comment]
Hi @renata-franco !

>I was wondering what you exactly mean by "large". How many does the example have? And could you please provide a video showing the issue, please?

The a8cteam51 account owns 769 websites at the moment and has 25 pages worth of upgrades in Store Admin:
https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=a8cteam51

>Also seems like this is being worked on here: 1018-gh-Automattic/payments-shilling so I will be closing this one.

_ack_, thank you!

**Comment by renata-franco** [comment]
> The a8cteam51 account owns 769 websites at the moment and has 25 pages worth of upgrades in Store Admin:
[wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=a8cteam51](https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=a8cteam51)

Thanks for explaining this :)
