### ISSUE TITLE
[All] Update footer layout

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65710]
### Details
The footer has a new proposed layout, now it's left-aligned with an addition of Jetpack and WP logos. It also includes two copies that may change depending on the email type:

#### New Like emails (comment and post)
- **Title:** Real-time notifications with the Jetpack mobile app
- **Subtitle:** See your likes, comments, and stats anywhere, anytime.
![Image](https://user-images.githubusercontent.com/3113712/179624801-83dfba51-fae3-4719-a016-96c56316fdf1.png)

#### New Comment emails (comment and approval)
- **Title:** Reply faster with the Jetpack mobile app
- **Subtitle:** Aprove and reply to comments with real-time notifications right on your device.
![Image](https://user-images.githubusercontent.com/3113712/179624850-43b2f3b6-840a-4338-a907-8e0364266ff7.png)

#### New Post emails
- **Title:** Get the Jetpack app to use Reader anywhere, anytime.
- **Subtitle:** Follow your favorite sites, save posts to read later, and get real-time notifications for likes and comments.

![Image](https://user-images.githubusercontent.com/3113712/179624894-88144d2f-23b6-47f7-bfc3-0a3d40d820c7.png)

#### Others
- **Title:** Get the Jetpack app
- **Subtitle:** View stats, moderate comments, create and edit posts, and upload media.

![Image](https://user-images.githubusercontent.com/3113712/179624946-25c928d4-1e4d-4f17-ad51-46e13482b32a.png)

**Figma reference:** c5bt2O2vWhTlhSREC89Bw2-fi-2741%3A16333

### Resources
- [App Store Badge](https://developer.apple.com/app-store/marketing/guidelines/)
- [Google Play Badge](https://play.google.com/intl/en_us/badges/)
- WordPress icon is also available on [Icons Library](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library)
- Jetpack can be exported on Figma

### Checklist
- [ ] Implement New Like variation
- [ ] Implement New Comment variation
- [ ] Implement New Post variation
- [ ] Change to a left aligned layout
- [ ] Switch Google Play and App Store badge positions

**Comment by yansern** [comment]
This work will be taken over by another team. pdgv5Y-mK-p2#comment-174
