### ISSUE TITLE
Marketplace: Query wccom for products based on categories

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#65718]
We added new categories to products in 13159-gh-Automattic/woocommerce.com and should now be able to query them through `/wp-json/wc/store/products?_unstable_tax_wpcom_marketplace_categories=[array_of_term_ids]`.

- [ ] Update calypso to load category products using the woocommerce.com api above

**Comment by lsl** [comment]
I don't know if this is something we should be doing yet (possibly update acceptance to be investigation task?) but I'm curious how far we can get. We should be waiting for elastic search but I don't know where that's at. We probably can't search this way but I think there is existing code seams we could implement something for the category lookups.

**Comment by allilevine** [comment]
> I don't know if this is something we should be doing yet (possibly update acceptance to be investigation task?) but I'm curious how far we can get. We should be waiting for elastic search but I don't know where that's at. We probably can't search this way but I think there is existing code seams we could implement something for the category lookups.

@cpapazoglou How does this task fit into the Elastic Search implementation / Woo integration work (once we add the categories to products)?

**Comment by cpapazoglou** [comment]
This task falls right under the Elastic Search implementation. Is it blocker for you in any way?

FWIW, we won't be using `/wp-json/wc/store/products?_unstable_tax_wpcom_marketplace_categories=[array_of_term_ids]` but an ES query which is far more flexible.

@gcsecsey is this related to any issue we already have open?

**Comment by allilevine** [comment]
> This task falls right under the Elastic Search implementation. Is it blocker for you in any way?

Thanks! 🙌 Not a blocker, but please let us know when we can test the ES queries in case there's tweaking needed on the WCCOM side.

**Comment by gcsecsey** [comment]
@cpapazoglou I think this issue is connected to https://github.com/Automattic/wp-calypso/issues/63167 Once we tackled that issue, we should be able to query for products based on the same term IDs through ES.

**Comment by lsl** [comment]
When we query ES instead are we able to maintain the setup of querying a group of tag slugs to represent a category? 

That's something we will want to maintain for querying .org plugins if its all being queried through the same index. I'd also like to keep the .com setup as consistent with .org as possible so [we're planning to store categories on woo.com in the same way](13159-gh-Automattic/woocommerce.com#issuecomment-1190920724) as we have in the marketplace catalog files (as tags).

**Comment by gcsecsey** [comment]
Sorry for the delay in getting back to you @lsl.

We're currently working on syncing the `wpcom_marketplace_categories` taxonomy to ES in #63903. Once the tags are in the index, we should be able to create a query on the API layer to get all plugins by a list of tags: https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html

**Comment by cpapazoglou** [comment]
@gcsecsey I think we should also tackle this before posting a CfT for ES searches?

**Comment by gcsecsey** [comment]
We've done a similar query for WP.org plugins in https://github.com/Automattic/wp-calypso/pull/68978. I'll look into updating the query to filter for wccom products as well.
