### ISSUE TITLE
[Gutenberg v13.7.0-rc.1] Site Editor returns 'The page requested does not exist'

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#65716]
### Quick summary

While team testing for `Gutenberg v13.7.0-rc.1`, we discovered that opening the site editor with an FSE theme active on a simple site returns the error `The page requested does not exist`

<img width="1792" alt="Screen Shot 2022-07-19 at 11 34 21 am" src="https://user-images.githubusercontent.com/21261509/179652326-9ceefb51-11a2-4d42-8b96-9ce409604409.png">

### Steps to reproduce

1. Open/create a simple site.
2. Activate an FSE theme from `Appearance > Themes`
3. Go to `Appearance > Editor`
4. The page returns a `The page requested does not exist` message.

### What you expected to happen

I expected the site editor to load. 

### What actually happened

The site editor returned the message `The page requested does not exist`.

### Context

Team Testing for `Gutenberg v13.7.0-rc.1` 

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

FSE Themes

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by chad1008** [comment]
Thanks @rw-ye! This is an interesting one... sandboxes (mine, at least) appear to be immune. I can't repro there (which is why I didn't catch it when smoke testing before the edge release), but I can reproduce it on a normal Simple site.

This will need some investigation, thanks again for the report!

**Comment by chad1008** [comment]
Haven't found any clues to the cause yet. There's one error in the console, and it's just a 500 error for `https://chadnonedgetest.wordpress.com/wp-admin/themes.php?page=gutenberg-edit-site`. There aren't any changes in the site editor URL with the new RC.

**Comment by Addison-Stavlo** [comment]
Im noticing on my test site that I am unable to visit the page editor was well in this state. 🤔 

I noticed a PHP warning about `gutenberg_enable_block_templates` not being a function. `Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'gutenberg_enable_block_templates' not found or invalid function name...`

**Comment by fullofcaffeine** [comment]
> I noticed a PHP warning about gutenberg_enable_block_templates not being a function. Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'gutenberg_enable_block_templates' not found or invalid function name...

Hi Addie 👋🏻, where did you see the warning?

**Comment by Addison-Stavlo** [comment]
> Hi Addie 👋🏻, where did you see the warning?

when logging php errors on my sandbox from /tmp/php-errors

i was testing an unrelated diff here - D84305-code and my test site with edge enabled was having problems due to this issue.

**Comment by renata-franco** [comment]
📌 SCRUBBING

- Tested on Simple ✅ 


------

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate this issue on a Simple site with Attar theme.

<img width="902" alt="imagen" src="https://user-images.githubusercontent.com/81378719/181284372-858c0ecd-cab4-4644-a1c4-47afdc2fefd3.png">


1. For the testing with the correct version of Gutenberg, [I used these instructions](pdtkmj-gU-p2)

------

📌 ACTIONS

- Marked as Triaged for Quality Squad review

**Comment by daledupreez** [comment]
I believe this issue should be addressed by https://github.com/Automattic/wp-calypso/pull/65997 and/or https://github.com/Automattic/jetpack/pull/25281, so I am going to close this issue out.
