### ISSUE TITLE
Sites Management Dashboard: Ensure back/forward history buttons work as expected

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#65733]
The back/forward history buttons don't work as expected right now, and they should.

From https://github.com/Automattic/wp-calypso/pull/65644#pullrequestreview-1041945027

> My only comment is that the back/forward history buttons doesn't seem to work as expected.
> 
> We can create an issue to fix that.
> 
> We probably need to create a useEffect to add a [popstate listener](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event):
> ```js
> window.addEventListener('popstate', (event) => {
>   console.log(document.location);
> });
> ```
> 
> ### Video
> https://user-images.githubusercontent.com/779993/179532391-212893a6-1ed6-4d6e-9d5e-268c78d0f4d0.mp4

Guiding this issue is @p-jackson's comment in #65726:

> My hope is that eventually you should be able to glance at the `<SitesDashboard>` component and see all of the major parts of the dashboard UI. The buttons, search boxes, tabs and table would all be portable and sharable components, but the dashboard is thing inside the Calypso app that glues them all together. This might increase the size of the `<SitesDashboard>` component, but I don't think that's anything to fear. It should be mostly JSX, with the fancy logic relegated to other components and hooks.
It will also minimise the amount of "prop drilling" needed for basic things like selected tab state and filtered sites list.

It's also work reviewing p1658176514415419-slack-C0347E545HR and #65711

**Done is:**
* There's a `window.addEventListener('popstate' )` listener high in the component tree (either `<SitesDashboard>` or the controller).
* `status` and `search` state is managed high in the component tree.
* The back/forward history buttons properly update `status` and `search` state.
* (might not be possible but) ideally, the search input and tabs dynamically update when back/forward history buttons are used.

**Comment by p-jackson** [comment]
Thanks for creating the issue @danielbachhuber.

> There's a `window.addEventListener( 'popstate' )` listener high in the component tree

@sejas I'm just throwing in my 2 cents on the above criteria. The `popstate` listener doesn't _have_ to be explicit in our code. Of course it might need to be, but the `page.js` library also has a `popstate` listener, so if you manage to implement this using `page.js` high in the component tree then that meets the criteria too.

**Comment by sejas** [comment]
Our latest implementation integrates the page context to build the URLs. In this way, the app handles the history stack "automatically".
The filtered results and the query params are working out of the box. The only thing that is failing is marking as active the selected tab.
I've found that our Tabs component uses a state encapsulated that we don't have control over.
https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/tab-panel/index.js#L44

I see two different options to display the current tab correctly :
1. Add a hack to click programmatically on the selected tab when the history changes
or 
2. Rewrite the tabs component from scratch to accept the current tab from the props.

- None of these options seem currently appropriate. In future iterations, we will probably replace the tabs with select boxes, as suggested here https://github.com/Automattic/wp-calypso/pull/65871
- I think the right path to take, at least for now, is replacing the history when the `search` or `status` query changes, similar to what's described here: https://github.com/Automattic/wp-calypso/issues/65762
   - Here is a PR replacing the history stack https://github.com/Automattic/wp-calypso/pull/66174

**Comment by sejas** [comment]
- Closing this issue in favor of https://github.com/Automattic/wp-calypso/pull/66218 and https://github.com/Automattic/wp-calypso/pull/66174
