### ISSUE TITLE
[New Comment] Should display `View comment` instead of `Reply` button

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#65746]
### Details

The current `prod` implementation displays `View comment` instead of `Reply` button.
Also the `commented` keyword is not clickable in the `prod` implementation. Note that keeping the hyperlink would also result in a not so nice UI when the commenter's username becomes a hyperlink too. 

![Annotation on 2022-07-19 at 18-06-55](https://user-images.githubusercontent.com/2019970/179799212-d1a0ad6f-f693-4785-9221-d514455f3d9a.png)

![Screenshot 2022-07-19 at 17 55 26](https://user-images.githubusercontent.com/2019970/179795296-cf50fa66-9fb9-45c5-b4d4-4d933f5ed0d2.png)

### Checklist

- [ ] display `View comment` instead of `Reply` button 
- [x] do not create a hyperlink over `commented` word

**Comment by mashikag** [comment]
I am closing this issue but it does not mean it is done.

It is now moved in as a requirement of the following issue: https://github.com/Automattic/wp-calypso/issues/65741

**Comment by ivan-ottinger** [comment]
This is being addressed in D86596-code.
