### ISSUE TITLE
Calendly block: Calendar settings link is broken

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#65757]
### Quick summary

The Calendly block has a link under Calendar settings (_"Follow these instructions to change the colors in this block."_) which links to a broken link:

```
https://help.calendly.com/hc/en-us/community/posts/360033166114-Embed-Widget-Color-Customization-Available-Now-
```

This should be updated to either the correct link from their site or a section on the .com [support page](https://wordpress.com/support/wordpress-editor/blocks/calendly-block/).

### Steps to reproduce

1. Add a Calendly block to a page 
2. Add an embed link
3. Look under block settings > Calendar settings
4. Click link

![Screen Shot on 2022-07-19 at 15:45:59](https://user-images.githubusercontent.com/10353785/179835578-d5bd1509-1f10-42d7-b7a4-d7f199c8ec05.png)

### What you expected to happen

Directions to change the color

### What actually happened

404 page, then redirect to the Calendly support page

### Context

Discovered this building a site pdEkSe-JX-p2

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Browser, operating system and other notes

Not browser related, but I was using FF 102.0.1

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by daledupreez** [comment]
It's probably worth switching the link to https://wordpress.com/support/wordpress-editor/blocks/calendly-block/#change-the-look-and-feel-of-the-calendly-embed
That allows us to reference documentation we control and avoid similar broken links in future. (Also, our docs are pretty good in this case!)

**Comment by daledupreez** [comment]
I looked into this some more, and things aren't that simple. 🙃

The [WordPress.com docs for the Calendly block](https://wordpress.com/support/wordpress-editor/blocks/calendly-block/) are much more comprehensive than the [Jetpack docs for the Calendly block](https://jetpack.com/support/jetpack-blocks/calendly-block/). I have reached out to the Jetpack docs team, and will see if we can improve that documentation as a starting point.

**Comment by mikeicode** [comment]
@daledupreez 

I'm assuming the link to the Calendly site showed a page explaining how to change the colors from the actual embed, like their current [support page](https://help.calendly.com/hc/en-us/articles/223147027-Embed-options-overview), under **Customizing your embed > Customize the color and button text**:

![Screen Shot on 2022-07-28 at 08:15:57](https://user-images.githubusercontent.com/10353785/181502645-58a4de10-f950-48ca-8b9d-4a3c6c851adc.png)

Our docs show how to change the Buttons block, but don't show how to change the actual colors of the embed. I'm not saying they _should_, but just an FYI of what I'm assuming we previously linked to.

**Comment by daledupreez** [comment]
Thanks for taking a look at this, @mikeicode! I was debating whether we want to link to their docs for two reasons:
1. They have already updated and removed the previous content, so their track record isn't stellar
2. They don't have an anchor for the _Customize the color and button text_ section, _and_ the anchor for the broader _Customizing your embed_ section is simply `#3`, which doesn't make it ideal to link to (especially on mobile where the relevant content will require a decent amount of scrolling).

I am thinking that we likely need three sets of related changes:
1. Update the WordPress.com documentation to mention that some customization options are only available via Calendly, and the block can only affect some parts of the embed.
2. Update the Jetpack documentation to be closer to the WordPress.com documentation.
3. Update the language in the block editor to reflect that some changes need to be made in the block editor, and some need to be made via Calendly.

**Comment by daledupreez** [comment]
As a quick update on this, I drafted some updates to the Jetpack documentation for the Calendly block, which is a blocker for us updating the links to something we own. That content has been reviewed, and should make it onto the site this week.

I'll start work on a PR to update the links in the meantime so we can roll out a fix as soon as the content is updated.

**Comment by daledupreez** [comment]
As a follow-up on this, the Jetpack docs for the Calendly block have been updated, so we can land this PR as soon as get it reviewed and tested.

**Comment by daledupreez** [comment]
The changes were deployed to WordPress.com Simple sites a few minutes ago. The fix will only roll out to Atomic sites when during our next weekly Jetpack alpha release.
