### ISSUE TITLE
My Home - Add homepage card that links to WP Youtube page

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#65750]
From @ianstewart discussion in Slack at p1658246371107379-slack-C029JEQRVRT

> thoughts on making a card like the one shared here that links out to [our WordPress YouTube page](https://www.youtube.com/wordpressdotcom)?
My thoughts on it:
>
>It should be super-easy to design and launch. But why do it? From talking to @supernovia over the past few days and looking at our cancellation reasons, it has become even more clear that people need help setting things up, and this is always going to affect Marketplace top of funnel, so to speak. And that YouTube page is pretty awesome at helping people set things up.
>
>If it’s very simple, and a good idea, I think it’s worth doing ASAP for an Expand team that would like a quick front-end PR to fit in. Seems generally helpful for Dotcom plus also for Expand.

![image](https://user-images.githubusercontent.com/13437011/179804626-eb5b5925-9769-4838-a562-307db5ab5a65.png)

Let's add a new card to the homepage stack for all users offering direction to the WPcom YouTube page as detailed above.

**Comment by ianstewart** [comment]
@blackjackkent  would be good to confirm that we have tracks events for clickthrough on those cards. (We probably do, but never know.)

**Comment by blackjackkent** [comment]
@SaxonF Could you whip up a design for this card so we can get it set up? :)

**Comment by SaxonF** [comment]
if the goal is to help guide and educate users, should this part of the help center work and/or Launchpad on Create? I'm wary of introducing too many generic pathways into help and it might also get more visibility there.

**Comment by blackjackkent** [comment]
@ianstewart Do you have any thoughts on Saxon's comments above?

**Comment by andres-blanco** [comment]
You can now access educational videos on the Help Center.
<img width="436" alt="image" src="https://user-images.githubusercontent.com/375980/225752136-a6755860-9009-43b9-bd0f-24956feabcdc.png">
