### ISSUE TITLE
Sites Dashboard: Handle sites that are redirects or have conflicting URLs

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#65767]
The way we're calculating the "site slug" for the sites in the dashboard is naive. You can see [the logic we usually use here](https://github.com/Automattic/wp-calypso/blob/12687cf918f9f073d8e09ab39a4cb069d0448d1c/client/state/sites/selectors/get-site-slug.js#L16).

The naive implementation (added in #65764) means that clicking the primary link in the site row doesn't work for some sites. Specifically:
- Redirect sites https://wordpress.com/support/site-redirect/
- Situations where two sites have the same URL, which can happen with Jetpack. See https://github.com/Automattic/wp-calypso/blob/12687cf918f9f073d8e09ab39a4cb069d0448d1c/client/state/sites/selectors/get-site-collisions.js#L6

We might need to request some extra data as part of the reduced sites excerpt payload. Or maybe we should add support to the backend for generating slugs rather than doing it on the client?

Done is:
- [ ] Navigation from the dashboard to a site's My Home works when the site represents a redirect
- [ ] Navigation from the dashboard to a site's My Home works when the site's URL conflicts with another site in the list
- [ ] It may or may not share code with the `getSiteSlug()` selector

**Comment by danielbachhuber** [comment]
@p-jackson FYI - I had previously flagged this with https://github.com/Automattic/wp-calypso/issues/65490#issuecomment-1189029079 and had a partial pull request going: #65736

**Comment by p-jackson** [comment]
Argh! Sorry I didn't notice your early PR #65736 :( I could have just continued work on that one.

**Comment by danielbachhuber** [comment]
Also worth noting: we want to avoid hitting Redux, because it will cause a lot of API requests, slow down our selector, etc. 

The redirect scenario is relatively straightforward:

https://github.com/Automattic/wp-calypso/blob/d2900b0413e07ccd19a6e8357a84a989f024c9c8/client/data/sites/use-site-excerpts-query.ts#L54-L64

Solving `isSiteConflicting` may be more involved.
