### ISSUE TITLE
Sites Management Dashboard: Considering skipping browser history when `?search=<query>` updates

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#65762]
Currently, when a user searches the site dashboard, browser history is updated with the search value:

https://user-images.githubusercontent.com/36432/179855691-77b89b15-dbf2-4763-973d-72ed9192592b.mp4

In #65760, debounce was removed so _every keystroke_ gets pushed to the URL. I think this is excessive. I'm also not convinced search queries should be pushed to browser history in the first place.

@Automattic/build Thoughts?

**Done is:**
* We have a decision on whether or not search queries should be a part of browser history.
* If we decide to remove them, a pull request is submitted to remove them.

**Comment by zaguiini** [comment]
If the concern is regarding polluting the browser history by adding new entries, we could replace the current one (`history.replace`) instead.

I do think it's very useful to keep the search in the query parameters as a regular filter if somebody wants to quickly apply filters by bookmarking a page, for example.

**Comment by danielbachhuber** [comment]
> If the concern is regarding polluting the browser history by adding new entries, we could replace the current one (`history.replace`) instead.

Ah, yeah, that could work too.

**Comment by p-jackson** [comment]
`history.replace` sounds pretty good. Presumably calling this directly wouldn't fire the `page.js` handling? That's nothing wrong with that, just wondering out loud.

> _every keystroke_ gets pushed to the URL. I think this is excessive

It does feel like the URL would be changing a lot 😅 But if there are no performance issues with that (like the call to `history.replace()` taking 50ms to complete) then maybe we wouldn't need to debounce it? I just want to make sure the keypresses feel responsive.

**Comment by sejas** [comment]
- If we implement the tabs as dropdown, then I don't see the need for this either #65733
