### ISSUE TITLE
Design Preview: Maybe add Premium badge to header

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#65786]
> I'll ping Saxon on Slack to see if we need the premium badge there.

_Originally posted by @andres-blanco in https://github.com/Automattic/wp-calypso/issues/65701#issuecomment-1190375336_

p1658328246651409-slack-C0Q664T29

We might want to add a Premium badge to premium themes in the design preview header, like in this mockup:

<img width="804" alt="179599405-0adf3582-82ff-40c1-8f0a-b2fea40c177b" src="https://user-images.githubusercontent.com/2124984/180018971-c940c4e3-8110-4ceb-abdf-ac418ebe90dc.png">

Creating this issue so it doesn't fall through the cracks.

**Comment by blackjackkent** [comment]
Closed by #65944
