### ISSUE TITLE
[New Liked Comment] Create feature flag

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65798]
### Details
Create `wpcom_use_2022_new_liked_comment_email_template` feature flag using a similar approach as `wpcom_use_2021_email_templates` did. There is a `wpcom_html_emails_use_i2_templates` function that validates if the user's email finishes with `+wp21em`, this function is unused and can be replaced for a new one related to New Liked Comment.

**Comment by ivan-ottinger** [comment]
I have deployed the patch now: D84581-code. Changeset: r249738-wpcom.
