### ISSUE TITLE
E2E: Site Importer specs permanently failing due to changes to Importer

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#65792]
### Quick summary

Site Importer specs are failing permanently due to a change in the Goals Capture feature and the associated featuer flag being turned on.

### Steps to reproduce

Run the `onboarding/setup__importer.ts` test or `onboarding/start__importer.ts` specs.

### What you expected to happen

Specs should pass.

### What actually happened

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "input.capture__input" to be visible
============================================================
at StartImportFlow.validateURLCapturePage (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/start-import-flow.ts:74:19)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/setup__importer.ts:32:26)-
```

![image](https://user-images.githubusercontent.com/6549265/180044230-192a9138-2423-46a0-9df1-7d1bac15f886.png)

### Context

Automated testing.

### Reproducibility

Consistent

Possibly related issues: https://github.com/Automattic/wp-calypso/pull/65539 and https://github.com/Automattic/wp-calypso/pull/65584.

**Comment by yansern** [comment]
Thanks for catching this! Does manually trigger "Calypso E2E Pre Release" in TeamCity runs the importer specs?

**Comment by worldomonation** [comment]
I believe the Importer specs are run for the Calypso E2E suites, which are run on feature branches for every commit.

Relevant thread: p1658336587392099-slack-C02DQP0FP
