### ISSUE TITLE
Reader: Tags: tag not found page doesn't have any helpful info

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#658]
Steps to reproduce:

1. Go to a tag page for a tag that doesn't exist, i.e. https://wordpress.com/tag/murdersloth
1. Go to a list page that doesn't exist, i.e. https://wordpress.com/read/list/nbradbury/murdersloth

<strong>Result:</strong> a placeholder header is shown with no indication that the list or tag was not found. The following console error appears in Firefox:

```
TypeError: sub.slug is undefined reader.5a28957d4ee8f9a7f639.min.js:8:17897
```

![screen shot 2015-11-24 at tue nov 24 12 36 07 pm](https://cloud.githubusercontent.com/assets/1119271/11375214/05eedc12-92a8-11e5-988c-2ec0499a5e01.png)
<sup>Seen at https://wordpress.com/tag/murdersloth using Firefox 42.0 on Mac OS X 10.10.5</sup>

We should fix this problem both for tags that don't exist as well as tags which don't have anything public to display, i.e. https://en.wordpress.com/tag/ancient-greek-and-roman-coins-www-trustedcoins-com/

![screen shot 2015-11-24 at tue nov 24 12 34 56 pm](https://cloud.githubusercontent.com/assets/1119271/11375188/e61baa82-92a7-11e5-94c6-ba5600ef6397.png)
<sup>Opera 33.0, logged out tag page view</sup>

Keep in mind logged-out tag pages should also be fixed and that they are indexed by Google.

**Comment by vsukhomlinov** [comment]
@designsimply I'm able to get a tag page with no public posts on it [https://wordpress.com/tag/Empty1](https://wordpress.com/tag/Empty1)

<img width="1430" alt="screen shot 2015-11-25 at 9 32 59 pm" src="https://cloud.githubusercontent.com/assets/108110/11415827/b6d970ea-93bc-11e5-84c0-4092e99d5584.png">

While other tags that don't exist return response with error message like 'The tag requested does not seem to be valid.'
Does it make sense to reuse the view from above for that case or display the error somehow?

**Comment by designsimply** [comment]
@vsukhomlinov, thanks for the note. I think the difference is that Empty1 must be an existing tag used by someone in the past for testing and it just doesn't have any recent posts in it. Try https://wordpress.com/tag/thistagdoesntreallyexistitsreallytoolonganywaywhowouldeveruseit

> Does it make sense to reuse the view from above for that case or display the error somehow?

Yes, that would solve this issue.
