### ISSUE TITLE
Marketplace: Improve or replace generic categories

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#65818]
`photo`,`widgets`,`posts`

Search performance for these categories seemed low. We suspect its due to them being very general in nature.

For `photo` (aka media), `widgets`, and `posts` categories, look through the plugins within them and pull out more specific categories.

For example, the [photo category](https://wordpress.org/plugins/tags/photo/) might be worth renaming to "Photo gallery". We're looking to make categories focused on solving a user problem instead of focusing on generic labeling.

- [ ] Suggest category replacements (or removal) for `photo`, `widgets`, and `posts`

**Comment by cpapazoglou** [comment]
The categories have already been curated.
