### ISSUE TITLE
Cold Start: Cards not showing post preview in Safari

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#6581]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/recommendations/start
2. Cards don't show the post preview. If they do, try refreshing again.
#### What I expected

For cards to show post preview:

<img width="755" alt="screenshot 2016-07-06 13 30 53" src="https://cloud.githubusercontent.com/assets/4924246/16633377/e981ce22-437d-11e6-881c-8a9ab7708577.png">
#### What happened instead

Cards don't show their post preview:
<img width="753" alt="screenshot 2016-07-06 13 31 42" src="https://cloud.githubusercontent.com/assets/4924246/16633398/04e8604a-437e-11e6-9c00-97ef7196611b.png">

Mobile Safari:
<img width="259" alt="screenshot 2016-07-06 13 36 21" src="https://cloud.githubusercontent.com/assets/4924246/16633530/a44ae8c4-437e-11e6-911f-15da0dfb27eb.png">
#### Browser / OS version

Safari 9.0.3, OSX 10.11.3
Safari 9.1.1
Mobile Safari, iOS 9.3.2

**Comment by blowery** [comment]
Appears the problem is that the map we maintain in the post selector occasionally has all of it's entries overwritten to one entry with the key 'true'. Investigating how that could happen.

**Comment by bluefuton** [comment]
Still seeing this occasionally in production, when returning from a full-post view or site stream using the 'back' link. Intermittently I get this:

<img width="821" alt="screen shot 2016-07-07 at 19 47 12" src="https://cloud.githubusercontent.com/assets/17325/16663271/ca700f40-447b-11e6-8c06-6c3cfb16e8b9.png">

**Comment by jancavan** [comment]
Checked again right now and can confirm this is happening again 😞  Although it worked fine for me earlier this morning.

**Comment by blowery** [comment]
@bluefuton if you can repro it, you'll want to set a break inside the reader/posts/selectors::getPostBySiteAndId selector and see what's living in that map. It was occasionally losing all the entries in my testing.
