### ISSUE TITLE
Explore backend improvements

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#65826]
### Objective
Everything Import migration results in breakage of a few Atomic-specific functionalities like symlinked plugins, plan status, Jetpack connection and a few other things, see p7DVsv-eM6-p2#comment-41177 for more details.

**Comment by zaerl** [comment]
See:
1. https://github.com/Automattic/dotcom-manage/labels/Backend%20improvements
2. p1660727999900679-slack-C01A60HCGUA

**Comment by retnonindya** [comment]
I'm triaging this issue, and it seems like the issue is no longer relevant now that we have updated our site migration flow. Also, the symlinked issue has been fixed here: peaFOp-R-p2 

📌 ACTIONS

Closed as could not replicate (please reopen if the issue reoccurs)
