### ISSUE TITLE
Jetpack price detection failure if the process has been interrupted

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#65824]
### Objective 
When we agree to install Jetpack, we’ll face a screen that needs our approval before continuing, if we decide to think about it and come back later, the process will be broken with a wrong pricing page, see pcmemI-KN-p2#failure-if-the-process-has-been-interrupted for videos.

**Comment by ouikhuan** [comment]
This is failing due to the user account is not fully connected to the self-hosted site.

**Comment by retnonindya** [comment]
I'm triaging this issue, and it seems like the issue is no longer relevant now that we have updated our site migration flow.

📌 ACTIONS

Closed as could not replicate (please reopen if the issue reoccurs)
