### ISSUE TITLE
Detect “.wpress” uploads

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#65829]
### Objective

Detect “.wpress” uploads at `/import` and recommend them to use Jetpack import if they can, or as a second suggestion, offer them to install “All-in-one WP migration”.

**Comment by vishnugopal** [comment]
Caveats:
- The suggestion for installing All-in-one WP migration can only be done on Atomic sites, so the message should keep that in mind.

**Comment by ouikhuan** [comment]
Related PR #66674

**Comment by ouikhuan** [comment]
This is merged and deployed so I'm closing this issue.
