### ISSUE TITLE
The font getting reset

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#65832]
### Quick summary

The user reached out to us to inform the fonts on their site changed. When tried they aren't able to change it back through Global Styles setting on Site Editor.

### Steps to reproduce

We don't know the exact steps here to replicate, but we're suspecting it is caused due to Blockbase themes since we've got multiple cases using different themes.

On my test site I'm able to replicate that changing the font doesn't save it. Here are the steps I followed:
1. Activate `Antonia` theme on my atomic site.
2. Checked the font from Global Style and it was set to default, showing Times New Roman font family when checked.
3. When changing the font from Global Styles, it doesn't save.

Here is a screencast video showing the saving of the font issue:

https://user-images.githubusercontent.com/7382505/180166193-78aef8d4-2888-4f3b-bc5b-978d4ab573a9.mov

### What you expected to happen

The font family does not change randomly. And when the font is changed it gets saved correctly.

### What actually happened

The font was changed randomly.

### Context

Customer report:

Theme: `Antonia`
Chat: 20702780-hc
Follow up: 5412091-zd-woothemes
Site URL: https://roeartstudio.com/

Some other cases: 
Simple site: p1658376880935749-slack-CJDUN89L1
Atomic site: p1658354145149709-slack-C03TY6J1A

Another simple site: https://ltstrategicstories.com/

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

The issue is replicated on multiple themes:

Quadrat White, Antonia, Blank Canvas, etc.

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

In some cases of atomic sites, deactivating the Gutenberg plugin fixes the issue. On my user's site, deactivating the Gutenberg plugin didn't make any change.

**Comment by happychait** [comment]
Another report for a Simple site to be followed up:

- [x] 5411926-zen
Theme: Antonia

**Comment by edwinho89** [comment]
- [ ] 5411796-zd-woothemes
Meraki theme on simple site

**Comment by marutim** [comment]
36128397-hc

Platform: Atomic
Theme: Quadrat White

Workaround: Deactivated the Gutenberg plugin to fix the font issue

**Comment by maciejpilarski** [comment]
5412634-zen

Platform: Atomic
Theme: Geologist

**Comment by kavyagokul** [comment]
36129454-hc

Platform: Atomic
Theme: Quadrat White
Workarround: Deactivated Gutenberg

**Comment by maciejpilarski** [comment]
36129638-hc

Platform: Atomic
Theme: Attar

**Comment by vajrasar** [comment]
- [ ] 5412470-zd-woothemes

AT / `Attar` theme.

Asking the user to try and deactivate the Gutenberg plugin.

**Comment by upwardmomentum84** [comment]
35861979-hc

Platform: Atomic
Theme: Quadrat White

**Comment by sguzovskaia** [comment]
More reports:
36129463-hc/5413640-zen  | Theme: Attar
25760154-hc | Theme: Zoologist

**Comment by CompChris** [comment]
5413663-zen
Disabled Gutenberg as workaround.

Platform: Atomic
Theme: Quadrat White

**Comment by jp-imagines** [comment]
Another in 36134915-hc. Atomic site, theme: Appleton. Workaround of disabling Gutenberg helped.

- [ ] 5414126-zd-woothemes

Also noting that this user's navigation menu went missing as well (unsure if that was before or after Gutenberg was deactivated). I suspect they originally set it up in the Customizer, and that didn't get ported over with the recent Blockbase update. I _was_ able to add the menu back again from the Site Editor (there was a blank Navigation block, and their "classic" menu still existed to select.)

**Comment by pbking** [comment]
This SHOULD be addressed with [this change](https://github.com/Automattic/themes/pull/6269) which was just deployed.  It's a change to Blockbase and once that version (3.0.1) is pushed to the atomic sites this should no longer be a problem.

Any of those sites noted above where Gutenberg was inactivated to address this issues should be able to re-activate Gutenberg with no adverse effects.

I'm not sure how long it takes once a theme has been deployed before it is available on Atomic sites so the results of this being addressed might not be immediate.

Update: Theme has synced to Atomic sites and I've confirmed things seem to be working as expected on a few atomic sites I have tested noted from above.

**Comment by edwinho89** [comment]
Adding report for visibility: 5414211-zd-woothemes
Checking to see if issue has been resolved.

**Comment by Robertght** [comment]
Another report on 5413305-zen

Theme: Winkel (simple site)

I've asked the user to set it again for now.

**Comment by vajrasar** [comment]
> Adding report for visibility: 5414211-zd-woothemes Checking to see if issue has been resolved.

Edwin, do you still think we need to reach the user here?

**Comment by vajrasar** [comment]
Most of the affected users are informed about the fix, and I informed the remaining. 👍

**Comment by vajrasar** [comment]
> Most of the affected users are informed about the fix, and I informed the remaining. 👍

Additionally updated the following

5491159-zen
5491163-zen
5491168-zen
5491175-zen


---

> 35861979-hc
> Platform: Atomic Theme: Quadrat White

@upwardmomentum84 can you please check this interaction, as I do not see the discussion about the font issue here.
