### ISSUE TITLE
Marketplace: Investigate product description styling in Calypso

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#65842]
## Description
Some Marketplace product descriptions aren't being displayed correctly in Calypso. We should evaluate if we can do anything so that these descriptions are presented in a way that doesn't break the UX.

**Comment by Copons** [comment]
I'm sending this to @Automattic/bespin, it should tangentially fit into the Plugin Details work.
It was an old draft that we had on our board so I'm afraid I don't have more details, but it should be relatively easy to do a quick rundown of the Woo extensions, comparing their descriptions with how they appear on WCCOM.

**Comment by cpapazoglou** [comment]
Is this related to https://github.com/Automattic/wp-calypso/issues/65461?

**Comment by Copons** [comment]
> Is this related to #65461?

Related but not strictly the same.

There is a good example in the screens from that issue though:
<img width="811" alt="Screenshot 2022-07-28 at 15 32 04" src="https://user-images.githubusercontent.com/2070010/181551567-3e0a7d49-4f87-4167-af70-f57bbb74f249.png">

The compatibility warning has a purple background on WCCOM, but it shows as a regular paragraph on Calypso.
I'm pretty sure there will be other cases, since we don't use the same stylesheets.
