### ISSUE TITLE
Theme showcase: Add purchase information in the theme data

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#65857]
We don't have the information on whether a theme was purchased or not. The way we verify if the theme was purchased is very fragile and can lead to problems in the future. To define if a theme was purchased or not, currently, we are checking if the theme has the price information in one place and not in other.
https://github.com/Automattic/wp-calypso/blob/d3a17c226435acd3686dc52324b24f735c26ec2c/client/components/theme/index.jsx#L156
https://github.com/Automattic/wp-calypso/blob/d3a17c226435acd3686dc52324b24f735c26ec2c/client/components/theme/index.jsx#L168-L173
https://github.com/Automattic/wp-calypso/blob/d3a17c226435acd3686dc52324b24f735c26ec2c/client/components/theme/index.jsx#L175-L179

**Comment by mreishus** [comment]
Just verified the behavior:

- Payton = A premium theme I haven't bought, both are theme.price and this.props.price = "$50"
- Skivers = A premium theme I have bought, theme.price is "$50" and this.props.price = ""
- Livers = A free theme, theme.price is undefined and this.props.price = ""

**Comment by mreishus** [comment]
## Current Confusing Implementation

`components/theme/index.jsx` is using the this.props.price to figure out if a theme has been purchased in a confusing way. This is coming from a `getPrice` prop, which is using a `getPremiumThemePrice` selector. This is [specced to return empty string for a theme that is not premium or a premium theme that is purchased](https://github.com/Automattic/wp-calypso/blob/b0513a911ca52dedb220c3839900d460dc22a3a8/client/state/themes/test/selectors.js#L2537-L2592).

This also involves the [ThemeQueryManager](https://github.com/Automattic/wp-calypso/blob/b0513a911ca52dedb220c3839900d460dc22a3a8/client/lib/query-manager/theme/index.js#L8) which is a huge rabbit hole; I recommend not looking too deep into it... 

## More clear alternative

Looking deeper into the implementation of the `getPremiumThemePrice` selector, there is a clearer one that does exactly what we want:

* `isPremiumThemeAvailable`: Checks if the theme itself is purchased or if the unlimited premium themes feature is available

**Selector that checks for individual theme purchase and all premium themes feature** 

https://github.com/Automattic/wp-calypso/blob/b0513a911ca52dedb220c3839900d460dc22a3a8/client/state/themes/selectors/is-premium-theme-available.js#L15-L20


We can also use `isThemePurchased` or `siteHasFeature` if needed.
I believe `<QuerySitePurchases />` loads the purchases data but there's a good chance it's already being included in whatever page we're on.

## One Caveat

!!! I've seen some instances of variables called `isPremiumThemeAvailable` that are not checking the `isPremiumThemeAvailable` selector, which means the purchase data is not being checked.

**Even though the variable is named `isPremiumThemeAvailable`, the individual purchase data is not being checked!**

https://github.com/Automattic/wp-calypso/blob/77109d19959fdc7d49b19d67b83b8fefa42e43d5/packages/design-picker/src/hooks/use-designs-by-site.ts#L15-L20

So we need to be careful and try to fix all of these.
Thinking about it more, this might have a reason for being this way; maybe it's referring to a potential purchase on a new site that isn't created yet, but I do think reusing the same variable name makes it potentially ambiguous as to what it's doing.

## More misleading examples

https://github.com/Automattic/wp-calypso/blob/77109d19959fdc7d49b19d67b83b8fefa42e43d5/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx#L86-L91

https://github.com/Automattic/wp-calypso/blob/77109d19959fdc7d49b19d67b83b8fefa42e43d5/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx#L69-L74

https://github.com/Automattic/wp-calypso/blob/77109d19959fdc7d49b19d67b83b8fefa42e43d5/client/signup/steps/design-picker/index.jsx#L51-L53

In all three of these, the variable is called `isPremiumThemeAvailable`, but the individual purchase data is not being checked.

**Comment by blackjackkent** [comment]
Action item: Audit all uses of `isPremiumThemeAvailable` to make sure that they are also checking if the user has purchased the theme in order to avoid inappropriate upsells.

**Comment by mreishus** [comment]
Overlaps with #65704 some

**Comment by mreishus** [comment]
Some PRs cleaning up the theme card:
  * #66170 
  * #66173
  * #66183
  * #66184

**Comment by mreishus** [comment]
Some PRs for the Unified Design Picker:

* #66187
  * Checks if theme is purchased when browsing the list of designs. Requires sending a list of all purchased themes to the DesignPicker
* #66239
  * Checks if theme is purchased when previewing an individual design. 

Same changes for the Site Setup Design Picker:
* #66279 
  * Checks if theme is purchased when browsing the list of designs. Requires sending a list of all purchased themes to the DesignPicker
  * Checks if theme is purchased when previewing an individual design.

**Comment by valterlorran** [comment]
I'm closing this issue since all the PRs were already merged.
