### ISSUE TITLE
Make Marketplace plugin activation load dependent plugins

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#65858]
In April we changed how Marketplace plugins are activated, to enable dependant plugins when activating a purchased plugin (D78193-code). This was specifically to cater for an issue activating a third party plugin (pdh6GB-zu-p2). 

In May when refactoring this code (D80817-code) this was unwittingly undone - marketplace plugin installation loaded only dependant plugins, but activation ran without any plugins loaded see class-wpcomsh-cli-commands.php#L586 in wpcomsh.

After discussion (pdh6GB-1EV-p2) we decided to restore enabling dependency plugins when activating a Marketplace plugin.

The most straightforward way to achieve this is to split out activation from the symlink command, using the --skip-plugins= argument

**Comment by rcrdortiz** [comment]
Review: 765-gh-Automattic/dotcom-manage
