### ISSUE TITLE
Checkout: Bring customers to onboarding flows after checkout for new sites

### ISSUE THREAD

**Issue by bangank36** [Automattic/wp-calypso#65869]
# Description
This is following tasks for the recent update on post-checkout #65851 

**New sites**: Plans → Checkout → Upsell → Continue site setup onboarding.
**Existing sites doing plan upgrade**: Checkout → Upsell → Thank you page
**Existing sites launching a site upgrade:** Plans → Checkout → Upsell → My home

# Testing Instructions
- Give yourself some credits
- Trigger the upsell flow on new sites and existing sites to check the redirection

# Related
#65773
#65851

**Comment by taipeicoder** [comment]
Closing as it's shipped.
