### ISSUE TITLE
Drafts: should not show latest drafts if no drafts

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#6586]
![](https://cldup.com/anLOd-AsRq.png)

@mcsf noticed an odd line height issue on the empty state messaging for the new pages/posts drafts feature. Really, we should be hiding the "Latest Drafts" list entirely if there isn't at least one draft to show.

#### Steps to reproduce
1. Starting at URL: wordpress.com/posts for a blog with no saved drafts
2. Expand window size to allow for the Latest Drafts sidebar
3. Notice that Latest Drafts shows even if there are no... latest drafts

cc @mtias

**Comment by mtias** [comment]
This seems to be an old screenshot, the line height issue should be fixed in master.

**Comment by mcsf** [comment]
This was taken from the Desktop app, so that would explain it.

**Comment by mcsf** [comment]
Correct; this is via browser:

<img width="339" alt="screen shot 2016-07-07 at 12 56 05" src="https://cloud.githubusercontent.com/assets/150562/16652380/34cac6d0-4442-11e6-8f2b-6535d9ab70ee.png">

Still, I find @meremagee's suggestion to avoid empty states very valid:

> Really, we should be hiding the "Latest Drafts" list entirely if there isn't at least one draft to show.

**Comment by mtias** [comment]
Not sure, it felt awkward to have it switch columns based on whether drafts were present or not. Still undecided. (Also because we want to explore adding a few more things to that third column.)

cc @rickybanister thoughts?

**Comment by mtias** [comment]
The loading states would be awkward — what do we show when we don't know post counts yet? You'll either get a column appearing suddenly, or a column disappearing suddenly.

**Comment by rickybanister** [comment]
I guess it partly depends on the layout of the page. If the drafts column was displayed next to the main column without affecting the layout (nudging the main column over) we could have it appear via transition when the drafts are loaded. This would give us leeway to do other interesting things with that space—if you have no drafts we could show a nice illustration encouraging users to create one, or any number of things.

**Comment by shaunandrews** [comment]
Since we're undecided on showing a blank drafts column or not (I'm on the side of not showing empty useless stuff), can we at least hide it when there are no posts at all? The blank slate looks super awkward with the empty column there.

![screen shot 2016-07-13 at 12 02 53 am](https://cloud.githubusercontent.com/assets/191598/16805257/478df90a-48dd-11e6-8306-e83a1ff867a0.png)

**Comment by meremagee** [comment]
On smaller screens, empty drafts is quite obtrusive:

![](https://cloudup.com/cQZzotIjNgU+)
