### ISSUE TITLE
Store: Create your store button shown upon purchase of eCommerce plan takes users to a broken page.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#65864]
### Quick summary

Upon successful purchase of the eCommerce plan, the post-purchase screen has a single button labelled "Create your store!".

Clicking on this button takes user to a page with the following error:
```
Sorry, you are not allowed to access this page.
```

![Screen Shot 2022-07-21 at 1 55 11 PM](https://user-images.githubusercontent.com/6549265/180315644-7936acf3-7457-4223-ada3-18bfcb035d40.png)

### Steps to reproduce

prereq. add some free credits to user, or enable the store testing sandbox cookie.

1. log in as user.
2. navigate to the `/start` endpoint.
3. select a free .wordpress.com domain.
4. select the eCommerce plan.
5. check out using credits.
6. click on the `Create your store!` button.

### What you expected to happen

User is taken to the screen where they can create their store.

### What actually happened

User is taken to a page with error: Sorry, you are not allowed to access this page.

https://user-images.githubusercontent.com/6549265/180315660-5e9694a0-6df0-457f-8f37-0e53528c5a4e.mov

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari

### Context

Automated and manual testing.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

**Comment by mreishus** [comment]
When purchasing a new ecommerce plan with the sandboxed store, the site is successfully transferred to atomic, but the woocommerce plugin is not installed. 
When purchasing from the real store, woocommerce is installed.
The page it's trying to land on is the woocommerce wizard, so the plugin needs to be active for it to work.

**Comment by worldomonation** [comment]
Closing the issue for now because as noted, the issue is due to WooCommerce not being installed on AT sites when eCommerce is purchased inside a sandbox.

Thanks for @mreishus for the investigation.
