### ISSUE TITLE
Plugins: No results showing up through direct links

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#65872]
### Quick summary

When accessing a direct link, the results are not showing up.

I can see @galakhyati was able to display some results, but I couldn't.

It looks like it may be dependent on if we have the primary site set to an AT site or not.(I didn't have it set)

### Steps to reproduce

1. click on: https://wordpress.com/plugins/manage?s=Multilingual
2. Check if you get any results

### What you expected to happen

To see some results

### What actually happened

I saw nothing

![image](https://user-images.githubusercontent.com/6737345/180383813-2659cf20-81d7-46c0-8bdb-b3e35060cfa4.png)

### Context

p1658472817575789-slack-C03TY6J1A 

I also notice we reference this here: https://wordpress.com/support/set-up-a-multilingual-blog/

This could affect potential buying users from getting their website done.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

no

### Browser, operating system and other notes

Chrome

### Reproducibility

Intermittent

### Severity

Some (< 50%)

**Comment by obenland** [comment]
Do you have a site that has that plugin installed? If not, it will show the blank screen (which is not great, but expected).
So the direct link depends on the user having at least one site with that plugin installed.

**Comment by cometgrrl** [comment]
Perhaps we should reframe this bug to update the support document? Is there a direct link to the plugin that would allow users to add the plugin to their site? It seems that's the intent of the current link from the support document.

**Comment by jordesign** [comment]
As this is a docs issue - I've closed this issue in favour of 1659-gh-Automattic/en.support-docs-content
