### ISSUE TITLE
[New Comment] Reply-to email address is missing in certain circumstances

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#65884]
The new "New Comment" email template is missing `reply-to` address. Please see the screenshots below for comparison:

| Current email template | New email template |
| ------------- | ------------- |
| ![Image](https://user-images.githubusercontent.com/25105483/180441237-93188076-f36a-4a52-8a5b-9eeb9d6b3b01.png) |  ![Image](https://user-images.githubusercontent.com/25105483/180441238-d420cec3-0ccf-47cd-bbb2-6059c6c4d24b.png) |

**Comment by ivan-ottinger** [comment]
The issue doesn't seem to be related to the new email template:

![Image](https://user-images.githubusercontent.com/25105483/184670539-55cc9d5c-8ece-4aab-a2a8-d8dd76a8438a.png)

Instead, it looks like it is related to the email address of the recipient. I will investigate further.

**Comment by ivan-ottinger** [comment]
The "Reply-To" email address is missing when the recipient email address is longer than 33 characters. This is because the generated "Reply-To" email address is too long to be considered valid and is omitted from the email.

Investigation details: pdDOJh-DX-p2.

**Comment by ivan-ottinger** [comment]
The D86000-code patch that hides the tip in the new _New Comment_ email template when the "Reply To" email address is not valid, is ready for review.

The patch won't fix the underlying issue, but will make sure there isn't confusion that could come from displaying the feature tip when the feature isn't available.

The underlying issue will be addressed as a part of maintenance.

**Comment by ivan-ottinger** [comment]
The D86000-code patch is now deployed to production.

I am leaving this issue open and moving it to maintenance - as the root cause hasn't been addressed yet. Possible next steps can be found in the following discussion: pdDOJh-DX-p2#comment-470.

**Comment by ivan-ottinger** [comment]
Just a quick observation: It looks like the issue is not present in the New Comment email notification sent to the **post author**. Therefore, the check of the "reply-to" email validity isn't necessary there: D86564-code.

issue is still present in New Comment email notifications sent to **followers**.

**Comment by JuanLucha** [comment]
I tried to reproduce this following these steps:
1- Create a new site with user A.
2- Following the site with user B.
3- User B activates "Email me new comments" in the notification settings of the new site.
4- User A creates a new post.
5- User A comments on that new post.

The result is the user B receiving the "[Site Title] User A commented on The New Post" email, but the reply-to field of the email was filled.

@ivan-ottinger  if you are able to reproduce, please tell me more about the steps you followed. 😄

**Comment by ivan-ottinger** [comment]
Thanks for checking, Juan! Have you tried with the long email address though? (as described in pdDOJh-DX-p2 from the [comment above](https://github.com/Automattic/wp-calypso/issues/65884#issuecomment-1216759349))

**Comment by TimBroddin** [comment]
The workaround is fine!
