### ISSUE TITLE
Move WooCommerce_Host_Service to lib/woocommerce-services

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#65898]
Since `WooCommerce_Host_Service` is now being used by the Atomic and Marketplace libraries makes sense to copy that class into `lib/woocommerce-services` and point them both libraries and tests to the relocated class.

Also, extend the abstract class `WooCommerce_Host_Manager` from `WooCommerce_Manager` and remove the overridden methods `get_customer_data` and `get_site_url`.

**Comment by obenland** [comment]
Step 1: D86606-code

**Comment by JulianBustamante** [comment]
Step 2: D87225-code

**Comment by JulianBustamante** [comment]
Deploy step 2: r252128-wpcom

**Comment by JulianBustamante** [comment]
Step 3: D87344-code

**Comment by JulianBustamante** [comment]
Deployed final step 3: r252376-wpcom

**Comment by obenland** [comment]
Thank you!
