### ISSUE TITLE
Social Auth: `calypso_login_success` unexpectedly dispatched with `social_service_connected: false`

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#65897]
From https://github.com/Automattic/wp-calypso/pull/65865#issuecomment-1192501071

When logging in with Google, the `calypso_login_success` event is unexpectedly dispatched with `social_service_connected: false`:

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/36432/180481584-7ffb1fc5-1ded-4274-b43e-84e1fb8fe203.png">

`socialConnect` is somehow incorrect here:

https://github.com/Automattic/wp-calypso/blob/d2e27c7b2f8120cdd7861fe37bacc41921428f97/client/blocks/login/index.jsx#L194-L198

**Done is:**
* The `social_service_connected` has the correct value (which I believe should be `'google').

**Comment by zaguiini** [comment]
It has the correct value... `social_service_connected` in this context means a login from the `/social-connect` endpoint, so this is working as expected, though with a not-so-nice name. cc @danielbachhuber you can close this if you want or let me know if you want to rename it.

**Comment by danielbachhuber** [comment]
@zaguiini Nah, keeping the prop as-is works fine for me.
