### ISSUE TITLE
Marketplace: Jetpack Search shows as Inactive

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#65904]
Jetpack Search shows as installed but inactive in the Plugins Browser. Tested on Simple and Atomic.

<img width="526" alt="Screen Shot 2022-07-22 at 4 00 39 PM" src="https://user-images.githubusercontent.com/1689238/180569299-fe7f8166-f6a8-496b-a0b5-145c609c212c.png">

**Comment by allilevine** [comment]
@Copons Is this already covered somewhere?

**Comment by Copons** [comment]
@allilevine yes, covered by https://github.com/Automattic/wp-calypso/pull/65252
Thanks for reporting though, I'll mention this issue in the PR 🙂
