### ISSUE TITLE
Marketplace: Jetpack Search isn't the first result for Jetpack Search

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#65903]
When searching for "Jetpack Search" via the /plugins browser, it's the 11th result:
<img width="1095" alt="Screen Shot 2022-07-22 at 4 53 44 PM" src="https://user-images.githubusercontent.com/1689238/180567051-56477265-808e-4aaa-b1f2-ea4d6cea49ef.png">

It should be the first result, or at least in the top 5.

**Comment by lsl** [comment]
It's 4th result now, might be something that just needs a bit of time to rank up. Closing to save you a click but re-open if this is something you think needs further attention.
