### ISSUE TITLE
Themes: Tags are getting out of sync

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#65900]
Sometimes Theme tags get out of sync between theme.wp.com and what is on their `style.css`. This causes problems particularly in the home replacement process that's triggered from the "Activate" modal.

It would be good to have a bot that checks the differences and automatically reports.

This is the thread that triggered this discussion: p1658506665291069-slack-C0Q664T29.

**Comment by andres-blanco** [comment]
A possible & simpler fix is to see if we can remove the check for tags from the `style.css` in the homepage replacement process. For this to be possible all current themes should have a homepage available.

**Comment by valterlorran** [comment]
Discussion related to this here: p1660919145446239-slack-C029FM1EH

**Comment by markbiek** [comment]
I've started an MC page to call out themes that have mismatches. Details in paYKcK-2a8-p2

**Comment by markbiek** [comment]
New MC page has launched: `/themes/tag-check/`
