### ISSUE TITLE
Attar theme: Slideshow Block not Displaying on the Live Page

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#65917]
### Quick summary

On a site with the Attar theme, a slideshow block will only be visible on the editor and not the live page. When refreshing, it will briefly show the images and will display blank. 

### Steps to reproduce

1. Activate the Attar theme.
2. On a page, add a slideshow block and publish.
3. View the page editor and live page. 

### What you expected to happen

The slideshow block will be visible in both the editor and live page on the Attar theme.

### What actually happened

The slideshow block is only visible in the editor and not the live page on the Attar theme.

### Context

- Customer report: 5415715-zen and self-testing. 

### Slideshow block in the editor: 

<img width="1661" alt="Screen Shot 2022-07-24 at 3 01 49 PM" src="https://user-images.githubusercontent.com/36863633/180648216-47c709e6-4bc0-4e0a-a872-d6fa935f30d4.png">

---

### Live page: 

![Screen Shot on 2022-07-24 at 15:02:06](https://user-images.githubusercontent.com/36863633/180648223-7f39bde6-8e9d-4f95-9e61-6b108618d40b.png)

---

###  When refreshing, it will briefly show the images in the slideshow then will display blank. 

![Screen Capture on 2022-07-24 at 15-05-38](https://user-images.githubusercontent.com/36863633/180648409-914435c5-cb66-4bc4-bd34-8170e2bc5aaf.gif)

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Attar

### Browser, operating system and other notes

MacOS 12.4, Firefox 102

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Use another block that displays images on the Attar theme. Or change to another theme.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can confirm the issue occurs when the block is inside the editor and not when it's added in a single page or psot.
- This is a known issue with FSE and the Slideshow block as discussed here:
https://github.com/Automattic/themes/issues/6081
https://github.com/Automattic/jetpack/issues/22834

The slideshow will create a huge width in this case.

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/themes/issues/6081
