### ISSUE TITLE
TEXT error regarding the plan features description upon attempting to purchase a plugin on a simple site

### ISSUE THREAD

**Issue by DavidSaladu** [Automattic/wp-calypso#65914]
### Quick summary

When trying to purchase a plugin on a simple plan, the system states that we will need to upgrade the plan (ok until here).

On that area, asides from the plugin price, and what it includes, there’s a small snippet of the plan that will be needed (business) it’s cost, and some of its features. the problem is that the plan features list is the same (and includes free domain) wherever the price is selected annually or monthly, while our monthly paid plans don’t include a free domain.

It can be seen more clearly here:

![Screen Capture on 2022-07-23 at 23-32-37](https://user-images.githubusercontent.com/79575219/180623643-cd8090ee-0087-4188-9e44-1c63f61c97dc.gif)
.

### Steps to reproduce

1. Access a simple site
2. Select a plugin to purchase
3. It will prompt the user to pay a price to upgrade the plan to business (in order to have plugins) and will show the price and some of the plan features.
4. The first feature will be free domain for the first year wherever the monthly or the annual payment are selected

### What you expected to happen

When the monthly payment is selected the free domain for the first year shouldn't appear. 

### What actually happened

The plan features show the Free domain for one year while being paid monthly which can be a bit misleading:

![image](https://user-images.githubusercontent.com/79575219/180623738-b614fbd0-ac91-4850-9196-58f73e72e45f.png)

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No, it seems to happen with all themes tested.

### Browser, operating system and other notes

MacOs Monterrey 12.3.1
Google Chrome Version 103.0.5060.114 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - N/A

📌 SCRUBBING
- Tested on P2 - N/A 
- Tested on Simple ✅ 
- Tested on AT - N/A
- Tested on Self-hosted - N/A 

📌 FINDINGS/SCREENSHOTS/VIDEO
- It looks like this may have been updated. I cannot recreate. This is the copy I see now:

<img width="1060" alt="Screenshot on 2022-07-28 at 22-15-50" src="https://user-images.githubusercontent.com/30788962/181681955-353e4eca-c7dc-4b6e-ac68-a5bb0c63b561.png">

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
