### ISSUE TITLE
Possible to deactivate Jetpack via dev tools

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#65915]
### Quick summary

Apparently Elementor Support found a workaround to deactivate Jetpack via a change to attributes using dev tools. They've suggested this workaround to at least one user (HE already helped user resolve by finding the actual problematic setting in Elementor)

This is not something that is likely to affect many users due to knowledge required but it still shouldn't be allowed

### Steps to reproduce

1. Go to installed plugins page
2. check box next to Jetpack/Akismet
3. Inspect apply button for bulk actions
4. Change Bulk Actions options value to deactivate-selected
5. Apply change

### What you expected to happen

They shouldn't be able to deactivate Jetpack from the front end in any way

### What actually happened

They can deactivate Jetpack, breaking site features

How it's set:
![2022-07-24 at 10 02](https://user-images.githubusercontent.com/47717887/180636348-801269cd-f8bc-40bd-8171-e3ccb001fa21.jpg)

Requires change to:
![2022-07-24 at 10 02](https://user-images.githubusercontent.com/47717887/180636354-b8f600b3-043c-4e76-b596-4f9ca137083f.jpg)

### Context

Was mentioned in slack here: p1658642191948719-slack-C03TY6J1A

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

**Comment by jamiepalatnik** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 

📌 SCRUBBING
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this. It is possible to deactivate Jetpack by using browser dev tools to change that option value `-1` to `deactivate-selected`.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by jeherve** [comment]
That's a nice little trick, and maybe something the Atomic team should look at. @jmdodd What do you think of this? Should the platform somehow re-enable platform-managed plugins that get disabled with tricks like that?

**Comment by obenland** [comment]
We could block this by filtering the `deactivate_plugin` capability and checking if the passed plugin is in the disallow list.
