### ISSUE TITLE
Unified design picker: Tailored UI based on intent (Write  & Build flow)

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#65924]
## Description
Current, the unified design picker is available in the Build and Write flow. It's likely that we will want to introduce it eventually in the Seller flow, as well. As of now, the unified design picker has the following behavior:
"Out of the three generated designs, it randomly selects one Blog design, one Portfolio design, and one Business design."

While this works for a more generic flow such as the Build flow, we can provide a more tailored experience for the Write flow.
"Out of the three generated designs, we randomly show three Blog designs."

And we would follow the same logic for the Seller flow.
### Dev tasks
- [x] Update query params to accept `site intent` value
- [x] Update returned values for Write flow 
- [x] Update returned values for Seller flow
## Acceptance Criteria
- [x] The unified design picker should show different generate design layouts according to the site intent.

**Comment by bangank36** [comment]
Closed as landed 🛬
