### ISSUE TITLE
Customizer: Widgets with slideout settings don't display correctly on small-screen mobile devices

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#6593]
#### Steps to reproduce
1. On a mobile phone, starting at URL: https://wordpress.com/customize
2. Select a site and go to Widgets > select a widget area
3. Add a "Follow Blog" widget (or other widget with slideout settings)
4. Open the widget settings

#### What I expected

Be able to edit the Follow Blog widget settings.

#### What happened instead

The Follow Blog widget settings pop out to the side, not below. So I can't see the entire form and it makes it difficult to modify the widget.

#### Browser / OS version

Originally reported in the WP Android app on Nexus 6P, Android 6.0.1.
Tested for Calypso web in Mac OS X 10.11.5, Chrome 51.0.2704.103, using the Nexus 6P emulator. 
Also tested on iPhone 6, iOS 9.3.2, Safari.

#### Screenshot / Video

![screen shot 2016-07-07 at 12 08 29 pm](https://cloud.githubusercontent.com/assets/8658164/16651391/91b0ea8e-443b-11e6-83c4-c6f2e1341466.png)

#### Context / Source
h/t @shawnajean for the original report: https://github.com/wordpress-mobile/WordPress-Android/issues/4293

**Comment by lancewillett** [comment]
This isn't Calypso specific, so I moved to Customization bug list.
