### ISSUE TITLE
[New Liked Comment] Add link descriptors in the old email template

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#65933]
### Details
In order to collect metrics before the rollout we need to introduce link descriptors on all links and buttons for the old template. Similar links should reuse link descriptors defined for the new template on #65709.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/3113712/180325979-5fa24fed-577f-4f14-856a-3a772f26f5b0.png">

### Links List
- Post Title
- View Comment
- Email Notification Settings
- Trouble clicking? URL (same as Email Notification Settings)

### Checklist
- [x] Include data-tracks-link-desc on all links
- [x] Verify if the descriptors is available in the URL event data

**Comment by mashikag** [comment]
✅ Done: D84839-code
