### ISSUE TITLE
[Bug]: Gutenberg CORS error

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#65954]
### Quick summary

Currently when you visit https://jetpackme.wordpress.com/wp-admin/post.php?post=121138&action=edit page.
You see a CORS Error in the FF browser. 

See
<img width="1135" alt="Screen Shot 2022-07-25 at 5 11 43 PM" src="https://user-images.githubusercontent.com/115071/180895618-bf7ef636-cbb7-4ef7-aefb-f89ef583e10a.png">

Also note that this endpoint currently doesn't exits on public-api. It return a 404 error. There is some site mapping that is currently missing. 

### Steps to reproduce

In FF visit https://jetpackme.wordpress.com/wp-admin/post.php?post=121138&action=edit  
Notice that the editor doesn't load as well as the error in the developer console 

### What you expected to happen

For the editor to load as expected. 

### What actually happened

The editor didn't load. 

### Browser

Mozilla Firefox

### Context

Dogfooding. 

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

**Comment by mreishus** [comment]
There's an undeployed fix for this in D84902-code.

**Comment by markbiek** [comment]
@enejb I've tested and approved that diff.

**Comment by david-binda** [comment]
The above mentioned fix ( D84902-code ) has been deployed. I'm going to close the issue, but feel free to re-open if needed.
