### ISSUE TITLE
[Bug]: Annual discount percentage is inconsistent between Plans page and checkout

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#65969]
### Quick summary

When you go through the process of buying a plan, the Plans page shows you an annual purchase discount that is slightly different from the number shown later during checkout (for example, 43% on the Plans page vs. 42% during checkout, for the Premium plan).

**Plans page:**

![plans-page](https://user-images.githubusercontent.com/235183/181011179-07307973-7a12-4dcc-9273-cd493e456d95.png)

**Checkout:**

![checkout](https://user-images.githubusercontent.com/235183/181011177-dc1ab5a6-9ab6-426d-b482-158b7473d8f5.png)

### Steps to reproduce

1. Either sign up for a new site and choose a plan (e.g. Premium), or purchase a plan for an existing site starting at https://wordpress.com/plans.
2. Continue through to checkout.

### What you expected to happen

The quoted percentage discounts to be consistent.

### What actually happened

The quoted percentage discounts were not consistent.

### Reproducibility

Consistent

**Comment by michaeldcain** [comment]
From planning:

We should use `floor()` and round down, since we're technically not providing them 43%.

**Comment by spraveenitpro** [comment]
The premium plan says that it is saving 56% by paying annually:

![LHAOoJ.png](https://user-images.githubusercontent.com/552016/230482364-d672c2fb-8ac5-49bc-b17c-024eaab15d8f.png)

But the annual payment for the premium plan is $216, which means:

![LPqpkx.png](https://user-images.githubusercontent.com/552016/230484041-c39a1199-b649-406c-8d03-04ae188eef2a.png)

This means it is 55% that is saved by paying annually, rounding down from 55.5%

Similarly for personal plan:

![HYA8Tm.png](https://user-images.githubusercontent.com/552016/230486053-b94ecb52-6005-49e7-a1d1-331d3d384214.png)

The annual payment for personal plan being $48 which means:

![it4GtK.png](https://user-images.githubusercontent.com/552016/230486765-953e897a-6452-4f86-9c16-6d3bd898ea41.png)

For Biz plan:

![40kdQ8.png](https://user-images.githubusercontent.com/552016/230487968-bc3468b2-84bb-4da6-8d98-b557252b4dc8.png)

For Business plan it is 37.5% but shown as 38%:

![LzfrMz.png](https://user-images.githubusercontent.com/552016/230487258-cf67d164-3208-4a7d-a0e7-fdccb5494f3d.png)

So I think it does make sense to round down as like you said `we're technically not providing them 43%.`  [now 56%]

@michaeldcain

**Comment by michaeldcain** [comment]
https://github.com/Automattic/wp-calypso/pull/75416 looks good to me. I moved it to reviewed and will return this to In Progress, pending your investigation into whether or not the Checkout variant picker needs any updates.

**Comment by spraveenitpro** [comment]
> #75416 looks good to me. I moved it to reviewed and will return this to In Progress, pending your investigation into whether or not the Checkout variant picker needs any updates.

The Variant picker looks good based on my investigation. 

![kzJadR.png](https://user-images.githubusercontent.com/552016/232118814-19dd961b-6dbf-4f01-b1fe-f2e44398fd12.png)
