### ISSUE TITLE
[Bug]: Site's user edit form throws error in the console

### ISSUE THREAD

**Issue by wojtekn** [Automattic/wp-calypso#65970]
### Quick summary

When I edit the site's user, I see a JS error in the console:

> react-dom.development.js:67 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components

It says it' warning, but it is thrown as an error. 

### Steps to reproduce

1. Start local calypso
2. Open any site
3. Navigate to Users and edit a user

### What you expected to happen

There is no error displayed in the JS console.

### What actually happened

Error "Warning: A component is changing an uncontrolled input to be controlled." is shown.

![Screen Shot 2022-07-26 at 15 01 18](https://user-images.githubusercontent.com/727413/181016615-87e81fb5-d3c1-4395-b703-ab45b4ef8abb.png)

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Other notes

I reproduce it in local Calypso, and I can't reproduce it in WPCOM.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by cuemarie** [comment]
@wojtekn This report was found in a backlog sweep.  Did this stem from a user interaction or internal request for assistance? Do you still feel this needs addressing, or was a resolution found outside of this report?  

Thanks for providing additional context.

**Comment by wojtekn** [comment]
@cuemarie I can't reproduce it anymore.

I see we've changed how we save the form in https://github.com/Automattic/wp-calypso/pull/71720, and I think it fixed the issue.
