### ISSUE TITLE
[Bug]: "Discount for first year" no longer appearing in checkout

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#65972]
### Quick summary

When you get a single-term discount during checkout, there should always be some kind of message displayed next to the crossed-out price to indicate that, usually something like "Discount for first year".  The purpose of that is to make clear that the price you're paying now is lower than the price you will pay on future renewals.

Somewhere along the way, a regression happened and this discount is no longer being displayed in many cases.

For example, when upgrading from a Premium plan to a Business plan, it used to look like this:

![checkout-discount-before](https://user-images.githubusercontent.com/235183/181043324-7a11f715-b6fe-4662-842c-8bacf56a62cc.png)

But now it looks like this:

![checkout-discount-after](https://user-images.githubusercontent.com/235183/181043319-014174ca-1332-464f-bdef-babdd19b679b.png)

I think the bug might be here:
https://github.com/Automattic/wp-calypso/blob/77597bde18af562a8de70016b14dfb18d0cb75e4/packages/wpcom-checkout/src/checkout-line-items.tsx#L682

`product_cost_integer` may be the wrong thing to check since it doesn't include the discount.  Possibly `item_subtotal_integer` is better, although this needs more research, and it's not clear to me when the behavior changed either.

### Steps to reproduce

There may be more than one way to reproduce this, but the simplest is:
1. Buy a plan (for example, a Premium plan).
2. From the Plans page, choose a higher plan to upgrade to (for example, a Business plan).
3. In checkout, look at the price that is shown.

### What you expected to happen

To see a "Discount for first year" or similar message next to the crossed-out price.

### What actually happened

There was no message displayed.

### Reproducibility

Consistent

**Comment by sirbrillig** [comment]
D82241-code was the cause. Working on a fix.

**Comment by sirbrillig** [comment]
Related, it turns out that some shopping-cart endpoint product properties are incorrect: 1048-gh-Automattic/payments-shilling
