### ISSUE TITLE
Social Auth: Create funnels for and document new Tracks events

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#65995]
In #65865 and #65911, we added new Tracks events to track progress on the Google and Apple auth flows:

* log in (`/log-in`);
* sign up (`/start/user`);
* account linking (`/me/security/social-login`).

We should make sure they're appropriately documented.

**Done is:**

- ~~[ ] We have Tracks funnels for each of the primary flows.~~
- [x] We have a Field Guide page documenting each Track event for each flow, and linking to the funnels.
- [x] Any feedback on the documentation is applied.
- [x] The documentation is noted on the existing P2 thread.

**Comment by danielbachhuber** [comment]
@vindl Here's my first pass at `Google and Apple Social Auth Tracks Events` documentation: PCYsg-JCl-p2

Couple of questions:
1. Can you let me know if there's anything you'd add to or change about the documentation?
2. Which funnels would it make sense to add? Personally, I think the events are useful enough on their own; I'm not sure if funnels are necessary.

Thanks!

**Comment by vindl** [comment]
@danielbachhuber

1. The documentation LGTM.
2. No need to create funnels, for now, let's observe the events as you suggest. If needed, I'll create some funnels after we get a couple of weeks' worth of data.

**Comment by danielbachhuber** [comment]
@vindl Sounds good, thanks!
