### ISSUE TITLE
[Bug]: Email digest not being delivered

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#66009]
### Quick summary

A user reported that they received a weekly digest subscription containing posts from around two months of content -- previous digests were not sent to the user.

### Steps to reproduce

The steps to reproduce aren't clear, as the user just noticed their overfull (and overdue) email when it arrived after the long interval.

### What you expected to happen

The user should have received weekly digests each week.

### What actually happened

The user received all of the content in a single digest email after not receiving a digest for multiple weeks.

Some additional details are reported in this internal Slack message: p1658893574738309-slack-C029GN3KD

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Intermittent

### Severity

Some (< 50%)

**Comment by daledupreez** [comment]
I did some investigation into this last week, and it seems that the biggest volume of issues stem from two sources:
1. Errors from Emogrifier, a library we use to inline CSS styles, but where we are running an out of date version.
2. Errors due to memory exhaustion (which may or may not be triggering the errors above)

I'll keep looking into this over the course of the week, firstly by exploring whether we can upgrade the Emogrifier library without major issues, and by exploring whether we can flush our caches more aggressively.

**Comment by cometgrrl** [comment]
@daledupreez I believe this is fixed by this D82387-code.

**Comment by daledupreez** [comment]
Thanks, @cometgrrl!

I was waiting for today to see what happened to my personal set of subscriptions, and things are looking _really_ good. I had some big backlogs that got cleared, which suggests the change worked for a number of subscriptions that had been failing for some time.

I am going to close this issue as a result.
