### ISSUE TITLE
Whatsapp icon changes in generic icon when whatsapp link is added

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#66010]
### Quick summary

Using the social menu in the theme Karuna displays a Whatsapp icon in the demo but it changes to the chain icon when a Whatsapp number is added instead of whatsapp.com.

### Steps to reproduce

Open a site, activate the theme Karuna
When the theme is activated and the social menu is displayed it also shows a Whatsapp icon. 
![Markup 2022-07-27 at 11 19 22](https://user-images.githubusercontent.com/5507879/181211853-b91952c1-397f-49ac-9c3a-045cf404a531.png)
 When replacing the Whatsapp.com link with a phone number link the Whatsapp icon disappears and a chain icon appears
![Markup on 2022-07-27 at 11:23:29](https://user-images.githubusercontent.com/5507879/181212147-570a4eba-5338-43a4-b096-2a51796fcb27.png)
 

### What you expected to happen

I expected the icon to display the same when the whatsapp.com url was replaced with the phone number link

### What actually happened

The icon changed to a chain icon

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Only happens with theme Karuna. 
I also tested some other themes with the social menu option (Canard, Blask, Rowling) but they show the chain icon regardless of what the URL is in the menu. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by dcoleonline** [comment]
- [ ] 5427608-zen We should reply here once this is resolved.

**Comment by renata-franco** [comment]
📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 
- 
------

📌 FINDINGS/SCREENSHOTS/VIDEO

I could not replicate this on Simple or AT sites. When adding the Social Media menu the WhatsApp link does not appear there by default. When adding a Custom Link in the Social Media menu going to My Site → Appearance → Menus, it shows the link. For example, I added a link to `google.com` and it showed a Google icon. When adding a WhatsApp link, it showed the icon for that. I tried changing the link to another number and it was still there. 

Please note that the link for WhatsApp looks like this: 

`https://api.whatsapp.com/send?phone=PHONE_NUMBER_WITH_INTERNATIONAL_CODE`




------

📌 ACTIONS

- Closed as could not replicate (please reopen the issue reoccurs)
