### ISSUE TITLE
Biyearly plan price shows incorrectly on the Purchases page.

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#66025]
### Quick summary

User reports (5426144-zd-woothemes) that the BiYearly plan shows up incorrectly on the https://wordpress.com/purchases/subscriptions/ page, or at the https://wordpress.com/me/purchases page.

The plan is Biyearly, and it shows US $84/ year. $84 USD is the biyearly Personal plan cost. It should say $42 / year or $84 / 2 years.

![CleanShot 2022-07-27 at 21 09 02](https://user-images.githubusercontent.com/84539773/181354157-9143d4ba-cf92-4522-9dad-6936463f0f18.jpeg)

The subscription shows up correctly on the Receipt:

<img width="887" alt="CleanShot 2022-07-27 at 21 19 23@2x" src="https://user-images.githubusercontent.com/84539773/181354503-9ae46749-2b6e-47f8-b634-570568119d97.png">
 

### Steps to reproduce

1. Add biyearly plan
2. Visit ttps://wordpress.com/purchases/subscriptions/ page, or the https://wordpress.com/me/purchases page.

### What you expected to happen

The price would reflect the length of the plan.

### What actually happened

It is misleading a little.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

**Comment by annbingle** [comment]
Same report here 34800445-hc

<img width="1019" alt="Screen Shot 2022-07-30 at 21 22 22" src="https://user-images.githubusercontent.com/40605613/181916379-84267e2b-2a30-46ad-9fa1-670f8b0fee47.png">

<img width="1023" alt="Screen Shot 2022-07-30 at 21 22 46" src="https://user-images.githubusercontent.com/40605613/181916382-46790fec-9625-4411-ab1f-7842e1339969.png">

**Comment by Joshgrygiel** [comment]
📌 SCRUBBING
- Tested on P2 - N/A
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - N/a
- Replicable on Core - N/a

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to verify that the price label for bi-annual plans is indeed displaying the incorrect price per year:

![Annotation on 2022-08-02 at 15-31-47](https://user-images.githubusercontent.com/88345647/182467822-8b8fe08c-2470-4719-a5f2-6a9a8cdee534.png)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by DavidRothstein** [comment]
Also being discussed here: 1095-gh-Automattic/payments-shilling

**Comment by sirbrillig** [comment]
Should be fixed by https://github.com/Automattic/wp-calypso/pull/67021
