### ISSUE TITLE
Blogger importer: the progress bar should not overlap with the status text

### ISSUE THREAD

**Issue by jimmy319** [Automattic/wp-calypso#66036]
**Issue:**

The progress bar should not overlap with the status text like this:

![Image](https://user-images.githubusercontent.com/1024985/181441674-de479850-b4f4-4c41-8908-bd69c5667c5e.png)

**Comment by jimmy319** [comment]
I've tried to reproduce this bug but it works well on my end (see screenshots below). @vishnugopal could you test it to see if this bug still persists on your end when you have time?

PC

![Image](https://user-images.githubusercontent.com/1024985/181741231-82604bc5-1e85-4458-be5c-719abb4385f5.png)

Mobile

![Image](https://user-images.githubusercontent.com/1024985/181741309-a86074d5-2771-425f-b5f4-6d2a63c818d7.png)

**Comment by vishnugopal** [comment]
Agreed, seems to be working fine now, must have been a niggle! Closing!
