### ISSUE TITLE
Marketplace: copy check sensei pro JITM

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#66034]
The Sensei Pro JITM needs more context. "More with Sensei Pro" is kind of meaningless as far as sentences go. Could we explain what more you'll get with this plugin?

For context, the Yoast spotlight uses "Drive more traffic with Yoast SEO Premium."

![Screenshot 2022-07-28 at 15-01-26 Plugins ‹ Site Title test — WordPress com](https://user-images.githubusercontent.com/811776/181424441-6608e50a-2b87-4747-af2d-9a2c4768e89a.png)

Acceptance
- [ ] Add context to the JITM copy in `jitm-engine.php`

**Comment by cpapazoglou** [comment]
Patched in D97511-code

**Comment by cpapazoglou** [comment]
Deployed r259145-wpcom
