### ISSUE TITLE
Marketplace: Order top paid and browse paid plugins by sales

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#66033]
We won't be able to order these properly by real sales data for a while. (Until the ES integration is complete and sales data is feeding into it.)

In the meantime we'd like to prioritize ordering paid plugins by sales data to make sure the most popular plugins are being surfaced to users as early as possible.

The current order determining what plugins show up in the paid section first is controlled by the order in which things are being added to the products array in `class-marketplace-product-catalog.php`.

To re-arrange the order of plugins on the front end you just need to pick the order of functions called in the `__construct`.

_Testing note:_ these particular `public-api.wordpress.com` responses are cached by calypso, you'll need to delete calypso's indexdb data to get the list to refresh after changing things on your sandbox.

Context:
p1658945343153799-slack-C029JEQRVRT

Acceptance
- [ ] Order top paid plugins by [sales data.](https://github.com/Automattic/wp-calypso/issues/66084#issuecomment-1201339432)

**Comment by yashdev9274** [comment]
hello Louis Laugesen is this issue still open

**Comment by lsl** [comment]
Hi @yashdev9274, yes still open but it's something we need to change on the backend, sorry if you were looking for something to start on in calypso!

**Comment by yashdev9274** [comment]
is there any beginner friendly issues you know I can contribute to...

**Comment by yashdev9274** [comment]
I am new to open source and haven't done any commits yet

**Comment by yashdev9274** [comment]
so if there are please let me know

**Comment by allilevine** [comment]
@lsl @candy02058912 Does this need review of D85273-code?

**Comment by candy02058912** [comment]
Deployed with @lsl today.
After screenshot:
![image](https://user-images.githubusercontent.com/6586048/182760769-83fc7338-4139-476c-a0d1-1c65946a0367.png)

**Comment by lsl** [comment]
@yashdev9274 are you looking to get started with WordPress open source in general or specifically WordPress.com's wp-calypso? Just want to clarify because this repo (wp-calypso) is the open source repo for WordPress.com's logged in user interface. It's possible you're looking for the .org repo which is using a system called trac instead of github. (Some people land here by mistake from Google)

There is a list of open tickets that need open source contributions in [trac](https://core.trac.wordpress.org/tickets/no-patch). For example, [this one](https://core.trac.wordpress.org/ticket/53976) might be a good one to start with. I'd start by reading [this page](https://core.trac.wordpress.org/) first too.

You can join the [.org slack](https://make.wordpress.org/chat/) if you'd like to chat with people in the community as well.
