### ISSUE TITLE
[All] Fix font-size inconsistency in the email templates on mobile

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66041]
There seems to be a font-size inconsistency between links and normal text in the new email templates on mobile:

|   |  |
| ------------- | ------------- |
| ![Image](https://user-images.githubusercontent.com/25105483/181465154-69183e27-258c-40b8-af48-351994317471.jpeg) |   ![Image](https://user-images.githubusercontent.com/25105483/181465155-620480fc-a792-4709-9a37-da4ca66ec141.jpeg) |

Reproduced on iOS Gmail app.

Link to comment where the issue was discovered: D84748-code#1773634.

**Comment by ivan-ottinger** [comment]
Were you able to reproduce the issue on your end, Juan? 🤔  Because when I was adjusting the iOS settings today, it looks like the issue might be not related to our templates after all.

Instead, I suspect the issue could be related to the Gmail app and specific font-size setting in iOS. Because when I restore the default font settings in iOS, the links in the email template get back to the normal size - as the rest of the email copy.

Example:

![Markup on 2022-08-01 at 10:46:23](https://user-images.githubusercontent.com/25105483/182110245-ae8d5e28-1a1d-443f-ae11-e6d66eea5cfe.png)

This would also explain why we haven't received any issue reports.

**Comment by yansern** [comment]
I can confirm the font size inconsistencies only appears on the Gmail app when Text Size is increased on iOS. On Mail app, all the text size increases together. Attaching screenshots.

That said, I don't think this is something we should bother fixing. Perhaps Gmail itself need to fix this. Let's close this issue then.

| Mail | Gmail |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1287077/182174921-be752fe9-45b9-4b69-89e1-d8482a9c4c4f.png) |  ![image](https://user-images.githubusercontent.com/1287077/182174960-d487e606-f0cb-4b57-9f47-8831b5b0c57b.png) |

**Comment by ivan-ottinger** [comment]
Thanks for testing this Yan.

> That said, I don't think this is something we should bother fixing. Perhaps Gmail itself need to fix this. Let's close this issue then.

Yes, it looks like Gmail-app-related issue.
