### ISSUE TITLE
Marketplace: Add a red border to the 3PD checkbox instead of blue when not checked

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#66055]
### Details

As part of the linked task #64799, a new checkbox was added to the checkout screen as part of this PR

- https://github.com/Automattic/wp-calypso/pull/65414

When the checkbox is not checked and the user presses the `Pay` button, the checkbox is highlighted in blue and an error message is displayed to indicate that the checkbox is required. 

As part of the demo of the task, some members of the team suggested changing the color of that border to red to indicate an error, this task is a follow-up of that conversation. 

The change technically would be simple but input from design would be great. Please find attached a mockup of the before and after:

|Current | Suggested|
|-------|------|
|![CleanShot 2022-07-28 at 17 28 11@2x](https://user-images.githubusercontent.com/3519124/181577177-4aa84356-e144-4e37-a901-e8f78487a9b9.png)|![CleanShot 2022-07-28 at 17 29 55@2x](https://user-images.githubusercontent.com/3519124/181577609-ec4606fa-4d9a-4c32-b647-38b98831ff83.png)|

cc: @galakhyati, @SaxonF 

### Related

#64799

**Comment by vinimotaa** [comment]
Hi folks,

Did play with some alternatives, and here is my take on it;

- I agree the red color is more appropriate in this case
- When you select/undo de checkbox, the entire component "flickers" a lot by adding the outside stroke to it, and the error message together

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/97929097/187698991-abcff12d-57e1-426f-8e1a-34c3a76e3d7f.png">

My suggestion (see above) is to replace the line with a light red background taking up the entire box and the message. It feels less aggressive, at the same time that it also flags the issue.

If somehow this is out with the rest of our system, I'd go with the red stroke suggested previously.

@WBerredo

**Comment by WBerredo** [comment]
Thanks @vinimotaa, considering the checkout page pattern to highlight is to use borders, I would go with the implemented here #66888
