### ISSUE TITLE
Marketplace: Plugin installation fails if folder already exists

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#66077]
### Quick summary

For premium plugins we are installing the base plugin and requirements through CLI. If any of these plugins already exist in the site (eg in a previous version), the installation will fail cause it hasn't permissions to overwrite the software.

Applying `--force` to all installed plugins might be the solution

eg. ` wp plugin install woocommerce-payments --force`

### Steps to reproduce

1. In an atomic site install an outdated `woocommerce-payments` by uploading this zip https://downloads.wordpress.org/plugin/woocommerce-payments.3.9.3.zip
2. Buy any premium woo extension from wordpress.com/plugins
3. Inspect that neither the woo extension nor `woocommerce-payments` are installed / activated

### What you expected to happen

All software to be installed / activated.

### What actually happened

![CleanShot 2022-07-29 at 10 51 03@2x](https://user-images.githubusercontent.com/12430020/181711529-c5b937f8-40a5-479b-8244-e51a753c545f.png)

### Available workarounds?

Yes

### Workaround details

Symlink the paid plugin - install through CLI the .org version eg `wp plugin install woocommerce-payments --force`

**Comment by BogdanUngureanu** [comment]
D85068-code (pending for review) adds the `--force` flag in the installation process.

**Comment by rcrdortiz** [comment]
Fixed here: https://github.com/Automattic/wp-calypso/issues/66115
