### ISSUE TITLE
Removing Jetpack VideoPress, prompt missing list of lost features

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#66076]
### Quick summary

When removing the Jetpack VideoPress subscription, the prompt is missing the list of lost features.
Issue is not a blocker, user is just not reminded of what they'll be missing.

### Steps to reproduce

1. Add VideoPress to a self-hosted site
2. Remove the VideoPress subscription

### What you expected to happen

The prompt should look similar to this (example with removing Jetpack Complete):
![](https://user-images.githubusercontent.com/15944096/179893999-44f2a4ab-272c-4d9a-83a1-a884527ac7ab.png)
 

### What actually happened

The list of lost features for VideoPress is missing:
![](https://user-images.githubusercontent.com/15944096/179894152-07307518-7089-4970-ab76-edbf0b239c90.png)

### Context

Encountered while testing workflow.
Filing in this repo as the issue happens in Calypso.

If this needs to be handled by the VideoPress team, please transfer to Automattic/greenhouse.

### Platform (Simple, Atomic, or both?)

Self-hosted

**Comment by cuemarie** [comment]
📌 SCRUBBING
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicable on my self-hosted test site - removing the Jetpack VideoPress subscription leads to a prompt that says `Once you remove your subscription, you will lose access to the following:`, but doesn't include any further information.

<img width="1415" alt="Screen Shot 2022-07-28 at 9 33 32 AM" src="https://user-images.githubusercontent.com/27249804/181591084-e22154ea-8a58-4ce8-9df5-e09352d30b89.png">


📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Transferred to Jetpack external repo

📌 Message to Author
- Thank you for the clear report! As this is specific to the Jetpack VideoPress subscription on self-hosted sites, I'm moving this to the Jetpack repo.

**Comment by jeherve** [comment]
I"ll move this back to the Calypso repo, since this interface lives and is developed there.

@Automattic/greenhouse Do you think you could take a look at this?

**Comment by jgcaruso** [comment]
I've added it to our team board. We'll take a look.

**Comment by obenland** [comment]
@jboland88 Is it possible that VideoPress is not identified as a Jetpack product after [these changes](https://github.com/Automattic/wp-calypso/commit/c3dc3d6e7ad0ea1baca7caa7d287af7b31f9980b#diff-bbbc04d9cc127e4c2fb4dc78916519010fe7c1d0260ca24fcf5826c5ecb62958)?

**Comment by jboland88** [comment]
I don't think that's the cause @obenland. This [JetpackBenefits component](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/jetpack-benefits/index.tsx) handles showing the different features that will be lost depending on the product. There's a fixed set of outputs there and It looks like it doesn't do any checking for VideoPress features at the moment. I think that would be the place to add some new checks and output.

**Comment by jgcaruso** [comment]
This has been deployed.

<img width="825" alt="Screen Shot 2022-09-13 at 2 05 01 PM" src="https://user-images.githubusercontent.com/4081020/189977325-a84f2327-fd03-4449-912a-5f86d8864eee.png">
