### ISSUE TITLE
Improve premium plugin order on /plugins and /plugins/browse/paid

### ISSUE THREAD

**Issue by emmnyc85** [Automattic/wp-calypso#66084]
### Details

Plugins appear on the same order we have hardcoded them on both  /plugins and /plugins/browse/paid. Let's automatically re-order them based off # of purchases in the past 30 days.

### Checklist

- Implement code change for order order on /plugins 
- Implement code change for order order on /plugins/browse/paid

Bespin team to DRI this

**Comment by cpapazoglou** [comment]
> Plugins appear on the same order we have hardcoded them on both /plugins and /plugins/browse/paid. Let's automatically re-order them based off # of purchases in the past 30 days.

Sorry @emmnyc85 , dynamic reordering isn't something we can tackle easily now. Can we have a static order?

**Comment by emmnyc85** [comment]
Understood. Let's take the existing top selling order and use that for now. Sound good?

**Comment by cpapazoglou** [comment]
Here is the current order it needs to be reflected in `Marketplace_Product_Catalog` in WPCOM

[Dotcom Marketplace_ Ranked list of plugins by sales.csv](https://github.com/Automattic/wp-calypso/files/9234661/Dotcom.Marketplace_.Ranked.list.of.plugins.by.sales.csv)

**Comment by cpapazoglou** [comment]
The list above isn't correctly aggregated, this is the updated one

[Dotcom Marketplace_ Ranked list of plugins by sales (monthly&yearly).csv](https://github.com/Automattic/wp-calypso/files/9235041/Dotcom.Marketplace_.Ranked.list.of.plugins.by.sales.monthly.yearly.csv)

**Comment by lsl** [comment]
@cpapazoglou @candy02058912 was going to complete this static reordering as an onboarding task tomorrow, could we takeover here with https://github.com/Automattic/wp-calypso/issues/66033 - we'll use this list the csv above to decide on ordering.

**Comment by cpapazoglou** [comment]
Thanks @lsl and @candy02058912 , I will close this as duplicate.
