### ISSUE TITLE
Marketplace: Launch Elastic Search query for .org

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#66089]
## Summary

The functionality to query the `.org` plugins using Elastic Search is ready for the initial phase. This task will be used for launching it.

Context here: pdh6GB-Ax-p2#comment-1954

**Comment by cpapazoglou** [comment]
Let's launch it in wpcalypso and post a CfT

**Comment by gcsecsey** [comment]
Raised a PR to update the wpcalypso config: https://github.com/Automattic/wp-calypso/pull/66133

**Comment by gcsecsey** [comment]
Posted the CFT: pdtkmj-jJ-p2

**Comment by cpapazoglou** [comment]
Should we move this to next sprint for monitoring the CfT and launching in production?

**Comment by gcsecsey** [comment]
Good idea, moved it to the next sprint backlog 👍

**Comment by cpapazoglou** [comment]
Let's fix https://github.com/Automattic/wp-calypso/issues/66866 before launching this.
