### ISSUE TITLE
Reader: Reword invalid tag response.

### ISSUE THREAD

**Issue by aerych** [Automattic/wp-calypso#6609]
The API response after entering an invalid tag reads:
`The TAG requested does not seem to be a valid tag`
Maybe change this to read:
`The tag requested does not seem to be valid.` 
so the casing is nicer and the word "tag" is not repeated.  This would be a nicer message for API clients to display to users.

**Comment by gibrown** [comment]
We should probably rework the API so that tags are topics, and a topic is any phrase. It doesn't need to match something in the global tags table. There is already some work done to go in this direction on the back end.

**Comment by TooTallNate** [comment]
The error message should now be `The tag requested does not seem to be valid.` for all tag-related endpoint user-input errors.

**Comment by aerych** [comment]
Awesome. Thanks for the fast turn around @TooTallNate :)
