### ISSUE TITLE
Email Forwarding: Inaccessible on Domain-Only domains

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#66100]
### Quick summary

Email Forwarding is inaccessible to new domain-only sites without an explanation as to why.

### Steps to reproduce

1. Start at `/email/domain.org/manage/domain.org`
2. Select "Email Forwarding"
3. Select "Add Email"
4. Be redirected to the indefinite loop 

### What you expected to happen

A screen to add Email Forwarding should be offered, or there should be some explanation as to why I can't set up Email Forwarding. I registered this domain about twelve hours ago, so it could just be a matter of needing to wait - but that should be made clear! 

### What actually happened

![email-forwarding](https://user-images.githubusercontent.com/43215253/181901181-b2780f6c-aff9-4d94-ad49-b8a9d01b614d.gif)

### Platform

Domain-only site without a blog attached

Note: I have a version of Calypso saved from last year, where Email Forwarding works fine - as such, I'm guessing it's an issue with something in Calypso rather than the backend.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Domain Only: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Registered a brand new domain without a site
- Once back on dashboard, selected **Inbox**
- Tried adding Email Forwarding, and entered into the loop mentioned above

We do show this message when the domain was first registered:

![Markup on 2023-03-21 at 15:40:41](https://user-images.githubusercontent.com/27249804/226758248-60322838-0d16-471b-886f-0aed369d3290.png)

But I agree, the Email Forwarding loop that ensued was pretty annoying :) 

Step 1 - Select **Inbox**
![Markup on 2023-03-21 at 15:45:15](https://user-images.githubusercontent.com/27249804/226758778-0f67b45d-edfc-4120-b576-f02b007ebce1.png)

Step 2 - Select **Email Forwarding**
![Markup on 2023-03-21 at 15:46:12](https://user-images.githubusercontent.com/27249804/226758809-d683bb19-4af7-4d9c-9eee-fe6de149ba53.png)

Step 3 - Select **Add Email**
![Markup on 2023-03-21 at 15:46:53](https://user-images.githubusercontent.com/27249804/226758843-39d182d4-ca46-45ae-93ae-bf7c44167b1e.png)

You're returned to Step 2 from here.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
📌 SCRUBBING : UPDATE 
- returned today to my domain-only domain, and I still get stuck in this loop when trying to add email forwarding.

**Comment by cuemarie** [comment]
Nomado is going to have a look at this as well, per p1679576429556309/1679509114.400639-slack-C03TY6J1A
