### ISSUE TITLE
Theme Subscriptions - Prep for testing by A8Cs

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#66134]
We need to make sure that theme subscription work is testable by anyone responding to the CFT.

* Possible solutions - 
   * ~~All automatticians~~
   * **User RC checkbox to flag certain users for testing**

~~Let's reach out to Happiness team to coordinate on the best testing strategy here.~~

**Comment by blackjackkent** [comment]
@andres-blanco and I discussed this a little further and he reminded me that we wouldn't have to manage the user RC assignments ourselves; any tester would be able to go in and enable it for themselves after seeing instructions in the CFT. With this in mind, I think it's definiltely the best solution and have updated this issue accordingly.

**Comment by andres-blanco** [comment]
This is what I have in mind for this feature:
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/375980/182223775-25bb6513-fe67-4ca5-8aa8-d5ad0ad9d77e.png">

**Comment by andres-blanco** [comment]
This is the diff where the filter for emails that read the user configuration was added: D67348-code

**Comment by andres-blanco** [comment]
D85230-code

**Comment by andres-blanco** [comment]
Closed by D85230-code
