### ISSUE TITLE
LaunchPad Proper - Site Preview

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66131]
The LaunchPad will need a site preview with device type options as noted in designs - paYE8P-1Ot-p2.

We likely already have the tools/components for this, lets see if we can reuse or repurpose them in the LaunchPad or create our own version if necessary.

**Comment by agrullon95** [comment]
# LaunchPad Site Preview Notes (WIP)

## Reusing `<WebPreview />` component
The WebPreview component will provide us with an iframe that will display a provided site URL and a customizable toolbar to add options above the iframe. This has already been implemented on multiple pages such as the `/start/setup-site/` stepper flow (Navigate to http://calypso.localhost:3000/start/setup-site/design-setup-site?siteSlug={siteSlugHere} then click on any theme).

The WebPreview component and props can be viewed here: https://github.com/Automattic/wp-calypso/blob/093820e320298691995deb2d1dbc6e46f45bed61/client/components/web-preview/content.jsx#L403

### Props notes:

**previewUrl**: URL we want to load within the iframe.
We might need to provide a URL with additional query arguments: ` {
                iframe: true,
                theme_preview: true,
                'frame-nonce': '',
            },`

**iframeTitle**: Accessibility title for iframe

**externalUrl**: URL that will display on the iframe address bar

**toolbarComponent**: Component that will display above the iframe. We can populate this area with a device switcher (desktop, tablet, mobile buttons) component. We can reuse the existing PreviewToolbar component from the signup flow: https://github.com/Automattic/wp-calypso/blob/2938bcb9d3d803a22b15be9a8dc5ea8a4bee53d8/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/preview-toolbar.tsx#L14

**loadingMessage**: Message to display when iframe site preview hasn't been loaded yet.

### Questions/Concerns

`<WebPreview />` component requires that the site be loaded over HTTPS.
* Will front-end links for Jetpack sites be previewable within the iframe? (For example, if the domain is missing HTTPS support).

* The user is able to interact with the iframe preview page by default. Do we have any specific requirements about how we want to block user interaction? I found that the CSS styling `pointer-events: none` can be used on the iframe to block mouse interactions. I'm wondering if there are any drawbacks to using this styling (?).

* Is the design for the default view (desktop) supposed to be small width-wise ?
<img width="614" alt="image" src="https://user-images.githubusercontent.com/10482592/182679319-5cf4caa9-d461-499d-8353-b352b72edab6.png">


### Example of usage (testing within the `/home` page)

![image](https://user-images.githubusercontent.com/10482592/182670243-6c932db0-4272-46d1-a6d1-a2eef2c1ea59.png)

**Comment by jeyip** [comment]
@agrullon95 Great job on digging! How would you feel about adding your WebPreview props notes to https://wpcalypso.wordpress.com/devdocs/design? It wouldn't have to be now, but if you agree, maybe we could leave a TODO somewhere to update docs

**Comment by jeyip** [comment]
> Will front-end links for Jetpack sites be previewable within the iframe? (For example, if the domain is missing HTTPS support).

Out of curiosity, would this be a problem anywhere the WebPreview component appears?

> I found that the CSS styling pointer-events: one can be used on the iframe to block mouse interactions. I'm wondering if there are any drawbacks to using this styling (?).

I imagine it might be an issue if we ever want to capture iframe tracking events in the future ( although unsure how likely this would be ).

> Is the design for the default view (desktop) supposed to be small width-wise ?

Good question -- Let's check in with @nuriapenya. I imagine it _shouldn't_ be small width wise.

**Comment by nuriapenya** [comment]
> Is the design for the default view (desktop) supposed to be small width-wise ?

No, no. The desktop view should show the wide preview, as it is currently built. What we might change is the default preview. For both Newsletter & Link in Bio makes more sense to have mobile defaulted. 

Would that be difficult to implement?

So cool starting to see things live 💎 great job @agrullon95

**Comment by agrullon95** [comment]
> No, no. The desktop view should show the wide preview, as it is currently built. What we might change is the default preview. For both Newsletter & Link in Bio makes more sense to have mobile defaulted.
> 
> Would that be difficult to implement?
> 

The component already contains a property to set a default device (`defaultViewportDevice`), so that should be straightforward to implement.

**Comment by agrullon95** [comment]
> > Will front-end links for Jetpack sites be previewable within the iframe? (For example, if the domain is missing HTTPS support).
> 
> Out of curiosity, would this be a problem anywhere the WebPreview component appears?

Yes, the same issue will occur across all `WebPreview` components.

**Comment by Addison-Stavlo** [comment]
Im closing this issue with the merge of https://github.com/Automattic/wp-calypso/pull/66424

and created follow ups for future tracking:
https://github.com/Automattic/wp-calypso/issues/66574
 https://github.com/Automattic/wp-calypso/issues/66571
 https://github.com/Automattic/wp-calypso/issues/66572
 https://github.com/Automattic/wp-calypso/issues/66575
