### ISSUE TITLE
Help Center: disable for P2 frontend

### ISSUE THREAD

**Issue by vasyas** [Automattic/wp-calypso#66149]
### What

Remove Help Center assets from the P2 frontend.

### Why

Help Center is not used in the P2 frontend editor. Loading its assets will degrade page loading time. Also, sometimes loading of Help Center brings unneeded CSS rules, see 5805-gh-Automattic/p2 and #66181

**Comment by escapemanuele** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/66181
