### ISSUE TITLE
LaunchPad - Add moments of celebration

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#66147]
### What

As the user completes the launchpad checklist, we can add emojis, playful text, or other ways of celebrating their progress.

### Why

We can delight users with fun messaging and animations, which can be a way of connecting with users more personally and can also provide a better first impression of our platform

Related to https://github.com/Automattic/wp-calypso/issues/65684

**Comment by Addison-Stavlo** [comment]
It would be really cool to have some sort of overlay confetti animation to play on the processing screen transition into my home when the user launches their site (or even just on my home for non-launchpad users launching there as well) 🤔

**Comment by Addison-Stavlo** [comment]
closing this with our addition of the celebration modal.
