### ISSUE TITLE
Sidebar: add persistent Help link to editor sidebar

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#6615]
In April, we added a persistent Help icon to the footer of My Site(s) and Reader sidebars. This makes accessing help more direct (formerly accessible 2 levels lower via /me) and gives live chat users access to chat without obscuring other important parts of the UI (which the chat dialogue was [known to do](https://cloudup.com/cBnZ9_O0zrD)).

This icon should be available within the editor context as well:

![](https://cloudup.com/cc_tSvnxtsb+)

Reference: https://github.com/Automattic/wp-calypso/pull/4447
Current implementation in sidebars: https://cloudup.com/c2-qL8w2ff5

**Comment by aduth** [comment]
Reopening this, as I'm observing that in Safari at least, the Help icon gets stuck at the bottom of the viewport when open accordions cause sidebar scroll. Maybe a `z-index` thing? cc @mtias re #6618

![help](https://cloud.githubusercontent.com/assets/1779930/17156150/4bbf2be2-5356-11e6-8a73-b593064301fc.gif)

**Comment by mtias** [comment]
@aduth, yes, that's known, we need to use the Sidebar component and probably the sidebar regions for scrolling the drawer.

**Comment by lancewillett** [comment]
This is working for me now in Safari 10.0.3 on OS X 10.12.3.
