### ISSUE TITLE
Marketplace search: author display name differs from WP.org

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#66159]
Some results display a different author name that's displayed on WP.org. We may need to revisit which fields we use as the source for the author display name.

#### Steps to reproduce

> **Note**
> The `marketplace-jetpack-plugin-search` feature flag is enabled by default on the **wpcalypso** environment.

1. Starting at URL: https://wpcalypso.wordpress.com/plugins
2. Search for a plugin where the author username and display name are different, eg.: `unicard`
3. Search for the same plugin in the WP.org plugin repository: https://wordpress.org/plugins/search/unicard/

#### What I expected
The author display name should match on the two search results.

#### What happened instead
The author display name is different on the two search results.

#### Screenshot / Video
| WP.org result | Marketplace result |
| ------ | ----- |
| ![CleanShot 2022-08-02 at 12 07 07@2x](https://user-images.githubusercontent.com/11555574/182350018-42f9d7d8-f91c-4454-9522-b369616d8a9b.png) | ![CleanShot 2022-08-02 at 12 06 39@2x](https://user-images.githubusercontent.com/11555574/182350028-f41c6ca9-a714-44d0-99a2-fea61a20a730.png) |

**Comment by epeicher** [comment]
Diff created for the backend changes: D86503-code
Pull Request for the front-end changes: https://github.com/Automattic/wp-calypso/pull/66926

**Comment by epeicher** [comment]
Deployed r251270-wpcom
