### ISSUE TITLE
Reblog: Featured images not visible on reblogged posts

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#66150]
### Quick summary

When a post is reblogged, the post's featured image is never shown on the public post. It is however, output as an `og:image` and picked up in both the Calypso post list and rich media previews on social networks, etc.

Changing/re-adding the featured image has no effect. The image is simply not output on the front end.

Cc @druesome

### Steps to reproduce

1. Reblog a post with a featured image.
2. View the reblogged post.

### What you expected to happen

The featured image should output on the front end, just like any other post.

### What actually happened

The post's featured image is never shown on the front end.

### Context

Live chat: [35995155](35995155-hc)
Follow-up email: 5440080-zd-woothemes

Initial internal discussion: p1659332201751659-slack-C03TY6J1A
Escalated internal discussion: p1659335868663679-slack-C7YPUHBB2

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No. Tested on Dalston, Twenty Twenty and Quadrat so far.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by inaikem** [comment]
Additional internal discussion here: p1659410908982619-slack-C03NLNTPZ2T

**Comment by creativecoder** [comment]
Proposing a fix in D85402-code.

I don't have much context about or experience with the reblogging feature, so any help testing and reviewing is much appreciated!

**Comment by cuemarie** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ⚠️ - `Reblog` feature is only available on Simple sites.
- Tested on Self-hosted ⚠️ - `Reblog` feature is only available on Simple sites.
- Replicable on Core - Yes/No

📌 FINDINGS/SCREENSHOTS/VIDEO
- When reblogging a post with a featured image to another simple site, the featured image does appear on the **latest posts** page of the simple site, but not on the **single post** page. 
     - **Single Post** page is displaying a `wpcom-reblog-snapshot`
     - **Latest Posts** page is just pulling the post's actual content. 
- This means the **Latest Posts** also shows more of the post's text, while the **Single Post**'s `wpcom-reblog-snapshot` shows only a short excerpt. Examples below:

**Reblogged Post:** pdIcnP-2a-p2

**Latests Posts (Index.php)**

<img width="1535" alt="Screen Shot 2022-08-05 at 11 13 08 AM" src="https://user-images.githubusercontent.com/27249804/183138691-3613e81c-8db0-432a-a6fb-8dd7080ade6e.png">

**Latests Posts (Index.php) - Inspector Tools**
<img width="1229" alt="Screen Shot 2022-08-05 at 11 33 14 AM" src="https://user-images.githubusercontent.com/27249804/183140156-b787e88d-618c-439c-a4f7-116a1d41f916.png">

**Single Post Page**

<img width="1540" alt="Screen Shot 2022-08-05 at 11 13 36 AM" src="https://user-images.githubusercontent.com/27249804/183138741-f802b391-9e4b-483a-af63-ed681e936b81.png">

**Single Post Page - Inspector Tools**

<img width="1034" alt="Screen Shot 2022-08-05 at 11 30 38 AM" src="https://user-images.githubusercontent.com/27249804/183139735-4a0a63a4-34b3-47a2-b691-ee47e41aed2c.png">

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by creativecoder** [comment]
D85402-code has been deployed, which should resolve this issue.

If you see additional issues with reblogging and featured images, let me know!
