### ISSUE TITLE
Button Block on Barnsbury theme is "invisible" when set to 'Outline'

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#66152]
### Quick summary

Using the Barnsburey theme, the Button Block shows as invisible on the front end when set to use the 'Outline' style.

### Steps to reproduce

1. Activate the Barnsburey theme.
2. Add a button block to a page.
3. Set it to 'Outline' and save the page.
4. View the page.
5. The button is "invisible" and only appears on hover.

### What you expected to happen

I expect the button to display using the colour I set.

### What actually happened

The button appeared "invisible" until hovered over.

### Context

36274008-hc

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Unknown. I was only able to test on Barnsbury.

### Available workarounds?

Yes, easy to implement

### Workaround details

CSS fix:

```
/* Manually set button color | 36274008-MK */
a.wp-block-button__link.has-secondary-color.has-text-color.wp-element-button {
    border: 2px solid #cad2d7;
    color: #cad2d7;
}

/* Manually set button hover state | 36274008-MK */
a.wp-block-button__link.has-secondary-color.has-text-color.wp-element-button:hover {
    border: 2px solid #3c2323;
    color: #3c2323;
}
```

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I cannot replicate this. @inaikem I believe this is an unfortunate combination of colors. Do you happen to remember it?

📌 ACTIONS
- Await author feedback

**Comment by inaikem** [comment]
You might be right. The colours present when they came into chat are the same as those set now:

![Screen Shot on 2022-08-05 at 12:30:03](https://user-images.githubusercontent.com/66711744/183001780-1a37cdef-2428-460c-8029-11bab8cdc124.png)

Feel free to close if you can't replicate!

**Comment by Robertght** [comment]
Thank you! Closing for now. 

Please reopen if the issue reoccurs.
