### ISSUE TITLE
Theme Subscription: Extra purchase when buying a theme subscription

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#66179]
After purchasing either the `theme:baxter-yearly` or `theme:baxter-monthly` theme subscriptions, I end up with two purchases.

![image](https://user-images.githubusercontent.com/917632/182445237-ed8ac176-b26f-4ee7-b540-5b6a45782a16.png)

You can also see both purchases by viewing `/sites/<site-id>/purchases`
![image](https://user-images.githubusercontent.com/917632/182445363-3a52fdfd-8384-4ae5-b2d8-a6f78f695143.png).

What happens is the first purchase (with id `1017364`) is the actual theme subscription. Deleting this purchase triggers the correct deactivation process. The issue is that purchase is `1017364` is _not_ in the `premium_theme_purchases` table.

The second purchase (with id `295981`) _does_ appear in the `premium_theme_purchases` table but can't be deleted due to an "Only owner can delete subscription" error.

We need to figure out why two purchases are created and fix it so there's a single purchase that appears in `premium_theme_purchases` and can be delete/deactivated.

Related to #66048 and D84731-code

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- There are no longer yearly/monthly purchase options for this theme
- When purchasing the design on a free site, only one purchase is listed:

#### Screenshots/Recordings

![Markup on 2023-05-03 at 12:27:45](https://user-images.githubusercontent.com/27249804/236024416-ef346ef8-aef1-4d27-998f-f89cd3a0a0ab.png)


📌 ACTIONS
- Closed as no longer relevant
