### ISSUE TITLE
[Meta] KPI Dashboard Project

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#66188]
### Details

As noted in pciE2j-EI-p2, @Automattic/kitkat is looking to create a dashboard to report on identified metrics.

**Comment by worldomonation** [comment]
Phase 1 of the project has been shipped, with an Allure dashboard generating on each Pre-Release Test run.

**Comment by cometgrrl** [comment]
@worldomonation Since we don't have a defined next phase, should this be closed now?

**Comment by worldomonation** [comment]
@cometgrrl Agreed, let's close for now.
