### ISSUE TITLE
PostSchedule: should use gray variable

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#6619]
![image](https://cloud.githubusercontent.com/assets/548849/16684081/4cf2500e-4503-11e6-938b-f49796ba7366.png)

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Closing because the post scheduling interface has changed.

<img width="270" alt="screen shot 2018-01-02 at tue jan 2 10 00 24 pm" src="https://user-images.githubusercontent.com/1119271/34509583-d51cd682-f008-11e7-8205-667b4381dd99.png">
