### ISSUE TITLE
Sites Management Page: Write a draft for blog announcement

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#66191]
Let's start a draft post in Google docs for this feature's upcoming WP.com blog announcement. It should be done two weeks before the planned release date.

Once done, we should also make a `socialmattic` request.

**Comment by danielbachhuber** [comment]
@vindl @p-jackson I think we're getting close to the "two weeks before the planned release date", so I might be falling behind on this issue.

Here's my ~~draft~~ outline thus far: https://docs.google.com/document/d/1JT2cDeAh4CLgKSmOGoOa5lkW5T__M4AFlSCyf6JD6yA/edit

What do you think of the overall approach? Am I headed in the right direction?

**Comment by vindl** [comment]
@danielbachhuber After some recent process updates, we'll have a Marketing team responsible for blog posts in different areas. For Build, that will be Searchlight and @Lochlaer.

**Comment by danielbachhuber** [comment]
@vindl @p-jackson @Lochlaer I've updated the Google Doc such that it now represents a full first draft.

It's a little on the short side, though (272 words). Not sure what our target length is.

Also, in interest of simplicity, I dropped the 'Tech Tip' section.

**Comment by p-jackson** [comment]
I think short and sweet is good. The important message that "this basic feature should help and there's more coming" comes across strongly IMO.

We might need to work in some instructions for how to navigate to the Sites page. The first paragraph of the first section seems like a natural place, but it also seems like a pretty detail heavy way to start of the section.

**Comment by danielbachhuber** [comment]
> We might need to work in some instructions for how to navigate to the Sites page. The first paragraph of the first section seems like a natural place, but it also seems like a pretty detail heavy way to start of the section.

@p-jackson Good point! I've added a short mention later on in the blog post.

Pretty happy with where this draft is at now 🚢
