### ISSUE TITLE
Media Library: Ampersands in the Title and caption fields convert to &amp; on WordPress.com simple

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#66206]
**Update**

After discussion in the comments, I've updated the details of this issue.

### Steps to reproduce the behavior

**This only happens on WordPress.com Simple**

1. Go to Media > Library
2. Upload 2 images.
3. In the first image, add a title using an ampersand

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/426388/182556500-acbb36eb-8e60-41fd-b354-0a71414a4352.png">

4. In the second image, add a caption using an ampersand

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/426388/182556608-397f6699-00a5-4124-a2a3-973c1525e409.png">

5. Refresh the page
6. When reviewing the metadata of the images, you'll see that the ampersands are now encoded:

<img width="457" alt="Screen Shot 2022-08-03 at 10 05 01" src="https://user-images.githubusercontent.com/426388/182556951-f59f9eb2-2f16-4c31-b564-fd877f710896.png">

<img width="541" alt="Screen Shot 2022-08-03 at 10 04 57" src="https://user-images.githubusercontent.com/426388/182556957-363c9e6e-1930-47bf-890a-ac2ffe112c12.png">

************

Old issue content below:

To start, I should mention that I'm only seeing this issue in the Carousel, but I'm not certain that it is happening because of the carousel code.

### Steps to reproduce the behavior

1. Add a gallery block to a blank page
2. Add two images to the gallery
8. Include an ampersand in the title of one image
9. Include an ampersand in the caption of the other image
10. Publish and view the live page
11. The ampersand in the title will convert to `&amp;` while the ampersand in the caption will show correctly

#### What I expected to happen

The ampersand would show correctly in either case

#### What actually happened

The ampersand was converted to &amp;
~~

### Context

4148144-zen

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
it appears to be simple only

#### Is there any console output or error text?
no
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It doesn't block purchases. It happened on my test site and a customer site.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
wp-admin - ampersand in title:
![image](https://user-images.githubusercontent.com/3505172/127344955-7bdafdb0-12de-47c2-8f35-19fb62bdf958.png)

carousel - ampersand in title:
![image](https://user-images.githubusercontent.com/3505172/127345081-174287c1-b8f1-464e-83ad-7d863baac6ea.png)

wp-admin - ampersand in caption:
![image](https://user-images.githubusercontent.com/3505172/127345190-a11e4793-af13-4991-8e5a-24a74966d7ed.png)

carousel - ampersand in caption:
![image](https://user-images.githubusercontent.com/3505172/127345322-0d327e00-f0d0-4722-acec-d254f11dc4a3.png)

We should notify the customer once this has been investigated/resolved.

**Comment by inaikem** [comment]
Following the steps above, I added two images to a tiled gallery as follows:
&nbsp;
- Include an ampersand in the title of one image
- Include an ampersand in the caption of the other image
&nbsp;

...and viewed them in a published post on a simple site.The exact test text I used was as follows:
&nbsp;
- Caption: Just an `&` test. Will we see `&amp;`?!
- Title: Just an `&` test. Will we see `&amp;`?!
&nbsp;

Surprisingly, the carousels rendered the test text on the published page as follows:
&nbsp;
- Caption: Just an `&` test. Will we see `&`?!
- Title: Just an `&` test. Will we see `&`?!
&nbsp;

However, when revisiting the media library via the Tiled Gallery block's edit icon, the test text had changed to the following:
&nbsp;
- Caption: Just an `&amp;` test. Will we see `&amp;`?!
- Title: Just an `&amp;` test. Will we see `&amp;`?!

**Comment by jeherve** [comment]
I can't reproduce the original issue, but I can reproduce the problem described in the comment. It only happens on WordPress.com simple though.

<img width="851" alt="Screen Shot 2022-08-03 at 09 56 13" src="https://user-images.githubusercontent.com/426388/182555107-c686b2e6-81be-45d4-a9f5-9836bfc8858d.png">
<img width="851" alt="Screen Shot 2022-08-03 at 09 56 06" src="https://user-images.githubusercontent.com/426388/182555119-0f091d6e-3895-4a69-a381-32784a51466e.png">


Thank you!
