### ISSUE TITLE
[Bug]: Mismatched Subscriber Count in Publish & Subscribe Blocks

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#66213]
### Quick summary

For my site `vishnugopal.com`, there seems to be a mismatch between the number of followers/subscribers I have and the count it displays when I hit Publish or add a Subscribe block:

Publish:
<img width="268" alt="CleanShot 2022-08-03 at 14 41 58@2x" src="https://user-images.githubusercontent.com/533/182571179-4a48a1d4-3fa1-4b47-b244-b01480f87357.png">

Subscribe block:
<img width="874" alt="CleanShot 2022-08-03 at 14 43 54@2x" src="https://user-images.githubusercontent.com/533/182571616-8d572e7a-0cfe-4b12-b99c-80aa4b4723a3.png">

But count of subscribers/followers is actually much less:
<img width="828" alt="CleanShot 2022-08-03 at 14 44 36@2x" src="https://user-images.githubusercontent.com/533/182571730-2c70ba50-9526-41ee-87e7-cac4736e3276.png">
<img width="789" alt="CleanShot 2022-08-03 at 14 44 47@2x" src="https://user-images.githubusercontent.com/533/182571772-684355cb-67c2-4a13-99ed-fc8096bcc328.png">

I've been having this blog since ages (2003 at least) so I'm not sure if it's something I did on the way deliberately that made things like this. My one hunch was that it adds up the number of my [Twitter followers](https://twitter.com/vishnugopal) (2,975 Followers) since I have that connected, but I couldn't make that arithmetic work.

### Steps to reproduce

This appears only at `vishnugopal.com` so I'm not sure how to reproduce this.

### What you expected to happen

NA

### What actually happened

NA

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Context

Internal Testing

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

One

**Comment by TimBroddin** [comment]
Deployed to wpcom in  D89641-code & D89833-code

Waiting on PR for Jetpack: https://github.com/Automattic/jetpack/pull/26751/

Communication with HE: pdDOJh-Sv-p2

**Comment by eduardozulian** [comment]
👋 Just wanted to bring attention that customer feedback is being shared in p7DVsv-fDf

**Comment by TimBroddin** [comment]
Hi @eduardozulian, thanks for mentioning this. Started discussion here: p1666295848198789-slack-C02TCEHP3HA

**Comment by cuemarie** [comment]
The Publish count and Subscribe block do indeed include social media followers.  This was removed, but ultimately reverted in D90735-code

Users now have the ability to opt to include/exclude social media followers in their subscriber count. See public guide for more: https://wordpress.com/support/wordpress-editor/blocks/subscribe-block/#block-settings
