### ISSUE TITLE
Sites Management Page: Don't show status-specific empty states where there are no sites at all

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66210]
When the user has no sites at all the empty states currently look like this.

https://user-images.githubusercontent.com/1500769/182567507-6b7ecca9-6a04-4ac8-8b41-dc697abcad99.mp4

The helpful messages about "launch one of your sites" don't make much sense when there are no sites. In this case, we should show the "Create your first site" message regardless of the status filter.

Done is:
- "Create your first site" is always visible when there are no sites, regardless of status filtering.

**Comment by danielbachhuber** [comment]
@p-jackson @Automattic/build Given the Sites Management Page now looks like this:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/36432/182841275-760872a9-cd71-48cd-bdc4-ee3742afe3dc.png">

What if we simply hid the search input and filter dropdowns when `allSites.length === 0` ?

**Comment by p-jackson** [comment]
Yup I think that's perfect.
