### ISSUE TITLE
Rowling Theme: Fonts set in the Customizer not the same in Editor #5554

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#66231]
### Quick summary

Using the Rowling theme, the fonts set in Customize > Fonts appear correctly on the live page but show a different font in the page editor.

5449616-zen

### Steps to reproduce

1. activate Rowling theme
2. go to Appearance > Customize > Fonts
3. set fonts for Heading and Base font
4. visit the site to see how it looks on the live page - it shows the correct font set in the Customizer
5. open a page in the editor - the font in the editor will not be the same as the font you set in the Customizer

### What you expected to happen

Fonts set in the customizer will appear the same in the live page and page editor.

### What actually happened

Fonts set in the customizer only appear correctly on the live page but show a different font in the page editor.

### Context

Looks like this in the editor:
<img width="925" alt="Screen Shot 2022-08-03 at 1 19 13 PM" src="https://user-images.githubusercontent.com/34966264/182671322-1e3d9936-b1ec-4b4e-a119-164b633f1719.png">

And like this on live page:
<img width="644" alt="Screen Shot 2022-08-03 at 1 27 32 PM" src="https://user-images.githubusercontent.com/34966264/182671535-960bac2b-b917-49b4-b472-ec1030f3871a.png">

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No, it looks like the same issue as Twenty Twenty theme here:
https://github.com/Automattic/themes/issues/5554

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

At this time, only using another theme.

**Comment by cuemarie** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/66233
