### ISSUE TITLE
Classic Themes: Fonts set in Customizer are not applied in page or post editor

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#66233]
### Quick summary

The font in the page editor does not match the font set in Customizer. Font seems to be `Times New Roman`. This is occurring even though "Use theme styles" is enabled in the editor preferences.

This is present in `Saga` theme. I tried various fonts and it seems to always show `Times New Roman`.

### Steps to reproduce

1. Activate `Saga` theme.
2. Open a page for editing.
3. Make sure the "Use Theme Styles" toggle is on in the page editor preferences.
4. Add some blocks that allow text such as a paragraph block.
5. Font appears to be `Times New Roman`.

### What you expected to happen

The font to match what is set in Customizer.

### What actually happened

Font shows as `Times New Roman`

![Markup on 2022-08-03 at 14:43:16](https://user-images.githubusercontent.com/93800099/182685308-1025657c-d977-4ecf-bc3e-ac18a71917dc.png)

### Context

34008968-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

- Saga
- Dara (saw this on another user's site, but they weren't asking for help with this)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Not exactly a workaround but if you turn off "Use Theme Styles" in the page editor preferences, some users may find the text to be easier to read.

**Comment by daria2303** [comment]
5451990-zd-woothemes
5451829-zd-woothemes

There are several discussions on this issue in slack.

Related bug reports: 
https://github.com/Automattic/wp-calypso/issues/66231
https://github.com/Automattic/themes/issues/5554

**Comment by csabarakasz** [comment]
Same issue, different theme: Pique.

This might be not theme specific.

- [ ] 34226706-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- ✅ Replicated on Simple and AT sites using the following themes: `Saga`, `Rowling`, `Twenty Twenty`.

**Simple**

Customizer:

<img width="1160" alt="Screen Shot 2022-08-05 at 12 37 42 PM" src="https://user-images.githubusercontent.com/27249804/183149909-c0ff4f12-9885-482a-8104-cbe3e3277ad5.png">

Editor:
<img width="1478" alt="Screen Shot 2022-08-05 at 12 39 59 PM" src="https://user-images.githubusercontent.com/27249804/183149781-34160a2d-fd94-4f03-ae7c-56914d4f23c0.png">

**AT**

<img width="1433" alt="Screen Shot 2022-08-05 at 12 48 45 PM" src="https://user-images.githubusercontent.com/27249804/183150313-7eec6cfc-0bd1-4d12-bf42-d7aef182f9d7.png">

Customizer: 

Editor:
<img width="1271" alt="Screen Shot 2022-08-05 at 12 42 02 PM" src="https://user-images.githubusercontent.com/27249804/183149838-f4cbd514-2c47-4155-8d39-f8bffa9e6dc7.png">

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
User report from https://github.com/Automattic/wp-calypso/issues/66231 :

- [ ] 5449616-zd-woothemes

**Comment by cuemarie** [comment]
User report from https://github.com/Automattic/themes/issues/5554 : 

- [ ] 5450315-zd-woothemes

**Comment by Robertght** [comment]
I'm not sure if we can get to these in one go. @jeffikus is this best handled through the themes itself or another component?

LE: and should we keep it here or move it to Themes?

**Comment by jamiepalatnik** [comment]
Another report, Dara theme: 37593262-hc

**Comment by jamiepalatnik** [comment]
Another report, Catch Flames Pro (third-party theme): 37665489-hc

**Comment by sarahcada** [comment]
Another report, Dara theme:

- [ ] 5665014-zd-woothemes

**Comment by Robertght** [comment]
It looks like this was previously fixed somehow(probably related https://github.com/WordPress/gutenberg/issues/42902) , but the issue is now back.

**Comment by zdenys** [comment]
5665800-zd-woothemes

**Comment by mdtanjid0** [comment]
5664186-zd-woothemes

**Comment by Joshgrygiel** [comment]
Another report, Independent Publisher 2 theme, 37731251-hc

**Comment by kerrynicl** [comment]
Another case with Dara theme - 5663210-zd-woothemes

**Comment by deancroyal** [comment]
A report for Apostrophe 2 36988818-hc

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/text-style-not-the-same-in-editor-and-in-blog/
Independent Publisher 2 theme

**Comment by hacchism** [comment]
Another report, Business theme, 5685124-zd-woothemes

**Comment by zdenys** [comment]
Toujours theme in 5675202-zd-woothemes

**Comment by upwardmomentum84** [comment]
Canard theme in 5686516-zd-woothemes

**Comment by arinoch** [comment]
The original Independent Publisher theme is having this issue in 5681101-zd-woothemes. The workaround of disabling "use theme styles" does not work - the site won't respect that setting. p1667785397936439-slack-C03TY6J1A

**Comment by upwardmomentum84** [comment]
Another case (Ubud - retired theme): 20485070-hc

**Comment by rw-ye** [comment]
Another report: 5732304-zd-woothemes

Theme: Bushwick

**Comment by csabarakasz** [comment]
- [ ] 5754256-zd-woothemes

Theme Libretto

**Comment by daria2303** [comment]
5862867-zd-woothemes

Munchies theme

**Comment by ersatzpenguin** [comment]
This came up in 5891832-zd-woothemes

Baskerville 2. Thinking this might be due to changes in how Global Styles are managed now since old workarounds for this sort of issue aren't applicable (Global Styles settings aren't available in the page editor at all now).

**Comment by jeffikus** [comment]
Hi folks, @pbking and I debugged this further today. 

This looks to be an issue in the `custom-fonts` plugin. @obenland @mpkelly @daledupreez tagging you as you were the latest committers there and seem best positioned to find a solution. My best estimate as to what is going on here is the `typekit_add_font_category_rules` filter is not being applied in the editor. It appears that it is being applied in the customizer and the frontend, but not in the post and page editor. I tested this with a few different themes, and there appears to be several implementations of "global styles" that I'm not very familiar with, through that plugin or through Jetpack - as an example, you can see the filter file in Radcliffe 2 [here](https://github.com/Automattic/themes/blob/trunk/radcliffe-2/inc/jetpack-fonts.php). @jeherve perhaps you might have some additional insight here.

I don't see a way to fix this from with the theme itself, unless you all have a suggestion? Regardless, the most scalable solution appears to be to solve it in the plugin.

**Comment by jeherve** [comment]
I'm not at all familiar with the old Custom Fonts plugin so I'll let others chime in on that. I know we've done a lot of work on Global styles in the past couple of months, and it seems that @simison had looked at compatibility between his work and Custom Fonts at the time (see 328-gh-Automattic/custom-fonts), but I don't know where things are at with this plugin today.

**Comment by christianguerrag** [comment]
Another report here 5924011-zen

**Comment by ezebecke** [comment]
Also in [5920211-zd](5920211-zd-woothemes)

**Comment by daria2303** [comment]
37509457-HC 
workaround helped
