### ISSUE TITLE
Sites Management Page: Calibrate fuzzy search so it's not so fuzzy

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66248]
Currently the fuzzy search is very forgiving. It will match a site using a single character from the query string.

![Image](https://user-images.githubusercontent.com/1500769/182768657-dd355441-c4f1-4690-a76b-0127be9f11c5.png)

The fuzzy search sorts the closest matches to the top of the table which helps, but it still leaves sites in the table the user might have expected should have disappeared. The fuzzy search library we're using (`fuse.js`) has options for setting how lenient the fuzzy search should be. Perhaps we just need to adjust these parameters.

On the other hand perhaps this is just the nature of fuzzy search and the user is just supposed to depend on the closest match bubbling to the top of the list and ignore the other sites. If I look at the fuzzy searching in VS Code it will match on a single character from the query string.

![Image](https://user-images.githubusercontent.com/1500769/182769420-a6f676d3-c8cd-4bc3-86c4-4c1a139304b9.png)

In this case I think an important part of the fuzzy searching UI is that the matching part is highlighted in the UI. This gives the user feedback on why one site has risen to the top of the list while the other has not.
I have a PR that partially implements this: https://github.com/Automattic/wp-calypso/pull/66075

Done is:
- This task doesn't have a very good definition for done. Done means that the fuzzy search feels about right. This could mean the `fuse.js` options are tweaked or that we highlight search matches in the UI.

**Comment by wojtekn** [comment]
I've tried adjusting the threshold parameter but without success. Currently, we set it to 0.4. When I search for "test", I get four results that have an exact match, then the next results do not have anything similar to "test". Based on screenshots shown by @p-jackson, I guess it is "T....   ...es...   ....t"-like match.

I tried to decrease the threshold to 0.3, but I didn't observe too much change. Reducing the threshold to 0.2 left me only with exact matches for the "test". However, this killed the fuzziness completely as I couldn't search for "site" when I had a typo in the search phrase e.g., "sitw" or "sitr".

> On the other hand perhaps this is just the nature of fuzzy search and the user is just supposed to depend on the closest match bubbling to the top of the list and ignore the other sites.

It may be that it's about that 👍

**Comment by p-jackson** [comment]
The `ignoreLocation` fix in #66311 has improved search results a lot for me. When I use the `"test"` query string now I get much more reasonable results than the screenshot I posted above. The single letter matches are much further down the list, off the screen even. So I'm a lot happier with how fuzzy search feels now.

Let's roll with the threshold as it is.
