### ISSUE TITLE
Sites Management Page: Add tile view

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66247]
This task is to implement a tile view for the Sites Management Page. There are a number of tasks so this should be done over multiple PRs.
![Image](https://user-images.githubusercontent.com/1500769/182765352-a780c40e-07ad-4bfb-96de-9580d76d361c.png)

Notice how both modes are available on small screens.
![Image](https://user-images.githubusercontent.com/1500769/182765387-f0909639-f1f3-4cf5-9458-15c6ef4e0347.png)

Grab the SVGs for the toggle from here pdKhl6-Au-p2#comment-517

Done is:
- [x] User can view version of their sites list in a grid layout with larger site icons
   - [ ] Each row in the grid shows up to 3 tiles
   - [ ] Number of tiles per row gradually decreases as screen width decreases
- [x] Tile shows info for each site
   - [ ] Show site title with link to dashboard
   - [ ] Show site URL with link to front end
   - [ ] Show ellipses menu
   - [ ] Launch status is displayed as a badge (except make it grey pdKhl6-Au-p2#comment-521)
   - [ ] Tiles don't show last published date
- [x] Use can toggle between tile and table views
   - [ ] Toggle state is persisted in user preferences store
   - [ ] Tile view is the default
   - [ ] both views are available on mobile layouts
- [x] Filtering works with tile view

**Comment by zaguiini** [comment]
Note to self: use this property to achieve aspect ratio between screen sizes: https://caniuse.com/mdn-css_properties_aspect-ratio

**Comment by zaguiini** [comment]
Done 🚀
