### ISSUE TITLE
Marketplace: Show name instead of username on submission success page

### ISSUE THREAD

**Issue by lupus2k** [Automattic/wp-calypso#66273]
According to @mtias [suggestion](https://github.com/Automattic/wp-calypso/pull/64671#discussion_r937714820), we should show the `name` instead of `username` in the `Hello` message.

#### Screenshot
| Before | After |
| -- | -- |
| <img width="637" alt="image" src="https://user-images.githubusercontent.com/402286/182918880-5006a279-d8b1-46f7-aa3c-370e4bc86d70.png"> | <img width="637" alt="image" src="https://user-images.githubusercontent.com/402286/182919051-cf36ff63-c713-4155-8d08-f16f7975d8d6.png"> |

#### Steps to reproduce

1. Logged in as a WPCOM Partner
2. Go to URL: `/marketplace/submission-success?returning=true`
3. Check for the username after `Hello, `

**Comment by Rolilink** [comment]
LGTM!

**Comment by mtias** [comment]
Thanks!
