### ISSUE TITLE
Payton: Theme only displays 2 fonts for Global Styles text font choices

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#66286]
### Quick summary

The theme Payton is currently only showing two font options when going to Global Styles when there should be more to choose from. 
<img width="292" alt="CleanShot 2022-08-01 at 15 01 53@2x" src="https://user-images.githubusercontent.com/83020905/182082849-875ed2ec-8e1d-4d7e-ab57-52df17aef156.png">

### Steps to reproduce

1. Activate Payton theme
2. Visit Site Editor
3. Go to Global styles
4. Change font for text
5. Only two options: Source Serif Pro or Overpass

### What you expected to happen

There should be additional font options here.

### What actually happened

There are only two font choices.

### Context

35806197-hc
Tried on test Atomic and test simple sites.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Payton. The other theme I tested that was also Premium (Videomaker) did not exhibit this issue.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by druesome** [comment]
Related P2: p9F6qB-9Yy-p2

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to recreate this issue on simple and AT test sites. In Global Styles > Typography > Text > Font family, I see only Default, Source Serif Pro, and Overpass in the dropdown.
- I was not able to test on a self-hosted site since I wasn't able to find a version of the Payton theme for self-hosted sites.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Robertght** [comment]
Moving this to .com as it's a Premium theme. 

cc @Automattic/serenity

**Comment by Robertght** [comment]
Also, potentially relate to https://github.com/Automattic/wp-calypso/issues/66008

**Comment by JoshuaGoode** [comment]
Related / duplicate?  https://github.com/Automattic/wp-calypso/issues/63229#issuecomment-1211176825

**Comment by blackjackkent** [comment]
This was probably solved by https://github.com/Automattic/wp-calypso/issues/63229 - let's verify that's the case and close if so.

**Comment by markbiek** [comment]
@Automattic/serenity I've confirmed that this _is_ still happening. Testing on both WordPress.com and running Calypso locally with the latest `trunk`.

**Comment by markbiek** [comment]
@pbking Given the change you made [here](https://github.com/Automattic/wp-calypso/issues/63229#issuecomment-1218431731), do you have any thoughts on why Payton is still showing an incorrect list of fonts?

My steps to reproduce:
1. Go to a free site
2. Purchase Payton
3. Replace homepage content
4. Go to the site editor and go to styles -> typography -> text

**Comment by markbiek** [comment]
Thanks to @pbking for digging into this.

It seems that the issue was that the `theme.json` files had been updated but not deployed. They've been deployed and I'm now seeing the full font list for the theme.

paYKcK-2cp-p2
