### ISSUE TITLE
Nesting Quote blocks cannot be merged with other Quotes using backspace/delete

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#66283]
### What

A user shared in 36219697-hc that they wished they could still key DELETE or BACKSPACE to move a paragraph block that follows a quote block up into the quote block. 

It seems this isn't possible anymore now that the quote blocks are nested, following this update: https://github.com/WordPress/gutenberg/pull/25892

I showed the user how to drag/drop blocks using **List View** as a workaround, but also assured them I'd pass their feedback along.

### Why

This would make it possible to merge 2 Quote blocks, or to move a paragraph block up into a quote block, using keystrokes, rather than dragging/dropping in the editor.

**Comment by Greatdane** [comment]
Yes, I don't think this is possible now that paragraph blocks and nested within the quote blocks. 

I am going to close this for now (dragging and dropping on list view should be how we do this, consistent with moving any other block), but we have a record of the user's feedback at least!
