### ISSUE TITLE
Sites Management Page: Improve performance while typing

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66295]
I have 594 rows in my table, and typing the first character into the search box takes ~250ms. When I type I expect the characters to appear on screen instantly, so this delay feels janky.

594 sites is not typical so I'm not the average user. But it's possible there are tweak we can make that would improve things. With some help from the React dev tools.

Another option would be to debouce the event handler for the search box so that at least the characters appear quickly in the input box even though it will take some time before the search results update. I shy away from this because for the average user with only a few sites we'll be making the search less responsive.

Done is:
- [ ] Typing in the search box feels responsive. Being able to re-render in under 16ms (or 60fps) is a good benchmark, but any improvement would be good.

**Comment by p-jackson** [comment]
Made some improvements in #66392. Halved the amount of time the JS takes to run when the user types their first character. CSS perf appears to be the slowest part now.

**Comment by danielbachhuber** [comment]
> CSS perf appears to be the slowest part now.

@p-jackson Out of curiosity, what do you think is slow about the CSS?

**Comment by p-jackson** [comment]
I've been doing some Googling about it to find out. The `key` prop for each row means that React should be doing an efficient job of rearranging the DOM elements, and that makes me think that there's something about the row style that makes doing a re-layout expensive. Maybe some sort of `position: absolute | relative` in one of the row components that makes layout hard? I'm just sort of throwing ideas out there 😄 But I'm sure we're not the first people to want to rearrange a large number of React elements.

Sometimes I've improved this sort of thing by using a CSS trick to "promote" an element into it's own layer in video memory, and then the browser can translate it around the screen super fast. I think it was a `transform` rule that does it. But I'm not sure that'd work in this case (and maybe not great to promote so many layers?)

**Comment by p-jackson** [comment]
I'm not going to do any more towards this for i1. Javascript perf has certainly improved, but we might be close to the limit for what we can do with a table of this many rows when it comes to CSS performance.
We could render as a [virtualised list](https://github.com/bvaughn/react-virtualized), but that's another order of magnitude in terms of complexity.
