### ISSUE TITLE
Marketplace search: get recommended plugins

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#66303]
Subtask of https://github.com/Automattic/wp-calypso/issues/63717

Based on this comment: pdh6GB-sk-p2#comment-1639

We need to create a new query and an endpoint to be able to serve recommended plugins based on the slug of the current plugin.

### Query

With ES we can perform different aggregations (related, frequent, [uncommonly_common](https://www.elastic.co/blog/significant-terms-aggregation)) to get the list of recommended plugins. Greg created an example query here: 2c775-pb/#php

### Endpoint

We need to create a new endpoint that can takes a list of one or more plugin slugs and returns a list of plugins, using some of the aggregation algorithms above.

### URL scheme

`/marketplace/<slug>/recommended`

**Comment by cpapazoglou** [comment]
Closing this for now.
