### ISSUE TITLE
Marketplace search: get related plugins

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#66301]
Subtask of #63717

Based on this comment: pdh6GB-sk-p2#comment-1639

We need to create a new query and an endpoint to be able to serve related plugins based on slug (or ID). ES supports a [More like this](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html) (MLT) query type that selects similar documents based on a set of terms.

### Query
We can build the MLT query based on the existing related posts query (the file has been deleted, so it's not on opengrok, trac: r248665-wpcom/trunk/wp-content/plugins/elasticsearch/querying/class.es-extract-mlt-query.php)

As Greg has mentioned, we need to modify the query to work on top of the Jetpack Search index (running the query against the all_content.en field).

### Endpoint

There's an existing endpoint for serving related posts: `class.wpcom-json-api-related-site-endpoint.php` This endpoint uses ES filters, so it should be easy to add filtering based on what the site is already doing or any extra context for the user.

We can also add TrainTracks events similarly to https://github.com/Automattic/wp-calypso/issues/64614 to be able to track clicks

### URL scheme

`/marketplace/<slug>/related`

**Comment by gcsecsey** [comment]
I've forked the `sites/%s/post/%s/related` endpoint to create a new endpoint under `/marketplace/%s/related` where the path parameter will be the Calypso product slug. D116097-code is the draft diff with the forked endpoint.

Since then, I've been reading more about how the MLT query works in Elasticsearch, and how the related endpoints that are used in reader and in wpcom related posts are using it currently. It seems there have been some changes recently to the Elasticsearch codebase, the MLT query parts of the related posts code were moved in these diffs:
- D83607-code
- D83546-code

The `Reader_Post_Related` class currently supports getting recommendation from the same blog, or globally using the `global-temporal` index. Our requirements differ slightly in needing to get recommendations from 2 different blogs, and the content lives in the `jetpack-search` index. I'm currently looking into how it'd be best to extend this class to support our use-case as well.

**Comment by gcsecsey** [comment]
D116097-code is now ready to be reviewed

**Comment by gcsecsey** [comment]
There was a mockup in Figma about how these cards would be displayed in Calypso:
<img width="791" alt="CleanShot 2023-08-04 at 10 39 11@2x" src="https://github.com/Automattic/wp-calypso/assets/11555574/edd5a728-4abf-4299-a1ef-28b993d6ae95">

Based on this, I've created this schema to be returned from the endpoint. The response is an array of these objects:
```json
[
    {
        "_id": "113771570-p-8822811",
        "_score": 2307.4941,
        "fields": {
            "blog_id": 113771570,
            "excerpt": "Customize AutomateWoo custom workflow emails using YayMail – WooCommerce Email Customizer",
            "icon": "https://woocommerce.com/wp-content/uploads/2021/11/email-customizer-for-automatewoo-2.png",
            "marketplace_slug": "email-customizer-for-automatewoo",
            "post_id": 8822811,
            "product_slug": null,
            "slug": "email-customizer-for-automatewoo",
            "title": "Email Customizer for AutomateWoo"
        }
    }
]
```

We can iterate on this, and add the resulting schema to the data layer in Calypso:
- we can add the main category using the `plugin.categories` field
- the prices will need to be fetched from the WPCOM store
- the `_id`, `_score`, `blog_id` and `post_id` fields are only used for testing, or needed if we do additional lookups from ES for the same product, otherwise these can be removed

**Comment by gcsecsey** [comment]
I'm updating the points on this story from `3` to `5`, because
- resolving the plugin in Elasticsearch by slug
- adapting the MLT query to plugins from the Reader class (which works with blog posts)

have taken additional time to implement and test. We haven't considered these factors in such detail when estimating the issue.

**Comment by gcsecsey** [comment]
Changes deployed in r272935-wpcom

**Comment by WBerredo** [comment]
Are there any reasons for the request results to not be encapsulated in `body.data` as other WP.com requests?

As there is this pattern in other requests I think the Calypso `wp` package assumes it as default and try to read directly from this structure.

**Comment by WBerredo** [comment]
Digging a bit into WP.com code I found `rest_ensure_response` adds the `data` encapsulation, but I'm not entirely sure about how to add the `body`.

**Comment by gcsecsey** [comment]
> Are there any reasons for the request results to not be encapsulated in body.data as other WP.com requests?

No, we can encapsulate the data the same way to make parsing easier on the client side.

> Digging a bit into WP.com code I found rest_ensure_response adds the data encapsulation, but I'm not entirely sure about how to add the body.

I'll look into using `rest_ensure_response` and raise a small diff.

**Comment by gcsecsey** [comment]
Raised diff: D119347-code
