### ISSUE TITLE
calypso_signup_site_vertical_submit trends should look identical in both vertical_title & vertical_id trend views

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#66306]
# Description
 The Tracks Trends view for calypso_signup_site_vertical_submit with prop= vertical_id should look identical to prop=vertical title--but they do not. See comment in https://github.com/Automattic/wp-calypso/pull/66249#issuecomment-1206385178

There should be a 1:1 relationship with vertical_title & vertical_id, but this is not true for "Something else".

In each trend view null and "Something else" should have the same count - meaning the null count should be the same for the id view and the vertical_title view.   I think "Something else" is being recorded as vertical_id = null. If so, maybe we need to give "Something else" a special id, like -1. Or maybe there is a better idea?

https://user-images.githubusercontent.com/5665959/183076235-ccd4f9a2-9805-4500-a090-c7becdffb5dc.png

![Image](https://user-images.githubusercontent.com/5665959/183077265-2ad23092-4bff-4c81-a1c0-8294ffc90372.png)

# Acceptance Criteria
- [ ] each value in the vertical dropdown list must have a unique ID, including "Something else"
- [ ] null value should only be recorded if the user has not selected any value in the drop down list (right now this means use clicked continue or user clicked skip

# Testing
* because tracks data is shown in discrete days we need to test this 2 or 3 days after the code change is merged into production

**Comment by autumnfjeld** [comment]
@bangank36  Would you want to work on this?   Let me know if you have any questions. :)

**Comment by bangank36** [comment]
> @bangank36 Would you want to work on this? Let me know if you have any questions. :)

Sure, I can take care of this next week

**Comment by bangank36** [comment]
> maybe we need to give "Something else" a special id, like -1.

I think this should work, since the id will be used for metrics only

**Comment by bangank36** [comment]
> because tracks data is shown in discrete days we need to test this 2 or 3 days after the code change is merged into production

#66330 has been deployed, so I moved this issue to "In Progress" to test the result in next several days

**Comment by autumnfjeld** [comment]
>  "In Progress" to test the result in next several days

perfect. Thank you!

**Comment by bangank36** [comment]
Tracked the TRACKS trends view and confirmed that `vertical_id` and `vertical_title` had the same count. Close this ticket as mission accomplished
