### ISSUE TITLE
Gutenberg: long anchors make the list view take a lot of space

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#66300]
### Quick summary

When adding long HTML anchors to a block in the Advanced settings, the list view in the editor takes more and more space on the screen.

### Steps to reproduce

1. Add a block
2. Open the list view
3. Go to block settings > Advanced > HTML anchor
4. Add a long anchor text
5. Notice the width of the list view getting bigger

### What you expected to happen

The width of the list view to stay the same
![Uploading image.png…]()

### What actually happened

The list view gets bigger, and makes the editor too small
![image](https://user-images.githubusercontent.com/81776920/183060683-1dac1fab-846c-4af6-8d61-6b74783aebe8.png)

### Context

5453488-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Browser, operating system and other notes

Firefox 103 on macOS (Catalina) - doesn't look specific

### Reproducibility

Consistent

### Severity

All

### Workaround details

The issue seems to be coming from this backend CSS code:

.block-editor-list-view-leaf .block-editor-list-view-block-select-button__anchor {
  max-width: min(100px,40%);
}

It can be replaced with this instead:

.block-editor-list-view-leaf .block-editor-list-view-block-select-button__anchor {
  max-width: min(100px,40vw);
}

**Comment by KirkwallDay** [comment]
- [ ] Another instance here: 36387662-hc

**Comment by renata-franco** [comment]
📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - Yes

------

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate it on Simple, AT, and self-hosted sites. 

**Simple:**

![imagen](https://user-images.githubusercontent.com/81378719/183941984-781f789d-0c5d-441d-8083-3cfbb2c49f8a.png)


**AT site:**

![imagen](https://user-images.githubusercontent.com/81378719/183941386-eed9fb32-2d30-4266-8ce6-1b98c2ab1d08.png)

**Self-Hosted:**

![imagen](https://user-images.githubusercontent.com/81378719/183941783-a843bccc-6ac1-4f2d-84fd-e7766c46f3fe.png)

Here is a video of what it looks like: 


https://user-images.githubusercontent.com/81378719/183942352-4e5c8489-1a6e-441f-886c-3a2b25691928.mp4



------

📌 ACTIONS

- Marked as Triaged for Quality Squad review

**Comment by Robertght** [comment]
Looks like it's gonna be fixed in the 14.0 release: https://github.com/WordPress/gutenberg/pull/43134

**Comment by annezazu** [comment]
Closing out as this has been fixed :) https://github.com/WordPress/gutenberg/pull/43134
