### ISSUE TITLE
Incorrect price for "Ultimate Traffic Guide" plus some minor copy mistakes

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#66320]
### Quick summary

The guide https://wordpress.com/marketing/ultimate-traffic-guide/DOMAIN/ contains some copy mistakes such as:

- "Face**B**ook"
- "guides like this often cost **$0** or more"
- "In fact, if you act today you’ll pay just **$0** for The Ultimate Traffic Guide."

<img width="936" alt="This guide will teach you everything you need to know from which email marketing tools" src="https://user-images.githubusercontent.com/31009008/183144839-bfd7b3af-6b53-4a03-83e2-3fd1939b361c.png">

### Steps to reproduce

1. Go to https://wordpress.com/marketing/ultimate-traffic-guide/DOMAIN/

### What you expected to happen

Copy fixes, and most importantly, correct the price.

### What actually happened

Incorrect Price

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by romitgithub** [comment]
@davipontesblog Could you please share the correct copy content?

**Comment by davipontesblog** [comment]
@romitgithub this might require a comment from someone in the Marketing team. 
@donlair is this still relevant or have we removed that page from calypso now?

**Comment by cuemarie** [comment]
I believe this page has been removed from Calypso. Tools > Marketing includes this: 

![Markup on 2023-05-03 at 12:17:25](https://user-images.githubusercontent.com/27249804/236021478-ad6074c1-8f33-49be-940d-d6edbad49890.png)

And https://wordpress.com/marketing/ultimate-traffic-guide/DOMAIN/ now redirects to https://wordpress.com/learn/courses/intro-to-seo/

Closing out.
