### ISSUE TITLE
Remove hamburger/menu icon from design thumbnails

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#66335]
## Description
From pdtkmj-h8-p2#comment-509.

In mobile screen sizes, showing hamburger/menu icon in the design previews might mislead users in thinking they are draggable toggle icons.See screenshot for reference:

![Image](https://user-images.githubusercontent.com/797888/183354872-d19123a8-5b87-4627-9003-d831b88ee5d9.png)

NOTE ! If this is not a super straightforward simple task, then let's not do it. It ins't worth doing anything complicated.

## Acceptance Criteria
- [ ] Hide hamburger/menu icon when thumbnail is rendered via mShots.
- [ ] Hide hamburger/menu icon when thumbnail is rendered via iframe.

**Comment by autumnfjeld** [comment]
If this is not a super simple task, meaning if there is any technical complication, then let's just leave it as it is.  I think it very debateable on whether users would be confused with this.

**Comment by roo2** [comment]
Since the images are generated with mshots, I don't see an easy way to modify them in a way that would remove the hamburger menu. I think we would have to add another parameter to the `/block-previews/site` endpoint that hides the hamburger menu, which would be a substantial task.

**Comment by arthur791004** [comment]
> I think it very debateable on whether users would be confused with this.

Agreed. I think we could work on this when we receive for more feedback on the user's confusion.

**Comment by taipeicoder** [comment]
+1
