### ISSUE TITLE
[All] Consider relocating RTL/LTR CSS URL generation logic

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66336]
More context can be found in the following patch: D85354-code - in its description, below _"A couple notes on the RTL logic implementation"_ heading.

**Comment by mashikag** [comment]
I would suggest implementing static methods instead of relocating the code.

**Comment by yansern** [comment]
Requoting what I've said here: D85354-code#1786604

I think WordPressMailer should be made smart enough to know what CSS file to load without needing implementors to explicitly decide what CSS file to load for every e-mail template we create.

**Comment by mashikag** [comment]
This is done. The `HTML_Email` class is now responsible for implicitly applying the LTR/RTL stylesheet.
