### ISSUE TITLE
General styling: remove `long-content-fade` SCSS mixin and use the one exported by `@wordpress/base-styles`

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#66350]
### Details

We're defining our own version of the [`long-content-fade`](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/stylesheets/shared/mixins/_long-content-fade.scss) mixin and it's pretty much a copy-paste of [what we have in `@wordpress/base-styles`](https://github.com/WordPress/gutenberg/blob/6ecb4c7740c3767f30878a3c639367a290dbbfba/packages/base-styles/_mixins.scss#L63).

It's a good idea to remove our version and use the one shipped by the agnostic package. That way, we'd have a single source of truth and something that the community maintains, essentially one less point of maintenance for us.

### Checklist

- [x] In `@wordpress/base-styles`, extract the `long-content-fade` mixin to its own file so we can import it exclusively
- [ ] Remove the version from Calypso and import the `long-content-fade` file inside `client/assets/stylesheets/shared/mixins/_mixins.scss`
- [ ] Check that all usages of `long-content-fade` did not introduce regressions, including the places where we're not defining the `$color` variable, which has a different default value in the mixin definition

### Related

#65598.

**Comment by vykes-mac** [comment]
created a PR https://github.com/WordPress/gutenberg/pull/46485. Seems I can't add labels as a first time contributer

**Comment by p-jackson** [comment]
w.r.t WordPress/gutenberg#46485 see p1671421937566529-slack-C0347E545HR

Is it really necessary to change our upstream dependency? What's the harm of importing a bunch of SCSS mixins if they don't get used? If there are naming collisions perhaps it'd be better for us to change _our_ names to avoid confusion with the GB mixins anyway.

**Comment by zaguiini** [comment]
Are we going to work on this? 👀

**Comment by vykes-mac** [comment]
I looked at this and the change that is required for this simple thing has gotten huge. I don't think the effort is worth the results.

**Comment by autumnfjeld** [comment]
Should this be closed? Or moved into the backlog?

**Comment by vykes-mac** [comment]
Yup I intended to close it

**Comment by autumnfjeld** [comment]
I'm going to move this out of "Groundskeeping Maintance"

Can this be closed @vykes-mac ?

**Comment by vykes-mac** [comment]
Yeah it can be closed
