### ISSUE TITLE
Sites Management Dashboard: Improve mobile view of site content controls 

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#66359]
### Details

After introducing tile view and the mode toggle, we're actually consuming a lot of space on small screens and it's looking not only ugly but terrible from a UX perspective:

![image](https://user-images.githubusercontent.com/26530524/183485137-2bf1b34f-25e4-41c9-8fc2-1e50f269ceb7.png)

We can improve this by making the search fully occupy the first row and then putting the dropdown and mode toggle on the second row.

### Related

Related to #66247

**Comment by danielbachhuber** [comment]
Saxon gave his thumbs up in p1660080585556929/1660072726.351699-slack-C0347E545HR
