### ISSUE TITLE
[Bug]: Final characters in the search input are invisible

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#66364]
### Quick summary

If enough text is typed into the search input component that the text overflows the input box, the final few characters are invisible until you type more text so they appear again. You can also make the text cursor itself invisible.

https://user-images.githubusercontent.com/6265975/183508474-33af1ae0-ff69-45a7-b9c5-380effa856ca.mov

### Steps to reproduce

1. Run `yarn workspace @automattic/search run storybook`
2. Once running, visit http://localhost:49901/?path=/story/search--with-different-color
3. Type a lot of text into the red search input box, such that it overflows the input

### What you expected to happen

All text should be visible.

### What actually happened

The text towards the end of the search input is invisible from the fade-out style.

### Reproducibility

Consistent

### Available workarounds?

No but the platform is still usable

**Comment by romitgithub** [comment]
@noahtallen What's the expected fix here? Should I just add padding-right to the input?

Trying to understand what is the use of fade layover here?

**Comment by romitgithub** [comment]
Or a better solution would be to hide the overlay when input is in focus.

**Comment by noahtallen** [comment]
Good question -- I also think hiding that while focused could work well.

**Comment by mpkelly** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/69217
