### ISSUE TITLE
Premium Theme: Munchies

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#66371]
### Details

The Munchies premium theme needs the following:

### Checklist

Already done:
* [Demo site](Peaf0H-l-p2) setup.
* Theme showcase page draft.

To do:
- [x] Headstart annotations (guide: paYKcK-1Pt-p2)
- [x] GlotPress project (guide: paYKcK-1Pt-p2)
- [x] Launch process (launch guide: PNEWy-eBM-p2)

**Comment by alaczek** [comment]
I tried generating headstart annotations and they looked good to me, except for the nav menu, which contained items like "Blog" and "Testimonials", and wasn't the actual menu displayed on the demo site. If someone can figure out where that menu is coming from and how to fix it, that would be awesome (I didn't commit my experimental headstart annotations).

**Comment by michaeldcain** [comment]
> except for the nav menu, which contained items like "Blog" and "Testimonials", and wasn't the actual menu displayed on the demo site

I looked at this with @valterlorran and it looks like Headstart is copying legacy nav menus instead of the new FSE navigation block post type. Valter is working on adding that support in D85195-code

**Comment by sixhours** [comment]
> I tried generating headstart annotations and they looked good to me, except for the nav menu, which contained items like "Blog" and "Testimonials", and wasn't the actual menu displayed on the demo site. If someone can figure out where that menu is coming from and how to fix it, that would be awesome (I didn't commit my experimental headstart annotations).

@valterlorran and I looked at this today and found a super secret (well not really) `wp_navigation` post type area that had a bunch of old menus in it. I don't claim to understand how FSE works, but you can manage existing menus for a site from `/wp-admin/edit.php?post_type=wp_navigation`. I cleared out all the menus labeled "Primary" on the Munchies demo site, then re-set-up the menu block in the header and saved it. That seems to have fixed the issue and now Headstart will grab the correct navigation menu with Valter's patch. :D

**Comment by alaczek** [comment]
Sounds like all of this stems from the old demo content and legacy post types being pulled in. This goes beyond this ticket, but it would be great if we could update the source of the demo site content in the demo gen script to something more modern, maybe Vivre or Livro?

**Comment by valterlorran** [comment]
Sounds good to me. I will take a look to learn more about it. Thanks!

**Comment by markbiek** [comment]
- Headstart annotation deployed: D87326-code
- Linguine strand id: 138046
- Glotpress project deployed: D87334-code

**Comment by markbiek** [comment]
PNEWy-eBM-p2

**Comment by markbiek** [comment]
And we're launched!

https://wordpress.com/theme/munchies
