### ISSUE TITLE
[Spike] Sites Management Page: "Hidden" sites don't appear unless the user searches for them

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66380]
Calypso allows you to "hide" sites using this legacy interface https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs&show=hidden

The Calypso site switcher doesn't display these sites by default
![Image](https://user-images.githubusercontent.com/1500769/183569755-f73aa4ea-858e-4f54-b690-4d0e29c9f83e.png)

But as soon as you start typing in the site switcher's search box the hidden sites appear.

I don't know how often this is used by customers, but a12s use this feature a lot.

In terms of design we don't know whether we'd want to expose this feature using some text at the bottom of the page (like the site switcher does), or using a filter dropdown which is more in keeping with the current design. Or whether we want to have the feature at all. That's why this is a spike. @SaxonF @vindl 

This spike is done when:
- we understand whether it'll be trivial to access a site's hidden flag using our current way of fetching site excerpts. It's also possible that this data comes from a different endpoint, which would make implementing this feature a touch more difficult.

**Comment by danielbachhuber** [comment]
The `<SiteSelector>` component uses `getVisibleSites()` to determine which sites are visible vs. hidden:

https://github.com/Automattic/wp-calypso/blob/0b34a51b66b803979b309150ca3fbfc55ba5c549/client/components/site-selector/index.jsx#L567

Like @wojtekn identified earlier, `getVisibleSites()` simply filters on the `visible` attribute:

https://github.com/Automattic/wp-calypso/blob/0b34a51b66b803979b309150ca3fbfc55ba5c549/client/state/selectors/get-visible-sites.js#L11-L17

**Comment by danielbachhuber** [comment]
I put together a prototype with #66459
