### ISSUE TITLE
Sites Management Page: Grid/Table toggle button updates on its own if you toggle it too quickly

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66381]
The layout toggle on the sites management page gets all confused if you switch it too quickly. It probably has something to do with clicking the toggle while the network request to persist the setting is still in transit.

https://user-images.githubusercontent.com/1500769/183571705-602881aa-8794-4151-a04c-1f4b76b97e95.mov

##### Steps
1. `/sites-dashboard`
2. Quickly toggle to the other mode, and then back to the original mode
3. After a few milliseconds the toggle will change on its own

**Comment by danielbachhuber** [comment]
> The layout toggle on the sites management page gets all confused if you switch it too quickly.

@p-jackson It's a feature, not a bug? 😄

**Comment by zaguiini** [comment]
I think the solution for this would be to disable switching until saving was completed.
