### ISSUE TITLE
SignUp: Add loading step

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#66396]
### Details

After submitting the form there should be a loading step, according to this [design spec](https://www.figma.com/file/BcUdhLlhAp7UHtQHNTI4zA/Tailored-Onboarding-%26-Launchpad?node-id=1865%3A18108)

**Comment by alshakero** [comment]
This was done by [this](https://github.com/Automattic/wp-calypso/pull/66397), right?

**Comment by renancarvalho** [comment]
Yes, this can be closed.
