### ISSUE TITLE
[New Comment] Implement heading as per design

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#66405]
### Details

The updated _New Comment_ email template should include the "New comment!" heading:

Before:

![Markup on 2022-08-10 at 10:54:20](https://user-images.githubusercontent.com/25105483/183859638-3f08378a-6aa0-4f4b-8a3b-ec4fee5106b2.png)

After:

![Screenshot 2022-08-09 at 16 10 41](https://user-images.githubusercontent.com/2019970/183671183-492b0409-aff1-4f02-aef9-babcf7569ec3.png)

**Comment by ivan-ottinger** [comment]
D85720-code patch is now deployed. → Closing this issue.

**Comment by ivan-ottinger** [comment]
D85720-code patch is now deployed. → Closing this issue.
