### ISSUE TITLE
[New Comment] Validate pingback and trackback emails

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#66408]
All the new comment work needs to be completed first.

**Comment by yansern** [comment]
If possible to isolate this, pingback & trackback send it with old emails first.

**Comment by yansern** [comment]
The code-D86796 isolate puts pingback & trackback from the current scope of work. Moving this back to backlog.

**Comment by mashikag** [comment]
Ensure we are using the old comment template for those.

**Comment by ivan-ottinger** [comment]
At the end it looks like the old email template for pingbacks and trackbacks should be still in use. Here is the related patch that removed the feature flag - so you don't have to search for it: D88972-code.



![Image](https://user-images.githubusercontent.com/25105483/194092417-6347e6bf-f513-455b-ab4b-11fb7f7d5f2a.png)

**Comment by phcp** [comment]
Looking to the code seems that the only issue is the email version, that should be 1.0 for trackback and pingback emails.
D88972-code#C5002645NL494

**Comment by ivan-ottinger** [comment]
> Looking to the code seems that the only issue is the email version, that should be 1.0 for trackback and pingback emails.
D88972-code#C5002645NL494

That's a great catch! Looking at the code, the issue has been there since we launched the New Comment email template / enabled the flag.

**Comment by mashikag** [comment]
Thanks @phcp and @ivan-ottinger for helping out with this! 🙌  

> Looking to the code seems that the only issue is the email version, that should be 1.0 for trackback and pingback emails.
D88972-code#C5002645NL494

Great catch @phcp ! 👏  In that case I will close this issue and create a new one specifically about the email version.

**Comment by mashikag** [comment]
Closing this issue as we did not upgrade the pingback and trackback emails to use the new templates. They are still using the old ones. Resolving the following issue ensured the old templates are applied: https://github.com/Automattic/wp-calypso/issues/67263
