### ISSUE TITLE
[Bug]: Unified Design Picker: Does not work with intent-less sites

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#66419]
### Quick summary

When the unified design picker is on, /setup/designSetup no longer works with sites that don't have an intent collected.

CC @Automattic/ganon 

### Steps to reproduce

* Have a site that was created without an intent (example: 2d1e7-pb ) 
* Be in an environment with the `signup/design-picker-unified` flag on (example: calypso localhost)
* Visit `http://calypso.localhost:3000/setup/designSetup?siteSlug=SITESLUG`
* Expect to see: Designs to pick from
* Actually see: No designs and a console error `Invalid parameter(s): intent`
* Rolling back D85183-code fixes it

The page makes a request to `/wpcom/v2/starter-designs?_envelope=1&vertical_id=&intent=&seed=SITESLUG&_locale=en
` which returns 

```
{
	"body": {
		"code": "rest_invalid_param",
		"message": "Invalid parameter(s): intent",
		"data": {
			"status": 400,
			"params": {
				"intent": "Invalid parameter."
			},
			"details": []
		}
	},
	"status": 400,
	"headers": {
		"Allow": "GET"
	}
}
```

### Reproducibility

Consistent

**Comment by taipeicoder** [comment]
@mreishus thanks for letting us know about this issue! We've pushed a fix in D85686-code. Could you explain the flow that would lead to the UDP without site intent?

**Comment by autumnfjeld** [comment]
> Could you explain the flow that would lead to the UDP without site intent?

Yes, this is key.  It sounds like this issue is an edge case that would never happen in onboarding flow.

**Comment by mreishus** [comment]
Internally, we directly visit the url to test changes to the design picker.
Externally, it looks like various site importers can send users to the design picker:
Example:
https://github.com/Automattic/wp-calypso/blob/3f71a8039b7b0dc0b23e3e6c7573ea1d9a19dc3f/client/blocks/importer/wix/index.tsx#L126-L129
https://github.com/Automattic/wp-calypso/blob/3f71a8039b7b0dc0b23e3e6c7573ea1d9a19dc3f/client/blocks/importer/wordpress/import-content-only/index.tsx#L92-L93
#65926 + #66385
I agree it's not something that comes up while making a new site, but keeping the ability to test the design picker on all sites seems really handy.
