### ISSUE TITLE
[Bug]: RSS Block "Number of Items" Setting

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#66414]
### Quick summary

Per our support docs, the [RSS Block](https://wordpress.com/support/wordpress-editor/blocks/rss-block/)'s "Number of Items" setting allows you to "choose the number of items that will display from the RSS feed. The maximum number of items is 10."

However, you can increase the number of items to display to 20 but the block will only display 10 items as expected. 

### Steps to reproduce

1. Add an RSS Block and enter a URL for a blog feed. Make sure the blog has at least 20 posts. 
2. Open the block's settings and set the number of items to "20"
3. Publish and view the page. 

### What you expected to happen

The page should display 20 items as per the setting: 

![Annotation on 2022-08-09 at 13-30-07](https://user-images.githubusercontent.com/10015451/183726458-30023425-8b00-49d2-9ef4-9288e407f890.png)

### What actually happened

Only 10 are displayed.

 If 10 items are to only be displayed, then the toggle or text field next to the toggle should not accept a number greater than 10. The user reporting this would like to see this block accept up to 20 items. 

### Context

Customer report and replicated through my own testing

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The Latest Posts Block: https://wordpress.com/support/wordpress-editor/blocks/latest-posts-block/

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on AT: **Could Not Replicate** / Working as designed

📌 FINDINGS/SCREENSHOTS/VIDEO
- When using the RSS block, the feed's results will be limited by the number of posts include in the site's feed.
- By default, WordPress.com feed settings are set to 10 under Settings > Writing > Feed Settings. 
- If I update the Feed settings there to 30, then share the URL for that site through an RSS block, I am able to display more than 10 posts.

*Example*

![Markup on 2022-10-06 at 18:30:27](https://user-images.githubusercontent.com/27249804/194447479-e84f40a9-a8f9-4585-997a-a5b4880edaa1.png)

![Markup on 2022-10-06 at 18:30:13](https://user-images.githubusercontent.com/27249804/194447474-1c49539a-af23-4d94-9159-bf175e52ee23.png)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
