### ISSUE TITLE
[New Liked Comment] Fix email sent out in liker’s language

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#66420]
More details at pb6Nl-fi7-p2#comment-99696

**Comment by ivan-ottinger** [comment]
Related issue: 5404-gh-Automattic/p2.

**Comment by mashikag** [comment]
Related issue: pd4QKa-Ar-p2
p1660220200872519-slack-C03NN1C1ERF

**Comment by yansern** [comment]
**Explanation:**
A RTL user liking a comment of a user (LTR) on his LTR site, the user receives the email in RTL.


![image](https://user-images.githubusercontent.com/1287077/187722740-56895a58-72f8-418b-87f2-e9410e3119ae.png)

**Comment by phcp** [comment]
D88275-code is now merged and deployed.
