### ISSUE TITLE
Permalinks displaying post IDs when in drafts and scheduled.

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#66433]
### Quick summary

<img width="351" alt="Screen Shot 2022-08-10 at 14 39 40" src="https://user-images.githubusercontent.com/92185881/183832684-647829c9-2841-4e18-9b14-d1f5a8bd72d5.png">

Permalinks are displaying the plain post ID instead of the edited URL in drafts and when scheduled to be published at a later date.

Is there a way to display the URL without clicking on "URL" to preview it?

### Steps to reproduce

1. Create a new post.
2. Add a new title and then save it in draft, or schedule to publish at a later date.
3. Click on the URL to edit the permalink.
4. URL still shows the post ID instead of the permalink.

### What you expected to happen

The permalink would be displayed.

### What actually happened

URL showed the post ID instead.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - Yes. Reported here: Repo: https://github.com/WordPress/gutenberg/issues/43161

📌 FINDINGS/SCREENSHOTS/VIDEO
-  Replicated in all test environments except for P2. See screenshots below

#### AT

![Markup on 2022-08-11 at 10:46:02](https://user-images.githubusercontent.com/27249804/184200756-fc8b912c-6274-4684-92b7-1599a13273f7.png)

#### Simple

![Markup on 2022-08-11 at 10:46:40](https://user-images.githubusercontent.com/27249804/184200806-91456bea-5f87-4f35-87df-d62b00e5df13.png)

#### Self-Hosted

![Markup on 2022-08-11 at 10:47:07](https://user-images.githubusercontent.com/27249804/184200881-a436766d-dfed-415d-a9cc-a3b1a447c79e.png)

#### P2

![Markup on 2022-08-11 at 10:49:00](https://user-images.githubusercontent.com/27249804/184200930-11df8611-83b5-4e0a-9b60-4beb4ba4d277.png)

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Reported issue in Gutenberg Repo: https://github.com/WordPress/gutenberg/issues/43161
- Added to Cross-Repo watchlist

**Comment by youbrokesomething** [comment]
This is fixed as of Gutenburg 14.1
