### ISSUE TITLE
Unified design picker: Do not show generated designers in the Seller flow

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#66438]
## Description

![Image](https://user-images.githubusercontent.com/5665959/183908679-94603a8a-6de2-45c8-8f0e-2ff2e8c9ca34.png)

Currently, the unified design picker is not showing designs tailored to the Seller flow. Instead, it's showing one generated design for Blog, another for Portfolio, and another for Business Services. Since we currently don't have ant eCommerce recipes, let's not show any generated designs in the unified design picker when the site intent is Sell.

Note that this task blocks the release of the unified design picker.

## Acceptance Criteria
- [x] When the site intent is Sell, do not show any generated designs in the unified design picker.

**Comment by bangank36** [comment]
Closed as landed
