### ISSUE TITLE
Revert flow progress bar .is-fixed style

### ISSUE THREAD

**Issue by bangank36** [Automattic/wp-calypso#66432]
## Description

We should clean up the `is-fixed` implementation for the flow progress bar once the UDP is shipped

## Reference

[Convo](https://github.com/Automattic/wp-calypso/pull/66333#discussion_r941920536)

**Comment by taipeicoder** [comment]
@bangank36 can we close this?

**Comment by bangank36** [comment]
> @bangank36 can we close this?

Sure, closed as landed
