### ISSUE TITLE
[New Comment] Display "You can also reply to this email..." hint

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66442]
The new email templates (_New Comment_ and _New Post_) should include the following tip:

![Image](https://user-images.githubusercontent.com/25105483/183874336-c42d421b-b5a2-4ffe-8ae1-8dc5e156b22b.png)

We need to check whether the display should be conditional.

Figma: c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A23435.

---

TODO:
- [x] https://github.com/Automattic/wp-calypso/issues/66753
- [x] https://github.com/Automattic/wp-calypso/issues/66754
- [x] https://github.com/Automattic/wp-calypso/issues/66755

**Comment by phcp** [comment]
The tip icon is available here: [icons.zip](https://github.com/Automattic/wp-calypso/files/9339745/icons.zip)
@ivan-ottinger @JuanLucha

**Comment by ivan-ottinger** [comment]
Thanks for the icons, Paulo!

**Comment by ivan-ottinger** [comment]
I have divided this task into three separate issues which are now linked in the description above.

**Comment by ivan-ottinger** [comment]
Related issue: https://github.com/Automattic/wp-calypso/issues/66915.

**Comment by ivan-ottinger** [comment]
All three tasks are now done. → Closing this issue.
