### ISSUE TITLE
Unified design picker: Prevent page jumping when switching theme filters

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#66440]
## Description
In the unified design picker, switching the theme filter can sometimes cause the page to jump caused by the number of displayed themes changing. See recording for reference:

https://user-images.githubusercontent.com/797888/183868403-fb7c2895-4cf4-4ab9-adde-9eab1ae66f37.mp4

## Acceptance Criteria
- [ ] Switching the theme filter shouldn't cause a page jump.

**Comment by arthur791004** [comment]
Re-open as the fix has been reverted

**Comment by taipeicoder** [comment]
Closing as #66962 as been merged.
