### ISSUE TITLE
[New Comment] Add icons to the CTA buttons

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66446]
The CTA buttons should include icons:

![Image](https://user-images.githubusercontent.com/25105483/183876474-8bce1bff-2756-45da-9be7-e3e2fe86b5e9.png)

Figma: c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A23435

**Comment by phcp** [comment]
Trash and spam icons are available here: [icons.zip](https://github.com/Automattic/wp-calypso/files/9339745/icons.zip)
@ivan-ottinger @JuanLucha

**Comment by ivan-ottinger** [comment]
Thanks for the icons, Paulo!
