### ISSUE TITLE
[New Liked Comment] Fix incorrect "Trouble clicking?" URL

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66453]
The new template is displaying incorrect "Trouble clicking?" URL:

![Image](https://user-images.githubusercontent.com/25105483/183909242-02ae8c90-90bd-4bea-9bc7-e4e426dec902.png)

Instead of displaying the post URL, it should point to the notification settings page:
![Image](https://user-images.githubusercontent.com/25105483/183909243-9dcf41c2-f70d-4941-8218-812d4f3a5a59.png)

**Comment by ivan-ottinger** [comment]
The old (current) template is pointing to https://wordpress.com/me/notifications (that's where `https://wordpress.com/settings/notifications/?sn=c#settings-notifications` goes to):

![Markup on 2022-08-10 at 17:01:34](https://user-images.githubusercontent.com/25105483/183938301-0fc64678-2d7b-4142-a6b1-2405a7906096.png)

This page allows users to unsubscribe from any site. Users can also unsubscribe from specific type of notification.

---

On the other hand, the "email notification settings" link in the new template currently points to https://wordpress.com/me/notifications/comments:

![Markup on 2022-08-10 at 17:03:50](https://user-images.githubusercontent.com/25105483/183938783-86d1d8ac-88f5-47ba-96e8-a5844819e987.png)

which allows users to unsubscribe from all _New Liked Comment_ emails.

The question is: which link will users find more useful (?)

**Comment by yansern** [comment]
I would say the same as what the current (old) template uses.

**Comment by ivan-ottinger** [comment]
The D85738-code patch is now ready for review.

**Comment by ivan-ottinger** [comment]
I have now merged and deployed the patch.
