### ISSUE TITLE
[New Liked Comment] Consider displaying full comment instead of excerpt

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66450]
It might be better user experience if we display full comment instead of excerpt:

![Image](https://user-images.githubusercontent.com/25105483/183906828-dc630f66-0f6e-4859-bc82-65cb9589fda8.png)

More context: pdtkmj-iG-p2#comment-539.

**Comment by ivan-ottinger** [comment]
Hey @saygunnyc 👋  When a _post comment_ is liked, the related email template currently displays the **comment excerpt** only - as can be seen in the screenshot above. This has been the case since we started working on the new email templates. 

When looking at the design in Figma (c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A21504), the comment is short there and therefore it is not clear whether the intention is to display excerpt or the full comment there.

We have a patch in review (D88944-code) that makes sure the full comment is displayed instead of the excerpt. The reason I am pinging you here is to check your point of view as well - to make sure we are aligned with the original design intention before moving forward. Thank you very much.

---

- similar P2 template issue / discussion: https://github.com/Automattic/p2/issues/5436
- report from the template testing: pdtkmj-iG-p2#comment-537

**Comment by saygunnyc** [comment]
Thanks for the ping @ivan-ottinger! Let's not change the logic of existing emails. I believe they also display the comment excerpt. Please let me know if I'm wrong.

**Comment by ivan-ottinger** [comment]
Thank you for your response Saygun!

> Let's not change the logic of existing emails. I believe they also display the comment excerpt. Please let me know if I'm wrong.

For instance, the _New Comment_ email displays the full comment (outside of the blockquote though):

![Markup on 2022-10-03 at 11:11:53](https://user-images.githubusercontent.com/25105483/193542653-4195aa02-0536-4173-acda-7107dbbdad4f.png)

Here is an example of current email (excerpt) vs what we have in mind (full comment):
![Markup on 2022-10-03 at 11:19:46](https://user-images.githubusercontent.com/25105483/193543391-fb7b3c53-6943-4bce-8dad-63ce1bf86625.png)
![Markup on 2022-10-03 at 11:20:13](https://user-images.githubusercontent.com/25105483/193543395-2e066273-853e-4c58-8a71-29098cf04dee.png)

**Comment by saygunnyc** [comment]
> For instance, the New Comment email displays the full comment (outside of the blockquote though):

This seems wrong. 😄 

I was meaning to ask the initial existing, before we updated the designs.

**Comment by ivan-ottinger** [comment]
> This seems wrong. 😄

This is how it actually was in the old _New Comment_ template as well:

![Markup on 2022-10-03 at 11:39:43](https://user-images.githubusercontent.com/25105483/193547128-7c1ba5db-b554-4c8c-bee9-c9361e7da8f6.png)

→ The template is displaying full comment - outside of the blockquote. What's in the blockquote is the actual content being commented on - either the post content or the previous comment another commenter is responding to.

But I agree, it might not be the best. 🤔 

---

> I was meaning to ask the initial existing, before we updated the designs.

Ah, I misunderstood! :)

The old _Liked Comment_ email template displayed comment excerpt only - not the whole comment. In that case we can keep displaying the excerpt only in the new template as well.

**Comment by saygunnyc** [comment]
Oh, I see, so that one is a comment to a comment.
 
> The old Liked Comment email template displayed comment excerpt only - not the whole comment. In that case we can keep displaying the excerpt only in the new template as well.

Makes sense for now.

**Comment by ivan-ottinger** [comment]
> Oh, I see, so that one is a comment to a comment.

Yes, even when the comment is left on a post directly (not as a response to existing comment), the post content is displayed in that blockquote.

> Makes sense for now.

Thank you for sharing the design point of view, Saygun! We will not make the change then and leave the comment excerpt there.
