### ISSUE TITLE
Purchases: placeholder for Manage Purchase looks odd in smaller screens

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#665]
This is what the placeholders for Manage Purchase looks like in smaller devices:

![screen shot 2015-11-24 at 19 54 03](https://cloud.githubusercontent.com/assets/1248436/11377243/292c8d86-92e5-11e5-8b61-e905b060ffb2.png)

Note how the placeholders for the purchase details take no horizontal space.

cc @mikeshelton1503

**Comment by mikeshelton1503** [comment]
Good catch @fabianapsimoes It should be something more like this:

![image](https://cloud.githubusercontent.com/assets/12596797/11377583/9412455e-92b4-11e5-99d6-ac1e726bc980.png)
