### ISSUE TITLE
Marketplace: Prevent vectors of attack to be sent through searches

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#66506]
As seen here pdh6GB-1LG-p2#comment-2602 let's prevent users from searching with possible vector of attacks as searches:

- [ ] Block searches containing html tags to hit the backend.
- [ ] Block searches containing html tags to send tracks events.
- [ ] Send some kind of no results message when the user hits enter.

Any other vectors of attack we should block? please add to the list.

**Comment by lsl** [comment]
These are handled server side.
