### ISSUE TITLE
[Editor] Content alignment/padding issues

### ISSUE THREAD

**Issue by cometgrrl** [Automattic/wp-calypso#66516]
### Quick summary

When not in fullscreen mode, if you have the Calypso sidebar open and the post/block settings on the right, when the browser window is narrower than a certain width, the left and right padding seems to be lost.

Also, the Stats menu item seems to be making the sidebar wider than it needs to be with the stats graphic so far to the right, which is probably exacerbating the issue.

### Steps to reproduce

- Open a post or page in the editor
- Make sure it's NOT in fullscreen mode
- Open the post/block settings sidebar
- Make the browser window narrower and narrower

Attached are screen recordings comparing to core behavior. 

https://user-images.githubusercontent.com/86427589/184263750-13ef8bba-894f-4c6e-95b9-b2ab0b79c150.mov

https://user-images.githubusercontent.com/86427589/184263758-65ad9fcb-2966-4f2b-9b98-e5dcfed43f32.mov

### What you expected to happen

As the window gets narrower, there should be some padding maintained, similar to core behavior.

### What actually happened

When the window is narrow, there's no left or right padding.

### Context

Reported in Slack. p1660236176410749-slack-C029GN3KD

Reported again here p1673374961019329-slack-C9EJ7KSGH

Looks like ~1300px is where it abuts the sidebar and doesn’t break down to a narrower view. So there’s padding north of 1300px but everything under that loses any padding.

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

If you have a large monitor, you can make the browser wide enough to not encounter this issue.

**Comment by vykes-mac** [comment]
@cometgrrl are you still able to reproduce this issue? I tried an was unable to reproduce it.

**Comment by cometgrrl** [comment]
Yes! Let me know if you need help, I think Andrew says it happens when the width is less than 1300px.

**Comment by nelsonec87** [comment]
@cometgrrl , I've tried to reproduce it as well, went below 1000px width (the window size is shown in the top right corner), but the padding seems ok:

- Version 108.0.5359.124 (Official Build) (x86_64)
- MacOS 13.0.1 - Intel

https://user-images.githubusercontent.com/3801502/211955386-76171219-e178-46cc-ae4e-817474511732.mp4

**Comment by cometgrrl** [comment]
Hmm, browser or OS dependent maybe?  I have Chrome Version 108.0.5359.124 (Official Build) (arm64) and Mac OS 13.1 on an M1 Pro.

https://user-images.githubusercontent.com/86427589/211956543-806f19c6-8c78-4fcb-b326-a39a6c1ac247.mov

**Comment by nelsonec87** [comment]
I've updated my comment with Browser/OS versions in case it helps :)

**Comment by vykes-mac** [comment]
@nelsonec87 was your editor set to fullscreen when open the post? I wasn't able to reproduce it but I think it happens when the editor loads in fullscreen by default.

**Comment by cometgrrl** [comment]
> @nelsonec87 was your editor set to fullscreen when open the post? I wasn't able to reproduce it but I think it happens when the editor loads in fullscreen by default.

Mine was. Maybe we need to fix that bug first?

**Comment by vykes-mac** [comment]
> Mine was. Maybe we need to fix that bug first?

I think it's associated with that bug.

**Comment by nelsonec87** [comment]
@vykes-mac Mine was on fullscreen when I loaded 🤔

**Comment by vykes-mac** [comment]
@cometgrrl what theme were you using?

**Comment by cometgrrl** [comment]
Uh, the latest attempt was on my team's P2. But on my simple site, it looks like it's Twenty-Twelve.

**Comment by vykes-mac** [comment]
It seems the issue at the moment only happen on P2 sites.
