### ISSUE TITLE
Global Styles: Button colors don't save on simple sites

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#66531]
### Quick summary

Global Styles has an option to change the text and color options for buttons. These colors don't stick, they reset to the default after saving. This appears to only happen on simple sites.

### Steps to reproduce

1. Activate Russell on a simple site
2. Visit Global Styles > Buttons
3. Change background and/or text color, save

### What you expected to happen

The button colors should save after resetting, as they do on AT with Gutenberg activated:

https://user-images.githubusercontent.com/10353785/184361395-1150a616-8fd9-4889-9a85-18e86ccc76cc.mp4

### What actually happened

The colors reset to the default after saving.

https://user-images.githubusercontent.com/10353785/184361230-4e6ab28e-9927-47c2-96a5-f9f237575268.mp4

### Context

I run into this every time I use FSE building a DIFM-L site. 

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

I've tested Vivre, Antonia, Meraki, Russell. Doesn't appear to be theme specific.

### Browser, operating system and other notes

FF: 103.0.1
Mac: 12.4

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

You could individually change the colors on Buttons blocks but this is a workaround with its own issues (no hover states, requires extra time, etc). The point of Global Styles is to make global changes without requiring CSS or making individual changes, so please don't consider this workaround as a reason to not resolve the actual issue with this feature.

**Comment by metabreakr** [comment]
AT site: 36466280-hc

**Comment by mikeicode** [comment]
Ran into this on Quadrat: pdEkSe-ZJ-p2

**Comment by zachspears** [comment]
Unable to reproduce, but leaving open for another Triager to test since there are multiple user reports.

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to reproduce this issue on a simple site with Russell activated. When I clicked Save after making changes to colors in Global Styles > Colors > Buttons, the changes were reset to the default instead of continuing to show the new colors I selected.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by zyousafi** [comment]
Same issue here: #36105337-hc

Provided the user with a workaround using custom CSS

**Comment by mikeicode** [comment]
Same issue on the new theme Disco.

https://user-images.githubusercontent.com/10353785/187456544-a6c45424-d0be-459e-a91a-dbf59c8b9916.mp4

**Comment by Robertght** [comment]
I'm not sure if this is theme specific at the moment, but can we get a confidence check on it @Automattic/cylon ?

**Comment by paxblueribbon** [comment]
Same issue but on an atomic site: zd-5522453

**Comment by darnelldibbles** [comment]
Another report https://wordpress.com/forums/topic/color-changes-to-the-buttons/?view=all#post-3859661

**Comment by katiebethbrown** [comment]
+1 - We ran into this testing on a Team51 simple site as well. We were using the Blank Canvas theme.

**Comment by Addison-Stavlo** [comment]
Testing this now I am no longer able to replicate on Russel, Disco, or TT2 on a simple site. Can others confirm if this is still happening?  - It sounds similar to some Gutenberg upgrade issues I think @noahtallen or @fullofcaffeine recently resolved.

One thing I noticed is the "Buttons" block in global styles no longer has a color option like in the screenshots above, this lives under the singular "Button" block and seems to be working/saving as expected.

**Comment by mikeicode** [comment]
> Can others confirm if this is still happening?

@Addison-Stavlo 

Tested in Russell, Disco, Merkai (below), it's working now!

https://user-images.githubusercontent.com/10353785/191802322-6fa3eb2f-5720-4db3-8cce-21326b4b7951.mp4

_We really need hover color options but that's a different issue._ 

I'll close this. :)
