### ISSUE TITLE
Menus: Renaming default menu doesn't carry over new menu name

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#6653]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/menus/site.wordpress.com. This works best with a site with no current menus.
2. If you have no menus currently, you'll see the default menu. Click the pencil icon to edit the default menu title.
3. Enter a new menu title. I used "Non-default Menu Title" in my example.
4. Click "Save."

#### What I expected
I expected this to copy the default menu, create a new menu with that copy, and assign it the name I tried to give the default menu. At the end, I would've had two menus—"Non-default Menu Title" and the default menu with "Non-default Menu Title" being selected.

#### What happened instead
It temporarily assigned my custom name to the default menu and created a separate menu with "Menu 1." When I refreshed the page though, my custom menu title was missing. "Default menu" was restored and "Menu 1" (The default name assigned to new menus) was still there.

#### Browser / OS version
Chrome 51. OSX 10.11.

#### Screenshot / Video
Video: https://cloudup.com/cJAKHzQws3O (22 sec)

#manual-testing

**Comment by beaucollins** [comment]
Not sure if related but I'm noticing that I can't add any menu items to a default menu either.

**Comment by lancewillett** [comment]
Thanks for the bug report — I'm putting in the Menus Future milestone, but we don't plan to work on menus much more; instead, we plan to deprecate them and point authors to Customizer > Menus instead.
