### ISSUE TITLE
WordPress.com Marketplace: WooCommerce extensions purchased show as inactive in WooCommerce

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#66546]
### Quick summary

When purchasing a WooCommerce extension through the WordPress.com Marketplace it shows as inactive in the WooCommerce "My Subscriptions" tab.

### Steps to reproduce

1. Go to Plugins and purchase a WooCommerce extension (I have tested this using the WooCommerce Bookings extension)
2. Go to WooCommerce > Extensions > My Subscriptions

### What you expected to happen

I would expect that WooCommerce would recognize that the extension has been purchased through WordPress.com and show as "Active" in the "My Subscriptions" tab. 

### What actually happened

The extension does appear, but it shows as "Inactive" and prompts the user to purchase again.

![Markup on 2022-08-13 at 15:52:54](https://user-images.githubusercontent.com/24914028/184472524-4bf88b1d-48f7-4870-88e2-d5dde7e625d6.png)
 

### Context

5475126-zen

p7DVsv-dng-p2#comment-41634

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Workaround details

This doesn't seem to affect the user's ability to actually use the extension, but it is confusing for users to see a prompt to purchase an extension that they have already purchased on their end.

**Comment by cpapazoglou** [comment]
Thanks for reporting! This will be addressed by https://github.com/Automattic/wp-calypso/issues/60661.

We had originally paused the work due to lower priority (eg no user reports). It seems though that we need to readjust our priorities now.

cc: @JulianBustamante
