### ISSUE TITLE
Marketplace: Use the new webhooks table to track the webhooks events

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#66563]

**Comment by cpapazoglou** [comment]
Is this the same as https://github.com/Automattic/wp-calypso/issues/65349 ?

**Comment by JulianBustamante** [comment]
@cpapazoglou #65349 solves marketplace_webhooks table discussion and creation. This issue was created to implement all the code required by webhooks to insert, update status, etc.

**Comment by cpapazoglou** [comment]
Let's deprioritise this pdh6GB-1Xz-p2#comment-2810

**Comment by cpapazoglou** [comment]
Seems not needed for the time being. We can reopen it in the future.
