### ISSUE TITLE
LaunchPad Previews -  Hide site URL

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66571]
Follow up to https://github.com/Automattic/wp-calypso/pull/66424 / https://github.com/Automattic/wp-calypso/issues/66131

The designs for the LaunchPad site preview will hide the site URL in the preview component

![Screen Shot 2022-08-15 at 9 07 00 AM](https://user-images.githubusercontent.com/28742426/184640650-4cb9b282-5d0e-444b-8f82-f6cd73de9313.png)

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/66580 will enable this to be used for our implementation

**Comment by agrullon95** [comment]
https://github.com/Automattic/wp-calypso/pull/66614 added `showSiteAddressBar` prop to Launchpad `<WebPreview />` component to hide the site URL in the site preview.
