### ISSUE TITLE
LaunchPad Site Preview - Disable interaction

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66574]
Follow up to https://github.com/Automattic/wp-calypso/pull/66424 / https://github.com/Automattic/wp-calypso/issues/66131

In the [LaunchPad site preview](https://github.com/Automattic/wp-calypso/blob/862e948fc8b2b36dafa05901787bd6939b5ddf1c/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx#L24), we can click on and interact with the site in the preview. We want to disable this from happening and only allow scroll.

**Comment by Addison-Stavlo** [comment]
We may be able to use existing solution for reference:

https://github.com/Automattic/wp-calypso/issues/40477

D41110-code

EDIT - or maybe that is a bit more difficult since that is an endpoint for theme previews, and we are always referencing the usrers specific site?

Other ideas could be to:
* inject a script into the iframe content to stop click events on capture -> although there would be some cross origin frame issues to get around here.
* perhaps we can make site urls with a certain param like `preview` prevent clicking?
* maybe creating an invisible element above the preview in z-index to capture clicks but allow scroll?
* other ideas?

**Comment by agrullon95** [comment]
> D41110-code
> EDIT - or maybe that is a bit more difficult since that is an endpoint for theme previews, and we are always referencing the usrers specific site?

Correct, this is specifically for theme previews, so I won't work with for any URL. Maybe it's possible to create a similar solution (new API using that code as a reference) for blocking links, form submissions etc on any wordpress site (instead of themes only).

> maybe creating an invisible element above the preview in z-index to capture clicks but allow scroll?

I'm currently looking into this solution. So far I'm able to add a div overlay, but I still need to figure out how to allow scrolling on the iframe behind the overlay.

**Comment by agrullon95** [comment]
**Additional comments about another solution I have experimented with:** 

I created a new API using some of the code referenced in D41110-code that will fetch the provided site, modify the site content to remove links/forms/other user interactions and return the modified HTML back to the client.

Frontend code: https://github.com/Automattic/wp-calypso/pull/67472
Backend code: D87462-code (updated with correct link)

With this solution, we do not need to fetch the target site manually and modify it on the front end. This can help get past CORS iframe-related issues and prevent using jQuery/JS to modify the document before placing it into the iframe. The backend will do the majority of the work and simply return an HTML document that can be rendered on the page without many changes to the frontend code.

**Comment by miksansegundo** [comment]
I can reproduce this issue on production. Users can interact with the LaunchPad site preview to click on links.

Is there another issue tracking this? cc: @Automattic/kitkat 

https://github.com/Automattic/wp-calypso/assets/1881481/2fb69ba3-c3f4-43a0-8afa-e793591a5d4f

As a side effect, the domain upsell banner appears when it shouldn't. See https://github.com/Automattic/wp-calypso/pull/73840

**Comment by worldomonation** [comment]
@miksansegundo Interesting, I had thought this was expected behavior. As far as I'm aware, we don't have anything else tracking this. 

It sounds like this is an issue, so let's create a new tracking issue.

**Comment by arthur791004** [comment]
Sorry I did something wrong [here](https://github.com/Automattic/wp-calypso/blob/62fa21a88197f66d8a33f22c419e0c4bac9239b8/client/landing/stepper/declarative-flow/internals/components/site-preview/index.tsx#L61) after refactor 😓
