### ISSUE TITLE
LaunchPad Preview - Other CSS changes

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66575]
Follow up to https://github.com/Automattic/wp-calypso/pull/66424 / https://github.com/Automattic/wp-calypso/issues/66131

Other CSS updates to meet designs (borders, etc.). At this point the remaining updates on the radar are:

- [x] the font-weight of the siteURL shown above the checklist.
- [x] iframe shadow
- [x] Checklist item hover state
- [x] iframe dynamic height & width

**Comment by agrullon95** [comment]
Iframe shadow, checklist item hover state (changes to blue on hover) have been updated in #66892.

**Comment by agrullon95** [comment]
Sidebar component, iframe border, site preview device picker styling have been updated in #66614.

**Comment by agrullon95** [comment]
Iframe dynamic height (already completed dynamic width CSS work) changes have been updated in https://github.com/Automattic/wp-calypso/pull/67471.

**Comment by Addison-Stavlo** [comment]
very nice, closing this issue now as all tracked items are complete.
