### ISSUE TITLE
LaunchPad Site Previews - hide tablet button

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66572]
Follow up to https://github.com/Automattic/wp-calypso/pull/66424 / https://github.com/Automattic/wp-calypso/issues/66131

LaunchPad preview designs have us hide the tablet button on the preview component:

![Screen Shot 2022-08-15 at 9 13 55 AM](https://user-images.githubusercontent.com/28742426/184641657-24d16ec4-a5d4-4e2f-917a-e8f7c1cbe453.png)

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/66580 will enable this to be used for our implementation

**Comment by agrullon95** [comment]
https://github.com/Automattic/wp-calypso/pull/66614 added `devicesToShow` prop to Launchpad `<WebPreview />` component to hide tablet icon on device switcher toolbar.
