### ISSUE TITLE
LaunchPad screen - direct users to LaunchPad instead of calypso Home

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66573]
Follow up to https://github.com/Automattic/wp-calypso/issues/66119 / https://github.com/Automattic/wp-calypso/issues/66119

Ensure launchpad enabled sites show the LaunchPad instead of calypso "My Home". Perhaps this is a redirect from my home to our stepper flow, or another solution.

**Comment by jeyip** [comment]
Working on this PR raises a few questions that are worth mulling over:
- How will we know when the user completes the launchpad checklist? I think a site setting is a natural solution for this, but will give it more consideration.
- Overriding the my home URL will be simple enough. The real question will be when and where we want this to happen.
- Admin menu items and links are retrieved from the admin-menu endpoint
  - Once we fetch info, it's hydrated in the `adminMenu` slice of state
  - I haven't given this a ton of thought, but I think we'll probably want to override the my home URL in the redux reducer while we're initializing the `adminMenu` slice of state. That way, any references to the my home URL will point to launchpad, regardless of where it appears in the UI
  - The alternative is to override things in the `getAdminMenu` selector in `client/state/admin-menu/selectors/index.js`

Relevant info:
- Site Sidebar Component `client/my-sites/sidebar/index.jsx`
- Client side logic that fetches admin menu items`client/state/data-layer/wpcom/sites/admin-menu/index.js`
- Api endpoint that returns admin menu items `/sites/${ action.siteId }/admin-menu/`
