### ISSUE TITLE
Theme Support: Identify Automation Tasks

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#66581]
As Serenity continues supporting the themes team in the dev tasks required to release a new theme, there are points where we can introduce more automation into the process to streamline our efforts. Let's get a list together and create issues for introducing this automation into the theme support workflow.

**Comment by valterlorran** [comment]
1. [ ] Automate the Diff creation right after the pull(`yarn tool pull <theme-slug>`) command that I added on the premium-theme-tools repo;
2. [x] Automate the generation of the Headstart annotation. I believe it can be combined with the step above.
3. [x] Create the POT file and submit the theme to translation automatically.
4. [ ] Maybe we could also give the option to add the theme to the soft launch list, which would create a diff on WPCOM.
5. [ ] After the diff is reviewed and deployed the person responsible for launching the theme would need to run a new command to the next steps(PNEWy-eBM-p2):
  5.1 [ ] Build the ZIP file
  5.2 [ ] Add the theme as a product to the Store
  5.3 [ ] Create a diff like this: D86011-code(more information pdgA0m-90-p2)
  5.4 [ ] Add the theme to the prices page in MC
6. [ ] When step 5 is tested(pdgA0m-8Y-p2) and deployed:
  6.1 [ ] Network Activate the theme
  6.2 [ ] Publish the Theme Showcase page
7. [ ] Maybe we can automatically create a diff removing the theme from the soft launch list.

**Comment by blackjackkent** [comment]
Closing - linked tasks above will carry this work forward. :)
