### ISSUE TITLE
Site Management Dashboard: Unify search and filter components with the ones used in Jetpack Cloud's Agency Dashboard

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#66582]
### Details

In an attempt to unify the codebase as much as possible as explained in pdKhl6-ty-p2, we should be able to abstract the search and filter functionalities between the two products.

| SMD | JC Agency Dashboard |
| ----- | ---------------------- |
| ![image](https://user-images.githubusercontent.com/26530524/184696941-ba6740b1-19a3-4b71-a3c6-0466d94b1fe5.png) | ![image](https://user-images.githubusercontent.com/26530524/184697012-6aa83652-420f-4754-9b09-3f4c4f09d0b6.png) |
| ![image](https://user-images.githubusercontent.com/26530524/184697104-b5cba8ea-aa46-4b7f-9c3b-75d85999ce1b.png) | ![image](https://user-images.githubusercontent.com/26530524/184697073-fbbb8e5f-b055-486e-84ea-51c06dd25289.png) |

Visually, they must conform to each product (i.e. styling could be different). Feature and usability-wise, they must be equal. My only concern is which experience we want to choose: SMD's or JC Agency Dashboard's? That's a question for the stakeholders. cc @vindl @SaxonF @jeffgolenski @grbicsanja 

### Checklist

- [ ] Component is moved to `@automattic/components`;
- [ ] Both dashboards use the component;
- [ ] Both dashboards include their own styling when using the component;
- [ ] Both dashboards include different filters and they work without affecting each other.

### Related

https://github.com/Automattic/wp-calypso/issues/65197

**Comment by vindl** [comment]
@zaguiini can we also include Automattic's P2 list in this analysis? It looks fairly similar to our list view.

**Comment by zaguiini** [comment]
We won't work on this. As there is an ongoing project to unify the Jetpack Cloud and the Sites page, this will probably be addressed there with other design changes.
