### ISSUE TITLE
Sites Management Page: Add site actions for 'Hide from list' and 'Always show in list'

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#66597]
Now that we've applied 'Hidden' sites to the Sites Management Page (#66459), let's add 'Hide site from list' and 'Always show site in list' site actions to the ellipsis menu. Clicking on either of these should perform the expected change.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/36432/184881755-b8ca6f31-1f64-4618-b607-c105aae23712.png">

However, there are a couple of additional UX aspects I'm aware of:
1. In the Sites Management Page's default state (hiding all 'Hidden' sites), it will be a funky UX to click 'Hide site from list' and have the site immediately disappear from view. We may want to add some effect to the transition (e.g. have the row fade out first, or add a confirmation notice).
2. When the Sites Management Page is showing all sites, it's not currently possible to distinguish between 'Hidden' and not hidden sites. It might be helpful to make it possible.

We may or may not want to address these UX aspects with this issue.

**Done is:**
* When `site.visible === true`, the site has 'Hide from list' as an available site action. Clicking on the menu item should set `site.visible = false`.
* When `site.visible === false`, the site has 'Always show in list' as an available site action. Clicking on the menu item should set `site.visible = true`.
* We've addressed the two UX aspects in the PR, or logged them on the feedback thread to be addressed later.

**Comment by p-jackson** [comment]
I've started a diff that adds an endpoint for updating visibility D86125-code

**Comment by danielbachhuber** [comment]
Endpoint diff is ready! D86125-code

**Comment by zaguiini** [comment]
UX concerns regarding the visibility of hidden sites are going to be addressed in https://github.com/Automattic/wp-calypso/pull/66661. This PR needs design input.

In the meantime, we'll have the visibility toggle action ready.

**Comment by vindl** [comment]
Punting work on this for now due to UX concerns raised above. We can deal with this in i2 with different mechanisms (site starring, better sorting).
