### ISSUE TITLE
how to add calypso to apache vhost config (enabling as site)

### ISSUE THREAD

**Issue by TheRojam** [Automattic/wp-calypso#666]
How can i add calypso to apache vhost config (enabling as site)?
i running a apache webserver with serval sites in serval config files under sites-enable
this works fine but how can i run calypso as a virtual host just add a config file for it in the apache conf-dir with a path in it?

**Comment by Tug** [comment]
Hi @TheRojam ,

You may want to look into this example of configuration: http://httpd.apache.org/docs/2.2/en/vhosts/examples.html#proxy

So without testing I would say it should look like this:
```
<VirtualHost *:*>
ServerName calypso.localhost
ProxyPreserveHost On
ProxyPass / http://127.0.0.1:3000/
ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
```
