### ISSUE TITLE
There is no way to add new menu items to the navigation block on certain themes 

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#66602]
### Quick summary

When editing the template parts in the Livro theme it's not possible to add new items to the menu. There is no + icon. 

### Steps to reproduce

Activate theme Livro
Open the theme editor and edit the header
Select the "New menu" button to add a new menu
No option to add items to the menu

Or 

Activate theme Livro
Open the theme editor and edit the header
Select the "Select menu" button to edit an existing menu
No option to add items to the menu

Video: https://user-images.githubusercontent.com/5507879/184909914-479a5d25-f20b-4a20-89cd-412a702805b6.mp4

### What you expected to happen

I expected to be able to add menu items to the menu

### What actually happened

I was not able to add menu items to the menu

### Context

36476468-hc
Follow up: 5482616-zd

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Yes, connected to the theme Livrothe 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Switch to a theme that has the classic menu option available, for example, Twenty Twenty
Create the menu via wp-admin/nav-menus.php and save
Switch themes to Livro
Select the menu you created before.

**Comment by Greatdane** [comment]
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ❌ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Seems like a number of themes are affected and looks to be due to a recent Gutenberg update? I tried Livro, Zoologist, Russell, all not working. Twenty Twenty Two works

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Labeled high priority

**Comment by Greatdane** [comment]
Vivre also does not work (see https://github.com/Automattic/wp-calypso/issues/67905)

**Comment by Greatdane** [comment]
This looks to have been fixed, closing. 

![w7vNPk.png](https://user-images.githubusercontent.com/5075840/194213888-41dbe7dc-aa69-4547-9c52-5bdc1da110a1.png)
