### ISSUE TITLE
Launch WPCOM SSH: Update support link to SSH-specific docs

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#66604]
Once our SSH-specific documentation is ready, we should link to it in `<SFTPCard>`.

From #66584

**Done is:**
* `<SFTPCard>` is updated to include a link to our SSH-specific documentation.

**Comment by danielbachhuber** [comment]
@JoshuaGoode Can you update this issue when the SSH doc is ready?

**Comment by Nic-Sevic** [comment]
Once posted (28th?) it will have this permalink: https://wordpress.com/support/connect-to-ssh-on-wordpress-com/
if wanted, you can view the draft that will be published here: https://en.support.wordpress.com/?page_id=213309

**Comment by danielbachhuber** [comment]
@Nic-Sevic Thanks!
