### ISSUE TITLE
Reader Card Refresh: Update post excerpt truncation (add ...)

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#66619]
## Description

We're in the process of updating the look and feel of our Calypso Reader Cards. As a part of this, we'll need to update how we're truncating the excerpt copy:

### Before
![Image](https://user-images.githubusercontent.com/5634774/184984147-8c0848ca-6bd3-4e18-bca3-34c4f771d1c1.png)

### After
![Image](https://user-images.githubusercontent.com/5634774/184984228-0add1bbf-adfc-419b-b057-ce7cca06bca2.png)

**Comment by roo2** [comment]
I think we will need a js solution for adding the ellipsis because it doesn't work well with pure css across multiple lines https://stackoverflow.com/questions/33058004/applying-an-ellipsis-to-multiline-text

**Comment by davemart-in** [comment]
I plan to spend more time digging into the code on this one today. I think the solution we have right now A) formats the excerpt, then B) applies CSS to determine how many lines to show and a hacky fade out effect at the end of the last line. Pure JS ellipsis may not work, since we're not doing this based on character count. I'll share more as I dig in.

**Comment by davemart-in** [comment]
I dug into this one a bit more this morning. Here's what I found:

- The [ReaderExcerpt](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/reader-excerpt/index.jsx) component has a conditional to force use of `post.excerpt` if `isDiscover`. Discover is no longer used, so I'm going to remove this conditional.
- In [formatExcerpt](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/post-normalizer/rule-create-better-excerpt.js) `striptags()` removes any HTML tags that are not whitelabelled, then in a shadow DOM we remove some other stuff, replaces `&nbsp;`, and finally limits the output to just 4 DOM elements.
- [createBetterExcerpt](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/post-normalizer/rule-create-better-excerpt.js) creates a series of excerpt alternatives to choose from.

Here's my checklist for how I'll proceed:

- [x] Remove `isDiscover` conditional in ReaderExcerpt component
- [x] Remove `long-content-fade` css include (since it's not really doing anything
- [x] Use san serif font for excerpt
- [x] Default to `post.content_no_html` for excerpt text (as p tags will break up the content in inconsistent ways otherwise)
- [x] Remove max-height CSS restriction (which makes line clamping much harder to deal with)
- [x] Remove manually added "..." from `post.short_excerpt`
- [x] Add line clamp CSS to `.reader-post-card.card .reader-excerpt` (2 lines max)
- [x] Remove outdated line clamp CSS from `.reader-related-card__excerpt`
- [x] Add new line clamp CSS to `.reader-related-card__excerpt` (2 lines max)

**Comment by davemart-in** [comment]
Merged #67278 into #66650
