### ISSUE TITLE
Reader Card Refresh: Stack media vertically and make full width

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#66621]
## Description

We're in the process of updating the look and feel of our Calypso Reader Cards. As a part of this, we'd like to make all media full-width vs left aligned. We'll want to make updates to the following cards:

- Single image
- Two images
- Three images
- Four images
- Video
- Gallery

### Before
![Image](https://user-images.githubusercontent.com/5634774/184982439-5d2d3ec1-441a-4f05-8ca0-0fdc0b942725.png)

#### Single Image
![Image](https://user-images.githubusercontent.com/5634774/184982997-eb81d577-022b-4c83-b527-57461064756c.png)

#### Two image
![Image](https://user-images.githubusercontent.com/5634774/184983147-ab99d5e7-4613-41a6-853a-4577882aaa6b.png)

#### Three image
![Image](https://user-images.githubusercontent.com/5634774/184983214-5ae47825-b043-4428-87c5-14e1bdaf14dc.png)

#### Four image
![Image](https://user-images.githubusercontent.com/5634774/184983280-16e3d583-8628-4af3-9401-376c120bcdbe.png)

#### Video
![Image](https://user-images.githubusercontent.com/5634774/184983431-979dda09-0998-4c50-bdf8-639447f7c329.png)

#### Gallery
![Image](https://user-images.githubusercontent.com/5634774/184983493-978b6411-3854-4be8-a462-c7c6f1e1f5fe.png)

**Comment by eoigal** [comment]
I don't understand how we want to show posts with a single image but doesn't have the quality to increase size to reader post width.  The images from Techmeme typically include thumbnails from other aggregated sources.

<img width="636" alt="Screenshot 2022-08-31 at 11 47 16" src="https://user-images.githubusercontent.com/5560595/187661672-51f8e3b5-cfc6-4a0f-8733-de4c02eb1d06.png">

I think we should either omit images of a certain size or we reduce the rescaling to prevent the image from having this blurred effect.

**Comment by davemart-in** [comment]
@eoigal I assume we're already using the uploaded image resolution here (not downsizing in any way)?

I'd say let's start by just implementing the change for all reader cards to always show the image. For now just stretch it to 100%. Once you have a PR, we can do some more testing to see how rampant this is and adjust accordingly.

cc @ollierozdarz for his thoughts.

**Comment by eoigal** [comment]
> I assume we're already using the uploaded image resolution here (not downsizing in any way)?

I've tried to replicate this on a p2 (and failed) so not sure if its a feed/RSS parsing thing.

For context the reader post is rendered like this on techmeme; (from [here](https://www.techmeme.com/220831/p9#a220831p9))
<img width="621" alt="Screenshot 2022-08-31 at 14 46 42" src="https://user-images.githubusercontent.com/5560595/187694638-8840d84a-5f11-49b1-928b-f8500ac904ab.png">

That image is found - https://www.techmeme.com/220831/i9.jpg - which is a thumbnail and 124x83 in size - when this gets blown up to default 600px (in the featured image reader component) it gets that pixelated look.

**Comment by ollierozdarz** [comment]
> @eoigal I assume we're already using the uploaded image resolution here (not downsizing in any way)?
> 
> I'd say let's start by just implementing the change for all reader cards to always show the image. For now just stretch it to 100%. Once you have a PR, we can do some more testing to see how rampant this is and adjust accordingly.
> 
> cc @ollierozdarz for his thoughts.

My 2 cents are that while it's important to factor in images  with poor quality (like the example), we want to be building towards a system that encourages quality (images, post design, etc). I agree with @davemart-in - let's stick to the plan

**Comment by roo2** [comment]
It sounds like it's not just a CDN thing where better images are available but we are currently choosing a smaller thumbnail for the reader?

If those are the source images, maybe we could look into some kind of a deliberate blur or filter to make it look more deliberate? https://devbeep.com/css-blur-effects/ ( check with @ollierozdarz and @davemart-in )

**Comment by davemart-in** [comment]
Yep, blur could work if needed, but let's see how rampant the problem is before implementing anything like that.

**Comment by davemart-in** [comment]
This issue has merged with #66650.
