### ISSUE TITLE
Reader Card Refresh: Update engagement icons

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#66620]
## Description

We're in the process of updating the look and feel of our Calypso Reader Cards. As a part of that, we'll want to update some of the action icons. Let's toss the follow icon in there while we're at it.

### Before
![Image](https://user-images.githubusercontent.com/5634774/184983765-27b0491c-be4b-49d1-8805-089fa780ef11.png)

### After
![Image](https://user-images.githubusercontent.com/5634774/184983845-95100680-9f1c-420d-a056-15dab80f4e98.png)

**Comment by roo2** [comment]
I did a bit of changes to alignment already in https://github.com/Automattic/wp-calypso/pull/66749. When there is an indicator next to the Star icon, it should be right aligned with the top hamburger menu e.g.
<img width="616" alt="Screen Shot 2022-08-22 at 3 14 13 pm" src="https://user-images.githubusercontent.com/22446385/187794932-aa51b84d-6436-496d-92a8-a2c7458f91ce.png">

**Comment by davemart-in** [comment]
Merged into #66650 from #68103
