### ISSUE TITLE
Sites Management Page: remove Get Started header for free sites screenshots

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#66627]
All free site screenshots currently contain the "Get Started" header that appears for logged-out users. If users have multiple free sites next to each other, this can look confusing, and it almost looks like it's part of the thumbnail UI. We should try to hide this banner when the request originates from mShots.

<img width="540" alt="Screenshot 2022-08-16 at 15 51 57" src="https://user-images.githubusercontent.com/1182160/184982892-54ea4e9a-d4bf-485f-8af8-1c36297048b0.png">

To get this to show:

1. Use a WP.com simple test site that's public/launched.
2. View its front end in an incognito session.

**Comment by p-jackson** [comment]
This can be hidden with a query parameters: `?hide_banners=true`
2d2d7-pb

I believe there's a query param that will hide the cookie banner too. It's off-screen for us at the moment so it doesn't matter, but it might come up if we change the dimensions of the screenshot we take using mShots.
