### ISSUE TITLE
Reader Card Refresh: Remove multi-post truncation

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#66625]
## Description

We're in the process of updating the look and feel of our Calypso Reader Cards. As a part of this, we'd like to completely remove the code that pulls posts which were published close to each other into a single card. Instead, we'll just show each post as it's own card. here's an example of what you see today:

![Image](https://user-images.githubusercontent.com/5634774/184980960-ba4457be-6ad6-409c-8029-22785974f4d1.png)

**Comment by eoigal** [comment]
I've created [PR](https://github.com/Automattic/wp-calypso/pull/66916) to remove this functionality but wonder should we keep it but default to not combining cards (by setting `shouldCombineCards` to false in the Stream component)?

**Comment by davemart-in** [comment]
@eoigal The good thing about GitHub is that the code is all there in your PR if we ever want to bring it back to life. I'd side with just removing it as I don't foresee us bringing it back.

**Comment by eoigal** [comment]
Merged into https://github.com/Automattic/wp-calypso/pull/66650
