### ISSUE TITLE
Reader Card Refresh: Move more menu to top right

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#66624]
## Description

We're in the process of updating the look and feel of our Calypso Reader Cards. As a part of this, we'll be moving the more menu from the bottom right corner to the top right corner.

### Before

![Image](https://user-images.githubusercontent.com/5634774/184981206-1d45e3c3-e4f9-435f-b9f7-88ee5367c746.png)

### After

![Image](https://user-images.githubusercontent.com/5634774/184981301-6961fb05-9598-4c82-95bc-8b413088e574.png)

**Comment by roo2** [comment]
I ran into a design issue moving the hamburger menu and asked here pe7F0s-90-p2#comment-88

**Comment by roo2** [comment]
merged into https://github.com/Automattic/wp-calypso/pull/66650
