### ISSUE TITLE
Enhancement - Provide the same editing tools for the Subscribe and Login buttons in the Paid Content block

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#66639]
### Quick summary

The Premium Content block was recently updated to use nested blocks. Inside the nested block's "Guest View", the buttons to **Subscribe** and **Log In** are 2 different blocks altogether, and they offer different tools for setting width and alignment. This makes it more difficult and limited to have a consistent look to your buttons.

- The **Subscribe** button - a `Payment Button` block - has tools to adjust the width of the button (by percent), and has an alignment option in the floating toolbar. 
- The **Login** button, a `Premium Content login button` block - does not include either of these options, so you can't set it's width or alignment to match the Subscribe button. 
- It's also not possible to make them align on the same row.

<img width="1131" alt="Screen Shot 2022-08-16 at 6 14 27 PM" src="https://user-images.githubusercontent.com/27249804/185013131-5787e9bc-e2e4-4f02-b414-0f003f5a64e1.png">

### Steps to reproduce

1. On any test site (Stripe doesn't need to be connected) create a new page or post, and add a `Premium Content` block
2. Select the **Subscribe** button, and adjust it's width to 50% or something, and set it to align-center
3. Select the **Login** button to make the same changes

### What you expected to happen

The same options would be available

### What actually happened

It's not possible to adjust the width or alignment of the "Login" button to match the "Subscribe" button.

**Width Settings**

https://user-images.githubusercontent.com/27249804/185014238-e4624fed-8dae-4954-bd9f-121a0da17c57.mp4

**Alignment Settings**

https://user-images.githubusercontent.com/27249804/185014270-2126104c-98da-41ba-9041-e4e13f986f63.mp4

### Context

User report & Follow Up Email: 
- 36485911-hc 
- [ ] 5484084-zd-woothemes

Replicated on a Simple & AT test sites. Premium Content block not available on Self-Hosted.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No - issue presented in Themes Coherent, Quadrat White, and Alonso.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

I imagine there are some CSS workarounds we could implement, but this would only help some users.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Not replicable**
- Replicable on Core? **No**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested once more on AT with Blank Canvas, and Simple with Twenty Nineteen. Replicated in both instances. 

*Example - AT with theme: Blank Canvas*

![Screen Capture on 2022-08-23 at 10-07-13](https://user-images.githubusercontent.com/27249804/186221043-3691a4fd-1e4c-411f-a25a-98054f62e69d.gif)

*Example - Simple with theme: Twenty Nineteen*

![Screen Capture on 2022-08-23 at 10-09-38](https://user-images.githubusercontent.com/27249804/186221843-85a2377c-7284-42ff-8a67-64a25eccd985.gif)


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Gustavo-Hilario** [comment]
Another report here:

- [ ] 5484084-zen

Screenshot:

![Markup on 2022-08-29 at 10:09:26](https://user-images.githubusercontent.com/50875131/187208823-13f2df95-0d33-4bea-a184-6cd7fed37ea3.png)

**Comment by sophiegyo** [comment]
Chat 41837775-hc
Follow-up 6084020-zen

Context: user was migrating in from another provider and trying to set up Premium Content blocks on a Simple site.
Both on their Simple site, and when I tested on my Atomic site, the buttons appeared stacked in the editor, but seem to appear correctly side by side when published.

Editor: 

<img width="984" alt="image" src="https://user-images.githubusercontent.com/36608681/228779592-ee1158fe-782d-4b52-9408-66ff5693725d.png">

Published:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/36608681/228779715-ce24e5fd-128c-4ffe-811d-598e05d32e18.png">

**Comment by cuemarie** [comment]
📌 ACTIONS
- Retested today and the Subscribe & Login buttons still have different options available
- Updating to an "Enhancement" type, as this is likely by design
- Due to the age of this issue, I've downgraded the priority from `High` to `Normal` to better reflect its status in the larger context of open bugs in this repo.
