### ISSUE TITLE
Jetpack: Sidebar: New plugin update notice pops up a preview of my site

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#6663]
The "There is a plugin update available." message on sitebar pops up a display of my site instead of navigating to the plugins page.

The link shows on hover is valid but it doesn't get triggered.

![](http://g.recordit.co/GF9tHIYU3K.gif)

**Comment by tyxla** [comment]
@umurkontaci does this still occur? I'm unable to reproduce it at this time.

**Comment by rickybanister** [comment]
@ebinnion is this the same as #7513 that you fixed?

**Comment by ebinnion** [comment]
Looks like it. I confirmed that I can not repro.

![fixed_preview_issue](https://cloud.githubusercontent.com/assets/1126811/18964948/b6ee61fe-8640-11e6-99e0-8c86f096726c.gif)

As a note, that specific notice and text only shows when there are only plugin updates (not theme or core updates as well).

I'm going to close.
