### ISSUE TITLE
Add Learn More Link to Plugins Page

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#66635]
### What

On almost all Calypso screens, there is a "Learn More" link to a support doc about the page the user is viewing. Example from Domains:
![image](https://user-images.githubusercontent.com/30727666/185006361-450b78d8-7bfc-4e59-8fb7-ed2eb75eb65a.png)

Plugins is currently missing a Learn More link on both simple and atomic:
![image](https://user-images.githubusercontent.com/30727666/185006429-6c3e09c4-a801-488f-b8f1-560153403670.png)

### Why

The support doc link assists users in understanding more about the screen they're viewing, and provides easy access to help. Context: p58i-9Vz-p2#marker

### How

Add a Learn More link directly after the help text in the tooltip:

>Add new functionality and integrations to your site with plugins.

The correct link is:

https://wordpress.com/support/plugins/

Related to #60876 cc @arcangelini

**Comment by zachspears** [comment]
GReat suggestion for consistency and useful documentation. Added Low priority due to low impact.

**Comment by donalirl** [comment]
Bumping up the priority since it provides a help point for all users. Also adding to Vertex team board since they have been able to assist with the other Learn More links throughout Calypso.
