### ISSUE TITLE
[Block] Buttons: Border color does not respond to text color in FSE Themes

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#66649]
### Quick summary

In the past you could apparently set the outline color of a button block by setting the text color but this doesn't work anymore.

There is no no way of setting the button outline color. No option in the block settings or global styles.

### Steps to reproduce

Add a button block.
Try to change the outline color

https://user-images.githubusercontent.com/13706336/185130397-54cc486d-9e39-41a4-bdd1-bfa1e87d78b4.mp4

### What you expected to happen

An option to appear to set the outline color

### What actually happened

There is no option.

### Context

5483706-zd

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Tested on Antonia and Vivre on test site.

### Reproducibility

Consistent

### Available workarounds?

Yes, difficult to implement

### Workaround details

Yes but only if an option for CSS exists.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
-
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Replicated**
- Replicable on Core? **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
-
- I was able to replicate this issue in all test environments, only when using Block Themes. 
     - On a classic theme (Twenty Nineteen), the border color follows the Text color, when the style **Outline** is selected. This aligns generally with what our [Public docs](https://wordpress.com/support/wordpress-editor/blocks/buttons-block/#styles) say: 
     - `In the Styles options, you can set the button to be filled with a color (Fill) or have a solid border (Outline).`

- However,after switching to a block theme, the same button's outline becomes unresponsive to changes in Text color. 

### Example: Simple site, Theme: Twenty Nineteen
- The button border works as expected, when the *style* is set to **Outline**, not **Fill**.

https://user-images.githubusercontent.com/27249804/186224800-a984f8d4-1622-458d-ab42-a7266af1e13b.mov

### Example: Simple site (same as above), Theme: Blockbase

https://user-images.githubusercontent.com/27249804/186227077-0b62a128-4b4d-4324-bde7-0e753599968e.mp4

### Example: AT site, Theme: Zoologist 

https://user-images.githubusercontent.com/27249804/186226308-0172d6ca-54d6-4a1f-b63e-f8fbcc2b1d0f.mp4

### Example: Self-Hosted site, Theme: TT2

https://user-images.githubusercontent.com/27249804/186226346-a608d242-c742-4a26-a40f-77fa5fdc858c.mp4


📌 ACTIONS
-
- Marked as Triaged for Quality Squad review
- Reported in Gutenberg repo: https://github.com/WordPress/gutenberg/issues/43535
- Added to 'HE Cross-repo Watchlist' project board

**Comment by annezazu** [comment]
This was resolved in Gutenberg soon after being reported 2 years ago: https://github.com/WordPress/gutenberg/issues/43535

Closing out :)
