### ISSUE TITLE
[New Comment] In some situations, two email notifications are sent instead of one

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66651]
When a new comment is made on a post, **two emails** are sent to the post author:

| Normally sent to post author only | Normally sent to post subscriber only |
| ------------- | ------------- |
| ![Markup on 2022-08-18 at 14:25:11](https://user-images.githubusercontent.com/25105483/185394322-966918d8-3e04-4021-8dd4-dc06d3e8c2ed.png) | ![subscriber](https://user-images.githubusercontent.com/25105483/185394334-2a59c9ef-a75e-4b1d-b49f-59f07a13e51d.png) |

It looks like the post author should receive only the email on the _left_. The email on the _right_ should be sent to post subscribers only.

---

- Background: pdDOJh-DG-p2#comment-485
- Potentially related patch: D81740-code
- Figma: xyH1cLTuiOBgChGAhZvh2y-fi-0%3A1

**Comment by ivan-ottinger** [comment]
Related Slack discussion: p1660826625586199-slack-C02TCEHP3HA

**Comment by ivan-ottinger** [comment]
User report: 5525826-zd-woothemes.

**Comment by renata-franco** [comment]
> User report: 5525826-zd-woothemes.

User would like to be informed once this is fixed.

**Comment by phcp** [comment]
@renata-franco the issue was fixed on D89102-code
