### ISSUE TITLE
Hosting screen improvements

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#66656]
Just a placeholder for now, more details will be added later. Some things to improve:

- non-business users don't see all the available features when the upgrade nudge is active.
- features could have their own separate sections/pages.

**Comment by SaxonF** [comment]
> non-business users don't see all the available features when the upgrade nudge is active.

@vindl as a first step could we remove the gradient and just apply opacity to the entire section plus disable pointer events? `pointer-events: none;`

![Image](https://user-images.githubusercontent.com/1072756/189820995-33bd1a78-ee8c-4f95-babd-b59c14378e1b.png)

**Comment by vindl** [comment]
@SaxonF Yes, that seems like a quick win.

**Comment by zaguiini** [comment]
We're working on it. Follow the progress on [this view](https://github.com/orgs/Automattic/projects/545/views/3).
