### ISSUE TITLE
Codeowners lists payments team which no longer exists

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#66652]
The [CODEOWNERS file](https://github.com/Automattic/wp-calypso/blob/7bdedda44ff9dc9426b7c975a626810bddd7a444/.github/CODEOWNERS#L35) refers to `@Automattic/payments`, which no longer exists. That should probably be changed.

<img width="1078" alt="Screen Shot 2022-08-17 at 12 22 47 PM" src="https://user-images.githubusercontent.com/2036909/185192002-1b38e101-f99a-41cd-b234-69990506a6f4.png">

**Comment by michaeldcain** [comment]
From planning:

Let's update it to Shilling. If any of these give too many notifications (especially not related to our work), let's remove our names.

**Comment by JessBoctor** [comment]
This seemed like a simple fix, so I went ahead and took care of it. :)
