### ISSUE TITLE
Sites Management Page: Add a lock icon for private sites in grid view

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#66669]
In grid view, it might not be obvious why some sites show screenshots and others use a site icon or a letter. Let's add a lock icon to the bottom right corner of the thumbnail to clarify this.

cc @SaxonF for any design and placement feedback.

**Comment by vindl** [comment]
Documenting some follow-up discussion points:

1. We don't need to include this in i1 since it would duplicate the `Private` labels.
2. We'll explore adding screenshots for private sites in i2. If that's successful this will no longer be an issue.

If (2) doesn't work out, we can revisit the designs to make the distinction clearer. Until then, I'm putting this issue on hold.

**Comment by sejas** [comment]
I've removed it from the i1 milestone.

**Comment by vindl** [comment]
We'll provide alternatives to screenshots for the Coming Soon and P2 sites. The goal is to use fewer fallbacks for private sites, so there is less need to deal with them separately.
