### ISSUE TITLE
GuidedTours: Fix positioning for right-hand-sided steps

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#6666]
Currently, steps that are placed on the right hand side of the screen have odd positioning (see #6472). Let's make our positioning logic more robust.

**Comment by lsinger** [comment]
Can you call out specific examples? 

E.g. the step targeting `themes-tier-dropdown` has a position setting of `below` but is definitely buggy and should be much more on the right (for some reason the dropdown's client rect has a very funky `right` value).

**Comment by lsinger** [comment]
Unsure what to look for here specifically — closing for now, this is something that will definitely resurface when building tours that use such positioning.
