### ISSUE TITLE
Feature request: Allow Chart block on WordPress.com

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#66676]
### What

It'd be nice if we have an in-built tool that allows adding charts on editor

Initially requested on chat:  36518053-hc

### Why

Like table block or this site https://optolongfilter.com/products/1064-100nm-bandpass-filter/ , we can display charts without the need of installing custom plugins

**Comment by Greatdane** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/61294
