### ISSUE TITLE
Mini Cart block: Cart showing blank with WooCommerce Subscriptions plugin active

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#66683]
### Quick summary

The user has WooCommerce Subscriptions with a lot of other plugins active. They have added Mini Cart block to their Editor and when a product is added to the cart, opening the cart it shows.

Deactivating the WooCommerce Subscriptions plugin shows the cart contents.

As per the [guide](https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-6), WooCommerce Subscriptions 3.1.0+ plugin should be compatible with the Woo Cart & Checkout Blocks.

### Steps to reproduce

1. Have WooCommerce (v6.8.0) and WooCommerce Subscriptions plugin (v4.5.0 ) activated.
2. Mini cart block is added to the Editor.
3. Add the product to the cart.
4. Clicking on the mini cart block, it shows a blank cart whereas the item is added to the cart. 

### What you expected to happen

The items added to the cart to be shown

### What actually happened

The cart items were showing blank.

### Context

Customer report
Chat: 36520178-hc
Follow up: 5487959-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by zachspears** [comment]
Able to reproduce, moving forward.

**Comment by Aljullu** [comment]
Howdy, as we are working on improvements to the Mini Cart block (https://github.com/woocommerce/woocommerce-blocks/issues/8556), I wanted to see if I could reproduce this issue, but I wasn't able. I wonder if maybe this was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/7794? In that case, we should be able to close this issue.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- WooCommerce is now up to Version 7.7.0, and WooCommerce Subscriptions' latest release is Version 5.1.2
- I cannot replicate this issue with both activated; the Mini Cart block works as expected.

📌 ACTIONS
- Closed as could not replicate
