### ISSUE TITLE
Social icons block in customizer not allowing URLs

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#66699]
### Quick summary

There is no way to add a URL link to a social icon when adding in the customizer.

Please see video - 

Uploading Screen Capture on 2022-08-18 at 13-33-06.mov…

### Steps to reproduce

1. Add the social icons block
2. Add a twitter link
3. There is no where to add the actual link to Twitter

### What you expected to happen

An area to appear where I can add the link.

### What actually happened

No option appeared to add a link

### Context

5478195-zd

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Tested on Toujour on Simple and Atomic and Shoreditch

### Browser, operating system and other notes

Chrome/Mac

### Reproducibility

Consistent

### Available workarounds?

Go to the widgets are in wp-admin and enter it there.

**Comment by zachspears** [comment]
Hello @rickmgithub, while taking a look at this issue I was able to add a link to the Twitter Social Icon as follows:
https://user-images.githubusercontent.com/10124024/186551271-08beb1dd-752e-41df-a5d5-2f21dd8cd626.mov

While this process could certainly be more intuitive, can you confirm if you are able to add a link, or if this issue might be theme-specific? Thanks!

**Comment by Greatdane** [comment]
@rickmgithub it also looks like your video did not upload, can you share it again if the issue is still present?

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closing report due to stale conversation. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
