### ISSUE TITLE
[All] Clean up unnecessary feature flags

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66701]
Once all new updated emails are launched, we can remove feature flags to clean up the code.

- [x] New Liked Comment: https://github.com/Automattic/wp-calypso/issues/66803
- [x] New Liked Post: https://github.com/Automattic/wp-calypso/issues/68513 
- [x] New Comment: https://github.com/Automattic/wp-calypso/issues/68520
- [x] Comment Approval: https://github.com/Automattic/wp-calypso/issues/68523 
- [x] Invitation

Finally we can also remove the main new template email flag:
- [x] `wpcom_use_2021_email_templates`

We can also consider removing old email templates.

**Comment by TimBroddin** [comment]
This one is deployed!
