### ISSUE TITLE
LaunchPad - data for LaunchPad activity / status

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66706]
Ensure that a site setting, option, or other form of persistent data is in place on site creation that we can use and update to determine if the launchpad should be shown for a particular site.

some p2 discussion / context - pdDR7T-bx-p2
recently mentioned in slack - p1660767513980659-slack-CHN6J22MP

**Comment by Addison-Stavlo** [comment]
with https://github.com/Automattic/wp-calypso/pull/66613 and D86659-code merged, this issue will be resolved once https://github.com/Automattic/wp-calypso/pull/67016 is deployed.

**Comment by edanzer** [comment]
This has been resolved now with https://github.com/Automattic/wp-calypso/pull/67016
