### ISSUE TITLE
LaunchPad - Data for determining which LaunchPad flow to show

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66707]
Ensure that a site setting, option, `site_intent`, or other form of persistent data is in place on site creation that we can use to determine which launchpad flow to show to a site using LaunchPad.

some p2 discussion / context - pdDR7T-bx-p2
recently mentioned in slack - p1660767513980659-slack-CHN6J22MP

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/66798 should allow us to use site-intent for this.

**Comment by jeyip** [comment]
Closing this for now because https://github.com/Automattic/wp-calypso/pull/66798 was merged
