### ISSUE TITLE
Bold <strong> rich-text formatting is maintained when copy and pasted into Block Editor post title

### ISSUE THREAD

**Issue by hngdny** [Automattic/wp-calypso#66720]
### Quick summary

Bold <strong> rich-text formatting is maintained when copy and pasted into Block Editor post title

When copying text (by using either mouse or keyboard clipboard functions) from a source that has bold (<strong>) rich-text formatting, post titles maintain the bold HTML element and will start to appear as bold in blog feeds as well as post email notifications.

### Steps to reproduce

1. Create a new post with the Block Editor
2. Copy text from source with bold rich-text formatting
3. Paste clipboard content into post title, using either mouse right-click or keyboard shortcut.

### What you expected to happen

Text pasted into post titles should not keep the source's bold `<strong>` rich-text formatting.

Post headings should be consistently maintaining the same font-weight.

### What actually happened

Post titles appear in bold, inconsistent with other headings.

Email notification post titles show <strong> HTML element tags.

### User example 1 – 5470448-zen
Here is a screenshot of the user's front page blog feed. The first title shown does not have any particular settings (non-sticky) but appears with Bold font styling, which is unexpected and inconsistent with the following blog post title where no Bold font styling is applied.
![Screen Shot 2022-08-18 at 16 27 22](https://user-images.githubusercontent.com/70492744/185496246-04ed64ec-f92a-44ac-8931-df410c16b13c.png)

### User example 2 – 5486309-zen
A possible link, affecting the email notification title issue here.

User's post title:
![Screen Shot 2022-08-18 at 16 02 06](https://user-images.githubusercontent.com/70492744/185496157-1a70b4a6-7108-4a5a-a818-e65f26cc0177.png)

![Screen Shot 2022-08-18 at 16 06 41](https://user-images.githubusercontent.com/70492744/185497270-3d9cf1f4-fdd3-45b4-832a-a5c8da1e255f.png)

## Screen recording of the issue replicated on a test site

https://user-images.githubusercontent.com/70492744/185497455-147cae2a-b14a-4df1-8d25-a36a1a98c4a5.mov

## Differences between WordPress.com view vs Classic View
![Screen Shot 2022-08-18 at 16 49 15](https://user-images.githubusercontent.com/70492744/185497794-2d4bf782-f319-436c-b37e-ddad6cef8e48.png)

### Platform (Simple, Atomic, or both?)

Simple

### Browser, operating system and other notes

Tested with Firefox 103.0 (64-bit)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Suggest that users first paste text into either Notepad or TextEdit (Plain text mode under _Format -> Make Plain Text_) to strip away the rich-text formatting.

Although not universal, Windows/PC users can try pasting text while stripping it of its formatting: `Ctrl + Shift + V` keyboard shortcut or `Option + Cmd + Shift + V` for Mac.

**Comment by KirkwallDay** [comment]
- [ ] Another instance here 5482659-zen

**Comment by zachspears** [comment]
Able to reproduce. Upgraded priority due to impact and possible issues with email updates.

**Comment by Babylon1999** [comment]
5511321-zd


Shared the workaround.

**Comment by jp-imagines** [comment]
Another report in 36924675-hc. User was frustrated that their "new post" email came out with the `<strong> </strong>` tags in the post's title, and received multiple complaints from their readers about it.

**Comment by masperber** [comment]
13082678-hc Another report where the user reported that their new post notification emails contained `<strong>` tags in the title.

As a workaround, I suggested that they use the Quick Edit function to remove these tags before publishing.

User says that they've been copy/pasting titles from a text editing program all along, so based on when the problem started for them, this bug was introduced some time between August 4 and August 11, 2022.

**Comment by tavilla61** [comment]
Another instance here: 37009181-hc (5603277-zen follow-up ticket) 

I shared the workaround in the follow up.

**Comment by ariel-maidana** [comment]
Another instance: 5640862-zd-woothemes

**Comment by kelasante** [comment]
Another instance in 37523955-hc. Shared the workaround and asked the user to remove titles in the post and retype it. Another workaround that works is to edit the titles in Quick Edit in wp-admin.

**Comment by danielbachhuber** [comment]
I'm unable to reproduce this issue with Gutenberg 15.0.0-rc.1 in Chrome 108.0.5359.124:

https://user-images.githubusercontent.com/36432/212320531-25d11bb6-c49a-4d92-a4ab-bbf22681fb72.mp4

It seems like this issue might've been fixed in Gutenberg 14.6? https://github.com/WordPress/gutenberg/pull/35825

Can anyone still reproduce the issue?

**Comment by danielbachhuber** [comment]
I'm pretty sure this is fixed. Feel free to re-open if there are further reports!
