### ISSUE TITLE
Sites Management Page: Prepare PR that releases SMP to all users

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66727]
If we prepare the PR that releases SMP to all users ahead of time then we'll be able to work out all the wrinkles before release day (29th). That way we know we'll be able to merge it at a convenient time when we have plenty of time to monitor for potential issues.

Done is:
- [x] `build/sites-dashboard` feature flag is enabled in production
- [x] SMP is available at the `/sites` URL
- [x] PR is reviewed and ready to merge

**Comment by sejas** [comment]
Deployed! 🚀
