### ISSUE TITLE
Sites Managment Page: Write a deployment announcement post for wpcomhappy

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#66726]
Let's post a heads up to wpcomhappy P2 letting folks know of the upcoming deployment of SMP

- This is a good one to get inspiration from p7DVsv-cGX-p2
- In should refer to the CfT and Project Thread
- It should give an approximate of time it'll be deployed (like what time approximately on the 29th, which timezone etc.)
- Where to report issues

Not tied to the publishing of the above post but documenting it here anyway; we should follow this p7DVsv-d8l-p2 when we do the deployment.

**Comment by p-jackson** [comment]
7DVsv-p2?draft=58424

**Comment by danielbachhuber** [comment]
@p-jackson Made some edits directly to the draft!

**Comment by danielbachhuber** [comment]
🚢
