### ISSUE TITLE
Show style variation indicator in the static designs of Design Picker

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#66734]
# Description

For each static design (theme) that has style variations, we want to show an indicator in the form of circles representing each variation. Design (updated 19 Aug, ignore the "ellipsis" icon):

<img width="487" alt="image" src="https://user-images.githubusercontent.com/1525580/185540123-d6650838-6c2b-42ad-bb67-30603153a820.png">

A static design has style variations if it has non-empty `style_variations` field in the response of the `/wpcom/v2/starter-designs` endpoint. See: 120-gh-Automattic/ganon-issues

# Acceptance Criteria:

- [ ] When a static design has style variations, for each variation, show a circle indicator, which:
   - [ ] has the background color of the variation, and
   - [ ] contains and `A` letter which has the foreground color of the variation,
- [ ] When there are more than 4 variations, show only the first 4 and then show an additional `+ X` indicator.
- [ ] When the indicator is clicked, it will just show the theme preview page.

**Comment by fushar** [comment]
@autumnfjeld @SaxonF : I have a few questions that will affect the A/C:

1. For the first iteration, should we ignore the the following icons? ("tile" and "ellipsis" icons):

<img width="397" alt="image" src="https://user-images.githubusercontent.com/1525580/185536703-a4bc1a03-3565-47bd-ab57-21ef65dd62d3.png">

2. Should we limit the number of circles? What happens if the number of variations exceeds this limit? I guess we can just show the first X variations?

3. We just want to show the background color in the circles, right?

**Comment by SaxonF** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/1072756/185537939-8286405f-6ba3-42c8-8d36-2232768d46c4.png">

 1. yep we can ignore.
 2. Yes limit to 4 and if goes over include a +5 item that indicates further variations
 3. Background and text colour which should be consistent with how global styles are represented in sidebar 
<img width="281" alt="image" src="https://user-images.githubusercontent.com/1072756/185538049-4733c95e-19f3-467e-a5ab-55a8d8610d3d.png">

Updates can be seen in Figma 7l53h5fxAUNjVRBQ82YFwn-fi-242%3A43264

**Comment by fushar** [comment]
@SaxonF Thanks, I've updated the issue description 😄

**Comment by taipeicoder** [comment]
>  contains and A letter which has the foreground color of the variation

After confirming with @SaxonF in 7l53h5fxAUNjVRBQ82YFwn-fi, the A letter should be the primary color.

**Comment by taipeicoder** [comment]
Closing with #66856
