### ISSUE TITLE
Connections: Change Instagram "Widget" to "Block"

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#66730]
### Quick summary

The Instagram _widget_ no longer exists, but there is a reference to it in Calypso.

### Steps to reproduce

1. Go to  Tools → Marketing → Connections 
2. Expand Instagram

It says:

>Add an Instagram widget to display your latest photos.

![image](https://user-images.githubusercontent.com/30727666/185521633-c5a896b4-9c7b-4b9d-90be-460fc5e02560.png)

### What you expected to happen

It should say "block".

### What actually happened

It says "widget", which is outdated.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Confirmed, wordage needs changing. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review
