### ISSUE TITLE
New email notification template: Image caption formatting is broken.

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#66739]
### Quick summary

Image captions in the new email template appear larger than paragraph text and there's no linebreak/spacing after them.

![z2dndM.png](https://user-images.githubusercontent.com/66711744/185561978-8101e640-2540-4436-ac2f-a36783cec7c1.png)

The screenshot above was from a notification sent from a site using the TwentyTwenty theme.

### Steps to reproduce

1. Create a post with images and captions.
2. Publish the post
3. View the notification email.

### What you expected to happen

I expected the captions to be the same size, smaller, or formatted differently from normal paragraph text.

### What actually happened

Image captions in the new email template appear larger than paragraph text and there's no linebreak/spacing after them.

### Context

Chat: 35641737-hc
Ticket: 5490339-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Unknown

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no 
- Tested on Simple ✅ 
- Tested on AT  - no
- Tested on Self-hosted - no

📌 FINDINGS/SCREENSHOTS/VIDEO
- I cannot replicate this issue, unfortunately with or without Twentytwenty: 
 ![q2y01K.png](https://user-images.githubusercontent.com/6737345/186582354-f7e33c9f-b313-460f-9bfa-bdee8294865d.png)

📌 ACTIONS
- Await author feedback
- Once we are able to replicate, check with Apex

📌 Message to Author
 - @inaikem can we get more details on this?

**Comment by inaikem** [comment]
That's pretty much all I have but I'll ping them for more details on their email client to see if that helps 🙏

**Comment by inaikem** [comment]
I've reopened the interaction above asking for further details

**Comment by i11za** [comment]
@Robertght @inaikem user has replied in 5490339-zd-woothemes that they had one post arrive fine in the email, but 2-3 ones prior to that did not, and shared inline copies of the emails. Perhaps it was a temp issue if the latest email arrived fine?

I've acknowledged receipt, and let them know we'll let them know once there's an update. Haven't closed the ticket yet, placing on 72 hour hold. 

In hindsight I'm now wondering if we should ask them to send emails as attachments so we can see full email/headers/etc., as well as ask for browser/OS information? Could this be a browser issue? 

Also, flagging as something that caught my attention, most likely unrelated: I haven't tested this, but could it be that the Amazon links are somehow breaking the formatting? In the email they shared these seem to be updated from `www.amazon.pl/....` to `nam12.safelinks.protection.outlook.com/...` -

**Comment by inaikem** [comment]
> Perhaps it was a temp issue if the latest email arrived fine?

This may well have been the case. I've sent over a quick reply asking them to let us know if they experience the issue again.

> In hindsight I'm now wondering if we should ask them to send emails as attachments so we can see full email/headers/etc., as well as ask for browser/OS information? Could this be a browser issue?

We could (and I just did in my reply 😉). We can see the original forward using the "view original email" option under the envelope icon at the top right of each reply in ZD to view the mail. Here's a screenshot of the first example:

![eN9qXh.png](https://user-images.githubusercontent.com/66711744/187063881-43340d52-f259-4ca5-a71f-ed4560f98a2e.png)

**Comment by inaikem** [comment]
I'm leaving this in the "Needs HE/Author reply" queue for now but please feel free to close this out if they don't reply over the next 1-2 weeks. We can always reopen and retest if needed 🙏

**Comment by cuemarie** [comment]
User has replied with screenshots of their new post email, as well as a new post email from a separate blog they follow as well, showing the same issues, shown below. They also anecdotally shared that this experience is shared by others they've been in touch with.

### Example Email 1 
- [Post](https://leonbergerlife.com/2022/09/03/leonberger-dog-complete-owners-manual/) published 03-09-2022
- images are linked

<img width="1490" alt="Screen Shot 2022-09-05 at 8 38 00 AM" src="https://user-images.githubusercontent.com/27249804/188483541-d0091cba-9efd-42e0-87ab-088881fb3052.png">

<img width="1488" alt="Screen Shot 2022-09-05 at 8 39 12 AM" src="https://user-images.githubusercontent.com/27249804/188483554-69c87c38-812e-4d11-b21a-96410b853b97.png">

### Example Email 2 (from a 2nd site)
- [Post](https://alexdiaz-granados.com/2022/09/04/sleepless-in-seattle-no-more-like-restless-in-the-sunshine-state/) published 04-09-2022
- Images showing the issue are **not** linked images in the post
- This site's theme: **Stratford**

<img width="1493" alt="Screen Shot 2022-09-05 at 8 40 02 AM" src="https://user-images.githubusercontent.com/27249804/188483579-ebff6037-3509-4996-a875-c9ab159dfe7c.png">

<img width="1489" alt="Screen Shot 2022-09-05 at 8 40 39 AM" src="https://user-images.githubusercontent.com/27249804/188483589-035ba79d-760f-413d-93a4-74661cc224c8.png">

---
@inaikem 

- Could this be an issue with Outlook, specifically? I've let the user know that we're looking into this for now.
- Second question - is this better moved to a P2, or do we suspect a bug is at play here?

**Comment by Robertght** [comment]
@cuemarie  I signed up with Outlook and can confirm this is indeed an issue:

![6TWpxp.png](https://user-images.githubusercontent.com/6737345/188575023-0fa331f1-80e6-463e-bff6-903c3aa3148a.png)

@Automattic/apex can this be adjusted for other email clients as well?

**Comment by eduardozulian** [comment]
Just to update here that we have another ticket (from the same user) at 5546878-zen. We can use this one to follow up instead.

**Comment by ivan-ottinger** [comment]
Thank you for sharing the details Robert and Eduardo!

I have added the issue to our maintenance project board.

**Comment by TimBroddin** [comment]
I've created a patch for this: D93721-code

**Comment by TimBroddin** [comment]
This fix has been deployed! 🥳
