### ISSUE TITLE
Jetpack NUX: match emails coming from wp-admin to existing wp.com accounts

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#6673]
I'd like us to run a test where we send the connecting user's wp-admin account email address to wordpress.com when they initiate a new connection. We would then check if that email address is associated with an existing account and if so, pre-fill the username field for them. 

It might be nice to run it as a test where we detect an account for all users, but only pre-fill for half. If that is silly we can launch for all users and compare to our current baseline connection rate.

cc @richardmuscat @johnHackworth @roccotripaldi and @ebinnion who's SSO/invites expertise might be helpful

**Comment by tyxla** [comment]
This has been addressed by @ryelle for the old flow in D2342-code.

Work is in progress for the new flow in D2800-code.

**Comment by tyxla** [comment]
Done in D2800-code for half of the users.
