### ISSUE TITLE
Plans Redesign: reorder plans features according to @	apeatling design

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#6674]
Reorder plan features according to this: #6381.

![0fa252cc-3d2d-11e6-8141-62a45a98049d](https://cloud.githubusercontent.com/assets/1270189/16741655/20350f36-4759-11e6-8282-d4d53d17f598.png)

**Comment by gwwar** [comment]
@apeatling @rralian we don't have a corresponding free "feature" for WordPress ads vs no WordPress ads in the other plans. Should we add one in, or change the ordering from the mock?

<img width="325" alt="screen shot 2016-07-11 at 10 43 15 am" src="https://cloud.githubusercontent.com/assets/1270189/16740630/ced845c6-4754-11e6-8b6f-62f0ff654791.png">

**Comment by apeatling** [comment]
Can you screengrab what the ordering would look like with all plans + the ordering change?

**Comment by gwwar** [comment]
<img width="1269" alt="screen shot 2016-07-11 at 11 07 17 am" src="https://cloud.githubusercontent.com/assets/1270189/16741343/bb2c95ce-4757-11e6-8ab0-4f30a455d188.png">

**Comment by gwwar** [comment]
We need to fix a bit of styling with the infotip, but it looks like we can shorten the design customization text too.
