### ISSUE TITLE
Implement style variation switch buttons in the theme preview page

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#66741]
# Description

In the Design Picker, when the selected theme has style variations, we want to show a button for each style variation, when clicked, applies the style to the theme preview. Design:

### Desktop

![Image](https://user-images.githubusercontent.com/1525580/185544784-d7b2a5fd-446b-4038-82ce-4e4e79edf171.png)

### Mobile

![Image](https://user-images.githubusercontent.com/1525580/185570689-335e1c86-a1d5-458b-8bd0-95e448ddac39.png)

# Acceptance Criteria

- [x] For a theme that has style variations, show the switch button for each style variation. The button should look the same as the one in the Site Editor:

| Livro | Pendant |
| -----|-------------|
| <img src="https://user-images.githubusercontent.com/1525580/185573522-a1007b03-b116-4ebf-a8a3-42d7d5697d6b.png" width="300"/> | <img src="https://user-images.githubusercontent.com/1525580/185575269-45d30af7-30e0-45ac-bc3b-d31b88ae7d0e.png" width="300" /> | 

- [x] When the switch button is clicked, the style is applied to the theme preview on the right.

# Dev Tasks

- [x] Show the style switch button for each style variation read from the `/wpcom/v2/starter-designs` endpoint (see: 120-gh-Automattic/ganon-issues)
- [x] Inject the style variation CSS to the site preview endpoint `/wpcom/v2/block-previews/site` (see: 121-gh-Automattic/ganon-issues)

**Comment by fushar** [comment]
@autumnfjeld @SaxonF some questions:

1. Should we use this design (left sidebar containing the theme name) for the themes which do not have style variations as well?

2. Should we implement the following sections (description, support, features), or can we ignore them for the first iteration?

<img src="https://user-images.githubusercontent.com/1525580/185576835-097c1850-b741-4309-9b0b-846ec275560f.png" width="400" />

3. We notice some differences in other aspects of the design as well, should we also implement them?

| Existing design | New design
|-------|------|
| <img src="https://user-images.githubusercontent.com/1525580/185584454-68c6223d-a075-4967-a9a6-1e6e3b5c93b2.png" width="400" /> |  <img src="https://user-images.githubusercontent.com/1525580/185585103-d155cbe7-b33f-4ae9-b489-f9c39e982fd1.png" width="300" /> |

**Comment by arthur791004** [comment]
> We notice some differences in other aspects of the design as well, should we also implement them?

I thought the only difference is the device switcher and it doesn't look good if we put it on the top of the browser header on this page. And the other part is the header of this design 😆

**Comment by SaxonF** [comment]
> Should we use this design (left sidebar containing the theme name) for the themes which do not have style variations as well?

Yes, best if we keep them consistent if possible.

> Should we implement the following sections (description, support, features), or can we ignore them for the first iteration?

I believe this was already implemented as part of https://github.com/Automattic/wp-calypso/pull/65259 so might just be able to pull it over.

**Comment by autumnfjeld** [comment]
> I believe this was already implemented as part of https://github.com/Automattic/wp-calypso/pull/65259 so might just be able to pull it over.

@fushar if it is easy, go ahead and do it for this iteration.   If not, write up an issue for post MVP launch. 😃

Also, we won't have that info for v13n designs..... 🤔  

> I thought the only difference is the device switcher

This is a big deal.  Was there further discussion of where the device switcher will be @SaxonF ?

**Comment by fushar** [comment]
> This is a big deal. Was there further discussion of where the device switcher will be @SaxonF ?

We decided to keep the device switcher at top-center of the page.

**Comment by fushar** [comment]
Closing this issue as all tasks are done!
