### ISSUE TITLE
Sites Management Page: Prevent character clipping on ellipsis text

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#66758]
From pdtkmj-nh-p2#comment-583

Any characters that drop low on the Y-axis appear to be clipped:

![image](https://user-images.githubusercontent.com/36432/185624472-4e256f56-ec2f-4527-8d7b-e5ed39dc0ff6.png)

**Done is:**
* The characters appear fully.

**Comment by sejas** [comment]
It also happens on tile view:

<img width="444" alt="Screenshot 2022-08-22 at 18 50 38" src="https://user-images.githubusercontent.com/779993/185986561-d1510d77-39d1-49ef-96ea-2b3f6ab5dfb3.png">
