### ISSUE TITLE
Pattern Assembler: Show the main screen on "build-your-own-layout" step

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#66787]
# Description

We want to show the main screen on the new step, and it will include the title, description, "choose a header", "add a section", "choose a footer", and "Continue" button.
![image](https://user-images.githubusercontent.com/13596067/185575443-eed235dd-5b05-4d5c-8f4a-870b5a3df069.png)

7l53h5fxAUNjVRBQ82YFwn-fi-238%3A41198

Please ignore the search bar here.

# Acceptance Criteria

- [x] It will show "Choose a header", "Add a first section", and "Choose a footer" buttons at the beginning. If you have already selected a section, the "Add a first section" copy will change to "Add another section".
- [ ] When you click on the "Choose a header", it will show the pattern selector, and all of the patterns should be related to the header (`blockTypes: "core/template-part/header"`)
- [x] When you click on the "Add a first section" or "Add another section", it will show the pattern selector, and the header/footer-related patterns should be excluded.
- [ ] When you click on the "Choose a footer", it will show the pattern selector, and all of the patterns should be related to the footer (`blockTypes: "core/template-part/footer"`)
- [x] The selected pattern is added showing the pattern name in one line. If the pattern name is too long we will truncate it off using `...` at the end + show the entire name via tooltip with `title`.
- [x] When you hover on the selected pattern, you will see the 3 action buttons as screenshot below
    ![Screen Shot 2022-08-19 at 4 26 03 PM](https://user-images.githubusercontent.com/13596067/185577549-96c68ec1-1063-4069-bfd1-490d32a2405f.png)
    - [x] The first one is to re-order the section and it won't be shown on the header/footer pattern. When you click "up", the section will go up. When you click "down", the section will go down
    - [x] The second one is to select another pattern. When you click on it, it will show the pattern selector again.
    - [x] The last one is to remove the selected pattern

Note that we don't limit the number of selected sections.

# Dev Tasks

- [x] https://github.com/Automattic/wp-calypso/pull/66954

# Related

* https://github.com/Automattic/wp-calypso/issues/66589

**Comment by miksansegundo** [comment]
I have added the following acceptance criteria to consider the long pattern names:

>- [ ] The selected pattern is added showing the pattern name in one line. If the pattern name is too long we will truncate it off using `...` at the end + show the entire name via tooltip with `title`.

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/66954 and we show the whitelisted patterns instead of filtering patterns by `blockTypes`
