### ISSUE TITLE
Pattern Assembler: Show Blank Canvas option in the Unified Design Picker

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#66785]
# Description

We want to show the blank canvas option in the UDP. When you select a blank canvas design, you will land on the "build-your-own-layout" (TBD) step

![Screen Shot 2022-08-19 at 12 51 17 PM](https://user-images.githubusercontent.com/13596067/185545223-de3ab784-89e6-4aeb-a2d9-de3c95ade1f5.png)
7l53h5fxAUNjVRBQ82YFwn-fi-238%3A41198 but I cannot find it 😅

- [x] Confirm with @SaxonF the clickable area of the blank canvas option (all or only the "Get Started" button)

# Acceptance Criteria

- [x] The position of the blank canvas option is between the first and second line of the static designs in the UDP
- [x] When you click on the option, you will land on the "build-your-own-layout" (TBD) step
- [x] A new step "build-your-own-layout" (TBD) without any content

# Dev Tasks

- [x] Update feature flag for "build-your-own-layout" step
- [x] Create empty step on stepper
- [x] Add the blank canvas CTA

# Related

* https://github.com/Automattic/wp-calypso/issues/66589

**Comment by bangank36** [comment]
Landed
