### ISSUE TITLE
Select header/footer/section  patterns for the Pattern Assembler MVP

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#66789]
# Description

[PT: Blank Canvas Pattern Assembler: pbxlJb-2ki-p2)

Coordinate with designers to establish list of patterns for the MVP.

See slack conversation kicking off collaboration: p1662099782169749-slack-C02M88KJ684

Ola & Onur created this site to plan out which patterns to use for MVP: http://passembler.wordpress.com/

# Dev Tasks 
@miksansegundo can update as needed
- [ ] get pattern IDs of the patterns that Ola & Onur use in http://passembler.wordpress.com/
- [ ] hardcode these so these patterns surface in the PA

# Test
* ask @autumnfjeld  or one of the theme designers to build a layout in PA
* code tests
* what else?

# Resources
* Here is a FigJam with data and ideas on patterns we should use in the Pattern Assembler MVP: KFKxJ6nH1D9tyIh7IqlC8a-fi-0%3A1 
* http://passembler.wordpress.com/

**Comment by autumnfjeld** [comment]
Here are the most commonly chosen patterns from the pattern inserter:


![Image](https://user-images.githubusercontent.com/5665959/185827850-32bfbf90-d297-495a-92c2-6f86bc15b918.png)

To me it looks like we should offer query block patterns. 🤔 

tracks/trends/?compareby=prop&eventname=wpcom_pattern_inserted&interval=day&prop=pattern_name&startdate=20220723&stat=uniques

**Comment by miksansegundo** [comment]
We could create a `tag` or a `meta` to mark the patterns that we want to show in the pattern selector. That would make the maintenance/testing easy.

We plan to show the headers and footers using the metas `block_type_core/template-part/header` and `block_type_core/template-part/footer` but we might want to hide some of those. 

We could create the following `meta` for the Pattern Assembler:

-  `pattern_assembler/header`
-  `pattern_assembler/section`
-  `pattern_assembler/footer`

This can be done in a second iteration after the MVP.

**Comment by miksansegundo** [comment]
We can find the list of patterns that we are using hardcoded in this [file](https://github.com/Automattic/wp-calypso/blob/612fe4cc380b724c2b71ccf2a3cb4114c08c98fc/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts).

**Comment by autumnfjeld** [comment]
Reached out to themers to get assistance:  p1662099782169749-slack-C02M88KJ684

**Comment by miksansegundo** [comment]
@autumnfjeld I don't have access to passembler.wordpress.com, do you? I'm following the thread, and I think we are still waiting for our themers to share with us a harmonious subset of patterns for the MVP.

**Comment by miksansegundo** [comment]
Just noting here that the patterns used in the layouts in passembler.wordpress.com that are coming from `patternboilerplates` will be moved to `dotcompatterns` by the designers because in the PA we want to use only patterns from `dotcompatterns`. 

At the moment, the PA doesn't support patterns from other source sites. We could add support with some minor adjustments in the UI.

**Comment by miksansegundo** [comment]
Here is the list of patterns IDs from passembler.wordpress.com:

**Layout 1**
https://patternboilerplates.wordpress.com/?p=1707
https://patternboilerplates.wordpress.com/?p=1163
https://patternboilerplates.wordpress.com/?p=2173
**https://dotcompatterns.wordpress.com/?p=5634**

**Layout 2**
https://patternboilerplates.wordpress.com/?p=2077
https://patternboilerplates.wordpress.com/?p=898
https://patternboilerplates.wordpress.com/?p=1138
https://patternboilerplates.wordpress.com/?p=2080
**https://dotcompatterns.wordpress.com/?p=1053**

**Layout 3**
https://patternboilerplates.wordpress.com/?p=2173
https://patternboilerplates.wordpress.com/?p=1201
https://patternboilerplates.wordpress.com/?p=1199
https://patternboilerplates.wordpress.com/?p=1223
https://patternboilerplates.wordpress.com/?p=1538
**https://dotcompatterns.wordpress.com/?p=1603**

**Layout 4**
**https://dotcompatterns.wordpress.com/?p=5851**
**https://dotcompatterns.wordpress.com/?p=3244**
**https://dotcompatterns.wordpress.com/?p=1949**
**https://dotcompatterns.wordpress.com/?p=1464**
**https://dotcompatterns.wordpress.com/?p=1213**

The patterns in bold are from `dotcompatterns`, the rest are only in `patternboilerplates`.

**Comment by alaczek** [comment]
I move the patterns from Layouts 1-3 from `patternboilerplates` to `dotcompatterns`:

**Layout 1:**
* https://dotcompatterns.wordpress.com/?p=7132
* https://dotcompatterns.wordpress.com/?p=7135
* https://dotcompatterns.wordpress.com/?p=7138
* https://dotcompatterns.wordpress.com/?p=5634

**Layout 2**
* https://dotcompatterns.wordpress.com/?p=7140
* https://dotcompatterns.wordpress.com/?p=7143
* https://dotcompatterns.wordpress.com/?p=7146
* https://dotcompatterns.wordpress.com/?p=7149
* https://dotcompatterns.wordpress.com/?p=1053

**Layout 3:**
* https://dotcompatterns.wordpress.com/?p=7138
* https://dotcompatterns.wordpress.com/?p=7153
* https://dotcompatterns.wordpress.com/?p=7156
* https://dotcompatterns.wordpress.com/?p=7159
* https://dotcompatterns.wordpress.com/?p=7161
* https://dotcompatterns.wordpress.com/?p=1603

**Comment by miksansegundo** [comment]
@autumnfjeld @alaczek the patterns have been added 🎉 
Do you want to build a layout in PA to review them before we close this issue? We could change their order or adjust the names if required.

**Comment by miksansegundo** [comment]
We'll add the following patterns as sections:
 
**ID 737**
![image](https://user-images.githubusercontent.com/1881481/192679849-2661d33c-5ce4-425a-8a05-579e4c767db7.png)

**ID 1213**
![image](https://user-images.githubusercontent.com/1881481/192679890-7db32f22-9e9b-413d-a92d-f26be0ab2ec3.png)

**ID 3255**
![image](https://user-images.githubusercontent.com/1881481/192679909-4788a2d2-1fff-4042-9159-a0a1b12c0290.png)

**ID 5676**
![image](https://user-images.githubusercontent.com/1881481/192679925-69fced98-4da4-44b2-b482-00e1e73d8a0c.png)

**ID 789**
![image](https://user-images.githubusercontent.com/1881481/192679933-d0d8aafc-3a5d-4146-b581-b72af76b0f77.png)

**ID 194**
![image](https://user-images.githubusercontent.com/1881481/192679990-05461cdd-d841-4489-aaf1-a60dac852707.png)

**ID 3227**
![image](https://user-images.githubusercontent.com/1881481/192679996-09572552-9cc1-4f28-999e-a48a3eee2883.png)

**ID 1751**
![image](https://user-images.githubusercontent.com/1881481/192680010-5115863f-36ac-4b40-a51c-a231e266913d.png)

**Comment by autumnfjeld** [comment]
Just tested. I saw a weird lag on first clicking "Choose a header", instead of the cool animiation there was awkward loading of the patterns.  I'll try to reproduce and get back about this.

I was thinking we would show ONLY[ wireframe + the 9 patters above](https://github.com/Automattic/wp-calypso/issues/66789#issuecomment-1260350649).  This provide a consistent look & feel among all the patterns in the list. 
Here is what I see:
| 1 | 2 |
| - | -|
| ![image](https://user-images.githubusercontent.com/5665959/192912900-420767f8-f71e-4ccd-bc36-19358290cd2e.png) | ![image](https://user-images.githubusercontent.com/5665959/192913080-ab1a8201-5077-4e08-a449-8fe5e0408ebd.png)

|




With this plan we need to remove these:

<img width="307" alt="image" src="https://user-images.githubusercontent.com/5665959/192912643-de58f556-ac2a-4d92-ae9d-12d4ca17fd19.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/5665959/192912659-72245def-778e-464a-9506-35147094c37e.png">

<img width="294" alt="image" src="https://user-images.githubusercontent.com/5665959/192912688-6031b916-a4e7-43e5-a2fa-27f7a435675e.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/5665959/192912705-5c0fda7c-9825-4536-a1dc-1ac9c5f8df6d.png">


What do you think @alaczek .   I might need to do some thinking on this.  Are we offering enough interesting patterns if we only do wireframes+the 9 patterns?

**Comment by miksansegundo** [comment]
It sounds good to me to remove those patterns to provide a consistent look & feel with image placeholders and because we have other patterns that look very similar. 

On the other hand, I think that spreading some patterns with true images in the list make the list more colorful and atractive, and also could help users to better understand the image placeholders in the wireframe patterns.

> Are we offering enough interesting patterns? 

I think so because we have patterns from almost every category. We are missing patterns from the categories:

- Coming soon
- Newsletter

**Comment by autumnfjeld** [comment]
Hmmmm, I don't think at the MVP stage we need Newsletter or Coming soon (since an unlaunched site already shows as Coming Soon ... at least I think).
