### ISSUE TITLE
[Bug]: Image Block Converts to an Embed Block for Smug Mug URLs

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#66782]
### Quick summary

When inserting a SmugMug URL into an Image Block via the "Insert from URL" option, the block automatically converts to an Embed Block. A user in 5489479-zen is experiencing this when editing an existing or scheduled post. This conversion is resulting in broken links on the site. 

https://user-images.githubusercontent.com/10015451/185792634-4b836213-f5a2-49e2-8d63-9277d79d7a14.mp4

### Steps to reproduce

1. Open an existing post to edit
2. Use a link for an image from Smugmug.com (try this one https://photos.smugmug.com/photos/i-D9Kc9qh/0/X3/i-D9Kc9qh-X3.jpg )
3. An Image Block to a post
4. Select the "Insert from URL" option
5. Paste the SmugMug URL in the field
6. Update the post and view the post
7. Notice the broken image link

The problem also occurs when using the SmugMug Block and Embed Blocks.

### What you expected to happen

For the block to remain an Image Block and display the image. 

### What actually happened

The block converts to an Embed Block. 

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

I've asked the user in 5489479-zen if they have any other SmugMug links we can test. 

### Reproducibility

Consistent

### Severity

One

**Comment by cuemarie** [comment]
Played into this user's ticket and they haven't shared any further images we can test; though they did mention that **not all images change to broken links, only some**. 

Also, I do see in this WordPress.org support article for the SmugMug embed block (here: https://wordpress.org/support/article/smugmug-embed/ the following advice):

> If we use an URL that can’t be embedded, the block shows the message “Sorry, this content could not be embedded.”
>
>You will have two choices: Try again with a different URL or convert it to a link.

This article was last updated in 2020, so I'm not sure if this integration has had much love recently, but figured I'd share.

**Comment by Robertght** [comment]
The user didn't share a link regarding this site and they said it doesn't happen consistently. I'm going to close this for now until they share more details so please reopen then.

**Comment by renata-franco** [comment]
The user came back and said it happened again, but in the end, removed the Embed Block and added another Image Block instead, so the error is no longer there. Told them that next time to leave it there for us to check it out a bit. 

They also said 
> Honestly, I don't think there's anything special about that link. I think this behavior is from instability in the code. And, by "instability" I mean the code (programmer) trying too hard to be clever.
I could be wrong, of course. It could also be various algorithms are gaining self-awareness and are messing with us. 

Not sure where that is coming from, but they think that the image URLs they are using are normal, so the problem should not happen.
