### ISSUE TITLE
Ensure patterns and pattern names are translated (when that is possible)

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#66793]
# Description
PT: pbxlJb-2ki-p2
Looks like we have another sleuthing task for missing translations.   See this slack convo for context p1661141810155589-slack-CRWCHQGUB.

Ideally we will ship the PA project to all languages with all the pattern related copy translated into mag-16 languages.  There may be instances where this is not possible, for instance patterns that are coming from core.

# Tasks & ToDos
- [ ] flag this in #dotcom-templates
- [ ]  reach out to i18n and see if there are any known hickups in the pattern translation process

**Comment by autumnfjeld** [comment]
This is related to what @arthur791004  is discussing with i18n: 
p1660722347960409-slack-C02AED43D

Info: PCYsg-6pZ-p2

**Comment by autumnfjeld** [comment]
@bangank36 & @miksansegundo   Do we need to start doing some spot checking to see how patterns are showing up in translations?   Then we can better understand what the current state is.

Should we move this issue to Ready for Dev?

**Comment by bangank36** [comment]
That's good idea, I can help checking the pattern's translation

**Comment by autumnfjeld** [comment]
@bangank36  Cool, please go ahead and move it into "In Progress".   You may want to start with some spot checking in different languages then report back to the team about how many problems you find (untranslated patterns).    Then we'll probably need to make some decisions on whether it is acceptable to ship without translations or do the work to get translation process started.   Naturally reach out for any help you need. :)

**Comment by miksansegundo** [comment]
The status of the **wireframe patterns translations** for all the languages, except one pattern, is around **90% of completion**.

**Comment by autumnfjeld** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/e6518353-71e9-41b7-9208-fde8f676bf08-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)  Thanks for the status update @miksansegundo . I'd say we're ok to ship with that.

**Comment by miksansegundo** [comment]
I'm closing this issue as the wireframe patterns are 100% translated including the names (except for two that are still around 90%).

Here is a screenshot of the translation in Spanish:

<img width="352" alt="Screen Shot 2565-10-07 at 16 15 48" src="https://user-images.githubusercontent.com/1881481/194519048-8c038fa4-b112-4d2a-aacd-89ad09b899cd.png">
