### ISSUE TITLE
[Bug]: Unused Quick Start sessions banner is confusing

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#66799]
### Quick summary

When a user has any unused Quick Start sessions, we show the following banner on the `/me/purchases` screen:
<img width="1154" alt="Screenshot 2022-08-17 at 12 41 22" src="https://user-images.githubusercontent.com/3376401/185880665-f85f5ee4-dfb3-487c-b6dd-542572afcdbf.png">

As discussed in this thread ( p1660735418728269-slack-C039XBM6ESF ), there are multiple issues with this banner:
 * The "Schedule now" CTA links to the site picker, where it is unlikely that the user will pick the site that has unused sessions - we should ensure we always link to a site with unused sessions so the available actions match the CTA
 * The copy doesn't make it clear what Quick Start sessions are -- given when they were retired, it's highly unlikely that users will know what a Quick Start session is, or why they still have unused sessions
 * The overall banner design doesn't match our current guidelines for spacing, placement, or illustrations

There is also a broader question around how actively we should be promoting unused Quick Start sessions to users who have them, but this initial work should be focused on cleaning up and simplifying this specific flow. A quick-ish follow-up may be to show the improved version of this banner in the site-specific purchases page in _Upgrades_ -> _Purchases_, but only when the unused session is for the current site.

### Steps to reproduce

The hardest part of reproducing this issue is that your user needs to have an unused Quick Start session, or such a session needs to be mocked up in some way. This is largely because we have not been selling or bundling these sessions for quite some time.

However, if you do have such a user, you can see the current banner by navigating to `/me/purchases`.

### What you expected to happen

As noted in the general description, there are a few things that ought to happen:
 * Clicking on the "Schedule now" link should take me to a page where I can schedule a session, and not a site selection page
 * The visuals for the component ought to be updated to match our current design guidelines

### What actually happened

* Clicking on "Schedule now" takes me to a site selection page
* The banner doesn't match our current design guidelines

### Context

Internal report

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by daledupreez** [comment]
cc @joelwills -- apologies for pulling you in this late, but it's pretty clear that we want to make sure the UX in Calypso doesn't prevent users from scheduling sessions.

We may want to kick off a separate discussion if we think we should promote scheduling for unused Quick Start sessions more proactively. One thing I would like to tackle once we land https://github.com/Automattic/wp-calypso/pull/67024, is to make this same banner available under the site-specific purchase list. Let me know if you think that may be going too far.

**Comment by joelwills** [comment]
@daledupreez Thanks, I appreciate the heads-up.

I don't think we need to make it more obvious or promote it more proactively. That said, I think we need to allow users to book a session if they wanted it, and not make it difficult or confusing for them to do so. 

We are limited by the number of folks we have available to do Quick Starts so the worse that can happen is we get complaints that they can't find a slot to book. We can fix that by adding more people or making slots available further into the future. I just wouldn't make it so "in-your-face" that we have hundreds of people suddenly deciding to book them. For example, the banner could be at the bottom of the active upgrades, rather than the top?

**Comment by mpkelly** [comment]
Changed were made in PR https://github.com/Automattic/wp-calypso/pull/67024 which has now been deployed.
