### ISSUE TITLE
Marketplace: Plugin details breadcrumbs requires double click to navigate

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#66795]
pdh6GB-1QJ-p2 - When viewing a product, navigating to the plugin page root from a plugin detail page requires two clicks of the breadcrumb to load it.

Acceptance:
- [ ] Links no longer require two clicks

**Comment by lsl** [comment]
So [this function](https://github.com/Automattic/wp-calypso/blob/110806a819dca23a6118518d7808145b37bec2a6/client/my-sites/plugins/controller.js#L100) is running twice when you click a link.

The first pass runs the correct `browsePlugins` function, the second pass runs `plugin`.

Why...? Not sure yet. :shrug:

**Comment by claudiucelfilip** [comment]
> The first pass runs the correct `browsePlugins` function, the second pass runs `plugin`.

It looks like this [clearSearch](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/search-box-header/index.jsx#L100) call is causing the issue it forces the router to update and rerun the middlewares. This also affects the `/plugins` route, where [browsePlugins](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/controller.js#L114) is run twice each time.

**Comment by DustyReagan** [comment]
I had another go at this here: https://github.com/Automattic/wp-calypso/pull/66883
