### ISSUE TITLE
Investigate disparity in calypso_signup_site_vertical_submit

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#66796]
# Description

Check to make sure the prop `has_vertical_images` is firing correctly.   According to tracks, only 3% of users select a vertical that has vertical images.   That doesn't seem to match up with other data about which vertical is selected.

For example, about 15% of users select Education, which has vertical images.

![Image](https://user-images.githubusercontent.com/5665959/185869227-ea2bbae3-a193-411e-b432-b905fb0a574e.png)

![Image](https://user-images.githubusercontent.com/5665959/185869362-38a4ddb8-7856-45eb-91e1-f90a2b482c5c.png)

Also to clarify, this event fires both when the user actually selects a vertical, and also fires when a user DOES NOT select a vertical but rather simply clicks continue. In which case vertical_title is recorded as `null` 

![Image](https://user-images.githubusercontent.com/5665959/185869936-21d368c2-96e4-471d-a134-5565e91f689c.png)

# Tasks
- [x] look for a bug associated with `has_vertical_images` prop
- [] remove prop has_verticalizable_images, I think this has to be done in repo https://github.com/Automattic/tracks-events-registration

**Comment by autumnfjeld** [comment]
Note @taipeicoder: we should not close this issue until we confirm in tracks that the data makes sense. 

1. merge  #66801
2. wait a couple days and examine  calypso_signup_site_vertical_submit for data consistency
3. if all good, close this issue

😃

**Comment by taipeicoder** [comment]
@autumnfjeld data seems consistent now, however I'm still seeing `has_verticalizable_images` which, according to the data team, should no longer be there since it's been more than 14 days since that prop was last tracked 🤔

**Comment by autumnfjeld** [comment]
We can watch it for a other few days then follow up with data peeps about why it is still showing up

**Comment by autumnfjeld** [comment]
Follow up to understand why this prop  `has_verticalizable_images`  is still showing up.:  1085-gh-Automattic/tracks-events-registration.

**Comment by taipeicoder** [comment]
Found relevant convo: p1618434360156000-slack-C03DKP1JP
After checking the code fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qvagreany%2Qgenpxf%2Qrirag%2Qncv.cuc%3Se%3Q1154s614%2352-og and fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sabfnen%2Sgenpxf%2Qrirag.cuc%3Se%3Q11s6np25%26sv%3Qtrg_rirag_cebcregvrf%23trg_rirag_cebcregvrf-og

Doesn't seem that we're actually filtering event props within 14 days.

**Comment by taipeicoder** [comment]
See D90830-code for a proposed fix.

**Comment by taipeicoder** [comment]
Closing as D90830-code has been deployed.
