### ISSUE TITLE
[Bug]: Comment form: label text and input value are shown together on Firefox after a page refresh

### ISSUE THREAD

**Issue by mpkelly** [Automattic/wp-calypso#66791]
### Quick summary

Firefox remembers form data, so if you fill out a form and then refresh the page; your data will persist. This causes trouble on the Comment Box form, which has some dynamic labels.

You can see the problem here:
https://user-images.githubusercontent.com/6851384/185831610-41fd8687-3c0c-48eb-9bc3-2d5ba8080430.mp4

 

### Steps to reproduce

1. Using Firefox, while not signed in to WordPress.Com, navigate to a post and expand the Comment Box
2. Enter values for one or more of Email, Name, Website
3. Do a page refresh
4. Expand the Comment Box and confirm your previously entered values are still shown
5. **Tab** into the input fields that have values.
6. Confirm that you can see the value you entered and the dynamic label text like in the video

### What you expected to happen

If there is a value set then there should be any label shown

### What actually happened

Label text and input value are shown together

### Browser

Mozilla Firefox

### Context

I found this while working on https://github.com/Automattic/wp-calypso/issues/64913

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

You can clear the input value and then blur it to see the label again.

**Comment by daledupreez** [comment]
I've just deployed the fix in D87300-code to WordPress.com, so this should be resolved once users get the new Javascript.
