### ISSUE TITLE
Latest Posts Block not wrapping text correctly

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#66806]
### Quick summary

Text is being pushed into the next column on different screen sizes. 
<img width="1083" alt="Markup 2022-08-22 at 11 43 39" src="https://user-images.githubusercontent.com/13706336/185903682-6448007a-ff3b-4344-9090-260c1c592d01.png">

### Steps to reproduce

* Add a latest posts block in grid format. 
* Add three posts with "long" words in the titles. It's crucial that they are a little longer than normal.
* Resize the screen. Words push into the next column.

### What you expected to happen

The text to wrap

### What actually happened

The text doesn't wrap

### Context

Test site -
<img width="588" alt="Markup 2022-08-22 at 11 50 25" src="https://user-images.githubusercontent.com/13706336/185904243-2d10fd0d-c315-422b-8233-333a9cdca8f0.png">
 

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Themes tested Hemmingway Rewritten and Winkel

### Reproducibility

Consistent

**Comment by janmckell** [comment]
The user at 5499177-ZD provided a workaround, where they re-typed the text instead of pasting it, and the overflow of text worked as expected.

![wrapped text](https://user-images.githubusercontent.com/84089207/186157929-3cfd60c1-a4b1-4a26-82fd-9afb4f6a461c.jpg)

**Comment by Greatdane** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Could Not Replicate
- Tested on Self-hosted - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Was unable to replicate 
- Seems like the initial user was able to fix it by not pasting by typing the title. I wonder if there was some HTML/invalid character in the initial title? 

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
