### ISSUE TITLE
Theme/Plugin Bundling: Simplify seller steps

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#66815]
As part of the theme/plugin bundling, we're going to simplify how sellers end up going through the "Start simple" or "More power" flows.

**This needs to be behind the `themes/plugin-bundling` feature flag!**

How this will work:

- User picks the “Sell” intent.
- We take them to theme selection instead of “Start simple”/”More power”.
    - This means we need check for the "Sell" intent at the `options` step and go from there.
- If they pick a theme that has WooCommerce bundled with it, we switch them over to the plugin-bundle-flow (which currently mimics “More power”).
- If they pick a theme that doesn’t have WooCommerce bundled, then we continue as if they had picked “Start simple” (payment-blocks site).

See full discussion at paYKcK-20A-p2.

**Comment by valterlorran** [comment]
Clicking on the back button on the `designSetup` step is getting me redirected to `storeFeatures`. The progress bar is reset when you arrive at the `designSetup` step.

**Comment by markbiek** [comment]
> Clicking on the back button on the `designSetup` step is getting me redirected to `storeFeatures`. The progress bar is reset when you arrive at the `designSetup` step.

@valterlorran Would you mind opening a new issue for that?
