### ISSUE TITLE
Metrics planning & tracks events for the v13n standard designs

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#66835]
# Description
### Tracking performance of v13n of standard designs  in  https://github.com/Automattic/wp-calypso/pull/66680
- Geologist
- Stewart
- Arbutus
- Zoologist

This is a multi part issue (it can be broken into two issues if that makes more sense).

###  Part 1: planning & creating tracks events
Metrics analysis always starts with formulating good questions. What do we want to learn? In this case for these 4 verticalized themes, the question is straightforward: 

**Questions**: 
* Do users select the v13n version more or less than the standard (non-v13n) version?
* Is there a difference in theme switch rates (calypso_themeshowcase_theme_activate) for the v13n vs standard version?
* Are there other questions?  For me, I think it would not make sense to compare things downstream like launch rate, I think more the point is to analyze if the theme seems more "attractive" to users in the design picker.

Now that we defined our question(s), how do plan tracks events & tracks props to make our analysis easy?

It will be useful to have an event that fires only for verticalized designs/themes `calypso_signup_select_verticalized_design` (in part we need this because tracks tools aren't very useful when an analysis is needed that involved multiple props).  This should have prop `slug` so we can track both  standard themes and recipe layouts.

An example: If we have such an event we can compare data numbers for Geologist in  `calypso_signup_select_verticalized_design` and in `calypso_signup_select_design`

We can also add a prop to `calypso_signup_select_design`, prop=`is_v13n_theme` or `is_verticalized_theme` as this could be useful analysis.

### Part 2: Data analysis & P2 of the results
Once this feature has been in front of users for two or more weeks, do the analysis to answer the questions above.
It might be interesting to try out HUE for this too.  

Post results in a P2.

# Related / references

See Autumn 's P2 on v13n design picking
p1660873558910149/1660581132.320589-slack-C02TCEHP3HA

**Comment by arthur791004** [comment]
> Do users select the v13n version more or less than the standard (non-v13n) version?

@autumnfjeld Does it mean that we will have two versions of the theme shown in the bottom section of UDP? For example, the Geologist theme will show in the bottom section twice. One is verticalized and the other isn't.

If not, I think we cannot compare the result with the approaches you mentioned as the original event, `calypso_signup_select_design`, won't be fired anymore or the value of `is_verticalized_theme` will be always true. My original imagination is to compare data numbers before/after the release date. For example, if we release https://github.com/Automattic/wp-calypso/pull/66680 on Aug 29, we need to check whether the number of Geologist selections increases/decreases after Aug 29. If we see its curve going up, then the result is good and it might be worth selecting more and more themes to verticalize. If not, the result is not good and we might need to revert https://github.com/Automattic/wp-calypso/pull/66680

What do you think?

**Comment by autumnfjeld** [comment]
@arthur791004 
>  two versions of the theme shown in the bottom section of UDP

No, this isn't what I meant. (Although that is an interesting idea, kind of like we have multiple versions of TT2 and Geologist).  But no, that isn't what I meant.

There are many ways to set up the tracks events and props to be able to answer the question " Do users choose the v13n or  non-v13n  more."   For me the "right" way is the way that will be easiest (no google sheets).

Some thoughts:
You are right that if we wanted to record the v13n-Geologist via `calypso_signup_select_verticalized_design` then maybe we wouldn't want to record it on the event `calypso_signup_select_design`.   OR we could have both events fire when v13n-Geologist is selected and then we must do some calculations in a Google sheet to get the answer.  An example:   on Sept 15 we see that `calypso_signup_select_design` shows Geologist is chosen  20 times (this includes both v13n and non-vi13n).   But we know `calypso_signup_select_verticalized_design` shows v13n-Geologist fires 5 times on Sept 15.  THus we can conclude on Sept 15, the non-v13n was chosen 15 times but the v13n was chosen 5 times.   Does that make sense?

I'm not saying that is the best approach.  This is a great example of how it can be "hard" to figure out the best way to set up metrics.  I am happy with any tracks event approach that will answer the question:  " Do users choose the v13n or  non-v13n  more." 


> we need to check whether the number of Geologist selections increases/decreases 

True! This would give some idea if Geologist is picked more after the release.  Maybe that rough metric is enough.  
But how do you know users are choosing the v13n version?  Via the prop `is_verticalized` ?   Since we can't view two props together in tracks trends....you have do extra analysis in Google sheets....or maybe this is the ideal use case for HUE. 

I still think having the event `calypso_signup_select_verticalized_design` is useful, because we are isolating the event for v13n designs/themes and can use that as a very clear marker to see how v13n-Geologist is being selected.   
So in the situation user selects v13n-Geologist then both   `calypso_signup_select_verticalized_design` and  in `calypso_signup_select_design` would fire.

There are probably additional ways to set up tracking.... 🧠

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/67074 and we've added `calypso_signup_select_verticalized_design` when the user selects the verticalized design!

**Comment by autumnfjeld** [comment]
There is a Part 2.....so technically issue isn't done.  :).  Maybe next time I should make two issues, and put the P2 for the results is in a separate issue.

**Comment by arthur791004** [comment]
Oops...I forgot the Part 2 section... 😅

**Comment by autumnfjeld** [comment]
> I forgot the Part 2 section

hahaha.  I watching you @arthur791004 ! LOL.

**Comment by autumnfjeld** [comment]
Going to close this, as @fushar 's post  was the last step.  [Analysis: Selection of verticalized standard themes pbxlJb-2PI-p2
