### ISSUE TITLE
Style selection: Apply style variation to the new site

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#66842]
# Description

We want to be able to actually select the theme (static design) and a style variation. When the onboarding finishes, the style variation should be applied. 

# Acceptance Criteria

- [x] When a user selects a theme with a style variation, when the onboarding finishes, the site has the look-and-feel of the style variation.
- [x] When the user go to the site editor and checks the Global Styles sidebar, the selected style variation during onboarding, is also selected here.

# Dev Tasks

- [x] Implement button to submit selected design (theme) and variation, passing the necessary param to `themes/mine` endpoint.

**Comment by autumnfjeld** [comment]
This is a user facing project, all under the concept of "style selection" in calypso, all issues should be in wp-calypso.  If you temporarily make ganon-issues public, I think then that it is very easy to transfer the issue.

![image](https://user-images.githubusercontent.com/5665959/185813469-e57bb1b7-b940-4c24-8977-27798a258160.png)

**Comment by fushar** [comment]
Backend endpoint modification was done here by team Apex: D86760-code

**Comment by fushar** [comment]
All done, closing.
