### ISSUE TITLE
Site switcher adjustments

### ISSUE THREAD

**Issue by SaxonF** [Automattic/wp-calypso#66844]
### Details

To increase the visibility over the SMP we'll be making some iterations to the current site switcher sidebar.

**Single sites**

- Move add new site button to bottom of sidebar, under collapse. We can keep the existing, low prominence button style for now.
- Site switcher remains hidden

Multi sites
![image](https://user-images.githubusercontent.com/1072756/186086070-b4f780a9-4a5a-492a-9ae4-df4914c6fbba.png)
![image](https://user-images.githubusercontent.com/1072756/186086086-8920a8c9-c87d-450f-9a8e-cd50a59523e3.png)

- Move the add button to bottom of the sidebar and increase its prominence
- The add button will not trigger a dropdown as part of this first release and will behave as it does currently
- Add a "manage xx sites" button to the bottom above add new
- Keep the “all my sites” link when on a page that has a global equivalent, but change copy to "View [stats] for all sites"
- Hide the “View All Sites” button when on a page that doesn't have a global equivalent as this is covered by the manage sites button below

### Related

https://github.com/Automattic/wp-calypso/issues/65162

**Comment by danielbachhuber** [comment]
Closing in favor of #67040 and #67041
