### ISSUE TITLE
Site preview: Jackson theme alignment issue

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#66840]
## Description
In the unified design picker, the Jackson theme isn't correctly center aligned. See screenshots for mShots and iframe, respectively:

![Image](https://user-images.githubusercontent.com/797888/186076541-de89d734-7a28-4c8d-bbbd-741688cd15aa.png)
![Image](https://user-images.githubusercontent.com/797888/186076564-44fd9ca8-bf53-4163-ba31-202af02d2cd3.png)

While in Theme Showcase, it shows the preview correctly:
![Image](https://user-images.githubusercontent.com/797888/186076633-d1d965a9-6ea5-4dea-83f7-e196f6aae410.png)

## Acceptance Criteria
The Jackson theme preview for both mShots and iframe should render correctly as it is in the Theme Showcase.

**Comment by arthur791004** [comment]
This might be related to p1660885876278549-slack-CRWCHQGUB and it comes from Gutenberg with v13.19.0 above. We need to think about how to fix it.

**Comment by arthur791004** [comment]
Close it via D86538-code

Here is the screenshot after applying that patch:
![image](https://user-images.githubusercontent.com/13596067/186833745-2d82abcd-aaa3-4bc6-9c7b-50b6e3e408f3.png)
