### ISSUE TITLE
(esthetics) Remove G Suite mention under Emails > Add new mailboxes , replace it with Google Workspace

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#66868]
### Steps to reproduce

1. On an account with a Google Workspace subscription
2. Go to Emails > Add new mailboxes (https://wordpress.com/email/DOMAIN/gsuite/add-users/DOMAIN)

### What you expected to happen

To see "Google Workspace: DOMAIN" as the title

### What actually happened

I see "G Suite: DOMAIN" as the title
![image](https://user-images.githubusercontent.com/81776920/186178903-87de85de-7acc-4906-b6a2-5c5672a85a01.png)

### Context

5500067-zd-woothemes (no complaint linked)

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by zachspears** [comment]
This appears to have been updated since this issue was created. Thank you for reporting. Marking closed.
![Screenshot](https://user-images.githubusercontent.com/10124024/186776228-cc66d75d-2f8f-4e08-8800-3fbb5d6f9935.jpg)

**Comment by mxhassani** [comment]
@zachspears Thank you for checking. The issue seems to be pertinent on the user's account.

The "Google Workspace" label is displayed shortly when first loading the page then the G Suite label replaces it:

https://user-images.githubusercontent.com/81776920/187180736-1df63735-460a-4726-82ff-598e4b3633b2.mp4

* Firefox 103 on macOS (Catalina)
