### ISSUE TITLE
Galleries: < sign over gallery blocks

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/wp-calypso#66865]
### Quick summary

Above a gallery block there's a < character displayed.

User site:
https://libisoo.com/2022/08/23/hummus/

https://d.pr/i/Po99pg

I was able to reproduce it on my side using a different theme:
https://maciejpilarski41873144.wordpress.com/2022/08/23/gallery-test/

https://d.pr/i/uVMb6v

### Steps to reproduce

1. Create a New post
2.  Add some paragraphs 
3.  Add a gallery block
4. Save the changes/publish post

### What you expected to happen

Gallery without any <

### What actually happened

Gallery with < on top.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

**Comment by maciejpilarski** [comment]
ZD5500430

**Comment by anastas10s-afk** [comment]
ZD5500143

**Comment by carinapilar** [comment]
I have just spotted this too with the Gallery block, it also happens on P2 comments. I wasn't able to replicate it on WordPress.org.

**Comment by wiesenhauss** [comment]
HC36595062 - Tiled Gallery

<img width="305" alt="Screen Shot 2022-08-23 at 14 59 47" src="https://user-images.githubusercontent.com/99455043/186231315-540a80ac-354f-486c-a7f3-83be4085b888.png">

**Comment by ariel-maidana** [comment]
5500220-zd-woothemes

**Comment by mxhassani** [comment]
Similar case here: 5501094-zd-woothemes

User mentioned it was not there a day ago.
Tested on Twenty Seventeen and Heiwa.

### ❗ Affects Tiled Gallery block too

Workarounds (not ideal):

* Converting the Gallery block to one of the other blocks:

![image](https://user-images.githubusercontent.com/81776920/186242160-b2ed0631-c778-4635-bb68-f1cfc539af8e.png)

* Putting the Gallery block inside a Group block, then set text color on that group to match the page background color.

**Comment by daledupreez** [comment]
This is almost certainly a regression introduced by my changes in Automattic/jetpack#25441, specifically on this line: https://github.com/Automattic/jetpack/blob/d5e90d438ba4678c30c2c13f8f032a86610f5409/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php#L386

The issue seems to be that I unnecessarily added a `<` to the replacement.

@mpkelly, could you take a look at this when you get in tomorrow if someone hasn't managed to get this fixed in the meantime? (I am too tired to take this on at the moment!)

**Comment by metabreakr** [comment]
5501650-zen

5501522-zen

**Comment by oskosk** [comment]
Patch deployed (D86416-code)
Jetpack fix: https://github.com/Automattic/jetpack/pull/25795

**Comment by kraftbj** [comment]
Note for Atomic sites: the fix resolving this is expected to go out tomorrow, likely in the US morning.

**Comment by oskosk** [comment]
Thanks @kraftbj !

**Comment by dragstor** [comment]
5503408-zen
5503398-zen

**Comment by i11za** [comment]
I originally thought this was theme related, and reported it [here](https://github.com/Automattic/wp-calypso/issues/66871). 

Another report: 5500318-zen

**Comment by daria2303** [comment]
I am still getting it here 5503523-zd-woothemes and also on one of my test sites but on another one no. Didn't find a rule.

**Comment by daledupreez** [comment]
@daria2303, I believe the issue is due to the fix not being rolled out to Atomic sites yet. The update has been requested in p9o2xV-2mz-p2, and should occur at some point today. (I confirmed that the site in your ticket is still running Jetpack version 11.3-a9, which includes the bug.)

**Comment by oskosk** [comment]
@daria2303 the fix was rolled out to Atomic sites yesterday. Closing this again. Thank you
