### ISSUE TITLE
[Bug]: Searching doesn't work for users with unindexed languages

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#66866]
### Quick summary

As a wpcom user with my language set to en_GB (British English) when I search using the elastic search marketplace MVP I get zero results regardless of my search term. 

### Steps to reproduce

1. Set WPcom account to en_GB
2. Go to wpcalypso.wordpress.com/plugins
3. Type 'jetpack search' in the search box and hit enter

Any other search string which should bring up .org plugins will also illsutrate.

### What you expected to happen

To see search results from .org

### What actually happened

Zero results found

### Other notes

Inspecting the API request shows it doesn't give any results

https://public-api.wordpress.com/rest/v1.3/marketplace/search?http_envelope=1&locale=en-gb&fields[0]=blog_icon_url&fields[1]=comment_count&fields[2]=plugin.excerpt&fields[3]=like_count&fields[4]=modified&fields[5]=modified_gmt&fields[6]=plugin.title&fields[7]=author&fields[8]=author_login&fields[9]=blog_id&fields[10]=date&fields[11]=date_gmt&fields[12]=permalink.url.raw&fields[13]=post_id&fields[14]=post_type&fields[15]=slug&fields[16]=plugin.tested&fields[17]=plugin.stable_tag&fields[18]=plugin.active_installs&fields[19]=plugin.support_threads&fields[20]=plugin.support_threads_resolved&fields[21]=plugin.rating&fields[22]=plugin.num_ratings&fields[23]=plugin.icons&query=batman&sort=score_default&size=20&group_id=wporg&lang=en_GB

Changing the lang getvar to just lang=en, and there are lots of results.

Gets results:
 * en
 * de_DE

No results:
 * en_GB
 * en_CA

400 bad request:
 * de
 * de_AT
 * en_US

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Change your account language

**Comment by dsas** [comment]
Detective work:

I noticed that the endpoint sometimes uses `Jetpack_WPES_Search_Query_Parser` which has a list of languages and a function to normalise them, which looks like it would avoid this problem. Use of the language normalisation was explicitly disabled in D82452-code though. It's not clear from that commit why but some of the comments on the initial implementation (D81357-code#1715923) hint that it wasn't right for us and yielded mixed-language results. If I try temporarily undoing this, the tests do start failing. D83978-code looks like where the current multi-lingual mechanism is implemented though.

More recently, and on the client-side #65548 added some Calypso code to get the wpSlug [from the Calypso languages list](https://github.com/Automattic/wp-calypso/blob/trunk/packages/languages/src/languages-meta.json) and give that to the server. It's related to D84165-code, which is as-yet unfinished.

**Comment by dsas** [comment]
The locales giving a 400 response is because they're searching for an unknown locale. It returns false from `es_api_search_index` and has an error like this logged:

```
Elasticsearch error: {
  "level": "warning",
  "message": "Response",
  "context": [
    "{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no mapping found for field [plugin
.all_content.de_AT
    ]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":26,"index":"jetpack-search-21","node":"
ArpBgOQwQgq1UlVDlyZ2-w","reason":{"type":"illegal_argument_exception","reason":"no mapping found for field [plugin.all_content.de_AT
    ]"}}],"caused_by":{"type":"illegal_argument_exception","reason":\
"no mapping found for field [plugin.all_content.de_AT
    ]","caused_by":{"type":"illegal_argument_exception","reason":"no mapping found for field [plugin.all_content.de_AT
    ]"}}},"status":400}"
  ]
}
```

**Comment by dsas** [comment]
I opened D86578-code for fixing the 400 errors that querying while using an unindexed language gives

**Comment by dsas** [comment]
The locales giving 400 responses has been resolved (D86578-code). The locales giving no results is a wip

**Comment by dsas** [comment]
I've got a WIP at D86717-code for fixing it for British English

**Comment by BogdanUngureanu** [comment]
@Automattic/ajax D86717-code is now ready for review.

**Comment by BogdanUngureanu** [comment]
Deployed in 9c1ba06aeb2344ae6d6675c479f858a748ea799e
