### ISSUE TITLE
FSE: Allow Preview in New Tab from Site Editor

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#66873]
### What

Add the **Preview in new tab** option to the site Editor so you can see how template changes will really look on the front end.

### Why

It would be really useful to be able to preview template changes in the Site Editor the way you can preview page/post changes in a separate tab so that you can see what your changes will really look like. Right now, we have to save the template and then if we view it on the front end and it doesn't look the way we expect, there is no revision to go back to. 

Even if we get the ability to access revisions, this would still be useful because it allows you to see how pages will look if the Additional CSS you've added is applied. And also, it gives HEs the ability to experiment on a user's site to see how a template change will look without having to save the template.

### How

Add the **Preview in new tab** option in the site Editor the same way it is added in the Page and Post editor.

**Comment by Greatdane** [comment]
Possibly related core issue; 
- https://github.com/WordPress/gutenberg/issues/29398

**Comment by zachspears** [comment]
@Greatdane is correct, https://github.com/WordPress/gutenberg/issues/29398 appears to be the appropriate core issue and correct location for this feature. Closing this issue. 👋
