### ISSUE TITLE
Theme: Twenty Fourteen shows `>` symbol before above Gallery block

### ISSUE THREAD

**Issue by i11za** [Automattic/wp-calypso#66871]
### Quick summary

A `>` symbol appears above Gallery Block with Twenty Fourteen on simple sites. Not an issue on AT sites.  

Initially suspected to be due to the fact that the reported gallery was nested within a Cover Block, but was able to replicate with a separate "stand-alone" Gallery Block as well. 

### Steps to reproduce

1. Create a gallery, add images. 
2. Preview in new tab, or publish the page. 

### What you expected to happen

Looks as it does in the editor:

- Gallery Block
<img width="537" alt="image" src="https://user-images.githubusercontent.com/84193945/186182236-4e1a5541-6e18-48e5-a730-48b9ae61e855.png">

- Gallery Block nested inside a Cover Block (as initially suspected this to be the cause)
<img width="550" alt="image" src="https://user-images.githubusercontent.com/84193945/186182047-339d2aba-9e78-4c7f-aca1-a035b010c676.png">

### What actually happened

When previewing in a new tab, or on live page/post a `>` appears above the gallery

- Gallery Block
![image](https://user-images.githubusercontent.com/84193945/186183583-6faa47d3-81ca-4936-bffc-b5f7e13640ec.png)

- Gallery Block nested inside a Cover Block
![image](https://user-images.githubusercontent.com/84193945/186183699-9b4ec951-72f4-4a74-9b62-7a154b53292f.png)

### Context

Customer report: 36574197-hc
Follow-up ticket: 5500318-zd-woothemes
Slack discussion: p1661257917489649/1661256349.130059-slack-C03TY6J1A

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Twenty Fourteen

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by i11za** [comment]
User wrote back to say the issue has been resolved, and testing this on my side I'm no longer able to replicate it either. Could it have been fixed in one of recent deployments?

**Comment by i11za** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/66865 - has now been fixed.

**Comment by daledupreez** [comment]
@i11za, can we close this issue? It looks like this is a duplicate of the now-resolved #66865.

**Comment by CodeAllNightNDay** [comment]
I have a case here with Twenty Fourteen theme as well:
29886764-hc

It's the Gallery Block in this instance, and the site is Atomic.

**Comment by daria2303** [comment]
Same in 5503523-zd-woothemes, I reopened https://github.com/Automattic/wp-calypso/issues/66865

**Comment by daledupreez** [comment]
@CodeAllNightNDay and @daria2303, it looks like the remaining sites that are affected are all Atomic sites -- the fix hasn't been rolled out to Atomic sites yet: that has been requested in p9o2xV-2mz-p2.

**Comment by i11za** [comment]
> @i11za, can we close this issue? It looks like this is a duplicate of the now-resolved #66865.

@daledupreez yes please, I was planning to check whether to closer or to merge with https://github.com/Automattic/wp-calypso/issues/66865, but the day got away from me. Thank you!

**Comment by zachspears** [comment]
This ticket has just come up in Triaging. Looks to be a duplicate of #66865, which has been closed. I just tested this and confirmed. Marking resolved.
