### ISSUE TITLE
Marketplace: Improve images quality in plugin pages

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/wp-calypso#66906]
An example: https://wordpress.com/plugins/wordpress-seo-premium

The images aren't of high quality (perhaps not retina ready), which affects negatively the perception (and clarity) of what we sell. 

![image](https://user-images.githubusercontent.com/25516611/186386772-29061be6-9db4-4865-aaf8-152d4d2a8499.png)

**Comment by cpapazoglou** [comment]
The problem mainly comes from the fact that we dynamically reuse images that meant for a 2-column layout where they appear smaller. We will try to fix this by changing the source images to higher quality ones.

@Automattic/explorers before adding any more plugins, let's make sure that the images they provide us are high quality.

**Comment by allilevine** [comment]
> @Automattic/explorers before adding any more plugins, let's make sure that the images they provide us are high quality.

@cpapazoglou Can we be more specific about high quality? What size are we looking for?

**Comment by cpapazoglou** [comment]
The grid max-width is `667px`. Aiming for retina images means that width should be `1334px`.

**Comment by cpapazoglou** [comment]
@alanabweinstein, @josemarques 
the following woo extensions are offered through WordPress.com too. Can you replace the images in description with higher quality ones?

 `woocommerce-subscriptions`;
 `woocommerce-bookings`;
 `woocommerce-table-rate-shipping`;
 `automatewoo`;
 `woocommerce-shipment-tracking`;
 `woocommerce-xero`;
 `woocommerce-points-and-rewards`;
 `woocommerce-deposits`;
 `woocommerce-one-page-checkout`;
 `woocommerce-shipping-fedex`;
 `woothemes-sensei`;
 `woocommerce-pre-orders`;
 `woocommerce-shipping-usps`;
 `woocommerce-shipping-canada-post`;
 `woocommerce-product-addons`;
 `woocommerce-min-max-quantities`;
 `woocommerce-product-vendors`;
 `woocommerce-shipping-ups`;
 `woocommerce-shipping-australia-post`;
 `woocommerce-shipping-royalmail`;
 `woocommerce-product-bundles`;
 `woocommerce-conditional-shipping-and-payments`;
 `woocommerce-composite-products`;
 `woocommerce-gift-cards`;
 `woocommerce-product-filters`;
 `woocommerce-product-csv-import-suite`;
 `woocommerce-additional-variation-images`;
 `woocommerce-shipping-per-product`;
 `automatewoo-referrals`;
 `woocommerce-all-products-for-subscriptions`;
 `woocommerce-shipping-stamps`;
 `woocommerce-eu-vat-number`;
 `woocommerce-distance-rate-shipping`;
 `woocommerce-back-in-stock-notifications`;
 `woocommerce-product-recommendations`;
