### ISSUE TITLE
Unified design picker: Too much vertical white space when themes are filtered by "Business" and other filters

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#66905]
## Description
In the unified design picker, when themes are filtered by "Business" there is a big vertical gap between the first and second row. See screenshot for reference:

![Image](https://user-images.githubusercontent.com/797888/186385386-be17dcef-3c50-4b74-9402-45270fdc3a69.png)

 ## Acceptance Criteria
The vertical spacing should be the same across filters.

**Comment by bangank36** [comment]
I am on trunk and the issue seems to be happening on the ~~generated design picker~~ generated designs on UDP as well

![Screenshot on 2022-08-24 at 17-24-17.png](https://cdn-std.droplr.net/files/acc_1243635/KMo8Mq)

**Comment by taipeicoder** [comment]
@bangank36 how are you seeing this on trunk? We shipped UDP, the generated design picker shouldn't be accessible anymore.

**Comment by bangank36** [comment]
It is the generated design ~~picker~~ on UDP, screenshot taken from Build flow

![Screenshot on 2022-08-24 at 17-36-39.png](https://cdn-std.droplr.net/files/acc_1243635/v2xpbO)

**Comment by bangank36** [comment]
> @bangank36 how are you seeing this on trunk? We shipped UDP, the generated design picker shouldn't be accessible anymore.

Sorry I used an incorrect name, updated the comment for clarification

**Comment by arthur791004** [comment]
I thought we have to revert that [change](https://github.com/Automattic/wp-calypso/pull/66733) to fix the production issue. The UDP looks so bad now...

https://user-images.githubusercontent.com/13596067/186598128-02e7c4e4-f6a9-43a4-b9ea-fc780aff5020.mov

@Automattic/ganon What do you think?

**Comment by bangank36** [comment]
> I thought we have to revert that [change](https://github.com/Automattic/wp-calypso/pull/66733) to fix the production issue. The UDP looks so bad now...

I agree to revert this PR, the page jump issue is a minor bug though...

**Comment by arthur791004** [comment]
Here is a reverting PR: https://github.com/Automattic/wp-calypso/pull/66957

**Comment by miksansegundo** [comment]
If we want to use the same kind of workaround that we had before for fixing the jump we could just add a `min-height` to the class `.unified-design-picker__standard-designs`.

**Comment by taipeicoder** [comment]
Closed due to #66957 being merged.
