### ISSUE TITLE
Comments: Comment submission does not work, users get "Error: Please fill the required fields" error.

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#66904]
### Quick summary

Some of the WordPress.com sites are facing issues when users are trying to comment on them.

The error in action-
<img width="884" alt="Screenshot 2022-08-24 at 2 34 27 PM" src="https://user-images.githubusercontent.com/40609190/186377900-f74b9858-e5ed-4a82-b473-e14868186a62.png">

The browser is able to recognise that users are logged in-
![Markup on 2022-08-24 at 14:35:48](https://user-images.githubusercontent.com/40609190/186378216-d1bed20a-d3cb-426f-866c-ae13344b6736.png)

However, as soon as we try submitting a comment, we get the error.

For sites that allow anonymous comments, or, after turning off the discussion setting for “Comment author must fill out name and e-mail”, one would be able to submit the comment, however, the comment would show up as **Anonymous** comment-
<img width="679" alt="Screenshot 2022-08-24 at 2 40 22 PM" src="https://user-images.githubusercontent.com/40609190/186379808-360a3e7c-7fef-47c1-9de7-29d24e895441.png">

### Steps to reproduce

1. Go to the post/page of an affected site to comment on while being logged in to your WordPress.com account. 
2. Write and submit a comment.

### What you expected to happen

I expect the comment to get posted. 

### What actually happened

If anonymous comments are allowed, then the comment gets posted, however, the user details are not recorded and the comment shows up as **Anonymous**.

If anonymous comments are not allowed on the site, then the comment does not go through and we get the error.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

zen-5501643, zen-5498421, zen-5497964, zen-5500997

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

I was not able to replicate this issue on my two test sites, one FSE and another non-FSE. However, seeing more and more reports from users.

Console shows-
<img width="505" alt="Screenshot 2022-08-24 at 2 47 26 PM" src="https://user-images.githubusercontent.com/40609190/186380849-9d95a53f-ccd2-46de-93e9-65151edb8750.png">

Not seeing any CLI errors, however a few notices and warnings-
<img width="1422" alt="Screenshot 2022-08-24 at 2 49 39 PM" src="https://user-images.githubusercontent.com/40609190/186381424-b5812be6-9564-4888-9e0e-eaaa9e8ee98d.png">

Tried disabling all plugins, did not help.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

We can still comment if the commentator manually fills out the name, email fields while being **logged out** of their account-

<img width="916" alt="Screenshot 2022-08-24 at 2 54 18 PM" src="https://user-images.githubusercontent.com/40609190/186382392-c68fe61c-b79c-406a-a5e5-a42807b1a914.png">

**Comment by ahmadbaig1** [comment]
Please note the issue was not reproducible on one of the above user's site after being initially reported.

**Comment by connorhipps** [comment]
Issue reported here as well: 5493407-zd-woothemes

**Comment by ccwalburn** [comment]
Issue reported here: 34098134-hc

Created follow-up ticket in case we bulk notify:

- [ ] 5504898-zen

**Comment by ahmadbaig1** [comment]
Also reported here: 5492149-zen

**Comment by kmrpankaj** [comment]
Issue reported here 5505011-zen

**Comment by connorhipps** [comment]
This appears to be the same issue, though the error message isn't displayed: 5497974-zd-woothemes

**Note:** The user is attempting to post to a .org site where they are listed as "Anonymous." Please see the ticket for the site URL.

**Comment by vajrasar** [comment]
Another here 

- [ ] 5504839-zen

**Comment by kerrynicl** [comment]
Another reported here 5504839-zen

**Comment by radtechgh** [comment]
Another report here: 
5506996-zen
Simple site.

**Comment by masperber** [comment]
Another report

- [ ] 5507397-zen

**Comment by retnonindya** [comment]
Not a user interaction, but personal experience: This explains why I can't comment on @robfelty's blog post [here](https://www.fedibblety.com/2022/08/a-warm-house/) I thought it was an error on my end so I didn't think much about it.

**Comment by robfelty** [comment]
> Not a user interaction, but personal experience: This explains why I can't comment on @robfelty's blog post [here](https://www.fedibblety.com/2022/08/a-warm-house/) I thought it was an error on my end so I didn't think much about it.

And here I thought you were just ignoring me :)

**Comment by Robertght** [comment]
Adding this to the [Dotcom Bug Prioritization Board](https://github.com/orgs/Automattic/projects/343#card-85263255) and marking it as a High priority. cc @vajrasar 

Checking with @ahmadbaig1 for now if this was added through Bugomattic as I don't see the automation.

**Comment by Robertght** [comment]
~Another report: 5476871-zen~

ignore this one

**Comment by mxhassani** [comment]
There is a P2 regarding a similar case, being worked on here: p2EDhh-1Fg-p2#comment-8161

**Comment by msilbers** [comment]
reported by someone who would like to be notified once resolved

- [ ] 5509543-zen

**Comment by ebinnion** [comment]
I've reverted D79454-code which I believe will address the immediate issue. Of note, this also has the effect of hiding the social logins when 3rd party cookies are not supported.

**Comment by ebinnion** [comment]
After some investigation, I have found the root and can confirm that it should be fixed in the above revert. I have a second go at a patch to address third-party cookie issues taking into account the root issue.

I'll plan on getting this reviewed and deployed early next week. D86706-code

**Comment by paxblueribbon** [comment]
Adding to this a customer asking for an update when its resolved: 
zd-5505011

**Comment by supernovia** [comment]
There are dozens of folks complaining of issues on this site:
https://bayphotosbydonna.com/2022/08/24/blog-commenting-issues/

**Comment by sophiegyo** [comment]
I landed on #5492149-zen (mentioned above) and I had an idea.
I tried deactivating the Protect module in Jetpack, and posted a comment. This worked.

Screen recording: 

https://user-images.githubusercontent.com/36608681/187022172-6e5719ea-74e9-4ca6-a185-628415f04928.mp4

The result:

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/36608681/187022180-d54eac13-ed90-4669-a822-8e96da32c395.png">

Evidently the "self-contained" errors in the console aren't too much of a problem because I noticed that after submitting my comment, this notice came up in the console:

```
Partitioned cookie or storage access was provided to “[https://jetpack.wordpress.com/jetpack-comment](https://jetpack.wordpress.com/jetpack-comment/?blogid=207848809&postid=1973&comment_registration=0&require_name_email=1&stc_enabled=1&stb_enabled=1&show_avatars=1&avatar_default=identicon&greeting=Leave+a+Reply&jetpack_comments_nonce=d686983941&greeting_reply=Leave+a+Reply+to+%25s&color_scheme=light&lang=en_US&jetpack_version=11.3-a.11&show_cookie_consent=10&has_cookie_consent=0&token_key=%3Bnormal%3B&sig=931b238cc17756bbf6bb919dd79dcbb47ad37276#parent=https%3A%2F%2Fconwegian.com%2F2022%2F08%2F10%2Fcity-awarded-24-6-million-grant-for-connect-conway-project%2F)
```

So I'm guessing it's more to do with Protect. When I first saw the ticket I suspected it might be something to do with a recaptcha (I've seen another ticket where someone who had to install a recaptcha plugin for their forms found it blocked comments in a similar manner to this) but since the above site does not have any recaptcha plugins I wondered if similar protective functions - in this case Jetpack Protect - might cause it.

I updated the user in this ticket to let them know we're working on it, and that I was able to submit a comment without Jetpack Protect being on.

**Comment by AMcGrady** [comment]
Adding to this a customer asking for an update when its resolved:
5471252-zen

**Comment by jordesign** [comment]
> After some investigation, I have found the root and can confirm that it should be fixed in the above revert. I have a second go at a patch to address third-party cookie issues taking into account the root issue.

> I'll plan on getting this reviewed and deployed early next week. D86706-code

@ebinnion  just to confirm - the revert means the issue should no longer be occuring for users? And that proposed deploy is the one that would try again, taking the previous issue into account?

**Comment by hacchism** [comment]
Another report:
5505287-zen

**Comment by brinbliss** [comment]
User in 5493407-zd-woothemes provided this workaround that fixes a single site, from Apple Support.

This workaround may work for more sites, but has only been tested by this user on one site: click "log out" where the profile icon shows up in the comment field. From here, re-sign in to WordPress.com and then open up the comment reply box. Fill out the name/email address/site name fields, and then click "save".

**Comment by ebinnion** [comment]
> @ebinnion just to confirm - the revert means the issue should no longer be occuring for users? And that proposed deploy is the one that would try again, taking the previous issue into account?

Correct

**Comment by ccwalburn** [comment]
@ebinnion I had a report at 14:50 UTC today that it was still a problem. Does the user need to do something on their end?
5497964-zen

**Comment by ebinnion** [comment]
It looks like the user reported that they weren't reporting issues after you followed up with them and the issue was subsequently closed.

**Comment by wiesenhauss** [comment]
Another report:
- [ ] 5524644-zen

**Comment by supernovia** [comment]
> * 5524644-zen

@wiesenhauss if their edit button is giving them trouble too, could this one be an issue with cookies in general and not just the comment form?

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group has finished following up with the affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by vajrasar** [comment]
Quick Note: The issue was addressed in two parts:
Reverting D79454-code
Reimplementing those changes in D86706-code
