### ISSUE TITLE
Comments on AT Sites not working in Chrome

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#66914]
### Quick summary

A user has reported that some of their site visitors notified them that they cannot leave comments. After testing, it appears that this is affecting AT sites on Chrome. When a visitor tries to leave a comment, even if they are logged into their WordPress.com account, they see a message stating `Error: Please fill the required fields.`

### Steps to reproduce

1. Have a test page where people can leave comments on an AT site
2. Ask some of your colleagues to leave comments within the Chrome browser to see if they get the error message as well
3. Test again on a Simple site

### What you expected to happen

The comment should post to the site without issue.

### What actually happened

The `Error: Please fill the required fields.` message appears, even if that visitor is logged into their WordPress.com account.

### Context

Initial report: 36575952-hc

Screenshot from teammate leaving comment on AT Site: ![BtnOCv.png](https://user-images.githubusercontent.com/51870544/186421896-af226d1d-3e34-4a0e-9be7-d5eeb22eab10.png)

Screenshot from teammate leaving comment on Simple Site: ![t7Zdak.png](https://user-images.githubusercontent.com/51870544/186421965-967f0fa9-8c72-4ced-ba95-94ebf03fcfdb.png)

Slack discussion: p1661178226142839-slack-C03TY6J1A

### Platform (Simple, Atomic, or both?)

Atomic

### Browser, operating system and other notes

Chrome-specific issue from my testing.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Deactivating the `Comment author must fill out name and e-mail` option under `Settings > Discussion` bypasses this issue.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - no

📌 ACTIONS
- Closed as duplicate of  https://github.com/Automattic/wp-calypso/issues/66904#issuecomment-1228612870
