### ISSUE TITLE
Unsubmitted plugin search term does not clear during navigation

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#66937]
Would like to check if this would be considered an issue or an intended behavior:

1. Enter the search term but don't actually search
2. Navigate to a category
3. search term is preserved

Screencast:

https://user-images.githubusercontent.com/6586048/186385899-9537b3ab-e74a-4384-bc2c-604bc865f12c.mp4

_Originally posted by @candy02058912 in https://github.com/Automattic/wp-calypso/issues/66883#issuecomment-1225482094_

**Comment by candy02058912** [comment]
Hi @vinimotaa, would love your input on this:
Would we want to preserve users' unfinished actions?
Also linking to input from this comment: https://github.com/Automattic/wp-calypso/pull/66883#issuecomment-1226635501

**Comment by cpapazoglou** [comment]
Cannot reproduce anymore.
