### ISSUE TITLE
Plugin Search behavior seems unintuitive when under a category

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#66938]
The behavior of the Plugin Search box when underneath a category seems unintuitive.

When you search for a term while under a category:

* The URL changes to:
https://wordpress.com/plugins/browse/{category}/example.wordpress.com?s={search-term}
* The breadcrumbs includes the category
* Clicking "X" in Search takes you back to the category
* Clicking on "Clear" takes you back to the main plugins page

The search itself is in no way related to the category. Since the URL and breadcrumbs show the category and the "X" takes you back to the category, I'd expect the search term to search only within the category we're currently in. Since it does not, I'd expect the URL and breadcrumbs to NOT contain a category, and the "X" should always take us back to the main plugins page, just like "Clear" does.

![search-category](https://user-images.githubusercontent.com/140841/186512014-b7ebc5d1-5b2a-4311-bc95-830c268b0908.png)

I feel like (unless we start limiting search results within a category) Search results should always be after the "root" Plugins page, no matter what page you submitted the search form from.

![search-root](https://user-images.githubusercontent.com/140841/186522382-25a5e765-f401-4517-9fb2-80321ca9fdf3.png)

**Comment by lsl** [comment]
Agree with all of this.

Building on top of your suggestion in slack to update the full path in `pageToSearch` p1661381701763909/1661372850.310569-slack-CKZHG0QCR

Could we move search to its own route entirely? `/plugins/search?s=...` ? That might help focus us in on changing the right things in the right places.

**Comment by DustyReagan** [comment]
Paging @Automattic/bespin for potential feedback. ☺️ Any thoughts on moving the Search results out from underneath categories?

**Comment by cpapazoglou** [comment]
We should either:
- Respect the current category when searching
- If we cannot do the above, remove the category from URL and breadcrumb when user initiates a search

**Comment by lsl** [comment]
Context to the above comment in case you need it: pdh6GB-1QJ-p2#comment-2778

**Comment by cpapazoglou** [comment]
Discussed it within the team and voted for updating the UI ( url and breadcrumb ) to account for the "All results" page.
