### ISSUE TITLE
[Comment Approval] Display commenter's Great Posts section

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66975]
The new email template should include _Great Posts_ section:

![Image](https://user-images.githubusercontent.com/25105483/186648233-cc11e35b-9fed-4144-a89a-9058299a06af.png)

The logic and styling should be the same as in the _New Comment_ email template.

Figma: c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A24079

**Comment by yansern** [comment]
Draft PR. D87118-code

**Comment by yansern** [comment]
Ready for review.
