### ISSUE TITLE
[Comment Approval] Display commenter's information (URL, Email, Whois)

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66976]
The new email template should include information about the commenter:

![Image](https://user-images.githubusercontent.com/25105483/186648986-88b79131-7e78-441b-8e41-df283d010fb1.png)

Figma: c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A24079
Similar task for the _New Comment_ email template: https://github.com/Automattic/wp-calypso/issues/65748

**Comment by yansern** [comment]
Draft PR. D87116-code

**Comment by yansern** [comment]
Ready to review.

**Comment by ivan-ottinger** [comment]
The patch has been merged.
