### ISSUE TITLE
[Bug]: tailored flows: can't upload big image

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#66980]
### Quick summary

Can't upload big images as logo/avatar for link-in-bio and newsletter.

### Steps to reproduce

1. Start newsletter flow https://horizon.wordpress.com/setup/?flow=newsletter
2. Upload big image file as a logo
3. 
    ![Screenshot 2022-08-25 at 14 27 59](https://user-images.githubusercontent.com/87168/186652816-824c3cfd-eb3c-4dc6-b2bb-ebdd0a564fea.png)

4. Note error at console when pressing continue
5. 
    ![Screenshot 2022-08-25 at 14 27 20](https://user-images.githubusercontent.com/87168/186652808-04e2bff4-646d-419b-8315-42b4bcfee0cf.png)

### What you expected to happen

Big images to work or at least error gracefully.

### What actually happened

UI froze, no way to continue.

How is this stored, are is that storage available in incognito mode?

### Reproducibility

Consistent

**Comment by heavyweight** [comment]
We were assuming that this can be an issue. I tried to provoke this by uploading 10mb image and it didn't happen for me.
@simison how big was the image you uploaded?
