### ISSUE TITLE
[Bug]: Plugin search page's width breaks in Calypso

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#66990]
### Quick summary

With certain search terms, Calypso's plugin directory page will break.

A few search terms where this happens are `pop-up`, `elementor`

![U56I6bqPZj8OMMxLWImZotyVerxkXJAJWovUlvEa.jpg](https://user-images.githubusercontent.com/84539773/186675955-02990c7c-f66d-41f5-9aa1-86f386f767bf.jpg)

![yHp5ToyTGFtKMvvPg4hsLaXhZY2BeIIw3pwc9r6p.jpg](https://user-images.githubusercontent.com/84539773/186677457-ef35599c-8c4d-44b8-8a0d-37bfc4909f57.jpg)

Simple sites are the same:

![tddKonw1QeD355L2t1722rwKExl32DZM3H3FWPvJ.jpg](https://user-images.githubusercontent.com/84539773/186678209-476711fd-8431-471d-b761-acf6ff9b3a39.jpg)

Happened on Firefox and Chrome 104 on MacOS.

Possibly caused by this CSS:
<img width="330" alt="image (1)" src="https://user-images.githubusercontent.com/84539773/186680999-e4177570-0b2b-4dbe-a320-684aeff811a9.png">

### Steps to reproduce

1. Visit https://wordpress.com/plugins/
2. Search for `elementor`

### What you expected to happen

The width remains the same.

### What actually happened

The width is too large.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

[p1661431979606559-slack-C03TY6J1A](p1661431979606559-slack-C03TY6J1A)

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Seems resolved.

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/236019418-0eac5e44-8240-4d9e-9cd3-96caabd0d835.mov

📌 ACTIONS
- Closed as no longer relevant
