### ISSUE TITLE
Donations Block: Predefined amounts ($5, $15, and $100) are only charging customers with $1

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#66997]
### Quick summary

When users' customers select any of the predefined amounts on the Donation block to make a donation, they are only getting charged $1.

![Markup on 2022-08-25 at 12:18:59](https://user-images.githubusercontent.com/50875131/186706171-06762ff3-7fa2-4697-af00-f42a2c17af99.png)

### Steps to reproduce

1. Add the Donation block to a page.
2. Publish the page and proceed with a donation.
3. Choose one of the predefined amounts.
4. Proceed with payment.
5. When checking payment history or bank receipts, we will only see a 1$ charge.

### What you expected to happen

I expected customers to be charged for the amount they selected.

### What actually happened

Users' customers are only paying/donating $1.

### Context

Reports so far:

5504364-zd-woothemes
5504465-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by mmtr** [comment]
This was a regression caused by D86063-code (intended to fix https://github.com/Automattic/jetpack/issues/25030) so I reverted that and users should be charged the right amount again.

**Comment by inaikem** [comment]
5502334-zd-woothemes

User attempted 2x $100 payments and was billed $1 each time. They manually donated using details provided elsewhere on the site.

Adding the interaction here as we may have a few more to track and respond to. 

Context: p1661674867361469/1661441678.719449-slack-C02FMH4G8

**Comment by vajrasar** [comment]
@mmtr this seems to have returned. Can you please check?

I got a user here 6650767-zen and also I can replicate the issue on my test site.

**Comment by poeticabdul** [comment]
Reported here 6601925-zen

**Comment by mmtr** [comment]
Hey @Automattic/gold, have you introduced any change recently that might have caused this?

**Comment by mmtr** [comment]
Seems that the default donation plans are now created with the `is_editable` flag to true and that's making the checkout form to use the default/fake plan amount ($1) to be used here: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Szrzorefuvcf%2Spynff.zrzorefuvcf%2Qpurpxbhg%2Qsbez.cuc%3Se%3Q7q64rqo1%26zb%3Q17469%26sv%3Q337%23337-og

Those default donation plans should be created with the `is_editable` flag to false, so it seems that a regression has been introduced somewhere (cc @Automattic/gold).

**Comment by mmtr** [comment]
Looks like the regression was introduced in D115524 (cc @millerf). As of that diff, `generate_default_products` (which is used to create the default donation plans) changes the `is_editable` param from the 5th argument to the 4th one. But the function is still used setting the the `is_editable` param in the 5th argument because https://github.com/Automattic/jetpack/pull/31749 was never merged.

**Comment by millerf** [comment]
@mmtr Thanks for reporting. I am AFK right now, but this issue duplicates https://github.com/Automattic/jetpack/issues/32092 that is being handled by @pottedmeat.

**Comment by millerf** [comment]
> https://github.com/Automattic/jetpack/pull/31749 was never merged.

Oooh.. Nicely catch. Referencing in https://github.com/Automattic/jetpack/issues/32092

**Comment by inaikem** [comment]
Looks like this was fixed in the linked issue above. Is someone able to help confirm? Thanks!

**Comment by mmtr** [comment]
I cannot longer reproduce it on my end, so closing this one out. Feel free to re-open if the issue still happens.
