### ISSUE TITLE
Customizer: no way to exit Preview mode and pick a different theme easily

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#67]
**Steps to reproduce:**

1. Go to My Sites > Themes (Customize)
2. Once you're in Customizer, change your Theme
3. pPck a Theme then hit Preview
4. Exit this Preview (to pick a different theme) but be taken to My Sites instead

I'm unable to exit the Preview mode to pick another theme. When I hit "X" on the upper left corner, I am instead taken to My Sites and have to go through all of the above steps again. I should be able to preview a Theme, exit this preview mode and be able to easily preview a different Theme again.

**Video:**
https://cloudup.com/cxuVJ-NTOBu

**Comment by mattwiebe** [comment]
Another bug fixed after #1227 was fixed! :tada:
