### ISSUE TITLE
[Bug]: Can't introduce a new password in signup page

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#67031]
### Quick summary

If you insert the wrong password on the signup page you can't create a new one.

### Steps to reproduce

1. Go to wordpress.com
2. Insert a username
3. Insert a password identical to the username
4. Click "Create account"

### What you expected to happen

A notification pop up saying that you can't use the user and password that is the same. And you can insert another one.

### What actually happened

A notification pop up saying that you can't use the user and password that is the same. It's impossible to insert a new one because the form remains disabled.

### Reproducibility

Consistent

**Comment by zaerl** [comment]
If the page is reloaded the form is correctly enabled.

**Comment by zachspears** [comment]
Tested, in my test I did not receive a pop-up whatsoever. Low priority due to low impact and easy work around.

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/69749
