### ISSUE TITLE
[Subscriber Welcome] Subscription dashboard link makes the email wider than it should be

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#67038]
The "Subscription dashboard" link is too wide which makes the email stretch:

![Image](https://user-images.githubusercontent.com/25105483/186902755-e611b1c2-5bc4-4cef-adff-a9cbe41d639a.png)

We may consider changing the way the link is wrapped.

Another thing to consider is to nest the link inside anchor `<a>` - as currently some email clients (e.g. Apple's Mail app) turn the plain text into a link with default blue color that is not the same as the blue color used in the rest of the email.

**Comment by TimBroddin** [comment]
It seems this was fixed already. When inspecting the link <wbr> tags are present. Also a class is color style is applied to the link. I'm closing this for now.

![CleanShot 2022-09-21 at 10 51 03@2x](https://user-images.githubusercontent.com/528287/191461013-05840d7a-417a-4942-9789-fbd77e044c5f.png)
