### ISSUE TITLE
Cultivate: pagination displays as an empty section when there are not further posts

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#67030]
### Quick summary

When we have only 2 posts and pagination is used with the Query Loop block, we'll get an empty section like so:

![wHhR4V.png](https://user-images.githubusercontent.com/6737345/186857677-52821143-5c62-44bb-870c-43e1c4a89c81.png)

### Steps to reproduce

1. Create a couple of posts and add a query block to a page with the pagination block on them.
2. Check the results

### What you expected to happen

To not see the pagination section

### What actually happened

The pagination section appeared as in the screenshot above

### Context

Manual testing

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Cultivate

### Browser, operating system and other notes

Chrome

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
Flagging this for @Automattic/serenity

**Comment by valterlorran** [comment]
Hey! I added a possible fix here: D88111-code

**Comment by valterlorran** [comment]
I created this discussion to understand how to update the sites that already have the theme applied: p1663757176266909-slack-C029FM1EH

**Comment by valterlorran** [comment]
Context: The changes I did will only work for the next time the theme is applied, the ones that already applied the theme before the change will still show the empty container.

**Comment by valterlorran** [comment]
I'm closing this since we fixed the problem for future applications.
