### ISSUE TITLE
Site Switcher: Always display 'Add new site' in Calypso sidebar, and stick to bottom

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#67040]
At the moment, the 'Add new site' button displays in two places:
* Bottom of the sidebar for users with only one site.
* Bottom of the site switcher for users with more than one site.

To make the user experience more consistent, we'd like the 'Add new site' button to _always_ appear at the very bottom of the sidebar:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/36432/186909213-efdb16d9-e493-424f-ad27-94163b5d92bd.png">

Design for the button is a little TBD at the moment.

**Done is:**
* [x] A consistent 'Add new site' button is added to the sidebar for users with one site and users with multiple sites.
* [x] The 'Add new site' button is always sticky at the bottom of the sidebar.
* [x] When the sidebar collapses, the 'Add new site' button appears as a plus icon.
* [x] The button continues to fire the `calypso_add_new_wordpress_click` Tracks event.
* [x] 'Add new site' also appears at the bottom of the Site Switcher.
* [ ] Changes are tested against Jetpack Cloud to ensure no regressions.

**Comment by zaguiini** [comment]
Should the icon at the bottom of the site switcher look like:

![image](https://user-images.githubusercontent.com/26530524/187996027-06664d28-cadc-4ec4-8e8b-bff0441b1a43.png)

or should we stick with the current one?

![image](https://user-images.githubusercontent.com/26530524/187996140-a994c959-3dcc-4974-88e9-a50f255591fe.png)

So:
- in the sidebar: "Add new site" button, outlined;
- in the site switcher "Add new site" button, filled.

Is that right, @danielbachhuber?

**Comment by danielbachhuber** [comment]
@zaguiini The "Add new site" button outside of the Site Switcher should appear like the "Manage [N] Sites" button in the Site Switcher:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/36432/187996666-2ef15137-7ad2-4626-8af4-cdee277ace8c.png">

A more subtle secondary button style.

> So:
> 
>  in the sidebar: "Add new site" button, outlined;
>  in the site switcher "Add new site" button, filled.

This is correct.

**Comment by sejas** [comment]
I've found that in the menu inside wp-admin we are also showing the `Add New Site` button for users with one site:

<img width="260" alt="Screenshot 2022-09-01 at 20 31 59" src="https://user-images.githubusercontent.com/779993/187997159-950d9616-f24d-4b83-b3db-2aa7a4c62b2a.png">

I think for wp-admin we should it as it is right now, like any other button, but we will show it to all the users regardless of the number of sites the user has.

In Calypso we can show it at the bottom as defined in this issue 👌 .

**Comment by danielbachhuber** [comment]
> I think for wp-admin we should it as it is right now, like any other button, but we will show it to all the users regardless of the number of sites the user has.

@sejas Good catch!

I think `/wp-admin/` and Calypso are meant to have consistent designs. What do you think about applying the sticky bottom "Add new site" button design to `/wp-admin/` too?

**Comment by zaguiini** [comment]
>I think /wp-admin/ and Calypso are meant to have consistent designs. What do you think about applying the sticky bottom "Add new site" button design to /wp-admin/ too?

The styles on WP Admin are base WP ones, so does it make sense to use Calypso-like styles in a place that is not Calypso?

**Comment by sejas** [comment]
Yeah, I have mixed feelings.

Sure, we could add the button at the bottom and style it , but should we?

I feel ok about making the change on calypso, but I think we should keep the standard "wp" on wp-admin as much as we can. Just my 2 cents.

**Comment by danielbachhuber** [comment]
> The styles on WP Admin are base WP ones, so does it make sense to use Calypso-like styles in a place that is not Calypso?

We're already applying Calypso-like styles to `/wp-admin/`:

**An Atomic site**

<img width="737" alt="image" src="https://user-images.githubusercontent.com/36432/188003279-f9367427-8a64-4689-93c4-8c1e275a31cc.png">

**The real wp-admin**

<img width="708" alt="image" src="https://user-images.githubusercontent.com/36432/188003172-a35fd0cd-d5f6-4855-8db7-7c5dcf13627e.png">

We actually want to keep the design as consistent as possible between `/wp-admin/` and Calypso...

**Comment by zaguiini** [comment]
@sejas could you please implement the "Add new Site" button inside the site switcher as part of this PR? It makes sense to have it consistently outside and inside the site swticher before merging https://github.com/Automattic/wp-calypso/pull/67295.

**Comment by danielbachhuber** [comment]
@zaguiini I don't think it's necessary to implement the "Add new site" button inside the site switcher on this issue. It's fine if the styles are inconsistent for some short period of time.

**Comment by sejas** [comment]
In order to focus on calypso first, I've created this issue to change the button on wp-admin for atomic and simple sites:
- https://github.com/Automattic/wp-calypso/issues/67323

**Comment by danielbachhuber** [comment]
> In order to focus on calypso first, I've created this issue to change the button on wp-admin for atomic and simple sites:

@sejas Sounds good!

**Comment by sejas** [comment]
@danielbachhuber do you know if making the button sticky to the bottom means to overlap/float it over the rest of the menu, similar to site switcher? or just pushing it at the bottom as you can see in https://github.com/Automattic/wp-calypso/pull/67322

Add new site in Site Switcher:
<img width="250" alt="Screenshot 2022-09-02 at 17 16 13" src="https://user-images.githubusercontent.com/779993/188196026-16cd3a39-75f9-44cd-a5f4-9a1432964db5.png">

**Comment by danielbachhuber** [comment]
> do you know if making the button sticky to the bottom means to overlap/float it over the rest of the menu, similar to site switcher?

@sejas Let's assume "overlap/float it over the rest of the menu" for now, yes. The goals are "more consistent UX with site switcher" and "more prominent overall", so I think this description better addresses the goal.

**Comment by sejas** [comment]
Sounds perfect, thanks Daniel! 👍

**Comment by sejas** [comment]
@danielbachhuber, in the end, I've decided not to show the Add new site button floating over the rest of the menu.
I've found that it requires a big refactor on the Sidebar and changing the current Sidebar design/behaviour.

You can take a look at the current PR here: https://github.com/Automattic/wp-calypso/pull/67322

**Comment by danielbachhuber** [comment]
> in the end, I've decided not to show the Add new site button floating over the rest of the menu.
> I've found that it requires a big refactor on the Sidebar and changing the current Sidebar design/behaviour.

Sounds good!

**Comment by sejas** [comment]
As discussed here: p1662676582363559-slack-C0347E545HR
We've decided to:
- Stick the button to the bottom of the sidebar
- Use the new button design, the same used on Site Switcher
-  Keep showing it for users with only one site
