### ISSUE TITLE
Site Switcher: Move 'Manage [N] Sites' button to bottom of the UI, add conditional 'View [feature] for sites' button

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#67041]
After #66804 lands, we'd like to add a 'Manage Sites' button to the bottom of the Site Switcher UI.

![image](https://user-images.githubusercontent.com/36432/186911432-bb62c0fe-ec31-468d-a898-ec98620c7966.png)

The number should reflect the user's total number of sites.

Design for the button is a little TBD at the moment.

Next, the existing 'All my sites' button in the Site Switcher is a little erratic: sometimes it takes you to a list of all your sites, and other times it takes you the multi-site view relating to the feature you're looking at (e.g. stats). We'd like to instead change the existing 'All my sites' button to a 'View [feature] for sites' button that only appears when a given view has a multi-site context:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/36432/186913206-7f5231d5-1d7b-4845-a748-446bde17b870.png">

**Done is:**
* [x] A new 'Manage [N] Sites' button appears at the bottom of the Site Switcher UI.
* [ ] The count in the button reflects the user's total number of sites.
* [x] The button links to the new Sites page (`/sites`).
* [x] The button triggers a Tracks event when clicked.
* [x] The existing 'All my sites' UI element is removed.
* [x] A 'View [feature] for sites' button appears when a given view has a multi-site context.
* [ ] The 'Add new site' button is styled as depicted (without dropdown, though).
* [ ] Changes are tested against Jetpack Cloud to ensure no regressions.

**Comment by zaguiini** [comment]
>button that only appears when a given view has a multi-site context

~Do we have any kind of list or flag for those cases?~

EDIT: Here is a list of the pages that have an all-sites version: https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/sidebar/static-data/all-sites-menu.js.
