### ISSUE TITLE
Kerr: Button block hover text shows correctly in editor, blank or too light on live page

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#67048]
### Quick summary

- WP Button block, fill setting. Hover over button, background goes white, outline correct, text switches to outline color.
- Live page, hover over button, background goes light, outline correct, text is white or light, unreadable.
edit view:
<img width="876" alt="Markup 2022-08-26 at 10 09 13" src="https://user-images.githubusercontent.com/8058729/186926398-1829b67e-7b84-467c-9dbb-55e31f3dfda7.png">
live page view:
<img width="706" alt="Markup 2022-08-26 at 10 10 55" src="https://user-images.githubusercontent.com/8058729/186926447-be38b5b9-a2ad-40d0-bd39-6f46d2ed805c.png">

### Steps to reproduce

1. test site, switched theme to Kerr.
2. added buttons on page.
3. update page, review buttons on live view.

### What you expected to happen

button text should switch to outline color on hover, background switches to light color.

### What actually happened

button background goes light, text stays light making it unreadable/difficult to read.

### Context

Business AT test site, switched to Kerr theme. Added button, tested edit view and live.
Also tested on Business simple site. Works correctly.

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Kerr, Zoologist

### Browser, operating system and other notes

Firefox, Mac OS 12.5.1

### Reproducibility

Consistent

**Comment by radtechgh** [comment]
initial site: 5509309-zen

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - no

📌 FINDINGS/SCREENSHOTS/VIDEO
- This has been inconsistent for me, however, as it involves Kerr, I'm highlighting this to @Automattic/serenity 

cc @pbking if you can double check as it's Blockbase related.

📌 ACTIONS
- Marked as Triaged for Serenity

**Comment by andres-blanco** [comment]
I've created a site on AT using the Kerr theme and there is no hover effect over buttons. This doesn't seem to be an issue anymore.
