### ISSUE TITLE
Notifications: User receiving new post notifications from a blog to which they are not subscribed.

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#67067]
### Quick summary

A user is receiving new post notifications from a blog to which they are not subscribed.

### Steps to reproduce

Not reproducible on a test site. I'm creating this bug report as part of ongoing nudges to get more eyes on it.

See: p1661413514518259-slack-C02HLU2CH

### What you expected to happen

Users should not be receiving notifications relating to blogs they are not subscribed to/

### What actually happened

The user is receiving new post notifications from a blog to which they are not subscribed.

### Context

5505659-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

**Comment by Greatdane** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I don't think this is a bug. See; p1661412010881009-slack-C03TY6J1A

📌 ACTIONS
- Await author feedback
- Closed as could not replicate (please reopen the issue reoccurs)
