### ISSUE TITLE
German importer info/support doc modal links to broken link for `support-article=41`

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#67068]
### Quick summary

The DE import info/support modal opens a broken support link for support-article=41.

### Steps to reproduce

1. Create/open a site set to the DE locale.
2. Access https://wordpress.com/import/yourgroovydomain.blog
3. Click the `Weitere Informationen` to trigger the support doc modal.
4. Click `Artikel öffnen` to be taken to https://wordpress.com/importieren/.

### What you expected to happen

The link for this button should be:
https://wordpress.com/de/support/importieren/

### What actually happened

This button redirects to:
https://wordpress.com/importieren/

The `Weitere Informationen` link point to:
https://wordpress.com/de/support/import/

Both should redirect to:
https://wordpress.com/de/support/importieren/

### Context
![Import support link broken](https://user-images.githubusercontent.com/66711744/187060188-ec89d98d-c2f2-4d25-8153-b270c3594a9d.png)

5496733-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

DE locale

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: Could Not Replicate
- Tested on AT: Could Not Replicate
- Replicable on Core?  No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Looks like this may have been fixed! I'm seeing the `Artikel öffnen` button direct to `https://wordpress.com/de/support/import/` on both Simple and AT sites


*Example*
![Markup on 2022-08-31 at 19:41:57](https://user-images.githubusercontent.com/27249804/187820903-0eae691c-402d-4f2d-8ed3-1344f0d1f38a.png)


📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @inaikem I wasn't able to replicate this, so thinking it may have been caught already! Feel free to reopen if you're still able to replicate or the issue recurs. Thanks!
