### ISSUE TITLE
Pattern Assembler: Improve performance of pattern/site preview endpoints

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#67079]
Can we optimize existing endpoints `block-previews/pattern` and `block-previews/site` for the PA project? The reason is that PA does not require:

- to verticalize patterns or sites
- to add styles or scripts based on the theme (always use `Blank canvas`)
- to generate HTML with content for a source based on the theme (always is `dotcompatterns`)

**Other optimizations**
- The HTML of each pattern is always the same so that the response can be pre-cached.
- Any other possible improvements?

Related #67076

**Comment by autumnfjeld** [comment]
@Automattic/ganon   This is how @fushar  :)

**Comment by fushar** [comment]
Now that I just played around with the feature, I (subjectively) feel that the current performance is good enough. I suggest before taking any action on this issue, let's wait for the CfT and see if people will find that the feature is slow.

**Comment by fushar** [comment]
@miksansegundo can we close or conclude this issue now? 😄 I think we should link to the past PRs / diffs that contribute to this endpoint's performance improvements.

**Comment by miksansegundo** [comment]
We did these improvements:
- D90635-code
- D91400-code
