### ISSUE TITLE
Theme Support: Automate Deploy Prep Steps for Merged Theme

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#67096]
As part of our efforts to [introduce automation into the theme support process](https://github.com/Automattic/wp-calypso/issues/66581), we should create an automated script for the preparation steps prior to deployment after a theme has been merged into WPCOM. These steps include:

* Building the ZIP file
* Adding the theme as a product to the Store
* Creating a diff like this: D86011-code (more information pdgA0m-90-p2)
* Adding the theme to the prices page in MC

**Comment by sixhours** [comment]
Unlikely to prioritize this in the next year; closing.
