### ISSUE TITLE
Theme Support: Automate theme deployment steps

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#67097]
As part of our efforts to [introduce automation into the theme support process](https://github.com/Automattic/wp-calypso/issues/66581), we should automate the steps required to deploy a theme to the public. (These should follow on from the work done in https://github.com/Automattic/wp-calypso/issues/67096 )

These steps include:
* Network activating the theme
* Publishing the theme showcase page
* Creating a diff to remove the theme from the soft launch list

**Comment by sixhours** [comment]
We're unlikely to prioritize this within the next year; closing.
