### ISSUE TITLE
Reduxify: Migrate Signup

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#6709]
#### Master Thread: Reduxify Signup

---

The Signup was written with `localStorage`, Flux and stores concept in mind. The progress of the signup and data that is passed between each step is saved in one of two data stores:
- `SignupProgressStore` - holds the progress of the Signup (what steps have been finished) and some information about the step (so the signup can be restored from a closed session).
- `SignupDependencyStore` - holds data that will be passed between the steps (`dependencies` and `providesDependencies` which are defined in the `/client/signup/config/steps.js`)

Both stores rely on `localStorage` to store data. In order to improve that and have more consistent code with the other parts of Calypso they should be migrated to Redux, as this is the way we are moving forward with data storage.
#### Why `Signup<something>Store` in Redux and not just reducers?

To properly migrate to Redux, both stores should be deprecated, which means all steps in Signup have to be updated to work with Redux directly and not rely on the underlying stores. This would take a lot of time to implement, test properly and put into production.
If this is done in one go, it would mean that we will be pushing a completely (or at least a huge part of it) rewritten Signup component.

There are way too many places this will fail.

A better way to handle it is to migrate the Signup process in small increments, which can live independently of each other. This way we can migrate parts of the process without breaking the rest of it. 

What we are going with is to do the migration in the following steps:
- [x] Migrate the `SignupDependencyStore` to Redux ( #6124, #25510 )
- [x] Migrate the `SignupProgressStore` to Redux ( #25606, #25645, #25893 )
- [ ] Remove dependency on `Flux` and its `Dispatcher` ( _TBD_ )
- [ ] Migrate the signup steps to use the Redux state (basically remove `SignupDependencyStore` and `SignupProgressStore`) ( _TBD_ )

At the end of this process, there will be no remains of `localStorage` and "stores".

cc @michaeldcain @coreh

**Comment by jsnajdr** [comment]
Fixed in #32982.
