### ISSUE TITLE
Theme Support: Automate diff creation and generating Headstart annotation for new theme

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#67093]
As part of our efforts to [introduce automation into the theme support process](https://github.com/Automattic/wp-calypso/issues/66581), we should update the `premium-theme-tools` repo script to include automation for generating the diff that patches the theme files to GitHub to wpcom. This automation should also include automatic generation of the theme's Headstart file. We should also create a (probably separate) command to automate soft-launching the theme once its diff is merged.

**Comment by markbiek** [comment]
This was done as part of PR2 in the premium-theme-tools repo.
