### ISSUE TITLE
Misaligned labels in the post list view [Staging]

### ISSUE THREAD

**Issue by bartoszbak** [Automattic/wp-calypso#67104]
### Quick summary

Labels in the post list view are misaligned - staging environment 

![CleanShot 2022-08-29 at 15 15 07@2x](https://user-images.githubusercontent.com/12172350/187210019-21728111-fd2b-4a38-9c73-eddbbfdfa646.jpg)

### Steps to reproduce

1. Open https://wordpress.com/home/dotcom.wordpress.com - or any site within wordpress.com as A12s
2. Open Posts on the left sidebar
3. Look at the list view with posts
4. On the lists, labels located under the post title are misaligned 

### What you expected to happen

I expect all the labels aligned horizontally

### What actually happened

Labels under the post title are not aligned horizontally making it look clunky 

### Browser, operating system and other notes

Mac OS, 12.5 
Chrome Version 104.0.5112.101 (Official Build) (arm64)

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

**Comment by danielbachhuber** [comment]
Looks like this is still slightly off:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/36432/202583817-06bdcfcf-380d-4e0c-9578-01f4f5029118.png">

Unfortunately, it's two separate elements 😔

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/36432/202583911-2194269e-b574-4fb6-9101-2893af06630a.png">

Maybe we can combine them?
