### ISSUE TITLE
Theme/Plugin Bundling: Display different UpgradeModal depending on the theme

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#67120]
When unlocking a premium theme from the `designSetup` step, we need to display a slightly different upgrade modal depending on if the theme has bundled plugins.

For a _non-bundled_ theme, we can display the current upgrade modal which lets them make a one-off purchase of the theme.

![image](https://user-images.githubusercontent.com/917632/187249938-f868dc7c-e12d-4313-9dad-2e0be8f57fbc.png)

For a theme with bundled plugins, we need to display the "Upgrade Plan" modal instead.

![image](https://user-images.githubusercontent.com/917632/187250034-5f436884-5b1d-4285-8924-fdd3eb51223c.png)

**NOTE:**

- We need to say "Business plan" instead of "pro plan"
- I think we're safe to hard-code the modal to be WooCommerce-specific for now.

**Comment by nelsonec87** [comment]
The "Upgrade Plan" modal was added in this PR https://github.com/Automattic/wp-calypso/pull/67244.
There are other things to work on regarding these modals:
- When clicking on "Premium theme" link or "Upgrade plan" button, populate the cart with the right product.
- Clicking on "Buy and activate theme" it should add the theme to the cart, not the plan.

**Comment by nelsonec87** [comment]
Also, as @mreishus wrote here https://github.com/Automattic/wp-calypso/pull/67244#pullrequestreview-1094053826 :


---

I think a good follow up is to check when the upgrade modal is displaying.
For example, the Premium plan gives access to unlimited premium themes, but it does not give access to the woop feature (or the atomic feature). If I have the premium plan and select a premium theme with woo bundled, I believe it will let me use the theme, and will not prompt to upgrade to business.
https://github.com/Automattic/wp-calypso/blob/259cbafefc7060ea189d65e6a8f964024839b8a3/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/site-setup-design-picker.tsx#L399-L400

---

Another followup could be to make this trigger only if the correct softwareset is present, so a software set of ['woo-on-plans'] would trigger the new modal, but ['some-other-thing'] would not.

**Comment by mreishus** [comment]
Mark added a hook use-is-plugin-bundle-eligible.ts in #67329. An additional condition for needing upgrade would be `|| ( <it's a bundled theme> && ! isPluginBundleEligible )`.
Although there are now two different kinds of needsUpgrade; needs upgrade to access premium themes, needs upgrade to access woop+atomic. Not sure if that has any implications.

**Comment by markbiek** [comment]
@nelsonec87 I just merged #67329 so you'll have access to that hook once you rebase `trunk`.
