### ISSUE TITLE
Theme/Plugin Bundling: From the theme showcase, allow plan upgrades for bundled themes

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#67121]
Similar to #67120, we need to provide two different purchase flows from the Theme Showcase.

For a non-bundled theme, we'll continue to display "Purchase" so the user can buy the theme as a on-off purchase.

![image](https://user-images.githubusercontent.com/917632/187250673-d3cc36ec-55f3-4004-b0e8-db399e135f24.png)

![image](https://user-images.githubusercontent.com/917632/187250749-68ed2aba-520b-4fb6-af56-84f86e97f63d.png)

For a theme with bundled plugins, the info popup should display "Upgrade plan" instead of "Purchase". The "Pick this design $nn" button on the individual theme page should display "Upgrade plan" instead.

Clicking "Upgrade" from either the info popup or the theme page should take the user to checkout for purchasing the "Business plan".

**Comment by mreishus** [comment]
This should be solved with #67131. To see the new behavior, the `themes/plugin-bundling` flag needs to be on and the selected theme needs to have a `theme_software_set` in its taxonomy.
