### ISSUE TITLE
Do not show theme variations

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#67137]
# Description

We won't want to show all the TT2 variations, or any theme variations in the theme grid, since that is now handled by Style Selection.

# A/C
Theme grid should have only ONE TT2, only ONE podcast for women, etc....
![Image](https://user-images.githubusercontent.com/5665959/187318390-32355802-ad5d-4f72-9fdb-6c12d04d823a.png)

**Comment by fushar** [comment]
Landed!
