### ISSUE TITLE
Change "Email list importing" message to "Your email list is being uploaded."

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#67149]
See: pdtkmj-pL-p2#:~:text=We%20probably%20need%20to%20update%20the%20wording%20a%20bit%20from%20%E2%80%9CYou%20have%20email%20list%20importing%E2%80%A6%E2%80%9D%20to%20something%20like%2C%20%E2%80%9CWe%20are%20importing%20your%20subscribers%E2%80%A6%E2%80%9D.

**Comment by simison** [comment]
While we don't have the CSV importing/uploading public for launch, we should probably find another copy with designers.

Something along the lines of "Your subscribers have been added"?
