### ISSUE TITLE
[Bug]: Blank pages when token has expired

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#67145]
### Quick summary

Some URLs show a black page when the user token is expired.

### Steps to reproduce

1. Get an expired token
2. Visit any calypso page that calls `https://public-api.wordpress.com/rest/v1.1/me/settings`

When a token is expired the backend output:
```json
{
	"code": 401,
	"headers": [{
		"name": "Content-Type",
		"value": "application\/json"
	}],
	"body": {
		"error": "reauthorization_required",
		"message": "A fresh access token must be used to query information about the current user."
	}
}
```

### What you expected to happen

Show the verification code modal like what happens in `/me` or maybe redirect to that page.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/167611/187366353-ae2f350d-a363-40bd-ad00-876e9fcd5f09.png">

### What actually happened

The page main div (id="content") is blank.

### Other notes

The site is a wpcom one.

### Reproducibility

Intermittent

**Comment by Greatdane** [comment]
As discussed on Slack (p1662610324398489/1662610137.992159-slack-C01UW7SB411), moving on without usual triage.

**Comment by youbrokesomething** [comment]
@zaerl Is this a bug that Caribou will take on?

**Comment by zaerl** [comment]
Hi @youbrokesomething. No we will not. I've opened this bug report but it's not related to us.

**Comment by youbrokesomething** [comment]
@zaerl Okay! I'll see if I can find a team for it. Thank you!

**Comment by renancarvalho** [comment]
Since @zaerl and me cannot reproduce it anymore, we think is a good idea to close it.
