### ISSUE TITLE
Plans: Mobile design tweaks

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#6714]
This is a more basic way to show plans on mobile. We would also look at working on swiping full cards on mobile once we have this launched.

![mobile-plans](https://cloud.githubusercontent.com/assets/1464705/16774947/0dd46994-4813-11e6-9e74-46fb250226ac.png)

**Comment by apeatling** [comment]
Yep definitely.

**Comment by gwwar** [comment]
Here's a rough sketch of how the feature expansion behaves
![expand](https://cloud.githubusercontent.com/assets/1270189/16777469/8d191ca8-481e-11e6-96ef-731cc9035823.gif)

**Comment by rickybanister** [comment]
Can't we just use the standard left-aligned card title for 'show included features?' Can you click on the text itself?—it'd be nice if you could click anywhere in the collapsible card to expand it I think.

**Comment by gwwar** [comment]
Oh you're right @rickybanister, I must have been using the wrong prop. 
<img width="536" alt="screen shot 2016-07-12 at 11 05 25 am" src="https://cloud.githubusercontent.com/assets/1270189/16777938/949e5f18-4820-11e6-90a4-300d371495f8.png">

**Comment by gwwar** [comment]
Updated to look like:
![expand](https://cloud.githubusercontent.com/assets/1270189/16778098/3b6ffe00-4821-11e6-942c-80de0ba2b402.gif)

**Comment by rickybanister** [comment]
That looks great!
