### ISSUE TITLE
Twenty Twenty: Video embeds are not center aligned

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#67159]
### Quick summary

Embedded videos (tested with YouTube, Vimeo, and Video blocks) on the _Twenty Twenty_ theme do not respect the `Align center` setting, and are also not centered for the `None` or `Wide width` alignment settings.

### Steps to reproduce

1. Activate the _Twenty Twenty_ theme.
2. Create a new post or page and insert a video. Tested with the Youtube, Vimeo, and Video blocks. 
3. Select an alignment option: either `None`, `Align center`, or `Wide width`.
4. Preview/view the post or page.

### What you expected to happen

The video should be centered on the page.

### What actually happened

The video is aligned to the far left instead:

![ZMaBmh.png](https://user-images.githubusercontent.com/5630717/187461325-faab4b13-21b3-4912-affc-9ee54c079d59.png)

### Context

5517970-zd-woothemes

It looks like the primary issue is this inline CSS (which is overriding the `auto` left/right margins from `.aligncenter`):

```
.wp-block-embed {
   margin: 0 0 1em 0;
}
```

I suspect this would impact other embed-type blocks as well.

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Identified on _Twenty Twenty_. Unable to replicate on _Twenty Twenty One_ or _Twenty Twenty-Two_.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Adding the affected video into a Group block (using the `Group` option in the triple-dot hovering toolbar menu) seems to be a viable workaround.

**Comment by zachspears** [comment]
Hey, @jp-imagines I have tested this, and I am unable to reproduce it. Are you still seeing this issue? Thanks!

**Comment by jp-imagines** [comment]
@zachspears I'm still able to reproduce on my test site: sd1dH7-140-p2 (Atomic site, _Twenty Twenty_ theme, video-type blocks on a post with either `none` or `align center` alignment setting).

**Comment by jp-imagines** [comment]
By sheer coincidence, I ran into another existing report for this same issue: https://github.com/Automattic/themes/issues/6198

Confirmed on my test site that disabling _Page Optimize_ does resolve this, so it seems that's what's causing the conflict.

Closing this report in favor of the older one.
