### ISSUE TITLE
Header and Footer not displaying on default templates

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/wp-calypso#67167]
### Quick summary

On several sites using FSE themes, the header and footer is suddenly not displaying correctly on default page template. 

For example, the default page and single post template are suddenly not displaying header and footer. The header and footer both show correctly for the template in the Site Editor but the header and footer both fail to display on the live site. 

Example of what I see in the Site Editor for the **Page** template: 

https://user-images.githubusercontent.com/77413972/187490693-85401bf5-621a-4381-bdb8-2f00293bbc51.mp4

What is seen on the live site: 

https://user-images.githubusercontent.com/77413972/187490594-975aeca0-a6e0-4036-bae2-dc358e329fbd.mp4

This appears to be a large bug affecting many FSE sites. 

### Steps to reproduce

1. Edit site using FSE theme via the Site Editor
2. Edit the default page template - confirm header and footer are added
3. Visit live site and you will see that pages using the default page template do not load the header and footer

### What you expected to happen

I expected header and footer added via the Site Editor to display on the live site. 

### What actually happened

Header and footer added via Site Editor do not load on the live site. 

### Context

Customer reported: 5518641-zen

### Platform (Simple, Atomic, or both?)

Seems to only be present on Simple sites. 

### Theme-specific issue?

Unknown if this bug is present on all FSE themes. Unable to duplicate on my test site but have seen several customers with this bug today. 

### Severity

Urgent - large bug affecting lots of users

**Comment by msilbers** [comment]
- [ ] 5518839-zen
- [ ] 5518838-zen

**Comment by sharonlaker19** [comment]
- [ ] 5518207-zen

**Comment by mreishus** [comment]
Caused by D86821-code. Left some investigation notes inside that issue.

**Comment by wiesenhauss** [comment]
- [ ] 5518084-zen

**Comment by JoshuaGoode** [comment]
* p1661876487676969-slack-C02FMH4G8 
* D86821-code

**Comment by mreishus** [comment]
We've pushed a revert in D86868-code which may address the issue.

**Comment by wpshellbelle** [comment]
> We've pushed a revert in D86868-code which may address the issue.

@mreishus This looks to have resolved this issue! I am seeing that the header and footer are loading correctly on the live site now.

**Comment by dev-sabbir** [comment]
This one was reported yesterday: 5518741-zd-woothemes

The issue seems to be fixed for them now. I am adding this comment here to keep track.

**Comment by tvolpert** [comment]
I have a user here that appears to still be experiencing the issue: 

- [ ] 48357-hc

**Comment by zachspears** [comment]
Unable to reproduce it, but still seeing this issue on here: 48357-hc . Low priority due to most sites are reporting the issue solved.

**Comment by JoshuaGoode** [comment]
These are likely unrelated issues @tvolpert @zachspears -- as this Github issue should be closed and users updated.
