### ISSUE TITLE
READER - Card Refresh: Updates to search screen

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#67168]
## Description

We're in the process of updating the look and feel of our Calypso Reader Cards. As a part of this, we'd like to update the design of the search screen.

### Before

<img width="1160" alt="CleanShot 2022-08-30 at 12 39 17@2x" src="https://user-images.githubusercontent.com/5634774/187492580-c9e5d19a-0bcc-426c-9b42-a7acfb4e9254.png">

<img width="1152" alt="CleanShot 2022-08-30 at 12 40 30@2x" src="https://user-images.githubusercontent.com/5634774/187492676-ded79955-d94a-41a4-a451-266a2aded348.png">

### After

<img width="575" alt="CleanShot 2022-08-30 at 12 40 58@2x" src="https://user-images.githubusercontent.com/5634774/187492744-481577fe-a25a-4882-bc9a-0ad8ca5d5812.png">

<img width="579" alt="CleanShot 2022-08-30 at 12 41 18@2x" src="https://user-images.githubusercontent.com/5634774/187492848-757ccad8-6115-40ef-b2a1-c57e7eae0734.png">

<img width="581" alt="CleanShot 2022-08-30 at 12 41 46@2x" src="https://user-images.githubusercontent.com/5634774/187492933-32bc7007-7bfb-4456-b5a1-8b3b85e8e3d1.png">

## Checklist

- [ ] Minor updates to search bar CSS
- [ ] Remove "POSTS" column header in left column
- [ ] Update column header styles in right column
- [ ] Remove 50/50% column view (instead, default to cards on left, recommended sites column on right)
- [ ] Add dropdown in search field for relevance and date filter options

**Comment by ebinnion** [comment]
Project thread for v1 is here: https://loopp2.wordpress.com/2023/04/18/project-thread-reader-search-refresh-v1/

**Comment by ebinnion** [comment]
Project thread: pe7F0s-Le-p2
