### ISSUE TITLE
Reader Card Refresh: Update header of followed site screen

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#67166]
## Description

We're in the process of updating the look and feel of our Calypso Reader Cards. As a part of this, we'd like to update the header of the followed site screen.

### Before

<img width="1156" alt="CleanShot 2022-08-30 at 12 26 59@2x" src="https://user-images.githubusercontent.com/5634774/187490429-4042ccc1-75e0-472c-9d8e-5fe6e6876a35.png">

### After

<img width="579" alt="CleanShot 2022-08-30 at 12 33 39@2x" src="https://user-images.githubusercontent.com/5634774/187491474-536a9d50-feca-4556-9718-4b86c0574ab5.png">

## Checklist

- [x] Increase font size of site name and add serif font
- [x] Move number of followers, settings link, and follow link below site name
- [x] Adjust margins/padding accordingly

**Comment by jordesign** [comment]
Howdy folks - I've started a PR to try and help out here - It's possible a little rough ;)

I've got the layout and font sizes sorted - just a couple of outstanding questions about font sizes and icons.
https://github.com/Automattic/wp-calypso/pull/67192#issuecomment-1232547410

**Comment by davemart-in** [comment]
@jordesign exciting! Thanks for jumping in! I'll take a look at this later today and leave my thoughts on your PR.

**Comment by davemart-in** [comment]
Closed out with #67192
