### ISSUE TITLE
Marketplace: Category Description (labels)

### ISSUE THREAD

**Issue by vinimotaa** [Automattic/wp-calypso#67171]
I'm creating this ticket for us to centralize, align and keep updating the Category descriptions (labels) as we get them.

**These are the ones we already have:**

Ecommerce & Business
Everything you need to turn your WordPress site into a powerful online store.

Booking & Scheduling
_Add a fully functional booking system to your site._

Analytics
_Tools to help you better understand your site's visitors and performance._

Design
_A collection of tools that will give you more control over the design of your site._

**We still need a description for these:**

Search Engine Optimization
Events Calendar
Social
Email
Security
Finance & Payments
Shipping & Delivery
Marketing
Photo & Video
CRM & Live Chat
Crowdfunding
Learning Management Systems
Widgets
Posts & Posting

@michaelpick any suggestions on these other categories? Another thing to consider is how to keep them consistent with each other.

Some initial descriptions that came from @SaxonF some time ago; https://github.com/Automattic/wp-calypso/issues/64055#issuecomment-1140626607

**Comment by michaelpick** [comment]
@vinimotaa – sure! I'll work up a few options and aim to bring some consistency to the approach. I'll aim to drop those here on Monday if not sooner.

**Comment by vinimotaa** [comment]
Thanks a lot @michaelpick!

**Comment by michaelpick** [comment]
Hey @vinimotaa 👋 

I took a look at these and the related titles and labels in #65574. 

To help us get to the consistency you mentioned, I came up with two different patterns that could be pretty easily captured in a light-weight Marketplace styleguide:

## Pattern 1: Action-oriented; `why > what > how` pattern
In this variation the subheadings run a little longer, the better to lead with an action-focused 'why' (I should care) and 'what' (it is), before pivoting into an explicit 'how' (it works). The benefit here is additional context – I am given:

- An outcome
- Features and benefits related to that outcome
- A concrete set of actions supporting that outcome. 

This is at the expense of brevity.

The pattern goes like this:

`{Outcome focused verb}` `{feature and benefit}` by `{gerund (-ing)}` `{concrete actions}`

An illustrative example:
'Learn the piano and impress your friends by following these bite-sized interactive lessons.'

### Applied to the subheadings

**Ecommerce & Business**
Turn your site into a store by adding powerful, flexible ecommerce features.

**Booking & Scheduling** {{Note: research suggests it's better to use 'and' than ampersand for readability}}
Turn site visitors into customers by adding advanced bookings and schedule management tools to your site.

**Analytics**
Understand what's working and what isn't by digging deep into site visitor and performance insights.

**Design**
Finesse every detail of your site's design by adding advanced customization tools to your site.

**Search Engine Optimization**
Increase and maintain search visibility for your site by optimizing your metadata and content

**Events Calendar**
Build buzz and attention by displaying and managing an events calendar on your site.
((Note: is this the intended purpose, or is it more of an internal calendar?))

**Social**
Amplify the visibility of your content by connecting to your audience across social platforms.

**Email**
Build a direct connection to your site visitors by capturing, integrating, and managing your email list.
((Note: is this the full scope of email plugins?))

**Security**
Get added peace of mind by enhancing your site's security features.

**Finance & Payments**
Make collecting, managing, and reporting on payments a breeze by adding these seamless tools and integrations.

**Shipping & Delivery** {{See previous note about ampersands. Better to use 'and'}}
Create a seamless ordering experience for your customers by integrating and managing product shipping and delivery.

**Marketing**
Make your site or business stand out by amplifying the reach and visibility of your projects and products.

**Photo & Video** {{Ampersand warning}}
Elevate your site's visuals by creating, editing, and managing video and images with precision and flexibility.

**CRM & Live Chat**
Build and maintain stronger relationships with your customers by putting advanced customer service tools to work for your business.

**Crowdfunding**
Raise funding for your product, cause, or project by integrating crowdfunding tools directly into your site.

**Learning Management Systems**
Teach, track, and promote courses and educational content by seamlessly integrating LMS tools into your site. 

**Widgets**
Take deeper control of your site's widgets by putting advanced customization and integrations to work.

**Posts & Posting**
Take your publishing goals further by using advanced post content, planning, and scheduling tools.

---

Note: overall, I find this pattern a little bloated and somewhat awkward in some situations, but I'm open to being wrong. My gut says that the second pattern strikes a better balance. See what you think!


## Pattern 2: Action-oriented, condensed `what/why` pattern

In this variation – my preference – our supporting subheads aim for a balance of:
- Concision 
- Clarity
- Leading with a concrete outcome which absorbs some of the 'how' of pattern 1
- Merges feature and benefit within

This gives us greater concision and readability at the expense of a more explicit 'how'

The pattern:
`{Outcome focused verb}` `{condensed feature/benefit/action}`

Example:
Bake an amazing cake for your chocolate-obsessed family

### Applied to the subheadings

**Ecommerce & Business**
Turn your site into a powerful online store.

((Style note: I don't think we need to explicitly call out WordPress or WordPress.com except where it makes a critical difference, such as 'Recommended by the WordPress.com team'. Thus, 'your site' replaces 'Your WordPress.com site'}}

**Booking & Scheduling** {{Note: research suggests it's better to use 'and' than ampersand for readability}}
Take bookings and manage your availability right from your site.

**Analytics**
Go deeper and learn faster with site visitor and performance insights.

**Design**
Finesse {{every detail of)) your site's design with advanced customization tools.

**Search Engine Optimization**
 Fine-tune your site's content and metadata for search engine success.

**Events Calendar**
Build buzz and set the scene with an on-site events calendar.
((Note: is this the intended purpose, or is it more of an internal calendar?))

**Social**
Connect to your audience and amplify your content on social.

**Email**
Forge a direct connection with your readers through email.
((Note: is this the full scope of email plugins?))

**Security**
Take advanced control of your site's security.
 
**Finance & Payments**
- Sell products, subscriptions, and services while keeping on top of every transaction.
- ALT: Collect payments and keep on top of every transaction with advanced payment integrations.

**Shipping & Delivery** {{See previous note about ampersands. Better to use 'and'}}
Create a seamless shipping experience with advanced delivery integrations.

**Marketing**
- Bring in new business and shine a spotlight on your projects or products.
- ALT: Amplify the reach and visibility of your site or business.

**Photo & Video** {{Ampersand warning}}
Create, share, edit, and manage beautiful images and video {with added precision and flexibility.}

**CRM & Live Chat**
- Create stand-out customer service experiences for your site visitors.
-  ALT: Take customer service and connection to the next level.
- ALT: Build deeper relationships with your customers.

**Crowdfunding**
 Launch and run crowdfunding campaigns right from your site.

**Learning Management Systems**
Create, run, and manage interactive courses and learning experiences.

**Widgets**
Take widgets to the next level with advanced control and customization.

**Posts & Posting**
Unlock advanced content planning, publishing, and scheduling features.

---

Happy to iterate on either pattern or propose alternatives.

I'll write up a few quick style inconsistencies and potential solutions in a separate comment.

**Comment by michaelpick** [comment]
# A few quick style notes

## Title vs. sentence casing
We aren't consistently applying casing to headings and subheadings across the page. While it's open to being evolved, our style guide [recommends](https://dotcombrand.wordpress.com/style/#:~:text=For%20headings%2C%20buttons%2C%20and%20text%20in%20general%2C%20we%20use%20sentence%20case.) the use of sentence casing for headings. Sentence case increases readability [according to research](https://readabilityguidelines.co.uk/grammar-points/capital-letters/#2-use-sentence-case-in-headlines-and-subheads), so I reckon we should implement this here unless there are any strong objections.

## Ampersands and readability
There are also a number of [readability advantages](https://readabilityguidelines.co.uk/grammar-points/ampersands/) to using 'and' rather than an ampersand. I'd recommend that we replace the 'X & Y' titles to 'X and Y'

## On the use of WordPress and WordPress.com in explanatory copy
We quite often drop extraneous 'WordPress' and 'WordPress.com' references into explanatory sentences. We should only really do this where there's a strong case for it, i.e.:
- Disambiguation between a WordPress.com plugin or feature and a WordPress-at-large plugin or feature
- Disambiguation between WordPress and another platform, site builder, CRM etc.
- Where we are explicitly calling out the WordPress.com team or product for a reason (e.g. 'Top picks from the WordPress.com team' is a lot clearer than 'Top picks from the team'
- Where there are specific SEO reasons to sprinkle in WordPress.com or WordPress references in relation to a particular product. Even then, with Google's skew towards meaningful, helpful, high-quality content this may not be advisable if unjustified in the contest of a sentence

In other cases, we can achieve better concision and clarity – and avoid sounding too self-congratulatory – by cutting the superfluous reference. For example:

'Turn your WordPress.com site into a powerful store' could more concisely be expressed as 'Turn your site into a powerful store', with the fact that the user is on a WordPress.com page, reading about WordPress.com features, in a marketplace where they can only purchase plugins to use with WordPress.com somewhat filling in the blanks for us.

**Comment by michaelpick** [comment]
# Bringing the above together into recommended copy

I've combined the above style notes with my personal favorite lines. Totally happy to use any of the others, or to iterate on any that don't quite hit the mark. I've also commented a couple for clarification of scope.

## Ecommerce and business
Turn your site into a powerful online store.

## Booking and scheduling
Take bookings and manage your availability right from your site.

## Analytics
Go deeper and learn faster with site visitor and performance insights.

## Design
Finesse your site's design with advanced customization tools.

## Search engine optimization (SEO)
Fine-tune your site's content and metadata for search engine success.

## Events calendar
Build buzz and set the scene with an on-site events calendar.
((Note: is this the intended purpose, or is it more of an internal calendar? This also feels like a slightly uncannily specific category, maybe?))

## Social
Connect to your audience and amplify your content on social.

## Email
Forge a direct connection with your readers through email.
((Note: is this the full scope of email plugins?))

## Security
Take advanced control of your site's security.

## Finance and payments
Sell products, subscriptions, and services while keeping on top of every transaction.

## Shipping and delivery
Create a seamless shipping experience with advanced delivery integrations.

## Marketing
Bring in new business and shine a spotlight on your projects or products.

## Photo and video
Create, share, edit, and manage beautiful images and video {with added precision and flexibility.}

## CRM and live chat
Create stand-out customer service experiences for your site visitors.

## Crowdfunding
Launch and run crowdfunding campaigns right from your site.

## Learning management systems (LMS)
Create, run, and manage interactive courses and learning experiences.

## Widgets
Take widgets to the next level with advanced control and customization.

## Posts & Posting
Unlock advanced content planning, publishing, and scheduling features.

**Comment by vinimotaa** [comment]
Hey @michaelpick, great work here mate. I loved the approach and consistency!

I'll work with the team to implement this ASAP.

Thank you a lot!

**Comment by vinimotaa** [comment]
@allilevine hey A.! Tagging you on this thread - @michaelpick helped us to put together the categories description for the Marketplace.

**Comment by vinimotaa** [comment]
@allilevine not sure if we should merge this thread with [#67239](https://github.com/Automattic/wp-calypso/issues/67239)?

**Comment by allilevine** [comment]
> @allilevine not sure if we should merge this thread with [#67239](https://github.com/Automattic/wp-calypso/issues/67239)?

@vinimotaa Can we keep this issue focused on the copy, and #67239 focused on any design (e.g. CSS) changes we need to make? Or do they need to happen simultaneously?

**Comment by vinimotaa** [comment]
@allilevine sure, we keep them as is :)

**Comment by lsl** [comment]
>  ((Note: is this the intended purpose, or is it more of an internal calendar? This also feels like a slightly uncannily specific category, maybe?))

Not sure about the origin of this but it is most likely the intended purpose for things like Events Calendar Pro being added soon. Definitely not an internal calendar, that would be a different category, "editorial [publishing] calendar" maybe - there are plugins for that too.

> ((Note: is this the full scope of email plugins?))

[Anything tagged with "email"](https://github.com/Automattic/wp-calypso/blob/8fc65f298af53b1fd6a06217578690a3fbe29810/client/my-sites/plugins/categories/use-categories.tsx#L114). Suspected the main usecase for this category would be for building email lists, email newsletter signups, sending newsletters, etc.


> Finance & Payments
>    Sell products, subscriptions, and services while keeping on top of every transaction.
>    ALT: Collect payments and keep on top of every transaction with advanced payment integrations.

Would prefer the alternate here, ecommerce / woo covers selling products.

> Marketing
>    Bring in new business and shine a spotlight on your projects or products.
>    ALT: Amplify the reach and visibility of your site or business.

Prefer the alt here too. Shining a spotlight vs amplify reach, I'd prefer to amplify reach.
