### ISSUE TITLE
Site Switcher i1: Add Tracks event for click on list item site

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#67209]
In order to better understand how well our ordering algorithm works, we'd like to track clicks on which site gets clicked:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/36432/187687749-58cfd024-a392-46ae-8786-ad062cb9f212.png">

**Done is:**
* When a site in the site switcher list is clicked, a new `calypso_switch_site_click_item` event fires.
* The `calypso_switch_site_click_item` event includes a `position` property that captures the site's position in the list.
* The `calypso_switch_site_click_item` event includes a `list_item_count` property that captures the total number of sites present in the list.
* The `calypso_switch_site_click_item` event includes a `is_searching` property that captures whether or not a search was initiated.

**Comment by vindl** [comment]
Should we also account for the total number of sites on the list? Rationale: position 4 is great in a list of 100 sites, and not that great if there are only 5 sites. One way to do it would be to record `(total - position)/total`.

**Comment by danielbachhuber** [comment]
> Should we also account for the total number of sites on the list?

@vindl Sure! I've updated the description accordingly.
