### ISSUE TITLE
Sites Management Page: grid view problems in Safari

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#67202]
There are a couple of issues with the grid view in Safari currently, likely happening on accounts with a large number of associated sites (100+):

- mshots thumbnails don't appear or appear inconsistently.
- there are performance issues in that view that almost cause Safari to freeze. This is especially pronounced while toggling between the grid and list view.

**Comment by sejas** [comment]
Fixed on two PRs: 
- https://github.com/Automattic/wp-calypso/pull/67205
- https://github.com/Automattic/wp-calypso/pull/67029
