### ISSUE TITLE
Comments not rendering the theme styled form on desktop

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#67212]
### Quick summary

On desktop screens, we get the default comments styling, but on mobile it shows up the theme styled one

### Steps to reproduce

1. Activate any theme
2. Check on a post/page that allows comments on desktop and mobile

### What you expected to happen

To see it styled as on mobile

### What actually happened

I'm seeing the default styling on desktop. 

Desktop vs mobile

Cultivate
![aLlZjF.png](https://user-images.githubusercontent.com/6737345/187686897-5a448fcd-0e52-48c7-9460-2e21cd7de67d.png)

Baskerville 2

![image](https://user-images.githubusercontent.com/6737345/187693631-027d49d1-9ebe-4280-acb0-9507e162b336.png)

### Context

5520356-zen

Slack thread: p1661953451709069/1661494145.715119-slack-C02FMH4G8

cc @daledupreez @ebinnion 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

Emulated on Chrome(iPhone 12/etc) and tested on iPhone 13

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by daledupreez** [comment]
This is part of a longer-term issue where our comment forms have had very opinionated styling on desktop.

@Automattic/dotcom-janitors have been working on improving the situation, and had a broader discussion about it a few weeks ago in p1HpG7-hu9-p2. We've also been working to modernise and simplify the CSS so we are more aligned with the theme's CSS in D85984-code, which we plan to deploy tomorrow. That should comprise a major first step towards styling the comment form in a theme-neutral manner, but we can keep this issue open as we move towards a better state.

**Comment by daledupreez** [comment]
We rolled out an initial update to the styles earlier today in D85984-code. That change more closely aligns the desktop commenting UI with the theme on WordPress.com Simple sites.

**Comment by daledupreez** [comment]
We've just deployed a small improvement in D87700-code, which removes styling for the comment submit button.

You can see the improvement for Cultivate here:

![Image](https://user-images.githubusercontent.com/3376401/190168934-aea48532-17b5-4913-af5c-2655c9022191.png)

Unfortunately, the change doesn't improve Baskerville 2 due to us using slightly different element names for the comment form. I will work out how best to handle that shortly.

**Comment by daledupreez** [comment]
I just deployed D87734-code to fix the button styling issue for Baskerville 2, and possibly some other themes. The short version of that changes is that I added `button` as a CSS class to the "Post Comment" button.

**Comment by daledupreez** [comment]
I've switched teams, so this work may be on hold for some time. However, I think we have already reduced the number of styles considerably on Simple sites.

**Comment by lupus2k** [comment]
I made some tests, and it is looking good for Atomic Sites. Desktop & Mobile matches:
| Mobile | Desktop |
| --- | --- |
| <img alt="image" src="https://user-images.githubusercontent.com/402286/211939250-3f9d316f-dbe9-4397-9e22-39666974dd6a.png"> | <img alt="image" src="https://user-images.githubusercontent.com/402286/211939004-a66375d1-f190-459e-a1d9-57bb7acc3e57.png"> |

But in Simple sites, on Desktop, it uses the Jetpack Comments form, and we have to change some CSS.
Actual look:
| Mobile | Desktop |
| --- | --- |
| <img alt="image" src="https://user-images.githubusercontent.com/402286/211939748-51786096-042f-4f98-9988-dd36a693a4df.png"> | <img alt="image" src="https://user-images.githubusercontent.com/402286/211938857-cba38bd8-2f9d-4968-88b6-a407598560a4.png"> |

I was working on some CSS changes and this is what I get on Desktop and using the Jetpack Comments form:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/402286/211938872-ab83f7d8-198c-403f-987b-370df4293a8f.png">

**Comment by lupus2k** [comment]
Created a diff to match Jetpack Comment Form to the selected theme.
D98218-code

**Comment by cometgrrl** [comment]
> Created a diff to match Jetpack Comment Form to the selected theme.
D98218-code

@lupus2k Does this mean this is resolved now? Can we close it?

**Comment by cuemarie** [comment]
Retested simple sites today:

**TT3**

| Desktop | Mobile |
| --- | --- |
| ![Markup on 2023-10-05 at 16:37:34](https://github.com/Automattic/wp-calypso/assets/27249804/74264bb7-66a7-40db-8609-fa7a3efc1a4d) | ![IMG_64A9812AE040-1](https://github.com/Automattic/wp-calypso/assets/27249804/802e500a-e6f5-4bb3-a382-6ea0b8af872d) |

**Disco**

| Desktop | Mobile |
| --- | --- |
| ![Markup on 2023-10-05 at 16:39:28](https://github.com/Automattic/wp-calypso/assets/27249804/c4ff28a0-1baf-43c9-bc68-8fddb8ff6760) | ![IMG_96093083580C-1](https://github.com/Automattic/wp-calypso/assets/27249804/5144d870-a60e-46fd-86d0-a797066eaa60) |

📌 ACTIONS
- Closing as resolved
