### ISSUE TITLE
Marketplace: Nudge Redesign

### ISSUE THREAD

**Issue by vinimotaa** [Automattic/wp-calypso#67223]
Another component we’re aiming to improve is the plan upgrade nudge design. The affordance of the existing Calypso’s nudge is pretty low. Apart from that, the visual component looks like an “alert message” about your current plan more than a “call to action” to upgrade your plan.

We plan to build this as a new component to replace the existing one on the Marketplace and check the conversion performance over time. Depending on how it performs, we can potentially replace all the plan upgrade nudges across the platform using this new component and still use the existing one for alert messages and other notifications.

- We shall keep the same content (call to action for now)
- We shall display the nudge always in the same place (right below the main search header)
- Add/keep analytics

Bellow the existing design version

![Group 1000004420](https://user-images.githubusercontent.com/97929097/187728702-8972e76e-5292-443a-98f9-eb37471b7ca1.png)

This is what it should look like:

![Group 1000004422](https://user-images.githubusercontent.com/97929097/188197375-a8dee59c-1edc-44bb-bcc8-629e98489275.png)

Section padding details:

![Group 1000004427](https://user-images.githubusercontent.com/97929097/187728906-cb88466b-d1c4-49b1-8393-59efd2fe5484.png)

![Group 1000004428](https://user-images.githubusercontent.com/97929097/187728958-a782c0cb-2067-40dc-ab54-879542299e2c.png)

**Comment by allilevine** [comment]
Considering A/B testing: pdh6GB-207-p2

**Comment by allilevine** [comment]
We're likely not going to A/B test this change, but monitor clicks.

**Comment by vinimotaa** [comment]
A quick update on this issue - we need to replace the copy of the nudge, both description and CTA.

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/97929097/193632035-d823094d-bc53-4b27-b8e5-04d29a0e5fac.png">

cc @lupus2k

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/issues/68540
