### ISSUE TITLE
Video Uploads Failing on Atomic Sites

### ISSUE THREAD

**Issue by connorhipps** [Automattic/wp-calypso#67236]
### Quick summary

Users cannot upload .mp4 or .mov files (possibly any video files at all) via the Media Library or the Video Block on Atomic sites. This doesn't appear to be theme-specific. 

Personal Atomic Site Test:
![CleanShot 2022-08-31 at 15 48 48](https://user-images.githubusercontent.com/5952196/187769425-7d83acc3-7803-4e2c-baa1-31d77960f347.gif)

### Steps to reproduce

1. Start by navigating to the site referenced in 5522178-zd-woothemes
2. Navigate to My Site → Media → Select any .MP4 file → Download the File and Rename It
3. Open a test atomic site and navigate to My Site → Media → Click 'Add New' 

### What you expected to happen

A successful .mp4 upload to an Atomic site. 

### What actually happened

The following error is shown on upload:

`1 file could not be uploaded because an error occurred while uploading.`

### Context

- This has been noted on 5522178-zd-woothemes and personal atomic sites. 
- Changing the file type doesn't seem to correct the issue (for instance, .mov doesn't upload either). 
- Videos cannot be uploaded via the Editor either. 
- Images can still be uploaded. 

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Not theme specific. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by msilbers** [comment]
reported in 

- [ ] 5522323-zen

**Comment by JoshuaGoode** [comment]
Thanks for the report

For widespread Atomic-specific things, please be sure to ping @Automattic/reactor, and also @ at-help internally, and possibly post to Atomic Requests as well. Feel free to just start with a ping, though.

cc @upwardmomentum84 

Internal discussion: p1661975727174769-slack-C02FMH4G8

**Comment by upwardmomentum84** [comment]
Reported in

- [ ] 30710011-hc

**Comment by msilbers** [comment]
- [ ] 5522504-zen

**Comment by JoshuaGoode** [comment]
Jetpack 11.3beta caused some issues


We reverted back to 11.3-a.11 and issues are resolved.
