### ISSUE TITLE
Sharing Button 'Press This' not copying highlighted text to new post

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#67245]
### Quick summary

When resharing content using the `Press This` sharing button on a site that's chosen to display it, the highlighted text is not copying over to the new post.

- By comparison, using the `Press This` bookmark works properly

### Steps to reproduce

1. I was able to replicate the reports using Firefox 104, Chrome 104
2. On a simple test site, go to Tools > Marketing > Sharing Buttons, and add the `Press This` sharing button, and make sure sharing buttons appear on your posts or pages. 
3. Open a post on that site, highlight text, and select `Press This`

### What you expected to happen

The highlighted text to appear in the new post, like it does when using the `Press This` Bookmark:

![Markup on 2022-08-31 at 19:15:36](https://user-images.githubusercontent.com/27249804/187818541-fb5ef14d-acd4-45a3-90c8-ebd6ceb8bd31.png)

### What actually happened

The new post's title copies over, but there's no body of content.

<img width="1236" alt="Markup 2022-08-31 at 19 17 01" src="https://user-images.githubusercontent.com/27249804/187818480-bd9ddc29-0a01-45fa-8132-757d6d07b10d.png">

### Context

Creating a new report for this specific issue to distinguish the reports shared here:  **Press This Not Working In Some Browsers #56960** , which was originally specific to the Press This Bookmark.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

Screenshots above are from:

- Firefox Version 104.0 on macOS Monterey version 12.5.1 
     - Javascript, Cookies, and Third Party Cookies all enabled
- Chrome Version 104.0.5112.101 on macOS Monterey version 12.5.1
     - Javascript, Cookies, and Third Party Cookies all enabled
- Chrome Version 105.0.5195.52 (same browser as above, just updated)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The Press This Bookmark (guide: https://wordpress.com/support/press-this/ )works as an alternative

**Comment by cuemarie** [comment]
Copying over an interaction regarding the sharing-button-specific issue from another report: 

- [ ] 4765045-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: feature not available on AT
- Tested on Self-hosted: feature not available on Self-Hosted
- Replicable on Core? No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Still able to replicate this issue. `Press This` sharing button on a simple site pops open a window with just the title of the post, and none of the content in the body of the post being shared.

*Example*
<img width="1670" alt="Screen Shot 2022-09-07 at 9 37 42 AM" src="https://user-images.githubusercontent.com/27249804/188934573-a4df57e7-4de8-4ddf-917d-f39a110a0d91.png">


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by nelsonec87** [comment]
Here is a diff to fix it: D97836-code
![image](https://user-images.githubusercontent.com/3801502/212076141-dbe18e0b-3c07-489c-b4d3-66f2a3931412.png)

**Comment by nelsonec87** [comment]
Diff landed
