### ISSUE TITLE
LaunchPad preview - disable banner

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67279]
Edit - after testing again this seems to happen with newsletter sites on the 'free' plan in general.

<s>When using the LaunchPad in incognito mode on chrome, or default settings on safari (possible related to 3rd party cookie settings?),</s> there is a banner added inside the preview:

![Screen Shot 2022-09-01 at 12 48 12 PM](https://user-images.githubusercontent.com/28742426/187968963-f05304c4-9dc6-4275-b2cd-661d918f648c.png)

We want to disable this when possible. One suggestion was to add the `?preview=true` param, but I tested this briefly and it didnt seem to work.

**Comment by sharpirate** [comment]
Created a [PR](https://github.com/Automattic/wp-calypso/pull/67345)
