### ISSUE TITLE
Marketplace: Top header Refinements

### ISSUE THREAD

**Issue by vinimotaa** [Automattic/wp-calypso#67285]
I believe this is a quick win. As we added the categories to the main header, we want to reduce overall proportions and keep the "most popular searches" within the same line, and double-check if the overall padding matches what is below;

![topheader_01](https://user-images.githubusercontent.com/97929097/187990176-9157fe2b-e58c-43e2-a348-adafa5adf48b.jpg)

![topheader_02](https://user-images.githubusercontent.com/97929097/187990192-1665c9c4-e8c9-454f-9776-13f5f75f0e2f.jpg)

**Comment by vinimotaa** [comment]
Hi team, this is a quick update/iteration on the above.

While I keep exploring the overall redesign of this top header, we need to update the existing one with the following changes;

![topheader](https://user-images.githubusercontent.com/97929097/193278552-a581f3ea-9679-4c88-8413-2203689f042f.jpg)

- Review all the padding specs from the image above
- Add a Light Grey background #fdfdfd to the top header
- Remove "most searched words" from the header
- Add/change the below-header background color to white. This applies to all pages (#fff)
- Change the color of the main title (Flex your site's features with plugins), the activated category button, and the category names to Blue90 (#01283D).
- Remove the arrow from “Browse all,” and add a lowercase for “all”. Browse all
- Search box size would be 400px wide
- The line (stroke) right below the main top header should be 1px #F6F7F7

Final look;

![topheader_look](https://user-images.githubusercontent.com/97929097/193279423-ac601d7f-260d-45a2-ac88-b993ae3e7806.jpg)

**Comment by lsl** [comment]
Designs look good vini, have you got a Figma link handy?

Let's break this down into multiple issues for development, for example these could be their own issues / pr's:

- Color changes
- Margin/padding changes
- Search term removal + box size change
- Browse all link text change

**Comment by candy02058912** [comment]
Created issues:
- Color changes: https://github.com/Automattic/wp-calypso/issues/68572
- Margin/padding changes: https://github.com/Automattic/wp-calypso/issues/68573
- Search term removal + box size change: https://github.com/Automattic/wp-calypso/issues/68574
- Browse all link text change: https://github.com/Automattic/wp-calypso/issues/68575
