### ISSUE TITLE
Add Support Link to Block Descriptions for Post Content and Table of Content Blocks

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#67293]
### What

This is a follow-up to #62284 and #56091 to add new documentation links to two blocks:

- [x] Post Content https://wordpress.com/support/full-site-editing/theme-blocks/post-content-block/
- [x] Table of Contents https://wordpress.com/support/wordpress-editor/table-of-contents-block/

cc @arcangelini 

### Why

This will help WordPress.com users easily discover our comprehensive resources on how to use each block in the editor. With these support docs, users can learn about blocks more quickly, figure out the settings themselves, and reduce their likelihood of contacting support for basic editing tasks.

### How

Around 70 blocks have a Learn More link to a support doc, such as this example:

![image](https://user-images.githubusercontent.com/30727666/188034347-d0bcdfbe-f1f6-45e1-8a29-751f2c798a82.png)

Let's add the above links to the Post Content and Table of Contents blocks:

![image](https://user-images.githubusercontent.com/30727666/188034304-3bfe5da1-5c59-4837-8722-c70631afd5e9.png)

![image](https://user-images.githubusercontent.com/30727666/188034276-0ffeb7c6-10a2-421f-a6b9-263b828d87d1.png)

**Comment by alshakero** [comment]
Hi @donalirl! Was this intentionally added to our board?

**Comment by donalirl** [comment]
@alshakero Yes, it was intentional as the previous task #62284 was also done in that board. My apologies if I made a mistake!

**Comment by alshakero** [comment]
No worries at all! Adding it to our board usually implies that we'd build it, and it seems my teammates [did think that and implemented it](https://github.com/Automattic/wp-calypso/pull/67425) :D

**Comment by escapemanuele** [comment]
@donalirl it is also necessary to add localization to the support articles presented.
Url has been translated, but translation for the support article for Post Content is still missing though.

**Comment by donalirl** [comment]
Thanks! I've submitted it for translation. Ref: p1662686588197479-slack-C02AED43D
