### ISSUE TITLE
LaunchPad - newsletter 1st publish celebration modal

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67321]
Create an editor plugin (possibly through ETK), presents a congratulatory modal upon completion of the publish first post task of the newsletter launchpad flow.

This can check for site options of `site_intent == 'newsletter'` and `launchpad_checklist_tasks_statuses.first_post_published !== true` to know which sites to show this to on publish.

![image](https://user-images.githubusercontent.com/28742426/188627212-1664dcf6-d02b-4b20-b824-df825042cfea.png)

**Comment by edanzer** [comment]
Do we have any Figma designs or other input/decisions on the content of this modal, including headline/text, but also where the buttons will go? Otherwise, I'm happy to just add the content/buttons myself and we discuss any changes in the PR.

**Comment by Addison-Stavlo** [comment]
> other input/decisions on the content of this modal, including headline/text, but also where the buttons will go? 

I would go with the text and positioning in the design screenshot linked above, but maybe @nuriapenya has more specifics or updates?

**Comment by saygunnyc** [comment]
I think we're missing dots after "23 readers" and "to the world" I also believe share is used with "with" instead of "to". 

So, It should be:
"Congratulations! [Intro to Lorca](url) is on its way to **23 readers**. Now it's time to share it with the world. "

cc @michaelpick in case he has any final notes before translation.

**Comment by michaelpick** [comment]
Thanks @saygunnyc! I agree with your comments above. Otherwise, LGTM!

**Comment by Addison-Stavlo** [comment]
We are abandoning this issue for other approaches for launchpad cohesiveness - paYE8P-2kx-p2 

Also noting the design conflicts with (or is covered by) the in development publish sharing modal unrelated to launchpad/TUCs.
