### ISSUE TITLE
Site Switcher: Always display 'Add new site' in wp-admin menu, and stick to bottom

### ISSUE THREAD

**Issue by sejas** [Automattic/wp-calypso#67323]
### Details

The 'Add new site' button is currently in two places:
* Bottom of the sidebar for users with only one site.
* Bottom of the site switcher for users with more than one site.

To make the user experience more consistent, we'd like the 'Add new site' button to _always_ appear at the very bottom of the sidebar:

<img width="265" alt="Screenshot 2022-09-02 at 16 00 09" src="https://user-images.githubusercontent.com/779993/188177729-4a475258-abe0-4250-8873-0bb0d84ce87d.png">

Design for the button is a little TBD at the moment.

### Checklist

* [x] A consistent 'Add new site' button is added to the sidebar for users with one site and users with multiple sites.
* [ ] The 'Add new site' button is always sticky at the bottom of the sidebar.
* [ ] When the sidebar collapses, the 'Add new site' button appears as a plus icon.
* [x] The button continues to fire the `calypso_add_new_wordpress_click` Tracks event.
* [x] 'Add new site' also appears at the bottom of the Site Switcher.
* [ ] Changes are tested against Jetpack Cloud to ensure no regressions.

### Related

 https://github.com/Automattic/wp-calypso/issues/67040

**Comment by sejas** [comment]
PR https://github.com/Automattic/jetpack/pull/26015 Abandoned

**Comment by danielbachhuber** [comment]
Thanks again for your work on this, @sejas ! My apologies for the poor direction on my part 🙃
