### ISSUE TITLE
Styles: Change to the link hover color does not apply

### ISSUE THREAD

**Issue by vajrasar** [Automattic/wp-calypso#67320]
### Quick summary

When you change the link hover color using Site Editor > Styles - it does not applu

### Steps to reproduce

1. Go to Site Editor
2. Open Styles
3. Colors > Links > Hover > Change color to any color
4. Save the changes
5. Check the site, the link hover color won't change

### What you expected to happen

The link hover color should be set to the one I select using Site Editor > Styles.

### What actually happened

The link hover color defaults to the one already applied.

### Context

📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Could Not Replicate
- Tested on Self-hosted - Could Not Replicate
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate the issue using multiple themes including Remote, TT2, Meraki, Ames. Hence, the issue seems to be with the Styles feature and not the themes. 

The issue can only be replicated on the Simple sites.

I was able to replicate the issue on AT and Core, but after a cache flush things worked as expected. Hence, could no longer replicate on AT and Core.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No. 

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by vajrasar** [comment]
- [ ] 5526760-zen

**Comment by simison** [comment]
cc @Automattic/team-calypso-platform in case this is WP.com integration issue

**Comment by jamiepalatnik** [comment]
Another report: 36946343-hc

Attar theme. Shared custom CSS as a workaround.

**Comment by Gustavo-Hilario** [comment]
Another report:

- [ ] 5630255-zen

Cultivate theme. Shared CSS code.

**Comment by mpkelly** [comment]
I'm looking at this currently. My initial findings are that it works in some places but not others.

**Comment by mpkelly** [comment]
@vajrasar, which links were you having trouble with specifically? For example, it could be post titles, links in paragraphs, or links in menus/navigation. One thing to keep in mind, which might also be useful as a workaround, is that some blocks have their own link colour styles. If you go to **Styles** > **Blocks** > **Paragraph** > **Colors** > **Links** and specify colours there it should override the Global setting.

✅ = works at global level and block level. 

**Maraki**

- ✅  links in Paragraph block
- ✅  links in List Item block
- ✅  links in Page List block
- ❌  links in Latest Posts block inside a Footer with a dark background (see image below). I can't change these at all. 

![image](https://user-images.githubusercontent.com/6851384/198524452-45eab8a1-ab7e-4ab7-878b-e579ae79d64e.png)

**TT2**,
**Remote**

I can't change any links using these themes. I have tried changing the global link colour (**Styles** > **Colors** > **Links**) and also changing specific blocks (e.g.  **Styles** > **Blocks** > **Paragraph** > **Colors** > **Links**) but nothing works and the links are always the theme default colours. I can't see any CSS in Chrome from my changes in the Styles menu. 

I am going AFK soon, so I will see if someone on the @Automattic/build team can take a look at this.

**Comment by sanjeev00733** [comment]
Another report in #19939424-hc. 
It is not possible to change the navigation link hover color via Global Styles in the site editor.

**Comment by Gustavo-Hilario** [comment]
_Another report here: 6384755-zen
Theme: Munchies_

There was a CSS code overwriting the color the user set on Styles:

![Annotation on 2023-06-08 at 15-13-16](https://github.com/Automattic/wp-calypso/assets/50875131/f5b0a498-17bb-47fd-a402-352e5810f6f4)

_Code: https://s0.wp.com/wp-content/plugins/gutenberg-core/v15.9.1/build/block-library/blocks/navigation/style.css?m=1685748459i&cssminify=yes_

**Comment by cuemarie** [comment]
Retested today, and it appears this is resolved now for linked text, headings, post titles, etc.  The Navigation Block links are not impacted in the same way, and there are open requests for adding support for that, noted below.

https://github.com/Automattic/wp-calypso/assets/27249804/d7694e83-dcbb-4fda-85c4-00d1cb7440c5

`*` - For Navigation block link hover colors, specifically, please add interactions to the feature request below:
- WPcom feature request (for interactions): https://github.com/Automattic/wp-calypso/issues/79153
- Related Core issue: https://github.com/WordPress/gutenberg/issues/47431

📌 ACTIONS
- Closed as resolved
