### ISSUE TITLE
Question: Beginners friendly issues

### ISSUE THREAD

**Issue by alejandronanez** [Automattic/wp-calypso#6733]
Hi there, I'm wondering if it would be possible to add a label that indicates that an issue is "beginner friendly" for people new to the repo (like me).

Thanks!

**Comment by jeremeylduvall** [comment]
Hey @alejandronanez! We do currently have the `[Type] Good First Change`:

https://github.com/Automattic/wp-calypso/issues?q=is%3Aissue+is%3Aopen+label%3A%22%5BType%5D+Good+First+Change%22

Is that the type of label you were looking for?

**Comment by alejandronanez** [comment]
I guess so! Thanks @jeremeylduvall. I'm closing this. 👍

**Comment by alejandronanez** [comment]
@jeremeylduvall btw what's the process for grabbing an issue so others don't work on it.

**Comment by jeremeylduvall** [comment]
We don't have a specific process in place that I'm aware of. If it's unassigned, feel free to work on it. You can also comment on the issue letting others know you're tackling it so anyone can ping you if they have questions.
