### ISSUE TITLE
Site Thumbnail: Avoid loading images twice

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#67338]
One side effect of #67337 is that the image is loaded twice 😦 

![image](https://user-images.githubusercontent.com/36432/188214247-25f2984a-615e-43ad-82c8-e6456bc9f626.png)

I think this is because `src` is loaded first, and then `srcset`.

From p1662140637833059/1662136092.517739-slack-C0347E545HR

**Done is:**
* A Site Thumbnail image is only loaded once.

**Comment by zaguiini** [comment]
https://www.google.com/search?q=src+srcset+loading+twice&oq=src+srcset+loading+twice&aqs=chrome..69i57j33i160l4.2683j0j1&sourceid=chrome&ie=UTF-8

**Comment by danielbachhuber** [comment]
This was fixed in #67406
