### ISSUE TITLE
LaunchPad - Enable going back to "Add Subscribers" for newsletters.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67336]
Currently in the newsletter checklist for LaunchPad, "Add Subscribers" is complete and we offer no way for the user to go back to this screen to add more subscribers.

We should enable this item to allow navigation back to this step in a flow that leads back to Launchpad. The checklist item should still reflect completion visibly, but allow for this navigation.

**Comment by agrullon95** [comment]
Launchpad enabling navigating back to `Add Subscriber` after task completion changes have been updated in #https://github.com/Automattic/wp-calypso/pull/67405.
