### ISSUE TITLE
Site Thumbnail: Don't accidentally show mShots loading image when mShot URL updates

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#67340]
If you already have `/sites` loaded and make a change to one of your sites, the incremented `site.last_updated` will cause a new mShot to be generated.

However, when the mShot is generated, the mShots loading image will display:

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/36432/188219263-99a9dda3-1df6-4169-a2ca-51e5ebf550f3.png">

What should be displaying is the site icon overlaid on a blurred background with the loading state applied.

Discovered while working on #67337

See conversation in p1662136092517739-slack-C0347E545HR

```diff
diff --git a/client/sites-dashboard/components/sites-site-item-thumbnail.tsx b/client/sites-dashboard/components/sites-site-item-thumbnail.tsx
index 49e715a40e..324750e836 100644
--- a/client/sites-dashboard/components/sites-site-item-thumbnail.tsx
+++ b/client/sites-dashboard/components/sites-site-item-thumbnail.tsx
@@ -25,8 +25,8 @@ export const SiteItemThumbnail = ( { site, ...props }: SiteItemThumbnailProps )
 	let siteUrl = site.URL;
 	if ( site.options?.updated_at ) {
 		const updatedAt = new Date( site.options.updated_at );
-		updatedAt.setMinutes( 0 );
-		updatedAt.setSeconds( 0 );
+		// updatedAt.setMinutes( 0 );
+		// updatedAt.setSeconds( 0 );
 		siteUrl = addQueryArgs( siteUrl, {
 			v: updatedAt.getTime() / 1000,

 
```

**Steps to reproduce**
1. Apply the patch above.
2. Navigate to `/sites` in your local environment.
3. Observe a site thumbnail appear as expected for your site.
4. With `/sites` open in one window, make an edit to a Site Editor page in the FSE.
5. Switch back to the `/sites` page.
6. Wait for a moment for the data to refresh.
7. Once the data refreshes and `site.last_updated` is incremented, observe the mShots loading image appear.

**Comment by vykes-mac** [comment]
What I've seen so far is that the browser holds on to the srcset and displays one of the the images when `onLoad` fires. This prevents the check 
```
const hasLoadingImgDimensions = event.currentTarget.naturalWidth === 400 && event.currentTarget.naturalHeight === 300;
```
from ever being valid since none of the srcset matches the width and height of the mshot default image. It would make sense to set the srcset after the image is fully loaded but this might cause the onload function to fire again.
