### ISSUE TITLE
Feature request: Serbian Latin transliteration

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#6734]
WordPress.com offers the option to transliterate Serbian into latin script, instead of using the Cyrillic script. The option does not exist in Calypso, and even if enabled in WP-Admin, doesn't affect Calypso.

**Comment by yoavf** [comment]
Note: the current option in wp-admin is a per blog setting. If enabled, it affects the user interface while on the blog, but it doesn't affect any strings elsewhere.

**Comment by carinapilar** [comment]
Requested on #2713922-t
