### ISSUE TITLE
Gutenberg Paragraphs: dir="LTR" results in unexpected or invalid content error

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#67354]
### Quick summary

Content creators who use RTL and LTR languages in their sites have been able to reverse text direction for a given paragraph block by editing its HTML and adding `dir="LTR"` or `dir="RTL" `. This stopped working in a recent update: creating paragraphs with that HTML edit, or editing a post that already has those types of paragraphs, results in `unexpected or invalid content error` messages that can't be recovered without stripping the text direction. Block recovery doesn't help; the setting gets removed.

### Steps to reproduce

1. Start by writing a new post: https://wordpress.com/post
2. Add a paragraph
3. Choose to edit its HTML
4. Add dir=RTL or dir="rtl" or whatever acceptable syntax you'd like (this happens with ltr as well)
5. Tap out of the block; you'll get a block error
6. If you attempt recovery, the direction will be removed

https://user-images.githubusercontent.com/3476361/188287322-eef6d74d-a8bd-4047-b881-5f9589478bf3.mov

### What you expected to happen

Honestly I'd expect a [text direction option](https://github.com/Automattic/wp-calypso/issues/62319) in the paragraph block's settings, or just [for blocks in general](https://github.com/WordPress/gutenberg/issues/26608). But if we must hand-edit the HTML, we need to accept it as valid.

### What actually happened

We get a block error with an offer to attempt recovery, which just removes the text direction.

### Context

https://wordpress.com/forums/topic/left-to-right-english-text-in-right-to-left-hebrew-blogs-is-mis-directed/

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Theme-specific issue?

n/a

### Browser, operating system and other notes

n/a - this isn't a browser so much as an issue with what code we accept as valid. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is to ignore the error and publish anyway, but it's kind of annoying to no longer be able to see the block text in the editor. Or, we can convert to an HTML block instead. But it would be better to fix the issue.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on P2: **Replicated**
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Replicated**
- Replicable on Core? **Yes** : https://github.com/WordPress/gutenberg/issues/15349

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate this everywhere, just as @supernovia has described above. 

*Examples*

**Simple**

https://user-images.githubusercontent.com/27249804/188951594-930b5858-c4b6-4c39-9566-344a4968995a.mp4

**Self-Hosted**
<img width="1308" alt="Screen Shot 2022-09-07 at 11 26 45 AM" src="https://user-images.githubusercontent.com/27249804/188951540-003838df-561a-417f-b467-db75dae4efca.png">

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Related Core Issue:
     - https://github.com/WordPress/gutenberg/issues/15349
- Added to 'HE Cross-repo Watchlist' project board

**Comment by annezazu** [comment]
The related Gutenberg issue has been resolved: https://github.com/WordPress/gutenberg/issues/15349 

Closing this out as a result!
