### ISSUE TITLE
Top Toolbar does not stay enabled on free plan

### ISSUE THREAD

**Issue by renata-franco** [Automattic/wp-calypso#67382]
### Quick summary

The Top Toolbar that we can turn on via the extra options on the Block Editor needs to be turned on every time the user opens a new page. This was only replicable on a free plan site. Does not seem to happen on paid plan sites. 

### Steps to reproduce

1. Go to Block Editor. 
2. Click on the three dots on the top right. 
3. Select Top Toolbar. 
4. Close the Editor and open a new post/page. 
5. See how the Top Toolbar is not turned on. 

### What you expected to happen

The top toolbar should be turned on on all pages or posts. They shouldn't be any need to turn it on every time. 

### What actually happened

Top Toolbar has to be turned on every post/page that the user opens. 

### Context

For reference, this is the top toolbar:

![imagen](https://user-images.githubusercontent.com/81378719/188446002-75c8aff0-5989-4dca-b51e-9d9d786f8ee9.png)

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

User would need to upgrade to a paid plan, or turn on the tool bar every time they visit the editor.

**Comment by renata-franco** [comment]
Here is a video of the bug in action. 

https://user-images.githubusercontent.com/81378719/188447214-9c34e29c-e1ca-4cd7-8950-12c3c0e3baca.mp4

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Could Not Replicate
- Tested on Self-hosted - Could Not Replicate
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this issue on a free site as stated in the original report, and also on a Personal plan simple site. 
- I was not able to replicate this on Premium, AT, or self-hosted sites. The top toolbar appears on other pages once it is selected in the options.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by youbrokesomething** [comment]
I was able to reproduce the same behavior with Spotlight Mode and Fullscreen mode as well. Fullscreen mode is defaulted to on and won't stay off. [It looks like this might be a duplicate issue.](https://github.com/Automattic/wp-calypso/issues/64324) However, not being able to reproduce on a paid site seems new.

**Comment by heavyweight** [comment]
This is no longer reproducible
