### ISSUE TITLE
Style selection: UI/UX polish

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#67388]
## Description
These are the UI/UX polish tasks that either need more clarification or time to work on:
- [x] How to handle theme descriptions?
For now, we just display the first sentence of the description. (D86697-code)
- [x] How to handle preview without style variations? Sidebar would look very empty.
#67629
- [x] Update the mobile breakpoint to 1024px.
#67778
- [x] Clicking a style variation from the style indicator should open the preview with the variation selected.
#67436
- [x] Style preview font-rendering not loading the correct font.
We are likely to not address this in the MVP due to technical complications. See: pbxlJb-2ow-p2

## Acceptance Criteria
Discuss with stakeholders to align on how to handle the issues mentioned above.

**Comment by SaxonF** [comment]
>  How to handle preview without style variations? Sidebar would look very empty.

@taipeicoder let's move forward with just showing the old preview on themes without variations for now.

**Comment by taipeicoder** [comment]
Closing as it's deployed.
