### ISSUE TITLE
Blank Canvas: Images in the slideshow block are not visible on the live page

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#67392]
### Quick summary

Using Blank canvas, images in the slideshow are only visible in the site editor but not on the live page.

### Steps to reproduce

1. Activate Blank Canvas theme.
2. Open the site editor and add a slideshow. 
3. Compare the slideshow on the site editor and the front page of the site. 

### What you expected to happen

The slideshow images will be visible in both the site editor and front page of the site. 

### What actually happened

The slideshow images are only visible in the site editor. 

### Context

User report: 5531661-zd and self-testing. 

<img width="2457" alt="Screen Shot 2022-09-05 at 5 07 58 PM" src="https://user-images.githubusercontent.com/36863633/188478870-0f755d5a-496b-4410-aee6-fff91deea8ac.png">

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Blank Canvas

### Browser, operating system and other notes

MacOS 12.5.1, Firefox 104. 

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Change into another theme, I tested Skatepark and the slideshow images appear in both the site editor and front page.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on P2 ✅ 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- This is a duplicate of these two issues:
https://github.com/Automattic/themes/issues/6081
https://github.com/Automattic/jetpack/issues/22834

- What we know is that the Slideshow Block isn't fully compatible with the Site editor.

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/themes/issues/6081
