### ISSUE TITLE
Signup: Headstart: Headstart flows should use the `ThemesList` shared component.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#674]
See #256.

**Comment by kwight** [comment]
@sirbrillig Would your findings in #675 apply here too?

**Comment by sirbrillig** [comment]
I think this issue is still relevant. IIRC, Headstart's flow is identical to the "regular" signup flow except that it also triggers Headstart during the site creation Action. If the "regular" signup flow has been changed, the Headstart flow should be changed as well to match.

**Comment by sirbrillig** [comment]
That said, this should probably wait until #256 is complete.

**Comment by oskosk** [comment]
#1079 has been merged. Is this solved now @kwight ?

**Comment by sirbrillig** [comment]
Hmm. From the testing instructions in the PR read:

> Load http://calypso.localhost:3000/start/headstart (you'll be redirected to /start/themes)

In fact, you should be redirected to start/headstart/theme-headstart.

But maybe it was a typo. I tested the /headstart flow and when I created a new site, it appears to have all the correct headstart content.  To compare, here's a new site created with the Edin theme without Headstart:

<img width="512" alt="screen shot 2015-12-02 at 11 34 54 am" src="https://cloud.githubusercontent.com/assets/2036909/11536972/e5223e42-98e8-11e5-9f2f-8c3916700c48.png">

And here's a site I just created with Edin using the Headstart flow:

<img width="512" alt="screen shot 2015-12-02 at 11 35 12 am" src="https://cloud.githubusercontent.com/assets/2036909/11536980/f2c8336c-98e8-11e5-87b4-8b7ab0e197ce.png">

I'd say that this is working. We can re-open this issue if we discover any problems. Thanks, @oskosk!
