### ISSUE TITLE
DevDocs: SpinnerLine component is hidden

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#6740]
Note that this is unique to devdocs, and not an actual production issue.

#### Steps to reproduce
1. Open URL https://wpcalypso.wordpress.com/devdocs/design/spinner-line
2. Observe

#### What I expected
To see the Spinner Line component

#### What happened instead
The component is rendered invisible by [this entry](https://github.com/Automattic/wp-calypso/blob/master/client/devdocs/style.scss#L164) in the devdocs style.scss file.  I believe it was introduced by commit https://github.com/Automattic/wp-calypso/commit/39b20f110193d08ef45090eeddd43240884f99ce cc: @mtias 

#### Screenshot / Video
![wp-calypso-spinnerline-invisible](https://cloud.githubusercontent.com/assets/7233112/16808246/b5e8804e-48e9-11e6-9a8c-be404dca47cd.gif)

#### Context / Source
#manual-testing (while configuring automated tests)

This would have been found via automated visual diff testing, but the since the spinning components are constantly changing by design those elements are ignored.

**Comment by mtias** [comment]
@hoverduck this wasn't introduced recently, it's just old code we had for devdocs display clashing with the component element: https://github.com/Automattic/wp-calypso/blob/master/client/devdocs/style.scss#L163
