### ISSUE TITLE
LaunchPad -  handle Hello World post on newsletter sites

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67426]
Currently Newsletter sites are created with the standard "Hello World" post already published. Beyond this, the post is future dated so it shows up higher in the blog feed than their later added newsletter posts.

There are various ways we could address this, but it seems like we could look at:
* (preferable) Changing "Hello World" for newsletter sites to `draft` state when their first other post is published.
* (fall-back) Change the date on "Hello World" to not be future-dated, so it doesnt show up above the newsletter feed.

**Comment by agrullon95** [comment]
~~I have opened a diff with the changes for this issue: D87537-code~~

~~These changes will follow the first bullet point method: `(preferable) Changing "Hello World" for newsletter sites to draft state when their first other post is published.`.~~

Logic has been updated to remove the initial "Hello World!" for newsletter sites during the "new site" process: D87596-code

**Comment by agrullon95** [comment]
Removing the "Hello World!" post for newsletter sites only changes have been merged : D87596-code.

Let's keep a note for investigating the Headstart library solution (not creating the initial post on during the site creation process). It could provide a cleaner , generic solution for different tailored site flows.
