### ISSUE TITLE
[Bug]: Site Editor infinite loading in Safari only

### ISSUE THREAD

**Issue by connah99** [Automattic/wp-calypso#67434]
### Quick summary

Opening the Editor on Safari via Appearance>Editor results in an infinite loading screen. The loading animation is present until the page stops loading, but the Editor itself is never loaded. This issue is not present in either the app or other browsers. 

Standard troubleshooting such as cache clearing, network reset etc resulted in no difference and this issue is present on multiple devices. 

### Steps to reproduce

1. From admin, go to Appearance>Editor
2. Click on Editor

### What you expected to happen

The Editor to load.

### What actually happened

The Editor didn't load and a white screen was the only outcome. 

### Browser

Apple Safari

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Other browsers and the app still load the Editor with no issue.

**Comment by happychait** [comment]
A similar customer report with Safari: Site Editor doesn't load / keeps blanking.

37718105-hc

**Comment by masperber** [comment]
Another report here: 42714175-hc

**Comment by vinnykaur** [comment]
3 reports

40934410-hc
42125120-hc
6223544-zen

**Comment by essleeung** [comment]
~~Another case here 41165892-hc- it only loads if a specific template is selected.~~ Moving to [76105](https://github.com/Automattic/wp-calypso/issues/76105) instead.

**Comment by christianguerrag** [comment]
Three cases here: 6208728-zen 6224425-zen and 6224876-zen reported by HCs in Slack.

**Comment by dlaurisse** [comment]
Another one here: 6207527-zen

**Comment by trixxmanaty** [comment]
Another one here: 6224717-zen

**Comment by abyvantony** [comment]
Another one here: 6225738-zen

**Comment by abyvantony** [comment]
Another one here: 6225287-zen

**Comment by abyvantony** [comment]
Another one here:  6225312-zen

**Comment by abyvantony** [comment]
Another one here:  6224944-zen

**Comment by abyvantony** [comment]
Another one here:  6225531-zen

**Comment by laragee6** [comment]
This user is experiencing the same issue: zen-6225312

**Comment by trixxmanaty** [comment]
same issue here: 6224944-zen

**Comment by abyvantony** [comment]
Another one here: 6225559-zen

**Comment by trixxmanaty** [comment]
another one here: 6225531-zen

**Comment by trixxmanaty** [comment]
same issue here: 6224357-zen

**Comment by abyvantony** [comment]
Another one here: 6225845-zen

**Comment by abyvantony** [comment]
Another one here: 6225877-zen

**Comment by cuemarie** [comment]
This appears to be the same as:

- https://github.com/Automattic/wp-calypso/issues/76105

which has been escalated for attention here: p1682186205979559-slack-C02FMH4G8

**Comment by villanovachile** [comment]
I don't think this issue (only happening in Safari) is actually related (the issue I escalated is specifically is related to the removal of iframe, which is causing a CORS issue on all browsers). 

For anyone reading this, I'd recommend reporting subsequent issues to this thread: https://github.com/Automattic/wp-calypso/issues/76105 so we can get more eyes on it.

**Comment by cuemarie** [comment]
I agree with @villanovachile ! I think most of the issues that were reported here in the last 24-48 hours are pretty likely reflecting https://github.com/Automattic/wp-calypso/issues/76105 instead. 

---

@masperber , @vinnykaur , @essleeung , @christianguerrag , @dlaurisse , @trixxmanaty , @abyvantony , @laragee6 - Can you please check your customer's browser, domain set up, and the console logs they were running into in the editor, to determine which issue they were facing?

- If they only see the problem in Safari, and do not have a custom domain as primary, then this is the right place to report it.
- If they have a custom domain as primary on a simple site, and see the problem across browsers (bonus points if you can spot that CORS error in the Console), then please share the user interaction on https://github.com/Automattic/wp-calypso/issues/76105 instead, especially if the user is hoping for a reply about it in the future.

Thanks for your help getting all these interactions reported in the right place!

**Comment by cuemarie** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/76105 as it appears most of these interactions reflect that issue instead.
