### ISSUE TITLE
Task: Apple sign in is unavailable for newsletter flow

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#67440]
### Details

See [Context](pdtkmj-pL-p2#comment-828).

This shouldn't be hard, as the problem only occurs in the newsletter flow.

**Comment by heavyweight** [comment]
Took a look at this and I think we should close this.

The apple signup is available on trunk and prod
<img width="1754" alt="Screenshot 2022-09-07 at 10 38 58" src="https://user-images.githubusercontent.com/7000684/188832678-25225c23-3fda-47f0-b9e6-55f79e3218da.png">
<img width="1783" alt="Screenshot 2022-09-07 at 10 38 51" src="https://user-images.githubusercontent.com/7000684/188832683-6446c082-e90f-485a-a4d5-4ea94196c358.png">

The user was testing on horizon.wordpress.com
I verified that it is not available there:
<img width="1624" alt="Screenshot 2022-09-07 at 10 39 07" src="https://user-images.githubusercontent.com/7000684/188832875-d0e9b300-7f10-4ba0-857b-469cf22f3cea.png">

Looking at the config it is explicitly disabled there on this line: https://github.com/Automattic/wp-calypso/blob/trunk/config/horizon.json#L93

**Comment by alshakero** [comment]
Great sleuthing.
