### ISSUE TITLE
Task: Unexpected scroll bar in the plans grid

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#67449]
### Details

Context [here](pdtkmj-pL-p2#:~:text=Nitpick%2C%20but%20there%20was%20an%20unexpected%20horizontal%20sidebar%20on%20the%20plan%20selection%20step%3A)

Most likely the same bug as https://github.com/Automattic/wp-calypso/pull/66961

**Comment by heavyweight** [comment]
Tested with lots of different browsers, as well as MBP with Firefox as in the original report, but couldn't reproduce this.
Will [follow up on the P2](pdtkmj-pL-p2#comment-901), and close this after some feedback from the reporter.
