### ISSUE TITLE
Theme Sheet: Add upsell banner for bundled premium themes

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#67450]
### Details

In https://github.com/Automattic/wp-calypso/pull/67444, I removed the upsell banner for premium themes, because the wording doesn't fit:
![2022-09-06_10-06](https://user-images.githubusercontent.com/937354/188682313-553d5505-b1bd-48ea-8d42-e07bfb789d9d.png)

Should we add a new banner specific to bundled premium themes? (Woocommerce themes)

**Comment by blackjackkent** [comment]
You can probably use something similar to the wording suggested at https://github.com/Automattic/wp-calypso/issues/68307.

**Comment by markbiek** [comment]
@blackjackkent What do you think of this wording? (based on the link you provided)

![image](https://user-images.githubusercontent.com/917632/195179808-4bc5c310-5794-4758-9642-86b4b4f23d95.png)
