### ISSUE TITLE
[WooCommerce] Analytics - Custom Date selection displays oversized arrow icons

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#67493]
### Quick summary

When trying to open the calendar under WooCommerce's Analytics > Overview, on selecting a specific date range, when trying to open the date picker nothing happens.

There are Previous and Next arrows showing in large. 

Screencast video: 
https://user-images.githubusercontent.com/7382505/188856775-f8796b38-2721-4a26-81cf-9c5ea6a819a2.mp4

### Steps to reproduce

1. Open Analytics from WooCommerce.
2. Under Overview open the filter and under the Custom tab.
3. The date picker is showing weirdly, it is open with large next and next arrows.

### What you expected to happen

The large arrows are not to be displayed. And the date picker to be shown when clicking on the calendar icons.

### What actually happened

Large arrows showing and the calendar is pushed down belowshow

### Context

customer report
chat: 36783627-hc
Ticket: 5538891-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by kimerlin81** [comment]
Another case of this reported:
5542072-zd-woothemes

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated - gigantic arrows in the date picker under WooCommerce Analytics. The arrows do still work (advancing the calendar below forward or back a month)

*Example*
![Markup on 2022-09-13 at 09:42:06](https://user-images.githubusercontent.com/27249804/189959491-a655dcf8-e034-4ea1-af72-b09f9009a540.png)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by csabarakasz** [comment]
The user came back again: 36903940-hc

This is the follow-up ticket

- [ ] 5542072-zd-woothemes

**Comment by melek** [comment]
Affecting 5638406-zen as well.

**Comment by sverleis** [comment]
Affecting 5683511-zen

**Comment by cometgrrl** [comment]
@Automattic/solaris It seems like this bug might belong over on the Woocommerce side of things. What's the best way to confirm that? Is there an easy way to check on a self-hosted site with WC if this reproduces so we can rule out if it's an Atomic site-only issue?

**Comment by lanej0** [comment]
I tried to reproduce this on WooCommerce 7.2.2 on both Jurassic Ninja (self-hosted) and on an Atomic Ephemeral site.  I wasn't able to see the giant arrows, with the new WC navigation feature enabled or without.

![Screenshot 2023-01-09 at 11 30 25 AM](https://user-images.githubusercontent.com/80276/211392352-930e6c20-65ae-4f2f-8d91-fbbf29d7b809.png)

Might be worth checking the console to see if there are any errors in JS or CSS loading?

**Comment by jordesign** [comment]
I'm not longer able to recreate this - so it seems it may have been fixed in the interim period

**Comment by vinnykaur** [comment]
📌 SCRUBBING : RESULT

- Tested on AT - Could Not Replicate
- Tested on Self-hosted - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Cannot replicate the issue

<img width="1325" alt="Screenshot 2023-01-10 at 6 17 48 PM" src="https://user-images.githubusercontent.com/49183855/211555724-6b6ea6b9-fb23-4b92-ad28-517bef9df4fb.png">

📌 ACTIONS

- Marked as Triaged for Quality Squad review.

**Comment by vinnykaur** [comment]
Closing this, but please feel free to open again if you can replicate the issue.
