### ISSUE TITLE
WordPress iOS app - After sharing a Reader post, the app stays at the confirmation page

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/wp-calypso#67499]
### Quick summary

When sharing a post from Reader to Facebook, the WordPress iOS app remains at the confirmation page and doesn't go back to the Reader. The app needs to be relaunched.

### Steps to reproduce

1. Open WordPress app on an iPhone.
2. Go to reader, share a post to Facebook.

### What you expected to happen

The app should have gone back to the Reader screen.

### What actually happened

It remained on the confirmation page and there's no option to go back without relaunching the app. Here's a video that I recorded on my iPhone.

https://user-images.githubusercontent.com/49064126/188874967-7e3f8141-54be-496a-8136-389fd252cd34.mp4

### Context

- [ ] Reported in #5533938-zen

I was able to duplicate this on my iPhone 13 Pro. On Android the app goes back to Reader screen as expected (p1662550606702149-slack-C03TY6J1A)

### Theme-specific issue?

No

### Browser, operating system and other notes

iOS devices
WordPress 20.5 (20.5.0.1)

### Workaround details

Relaunching the app helps.

**Comment by Joshgrygiel** [comment]
📌 SCRUBBING
- Tested on both an iPhone 11 running iOS 16.0 and an iPhone X running iOS 15.4
- Replicable: No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Upon sharing a post to Facebook from the reader the app successfully shared the post to Facebook, and redirected back to the Reader tab as normal.

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)


📌 Message to Author
- Hey @mriyazuddin I was unable to replicate this on my end after testing on an iPhone 11 and iPhone X. I do see the app was updated after this report was opened, and I'd like to know if you can still reproduce the issue on your iPhone 13? Thank you!

**Comment by mriyazuddin** [comment]
Thanks for the update. Not sure how I missed this. I'm unable to replicate this as well now as sharing to Facebook works fine now. I've let the user know.
