### ISSUE TITLE
Atomic: Unable to Invite 'Subscriber' user roles via Calypso

### ISSUE THREAD

**Issue by cat-og** [Automattic/wp-calypso#67531]
### Quick summary

The subscribers role was not available when inviting new users to a plugin-enabled site. I confirmed this on my site, and there was no change when I tried setting the site to Private. 

### Steps to reproduce

1. Go to Users on a plugin-enabled site.
2. Invite new users.

### What you expected to happen

I expect the Subscribers role to be available when inviting new users. 

### What actually happened

The only available roles available are:

- Administrator
- Editor
- Author
- Contributor
- Shop manager
- Customer

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by ariel-maidana** [comment]
Another case here: 15647818-hc
Please notify the user when this issue is solved.

**Comment by inaikem** [comment]
Tested and replicated on new and existing sites. I see the [equivalent ](https://wordpress.com/support/user-roles/#follower)Follower[ role](https://wordpress.com/support/user-roles/#follower) on Simple sites but is Subscriber missing — see the screenshots below.

**Note:** it is still possible to invite users via WP Admin, which is a suitable fix for sites that don't need WPcom SSO. However, for WPcom users, this results in the newly invited user getting stuck in an endless JP connection loop with the message: `This site is already connected to a different WordPress.com user, you need to disconnect that user before you can connect another.`

Escalated for review here: p1662868346809039-slack-C02FMH4G8Cc: @Automattic/reactor 



**Simple sites**
<img width="755" alt="New user - Simple" src="https://user-images.githubusercontent.com/66711744/189511712-ceb9e12f-0021-497d-8206-0771b66fc197.png">

&nbsp;
**Atomic sites**

<img width="763" alt="New User - Atomic" src="https://user-images.githubusercontent.com/66711744/189511718-e6e3e5fd-52d1-489c-96ec-740b672f683d.png">

**Comment by Nic-Sevic** [comment]
Also tested this on an ephemeral site and the "follower" option is there with the newest release candidate for Jetpack 11.4-a.1

When tested on WoA site though, with only Jetpack active, the "follower" option is not there. In this case I'm also seeing a request for `https://public-api.wordpress.com/rest/v1.1/sites/204198722/roles?http_envelope=1` failing but I'm not sure if this is related

**Comment by Nic-Sevic** [comment]
It seems like this is connected to this change: https://github.com/Automattic/wp-calypso/pull/67160

**Comment by bogiii** [comment]
Hey @Nic-Sevic,

You are right. My recent changes caused a missing role issue.
I forgot to pass the flag option to the `RoleList` component. The fix is here: https://github.com/Automattic/wp-calypso/commit/7144f2934f612a3ff6c51af333271228b013781a

I'll test this case one more with fresh eyes on Monday morning and deploy it ASAP.

Thanks for discovering it!

**Comment by inaikem** [comment]
> Another case here: 15647818-hc
> Please notify the user when this issue is solved.

@ariel-maidana 👋 I've manually replied to the affected user above. In the future, please be sure to create a follow-up for us to track as described at the link below, thanks!

p7DVsv-eZ1-p2

**Comment by ariel-maidana** [comment]
> @ariel-maidana 👋 I've manually replied to the affected user above. In the future, please be sure to create a follow-up for us to track as described at the link below, thanks!
Thank you @inaikem! I'll take it into account in the future.
