### ISSUE TITLE
[Bug]: Support link for block description tracking broken

### ISSUE THREAD

**Issue by arcangelini** [Automattic/wp-calypso#67538]
### Quick summary

There appears to be an issue with the tracking of the support link block. As of August 19 there was a sharp drop in the amount of clicks. More details here - p1662467300871089-slack-CRNF6A9DX

**Comment by cuemarie** [comment]
Whatever broke the tracking looks to have been resolved (or removed) after 2022-11-10 - tracking is back starting that date. Closing as resolved.
