### ISSUE TITLE
Marketplace: Endpoint for creating a billing_intent

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#67547]
A billing intent is the intention of a customer to go through with a transaction. The billing intent is created by a 3pd vendor after a customer selects their plan in the 3pd interfaces. Vendor should have a way to create [POST] this billing intent through an API.

- [ ] the endpoint accepts uuid (combination of user and site id), store_product_slug, price in usd, billing_interval ( monthly / annually ), return_url
- [ ] the endpoint returns a WP.com checkout url `https://wordpress.com/checkout/[DOMAIN]` or an error

A basic data structure for billing intents has been created in https://github.com/Automattic/wp-calypso/issues/67260

**Comment by gavande1** [comment]
WIP Diff created: D87610-code

**Comment by gavande1** [comment]
Diff separated for easy review- D88280-code

**Comment by gavande1** [comment]
Deployed part 2 in r253253-wpcom

**Comment by gavande1** [comment]
Diff created for tests: D88989-code

**Comment by cpapazoglou** [comment]
Since we are not doing anything catastrophic in production, I guess we can merge this and iterate.

**Comment by gavande1** [comment]
Deployed r253805-wpcom

**Comment by gavande1** [comment]
Test deployed r254043-wpcom
