### ISSUE TITLE
Marketplace: Communicate the support policy for WP Job Manager add-ons

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#67553]
We should add a notice in the WPJM add-ons description mentioning that WPJM support is via email only to set the correct user expectations.

A nice to have for the Marketplace would be to handle support policies natively (as suggested in https://github.com/Automattic/wp-calypso/issues/67542), but it's not a blocker for the WPJM add-ons work.

**Comment by dsas** [comment]
I'm not sure this is needed. If it's a billing enquiry, or something super obvious like 'yup you deactivated the plugin', a HE would presumably just handle it in live chat. If it requires product knowledge they'll kick it to email.

[For 3PD](https://developer.wordpress.com/wordpress-com-marketplace/supporting-wordpress-com-plugins/)s our HEs will handle billing and generic questions, but anything technical goes to ticket and forwarded to the 3PD. 

What's the difference here?

**Comment by Copons** [comment]
@dsas I think we can close this, as clarified in p1663071305588769-slack-CJS75TX3R.
