### ISSUE TITLE
Marketplace: Add new action hooks for subscription events to WPCOMSH

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#67550]
Expose a new license_provisioned action hook in WPCOMSH that would be used by vendors to persist the license information on the Atomic site.

**Comment by obenland** [comment]
Is this not covered by the `subscription_created` webhook?

**Comment by BogdanUngureanu** [comment]
Handled by @obenland in https://github.com/Automattic/wpcomsh/pull/1100 with a follow-up improvement in https://github.com/Automattic/wpcomsh/pull/1102. The second PR looks fine, but I made an improvement suggestion. 

Moving this to review on our board.
