### ISSUE TITLE
[Bug]: Subdirectory Site Preview Duplicates Pathname

### ISSUE THREAD

**Issue by sdixon194** [Automattic/wp-calypso#67563]
### Quick summary

The component rendering the site preview URL is appending the pathname on top of the site URL (which already includes the pathname for sites in subdirectories), causing the site preview URL to look duplicated. I believe [this is happening here](https://github.com/Automattic/wp-calypso/blob/4c6a3e471be6b6b75112b28d8cddf2670cfd643a/client/my-sites/preview/main.jsx#L130).

![Screen Shot on 2022-09-08 at 12:43:42](https://user-images.githubusercontent.com/33553323/189178911-ee7b8b42-7c79-4705-986e-75b5d623e90a.png)

### Steps to reproduce

1. Create a WordPress site in a subdirectory, connect it to Jetpack.
2. Go to wordpress.com, switch to the subdirectory site and click on the site preview option
3. See that the URL shown duplicates the subdirectory URL path.

### What you expected to happen

The site URL to be shown once.

### What actually happened

It's appending the site subdirectory name twice.

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
Looks like this was resolved by https://github.com/Automattic/wp-calypso/pull/68358
