### ISSUE TITLE
[Comment Approval] Fix email subject when the post has no title

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#67565]
![Image](https://user-images.githubusercontent.com/3113712/189195969-ccbab4c2-13d2-4a90-9a66-5bc49671653d.png)

**Comment by ivan-ottinger** [comment]
Looking at the [Figma](c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A24079), the new email subject should be in the following form: `[{site_title}] {user_name} commented on {post_name}` - basically the same as for the _New Comment_ emails (https://github.com/Automattic/wp-calypso/issues/67597).

**Comment by ivan-ottinger** [comment]
D87580-code is now deployed.
