### ISSUE TITLE
Themes: Fix per-plan default themes, set Ecommerce default theme to Twenty TwentyTwo

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#67562]
As discussed in this P2 comment thread p9Jlb4-575-p2#comment-5774, we should update the default selected theme for users on the eCommerce plan to be Twenty Twenty Two rather than the current Zoologist.

**Comment by mreishus** [comment]
There is no default ecommerce theme. There is only a default theme that applies to all sites regardless of plan selected. It's currently zoologist, but we can update that to 2022 in #68118. It was set to zoologist in #57134.

Alternatively, it looks like it's trying to detect plan type and switch themes based on it, but it's not working.
https://github.com/Automattic/wp-calypso/blob/6e316cb8c662f3899cb6df64454c412b6b412c0e/client/lib/signup/site-type.js#L42-L81
We could fix that, but it would take longer.

**Comment by mreishus** [comment]
We want to 
* keep zoologist as the default theme
* Fix the per-plan theme detection in `client/lib/signup/site-type.js`
* Change ecommerce's theme to twenty twentytwo

**Comment by mreishus** [comment]
I tried this approach: https://github.com/Automattic/wp-calypso/pull/68164
It seems to work, but I definitely want someone with experience in the onboarding and signup areas to review it.

**Comment by daledupreez** [comment]
@blackjackkent, I think we can close this issue out now that we've deployed both #68411 and #68417. The first PR switches the default theme to Twenty Twenty Two for all signup flows where the user explicitly chooses the eCommerce plan from the plans step in signup, and the second PR ensures that we default the theme to Twenty Twenty Two for the `ecommerce` and `ecommerce-monthly` signup flows where the user doesn't explicitly pick their plan.

Feel free to re-open if you think we need to take on more for this task.
