### ISSUE TITLE
Site Creation: Add ability to pre-select "import" goal when going through site creation flow

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#67586]
When navigating to the site creation flow we should be able to pass a flag (e.g. `?goals=import`) that will pre-select the "import" goal when going through the site creation and onboarding flow.

![Image](https://user-images.githubusercontent.com/1500769/189264403-c9f3d0c4-e164-4ab2-b4fb-5f7d0255ed14.png)

When this flag is available, it will be used by the sites management page when they indicate they want to import an existing site. See #67534.

Rather than pre-selecting, another option is to automatically submit the goal step, so the user doesn't even get asked the question about goals. The reason I think we should leave the goal step in the flow is because the user can have multiple goals. By indicating at the start of the flow that they'd like to import an existing site they've let us know one of their goals. But they might still have others!

Done is:
- [ ] Ability to pass a goals flag to `/start` flow
- [ ] The goals step is prefilled by the values in the flag
- [ ] We're only interested in the "import" goal, but the implementation shouldn't rule out the ability to pass multiple goals in the future

**Comment by wojtekn** [comment]
@p-jackson, we currently support pre-selecting goals via the `ref` parameter - for a given `ref` value, we can configure an array of goal values that we need to select:

https://github.com/Automattic/wp-calypso/blob/a86dc2254a6c12b82f26da8aa57839111177477e/client/landing/stepper/declarative-flow/internals/steps-repository/goals/index.tsx#L33:L35

We could add a new record to support this ticket requirements:

```
'smp-import': [ SiteGoal.Import ],
```

It also supports multiple values - we could choose multiple goals that should be pre-selected for a given `ref`.

Does it fill the requirements? Or do we need a separate `goals` URL param that would precede values set by the `ref` parameter?

**Comment by wojtekn** [comment]
It's done. I've reused an existing feature that uses `refGoals` for now, we can adjust it later if needed.
