### ISSUE TITLE
Plans Redesign: Update "My Plan" page to use a plan icon

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6759]
As @apeatling suggested, let's update the star icon to the related plan icon on http://calypso.localhost:3000/plans/my-plan

We should create an plan icon component that we can reuse. (eg plan-features/header should be updated to use the shared component).

![ee3e8116-48ec-11e6-9da8-4cc4ea6aeb79](https://cloud.githubusercontent.com/assets/1270189/16817564/34f87778-48f8-11e6-92da-4172c42737b4.png)

**Comment by lamosty** [comment]
@rralian: I work on this in #6777.
