### ISSUE TITLE
Getting Started documentation: add note about `ulimit`

### ISSUE THREAD

**Issue by aminimalanimal** [Automattic/wp-calypso#676]
By default, OS X has a `ulimit` that is too low to properly run `make run`. Too many files are required simultaneously, passing the 256 file limit, which results in errors in the console and only the navigation bar and report bug section being loaded in the page.

Users can run `ulimit -n 2560` to increase this limit and allow them to run the project properly. I suggest adding a note about this to the docs.

**Comment by Viper007Bond** [comment]
It's mentioned in the troubleshooting documentation:

https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md
