### ISSUE TITLE
Classic Themes Showcase - FSE themes prompt customizer

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67606]
Currently the classic themes showcase prompts variousn buttons to the customizer instead of the site editor when FSE theme is active/activated.

### To Repro

1. Visit the theme showcase in calypso
2. Set 'classic' from the view options in the top-right:
<img width="270" alt="Screen Shot 2022-09-09 at 9 24 24 AM" src="https://user-images.githubusercontent.com/28742426/189360173-86928a63-d3b7-4409-97f5-da8303e8601b.png">
3. Enable an FSE theme
4. Problem 1 :  The confirmation modal prompts users with a link to the customizer instead of the site editor:
<img width="435" alt="Screen Shot 2022-09-09 at 9 26 27 AM" src="https://user-images.githubusercontent.com/28742426/189360563-a3742f32-2769-491d-bdc0-651cd5e42f8f.png">
5. Problem 2: The theme card prompts a customizer button instead of a site editor button as well:
<img width="323" alt="Screen Shot 2022-09-09 at 9 27 07 AM" src="https://user-images.githubusercontent.com/28742426/189360693-a96fe4db-7927-469a-ae00-598acc8a81cf.png">

### What is expected?

These buttons to be "Edit site" or "Edit" buttons leading to the site editor, as is seen on the default theme showcase.

**Comment by jeyip** [comment]
Potential fix D88732-code
