### ISSUE TITLE
Marketplace: vendors should be able to authenticate our webhooks

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#67610]
If we’re going to ask vendors to provision a license, we should find some way to allow the 3pd to authenticate our requests. This might be [signing the request like Github does for webhooks](https://href.li/?https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks) or just passing a shared secret.

related convo: paYJgx-2lt-p2#comment-2758
props: @ebinnion

**Comment by cpapazoglou** [comment]
We can use the shared token that vendor already has for authentication to create a signature and add it in the request so that then vendor can verify the authenticity by creating a signature with their token and checking against the signature in the request sent.

**Comment by obenland** [comment]
Patch in D87893-code

**Comment by BogdanUngureanu** [comment]
Deployed in rWPGIT76aa088646bbc8c9f240adbc02fdfcb709ca6d87
