### ISSUE TITLE
Plans Redesign: Highlight the premium plan as the most popular plan

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#6761]
I think we should be calling out the premium plan as our most popular plan and differentiating it in some way. This is a very common practice across different paid services.

The idea is that it will encourage people to select premium who may be on the fence, or bring more people up who would otherwise have selected personal.

We should test this separately from the rest of the work on the plans page.

![screen shot 2016-07-13 at 12 35 18 pm](https://cloud.githubusercontent.com/assets/1464705/16817673/bcc9d502-48f8-11e6-908b-08404cf90590.png)

Looking for feedback on the design, specifically colors.

**Comment by gwwar** [comment]
Implementation wise for the ribbon, we should be able to pull a lot of the styling from:
https://wpcalypso.wordpress.com/devdocs/app-components/feature-comparison

**Comment by rickybanister** [comment]
I don't really like the combination of green and blue, neither really indicate a preference or a superior plan I don't think. Making the Premium plan taller or push forward seems like a more standard way of promoting a plan.

Or perhaps we try using standard buttons for personal and business and primary buttons for premium?

**Comment by gwwar** [comment]
We may also want to consider accessibility for color choices here. ie make sure we have good contrast or pick colors that folks are unlikely to have a difficult time here with

**Comment by lamosty** [comment]
@rickybanister not sure we have enough space for making the premium plan taller/wider. We would have to make the other plans a bit smaller, I think.

**Comment by artpi** [comment]
> push forward

I would love that.

**Comment by rralian** [comment]
> I don't really like the combination of green and blue, neither really indicate a preference or a superior plan I don't think. Making the Premium plan taller or push forward seems like a more standard way of promoting a plan.

IMHO let's just try the easiest/fastest one first (which is probably just the colors), and if that wins we can test it against alternate approaches.

**Comment by artpi** [comment]
I am closind this since it's merged
