### ISSUE TITLE
Marketplace: Intermittent empty footer space bug

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#67615]
From pdh6GB-1Vu-p2 it's not consistent but we have a bug under the educational resources with a full-height bleed of empty footer space.

![footer empty](https://user-images.githubusercontent.com/1689238/189428054-87b1695e-b138-4f51-af2a-53edd3caea8a.png)

Acceptance criteria:
- [ ] You've tried to reproduce the issue on /plugins
- [ ] If replicable, a fix for the issue.

**Comment by lsl** [comment]
Could be related to [these things](https://github.com/Automattic/wp-calypso/blob/186c7a8aaebfe0aac8d02990cdf67f6c90c87c4c/client/components/section/index.tsx#L27-L30). Might be best to redesign the page layout into something simpler. I think we're working around a mismatch between design wanted and calypso base page layout components.

**Comment by cpapazoglou** [comment]
Could not reproduce it.
