### ISSUE TITLE
Feature: WordPress.com Marketplace (Plugins) > User can't reinstall plugin after reset/plugin deletion

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#67624]
### Quick summary

If a user deletes a plugin that they purchased through the marketplace they have no real way to get it back because it doesn't show in the WooCommerce dashboard. Instead, if they try and re-add it through the marketplace they're prompted to purchase it again even if the subscription is still valid.

Maybe we should change this so that if a valid sub is found the marketplace allows re-linking the associated plugin?

### Steps to reproduce

1. purchase a plugin subscription through the marketplace (ex: WooCommerce subscriptions)
2. SFTP into the site and delete the plugin (also happens when user requests to have their site reset)
3. see that no way to re-add plugin to site (restore should work but this may not be obivous to user)

### What you expected to happen

they should be able to re-add the plugin for use with the existing license

### What actually happened

since the plugin is symlinked and it seems like they don't receive a zip file copy the user has no way to re-add the plugin even if the subscription is still valid

### Context

5547957-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

no

### Browser, operating system and other notes

n/a

### Reproducibility

Consistent

### Severity

Affects all users with marketplace plugin purchases and there's no user facing workaround

### Available workarounds?

Yes, difficult to implement

### Workaround details

An HE needs to re-symlink the plugin for them or needs to have the user rewind to the point the plugin was present

**Comment by csmcneill** [comment]
- P2: p6q7sZ-aqV-p2
- Similar issue: #60661
- Similarly discussed in p1657556488136659-slack-C3NCP7ZJ6

For the last item in the list, a user purchased [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/?aff=10486&cid=1131038) but it did not install/activate due to a conflict which threw a fatal error. 

To resolve it, we used the following WP CLI command:

```
$ wp --skip-plugins --skip-themes plugin symlink [folder name] --activate
```

Replace `[folder name]` with the appropriate folder name (e.g. `woocommerce-subscriptions` or `woocommerce-composite-products`).

**Comment by Joshgrygiel** [comment]
📌 SCRUBBING
- Tested on P2 ❌
- Tested on Simple ❌ 
- Tested on AT ✅ 
- Tested on Self-hosted - ❌ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can confirm the symlinked plugins added through the Marketplace can not be simply added back to the site by the user, even if the purchase is still active. 

The suggested command to add the symlinked plugin back does indeed work:

`$ wp --skip-plugins --skip-themes plugin symlink [folder name] --activate`

It would make sense to have some sort of checker in place to ensure users are able to add their purchased marketplace plugins back to their site whenever they feel they want it back on their site. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by ghost** [comment]
Another report here 37443732-hc

**Comment by agrullon95** [comment]
@cpapazoglou - Is this something that has been also raised in your discussions related to syncing WP.com and WooCommerce.com plugins? (https://github.com/Automattic/wp-calypso/issues/60661). 

I noticed I cannot delete the WooCommerce Subscription plugin on WP.com (which helps mitigate part of this issue), but I was able to force delete using an SFTP client. As this issue mentions, theres no way to add the WooCommerce Subscription plugin again from WP.com nor WC.com.

It would helpful if you have any existing discussions I can look at or join if there's something we can start doing from our end. Thanks

**Comment by cpapazoglou** [comment]
> @cpapazoglou - Is this something that has been also raised in your discussions related to syncing WP.com and WooCommerce.com plugins? (#60661).
> 
> I noticed I cannot delete the WooCommerce Subscription plugin on WP.com (which helps mitigate part of this issue), but I was able to force delete using an SFTP client. As this issue mentions, theres no way to add the WooCommerce Subscription plugin again from WP.com nor WC.com.
> 
> It would helpful if you have any existing discussions I can look at or join if there's something we can start doing from our end. Thanks

👋 @agrullon95 there are no discussions on how we could allow the end user to add back a purchased and deleted plugin. Eventually we would need:
- an endpoint that checks if the plugin is purchased and adds it back by calling `$marketplace_software_manager->install_product_software()`
- leveraging this endpoint in Calypso, instead of forcing the user to buy the plugin again

For HE:
- if the plugin is purchased through WP.com users should not upload it or install it in any other way other than the one mentioned in https://github.com/Automattic/wp-calypso/issues/67624#issuecomment-1245733650 for the time being.
- if the site goes simple and then it's transferred again to Atomic all marketplace plugins will get installed.

**Comment by epeicher** [comment]
After the work done as part of 
- https://github.com/Automattic/wp-calypso/issues/60661
The user will be able to download and re-install the WooCommerce plugin uploading it. The subscription will still be valid and the plugin will appear as activated.

![CleanShot 2023-01-20 at 21 09 02@2x](https://user-images.githubusercontent.com/3519124/213796875-97c56965-1834-4156-9df6-a9752468bfff.png)

In my opinion this approach is fine and this issue could be closed but I would like if someone else confirms that we are happy with this approach.

**Comment by cpapazoglou** [comment]
> After the work done as part of
> 
> * [Marketplace: Sync WP.com purchases with WC.com #60661](https://github.com/Automattic/wp-calypso/issues/60661)
>   The user will be able to download and re-install the WooCommerce plugin uploading it. The subscription will still be valid and the plugin will appear as activated.
> 
> ![CleanShot 2023-01-20 at 21 09 02@2x](https://user-images.githubusercontent.com/3519124/213796875-97c56965-1834-4156-9df6-a9752468bfff.png)
> 
> In my opinion this approach is fine and this issue could be closed but I would like if someone else confirms that we are happy with this approach.

Installing the plugin by downloading it will not install the managed version, let'a avoid sharing this workaround with users. Instead, triggering the `marketplace_post_transfer_manage_software` async job from Calypso user purchase seems enough for starters.

![CleanShot 2023-01-23 at 13 32 58@2x](https://user-images.githubusercontent.com/12430020/214029797-58495d3a-d8ab-435f-a04a-86ca5b40bae5.png)

**Comment by epeicher** [comment]
Thanks, @cpapazoglou for your suggestion! I didn't think about it, but we can see using an FTP client that the plugin is not installed as a symlink thus not-managed
![CleanShot 2023-01-23 at 18 05 57@2x](https://user-images.githubusercontent.com/3519124/214103342-9ae1da36-68d5-4b0f-bb73-bdb5c8b3bf1d.png)

> triggering the marketplace_post_transfer_manage_software async job from Calypso user purchase seems enough for starters.

To clarify the approach, does that imply:
- Adding the button to the purchases screen
- Calling the backend to trigger `marketplace_post_transfer_manage_software`
- Notify the user about the success or error of the async job

Do you agree with that approach? One question about it, do you suggest a way to trigger an async job from Calypso? Any code or examples I could check?

Thank you very much!

**Comment by cpapazoglou** [comment]
> Do you agree with that approach?

Yes, that's the idea!

> One question about it, do you suggest a way to trigger an async job from Calypso? Any code or examples I could check?

I don't think there is such a wrapper / endpoint. We will need to create a new post route eg `wpcom/v2/marketplace/products/%slug/install` in WPCOM_REST_API_V2_Endpoint_Marketplace_Products class.

**Comment by epeicher** [comment]
Diff that creates the endpoint D99297-code

**Comment by epeicher** [comment]
Diff created D99297-code

**Comment by epeicher** [comment]
Diff with backend changes deployed r260576-wpcom
