### ISSUE TITLE
Pattern Assembler: Improve the a11y

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#67632]
#### Description

We preload the patterns by hiding the elements on the screen. However, it's not good for the a11y. So, we need to improve the a11y to make the behavior of pressing tab/space/enter better.

#### Acceptance Criteria

* The behavior of pressing tab/space/enter works as expected.

#### Dev Tasks

- [ ] TBD

#### Related

* https://github.com/Automattic/wp-calypso/pull/67478#issuecomment-1240403005

**Comment by bangank36** [comment]
Closed as landed

**Comment by miksansegundo** [comment]
I think that we need to use `tabIndex={ show ? 0 : -1 }` [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx#L47) as well.

**Comment by bangank36** [comment]
> I think that we need to use `tabIndex={ show ? 0 : -1 }` [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx#L47) as well.

As discussed, I updated the fix on this 7ed0fde

**Comment by autumnfjeld** [comment]
@bangank36  this issue is still in the Ready for Dev column.  Can you move it to the appropriate column in our git board?

**Comment by bangank36** [comment]
Landed (2nd attempt)
