### ISSUE TITLE
Pattern Assembler: Show "Start with a blank canvas" CTA on mobile

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#67631]
#### Description

We also want to allow user to select the blank canvas design on mobile. cc @autumnfjeld 

From @SaxonF ([slack convo](p1663034398447989/1663034258.088529-slack-CRWCHQGUB))
> There is no mobile design for the cta as it should scale down without needing to change anything but I can put something together if it will help

Ping Saxon as needed for clarification.
Here is a quick mockup (that was WIP when I screenshoted it)
Check Figma for latest: 7l53h5fxAUNjVRBQ82YFwn-fi-1119%3A58446

<img width="146" alt="image" src="https://user-images.githubusercontent.com/5665959/189791633-68b8ac28-c3dd-4323-93eb-c8b82209e0db.png">

#### Acceptance Criteria

- [x] Show the blank canvas design on mobile
- [x] When the user selects the blank canvas design on mobe, they will land in the editor
- [x] Confirm with @SaxonF to show the different message on mobile as the behavior is different

#### Dev Tasks

- [ ] TBD

#### Related

N/A

**Comment by autumnfjeld** [comment]
I might phrase it as "Show the blank canvas CTA (Call to Action)" on mobile, and the behavior is the same as selecting any other designs.  But that is just minor wording.

**Comment by SaxonF** [comment]
Design should scale down on mobile and remain single column. We can adjust text on mobile as we'll be pushing people into the editor initially. 

![image](https://user-images.githubusercontent.com/1072756/189792181-e738e8d7-ffc1-4ece-bd50-f3ef3490a139.png)

**Comment by arthur791004** [comment]
@autumnfjeld @SaxonF What's the position of the blank canvas CTA on mobile?

**Comment by autumnfjeld** [comment]
@arthur791004  You mean list 1st in the list or 2nd in the list?   Should we follow the screenshot above?  Similar to desktop, it doesn't show 1st?

**Comment by arthur791004** [comment]
Yes, I just want to confirm whether the position is the same as desktop or not

**Comment by SaxonF** [comment]
@arthur791004 would it after the generated designs and the first row (3 themes)? So 7th I suppose?

**Comment by arthur791004** [comment]
Sure! We will show it after the first 3 themes on mobile (the same as desktop). Note that we only have one theme per row on mobile

**Comment by bangank36** [comment]
Closed as Landed
