### ISSUE TITLE
Marketplace search: Find by Author should return more results

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#67644]
This is a follow-up of the following PR [#67327](https://github.com/Automattic/wp-calypso/issues/64939) as suggested by the following comment https://github.com/Automattic/wp-calypso/pull/67327#pullrequestreview-1103763016

Current implementation filters results by Author using `plugin.author.raw` field as explained in [the original task](https://github.com/Automattic/wp-calypso/issues/64939#issuecomment-1242213932) but additionally we could return more results if we add some kind of criteria to include contributors

> With this change we are missing many results that the author searched is a contributor ( not the original author ).

This task should be used to investigate and implement better options. For example, when filtering by `developer:"Automattic"` the following results should be also returned `Jetpack CRM` and `Jetpack Boost`. 

If we look at the original results returned by the `WP.org` API ([link here](https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request%5Bsearch%5D=jetpack-crm)), the Author is
```
"author": "<a href=\"https://jetpackcrm.com\">Automattic - Jetpack CRM Team</a>",
```
so this may indicate that using a fuzzy search by `plugin.author` could be one option but please note that the fuzzy search also could return more results than required, so that's why some investigation is required before the implementation.

**Comment by epeicher** [comment]
The following filter has been tested (commit https://github.com/Automattic/wp-calypso/commit/9e636f0d8e35b4dd62993b64561f972fc4594e7b):
```
should: [ { term: { 'plugin.author.raw': author } }, { match: { 'plugin.author': author } } ],
```
which returns results that either:
- have the **exact** value in `plugin.author`: `term: { 'plugin.author.raw': author }`
or
- have the **fuzzy** value in `plugin.author`: `match: { 'plugin.author': author }`

That works fine for **single-word** terms like `Automattic` as it now returns values for `Jetpack CRM` or `Jetpack Boost` **but** it will return too many results for **multiple word** terms like `Team Yoast` as it will match results for the `Team` word. Another example would be `LiteSpeed Technologies` which will return results for the `Technologies` word.

I am going to investigate other alternatives

**Comment by epeicher** [comment]
Before considering alternatives, I am going to double check if _fuzzy_ search is a good option to filter by author. Convo started here p1663066088719179-slack-C02JPCHEKDY

**Comment by epeicher** [comment]
An important detail, if we decide to use the `match` operator for filtering, is that we should add it to the list of `$queries_allowed` in the backend as indicated here 2d8f3-pb

Otherwise, the following error will be returned when doing the query:
```
BadRequestError: [queries:match] is not whitelisted. See https://developer.wordpress.com/docs/elasticsearch/elasticsearch-queries/
```

**Comment by gcsecsey** [comment]
@epeicher I've investigated this issue a bit, but I couldn't find a solution that would show all the required results.

### Finding all plugins by author

> That works fine for single-word terms like Automattic as it now returns values for Jetpack CRM or Jetpack Boost but it will return too many results for multiple word terms like Team Yoast as it will match results for the Team word. Another example would be LiteSpeed Technologies which will return results for the Technologies word.

I've also tested this, and I don't think we could use a `match` query with author names because of this reason.

We could, however, try to filter for the author name on multiple fields at the same time. Based on some examples, eg. try matching the author name `Automattic` against the `author_login` field as well.  Unfortunately, for most authors, the value in `author_login` differs from either the username in `plugin.contributors` or the name in `author` (or both), so we can't consistently use this field:

```json
GET jetpack-search-22/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "blog_id": "108986944"
          }
        },
        {
          "term": {
            "plugin.contributors": "litespeedtech"
          }
        }
      ]
    }
  },
  "_source": "{field}",
  "fields": ["author_login", "author","title.default", "plugin.author", "plugin.contributors"] 
}

// example hit
{
  "_index": "jetpack-search-22",
  "_type": "_doc",
  "_id": "108986944-p-98310",
  "_score": 11.529117,
  "_routing": "108986944-0",
  "_source": {},
  "fields": {
    "plugin.contributors": [
      "litespeedtech"
    ],
    "author_login": [
      "LiteSpeedTech"
    ],
    "title.default": [
      "Dash Notifier"
    ],
    "plugin.author": [
      "LiteSpeed Technologies"
    ],
    "author": [
      "LiteSpeed Technologies"
    ]
  }
},
```

I've also thought about looking up the author username based on the display name, but this would be problematic to do across WC.com vendors and WP.org authors.

Overall, I think it would be the most straightforward to filter for exact matches on the `author` field, especially if we plan to use the same filter in the search experience below.

### Search experience

As per [this comment](https://github.com/Automattic/wp-calypso/issues/64939#issuecomment-1235296063), I agree that for the search experience, we should implement faceting. That will let the user select the author out of all the possible ones for the search phrase, even if the author names have slight differences.

I couldn't test this with fields apart from `plugin_author` because aggregations only work on keyword fields, and currently it's the only keyword field. The result of the aggregation will look like this:

```json
GET jetpack-search-22/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "blog_id": "108986944"
          }
        }
      ],
      "should": [
        {
          "term": {
            "plugin.author_login": "automattic"
          }
        },
        {
          "term": {
            "plugin.contributors": "automattic"
          }
        }
      ]
    }
  },
  "_source": "{field}",
  "aggs": {
    "plugin_author_name": {
      "terms": {
        "field": "author_login"
      }
    }
  }
}

"aggregations": {
    "plugin_author_name": {
      "doc_count_error_upper_bound": 45,
      "sum_other_doc_count": 32016,
      "buckets": [
        {
          "key": "unknown_user",
          "doc_count": 28077
        },
        {
          "key": "shawfactor",
          "doc_count": 107
        },
        {
          "key": "rubengc",
          "doc_count": 95
        },
        {
          "key": "automattic",
          "doc_count": 80
        },
        {
          "key": "coffee2code",
          "doc_count": 73
        },
        {
          "key": "abuhayat",
          "doc_count": 65
        },
        {
          "key": "Access Keys",
          "doc_count": 53
        },
        {
          "key": "gopiplus",
          "doc_count": 53
        },
        {
          "key": "smub",
          "doc_count": 52
        },
        {
          "key": "algoritmika",
          "doc_count": 50
        }
      ]
    }
  }
```

On the UI, clicking on the author from the list should just apply the filter for that author name.

**Comment by epeicher** [comment]
Thanks @gcsecsey for the thorough analysis! I totally agree that the search experience would improve if we add faceting with a tree of aggregated author results that the user can click to filter down results. 

But as a current approach, do you agree that using the current `plugin.author.raw` field is good enough for the time being? 

@cpapazoglou  please note that we have not found a proper solution using existing functionality, if we use a fuzzy search it will return much more results than required, e.g. searching for `Team Yoast` will return results that match `Team`. 

Should we close this task and approach the search experience in a more global way using faceting? 

As an example, navigating to https://jetpack.com/?s=plugins
![CleanShot 2022-09-20 at 09 14 42@2x](https://user-images.githubusercontent.com/3519124/191192071-62411ea2-5d3f-4a9b-b415-22d41eaec6fb.png)

**Comment by cpapazoglou** [comment]
> Should we close this task and approach the search experience in a more global way using faceting?

Yes, let's close this for the time being.

**Comment by gcsecsey** [comment]
>But as a current approach, do you agree that using the current plugin.author.raw field is good enough for the time being?

Sorry for forgetting to answer this earlier. @epeicher Yes, I think that overall, using the `plugin.author.raw` field is a good interim solution, until we can implement a more robust one with facets.

**Comment by epeicher** [comment]
Closing this issue as per discussion in the comments, the current filtering approach is a good interim solution. A more global approach where we use faceting by author to filter by exact terms would be something that will improve the search experience
