### ISSUE TITLE
[DUP] Sites Management Page: add importing flow

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#67647]
Depends on: https://github.com/Automattic/wp-calypso/issues/67646.

Building upon the work in https://github.com/Automattic/wp-calypso/issues/67646, let's add the importing option in the New Site dropdown menu.

![image-6](https://user-images.githubusercontent.com/1182160/189646234-7b247351-0855-42c7-818a-1c98fd69e184.png)

Done is:

- [ ] There is a `Import an existing site` option in the split button dropdown menu.
- [ ] Clicking on it kicks off the site importing flow (explore how to reuse new importing flows from onboarding)
- [ ] We have Tracks events for clicks on this item

**Comment by wojtekn** [comment]
It looks like it duplicates https://github.com/Automattic/wp-calypso/issues/67534. I've ensured that requirements are compiled into the other ticket, and I've closed this one.
