### ISSUE TITLE
Sites Management Page: add Jetpack connection flow

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#67646]
Let's add Jetpack Connect as a separate option in the New Site button dropdown:

![image-6](https://user-images.githubusercontent.com/1182160/189644775-f4d91cd5-f526-4904-9670-ffc85793c300.png)

One caveat is that we should be using the [split button](https://web.dev/building-a-split-button-component/), so there is no need to repeat the "Create new site text".

Done is:
- [x] There is a dropdown under `New Site` button that shows `Connect Jetpack site` option
- [x] Once it's clicked, it leads to `jetpack/connect`
- [x] No need to add the importing flow, that will be handled in a separate task
- [x] We have Tracks events for clicks on this item

**Comment by sejas** [comment]
- Would be `Connect a Jetpack site` a better sentence?

- Should we add a "back to sites" button  when we navigate to the Jetpack page from the SMP, similar to the Add new site page?

**Current Jetpack Flow**
<img width="1228" alt="Screenshot 2022-09-12 at 15 01 44" src="https://user-images.githubusercontent.com/779993/189673882-aa334ba8-0f1d-4dea-908d-912149b8caad.png">

**Current Add new site Flow**
<img width="1260" alt="189674005-538859ae-ac3d-4653-a04b-d3cb8819f60b" src="https://user-images.githubusercontent.com/779993/189714833-790bbd74-3c75-49fd-bfb0-fa7c28f3a1ff.png">

**Comment by vindl** [comment]
@sejas, I'd say yes on both accounts. Maybe we should move these decisions and discussions to the PR so that the folks don't miss them.

**Comment by sejas** [comment]
I've copied my questions into the PR 👌
