### ISSUE TITLE
WP.com /hosting landing page

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#67648]
We should rethink the design and content of the /hosting landing page on WP.com. It should talk more to the builder and agency customers, and we should highlight some of the newly launched features:

- Sites Page
- SSH access
- WP CLI access

Done is:
- [ ] Determine if we need new designs and visuals for the page (we can make edits in Gutenberg too)
- [ ] Propose an update for page's copy and submit it for creative review

**Comment by SaxonF** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/1072756/190084922-e74b0196-15d2-4bee-ae39-7ffeb752b5e4.png">

**Site management**
Access and manage all your [WordPress.com](http://wordpress.com/) sites from the one location.

`<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M6 8C6 6.89543 6.89543 6 8 6H20C21.1046 6 22 6.89543 22 8V20C22 21.1046 21.1046 22 20 22H8C6.89543 22 6 21.1046 6 20V8ZM26 8C26 6.89543 26.8954 6 28 6H40C41.1046 6 42 6.89543 42 8V20C42 21.1046 41.1046 22 40 22H28C26.8954 22 26 21.1046 26 20V8ZM6 28C6 26.8954 6.89543 26 8 26H20C21.1046 26 22 26.8954 22 28V40C22 41.1046 21.1046 42 20 42H8C6.89543 42 6 41.1046 6 40V28ZM36 28C36 26.8954 35.1046 26 34 26V26C32.8954 26 32 26.8954 32 28V30C32 31.1046 31.1046 32 30 32H28C26.8954 32 26 32.8954 26 34V34C26 35.1046 26.8954 36 28 36H30C31.1046 36 32 36.8954 32 38V40C32 41.1046 32.8954 42 34 42V42C35.1046 42 36 41.1046 36 40V38C36 36.8954 36.8954 36 38 36H40C41.1046 36 42 35.1046 42 34V34C42 32.8954 41.1046 32 40 32H38C36.8954 32 36 31.1046 36 30V28Z" fill="white"/>
</svg>
`

**Connect to SSH**
Manage your [WordPress.com](http://wordpress.com/) website using command-line tools such as WP-CLI.
`<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9 18C7.8 18 7 19 7 20V23.5C7 24.5 7.8 25.5 9 25.5H14V27H7V30H15C16.2 30 17 29 17 28V24.5C17 23.5 16.2 22.5 15 22.5H10V21H17V18H9ZM21 18C19.8 18 19 19 19 20V23.5C19 24.5 19.8 25.5 21 25.5H26V27H19V30H27C28.2 30 29 29 29 28V24.5C29 23.5 28.2 22.5 27 22.5H22V21H29V18H21ZM31 18V30H34V25H38V30H41V18H38V22H34V18H31Z" fill="white"/>
</svg>
`

**WP-CLI access**
Manage plugins, update posts and debug errors across all your sites on [WordPress.com](http://wordpress.com/)
`<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M41.25 5.25H6.75C5.92031 5.25 5.25 5.92031 5.25 6.75V41.25C5.25 42.0797 5.92031 42.75 6.75 42.75H41.25C42.0797 42.75 42.75 42.0797 42.75 41.25V6.75C42.75 5.92031 42.0797 5.25 41.25 5.25ZM24.0516 24.2859L15.0516 31.8328C14.8078 32.0391 14.4375 31.8656 14.4375 31.5469V28.6078C14.4375 28.5 14.4891 28.3922 14.5734 28.3219L19.7203 24L14.5734 19.6781C14.5304 19.6441 14.4957 19.6006 14.4721 19.551C14.4485 19.5014 14.4367 19.4471 14.4375 19.3922V16.4531C14.4375 16.1344 14.8078 15.9609 15.0516 16.1672L24.0516 23.7094C24.2344 23.8594 24.2344 24.1359 24.0516 24.2859V24.2859ZM33.5625 31.5469C33.5625 31.7531 33.4031 31.9219 33.2109 31.9219H24.5391C24.3469 31.9219 24.1875 31.7531 24.1875 31.5469V29.2969C24.1875 29.0906 24.3469 28.9219 24.5391 28.9219H33.2109C33.4031 28.9219 33.5625 29.0906 33.5625 29.2969V31.5469Z" fill="white"/>
</svg>
`

**Comment by vindl** [comment]
Thanks! Closing this as completed from a design standpoint. I'll open up a new ticket for dev.
