### ISSUE TITLE
Pattern Assembler: UI/UX polish

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#67645]
#### Description

This issue is to collect the UI/UX feedback of the Pattern Assembler

#### Acceptance Criteria

- [x] https://github.com/Automattic/wp-calypso/issues/67630
- [x] The progress of Pattern Assembler step is wrong https://github.com/Automattic/wp-calypso/pull/67954

#### Dev Tasks

- [x] https://github.com/Automattic/wp-calypso/pull/67638
- [ ] TBD

#### Related

https://github.com/Automattic/wp-calypso/issues/66589

**Comment by autumnfjeld** [comment]
All the items in the issue description are complete. I will close this.   @arthur791004 let me know if that is not the correct action. :)
