### ISSUE TITLE
Marketplace: create saas_landing_page field in WooCommerce.com WP.com Marketplace pane.

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#67655]
In order that user selects a plan for a SaaS product, they need to be redirect to the vendor landing page ( see pdh6GB-1XJ-p2 ). This URL ( `saas_landing_page` ) should be synced in `store_vendor_products` table.

![Image](https://user-images.githubusercontent.com/12430020/189667588-79be9116-5cc1-465f-afc7-ad134338cf2f.png)

**Comment by cpapazoglou** [comment]
Let's try bundling this sync request together with the webhook URL field.

**Comment by JulianBustamante** [comment]
PR created - 14399-gh-Automattic/woocommerce.com

**Comment by JulianBustamante** [comment]
WC.COM PR deployed - 14399-gh-Automattic/woocommerce.com
