### ISSUE TITLE
Marketplace: redirect users in vendor landing page for SaaS products

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#67657]
In https://github.com/Automattic/wp-calypso/issues/67656 we have found a way to have available in Calypso the `saas_landing_page` for every product. 

If `saas_landing_page` exists and has a value, we should

- should a saas friendly plugin details page. 
-- Probably it won't have a price and a billing interval selector. 
-- CTA button copy might need to be adjusted since it will redirect users to the vendor landing page
- CTA button redirects to `saas_landing_page?uuid=[combination of user id and site id]`

**Comment by cpapazoglou** [comment]
@vinimotaa can you help us here? This is an example from WC.com https://woocommerce.com/products/syncee-global-dropshipping/?quid=3f8b266da60dc2967f7b8747c78f1962

**Comment by vinimotaa** [comment]
Hi @cpapazoglou 

This is not clear to me - can you provide more context?

**Comment by cpapazoglou** [comment]
For some plugins that will be defined as SaaS (software as service) the flow will change to:

1. User clicks CTA in plugin details
2. User is redirected to SaaS vendor landing page
3. User selects plan and duration
4. User is redirected back to WordPress.com checkout

In this case we need to 

- Remove pricing - we don't know the price. User selects it in vendor landing page.
- Remove billing interval selector - we don't know the interval. User selects it in vendor landing page.
- Adjust the copy 
-- `Purchase and activate` doesn't seem accurate since they will have to go through the vendor landing page?
--  Maybe we need to add more explanatory copy about us redirecting them to the vendor landing page so they don't get surprised?

**Comment by epeicher** [comment]
Diff created adding a testing product only visible to A11ns D89194-code

**Comment by epeicher** [comment]
The linked PR #68667 and the diff D89194-code will allow using a test product to do all the required changes for other SaaS products

**Comment by epeicher** [comment]
Test Saas Product deployed r253843-wpcom

**Comment by epeicher** [comment]
I am assuming the Business plan is required to install the SaaS plugins, is that correct? If that is the case, should the Business plan price be displayed?

<img src="https://user-images.githubusercontent.com/3519124/195182051-8d6f5383-ba92-4a99-8fbd-c1296d258daa.png" width="300" />

**Comment by vinimotaa** [comment]
Hi everyone - I had a quick pass at this, and I'd like to hear your feedback.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/97929097/195210268-a44b2ce1-0904-45ba-b7c0-acea90d2d768.png">

I designed for two use cases;

**For users below Business Plan**, we can use a secondary color CTA for "plugin activation" and add a "plan upgrade" call to action component+CTA right below. I'd say that both CTA's could trigger the main Plan Upgrade modal window that we're exploring;

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/97929097/195211022-b6a299fe-a953-4444-86fc-89ad20bb2c15.png">

**For users on Business Plan and above**, we would just display the main CTA right on top and hide any irrelevant component - price, toggle, etc.


Let me know your thoughts!

cc; @cpapazoglou @epeicher

**Comment by epeicher** [comment]
Thanks, @vinimotaa for your input. 

Let me summarise my understanding of the different flows to provide some feedback. In the case of the SaaS product, the user will be redirected to the third-party vendor for purchasing. Then, when the purchase is selected, the user will be redirected back to the checkout page with one of those possible scenarios:
- The Saas product plus the Upgrade if the plan is below Business
- Only the Saas product if the pan is in Business or greater

So as I see it we could have just one button that eventually will drive the upgrade if required. My concern is that if we add an _Upgrade to Business_ button the user will be diverted from the original idea of purchasing the SaaS product

**Comment by epeicher** [comment]
As an additional context, let me summarise the current implementations for premium and free plugins and two different suggestions for Saas products, one with two buttons and another one with just one `Getting started`:arrow_upper_right: button

Do you think as an initial iteration we could release (only for A11ns) the version **Saas plugin _One_ button**?

|Site plan|Premium Plugin | Saas plugin _One_ button |  Sas plugin _Two_ buttons  | Free plugin|
|-------|-------|------|------|------|
|**Needs upgrade**|   ![CleanShot 2022-10-14 at 15 13 44@2x](https://user-images.githubusercontent.com/3519124/195870288-c741921d-556d-46b0-b8fe-ac7b3e9fed87.png)       |      ![CleanShot 2022-10-14 at 15 14 00@2x](https://user-images.githubusercontent.com/3519124/195870413-1a965658-85e2-4e38-adbb-f0b126705b41.png)    |   ![CleanShot 2022-10-14 at 16 15 23@2x](https://user-images.githubusercontent.com/3519124/195871662-ef80cba7-3d10-46ad-912f-1c9183373291.png)   |  ![CleanShot 2022-10-14 at 15 17 49@2x](https://user-images.githubusercontent.com/3519124/195870570-330a3a3a-7a78-42eb-86d5-491c7b800d2a.png)   |    
|**Business or greater**|    ![CleanShot 2022-10-14 at 15 14 31@2x](https://user-images.githubusercontent.com/3519124/195870835-c2620d89-22a6-415d-b478-6eda5f41f553.png)      |     ![CleanShot 2022-10-14 at 15 14 17@2x](https://user-images.githubusercontent.com/3519124/195871214-9337dcf6-b92d-4ce7-8c38-0e145db81efc.png)  |  `Same than the left cell`  |     ![CleanShot 2022-10-14 at 15 18 31@2x](https://user-images.githubusercontent.com/3519124/195871329-17b84446-3c26-4918-b9b1-5d069f4253a4.png)     |

**Comment by epeicher** [comment]
An initial version of the changes has been done in the linked PR https://github.com/Automattic/wp-calypso/pull/68667#issue-1398137649. I have added the [two buttons suggestion ](https://github.com/Automattic/wp-calypso/issues/67657#issuecomment-1275358502) but the suggested behaviour will be:
- User clicks on the `Getting started` button: The page will be redirected to the third-party vendor
- User clicks on the `Upgrade to Business` button: The page will be redirected to the checkout page with the business-plan added.

Any feedback please advise, we can use the PR to iterate over changes

**Comment by vinimotaa** [comment]
Hi @epeicher, that seems good for now! Once we have a Plans page defined, ideally, we would redirect users to that page before the check out. For now, let's direct them to check out. Thanks!
