### ISSUE TITLE
Marketplace: add footer with static data to Plugin Details page

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#67663]
Related to pdh6GB-sk-p2 we should add a footer with static text

![Image](https://user-images.githubusercontent.com/12430020/189681589-a90d69cb-d873-4b74-a36b-59006509e8af.png)

We can reuse the component already used in https://wordpress.com/plugins.

@vinimotaa can you provide the copy?

**Comment by epeicher** [comment]
I have created an initial version of the change using the existing component. I have asked a few questions about the differences between the design and the current implementation of the footer in the linked PR https://github.com/Automattic/wp-calypso/pull/67898
