### ISSUE TITLE
Task: Tailored Flows - the flow name should be visible in the loading screen

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#67661]
### Current behavior:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/17054134/189675263-76ba66ec-6283-4f04-8370-2f33b193b56d.png">

### Expected behavior:
![image](https://user-images.githubusercontent.com/17054134/189676080-88cb2d9e-fc57-44c4-9be6-e03f7b76b39b.png)

**Comment by renancarvalho** [comment]
This was fixed by this #67600
