### ISSUE TITLE
LaunchPad - follow up on 'infinite' redirect issue.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67660]
Currently we are band-aid fixing an issue with infinite redirect between launchpad and myhome after disabling the launchpad, however we need to find a way to resolve this for real.  There are still edge cases where we will find a redirect from `MyHome -> LaunchPad -> MyHome` again. One way to see this is to complete the LaunchPad for Newsletters by publishing a post in the editor, exiting to calypso, and then clicking on MyHome:

![redirect-issue](https://user-images.githubusercontent.com/28742426/189673803-0c1844f3-1821-4314-a749-9905e5f8d45f.gif)

Some history:

There is stale data in the myHome side reflecting that launchpad is still active, while the launchpad is getting the fresh updated data that it is not. We are patching this by redirecting from launchpad to myhome with a special query arg to prevent the redirect.  Right now, this param initially prevents the issue when hitting "Launch" from the link-in-bio flow, but there are other edge cases that will still show some redirect flashing as noted above. More info in slack p1662061501596589-slack-C03N25JPCE4

**Comment by jeyip** [comment]
Potential Fix https://github.com/Automattic/wp-calypso/pull/67967
