### ISSUE TITLE
[Invite Follower] Implement new design for desktop and mobile

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#67683]
# What's needed
When the blog owner uses the "invite" functionality to invite a new follower, an email is sent to the invited person. We need to update the look and feel of that invitation email according to this new design: c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A22501

The implementation details of the old version of this email can be found here: PdDOJh-In-p2.

**Comment by mashikag** [comment]
Resolved by: D88300-code
