### ISSUE TITLE
[Invite Role] Implement new design for desktop and mobile

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#67684]
# What's needed
When the blog owner uses the "invite" functionality to invite a new contributor, an email is sent to the invited person. We need to update the look and feel of that invitation email according to this new design: c5bt2O2vWhTlhSREC89Bw2-fi-2658%3A22786

The implementation details of the old version of this email can be found here: PdDOJh-Is-p2

**Comment by sethmclellana8c** [comment]
This ticket might be related to a recent p2 note I passed to the email team (Dinobots): pd0D4C-Zz-p2

When you're in there redesigning the different versions of the invite, can you update the language as well? (I tried viewing the Figma and couldn't get it to work. I'm note sure if the new design would change the language as well.)

**Comment by TimBroddin** [comment]
pd0D4C-Zz-p2#comment-2895
