### ISSUE TITLE
Gutenberg: Double Click after using Block Inserter

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#67694]
### What

After adding a block to the editor, remove the need of double-clicking to access the block's settings.

### Why

You have to click twice to access the block's settings after adding to the editor through the block inserter, the layout also moves on your first click.

### How

To replicate:

1. Click on the + icon from the Block Inserter on the top left
2. Click on a block to add it - you will notice that the Block Inserter won't close
3. Try using an option on the block itself, such as clicking on an alignment option on its toolbar
4. You will notice that the option won't open, instead, the Block Inserter panel closes
5. You have to click on the block's option again to get what you need

Here's an example - after adding the block, you can see that the first click on the option closes the Block Inserter, and the second click that actually opens the block's options:

![block-inserter-double-clicking](https://user-images.githubusercontent.com/16104522/189746747-ce4e2348-8116-4432-a471-0f68987b37fe.gif)

**Comment by annezazu** [comment]
I can't replicate this nor do I see an associated issue in the Gutenberg repo. Closing this out as a result:


https://github.com/user-attachments/assets/4e76c90d-ae82-47ab-8da1-78657c449860
