### ISSUE TITLE
Marketplace: Iterate on domain eligibility warning

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#67695]
Update the domain eligibility warning we show to users before purchasing/installing a plugin on a Simple site, with the new modal here: pdh6GB-26h-p2 All links need to be trackable.

![Image](https://user-images.githubusercontent.com/1689238/189746563-3d797a2f-161d-45c2-9050-628c17764a35.png)

Acceptance criteria:
- [x] Screenshots for all possible warnings have been shared with Design. See paObgF-Mn-p2 for possible warnings. We need to take screenshots of how those look in the Marketplace.
- [x] Implement the new modal design.

**Comment by paulopmt1** [comment]
As part of this issue @allilevine, do we want to improve the current warning (shown in the issue description) for this new one pdh6GB-22x-p2#comment-2878 ?

![image](https://user-images.githubusercontent.com/1044309/190665822-ce289325-976c-4719-9bbe-b91f31c15afd.png)

**Comment by allilevine** [comment]
> As part of this issue @allilevine, do we want to improve the current warning (shown in the issue description) for this new one pdh6GB-22x-p2#comment-2878 ?

Yes, we should actually replace this issue with implementing the new new design here: pdh6GB-26h-p2 I'll update the description.

@vinimotaa Is there a Figma for the new modal design?

**Comment by vinimotaa** [comment]
Figma board [can be found here](https://www.figma.com/file/HOg65lHD0QOfaq0QtzKQbC/Dog-Fooding?node-id=962%3A10389) for now.

**Comment by lsl** [comment]
@paulopmt1, @allilevine suggested to drop the sprint goal flag from this as it's not likely we can ship this in the time we have and it's distracting from the plans page work. We can tackle the modal updates next sprint once we ship the plans page.

**Comment by paulopmt1** [comment]
That sounds good @lsl. In that case @vinimotaa we have more time for your last design adjustments.

**Comment by vinimotaa** [comment]
@lsl I might be wrong, but it seems the modal update is more important than the plans page for this sprint? The modal update was the latest iteration of the plan upgrade work pdh6GB-26h-p2

cc @allilevine @ianstewart

**Comment by paulopmt1** [comment]
New copy to implement: HOg65lHD0QOfaq0QtzKQbC-fi-974%3A10060

**Comment by lsl** [comment]
Planning post here pdh6GB-25m-p2 - domain eligibility was in the backlog but not a focus. Moving to slack. p1664155028405089-slack-C03FE3T479R

**Comment by lsl** [comment]
Broke this down into separate issues see [sprint 31](https://github.com/orgs/Automattic/projects/290/views/20?filterQuery=team%3AExplorers+sprint%3A%22Sprint+31%22).
