### ISSUE TITLE
Marketplace: Direct nudge clicks to new Plans page

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#67693]
Upgrade nudges in the Marketplace should link to the new Plans page: https://github.com/Automattic/wp-calypso/issues/67574

From the Plans page they should go directly to checkout.

Acceptance criteria:
- [x] The upgrade nudges  on /plugins link to the new Plans page we've created.
- [x] Choosing a plan on the Plans page takes the user to checkout (no domain eligibility since we're not installing a plugin).

**Comment by DustyReagan** [comment]
I understand why we want to link the upgrade nudge to the new plans page, but for a future A/B test, it might be worth comparing the conversion rate of this change to the current conversion rate of linking to the shopping cart directly. I'm wondering if someone has clicked "Upgrade to the Business plan to install plugins. -- Upgrade now" maybe they don't need anymore convincing?

**Comment by allilevine** [comment]
> I understand why we want to link the upgrade nudge to the new plans page, but for a future A/B test, it might be worth comparing the conversion rate of this change to the current conversion rate of linking to the shopping cart directly. I'm wondering if someone has clicked "Upgrade to the Business plan to install plugins. -- Upgrade now" maybe they don't need anymore convincing?

@DustyReagan That's a good point, it may not be as relevant here. Let's track conversions before and after the change, and revert if needed.

**Comment by allilevine** [comment]
@DustyReagan Should we close this one for now, since https://github.com/Automattic/wp-calypso/pull/67829 was merged?
