### ISSUE TITLE
Premium Theme: Varese

### ISSUE THREAD

**Issue by onuro** [Automattic/wp-calypso#67703]
### Details

The Varese premium theme needs the following:

### Checklist

- [x] [Theme Demo site](https://varesedemo.wordpress.com/) set up
- [x] Theme showcase page draft.
- [x] [Headstart annotations (guide: paYKcK-1Pt-p2)] (Strand id: `139259`)
- [x] [GlotPress project (guide: paYKcK-1Pt-p2)]
- [x] [Launch process (launch guide: PNEWy-eBM-p2)]

**Comment by markbiek** [comment]
@onuro I noticed that all of the [Posts](https://varesedemo.wordpress.com/wp-admin/edit.php) on the demo site were created using the Classic editor.

I've converted them to blocks but can you please make a note to only use the Block editor in the future? Our tools can only create the Headstart annotation from blocks.

It also seems like there's some stale Jetpack testimonial data in the site database somehow, even though Jetpack isn't installed. I'll be skipping that for now.

**Comment by markbiek** [comment]
@onuro I also wanted to note that, while the homepage of the demo site is restaurant related, all of the posts are about yoga. 

My assumption is those are old data so I'm leaving them out of the Headstart file.

**Comment by markbiek** [comment]
Launched!
