### ISSUE TITLE
Page Layouts Preview Error on Zoologist Theme

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#67708]
### Quick summary

Page layouts show the following error instead of the layout preview image: `{﻿"error":"no-site","message":"No demo site found."}`. 

### Steps to reproduce

1. Activate the Zoologist theme.
2. Go to Pages → Add New to trigger Page Layouts window.

### What you expected to happen

I expected to see previews of all the layouts.

### What actually happened

The previews appear to be broken and instead display the error `{﻿"error":"no-site","message":"No demo site found."}`

![image](https://user-images.githubusercontent.com/30727666/189797816-3e6dce71-2bb6-4d12-932e-295c60743831.png)

### Context

#36895498-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Occurs on Zoologist theme, but not on its parent (Blockbase) or other child themes (I checked Geologist and Russel.)

### Reproducibility

Consistent

### Severity

All

**Comment by inaikem** [comment]
Further context:

- p1663032920668219-slack-C0160HSMDQV
- p1662956039686129-slack-CRWCHQGUB

Marking as triaged.

**Comment by autumnfjeld** [comment]
Possibly related: 
the demo link on in the theme showcase is pointing to the wrong demo site https://wordpress.com/theme/zoologist/fieldguide.automattic.com .  I've asked if someone from theme team look into this. p1663043532684419/1662957106.832429-slack-C029FM1EH

**Comment by arthur791004** [comment]
According to p1663047029438769/1662956039.686129-slack-CRWCHQGUB, we have fixed the issue for the English users. For non-English users, we need to wait for the mShots cache to expire

**Comment by arthur791004** [comment]
According to p1663047029438769/1662956039.686129-slack-CRWCHQGUB, we have fixed the issue for the English users. For non-English users, we need to wait for the mShots cache to expire

**Comment by arthur791004** [comment]
@donalirl I thought this issue has been resolved, could you help to confirm again? thanks!

**Comment by donalirl** [comment]
@arthur791004 Yes, I can no longer recreate the issue. The layout previews show up for me:
![image](https://user-images.githubusercontent.com/30727666/192404164-45e7ddef-49ce-4fa5-ba5f-96f065ec465a.png)

**Comment by arthur791004** [comment]
Great! Let's close this issue 👍
