### ISSUE TITLE
Purchases: Update cancellation copy for plans

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#6770]
From p2MSmN-4YT-p2:

Here is what happens when a user cancels a plan with a bundled domain:

- We unbundle the domain, leaving it on the user's account.
- We remove the plan subscription.
- If eligible for a refund, we refund the user the price of the plan minus the price of the domain.

The issue is that the copy in the Confirm Cancellation step doesn't describe what happens to the domain. See:

<img width="450" alt="ifnwgxfr2u-900x900" src="https://cloud.githubusercontent.com/assets/1248436/16836918/7585c1f6-49c0-11e6-8e95-4f20eb226ffe.png">

@ranh suggested we update the copy to the following:

> This plan includes the custom domain mapping for example.com, normally a $ X purchase. The domain will not be removed along with the plan, to avoid any interruptions for your visitors.

> You will receive a partial refund of $ X, which is $ X for the plan minus $ X for the domain mapping. To cancel the domain mapping with the plan and ask for a full refund, please contact support.

Note that the second part of the copy needs to change depending on either the user has a mapping or a registration. 

@ranh the issue here is that it's not possible to get the refund for the unbundled domain right now, due to T431-code. <s>Should we update that with instructions to contact support for now? </s> We did.

**Comment by ranh** [comment]
> Should we update that with instructions to contact support for now?

A go at that:

> You will receive a partial refund of $ X, which is $ X for the plan minus $ X for the domain mapping. To cancel the domain mapping with the plan and ask for a full refund, please contact support.

This could replace the existing link to "ask a happiness engineer".

**Comment by fabianapsimoes** [comment]
Thanks, @ranh!

Seems @scruffian and @janm6k are looking into possibly fixing the issue in T431-code. I'll wait a bit before prioritizing this change, in case we can go with your first suggestion already.

**Comment by fabianapsimoes** [comment]
As per p1469091300000003-upgrades-slack, seems the fix for T431 isn't trivial so we'll go ahead with this fix and the second suggestion. I've updated the description with the final copy.
