### ISSUE TITLE
Marketplace: Add new `provision_license` webhook

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#67715]
### Details

In order to automatically configure a license on the vendor's backend, we should introduce a new webhook command called `provision_license` that would be triggered after the software installation is finished.

This new command will make a request on the vendor side to obtain a new license key for a newly created purchase. The vendor would then need to respond with a valid license information.

With the license information received from the vendor response, will be then need to pass it to the Atomic site.

### Checklist
- [ ] Implement a new webhook called provision_license

**Comment by obenland** [comment]
Could we re-use the `subscription_created` webhook and extend it to also accept a license information response?

**Comment by obenland** [comment]
See p1663948743130249-slack-C029JEQRVRT for discussion on reusing `subscription_created`

**Comment by BogdanUngureanu** [comment]
Authorization header diff is ready for review in D87893-code

Adding the provision_license webhook is in D88919-code. The code changes are ready but I haven't manually tested it or added the testing instructions.

**Comment by BogdanUngureanu** [comment]
D88919-code is now RfR.
