### ISSUE TITLE
Marketplace: Don't hide installed plugins on category / discover pages

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#67712]
When I install a plugin and then go back to the marketplace I should see that my plugin was installed, I shouldn't see that the plugin disappeared.

- [ ] Don't hide installed plugins from category browse pages
- [ ] ~Don't hide installed plugins from discover page sections~ [not required](https://github.com/Automattic/wp-calypso/issues/67712#issuecomment-1266533963)

I think we did this to not "use up" a plugin slot but I'm not really sure this makes sense and it makes for a confusing user experience.

**Comment by lsl** [comment]
@cpapazoglou / @vinimotaa see any issues with this change?

**Comment by cpapazoglou** [comment]
The original idea is that this way:

- Marketplace landing page **Discover** has always fresh content
- There is no reason marketing an installed plugin in the Marketplace landing page **Discover**

I agree though, that in any other case like **Category** pages and **Search Results**, installed plugins should appear.

**Comment by lsl** [comment]
Search results I think it does, but category browse pages are hidden like on the discover screen (I think they're the same component with extended limits).

**Comment by cpapazoglou** [comment]
Seems working as expected



![Image](https://user-images.githubusercontent.com/12430020/211558957-61fd9532-5d6d-4596-9ef7-9328c1617c25.png)
