### ISSUE TITLE
Pattern Assembler: Show "Start with a blank canvas" CTA only for write and build flow

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#67713]
#### Description

pbxlJb-2ki-p2 mentioned, “As a user in the build or write onboarding flows, when I reach the Design Picker step, I will see a CTA to select the blank canvas option.” So, the “Start with a blank canvas” CTA should only show for the write and build flow

#### Acceptance Criteria
- [x] The “Start with a blank canvas” CTA should only show for the build ~and write~ flow. (see convo p1663316142361469-slack-CRWCHQGUB

#### Dev Tasks

- [x] https://github.com/Automattic/wp-calypso/pull/67729
- [x] https://github.com/Automattic/wp-calypso/pull/67803

#### Related

pbxlJb-2ki-p2

**Comment by arthur791004** [comment]
Close it as it's shipped 🚢

**Comment by autumnfjeld** [comment]
Just updated issue description .  The PA will only go in the build flow p1663316142361469-slack-CRWCHQGUB
