### ISSUE TITLE
[All] Update footer font style

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#67725]
Set font size to 14px at 150% (or 21px) line-height as seen on updated Figma: c5bt2O2vWhTlhSREC89Bw2-fi-3690%3A16676.

Context: p1663061857007299/1663053451.007569-slack-CRNF6A9DX

**Comment by phcp** [comment]
The footer font size is currently 16px, so I guess it should be set to 14px as it is in the updated Figma.

![Image](https://user-images.githubusercontent.com/3113712/189907566-225bcde9-9714-49ac-906f-7808f745fcd3.png)

**Comment by ivan-ottinger** [comment]
That's a good point. I think that was a typo and it should be 14px as you say. → I will fix this in the issue description,

Btw, the patch is almost ready for review. :)

**Comment by ivan-ottinger** [comment]
D87624-code is now ready for review.

**Comment by ivan-ottinger** [comment]
D87624-code is now merged and deployed.
