### ISSUE TITLE
Link in Bio page title wrongly translated

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#67732]
When in the link in bio flow, I see the page title truncated when not in English (I tried in Italian)

![image](https://user-images.githubusercontent.com/52076348/189886732-ab428ac7-36d4-44dd-8dd0-8157868761e8.png)

**Comment by cuemarie** [comment]
Seems this was fixed in https://github.com/Automattic/wp-calypso/pull/67753

Checked flow in french, look good:
![Markup on 2023-05-03 at 11:30:53](https://user-images.githubusercontent.com/27249804/236010716-b8a8ed27-594d-428a-be10-c92cb78fef89.png)
