### ISSUE TITLE
Marketplace: Custom domain dialog button too wide

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#67745]
The Custom domain dialog displays the plugin name in the Install button, for example `Install Yoast SEO` but for other plugins with long names, the button grows too wide, examples below:

|Correct for some plugins | Ugly for some other plugins|
|-------|------|
|<img width="467" alt="CleanShot 2022-09-13 at 16 42 27@2x" src="https://user-images.githubusercontent.com/3519124/189931578-d86a11be-bccc-479c-baa7-03e8fff9e58d.png">|<img width="903" alt="CleanShot 2022-09-13 at 16 43 17@2x" src="https://user-images.githubusercontent.com/3519124/189931807-bfd058f8-5de6-4de1-b16c-0cd26a54c9a8.png">|
|<img width="463" alt="CleanShot 2022-09-13 at 16 41 36@2x" src="https://user-images.githubusercontent.com/3519124/189931635-a084da0c-56ea-47c1-a4f9-5caabef1f594.png">|<img width="825" alt="CleanShot 2022-09-13 at 16 44 17@2x" src="https://user-images.githubusercontent.com/3519124/189932065-42e7efbb-029a-4ac5-b195-f5f09c72fc9c.png">|

An alternative could be changing the text to a fixed message like `Install Plugin`

**Comment by cpapazoglou** [comment]
Or we could set a `max-length` and `overflow: hidden;` `text-overflow: ellipsis;`
