### ISSUE TITLE
Hosting Config: Only show clear cache reason modal every 24 hours

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#67749]
When a user is allowed to clear cache on an Atomic site (p7DVsv-8uo-p2), they see a modal every time they click the button:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/36432/189945478-e426efd7-0d7a-4f40-8d80-c7920015c2ec.png">

Some user feedback I received at WCUS 2022:
> Every time you want to clear the cache, there's a popup that requires you to enter a reason why you want to clear the cache. We obviously try to keep cache clearing to a minimum, but when doing certain types of work, we may need to clear it a few times, and this gets really tedious. 

Let's only show the modal every 24 hours instead.

**Done is:**
* After the user has completed the modal once, they only see it every 24 hours.

**Comment by bazza** [comment]
Is anyone looking at these reasons?  If not, we probably don't need to collect them.  The intention was to review them to identify bugs, but if we aren't actually doing that then why do we need to ask?

**Comment by zaguiini** [comment]
@bazza well, having some analytics stored won't hurt as if we ever want to use that data (if we're not doing that already), we'll have it. Plus, the user having to explain before taking such a destructive action (that will take more resources from our servers) might slow down the user and prevent them from actually taking the action. This could be potentially beneficial for us.

**Comment by danielbachhuber** [comment]
@bazza Not to my knowledge. I'll look into it, and report to P2.
