### ISSUE TITLE
Themes: Add free/premium/all buttons to search bar

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#6774]
Replacing the existing dropdown.

**Old**
![screen shot 2016-07-14 at 12 50 39](https://cloud.githubusercontent.com/assets/7767559/16838914/f35359a6-49c3-11e6-9257-8a54ec656d40.png)

**New**
![screen shot 2016-07-14 at 13 07 58](https://cloud.githubusercontent.com/assets/7767559/16838940/0da95db4-49c4-11e6-844e-81d8a28d1585.png)

**Comment by ockham** [comment]
Maybe use [SegmentedControl](https://wpcalypso.wordpress.com/devdocs/design/segmented-control) to implement.

**Comment by ockham** [comment]
(plus maybe [SectionNav](https://wpcalypso.wordpress.com/devdocs/design/section-nav))
