### ISSUE TITLE
[Invite Follower] Add tracking parameters to new template

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#67741]
**Note:** This task depends on [this one](https://github.com/Automattic/wp-calypso/issues/67683)

We need to add the data-tracks-link-desc attribute to all the links in this email new template. The values of those link descriptions are as follows:

![Image](https://user-images.githubusercontent.com/3832570/189926407-baf11aa5-cac2-4c59-83e6-2b2b48336e90.png)

You can find more information about this email here: PdDOJh-In-p2.

**Comment by TimBroddin** [comment]
The plain link in the _Trouble clicking_ section isn't clickable, so we shouldn't add it there.
