### ISSUE TITLE
Themes: Parse `key:value` syntax in the search box

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#6775]
Parse queries such as:
```
subject: business
color: blue
feature: custom-background
```

And convert to a filter query using new `filter` API arg from #6603

**Comment by folletto** [comment]
Are we thinking something like `([a-zA-Z0-9]+\:\s*[a-zA-Z0-9-_]+)`?

[![screen shot 2016-07-14 at 13 33 40](https://cloud.githubusercontent.com/assets/4389/16839562/a2487420-49c7-11e6-8b65-6284a23f5bc0.png)](https://regex101.com/#javascript)

**Comment by seear** [comment]
i18n is something we need to consider.

**Comment by folletto** [comment]
Good point. Can we keep the underlying logic/terms in a single language (url, too) and translate only the associated label?

Not sure the tradeoff balance in having translated URLs too, and if it breaks canonical stuff. Probably something to review later once we have the sheets properly translated (different language canonical at that point?)

**Comment by ockham** [comment]
Uh, wouldn't it be easier without the spaces, i.e. `subject:business` or `feature:custom-background`? Google does it that way, doesn't it? (`site:wordpress.com`, `ref:wordpress.com` etc)

**Comment by ockham** [comment]
If yes, we could do with something as simple as

```js
searchString.split( ' ' ).map( part => part.split( ':' ) )
```
(or close)

**Comment by seear** [comment]
> If yes, we could do with something as simple as
searchString.split( ' ' ).map( part => part.split( ':' ) )
(or close)

This is really an implementation detail, so the discussion would probably be better in the PR, but the same regex is also being used to strip all the filters out of the search box content to leave the search string intact, which a call to `split()` won't accomplish: 
https://github.com/Automattic/wp-calypso/pull/6860/files#diff-da85ecea81ed7dcf86097e6d06009d88R53

So we can do the parsing, the capturing of the value part, and the stripping of the filters, all with one simple regex. Allowing spaces after the colon comes for free.

**Comment by seear** [comment]
> ([a-zA-Z0-9]+\:\s*[a-zA-Z0-9-_]+)

And actually we can make it even simpler by using the `\w` character class, which is equivalent to `[A-Za-z0-9_]`, leaving us with:

`/\w+\:\s*(\w+)/g`

**Comment by folletto** [comment]
> If yes, we could do with something as simple as

In these scenarios I'm often edging to go for Regex even if it's simpler, because it allows more fine-grained control that can be then ported and tested easily. I won't be agains a pure JS parser, so consider this a preference on my side.

So:

> easier without the spaces

Yes, would be easier to implement. This is for me more a choice if we want to be more forgiving when a user types, or not. Allowing the space in between seems making sense to me, but maybe there's some case I'm not considering, or maybe it's not really solving an issue and I'm just being too defensive in that code. :)
