### ISSUE TITLE
[All] Fix font-weight on email footer

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#67757]
The current implementation has some of the footer texts wrapped with `strong` tag, for these ones the `font-weight` is inconsistent with the others that uses `span class="title"`. On both cases the `font-weight` should be 600, as it is on Figma.

![Image](https://user-images.githubusercontent.com/3113712/189976686-765ae99f-559b-473b-b44d-cdd1d50da8e8.png)

**Comment by ivan-ottinger** [comment]
We have deployed the D87656-code patch that fixes the issue..
