### ISSUE TITLE
Unified Design Picker: Themes with Atomic Demo Sites fail to preview if sandboxed

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#67768]
* Have public-api sandboxed
* Visit `/start` on the wpcalypso environment
* Get to the design picker
* Choose thriving artist (This theme has an atomic demo site)
* When the preview loads, your browser is staring at an error

**Before loading**
![2022-09-13_16-55](https://user-images.githubusercontent.com/937354/190018913-345c1c66-f070-49e3-9bdf-2944c6419cff.png)

**After loading**
![2022-09-13_16-56](https://user-images.githubusercontent.com/937354/190019111-a6f441b4-7099-4ed1-82d9-884ef323940b.png)

This is essentially the same problem as #66738.

```
wp-content/rest-api-plugins/endpoints/block-previews/block-previews-site.php
$theme_demo_content = $this->get_theme_demo_content( $theme_demo_site_id, $language );
```

```
wp-content/rest-api-plugins/endpoints/block-previews/block-previews.php
$theme_demo_content_response = Template_Helpers::get_instance()->get_demo_content(
```

```
wp-content/lib/nux-helpers/class-template-helpers.php
return wpcom_sandbox_pseudo_remote_get( $site_id, $query_args );
```

```
wp-content/lib/nux-helpers/sandbox-pseudo-remote-get.php
Observe $cmd. It has the wrong domain (non-atomic), and if you fix it, the command doesn't work anyway. (Sunrise error "Error: the domain you requested can not be served at this time.").
```

**Comment by blackjackkent** [comment]
Closed by D88228-code
