### ISSUE TITLE
Pattern Assembler - Page template for headstarting the site

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#67780]
We must use a page template when headstaring the site with the patterns chosen in the PA. There are some issues and limitations when using the page templates available:

- `Blank` doesn't include the header or footer, so it can be used for content only. No header or footer will be shown in the site editor, which is confusing because we show the default footer (Simple Centered Footer) in the PA preview.
- `Footer only` doesn't include the header, so it could be used for the footer and content only. There is an issue running headstart with this page template because the footer_pattern_ids are ignored. We'll have to debug it and fix the issue if we want to use this template.
- `Header and Footer only` include header, footer, and content. We could use this page template for all cases, but there is an issue when the header is not chosen in the PA, the default header (Simple Header with Tagline) will be used by default and shown in the site editor, which leads to confusion because it is not shown in the PA preview.

### Acceptance criteria

- [ ] Avoid confusion and make the concept of “page/site building” clear to a new user. 
- [ ] Use the page template `Header and Footer only` for all cases because the site must have a header and footer
- [ ] Guide the user to choose a header, one content, and a footer to be able to `Continue`. How can we guide users to "force" them to choose patterns? Show a message when they click on `Continue`? Disable the button and show a tooltip until the patterns are selected? Any other UX?
- [ ] ~If the user doesn't choose a header/footer, show the default header/footer in the PA preview.~
- [ ] Update the copy “Kick start the content on your page by picking patterns. First choose a header for your page layout, then choose at least one section pattern, and finally choose your footer.”

[Slack convo](p1663047632213009-slack-CRWCHQGUB)
Related to [#67498](https://github.com/Automattic/wp-calypso/pull/67498)

**Comment by autumnfjeld** [comment]
![image](https://user-images.githubusercontent.com/5665959/190064373-953c9360-444e-4920-989b-3da304c5bd9f.png)
That is in conflict with the point above it.

**Comment by autumnfjeld** [comment]
@mtias flagging this with you in case you have strong opinions.  See Miguel's description above. :)

**Comment by autumnfjeld** [comment]
cc: @Automattic/ganon

**Comment by mtias** [comment]
I do have a strong opinion! :) This flow is precisely about the user creating its own template, so we shouldn't be using any predefined one. We should be creating a new template specific to what the user wants to do and saving it as a customized template on their site.
