### ISSUE TITLE
Getting Started documentation: `make run` requires users to manually add git pre-commit hook

### ISSUE THREAD

**Issue by aminimalanimal** [Automattic/wp-calypso#678]
Either the project needs to include a `pre-commit` file within `.git/hooks/` or the documentation should be updated to walk the user through this process before telling them to run `make run`.

As is, attempting to run the project for the first time requires the user to debug and manually add (and make executable) this missing prerequisite.

**Comment by dharamgollapudi** [comment]
@aminimalanimal `githooks-commit` task of the Makefil, which is a pre-requisite of `run` task takes care of symlinking the pre-commit hook https://github.com/Automattic/wp-calypso/blob/master/Makefile#L140

**Comment by philwong** [comment]
How this can be fixed manually?

**Comment by klimeryk** [comment]
I've tested this now, and it's like @dharamgollapudi mentioned - the `pre-commit` hook is added as part of `make run` ([see `Makefile`](https://github.com/Automattic/wp-calypso/blob/master/Makefile#L77)).

If you need to re-add the hooks, you can do so by running:
* `make githooks` - sets up `pre-commit` and `pre-push` hooks.
* `make githooks-commit` or `make githooks-push` if you just want the `pre-commit` or `pre-push` hooks respectively.

These commands just link the hooks (that reside in `bin/`) to `.git/hooks`, so you can do so manually by executing `ln -s ../../bin/pre-commit .git/hooks/pre-commit` in the root of the project. But it's better to use `make` for it, that's what it's there for :)

Hope this helps!
