### ISSUE TITLE
Domain Selection: hover state of the domain selection step looks cut off on the sides for non-featured domains

### ISSUE THREAD

**Issue by heavyweight** [Automattic/wp-calypso#67811]
<img width="1427" alt="Screenshot 2022-09-14 at 15 04 41" src="https://user-images.githubusercontent.com/7000684/190161834-f0b87c79-f78f-496f-9408-534507e22bcb.png">

https://user-images.githubusercontent.com/3392497/190159113-3836a635-c8a8-4693-828d-d57cca515d5f.mov

**Comment by klimeryk** [comment]
FYI, I've tested this in regular `/start` flow and it's present there, so it's not specifically linked to the Newsletter flow (where I originally spotted it in https://github.com/Automattic/wp-calypso/pull/67665#pullrequestreview-1107426117

**Comment by heavyweight** [comment]
p1663337658990939-slack-C02T4NVL4JJ
