### ISSUE TITLE
Tailored Flows: Description field has visible scrollbar

### ISSUE THREAD

**Issue by heavyweight** [Automattic/wp-calypso#67810]
Win10 and Firefox

<img width="1919" alt="Screenshot 2022-09-14 at 15 01 37" src="https://user-images.githubusercontent.com/7000684/190161468-37c66c7b-fec3-4311-ae3a-5c161368a921.png">

**Comment by escapemanuele** [comment]
Hey @heavyweight, is this still actual? I tried testing on Firefox in Windows but couldn't replicate!

If it is, please tell me how you tested this

![image](https://user-images.githubusercontent.com/52076348/190618112-dc2f9c28-c130-4ae7-979f-bb77385dba88.png)

**Comment by heavyweight** [comment]
Can't reproduce it anymore
