### ISSUE TITLE
Plans: plans cards too tight to the top

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#6782]
In the pending plans page redesign the plans cards don't have enough margin/padding on the top when the "popular" banner is shown.

## Plans Page
![plans page](https://cloudup.com/cOV0dnqehPZ+)

## NUX
![nux](https://cloudup.com/c0FCbCmMGqf+)

/cc @lamosty

**Comment by rralian** [comment]
can you grab this one too?

**Comment by lamosty** [comment]
> can you grab this one too?

Yes. However, @artpi is working on different popular plan badge in #6793. It looks like this:

![selection_059](https://cloud.githubusercontent.com/assets/4988512/16870970/9f966012-4a84-11e6-872d-dcb2197106d8.png)

![selection_061](https://cloud.githubusercontent.com/assets/4988512/16871111/3ce3cb16-4a85-11e6-9658-f1009a4eebaf.png)

**Comment by rralian** [comment]
Agreed, probably makes sense to just tackle it in his PR. I'll close this one.
