### ISSUE TITLE
LaunchPad - Checklist API Refactor discussion reminder

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67820]
A reminder that we need to discuss / p2 / decide about refactoring the checklist API and launchpad to utilize it.

We should decide about this soon as it will be much more difficult later down the road.

**Comment by mattwiebe** [comment]
@Addison-Stavlo can you point me to more of the context around the needed discussion?

**Comment by Addison-Stavlo** [comment]
paYE8P-28d-p2 for the discussion.

My apologies I missed your ping @mattwiebe !  I was letting Erick handle kickstarting this post since he has a good chance to dig into these items while you were on sabbatical.
