### ISSUE TITLE
Launchpad: Add unit tests for Sidebar

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#67823]
### What

Add unit tests for the sidebar component, akin to the [launchpad checklist-item](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/checklist-item.tsx)

### Why

The sidebar has dynamic behavior that we'd like to test, partly because, if subject to refactoring, we'll want the reassurance of unit tests, and also because it's a critical piece of launchpad functionality.

**Comment by agrullon95** [comment]
Changes merged: https://github.com/Automattic/wp-calypso/pull/68537
