### ISSUE TITLE
Themes: Style key:value search strings

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#6783]
Style the `key:value` strings from #6775 as they are typed in. Possibly using [TokenField](https://href.li/?https://wpcalypso.wordpress.com/devdocs/design/token-fields) component.

![screen shot 2016-07-14 at 13 31 53](https://cloud.githubusercontent.com/assets/7767559/16844737/221dd1b6-49de-11e6-908b-85f48e6e17f6.png)

**Comment by ockham** [comment]
> Possibly using [TokenField](https://href.li/?https://wpcalypso.wordpress.com/devdocs/design/token-fields) component.

Curious to hear your thoughts on this @mtias

**Comment by mtias** [comment]
We probably want to extract a `Token` component [from this sub-component](https://github.com/Automattic/wp-calypso/blob/master/client/components/token-field/token.jsx); token field and the theme search would use it.

Not sure token-field itself makes sense here? It depends on what interactions you expect.

**Comment by seear** [comment]
Possible we could iterate on this: start by using token-field and having the _key:value_ bit all one color, then go from there.

**Comment by ockham** [comment]
Closed by #8475.
