### ISSUE TITLE
Guided Tours: Guarantee a tour's completion before selecting another

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#6785]
#6417 introduced a substantial change in how Guided Tours works — namely, how it decides to show a tour based on all sorts of triggers. It now needs an addendum which formally ensures that it never switches from tour A to tour B mid-flight. In short:

``` diff
 export const findEligibleTour = createSelector(
-   state => findRequestedTour( state ) || findTriggeredTour( state ),
+   state => findOngoingTour( state ) || findRequestedTour( state ) || findTriggeredTour( state ),
    [ getActionLog, getToursHistory ]
 );
```

This isn't yet an issue because the current situation is particular:
- our production tour `main`  has a `context` that is always `false`, meaning it can only be requested via query arguments, i.e. `?tour=main`;
- as seen in the snippet above, requested tours take precedence over the rest.

As soon as we switch from explicitly requesting `main` to letting GT _decide_ to show it based on triggers, the following becomes an issue:
1. Navigate to Calypso (anywhere), and let's assume GT starts the `main` tour
2. While following the tour, navigate to Themes, even though that isn't requested in the tour yet
3. That act of navigating to Themes has added an item to `state.ui.actionLog` which will inform GT. Because GT considers the most recent triggers first, it will suddenly decide that `themes` is the tour that should be shown.
4. Result: the user is unexpectedly taken from tour `main` to `themes`

**Comment by lsinger** [comment]
@mcsf is this maybe solved by the new tour selection mechanism (`relevantFeatures` et al.)?

**Comment by mcsf** [comment]
I'll have to have a better look, but I'd feel better having a mechanism that's specific and explicit[^1] for this purpose, rather than trusting a different piece which may change in the future and introduce breakage.

[^1]: like the snippet in the issue description
