### ISSUE TITLE
Add additional verticals to the verticals drop down

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#67854]
# Description

![Image](https://user-images.githubusercontent.com/5665959/190381532-b28f7134-9353-41a2-87d9-6148f79e5068.png)

![Image](https://user-images.githubusercontent.com/5665959/193503320-65ff9526-f2f7-4cce-b34d-3ca354f86b62.png)

This analysis of user selection of industry verticals pbxlJb-2pM-p2 shows that the top 10 selected verticals are EXACTLY THE SAME as the ones in the drop down list--with the exception of "Arts & Entertainment" bumping "Travel Agencies & Services" out of the top 10.    I think we are influencing users.  I'd like to update the list and include more verticals and then check the metrics.

HYPOTHESIS:  the verticals we suggest in the drop down list will always be the top selected verticals.

All the verticals in the list should be supported/whitelisted (so may need to whitelist these, ensure there are images.

### New verticals:

1. Science
2. Fashion & Style
3. Real Estate
4. Sports
5. Home & Garden
6. Pets & Animals

# Dev Tasks
- [x] update the list to show 16 verticals per the new ones above
  - [x] D89106-code
  - [x] https://github.com/Automattic/wp-calypso/pull/68697
  - [x] https://github.com/Automattic/wp-calypso/pull/68698
- [x] We should have images for the six verticals @autumnfjeld can add images, or I think we might be able to use existing 
- [x] Add entry to Ship table
- [x] Follow up with metrics check in a week to see if top 16 verticals matches the updated dropdown list

# References
* pbxlJb-2pM-p2
* code
  * vertical-store.php wpcom/wp-content/lib/verticals/vertical-store.php?r=a7dbfe5f

# Testing
*  Go to wordpress.com/start
* Confirm additional verticals are showing
* Ping @autumnfjeld for testing

**Comment by autumnfjeld** [comment]
@Automattic/ganon  Moving this to top of Ready for Dev.    I was debating to update the list to 15/16 verticals or maybe more, like 20.  Anyone have any opinions on this?

**Comment by arthur791004** [comment]
I think 15/16 verticals are enough, and we could increase to 20 later if we want 🙂

Here is the image count of each vertical. I think we might need to add more images to the `Fashion & Style` vertical as it only has 8 images and the others are from its parent vertical.
| Vertical | Image Count |
| - | - |
| Science | 14 |
| Fashion & Style | 15 (7 of them are from its parent vertical) |
| Real Estate | 13 |
| Sports | 19 |
| Home & Garden | 14 |
| Pets & Animals | 17 |

> I think we are influencing users.

I think we could also shuffle the top verticals to eliminate the influence of the order, what do you think?

**Comment by autumnfjeld** [comment]
> I think we could also shuffle the top verticals to eliminate the influence of the order, what do you think?

Great idea!!!  

I'll add more Fashion images.

**Comment by autumnfjeld** [comment]
And just double checking , these six verticals area already whitelisted because they are top level verticals ya? Oh except Fashion & Style is not top level.

**Comment by taipeicoder** [comment]
We should also add this to the FTME Change Log / Ship Table.

**Comment by arthur791004** [comment]
Shipped and [added to the Ship Table](pbAok1-2MG-p2#comment-5590)! We could follow up with metrics next week

**Comment by autumnfjeld** [comment]
Are you volunteering to follow up? 😃  Then you post a comment to pbxlJb-2pM-p2.   Simple check in tracks trends that I am guessing will show these 16 are now the top.   

![bitmoji](https://sdk.bitmoji.com/render/panel/e6518353-71e9-41b7-9208-fde8f676bf08-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=66)

**Comment by arthur791004** [comment]
Sure!

**Comment by arthur791004** [comment]
Post a comment pbxlJb-2pM-p2#comment-1923 to show the metrics with newly added 6 verticals 🙂

**Comment by arthur791004** [comment]
Close as it's completed
