### ISSUE TITLE
Pattern Assembler - Remove predefined footer from Blank canvas theme

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#67856]
When using the default template `Footer Only`, the theme Blank canvas includes the footer `footer-with-site-title`. This is expected, this is how we present the [Blank Canvas theme](https://wordpress.org/themes/blank-canvas/).

![Image](https://user-images.githubusercontent.com/1881481/190363811-61f248ea-c00d-46fa-8c1a-1e8863b58ed3.png)

However, for the Pattern Assembler flow, we shouldn't use any predefined footer. The user should choose the patterns, preview them, and continue to see the final result in the site editor. 

In this first iteration, we use the REST API `/blocks-preview/site` to preview the patterns selected by the user. We could remove the footer from the preview by passing a param in the URL. However, the footer would still appear on the site because it is included in the default template `Footer Only`. We can create a template `Header Only` to solve this case.

- Footer only selected (plus content) -> use the template `Footer Only`
- Header only selected (plus content) -> use a new template `Header Only` 
- Only content selected -> use the template `Blank` 

**Can we create a new template `Header Only` in the Blank canvas theme?** 

It would be added in a folder `template/`, with the name `header-only.html` and the file content:
```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:post-content {"layout":{"inherit":true}} /-->
```

I'm not sure if we have to add the template part `header.html` in the folder `block-template-parts` as in [here](https://github.com/Automattic/themes/blob/trunk/geologist/block-template-parts/header.html).

We did something similar in this [PR](https://github.com/Automattic/themes/pull/5103/files) to add the template `Footer Only` to the theme `Blockbase`.

**Comment by arthur791004** [comment]
I'm not sure but it might be acceptable as we want to show the credit footer such as “Proudly powered by WordPress.” 🤔

**Comment by autumnfjeld** [comment]
Related to this: 

I just went to try to remove the footer credit on a free site via the customizer
<img width="293" alt="image" src="https://user-images.githubusercontent.com/5665959/190541081-e4888911-3693-4dca-b8b7-40845dfa570b.png">
It is not possible via the customizer.

But on the same site, via the Site-Template Editor, I can delete the footer text.

**Comment by autumnfjeld** [comment]
Getting input on how the footer credit should work: p1663295644661609-slack-CRNF6A9DX

**Comment by autumnfjeld** [comment]
@Automattic/ganon  I think we can consider this issue resolved. Correct?

See slack convo: p1663336130002809/1663295644.661609-slack-CRNF6A9DX

We will accept @Addison-Stavlo 's #3 point:

> 3 - Why not just get rid of footer credits altogether and use the banners for free sites?
>- From a technical side this seems much more maintainable and easier to implement than locking footers and removing html editors. It would free up any conflicts that might arise from injecting footer credits on non-FSE sites. It would free up any concerns around how we interact with themes/designs with specific footers or no footers (like LIB).
> - From a user side it allows them to customize their footers - this seems huge. If we are locking footers that means users cant customize the content in them that may not make sense, or restrict them from adding basic footer things like business addresses, contact info, or other small footer items they would want to add.
>- From a marketing side the banner is a more visible nudge to upgrade to a paid plan. etc. (edited)
