### ISSUE TITLE
Premium Theme: Tsubaki

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#67862]
### Details

The Tsubaki premium theme needs the following:

### Checklist

- [x] Sync [Tsubaki](https://github.com/Automattic/theme-tsubaki) to WP.com
- [x] Theme showcase draft
- [x] Add the theme to the soft-launch filter
- [x] Build a ZIP for the theme
- [x] Add the theme as a product to the Store
- [x] Add the theme to the prices page in MC
- [x] Demo site creation: https://tsubakidemo.wpcomstaging.com/
- [x] Headstart annotations (don't forget to submit for translation)
- [x] GlotPress Project creation
- [x] Launch process

Cheat sheet: paYKcK-1Pt-p2

Premium theme launch guide: PNEWy-eBM-p2

**Comment by iamtakashi** [comment]
> Add the theme as a product to the Store

`D87930-code`

**Comment by iamtakashi** [comment]
> Demo site creation: https://tsubakidemo.wpcomstaging.com/

I'm working on the demo site downgraded to a simple site https://tsubaki.wordpress.com at the moment for generating Headstart annotation.

**Comment by iamtakashi** [comment]
A diff for GlotPress project: D88714-code

**Comment by iamtakashi** [comment]
I've heard the idea that makes Tsubaki the default theme for Woo. With that and the guideline for themes to provide its homepage content has changed, so I need to make some changes to the theme before we launch the theme.

Please continue to work on the issues with Headstart and Atomic but don't launch the theme yet.

**Comment by iamtakashi** [comment]
@mreishus @daledupreez I've merged the changes into the theme. Shall I wait to sync the theme in WP.com or can I just go a head?

**Comment by mreishus** [comment]
> @mreishus @daledupreez I've merged the changes into the theme. Shall I wait to sync the theme in WP.com or can I just go a head?

Please go ahead and then let me know. I'll then create a new annotation and regenerate the test site.

**Comment by iamtakashi** [comment]
I've deployed the theme. I've also realised that the deployment had no effect on the Atomic demo site, but I manually install the updated theme by uploading the theme.

Anyway, the demo site looks good to go now.

**Comment by daledupreez** [comment]
@iamtakashi, I wonder whether the issue with Atomic not updating is because we're not creating releases of the theme and/or not bumping the version. I have some questions about the way we handle managed themes on Atomic, so I will loop back on this topic tomorrow, hopefully with some helpful information!

**Comment by iamtakashi** [comment]
@daledupreez OK. Hopefully, we'll know the best way to update the theme in Atomic. I've actually realised something left to update, but the theme and the demo will be both ready by tomorrow.

**Comment by iamtakashi** [comment]
I'm done with the changes I needed to make. 

I expect minor updates will be made to the themes going forward. It's not a blocker for launch, but it'd be great if we could streamline the process of deploying the theme to Atomic and regenerating the Headspace annotation.

**Comment by mreishus** [comment]
I've created the annotation, bumped the version to ~~1.1~~ 1.1.1, and regenerated my test site. Please take a look at the test site ( the "craft" "2" site mentioned here paYKcK-2aK-p2 ) and let me know what we need to fix in the annotation.

I remember last time, I needed to manually specify ` "page_template": "page-without-title",` for the homepage, but this time around, there is no homepage. So maybe I need to do something like this somewhere else?

Also, the buttons for New Arrival / Men / Women on the homepage no longer go anywhere. This is matching what I see on the demo site, but I think it worked better before?

I also noticed it no longer has the auto loading homepage tag. This might be because it went from a homepage to a blog view, but it's something we might want anyway. Need to follow up on tomorrow.

**Comment by iamtakashi** [comment]
@mreishus, thanks for the update.

> I remember last time, I needed to manually specify "page_template": "page-without-title", for the homepage, but this time around, there is no homepage. So maybe I need to do something like this somewhere else?

This was one of the changes I needed to make to the theme. The homepage content used to be built on a page that used the `page-without-title`, but now a new template `home.html` is providing the homepage content. This was due to the recent changes in our theme guidelines.

> Also, the buttons for New Arrival / Men / Women on the homepage no longer go anywhere. This is matching what I see on the demo site, but I think it worked better before?

This is also related to the change above. Now the homepage content is provided in the template, and the patterns that don't have any specific URLs (this is fine, and the patterns shouldn't have the specific URLs.)

> I also noticed it no longer has the auto loading homepage tag. This might be because it went from a homepage to a blog view, but it's something we might want anyway.

I don't actually know what the tag means. Where was it used to be?

**Comment by iamtakashi** [comment]
The only thing I've noticed was the navigation in the footer (under Need a help? heading.) I would like to have a different navigation from the one in the header. Is that possible to achieve?

| Demo Site | Test Site |
| ----------- | ----------- |
| ![tsubakidemo wpcomstaging com_](https://user-images.githubusercontent.com/908665/197773692-c97a12a8-bfb7-4e15-abca-ec3687a34a72.png) | ![testsitemmrcraft2 wpcomstaging com_](https://user-images.githubusercontent.com/908665/197773728-914a7c7e-1f98-4f87-a399-9b40063fb975.png) |

**Comment by daledupreez** [comment]
@nelsonec87 is working on that issue in #69008 - the nav menus aren't working correctly at the moment.

Also, can I request that we change from "Need a help?" to the simpler "Need help?" for the footer column? "Need help?" is a much more common/standard way of phrasing this in English.

**Comment by iamtakashi** [comment]
> Also, can I request that we change from "Need a help?" to the simpler "Need help?" for the footer column? "Need help?" is a much more common/standard way of phrasing this in English.

Thanks for pointing that out :) I'll change it asap!

**Comment by iamtakashi** [comment]
I've changed the heading. Thanks again for pointing this out.

**Comment by markbiek** [comment]
Theme is launched to all users!
