### ISSUE TITLE
Marketplace Search: Investigate a way to add multiple marketplace fields to one field that will be indexed by Elasticsearch

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#67863]
Currently, every new field added to a Marketplace product in WooCommerce.com side needs to be added to the `jetpack-search` index to be returned when searching. 

Most of those fields will not be used for search so they can be stored as a PHP-serialized array (or _json_ blob) that we could name `wpcom_marketplace_fields`

This task is to investigate and if possible implement a way to do this so we can:

- add only this field in jetpack sync fields
- enhancing `wpcom_marketplace_fields` to include more fields in the future if needed without having to change the indexed fields in Jetpack.

Further context can be found in this task comment: https://github.com/Automattic/wp-calypso/issues/64891#issuecomment-1243817089

The following comment has one example of adding this new consolidated field `wpcom_marketplace_fields` to the `jetpack-search` index pdh6GB-Ax-p2#comment-4321

**Comment by gcsecsey** [comment]
I've looked for some examples for earlier:
- we've added the `plugins.icons` field as a serialized JSON in D82452-code
- we've added the `plugins` with all of its subfields in the `get_plugin_fields` function in D81205-code

**Comment by epeicher** [comment]
After some investigation, I have found that if we would like to go for the serialization approach we should store those fields in WC.com database serialized so they can be read by Elasticsearch document builder. 
That is what we currently do with the `plugins.icons`, link can be found here 2dbbb-pb

This implies changing saving functionality in WC.com and adding some complexity in WC.com side.

On the other hand, indexing every required field seems to be fine as at the moment we have less than 400 in `public_postmeta` and according to [this comment ](https://github.com/Automattic/wp-calypso/issues/64891#issuecomment-1243907286) we could add up to 100,000 fields before running into problems. @gibrown also mentions that 
>  It would be good if these fields were a bit more generic, but I don't think we should worry too much about them. As long as we don't auto add every field (like we used to) then I doubt we will run into a problem.

And that will not be the case, we are going to add them manually every time so it does not seem to be a problem.

@cpapazoglou What do you think? I could open a PR and a diff with those new fields as it was done
- D85227-code
- https://github.com/Automattic/jetpack/pull/25376/files

**Comment by cpapazoglou** [comment]
> After some investigation, I have found that if we would like to go for the serialization approach we should store those fields in WC.com database serialized so they can be read by Elasticsearch document builder. That is what we currently do with the `plugins.icons`, link can be found here 2dbbb-pb

We don't those fields to be searchable. We only want them to be synced to shadow site, so that we can query the WP.com DB for that site and deserialise them - add them to the products response.

**Comment by epeicher** [comment]
In order to sync those fields from WC.com to WP.com I can think of two options:
1. Store them serialized in WC.com in one `meta` field: That will require updating the saving and retrieval logic in WC.com to serialize/deserialize them. That single field will be added to `public_postmeta`
2. Store them in WC.com as multiple individual `meta` fields (as it currently works) and add them to `public_postmeta`

In both options, they will be added to Elasticsearch, in option 1 as a serialized object and in option 2 as multiple fields.

@gibrown, @robfelty, is the above correct? This is, in order to sync fields from WC.com to WP.com they need to exist in `public_postmeta`, right? 

I think this is the call stack but there could be different paths 2dbc1-pb

**Comment by robfelty** [comment]
I think that we have agreed that since these fields are only going to be stored, but not indexed, that it would be best to go with option 1. They will need to be added to the list of `public_postmeta`, as you mention.

**Comment by epeicher** [comment]
The linked task
- https://github.com/Automattic/wp-calypso/issues/68524

will be used to consolidate the fields into one in WC.com and also synchronize it to WP.com.

Closing this task as the investigation is completed
