### ISSUE TITLE
Themes: Auto-suggest search filter types

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#6786]
![screen shot 2016-07-14 at 16 36 46](https://cloud.githubusercontent.com/assets/7767559/16845599/5d92b588-49e1-11e6-8a24-6e7bc65e1fb2.png)

On focus, suggest possible fields to query for. When clicking on any of them, pre-populate the search input with that field, and attach the following user input to it.

**Comment by folletto** [comment]
Note: this is currently static for M5-MagicSearch. We will make this dynamic (suggesting taxonomies more flexibly) probably in the future.

**Comment by folletto** [comment]
Updated i5 design:

![screen shot 2016-08-31 at 16 38 17](https://cloud.githubusercontent.com/assets/4389/18135300/592bc3e4-6f99-11e6-81a9-a9d3300eed92.png)

**Comment by ockham** [comment]
Closed by #8282. Let's open separate issues for styling/UX iterations should we feel the need.
