### ISSUE TITLE
Themes: Auto-complete search filter strings

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#6787]
![screen shot 2016-07-14 at 16 48 15](https://cloud.githubusercontent.com/assets/7767559/16846053/e994c228-49e2-11e6-9146-c81b12f8e093.png)
![screen shot 2016-07-14 at 16 48 43](https://cloud.githubusercontent.com/assets/7767559/16846054/ea779bca-49e2-11e6-8717-7bd5406d3636.png)

Builds on #6786. Suggestions appear and narrow down as user types. For this iteration, the suggestion data will come from a static list in the client.

**Comment by folletto** [comment]
Updated i5 design:

![screen shot 2016-08-31 at 16 39 43](https://cloud.githubusercontent.com/assets/4389/18135352/8ccafed6-6f99-11e6-9321-3a925943a638.png)

**Comment by ockham** [comment]
Closed by #8282.
