### ISSUE TITLE
Converting a Pullquote Block into a Quote Block causes Gutenberg to Crash

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#67876]
### Quick summary

When using the Block conversion feature, attempting to convert from a Pullquote Block to a Quote Block will cause Gutenberg to crash.

There was previously a similar bug when trying to convert from an Image or Gallery block to a Carousel Block, but a link to this issue escapes me at the moment.

### Steps to reproduce

1. Add a Pullquote Block to a page or post
2. Click on the block icon to convert to another block
3. Mouse over the "Quote" block option in the menu

### What you expected to happen

You should be able to convert to a Quote block

### What actually happened

As soon as you mouse over the Quote block option in the block conversion menu, Gutenberg crashes.

### Context

Customer report: 36579084-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Instead of converting blocks, you can delete the block and make a new one.

**Comment by masperber** [comment]
- [ ] 5560822-zen for customer followup when resolved.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on P2: **Replicated**
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Replicated**
- Replicable on Core? **Yes**  - reported here: https://github.com/WordPress/gutenberg/issues/44307

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated just as described across all test environments.

*Example from Self-Hosted Site*

https://user-images.githubusercontent.com/27249804/191389578-8ca908e4-3b07-40b6-ba21-35cdd03bacdd.mov

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Reported in Gutenberg repo: https://github.com/WordPress/gutenberg/issues/44307
- Added to 'HE Cross-repo Watchlist' project board

**Comment by cuemarie** [comment]
https://github.com/WordPress/gutenberg/issues/44307 is resolved, and I retested today and could not replicate:

https://github.com/Automattic/wp-calypso/assets/27249804/274ab546-2d97-4f26-9641-0a5cc119eedc


📌 ACTIONS
- Closed as resolved
