### ISSUE TITLE
Handling an unlimited number of themes in the Design Picker

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#67880]
# Description

<img width="1604" alt="image" src="https://user-images.githubusercontent.com/5665959/190524448-7381ce79-7424-4893-9095-9482d8b329a5.png">

NOTE: This work is for the wordpress.com/start onboarding Design Picker. NOT the Theme Showcase (though it can certainly be duplicated in another git issue/piece of work)

We [recently discovered](https://github.com/Automattic/wp-calypso/pull/67722#issuecomment-1247467914) a hard coded limit of 50 themes returned from elasticsearch query to fetch themes and updated it to limit=100 (D87686-code)  on 15-09-2022.  Per discussion in this report , p58i-dav-p2,  we do not want to have any limit on number of themes showing in the onboarding Design Picker.

So let's implement[ load themes on scroll](p58i-dav-p2). 
What a GREAT  "problem" to have!

We really only need "load on scroll" if there is a performance issue loading 60 or 70 or 100 themes (whatever the # might be).  My opinion is we already have a performance issue, as page takes 4-5 seconds to load.

# Design Tasks

- [ ] How do we indicate "more on scroll" - how about a simple blur at the bottom or just try with no visual indicator, like the middle example [here](https://uxdesign.cc/ui-cheat-sheet-pagination-infinite-scroll-and-the-load-more-button-e5c452e279a8)

![image](https://user-images.githubusercontent.com/5665959/190525815-dc149bb9-1ecc-47ae-8de1-0861631f57ad.png)

# Dev Tasks

- [x] Remove the 100 theme limit
- [ ] Have a look at how "load on scroll" works in the Theme Showcase
- [ ] Determine if there is a performance issue at play (right now loading 57 themes takes 4-5 seconds.  Can this be improved if we do some clever lazy loading on scroll?
  - [ ] can perf slowness be attributed more to v13n designs or theme grid (my own person test show that the DP still takes many seconds to load even when there are not v13n designs shown)
- [ ] As needed, query for more designs as user scrolls  (that implementation actually up to dev)

@Automattic/ganon

**Comment by fushar** [comment]
> My opinion is we already have a performance issue, as page takes 4-5 seconds to load.

I just discovered that Team Vertex actually did a performance enhancement on Design Picker before the Unified Design Picker era. See: https://github.com/Automattic/wp-calypso/pull/63129. Basically it will pre-fetch the designs before the user even lands in it.

I'd suggest we first try to port that logic to UDP and see if it feels fast? (and therefore we don't need to implement this "load on scroll")

**Comment by fushar** [comment]
> I'd suggest we first try to port that logic to UDP

Unfortunately, it is impossible as the our new /starter-designs endpoint needs the values of the intent and the vertical id, which are the two immediate steps before the design picker step. So, no prefetching could be done 😢 We are removing that logic instead, via #68329.

**Comment by fushar** [comment]
> Determine if there is a performance issue at play (right now loading 57 themes takes 4-5 seconds

> can perf slowness be attributed more to v13n designs or theme grid (my own person test show that the DP still takes many seconds to load even when there are not v13n designs shown)

I tried multiple times on incognito window and it didn't take 4-5 seconds to load the Design Picker. It load just smoothly / fast.

@autumnfjeld or maybe what you experienced is that the themes' **mShots previews** and/or the generated designs' iframes  took that many seconds to **render**? I do experience some slowness occasionally, but still tolerable (not 4-5 seconds).

**Comment by fushar** [comment]
> Remove the 100 theme limit

PR ready: D88574-code

**Comment by fushar** [comment]
Based on my investigation, the way our Unified Design Picker loads the design currently, is working just fine, and no optimization is necessary. Maybe we should revisit this issue once the number of themes are more than ~ 200. Let me know if we still want to discuss it otherwise!

**Comment by fushar** [comment]
> Remove the 100 theme limit

Shipped via D88574-code

**Comment by autumnfjeld** [comment]
> I tried multiple times on incognito window and it didn't take 4-5 seconds to load the Design Picker. It load just smoothly / fast.

Excellent. I suspect it was because I had so many sites, I've since used to delete about 40 sites. Here's a handy tool in case you ever need it:  in mc tools: /tools/bulk-delete-test-sites/
