### ISSUE TITLE
Marketplace: Title limits for for plugins

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#67890]
![Screenshot(8)](https://user-images.githubusercontent.com/811776/190566667-2c873bc8-2612-4176-8736-070667aaad06.png)

- [ ] Put a hard limit on title length we are willing to render.

cc @vinimotaa / @SaxonF - anything specific in mind or is 50 chars a good enough fix? `All in One SEO – Best WordPress SEO Plugin – Easi...`

**Comment by cpapazoglou** [comment]
I would suggest:
- putting a limit in the breadcrumb
- leave title as is
- title in modal should be styled in bold
- CTA button change to "Install"
