### ISSUE TITLE
Vivre Theme | Unable to add submenu options using Site Editor

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/wp-calypso#67905]
### Quick summary

Using Vivre theme, when trying to add a submenu to a menu option, the + button hides behind the toolbar and so can't be clicked unless the menu orientation is changed from horizontal to vertical.

https://user-images.githubusercontent.com/49064126/190629706-d853c466-9914-4405-a809-72f7bbe2891c.mp4

### Steps to reproduce

1. Activate the Vivre theme.
2. Go to Site Editor and edit the header.
3. Add a menu with horizontal orientation and add a submenu to one of the menu options.
4. Try adding a submenu option.
5. The + button hides behind the toolbar and can't be clicked unless the menu orientation is changed to vertical.

### What you expected to happen

The + button should have been visible fully and accessible.

### What actually happened

The + button hide behind the toolbar partially and couldn't be clicked.

### Context

#5559347-zen

### Platform (Simple, Atomic, or both?)

both

### Theme-specific issue?

I was able to reproduce this on a simple as well as AT test sites using the Vivre theme.

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Change the menu orientation to vertical, add submenu options and then change the menu orientation back to horizontal.

**Comment by Greatdane** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/66602
