### ISSUE TITLE
Block Toolbar position incorrect for blocks inside cover block on dotcom for Free/Personal Sites.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67929]
The position of the block toolbar does not align with core functionality when the selected block is inside a cover block on dotcom.

dotcom:

<img width="400" alt="Screen Shot 2022-09-16 at 1 45 57 PM" src="https://user-images.githubusercontent.com/28742426/190701220-eba064ca-2687-46a4-bf5f-e04e8c8ba49a.png">

core Gutenberg:

<img width="400" alt="Screen Shot 2022-09-16 at 1 47 55 PM" src="https://user-images.githubusercontent.com/28742426/190701346-ff1b41f4-a63e-4b57-b89e-45557aa6c4fa.png">

### To reproduce:
* Add a cover block to the page
* add some blocks inside it, paragraph text, etc.
* add a "Buttons" block and a few buttons.
* try selecting a button and notice that the toolbar is always positioned relative to the parent cover block instead of above the button itself.

### Notes & findings:
* Tested running the same gutenberg builds/themes locally vs. on dotcom. - only reproducable on dotcom
* Issue does not happen with other container blocks like a "group" block.
* This happens regardless of the editor being iframed.
* tested on multiple themes TT2, blockbase, Livro
* Happens in both post/page and site editors.
* im only finding this on simple sites. in fact on all simple sites i test except for this one outlier p1663357192215469/1663352237.319669-slack-C03N25JPCE4

**Comment by Addison-Stavlo** [comment]
From my own testing I am seeing:
* Creating new sites with a "Free" or "Personal" plan reproduce this issue.
* Creating new sites with a "Premium", "Business", or "E-Commerce" plan do not reproduce this issue.

Free/Personal (unexpected):
<img width="718" alt="Screen Shot 2022-09-20 at 11 26 31 AM" src="https://user-images.githubusercontent.com/28742426/191299722-f98818b2-e427-442b-916a-90bcb23d8d3d.png">


Premium/Business/Ecom (expected):
<img width="765" alt="Screen Shot 2022-09-20 at 11 25 52 AM" src="https://user-images.githubusercontent.com/28742426/191299509-6ce2f9bc-c792-4799-b002-7caded3fcf8e.png">

**Comment by jeyip** [comment]
### Technical Notes

Since things are fine in Core, consider opening this page in Dotcom and in a self-hosted instance and comparing / contrasting the styles to determine why one view works and the other doesn't.

This seems like it might be a potential culprit https://github.com/Automattic/jetpack/pull/25812. We should also test reverting the css changed here fixes the problem

**Comment by Addison-Stavlo** [comment]
> This seems like it might be a potential culprit https://github.com/Automattic/jetpack/pull/25812.

I ran a git-bisect and confirmed this commit introduced the regression.

**Comment by simison** [comment]
:wave: Did this get sorted already?

**Comment by Copons** [comment]
Apologies for the delay, we just were on meetup when we got the alert, and it must have slipped through the cracks; I've now added this issue to @Automattic/ajax sprint board.

@mmtr, could you take a look at this tomorrow? 🙇‍♂️
