### ISSUE TITLE
Marketplace: Remove search result highlights

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#67922]
Hide the search term highlights in results. Context: pdh6GB-1Vu-p2

![Image](https://user-images.githubusercontent.com/1689238/190682549-e3518c32-b4a9-43d4-838c-b048992a4577.png)

Acceptance criteria:
- [ ] Terms in search results that match the search term are no longer highlighted.

**Comment by lupus2k** [comment]
This issue is part of https://github.com/Automattic/wp-calypso/issues/68492
