### ISSUE TITLE
Help Center: Ensure tickets are marked as overflow when chat is unavailable

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#67927]
### Quick summary

In the FAB and contact form when a user that is eligible for chat tries to contact us and we do not have any chat availability we check a Chat Overflow field when the ticket is created in Zendesk to record that the user should have received chat. We then use this value to generate our responsiveness performance in Happiness data.

We need to ensure that Help Center does the same, checking the Chat Overflow field if a ticket is created by a chat-eligible user while we do not have any availability. One concern with this is that some amount of users would have picked the ticket channel regardless, but this seems like the cleanest solution with our current data resources so our existing reporting continues to work.

@klimeryk I wasn't able to quickly find where this code is to reference it so it properly factors in when chat is closed. Could you share any relevant code references? Thank you!

cc @arcangelini 

### Steps to reproduce

1. Submit a ticket from Help Center while chat is unavailable

### What you expected to happen

Chat Overflow field in Zendesk should be checked

### What actually happened

Chat Overflow is not checked regardless of whether chat is available or not

### Reproducibility

Consistent

**Comment by arcangelini** [comment]
This was addressed in #67928
