### ISSUE TITLE
Marketplace: Rotate popular search terms in search field

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#67926]
On /plugins, remove the popular search terms and rotate them as suggestions in the search field instead.
Context: pdh6GB-1Vu-p2

Acceptance criteria:
- [ ] Record data for searches overall, to see if this change affects search counts.
- [ ] Remove popular search terms and simultaneously add the popular search terms as rotating suggestions in the search field.
- [ ] Check search counts after the change.

**Comment by cpapazoglou** [comment]
Popular searched have already being removed. Let's rotate the placeholder as suggested to make the page more alive.

**Comment by cpapazoglou** [comment]
Let's use the script in PCYsg-ID9-p2 to find the 5 most popular categories.
