### ISSUE TITLE
[Bug]: Help Center: Chat/Email submit button overflowing

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#67931]
### Quick summary

The Email us/Chat with us button in Help Center is overflowing the Help Center container on the right edge. cc @arcangelini 

### Steps to reproduce

1. Open Help Center
2. Click Still Need Help
3. Choose Live chat or Email
4. Note the submit button overflows the container

### What you expected to happen

The button to be constrained by the container

### What actually happened

The button overflows the right edge 

<img width="423" alt="Screen Shot 2022-09-16 at 11 34 46 AM" src="https://user-images.githubusercontent.com/1900444/190708765-80e4f64f-927d-4e7d-a7b6-b07b7cc626d2.png">

<img width="426" alt="Screen Shot 2022-09-16 at 11 29 08 AM" src="https://user-images.githubusercontent.com/1900444/190708775-8e995280-fbc1-4e84-9e01-4560421e4de0.png">

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by arcangelini** [comment]
Thanks!
