### ISSUE TITLE
[Bug]: Help Center: Initial connection message shows when reopening Help Center with active chat

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#67935]
### Quick summary

When Help Center is closed while chat is active and reopened the default text and a message about connecting to a Happiness Engineer is briefly shown before the open chat reappears.

![chat message 2](https://user-images.githubusercontent.com/1900444/190712351-88035cad-e6d1-4f43-a358-490ec115921e.gif)

cc @arcangelini 

### Steps to reproduce

1. In Help Center with an active chat close it out from the X
2. Click the ? in the admin bar to reopen Help Center
3. The intro text and connecting message briefly show before the chat reloads

### What you expected to happen

The chat to instantly load as it did from the FAB

### What actually happened

The connection message appears before the chat is loaded. 

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by jordesign** [comment]
+1 to this - I was noticing it as well.

**Comment by alshakero** [comment]
The proposed fix is here https://github.com/Automattic/wp-calypso/pull/68046
