### ISSUE TITLE
Sites Management Page: Standardize filter dropdowns visually

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#67940]
### Details

Right now, we have the site status and sorting order dropdowns in SMD:

![image](https://user-images.githubusercontent.com/26530524/190726558-18ebf35d-d7bc-4117-ba28-8ea64b6a31ae.png)

The sorting dropdown should have less relevance than the status filter, but that doesn't mean they should differ visually.

@SaxonF suggested on Slack (p1663188155170329-slack-C0347E545HR) that we might standardize the dropdowns and give relevance by using other elements, such as positioning. There's more information on the Slack message.

### Done is

- [ ] There's consensus on how to style dropdowns in SMD;
- [ ] Dropdowns are consistent.

**Comment by mpkelly** [comment]
I was going to pick this up, but I am not sure about this part:

>There's consensus on how to style dropdowns in SMD;

Do we want to make both the Status and Sort menus use the same style as Status does currently?

@Automattic/build, this is one of the remaining tasks on Sites Management Page i2, so ideally, we'd work on it or close it down. Please chip in if you have any input for the first requirement above.

**Comment by sejas** [comment]
Tagging @SaxonF, as he probably has more insights. ✨

**Comment by zaguiini** [comment]
We won't work on this. As there is an ongoing project to unify the Jetpack Cloud and the Sites page, this will probably be addressed there with other design changes.
