### ISSUE TITLE
Pattern Assembler: Show the CTA only for the Build flow

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#67951]
#### Description

Revising #67713, the "Start with a blank canvas" CTA should only show for the build flow and not the write flow, as right now we don't have patterns suitable for blogs.

#### Acceptance Criteria
- [x] The “Start with a blank canvas” CTA should only show for the build ~and write~ flow. (see convo p1663316142361469-slack-CRWCHQGUB

cc: @Automattic/ganon

**Comment by taipeicoder** [comment]
Closing as it's deployed.
