### ISSUE TITLE
List block shows extra line break on the back end

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#67957]
### Quick summary

The List Block creates this extra line break look soon after a new line is inserted. 

Looks broken on the backend, but okay on the frontend.

https://user-images.githubusercontent.com/84539773/190960440-e3baf24a-fde2-4d73-8823-cd55e00c76d2.mp4

### Steps to reproduce

Insert List block.
Add a new line.
Publish the page. Frontend looks okay.

### What you expected to happen

There wouldn't be this double line break.

### What actually happened

There is a double line break.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Workaround details

Not needed, because on the frontend it looks okay, but it is not how it is supposed to look.

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Could Not Replicate
- Tested on Self-hosted - Could Not Replicate
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I could not replicate this in any of my tests. The List block seems to be working as expected.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @csabarakasz If you are still able to replicate this, can you please share more details on how others can replicate? For example, does this happen with a specific browser or theme? Thanks!

**Comment by csabarakasz** [comment]
It seems like it was caused by an extension on my Firefox. I deactivated all of them and the issue went away
