### ISSUE TITLE
Pattern Assembler: Pattern is duplicated when editting

### ISSUE THREAD

**Issue by bangank36** [Automattic/wp-calypso#67952]
#### Steps to reproduce

1.  Visit PA screen: http://calypso.localhost:3000/setup/patternAssembler?siteSlug={your_site}
2. Add a section ( Add a first section or Add another section ) eg: "Image and text side by side"
3. Hover over the selected pattern and click edit, try to select the same pattern "Image and text side by side", you will see it is duplicated on the list

#### What I expected

1. There shouldn't be duplication

#### Screenshot / Video

https://user-images.githubusercontent.com/10071857/190949162-d07b93f9-e07e-465a-944d-ae7eb51933f4.mp4

**Comment by miksansegundo** [comment]
I found the bug! I could not resist fixing it 😊 in https://github.com/Automattic/wp-calypso/pull/68029
