### ISSUE TITLE
Marketplace: Plan information step hints

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#67977]
The blue-boxed area

![Image](https://user-images.githubusercontent.com/6586048/191047347-665d5445-23fb-455d-accc-4cb955746339.png)

Acceptance criteria:

- [ ] Shows the hints (not sure what to call them)

**Comment by lsl** [comment]
@vinimotaa Are there any specific icons you want us to use? http://automattic.github.io/gridicons/ Doesn't have a lightbulb.

**Comment by vinimotaa** [comment]
Money back guarantee: 
`<Gridicon icon="money" />`

Flex your site with plugins
`<Gridicon icon="plugins" />`

Essential features
`<Gridicon icon="plans" />`


@lsl
