### ISSUE TITLE
Marketplace: Free plugin handling

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#67994]
Free plan shows Jetpack and Akismet as installed and managed but the copy here about what is included with a business plan upgrade doesn't make sense given there is no upgrade being required.

![Screenshot(11)](https://user-images.githubusercontent.com/811776/191145365-5286e0df-ec0a-4ff8-bfec-25e8cdeb6b45.png)

There's also a strange design artifact with the duplicate border separator of different widths shown without any CTA / text.

- [ ] Improve copy
- [ ] Remove double border

**Comment by lsl** [comment]
@vinimotaa @SaxonF Copy / design suggestions?

**Comment by vinimotaa** [comment]
What about something like this?

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/97929097/191257654-f4ee24ed-771e-48e2-b887-f4a9ca30e8d9.png">

**Comment by lsl** [comment]
LGTM, got a figma link for when someone gets to it?

**Comment by vinimotaa** [comment]
@lsl 

https://www.figma.com/file/HOg65lHD0QOfaq0QtzKQbC/Dog-Fooding?node-id=984%3A9629
