### ISSUE TITLE
Reader Search: Add search suggestions support

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#6799]
There are a number of cases we should add support for:
- Past history of user searches (at the least get them from localstorage)
- The api should look at whether the current search may have a typo and suggest corrections
- suggest terms based on similar searches. For example, adding more words to the phrase. This probably requires some new indexing and so will take some backend work

**Comment by fraying** [comment]
One more: Algorithmic suggestions for searches based on search term frequency (or something else) to replace the Staff Suggestions.
