### ISSUE TITLE
Themes: inconsistent exit behavior exiting the Customizer after changing a theme

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#68]
This issue is a series of related Customizer bugs that happen in Calypso, specifically when exiting the Customizer after changing a theme.

# Issue 1:

1/ Go to Calypso single site view, click on 'Customize' button

![screen shot 2015-08-27 at 8 33 32 pm](https://cloud.githubusercontent.com/assets/11487924/9527994/08ab56f8-4cfb-11e5-94a6-dfdb283ffb4a.png)

2/ Change the site theme & the site title:

![screen shot 2015-08-27 at 8 36 49 pm](https://cloud.githubusercontent.com/assets/11487924/9528071/76a8cf50-4cfb-11e5-8c78-267c2bdcc48b.png)

3/ Click on 'Save & Activate'

![screen shot 2015-08-27 at 8 37 50 pm](https://cloud.githubusercontent.com/assets/11487924/9528085/86a3cfe0-4cfb-11e5-8d8f-864f864d93e9.png)

**Actual result:** See the front page of the site
**Expected result:** To go back to Calypso Themes with a confirmation screen about changing the theme:

![screen shot 2015-08-27 at 8 33 23 pm](https://cloud.githubusercontent.com/assets/11487924/9528134/bafaa5b6-4cfb-11e5-8c64-651106afa692.png)

The success message would be consistent with the rest of Themes behavior of confirming the theme change.

# Issue 2:

1/ Go to Calypso > Themes, click on 'Customize' for the current theme:

![screen shot 2015-08-27 at 8 45 44 pm](https://cloud.githubusercontent.com/assets/11487924/9528338/a30f1f30-4cfc-11e5-94fd-c0de977cc725.png)

2/ Change theme to something else:

![screen shot 2015-08-27 at 8 46 32 pm](https://cloud.githubusercontent.com/assets/11487924/9528358/c1109176-4cfc-11e5-8398-9ce246061c90.png)

3/ Click on 'Save & Activate'

![screen shot 2015-08-27 at 8 47 03 pm](https://cloud.githubusercontent.com/assets/11487924/9528377/d4771258-4cfc-11e5-81dd-8b65f90621e9.png)

**Actual result:** Go to the front page of the site
**Expected result:** Go back to Calypso Themes and see a success message about changing the theme:

![screen shot 2015-08-27 at 8 33 23 pm](https://cloud.githubusercontent.com/assets/11487924/9528134/bafaa5b6-4cfb-11e5-8c64-651106afa692.png)

# Issue 3:

1/ Go to Calypso > Themes, click on 'Customize' for the current theme:

![screen shot 2015-08-27 at 8 45 44 pm](https://cloud.githubusercontent.com/assets/11487924/9528338/a30f1f30-4cfc-11e5-94fd-c0de977cc725.png)

2/ Change the site theme & the site title:

![screen shot 2015-08-27 at 8 36 49 pm](https://cloud.githubusercontent.com/assets/11487924/9528071/76a8cf50-4cfb-11e5-8c78-267c2bdcc48b.png)

3/ Click on 'Save & Activate'

![screen shot 2015-08-27 at 8 52 28 pm](https://cloud.githubusercontent.com/assets/11487924/9528530/9526f0a4-4cfd-11e5-96d5-478b50bd6ee6.png)

**Actual result:** Go to the front page of the site
**Expected result:** Go back to Calypso Themes and see a success message about changing the theme:

![screen shot 2015-08-27 at 8 33 23 pm](https://cloud.githubusercontent.com/assets/11487924/9528134/bafaa5b6-4cfb-11e5-8c64-651106afa692.png)

# Solution

The best possible outcome here is to redirect back to the Showcase if the Customizer has been accessed via a Showcase link.

Why? Because once the theme has been changed from within the Customizer, we should go back to our welcome message. It's not perfect but at least it gives the user a choice: _Back to themes_ or _Visit site_.

**Comment by mattwiebe** [comment]
These instances should all be fixed now that #1227 is closed. Those cases all involved breaking out of Calypso due to the way theme previewing in the Customizer works.
