### ISSUE TITLE
Calypso: update excerpts and permalink documentation links to wpcom

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#68009]
https://github.com/Automattic/wp-calypso/issues/52191#issuecomment-1251864383

Links were probably updated in wordpress core, so we need to intercept these new links.

**Comment by donalirl** [comment]
Looks like this reverted again, as the links are leading to .org documentation in the editor right now.

**Comment by escapemanuele** [comment]
Yes, the link has changed and so we need to update it in our code 👍

**Comment by escapemanuele** [comment]
Opened this PR @donalirl  https://github.com/Automattic/wp-calypso/pull/78908

**Comment by escapemanuele** [comment]
This has been fixed @donalirl
