### ISSUE TITLE
Plans Redesign: fix plans compare redirect

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6800]
With the plans redesign enabled, start Calypso with `ENABLE_FEATURES=manage/plan-features make run` and try navigating to http://calypso.localhost:3000/plans/compare/:mysite:

Doing so redirects you to  http://calypso.localhost:3000/plans instead of http://calypso.localhost:3000/plans/:mysite: and forces you to select a site again.

**Comment by rralian** [comment]
@lamosty can you take a look at this before you head out?

**Comment by lamosty** [comment]
Fix in #6781. The reason why I hadn't added the site domain to `/plans` redirect URL is that I saw the code below:

![selection_057](https://cloud.githubusercontent.com/assets/4988512/16866882/e1153358-4a6e-11e6-9687-e82f0c6af4d1.png)

without the site domain (=> only `/plans/compare`). But it's probably something different.

**Comment by artpi** [comment]
> Fix in #6781.
I put a fix in https://github.com/Automattic/wp-calypso/pull/6893 and removed it from there. It needed rebasing
