### ISSUE TITLE
Plans Redesign: free plan link

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#6801]
With the plans redesign enabled, start Calypso with `ENABLE_FEATURES=manage/plan-features make run` and navigate to http://calypso.localhost:3000/start

Follow steps until you reach plans.

We currently see the following
<img width="1130" alt="screen shot 2016-07-14 at 12 05 08 pm" src="https://cloud.githubusercontent.com/assets/1270189/16852361/a8ccd97c-49bc-11e6-95a0-bcd61f53d613.png">

1. We should not display the compare plans link
2. If the the free plans link test introduced in #6763 is positive, implement the `skip for now` link and do not display the free plan as a column in nux.

**Comment by rralian** [comment]
This isn't necessary any longer, since the free-plan test was canceled. I will create a cleanup PR to remove it from the codebase and simplify things.

**Comment by rralian** [comment]
Addressed by removing the test.
