### ISSUE TITLE
Sites Management Page: promote tailored flows

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#68018]
When user has 1 site, let's promote the newly released link-in-bio tailored flow in the grid view.

![image](https://user-images.githubusercontent.com/1182160/191242465-cc0c5f19-81c7-4ad1-9f8f-dedecd39f53b.png)

Done is:
- [ ] visuals match the proposed designs https://github.com/Automattic/wp-calypso/issues/68018#issuecomment-1257483200
- [ ] clicking on button opens up the link-in-bio tailored flow
- [ ] new tracks even for button clicks
- [ ] promotion isn't shown if the user already has a Link in Bio site
- [ ] promotion is dismissable

**Comment by vindl** [comment]
Questions for @SaxonF:

- Where can we get the image assets for this?
- Should we do something similar in list view?
- Should we do it in the case when there are 4-5 sites?
- How should the design appear when the unit only takes 1/3 of the grid?

**Comment by danielbachhuber** [comment]
@vindl How should the design appear when the unit only takes 1/3 of the grid?

**Comment by vindl** [comment]
@danielbachhuber, I'll add that to the list of questions for Saxon.

**Comment by SaxonF** [comment]
QeephiOEw5Ym0kj1jfVCqn-fi-1086%3A50193

![image](https://user-images.githubusercontent.com/1072756/192196574-b2ba0fe3-49a7-40bc-852f-1f4e60ba38e2.png)
![image](https://user-images.githubusercontent.com/1072756/192196580-176bc772-1fe9-4b2f-a26e-bdd161c4f108.png)
![image](https://user-images.githubusercontent.com/1072756/192196596-e47d6083-1cc3-43e3-a6e9-11bc0943d621.png)

@danielbachhuber @vindl thoughts? I think we should start with showing when just one site.

**Comment by vindl** [comment]
> @danielbachhuber @vindl thoughts? I think we should start with showing when just one site.

The tile view looks good to me! ✨ What do you think about making it less pronounced in the list view? I imagined something that would blend in as another row on the table.

**Comment by p-jackson** [comment]
> clicking on button opens up the link-in-bio tailored flow

Does anyone know the link to this tailored flow?

I wonder if we have any way of knowing whether the user's one existing site is already a link-in-bio site. That way we can hide this promotion.

@SaxonF what are your thoughts on having the ability to dismiss the promotional banner? The upsells on My Home have this interface:
<img width="1063" alt="CleanShot 2022-09-27 at 09 03 59@2x" src="https://user-images.githubusercontent.com/1500769/192369400-a0925b40-d091-4e57-8ec4-b35ba3c3873c.png">
But we could just have a simple cross in the top right. IMO non-dismissable upsells on a landing page are a bit aggressive.

**Comment by SaxonF** [comment]
> Does anyone know the link to this tailored flow?

https://wordpress.com/setup?flow=link-in-bio&ref=logged-out-homepage-lp

> I wonder if we have any way of knowing whether the user's one existing site is already a link-in-bio site. That way we can hide this promotion.

I imagine there would be in order to know when to show the Launchpad.

> what are your thoughts on having the ability to dismiss the promotional banner?

👍

**Comment by mpkelly** [comment]
Hi, @SaxonF. I am starting this task. I have a few remarks:

1. In your QeephiOEw5Ym0kj1jfVCqn-fi-1086%3A50193, I noticed that frame one and frame three use almost, but not quite, the same image - can these be made to be exactly the same?
2. Do you want to include the Dismiss Button, or should I add something consistent with other banners? My only worry is that the X-button we usually use will overlap the image on the third frame with its current placement. Maybe you can include the X-button in your mockups and adjust the height slightly for the third frame?
3. In the existing text on the site, we usually write: "Link in Bio site". So I think we should do the same with your subtext.

**Comment by SaxonF** [comment]
@mpkelly 
1. Yep we should use the same image. Let me know if you can export from Figma.
2. Added dismiss button.
3. Good pickup! Adjusted in Figma.

**Comment by mpkelly** [comment]
@SaxonF - I can see your edits coming through now. Thanks. And yeah, I have exported the images from Figma.

**Comment by mpkelly** [comment]
Hi @vindl, regarding this requirement:
>promotion isn't shown if the existing site was created with the link-in-bio tailored flow

Maybe we should not show the banner if the user already has one or more Link in Bio sites, regardless of the current site, which isn't shown on the `/sites` page currently?

Also, is there a way to know if a site was created via the Link in Bio flow or was that something that needs to be added? Looking at the `me/sites` response, I can see a couple of properties that look like they are related to Link in Bio but they aren't very explicit:

```
sites.options.launchpad_checklist_tasks_statuses.links_edited
sites.single_user_site
```
I can do more digging but needn't duplicate analysis if someone else already checked.

**Comment by mpkelly** [comment]
@SaxonF I made some progress with this. You can test the draft PR here https://github.com/Automattic/wp-calypso/pull/68483

**Comment by danielbachhuber** [comment]
@SaxonF @vindl @p-jackson Given the obtrusiveness of this notice, how will we evaluate whether or not it performs to our expectations? I'd imagine we'll want to only keep it if it performs well.

**Comment by vindl** [comment]
> Maybe we should not show the banner if the user already has one or more Link in Bio sites, regardless of the current site, which isn't shown on the /sites page currently?

@mpkelly yes, that's what I had in mind.

> Also, is there a way to know if a site was created via the Link in Bio flow or was that something that needs to be added?

I'm unaware of a good way to check for that, so I'll loop in @Addison-Stavlo for ideas.

**Comment by vindl** [comment]
> @SaxonF @vindl @p-jackson Given the obtrusiveness of this notice, how will we evaluate whether or not it performs to our expectations? I'd imagine we'll want to only keep it if it performs well.

What "good performance" means quantitatively is up for debate. In my opinion, every new site creation counts. But to have a starting point for conversation, how does this sound: 5% of users that see the notice end up clicking on the link, and 20% end up creating a new site - so 1% overall conversion rate.

**Comment by danielbachhuber** [comment]
> But to have a starting point for conversation, how does this sound: 5% of users that see the notice end up clicking on the link, and 20% end up creating a new site - so 1% overall conversion rate.

Sounds like a great starting point!

**Comment by mpkelly** [comment]
This has been deployed just now. https://github.com/Automattic/wp-calypso/pull/68483
