### ISSUE TITLE
Task: Hide the Help Center for users with no sites and show the FAB instead

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#68026]
### Details

The help center heavily depends on the user having a site to render the right help articles and to fill the contact form fields. 

Let's show the FAB istead of the Help CEnter in that case.

**Comment by supernovia** [comment]
Would we reconsider this? When working with users we tend to tell them things like "Look in the upper right for the question mark icon" and if that's just not predictable, it can frustrate HEs and users alike.

**Comment by alshakero** [comment]
100%. I came to close the issue and fix the Help Center instead. 

Closing as superseded by https://github.com/Automattic/wp-calypso/issues/68150.
