### ISSUE TITLE
Sites Management Page: Accessibility concerns with dropdowns

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#68021]
@wojtekn [identified some accessibility concerns](https://github.com/Automattic/wp-calypso/pull/67936#issuecomment-1250671637) with the dropdowns:

> However, I noticed a few other issues related to the screen reader:
>
> 1. when I open the "Status" dropdown using enter key, I can use arrows to navigate through options. I can't do the same in the "Sorting by" dropdown. Tab works in both, though.
> 2. screen reader reads the number of sites without the context. Should it read "thirteen sites" instead of just "thirteen"?
> 3. each option in the "Status" dropdown is read twice giving the confusing "Public Public thirteen", "Coming soon Coming soon two" etc.

I think 2 and 3 are easily fixable. 1 might be a more difficult issue with the underlying component.

**Done is:**
* We've fixed what we easily can, and opened new issues (if needed) for more thorny problems.

**Comment by wojtekn** [comment]
Closing. We can skip this one as the tab is the default way to navigate and it works for both buttons:

> when I open the "Status" dropdown using enter key, I can use arrows to navigate through options. I can't do the same in the "Sorting by" dropdown. Tab works in both, though.
