### ISSUE TITLE
Sites Management Page: provide next steps for un-launched sites

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#68020]
As part of i2, we want to provide the next steps for un-launched sites in the status column and grid view:

![image](https://user-images.githubusercontent.com/1182160/191244248-ebcbb8af-3de1-4ea9-b935-1299132a788e.png)

![image](https://user-images.githubusercontent.com/1182160/191244362-bbed06f3-6d7d-470e-9b3c-fea6157f04bb.png)

Done is:
- [ ] The implementation matches the proposed designs visually
- [ ] Clicking on the particular step opens up the launchpad with the appropriate view
- [ ] We have tracks events for particular step clicks

**Comment by vindl** [comment]
Questions for @SaxonF:

- What exact steps do we want to surface here?

**Comment by SaxonF** [comment]
@vindl do we have access to Launchpad data? This should be driven by the task list there but maybe as a first pass we can just link off to the Launchpad if one exists?

**Comment by vindl** [comment]
@SaxonF, we do, but they don't have the `Add domain` step because it happens sooner in the flow.

Here are the steps we have so far:
|Newsletter|Link in Bio|
|-|-|
|<img width="467" alt="Screenshot 2022-09-26 at 14 26 26" src="https://user-images.githubusercontent.com/1182160/192276536-79757229-71b7-42cf-92bd-3b3749b955aa.png">|<img width="494" alt="Screenshot 2022-09-26 at 14 27 25" src="https://user-images.githubusercontent.com/1182160/192276544-c2968fc4-4ddb-4fbf-9dc2-a7d1f74e4b8b.png">|

We should be able to use the following function to get the next step: https://github.com/Automattic/wp-calypso/blob/7c215f39f56089e351d35ad506c3836b29dc9f06/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts#L11

The tasks statuses are persisted in the `launchpad_checklist_tasks_statuses` site option: https://github.com/Automattic/wp-calypso/blob/9850f8d33bd047f0ff01bdfd047ef62b52a4f0d9/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts#L23

We can use the ones available here for start, and if we need more like `Add domain` they should likely be surfaced in both places for consistency.

**Comment by p-jackson** [comment]
I don't know much about the new launchpad (I don't actually know how to bring up that UI that @vindl shared above), but I see that the old launch checklist on My Home still exists

<img width="1073" alt="CleanShot 2022-09-27 at 08 36 15@2x" src="https://user-images.githubusercontent.com/1500769/192364594-89875dc7-dabc-4ff3-93f9-00654a56531d.png">

The My Home checklist is what I'd assumed we showing on the SMP. I know that the Launchpad is the new thing though, so perhaps it makes more sense to go with that.

We could support both, but I'm worried that the SMP would end up showing you another checklist immediately after you've just completed one.

**Comment by SaxonF** [comment]
Thoughts on just linking to either Launchpad if one exists or My Home for now?
![image](https://user-images.githubusercontent.com/1072756/192973518-66d8b6e1-5084-4fe3-bc19-8d34476b8c20.png)
![image](https://user-images.githubusercontent.com/1072756/192973556-6a808179-8aeb-4c41-a841-c16f75ecf844.png)

**Comment by vindl** [comment]
> Thoughts on just linking to either Launchpad if one exists or My Home for now?

Sounds like a good first step. 👍

**Comment by p-jackson** [comment]
It's possible to have a checklist immediately after completing a previous checklist.

https://user-images.githubusercontent.com/1500769/193196321-3c0f05e4-48ff-4887-b362-ef9ef52fafe1.mp4

So what I don't like is the idea that after showing one donut in the sites management page, that after following the link and going through the checklist, the sites management page will show you _another_ donut you need to complete.

One idea is to only show the checklist from My Home in the sites list when the site wasn't created using a tailored flow. But on the other hand it's just a general issue with the tailored flows at the moment (you see one checklist right after the previous one). So maybe we shouldn't be trying to fix that here, and it's just easier to show the donut if _either_ of the checklists are incomplete. Defaulting to the tailored flow checklist of course.

**Comment by p-jackson** [comment]
I take that back. In the above video I launch the site, so even though the checklist is still available in My Home, the donut won't appear on `/sites` because the site has been launched.

**Comment by danielbachhuber** [comment]
Now that we're talking about the donut, I feel like it does give me a little anxiety. Maybe just show the 'Launch Guide' link, or test donut vs. non-donut to see which performs better?

Also, relevant to this issue and #68018: I'd be curious about how many users might see this state (`Coming Soon site in Sites page list`)

**Comment by p-jackson** [comment]
That "todo list induced anxiety" is sort of by design though isn't it? We're using the checklist as a way to drive folks to launch. Usually I'd advocate people being able to skip or dismiss the checklist, but I don't think we really want any unlaunched sites long-term right? Either you should launch your site or you should delete it.

> I'd be curious about how many users might see this state

My guess is not very often for the tailored launch flows (that flow is _very_ persistent in getting you to complete the flow), and more-so with the regular My Home checklist. It's pretty easy to keep putting that off.

**Comment by p-jackson** [comment]
> We have tracks events for particular step clicks

@vindl FYI the scope of this task changed a bit because we don't have ready access to the data for the exact steps. That means we're not recording tracks for particular steps, just that they clicked to go to the launchpad in general.

**Comment by vindl** [comment]
> @vindl FYI the scope of this task changed a bit because we don't have ready access to the data for the exact steps. That means we're not recording tracks for particular steps, just that they clicked to go to the launchpad in general.

Thanks for the heads up. 👍 We can add them later when/if we start displaying more granular steps on the Sites page.
