### ISSUE TITLE
Site Switcher: Tweak 'Magic' sorting algorithm to put primary site first, use frequency as tiebreaker

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#68030]
Couple of tweaks to the 'Magic' sorting algorithm that I think will improve the experience:
1. ~Always put the primary site first.~
2. If two sites have an interaction on the same date, use the total amount of interactions as the next tiebreaker (before sorting alphabetically).

**Done is:**
* ~Both of these tweaks are~ The second tweak is applied to the algorithm.

**Comment by vindl** [comment]
> Always put the primary site first.

I left some comments in Slack related to this. I'm not convinced that the primary site needs to be at the top:

- I'm not using it or accessing it very frequently. It's just a test blog for me, and it's not valuable to surface it at the top.
- For folks that are using it frequently, the interaction algorithm should place it towards the top anyway.
