### ISSUE TITLE
LaunchPad - remove visible arrows from completed tasks.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#68037]
Currently completed tasks that allow revisiting have visible chevron/arrows, such as "Add links" in the example below: 

<img width="478" alt="Screen Shot 2022-09-20 at 10 40 23 AM" src="https://user-images.githubusercontent.com/28742426/191288105-bc65b995-dda1-408e-9dbf-cc02820f6577.png">

We want to update these to not show the arrow by default.

Uncertain: Do we want to leave these arrows on hover or get rid of them entirely? cc @nuriapenya here or on the subsequent PR to help decide what is desired.

**Comment by nuriapenya** [comment]
> Do we want to leave these arrows on hover or get rid of them entirely?

The idea would be to remove them entirely. We already have the hover effect (turning blue) and the main goal of the list is prompting people to do the next task (rather than going backwards)
