### ISSUE TITLE
LaunchPad - Update the main copy to be dynamic

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#68033]
The main Launchpad copy ("Your ${flowName} is ready to launch!") is static and sometimes unfitting for the situation.  We should update this to be more dynamic.

<img width="512" alt="Screen Shot 2022-09-20 at 10 19 02 AM" src="https://user-images.githubusercontent.com/28742426/191282688-91ff755a-a573-4914-9712-4bcd5e2b07fd.png">

1. When the site is not yet ready to launch (incomplete dependent steps before the Launch step can be enabled - such as when "Add links" has not yet been done in the link-in-bio flow) - We should update this to `"Your ${siteType} is almost ready!"`
2. For sites that are already launched before completing the LaunchPad (Newsletter flow) - the final ready copy should read "Your Newsletter is ready!" (we should remove "to launch"). - While keeping flows that do have a final launch step  (link-in-bio) with the original "to launch" verbage.

**Comment by edanzer** [comment]
Resolved by https://github.com/Automattic/wp-calypso/pull/68055
