### ISSUE TITLE
Sites Management Page: Enable Magic sorting in production

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#68044]
### Details

In https://github.com/Automattic/wp-calypso/pull/67990 we disabled "Sort by: Magic" in production as it's a feature not yet ready for all WPCOM users. It's lacking training before actually becoming useful to the users, so we chose to disable it.

### Checklist

- [x] Remove all references to the `sites/automagical-sorting` feature flag from the code base.

**Comment by danielbachhuber** [comment]
Shipped in #68060
