### ISSUE TITLE
Reader: unable to load development in IE11/Edge

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#6806]
Doing some testing, and I notice that the reader doesn't load posts for me in IE11 (and @gwwar noticed the same in Edge). I just see the placeholders. I get a not super helpful fatal error in the console.

This is limited to development... it loads fine for me in wpcalypso and in production.

I don't know exactly what the issue is, but I'm a little worried it has something to do with a feature enabled in development and no other environments. Or maybe it has to do with the domain. ¯\\_(ツ)_/¯

Anyhew, though you might want to know about it.

![error](https://cloudup.com/cFWQeAscszG+)

and this is the line it's referring to
![error line](https://cloudup.com/cVuABeg-yc0+)

/cc @blowery

**Comment by blowery** [comment]
That's sometimes a bad function being passed to nextTick....  I'll take a peek in the morning unless @bluefuton beats me to it

**Comment by lancewillett** [comment]
Closing as no further reports or action taken in last 3 months.
