### ISSUE TITLE
[Bug]: Draft Post Previews return 404 error

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#68071]
### Quick summary

This is a continuation of https://github.com/Automattic/wp-calypso/issues/57812. It appears as if several users are still experiencing the error, although at a much less frequent pace then before after we released a third party cookies patch https://github.com/Automattic/wp-calypso/pull/66046

The new errors may or may not also be related to third party cookies.

### Steps to reproduce

In theory, we should be able to replicate by following these steps:

- Create a site with a custom domain
- Create a draft post
- Try to preview it in a separate window

In practice, I'm unable to do so.

### What you expected to happen

Preview the post

### What actually happened

Redirected to a 404 page

### Reproducibility

Intermittent

### Available workarounds?

Preview the post or page from the post or page list view instead

**Comment by zachspears** [comment]
Unable to reproduce. Leaving for a second opinion.

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- On Chrome I was able to replicate this, but not consistently. It only happened the first time I tried to preview a draft post in a new tab. I got a page not found message. When I tried again, it worked.
- On Safari I was able to replicate the blank screen reported by some users in https://github.com/Automattic/wp-calypso/issues/57812 when I tried to preview a new draft post. This happened even when I tried again. The link showing in the browser when I saw the blank screen was https://r-login.wordpress.com/remote-login.php?action=link&back=https%3A%2F%2Fjamiepalatnik.com%2F%3Fp%3D2024%26preview%3Dtrue

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by wiesenhauss** [comment]
User reported issue here: 37278499-hc

**Comment by sudeepbaral** [comment]
Another report here: 5648023-zen

**Comment by villanovachile** [comment]
Another report: 5790561-zen

Provided user with workaround

**Comment by Robertght** [comment]
Another request in 38790499-zen

Theme: Dynamic News(retired)
Browser: Firefox

**Comment by philnick206** [comment]
Another report 5971077-zen

Theme: Lovecraft
Browser: Firefox

**Comment by crisbusquets** [comment]
Another report 6007351-zen

Theme: Bueno

**Comment by jp-imagines** [comment]
Reported in 6010077-zd-woothemes too.
Notably, this site doesn't have a custom domain, but a `.home.blog` free address. Same issue.

**Comment by jeyip** [comment]
@cometgrrl There appears to be an uptick in incidences of this issue recently. Wondering if you've seen any other reports elsewhere.

@Addison-Stavlo At this point, I'm unsure who would be responsible for tackling a problem like this 🤔 Do you happen to know another team that would be more appropriate to keep an eye on this task?

**Comment by cometgrrl** [comment]
@jeyip I am not aware of additional reports beyond what's mentioned here. For now, I'd say let's keep an eye on it, and see if it continues.

**Comment by rickmgithub** [comment]
New one 32083830-hc

**Comment by villanovachile** [comment]
Another report 6592671-zen
user is using Chrome

**Comment by cuemarie** [comment]
This new report: https://github.com/Automattic/wp-calypso/issues/80788 seems to reflect this same issue, but with clearer notes and steps to replicate. Gathering that based on Jamie's [triage notes](https://github.com/Automattic/wp-calypso/issues/68071#issuecomment-1262719207):

>  I was able to replicate this, but not consistently. It only happened the first time I tried to preview a draft post in a new tab. I got a page not found message. When I tried again, it worked.

With that in mind, I'm going to close this issue in favor of the new one. 

📌 ACTIONS
- Closed in favor of #80788
