### ISSUE TITLE
Marketplace search: return `active_installs` field from the API

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#68078]
This is a follow-up issue to #63167.

Currently, the `plugin.active_installs` field is not being returned by the API: https://public-api.wordpress.com/rest/v1.3/marketplace/search?group_id=wporg&fields[]=plugin.title&fields[]=plugin.active_installs&category=popular

Looking at the code, the field is added to the `returnable_fields` array, despite this the field is not returned: 2da84-pb

**Comment by epeicher** [comment]
After a quick initial investigation, I have found that the `plugin.active_installs` is returned  in the `_source` field but not in the `fields` field, code here 2da88-pb

Then, when building the results the field `_source.plugin.active_installs` seems to be skipped by the following logic 2da86-pb/#plain

**Comment by gcsecsey** [comment]
A fix for this issue has been deployed with D87985-code

**Comment by epeicher** [comment]
Hi @gcsecsey, I cannot see the fix in the diff, I added it in a comment as a suggestion but I did not commit any code. Could it be that it has been missed? 🤔

**Comment by gcsecsey** [comment]
Oof, I'm sorry @epeicher, for some reason I've believed your comment to be an addition to the diff here 🤦 
<img width="748" alt="CleanShot 2022-09-27 at 14 47 49@2x" src="https://user-images.githubusercontent.com/11555574/192544238-bf6ecc07-4770-478f-8256-2e0c1597a5ea.png">

I'm going to raise a small diff with this change soon!

**Comment by gcsecsey** [comment]
Raised diff D88613-code

**Comment by epeicher** [comment]
I have reviewed the diff and LGTM. I have added the task to the sprint and changed the status to Ready to Merge 🚢

**Comment by gcsecsey** [comment]
Changes have been deployed in r253339-wpcom
