### ISSUE TITLE
Sites: suspended blogs should have limited capabilities

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#6808]
When a blog is suspended for violating the WordPress.com Terms of Service, all capabilities on the blog should be disabled except for the ability to export, transfer the domain, or purchase a guided transfer.

Related: 555-gh-io, https://github.com/Automattic/wp-calypso/issues/2527

**Comment by folletto** [comment]
Brainstorming about the design of this, we could:

1. Disable all the necessary UI pieces, like with semi-transparency. The downside of this is maintenance when new parts are added.
2. Create a UI ad hoc that provides only the functionalities above. The downside of this is maintenance of this UI over time.
