### ISSUE TITLE
Stats: Spinners don't appear correctly in IE11

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#6809]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/ in IE11
2. Look at any of the stats pages as they load

#### What I expected

Small spinners - as per other browsers

#### What happened instead

Oversized spinners

#### Browser / OS version

IE11 on Windows 10

#### Screenshot / Video

![ie11 spinners](https://cloud.githubusercontent.com/assets/128826/16858786/d02760ae-4a6c-11e6-9883-0e855ee1ebc9.png)

#### Context / Source
#dogfooding  #manual-testing

**Comment by lancewillett** [comment]
I couldn't reproduce this today on Windows 10, IE 11 running wpcalypso.

<img width="1395" alt="screen shot 2016-10-14 at 13 01 57" src="https://cloud.githubusercontent.com/assets/66797/19401137/70c21598-920e-11e6-92c6-03273f9ddc48.png">
