### ISSUE TITLE
Reader: Tags: change 'follow a tag' to 'find a tag'

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#681]
Steps to reproduce:
1. Go to https://wordpress.com/
2. Search for a tag in the left sidebar

<strong>Result:</strong> the tag is automatically followed even though I have only searched.

![screen shot 2015-11-24 at tue nov 24 3 57 17 pm](https://cloud.githubusercontent.com/assets/1119271/11380473/35cba7b4-92c4-11e5-9b7a-271d49f6883d.png)
<sup>Seen at https://wordpress.com/tag/kite-surfing using Firefox 42.0 on Mac OS X 10.10.5</sup>

We should remove the automatic follow of a tag.

**Comment by shaunandrews** [comment]
I think this'll be a non-issue when #724 is merged, as it'll look like less of a "search for tags" and more obviously a "follow tag" input.
