### ISSUE TITLE
[Invite Role] Make sure RTL works with the new template

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#68109]

**Comment by TimBroddin** [comment]
The new template seems to honor RTL:

Invitee has an RTL language:
![Image](https://user-images.githubusercontent.com/528287/192524885-bd2d7416-1dc4-43af-baf3-c63d7e0d9857.png)

Invitee has a LTR language:
![Image](https://user-images.githubusercontent.com/528287/192525023-3d923f74-923f-4a8c-975b-c2a1b7b6a888.png)

I tried changing site and inviter's language, but this did not seem to affect the received e-mail.
