### ISSUE TITLE
[Invite Follower] Make sure RTL works with the new template

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#68110]

**Comment by TimBroddin** [comment]
Inviter (LTR site) -> Follower (RTL)
<img width="1726" alt="CleanShot 2022-09-28 at 09 27 58@2x" src="https://user-images.githubusercontent.com/528287/192715839-49a52714-99c0-426c-8fac-2ee368e619a3.png">

Inviter (RTL site) -> Follower (LTR)
<img width="998" alt="CleanShot 2022-09-28 at 09 29 45@2x" src="https://user-images.githubusercontent.com/528287/192716122-644133e4-bad5-4a99-802c-39ce2c1c3b3c.png">

Inviter (RTL site) -> Follower (not registered):
<img width="1040" alt="CleanShot 2022-09-28 at 09 34 38@2x" src="https://user-images.githubusercontent.com/528287/192717133-37d8c13e-2fb9-4b26-b4ed-79a8a590803c.png">
