### ISSUE TITLE
Fix race condition in plugins search component

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#68115]
### Details

To reproduce

- With "plugins-plans-page" config feature enabled
- On a plan lower than business
- Go to the /plugins page
- Select a category
- Then search for term
- Then select a plugin
- Then try to install and end up on the Plugins Plans page
- Now click on Search results in the breadcrumbs
- The URL changes correctly, but we're still on the Plugins Plans page

Much more context in the comments of this PR [here](https://github.com/Automattic/wp-calypso/pull/67989#pullrequestreview-1113387970).

### Checklist

- [ ] Race condition addressed, bug fixed.

### Related

https://github.com/Automattic/wp-calypso/pull/67989

**Comment by lsl** [comment]
[Potential fix?](https://github.com/Automattic/wp-calypso/pull/67989#issuecomment-1253711522)

**Comment by claudiucelfilip** [comment]
> [Potential fix?](https://github.com/Automattic/wp-calypso/pull/67989#issuecomment-1253711522)

Pushed the fix to #68386
