### ISSUE TITLE
Site Settings: Make it clearer when deleting a site with upgrade(s) owned by another username

### ISSUE THREAD

**Issue by hafizrahman** [Automattic/wp-calypso#6813]
#### Steps to reproduce
1. Have a test site with two users, let's say user A and user B
2. Let user A has an upgrade on the site, none for user B
3. Log in as user B
4. Go to https://wordpress.com/settings/general/:site and click the "Delete Site" section
5. This pop-up will appear https://cloudup.com/i4kCSRiGIyM
6. Click "Manage Purchases"
7. This will open user B's https://wordpress.com/purchases page, which will be empty

As @spncrb mentioned in #6798, this is potentially confusing because the pop-up in point 5 says that the user has upgrades that need to be cancelled first, but the Purchases page in point 7 will show no upgrades (because the upgrade is owned by another user).

@spncrb suggested that we add a secondary modal that says the site has purchases from another user and they will have to cancel them to delete the site?

I also wonder whether:

A) The secondary modal need to be detailed and display what those purchases are and which other usernames owned them (for ease of communication, maybe), or

B) the modal should be discreet and simply mention that there are upgrade(s) owned by other user(s)

I think option A is better, but not entirely sure about the privacy aspect.

**Comment by spncrb** [comment]
Thanks for opening this Hafiz!

For the A vs. B - I'd say if the user is an admin on the site, then A is good, if they aren't, then a generic "please talk to the administrator of the site" message seems more appropriate.
