### ISSUE TITLE
Accordion Block Crash

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/wp-calypso#68130]
### Quick summary

When you click them in the editor they crash, without even the option to recover or switch to HTML.

### Steps to reproduce

1. Create a page on an atomic site
2. Add an accordion block (I used similar settings to the customer who first reported this, an image, header, and paragraph block in the first accordion item, then in the second accordion item a columns block with an image in one and a header in the other).
3. Save and refresh the editor.

### What you expected to happen

You should be able to click on an coblocks block and edit it.

### What actually happened

the block crashes with no chance to even convert to HTML or Attempt Recovery

### Context

hc-27625415
zd-5575633

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

no

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Using the list view to click on the accordion items.

**Comment by JoshuaGoode** [comment]
If this can be consistently reproduced on another site with other content, and we eliminate all WPCOM things, this might end up needing to be reported directly to CoBlocks. The accordion blocks isn't a block WordPress.com provides -- it's an extra included in the full CoBlocks plugin which we don't support.

https://github.com/godaddy-wordpress/coblocks/issues

Or, https://wordpress.org/support/plugin/coblocks/

**Comment by JoshuaGoode** [comment]
It appears a contributor to the issue is the current symlinked Gutenberg version, 14.0.2. Not sure why.

Deactivating Gutenberg allows things to work as expected. 

A potential workaround, albeit not great, would be to unsymlink Gutenberg via `wp wpcomsh plugin use-unmanaged gutenberg`

**Comment by zyousafi** [comment]
> If this can be consistently reproduced on another site with other content, and we eliminate all WPCOM things, this might end up needing to be reported directly to CoBlocks. The accordion blocks isn't a block WordPress.com provides -- it's an extra included in the full CoBlocks plugin which we don't support.

Tested this thoroughly on my WordPress.com site and my self-hosted WordPress.org site.  I can recreate the issue consistently, so it's not a WordPress.com-specific issue

**Comment by zyousafi** [comment]
> A potential workaround, albeit not great, would be to unsymlink Gutenberg via `wp wpcomsh plugin use-unmanaged gutenberg`

While deactivating the Gutenberg plugin worked, this workaround did not.  The unsymlinked version of Gutenberg was still conflicting with the Accordion Block and it was throwing the same error as before

**Comment by i11za** [comment]
Another user report here: 5585953-zd-woothemes - AT site / Shawburn theme

Tested on own test site with same theme Shawburn and Twenty Twenty One and seeing the same error. 

In both cases deactivating Gutenberg resolves the issue, but the unsymlinked version of Gutenberg is still conflicting with the Accordion Block.

**Comment by paxblueribbon** [comment]
I also posted on godaddy/coblocks github
https://github.com/godaddy-wordpress/coblocks/issues/2428

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO

- Recording of behavior in my test:

https://user-images.githubusercontent.com/27249804/192635728-af065885-7a54-403f-b13a-d8e057432fa1.mov

---

>Tested this thoroughly on my WordPress.com site and my self-hosted WordPress.org site. I can recreate the issue consistently, so it's not a WordPress.com-specific issue

>While deactivating the Gutenberg plugin worked, this workaround did not. The unsymlinked version of Gutenberg was still conflicting with the Accordion Block and it was throwing the same error as before

Also thank you @zyousafi for your detailed notes here! 

This bug looks pretty thoroughly scrubbed, and now reported here: https://github.com/godaddy-wordpress/coblocks/issues/2428

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Added to 'HE Cross-repo Watchlist' project board
- awaiting updates on the CoBlocks issue report listed above

**Comment by ccwalburn** [comment]
I had a user with this issue last week and referred them to the plugin support since we don't support CoBlocks, but I wanted to mention the workaround I found in case it helps others. 

I am consistently able to edit an Accordion block by selecting it in List View.


https://user-images.githubusercontent.com/32983813/193358954-3cc111fd-e279-433a-9fc8-8ff9e67270c1.mp4

**Comment by AnthonyLedesma** [comment]
@paxblueribbon Thanks for the report on the CoBlocks side. With Gutenberg version 14.2.0, I was not able to replicate it.  I understand there was something with Gutenberg going on like a pinned version is that something I can run on the open-source WordPress side?

I also see people reporting sites in WordPress.org able to replicate. I was not able to reproduce with WP 5.9.2 or 6.0.2 or with Gutenberg active and with JetPack active. I also tried Go theme and TwenetyTwenty and both are fine. 

Is there any additional information you could provide for us to go on?

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

I can't reproduce the issue anymore. 

https://github.com/Automattic/wp-calypso/assets/67279475/86f91a4f-c3ff-425f-887e-eec1432b997b

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
