### ISSUE TITLE
Task: Consider showing the Help Center in My Home

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#68147]
### Details

Currently, the help Center is hidden from My Home to avoid duplicating "Get Help" widget in the bottom of the page. This has some merit, but it's making the masterbar unreliable. The Help Center shows in many places except My Home. But it's pretty hard for the user to infer why.

I think a tiny 24x24 icon shouldn't interfere that much with "Get Help".

**Comment by jordesign** [comment]
My 2c is that having consistency in the masterbar is far more important than being worried about doubling up on ways for users to be helped.

**Comment by alshakero** [comment]
Closing as done in https://github.com/Automattic/wp-calypso/pull/68568
