### ISSUE TITLE
Marketplace: Redirect user to redirect_url after purchasing SaaS product

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#68148]
## details

The SaaS product purchase capabilities were added in #67547 and #67652. But the problem right now is users are not being directed to redirect URLs after purchasing SaaS products from calypso. We need to get the redirect URL from the associated billing intent.

**Comment by epeicher** [comment]
#### Backlog grooming
The task to implement the backend changes required for this is https://github.com/Automattic/wp-calypso/issues/68441. 

When the user completes the checkout process for SaaS product, we need to fetch associated billing intent from the backend and redirect the user to `redirect_url`.

**Comment by cpapazoglou** [comment]
Let's check if we can add this parameter to the `purchases` array of objects first.

**Comment by cpapazoglou** [comment]
Haven't done any progress here. The idea is:
- in [MarketplaceThankYou](https://github.com/Automattic/wp-calypso/blob/b861acf21449733c70426391383b4264866e9634/client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx#L53)
- we get the latest transaction
- check if there is a purchase with a `redirect_url`
- redirect to this `redirect_url`

**Comment by epeicher** [comment]
Diff reviewed ✅ D91398-code
