### ISSUE TITLE
Document Link-in-Bio patterns and how they work in onboarding

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#68176]
# Description

Link-in-bio patterns have their own unique behavior in onboarding, headstart, and other things.   @alaczek and @arthur791004 and @alshakero please work together to create a Field Guide page that documents all the things you know.   So that next time someone asks (p1663898780391079-slack-CRWCHQGUB) how to update patterns we can provide them with a FG link.

From Ola: I have three questions for the design picker:
* how do I remove a design from the lineup?
* how do I change order they are displayed in?
* how fast will I see changes (are these cached, how can I flush the cache)?

# ToDo
- [ ] Add documentation to FG, this could go in this [onboarding area of the FG](PCYsg-D3w-p2) 
- [ ] Think if there is anything else related to this flow that needs documenting

See
https://dotcompatterns.wordpress.com/category/link-in-bio/
https://github.com/Automattic/themes/tree/trunk/lynx
https://wordpress.com/setup/patterns?flow=link-in-bio

**Comment by arthur791004** [comment]
Here is the document: PCYsg-L1F-p2 cc @alshakero

**Comment by arthur791004** [comment]
@alaczek Could you help to check whether something else needs to document in PCYsg-L1F-p2 ? thanks!

**Comment by autumnfjeld** [comment]
Nice job Arthur. We can probably close this.  If @alaczek or @alshakero want to make changes/edits they can do so.

**Comment by arthur791004** [comment]
Okay!
