### ISSUE TITLE
Surface themes with style selection towards top of theme grid

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#68183]
# Description
This  can be done post-launch.  Not a blocker for launch.
See pdtkmj-Ad-p2

We'd like to ensure we surface themes that offer style selection in a more prominent position in the DP.    They can be mixed in or weighted.    

One idea: say we have 8  style-themes.  We make sure these 8 are in the top 12 of themes shown.

Also ok to go the easy route and just show them as the first 8.

# Dev tasks
- [ ] Adapt theme randomization so themes with styles get preference at top of DP.
- [ ] Ensure randomization sill works amongst all themes

# Testing

**Comment by autumnfjeld** [comment]
Let's ship this 7-10 days after shipping Style Selection so we can do a metrics check on influence of having themes at the top of the grid.

**Comment by taipeicoder** [comment]
Closing as it's shipped. Will follow up with metrics in #68463
