### ISSUE TITLE
Pattern Assembler - Scroll to a specific section in the preview 

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#68182]
We want to scroll to a specific section in the preview when it is chosen. 

We have done that for the footer in https://github.com/Automattic/wp-calypso/pull/68141 using the CSS selector `footer`, we could have used `.site-footer-container` instead because all the footers have that class, and we only allow adding one footer in the PA.

However, the sections don't have a specific class or ID to select them and scroll to show them. Some possible solutions are:

- Each pattern has a unique `slug`, so we could use it to add a class in the HTML with an index because the same pattern can be added multiple times. This change will be done in the API `/block-previews/site`.
- Each pattern seems to have the class `wp-block-group` in the container `div`, so we could use it to find the section using its position in the list of selected sections. This solution seems simpler because doesn't change the API. <img width="356" alt="Screen Shot 2565-09-23 at 12 57 40" src="https://user-images.githubusercontent.com/1881481/191899915-928d90a2-7c3d-482f-ab74-48dae35800c7.png">
- Any other ideas? @Automattic/ganon

**Comment by bangank36** [comment]
> Each pattern seems to have the class `wp-block-group` in the container `div`, so we could use it to find the section using its position in the list of selected sections. This solution seems simpler because doesn't change the API.

:+1:  for this, we can target section using their index, the challenge is to find out which is the latest pattern has been added/modified into `PatternAssemblerPreview`

**Comment by miksansegundo** [comment]
> 👍  for this, we can target section using their index, the challenge is to find out which is the latest pattern has been added/modified into PatternAssemblerPreview

The preview is reloaded every time a section is added/sorted/replaced; we could track that change using the section ID to trigger the scroll when the preview loads.

I think the scrolling feature added in D88290-code can be reused passing a selector like `.entry-content > .wp-block-group:nth-child( [position] )`.

We must first confirm that the class `.wp-block-group` exists for all section patterns.

**Comment by fushar** [comment]
> We must first confirm that the class .wp-block-group exists for all section patterns.

I have a hunch that it is not present if the pattern only consists of a single block, can we try to investigate this?

**Comment by miksansegundo** [comment]
> I have a hunch that it is not present if the pattern only consists of a single block, can we try to investigate this?

I did it 😊 and the class `.wp-block-group` is present in all [the section patterns selected](https://github.com/Automattic/wp-calypso/issues/66789) by our designers for the PA.

**Comment by bangank36** [comment]
Follow up on this [bug](https://github.com/Automattic/wp-calypso/pull/68339#issuecomment-1263004881), one of the reason that messes up the scrolling of block preview is

*    Not all pattern is tied to 01 `.wp-block-group` class, for example, [contact-5](https://dotcompatterns.wordpress.com/2020/05/22/contact-5/) pattern consists of 2 `.wp-block-group`

Therefore I think we still need to update API ( `transform_patterns_to_html` ) to wrap the pattern preview HTML inside a container eg `.wp-block-content-wrapper` to make sure each pattern is paired with 01 container

The next thing to discuss is how to identify the position of pattern preview on site preview

1.  Keep using index like now and target the element with `nth-child` selector  
    - Note that we still have to deal with the wrong element scrolling when re-order the patterns
2.  Assign unique key for each `.wp-block-content-wrapper` to help target the element on the preview, I proposed pattern key implemented using increment index [here](https://github.com/Automattic/wp-calypso/pull/68286/files#diff-238ed6a820087c26a46b9cfe70db2c6a0e8e9408913101ee0aad08dddaf5f811R65)  
    - Then on API we should explode the pattern key string to get the correct pattern id  
    - Note that there should be some potential issues with identifying correct re-orders/added/removed pattern on preview  
      
    Any ideas cc: @Automattic/ganon

**Comment by arthur791004** [comment]
I think it might be better to keep using `nth-child` selector. I'd not prefer to update the API for this feature unless it's inevitable

**Comment by bangank36** [comment]
> *   Not all pattern is tied to 01 `.wp-block-group` class, for example, [contact-5](https://dotcompatterns.wordpress.com/2020/05/22/contact-5/) pattern consists of 2 `.wp-block-group`

@arthur791004 if you have a look at the mentioned pattern, you can see it consists of 2 `.wp-block-group`  
 

![Markup 2022-09-30 at 20.13.23.png](https://cdn-std.droplr.net/files/acc_1243635/82gn8j)

## In preview

![Markup 2022-09-30 at 20.15.58.png](https://cdn-std.droplr.net/files/acc_1243635/Vwb3en)

**Comment by arthur791004** [comment]
@bangank36 I think we could probably inquire of designers whether we could wrap this kind of pattern into a single group. What do you think? cc @autumnfjeld @alaczek

**Comment by bangank36** [comment]
> @bangank36 I think we could probably inquire of designers whether we could wrap this kind of pattern into a single group. What do you think? cc @autumnfjeld @alaczek

Definitely!

**Comment by miksansegundo** [comment]
@bangank36 In this other [issue](https://github.com/Automattic/wp-calypso/issues/66789#issuecomment-1261609964), we are discussing removing that pattern from the list to provide a consistent look & feel. 

Do you know if there are other patterns affected? I'll review all the patterns again to check that they have only one `.wp-block-group`.

**Comment by bangank36** [comment]
I'll check them again

**Comment by miksansegundo** [comment]
@bangank36 I already checked all patterns, after this [PR](https://github.com/Automattic/wp-calypso/pull/68509) is merged to remove some patterns, every pattern will have only one wrapper with `.wp-block-group`.

**Comment by bangank36** [comment]
Then I think this [PR](https://github.com/Automattic/wp-calypso/pull/68339) is good to go as well, without touching the API again

**Comment by autumnfjeld** [comment]
>  I think we could probably inquire of designers whether we could wrap this kind of pattern into a single group. What do you think? cc @autumnfjeld @alaczek

Probably wise to ask that in #themes or directly to a themer in slack. 😃

**Comment by miksansegundo** [comment]
I already asked Ola in slack p1664321562054549/1664256309.093529-slack-CRWCHQGUB

> This means each patterns needs to be wrapped in a group block… it is a practise that we’re using with new patterns. Although one case where we don’t is if the pattern is wrapped in a cover block, then we typically don’t add a group around.

She mentions an exception when using a cover block, but that is not the case for any patterns we have selected for the PA. So we should be good because in the future we will have to update the list of pattern IDs manually so we can check them before adding them to the PA.

**Comment by bangank36** [comment]
Closed as landed
