### ISSUE TITLE
WPCOM SSH: Allow a user to attach their SSH key to a site

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#68204]
Once the REST API endpoint is complete (969-gh-Automattic/dotcom-forge) and a user can add a SSH key to their account (#68201), let's add some UI to allow a user to attach their SSH key to a site.

**These are quick and dirty mockups.** Feel free to improve upon them during implementation.

When the user doesn’t have a SSH key and no SSH keys are attached to the site, here’s how the UI would appear:

![image](https://user-images.githubusercontent.com/36432/191956574-c41e7511-48e0-427e-acda-c2b2cd655dde.png)

When a user does have a SSH key and no SSH keys are attached to the site, here’s how the UI would appear:

![image](https://user-images.githubusercontent.com/36432/191956598-ebf39c3f-f921-4dc2-910b-c75dd5e4bfa4.png)

![image](https://user-images.githubusercontent.com/36432/191956604-b5d65c1c-f847-4b52-9ed3-a310efa1f97c.png)

When another user’s SSH key is added to the site but your user doesn’t have a SSH key, here’s how the UI would appear:

![image](https://user-images.githubusercontent.com/36432/191956646-fc7536d7-f39f-4cec-a852-7d9d1e188902.png)

**Done is:**
* The necessary UI is added for a user to attach a SSH key to a site, or remove an already attached SSH key.
* Some notification UI appears when the user successfully performs an action.
* Some error UI appears if a API request fails.
* A Tracks event is fired when the user successfully attaches or detaches a SSH key.
* The feature is accessible everywhere except staging and production behind a `hosting/ssh-keys` feature flag.

**Comment by danielbachhuber** [comment]
From team meeting: if user clicks 'Add SSH key to your account', it would be nice if we pointed them back to 'Hosting Configuration' after they save. We can include a little back banner for this.

**Comment by sejas** [comment]
@danielbachhuber, should a user who has access to the admin site be able to delete the ssh belonging to other users?
Or alternatively, should each user be able to delete only their own keys?

**Comment by danielbachhuber** [comment]
> should a user who has access to the admin site be able to delete the ssh belonging to other users?

@sejas Yes.
