### ISSUE TITLE
LaunchPad - checklist items not in tab navigation on firefox/safari

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#68206]
Using tab navigation in the launchpad should allow us to select and use checklist items. Currently, this seems to work as expected in Chrome but does not in Firefox or Safari.

Expected behavior (Chrome) - checklist items in keyboard nav:
![tab-works](https://user-images.githubusercontent.com/28742426/191985117-ec8ceaa9-b628-44a9-b21c-0169fda2f5d3.gif)

Unexpected behavior on Firefox/Safari - checklist items not tabbable:
![no-tab-nav](https://user-images.githubusercontent.com/28742426/191985303-894dcb61-fbef-4cbc-aec9-a197af40f7aa.gif)

**Comment by jeyip** [comment]
See p1663943878098109-slack-CHN6J22MP for context

For FireFox, it appears as if users need to enable certain operating system / browser settings to keyboard navigate to and from links. See [this stackoverflow answer](https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox) for more info.

`In Firefox, type "about:config" in the URL bar. There is no accessibility.tabfocus preference on the mac, so you'll have to make one. Right click in the window, create a new "integer" pref, and set it to 7.`

If interested in the specific settings and why we set them to `7`, here are [the relevant docs](http://kb.mozillazine.org/Accessibility.tabfocus)

**Comment by jeyip** [comment]
For Safari, besides needing to press the tab key a large number of times before seeing any visible page interaction, the focus task focus appears to work as expected for me 🤔 

![2022-09-23 15 16 52](https://user-images.githubusercontent.com/5414230/192063972-76e577bb-fd0b-4612-a1b5-1995e2c1320f.gif)
