### ISSUE TITLE
Marketplace search: index WC.com product fields to the same schema as WP.org

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#68219]
In https://github.com/Automattic/wp-calypso/issues/63903 we've synced the existing WooCommerce fields to the jetpack-search ES index. To proceed with fetching search results from both WP.org and WC.com with a single request, we'll need to map the newly synced fields to the same `plugin.*` schema as we did with WP.org plugins in D81205-code.

We're still missing one WC.com specific field, `active_installs` from the index, I've created a separate issue for it: https://github.com/Automattic/wp-calypso/issues/68218

I think we could proceed with creating a mapping for the rest of the fields, and following it up later, once we've successfully synced the number of installs. Is this something that @robfelty or the @Automattic/prometheus team can help us with, perhaps?

**Comment by epeicher** [comment]
#### Backlog grooming

- We would need to create a mapping similar to D81205-code. 
- Potentially, we could create a new `WPES_WPCOM_Plugin_Post_Field_Builder` for getting the mapping from WC.com fields
- Add the WC.com id to this condition to the following condition 2de28-pb

**Comment by gcsecsey** [comment]
Draft diff raised: D90619-code

I've added a new field builder that's going to extend the existing one for WP.org plugins, and started mapping the WC.com specific fields to the index. Progress and testing instructions are shared on the diff.

**Comment by gcsecsey** [comment]
I've added the ES query discussed in https://github.com/Automattic/wp-calypso/issues/68218 to the diff.

**Comment by gcsecsey** [comment]
We've discussed with @cpapazoglou to split the diff above to multiple smaller diffs, to make reviewing and incremental deployments easier.

I've raised the first smaller diff, which adds the new field builder class for WC.com products: D90850-code

**Comment by gcsecsey** [comment]
Raised a draft diff that contains the changes to the field mappings: D91024-code

**Comment by gcsecsey** [comment]
The diff is now deployed in r256401-wpcom
