### ISSUE TITLE
Marketplace search: Add number of installs to WooCommerce products

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#68218]
In #63903 we've synced the existing WooCommerce fields to the `jetpack-search` ES index. We have a set of fields required to be able to show search results in Calypso, these are tracked in this table: pdh6GB-Mm-p2#comment-1632

Currently, only the lack of `active_installs` field or similar is missing. We should investigate how we could estimate and assign the number of installations to all existing WooCommerce products.

**Comment by gibrown** [comment]
@robfelty let's take the details to p2, but we could maybe estimate this from Jetpack install data.

**Comment by gcsecsey** [comment]
I've experimented with querying this data from the `jetpack-sites` index and created an aggregation where I can filter for the premium plugin slugs (as we have the number of installs for all other plugins):

```json
GET jetpack-sites-10/_search?routing=1
{
  "size": 0,
  "aggs": {
    "counts": {
      "terms": {
        "field": "enabled_plugin_slugs",
        "include": [
          "woocommerce",
          "woocommerce-bookings",
          "woocommerce-subscriptions"
        ]
      }
    }
  }
}
```

@gibrown @robfelty Do you think we could use these results dynamically, eg. when indexing WooCommerce products to the `jetpack-search` index perhaps?

**Comment by gibrown** [comment]
Ya it should be ok to use something like that in the indexing job and get the data from site profiles. I would probably suggest [a filters aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/search-aggregations-bucket-filters-aggregation.html) rather than a terms agg that uses "include". Let's discuss it on the wpcom diff though.

**Comment by gcsecsey** [comment]
Thanks for the suggestion @gibrown, I tested a filters aggregation query, and it also works great:
```json
GET jetpack-sites-10/_search?routing=1
{
  "size": 0,
  "aggs": {
    "plugin_install_counts": {
      "filters": {
        "filters": {
          "woocommerce-bookings": {
            "term": {
              "enabled_plugin_slugs": "woocommerce-bookings"
            }
          },
          "woocommerce-subscriptions": {
            "term": {
              "enabled_plugin_slugs": "woocommerce-subscriptions"
            }
          }
        }
      }
    }
  }
}
```

In https://github.com/Automattic/wp-calypso/issues/68219 we'd like to index other fields from WC.com to `plugin.*` fields similarly to how we did with WP.org results in D81205-code. I'll add these changes to the same diff in our next sprint.

**Comment by gcsecsey** [comment]
@gibrown I raised a draft diff, I'm still working on the rest of the fields, but I already added the ES query to get the number of installations, please take a look at it when you can. 🙂 D90619-code
