### ISSUE TITLE
Pro plan is still mentioned in the com-vs-org landing page

### ISSUE THREAD

**Issue by emilyaudela** [Automattic/wp-calypso#68225]
### Quick summary

On the https://wordpress.com/com-vs-org/ landing page, there is still a mention of the Pro plan which has been deprecated for over a month. This needs to be updated to say Business and eCommerce plan.

### Steps to reproduce

1. Start at https://wordpress.com/com-vs-org/
2. Scroll down to the plan comparison section of the page.
3. The third item under WordPress.com says `Choose from hundreds of beautiful designs and customize them for your business site, blog, or portfolio. If you purchased a WordPress theme elsewhere? No problem: the WordPress.com Pro plan lets you install any theme you’d like.` The second second should say "the WordPress.com Business and eCommerce plans let you install all the themes you'd like.
<img width="1515" alt="Screen Shot 2022-09-23 at 11 12 36 AM" src="https://user-images.githubusercontent.com/36699353/192018390-5c256997-6088-4d7d-b85d-c6614a558210.png">

### What you expected to happen

The landing page shouldn't mention the deprecated Pro plan.

### What actually happened

Pro plan was mentioned instead of Business and eCommerce plans.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- "If you purchased a WordPress theme elsewhere? No problem: **the WordPress.com Pro plan** lets you install any theme you’d like."
- Copy is still present

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by niranjan-uma-shankar** [comment]
Will be fixed in D95659-code.
