### ISSUE TITLE
Clean up: setup flow related feature flag and its code

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#68244]

**Comment by autumnfjeld** [comment]
Is this still "In Progress"?

**Comment by fushar** [comment]
cc: @arthur791004 as the original creator of this issue

Could you check the linked PRs and see if there's anything else in your mind about the cleanup?

**Comment by arthur791004** [comment]
Thanks for working on this issue sooooo quickly!

I thought we could also remove the following flags
* signup/design-picker-use-featured-picks-buttons
* signup/ftm-flow-non-en
* signup/starting-point-courses
* signup/site-vertical-step
* signup/hero-flow-non-en

Besides, these flags are enabled for a long time, we might probably consider removing them as well
* signup/design-picker-premium-themes-checkout
* signup/goals-step
* signup/goals-step-2

**Comment by autumnfjeld** [comment]
I'm going to move this to the backlog, it can be picked up after we ship the PA MVP.   We'll need many brains focused on PA til then.

**Comment by arthur791004** [comment]
Close it as it's completed 🎉
