### ISSUE TITLE
Simple sites unable to send pingbacks

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#68245]
### Quick summary

Sending a pingback between simple sites is not received by the target site.

### Steps to reproduce

1. Create or open two sites, both simple (plan doesn't matter).
2. Configure both sites to send and receive pingback notifications.
3. On site 1, write a dummy test post - this will be your target.
4. On site 2, write a dummy test post that links back to the post you wrote on site 1.

### What you expected to happen

Site 1 should receive a pingback from site 2.

### What actually happened

Site 1 receives no pingback, site 2 displays no failure message.

### Context

Reported in 5578307-zd-woothemes, and tested just now by me. Previous HE tested for https://github.com/Automattic/wp-calypso/issues/55472, which may also be related.

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

### Workaround details

Comments will still work, if a user wants to manually link their post on the target site's post.

**Comment by jamiepalatnik** [comment]
Just noting that the user requested an email follow-up if there is any update to share: 5578307-zd-woothemes

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I followed the instructions to test this. I tried two tests, posting a link to the other site on each site. Both sites received pingback notifications in the comments as expected.
- Screenshot: 

<img width="1218" alt="Pingback" src="https://user-images.githubusercontent.com/30788962/193109349-eacb427d-1928-4e4b-a94d-52f004bdbbf4.png">

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @arinoch Please feel free to reopen if you have other user reports or more details on how others can replicate this. Thank you!

**Comment by marcuswisecaesar** [comment]
Reopening this as I've just run into this in chat and replicated on my test site. 

### Quick Summary
Sending a pingback between simple sites is not received by the target site. (this began happening for a user in chat on 2/15) 

### Steps to reproduce
Create or open two simple sites (the plan doesn't matter).
Configure both sites to send and receive pingback notifications.
On site 1, write a dummy test post - this will be your target.
On site 2, write a dummy test post that links back to the post you wrote on site 1.
What you expected to happen
Site 1 should receive a pingback from site 2.



### What actually happened
Site 1 receives no pingback; site 2 displays no failure message.

### Context
Reported in 36291396-hc, tested and replicated on two simple test sites, 1 personal, and 1 Business non-AT.

### Platform (Simple, Atomic, or both?)
Simple

### Theme-specific issue?
No response

### Browser, operating system, and other notes
My testing was in Chrome on Mac OS Ventura 13.2.1

### Reproducibility
Consistent

### Severity
All

### Available workarounds?
There is no user impact.

### Workaround details
Comments will still work if a user wants to link their post on the target site's post manually.

**Comment by marcuswisecaesar** [comment]
The user would like a response here :

- [ ] 5967982 - zen

**Comment by csonnek** [comment]
Report via Twitter: https://twitter.com/DAntion/status/1626958430798848002

**Comment by csonnek** [comment]
Three more users having trouble from the forums: https://wordpress.com/forums/topic/pingbacks-39/?view=all

**Comment by csonnek** [comment]
Another in https://wordpress.com/forums/topic/self-pingbacks-are-not-working/?view=all

**Comment by thekingsprojects** [comment]
Another case here: 5966347-zen

This user's case seems to be about pingbacks from their own posts (one post linking to another). I can replicate on my simple site; I wasn't able to receive pingbacks on my own posts, even with pingbacks enabled.

I also did some testing between my simple test site and an AT one; the simple site received a pingback when the AT site linked to one of its posts, but when the simple site linked to AT, there was no pingback received by the AT site. So it may be any pingbacks being initiated by simple sites at all, no matter what plan the "target" site has.

**Comment by carolframen** [comment]
Another report #5964036-zen

**Comment by carolframen** [comment]
#5969591-zen

**Comment by jorpdesigns** [comment]
Another report in 5969787-zen

Site is simple and they are not receiving pingbacks between posts on the same site.

**Comment by jorpdesigns** [comment]
Reported in 5981758-zen

No pingbacks received between posts on the same (simple) site.

**Comment by Robertght** [comment]
Another case here: 5970613-zen.

This started happening on Feb 15 for the user.

**Comment by dragstor** [comment]
5964114-zen

**Comment by mdtanjid0** [comment]
5967982-zen came again and asked about the update ( just a note ).

**Comment by cintacks** [comment]
Another update request for 5964114-zd-woothemes

**Comment by ersatzpenguin** [comment]
Another report in 5990448-zd-woothemes.

**Comment by tyxla** [comment]
Reported in #73821 also, I've closed it in favor of this one.

**Comment by ttcath** [comment]
but looks like some missing pingback from 2023.2.25 to 2023.2.28 restore, rest pingback from date 2023.2.10 to 2023.3,1, eveyday, I add 4 pingback on some post on the same site still missing, but the link added work. @tyxla

**Comment by ttcath** [comment]
@tyxla it looks like the pingback after 2023.3.2 on the site appear twice, pls look at it. thx

**Comment by tyxla** [comment]
> @tyxla it looks like the pingback after 2023.3.2 on the site appear twice, pls look at it. thx

Hey, @ttcath I'm not sure I understand. I've taken a look at a few of the posts published after March 2nd, 2023, and didn't see any pingback appearing twice. Could you please provide more details?

**Comment by ttcath** [comment]
@tyxla   sorry for the mistake. I means, that the pingback from 2023.2.10 to 2023.2.24 missing. Pingback from 2023.2.25 to 2023.2.27 just restore a little. Pingback after 2023.3.2 appear usual, but delay notifcation.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Test steps:

1. Opened Personal and Premium plan sites
2. Enabled Pingbacks on both, under Discussions > Settings
3. Enabled pingbacks & comments on Premium Plan post https://mqtest262591086.wordpress.com/2023/02/06/fish/
4. Created a new post on the Personal site and shared that link
5. Published Personal Site post
6. No notification occurred on the Premium plan site, and no pingback appears on the post

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by ttcath** [comment]
Dear @tyxla 

Today, I add two pingback into a post, but pingback is missing

https://ttcath.org/2023/03/10/intenzioni-di-preghiera-del-santo-padre-2024-cim-cn/
https://ttcath.org/2023/03/10/intenzioni-di-preghiera-del-santo-padre-2024-tra-cn/

both two links add as pingback into those two posts 
https://ttcath.org/2023/03/27/prot-13-23-tt-tra-cn/
https://ttcath.org/2023/03/27/prot-13-23-tt-sim-cn/

So, totally, there must be 4 pingpacks, but in fact, none.

**Comment by cuemarie** [comment]
@Automattic/loop Anything that your team can check out here?

**Comment by cuemarie** [comment]
Forums report (same user):

- https://wordpress.com/forums/topic/pingbacks-from-prior-url/
- https://wordpress.com/forums/topic/pingbacks-not-working-anymore/

**Comment by davemart-in** [comment]
Thanks for the ping @cuemarie. This is the first I've heard of this. I have added this to our bugs board and attached a "High" priority to it. I'm not sure exactly when we will be able to investigate, but we'll update this thread when we do.

**Comment by cuemarie** [comment]
Thanks @davemart-in ! We've updated our triaging process since this was first filed to include a ping to teams that get assigned, so I figured it just hadn't really hit y'alls inbox yet.  Appreciate the 👀 !

**Comment by roo2** [comment]
👀 having a look at this now. I was able to see the pingback when posting a link from my a8c account but not from a different test account. I'm not familiar with this feature and a search for 'pingback' returned 3.5k results in 1.3k code files 😆 but I'll start digging.

**Comment by roo2** [comment]
At least for my test blog, I've been able to trace it back to an akismet spam check that happens before sending the pingback. 30854-pb/

This would explain why some people are seeing this issue and others are not.

Perhaps the spam filter is too sensitive or getting caught on something innocent. I'll dig into what's causing this tomorrow 👀.

**Comment by davemart-in** [comment]
cc @stephdau  - Do you know who we could chat with on the Akismet side of things about this?

**Comment by roo2** [comment]
posted internally to ask for help from the akismet side pZbK5-7tu-p2

**Comment by stephdau** [comment]
> cc @stephdau - Do you know who we could chat with on the Akismet side of things about this?

This has now been handled on the Akismet end, and should no longer be an issue. 🙂

**Comment by roo2** [comment]
It fixed it for me. I'll close this as fixed unless more reports come in.
