### ISSUE TITLE
Pattern Assembler - Transitions for pattern list items

### ISSUE THREAD

**Issue by bangank36** [Automattic/wp-calypso#68258]
## Description

  
We need to add transition to the pattern list in PA flow when an item is:

*   Added
*   Removed
*   Updated position

## Acceptance Criteria

  
TBD

## Reference

Related [**#67897**](https://github.com/Automattic/wp-calypso/issues/67897)

**Comment by bangank36** [comment]
Closed as Landed

**Comment by autumnfjeld** [comment]
Just a little tip: it's always good to include a screenshot in any issue when possible.  Makes it much clearer to anyone else reading the issue.  Thank you. :)
