### ISSUE TITLE
Marketplace: Section promo max width fix

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#68255]
The plugins plan page a promo section with 3 notes about business plan benefits. This section's spacing, margins, and responsive behavior should match the education footer below it.

![Screenshot(19)](https://user-images.githubusercontent.com/811776/192230165-46f20fc7-e232-4a42-a7a5-a74e63dd877e.png)

- [ ] Stretch out the section promo in the plans page to match the education footer sections.
- [ ] Refactor if needed: Ensure this section component is using the same container component as the education footer to handle it's spacing.

**Comment by cpapazoglou** [comment]
This page is loading for `/plugins/plans/:pluginSlug?/:intervalType(yearly|monthly)/:site` route.

Not sure about this, currently the promo section aligns with the container above it.

@vinimotaa what's your take here?

|Current | Suggested|
|-------|------|
|![Image](https://user-images.githubusercontent.com/12430020/211553258-d0f8e45a-1cd6-4d98-ab96-c623e182e1ad.png)|![Image](https://user-images.githubusercontent.com/12430020/211553326-747f6751-96db-4fc1-a83a-01ead78caba2.png)|

**Comment by Raj100679** [comment]
@cpapazoglou @lsl Can I work on this?

**Comment by lsl** [comment]
@cpapazoglou is this page still accessible by any means? 

It looks very broken https://wordpress.com/plugins/plans/wordpress-seo-premium/yearly/test1251414.wordpress.com

**Comment by cpapazoglou** [comment]
> @cpapazoglou is this page still accessible by any means?
> 
> It looks very broken https://wordpress.com/plugins/plans/wordpress-seo-premium/yearly/test1251414.wordpress.com

While the page is accessible, it's not linked anywhere. It's part of a feature that never got launched. I will close this for now. Thanks for your interest @Raj100679 but I don't think it worths working on this.
