### ISSUE TITLE
Marketplace Search: Add an “Astra” theme card that will have a CTA “Install by upgrading to Business plan”

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#68285]
### Details 

Add an [“Astra” theme card](https://wordpress.org/themes/astra/) that will have a CTA “Install by upgrading to Business plan”. Clicking this CTA will lead the user through checkout and then theme installation as we already do with plugins.

Related to pdgAPm-uo-p2#comment-446

Design: @SaxonF suggested (pdgAPm-uo-p2#comment-453) showing a more generic card for all empty searches like the following 

![image](https://user-images.githubusercontent.com/12430020/192539526-9bbcc310-0b43-4e7e-9ba0-ab5b07793b0d.png)

Let's follow this approach for `Astra` terms and follow up on how we can expand it to more themes - the challenge is that the theme searched should exist in the [WP.org directory](https://wordpress.org/themes).

**Comment by SaxonF** [comment]
@WBerredo Figma here 0EogtxvlmxMGcnEEaMVECv-fi-1123%3A26950. Let me know if you need help exporting the image. I'd recommend taking a look at the pattern assembler work from Ganon as it uses a similar card to showcase the blank canvas theme.

**Comment by WBerredo** [comment]
<img width="1192" alt="Screen Shot 2022-10-04 at 09 25 39" src="https://user-images.githubusercontent.com/5039531/193845639-6cce6d34-1ef0-42f1-85db-7bbff9b4dfd9.png">

1. Currently we show a nudge for upgrading the site plan, should we remove it considering this new empty search layout?
2. This new empty search layout will only be shown when the user is on free/premium plan? If yes, should we use the same approach as in plugins to use a backend flag to verify if a site supports a given feature? @Automattic/bespin 
3. The background on the mock is white, so the gray border makes sense. Currently, we have an already gray background, what should be the approach here?
4. 
cc: @SaxonF
