### ISSUE TITLE
Theme: Spearhead Blocks

### ISSUE THREAD

**Issue by onuro** [Automattic/wp-calypso#68291]
### Details

The Spearhead Blocks theme needs the following:

### Checklist

- [x] [Theme Demo site](https://spearheadblocksdemo.wordpress.com/) set up
- [x] [Theme showcase page draft.]
- [x] [Headstart annotations (guide: paYKcK-1Pt-p2)] (Strand id: `139259`) 
- [x] [GlotPress project (guide: paYKcK-1Pt-p2)]
- [x] [Launch process (launch guide: PNEWy-eBM-p2)]

**Comment by daledupreez** [comment]
Hi @markbiek! Could you try to tackle the work to get this theme launched? I nominated you during the sprint planning meeting. 😬 😉

**Comment by markbiek** [comment]
@daledupreez Absolutely! I'll get that cranked out as soon as I can.

**Comment by markbiek** [comment]
Launched!
