### ISSUE TITLE
Reader: comment bubble doesn't take you directly to comments

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#683]
Steps to reproduce:

1. Go to https://wordpress.com/
1. Click on the comment icon for any post

<strong>Result:</strong> I expected clicking the comment bubble would display comments, but clicking the comment bubble only opens the post.

From here, tap the comment bubble inside the Reader main stream:

![screen shot 2015-07-31 at fri jul 31 7 57 35 am](https://cloud.githubusercontent.com/assets/1119271/9006925/807138b2-375a-11e5-9b88-d6fcf81fcb34.png)
<sup>Seen at https://wordpress.com/ using Chrome 43.0.2357.134 on Mac OS X 10.10.4</sup>

Land at the top of the full post view in the Reader, then tap the comment bubble at the top right:

![screen shot 2015-07-31 at fri jul 31 7 56 59 am](https://cloud.githubusercontent.com/assets/1119271/9006938/92a0efe6-375a-11e5-98f6-c76ce2161ceb.png)
<sup>Seen at https://wordpress.com/read/post/feed/10410238/767008807 using Chrome 43.0.2357.134 on Mac OS X 10.10.4</sup>

This is where I expected to land after the first tap:

![screen shot 2015-07-31 at fri jul 31 7 56 52 am](https://cloud.githubusercontent.com/assets/1119271/9006940/98c5516e-375a-11e5-9be1-2e1ff4fcaac9.png)
<sup>Seen at https://wordpress.com/read/post/feed/10410238/767008807 using Chrome 43.0.2357.134 on Mac OS X 10.10.4</sup>

From kokkieh:

<blockquote>I want to remember that in the previous version that icon linked directly to the comments in the old pop-up, but now with the slide-out it goes to the top of the posts, same as clicking the title, and one has to scroll down the whole length of the post to find the comments. Do you think it's possible that the comment icon can link directly to the post comments again? Thanks :)</blockquote>

— https://en.forums.wordpress.com/topic/reader-view/page/7?replies=197#post-2436731

From blowery:

<blockquote>When we go to test this, there are three main entrance flows that have to work:
1) hit the button from the stream. Should open FPV and scroll you to comments.
2) reload the FPV with #comments in the URL. Should scroll you down to the first comment once the content loads. Might scroll you back to wherever you were when you hit reload.
3) hit the button from the stream, get scrolled down, then click on a link in a comment or in the post body. Then hit back to re-enter FPV. Scroll position should be maintained.</blockquote>

**Comment by bluefuton** [comment]
Fixed in #2058.
