### ISSUE TITLE
Theme Bundling: Fix errant behavior when selecting a bundleable theme from theme showcase

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#68309]
There were some comment feedbacks on pdtkmj-xt-p2 relating to behavior when selecting Thriving Artist from the theme showcase rather than in onboarding:

> Thriving Artist theme can be activated with the Premium plan, so it’s not the case This WooCommerce theme is included in the Business plan Video.

I believe this confusion stems from the fact that the theme in and of itself is a Premium theme and thus technically available to all premium users, but that we are enforcing the behavior of upgrading to Business and including a plugin separately. 

We seem to have two options here to provide better clarity.

* Avoid pushing users into the upgrade flow at all if they select the theme from the showcase. (In other words, if a user selects the theme during onboarding, we encourage them to install the plugin at the same time; however, if they select it from the showcase, we treat it just as a regular A8C Premium theme and provide no special functionality.)
* Provide a similar confirmation modal to the one in onboarding, indicating that the user will be getting a plugin installed and will need to be upgraded to a business plan.

@ianstewart Do you have any thoughts on this one way or the other?

**Comment by nelsonec87** [comment]
Closed with https://github.com/Automattic/wp-calypso/pull/68361
