### ISSUE TITLE
Jetpack Connect Plans: fix styles

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#6830]
When you land on the plans page after connecting your Jetpack site, there are a few styles that are not quite right:

<img width="816" alt="screen shot 2016-07-15 at 2 12 57 pm" src="https://cloud.githubusercontent.com/assets/2694219/16884510/d7a6e162-4a97-11e6-9728-35164b9c4f3f.png">

The list items for the free plan are the wrong color, and have incorrect spacing. And the spacing of the 'Upgrade Now' button for the Premium Plan is off.

**Comment by rickybanister** [comment]
I think with the new plan design launching we can likely close this in favor of the new design. Any objections?

**Comment by roccotripaldi** [comment]
Closed. #7165 will use the redesigned plans page.
