### ISSUE TITLE
Marketplace: Add Business Plan to cart when billing intent is created for a site that has a lower plan

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#68322]

**Comment by epeicher** [comment]
#### Backlog grooming

Third-party vendors will call the billing intent endpoint created here D87610-code. The endpoint adds SaaS products to the user’s cart automatically. But when the user’s site doesn’t have a higher plan then the cart validator throws an error indicating that the product doesn’t support plugin installation. The business plan could be added at that point by the backend code that handles that.

**Comment by cpapazoglou** [comment]
Draft code in D90164-code

**Comment by cpapazoglou** [comment]
Deployed r254801-wpcom
