### ISSUE TITLE
[Invite Follower] Make sure different languages for inviter and invited works sends the emails in the right language each case

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#68325]

**Comment by TimBroddin** [comment]
When user is registered it takes the user's language:
![Image](https://user-images.githubusercontent.com/528287/192540511-4dfdc90f-c224-4450-bb0b-428c12de2c40.png)

When the user is not registered, it takes the site's language:
![Image](https://user-images.githubusercontent.com/528287/192540646-83c5b035-9d8e-4256-af6a-ac63155502b1.png)
