### ISSUE TITLE
Marketplace: Update billing intent status to active after subscription is purchased

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#68324]
### Details

Whenever new billing intent is created, we add `pending` as the default state for the billing intent. But when a purchase is completed for any billing intent there is no way to tell if the specific billing intent was successful. So we need to mark billing intent as active so that we can see how many billing intents actually had successful checkout. 

### What needs to be done

We need to update the status field of billing intent when there is any successful checkout. We can listen to product activated /deactivated hooks to update billing status intents.

**Comment by cpapazoglou** [comment]
Can you provide more context here Rahul? Why is that needed?

**Comment by JulianBustamante** [comment]
Diff created D90607-code

**Comment by JulianBustamante** [comment]
Deployed r255198-wpcom
