### ISSUE TITLE
Task: Reuse socket connections

### ISSUE THREAD

**Issue by arcangelini** [Automattic/wp-calypso#68359]
### Details

When the user closes the chat window the socket connection remains open. If the user opens Help Center again, another socket connection is opened. This causes multiple open sockets.

Ideally we would leave the connection open and reconnect the chat when Help Center is loaded again, but if not we need to at least close the connection that is already open.

<img width="1010" alt="Markup 2022-09-27 at 20 24 15" src="https://user-images.githubusercontent.com/33258733/192607164-0f2d26e8-11a0-4ca0-bafe-bcad532d6203.png">

**Comment by alshakero** [comment]
This will be fixed by https://github.com/Automattic/wp-calypso/pull/68292
