### ISSUE TITLE
Newsletter Flow: Colour picker remove the pointer of the selector

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#68353]
### Details

Context here: pbAok1-3fI-p2

Remove the pointer of the selector 

![Screen Shot 2022-09-27 at 17 58 18](https://user-images.githubusercontent.com/52076348/192576915-77a34ab2-e6c6-405b-916c-e74e82b18abd.jpg)

**Comment by alshakero** [comment]
Closing as done in https://github.com/Automattic/wp-calypso/pull/68436
