### ISSUE TITLE
Pattern Assembler - Zoologist is used instead of Blank canvas when the onboarding data has expired

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#68374]
### Description
Suppose a user bookmarks the URL of the PA `/setup/patternAssembler` and accesses it after one week. In that case, the PA will use Zoologist (the default theme) instead of Blank canvas. This is an edge case because users should not access the PA directly. However, they could do it and skip all the previous onboarding steps.

#### Why this happens?
During the onboarding, we persist the `selectedDesign` which includes the theme/stylesheet slug for the Blank canvas in the `Onboard` store using the config [one-week-persistence-config](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/one-week-persistence-config/index.ts). With this config, the data in the store is persisted for 7 days in the `localStorage` of the browser and automatically cleaned after that period or when a new param is added to the same URL.

### Reproduction
- Create a new site or use the site slug of a site that you have not used for the PA flow in the past 7 days.
- Access the URL `wordpress.com/setup/patternAssembler?siteSlug=[ YOUR SITE ]`
- Check that when you add a pattern the PA preview shows the theme Zoologist

<img width="1540" alt="Screen Shot 2565-09-28 at 13 56 26" src="https://user-images.githubusercontent.com/1881481/192709954-e808dca8-2e96-4103-8e00-384aeb9dcfe1.png">

### Proposed solutions
- We could solve it by redirecting users to the first step of the onboarding process. 
- We could hardcode the theme/stylesheet in the UI or force it in the server API with a param, instead of getting it from the `Onboard` store 

@Automattic/ganon what do you think about the proposed solutions? Is there any other possible solution?

### Related
Slack convo: p1664174198721219/1664172850.948199-slack-CRWCHQGUB

**Comment by arthur791004** [comment]
> We could solve it by redirecting users to the first step of the onboarding process.

I'd prefer this one.

> We could hardcode the theme/stylesheet in the UI or force it in the server API with a param, instead of getting it from the Onboard store

If we go this way, we will lose the data from the previous steps. For example, we won't know the user's goals as the data is expired and I think their goal is important to us.

**Comment by taipeicoder** [comment]
> > We could solve it by redirecting users to the first step of the onboarding process.
> 
> I'd prefer this one.
> 
+1. Adding to what Arthur already said, users would probably forget what they did after a week, so I think it'd be good to have them start fresh again.

**Comment by bangank36** [comment]
> We could solve it by redirecting users to the first step of the onboarding process.
This'll work, also there is no way we can know when the storage is wiped out right?
