### ISSUE TITLE
Newsletter: [Write First Post] [Pre-Publish] The subscribers section should be at the top

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#68381]
At the moment the **Subscribers** section is at the very bottom of the pre-publish sidebar. The goal of this task is move the section to the top of the sidebar.

Screenshot of the current UI state:
![Image](https://user-images.githubusercontent.com/2019970/192802717-c7f856d7-ac1a-4268-98e0-a9e2cbeb309b.png)

**Comment by mashikag** [comment]
Looks like there is little of control from jetpack's perspective where a pre-publish panel is placed. When it is registered it is added to the bottom of the panels list. If there is ever something included before jetpack it can register a pre-publish panel ahead of jetpack. 

This still requires more debugging for me to understand the rendering process of the panel in more details.

**Comment by TimBroddin** [comment]
Closing this as lots of product discussion has happened since.
