### ISSUE TITLE
Editor: Table tags stripped when pasting from Excel

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#684]
User reported that he could not paste Excel tables into the new editor, while still being able to do so on WP Admin.  After testing, here are the results when attempting to paste into the new editor:

MacBook Pro
Did not work on: Safari, Chrome, Firefox

Result on Firefox:
![excel to calypso on firefox](https://cloud.githubusercontent.com/assets/11635760/11380640/2cdacc92-92ac-11e5-8ec5-dfabaac8b403.png)

PC (Windows 7)
Did not work on: Chrome
Worked on: IE11, Firefox

Result on Internet Explorer 11:
![excel_to_calypso_ie11](https://cloud.githubusercontent.com/assets/11635760/11380621/1864a7ba-92ac-11e5-98f7-6f3890834396.png)

WP Admin's HTML tab on Internet Explorer 11:
![excel_to_wpadmin_ie11_html](https://cloud.githubusercontent.com/assets/11635760/11380687/7e095e44-92ac-11e5-8e19-3a713c6f4ba7.png)

All tags were stripped when pasting into Chrome on a Mac; toggling between the Visual and HTML tabs did not yield any new results.

This only happens when copying directly from Excel.  When copy/pasting a table into the new editor from Google Sheets, Numbers, and also from a table pasted into the new editor on IE11, the table showed up correctly.

**Comment by supernovia** [comment]
We have some mentions of this issue in the public forums and will want to follow up when this is fixed.

**Comment by dirksmets73** [comment]
Hi all, I have the same problem since a while.  I'm not longer able to copy paste excel tables directly from excel to wordpress.  I use Chrome and it's not possible anymore, I get plain text.
When using internet explorer 11 it works just fine.  Just like the example shown above... 
Any progress on this issue ?

**Comment by hoverduck** [comment]
21Apr16 Bug Scrub

Appears to be fixed, so I'm closing it.  I was able to paste from Excel into the visual editor on Windows Chrome and IE11, and on OSX from LibreOffice Calc into Chrome and Firefox.
![image](https://cloud.githubusercontent.com/assets/7233112/14718091/9ce0e7ac-07c2-11e6-8cf7-378e90b515f0.png)
