### ISSUE TITLE
Reader Search: Mobile width: Images should be smaller

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#6840]
In Reader Search, when the browser is iPhone width (smallest break point), the images should be about half their current width.

Current:

![screen shot 2016-07-15 at 2 40 53 pm](https://cloud.githubusercontent.com/assets/24388/16889348/87a7ce26-4a9a-11e6-99f1-595d71e56348.png)

This is to keep the blocks less tall, give more room for the text.

**Comment by jancavan** [comment]
Looks like this has been resolved. The images are narrow in viewports `<480px`.

**iPhone 6 Plus:**
![screenshot 2016-07-18 16 41 43](https://cloud.githubusercontent.com/assets/4924246/16933904/95f13eb8-4d06-11e6-8d73-7034a56f8a75.png)

**iPhone 6:**
![img_3394](https://cloud.githubusercontent.com/assets/4924246/16933908/9e1ba416-4d06-11e6-8547-f8054252c3d7.jpg)
