### ISSUE TITLE
LaunchPad - Show email verification notification

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#68407]
Lets update the launchpad to show the "Email Confirmed!" banner when applicable.

**Notes:**

Currently when a user verifies their email, they are directed to MyHome with an "Email confirmed!" banner that shows up:

![image](https://user-images.githubusercontent.com/28742426/192811015-6150aae7-dcf1-48f1-ae74-1423b015a145.png)

This banner seems to be triggered via the `verified` query param. Ex - `https://wordpress.com/home/SITE_SLUG?verified=1`

For launchpad sites, this MyHome URL will immediately redirect to launchpad and no confirmation banner will be shown. We should make sure this `verified` param is carried over to the launchpad on redirect when applicable, and ensure the same confirmation banner shows up in the launchpad in this case.

**Comment by agrullon95** [comment]
Potential fix: https://github.com/Automattic/wp-calypso/pull/68453
