### ISSUE TITLE
Marketplace Install Dialog: Unify CSS styles

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#68414]
### The problem

Our modal should have these specs. Figma: [HOg65lHD0QOfaq0QtzKQbC-fi-1517%3A11006](https://href.li/?https://www.figma.com/file/HOg65lHD0QOfaq0QtzKQbC/?node-id=1517%3A11006)

![Image](https://user-images.githubusercontent.com/1044309/192853359-a83f1fa2-b5b9-45df-9a8b-d81f9bad2db1.png)

Figma: [HOg65lHD0QOfaq0QtzKQbC-fi-1183%3A11200](https://href.li/?https://www.figma.com/file/HOg65lHD0QOfaq0QtzKQbC/?node-id=1183%3A11200)

![Image](https://user-images.githubusercontent.com/811776/192197991-ad58600b-b629-4f51-a949-83ccdacfc0c8.png)

### The current state

- This is the /plugins implementation so far:

	<img width="688" alt="image" src="https://user-images.githubusercontent.com/1044309/192854929-628d2709-fb92-41ed-b4f1-47efd2f011cc.png">

- This is the same /plugins implementation but at a business simple site (which is not atomic yet) [at this pr](https://github.com/Automattic/wp-calypso/pull/68362):

	![image](https://user-images.githubusercontent.com/1044309/192862243-84981af8-851e-40da-9fc5-b0009555eed4.png)

- And here at the jetpack /backup, we have extra padding at the Dialog component:

	<img width="853" alt="image" src="https://user-images.githubusercontent.com/1044309/192857287-11452291-a93d-48d5-88cc-e4cbad7a90da.png">

- **Themes upload**: At /themes/upload, we don't even have padding (before changes at https://github.com/Automattic/wp-calypso/pull/68362):

	<img width="772" alt="image" src="https://user-images.githubusercontent.com/1044309/192857576-b457f343-fc87-48b3-960c-236714e8cd52.png">

- **Plugins upload**: At /plugins/upload we don't have a specific box for it, preview [from this pr](https://github.com/Automattic/wp-calypso/pull/68362):

	![image](https://user-images.githubusercontent.com/1044309/192862946-cf38e88d-1fe9-4d3c-ab51-0a66a83913fe.png)

- **Host activation**: At /hosting-config/activate/{site} 

	<img width="883" alt="image" src="https://user-images.githubusercontent.com/1044309/192867138-8762fe15-3af5-41c8-a2c1-2d8be439da7e.png">

### Requirements

We need to make sure it will work on all of its uses, and that's the hard part because we have a lot of use cases for this modal.

Please update the following list to make sure we covered everything:

- [ ] /plugins page with simple free site
- [ ] /plugins page with simple business site
- [ ] /plugins/upload with simple business site
- [ ] /themes/upload with simple business site
- [ ] /backup/{site} with simple business site
- [ ] /hosting-config/activate/{site} with simple business site

**Comment by paulopmt1** [comment]
@vinimotaa do we have interfaces for screens like **Plugins upload**, **Theme upload** and **Host activation**?

**Comment by paulopmt1** [comment]
Please note that to make [my PR](https://github.com/Automattic/wp-calypso/pull/68362) approvable, [I added some custom CSS on specific screens](https://github.com/Automattic/wp-calypso/pull/68362/commits/d7690c33e77a37b3c130f97f7d742421bee7b891), which will likely to be changed after Vini's layouts or this PR code.

**Comment by paulopmt1** [comment]
Hey @vinimotaa, in some places, we have The continue button on the left (like hosting and installing the plugin). Can we standardize it to always be at the right, like in the plugin install?

For example, this: 

![image](https://user-images.githubusercontent.com/1044309/193040894-61bfb86f-ad7b-48fd-b22f-3c50c0aae973.png)

Will became:

![image](https://user-images.githubusercontent.com/1044309/193040995-b7def83a-71e6-4259-afed-08f5fb8a4292.png)

**Comment by vinimotaa** [comment]
Hi @paulopmt1 - I'd standardize on the right-hand side
