### ISSUE TITLE
Marketplace: Endpoint for retrieving the billing_intent data

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#68441]
We probably need to implement backend API to fetch billing intent associated with the purchase.

When the user completes the checkout process for SaaS product, we need to fetch associated billing intent from the billing intents table. The billing intents table has `redirect_url` fields saved when billing intent was first created.

Related to https://github.com/Automattic/wp-calypso/issues/68148

**Comment by cpapazoglou** [comment]
Let's check if we can add this parameter to the `purchases` array of objects first.

**Comment by cpapazoglou** [comment]
This should be doable in `wp-content/admin-plugins/wpcom-billing/class.wpcom-store-api.php:345` by checking if this is a SaaS product and optionally adding the `redirect_url` prop.

**Comment by JulianBustamante** [comment]
Diff created D90175-code

**Comment by JulianBustamante** [comment]
Deployed r254846-wpcom
