### ISSUE TITLE
Premium Themes/Bundling: Show badges for themes with Style Variations

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#68440]
If a theme has style variations, "Premium" and "WooCommerce"  badges are not shown:
![image](https://user-images.githubusercontent.com/3801502/193048793-d767c10e-b4af-4db3-adfc-b7bbae9f4b37.png) 
![image](https://user-images.githubusercontent.com/3801502/193048937-4ccd0c03-02e9-4d87-9b0f-d093d645ad33.png)

Premium theme Varese, for example:

![image](https://user-images.githubusercontent.com/3801502/193048430-ffc82743-3ad8-487c-bcf5-9d369032b9c5.png)

vs Themes without style variations:

![image](https://user-images.githubusercontent.com/3801502/193049857-db34c23d-93fe-4098-8d58-4495b52a9bd9.png)

**Comment by arthur791004** [comment]
@SaxonF @taipeicoder I think we still need those badges when previewing the theme with style variations. What do you think?

**Comment by taipeicoder** [comment]
Should we place badges below the theme title instead of next to it? The sidebar is narrow enough to create overflow for titles as "Twenty Twenty-Two", for example.
![Screen Shot 2022-09-30 at 10 58 01 AM](https://user-images.githubusercontent.com/797888/193180643-0ce6a8ca-49ec-4d4b-a1a6-78be8600342e.png)

**Comment by taipeicoder** [comment]
From p1664762706432389-slack-CRWCHQGUB, we will show the badges above the theme title:
![Image](https://user-images.githubusercontent.com/797888/193512328-3cf63c01-3c9a-4368-a220-f5d5616352fa.png)

**Comment by taipeicoder** [comment]
Closing as it's deployed.
