### ISSUE TITLE
Two-factor: Re-enabling two factor authentication results in UI bugs

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#6845]
Hi lovely people.

I recently did a security audit and updated my 2fa device for my WordPress.com account. The only way to change device was -- sadly -- to remove and then re-enable two factor authentication. I wish it was like other services where you can just change it and don't have to generate new backup codes etc. However this is besides the point, the point is that I found some bugs when the process was about to be completed.

This is what it ended up looking like:
<img width="891" alt="screen shot 2016-07-16 at 22 58 59" src="https://cloud.githubusercontent.com/assets/3073557/16897154/54fbeb0a-4ba9-11e6-8194-1ef9003e8c3f.png">
#### Bugs
- Toast notice in 2fa is not hidden when 2fa is enabled again.
- Status message in the top box is not updated (ON - OFF) when 2fa is enabled again.
#### Steps
1. /me/security/two-step
2. Disable two-step, then re-enable. _The toast "successfully disabled 2fa" doesn't go away._
3. Add a number, add a secret via a QR code. Verify the generated codes and do something with the backup codes.
4. Once out of the wizard there's now a prompt "successfully enabled 2fa", so there are _two prompts_.
5. Status in the top box still says "OFF" in red.
#### Browser / OS version

OS X Chrome (latest)
#### Screenshot / Video

see above
#### Context / Source
# security-audit #security #2fa

**Comment by designsimply** [comment]
Thanks for the report! I tested and was able to reproduce the problem where the status does not update after re-enabling 2fa using your steps. ([1m11s](https://cloudup.com/cbtA64-j0WT))

![screen shot 2016-07-18 at mon jul 18 9 17 42 am](https://cloud.githubusercontent.com/assets/1119271/16920242/1e33e560-4cca-11e6-88ac-556d79d6b7d4.png)
<sup>Seen at https://wordpress.com/me/security/two-step using Firefox 47.0.1 on Mac OS X 10.11.5</sup>

> The only way to change device was -- sadly -- to remove and then re-enable two factor authentication. I wish it was like other services where you can just change it and don't have to generate new backup codes etc.

Good notes. https://github.com/Automattic/wp-calypso/issues/19 should cover this one.

> Toast notice in 2fa is not hidden when 2fa is enabled again.

Good find. That persistent disabled message is covered in https://github.com/Automattic/wp-calypso/issues/5388

**Comment by isaackeyet** [comment]
Thanks Sheri! Calypso rocks.

**Comment by madeincosmos** [comment]
I ran into the same problem on Windows 10 with Chrome 53:

https://cloudup.com/cmm8F0T-Son

Same process applies as above :)

**Comment by pmaiorana** [comment]
I just ran into this one as well; macOS Sierra v10.12, Chrome Version 53.0.2785.143 (64-bit).
