### ISSUE TITLE
[New Subscriber] Fix subscriber heading layout

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#68456]
Context: p1664476423685359-slack-C02TCEHP3HA

It should be fixed following the mobile layout for New Subscriber template on Figma.
c5bt2O2vWhTlhSREC89Bw2-fi-958%3A9456

**Comment by TimBroddin** [comment]
I fixed the space, but still have to do the break on mobile.

**Comment by TimBroddin** [comment]
Patch for the line-break, sadly it doesn't work in Gmail. I'm researching a bit more.

D88905-code

**Comment by TimBroddin** [comment]
Closed in D88905-code
