### ISSUE TITLE
Switch Site: Option to Hide Sites in sidebar

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#68455]
### Quick summary

When you click on Switch Site to choose another one of your sites, it's showing all of them, including hidden ones.

### Steps to reproduce

1. Go to your WordPress.com account.
2. From My Sites, click on Switch Site
3. Check the list of your sites.

You can hide sites from here: https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs

### What you expected to happen

To only list sites marked as visible.

### What actually happened

It's now showing all sites, not respecting the hiding setting.

### Context

I noticed this yesterday, suddenly all the 357 sites I'm in are showing on the list, not just the 16 I marked as visible. I replicated it on Chrome and Firefox using different WordPress.com accounts.

**Comment by bizanimesh** [comment]
I noticed this on my account yesterday, and we have a report from one user as well.

- [ ] 5592227-zen

**Comment by cuemarie** [comment]
So glad this has been reported - as I follow a lot of sites, this has been driving me a little bananas! ➕

**Comment by danielbachhuber** [comment]
Thanks for the report!

Displaying hidden sites in the Site Switcher was actually an intentional product decision in `Site Switcher i1` (pdKhl6-Fj-p2). We added sorting modes to the Sites page (https://wordpress.com/sites), including 'Magic' which sorts your sites based on frequency of interaction. We would also like to eventually remove the concept of hidden sites.

Our hope is that 'Magic' is sufficient to bump your most important sites to the top of your list. If you think 'Magic' could be even better, could you stop by `#dotcom-build` so we can review which sites are appearing against which you'd expect or prefer to appear?

**Comment by carinapilar** [comment]
> Displaying hidden sites in the Site Switcher was actually an intentional product decision

Thanks for the context, @danielbachhuber! That's really sad to hear though, since removing that option is extremely disruptive to HE's workflows (another disruptive user case might be for agencies). For example, I have a couple of test sites that I use on my day-to-day work, I don't use all of them every day, so now I see just my primary test site at the top and then the other 357 P2s that I don't need in alphabetic order. Unfortunately, this 'Magic' option isn't helpful to HEs as the hidden option was.

I guess it might be especially troublesome for any A11n, since we're added to hundreds of P2s, and even if you're not an HE with some test sites, you will now need to search the site you want, in the midst of all P2s you don't need that could've been hidden. 😞

**Comment by rossanafmenezes** [comment]
I would just like to second what Carina said. And not only for HEs. I have several stores I use to test changes in the Woo mobile app. Same situation, I don't use them every day and now they are lost in the middle of hundreds of P2s I'm part of. 

Also, seconding the fact that this might not be the best situation for agencies or Freelancers with multiple clients. :(

**Comment by danielbachhuber** [comment]
@carinapilar @rossanafmenezes Just to confirm, both of your accounts are set to sort by 'Magic'? You'll be able to see that at the top of https://wordpress.com/sites:

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/36432/195706130-5c7517a5-8a77-4007-bdba-ed98f0bef414.png">

**Comment by rossanafmenezes** [comment]
Hi @danielbachhuber 

Yes, Mine is. But it does not help in my case.

**Comment by danielbachhuber** [comment]
@rossanafmenezes and I chatted a bit about the specifics of her use case in Slack p1665695420988339-slack-C0347E545HR

**Comment by bizanimesh** [comment]
Hi @danielbachhuber - my account is also set to sort by **Magic**, but I can still see all the sites there. There is no problem if we are showing them all in https://wordpress.com/sites, but it would be very helpful if we could make the sites disappear again from the **My Sites » Switch site** that are set to be Hidden.

**Comment by cuemarie** [comment]
📌 ACTIONS
- relabeled this as a feature request and adjusted the title slightly, given that it's working as intended. Perhaps we can keep the feature request in place of the bug report to track/discuss bringing back a way to hide sites?

**Comment by danielbachhuber** [comment]
> Perhaps we can keep the feature request in place of the bug report to track/discuss bringing back a way to hide sites?

@cuemarie Sounds great! I would love to keep collecting feedback and insights.

**Comment by carinapilar** [comment]
That's sad to hear, that a removal of an existing feature turned into a _feature request_, especially because on the Switch Site list itself nothing changed besides the buttons at the bottom. I hope this gets implemented soon, because it's very disruptive. 😞

**Comment by carinapilar** [comment]
I now noticed that it does seem to exist a bug on the new Switch Site and the removed hidden feature. @danielbachhuber, let me know if I need to open a new GH request for the following:

**Steps to replicate:**
1. Select one of your sites from the list
2. Click on the Pages menu item
3. Click on "Switch Site"

It shows the number of visible sites, even though that feature isn't working anymore. I have 300+ sites, and 16 marked as visible, even though the list shows all 300+ sites now, it's still showing the number 16 and _"View pages for all sites"_, which is now confusing, because it doesn't show the pages for all 300+ sites, but just for the 16 visible ones.

This is the area I'm referring to:

![hidden-sites-counter](https://user-images.githubusercontent.com/16104522/196189514-aa88a280-24fd-4fa8-b387-aca32a8ab465.jpg)

**Comment by danielbachhuber** [comment]
> It shows the number of visible sites, even though that feature isn't working anymore. I have 300+ sites, and 16 marked as visible, even though the list shows all 300+ sites now, it's still showing the number 16 and _"View pages for all sites"_, which is now confusing, because it doesn't show the pages for all 300+ sites, but just for the 16 visible ones.

@carinapilar Good eye! This discrepancy is on our radar (https://github.com/Automattic/wp-calypso/issues/68919). We could probably show an icon instead.

**Comment by thekingsprojects** [comment]
Another user who wanted to be able to hide sites here—they don't want to see them at all, and don't have enough sites that any sorting would be likely to "bury" them in the list. (They may just end up deleting the sites anyway, they need to think about it, but wanted to consider hiding them in the meantime.)

37402025-hc

**Comment by ash1eygrace** [comment]
Just wanted to add a plus 💯 here that we need to preserve hidden and visible preferences set via My Site > Profile > Manage Blogs. 

The closest I could get to my original setup is to manually leave 200+ blogs one by one via My Site > Profile > Manage Blogs since the bulk select option isn't working, but I gave up. 

For now, I've resorted to browser bookmarks for each test site, but I really hope this makes a comeback. 

If we're going to deprecate the hidden/visible feature, at least adding an option to let me pin specific sites at the top of the list when going to My Site > Switch Sites (for clarification: not Manage Sites button, too much click currency to open that) would be amazing!

**Comment by rossanafmenezes** [comment]
Another thing I just noticed @danielbachhuber :

<img width="226" alt="Screen Shot 2022-10-23 at 4 48 17 PM" src="https://user-images.githubusercontent.com/30724184/197417542-71c9e450-1f71-47d5-a62e-bd7930f9fe2d.png">

it only shows the first 50 sites. Right now, I'm looking for one of my personal blogs, so I know the site title and address, but when I'm looking for one of my 18 test sites, the site title and address are not something I memorize because a lot of them a random, which makes things even harder, since obviously the first 50 sites in the list will be all P2s  :(

**Comment by danielbachhuber** [comment]
> Right now, I'm looking for one of my personal blogs, so I know the site title and address, but when I'm looking for one of my 18 test sites, the site title and address are not something I memorize because a lot of them a random, which makes things even harder, since obviously the first 50 sites in the list will be all P2

@rossanafmenezes Great insight! Thanks for sharing 😊

**Comment by atrumgeost** [comment]
I'm also adding a +1 here. I have been very intentional about the sites I mark as hidden so that I can have test sites handy on the "Switch site" sidebar. The Magic sort doesn't help in my case.

**Comment by csonnek** [comment]
Adding my +1 to this. Having been at a8c for nearly 10 years now, I have _HUNDREDS_ of sites under my account. And the ones showing in the "magic" sort  are mostly internal P2s which I would never need to "manage" and retired sites that haven't had new posts as far back as 2019: 

![Sites_—_WordPress_com](https://user-images.githubusercontent.com/2814452/204325984-bc832d5f-be99-46fb-80ed-34b2a91f6a95.jpg)

...all in the first page of my sort. 

With close to 400 HEs, this is a big problem.

**Comment by carinapilar** [comment]
I also noticed that even though I access my Primary Site every day, since it's the one I use for testing, it's almost never on the list - so if I select another site, I have to search for the primary one to go back to it, while I would expect to be the first on the list.

**Comment by danielbachhuber** [comment]
> retired sites that haven't had new posts as far back as 2019:

@csonnek Out of curiosity, is there a specific reason you still want to be a member of the retired P2s? Or have you simply not removed yourself from them?

Also, the idea behind "Magic" sort is that your most important sites will bubble to the top of the list. I notice an issue, though: our A-Z sorting algorithm puts `(Retired)` at the top of the list:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/36432/204361382-1d49bee1-5bf6-4988-bd08-018efbb3661d.png">

I'll put together a PR so they appear at the bottom.

> I also noticed that even though I access my Primary Site every day, since it's the one I use for testing, it's almost never on the list

@carinapilar What sort of actions do you perform on your Primary Site?

**Comment by carinapilar** [comment]
> What sort of actions do you perform on your Primary Site?

@danielbachhuber, usually for testing purposes, like creating pages, posts, changing themes, privacy settings, and accessing the Customizer.

**Comment by csonnek** [comment]
> Out of curiosity, is there a specific reason you still want to be a member of the retired P2s? Or have you simply not removed yourself from them?

@danielbachhuber I just never removed myself - mainly because they're hidden and it was never an issue previously. But the fact they showed on my first page of the "magic" sort seemed strange.

**Comment by liviopv** [comment]
+1 to this as well. While the new site management screen looks excellent, the new listing mechanism removes _**years**_ of user-made choices. While we tenured a12s are more affected, I imagine there are a lot of long-term WordPress.com power users out there suddenly confused about why their hidden sites are visible again on their lists.

If we don't want to bring back My Blogs and the option to hide sites, one possible option to accommodate a12s needs would be including an a11n-only option to hide P2s from the site management list.

**Comment by danielbachhuber** [comment]
@liviopv To help broaden the pool of knowledge, can you share more detail about what you're seeing that you don't expect to see? Screenshots would be very helpful too. Thanks!

**Comment by liviopv** [comment]
@danielbachhuber My problem is similar to @csonnek's - even with the Magic sorting, I get several P2s that I intentionally hid over the years, but I don't get a lot of my personal sites (testing or actual). I also get things like Learnomattic (I was just taking a course) and the Swag Store (why?) that also don't make any sense in the "My Sites" list. 

<img width="339" alt="Markup 2022-12-08 at 17 44 37" src="https://user-images.githubusercontent.com/14153300/206525370-4a82ea45-22ff-4010-9266-33ccbc4712da.png">

Does the Magic algorithm account for the user role I have on the site?

**Comment by danielbachhuber** [comment]
@liviopv Thanks for the additional detail — this is great!

> Does the Magic algorithm account for the user role I have on the site?

It doesn't, and that's potentially a change we could make. However, we don't have any great ways to test algorithm changes at the moment. I'd want such a testing apparatus for a broader change like that.

I tried demoting hidden sites to the bottom of the list (https://github.com/Automattic/wp-calypso/pull/70972) but I'm not in love with the results.

**Comment by carinapilar** [comment]
Adding here again how difficult it is to work with this new list of sites. @danielbachhuber, would it be better to have a new GH thread to track issues with the Magic algorithm? Since this one turned into a feature request.

I find it very odd that my primary site, which I **use every day**, isn't showing on the list. And while working today, I accessed my personal site a couple times, and suddenly at the end of the day it's also not showing on the list, while I have other sites showing up that I haven't accessed **for years**, this looks like a bug to me, so I wonder if having a new GH thread just for this would get more eyes on it.

**Comment by danielbachhuber** [comment]
> would it be better to have a new GH thread to track issues with the Magic algorithm?

@carinapilar Sure! If there are specific problems that you discover with the Magic algorithm, feel free to create new issues. We can use https://github.com/automattic/dotcom-forge if we want to be able to share non-public information. I'd also be happy to jump on a call with you to debug in real-time, if needed.

> I find it very odd that my primary site, which I **use every day**, isn't showing on the list. And while working today, I accessed my personal site a couple times, and suddenly at the end of the day it's also not showing on the list, while I have other sites showing up that I haven't accessed **for years**, this looks like a bug to me

Yep, that is odd and unexpected. It'd be great to get to the bottom of it!

**Comment by carinapilar** [comment]
Thanks, @danielbachhuber, I have moved here: https://github.com/Automattic/dotcom-forge/issues/1437 - since this GH thread turned into a feature request to have the hiding feature back, this new one is to discuss how the Magic algorithm works.

**Comment by csonnek** [comment]
> I find it very odd that my primary site, which I use every day, isn't showing on the list.

I can confirm that as well. It's not even on page 1! I end up manually typing in the site URL, then going to the backend that way, which isn't very user-friendly, IMO.

**Comment by pauljacobson** [comment]
Just adding a request from a customer to be able to hide sites here: 6016237-zen

I have relayed the rationale for the change to Sites to them in the meantime.

**Comment by lsl** [comment]
@inaikem we could possibly close this, the support documentation no longer links to the sites dashboard page, so we shouldn't get new user reports about this being broken.

In terms of implementing this in the new /sites dashboard I don't think there is enough user demand to offset the added complexity this would bring to the sites dashboard filters, and introduces some nuance around site statuses that would be hard to explain, for example, what is the difference between a hidden site and a private site?

**Comment by kentaurse** [comment]
good project.
I can do this ticket.

**Comment by Robertght** [comment]
Given that the context has changed with the new interface since the original request, I don't know if we should close or open a new one as a feature request and we could track the user demand there. 

@lsl @inaikem I'm fine with either option, but I need your input on this.

**Comment by kentaurse** [comment]
Hello @lsl, @inaikem, and team,

Thanks for the detailed background on this issue. I understand the complexities involved with adding more site filtering options, especially given the overlap with site privacy statuses.

However, given the number of users affected, including those with extensive site lists, I'd be happy to contribute to this feature request. I could implement an intuitive toggle option for hiding or prioritizing sites within the dashboard. This would maintain simplicity while still enhancing usability for power users who manage many sites.

Let me know if you’d like further details or a sample proposal on how to integrate this seamlessly. Looking forward to the opportunity to support this improvement!

Best regards,
Ethan Tan

**Comment by lsl** [comment]
> However, given the number of users affected, including those with extensive site lists

Hi @kentaurse, I don't think there are that many users affected by this, most users only have 1-2 sites. We're also doing some large refactoring around the sites dashboard right now, your work would likely run into a lot of conflicts come merge time. I think it would best to hold off on this one.

@Robertght usually prefer to keep the conversation confined to a single issue, but restarting a new issue might be worth while here just to avoid the confusion with early reports and zendesk tickets about the old interface.

**Comment by kentaurse** [comment]
I got it.
