### ISSUE TITLE
Email: broken email for 2fa enabled/disabled notice

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#6846]
Hello again,

Wanted to highlight what the emails look like for enabling/disabling 2fa. Looks like an old email template, and wp-calypso is probably not the right place to report this, but just so it gets some attention!
#### Steps to reproduce
1. enable/disable 2fa
2. ???
3. get email
#### What I expected

pretty emails or plain text
#### What happened instead

ugliness!
#### Browser / OS version

Airmail Beta 3.0 (371)
#### Screenshot / Video

<img width="828" alt="screen shot 2016-07-16 at 23 17 30" src="https://cloud.githubusercontent.com/assets/3073557/16897257/eee25b26-4bab-11e6-99a1-3e45b44e5f07.png">

**Comment by kriskarkoski** [comment]
The email is now properly styled. Closing.
