### ISSUE TITLE
Stepper Framework: Redirect to first step once the ONBOARD_STORE is expired

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#68467]
Refer to https://github.com/Automattic/wp-calypso/issues/68374, it might be better to redirect the user to the first step once the onboarding data is expired

**Comment by bangank36** [comment]
Do we have a selector to detect when the store has been expired? Or we can just check the goals and intent `site-setup-flow.ts`? 🙏

**Comment by bangank36** [comment]
Closed as implemented on #69780
