### ISSUE TITLE
Help Center: errors in widget.wp.com need env_id

### ISSUE THREAD

**Issue by arcangelini** [Automattic/wp-calypso#68477]
### Details

This took me a while to track down, but there is an error in the console that shows that the `env_id` is missing in the config. This only appears if there is a JS error in widgets.wp.com. Manually adding the `env_id` to the config will reveal the actual error that is occurring.

<img width="1539" alt="Markup 2022-09-30 at 12 01 51" src="https://user-images.githubusercontent.com/33258733/193247119-44fafda8-0f0c-4f3a-b673-f598b96e487e.png">

I sniffed around to where this was being required to log the error but was not able to remedy the issue. We need to either update the logging to not require the `env_id` or figure out how to add the dynamic `env_id` to the happychat widgets window.

**Comment by alshakero** [comment]
This will be fixed here: https://github.com/Automattic/wp-calypso/pull/68292
