### ISSUE TITLE
Registering products to WC.com host api plan returns an error

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#68476]
Steps to Reproduce
- Sandbox `public-api`
- Buy WooCommerce Bookings through WordPress.com

Result:
- Order is not created in https://woocommerce.com/my-account/orders/
- Error is logged in `wccom-alerts` slack channel

**ERROR production**
Product woocommerce-bookings is not part of [WordPress.com](http://wordpress.com/) Marketplace.
Logged by `/wccom-plugins/host-plan/includes/api/v1/class-rest-controller.php:144`

Related convo: p1664488635703499-slack-C9J8248EB

**Comment by cpapazoglou** [comment]
I can’t yet understand the root cause of the error. The product slug is parsed but it appears that woocommerce-bookings  doesn’t belong to the WordPress.com Marketplace package. The code that includes it in the package checks if it has a term from the `wpcom_marketplace_categories` taxonomy and as it seems it has such terms assigned



![Image](https://user-images.githubusercontent.com/12430020/193245736-82384ebf-efc5-4bed-b09c-30acb2717b6b.png)

**Comment by cpapazoglou** [comment]
@JulianBustamante  can you take a look?

**Comment by gavande1** [comment]
Linked PR https://github.com/Automattic/woocommerce.com/pull/14605
