### ISSUE TITLE
The `i` button seems unaligned in the users interface

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#68487]
![Image](https://user-images.githubusercontent.com/3832570/193272665-b0ba13ec-2d8e-45b0-b6f0-7b1b14ed0e72.png)

Seems like the `i` button is not aligned vertically. This can be found in the user list in calypso.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- This issue occurs on `https://wordpress.com/people/team/SITE_ADDRESS` when a user is marked as a Contractor.
- It's still the case that the `i` icon is aligned to the top of the user role stickers: 

#### Screenshots/Recordings

![Markup on 2023-05-03 at 11:25:04](https://user-images.githubusercontent.com/27249804/236009544-05203ca3-b4bc-445a-a4a6-6534f490d9ae.png)

📌 ACTIONS
- Assigned to Apex
