### ISSUE TITLE
Remove quick start session mention from new site welcome notification

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#68481]
### What

Remove "quick start session" from new site notification as we don't offer these anymore.

![image](https://user-images.githubusercontent.com/87168/193252875-84f16b4a-5a26-496b-9764-a0936450b22a.png)

### Why

No quick start sessions in premium plan anyway.

### How

Just remove entirely the text highlighted in blue above.

**Comment by Addison-Stavlo** [comment]
D89008-code
