### ISSUE TITLE
Me: make changing email addresses more visually explicit

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#685]
Currently the process for changing your WordPress.com account email address looks like this:

Default:
<img width="697" alt="screen shot 2015-11-24 at 4 11 13 pm" src="https://cloud.githubusercontent.com/assets/437258/11380865/b51ee236-92c6-11e5-90e2-2b4f0d3604ab.png">

Changed:
<img width="701" alt="screen shot 2015-11-24 at 4 12 14 pm" src="https://cloud.githubusercontent.com/assets/437258/11380867/bc95ac5c-92c6-11e5-8bc0-630e56f7be96.png">

I find that to be very confusing. Until I read the fine print I assumed my change did not go through. Instead we should do this:

<img width="700" alt="screen shot 2015-11-24 at 4 14 39 pm" src="https://cloud.githubusercontent.com/assets/437258/11380892/d5dc4b4e-92c6-11e5-8af0-30f354d8a182.png">

We should display the new email address in the field, but disable the field. The user shouldn't be able to change the email again until they verify the new address. If they want to go back to the original address they can click the cancel link.

Also note that the notice did not have a prop for 'is-info' so it is missing styling. The existing class seems like it was added via ClassNames incorrectly as 'info'.

cc @ebinnion @alternatekev @MichaelArestad

**Comment by v18** [comment]
This is related to #975 - email validation

**Comment by ebinnion** [comment]
As a note, the pending notice now looks like the following screenshot after #1273.

![68747470733a2f2f636c6475702e636f6d2f346f73494f4d474b306c2d3330303078333030302e706e67](https://cloud.githubusercontent.com/assets/1126811/11596885/79fde6fc-9a7d-11e5-84ea-9888a1ecf2b4.png)

**Comment by rickybanister** [comment]
The input still needs to be disabled. Clicking cancel would revert the email address and make the field editable again.
