### ISSUE TITLE
Global Styles: Setting default variation clears styles from previous selected variation

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#68512]
### Quick summary

The styles previewed in the Global Styles variation picker are lost when switching from a non-default variation to a default variation.

https://user-images.githubusercontent.com/1233880/193547692-9740599a-0b7c-484d-a561-329c4bbc248a.mov

### Steps to reproduce

- Go to https://wordpress.com
- Switch to a Simple or Atomic site
- Make sure the site uses a block theme such as Twenty Twenty Two.
- Go to Appearance > Editor
- Open the Global Styles sidebar
- Select a non-default style variation
- Select the default style variation.
- Close the sidebar
- Open the GS sidebar again, and open the style variations.

### What you expected to happen

The styles of every variation should be previewed

### What actually happened

The styles from the previously selected variation are missing

**Comment by mmtr** [comment]
Looks like this is caused by the logic that tracks the inserter menu events introduced by #41168, since the issue is not reproducible if I revert those changes. cc @retrofox

**Comment by retrofox** [comment]
> ...since the issue is not reproducible if I revert those changes. cc @retrofox

Hi, Miguel. I haven't touched those files for a long time ago. Thanks for dealing with this.
I'd try to take a look in a few days if that's still useful.

**Comment by simison** [comment]
What's the latest on this?

Me and @alaczek hit this problem just recently when playing with new link-in-bio styles and the experience of switching styles felt pretty buggy.

**Comment by mmtr** [comment]
I'll start looking into this today

**Comment by mmtr** [comment]
Turns out this was finally caused by https://github.com/Automattic/wp-calypso/pull/57957 (cc @Addison-Stavlo). I opened https://github.com/Automattic/wp-calypso/pull/68718 to fix this.
