### ISSUE TITLE
Editor: Google Photos image URL not recognised

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#6853]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. In Google Photos, add an image to a shared folder, click on image to view, and right-click ->Copy Image Link/Location/URL depending on browser
3. In the post editor, click Add Media.
4. Select Add Via URL and paste the URL of the Google Photos image
#### What I expected

That the image will be embedded in the post.
#### What happened instead

The editor gave a File Type not supported error - see screen shot.

It appears that as the Google Photos image URL does not contain the name of the actual image file, e.g. photo.jpg, like images in the WordPress.com media library or images embedded from Imgur.com, the editor doesn't recognise it as an image URL.

However, adding that same URL manually using HTML in the HTML tab of the editor correctly embeds the image. The URL also works when selecting the Add Via URL option in the WP-Admin editor, so the issue is not Google Photo embeds not being supported.
#### Browser / OS version

Confirmed in Firefox and Chrome on Mac OSX
#### Screenshot / Video

<img width="854" alt="new_post_ _kokkiestrialtestsite_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/16901443/26b045fc-4c44-11e6-8693-e4a0b99a80a8.png">
#### Context / Source

Reported via the WordPress.com support forums: http://en.forums.wordpress.com/topic/about-insert-an-image-via-url

**Comment by lancewillett** [comment]
For reference the format of a Google Photos share-able URL is something like this:

`https://goo.gl/photos/[string]` where the string is a GUID with no file extension.

**Comment by gracie** [comment]
This error seems to be impacting images beyond the Google Photos. Example:

http://67.media.tumblr.com/1bd008e8b4c59da9bb5a5bd4f4e47ea7/tumblr_n8lovfOuoE1tuhg7go1_500.gif	

Screencast of issue:

https://cloudup.com/cbuyMWquYCJ

It works correctly in WP-Admin.

Reported in #534707-chat

**Comment by KokkieH** [comment]
@gracie I think your issue might be related to #9600. The add via URL has never supported the Google Photos link as far as I can tell, but other image links started giving trouble since yesterday.

**Comment by KokkieH** [comment]
This is still an issue, though given that we now support linking your Google Photos library directly to your media library and no further reports on this, I'd say it's safe to close.

Feel free to reopen if anyone disagrees.
