### ISSUE TITLE
Expand Data Watch - Collect data on Seller Experience funnels

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#68539]
As part of Expand Data Watch initiative (pdgAPm-vA-p2), we should collect data from September relating to the following:

> Step funnels reporting on Seller Experience flows, including flow completion, upgrades happening in the funnels, and upgrades for Payments Blocks that were inserted in the funnels w/in 7 days of site creation.

This should be able to leverage past metrics work, including https://github.com/Automattic/wp-calypso/issues/65688

**Comment by daledupreez** [comment]
@blackjackkent, I think my work in paYKcK-298-p2 should suffice for this. Can you confirm?

**Comment by blackjackkent** [comment]
Yep, this can be closed out!
