### ISSUE TITLE
Add track events to Atomic sites when editor suggests plugins

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#68541]
### Details

On Atomic sites:
- [ ] Add a tracks event that fires when the Editor returns Blocks “Available to install.” Include a prop that displays the number of block plugins returned.

Follow-up:
- [ ] Add a tracks event for clicks on those items with a prop for the block slug and/or name.

Context: pdh6GB-226-p2#comment-3024

https://user-images.githubusercontent.com/140841/193690806-16812b8b-de1c-4ecd-810a-09c06e35a5d7.mp4

**Comment by allilevine** [comment]
@ianstewart clarified that this is the priority for this sprint:

> an event that fires when the Editor returns Blocks “Available to install.”

We talked in our team call about taking an approach similar to https://github.com/Automattic/wp-calypso/pull/65870 using [wpcom-block-editor](https://github.com/Automattic/wp-calypso/tree/b6c7d311591da4cff591bbba27345f3e2e3d9cda/apps/wpcom-block-editor/).

Is that still our next step @lupus2k?
