### ISSUE TITLE
Task: Update URLs to Domain Connection Docs

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#68548]
### Details

To simplify our domain connection instructions, we will be breaking up our [domain connection doc](https://wordpress.com/support/domains/connect-existing-domain) into two docs:

1. The name server method: https://wordpress.com/support/?page_id=219832 (the content of this draft will be moved into the [live doc](https://wordpress.com/support/domains/connect-existing-domain))
2. The A record method: https://wordpress.com/support/domains/connect-a-domain-alternative-method/ (this doc is live)

The support doc is linked in the domain connection flow in the following places:

Link 1: https://wordpress.com/support/domains/connect-existing-domain/#change-your-domains-name-servers
![image](https://user-images.githubusercontent.com/30727666/193707727-5b2b5146-0675-4acc-84b3-d406f9628d24.png)

Link 2: https://wordpress.com/support/domains/connect-existing-domain/#connect-with-a-records
![image](https://user-images.githubusercontent.com/30727666/193707788-d279abf7-8b56-47eb-a886-9b3ab158062e.png)

These two links will no longer work after we make the docs changes live. We can make the changes live once the URLs are updated in the interface.

### Checklist

- [ ] Update link 1 to https://wordpress.com/support/domains/connect-existing-domain/#step-2-change-your-domains-name-servers
- [ ] Update link 2 to https://wordpress.com/support/domains/connect-a-domain-alternative-method/

@delputnam @rafaelgalani is this something you can take care of, similar to https://github.com/Automattic/wp-calypso/issues/64285 ?

**Comment by delputnam** [comment]
@donalirl I’ll add this to Nomado’s next sprint. We’ll update here with a comment once we’ve updated the links in calypso.

**Comment by delputnam** [comment]
Pending fix here: https://github.com/Automattic/wp-calypso/pull/69291

**Comment by delputnam** [comment]
Fix deployed in : https://github.com/Automattic/wp-calypso/pull/69291

**Comment by donalirl** [comment]
@delputnam @ramynasr sorry I just noticed I pasted the _old_ link for the "Advanced setup" documentation. It should be:

https://wordpress.com/support/domains/connect-a-domain-alternative-method/

Is it possible to update that quickly?

**Comment by delputnam** [comment]
Quick fix deployed in: #69335
