### ISSUE TITLE
Design Preview: Site icon and design title are overlapping

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#68551]
As title, they are overlapping when the viewport is between mobile and desktop

![Image](https://user-images.githubusercontent.com/13596067/193721651-27c7601f-7e9e-4bff-b6f6-a519c55fc3ae.png)

**Comment by bangank36** [comment]
I think the logo and title should be aligned on same line on mobile as well, since there is so much empty space here, what do you think?  
 

![Screenshot on 2022-10-27 at 09-11-24.png](https://cdn-std.droplr.net/files/acc_1243635/ZPK41U)

**Comment by arthur791004** [comment]
No, they don't need to be on the same line.

**Comment by bangank36** [comment]
Landed
