### ISSUE TITLE
Sites Management Page: design display visitor count as column in table view

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#68557]
A goal of Sites Management Page i2 is to "Add the Stats view to the sites list"

The current mockup shows a column for "visitors" and "engagements" in table mode

![Image](https://user-images.githubusercontent.com/1500769/193735133-71df68f1-d526-40a0-88a1-dc06cd570030.png)

Before we start implementing lets figure out
- what's the timeframe the number refer to is it for example number of visitors per month?
- is it the counts from just last month or a rolling average?
- how should we communicate the meaning of these numbers to the user?
- what should engagements refer to? just comments and likes (including likes on comments?)
- caveat: I don't _think_ we have access to the number of FB likes

**Comment by p-jackson** [comment]
My proposal to get the discussion started is that we add an info icon with a tooltip to the column headers, that way we can explain to the user what these numbers refer to
![191244248-ebcbb8af-3de1-4ea9-b935-1299132a788e](https://user-images.githubusercontent.com/1500769/193736282-bc6cb097-8bf9-478c-942e-585138089f90.png)

For the numbers themselves I think we could default to "per day" because that's the default view in Calypso's stats view (see `/stats/day/{{ site slug }}`). In stats view we should visitor, like, and comment counts for the current day. We should just copy exactly how those numbers work.
![CleanShot 2022-10-04 at 17 44 19@2x](https://user-images.githubusercontent.com/1500769/193736260-18182280-2943-4774-8ef6-c69ab72d42a9.png)

Visitors will come over directly, and Engagements will be the sum of Likes and Comments.

**Comment by SaxonF** [comment]
@p-jackson we basically want to take the most vital data from `https://wordpress.com/stats/week` and move it into sites view. Data should already be available for us to use. Your plan sounds like a good first step to me!

**Comment by vindl** [comment]
> My proposal to get the discussion started is that we add an info icon with a tooltip to the column headers, that way we can explain to the user what these numbers refer to

How about linking the numbers to detailed stat pages, like `stats/week/{site}?tab=visitors`?

**Comment by danielbachhuber** [comment]
For a more visual approach, what about sparklines or a bar chart with the last 7 days of visitors?

![image](https://user-images.githubusercontent.com/36432/193818799-166f8bcf-4725-4d3c-8f5d-b1581d8b9e5c.png)

Also, it doesn't seem super high value to me to display "Engagements":
* It's not obvious what "Engagements" actually means.
* Many sites will have very few engagements, and sites with likes or commenting disabled won't have any.

What's the context of the request to add "Engagements"?

Lastly, it seems like we'll need to pull this stats data in as a secondary API request?

**Comment by vindl** [comment]
> For a more visual approach, what about sparklines or a bar chart with the last 7 days of visitors?

This crossed my mind too, it might be nicer if it doesn't add too much noise.

> Also, it doesn't seem super high value to me to display "Engagements":

➕

**Comment by vindl** [comment]
Taking a step back - one of my goals when proposing the stats view was to provide a path for deprecating the dated `/stats` page. I don't feel like the designs proposed above will enable that, unless they are just a first pass on this.

**Comment by p-jackson** [comment]
> provide a path for deprecating the dated `/stats` page

Looks like there's a planned modernisation of the stats page p1HpG7-inx-p2, so doesn't look like it's on a path to being deprecated.

I think there's still space for some stats on the sites manage page though, but it's more about being able to scan things. Like an alert if your viewership happens to drop suddenly. In this sense showing the sparkling is more appropriate than a raw number IMO.

We could even call the column Jetpack Stats! Powered-by-Jetpack for the win 💪

What do you think about the sparkline instead of the raw numbers @SaxonF? Since it's already displayed in the sidebar I'm hoping it won't be too hard to replicate in the dashboard 🤞 

> Lastly, it seems like we'll need to pull this stats data in as a secondary API request?

Definitely! The list of site excerpt data is starting to get long and these stats requests seem like they could be expensive. There's no reason that we can't render the initial table and then let these stats appear one at a time as they load in.

**Comment by danielbachhuber** [comment]
> There's no reason that we can't render the initial table and then let these stats appear one at a time as they load in.

Another fanciness: prioritize API requests for the in-view sites first, then initiate the remaining requests.

**Comment by SaxonF** [comment]
> For a more visual approach, what about sparklines or a bar chart with the last 7 days of visitors?

I considered this but was concerned about dev effort since its not currently part of the cross site stats page. If we aren't concerned about that then let's do it.

**Comment by SaxonF** [comment]
> Looks like there's a planned modernisation of the stats page p1HpG7-inx-p2, so doesn't look like it's on a path to being deprecated.

This is focused on single sites. Is the multi site view a Dotcom only thing?

**Comment by SaxonF** [comment]
> one of my goals when proposing the stats view was to provide a path for deprecating the dated /stats page

> What's the context of the request to add "Engagements"?

@danielbachhuber just an attempt at covering what's shown in the existing stats page

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/1072756/193945753-40ca7aab-e050-42c8-b0df-cd59f2fbff04.png">

**Comment by p-jackson** [comment]
> This is focused on single sites. Is the multi site view a Dotcom only thing?

I realise now that @vindl's comment about deprecating `/stats` is about deprecating the all-sites stats page in Calypso. This makes sense.

@SaxonF shared this mockup here p1664931190290019/1664858998.620499-slack-C041RHH38NQ

https://user-images.githubusercontent.com/1500769/193987479-51e193c1-4acc-4d2e-947e-76e997155d7f.mp4

I think adding the sparkling is the direction we should take. It's better as a scannable view of how the traffic on each of the sites is going, which is what the dashboard is for IMO. I don't think we aim for the tooltip this iteration, but I'm hoping that it won't be too hard to import the existing sparkline component from the Calypso sidebar. 

If we add sparklines to the dashboard with a link to the individual site’s stat page, then maybe we can add a notice to all-sites stats page saying it’s being deprecated and to use the dashboard instead. Reviewing engagement with the notice might give us enough confidence to say deprecating the page is ok, and so we don’t feel the need to implement tooltip.

**Comment by p-jackson** [comment]
I've written up concrete requirements for i2 #68626
