### ISSUE TITLE
Marketplace: Create tracks funnels for logged out page views

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#68560]
pdgAPm-vA-p2 - we have a new request here to setup funnels for logged out page views resulting in plan sign ups.

See p2 for specific details.

- [ ] Create tracks funnels as required
- [ ] Spin off issues for adding new logged out tracks events if required
- [ ] Spin off issues for any looker reports if required

**Comment by candy02058912** [comment]
Seems like a duplicate issue with the one on the board: https://github.com/Automattic/wp-calypso/issues/68599
