### ISSUE TITLE
Marketplace: Top header Refinements - Browse all link text change

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#68575]
Designs [here](https://github.com/Automattic/wp-calypso/issues/67285#issuecomment-1263572934).

Acceptance Criteria:

- [ ] Remove the arrow from “Browse all,” and add a lowercase for “all”. Browse all

**Comment by lsl** [comment]
Beware this link is moving in https://github.com/Automattic/wp-calypso/pull/67781/files?w=1#diff-04e84428ce7f3797e30b27404dfd422ec0b053242ab82d1a6fc0ec58880d0c06R36 (note for me to check this doesn't become a lost update)
