### ISSUE TITLE
Task: Help Center - record the available support options in chat page when the user lands there

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#68578]
### Details

When users load the contact page in the help center, we should record what support options they had. We already record what options they pick, so knowing users preferences is a valuable lesson to take home and it affects our staffing planning.

Context here: p7DVsv-fpN-p2#comment-42253

**Comment by heavyweight** [comment]
Sorry but this seems very vague to me. 
I don't understand what needs to be done.
Could you expand a bit on what is required to be done?

**Comment by alshakero** [comment]
That's fair. Basically, send a track event listing the available options when the user lands in the contact page of the Help Center.

Something like:
```js
useEffect(() => {
	recordTracksEvent( 'calypso_helpcenter_contact_options_impression', {
			location: 'help-center',
			hadChatOption: renderChat.state === 'AVAILABLE',
			hadEmailOption: renderEmail
		} );
}, [renderChat, renderEmail])
```

In this page, https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/components/help-center-contact-page.tsx#L89
