### ISSUE TITLE
Marketplace: Top header Refinements - Color changes

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#68572]
Designs [here](https://github.com/Automattic/wp-calypso/issues/67285#issuecomment-1263572934).

Acceptance Criteria:

- [ ] Add a Light Grey background #fdfdfd to the top header
- [ ] Add/change the below-header background color to white. This applies to all pages (#fff)
- [ ] Change the color of the main title (Flex your site's features with plugins), the activated category button, and the category names to Blue90 (#01283D).
- [ ] The line (stroke) right below the main top header should be 1px #F6F7F7

**Comment by lupus2k** [comment]
Reopened because of this: https://github.com/Automattic/wp-calypso/pull/68717
