### ISSUE TITLE
Task: Help Center - Offer support on Atomic sites too

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#68583]
### Details

The current blockers for Atomic support are the following:

1. **Support tickets**: no ability to post support tickets due to lack of an API accessible by Jetpack sites. We should add a Jetpack endpoint, just we did with [articles](https://github.com/Automattic/wp-calypso/pull/65329). 
2. **Chat JWT tokens**: in Calypso and simple sites we use 3 endpoints to get a Happychat JWT token. /me, /sign/ and /session. We need to create a single Jetpack endpoint that directly gives the JWT without exposing any of the info any of these endpoints return. We should return as little info as possible.

**Comment by arcangelini** [comment]
Add V2 endpoint for creating tickets - D89579-code

**Comment by arcangelini** [comment]
~After investigating, it seems we already have an endpoint for `/jwt/sign` - fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg-ncv-cyhtvaf%2Sraqcbvagf%2Synfntan.cuc%3Se%3Q3op5q45r-og~

Add V2 endpoint for JWT signing - D89714-code

**Comment by arcangelini** [comment]
Add V2 endpoint for creating Happychat session - D89671-code
