### ISSUE TITLE
Create a new funnel reporting on the flow of logged-in/out visits to /plugins

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#68599]
### Details

Context: pdgAPm-vA-p2

Create a Funnels reporting on the flow of logged-in/out visits to /plugins, viewing plugin details, activating by plan. 
Along with a report on resulting plan upgrades as a result.

The logged-out funnels should also include the in-between signup pages.

**Comment by candy02058912** [comment]
Slack thread: p1665139574444899-slack-CKZHG0QCR

**Comment by allilevine** [comment]
@paulopmt1 @candy02058912 Can we close this one with pb5gDS-27P-p2 ?

**Comment by paulopmt1** [comment]
Sounds good @allilevine. Thanks for the funnel @candy02058912, it was really helpful on that report.

**Comment by candy02058912** [comment]
Thanks @paulopmt1 for writing up the post 🙏
