### ISSUE TITLE
Task: Track Reader refresh issues

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#68604]
### Details

This task will be used to track any bugs introduced with the reader refresh #66650

### Checklist

- [x] Reader full post table width is too wide - eg https://wordpress.com/read/feeds/45339984/posts/4283753749
<img width="1515" alt="Screen Shot 2022-10-04 at 3 09 34 PM" src="https://user-images.githubusercontent.com/5560595/193918855-14a94686-d5ea-490f-9c8b-c235272a1058.png">

- [x] Share popup tooltip not positioned correctly on mobile
<img width="485" alt="Screen Shot 2022-10-04 at 3 13 56 PM" src="https://user-images.githubusercontent.com/5560595/193919134-ef60ad78-c9b5-454f-b162-6e32b7276bc6.png">

- [x] Some posts seem to be missing excerpts and titles p1664939411824579-slack-C03NLNTPZ2T
![Screenshot 2022-10-05 at 11 02 43 AM (1)](https://user-images.githubusercontent.com/22446385/193985571-bd9964db-3ac2-46d4-a123-a2d864a7db18.png)

- [x] Using `J` and `K` shortcuts to tab through posts seems to stop working part way down the page https://github.com/Automattic/wp-calypso/issues/68604#issuecomment-1267686054, https://github.com/Automattic/wp-calypso/issues/68604#issuecomment-1267703081, p1664923429516379-slack-C03NLNTPZ2T

- [x] When flags are visible in popover menu (flags are visible to a12s), the width of the highlight can be too narrow p1664859938143759/1664853036.397099-slack-C03NLNTPZ2T
<img width="360" alt="Screen Shot 2022-10-04 at 3 04 52 pm" src="https://user-images.githubusercontent.com/22446385/193987410-ee09ef66-6ad2-4e7d-b4bf-bdf2df261058.png">

- [x] Featured images being omitted from gallery due to dimension ratios - p1665153353799339-slack-C03NLNTPZ2T
Example found [here](http://calypso.localhost:3000/read/feeds/33517989/posts/4287993750). Wolf image is being filtered and not included in gallery.

### Related

#68647

**Comment by sirbrillig** [comment]
I noticed the newer, thinner reader view just now and something seems to be broken when navigating posts via the keyboard (`j` and `k`). If you press `j` to scroll down a bunch of posts, eventually the scrolling just stops even though the selected post keeps moving down.


https://user-images.githubusercontent.com/2036909/193944475-a23f141e-d3ef-4465-ab6a-742a4a48be04.mov


My reproduction instructions:

1. Make sure you're subscribed to a bunch of p2s.
2. Visit https://wordpress.com/read/a8c
3. Press `j` repeatedly; note that each time it will highlight the next post in the viewport, scrolling it into the center of the viewport.
4. Notice that after a handful of posts, pressing `j` will continue to highlight the next post, but the viewport will stop scrolling that post into view.
5. Also notice that if you scroll down past this point using a scroll bar or scroll wheel, and then press `j`, the viewport will scroll back up to a post much higher in the list (the last one that it scrolled into view automatically).

**Comment by ashleyleia** [comment]
I'm noticing the same issue as described above that pressing 'j' only scrolls down to a certain point, and then won't scroll down any further.

I like the more modern look of the refresh, but I think a few tweaks could make it more user-friendly.

With the "like" icon no longer being filled when a post has been liked, it's now quite difficult to see the difference in icon outline colour between what's been liked (#0675C4) and what's not (#646970). For me and other Reader users I know, seeing what we've already "liked" helps us see what we're caught up to in our feed, so having more contrast between what's  been liked and what hasn't been would be really helpful.

For the .reader-post-card .reader-excerpt text, the combo of 1rem sans-serif system font with 22px line height and -0.24px letter-spacing looks a bit small, scrunched together, and hard to read, and for me at least, slightly tweaking even one of those properties boosts readability.

I like the idea of a narrower reader container, but a max-width of 600px leaves a lot of white space, and given that the font is small and individual cards are now closer together with just a hard-to-see 1px solid #e9e9ea border-bottom dividing them, it feels a bit disproportionate.

**Comment by roo2** [comment]
Thanks for the feedback @ashleyleia! I've worked on the like button contrast issue in https://github.com/Automattic/wp-calypso/pull/68616 , added the letter spacing issue to our checklist, and forwarded the min-width feedback to @ollierozdarz 👍 p1664919359274319-slack-C03NLNTPZ2T

**Comment by eoigal** [comment]
I don't think this is a bug. [The post below is being detected as a photo post which means the title and excerpt are not rendered. If character length is less than 85 chars and the canonical image is the right size, it gets displayed as a photo post.](https://github.com/Automattic/wp-calypso/blob/5296b8665ff87f18665bbd0e23b6381108950af4/client/state/reader/posts/normalization-rules.js#L80) 

* Some posts seem to be missing excerpts and titles p1664939411824579-slack-C03NLNTPZ2T
![Screenshot 2022-10-05 at 11 02 43 AM (1)](https://user-images.githubusercontent.com/22446385/193985571-bd9964db-3ac2-46d4-a123-a2d864a7db18.png)

**Comment by davemart-in** [comment]
**RE: Narrow width**

@ashleyleia we plan to introduce a sidebar, which should help fill out the page a bit more, but had to cut it from this v1 release:

<img width="720" alt="CleanShot 2022-10-05 at 15 59 07@2x" src="https://user-images.githubusercontent.com/5634774/194152112-5f845c5e-bba7-400e-b8a6-ef71b1b46e90.png">

**Comment by ashleyleia** [comment]
@davemart-in Okay, that makes sense! 👍

**Comment by eoigal** [comment]
Closing this for now as all known issues have been fixed. Can re-open if any new issues are found.

**Comment by eoigal** [comment]
Closing again. If another issue pops up, can re-open.

**Comment by zdenys** [comment]
> Narrow width

The user in 5607255-zd-woothemes is not happy about this change:

- https://github.com/Automattic/wp-calypso/issues/66626

Here is their feedback:

> The reader is now extra narrow (see all that white space on the sides between the articles and the side bar on the left, and all the white space on the right between the post and edge of the browser) and it didn't used to be like that. The post would take up the full width of the page. The various buttons under the post have changed as well. It looks just like how the app looks on my phone. It is very distracting being on a laptop and seeing ALL that whitespace, especially as it didn't used to be that way. I would like to know why the change was made, as users on cell phones can already use the app and this alienates computer users. I am not the only seeing it (see the comment section of https://bookstooge.wordpress.com/2022/10/04/the-wp-reader-just-changed-on-me/ to confirm that others see the same thing as me).
>
> I understand incremental changes, but this was a radical visual change, for the worse and I could find ZERO information about it anywhere online. The previous person I was talking to didn't even seem to know that ANY change had taken place and you yourself seem to be under the impression that nothing has changed. That is worrying to me as you people are supposed to be aware of changes being made. The fact that you are not or are not aware of how those changes affect users leaves me wondering just how effective support is.
>
> A simple, "we changed the reader and we know it looks different" is all I was looking for. But so far you all seem to disavow the changes and despite the screenshot I took are denying the differences. I'm sorry to be so hostile, but this continued attitude by automattic employees is wearing thin.
>
> To sum up, I would simply like to know WHY the changes were made and what the reasoning behind the changes were.

cc: @davemart-in

**Comment by davemart-in** [comment]
@zdenys thanks for the feedback!

The changes were made to begin to incrementally improve the reader. This is the first of many updates that we plan to make. We had a blog post queued up to share this update, but since we had to cut scope, it was recommended that we we not publish it yet. Once we add the side bar, the page should look less skinny, and after that change is out, we'll get a blog post up.
