### ISSUE TITLE
Sites Management Page: Launch nag icon should be bolder

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#68623]
As pointed out here https://github.com/Automattic/wp-calypso/pull/68533#issuecomment-1266336815, the donut icon in the launch nag message is a little thin.

![Image](https://user-images.githubusercontent.com/1500769/193982836-5ac63fb1-5da3-4024-9220-6fa65814a6bd.png)

Let's make it a pixel or two thicker.

Done is:
- [ ] Donut icon has an appropriate visual weight. It should be easy enough to interpret without squinting.
- [ ] Run it past before @SaxonF before merging

**Comment by mpkelly** [comment]
I am starting this one.
