### ISSUE TITLE
Marketplace: remove FullListView

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#68621]
I found the `FullListView` component to be unnecessary in https://github.com/Automattic/wp-calypso/pull/67781. It used to be used more widely but we now use the PluginsBrowserList directly. The only place it is currently used is the category page.

Let's inline it into the category page so we can more easily implement https://github.com/Automattic/wp-calypso/issues/68620

- [ ] Delete and inline `FullListView` into the category page component

Example approach: https://github.com/Automattic/wp-calypso/pull/67781/commits/dcda548a3daa88122e5ae846ebceb452ac86e427

**Comment by allilevine** [comment]
@lsl What priority would you assign to this? Is it needed before Collections?

**Comment by lsl** [comment]
Not "needed" but it should happen before further work happens on these section components or any changes of margin / spacing between sections takes place. I suspect some of that will be needed for the collections work so we could prioritize it for doing earlier.

**Comment by lsl** [comment]
This (#68621) and https://github.com/Automattic/wp-calypso/issues/68620 needed to be done in one step, PR ready here, https://github.com/Automattic/wp-calypso/pull/68802.

Dropped the sprint goal flag from the third part https://github.com/Automattic/wp-calypso/issues/68622 as it's less important for the collections work.

Would like to keep it in the backlog for this sprint. It's the last step in closing out https://github.com/Automattic/wp-calypso/issues/65574
