### ISSUE TITLE
Sites Management Page: Replace `react-intersection-observer` with `IntersectionObserver`

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#68625]
#68533 introduced the `react-intersection-observer` dependency. This just wraps the browser's built-in `IntersectionObserver` functionality, so I don't think taking on the extra dependency is worth it. It just makes dependency upgrades harder down the track.

Here's some existing Calypso code that does the same things
https://github.com/Automattic/wp-calypso/blob/bba5d88eb17e0ab5ea9481486cacd0ca05263f16/client/components/activity-card-list/visible-days-limit-upsell/hooks.ts#L5

And we have a very similar helper hook in `/client/lib/detect-window-boundary/index.ts`. Although it's for when something leaves the viewport (useful for sticky headers)
https://github.com/Automattic/wp-calypso/blob/bba5d88eb17e0ab5ea9481486cacd0ca05263f16/client/lib/detect-window-boundary/index.ts#L14

**Comment by danielbachhuber** [comment]
> #68533 introduced the `react-intersection-observer` dependency. This just wraps the browser's built-in `IntersectionObserver` functionality, so I don't think taking on the extra dependency is worth it.

FWIW, `react-intersection-observer` also offers some nifty features outside of the browser's built-in `IntersectionObserver` functionality. It exposes those through a nice API, is well-maintained, and has good test coverage. I'm not sure what we gain by recreating all of this on our own.

**Comment by mpkelly** [comment]
I was siding with @danielbachhuber after checking Bundlephobia and seeing it was only 1.8kb gzipped, but the hook in `visible-days-limit-upsell/hooks.ts` is precisely what we need, so I think it makes sense to modify that so it accepts a callback param and then reuse it. I've actually done that already, but I will try and add a test suite as well.

**Comment by mpkelly** [comment]
It's a bit awkward for manual testing and would depend on an external dependency for mocking, so I decided to test it manually.
