### ISSUE TITLE
Plans: cancel the google-vouchers test

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#6865]
The google-vouchers test was a failure in the sense that presenting the feature to users (at least the way we have done so far) does not help to sell plans.

Let's stop running the test, no longer mention advertising vouchers at all on the plans pages or the plans/compare pages, but show the google-vouchers feature for premium and business plans on the my-plan page and the post-purchase thank-you page.

**Comment by retrofox** [comment]
[ ] Remove the feature from both `plans` page
[ ] Remove the feature from both `plans/compare` page
[ ] Implement google vouchers on the my-plan page.
