### ISSUE TITLE
Navigation and logo are not displayed correctly in some pattern previews

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#68695]
Some patterns are not displayed correctly in the previews. It seems unrelated to Blank canvas because it can be reproduced with all themes.

The header pattern **Centred Header with Logo and Navigation** shows the logo placeholder in the [source site](https://dotcompatterns.wordpress.com/2022/08/29/centred-header-with-logo-and-navigation/) site 

<img width="670" alt="Screen Shot 2565-10-06 at 10 57 30" src="https://user-images.githubusercontent.com/1881481/194210924-b9238b27-63ff-4859-9fd8-bf93180b4170.png">

But not in the [preview](https://mc.a8c.com/patterns-toolkit/block-patterns/index.php?site=dotcompatterns.wordpress.com&categories%5B0%5D=footer&theme=zoologist&pattern=5608).

<img width="499" alt="Screen Shot 2565-10-06 at 10 58 22" src="https://user-images.githubusercontent.com/1881481/194210935-d9b8144f-d219-4adf-bf32-02c9de487f4e.png">

These footer patterns don't show the navigation in the preview:
- **Footer with credit line and navigation** [Preview](https://mc.a8c.com/patterns-toolkit/block-patterns/index.php?site=dotcompatterns.wordpress.com&categories%5B0%5D=footer&theme=zoologist&pattern=5883) - [Source site](https://dotcompatterns.wordpress.com/2022/08/26/footer-with-credit-line-and-navigation/)

<img width="1182" alt="Screen Shot 2565-10-06 at 10 56 53" src="https://user-images.githubusercontent.com/1881481/194211060-7c03192a-e929-4eac-a00f-89fe63fd390c.png">
 
- **Footer with navigation and credit line** [Preview](https://mc.a8c.com/patterns-toolkit/block-patterns/index.php?site=dotcompatterns.wordpress.com&categories%5B0%5D=footer&theme=zoologist&pattern=5883) - [Source site](https://dotcompatterns.wordpress.com/2022/08/26/footer-with-navigation-and-credit-line/)

<img width="1152" alt="Screen Shot 2565-10-06 at 10 57 00" src="https://user-images.githubusercontent.com/1881481/194211052-a50061b8-e8c2-476e-bb15-f41c0128ac0e.png">

**Comment by autumnfjeld** [comment]
@miksansegundo   Could this be related to issues discussed here pNEWy-eFy-p2

https://github.com/Automattic/dotcom-forge/issues/1034

**Comment by arthur791004** [comment]
Actually, that placeholder is the site logo on the dotcompatterns source site 😂 Here is that logo: https://dotcompatterns.files.wordpress.com/2020/04/site-logo.png

**Comment by miksansegundo** [comment]
I think we should preview the pattern with the log using a white image as we do in the pattern inserter in the editor.

![Image](https://user-images.githubusercontent.com/1881481/194835829-db2e78af-409a-4d36-a9f7-01bd87b1a6e0.png)

I think in the editor they hardcode the logo image when there isn't one. Can we do the same for the API `/block-previews`? I think we can and it will be a solution.  

And about the footer patterns that have missing navigation, @arthur791004 mentioned that the function `gutenberg_render_block_core_navigation` does not render anything if the menu items are empty. However, the issue is reproducible in the MC Pattern Toolkit tool where the menu items are not empty. Other patterns show the navigation correctly.

This footer ID `5883` that does not show the navigation uses this code:
```<!-- wp:navigation {"ref":6217,"layout":{"type":"flex","justifyContent":"right"}} /-->```

The header pattern ID `5588`  that use this code shows the navigation:
```<!-- wp:navigation {"layout":{"type":"flex","justifyContent":"right"}} /-->```

![Image](https://user-images.githubusercontent.com/1881481/194841636-dcc4a131-57df-4a24-9536-303e265aa7cf.png)

I'm investigating this.

**Comment by miksansegundo** [comment]
I found that these footer patterns use a navigation block with `"ref": 6217` that doesn't display anything because it throws the error `Navigation menu has been deleted or is unavailable`. 

The same issue happens on the Centered header pattern (ID 5579) because it uses the same `ref: 6217`.

We just have to remove the ref to make them work. I asked about it in p1665463016671209-slack-C02M88KJ684

I tested it in the editor to confirm that removing the ref fixes the issue.

**Code**
![Image](https://user-images.githubusercontent.com/1881481/194998695-5689e06b-1281-4c8b-8980-abd90e456c0c.png)

**Preview**
![Image](https://user-images.githubusercontent.com/1881481/194998694-42922e59-ff9d-4e64-a994-9cafcafea3e9.png)

**Comment by miksansegundo** [comment]
I found a solution to show a site logo placeholder in the previews https://github.com/Automattic/wp-calypso/pull/68894.

About the navigation issue, I got the confirmation to remove the `ref: 6217` from the patterns affected in `dotcompatterns`.

**Comment by miksansegundo** [comment]
I found a much simpler solution to show the logo in the previews. I just had to upload a custom logo to the Blank Canvas Blocks demo site. We'll have to upload the logo to the new Clean Slate theme demo site when it is ready.

About the navigation issue, the issue cannot be fixed by removing the navigation ID `ref: 6217` because the editor adds that `ref` automatically. I found a simple solution, we have to use `navigation-link` blocks as we do in other patterns.

```
<!-- wp:navigation {"layout":{"type":"flex","justifyContent":"right"}} -->
  <!-- wp:navigation-link {"label":"About","url":"#","isTopLevelLink":true} /-->
  <!-- wp:navigation-link {"label":"Blog","url":"#","isTopLevelLink":true} /-->
  <!-- wp:navigation-link {"label":"Contact","url":"#","isTopLevelLink":true} /-->
<!-- /wp:navigation -->
```

I think this option is the best because the preview is consistent, as the navigation items don't depend on the navigation `ref: 6217` that exists only in the source site.

I'm waiting for confirmation to go ahead and update the affected patterns to use `navigation-link` blocks. See p1665563215329609/1665463016.671209-slack-C02M88KJ684

**Comment by miksansegundo** [comment]
✅ The logo and navigation are displayed in all our header and footer patterns! 

**Headers**
<img width="325" alt="Screen Shot 2565-10-13 at 10 19 45" src="https://user-images.githubusercontent.com/1881481/195492332-d417fedf-0084-47c6-9aca-41af1add36c0.png">

**Footers**
<img width="610" alt="Screen Shot 2565-10-13 at 10 30 26" src="https://user-images.githubusercontent.com/1881481/195492656-34849764-fd59-4dce-ac76-8c4661b9b414.png">

I'm going to continue working on improving the previews.
