### ISSUE TITLE
Style variations are not being saved if the sidebar isn't on the variations screen

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#68707]
### Quick summary

When changing to a non-default style variation, the choice is not saved when clicking save if the variation screen is navigated away from.

This happens on simple and atomic sites but not jetpack sites. Presumably a bug in ETK or wpcom-block-editor.

### Steps to reproduce

1. Create a wpcom site
2. Use a block-based theme with variations, e.g. twenty twenty-two
3. Go to Appearance -> Editor in the menu to open up FSE
4. Click the Styles icon in the top right (half-empty circle) to open the Styles sidebar
5. Click Browse styles
6. Choose a non-default variation, i.e. any variation except the top left one
7. Notice the preview in the main part of the screen changes to match the selected variation
8. Click the '<' next to 'Browse styles' to go back in the sidebar
9. Press Save

### What you expected to happen

1. A prompt saying 'Are you ready to save? Showing that the Custom Styles has been changed
2. After hitting Save again:
3. The variation choice should be saved, disabling the Save button. 
4. Viewing the front-end of the site shows that the variation is being used - it looks somewhat like the preview

https://user-images.githubusercontent.com/93301/194288936-a332b31b-d7f4-47b3-a1ee-bd7dcf4d06a3.mp4

### What actually happened

1. The sidebar very quickly (it's just a flash) changed to the Browse styles page and then changed back. 
2. The Save button is not disabled
3. Viewing the front-end of the site shows the original variation being used.

https://user-images.githubusercontent.com/93301/194289506-0c03e6d5-c9c7-4bdd-bb5d-c1fc887adee3.mp4

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

1. Press Browse styles
2. (If still in the editor from a failed save attempt) Select a different variation
3. Select the variation you want
4. Press Save

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated 
- Tested on AT - Could Not Replicate 
- Tested on Self-hosted -  Could Not Replicate 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- If you press Save a second time, it works for some reason
- Unable to reproduce on Atomic

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by mmtr** [comment]
I confirmed it's unrelated to ETK or the `wpcom-block-editor` app, so since it happens on Simple sites only I wonder if the underlying issue is because they are not fully updated to WordPress 6.1.

**Comment by mmtr** [comment]
I've been able to identify thanks to `git bisect` that the issue was introduced when we activated Gutenberg 14.1.1 on prod (D87743-code).

**Comment by mmtr** [comment]
This is super weird. Now I can replicate the issue on Atomic sites and self-hosted sites too, so I think this is a Gutenberg issue.

I created an issue there (https://github.com/WordPress/gutenberg/issues/45165), so I'm closing this one in favor of that.

**Comment by mmtr** [comment]
This was solved in Gutenberg 14.4.0.
