### ISSUE TITLE
Page Layouts Only Showing One Option for Home and Blog

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#68716]
### Quick summary

When creating a new page only one layout option is showing for "Home" or "Blog" types. This is different than what is shown in this [YouTube video](https://www.youtube.com/watch?v=CEJLoXipdL0&t=149s)

### Steps to reproduce

1. Create a new page.
2. When `Page Layout` modal pops-up switch choose "Home" or "Blog" from left sidebar.
3. Only one option shows for each of these.

![Markup 2022-10-06 at 10 26 16](https://user-images.githubusercontent.com/93800099/194340161-621f79d1-26ce-4a3f-bc5d-3349034ba611.png)

### What you expected to happen

To see more than one option.

### What actually happened

Only one option shows.

### Context

37272978-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Tried various themes both FSE and Classic and issue persists. The theme doesn't seem to affect how this works.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Workaround details

Not really a good workaround, but the user can use Block Patterns instead.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: n/a

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated in both Simple and AT, just as described above.

*Example on AT site*
![Screen Capture on 2022-10-06 at 17-14-33](https://user-images.githubusercontent.com/27249804/194440560-46049b00-77d7-4cde-92f0-197fe184821b.gif)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by kerrynicl** [comment]
another case - hc-37287825

**Comment by csabarakasz** [comment]
I also noticed this issue while working on the Compelling Homepage Webinar presentation. So +1!

**Comment by cintacks** [comment]
Another example here: 37197877-hc

Advising user to use block patterns 😑

**Comment by brinbliss** [comment]
+1 as well! This is a very useful tool for fixing accidentally deleted layouts or homepage blocks, or directing a user to create a new page for a particular part of their site.

**Comment by khristiansnyder** [comment]
+1. Noticed this on my site. I often direct others to this tool to quickly create pages using the layouts and would be quite valuable to have showcase the rest of the layouts.

**Comment by upwardmomentum84** [comment]
Reported again here - 40163553-hc

**Comment by cuemarie** [comment]
Ran into this here: 14291644-hc

User reported the issue under **Home** and **Contact**, and noted they also couldn't find anything useful or similar to our tutorial videos under **Featured.**

Recommended they start from a blank page, then add patterns, or use https://wordpress.org/patterns/

**Comment by annezazu** [comment]
Hey folks! Looping back on this quite a bit later and noticed that we don't show "Home" patterns anymore:

![Screenshot 2024-09-02 at 6 21 51 PM](https://github.com/user-attachments/assets/bede685b-1723-4ea1-ab1b-d73c9f2ce601)

We also show a dedicated section for Blog Posts which has six options available. There are also four patterns for Contact. Since this issue opened to, https://wordpress.com/patterns was launched and integrated.

I'm going to close this out as a result but let me know if I missed anything and **please** share what patterns you'd like to see more of to benefit users.
