### ISSUE TITLE
Marketplace: Upsell nudge "blinks" when user is already on a plan that supports plugins

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#68748]
Slack Thread: p1665130893251959/1665074605.761439-slack-C02FMH4G8

https://user-images.githubusercontent.com/6586048/194515734-11b82506-4297-453e-bdfa-a0e7f885d29b.mp4

**Comment by simison** [comment]
Here's a video:

https://user-images.githubusercontent.com/87168/194516261-801ae385-eb31-44a2-86d8-a0937aefa31d.mov

I opened the plugins page with hard-refresh to clear cache. 

Spacing with "must have premium plugins" looks sort of tight as well.

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/issues/66736 / https://github.com/Automattic/wp-calypso/pull/69202
