### ISSUE TITLE
Editor / CPT: Trash post button should trash, not delete, CPTs

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#6876]
Related: #6179

In #6179, a new `trashPost` action creator was added to the posts state, enabling ability to trash custom post types by calling the save endpoint with `status: 'trash'`. The editor currently uses the `POST /sites/%s/posts/%d/delete` endpoint, which trashes posts and pages, but permanently deletes custom post types. We should either update the trashing behavior in the editor to use the new `trashPost` action creator or update the legacy Flux `PostActions.trash` method to use the save endpoint.

cc @codebykat

**Comment by codebykat** [comment]
I'm actually fixing this in the API (to trash CPTs as well as posts/pages; right now it's hardcoded to skip trash unless type is `post` or `page`, which doesn't seem right).

The editor's Restore functionality isn't right, though. (It needs to call `/restore`, not update the post with `status=draft`).

**Comment by codebykat** [comment]
BTW using `/delete` when possible is quite a bit more performant than updating the post with `status=trash`, since there's a bunch of extra logic in the latter to save any other post changes that were also transmitted.

**Comment by aduth** [comment]
>The editor's Restore functionality isn't right, though. (It needs to call `/restore`, not update the post with `status=draft`).

Can you create a separate issue for this? If we change the API behavior for the `/delete` endpoint, we can close this issue. That said, there's some history on whether that'd require a version bump, since it's a documented endpoint ([and documented behavior](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/posts/%24post_ID/delete/)).

Ref: D2061-code

**Comment by codebykat** [comment]
Proposed fix in D2299-code

**Comment by codebykat** [comment]
Opened another issue for restore in the editor: https://github.com/Automattic/wp-calypso/issues/6878

**Comment by codebykat** [comment]
Fixed the delete endpoint in r139292-wpcom. I also fixed up the documentation wording (my reading is that the behavior was previously undefined for CPTs).
