### ISSUE TITLE
Task: Fix CSS styling On Tools->Marketing Cards

### ISSUE THREAD

**Issue by ayebare** [Automattic/wp-calypso#68761]
### Details

Issue Origin:  [issue reported by @niranjan-uma-shankar ](https://github.com/Automattic/wp-calypso/pull/68635#pullrequestreview-1131219158)

On the Tools->Marketing page,  There is a minor button spacing issue in the mobile view - the CTA button would look better aligned to the center but it's correctly aligned to the right. 

<img width="741" alt="Align CTA center" src="https://user-images.githubusercontent.com/11347472/194533048-fa51eff6-a23e-41b2-b138-8a9c299466a0.png">

**Steps to reproduce**
Open the Toos->Marketing 
Switch to mobile view using chrome tools and look at the feature list cards.

**What you expected to happen**
CTA Buttons of each card should be aligned in the center of the card.

**What actually happened**
CTA button is aligned to the right.

**Browser**
Google Chrome

### Checklist

- [ ]
- [ ]

**Comment by gmovr** [comment]
Cool! Adding this to our board 👍

**Comment by kirtanchandak** [comment]
can I work on this ?

**Comment by steve-lgtm** [comment]
I just fixed the issue. How can I contribute it?

**Comment by 0xClint** [comment]
Is this will be tagged as hacktobertfest?

**Comment by gmovr** [comment]
Thanks for the interest in contributing to Calypso! 

Feel free to make a pull request containing the changes. You can read more about contributing to Calypso here: https://github.com/Automattic/wp-calypso/blob/trunk/docs/CONTRIBUTING.md

**Comment by dawkrish** [comment]
is this issue still open or closed ?

**Comment by Tanujp106** [comment]
Is someone working on this issue right now?

**Comment by ayebare** [comment]
Thanks for the interest @kirtanchandak , @steve-lgtm , @Omkar0803 , @krishnanshagarwal112 and @Tanujp106  

If any of you is still interested in contributing to this fix, feel free to post a pull request in this thread, and I will do my best to guide you till your fix is merged.
As @gmovr  mentioned, I recommend you read through https://github.com/Automattic/wp-calypso/blob/trunk/docs/CONTRIBUTING.md before you commit.

**Comment by utkarshkumarawasthi98** [comment]
Hello, please assign this issue to me.

**Comment by ayebare** [comment]
Thanks, @utkarshkumarawasthi98 . The issue has been assigned to you. let me know if you need anything.

**Comment by utkarshkumarawasthi98** [comment]
Can you please share the path where the file is located so that I can look into it, thanks.

**Comment by arjunpotter17** [comment]
Hey, I've fixed the issue and opened a pull request. Kindly help me out.

**Comment by dawkrish** [comment]
I am not the maintainer of this project

**Comment by arjunpotter17** [comment]
@ayebare I have made a pull request fixing the issue. Kindly input suggestions. Is there anything else for me to do?

**Comment by ayebare** [comment]
Owesome, I will take a look @arjunpotter17 as soon as I get a moment, then help move this forward :)

**Comment by flamealchemist5** [comment]
hi there, please assign this issue to me.

**Comment by Kadambini30** [comment]
hii can you assign this issue to me please, is it still open?? @utkarshkumarawasthi98

**Comment by AarthiElango** [comment]
hi, can you assign this issue to me.

**Comment by Raj100679** [comment]
@ayebare Is this issue open , I can work on this?

**Comment by akshitchowdhury** [comment]
@ayebare Hi..I'm interested on working in this issue. You can count me in and assign it to me if its still open
