### ISSUE TITLE
Themes: Remove the upsell nudge when there are no results on the themes search

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#68789]
Due to #68542, there will be a button to upsell on this case, so this nudge won't be needed.

<img width="1288" alt="Screen Shot 2022-10-07 at 14 53 04" src="https://user-images.githubusercontent.com/5039531/194642802-a8f7943f-fd9a-4428-a346-3ef0dd9619a5.png">

**Comment by cpapazoglou** [comment]
The upsell nudge should be hidden only when the no results banner shows.
