### ISSUE TITLE
Move `billing_intents` from sqlite to mysql

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#68829]
While developing the SaaS licensing we have to create a new table `billing_intents`. In order to avoid making modifications to a live database, we opted for using SQLite. When ready with the table schema, we should move this to MySQL.

**Comment by gavande1** [comment]
Schema created at 2ddf3-pb/#sql

**Comment by cpapazoglou** [comment]
Generally looks good to me, I am just wondering:
- Should the `billing_plan_id` be unsigned as in `billing_plans` fbhepr%2Skers%2Sfpurznf%2Sovyyvat%2Qncv%2Sovyyvat_cynaf.fdy%3Se%3Q233357%26zb%3Q14%26sv%3Q1%231-og?
- Same for `intent_id`

**Comment by gavande1** [comment]
Yes. I agree. It should be unsigned.

**Comment by gavande1** [comment]
Diff created D93260-code

**Comment by gavande1** [comment]
Deployed r256951-wpcom
