### ISSUE TITLE
Add 'Search' to Sidebar when visiting any WordPress.com site.

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#6882]
#### Steps to reproduce
1. Go to any WordPress.com site (https://aaronyantest6.wordpress.com/)
2. Click on 'Reader' at the top left to show the sidebar
3. There is no 'Search' in this sidebar

#### What I expected

I expected to see the sidebar items (such as 'Search') also seen when visiting wordpress.com:

- Followed Sites
- Discover
- Search
- Recommendations
- My Likes

#### What happened instead

The sidebar was missing 'Search' 
- Followed Sites
- Discover
- Recommendations
- My Likes

#### Browser / OS version

Google Chrome Version 51.0.2704.106 (64-bit) / OS X El Capitan 10.11.5

#### Context / Source
Testing the signup process and arriving at the Reader (specifically searching in the Reader). Currently, it takes three clicks to search the Reader from any WordPress.com site.

1. Click 'Reader' (expose sidebar)
2. Click 'Followed Stream' in the sidebar
3. Click 'Search' in the sidebar

#### Screenshot / Video

Sidebar from any WordPress.com site
![signup_part1](https://cloud.githubusercontent.com/assets/4505888/16935358/9b8a32b4-4d13-11e6-81be-0349893fa389.png)

Sidebar from WordPress.com
![signup_part2](https://cloud.githubusercontent.com/assets/4505888/16935359/9b8fd700-4d13-11e6-993d-c0fb60df5a16.png)

**Comment by lancewillett** [comment]
This isn't a Calypso bug but a discrepancy in the front-end navigation and toolbar for WordPress.com sites. Moved to internal bug tracker: 7800-wpcom
