### ISSUE TITLE
[New Post] Make sure the post title is outputted as plain text (without extra HTML tags)

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#68836]
The _New Post_ email doesn't filter out unnecessary HTML tags from the post title. This could be noticed in one of the recent newsletter emails:

![Image](https://user-images.githubusercontent.com/25105483/194898151-80c874a6-0af2-4129-96ef-89370d4a9785.png)

I believe we should make the email template strip down all unnecessary HTML tags.

**Comment by yansern** [comment]
The observation that we notice is that on the Gutenberg Editor, you can enter html tags such as `<i>` or `<strong>` and it will be stripped (only visually) on the editor, but still saved in the post title.

But this does not apply to all html tags, e.g. `<h1>` and `<ul>` tags are stripped off in the post title when saved.
 
On the frontend, the `<i>` and the `<strong>` tags are still applied on the page, e.g. the italic part appears italic.

For our case, my suggestion would be to strip out all html tags on the title completely (just like how the editor behaves) when displaying it on the email templates. We can use the `wp_strip_all_tags()` function.

https://developer.wordpress.org/reference/functions/wp_strip_all_tags/

**Comment by yansern** [comment]
Patch D90426-code ready for review.

**Comment by phcp** [comment]
Closed by D90426-code

**Comment by ivan-ottinger** [comment]
Related issue: https://github.com/Automattic/wp-calypso/issues/65656
