### ISSUE TITLE
Posts: viewing the posts list gives a React warning

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#6883]
To reproduce:

1. go to the posts list, i.e. calypso.localhost:3000/posts/my/<siteurl>
2. in the console, React warns that `ref` and `key` are not props

<img width="857" alt="screen shot 2016-07-19 at 11 46 46 am" src="https://cloud.githubusercontent.com/assets/23619/16945749/9fe1681c-4da6-11e6-823a-befd735cddad.png">

This is the code that triggers the warning:

```JavaScript
		const propsToCheck = [ 'ref', 'key', 'post', 'postImages', 'fullWidthPost', 'path' ];

		if ( checkPropsChange( this.props, nextProps, propsToCheck ) ) {
			return true;
		}
```

`blame` shows that this line was part of Calypso from the start (53bde8c). 

Removing `ref` and `key` from the array stops the warning, but they might still be there for a reason. Does anyone know?

**Comment by timmyc** [comment]
I can not re-create the console warnings - closing this out.
