### ISSUE TITLE
Documentation for Mailpoet

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#68830]
While we are developing the SaaS licensing, let's provide Mailpoet with a draft documentation of:

- the purchase flow
- how a billing intent is created

**Comment by rapidclue** [comment]
The documentation has been created at https://developer.wordpress.com/wordpress-com-marketplace/saas-billing-api/ and linked on https://developer.wordpress.com/wordpress-com-marketplace/.

**Comment by gavande1** [comment]
The documentation has been created at https://developer.wordpress.com/wordpress-com-marketplace/saas-billing-api/ and linked on https://developer.wordpress.com/wordpress-com-marketplace/

**Comment by cpapazoglou** [comment]
Before closing this, can we also add the billing intents endpoint to the swagger docs?

**Comment by gavande1** [comment]
The diff created for adding route to swagger docs: D90199-code
