### ISSUE TITLE
Sites Management Page: coming soon sites show a fake coming soon notice for the site thumbnail

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#68859]
We don't generate site snapshots of coming soon sites because they're inaccessible to mShots. That means most coming soon sites use this fallback thumbnail (since they probably also don't have a site icon)

<img src="https://user-images.githubusercontent.com/1500769/194964797-81596d4e-4d42-42b8-aa38-d12e6a9f6902.png" alt="Image" style="max-width: 100%;" width="439px">

The fallback thumbnail is less informative than just showing the coming soon notice. So we should just show the blue coming soon notice that appears on the site's frontend.

<img src="https://user-images.githubusercontent.com/1500769/194965684-5a8421a7-65aa-408c-9d5c-c3ea19f5199e.png" alt="Image" style="max-width: 100%;" width="796">

Since we know what the coming soon notice looks like, it's more inefficient to generate the thumbnail as an SVG. This saves us from making requests to mShots, and SVG means the "Coming Soon" message can be translated. It doesn't have to match the frontend 100% (e.g. we don't need the sign-in buttons), just give the general idea:

**Mockups**:

<img src="https://user-images.githubusercontent.com/1500769/194966137-b5b22d20-64d7-4549-8cbb-9c8f33c891fd.png" alt="Image" style="max-width: 100%;" width="455">

<img src="https://user-images.githubusercontent.com/1500769/194966151-05c3f4b4-d24a-41e4-8d45-10f54a7f1bed.png" alt="Image" style="max-width: 100%;" width="1323">

**Done is**:
- [ ] Coming soon sites have a site thumbnail that looks similar to the coming soon frontend
- [ ] Thumbnail translated into the _site's_ language (this is the language used by the frontend, not the admin UI language)
- [ ] Thumbnail switches to mShots when site is launched
- [ ] Thumbnail switches to SVG when site is set to coming soon

**Comment by mpkelly** [comment]
I am starting this now.
