### ISSUE TITLE
[Bug]: Payments Block: Button width settings have no effect.

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#68861]
### Quick summary

The width setting on the Payments Block seems to have no effect. All the other block settings (typography, colors, etc.) seem to be working correctly.

![plaVRSgM3w](https://user-images.githubusercontent.com/4550351/194969845-e286eb01-a71b-41b4-8351-50cd805b7f6d.gif)

### Steps to reproduce

1. Insert a Payments block into a post or a page.
2. Under block settings try changing the width to any of the presets.
3. Switching between presets has no effect.
4. Save and preview. The changes are not reflected in the preview either.

### What you expected to happen

I expected the button to change width according to the selected setting.

### What actually happened

The button does not react to changing the width setting at all.

### Browser

Google Chrome/Chromium

### Context

Noticed while working on a pattern featuring the Payments block.

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Found in: https://github.com/Automattic/blockpatterns/issues/278

### Reproducibility

Consistent

**Comment by iamtakashi** [comment]
I think this is one of the symptoms that's fixed when the block became Payment Button**s** block. The users won't see this problem now unless they made the content before the change.

**Comment by alaczek** [comment]
In that case I think it's ok to close this issue.
