### ISSUE TITLE
2FA Two-Step Authentication, Users not receiving SMS via SMS method

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#68867]
### Quick summary

Account Recovery queue is seeing an increased number of users who suddenly are not receiving codes via the SMS method for 2FA. When checking the status of the SMS, we see some have been delivered successfully, some have not. This also varies by country and we're still trying to see if there is any particular pattern. 

### Steps to reproduce

1. User goes to log in with a 2FA enabled (via SMS) account.
2. SMS with code is never received by user

### What you expected to happen

2FA codes sent via SMS should be reaching users

### What actually happened

We're getting many users who have not normally had account issues suddenly using AR queue to let us know that they can't log in because they don't receive SMS.

### Context

Gathering tickets where we've seen this so far:
5621430-zd (User noted SMS was working fine until a few days ago. Canadian phone number, SMS lookup shows status: undelivered)

5620944-zd (US phone number, SMS lookup shows status is undelivered)

5621084-zd (Canadian phone number, SMS lookup shows undelivered)

5621711-zd (User came into live chat to tell us they were having issues receiving SMS. Canadian number, SMS lookup shows undelivered. User had to use backup codes to get into account)

5621115-zd (US number, status is undelivered)

5619253-zd (User had to be sent single use codes. Then they turned on 2FA via app method it seems)

5618827-zd (User was having issues with 2FA SMS, so we sent single use codes. Took a few tries, but they were able to get in and looks like enabled app method of 2FA after removing SMS method.

### Workaround details

The only workaround is for users to contact us, letting us know they aren't getting SMS so we can send single use codes.

**Comment by brinbliss** [comment]
Report in 5614485-zd-woothemes regarding a Canadian phone number. SMS lookup shows "No record found."

**Comment by cuemarie** [comment]
📌 SCRUBBING
- tried setting up SMS 2fa for a non-admin test account, but the SMS delivered fine for me. SMS lookup shows `status: delivered`
- More HE discussion on the issue here, for context: p1665445217688809-slack-C02FMH4G8

📌 ACTIONS
- Due to the higher number of reports, going to push this one along anyway so we can get more eyes looking for patterns in the reports above.
- Marked as Triaged for Quality Squad review

**Comment by ha-un** [comment]
Another report: 5623561-zd-woothemes (US number, undelivered)

**Comment by kuropixel** [comment]
Another report: 5620944-zen (Canadian number, status undelivered)

**Comment by kuropixel** [comment]
Another report. 5624205-zen. (Canadian number, status undelivered)

**Comment by brinbliss** [comment]
Another report in 5624320-zd-woothemes. Canadian number, status undelivered.

**Comment by jamiepalatnik** [comment]
Another report: 5618160-zd-woothemes

Advised user to use an authenticator app instead of SMS messages as a workaround in the meantime. 

I checked the user reports we have so far and I see that most share the same error code in the SMS lookup. Investigating a resolution for this here: pMz3w-g7U-p2

Noting that 5619253-zd-woothemes had a different error than the rest on a couple SMS messages but other messages were delivered successfully. Looks like no follow-up is needed on that ticket though.

**Comment by wpshellbelle** [comment]
Another report at 5632038-zd-woothemes

**Comment by mdtanjid0** [comment]
Another one: 5626517-zd

**Comment by brinbliss** [comment]
Another report in 5632396-zd-woothemes. Canadian number, and status undelivered.

**Comment by brinbliss** [comment]
Another report in 5633724-zd-woothemes. Canadian number, and status undelivered.

**Comment by kuropixel** [comment]
Another report in 5637463-zd. Canadian number, status undelivered.

**Comment by kuropixel** [comment]
Adding more: 5638304-zd. Canadian number, status undelivered.

**Comment by kuropixel** [comment]
Another: 5634186-zd. Canadian number, status undelivered.
user shared: "I have called my cell phone provider and they said it is an issue on your end because **you are not registered in Canada to receive verified text confirmations through your provider**."

**Comment by brinbliss** [comment]
As a note, there's additional progress in pMz3w-g7U-p2#comment-102885. We can continue to report cases where a user is affected here, however, so they can be notified when SMS 2FA is restored.

**Comment by ccwalburn** [comment]
Another report here: 5640924-zen
_Notified of fix 10/19/2022_

**Comment by kuropixel** [comment]
Another report: 5640868-zen (US number, status undelivered)

**Comment by ha-un** [comment]
Another report: 5640869-zd-woothemes (US number, status undelivered)

**Comment by Robertght** [comment]
5638500-zen

**Comment by SiobhyB** [comment]
Another report in 5629922-zd-woothemes

**Comment by jamiepalatnik** [comment]
Latest update on this issue is here: pMz3w-g7U-p2#comment-102973

**Comment by jamiepalatnik** [comment]
This issue should now be resolved, so I think it would be OK to follow up with any users that requested a follow-up: pMz3w-g7U-p2#comment-102992

**Comment by jamiepalatnik** [comment]
Closing this since there are no new user reports. The issue should be resolved. If we do get any other user reports with the same error code discussed above, we can reopen and take another look.

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
