### ISSUE TITLE
Show a message in unlaunched sites when ETK plugin is disabled 

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#68870]
We want to alert users that disable the ETK plugin in an atomic site that has not been launched with a message like this: **Disabling this plugin will make your site public.**

We will show the message when the plugin is deactivated or removed but only if the site hasn't been launched.

![image](https://user-images.githubusercontent.com/1881481/194993638-2b664ce9-2211-4a2a-afa8-615d8073bab8.png)

The explanation of why the site becomes public if the ETK plugin is deactivated is in the post The default Privacy setting for sites pbxlJb-2ye-p2.

A better solution to prevent this issue is moving the code in the ETK related to the "Coming soon" privacy setting to Jetpack because there it cannot be disabled. That solution is still being discussed.

Related https://github.com/Automattic/wp-calypso/issues/52596

**Comment by miksansegundo** [comment]
The plugins page `/wp-admin/plugins.php` doesn't use React. I found a simple way to add an inline confirmation message on the click event of the link "Deactivate" using the filter `plugin_action_links_{$plugin_file}`. 

<img width="265" alt="Screen Shot 2565-10-19 at 18 36 08" src="https://user-images.githubusercontent.com/1881481/196682787-8a8bafbe-d202-45a2-92ab-703abaa74043.png">

Is it too hacky? Do you have better ideas @Automattic/ganon?   

```php
function wpcom_filter_etk_plugin_action_links( $actions ) {
  $unlaunched = get_option( 'launch-status' ) === 'unlaunched';

  if ( $unlaunched ) {
    function add_confirm( $action ) {
      $message = translate( 'Disabling this plugin will make your site public.' );
      $confirm = "confirm('$message') ? null : event.preventDefault()";

      return str_replace(
        '<a href="plugins.php?action=deactivate', 
        "<a onclick=\"$confirm\" href=\"plugins.php?action=deactivate",
        $action
      );
    }
    $actions = array_map( 'add_confirm', $actions );
  }
  
  return $actions;
}

add_filter( 'plugin_action_links_full-site-editing/full-site-editing-plugin.php', 'wpcom_filter_etk_plugin_action_links' );
```

I tested the code in an Atomic Ephemeral Site. I had to remove the part to check the launch status because these sites are not connected to wordpress.com. 

Do you know how I can test it on a real atomic site? I tried sandboxing it, but I got the Chrome error `NET::ERR_CERT_COMMON_NAME_INVALID` saying that the connection is not private (HTTPS).

**Comment by arthur791004** [comment]
> Do you know how I can test it on a real atomic site? I tried sandboxing it, but I got the Chrome error NET::ERR_CERT_COMMON_NAME_INVALID saying that the connection is not private (HTTPS).

You have to use your atomic site and install the latest plugin manually

**Comment by arthur791004** [comment]
> I found a simple way to add an inline confirmation message on the click event of the link "Deactivate" using the filter plugin_action_links_{$plugin_file}.

I think we only need to handle the `deactivate` link instead all of the actions. Otherwise, you will see confirm again when you try to activate the plugin.

I found there are 2 plugin management pages
* `/plugins/manage/<your_site>`
* `<your_site>/wp-admin/plugins.php`

I'm confused why we don't migrate to the new version...but I assume we have to support both when the user tries to deactivate the plugin.

**Comment by miksansegundo** [comment]
> I think we only need to handle the deactivate link instead all of the actions. Otherwise, you will see confirm again when you try to activate the plugin.

I'm targeting the deactivate link only because I replace `'<a href="plugins.php?action=deactivate'`

> You have to use your atomic site and install the latest plugin manually

The problem is that I cannot access my atomic site when it is sandboxed

**Comment by arthur791004** [comment]
> The problem is that I cannot access my atomic site when it is sandboxed

What do you mean by that? You cannot sandbox your atomic site. Instead, you need to zip the new ETK plugin and install it there. See "ETK and Atomic Sites" section in PCYsg-ly5-p2

**Comment by miksansegundo** [comment]
> I found there are 2 plugin management pages

I found that `/plugins/manage/<your_site>` is part of the Jetpack Cloud. It's called the Agency plugin management dashboard. See p1HpG7-gua-p2#comment-55756

Shall I create an issue in Jetpack repo?

**Comment by miksansegundo** [comment]
> You cannot sandbox your atomic site.

If I cannot sandbox my atomic site, how can I test the code in my sandbox?

Where should I put this code?
```php
function wpcom_filter_etk_plugin_action_links( $actions ) {
  $unlaunched = get_option( 'launch-status' ) === 'unlaunched';

  if ( $unlaunched ) {
    function add_confirm( $action ) {
      $message = translate( 'Disabling this plugin will make your site public.' );
      $confirm = "confirm('$message') ? null : event.preventDefault()";

      return str_replace(
        '<a href="plugins.php?action=deactivate', 
        "<a onclick=\"$confirm\" href=\"plugins.php?action=deactivate",
        $action
      );
    }
    $actions = array_map( 'add_confirm', $actions );
  }
  
  return $actions;
}

add_filter( 'plugin_action_links_full-site-editing/full-site-editing-plugin.php', 'wpcom_filter_etk_plugin_action_links' );
```

**Comment by arthur791004** [comment]
You have to add the code to the ETK plugin, build the new one, zip and upload it to your atomic site. Just the same as how you test the new version of ETK plugin on atomic site before shipping. See "ETK and Atomic Sites" section in PCYsg-ly5-p2
