### ISSUE TITLE
Toggle underline on links when hovered using Styles

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#68878]
### What

When hovering on links, underlines are shown, and there's no way to remove them.

In Styles, we have the option to change the color of links when hovered. 

Interaction: 37322041-hc

### Why

Convenient for users to turn underline on or off on links without the use of CSS

**Comment by zachspears** [comment]
Hello @edwinho89, it looks like this is a duplicate request of [this ticket](https://github.com/Automattic/wp-calypso/issues/62279), so I am closing this one for now. I have added your interaction to the other ticket for transparency.
