### ISSUE TITLE
Use page.html (aka default template) as the template for PA v1

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#68880]
# Description

See p1665464379515479/1665152933.113869-slack-CRWCHQGUB
See pbxlJb-2AA-p2#comment-1861 

While we wait for Clean Slate, we can use Blank Canvas for the CfT or even ship feature with the expectation Clean Slate will soon be ready!

# Tasks
- update the onboarding mechanism to use `page.html` instead of `header-and-footer.html`

# Related

**Comment by arthur791004** [comment]
Close it in favor of p1665477921376149/1665152933.113869-slack-CRWCHQGUB
