### ISSUE TITLE
Plans: Compare screen runs too wide in German

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#6889]
Because of the long translation in German (and possibly other languages) the first column runs too wide for the current number of 4 plans.

![screen shot 2016-07-19 at 14 14 26](https://cloud.githubusercontent.com/assets/203408/16949710/8b22f5b0-4dbc-11e6-8df5-52cb8b940875.png)

This was mainly introduced by a `white-space: nowrap;` in b8e42934

**Comment by lancewillett** [comment]
The plans compare screens have been redesigned significantly now, and I can no longer repeat this bug.

Here's a visual record (both in /plans logged in — and in /start for signup flow). Testing with Mac-n-Chrome.

![screen shot 2016-10-18 at 10 42 26](https://cloud.githubusercontent.com/assets/66797/19489359/cc3164a6-951f-11e6-9687-6baacc92e16d.png)
![screen shot 2016-10-18 at 10 42 29](https://cloud.githubusercontent.com/assets/66797/19489357/cc2d9010-951f-11e6-857b-c2dd6f13db2a.png)
![screen shot 2016-10-18 at 10 43 08](https://cloud.githubusercontent.com/assets/66797/19489358/cc2e9de8-951f-11e6-9ccc-a7b8f050472f.png)
![screen shot 2016-10-18 at 10 43 10](https://cloud.githubusercontent.com/assets/66797/19489356/cc2c066e-951f-11e6-84f8-15756bda96c1.png)
