### ISSUE TITLE
Marketplace search: investigate and fix search tracks events

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#68901]
Based on the thread here: pdgAPm-vA-p2#comment-531

The two tracks events are:
- `calypso_plugins_search_results_show`: fired when the first page of results are loaded
- `calypso_plugins_search_results_page`: fired on each subsequent page of results loaded

We should investigate why `calypso_plugins_search_results_show` is not being fired, and if `calypso_plugins_search_results_page` is being fired more times than intended.

**Comment by paulopmt1** [comment]
> calypso_plugins_search_results_page should be that _show should only be called once per search

Even if we receive 0 results from our search, we have at least four calls of `calypso_plugins_search_results_page` and it keeps increasing without changing anything on the page:

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/1044309/196196748-ecea16be-a2c5-4c90-9cee-838c664151e5.png">

**Comment by lsl** [comment]
Drop off happens on Sept 8. 

![Screenshot 2022-10-20 at 15-49-18 Tracks Trends - calypso_plugins_search_results_show - Metrimattic](https://user-images.githubusercontent.com/811776/196858982-932e4034-0d13-416d-8bcd-29a20a8feb20.png)

I'm guessing it's something to do with the Jetpack search swap out on that day https://github.com/Automattic/wp-calypso/pull/67510.

> Even if we receive 0 results from our search, we have at least four calls of calypso_plugins_search_results_page and it keeps increasing without changing anything on the page:

This sounds like the infinite search issue we saw a while back. It's leveraging page height or something and if there are no results it just keeps firing searches off. (not sure if that's what is happening here yet)

**Comment by lsl** [comment]
Pagination response looks missing or something.

Really need to move these over to typescript. :shrug:

**Comment by lsl** [comment]
Sort of fix here https://github.com/Automattic/wp-calypso/pull/69274

One issue with this "fix" is that `calypso_plugins_search_results_show` won't always fire on secondary page loads.

Search "test one" => see `_show`
Search "test two" => see `_show` 
Search "test one" => see `_show`
Scroll down to the next page load for "test one"
Search "test two" => see `_show`
Search "test one" => won't see `_show`

The cached result is coming back in full with all previously scrolled to pages, since the fix is leveraging this to figure out what page we're on it thinks we're no longer on page one and so doesn't fire the `_show` event off again (when it should)

**Comment by lsl** [comment]
There should be the selected page_handle coming through in data ([this ESResponse](https://github.com/Automattic/wp-calypso/blob/56ade194b65ed293731c704bb2c7e1a731a1d369/client/data/marketplace/use-es-query.ts#L131) thing) but I don't see it in the response we receive. 

It is coming through in the network response and being added to the individual pages but we're not seeing it returned as the "selected page". Figuring out how to get that selected/current page into the pagination response and using that to figure out whether we're on page 1 or not is probably the proper fix here.

Impl: probably replace the `pagination.page` value with something like `pagination.pageone`

Let's merge https://github.com/Automattic/wp-calypso/pull/69274 as is so we get some data coming through and figure out how to fix cached search result events later.
