### ISSUE TITLE
SiteSwitcher: display total sites (visible + hidden) count on `<AllSites />`

### ISSUE THREAD

**Issue by sejas** [Automattic/wp-calypso#68919]
### Details

This issue is a follow-up from: https://github.com/Automattic/wp-calypso/pull/68785#pullrequestreview-1134966302

There is a mismatch between the total number of visible sites shown in the `<AllSites />` component and the actual total number of sites (visible + hidden) shown in the Site Selector sidebar.

<img width="257" alt="Screenshot 2022-10-11 at 16 49 01" src="https://user-images.githubusercontent.com/779993/195139343-4d2b5cb8-be3e-4b3b-ac66-3cf366b5acee.png">

Suggested diff: 

```diff
diff --git a/client/blocks/all-sites/index.jsx b/client/blocks/all-sites/index.jsx
index acea602b40..1e21f3cda6 100644
--- a/client/blocks/all-sites/index.jsx
+++ b/client/blocks/all-sites/index.jsx
@@ -5,7 +5,6 @@ import PropTypes from 'prop-types';
 import { Component } from 'react';
 import { connect } from 'react-redux';
 import Count from 'calypso/components/count';
-import { getCurrentUserVisibleSiteCount } from 'calypso/state/current-user/selectors';
 import getSites from 'calypso/state/selectors/get-sites';
 
 import './style.scss';
@@ -78,11 +77,13 @@ class AllSites extends Component {
 // don't instantiate function in `connect`
 const isSiteVisible = ( { visible = true } ) => visible;
 
-export default connect( ( state ) => {
-	const visibleSites = getSites( state )?.filter( isSiteVisible );
-	const userSitesCount = getCurrentUserVisibleSiteCount( state );
+export default connect( ( state, props ) => {
+	const sites = getSites( state, { shouldSort: false } ).filter( Boolean );
+	const userSitesCount = props.count ?? sites.length;
 
 	return {
-		count: config.isEnabled( 'realtime-site-count' ) ? visibleSites.length : userSitesCount,
+		count: config.isEnabled( 'realtime-site-count' )
+			? sites.filter( isSiteVisible ).length
+			: userSitesCount,
 	};
 } )( localize( AllSites ) );

```

This diff modifies the props in a way that gives:
- the `count` value if it's provided as a prop;
- the visible sites count in case we're browsing Jetpack Cloud;
- the total sites (visible + hidden) count to match the behavior on the Site Selector.

### Checklist

Done is:
- [ ] The number of sites in `<AllSites />` is the total (visible + hidden), not only visible.

### Related

https://github.com/Automattic/wp-calypso/pull/68785

**Comment by sejas** [comment]
@zaguiini I think this is not currently needed.

<img width="257" alt="Screenshot 2022-10-11 at 16 49 01" src="https://user-images.githubusercontent.com/779993/195139343-4d2b5cb8-be3e-4b3b-ac66-3cf366b5acee.png">


If a user clicks on `View Stats for all sites`, then the page only shows the stats for the visible sites, not for all the sites, so the number is indeed correct.

If we show the total number of sites, I would expect to see the stats for all my sites, not only the visible ones. The same reasoning applies to pages, posts etc. Not only the stats page.

We can add the task of showing the stats for all the sites to this issue. I just want to confirm that's the best path to take:

1. Showing the total number of sites and showing only visible sites on the stats page.
   - Probably `/sites`  page will replace the stats page in the short term.
2. Showing the total number of sites and updating the stats page to show all the sites too, which can result in a poor experience if the user has hundreds of sites.

As an alternative solution, we could change the copy to: `View stats for my visible sites`

**Comment by zaguiini** [comment]
That's a fair call @sejas 👍 I would advise against changing the copy since it will increase the complexity for the user. Let's just display the visible sites and make the count only for visible sites. Hidden sites are only shown in the site switcher and in search, so let's not stress about it and make the user need to remind one more thing.

**Comment by sejas** [comment]
Cool, then I'll close this issue until we remove the stats page.

**Comment by danielbachhuber** [comment]
Cross-linking some feedback on this discrepancy: https://github.com/Automattic/wp-calypso/issues/68455#issuecomment-1280867027
