### ISSUE TITLE
Theme: Launch Masu

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#68929]
### Details

The Masu free theme needs the following:

### Checklist

- [x] Move Masu to WP.com
- [x] Set up a [demo site](https://masudemo.wordpress.com/)
- [x] Theme showcase draft](https://theme.wordpress.com/wp-admin/post.php?post=41000&action=edit)
- [x] Headstart annotation (guide: paYKcK-1Pt-p2) (Strand ID `142550`)
- [x] GlotPress project (guide: paYKcK-1Pt-p2)
- [x] Launch a free theme (guide: paYKcK-1Pt-p2)

**Comment by markbiek** [comment]
Launched!

**Comment by iamtakashi** [comment]
That was quick! Thank you so much.
