### ISSUE TITLE
Marketplace: Browse all left-padding

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#68941]
The new subheadings are running up a bit close to the browse all link in some mobile resolutions. Need to add a padding/space between them.

- [ ] Add space between subtitle/titles and the browse all links.

![Screenshot(38)](https://user-images.githubusercontent.com/811776/195250798-c0430d2f-8b89-4485-9fc9-9bca9a88bde4.png)

**Comment by and1can** [comment]
Hi @cpapazoglou , 
I have got a PR for this that is ready for review. If the assignment is available, please assign this to me.

**Comment by and1can** [comment]
Hi @WBerredo , 

This is more of a house-keeping question. Since my fix is merged, this ticket should be closed. I'm not sure if there is currently a way to automate this (I don't have write privileges and cannot assign a label to auto-close this ticket).

**Comment by cpapazoglou** [comment]
Hey @and1can, thanks for your fix. There is an automation closing the respective issue when you use the `Fixes` keyword instead of `Related to` in the PR description.
