### ISSUE TITLE
Marketplace: Add 6 replacement plugins for collections

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#68942]
We had to drop a few of the proposed plugins as they weren't yet available in the marketplace.

- [ ] Work with design to come up with 6 replacements for the `monetization` and `business` collections. (3 each)
- [ ] Add the 6 new plugins to the [`useCollections` array](https://github.com/Automattic/wp-calypso/blob/ba0b00eaa561a6ebf7b507133cc82b389b357ab9/client/my-sites/plugins/plugins-browser/collection-list-view/index.tsx#L21)

Current plugins:
![Screenshot 2022-10-13 at 15-45-19 Plugins — WordPress com](https://user-images.githubusercontent.com/811776/195503760-fe7e94d5-5550-4373-b724-51775e8123dd.png)
![Screenshot 2022-10-13 at 15-45-13 Plugins — WordPress com](https://user-images.githubusercontent.com/811776/195503766-acc2f05e-c864-4c26-804b-2d119daa8a7e.png)
(from https://wordpress.com/plugins)

**Comment by allilevine** [comment]
@sethmclellana8c suggested a pop-up plugin for site monetization. Just capturing that here.

**Comment by lsl** [comment]
Pulling together some best guesses based on searches and some :thinking: 

Local business:
- https://wordpress.org/plugins/zero-bs-crm/ - "Lead generation through to invoicing and billing"
- https://wordpress.org/plugins/strong-testimonials/ - "Publish your testimonials and reviews"
- https://wordpress.org/plugins/all-in-one-wp-migration/ - "Move websites between hosts with ease"

Supercharge / Monetization
- https://wordpress.org/plugins/optinmonster/ - "Monetize your website traffic" (popups, moved from ecom collection)
- https://wordpress.org/plugins/easy-digital-downloads/ - "Create and sell digital products"
- https://wordpress.org/plugins/elementor/ - "Drag and drop website editor"

Ecom collection (to replace optin monster)
- https://wordpress.org/plugins/woocommerce-paypal-payments/ - "Accept PayPal payments"

Provided some rough copy short descriptions to get us started. Drop a comment with any changes you'd like to see.

Seeing some tracks search terms I think these would be three good collections to also create - and maybe rotate them in?

- SEO and analytics: 
- Backup and migrations
- Site builders and customizations

**Comment by paulopmt1** [comment]
Thanks for making the list @lsl, [did a few copy changes](https://github.com/Automattic/wp-calypso/pull/69088), please let me know if you see we should roll back them:

- `Lead generation through to invoicing and billing` to `Lead generation and marketing automation`
- `Publish your testimonials and reviews` to `Easily collect and display testimonials`
- `Drag and drop website editor` to `Drag and drop page builder`

**Comment by lsl** [comment]
Reads much better, thank you!
