### ISSUE TITLE
Marketplace Collections: Jetpack sites

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#68948]
With the new collection sections introduced with #68884 / #67987 we're now showing paid plugins to Jetpack users which we previously avoided.

- [x] Determine if we should hide paid plugins or even entire collections from Jetpack users
- [x] Determine if for Jetpack sites we should hide the first section
- [x] Action as required

/plugins currently looks like this for Jetpack users:

![Screenshot 2022-10-12 at 17-28-13 Plugins ‹ Ganon Test Site — WordPress com](https://user-images.githubusercontent.com/811776/195266476-a3321c3f-9566-4cb5-92b7-8a7e31afbebd.png)

(made an issue for the banner https://github.com/Automattic/wp-calypso/issues/68937)

@cpapazoglou / @vinimotaa for design/product input.

**Comment by DustyReagan** [comment]
> Determine if we should hide paid plugins or even entire collections from Jetpack users

I feel like we should hide all plugin collections to Jetpack sites, until we get more free plugins in the collections to shuffle into the space taken up by paid plugins. At that point we can re-evaluate if we'd like to show collections (with paid plugins filtered out) to Jetpack sites, and where they should be placed (such as the case with the first monetization collection appearing above dev favorites).

I created a PR to do the above here: https://github.com/Automattic/wp-calypso/pull/68997
