### ISSUE TITLE
Marketplace: Collections design review

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#68946]
https://github.com/Automattic/wp-calypso/pull/68884 Introduced the new collections defined by https://github.com/Automattic/wp-calypso/issues/67987. Since [we were able to re-use](https://github.com/Automattic/wp-calypso/issues/67979#issuecomment-1274119356) an existing compact design version of PluginsBrowserList, some design spec's were missed.

- [x] Review the specified designs in https://github.com/Automattic/wp-calypso/issues/67987
- [x] List any remaining changes required here
- [ ] Fix the remaining changes required

Figma f84fqtCG4pCnCh2Hq0But5-fi

**Comment by candy02058912** [comment]
### Margins/Paddings
- [x] 20px -> 16px
![margin](https://user-images.githubusercontent.com/6586048/195566340-6311a56f-c7ad-4f57-b9eb-be6198aa4087.png)

- [x] 20px -> 24px
![margin](https://user-images.githubusercontent.com/6586048/195567107-0fad4fdf-c311-4068-a9b3-c218edebd3c1.png)


### Font size
- [x] 24px -> 26px
![font](https://user-images.githubusercontent.com/6586048/195564004-67c5b569-bc26-4950-9049-ba29b88d5856.png)

@vinimotaa this is a typography exception, should we revert back to 24px, which is `$font-title-medium`

### Other

- [x] Browse all (tracked in #69031)
![wpcom](https://user-images.githubusercontent.com/6586048/195569177-3c359c59-b600-43d7-8680-fa6c6ba563c0.png)

**Comment by lupus2k** [comment]
@vinimotaa should we update the font size to 26px in "Get started with plugins" too?

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/402286/195631686-f80cf106-1b3b-458d-9a3c-b8992c2e0cef.png">

**Comment by paulopmt1** [comment]
> @vinimotaa should we update the font size to 26px in "Get started with plugins" too?
> 
> <img alt="image" width="1112" src="https://user-images.githubusercontent.com/402286/195631686-f80cf106-1b3b-458d-9a3c-b8992c2e0cef.png">

Good catch @lupus2k! The spaces were [fixed here](https://github.com/Automattic/wp-calypso/pull/69040) and the font-size, I created a question [for Vini here](https://github.com/Automattic/wp-calypso/pull/69032#pullrequestreview-1141486643). Ideally, we should be able to reuse the sizes we already have on Calypso. Let's see if we can do it :)
