### ISSUE TITLE
Marketplace Collections: Plugin data loading investigation

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#68943]
In https://github.com/Automattic/wp-calypso/pull/68884 I made some assumptions about the way we want to store this data plugin data for collections. Collections are currently [hardcoded](https://github.com/Automattic/wp-calypso/blob/ba0b00eaa561a6ebf7b507133cc82b389b357ab9/client/my-sites/plugins/plugins-browser/collection-list-view/index.tsx#L21) along with all their plugin information (Names, descriptions, icons, availability etc)

While I think we do want to keep the list of plugin slugs hardcoded and the collection title/descriptions along side them, I suspect we want to load plugin titles, descriptions and icons via the api (`usePlugins`).

There is going to be some cross over in this issue with the other issue we have open about whether collections are categories or not. See https://github.com/Automattic/wp-calypso/issues/68945 for more on that. 

If possible, lets try limit the scope of this issue to just loading plugin info directly via usePlugins in order to only store a list of plugin slugs as a collection.

Acceptance:

- [ ] Confirm with design if the figma detail (like plugin descriptions / icons) is expected to stay the same or if we can use a truncated plugin short description from the endpoint 

If we need to keep descriptions as is:
- [ ] Investigate whether it's worth it or decide if we should create a new field in a woocommerce.com product field and store it there

If we can use truncated descriptions:

- [ ] Investigate whether we can specify a list of plugins per collection and offload name, icon and descriptions to the api endpoint.

**Comment by DustyReagan** [comment]
I started looking at this, but haven't gotten far. Can we use [`usePlugins`](https://github.com/Automattic/wp-calypso/blob/5db172218bbdfbe6cd74591f201c68eb1db70fa9/client/my-sites/plugins/use-plugins/index.ts#L54) to pull a list of plugins by `slug`?

**Comment by lsl** [comment]
Can possibly do multiple single plugin slug queries but you'd need to check it doesn't feel laggy or cause problems for logged out ssr views.

Before getting too far I'd like to get design confirmation about what collections are and where the data should be fetched from. Mostly for ideas about scale and how large / how many collections we want to have in future. If it stays a small list maybe hardcoding isn't so bad.

**Comment by lsl** [comment]
@vinimotaa are you able to expand on what you envision for collections from a technical perspective? What are they, what makes them different from categories?

**Comment by lsl** [comment]
Update: I think we're circling on just calling these categories with a short set of specified preview plugins. See https://github.com/Automattic/wp-calypso/issues/68945#issuecomment-1278269225 for more info.
