### ISSUE TITLE
Add 'Templates' and/or 'Template Parts' to the Appearance menu to allow deep linking to those sections of the Site Editor

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#68955]
### What

Could we add some additional items to the Appearance admin menu?

* 'Templates' which would link to /wp-admin/site-editor.php?postType=wp_template
* 'Template Parts' which would link to /wp-admin/site-editor.php?postType=wp_template_part

### Why

This could be helpful to users in 2 ways...

1. It makes it clear how to access those areas (for users who *know* they wish to go straight to editing a template)
2. Having those pathways clearly labeled as an entry point to editing templates and parts correctly sets the context and mindset for users who enter the Site Editor that way

**Comment by zachspears** [comment]
This is a great idea and would also help users differentiate between them as separate kinds of editing. I think the menu, while just being useful to locate these pages, would also provide a lot of benefit for the intuitive understanding of FSE.

**Comment by autumnfjeld** [comment]
I'm going to add this to this issue to WordPress.com Web Engineering Roadmapping https://github.com/orgs/Automattic/projects/472 "Idea Inbox"

**Comment by ebinnion** [comment]
We chose to put this in the icebox for now on WPCOM to see how the home navigation helps with the pattern assembler project.

**Comment by jordesign** [comment]
Closing this as the new Browse mode in Gutenberg reveals these items much more easily.
