### ISSUE TITLE
Launchpad: Upgrade domain badge

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#68969]
When users select a free domain during the onboarding, we will display a Customize badge in the domain input, allowing them to go back to the domain’s step and change it if desired.

I’m not sure how easy it is to bring the users back to the Domains Step page at the moment, but alternatively, we could link them to wordpress.com/plans for the time being

https://user-images.githubusercontent.com/7931304/195321803-94eb0042-91ac-4536-8b10-3feb1bbc13d6.mov

Design: 9wpoYJrMlYKAKUYvVBMN74-fi-1088%3A18997

**Comment by Addison-Stavlo** [comment]
While the domains screen shown in the video is being refactored and redesigned from setup to stepper frameworks, it probably makes sense to make this upgrade badge link to calypso domains page in the meantime.

**Comment by agrullon95** [comment]
Closed with #69086.
Thank you @Sharpirate!
