### ISSUE TITLE
Launchpad: Copy to Clipboard

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#68967]
For launched sites in which the URL is available (for now, Newsletter only), we will provide the possibility to copy the link into the clipboard from the domain input. This would allow users to quickly see their site live or share link.

**Logic:**

When hovering over the URL, the copy icon appears and clicking it automatically copies it to the clipboard. The tooltip disappears after a few seconds. 

**Video Prototype:**

https://user-images.githubusercontent.com/7931304/195320885-7a4e5e0e-9a0f-49f8-95d2-85cec79addf2.mov

Other Scenarios:

- Extreme long domain
- Free domain + Upgrade badge (when implemented)

![Image](https://user-images.githubusercontent.com/7931304/195321330-967be58a-a9a4-484e-b5c4-c20bde29d0a2.jpg)
![Image](https://user-images.githubusercontent.com/7931304/195321331-d254966a-58ca-4ca0-9b0a-aa65f268b8c9.jpg)

Figma Designs: 9wpoYJrMlYKAKUYvVBMN74-fi-1086%3A16682

**Comment by jeyip** [comment]
@nuriapenya Really love the onHover behavior of the copy to clipboard icon.

One note though -- in the 2 factor authentication backup codes feature, I found an existing example of copying to the clipboard, but with a different icon and different tooltip styling. Wondering if it's okay to continue with these conventions and reuse the icon and tooltip?

https://wordpress.com/me/security/two-step

<img width="620" alt="Screen Shot 2022-10-13 at 12 31 42 PM" src="https://user-images.githubusercontent.com/5414230/195692969-6ea89af2-ab55-49ef-83e0-31f35743e3de.png">

**Comment by Addison-Stavlo** [comment]
> One note though -- in the 2 factor authentication backup codes feature, I found an existing example of copying to the clipboard, but with a different icon and different tooltip styling. Wondering if it's okay to continue with these conventions and reuse the icon and tooltip?

@nuriapenya is afk for the next couple weeks. The tooltip seems like it could be helpful, but I would try to go with the icon from the design if possible. If there are other blockers to that we can use this existing one as a fallback and follow up later once she is back from AFK. (side note rant - the new standard copy icon shown in the designs always confuses me when I run across it with other options LOL, i do personally prefer the older one but that newer one seems to be taking over everywhere)

**Comment by Addison-Stavlo** [comment]
@jeyip another thing to consider in this issue/PR is the situation where we are showing a custom domain in that field, but the custom domain has not yet been set up and the link would essentially lead to an inactive or not fully established (insecure) URL. Depending on various things including the type of domain, this can take anywhere from a few seconds to tens of minutes (or more?).

I spoke to @nuriapenya some about this on Tuesday before she left for AFK, and it sounds like we want to both:
* a) prevent showing the copy functionality until the domain is set up. It seems there are a couple helpful properties on the domains object to tell us both when the custom domain is set as primary (`primary_domain`), as well as when it is fully secure (`ssl_status = 'active'`) - id imagine we want both conditions to be true). 
* b) show a notification message underneath the domains preview noting that it is in the process of being set up. That would look something like the following but with a different copy:

![image](https://user-images.githubusercontent.com/28742426/195856835-5bf0b5d9-7ec5-4793-a62c-e15b408b761f.png)

Something along the lines of "We are in the process of setting up your new domain! It may take a few minutes before this is ready."

We can punt `b` to a separate follow up issue as well if you think it makes more sense to keep the PRs for the copy functionality and notification separate. Thoughts?

**Comment by jeyip** [comment]
> We can punt b to a separate follow up issue as well if you think it makes more sense to keep the PRs for the copy functionality and notification separate.

I prefer to work with smaller PRs, so I'll handle `b` in a follow-up like you're suggesting :)

**Comment by jeyip** [comment]
> The tooltip seems like it could be helpful, but I would try to go with the icon from the design if possible. 

I checked and the asset for the icon in Figma is just two rectangles 😆 I'm not sure if she'd like to refine it more. Implementing the new icon ourselves won't a problem when we have the SVG, but for now, I'll stick with the official `Gridicon` until @nuriapenya is back.

**Comment by jeyip** [comment]
@Addison-Stavlo also curious how you feel about this behavior for the extremely long domain. I have the clipboard button shift url text over, as opposed to allocating a set amount of space for the button so that the url text _doesn't_ shift when the button appears.

![2022-10-16 12 20 53](https://user-images.githubusercontent.com/5414230/196053935-1993d2e4-f100-4648-a9e3-78fb76a51366.gif)

**Comment by jeyip** [comment]
A few remaining follow-up tasks for the clipboard button

- show a notification message underneath the domains preview noting that it is in the process of being set up
- Replace old clipboard icon with new one specified in [figma designs](https://github.com/Automattic/wp-calypso/pull/9wpoYJrMlYKAKUYvVBMN74-fi-1086%3A16682)
- unit tests
- consider how to make the button keyboard accessible

**Comment by jeyip** [comment]
Closing this issue since the large majority of features have been implemented. There is a follow-up issue regarding clipboard button keyboard focus that I'll create, but it's lower priority to handle
