### ISSUE TITLE
Launchpad: Email Validation message

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#68961]
A side-effect of newsletters starting launched is a requirement for email verification to happen before allowing posts to be published. For that, I'm proposing to revise two areas:

1. Add a notification banner on top of the Launchpad to remind users on validating email
2. Re-design the text and styling of the already existing message in the editor

![Image](https://user-images.githubusercontent.com/7931304/195296967-859e3b72-484a-4d37-a393-adae7270b077.jpg)
![Image](https://user-images.githubusercontent.com/7931304/195296966-73f4ae27-3447-41d9-919a-aaa0c54cc78a.jpg)

Figma: 9wpoYJrMlYKAKUYvVBMN74-fi-1166%3A18181

**Comment by Addison-Stavlo** [comment]
I think the last thing for this issue is to update the editor's version to be a 'warning' as opposed to an 'error' (this should update the color from red to yellow) - some discussion from p2 - paYE8P-29S-p2#comment-1801

cc @Sharpirate
