### ISSUE TITLE
Launchpad: Main task should be a CTA

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#68970]
We will turn the main task in the Launchpad into a primary button.

CTA:

- Newsletter: `Write your first post` and always be active as the site is live.
- LIB: `Launch your site` and will be inactive until users complete `Add links` task.

![Image](https://user-images.githubusercontent.com/7931304/195320210-9d404b40-9878-49e9-9249-1f6a697d5ecf.jpg)
![Image](https://user-images.githubusercontent.com/7931304/195320209-4a042d53-10f5-47ad-a92c-16b7c2eb18c6.jpg)

Design Newsletter: https://www.figma.com/file/9wpoYJrMlYKAKUYvVBMN74/Launchpad?node-id=985%3A16220
Design LiB: https://www.figma.com/file/9wpoYJrMlYKAKUYvVBMN74/Launchpad?node-id=985%3A16100

**Comment by agrullon95** [comment]
Issue resolved with changes: https://github.com/Automattic/wp-calypso/pull/69096
