### ISSUE TITLE
Plans: free plan vertical alignment issues

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#6897]
![](https://cloudup.com/couAyWhPYIb+)

#### Steps to reproduce
1. Starting at URL: wordpress.com/start/plans
2. Note vertical alignment in free option is different than the 3 paid plans
3. Also note that the `upgrade now` cta for the premium plan sits lower than the ctas for personal & business

cc @apeatling since you fixed up previous alignment issues here

**Comment by rralian** [comment]
This has been addressed as part of #6895
