### ISSUE TITLE
Update page header

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#68974]
Part of the modernization project (p1HpG7-igQ-p2).

# Development

Blocked by #69041, which needs to be in place before this can be implemented.

# Design

We'll want to update the page header to match Calypso's new pattern. This new header is already present in:

- Add-ons: https://wordpress.com/add-ons/
- Domain: https://wordpress.com/domains/manage/
- WooCommerce: https://wordpress.com/woocommerce-installation/
- Plugins: https://wordpress.com/plugins/
- And probably other sections too.

What I don't think is covered in the current implementation is the supporting tabbed menu and extra links on the right side. Check this Dotcom system Figma file for all the variations explored already: eqlepL7MHifK8Bgr1OWqLr-fi-1310%3A1681&viewport=260%2C383%2C0.65

Below you'll find the Before/After comparison as well as specs:

![Image](https://user-images.githubusercontent.com/390760/195375639-88a4f649-8609-4b73-b87d-eab2168a42db.png)

![Image](https://user-images.githubusercontent.com/390760/195375655-ceb6d0fd-99bf-4ff8-97ae-8ee36d89696a.png)

![Image](https://user-images.githubusercontent.com/390760/195401820-8ed1fe75-9bf4-4fc0-9555-3129d744ae45.png)

**Comment by dognose24** [comment]
Hi @keoshi, I am figuring out if we are trying to make all existing `fixed` page headers support the proposed style change as per the design below. (`eqlepL7MHifK8Bgr1OWqLr-fi-1310%3A1681`)

<img width="997" alt="截圖 2022-11-08 上午3 56 01" src="https://user-images.githubusercontent.com/6869813/200403159-6d6b5795-9fea-4516-bb84-4fadef5bf88a.png">

**Comment by keoshi** [comment]
@dognose24 Hey there! This header style has been worked on by the Dotcom Design team, we merely reused the Figma component to support our own use cases. I don't know how much of this has been ported over to the code component, or how flexible it is in terms of adapting to our particular scenarios, so I'd rely on you all to let us know if we should extend the existing component or create a new one if that gets us to shipping faster and then later converge both.

I realize the above is totally a non-answer (sorry), but what do you think?

**Comment by dognose24** [comment]
Hey @keoshi! If we are not planning to fix the page header for some convenient interactions with the `tabbed menu` and `extra links`, we could keep the static headers for Stats. We can just refactor the page header as a `component in Stats` instead of using the same component as those existing pages. 👍🏼

**Comment by jsnmoon** [comment]
@danjjohnson: This feature is expected to release in the next 24 hours.

**Comment by jsnmoon** [comment]
@dognose24: Is this task finished?

**Comment by keoshi** [comment]
I just spotted a missing background color in the Ads page header:

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/390760/203083032-0c2e3212-ce11-42c6-afaa-40bcf4dcd899.png">

Notice how only the nav is set against a white background and not the entire header.

Would be great if we could fix before closing the issue for good. Thank you!

**Comment by jsnmoon** [comment]
@Automattic/red: Could someone tackle the Ads page header issue Filipe mentioned above? Thanks!

**Comment by dognose24** [comment]
> Notice how only the nav is set against a white background and not the entire header.

This issue has been fixed in https://github.com/Automattic/wp-calypso/pull/70253. cc @keoshi @jsnmoon

**Comment by dognose24** [comment]
> Is this task finished?

@keoshi Is the current extra links section on the right side keeping the same rather than the `ellipsis panel` in a smaller viewport good enough? Since the tab menu on the `width <= 480px` viewport is using the original menu, the `Followers` info still has enough space to display on the `width > 480px` devices.

<img width="594" alt="截圖 2022-11-25 上午10 49 46" src="https://user-images.githubusercontent.com/6869813/203891572-6182dc36-fbb7-492b-9e35-d89c405e5f5d.png">

<img width="577" alt="截圖 2022-11-25 上午10 58 19" src="https://user-images.githubusercontent.com/6869813/203891923-0e31dbbc-c092-406d-9ba8-b4b314d5f6c8.png">

**Comment by keoshi** [comment]
@dognose24 We got some encouragement to show the Followers count as much as possible since it's a big metric for our new newsletter site-type segment.

Could we add the Followers link to the dropdown menu like so?

<img width="390" alt="image" src="https://user-images.githubusercontent.com/390760/203946298-c04fddb5-8c93-4d91-a087-9128fef76057.png">

**Comment by dognose24** [comment]
> Could we add the Followers link to the dropdown menu like so?

@keoshi Looks like a plan! I have addressed it [in this PR](https://github.com/Automattic/wp-calypso/pull/70446).
