### ISSUE TITLE
Create layout grid

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#68975]
# Development

- [x] Apply grid layout to Traffics page.
(#69907)
- [ ] ~Apply grid layout to the Insights page.~ 
Note: I don't think it's appropriate to apply a grid to the insights page at this time -- we need to migrate other components on that page before we can consider this. -@jsnmoon

# Design

Part of the modernization project (p1HpG7-igQ-p2).

To make sure our layout is scalable, expectable, and replicable across multiple sections, we'll want to lay down a layout grid where the various blocks and module can fall into.

**Whether this needs to be implemented as suggested or simply as discrete rows as shown in the examples is totally up to you.** :)

A layout grid is centered on the content area and consists of:

- Columns: the main and largest element of a grid; it’s where all other components (titles, text, buttons, icons, etc.) will be aligned to.
- Gutters: the empty space that exists between columns.
- Margins: the empty space around the grouping of columns + gutters.

We're proposing the following:

- **Desktop**
  - Columns: 12 total at 80px wide.
  - Gutters: 24px wide.
  - Margins: 24px wide.
- **Tablet**
  - Columns: 8 total at 90px wide.
  - Gutters: 24px wide.
  - Margins: 16px wide.
- **Mobile**
  - Columns: 4 total at 64px wide.
  - Gutters: 24px wide.
  - Margins: 16px wide.

Below you'll find the Before/After comparison, specs, and examples:

![Image](https://user-images.githubusercontent.com/390760/195336205-1c7594d1-15b0-4f38-a85e-3c9846ab8cca.png)

![Image](https://user-images.githubusercontent.com/390760/195336225-c93907b8-b485-4871-8e9d-09fd9cd39665.png)

![Image](https://user-images.githubusercontent.com/390760/195338804-8160ec7f-eee0-4071-ab97-aaba97988b5f.png)

**Comment by jsnmoon** [comment]
Looks great!
