### ISSUE TITLE
READER - Remove follow/following links

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#68982]
## Description

There are a handful of places where we need to remove the Follow/Following links:

- [x] Search results screen
- [x] Recommended posts (Keep icon, remove label)
- [x] My likes & lists pages

### Search results screen

![CleanShot 2022-10-12 at 09 37 38](https://user-images.githubusercontent.com/5634774/195357665-aaec7488-fbc1-4f13-8923-b54c0b1fad28.png)

### Recommended posts

![CleanShot 2022-10-12 at 09 39 02](https://user-images.githubusercontent.com/5634774/195358032-44758c81-c510-4de5-9957-a65e393970f7.png)

### My likes & lists pages

![CleanShot 2022-10-12 at 09 40 27](https://user-images.githubusercontent.com/5634774/195358292-dc8a3e9b-b58c-4ac2-9d0c-ee25355d89f2.png)

**Comment by eoigal** [comment]
Search and like follow/following were removed with https://github.com/Automattic/wp-calypso/pull/68890
