### ISSUE TITLE
Update modules styling

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#68981]
Part of the modernization project (p1HpG7-igQ-p2).

We're proposing a visual refresh of each module and we're summarizing all changes here.

This change also includes adding a percentage bar to create a nice and simple visual representation of the distribution of data available on each module. **Q: do we want to break this into its own task?**

Below you'll find the Before/After comparison as well as specs:

![Image](https://user-images.githubusercontent.com/390760/195563767-97e9f2ed-f888-4092-a4f6-645831429f49.png)

![Image](https://user-images.githubusercontent.com/390760/196402269-cda42bd9-439b-40aa-b0a9-2fa68f5ee07f.png)

![Image](https://user-images.githubusercontent.com/390760/195563816-2c29ee8c-ae7b-42ca-89cb-2b9a57a3dc8a.png)

**Comment by jsnmoon** [comment]
> This change also includes adding a percentage bar to create a nice and simple visual representation of the distribution of data available on each module. **Q: do we want to break this into its own task?**

Yes, I think having a separate task for the bar chart background makes a lot of sense.

**Comment by keoshi** [comment]
Makes total sense. I'll break the specs apart and add images to the card "_Add horizontal bar chart background for stats modules_".

**Comment by keoshi** [comment]
@jsnmoon I've updated all instances to reflect the intermediary state without percentage bars.

**Comment by jsnmoon** [comment]
@keoshi Thank you!

**Comment by jsnmoon** [comment]
@grzegorz-cp: Can we consider this issue resolved?

**Comment by grzegorz-cp** [comment]
Yes, let's mark it as done.
