### ISSUE TITLE
READER - Full post featured image needs to be full-width

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#68994]
## Description

- [x]  When viewing a full post, the featured images should be 100% of the width (720px), not 474px:

![CleanShot 2022-10-13 at 10 55 04](https://user-images.githubusercontent.com/5634774/195632012-66325756-df90-4961-a463-4412f5f715a5.png)

See: `/read/feeds/108002187/posts/4313195239`

- [x] Recommended post & search screen images that are more tall than they are wide are not filling out the whole container:

![image](https://user-images.githubusercontent.com/5634774/195632375-9835ebf8-711d-40da-91de-e6e5488f1a96.png)

- [x] When an image with a caption is rendered, it includes whitespace/padding for the caption text. We need to add a wrapper to the img to allow us to use the inset box-shadow style.
- [x] Nice to have - add aspect ratio classes to the wrapper so we can style the img depending on its img aspect ratio

See: `/read/search`

**Comment by davemart-in** [comment]
My thought was that we could compare the width to the height of an image pre-rendering and if the width is equal to the height (square) or less than 3:2 aspect ratio that we could apply a CSS class that would allow us to adjust accordingly (targeting max-width, vs. max-height).

![Image](https://user-images.githubusercontent.com/5634774/195886962-7d1c4693-d79b-4c9b-9874-87581e336af3.png)

**Comment by eoigal** [comment]
Fixed the recommended post featured images not expanding in https://github.com/Automattic/wp-calypso/pull/69105
