### ISSUE TITLE
Editor / Press This bookmarklet: Pull images from page for Add Media

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#690]
In the wp-admin bookmarklet, when you click on the Add Media button, the images from the page you're sharing appear:

![04a5f116-d213-11e4-8950-ea539dd1b86d](https://cloud.githubusercontent.com/assets/52152/11382147/1976d96c-92b5-11e5-9128-90101dc81f4b.png)

In the bookmarklet for the Calypso editor, adding an image does not pull this info.

**Comment by designsimply** [comment]
Moved to https://github.com/Automattic/wp-calypso/issues/1552
