### ISSUE TITLE
Munchies theme line height is too small

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#69004]
### Quick summary

Line Height in Munchies theme makes text blend together.

Line height issue: https://imgur.com/cSxqYwA
With theme template _line-height_ commented out: https://imgur.com/m8wQWFs
(Had trouble adding images directly, so uploaded them to imgur instead)

### Steps to reproduce

1. Using the Munchies theme create a new page. 
2. Add paragraph block and preview page.

### What you expected to happen

The text should display legibly. 

### What actually happened

The text looks squished together. 

### Context

User report: 37389002-hc

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Yes, Munchies theme

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The following CSS can be used:

/* Fix line height */
body {
    line-height: 1 !important;
}

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on P2 - N/A
- Tested on Simple -  Could Not Replicate 
- Tested on AT - Could Not Replicate 
- Tested on Self-hosted -  N/A
- Replicable on Core - N/A

📌 FINDINGS/SCREENSHOTS/VIDEO
The user who reported this has the line height set to 0.6 in global styles in the site editor

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
