### ISSUE TITLE
[Bug]: Add Jetpack Server Credentials Showing on Atomic Site's Backup Page

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#69006]
### Quick summary

If the site is Atomic, we need not to show the **Add your server credentials banner** or the message **Enter your server credentials to enable one-click restores from our backups** on the Jetpack backups page, since we manage those credentials and there are no user-facing ways to edit or see those. 

<img width="1639" alt="Screen Shot 2022-10-12 at 2 46 51 PM" src="https://user-images.githubusercontent.com/29527450/195446236-420b4794-9057-478a-8bee-9a59431b1e8c.png">

It seems this was introduced and related to the PR: https://github.com/Automattic/wp-calypso/pull/68552 cc @Initsogar 

It looks like the condition `const isAtomic = hasCredentials && 'dynamic-ssh' === protocol;` was used to check if a site is Atomic on this page https://github.com/Automattic/wp-calypso/blob/trunk/client/components/advanced-credentials/index.tsx , and it might be helpful to include the same condition, in this case, to prevent the message from displaying on Atomic sites.

### Steps to reproduce

1. Have an Atomic Site at WordPress.com with available backups.
3. To break credentials for backups, open the Atomic Site's VPMC and change the site's URL to an invalid URL (it just needs to differ from the actual Atomic site's address which will break the credentials for backups).
5. On WordPress.com, Navigate to My Site > Atomic Site > Jetpack > Backups 

### What you expected to happen

I expect a message that says contact support or anything other than asking a user to add server credentials since we manage them on Atomic, and the user cannot add them or delete them. 

### What actually happened

You see the banner at the top that says: 

> Add your server credentials Enter your SSH, SFTP or FTP credentials to enable one-click site restores and faster backups.

Click on any of the Action +, and you'll see the message:

> Enter your server credentials to enable one-click restores from your backups.

### Context

p1665603763936529-slack-C03TY6J1A
p1665595347233759-slack-C03TY6J1A 

### Other notes

This was observed when a user's domain was propagating, but it could also show anytime that credentials fail to test, like restoring a site after it was reverted. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Fix credentials.

**Comment by Initsogar** [comment]
Thanks for the issue report @ash1eygrace! I'm working on it.

**Comment by dcoleonline** [comment]
Experienced in 37360425-hc also. We toggled the primary and staging domains to get it to work.

**Comment by essleeung** [comment]
Experienced in 29223218-hc. Also toggled the staging domain.

**Comment by mxhassani** [comment]
Another case here: 3068963-hc . p1665765981976679-slack-C03TY6J1A

**Comment by ash1eygrace** [comment]
The issue here was to remove the **Add your server credentials banner** at the top of the page, and **Enter your server credentials to enable one-click restores from our backups** when the user clicks Action +, which are no longer showing, and was fixed yesterday in #69010. I'll close this issue since it was for the banners asking for server credentials, which has been solved. 

If the button is not accessible, the troubleshooting checklist will help to fix that, which includes changing the Primary domain to staging; if staging isn't working, it could be a Jetpack sync issue.
