### ISSUE TITLE
Pattern Assembler in logged-in Theme Showcase: Switching to blank canvas leads to PA flow

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#69014]
#65575 
# Description
This work in on pause until we have details from design (main issue being how to properly handle theme switch flow).  However we will move forward with adding the PA flow as an onboarding flow originating from the logged-out showcase.

Referring to p1665578592503809/1665152933.113869-slack-CRWCHQGUB, we need to make the pattern assembler a core part of the experience whe picking  the new  Blank Canvas theme.

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/5665959/196872063-dfb924aa-d6d2-4ea4-825c-972e4816df07.png">

**Here are the entry points**
* Switch to the blank canvas theme from the theme showcase
* Click the “Use this Theme” button from the [blank canvas demo site](https://blankcanvasblocksdemo.wordpress.com)

# Design
* Do we use the existing BC square? 
* Or use similar design as in the DP?
*
<img width="253" alt="image" src="https://user-images.githubusercontent.com/5665959/196872324-14a5124d-4c7f-4418-9d43-4e4a36e6eb39.png">
vs
<img width="533" alt="image" src="https://user-images.githubusercontent.com/5665959/196872768-7c0578d1-36bb-4995-9a92-4714bfab9ef7.png">

# Implementation Details

- [ ] When the existing site (with another theme) already has a Home template, after completing the PA flow, the Home template must contains the correct, selected patterns.

**Comment by fushar** [comment]
Do we load the original homepage patterns (from the previous theme) to the Pattern Assembler screen, or do we always start with an empty header/section/footer? Especially when the user selects "Preserve my homepage content" when switching to Blank Canvas.

@Automattic/ganon

**Comment by autumnfjeld** [comment]
This isn't required for launch of the PA MVP, but we should ship it soon after.   See Matias confirmation of that: p1665735522252499/1665730226.315779-slack-CRWCHQGUB

The PA flow from Theme Showcase  will need a mini-CfT of its own to make sure we catch any bugs or unexpected consequences.

**Comment by autumnfjeld** [comment]
> Do we load the original homepage patterns (from the previous theme) to the Pattern Assembler screen, or do we always start with an empty header/section/footer? Especially when the user selects "Preserve my homepage content" when switching to Blank Canvas.

* Should be clear to user they are really starting with a blank canvas (doesn't have to be like with other theme switch)
* Start with empty header/section/footer
* I think we offer different options, don't preserve homepage

**Comment by autumnfjeld** [comment]
I think we would only offer the option on the right.  Would just be a modal, or notice that old homepage is in Pages -> Drafts.    Or if the prior theme doesn't have WPpages, only templates, then maybe different copy is needed.
<img width="969" alt="image" src="https://user-images.githubusercontent.com/5665959/196873363-eab0d27b-c4f3-4ce2-8fd5-8c2c50c366db.png">

**Comment by fushar** [comment]
I added the following A/C in the description:

- [ ] When the existing site (with another theme) already has a Home template, after completing the PA flow, the Home template must contains the correct, selected patterns.

See the original discussion: https://github.com/Automattic/wp-calypso/pull/69241#pullrequestreview-1148665502

**Comment by miksansegundo** [comment]
@autumnfjeld shall we close this for now? We are going to hide the BC in the theme showcase. https://github.com/Automattic/wp-calypso/issues/69168#issuecomment-1285118962

**Comment by autumnfjeld** [comment]
@miksansegundo  We will only hide it until this work done. :). This should stay in the backlog. 

As soon as we have the PA flow working in theme showcase, then we will un-hide the BC in the theme showcase.

This work is not part of PA MVP, but we can start on it once CfT is out.
