### ISSUE TITLE
Create a home page template on the fly after the user finishes PA flow

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#69015]
Referring to p1665497100719849/1665152933.113869-slack-CRWCHQGUB, the new blank canvas won't have a built-in `home.html` and we need to create it on the fly

**Comment by fushar** [comment]
Is this basically your PR? 😄 https://github.com/Automattic/wp-calypso/pull/68473 (just need to modify the template name)

@Automattic/ganon

**Comment by arthur791004** [comment]
Yes but we also need to modify the main content. Additionally, we might need to update the `show_on_front` option as you mentioned before

**Comment by fushar** [comment]
Okay, let me take this issue :)

**Comment by fushar** [comment]
Landed!
