### ISSUE TITLE
Tailored cases: Pretty URLs for intro step

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#69028]
### What

See p1665560677476059-slack-C02NQ4HMJKV

The request is to use a pretty URL for the first step of the tailored case flows so that the URL looks more like:

http://wordpress.com/setup/newsletter

Instead of 

http://wordpress.com/setup?flow=newsletter

### Why

This is useful when sharing the URL manually.

**Comment by alshakero** [comment]
Closing as done in https://github.com/Automattic/wp-calypso/pull/69561
