### ISSUE TITLE
Marketplace Collections: Browse all / Browse collections button

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#69031]
Related to #68945, but this one is focused on the button itself since this branched out from #68946.

![Image](https://user-images.githubusercontent.com/6586048/195625365-502a08d5-51f2-4fc5-93bf-794e6a11f57d.png)

Acceptance criteria:

- [ ] Browse Collection: Show the number of plugins in that particular collection
- [ ] Both: Add the `>` part

**Comment by lsl** [comment]
Thanks for splitting out to a new issue, we just removed that last week, I think the design / figma is out of date.

**Comment by candy02058912** [comment]
Oops didn't catch that. Thanks for closing the issue.
