### ISSUE TITLE
Stats: Add horizontal bar chart background for stats modules

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#69044]
Part of the modernization project (p1HpG7-igQ-p2). Perhaps we could do this using dynamic styling?

# Development
- [x] Create a horizontal bar chart data table component
(#69117 by @grzegorz-cp)
- [x] Integrate the new component in the Traffic page
  - #69545
  - #69726 
  - #69812 
  - #69841
  - #69915
- [x] Release to production

# Designs

![Image](https://user-images.githubusercontent.com/390760/195564823-4a15a308-39bd-4bf0-b910-659587a24a74.png)

![Image](https://user-images.githubusercontent.com/390760/195564854-b979f2d5-101d-4965-b041-6e10f8cc2398.png)

![Image](https://user-images.githubusercontent.com/4044428/194180449-fab2a70a-0968-4f3f-85b2-79d3bd403b78.png)

**Comment by jsnmoon** [comment]
@grzegorz-cp: I updated this issue with two subtasks to better align with the plan you mentioned over Slack 👌

**Comment by jsnmoon** [comment]
@danjjohnson: We'll start adding this feature to the Stats' traffic page soon behind a feature flag. Looping you in here for awareness and customer rollout guidance 👍

**Comment by keoshi** [comment]
Moving a couple of items from https://github.com/Automattic/wp-calypso/pull/69907 to this issue:

On the smallest resolutions, we should adjust the card styling:

- [x] Set `border-radius` to `0px`.
- [x]  Set `border-left` and `border-right` to `0px` so the card is flush with the window and only has border on the top and bottom.

Before | After
--|--
<img width="330" alt="image" src="https://user-images.githubusercontent.com/390760/201691552-bd43add1-7bc5-407f-adb2-116b54fa28b5.png"> | <img width="330" alt="image" src="https://user-images.githubusercontent.com/390760/201691961-ee49d140-6aef-4798-9dd2-b379d5bef27b.png">

**Comment by jsnmoon** [comment]
> On the smallest resolutions, we should adjust the card styling:
>     * Set `border-radius` to `0px`.
>     * Set `border-left` and `border-right` to `0px` so the card is flush with the window and only has border on the top and bottom. 
> 
> (@keoshi)

This has been addressed in #70020 via 8108e0dccdb8b4f7665a5bd742b621cade94dae6 😁

**Comment by keoshi** [comment]
Beautiful, thank you!
