### ISSUE TITLE
Update main chart area styling

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#69041]
Part of the modernization project (p1HpG7-igQ-p2).

# Development

This blocks #68974.

- [x] Move the chart off of the card (remove borders and background color).
- [x] Round the top corners of each bar.
- [x] Visually separate the tabs from the chart.
- [x] Integrate the time period label and arrow controls above the chart.
- [x] Use core WordPress icons.
- [x] Use the primary color from the user's theme.
- [x] Restore nested bars for visitors for the Traffic chart.

Related PRs:
- #69529
- #69661
- #69743
- #69746
- #69810

# Design

Proposal to update the chart area:

- [ ] Full-bleed chart. No borders, no background color.
- [ ] Title corresponds to the selected time range.
- [ ] Move time periods to the left.
- [ ] Move arrows to the right.
- [ ] Primary colors change with the user theme. We've double-checked all user color schemes for contrast/a12y issues and found no blockers.
- [ ] Round top corners of each bar.
- [ ] New styling for the tabbed options.
- [ ] Update icons to WP Core ones.
- Interaction design to remain the same. Bar animation is good when switching between time frames, etc.

Below you'll find the Before/After comparison as well as specs:

![Image](https://user-images.githubusercontent.com/390760/195591297-137b3537-a135-4a13-bf21-57ad5410d134.png)

![Image](https://user-images.githubusercontent.com/390760/195592787-6061db71-d0a3-4720-8e4e-6f69bfbcda7c.png)

**Comment by jsnmoon** [comment]
A note for contributors: Please ship changes for this issue incrementally in multiple PRs.

**Comment by dognose24** [comment]
I am going to try tackling this for the next few days.

**Comment by dognose24** [comment]
I have noticed a few edge case styles need definition as the following: cc @jeffgolenski @keoshi 

- How do we handle the `last query date` when navigating to the last bar chart? The actual behavior increases the section height, which looks wobbly, especially at the chart header position. However, keeping the original behavior is also a working option. But the last query date styles may need some adjustment.
- Is the data period `title` that may break the line appropriate?

<img width="1090" alt="header-date" src="https://user-images.githubusercontent.com/6869813/198357925-6a0cf1e5-d312-4eb4-8fc5-11504bd7ee69.png">

- If we set the `font-size` of the X-axis label to `14px`, the label text will break the line when switching to the `Day` or `Week` period options.

<img width="1114" alt="x-label" src="https://user-images.githubusercontent.com/6869813/198358988-bedac763-6958-481f-9f69-8d5f68f569df.png">

**Comment by jeffgolenski** [comment]
@dognose24 Can we abbreviate all the months when there are date ranges selected like the examples you have above? Also we can remove the words "Stats for" as it's pretty evident those are stats displaying on the stats, insights, ads, or store pages.

**Comment by keoshi** [comment]
Ditto to everything @jeffgolenski said above!

> If we set the `font-size` of the X-axis label to `14px`, the label text will break the line when switching to the `Day` or `Week` period options.

Hm, good catch. I wonder if this is already happening in other languages. I'd be tempted to _not_ change anything else, as it might break other areas that use the same components, and address this separately if we can.

**Comment by dognose24** [comment]
> Can we abbreviate all the months when there are date ranges selected like the examples you have above? Also we can remove the words "Stats for" as it's pretty evident those are stats displaying on the stats, insights, ads, or store pages.

Yes @jeffgolenski! Sounds like a plan!

> I'd be tempted to not change anything else, as it might break other areas that use the same components

Agree with you! @keoshi

**Comment by dognose24** [comment]
I will use a follow-up PR to tackle [period header content and alignment](https://github.com/Automattic/wp-calypso/issues/69602). cc @jeffgolenski @keoshi

**Comment by dognose24** [comment]
<img width="1145" alt="截圖 2022-11-04 下午3 17 43" src="https://user-images.githubusercontent.com/6869813/199915050-f7528659-d2da-463f-81b9-e8fb8d61d010.png">

The primary color from user themes works fine.

**Comment by jsnmoon** [comment]
@danjjohnson: This feature is expected to release in the next 24 hours.
