### ISSUE TITLE
Fix props in wpcom_pattern_inserted

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69052]
# Description

Context: p1665560719680619/1665560715.828549-slack-CRWCHQGUB

Fix props in wpcom_pattern_inserted that are firing null.  Do some sanity checking on this event to make sure it is recording what we think it is recording.

![Image](https://user-images.githubusercontent.com/5665959/195749233-00a46c9d-2285-4e58-a95e-6c44ab9a5be5.png)

![Image](https://user-images.githubusercontent.com/5665959/195751541-19169a5c-cf75-4ef5-9749-8583b6158e49.png)

![Image](https://user-images.githubusercontent.com/5665959/195751717-fafbb6c8-554a-41f2-9bec-69015ccdcb19.png)

#  Tasks
* Examine [getEditorType](https://github.com/Automattic/wp-calypso/blob/9e60b9b61b9a0534ffa7440c2bf867205719a6a0/apps/wpcom-block-editor/src/wpcom/features/utils.js), is it returning the correct editor?   Is there a better way to determine editor type? 
* Fix props in wpcom_pattern_inserted that are firing null 
  * editor_type
  * template_part_id
* Note: for some props `null` might make sense, let's discuss that, since it has implications in how data is interpreted in track

# Dev Tasks

- [x] https://github.com/Automattic/wp-calypso/pull/69232

# Testing

**Comment by bangank36** [comment]
`document.querySelector( '#edit-site-editor' )` always return null, even in FSE, so I think we should find another way to determine the current editor

**Comment by arthur791004** [comment]
Checked, and here is the type and id mapping

| Type | ID |
| - | - |
| Page, Post | editor |
| Site | site-editor |
| Widget | widgets-editor |
| Customize | customize-controls |

**Comment by bangank36** [comment]
@arthur791004 how can we access Widget and Customize editor

**Comment by arthur791004** [comment]
> Customize editor

You can access the Customize editor from "Appearance > Customize".

> Widget editor

When you switch to old themes like "Twenty Twenty", you will see it from "Appearance > Widget"

**Comment by arthur791004** [comment]
I'll create a PR to fix this issue 🙂

**Comment by arthur791004** [comment]
Checked the `editor_type` and it's fixed from the trends below

![image](https://user-images.githubusercontent.com/13596067/196890273-08b7dd72-880a-442c-a1d6-19053b5ed6aa.png)

I'll continue to monitor the `template_part_id` to see whether the `null` value is decreased or not. But it might not be easy to check whether it makes sense or not because people probably don't insert patterns to the template part block when they're editing the template.

**Comment by arthur791004** [comment]
Close as it's completed
