### ISSUE TITLE
Jetpack Sites: Visual issue on list of sites a plugin is installed

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#6905]
When on WordPress.com and viewing a plugin via a Jetpack Connected site, There's a visual issue when you have a plugin installed on a multi-site network. 

The line-height of "network management disabled" seemingly needs some tweaks, and the enable button text is cut off / ellipsis'd.  

Example: 
![screen shot 2016-07-19 at 4 09 16 pm](https://cloud.githubusercontent.com/assets/214813/16964618/7202f888-4dca-11e6-96c7-a02ef34c909e.png)

To replicate:
1) Have a plugin like VaultPress installed on a multisite network.
2) Visit the plugin page on a jetpack connected site: https://wordpress.com/plugins/vaultpress

cc @MichaelArestad since you're the last person I knew who worked on this!

**Comment by rickybanister** [comment]
@jeffgolenski I'd love to help you fix this as an intro-to-calypso PR. Let's confirm it's still an issue and try to tackle quickly early next week.

**Comment by jeffgolenski** [comment]
@rickybanister Phenomenal idea man!

**Comment by jeffgolenski** [comment]
Can confirm it's still a present issue.

**Comment by MichaelArestad** [comment]
@jeffgolenski now get in there! (happy to help)

**Comment by jeffgolenski** [comment]
@MichaelArestad  @rickybanister going to dive in early next week methinks. want to clear a few more things off the plate first!

**Comment by jeffgolenski** [comment]
The issue here is the icon with the class name `all-sites-icon`  We just need to make the top and bottom margin 0 to stop it from throwing off the text alignment.
