### ISSUE TITLE
Subscriber form: Show a disclaimer even if the customer types manual list of emails

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#69060]
See: p2y3YZ-5IC-p2#comment-13985

**Comment by saygunnyc** [comment]
The image below carries all propositions for paid and free users. Figma: HSljkKnYECEEegL3DqP2xC-fi-6601%3A139584

<img width="1805" alt="Allcases" src="https://user-images.githubusercontent.com/78876323/196200484-c404cdaa-d837-4da3-b5a8-5f051d4726d3.png">

**The proposal is to:**
- Tweak the disclaimer by removing "on your list" so it doesn't only refer to the email list but also the emails entered on input fields – _"By clicking “Continue,” you represent that you’ve obtained the appropriate consent to email each person.  Learn more"_
- Display the disclaimer even if the user just filled in an email using input fields.

<img width="1512" alt="Screen Shot 2022-10-17 at 5 15 47 PM" src="https://user-images.githubusercontent.com/78876323/196201244-030fd6f1-4659-452f-ae0c-a4a278a70030.png">


**100 subscriber limit copy proposal**
While this is not directly related to this issue, if we are to keep the 100-subscriber limit on free users, I'd like to propose that we tweak the import copy to indicate the limit to users, so it's less frustrating to them. – _"Or bring your mailing list up to 100 emails from other newsletter services by uploading a CSV file."_

<img width="1523" alt="Screen Shot 2022-10-17 at 5 19 37 PM" src="https://user-images.githubusercontent.com/78876323/196201744-bda3a34a-0c53-4bb3-abb0-be2dbad18315.png">


Lemme know your thoughts.

**Comment by bogiii** [comment]
@saygunnyc, I like your proposals, and I'll start working on them.
