### ISSUE TITLE
Dev Tools: Support changing 'Dashboard Color Scheme' from `<AccountSettingsHelper />`

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#69084]
Building off #69026, it would be nice if a developer could also change their 'Dashboard Color Scheme' from `<AccountSettingsHelper />`.

The existing 'Dashboard Color Scheme' UI might not fit well, so we may want to produce a simplified version. Given this is an internal tool, it doesn't need to be fancy.

**Done is:**
* [ ] It's possible for a developer to change their 'Dashboard Color Scheme' from `<AccountSettingsHelper />`.
* [ ] When they change their 'Dashboard Color Scheme', the setting persists between page refresh.

**Comment by mpkelly** [comment]
Gonna start this now.
