### ISSUE TITLE
FSE: Theme default Block Patterns appear empty in site editor

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#69099]
### Quick summary

Theme **Twenty Twenty-Two**'s default header template parts `Header (Dark, small)` and `Header (Dark, large)` are not showing the hatchery block pattern in the editor, but are displaying them on the live site. 

Instead, the site editor just shows an empty `Pattern` block.

### Steps to reproduce

1. Activate any TT2 theme on a test site
2. Set your homepage to display latest posts, so that your front page uses the `Home` template
3. Open the Site Editor > Home template
4. By default, the Home template uses the `Header (Dark, small)` template part. 

### What you expected to happen

The block pattern's "The Hatchery" content and bird image should appear in the editor, like it does on the live site. 

### What actually happened

The `Pattern` block is empty

![Markup on 2022-10-14 at 14:29:29](https://user-images.githubusercontent.com/27249804/195948100-4c56395e-9b7e-4eab-9099-539f6c712a8d.png)

### Context

Came up while helping a customer using the TT2 (Pink) theme. Slack: p1665781210165779-slack-C03TY6J1A

Replicated on AT and Simple using TT2 (Pink) and TT2. Additional comparisons: 

***Editor***

https://user-images.githubusercontent.com/27249804/195948187-6a08baad-25fe-4ee5-b286-b766593c77f6.mp4

***Live Site***

https://user-images.githubusercontent.com/27249804/195948601-1f67ac14-f26a-4d8c-afea-c30dca4bc9c7.mp4

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Twenty Twenty-Two

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

If the user wants the Hatchery content gone (to match the editor), they have to remove the invisible Pattern block:

![Markup on 2022-10-14 at 14:42:10](https://user-images.githubusercontent.com/27249804/195948379-a96f7f6a-49d3-4795-bd1f-ae4631cb17c6.png)

If they want it visible, they have to trust that it's there on the live site

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Could Not Replicate
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this on my simple and AT test sites, but not self-hosted.
- I had trouble replicating this consistently on my AT site. When I first activated the theme, it showed the content as a Header and Image block, and then it displayed as expected:

<img width="1041" alt="TT2" src="https://user-images.githubusercontent.com/30788962/197027023-e259b633-ac23-4d14-b834-bc4c204504a0.png">

I navigated away and when I checked again it was replaced by an empty Pattern block showing the issue from this report. But when I switched themes again to try to recreate this switch to the Pattern block, I was not able to. It seems the issue only occurs when the demo content is loaded from the Pattern block.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
👋 Me again - just noticed `Blank Canvas` doing the same thing with a default block pattern designed to display comments, I believe. While I don't expect we should see *much* in the way of comments in the editor, this is pretty confusing, and I can imagine it's very easy for folks to delete that empty-looking content.

Free Simple site, **Blank Canvas**

**Editor**

![Markup on 2022-10-21 at 21:07:35](https://user-images.githubusercontent.com/27249804/197318425-b16b802a-82dc-49f5-a3b1-a7d13d357cbd.png)

**Live Site**

<img width="1189" alt="Screen Shot 2022-10-21 at 9 07 54 PM" src="https://user-images.githubusercontent.com/27249804/197318433-9c5e64d3-4d5e-47fe-8f59-169e219ad86e.png">

📌 Actions
- updated the title as this doesn't just seem like a TT2 issue after all

**Comment by fushar** [comment]
Skimmed the issue. I think this might have something to do with bad Headstart default content. @Automattic/lego can we investigate this as part of the year-end maintenance?

**Comment by arthur791004** [comment]
@cuemarie 👋 Does this issue still exist? When I activate the TT2 theme on my site and go to the site editor, I see the pattern blocks instead of nothing.

![image](https://user-images.githubusercontent.com/13596067/208015989-2a575e0d-2ea6-4689-a7ca-74870973146c.png)

**Comment by fushar** [comment]
I also could not reproduce the issue. I tested on Simple, Atomic, and Jetpack sites. Tested using regular TT2 and TT2 Pink.

Maybe the issue has been resolved sometime between October and now.

Closing this issue for now, but feel free to reopen when this issue occurs again 😄
