### ISSUE TITLE
Error during installation : node-gyp doesn't install correctly

### ISSUE THREAD

**Issue by Wodric** [Automattic/wp-calypso#691]
Hi, 

I'm trying to install for several hours, I got some issues I solved by myself but this one seems to be a bit harder. 
I try to install this on my Linux mint 17.2 with node js version v5.1.0 and npm version 3.3.12 . 

But during my make install I got error on node-gyp as you can see on attach file.
I saw that python version must be a 2.7.X to install node-gyp I got the 2.7.6 one in my path.

Do you have any idea?

[npm-debug_log.txt](https://github.com/Automattic/wp-calypso/files/43278/npm-debug_log.txt)

**Comment by ajiksip** [comment]
no problem, I got same issue, but it run well on my local machine (Ubuntu Trusty, nodejs v0.10.40, npm v1.4.28)

try `make run` again after installation..

**Comment by sirbrillig** [comment]
> error contextify@0.1.15 install: `node-gyp rebuild`

The error is during the build for [contextify](https://github.com/brianmcd/contextify), which has had [problems in the past](https://github.com/brianmcd/contextify/issues/180), although the latest version supposedly fixed those issues. 

While this is researched, one possibility is to just avoid contextify. With node > 4 it's possible to upgrade the `jsdom` dependency in `package.json` to the latest release, which no longer uses contextify. We can't do that in the project yet as for the moment we still support node 0.x.

**Comment by Wodric** [comment]
Hi, 
Tks for answer, it run goods with node 0.X.
