### ISSUE TITLE
Add a Support Link to the Block Description for the Comments Block

### ISSUE THREAD

**Issue by sharonlaker19** [Automattic/wp-calypso#69108]
### What

This is a follow-up to https://github.com/Automattic/wp-calypso/issues/62284, https://github.com/Automattic/wp-calypso/issues/56091, and https://github.com/Automattic/wp-calypso/issues/67293 to add the new documentation link to the Comments block:

- [ ] Comments Block https://wordpress.com/support/full-site-editing/theme-blocks/comments-block/

cc @arcangelini

### Why

This will help WordPress.com users easily discover our comprehensive resources on how to use each block in the editor. With these support docs, users can learn about blocks more quickly, figure out the settings themselves, and reduce their likelihood of contacting support for basic editing tasks.

### How

Around 70 blocks have a Learn More link to a support doc, such as this example:

![image](https://user-images.githubusercontent.com/71630911/196014923-138169f6-9b02-4bd2-9177-9b193474bf65.png)

Let's add the above link to the Comments blocks:

![comments block](https://user-images.githubusercontent.com/71630911/196014990-3c6f7b5d-f982-429b-9dae-bfadc87a6e9f.jpg)

**Comment by escapemanuele** [comment]
Opened a PR for this: https://github.com/Automattic/wp-calypso/pull/70033
