### ISSUE TITLE
Marketplace: Add plugins category page links to /install-plugins/ lohp

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#69112]
We need to cross-link into to the logged out plugins pages from WordPress.com logged out home pages (lohp).

Let's start by adding category page links from the [`/install-plugins` page](https://wordpress.com/install-plugins/):

![Screenshot(45)](https://user-images.githubusercontent.com/811776/196072937-31cdfda1-922f-4987-a8d7-5635d8870ef3.png)

Acceptance:
- [ ] Figure out what categories to link to for each heading + list them here (e.g. "Essential SEO" => [`/plugins/browse/seo`](https://wordpress.com/plugins/browse/seo))
- [ ] Add new links to the logged out page

**Comment by lsl** [comment]
Related https://github.com/Automattic/martech/issues/1000

Slack context  p1665972619226399-slack-CFFF01Q4V

**Comment by cpapazoglou** [comment]
Category pages are now indexed - not in good ranking though, I had to be very explicit with the search term.



![Image](https://user-images.githubusercontent.com/12430020/211546966-9cc05f16-d25e-40b2-bdd4-2599c7baaebc.png)
