### ISSUE TITLE
Move reusable components to @automatic/components

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#69115]
Ganon has created components that can be useful for other teams/projects. We can move these components to `@automatic/components` with the proper docs:

- ThemePreview
- Others?

**Comment by fushar** [comment]
Good idea. Related: pdKhl6-1hu-p2

**Comment by autumnfjeld** [comment]
@fushar @miksansegundo  Should we move this to Ready to Dev and flesh out details for this issue?

**Comment by taipeicoder** [comment]
Closing this as team Lego has been mindful when it comes to this. See:

- #73634
- #71265
