### ISSUE TITLE
Task: Update designs for theme page banner

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#69124]
### Details

We want to update the styles for the upgrade bar we show on theme demo sites.

Discussion about the direction: p9Jlb4-5gS-p2#comment-6040
Figma: HrozjSkGvZzQYg1DDZpXiu-fi-55%3A856
Related back-end change: D88784-code

### Checklist

- [x] New styles are applied for theme demo sites on WordPress.com Simple
- [ ] New styles are applied for theme demo sites on WordPress.com Atomic

**Comment by valterlorran** [comment]
We are addressing this issue here: D96134-code
