### ISSUE TITLE
Jetpack checkout refers to refund window for "non-domain" products

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#69142]
### Quick summary

When you check out for Jetpack following https://github.com/Automattic/wp-calypso/pull/68093, the terms of service at the bottom make a reference to the refund window for "non-domain" products:

![jetpack-checkout](https://user-images.githubusercontent.com/235183/196259038-d664271d-b694-4a95-a671-91ad24c3a8f7.png)

This is maybe a bit confusing since you can't buy a domain on a Jetpack site.

### Steps to reproduce

Go to https://cloud.jetpack.com/pricing and put a product in your shopping cart.

### What you expected to happen

The checkout screen probably shouldn't reference "non-domain" products since all Jetpack products meet that criteria.

### What actually happened

The text from WordPress.com (which references "non-domain" products) carried over to Jetpack checkout too.

### Reproducibility

Consistent

**Comment by michaeldcain** [comment]
This looks like it was cleaned up in the recent ToS refactor:

<img width="621" alt="Screenshot 2024-01-16 at 12 20 42 PM" src="https://github.com/Automattic/wp-calypso/assets/942359/41f630f6-e9e2-49e8-9524-81bd7139c2d5">
