### ISSUE TITLE
Guided Tours: organizing our selectors

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#6914]
As we move towards a framework for any Calypso developer to build tours with, organizing our selectors in a way that makes sense becomes more important. Candidate layout:

``` text
client/state/ui/guided-tours/
├── actions.js
├── reducers.js
├── config.js // makes more sense here than in `layout`
└── selectors/
    ├── index.js
        ├── findRequestedTour()
        ├── findTriggeredTour()
        ├── findEligibleTour()
        └── getGuidedTourState()
    ├── internal.js // for GT itself
        ├── getRawGuidedTourState()
        ├── getStepConfig()
        ├── getToursConfig()
        ├── getToursFromFeaturesReached()
        ├── getToursHistory()
        ├── getTourFromQuery()
        └── …
    ├── history.js | helpers.js // for GT consumers
        ├── getToursSeen()
        ├── hasJustSeenTour()
        └── …
    ├── nux.js | user.js
        ├── isNewUser()
        └── hasJustLandedInCalypso()
    ├── upgrades.js
        ├── hasJustUpgraded()
        └── hasLeftThankYouPage()
    └── …
```

Prelim decisions taken with @ehg and @lsinger:
- no need to overthink it for selectors that haven't yet been written, e.g. `upgrades.js`;
- `internal.js` could be `internal-helpers.js`;
- not set whether `find*Tour` functions belong in `index.js` or `internal-helpers.js` — they're small and high-level enough that it may be interesting to have them more visible in `index.js` so that anyone can quickly understand the GT framework's decision process;
- in the long run, we envision a separation between GT proper and a general layer for **context**, e.g. `state/ui/context`, with high-level selectors.

**Comment by lsinger** [comment]
@mcsf what are your current thoughts on this?

**Comment by mcsf** [comment]
I still think it's a worthwhile task. A bit has changed in our approach (and hence direction) since issue creation (JSX-based configs, leveraging React context), and so a few of the above probably won't apply any longer, which is fine.

I say this is something to tackle at the end of our janitorial window, and it **goes hand in hand with building documentation** for the GT framework.

**Comment by lsinger** [comment]
> something to tackle at the end of our janitorial window, and it goes hand in hand with building documentation

👍 sounds great!

**Comment by lsinger** [comment]
We'll ochestrate this with more general changes in Calypso if and when they come. Closing for now.
