### ISSUE TITLE
Writing Prompts - Figure out how to determine if user went through blogger onboarding flow

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#69155]
## Description

We plan on adding writing prompts to the Gutenberg block editor. In doing so we also want to promote this feature in a couple of spots. As part of that work, we will need to figure out how to determine if user went through blogger onboarding flow.

**Comment by roo2** [comment]
If the user went through blogger flow they will have the `site_intent` blog option set to `write`
`get_option( 'site_intent' ) === 'write'`
