### ISSUE TITLE
Add Site Editing slide to the Welcome Tour

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69156]
# Description
The  Blank Canvas Pattern Assembler onboarding flow, see pbxlJb-2ki-p2 , ends with the user landing in the Site Editor.  The Welcome Tour should be updated to have contextual information related to the Site Editor, as currently it only has content on Block Editing. This new tour will only show for the PA flow (later it could be expanded for other themes that are designed for template content editing.)

You can see the welcome tour in the context of the LIB flow (which also lands users in the Site Editor, but LIB is a much more focused simple experience. Note design ideas posed for LIB Welcome Tour https://github.com/Automattic/wp-calypso/issues/68971).

<img width="458" alt="image" src="https://user-images.githubusercontent.com/5665959/196317473-977e9f81-1d49-4d82-bf67-f4e1ed76382f.png">

----

I suggest we add a slide, which will be slide 2, that introduces the site editor and links out to docs.

Slide title: "Full Site Editing"
Slide text: "In the WordPress Full Site Editor you can edit content and update fonts and colors for every part of your site: header, footer and main section content."

What should the image be?

# Related

- #69607
- https://github.com/Automattic/wp-calypso/issues/72533
	- We better take the "Browse Mode" into consideration.

# References 

- See the comments on this post on Welcome Tour overview: pbxlJb-2rq-p2
- https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux

@Automattic/lego

**Comment by miksansegundo** [comment]
Here is a relevant video [Understanding the Page Editor vs. Site Editor](https://learn.wordpress.org/tutorial/understanding-the-page-editor-vs-site-editor/)

**Comment by autumnfjeld** [comment]
@SaxonF just shared a visual of ideas for Welcome Tour content:




![Image](https://user-images.githubusercontent.com/5665959/196863994-a8798086-ee5d-4a54-9b9b-22c2474e5aa4.png)

**Comment by autumnfjeld** [comment]
> Here is a relevant video [Understanding the Page Editor vs. Site Editor](https://learn.wordpress.org/tutorial/understanding-the-page-editor-vs-site-editor/)

We can’t use this video because it instructs users to edit content in the Page/Post editor and layout in the FSE.   That doesn’t match up with the PA project where all content is edited in FSE.

**Comment by autumnfjeld** [comment]
Referencing discussion with Saxon: p1666244076252449-slack-CRWCHQGUB

**Comment by autumnfjeld** [comment]
Image should be abstract (maybe not real UI, which changes).
Gif would be better than video (autoplay).

**Comment by arthur791004** [comment]
I think [Intro to the Site Editor and Template Editor](https://learn.wordpress.org/tutorial/intro-to-the-site-editor-and-template-editor/) is also a great video for learning!

**Comment by autumnfjeld** [comment]
@fushar Could you break this up into two issues, e.g. two shippable pieces of work? Or just reword the issue description to make it clear it is two parts.

Part 1
* Technical foundations to conditionally show a customized tour that shows in FSE (while showing the existing Tour in the Post & Page editor, where functionality remains same in those cases)
* Update slide 1 as specified in the description above

Part 2
* Update the other two slides 
  * a new slide for FSE
  * updating the "Edit your site" slide 

Thank you :)

**Comment by fushar** [comment]
> @fushar Could you break this up into two issues, e.g. two shippable pieces of work?

@autumnfjeld I split this issue into the following two tasks instead:

- Updating slide 1 and slide 3 for Site Editor (see: #69607)
- Adding a new slide for FSE (this very issue, as it already has the discussions)

**Comment by fushar** [comment]
@autumnfjeld Could you confirm here whether the new slide is shown for the Site Editor only if the site came from the PA flow, or for the Site Editor regardless of the flow?

**Comment by autumnfjeld** [comment]
@fushar For this work, we can focus on two scenarios :

**# 1** user opens post or page editor (or it is programmatically opened)
- The Welcome Tour is unchanged,  shows content like it does now in production (for block editing)


**# 2** user opens the site editor  (or it is programmatically opened)
- The Welcome Tour shows updated content specific for Full Site Editing


It isn't dependent on flow, but rather identifying which editor. 


As we chatted about last week, p1666937551237989/1666866470.057429-slack-CRWCHQGUB  this is the easiest implementation, ya?
 
It would also be interesting to understand the mechanics if we wanted to do more "advanced" control in the future. Like show different content depending on flow, as you mention at the end of your post  pbxlJb-2U0-p2.

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
