### ISSUE TITLE
Writing Prompts - Create new writing prompt notification

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#69159]
## Description

We plan on adding writing prompts to the Gutenberg block editor. In doing so we also want to promote this feature in a couple of spots. As part of that work, we will need to create notifications for the writing prompt. We will have to do a bit of research about the best way to use the existing notifications system to achieve our aims.

Notifications will only be sent for eligible users (bloggers who haven't opted out)

This includes hooking up the link to go to the new post editor (for the correct site) with the prompt active

Notification settings are handled in https://github.com/Automattic/wp-calypso/issues/69160

## Screenshot

![image](https://user-images.githubusercontent.com/5634774/196435979-f6380d35-b4c1-4a9a-86ba-edcf81cd9736.png)

## Notification timing

Let’s create a cronjob for these notifications (both notifications and emails) which on a daily basis looks for any site with these notifications active, then does a check to see:

- Has it been a multiple of 3 days (3 days, 6 days, 9 days, etc…) since they published something? -> Send notification (Keep this going until they opt out)
- Has it been 1 day since they signed up with nothing published? -> Send notification
- Has it been a multiple of 3 days (3 days, 6 days, 9 days, etc…) since they signed up with nothing published? -> Send notification (Keep this going until they opt out)

**Comment by eoigal** [comment]
Started work on wpcom with D90182-code

**Comment by davemart-in** [comment]
I updated this PR description with the notification timing that we settled on.

**Comment by eoigal** [comment]
Added writing prompt template with https://github.com/Automattic/wp-calypso/pull/69352

**Comment by eoigal** [comment]
Found an issue deploying on WPCOM where styles aren't being ported - being worked on https://github.com/Automattic/wp-calypso/pull/69949

**Comment by eoigal** [comment]
Writing  prompts are now deployed fully on WPCOM with https://github.com/Automattic/wp-calypso/pull/69949 merged and the notifications deployed as per fieldguide instructions.
