### ISSUE TITLE
Add virtual home.html link in Calypso pages

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69158]
# Description
For MVP of the Pattern Assembler we have a number of "supporting work" items to make the user experience smoother.  One of these items is surfacing "virtual pages" in https://wordpress.com/pages.
Spike completed.  [[Spike] Surfacing virtual pages in the wordpress.com/pages UI](https://github.com/Automattic/wp-calypso/issues/69011)

This issue defines what will ship to users.  See @arthur791004 's video demo: p1666004346238589/1665657784.022599-slack-CRWCHQGUB

![image](https://user-images.githubusercontent.com/5665959/196323350-0bf97258-c8f7-44db-8c6c-b5161dbb0a14.png)

## Specs
* Show “Home” template in pages section if the homepage display is setting to “latest posts”
* It supports “Edit”, “View page” and “Copy link” actions
* It has :info: icon next to the title, and indicates this one is “Home” template, and only part of actions are supported.  Customers can click “Learn more” link to see details. 
  * Copy: "The homepage of your site displays the Home template[link to template editor or site editor] 
  * Learn more: what should we link to? https://wordpress.com/support/full-site-editing/ or directly to the Templates page here: https://wordpress.com/support/templates/
* It has the “homepage” badge below the title
* The “Home” template is searchable
* Consider home.html a "published page" in terms of "published page counts" - expect this to change as we get input or in CfT beca

## Open questions
* Do we need to increase the count of the published pages by 1?
* The virtual page won't have same "menu options" as other pages. Is this a big deal?

## Dev tasks

- [x] https://github.com/Automattic/wp-calypso/pull/69070

## Testing
* when the feature is updated, create another movie that we can share to get copy approval

**Comment by autumnfjeld** [comment]
@arthur791004  you can link any PRs here to this issue. :)

**Comment by arthur791004** [comment]
> Copy: "The homepage of your site displays the Home template[link to template editor or site editor]

When the user clicks on the Home page, they will enter the site editor. Do we still need to link the description to to the site editor?

> Learn more: what should we link to? https://wordpress.com/support/full-site-editing/ or directly to the Templates page here: https://wordpress.com/support/templates/

I link it to https://wordpress.com/support/templates/#template-hierarchy because it describes “If your site is set up to display the latest posts on the front page, the Home or Index template applies the style for that page.” below. Does it make sense?

**Comment by arthur791004** [comment]
I've made a change to update the copy and only apply to the themes that support FSE.

Here is new [demo](https://user-images.githubusercontent.com/13596067/196390946-60b0d360-978c-449a-8003-6601a208f366.mov).

**Comment by fushar** [comment]
Added a new issue for the Front Page template case: #69282.

See the original discussion here: https://github.com/Automattic/wp-calypso/issues/69171#issuecomment-1283748835

**Comment by autumnfjeld** [comment]
@arthur791004  One more question about the "rules" for showing a virtual page.  See discussion, what Saxon said about this should only apply to block themes.  p1666565049015129-slack-CRWCHQGUB

Are we limiting this to block themes only? e.g. in https://github.com/Automattic/wp-calypso/pull/69070
