### ISSUE TITLE
Improve tooltip styling

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#69178]
Part of the modernization project (p1HpG7-igQ-p2).

# Development

- [x] Update styles for the chart tooltips
(#69311)
- [x] Address review feedback
(#69508)

# Design

Create a cohesive and consistent style for tooltips/popovers across the entire Stats experience (and eventually all of Calypso).

This is based on Dotcom's own explorations of a tooltip: eqlepL7MHifK8Bgr1OWqLr-fi-415%3A1426&viewport=-816%2C-149%2C6.43

![Image](https://user-images.githubusercontent.com/390760/196405123-0b065272-9a67-4c82-a81f-4c8661cf1402.png)

![Image](https://user-images.githubusercontent.com/390760/196405944-58e0f97e-b42a-41ae-a57e-bd397ab3f38b.png)

**Comment by dognose24** [comment]
Hi @keoshi! I got a question: Is the `What happens when meteors collide with Earth` link always included in the `Post published` item?

**Comment by keoshi** [comment]
Hey, @dognose24! That’s just an example post and how it would show up in this tooltip.

I believe right now we show a maximum of two post titles (without links though) and beyond that we just have a counter: 3 Posts published, 4 Posts published, etc.

**Comment by dognose24** [comment]
Yes! I would just like to ensure the link is part of the `Post published` item. So the link shows when there is only `one` published post?

> I believe right now we show a maximum of two post titles (without links though) and beyond that we just have a counter: 3 Posts published, 4 Posts published, etc.

Should we keep this original display logic?

**Comment by keoshi** [comment]
Yes, the links are associated with that last item.

I think it would be smart to keep that same logic — max of two links, then reduce to a counter — otherwise the tooltip could grow unwieldily very quickly. Plus, keeping it the same should reduce the scope of this work, but I’m also interested to know what you think. :)

I will say that two seems like a more random choice than, say, three or even just one.

**Comment by dognose24** [comment]
> I think it would be smart to keep that same logic

Couldn’t agree with you more!

I would keep the original logic and only add links to the displayed titles.

**Comment by keoshi** [comment]
Sounds great to me! Thank you @dognose24 !

**Comment by dognose24** [comment]
PR #69311 would provide tooltips for the fundamental styles but not include the `7-day highlights` tooltip content since the feature has not been implemented. Thus, this issue would be partially fixed by #69311 and related to #69224. cc @jsnmoon

**Comment by jsnmoon** [comment]
Let's consider this issue closed once we've addressed @keoshi's feedback from [here](https://github.com/Automattic/wp-calypso/pull/69311#issuecomment-1286741996).

**Comment by dognose24** [comment]
As discussed with @jsnmoon, we plan to shelve the icons importing for now. We can import all the necessary icons only once later before the project ends. I have [proposed the fix](https://github.com/Automattic/wp-calypso/pull/69508) for [uppercase texts](https://github.com/Automattic/wp-calypso/issues/69495). cc @keoshi

**Comment by jsnmoon** [comment]
Agreed, let's track the icon updates with [this issue instead](https://github.com/Automattic/wp-calypso/issues/69530).
