### ISSUE TITLE
Writing prompts - Show writing prompt in Gutenberg editor as placeholder text

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#69172]
## Description

We plan on adding writing prompts to the Gutenberg block editor. This card covers the actual writing prompt being shown to eligible users in the actual gutenberg editor.

Eligible users are:

* Wordpress.com (or WoA) users who are bloggers `site_intent === 'write'`
* And also opened the editor from one of two prompt links

## Screenshots

<img width="1680" alt="in-editor" src="https://user-images.githubusercontent.com/22446385/196358175-a4e82ca4-1ef3-4cd8-b29e-196b2534026c.png">

![image](https://user-images.githubusercontent.com/5634774/196436815-902351be-f52c-4046-a01b-74788df1d6d6.png)

Currently being implemented in jetpack here: https://github.com/Automattic/jetpack/pull/26680

**Comment by creativecoder** [comment]
This has been completed.
