### ISSUE TITLE
Writing Prompts - Button to permanently hide writing prompts box from the My Home screen for current site

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#69173]
## Description
We plan on adding writing prompts to the Gutenberg block editor. In doing so we also want to promote this feature in a card on the my-home page https://github.com/Automattic/wp-calypso/issues/69157. As part of that work, we will need to give users a way to permanently dismiss the card. 

* Includes adding the "hamburger menu" to the card
* Also includes a link to the notification settings, see: https://github.com/Automattic/wp-calypso/issues/69160

## Screenshot

![CleanShot 2022-10-17 at 10 47 55](https://user-images.githubusercontent.com/22446385/196361996-597d5fa8-7f11-46bb-a69a-f3bf5de85b70.jpeg)

**Comment by creativecoder** [comment]
This has been implemented in the my home card.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/1699996/211409217-7ef9da77-b3fe-497c-b324-b27bb9ee5e75.png">
