### ISSUE TITLE
Writing prompts - Support team global in translating writing prompts to mag-16 languages and updating API

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#69170]
## Description

We plan on adding writing prompts to the Gutenberg block editor. As part of that work, we will need to translate the existing writing prompts returned by the existing writing prompts API (2decf-pb) to be translated into the magnificent 16 languages (PCYsg-9nE-p2).

The global team has this issue 526-gh-Automattic/i18n-issues to track getting the actual translation process happening in glotpress. Their task actually also includes updating the API so in practice there may be nothing for us to do. 

This task on our board is just a placeholder to assist them/coordinate as needed and potentially do the API i18n work if they don't get to it.

p2 thread: pe7F0s-gI-p2#comment-258

**Comment by creativecoder** [comment]
Started a discussion about the API implementation and translations here: pe7F0s-j1-p2

**Comment by creativecoder** [comment]
Writing prompt translations have been completed.
