### ISSUE TITLE
Create new section: 7-day highlights

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#69224]
Part of the modernization project (p1HpG7-igQ-p2).

# Development

Related highlights sections: #69224, #69227, #69229. Check with progress there to explore code reuse possibility.

- [x] Ensure that this API data is available from an endpoint.
(@jsnmoon: data is available, an endpoint doesn't exist)
- [x] Create an API endpoint for fetching data for the 7-day highlights.
(@jsnmoon: ✅ D90814-code)
- [x] Create a highlights component that shows current values for Visitors, Views, Likes, and Comments.
(#69541)
- [x] Integrate the highlights component in the Traffic page with appropriate API data.
(#69640)
- [x] Integrate trends data into the highlights component.
(@jsnmoon: ✅  D91238-code)
- [x] Release to production.
(#69862)

Punted for later iterations:
- [ ] Add tooltip support to the highlights component.

# Design

To create value on the Traffic page and highlight metrics that we have access to but aren't exposing to users at the moment, we propose adding a new section: 7-day highlights.

This will give users a quick glance at:

- Metrics for the on-going last 7 days for Visitors, Views, Likes, and Comments.
- Info icon will show additional explanation of exactly what data is included here. _Contents are still WIP!_
- Comparison with the previous period via trends (↑/↓/—) and percentage of change.
- These numbers would display as truncated for anything larger than 999: 1.5K, 2M, 47B, etc.
- When these truncated numbers are hovered/focused we can display the exact number via a tooltip ([related GH task here](https://github.com/Automattic/wp-calypso/issues/69178)). For screenreaders we can simply use the full number.

Specs are below:

![Image](https://user-images.githubusercontent.com/390760/196393011-9ef5ffd6-3ef0-4b4b-b87e-3ea37feb6286.png)

![Image](https://user-images.githubusercontent.com/390760/196412448-bef14473-e166-4826-be56-6fdc8b6e84e4.png)

![Image](https://user-images.githubusercontent.com/390760/196393155-f6c73600-7a8a-4818-b6fe-2da2ca023786.png)

![Image](https://user-images.githubusercontent.com/390760/196393102-fa4fc884-5535-4af5-98b4-c491c75a949a.png)

Behavior in mobile:

- Horizontal scroll through all the individual cards.

![Image](https://user-images.githubusercontent.com/390760/196416576-8d064c7a-a8c3-41da-baf1-6eabc9a73949.png)

![Image](https://user-images.githubusercontent.com/390760/196416595-a103a384-4aa7-436a-870e-bfc0164be853.png)

**Comment by jsnmoon** [comment]
@keoshi: Are we showing values from the 7-day highlights anywhere in the current interface?

**Comment by keoshi** [comment]
@jsnmoon This is a new module we're proposing and there's currently no visibility of these metrics.

We assumed this would be possible because there's a 7-day summary for some metrics in the detailed view page; e.g.: https://wordpress.com/stats/day/posts/SITE_URL?startDate=2022-10-19&summarize=1&num=7

**Comment by jsnmoon** [comment]
Going to try tackling this for the next few days.

**Comment by jsnmoon** [comment]
@keoshi: I noticed some divergence between the pictured designs and the Figma file. Am I correct in assuming the Figma file as our canonical source of truth?

**Comment by jsnmoon** [comment]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/4044428/201427144-b5c6dced-e1b4-485d-84e9-49229de58621.png">


@danjjohnson: We just shipped this new feature to production!
