### ISSUE TITLE
Stats: Add an All-time highlights section to the Insights page

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#69229]
Part of the modernization project (p1HpG7-igQ-p2).

# Development

Related highlights sections: #69224, #69227, #69229.

- [x] Create a component for showing values from the existing all-time stats widget.
(https://github.com/Automattic/wp-calypso/pull/69937)
- [x] Create a component for showing the most popular time.
(https://github.com/Automattic/wp-calypso/pull/69937)
- [x] Create a component for showing the highest page views.
(https://github.com/Automattic/wp-calypso/pull/69937)
- [x] Combine the above components into a highlights component.
(https://github.com/Automattic/wp-calypso/pull/69937)
- [x] Integrate the highlights component into the Insights page [below the Year in Review section](https://github.com/Automattic/wp-calypso/issues/69227).
(https://github.com/Automattic/wp-calypso/pull/70001)

# Design

The Insights page will now a section named “All-time highlights”, which groups and rearranges data points that are already available (AFAIK). Three modules are included:

- All-time stats
- Most popular time
- Best pageviews day ever

The first one has more metrics, but the last two are equally formatted. All three cards should have the same height when they appear side-by-side on large screens.

![Image](https://user-images.githubusercontent.com/390760/196452286-928e00b8-e013-4d2f-a327-b79978c3f689.png)

![Image](https://user-images.githubusercontent.com/390760/196452313-79eec1c0-a6cc-4415-871d-3f77c227e97e.png)

Mobile behavior:

- All three cards should be placed into a single one.
- This unified card now reveals a top navigation that lets users slide to the next/previous card.

![Image](https://user-images.githubusercontent.com/390760/196452334-e1182898-de03-4f39-8fa2-9fe4d66cf9ba.png)

**Comment by dognose24** [comment]
Since the number of `Likes` does not exist in the `/stats` API so far, could we restore the `Likes` item of the All-time stats card in a follow-up improvement with the API update for all-time like counts? cc @keoshi @jeffgolenski @jsnmoon

**Comment by keoshi** [comment]
That sounds perfectly reasonable to me, @dognose24. :)
