### ISSUE TITLE
[All Emails] Introduce `data-wpcom-track` data attribute to force tracking of links.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#69235]
When emails are sent out from Simple Site with custom domain or Atomic sites, they are currently not being tracked.

This is because the `WPCOM_Guides_Utils::make_links_trackable()` function is a general-purpose function that doesn't allow external links to be tracked to avoid Open Redirects (security).

However, since the links on emails are URLs that we control, we should allow them to be tracked.

In order to do that, we will introduce the `data-wpcom-track` attribute which forces a link to be tracked regardless of whether they are from external domain, e.g.

```
<a href="" data-wpcom-track>Reply</a>
```

We will start by updating New Post emails.

**Comment by mashikag** [comment]
@JuanLucha I see there is two of us assigned to the issue. FYI I am starting the work on the ticket now.

**Comment by yansern** [comment]
Patch here: D90986-code
