### ISSUE TITLE
[New Post] Adjust template for password-protected posts

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#69244]
The _Comment_ and _Like_ buttons are displayed even when the post is password-protected:

![Image](https://user-images.githubusercontent.com/25105483/196652805-a0a68e67-4d67-4dca-bb31-67f22dd9cc15.png)

I believe these buttons, together with the tip, should not display (as they don't do what is expected of them). Maybe we could consider replacing them with a button like "Go to post" (or similar).

We could also consider changing the format and copy of the current _"This post is password protected. You must visit the website and enter the password to continue reading."_ message.

**Comment by saygunnyc** [comment]
>I believe these buttons, together with the tip, should not display
> Maybe we could consider replacing them with a button like "Go to post" (or similar).

💯 

Let's keep the post title and details as is for now.
The CTA should be "View post".

**Comment by TimBroddin** [comment]
Deployed!
