### ISSUE TITLE
Limit Global Styles: Changes are not saved after clicking on the upgrade link

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#69247]
#### Steps to reproduce

1. Open the site editor on a site with limited Global Styles
2. Add some changes to the Global Styles
3. Click on the save button
4. Click on the upgrade link that is displayed in the pre-save notice
![image](https://user-images.githubusercontent.com/1233880/196694239-92d7d862-2cc6-4eaf-afd7-1662d12df958.png)

#### What I expected

The Global Styles changes to be saved before going to the plans page. I shouldn't be asked to save the changes before.

#### What happened instead

I'm asked to save the changes before leaving. If I click leave, my changes are unsaved.

![image](https://user-images.githubusercontent.com/1233880/196694521-425e8297-47e5-4f3a-a851-45303e9ea238.png)

#### Context / Source

pdtkmj-EG-p2#comment-1128

**Comment by mmtr** [comment]
Now that I think about it, I'm not sure we should save without warning the user, since those changes won't be public and the user showed interested in having them public which is why they clicked on the upgrade link before saving. 

The site editor doesn't have the concept of drafts to save unpublished changes, so I'm not sure how to proceed here. Maybe we should open the plans page on a new tab and keep the changes unsaved?

@Copons @SaxonF what are your thoughts?

**Comment by SaxonF** [comment]
Can we open that upgrade link in a new tab?

**Comment by mmtr** [comment]
Yup! That's what I ended up doing in https://github.com/Automattic/wp-calypso/pull/69342. Thanks!
