### ISSUE TITLE
[Bug]: Style picker shows scrollbars for Pixl theme

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#69279]
### Quick summary

When creating a new site, and picking Pixl theme, I see scrollbars in style picker. I don’t see them in other themes nor in site editor, so not sure what’s going on.

I have the “always show scrollbars” setting enabled on my browser (or was it OS level) to easily spot scroll problems, so likely won’t look that bad for customers, but they’re still scrollable for customers and might show scrollbars on hover.

![image](https://user-images.githubusercontent.com/87168/196903999-22eebd07-1aa9-4066-bdbe-987f3fc176c0.png)
![image](https://user-images.githubusercontent.com/87168/196904009-eb58eca8-1d93-4d5c-86a7-1c453461166b.png)

### Steps to reproduce

1. create new site /start
2. Pick Pixl theme
3. See style picker has scrollers
   - probably requires "always show scrollbars" setting be on in the browser/OS

### What you expected to happen

No scrollers.

### What actually happened

scrollers

### Browser

Mozilla Firefox

### Reproducibility

Consistent

**Comment by simison** [comment]
Just guessing, but perhaps there's CSS reset missing, or it's different from the one in Gutenberg?

No problems in the editor:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/87168/196905754-47e795f8-3378-4d22-af7f-011b90c27dae.png">

**Comment by miksansegundo** [comment]
Related https://github.com/Automattic/wp-calypso/pull/69272

**Comment by taipeicoder** [comment]
Closing via #69363
