### ISSUE TITLE
Onboarding Design Picker - "Simple" Premium Theme does not have option for single purchase

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#69296]
The upgrade modal for "simple" first-party premium themes (i.e. non-bundled) implies (correctly) that the user can either purchase the theme individually or upgrade to Premium to get all simple first-party premium themes included. 

However, the price displayed is the price for the Premium plan, not the individual theme purchase, and clicking on the "Buy and Activate Theme" button takes the user to purchasing a Premium theme, not the individual theme as would be expected.

![CleanShot 2022-10-20 at 13 17 45@2x](https://user-images.githubusercontent.com/13437011/197027197-c48b062a-b555-4d67-9591-76613967e6c5.png)
![CleanShot 2022-10-20 at 13 18 45@2x](https://user-images.githubusercontent.com/13437011/197027334-9a561121-739e-4666-81ee-8cf345a45b7f.png)

Expected behavior:
* Modal displays purchase price for individual theme.
* "Buy and Activate Theme" takes user to cart with the individual theme purchase.
* "or get it for free when on the Premium plan" link takes user to cart with a Premium account subscription

Actual behavior:
* Price displayed is Premium account subscription yearly price
* Both links take the user to a cart with a Premium account subscription.

**Comment by sixhours** [comment]
<img width="801" alt="Screen Shot 2023-03-16 at 4 32 18 PM" src="https://user-images.githubusercontent.com/2124984/225757456-d2201677-f5e7-47f2-a38e-61345340961c.png">

At some point this modal was updated to reflect the actual behavior and remove references to purchasing an individual theme. Closing as fixed.
