### ISSUE TITLE
Onboarding Design Picker - "Skip for Now" link in seller onboarding flow takes user to old screen

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#69297]
When going through the seller onboarding flow, the "Skip for now" button on the store name and tagline screen takes the user to the old `storeFeatures` screen. 

![CleanShot 2022-10-20 at 13 22 38@2x](https://user-images.githubusercontent.com/13437011/197028025-5df1174e-8411-4171-bbd8-f080a5034514.png)
![CleanShot 2022-10-20 at 13 23 14@2x](https://user-images.githubusercontent.com/13437011/197028309-43723dfb-5bb2-429c-85cd-3ba9ef905292.png)

This link should take the user to design selection in the same way that the "Continue" button does.

**Comment by sixhours** [comment]
The skip button was removed from this screen in #72159
