### ISSUE TITLE
Fix empty authors

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#69299]
Part of the modernization project (p1HpG7-igQ-p2).

In same cases, the list of authors shows a nameless/non-existent author causing it to appear empty.

It would be good to investigate why this is happening and fix these occurrences.

![Image](https://user-images.githubusercontent.com/390760/195615822-a4f3f455-68ba-48dc-b20a-4c906c7f4acf.png)

**Comment by a8ck3n** [comment]
So from what I can tell, this unlabeled user is the consolidated list of all public posts by all users who do not have an associated WordPress.com login. As I understand it, we don't actually sync this user data so I'm not sure we can parse this any further.

One option might be to label the user something like, "wp-admin user" or "Unconnected Author" or something similar. We could then include a tooltip explaining that we only index connected authors. Then it would be up to the site admin to decide if they wish to connect all their authors for the sake of better Stats fidelity.

Steps to reproduce in pejTkB-4F.
