### ISSUE TITLE
[Block] Blog Posts Block missing first post when added to FSE Templates

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#69306]
### Quick summary

Using the `Blog Posts Block` instead of a `Query Loop Block` on templates seems to not work well. The most recently published post doesn't display on the live site. 

(And because of the lack of previews, as reported here: https://github.com/Automattic/wp-calypso/issues/69101 , this is hard to notice while working in the editor)

### Steps to reproduce

1. Activate an FSE theme like `Zoologist`
2. Set the homepage to display latest posts
3. Open the Site Editor to edit the homepage
4. There will be a Query Loop block in place. Below that, add the Blog Posts block to the template. 
5. Save this change and view the live site

### What you expected to happen

The same posts in the same order should appear in either the Query Loop Block or the Blog Posts block.

### What actually happened

The Blog Posts block does not include the most recently published post.

**Example: AT site, Zoologist Theme**

![Markup on 2022-10-20 at 15:43:19](https://user-images.githubusercontent.com/27249804/197073607-cfe078ee-69b4-4bae-812b-e919cde844b7.png)

### Context

Currently testing for this user: 5646515-zd-woothemes

This issue has also been reported as theme specific, here: https://github.com/Automattic/themes/issues/6161 but it seems it's not just impacting that theme. 

I replicated the issue on an AT test site using **Byrne** and **Zoologist**.

**Byrne**

![Markup on 2022-10-20 at 15:38:34](https://user-images.githubusercontent.com/27249804/197073583-8d23612f-419d-4352-b48e-104c56ed7d80.png)

### Platform (Simple, Atomic, or both?)

Atomic

### Browser, operating system and other notes

Firefox

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is to replace the Blog Posts block with the Query Loop block. While this is easy for us to implement, it may be difficult for users who prefer the Blog Posts block, as the QL block is more complex to add and set up.

**Comment by cuemarie** [comment]
My gut tells me that it's expected that the Blog Posts Block won't actually work that well on FSE templates, and that these issues are evidence of that - but I haven't been able to prove that theory anywhere. If users shouldn't be using the Blog Posts block on templates, I don't think we've made that clear enough to users (or HEs) yet, so it'd be great to confirm that!

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated 
- Tested on AT - Replicated 
- Tested on Self-hosted - Replicated 
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this issue with the Blog Posts block in all tests on simple, AT, and self-hosted.
- Blog Posts block comes from WordPress.com Editing Toolkit plugin on self-hosted site.
- I agree that it would be helpful to clarify if Blog Posts blocks should only be used on pages or if they can be used on templates too as an alternative to the Query Loop block.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by csabarakasz** [comment]
Same issue for Quadrat Yellow theme here:

- [ ] 5686765-zd-woothemes

I am suggesting using Query Loop Block instead.

**Comment by sanjeev00733** [comment]
Similar issue with Varese theme in 

- [ ] 5693751-zd-woothemes

**Comment by dsas** [comment]
This block (a8c/blog-posts) is an [alias for the newspack-blocks/homepage-articles block](https://github.com/Automattic/wp-calypso/blob/67aa5a0e9dd5ec27011a57fe41dac55dbfdabc0e/apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php#L24-L26) which is synced from the [newspack repo](https://github.com/Automattic/newspack-blocks/tree/master/src/blocks/homepage-articles).

The block does not show the current item in the WordPress loop:
 * The [block calls Newspack_Blocks::build_articles_query](https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/homepage-articles/view.php#L24)
 * `Newspack_Blocks::build_articles_query` specifically says [ignore the current item in The Loop, unless in specific mode](https://github.com/Automattic/newspack-blocks/blob/dc0bb40472f2564e53bf5520b684edb536605fcd/includes/class-newspack-blocks.php#L579-L590).

This has been the case since [June 2020](https://github.com/Automattic/newspack-blocks/commit/030024d70135fa655985aff801568bee2550caa0), the rationale being if you used this block inside a blog post then you wouldn't want to include the current post.

An alternative explanation is that the posts are already appearing on the page via another instance of this block, in which case they might get excluded. This wasn't the case in the happychat I witnessed.

Is something inside these themes / FSE starting The Loop?

**Comment by jartes** [comment]
Another report on 5800833-zd-woothemes

Suggested the Query Block as a workaround.

**Comment by sanjeev00733** [comment]
Another report on 5830325-zd

Suggested adding a query loop block

**Comment by zyousafi** [comment]
Another report on 5889489-zd-woothemes

Suggested the Query Loop Block as a workaround for now

**Comment by deancroyal** [comment]
Another report here on site using Twenty Twenty Three theme 40068045-hc 

We'll use Query Loop block to temporarily display latest post until this is resolved.

**Comment by rinazrina** [comment]
Another report on site using Varese theme: #5988052-zen 

User has only one post, and it's not showing on the Blog Posts block, both on the editor and on the published page. Query Loop Block worked as a workaround.

**Comment by poeticabdul** [comment]
Another report 5983195-zen

**Comment by metabreakr** [comment]
I've encountered this numerous times in FSE themes for BBE customers. The issue with the query loop is that it does not show projects nor testimonials, unlike the blog posts block. 

This is a blocker for me — one or the other needs to be "fixed," and my hope is that the query loop can show additional post types.

**Comment by dsas** [comment]
Not to distract from this issue, but the query loop can show projects or testimonials, how useful that is depends upon what exactly you're trying to achieve.
<img width="284" alt="Screenshot 2023-03-15 at 19 44 50" src="https://user-images.githubusercontent.com/93301/225425652-b07df23e-5776-42e4-92dc-795f498f2417.png">

**Comment by metabreakr** [comment]
Thanks @dsas —  I stand corrected!

**Comment by poeticabdul** [comment]
Reported here 19840491-hc

**Comment by kuropixel** [comment]
Reported here 42504650-hc

Also reproduced on a test sites (both Atomic and Simple) with theme Adventurer which was able to show the issue:
- The latest post will not be displayed

Workaround: Query loop block

 Other FSE themes seemed to be ok. 🤷‍♀️

**Comment by jartes** [comment]
Another case on 6300599-zd-woothemes with the `Skatepark` theme on a Simple site.

**Comment by jartes** [comment]
Another report on 6319085-zd-woothemes

**Comment by rinazrina** [comment]
Another one: 6381775-zd-woothemes

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – reproduced
Tested on Atomic – reproduced
Replicable outside of Dotcom – not tested

📌 FINDINGS/SCREENSHOTS/VIDEO
**AT** - video showing part of the reproduction steps

https://github.com/Automattic/wp-calypso/assets/6549265/a2dcebf6-6bf3-4adc-8540-dbe80b5c2736



**AT** - screenshot
<img width="1792" alt="Screenshot 2023-06-12 at 12 04 34 PM" src="https://github.com/Automattic/wp-calypso/assets/6549265/70ea35d3-909f-4d74-854f-1c28880b9e7a">


📌 ACTIONS
- maintain status quo despite the number of ticket since there's an easy workaround.

**Comment by aleone89** [comment]
Another report here: https://wordpress.com/forums/topic/blog-posts-block-not-showing-latest-posts/?view=all

**Comment by ClassicRKR27** [comment]
Another report here: 6524568-zd-woothemes

Found that the post actually _is_ showing, it's just not in the correct order and is hidden until you click the `Load more posts` button: ![B5aNZl.png](https://github.com/Automattic/wp-calypso/assets/51870544/13696c65-515c-4c4e-ac4d-10562b5cae1d)

**Comment by aleone89** [comment]
Another report here: https://wordpress.com/forums/topic/the-blog-posts-block-does-not-update-properly/#post-3972582 

Theme: Tenaz

**Comment by metabreakr** [comment]
While working on pdEkSe-43T-p2 I discovered that the Post Carousel block is also affected by this same issue. 

EDIT: Related issue: https://github.com/Automattic/wp-calypso/issues/73171

**Comment by ClassicRKR27** [comment]
Another report here: 6267279-zd-woothemes

**Comment by katiebethbrown** [comment]
Also Related:

- https://github.com/Automattic/wp-calypso/issues/62696

**Comment by CodeAllNightNDay** [comment]
Issue here: https://wordpress.com/forums/topic/bug-report-8/

**Comment by zdenys** [comment]
Another related issue:
- https://github.com/Automattic/newspack-blocks/issues/1217

**Comment by poeticabdul** [comment]
Another issue 6755689-zen

**Comment by jp-imagines** [comment]
Another report in 6787727-zd-a8c

**Comment by supernovia** [comment]
Another report here:
https://wordpress.com/forums/topic/home-page-restricts-posts-seen/

**Comment by rw-ye** [comment]
Another report: 7544640-zd-a8c

**Comment by Aurorum** [comment]
7569274-zen

**Comment by jp-imagines** [comment]
I had a potential report of this here: 7618145-zd-a8c, last reported on January 21. The user's report matches the behavior described here, but I don't see the issue on their site anymore.

I can't replicate on a Simple test site, but I _can_ still replicate on Atomic.

Marking this for re-triaging. Not sure if maybe a recent update fixed this, and it's coming to WoA soon?

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Could Not Replicate 
– Tested on Atomic: Could Not Replicate 

- Yet, I reproduced this along with @nazilya06 a few days ago, but the issue does not appear to be present any longer.

📌 ACTIONS

– Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by katiebethbrown** [comment]
@filipanoscampos - I'm reopening. This is still happening on my test site.

https://staging-3cce-kbbatomicbusiness.wpcomstaging.com/

Atomic site. Active theme is Bute. Homepage uses the Front Page template.

You can see in the screenshot that the editor (on the left) looks as expected. I have a blog posts block on top and a query loop blow below. They both show the same posts in order.

But the front end (on the right) shows the issue. The blog posts block on top starts at post two.

Changing the deduplication logic setting has no impact. I see the same result in the editor and on the front end regarless of how it is set.

So there are two issues:

- The editor and front end don't match.
- The front end is skipping the first post in the loop.

![CleanShot 2024-01-30 at 14 26 38@2x](https://github.com/Automattic/wp-calypso/assets/42279181/8fc9f222-4abd-4f18-8c8e-6a55fd96844a)

**Comment by Aurorum** [comment]
7667528-zen

**Comment by masperber** [comment]
7683199-zen

**Comment by CacheMeOwside** [comment]
Another report: 7683155-zen
Suggested the Query Loop Block as a workaround.

**Comment by OmarFPG** [comment]
7694150-zen. Suggested the Query Loop Block as a workaround.

**Comment by CacheMeOwside** [comment]
Another report: 7683155-zen
Suggested the Query Loop Block as a workaround.

**Comment by supernovia** [comment]
7717852-zd-a8c
Suggested the query loop block but the user would rather not use that.

**Comment by Robertght** [comment]
Another one with Creatio 2. Used the Query Loop block instead.

7772534-zd-a8c

**Comment by chekle** [comment]
Another user experiencing this issue using the Spiel theme:
7777110-zd-a8c

**Comment by AnjanaV93** [comment]
Another report here with Bute theme: 7833034-zen

**Comment by CacheMeOwside** [comment]
Another report here with Assembler theme: 7797059-zen
Suggested the Query Loop Block as a workaround.

**Comment by nazilya06** [comment]
Another report with Twenty Twenty-Three theme: 7932261-zd-a8c
Suggested the Query Loop Block as a workaround.

**Comment by filipanoscampos** [comment]
Reported here 8000272-zd-a8c

**Comment by filipanoscampos** [comment]
Another case, here: 8021921-zd-a8c

**Comment by rosepajaroja** [comment]
Another case here: 8040447-zd-a8c

I can also replicate it on my test AT site

**Comment by chekle** [comment]
+1 8088220-zd-a8c

**Comment by chekle** [comment]
8088220-zd-a8c

**Comment by hngdny** [comment]
Another report here 8088859-zd-a8c
Yuga theme

**Comment by chekle** [comment]
+1 8088220-zd-a8c

**Comment by deancroyal** [comment]
Report here from customer using Assembler theme 8098167-zd-a8c

**Comment by ezebecke** [comment]
Another case 8101222-zd-a8c

**Comment by katiebethbrown** [comment]
^ When this was closed in January it automatically moved to `Done` status in the project board. Re-opening didn't adjust that, and I just caught it. So I've restored it to an active state in the project board and moved it back into `Needs Triage` status, because it's continuing to collect reports and could use review.

**Comment by filipanoscampos** [comment]
8124244-zd-a8c

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Simple Site:

![CleanShot 2024-04-30 at 15 18 01@2x](https://github.com/Automattic/wp-calypso/assets/14153300/e2ebe0ce-c795-4f4d-a4f1-ab7f0c5b0865)

Atomic Site:

![CleanShot 2024-04-30 at 15 22 58@2x](https://github.com/Automattic/wp-calypso/assets/14153300/ab1177ac-a9b8-4bde-b315-e2c81c784a59)


📌 ACTIONS
- Triaged

📌 Message to Author
@katiebethbrown the last time I checked on this p1689624552262589-slack-C0160HSMDQV the main problem was that this block (like the Post Carousel block) was not designed to work in the templates when they were developed by Newspack. 

Newspack doesn't have immediate plans to update them, and no teams in Dotcom are actively working on a8c block updates and maintenance. Any chance 51 devs have the bandwidth to work on this bug and ship those improvements for all a8c customers?

**Comment by mxhassani** [comment]
8140315-zen
Simple site

**Comment by rw-ye** [comment]
8253473-zd-a8c

Theme: Cakely

**Comment by Joshgrygiel** [comment]
Another report in 8343635-zd-a8c

Fewer theme, AT site

**Comment by DavidSaladu** [comment]
Other report https://wordpress.com/es/forums/topic/no-muestra-ultima-entrada/?view=all Simple plan, Carnation theme

**Comment by i11za** [comment]
8478820-zd-a8c
Starter plan
Assembler theme

**Comment by rosepajaroja** [comment]
Another one here: 8581276-zen
Suggested Query Loop as an alternative
