### ISSUE TITLE
Marketplace: Refine the design of the CTA buttons in SaaS products

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#69328]
The current design of the CTA buttons for SaaS products includes a card with a white background that does not look very nice in the plugins details sidebar.

![CleanShot 2022-10-21 at 12 56 22@2x](https://user-images.githubusercontent.com/3519124/197180505-ff250d68-5c77-449d-9fb7-27589eb7501d.png)

@vinimotaa, would it be possible to create a Figma design for that?

For context, this is the original design the changes were based on: https://github.com/Automattic/wp-calypso/issues/67657#issuecomment-1275358502

In order to see the above Test Saas Product:
- Sandbox your API and make sure you have `define( 'USE_STORE_SANDBOX', true );` as explained in PCYsg-IA-p2
- Select a free site and search for the plugin Test SaaS Product, e.g. /plugins/test-saas-product/<site_id>

cc: @WBerredo

**Comment by vinimotaa** [comment]
Access to [Figma file here](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=5338%3A39127)!

@epeicher @WBerredo

**Comment by cpapazoglou** [comment]
For the time being the differences from the design I can **quickly**  see, are:

- border radius
- sidebar width

@vinimotaa after a call with the team we found out that the white background of the CTA to upgrade plan looks like a hole due to the main page background also being white. Can we adjust something to make it look better?

**Comment by vinimotaa** [comment]
@cpapazoglou looking at the outcome, I agree with that!

What if we add a slightly darker gray (EFEFEF) to it instead?

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/97929097/197559280-46e1d3ff-fe66-4986-8d37-698ee18ea9ca.png">

I also tried to follow the same style as the "Get Started" button - white BG with a grey stroke:

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/97929097/197559704-60e43e67-fb4d-4ebb-b4f9-1a134b4f70c9.png">

**Comment by epeicher** [comment]
Thanks @vinimotaa  for the update! I like the second version with the white background and a grey border similar to the "Get started" button.

@WBerredo , @cpapazoglou , what do you think?

**Comment by cpapazoglou** [comment]
The second version looks better to me too.

Thanks @vinimotaa

**Comment by epeicher** [comment]
The changes in the sidebar and the card for SaaS products have been implemented in the linked PR #69429. Some screenshots of the before and after can be found there.

The Figma file used f84fqtCG4pCnCh2Hq0But5-fi-5468%3A38057
