### ISSUE TITLE
Gifting: Investigate on where should the front end banner code live

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#69326]
Context: p1666331336448729/1666212587.180779-slack-C03FE3T479R

We need take these into consideration:
* Jetpack
* wpcomsh
* wpcom trunk
* Jitms
* somewhere else

Also along with the case for:
* atomic sites
* simple sites

Acceptance criteria:

- [ ] decision on where we should put the code for the front end banner

**Comment by candy02058912** [comment]
Some investigation:


![Image](https://user-images.githubusercontent.com/6586048/197170448-213a6457-27bc-47e0-a7c0-12e058b41624.png)

### 1. blog-plugins: top marketing bar 

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Soybt%2Qcyhtvaf%2Sznexrgvat%2Qone.cuc%3Se%3Qo914npq5%23373%2Q379-og

### 2. jetpack? mu-plugins?: cookie accept dialog

fbhepr%2Sfrnepu%3Scebwrpg%3Qpnylcfb%26cebwrpg%3Qwrgcnpx%26cebwrpg%3Qjcpbz%26cebwrpg%3Qjcpbzfu%26shyy%3Q%2522vapyhqvat%2Oubj%2Ogb%2Opbageby%2Opbbxvrf%252P%2Ofrr%2Ourer%2522%26qrsf%3Q%26ersf%3Q%26cngu%3Q%26uvfg%3Q%26glcr%3Q%26keq%3Q%26aa%3Q4%26fv%3Qshyy%26fv%3Qshyy-og

### 3. mu-plugin: actionbar

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Snpgvbaone%2S-og

**Comment by allilevine** [comment]
@candy02058912 Thanks for kicking this off! I'd also recommend taking a look at the discussion on https://github.com/Automattic/dotcom-forge/issues/1014

**Comment by paulopmt1** [comment]
Hey @candy02058912, we got a direction on it: p1666640497864299/1666212587.180779-slack-C03FE3T479R. I'm curious to understand why and how to sync the code between `wpcomsh` and `wpcom`. But pretty sure we'll get there!

**Comment by paulopmt1** [comment]
Thanks for working on this @candy02058912!

**Comment by candy02058912** [comment]
Thanks for helping with it @paulopmt1 🙏
