### ISSUE TITLE
Remove GA section from Tools > Marketing > Traffic when the Jetpack feature is disabled

### ISSUE THREAD

**Issue by xristos3490** [Automattic/wp-calypso#69320]
### What

There is a Google Analytics section under Tools > Marketing > Traffic. When the `google-analytics` jetpack feature gets disabled using the `jetpack_get_available_modules` hook, this section is not removed as supposed to be. 

This issue aims to make this section's visibility reflect the feature status.

**Comment by ash1eygrace** [comment]
This came up here p1683352766763799-slack-C03TY6J1A

**Comment by syhussaini** [comment]
> This came up here p1683352766763799-slack-C03TY6J1A

Related ticket 6266500-zen

**Comment by csabarakasz** [comment]
6377666-zd-woothemes User asked how to add the Measurememnt ID to the Commerce plan—shared the install Site Kit workaround.
