### ISSUE TITLE
Marketplace: Handle SaaS products when no site is selected

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#69329]
When no site is selected and the user selects a SaaS product, it should redirect the user to the third-party vendor as it currently does when opening the plugin details and a site is selected https://github.com/Automattic/wp-calypso/pull/68667#issue-1398137649

#### Steps to reproduce:
- Sandbox your API and make sure you have define( 'USE_STORE_SANDBOX', true ); as explained in PCYsg-IA-p2
- Navigate to https://wordpress.com/plugins?s=test _without selecting any site_
- Select the `Test SaaS Product`
- Click on Manage sites (screenshot below)
- The buttons should read `Getting started in a similar way to when opening the plugin details with a selected site

![CleanShot 2022-10-21 at 13 17 42@2x](https://user-images.githubusercontent.com/3519124/197184025-ef287044-74cb-49d0-8bec-bbd8354a9c33.png)

**Comment by cpapazoglou** [comment]
Closing https://github.com/Automattic/wp-calypso/issues/69367 as duplicate.
