### ISSUE TITLE
Editor: Pages don't have a spot to enter tags even when theme declares support for tagged pages

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#6934]
#### Steps to reproduce
1. On a WordPress.com site, add a page to a theme that supports pages as part of the Featured Content area, such as [Sketch](https://theme.wordpress.com/themes/sketch/).
2. In the page editor, look in the sidebar for a spot to add a tag.
#### What I expected

I expected to find a spot to add a tag to the page, since Sketch supports pages in the Featured Content area, and in order to use Featured Content, the page must be tagged.

The tag option **is** present as expected in WP Admin:

![edit page __ kp test site __ wordpress](https://cloud.githubusercontent.com/assets/7662449/16999711/689213ba-4e8d-11e6-8639-c1e81c317b03.png)
#### What happened instead

There is nowhere for users to add a tag to a page in Calypso, even when the theme supports it.
#### Page support in Jetpack Featured Content

This is the function to add page support to a theme - note the word "page" in the array.

```
add_theme_support( 'featured-content', array(
  'filter'     => 'sketch_get_featured_posts',
  'max_posts'  => 10,
  'post_types' => array( 'post', 'page', 'jetpack-portfolio' ),
) );
```
#### Browser / OS version

All 
#### Context / Source

Reported in the WordPress.com support forums at https://en.forums.wordpress.com/topic/adding-tags-to-pages-1
# user-report

**Comment by nylen** [comment]
This was added a couple days ago in #6744, but it and other features related to custom post types are behind a feature flag pending further testing.  It's enabled in development mode and on wpcalypso.wordpress.com, though.  See also #6626.

**Comment by aduth** [comment]
By default, pages do not support tags. It appears that for themes supporting featured content, the `post_tag` taxonomy is updated to add support for pages. It appears as a consequence of this that the post type `tags` support is added, which [while not listed as a built-in support](https://codex.wordpress.org/Function_Reference/add_post_type_support) was used previously to enable the tags input for editing pages on these themes.

As @nylen mentioned, this will be enabled by default with the impending release of custom post type support, but in the interim we could also seek to re-add the condition which would allow tags to be shown when we determine the post type support exists.

Ref: 11968-gh-calypso-pre-oss

**Comment by aduth** [comment]
Proposed interim fix at #6937

**Comment by supernovia** [comment]
Heyo! We just noticed this is still an issue if the interface language not English. We've tested French and Spanish.

**Comment by aduth** [comment]
Fixed again in r146417-wpcom

**Comment by supernovia** [comment]
Thank you :)
