### ISSUE TITLE
grunion-contact-form error on the Classic Editor in simple sites

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#69344]
### Quick summary

Creating or editing a post using the Classic Editor in a simple site results in this error: 

`Failed to load plugin url: /wp-content/mu-plugins/grunion-contact-form/js/tinymce-plugin-form-button.js`

The error message can be closed it's possible to edit the post and save the changes, so it's not a critical error.

### Steps to reproduce

1. On a simple site, go to Posts ---> All Posts.
2. Switch to Classic View.
3. Create a new post using the Classic Editor, or edit an existing post using the Classic Editor.

### What you expected to happen

The post should load in the Classic Editor without errors.

### What actually happened

The post is loaded in the editor, but shows this error: `Failed to load plugin url: /wp-content/mu-plugins/grunion-contact-form/js/tinymce-plugin-form-button.js`

### Context

5649087-zd-woothemes
Reproduced on a test site.

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

The error mesage can be closed by clicking on the "X" next to it.

**Comment by csonnek** [comment]
Another report in https://wordpress.com/forums/topic/error-message-when-editing-posts/?view=all

Note that the site in this example is using a theme that we retired in August 2015.

**Comment by kelasante** [comment]
Another report in 37519418-hc. The user is using the Wilson theme, which is not retired.

**Comment by sdixon194** [comment]
This was the result of some files that weren't removed when the contact form feature was defusioned (to bring the files in sync between atomic and dotcom while allowing them to be developed from a single source). 

Fixed here: D90474-code
Deployed here: r254928-wpcom

You can notify the users that the fix should be out now 👍
