### ISSUE TITLE
Blockbase: cannot edit site title in site editor in Firefox

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#69357]
### Quick summary

When editing the site title in the site editor, it is not possible to make this change in Firefox.

### Steps to reproduce

1. Activate Blockbase
2. Go to Appearance → Editor
3. Try to edit the site title in the header template

### What you expected to happen

It should be possible to edit the site title.

### What actually happened

The site title can be seleteced but not edited:

<img width="573" alt="Screen Shot 2022-10-21 at 3 07 56 PM" src="https://user-images.githubusercontent.com/39252765/197309750-45039f2f-7799-49f3-b49b-2f90788c74eb.png">

### Theme-specific issue?

Blockbase

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Could Not Replicate
- Tested on Self-hosted - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested in Firefox (v. 104.0.2) on simple, AT, self-hosted. I was not able to replicate. I was able to edit the site title in the Site Editor as expected.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
