### ISSUE TITLE
Twenty Fifteen: List Block Indent Not Displaying in Editor on Simple Sites

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#69358]
### Quick summary

When you indent an item using the List block on a page, it does not display the indent in the Editor. You will need to preview or use the list view to see the change. This happens with the Twenty-Fifteen theme on simple sites. 

https://user-images.githubusercontent.com/74204272/197314903-49abfa6c-76ae-45f5-aaff-001e40c27e51.mp4

### Steps to reproduce

1. On a simple site with the Twenty Fifteen theme, add a list block
2. Add list items and indent one item.
3. Nothing seems to happen when you indent. However, when you preview changes, it looks fine. 

### What you expected to happen

To see the indent in the Editor as you do on other themes

### What actually happened

No indication that the indentation worked. 

### Context

User reported this in 37546539-hc / 5650181-zen

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Twenty Fifteen

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

A workaround is to see the indent in the list view or preview changes.

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on P2 - Replicated
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Replicated
- Replicable on Core - Yes


📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/themes/issues/6604
