### ISSUE TITLE
Marketplace: SaaS product redirect, account for buttons in all sites view

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#69367]
In https://github.com/Automattic/wp-calypso/issues/67657 we have added a redirect URL in SaaS plugin pages. We also need to account for all sites view

![Image](https://user-images.githubusercontent.com/12430020/197489326-a08fc713-6eb7-40e6-9d7b-804f0a24f4cd.png)

- Visit `/plugins/test-saas-product`
- Click Manage Sites
- Buttons should redirect to that URL with the specific selected site id

**Comment by epeicher** [comment]
Thanks for reporting this. I created a similar task 
- https://github.com/Automattic/wp-calypso/issues/69329

We can close one of them as they seem to be duplicates
