### ISSUE TITLE
Writing Prompts: add post metadata when responding to a writing prompt

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#69364]
### Description
See discussion p1666258027351339/1666124786.711609-slack-C03NLNTPZ2T

The mobile app writing prompts implementation adds a piece of post metadata `_jetpack_blogging_prompt_key` that links the post to the writing prompt that inspired it.

In order to query across wordpress.com for _all_ posts inspired by a certain prompt, the `post_meta` approach does not scale, so the mobile team added a new table for the v2 project pMz3w-fie-p2

It looks like this table is already used, and there is even an mc page where you can see all responses to writing prompts form the mobile app! 2dfa3-pb/

It looks like In order to get the information into this table we need to use the `add` function in answers.php 2dfa4-pb/

The mobile app is also tagging posts with the #dailyprompt tag pe7F0s-mf-p2#comment-317
### Checklist
- [ ] Set the `_jetpack_blogging_prompt_key` post meta on new posts that are responses to writing prompts
- [ ] Use the `add` function in answers.php or otherwise ensure a new row is added to the table 2dfa4-pb
- [ ] Add the `#dailyprompt` tag to the post

**Comment by roo2** [comment]
cc @creativecoder, it looks like you're doing this as part of https://href.li/?https://github.com/Automattic/jetpack/pull/26680

**Comment by creativecoder** [comment]
@roo2 Yes, that's correct, thanks for connecting the dots! The recent changes to that PR should take care of all 3 items on the checklist for this issue.
