### ISSUE TITLE
Marketplace search: filter for paid products enrolled to the Marketplace

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#69370]
This is a follow-up issue for https://github.com/Automattic/wp-calypso/issues/68219 and also a sub-task of #63905

Even though all WC.com products can be queried from the Marketplace API, not all of them are added to the store. This means that even though the user will be able to see these in search results and categories pages, when clicking through the plugin details page, it won't be possible to install these plugins.

**Comment by cpapazoglou** [comment]
I believe you are referring to filtering all WC.com products by the `wpcom_marketplace_categories` taxonomy so that we retrieve only WordPress.com specific products, right?

**Comment by gcsecsey** [comment]
Yes, that's right. The challenging part here is that we should filter for this field only for WC.com products.

When separately searching for the WC.com blog ID, it's not an issue, this Kibana query returns what we're looking for:
```json
GET jetpack-search-25/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "terms": {
            "blog_id": ["113771570"]
          }
        },
        {
          "exists": {
            "field": "plugin.extra_fields"
          }
        }
      ]
    }
  },
  "_source": false,
  "fields": ["post_id"]
}
```

If we want to also see results from WP.org next to these, the query gets a bit more difficult. We have to either get all results from WP.org or get the filtered results from WC.com. With a bool query it looks like this:
```json
GET jetpack-search-25/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "bool": {
            "must": [
              {
                "terms": {
                  "blog_id": [
                    "113771570"
                  ]
                }
              },
              {
                "exists": {
                  "field": "taxonomy.wpcom_marketplace_categories"
                }
              }
            ]
          }
        },
        {
          "bool": {
            "must": [
              {
                "terms": {
                  "blog_id": [
                    "108986944"
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  },
  "_source": true
}
```

Still, an additional problem is how the ES common API class builds the query. It adds the blog IDs as filters: 2e437-pb/#php

AFAIK adding the blog IDs as filters is important for logging the appropriate blog IDs, but it also prevents us to further customize the filters for some of the blog IDs.

cc @gibrown, could you please help with how could we add additional filters for only some of the blog IDs?

**Comment by cpapazoglou** [comment]
We can also considering filtering the products while indexing. Since only WordPress.com is the consumer of this index it would make sense having only WordPress.com related products.

**Comment by gibrown** [comment]
Your second query looks fine to me. The common API should just wrap the whole query, so I think the query you have above should still work right?

The other thing you could do is move the problem to the indexing side and add a field that indicates whether the plugin is available in the marketplace or not.

**Comment by gcsecsey** [comment]
> We can also considering filtering the products while indexing. Since only WordPress.com is the consumer of this index it would make sense having only WordPress.com related products.

> The other thing you could do is move the problem to the indexing side and add a field that indicates whether the plugin is available in the marketplace or not.

I think this is a more robust way to solve this problem. We already have a `plugin.disabled` field, which uses the meta key with the same name for WP.org plugins and is currently unused for WC.com products:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Scyhtvaf%2Srynfgvpfrnepu%2Svaqrkvat%2Sjcrf%2Qyvo%2Qjcpbz%2Spbzzba%2Spynff.jcrf%2Qjcpbz%2Qcyhtva%2Qcbfg%2Qsvryq%2Qohvyqre.cuc%3Se%3Q3p22208s%2374-og

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Scyhtvaf%2Srynfgvpfrnepu%2Svaqrkvat%2Sjcrf%2Qyvo%2Qjcpbz%2Spbzzba%2Spynff.jcrf%2Qjcpbz%2Qcebqhpg%2Qcbfg%2Qsvryq%2Qohvyqre.cuc%3Se%3Qp2np08s0%2344-og

On the WP.org side, there appears to be no plugin that's currently disabled:
```
gpr select * from wp_108986944_postmeta where meta_key = 'plugin_disabled'
No results found
```

I think we could use this field for this purpose, or we could also create a field called `hide_on_marketplace` or similar.

**Comment by gcsecsey** [comment]
Diff created: D93114-code

**Comment by epeicher** [comment]
I have reviewed the changes and they LGTM

**Comment by gcsecsey** [comment]
Thanks for the quick review @epeicher, the changes are deployed with r256616-wpcom 🚢
