### ISSUE TITLE
Limit Global Styles: Double upgrade banner after launch

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#69371]
We display two upgrade banners in the frontend of launched sites that have limited Global Styles:

![image](https://user-images.githubusercontent.com/1233880/197498806-65b2702e-1b0a-457c-a2df-33f71138f9be.png)

We should either combine them or hide one of them

#### Steps to reproduce

1. Create a free site
2. Add the `wpcom-limit-global-styles` blog sticker
3. Go to Appearance > Editor
4. Open the Styles sidebar
5. Add some changes and save them
6. Launch the site
7. Visit the frontend

#### What I expected

To see only one upgrade banner

#### What happened instead

I see two different upgrade banners, one for hiding the ads, and the other one to make the styles visible

**Comment by mmtr** [comment]
cc @SaxonF

**Comment by SaxonF** [comment]
This is related to recent changes to our marketing bar where we are now sharing that bar to site owners. The marketing bar ("remove this site banner") should sit below the launch bar at the very least. This should be treated as a separate issue as I don't think its related to global styles.

**Comment by rcrdortiz** [comment]
The enhancement is now deployed.
