### ISSUE TITLE
Fix visual issue at upgrade nudge

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#69380]
We expect to have this padding at the upgrade nudge in /plugins page:

![Image](https://user-images.githubusercontent.com/1044309/197531421-dfe09697-ff83-48fa-9078-0acf26a89dcc.png)

Currently, **only at simple sites that were Atomic once**, this is the padding:

![Image](https://user-images.githubusercontent.com/1044309/197531458-45369c24-97b9-49e4-a245-e86ea84cf0f1.png)

**Comment by cpapazoglou** [comment]
Can't repro anymore.
