### ISSUE TITLE
Project: Tailored eCommerce Flow MVP

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#69386]
### Details

This project-level issue is intended as a starting point for our work on improving the eCommerce purchase flow, as per this project thread: paYKcK-2ds-p2

The tasks in the checklist below are drawn from this initial breakdown of the work: paYKcK-2fe-p2

### Checklist

- [x] Initialize new eCommerce Stepper flow behind a feature flag.
  * We should create a new flow concept in Stepper specifically for this new eCommerce entry point, which should only be accessible when a (new) feature flag is enabled in an environment.
  * See #62669 and its associated PR for a similar task from when we migrated the Anchor onboarding flow to Stepper.
  * Completed in https://github.com/Automattic/wp-calypso/pull/69453
- [ ] Implement login/signup step
  * Not originally included in the MVP but required in order to have a functional experience for non-logged-in users
  * Design for this can be found at peapX7-Gb-p2
  * As Saxon noted in Slack (p1666822623964669/1666812328.628779-slack-C0Q664T29), we can make use of existing work from the Link In Bio use case ( https://wordpress.com/setup/intro?flow=link-in-bio&ref=logged-out-homepage-lp )
- [ ] Implement the Store Profiler step - peapX7-Gb-p2#store-profiler
  * This first step as defined in the MVP definition is roughly analogous to some existing Stepper info collection screens but more compact.
  * Data collected in this step should be persisted in the Calypso data store in the same way that we are currently persisting information in other onboarding flows from the “Site Options” and verticals collection screens. The data should also be correctly stored in the WooCommerce configuration.
- [ ] Implement stripped-down design selection step
  * The specific scope is still under discussion, but the designs calls for the use of the [existing patterns step](https://github.com/Automattic/wp-calypso/tree/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/patterns/) from the Link in Bio onboarding flow, which currently shows previews using a tall, narrow, mobile-sized screen rather than a desktop preview
  * The set of themes/designs is also under discussion, but we are currently leaning towards using variations of Tsubaki as a starting point, along with possibly one or two variations of Thriving Artist - see the following thread for more details: paYKcK-2fe-p2#comment-1691
  * Given the ongoing discussions, this task will likely need to be broken down further
- [ ] Add existing domain and checkout steps
  * The final two steps of this new onboarding flow involve having the user select a domain and checkout. Given Stepper’s modular nature, we should be able to almost wholesale incorporate these existing steps into the new flow
  * We should be able to autofill the domain search box with values based on the user’s site name information via the `new` URL parameter along with `search=yes`, as per [this code](https://github.com/Automattic/wp-calypso/blob/c23e3520bfb9fd22aad5f8f17befd6eaccebf6ee/client/signup/steps/domains/index.jsx#L86)
  * The exact implementation may depend on the work to move these components to the Stepper framework - pdDR7T-hL-p2

**Comment by blackjackkent** [comment]
Closed since eCommerce flow initial deployment is complete.
