### ISSUE TITLE
Project: Third-party premium themes

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#69383]
### Details

This issue is intended as a broad tracking issue for the Calypso aspects of this project, with the bulk of the tasks being pulled from paYKcK-2fC-p2, which outlines the remaining work.

Note that for our first iteration we do not plan on adding these themes to onboarding.

#### To verify
- [x] We need to review the subscriptions list and details page are working as expected, especially once we separate out third party premium themes
- [x] We need to review the purchases/receipts list and details page are working as expected, especially once we separate out third party premium themes

#### New work

- [x] We need to map out how we're going to distinguish between first-party and third-party premium themes in various cases, including at least the following:
   * [x] The purchases, subscriptions, and receipts UIs
   * [x] The theme showcase
- [x] We need to work out how we can generate previews for these third party themes, and add the themes to the theme showcase – we likely need to have the theme demo sites on Atomic for this 
- [x] The upsell banner on `/themes/:themeSlug/:siteSlug` needs to correctly specify the Business plan for third party themes; we need to add both the theme _and_ the Business plan to the shopping cart for users on lower plans
- [x] The theme page on `/themes/:themeSlug/:siteSlug` needs to ensure that users _can’t_ purchase the theme directly, but only via a purchase + plan upgrade
- [x] The theme showcase needs to clearly communicate that third-party themes need a subscription and Business plan, and the upsell flow(s) need to communicate that clearly as well
  * This may be addressed by #69046, but we likely have some additional wiring once we know how to identify third-party premium themes

**Comment by markbiek** [comment]
> We need to review the subscriptions list and details page are working as expected, especially once we separate out third party premium themes

I verified that I was able to see both Makoney and the Business plan in my purchases. Cancelling the Business plan also flagged the Makoney subscription for cancellation (after it expires).

**Comment by markbiek** [comment]
> We need to review the purchases/receipts list and details page are working as expected, especially once we separate out third party premium themes

The purchases list and details seem fine as does billing history.

![image](https://user-images.githubusercontent.com/917632/207908371-c26c10e8-f527-47b2-bb5b-9f2d41fcaf72.png)

![image](https://user-images.githubusercontent.com/917632/207908414-8b4db644-c685-42ca-a6c6-922c751a59ad.png)

![image](https://user-images.githubusercontent.com/917632/207908541-f128b4c2-4f56-4f73-88fc-53d120b968d4.png)

**Comment by daledupreez** [comment]
From a technical perspective, all aspects of this are ready to launch, with the exception of one bug-fix in #72072.

I am going to mark the main technical work here as Done and close this issue.
