### ISSUE TITLE
Load Google fonts locally rather than from Google's FDN

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#69395]
### What

Some themes on WordPress.com load fonts from Google's FDN. Even themes where we believe fonts are bundled locally include CSS that comes from Google.

Rather than loading fonts from Google, it would be ideal if these could be locally bundled. 

Full discussion here: p58i-cSr-p2#comment-55762

### Why

Recent GDPR related rulings are causing concerns for users in some EU countries about the legality of fonts loading from Google's FDN.

For AT sites, we can help by disabling Jetpack's fonts module: P9HQHe-20k-p2

For simple sites, there is no current solution other than asking users to upgrade to the Business plan/make their site AT.

We are also starting to receive requests from users who are facing legal requests for site logs related to this.

**Comment by arinoch** [comment]
I'd like to see this assigned to a higher priority, if possible, based on the number of users potentially impacted. For impacted users, I queried the number of Google fonts related tickets I've touched in the last 24 hours. Note: these are only tickets I touched, not all active tickets in the privacy queue.

1. 5659050-zd-woothemes
2. 5659100-zd-woothemes
3. 5659953-zd-woothemes
4. 5660471-zd-woothemes
5. 5660875-zd-woothemes
6. 5660957-zd-woothemes
7. 5661317-zd-woothemes
8. 5658092-zd-woothemes
9. 5658154-zd-woothemes
Again, these are only tickets touched by me, not all active tickets in the privacy queue.

**Comment by gwensmithx** [comment]
I've run into a couple of instances of this today as well:

4758840-hc
5633317-zd-woothemes

**Comment by arinoch** [comment]
More privacy queue fun.
1. 5650989-zd-woothemes
2. 5661462-zd-woothemes
3. 5661568-zd-woothemes
4. 5662822-zd-woothemes
5. 5663226-zd-woothemes
6. 5663273-zd-woothemes
7. 5663496-zd-woothemes
That's so far today. I dive back into the queues and chats later and may find more.

**Comment by youbrokesomething** [comment]
@ianstewart Sorry to ping you so soon after the Marvel announcement. Is this something Ajax or Gannon would be able to look into? Seems like quite a few customers are concerned.

**Comment by sajmes** [comment]
37739159-hc

**Comment by brinbliss** [comment]
5677110-zd-woothemes

**Comment by sajmes** [comment]
5674900-zd-woothemes

**Comment by sajmes** [comment]
5675734-zd-woothemes

**Comment by sajmes** [comment]
5677814-zd-woothemes

**Comment by sajmes** [comment]
5665210-zd-woothemes

**Comment by sajmes** [comment]
5665672-zd-woothemes

**Comment by sajmes** [comment]
5678240-zd-woothemes

**Comment by sajmes** [comment]
5678737-zd-woothemes

**Comment by thekingsprojects** [comment]
5681991-zen

This user previously received a fine for the CDN fonts.

**Comment by sajmes** [comment]
5682219-zd-woothemes

**Comment by sajmes** [comment]
See: https://github.com/Automattic/dotcom-forge/issues/983

**Comment by sajmes** [comment]
5681772-zd-woothemes
5684853-zd-woothemes
5685989-zd-woothemes

**Comment by sajmes** [comment]
5686672-zd-woothemes

**Comment by sajmes** [comment]
5671718-zd-woothemes

**Comment by sajmes** [comment]
5687826-zd-woothemes

**Comment by sajmes** [comment]
5691797-zd-woothemes

**Comment by dhackneya8c** [comment]
5691767-zen

**Comment by jartes** [comment]
5693707-zd-woothemes

**Comment by jromales** [comment]
5701507-zd-woothemes

**Comment by jromales** [comment]
5698404-zd-woothemes

**Comment by jromales** [comment]
5703294-zd-woothemes
5702069-zd-woothemes

**Comment by sajmes** [comment]
5704074-zd-woothemes

**Comment by brinbliss** [comment]
There's some progress regarding rolling out this feature to sites: pMz3w-g6E-p2#comment-103418

**Comment by brinbliss** [comment]
5729786-zd-woothemes

**Comment by jartes** [comment]
5760067-zd-woothemes

**Comment by caimin-j** [comment]
Just noting that the user in 713174-zen is not able to upgrade to Business, so will be forced to cancel their plan. I suspect this will apply to many other users with Simple sites.

**Comment by brinbliss** [comment]
Locally loading Google Fonts is nearly finished for non-Business sites here: p58i-cSr-p2#comment-56325

More information regarding how this change affects users who choose not to upgrade to Business is here: p58i-cSr-p2#comment-56365

It may be safe to close this issue now, pending any delays.

**Comment by obenland** [comment]
Google Font requests from themes should be fixed now for Simple and WoA sites regardless of plan. I'm working on finishing up requests from Custom Fonts and Jetpack's Google Fonts module.

@caimin-j Please see p58i-cSr-p2#comment-56325 for context.

**Comment by eduardozulian** [comment]
5741643-zen

**Comment by obenland** [comment]
Closing as fixed. All changes to host those fonts on wp.com are in production. See p58i-cSr-p2#comment-56325

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group has finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
