### ISSUE TITLE
Show virtual pages UI for other reading settings

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69400]
# Description
Not required for MVP, since it doesn't directly affect the PA flow / PA site setup.

See this comment for content pbxlJb-2OQ-p2#comment-1970

We want to surface the virtual home.html  "page" for these reading settings:

![Image](https://user-images.githubusercontent.com/5665959/197659454-343f8309-69c5-4ce6-9b08-8fc9ae9418b2.png)

This could easily apply to users who go through the PA flow, then later decide to set up a blog page.  

![Image](https://user-images.githubusercontent.com/5665959/197659866-71119cba-6eb3-40b7-bb38-d7fe764e1608.png)

**Comment by autumnfjeld** [comment]
This is a bug as reported by @arthur791004  pbxlJb-2OQ-p2#comment-1978

**Comment by bangank36** [comment]
I think we should check for `homepageId` when `homepageType` is 'page' ( it is 0 when no page is assigned), I'll propose PR for this fix

**Comment by autumnfjeld** [comment]
@bangank36 Reminder to close the corresponding issue when the PR is merged.  I'll close this since https://github.com/Automattic/wp-calypso/pull/69550 is done.
