### ISSUE TITLE
Pattern improvements for MVP 🤞

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69408]
# Description
Pattern quality will be a continual evaluation, but here's some items I'd like to tackel before MVP.  Dependent on help from Ola or another theme designer. 

pbxlJb-2wa-p2

See this [FigJam](KFKxJ6nH1D9tyIh7IqlC8a-fi-202%3A11) 

- [x] Add horizontal padding to the patterns that have full-width without padding.
- [x] Discuss with Ola: how difficult it would be to change the grey to a happy to color. If it is easy, let's do it for MVP.
- [ ] Header pattern with big, bold text https://wppals.com/wp-content/uploads/2021/09/glamour-1.png
- [x] Swap the content patterns for the content wireframe patterns in dotcompatterns. See planning in this figma KFKxJ6nH1D9tyIh7IqlC8a-fi-202%3A42
- [x] ~Only one or two headers should have menu items, or any indication of a multi-site page.~ Instead we decided to simply the menu items, only have "Home" as a menu item, remove "Blog"
- [x] remove custom color on the colored footer pattern

Three places to consider for color change:
* site logo icon
* block background
* image placeholder

----

**Comment by miksansegundo** [comment]
> Swap the content patterns for the content wireframe patterns in dotcompatterns.

I went ahead a few days ago and swapped them in [Pattern Assembler - UI improvements](https://github.com/Automattic/wp-calypso/issues/69362) for testing. Here is the list of wireframe content patterns ordered by function:

1. https://dotcompatterns.wordpress.com/?p=7156
2. https://dotcompatterns.wordpress.com/?p=7153
3. https://dotcompatterns.wordpress.com/?p=7146
4. https://dotcompatterns.wordpress.com/?p=1600
5. https://dotcompatterns.wordpress.com/?p=7149
6. https://dotcompatterns.wordpress.com/?p=7135
7. https://dotcompatterns.wordpress.com/?p=5691
8. https://dotcompatterns.wordpress.com/?p=7143
9. https://dotcompatterns.wordpress.com/?p=737
10. https://dotcompatterns.wordpress.com/?p=7132
11. https://dotcompatterns.wordpress.com/?p=7159
12. https://dotcompatterns.wordpress.com/?p=1585
13. https://dotcompatterns.wordpress.com/?p=789
14. https://dotcompatterns.wordpress.com/?p=5666
15. https://dotcompatterns.wordpress.com/?p=462
16. https://dotcompatterns.wordpress.com/?p=5663
17. https://dotcompatterns.wordpress.com/?p=7140
18. https://dotcompatterns.wordpress.com/?p=7138
19. https://dotcompatterns.wordpress.com/?p=7161
20. https://dotcompatterns.wordpress.com/?p=6712

**Screenshots** (in order too)
<img width="321" alt="Screen Shot 2565-10-26 at 12 03 55" src="https://user-images.githubusercontent.com/1881481/197939615-8985d3d8-3b25-4962-9f55-43632748d074.png">
<img width="319" alt="Screen Shot 2565-10-26 at 12 04 14" src="https://user-images.githubusercontent.com/1881481/197939627-4bbc8813-b6f7-4ff5-8fcb-e5133c87adf7.png">
<img width="322" alt="Screen Shot 2565-10-26 at 12 04 31" src="https://user-images.githubusercontent.com/1881481/197939639-166c8afe-c455-4c46-a7eb-3e12c4f1c3fb.png">
<img width="323" alt="Screen Shot 2565-10-26 at 12 04 49" src="https://user-images.githubusercontent.com/1881481/197939648-60d5a423-b953-4170-97b8-b9a952a6fbd4.png">

**Comment by autumnfjeld** [comment]
As discussed with Ola, we will simplify the menus and remove "Blog".   

Updated menus shown here:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/5665959/198908530-8bf18f42-2fb4-4152-87b4-a44b036a484e.png">

**Comment by miksansegundo** [comment]
There is also a [PR](https://github.com/Automattic/wp-calypso/pull/69570) to show the site title or the text `Site Title` instead of the theme name. 
<img width="467" alt="Screen Shot 2565-10-31 at 11 37 00" src="https://user-images.githubusercontent.com/1881481/198932137-e2631579-383d-4934-942e-16e61b5d8c86.png">

**Comment by miksansegundo** [comment]
And in the same PR, we are replacing the demo site tagline `Blank Canvas is a barebones starter theme, stripped off of content templates but only a footer and a header` with a more generic text `Site Tagline`.

Edited: ✅ Done!

**Comment by miksansegundo** [comment]
<img width="240" alt="Screen Shot 2565-10-31 at 15 52 06" src="https://user-images.githubusercontent.com/1881481/198969131-58eec039-3059-4dbf-86e4-f756e54be228.png">
To show the logo placeholder image in the patterns and site previews, we have to upload it to the new BC demo site. 

Edited: ✅ Done! There is a way to upload the logo from the editor using the Logo block.

**Comment by miksansegundo** [comment]
A reminder about changing the background color of the header pattern https://dotcompatterns.wordpress.com/?p=5316

<img width="1285" alt="Screen Shot 2565-10-31 at 17 17 30" src="https://user-images.githubusercontent.com/1881481/198985480-b3d10d6d-8b3b-4824-9ece-0218f8a26e13.png">

Edited: ✅ Done!

**Comment by miksansegundo** [comment]
Here is the list of patterns with alignment issues related to Blank canvas 3:

- p1668145709229129/1667482926.154089-slack-C02M88KJ684
- p1668425202233199/1667482830.071029-slack-C02M88KJ684
- p1668150092380619/1667483253.329579-slack-C02M88KJ684
- p1668149610672159/1667483147.976649-slack-C02M88KJ684

**Comment by autumnfjeld** [comment]
Going to close this.

Only this item didn't get done, but that's ok:

 Header pattern with big, bold text https://wppals.com/wp-content/uploads/2021/09/glamour-1.png
