### ISSUE TITLE
[Bug]: Users on Atomic sites do not get starter content when switching to a WooCommerce-specific theme

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#69415]
### Quick summary

If a user already has an Atomic site, and they then switch to a theme built for WooCommerce, like Tsubaki or Thriving Artist, they do not get the starter content for the theme on their site, especially the data related to products.

### Steps to reproduce

1. Ensure you have an Atomic site with an active Business or eCommerce plan
2. Switch the theme on your site to either Thriving Artist or Tsubaki, and request that you get the starter content for the theme

### What you expected to happen

The theme should get applied to the site, and the WooCommerce-related setup should be applied to my site, especially the products and product-related fields like Product Categories.

### What actually happened

Only limited starter content is applied to the site.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Users can use some of the patterns from the theme to recreate part of the site, but this is _way_ more difficult to do for most users.

**Comment by sixhours** [comment]
Given the complexity of headstarting atomic sites, and the risk of overwriting a user's existing content with placeholder content, I'm closing this as wontfix.
