### ISSUE TITLE
Make the newsletters branch run on a WPCOM Simple site

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69412]
We want to make https://github.com/Automattic/jetpack/pull/26417 run on a WPCOM Simple site and test it.

WPCOM is running Jetpack and all Jetpack features are features on .com.
Previously, there was a fusion process: PCYsg-fkM-p2
But now they seem to be depracating fusion: pdWQjU-3E-p2

It will require digging into what is the Jetpack release process nowadays and how to run the branch. @oskosk may help you

**Comment by n3f** [comment]
Some informative posts:

* The Future of Development: pdWQjU-77-p2
* jetpack rsync – Test your branches on ...: pdWQjU-6L-p2

**Comment by n3f** [comment]
The `jetpack rsync` command works great and I tested on WPCOM with a sandboxed site...
