### ISSUE TITLE
Marketplace: Plugin details logged out iteration

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#69410]
As per pdgAPm-yE-p2#comment-568, the following changes need to be applied to the Plugin Details page:

- [x] Change the main CTA (on the sidebar) to “Get Started,” also taking users to /start with the Business Plan pre-selected - #69641
- [x] Update the marketplace footer to the page - https://github.com/Automattic/wp-calypso/pull/69557
- [x] Add the standard global header to the page
- [x] Add the standard global footer to the page - https://github.com/Automattic/wp-calypso/pull/67706
- [x] How to approach the wording `Free` on the unlogged experience - https://github.com/Automattic/wp-calypso/pull/69754
- [x] Breadcrumb distance to plugin information - https://github.com/Automattic/wp-calypso/pull/69767
- [x] Styling issues (padding and font-size) - #69770

Figma: f84fqtCG4pCnCh2Hq0But5-fi

**Comment by cpapazoglou** [comment]
@WBerredo can you hash out what needs to be done here from pdgAPm-yE-p2?

**Comment by WBerredo** [comment]
This task still needs design, after the initial drafts we can draw up a plan of how to tackle those. At this time, I'll be filling in the description of this task to reflect our efforts.

**Comment by WBerredo** [comment]
The overall work was described here:  pdgAPm-yE-p2
