### ISSUE TITLE
Test the newsletters branch and review everything

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69411]
We want to test https://github.com/Automattic/jetpack/pull/26417 and see:

- What can we improve
- What can we make better
- What does not make sense

The goal is to:
1. Improve testing instructiosn
2. Find new tasks

**Comment by romarioraffington** [comment]
1. I'll add tasks to the board as I see issues/improvements. I'll also take the time to fix issues as they come up
2. I'll also add  comments to the [PR](https://github.com/Automattic/jetpack/pull/26417) as I see code improvements

**Comment by romarioraffington** [comment]
### Possible Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/69525
- [ ] https://github.com/Automattic/wp-calypso/issues/69524
- [ ] https://github.com/Automattic/multiwoo/issues/972

**Comment by romarioraffington** [comment]
I think we can close this for now
