### ISSUE TITLE
“Add paid plan” button doesn’t update once a paid plan is added

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69414]
In https://github.com/Automattic/jetpack/pull/26417 we introduced an "add paid plan" button that lets you add a new plan in the subscribe block.
When you already have plans, it should show "edit plans". I remember we tested it and it was always "add" but that may have been since fixed.

**Comment by romarioraffington** [comment]
Appears to have been fixed. 

<img width="1794" alt="Captura de Pantalla 2022-10-25 a las 14 11 26" src="https://user-images.githubusercontent.com/7076981/197861323-2ac5b626-3154-4b34-81f6-ca6486cab7f4.png">


#### TODO
- [x] We should change the URL to not open the "Add a new payment plan" modal when the "Manage Plan" button is clicked
- [x] We should change the text above the "Manage Plan" button from "Set up a paid plan for readers to access your content." to "Manage your paid plan" or something to that effect

**Comment by romarioraffington** [comment]
Fixed in [5190449](https://github.com/Automattic/jetpack/pull/26417/commits/51904490012f4e4d2f1654984fd0d771cd615828) and respectively and [7be115d](https://github.com/Automattic/jetpack/pull/26417/commits/7be115d4a353bd3039732349287ae3e169d206ab)
