### ISSUE TITLE
Task: Identify third-party themes in APIs that drive the theme showcase

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#69420]
### Details

We need to ensure that we have a way to represent third-party themes in the themes APIs that drive the theme showcase.

This task is fairly broad and may require multiple changes, but the core goal is to make sure that we tackle a few closely related work items.

### Checklist

- [ ] Ensure that we identify third-party themes in the themes APIs -- D90272-code should provide pretty good prior art
- [ ] Ensure that our client-side code in Calypso that processes the responses from above handles the new field(s) and represents the field(s) in their data models
- [ ] Ensure that locations like the theme showcase and design picker filter third party themes out prior to us launching the relevant feature flags

### Related

#69383

**Comment by markbiek** [comment]
Initial plan is to add a `theme_source` property which can (currently) be either `first_party` or `third-party`. Then we'll have a helper function which is `isThirdPartyTheme`.

**Comment by markbiek** [comment]
First pass diff: D90663-code

**Comment by markbiek** [comment]
P2 for implementation discussion: paYKcK-2hP-p2

**Comment by markbiek** [comment]
D90663-code has been landed and deployed!

**Comment by markbiek** [comment]
Reopening to debug the error described in p1666876390257529-slack-C4N88L95W

**Comment by markbiek** [comment]
Fixed and deployed in D90887-code
