### ISSUE TITLE
[UI] Create Email Opens summary card on stats dashboard

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#69431]
The stats dashboard lives on https://wordpress.com/stats. It displays stats cards with filtered by the period/date you select in the timeline. The goal for this tasks is to create an Email Opens card on the dashboard, consuming data from the mock endpoint created on this patch: D90605-code

The card can be similar to the example below, row actions are out of scope for this task.

![Image](https://user-images.githubusercontent.com/3113712/197819672-5c24f16c-20fe-44b4-9f62-6d785847cda2.png)

- [ ] Create the UI component on Calypso
- [ ] Wrap the component under a feature flag

**Comment by JuanLucha** [comment]
Fixed on https://github.com/Automattic/wp-calypso/pull/69526
