### ISSUE TITLE
Image Editing Options Stopped Working

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#69441]
### Quick summary

Image editing options on the media library stopped working.

### Steps to reproduce

1. Go to your site's media library
2. Select one image
3. Click on Edit
4. Click on Edit Image (site needs to be Public)
5. Click on Crop and select part of the image, click Done to save the changes

### What you expected to happen

For the cropped image to save.

### What actually happened

It seems it's saving, but it goes back to its original.

### Context

None of the editing options seem to be saving, Crop, Flip, Rotate, it always go back to its original.

Here's an example with Crop:

![cropping-images](https://user-images.githubusercontent.com/16104522/197832037-822a30a5-7e28-4247-9eb7-59dbde962129.gif)

Reported on 37556973-hc

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Not difficult, but might be tricky for some users. The editing options seem to still work from WP-Admin.

**Comment by sophiegyo** [comment]
I had another chat for this: 37653854-hc

In my chat I was able to flip an image on my own test site in wp-admin only, but not crop it effectively. The user could not crop either in Calypso or wp-admin.

**Comment by vykes-mac** [comment]
I'm able to reproduce this and looking into it.

**Comment by donalirl** [comment]
Found in #36964488-hc. Suggested Image block cropping tool as a workaround. No follow-up required.

**Comment by ai2n** [comment]
Ditto #34498112-hc

**Comment by msilbers** [comment]
reported in #6615371-hc

**Comment by Jaykame** [comment]
Reported in #37135023-hc
The workaround of wp-admin did not work so I suggested user use the image cropping tool as an alternative but user does not like the workaround.

They would like a follow-up to when this is resolved.

**Comment by tanjoymor** [comment]
Another case 37781128-hc

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this in Calypso. Cropping in WP Admin worked as expected.
- Looks like it's already being worked on based on [this comment](https://github.com/Automattic/wp-calypso/issues/69441#issuecomment-1293935005).

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by vykes-mac** [comment]
There's a fix attached that's currently being reviewed.

**Comment by gwensmithx** [comment]
Hey all, was the fix deployed? I've run into this issue again today and can repro it - #5687453-zen I'll ping since this has been closed. I didn't want to reopen it in case the fix hasn't actually been deployed yet but is scheduled to. @vykes-mac @samiff

**Comment by samiff** [comment]
Hey @gwensmithx 👋 

The fix mentioned in https://github.com/Automattic/jetpack/pull/27224 has not been deployed just yet on WordPress.com. That should be happening soon however, see internal: p9o2xV-2zl-p2#comment-6573

**Comment by samiff** [comment]
@gwensmithx The fix in https://github.com/Automattic/jetpack/pull/27224 has now been deployed to wpcom
