### ISSUE TITLE
Checkout: Pricing for products with introductory offers is displayed in a confusing way

### ISSUE THREAD

**Issue by pablinos** [Automattic/wp-calypso#69456]
### Quick summary

We have an introductory offer for Jetpack Social that is $1 for the first month. At the end of the month, the plan renews and the customer is charged for the other 11 months at full price.

For the annual plan, this is being displayed at the top of the checkout page as if it's $1 for the whole year.

![image](https://user-images.githubusercontent.com/96462/197894694-d3ed3469-86dc-47ac-b851-63341bc204d2.png)

We do explain things in the disclaimer text further down the page, but some customers might be under the impression that they are receiving a whole year for $1.

![Explanatory text](https://user-images.githubusercontent.com/96462/197894590-2b8b4f5d-f9a6-4db8-964f-0dab0556dddf.png)

### Steps to reproduce

- Start at cloud.jetpack.com/pricing
- Click 'Get' next to the Social plan.

### What you expected to happen

That the checkout would better indicate that you are paying $1 for the first month and that you will pay more like $111 for the year.

### What actually happened

The checkout displayse the annual price as the introductory one of $1

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by DavidRothstein** [comment]
This was greatly improved in https://github.com/Automattic/wp-calypso/pull/71016 and now looks more like this:

![Screenshot from 2023-02-14 12-54-57](https://user-images.githubusercontent.com/235183/218818651-5b4a6082-38ca-4077-afe7-efa3f122c726.png)

Further improvements are also tracked in https://github.com/Automattic/wp-calypso/issues/71633 so I think we can probably close this.
