### ISSUE TITLE
Task: Update the banner on the theme page for third-party themes

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#69468]
### Details

This task involves two closely related changes on the `/themes/:themeSlug/:siteSlug` page.

Note that completion of this task is blocked by #69420, as we need to be able to identify whether a theme is a third-party theme.

### Checklist

- [x] Update the wording on the banner to indicate that users need to upgrade to the Business plan (if they don't already have it) _and_ purchase the theme if they want to use the theme, so there are two cases here:
  * If the user already has a Business plan, call out the cost of the theme subscription (and likely align the term with the plan's term, i.e. monthly/yearly/annual)
  * If the user doesn't have a Business plan, call out that the user will need to upgrade to Business _and_ purchase the theme subscription
  * We may need some clarity on how to handle monthly vs yearly subscription options in the UI. We may want two separate buttons/CTAs, e.g. `| $5/month |` and `| $40/year |`
- [x] Update the click handling logic to ensure that we add the theme subscription to the cart, as well as adding the Business plan when needed

### Related

#69420

**Comment by valterlorran** [comment]
I'm trying to think of a way to organize all the possibilities in the banner, but it seems to me that the best way to do it is to leave a single button as is now and add a modal where the user can choose between monthly and yearly subscriptions. This way, we can add more information. WDYT?
We probably could use the same modal for https://github.com/Automattic/wp-calypso/issues/69470

**Comment by daledupreez** [comment]
I think it may be worth keeping the scope smaller for now. How about the following approach?
1. Let's start by keeping one CTA, and having the downstream flow (and any pricing) match the billing interval for the current plan (if any). If the user has no plan, we may want to default to _monthly_ pricing for Business and the theme -- a free user is unlikely to suddenly pay over $300 based on a theme. That will give us early data on how many people are interested in an upgrade, without major complexity.
2. As a later iteration, we can explore a modal or similar to give users a choice after clicking on the banner. But I think we can keep things simpler for now.

**Comment by markbiek** [comment]
@daledupreez @valterlorran Isn't it true that the user will be able to change the billing frequency once they get to the checkout page? Assuming that's correct, I think that would make the simplified approach reasonable since the user still has an opportunity to change.

**Comment by valterlorran** [comment]
https://github.com/Automattic/wp-calypso/pull/70227 closed this issue.
