### ISSUE TITLE
Task: Update kebab menu on theme showcase for third party themes

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#69470]
### Details

We need to update the menu items in the kebab menu to ensure that we communicate the correct purchase path to users. We may want to use "Subscribe" instead of "Purchase", as the actions are distinct for first-party and third-party themes.

Note that this is blocked by #69420.

![CleanShot 2022-10-24 at 11 30 26](https://user-images.githubusercontent.com/3376401/197981874-c6236e2a-ec19-4733-861a-7b5e3d2a3a81.jpeg)

### Checklist

- [x] If a user already has a business plan, offer them a "Subscribe" option, which will add the premium theme subscription to their cart
   * We will need a way to pick the appropriate term for the subscription (i.e. monthly or annually)
- [x] If a user doesn't have a business plan, the menu item should be "Upgrade and subscribe", or possibly "Upgrade and purchase"
   * As above, we should consider how we can pick an appropriate subscription term

### Related

#69420

**Comment by valterlorran** [comment]
@markbiek I've added a hook to add the theme on the cart and redirect to the checkout. I think it can be useful on this issue.
https://github.com/Automattic/wp-calypso/blob/d52fc044ae0e3c09fb1b4c59712d4614d0a47724/client/state/themes/hooks/use-add-external-managed-theme-to-cart.tsx#L24-L74

**Comment by markbiek** [comment]
The initial menu changes are done. I'm leaving this open so we can go back and update the checkout urls once the backend is further along.

**Comment by valterlorran** [comment]
https://github.com/Automattic/wp-calypso/pull/71191 closes this issue.
