### ISSUE TITLE
Task: Update the CTA on the theme page for third-party themes

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#69480]
### Details

The theme page at `/theme/:themeSlug/:siteSlug` currently has a CTA that depends on the user's current plan, and whether the theme bundles any software. We need to ensure that the CTA correctly handles the case where the user already has a Business plan (or higher), and where the user doesn't have a plan that supports installing a theme.

_Note: completion of this work depends on the completion of #69420._

#### Screenshot

<img width="1222" alt="Screenshot 2022-10-26 at 14 57 47" src="https://user-images.githubusercontent.com/3376401/198034117-b86a0c12-364f-4408-97d5-0dacf0824806.png">

### Checklist

- [ ] If a user has a plan that supports installing themes, then we should show a CTA to subscribe/purchase the plan and the annual/monthly price.
- [ ] If the user doesn't have a plan that allows for plugins, then we should show a CTA to "Upgrade and purchase" both the Business plan and the theme.

### Related

#69420

**Comment by valterlorran** [comment]
Hey Dale, isn't this issue a duplication of https://github.com/Automattic/wp-calypso/issues/69468?

**Comment by sixhours** [comment]
@valterlorran was this closed by #69831 and #69616?

**Comment by valterlorran** [comment]
@sixhours yes!
