### ISSUE TITLE
Social Icons Block: Add Patreon icon

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#69496]
### What

Customer requested the Patreon icon to be [supported on the Social Icons Block](https://wordpress.com/support/menus/social-links-menu/#supported-icons).

37643639-hc

### Why

Customer wants to link to their Patreon icon from the site.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by zdenys** [comment]
I can see Patreon icon with the latest version of Gutenberg: v14.7.3 on Simple Sites:

![KdQPEQ.png](https://user-images.githubusercontent.com/39308239/209930919-a78527eb-a49d-4c99-ae8c-3e2b98c3d63a.png)

Closing this one.
