### ISSUE TITLE
FSE - Persist theme block pattern content through theme switch

### ISSUE THREAD

**Issue by bangank36** [Automattic/wp-calypso#69507]
## Description

This is follow-up for the issue #68427, we are pursuing the solution for persist templates content for all FSE themes, not just focus on BCPA flow like now ( switch from blank-canvas-3 theme to other theme )

### What we've achieved:

*   Persist home page template content & template parts
*   Template content is persisted by create or update post template (wp_template or wp_template_part) of the new theme with the old theme's content

### What we are after

*   Persist the theme's block pattern content, since they are tied to specific theme, upon switching the content of theme's patterns won't be transferred to new theme  
    **Note** that the BCPA uses blank-canvas-3 so it won't be a problem for now since the theme are not children of any theme nor contains any block patterns
*   Persist other templates, not just home page template
*   Improve UI/UX copy

## Reference

*   #68427, phabricator [#69421](https://github.com/Automattic/wp-calypso/issues/69421)

**Comment by bangank36** [comment]
Draft PR is here D90868-code, so far so good, `parse_theme_block_patterns` will parse the `wp:pattern` using regex and replace it with the pattern actual content. One problem is current solution can not get the pattern of parent theme. Come back on this after #69421 is merged

**Comment by bangank36** [comment]
Regarding copy, we found the message on theme switch modal is confusing users when they select not to preserve home page:

`After activation, you can still access your old homepage content under Pages -> Drafts`

I think we should check for current homepage settings in Reading option to update the message accordingly

![Screenshot on 2022-11-01 at 11-27-46.png](https://cdn-std.droplr.net/files/acc_1243635/LcqEBl)

**Comment by arthur791004** [comment]
@bangank36 I thought this feature is important, so I made a change based on D90868-code and did a bit refactor to avoid duplicate code. See D91764-code

**Comment by arthur791004** [comment]
Close it via D91764-code
