### ISSUE TITLE
Make the test_refresh_token_endpoint_works_with_login_code test work

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69513]
D89966-code introduced a new test_refresh_token_endpoint_works_with_login_code test.
The test is currently skipped because the line:
```
		$api_token_response = $this->call( 'POST', '/v1.1/sites/' . get_current_blog_id() . '/memberships/token/refresh', [ 'login_code' => $code, 'email' => $email ] );

```

Somehow PRINTS the response instead of returning it, which is peculiar.
I tried using `ob_buffer` to capture that response, but it would sometimes also catch warnings from other test suites and not return valid JSON.

The scope of this task is to make this test to work. If there is an upstream error in that endpoint causing this, we need to fix it as well.

**Comment by n3f** [comment]
In my testing I'm seeing a totally different chain of events.  The api token response returns, however the JWT dosen't had any subscription information:

```
Array
(
    [iss] => http://wordpress.com/earn
    [sub] => 3
    [user_id] => 3
    [blog_sub] => not_subscribed
    [subscriptions] => Array
        (
        )

)
```

Will continue to dig, but I'm not familiar enough to know what it should be or what's off without deeper knowledge.

**Comment by n3f** [comment]
Problem was easier than expected: D91124-code

> **Note**
> Seems the test was missing a mock.

**Comment by millerf** [comment]
The diff was landed
