### ISSUE TITLE
Warning is confusing when uploading theme zip file on a simple site

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#69522]
![theme](https://user-images.githubusercontent.com/6586048/198301828-cf142771-8701-46d4-9f3b-ac9c8b540827.png)

Acceptance criteria:

- [ ] Adjust the copy to something unconfusing

**Comment by candy02058912** [comment]
Slack discussion: p1666877882426619-slack-CKZHG0QCR

Change to “When you install a plugin or a theme…“

**Comment by cpapazoglou** [comment]
Patched in D97460-code

**Comment by cpapazoglou** [comment]
Deployed r259091-wpcom
