### ISSUE TITLE
Make confirmation code UI match the rest of the UI, validate errors

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69520]
D89966-code introduced a UI for a confirmation code to confirm if user is indeed who he says he is.
See row E in  pbOQVh-2wm-p2 to understand why.

The confirmation code UI does not match the rest of the subscribe UIs as they were recently redesigned:

![image](https://user-images.githubusercontent.com/3775068/198274628-be248213-c911-48f0-baf2-bdd0d1fc33c7.png)

The scope of this task is to:
- Make the UI match the rest
- Make sure the error states are handled correctly.

**Comment by artpi** [comment]
Also @millerf says that any code passes, which should not be the case:
> AND ANY CODE WAS VALID

**Comment by artpi** [comment]
Sharing here what I shared on Slack:

1. We need to make header consistent with other screens. Here for example, it has a customization passed in for site logo and title:
![image](https://user-images.githubusercontent.com/3775068/199473942-e211c9a5-31e7-4b52-974d-1970a8d56fe0.png)

2. We need to make button respect the color from customization:

![image](https://user-images.githubusercontent.com/3775068/199474003-b72b9fcd-f268-4403-a496-2e2b72654a9d.png)

3. Header needs to be in proper place like here:

![image](https://user-images.githubusercontent.com/3775068/199474061-ff81bccf-4e36-4bfe-b8f5-9864d5a77cc4.png)

4. I have a vagu memory padding was off when typing in numbers, but i may be wrong

D88349-code should be a good background

**Comment by millerf** [comment]
Fixed in D91413-code

**Comment by millerf** [comment]
Adding another separate task to fix the return whenever the code is wrong. So far it will display the thank you page because something is off with `WPCOM_JSON_API_Endpoint` (see [this slack comment](p1667398923957349-slack-C01B6KEJ5GE))

**Comment by n3f** [comment]
@millerf , not sure if you're still working this or not.  I can take a swing at it (on Monday) if you don't update this before then...

**Comment by millerf** [comment]
I thought it was merged... I just need to review to ship it.

**Comment by artpi** [comment]
@millerf we are waiting for your deploy :)

**Comment by artpi** [comment]
This is done now
