### ISSUE TITLE
Fix visual issue at plugin categories zIndex

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#69528]
Context: pdh6GB-1Vu-p2#comment-3097

At the [/plugins page](https://wordpress.com/plugins), when scrolling the categories up, we have a zIndex problem.

What we currently have:

![Image](https://user-images.githubusercontent.com/1044309/198355529-92c38ba2-0ad8-4279-8a76-661db43a6219.png)

What we expect:
It should display behind the master header.

![Image](https://user-images.githubusercontent.com/1044309/198355633-52d56519-d95e-4766-8c3a-3930b2865958.png)

**Comment by epeicher** [comment]
Backlog grooming: List of `z-indexes` here: https://github.com/Automattic/wp-calypso/blob/c06835a4fbdc4dbfd39b1b1b73725b03af298229/client/assets/stylesheets/shared/functions/_z-index.scss#L33
