### ISSUE TITLE
Email verification links not working for WordPress.com email change

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#69533]
### Quick summary

I was able to replicate an issue with the email verification link not working for a WordPress.com account email change.

### Steps to reproduce

1. Go to Account Settings: https://wordpress.com/me/account
2. Change the account email, then click Save account settings.
3. Check the inbox for the new email address.
4. Click the verification link.

### What you expected to happen

I would expect the email change to be confirmed when I click the verification link.

### What actually happened

The change is not confirmed and the link redirect to a WordPress.com login screen if logged out, or the account settings page if logged in.

### Context

Reported by a user in chat: 37663437-hc
They tested with multiple emails and I was able to replicate on my test account with multiple emails and devices.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

It is possible for HEs to manually change the email address.

**Comment by jamiepalatnik** [comment]
Further testing in this thread: p1666894133097139-slack-C02FMH4G8

It looks like this issue may only happen when you attempt to open the verification link in a browser that is not logged in to the WordPress.com account you are trying to change.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

**Test 1 - Chrome Version 107.0.5304.87 on MacOS 12.5.1** 
- Non superadmin account
- Changed email address within Chrome
- Cleared Chrome cache and opened new session
- Opened new email address, clicked email link to confirm change
- Logged in to WordPress.com 
- **Email is now changed, as expected**

**Test 2 - Safari Version 15.6.1 on MacOS 12.5.1**
- Same non-superadmin account
- Changed email address back to previous, within Chrome
- Quite Chrome and opened Safari
- Logged out of WordPress.com
- Opened new email address, clicked email link to confirm change
- Logged in to WordPress.com
- **Email is changed again**

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
- leaving a note on the original slack thread noted above as well, in case there's more my tests didn't cover.
