### ISSUE TITLE
Stats: Audit and replace Gridicons with Gutenberg icons where viable

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#69530]
Wherever possible, replace Gridicon usage with [@wordpress/icons](https://www.npmjs.com/package/@wordpress/icons).

**Comment by jsnmoon** [comment]
@jeffgolenski and I discovered that the icons used in our designs might be the same as the ones included in [@wordpress/icons](https://www.npmjs.com/package/@wordpress/icons).

**Comment by jsnmoon** [comment]
Sorry for the false alarm, I don't think we need to manually import any SVGs since we can use @wordpress/icons. Closing this issue for now.

**Comment by jsnmoon** [comment]
I spoke too soon, we do need to import the "Visible" (👁️) icon:

```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule=“evenodd” clip-rule=“evenodd” d=“M4.0001 13C4.67092 13.3354 4.67078 13.3357 4.67066 13.3359L4.67346 13.3305C4.6767 13.3242 4.68233 13.3135 4.69036 13.2985C4.70643 13.2686 4.73209 13.2218 4.76744 13.1608C4.83819 13.0385 4.94741 12.8592 5.09589 12.6419C5.39361 12.2062 5.84485 11.624 6.45484 11.0431C7.67357 9.88241 9.49767 8.75 12.0001 8.75C14.5025 8.75 16.3266 9.88241 17.5454 11.0431C18.1554 11.624 18.6066 12.2062 18.9043 12.6419C19.0528 12.8592 19.162 13.0385 19.2328 13.1608C19.2681 13.2218 19.2938 13.2686 19.3098 13.2985C19.3179 13.3135 19.3235 13.3242 19.3267 13.3305L19.3295 13.3359C19.3294 13.3357 19.3293 13.3354 20.0001 13C20.6709 12.6646 20.6708 12.6643 20.6706 12.664L20.6702 12.6632L20.6693 12.6614L20.6667 12.6563L20.6588 12.6408C20.6522 12.6282 20.6431 12.6108 20.6315 12.5892C20.6083 12.5459 20.5749 12.4852 20.5311 12.4096C20.4437 12.2584 20.3146 12.0471 20.1428 11.7956C19.7999 11.2938 19.2823 10.626 18.5798 9.9569C17.1736 8.61759 14.9977 7.25 12.0001 7.25C9.00252 7.25 6.82663 8.61759 5.42036 9.9569C4.71785 10.626 4.20033 11.2938 3.85743 11.7956C3.6856 12.0471 3.55654 12.2584 3.46909 12.4096C3.42533 12.4852 3.39191 12.5459 3.36867 12.5892C3.35705 12.6108 3.34797 12.6282 3.34141 12.6408L3.33346 12.6563L3.3309 12.6614L3.32997 12.6632L3.32959 12.664C3.32943 12.6643 3.32928 12.6646 4.0001 13ZM12.0001 16C13.9331 16 15.5001 14.433 15.5001 12.5C15.5001 10.567 13.9331 9 12.0001 9C10.0671 9 8.5001 10.567 8.5001 12.5C8.5001 14.433 10.0671 16 12.0001 16Z” fill=“white”/>
</svg>
```

**Comment by keoshi** [comment]
Exactly, @jsnmoon — that's the only one that's not part of the WP icon library. Design will work with .org to see if we can add it to the library to avoid importing one-off SVGs.

**Comment by jsnmoon** [comment]
Got it! I'll slide this task into the backlog then.

**Comment by kangzj** [comment]
Just want to add, the Calypso Gridicon has some CORS issues in CDN environment, and I had to add [a component without assets](https://github.com/Automattic/wp-calypso/blob/b2ec1063e45499748ffb602ea7bff48b9ec69630/packages/components/src/gridicon/no-asset.tsx) and [load them separately ](https://github.com/Automattic/jetpack/blob/6618b0d48c8343ced6e8cf3cedca30bf9177779d/projects/packages/stats-admin/src/class-dashboard.php#L91).

If we could replace it, we'll be able to remove the hack, but note, there are dependencies other than Stats which relies on it.
