### ISSUE TITLE
[Bug]: When I scroll the list of pages they disappear until more have loaded

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#69559]
### Quick summary

For sites with a lot of pages, when additional pages load, the list of pages disappears for a moment while the rest load:

![page scroll](https://user-images.githubusercontent.com/275961/198562874-2a6dc20e-1520-4795-aa11-ca558f85b6c2.gif)

### Steps to reproduce

1. Open a site with a lot of pages (try https://rootstofruitstaging.wpcomstaging.com/)
2. Open the list of all pages in the admin
3. Scroll down
4. Notice that the list of pages disappears for a bit

### What you expected to happen

The additional pages should be added at the bottom without removing the list.

### What actually happened

The list disappears while more load.

### Browser

Google Chrome/Chromium

### Context

Building a site

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by vajrasar** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
The screenshot on the report is the same one I get on both the Simple and AT sites. 

This feels like a "feature not bug" at the moment, but pushing to Triaged for the respective team to check. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by scruffian** [comment]
This doesn't feel like a feature when you use it!

**Comment by zaguiini** [comment]
@vajrasar is it a feature, though? Sounds like a bug to me 🤔 I can't think how I might benefit from this type of behavior...

**Comment by mpkelly** [comment]
To me, this is a bug and can easily be reproduced using the Field Guide. We have infinite scroll on the posts list, but it doesn't have this problem. I will try and fix it now.
