### ISSUE TITLE
Invitations Failing to Send

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#69574]
### Quick summary

Some users cannot invite users to their site. They receive a message of `Sorry, we couldn't process your invitations. Please try again later.` or a message saying `Invitation failed to resend.`

[P2 here](p2EDhh-1K6-p2) p2EDhh-1K6-p2 with more cases.

### Steps to reproduce

1. Go to Users
2. Invites
3. Click Invite
4. Invite user, set a role and click "Send Invitations".

I cannot reproduce this on any of my test sites. I tested on both Simple and Atomic sites.

### What you expected to happen

To receive a success message.

### What actually happened

Received a message of `Sorry, we couldn't process your invitations. Please try again later.` or a message saying `Invitation failed to resend.`

![Annotation on 2022-10-28 at 10-05-39](https://user-images.githubusercontent.com/93800099/198637525-0208eb64-bed7-4b52-8e40-badc4b92fd0c.png)

![Annotation on 2022-10-28 at 10-06-52](https://user-images.githubusercontent.com/93800099/198637668-f1c79219-9beb-4ce4-957e-341fb90ced90.png)

### Context

37666047-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Intermittent

### Severity

Some (< 50%)

**Comment by Nic-Sevic** [comment]
To add more details here: If you revoke an invite that failed and attempt again, even if you get the message `Sorry, we couldn't process your invitations. Please try again later.` the invite will show up in the invite list (you have to refresh the page).

On these we're also seeing network errors like 
`{"code":404,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"unknown_invite","message":"The requested invite was not found."}}` as a response to `https://public-api.wordpress.com/rest/v1.1/sites/145213789/invites/new?http_envelope=1&locale=zh-tw` with a status of 500

and `?v=2.0:16  POST https://public-api.wordpress.com/rest/v1.1/sites/145213789/invites/c8e689964c0d01fb07e9773daecd2e34/resend?http_envelope=1&locale=zh-tw 500 `


Of the three sites one let me successfully send an invite to my test email and the other two wouldn't let me send anything.
Site that let me send Blog ID: 73433122

**Comment by zdenys** [comment]
I've reported my recent case on this other bug report from 2021 where I see 4 new reports from the past few days:
- https://github.com/Automattic/wp-calypso/issues/56758

We've had a spike of new cases of this issue over the past few days. By just looking at tickets, I could find these:
- 5664700-zd-woothemes
- 5665623-zd-woothemes
- 5665813-zd-woothemes
- 5658228-zd-woothemes
- 5665936-zd-woothemes
- 5664292-zd-woothemes
- 5654928-zd-woothemes
- 5659839-zd-woothemes

I've asked here p1667034449730479-slack-C02FMH4G8

**Comment by cuemarie** [comment]
A fix for this issue was deployed here: D91167-code (Deployment reported here: p1667210573582539/1667034449.730479-slack-C02FMH4G8 )

While there was a spike in recent user reports noted above, many of those tickets are solved. Will check in with others as to whether this merits a bulk reply to impacted users.
