### ISSUE TITLE
Site Editor - Update close button URLs for Gutenberg 14.5

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#69572]
Gutenberg 14.5 will remove the `MainDashboardButton` slot/fill and replace it with a `dashboardLink` setting instead. Relevant changes can be found in [this PR](https://github.com/WordPress/gutenberg/pull/45149). Note 14.5 is not currently available and probably will be on edge some time next week, until then you can sync a Gutenberg build with the above changes to your sandbox for testing.

* When 14.5 lands on edge, we will need to populate this `dashboardLink` setting appropriately.
* Once 14.5 is on production and stable, we can get rid of our previous uses of the Site Editor's `MainDashboardButton` (Not to be confused with the slot/fill from the post-editor package of the same name). I believe this is only used in 2 places similarly: [iframe-bridge-server](https://github.com/Automattic/wp-calypso/blob/c2ebef6bf5243953d47b000a8e4cc560e5f95c85/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L462) and [wpcom-block-editor features](https://github.com/Automattic/wp-calypso/blob/fd70c514b2dd235a7a2bf481b5eb61e7d7ea95ca/apps/wpcom-block-editor/src/wpcom/features/override-edit-site-back-button.js#L16) with the former probably being redundant anyways after the addition of the latter.

We should keep the solution away from the iframe-bridge-server as this doesn't work in wp-admin and is planned to soon be removed.

**Comment by mattwiebe** [comment]
This was closed by #69929
