### ISSUE TITLE
Marketplace: Add two additional WC.com fields to Product Extra Fields meta

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#69584]
The following two fields are not synchronised to WP.com and they are returned by the `/marketplace/products` endpoint so they could be included in the `wpcom_marketplace_product_extra_fields` meta currently saved in WC.com database:

- `_demo_url`
- `_documentation_url`

They are the only missing fields required to be able to get from Elasticsearch results the same values currently returned by `/marketplace/products`. More context here
- https://github.com/Automattic/wp-calypso/issues/64891#issuecomment-1239440175

As the other fields are already included in the `wpcom_marketplace_product_extra_fields`  field

This task will be used to either include those fields in `wpcom_marketplace_product_extra_fields` or find an alternative way to synchronise them to WP.com

As a fallback, they can be added to the [`postmeta_to_sync` collection](https://github.com/Automattic/jetpack/blob/4e48555eec5fcd2e092236bd3d81bb3eca54f6c6/projects/packages/sync/src/modules/class-search.php#L70) and fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Sflap%2Spynff.wrgcnpx%2Qflap%2Qzbqhyr%2Qfrnepu.cuc%3Se%3Qs550q181%26sv%3Qchoyvp_cbfgzrgn%2348-og

This task is required by 
- https://github.com/Automattic/wp-calypso/issues/64891

**Comment by cpapazoglou** [comment]
We can modify the post save handler so that it includes other collection of fields too. @JulianBustamante  can you confirm?

**Comment by epeicher** [comment]
Adding to the original description, this action `woocommerce_admin_process_product_object` is the one that could be used to listen for modification of the fields.  
And that is effectively already handled by the Marketplace logic [here](https://github.com/Automattic/woocommerce.com/blob/ce9bf6a5c282c838e68cf40c509c982eccaaec5c/plugins/wccom-plugins/wpcom-marketplace/wpcom-marketplace.php#L160) so it can be used to update the `wpcom_marketplace_product_extra_fields` with those two new fields.
