### ISSUE TITLE
Connection options for Publicize can't be changed in classic editor

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#69589]
### Quick summary

Connection options for Publicize can't be changed in classic editor but can be changed in block editor
Seems like active connections are still being automatically added but the user can't choose to add or remove connections before publishing

### Steps to reproduce

1. On a simple or atomic site make sure that some connections exist for publicize (if Atomic site you also need to make sure publicize is active)
2. open a post in the block editor and confirm you can change the connection toggles in the Jetpack section
3. open a post in the classic editor and see that you can't change the selections in the edit menu of the Jetpack Social section

### What you expected to happen

Should be able to select/unselect which connections are published to regardless of editor

### What actually happened

Can only change connections selected in Block editor

block editor:
![2022-10-28 at 14 00](https://user-images.githubusercontent.com/47717887/198712293-1051b3d4-17b2-4382-9d93-15ecb28a2ae4.jpg)

classic editor:
![2022-10-28 at 13 58](https://user-images.githubusercontent.com/47717887/198712201-e75da360-9716-4120-b6ef-c8acafeed501.jpg)

### Context

36849215-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

no

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The user can make changes in the block editor before publishing the post. They need to take care though as switching between classic and block editor can sometimes break things/create broken blocks

**Comment by tvolpert** [comment]
looks like another instance here. I advised them to switch to the Block Editor for now when they're ready to publish their posts

- [ ] 36325850-hc

**Comment by CodeAllNightNDay** [comment]
Cases here:
5666937-zen
5667893-zen

**Comment by pablinos** [comment]
I can't access those tickets for some reason, but this was an issue for a few hours on Friday and judging from the time it was reported and the second instance it would have still have been an issue for these customers. 

The fix was deployed around October 29 00:30 UTC. If there are instances after this time then it will need further investigation.

**Comment by pablinos** [comment]
I've gone through all these reports now, and it seems that they were all before the fix was deployed, so everything should be ok now.

**Comment by Nic-Sevic** [comment]
Confirmed that I can no longer reproduce so closing
