### ISSUE TITLE
Help Center: Move lower to not overlap or hide some buttons 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#69599]
### What

In the Domains section https://wordpress.com/domains/manage/ if the Help Center is open, it overlaps with "Site domains" and "Add a Domain" buttons.  In DNS records section https://wordpress.com/domains/manage/example.com/dns/example.com  if the Help Center is open, it overlaps with "Add a record" button. 

### Why

The user was not able to see "Add a record" button when the Help Center was open (37693165-hc). 

### How

"Add a domain" and options in "Add a domain" are covered with the Help Center open: 

<img width="594" alt="Screenshot 2022-10-29 at 2 08 50 PM" src="https://user-images.githubusercontent.com/36863633/198830970-c349fb1d-3d09-4327-bae6-a4dce601f4d2.png">

"Add a record" with the Help Center open: 

<img width="766" alt="Screenshot 2022-10-29 at 2 15 50 PM" src="https://user-images.githubusercontent.com/36863633/198831006-0cd3fbab-b527-4b39-b7fe-c23aa67db2b3.png">

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by escapemanuele** [comment]
I believe this is no more an issues, since we made it more clear that the Help Center is draggable

**Comment by phcp** [comment]
Closing this as it's no longer an issue. As Emanuele mentioned above, there are elements (cursor and icon) indicating that the Help Center is draggable.

https://github.com/user-attachments/assets/6bfc0e55-d2d0-4a58-861c-a333d932183a
