### ISSUE TITLE
Reader: excerpts in summary feeds don't display line breaks

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#696]
Steps to reproduce:

1. Go to WP Admin > Settings > Reading, select "Summary" for feeds, and Save Changes
1. Start a new post at https://wordpress.com/post
1. Add a poem to the body of the post
1. Save and publish
1. View the post in the Reader stream it https://wordpress.com/

<strong>Result:</strong> line breaks are not displayed for excerpts in summary feeds. This causes a problem for poetry formatting.

![screen shot 2015-11-24 at tue nov 24 4 47 29 pm](https://cloud.githubusercontent.com/assets/1119271/11381661/4a85ec94-92cb-11e5-8849-e31119e585a9.png)
<sup>Seen at https://wordpress.com/ on this blog https://wordpress.com/read/blog/feed/40471243 for this post https://wordpress.com/read/post/feed/40471243/872344084 using Firefox 42.0 on Mac OS X 10.10.5</sup>

Sample content:

```
why did you go
little fourpaws?
you forgot to shut
your big eyes.

where did you go?
like little kittens

e e cummings
``` 

/hat tip alexjgustafson for the original report

**Comment by cesarabeid** [comment]
Hey all! I have a user who reported this first in August, we told him we were working on it... He just created a new ticket, showing frustration the issue is not yet resolved.  Do we have an update for him?

**Comment by bluefuton** [comment]
@cesarabeid Thanks for the reminder! I'll add it to our 'UI nits' milestone, which is being worked on now. It should then hopefully be fixed and shipped in February.

**Comment by cesarabeid** [comment]
Thank you @bluefuton! I'll check back in a few weeks for status.  Thank you!!

**Comment by bluefuton** [comment]
@cesarabeid All fixed and deployed - you can feed this back to the user :)

**Comment by cesarabeid** [comment]
Thanks @bluefuton !

**Comment by cesarabeid** [comment]
Just heard back from the user, there's still a bit of an issue.  Here's a poem from his site:
http://d.pr/i/bbgu

Reader is rendering first and second line OK, but merging 3rd and 4th line together:
http://d.pr/i/12USr

User also complaining that text fades out too soon - I think that's a feature of the Reader though.

[Ticket](https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2520941&highlight=--+Mixed+--&ticketsearchid=1076280)

**Comment by blowery** [comment]
For ref, the blog in question is http://calypso.localhost:3000/read/blogs/68015336

**Comment by blowery** [comment]
So, our current rules are that we only show the expanded post when the post is short (less than 100 words) _and_ it doesn't contain any images or embeds. All of these posts contain an image in the body, so we don't show the full post variant inline.

For summary cards, we only show the first three lines, and the fade happens on the end of the container. For stuff like this with short lines, you don't see the fade.

This did highlight an issue with how we're building the excerpts though. I filed #3692 to address that. It preserves the line breaks in this blog, but now it cuts things off after three lines, so it's not much of an improvement. We could try to allow 1 image in a post, but then we also have to suppress it in the content, but only in the stream.

I'm not really inclined to spend more time fixing this, as we're going to start work on a new layout for the posts list pretty soon anyway and we can't customize the feed stream for every kind of post format out there. The summary cards are meant to be summaries, not the full post. If the user clicks through to the full post, they'll see the proper formatting.

**Comment by cesarabeid** [comment]
@blowery This explains a lot. I'll circle back with the user and explain when [#3692](https://github.com/Automattic/wp-calypso/pull/3692) is closed.
