### ISSUE TITLE
Update Site Editor's Welcome Guide slides to mention FSE

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#69607]
# Description

The  Blank Canvas Pattern Assembler onboarding flow, see pbxlJb-2ki-p2 , ends with the user landing in the Site Editor.  The Welcome Tour should be updated to have contextual information related to the Site Editor, as currently it only has content on Block Editing.

Update the copy of these slides on Site Editor.

### Slide 1

<img width="401" alt="image" src="https://user-images.githubusercontent.com/5665959/196617172-bb7cfe78-c3d6-45ec-bf81-19c56eeb6221.png">

to:

> Take this short, interactive tour to learn the fundamentals of the WordPress Full Site editor.

### Slide "Edit your site"

<img width="402" alt="image" src="https://user-images.githubusercontent.com/5665959/196617121-6bc8818f-a543-4b25-9801-9489ca3473e1.png">

to:

> Design everything on your site using blocks  - from the header right down to the footer - in the Full Site Editor. (Learn more)[https://wordpress.com/support/full-site-editing/]

# Acceptance Criteria

- [x] The description is updated as specified above on Site Editor.
- [x] The description is NOT updated on Page / Post Editor.

@Automattic/ganon

**Comment by fushar** [comment]
@autumnfjeld Should it be:

- `Full Site editor` (as mentioned in the original issue description), or
- `Full Site Editor`, or
- `Site editor`

?

Not sure if we ever mention "full site editor" (in whatever capitalization) anywhere else?

cc: @SaxonF

**Comment by autumnfjeld** [comment]
@fushar  These docs use the term "Full Site Editing".   https://wordpress.com/support/full-site-editing/
So let's go with Full Site Editor.

**Comment by fushar** [comment]
This is shipped.
