### ISSUE TITLE
Editor: clicking on site preview from within the Editor opens site in new tab

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#6962]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000
2. Go to My Sites
3. Select a WordPress.com site as the currently selected site
4. Click the site preview (site card near the top of the sidebar, below "Switch Site")
5. Site preview opens within Calypso in an overlay
6. Go to "Blog Posts"
7. Click "Edit" for a blog post
8. Again click the site preview (site card near the top of the sidebar, below "Back")
#### What I expected

Site preview opens within Calypso in an overlay
#### What happened instead

Site preview opens in a new tab

This is inconsistent -- we should use the within-Calypso preview overlay here as well. I'm tempted to call it a bug instead of an enhancement. 

Thanks @meremagee for reporting. 🙇

**Comment by alisterscott** [comment]
It looks like the site card on the editor always opens in a new window now regardless of entry point

**Comment by lsinger** [comment]
The site card isn't a link anymore. Closing.
