### ISSUE TITLE
[Bug]: Write new post in masterbar misaligned when Chrome translates the page

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#69631]
### Quick summary

When Google Chrome translates a page, it adds extra markup which then causes issue with the alignment of the new post button in the masterbar.

<img width="1640" alt="Screen Shot 2022-10-26 at 1 10 17 PM" src="https://user-images.githubusercontent.com/1126811/199089018-f2ea06e1-15a9-4f4e-9f8a-ad40f895826e.png">

### Steps to reproduce

1. Go to a non-English local site with Chrome
2. Allow Chrome to translate
3. Notice misalignment

### What you expected to happen

No misalignment

### What actually happened

Misalignment

### Browser

Google Chrome/Chromium

### Other notes

p1666807858943829-slack-C03N25JPCE4

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested in Chrome Version 113.0.5672.63 (current) - **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO

https://user-images.githubusercontent.com/27249804/236068527-d80662b2-fa14-4b7d-b050-c43672e6f2f9.mp4

📌 ACTIONS
- Closed as could not replicate/no longer relevant
