### ISSUE TITLE
Premium Theme: Tazza

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#69644]
### Details

The Tazza premium theme needs the following:

### Checklist

- [x] [Set up the demo site](https://tazzademo.wpcomstaging.com/)
- [x] Theme showcase draft
- [x] Add the theme to the soft-launch filter
- [x] Build a ZIP for the theme
- [x] Add the theme as a product to the Store
- [x] Add the theme to the prices page in MC
- [x] Headstart annotations (don't forget to submit for translation)
- [x] GlotPress Project creation
- [x] Launch process

Cheat sheet: paYKcK-1Pt-p2

Premium theme launch guide: PNEWy-eBM-p2

**Comment by valterlorran** [comment]
Submitted the headstart for translation. ID: 149842

**Comment by markbiek** [comment]
Launched!

![image](https://user-images.githubusercontent.com/917632/204847993-de2049dd-1956-468e-8afb-e0ccad2b9028.png)
