### ISSUE TITLE
Gifting: Limit which plans / sites / purchases see the gifting toggle

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#69646]
Context: https://github.com/Automattic/wp-calypso/pull/69637#issuecomment-1298050124

We only show the gifting toggle on some sites per [this code](https://github.com/Automattic/wp-calypso/blob/ff429e5bb5b4021ac11d12ae8c3d20252399cf91/client/my-sites/site-settings/form-general.jsx#L645) but I'm thinking we should limit this further to only dotcom paid plans excluding e.g. jetpack, p2, domain only etc.

Acceptance:
- [x] ~Determine what sites should see the gifting option in site settings~ Figured this out based on the [wpcomsh impl](https://github.com/Automattic/wpcomsh/blob/56eff066e832a64284937a1d45acab4e9466c69f/frontend-notices/class-wpcomsh-frontend-notices.php#L105-L112)
- [x] Exclude plans like p2 from the [current list](https://github.com/Automattic/wp-calypso/blob/ff429e5bb5b4021ac11d12ae8c3d20252399cf91/client/my-sites/site-settings/form-general.jsx#L645).
- [x] Remove the auto renew check, we now want this setting displayed for all wpcom sites.

**Comment by DustyReagan** [comment]
Do we just need to confirm the plan is one of [these](https://github.com/Automattic/wp-calypso/blob/b2ac371036a0c0e9988ef4b2c7bb3ada9a4f6aa8/packages/calypso-products/src/constants/wpcom.ts#L42-L55) or [these](https://github.com/Automattic/wp-calypso/blob/b2ac371036a0c0e9988ef4b2c7bb3ada9a4f6aa8/packages/calypso-products/src/constants/wpcom.ts#L64-L66)?

**Comment by lsl** [comment]
Need to confirm what sites the feature should apply to.

From my understanding it was only dotcom plans but maybe p2 should be included?

**Comment by lsl** [comment]
Going by this PR, [looks like we exclude p2](https://github.com/Automattic/wpcomsh/pull/1118/files?w=1#diff-0cd1140ab64b12cf731ce339c45d831b963a2e0b6dbb03c2fcff67bacdf7eaf6R108-R112)

**Comment by lsl** [comment]
Updated acceptance to include auto renew restriction removal.

@allilevine / @michaeldcain / @JanaMW27 should we be including p2 plans in gifting?

**Comment by DustyReagan** [comment]
It just occurred to me this could be a good case for a new site feature. We could probably leverage that feature in `gifting-banner.php` too.

Thoughts on https://github.com/Automattic/wp-calypso/pull/69939 and D92119-code ?

**Comment by lsl** [comment]
Plan feature sounds like a good way to gate this, thanks!
