### ISSUE TITLE
Theme Subscriptions: Fix overlapping logic between theme bundling and third-party subscriptions

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#69660]
Part of #69383

There is a high likelihood that upcoming third-party themes will also have WooCommerce bundled with them.

We need to make sure that we correctly handle UI and logic for themes that are both third-party _and_ bundled.

This means that we need to ensure we're displaying the third-party messaging even if the theme is also bundled. Currently, we seem to default to the bundled messaging.

## Messaging

See #69476 and #69591 for additional details.

- "Upgrade to subscribe" (user has a Free/Personal/Premium plan)
- "Subscribe" (user has a Business plan)
- "This premium theme costs $NN per year and can only be purchased if you have the Business plan on your site"
- "This premium theme is only available while your current plan is active and costs $NN per year."

## Items to check

- Tooltip on the theme showcase (#69591)
- Upsell banner on theme showcase (#69468)
- Kebab menu on theme showcase (#69470)
- CTA on theme page (#69480)
- Upsell banner on theme page (#69468)

**Comment by valterlorran** [comment]
@markbiek, do you know if we will use `theme_software_set` for the marketplace themes? If so, we should consider changing the selector that checks if the theme is bundled:
https://github.com/Automattic/wp-calypso/blob/a90453f239faa80d66490e9afe69818a7d6a77a9/client/state/themes/selectors/does-theme-bundle-software-set.js#L6-L12

**Comment by markbiek** [comment]
> do you know if we will use theme_software_set for the marketplace themes? If so, we should consider changing the selector that checks if the theme is bundled:

I'd love for @daledupreez to confirm but I believe we are _not_ going to be using software sets for marketplace themes.

**Comment by daledupreez** [comment]
I don't believe we will be using software sets for these dependencies, but rather definitions within the back end code so we can handle more complex installation logic.

Also, we may need to create a task to remove the feature flag checks for `themes/plugin-bundling`.
