### ISSUE TITLE
[Paid Newsletters] Subscribe as a new blog subscriber and immediatelly unlock content

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69664]
There seems to be the case where:

- User never subscribed to anything
- Post is for blog subscribers only

These are these flows:
docs.  google.  com     /spreadsheets/d/1zAVGVPn_KbaOy4BopmKkx9q-fGI0b8fn-BTcAWnYfaA/edit#gid=402847350&range=11:12

In the first-blog subscribe we are not properly setting the token for unlocking the content.
Instead, we close the modal BEFORE subscribing and reload the page to unlock content.

Instead, I think we should be:
- Subscribing in the modal instead of through regular Jetpack subscribe flow
- But since we don't wait for the confirmation email, maybe we can also allow folks with `unverified` status for a certain time after subscribing?

## Goal of this task

In the modal hosted on subscribe .wordpress .com :

1. For this case of the user, sign the user up as the blog subscriber in the modal
2. Redirect with the proper JWT token

In the code that unlocks the post in Jetpack / WPCOM 

- Allow `pending` status of blog_sub to unlock content

**Comment by romarioraffington** [comment]
>  maybe we can also allow folks with unverified status for a certain
> Allow pending status of blog_sub to unlock content


Instead of introducing another status. I think we should allow users with the `confirming` statuses to unlock free content.

Based on my testing, the `blogsub=confirming`  and   `subscribe=status `are added as a query param after the flow described for WPCOM and Jetpack respectively.

**Comment by romarioraffington** [comment]
See D92672-code
