### ISSUE TITLE
Domains: Phone number placeholder in invalid format

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#6966]
#### Steps to reproduce
1. Starting from URL: https://wordpress.com/domains/add/example.wordpress.com
2. Select a domain name, either accept or decline GApps
3. Fill out the contact information form
4. Follow the format given for the phone number

#### What I expected
To be able to purchase a domain

#### What happened instead
PR #5813 added a new placeholder for the Phone number field, `+1.555.867.5309`, but if you actually try to input a phone number in that format it gives the error `The last 5 characters of “Phone” must not be a dot.`

#### Browser / OS version
OSX Chrome v51

#### Screenshot / Video
<img width="291" alt="screen shot 2016-07-22 at 10 49 11 am" src="https://cloud.githubusercontent.com/assets/7233112/17060940/2b493920-4ffa-11e6-8ac4-2361dad687bb.png">

#### Context / Source
#manual-testing

**Comment by klimeryk** [comment]
Argh, nice catch. The "five last characters must not be a dot" is a requirement from our external partners. I've added the validation for that around the same time this placeholder was added and I didn't realise they conflicted with each other - thanks for reporting!
/cc @umurkontaci as you are working on improving this field

**Comment by umurkontaci** [comment]
Being tracked in #7453.
