### ISSUE TITLE
Add date followed when sorting by date

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#69665]
## Description

On the manage followed sites screen, when you sort by date followed, we should show the date that you followed the site for each site:

### Before

![image](https://user-images.githubusercontent.com/5634774/199309153-2efa4cc4-46c1-488e-aed8-757b33ee542c.png)

### After

![CleanShot 2022-11-01 at 14 39 12](https://user-images.githubusercontent.com/5634774/199312157-ab245574-9df0-4d64-bca6-c5facd492a0d.png)

## Notes

@creativecoder shared:

> There is a date_subscribed property we track with followed sites, and it’s already returned by the https://public-api.wordpress.com/rest/v1.2/read/following/mine  endpoint used on the /following/manage page

p1667507516925849-slack-C03NLNTPZ2T

**Comment by ollierozdarz** [comment]
Looks good @davemart-in!
