### ISSUE TITLE
LaunchPad - Launchpad stepper page does not stay in browser history.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#69666]
To Repro:
* Go through the standard onboarding flow for newsletters or link-in-bio to get to LaunchPad
* Select the task to take you into the editor ('add links' for LIB or 'write your first post' for newsletters)
* Once the editor loads, click the browser's back button.
* Notice we dont return to the launchpad, but whichever start/stepper page we had previously visited.

This is likely due to use of `window.location.replace` as opposed to `window.location.assign` when navigating to the launchpad.

In the gif below we start at Launchpad -> Personalize -> Launchpad -> select Add links/editor -> hit browser back button -> land back at personalize step instead of launchpad

![no-launchpad-history](https://user-images.githubusercontent.com/28742426/199308804-0a5d1947-80c3-4c21-bef8-a4d3cbb79301.gif)

**Comment by agrullon95** [comment]
Changes for this issue merged: https://github.com/Automattic/wp-calypso/pull/69691
