### ISSUE TITLE
Jetpack SSO: sites with subfolder not being saved properly to state

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#6967]
If i have a site in a subfolder, like  `example.com/wordpress`, only `example.com` is saved to `JetpackSSOSessions`.  Thus during the approval process `issSSO` fails, and I see the 'Approve' button instead of being auto-authorized.

To reproduce:
- create a new user on a Jetpack site that lives in a subfolder
- ensure that you have a corresponding wpcom account that has the same email address
- logout of both jetpack site and wpcom
- login to your jetpack using SSO
- login to wpcom using the corresponding account
- Click 'Login'
- Notice the 'Approve' button instead of being auto-authorized

cc: @ebinnion

**Comment by ebinnion** [comment]
Fixes in #6986.
