### ISSUE TITLE
Navigation Block: Does not indicating submenus on mobile (when items are centered)

### ISSUE THREAD

**Issue by ha-un** [Automattic/wp-calypso#69677]
### Quick summary

When using the Navigation Block to create submenus, the mobile view doesn't indicate which is a submenu. This only happens when the menu items are aligned as center.

### Steps to reproduce

1. Create a site with Munchies theme. (or any theme)
2. Create a menu & add submenus (page links).
3. (If not already), center the menu items.

### What you expected to happen

When the menu items are aligned left or right, the submenus are indented.

<img width="339" alt="Screenshot 2022-11-01 at 5 52 21 PM" src="https://user-images.githubusercontent.com/96960321/199369221-4da8be27-3840-4add-b3fb-4134849c987c.png">

### What actually happened

When the menu items are centered, there is no indication of the submenu.

<img width="361" alt="Screenshot 2022-11-01 at 5 53 12 PM" src="https://user-images.githubusercontent.com/96960321/199369308-16c1aeea-0598-4df1-931d-82f175be069f.png">

### Context

- User report: 37762283-hc
- Follow-up: 5676172-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Started with Munchies theme as a report, but upon testing, it seems like most themes are affected.

### Reproducibility

Consistent

### Severity

One

**Comment by jordesign** [comment]
This is something that could be addressed in core - so I've opened an issue there.
https://github.com/WordPress/gutenberg/issues/45612

**Comment by cuemarie** [comment]
Thanks @jordesign ! This looks like a duplicate of https://github.com/Automattic/wp-calypso/issues/75576 as well, so closing this and will share the Gutenberg request there
