### ISSUE TITLE
Block Patterns not available on the mobile app.

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/wp-calypso#69679]
### What

When trying to add block patterns from the mobile app, we cannot find that option.

The option is available through the web though.

Screenshot from desktop view:

<img width="911" alt="Screen Shot 2022-11-02 at 08 47 18" src="https://user-images.githubusercontent.com/49183855/199388841-d4fe23a6-62a8-47f4-a2ec-a73fef0eb547.png">

Screenshot from the mobile view:
![image](https://user-images.githubusercontent.com/49183855/199388962-e3ae7ed2-eb27-4008-9622-4ab8b889f4a7.png)

User reported this on hc-[37725567](37725567-hc)

### Why

Having block patterns on the mobile apps will help users who use customize their content easily from the mobile as well.

**Comment by zachspears** [comment]
Hello @vinnykaur! Thank you for sharing this feature request. This GitHub repo is targeted toward calypso, please start a new feature request with on the WordPress app repo here: https://github.com/wordpress-mobile/WordPress-iOS

Thanks!
