### ISSUE TITLE
Persist Home template doesn't work on AT sites

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#69686]
After we deployed D89996-code, we're able to persist the Home template when switching themes. However, this doesn't work on AT sites, and we might need to support it.

### Related

* https://github.com/Automattic/wp-calypso/issues/68427

**Comment by okmttdhr** [comment]
Closing as the persisting homepage is disabled currently and it's in inactivity. Let's reopen when we work on it again!
