### ISSUE TITLE
Plugins: Update notice broken on mobile

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#6968]
#### Steps to reproduce
1. Visit a single site plugin page of a plugin that needs an update on a mobile device.
#### What I expected

To be able to recognise the button that I need to push to update the plugin.
#### What happened instead

I saw 2 orange strips.
#### Browser / OS version

Chrome / OSX
#### Screenshot / Video

<img width="440" alt="screen shot 2016-07-22 at 09 13 27" src="https://cloud.githubusercontent.com/assets/115071/17063559/c5a93578-4fec-11e6-9448-ca240a7fd117.png">
#### Context / Source
# dogfooding

cc: @rickybanister

**Comment by rickybanister** [comment]
@mtias have you ever encountered this? Do you think it's only happening here because of some strange flex cascade?

**Comment by mtias** [comment]
I've seen this before. I think it was expected to do that when text overflows.

**Comment by lancewillett** [comment]
Closing as "works for me" — feel free to open new issues for new bugs.

**Comment by rickybanister** [comment]
I think it's fine to leave this one closed for now, the improvement we came up with is being tracked in #8127
