### ISSUE TITLE
Marketplace search: index categories and tags to a common schema

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#69692]
Follow-up issue to #69337 

Based on the backlog grooming here: p1666876574190569-slack-C02JPCHEKDY

To make filtering by category easier, we need to index the below taxonomies to the `plugin.*` array:
- For WP.org plugins: 
  - `plugin_tags`
  - `plugin_category`

- For WC.com products:
  - `wpcom_marketplace_categories`
  - `product_tag`

We can update the filtering logic created in #69337 to use these newly added fields for filtering instead of the site-specific ones.

**Comment by gcsecsey** [comment]
Diff created: D93580-code

**Comment by epeicher** [comment]
Changes deployed r256949-wpcom
