### ISSUE TITLE
Import focused flow: Support choosing domain and plan steps

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#69698]
Create a new onboarding flow:

- Doesn’t assume site is created yet, and instead creates a new site.
- Doesn’t include “goals” step
- Does include domains & plans steps
- Asks for customer’s old site’s URL like importer flow does

cc @vishnugopal

**Comment by simison** [comment]
See https://github.com/Automattic/wp-calypso/pull/68722 and pdDR7T-hL-p2
