### ISSUE TITLE
Marketplace search: add more weight to number of installs and reviews

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#69693]
Based on the discussion here: p1666887570005669/1666886827.660349-slack-C029JEQRVRT

Currently, the ranking of search results puts much more weight on matching pieces of product title or description than needed. Important data points, like the number of installations or number of reviews for the product are considered with a lower weight.

We need to update the ranking config to feature more popular or more heavily reviewed products higher up in search results.

The config the API uses is stored here: 2e139-pb/#php

**Comment by cpapazoglou** [comment]
Here is the config used in `wordpress.org` https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/libs/site-search/jetpack-search.php#L837.

Let's try to revise our config based on this.

**Comment by gcsecsey** [comment]
In Kibana we can also use the `"explain": true` parameter to get the details on how the scores are calculated in ES. This could help us a lot in calculating the boost values needed.

However, I haven't yet found an easy way to either provide all the filters and boost values that we have configured in PHP or to get the same explain field back from ES through the ES API wrapper.

**Comment by gcsecsey** [comment]
On our team meetup we've started working on a diff that's addressing this issue as well: D95306-code

**Comment by cpapazoglou** [comment]
Deployed r258769-wpcom
