### ISSUE TITLE
Marketplace: Vendor OAuth2 Token Doesn’t Have User_id Configured

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#69694]
### Details

At some point along the way of developing the licensing system, it seems like we stopped treating vendors as machines ([Client Credentials](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow)) and started to associate credentials with user ids. 

There are several instances where we needed to know the `user_id` of from vendor token. 

### What needs to be done

The vendor OAuth 2 token needs to resolve the vendor's WPCOM user_id in the `user_id` field. 

### How

TBD

Related to: pdt2If-uJ-p2#comment-276

**Comment by gavande1** [comment]
Created diff: D91861-code. The basic idea here is to create a vendor API token with user_id. So whenever this API token is used, the user_id will resolve correctly. In addition to that, it simplifies the process of creating API tokens for the vendor.

**Comment by gavande1** [comment]
Created another diff: D92061-code

**Comment by gavande1** [comment]
Second diff deployed: r256551-wpcom

**Comment by cpapazoglou** [comment]
D91861-code is ready for review

**Comment by epeicher** [comment]
I have reviewed D91861-code and the changes LGTM

**Comment by gavande1** [comment]
There were a few problems with the diff and it's been updated. I would like to have another review of it.

**Comment by gavande1** [comment]
Deployed r256703-wpcom
