### ISSUE TITLE
Launchpad: Address a11y issues from aXe scan

### ISSUE THREAD

**Issue by sharpirate** [Automattic/wp-calypso#69690]
#### Summary
I've run an aXe scan on the Launchpad page which identified some unresolved a11y issues:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/20927667/199453930-ab28426d-012e-4a97-96a5-8fb908143de9.png">

#### Reproduce
1. Install [aXe Devtools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US)
2. Go to `https://wordpress.com/setup/launchpad?flow=link-in-bio&siteSlug=YOUR_SITE_SLUG`
3. Open aXe Devtools (inside Chrome DevTools)
4. Run a full page scan

#### Note
It's important to note that we probably won't be able to fix all of these since some of them are regarding color contrast which is a design decision. We should aim to fix the ones that make sense.

**Comment by youbrokesomething** [comment]
A quick note on color contrast, the extension will mark any color contrast that it isn't sure of as needing manual review. You can use a tool like the [Accessible Web color contrast checker](https://accessibleweb.com/color-contrast-checker/) to check manually. That tool includes font size which is also essential!

**Comment by Addison-Stavlo** [comment]
@Sharpirate I recall you merged one PR to address issues found here. Do you think this is worth keeping open at this point?

**Comment by sharpirate** [comment]
One remaining thing we can do as part of this issue is to fix the file input which `aria-hidden="true"` but it's still focusable which produces the following issue: _ARIA hidden element must not be focusable or contain focusable elements_

<img width="624" alt="image" src="https://user-images.githubusercontent.com/20927667/202593890-f05688f5-c9ae-4f02-bd9d-d7733ff8de5f.png">

It comes from the `component-file-picker` package which is used by the [file-picker component](https://github.com/Automattic/wp-calypso/blob/7af06e175058130c9d451189cf22c5a601ac0b8c/client/components/file-picker/index.jsx#L15). We would want to drop the package since it hasn't been updated in 8 years and has some a11y issues. We would need to implement what the package did in our component directly

**Comment by Addison-Stavlo** [comment]
> We would want to drop the package since it hasn't been updated in 8 years and has some a11y issues. We would need to implement what the package did in our component directly

this seems like a wider issue to address separately, il close this for now.
