### ISSUE TITLE
Template var not replaced

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#69704]
Follow up on https://github.com/Automattic/wp-calypso/issues/69520

When entering the right code, the "thank you" template is wrong ({{email}} is not replaced)

See:
<img width="327" alt="Screenshot 2022-11-02 at 16 01 33" src="https://user-images.githubusercontent.com/790558/199525101-fec4214b-8643-401a-873f-00b81fe37e1b.png">

**Comment by artpi** [comment]
I think I failed to port the javascript that should run on this specific flow. I think @n3f also reported it on slack

**Comment by artpi** [comment]
Oh its a duplicate of #69722

**Comment by romarioraffington** [comment]
Also, we always show the "Thank You" page, even when the OTP is invalid

https://user-images.githubusercontent.com/7076981/199781231-5ac2e343-894c-4359-9eca-802373349f7f.mov

**Comment by millerf** [comment]
Yes, we have a task for it. This task is only the design.

**Comment by millerf** [comment]
I actually cannot find the task. Can you create one?

**Comment by artpi** [comment]
https://github.com/Automattic/wp-calypso/issues/69759

**Comment by artpi** [comment]
Created one just now

**Comment by n3f** [comment]
Reviews: D91997-code

**Comment by n3f** [comment]
Merged/deployed
