### ISSUE TITLE
Scheduled post's publish date/time picker shows different dates

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#69708]
### Quick summary

User reports that the date shown on the visual calendar when they try to schedule a post is off from the date shown in the text field.

### Steps to reproduce

1. Start on any post.
2. Click on date next to Publish under the Summary module in the right sidebar of the post.

### What you expected to happen

Date indicated on calendar should match date shown in text fields.

### What actually happened

Date indicated on calendar differs from date shown in text fields.

### Context

Customer report: 37725451-hc

User supplied screenshots in chat. Unable to reproduce on our end.

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Unknown

### Browser, operating system and other notes

Chrome/107.0.0.0 on MacOS (version unknown)

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by aisajib** [comment]
@the-misha I wasn't able to reproduce this with multiple timezone settings on my test atomic site. I wonder if this was a one-off issue on their end. I'm closing this since we couldn't reproduce it at all on our end. Feel free to reopen if users repeat similar reports.
