### ISSUE TITLE
[Paid Newsletters] :: investigate weird subjects in sent subscription confirmation emails

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69711]
Per @n3f :
p1666727772715049-slack-C01B6KEJ5GE

**Comment by millerf** [comment]
Could not reproduce...


<img width="1339" alt="Screenshot 2022-11-04 at 14 32 51" src="https://user-images.githubusercontent.com/790558/199985409-73dbe92f-b6e6-4162-8d31-ecf930125f39.png">

**Comment by millerf** [comment]
I'll leave it here if someone has more luck....

**Comment by n3f** [comment]
We figured out on slack that this was a bad issue.  I have my outgoing email trapped in a filter and the subject changed/mangled, so it's probably related to that.
