### ISSUE TITLE
Billing: Have a way to add a payment method independent of any purchase

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#6971]
For Connect for WooCommerce, we're going to need to be able to allow the primary user of a Jetpackked blog to Add and Edit a payment method, independent of any plan/subscription. We need this in order to be able to charge the user for shipping labels they purchase.

The user will also need a way to indicate what payment method is the default, in the event that the user has multiple payment methods.

I think this could live in https://wordpress.com/me/billing under Manage Your Credit Cards

<img width="1272" alt="screen shot 2016-07-22 at 11 10 39 am" src="https://cloud.githubusercontent.com/assets/1595739/17066719/355655c6-4ffd-11e6-9975-fdcdfae56133.png">

We need this by mid August.  My team can help with some of the design and development - we would love to partner up on this.

cc @nabsul @peterbutler

**Comment by gziolo** [comment]
@breezyskies: We had already working prototype for cards management, when working on `Purchases` for Calypso. It was completely purchase dependant. Do you think we could reuse some design bits here? I'm also wondering if `Manage Credits Cards` section doesn't deserve its own tab? It feels a bit misplaced as a part of `Billing History`.

@allendav: We already have `Add Card Details page` so this shouldn't be a big task on the front end side to connect the existing section with it:

![screen shot 2016-08-08 at 12 21 25](https://cloud.githubusercontent.com/assets/699132/17476919/bbefba74-5d62-11e6-8710-f046da4edf44.png)

**Comment by breezyskies** [comment]
A few questions:

> For Connect for WooCommerce, we're going to need to be able to allow the primary user of a Jetpackked blog to Add and Edit a payment method, independent of any plan/subscription. We need this in order to be able to charge the user for shipping labels they purchase.

How does a user get here? What does the flow look like and what expectations are set before they land here? Will this option only be presented to Jetpack users (or only Jetpack users who are using shipping labels)?

> The user will also need a way to indicate what payment method is the default, in the event that the user has multiple payment methods.

This only applies to the shipping label payments, correct? We don't really have the concept of a "default" payment method in general AFAIK.

Also, is there a reason not to tie this to a recurring subscription of some sort to make it more consistent with the existing UI (e.g. a "Shipping Labels" product)? How will charges look after someone has paid?

**Comment by nabsul** [comment]
@breezyskies 

> How does a user get here? What does the flow look like and what expectations are set before they land here? 

The user starts out on their self-hosted (jetpack enabled) site, where we check if the user has any saved payment methods. If not, we direct them to their wp.com payments page to add a payment method.

> Will this option only be presented to Jetpack users (or only Jetpack users who are using shipping labels)?

I don't think this needs to be Jetpack specific. Managing payment methods is something all WP.com users can make use of.

> This only applies to the shipping label payments, correct?

For now yes, but this could be useful in many other scenarios.

> We don't really have the concept of a "default" payment method in general AFAIK.

Correct. We're working on adding support for this to the BillingDaddy API. For now, let's focus only on adding a payment method.

> Also, is there a reason not to tie this to a recurring subscription of some sort to make it more consistent with the existing UI (e.g. a "Shipping Labels" product)? How will charges look after someone has paid?

There is no subscription associated with purchasing labels. It's a one-time payment that will be made each time a user purchases a shipping label.

**Comment by allendav** [comment]
Yep, this is all correct. As noteable is that we will allow the merchant to choose from one of the payment methods for label purchases. We were going to put that on the [client](https://github.com/Automattic/woocommerce-connect-client/issues/471).

**Comment by peterbutler** [comment]
>Will this option only be presented to Jetpack users (or only Jetpack users who are using shipping labels)?
>I don't think this needs to be Jetpack specific. Managing payment methods is something all WP.com users can make use of.

This is true, it doesnt need to be jetpack specific - but at this point (until we overhaul payment management on WordPress.com), there will be no reason for a WordPress.com only user to ever use this functionality.  As such, I think we should build it with the idea that it's generic, but I don't think it's important to make sure users can get there from WordPress.com - I think it's ok to only have it linked from the jetpack site.

>Also, is there a reason not to tie this to a recurring subscription of some sort to make it more consistent with the existing UI (e.g. a "Shipping Labels" product)? How will charges look after someone has paid?
> There is no subscription associated with purchasing labels. It's a one-time payment that will be made each time a user purchases a shipping label.

I agree - we toyed with the idea of creating a subscription for these, but it feels forced - the analogy doesn't quite work.  For now, these will be essentially one time purchases, made with a stored card.  The trick is just getting the card stored for use.
