### ISSUE TITLE
Fix subscription login dialog

### ISSUE THREAD

**Issue by n3f** [Automattic/wp-calypso#69722]
After entering a previously subscribed email (and entering the security code) the confirmation dialog needs to be updated. (Both the bad placeholder `{{email}}` and the general text should all be changed.

![image](https://user-images.githubusercontent.com/6354169/199617852-0e6841d4-4b63-466c-9216-37c1d21e533e.png)

**Comment by romarioraffington** [comment]
Is this a duplicate of https://github.com/Automattic/wp-calypso/issues/69704 ?

**Comment by n3f** [comment]
> Is this a duplicate?

Looks like it...
