### ISSUE TITLE
[Bug]: Weird behavior in subscriptions management page

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#69736]
### Quick summary

When trying to unsubscribe from a subscription, the subscription get duplicated on screen (but it still gets unsubscribed).

A screencast is worth a thousand words:

https://user-images.githubusercontent.com/790558/199685617-24874043-c55f-4d5e-8d30-a38b7ff7da8a.mov

### Steps to reproduce

1. Get a subscription from a site SITE_URL
2. Go to your subscription management page (https://wordpress.com/following/manage/?s=SITE_URL)
3. Try to unsubscribe

### What you expected to happen

The subscription is cancelled / nothing special happens

### What actually happened

The subscription is duplicated.

When the page is reloaded, everything is as expected.

### Browser

Android Chrome

### Context

development of jetpack paid newsletters (see https://github.com/Automattic/jetpack/pull/26417), but we don't touch at the subscription page.

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by cuemarie** [comment]
This report was found in a sweep of backlogged issues that were not prioritized or on the Dotcom Bug Prioritization Board. Gave it a quick triage test, notes below.

📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested in Reader - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- This does not seem to be presenting anymore. Tested in Firefox 112.0.2

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/235785725-4a1746b5-8c16-4733-b6c6-1a43ec2f4b0a.mp4

📌 ACTIONS
- Closed as could not replicate
