### ISSUE TITLE
[Bug]: Earn block asking for unnecessary upgrade

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#69740]
### Quick summary

The payment block is asking for a plan upgrade but checkout (after paying) tells you it is unnecessary.

This happens  on WPCOM in a development environment and has not been tested any place else.

<img width="738" alt="Screenshot 2022-11-03 at 12 00 20" src="https://user-images.githubusercontent.com/790558/199707166-4f36048d-aa56-4421-a71e-3e4032f0c24f.png">

While checkout tells it is not needed:

<img width="1303" alt="Screenshot 2022-11-03 at 12 01 30" src="https://user-images.githubusercontent.com/790558/199707252-8e4c380b-6ba0-4124-a103-27796327525c.png">

### Steps to reproduce

1. Create a new domain
2. Get a paid plan (I think I am on business - site is jetpackearntest.wordpress.com)
3. Go to calypso and add a payments block
4. You should see "Upgrade to Personal..."

### What you expected to happen

You should not see the "Upgrade to Personal" button

### What actually happened

You see the  "Upgrade to Personal" button

### Context

dev environemnt - tests tore

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by millerf** [comment]
Some more data: if you are on a Personal plan and do the checkout, it renews your plan...

**Comment by cuemarie** [comment]
This report was found in a sweep of backlogged issues that were not prioritized or on the Dotcom Bug Prioritization Board. Gave it a quick triage test, notes below.

📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Could not replicate on AT or Simple Test Sites in WordPress.com

#### Screenshots/Recordings

**Business Plan**
![Markup on 2023-05-02 at 13:56:38](https://user-images.githubusercontent.com/27249804/235784362-25dca676-70cb-4ec3-b2af-73b60edc96dd.png)

**Premium Plan**
![Markup on 2023-05-02 at 13:55:57](https://user-images.githubusercontent.com/27249804/235784374-000628f1-a231-4945-813e-75795f552095.png)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
