### ISSUE TITLE
Weak password banner disables ability to edit password on signup form

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#69749]
## Description

I just ran into a critical bug trying to create a new [WP.com](http://wp.com/) site. I just tossed in a random assortment of characters as a password (`passjdks`) and saw this banner alert, but the form fields became disabled, so I couldn't actually change my password. 

<img width="1027" alt="CleanShot 2022-11-03 at 11 16 41@2x" src="https://user-images.githubusercontent.com/5634774/199762536-1c37a0a4-3059-49e1-b025-4b59e948054d.png">

I went through the flow again and recorded a video, just to make sure I could reproduce the issue.

https://user-images.githubusercontent.com/5634774/199762556-edc778dd-5dab-4f3c-ab42-b6d9520fa2b8.mp4

## Expected

That I'd be able to update my password

## Actual

The form fields became disabled, so I couldn't edit my password.

## Steps to reproduce

1. Open incognito tab
2. Go to [https://wordpress.com/start/](https://wordpress.com/start/)
3. Put in an email, username and weak password ( I used: passjdks)

## Setup

Mac Monterey 12.6
Chrome Version 106.0.5249.119 (Official Build) (arm64)

**Comment by p-jackson** [comment]
#69755 addresses the frontend issue of the UI getting locked up.

We can also tidy up the logic in the backend D91653-code
