### ISSUE TITLE
Themes: Activate button hidden at mobile screen width

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#6975]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/example.wordpress.com
2. Click the ellipsis at the bottom of a theme card and select Live Demo

#### What I expected
To be able to Activate the theme from this page

#### What happened instead
I see the "Activate this design" button briefly, but it's soon covered up by the top of the theme.  I believe this was introduced with this PR - https://github.com/Automattic/wp-calypso/pull/6952
cc: @sirbrillig 

#### Browser / OS version
OSX Chrome v51, Linux Chrome v43

#### Screenshot / Video
![wp-calypso-mobile-themes](https://cloud.githubusercontent.com/assets/7233112/17069561/30f8d062-5025-11e6-984f-40a2d849c43d.gif)

#### Context / Source
#automated-testing

**Comment by sirbrillig** [comment]
Thanks! I've got a fix in #6976 but it deserves testing.
