### ISSUE TITLE
[Newsletters] Validate OTP

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69759]
Also, we always show the "Thank You" page, even when the OTP is invalid

https://user-images.githubusercontent.com/7076981/199781231-5ac2e343-894c-4359-9eca-802373349f7f.mov

Per @romarioraffington in #69704

**Comment by n3f** [comment]
I fixed this in D91850-code

**Comment by artpi** [comment]
I added a few comments

**Comment by n3f** [comment]
Merged/deployed.
