### ISSUE TITLE
LaunchPad - Surface a launchpad banner in calypso

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#69756]
For sites that have the launchpad active, we should surface a banner in Calypso admin to make finding and returning to the launchpad easy. So when a launchpad user selects "go to admin" and visit more complicated calypso admin, there will always be a visible indication of how to return to the launchpad at the top of the page.

In a fitting visible location such as the top of the right hand column or just below the top admin bar:

![Screen Shot 2022-11-03 at 1 44 54 PM](https://user-images.githubusercontent.com/28742426/199797379-c033bc77-bd90-42d2-82fc-ba4a15392f72.png)

An idea for starting design for this banner can be visually similar to the email notification banner we added to the LaunchPad screen:

![image](https://user-images.githubusercontent.com/28742426/199798458-9b059d40-6b89-49ce-9a9d-69024ecb1e7c.png)

Where we have a friendly icon (rocket ship?), a light (possibly playful) message about returning to the launchpad, and a button/link that will navigate users to the fullscreen launchpad.

It is up to us to find a reasonable / consistent 1st iteration design while developing this, and we can always update further through future design input.

**Comment by jeyip** [comment]
Shepherding this while Matt is AFK

**Comment by jeyip** [comment]
Could you describe what you mean when you say “In a fitting visible location such as the top of the right hand column…“?

Having something right under the admin bar is going to be tricky. With the current CSS, it’s not impossible, but there are lots of edge cases to cover ( different breakpoints, the “view” tab, different layout content background colors, etc. )

**Comment by jeyip** [comment]
> Could you describe what you mean when you say “In a fitting visible location such as the top of the right hand column…“?

Having something right under the admin bar is going to be tricky. With the current CSS, it’s not impossible, but there are lots of edge cases to cover ( different breakpoints, the “view” tab, different layout content background colors, etc. )

Relevant discussion p1669070392411239-slack-CHN6J22MP

**Comment by jeyip** [comment]
The notice doesn't appear in `wp-admin`, only in Calypso admin. Currently working on fixing this...

**Comment by Addison-Stavlo** [comment]
closing this since it is against the design direction
