### ISSUE TITLE
Move + edit educational resources section on /plugins

### ISSUE THREAD

**Issue by jeremyanderberg** [Automattic/wp-calypso#69763]
### Details

Here are my recommendations for moving and slightly editing the educational resources found at the bottom of the /plugins page. Here's what it looks like now: 

<img width="961" alt="Screen Shot 2022-10-18 at 2 00 23 PM" src="https://user-images.githubusercontent.com/106615146/199813789-b2dd7fea-f9fd-41fd-9002-0a1d99a46c18.png">

1. Can we get rid of the category names at the top of the cards (Website Building, Customization, and SEO)? They don’t add anything – other than some visual clutter.

2. Can we align the “Read More” text/links?

3. Can we do something different with the color/font of the text? Blue on blue feels especially hard to read from an accessibility point of view. (@vinimotaa) 

4. Can we replace the far-right card with this article: https://wordpress.com/go/website-building/17-must-have-wordpress-plugins-useful-for-all-sites/. 

5. Finally, let's move the entire section up. My suggestion is to try either of these spots:

![Annotation on 2022-10-18 at 14-30-08](https://user-images.githubusercontent.com/106615146/199814153-4c859f06-64dd-4408-97b3-781932f70f26.png)

**Comment by cpapazoglou** [comment]
Backlog grooming:
- Let's move the section just above "Our developers' favorites"
- @vinimotaa can you suggest an alternative bg color?

**Comment by vinimotaa** [comment]
Hi @WBerredo, here is the suggested design for this issue;

![marketplace_educationalresources](https://github.com/Automattic/wp-calypso/assets/97929097/33bc09e1-8c41-40d7-83a5-a4b42b98437d)
