### ISSUE TITLE
Port tests from FSE to Jetpack

### ISSUE THREAD

**Issue by romarioraffington** [Automattic/wp-calypso#69764]
### Description

We want to port [these Premium content tests](https://github.com/Automattic/wp-earn/blob/master/dev/test/Automattic/Earn/PremiumContent/PremiumContentDomTest.php) to Jetpack

**Comment by romarioraffington** [comment]
Didn't get very far with porting tests. I was able to add some tests [here](https://github.com/Automattic/jetpack/commit/882d06ba0a726beb0febf9cd240390897f385e7a). Putting this back to work on something more urgent

**Comment by n3f** [comment]
I don't know if the link is bad, but the test linked in the description appears to be testing a class that doesn't exist anymore (at least I can't find it -- but I could be mistaken)...

**Comment by millerf** [comment]
>  I don't know if the link is bad, but the test linked in the description appears to be testing a class that doesn't exist anymore (at least I can't find it -- but I could be mistaken)...

Same question. Why do Romario's tests not listed in the ones from the WPCOM link...

**Comment by millerf** [comment]
@romarioraffington I think the tests you added duplicate the ones I created [here](projects/plugins/jetpack/tests/php/modules/subscriptions/test_class.jetpack-subscriptions-online.php) and [here](projects/plugins/jetpack/tests/php/modules/subscriptions/test_class.jetpack-subscriptions-offline.php)

**Comment by romarioraffington** [comment]
Yea @millerf , I think the core of this task was to introduce tests and I think your PR is doing that
