### ISSUE TITLE
[Placeholder] Address Ian's comments on theme switch

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69771]
# Description
Dec 12 update: I'm keeping this issue open as a placeholder.  All [theme switch issues](https://github.com/orgs/Automattic/projects/338/views/35) will be triaged when we are ready to take action in early 2023.

See pbxlJb-2X4-p2#comment-2066

Let’s parse fixes/create issues as

* fixing anything we’ve made worse (if that is the case)
* things we need to fix in general

And let's figure out what state is acceptable to ship, the current state is already broken. So I don't think we are making things worse with D89996-code

**Comment by taipeicoder** [comment]
We can close this one, since the theme switch experience has undergone many improvements, including:

- https://github.com/Automattic/wp-calypso/pull/77881
- https://github.com/Automattic/wp-calypso/issues/79167
