### ISSUE TITLE
Task: Improvements for the Import a Domain flow. 

### ISSUE THREAD

**Issue by JanaMW27** [Automattic/wp-calypso#69787]
### Details

If a user wants to import their domain, the first page that they see when they initiate the flow is the following:
<img width="1150" alt="image 6" src="https://user-images.githubusercontent.com/71137829/199953846-f6744db0-3726-480f-a92e-1053cfaf042b.png">

This page should have a better structure and provide directions for the user on what they have to do and why.

### Checklist

- [ ] Evaluate the import domain flow
- [ ] Re-design the first page of the flow
- [ ] Define any other improvements that we could make to the flow
- [ ] Development of the changes

Let's keep in mind that these changes need to be small, incremental, and easy to ship quickly.

**Comment by JanaMW27** [comment]
@paulbonahora has done a first exploration [here](https://www.figma.com/file/eLf7gfvbYHwHUx1Ys2kAaa/Untitled?node-id=0%3A1).

**Comment by JanaMW27** [comment]
Latest design can be [found here.](https://www.figma.com/file/0JF6KLmG0YRR7RB6WaWEfU/Importing-domain?node-id=1601%3A7237)
![Import a domain](https://user-images.githubusercontent.com/71137829/200912670-27efa667-c850-48f9-9ac7-d1be716c9582.png)

**Comment by paulbonahora** [comment]
Looking great! @claudiucelfilip , would you be able to help with the implementation of this as part of our bottle pickup? There are new strings of texts so it'd be ok to default to the old version for non-en texts until translations come in.

**Comment by claudiucelfilip** [comment]
Opened https://github.com/Automattic/wp-calypso/pull/69898 with the changes for this.

**Comment by kelliepeterson** [comment]
Hey folks. Love that you're working on this, but I have a couple of comments:

Please include something on the page about owning the domain. "Enter the domain you would like to use" will absolutely lead to users entering domains that someone else owns and thus creating frustration. 

Domains don't actually include https or www. I'm not sure why we wouldn't simply state "please enter the domain without..." instead, but if you think it's important, cool as long as you're stripping it out on submission. 

Cheers!

**Comment by paulbonahora** [comment]
Hey @kelliepeterson thanks for the note. I realize we didn't include context for this so I'll share more of it: the main issue we're trying to address here is that currently, if users include "www" on the domain, they get an error message that gives the impression their domain won't be eligible to use, see [here](https://d.pr/i/NGpMfw). That's the main nuance we're trying to address as we suspect we may be losing on conversions as a result. Furthermore, there's been chatter on [this thread](https://a8c.slack.com/archives/C9EJ7KSGH/p1667395571531619) where it's been suggested to improve the design and UX and thus Jana's recommendation to change the layout.

The domain ownership is a good point. I'd say the header suggests ownership already, specially considering users are coming from a prompt that asks them specifically if they already own a domain (see [here](https://d.pr/i/9x6ErJ)). We'll take a look to see if there's anything else we can add to make this clearer.

**Comment by pablohoneyhoney** [comment]
I think we need `https://` as a placeholder, not `www`.

**Comment by JanaMW27** [comment]
Like this:

https://user-images.githubusercontent.com/71137829/202502329-5568725b-8a95-4f91-ac39-cda3dfeaec8b.mov

**Comment by paulbonahora** [comment]
I like that @JanaMW27 ! In particular now that the bug shared [here](https://github.com/Automattic/wp-calypso/issues/69787#issuecomment-1309400825) is fixed (thank you @delputnam  for this!), so if users now type in "www", we handle that on the backend. This UX would now work.

**Comment by claudiucelfilip** [comment]
The `https://` has been added as a placeholder, as [per video](https://github.com/Automattic/wp-calypso/issues/69787#issuecomment-1318892953).
Because `yoursiteaddress.com` is [already owned](https://github.com/Automattic/wp-calypso/pull/70169#discussion_r1026433045), `yourgroovydomain.com` was been used instead (taken from PCYsg-eI0-p2). 
Non-english locales will continue to use `mydomain.com` until translations for the new version are available.

cc. @pablohoneyhoney @paulbonahora
