### ISSUE TITLE
Empty query date in StatsPeriodHeader

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#69781]
An empty query date is displayed within the StatsPeriodNavigation of the `Ads` page when navigating between periods, which makes the period title move up and down.

Related to https://github.com/Automattic/wp-calypso/pull/69743#pullrequestreview-1167799361
![Large GIF (764x68)](https://user-images.githubusercontent.com/4044428/199857753-8578cb38-ba9a-4cd2-97b1-d732d36ba855.gif)

**Comment by jsnmoon** [comment]
@dognose24, is this resolved?

**Comment by jsnmoon** [comment]
Closing as resolved, please reopen if I'm mistaken.
