### ISSUE TITLE
Featured image email toggle: Add link pointing to the featured image docs

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#69786]
The new Featured image email toggle needs more information on what the Featured image is.

Product discussion: pdtkmj-Gy-p2#comment-1149

The goal of this task is to add CTA link `Learn more about the featured image` leading to user-facing Featured image doc: https://wordpress.com/support/featured-images/.

We can use the same structure/design as we have for Feed settings:

![Image](https://user-images.githubusercontent.com/25105483/199940766-6752ceb6-f2e2-461b-9836-ab6a17ec6db6.png)

**Comment by saygunnyc** [comment]
Let's add a dot at the end. "Learn more about the feeds. "
Similarly to:

<img width="196" alt="Screenshot 2022-11-28 at 12 49 48 PM" src="https://user-images.githubusercontent.com/78876323/204346336-cf94f2ed-b0af-4c8a-a37c-a635ba167faf.png">

**Comment by ivan-ottinger** [comment]
https://github.com/Automattic/wp-calypso/pull/70870 is now ready for review.

**Comment by ivan-ottinger** [comment]
This task has been addressed in https://github.com/Automattic/wp-calypso/pull/70981
