### ISSUE TITLE
Reader: Manage Following name/date sorter doesn't work with 3 or less items 

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#6979]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/following/edit
2. Make sure you have 3 or less followed sites
3. Try sorting the list by name or date

#### What I expected
For this feature to work even with 2-3 followed sites

#### What happened instead
I had 3 followed sites but I'm unable to sort it

#### Browser / OS version
Chrome 51.0.2704.106 / Mac OS 10.11.3

#### Screenshot / Video
Video: https://cloudup.com/c8Tz-dc8d-u

I think it also might make sense to just use the `SelectDropdown` component here.

**Comment by bluefuton** [comment]
Could it be that the outcome of both sorts is the same in this case @jancavan? I have a test account with 3 and it sorts as expected:

https://cloudup.com/cRWJF6KP_9S

**Comment by jancavan** [comment]
Ooh that's it! I didn't realize that. Thanks.
