### ISSUE TITLE
Reader: polls do not show up in the single-post view

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#698]
Steps to reproduce:

1. Start a post at https://wordpress.com/post
1. Add a poll ([related help page](https://en.support.wordpress.com/polls/))
1. Publish the post and view it in the Reader

<strong>Result:</strong> the poll doesn't show up.

Example post:

![screen shot 2015-11-24 at tue nov 24 5 45 46 pm](https://cloud.githubusercontent.com/assets/1119271/11383048/83b5e5e8-92d3-11e5-85a1-3794060e5ad9.png)
<sup>Testing with Firefox 42.0 on Mac OS X 10.10.5</sup>

Same post in the Reader:

![screen shot 2015-11-24 at tue nov 24 5 46 46 pm](https://cloud.githubusercontent.com/assets/1119271/11383042/8076721c-92d3-11e5-9f34-aea3c7290f2b.png)
<sup>Seen at https://wordpress.com/read/post/id/72040772/1919 using Firefox 42.0 on Mac OS X 10.10.5</sup>

/hat tip vparkhere for the original report

**Comment by bluefuton** [comment]
The markup _is_ being provided by the API:

<img width="904" alt="screen shot 2016-02-02 at 17 04 54" src="https://cloud.githubusercontent.com/assets/17325/12739501/24c67cea-c9cf-11e5-9b3e-cb79087c664a.png">

...so I think we may need a special case in the post normalizer.
