### ISSUE TITLE
Writing Prompts: refactor, rename to blogging-prompts and reuse common functions

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#69813]
As @creativecoder reported pe7F0s-mf-p2#comment-361

> regarding code naming – all of the existing code uses the name “**blogging prompts**“ [...] I think keeping things consistent in the code makes it much easier to search and find the relevant code, especially since it’s spread out among so many different places.

We've also talked about reusing common functions defined in https://github.com/Automattic/jetpack/pull/26680/files#diff-acd0204d3f6f426c73c50b612d14f3c9fdba8386c5047cbb2cea0892822faeb1

We've also been debating standardizing on how we check whether the user is a blogger or not p1667792156714089/1667217622.476049-slack-C03NLNTPZ2T

### Checklist 

- [x] Update notifications D90182-code and D91457-code to use the blogging-prompts naming convention
- [x] Use shared functions [defined in jetpack](https://github.com/Automattic/jetpack/pull/26680/files#diff-acd0204d3f6f426c73c50b612d14f3c9fdba8386c5047cbb2cea0892822faeb1) wherever possible, including to determine whether the user is a blogger or not
- [x] Move existing code to the blogging-prompts 2e1ed-pb library wherever possible.
- [x] [lower priority] Rename frontend code for [notifications](https://github.com/Automattic/wp-calypso/pull/69352) and [my-home card](https://github.com/Automattic/wp-calypso/pull/69696) to use *blogging*-prompts naming

**Comment by eoigal** [comment]
The refactoring listed appears to be done. We can reopen if we find other areas where refactoring might be beneficial

**Comment by creativecoder** [comment]
Nice, thanks for following up with this!
