### ISSUE TITLE
Writing Prompts: Add answers_prompt query param

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#69820]
### Details

Links from My Home or notifications in Calypso should append the `?answer_prompt={prompt_id}` query param, to instruct the post editor to set up the post as a response to a writing prompt.

We need to update the writing prompts notification handler on calypso to include this query param when the Answer Prompt action link has been clicked.

### Checklist

- [x] Create PR to add `answer_prompt` query param to Answer Prompt action link

**Comment by eoigal** [comment]
I was able to do this from WPCOM side, no need for calypso PR

code-D91874

**Comment by creativecoder** [comment]
Looks like this was resolved by D91874-code, so I'll close this issue.
