### ISSUE TITLE
Blockbase: Slideshow block shows on site editor but does not show on preview or live site

### ISSUE THREAD

**Issue by Jaykame** [Automattic/wp-calypso#69859]
### Quick summary

The Slideshow Block shows images fine on Site Editor (FSE) but does not show up on the live site when added through the Site Editor. 

### Steps to reproduce

1. Choose a **Blockbase** theme. 
2. Go to **Appearance -> Editor**. 
3. Add a **Slideshow Block**. 
4. Select or Upload a few images. 
5. Save and Preview your site. 
6. Slideshow images do not show up. 

Screenshots:

### What you expected to happen

Slideshow images should be shown on the live site.

### What actually happened

Slideshow images do not show up on the live site. 

**Screenshot:** 

**Slideshow Block inside the Site Editor.**
![Screenshot on 2022-11-08 at 11-51-42](https://user-images.githubusercontent.com/37708357/200668713-4270ec29-ecff-40c2-a342-15ecc62c2e0e.png)

**When previewing the live site.**
![Screenshot on 2022-11-08 at 11-52-14](https://user-images.githubusercontent.com/37708357/200668729-e76861cb-7a0c-40ed-8906-5cbe64c607a2.png)

### Context

Reported in 5666258-zen. 

Replicated issues when testing on several themes including several Blockbase and FSE themes. It appears to only affect Blockbase themes on both atomic and simple sites. 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Blockbase themes. Specifically tested on Varese, Blockbase, Hari. 

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Placing the **Slideshow Block** into a **Group Block** appears to solve the issue.

**Comment by zachspears** [comment]
Replicated in Atomic and Simple. Block is displaying but incorrectly.

**Comment by dpasque** [comment]
From what I can tell, this seems pretty disruptive, as users effectively won't be able to use this block on blockbase sites, which is the base of a lot of our themes Bumping to high as there doesn't seem to be a workaround that preserves the same functionality.

**Comment by mgozdis** [comment]
Additional report in 40628264-hc on a Simple site using Videomaker theme. I reproduced on a test site with Videomaker and this seemed to only affect the Front Page template or homepage. Grouping the Slideshow Block then displayed the images on the front end. Adding a Slideshow Block to a regular page in Videomaker worked fine whether grouped or not.

**Comment by jp-imagines** [comment]
Another report in 5958978-zd-woothemes on Zoologist. Adding the Slideshow into a Group (and adjusting the width/alignment setting) fixed things.

**Comment by edwinho89** [comment]
Another report: 41369473-hc
Site on [Attar theme](https://wordpress.com/theme/attar/)

Applying workaround fixed

**Comment by sguzovskaia** [comment]
Another report 6076800-zen
Slideshow block does not display on the live site when added to the Index template. Simple site with Business plan.

**Comment by sguzovskaia** [comment]
Another report: 6076800-zen
Slideshow block does not show on preview or live site when added to the Index template. Theme Dorna

**Comment by pbking** [comment]
For reason's I haven't yet discerned when this block is dropped directly into a template page the block expands to an enormous size:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/146530/228656533-81eeb3ca-3b6e-4f21-a6ad-93269365b58d.png">

The actual block bits might be in there somewhere but it's so big I haven't found it...

**Comment by pbking** [comment]
I found this to be the cause:

https://github.com/Automattic/themes/blame/trunk/blockbase/sass/base/_layout.scss#L7

Trying to determine what removing that does across Blockbase children.

**Comment by pbking** [comment]
Possible fix here: https://github.com/Automattic/themes/pull/6961

**Comment by pbking** [comment]
This has been fixed and deployed.
