### ISSUE TITLE
Gifting settings defaults

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#69879]
We're figuring out how the default settings should behave in https://github.com/Automattic/dotcom-forge/issues/1176.

If we go for something like what I've suggested in https://github.com/Automattic/dotcom-forge/issues/1176#issuecomment-1308222345
```
$gifting_default_option = $auto_renew === false
$gifting_option_enabled = get_option('wpcom_gifting_subscription', $gifting_default_option)
```

We'll need to:

- [x] Update [this line](https://github.com/Automattic/wp-calypso/blob/d966527c215653e0d47d1f5134a311e09da16d90/client/my-sites/site-settings/form-general.jsx#L822) in calypso to no longer default to true in JS based on a missing value from the response.
- [ ] Update [this line](https://github.com/Automattic/jetpack/blob/e5ab0a96c2f1ffe7e7a3cca709a80473392edfd2/projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php#L439) in Jetpack to use the logic above to set a default value in the settings api response.

Note, this second part requires looking up purchase data in Jetpack, we should have it in the features code loaded via wpcomsh but we'll need to guard access to that APD data appropriately. Look at the [wpcomsh implementation](https://github.com/Automattic/wpcomsh/blob/master/frontend-notices/class-wpcomsh-frontend-notices.php#L137) to see how to do this. I know we shot this down in team call but I think moving this code all over to Jetpack makes a fair bit of sense or we're going to be duplicating the plan / purchase lookup code.

**Comment by DustyReagan** [comment]
Can we update calypso to use the logic above to set a default value on the toggle? And leave Jetpack as is? I ask because Jetpack's next release is Dec 6th.

**Comment by DustyReagan** [comment]
Oh, but Jetpack releases weekly on Atomic doesn't it. So maybe ok? Still, I wonder if updating Jetpack with the default is strictly necessary?

**Comment by DustyReagan** [comment]
>  I wonder if updating Jetpack with the default is strictly necessary?

I just tested it. It's necessary. 😅

**Comment by DustyReagan** [comment]
Something like this? https://github.com/Automattic/jetpack/pull/27374/files

It seems to be testing well.

**Comment by lsl** [comment]
>> I wonder if updating Jetpack with the default is strictly necessary?

> I just tested it. It's necessary.

I wasn't sure about this myself but glad my assumption was correct :smile:
