### ISSUE TITLE
Pattern Assembler - Find a solution for a long list of sections

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#69882]
There is no limit to the sections that can be added to the list. The list will grow vertically and push the "Continue" button out of the view.

<img width="402" alt="Screen Shot 2565-11-09 at 16 16 29" src="https://user-images.githubusercontent.com/1881481/200791721-4b3c15cb-8ca4-4d85-b48d-a18fd8693a9f.png">

Possible solutions are: 

- Limit the number of sections. 
This is possibly the easiest solution. A limit of six sections seems a good number because it would work well on small desktop screens. The implementation can be done by hiding the button `Add another section` when the limit is reached.
- Limit the max height of the sections and add scrollbars. 
While this solution could sound simple, I think it won't work well because the UX might not be good. Some sections and the scrollbars wouldn't be visible and when a section is added the scroll must be updated.
- Others?  @Automattic/ganon 

Considerations:
- We might not need a limit on mobile

**Comment by arthur791004** [comment]
I'd prefer the first one because it's simple and I assume 6 ~ 8 sections are enough for the new site 🙂

**Comment by miksansegundo** [comment]
@SaxonF what are your thoughts about limiting the number of sections to 6 ~ 8 sections and hiding the button?

**Comment by SaxonF** [comment]
@miksansegundo Sorry for the delay, was AFK. I think I'd lean towards just letting people do what they want and fixing continue button to the bottom. We can monitor post release and see if its something we need to resolve.

Behaviour would be similar to this

https://user-images.githubusercontent.com/1072756/202053201-0cd6b2b7-b05a-455a-96ed-2f991b52e5b8.mp4

**Comment by miksansegundo** [comment]
@SaxonF we can try it. I see some UX issues with that approach:

- the button to add another section and the footer will be out of the screen.
- we'll have to create extra scroll at the bottom of the scrolling area or the last elements will be behind the button.
- after adding a section we have to jump to the bottom of the list scrolling programmatically to show the last section

**Comment by autumnfjeld** [comment]
@Automattic/ganon  Let's watch the data after we ship to users to understand if this is even a scenario we need to worry about.   Going to put this in the backlog.
