### ISSUE TITLE
Themes: Logged-out navigation to signup and back broken again

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#6990]
#### Steps to reproduce
1. In an incognito window, go to http://calypso.localhost:3000/design
2. Click on a theme's '...' button, choose 'Pick this design'
3. Go back

<img width="1414" alt="bildschirmfoto 2016-07-25 um 11 32 02" src="https://cloud.githubusercontent.com/assets/96308/17097751/76cab38a-525f-11e6-9469-f1fc1f6e9fd0.png">

**Comment by ockham** [comment]
We added [this](
https://github.com/Automattic/wp-calypso/blob/641f6d5fd2b446be91474e55f3d83d193c541fce/client/boot/index.js#L382-L399) as a guard for this case with #4992. Unfortunately, that check no longer has us covered, since as of #5872, the entire `signup` section is isomorphic.

**Comment by ockham** [comment]
Maybe the check should be for `isSingleTreeRendered` instead of `isSectionIsomorphic`, since those aren't necessarily identical conditions.

**Comment by ockham** [comment]
cc @ehg

**Comment by ockham** [comment]
Documenting here that moving back and forth between the logged-out theme showcase and `signup` (via 'Pick this design', and back) results in a memory leak due to event listeners:

<img width="1069" alt="screen shot 2016-07-25 at 12 11 37" src="https://cloud.githubusercontent.com/assets/96308/17101989/a2d25682-5277-11e6-8e0a-3d0f4fc85ce7.png">

**Comment by seear** [comment]
A fallback fix, if we find #6991 too risky for now, might be to check explicitly for the `signup` section where we currently check for a non-isomorphic section.
