### ISSUE TITLE
Update the page title of onboarding steps

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#69916]
### Description
The following steps are using the page title `What’s your website about?`:

- Design Picker
- Pattern Assembler
- Pattern Assembler starting point
- Learn the basics

Each step should have a different page title because they are visible on the tab, the back history, and potentially on the page bookmark title.

<img width="553" alt="Screen Shot 2565-11-10 at 12 30 09" src="https://user-images.githubusercontent.com/1881481/201008375-bd47dc92-0e67-4db7-a2cd-3855d06c97d0.png">
<img width="351" alt="Screen Shot 2565-11-10 at 11 59 11" src="https://user-images.githubusercontent.com/1881481/201005587-44821d28-4107-4f71-b234-be95f541349a.png">
<img width="864" alt="Screen Shot 2565-11-10 at 12 29 41" src="https://user-images.githubusercontent.com/1881481/201008384-38b26fd1-fb27-4c12-b4f4-1a3246805723.png">

### Acceptance criteria
- [ ] Update the page title for all onboarding steps after the vertical step

### Implementation
We have to add it on top of the `<StepContainer>`:

```jsx
<>
  <DocumentHead title="The Step Page Title" />
  <StepContainer>
</>
```
As it is done on [the vertical step](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/index.tsx#L63).

@arthur791004 mentioned that we had an issue with that. cc: @Automattic/ganon

**Comment by bangank36** [comment]
I'll look into this issue

**Comment by bangank36** [comment]
Closed as landed
