### ISSUE TITLE
Free Onboarding Flow: Remove domains/plans steps

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#69921]
### Details

- Create a feature flag to hide the upcoming changes
- Remove domains/plans steps from the free flow.
- Roll out changes gradually to a small percentage of users. One means of doing so is by modular division of the user ID. Roll out is dependent on https://github.com/Automattic/wp-calypso/issues/69920

### Related

https://github.com/Automattic/wp-calypso/issues/69899

**Comment by jeyip** [comment]
### Notes:

Looking into modifying the logic below.

https://github.com/Automattic/wp-calypso/blob/322fba7a3e878a98a34fe89efdee5ce8a9a7c86c/client/signup/config/flows-pure.js#L72-L79

 Simply removing the `domains` step _does not_ work. The client side routing middleware expects at least 1 step in the flow ( the 'user' step doesn't count if the user is already logged in )

https://github.com/Automattic/wp-calypso/blob/72a154d63ae49ac119c1cf6c1860ad6cbed238fb/client/signup/utils.js#L68-L70

Thinking about reusing the tailored onboarding flow processing screen to create a temporary view while their auto-generated site is being scaffolded. https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/tailored-flow-processing-screen/index.jsx

Gating behind a feature flag should be easy though. See https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/config/flows-pure.js#L104

**Comment by jeyip** [comment]
@edanzer is exploring an implementation of the free onboarding flow within the stepper framework. We've paused any work on modifying the `/start` flow for now.

cc @Addison-Stavlo

**Comment by edanzer** [comment]
> @edanzer is exploring an implementation of the free onboarding flow within the stepper framework. We've paused any work on modifying the `/start` flow for now.

See PR to set up Free Flow scaffolding here: https://github.com/Automattic/wp-calypso/pull/70350
And see Tracking Issue with initial follow up tasks here: https://github.com/Automattic/wp-calypso/issues/70491

**Comment by Addison-Stavlo** [comment]
It seems this is complete regarding the 2 closed issues noted just above.

Im closing, but please reopen if i am unaware of something else pending here.
