### ISSUE TITLE
Free Onboarding Flow: Create a domain name generator

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#69920]
### Details

Create a name generator similar to what is described here paYE8P-2bD-p2, but audited to be acceptable for facing towards users ( Ex. We don't want the adjective "bitchy" to be included as an adjective )

### Checklist

- [x] Add site name generator logic into WPCOM lib folder
- [x] Set up endpoint to return a random generated name
- [ ] Set up i18n to allow usage of locale
- [ ] Possibly set up Jurassic Ninja to use this new site name generator

### Related

https://github.com/Automattic/wp-calypso/issues/69899

**Comment by agrullon95** [comment]
I'm currently working on adding the site name generator logic and creating an endpoint to return a randomly generated name: D92624-code

Possible name generation ideas:
- Random format everytime (adjective + noun, noun + adverb, etc.).
- Default / Fixed format with username prefix.
- Word combination revolving around username (adverb + adjective + username).

**Comment by agrullon95** [comment]
Random name generator logic was added into lib/managed-subdomains directory: D92934-code
Logic specific to the free flow name generation during site creation step: D96193-code

**Comment by Addison-Stavlo** [comment]
Nice work here @agrullon95! Thank you for all your efforts.
