### ISSUE TITLE
[Newsletters] User logged in to WPCOM, post is blog-subscriber only

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#69930]
In https://github.com/Automattic/wp-calypso/issues/69518 we introduced a check to properly handle the `blog_sub` parameter.

But there is one more case that we are missing:
- User is logged in to WordPress.com
- She is a blog subscriber
- Post is subscriber-only

In that case we have to intercept user_id from the actual logged in session, and check if user is indeed a subscriber.
Somewhere here we have to check if access level is subscribers 
https://github.com/Automattic/jetpack/pull/26417/files#diff-a2de8fe49437410f2cef32a4b1cb8a63cbe0727afd32c4e8312fcc73c913ad8bL75

And instead of checking for valid subscriptions, we have to check for user being a blog subscriber.

Since this code is in Jetpack, and this information only being available on WPCOM, we can probably introduce a filter like we do for `earn_get_user_subscriptions_for_site_id` for consistency

**Comment by n3f** [comment]
@artpi I just want to clarify the test cases for this PR/issue: (in all cases the Subscriber attempts to login to view post).

1. They are a subscriber with their WPCOM email, and the post is subscriber only. They aren't logged in so the email check should pass as normal.
2. Subscriber (logged-out), post is all subscribers, they aren't logged in so the email check should pass as normal.
3. Subscriber (logged-out), post is everyone, no email check required.
4. Subscriber (logged-in via WPCOM), post is subscriber only.  This should use the `blogsub` parameter now.
5. Subscriber (logged-in via WPCOM), post is all subscribers. This should also use the `blogsub` parameter?
6. Subscriber (logged-in via WPCOM), post is everyone, no email check required.

**Comment by artpi** [comment]
@millerf Are you also working on this case?

**Comment by millerf** [comment]
@artpi I just read this one for the first time now. I think this case is covered [here](https://github.com/Automattic/jetpack/pull/27564/files#diff-307b85ed7ed565b3adafed7b241dfeda61a1e6c228480c869c8ddd9d5c77f380R189)
