### ISSUE TITLE
Users: Privacy Information link is broken in Followers section

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#69947]
### Quick summary

When you click the (i) icon in Users → Followers you'll see the link Privacy Information that points to `https://wordpress.com/people/followers/{SITENAME}#privacy` and hence leads to the same page instead of supposedly to an external support page.

![LQXUDR.png](https://user-images.githubusercontent.com/39308239/201315232-c862acb3-4c58-4a96-97a8-6d1e579ff5ab.png)

### Steps to reproduce

1. On a site where you have at least one follower go to Users → Followers
2. Click the (i) icon to expand the modal window
3. Click Privacy Information

### What you expected to happen

An external support page to be opened (maybe https://wordpress.com/support/followers/ but it lacks the Privacy Information section, so maybe it should be another page)

### What actually happened

The same page reloads

### Context

Noticed while working on 5665433-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this. 
- Clicking Privacy Information link reloads the page with #privacy at the end of the URL. 
- I would also expect this link to go to a more useful page, like relevant support documentation.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by sejas** [comment]
- @zdenys , I've fixed this issue on https://github.com/Automattic/wp-calypso/pull/71536
I removed the broken `Privacy Information` and added a `Learn more` link to https://wordpress.com/support/followers/

Thanks for reporting the issue! 🙌 

| **Before** | **After** |
|---|---|
| <img width="614" alt="Screenshot 2022-12-29 at 12 48 52" src="https://user-images.githubusercontent.com/779993/209947272-a53d6bbb-188c-4cea-bc35-db0e0ec1ecd7.png"> |<img width="641" alt="Screenshot 2022-12-29 at 12 25 38" src="https://user-images.githubusercontent.com/779993/209944789-5bc6eedb-b105-41d8-bd73-c7621eb84c5b.png"> |
