### ISSUE TITLE
WC.com products: sync monthly and yearly product IDs

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#69948]
Related Slack conversation: p1668159067812879-slack-C029JEQRVRT

To remove hard-coded items from the Marketplace catalog class, we need to be able to access `wpcom_marketplace_store_product_yearly_id` and `wpcom_marketplace_store_product_monthly_id` meta fields in the jetpack-search index.

Changes need to be made similarly to #69081 and #63903

**Comment by gcsecsey** [comment]
Diff raised: D92154-code
Jetpack PR created: https://github.com/Automattic/jetpack/pull/27376

**Comment by gcsecsey** [comment]
Based on the discussion [here](https://github.com/Automattic/wp-calypso/issues/64891#issuecomment-1243880889), instead of syncing them separately from WC.com to the shadow site, these fields should be added to the dynamic serialized field we've created in #67863. This would require a smaller change in only one codebase and lend us greater flexibility in the long term. I'll add a PR with these changes soon.

**Comment by JulianBustamante** [comment]
@gcsecsey All the marketplace products metadata fields are currently stored in the extra meta field, including `wpcom_marketplace_store_product_yearly_id` and `wpcom_marketplace_store_product_monthly_id` so no changes are required on WCCOM.

**Comment by gcsecsey** [comment]
Thanks @JulianBustamante for the heads up! 🎉  I've checked the WC.com code and the fields are indeed added to the extra field.

I've tried checking the synced field for a products where we already have these fields added, eg. WooCommerce Bookings, but the serialized field didn't show up in Site Explorer: 2e363-pb/#plain I suspect this issue is similar to what we've had here: p9dueE-5AB-p2#comment-8829

I'll look into why the field isn't synced yet and try to fix it, then I'll proceed with updating the mappings in WPCOM.

**Comment by gcsecsey** [comment]
I've added the extra fields meta field to the whitelist so it would be synced, but there were some errors and it still isn't being synced. I've added more details and asked for help here: p9dueE-5AB-p2#comment-8892

**Comment by epeicher** [comment]
After completing task #70108, I think this task can be progressed. I have found that `woocommerce-bookings` product is not correctly indexed in ES (currently investigating why) but for example `shipment-tracking` returns a valid JSON serialized `plugin.extra_fields` ([screenshot here](https://github.com/Automattic/wp-calypso/issues/70108#issuecomment-1319729345))

**Comment by gcsecsey** [comment]
I've raised a diff for this here: D92833-code

**Comment by gcsecsey** [comment]
Thanks for the swift review @epeicher! 🎉

**Comment by gcsecsey** [comment]
Changes are deployed in r256474-wpcom
