### ISSUE TITLE
Stats: Update sections background color

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#69953]
# Development

- [x] Apply new backgrounds to the traffic page.
(#70093)
- [x] Apply new backgrounds to the insights page.
(#70158)
- [x] Apply new backgrounds to the store page.
- [x] Apply new backgrounds to the ads page.

# Design

Part of the modernization project (p1HpG7-igQ-p2).

One thing we're missing is the background colors for each section in Stats. This is a global change that should be applied to all Stats pages.

Here are the specs:

- **Header**: #ffffff
- **Highlights**: #fbfbfb
- **Page body**: #fdfdfd

![Image](https://user-images.githubusercontent.com/390760/201377225-273ff0eb-6e0d-43f0-9caa-84297f37b136.png)

**Comment by jsnmoon** [comment]
@wilmersondasilva: I updated this PR with subtasks for your reference.
