### ISSUE TITLE
Guided Tours / First View: don't collide

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#6996]
Not an issue currently, as no guided tour is enabled in production.

![screen shot 2016-07-25 at 14 19 07](https://cloud.githubusercontent.com/assets/150562/17104190/b58a6b64-5279-11e6-9eb0-2499cbfc1137.png)
## Preliminary thoughts
- Treat First View (FV) displays like guided tours
- That way, a single selector `hasRecentlySeenTours` ("recently" could be defined as a couple of minutes) could be checked in Guided Tours (GT) selectors, so that no new tour is initiated if the former returns `true`.
- That said, there are different UX considerations for FV vs. GT — for instance, it makes sense to show different FV dialogs one after the other for a new user that is discovering Calypso's sections (e.g. lands in `/stats`, sees FV for Stats, switches to `/pages`, sees FV for Pages), but it doesn't make sense to do the same for GT.
- So maybe two separate conditions are to be checked — `isShowingFirstView` and `hasRecentlySeenTours` by GT?

cc @mattsherman

**Comment by mattsherman** [comment]
> Not an issue currently, as no guided tour is enabled in production

@mcsf Just double-checking... so, this isn't an issue presently, and you are planning on addressing it as part of the GuidedTours M3?

Based on the different UX considerations you mentioned, I agree that having the two separate conditions checked by GT would be best.

**Comment by mcsf** [comment]
> Just double-checking... so, this isn't an issue presently, and you are planning on addressing it as part of the GuidedTours M3?

Correct.

> Based on the different UX considerations you mentioned, I agree that having the two separate conditions checked by GT would be best.

👍, thanks.

**Comment by lsinger** [comment]
I agree `isShowingFirstView` would be great to have. 

What would `hasRecentlySeenTours` do, exactly? Check whether any first view or tour has been seen in the past, say, 3 minutes and stop any tours from starting if so? What situation would we want to avoid with this -- a tour coming up as soon as a first view is clicked away or a different tour ended? 

As a note to myself mostly: this would likely go into guided tours's `selectors.js` and would not be needed to be specified for each single tour.

**Comment by mcsf** [comment]
> What would hasRecentlySeenTours do, exactly? Check whether any first view or tour has been seen in the past, say, 3 minutes and stop any tours from starting if so? What situation would we want to avoid with this -- a tour coming up as soon as a first view is clicked away or a different tour ended?

Yes, that's what I envisioned, so as to avoid to avoid overburdening the user.

**Comment by lsinger** [comment]
This could be useful: https://github.com/Automattic/wp-calypso/blob/f7e3f5124aeb82fdaa0cacee96d000fb147786e9/client/state/ui/first-view/selectors.js#L81
