### ISSUE TITLE
[Bug]: Client-side estimation of Jetpack Search tiers in checkout can be wrong

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#69964]
### Quick summary

Parts of checkout seem to use a client-side estimation of the Jetpack Search tier (rather than the actual one from the server) which can lead to issues like this in checkout:

![image-2-1](https://user-images.githubusercontent.com/235183/201404324-0c933625-6655-4b64-86ae-e3d78ec6922b.png)

That looks very similar to the bug that this issue was trying to fix:
- https://github.com/Automattic/wp-calypso/pull/63640

Perhaps it didn’t fix it in all cases? The code in that pull request introduced a `getSearchProductTierPrice()` method which looks like it’s trying to estimate the number of search records on the client side...

https://github.com/Automattic/wp-calypso/blob/dbd281a682c68d607a3506d5505387e067218b50/client/state/products-list/selectors/compute-full-and-monthly-prices-for-plan.ts#L101-L112

I can imagine there being scenarios where that doesn’t match the actual number of search records calculated on the server. (For example, in the above screenshot, the site is actually on the second tier, $10, but the variant picker seems to be estimating it as on the first tier, $5).

Suggestion to fix this would be to remove that code and use the actual quantity of search records returned by the server to calculate the tier (I’m almost 100% sure this is available in the shopping cart data) or even just use the direct monthly price (which might be available in the shopping cart too, but I’m not positive).

### Steps to reproduce

I don't know how to reproduce this exactly, but we've received reports at pNPgK-6aW-p2.  Presumably there are cases where the client-side estimate of the number of posts used to calculate the Jetpack Search tier actually doesn't match the number used on the server.

### What you expected to happen

The two indicated prices shown in the shopping cart should always match.

### What actually happened

The two indicated prices shown in the shopping cart do not always match.

### Reproducibility

Intermittent

**Comment by gibrown** [comment]
@jsnmoon @kangzj adding this to the launch list of issues. Feels like after the launch we should fix this so it works correctly using the pricing from the backend.

**Comment by sirbrillig** [comment]
This may be fixed by https://github.com/Automattic/wp-calypso/pull/70452

**Comment by gibrown** [comment]
@sirbrillig that only displays monthly vs yearly pricing right? Doesn't seem to display the total numbers of records/requests.

**Comment by sirbrillig** [comment]
🤔 I may be confused, but I think this issue is about the fact that the price displayed in the line item (which comes from the shopping cart and therefore hopefully has the right number of records) is sometimes out-of-sync with the price displayed in the billing term variant picker (which comes from complex client-side calculations). https://github.com/Automattic/wp-calypso/pull/70452 changes the variant picker to get its prices also from the shopping cart and therefore should (hopefully) always be accurate.

**Comment by gibrown** [comment]
Oh, I see... yes I think I was confused by a separate issue being discussed elsewhere. This is great, sorry for the confusion.
