### ISSUE TITLE
NUX plans a/b test ideas

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#6997]
Let's add simple test ideas to this github issue, and as we tackle them, check off the boxes and add a link to the github issue that implements the test.
- [ ] display FAQ
- [x] ~~show called-out plan with larger larger/magnified column ("embiggening")~~
- [ ] open tooltips on hover
- [ ] test calls-to-action _above_ the plan descriptions
- [ ] add "best for [so-and-so]" to the plans for better social targeting
- [ ] display plans in order from most-expensive to least-expensive

**Comment by apeatling** [comment]
I will put together mockups for these where applicable.

**Comment by apeatling** [comment]
**"show called-out plan with larger larger/magnified column ("embiggening")"** -- I think we should scrap this test. We have the premium theme well highlighted now with the buttons a different color. If we start changing the size of this, then features and headers stop lining up.

**Comment by apeatling** [comment]
test calls-to-action above the plan descriptions

![cta-top](https://cloud.githubusercontent.com/assets/1464705/17152297/07a27f9c-532c-11e6-9418-9ecd5b0ba29c.png)

**Comment by apeatling** [comment]
add "best for [so-and-so]" to the plans for better social targeting

Personal
- **Best for Personal Use:** Boost your website with a custom domain name, and remove all WordPress.com advertising. Get access to high quality email and live chat support.

Premium
- **Best for Entrepreneurs & Freelancers:** Build a unique website with advanced design tools, CSS editing, lots of space for audio and video, and the ability to monetize your site with ads.

Business
- **Best for Small Business:** Power your business website with unlimited premium and business theme templates, Google Analytics support, unlimited storage, and the ability to remove WordPress.com branding.

**Comment by apeatling** [comment]
I'm working on a PR for a test with the new descriptions.

**Comment by rralian** [comment]
> I'm working on a PR for a test with the new descriptions.

Now that we're about done with consolidated tests across calypso and our php codebase, I think this is something we'd probably want to implement with the new system, so we can keep the content of all the plans pages in sync.
