### ISSUE TITLE
Gifting: enable gifting for a11n's

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#69977]
Once https://github.com/Automattic/wpcomsh/pull/1141 and https://github.com/Automattic/jetpack/pull/27374 are merged, let's enable gifting for a11n's.

 - [x] Enable the subscription-gifting flag in wpcalypso and staging environments. Alternatively we could just remove the flag entirely and show the option to all users early.
 - [x] Replace the gifting_banner flag _GET check in wpcom/wpcomsh with a proxy check:

```
if ( ( defined( 'AT_PROXIED_REQUEST' ) && AT_PROXIED_REQUEST ) || 
  ( defined( 'A8C_PROXIED_REQUEST' ) && A8C_PROXIED_REQUEST ) ) {
```

**Comment by DustyReagan** [comment]
> Replace the gifting_banner flag _GET check in wpcom/wpcomsh with a proxy check:

wpcom: D92328-code
wpcomsh: 1146-gh-Automattic/wpcomsh

**Comment by DustyReagan** [comment]
> Enable the subscription-gifting flag in wpcalypso and staging environments.

Calypso: https://github.com/Automattic/wp-calypso/pull/70012
