### ISSUE TITLE
Marketplace: vendor signup refactor to move code in product vendors plugin

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#69998]
Related: p1667844178851579-slack-C029JEQRVRT

**Comment by cpapazoglou** [comment]
@JulianBustamante is this something you can wrangle?

**Comment by cpapazoglou** [comment]
It seems that this part needs to be extracted in hook logic
`/plugins/woocommerce-product-vendors/includes/class-wc-product-vendors-shortcodes.php#L72-L80`

**Comment by JulianBustamante** [comment]
@cpapazoglou I'm looking into it.

**Comment by cpapazoglou** [comment]
@JulianBustamante have you created the follow up issue here for adding the code in the plugin itself?

**Comment by JulianBustamante** [comment]
@cpapazoglou  I created the PR on the woocommerce-product-vendors repository https://github.com/woocommerce/woocommerce-product-vendors/pull/773
