### ISSUE TITLE
Site Picker: 'Add New WordPress' option is hard to find with lots of sites

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#7]
There is an 'Add New WordPress' option at the bottom of the Site Picker.

If you have lots of sites, this is hard to find as there is a lot of scrolling.

Options to resolve this include having it in a fixed position, or moving it elsewhere (eg. switcher prompt)

<img width="320" alt="add_new_wordpress" src="https://cloud.githubusercontent.com/assets/128826/11200366/52741b74-8d21-11e5-9864-cf32403e4110.png">

**Comment by maxfenton** [comment]
Looks like they moved this button above the list of sites, now.

Does this button let you add an existing site to the app, or just create a new Wordpress site on wordpress.com ? Seems to be the latter. — trying to figure out if that's a bug or (otherwise) how to add a second, existing site to the app.

**Comment by mtias** [comment]
Closing as the button is fixed positioned over the list of sites now.

**Comment by alisterscott** [comment]
@maxfenton:

> Does this button let you add an existing site to the app, or just create a new Wordpress site on wordpress.com? Seems to be the latter. 

Yes, it just allows someone to register a new WordPress.com site.

> trying to figure out if that's a bug or (otherwise) how to add a second, existing site to the app

At the moment, AFAIK, the only way to edit which sites you belong to which are shown in this list is to use a mobile app edit function, or use wp-admin (wp-admin/index.php?page=my-blogs)
