### ISSUE TITLE
Menus: poor UX around adding dead menu links before content exists

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#70]
Menus: poor UX around adding dead menu links before content exists

As compared to wp-admin, it's easy in Calypso to add a menu item that doesn't link to any content.

Reported in Slack by WP.com support staff (p1447089334000010-slack-triage, see also 964855-t):

I've noticed some weirdness in Custom Menus in Calypso: I've had a few users with menus containing dead links. The Calypso Menu screen allows users to add new items to the menu, specify the menu link title, but then add the item without actually selecting a page/category/tag, etc.

When users then later do publish the pages the published pages are not being added to the existing links in the menu, leading to quite a lot of confusion. This is especially an issue with new users who don't realize they must create content before adding it to a menu. As a result they spend considerable time creating a menu that doesn't work and basically has to be redone from scratch once they have the content.

It's not related to any specific browser. I've been noticing the issue of dead menu links or empty menu links redirecting to the home page or a post with several users over the past couple of weeks, but only figured out the cause today when I got a ticket where the user had added over ten "pages" to the menu, while only having the default About page published on her site.

To reproduce:

1. Create/edit a menu via My Sites. Make sure it's set to one of the site's menu locations.
2. Add a new menu item. It can be a page, post, category, tag or link.
3. Optionally edit the menu item title, but don't select a post/page/category or insert a link URL.
4. Select Add Item, and save the menu.

In menu editing flow, the item is saved without linking to any content:
![screen shot 2015-11-09 at 10 26 46](https://cloud.githubusercontent.com/assets/66797/11041950/b12f1976-86d1-11e5-808f-d4058b1e1c8d.png)

Front-end menu items links to latest published post:
![screen shot 2015-11-09 at 11 04 09](https://cloud.githubusercontent.com/assets/66797/11041955/b4b316d8-86d1-11e5-8326-f8b3f6f7500b.png)

On the site of the end user who submitted the ticket above, the menu items are completely dead links. The user doesn't have any posts published, which explains why the menu links are dead.

On another WP.com test site, the menu items are clickable but link only to the most recent published post and not to the related page. 

For comparison, in WP-Admin it's not possible to add any item to the menu without selecting existing content (or adding a URL in the case of custom links) first. This prevents menu items being added before the corresponding content exists.

**Comment by marekhrabe** [comment]
I've just had a support ticket where the person had all the content ready, but they created menu links with just a title and no location. I hope we will be able to add some validation for this to ease the confusion a little bit.
