### ISSUE TITLE
Editor: support parsing hashtag-style tags and other plugin filters from post content

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#700]
For sites using Calypso to edit a P2 themed site (like many Automattic and WP Make sites) it'd be nice if the editor allowed setting inline tags in the post content.

This mimics how an author would add a tag from the front-end editor of a P2 site.

Example:

```
This is the post content.

#tag2 #tag3
```

In this scenario, after saving the post — `#tag2` and `#tag3` would be tags on the post.

@nylen says

> The P2 plugin [parses tags from the_content](https://github.com/Automattic/o2/blob/master/inc/tags.php#L15) when the post is **saved** and [turns tags into links](https://github.com/Automattic/o2/blob/master/inc/tags.php#L18) when the post is **viewed**.  We must not be hitting that first bit of code when we save a post from the REST API.

Note: This seems to only occur when editing on WordPress.com sites. Jetpack-enabled WordPress.org sites running P2 theme (and o2 plugin) don't seem to have this issue.

**Comment by lancewillett** [comment]
Seems to me in testing this, and also "unresolved" status in the O2 plugin "todo" module — that the plugin itself isn't loaded, so the `transition_post_status` actions added in O2 plugin files are not executed.

Those hooked actions **do** fire on a Jetpack site, posting from Calypso — so this is only with WP.com sites.

**Comment by lancewillett** [comment]
Similar to tags not auto-linking, when you use a feature like Automattic's internal P2 "x-post" formatting it doesn't work. Something like `+dotcomp2` should auto-link and create a cross-post. So that points to something in the o2 plugin is hooked to a certain filter, say on post publish, and the API request that fires from Calypso's publish event isn't causing the filters to run.

**Comment by gwwar** [comment]
@lancewillett is this currently assigned to any teams? It's pretty confusing when an xpost doesn't work from the Calypso editor.

**Comment by lancewillett** [comment]
@gwwar Not that I know of... @jblz and the Samus have it on their radar in general but aren't actively working o at it right now. Noting that this internal thread has a bit more detail: p58i-5nF-p2.

**Comment by lancewillett** [comment]
Closing as x-posting and tagging now work as expected.
