### ISSUE TITLE
Instagram Posts cut and repeated

### ISSUE THREAD

**Issue by ckmccoy2** [Automattic/wp-calypso#70005]
### Quick summary

Videos being cut and repeated on this ticket: 5703664-zd

### Steps to reproduce

1. Add an Instagram block to a page or post on a simple site
2. Add post link in ticket notes

### What you expected to happen

Post to show as it does in instagram

### What actually happened

formatting is odd where a portion of the video appears to be cut and repeated

### Context

Seems to only happen for this user, not able to repeat behavior using posts/reels from other user accounts

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

One

### Workaround details

Asked them to see if post appears correctly using latest instagram posts block

**Comment by rickmgithub** [comment]
The original reporter added some further details about how they make the videos

"I just record the videos with my phone, generate subtitles, and save them as mp4 files. The subtitles are burned into the videos, meaning they are not an additional .srt file but simply visual input added to the video. So the videos are regular mp4 files. Then I upload them as reels on Instagram via the Meta Business Suite app. By using the Latest Instagram Posts block, I don't get the same problem. It looks just fine."

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate the issue with the link from the user report, but I was not able to replicate this issue with other links from Instagram. 

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @ckmccoy2 Please feel free to reopen if you are able to replicate this with other Instagram links. I would recommend following up with the user to let them know they can continue using the Latest Instagram Posts block as a workaround or consider reporting this through internal channels. Thanks!
