### ISSUE TITLE
Sometimes Apple Pay/Google Pay displays "This payment type is not supported"

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#70019]
In the past few days (starting on Oct. 27), we've seen 9 instances of the fatal error "This payment type is not supported" show up for clients. This error is thrown when the payment button for the Apple Pay or Google Pay payment method is rendered and Stripe tells us that the payment is not allowed.

https://github.com/Automattic/wp-calypso/blob/ac5971e98b0249bdb7b4b617e3b40cf65ae128ba/packages/wpcom-checkout/src/payment-methods/apple-pay.tsx#L88-L92

In theory this message should never occur because there is code to ask Stripe if those payment methods are allowed before the payment method is rendered at all:

https://github.com/Automattic/wp-calypso/blob/ac5971e98b0249bdb7b4b617e3b40cf65ae128ba/client/my-sites/checkout/composite-checkout/components/checkout-main.tsx#L330-L340

**Comment by sirbrillig** [comment]
See this Slack thread for a link to the errors in our logs: p1668284243832319/1668283204.862969-slack-C096PD42U

**Comment by michaeldcain** [comment]
From planning:

This is lower priority since users have the ability to checkout with other payment methods. Moving it to the backlog until we have more bandwidth.

**Comment by sirbrillig** [comment]
There's been another spike of five of these today. Once again, all for different users.

**Comment by sirbrillig** [comment]
I have an idea for something to try: 

`useIsWebPayAvailable()` currently does not provide the `displayItems` when it does the initial check for web payment methods. Later, `usePaymentRequestOptions()` does include those properties when it's called inside the payment method button itself. It may be that providing those properties in `useIsWebPayAvailable()` would resolve this issue by hiding Apple Pay in more cases where it's not available.

Working on this in https://github.com/Automattic/wp-calypso/pull/70201

**Comment by sirbrillig** [comment]
Another instance of this today (p1669409105840389-slack-C096PD42U) even though it should be even more impossible now that https://github.com/Automattic/wp-calypso/pull/70201 is merged. 😭 

Maybe we need to figure out some way to use the _same_ payment request instead of creating two. Right now this would be hard because we'd need to create the payment request in `CheckoutMain` to determine if the payment method should be shown, then probably pass it into the payment method itself for use by the button. However, the payment request includes the completion callback, and that callback is only available inside the payment method. 

🤔 There may be some other way to structure this.

**Comment by sirbrillig** [comment]
Many more instances now. About 1 or 2 a day.

One idea I had was to only create the paymentRequest once, in `CheckoutMain`, and thread it down to the payment method. Since it needs to have the `onSubmit` handler already set, we could use `useProcessPayment` to get it manually. However, it turns out this won't work because `useProcessPayment` uses the context provided by `CheckoutProvider` which is also the component that needs the payment methods as a prop.

**Comment by sirbrillig** [comment]
New idea: let the payment method buttons decide for themselves if their payment method should be visible: https://github.com/Automattic/wp-calypso/pull/70614
