### ISSUE TITLE
Stats: Quickly moving mouse across bar graph leaves ghost tooltips

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/wp-calypso#7003]
1. Visit https://wordpress.com/stats/day/www.your-domain.com
2. Quickly move mouse from left to right across the bars.
3. Note the left behind empty tooltips.

I can reproduce in both Firefox 49.0a2 (2016-07-24) and Chrome 51.0.2704.103.

![stats_ _viper007bond com_ _wordpress com_-_firefox_2016-07-25_12-27-16](https://cloud.githubusercontent.com/assets/406254/17114454/df1aed2a-5263-11e6-9469-a9cb05c142a0.png)

**Comment by gwwar** [comment]
This should be fixed by #7217
