### ISSUE TITLE
Stepper eCommerce flow: Define the URL users should be redirected at the end of the flow

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#70044]
When the user finished the new eCommerce flow, where should they be redirected to?

*We may have to wait for the Woo installation.

**Comment by daledupreez** [comment]
Per a discussion @nelsonec87 and I had yesterday, we think this should redirect users to WooCommerce onboarding. As he pointed out in the task description, this will likely need to be deferred until WooCommerce has been installed on the site.

**Comment by nelsonec87** [comment]
Implemented in https://github.com/Automattic/wp-calypso/pull/69974/
