### ISSUE TITLE
Stepper eCommerce flow: integrate the monthly/yearly parameter

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#70045]
Use the [new `recur` param](https://github.com/Automattic/wp-calypso/pull/69932) in the new eCommerce flow.

**Comment by blackjackkent** [comment]
@SaxonF @daledupreez @nelsonec87 Looking at the designs at 9XooISHKU1phs4Ju2Yyy5p-fi-2407%3A31088&t=YOZuFBNqcwv0V9FB-0 it feels like the main potential visual difference here is simply choosing whether "Pay monthly" or "pay annually" is autoselected for the user on the plan selection page. Are there other visual differences we want to incorporate between the monthly and yearly versions of the flow?

**Comment by daledupreez** [comment]
@blackjackkent, I think there are two aspects to using the new parameter:

1. For our MVP, we need to add the correct eCommerce plan to the cart within the flow. More specifically, we need to load either the monthly or yearly eCommerce plan to the cart based on the value of the new setting.
2. Once we have a clearer outline for supporting multiple eCommerce plans (or plan tiers) and we need a plans page to our flow, we can then integrate the setting into our plans page.

For now, we only need the work in (1) above -- I don't think it's worth starting on (2) for a while.

**Comment by nelsonec87** [comment]
Implemented in https://github.com/Automattic/wp-calypso/pull/69974
