### ISSUE TITLE
Calypso: Inline SVG data for mobile QR code

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#70055]
Per [this comment](https://github.com/Automattic/wp-calypso/pull/70028#discussion_r1023458946), it would probably be better to have the SVG data in the bundle.

**Comment by a8ck3n** [comment]
After much trial and error, I ended up adding the QR codes as PNGs. Despite my best efforts, I wasn't able to get clean SVG data out of the online generators I tried. Most of them had had hard-coded sizes which didn't scale easily/consistently in my testing. Using PNG was pretty straightforward and the data size was still quite small though, so maybe not an issue?

**Comment by jsnmoon** [comment]
Could you spin up a draft PR, @a8ck3n? I'm sure the team could provide feedback with ideas for improvement!
