### ISSUE TITLE
LaunchPad - Update copies (title, subtitle, CTA)

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#70069]
We need to update title, subtitle, and CTA for the LaunchPad.

For Newsletter we should have:
Title: You’re all set to start publishing.
Subtitle: Why not welcome your readers with your first post?

For link-in-bio we should have:
Title: You’re ready to link and launch
Subtitle: All that’s left is to add some links and launch your site.
CTA: Launch your site

![Screen Shot 2022-11-16 at 9 09 43 AM](https://user-images.githubusercontent.com/28742426/202202770-482ec07b-6501-4a0f-abf6-f4296f71a8af.png)

**Comment by agrullon95** [comment]
Changes merged in:  https://github.com/Automattic/wp-calypso/pull/70123
