### ISSUE TITLE
Stats: Random "0" in page during loading

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/wp-calypso#7006]
I'm having trouble reproducing this but I did get a screenshot of it, so I'm opening an issue for it incase someone can manage to track it down.

This was for a Jetpack site if it matters.

Look above "Today's Stats":

![stats_ _wordpress com_-_firefox_developer_edition_2016-07-25_12-26-52](https://cloud.githubusercontent.com/assets/406254/17116424/91ff64c2-526c-11e6-8d80-a0c60b91c9ca.png)

**Comment by timmyc** [comment]
I believe this was fixed in #9117
