### ISSUE TITLE
[Bug]: Logged-out /themes page only shows 20 themes on All filter

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#70060]
### Quick summary

The /themes page, on a logged-out user (e.g. on incognito), only shows 20 themes, on the default All filter. However, when we select the Free / Premium filter, more than 20 themes are shown, which does not make sense.

### Steps to reproduce

1. Open a new incognito window.
2. Go to wordpress.com/themes.

### What you expected to happen

I see more than 20 themes.

### What actually happened

I only see 20 themes.

### Reproducibility

Consistent

**Comment by fushar** [comment]
After some investigation, this bug is first introduced (accidentally, I believe) by #66431 (Add themes subtree back to the server-side redux cache).

The PR (re-)adds /themes results to the cached SSR data. Unfortunately, the default limit is 20:

https://github.com/Automattic/wp-calypso/blob/9fc87b67031891e9fd9545ccf44963a703370586/client/state/themes/constants.js#L5

which causes the default (logged out) themes result to only have 20 themes.

We can revert the PR; or, alternatively, we can just increase the default limit. I will submit a PR soon.

cc: @Automattic/ganon @noahtallen

**Comment by noahtallen** [comment]
Makes sense. We _cannot_ remove caching from this route so another solution sounds good

**Comment by fushar** [comment]
Fixed in: D92975-code.
