### ISSUE TITLE
Plans: Missing tooltip description for developer tools

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#70078]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/plans
2. Click on the "SFTP, SSH, WP-CLI, and Database access" info tooltip

#### What I expected

The description text to show. We can coordinate the copy with @that-mike-bal and/or our PAs.

#### What happened instead

An empty tooltip box appears.

#### Browser / OS version

All.

#### Screenshot / Video

<img width="509" alt="Screenshot 2022-11-16 at 5 55 10 PM" src="https://user-images.githubusercontent.com/1182160/202244571-fcf2d168-599d-4b26-b0fa-ed2a423ce093.png">

**Comment by vindl** [comment]
Description should be added here: fbhepr%2Skers%2Spnylcfb%2Spyvrag%2Syvo%2Scynaf%2Ssrngherf%2Qyvfg.wf%3Se%3Q726q663q%26zb%3Q22048%26sv%3Q679%231393-og

**Comment by that-mike-bal** [comment]
I think we could go with something like 
"A set of developer tools that give you more control over your site, simplify debugging, and make it easier to integrate with each step of your workflow."
