### ISSUE TITLE
CPT: Testimonial Shows "Page Options" in sidebar

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#7007]
In `<EditorDrawer />` the [logic](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/editor-drawer/index.jsx#L297) to show "Page Options" currently keys off of the post types `supports.page-attributes` boolean.  As such the full accordion with parent, page template, and order are shown - under the heading of "Page Options" ( which needs to be post-type aware, perhaps just "Options" for non pages ):

![new_testimonial_ _testingtimmy2_wordpress_com_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/17116595/535fa6a4-526d-11e6-92bc-f8eda3f6f74f.png)

In wp-admin, the only page-attribute that is exposed is the `order`:

![add_new_testimonial_ _ _wordpress](https://cloud.githubusercontent.com/assets/22080/17116615/7ceb9410-526d-11e6-9f9a-d0bc255aa663.png)

Do we need more granularity in `post-type.supports` object? /cc @aduth

**Comment by aduth** [comment]
Updates are needed to the render logic, but we have all of the information we need:

- Parent page: Should only be shown if `postType.hierarchical` is `true`
- Page template: Should only be shown if `postType.name === 'page'` ([reference](https://github.com/WordPress/WordPress/blob/de5a513027e852de6597b6cbfdc3ef94ef56f8ed/wp-admin/includes/meta-boxes.php#L820-L852))
- Order: Should only be shown if `postType.supports[ 'page-attributes' ]` is `true`
