### ISSUE TITLE
Stats: Add tooltips to the 7-day highlights section

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#70089]
# Development

- [x] Apply tooltips to show the full, original value when the highlight card component shortens the value for display:
( https://github.com/Automattic/wp-calypso/pull/72972 )
> <img width="375" alt="image" src="https://user-images.githubusercontent.com/4044428/202321629-52281dd8-93f2-4608-979c-01cdef3677a2.png">

- [x] Replace `Compared to previous 7 days` next to the 7-day highlights header with the following tooltip:
( https://github.com/Automattic/wp-calypso/pull/72987 )
> <img width="490" alt="image" src="https://user-images.githubusercontent.com/4044428/202321515-87ad4f8e-13b2-47a5-890f-fc7963db2fe6.png">

# Design

See this [design review](https://github.com/Automattic/wp-calypso/pull/69862#issuecomment-1309436978).

![Image](https://user-images.githubusercontent.com/4044428/201427398-bf23ff92-ea0e-4cf4-a96c-9c869ad8d483.png)

**Comment by jsnmoon** [comment]
@jeffgolenski: Have there been any updates to the design for this feature?

**Comment by grzegorz-cp** [comment]
Tooltips showing the numbers can be introduced by removing `showValueTooltip` property from https://github.com/Automattic/wp-calypso/pull/71159/files#diff-8f269ba2c186ae08850fb173cb509c692af6d2e73afb5f3a2bb5ce3c1f746081R57

**Comment by dognose24** [comment]
I have added the [maintenance task](https://github.com/Automattic/wp-calypso/issues/72988) for the `client/components/tooltip/` replication to improve the reusability. We could defer the refactor to the maintenance project period. cc @jsnmoon

**Comment by jsnmoon** [comment]
I went ahead and removed the tooltip component relocation from this issue. Feel free to close this PR once #72987 ships, @dognose24!
