### ISSUE TITLE
Logged-out sign-up flows are broken for users that already have an account

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#70091]
### Quick summary

This definitely affects the sign-up flow for logged-out theme showcase and probably affects other similar sign-up flows too.

Users who already have an account but aren't logged in can go through various sign-up routes, including theme selection (via wordpress.com/themes). As part of this sign-up process users are prompted to register. There is no option for users to login until they enter their email address in the registration field, which will prompt them to login. After logging in the process will resume, but ultimately get stuck on a calypso screen saying something like ‘Step 5 of 5: Planning the next chess move’

Initial finding: pekYwv-K-p2#comment-22 initial discussion: p1668639625213129-slack-C048CUFRGFQ

### Steps to reproduce

1. Go to wordpress.com/themes while logged out
2. Choose a theme
3. Choose a free domain
4. Choose a free plan
5. Enter the email address of an existing account on the registration page
6. Follow link to login on the error message
7. Login (with 2fa)
8. Get stuck on ‘Step 5 of 5: Planning the next chess move’ for five minutes
9. Refresh page, watch it zip straight through to Step 5 and get stuck again

### What you expected to happen

I expected to have an option to login (rather than using the registration form and following a link) and to ultimately get a new site using the theme I selected

### What actually happened

I got stuck on ‘Step 5 of 5: Planning the next chess move’ for many minutes until I ran out of patience

### Context

Exploratory testing

### Theme-specific issue?

No, tried with multiple themes.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Go back in your browser history and start the whole process from scratch losing any work you have entered.

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this in my test. I got stuck on "Planning the next chess move Step 5 of 5" 
- Noting that I got stuck on the "Planning the next chess move" step in other testing today when I attempted to create a new site, but when I refreshed the page, I was able to continue with the site creation flow. I remember this because I thought, "they are really thinking hard about that chess move" :)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by dsas** [comment]
I've opened a PR at #70177. I'll run some more tests but it seems to fix the problem for the logged-out theme flow, as well as the domains flows.

A different, simpler and more robust "fix" would be to avoid the problem entirely and move the user step to the beginning of the process.

**Comment by dsas** [comment]
Reopening, #70177 fixed this for domains but #70467 is needed for themes
