### ISSUE TITLE
Editor: can't add tags via sidebar for P2 themed sites (both Jetpack, WP.com)

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#701]
The Calypso editor won't save tags added via the sidebar for WP.org sites running [latest o2 plugin](https://github.com/Automattic/o2) and [P2 theme](https://wpcom-themes.svn.automattic.com/p2-breathe/).

![drop-tag](https://cloud.githubusercontent.com/assets/66797/10234720/67bf35d6-684b-11e5-9558-75c47950e822.gif)

<sup>Tested in Safari 9.0.1 on OS X 10.11.1.</sup>

Steps to repeat:
1. Try to add tags via the new editor's tag sidebar "Categories & Tags" menu.
2. The tags don't appear as tags with the published post, and are removed from the "Categories & Tags" menu upon save.
3. Tags _should_ work both ways: 1) added as inline tags in the post (o2 plugin [finds these upon save](https://github.com/Automattic/o2/blob/master/inc/tags.php#L15)) and 2) as tags attached to the post in the editor via the "Categories & Tags" menu.

Note: WordPress.com sites work just fine for this functionality — but have a mirror opposite bug. :) #700 — they don't allow saving tags with the inline `#` notation.

**Comment by p3ob7o** [comment]
Noticed the same behaviour on WordPress.com when posting from the Calypso Editor to a WordPress.com site running P2 as the theme. Inline tags will work, tags in the sidebar will be deleted upon publishing (they persist when saving drafts though).

**Comment by stephanethomas** [comment]
I've encountered this issue today as well, as mentioned in p1518527251000299-slack-flow (see the provided video there). When I check the browser's console there is no error, the API call seems well-formed, and is successful. However the API doesn't return the new tag in the response.

**Comment by rickybanister** [comment]
I've noticed this issue recently as well. If I don't remember the wording of a tag I use the sidebar's typeahead, and later realized the tag didn't apply. I believe @davidakennedy had the same problem recently.

**Comment by lancewillett** [comment]
This is fixed quite a while ago.
