### ISSUE TITLE
[Bug]: Can't got back in the new importer flow

### ISSUE THREAD

**Issue by wojtekn** [Automattic/wp-calypso#70100]
### Quick summary

When I use [the new import-focused flow](https://wordpress.com/start/import), I observe different behavior when compared to the old flow:
- Back button does not do anything
- there is no progress bar at the top

Those work fine when I use [an old import flow](https://wordpress.com/start?source=sites-dashboard&ref=smp-import).

### Steps to reproduce

1. Start at https://wordpress.com/start/import
2. Choose a domain
3. Choose a free plan

### What you expected to happen

* "Back" button navigates to the previous page
* there is a blue progress bar displayed at the top of the page

![Screen Shot 2022-11-17 at 08 59 37](https://user-images.githubusercontent.com/727413/202390818-94d9ecd5-c54a-4cfa-898c-49b4d3ad21fe.png)

### What actually happened

* "Back" button doesn't work
* there is no progress bar

![Screen Shot 2022-11-17 at 09 00 33](https://user-images.githubusercontent.com/727413/202390798-88a6a01e-7124-4dbf-aef3-15f42541c61f.png)

### Browser

Google Chrome/Chromium

### Context

pdKhl6-Jm-p2#comment-1221

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

I can use the browser back button.

**Comment by bogiii** [comment]
Hey @wojtekn,

Thanks for reporting this issue to us!

I talked to @vishnugopal, and we agreed that the Back button should not be there since the user in the previous steps creates a website, so returning him probably will cause confusion since the website has already been made.

We decided to hide the back button from the initial import screen.

Fixes are here: https://github.com/Automattic/wp-calypso/pull/70197

**Comment by wojtekn** [comment]
@bogiii, thanks for checking it. I've tested how it works now - I can't see the "Back" button anymore, and I see your point saying that the Back button doesn't make sense there.

However, I can still get stuck - I chose my slug in the previous step, but now if I change my mind and don't want to import any more, I can't go back, and I can't proceed further.

Would it make sense to add "Skip to dashboard" or another way to skip the import? We have this on the "What are your goals?" page.

**Comment by bogiii** [comment]
> Would it make sense to add "Skip to dashboard" or another way to skip the import? We have this on the "What are your goals?" page.

It absolutely makes sense. I'll see how it works on the goals page and we can implement the same solution by adding an additional "Skip to dashboard" button.

Ticket: https://github.com/Automattic/wp-calypso/issues/70484

cc @vishnugopal

**Comment by bogiii** [comment]
Hey @wojtekn,

The navigation `Skip to dashboard` button has been added and deployed.

**Comment by wojtekn** [comment]
@bogiii thanks, it works well now.  There is no progress bar at the top, and if I change my mind at the import step, I can use the "Skip to dashboard" link to finish the process early.
