### ISSUE TITLE
Plans: redirect logged-out /plans to /pricing

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7010]
Sounds like we have quite a few links to our `/plans` pages, but they only work when logged in. When a user is logged-out and loading the `/plans` route (_not_ the `/plans/:site` route), we should redirect them to `https://wordpress.com/pricing` which will require a full page reload, as that page is not built by calypso.

**Comment by gwwar** [comment]
For reference here are the requirements for moving /plans to being SSR ready.
https://github.com/Automattic/wp-calypso/blob/master/docs/isomorphic-routing.md
https://github.com/Automattic/wp-calypso/blob/master/docs/server-side-rendering.md

**Comment by gwwar** [comment]
We still need #7041 for local dev, but looks like we still redirect in prod
