### ISSUE TITLE
[Premium content] Specific UI for the gate of paid content

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#70119]
### Context

When a post is gated (either if subscribers-only or paid-only,  it is presented with this modal:
<p align="center">
<img width="300" alt="Screenshot 2022-11-17 at 15 48 49" src="https://user-images.githubusercontent.com/790558/202477964-4a263847-b4bf-4b5d-b4f0-e8890ba12c43.png">

Once email is entered, a choice is given to user:
<p align="center">
<img width="200" alt="Screenshot 2022-11-17 at 15 59 37" src="https://user-images.githubusercontent.com/790558/202480825-c4a1f89c-730d-4f10-bdd3-a0257b136d9f.png">
</p>

However, this flow can be confusing if the post is paid-only: the user can subscribe "for free", and still get gated.

### Task

2 design choices need to be made:
- Do we change the modal text when the post is paid-only?
- Do we prevent the user to subscribe for free when the post is paid-only?

Once choices are made, it needs to be documented in this task and implemented.

**Comment by romarioraffington** [comment]
I think for now we can hide the Free option

**Comment by artpi** [comment]
Nice catch!

I had this as a question to @pablohoneyhoney  in the spreadsheet:

Paid subscriber? | Post-level visibility setting | Subscriber email sent? | User sees the post | What happens in the modal | Notes
-- | -- | -- | -- | -- | --
❌ | Paid-Subscriber | ❌ | ❌ | Full checkout flow, after which moal closes, attaches JWT token to unlock the content and page reloads to generate logged-in view. User can choose "Free" option in the checkout but it will NOT unlock the content. | We attach payment and subscription to your user_id that you are logged into in WPCOM as we don’t want to create additional users for payments

@pablohoneyhoney should we disable free option if it will NOT unlock the content for the user?
I was thinking we can also pitch them in email to become a paid subscriber

**Comment by romarioraffington** [comment]
The solution in D92672-code currently hides the free option
