### ISSUE TITLE
Jetpack Connect: Show monthly plan toggle in JPC flow

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#7013]
On the plan selection page in JPC, we currently do not show the Monthly Plan / Yearly Plan toggle. We should add it in.

![screen shot 2016-07-25 at 8 34 55 pm](https://cloud.githubusercontent.com/assets/2694219/17122272/ed81a0a4-52a7-11e6-8d5f-a879baa2a873.png)

**Comment by tyxla** [comment]
I think this issue no longer occurs. The toggle is always shown when I'm testing, both with and without current plan. 

Also, I'm working on updating the current toggle in this PR: https://github.com/Automattic/wp-calypso/pull/7402 - this is further discussed in https://github.com/Automattic/wp-calypso/issues/6301.

**Comment by tyxla** [comment]
This case has been covered in https://github.com/Automattic/wp-calypso/pull/7402.
