### ISSUE TITLE
Help Center: allow HE's to request user screenshots during chat sessions

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#70147]
Since I did my support rotation, I felt that having the ability to see what the user is seeing would be immensely helpful to our HEs. I never mentioned this idea because it would have been pretty hard to implement before the Help Center. But now that the Help Center is accessible almost everywhere, it would take less than a week for a team of two people to get this running. All the APIs are ready, just needs some glue code.

Note that this doesn't pose any privacy issues because we'd only be able to screenshot what's inside WordPress.com.

**Comment by allilevine** [comment]
@alshakero Have you shared this idea with HEs? Is it still doable?

**Comment by alshakero** [comment]
Hi @allilevine! Thanks for the ping, should have updates this issue a while ago.

Yes, we discussed this and decided to shelf it because Zendesk has it natively, and we were moving to Zendesk. We're already on ZD now! 

p1669057572419479-slack-C0442CPG81M
