### ISSUE TITLE
Stepper eCommerce flow: check/create/update Tracks events

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#70145]
Check the whole flow for missing/needed Tracks events

**Comment by mreishus** [comment]
Is there a reference list of which tracks events we want?

**Comment by nelsonec87** [comment]
Not that I know of @mreishus . I believe we'll need to mirror the old flow: [wordpress.com/start/ecommerce](https://wordpress.com/start/ecommerce)

**Comment by mreishus** [comment]
I'm not yet sure what needs to be added. The basic stepper tracks look to be working. For reference, below is a log of step names I see when running in the production flow vs the new ecommerce flow.

### production ecommerce

```
_en: calypso_signup_actions_submit_step
_en: calypso_signup_actions_exclude_step
_en: calypso_domain_search_pageview
_en: calypso_signup_start
_en: calypso_signup_step_start
_en: calypso_domain_search_pageview
_en: calypso_page_view
_en: calypso_community_translator_disabled
_en: calypso_domain_search_results_suggestions_receive
_en: calypso_domain_search_results_suggestions_receive
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_traintracks_render
_en: calypso_domain_search
_en: calypso_traintracks_interact
_en: calypso_domain_search_add_button_click
_en: calypso_domain_search_submit_step
_en: calypso_signup_actions_submit_step
_en: calypso_signup_actions_exclude_step
_en: calypso_signup_actions_submit_step
_en: calypso_signup_processing_screen_show
_en: calypso_signup_actions_complete_step
_en: calypso_signup_actions_complete_step
_en: _aliasUser
_en: calypso_explat_initialization
_en: calypso_page_view
_en: calypso_signup_complete
_en: calypso_community_translator_disabled
_en: calypso_checkout_composite_cart_loaded
_en: calypso_checkout_page_view
_en: calypso_checkout_composite_loaded
_en: calypso_checkout_validating_contact_info
_en: calypso_checkout_composite_step_complete
_en: calypso_checkout_composite_first_step_complete
_en: calypso_checkout_composite_step_changed
_en: calypso_checkout_skip_to_last_step
_en: calypso_checkout_form_submit
_en: calypso_checkout_composite_form_submit
_en: calypso_checkout_composite_stripe_submit_clicked
_en: calypso_checkout_payment_success
_en: calypso_checkout_composite_payment_complete
_en: calypso_checkout_composite_step_complete
_en: calypso_checkout_thank_you_view
_en: calypso_page_view
_en: calypso_page_view
_en: calypso_atomic_transfer_complete
_en: calypso_page_view
```

### new ecommerce flow

```
_en: calypso_signup_start
_en: calypso_signup_step_start
_en: calypso_signup_actions_submit_step
_en: calypso_signup_step_start
_en: calypso_signup_store_profiler_submit
_en: calypso_signup_actions_submit_step
_en: calypso_signup_step_start
```

The new ecommerce flow is much shorter as I can't get to the checkout step yet. I'm stuck when choosing a design. I believe this is a well known road block related to us integrating the flow with some other work in progress.

**Comment by sixhours** [comment]
It looks like all the main events are there (built into the Stepper framework) but we might want to add event properties for design selection -- it doesn't look like we're adding the theme name/slug as a property, that could be useful data down the road.

<img width="615" alt="Screen Shot 2022-12-06 at 11 22 51 AM" src="https://user-images.githubusercontent.com/2124984/205966439-01aef950-02eb-4d22-9140-e37a5f43f103.png">

**Comment by sixhours** [comment]
@nelsonec87 @blackjackkent I've looked through the other Tracks events in this flow and didn't see any other glaring omissions, but let me know if you want to add other specific data. :)

**Comment by blackjackkent** [comment]
Since we've merged adding the design info, I feel comfortable closing this. Thanks for looking into it @sixhours !
