### ISSUE TITLE
Purchases: String 'Manage Purchase' is not localized

### ISSUE THREAD

**Issue by gedex** [Automattic/wp-calypso#7016]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/purchases
2. Go to the purchased plan
3. See the title on the top, 'Manage Purchase'.
4. Switch to another interface language and verify step 3 again.

#### What I expected

The string 'Manage Purchase' is translated to user's interface language.

#### What happened instead

The string 'Manage Purchase' is **not** translated to user's interface language.

#### Browser / OS version

Chrome 51.0.2704.103 (64-bit) / OSX 10.11.14

#### Screenshot / Video

<img width="732" alt="screen_shot_2016-07-26_at_11_14_14_am" src="https://cloud.githubusercontent.com/assets/78313/17124538/cfe98f00-5326-11e6-9d7e-08db75834d60.png">

Interface language set to 'es'.

**Comment by fabianapsimoes** [comment]
It does seem like the string is translatable ([see](https://github.com/Automattic/wp-calypso/blob/8a20ad81021ebb87bef3b3b4aac341b209c6caca/client/me/purchases/titles.js#L17)) and that there is a translation available for `es` ([see](https://translate.wordpress.com/projects/wpcom/es/default/?filters[status]=either&filters[original_id]=202166&filters[translation_id]=5703499)).

@akirk could you take a look and check if that string has been deployed already? Or maybe there's some other reason why the translation isn't showing?

**Comment by akirk** [comment]
Defining a [context in this way](https://github.com/Automattic/wp-calypso/blob/8a20ad81021ebb87bef3b3b4aac341b209c6caca/client/me/purchases/titles.js#L6)  doesn't work.

When we extract strings for translation, we are looking just at the **raw js text file**, we don't run JavaScript (it would be far to complex). So for that reason the string gets added to GlotPress [without a context (no grey box with white text next to the original)](https://translate.wordpress.com/projects/wpcom/es/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=202166&filters%5Btranslation_id%5D=5703499) but when we ask for displaying the string, a context is provided `Title text`, hence no translation with that context can be found.

Two possible solutions:
 - Remove the context, i.e. [L6](https://github.com/Automattic/wp-calypso/blob/8a20ad81021ebb87bef3b3b4aac341b209c6caca/client/me/purchases/titles.js#L6) (preferable in this case)
 - add the context verbatim in each line (will require a full translation cycle: extract new string to GlotPress, send for translation next week, get string back and deploy)

**Comment by akirk** [comment]
cc @gziolo who created this code.

In general, context is like commas in English: when in doubt, leave it out. Context is only needed if it shows that **the same text needs to be translated differently in two locations of our UI, depending on the _context_**. I know that adding context is well-intentioned but if you want to help the translator (and that is very much appreciated!), please use a [comment](https://github.com/Automattic/i18n-calypso#translate-method).
