### ISSUE TITLE
Security: Strings in list of access permissions of connected applications are not localized

### ISSUE THREAD

**Issue by gedex** [Automattic/wp-calypso#7017]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/security/connected-applications
2. Click on any of connected application
3. See list of **Access Permissions**
4. Switch to another interface language and verify step 3 again
#### What I expected

Strings in **Access Permissions** list to be translated to user's interface language. Here's an example of **WordPress for iOS** has on **Access Permissions**:
- View user information data such as username, name, email, blog, and Gravatar.
- View and manage posts including reblogs and likes.
- View and manage a post's comments.
- View and manage a site's tags and categories.
- Follow and unfollow blogs.
- View and manage a user's notifications.
- View stats for a site.
- Manage a site's media library.
- View and manage a site's menus.
#### What happened instead

Strings in **Access Permissions** list is **not** translated to user's interface language. 
#### Browser / OS version

Chrome 51.0.2704.103 (64-bit) / OSX 10.11.14
#### Screenshot / Video

<img width="720" alt="screen_shot_2016-07-26_at_12_05_46_pm" src="https://cloud.githubusercontent.com/assets/78313/17124897/73f9b348-5329-11e6-8fcf-a1f2a5c866b0.png">

**Comment by lancewillett** [comment]
I think this might have less to do with Calypso strings and more to do with the WordPress.com REST API response.

To research:
1. Is the string translated in GlotPress (<a href="https://translate.wordpress.com/projects/wpcom/es/default/">es</a> as an example)
2. If yes, why isn't Calypso using the translated string?

(If no, the strings should be translated first.)

**Comment by lancewillett** [comment]
I think some of these strings aren't translated yet, here's an example: https://translate.wordpress.com/projects/wpcom/es/default/?filters%5Bterm%5D=%3Cstrong%3EFollow%3C%2Fstrong%3E+and+%3Cstrong%3Eunfollow%3C%2Fstrong%3E+blogs&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by lancewillett** [comment]
It could also have something to do with the fact these strings — in the API response — have HTML tags like `strong`. These could be making the localization lookup fail somehow...

Ping @akirk for a 2nd opinion.

**Comment by lancewillett** [comment]
Maybe <a href="https://github.com/Automattic/wp-calypso/blob/6394a9c1409d0b1629b820cd81b48cdaf710fd48/client/me/connected-application-item/index.jsx#L170">this `description` call</a> needs `this.translate()` wrapped around it?

**Comment by akirk** [comment]
> Maybe this description call needs this.translate() wrapped around it?

No, please don't wrap a translate call around a variable. We cannot extract text from there.

The text needs to be returned translated from the API, so [this](https://github.com/Automattic/wp-calypso/blob/master/client/lib/connected-applications-data/index.js#L53) needs to be changed to `wpcom.withLocale().me()` in the first place, then we can check for the translation status of the strings.

**Comment by lancewillett** [comment]
Cool, thanks for the notes. I'll leave you to create a pull request.
