### ISSUE TITLE
[Newsletters] confirm that current subscribers are detected

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#70178]
**I picked an email that was already subscribed as an email subscriber**

## Here is what should have happened:

Scenario | Site type | LoggedIn to WPCOM? | Has proper JWT Cookie? | Subscribed as blog subscriber? | Paid subscriber? | Post-level visibility setting | Subscriber email sent? | User sees the post | What happens in the modal | Notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
P | All | ❌ | ❌ | ✅ | ✅ / ❌ | Blog subscriber | ✅ | ❌ | Modal from subscribe.wordpress.com opens, sees that email matches an account with a blog subscription. Returns JWT token to pass that information to frontend | We dont really check if user is truthful about their subscription because there is nothing for them to gain by lying

## Here is what happened:

Modal closed, as if I was not an email subscriber

Here is a video with details:
https://www.loom.com/share/8d2a13f8f5b24f31914c8a46013fedc0

Another site, another case:

https://www.loom.com/share/4bfaa027fee94c8f931da1f3016b1860

**Comment by romarioraffington** [comment]
I think it would be best to put this fix in D92672-code.  We need https://github.com/Automattic/jetpack/pull/27352 and WPCOM code to be merged and deployed. An additional PR would require a second rebase

**Comment by romarioraffington** [comment]
@artpi, how do you think we should handle this? There are edge cases here:

- [ ]   **The user is a pending free subscriber:** We send a code for the user to authenticate and confirm their email.
- [ ]  **The user is a free subscriber:** We send a code for the user to authenticate
- [ ]  **The user is a free subscriber:** We should allow them to "upgrade" to a paid subscriber ( [added a task](https://github.com/orgs/Automattic/projects/188#card-86903320) )
- [x] **The user is paid subscriber:** User receives a code via email to authenticate

**Comment by romarioraffington** [comment]
D93343-code

I went with the following approach:

- [x]   **The user is a pending free subscriber:** We send a code for the user to authenticate and confirm their email.
- [x]  **The user is a free subscriber:** We send a code for the user to authenticate
