### ISSUE TITLE
Use a feature flag for the theme switch work

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#70179]
# Description
This is high priority work, let's  tackle this on Monday Nov 21.  🙏 

**Context:**
* p1668738547992409/1668738542.228939-slack-CRWCHQGUB
* [Persist template content on theme switch] pbxlJb-2X4-p2 

 **Theme switch work:**

* D91764-code
* Spike issue https://github.com/Automattic/wp-calypso/issues/68427
* D89996-code

Currently the theme switch work is visible to all a8c.   We aren't ready to ship this work to users, so we need to make the a8c experience equal to the user experience.    Marvel team will do a bigger audit of the theme switch experience and can build on the work already done once design & UX decisions are clear.

## Tasks
- [x] put the work behind a flag instead of making it available to all a8c via [is_automattician]

@Automattic/ganon

**Comment by autumnfjeld** [comment]
I also added a new feature "Theme Switch"  https://github.com/orgs/Automattic/projects/338/settings/fields/4607557

**Comment by bangank36** [comment]
Closed as landed
