### ISSUE TITLE
Create My Home card for the Site Editor video screen

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#70189]
# Description

See the video screen work in https://github.com/Automattic/wp-calypso/issues/69175 & https://github.com/Automattic/wp-calypso/pull/69847.

Create a new card for My Home for linking to these videos.  This can appear for any user.  For example:
* Build flow will see a card for Site Editor (SE) video screen
* Sell flow will see a card for SE video screen
* Blogger flow will see both a card for Blogger video screen and SE video screen (blogger one takes precedence) 
* I think any flow should show the SE video screen card

This is the blogger card:

![Image](https://user-images.githubusercontent.com/5665959/202778248-aa449a00-8308-4ad4-a37f-9d647a3f12e3.png)

### Copy for the SE card:

Design like an expert
Master the basics of Site Editing with five short videos. Learn how to edit colors, fonts, layouts, and bring your style to your site. 
Start learning

Tasks
- [x] Get input from @ianstewart &/or @SaxonF on the copy.
- [x] Add SE card to My Home
- [x] card should link out to SE video screen (same as Blogger card links out to Blogger video screen)
- [ ] bonus : fix the inconsistency with the link out icon (shown in the screenshot below). Remove the icon.

![Image](https://user-images.githubusercontent.com/5665959/202779747-5863df6f-5a46-4225-bed7-67442eb3cc46.png)

**Comment by arthur791004** [comment]
> bonus : fix the inconsistency with the link out icon (shown in the screenshot below). Remove the icon.

This is the expected behavior as it will open a new window when you click "Learn more". However, others without icon will open the modal in the same window. Do we still need to change the behavior?

**Comment by arthur791004** [comment]
Currently, the "Blog like an excerpt from day one" card shows regardless of the site intent, just double confirm that we want to show this card only for the site whose "intent" is not "write", right?

**Comment by autumnfjeld** [comment]
> This is the expected behavior as it will open a new window when you click "Learn more". However, others without icon will open the modal in the same window. Do we still need to change the behavior?

@arthur791004 
Ah ok.  That makes sense.  Thanks for explaining. :)
Do not change the behavior.

**Comment by autumnfjeld** [comment]
> Currently, the "Blog like an excerpt from day one" card shows regardless of the site intent, just double confirm that we want to show this card only for the site whose "intent" is not "write", right?

@arthur791004 . Thank you for the info. I thought the blog card showed up  only for intent = write.
Let's leave it as it is, flagging with @ianstewart  in case he has opinions.

Then what I'd like to change is:
* both cards will be available, the difference is the default top card
* for intent=write, the blog card shows on My Home page load
* for other intents, the SE card shows on My Home page load


Does that makes sense?

**Comment by arthur791004** [comment]
Yes, it makes sense to me 🙂

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/70224
