### ISSUE TITLE
Fix PA (or DP?) padding to make it equal on left and right

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#70184]
# Description
As pointed out in the PA call, the right and left padding are not equal in the DP.
Call recording: https://drive.google.com/file/d/1oKwHHuZ6_8TvCSrQDlbXJB6HvGaFJb9L/view

![Image](https://user-images.githubusercontent.com/5665959/202766173-e7f93345-1225-4ecd-acb8-8e2590263000.png)

@Automattic/ganon

**Comment by bangank36** [comment]
This issue seems only to happen in "Show all" category, on Build flow (with blank canvas CTA)

![Screen Capture on 2022-11-21 at 12-02-36.gif](https://cdn-std.droplr.net/files/acc_1243635/yGiCam)

**Comment by bangank36** [comment]
Closed as landed
