### ISSUE TITLE
Advanced SEO: hide options from Editor when editing a post on a Jetpack site

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#7020]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/yoursite.com (Jetpack site)
2. Check the tools in the left sidebar 
3. Advanced SEO is displayed although Jetpack doesn't have a way to output that information on the site.

**Comment by lancewillett** [comment]
Advanced SEO is coming to Jetpack, soon! Closing as this is in progress. See p3fqKv-3Gq-p2

**Comment by vindl** [comment]
Resolved in https://github.com/Automattic/wp-calypso/pull/8663.
