### ISSUE TITLE
Onboarding Progress Bar size not proportional

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#70205]
# Description

This was reported in, [Feedback: Issues with the Premium Woo theme flow] pdh1Xd-1Al-p2 .  I believe same issue exists in all onboarding flows. 
 
The onboarding progress bar on the first screen is too small. The tiny initial length implies there are A LOT of steps left.  It needs to be roughly proportional to the number of steps. If 5 steps, start length should be 1/5 of the viewport.  If # steps can't be accurately represented, then use a common sense length.

![Image](https://user-images.githubusercontent.com/5665959/202856284-52e0ea20-8792-456e-886a-bfc15c2cd8a5.png)

# Tasks
- [ ] increase the starting length to a reasonable proportion of the width of the viewport

cc: @ngan since you worked on this.

**Comment by bangank36** [comment]
Sorry I missed your ping on this, will have a look on this next week 🤗
