### ISSUE TITLE
[Bug]: Subscriber Importer: subscribers with matching wpcom accounts remain as email only subs 

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#70216]
### Quick summary

When adding email subscribers to an Atomic site no local user is getting created when a WordPress.com account exists. This means that users can't be "invited" as followers and can't login to view sites that are set to private (which they should be able to). 

Essentially, it's ignoring the difference between subscribers with wpcom accounts and those without, making everyone an email subscriber only.

I was able to reproduce this with the site set as both Public and Private. The current workaround seems to be manually creating a local user and emailing the newly "invited" user from that flow.

### Steps to reproduce

1. On a WoA, dotcom site go to https://wordpress.com/people/email-followers/{site} and add an email with a matching wpcom account
2. Check the follower tab/ CLI/ wp-admin users tab to see a local user isn't added
3. with the site set to private, try to access the site as the subscriber you just added
4. see that there's no way to create a local user to get access

### What you expected to happen

It should create the local user like it used to 

OR
if we no longer want wpcom subscribers **and** email only subscribers there should be some alternate way for site owners to invite someone to view a site that's private/coming soon on Atomic

### What actually happened

Right now it seems like the only way a user could try to become a follower (this should be the same as a subscriber with a wpcom account, right?) is if they follow via the reader. 
Subscribing to the site via a public flow while logged in with their wpcom account adds them as an email subscriber only, not as a subscriber with a connected wpcom account. 

### Context

p1668940687198289-slack-C03TY6J1A

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

The bigger impact appears to be on Atomic sites but simple sites also have no way of getting email addresses linked to existing wpcom accounts with this new flow

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

You can add them as an email subscriber and then manually add them to the wp-admin user list for atomic sites

For simple sites users can still be invited as viewers

**Comment by inaikem** [comment]
Internal report thread: p1668949223858979-slack-C01A60HCGUA

Pinging @Automattic/caribou for completeness 🙏

**Comment by ouikhuan** [comment]
See more discussion here: p1668949223858979-slack-C01A60HCGUA

> Check the follower tab/ CLI/ wp-admin users tab to see a local user isn't added

After investigating further, it looks like this is only limited to some of the accounts.

In this case we'll have to come up with solutions that add a subscriber as a local user on the Atomic site and figure out what we want to do if an imported email does not have a wpcom account. (Access a private site requires a wpcom account)

**Comment by vishnugopal** [comment]
More discussion here: pcmemI-1tt-p2 to try to fix this issue.

Just a note that there will always be a distinction between `Email subscribers` (earlier email followers) and the `Subscriber` role specific to Atomic site. So to have a user get access to an Atomic private site, add them as a Subscriber.

**Comment by ouikhuan** [comment]
I'm going to close this issue for now as it's been deployed and address in #70623, thank you!
