### ISSUE TITLE
Stats: Fix search terms ordering

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#70212]
Part of the modernization project (p1HpG7-igQ-p2).

In some instances, items with higher values will come at the bottom of the Search terms list.

![Image](https://user-images.githubusercontent.com/390760/202683189-a0acdfcb-e65b-425c-a98f-881b5af3e480.png)

Does it only happen with “Unknown Search Terms” because it's treated like a special, less important item than “real” search terms?

In any case, our new horizontal bars now make this look like an error so I'd propose:

- **Option 1**: position this item in its natural position, by views in descending order.
- **Option 2**: don't touch its position but remove the horizontal bar so it looks intentional and not like an error.

Thoughts on this @jeffgolenski ?

**Comment by grzegorz-cp** [comment]
I think that `option 1` makes more sense because if we remove the bar, we still have the higher number at the bottom and no bar.

@jeffgolenski do you agree?
