### ISSUE TITLE
Marketplace search: serve icon URL through the search API

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#70233]
Subtask of #63905

Currently, we index icons for WP.org and WC.com results differently. This is due to how the original sources store the icon URLs.

WP.org results contain a serialized icons object:
```json
{
  "icons": "{\"icon-128x128.png\":{\"filename\":\"icon-128x128.png\",\"revision\":1730848,\"resolution\":\"128x128\",\"location\":\"assets\",\"locale\":\"\"},\"icon-256x256.png\":{\"filename\":\"icon-256x256.png\",\"revision\":1730848,\"resolution\":\"256x256\",\"location\":\"assets\",\"locale\":\"\"}}",
}
```

WC.com results contain a single URL in the icons field:
```json
{
  "icons": "https://woocommerce.com/wp-content/uploads/2013/09/zapier-icon-80px@2x.png",
}
```

We've been adding logic to handle the `icons` object to Calypso so far. To make both the client code simpler and move this responsibility closer to the data source, I think we should move this logic to the field mapper classes in `class.wpes-wpcom-plugin-post-field-builder.php`.
That way, only the icon URL that needs to be displayed with the result would be stored in ES.

**Comment by gavande1** [comment]
Backend diff created: D95204-code

**Comment by epeicher** [comment]
Diff deployed r257902-wpcom

**Comment by epeicher** [comment]
After successfully merging both backend and fron-end changes, this task is completed
