### ISSUE TITLE
Task: Ensure we don't show marketplace themes in signup flows

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#70249]
### Details

At launch, we only want to show marketplace themes in the Calypso theme showcase and the theme selection UI, but we need a mechanism to ensure that we exclude those themes when we're in signup or onboarding flows.

Ideally, this filtering would happen on the server, but we then need some way to determine which context we're in.

**Comment by mreishus** [comment]
Are we defining marketplace themes as any theme with `.theme_type` == `managed-external`?

**Comment by mreishus** [comment]
Since all themes requested in calypso get sent to the same redux store, and there's no guarantee which backend queries have been sent before or what cached data has been persisted, I think at least part of this filtering has to live on the client side.

**Comment by mreishus** [comment]
Since the signup design picker uses "Starter Designs", which are stored in the client separately from Themes, we may be able to filter the backend endpoint for Starter Designs only.

**Comment by mreishus** [comment]
D93176-code : starter-designs endpoint: Filter out managed-external themes

**Comment by mreishus** [comment]
Not merging the above since dale has a plan to fix in D93423-code

**Comment by valterlorran** [comment]
This issues was closed by D94819-code and D94436-code
