### ISSUE TITLE
Stats: Chart container lacks horizontal padding from screen edges on tablet viewports (480px ~ 659px)

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#70258]
Examples:

![Image](https://user-images.githubusercontent.com/4044428/203150355-b755ec31-29e2-45cb-9a57-9165e9ddfab3.png)

![Image](https://user-images.githubusercontent.com/4044428/203150492-2919a64e-42e2-4fff-9e58-178262eabe34.png)

**Comment by dognose24** [comment]
Hi, @keoshi @jeffgolenski! I have a few solutions to this issue that need your opinion. There will be some break lines at the viewport near 480px with adding horizontal padding on the `Traffic` page. Do they look reasonable to you?

<img width="632" alt="截圖 2022-11-28 下午11 24 21" src="https://user-images.githubusercontent.com/6869813/204320769-a5c2826e-0a29-4ad6-b706-15e9901b683c.png">
<img width="526" alt="截圖 2022-11-28 下午11 24 50" src="https://user-images.githubusercontent.com/6869813/204320808-1b7c21ec-46d6-4f97-8ffd-1918d4114ee8.png">
<img width="546" alt="截圖 2022-11-28 下午11 23 41" src="https://user-images.githubusercontent.com/6869813/204320846-64504c7c-8343-4435-9553-fd4040a20e27.png">

The lines in the tabs on the `Store` page also seem messy before transforming to the full-width item under `width <= 480px`.

<img width="536" alt="截圖 2022-11-28 下午11 25 30" src="https://user-images.githubusercontent.com/6869813/204320357-966c6e74-2a71-4b65-a2c9-a691336052e1.png">

These are some edge cases that I could not find a perfect way to address for now. What do you think?

cc @jsnmoon

**Comment by keoshi** [comment]
Hey @dognose24!

They all look reasonable, but the last one feels too tight and confusing IMO. I also want to mention that they might look great in English, but that's not necessarily true for other languages.

Is there are reason why we shouldn't break these sooner into these vertical tabs? By sooner I mean when the viewport is larger than 480px, probably around ~600px?

![image](https://user-images.githubusercontent.com/390760/204578195-09a22b80-0aca-4010-9fac-c11ca1777a9e.png)

**Comment by dognose24** [comment]
> By sooner I mean when the viewport is larger than 480px, probably around ~600px?

I was also considering this solution, which looks like it is working once and for all. I will dig into the shared components to try to modify the breaking point for all chart tabs. Thanks for your feedback! @keoshi
