### ISSUE TITLE
Theme styling for the "load more posts" button styling is missing

### ISSUE THREAD

**Issue by desnum** [Automattic/wp-calypso#70267]
### Quick summary

In the Zoologist theme, the "load more posts" button in the Blog Posts block looks like it's straight out of the 90s.

### Steps to reproduce

1. Activate Zoologist
2. In FSE, add a Blog Posts block
3. Have more posts in the site than you choose to display in this block
4. Turn on the "Show "Load more posts" Button" setting in the right sidebar
5. Save the changes

### What you expected to happen

I'd expect that the button would look more similar to how it is in the editor

<img width="1477" alt="Screen Shot 2022-11-21 at 9 54 37 PM" src="https://user-images.githubusercontent.com/43796228/203209851-99c02b90-f6f3-4e58-a9e8-b5dc9f3b2e43.png">

### What actually happened

The button on the frontend is small and gray

<img width="1467" alt="Screen Shot 2022-11-21 at 9 55 32 PM" src="https://user-images.githubusercontent.com/43796228/203209963-0f1ce3ff-344e-41d2-9557-ea53fe3fdee3.png">

### Browser

Mozilla Firefox, Android Chrome

### Context

A user brought this issue up in 5730756-zen, and I can replicate it in my own simple test site

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Workaround details

I shared this CSS:

/*load more posts button styling | 5730756-zen DF*/
.wpnbha.has-more-button button {
	color: white;
	background-color: #54C7F7;
	padding: 15px;
	border: none;
}

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on a simple site and it looks like this works now- could not replicate!

#### Screenshots/Recordings

![Markup on 2023-04-27 at 17:05:50](https://user-images.githubusercontent.com/27249804/235015632-1ab58dc0-90b4-46eb-a394-499a27f0d788.png)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
