### ISSUE TITLE
Stats: Simplify Referrers groupings

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#70260]
Part of the modernization project (p1HpG7-igQ-p2).

In some scenarios, the groupings that appear on the Referrers module just add unnecessary complexity.

In the example below you can see there's only one Referrer — Google Search — but it's still added to a “Search Engines” group that you have to click to see it.

If there's only one child item, could we get rid of the grouping to clean up the interface?

![Image](https://user-images.githubusercontent.com/390760/197245294-19d577dd-cf5a-4649-b272-43ba9ac7ce50.png)

**Comment by wilmersondasilva** [comment]
I think this grouping is coming from the API. Should we change this behavior on the API or on the client, @jsnmoon?

**Comment by jsnmoon** [comment]
> I think this grouping is coming from the API. Should we change this behavior on the API or on the client, @jsnmoon? (@wilmersondasilva)

Interesting; can you investigate the API implementation and let us know how feasible such a change would be? It'd be good to tackle this issue at its source, but I'd like for us to be pragmatic here.

**Comment by jsnmoon** [comment]
Fixed in #73461.
