### ISSUE TITLE
/support LP i1

### ISSUE THREAD

**Issue by vinimotaa** [Automattic/wp-calypso#70285]
The /support site receives well over one million monthly page views and is a valuable asset to our company. Investing in its appearance and functionality will benefit our users and business.

The main goal of redesigning the /support was to make it as easy as possible for users to discover the right doc, which the current design does not do a great job of. To achieve our goal, we had to re-structure the main pages – which we’ll cover below.

P2 here
[WIP Figma here](KvlrD3opdur6eTpH3VGRPv/%F0%9F%9A%A7-Logged-out-Landing-pages-fi-2689%3A12811)

**Comment by vinimotaa** [comment]
The /support site receives well over one million monthly page views and is a valuable asset to our company. Investing in its appearance and functionality will benefit our users and business.

The main goal of redesigning the /support was to make it as easy as possible for users to discover the right doc, which the current design does not do a great job of. To achieve our goal, we had to re-structure the main pages – which we’ll cover below.

- P2 here
- WIP Figma here

**Comment by vinimotaa** [comment]
** Update

The Vertex Team [started some scoping](https://wp.me/p2pdDR7T-sm-p2) on development.

**Comment by ebinnion** [comment]
Should this issue be closed now?

**Comment by vinimotaa** [comment]
Yes, we can close this for now - I'll follow up creating a new GH for the iterations to come.
