### ISSUE TITLE
/hosting LP i1

### ISSUE THREAD

**Issue by vinimotaa** [Automattic/wp-calypso#70284]
We want to revamp the existing /hosting page from the group up, especially given our last updates to Plans and overall design direction for LOHP.

- P2 here
- @vinimotaa Initial Figma File [here](https://www.figma.com/file/KvlrD3opdur6eTpH3VGRPv/%F0%9F%9A%A7-Logged-out-Landing-pages?node-id=2501%3A9133&t=degvY9t9dVzH7dI6-1)
- @Noemish Latest explorations file [here](I25gumfCSOuvS7ZqnUBngW-fi-5%3A43&t=coTSU8atbyXCf5Bv-1)

**Comment by vinimotaa** [comment]
*UPDATE

Naomi has been exploring the overall VIsual Design directions for the landing page while @that-mike-bal has been refining the content.

*NEXT STEP

Get the VD directions approved and support Naomi to refine the page and work with Dev. team on hand-off.

**Comment by Noemish** [comment]
I've shared latest explorations for visual direction

Figma [here](https://www.figma.com/file/I25gumfCSOuvS7ZqnUBngW/Hosting-LP?node-id=5%3A43)
Slack thread [here](https://a8c.slack.com/archives/C04B8243NKD/p1669308393364089)
