### ISSUE TITLE
Sites as landing page: display opt-in banner

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#70294]
### Details

If the user has more than one site, let's display the banner above the header on the `/sites` page indicating that it's possible to make it their landing page.

Design suggestion:

![image](https://user-images.githubusercontent.com/26530524/203365928-59e969c6-445a-4ff1-95a8-8ae116685380.png)

When clicking "Yes", save a boolean preference and hide the banner.

When clicking "No", hide the banner and remember that decision for 14 days before showing it again. We should display a notice indicating that it's possible to toggle that preference later on the settings page.

We should fire some events, too:

- `calypso_sites_as_landing_page_seen`, when the banner is shown
- `calypso_sites_as_landing_page_rejected`, when the user clicks "No"
- `calypso_sites_as_landing_page_accepted`, when the user clicks "Yes"

### Done is

- [ ] Banner is shown if the user has more than one site
- [ ] Preference is saved after clicking "Yes"
- [ ] Banner is hidden temporarily after clicking "No"
- [ ] Events are fired according to actions

**Comment by p-jackson** [comment]
If the user setting was already set to "no", and then they choose "no" again (because the banner reappeared) then do we want to record another `calypso_sites_as_landing_page_rejected` event? Will we end up double-counting people.

Maybe we just an event prop that indicates what the previous value was so we can exclude repeats when appropriate.

**Comment by p-jackson** [comment]
I've been using a preference that's saved to the Calypso preference store (i.e. `import { savePreference, getPreference } from 'calypso/state/preferences/actions'`) using a preference key of `'sites-landing-page'` and with a format of:
```
{
	useSitesAsLandingPage: boolean;
	updatedAt: number;
}
```

e.g.
```js
	dispatch(
		savePreference( 'sites-landing-page', {
			useSitesAsLandingPage: true,
			updatedAt: Date.now(),
		} )
	);
```

The `updatedAt` field will allow us to implement the show-again-after-14-days feature.

It could have been implemented as `true | number`, where the use of a number implies the user said no. But using the full object makes it easier to manually edit in the bottom-right dev menu.

**Comment by zaguiini** [comment]
> Maybe we just an event prop that indicates what the previous value was so we can exclude repeats when appropriate.

I think that's the way to go, @p-jackson

**Comment by zaguiini** [comment]
@SaxonF that's what I currently have:

![Image](https://user-images.githubusercontent.com/26530524/203833804-3ba4c139-43a5-4e67-a068-f208dacd9a9f.png)

I'm not a big fan of it, the banner CTA is battling with the "New Site" for attention. Do you have any ideas on how to proceed with that? cc @Automattic/build 

Right now I'm playing with removing the icon, it makes it a little bit better on the left site, but on the right it's still something to be worked on.

![image](https://user-images.githubusercontent.com/26530524/203835750-70964e8a-74ae-4c3a-88a7-9a1d49974fc8.png)

Another possibility would be to make it a banner floating on the bottom left, but that'd be pretty much hidden.

One thing I came up with was:

![image](https://user-images.githubusercontent.com/26530524/203839233-1e62d1e8-f421-4274-b304-53aa23b58e70.png)

But I feel the CTA is not standing out. It does look better than the initial attempt, though.

I'm almost dropping the "Beta badge". It looks way cleaner without it:

![image](https://user-images.githubusercontent.com/26530524/203840782-9bba2c9a-02f2-4ee0-8c54-677a17e3647b.png)

I'm also inclined not to make it full-width, that way it flows better to the user when they read, and it makes it also less prominent on the page. My opinion is that this final version above looks good to me.

Let me know what you think!

**Comment by zaguiini** [comment]
Progress in https://github.com/Automattic/wp-calypso/tree/add/sites-landing-page-opt-in-banner.

**Comment by SaxonF** [comment]
This is a good opportunity to form a pattern around page related actions needing attention. The notice component should be used and be placed under the page header for anything page related. It can either be placed in the page header itself or at the top of the content section.

![image](https://user-images.githubusercontent.com/1072756/203898841-888aedd4-eb78-4885-80e1-9254f5b749a8.png)

![image](https://user-images.githubusercontent.com/1072756/203898849-63d8c511-b7bc-4c86-a1ac-3cddc3d0e4b6.png)

You can see an example of this type of notice being used in /domains. The notice should accept a primary and secondary action props as well as dismissible. We'll want to eventually update Calypso/other notices to reflect this style.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/1072756/203898303-f187a8f2-87f7-40f7-a9bb-41d0394dff7e.png">

**Comment by zaguiini** [comment]
Thanks for all the help, @Automattic/build, and @SaxonF. Here's how it looks now:

![image](https://user-images.githubusercontent.com/26530524/203984438-8e1f8bb3-40ce-4ddb-bb26-c44400c71b48.png)
