### ISSUE TITLE
Sites as landing page: introduce feature flag

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#70293]
### Details

As we want to work on this project in small chunks, it makes sense to include a feature flag so we can hide the progress from the end users. Let's introduce a feature flag called `sites-as-landing-page`, enabled in all environments except production.

**Comment by p-jackson** [comment]
The first thing I ran into was should the flag be set in Jetpack Cloud? i.e. `config/jetpack-cloud-*.json`

I'm going to say no. We don't want to change any of the landing page behaviour for users who go to `cloud.jetpack.com` so to me that means the flag should always be off.

**Comment by p-jackson** [comment]
Feature flag added in #70319
