### ISSUE TITLE
Update two examples of text in Calypso referring to "Full Site Editor/Editing" to "Site Editor/Editing"

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#70303]
See: https://make.wordpress.org/updates/2022/11/04/site-editor-a-more-user-friendly-name/ and p9Jlb4-5Pi-p2

We'll need to update the labelling in Calypso to reflect this, where it appears.

Two examples (of many):

![image](https://user-images.githubusercontent.com/545779/203415678-a176a34e-9077-4dc1-8f0c-b595f30b076c.png)

![image](https://user-images.githubusercontent.com/545779/203415747-e7566c7d-fc95-42dd-aac2-900e5371fb50.png)

**Comment by fushar** [comment]
- [x] Updated the string in the theme activation success modal here: #71181 
- [x] Discussed about renaming the `Full Site Editing` search term here: pNEWy-fPD-p2

**Comment by fushar** [comment]
Also, as far as I know, the only string that we need to update in Calypso codebase is the one in the theme activation success modal above. Other strings are user input, such as the `Full Site Editing` "feature" above, theme description, etc. that needs manual edits.

**Comment by Copons** [comment]
cc https://github.com/Automattic/wp-calypso/issues/68953

**Comment by fushar** [comment]
This is done.
