### ISSUE TITLE
[Bug]: Missing GDPR banner styling on the new Woo login page

### ISSUE THREAD

**Issue by moon0326** [Automattic/wp-calypso#70306]
### Quick summary

![Screen Shot 2022-11-22 at 2 37 55 PM](https://user-images.githubusercontent.com/4723145/203435576-94a1c62d-8466-46e7-8dd6-21ed55488e65.jpg)

Wrong styling is applied on the login page from HTTP://woocommerce.com -> click Start

### Steps to reproduce

1. Make sure to sign out all wp.com accounts. Use Incognito mode.
2. Go to https://woocommerce.com
3. Click `GET STARTED`
4. You should be redirected to wp.com login page
5. Notice the GDPR banner has white background and text is invisible.
6. If you don't see the banner, clear the cookie.

FYI, I couldn't see the GDPR banner in the US. I had to use VPN to change my IP to an EU country. 

### What you expected to happen

The banner text should be visible.

### What actually happened

The banner text is invisible due to the wrong background color

### Reproducibility

Consistent

**Comment by cuemarie** [comment]
Seems this was addressed with https://github.com/Automattic/wp-calypso/pull/70307
