### ISSUE TITLE
Gifting: Expiry date should revert after a refund

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#70316]
In the event a gift is refunded, the receiver's plan expiry date should revert to what it was before the gifted subscription was applied.

Acceptance: 
- [ ] Plan expiry date reverts on gift refund

**Comment by allilevine** [comment]
@DavidRothstein This is feedback from the CfT, is it related to in progress billing work?

**Comment by DavidRothstein** [comment]
I think this can probably be closed as "won't fix"?  More details here: pdtkmj-Ks-p2#comment-1229

**Comment by lsl** [comment]
Should we drop the refund wording from the checkout as you suggest here: pdtkmj-Ks-p2#comment-1231?
