### ISSUE TITLE
Retention: Remove the is_automattician check to launch it

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#70314]
D93101-code introduced the JITM behind an is_automattician check with a TODO to remove it to launch.

Once:
- churn_prediction is populated https://github.com/Automattic/dotcom-forge/issues/1145
- the experiment is configured https://github.com/Automattic/dotcom-forge/issues/1223

Remove this is_a11n check to launch.

**Comment by DustyReagan** [comment]
Gate removal here: D97010-code

**Comment by DustyReagan** [comment]
Experiment results here: 20938-explat-experiment
