### ISSUE TITLE
Gifting: Checkout cancellation should return to referrer not /start/domain.

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#70317]
When clicking the "X" in checkout or otherwise emptying the cart you should be returned to the referring domain.

Some quick testing of https://wordpress.com/checkout/business-bundle/gift/19766713?cancel_to=https://... and checking [the code](https://github.com/Automattic/wp-calypso/blob/6cf5483ea2563468ca83848a35c0437c9ee2ae2b/client/my-sites/checkout/composite-checkout/lib/leave-checkout.ts#L82) tells me we're only able to redirect to internal routes, lets just go to home for now.

Acceptance:
- [ ] Add a `?cancel_to=/` url param to the Gift CTA url so early checkout exit's return somewhere other than /start/domain

**Comment by lupus2k** [comment]
What do you think about adding an else [here](https://github.com/Automattic/wp-calypso/blob/6cf5483ea2563468ca83848a35c0437c9ee2ae2b/client/my-sites/checkout/composite-checkout/lib/leave-checkout.ts#L85) using `window.location.href`?

**Comment by lupus2k** [comment]
Created this diff (for simple sites): D93366-code
Also, this PR at wpcomsh (for atomic sites): https://github.com/Automattic/wpcomsh/pull/1157
