### ISSUE TITLE
Retention: Open up the JITM to all admin_notices

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#70311]
Expand on D93101-code to include all admin_notice display sections per @DustyReagan's suggestion:

```
->message_path( '/calypso:.*:admin_notices/' )
```

- [ ] Update message path
- [ ] Confirm where these are shown to users and that it makes sense to show it in all contexts.

**Comment by lupus2k** [comment]
Created this diff: D94420-code

**Comment by candy02058912** [comment]
Created a follow-up issue: https://github.com/Automattic/dotcom-forge/issues/1339
