### ISSUE TITLE
Gifting: Confirm monthly subscription gifts monthly subscription

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#70310]
p1669159910597899/1669109595.137749-slack-C04CLBHNUDN

Needs clarification/confirmation for marketing: When you gift a monthly subscription site is it for a month or a year?

**Comment by allilevine** [comment]
@lsl Can we resolve this one by testing it out? Any blockers?

**Comment by lupus2k** [comment]
I confirmed you gift the same type of subscription the user has. 
If the user has monthly, the gift is monthly. If the user has yearly, the gift is yearly.
