### ISSUE TITLE
Customizer Theme Showcase is showing style error on Atomic sites

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#70329]
### Quick summary

https://user-images.githubusercontent.com/9984867/203521867-1699537c-10ef-42eb-a23d-bb8c066bde71.mp4

Both "Installed Themes" and "WordPress.org Themes" showcase show styling error on Customizer. 

My Site → Appearance → Customize → "Change" button for themes

This is only available for Atomic sites. 

### Steps to reproduce

1. Go to "My Site".
2. Click "Appearance" and select "Customizer."
3. Click "Change" for the theme". 

https://user-images.githubusercontent.com/9984867/203524864-18b61acf-8ef0-4dc4-84e1-b8110eeedafc.mov

### What you expected to happen

Display themes with no styling errors: 

![Screen Shot on 2022-11-23 at 18:21:59](https://user-images.githubusercontent.com/9984867/203522988-1a221a9c-9bd7-4fca-b796-4bbb49b16ab5.png)

### What actually happened

Themes are displayed with styling error on the labels.

![Screen Shot on 2022-11-23 at 18:29:32](https://user-images.githubusercontent.com/9984867/203524426-cc6271e5-c055-414d-8cc3-33b1e09919f6.png)

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

**Comment by jeherve** [comment]
Closing in favor of https://github.com/Automattic/jetpack/issues/27622
