### ISSUE TITLE
Marketplace: add Jetpack search free plan

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#70333]
P2 thread: pdh6GB-2qC-p2

Jetpack search now has a free plan, which is added to the WPCOM store, but requires a checkout to activate. The plan is available for all sites, it doesn't require a Business plan. We need to add the free plan for Jetpack search for the plugin details page, and make it the default CTA, when it's not yet activated.

Here's a sketch of the changes from p8oabR-Xh-p2#comment-6788
![image](https://user-images.githubusercontent.com/11555574/203550198-934ea786-f6a3-4cfd-a94a-6c27af4c4bb6.png)

We should update the CTA logic with these two states:
- If neither version of the product is purchased/installed yet:
  -  CTA should have the text “Start for Free”
  - Clicking it should redirect to checkout with `PRODUCT_JETPACK_SEARCH_FREE`
- If the free plan is purchased/installed:
  - CTA should have the text “Upgrade Jetpack Search”
  - Clicking it should redirect to checkout with `PRODUCT_JETPACK_SEARCH` or `PRODUCT_JETPACK_SEARCH _MONTHLY)`

To add the free plan, we'll need to update this constant:
https://github.com/Automattic/wp-calypso/blob/e691fa9b9d206430f863d1dc758add8ad7e6bde2/client/my-sites/plugins/constants.js#L17-L26

Then update this hook to update what's shown on the UI:
https://github.com/Automattic/wp-calypso/blob/e691fa9b9d206430f863d1dc758add8ad7e6bde2/client/my-sites/plugins/use-preinstalled-premium-plugin/index.js#L14

More details on the changes to be made here: pdh6GB-2qC-p2#comment-3208

**Comment by epeicher** [comment]
#### Backlog grooming:

This task is timeboxed to 1 for an initial investigation. That investigation should reflect what needs to be done.

**Comment by epeicher** [comment]
A new related bug has been reported 
- #73009
