### ISSUE TITLE
Marketplace search: malformed ES queries are sent for categories

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#70331]
Based on the 🧵 here: p1669200946778249-slack-C029JEQRVRT

There are a number of invalid ES queries being sent by Calypso. Logstash link here: 2e49f-pb

The slug filter within the `filter.should` clause is parsing arrays incorrectly:
```json
{
    [ ... ]
    "filter": {
        "bool": {
            "should": [
                {
                    "term": {
                        "taxonomy.plugin_category.slug": "ecommerce"
                    },
                    "terms": {
                        "taxonomy.plugin_tags.slug": {
                            "[": "payments"
                        }
                    }
                }
            ]
        }
    },
    [ ... ]
}
```

This filter is created in this function: https://github.com/Automattic/wp-calypso/blob/84586808865a834278f0366e79fd0265fba3b2b2/client/data/marketplace/search-api.ts#L129

Also, let's create a `marketplace-alerts` alert in grafana (p1669222941818929/1669200946.778249-slack-C029JEQRVRT)

**Comment by gcsecsey** [comment]
This is still an issue, there are <7 days old logs in logstash, eg.: 2eca5-pb

That example JSON is a query for the SEO category. When trying to format the JSON, the filter clause is missing the array closing bracket, and is parsed as a property:
```json
"filter": {
	"bool": {
		"should": [
			{
				"term": {
					"taxonomy.plugin_category.slug": "seo",
					"taxonomy.wpcom_marketplace_categories.slug": "seo"
				},
				"terms": {
					"taxonomy.plugin_tags.slug": {
						"[": "seo"
					},
					"taxonomy.plugin_tag.slug": {
						"[": "seo"
					}
				}
			}
		]
	}
}
```

In Calypso, these parameters are sent as query string parameters, eg.: https://public-api.wordpress.com/rest/v1.3/marketplace/search?http_envelope=1&fields[]=blog_icon_url&fields[]=comment_count&fields[]=plugin.excerpt&fields[]=like_count&fields[]=modified&fields[]=modified_gmt&fields[]=plugin.title&fields[]=author&fields[]=plugin.author&fields[]=author_login&fields[]=blog_id&fields[]=date&fields[]=date_gmt&fields[]=permalink.url.raw&fields[]=post_id&fields[]=post_type&fields[]=slug&fields[]=plugin.tested&fields[]=plugin.stable_tag&fields[]=plugin.active_installs&fields[]=plugin.support_threads&fields[]=plugin.support_threads_resolved&fields[]=plugin.rating&fields[]=plugin.num_ratings&fields[]=plugin.icons&fields[]=plugin.store_product_monthly_id&fields[]=plugin.store_product_yearly_id&fields[]=plugin.premium_slug&fields[]=plugin.product_slug&page_handle=ZnJvbT0yMCZhbGc9bWFya2V0cGxhY2UlM0FzZWFyY2glMkYxJnNlc3Npb25faWQ9M0pGM2tt&query=&sort=active_installs&size=20&lang=en&group_id=marketplace&track_total_hits=false&filter[bool][should][][term][taxonomy.plugin_category.slug]=seo&filter[bool][should][][terms][taxonomy.plugin_tags.slug][]=seo&filter[bool][should][][term][taxonomy.wpcom_marketplace_categories.slug]=seo&filter[bool][should][][terms][taxonomy.plugin_tag.slug][]=seo

According to chrome dev tools, it should be parsed correctly:
![Image](https://user-images.githubusercontent.com/11555574/212716999-5c39082e-df65-4c23-889d-1b705a87a445.png)

I've tried reproducing it by adding this line to the file on my sandbox: D98209-code

When sending the same request from Calypso by clicking on the SEO category on the `/plugins` page, this produces a correct JSON:
```json
"filter": {
    "bool": {
        "should": [
            {
                "term": {
                    "taxonomy.plugin_category.slug": "seo"
                }
            },
            {
                "terms": {
                    "taxonomy.plugin_tags.slug": [
                        "seo"
                    ]
                }
            },
            {
                "term": {
                    "taxonomy.wpcom_marketplace_categories.slug": "seo"
                }
            },
            {
                "terms": {
                    "taxonomy.plugin_tag.slug": [
                        "seo"
                    ]
                }
            }
        ]
    }
},
```

The `WPCOM_JSON_API_Marketplace_Search_Endpoint` class doesn't parse the `input_args` directly, it passes these to the `Jetpack_WPES_Query_Builder`: fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qznexrgcynpr%2Qfrnepu%2Qraqcbvag.cuc%3Se%3Q7325qr2p%23664-og

@robfelty could you please help with whether we're passing the arguments correctly to the parser? I'm not completely sure where the formatting goes awry, maybe we should pass these filters in a different way? Thanks!

**Comment by robfelty** [comment]
I think I would try replacing
```
filter[bool][should][][terms][taxonomy.plugin_tag.slug][]=seo
```
with
```
filter[bool][should][][terms][taxonomy.plugin_tag.slug]=seo
```

(remove the last `[]` brackets

**Comment by gcsecsey** [comment]
Removing the last `[]` brackets results in a 400: 
```json
{
    "code": 400,
    "headers": [
        {
            "name": "Content-Type",
            "value": "application/json"
        }
    ],
    "body": {
        "error": "bad_request",
        "message": "query failed"
    }
}
```

I'm not sure if the `terms` query can have only one value, we're using a `terms` query for the tags because there can be either one or more tags for the category we're trying to match from here: https://github.com/Automattic/wp-calypso/blob/47c767974c11d584dc9299f91ae7498ba837976d/client/my-sites/plugins/categories/use-categories.tsx#L131-L133
For categories, we've been using a `term` query so far because we're always only matching one category slug.

**Comment by robfelty** [comment]
Hmm. I tried just running the API call you mentioned above directly in Firefox, and it seemed to work correctly - at least, it gave me results which looked right. Does that also work for you? If so, I suspect the issue might be with Calypso.

**Comment by gcsecsey** [comment]
Yes, the link above works as expected, but that still has the trailing `[]` in the query parameters. I meant that removing those from the query results in a 400 error, so replacing the `[terms][taxonomy.plugin_tags.slug][]=seo` part with `[terms][taxonomy.plugin_tags.slug]=seo`:
https://public-api.wordpress.com/rest/v1.3/marketplace/search?http_envelope=1&fields[]=blog_icon_url&fields[]=comment_count&fields[]=plugin.excerpt&fields[]=like_count&fields[]=modified&fields[]=modified_gmt&fields[]=plugin.title&fields[]=author&fields[]=plugin.author&fields[]=author_login&fields[]=blog_id&fields[]=date&fields[]=date_gmt&fields[]=permalink.url.raw&fields[]=post_id&fields[]=post_type&fields[]=slug&fields[]=plugin.tested&fields[]=plugin.stable_tag&fields[]=plugin.active_installs&fields[]=plugin.support_threads&fields[]=plugin.support_threads_resolved&fields[]=plugin.rating&fields[]=plugin.num_ratings&fields[]=plugin.icons&fields[]=plugin.store_product_monthly_id&fields[]=plugin.store_product_yearly_id&fields[]=plugin.premium_slug&fields[]=plugin.product_slug&page_handle=ZnJvbT0yMCZhbGc9bWFya2V0cGxhY2UlM0FzZWFyY2glMkYxJnNlc3Npb25faWQ9M0pGM2tt&query=&sort=active_installs&size=20&lang=en&group_id=marketplace&track_total_hits=false&filter[bool][should][][term][taxonomy.plugin_category.slug]=seo&filter[bool][should][][terms][taxonomy.plugin_tags.slug]=seo&filter[bool][should][][term][taxonomy.wpcom_marketplace_categories.slug]=seo&filter[bool][should][][terms][taxonomy.plugin_tag.slug]=seo

With this URL I get the same error in Postman, Chrome and Firefox too. I'll try adding a conditional to use a `term` query if there's only one tag we're interested in.

**Comment by robfelty** [comment]
I guess I don't understand the problem then - what is wrong with the original query?

**Comment by gcsecsey** [comment]
I don't think the original query is wrong. However, it produces errors on the production environment.

The problem is that I was unable to reproduce the issue so far. With WPCOM and Calypso both up-to-date, I can send the same query and get correct results on my sandbox. I'm not really sure yet what's causing the query to be malformed, but I'll try updating Calypso to use a term query instead of a terms query when there's only one tag, to see if that resolves the issue.

**Comment by gcsecsey** [comment]
Looking at the logs in Logstash, I've found that within the `extra` field, the `lang` parameter seemed to be always different from English. I couldn't filter for it but checked a couple of dozen of logs and the query was always sending a different language parameter.

In Calypso, I've changed my language and in this case the query will be formatted differently:
![Image](https://user-images.githubusercontent.com/11555574/212936561-55ff8fd1-084f-4611-8a52-dce8f9447708.png)

This is the query with English language parameter and correct formatting:
![Image](https://user-images.githubusercontent.com/11555574/212936543-15101519-8b06-467a-8f4f-52ce02906e78.png)

So this is definitely a Calypso issue, I'll look into what's exactly causing this difference and create a fix for it.

**Comment by robfelty** [comment]
Nice sleuthing!

**Comment by gcsecsey** [comment]
I've tried to debug this issue further today and managed to solve one problem. However, the query string of the request is still changed when the language is not set to English, and with the changed query all categories fail to load.

When sending the request, the generated query string seemed correct for all locales:
https://github.com/Automattic/wp-calypso/blob/6d462a15a1e4566512682c5ebd31aa444122fc68/packages/wpcom.js/src/lib/util/send-request.js#L65

In `addLocaleQueryParam`, if the language is not set to English, the query is parsed again with `qs.parse`:
https://github.com/Automattic/wp-calypso/blob/8655c5d63a946d21ecc78a36e7e88cb80a302ba2/client/lib/wp/localization/index.js#L19

After this point, the parsed object has an additional `[]` within the ES bool filter object. According to the readme:
> By default, when nesting objects qs will only parse up to 5 children deep. This means if you attempt to parse a string like 'a[b][c][d][e][f][g][h][i]=j' your resulting object will be:
>
> ```javascript
> var expected = {
>     a: {
>         b: {
>             c: {
>                 d: {
>                     e: {
>                         f: {
>                             '[g][h][i]': 'j'
>                         }
>                     }
>                 }
>             }
>         }
>     }
> };
> var string = 'a[b][c][d][e][f][g][h][i]=j';
> assert.deepEqual(qs.parse(string), expected);
> ```

By adding a higher depth parameter to this call, one additional pair of brackets are removed from the query string:
<img width="473" alt="CleanShot 2023-01-18 at 16 09 12@2x" src="https://user-images.githubusercontent.com/11555574/213229476-c993968a-ae69-4a6b-8737-c5fbe19efdde.png">

However, compared to the request with the English locale, the bracket pairs still have iterator numbers, and the request is still failing on the backend. I'm suspecting that there is another `qs.parse` in the call chain that causes this and will investigate further.
