### ISSUE TITLE
Gifting: style title alignment / css leak?

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#70355]
Could be another theme style leaking over? This isn't the first one of these, lets loop over a few different themes and check for similar issues.

Context pdtkmj-Ks-p2#comment-1238

![Screenshot(15)](https://user-images.githubusercontent.com/811776/203688182-faf52676-4216-4264-bb0e-eb5363abf797.png)

- [ ] Align the subtitle part of the banner at every view port size
- [ ] Check 10 other themes for similar styling issues

**Comment by lupus2k** [comment]
This happened on themes using `text-align: center;` on the `.body`
I fixed this aligning `.wpcom-gifting-banner__subtitle` to the left (or right on rtl)

**Comment by paulopmt1** [comment]
The error happens on [default theme](https://wordpress.org/themes/default/) and specific screen size for any browser:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1044309/203987892-d324acd6-1cab-4281-8d48-33a3b68c0bc4.png">

**Comment by candy02058912** [comment]
Reminder for people testing with this theme: need to use PHP 7.4, so it doesn't break the site.
