### ISSUE TITLE
Marketplace: Ensure plugin title correctly displays html-encoded characters

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#70363]
Some plugins that contain special characters like `&` do not display correctly the title after installation

For example `Health Check & Troubleshooting`, when the plugin is installed,  `&` in the title changes to `&amp;`. 

![Screen Shot on 2022-11-24 at 15:40:37](https://user-images.githubusercontent.com/66711744/203732106-f0ba245c-0ea3-42ae-83f8-24828781eb10.jpg)

One suggestion is to use a library like `@wordpress/html-entities` to the decode them.

Related convo: p1669275801456189-slack-C029JEQRVRT

**Comment by inaikem** [comment]
**Note:** I updated the original screenshot to obscure domains and other PII

**Comment by gcsecsey** [comment]
I think this issue might be related: #70273
