### ISSUE TITLE
Register GitHub as a keyring service

### ISSUE THREAD

**Issue by mpkelly** [Automattic/wp-calypso#70375]
### Details

Add GitHub as an external connection that the Keyring manages. See discussion [here](pdKhl6-1u2-p2#comment-1959). 

### Checklist

- [x] Endpoint `/me/connections` should include the GitHub connection
- [x] Should be able to connect and authorize GitHub which then results in an `access_token` being stored by the Keyring
- [x] ~UI at `/marketing/connections/:site` should reflect the connected state~ UI added in https://github.com/Automattic/wp-calypso/pull/72625 should reflect the connected state

**Comment by mpkelly** [comment]
I will reuse the app I used when doing the analysis. I've added a logo and description and changed the name.

https://github.com/apps/wordpress-dot-com

Later on, we'll move this app to the Automattic org.

**Comment by p-jackson** [comment]
Completed by D99604-code
