### ISSUE TITLE
Menus don't display well at smaller viewport widths

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#70374]
# Description
For post-CfT, probably good to fix before we launch the MVP

Is this a pattern problem?

![Image](https://user-images.githubusercontent.com/5665959/203823750-476bb489-5dc7-4fea-bac2-485b4bad6cea.png)

@Automattic/ganon

**Comment by autumnfjeld** [comment]
See chat p1669682784727679/1669682695.821939-slack-C048CUFRGFQ
"Can always be resolved with max site title widths"

**Comment by bangank36** [comment]
I think it is related to pattern, since I use the BC3 theme on my site and did not see the problem ( the nav will break to new line )

![](https://user-images.githubusercontent.com/10071857/204572974-601c9c45-4dc0-4e5a-9fe8-53ec3b4d2339.gif)

**Comment by arthur791004** [comment]
It's an issue of the pattern. When I use that pattern in my side editor, the navigation is also broken into new line

![image](https://user-images.githubusercontent.com/13596067/205000741-22fed63a-8e42-4535-9586-890b82fe2801.png)

**Comment by arthur791004** [comment]
A possible way is to enable "Allow to wrap to multiple lines" for this kind of header, e.g: Simple Header. @autumnfjeld What do you think?

![Screen Shot 2022-12-01 at 4 21 17 PM](https://user-images.githubusercontent.com/13596067/205002208-eb540944-2a11-4a5f-ba3e-ba55c6bea119.png)

**Comment by autumnfjeld** [comment]
Yes, it seems to me they need to wrap.    Reach out in #dotcom-marvel if you want themer help in making decisions.

**Comment by alaczek** [comment]
Good idea! I updated the pattern.

**Comment by arthur791004** [comment]
Close it as we enabled "Allow to wrap to multiple lines" for this kind of header 🙂
