### ISSUE TITLE
Support repo `push` event listener using the GitHub API. 

### ISSUE THREAD

**Issue by mpkelly** [Automattic/wp-calypso#70380]
### Details

Once the Connect UI is in place, the user should be able to connect a repo and branch by hitting "Connect". This should call the API, which will register a `push` event listener with GIHub for the selected repo. 

We can create and share a secret with GitHub to protect webhook event payloads. The request signature should be validated on WPCOM, where the webhook event is received. 

https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks

### Checklist

- [x] Does a one-time webhook registration with the GitHub API and updates the `site` data so we know the hook is active
- [x] Has a server-side handler that can receive and copy the files from the push event
- [ ] Has PHP tests
- [ ] Should exclude symlink locations that can't be overridden.
- [x] Should generate a secret which will be stored on WPCOM and shared with GitHub,

**Comment by zaguiini** [comment]
This is done, the feature is already working.
