### ISSUE TITLE
New Welcome Tour Slide for Site Editor

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#70386]
# Description
This is not needed for CfT or MVP. (But would cool to ship it close to MVP.)

❗This card will be FLOW DEPENDENT. Meaning the card shown below is only for the PA flow.  

We want to surface this great new Site Editor video tutorial screen.  As shown in https://github.com/Automattic/wp-calypso/issues/70189.  ❗The content in the Welcome Tour will be FLOW DEPENDENT. Meaning the card shown below is only for the PA flow.  

For the Pattern Assembler flow, this should be the first card.

![Image](https://user-images.githubusercontent.com/5665959/203838147-9c8aacca-6a01-4b88-a8c2-734e1e0b7373.png)

## Open questions
Please work with @SaxonF on decisions need to be made on altering the current first card. For example: do we simply replace the current 1st card with Saxon's design above?  (Please update this issue when a decision is made.)

<img width="409" alt="image" src="https://user-images.githubusercontent.com/5665959/203838621-90770f9a-67ac-4d93-8f5b-eb1e83e5599c.png">

# References
p1669183962774579/1668795394.804869-slack-C048CUFRGFQ

**Comment by autumnfjeld** [comment]
@arthur791004  Let's change this copy:

<img width="236" alt="image" src="https://user-images.githubusercontent.com/5665959/205144783-5aa911e9-0957-48bf-b8d8-5fd963ae528b.png">

New copy:

Watch these short videos and take this tour to get started.

**Comment by autumnfjeld** [comment]
From this [slack] p1669923003312849/1668795394.804869-slack-C048CUFRGFQ convo:

For this PA scenario:
* User goes thru PA onboarding
* User lands in Site Editor at the end of onboarding
* User sees the Welcome Tour, with the new video slide
* The Welcome Tour only shows automatically ONE TIME.  The first time the user/site enters the editor.
* Later…much later….the user may access the Tour from the Editor Options menu. So yes, the text Nice job!…..  doesn’t make sense.   

For that last scenario (see screenshot below of the options menu), let’s create another [issue](https://github.com/Automattic/wp-calypso/issues/70386) to address this. Does not block  the current issue.
Issue should include:
* create a Welcome Tour with video slide that uses generic text (not PA related)
* this WT can show up in any flow when user opens SE for first time
* this WT can show when user access WT from options menu


To be clear for PA flows sites, when the user enters from Appearance > Editor the tour should not show automatically because they have already seen the tour.

We should 

![image](https://user-images.githubusercontent.com/5665959/205146149-75ae1b44-0208-4961-a3ca-73491e63e843.png)


![image](https://user-images.githubusercontent.com/5665959/205146089-378fa6da-4609-45f1-935a-6728c9e4b163.png)

cc: @Automattic/ganon

**Comment by arthur791004** [comment]
@autumnfjeld You can play it from https://github.com/Automattic/wp-calypso/pull/70641

Now, you will see the new slide when you finish the pattern assembler flow. If you refresh the page or re-enter from another entry (e.g.: Appearance > Editor), the slide will keep the same as before.

Besides, I made a change to rename `Try it out` to `Take tour` no matter whether it's a new slide or not. Does it make sense?

Last, I add a new event when the user clicks on the image or link on the new slide. (I don't think we need to distinguish the user clicks on the image or link, do we?)
* Event name: calypso_editor_wpcom_tour_site_editor_course_link_click
* Props
  * is_pattern_assember: whether the user is from pattern assembler. If we want to have a similar slide for all flows/intent, we can use this to distinguish it.

What do you think?

**Comment by fushar** [comment]
@autumnfjeld @SaxonF I have some feedback for the copy:

1. `Take tour`. Didn't we agree that this should be `Next`, according to p1669155451437569-slack-C048CUFRGFQ? Or at the very least, this should be `Take the tour`.
2. I also propose to change the description a bit (removing `it's`) to:

This is the Site Editor, ~~it’s~~ where you can change everything about your site, including adding content to your homepage. Watch these short videos or take a tour to get started.

What do you think?

**Comment by fushar** [comment]
@arthur791004 just realized that @autumnfjeld also had this comment:

> New copy:

> Watch these short videos and take this tour to get started.

which didn't get applied in the PR :)

**Comment by arthur791004** [comment]
> @arthur791004 just realized that @autumnfjeld also had this comment:

> New copy:

> Watch these short videos and take this tour to get started.

> which didn't get applied in the PR :)

Ooops, I didn't notice that!

**Comment by autumnfjeld** [comment]
Not a big deal, can happen in another PR. :)

**Comment by fushar** [comment]
All right! Approving the PR.

**Comment by autumnfjeld** [comment]
> @autumnfjeld @SaxonF I have some feedback for the copy:
> 
> 1. `Take tour`. Didn't we agree that this should be `Next`, according to p1669155451437569-slack-C048CUFRGFQ? Or at the very least, this should be `Take the tour`.

@fushar  Yes, you are right.   I like "Take the tour" but either suggestion you make is fine.

> 2. I also propose to change the description a bit (removing `it's`) to:
> 
> This is the Site Editor, ~it’s~ where you can change everything about your site, including adding content to your homepage. Watch these short videos or take a tour to get started.
> 
> What do you think?

YES, much smoother reading when removing "it's". 

Again, fine for these copy updates to go in a subsequent PR. Thanks for catching!!!  :)

**Comment by arthur791004** [comment]
Close it via [#71177](https://github.com/Automattic/wp-calypso/pull/71177), [#70641](https://github.com/Automattic/wp-calypso/pull/70641), and D96854-code
