### ISSUE TITLE
Add Tracks and Funnels; schedule calendar events for follow up

### ISSUE THREAD

**Issue by mpkelly** [Automattic/wp-calypso#70383]
### Details

Add Tracks events and maybe some Funnels. Also, set up some [calendar events](pdKhl6-1dx-p2) to evaluate uptake

### Checklist

- [ ] Tracks events are added for views and clicks of Authorize, Connect, and Disconnect buttons
- [ ] Calendar events are set up for 1m , 3m, 6m and 1y.

**Comment by p-jackson** [comment]
I've created https://github.com/Automattic/wp-calypso/pull/73748 which adds the Calypso tracks events.

I also want to record how often the webhook is called and deployments are completed, have errors, etc. Tracks isn't the right tool for this though since these events won't be associated with a particular user. I'll create a diff to add bump stats.

**Comment by p-jackson** [comment]
Count how many webhooks we receive D102687-code

**Comment by p-jackson** [comment]
Draft PR which adds stats in wpcomsh so we can count how many deployments actually complete https://github.com/Automattic/wpcomsh/pull/1282

**Comment by p-jackson** [comment]
https://github.com/Automattic/wpcomsh/pull/1282 is the final code change needed for this task I believe.

**Comment by zaguiini** [comment]
@p-jackson how do we feel about adding a card impression event when there is no connection to GitHub?

This way we can understand better if the users are authorizing, viewing the card, but not actually taking action.

Imagined state flows:

- card is seen
- GH is authorized (or not)

or

- card is seen
- GH is authorized but not connected

**Comment by p-jackson** [comment]
I don't think we need it. To measure the drop off between authorised and connected we don't need an impression event. The funnel would just be "authorised -> connected".

And for the other one, I don't know what would be a useful metric for the the drop off between card impression and authorise clicked. What's a good conversion rate there? Would be pretty small IMO; less than 1%. And it doesn't seem to measure success. It's ok for users to just visit the `/hosting-config` page without interacting with GitHub.

If we're just wanting to know the proportion of Business Plan users who use this feature then I think we can just do that with a database query.

**Comment by zaguiini** [comment]
>It's ok for users to just visit the /hosting-config page without interacting with GitHub

I mostly wanted to register the impression only when the card got into view. Still, maybe it's indeed not necessary because it's another tool in the toolbox and not everyone will want to use GH regardless of how well we sell it.

**Comment by p-jackson** [comment]
I've added a 1/3/6/12 month reminder to the Quake Team calendar with a link to this post which contains ready made metrics to make things easier pet6gk-9M-p2

I've also added a method for counting the number of active users D103945-code. I think we're good with this task now.
