### ISSUE TITLE
Premium theme language is incorrect at /designSetup

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#70388]
Example 1:

![image](https://user-images.githubusercontent.com/545779/203840487-6be65fd1-ba2b-4c96-b174-3c85720ae0f2.png)

These themes are not recurring subscriptions when purchased individually.

Better would be a simpler, "Included in WordPress.com Premium.”

Example 2: 

![image](https://user-images.githubusercontent.com/545779/203842794-d3c509b5-b4c3-4db4-8984-3f9796d8026f.png)

![image](https://user-images.githubusercontent.com/545779/203842863-416c71f8-bfea-48f1-82ad-ee365f6275c4.png)

This is not a subscription for an individual theme. More correct language here would be, "Gain access to all our Premium themes with a subscription to the Premium plan."

![image](https://user-images.githubusercontent.com/545779/203843376-090790d7-f074-47ac-8ddd-907681d44abd.png)

Because of the language of this button and the previous copy it makes it seem as if you're about to purchase just the theme. What actually happens is we add the Premium plan to a cart.

More correct labelling would be "Upgrade to activate."

**Comment by SaxonF** [comment]
![image](https://user-images.githubusercontent.com/1072756/203871255-c6c75e2f-ccf9-40f3-927c-b292694d4640.png)

![image](https://user-images.githubusercontent.com/1072756/203893937-ddeeee30-df15-493d-a0ac-08113ad198f6.png)

![image](https://user-images.githubusercontent.com/1072756/203893830-c9d3a2f4-68dd-476a-9ea8-793bfb20a2f3.png)

**Comment by bangank36** [comment]
Suggest to use current copy `Included in WordPress.com Premium` in [here](https://github.com/Automattic/wp-calypso/blob/271c4f23020f5f1cd6154f4954e5d23eba83600e/packages/design-picker/src/components/index.tsx#L130), so that we don’t have to wait for the translation of `Included in the Premium plan`

**Comment by bangank36** [comment]
There are 3 kinds of upgrade modals:  

*   First-party themes:[https://d.pr/i/WyNlGx](https://d.pr/i/WyNlGx)
*   Third-party themes:[https://d.pr/i/XeWGB6](https://d.pr/i/XeWGB6)
*   Woo themes:[https://d.pr/i/dYC7RK](https://d.pr/i/dYC7RK)

Third-party themes upgrade modal can be enabled only with flag `'themes/subscription-purchases'` ( [link](https://github.com/Automattic/wp-calypso/blob/c772124d764ce4afa570c8776fe4394a738d3439/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.tsx#L190) ), so this [#70398](https://github.com/Automattic/wp-calypso/pull/70398) will update the standard upgrade modal in [here](https://github.com/Automattic/wp-calypso/blob/c772124d764ce4afa570c8776fe4394a738d3439/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.tsx#L52)

**Comment by bangank36** [comment]
Closed as landed
