### ISSUE TITLE
Reading Settings: Add "For each new post email, include..." newsletter setting

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#70427]
This task is part of group of tasks responsible for separating `rss_use_excerpt` to apply to RSS feeds only.

Add new newsletter section setting to Reading settings page. The new setting will be responsible for dictating whether the New Post email notification should include the whole post content in the email body or just an excerpt.

See related conversation: pdDOJh-15W-p2#comment-812

**Comment by mashikag** [comment]
@saygunnyc 👋 
1. Could you please help us to  come up with a copy for this new Newsletter setting?
2. When it comes to the UI I believe we can kinda copy the RSS setting design, right? 


![Image](https://user-images.githubusercontent.com/2019970/203984139-ea16440d-ee87-458e-a8de-43b0d7fa723d.png)

**Comment by saygunnyc** [comment]
Hey @mashikag, 
Yes, as discussed, we can duplicate the same section visually. Below, I took a crack at the copy. cc @michaelpick for a review once he gets the chance.

__

**For each new post email, include**
- Full text
- Excerpt

_Sets whether email subscribers can read full posts in emails or just an excerpt and link to the full version of the post. [Learn more about sending emails](https://wordpress.com/support/launch-a-newsletter/)._

__


Not directly related, but it can perhaps be linked to the **"Sending Emails"** title on the **"Launch a Newsletter"**support doc. Perhaps we mention this setting there too. Lemme know your thoughts!

**Comment by mashikag** [comment]
Thanks @saygunnyc ! The copy sounds good to me. 

> Not directly related, but it can perhaps be linked to the "Sending Emails" title on the **"Launch a Newsletter"**support doc. Perhaps we mention this setting there too. Lemme know your thoughts!

I do not see the setting to be mentioned there. I also think it may be a good idea to talk about it somewhere in the docs. Would you know a specific person/team responsible for the docs that we could suggest it to?

**Comment by saygunnyc** [comment]
Maybe @jordesign might be the right person to ping for help finding that person! 😄

**Comment by michaelpick** [comment]
> Sets whether email subscribers can read full posts in emails or just an excerpt and link to the full version of the post. [Learn more about sending emails](https://wordpress.com/support/launch-a-newsletter/).

Sorry for the slow reply – I'm getting caught up after a couple of days out with flu 🙇 

This reads well to me, @saygunnyc, and I like that it's consistent with the RSS approach 👍

**Comment by saygunnyc** [comment]
Thanks so much for reviewing @michaelpick!
And hope you're feeling better!

**Comment by jordesign** [comment]
Pinging @donalirl  and @ktyfuller604 re: Docs for this new setting.
