### ISSUE TITLE
Reading Settings: Uptake the new `wpocm_subscription_emails_use_excerpt` site option

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#70435]
In New Post subscription email notifications include either full post content or a post excerpt depending on the current site's value of `wpocm_subscription_emails_use_excerpt` option.

**Comment by sophiegyo** [comment]
We had a question about this just now - user's site has feed settings currently on "excerpt" but their new post emails are showing the full text. Honestly, so is the individual post in the feed too.

Is this expected while these changes are still in development?

Example feed:
https://wordpress.com/read/feeds/7566900
Example post from feed:
https://wordpress.com/read/feeds/7566900/posts/4428132252

**Comment by supernovia** [comment]
Noting this previously worked to just send the excerpt or first several lines of the email, so this has changed recently.

**Comment by mashikag** [comment]
Thank you so much for your reports @sophiegyo  and @supernovia ! ❤️

> Is this expected while these changes are still in development?

No, not at all. This looks like a regression indeed. I am looking at this now. 👀

**Comment by mashikag** [comment]
This task was done in: D95517-code

**Comment by mashikag** [comment]
@sophiegyo despite the fact that this task was just done, the feed setting should still apply to our users until they manually will apply the new setting - this is not possible to do so in production yet as the new Reading Settings page is not released yet.

Sometimes a post can be sent in full content if the post's length is less than what is required for an excerpt to be generated. As per wporg documentation the default excerpt length is 55 characters ([see here](https://developer.wordpress.org/reference/functions/the_excerpt/#:~:text=the%20default%20length%20is%2055%20words)).

In case the post was actually longer than 55 characters, and the excerpt still does not apply. Would it be possible for you to share the exact post with me?

**Comment by mashikag** [comment]
Sorry @sophiegyo, I just re-read your comment after creating the above response. I realized that you did actually provide me with the actual example of where the issue was experienced.

> Example feed:
https://wordpress.com/read/feeds/7566900
Example post from feed:
https://wordpress.com/read/feeds/7566900/posts/4428132252

I have taken this up to trigger a new post email for the exact post to my own email and the below was what I got:
![Screen Shot 2022-12-16 at 17 38 46](https://user-images.githubusercontent.com/2019970/208146811-2e2ed4b9-86a0-4949-988a-415bf44f9f1b.png)

The new post email includes an excerpt as expected. Another words I was unable to reproduce the issue. Did you experience the issue first hand, i.e. yourself, or it was only the report from the user that you received? Perhaps any screenshots with it? 

> user's site has feed settings currently on "excerpt" but their new post emails are showing the full text. Honestly, so is the individual post in the feed too.

I am not sure about this one though. Is the setting supposed to display an excerpt in the individual post in the feed? Not sure... 

@supernovia would you be able to answer the following question specifically? The "excerpt" setting seems to apply as expected to the RSS posts feed (https://wordpress.com/read/feeds/7566900) but it does not seem to apply to a single post feed (https://wordpress.com/read/feeds/7566900/posts/4428132252). Is the setting expected to apply to a single post feed too?

Perhaps we should relate to wporg's behavior for the setting. Does it work the same as in wpcom?
