### ISSUE TITLE
Components: Form Text Input With Affixes don't expand as needed on Safari

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#7044]
On Safari (`Version 9.1.1 (11601.6.17)`), the affixes don't expand to accommodate longer text:

<img width="739" alt="screen shot 2016-07-26 at 21 28 43" src="https://cloud.githubusercontent.com/assets/3392497/17152549/8191da5e-5378-11e6-9272-68d43984a130.png">

On Chrome (`51.0.2683.0`), it works correctly:

<img width="711" alt="screen shot 2016-07-26 at 21 29 24" src="https://cloud.githubusercontent.com/assets/3392497/17152552/89022c26-5378-11e6-8967-51f4dc159b90.png">

To test, visit https://wpcalypso.wordpress.com/devdocs/design/form-fields and change the text in the affixes using Developer Tools. In the wild, these types of fields can be seen in the DNS Editor (`https://wordpress.com/domains/manage/:site/dns/:domain`), where they are used for the domain suffix part.

cc @mtias

**Comment by folletto** [comment]
It seems both `.form-test-input-with-affixes_suffix` and `.form-test-input-with-affixes_prefix` are missing the `flex` property? A quick live`flex: 1 0 auto;` (grow, don't shrink, auto-size) addition seems fixing it.

---

Aside: the font size of prefix/suffix should match the input text box, right now seems bigger.
