### ISSUE TITLE
[Bug]: Incorrect theme preview when switching back to a global styles modified theme

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#70448]
### Quick summary

Only one of the two previews when switching back to a global-styles customised theme takes into account global styles.

### Steps to reproduce

1. Enable the skatepark theme
2. Open up the site editor
3. In the global styles menu change the background colour
4. Save global styles
5. Switch theme to any other theme
6. Switch back to global styles

### What you expected to happen

The theme showcase theme switch preview modal would show two accurate previews - both the _preserve homepage_ preview and the _replace homepage_ preview would show previews with my global styles set background color taking effect.

### What actually happened

The _preserve homepage_ option did show a correct preview, the _replace homepage_ didn't.

Here's the previews: 
![image](https://user-images.githubusercontent.com/93301/204039345-abe8e25f-eb9f-418e-be88-fa40c4e8de8c.png)

Here's what my site looked like when replacing homepage:
![image](https://user-images.githubusercontent.com/93301/204039384-ab364ceb-3b47-4b8b-bdc8-e052647f9e5c.png)

### Other notes

Probably the _replace homepage_ comes from the theme demo/headstart content, and doesn't load global styles.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by karenroldan** [comment]
I was able to replicate it in both simple and atomic sites. Only the `preserve homepage` displayed the global style I have set, but not on the `replace homepage` preview

![simple](https://user-images.githubusercontent.com/67279475/218484712-e07f63a5-fcf7-47cc-8c4e-6f110704c8fd.png)

**Comment by mgozdis** [comment]
Had a user report similar issue on a Simple site. They selected a different style and were upset that a previous Global Style was preserved instead of using the Default style they selected: ![QKHoSE.png](https://github.com/Automattic/wp-calypso/assets/121042930/6275d99e-1c71-4c6d-816f-48335866e7b2)

They were expecting the Default style selected to display and apply while preserving their homepage.

**Comment by karenroldan** [comment]
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Low` to better reflect its status in the larger context of open bugs in this repo.

**Comment by dsas** [comment]
Now we've got rid of this switcher dialog we can just close this issue.
