### ISSUE TITLE
[Bug]: Embed Block doesn't work on FSE themes

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#70457]
### Quick summary

Embed doesn't seem to work on simple sites with FSE theme active. It displays fine while on the editor, but it displays as a hyperlink on the live page/post. 

The link tested was: 

https://blog.petrieflom.law.harvard.edu/2022/11/21/the-res-nullius-construction-of-human-genomic-data/

**Test on Free site with FSE theme - Quadrat**

[Link](https://rosetestingmarketplace182152970.wordpress.com/2022/11/27/embed-test-2/)

![Screen Shot on 2022-11-27 at 09:02:25](https://user-images.githubusercontent.com/9984867/204114624-bd7623b5-3133-42e4-8616-b80a75315284.png)

**Test on Free site with non-FSE theme - Twenty Twenty One**

[Link](https://rosetestingfse.wordpress.com/2022/11/22/26/)

![Screen Shot on 2022-11-27 at 09:08:00](https://user-images.githubusercontent.com/9984867/204114755-de1b02a3-dd47-4de7-a4ad-2d26d748ba76.png)

---

FSE themes tested so far: 

Masu
Blockbase
Cultivate
Geologist
Attar
Quadrat

_I couldn't confirm this is happening to all FSE themes. So far, it's more like an intermittent issue, but something we could probably look at._ 

### Steps to reproduce

1. Enable FSE theme on a simple site. 
2. Create a new post. 
3. Embed the link - https://blog.petrieflom.law.harvard.edu/2022/11/21/the-res-nullius-construction-of-human-genomic-data/

### What you expected to happen

Embed will work on the live post. 

### What actually happened

Embed shows while on the editor, but it shows only the hyperlink on the live post. 

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Issue was reported here - p2EDhh-1LZ-p2
Discussed here - p1669085454810989-slack-C03TY6J1A
Follow-up ticket - 5731510-zen

### Reproducibility

Consistent

**Comment by zachspears** [comment]
Hello @rosepajaroja, I was just testing the embed on a Simple site, and the embed was working fine when tested in Geologist, Attar, and Cultivate. It looks like this issue may have been resolved. Can you confirm if you are still seeing the issue with embedding? Thanks!

**Comment by vajrasar** [comment]
Please feel free to re-open this report if the issue persists.
