### ISSUE TITLE
Pattern Assembler - Adding sections behaviour

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#70461]
Section pattern selection: pattern panel should stay open until user selects all section patterns.

## Acceptance criteria
- When entering the section adding state, clicking a pattern will add it to the preview but the user should remain in this state to allow them to continue picking sections.
- When replacing a pattern, the pattern being replaced has a dark border indicating the status "selected/added". Existent feature.
- When ready, they click "Done" to go back to the list of selected patterns.

## UX Notes
- Maybe the "replace" action name and icon need to be reviewed? The behavior is not the same for the header and footer, and sections. The header and footer will be replaced with only one pattern, but sections can be replaced with multiple patterns.
- When in the section adding state, selected patterns are previewed on the right and added one after the other in the order they are added. Users cannot order patterns in this state, they must go back to the list to order patterns.

Related [Pattern assembler refinements from walkthru call#1251](https://github.com/Automattic/dotcom-forge/issues/1251)

**Comment by miksansegundo** [comment]
@Automattic/ganon can you share your thoughts about this change? I think adding multiple patterns won't work well with the toggle feature.

**Comment by SaxonF** [comment]
@miksansegundo I think to keep this simple to start with:
- When inserting a _new_ pattern there is no selected/added state. A user can add the same pattern multiple times.
- When replacing a pattern, the selected pattern has selected state, but clicking a pattern returns to the list, so no change here.

Basically the pattern inserter needs to have a `selectMultiple` type prop so it can handle both scenarios.

> When in the section adding state, selected patterns are previewed on the right and added one after the other in the order they are added. Users cannot order patterns in this state, they must go back to the list to order patterns.

This is true and something I imagine will come up during testing but let's keep an eye on it. There are other ways around this like being able to re-arrange patterns from the frame.

**Comment by fushar** [comment]
Do we have another issue for header/footer selection? The behavior is different: we're always replacing the pattern, but the pattern inserter can stay open.

**Comment by miksansegundo** [comment]
> Do we have another issue for header/footer selection? The behavior is different: we're always replacing the pattern, but the pattern inserter can stay open.

@fushar I have created another [issue](https://github.com/Automattic/wp-calypso/issues/70473).

**Comment by autumnfjeld** [comment]
Closing this.

We did one early metrics analysis: [Early Blank Canvas PA Metrics Peek] pbxlJb-3cX-p2  then found problems in how some of the events were firing, then fixed them [Pattern Assembler Success Metrics] pbxlJb-3bS-p2  
We'll do a formal and thorough metrics analysis within the next week.
