### ISSUE TITLE
Woo Tailored Onboarding: standardize how frames are presented

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#70469]
![image-26 (1)](https://user-images.githubusercontent.com/1234758/204255286-f2f65f84-4eee-4b41-8120-3e651a5d30aa.jpg)

It would be nice if we could standardize how web/browser frames are presented across the platform. Maybe we can pull out the web-preview__frame [class that Launchpad uses](https://github.com/Automattic/wp-calypso/blob/7d1193391edbdb76e685ad62d62ff78f7cc2cd1d/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss#L442), so it can be put to use in other places like this theme picker carousel.

The link in the bio is the only live flow, and that’s mobile-focused. Videopress and Blog flows may use it as well.

More info: pdtkmj-LF-p2#comment-1193

**Comment by markbiek** [comment]
Looks like this has already been handled on the tailored ecommerce flow.
