### ISSUE TITLE
Virtual Pages: Revamp page header

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#70465]
## Description

As part of the [iterative style updates to Calypso](p9Jlb4-5H1-p2) initiatives, we want to make several changes to the Pages page, especially related to the virtual pages.

[Context](pdtkmj-MO-p2#comment-1208)

## Screenhots

| Before | After |
| -------|----- |
| ![Image](https://user-images.githubusercontent.com/1525580/204213100-d6af43d0-8609-404d-b332-f504698f29f5.png) | ![Image](https://user-images.githubusercontent.com/1525580/204214079-80819968-792b-4e70-b2bf-ad9ee9e612ea.png) |

## Acceptance Criteria

- [ ] The "Add new page" CTA is now at the top-right corner of the page
- [ ] There is only one "Pages" heading, which is at the top-left corner of the page
- [ ] The Published count now includes the virtual homepage page

@Automattic/ganon @SaxonF

**Comment by autumnfjeld** [comment]
@SaxonF & @fushar Is this issue still relevant ? Or does it need updating? Or should we close it or icebox it?

I've taken screenshots of the feature that is now in production:


![Image](https://user-images.githubusercontent.com/5665959/207141197-384d23fb-78a6-4a78-9c08-962066c595d2.png)



![Image](https://user-images.githubusercontent.com/5665959/207141233-4fe7b505-83b9-41ce-a936-7d27251d5c55.png)



![Image](https://user-images.githubusercontent.com/5665959/207141428-d7885dbd-e488-4ae2-a705-c99316fa727f.png)

**Comment by fushar** [comment]
It is still relevant IF we still want to prioritize / work on virtual pages.

**Comment by autumnfjeld** [comment]
Given the advances in the Site Editor and the Pages view there, I don't think we need this in Calypso.
