### ISSUE TITLE
Marketplace search: display WC.com product prices on search results

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#70479]
Subtask of https://github.com/Automattic/wp-calypso/issues/63905

When fetching WC.com products through ES, the prices are currently not displayed. This is most likely because there's no variation IDs sent in the API response, so no WPCOM product is found for the variations here:
https://github.com/Automattic/wp-calypso/blob/84586808865a834278f0366e79fd0265fba3b2b2/client/my-sites/plugins/plugin-price/index.jsx#L15-L16

To show prices:
- [x] variation IDs need to be returned in the API response D93605-code
- [x] variation IDs need to be mapped to the product type in Calypso https://github.com/Automattic/wp-calypso/pull/70483
- [x] add all variation IDs in WC.com https://github.com/Automattic/wp-calypso/issues/71137
- [x] add all product slugs in WC.com https://github.com/Automattic/wp-calypso/issues/71139

**Comment by gcsecsey** [comment]
Diff created with the API changes: D93605-code

**Comment by gcsecsey** [comment]
WPCOM changes deployed with r256940-wpcom

**Comment by gcsecsey** [comment]
While testing #70483 I've found that not all Marketplace products have their prices stored in ES. This is because the variation IDs are missing from WC.com and aren't synced yet. We'll also have to go through the catalog and assign the variation IDs of all existing marketplace products in WC.com, eg.: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Spynff%2Qznexrgcynpr%2Qcebqhpg%2Qpngnybt.cuc%3Se%3Q43n62p9q%231567%2Q1574-og

**Comment by gcsecsey** [comment]
The issue in #70483 is caused by the product slug not being stored and used from ES. I've added a more detailed description [here](https://github.com/Automattic/wp-calypso/pull/70483#issuecomment-1330657168) and will create a diff to address this, but we'll also need to go over the catalog and add all product slugs to WC.com, I'll add this to the checklist.

**Comment by gcsecsey** [comment]
Diff raised for adding `product_slug`: D93742-code

**Comment by epeicher** [comment]
I have reviewed and accepted D93742-code 👍

**Comment by gcsecsey** [comment]
Diff deployed with r257048-wpcom
