### ISSUE TITLE
"My Themes" sometimes fails to appear

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#70477]
### Quick summary

In Appearance > Themes, Atomic sites should display "My Themes," which is an area where users can manage their installed themes. Sometimes "My Themes" does not appear.

### Steps to reproduce

To make "My Themes" fail to appear:

1. Go to Appearance > Themes on an Atomic site.
2. Refresh the page.
3. "My Themes" will not appear.

There may be other conditions where "My Themes" does not appear.

### What you expected to happen

"My Themes" should appear in Appearance > Themes

### What actually happened

Sometimes "My Themes" does not appear.

### Context

Customer report 38254867-hc

Customer reported difficulty finding where to delete their installed theme. "My Themes" did not appear for them until I found a workaround (noted below).

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Click on another tab, for example "Settings," then navigate back to Appearance > Themes.

**Comment by fushar** [comment]
I can reproduce this. There is something wrong in the theme showcase. This is a perfect issue for @Automattic/lego's year-end maintenance initiative.

**Comment by fushar** [comment]
This is fixed and shipped!
