### ISSUE TITLE
Woo Tailored Onboarding: Store Profiler data is not being persisted

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#70476]
![Screen Shot 2022-11-28 at 10 46 32](https://user-images.githubusercontent.com/1234758/204293149-f5fa20e8-b636-4ed6-a2ff-fdfb6b27ae72.png)

The store profile information is not filled if I hit the back button on the design carousel step.

**Comment by valterlorran** [comment]
PR #69721 should've prevented this.

**Comment by blackjackkent** [comment]
Closed by #69721
