### ISSUE TITLE
Woo Tailored Onboarding: The Woo “Store Details” task in the task list should be completed by default

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#70471]
![Screen Shot 2022-11-28 at 08 27 17](https://user-images.githubusercontent.com/1234758/204266731-76216712-32b9-4a2b-a8af-6c4d55561c0b.png)

When we land on the wc-admin page, the "Store Details" task is incomplete. I made sure I selected the industry and the location in the store profiler step.

More info: pdtkmj-LF-p2#comment-1275

**Comment by valterlorran** [comment]
This issue can be related to #70476.

**Comment by nelsonec87** [comment]
I wasn't able to reproduce it locally (`trunk`)
![image](https://user-images.githubusercontent.com/3801502/204360349-6e9a91c9-fd75-4fbd-bd79-8b1342fc0838.png)

nor on wordpress.com
![image](https://user-images.githubusercontent.com/3801502/204360391-06e78b67-c69d-43a3-b6fc-22a550c597e9.png)

But, even though the steps shows up for me as completed, checking the vertical_id shows `false`, which is wrong.
