### ISSUE TITLE
Navigation block: Unable to add submenu items to overlay menu (mobile menu)

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#70486]
### Quick summary

For some links (particularly those with shorter text titles, it seems), it is impossible to add a submenu link when editing a Navigation block with the "Overlay Menu" setting set to `Always`. The submenu `+` button is rendered off-screen, and there's no way to scroll over to click it.

### Steps to reproduce

1. Activate any block theme (FSE theme) and open the Site Editor.
2. Insert a Navigation block on the right side of the site's header. Make sure the **Overlay Menu** setting is set to **Always**.
3. Click on the Navigation block to open it, and add a top-level menu link (if needed).
4. Click on the menu link, and click the "Add submenu" button in the floating toolbar.

### What you expected to happen

The `+` button to add a submenu link should be visible to add a new submenu link.

### What actually happened

For some links, the `+` button is rendered off the right side of the editing window. A horizontal scrollbar appears, but it doesn't work. 

![Markup on 2022-11-28 at 12:02:21](https://user-images.githubusercontent.com/5630717/204337766-b1ce9f7a-d3b0-44d2-a1c0-ea914a7993d4.png)

### Context

38245695-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Switch the Navigation block's "Overlay Menu" setting to either `Off` or `Mobile` to setup submenus without the overlay, then switch back to `Always` when finished.

**Comment by zachspears** [comment]
Hello @jp-imagines, I am unable to reproduce this bug for mobile overlay menus. Is this happening in a specific theme? Here is what I am seeing:

<img width="1693" alt="Screenshot on 2022-12-13 at 20-30-52" src="https://user-images.githubusercontent.com/10124024/207499132-cc8c8a97-257e-4177-98a9-ffe5926340ca.png">

Thanks!

**Comment by jp-imagines** [comment]
@zachspears I think there may have been some updates to the Navigation block recently. The UI for adding submenus seems to have changed, so the issue no longer occurs – submenu items are shown below their parent instead of in a separate window, and the **+** button to add another is inline within the editor.

I'll close up this issue since it seems fixed. 👍
