### ISSUE TITLE
Reader: like & comment buttons do not receive the tap on the full post view on IE Mobile 10

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#705]
Steps to reproduce:
1. View the reader on a Windows Phone's IE 10 browser
2. Tap a card to display the full post view
3. Tap either the comment or like button at the top of the screen

<strong>Result:</strong> the tap is actually received by one of the buttons on the master bar, opening either the editor, or notifications depending where you tap.

From aerych:

<blockquote>I used a Nokia 920 sporting Windows Phone 8.0.</blockquote>

**Comment by alisterscott** [comment]
Closing as low priority bug that hasn't been looked at for some time.
