### ISSUE TITLE
Odyssey Stats: Add loading spinner or similar for Stats pages and/or components

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#70509]
The requests from Odyssey Stats need to be proxied to WPCOM, which greatly increase the latency of the response of the pages. The components are blank while loading data.

Calypso Stats seems okay tho benefiting from accessing `public-api` directly.

**Comment by wilmersondasilva** [comment]
@kangzj I'm not sure if I got this issue. When I access the Odyssey Stats, I see a loading spinner. Can you provide more details or attach a video?



![Image](https://user-images.githubusercontent.com/6406071/212393068-e88fde8d-b19d-4c9a-a8d6-5bfea7d36b94.png)

**Comment by kangzj** [comment]
@wilmersondasilva thanks for looking into this. This was addressed in https://github.com/Automattic/jetpack/pull/28219 and I’m closing it now.
