### ISSUE TITLE
Unable to view the active upgrade item when viewing in another language (ie: RU, ES)

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#70515]
### Quick summary

I had a user on chat who was unable to remove an item from their active upgrades. They met with the following error when viewing it:

"Lo sentimos, se ha producido un error al intentar cargar esta página."

This was tested with RU and ES languages.

No issue when the language was set to EN.

Reference:
38325857-hc

### Steps to reproduce

1. Go to Upgrades → Purchases → Active Upgrades
2. Click on any of the product and item
3. Error is displayed (when language is not EN, or when the language was RU or ES)

### What you expected to happen

The active upgrade should be displayed.

### What actually happened

Error message displayed.

"Sorry, there was an error trying to load this page." (in the user's language)

**Comment by Nic-Sevic** [comment]
Posted on autopay here before we discovered the two were connected: 
pNPgK-6eM-p2

**Comment by Nic-Sevic** [comment]
seeming cause: https://github.com/Automattic/wp-calypso/commit/8046dde2270634761126bb5885440543b43f6e00

**Comment by galakhyati** [comment]
Another instance: 9110848-hc

**Comment by Nic-Sevic** [comment]
reverted cause here: https://github.com/Automattic/wp-calypso/pull/70522
p1669715203876419-slack-C02BEP610

**Comment by kriskorn** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/70522. 
Closed!

**Comment by Nic-Sevic** [comment]
> Another instance: 9110848-hc

reached out to user to let them know
