### ISSUE TITLE
Pre-publish subscribers do not include social followers

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#70520]
### Quick summary

Pre-publish checks on posts used to include number of social followers.

It previously includes social followers, as you can find it mentioned under https://github.com/Automattic/jetpack/pull/26751

We have revert changes based on https://github.com/Automattic/jetpack/pull/27083 , however subscriber counts on pre-publish checks did not include social followers there.

Reported in 5747746-zd-woothemes

### Steps to reproduce

1. Create a new post
2. Add title and contents
3. Click on Publish, pre-publish checks will appear as sidebar

### What you expected to happen

The number of subscriber counts on pre-publish checks include social followers.

### What actually happened

Number of subscriber counts on pre-publish checks only include number of WordPress.com followers, no social followers.

### Reproducibility

Consistent

**Comment by TimBroddin** [comment]
I took a look and right now, it looks like they are getting the new panel, which has the counts split out:

![CleanShot 2022-12-02 at 15 54 48@2x](https://user-images.githubusercontent.com/528287/205321554-9a26015f-009b-473e-b04c-d063a6fb42b3.png)

(I'll take a look at the translations of those.)

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: Could Not Replicate
- Tested on AT: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- As noted above, it looks like the social followers are now shown broken out from site subscribers. Tested on AT and Simple:

**AT**
<img width="1227" alt="Markup 2022-12-20 at 14 01 33" src="https://user-images.githubusercontent.com/27249804/208767873-304f8ec8-0634-4967-a2f1-208db260afd1.png">

**Simple**
<img width="1242" alt="Markup 2022-12-20 at 14 12 16" src="https://user-images.githubusercontent.com/27249804/208767882-e989bbd3-5493-4541-9132-da3a6d60eca2.png">

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
