### ISSUE TITLE
Woo Tailored Onboarding: Creating a new user redirects to /read

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#70545]
If we create a new user through the new Woo flow, we get redirected to `/read` and not to `/setup/ecommerce?flags=signup/tailored-ecommerce`

Steps to reproduce:
* Navigate to `/setup/ecommerce?flags=signup/tailored-ecommerce` on an incognito tab, and make sure you are not logged in.
* Fill in the information to create an account
* Get redirected to `/read` instead of being redirected back to `/setup/ecommerce?flags=signup/tailored-ecommerce`

**Comment by markbiek** [comment]
I did some testing and I can't reproduce this on development, only production.

That seems to me like it's an issue with the feature flag getting lost during the account creation process and not an issue with the flow itself.
