### ISSUE TITLE
Promoted Posts: Replace the current banner on /stats

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#70546]
P2 post: pb5gDS-2fR-p2

Replace the current banner on /stats with a banner for the new Promoted Posts feature:

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1044309/204637919-33788501-f2e2-463a-8557-8f7e480e48bc.png">

### Next step
Waiting for design input:

- Create a new banner for Promoted Posts
- Consider a better and more contextual placement of the stats banner, as it’s currently at the very bottom of stats.

**Comment by allilevine** [comment]
@paulopmt1 Closing since we added the mini-carousel on /stats, let me know if there's still more to do.
