### ISSUE TITLE
Woo Tailored Onboarding: designCarousel step should be more responsive

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#70551]
Perhaps not restricted to this project, the design picker could use work for responsiveness. The chrome around the edge gets cut off on tablet-size screens.

https://user-images.githubusercontent.com/1234758/204646977-fab981fc-574b-478c-899b-72bc65148928.mov

**Comment by daledupreez** [comment]
This is a duplicate of #70644, which was addressed by #70789 last week.
