### ISSUE TITLE
Free Flow: Add Name Generation Field to Setup Screen

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#70554]
### Details

The current Free Flow is simply using the same setup screen as Link in Bio. We need to add a domain generation field to that form. Because this field will effectively replace the domains screen, in addition to adding the field to the form, we will need to ensure that the domain from this field is provided downstream to the code that actually does the site setup process.

Notes: 
- Requires that the name generation script be ready for use. 
- This will be related to the task to [remove the Domains screen](https://github.com/Automattic/wp-calypso/issues/70553).
- Figma designs are not yet ready, but you can refer to this P2 for design: p9Jlb4-5ST-p2

**Comment by Addison-Stavlo** [comment]
conversation in slack - p1671115195790299-slack-CHN6J22MP 

as we decided to avoid showing the domain to the users at this stage to hopefully limit confusion, friction, overthinking, etc.
