### ISSUE TITLE
Free Flow: Add Choose Design Screen

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#70559]
### Details

The Free Flow has a Choose Design screen to allow a user to choose a theme. For now, the current flow is just using the Choose Design screen for Link in Bio as a placeholder. We need to update this to match mockups (for now, see p9Jlb4-5ST-p2). 

Notes: 
- This may be a big enough tasks that we should break it into sub-tasks. 
- This task may also require conversation. For example, which themes do we include? How does theme options affect the [Edit your design](https://github.com/Automattic/wp-calypso/issues/70558) task for launchpad? 
- See this P2 for details on Free Flow: p9Jlb4-5ST-p2

Related: 
[Free Flow Tracking Issue](https://github.com/Automattic/wp-calypso/issues/69899)

**Comment by Addison-Stavlo** [comment]
Is this issue now fulfilled with https://github.com/Automattic/wp-calypso/pull/71279 @agrullon95 ? Or is there anything else outstanding to follow up on related to this?

**Comment by agrullon95** [comment]
@Addison-Stavlo - https://github.com/Automattic/wp-calypso/pull/71279 added the design picker for the free flow. I'll go ahead a close this issue.
