### ISSUE TITLE
Plans: refactor to remove old plans design

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7056]
We've tested a new design for the `/plans/:site` and `/start/plans` pages and it's been successful, so it's time to remove the old code. #7054 is of course a prerequisite before starting this.

Before we can rip out the old code however, we need to enable this feature for all environments, including [desktop.json](https://github.com/Automattic/wp-calypso/blob/master/config/desktop.json) and [desktop-mac-app-store.json](https://github.com/Automattic/wp-calypso/blob/master/config/desktop-mac-app-store.json). This would also need to be coordinated with launching the personal plan to those environments as well because the plans page was designed to include the personal plan. I'm not sure if there are still any reasons we can't just do that. @rodrigoi may have some good background info here.

This task is for both the code cleanup and coordinating to make sure we can safely launch in these environments.

**Comment by lamosty** [comment]
Asked in Slack and:

> `desktop-mac-app-store.json` is legacy and no longer used

So I assume `desktop-mac-app-store.json` is no longer a blocker for us.
