### ISSUE TITLE
Virtual pages: Add missing stats and QR code to virtual homepage menu

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#70569]
### Description

Add the following missing three-dot (ellipsis) menu items to the virtual homepage:

- [x] Stats link, pointing to https://wordpress.com/stats/post/0/<domain> (verify that it really works)
- [x] QR code, pointing to the homepage address.

### Metrics
See prior work in https://github.com/Automattic/wp-calypso/issues/70487
- [x] Add tracking for stats `calypso_pages_ellipsismenu_item_click | item=viewstats`
- [x] Add tracking for QRcode  `calypso_pages_ellipsismenu_item_click | item=qrcode`

@Automattic/ganon

**Comment by autumnfjeld** [comment]
Just noting this is low pri compared to items we need for PA MVP.

**Comment by fushar** [comment]
For future reference: this `https://wordpress.com/stats/post/0/{siteSlug}` link works only if the site's reading settings is set to "latest posts". If it is set to show a static page, the link is "broken":

| Latest posts | Static page |
|-|-|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/1525580/205800606-52ef22e5-1e7e-4000-b436-a1f9f6c922e2.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/1525580/205786658-c644a181-dd74-4fcb-9c30-16ef681c0e64.png">|

As we don't support the static page use case for now, we'll go ahead with this link.

**Comment by bangank36** [comment]
> For future reference: this `https://wordpress.com/stats/post/0/{siteSlug}` link works only if the site's reading settings is set to "latest posts". If it is set to show a static page, the link is "broken":
> 
> Latest posts Static page  
>  
> 
> ![image](https://user-images.githubusercontent.com/1525580/205800606-52ef22e5-1e7e-4000-b436-a1f9f6c922e2.png)
> 
> ![image](https://user-images.githubusercontent.com/1525580/205786658-c644a181-dd74-4fcb-9c30-16ef681c0e64.png)
> 
>   
> As we don't support the static page use case for now, we'll go ahead with this link.

Could we check for reading settings to show/hide stats item?

**Comment by fushar** [comment]
> Could we check for reading settings to show/hide stats item?

We can investigate this later when we decide what to do if the reading setting is set to show static page.
