### ISSUE TITLE
Reader: update discover following to follow the source site

### ISSUE THREAD

**Issue by jhnstn** [Automattic/wp-calypso#7057]
The follow option in the discover stream [here](https://wordpress.com/discover) only allows following https://discover.wordpress.com/. 
Instead the source site should be followed.

There are also some inconsistencies with full width discovery posts. 
When the discover pick is a post then the follow option is for the source site. 
When discover pick is a site https://discover.wordpress.com/ is the site that can be followed

#### What I expected
When viewing a discover pick I should be able to follow the source site

#### What happened instead
I am only able to follow the source site when the pick is a post and I am in full width view.
All other follow options are for discover.wordpress.com.

**Comment by jancavan** [comment]
One option is the addition of in-content follow buttons similar to: https://github.com/Automattic/wp-calypso/issues/2834

To note, there are some sites where we may not be able to add a follow button since they're non wpcom: https://wordpress.com/read/blogs/53424024/posts/16003, or maybe we could but just add their RSS?

**Comment by jhnstn** [comment]
@jancavan per your note: It seems like we can follow jetpack sites the same way we follow wpcom sites. We would need a workaround for self hosted sites but I've been told non-jetpack self hosted sites rarely get added to discovery 

The only outstanding issue with jetpack sites is figuring out if the pick is from a jetpack site. That information is on the discover pick but it's not being passed down to the reader at the moment
