### ISSUE TITLE
FSE: Global styles background color in Gutenberg not filling the entire editing area in editor 

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#70595]
### Quick summary

When using an FSE theme and a custom background color is set in Global Styles, the editor shows the color at the top of the main edit area. Part of the way down the editing area a white area is shown. This issue does not affect the live version of the site.

For instance with a green background color set, this is what the editor looks like:

![Markup 2022-11-30 at 09 22 47](https://user-images.githubusercontent.com/93800099/204866939-2a19f996-2af8-49cd-a702-ed4b3fc1d0e8.png)

### Steps to reproduce

1. Switch to an FSE theme such as Skivers.
2. Navigate to Appearance > Editor > Global Styles > Colors.
3. Set a background color to non-white and save changes.
4. Open a new post/page for editing.

### What you expected to happen

Then entire editing area to show with the specified background color that was set in Global Styles.

### What actually happened

The top portion of the editor shows the color set in Global Styles. Part of the screen (the bottom half) is white.

### Context

38358033-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Able to replicate issue on Attar, Skivers, and Varese. It is likely this occurs on more or all FSE themes.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

You can still add content as usual to the page/post. As you add content the colored area expands.

**Comment by zachspears** [comment]
Hey @upwardmomentum84, thanks for the report! I just tested this and was unable to reproduce it. It looks like this issue has been resolved, but wanted to confirm before closing the issue. Thanks!

**Comment by upwardmomentum84** [comment]
I can't reproduce any longer either. Looks to be resolved. Closing issue.
