### ISSUE TITLE
[Bug]: Hemingway Re-written: Cover Block image height exceeds coverblock height

### ISSUE THREAD

**Issue by villanovachile** [Automattic/wp-calypso#70597]
### Quick summary

When using Hemingway Re-written, the images in cover blocks exceeds the height of the cover block, which causes the image to overlap elements below the cover block.

### Steps to reproduce

1. Add a cover block in the Editor
2. Add an image to the cover block
3. Add a paragraph after the cover block
4. Save and view page

### What you expected to happen

I expect the image to remain within the confines of the cover block as shown here in Twenty Twenty-Two:

![image](https://user-images.githubusercontent.com/65082164/204877346-b99ed4fd-03ac-474f-97af-7e0589af84be.png)

### What actually happened

The image exceeds the height of the cover block:

![image](https://user-images.githubusercontent.com/65082164/204877511-435f03a4-510e-4c69-a573-badcc221fe64.png)

### Browser

Google Chrome/Chromium

### Context

Customer report

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

The issue appears to be caused by the following CSS:

```
.entry-content img[class*=wp-image] {
    max-width: 100%;
    height: auto;
}
```

### Reproducibility

Consistent

### Severity

All

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
