### ISSUE TITLE
Reader: card menu appears in the wrong location when the screen is zoomed on IE 10 Mobile

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#706]
Steps to reproduce:
1. View the reader via a Windows Phone's IE 10 mobile browser
2. Zoom the screen a bit
3. Tap the menu icon on one of the post cards

<strong>Result:</strong> the menu opens off to the right and down a bit, proportionate to how much you've zoomed. Zooming out all the way returns the menu to the correct position.

From aerych:

<blockquote>I used a Nokia 920 sporting Windows Phone 8.0.</blockquote>

**Comment by alisterscott** [comment]
Closing as a low priority bug that hasn't been looked at in some time. Reopen if necessary.
