### ISSUE TITLE
Plans: align logged-in/logged-out plans pages

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7060]
We show pricing information for logged-out users at wordpress.com/pricing. We're discussing internally, but I think it would be best if we instead served this info from calypso so we can make sure we present content consistently when we run abtests for our plans.

This task should be to create an SSR-enabled `/pricing` page in calypso with our content from `/start/plans` and the header/footer from the logged-out pages. I think the header/footer from this page actually represents the canonical version. https://en.wordpress.com/features/

**Comment by lamosty** [comment]
Instead of having two pages with plans and pricing info (/pricing and /plans), why not only single page? In #7061, you proposed /plans to be rendered like /themes if not logged in. Therefore, we could work only on that and simply redirect /pricing to /plans. What do you think?

**Comment by rralian** [comment]
I think that sounds perfect.
