### ISSUE TITLE
Jetpack Stats: Subpages are blank (ex: Posts list, Referrers)

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#70600]
### Quick summary

Unable to see the full list of posts or referrers in Stats. Clicking on view all results in a blank page. 

### Steps to reproduce

1. Starting in the Dashboard, click "[Stats](https://wordpress.com/stats/day/)"
2. Click "[Posts & pages](https://wordpress.com/stats/day/posts/)" (or any of the cards, including Referrers and Authors)

### What you expected to happen

The full list of Posts that were viewed on the particular day should display (or the content of the other cards)

### What actually happened

A blank white screen (sidebar still appears)

### Context

Customer Report

zd-5750348

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Browser, operating system and other notes

Tested on 
* Mac Monterey 12.6.1
* * Safari 16.1
* * Chrome 107.0.5304.121

### Reproducibility

Consistent

### Severity

All

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- clicking on the section titles shown on the Stats page (pictured below) lead to a white screen:

![Markup on 2022-11-30 at 12:13:12](https://user-images.githubusercontent.com/27249804/204887775-841e1e76-12b0-4088-bb77-6567d06d79b8.png)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 Message to Author
- Escalated here: p1669835404115809-slack-C02FMH4G8
