### ISSUE TITLE
Premium Theme: Zaino

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#70616]
### Details

The Zaino premium theme needs the following:

### Checklist

- [x] [Set up the demo site](https://zainodemo.wpcomstaging.com/)
- [x] Theme showcase draft
- [x] Add the theme to the soft-launch filter
- [x] Build a ZIP for the theme
- [x] Add the theme as a product to the Store
- [x] Add the theme to the prices page in MC
- [x] Headstart annotations (don't forget to submit for translation)
- [x] GlotPress Project creation
- [x] Launch process

Cheat sheet: [paYKcK-1Pt-p2](https://href.li/?paYKcK-1Pt-p2)

Premium theme launch guide: [PNEWy-eBM-p2](https://href.li/?PNEWy-eBM-p2)

**Comment by nelsonec87** [comment]
Soft-launch diff D94768-code

**Comment by nelsonec87** [comment]
Product store diff D94912-code

**Comment by sixhours** [comment]
We started the Headstart annotation here: D95212-code 

Product images did not carry over when we tested the annotation on a simple site, but we're not sure how to test it on an Atomic site.

**Comment by sixhours** [comment]
POT file diff is here: D95213-code

**Comment by sixhours** [comment]
Headstart annotation sent for translation in Strand ID: 151816

**Comment by sixhours** [comment]
Zaino is ready for launch! When we're ready the diff to remove it from the soft launch filter is here: D95415-code

**Comment by nelsonec87** [comment]
PR adding Zaino to the eCommerce flow: https://github.com/Automattic/wp-calypso/pull/71155

**Comment by daledupreez** [comment]
We launched Zaino last week, so I am marking this issue as Done.
