### ISSUE TITLE
Stats: Polish Insights All-time views UI

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#70610]
# Development

|Desktop|Mobile|
|-|-|
|![Screen Shot 2022-11-30 at 5 48 15 PM](https://user-images.githubusercontent.com/214813/204924810-9bda577a-b9a4-40f2-b549-45dc53870566.png)|![Screen Shot 2022-11-30 at 5 48 25 PM](https://user-images.githubusercontent.com/214813/204924819-db09999c-d00d-4eb8-b00d-491ec181800a.png)|

- [x] Restyle the container and header.
( https://github.com/Automattic/wp-calypso/pull/70918 )
  - [x] Remove card borders.
  - [x] Enlarge the title and change font to match the headers on the Traffic page.

- [x] Restyle the topmost buttons.
( https://github.com/Automattic/wp-calypso/pull/70918 )
  - [x] Align to the right for desktops.
  - [x] Align to the center below the title for mobile.
  - [x] Use the same color and styles of buttons from the buttons above the chart in the Traffic page ("Days, Weeks, Months, Years").

- [x] Restyle the chart legend ("Fewer ■■■■■ More Posts").
( https://github.com/Automattic/wp-calypso/pull/70918 )
  - [x] Should be centered and enlarged.
  - [x] Remove padding between squares in this area.
  - [x] Add 5px rounded corners.

- [x] Restyle the chart
( https://github.com/Automattic/wp-calypso/pull/70918 )
  - [x] Numbers in each box: increase size to .8rem and remove the letter spacing
  - [x] Months text: Remove the all-caps style
  - [x] Round the top left and bottom right corners of the chart.
![Screen Shot 2022-11-30 at 5 48 15 PM](https://user-images.githubusercontent.com/214813/204925848-55076334-ce48-42e3-8a2b-658a35e8a035.png)

# Design

### Details

Just making note of a few refinements to make on the insights graphs. Nothing major, just some visual polish. Breaking down each section for easier consumption.

<details><summary>Design Specifications</summary>

**Current**
![Screen Shot 2022-11-30 at 5 47 29 PM](https://user-images.githubusercontent.com/214813/204924728-4c970c1c-24d5-43c0-8ef3-7658bd1262c4.png)

**After:**
![Screen Shot 2022-11-30 at 5 48 15 PM](https://user-images.githubusercontent.com/214813/204924810-9bda577a-b9a4-40f2-b549-45dc53870566.png)

![Screen Shot 2022-11-30 at 5 48 25 PM](https://user-images.githubusercontent.com/214813/204924819-db09999c-d00d-4eb8-b00d-491ec181800a.png)
</details>

In context:
<img width="2963" alt="Insights i2 - Dotcom" src="https://user-images.githubusercontent.com/214813/204924845-c8eba623-e068-45b4-b73c-f7b428c82990.png">

### Checklist

- [ ] Overall page: When ready, the layout of most areas should be broken out of the bordered cards, just like we've done with the Traffic page!

<details><summary>Migrated to Development section</summary>

- [x] ~Enlarge title / change font to match headlines on Traffic page.~
- [x] ~Align segmented control to the right for large screen, center below the title on mobile.~
- [x] ~Use the same color and styles of the segmented control on the Traffic page above the graph. (Days, Weeks, Months, Years)~
- [x] ~Numbers in each box: increase size to .8rem and remove the letter spacing~
- [x] ~Months text: Remove the all-caps style~
- [x] ~Fewer / More post legend should be centered and enlarged. Please remove padding between squares in this area and add 5px rounded corners as shown in the mock!~
- [x] ~Round the top left and bottom right corners of the chart, as seen below...~

 
![Screen Shot 2022-11-30 at 5 48 15 PM](https://user-images.githubusercontent.com/214813/204925848-55076334-ce48-42e3-8a2b-658a35e8a035.png)

</details>

cc @keoshi

**Comment by jsnmoon** [comment]
@dognose24, this issue could use an update 🙏

**Comment by jsnmoon** [comment]
@dognose24: Closing the issue as complete 👍
