### ISSUE TITLE
Plans: enable a logged-out view of /plans

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7061]
As discussed internally, we often give out the `/plans` link to people to give them more information about our plans, but it requires a redirect if you're logged out, and it's pretty much useless if you don't have an account.

It would be great if we could serve the `/plans` content for logged-out users who are going straight to `wordpress.com/plans` (and _not_ `wordpress.com/plans/:site`), maybe with the same or similar treatment that we use for `wordpress.com/themes` when a user is logged-out.

**Comment by gwwar** [comment]
@retrofox note the related issue #7010

Doing this will require making the page, and any required imports SSR ready. See:
https://github.com/Automattic/wp-calypso/blob/master/docs/isomorphic-routing.md
https://github.com/Automattic/wp-calypso/blob/master/docs/server-side-rendering.md
