### ISSUE TITLE
CPT: Testimonial shows "Sharing" in sidebar

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#7062]
Reported by @alisterscott, we show Sharing in the sidebar, though Testimonials can't be Publicized (and these settings aren't shown in wp-admin). Publishing does not Publicize them though.

I'm not sure where this is special-cased or if we need to disable it for most CPTs (i.e. ones added by themes etc.).

**Comment by aduth** [comment]
Duplicate of #7072, fixed by #7089.

**Comment by aduth** [comment]
I guess technically #7072 is a duplicate of this one 😄
