### ISSUE TITLE
Unable to self cancel a domain

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/wp-calypso#70639]
### Quick summary

Users are unable to self-cancel a domain name. They are redirected to support every time when they click on the Continue button to delete the domain.
The `Need Help/Chat with us` link draws over the `Continue` button making it difficult to delete the domain.

### Steps to reproduce

1. Head to [Manage Purchases](https://wordpress.com/me/purchases).
2. Click on the Domain name you want to delete.
3. Click on Remove Domain
4. Click on the Continue Button 
5. You will be redirected to contact support.

### What you expected to happen

- Clicking on the Continue button should proceed to delete the domain. 

### What actually happened

- The `Need Help/Chat with us` link draws over the `Continue` button and opens a support window when trying to click on it.

### Context

Screenshot from the customer's site:

<img width="1253" alt="Screen Shot 2022-12-01 at 11 05 24" src="https://user-images.githubusercontent.com/49183855/205033622-fe56e437-f229-4d7e-bcc3-1bcba5611b12.png">

Testing from my test site:

https://user-images.githubusercontent.com/49183855/205033713-586fb312-f441-4702-b0db-a569ac560439.mov

Reported at 5756781-zen

[Slack discussion.](p1669888470855749-slack-C0160HSMDQV)

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

**Comment by carinapilar** [comment]
Got a user the other day with this issue, on 38260118-hc, they mentioned the exact same thing:

> There are the words "need help" and they bleed over on the 'Continue' button and that was the problem

They managed to cancel the domain at some point.

**Comment by marutim** [comment]
Another user in the chat can not cancel the domain with the same issue.

38400587-hc

**Comment by sguzovskaia** [comment]
Another possible case: 38465044-hc, though cannot tell what happens after they click on Remove domain and there's a big language barrier.

**Comment by ariel-maidana** [comment]
Another report here: 5769578-zd-woothemes
Clicking on "Remove domain" doesn't do anything.

**Comment by tellisbethel** [comment]
Another case here: 38587840-hc

Clicking the very edge of the button seemed to send the request through, but even though the domain was noted as having been removed, the subscription still remains in the user's subscription page and in SA. That might be a second, and totally unrelated issue however.

**Comment by aneeshd16** [comment]
Hi, this issue has been fixed via https://github.com/Automattic/wp-calypso/pull/71448
The chat button should render correctly now:
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/5436027/209273377-dc483d66-8f11-4488-b87c-c1178a43bd03.png">
