### ISSUE TITLE
[Bug]: The public private state update of calypso can get into a state of limbo

### ISSUE THREAD

**Issue by ddc22** [Automattic/wp-calypso#70642]
### Quick summary

Context found in a support ticket : https://github.com/Automattic/wp-calypso/pull/47399/files#r1036974115

### Steps to reproduce

Not sure

### What you expected to happen

To the public section to work properly

### What actually happened

A state of broken radio options where no option is properly selectable

### Reproducibility

Once

### Severity

One

### Workaround details

I was assuming that just launching the site for the homepage might work. But this form remains broken.

**Comment by jartes** [comment]
Closing, as the issue was due to a broken Jetpack connection on the Atomic Site.
