### ISSUE TITLE
NUX checkout step: add plan cart component

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7064]
Part of #6957. Create a component which displays the plan user selected along with other things in NUX flow. Put this component to devdocs so we can see how it behaves.
### Initial design (might change):

![selection_079](https://cloud.githubusercontent.com/assets/4988512/17171703/1eb80c94-53f2-11e6-81b9-d6967d53b864.png)
### Plan cart with credit card checkout form in NUX flow:

![](https://cloud.githubusercontent.com/assets/1464705/17065578/7393c11c-4ff7-11e6-9b82-3f58d91305ec.png)

Try to reuse as much as possible such as `CartItems`, `CartTotal` and `CartCoupon` so we don't reinvent wheel here.

**Comment by folletto** [comment]
Highlighting [my comment](https://github.com/Automattic/wp-calypso/issues/6957#issuecomment-234921035) from the other thread for reference:

> (1) I'd try to keep the same Plan header on the selection and payment steps, and avoid "Cart". Cart is a construct that is useful in some online shopping, but for us, and especially in this scenario, doesn't add any valuable information to the user. I'd just show: Plan header, extra stuff, total.

**Comment by alisterscott** [comment]
There hasn't been any activity on this issue in nearly a year and the NUX process has changed quite a lot in that time. I will close this issue for now as it's been low priority for that time, we can re-open should this be considered important to tackle at some point.
