### ISSUE TITLE
NUX checkout step: refactor/redesign PayPal payment box

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7066]
Part of #6957. Refactor/redesign the PayPal payment box component.
### Initial design (might change):

We don't have mockups for the PayPal payment box yet. However, it should look the same as credit card payment box except with different fields. Here's how:

Credit card payment box:

![selection_080](https://cloud.githubusercontent.com/assets/4988512/17172054/b1355710-53f3-11e6-8f63-376ef29f6853.png)

Current PayPal payment box:

![selection_082](https://cloud.githubusercontent.com/assets/4988512/17172317/c8c3ae6c-53f4-11e6-86ef-796b7b269444.png)
### Credit card payment box with plan cart and pay btn in NUX flow (substitute the CC payment box with PayPal payment box):

![](https://cloud.githubusercontent.com/assets/1464705/17065578/7393c11c-4ff7-11e6-9b82-3f58d91305ec.png)

**Comment by alisterscott** [comment]
There hasn't been any activity on this issue in nearly a year and the NUX process has changed quite a lot in that time. I will close this issue for now as it's been low priority for that time, we can re-open should this be considered important to tackle at some point.
