### ISSUE TITLE
Stats: Build Latest Post into Insights page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#70665]
If a site has posts, we want to build a visually appealing area that displays the site's latest post (this is any latest post, not tied to any specific author).

**Notes**

- This replaces the current "Latest post summary" card
- In the event the latest post IS ALSO the most popular, only one card should display at full width and take the "most popular"headline
- Mobile version should include a dotPager component
- This should be built in conjunction with the "Most popular post" card seen here...

![image](https://user-images.githubusercontent.com/4044428/205762580-ed83a4ba-c610-4308-a438-12c76aae1cc3.png)

|Before|After|
|-|-|
|![Screen Shot 2022-12-01 at 5 23 09 PM](https://user-images.githubusercontent.com/214813/205171831-8ccd209f-6fc2-45fc-94f8-634a5b5ddf86.png)|<img width="685" alt="image" src="https://user-images.githubusercontent.com/4044428/205762427-e3c2764d-64f5-4fda-b21b-21e03a2edde7.png">|

|Before|After|
|-|-|
|![Image](https://user-images.githubusercontent.com/214813/205151752-e828e744-a2d9-4020-8a8e-e1c24253c4ef.png)|![Image](https://user-images.githubusercontent.com/214813/205151539-ddd7e57b-45fc-4c99-ab37-ab95fc4a5c37.png)|

**Specs:**

![Image](https://user-images.githubusercontent.com/214813/205165791-fa1984ff-3d8d-4e93-8a75-00a48e81ade1.png)
![Image](https://user-images.githubusercontent.com/214813/205172786-9a56502d-140a-4580-a8a8-8a592ca8ecfd.png)

cc @keoshi

**Comment by jsnmoon** [comment]
Replaced by #70854.
