### ISSUE TITLE
Estimating Reading Time Enhancement 

### ISSUE THREAD

**Issue by freelylovinglife** [Automattic/wp-calypso#70678]
### What

User states that they saw an option in the past that displayed estimated reading time within a page edit.  Providing a screenshot with a section circled showing where they want this info displayed. 

<img width="2048" alt="Screen-Shot-2022-12-01-at-4 50 31-PM" src="https://user-images.githubusercontent.com/76487565/205205189-f8b7490a-e704-4ca3-babe-dbacccc42434.png">

### Why

A feature to help user to determine what kind of experience their site visitors have and how long it would take a visitor to read a post or page.

**Comment by zachspears** [comment]
I think this would be great, especially as we add more writing support functionality. Marking low due to low impact.

**Comment by zdenys** [comment]
I think it makes sense to close the above in favor of the below one which has more reports and is a duplicate:

- https://github.com/Automattic/wp-calypso/issues/70094

**Comment by zachspears** [comment]
Hey, @zdenys, thanks for the suggestion. I am going to go ahead and close this ticket in favor of the one you have shared.
