### ISSUE TITLE
Pattern Assembler - Identify and fix patterns with preview issues on mobile

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#70679]
We'll work on the UI for mobile in the next iterations. In this issue, I'd like to identify the patterns that could need design work to adjust them for mobile.

Most of the section patterns and some headers and footers have an issue with the horizontal padding. 

**[Simple Header with Dark Background](https://dotcompatterns.wordpress.com/2022/07/26/simple-header-with-dark-background/)**
https://dotcompatterns.wordpress.com/?p=5593

How it should look
![Image](https://user-images.githubusercontent.com/1881481/205203753-824e478e-23d3-4f36-ad06-15bd63948ecc.png)

How it looks in the PA
![Image](https://user-images.githubusercontent.com/1881481/205203754-5ca2369d-894f-43c4-95d1-40ce7b70212c.png)

**[Simple Header with Tagline](https://dotcompatterns.wordpress.com/2022/07/26/simple-header-with-tagline/)**
https://dotcompatterns.wordpress.com/?p=5601

How it should look
![Image](https://user-images.githubusercontent.com/1881481/205204919-65b367da-5cdc-44c1-b3c4-6ea8f96ed518.png)

How it looks in the PA
![Image](https://user-images.githubusercontent.com/1881481/205204954-bb67b540-cc78-4b44-842c-03c676dc51de.png)

**[Header with Site Title and Menu Button](https://dotcompatterns.wordpress.com/2022/07/26/header-with-site-title-and-menu-button/)**
https://dotcompatterns.wordpress.com/?p=5603

How it should look (To achieve this look, I removed the class `alignfull`)
![Image](https://user-images.githubusercontent.com/1881481/205206246-aae9c3fb-81d9-4e51-84eb-2403de0d7530.png)

How it looks
![Image](https://user-images.githubusercontent.com/1881481/205206002-caf22886-804e-4a4d-a75f-30fdef182a34.png)

The issue is related to the `alignfull` class and the padding in the preview container. 
![Image](https://user-images.githubusercontent.com/1881481/205206439-a97f6087-c185-4bbb-a3bd-ae03f1725378.png)

![Image](https://user-images.githubusercontent.com/1881481/205206644-4a247864-c730-46fc-a631-a9db69b0d0cc.png)

[Header with Button](https://dotcompatterns.wordpress.com/2022/10/13/header-with-button/)
https://dotcompatterns.wordpress.com/?p=7914
The issue here seems related to the breakpoint. 

How it should look
![Image](https://user-images.githubusercontent.com/1881481/205209780-730aebe3-da2c-4a6c-abf7-3d28697974ba.png)

How it looks
![Image](https://user-images.githubusercontent.com/1881481/205209823-875bd5f4-f417-4f95-9273-275e047d30db.png)

[Footer with Social Icons, Address, E-mail, and Telephone Number](https://dotcompatterns.wordpress.com/2022/04/28/footer-with-social-icons-address-e-mail-and-telephone-number/)
https://dotcompatterns.wordpress.com/?p=5316

How it looks
<img width="514" alt="Screen Shot 2565-12-02 at 10 58 22" src="https://user-images.githubusercontent.com/1881481/205211935-c5b195f1-4095-440d-b5fa-f862b3a84546.png">

[Footer with Newsletter Subscription Form](https://dotcompatterns.wordpress.com/2022/10/11/footer-with-newsletter-subscription-form/)
https://dotcompatterns.wordpress.com/?p=7485

How it looks
<img width="520" alt="Screen Shot 2565-12-02 at 11 04 04" src="https://user-images.githubusercontent.com/1881481/205212662-7e0d48cf-31d5-4fe4-9b90-c5b4c9bf8f8e.png">

This pattern, like others, looks okay in the PA preview for mobile because the iframe for the preview has padding that fixes the pattern padding issue.
<img width="671" alt="Screen Shot 2565-12-02 at 11 04 46" src="https://user-images.githubusercontent.com/1881481/205212761-e77eb29e-eb1b-441e-be0e-600f35ff286a.png">

 I don't think this solution was done intentionally as it doesn't work for all cases.

**Comment by autumnfjeld** [comment]
We need to do mobile analysis to understand the priority of mobile things: 1) how many peeps go thru onboarding mobile 2) launch rates on mobile.
Autumn will make issue for this metrics analysis.

**Comment by miksansegundo** [comment]
This issue aims to identify the Dotcom patterns that are not designed for mobile devices so we can fix them.

I'm moving it to `ready-for-dev/designer` because these patterns degrade the user experience not only on the assembler but on Wordpress.com, and the global Internet as well. 

Ideally, all patterns in our library should be designed for desktop, tablet, and mobile viewports using a responsive design. 


### A Curated And Ready-to-use Pattern Library

We could be testing them on all viewports before we add them to the Dotcom patterns library to address responsive design issues before they are offered to users in the Dotcom patterns library.

See an example on the Mobile preview on the editor:

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/8d38d6eb-507a-442e-94b3-b60450faece5)


The same example on the assembler:

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/d283649b-ad2b-4211-b40f-11ba0dde77cd)


Again, this issue is not about using the assembler (or the onboarding flows) on a mobile device but about making patterns readable/visible for the final users of Wordpress.com websites.


### Global Internet Analytics

Sharing a quick [reference](https://gs.statcounter.com/screen-resolution-stats) that says that the **mobile viewport 360x800** has been between the **Top 2 and Top 3** positions in **Worldwide stats** during the past 12-month period. 

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/5a12b0b2-a055-401e-89bc-24cef5c9466b)

cc: @taipeicoder @autumnfjeld @alaczek 😇

**Comment by miksansegundo** [comment]
Check out this comment on the Dotorg post [Advancing the power of patterns](https://make.wordpress.org/core/2023/07/13/core-editor-improvement-advancing-the-power-of-patterns/) about the Pattern directory:

> The new pattern are looking great on big screens. But as soon as the preview is changed to “narrow” inside the pattern directory 12 out of 14 new core pattern break there layout – leading to ugly views and horizontal scrollbars. Even the medium preview lets some of them struggle.
Example:
https://cloudup.com/ifmb5BQ60hs

> I think the featured patterns on .org should be a role model to show off the power of WP/blocks. In times of 65% mobile traffic (similarweb) the patterns in there current state are not great examples. To me it says something like “core doesn’t care about the majority of users (with small screens)” if the core curated pattern are this kind of bad examples.

**Comment by miksansegundo** [comment]
All the curated patterns can be tested in https://dotcompatterns.wordpress.com/assembler-in-template/

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/d1546dfb-e1c6-4b16-b849-575f97fb826b)


They are looking good, not great, after I fixed some patterns that were not looking good. Here are some examples:

|BEFORE|AFTER|
|--|--|
|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/631afd79-5a86-48c5-8db4-3ae4eb75e16b)|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/b8e3be13-5adb-4674-97c7-a59e95d0b1ca)|

|BEFORE|AFTER|
|--|--|
|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/68d03912-24fb-4648-bff7-dae3cae51843)|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/d7f2753a-c86d-4997-81bc-d1960939893e)|


|BEFORE|AFTER|
|--|--|
|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/308e2773-45d6-4a54-8832-be7f3962f448)|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/50cfdd2c-c4f2-46ae-9906-b5fe7cdbeb79)|


Some patterns could still be improved but the editor lacks responsive features to control the spacing and alignment of blocks depending on the viewport.

**Comment by autumnfjeld** [comment]
Very nice @miksansegundo !!   💟
