### ISSUE TITLE
Stats: Build Most Popular Post into Insights page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#70670]
If a site has posts, we want to build a visually appealing area that displays the site's most popular post (this is any most popular post, not tied to any specific author).

**Notes**

- In the event the latest post IS ALSO the most popular, only one card should display at full width and take the "most popular"headline
- Mobile version should include a dotPager component
- This should be built in conjunction with the "Latest post" card seen here...

![Image](https://user-images.githubusercontent.com/214813/205169248-05169e89-bd3c-4d77-a641-da1d08ffde9c.png)

|Before|After|
|-|-|
|![Image](https://user-images.githubusercontent.com/214813/205168959-456b8aac-c74a-4704-bf79-235564b4ad29.png)|![Image](https://user-images.githubusercontent.com/214813/205169177-21be4ed9-ef25-440b-bc16-2c53f0fb5c29.png)|

**Dev specs**

![Image](https://user-images.githubusercontent.com/214813/205172983-f81a4da3-3c75-45cf-ad6f-82936ccfa1d1.png)

cc @keoshi

**Comment by jsnmoon** [comment]
Replaced by #70854.
