### ISSUE TITLE
Pattern Assembler - Review translations

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#70685]
The translations in Spanish need some adjustments, and probably other languages too.

**For MVP**
For instance, `Add sections` is wrongly translated in Spanish as `Agregas secciones:`. 

This can be a blocker. @autumnfjeld 

- [X] Fixed the translation for `Add sections` in spanish
- [x] [Preview placeholder translation ](https://github.com/Automattic/wp-calypso/pull/70694)

**For v2**
In this [PR](https://github.com/Automattic/wp-calypso/pull/70632) we use the categories as pattern names, and the categories `Numbers` and `Call to action` are still not translated in Spanish.

![Image](https://user-images.githubusercontent.com/1881481/205220878-b2263cff-000e-40b9-91a6-c59812b1cedc.png)

**Comment by autumnfjeld** [comment]
@Miguel can you work with someone on Team Global about this? 

This will **not** block launch, but I do think it would be good to get a sanity check if you think translations have gone wrong.

See prior thoughts on pattern names & translations: p1661941751392109/1661141810.155589-slack-CRWCHQGUB
