### ISSUE TITLE
NUX checkout step: add payment status notification to Create your Account step

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7069]
Part of #6957. Add a payment status (either "Payment successful" or not successful) to the Create your Account step (`signup/steps/user`). This notification has to be probably coordinated with the pay button from #7067 as it needs to get the payment status info from somewhere (either successful credit card payment or PayPal payment).
### Initial design (might change):

![selection_084](https://cloud.githubusercontent.com/assets/4988512/17173080/eb4b158e-53f8-11e6-8616-da75c03e91d2.png)

**Comment by alisterscott** [comment]
There hasn't been any activity on this issue in nearly a year and the NUX process has changed quite a lot in that time. I will close this issue for now as it's been low priority for that time, we can re-open should this be considered important to tackle at some point.
