### ISSUE TITLE
NUX checkout step: add NUX checkout step

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7070]
Part of #6957. Add a new checkout step to NUX so that it's actually part of the NUX flow and not a completely standalone checkout process as it's now. It should be right after the selection of a plan, and allow the user to go back and change their selection.
### Initial design (might change):

![](https://cloud.githubusercontent.com/assets/1464705/17065578/7393c11c-4ff7-11e6-9b82-3f58d91305ec.png)
### Implementation details

Put together components from #7067, #7066, #7065 and #7064 so that they align properly as shown on the picture above. Also add the ToS text and "or use PayPal" link. Put this all behind a feature flag `nux/checkout-step` (or some other name).

**Comment by alisterscott** [comment]
There hasn't been any activity on this issue in nearly a year and the NUX process has changed quite a lot in that time. I will close this issue for now as it's been low priority for that time, we can re-open should this be considered important to tackle at some point.
