### ISSUE TITLE
Feature Request: auto-tagging live chats coming from the cancelation flow

### ISSUE THREAD

**Issue by paulbonahora** [Automattic/wp-calypso#70702]
### What

As per [this request](https://a8c.slack.com/archives/C03TDMUSUSG/p1669948444778949) we'd like to auto-tag chats live chat requests that will come from the cancelation survey. 

For further context, last week we [shipped an improvement](https://dotcomretention.wordpress.com/2022/11/25/improvements-to-the-cancelation-survey-providing-solutions-to-cancelation-reasons/) to the cancelation survey where we surface solutions based on the options chosen. There are specific instances chosen ([highlighted on the post](https://dotcomretention.wordpress.com/2022/11/25/improvements-to-the-cancelation-survey-providing-solutions-to-cancelation-reasons/#before-after)) that lead to a live chat interaction. These interactions should be automatically tagged with `cancelation_chat_prompt`.

### Why

Happiness requires to measure eventual additional chat load to plan staffing accordingly. We're surfacing the option to chat with someone since users are actively intending to churn at this particular step and it is our last chance to help them change their minds.

### How

Interactions coming specifically from the cancelation survey should just be auto-tagged with `cancelation_chat_prompt`.

**Comment by Robertght** [comment]
Closing this as per p8wKgj-7bC-p2
