### ISSUE TITLE
Virtual Homepage: Clarify in the tooltip that only admins can edit the homepage

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#70727]
### Description

We previously updated the tooltip in #70466.

Now, in addition to that, as only admins can edit the homepage template, we want to also clarify in the tooltip that only admins can edit the homepage. 

Here is my proposed copy:

| Administrators | Non-administrators|
|-|-|
|  <img width="400" alt="image" src="https://user-images.githubusercontent.com/1525580/205430629-9a9a9cb2-2b3d-47ce-b16d-e261422967c7.png"> | <img width="400" alt="image" src="https://user-images.githubusercontent.com/1525580/205430681-3f9d5de1-9ce3-421b-bcb9-a66996777d6e.png"> |

@SaxonF: What do you think of the copy? I only changed `You` to `Administrators`.

@Automattic/ganon

**Comment by SaxonF** [comment]
@fushar nice and simple 👍

**Comment by autumnfjeld** [comment]
Please see this comment on correcting some awkward phrasing with  "Showing the .....".
  https://github.com/Automattic/wp-calypso/issues/70466#issuecomment-1338480083

**Comment by bangank36** [comment]
> Please see this comment on correcting some awkward phrasing with "Showing the .....".
> [#70466 (comment)](https://github.com/Automattic/wp-calypso/issues/70466#issuecomment-1338480083)

I included in the [latest commit ](https://github.com/Automattic/wp-calypso/pull/70747/commits/85f5c2b1f0329b6d1a23321b0e5b456e272e192b)
cc: @fushar 

| Administrators | Non-administrators|
|-|-|
|  <img width="400" alt="image" src="https://user-images.githubusercontent.com/10071857/205806738-e98144db-76b9-466d-be6f-36920cdc473b.png"> | <img width="400" alt="image" src="https://user-images.githubusercontent.com/10071857/205806832-45adfd12-58b1-4cbe-a048-98bec87344c4.png"> |

**Comment by bangank36** [comment]
Given the fact the the tooltip's copy still require the template title, we will update it as below 

**Non-administrators:** Administrators can change the content of this page using the Site Editor

cc: @SaxonF @fushar

**Comment by bangank36** [comment]
Closed as landed
