### ISSUE TITLE
CPT / Editor: Display Sharing services only when post or type supports Publicize

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7072]
Originally reported by @alisterscott at https://github.com/Automattic/wp-calypso/pull/7053#issuecomment-235462206

We should only display the "Sharing" accordion settings services listing in the post editor if one of the following two conditions is met:

- The post type is "post"
- The [REST API post type object](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/post-types/) `postType.supports.publicize` is `true`

([Reference](https://github.com/Automattic/jetpack/blob/807039b/modules/publicize/publicize.php#L419-L433))

**Comment by kriskarkoski** [comment]
The Sharing section also includes the options to show/hide the sharing buttons and Like buttons.

<img width="257" alt="screen shot 2016-07-27 at 10 18 49 am" src="https://cloud.githubusercontent.com/assets/1900444/17178491/a8243444-53e3-11e6-9ed2-013b25bd4b4b.png">

Hiding the whole Sharing accordion would make those settings unavailable to be adjusted for CPTs. I confirmed these settings are shown in WP Admin.

**Comment by aduth** [comment]
@kriskarkoski : Good call. We should just control the display of the Publicize service options then. Updated title and content accordingly.
