### ISSUE TITLE
Virtual Homepage: Disallow editing for non-Administrators

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#70726]
### Description

Non-administrators are not allowed to edit templates. Therefore, for all users who are not Administrator:

- [x] Change the virtual homepage link from the Site Editor to the live site homepage URL (e.g. {siteSlug}.wordpress.com})

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1525580/205430368-01049b72-e5c1-4cf8-bf41-86ad93e8e233.png">

- [x] Hide the `Edit` menu item from the ellipsis menu

<img width="214" alt="image" src="https://user-images.githubusercontent.com/1525580/205430449-7115f7e5-6e32-4864-a27a-8e1fdfa7d7bf.png">

@Automattic/ganon

**Comment by bangank36** [comment]
Closed as landed. Thanks @arthur791004 @fushar

**Comment by fushar** [comment]
Thanks! Let's deploy tomorrow (APAC)
