### ISSUE TITLE
Setting text color adds unwanted yellow highlight when published

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/wp-calypso#70738]
### Quick summary

Text set with a text color and no background color in the editor may be formatted with `mark` tags, and display a yellow background color on the live page that doesn't appear in the editor. Where it's formatted with `span` tags, or edited to use them, that unwanted background color disappears. 

### Steps to reproduce

1. Use the block editor.
2. Type some text into the editor. Use the Highlight feature on the Paragraph block to set some text to have a different text color.
3. Publish the page or post. 

### What you expected to happen

The text should have the set color, and no background color. 

### What actually happened

The text has a yellow background color. 

### Context

Potentially linked to #57036 and all related issues, but different in where it appears.

Reported in 5764338-zd and replicated here: https://limitedepsilon.wordpress.com/hever-text-highlight-test/

In the original user report, only some instances had this effect (other instances had `span` tags around text with a different color, instead of `mark`, and did not have that background color). In my test, all of them did. I'm unsure if this is due to pasting in preformatted text from elsewhere.

Originally used Hever theme to match conditions on user site.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Tested on Hever, persists through theme change to Pixl. 

### Browser, operating system and other notes

Tested on Firefox for Mac. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Editing the HTML for each affected block and replacing `mark` with `span` removes the highlight.

**Comment by jerrysarcastic** [comment]
May also be related to https://github.com/Automattic/wp-calypso/issues/70675

**Comment by IoanaAMuresan** [comment]
Another related ticket: 5768913-zen - user would like to hear back when it's fixed.

**Comment by metabreakr** [comment]
Was able to reproduce in the Twenty Twenty Three theme in pdEkSe-1JM-p2. The workaround provided resolved the issue.

**Comment by gwensmithx** [comment]
reported here as well: #38563410-hc

**Comment by metabreakr** [comment]
Also happening with Blockbase in pdEkSe-Vd-p2 where it previously was not present on handoff.

**Comment by metabreakr** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/70675
