### ISSUE TITLE
Writing Prompts: Prompt appears when post has been copied

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#70741]
### Quick summary

A user has reported (and I have also noticed) that the Writing Prompt appears in posts even when they are being 'copied' using both the WP Admin and Calypso 'copy' fuinctionality.

I've witnessed this on a user's site, my own test site, and also on internal P2s

### Steps to reproduce

Go to your post list on any site. Click the three dots next to a post and click the 'Copy post' option.

### What you expected to happen

The Editor to load with an exact copy of the post.

### What actually happened

The copy did load - but the writing prompt appeared above. This was inconvinient at best, and confusing/concerning for users at worst.

> Again - when I view the previous post text view - the code does not exist. Only when I use Wordpress "COPY" command, does it magically appear in the "new post" editing screen created by Wordpress. Below is the code that magically appears. I SHOULD be able to use Wordpress COPY command, without ADDING a step outside the program on notepad, or WHY is there a copy command?

5764589-zd-woothemes

### Context

Customer report - 5764589-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

User's can delete the placeholder paragraph and publish the copy

**Comment by jordesign** [comment]
Screencast of issue:

https://user-images.githubusercontent.com/1842363/205540916-01bf2da7-b657-4a12-98f9-26d4b03edbcb.mov

**Comment by davemart-in** [comment]
Looks to be related to: https://github.com/Automattic/jetpack/issues/27747

**Comment by roo2** [comment]
@davemart-in nope, just similar 😅 https://github.com/Automattic/jetpack/issues/27747 is related to copying blocks from a word doc wheras this is using the calypso "copy post" function

**Comment by carinapilar** [comment]
We had a couple of other cases reported here too: p7DVsv-fOI-p2#comment-43105

**Comment by zachspears** [comment]
Able to reproduce the issue consistently and agree that it is a confusing experience. Also, an additional note when testing is to ensure that Writing Prompts are enabled under _Settings_ > _Writing_ > _Composing_ > _Show writing prompts_.

**Comment by roo2** [comment]
It looks like this is no longer an issue as we no longer show the blogging prompts as default https://github.com/Automattic/jetpack/pull/27919

**Comment by carinapilar** [comment]
> It looks like this is no longer an issue as we no longer show the blogging prompts as default

@roo2, I'm not sure I understood. The issue persists when the writing prompts are enabled.

When enabled, it's my understanding that they shouldn't show when you copy a post, since the post already has content - which it's what it's still happening.

**Comment by roo2** [comment]
ahh ok, you're right, sorry, my mistake!

**Comment by davemart-in** [comment]
Closing this out since we no longer will have writing prompts as placeholder text (based on feedback).

**Comment by carinapilar** [comment]
Hey @davemart-in! Is there an ETA for that? Shouldn't we keep this open until it's fixed, or another workflow is in place?

**Comment by davemart-in** [comment]
Hey @carinapilar! Placeholder writing prompts are no longer shown by default to everyone. You'll only see writing prompts as placeholder text if you've gone into writing settings and manually toggled the option on:

![image](https://user-images.githubusercontent.com/5634774/211858853-8cd09354-4d34-4019-95d3-8a5f62e9d26e.png)

But we are in the process of removing this toggle as well in pe7F0s-uo-p2

If it's helpful, I'm happy to keep this issue open until that toggle is removed, at which point no one should ever see a writing prompt as placeholder text again.

**Comment by carinapilar** [comment]
> Placeholder writing prompts are no longer shown by default to everyone. You'll only see writing prompts as placeholder text if you've gone into writing settings and manually toggled the option on

@davemart-in, right, I understand the toggle. I'm not sure I understood the next steps though, with the removal of the toggle, do you mean that the placeholder text won't show inside the editor anymore (it will only show in other places)?

**Comment by davemart-in** [comment]
@carinapilar that's correct. The placeholder text version of writing prompts is going away completely. The only way you will be able to show a writing prompt will be when you manually click a daily writing prompt promo like we have on My Home or in notifications (which should ship soon), in which case, you'll see the writing prompt show up in a quote block. You can read more about the v2 here: pe7F0s-uo-p2

**Comment by carinapilar** [comment]
Ah, nice, thanks for the clarification, @davemart-in!

**Comment by cuemarie** [comment]
Looks like the writing prompt has been removed completely from posts, and now appears in a Card in My Home. With that, I'll close this issue. Thanks all!
