### ISSUE TITLE
[Bug]: User on Business simple site can't activate .org theme

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#70759]
### Details

**Steps to reproduce:**

- On a business simple site
- Go to https://wordpress.com/theme/astra/{site}
- Click "Activate this design"

**Result:**

![CleanShot 2022-12-05 at 13 45 50@2x](https://user-images.githubusercontent.com/12430020/205629769-db9416ba-635e-4d6f-9ba0-b8bdfae7fdaa.png)

- Error message: Theme not yet available for this site
- Theme doesn't activate

**Expected result:**

- Notify that the site will be transferred to Atomic ( domain will change etc )
- Theme gets installed

Related: p1670191555375559/1668698905.832179-slack-CB0B2G43X

**Comment by zdenys** [comment]
5776578-zd-woothemes

**Comment by zdenys** [comment]
28120412-hc

**Comment by zdenys** [comment]
5851954-zd-woothemes

**Comment by mxhassani** [comment]
40719621-hc

**Comment by zdenys** [comment]
`6028219-zd-woothemes`

**Comment by NoHopeRadio** [comment]
40628925-hc
and
41433594-hc

**Comment by hacchism** [comment]
Another case reported: 6068576-zen

**Comment by zdenys** [comment]
6191002-zd-woothemes

**Comment by zdenys** [comment]
6194994-zd-woothemes
