### ISSUE TITLE
Themes: Keyboard shortcuts in search box

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#7075]
Initial plan, feel free to change:
- [ ] up/down cursor to cycle through suggestions
- [ ] tab (and/or enter) to select suggestion
- [ ] modifier + left/right to jump to pills and select whole pill
- [ ] backspace functions as usual

**Comment by folletto** [comment]
I feel there can be 2 approaches here:

1. Pill-as-Unit: the whole pill is considered a unit, so once it gets "activated" (with the pill design) it counts as a single character would in plain text.
2. Pill-as-Text: the pill is just some styling on text, so they still count and are treated as the individual character they are composed of, the visual styling just confirms if a specific pattern matches, but doesn't create a "unit".

**Comment by seear** [comment]
> I feel there can be 2 approaches here...

I feel (1) is more powerful. Pill becomes a unit once:
* a suggestion is clicked
* text is auto-completed
* valid filter is completely typed

Then once it is a unit, up/down will cycle it through suggestions, and backspace will eat into it, deleting the last letter and leaving 'unit' mode.

But I think we can iterate from (2) to (1).

**Comment by folletto** [comment]
> Then once it is a unit, up/down will cycle it through suggestions, and backspace will eat into it, deleting the last letter and leaving 'unit' mode.

This seems an intermediate version between the two: treated as unit for some interactions (arrows), but keeping text for others (backspace), right?

**Comment by ockham** [comment]
Closed by #8282. Let's file separate issues for future UX iterations.
