### ISSUE TITLE
Stepper eCommerce flow: remove design carousel subheader

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#70761]
In the new eCommerce flow, `/setup/ecommerce`, in the Design Carousel step, we should remove the "Don't worry, you can change or customize this at any time in the future" line.

Related to pdtkmj-LF-p2#comment-1315

![image](https://user-images.githubusercontent.com/3801502/205639584-2796cd9f-8819-4ef6-bc2a-0a23698b1e2d.png)

**Comment by sixhours** [comment]
Removed in #70782
