### ISSUE TITLE
Stepper eCommerce flow: vertical names are not localized

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#70766]
When using the eCommerce flow (`/setup/ecommerce`), in the store profiler, a verticals list is shown, but it's values are not translated to the user's language:

![image](https://user-images.githubusercontent.com/3801502/205648812-d9a52f6d-a9b7-4da3-b05c-43e0cce49e67.png)

![9sODZ1.png](https://user-images.githubusercontent.com/3801502/205648636-235b0df6-eb2b-4d8a-8fc6-9d97395dbab2.png)

Related to pdtkmj-LF-p2#comment-1357

**Comment by blackjackkent** [comment]
Resolved by #70934
