### ISSUE TITLE
Stepper eCommerce flow: check Design Carousel images resolution

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#70764]
We should make sure that the images/previews used in the Design Carousel - that can be seen in the eCommerce flow `/setup/ecommerce` - have a reasonable resolution, so they don't get pixelated.

Related to pdtkmj-LF-p2#comment-1368

**Comment by sixhours** [comment]
It looks like the current previews are set to 1280px wide. If given enough screen space, the carousel will stretch the previews larger than that, causing them to look pixelated. This screenshot was taken with my browser at ~1500px tall, giving each screenshot a width of 1386px:

<img width="1437" alt="Screen Shot 2022-12-05 at 1 55 42 PM" src="https://user-images.githubusercontent.com/2124984/205719820-bd2a9b02-938c-4073-b651-3a11365bc0fc.png">

The images seem to look best at large screen sizes when set to match the viewport width of 1920px, but that makes for a pretty big file size.

Same screenshot at 1920px wide, much less blurry:

<img width="1425" alt="Screen Shot 2022-12-05 at 2 02 59 PM" src="https://user-images.githubusercontent.com/2124984/205721240-6b431f81-04c7-4e6a-aefc-468dcd5539da.png">

**Comment by sixhours** [comment]
Fixed in #70786
