### ISSUE TITLE
Help Center: Hide Internal Shortcodes

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#70768]
### Quick summary

Some support articles show contextual prompts to upgrade. When viewed through the Help Center, the full shortcode is visible to the user, but the shortcode should not be user-facing.

### Steps to reproduce

1. Open the help center
2. Seach for "connect"
3. Click on the doc titled "Connect a domain"
4. View the shortcode at the bottom of the first section - "Domain Connection Overview"

### What you expected to happen

I expected the 'Upgrade Plan' button to be shown if my account does not have a paid plan. I expected the button to be hidden if my account has a paid plan. I expected to not see a shortcode in either case.

### What actually happened

I see this shortcode:
![image-7](https://user-images.githubusercontent.com/30727666/205652385-f9d5fe26-e24e-4b92-ac1f-137d67b1662e.png)

### Context

pdDR7T-l0-p2#comment-341

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by heavyweight** [comment]
Fixed with D99647-code
