### ISSUE TITLE
Stepper eCommerce flow: fix redirection in the end of the flow

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#70815]
When using the eCommerce flow (`/setup/ecommerce`), I'm being redirected to the CrowdSignal page (`/wp-admin/options-general.php?page=crowdsignal-settings`) in the end of it, instead of the WooCommerce page.

What I'm getting:
![image](https://user-images.githubusercontent.com/3801502/205908202-23b7cab3-0257-470f-8d54-e426af573bdc.png)

What I should get:
![image](https://user-images.githubusercontent.com/3801502/205908370-10afd5da-aeaa-42fd-a984-dab45543bb82.png)

**Comment by sixhours** [comment]
I went through the flow many times in different environments and browsers with different configurations and haven't been able to reproduce this again (although I have seen it in the past). I suspect this will be a difficult bug to squash.

**Comment by nelsonec87** [comment]
Closing this as we can't reproduce it anymore

**Comment by mreishus** [comment]
I do see this occasionally, but I'm not sure why.
