### ISSUE TITLE
[Bug]: Hovering over style variation in onboarding is janky in Firefox

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#70818]
### Quick summary

When choosing a style variation during onboarding, the animation when hovering over a style variation is janky in Firefox, flashing scrollbars for a split second. Chrome is fine

### Steps to reproduce

 1. Create a new site
 2. Choose a plan (free is fine)
 3. On the 'Pick a design' step, click a theme that has variations (little colourful circles beneath the preview)
 4. Hover the mouse over the preview

### What you expected to happen

A smooth animation to change the text from 'Aa' to the name of the variation.

https://user-images.githubusercontent.com/93301/205918177-1428ea8d-fdfa-4cde-aa91-752e8ef7fb85.mp4

### What actually happened

A janky animation briefly showing scrollbars as the text changes from 'Aa' to the name of the variation

https://user-images.githubusercontent.com/93301/205909351-7dcdb3e7-bdad-4379-a10e-8c9c82a2b8cb.mp4

### Browser

Mozilla Firefox

### Context

Found while testing https://github.com/Automattic/wp-calypso/pull/70775

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

Yes, easy to implement

### Workaround details

Don't use firefox, or just shrug and ignore it.

**Comment by dsas** [comment]
@Automattic/ganon maybe one for you?

**Comment by fushar** [comment]
Thanks for reporting. I find that this issue also happens in the Site Editor (Gutenberg). We are using the same Global Styles code from Gutenberg in onboarding, so this is not Calypso's issue.

I opened an issue there with more details: https://github.com/WordPress/gutenberg/issues/46506. Please chime in if you want to add more details!

**Comment by fushar** [comment]
Adding this to our Lego maintenance board. According to https://github.com/WordPress/gutenberg/issues/46506, this is fixed upstream in 14.8. Let's try to see if we need to port anything to our onboarding design picker component.

**Comment by fushar** [comment]
I've confirmed that the issue is fixed when we open the Global Styles tab in the Site Editor on dotcom.

Now we somehow need to port the changes to the onboarding Design Picker 😄

**Comment by taipeicoder** [comment]
I can't seem to reproduce this issue anymore. So it might have been fixed somewhere along #73634. Let's reopen a new task if the issue pops up again 🙂
