### ISSUE TITLE
General Onboarding - Try adding a LaunchPad at the end.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#70825]
Related to discussion in the last Cylon team meeting - paYE8P-2iv-p2 / paYE8P-2iv-p2#comment-1905

Lets try adding a launchpad to the end of the general onboarding flow. Most simply by adding it in as the last step of the flow, (or maybe just enabling will cover those other onboarding cases that land users in the editor or something else - so they are directed to the launchpad just after finishing there). The content/steps of the launchpad can be the same as that of the 'free flow's launchpad design -  p9Jlb4-5ST-p2 

Lets keep this change behind a PR or feature flag, and use it as a walkthrough, discussion point, and analysis of what else we may need to do to make the launchpad work here.

**Comment by edanzer** [comment]
Just following up to mark this as complete now that Launchpad in general onboarding is released. The original PR deploying this was https://github.com/Automattic/wp-calypso/pull/72677, but other work has been done since then.
