### ISSUE TITLE
[Bug]: Upgrade plan step text in launchpad can be misleading

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#70822]
### Quick summary

When signing up for a site, in some limited circumstances you can come back into the launchpad to read text saying:

> Upgrade your plan to publish your color changes and unlock tons of other features

The text is activated by use of global styles but it doesn't check how global styles has been used - it assumes that it's due to a colour change as that's the most likely path (due to accent colours on newsletter flow).

### Steps to reproduce

1. Go to wordpress.com/setup/link-in-bio
2. Choose a free plan when prompted
3. Keep going through the steps until the 'Add links' step, which puts you in the site editor.
4. Add the `wpcom-limit-global-styles` sticker to your site
5. Refresh the site editor
6. You're in the site editor, feel free to add links but mainly, use the styles sidebar to tweak the custom styles, e.g. change a font, but do not change colours
7. Save your changes, note the warning about global styles when saving
8. Press back, you should end up back in the launchpad.

### What you expected to happen

The launchpad should say something like "Upgrade to a premium plan to publish your style changes and unlock tons of other features"

### What actually happened

Launchpad says "Upgrade your plan to publish your color changes and unlock tons of other features", even though no colours have been changed in the making of this site.

![image](https://user-images.githubusercontent.com/93301/205936750-61197302-c6ef-4627-be9b-74cf760b6e5f.png)

### Context

Noticed while developing https://github.com/Automattic/dotcom-forge/issues/1227

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

No but the platform is still usable

### Workaround details

It's just confusing wording

**Comment by Copons** [comment]
Thanks Dean, added to our board, with lower priority (not sure why GH-actions added `[Pri] High`?) as it's fundamentally a edge case.
I'll mention this during the next design walkthrough.

**Comment by SaxonF** [comment]
"style changes" vs "color changes" makes sense to me

**Comment by dsas** [comment]
It was pointed out in the pekYwv-OA-p2 (around 47 minute) the wording / presentation should be much more celebratory and not look like a warning - better wording but something more like "You have customized your site styles it's looking good, you need to upgrade for it to be used".

"It's a terrible UI, it looks like an alarm, we should celebrate and make people want to pay...The application isn't ideal but the intent is good, it gives you reassurance so you know what will happen next"

**Comment by dsas** [comment]
See also https://github.com/Automattic/wp-calypso/issues/75728

**Comment by dsas** [comment]
Obsoleted by https://github.com/Automattic/dotcom-forge/issues/2262
