### ISSUE TITLE
NUX checkout step: redesign CartItem

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7082]
Part of #6957. Redesign `CartItem` component according to @apeatling mockups:

![selection_085](https://cloud.githubusercontent.com/assets/4988512/17184110/df36eb06-542a-11e6-975c-873e3b65bd71.png)

**Comment by alisterscott** [comment]
There hasn't been any activity on this issue in nearly a year and the NUX process has changed quite a lot in that time. I will close this issue for now as it's been low priority for that time, we can re-open should this be considered important to tackle at some point.
