### ISSUE TITLE
Blaze: Replace banners at /stats and /marketing/traffic

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#70835]
Project: PT: ~~Promoted Posts~~ Blaze – Increase engagement and profit MVP: pb5gDS-2fR-p2
More context here: p1670523152840609-slack-CKZHG0QCR

We want to replace the current banner on [/stats page](https://wordpress.com/stats), with a banner for ~~Promoted Posts~~ Blaze feature:

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/1044309/205913939-0fd89b6d-dd6a-4fe6-bd93-a998577a6ace.png">

Also, replace the Yoast banner [at /marketing/traffic](https://wordpress.com/marketing/traffic):

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/1044309/205915022-21c76f6f-74fd-4625-a3f9-392eed69b81b.png">

### Replacement content

Here is the new content. 
Figma here, under Design: pb5gDS-2fR-p2

![image](https://user-images.githubusercontent.com/1044309/207451519-fc4e6568-ae72-43ed-8cc0-380dc0551693.png)

### Requirements

- [x] Create the new banner with a dotcom design team member
- [x] [Replace the banners at /stats page](https://github.com/Automattic/wp-calypso/pull/71286)
- [x] [Replace the banners at /marketing/traffic page](https://github.com/Automattic/wp-calypso/pull/71276)
- [x] Make sure clicks are registered on Tracks
- [x] CTA will redirect the user to `https://wordpress.com/advertising/{blog-domain}`
- [ ] ~~Make sure we translate the text and the `$5` currency.~~
- [x] Banners should appear on Simple | Atomic | Jetpack connected sites.

**Comment by paulopmt1** [comment]
Should we use [the current /advertising](https://wordpress.com/advertising) banner as a reference?

<img width="954" alt="image" src="https://user-images.githubusercontent.com/1044309/205916157-1ba7c8c6-61b9-4c31-8452-b1e89c86b129.png">

**Comment by that-mike-bal** [comment]
I just want to specify - we did have a card on this page https://wordpress.com/marketing/tools that will need updated. It's not currently showing but it's Marketing > Tools vs Marketing > Traffic 

You can work with dotcom martech to get it updated and live per this thread: https://martechp2.wordpress.com/2022/09/20/request-add-promoted-posts-card-to-marketing-tools/

**Comment by DustyReagan** [comment]
Just double checking. We DO want these banners showing on Jetpack sites?

**Comment by paulopmt1** [comment]
> Just double checking. We DO want these banners showing on Jetpack sites?

Yeah, I also see a good opportunity to use Blaze on these sites. As we don't officially support Blaze on those sites, I asked if we can use it (because it already works): p1671455569930669/1671219222.327439-slack-CKZHG0QCR

**Comment by paulopmt1** [comment]
Thanks @DustyReagan! Merged and closing it.
