### ISSUE TITLE
Stats: Adjust link styling for clickable headers

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#70849]
- [ ] Apply the animated link indicator on the annual highlights section on the Insights page.

![Image](https://user-images.githubusercontent.com/4044428/206013867-68cfe34e-330a-45bc-a8c4-0f2b0504a846.png)

- [ ] Apply the animated link indicator on the stats modules on the Traffic page.

![Image](https://user-images.githubusercontent.com/4044428/206013895-bcd38650-894c-43d9-a298-4278ec5cf6a1.png)

**Comment by grzegorz-cp** [comment]
Based on the discussions in https://github.com/Automattic/wp-calypso/pull/70857 the scope of the ticket changed to:
- add a sentence in the highlights component
- remove links from titles in the cards with horizontal bars
- add `view details` in case `view all` is not visible and place the link at the bottom of the card

**Comment by grzegorz-cp** [comment]
Additional designs:
![Image](https://user-images.githubusercontent.com/112354940/206589954-df759698-c02c-49fb-b4c3-a2126b304ebd.png)


![Image](https://user-images.githubusercontent.com/112354940/206590347-252ac84f-375e-46c8-a059-bc8654d256c0.png)
