### ISSUE TITLE
Free Flow: Add Tracks Events

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#70845]
### Details

We need to add any appropriate tracks events to the Free Flow. While there are an array of tasks we need to add, we want to be extra sure that the calypso_signup_start and calypso_signup_complete events are firing as expected, as those are used in high level analytics and analysis for our onboarding flows. See this slack thread for details: p1669742224639489-slack-C4BJFJVPF

While working on this, we should keep an eye out for the possibility of ensuring these tracks events work across all tailored flows (ie, we may be able to resolve the tracks events for free flow in a way that resolves it for all tailored flows, current and future).

**Comment by Addison-Stavlo** [comment]
Another related issue - https://github.com/Automattic/wp-calypso/issues/70883 - for ensuring those noted events are working correctly for previous TUC flows as well.

It seems like we arent making any new interfaces here, so shouldn't have a lot to add for tracks. But as noted the `calypso_signup_start` and `*_complete` are important to ensure are working correctly here.

**Comment by edanzer** [comment]
This has been done now. Going to close this task - feel free to re-open if something is missing. 

See the following PRs.
Signup start: https://github.com/Automattic/wp-calypso/pull/72252
Signup start for newsletters adjustment:  https://github.com/Automattic/wp-calypso/pull/73781
Signup complete: https://github.com/Automattic/wp-calypso/pull/72309
