### ISSUE TITLE
Separate checkout code from upgrades section

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7085]
Part of #6957. In p1469640617001345-slack-plans-focus, @mtias suggested to separate the checkout code form the "upgrades" section. "Right now it’s bundled with domains, etc, as the same chunk of code, so it weights over 1MB".

Split `/domains` and `/checkout` [here](https://github.com/Automattic/wp-calypso/blob/master/client/wordpress-com.js#L162) to two separate sections.

**Comment by alisterscott** [comment]
There hasn't been any activity on this issue in nearly a year and the NUX process has changed quite a lot in that time. I will close this issue for now as it's been low priority for that time, we can re-open should this be considered important to tackle at some point.
