### ISSUE TITLE
Stats: Create a post stats card component

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#70852]
# Development

Create a PostStatsCard component that does the following:
- [x] Accept a `title`, `heading`, or a `header` property.
- [x] Show the post title.
- [x] Show the post views, likes, and comments with number truncation.
- [x] Show a representative image of the post if available. If not, expand the existing content horizontally to take up the entire card width.
- [x] Make the card responsive, as described [here](https://github.com/Automattic/wp-calypso/issues/70852#issuecomment-1353224082).
( https://github.com/Automattic/wp-calypso/pull/72334 )

# Context:

Intended for use in multiple PRs:
- [Latest Post card and the Most Popular Post card](https://github.com/Automattic/wp-calypso/issues/70854)
![Image](https://user-images.githubusercontent.com/4044428/206020959-a3578c88-b79c-4f0f-9498-bde51ffaf9bd.png)

- Missing image variant
<img width="1046" alt="Screenshot 2023-01-13 at 5 58 52 PM" src="https://user-images.githubusercontent.com/112354940/212241098-d04c6e8c-295b-49ba-9668-65b804a2e5fc.png">

- One image missing
<img width="1110" alt="Screenshot 2023-01-13 at 6 01 43 PM" src="https://user-images.githubusercontent.com/112354940/212241430-8d8a9afa-73aa-4d7f-8589-b29b63d043b6.png">

- Single card variant
<img width="1101" alt="Screenshot 2023-01-13 at 6 01 55 PM" src="https://user-images.githubusercontent.com/112354940/212241500-28b879b2-1a87-420f-a45d-09127e982d14.png">

- Single card with missing image
<img width="1102" alt="Screenshot 2023-01-13 at 6 02 08 PM" src="https://user-images.githubusercontent.com/112354940/212241554-ae52c75c-08ae-40ed-a4d7-170219310dfc.png">

- [Post Details Page - note that the width of items in one row is no longer 50%](https://github.com/Automattic/wp-calypso/issues/70671)
![Image](https://user-images.githubusercontent.com/4044428/206016272-a9be922f-0461-4378-a7a6-e68f0616705f.png)

# Design Specifications:

![Image](https://user-images.githubusercontent.com/214813/205165791-fa1984ff-3d8d-4e93-8a75-00a48e81ade1.png)
![Image](https://user-images.githubusercontent.com/214813/205172786-9a56502d-140a-4580-a8a8-8a592ca8ecfd.png)

**Comment by jsnmoon** [comment]
@jeffgolenski, could you provide design specs for how the card should look when expanded to the full page width?

**Comment by jeffgolenski** [comment]
@jsnmoon Working on that now, sir! Let's **keep this on hold** until we figure out a few more design use-cases. Trying to figure out what it'll look like when no featured images are present and also if the most popular post is also the most recent. Will need to check with @keoshi before moving to dev!

**Comment by jsnmoon** [comment]
@jeffgolenski: We also need more explicit guidance on how to handle narrow cards. Since we might be putting two of these cards side-by-side on the Insights page, narrow cards may happen even during desktop viewport sizes.

Here's what we currently have in #70916:

> <img width="428" alt="image" src="https://user-images.githubusercontent.com/4044428/206822762-f523bf17-9fe9-431d-b948-2cae84be9b11.png">

**Comment by keoshi** [comment]
@jsnmoon We explored narrower cards in a few different settings:

#### Detail page

<img width="428" alt="image" src="https://user-images.githubusercontent.com/390760/207345878-eb3c5c18-00f0-402e-9dd2-2ea15aedf0a1.png">

#### Insights page

<img width="467" alt="image" src="https://user-images.githubusercontent.com/390760/207346258-73d2cc7b-34b3-40f1-9f2b-67dcadceab56.png">

Notice how in this last one, we thought about using the `dotPager` component and let users switch between Latest post and Most popular post by tapping on the dots or swiping left/right.

This is already covered in the [image with the “Spacing” heading above](https://user-images.githubusercontent.com/214813/205172786-9a56502d-140a-4580-a8a8-8a592ca8ecfd.png), so let me know what we're missing.

**Comment by jsnmoon** [comment]
> @jsnmoon We explored narrower cards in a few different settings:
> 
> Notice how in this last one, we thought about using the `dotPager` component and let users switch between Latest post and Most popular post by tapping on the dots or swiping left/right.
> 
> This is already covered in the [image with the "Spacing" heading above](https://user-images.githubusercontent.com/214813/205172786-9a56502d-140a-4580-a8a8-8a592ca8ecfd.png), so let me know what we're missing.

I'd forgotten we wanted to apply dot paging to mobile post stats cards on the insights page; thanks for the reminder, @keoshi! I was hung up on Jasper's review feedback [here](https://github.com/Automattic/wp-calypso/pull/70916#discussion_r1044065073) for handling component widths less than 220px, which would make the counts bump up against each other, like so:

![image](https://user-images.githubusercontent.com/4044428/207435613-3a2545bd-92e5-4c87-86db-68282bbde2a7.png)

(Note that this interface is still WIP; the date, for example, has not yet been converted to a relative duration.)

Do you think this is a valid edge case we need to consider?

**Comment by keoshi** [comment]
> Do you think this is a valid edge case we need to consider?

Just took a look at the top 100 [screen resolutions](https://analytics.google.com/analytics/web/?authuser=2#/p309939556/reports/explorer?params=_u..nav%3Dmaui%26_r.explorerCard..selmet%3D%5B%22activeUsers%22%5D%26_r.explorerCard..seldim%3D%5B%22screenResolution%22%5D&r=user-technology-detail&collectionId=user) our users visit WordPress.com from and the smallest width I could find was `320px`.

That still gives around 100px of breathing room to play around with, but if we think that's not enough we could reduce the `font-size` for super small screens (`< 320px`).

**Edit**: your solution of breaking these three columns into rows seems a much better idea. Style-wise we could replicate the same visual as the numbers below the chart:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/390760/207893805-ef6634de-b243-41a2-be5d-c61cfb614037.png">

**Comment by jeffgolenski** [comment]
@jsnmoon Alright, as promised I've got the edge cases designed for the Latest Post & Most Popular Post. Let me know if this is possible.

**Cases explored:**

- When neither of these posts have featured images, we can show a button to add a featured image (on large screens only). This would take them to edit the post directly. 
- When both cards display, truncate the post title to 40 chars. 
- Mobile: When no featured image is present, we don't need to add the "add featured image" button. Let's see how often it's used on large screens first.
- When the latest post is also most popular, just display the most popular at full width!
- If there is a latest post, but it does not have any stats, hide it. (a bunch of 0s is depressing)

![Latest post   most popular post](https://user-images.githubusercontent.com/214813/211883666-335ae3c2-445a-48d4-9e57-6c31ab238694.png)

Within Figma, these designs can be found in the Insights Page Sandbox! cc @keoshi

**Comment by grzegorz-cp** [comment]
@jeffgolenski If I follow the comments correctly, for the mobile view, we decided to stack the information like on the screenshot from Filipe [here](https://github.com/Automattic/wp-calypso/issues/70852#issuecomment-1353224082). Since usually there will be two items, we also want to use a dot pager here, don't we?

**Comment by grzegorz-cp** [comment]
I've also been wondering about the post's title. Currently, `Latest post summary` redirects to the post details stats page when clicking on the title. Do we want to add the same functionality to the new card's title?
Is there a benefit in redirecting to the post itself? That could be something to consider in the following version.

**Comment by dognose24** [comment]
Since the [post detail page](https://github.com/Automattic/wp-calypso/issues/70671) is the first place to equip this post stats card component, there is still [some detailed design feedback](https://github.com/Automattic/wp-calypso/issues/70671#issuecomment-1371719954) that needs to fix and update back to this component.

**Comment by dognose24** [comment]
Since the post detail page #70671 is the first place to equip this post stats card component, there is still [some detailed design feedback](https://github.com/Automattic/wp-calypso/issues/70671#issuecomment-1371719954) that needs to fix and update back to this component.

**Comment by jeffgolenski** [comment]
@grzegorz-cp 

> Since usually there will be two items, we also want to use a dot pager here, don't we?

Yes, please use the dotpager component, please!

> I've also been wondering about the post's title. Currently, Latest post summary redirects to the post details stats page when clicking on the title. Do we want to add the same functionality to the new card's title?
Is there a benefit in redirecting to the post itself? That could be something to consider in the following version.

Yeah, I think we should allow the Latest post card and Most popular post card to link to the detailed view of those posts, respectively. These can be "silent links" so they don't need to stand out.

**Comment by jsnmoon** [comment]
@dognose24, could you take ownership of this task, since you have the most experience working on this new component? 🙏

**Comment by jsnmoon** [comment]
Marking this task complete!
