### ISSUE TITLE
FSE Themes: White screen covers the editor when Template Editor is accessed via Post / Page editor.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#70864]
### Quick summary

A white screen covers the editor when Template Editor is accessed via Post / Page editor on FSE themes. I was able to reproduce this issue on simple and AT sites with multiple FSE themes.

![Screen Capture on 2022-12-07 at 07-11-44](https://user-images.githubusercontent.com/33957570/206086496-5edad3a2-a7ce-4a2b-b470-9b7843c2c7d6.gif)

### Steps to reproduce

1. On a simple or AT site, activate an FSE theme.
2. Go to Page or Post editor. 
3. Click on Edit template from the sidebar options.
4. You will notice a big white screen covering the template editor.
5. On AT sites, if you disable Gutenberg plugin, the issue is resolved. 

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/33957570/206086894-a41c27d8-445e-4fb5-810d-f7cdee01c551.png">

### What you expected to happen

There shouldn't be a white box covering the template editor when it is accessed via page or post editor.

### What actually happened

A white box was covering the template editor.

### Context

User report: 38536957-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

FSE themes

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

We can ask user to access template editor from Appearance > Editor.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: Could not replicate
- Replicable on Core? No

📌 FINDINGS/SCREENSHOTS/VIDEO
- This is reproducible on FSE themes on simple and AT sites, but only on WordPress.com.

*Examples*

AT, Theme: Munchies

<img width="1478" alt="Markup 2022-12-08 at 16 46 29" src="https://user-images.githubusercontent.com/27249804/206591137-062f1974-8d46-40ae-bedd-502ea5081626.png">

Simple, Theme: TT2

![Markup on 2022-12-08 at 16:51:09](https://user-images.githubusercontent.com/27249804/206591112-756bd0e8-a1c9-4601-bd8e-c52018719144.png)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by arinoch** [comment]
Ran into this issue in 37387318-hc (thanks for the assist, @cuemarie), provided the directly load FSE workaround. Follow-up in 5776706-zd-woothemes, please.

**Comment by cuemarie** [comment]
Gutenberg v14.7.1 fixes this issue! Fix is already rolled out to Simple sites, and is on it's way to AT soon.

See p1670543706330229-slack-C02FMH4G8 for more details

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

**Simple**
![ff6hMz.png](https://github.com/Automattic/wp-calypso/assets/67279475/070a5418-088a-4516-91d9-e285c0155a17)

**Atomic**
![wXflD9.png](https://github.com/Automattic/wp-calypso/assets/67279475/b415948a-092b-439f-ad24-f3d636a5e706)

📌 ACTIONS
- Closed as no longer relevant (issue resolved by issue https://github.com/Automattic/wp-calypso/issues/70668)
