### ISSUE TITLE
Support virtual page on the Jetpack sites

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#70867]
Referring to p1670401676578729-slack-CRWCHQGUB, we cannot resolve the home template from AT site…

![Image](https://user-images.githubusercontent.com/13596067/206131285-633c2930-44ea-49ce-b530-7ead5911c22d.png)

Also, the template endpoint is `/wp-json/wp/v2/templates/{id}` instead of `/wp/v2/sites/195140650/templates/{id}` on the AT sites.

**Comment by bangank36** [comment]
So we need to update the [useTemplate](https://github.com/Automattic/wp-calypso/blob/718b379bc5c844f7edb30a781cc85e7be748d8a5/packages/data-stores/src/templates/use-template.ts#L18) hook to cover all the template endpoints right?

**Comment by arthur791004** [comment]
We still need to get the correct template because the `/sites/{id}/block-editor` endpoint returns `null`

**Comment by bangank36** [comment]
> We still need to get the correct template because the /sites/{id}/block-editor endpoint returns null

You're right!

**Comment by arthur791004** [comment]
Close it via D94705-code and https://github.com/Automattic/wp-calypso/pull/70935
