### ISSUE TITLE
Theme Showcase: Improving search in mobile view

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#70862]
## Description
From the comment p7DVsv-fVu-p2#comment-43203, there seems to be an issue on mobile where search dropdown is not changing according to user input. See screenshot for reference:

![img_5283](https://user-images.githubusercontent.com/797888/206078581-b170423b-df74-4804-866a-1cb53f05fa8c.png)

## Acceptance Criteria
The search behavior should be the same as in the desktop view. That is, the search dropdown should reflect the changes in the search input field.

**Comment by fushar** [comment]
I was not able to reproduce this issue.

Using real iPhone:

|![iphone-1](https://user-images.githubusercontent.com/1525580/208368792-4c9859d3-b900-443f-bcc9-6e28dcb0bb18.jpg)|![iphone-2](https://user-images.githubusercontent.com/1525580/208368797-582727d9-7656-4750-abdd-c1838595b0f8.jpg)|
|-|-|

Using Chrome and set the device to iPhone:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/1525580/208369072-b83f0c12-9b20-4cf1-a684-eb56009d2bb6.png">

@enejb , could you check if you're still experiencing this issue? Thanks in advance!

**Comment by taipeicoder** [comment]
@fushar reading this comment p7DVsv-fVu-p2#comment-43219 more closely, I think the feedback is referring to that while typing, none of the themes are visible due to being blocked by the search dropdown and other UI components (filters, upsell banner, etc.) Another observation is that pressing "Done" in the virtual keyboard just closes that keyboard and doesn't trigger search.

My proposal for improvement is to scroll the search bar to the top when focused. And perhaps add a max-height to the search dropdown, but I don't think that would help towards making the themes visible.

**Comment by fushar** [comment]
Ah! I see!

However we don't do "trigger-search-on-type" even on desktop, so this issue is not exactly mobile issue. Scrolling the search bar to top when focused doesn't solve the issue as well -- we need to press Enter ("return") to trigger search.

**Comment by taipeicoder** [comment]
Right you are, I think we can disregard the "trigger-search-on-type" feedback for now since it's not the intended UX 🙂
I'm thinking how we can provide more visibility on themes while users type, but it's unfortunately a layout problem since the search input + filters + upsell banner take up half of the screen. The virtual keyboard takes up the other half. 

![Screen Shot 2022-12-27 at 2 32 32 PM](https://user-images.githubusercontent.com/797888/209622158-399a02a8-b228-4248-bd4d-b0e11dfe008a.png)

I propose we close this for now until we have a more actionable approach. cc: @SaxonF
