### ISSUE TITLE
Editor: Sharing accordion present on page editor for Jetpack site with Publicize, Likes, and Sharing disabled

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7088]
#### Steps to reproduce
1. Disable Publicize, Likes, and Sharing modules on your Jetpack site
2. Navigate to URL: https://wordpress.com/page
3. Select the Jetpack site configured in step 1

#### What I expected

No Sharing accordion should be present in the sidebar.

#### What happened instead

A Sharing accordion with empty content is shown in the sidebar.

#### Screenshot

![Page editor sharing](https://cloud.githubusercontent.com/assets/1779930/17188769/909e35a8-540c-11e6-8cc0-9c11e7a786d2.png)

**Comment by aduth** [comment]
I'm having a hard time reproducing this one now. Not sure if anything had changed to incidentally fix the issue. @timmyc are you still observing this to be a problem?

**Comment by timmyc** [comment]
Yes I can still reproduce this issue on JP 4.3 beta.  I think the JP settings to properly create the issue are disable sharing and likes but leave publicized enabled.

Fix at #7378
