### ISSUE TITLE
Newsletter & LIB - calypso_signup_start/complete events.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#70883]
Following a recent zoom call, we discovered we may not be handling these events as expected by data analytics in our TUC flows with launchpad. p1670348011578479/1669742224.639489-slack-C4BJFJVPF

- [x] `calypso_signup_complete` - We don't seem to be sending this event consistently for these cases. Running through the newsletter flow, this fires when we select "write your first post" from launchpad. Running through the LIB flow, I am not seeing this event fire currently (although there are some tracks data that seem to imply it fires somewhere). We should find a way to make this event consistent and near (just after) site creation, before landing on the launchpad (or maybe only the 1st time they land there?). This event is important for data teams for correlating information with other backend events fired during the process.
- [x] `calypso_signup_start` - We noticed that[ this event](https://github.com/Automattic/wp-calypso/blob/ea02efce3d3026a3a6dbf0a73c47e94806b946d3/client/landing/stepper/declarative-flow/link-in-bio.ts#L29) seems to fire any time someone enters the stepper flow (regardless of the step). This means that when re-visiting launchpad, the `calypso_signup_start` event fires even though the site has long been created and completed the signup flow. It's unclear what we want to do here - perhaps we can make this specific to the first step in each flow instead? Perhaps is some history to why it is the way it is currently? Perhaps when we send users back to the launchpad we do this in a different (but very similar) defined stepper flow that doesn't fire this event? -  But in its current state, funnels using this start event will encounter a sharp drop off due to this unexpected firing/placement of the event. 

cc'ing @alshakero and @Automattic/vertex team as well as you might have more insight or history here - especially related to the 'start' events placement.

**Comment by edanzer** [comment]
This has been done. I handled all start/complete tracking together for all flows. 

See the following PRs.
Signup start: https://github.com/Automattic/wp-calypso/pull/72252
Signup start for newsletters adjustment:  https://github.com/Automattic/wp-calypso/pull/73781
Signup complete: https://github.com/Automattic/wp-calypso/pull/72309

Also see this related issue: 
Free Flow tracking: https://github.com/Automattic/wp-calypso/issues/70845
