### ISSUE TITLE
Stepper: Plugin-bundle flow doesn't redirect properly on calypso.live links.

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#70936]
When testing the plugin-bundle flow from a calypso.live link, the user isn't properly redirected after checkout.

The problem is in [this checkout file](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/checkout/get-thank-you-page-url/index.ts#L135-L171), redirect_to being an absolute link to the calypso live, is not caught and thus uses are redirected to home.

This is due to the way the redirect_to url is added: it should be a relative link, not an absolute one.
So this won't work:
https://container-silly-buck.calypso.live/checkout/your-wordpress-site.wordpress.com?redirect_to=https%3A%2F%2Fcontainer-silly-buck.calypso.live%2Fsetup%2Fsite-setup%2FdesignSetup%3FsiteSlug%3Dyour-wordpress-site.wordpress.com%26theme%3Dthriving-artist#step2

But from my testings this will instead work:
https://container-silly-buck.calypso.live/checkout/your-wordpress-site.wordpress.com?redirect_to=%2Fsetup%2Fsite-setup%2FdesignSetup%3FsiteSlug%3Dyour-wordpress-site.wordpress.com%26theme%3Dthriving-artist#step2

Thanks to @escapemanuele for surfacing this!

**Comment by sixhours** [comment]
This seems like it would be a relatively simple fix, although it's not a user-facing improvement.

**Comment by sixhours** [comment]
Closing since this is an internal issue and not user facing.
