### ISSUE TITLE
Plans: not prompted for site selection on plans/compare

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#7094]
1. Navigate to http://calypso.localhost:3000/plans/compare
2. This redirects to http://calypso.localhost:3000/plans/features (maybe this should be /plans instead?)
3. We see the following infinite loaders:

<img width="907" alt="screen shot 2016-07-27 at 1 20 13 pm" src="https://cloud.githubusercontent.com/assets/1270189/17191154/8b970ac6-53fd-11e6-92d2-9fff04397a77.png">

The simplest fix at the moment is to prompt the user to specify a site. Alternatively we could support a generic logged in pricing page.

**Comment by lamosty** [comment]
It should be `/plans`. Sorry, I probably introduced this bug (with @artpi's [approval](https://github.com/Automattic/wp-calypso/pull/6893))

**Comment by lamosty** [comment]
We also need to redirect from `/plans/features/:site` to `/plans/:site` as `/plans/features` is not a specific route but it renders the plans because the catch-all route does it.

**Comment by artpi** [comment]
> Sorry, I probably introduced this bug (with @artpi's approval)

Quite possible! I am not a thorough person :D
I thought we needed /plans/features route for the test time - being. Now that we have this in master, can we get rid of `/plans/features` ?

**Comment by lamosty** [comment]
> Now that we have this in master, can we get rid of /plans/features ?

Yeah, I'm getting rid of it. Actually, there is no such thing as `/plans/features`. It's just this catch-all route: https://github.com/Automattic/wp-calypso/blob/80dac4074ef7419b83e77ac6594a73ff003e1fc7/client/my-sites/plans/index.js#L77-L77.
