### ISSUE TITLE
Expound theme: Archive pages skip over older posts

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#70952]
### Quick summary

On the (retired) _Expound_ theme, some older posts are missing from category/tag archive pages. After loading the next page of results (either with infinite scrolling or the "older posts" button), some posts are skipped over and never displayed. Navigating directly to sequential pages displays these "missing" posts as expected.

### Steps to reproduce

1. Activate _Expound_ theme (retired).
2. Ensure you have a larger number of posts all assigned to the same category (`uncategorized` will work).
3. At _Settings > Writing_ and/or _Settings > Reading,_ make sure the number of posts per blog page is less than the number of posts in your test category. (For reference, I tested with 13 posts and 5 per page, as well as 13 posts and 10 per page.)
4. Visit the category archive page on the site.
5. Scroll down to load older posts (with infinite scrolling or the `older posts` button).

### What you expected to happen

The next set of posts should be displayed. The full list of posts displayed should match exactly what you see at _My Site > Posts_.

### What actually happened

Posts are "skipped" when loading more. Video below was taken with "infinite scroll" off, but the same occurs with it enabled.

Note the second page is missing "test post 3" through "test post 1" and displays "test post 0" instead:

https://user-images.githubusercontent.com/5630717/206513736-df1f91bf-b553-4e8d-8c9d-b292cb803d42.mp4

But navigating directly to `/category/uncategorized/2` shows the correct results:

![Markup on 2022-12-08 at 11:51:56](https://user-images.githubusercontent.com/5630717/206514004-d5c91365-b11f-4fb7-b133-b4abf8244372.png)

### Context

5775562-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Replicated on the retired Expound theme. Unsure if this also affects other themes – I've definitely seen this before on other themes, though I can't seem to find those reports at the moment.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

No true workarounds. Blog Post blocks work as expected, including their "load more posts" button, but this isn't a true workaround for most users.

**Comment by kavyagokul** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
This theme was retired in 2017, so it's not going to receive a fix. 

📌 ACTIONS
- Closed as no longer relevant 


📌 Message to Author
- @jp-imagines Probably a good idea to let the user know, and suggest a newer theme.
