### ISSUE TITLE
Plans: Reconcile personal plan storage discrepancy

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#7095]
On the Plans page for a given site, the Personal plan reads:

> 3GB Storage Space

However, when I add it to a site, I then see 13GB of storage when adding an item to my media library while editing a post instead of the 3GB I was expecting.

The copy on the info popup for the Personal plan also reads:

> With increased storage space you'll be able to upload more images, videos, audio, and documents to your website.

Since free sites currently get 3GB as well, this doesn't seem accurate since it's not really an "increased" amount of storage space over the default option.

#### Steps to reproduce
1. Purchase a Personal plan on your site
2. In Calypso, add a new post to that site and then add a media item. 

#### What I expected
I expected to see "__% of 3GB" since that's the displayed amount available in the plan.

#### What happened instead
I see "0.2% of 13 GB used"

#### Browser / OS version
Chrome 51.0.. Mac OS X El Capitan

#### Screenshot / Video
![screen shot 2016-07-27 at 2 25 49 pm](https://cloud.githubusercontent.com/assets/7240478/17191208/154a2ee4-5406-11e6-9520-e945e19c32df.png)

#### Context / Source
Indirect #user-report in #118535-h

**Comment by rodrigoi** [comment]
This has been fixed. New users that select or upgrade to the Personal Plan will have the 3GB space limit.

![screen shot 2016-08-04 at 17 52 04](https://cloud.githubusercontent.com/assets/233601/17417927/35a688e2-5a6c-11e6-9821-f8d9f6d6b03f.png)
