### ISSUE TITLE
Wide layout makes some pages hard to read + some inconsistencies

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7096]
@klimeryk found a bug with the wide layout redesigned plans use (p1469651926001040-slack-calypso). The Domain Management doesn't use wide layout as shown on the screenshot below:

![selection_091](https://cloud.githubusercontent.com/assets/4988512/17191863/505f4082-544c-11e6-86a1-1cba13522006.png)

What is more, even if we made it wide layout, @klimeryk notes that it will be hard to read. The "Domains" tab uses wide layout and it's hard to read, too (according to him):

<img width="1240" alt="screen_shot_2016-07-27_at_22 39 24" src="https://cloud.githubusercontent.com/assets/4988512/17191906/8e2c382a-544c-11e6-9a32-8c31d2dd8501.png">

While the initial issue can be fixed quite easily, I'd like to have a few designers look at these things and judge whether it's really hard to read with the wide layout or not. And if yes, what would be the best remedy for it.

**Comment by apeatling** [comment]
I don't think the wide layout is a big deal based on what I see above. There are not long sentences of text.

**Comment by klimeryk** [comment]
> I don't think the wide layout is a big deal based on what I see above. There are not long sentences of text.

On this view - sure. But please check other views in Domain Management. Clicking on one of those domains leads to a detailed view that has already been reported by @mtias in https://github.com/Automattic/wp-calypso/issues/1737 as hard to read. Making it wide would just exacerbate the problem:

<img width="959" alt="screen shot 2016-07-28 at 01 14 36" src="https://cloud.githubusercontent.com/assets/3392497/17195888/e23ec84c-5460-11e6-8029-8712cc5761e2.png">

The DNS editor also looks "bloated" when set to wide and inconsistent with other views such as Settings (which are not wide):

<img width="1116" alt="screen shot 2016-07-28 at 01 20 18" src="https://cloud.githubusercontent.com/assets/3392497/17195965/7f05b8ca-5461-11e6-9911-8e01729af101.png">

cc @breezyskies

**Comment by rralian** [comment]
I actually think it seems unexpected that these pages are shown together in the first place. "Plans" has its own sidebar item and so does "Domains." So when you click on these sibling options you navigate to a totally different section. They even have different homes in the URL. Why don't we just separate them? It looks like we could do this by removing the "my plan" and "plans" link from the domain pages and removing "domains" and "google apps" from the plans pages. Both sections would feel a little more logical (IMHO) and you could go back to the narrow pages for domains.

**Comment by mtias** [comment]
@rralian I think the design goal with the Plans navigation was to actually bring them closer and eventually remove domains from the sidebar. (It makes even more sense when you consider it domains <em>a la carte</em> aren't around anymore.)

**Comment by folletto** [comment]
> While the initial issue can be fixed quite easily, I'd like to have a few designers look at these things and judge whether it's really hard to read with the wide layout or not. And if yes, what would be the best remedy for it.

Yeah, it does. Even if there aren't full "sentences" there, there's still the separation of actions (label on the left, actions on the right) which makes the UI disconnected.

_As a rough rule of thumb, consider a maximum width of a "column" around 600-700px._

What's the need here of going that wide?

**Comment by lamosty** [comment]
> Yeah, it does. Even if there aren't full "sentences" there, there's still the separation of actions (label on the left, actions on the right) which makes the UI disconnected.

I see, thanks for your eyes. :eyes: 

> What's the need here of going that wide?

The new plans page needs to be wider otherwise the plans would be too crammed on each other. I would make it even wider but we don't have more space.

**Comment by folletto** [comment]
> The new plans page needs to be wider otherwise the plans would be too crammed on each other. I would make it even wider but we don't have more space.

The plans page can go wider, and we can keep the other pages in a more restricted view. We already have sections that go wider and other that don't.

The issue might just be a jumpy top navigation, so we might think something that is able to satisfy both. 

Another way would be to design the Domain Management page to go on two columns beyond a certain size.

**Comment by mtias** [comment]
> The issue might just be a jumpy top navigation, so we might think something that is able to satisfy both.

We are running into this in quite a few sections. We probably should figure out something where section nav is always full-width (perhaps even anchored to the page) and content can be whatever the content needs.

**Comment by folletto** [comment]
> We are running into this in quite a few sections. We probably should figure out something where section nav is always full-width (perhaps even anchored to the page) and content can be whatever the content needs.

That could be a good idea, and in line with our app-like approach.

Something like a Marginless Tab Bar:

![marginless-tab-bar-domains](https://cloud.githubusercontent.com/assets/4389/17211312/9f233e8e-54c0-11e6-9822-6a103f06d91b.png)

![marginless-tab-bar-stats](https://cloud.githubusercontent.com/assets/4389/17211313/9f250f0c-54c0-11e6-9d05-c163d98edc06.png)

**Comment by mtias** [comment]
Yes. Wonder what other designers think of it. cc @rickybanister @shaunandrews @adambbecker

**Comment by shaunandrews** [comment]
I'm totally on board with ditching our max-width where it makes sense. I proposed a PR (#3312 in pre-oss) that did this a long time ago, but there was some push-back about the width of screens changing as you move around Calypso — this didn't bother me then, and still doesn't bother me now.

Fixing the section nav (and always having it be consistent in its 100% - sidebar width) would help with the different widths between screens, as there would be a consistent element.

**Comment by mtias** [comment]
Yes, if we can figure out something for section nav that works, it becomes less of an issue whether the content has different widths, in my opinion. The biggest problem right now is that navigation jumps when you go from a wide width section to a narrow width section or to a full width section.

(Examples: "/posts" and "/posts/drafts"; this case with domains, from themes to any other section, etc.)

**Comment by adambbecker** [comment]
Ooh, yeah I'd definitely love to explore ditching any `max-width` we can and even if the content itself doesn't look all that great stretched out, that just means there's an opportunity to utilize the space available when the width is unrestricted.

I think that's @folletto's idea about a docked "Marginless Tab Bar" is totally a method by which we can explore further, especially since it's moves us towards more of an app-like layout which I've always wanted to move towards.

---

In the short term however, I've found that letting the content extend to `1040px` seems to be a nice middle ground. For example, here are a few screens with that max-width extension in place:

##### Stats
![screen shot 2016-07-28 at 11 07 01 am](https://cloud.githubusercontent.com/assets/1427136/17217813/b3581ae4-54b3-11e6-8af4-c72f530bb48e.png)

##### Posts
![screen shot 2016-07-28 at 11 07 44 am](https://cloud.githubusercontent.com/assets/1427136/17217831/bfe12bde-54b3-11e6-8167-37aee5cb5457.png)

##### Settings
![screen shot 2016-07-28 at 11 08 14 am](https://cloud.githubusercontent.com/assets/1427136/17217839/c7553360-54b3-11e6-8fd2-df4890f44ba3.png)

##### Plugins
![screen shot 2016-07-28 at 11 08 43 am](https://cloud.githubusercontent.com/assets/1427136/17217852/d1aff3b8-54b3-11e6-8fc5-22f8b7eff506.png)

---

That would basically be changing [this line](https://github.com/Automattic/wp-calypso/blob/30c0eedba1a57749e3b9d67e9b0ae6750efa2aa9/client/components/main/style.scss#L3) to `max-width: 1040px;`.

**Comment by breezyskies** [comment]
The "docked section nav" looks like a potentially good solution that could be applied in a few places that are having this issue. There are going to be some sections that don't make sense at full width, so this would be good to have regardless of domains specifically.

> I think the design goal with the Plans navigation was to actually bring them closer and eventually remove domains from the sidebar. (It makes even more sense when you consider it domains a la carte aren't around anymore.)

We've had several discussions about moving domains into settings (p6qnuF-HG-p2). @adambbecker also did some great concept work around this. However, this does need testing. Domains aren't a la carte anymore, but it's very likely they are still a major driver of plan sales. (Another consideration here has been the cart, which is shared between the plans and domains in the current section nav. Not a deal breaker but needs more thought.)

**Comment by lancewillett** [comment]
Related notes from a recent #dogfooding session by @beaulebens 

> Plans (and sub-sections) are the only ones who use a full-width layout. Domain details uses a controlled width. Jumps around a lot, feels broken.

Here's a screencast I took today, showing how jarring it can be as you move down the sidebar menu items:

![full-width-and-narrower](https://cloud.githubusercontent.com/assets/66797/19133813/2d713c98-8b0f-11e6-8551-81fefbceba60.gif)

**Comment by lancewillett** [comment]
See also https://github.com/Automattic/wp-calypso/issues/3920

**Comment by kriskarkoski** [comment]
There is still some inconsistency in Calypso widths, for example (clicking down the sidebar):
- Hosting Configuration (wide)
- Domains (wide)*
- People (narrow)
- Settings (narrow)

* Domains further jumps back to narrow if you click a single domaiin

**Comment by klimeryk** [comment]
@fditrapani, would be great to tackle this one along with the Domain Management revamp 🙏

**Comment by klimeryk** [comment]
Marking this as wontfix - this needs to be tackled on a higher/more general level and there does not appear there's appetite for that.
