### ISSUE TITLE
Launchpad: WoA compatibility

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#70965]
### Details

Any site that is created through Launchpad but transferred to Atomic will never be able to complete Launchpad.

### Checklist

- [x] Sync Launchpad options to wpcom via Jetpack
- [x] Copy Launchpad business logic to `wpcomsh`
- [x] Allow frontend previews on unlaunched sites

**Comment by Addison-Stavlo** [comment]
I believe all 3 bullet points above are resolved at this point. Is there anything else still needing to be done for this issue? cc @mattwiebe @edanzer

**Comment by mattwiebe** [comment]
Yup they're all resolved now, hooray! Closing this, we can open new issues for any specific troubles with the functionality.
