### ISSUE TITLE
Stats: Google My Business page enhancements (MVP)

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#70973]
# Development

- [x] Implement a new page header (same title and nav as all other stats pages)
( https://github.com/Automattic/wp-calypso/pull/72188 )
- [x] Change subtitle to "Integrate your business with Google and get stats on your locations. Learn more".
( https://github.com/Automattic/wp-calypso/pull/72188 )
  - Learn more should [link here](https://wordpress.com/support/google-my-business-integration/#checking-the-impact-of-your-google-my-business-connection).
- [x] "Google My Business" should be added as a nav item.
( https://github.com/Automattic/wp-calypso/pull/72188 )
- [x] Expand the content cards on this page to fill the width of the page:
![206593192-57bca018-18ee-4cfc-a5c0-27df66df6861](https://user-images.githubusercontent.com/6869813/212805089-8bb40969-b778-41ff-9f4c-2a00f815644e.png)
( https://github.com/Automattic/wp-calypso/pull/72188 )

# Design

Admittedly, we just discovered that the Google My Business page lives within stats for a small number of customers. As an MVP to modernize this page, can we implement the new stats page header + nav? Mocks below

### Current

|Before|After|
|-|-|
|![206592596-c662c5a5-2b9d-4cb1-8ebe-94c39eac9b4f](https://user-images.githubusercontent.com/6869813/212805793-78463629-e3ae-496c-95dd-f283e6445a2f.png)|![206592654-e72ee165-ec6c-4e20-aa7e-332537d8b37c](https://user-images.githubusercontent.com/6869813/212805833-a697c533-5e47-49d9-8972-1bd33dfc1702.png)|

**Comment by dognose24** [comment]
Closed with #72188.
