### ISSUE TITLE
Posts: Editing post from All Sites list yields null entry

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7097]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts
2. Click on the header of a post to open it in the editor
3. Click the Back button

#### What I expected
To return to the Posts list

#### What happened instead
The editor display is malformed, and the URL has `null` listed as the site.  Clicking Back again seems to work.

#### Browser / OS version
OSX Chrome v51

#### Screenshot / Video
![wp-calypso-posts-null3](https://cloud.githubusercontent.com/assets/7233112/17192308/deb7f59e-541b-11e6-895d-a37d26e4ea50.gif)

#### Context / Source
#manual-testing

**Comment by lancewillett** [comment]
I couldn't repeat this in Mac-n-Chrome. Feel free to re-open if you see it again.
