### ISSUE TITLE
Stats: Improve card hover state improvements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#70975]
The current hover / active states of each visual line item, isn't great for a couple of reasons:

The blue icons on top of a light blue bar are difficult to see
![Image](https://user-images.githubusercontent.com/214813/206597498-3db7391d-6b18-431c-ab65-a666222dcca0.png)

The text is difficult to read when the bar ends underneath it and is hovered.
![Image](https://user-images.githubusercontent.com/214813/206597517-02f6b3a6-2e51-4180-912b-c76416bcd779.png)

### Proposed

![Image](https://user-images.githubusercontent.com/214813/206598135-8f5c2011-55ae-4e76-909f-231ba7cc41f2.png)

To fix this issue, we're proposed some deeper contrast and consistency with a new hover / active state. With this:

- [ ] All text and icons will be the same color
- [ ] The length of the bar when hovered is more clear
- [ ] Deeper contrast with a deeper color background and white text / icons (theme dependent, will need to test)

**See prototypes**
[Hover state](https://codesandbox.io/s/stats-module-v2-09uyhm), [Nested hover state](https://codesandbox.io/s/stats-module-v2-1-w-groupings-h6qq9v) 

(@grzegorz-cp feel free to alter the final product as you mentioned in slack. you had some great ideas!)

**Comment by jsnmoon** [comment]
Closed by #71437.
