### ISSUE TITLE
SEO Preview Pane: Adjust for narrow screens

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#7098]
The new SEO editor pane in the `<WebPreview />` component includes the wide `<VerticalMenu />` component which does not work well on mobile/narrow displays. For views narrower than a certain width, we should switch out the `<VerticalMenu />` with something like a dropdown menu, or maybe even inline all of the previews in one big scrollable list.

For inspiration from another component, see [components/section-nav](https://github.com/Automattic/wp-calypso/tree/cbe60f7af9531c33a0384e794058a4604be55501/client/components/section-nav)

**Comment by roundhill** [comment]
Fixed via #7145
