### ISSUE TITLE
Marketplace: license provisioned with the wrong site domain

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#70980]
In p1670525945416779-slack-C03TY6J1A it seems that

1. A simple site user purchased Yoast SEO Premium
2. Site got Atomic, Domain changed, License got provisioned
3. License got provisioned with the wrong domain (*.wordpress.com)

Normally, whenever the site domain changes we should trigger a domain change event ( a specific API call for Yoast, a webhook for other plugins ). It seems that this event hasn't triggered while site was transferring and on the same time license got provisioned before the domain has changed.

**Comment by NoHopeRadio** [comment]
This happened again in 38317765-hc , the Yoast subscription was showing as inactive and the registered site address had the .wordpress.com instead of the custom domain. Changing the primary domain to the internal .wpcomstaging address and back to the custom domain seemed to correct the problem.

**Comment by ha-un** [comment]
Similar issue in 38798095-hc - the Yoast Premium plan was showing inactive as the site was previously a Jetpack-connected site, although the upgrade was purchased after the site was migrated.

Removed the Yoast Premium plan & added plan again to fix the problem.

**Comment by CodeAllNightNDay** [comment]
39656968-hc I switched domain to default and then back. It resolved the issue.

**Comment by brittanygray902** [comment]
7398774-hc 
5945669-zd

Had the same issue with this user. We've tried switching the domain to default and back - this did not work. Other testing tried was the following:

- deactivate all plugins, aside from Yoast
- adding / removing the Yoast Premium subscription
- another browser
- cache flush

None of these attempts fixed the problem. Issue persists.

**Comment by gavande1** [comment]
Diff created at D102059-code

**Comment by gavande1** [comment]
Deployed 261988-wpcom

**Comment by NoHopeRadio** [comment]
Another case in 39265997-hc 

`wpcomsh plugin use-managed wordpress-seo-premium` did not seem to work. I could not get the subscription to show until removing and readding it.

**Comment by gavande1** [comment]
Hey @NoHopeRadio, Thank you for reporting this issue. 
The site was affected by a recent [bug](https://github.com/Automattic/wp-calypso/issues/73857) where we were getting an `invalid hostname` error. That issue has been resolved.
