### ISSUE TITLE
DIFM House ads

### ISSUE THREAD

**Issue by Noemish** [Automattic/wp-calypso#70999]
Final [deliverables](Gf94NHvnrI6ViCfufxsi6V-fi-56%3A22116&t=V4IKvzHOKyFsYOhs-4)

Main designer: @jrdnhllr
Support designer: @garretsteider-a8c @Noemish

**Comment by jrdnhllr** [comment]
Final deliverables: [Figma](Gf94NHvnrI6ViCfufxsi6V-fi-216%3A1320) | [Drive](https://drive.google.com/drive/u/1/folders/1XwXTD3su5kSsX99pJK9HPLT6ea7HBHFT)
