### ISSUE TITLE
Reader: emoji support is missing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#710]
WordPress.com smilies are not working in the Reader.

Steps to reproduce:

1. Start a new post at https://wordpress.com/post
1. Add several emojis (see sample text below)
1. Publish the post and view it in the Reader

<strong>Result:</strong> emojis show up on the original post but don't work in the Reader.

![screen shot 2015-11-24 at tue nov 24 8 09 28 pm](https://cloud.githubusercontent.com/assets/1119271/11385499/6ed4b028-92e7-11e5-8df0-32f3dace5afc.png)
<sup>Seen at https://wordpress.com/ using Firefox 42.0 on Mac OS X 10.10.5</sup>

Blog stream: https://wordpress.com/read/blog/feed/40471243
Single-post view: https://wordpress.com/read/post/feed/40471243/872451398

<strong>Sample text:</strong>

```
:) ;) :D XD >:D :( :'( :| :/ :o :P >:( o_O 8-) ^^’ <3 :? =^-^= :evil: :twisted: :mrgreen: :oops: :roll: :idea: :!: :?: :bear: :star: :arrow:
```

From pento:

<blockquote>Just as a wild guess, is it because some smilies have < or > in the alt tag? I don't know how Calypso's HTML sanity checking works, so this is just the thing that jumps out at me from the initial post.</blockquote>

/hat tip eurello for the original report

**Comment by blowery** [comment]
test posts https://wordpress.com/read/post/feed/25320833/877372961 and https://wordpress.com/read/post/feed/25320833/877372763

Looks like they're just plain not getting converted. We'll have to figure out what converts them and get into the right place.

**Comment by dongseok0** [comment]
It looks contents are already converted but just stylesheet is missed.
