### ISSUE TITLE
WPcom House ads

### ISSUE THREAD

**Issue by Noemish** [Automattic/wp-calypso#71000]
[February request](p9Jlb4-6fv-p2)

Figma: 6wteAIDvmBC6VFcIBsOO99-fi-193%3A1817
Drive: 

Main designer: @jrdnhllr
Support designer: @garretsteider-a8c @Noemish

**Comment by jrdnhllr** [comment]
Final deliverables: [Figma](Gf94NHvnrI6ViCfufxsi6V-fi-216%3A1320) | [Drive](https://drive.google.com/drive/u/1/folders/1KCpze8N1RcXcrUmV_jOyzYrXjKdFVX3I)
