### ISSUE TITLE
Stats: Enhance posts details page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#71015]
We need a slight update to the visuals on the detail pages for posts, which are accessed from the Posts & Pages card on the Traffic page.

### Before / After
![Image](https://user-images.githubusercontent.com/214813/206769300-f66e6d17-3f94-4b17-a1d9-2fdb29563842.png)

### Notes

**Components that should be reused from other stats pages:**

- “All-time stats” card should use the “latest post” or “most popular post” component from the Insights page.
- Chart is the same as located on the Traffic page.
- All-time insights chart is the same as the Insights page.

**Components that need fresh styling**

- Post likes card

_As always, the dev specs also live in the Figma project on the Documentation for Devs page!_ 

![Image](https://user-images.githubusercontent.com/214813/206769679-7a06dc1f-97dd-4bd3-8742-362709fd7108.png)

**Comment by dognose24** [comment]
@jeffgolenski Is this task the same as #70671? If not, could you highlight the page URL for investigating quickly? 🙏🏼

**Comment by jsnmoon** [comment]
@jeffgolenski: Could we get added clarity for this task? Thank you! 🙏

**Comment by jeffgolenski** [comment]
@jsnmoon @dognose24 Sorry friends, github notifications still aren't pinging me on all issues I'm mentioned in. This looks to be a duplicate of [#70671](https://github.com/Automattic/wp-calypso/issues/70671). Sorry about that.
