### ISSUE TITLE
☂ [Spike] Adding style selection, fonts, colors to the Site Assembler Flow

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#71038]
# Description 
Below is a mockup from @SaxonF .   Picture it with the sidenav having two options 1) Choose starting style 2) Customize homepage.  So the user will go through a flow that allows for picking both patterns for their homepage and styles. This is concept that we will likely build.

### Example of possible flow (which is likely to change):
* User chooses Blank Canvas
* User sees sidebar options: Customize homepage & Choose starting style
* User chooses patters
* Then user chooses styles

In addition to near-build plans, there are further ideas to explore that are similar to Style Selection, which is both font+color.  We want to understand how the implementation would be different if we had a UI where the user selected just fonts or just colors.   This spike issue will explore all of these concepts.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/5665959/206941633-ceee8984-dc00-4605-b8ce-6cd27a77a367.png">

# Goals of this spike
- [x]  Go through the flow and code of gating styles that team Trex has done.  We will be doing similar UX.
- [x] Understand how the existing patterns in the PA flow work with global styles. What are the possible tech difficulties blocks?
  - [x] Will we need new patterns that work properly with choosing style selection  
- [x] Understand any blockers it would work to add font selection (just font, not color)
- [x] Understand any blockers to add color selection (just color, not font)
- [x] At the end of the spike, create an umbrella issue or separate git issues for the project work

# Dev Tasks 
- [x] pbxlJb-3l4-p2
- [x] https://github.com/Automattic/wp-calypso/pull/71917
- [x] Status Updates in the comments (see [example](https://github.com/Automattic/wp-calypso/issues/67076#issuecomment-1340530548) )

**Comment by autumnfjeld** [comment]
@arthur791004  This is another thing to think about during this spike, if the existing patterns work well with style changes.  Maybe they don't looks very interesting.

We will need an effort from themers on this as well, @alaczek @iamtakashi @onuro.

**Comment by autumnfjeld** [comment]
FYI @arthur791004 & @SaxonF  : looks like we may lean towards having separate steps for font and color selection, rather than the combined style variation choice.  See comment from Matias: pekYwv-gV-p2#comment-296. (Of course things may change.)



![Image](https://user-images.githubusercontent.com/5665959/208947987-b2eb51e2-05ab-4bcc-8687-116c0a9926c2.png)

**Comment by arthur791004** [comment]
## Status Update on Jan 12

Referring to pbxlJb-3l4-p2 and https://github.com/Automattic/wp-calypso/pull/71917, we're able to

* Display font and color variations in the site assembler
* Preview the selected font and color variation
* Store the selected font and color variation
* When to display upsell modal

See pbxlJb-3l4-p2 for more details and here is a quick demo:

https://user-images.githubusercontent.com/13596067/212050998-cd6d437b-afe0-40c9-aee2-f8098db0027f.mov

There are some issues that need to be resolved, but the technical path is clear. So, I break this ticket into the following tasks and plan to close this spike ticket

* https://github.com/Automattic/wp-calypso/issues/71976
* https://github.com/Automattic/wp-calypso/issues/71977
* https://github.com/Automattic/wp-calypso/issues/71978
* https://github.com/Automattic/wp-calypso/issues/71979
* https://github.com/Automattic/wp-calypso/issues/71980
* https://github.com/Automattic/wp-calypso/issues/71981
* https://github.com/Automattic/wp-calypso/issues/71982
* https://github.com/Automattic/wp-calypso/issues/71983
* https://github.com/Automattic/wp-calypso/issues/71985
