### ISSUE TITLE
[Earn] Rip out jQuery from checkout

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#71046]
On the backend, checkout uses jQuery to power the checkout experience in this file:

`/wp-content/lib/memberships/memberships-checkout-form.js`

We would love to stop using jQuery and switch to vanilla JS instead.
@neffff started this work and stopped it later, but I cannot find any reference.

**Comment by millerf** [comment]
Diff: D95337-code

I could not find how to test with saved cards
