### ISSUE TITLE
Odd upsell nudge placement on `/themes` for contacting support

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71068]
### Quick summary

The placement of this upsell nudge above all other content on the page, and at a narrower width, feels awkward. 

<img width="1404" alt="Screen Shot 2022-12-12 at 9 22 58 AM" src="https://user-images.githubusercontent.com/2124984/207069756-b20a1212-4ff3-4797-88bf-9cc50c2b840c.png">

### Steps to reproduce

I'm not sure what triggers this particular nudge because I don't see it on my other test sites. 

1. I have a test site on a Business plan, recently upgraded (within the last week)
2. I have a custom domain
3. I happened to be looking at `/themes`, but it also appears at `/plugins` at a slightly better location

<img width="1392" alt="Screen Shot 2022-12-12 at 9 28 40 AM" src="https://user-images.githubusercontent.com/2124984/207070709-50bf8115-f879-452d-9db2-f37ff30d04cf.png">

### What you expected to happen

For the nudge to look more integrated with the rest of the Theme Showcases' design (not above the major page heading, for example, and matching the width of the screen)

### What actually happened

<img width="1404" alt="Screen Shot 2022-12-12 at 9 22 58 AM" src="https://user-images.githubusercontent.com/2124984/207071262-490f303a-3851-4f1d-9721-188018c9d0b7.png">

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by simison** [comment]
FYI @autumnfjeld @Copons @ianstewart

**Comment by DustyReagan** [comment]
This particular JITM is for the churn retention experiment. More info here pb5gDS-2nh-p2 I think we may also have a duplicate issue here: https://github.com/Automattic/dotcom-forge/issues/1339
