### ISSUE TITLE
eCommerce flow: storeAddress step country drop-down border is partly obscured

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71072]
On the `storeAddress` step, the country drop-down is missing a bottom border:
<img width="1915" alt="207083786-248114fd-ceae-4614-ab7f-2341fa79159f" src="https://user-images.githubusercontent.com/5436027/207514983-066659a5-3742-469e-9b4d-aef71846f446.png">

Raised in p1670823429884279-slack-C0Q664T29

**Comment by mreishus** [comment]
Fixed in #71084
