### ISSUE TITLE
Theme Showcase - Pages are incorrectly translated (inconsistently)

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#71079]
Reported from pdqkMK-Nl-p2 - Any reason why the theme details pages are not translated? I can see why it might be a challenge to do this for plenty of third-party themes, but maybe we could keep our Automattic themes translated?

For the [rainfall theme](https://wordpress.com/ja/theme/rainfall) as an example, the description has translations [in only two locales](https://translate.wordpress.com/projects/wpcom/-all-translated/845574/):

![image](https://user-images.githubusercontent.com/13437011/207092662-c78e881d-8708-42bf-9f16-c6dd28bd8161.png)

Also, there are a lot of common elements in the theme details page which can be translated once and will be visible across all pages.

![image](https://user-images.githubusercontent.com/13437011/207092775-6a19f89a-1a8c-418d-9d3a-ead3393e67b5.png)
![image](https://user-images.githubusercontent.com/13437011/207092803-955798a9-ab82-4d46-9b24-6f737beb3152.png)
![image](https://user-images.githubusercontent.com/13437011/207092826-64d8aed5-36ae-4dd3-a624-58e2d0de50a7.png)

The support links there need to go to the localized support pages.

FURTHER INFO: There seems to be something off with the way translations are loaded. For [Baxter theme](https://wordpress.com/ja/theme/baxter), I’m seeing all the sections translated, but for [Rainfall theme](https://wordpress.com/ja/theme/rainfall), the page is mostly untranslated.

**Comment by blackjackkent** [comment]
(Not sure as I'm creating this issue if this is a question for Serenity or for @Automattic/i18n - can someone from that team take a look as well please?)

**Comment by dlind1** [comment]
We are currently looking into in it pxLjZ-7va-p2.

**Comment by sixhours** [comment]
Followed up in the P2 post to find out if this is still on the roadmap for i18n folks: pxLjZ-7va-p2#comment-19864

**Comment by sixhours** [comment]
As per Emily's reply on the P2 post:

> The descriptions of the new 3rd-party premium themes aren’t in GlotPress like [Automattic] themes, so we have no way to get those localized.

We'd need to work on a method of getting 3rd-party premium themes "hooked up" to GlotPress so they can also be translated. I don't know where that falls in our list of priorities so I'm leaving this open for now.

**Comment by sixhours** [comment]
This is unlikely to be prioritized in the next year, so closing as wontfix.
