### ISSUE TITLE
Theme Showcase: Upgrade CTA not working

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#71076]
Reported from pdqkMK-Nl-p2 - The upgrade CTA that is shown when not logged in, when a search term has zero results, is not working.

![image](https://user-images.githubusercontent.com/13437011/207091657-cd504b87-c11a-42a1-b5f9-43a9aaa546c9.png)

**Comment by blackjackkent** [comment]
@daledupreez The issue here is that this has logic left over from when this was also the logged-in view and is trying to navigate to `/checkout/${ selectedSite.slug }/${ PLAN_BUSINESS }?redirect_to=/themes/${ selectedSite.slug }`, but `selectedSite` does not exist so it nulls out. I'm assuming that we want to redirect in this scenario to either https://wordpress.com/pricing/ or directly to https://wordpress.com/start/business/user - do you have a preference on which?

**Comment by WBerredo** [comment]
@blackjackkent I created a fix on #71124 replacing this CTA with a `Get Started` CTA.
