### ISSUE TITLE
Reading Settings: Fix unexpectedly displayed "Changes you made may not be saved." dialog

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#71071]
When a setting with a toggle is changed and saved, the "Changes you made may not be saved." browser dialog appears on a page reload (or when trying to navigate away) - even though there's no need for it:

![Image](https://user-images.githubusercontent.com/25105483/207081798-897c7bd3-f495-414a-893f-bc910745fba8.png)

We could reproduce this issue with the following two settings:

* Enable featured image on your new post emails
* Limit feed to excerpt only

**Comment by ivan-ottinger** [comment]
Looks like the issue arises from the difference between saved `setting` (site option) value and the current value of the form `field` / toggle.

For instance, here's a comparison of values _before_ and _after_ the Featured image toggle is changed from `true` to `false` and saved:

**Before saving**
* value of `wpcom_featured_image_in_email` in `fields`: `true`
* value of `wpcom_featured_image_in_email` in `settings`: `true`

**After saving**
* value of `wpcom_featured_image_in_email` in `fields`: `false`
* value of `wpcom_featured_image_in_email` in `settings`: `0`

→ Hence the form still thinks the value haven't been saved.

This is quite similar to this issue: https://github.com/Automattic/wp-calypso/issues/71839.

I will explore what would be the best way to fix the toggles saving. So far it looks like that we may want to update the format specific options are stored in, e.g. not saving false as `0`, but `false` instead.

What's worth noting is that I haven't checked other toggles that are experiencing the same issue yet, just the `wpcom_featured_image_in_email`.

**Comment by ivan-ottinger** [comment]
Looks like there's something more in play - as even when I made sure both values match the type, i.e.: both are boolean and also have the same value after the form is saved (i.e. `false`), the browser prompt still appears...

**Comment by ivan-ottinger** [comment]
Alright, turns out that `updateDirtyFields` array inside `updateDirtyFields()` of `WrappedSettingsForm` component (in `client/my-sites/site-settings/wrap-settings-form.jsx`) keeps the updated field in it - even after it has been saved correctly.

Since the issue happens only when the toggles and radio buttons go from `true` to `false` when specific field goes into `undefined` state (which I was able to observe), I suspect that could be the root cause. Needs more investigation.

**Comment by mashikag** [comment]
### Another Report
I experienced the same issue after saving **Your homepage displays** setting on the new settings page.

**Comment by ivan-ottinger** [comment]
> I experienced the same issue after saving Your homepage displays setting on the new settings page.

Looks like this is somewhat related - as it happens when the "no" page is selected - similarly to toggles when `false` option is picked:

![Image](https://user-images.githubusercontent.com/25105483/214578680-92565d5d-a723-4d3b-abae-cfda06826972.png)
