### ISSUE TITLE
When Gutenberg Plugin is Active, Site Logo won't resize

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#71089]
### Quick summary

When the WordPress.com Gutenberg plugin is active on a WordPress.com site using a Full Site Editing theme, the attribute Image Width does not appear in block settings for a Site Logo Block.

### Steps to reproduce

1. Activate a Full Site Editing theme, such as Tsubaki
2. While Gutenberg plugin is active, go to the Site Editor
3. Insert a Site Logo Block

### What you expected to happen

The Site Logo Block's Image Width attribute should appear in Block settings

### What actually happened

The Site Logo Block's Image Width attribute does not appear in Block settings

### Context

Customer report 38614873-hc and HE testing

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

All FSE themes

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Deactivating the WordPress.com Gutenberg plugin allows for the Image Width attribute to be edited.

**Comment by cuemarie** [comment]
Please find updated triage notes below

<strike>📌 SCRUBBING : RESULT 
- Tested on Simple: Could Not replicate
- Tested on AT: Could Note Replicate
- Tested on Self-hosted: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Not able to replicate. The `Width` attribute was found under **Dimensions** within the block editor across simple, AT, and self-hosted sites.

AT Site, Gutenberg Version 14.7.1, Theme: Zoologist

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)</strike)

**Comment by masperber** [comment]
There is a discrepancy between the WordPress.org documentation for this block and the behavior on WordPress.com when the WordPress.com Gutenberg plugin is activated. See https://wordpress.org/support/article/site-logo-block/#block-settings

There should be an Image Width slider in the Block settings. See image below, from the above link.

<img width="257" alt="Screenshot 2022-12-13 at 6 28 36 PM" src="https://user-images.githubusercontent.com/12906034/207467398-1657bda4-4984-4756-b2b2-e808bcae4a1d.png">

This slider does not appear when the WordPress.com Gutenberg plugin is active.

Further, the Width buttons Fit, Fill, Fixed do not appear to have any effect on the Site Logo Block in my testing.

**Comment by cuemarie** [comment]
Thanks so much for that update, @masperber ! Will retriage here in a few

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on AT: **Replicated**
- Tested on Self-Hosted: **Replicated**
- Replicable on Core? **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- The discrepancy reported between how the Site Logo block works with the Gutenberg plugin on/off is replicable. Further, when adjusting the Width parameters available when the Gutenberg plugin is activated, it's not clear what should be happening there.
- **These differences present in the same way in a Self-Hosted environment with Gutenberg 14.7.1 active/deactivated**

AT Site, **Gutenberg Version 14.7.1 Active**, Theme: Zoologist

https://user-images.githubusercontent.com/27249804/207468462-de73a4ce-1ad0-4ca7-b7b4-dd7fa12967e5.mp4

AT Site, **Gutenberg deactivated**, Theme: Zoologist

https://user-images.githubusercontent.com/27249804/207468535-83ddab24-4710-4637-a5ba-18f9609708cb.mp4

The behavior when the plugin is active does not reflect the WordPress.org or WordPress.com support guides on the **Site Logo Block**:

- https://wordpress.org/support/article/site-logo-block/#block-settings
- https://wordpress.com/support/site-editing/theme-blocks/site-logo-block/#block-settings

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Reported in `/gutenberg`: https://github.com/WordPress/gutenberg/issues/46518
- Added to Cross-Repo watch-list

📌 Message to Author
- Thanks for the help understanding the issue a bit better, @masperber ! Those screenshots helped me see what you meant! 👍

**Comment by ckmccoy2** [comment]
38768968-hc with theme twenty-twenty-three

**Comment by thekingsprojects** [comment]
Another case with the Tsubaki theme: 38817321-hc

Noting here that I reactivated Gutenberg for the customer after they made the size change, and according to them the change remained in effect, so Gutenberg *should* only need to be temporarily deactivated for this workaround.

**Comment by happychait** [comment]
Updated this bug title to reflect that with Gutenberg plugin active, the resize handles are unavailable as well, besides the missing Image Width box from the block settings panel.
![Missing resize handles](https://user-images.githubusercontent.com/1519466/209070740-39dcaf4f-3dc4-443c-97f6-31c90b8f49ed.png)

**Comment by cuemarie** [comment]
Per the Core report ( https://github.com/WordPress/gutenberg/issues/46518 ):

> The issue was fixed via https://github.com/WordPress/gutenberg/pull/46214 and should be part of the Gutenberg 14.8 release. Initial report https://github.com/WordPress/gutenberg/issues/46198.

So we should see this resolve once 14.8 hits WordPress.com sites!

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

I can't replicate the issue anymore. I was able to resize the site logo and see the settings as expected. 

**Simple**
![hzkJbO.png](https://github.com/Automattic/wp-calypso/assets/67279475/2e02131d-2c34-40c5-8166-6959ecc333f2)

**AT**

![Q69qJ9.png](https://github.com/Automattic/wp-calypso/assets/67279475/ff4f53bc-8757-4726-8ca9-93f4c261c811)

📌 ACTIONS
- Closed as no longer relevant (issue resolved by issue https://github.com/WordPress/gutenberg/issues/46518)
