### ISSUE TITLE
Baskerville 2: Posts not displaying newest to oldest on simple site 

### ISSUE THREAD

**Issue by tavilla61** [Automattic/wp-calypso#71096]
_Note - this report is closed as `By Design` because the reported behavior is intentional; Baskerville 2 displays posts in chronological order, but that's based on the vertical order of the posts on the page, not just left-to-right by row. That means the screen size and length of content in a post's title/excerpt can change the visual order of the posts. -cuemarie_

---

### Quick summary

The site has a Personal plan and is using Baskerville 2. It's set to display latest posts on the Home page, and until recently they were being displayed in order of newest to oldest. 

User said occasionally one post would be out of order, but clearing the browser cache fixed it. 

Today, several posts are out of order. There are no sticky posts, and I don't see anything that would cause this, but since there was a recent core update, I'm wondering it has something to do with that. 

<img width="1536" alt="Screen Shot on 2022-12-12 at 16-04-34" src="https://user-images.githubusercontent.com/33466168/207176564-f57f537c-74c8-4cdc-b4a4-47a90eea1e66.png">

### Steps to reproduce

1. View site https://how-i-run-it.com/
2. Checked the order the posts were published.
3. Looked for any sticky posts or shortcode that would interfere
4. Simple site, so no plugin conflicts
5. Theme isn't retired

### What you expected to happen

I expected the posts to display with the newest posts first.

### What actually happened

Posts on the Home page are displayed out of order (according to their published by date). 

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

None

### Severity

One

### Available workarounds?

None

**Comment by ClassicRKR27** [comment]
An update on this; the user found that refreshing the page resolves the issue, and I was able to confirm on my end - so for whatever reason, it won't display correctly when first visiting the site but after a refresh it corrects itself and that update does cache with the browser.

Essentially, as soon as a visitor resets the homepage the issue will be fixed until they clear their browser cache.

Edit: Also, it seems like this may only be affecting the Chrome browser based on my testing. Safari and Firefox loaded the correct order without the need for a refresh.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could Not Replicate
- Tested on Atomic: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

**Steps taken to try to replicate in a test environment**

- On a test site with at least 10 posts, activate Baskerville 2
- Set homepage to display latest posts
- View front page

While a bit confusing at first, I believe Baskerville 2 is displaying posts in order, but that's based on the vertical order of the posts on the page, not just left-to-right by row. That means that the length of posts earlier in the page impact the order of posts later on the page, like so:  

![Markup on 2022-12-24 at 10:27:43](https://user-images.githubusercontent.com/27249804/209446045-426100f2-2cf1-4287-8740-df78a744a750.png)

In my tests, refreshing the page did not change the order of the posts.

With the user site above, I also did not see incorrect order on the posts - but it's possible that images loading slowly or timing out (until a refresh) would cause the posts to change their order after the page first loads. Tested in Chrome and FireFox.

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @tavilla61 Always make sure to exclude any user-specific information in your screenshots or details.
- Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

**Comment by ClassicRKR27** [comment]
So, it turns out that this has cropped up again; I have another report of it here: 6624550-zd-a8c

The previous workaround of refreshing the page is not working, so I'm going to suggest that they either switch their theme or create a page using the Blog Posts block to see if that resolves the issue.

**Comment by cuemarie** [comment]
Hey @ClassicRKR27 ! ~Can you double check to see if that user's issue is actually reflecting this?~

I checked out the user's site, and it does appear that their posts page is behaving as intended:

> Baskerville 2 is displaying posts in order, but that's based on the vertical order of the posts on the page, not just left-to-right by row. That means that the length of posts earlier in the page impact the order of posts later on the page
     - [triage notes above](https://github.com/Automattic/wp-calypso/issues/71096#issuecomment-1364560249)

This issue was closed as `By Design`, because the initial report is reporting the correct (if sometimes confusing for users) behavior of the theme. 

📌 ACTIONS
- Closed as by design
