### ISSUE TITLE
[Tech foundations] Alignment of Design Picker & Showcase APIs/mechanics/code

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#71092]
# Description
Part of ongoing theme showcase and design picker improvements.

![Image](https://user-images.githubusercontent.com/5665959/207144730-43d467ac-88a3-4174-a8f7-4fa0b737baee.png)

# Acceptance Criteria
- [ ] Reasonable updates to APIs and code to improve maintainability
- [ ] Caution used in what improvements are truly necessary

# Dev Tasks
- [ ]  task/PR 1
- [ ]  task/PR 2

# Testing 
* go to site
* instruction 1
* instruction 2

## Related
Project Thread: pNEWy-eFy-p2

**Comment by autumnfjeld** [comment]
@Automattic/lego   How urgent is this? Are there known tasks we should begin soon (within weeks)?

**Comment by taipeicoder** [comment]
Closing this as a lot of alignment work has now shifted to T-Rex. See: paYJgx-3Eb-p2
