### ISSUE TITLE
Create a Breadcrumb block 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#71121]
### What

Create a breadcrumb block. 
This is a feature request from 36874974-hc. 

### Why

For sites without WooCommerce or don't need it, a breadcrumb block will show site visitors which section of the site they're on and can easily go back to the previous sections.

**Comment by simison** [comment]
I'll close this in favor of having the suggestion in Gutenberg repo instead: https://github.com/WordPress/gutenberg/issues/21943

There's even some work already done in https://github.com/WordPress/gutenberg/pull/32500 (cc @andrewserong)
