### ISSUE TITLE
Editor Performance: Typing becomes extremely slow / laggy if Columns block contains several blocks of various types

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#71120]
### Quick summary

When there is a Columns Block added to the page and contains several blocks of various types (e.g. Heading, Paragraph, List but it could be others too), typing becomes very slow. 

https://user-images.githubusercontent.com/39308239/207266780-b2c2c7ee-29e1-45d6-b470-df2048be5f73.mov

### Steps to reproduce

1. Add a Columns Block
2. Add several blocks of various types (e.g. Heading, Paragraph, List) into it. You can copy these:

```
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Heading</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>one</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>two</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>three</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Heading</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>one</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>two</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>three</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Heading</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>one</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>two</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>three</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```

3. Type anything anywhere on the page

### What you expected to happen

No lag in typing speed and performance

### What actually happened

An extreme lag and slowness in typing. Typed letters take seconds to appear.

### Context

Started with a user report in 5779567-zd-woothemes (screen recording present) and continued with testing on my own Simple Site. I suspect it started after the recent Gutenberg update to v14.7.1.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No. Tested on P2020, Exford.

### Browser, operating system and other notes

macOS Monterrey 12.6.1 with Google Chrome Version 107.0.5304.121 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

None

**Comment by zdenys** [comment]
5785364-zd-woothemes

> I logged out and logged in again, but the editor is still super lagging when typing (with only one tab open). The letters don't appear at all until I finish typing a whole sentence, then appear all at once after like 5 seconds. I tried Safari and it was better than Chrome, but there was definitely a lag when typing.

**Comment by formosattic** [comment]
Maybe related or same issue, this previous report of lag in the editor, especially with Chrome MacOS, and with long-form content: https://github.com/WordPress/gutenberg/issues/22822.

**Comment by mxhassani** [comment]
> Maybe related or same issue, this previous report of lag in the editor, especially with Chrome MacOS, and with long-form content: [WordPress/gutenberg#22822](https://github.com/WordPress/gutenberg/issues/22822).

I believe that's what the user here is facing: 29079642-hc

**Comment by suyogyashukla** [comment]
38453587-hc - user reported the issue in chat.

**Comment by kspilarski** [comment]
This is the same case for 5783559-zen.

**Comment by ariel-maidana** [comment]
Another report (Site Editor): 5787072-zd-woothemes

**Comment by synora** [comment]
Another user 5787047-zen. 

They encountered the issue when they were trying to edit the "This Week's Retailer" page. They were trying to add content to the Classic Block, which contains a ton of content. 

There's also a Cover Block there that they do not use and within it, there are a ton of Paragraph Blocks. When I deleted Cover Block, the Classic Block was deleted as well. Undoing the deletion also brought back the Classic Block.

**Comment by upwardmomentum84** [comment]
Another report 38644258-hc

**Comment by Jaccuse** [comment]
Another case in 38720308-hc

They also have some pages without columns blocks that are seeing the same problem.

**Comment by Jaccuse** [comment]
Another one 29406626-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Editor performance before and after adding the sample content above was noticeably different. Here's a recording of my test for a second example:
- Theme activated on site: **Twenty Twenty Two**

https://user-images.githubusercontent.com/27249804/207467022-293e1bf5-3150-4532-98fe-74fe46e0f04c.mp4

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by fullofcaffeine** [comment]
Discussion continues in p1670974159155589/1670921285.336889-slack-CB0B2G43X.

**Comment by jorpdesigns** [comment]
Reported in 38747194-hc

- [ ] Follow-up: 5788990-zd-woothemes

**Comment by zdenys** [comment]
38543070-hc

**Comment by rakshitwesley** [comment]
Reported here: 28127814-hc
Follow-up: 5789290-zd-woothemes

**Comment by dragstor** [comment]
38753238-hc

**Comment by tyxla** [comment]
It appears like there's a fix in https://github.com/WordPress/gutenberg/pull/46527 and the performance regression might have been introduced in https://github.com/WordPress/gutenberg/pull/45364.

**Comment by aquaspy** [comment]
Thank you so much for this issue! I experience the same issue.

**Comment by CodeAllNightNDay** [comment]
I think it's an issue here. 38761291-hc

**Comment by jromales** [comment]
Another report in 5785898-zd-woothemes

**Comment by jorpdesigns** [comment]
Reported in 38586686-hc

- [ ] Follow-up: 5792370-zen

**Comment by noahtallen** [comment]
I believe this has been resolved now. Please let us know if not, and we can re-open!
