### ISSUE TITLE
Add a tag across writing prompts

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#71134]
## Description

When a customer manually clicks a writing prompt promo (either in a notification, email, or on my home), we should add a unified tag to the post so that folks can see other peoples responses.

Props to @MindyPostoff for pushing this idea forward.

**Comment by creativecoder** [comment]
This is already in place. The tag `dailyprompt` is added when responding to a prompt on web and mobile. On web, it's triggered by adding the `answer_prompt={prompt-id}` to the link to start a new post in the editor, which we do for My Home prompt cards, and plan to do with notifications and emails, when they are released.
