### ISSUE TITLE
Custom Title Formats: Improve editing UX

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#7113]
When editing the title formats in **My Sites** > **Settings** > **SEO**, it's somewhat awkward and unexplained how the editing process should work. "Chips" or "tokens" can be selected from the list that appears when typing in the edit box, but arbitrary text can also be inserted, including space characters. The only forbidden character is a `,` which immediately terminates the current chunk of plain text. Also, once a chunk of text has been entered, it can only be deleted, not edited again.

This component was built using the `<TokenField />` and that has turned out to have a relatively poor match for the functionality we need. At this point, it's possible that we could address this issue by replacing that component altogether and spend less effort than fixing these inconveniences, but I'm not certain of that.

**Comment by roundhill** [comment]
@dmsnell we can probably close this one eh?

**Comment by dmsnell** [comment]
Yes @roundhill I think we can! In contrast to how it felt before, I am very pleased with the results of the UX redesign.
