### ISSUE TITLE
SEO Preview: Appropriate show site vs post previews

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#7114]
The SEO preview currently displays the previews for sites and posts wherever we have them, or it assumes we want to see the site preview.

This should know whether or not we opened the `<WebPreview />` from **My Sites** directly or if we instead opened it from the editor. Pending that, it should show the appropriate type of previews.

**Comment by folletto** [comment]
Is this the tracking issue for the bug of showing the Social Preview outside the Editor Preview (i.e. in Themes → ••• → Live Demo?

![screen shot 2016-08-01 at 19 32 10](https://cloud.githubusercontent.com/assets/4389/17304690/b206e86e-581e-11e6-955b-d5302c294749.png)

**Comment by dmsnell** [comment]
Not really @folletto. We debated about showing it outside of the editor preview, so this isn't a bug as much as it is a choice. We didn't have a strong conclusion on it either. The reason for showing it in the theme selector is that themes have control over how the titles and excerpts are generated, which has an effect on the shared items. I thought it was reasonable to be able to provide the users the ability to see how their choice of theme would impact how their shares would look on Facebook/Twitter/etc…

**Comment by folletto** [comment]
The component is a generic `WebPreview`, while the "Social Sharing" icon is contextual to content and the specific intent of the tool that triggers it (specifically, the Editor). 

Even in the scenario where we might want to include it in Themes Demos (my opinion is currently against it) the fact that the component is a _generic_ preview and not a specific _content sharing_ preview means that it's not expected to show something like that unless explicitly desired by the action it's being triggered.

So, if not properly modular, should be at least off by default.

**Comment by dmsnell** [comment]
@folletto there's going to be a way to turn it on or off. It's not too general right now though as I think we only use it for site preview from **My Sites**, post preview from the editor, and site preview in themes.

**Comment by folletto** [comment]
...which is already a quite broad set of usages and intents, don't you think? ;)

**Comment by dmsnell** [comment]
well, I'm not going to argue whether or not it should be on by default, as we're pretty much on-the-fence about showing it in the theme preview, but it's still just `site` or `post`, so not that broad.

**Comment by dmsnell** [comment]
Closed in #7266
