### ISSUE TITLE
Create a page listing all component libraries and why you might use them

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#71143]
It's unlikely we'll unify all of our component libraries. At the very least, it'd be useful to document all of them in one place.

We can pull from pdKhl6-1hu-p2#comment-1413

**Done is:**
* All of the component libraries are documented to one page. Each should have a description explaining when you might use it, as well as some details about how to access it.
* (If possible) we pull in a list of the components in each library.

**Comment by tyxla** [comment]
Thanks for starting work on this, @danielbachhuber!

I think the comment you linked can be used to start that documentation page.

Me and the rest of Team Calypso are happy to aid with reviews, council, and whatever else you might need.
