### ISSUE TITLE
Bloganuary LP i1

### ISSUE THREAD

**Issue by Noemish** [Automattic/wp-calypso#71145]
Landing Page creation for Bloganuary

Needs to be based on the latest designs for LOHP

[Design file](2rvgnGtEvEzefwOu1i3U48-fi-413%3A2480&t=Zqq9CkPMbUQhMljz-1)

Main designer: @garretsteider-a8c 
Support designer: @Noemish

**Comment by Noemish** [comment]
Latest update:

- Design [file](https://www.figma.com/file/2rvgnGtEvEzefwOu1i3U48/Bloganuary-2023?node-id=413%3A2480)
- P2 comment

**Comment by garretsteider** [comment]
Latest Update:

- Updated website based on comments in Figma
- Image assets are now retina ready.
