### ISSUE TITLE
LOHP LP i5

### ISSUE THREAD

**Issue by Noemish** [Automattic/wp-calypso#71156]
Second iteration from [LOHP i1 (MVP) version](https://github.com/Automattic/wp-calypso/issues/70441)

Specs from @pablohoneyhoney of this 2nd iteration:

- Updates for this iteration will be more based on visual refinements (design and animations) and a review of copies and content

- We'll work on new videos and anything that requires new audiovisual content for i3

[P2](p9Jlb4-7A9-p2) | [Figma](jLDMqw1PAvxtcj9eoNwsHm-fi-4234_118830)

Main DRI: @jrdnhllr 
Support designer: @Noemish

**Comment by jrdnhllr** [comment]
Dropping this reference here: https://quentinhocde.com for when we're wanting to revisit a more animated depiction of our theme offerings (about halfway down).

**Comment by Noemish** [comment]
Amazing ref! Thanks @jrdnhllr

**Comment by jrdnhllr** [comment]
Another reference: 

Love the way Gutenberg depict **and demonstrate** the editor here!

https://wordpress.org/gutenberg/

**Comment by jrdnhllr** [comment]
LOHP i2 – suggestions on areas to improve jLDMqw1PAvxtcj9eoNwsHm-fi-3848_75286

**Comment by Noemish** [comment]
jLDMqw1PAvxtcj9eoNwsHm-fi-5572_113962
p9Jlb4-7M1-p2#comment-9128
