### ISSUE TITLE
SEO Preview: Audit and fix mobile issues

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#7115]
Known issues:

 - [ ] `<VerticalMenu />` is too wide for narrow screens, replace with different component when appropriate.

If you run an audit over the SEO preview pieces and notice any issues, please add them to the checklist above.

cc: @roundhill @mtias

**Comment by roundhill** [comment]
Here's what I'm thinking for the narrow view:

<img width="405" alt="screen shot 2016-07-28 at 10 48 30 am" src="https://cloud.githubusercontent.com/assets/789137/17223336/faf28194-54b0-11e6-8bba-c97ebb8e346c.png">

It's a little weird to force a 'vertical menu' to go horizontally, but it does work fine.

**Comment by dmsnell** [comment]
@roundhill looks good to me. If we eventually add more previews, maybe we would need to switch to the icons only? @drw158 had originally proposed the social icons each as tabs in the `<WebPreview />` so it wouldn't be too far off from his idea if we did this.

**Comment by roundhill** [comment]
That's a good idea, I'll hide the text when on mobile. Also, is that the Google+ logo there?

**Comment by dmsnell** [comment]
> is that the Google+ logo there?

yes because I couldn't find a simple Google `G` logo in the Social Logos. I think we need a new icon for it.

**Comment by folletto** [comment]
Why does the menu needs to shift horizontally instead of using the same two pages view as the navigation or customizer, which is a standard pattern we already use?
