### ISSUE TITLE
CPT: When deleting a post fails, it is not returned to the Trashed list

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#7116]
In order to reproduce this issue you'll need to make delete requests to the API fail.  The cleanest way I know of to do this is to sandbox public-api.wordpress.com and apply this patch: 152f0-pb

1. Start with one or more trashed posts in the CPT posts list.
2. Delete the post using the ellipsis menu and confirm the deletion.
3. Observe notice "An error occurred while deleting ..." but the post is not restored to the "Trashed" list.
4. Refresh the page and the post will re-appear in the list.

This is only an issue with the CPT listing screen, not the default Posts listing screen.

Recording:

![delete-failure-not-restored](https://cloud.githubusercontent.com/assets/227022/17201103/eb417bca-5450-11e6-8cf8-c7a73e62a761.gif)

**Comment by aduth** [comment]
This may generally lead into devising an approach for failure rollback.
