### ISSUE TITLE
Remove confirm prompt from FSE plugin once Coming soon is moved to Jetpack

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#71180]
The prompt was added in https://github.com/Automattic/wp-calypso/pull/69331

Related:
- https://github.com/Automattic/wp-calypso/issues/52596
- https://github.com/Automattic/jetpack/pull/27815
- https://github.com/Automattic/wp-calypso/pull/71012

**Comment by autumnfjeld** [comment]
@miksansegundo  Is this issue still relevant?  Has coming soon been moved to Jetpack?

**Comment by taipeicoder** [comment]
Closing this issue since the coming soon feature is now moved from ETK.
