### ISSUE TITLE
Email Subscription Ownership Notice Confusion on Domain Transfer 

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#71182]
### Quick summary

A and B are admins on the site
A is the domain connection owner
B added a domain transfer-in subscription (incomplete)

When B tries to add an email address with the domain, they can't, which is expected (only A can), BUT, the notice is confused and shows " Only B can add email, please login with that account "

![image](https://user-images.githubusercontent.com/81776920/207540957-270967f3-28d0-4c7e-94b9-1539b7537b8f.png)

The notice should be something like "only A can add an email subscription" or "the domain is pending transfer".

### Steps to reproduce

1. have two accounts admin on the same site
2. Add a domain connection with account A 
3. Add a domain transfer-in with account B for the same domain name
4. Try and add an email subscription while logged in as B

### What you expected to happen

To be informed on A can add an email subscription or that the domain is pending transfer 

### What actually happened

I am asked to login with B while I am already logged in

### Context

38682729-hc

### Reproducibility

None

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- So far, I'm unable to replicate this, as I can't start a transfer from the account that doesn't own the domain. Here's where I get stuck:

![Markup on 2022-12-24 at 10:38:56](https://user-images.githubusercontent.com/27249804/209446402-90253e97-d94e-4ff3-964e-6d52efeb1d2c.png)

Without a transfer, the Email page shows the correct account:

![Markup on 2022-12-24 at 10:41:03](https://user-images.githubusercontent.com/27249804/209446417-4b6ed98d-6ea6-4e70-9cab-74eba97706de.png)

📌 ACTIONS
- Await author feedback

📌 Message to Author
- @mxhassani were you able to replicate this issue in a test environment?
- Also, always make sure to exclude any user-specific information in your screenshots or details. Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

**Comment by vajrasar** [comment]
@mxhassani please re-check this and re-open if the issue persists.
