### ISSUE TITLE
FSE: Not able to set custom Block Spacing value on Simple sites

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#71183]
### Quick summary

Not able to set custom Block Spacing value in FSE. On clicking the Save button, it goes back to the default value. I was able to reproduce it with Rainfall, TT3 and TT2 on Simple sites.

### Steps to reproduce

1. On a simple site, activate an FSE theme.
2. Go to Appearance > Editor > Styles > Layout.
3. Change Block Spacing value.
4. Save the changes.
5. You will notice it changes to the default value.

Screen recording: 

![Screen Capture on 2022-12-14 at 09-07-17](https://user-images.githubusercontent.com/33957570/207558982-d2a67855-d69e-49f3-89a5-eecc909f0cc4.gif)

### What you expected to happen

Clicking on save button should save the Block Spacing value we set. 

### What actually happened

Block Spacing value reverted to the default value.

### Context

User report: 38727726-hc

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

FSE themes

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Shared this CSS: 

/* Make block space 0 | 38727726-HC NJ */

.wp-site-blocks > * + *{
margin-block-start:0px;
}

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: Could Not Replicate
- Tested on Self-hosted: Could Not Replicate
- Replicable on Core?  No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Issue presented exactly as described above. Any changes made to the `Block Spacing` field under Appearance > Editor > Styles > Layout are erased upon saving, in Simple sites only.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by villanovachile** [comment]
Another report: 36468939-hc

**Comment by goblinartificer** [comment]
Reported also in 39168909-hc today

**Comment by jartes** [comment]
Another report on 38762453-hc

Shared the CSS code as a workaround. Thanks for that!

**Comment by maciejpilarski** [comment]
Another report on 6078448-zd
Personal plan CSS fix not possible.

**Comment by annezazu** [comment]
I tried replicating this on a simple site and wasn't able to:

https://github.com/user-attachments/assets/83751f82-2684-493d-bb59-32a3d756e826

I don't see further reports of the problem and I can't see any related issues in the Gutenberg repo so I'm going to close out.
