### ISSUE TITLE
Gifting: Add a i or ? icon to the banner

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#71206]
The icon should link to the en.blog post for the feature, in a new tab/window.

Discussed here: pb5gDS-2nL-p2

**Comment by lupus2k** [comment]
Is this the correct link for the icon?
https://wordpress.com/support/gift-a-wordpress-com-subscription/

**Comment by candy02058912** [comment]
> Is this the correct link for the icon?
https://wordpress.com/support/gift-a-wordpress-com-subscription/


That was the link I was thinking about 🎁

**Comment by allilevine** [comment]
> > Is this the correct link for the icon?
> > https://wordpress.com/support/gift-a-wordpress-com-subscription/
> 
> That was the link I was thinking about 🎁

[The blog post link](https://wordpress.com/blog/2022/12/02/give-the-gift-of-wordpress-com/) was mentioned here: pb5gDS-2nL-p2

But the support article makes sense to me, since this is a help icon.

**Comment by kellychoffman** [comment]
Design:

<img width="841" alt="Screen Shot 2022-12-21 at 2 09 49 PM" src="https://user-images.githubusercontent.com/5835847/209011821-125f549d-a77d-4627-8843-5eb2d7f0b950.png">

icons: http://automattic.github.io/gridicons/
`help-outline` `is-small`

After much exploration, adding a dismiss icon in a space this small does not work. Instead, we should ensure the instructions for how to disable shows up in the support doc.
