### ISSUE TITLE
[Bug]: Navigation block is not rendered in editor if default menu is selected (simple sites only)

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#71221]
### Quick summary

When I tested on external wordpress sites and on my atomic site, the default behaviour of the "Navigation" block is to default to displaying the first available existing menu, and render a block outline in the editor like so:

##### Navigation in non-wpcom editor
<img width="1728" alt="Screen Shot 2022-12-15 at 8 53 13 am" src="https://user-images.githubusercontent.com/22446385/207732780-b4a2bc49-2999-4854-b91d-d5e2891d8afc.png">

On wpcom simple sites, the navigation block's default behavior seems to have been changed so that:
  * No menu is selected by default
  * If no menu is selected, the Navigation block is not rendered in the editor
  * If no menu is selected, the published page will render a default menu including a link to each page in the site
  
##### Navigation in wpcom editor
<img width="1728" alt="Screen Shot 2022-12-15 at 8 52 21 am" src="https://user-images.githubusercontent.com/22446385/207733082-b2a24f50-dc06-43f5-830b-90cdc587d54d.png">

##### Navigation in wpcom with no menu selected on published page
<img width="1728" alt="Screen Shot 2022-12-15 at 8 58 44 am" src="https://user-images.githubusercontent.com/22446385/207733495-2129133b-95c5-4380-862e-5a0d4afe7583.png">

If a menu _is_ selected, the editor will render a preview of the Navigation Block with those menu items.

###### Navigation in wpcom editor with menu selected
<img width="1728" alt="Screen Shot 2022-12-15 at 8 59 56 am" src="https://user-images.githubusercontent.com/22446385/207733707-6ee466e3-f258-47d3-b9ba-3b3e5b035448.png">

### User impact

This came up in a support interaction where the user didn't know how to edit the items in their footer menu. They didn't realize that their footer menu was the Navigation block which wasn't visible in the editor because it had the default menu selected.

5787899-zd-woothemes

### Solutions
We could either:

* Default to selecting the "Primary Menu", this would sidestep the issue. OR
* Pull the default menu (all pages) and render it in the editor like we when a menu is selected. OR
* Remove whatever customization's are causing this? it doesn't happen on my external wordpress site or on my atomic test site.

### Steps to reproduce

Using a simple site with several pages:
Go to the editor.
Insert a "Navigation" block, do not select a menu.

### What you expected to happen

The Navigation block is rendered in the editor.

### What actually happened

The Navigation block is not rendered in the editor.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by vinnykaur** [comment]
One more in 38567824-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Could Not Replicate**
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested AT and Simple, adding a Navigation block to an empty post as well as to the editor. In all cases, the Navigation block rendered a default menu as expected. 

**AT Example (Site Editor)**

https://user-images.githubusercontent.com/27249804/209447208-7b3da4f4-c1f2-4b3f-a590-d103c95e5fa6.mp4


**Simple Example (Site Editor)**

https://user-images.githubusercontent.com/27249804/209447201-4dc3af13-bed2-4451-a217-11e88ac4d4a4.mp4


📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
