### ISSUE TITLE
Design Picker: The 3rd generated design in the vertical tab is misaligned

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#71225]
## Description
As mentioned in the title, the third generated design in the vertical tab is misaligned when the pattern assembler CTA is present. See screenshot for reference:

![Image](https://user-images.githubusercontent.com/797888/207773741-7acc9197-e3ee-4cee-a31d-a457d1ee7937.png)

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/71266
