### ISSUE TITLE
Integrate Pexels and Google Images to Gutenberg media sidebar

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#71232]
Gutenberg (since 14.7) has [a new "media" tab](https://github.com/WordPress/gutenberg/issues/44496) in the inserter sidebar:

<img src="https://user-images.githubusercontent.com/87168/207824064-9ab59549-92c1-4e2a-9c69-c32c8c2e9aec.png" width="500" alt=""/>

Since then, the sidebar also has [OpenVerse available](https://github.com/WordPress/gutenberg/issues/46222).

It would be good to add WP.com's Google Photos and Pexels media sources to this sidebar.

Currently those image sources are available in the media block:

Media block | Media modal
-------|------
 <img src="https://user-images.githubusercontent.com/87168/207824405-996e7cbd-f23b-40d1-b982-7556e17f4dd3.png" width="400" alt=""/> | <img src="https://user-images.githubusercontent.com/87168/207825330-6f74cde4-9d2f-4e4c-a840-58e14526f8d1.png" width="400" alt=""/>

The "calypso media modal" which will stop functioning in the editor as 3rd party cookie support goes away, and once we finally remove the Calypso-Gutenberg iframe:

VideoPress doesn't currently play with the sidebar, it's on their radar but [isn't being worked on](https://github.com/Automattic/jetpack/issues/28651) however they have carried out a useful exploration - pe4Cmx-LC-p2. We don't need to work on this but we do need to be aware that they (and other unknown third parties) will follow our footsteps.

Next steps:
 - [x] Open/find an issue in GB repo about making the sidebar extensible
 - [x] Review any existing proposals, or create a new one for how extension could work - do this in the open
 - [x] Open a PR adding extension points
 - [x] Add Pexels and gphotos extensions to wpcom (or calypso/jetpack etc)

**Comment by ianstewart** [comment]
> On .com there's currently some integration problem as the tab doesn't show up.

Looks like this part works now at least.

**Comment by simison** [comment]
VideoPress is experimenting with the sidebar too pe4Cmx-LC-p2

**Comment by dsas** [comment]
Dropped this from forge roadmapping because https://github.com/orgs/Automattic/projects/472/views/38?groupedBy%5BcolumnId%5D=Status&pane=issue&itemId=27081286 is tracking that

**Comment by dsas** [comment]
The VideoPress P2 linked above explains roughly what we need to do, though it looks like adding to `inserterMediaCategories` is still not possible - it's a [private/experimental setting](https://github.com/WordPress/gutenberg/blob/1ae8864e338c12930466461a5366802faa954f13/packages/block-editor/src/store/private-actions.js#L15). @ntsekouras are there any plans to change this? Is there anything that we could do to help?

**Comment by ntsekouras** [comment]
Definitely we need to make an API for that, but right now we're very close to the new WP release. We should start working on this early to be definitely ready for the next one.

**Comment by ntsekouras** [comment]
It's a long shot to have it ready in just a few days for `6.3`, but I [opened a PR ](https://github.com/WordPress/gutenberg/pull/51542)about making the media categories extensible. I'd appreciate some testing there if any of you find some time 😄

**Comment by simison** [comment]
WP.com runs Gutenberg for all sites so it'd be fine if it's not in 6.3 yet?

**Comment by ntsekouras** [comment]
>WP.com runs Gutenberg for all sites so it'd be fine if it's not in 6.3 yet?

Oh, that's great then!

**Comment by dsas** [comment]
Uploaded @ntsekouras PR to my wpcom sandbox and from the wp-admin editor I'm now able to run some hacked together pexels fetch

```js
wp.blockEditor.registerInserterMediaCategory( {
	name: 'pexel13',
	labels: {
		name: 'Pexels13',
        
	},
	mediaType: 'image',
	async fetch( query = {} ) {
		// /wpcom/v2/sites/216813947/external-media/list/pexels?_envelope=1&number=20&path=recent&search=mountain&_gutenberg_nonce=de7555b5f0&_locale=user

		const url = 'https://public-api.wordpress.com/wpcom/v2/sites/216813947/external-media/list/pexels?_envelope=1&number=20&path=recent&search=mountain&_locale=user';
	
		const response = await wp.apiFetch( {url: url} );
		const results = response.media;
		return results.map( ( result ) => ( {
			...result,
			// If your response result includes an `id` prop that you want to access later, it should
			// be mapped to `InserterMediaItem`'s `sourceId` prop. This can be useful if you provide
			// a report URL getter.
			// Additionally you should always clear the `id` value of your response results because
			// it is used to identify WordPress media items.
			sourceId: result.ID,
			id: undefined,
			caption: result.caption,
			previewUrl: result.thumbnails.thumbnail,
			url: result.URL
		} ) );
	},
	getReportUrl: null,
	isExternalResource: true,
} );
```

and it works!

There's something going on with [`jetpack-layout-grid`](https://github.com/Automattic/block-experiments/tree/master/blocks/layout-grid/src) that I need to investigate, but I assume that's to do with a different gb trunk change, not Nik's diff

**Comment by dsas** [comment]
The current pexels code lives in [jetpack](https://github.com/Automattic/jetpack/blob/be09b5417a89ca66dbc033af952ec4d705fca840/projects/plugins/jetpack/extensions/shared/external-media/sources/pexels.js#L10) we will have to see how we can extract stuff to supply the `fetch` function for the inserter sidebar API.

**Comment by rcrdortiz** [comment]
Updated the end date since we haven't been working on this because we needed to work on the [GS on personal plans A/B test project.](paYJgx-3tS-p2)

**Comment by rcrdortiz** [comment]
Referencing [this issue](https://github.com/Automattic/dotcom-forge/issues/2514) since they share the same requirements.

**Comment by rcrdortiz** [comment]
We've now released these changes.
