### ISSUE TITLE
Editor: unexpected behavior when editing both lists and blockquotes at the same time

### ISSUE THREAD

**Issue by diegoreymendez** [Automattic/wp-calypso#7123]
#### Steps to reproduce

Just create a new post in Calypso or wp-admin, and start combining lists and blockquotes.  There's a video posted below showing the strange behaviour.
#### What I expected

Blockquotes should not affect lists and lists should not affect blockquotes.
#### What happened instead

In the video you can see how there's a strange interaction between lists and blockquotes.  At some point the list grows to three items without me typing anything.
#### Browser / OS version

Safari 9.1.2, OS X El Capitan 10.11.6
#### Screenshot / Video

https://cloudup.com/czt8DzFKqR6
#### Context / Source

I'm using Calypso and wp-admin to try and define the standard behaviour for [Aztec](https://github.com/wordpress-mobile/WordPress-Aztec-iOS).

**Comment by lancewillett** [comment]
I'm not sure there's anything actionable here (immediately) but I'm glad you reported it to document the strange behavior.

**Comment by rachelmcr** [comment]
This behavior will be superseded by the Gutenberg handling of quotes and lists.

#bug-scrub #pre-gutenburg-bug-purge
