### ISSUE TITLE
Unable to Delete a Site Due to Active Subscription

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#71233]
### Quick summary

Atomic site owners who wish to delete their site see a message to contact support, instead of being redirected to Purchases to remove their subscriptions. We should guide customers to remove their subscriptions first, so they can delete their Atomic sites without HE intervention.

### Steps to reproduce

On an atomic site with an active Business/ eCommerce / Pro plan:

1. Go to Settings → General 
2. Scroll down to the 'delete your site permanently' option
3. Observe the message to contact the support team to delete the site.

### What you expected to happen

I expected to be able to delete my site without contacting support.

### What actually happened

I see this message:
![image](https://user-images.githubusercontent.com/30727666/207825716-9adf30f6-3b69-423b-a3e7-e2fcc7c4c794.png)

### Context

The Close Account flow was addressed by @mpkelly in #57399. The Delete Site flow could be addressed the same way.

Encountered with a customer in #36077448-hc

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Users must contact support to delete their site. We can lessen the burden on support by guiding users to the self-serve flow that already exists.

**Comment by donalirl** [comment]
#32728329-hc

**Comment by mpkelly** [comment]
Hi, @donalirl, good job opening this. I will start on a PR.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated just as described:

<img width="1268" alt="Markup 2022-12-24 at 11 41 45" src="https://user-images.githubusercontent.com/27249804/209447908-3994a032-8e85-4f93-b31c-8d84531368c7.png">

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by mpkelly** [comment]
I've made the changes to allow self-service Atomic deletion https://github.com/Automattic/wp-calypso/pull/71380. After removing the plan, the user must wait a minute before deleting the site, as there is an async job running. A notice is shown while the delete button is disabled.
