### ISSUE TITLE
Baskerville 2: full post showing when front page is set to display excerpts on Atomic

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#71245]
### Quick summary

The theme is not honouring the user option to display Post Excerpts instead of the full post content on the front page and archives. This only happens on Atomic.

### Steps to reproduce

1. On an Atomic Site, activate Baskerville 2
2. In Settings > Reading, set the site to display the latest posts on the front page
3. In Settings > Reading, select "Excerpt" under "For each post in a feed, include".
4. Publish a new post with text contet and add a custom excerpt to it
5. The full post content will show up instead of the excerpt

### What you expected to happen

The theme should show the excerpt instead of the full post content

### What actually happened

The full post context was displayed

### Context

User report:

- [ ] [5793106-zen](5793106-zd-woothemes)

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Baskerville 2

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The More Block can be used https://wordpress.com/en/support/wordpress-editor/blocks/more-block/

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- The posts on the latest posts page in Baskerville 2 are not adjusted by the Feed settings within Settings > Reading, they are instead adjusted using Appearance > Customize > Content Options, as shown here: 

**AT Example**
<img width="1118" alt="Markup 2022-12-24 at 11 50 08" src="https://user-images.githubusercontent.com/27249804/209448096-c92d102e-7688-4b67-852f-3999a9bdafd0.png">

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
