### ISSUE TITLE
Site Editor: Specify the Current Document's Type

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#71275]
The user might not be aware of what kind of document is being edited — especially if unfamiliar with the Site Editor UI.

The Site Editor header displays the current document's name, but not its type.

We should specify the document's type in the header.

For example:

- "Home Template" instead of "Home".
- "Footer Template Part" instead of "Footer".

Note: this probably requires a Core change.

_Originally requested in https://github.com/Automattic/wp-calypso/issues/68953_

**Comment by dsas** [comment]
Saying "Index Template" isn't always exact. You could be editing the footer template part while editing the "Index Template"

Here's a screen grab of that, just displaying the type of the main entity being edited and the existing indicator that you're editing a footer
![image](https://user-images.githubusercontent.com/93301/216733844-9f31f177-7166-4968-8942-88cece48a6f8.png)

And here's one if I make it clear that the Footer is a template part
![image](https://user-images.githubusercontent.com/93301/216733920-f2248fb1-bba7-493d-be9b-8a5b3f09596f.png)

Note that the sidebar might not be displayed, and will not display stuff about template parts once you've selected a block inside that template part.



I _think_ that the first one, while not technically completely accurate, is actually less confusing. It doesn't seem very useful to me but I'm willing to be guided by others.

----

It doesn't help when editing page content inside the site editor though, that would need more work, but probably https://github.com/WordPress/gutenberg/issues/43608 is a better solution there.

![image](https://user-images.githubusercontent.com/93301/216734964-47b63725-4e37-4b05-beef-a79fb9cb2323.png)

**Comment by dsas** [comment]
WIP branch at https://github.com/dsas/gutenberg/tree/try/wayfinding-label-template in case anyone wants to experiment / try this. I'm not wholly sold on anything above as a significant improvement tbh, would appreciate some opinions @Automattic/t-rex

**Comment by mmtr** [comment]
I think this actually needs some design input. I'm not entirely convinced that _just_ appending the type to the name (with the same font style) is a good idea – it looks more confusing to me?

Perhaps we can include these icons to re-inforce the design language used by Gutenberg?

<img width="343" alt="Screenshot 2023-02-06 at 17 17 58" src="https://user-images.githubusercontent.com/1233880/217025781-17358da8-7222-40ee-97b7-cf41c0ed7818.png">

Something like this:

<img width="191" alt="Screenshot 2023-02-06 at 17 20 43" src="https://user-images.githubusercontent.com/1233880/217026286-267a470c-2259-431c-91cf-51e49f0dbb98.png">

Then, we could add the type as tooltips similar to other UI areas:

<img width="179" alt="Screenshot 2023-02-06 at 17 22 14" src="https://user-images.githubusercontent.com/1233880/217026820-79f0f8a7-a603-46e0-9fce-6cf12ef86267.png">

Alternatively, we could be explicit and avoid the tooltips:

<img width="372" alt="Screenshot 2023-02-06 at 17 27 55" src="https://user-images.githubusercontent.com/1233880/217028099-92acb5f5-26d4-46fa-aa89-4db88d06a040.png">

**Comment by Copons** [comment]
> I think this actually needs some design input.

Yes, absolutely!
And even more so if we are pushing changes to Core Gutenberg. 🙂 

> Something like this:
> 
> <img alt="Screenshot 2023-02-06 at 17 20 43" width="191" src="https://user-images.githubusercontent.com/1233880/217026286-267a470c-2259-431c-91cf-51e49f0dbb98.png">

I like this a lot.
It reinforces the visual language used in the site editor's sidebar so that users would get acquainted with it gradually but surely.

The tooltip on the icon might be a good one too.
They are used on every icon in the top bar, and can (usually) be toggled between icon+tooltip and label, so we could have both @mmtr's suggestions! 😄 

---

IMHO, we could just simply open a PR in Gutenberg showcasing one or two approaches, pinging @SaxonF for design review and see what happens. 🙂

**Comment by dsas** [comment]
I opened https://github.com/WordPress/gutenberg/pull/48052 with the icon idea.

I haven't yet added tooltips (information is already accessible though). The obvious solution of just wrap the BlockIcon in a Tooltip didn't work.

**Comment by dsas** [comment]
Closing, upstream are looking to go in a different direction.
