### ISSUE TITLE
[Bug]: Using gutenberg-edge (14.8 rc1) new custom CSS feature doesn't work

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#71273]
### Quick summary

The new Global styles custom CSS feature doesn't work

### Steps to reproduce

1. Create a new site
2. Get a premium+ plan and use e.g. Twenty Twenty-three theme.
3. Open the site editor
4. Open the global styles sidebar
5. Click the new 'Custom CSS' feature at the bottom of the page
6. Paste some style rule in like `h1.wp-block-heading { text-decoration:underline; color: orange; }`
7. Notice that the editor to the left now makes headings orange and underlined ✅ 
8. Press Save and then Save again once the pre-save prompt has loaded

### What you expected to happen

 * The editor to the left to remain as it is - orange underlined headings
 * To see orange, underlined headings when looking at the front-end of the site

### What actually happened

 * The headings are no longer orange or underlined in the editor or on the front-end of the site
 * If I close the CSS panel and reopen it, the CSS is gone!

https://user-images.githubusercontent.com/93301/208151238-b55f3895-aa9e-4821-a4d1-9870bca3459e.mp4

### Browser

Mozilla Firefox

### Context

Testing if global styles gating works with new custom CSS feature

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

There's an error in the browser console: `Uncaught TypeError: t.target.classList is undefined` 

**The HTTP PUT request does include the expected css string but the response doesn't.**

There's nothing in my sandbox error log.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by dsas** [comment]
This doesn't happen in Core on the 14.8 RC tag.

**Comment by dsas** [comment]
Maybe it's not limited to the new custom CSS feature, it also happens when choosing a style variation for example. I choose a style variation, saved it and it half-disappeared. Many of the previews were off too


https://user-images.githubusercontent.com/93301/208157295-260119ad-c565-4938-937e-579937a47147.mp4

**Comment by Copons** [comment]
cc @fullofcaffeine, as this might be an issue for the 14.8 Gutenberg merge if it happens before the holidays.

Wonder if this is the same (or related to) KSES issue that affects gradients ([Core Trac](https://core.trac.wordpress.org/ticket/57322)): https://github.com/Automattic/wp-calypso/issues/71009

See also p1670602379106569-slack-CBTN58FTJ.

**Comment by dsas** [comment]
I'm a superadmin afaik and I was testing as my a8c-self 🤔

**Comment by dsas** [comment]
Global styles created via the newsletter onboarding flow do work!

**Comment by glendaviesnz** [comment]
I just tested with a local install of 14.8-RC-1 and the global styles custom CSS saves as expected.

With Calypso the correct style value is being sent to the API but not returned, so mostly likely being stripped before saving. 

The place to start debugging why this is would be [here](https://github.com/WordPress/gutenberg/blob/release/14.8/lib/compat/wordpress-6.2/class-gutenberg-rest-global-styles-controller-6-2.php#L138). 

In order to work the [WP_Theme_JSON_6_2 ](https://github.com/WordPress/gutenberg/blob/release/14.8/lib/compat/wordpress-6.2/class-wp-theme-json-6-2.php) version of the theme json class needs to be loaded as this includes the addition of `css` as a `VALID_STYLE` [here](https://github.com/WordPress/gutenberg/blob/release/14.8/lib/compat/wordpress-6.2/class-wp-theme-json-6-2.php#L238) - if not the `styles.css` will be stripped as being invalid.

**Comment by glendaviesnz** [comment]
This [patch here](https://github.com/WordPress/gutenberg/pull/46561) needs to go into 14.8 to prevent a PHP warning being thrown if global styles are being updated but no custom CSS is included ... but it looks like this didn't get into RC1. I don't think this would affect this issue though as should just throw a warning and not affect the saving.

**Comment by mmtr** [comment]
I think this is another KSES issue in Core similar to https://github.com/WordPress/gutenberg/issues/45520 and https://core.trac.wordpress.org/ticket/57322.

I can reproduce the issue in Core when I enable the KSES filters with `add_action( 'init', 'kses_init_filters' );`

**Comment by dsas** [comment]
Opened up a Core issue https://github.com/WordPress/gutenberg/issues/46651

**Comment by simison** [comment]
FYI: [revert of the custom CSS to an experiment](https://github.com/WordPress/gutenberg/pull/46663)

**Comment by dsas** [comment]
There's an open [upstream PR that fixes the custom CSS issue](https://github.com/WordPress/gutenberg/pull/46815) that wfm on core. It uses the edit_css cap which we [remap for the customizer custom css](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/custom-css/custom-css.php#L126)

**Comment by mmtr** [comment]
Gutenberg has re-enabled the Custom CSS feature in https://github.com/WordPress/gutenberg/pull/46815 and https://github.com/WordPress/gutenberg/pull/47062 after solving the issues with the KSES filters and the needed capabilities. 

It'll be shipped in the next version (v15.1.0), so let's keep an eye on when it lands on WPCOM to see if it works as expected.

**Comment by mmtr** [comment]
Latest update in paYJgx-2WY-p2.

**Comment by mmtr** [comment]
We've confirmed that the feature remains hidden on Gutenberg v15.1.0 for Simple sites.

I also opened D101145-code to enable it in a safe way.
