### ISSUE TITLE
My Home: Contextual "Update Your Homepage" Task

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#71277]
In the My Home checklist, one of the task prompts to "Update your homepage" with an "Edit site" CTA.

![](https://user-images.githubusercontent.com/1842363/195260525-6df9dbfb-bf53-4bda-9a4c-aa4a53c69324.png)

Copy and CTA should change depending on the theme.

For example:

- Is it a legacy theme? Send to Customizer.
- Is it a full-fledged FSE-enabled block theme providing a homepage template? Send to Site Editor, modifying the homepage template.
- Is it an FSE-enabled theme without templates? Send to Page Editor for the homepage.

Note: please take a look at [this comment](https://github.com/Automattic/wp-calypso/issues/68953#issuecomment-1283454135) that provides pointers to external resources and conversations about this issue.

_Originally requested in https://github.com/Automattic/wp-calypso/issues/68953_

**Comment by mmtr** [comment]
> Is it a legacy theme? Send to Customizer.

I'm not sure about this. Currently, for legacy themes, the task send users to the page editor for the homepage, and the card uses a different copy:

<img width="938" alt="Screenshot 2023-01-12 at 15 50 13" src="https://user-images.githubusercontent.com/1233880/212098617-58c65911-c16d-4f61-a86f-4a24857bbd28.png">

IIRC, this task was added to change the homepage, not the site's design, so we should send users to the appropriate editor where they can update it.

So my suggestion is to apply these changes:

**Legacy theme (e.g. Twenty Seventeen)**

Item | Current | Proposed
--- | --- | ---
Sidebar title | Update your homepage | _N/A: same as currently_
Card title | Update your homepage | _N/A: same as currently_
Description | We've created the basics, now it's time for you to update the images and text. Make a great first impression. Everything you do can be changed anytime. | _N/A: same as currently_
Action text | Edit homepage | _N/A: same as currently_
Action URL | `/page/<site-slug>/<homepage-id>`  | _N/A: same as currently_

**FSE theme (e.g. Twenty Twenty-Three) with a virtual homepage (front page = recent posts)**

Item | Current | Proposed
--- | --- | ---
Sidebar title | Update your homepage | _N/A: same as currently_
Card title | Update your site's design | Update your homepage
Description | We've created the basics, now it's time for you to update the images and text. Make a great first impression. Everything you do can be changed anytime. | _N/A: same as currently_
Action text | Edit site | Edit homepage
Action URL | `/site-editor/<site-slug>`  | _N/A: same as currently. [The site editor opens by default the current homepage of the site](https://github.com/Automattic/wp-calypso/blob/a53a59fc8ea9dda0c9db0cc7cec3f204d72649a5/client/gutenberg/editor/calypsoify-iframe.tsx#L826-L837)._

**FSE theme (e.g. Twenty Twenty-Three) without a virtual homepage (front page = static page)**

Item | Current | Proposed
--- | --- | ---
Sidebar title | Update your homepage | _N/A: same as currently_
Card title | Update your site's design | Update your homepage
Description | We've created the basics, now it's time for you to update the images and text. Make a great first impression. Everything you do can be changed anytime. | _N/A: same as currently_
Action text | Edit site | Edit homepage
Action URL | `/site-editor/<site-slug>`  | `/page/<site-slug>/<homepage-id>`

**Comment by mmtr** [comment]
Posted pekYwv-vo-p2 to get some feedback about what's the best approach here.

**Comment by mmtr** [comment]
These are the next steps according to the feedback discussed in pekYwv-vo-p2:

- For legacy themes:
    - Keep the current “Update your homepage” wording.
    - Keep the current redirect to the page editor.
    - Keep the current behavior that hides the task if the homepage is set to show the latest posts.
    - Keep the current completion logic that requires the page content to be updated or the page_on_front option to be changed.
- For block themes:
    - Keep the current “Update your site’s design” wording.
    - Keep the current redirect to the site editor.
    - Change the behavior to show the task if the homepage is set to show the latest posts.
    - Change the completion logic to mark the task as completed upon clicking on the CTA button (similarly to how the “Edit site design” task from the Launchpad is completed upon loading the site editor).

**Comment by mmtr** [comment]
> For block themes: [...] Change the behavior to show the task if the homepage is set to show the latest posts.

D98360-code

**Comment by mmtr** [comment]
> For block themes: [...] Change the completion logic to mark the task as completed upon clicking on the CTA button

https://github.com/Automattic/wp-calypso/pull/72224
