### ISSUE TITLE
Free Flow - incorporate name generator

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71280]
Intended for work after the setup screen is implemented and the domains screen is removed.

As these pieces come together we will need to update the site creation to use the name generation approach (iirc just different options to the domains endpoint) we want for this flow.

**Comment by agrullon95** [comment]
Calypso changes : https://github.com/Automattic/wp-calypso/pull/71429
WPCOM changes to use domain generation logic on site creation: D96193-code
