### ISSUE TITLE
Stats: Page data fails to load

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#71282]
### Quick Summary

Reported in C1T3N5AMR-slack-p1671086556313499.

### Steps to reproduce

- Exact steps unknown.
- Occurs in `wordpress.com/stats/day/:siteSlug`.

### What you expected to happen

The chart and the stats modules below should load as expected.

### What happened

Chart data never loads. The chart data becomes stuck in a loading state; none of the stats modules load.

![Image](https://user-images.githubusercontent.com/4044428/208170828-70c7e315-6f21-487e-bc44-2528e3a817d2.png)

### Browser

- Google Chrome/Chromium
- Microsoft Edge
- Not Firefox 🤔 

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Logging out of WordPress.com and back in fixes the issue for most users

**Comment by brucea8c** [comment]
User in 5796102-zd-woothemes says that the issue is happening not only on Chrome and Edge, but also on Firefox.

**Comment by jsnmoon** [comment]
I've been testing on Chrome with site 103325115 and noticed this console error:

```
react_devtools_backend.js:4012 An error occurred while running 'mapSelect': Cannot read properties of undefined (reading 'unmapped_url') 
    at HelpCenter (app:///../packages/help-center/src/components/help-center.tsx:44:3)
    at AsyncLoad (app:///./components/async-load/index.jsx:20:5)
    at HelpCenterLoader (app:///./layout/index.jsx:149:3)
```

I'm still working on determining reliable reproduction steps.

EDIT: I spun up a fix for the above bug in https://github.com/Automattic/wp-calypso/pull/71283. However, I can't definitively say it'll resolve our customers' issues due to our lack of reproduction steps. I'll continue investigating.

**Comment by jsnmoon** [comment]
Other customer reports related to this issue:

- 5788922-zd-woothemes (Jetpack)
- 5791294-zd-woothemes (Jetpack)
- 5795153-zd-woothemes (Jetpack)
- 5800764-zd-woothemes (Jetpack)

**Comment by purplepioneer** [comment]
Another report: 

- 5800174-zd-woothemes (Jetpack)

**Comment by keoshi** [comment]
Another one here:
- 5787365-zd-woothemes (Jetpack)

**Comment by purplepioneer** [comment]
The customer in [5800174-zd-woothemes](5800174-zd-woothemes) (Jetpack) reported that logging out and back in fixed this issue for them.

**Comment by alinclamba** [comment]
Another report:

5811336-zd-woothemes 

- Logging out and back didn't help. 
- They are using Chrome browser

**Edited by @JenSwish:** User is reporting that they are able to see stats on their phone but not desktop. They're also unable to see stats for individual posts on the all posts page.

**edited by @gaurav1984:** They are signed-in to the same network on both their phone and the computer. They are also able to access Enhanced stats on their phone now.

**Edited by @alinclamba:** User provided some more specific details:
> - I can get basic stats - number of views per day, etc., in the light blue format but not enhanced stats in the dark blue showing number of visitors as well as visits.
> -  I can get the enhanced stats and individual post stats using microsoft edge, but this is not the browser i use. also i can only get the cutdown admin page with the black margin instead of the light blue one that has all the plugins, so microsoft edge isn't the total answer. it would mean having to swing back and forth between browsers - one to operate the site, and the other to get the stats.
> - attached screenshot shows microsoft edge on the left and chrome results on the right.
> ![2023-01-18](https://user-images.githubusercontent.com/6790170/213106656-55636516-d1c7-45fd-befc-ffdaa2446235.png)

**Edited by @alinclamba:** Finally user is happy with the experimental stats in WP-admin. We can consider this case closed.

**Comment by lakellie** [comment]
Here are some console errors shared by an impacted user today in 5831674-zen:

![image](https://user-images.githubusercontent.com/17372274/210597940-0d70db33-454c-4daa-9803-1d891d3a96b5.png)

**Comment by lakellie** [comment]
Another user report received in 5836271-zen

**Comment by lakellie** [comment]
Another user report in 5836750-zen

**Comment by lakellie** [comment]
Another user report in 5817506-zen, fixed by logging out and logging back in

**Comment by lakellie** [comment]
Another user report in 5831269-zen

**Comment by lakellie** [comment]
Another user report in 5835197-zen

**Comment by foleynotrose** [comment]
Another report in 5816928-zd-woothemes. They've already logged out and back in. In this case it's hanging on the Sites Loading page (Screenshot in ticket). Not totally sure it's related to this bug.

**Comment by jsnmoon** [comment]
I've dug into our Sentry error logs and discovered two likely issues that affect all of Calypso, not just Stats:

1. The user's authentication has expired, but Calypso is not prompting them for a reauthorization (via another login flow). In this scenario, the user is likely unable to interact with any other part of Calypso. (Sentry issue 3227853925).
2. The user has insufficient privileges to view site stats; see a previous report here: p1611587067150200-slack-C0CMN0V97. (Sentry issue 3227822650).

**Comment by purplepioneer** [comment]
Got a report in 5835197-zd-woothemes. Logging out and back in resolved things for this customer.

**Comment by jcortx** [comment]
Another report here. 5824772-zd-woothemes

Logging in-out doesn't seem to work for the user, trying to get more information from this user as what browser they are using, switching to another browser, etc.

**Comment by purplepioneer** [comment]
We have a report in 5851260-zd-woothemes, i've determined that the stats issue is preventing the user from being able to purchase a 100GB Jetpack VaultPress Backup storage add-on as the site's data isn't loading. 

I've asked the user to log out and back in to see if that resolves the stats issue. I also asked them to try another browser (Firefox) if log out/log in doesn't work.

**Comment by alinclamba** [comment]
Hi, can we have someone investigate [this one](https://github.com/Automattic/wp-calypso/issues/71282#issuecomment-1367123044) please?

**Comment by alinclamba** [comment]
@jsnmoon when you have the chance, please look at [this user's case](https://github.com/Automattic/wp-calypso/issues/71282#issuecomment-1367123044) and let us know if we can do something for them. Thank you!

**Comment by a8ck3n** [comment]
> @jsnmoon when you have the chance, please look at [this user's case](https://github.com/Automattic/wp-calypso/issues/71282#issuecomment-1367123044) and let us know if we can do something for them. Thank you!

Hello @alinclamba. For this case, it looks like something is blocking the network request in the browser. That would explain why the page loads but it never updates with any real data.

My first thought is they might have installed a browser plugin that is causing an issue. Please ask them:

1. To disable any browser plugins and reload the page.
2. To open the Console tab and check for any errors.
3. To open the Network tab and check for failed network requests (they should be in red).
4. To try accessing the page with Wordfence temporarily disabled. (This is a reach though, as it works correctly in Edge.)

If they can copy any error messages and share them that might help.

**Comment by a8ck3n** [comment]
> Here are some console errors shared by an impacted user today in 5831674-zen:

These errors would indicate they are either no longer authorized OR they are logged into WP.com with a different user who doesn't have the correct privileges. I'm only seeing one connected user on this site though, so the latter probably isn't the cause here. I've gone ahead and expired their current session (via the User RC) so they'll be forced to log in again when next they visit WP.com. That should fix any authentication errors.

I'm also seeing some errors in the console which appear to be related to the **All in One SEO** plugin. I'd recommend they temporarily disable that and try loading the page again.

Note that the Stats page is loading fine when I visit it so I'd probably make the same recommendations as above for this user (minus the Wordfence one as I'm not seeing that on their site).

**Comment by a8ck3n** [comment]
Another troubleshooting request. If you have a savvy user who is willing to dig into their Chrome dev console, please request the results from the following steps:

1. Load the Stats page showing the loading status.
2. Open the Developer Tools via the "View → Developer → Developer Tools" menu.
3. Select the Network tab.
4. Select the text filter and enter "stats"
5. Select the "Fetch/XHR" tab.
6. Reload the page.
7. Click on the "stats?http_envelope=1" request.
8. A view will open showing the request. Click on the Preview tab.
9. Let us know the results here. I'd expect a 200 with some data or a 403 with an "unauthorized" message.

This will cause the list to update with all the network requests that are needed to load the page. It should look like this:

![DebugSnap](https://user-images.githubusercontent.com/40267301/214003969-4201783b-dee6-4926-b200-89da208933f1.png)

And the request view:

![DebugSnap2](https://user-images.githubusercontent.com/40267301/214005058-f73df67b-712d-4a65-947f-cf8d036305a7.png)

This doesn't help us fix the issue but it would at least confirm that the effected users are running into authorization issues.

**Comment by pehaa** [comment]
In this ticket user reported similar issue - 5929893-zd-woothemes

Here is the `stats?http_envelope=1` Preview:

```
{code: 404, headers: [{name: "Content-Type", value: "application/json"}],…}
body: {error: "invalid_blog", message: "This blog does not have the Stats module enabled"}
code: 404
headers: [{name: "Content-Type", value: "application/json"}]
```

I checked that Site Stats module **was** enabled.

Disabling and re-enabling Site Stats fixed the issue.

**Comment by purplepioneer** [comment]
Hi there! In 6030904-zen, the user's stats are working but they report that the stats aren't in the right timezone. Has anyone taken a look into this?

**Comment by jsnmoon** [comment]
Hey @purplepioneer, the timezone issue is [being tracked here](https://github.com/Automattic/wp-calypso/issues/16186). Thanks for the report!

**Comment by jsnmoon** [comment]
Closing this as resolved as we [merged a fix](https://github.com/Automattic/wp-calypso/pull/71283). Subsequent reports lack specificity to the original issue, where the Stats page was failing to load the necessary data to render the page. 

Calypso failing to load due to expired sessions, however, is unrelated to this ticket.

**Comment by cuemarie** [comment]
As most of these reports were resolved with the HE, and later issues are less clearly related, I've removed this from the Batch Reply queue.
