### ISSUE TITLE
CoBlocks (Version 2.25.4) breaks the default Button blocks' colors

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#71287]
### Quick summary

There was an update from CoBlocks that broke the button colors.

### Steps to reproduce

1. Updating the CoBlock plugin to Version 2.25.4 (Gutenberg plugin not required to be active)

### What you expected to happen

The Buttons block and background colors to work as expected.

### What actually happened

The background color for the Buttons block was not displayed after the plugin updated.

### Context

Encountered in:

38743715-hc, 38652579-hc

### Reproducibility

None

### Severity

None

### Available workarounds?

None

### Workaround details

The current workaround was to deactivate the CoBlocks plugin.

**Comment by sajmes** [comment]
38851995-hc

**Comment by ai2n** [comment]
34523664-hc
38640858-hc

**Comment by thekingsprojects** [comment]
38437264-hc , follow-up 5798467-zd-woothemes

**Comment by isocialtish** [comment]
Another report of this 5798751-zen

**Comment by jp-imagines** [comment]
Another report in 5799624-zd-woothemes. Buttons were suddenly rendered with white text on white background; disabling CoBlocks resolves the issue.

**Comment by connorhipps** [comment]
Another instance reported here where buttons are missing. 35974233-hc

**Comment by jp-imagines** [comment]
Noting here that CoBlocks was reverted to `2.25.3` on Atomic earlier today (see p1671390544021089/1671313072.418389-slack-C02FMH4G8), which resolves the issue. There should be no new reports.

**Comment by zdenys** [comment]
I had a case of this last week, so reporting it for tracking purposes 5797387-zd-woothemes. In my case, I solved it by turning off CoBlocks since they were not used by the user.

**Comment by WunderBart** [comment]
Reported upstream in https://github.com/godaddy-wordpress/coblocks/issues/2460

**Comment by olafleur-godaddy** [comment]
As per https://github.com/godaddy-wordpress/coblocks/issues/2460#issuecomment-1360121046 , CoBlocks 2.25.5 should fix the issue.

**Comment by zachspears** [comment]
Conformed that https://github.com/godaddy-wordpress/coblocks/issues/2460#issuecomment-1360121046 resolved this, closing the issue.
