### ISSUE TITLE
Stratford Menu layout problem

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#71297]
### Quick summary

PROBLEM:
* Site looks odd on some browsers with gaps missing and page content only appear when the theme is scrolled

WHAT I FOUND:
* Works on my browsers on Mac Studio
* On Browserstack however using Apples OS Ventura there is a huge gap on Firefox, Safari and Chrome
https://user-images.githubusercontent.com/13706336/208337917-9c151f7f-54d7-4792-82f4-47522dc81cd8.mp4
* Works on Windows Edge with Browserstakc but has a big gap to the content that suddenly pops up as you scroll.
* I tried to recreate a test site and the no problem occured until I added a menu. It worked up to the point where I assigned a primary menu and then it did this - https://d.pr/v/agJZc8

* Theme Stratford

### Steps to reproduce

Add a menu

### What you expected to happen

No gaps or jumping of content

### What actually happened

Big gaps and content jumping up the page

### Context

38588711-hc  
5800479-zd

### Platform (Simple, Atomic, or both?)

Atomic

### Browser, operating system and other notes

Different problem based on os and browser

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by zachspears** [comment]
Unable to reproduce but marking triaged as this appears to only impact specific devices and screencast was provided.

**Comment by karenroldan** [comment]
Hi, @zachspears! Could you kindly check if this issue occurs with different themes, or is it specific to a single theme? Also if the issue occurs on self-hosted sites. If so, adding a triage note would be appreciated. Thank you!

**Comment by zachspears** [comment]
📌 HOUSEKEEPING (To be removed once checked)
- Leaving Low Priority

📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Could Not Replicate. Tested in Safari, Firefox, and Google Chrome, each one looked like the image added below. I am using MacOS Venture 13.0.1 (22A400).

📌 FINDINGS/SCREENSHOTS/VIDEO
![Screenshot on 2023-01-19 at 23-23-39](https://user-images.githubusercontent.com/10124024/213631276-300f72f2-fe03-4f25-9151-fdc6a24042ad.jpeg)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
Closed as could not replicate in any browser on the target MacOS version.
