### ISSUE TITLE
Swap old plans with redesigned plans in Jetpack Connect

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7130]
In the process of getting rid of old plans code (#7129), I discovered that Jetpack Connect `client/signup/jetpack-connect` uses old plans code in the `plans` file. We need to swap this with the redesigned plans from `client/my-sites/plan-features` before we can get rid of old plans code.

cc @rralian @gwwar @johnHackworth @roccotripaldi @rickybanister

**Comment by roccotripaldi** [comment]
Thanks @lamosty, I'll add this to our milestone and start on it tomorrow.

**Comment by lamosty** [comment]
Perfect, thanks a lot @roccotripaldi!

**Comment by gwwar** [comment]
@rralian for context, see screens in #5241

**Comment by lamosty** [comment]
Fixed in #7165.
