### ISSUE TITLE
Checkout: hide the presales Zendesk chat when purchases are blocked

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#71310]
### Details

We should not show the ZD presales chat widget to users when they're blocked from purchasing. 
See pdm0RZ-nC-p2#comment-782

Related: #70118 where the presales chat was added to checkout

**Comment by yoavf** [comment]
@sirbrillig 
I thought I could do something like
```
	const cartKey = useCartKey();
	const { responseCart } = useShoppingCart( cartKey );
	// Check if responseCart.message.errors include an object with `code=blocked`
```
But it seems like the cart clears the messages once they're displayed. 
Any suggestions on how to access the error messages (from the cart or elsewhere)?

**Comment by sirbrillig** [comment]
> But it seems like the cart clears the messages once they're displayed.

Hm. I'm not sure what would do that. CartMessages displays messages but AFAIK doesn't mutate the cart object so they should still be present. 

Although it does make me wonder: cart action promises are rejected if there are errors in the messages. Could that be related to what you are seeing? I'll look more closely at your code.

**Comment by yoavf** [comment]
> Hm. I'm not sure what would do that

I understood this to do that (once the messages are displayed), but maybe I'm wrong:
https://github.com/Automattic/wp-calypso/blob/37a991c492e216043578841b4a69ac1d55bc97cc/packages/wpcom-checkout/src/use-display-cart-messages.tsx#L76

**Comment by sirbrillig** [comment]
Oh! Hah, yes, I guess it does. It probably shouldn't do that, but I guess there was never a need to keep those error messages around before. We could remove that behavior. It should be the display component's responsibility not to show the same message more than once. I'll make a PR... 

Update: https://github.com/Automattic/wp-calypso/pull/71346
