### ISSUE TITLE
Checkout button hidden on mobile devices on Tsubaki theme

### ISSUE THREAD

**Issue by rakshitwesley** [Automattic/wp-calypso#71316]
### Quick summary

Cart popup on a site with Tsubaki theme is hiding the checkout button on a mobile device.

![kYque3.png](https://user-images.githubusercontent.com/95758851/208422265-32f62c69-ecc0-4026-a1ce-ce2341c01f74.png)

### Steps to reproduce

1. Add Tsubaki theme on a site
2. Open the site on a mobile device
3. Add a product to cart and select the cart icon from the top menu
4. The checkout option is not completely visible at the bottom.

### What you expected to happen

Checkout option to be visible

### What actually happened

Checkout option is hidden

### Context

Reported here: 38844553-hc

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Tsubaki theme

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by zachspears** [comment]
In my testing, I found that the checkout button is not hidden but needs to be scrolled to. There are also other layout issues on the checkout view:

https://user-images.githubusercontent.com/10124024/209871781-a6baa989-dbdd-4e22-9000-5351ff04571a.mov

The only workaround would be to scroll down.

**Comment by rakshitwesley** [comment]
Thanks @zachspears, for looking into this. I tested this on my android device with chrome browser, and the popup cart page does not scroll down.


https://user-images.githubusercontent.com/95758851/209898429-aa149aff-a70c-46ce-8bbd-8aab3df89931.mp4

**Comment by karenroldan** [comment]
Hi, @zachspears! Could you kindly check if this issue occurs with different themes, or is it specific to a single theme? Also if the issue occurs on self-hosted sites. If so, adding a triage note would be appreciated. Thank you!

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on AT - Replicated 
- Tested on Self-hosted - Replicated 
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicable on Tsubaki, Blockbase, and 2023 theme on self-hosted and Atomic.

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/70204
