### ISSUE TITLE
LaunchPad - Implement circular progress bar

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71326]
Develop a new progress bar with circular style design as shared in the p2 below, and use this as the progress bar in the launchpad checklist.

New designs for a 'cohesive launchpad experience' - paYE8P-2kx-p2 - use a circular progress bar for the launchpad. This helps create a cohesive and understandable experience as we will use a similar icon to represent the launchpad in other areas.

![Screen Shot 2022-12-19 at 9 35 15 AM](https://user-images.githubusercontent.com/28742426/208449694-6da5024e-81c6-4b9e-b8c4-0a4d9ce3ca62.png)

**Comment by nuriapenya** [comment]
@Sharpirate I prepared this [Figma file](9wpoYJrMlYKAKUYvVBMN74-fi-1760%3A43986) with some design guidelines. Let me know if you need something more specific :)
