### ISSUE TITLE
LaunchPad Preview - "On Click" to enter site editor

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71329]
Lets make the launchpad preview load into the site editor on click:

![Screen Shot 2022-12-19 at 10 17 56 AM](https://user-images.githubusercontent.com/28742426/208458884-e6a0e4b0-d803-4703-9ed2-3c18cfd63d08.png)

Open questions to raise in team meeting today:
* Should newsletters also have this functionality?
* Should there be a confirmation modal or anything else before redirecting?

**Comment by Addison-Stavlo** [comment]
> Should there be a confirmation modal or anything else before redirecting?

Note we have a design to make this have an "Edit" button on hover. Clicking that edit button will lead into the editor.

cc @nuriapenya did you have a design handy for that interaction? I think we have this in place somewhere else but its slipping my mind where it is... 😆

**Comment by nuriapenya** [comment]
@Addison-Stavlo I thought we could do is reuse the existing hover functionality that we have on the Theme pages:


https://user-images.githubusercontent.com/7931304/208651910-eecb4e29-d26c-4951-8ff2-2fc66c1d6d12.mov

So, I prepared [a design](9wpoYJrMlYKAKUYvVBMN74-fi-1760%3A47924&t=5ggp211QTyogKUvx-4) that would mimic this. The `Edit` button would link users to the Editor -> Edit Links task.

https://user-images.githubusercontent.com/7931304/208652007-296c8714-e9db-4728-bf95-e352e996780b.mov

I'd argue that for consistency purposes, Newsletter users (and all the other TUC) could also benefit from this feature. What do you think?
