### ISSUE TITLE
LaunchPad - Add Plugin Sidebar to post/page editor

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71328]
Dependent on https://github.com/Automattic/wp-calypso/issues/71325 

Register an editor plugin & plugin sidebar using the Icon noted above. For first iteration, we call fill the sidebars content with a CTA / link  to visit the launchpad.

Registering a plugin sidebar with an icon should automatically render the icon in the top-right of the page/post editor as so:
![Screen Shot 2022-12-19 at 10 03 54 AM](https://user-images.githubusercontent.com/28742426/208455791-730c8e6d-1c25-4a2b-9893-37db466f01bb.png)

Which is then used to open the default plugin sidebar, where we can add a copy and CTA.  A good example of what this default sidebar looks like could be the Jetpack plugin's sidebar:

![Screen Shot 2022-12-19 at 10 07 53 AM](https://user-images.githubusercontent.com/28742426/208456483-443a2720-1562-45d7-b32a-fe8311527d00.png)

cc @nuriapenya - for the first iteration do you have thoughts on any specific phrase / CTA etc. to present to the user from this sidebar?

Note - After shipping to the post/page editor, we can look at adding this to the site editor as well.

related to designs - paYE8P-2kx-p2

**Comment by nuriapenya** [comment]
>cc @nuriapenya - for the first iteration do you have thoughts on any specific phrase / CTA etc. to present to the user from this sidebar?

I'd say for the first iteration; we can keep it simple and have the following:

- **Title**: Setup Guide
- **Text**: Keep setting up your site with our recommended next steps. 
- **CTA**: Open Setup Guide

Also, we need to make sure the icon follows the same pattern as the other icons: Highlighted in the black when activated. WDYT? You can find the designs in Figma: 9wpoYJrMlYKAKUYvVBMN74-fi-1760%3A43986

<img width="371" alt="Screenshot 2022-12-21 at 11 23 35" src="https://user-images.githubusercontent.com/7931304/208882591-c2cd84ad-7d7c-4cd7-a8f9-9df49cb68279.png">

**Comment by nuriapenya** [comment]
Here's is how the whole interaction would look like:

https://user-images.githubusercontent.com/7931304/208885791-63120c50-d880-489c-bf37-48e3ab87d99a.mov

**Comment by Addison-Stavlo** [comment]
> Also, we need to make sure the icon follows the same pattern as the other icons: Highlighted in the black when activated. WDYT?

Agree, although I think that is handled by default by the editor's plugin system 🤞.

This seems like its ready for us to develop a first iteration? But I also see I put it on hold just before the break, so I might be forgetting something we discussed in slack. Il bring this up for clarity in the meeting today.

**Comment by Addison-Stavlo** [comment]
im closing this as it seems have fallen through on design reviews.
