### ISSUE TITLE
[AI Blocks] Create a credit system for the OpenAI tokens

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#71332]
### Why on hold?

We haven't figured out pricing yet. 
Blocker:  https://github.com/Automattic/ai-services/issues/7

### Details

Whenever we call OpenAI, we need to pay for the API call. 
So we need to implement a credit system - site owner will need to have a paid plan and/or purchase an addon to be able to use more text generations / image generations.

More details
p58i-dFa-p2

### Classes of credits

- Text tokens from plans that expire every month. We want to refresh tokens every month based on a plan and have ability to tweak this number.
- Image tokens from plans that expire every month. We want to refresh tokens every month based on a plan and have ability to tweak this number.
- Purchased text tokens that do not expire
- Purchase image tokens that do not expire

### Where to store these credits

Some ideas:

- blog_options
- wherever domain credits are stored (check with other payments teams)

### Checklist

- [x] See how domain credits work. Contact other payment teams if these are appropriate | See pbOQVh-2Re-p2
- [ ] Figure out how to track credits for the usage of OpenAI API. This probably needs a P2 | See pbOQVh-2Re-p2
- [ ] Implement the credit system during the OpenAI API Call in `WPCOM_REST_API_V2_Endpoint_OpenAI` - we want to subtract credits on usage | See D96963-code
- [ ] We need to inform the user how many credits are left. We can use the block sidebar for that. We will probably need a new endpoint in WPCOM_REST_API_V2_Endpoint_OpenAI/OpenAI_REST_Controller | Endpoint will be introduced in D96963-code
- [ ] We need to block the OpenAI API call when the user is out of credits | See D96963-code
- [ ] Implement renewal of the plan-based credits if the plan is active
- [ ] Introduce a plan nudge / purchase more credits nudge once #71337 is implemented

**Comment by artpi** [comment]
Another approach that may be better would be instead of having credits that we subtract, to track **usage** that we check when call is being made.

So basically whenever you make a call, we increment a counter instead of keeping balance.

And we have that counter already!

Log2logstash tracks endpoint usage and is super performant

**Comment by romarioraffington** [comment]
I think the aim here is to find a solution to track and communicate usage to our customers ( and other stakeholders ).

A user wants to know the following:

1. How much of my "tokens" or "credits" ( could be called something else ) I've used up
2. How much will it cost me to buy more "tokens" or "credits."
3. How do "tokens" or "credits" translate to value? For example, 30 pictures, 2000 words.

Finance and a8c want to know the following:

1. How much has a8c spent on OpenAI tokens for a particular plan to figure out margins
2. etc

As Artur pointed out above, Logstash allows us to track usage ( tackle the finance and a8c problem above ) by simply logging and creating dashboards. The only "issue" is that logstash data  is persisted for up to 6m based on my understanding. So the question here is... is this a problem?

> And we have that counter already!

True! IMHO, the logstash approach seems like a "hacky" but it's definitely an approach. I'll look into the BD addon approach and brainstorm / research other approaches to see our options are.

**Comment by artpi** [comment]
Relying on logstash may be problematic because the retention policy is about 3 months and when you purchase tokens, you expect them to be usable much longer.

But I still prefer counting usage and not subtracting some tokens.
I think we can combine these approaches:
- Rely on logstash for the "monthly" usage included in plans
- Rely on blog options for the usage you pay for

So the logic could be something like:

- Count usage over the last 30 days
- If lower than plan quota, continue request
- If higher than plan quota, see if you have an addon purchased and how much you've used.

That strategy also will let us to switch to metered billing easily

**Comment by romarioraffington** [comment]
> But I still prefer counting usage and not subtracting some tokens.

> That strategy also will let us switch to metered billing easily

I agree! 

> Relying on logstash may be problematic because the retention policy is about 3 months and when you purchase tokens, you expect them to be usable much longer.

I suspect this would cause an issue for yearly plans as well, assuming the tokens will only expire when the plan renews.


While I wait for feedback on pbOQVh-2Re-p2, I will be stubbing the DB layer. See D96963-code for work heavily in progress

**Comment by artpi** [comment]
Based on Matt's comments, we want to publish a p2 with progress so far so we can continue the discussion, but we are going to put this work on hold.

**Comment by romarioraffington** [comment]
I'll update pbOQVh-2Re-p2 to reflect the update and add D96963-code as a reference as well

**Comment by artpi** [comment]
Jetpack took this over
