### ISSUE TITLE
Site Editor - Close button compatability for Gutenberg 14.8

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71336]
Currently on edge sites running Gutenberg v 14.8.0-rc.1, the close button to the editor has been updated.

Instead of `< Dashboard` button, the icon now serves as the close mechanism once the panel is open:

![Screen Shot 2022-12-19 at 10 26 35 AM](https://user-images.githubusercontent.com/28742426/208460787-a6b9d24e-8b4f-4f88-8895-d1260e75c8da.png)

When this is clicked through the calypso editor iframe, navigation continues inside the editor iframe:
![Screen Shot 2022-12-19 at 10 28 07 AM](https://user-images.githubusercontent.com/28742426/208461035-7cc59050-d623-4022-b9ca-8d64284fea6f.png)

We currently handle this for the Iframed editor via - https://github.com/Automattic/wp-calypso/pull/70301 - however, we need to update/add new selector criteria so this functionality works with 14.8's new close button.

Note this selector is used in a few areas that may need to be updated https://github.com/Automattic/wp-calypso/search?q=.edit-site-navigation-panel__back-to-dashboard - including tracking events as well. 

Upon inspection it doesn't look like there is a good selector for this button that only represents it in the state in which it serves as a close link (other than checking for anchor tags or aria-labels). This buttons serves to open then panel if it isnt opened, or close the editor if the panel is already opened - so being able to determine between these two states of functionality seems important. is it possible to add a clear class name or id to this element in core when it is in the state that enables closing the editor?

**Comment by simison** [comment]
Is the main problem that link would open inside the iframe, instead of outside the iframe?

Otherwise we can override `__experimentalDashboardLink` to our needs? Not sure if tracking is that important on this button, and we could always add `?ref=` to the URL to be able to track at landing page.

**Comment by simison** [comment]
BTW Help Center is at 100%, it was deemed to be last blocking obstacle on removing the iframe.

**Comment by Addison-Stavlo** [comment]
> Otherwise we can override __experimentalDashboardLink to our needs?

We are already, which allows this to work well from the wp-admin (non-iframed) versions just fine.

Since we are already using that, another suggestions is using that in part of the selector: `[href="${ __experimentalDashboardLink }"]` for the iframe solution.

> Is the main problem that link would open inside the iframe, instead of outside the iframe?

Exactly. The user starts navigating around dotcom within the site-editor iframe.

>  Not sure if tracking is that important on this button

Not huge. Although it would be interesting to keep functional to compare these two approaches since we have historical tracks on the last approach. In some LIB flows we found ~33% of users entering the editor actually used the native close button... it would be interesting to see how this contrasts when the button is not labeled and serves a dual purpose of opening the panel.

**Comment by simison** [comment]
> Not huge. Although it would be interesting to keep functional [...]

Gotcha; if no click tracking, you can still observe `calypso_page_view` event with `?ref=` prop if that's added to the injected URL.

**Comment by Addison-Stavlo** [comment]
this has been resolved
