### ISSUE TITLE
Signup: Style tweaks to Domains signup

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#7134]
According to @shaunandrews mockup: http://codepen.io/shaunandrews/full/grzqaN/
- [ ] Remove 'upgrade' buttons, remove "Included in Premium" popover, and make each domain a clickable row (#7132)
- [ ] Move unavailable domain entry back into the list
- [ ] Reword “mapping” to something more explicit/easy to understand
- [ ] Use new explanatory image/copy about domains (#7233)

**Comment by klimeryk** [comment]
This issue seems to be stale and not needed anymore - closing.
