### ISSUE TITLE
Improve Google Apps for Work signup flow

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#7135]
According to @shaunandrews's mock: http://codepen.io/shaunandrews/full/grzqaN/
- [ ] Make it more explicit and provide a better explanation
- [ ] Allow users to skip it more easily (if they want to)
- [ ] Provide a contextualized example of what their email address will look like

**Comment by klimeryk** [comment]
Closing as G Suite has been removed from signup.
