### ISSUE TITLE
[Bug]: Theme Showcase: The "My Themes" filter sometimes can't be clicked

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#71368]
### Quick summary

The filter can't be clicked when the current filter is not "All".

@Automattic/lego 

### Steps to reproduce

1. Create a site with Business plan
2. Open `/themes/<siteSlug>`
3. Click on a filter other than "All" (e.g. "Blog")
4. Now click on "My Themes" filter

### What you expected to happen

The My Themes filter is selected

### What actually happened

The My Themes filter is NOT selected

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Click on the My Themes filter twice

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/71381
