### ISSUE TITLE
Missing Google Fonts in Global Styles on Simple Sites

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#71360]
### Quick summary

When looking for fonts in the Typography section of Global Styles using an FSE theme on a Simple site, only a small list of fonts is available. AT sites have a much larger selection of fonts to choose from.

### Steps to reproduce

1. On a Simple site, select an FSE theme (such as Appleton or Zoologist).
2. Go to Appearance > Editor, then open the Styles panel and select Typography.
3. Choose any type of typography to edit (such as Text), then open the Font dropdown.

### What you expected to happen

There should be a long list of fonts available to select, as shown in this screenshot from an AT site (Zoologist theme):

<img width="277" alt="styles-fonts-at" src="https://user-images.githubusercontent.com/82622339/208560150-809fc935-a24f-487e-9f99-d2c6d023c64f.png">

### What actually happened

There are only a handful of fonts available, as shown in this screenshot from a Simple/Premium site (also Zoologist):

<img width="288" alt="styles-fonts-simple" src="https://user-images.githubusercontent.com/82622339/208560217-f60a9d38-baf7-42d4-824a-e17821ddba25.png">

### Context

Customer wanted to use the Inter font for their Premium site, and couldn't find the font in the list. It seems like the font was available before?

Follow-up ticket here: 5802914-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Seems to be all FSE themes

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

No but the platform is still usable

### Workaround details

The only workaround I'm aware of right now would be upgrading to an Atomic-capable plan, which would restore the full font list and also allow for custom font plugins if needed.

**Comment by rinazrina** [comment]
Another report in #5803109-zen 

Site is using Appleton theme, and the user believes they used Monserrat before, but this font is no longer available on the font list under Styles.

**Comment by kriskorn** [comment]
The only commit regarding fonts I can see is this - https://github.com/Automattic/themes/commit/5be05d36a283c903f38fefefbd6acd4c27156791 in the last 13 hours. 
Matches the behaviour of Blockbase based themes not showing fonts properly. cc @pbking

**Comment by cintacks** [comment]
Have another instance here - user was using Monterrat before the GDPR change and wants it back: 5802857-zd-woothemes (Geologist theme)

AFAIK - this is still being worked on per: p58i-cSr-p2#comment-56325

**Comment by Robertght** [comment]
5779931-zen

**Comment by kriskorn** [comment]
**This should be fixed now!** 
More information here: p1671528574216529-slack-themes

**Comment by simison** [comment]
Revert in D96035-code fixed the issue.

**Comment by simison** [comment]
> AFAIK - this is still being worked on per: p58i-cSr-p2#comment-56325

@kettultim nope, GDPR changes are live. p58i-cSr-p2#comment-56500

**Comment by cintacks** [comment]
> > AFAIK - this is still being worked on per: p58i-cSr-p2#comment-56325
> 
> @kettultim nope, GDPR changes are live. p58i-cSr-p2#comment-56500

Missed that! I'm seeing it fixed now - thanks!
