### ISSUE TITLE
Signup: Test different wordings for the Domain “Upgrade” links

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#7136]
In some of our user tests, the users were confused with the wording of the “Upgrade” buttons. (And thought that perhaps domains were not available)

We're making these links a clickable row as part of issue #7134, but we also want to make sure the wording is explicit to the users that domains are a premium/paid feature. Ideally we'd run an A/B test with the following wordings:
- Upgrade
- Buy
- Add to Cart
- Select Plan

**Comment by klimeryk** [comment]
In https://github.com/Automattic/wp-calypso/pull/14401 we've launched an A/B test for this. We've used `Select` as the alternative CTA - and it seems to have done well enough (details: `p8kIbR-4e-p2`), so it's been deployed as the default CTA in https://github.com/Automattic/wp-calypso/pull/14953.
