### ISSUE TITLE
[Bug]: Current theme in Jetpack sites is not the first theme in Theme Showcase

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#71367]
### Quick summary

We always show the current theme as the first theme in the Theme Showcase grid. However, it looks like it is not the case for Jetpack sites.

@Automattic/lego 

### Steps to reproduce

1. Create a self-hosted site (e.g. using Jurassic Ninja)
2. Activate TT3
3. Connect to Jetpack
4. Open `/themes/<siteSlug>`

### What you expected to happen

The current theme (TT3) is the first theme. E.g. in simple sites:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1525580/208641791-081ae268-ac44-4d6e-9e62-851f3c8d88f9.png">

### What actually happened

The current theme (TT3) is NOT the first theme

<img width="792" alt="image" src="https://user-images.githubusercontent.com/1525580/208642047-d3bc329c-40c8-4ce7-b387-73cecb08ebb8.png">

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

None

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/71385
