### ISSUE TITLE
Quadarat: Missing fonts on Simple sites

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#71364]
### Quick summary

The number of fonts available in Quadrat themes is significantly less on Simple sites. I was able to see this issue only on Quadrat theme on simple sites.

On AT, Quadrat has more fonts.

### Steps to reproduce

1. Go to a Simple site.
2. Activate Quadrat.
3. Go to Appearance > Editor > Styles > Typography.
4. You will notice that only a few fonts are available.

Screenshot:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/33957570/208605565-f47c0907-5dc6-43ff-b678-1b0915ae3bac.png">

### What you expected to happen

Quadrat on simple sites should have same number of fonts that is on AT and other themes.

### What actually happened

There are only 5 fonts on Quadrat on simple sites.

### Context

User report: 5802373-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Quadrat

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by jordesign** [comment]
Just checking with @ianstewart  - is Quadrat one of the themes slated for retirement?

**Comment by zachspears** [comment]
Hey @devNigel, I just tested this on a simple site with Quadrat, and I am seeing several font options. Can you confirm if you are still seeing this issue? Thanks!

![Screenshot](https://user-images.githubusercontent.com/10124024/209887292-a014e32a-40f7-41d8-8509-42e13602058a.jpg)

**Comment by vajrasar** [comment]
Closing this since Me and Zach both could not replicate the issue. @devNigel pls reopen if the issue persists.
