### ISSUE TITLE
Page list loads a transparent text `Loading a page of Pages…` at the top for FSE themes with homepage set to `Your latest posts`

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#71375]
### Quick summary

On an FSE-themed site set to display the latest posts rather than a static page, the page list loads a blinking grey stripe that reads the message `Loading a page on multiple pages...` if selected. 

### Steps to reproduce

1. Activate an FSE theme such as Quadrat White
2. Go to Settings > Reading and select `Your latest posts` option
3. Go to Pages view 

### What you expected to happen

No blinking gray stripe at the top

### What actually happened

A blinking grey stripe that loads a transparent message `Loading a page on multiple pages...` that is revealed if you select the text.

![mvsFq9.gif](https://user-images.githubusercontent.com/39308239/208679812-949a11ef-ac58-40c9-9fd8-1994459ead28.gif)

The text color seems to be set to #000000 
![LKBZVG.png](https://user-images.githubusercontent.com/39308239/208679711-195668ce-8484-486f-8ed3-971a4bc61d06.png)

### Context

I suspect this is caused by p7DVsv-fRk-p2 (FYI @Automattic/lego). First noticed when working on 5804208-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

I have only tested FSE theme so far on Atomic.

### Browser, operating system and other notes

macOS Monterrey 12.6.1 with Google Chrome Version 107.0.5304.121 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by candy02058912** [comment]
I did a bit of testing today, and it seems that it's an Atomic specific issue.

**Comment by fushar** [comment]
@candy02058912 I have not been able to reproduce the issue. Could you tell us the exact steps? How did you create the Atomic site?

**Comment by candy02058912** [comment]
@fushar
I wasn't able to reproduce this issue today.
Tried on simple/atomic/jetpack sites.
Will be closing the issue.

**Comment by bangank36** [comment]
I can't find the blinking text either!

**Comment by zdenys** [comment]
The issue is still present on Atomic site. I can reproduce it on my several testing sites. The steps to reproduce are:
- Create an AT site (feel free to ping an HE to get credits added to your SA so you can upgrade to at least Business Plan and then go AT by clicking Activate in [Hosting Configuration](https://wordpress.com/support/hosting-configuration/))
- Activate an FSE theme such as Geologist
- Go to SITEURL/wp-admin/options-reading.php and select `Your latest posts` 
![F8dRHE.png](https://user-images.githubusercontent.com/39308239/209629911-cb139a0b-66df-468e-a629-620c6c42db52.png)
- Go to Pages section https://wordpress.com/pages/ (Calypso view not WP Admin one)
- Observe the issue
![6hv4Ey.gif](https://user-images.githubusercontent.com/39308239/209630054-0f61f9b4-da42-491b-ac26-6b2fc3f23c6d.gif)

**Comment by candy02058912** [comment]
@zdenys to double check, the sites that you're testing with are all "coming soon" (unpublished) sites?
@taipeicoder was able to reproduce this on unpublished atomic sites.

**Comment by zdenys** [comment]
>@zdenys to double check, the sites that you're testing with are all "coming soon" (unpublished) sites?

Yes! That was the missing part. Given that a new WP.com site is in Coming Soon mode by default, I totally missed mentioning that condition. When I launch the site, the issue is not reproducible.

**Comment by vajrasar** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Replicated
- Tested on Self-hosted - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate the issue on an AT site (Coming Soon mode active) with several FSE themes.

This seems like an issue which shows up with AT site (Coming Soon mode active) + FSE themes.

📌 ACTIONS
- Marked as Triaged for Quality Squad review
