### ISSUE TITLE
Use new horizontal layout for plans

### ISSUE THREAD

**Issue by coreh** [Automattic/wp-calypso#7137]
Now that we have a personal plan, we should investigate switching to a horizontal layout, as in @shaunandrews mock: http://codepen.io/shaunandrews/full/grzqaN/

**Comment by shaunandrews** [comment]
The plans page was just extensively redesigned and tested. I don't see us touching it anytime soon, and it also doesn't really fit with the domains milestone.

**Comment by coreh** [comment]
:thumbsup:
