### ISSUE TITLE
Blocks: Add "Learn More" to Navigation and Group

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#71384]
Almost all blocks on Dotcom have a "Learn more" link in their descriptions, pointing to our support pages.

https://github.com/Automattic/wp-calypso/blob/4cb39a0cdfcd6afcc38b1e29e1274a2741624f6e/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-description-links/src/block-links-map.ts

The Navigation and Group block don't have them, so let's add them!

- [ ] **Navigation**
  - `core/navigation`
  - https://wordpress.com/support/site-editing/theme-blocks/navigation-block/
- [ ] **Group**
  - `core/group`
  - https://wordpress.com/support/wordpress-editor/blocks/group-block/

According to @donalirl, both blocks had technical limitations preventing this. Let's investigate and fix accordingly!

Read more: pekYwv-mg-p2#comment-279

**Comment by BogdanUngureanu** [comment]
Deployed in WPCOM in rWPGITf6e313f05634
