### ISSUE TITLE
Theme Switch Modal shows inconsistent or wrong previews on Atomic in Firefox

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#71389]
See pekYwv-mg-p2#comment-283 for reference.

To reproduce create a new site without a custom domain and switch themes.

Examples from Firefox:

![image](https://user-images.githubusercontent.com/545779/208756977-8deedf1b-b036-4139-9c07-7fe6d88b1cba.png)

![image](https://user-images.githubusercontent.com/545779/208757078-8ea6962d-4a87-487b-bd22-b9807558b0a9.png)

The last example, shown in Chrome, matches expectations:

![image](https://user-images.githubusercontent.com/545779/208757163-9a1f4a14-1d7d-421c-9232-bef97cbb5a5c.png)

# Related
See https://github.com/Automattic/wp-calypso/pull/71349#issuecomment-1359645476

**Comment by fushar** [comment]
After some investigation, we believe this is due to Jetpack being in Safe Mode (unexpectedly) in the above scenario.

See: p9F6qB-90M-p2#comment-51026.

Closing this issue in favor of the resolution of the above's issue instead.
