### ISSUE TITLE
/website-builder LP i1

### ISSUE THREAD

**Issue by Noemish** [Automattic/wp-calypso#71418]
We only have [this request](pdZzpt-wv-p2) design needed, so I'm assigning this to backlog to @vinimotaa , @jrdnhllr or @Noemish to this task for the moment

DRI - Main designer: @jrdnhllr 
Support designer: @Noemish

**Comment by Noemish** [comment]
Latest thread
pdZzpt-mw-p2

**Comment by teafolk** [comment]
Just adding in a link to the post where we've been keeping track of all layout, content, and copy for this page! https://storytellersp2.wordpress.com/2022/10/28/key-landing-pages-conversion-refresh-website-builder/

**Comment by jrdnhllr** [comment]
Sharing an update here with initial wireframes and visual explorations pdZzpt-mw-p2#comment-1103

**Comment by jrdnhllr** [comment]
Adding a link to the most recent 3x design proposals  pdZzpt-mw-p2#comment-1127

**Comment by jrdnhllr** [comment]
Design update 👉 pdZzpt-mw-p2#comment-1177
