### ISSUE TITLE
/free LP i1

### ISSUE THREAD

**Issue by Noemish** [Automattic/wp-calypso#71419]
We only have [this request](pdZzpt-wv-p2) of design needed, so I'm assigning this to "Upcoming" to @vinimotaa , @jrdnhllr or @Noemish to this task for the moment

Main designer: @jrdnhllr 
Support designer: @Noemish

**Comment by Noemish** [comment]
updated copy
https://docs.google.com/document/d/1bCCyxNHt9UPOKccBlV-RWzmorHvYwutGBgMHvdFuJs0/edit#heading=h.obzvbpyf18vw

**Comment by jrdnhllr** [comment]
Figma MVP – [Wy6o12MwIkeC1RtXEUab8z-fi-33%3A15974](https://href.li/?https://www.figma.com/file/Wy6o12MwIkeC1RtXEUab8z/?node-id=33%3A15974)

**Comment by Noemish** [comment]
Latest designs Wy6o12MwIkeC1RtXEUab8z-fi-1_3244
Latest P2 pdZzpt-o1-p2#comment-1550
