### ISSUE TITLE
Retired and Third Party Themes Not Showing As Active in Calypso 

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#71438]
### Quick summary

Retired or Third party themes that are active on a site do not show in Appearance > Themes, so there is no way to no way to tell which theme is active unless you switch to the Classic view. 

### Steps to reproduce

1. Activated a retired or third-party theme.
2. Go to My Site > Appearance > Themes in Calypso
3. No way to tell which theme is active. 

### What you expected to happen

In Appearance > Themes, you can tell which theme is active when you are using a non-retired or  WordPress.com theme:

<img width="1329" alt="Markup 2022-12-21 at 16 50 24" src="https://user-images.githubusercontent.com/74204272/209025641-82f1ec78-7810-401a-8e2a-ca25cf457ab2.png">

### What actually happened

With Retired or third party themes, there is no indication of which theme is active unless you switch to the Classic view
<img width="1259" alt="Markup 2022-12-21 at 16 53 30" src="https://user-images.githubusercontent.com/74204272/209025710-30a6ad97-d1d5-4269-906e-78bb34a61332.png">

### Context

Noticed on my test site that I couldn't tell which theme was active in Calypso. 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is switching to Classic View to tell which theme is active.

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/71444, thanks for the report 🙂
