### ISSUE TITLE
Update WooCommerce loading screen on WordPress.com

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#71441]
## User Story

> As a user, 
> I want to see an updated loading screen design,
> so that I don't feel like looking at something dated and clunky while waiting for my site to set up.

Existing screen is:

<img src="https://user-images.githubusercontent.com/3747241/209041531-f7122cfb-5514-4f55-b9f4-d5ac2e8c78e6.png" width="500">

## Acceptance Criteria

```
Feature: Loading screen while setting up WordPress.com ecommerce plan

Given user
When the user selects to start a store in WPCOM
Then show the updated loading screen
Then it should redirect to WooCommerce homescreen
```

Design: 4ixWMlzrxllx93tSFsCW6k-fi-5037%3A81768&t=okHc8B7sfncDltj2-0

<img width="548" alt="image" src="https://user-images.githubusercontent.com/3747241/209039479-c4a9c9c6-7e83-4346-b6a8-01c4bffb0489.png">

**Comment by chihsuan** [comment]
It seems that Serenity has implemented this in the free trial flow

https://wordpress.com/setup/wooexpress

**Comment by ilyasfoo** [comment]
Good catch, @chihsuan! Yes, they've added the flow. We should be able to close this issue

**Comment by ilyasfoo** [comment]
It seems the current version does not 100% following Veronica's design. Namely, the messaging on loading bar. Reopening

**Comment by chihsuan** [comment]
figma: lD0gTB4IqGsmSmsnjZNaP6-fi-1%3A1461

**Comment by daledupreez** [comment]
Thanks for tracking this and re-opening, @ilyasfoo!

As a quick note, the existing screenshot you have there is what we show after purchasing the eCommerce plan, so we are not replacing that screen in this task.

I am going to ping @markbiek, as he built the initial implementation. Please feel free to ping anyone on Serenity for help/direction if needed.

**Comment by ilyasfoo** [comment]
@daledupreez Thanks for clarifying, this issue was created a while ago and the details were not updated. I think @chihsuan created a PR which does exactly what it is supposed to do

**Comment by ilyasfoo** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/73351
