### ISSUE TITLE
Design previews: clash of canvas and the wrapper

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#71440]
# Description

Originally reported p1671646058241269-slack-C048CUFRGFQ

In design picker, there is an undesired visual bug with the canvas and the wrapper. The edges of the site seem to overlap wrongly the device. Is this a known issue (Safari)? Not only on mobile but it’s more prominent in that viewport.

![Image](https://user-images.githubusercontent.com/5665959/209031277-01140c63-baeb-4999-9e89-63ee2ba19833.png)

# Dev Tasks
- [ ] check on all viewports to see all instances where this might be a problem
- [ ] prevent design from overlapping on the device frame

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/71455
