### ISSUE TITLE
Task: Remove Back button from tailored eCommerce flow steps

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#71459]
### Details

Per the discussion from this walkthrough, peapX7-1go-p2, we should remove the _Back_ button from the screens in the eCommerce flow.

### Checklist

- [ ] No screens in the eCommerce tailored flow should include a Back button

**Comment by nelsonec87** [comment]
The `storeProfiler` step is the only one showing the Back button in the eCommerce flow.
