### ISSUE TITLE
Post purchase upsell: update upsell nudge design

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#71463]
Update the upsell nudge for the post purchase upsell, in my-sites/checkout/upsell-nudge

Design: pebzTe-yQ-p2#comment-1004

Acceptance criteria:
- [ ] There's a new upsell nudge component.
- [ ] The copy is still the same.

**Comment by paulopmt1** [comment]
Closing this as we'll Prepare new upsell for the experiment (1461-gh-Automattic/dotcom-forge)
