### ISSUE TITLE
Post purchase upsell: send copy for translation

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#71462]
Submit upsell copy for translation. Final copy: pebzTe-yQ-p2#comment-1004

Acceptance criteria:

- [ ] Add as a preemptive translation: pxLjZ-6Mo-p2#comment-18710

**Comment by lupus2k** [comment]
I think we have to pause it because there is an ongoing discussion here: pb5gDS-2qa-p2#comment-3182

**Comment by paulopmt1** [comment]
> I think we have to pause it because there is an ongoing discussion here: pb5gDS-2qa-p2#comment-3182

Good to know! As I already have it done, in case we decide to move forward, [here are the current strings](https://github.com/Automattic/wp-calypso/commit/40df5bdb8fb009c7a8012dd4e8aa91c23a9a0347) ready for preemptive translation.

**Comment by allilevine** [comment]
Can we preemptively translate the shorter copy for https://github.com/Automattic/wp-calypso/issues/71670?

Latest copy: pb5gDS-2qa-p2#comment-3181

**Comment by paulopmt1** [comment]
[Sent the new copy for translation](https://github.com/Automattic/wp-calypso/pull/71538).

**Comment by paulopmt1** [comment]
Copy sent, [94% translated so far](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/post-purchase-upsell-design). Nothing else to do here.
