### ISSUE TITLE
Editor: Link hotlinked images

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#7148]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Paste image URL into editor
3. Image automatically embeds
4. Link image to any URL
#### What I expected

The image to remain embedded and linked to the URL I specified, whether the original image link, or another URL
#### What happened instead

The image is no longer embedded and becomes linked text.
#### Browser / OS version

Chrome OSX
#### Screenshot / Video

![image](https://cldup.com/LJvy2HPeoW.gif)
#### Context / Source

A number of users have requested that they be able to easily create linked hotlinked images without having to upload the image to their library. Personally, I like being able to upload an image from another URL so I'm not dependent on that site in the future, but these users are space-conscious and don't want to fill their media library.
Also, this is how the Add Image from URL works in wp-admin, so people wonder why they can't do it in the new editor.

#manual-testing #user-report

**Comment by lancewillett** [comment]
Thanks for this, it's worth discussing at the very least in context of parity of experience between wp-admin and Calypso editors.
