### ISSUE TITLE
[Bug]: Design Picker: Unable to skip design selection

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#71484]
### Quick summary

In the onboarding Design Picker, clicking the "Skip for now" link will lead the user get stuck in a "processing" step.

![image](https://user-images.githubusercontent.com/1525580/209317275-eb65efd5-fe14-4c17-b76d-7a3d5833695a.png)

@Automattic/lego 

### Steps to reproduce

1. Go to `/setup?siteSlug=<site slug>`
2. Select the "Promote myself or business" goal
3. Select any vertical
4. Click "Skip for now" link in the top-right corner of the screen

### What you expected to happen

The user get redirected to My Home.

### What actually happened

The user get stuck in a processing step.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/1525580/209317403-1abd8e93-6cf9-4fde-9d81-ddcb7016a0ca.png">

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by arthur791004** [comment]
We add the check of the action in the [commit](https://github.com/Automattic/wp-calypso/commit/70011367f103054443593856e2468bacc0fccc85) of this [PR](https://github.com/Automattic/wp-calypso/pull/68722). However, it makes the process step won't call the `submit` function anymore if we never set a pending action in the flow. As a result, sometimes the user might get stuck in a "processing" step

**Comment by bangank36** [comment]
Closed as landed
