### ISSUE TITLE
Update documentation for updating prices for Marketplace products

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#71488]
Update PCYsg-J5F-p2 with with suggesions for using `csv` files for bulk updating of prices.

**Comment by cpapazoglou** [comment]
@gcsecsey since you have worked with bulk update scripts, can you include the new tooling, docs, and examples in the fieldguide?

**Comment by gcsecsey** [comment]
I've updated the FG page and also posted a more detailed description here: pdt2If-MS-p2
