### ISSUE TITLE
My home domain upsell: add My Home callout

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#71499]
Add domain callout to My Home. Final copy and design: pebzTe-xR-p2#comment-969

Acceptance criteria:
- [x] Send strings for translation
- [x] Users on free plan with verified email see the domain callout on My Home, under the setup list.
- [x] The callout suggests an available domain based on the current site address. Use [domain-picker](https://github.com/Automattic/wp-calypso/tree/f0d7e63513661d59885f9df051f98811b3aadd94/packages/domain-picker/src/hooks)
- [x] The callout has buttons for both searching for a domain and purchasing the suggested domain.
- [x] Clicks on the callout are tracked.

**Comment by DustyReagan** [comment]
String translations here: https://translate.wordpress.com/deliverables/overview/7758175/

**Comment by DustyReagan** [comment]
> Users on free plan with verified email see the domain callout on My Home, under the setup list.

Do we only want this showing when "My Home" is in the site-setup state? fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Subzr%2Sivrjf%2Sfvgr%2Qfrghc.cuc%3Se%3Qn90p2nqo-og

![site-setup](https://user-images.githubusercontent.com/140841/213747214-7c8fd061-2454-4d6e-9809-853a7551d8b2.png)

**Comment by allilevine** [comment]
> Do we only want this showing when "My Home" is in the site-setup state? [fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Subzr%2Sivrjf%2Sfvgr%2Qfrghc.cuc%3Se%3Qn90p2nqo-og](uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Subzr%2Sivrjf%2Sfvgr%2Qfrghc.cuc%3Se%3Qn90p2nqo-og)

@DustyReagan Can you expand on this a bit? What are the other states, and would this callout make sense in them?

**Comment by DustyReagan** [comment]
> @DustyReagan Can you expand on this a bit? What are the other states, and would this callout make sense in them?

Following up here from our team meeting conversation. I'll look into the other states of My Home to see if it makes sense to include the upsell there. For the moment let's continue forward with the site-setup state as seen in the mockups/Figma.

**Comment by DustyReagan** [comment]
> Users on free plan with verified email see the domain callout on My Home, under the setup list.

This is complete in https://github.com/Automattic/wp-calypso/pull/72380 though the upsell will not be visible until D99116-code is merged. Allowing us to continue with the other tasks on this issue.

**Comment by DustyReagan** [comment]
> The callout suggests an available domain based on the current site address. Use [domain-picker](https://github.com/Automattic/wp-calypso/tree/f0d7e63513661d59885f9df051f98811b3aadd94/packages/domain-picker/src/hooks)

This is completed in https://github.com/Automattic/wp-calypso/pull/72508
