### ISSUE TITLE
My home domain upsell: add domain and plan purchase flow

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#71501]
Add a variation on the domain search flow (domains/add/) to match pebzTe-xR-p2#comment-969

Acceptance criteria:
- [x] We skip the domain search step if the user selects the suggested domain from the My Home callout.
- [x] We show a plan upsell step after the user selects a domain.
- [x] We show a modal if they skip the plan step.
- [x] We show a plan upsell only at the home domain upsell flow
- [x] Make sure we have tracking throughout the flow.

**Comment by paulopmt1** [comment]
Events created:

**Home Domain upsell**

- calypso_my_home_domain_upsell_impression
- calypso_my_home_domain_upsell_search_click
- calypso_my_home_domain_upsell_cta_click

**Plans page upsell**

- calypso_plans_page_domain_upsell_back_click
- calypso_plans_page_domain_upsell_skip_click
- calypso_plans_page_domain_upsell_continue_plan_click
- calypso_plans_page_domain_upsell_cancel_plan_click
