### ISSUE TITLE
My home domain upsell: add suggested domain to CTA path

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#71500]
If the user selects the suggested domain, add it to the cart and skip the search step.

Acceptance criteria:
- [x]  The suggested domain is added to the user's cart.

**Comment by lupus2k** [comment]
We have to make on CTA similar procedure as is used [here](https://github.com/Automattic/wp-calypso/blob/87c4f93d1470bef0c1a52a7519a8deac7a4ce3d7/client/components/domains/register-domain-step/index.jsx#L1291) or [here](https://github.com/Automattic/wp-calypso/blob/87c4f93d1470bef0c1a52a7519a8deac7a4ce3d7/client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx#L282)

**Comment by lupus2k** [comment]
Change how to add the domain, discussed here: p1674667789886409/1674605306.586739-slack-CKZHG0QCR

**Comment by lupus2k** [comment]
Fixed https://github.com/Automattic/wp-calypso/pull/72583
