### ISSUE TITLE
Image Block: Custom sizes cannot be used to stretch images to a different proportion than original aspect ratio

### ISSUE THREAD

**Issue by NoHopeRadio** [Automattic/wp-calypso#71509]
### Quick summary

There are a few aspects to this issue, and I'll try to address the various shades. Basically, if you want to squash or stretch an image using the editor tools, you cannot. It will always bounce back to its original proportions.

Here's my starting point, in the editor at full size: 

![image](https://user-images.githubusercontent.com/71042895/209447858-aebdc8bf-0c7c-4d02-9042-fa056efe3c9a.png)

Now let's say I want to make this image 300px x 500px without cropping it, for whatever reason:

![image](https://user-images.githubusercontent.com/71042895/209447932-320f1902-429f-44de-a2d8-859f44ce9901.png)

Here's how that ends up looking on a simple site:

![image](https://user-images.githubusercontent.com/71042895/209448029-d1b9c9ee-5fc0-4f02-932c-b791c7de25a8.png)

In this case, it preserves the width I set, but it resizes the height of the image to stay in the original proportions, even though the dimensions of the image do appear correctly in the inline attributes. Apparently, a `height: auto;` rule is taking precedence here somehow over the inline rule. It does look like this can be overwritten with a little custom CSS, and it looks like there's already an unused(?) class added to a resized image, `.is-resized` that we can use to limit this to resized images with something like:

```
.is-resized img {
  height: revert-layer;
}
```

![image](https://user-images.githubusercontent.com/71042895/209448161-2ecdad48-aece-46f1-ab83-f942b00ae33d.png)

Moreover, we get slightly different behavior if we change the alignment settings to "None," but maybe not quite so different as it should be.

![image](https://user-images.githubusercontent.com/71042895/209448324-f5f0e3f2-66ba-4e58-a1b0-c5cba7acb1e0.png)

The image is still center-aligned (which maybe it shouldn't be) and still proportioned to the original size, but now it needs a little more specificity for the CSS fix.
```
figure.is-resized img {
  height: revert-layer;
}
```

![image](https://user-images.githubusercontent.com/71042895/209448382-65d6ec4e-a3d5-4c55-9224-4ee6b8dc0c68.png)

On a site with Jetpack's Image CDN module active, we get different results that are harder to fix, as it does present an image with the dimensions set in the editor, but it arrives at this result by cropping rather than stretching:

![image](https://user-images.githubusercontent.com/71042895/209448472-fcb3dd1b-2c5d-4fdf-8d06-48897dd1b14e.png)

A standard CSS fix won't work in this case, as the resizing happens directly in the source image's path, in this case that's `https://i0.wp.com/area51234451.wpcomstaging.com/wp-content/uploads/2022/05/IMG_20141230_205152.jpg?resize=300%2C500&ssl=1`

### Steps to reproduce

1) Add image to page in image block.
2) Resize image against standard proportions
3) Image will either be resized to width set in custom proportions or cropped to dimensions, depending on whether site is simple or atomic (with Jetpack Image CDN module active)

### What you expected to happen

If a user wants to manipulate their images this way, they should be able to, and the image that shows on the site should reflect the one that shows in the editor.

### What actually happened

The image is either resized or cropped, never stretched. This might be at least partially intentional, that we are keeping users from stretching their images, but if that's the case, the options in the editor should be altered to reflect that, and the presence of an `.is-resized` class leads me to believe that there should be a different behavior here.

The fact that there's a different behavior with Jetpack than without may complicate solving this, but a solution for simple sites should at least not interfere with the current Atomic configuration.

### Context

#5802799-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No, seems universal

### Browser, operating system and other notes

The number of users who want to misproportion their images is likely rather low, but the fact that the options set in the editor aren't accurately reflected on the site seems like an oversight that should be corrected, even if it's just calculating the height in terms of the width there with a link icon and an asterisk saying that the proportions of images can't be changed.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Custom CSS:

```
figure.is-resized img {
  height: revert-layer;
}
```

Only really an option for Premium plan users, though.

**Comment by vajrasar** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated (with conditions)
- Tested on Self-hosted - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate the issue on Simple sites, and on the AT sites when the Jetpack has the Performance > Performance & speed modules deactivated. I tested with both FSE and non-FSE themes. The issue also shows up on the core (with or without GB plugin activated).

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cometgrrl** [comment]
@vajrasar Since this reproduces on core, can PAs file a bug under https://github.com/WordPress/gutenberg?

Also, I lowered this to Low priority as I don't think this is going to affect many users, and if they really want a disproportioned image, they can always edit the image manually and upload it as such.

**Comment by tvolpert** [comment]
I just came across this report in a ticket -- I believe it's the same [issue I reported here](https://github.com/Automattic/wp-calypso/issues/61744), since it seems to be the `height` value that is ignored in reverting the image aspect ratio.

**Comment by NoHopeRadio** [comment]
Something I noticed the other day and just ran a quick test to verify whether all the options work (they do!), is that the query loop's Post Featured Image block has convenient options for how the image fits that would be nice to have for the image block too, for consistency if nothing else:

![image](https://user-images.githubusercontent.com/71042895/210622187-c5832227-02f7-4bfc-80ea-e1a10c1dff1d.png)

This Post Featured Image block could potentially be used as a limited workaround if someone wants a different fit for a single image on a page or post.

**Comment by youbrokesomething** [comment]
I agree with @tvolpert, this looks like a duplicate. I'm going to close this ticket in favor of [this issue](https://github.com/Automattic/wp-calypso/issues/61744), which has the core issue linked.
