### ISSUE TITLE
Coblocks Carousel - Add to Gallery Does Not Behave as Expected

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#71503]
### Quick summary

When using the Add to Gallery button in the Coblocks Carousel Block, the Add to Gallery button will instead *replace* the entire gallery with the selected image(s), unless you have first clicked on Edit Gallery. If you click on Edit Gallery, then click Add to Gallery again, then images are added as expected.

https://user-images.githubusercontent.com/12906034/209423177-7b2eec95-1325-4dd6-bb69-01532f9771d5.mp4

### Steps to reproduce

1. Upload at least 2 images to the Media Library
2. Create a page and insert a Carousel Block with at least 1 image.
3. Click on Media Library, then click on an image to add without clicking on Edit Gallery first.
4. Click on Add to Gallery

### What you expected to happen

The selected image(s) should be added to the gallery without replacing all of the existing images.

### What actually happened

The selected image(s) *replace* the existing gallery.

### Context

Discovered while testing a different issue with the Carousel Block.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Clicking on Edit Gallery, then Add to Gallery will allow you to add images to the existing gallery as expected, but this is not readily apparent.

**Comment by vajrasar** [comment]
@masperber Hey! I checked and I was not able to replicate this on the AT site.

1. About the Captions, I think in your example the image had the white background and when you showed how the caption do not appear, it actually was there (if you can check by selecting the image since its white color).
2. I was not able to replicate the second issue at all since the newly selected images do not replace the existing ones.

Can you please re-check if the issue still persist for you?

**Comment by vajrasar** [comment]
@masperber Closing this, but please feel free to reopen if the issue persists.

**Comment by masperber** [comment]
Hi @vajrasar !

On my test site with T23 theme installed, the CoBlocks Carousel block crashes when I attempt to add an image, as shown here:

https://user-images.githubusercontent.com/12906034/221114903-7cf436d5-d3a5-44ed-aebe-65de0c6b76b3.mp4

**Comment by cuemarie** [comment]
@masperber The issue in your latest comment looks to reflect a different issue, reported here: **Coblocks > Carousel: Editor breaks when changing settings or deleting the block https://github.com/Automattic/wp-calypso/issues/71777**

Closing this one again as it's still not replicable. Thanks!
