### ISSUE TITLE
Premium Popover: match Premium plan features

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7153]
I noticed that the Premium popover component (`components/plans/premium-popover`) doesn't match the newly redesigned/reworded Premium plan.

CCing @umurkontaci as you show on the blame list. :)

The following doesn't match...:

![selection_024](https://cloud.githubusercontent.com/assets/4988512/17248009/b078ead0-5597-11e6-8e01-33afa26a92d2.jpg)

...with the following:

![selection_025](https://cloud.githubusercontent.com/assets/4988512/17248035/cd60341e-5597-11e6-8aea-3ec54e0126f5.jpg)

**Comment by umurkontaci** [comment]
PremiumPopover has been removed completely, closing.
