### ISSUE TITLE
Widget Visibility Rule doesn't work for WooCommerce Shop page

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#71544]
### Quick summary

Setting a visibility rule for a widget like this results in the widget not showing on Shop page. Removing the rule, makes it show fine.

![cEWAtE.png](https://user-images.githubusercontent.com/39308239/209804137-0b5899df-4e83-426b-8707-7e53057fd40e.png)

https://user-images.githubusercontent.com/39308239/209805965-d313cc85-e2b2-4c7f-98aa-b7c8b18b013c.mov

### Steps to reproduce

1. Start with an AT site that has WooCommerce installed and Shop page is assigned
2. Add a widget to widget area that would be available on Shop page (e.g. footer)
3. Set a visibility rule to show the widget if the page is Shop
![cEWAtE.png](https://user-images.githubusercontent.com/39308239/209804137-0b5899df-4e83-426b-8707-7e53057fd40e.png)
4. Preview the Shop page
5. Remove the visibility rule you have just added
6. Preview the Shop page

### What you expected to happen

The widget should show if the rule is set like this

![cEWAtE.png](https://user-images.githubusercontent.com/39308239/209804137-0b5899df-4e83-426b-8707-7e53057fd40e.png)

### What actually happened

The widget is not showing if the rule is set, but when removing the rule it shows fine.

### Context

Noticed in 5816142-zd-woothemes where the user set a Social Icons widget to display on Shop page via a visibility rule.

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Tested with several Classic themes: Pique, Independent Publisher 2.

### Browser, operating system and other notes

macOS Monterrey 12.6.1 with Google Chrome Version 108.0.5359.124 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by zdenys** [comment]
I think this one is the same:

- https://github.com/Automattic/jetpack/issues/8343

The [workaround](https://github.com/Automattic/jetpack/issues/20693#issuecomment-899264467) seems to be to set the rule like this:

![](https://user-images.githubusercontent.com/426388/33856315-06420356-dec8-11e7-8ff1-45c4eae863c8.png)

**Comment by vajrasar** [comment]
Closing this in favor of [Widget visibility: integrate with WooCommerce Shop Page](https://github.com/Automattic/jetpack/issues/8343#top) #8343
