### ISSUE TITLE
PremiumPopover should use PlanFeaturesPrice

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7154]
Is it possible to use `PlanFeaturesPrice` (`my-sites/plan-features/price`) instead of `PlanPrice` (`components/plans/plan-price`) in `components/plans/premium-popover`? We are removing the old plans code in #7129 and need to keep `PlanPrice` alive as it's used in `PremiumPopover` too.

CCing @umurkontaci as you are on the blame list. :)

**Comment by umurkontaci** [comment]
Hey @lamosty thanks for reporting this in. We can use the `PlanFeaturesPrice` instead

**Comment by umurkontaci** [comment]
PremiumPopover has been removed completely
