### ISSUE TITLE
Error when registering a domain that was previously connected. 

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#71555]
### Quick summary

When a user tries to register an available domain that was previously connected from an external registrar but has sense been released, the user will receive an error about the domain needing to be connected despite its registration availability. 

Unfortunately, I forgot a screenshot of this error and it is incredibly difficult to reproduce. 

### Steps to reproduce

1. Have a domain connection for a domain that is available for purchase (generally, this only happens when a domain was connected and is released.)
2. Try to register the domain. 

### What you expected to happen

You should be able to register the domain. 

### What actually happened

You get an error about the domain existing with an external registrar even though it is available. 

### Context

28541933-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Remove the domain connection in order to register the domain.

**Comment by vajrasar** [comment]
> generally, this only happens when a domain was connected and is released

I do not have such a domain name at the moment, and hard to replicate. 

I will try to ping someone in contextual guild about this.

**Comment by vajrasar** [comment]
Closing this, and for reference I asked for help here p1676381607467759/1672327299.144149-slack-C0761SX4K

Pls feel free to reopen if the issue persists.
