### ISSUE TITLE
Signup: Remove share icon from theme preview

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#7156]
![screen shot 2016-07-29 at 10 28 24 am](https://cloud.githubusercontent.com/assets/191598/17251543/34826a8e-5577-11e6-99a1-614f99a79a42.png)

There's a random share icon showing in the signup theme preview header. It doesn't do anything when clicked, and should be removed from the signup step.

**Comment by shaunandrews** [comment]
It actually seems like clicking the share icon breaks the preview.

**Comment by michaeldcain** [comment]
The share functionality was in development and only available behind a feature flag. Closing.
