### ISSUE TITLE
[Bug]: Problems and regressions with the new purchase cancellation pages

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#71577]
### Quick summary

Following up on https://github.com/Automattic/wp-calypso/pull/70856 I found a number of issues, some noted already in reviews there and others new.  For now I am just collecting them all in one place to evaluate.

In rough order of importance:

1. The cancellation page looks broken for anything that isn't a plan or a domain -- it has lots of references to plans and the feature list is nonsensical.  Example for Professional Email:

![professional-email](https://user-images.githubusercontent.com/235183/210018241-5bba73a3-557e-4a04-a045-6d153c824633.png)

2. When cancelling a plan and domain for a refund, we show the refund amount.  Screenshot:

![cancel-plan-domain-refund](https://user-images.githubusercontent.com/235183/210018194-0a09e544-c798-43b2-894e-c519593dc4db.png)

But when just cancelling a plan, we don't show it anywhere (this seems like a regression). Screenshot:

![cancel-plan-refund](https://user-images.githubusercontent.com/235183/210018260-5dc33f82-e99e-4a96-96b6-59e0a9159926.png)

3. When neither the plan nor domain are refundable, the page doesn't say when the plan will be removed after cancellation (just saw this is already tracked at https://github.com/Automattic/martech/issues/1366).

4. When cancelling a plan for a refund, the plan is removed right away, but the text at the top talks about features you'll lose when it expires:

![cancel-plan-refund-expires-wording](https://user-images.githubusercontent.com/235183/210018282-1b1a007c-bfbb-46d2-ad96-dac883fbebaa.png)

The text at the top should say something more like "When you cancel your WordPress.com Personal subscription, you will lose access to" in this case.

5. When you cancel the legacy Starter plan, the list of features doesn't make a whole lot of sense to me (also note the "you will lose access to ... Access to managed hosting" double wording):

![cancel-starter-plan](https://user-images.githubusercontent.com/235183/210018296-8fb4efe6-27db-4d78-8318-217c380a6749.png)

6. There are some general wording/grammar issues, although relatively minor (inconsistent tense in the page title, inconsistent capitalization in the button text):

![cancel-plan-wording](https://user-images.githubusercontent.com/235183/210019606-b1373aae-2493-4453-abd3-df070fcf8ee6.png)

7. In the case of a partial refund, it seemed odd to me that "refund" was in green but "partial" wasn't.  Screenshot:

![cancel-plan-with-partial-refund](https://user-images.githubusercontent.com/235183/210018339-e07d154c-f2ec-4d99-a6a0-11341db95df9.png)

**Comment by michaeldcain** [comment]
@southp: I'm just wondering if y'all have any plans to pick the new cancellation design back up. Asking so that we can help with reviews and track/prioritize this issue.

**Comment by southp** [comment]
Good question, @michaeldcain . This will need to be decided by @paulbonahora and @dzver when they are back. However, given that we are wrapping up the retention works, my pesonal preference is that we just move on.

**Comment by dzver** [comment]
Let's put this on hold until the new Plans Grid & Below the fold areas are shipped.

**Comment by Aurorum** [comment]
@DavidRothstein As mentioned in https://github.com/Automattic/wp-calypso/pull/89249#issuecomment-2260655009, I was taking a look at the Payments cancellation page and was going to make a few tweaks (mainly just minor ones around consistency), but I still think it could do with a lot more love. Has this project here been entirely abandoned or could I pick it up if someone from the Payments team would be willing to review? :)

**Comment by michaeldcain** [comment]
@Aurorum, I think this has been effectively shelved for the time being. You're welcome to address any of the issues above and @Automattic/shilling is happy to review any PRs. Let us know if you need another sandbox cookie at any point, and thanks for all of the help!

**Comment by southp** [comment]
Fwiw, the new cancellation page referred here was first reverted by https://github.com/Automattic/wp-calypso/pull/71578 and then fully cleaned-up by several subsequent PRs. Thus, I'd suggest to close this issue and open a new one extracting the action items that are still worth doing. Otherwise the historical context here will be confusing for posterity.

**Comment by DavidRothstein** [comment]
The new version from above was deployed, and to the best of my understanding it doesn't reintroduce any of the problems noted here two years ago... so we can safely close this.

Thank you!!!
