### ISSUE TITLE
Signup: Disable logged-out follow tab in theme previews

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#7158]
![screen shot 2016-07-29 at 9 54 47 am](https://cloud.githubusercontent.com/assets/191598/17251673/bb6e9432-5577-11e6-98a7-1b9a65a82c8a.png)

Some (most?) theme demo sites have the logged-out follow tab turned on. Since there's no good reason for someone to follow a demo site, we should disable this tab.

**Comment by michaeldcain** [comment]
This was handled in a wpcom plugin for demo sites.
