### ISSUE TITLE
[Woo - Free trial] Skip domains selection page

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#71584]
### _Note: The current scope of this work may overlap with work from other teams. To be confirmed._

P2: peapX7-1bf-p2

## User Story

> As a user,
> I want to skip the domain selection step and go straight to my free trial site,
> so that I can immediately begin evaluating the WooCommerce hosted solution

## Acceptance Criteria

```
Feature: Set up a free trial site

Given the user has completed NUX profiler questions
When the user clicks on "Start my free 30-day trial"
Then the system redirects the user to loading screen
And the system creates a site based on the given store name
And the system sets the site plan to free trial
And the system redirects the user to new site after completion
```

## Additional details

Loading screen figma: 4ixWMlzrxllx93tSFsCW6k-fi-6748%3A91686&t=uqpmhen12EFOgJdV-0
Prior art for domain name: https://github.com/Automattic/wp-calypso/pull/71429

**Comment by chihsuan** [comment]
> Note: The current scope of this work may overlap with work from other teams. To be confirmed.

I estimated this issue at 13 story points because we're unfamiliar with domain/checkout pages. I think it would be very helpful if other teams could help with some WPCOM changes.

**Comment by ilyasfoo** [comment]
Good point, @chihsuan. So far, no team has claimed this work yet, but it does seem like Serenity team may have the best context to do the work. Although they may have bigger fish to fry.

In case we have to do it, I've found a prior art on removing domain step https://github.com/Automattic/wp-calypso/pull/71099 that was done for Launchpad by Cylon team. This could be a good reference for us to start

**Comment by adrianduffell** [comment]
Yeah, I think Serenity team are going to have bigger fish to fry, but they can help "hold our hands" to complete this.

**Comment by Addison-Stavlo** [comment]
> In case we have to do it, I've found a prior art on removing domain step https://github.com/Automattic/wp-calypso/pull/71099 that was done for Launchpad by Cylon team. This could be a good reference for us to start

Adding context, the PR noted above is for the new free onboarding flow which is currently a work in progress. This flow does lack a domains step as well and we are replacing that part with some logic to generate a wordpress.com subdomain for the user behind the scenes (using information about the site/blog title, username, etc). We plan to have this ready for cft in the next week or so. 

We (@Automattic/cylon) would also be happy to answer questions or provide guidance related to removing the domains selection as well.

**Comment by ilyasfoo** [comment]
That'll be awesome, @Addison-Stavlo, thanks so much for the context and offering help!

**Comment by chihsuan** [comment]
Hey @ilyasfoo Can we close this? I think it's no longer needed as discussed in Slack.

p1673429419173949/1673364315.302559-slack-C03Q87XT1QF

**Comment by ilyasfoo** [comment]
Thanks for the ping, @chihsuan! Yes, we can close this.
