### ISSUE TITLE
Media & Text: Right-to-Left text direction isn't applied for RTL languages

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#71606]
### Quick summary

A user writing in Hebrew reported that the text in the **Media & Text** block isn't displayed from right-to-left anymore. Other blocks, such as the **Paragraph** blocks are still displayed text from right-to-left.

### Steps to reproduce

1. Set your account to Hebrew or another RTL language such as Arabic.
2. Create new page or post.
3. Add a **Media & Text** block and enter some text in the text part of the block.
4. Notice the content is being displayed from left-to-right as you type.

Here's an example comparing the 2 blocks:

<img width="979" alt="Markup 2023-01-02 at 14 10 15 (1)" src="https://user-images.githubusercontent.com/16645645/210237386-44719b39-e2af-4ae6-99e7-cd4d4e8f90e7.png">

### What you expected to happen

I was expecting the content to be displayed from right-to-left, as with the other blocks.

### What actually happened

Instead, the text is aligned on the left.

### Context

Reported in 35646500-hc

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

The workaround is to edit the content as HTML and add a `dir="rtl"` to the `p` tag but it creates an error, as reported here in #67354.

**Comment by cecilearkay** [comment]
Another easier work around is to use the following CSS:

```
.wp-block-media-text p {
	direction: rtl
}
```

**Comment by dlind1** [comment]
Should be fixed in D96814-code

**Comment by cecilearkay** [comment]
Tested and it works as expected, thank you!

**Comment by dlind1** [comment]
Great, thanks for checking!
