### ISSUE TITLE
Editor: Editing a link doesn't mark the post dirty

### ISSUE THREAD

**Issue by hypest** [Automattic/wp-calypso#7161]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/hypest.org/13
2. Edit a link's URL (like the `the Android DataBinding library` link in the post's first paragraph)
3. Alter the URL via the popup dialog
4. Hit "Save" on the 
#### What I expected

I expected the post to be marked dirty and the little "SAVE" button on sidebar to appear
#### What happened instead

The "SAVE" button on the sidebar did not appear. By the way, opening the editor in another browser tab shows the post without the URL alteration.
#### Browser / OS version

Opera 38.0.2220.41 / Ubuntu 16.04.1

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is an issue as described above (tested in OSX Chrome v54)
