### ISSUE TITLE
Block Editor :: Keyboard shortcut for underline :: Ctrl+U doesn't work. 

### ISSUE THREAD

**Issue by mdtanjid0** [Automattic/wp-calypso#71631]
### Quick summary

The keyboard shortcut Ctrl+U/⌘U ( Underline the selected text. ) with the Block doesn't work. 

That's not related to any specific themes; I have tried with different themes - but it only works with some. 

Keyboard shortcuts are listed here: https://wordpress.com/support/wordpress-editor/keyboard-shortcuts/

### Steps to reproduce

1. Create a page or edit an existing page. 
2. Select some texts. 
3. And check the Ctrl+U/⌘U ( Underline the selected text. )

### What you expected to happen

It should underline the selected text as mentioned [here](https://wordpress.com/support/wordpress-editor/keyboard-shortcuts/). 

### What actually happened

It doesn't underline the selected text. 

### Context

5828655-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Tested the keyboard shortcut `CMD+U` using macOS Monterey Version 12.5.1

- Firefox 111.0.1 - opens a `view-source:` version of the page
- Chrome Version 112.0.5615.49 - No response at all
- Safari Version 16.2 - No response
- Desktop App Version 7.2.0 Release - No response

📌 ACTIONS
- Assigned to Cylon

**Comment by cuemarie** [comment]
Related:

- https://github.com/WordPress/gutenberg/issues/13034
- https://github.com/WordPress/gutenberg/issues/14031

**Comment by Greatdane** [comment]
8197761-zd-a8c
