### ISSUE TITLE
User still able to display WordAds after downgrading to Personal plan.

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#71635]
### Quick summary

User is still able to display WordAds after downgrading plan to Personal. 

### Steps to reproduce

1. Enable WordAds on Premium Site. 
2. Downgrade to Personal Plan. 
3. Access WordAds

### What you expected to happen

No longer able to actively show and profit from new WordAds.

### What actually happened

Still able to access WordAds.

### Context

37505731-hc

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

None

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- did not test to replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Thanks @zachspears ! This is actually a known occurrence. Users who enroll in the WordAds program and later downgrade are not automatically withdrawn from the program. 
- Can't find a good P2 reference for you, but here are some quick examples in context: 
- p1575593683054000/1575593624.053700-slack-C029FQX6U 
- p1665131915430969/1665131294.232309-slack-CJDUN89L1


📌 ACTIONS
- Closed as not relevant
