### ISSUE TITLE
Deprecate custom breakpoint $break-design-preview: 1024px

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#71655]
## Description
Currently, the component `@automattic/design-preview` uses a custom breakpoint of 1024px. This creates a maintenance issue where there are already multiple places in the codebase that has to redefine this custom breakpoint, since `@automattic/design-preview` is meant to be loaded asynchronously.

For the sake of consistency, we should use one of the breakpoints defined in https://github.com/WordPress/gutenberg/blob/trunk/packages/base-styles/_breakpoints.scss, `$break-xlarge: 1080px;` is close enough. 

cc: @SaxonF 

## Acceptance Criteria
- [x] Update all references of `$break-design-preview`, and use `$break-xlarge` instead.
- [x] Ensure that the affected code works as before.

**Comment by mayo7e** [comment]
hi @taipeicoder  can i work on this?

**Comment by autumnfjeld** [comment]
Hi there @mayo7e , we are actually saving this issue for a new dev, to give them some "easy issues" to start with. :)    Thank you for checking! 😄

**Comment by mayo7e** [comment]
hi @taipeicoder ok noted. is there any  issue open i can work on?
