### ISSUE TITLE
Remove ONBOARD_STORE dependency from usePremiumGlobalStyles()

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#71653]
## Description
Currently, the hook `usePremiumGlobalStyles()` ([src](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/sites/hooks/use-premium-global-styles.ts)) depends on the `ONBOARD_STORE`, which is part of the Stepper framework. Now that we are using this hook outside the Stepper framework (#71563), it would be good to decouple the `ONBOARD_STORE` dependency.

## Acceptance Criteria
- [x] Remove Stepper dependency in `usePremiumGlobalStyles()`.
- [x] Update all existing code that calls `usePremiumGlobalStyles()`.
- [x] Ensure that the affected code works as before.

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/75823
