### ISSUE TITLE
WordPress.com Support: The top of the language selector overlay appears behind WordPress.com Admin bar on Chrome

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#71662]
### Quick summary

The top of the language selector overlay appears behind WordPress.com Admin bar on Chrome

### Steps to reproduce

1. Open Chrome
2. Log into WordPress.com at https://wordpress.com/log-in
3. Visit https://wordpress.com/support/
4. At the very bottom, in the footer click on `EN` next to Language
5. See the overlay open up
6. Notice the top part of the overlay

### What you expected to happen

The dark overlay should appear on top of everything else as it has `z-index: 100000`. It works fine in Safari: 

https://user-images.githubusercontent.com/39308239/210540352-434d5698-d842-4c61-b877-15563fa93a36.mp4

### What actually happened

The top part of the overlay (including the `X` for closing it) is covered by the WordPress.com Admin bar.

https://user-images.githubusercontent.com/39308239/210539776-8e6b5a7a-4229-4cf8-98cf-512ec700a823.mp4

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

It's only on https://wordpress.com/support/ that uses WordPress.com Support v2 theme.

### Browser, operating system and other notes

macOS Monterrey 12.6.1 with Google Chrome Version 108.0.5359.124 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Use a different browser than Chrome.

**Comment by escapemanuele** [comment]
Fixed with the new support site.
