### ISSUE TITLE
Post purchase upsell: fix conversion tracking

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#71669]
The path prop on the `calypso_page_view` event is returning `checkout/thank-you/:site/pending/:order_id` for the upsell page, instead of `/checkout/:site/offer-plan-upgrade/business/:order_id`. We'll need to fix that or add another event to track upsell page impressions.

Acceptance criteria:
- [ ] We can track upsell page impressions.

**Comment by DustyReagan** [comment]
Noting a previous P2 post about this issue here pduY5I-iQ-p2

**Comment by DustyReagan** [comment]
[#71766](https://github.com/Automattic/wp-calypso/pull/71766) had to be reverted info here: pb5gDS-2ur-p2

Added more unit tests here:
https://github.com/Automattic/wp-calypso/pull/71896
https://github.com/Automattic/wp-calypso/pull/71942

Fixed the 1st PR and published: https://github.com/Automattic/wp-calypso/pull/71897
