### ISSUE TITLE
Post purchase upsell: set up A/B experiment for copy

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#71670]
We want to test the current long copy vs. new, shorter copy for post purchase upsell conversions.

See: pb5gDS-2qa-p2#comment-3199

Acceptance criteria:
- [ ] We've implemented an A/B experiment with the ExPlat team to test long vs. short copy.

**Comment by paulopmt1** [comment]
A/B experiment set, waiting for the new metric to be created (pbmo2S-1Sz-p2) so we can finish the experiment set up.

**Comment by allilevine** [comment]
@paulopmt1 Are we good to close this one?

**Comment by paulopmt1** [comment]
Yes, based on our last conversation this one is done now: p1673541619155519/1673289198.965569-slack-CKZHG0QCR
