### ISSUE TITLE
Stats: Extract back/forward arrows into a reusable component

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#71677]
> it would be nice to refactor the back/forward arrows into a reusable component https://github.com/Automattic/wp-calypso/pull/71343#discussion_r1054822618

`YearNavigation`: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/annual-highlights-section/year-navigation.tsx#L33-L54

`StatsPeriodNavigation`: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/stats-period-navigation/index.jsx#L85-L104

**Comment by a8ck3n** [comment]
Addressed in #71755.
