### ISSUE TITLE
Checkout: Attempting to purchase Guided Transfer with premium theme active gives poor error message

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#7169]
#### Steps to reproduce
1. Starting at URL: https://en.support.wordpress.com/guided-transfer/
2. Add a Guided Transfer to the cart of a site that's running  premium theme
3. Go through checkout
4. See this message:

> This blog already has some of these upgrades. Did you mean to renew your subscriptions?
#### What I expected

An error message explaining that the site is running a premium theme, along with a link where I can change themes to allow me to procede with the guided transfer.
#### What happened instead

Error message not related to the issue:

> This blog already has some of these upgrades. Did you mean to renew your subscriptions?

The blog does not already have a Guided Transfer upgrade.
#### Screenshot / Video

![checkout_ _923_is_numbered__not_lettered_ _wordpress_com](https://cloud.githubusercontent.com/assets/933450/17257516/704545a0-5590-11e6-9c01-2ca5abf147b5.jpg)

**Comment by alexjgustafson** [comment]
Reported by user in 2756153-t

**Comment by SiobhyB** [comment]
I was able to replicate the above when attempting to purchase Guided Transfer with custom fonts active.

**Comment by kevmarsden** [comment]
Reported in 2858612-t by a user with custom fonts.

**Comment by starxedsteph** [comment]
This wording issue came up in 556856-chat.

Knowing that I'd seen it before, I've done a bit of digging and this seems to come up quite often.  I did a search of chat transcripts for the phrase "This blog already has some of these upgrades" and found it comes up about 3 times a week.  Spot checking those, all the chats I looked at with this phrase were in regards to the Guided Transfer purchase.
