### ISSUE TITLE
Global Styles: Live site not respecting the font set on Global Styles

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#71690]
### Quick summary

Hello! I've been playing around on my personal website when I noticed the font I set for the Heading in Global Styles is visible properly on the editor, but not on the live site.

I noticed this issue after I noticed the New Browse Mode on Site Editor is launched/active on my dashboard. I thought it was my browser cache acting up, but I noticed it happens on different browsers proxied _and_ unproxied and persisted after a couple of days.

### Steps to reproduce

1. Open Site Editor
2. Open Global Styles
3. Choose Typography
4. Choose "Headings"
5. Set the font for Headings to any custom font. In my case, I use the font "Fraunces"
6. Click "Update" to save the changes

![Screenshot 2023-01-05 at 10 35 20 AM](https://user-images.githubusercontent.com/44726232/210688650-41f41023-9cb2-4a40-9e0e-26a00d4d3cc7.png)

### What you expected to happen

I expect the change to be appropriately saved and reflected on both editor and the live site. 

### What actually happened

It is saved properly on the editor. Notice the customized font on the blog post title:

![Screenshot 2023-01-05 at 10 36 17 AM](https://user-images.githubusercontent.com/44726232/210688774-9b435f36-61a8-4354-a161-f91b6e31343a.png)

But the live site shows a different font.

![Screenshot 2023-01-05 at 10 37 02 AM](https://user-images.githubusercontent.com/44726232/210688844-637e2488-ce74-4279-a8e6-7898e55b458e.png)

According to the CSS (Browser Inspector,) the font should be "Fraunces":

```
h1, h2, h3, h4, h5, h6 {
    font-family: Fraunces;
}
```

I thought the issue happened because the Heading blocks were inside the Group Block, but when I tried a separated Heading Block outside the Group Block, the issue persists 🤔 

Interestingly, this issue does not appear when I set the customized font on the block _outside_ Site Editor (for example, I set a custom font on a text/paragraph on the post/page editor.)

### Context

Personal test on my personal blog

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Not sure if this is theme-specific or not, but I'm using Twenty Twenty Three.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by retnonindya** [comment]
I remember my teammate mentioned the same thing a couple of weeks ago. Here it is:
https://github.com/Automattic/wp-calypso/issues/71362 

> The theme's font uses a default serif typeface instead of the one in the theme's preview.

The issue should be solved, but it seems like it returns.

**Comment by dsas** [comment]
Duplicate of https://github.com/Automattic/wp-calypso/issues/71641
