### ISSUE TITLE
WPCOM elasticsearch query to get the total cost of OpenAI

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#71726]
We need to be able to automatically switch the AI features off if we exceed a certain cost ($15K).

We are already logging the `properties.cost` in logstash queries.

We need to find a way to use the `es_api_search_index` WPCOM function to aggregate this cost. If it exceeds $15K we want to automatically return `false` in the `OpenI::active` method. That way, it will automatically turn off further queries.

the code should live in the lib introduced in D97118-code

**Comment by millerf** [comment]
Done in D97333-code#inline-347576
FTR moved to use `bump_stats_extras` instead of relying on logstash data.
