### ISSUE TITLE
Stats: Blaze & Yoast CTAs on Traffic page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#71725]
Details: p1HpG7-jIF-p2
@jsnmoon @paulopmt1 @grzegorz-cp @DustyReagan @a8ck3n  @dognose24 - Just tagging everyone I know on each team to coordinate this work. See the link above for details. 

Collab between team Explorers and Red. We need to implement some new Blaze and Yoast CTAs throughout the traffic page within stats.

### Preview

![Image](https://user-images.githubusercontent.com/214813/210854222-f49baf6f-2882-4743-8f12-09af7931a8b2.png)

![Image](https://user-images.githubusercontent.com/214813/210854281-2fca6cfb-ab59-4221-a58f-60ea2df00bf6.png)

## Mini-carousel

![Image](https://user-images.githubusercontent.com/214813/210854529-80825269-258d-497c-beaf-f8298409c1eb.png)

![Image](https://user-images.githubusercontent.com/214813/210854563-0de532e7-8f3f-4d4e-8d81-e4348d9344c3.png)

## Empty State Carousel

![Image](https://user-images.githubusercontent.com/214813/210854612-e162148e-38c9-4018-9262-b167d657a3a3.png)

![Image](https://user-images.githubusercontent.com/214813/210854647-67037959-a356-4f13-8ca7-a36989330c63.png)

## Top posts & pages CTAs

![Image](https://user-images.githubusercontent.com/214813/210854703-c841d881-c4ae-4f47-be8d-bf9ca1900d01.png)

**Comment by paulopmt1** [comment]
Here is a follow-up task on the mini-carousel that the Explorers team will prioritize: 1460-gh-Automattic/dotcom-forge. @jsnmoon do you think the second part (Top posts & pages CTAs) of it is something your team would like to tackle?

**Comment by jsnmoon** [comment]
@paulopmt1: The iconography update task is being tracked [here](https://github.com/Automattic/wp-calypso/issues/71733).

**Comment by jeffgolenski** [comment]
Update on the visuals:
* New icon based on p2 convos
* CTA's should utilize the primary theme color based on the wordpress.com user settings, not the gradients in the dev specs! 

<img width="6559" alt="Blaze General CTA - Option 3 (Blaze   Yoast)" src="https://user-images.githubusercontent.com/214813/211865901-bf3d1df3-d718-41aa-b678-8601b828f22e.png">

**Comment by jsnmoon** [comment]
@paulopmt1: I believe this task is done! Can you confirm?

**Comment by jsnmoon** [comment]
Marking this as complete!
