### ISSUE TITLE
Task: Prevent billing emails for eCommerce trial plan

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#71731]
### Details

As noted in this review comment for our initial work for the new plan, D96941-code#2006565, we are correctly preventing renewals, but we are not preventing various billing emails from being queued up for the new product.

As discussed in D96941-code#2007935, we should filter out emails for subscriptions that can't be renewed.

**Comment by markbiek** [comment]
Here's a list of the billing events that I think we need to filter on. There really aren't very many distinct events, though each of these gets called a bunch of different times so the filter will need to be added in multiple places.

- `EVENT_PRE_RENEW_NOTIFY`
- `EVENT_MISSING_PAYMENT_METHOD_NOTIFY`
	- already excluded by `exclude_free_ownerships_filter`
- `EVENT_WPCOM_SUBSCRIPTION_AUTO_RENEW_DISABLED_NOTIFY`
- `EVENT_FETCH_AND_LOCK_MAXIMUM_RENEWAL_PRICE`
- `EVENT_AUTO_RENEW_DISABLED_NOTIFY`

These two filters seem like they would be applicable. But they're only for cases where subscription and ownership data are out of sync which I don't think applies to the WooExpress trial.

- `EVENT_WPCOM_SUBSCRIPTION_PRE_RENEW_NOTIFY`
- `EVENT_WPCOM_SUBSCRIPTION_UNBILLABLE_PAYMENT_METHOD_NOTIFY`

(Events are in fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sovyyvatqnqql%2Sfep%2Sjcpbz%2Sjcpbz.cuc-og)

**Comment by markbiek** [comment]
Also worth noting that all of the above events are passed ownership data except `EVENT_WPCOM_SUBSCRIPTION_AUTO_RENEW_DISABLED_NOTIFY` which receives subscriptions instead.

**Comment by markbiek** [comment]
WIP diff: D99209-code

**Comment by daledupreez** [comment]
We shipped D99209-code to production last week.
