### ISSUE TITLE
Me: unable to access sidebar on iOS 7.1.2

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#7175]
When viewing `/me` on iOS 7.1.2, clicking the header link to display the sidebar does nothing.

<img width="308" alt="screen shot 2016-07-29 at 4 15 33 pm" src="https://cloud.githubusercontent.com/assets/2036909/17262192/0204f0a0-55a8-11e6-9507-6602672159d1.png">

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me
2. View at mobile width with Safari on iOS 7.1.2
3. Click the "< My Profile" header.

#### What I expected

The sidebar to slide out (with the Gravatar and Sign Out button).

<img width="306" alt="screen shot 2016-07-29 at 4 19 47 pm" src="https://cloud.githubusercontent.com/assets/2036909/17262250/4d40123e-55a8-11e6-8779-26123f5657e9.png">

#### What happened instead

No effect. (Probably some JavaScript error, but who knows until we can reproduce it.)

#### Browser / OS version

Safari on iOS 7.1.2 on an iPhone 4s

Reported (and demonstrated) to me in person by: damcho@mac.com
#user-report

**Comment by lancewillett** [comment]
Thanks for the report — we aren't supporting iOS versions that far back — usually, latest stable and 1 back. Closing for now since it's unlikely to be a common case and we have bigger priority bugs to fix.
