### ISSUE TITLE
Site Editor - Exiting doesn't respect current environment.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71760]
Currently when we leave the site editor while on horizon.wordpress.com, the exit link directs us back to production wordpress.com. 

We want the site editor's exit to keep us in whichever environment we are currently in, as the post/page editors currently do.

<img width="508" alt="Screen Shot 2023-01-06 at 8 42 58 AM" src="https://user-images.githubusercontent.com/28742426/211024237-5d10e0a6-a178-4e46-b601-dfe5fdc8de59.png">

Recent art related to site editor close button:
* https://github.com/Automattic/jetpack/pull/27601 
* https://github.com/Automattic/wp-calypso/pull/71464

I think the former is the culprit as it defines the return url and hardcodes the `https://wordpress.com/home/` section of it. And the latter just uses whatever href is defined on the element.

**Comment by jeyip** [comment]
Working on the wp-admin back to dashboard button redirect next
