### ISSUE TITLE
[Bug]: Broken redirect to edit a page or post for Jetpack sites with a custom WordPress core path

### ISSUE THREAD

**Issue by xartuu** [Automattic/wp-calypso#71767]
### Quick summary

I use [Bedrock Wordpress](https://roots.io/bedrock) and host it on my own hosting. I have the [Jetpack plugin](https://wordpress.org/plugins/jetpack/) installed and am using the Wordpress Desktop app for Mac.

Due to a change in the folder structure in Bedrock - Wordpress core is under `/wp` - **editing posts and pages does not work** - both in the desktop application and on wordpress.com.

### Steps to reproduce

1. Install Wordpress Bedrock to change the folder structure - Wordpress core should be under *`example.com`*`/wp`.
2. Jetpack plugin installation.
3. Connecting Jetpack to your Wordpress.com account.
4. Trying to edit a post or page on https://wordpress.com/posts or https://wordpress.com/pages or through the desktop application.

### What you expected to happen

After selecting a page or post and clicking the edit button, the edit page or post window should open.

### What actually happened

When you select a post (a page too) and click edit, `https://wordpress.com/post/`*`example.com`*`/`*`id`* page opens up. This page redirects us to `https://`*`example.com`*`/wp-login.php?redirect_to=https%3A%2F%2Fwordpress.com%2Fpost%2F`*`example.com`*`%2F137%3FauthWpAdmin%3Dtrue` page that doesn't exist, instead of `https://`*`example.com`*`/wp/wp-login.php`*`...`*. It doesn't really take into account the real wordpres core address (`/wp`), which is indicated in [wordpress.com settings](https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs).

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Context

Editing pages and posts

### Platform (Simple, Atomic, or both?)

Self-hosted

### Other notes

The error occurs with a custom Wordpress core path. This includes when using Wordpress Bedrock.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by cometgrrl** [comment]
Since this affects only users using a custom Wordpress core path (such as Bedrock users), lowering the priority to normal.

**Comment by cometgrrl** [comment]
[Eric says](p1673480668486319-slack-C01LXBU1N21):

> It might be as simple as using the siteurl option instead of the home option.

**Comment by xartuu** [comment]
Thanks for fixing it!
