### ISSUE TITLE
Reader: Custom HTML block link + image doesn't display

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#71775]
### Quick summary

When a post that uses the Custom HTML block to display a hyperlinked image is viewed in the Reader, the contents of that block do not (always) display. On a post made by an affected user, the contents of the block don't display at all; it looks like there's nothing in that space, even though the contents of the block (a linked image) are visible on the original post on their actual website.

This is happening to HTML code that's just an anchor (`<a>` tag) surrounding an image (`<img>` tag)—no JavaScript is involved, although the URL does contain some parameters.

Viewing the source of the affected post in the Reader, I see that the HTML for the anchor tag is there, but there's nothing inside of it, so there's nothing that can actually be clicked on—the image is being stripped out and leaving an "invisible", unclickable link.

![missing html in link](https://user-images.githubusercontent.com/82622339/211125172-0f0f1b67-4ae8-43b5-bcfe-3cc94ab14f48.png)

On the user's site (Simple site, Dara theme), they can view the result of the block (the hyperlinked image) on their live site, but no one seems to be able to see it in the Reader. Another HE was able to replicate on a test site. However, when I used the same code on my own test site, I am able to see the same HTML on my own test post in the Reader (even though I can't see it on the user's post). I tried the same theme, same WordPress.com plan, made sure they didn't have it nested inside of other blocks, etc.. I'm not sure why it works on my test site but not the user's site/the previous HE's test.

### Steps to reproduce

1. Create a new post.
2. Add a Custom HTML block to the post, and add HTML to it consisting of an anchor tag `<a>` and an image tag `<img>`, so that the HTML should result in a hyperlinked image.
3. Publish the post and view it in the Reader.

The specific HTML in the user's case is

```
<a target="_blank" href="//www.blenza.com/linkies/links.php?owner=cmchesebro&postid=15Dec2022b&meme=13466"><img border="0" src="//www.blenza.com/linkies/graphic.php?owner=cmchesebro&postid=15Dec2022b&meme=13466" /></a>
```

### What you expected to happen

The contents of the HTML block should be visible when reading the post in the Reader, and you should be able to see an image that can be clicked to open another page:

<img width="891" alt="link functioning" src="https://user-images.githubusercontent.com/82622339/211125636-23bc05df-c43a-49af-9896-95d2d6967c47.png">

### What actually happened

No image is visible or clickable. In the Reader post's HTML, there's a hyperlink that doesn't contain any content and so doesn't function. (See screenshot in summary.)

### Context

User reported here: 5837484-zen

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Intermittent

### Severity

None

### Available workarounds?

None

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate 
- Tested on AT - Could Not Replicate 
- Tested on Self-hosted - Could Not Replicate 
- Replicable on Core - No


📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- Hi @thekingsprojects ! Were you able to replicate this on a test site? If you were able to, please add those details, and feel free  to reopen.

**Comment by thekingsprojects** [comment]
Hi @kavyagokul ! No, I was never able to replicate on a test site myself, but looking back at the ticket notes, it looks like the previous HE was able to.

@sguzovskaia , if you remember this case, could you offer any insight into how you were able to replicate this on your test site? If so, we can maybe reopen this. Much appreciated!
