### ISSUE TITLE
Plans: /my-plan should show domains even if already upgraded

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#7177]
The intention of /my-plan is to showcase what the user can do with the plan that they purchased. Currently, if the user has added a domain upgrade to their plan, we remove any reference to domains being included in plans.

![](https://cloudup.com/cIO6PbG9hYJ+)

Regardless of whether or not a user has added a custom domain for their site, we should showcase that the domain is included in the plan, perhaps even highlighting the domain(s) they have associated with the site here.

#### Steps to reproduce
1. Go to /my-plan on a site with a plan but **no** custom domain upgrade
2. Notice that there's a nudge to add a custom domain in the "what your plan includes" text
3. Go to /my-plan on a site with a plan **and** a custom domain upgrade
2. Notice that there is no mention of domains being included in any of the plans

**Comment by mtias** [comment]
> Regardless of whether or not a user has added a custom domain for their site, we should showcase that the domain is included in the plan, perhaps even highlighting the domain(s) they have associated with the site here.

Agreed. Don't know why the domains module is not being used here? cc @artpi

**Comment by meremagee** [comment]
Hm, using the `domains module` here was very likely explicitly removed because it doesn't always make sense in this context. For instance, for this site, I have a custom domain - the domain module will always nudge me to "get my custom domain," which is irrelevant:

![](https://cloudup.com/cj4WZof5l-R+)

I was more suggesting the following:
- if user does not have custom domain, show module with CTA to secure their custom domain
- if a user does have a used custom domain subscription, show that they are using it without a nudge to "get your custom domain," since it's already been... gotten.

**Comment by mtias** [comment]
Well, the domains module should be taking that into account.

**Comment by lamosty** [comment]
Sorry, this is my fault. When redesigning My Plans page to use two-column layout (and doing quite a refactor in #7410), I wrongly copied old domains logic instead of using the new one introduced in #7311. The code is still there in `upgrades/checkout-thank-you/custom-domain-purchase-detail`, we just need to use it in `ProductPurchaseDetails` instead of what we use now. Will create PR soon

**Comment by meremagee** [comment]
Closing this given updates in https://github.com/Automattic/wp-calypso/pull/7311

Thanks @lamosty!
