### ISSUE TITLE
Stats: Set "Stats" sidebar menu item as selected for the Store page

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#71787]
| Traffic page | Store page |
| --- | --- |
| <img width="819" alt="截圖 2023-01-09 下午3 50 00" src="https://user-images.githubusercontent.com/6869813/211261570-19f56bdf-0c1a-47c0-a57f-58f2c1115a6b.png"> | <img width="921" alt="截圖 2023-01-09 下午3 50 12" src="https://user-images.githubusercontent.com/6869813/211261607-146391a0-ff14-47fa-8e3a-2dbceaae344b.png"> |

**Comment by kangzj** [comment]
closed by #74028
