### ISSUE TITLE
Themes Dashboard: Third-Party Theme Live Demo option displays blank screen on Simple Sites

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#71780]
### Quick summary

It is possible to search for third-party themes from the Theme dashboard on simple sites and then view info about the theme, but if you click the Live Demo option from the three-dots menu, a blank screen displays.

### Steps to reproduce

1. Go to the Theme dashboard page of a simple site
2. Search themes for "Astra"
3. Click the three dots and select **Live Demo**

### What you expected to happen

I expected to either see the live demo, or see a message telling me that I needed a Business plan to access this option (or if it was a Business plan, that I needed to activate the Business plan features)

### What actually happened

A blank screen displays.

### Context

5848051-zen

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

None

### Severity

None

### Available workarounds?

None

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated 
- Tested on AT - Replicated


📌 FINDINGS/SCREENSHOTS/VIDEO
- When the preview tries to open in a frame, it shows a blank page
- Clicking on the frame opens a new tab with WP.org's really useless preview page

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/80310
