### ISSUE TITLE
Task: Audit UI to identify issues with free ecommerce trial

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#71793]
### Details

With the initial introduction of the ecommerce trial plan, we know that various places in Calypso won't work as expected. We want to perform an audit so we can identify areas where we will need to make improvements.

WIP record of the audit is in paYKcK-2A9-p2

**Comment by daledupreez** [comment]
@sixhours, would you consider this task wrapped up? I created it so we had a way to track/reflect your work on the audit.

**Comment by sixhours** [comment]
Yep! Let's close it out, the post is done; I'm sure we'll find other issues along the way.
