### ISSUE TITLE
WooExpress Trial: Plans page

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71807]
We're waiting on designs for the proposed Plans page at `/plans/[siteSlug]` for the eCommerce trial. As of now, the Plans page does not allow a user to upgrade when on the trial:

![screen-shot-2023-01-05-at-11 00 53-am](https://user-images.githubusercontent.com/2124984/211387009-9ce91a03-ea70-4827-974d-79765c5b40e3.png)

**Comment by daledupreez** [comment]
Designs are in peapX7-1rb-p2 - we're going to focus on a single plan implementation for now (though we may change that decision and approach).
