### ISSUE TITLE
State: Consolidate preferences and current user settings

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7180]
Preferences are simply a subset of the current user's settings from the `/me/settings` endpoint. I think we ought to create a new state subtree at `state.currentUser.settings` to request and track this data. We may or may not want to continue having a separate `state.preferences` subtree but it should simply defer many of its action creators to the current user settings action creators, and update its reducer state in response to current user settings being received.

cc @artpi

**Comment by lancewillett** [comment]
Still relevant? Will be closed soon if no traction.

**Comment by aduth** [comment]
Yes, still relevant.
