### ISSUE TITLE
WooExpress Trial: Add plan name in the sidebar

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71809]
The plan name is usually shown next to Upgrades in the Calypso sidebar. For the eCommerce trial, this value is blank:

<img width="447" alt="screen-shot-2023-01-05-at-10 57 21-am" src="https://user-images.githubusercontent.com/2124984/211388202-fe2e9b68-b492-44e7-949b-b9173dfab2ea.png">

Should it say "eCommerce" or "eCommerce Trial" or something else?

**Comment by sixhours** [comment]
~~Started this in D97487-code~~

**Comment by sixhours** [comment]
Since D97487-code shipped I'm seeing the correct text in the sidebar for all new sites created via the WooExpress setup URL. Can anyone else confirm they're seeing the same before I close this out?

**Comment by markbiek** [comment]
For posterity, I'm not currently seeing the plan name:

p1673966251611829-slack-C0Q664T29

**Comment by sixhours** [comment]
I'm not seeing it now, either 😂 Will keep digging.

**Comment by sixhours** [comment]
OK, I think we *do* need to update Jetpack so its `admin-menu` endpoint for Atomic sites recognizes the new plan: https://github.com/Automattic/jetpack/pull/28394

**Comment by sixhours** [comment]
Never mind, it appears to be working now. Closing!
