### ISSUE TITLE
WooExpress Trial: My Plan page

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71808]
The My Plans section at `/plans/my-plan/[siteSlug]` is broken for sites on the eCommerce trial. We're waiting on design for further instruction as to what this should look like.

![screen-shot-2023-01-05-at-10 59 24-am](https://user-images.githubusercontent.com/2124984/211387654-e9996ca5-0d8c-454a-b4a9-6ef7fa18e223.png)

**Comment by nelsonec87** [comment]
https://github.com/Automattic/wp-calypso/pull/72297 fixed the error.

**Comment by nelsonec87** [comment]
Figma file with the designs: jBwlERMS350NqhJNHZzAVF-fi-19%3A22589
