### ISSUE TITLE
WooExpress Trial: Theme Showcase updates

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71815]
The Theme Showcase at `/themes/[siteSlug]` needs to give trial users access to Unlimited Themes, including the first-party WooCommerce-enabled themes. Currently the Showcase treats these themes as requiring an upgrade to Business.

Clicking a theme's three-dots menu shows "Upgrade to activate"; clicking this brings the user to checkout with the Business plan in the cart:

<img width="440" alt="screen-shot-2023-01-09-at-9 52 33-am" src="https://user-images.githubusercontent.com/2124984/211411640-bbea8c47-7d6c-419a-ac67-d61ae0d1e8cf.png">

Individual theme pages like `/theme/tazza/[siteSlug]` also redirect to checkout with Business in the cart.

![screen-shot-2023-01-09-at-9 51 14-am](https://user-images.githubusercontent.com/2124984/211411634-3d4a0971-8f86-4486-bc6c-35ce836ebd90.png)

Clicking on "Install new theme" from the Theme Showcase also shows an upgrade that points directly to checkout:

![screen-shot-2023-01-09-at-10 41 58-am](https://user-images.githubusercontent.com/2124984/211411642-aab2cbef-e70d-48f7-ac06-18e5abaf955d.png)

We need to decide if these upsells should point to the Plans page, or add a different plan at checkout instead.

**Comment by sixhours** [comment]
Good to note I'm also seeing an upsell on that page with the eCommerce plan that I wasn't before:

<img width="1357" alt="Screen Shot 2023-01-16 at 11 22 32 AM" src="https://user-images.githubusercontent.com/2124984/212724862-ef85aa29-1773-4965-870d-8bbc633f7fad.png">

**Comment by daledupreez** [comment]
I've just retested this and had no problems switching to standard Premium themes when on a site with the eCommerce trial plan.
