### ISSUE TITLE
Writing Prompts - Add tracks and stats

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#71814]
### Details

We want to track engagement with Writing prompts. We need to identify what track events are missing and add bump stats to allow an easy way to measure user engagement with writing prompts feature.

Things to check:

### Tracks events

- [x] Clicked to skip the current prompt to see additional prompts
- [x] Clicked to answer a prompt from My Home card
- [x] Clicked to answer a prompt from a notification
- [x] Published a post that answered a prompt (include the last_editor property using `_last_editor_used_jetpack` post meta, so we know if the response came from web or mobile editors)
- [x] Clicked to hide the writing prompt My Home card

#### Additional concerns

- Each event should include the prompt id when relevant (in addition to the usual data about site, user, etc.)
- Align event names and properties with any existing mobile stats that already exist, where possible

### Bump stat

- Published a post that answered a prompt

### Related

See p1673289351258159-slack-C03NLNTPZ2T

**Comment by eoigal** [comment]
Added patch to add missing answer prompt id tracks event when a post is published. Also bumps stat to allow us to track how often a post is published from a writing prompt (and show us which prompt ID is the most popular).

code-D97474

**Comment by eoigal** [comment]
Most of the tracks are already in place thankfully.

- Clicked to skip the current prompt to see additional prompts
    - **not found**
- Clicked to answer a prompt from My Home card
    - `/tracks/events/event.php?eventname=calypso_customer_home_answer_prompt`
-  Clicked to hide the writing prompt My Home card
    - `/tracks/events/event.php?eventname=calypso_customer_home_task_skip`
- Clicked to answer a prompt from a notification
    - `/tracks/events/event.php?eventname=calypso_notifications_answer_prompt`
- Published a post that answered a prompt (include the last_editor property using `_last_editor_used_jetpack` post meta, so we know if the response came from web or mobile editors)
    - `/tracks/events/event.php?eventname=wpcom_post_publish`

**Comment by creativecoder** [comment]
> Most of the tracks are already in place thankfully.

Nice, that's good.

> `wpcom_post_publish`

Do we know from the existing Tracks event if the post publish was in response to a writing prompt? If not, I think it's worth creating a new event.

**Comment by eoigal** [comment]
I've deployed code-D97474. 

This patch adds a track event prop with the writing prompt ID. We know if the `wpcom_post_publish` is answering a writing prompt by checking the post meta for `_jetpack_blogging_prompt_key` meta value.

<img width="333" alt="Screenshot 2023-01-11 at 11 48 20" src="https://user-images.githubusercontent.com/5560595/211802552-4c54c63c-6a07-4831-bf6c-793d25ef611a.png">

We should also see bump stat for `/s/wpcom_post_writing_prompt_publish/` but haven't seen it yet. Not sure if related to testing on sandbox or async job takes longer than expected.

**Comment by eoigal** [comment]
Fixed issue with new stat. There is a 32 char limit and the name had 33 chars!

Changed from `/s/wpcom_post_writing_prompt_publis/` to `/s/wpcom_post_prompt_publish/`

**Comment by eoigal** [comment]
New event to track when a user skips today's prompt and chooses to answer an alternative prompt has been added in https://github.com/Automattic/wp-calypso/pull/72008.

The event is `calypso_customer_home_skip_prompt`. It was registered in https://github.com/Automattic/tracks-events-registration/pull/1340.

**Comment by eoigal** [comment]
All track events are now in place. If we need to add any more we can open an new task;

- Clicked to skip the current prompt to see additional prompts
    - `/tracks/events/event.php?eventname=calypso_customer_home_skip_prompt`
- Clicked to answer a prompt from My Home card
    - `/tracks/events/event.php?eventname=calypso_customer_home_answer_prompt`
-  Clicked to hide the writing prompt My Home card
    - `/tracks/events/event.php?eventname=calypso_customer_home_task_skip`
- Clicked to answer a prompt from a notification
    - `/tracks/events/event.php?eventname=calypso_notifications_answer_prompt`
- Published a post that answered a prompt (include the last_editor property using `_last_editor_used_jetpack` post meta, so we know if the response came from web or mobile editors)
    - `/tracks/events/event.php?eventname=wpcom_post_publish`

**Comment by eoigal** [comment]
Added new event to track clicks to `View All Responses` link in writing prompt card in https://github.com/Automattic/wp-calypso/pull/72369.

- Clicked `View All Responses` link
    - `/tracks/events/event.php?eventname=calypso_customer_home_view_all_responses`

**Comment by eoigal** [comment]
Aggregation of stats can be found in pe7F0s-zV-p2
