### ISSUE TITLE
Odyssey Stats: Restore Jetpack upsell section

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#71820]
![Image](https://user-images.githubusercontent.com/6406071/213558155-f7dad638-85d7-471d-9f40-a49621bdd8bf.png)

Restore the Jetpack upsell section that used to exist in the old Jetpack Stats.

**Comment by kangzj** [comment]
The original footer code could be found at: 

https://github.com/Automattic/jetpack/blob/1dbbc117e22ebb867515020b58b773b4eafa3b1f/projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-admin-page.php#L425

**Comment by wilmersondasilva** [comment]
This is the new design of the upsell section. I checked with @jeffgolenski and I'm following this new design.

![Image](https://user-images.githubusercontent.com/6406071/213558155-f7dad638-85d7-471d-9f40-a49621bdd8bf.png)

**Comment by wilmersondasilva** [comment]
I also talked to @kangzj about if we should implement this one on the Calypso or Jetpack side. I decided to start implementing it on Calypso and move it to Jetpack if needed.

**Comment by jeffgolenski** [comment]
@wilmersondasilva This upsell section is **not** to display within wordpress.com, just within the Jetpack stats in wp-admin, please!

**Comment by wilmersondasilva** [comment]
I'm aware of that, @jeffgolenski! It'll work exactly as you described. Thanks!

**Comment by jeffgolenski** [comment]
Excellent! Thank you sir!
