### ISSUE TITLE
Stats: Investigate keyboard triggers for navigation arrows

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#71836]
Per [this comment](https://github.com/Automattic/wp-calypso/pull/71755#discussion_r1063738685), we should confirm keyboard navigation is working correctly and if not, re-add the code that explicitly monitors for `space` and `return`. Also, are `enter` and `return` the same?

My understanding (from my time on the Search Accessibility project) is that modern browsers handle this mapping automatically, although it requires some config in Firefox and Safari. Will test and update this issue with next steps.

**Comment by a8ck3n** [comment]
Initial testing shows that both `space` and `return` are properly mapped in Chrome, Firefox, and Safari. There's no need to have an `onKeyDown` event handler.

Some additional digging on `enter` vs `return` turned up this: [Return and Enter Are Two Different Keys](https://daringfireball.net/2020/07/return_and_enter) — Very interesting. I do not have an `enter` key on my laptop keyboard but was able to simulate it using the trick noted in the article. (hold down `fn` before clicking `return`)

In my testing, triggering an `enter` key event was also properly handled in the browsers noted above.

My understanding is that an `onKeyDown` handler is needed when overriding an Anchor element to make it behave like a Button. In this scenario, browser behaviour is different (Chrome tabs to button and link elements and maps key presses while Firefox and Safari do not, unless configured to do so).

cc: @jsnmoon @grzegorz-cp @dognose24

**Comment by jsnmoon** [comment]
Sounds good, thanks for investigating!
