### ISSUE TITLE
Footer Credit: Premium plan can remove from FSE.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#71834]
### Quick summary

IF you switch to an FSE theme and are not on the Business plan (my testing used Premium, as did the user who's site I discovered the bug on), you can remove the footer credit.

### Steps to reproduce

1. Create a simple site on any plan Premium or lower.
2. Switch to, if not already using, any FSE theme.
3. Edit your site and remove the "powered by WordPress.com" footer. You can optionally replace it with anything else (I chose "Powered by a footer bug").

### What you expected to happen

FSE should ignore my footer changes, or the footer credit should be blocked in FSE, as it is for non-FSE themes.

### What actually happened

I can hide the footer credit without paying for a Business plan, which is [not the intent](https://wordpress.com/support/footer-credits/).

### Context

Discovered when a user in 38201268-hc requested their non-FSE site be able to remove the footer as they can with their FSE site. Both sites are Premium.

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by epeicher** [comment]
One line of investigation suggested for this task is to add a filter on REST API requests that sets the lock flag on the template part that renders the footer. One possible filter is the `rest_post_dispatch` filter. That needs to be investigated though as there could be better options. Source here p1674146320050789/1674136949.270979-slack-C03N25JPCE4

**Comment by danielbachhuber** [comment]
This should be fixed with D100796-code if someone would like to re-test.

**Comment by cometgrrl** [comment]
"[Blog at WordPress.com.](https://wordpress.com/?ref=footer_blog)" now shows if I remove the default "powered by".
