### ISSUE TITLE
Odyssey Stats: WordPress banners are incorrectly styled

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#71830]
![Image](https://user-images.githubusercontent.com/4044428/211445744-cd2e05d5-65e6-4f40-b620-8e9dd82d00d6.png)

Above is an example with a Jurassic Ninja banner.

**Comment by wilmersondasilva** [comment]
Are there other banners I should check out, @jsnmoon?

**Comment by jsnmoon** [comment]
None that I'm aware of. @kangzj, do you have any suggestions?

**Comment by kangzj** [comment]
Thanks for catching and working on this - which could be easily reproduced by spinning up a JN site I believe.

**Comment by wilmersondasilva** [comment]
I created https://github.com/Automattic/wp-calypso/pull/71954 as a proposal to fix this.
