### ISSUE TITLE
Plans: plan credits when upgrading are confusing

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#7183]
When viewing http://calypso.localhost:3000/plans with a site that has a personal plan we see:

<img width="784" alt="screen shot 2016-07-29 at 1 24 53 pm" src="https://cloud.githubusercontent.com/assets/1270189/17265527/8eb57230-55a4-11e6-89a8-5e77b7951d65.png">

Let's clarify the price difference by displaying annual prices, and explain the difference. Maybe something like:

```
$99/yr, just $27 to upgrade
```

cc @rralian @meremagee @apeatling

**Comment by folletto** [comment]
> explain the difference

I noticed with that layout some bleeding of the "per mont, billed yearly" text out of the white card box. Make sure any text change is tested to fit the smallest responsive column width. :)
