### ISSUE TITLE
Design Picker: Hide themes that are on the retire list

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#71835]
# Description

In the onboarding Design Picker, hide the themes that are on this retire list https://github.com/Automattic/themes/issues/6779

See request: pNEWy-fQg-p2#comment-55485

# Tasks 
Hide these themes:
- [x] Farrow
- [x] Heiwa
- [x] Dorna
- [x] Appleton
- [x] Meraki
- [x] Antonia
- [x] Barnett
- [x] Calvin
- [x] Ames

# Testing

**Comment by fushar** [comment]
This is shipped.

**Comment by ianstewart** [comment]
@autumnfjeld  can we add Quadrat to this list? It's my mistake that it's not on the list. See: pNEWy-fQg-p2#comment-55518
