### ISSUE TITLE
WooExpress Trial: Marketing page updates

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71855]
At `/marketing/tools/[siteSlug]` there’s a callout to upgrade to Premium to remove ads; this should probably be removed for the trial purposes, since we don’t want to push users to upgrade to a plan that doesn’t include the other trial features:

![screen-shot-2023-01-09-at-10 55 40-am](https://user-images.githubusercontent.com/2124984/211570452-2a65b5df-5b6b-4dec-82ba-70ecc5259eb0.png)

There are also a number of upsells for Business and Premium plans on the `/marketing/traffic/` screen:

![wordpress com_marketing_traffic_sixhours58_wordpress_com](https://user-images.githubusercontent.com/2124984/211570466-bd095e69-7e51-4b53-bcab-3d2134e302e5.png)

**Comment by markbiek** [comment]
Like #71861 and #71891, I think this is behaving correctly.

**Comment by markbiek** [comment]
I've tested this again and I believe the upsell banners are correctly _not_ being displayed. My suspicion is that we did the audit before some of the backend store code was launched.

**Comment by markbiek** [comment]
I've tested this again and I believe the upsell banners are correctly _not_ being displayed. My suspicion is that we did the audit before some of the backend store code was launched.
