### ISSUE TITLE
WooExpress Trial: Performance Settings upsells

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71861]
The screen at `/settings/performance/[siteSlug]` includes a number of upsells to different plans and features:

<img width="753" alt="screen-shot-2023-01-09-at-11 04 05-am" src="https://user-images.githubusercontent.com/2124984/211575326-ea1763d3-04d1-4f37-9927-461d5b9785e4.png">

1) Upgrade to Jetpack Search adds the product directly to the cart (this is probably fine)
2) Business plan (or higher) upsell goes to the Plans page (should probably be updated to point to eCommerce for the trial context)
3) Premium plan goes to the Plans page (should probably be updated to point to eCommerce for the trial context)
4) Install the AMP plugin goes to the AMP plugin page (this is probably fine)

**Comment by markbiek** [comment]
@daledupreez @sixhours I'm not seeing these banners either. I think this may be functioning correctly.

[Related comment](https://github.com/Automattic/wp-calypso/issues/71891#issuecomment-1380293347)

**Comment by markbiek** [comment]
I've tested this again and I believe the upsell banners are correctly _not_ being displayed. My suspicion is that we did the audit before some of the backend store code was launched.
