### ISSUE TITLE
Editor: Media: Gallery shortcode without image ids displays wrong images

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#7186]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Select a blog to start a new post
3. Select the "Insert content" button to add media
4. Upload two images
5. Select the "Continue" button
6. Select the "Insert" button to add the images to the post in a gallery
7. Switch to the HTML tab
8. In the gallery shortcode, remove the `ids` parameter from the shortcode
9. Switch back to the Visual tab
#### What I expected

I expected the gallery to stay the same, displaying all the images (and only the images) that are attached to this new post.
#### What happened instead

The gallery now shows all unattached media in the media library, and it does not show the images that I just added to this post.

The correct images end up in the published gallery, but the editor shows the incorrect images. This also affects Publicize — the wrong images also end up on the publicized social media posts.
#### Screenshot / Video

With the shortcode `[gallery ids="537,538" type="rectangular"]`:

<img width="785" alt="screen shot 2016-08-01 at 9 58 24 am" src="https://cloud.githubusercontent.com/assets/8658164/17288776/8b3f7480-57ce-11e6-9d82-23f958cabe46.png">

With the shortcode `[gallery type="rectangular"]` (ids removed):

<img width="742" alt="screen shot 2016-08-01 at 9 59 16 am" src="https://cloud.githubusercontent.com/assets/8658164/17288798/aa625b02-57ce-11e6-8980-df637925a22e.png">
#### Context / Source

This issue came up from a beta tester testing the share extension in the iOS app. When you share media with the iOS share extension, the images are added with a `gallery` shortcode without an `ids` parameter, which results in the problems mentioned above.

**Comment by alisterscott** [comment]
This is also an issue with posts that are generated with a Jetpack site sent via email that have galleries.

When loading such a post in Calypso rich text editor the images don't show at all:

![calypso rich editor](https://cloud.githubusercontent.com/assets/128826/17719356/4c794b9a-645d-11e6-9588-dd7c027be618.png)

In the plain text editor you can see a gallery shortcode without ids:

![calypso plain editor](https://cloud.githubusercontent.com/assets/128826/17719361/59a877be-645d-11e6-8666-8276f96143be.png)

**Comment by astralbodies** [comment]
Also any post created from `posts/new` using the `media` parameter to attach an image or images to a new post. The iOS share extension uses this feature to create new image post in a single shot and it breaks both Publicize and the view in the Calypso editor.

**Comment by rachelmcr** [comment]
I tested and confirmed that this is still an issue for galleries created with the methods described above:

- [Post by Email](https://en.support.wordpress.com/post-by-email/) (Jetpack and WordPress.com sites)
- WordPress for iOS Share Extension (sharing an image to the WordPress app)

**Comment by rachelmcr** [comment]
I tested this in Gutenberg, and a gallery shortcode without the image IDs appears as expected there. It shows only the images attached to the post in the gallery.

I'm closing this issue since it will be resolved with the Gutenberg editor.
