### ISSUE TITLE
Free Flow Launchpad - default preview to desktop view

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71885]
As noted in our recent team call testing this flow, we agreed that the default preview viewport should be desktop for this flow (and general launchpad flows.  To be clear, however, link-in-bio flow should still keep the mobile default.  paYE8P-2q0-p2

**Comment by agrullon95** [comment]
This change will be handled with this PR: https://github.com/Automattic/wp-calypso/pull/71931
