### ISSUE TITLE
Free Flow Launchpad - "Write Post" task autocompletes with theme content.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71884]
As noted in our recent team call testing this flow, we found that this task is autocompleted by theme starter posts. paYE8P-2q0-p2

This does not appear when first loading launchpad, but will after the first reload.

**Comment by mattwiebe** [comment]
A fix for testing: D97553-code

**Comment by mattwiebe** [comment]
The fix is now in production
