### ISSUE TITLE
Launchpad - update post editor sidebar to lead back to the launchpad.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#71888]
as noted in our recent team walkthrough, we want to update the exit button in the post editor to read "next steps" and lead back to the launchpad when the launchpad functionality is active.  paYE8P-2q0-p2

![Screen Shot 2023-01-10 at 2 32 13 PM](https://user-images.githubusercontent.com/28742426/211644529-beea1589-d219-44dc-9715-2fe237a522f8.png)

**Comment by Addison-Stavlo** [comment]
Note - im a bit confused here after testing today.

Tuesday in our walkthrough we saw that when entering the post editor from the launchpad, the exit took us to the posts page.
Today testing this again entering the post editor from the launchpad took us back to home / the launchpad - and only takes back to the posts list page if that was where we entered from.

**Comment by agrullon95** [comment]
Changes will be handled in this PR: https://github.com/Automattic/wp-calypso/pull/72352

> Note - im a bit confused here after testing today.
>
>Tuesday in our walkthrough we saw that when entering the post editor from the launchpad, the exit took us to the posts page.
>
>Today testing this again entering the post editor from the launchpad took us back to home / the launchpad - and only takes back to the posts list page if that was where we entered from.

@Addison-Stavlo - This all depends on how the user enters the post editor page. It seems like when the user first goes through one of the stepper flows (such as newsletter), and they navigate to the post editor through one of the launchpad tasks (`Write your first post`), the exit button will redirect them to the post page. I noticed if I navigate to `/home` and get redirect to the launchpad, then I navigate back to the post editor from `Write your first post` task, the exit button will redirect me to the "Dashboard" ( `/home`).
