### ISSUE TITLE
WooExpress Trial: Footer credit upsell needs updating

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#71891]
At `/settings/general/[siteSlug]` there's an upsell to Business to remove the footer credit that should be updated for the trial context:

<img width="761" alt="screen-shot-2023-01-09-at-11 02 46-am" src="https://user-images.githubusercontent.com/2124984/211571917-0a7dd8ca-cfe6-4857-a52e-02c5b525a482.png">

**Comment by markbiek** [comment]
@sixhours @daledupreez Do we want this copy to say something like "WordPress.com eCommerce Plan instead?

**Comment by markbiek** [comment]
I'm also not seeing the banner on my current ecomm trial:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/917632/212071003-deec450c-a152-42a9-a430-e7cab0a1e85a.png">
markbiek315.wpcomstaging.com

**Comment by daledupreez** [comment]
This feature should be included in the eCommerce and eCommerce trial plans, so we shouldn't have an upsell at all. This may be a gap in the trial plan configuration where we don't have the `WPCOM_FEATURES_NO_WPCOM_BRANDING` feature.

**Comment by markbiek** [comment]
I think it's actually behaving correctly given that I'm not seeing the banner at all on my trial sites.

**Comment by markbiek** [comment]
I've tested this again and I believe the upsell banners are correctly _not_ being displayed. My suspicion is that we did the audit before some of the backend store code was launched.

**Comment by sixhours** [comment]
Confirmed it's behaving correctly now!
