### ISSUE TITLE
Jetpack Scan: don't show "Save Settings" before you've activated Scan

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#7191]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/securityyoursite.com
2. When Scan isn't activated, the buttons aren't displayed properly.

<img width="772" alt="screen shot 2016-07-31 at 1 34 53 pm" src="https://cloud.githubusercontent.com/assets/426388/17292968/9cfe4f10-57ed-11e6-9f42-a1a9a7291b70.png">

**Comment by mtias** [comment]
"save settings" shouldn't be there, right? cc @MichaelArestad @rickybanister

**Comment by MichaelArestad** [comment]
I actually don't know on this one. @jeffgolenski any ideas?

**Comment by MichaelArestad** [comment]
I don't think it should be there, but it's not visible in production so let's not worry about it just yet.

**Comment by lancewillett** [comment]
This is still a bug: testing with a Jetpack site and Safari 10.0 on OS X 10.12.

<img width="875" alt="screen shot 2016-10-17 at 11 47 45" src="https://cloud.githubusercontent.com/assets/66797/19450757/9133dcfa-945f-11e6-90cf-c6e78adff589.png">

**Comment by rickybanister** [comment]
We're doing some improvements to the jetpack plugin settings styles, which will inform the calypso settings styles and hopefully bring about a fix here (to the larger problem of the design, not just button alignment)

cc @MichaelArestad

**Comment by jeherve** [comment]
Closing this as this part of Calypso does not exist anymore.
