### ISSUE TITLE
Themes: Update analytics for M5

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#7193]
- track current filter and vertical
- May need to update this [call](https://github.com/Automattic/wp-calypso/blob/5a573b4590fc0f57e3afa6a1219198482452a1d4/client/my-sites/themes/helpers.js#L139)
- Update ambiguous use of 'filter' [here](https://github.com/Automattic/wp-calypso/blob/5a573b4590fc0f57e3afa6a1219198482452a1d4/client/my-sites/themes/themes-selection.jsx#L66) (or [maybe not](https://github.com/Automattic/wp-calypso/pull/6860#discussion_r72973048))
- Anything else?

**Comment by folletto** [comment]
We did a review of all theme related events here: p4axMe-1gm-p2

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

Is this issue still applicable?

I am proposing to close this issue with an appropriate label denoting reason for closure if no work is scoped for the near term.
