### ISSUE TITLE
Blaze: Upload image accessibility issues

### ISSUE THREAD

**Issue by ha-un** [Automattic/wp-calypso#71953]
### What

Click/drag image is not being identified by screen reader (requires JAWS cursor to click the words only, not entire blank box), making the feature have accessibility issues.

### Why

When promoting a new post, an image is required and requires to click the upload icon or drag the image.

When using "tab" to navigate around the area, the image box and ability to upload an image is skipped and not being recognized (or hard to do so)by screen readers.

### How

Making the entire box clickable with an alt text could possibly solve the issue.

https://user-images.githubusercontent.com/96960321/211911388-600c4769-7730-47f9-a044-c2ee7c62a5fb.mp4

**Comment by dragstor** [comment]
The user mentioned that the `Change` button is present without having to use the JAWS cursor.

**Comment by allilevine** [comment]
@patrickwarner Is this an issue Explorers should pick up, or would it be better for Self Serve to take a look?

**Comment by allilevine** [comment]
I believe this is now fixed. I can tab to the "Select" button in the image area.

![Image](https://github.com/Automattic/wp-calypso/assets/1689238/450b766d-13e1-436c-a623-ac12edb1b15a)

Feel free to re-open if needed.
