### ISSUE TITLE
Site Assembler V2: Ensure the performance

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#71982]
#### Description

We have to ensure the performance when we bring the font and color variations to the site assembler. That being said, when the user selects any font or color variation, the user should feel everything smooth

#### Related

* https://github.com/Automattic/wp-calypso/issues/71038

**Comment by autumnfjeld** [comment]
Can this be closed @arthur791004 ?

**Comment by arthur791004** [comment]
Sure. The performance looks good on my side 😎
