### ISSUE TITLE
Writing Prompts: Add tags

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#71993]
### Details

Whenever someone clicks to answer a writing prompt, we need to insert two tags.

1. `#dailyprompt`
2. `#dailyprompt-17` - where 17 is the numerical number of the writing prompt. 

When we link people “view all responses” in the my home card, we’ll take them to https://wordpress.com/tag/dailyprompt-17.

![Image](https://user-images.githubusercontent.com/5634774/212120535-817605ba-f924-4389-a7f2-fea7967bb6c4.png)

### Checklist

- [ ] Add #dailyprompt-{prompt_id} to web (Jetpack)
- [ ] Add #dailyprompt-{prompt_id} to mobile apps
- [ ] Create a script to go through existing answer prompts in the blogging_prompt_answers table and add the #dailyprompt-{prompt_id} tag to those posts, where possible

**Comment by eoigal** [comment]
Just wondering if we should include these changes with https://github.com/Automattic/jetpack/pull/27779 ? @creativecoder wdyt?

**Comment by davemart-in** [comment]
@eoigal just noting that I updated these proposed tags to remove the `-` dash between the words `daily` and `prompt`. This way we stay consistent with the way we had been tagging prompts as well as consistent with the mobile apps.

**Comment by roo2** [comment]
also closed by https://github.com/Automattic/jetpack/pull/28387
