### ISSUE TITLE
Feature paid products more prominently on categories pages

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#71990]
Follow up for https://github.com/Automattic/wp-calypso/pull/68978 and https://github.com/Automattic/wp-calypso/pull/71928

When browsing category pages, paid products are currently featured based on the default sorting criteria. Eg. when clicking SEO, the free Yoast plugin is #1, and Yoast Premium is #8 in the list:
<img width="1048" alt="CleanShot 2023-01-12 at 12 58 21@2x" src="https://user-images.githubusercontent.com/11555574/212072747-ec722150-6137-480c-98db-169776456212.png">

We should update the sorting logic to feature paid products closer to the top of the page.

**Comment by epeicher** [comment]
Current sorting logic uses `active_installs` that eventually apply the following sorting by priority:
- active_installs desc
- date desc
- blog_id asc
- post_id asc 

But this can be updated to:
- blog_id desc (Paid products first)
- active_installs desc
- date desc
- post_id asc

**Comment by epeicher** [comment]
Comparison of results before and after:

|Category|Before | After|
|-------|-------|------|
|SEO|           ![CleanShot 2023-02-21 at 12 37 44@2x](https://user-images.githubusercontent.com/3519124/220334959-dea1a223-bb4e-4007-a2de-86d52e862789.png)                |![CleanShot 2023-02-21 at 12 30 21@2x](https://user-images.githubusercontent.com/3519124/220333556-99cd7f21-b4ca-4e40-aec2-55f52559c438.png) |
|Ecommerce & Business |        ![CleanShot 2023-02-21 at 12 37 29@2x](https://user-images.githubusercontent.com/3519124/220334899-a7d1cc8b-e442-4789-9e1d-5e5bc8d0ffff.png)           | ![CleanShot 2023-02-21 at 12 31 11@2x](https://user-images.githubusercontent.com/3519124/220333671-7d578b02-9c37-47e4-bf72-ac8d8044159f.png)|
|        Booking & Scheduling      |          ![CleanShot 2023-02-21 at 12 37 09@2x](https://user-images.githubusercontent.com/3519124/220334849-42849eec-965b-4ad6-964b-412ef7fd78c8.png)           | ![CleanShot 2023-02-21 at 12 31 49@2x](https://user-images.githubusercontent.com/3519124/220333814-bfdd6fb1-a70b-4baa-9828-6c243124bda6.png)|
|        Events Calendar      |            ![CleanShot 2023-02-21 at 12 36 49@2x](https://user-images.githubusercontent.com/3519124/220334801-8cf2cd78-b759-4a3a-8a27-45e278454551.png)          |![CleanShot 2023-02-21 at 12 32 08@2x](https://user-images.githubusercontent.com/3519124/220333874-1457fabd-5101-47e5-aa2c-7b45ee4325c8.png)|
|      Shipping & Delivery        |         ![CleanShot 2023-02-21 at 12 36 21@2x](https://user-images.githubusercontent.com/3519124/220334701-cbac2738-ffa2-4d7c-8207-3a9b74cea5e4.png)            |![CleanShot 2023-02-21 at 12 33 15@2x](https://user-images.githubusercontent.com/3519124/220334115-2000acac-3393-4e01-957d-45cf78d364db.png)|
| Marketing             |        ![CleanShot 2023-02-21 at 12 36 05@2x](https://user-images.githubusercontent.com/3519124/220334643-93dd7285-d131-4fb2-bd5d-e098f523da94.png)              |![CleanShot 2023-02-21 at 12 34 24@2x](https://user-images.githubusercontent.com/3519124/220334316-83ec6cc3-06b9-410e-9bc0-5912c20f2066.png)|

**Comment by epeicher** [comment]
Diff created D102207-code

**Comment by epeicher** [comment]
Deployed r261755-wpcom
