### ISSUE TITLE
Editor: Theme-specific modules are not accessible in Calypso's post editor

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#720]
Theme-specific modules that certain themes, including **Full Frame** and **Outspoken**, add to the post editor are not accessible in Calypso. 

For example, **Full Frame** includes a module for editing **text position** from the editor in WP Admin. This module isn't accessible in the Calypso editor:

![edit-post-e280b9-nicola-isabelle-e28094-wordpress](https://cloud.githubusercontent.com/assets/2998162/11394823/56358db2-935f-11e5-8177-cea9f68d9e84.png)

[As brought up in this forum thread](https://en.forums.wordpress.com/topic/new-editor-feedback-no-display-post-in-module-in-the-new-editor?replies=2), **Outspoken** has a **Display post in** module that doesn't appear in the Calypso editor, only in WP Admin:

![ejavfpdbno-2000x2000](https://cloud.githubusercontent.com/assets/2998162/11394893/badd03a8-935f-11e5-8460-f5c8ed2587a9.png)

This can be disruptive to users' workflow and also makes the process of setting up themes confusing for those who are new to WordPress.com (i.e. they need to navigate between the editors in Calypso and WP Admin.)

2435529-t, 269233-chat

**Comment by timmyc** [comment]
Closing in favor of #587
