### ISSUE TITLE
LaunchPad - resolve edge case of infinite loading

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72006]
As discussed in recent team meeting, paYE8P-2oH-p2

There is currently an edge case where the launchpad will be in an infinite loading state. This can happen when:

- [ ] the launchpad url is visited from a logged out user
- [ ] when providing a site slug that DNE

**Comment by agrullon95** [comment]
Handling launchpad infinite loading edge cases in: https://github.com/Automattic/wp-calypso/pull/72272

If logged out, redirect the user to `/home/{siteSlug}`.
Redirect the user to `/home` if the site slug query parameter does not exist or if it's an invalid blog
