### ISSUE TITLE
Writing Prompts - Visually show blockquote in reader feed

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#72016]
## Description

Lets show the blockquote in the feed if possible vs. stripping the tags and converting it to text.

### Before

![Image](https://user-images.githubusercontent.com/5634774/212942114-513fc875-82bc-437d-935e-0b899eafa077.png)

### After

![Image](https://user-images.githubusercontent.com/5634774/212122781-1678485c-2802-4232-b9b1-e933f7bc17d8.png)

**Comment by eoigal** [comment]
Think this can be closed. Nice job Eru.
