### ISSUE TITLE
Writing Prompts - Remove existing placeholder setting

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#72018]
## Description

We decided as a team that we’d just go ahead and remove the placeholder setting we added in the v1:

![Image](https://user-images.githubusercontent.com/5634774/212123760-c3891c91-c0e4-41e8-a6cf-2bea1a8f9418.png)

**Comment by roo2** [comment]
closed by https://github.com/Automattic/jetpack/pull/28387
