### ISSUE TITLE
Site Editor - Open in edit mode

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72019]
Recently, Gutenberg changes have forced the sidebar in the site editor to be open by default. This exposes complexities to our users at the wrong time and makes it easy for them to get lost with no current way to return to the default homepage template+content view that the editor loads in.  Some context and discussion in p9Jlb4-6ad-p2

![Screen Shot 2023-01-12 at 12 45 54 PM](https://user-images.githubusercontent.com/28742426/212140809-c6bd0b25-7176-4b8e-b8a5-564638ccdfe5.png)

It seems the [edit mode can be persisted in the URL of the editor](https://github.com/WordPress/gutenberg/issues/36667#issuecomment-1377221779). 

To keep things simple and streamlined for our users and their flows, we should update the URLs we use for loading the site editor to open this in edit mode.

**Comment by agrullon95** [comment]
Added `canvas=edit` query parameter to Calypso site-editor to always default to edit mode (hides sidebar on load) with:  #72339
