### ISSUE TITLE
Writing Prompts -  Show #dailyprompt as default tag

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#72017]
## Description

When customers go to the tags section in the reader and they have none, let’s show `#dailyprompt` by default to hopefully drive more awareness to this feature:

![Image](https://user-images.githubusercontent.com/5634774/212123115-5b178eb4-e91a-4574-9f2a-1bfab4b1dbae.png)

**Comment by eoigal** [comment]
Deployed in code-D98391
