### ISSUE TITLE
eCommerce Plan: dashboard redirects to broken link when WooCommerce is inactive

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#72022]
### Quick summary

If a user tries to access the dashboard of their site on the eCommerce plan but they don’t have WooCommerce active, it will lead them to an error screen because it can’t load `/wp-admin/admin.php?page=wc-admin`. 

### Steps to reproduce

1. Deactivate WooCommerce on a site with the eCommerce Plan
2. Reload Calypso or go to https://wordpress.com/home/

### What you expected to happen

Calypso dashboard should load regardless, even if WooCommerce is inactive

### What actually happened

It leads to an error message `Sorry, you are not allowed to access this page`

### Context

Customer report 39594770-hc

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Reactivating/reinstalling WooCommerce or switching to the Business Plan

**Comment by marutim** [comment]
Also reported here: 39622323-hc

Fixed it by installing and activating the WooCommerce plugin via CLI
