### ISSUE TITLE
Stats: Improve contrast for views/visitors bar on the classic-dark theme

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#72026]
![Image](https://user-images.githubusercontent.com/4044428/212154401-1762ab18-4ea3-4e16-999c-a82942e541dc.png)

Here are some suggestions and observations from @keoshi:

> Can we manipulate what tint/shade of a color we want to use with a specific color scheme? If so, let’s try to use a lighter shade of grey for the visitors bar in the chart.

> The classic-dark color scheme [has two neutral colors](https://github.com/Automattic/wp-calypso/blob/8ad918cd9844179f1195cb227e3815e58a9ed4ed/packages/calypso-color-schemes/src/shared/color-schemes/_classic-dark.scss#L3-L4) set as the --color-primary* variables.

**Comment by jsnmoon** [comment]
@keoshi & @jeffgolenski: Updating the classic-dark theme to have better primary and primary-dark colors would be the sustainable solution here, but I wonder if that's a task we should tackle. What do you think?

Note that the `classic-dark` theme breaks many assumptions in its color scheme, setting `primary-dark` as a **lighter** variant of the `primary` color. Because of this, it causes significant issues in our heatmap tables, for example:

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/4044428/212181696-a5ea9dfb-cf9a-4f8c-8ef6-dc1c5ca9187f.png">

**Comment by keoshi** [comment]
@jsnmoon Uff, that's not ideal. Nice catch, Jason. Thanks for thinking about this and for creating https://github.com/Automattic/wp-calypso/pull/72031 — will move the rest of the conversation there.

Thank you!
