### ISSUE TITLE
Stats: Apply CSS grid to the Insights page

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#72038]
Tasks:
* [x] apply CSS grid from the Traffic page to the Insights page
* [x] add `hideNewModule` to the `Tags & categories` and `Publicize` components (they will be extended in #72133 and #72134)
* [x] place correct modules in the new grid following the below design

While modernising the Traffic page, we created a CSS grid to place each module with horizontal bars in the correct place.
The same grid has to be applied to the insights page.

Order of modules

![Image](https://user-images.githubusercontent.com/112354940/212216981-998e107d-0e32-4cc0-8610-4d8d80107d3c.png)

**Comment by wilmersondasilva** [comment]
Will the `Latest post summary` be removed? I don't see it on the image you attached.

![image](https://user-images.githubusercontent.com/6406071/212399603-65ca8b42-41b3-4c2b-bbd6-ed55c8a4b0c8.png)

**Comment by jsnmoon** [comment]
> * add `hideNewModule` to the `Tags & categories` and `Publicize` components (they will be extended here and here) (@grzegorz-cp)

It looks like "here and here" didn't get their respective href links 🙂

**Comment by grzegorz-cp** [comment]
> Will the `Latest post summary` be removed? I don't see it on the image you attached.

`Latest post summary` will be replaced in #70852 so for the grid task we'll need to keep it in place or keep a feature flag until #70852 is implemented.

**Comment by grzegorz-cp** [comment]
I applied `hideNewModule` where needed as part of #71957 because otherwise, I won't be able to enable that feature flag in production.

**Comment by wilmersondasilva** [comment]
> Latest post summary will be replaced in https://github.com/Automattic/wp-calypso/issues/70852 so for the grid task we'll need to keep it in place or keep a feature flag until https://github.com/Automattic/wp-calypso/issues/70852 is implemented.


But what position should it be in for now? The same for `Publicize`, where should it be in the new grid?

**Comment by grzegorz-cp** [comment]
I think that we'll have to push the `Latest post summary` down into a third row that will be deleted when the component is replaced.

`Publicize` will merge with `Followers total` into `Social followers`, so let's put them where `Social followers` will be. The remaining component could go to the third row with `Latest post summary`. Could you check if this looks correct? Did you plan to put it behind a feature flag?

**Comment by wilmersondasilva** [comment]
Thanks for the answer, @grzegorz-cp! I think it will look correct. I'll implement it and let you know if something else comes up. 

> Did you plan to put it behind a feature flag?

I wasn't planning to create a feature flag. Do you think is necessary for this task? If so, I can do it.

**Comment by grzegorz-cp** [comment]
I was considering a feature flag until new components are developed, but maybe it's not necessary. Since we are shifting things around potentially without a feature flag, let's ask designers for their opinion. What do you think @jeffgolenski @keoshi ?

**Comment by keoshi** [comment]
Without knowing the clear benefits of each option, I don't have a strong opinion on either of those. I understand that we've been using feature flags until now, right? If that's the case, I'd vote for continuing to use them.

**Comment by jeffgolenski** [comment]
@grzegorz-cp @wilmersondasilva I prefer feature flags for testing before we finalize and ship. Makes it extremely easy to test from a designers' perspective!

**Comment by wilmersondasilva** [comment]
Thanks for the answer regarding the flag usage on this one, @jeffgolenski and @keoshi! I'm going to open the PR, and it's going with the flag.

**Comment by wilmersondasilva** [comment]
Here's the [PR](https://github.com/Automattic/wp-calypso/pull/72249), @jeffgolenski @grzegorz-cp @keoshi. It would be good if some of you could take a look at it. 

Reminding the UI of each module remains the same for now and it will be updated on follow-up PRs.

**Comment by jsnmoon** [comment]
Please enable the grid layout for production before marking this task as complete; thank you!

**Comment by jsnmoon** [comment]
Our current implementation (behind the feature flag) leaves behind noticeable vertical gaps between the cards. @grzegorz-cp, what do you think about vertically expanding the grid cards to take up rest of the empty space? We do this already on the traffic page, I believe.

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/4044428/217941917-b6c1e6f2-0ed5-40de-8906-044a25134f81.png">
