### ISSUE TITLE
Stats: Add totals section to the Ads page

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#72045]
# Development

Use the component showing highlights on the Traffic page (7-day highlight) and the Insights page (annual highlights) to:
- [x] display 3 cards for `Totals`
- [x] extend the component to display (i) tooltip
- [x] place any missing icons as SVG in the shared place where we currently store the `eye` icon SVG
- [x] verify that the mobile view works as expected
- [x] replace the old component and move it above the chart
- [x] populate the tooltip with existing content

Bonus:
- [x] reuse tooltip styles from the Traffic and Insights pages

# Designs

- Wide screen view
![Image](https://user-images.githubusercontent.com/4044428/211943915-f0184879-4cb6-4828-a6b8-ffa1955ace6e.png)

- Small screen view
![Image](https://user-images.githubusercontent.com/112354940/212245593-31a96c3e-634e-4ce6-8a48-d3419d3f7e7c.png)

**Comment by grzegorz-cp** [comment]
@jeffgolenski Tooltip should look the same as on the other pages (dark with bigger padding), shouldn't it?

**Comment by a8ck3n** [comment]
Hello @jeffgolenski — 👋 

Do you have the SVG data for the three required icons? I tried exporting them from Figma but have run into some issues with that. The first two exported fine but they don't draw correctly for me. For the third one (the lightbulb?), I was unable to get it to export. I'll use some existing icon data in the meantime.

Thanks!

**Comment by jeffgolenski** [comment]
@a8ck3n The three icons in the cards above are part of the WordPress Design Library set, which we're loading in calypso. We should only use manual SVGs when an icon isn't present in that set! The icon names are:

* `payment`
* `receipt`
* `tip`

@grzegorz-cp and I discussed the icon system in the past. I'm not exactly sure how they're implemented, but I know the icon set is good to go, we're using it on other pages! I believe you can follow the paper trail[ in this PR](https://github.com/Automattic/wp-calypso/pull/70625), Kevin.

**Comment by grzegorz-cp** [comment]
Thanks for the clarification Jeff.
@a8ck3n you can use the icons Jeff mentioned in a similar way it's [done here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/site.jsx#L4) but include the icon names mentioned above. Use the `Icon` component like [done here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/site.jsx#L81).

**Comment by a8ck3n** [comment]
Should be complete now that #72320 has been merged/deployed.
