### ISSUE TITLE
Pattern Assembler: use all the wireframe patterns

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#72041]
# Description
Currently we are only using a subset of the wirefame patterns that are available in https://dotcompatterns.wordpress.com/category/wireframe/

We want to use all the wireframe patterns.  

# Tasks
- [x] update https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts#L187 to include all wireframe section patterns

# Testing
- [x] Ensure performance of pattern loading is good

**Comment by miksansegundo** [comment]
I have updated the list, and the performance is good. 
We have some CSS issues with some patterns. I'll try to fix them and ask for help from theme designers.
