### ISSUE TITLE
LaunchPad onboarding flows: Progress bars are inconsistent

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72073]
as noted in a recent CFT - pdtkmj-WY-p2#comment-1518

The linear progress bar at the top of onboarding pages does not reflect the same status as the progress bar in the launchpad they end up in.

In the example of the free flow, design selection shows progress as (2/3). As soon as we submit and get to the launchpad we see a progress of (2/5).

![Screen Shot 2023-01-13 at 8 57 20 AM](https://user-images.githubusercontent.com/28742426/212336720-7c45ec3b-0c4a-4b29-bede-14a3fa8effac.png)

Goes into:
![Screen Shot 2023-01-13 at 8 58 03 AM](https://user-images.githubusercontent.com/28742426/212336886-b08036d2-440c-4178-9783-6c9d1928da84.png)

**Comment by jeyip** [comment]
@Addison-Stavlo @nuriapenya 

We can definitely do this, but one thing to consider is that both progress bars represent different concepts. 1 equates to progress through different views in onboarding, while the other describe the number of launchpad tasks completed. That being said, I agree with the sentiment of unifying progress into a single total -- just wanted to make y'all aware

**Comment by jeyip** [comment]
Started work at https://github.com/Automattic/wp-calypso/pull/72117

**Comment by jeyip** [comment]
Returning this to the backlog to focus on the higher priority launchpad in general onboarding feature

**Comment by Addison-Stavlo** [comment]
note the former progress bar was removed so this is no longer an issue
