### ISSUE TITLE
Design Picker - progress bar does not advance as expected

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72071]
as noted in a recent CFT - pdtkmj-WY-p2#comment-1518

The design picker has 2 steps: 1 to choose from a selection of designs, 1 to preview and confirm selection:
![Screen Shot 2023-01-13 at 8 38 53 AM](https://user-images.githubusercontent.com/28742426/212333043-61280f15-8aea-4bb8-8949-fca61725a75d.png)
![Screen Shot 2023-01-13 at 8 39 30 AM](https://user-images.githubusercontent.com/28742426/212333171-7a50e24b-b649-4b5e-a053-ba7f3cfec418.png)

Note above how the progress bar does not advance in these steps.

**Comment by autumnfjeld** [comment]
cc: @Automattic/lego 

One view is that we consider the design screens all "one step".   But this is maybe not great from user point of view.

**Comment by Addison-Stavlo** [comment]
> One view is that we consider the design screens all "one step". But this is maybe not great from user point of view.

Thats is how i initially looked at it as well. I created this since it was noted by someone on the linked CFT above, but don't personally have a strong opinion here.

**Comment by Addison-Stavlo** [comment]
closing this given the removal noted above.
