### ISSUE TITLE
LaunchPad - Launching shows a flash of the launchpad after the loading screen

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72077]
as noted in recent CFT - pdtkmj-WY-p2#comment-1518

"When launching the site, it looks like there’s a flash of the launchpad step visible before redirecting to Home."

Im having trouble copying in the supplied video, to see a visual example click on the noted P2 link above, and search the quoted text in the reply.

**Comment by agrullon95** [comment]
Issue resolved : https://github.com/Automattic/wp-calypso/pull/72101
