### ISSUE TITLE
WooExpress Trial: Show nudge with remaining days for trial in the left nav

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#72079]
For users on the free eCommerce trial, we need to show a nudge in the left nav that indicates how many days they have left on their trial, and includes a CTA that takes them to the plans page in Calypso.

From an implementation perspective, this should leverage the Jetpack JITM server-side framework for generating the nudge and content, much like the "Free domain available" nudge that we show to users who have purchased annual plans. We should be able to base the code very closely on that nudge: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Swrgcnpx%2Qwvgz%2Swvgz%2Qratvar.cuc%3Se%3Qo3qrq314%232195-og

The main implementation changes to the display conditions that we will need are:
 * Limit the nudge to Atomic sites only
 * Only show the nudge for eCommerce trial plans
 * Update the display text
 * Update the CTA text and target URL
 
We'll also want to trigger the message via a new top-level function.

**Comment by valterlorran** [comment]
I'm addressing this issue here: D98477-code

**Comment by valterlorran** [comment]
The documentation for how JITM works can be found here: PCYsg-cLC-p2

**Comment by daledupreez** [comment]
We deployed D98477-code earlier today.
