### ISSUE TITLE
LaunchPad - Customize domain should hide nav bar and be easy to return from.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72087]
Note the "customize" domain link in the Launchpad:

<img src="https://user-images.githubusercontent.com/28742426/212361049-14dd4d28-2e6b-4e4a-a26a-88218f605e71.png" width=300 />

When we click this we end up at the domains search page where the '< Back' Button does not lead back to the launchpad, and the calypso sidebar is visible:

<img src="https://user-images.githubusercontent.com/28742426/212361550-0aaf9fdb-5c6c-4c99-aa83-42c2cd8bc98f.png" width=700 />

Note this loads into `wordpress.com/domains/add/{siteSlug}` shown above, although may be better fitting to show `wordpress.com/domains/manage/{siteSlug}` (shown below) since this prompts more options and surfaces the subdomain renaming feature.

<img src="https://user-images.githubusercontent.com/28742426/212362566-dfbfac8e-94ed-4d13-af62-2cd4327f1a6b.png" width=700 />

We should make 3 main changes here:

- [ ] Point this "customize" link from the launchpad to `wordpress.com/domains/manage/{siteSlug}` instead
- [ ] Add a '< Back' button to this domains page that leads back to launchpad when we visit this page from the launchpad.
- [ ] Hide the admin sidebar when we visit this from the launchpad

Perhaps the latter 2 points can simply use a query param(s) to trigger the logic to add these custom features/functionalities.

**Comment by nuriapenya** [comment]
I realised that we have two type of Layouts/sub-navigation in Calypso:

Old:
<img width="1168" alt="Screenshot 2023-01-17 at 15 56 13" src="https://user-images.githubusercontent.com/7931304/212932028-45d7dd06-a6db-4a50-887e-8c7d7a7dc09a.png">

New:
<img width="1168" alt="Screenshot 2023-01-17 at 15 56 00" src="https://user-images.githubusercontent.com/7931304/212932062-5cd6efd5-512c-4f2b-9bd5-2c7e5e716f93.png">

The Domains Page has a new layout; therefore, the "back" button used in old layouts wouldn't work well visually. What if instead, we add an arrow in the header? Having the sidebar nav closed will already help into make this arrow noticeable:

<img width="1440" alt="Launchpad - Domains" src="https://user-images.githubusercontent.com/7931304/212932570-1838523a-9038-4f1c-8518-832c3656943a.png">

[Figma Design](YTe1seBsKUaFPqjwiuqc7U-fi-1807%3A10785&t=kNFc2BC5iXd0mC6S-4)

**Comment by mattwiebe** [comment]
@nuriapenya What about when a user completes a domain purchase flow? Should we direct them back to Launchpad somehow? Even automatically, skipping this screen entirely if they came in through Launchpad?

<img width="1280" alt="Screenshot 2023-01-13 at 16 22 32" src="https://user-images.githubusercontent.com/195089/212430266-9b6a2c12-0c4e-439e-9ce8-0f17c29a3201.png">

Also even if we direct them to the parent screen, they still need to go to the "add domain" screen to complete the flow, and also they also hit this "add professional email" upsell. 
<img width="1276" alt="Screenshot 2023-01-18 at 17 02 49" src="https://user-images.githubusercontent.com/195089/213314273-483c9874-a9ca-41c4-ae87-ec534bdbeb8b.png">

So do we hide the sidebar in each case throughout?

**Comment by nuriapenya** [comment]
@mattwiebe I just tested all the different flows (there are many intricate interactions in this area!), and I'm starting to think that closing the side panel might not be a good idea. Although the sidebar brings complexity, it's also the "permanent" escape point back to Launchpad.

I'd propose adding the "< back" button to the Domains page but not hiding the sidebar.

And in the meantime, I will look into the flows again and see if perhaps the Launchpad can be added in some of the steps like this page (after purchasing a domain):

![Thank-You-—-WordPress-com](https://user-images.githubusercontent.com/7931304/213656629-c1a8cb71-19fe-4386-b743-628587dff0e3.png)

Would that work @Addison-Stavlo ?

**Comment by Addison-Stavlo** [comment]
this has been resolved with the recent changes to the domains flows.
