### ISSUE TITLE
Sidebar: 

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#7208]
#5737 introduced sidebar regions, which broke the scrolling of the sidebar in GuidedTours. The fix for that assumed that the container to scroll would be the same for both mobile and desktop, but it's not. Instead, we need to grab different elements based on whether we're on a mobile viewport. #6220 introduces a helper function for GuidedTours to find the correct (scrollable) sidebar element.

In that PR, @mcsf [proposed](https://github.com/Automattic/wp-calypso/pull/6220#issuecomment-227789205) to either make that helper function more globally available or resolve the duality. This issue records his proposal in a (hopefully) more visible way. 

/cc @mcsf @coreh

**Comment by lancewillett** [comment]
I'm not sure I understand this one — @lsinger could you please update the title, or maybe close it if it's no longer actionable?

**Comment by lsinger** [comment]
Documented in #17275 / API docs in case this comes up again. Closing for now. 

Thanks @lancewillett!
