### ISSUE TITLE
Site preview domain upsell: add callout

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#72094]
Add the domain upsell callout to site preview. **It should only show for sites on a free plan that don't have a custom domain name.**

Example: 

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/1044309/215757844-c7d48870-8531-429c-b05c-00be72115960.png">

Figma: pb5gDS-2sr-p2

The callout should link to the same domain flow as the My Home domain upsell.

Acceptance criteria:
- [ ] There's a domain upsell callout on site preview.
- [ ] The callout links to the domain search and plan upsell flow.
- [ ] Clicks are tracked.
- [ ] Delete preemptive translations file `client/gutenberg/translations/site-preview-upsell.js`

**Comment by lupus2k** [comment]
Hey @JanaMW27, there is another site-preview view. You can see it by going to /posts, clicking on the 3 dots of one post, and clicking on `view`

What do you think if, in this preview, we show the upsell on the white bar between the device dropdown & the `Visit Site` button?

<img width="1877" alt="image" src="https://user-images.githubusercontent.com/402286/215867633-0332b29d-443a-49ef-8097-ee03f176cfa3.png">

**Comment by JanaMW27** [comment]
That would be better for this instance, yes! Thank you for spotting this case. 😁

**Comment by lupus2k** [comment]
Closed because of this: D99744-code
