### ISSUE TITLE
Odyssey Stats: Change display type throughout

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#72107]
"Display type" is a term used to describe the large heading type throughout a product or design. For stats in WordPress.com we're using Recoleta in many places, as seen here in "2023 in review", "All-time highlights" etc.

![Image](https://user-images.githubusercontent.com/214813/212426635-d474195f-17a1-4b86-bf11-2fae5850fc19.png)

However, for the stats we're displaying in Jetpack for wp-admin, we should use a different typeface. Recoleta is only used in the confines of WordPress.com. For any Jetpack plugin in wp-admin we use a different visual language called "Emerald"

![Image](https://user-images.githubusercontent.com/214813/212428736-46519a2c-ae6e-400f-bbd0-ca1d21e2c326.png)

Emerald display type is all sans-serif text, while Recoletta is a serif. We want the Headline Small styling [can be found in Storybook here](https://automattic.github.io/jetpack-storybook/?path=/story/js-packages-components-text-heading--default). Let's see how this feels!

- [ ] Replace Recoleta throughout Odyssey stats with Emerald headlines small

cc @ederrengifo

**Comment by grzegorz-cp** [comment]
Recently, I've introduced a mixin for the headers [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/_modernized-mixins.scss#L81), so it should be a bit easier to update now. We could enhance the mixin to output an additional set of CSS with some class specific to Odyssey.
We could also create an additional mixin that outputs both variants of fonts (that could be used for other cases).
