### ISSUE TITLE
Odyssey Stats: Fix detailed page breadcrumb styling

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#72109]
The breadcrumb nav on detailed stat pages just need some quick improvements to match those in calypso. A bottom border and some margin / padding correction

Now:

![Image](https://user-images.githubusercontent.com/214813/212430993-78fe5c1a-00fd-4fe1-9a38-e3c33c55489b.png)

Should look like calypso:
![Image](https://user-images.githubusercontent.com/214813/212431261-cf0ed177-f244-4978-a8b1-bea4a3f7f259.png)

**Comment by kangzj** [comment]
Fixed by #72751
