### ISSUE TITLE
Task: Remove themes/third-party-premium feature flag

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#72100]
### Details

After we launch third party premium themes and things are stable, we need to remove the remaining `themes/third-party-premium` feature flags from Calypso.

### Checklist

- [ ] Feature flag has been removed from the code
- [ ] Feature flag has removed from the environment definitions in `config`

### Related

#72098

**Comment by valterlorran** [comment]
Closing this because the flag was already removed.
