### ISSUE TITLE
Stats: Extend Year in Review display period

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#72106]
During the first month of a new year, the Year in Review section at the top of Insights can look quite bleak. See below

![Image](https://user-images.githubusercontent.com/214813/212425341-7afc97c7-7560-42cd-bc7c-0fa0203737d5.png)

Let's change the logic, so the year in review shows the previous year until February 1. So a user should see the "2022 in review" until February 1, 2023. This will allow a bit more impactful data to accumulate before we make the switch, and a customer won't have to stare at a bunch of 0s after the ball drops on new years eve!

cc @keoshi @jsnmoon

**Comment by jsnmoon** [comment]
This is a solid idea; moved the card to the todo column.
