### ISSUE TITLE
Task: initial wiring for eCommerce-specific plans content

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#72102]
### Details

While we don't have final designs for the new logged-in plans page or the My Plans page, we can create some initial PRs that identify when the site has the eCommerce trial plan, and sets up separate code paths when that is the case. As a starting point, we can render exactly the same content via the two code paths, but it will reduce our work once we do start implementation of the new designs.

### Checklist

- [x] Ensure we have a separate code path for the My Plans page when the site has the eCommerce trial
- [x] Ensure we have a separate code path for the Plans page when the site has the eCommerce trial

**Comment by nelsonec87** [comment]
PR https://github.com/Automattic/wp-calypso/pull/72297 Adds the new plan to the Plans List and makes the "My Plan" page work (instead of throwing an error)

![image](https://user-images.githubusercontent.com/3801502/213292787-a1e4eae1-8a6a-42de-ba8b-abb7d2144e23.png)
