### ISSUE TITLE
All Products for WooCommerce Subscriptions plugin can't be registered on WooCommerce.com

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#72124]
When trying to register the plugin All Products for WooCommerce Subscriptions using the WooCommerce.com Host API an error is returned by the API.

`WooCommerce registration: Product could not be registered Could not find product by slug for WordPress.com Marketplace: woocommerce-all-products-for-subscriptions.`

job=80521485330

**Comment by cpapazoglou** [comment]
`woocommerce-all-products-for-subscriptions` doesn't match the WC.com slug of the product with id `3978176`. In WC.com the slug is `all-products-for-woocommerce-subscriptions`. 

We should add `woocommerce-all-products-for-subscriptions` in https://github.com/Automattic/woocommerce.com/blob/cb06900816d8b6e032851fd84c813a5d5e6e81b3/plugins/wccom-plugins/wccom/includes/class-wccom.php#L410

**Comment by cpapazoglou** [comment]
Seems like we need to add https://woocommerce.com/wp-admin/post.php?post=18620&action=edit to the mappings https://github.com/Automattic/woocommerce.com/pull/15705/files too
