### ISSUE TITLE
Stats: Modernize bottom modules on the Insights page

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#72134]
After the CSS grid was applied in #72038, modernise the components to use horizontal bars and combine data when needed.

# Developmnet
- [x] verify `Tags & categories`
- [x] update `Comments`
- [x] update `Shares`
- [x] update `Followers`
- [x] combine `Publicize` and `Follower totals` (skip `Social`)
- [x] verify if users that didn't install `Publicize` are affected by the changes

Depends on:
- #72038 to ass a CSS grid
- #70852 to implement `Latest post summary`. When it's done, the old `Latest post summary` should already be hidden.
- #72133 to extend horizontal bars for `Tags & categories`
- #72135 to extend the horizontal bar card and allow a toggle in the header

# Designs
![Image](https://user-images.githubusercontent.com/112354940/212594980-4efc3cac-21fd-4eb2-af14-dd2011921a2d.png)

**Comment by jsnmoon** [comment]
@grzegorz-cp: Feel free to pare down the scope of this PR to meet our deadline for this Friday!
