### ISSUE TITLE
Writing Prompts: Possibly update email notification layout/style

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#72141]
### Details

Now that we have confirmed the emails are sent on schedule with guides appointment, we need to confirm the email template to matches design layout/style and update any inconsistencies.

### Now
<img width="579" alt="Screenshot 2023-01-16 at 07 51 37" src="https://user-images.githubusercontent.com/5560595/212652616-a58baae1-e77c-43ae-bbb1-e30aef3c6de0.png">

### Design
<img width="352" alt="Screenshot 2022-12-01 at 14 05 10" src="https://user-images.githubusercontent.com/5560595/212653090-1c5b1a28-53d0-4cf2-bb5c-c68ecbad9609.png">

### Checklist

- [x] Confirm with @ollierozdarz if current design is ok
- [x] It could be nice to make the copy in the app messaging more contextual. Something like "Get your prompts on the go with the Jetpack mobil app." or "Write your answer from anywhere with the Jetpack mobile app."

**Comment by eoigal** [comment]
Added app message to be more contextual with code-D98693

**Comment by ollierozdarz** [comment]
This looks great. Thanks @eoigal

**Comment by eoigal** [comment]
code-D98693 is deployed
