### ISSUE TITLE
Post-Purchase page: Add expiration date

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#72147]
### Details
Add the expiration date to Marketplace Plugins

![CleanShot 2023-01-20 at 14 12 16@2x](https://user-images.githubusercontent.com/5039531/213775514-b833f28f-6d45-44f1-942f-1900b3f75941.png)

### Related

P2: pdh6GB-2AP-p2
Figma: HOg65lHD0QOfaq0QtzKQbC-fi-2144%3A39024&t=2qXLnoCxMXgqC5pP-0

**Comment by cpapazoglou** [comment]
This is now done.
