### ISSUE TITLE
WooExpress Trial: Investigate orphaned store subscriptions

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#72154]
Before launching the eCommerce trial, we need to confirm that our code is not creating "orphaned" trial subscriptions that have no owner in the billing system.

See explanation in Slack: p1673650898723929-slack-C0Q664T29

Debugging info on P2: paXYpj-4Vo-p2

Any entries with `'product_id' => '1052'` are eCommerce Trials.

It's possible these orphaned subscriptions are transient, meaning as a result of tests we've done or they occurred before everything was properly connected. But it's also possible there's a bug in the current code that allows a trial plan to be created without a corresponding owner ID in the billing system.

**Comment by sixhours** [comment]
I suspect that these subscriptions were the ones created when we were using the `/checkout` method to add the plan to our sites, not the ones created once we had a proper flow in place at `/setup/wooexpress`.

**Comment by sixhours** [comment]
Noted that the last of the orphaned subscriptions occurred on Jan 10, and that's when the new endpoint to add the eCommerce Trial to a site was deployed: r259068-wpcom

**Comment by sixhours** [comment]
Oop, the number jumped again: paXYpj-4VV-p2 

That indicates there's still a bug somewhere allowing subscriptions to be created without owners.

**Comment by markbiek** [comment]
I've got a diff with a fix here: D98781-code

**Comment by markbiek** [comment]
D98781-code has been merged and landed.
