### ISSUE TITLE
Reader: Featured Image not displayed for some posts

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#7216]
#### Steps to reproduce
1. Go to https://wordpress.com/read/blogs/67272686
2. Locate the post titled "Help make WordCamp DFW a success!"
3. It doesn't display any featured image:
   ![screen shot 2016-08-02 at 12 44 08 pm](https://cloud.githubusercontent.com/assets/426388/17325977/d536740e-58ae-11e6-80c5-41ade8ac9af9.png)
4. The post does include a Featured Image, though:
   https://public-api.wordpress.com/rest/v1.1/sites/67272686/posts/5927

**Comment by bluefuton** [comment]
@jeherve I don't think that the featured image is big enough in this case (352 × 235px). We're looking for a minimum of 600px width to display a banner.

**Comment by blowery** [comment]
@bluefuton this is also one of those "one-liner" cases... I wonder if we should ditch those until the refresh comes out..

**Comment by jeherve** [comment]
> I don't think that the featured image is big enough in this case (352 × 235px). We're looking for a minimum of 600px width to display a banner.

That makes sense +:1

**Comment by blowery** [comment]
The other issue here is that the featured image isn't appearing in the full post view. I think we may be suppressing small ones, incorrectly.

**Comment by richardmtl** [comment]
I have a similar report in 2785611-t

https://wordpress.com/read/blogs/115053861

> Featured images stopped appearing for my posts newer than August 10, 2016

The image on http://www.selfdistractsequence.com/the-museum-of-grind/ is 840 x 480

**Comment by ehti** [comment]
Got another report. Featured images for this site were showing earlier, but not anymore for new posts.

E.g.: http://www.cookingfromheart.com/2016/08/22/farfalle-with-creamy-peas-and-chives-sauce-home-made-farfalle-recipe/

It has a featured image set but it doesn't show up. Feed:
https://wordpress.com/read/feeds/48698434

I don't see an issue with featured image size as the previous ones which do show up are similar in size as the new ones.

**Comment by blowery** [comment]
Looks like that site is having problems with the new Jetpack sync, which is causing us to miss the featured images. In contact with jpop support to see what we can do.

**Comment by blowery** [comment]
Ah, that wasn't the problem. The issue here is two-fold:
1) this isn't really a featured image, the image is actually in the content and 
2) the image is not in the content that's in the feed (see http://www.cookingfromheart.com/feed/ ) so we can't pick it up with our current system

To get featured images in the reader, the author can either use featured images on the posts, or they can turn off summary feeds for the site.

**Comment by jeherve** [comment]
Is there a possible work-around, when:

- the RSS feed is set to display the full post;
- a large Featured Image was defined for the post;
- that image was not inserted into the post, or is not the first image appearing on the page.

You can find 2 examples here:
https://wordpress.com/read/feeds/8020695

- https://public-api.wordpress.com/rest/v1.1/sites/53262711/posts/17647
    - Large Featured Image
    - RSS feed is set to display the full post
    - the featured image is inserted into the post, in a gallery, but is not the first image of that gallery.
    - The Reader picks the first image appearing in the HTML content.


- https://public-api.wordpress.com/rest/v1.1/sites/53262711/posts/17608
    - Large Featured Image
    - RSS feed is set to display the full post
    - The featured image is not inserted into the post.
    - The Reader picks the first image appearing in the HTML content.

It seems to me like the Featured Image should always be the first choice when choosing a cover image in the Reader, even if that Featured Image isn't used in the post.

**Comment by blowery** [comment]
@jeherve looks like the problem there is that werewp.com isn't properly associated with your jetpack site in the feedbag. Looking into that.

**Comment by lancewillett** [comment]
This looks resolved now, at least on original Reader view for https://wordpress.com/read/blogs/67272686

Testing with staging, Mac-n-Chrome:

![screen shot 2016-10-31 at 14 37 32](https://cloud.githubusercontent.com/assets/66797/19872562/a9ef66f6-9f77-11e6-81f3-49b642ee9912.png)

![screen shot 2016-10-31 at 14 37 36](https://cloud.githubusercontent.com/assets/66797/19872563/a9f1b550-9f77-11e6-9b5f-2279ed09394b.png)

If there are other related bugs that still need addressing, let's open new issues for them separately.
