### ISSUE TITLE
WooExpress Flow: Use WooCommerce fonts and colors

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#72166]
We need to make sure that we're using the correct WooCommerce fonts and colors on all trial flow steps. The fonts may already be correct but we should verify.

![image](https://user-images.githubusercontent.com/917632/212745471-7ba95051-2231-4646-b8db-233c6249d676.png)

**Comment by mayo7e** [comment]
hi @markbiek, where do i access the figma file?

**Comment by markbiek** [comment]
@mayo7e Thanks so much for your interest in working on Calypso. At the moment, this is an internal project so we're not  taking outside PRs. Please feel free to check the [issue list](https://github.com/Automattic/wp-calypso/issues) for something else you may be able to pitch in on!

**Comment by mayo7e** [comment]
ok thanks sounds good, is there some way to identify issues open for outside PRs only, this would aid me in selecting an issue to work on.

**Comment by markbiek** [comment]
I'm not sure off the top of my head. Possibly open issues that _do not_ have a project assigned?

For example, this issue is assigned to the Serenity Project:
![image](https://user-images.githubusercontent.com/917632/212766388-3aa9c1c7-7f89-42f1-9611-053330ba90c0.png)

**Comment by mayo7e** [comment]
Alright thanks. perhaps the ones open to outside contributors can be labelled. i reckon this would clarify things easily, as this current issue wasnt assigned.

**Comment by sixhours** [comment]
Deployed in #72283
