### ISSUE TITLE
WooExpress Flow: Update copy on processing steps

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#72168]
The `siteCreation` and `assignTrial` steps should have a title of

> Woo! We’re creating your store 

![image](https://user-images.githubusercontent.com/917632/212745852-41fcefd0-68b2-4a0c-b528-0a02b3cd1a6f.png)

`processing` step message should stay the same.

**Comment by sixhours** [comment]
This has been deployed in #72278
