### ISSUE TITLE
Munchies Theme: Can't find theme unless typing theme name in lower-case

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#72179]
### Quick summary

When searching for the theme “Munchies” with a capital M, the theme can’t be found.

### Steps to reproduce

1. Open the Themes showcase
2. Click on the search bar and look for “Munchies”
3. Notice there are no results.

https://user-images.githubusercontent.com/2540430/211142121-900f4d79-816e-47da-bbbc-1f8366a65ab0.mp4

### What you expected to happen

The theme to be listed when searched for either with upper case or lower case letters.

### What actually happened

The theme wasn't listed, unless searched for with lower case letters.

### Context

pd4QKa-HB-p2

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Munchies

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by vinnykaur** [comment]
📌 SCRUBBING: RESULT

- Tested on Simple - Replicated
- Tested on AT - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- When typing `Munchies` with a capital M, the theme is not searchable. But when I type just `Munch` the theme shows up.

https://user-images.githubusercontent.com/49183855/211552406-14adad4d-7281-4670-89fe-7cf61e7c31b5.mov

📌 ACTIONS

- Marked as Triaged for Quality Squad review

**Comment by taipeicoder** [comment]
Closing as fixed via D106354-code.
