### ISSUE TITLE
Videomaker theme, navigation has no block inserter when overlay menu is active.

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#72174]
### Quick summary

If no menu has been created, the Navigation block does not show an inserter "+" for page links as long as the overlay menu is active.

### Steps to reproduce

1. go to Appearance -> Editor. 
2. Edit navigation block.
3. Click hamburger menu.
4. No inserter can be found anywhere as long as the menu overlay is turned on in Navigation block settings.
5. Turn off menu overlay, and + will appear on hover.
6. Page links can now be added.

### What you expected to happen

+ inserter should be available without turning off the menu overlay.

### What actually happened

No way to insert page links with menu overlay active.

### Context

5835772-zen
User was unable to add page links.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

So far Videomaker, have not tested with other themes.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

Yes, easy to implement

### Workaround details

Disable Menu Overlay in Navigation block settings. Enable after adding page links. Once page links have been added, Menu Overlay can be turned back on. + block inserter will now show as it should when editing hamburger menu.

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate 
- Tested on AT - Could Not Replicate 
- Tested on Self-hosted - Could Not Replicate 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to see the + button to add new blocks with the overlay active
![image](https://user-images.githubusercontent.com/1659416/221850388-a5309ce5-3cd9-45d1-bd17-64cd377bad84.png)


📌 ACTIONS
- Await author feedback

📌 Message to Author
- Hey @Camaropilot ! Are you still able to replicate this? If yes, please add a screenshot/screencast of the issue, so we can test and replicate this. Thanks!

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Closing report due to stale conversation and inability to replicate. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
