### ISSUE TITLE
Components: PostItem / PostRelativeTimeStatus misalignment with long username

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7218]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/post-item
2. View a randomly selected post by a user with a long username
#### What I expected

The clock icon to be aligned to the start of the publishing time
#### What happened instead

The clock icon appears on the second line of the component
#### Browser / OS version

Screenshot below from Linux Firefox
#### Screenshot / Video

<img width="830" alt="screen shot 2016-08-02 at 9 42 29 am" src="https://cloud.githubusercontent.com/assets/7233112/17330615/76ff30d8-5895-11e6-8a8a-2cbe875a99ed.png">
#### Context / Source
# automated-testing #manual-testing (manual review of automated test results)

**Comment by rachelmcr** [comment]
#bug-scrub

The relative time is no longer aligned with the username in the posts list (and won't be with the upcoming condensed posts list), so this issue is no longer valid.
