### ISSUE TITLE
eCommerce: Customers Menu Item Visibility

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#72214]
### Quick summary

The **Customers** menu item is shown by default on eCommerce plan in the left sidebar at the top-level. If the WooCommerce Analytics setting is disabled in `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features` then the **Customers** menu item stays in the top-level, but is not accessible anymore and produces the "_Sorry, you are not allowed to access this page._" error.

<img width="1365" alt="customers-disabled" src="https://user-images.githubusercontent.com/12064241/212932984-e979c565-80e4-4be7-ab9a-9642f5b20fd5.png">

### Steps to reproduce

1. Start at `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features` and uncheck **Enables WooCommerce Analytics**.
2. Click the **Save changes** button.
3. Click on **Customers** in the left sidebar. 

### What you expected to happen

**Customers** menu item to be hidden when WooCommerce Analytics is disabled. The **Analytics** menu item is hidden.  

### What actually happened

**Customers** menu item stays in the top-level menu in the sidebar and produces an error shown in the above screenshot. 

### Context

Here are two screenshots of WooCommerce Analytics Enabled & Disabled:

**Enabled**
<img width="1240" alt="woo-analytics-enabled" src="https://user-images.githubusercontent.com/12064241/212934032-6acecaab-796d-4a7b-85e7-9f07968c75d3.png">

**Disabled**
<img width="1241" alt="woo-analytics-disabled" src="https://user-images.githubusercontent.com/12064241/212934085-a7f9eb47-ac5c-4ef8-b172-ade5794698b9.png">

**Discussion**: p9F6qB-beW-p2#comment-51290

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

NA

### Browser, operating system and other notes

NA

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Enable WooCommerce Analytics in `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`.

**Comment by PanosSynetos** [comment]
I guess we can close this, as it will be taken care of in Calypso Bridge

https://github.com/Automattic/wc-calypso-bridge/issues/913
