### ISSUE TITLE
Font not respected on site with TT3 theme 

### ISSUE THREAD

**Issue by IoanaAMuresan** [Automattic/wp-calypso#72234]
### Quick summary

On the site https://unhurry.in/ - the live homepage shows a serif font. It's a FSE site, with posts page as the homepage (see Settings -> Reading) so I expected to be able to modify this in the Index template. I checked and on all potentially relevant templates: index, home, page, blog (alternative), the font is Cabin (sans). Checked using Inspect and it seems the correct font is used but the browser doesn't seem to want to display it. Discussed here: p1673958595411329-slack-C03TY6J1A

### Steps to reproduce

1. Check live homepage - note the serif font; check using Inspect - and notice that the font used is Cabin 
2. Go to Settings -> Reading - note that the homepage is set to blog posts 
3. Go to Appearance -> Editor -> Index / Page / Blog (alternative) / Home -> Styles - and note that in all instances the font selected is Cabin (a sans serif font) 

### What you expected to happen

See the live homepage display the Cabin font, sans serif, as defined in Styles. 

### What actually happened

The live homepage displays a serif font despite the site using, under the hood, the correct, sans serif, Cabin font. 

### Context

Discussed here p1673958595411329-slack-C03TY6J1A

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Unsure, site uses TT3 

### Browser, operating system and other notes

Chrome, iOS - unsure if varies 
Reproduced by another HE in Slack 

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- On a test AT site, I activated the theme TT3, and set the homepage to display default posts page.
- Opened the Editor and set Styles > Typography > Text & Links to Font: `Cabin`
- This font selection was reflected in the editor and on the live site.

**AT Example**

<img width="1450" alt="Markup 2023-03-09 at 09 49 26" src="https://user-images.githubusercontent.com/27249804/224096931-668c01a9-dcdb-48e9-998c-0312bd9dd32a.png">

<img width="1354" alt="Markup 2023-03-09 at 09 49 57" src="https://user-images.githubusercontent.com/27249804/224096779-9ed25499-373d-4656-8fa8-b622da47447e.png">

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- Hi @IoanaAMuresan ! Were you able to replicate this issue on a test site _outside of_ the user's site? If so, please provide the steps you were able to follow to replicate the issue. If not, this would be best reported on an internal P2 instead for further testing.
- Also, please always make sure to exclude any user-specific information in your screenshots or details, even links to their sites.

- [ ] Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.
