### ISSUE TITLE
Use site locale for "Best views ever / Day"

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#72250]
The date is currently based on browser locale, which could be not consistent with other places. We should use site/user locale for consistency.

![Image](https://user-images.githubusercontent.com/1425433/213061130-78351dd1-fa23-47e7-a08e-6a57264e7471.png)

**Comment by jsnmoon** [comment]
We'll want to consider these locales, ordered by priority:

1. The user's locale, set via `/me/account` and stored in [user settings](https://github.com/Automattic/wp-calypso/blob/64c63ba65fd98dfe786885dbc38bcd6d3f0c4c91/client/lib/account-settings-helper/index.jsx#L17). It might also be accessible using [this selector](https://github.com/Automattic/wp-calypso/blob/a14b6727ffc1ed68b951c95f8a43ca6e1cb15ccc/client/state/current-user/selectors.js#L52).
2. The site's locale, set via `/settings/general/:siteSlug` and stored in `lang_id` in the [site settings](https://github.com/Automattic/wp-calypso/blob/fb5de969b9c11131f64d5e6bd101a32533450316/client/my-sites/site-settings/form-general.jsx#L924).
3. The browser's locale.

cc @annacmc

**Comment by annacmc** [comment]
@jsnmoon just to clarify - It's currently working with the user's locale now. Are we wanting to implement a fallback to the site and browser locale isn't defined? Is it possible that someone would/could not have a user locale set?

**Comment by jsnmoon** [comment]
> Are we wanting to implement a fallback to the site and browser locale isn't defined? Is it possible that someone would/could not have a user locale set? (@annacmc)

Let's ship the user locale enhancement first and punt the site/browser locale fallback into the backlog until it becomes necessary (e.g., due to user reports). I highly encourage shipping enhancements like this iteratively 🙂
