### ISSUE TITLE
Free Flow - Prep homepage entry point

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72268]
As part of enabling the free flow we will need to update the entry point on the homepage to point to our new flow:

![Screen Shot 2023-01-18 at 8 58 44 AM](https://user-images.githubusercontent.com/28742426/213190398-c4e05b34-f9d1-47ac-985a-e850a5fa31ed.png)

Deploying this however, will need to wait for removal of our feature flag so the flow is enabled in production. - https://github.com/Automattic/wp-calypso/issues/72269

**Comment by jeyip** [comment]
It looks like the marketing home page lives here fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Sgurzrf%2Su4%2S-og
