### ISSUE TITLE
Sites Management Page: Pre-fetch data for Site Actions

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#72275]
It's a little annoying to have 'Copy Site' and 'Manage Plugins' pop in after a delay

https://user-images.githubusercontent.com/36432/213200432-30da926f-3b76-4cfa-800f-c9536fe2759e.mp4

We could avoid it if we pre-fetched the necessary data. We could do this if the user hovers over the site row, or if the site is in the viewport.

From p1674052767199949-slack-C0347E545HR

**Done is:**
* 'Copy Site' and 'Manage Plugins' appear instantly when applicable, instead of after a delay.

**Comment by kozer** [comment]
Note:

It's a bit difficult to implement, as:
- We re fetching the data from server (purchases, features) each time the menu appears. Features reducer hold the state as `{ <site id>: <array of features> }` so we can avoid re fetching the features. On the other hand, this is not the case for purchases (it keeps on the state only the purchases for 1 site).
- The component that shows the menu items, lies inside gutenberg repo. It doesn't show the items by default, so the hooks we have don't kick in on load. And this is another problem. The usage of hooks. Hooks can't be rendered conditionally, or use them inside a useEffect (to fetch the data on mouse over). Also, they remounted every time the menu shows up, so the purchase re fetching is something that cannot be avoided till we change the reducer. We may need to move the hooks higher to another component, which troubles me as well, as we 'll mix up responsibilities (fetch everything just in case the user opens the menu)

**Comment by danielbachhuber** [comment]
@kozer Want to draft a pull request with your best guess on how to solve it?

**Comment by kozer** [comment]
@danielbachhuber I'm working on it. I'm trying to make as few changes as possible. I'll draft it in a bit, as I'm close to a solution

**Comment by kozer** [comment]
@danielbachhuber , just created a [pr](https://github.com/Automattic/wp-calypso/pull/72868), in case you want to check it out.
