### ISSUE TITLE
Launchpad - Help Center entry point

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#72276]
Having an entry point for the Launchpad in the Help Center might help users seeking guidance have a list of follow-up tasks they can do. One benefit of having Launchpad represented is that the Help Center is an element present globally, which means it can be accessed through the editor(s).

📍 Figma Design: 9wpoYJrMlYKAKUYvVBMN74-fi-1967%3A47912

https://user-images.githubusercontent.com/7931304/213207177-85fcc404-afe3-481d-aef9-bcc66b4893bb.mov

**Specs**

- This component would only appear while the Launchpad is activated
- The progress circle should be also update according to the real Launchpad
- `:hover` background: #F9F9F9

**Comment by Addison-Stavlo** [comment]
> The progress circle should be also update according to the real Launchpad

Note - if this expands the scope to snowball a bit I would advise adding this in a second PR.  1st ship this with the generic circular icon to get this change out to users, then follow up to make the progress bar relevant to our progress.

**Comment by agrullon95** [comment]
The launchpad entry point has been added to the Help center in: https://github.com/Automattic/wp-calypso/issues/72276
