### ISSUE TITLE
[Earn] Figure out how to streamline Stripe connection flow from the Subscribe block

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#72282]
We have a following problem after merging the newsletters branch:

Stripe Connection flow is very confusing:

1. Click Add plan from the Subscribe Block
2. Complete KYC
3. Click the back button from WPCOM
4. User ends up on the Earn page

The scope of this task is to:
a) Record a video of this problem so we can discuss it better
b) Do preliminary research of what is possible. Maybe we can somehow save the state before redirecting to KYC so we redirect again to a proper add product flow?

For the purposes of this task we can assume we are already on a paid plan, but I would love a video on both a paid and a free plan with the whole upgrade path as well.

**Comment by romarioraffington** [comment]
## Adding a Newsletter Payment Plan without a Stripe Connection

https://www.loom.com/share/50991ff0aee14a1a9074302e87997d8e

### Observations

After Stripe is connected, a success message is displayed with a link to add a payment plan. However, this only occurs when there are no payment plans. This doesn't help us as we want to prompt the user to create a **newsletter** plan if one does not exist.


<img width="1109" alt="Screenshot 2023-02-23 at 7 22 23 PM" src="https://user-images.githubusercontent.com/7076981/221061748-90aa707c-e13a-48e1-902a-adb3c18b4cb2.png">

### Possible Improvements
 
**Flow A:**
1. User clicks on the Add Payments or Manage Payments button from Gutenberg
2. On WPCOM user is redirected and prompted to complete Stripe KYC
3. After completing KYC, the user is redirected to the URL initially passed from Gutenberg  ( to add/manage payment )

**Flow B:**
1. User clicks on the Add Payments or Manage Payments button from the Gutenberg
2.  On WPCOM user is redirected and prompted to complete Stripe KYC
3. After completing KYC, a success message is displayed with a button to set up a **newsletter** plan.

**Flow C:**
1. User clicks on a Stripe KYC call to action button in the Subscribe block
2. After completing KYC, the user is redirected to the Earn page and is prompted to add a newsletter payment plan
3. User adds a newsletter plan by clicking the call to action button on the Earn page
5. ( Optional ) The user can add a newsletter payment plan from the Subscribe Block.

### Next Steps:

- [x] Look for any quick wins and document or create a patch
- [ ] Do a video of a free plan with the whole upgrade path as well.

**Comment by romarioraffington** [comment]
### Update

After diving into the code, I think the best approach is take is **Flow A** or **Flow B**.  We already have code that utilizes the query param to display a success notice like the one above. 

#### What I've learned

1. A `source` query param with a hardcoded value `calypso` is sent to the `/status` endpoint ( [code](https://github.com/Automattic/wp-calypso/blob/d3a96e3c6da811fc49c9bb57005743d45a72b59d/client/state/data-layer/wpcom/sites/memberships/index.js#L94) ) and the HTTP request dispatched by redux.
2. The  `source` query param is allowed to have the following 4 values: 'calypso', 'earn', 'gutenberg', 'gutenberg-wpcom'. ( [code](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/memberships.php#L48) )
3. On WPCOM the `get_memberships_settings_for_site` gets called ( [code](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/memberships.php#L264) )
4.  The source is passed to Stripe as state which gets returned after a customer completes KYC ( [stripe docs](https://stripe.com/docs/connect/oauth-reference#get-authorize-request) ).
5. When the state from Stripe is returned with the source, we redirect based on the value of the source and append a new query param ( See `class.wpcom-json-api-memberships.php:5131` )
6. The frontend utilizes that query param to display a notice ( [code](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/earn/memberships/index.jsx#L500) )

#### What I've tried

1. I've tried to modify step 1 above to pass a source ( e.g "earn-newsletter ").
2. Updated the accepted params in step 2
3. Updated logic in step 5 to redirect with a query a different query param if the source is "earn-newsletter"
4. Updated the front-end code to redirect or show a notice based on the query param from step 3.

#### Issues I've faced
I haven't figured out how to update the `$action` [here](https://github.com/Automattic/wp-calypso/blob/d3a96e3c6da811fc49c9bb57005743d45a72b59d/client/state/data-layer/wpcom/sites/memberships/index.js#L90) with the correct source before the HTTP is dispatched. Requested some help/guidance on slack: p1677681688141449/1677468457.620079-slack-C01B6KEJ5GE

**Comment by romarioraffington** [comment]
### Update

- [x] PR was submitted with the Calypso changes. Additional UI improvements were made as well
- [x] Figure out how to dynamically update the `stripe_connect_success` on Stripe redirect, but modifying the `$action` [here](https://github.com/Automattic/wp-calypso/blob/d3a96e3c6da811fc49c9bb57005743d45a72b59d/client/state/data-layer/wpcom/sites/memberships/index.js#L90) with the correct source before the HTTP is dispatched.

**Comment by n3f** [comment]
The stripe redirect is controlled by a hardcoded endpoint in the stripe account (fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qzrzorefuvcf.cuc%3Se%3Q0ro0qn44%23519-og). However when the stripe connect url is generated we pass a state object to it that gets returned/passed through the stripe redirect (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sovyyvatqnqql%2Sfep%2Sncv%2Spbaarpgrq%2Qnppbhagf%2Qanzrfcnpr.cuc%3Se%3Q241n49po%23607-og).  This is probably what you're going to need to leverage.

**Comment by romarioraffington** [comment]
> This is probably what you're going to need to leverage.

@n3f absolutely,  this is the plan. In fact the source is passed as an attribute in the state to Stripe. See fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Szrzorefuvcf%2Spbaarpgrq%2Qnppbhagf.cuc%3Se%3Q456n1sp9%2311-og

The issue I'm currently working on is the following:

> I haven't figured out how to update the $action [here](https://github.com/Automattic/wp-calypso/blob/d3a96e3c6da811fc49c9bb57005743d45a72b59d/client/state/data-layer/wpcom/sites/memberships/index.js#L90) with the correct source before the HTTP is dispatched.

**Comment by romarioraffington** [comment]
### Update

Current PRs:


1. https://github.com/Automattic/jetpack/pull/29351
2. https://github.com/Automattic/wp-calypso/pull/74146
3. D103932-code

**Comment by romarioraffington** [comment]
### Update

1. Created a demo to showcase the flow in its entirety. My microphone didn't record but I think the video is still of value: https://www.loom.com/share/cba348e10b4d4383aab2855ef1aa4822
2. Deployed D103932-code
3. Merged https://github.com/Automattic/jetpack/pull/29351
4. Updated https://github.com/Automattic/wp-calypso/pull/74146 to pass source in the reducer's `$action`
