### ISSUE TITLE
Jetpack Plans: The current plan for any given site should be extended to its monthly/annual counterpart

### ISSUE THREAD

**Issue by bubel** [Automattic/wp-calypso#7228]
If you have a monthly Jetpack plan subscription, the dashboard does not tell you which subscription you have if you are viewing the annual subscriptions. This is especially confusing when you open the /plans/ page for your site and see no buttons or notes with any of the plans.

The "Your plan" button should be applied to both monthly and annual versions of whatever subscription someone has for their site.

**Comment by rickybanister** [comment]
cc @johnHackworth @roccotripaldi 

Related to #6499 and #6301

**Comment by sirreal** [comment]
Recent discussion related to toggling between monthly/yearly plans concluded that showing "Your plan" for a plan you can _switch to_ wasn't coherent. This will be handled better when monthly/yearly plan switching is implemented. As such, I think this issue can be closed.

@rickybanister can you confirm?

**Comment by rickybanister** [comment]
I disagree @sirreal 

To a user they paid for the _features_ of the plan, not the billing frequency. The interface should show them the corner banner thing when viewing the set of features they have. Now that the action button for your plan says 'manage plan' I think we are handled in that regard. We don't have to let them change billing period from the plans screen, they can do so from /me/purchases. 

The plans page should just remove the monthly/yearly toggle (as we already have) and clearly display 'billed yearly' right here:

![image](https://cloud.githubusercontent.com/assets/437258/26361469/127a44bc-3fa9-11e7-9bde-f9d835b72793.png)

For comparison, here is the screen when I toggle. I no longer understand which plan I have AND I can't perform ANY action. I can't switch to monthly, I can't downgrade, I can't manage my plan.

![image](https://cloud.githubusercontent.com/assets/437258/26361498/2d7d5a1a-3fa9-11e7-8818-7d68585bf817.png)

**Comment by rickybanister** [comment]
It could actually say 

`Subscription expires on June 23, 2017`

Rather than 'billed yearly' as that's what we say in /purchases.

**Comment by sirreal** [comment]
Thanks for the clarification @rickybanister. I'll get started on this soon.

> It could actually say
> > Subscription expires on June 23, 2017
> Rather than 'billed yearly' as that's what we say in /purchases.

I'm not sure what you mean here. I don't see that text on the plans page.

**Comment by rickybanister** [comment]
Yes, sorry, I was rushing and should have provided a mockup. I think this would be nice:

Before: 

I have a yearly pro plan and toggle to monthly and I see this:
![image](https://cloud.githubusercontent.com/assets/437258/26424494/65a23cfc-409f-11e7-8bd7-15b2159bc95d.png)

Where did my plan go?!

I toggle back to yearly, phew there's my plan:
![image](https://cloud.githubusercontent.com/assets/437258/26424518/7bd860f0-409f-11e7-8e4f-474223782d22.png)

After:
I toggle to monthly or yearly on the other plans and I see this regardless:
![image](https://cloud.githubusercontent.com/assets/437258/26424585/c1884e80-409f-11e7-92e8-cbddb97e2e68.png)

My follow up comment was simply to say 'showing the expiration date is better than just having read-only text saying you have x plan and it's in billed-yearly-mode'.

**Comment by sirreal** [comment]
I see three changes in the design:

- [ ] #14509 Keep ribbon when toggling monthly/yearly
- [ ] Show expiration/renew date for current plan regardless of interval
- [ ] Show "Manage Plan" button regardless of interval

**Comment by rickybanister** [comment]
@richardmuscat can I have a gut check on my proposal above—should the price change on the plan you have as the monthly/yearly toggle is clicked, or should we persistently show the plan you actually paid for? You can't modify the billing period from this page and must click 'manage purchase' to do so (when that feature is available) so I'm inclined to think that we should only show the price that you paid for your plan—that is not currently outlined in this issue.

**Comment by rickybanister** [comment]
@sirreal yes, I am advocating for those three design changes, BUT in my last comment there I'd like to get some input from Growth on whether we should also include a fourth change—to keep the price static for 'your plan' and show the amount you paid (vs having the price toggle back and forth, which could cause confusion since it will go from what you paid to the lower monthly amount).

**Comment by sirreal** [comment]
A note about showing the expiration date here. I took a look at the purchases page which has logic to show "Renews on" or "Expires on." Do we want to follow the same logic here? It's going to make that part of this issue significantly more complicated. Here's a naïve implementation which won't report renew/expires as accurately as purchases: #14516

**Comment by richardmuscat** [comment]
@rickybanister / @sirreal -- so late to the party here. 

i think the proposal makes sense but I'd request one addition: when you're on a monthly cycle for any of the plans, that plan you're on should have a button saying "upgrade to yearly" or something to that effect

**Comment by rickybanister** [comment]
Once that is possible that makes sense :)

**Comment by sirreal** [comment]
cc @tyxla who will I believe will be starting on monthly -> yearly upgrades soon: https://github.com/Automattic/wp-calypso/issues/7228#issuecomment-305784410

**Comment by tyxla** [comment]
Thanks for the ping @sirreal. Yeah, that's on me :+1:

**Comment by tyxla** [comment]
This issue is still present and needs some work.

**Comment by rickybanister** [comment]
@tyxla can you confirm what work remains in order to get this issue closed? 

I just checked and @richardmuscat's last comment about the 'upgrade to yearly' call to action is finished:

![image](https://user-images.githubusercontent.com/437258/37722517-98c3df3c-2d02-11e8-96f3-969e248ac101.png)

That is, if you view the yearly tab. If you view the monthly tab you see this:

![image](https://user-images.githubusercontent.com/437258/37722562-b2effc92-2d02-11e8-8d33-44e80e9e39b8.png)

Any reason this issue should remain open? Should we make the upgrade to yearly option available in both places? That may make it more difficult for a person to find the purchases page, but has other benefits.

**Comment by tyxla** [comment]
Looking again, it seems the "Your plan" ribbon works properly to cover these cases.

I was thinking whether we should also propagate the "Manage Plan" to the monthly plan view when viewing the corresponding yearly plan for a site that currenly has a yearly plan. But that is probably something unrelated. 

That being said, I agree we could close this one and reconsider future improvements another time @rickybanister.
