### ISSUE TITLE
Plans: Create a better user experience for finding and renewing expired plans

### ISSUE THREAD

**Issue by bubel** [Automattic/wp-calypso#7230]
Note: I've only tested this with Jetpack plans.

Currently, if you have an expired plan for a site and go to /plans/ for that same site, you will see no options allowing you to purchase/renew a plan or a note explaining that your plan has expired. You will need to go to /purchases/ (without any clear direction from the UI) and renew the plan there or remove it from your site (which will give you the ability to sign up for something else when you go back to /plans/).

The option to renew or remove an expired plan for a site should be presented as a button (just like the upgrade button) attached to the expired plan type. This will reduce the amount of digging someone must do when looking to renew.

**Comment by mtias** [comment]
See https://github.com/Automattic/wp-calypso/pull/5212
