### ISSUE TITLE
Wpcom sites that no longer meet the wordAds criteria still qualify for wordAds.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#72304]
### Quick summary

A site that stops being eligible for wordAds due to plan downgrade still receives WordAds.

### Steps to reproduce

1. Create a site, or use an existing site, on the Business or Premium plan.
2. Sign up for WordAds on that site.
3. Cancel your Business or Premium plan.

### What you expected to happen

I should no longer qualify for wordAds, and no longer see/be able to change the relevant settings.

### What actually happened

WordAds behaves as if the site still qualifies for it, including continuing to display ads on a paid plan that should have ads turned off (Personal plan).

### Context

Reported in 38177260-hc, tested by me on a test site.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Manually turn off wordAds from within the settings. Unfortunately, this may also disable ads on free sites, which is not intended - do this only on paid plans that shouldn't qualify for WordAds.

**Comment by cuemarie** [comment]
📌 Message to Author
- Thanks for the report @arinoch ! I believe this was actually just fixed recently, here: pedfti-17N-p2
     - As of 2023-02-28, it seems this has been launched: pedfti-17N-p2#comment-1769
- Are you still able to replicate the issue with your WordAds test site? If so feel free to reopen!

📌 ACTIONS
- Closed as no longer relevant (issue resolved by pedfti-17N-p2 )
