### ISSUE TITLE
Editor: notice messaging for sites without title is buggy

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#7231]
#### Steps to reproduce
1. Open up a site, and set the title to an empty string, save settings
2. Open the Post Editor, and publish a post
3. Notice the confirmation message is missing the site name

#### What I expected
For the notice to fallback to using the site domain instead.

#### What happened instead
![edit_post_ _testingtimmy2_wordpress_com_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/17340260/45e620f6-58a4-11e6-90df-54b7d341b306.png)

**Comment by aduth** [comment]
With the merging of #6477, we should be able to use the `name` property on the result of `getSite`, as it is computed to fall back to the domain.

**Comment by lancewillett** [comment]
This is now working much better! Yay.

Visual record:

Set the site title to empty.

![screen shot 2016-10-17 at 11 54 59](https://cloud.githubusercontent.com/assets/66797/19451036/99fc7abc-9460-11e6-841a-18ccf7bada2e.png)

Publish a new post

![screen shot 2016-10-17 at 11 55 11](https://cloud.githubusercontent.com/assets/66797/19451041/a0794d3e-9460-11e6-9327-b2a0797200aa.png)

See the site domain used in place of empty title:

![screen shot 2016-10-17 at 11 55 16](https://cloud.githubusercontent.com/assets/66797/19451054/add7baf6-9460-11e6-98b7-adbf8a8bc5b6.png)

**Comment by aduth** [comment]
Fixed in #7322
