### ISSUE TITLE
Premium Theme: Amulet

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#72311]
### Details

The Amulet premium WooCommerce theme needs the following:

### Checklist

- [x] [Set up the demo site](https://amuletdemo.wpcomstaging.com/)
- [x] Theme showcase draft
- [x] Add the theme to the soft-launch filter
- [x] Build a ZIP for the theme
- [x] Add the theme as a product to the Store
- [x] Add the theme to the prices page in MC
- [x] Headstart annotations (don't forget to submit for translation)
- [x] GlotPress Project creation
- [x] Launch process

Cheat sheet: [paYKcK-1Pt-p2](https://href.li/?paYKcK-1Pt-p2)

Premium theme launch guide: [PNEWy-eBM-p2](https://href.li/?PNEWy-eBM-p2)

**Comment by markbiek** [comment]
There's some ongoing discussion about whether to use the new generic headstart or to generate the headstart from the demo site. In case someone else picks this up, there are diffs open for each option.

Discussion: p1680184351000579/1680120346.535099-slack-C029FM1EH

Generic headstart:     D106542-code
Demo site headstart: D106602-code

**Comment by sixhours** [comment]
Glotpress project created and POT diff is here: D106884-code

**Comment by sixhours** [comment]
Headstart annotation sent for translation, strand ID 170925

**Comment by sixhours** [comment]
Removing from soft launch filter: D108156-code

**Comment by sixhours** [comment]
Amulet has launched!
