### ISSUE TITLE
☂️ Site Assembler - Write Flow (core patterns)

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#72329]
# Description
Part of **Site Assembler** project. 
PT: **Pattern Assembler in the Write Flow**. See: pbxlJb-3hx-p2

We want to present the Site Assembler in the onboarding Write flow. This project will enable blog patterns and query block patterns to be selected in the Pattern Assembler so we can present the Assembler step in the Write Flow.

# Acceptance Criteria
- [ ] Discuss with theme designers new patterns. See this slack convo p1661849184727399/1661827036.318049-slack-CRWCHQGUB
- [ ] Show the Site Assembler CTA in the design picker in the `write` and `build` flow.
- [ ] Show `core` query patterns in the category `Posts` in the site assembler.
- [ ] Render `core` query pattern previews with `4` fake posts. Maybe from `dotcomverticalposts`.
- [ ] Create actual posts (the same as the fake posts used for the previews) on the user's site before landing on the editor at the end of the site assembler flow.
- [ ] Ensure that the query patterns selected in the assembler flow are displayed correctly in the editor and the site front-end

# Dev Tasks
- [ ] Add a condition to include the blank canvas theme in the list of starter designs for the `write` intent. See the [line](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx#L105). 
- [ ] Update the site assembler to fetch patterns from the API endpoint `public-api.wordpress.com/wp/v2/sites/[ SITE ID ]/block-patterns/patterns` rather than using a hardcoded [file](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts).
- [ ] Update the API endpoint `/sites/[ SITE ID ]/block-renderer/patterns/render` to receive `pattern-names` rather than `pattern-ids` and fetch their content from the pattern registry.
- [ ] Update the BlockRenderer component to [fetch/render](https://github.com/Automattic/wp-calypso/blob/trunk/packages/block-renderer/src/hooks/use-rendered-patterns.ts#L10) patterns by `slug` rather than by `id` because the API endpoint `public-api.wordpress.com/wp/v2/sites/[ SITE ID ]/block-patterns/patterns` returns pattern `slug` as `name`.

# Dev Notes
The `core` query patterns are not coming from `dotcompatterns`, they are in WordPress core, in the folder `/wpcom/wp-includes/block-patterns`. See fbhepr%2Skers%2Sjcpbz%2Sjc%2Qvapyhqrf%2Soybpx%2Qcnggreaf%2S-og

There aren't `core` query patterns in the Pattern Directory for now, but we expect to have them in the future. 

All `core` and `dotcompatterns` patterns are registered in the WordPress Registry class in the ETK plugin when the request to `/sites/[ SITE ID ]/block-patterns/patterns` is received.

Patterns from `dotcompatterns` use the prefix `a8c/`, and from `core` use `core/`. 
<img width="275" alt="Screenshot 2566-01-19 at 14 49 57" src="https://user-images.githubusercontent.com/1881481/213387115-489a09a0-3316-42da-a8d8-15a773fbff39.png">

Patterns from the registry are fetched using the pattern name `slug` as identifiers. Here is an example of fetching a pattern from the registry.

```
$registry = \WP_Block_Patterns_Registry::get_instance();
$registry->get_registered( 'core/query-medium-posts' );

/*
Array(
    [name] => core/query-medium-posts
    [title] => Image at left
    [blockTypes] => Array(
        [0] => core/query
     )
    [categories] => Array(
        [0] => query
     )
    [content] => <!-- wp:query {"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
	<div class="wp-block-query">
	<!-- wp:post-template -->
	<!-- wp:columns {"align":"wide"} -->
	<div class="wp-block-columns alignwide"><!-- wp:column {"width":"66.66%"} -->
	<div class="wp-block-column" style="flex-basis:66.66%"><!-- wp:post-featured-image {"isLink":true} /--></div>
	<!-- /wp:column -->
	<!-- wp:column {"width":"33.33%"} -->
	<div class="wp-block-column" style="flex-basis:33.33%"><!-- wp:post-title {"isLink":true} /-->
	<!-- wp:post-excerpt /--></div>
	<!-- /wp:column --></div>
	<!-- /wp:columns -->
	<!-- /wp:post-template -->
	</div>
	<!-- /wp:query -->
)
*/
``` 

# Testing 
* Create a new site
* Select a domain and a plan
* In the goals screen, select `Write & Publish`
* Continue until the Design picker and scroll down to click `Start designing`
* Add patterns from the category `Posts`
* Make sure the previews have 4 posts and look good
* Click `Continue` to complete the flow and you'll land in the editor
* Make sure the previews in the editor and the site front-end match the previews in the assembler

## Related
Spike: https://github.com/Automattic/wp-calypso/issues/68133
WordPress Patterns 101: pekYwv-51-p2

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
