### ISSUE TITLE
Email Stats: we need to cancel deprecated requests to the backend.

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#72353]
When the user clicks on a new period (hours or days) or if they click in the left or right arrows, this triggers a new fetch of the data from the backend.

![Image](https://user-images.githubusercontent.com/3832570/213558843-a04747e8-1e3b-4456-93c7-9dacd5417d75.png)

However, the user can click multiple times, and that will pile up the requests to the backend. It's possible that those responses doesn't come at the same order they were requested, making the data shown to the user wrong and inconsistent.

We need to make the previous request to be canceled when the new one is made.

**Comment by TimBroddin** [comment]
I agree. 

`fetch` has an [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) which can be called to abort a request. However, we'd have to go deep into wpcom.js's internals to be able to cancel inflight requests.

**Comment by TimBroddin** [comment]
It seems requests are being made by this package: https://github.com/Automattic/wpcom-xhr-request 
Which in turns uses this package to make XHR requests: https://github.com/ladjs/superagent

**Comment by JuanLucha** [comment]
If there is no way at the moment to cancel the request, we could invalidate the response making a check in the `then` of the promises somehow.

**Comment by TimBroddin** [comment]
I think one possible solution would be to move out our API calling functions from wpcom.js and make them regular `fetch` calls. We wouldn't be the first ones to do that:

<img width="1655" alt="CleanShot 2023-01-20 at 11 29 43@2x" src="https://user-images.githubusercontent.com/528287/213674097-0a6a1a00-ea28-443f-ab2f-8509ee6a6a32.png">

(and we'd also not be the first ones to use an AbortController in the codebase either)

**Comment by JuanLucha** [comment]
I like the idea of using `fetch`

**Comment by TimBroddin** [comment]
Here's a nice example of combining this with Redux: https://spencerfeng.medium.com/create-an-abortable-api-using-abortcontroller-and-abortsignal-d774bed40701

**Comment by TimBroddin** [comment]
It might be a little tricky because we are firing multiple HTTP requests in a method. But nothing tricky is impossible!

**Comment by yansern** [comment]
I have 2 questions in mind (I haven’t look deeper technically so bear with me):

- Does the abort() function exist in wpcom.req.xhr.abort()? And is this somehow exposable through (what I imagine) are layers of abstractions?
- Would you need to pass in some kind of auth token (BearerToken?) when making a request using fetch? Would be curious how/where to retrieve this in Calypso, probably it is somewhere in the wpcom lib.

**Comment by TimBroddin** [comment]
I answered on P2, but I'll summarize it here as well to keep it documented:

- Requests are proxied through an iframe, making implementing abort difficult. There seems to be support to abort request support on the proxy side of things, but we'd have to implement it inside [wpcom-proxy-request](https://href.li/?https://github.com/Automattic/wpcom-proxy-request) as well.
- The token is stored "inside" the iframe as well, I can't seem to find a way to retrieve it on the Calypso side.

Link to full dive: pdDOJh-1ou-p2
