### ISSUE TITLE
This block has encountered an error - Classic Block in Posts Content Block

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#72358]
### Quick summary

"This block has encountered an error and cannot be previewed." error appears when a classic block is part of page content that is being shown on the site editor through a post content block

### Steps to reproduce

1. Create a page. Add a classic block to it with any written content
2. Go to the site editor, add a post content block
3. The post content block shows "This block has encountered an error and cannot be previewed."
4. Go back to the page, change the classic block to a paragraph block. It now works in the site editor

### What you expected to happen

That the post content block would not produce an error

### What actually happened

The post content block produced an error

### Context

5881693-zd

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Problem was on both Munchies and Blank Canvas

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on P2 -  Could Not Replicate 
- Tested on Simple -  Could Not Replicate 
- Tested on AT - Could Not Replicate 
- Tested on Self-hosted -  Could Not Replicate 
- Replicable on Core - No

📌 ACTIONS
- Await author feedback

📌 Message to Author

Hey @rickmgithub  ! Can you include more specific testing instructions, a screengrab, or a link to the site you tested on, so we can try and replicate this. I was not able to replicate this on simple, atomic, and self-hosted sites

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Closing report due to stale conversation. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
