### ISSUE TITLE
[Bug]: "Switch site" link gets hidden when scrolling 

### ISSUE THREAD

**Issue by jimjasson** [Automattic/wp-calypso#72367]
### Quick summary

When on a Calypso page on an Atomic site, a "Switch site" link shows up at the top of the menu: 

![Markup on 2023-01-20 at 14:12:57](https://user-images.githubusercontent.com/25955483/213692464-932e1813-1b62-448e-91bc-32f28d149699.png)

This link gets hidden when scrolling up and down the page and never appears again: 

https://user-images.githubusercontent.com/25955483/213693304-cd16e264-f15a-4116-9474-cd80655acd25.mp4

The issue is resolved only when reloading the page.

### Steps to reproduce

1. Open an Atomic site. 
2. Go to a Calypso page -- for example, "Pages".
3. Ensure that "Switch site" is visible. 
4. Scroll all the way down and then all the way up. 
5. "Switch site" gets hidden.

### What you expected to happen

I would expect that when I scroll back to the top of the page, "Switch site" would remain visible.

### What actually happened

When I scroll back up, "Switch site" gets hidden and I cannot click it. 

### Context

Internal testing

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to replicate the hiding `Switch Site`. On AT sites, I'm able to scroll back to the top and switch sites as expected.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
