### ISSUE TITLE
Move terms and conditions above button

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#72365]
See: 
![CleanShot 2023-01-20 at 15 26 32@2x](https://user-images.githubusercontent.com/533/213668069-b053d3cb-8802-4de9-a392-c3d74f817be9.png)

**Comment by ouikhuan** [comment]
The wording suggested by Jenny in [#28770](https://github.com/Automattic/jetpack/pull/28770)

> By clicking "Get Started," you agree to our [Terms of Service](http://wordpress.com/tos/) and to [share details](https://jetpack.com/support/what-data-does-jetpack-sync/) with WordPress.com.
