### ISSUE TITLE
[Bug]: UI gets stuck after activating hosting features

### ISSUE THREAD

**Issue by wojtekn** [Automattic/wp-calypso#72371]
### Quick summary

When I activate hosting features, the page gets stuck on the “Please wait while we activate the hosting features.“ message. Hosting features seem to be activated, but the page doesn't reload.

### Steps to reproduce

1. Create a site with a Business plan
2. Navigate to Settings -> Hosting Configuration
3. Activate hosting features and confirm domain change

### What you expected to happen

The page reloads after the process is done.

### What actually happened

"Please wait while we activate the hosting features." is displayed all the time.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

After some time, I can refresh page manually.

**Comment by kozer** [comment]
@wojtekn , I tried the steps you provided, and couldn't replicate this. Do we have a consistent way of reproducing the issue?
I know that this bug exists, or at least it was, as I have faced it in the past.

**Comment by wojtekn** [comment]
@kozer I just performed steps from the ticket description. When I try the process ten times, usually I'm redirected one or two times, and the rest is stuck.

**Comment by worldomonation** [comment]
There is no screenshot or video on the initial report, but if I understand correctly I was able to reproduce the issue on my test blog that I converted to a WoA site. ID: 216644510.

I was trying to enable SFTP to the blog as part of Jetpack release testing process. The page has been stuck at this screen for well over an hour.

![image](https://user-images.githubusercontent.com/6549265/227061075-a18b8c94-644f-47bb-8841-a1c6f4d520a9.png)

**Comment by worldomonation** [comment]
Once the page is refreshed, the same message is shown for a brief second and then the page is replaced with expected hosting configuration details.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on a Simple Business site - gave the screen about 3 minutes, and then refreshed to find that the advanced Biz plan features were there.
- About 1m10s in, my site address updates from `.wordpress.com` to `.wpcomstaging.com`, but the page itself didn't update until I refreshed the screen.

**Screenshots/Recordings**

https://user-images.githubusercontent.com/27249804/231600640-f5634c66-8f0e-4057-8de6-b7515915b4d0.mov

📌 ACTIONS
- Assigned to Build
- CC: @Automattic/reactor 

📌 Message to Author
- Anecdotally, I run into this frequently when helping customers, as we'll often have people transfer their site to AT while in chat with us, and have to ask them to refresh the page, or do so on our side instead.

**Comment by danielbachhuber** [comment]
Another report https://github.com/Automattic/dotcom-forge/issues/2151

**Comment by ash1eygrace** [comment]
I just encountered this issue today while doing some testing for something else. 

Calypso is stuck in the activating state even though the Atomic transfer has completed. After the transfer is complete, once you refresh, the banner goes away, and the hosting config page is displayed as normal.

**Comment by mpkelly** [comment]
I will take a fresh look at this because it seems like it has been flaky for ages.

**Comment by zaguiini** [comment]
@mpkelly There is some (old) work in https://github.com/Automattic/wp-calypso/pull/77112 that might be valuable.
