### ISSUE TITLE
Ads: disable WordAds for flagged sites

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7237]
For sites that have been flagged for some reason, we should not allow the user to enable WordAds. But we should give them an error message that explains this. I think it makes sense to do so at the point they would otherwise enable WordAds, here.

Rather than hiding it on the "my-plan" page that lists features, I think it would make sense to show some sort of error notice on the page where you enable WordAds and disable the button to "Join WordAds".

![WordAds enable page](https://cloudup.com/cxrbeJhZIEu+)

**Comment by artpi** [comment]
Fixed
