### ISSUE TITLE
Profile Management: update Gravatar without leaving Calypso

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#7238]
> the user profile page doesn’t have any options, links, or pointers that inform users what to do in order to change their profile image. Only by hovering and clicking around the page did I discover that clicking my avatar image on the left takes me to Gravatar.com.
> [...]
> it loads Gravatar.com and redirects me away from the backend of my WordPress.com site without providing an easy way to go back to where I started.
> 
> **Perhaps some sort of lightbox or a modal could be added that simplifies the process without redirecting users to Gravatar.com.**

Suggested here:
https://wptavern.com/managing-gravatars-in-wordpress-is-a-jarring-user-experience

**Comment by mtias** [comment]
For sure, the redirect to gravatar has been annoying for a really long time, and the current hover thing was supposed to be a short term thing. (Note: all short term things become eternal.) There were mockups for changing the gravatar (and cropping) in place since very early in Calypso. However, as far as I know, the main limitation is still the API from gravatar.

cc @rickybanister @ebinnion

**Comment by rickybanister** [comment]
It'd be great to make something happen with this.

**Comment by ebinnion** [comment]
I haven't looked into the API side of Gravatar, so I can't speak to that. But, I can try and look into this after we get 4.2 and a few other Jetpack things on my plate addressed.

**Comment by ebinnion** [comment]
For what it's worth, I just updated my Android WordPress Beta app, and the first thing I saw was something like:

"Tap your Gravatar to update"

@oguzkocer - Do you know who worked on that?

**Comment by oguzkocer** [comment]
@ebinnion: @hypest worked on it and I think the API is fully functional now.

**Comment by ebinnion** [comment]
Looks like the code to implement this in Android is here: https://github.com/wordpress-mobile/WordPress-Android/blob/24c81ba9e84e9b12ecec9de14534a1621e6eca66/WordPress/src/main/java/org/wordpress/android/networking/GravatarApi.java

**Comment by rralian** [comment]
> (Note: all short term things become eternal.)
#truth

> There were mockups for changing the gravatar (and cropping) in place since very early in Calypso.

Any idea where those live? I'm having trouble finding them.

**Comment by jeherve** [comment]
Fixed in #8456
