### ISSUE TITLE
[Bug]: When a new post is published with a Featured Image, the image does not show in the post content.

### ISSUE THREAD

**Issue by seamusberkeley** [Automattic/wp-calypso#72381]
### Quick summary

Jetpack sends for new posts do not include featured image. This includes email to subscribers and in the WordPress app.

Notice this was an issue in the past (https://github.com/Automattic/wp-calypso/issues/62994) that was supposed to have been resolved; it is still occurring.

### Steps to reproduce

1. Create post with featured image
2. Schedule post
3. Post is made
4. Email sent to subscribers does not include featured image
5. WordPress app notification appears without image

### What you expected to happen

Featured mage was supposed to appear in email and app

### What actually happened

No featured image was included

### Browser

Apple Safari

### Context

Research issue

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by ivan-ottinger** [comment]
Hello @seamusberkeley 👋🏼 

Thank you for the issue report.

When navigating to https://wordpress.com/settings/reading/, is the following setting enabled?

![Markup on 2023-03-06 at 12:31:02](https://user-images.githubusercontent.com/25105483/223098530-179706ac-7908-496b-9394-86f2965f8b92.png)

One thing to note is that there's an [ongoing issue with sites hosted on Bluehost](https://github.com/Automattic/wp-calypso/issues/62994#issuecomment-1455950637).

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Ran a test of this on a couple test sites, and can confirm that with the setting @ivan-ottinger noted above enabled, new post emails did include the Featured Image in the body of the post.  

**Screenshots/Recordings**

![Markup on 2023-04-11 at 17:24:30](https://user-images.githubusercontent.com/27249804/231316335-fcd962f9-eb88-4d00-baf4-1cf4a38e6245.png)


📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- Thank you for the report @seamusberkeley !
