### ISSUE TITLE
Attar: Not Saving Site Editor Changes

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#72389]
### Quick summary

On a site with the Attar theme active, the changes you make on the Site Editor aren't being saved.

### Steps to reproduce

1. Activate Attar on your site.
2. Go to Appearance > Editor.
3. Make a change to the content and hit Save.
4. Close the Editor, and open it again.

### What you expected to happen

To see the changes you saved.

### What actually happened

Changes you made are lost.

### Context

Found when trying to help a user remove the Post Title block from the Page template. Chat: 39602678-hc - cc @kerrynicl 

### Theme-specific issue?

Yes, Attar. Wasn't able to replicate with a different theme.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

We need to use custom CSS code instead.

**Comment by carinapilar** [comment]
Closing this one in favor of the Blockbase thread here: https://github.com/Automattic/wp-calypso/issues/72172

**Comment by cuemarie** [comment]
Compiling reports over here instead! https://github.com/Automattic/wp-calypso/issues/72684
