### ISSUE TITLE
WCCOM NUX: Incorrect NUX redirect for non-NUX flows

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#72400]
In p6JqRr-8pg-p2, it was found that new users who sign up via the login link are redirected to NUX.

A potential fix would be to ensure a default login behaviour should go to dashboard while users who go to "Get started" is redirected to NUX.

A good interim fix would be to make sure users who clicks on "Log in" would not be redirected to NUX. More discussions required to find out a better solution to separate users who wants to:

1. "Get started" to set up a WooCommerce site
2. "Get started" to explore WooCommerce extensions or other non-NUX related

**Comment by rjchow** [comment]
The oauth redirect is actually correctly populated, e.g when I click on "Log in" it has the redirect url param as:
`&redirect_uri=https://woocommerce.com/wc-api/wpcom-signin?next=my-dashboard`

So it seems to be some other redirect flow going on in the backend when a new user is detected. I also don't think it is the auth code on public-api.wordpress.com, so it's most likely something going on with code in wccom.

I wonder if we're hitting this branch? https://github.com/Automattic/woocommerce.com/blob/b78391c1e5e47b9a983a052adcd8a37b21317bbb/plugins/woothemes-wpcom-signin/includes/class-woothemes-wpcom-signin.php#L284

I'm EOD so I'm just dumping my findings here for now

**Comment by rjchow** [comment]
Determined that this issue is not relevant to wp-calypso (p6JqRr-8pg-p2#comment-15411), so I'm closing it
