### ISSUE TITLE
Update WCCOM local development database dump to include all the new Marketplace products

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#72403]

**Comment by cpapazoglou** [comment]
How urgent is this @JulianBustamante ? How much will it help us in WC.com development?

**Comment by JulianBustamante** [comment]
This is not that urgent, I will set the priority to low. This will help us to test changes from the local environment. For instance, last time we had to test changes on the Host API the products had to be exported on prod and imported on dev to make the tests work.
