### ISSUE TITLE
Skip onboarding default theme: default theme when skipping onboarding should be TT3 with hello world post

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#72413]
# Description

If the user skips onboarding, meaning "Skip to dashboard" on the Goals screen the default theme they get should be TT3.

I think this will be covered with [Change default theme for build flow to Twenty Twenty Three](https://github.com/Automattic/wp-calypso/issues/70604), but making this issue to be sure it gets covered.

![Image](https://user-images.githubusercontent.com/5665959/213982658-636e38b0-8a43-4b48-b7ac-38ec6ec5deb9.png)

# Related
https://github.com/Automattic/wp-calypso/issues/72410
https://github.com/Automattic/wp-calypso/issues/70604

**Comment by arthur791004** [comment]
I tested on https://github.com/Automattic/wp-calypso/pull/71025 and “Skip to dashboard” works as expected 🎉

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/issues/70604
