### ISSUE TITLE
Write default theme: headstart settings for Livro  produce incorrect reading settings

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#72410]
# Description

See @ianstewart's report of this issue pekYwv-xu-p2#comment-414

## What should happen
Livro homepage should be
https://livrodemo.wordpress.com/
https://github.com/Automattic/themes/tree/trunk/livro
From the demo site:
![image](https://user-images.githubusercontent.com/5665959/213969380-ee99c41e-f99c-4e30-b6c6-57e838954e91.png)

## What is happening (and is wrong)
* "homepage displays" is set to static page with  "Home" selected
* See settings in https://code.a8c.com/source/pub/browse/livro/inc/headstart/en.json, these look correct: `  "show_on_front": "posts"`
* Additionally I can see the content in the headstart file isn't being applied
* Thus I conclude the default headstart annotation is being used instead of Livro's
![image](https://user-images.githubusercontent.com/5665959/213969026-866b753f-1528-46a0-9402-c38bdd22046c.png)
![image](https://user-images.githubusercontent.com/5665959/213970509-23559501-5e67-481c-b1c3-356f7d1eef79.png)

Here is what Livro looks like in the DP:

# Related 
* [Headstart Issues for New Sites] paYE8P-1nV-p2

**Comment by autumnfjeld** [comment]
See more slack convos: p1675835558366129/1674460018.673149-slack-C048CUFRGFQ
> I’m asking to double check that this is then true:
In write flow, the default theme Livro uses the annotations created from the demo site
In build and other flows, where user skips and gets the default TT3 we will only have 1 post and no pages

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/75818
