### ISSUE TITLE
LaunchPad - Remove nav bar CTA override.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72430]
Lets remove/revert overriding the domains upsell in the nav sidebar for a launchpad CTA.

revert - https://github.com/Automattic/wp-calypso/pull/70325 
abandon - https://github.com/Automattic/jetpack/pull/27694

See pebzTe-DF-p2

**Comment by jeyip** [comment]
Closed https://github.com/Automattic/jetpack/pull/27694
