### ISSUE TITLE
Marketplace Themes: Can't activate Makoney after resetting the site

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#72444]
Users are not able to activate Makoney theme after resetting their site.

Slack thread: p1674361885647269-slack-C0160HSMDQV

**Comment by valterlorran** [comment]
I tried activating Tsubaki, it got transferred to Atomic as expected. However, the selected theme was Makoney.

**Comment by daria2303** [comment]
I am having the same error on my test sites, one atomic, and another one simple with Biz plan.
