### ISSUE TITLE
Editor: Cursor behaves unexpectedly with Grammarly Safari Extension

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#7245]
#### Steps to reproduce
1. Install Grammarly Safari Extension
2. Starting at Editor
3. Type five words in post body
4. Select for example the second word
5. Start typing to rewrite selected word
#### What I expected

To rewrite the word.
#### What happened instead

Cursor jumps all over the paragraph while typing.
#### Browser / OS version

Safari with Grammarly extension
#### Screenshot / Video

https://cloudup.com/cEfipYSM3Wj
#### Context / Source
# user-report

**Comment by lancewillett** [comment]
Maybe not something we can officially support since it's a 3rd party extension?

How does it work with wp-admin editor?

I suggest closing this one.

**Comment by marekhrabe** [comment]
I have contacted Grammarly engineers about the problem (they were well aware of it) and linked them to this issue in case there is something that we might help with to resolve it. As there is no response here, I would be in favor of closing too.
