### ISSUE TITLE
Domain Mapping Removal: Confusing messaging "Sorry to see you go"

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#72456]
### Quick summary

When a user tried to remove a mapped domain, the next says 

* Remove product: `site address`
* Sorry to see you go

The messaging is confusing as it seems to indicate the site is being deleted rather than removing the domain mapping

Screenshot: 

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/33957570/214144923-5338709a-34bd-4917-88dc-801ea3c9bbdb.png">

### Steps to reproduce

1. On a site with Domain connection, go to Upgrades > Purchases.
2. Remove the domain connection.
3. You will encounter the final screen with confusing messaging.

### What you expected to happen

The confirmation screen should be more specific and accurately inform what exactly is being removed.

### What actually happened

It seemed the site is being removed. 

### Context

User report: 37438430-hc

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 ACTIONS
- Looks like this matches this existing feature request: https://github.com/Automattic/wp-calypso/issues/67705

📌 Message to Author
- Thank you for the feature request @devNigel ! Closing this on in favor of the other
