### ISSUE TITLE
Template edits don't save on Jackson theme

### ISSUE THREAD

**Issue by kcswong** [Automattic/wp-calypso#72474]
### Quick summary

Trying to edit the Page template with a site using the Jackson theme appears to save changes, but those changes aren't reflected on the site, and returning to the template editor will show the changes did not successfully save.

### Steps to reproduce

1. Start in Appearance > Editor, then select the Page template to edit
2. The change I attempted was removing the Post Title block
3. Save changes

### What you expected to happen

For the title to be removed on all pages using the default page template.

### What actually happened

The titles remained and were not removed.

### Context

Customer report, follow up ticket in 5891696-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Jackson

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Could Not Replicate**
- Tested on AT: **Could Not Replicate**
- Tested on Self-hosted: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- In all tests, changes made to the Page template were saved properly and shown on the live site.  Tested on Simple, AT, and Self-hosted, by deleting Post title and/or adding text below it.

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
