### ISSUE TITLE
General Onboarding: Investigate and document onboarding goals

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#72479]
Different onboarding views are displayed in general onboarding depending on what goals are indicated by the user paYE8P-2op-p2. Documenting and understanding the intention of each goal could help inform what tasks would be appropriate for the general onboarding launchpad screen.

Investigation and documentation can take the form of a p2, similar to what @Addison-Stavlo has done here paYE8P-2op-p2

<img width="1496" alt="Screen Shot 2023-01-23 at 6 59 12 PM" src="https://user-images.githubusercontent.com/5414230/214203573-ba92bc39-9cac-432c-b718-ee67ba9b299a.png">

https://github.com/Automattic/wp-calypso/issues/72459

**Comment by Addison-Stavlo** [comment]
we investigated some this week - some context here paYE8P-2tn-p2 - and decided to start with `write` and `build` site intents which correspond to "write and publish", "promote", "other" and "skip to dashboard" goals.
