### ISSUE TITLE
General Onboarding: Disable Launchpad if user skips to dashboard

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#72478]
Should we disable launchpad in general onboarding if the user indicates that they want to skip the onboarding flow?

![Screen Shot 2023-01-23 at 6 53 43 PM copy](https://user-images.githubusercontent.com/5414230/214203137-aa495ec8-e3b3-4de3-8095-7e5126cadfcb.jpg)

https://github.com/Automattic/wp-calypso/issues/72459

**Comment by Addison-Stavlo** [comment]
closing this. as we decided and implemented to make this skip button enable the `build` site_intent by default and get that launchpad.
