### ISSUE TITLE
General Onboarding: Create Launchpad task list

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#72477]
For very specific use case onboarding flows (like newsletters and link-in-bio) we have a good understanding of what the user is trying to accomplish and thus can surface a relevant checklist to help guide them. But this is not the case in general onboarding, users from the same onboarding flow may have very different initial intentions and goals for their site.

Without knowing the users intentions it is difficult to surface a relevant checklist to them that is helpful and not restrictive or presumptuous. So how do we determine this accurately? Or can we determine a good starting checklist that is relevant for all users coming from the general flow?

paYE8P-2dY-p2

**Comment by Addison-Stavlo** [comment]
closing in favor of https://github.com/Automattic/wp-calypso/issues/72569
 https://github.com/Automattic/wp-calypso/issues/72570

we discussed initial checklists in paYE8P-2dY-p2 as well as our recent planning meeting paYE8P-2tn-p2 and are starting with basic checklists for the most basic of intents. These give access to creating posts and updating styles in the site editor. We can expand from there in further iterations.
