### ISSUE TITLE
General Onboarding: Find or create tracks funnel for general onboarding with Launchpad

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#72480]
We want to track whether or not user churn is reduced with the introduction of Launchpad in general onboarding. Find or create a tracks funnel which can do so.

PCYsg-4D1-p2

https://github.com/Automattic/wp-calypso/issues/72459

**Comment by Addison-Stavlo** [comment]
closing this as we have funnels evaluated on the project thread.
