### ISSUE TITLE
Reading Settings: Update the label/description on the "Welcome email text" and "Comment follow email text" settings

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#72485]
Context: pdtkmj-Vc-p2#comment-1624

The newly-added text-areas in the Calypso Reading settings page need better suited labels and descriptions:

**Before / current labels:**
![Markup on 2023-02-06 at 10:28:47](https://user-images.githubusercontent.com/25105483/216936886-de785b79-3b0c-48cb-ba9d-28d890812774.png)

**After:**
![Markup on 2023-02-06 at 10:26:22](https://user-images.githubusercontent.com/25105483/216936939-9bb3b960-b19a-4705-add8-364c2e0778bf.png)

TODO:
- [x] Add issue description and screenshot
- [x] Agree on the new label for the setting
- [x] Create PR - please note that the change will create a new string and therefore we need to count with translation time

Similar code changes can be used as in https://github.com/Automattic/wp-calypso/pull/72709/files

**Comment by mashikag** [comment]
I see there is an ongoing discussion (pdtkmj-Vc-p2#comment-1624) for the new label which is good 👍

I will mark the issue as 🔴 **Blocked** until we have agreed on the new title copy.

**Comment by ivan-ottinger** [comment]
Latest discussion: pdtkmj-Vc-p2#comment-1886.
