### ISSUE TITLE
Marketplace Themes: Add new meta field for the demo URL

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#72494]
Currently, we had to use the meta field intended to be used as the theme's landing page as the demo URL. In the future, some authors can have a different link for the landing page and the demo site. 

We should create a new custom meta field to store the demo URL. We also need to update the code I changed recently with the new custom meta field: D98563-code

**Comment by daledupreez** [comment]
I ended up collaborating with Bespin on this a few weeks ago as they were having issues with us using the same field for the screenshot and the main theme image used in the theme details page. We ended up resolving this via two changes:
 * D100532-code - this added meta fields for the demo URL and the screenshot URL
 * D100534-code - this ensured the new meta fields are used in the themes index
