### ISSUE TITLE
Stats: Investigate WordAds currency presentation

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#72492]
Per [this comment](https://github.com/Automattic/wp-calypso/pull/72320#discussion_r1083575318), we should confirm amounts on the Stats → Ads page are being handled correctly.

The current behaviour is to always display USD amounts with US formatting and a "$" symbol. I think this makes sense for WordAds if it's a USD-only program but it's worth confirming.

1. Is WordAds a USD-only program?
2. If so, does it make sense to localize the numbers?
3. If not, we need to update it to show localized amounts.

If we need to update the behaviour, the highlights (top row) and the tables should remain consistent.

**Update** — Currently we do localize the amounts. For example, on my CAD account, if switched to French, I see USD amounts as $0,00 instead of $0.00. When switching back to English, there's no indication that the amounts are USD as opposed to CAD either. Potentially confusing?

**Comment by a8ck3n** [comment]
Is WordAds USD-only? — Yes

p4x5kY-Zk-p2#comment-5083

With that in mind, does it make sense to localize the formatting of the amounts?

**Comment by jsnmoon** [comment]
Summoning friends of the team, @robfelty and @jeherve: Would you prefer to see USD amounts formatted to your locale (e.g., $123.45 -> $123,45)?

**Comment by robfelty** [comment]
Yes, it makes sense to format all numbers consistently, regardless of the currency. I would expect comma to be the decimal separator for German. Thanks for asking!

**Comment by jsnmoon** [comment]
Should be fixed by #72856!
