### ISSUE TITLE
Unable to delete or edit custom templates with a special character in title

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/wp-calypso#72510]
### Quick summary

Unable to delete custom templates created via the Site Editor if the custom template's name/title has a special character or uses an emoji. Users are also unable to edit templates with a title with a special characters. 

Not sure what characters are causing this issue exactly. One thing I noticed is that you can't delete a template if there is an emoji added to the name or if it uses a Greek character. I ran into this issue with a user who was writing in Greek. Issue seems present with nearly all Greek characters. 

When trying to delete a template with a special character, you see an error: `Error: No route was found matching the URL and request method.`

### Steps to reproduce

1. Head to _My Site → Appearance → Editor_
2. Create a new template (select Custom Template) 
3. Give the template a name. Try something like ΜΑΓΕΙΡΕΥΤΑ 
4. View your templates and then try deleting the custom template you just created: ΜΑΓΕΙΡΕΥΤΑ 
5. See error: No route was found matching the URL and request method.
6. Find that template is not deleted. Unable to rename template or delete template. 
7. Try editing the template - edit the template and save your changes, you will receive an error `Saving failed` 

Video with issue: 

https://user-images.githubusercontent.com/77413972/215183119-968f6b29-0440-401d-806c-81d38f0f5491.mp4

https://user-images.githubusercontent.com/77413972/214364842-11c34fe4-5e89-438f-9e64-c412c6616716.mp4

### What you expected to happen

I expected to be able to delete the template, regardless of name. 

### What actually happened

I am unable to delete template using (some) characters (like `Γ`). See error when trying to delete template instead: `Error: No route was found matching the URL and request method.`

Unable to edit template with special character, receive an error `Saving failed` 

### Context

Customer reported: 31349777-hc / 5893760-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by ahmadbaig1** [comment]
A user reported this as well. In this example, I was not able to delete the template if it had Korean letters. 
5895776-zen

**Comment by kerrynicl** [comment]
User also reported this in HC - 39988859. Unable to edit and save template named "Σελίδα: TO TAΨΙ ΤΗΣ ΜΑΜΑΣ"
created followup ticket 5904249-zen

**Comment by wpshellbelle** [comment]
Closing. Existing issues here:

https://github.com/WordPress/gutenberg/issues/45718
https://github.com/WordPress/gutenberg/issues/45633

**Comment by cometgrrl** [comment]
Re-opening so we can track user reports until we get a core fix.

**Comment by connorhipps** [comment]
Another user reported what seems to be the same issue here (In Greek): 5904489-zd-woothemes

**Comment by dolgelukkig** [comment]
Another one, with Chinese 
即可在本站自由发表作品-zen

**Comment by danielbachhuber** [comment]
Fix will be shipped in WordPress 6.2 https://core.trac.wordpress.org/ticket/57329

@cometgrrl Should we keep this open or close?

**Comment by cometgrrl** [comment]
@danielbachhuber For now, let's leave it open. HEs will often send a reply to customers when a fix is released, and that workflow is triggered by the issues in our repo being closed. 

I want to improve this process at some point because it requires manual monitoring of the linked external tickets. If you have thoughts on how we could do this more automatedly, I'd love to hear them. Something simple like issues watchlist and a notification in Slack that an issue on the list was closed would be a good starting point.
