### ISSUE TITLE
Plans: logged out pricing page styling issues

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#7252]
Because I naturally have my browsers set to odd sizes, I caught some styling issues on the /pricing page with the new style & personal plan updates:

![](https://cloudup.com/cN0NTFWHxfG+)

![](https://cloudup.com/cZXFJ1aLh9V+)
#### Steps to reproduce
1. Starting at URL: wordpress.com/pricing
2. narrow your browser window until you see The Weirdness™

**Comment by lamosty** [comment]
I think this is not a Calypso issue as wordpress.com/pricing is served from WP.com server and uses different codebase than http://calypso.localhost:3000/plans. Should I create issue for this in the internal tool?

cc @rralian as I'm not completely sure about this.
