### ISSUE TITLE
[Bug]: Missing Instagram and Jetpack Blocks On All Simple Sites

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/wp-calypso#72521]
### Quick summary

As of sometime today, the Instagram Block and the [Latest Instagram Posts](https://wordpress.com/support/instagram/#latest-instagram-posts-block) and all Jetpack blocks are not available on Simple sites. 

### Steps to reproduce

1. Edit a page or post on a Simple site
2. Click the block inserter (+) button
3. Search for Instagram or any Jetpack block
4. No results are found 

### What you expected to happen

I expected to find these Instagram Jetpack blocks available in the block editor 

### What actually happened

Instagram and [Latest Instagram Posts](https://wordpress.com/support/instagram/#latest-instagram-posts-block) are both missing. Jetpack blocks are also not available

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by cuemarie** [comment]
Troubleshooting happening here: p1674596371048279-slack-C02FMH4G8

**Comment by youbrokesomething** [comment]
The Jetpack team resolved this issue on the day it was reported.
