### ISSUE TITLE
Editor: publish scheduler is misleading/confusing

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#7253]
![](https://cloudup.com/cMEkNYL0K93+)
#### Steps to reproduce
1. Starting at URL: wordpress.com/post/[site]
2. Click the calendar/schedule icon on the right side of the `publish` button
3. Select a date in the future (ex. tomorrow)
4. Note that in the top bar, the time shows "tomorrow" +24 hours against your local time in standard time
5. Note that the input for the scheduler is in military time
6. Note that the bottom notice has a nod to UTC time
7. Wonder if you're scheduling a post against your local time or UTC.
8. Also wonder why yesterday's date is circled in gray but give up trying to figure it out because it's not relevant for the task at hand.
9. Leave scheduling to fate

I think we can clean this up a bit to make it more coherent. Suggestions include using either standard or military time uniformly and using either local time or UTC time across the board (preference would be local since UTC is not broadly used outside of the tech world).

**Comment by iamtakashi** [comment]
> 7. Wonder if you're scheduling a post against your local time or UTC.

This has been tackled in #10522 and #10558. These should clarify this confusion.

**Comment by iamtakashi** [comment]
> 4. Note that in the top bar, the time shows "tomorrow" +24 hours against your local time in standard time

This will be addressed #10762

**Comment by iamtakashi** [comment]
> 8. Also wonder why yesterday's date is circled in gray but give up trying to figure it out because it's not relevant for the task at hand.

This is relevant — when you make a schedule post, you would want to know the dates you previously scheduled for other posts. We display more info when you mouseover the circle. It might not be the best solution but it's clear what it is to me.

**Comment by iamtakashi** [comment]
I think this issue should be closed. The issues listed here have been (are going to be) tackled in separate tickets.
