### ISSUE TITLE
Welcome Tour: update when/how it appears in the site editor and/or browse mode

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#72533]
# Description

The Editor has a new UI "Browse mode"  [Heads up: A new Browse Mode is coming to the Site Editor] p7DVsv-g1G-p2.

Currently the Welcome Tour is appearing on top of the browse mode, which is awkward. See p1674232546963689/1674205328.303419-slack-C048CUFRGFQ

![Image](https://user-images.githubusercontent.com/5665959/214446990-3b4aaf73-cae3-460f-b9b9-12f0dff8ccc7.png)

There are a few approaches we could take to make this better:
1. Do not show the tour in browse mode, only show it once the user is in edit mode
2. Show the tour in browse mode and update Slide 1 to blend with the current state of the page, e.g. browse mode

The first option is easiest and makes more sense to me because the tour is meant to be an "interactive guide" where the user can do what the prompts suggest, live in the editor.

# Acceptance Criteria
- [x] Update the triggers for showing the tour so that is does NOT appear in browse mode, instead appears in edit mode
- [x] All the same rules apply, only show once when user opens the site editor for the first time

# Related
* https://github.com/orgs/Automattic/projects/338/views/1?filterQuery=welcome+tour

# Progress

- [x] https://github.com/Automattic/wp-calypso/pull/74242

**Comment by autumnfjeld** [comment]
This is more like "good fourth issue".    The update should be "simple", but will require getting familiar with a variety of code area/concepts.

**Comment by sankeerth125** [comment]
Hi @autumnfjeld can I work on this?

**Comment by autumnfjeld** [comment]
Hi, this is an issue for my team specifically.  But thank you for checking.  🤓

**Comment by sankeerth125** [comment]
ok, Thanks for the info.

**Comment by okmttdhr** [comment]
>The first option is easiest and makes more sense to me because the tour is meant to be an "interactive guide" where the user can do what the prompts suggest, live in the editor.

I agree with this. If we find users are having trouble with browse mode in the future, we can think about it then, so I thought it was OK to hide the tour.

Can we move this to `Ready for Dev`? @autumnfjeld

**Comment by autumnfjeld** [comment]
@okmttdhr  Yes, I am fine with your decision. :)  You can move to Ready for Dev.

Also, I just created another Welcome Tour issue.  It needs design work, but maybe you could have a look and ask @davewhitley what he thinks: https://github.com/Automattic/wp-calypso/issues/74089.   No rush on that, just wanted to let you know. :)

**Comment by okmttdhr** [comment]
And We better take the "Browse Mode" into consideration when we start working on https://github.com/Automattic/wp-calypso/issues/69156 (I added a note on it).
