### ISSUE TITLE
[Bug]: Checkout: Success notices are not displayed after redirect

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#72566]
### Quick summary

When the checkout URL contains a `redirect_to` parameter and the payment is successful, the user then redirect to the page specified in `redirect_to` parameter. However, the [successNotice](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/checkout/checkout-thank-you/pending/index.tsx#L298) component is not displayed on the redirect page, even though the `displayOnNextPage` option is set to `true`. 

I tried to debug it and see why is the `displayOnNextPage` property ignored, but without much luck.

cc @sirbrillig since you are probably more familiar with this than me. :) 

### Steps to reproduce

1. Go to checkout URL and pass a `redirect_to` that points to wp.com/themes/:your-site
2. Complete the payment and you'll be redirected to wp.com/themes/:your-site
3. Notice that the `Your purchase has been completed` notice is not displayed in the upper right corner

### What you expected to happen

To get the notice displayed

### What actually happened

The notice is displayed for a short period on the pending screen and after getting redirected, it disappears. 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by sirbrillig** [comment]
I've noticed problems with `displayOnNextPage` in the past, which is why sometimes I've resorted to `isPersistent` instead, although that forces the user to close the notice manually which is not ideal. 😞 I'll experiment with this some more to see if I can figure out what's happening (maybe there's a second redirect happening somewhere very quickly?) but if not, we might be able to try using `isPersistent` and combining it with `duration` so that it stays visible and disappears on its own.

**Comment by BogdanUngureanu** [comment]
Thanks for the quick response @sirbrillig, I've already tried to pass `isPersistent` on my local env but without luck, it still has the same behavior. 😢 I also did a bit of debugging in [the reducer](https://github.com/Automattic/wp-calypso/blob/0806b9c5b9c3343abed93a6a1b6afad78f73aefd/client/state/notices/reducer.js#L35) and noticed that even if I set the property to `true` (so that it's not dismissed at all), it still doesn't show.

**Comment by sirbrillig** [comment]
Hmmm.... maybe the page that you're ending up on (looks like `/themes/:site`?) doesn't include whatever component is supposed to display notices?

**Comment by BogdanUngureanu** [comment]
It's possible, but tbh, I'm unfamiliar with how the notices are implemented or work.

According to the docs
> It's unlikely you'll need to render GlobalNotices, because that will be handled by layout.

**Comment by BogdanUngureanu** [comment]
Oh, you are right! Since the theme/:theme page doesn't use the default layout, the notices are not displayed! Thanks a lot!

**Comment by sirbrillig** [comment]
Nice. It seems like we could alter the theme page layout to include `GlobalNotices`... not sure how much work that would be.

**Comment by BogdanUngureanu** [comment]
I've opened a PR that adds the [Global notice component to the theme page](https://github.com/Automattic/wp-calypso/pull/72588), but unfortunately, it looks like they still don't work. I did try it again with `isPersistent` but without luck. :(

I'll un-assign the issue from me, maybe someone has the capacity to work on it in the future.

**Comment by BogdanUngureanu** [comment]
Handled in https://github.com/Automattic/wp-calypso/pull/72379
