### ISSUE TITLE
Use the `hide_on_wpcom` flag to hide products on the Marketplace

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#72573]
Follow-up to https://github.com/Automattic/dotcom-forge/issues/1482

As the `hide_product_on_wpcom` field is synced to the shadow site, we can now use it when indexing products. As a preparation, we've considered this field when indexing the disabled field, but it was fetched as a meta field, not through the `extra_fields` fields:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Scyhtvaf%2Srynfgvpfrnepu%2Svaqrkvat%2Sjcrf%2Qyvo%2Qjcpbz%2Spbzzba%2Spynff.jcrf%2Qjcpbz%2Qcebqhpg%2Qcbfg%2Qsvryq%2Qohvyqre.cuc%3Se%3Q6s16onr7%2340%2Q45-og

We need to update this logic to get the field value from the extra fields object. The API response is already filtered based on this field, so this will hide all disabled products in Calypso: fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qznexrgcynpr%2Qfrnepu%2Qraqcbvag.cuc%3Se%3Q7325qr2p%23816-og

**Comment by gcsecsey** [comment]
Diff raised: D99316-code

**Comment by cpapazoglou** [comment]
@gavande1 can we use the same flag for hiding products in the dynamic catalog?

**Comment by gavande1** [comment]
Yes. I created [the issue](https://github.com/Automattic/dotcom-forge/issues/1555) for the same purpose.

**Comment by gavande1** [comment]
@gcsecsey Is it `hide_product_on_wpcom` or `hide_on_wpcom` that we want to use? Just to confirm.

**Comment by gcsecsey** [comment]
> @gcsecsey Is it `hide_product_on_wpcom` or `hide_on_wpcom` that we want to use? Just to confirm.

It's `hide_product_on_wpcom`. Sorry, I've typed it wrong in the description but fixed it now! 👍 

> Yes. I created https://github.com/Automattic/dotcom-forge/issues/1555 for the same purpose.

Actually, I was considering linking the diff to that issue. But to resolve that issue, I think we'll need to add a new parameter to the API endpoint. For that, we need to make the indexing working first, that's why I ended up raising a separate issue for it.

**Comment by gcsecsey** [comment]
Backend changes are now deployed in r260177-wpcom

I've re-indexed the Mailpoet business plan to make it hidden from search results:
![Image](https://user-images.githubusercontent.com/11555574/214824764-6cae5890-bf11-42d1-b9f9-4b6586c9cbe8.png)
