### ISSUE TITLE
[Enhancement]: Update to Mobile Promo Card on stats page

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#72596]
### Quick summary

We're looking to make some changes to [the `<MobilePromoCard />` component](https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/mobile-promo-card/index.tsx). The changes we're looking to make involve the following:

* Update the font so that it matches the other cards in the stats page's carousel.
* Use the [`<AnimatedIcon />`](https://github.com/Automattic/wp-calypso/tree/trunk/client/components/animated-icon) for the Jetpack app's icon, this is used for other mobile app promos within Calypso (see https://wordpress.com/me/get-apps for an example).
* Direct users to apps.wordpress.com (instead of jetpack.com/app) in order to download the Jetpack app.

Current screenshot:

<img width="1243" alt="Screenshot 2023-01-25 at 19 37 38" src="https://user-images.githubusercontent.com/2998162/214670195-2386cd65-76e1-4ce8-8048-81309fe0551a.png">

### Steps to reproduce

1. Navigate to _My Sites_ → _Stats_ in WordPress.com.
2. Scroll to the carousel at the bottom of the page.
3. Scroll through each of the carousel's cards until you reach the mobile promo.

### What you expected to happen

Each card in the carousel should use the same font. In addition, the mobile promo should be consistent with other mobile promos used throughout Calypso (including the animated icon and links to apps.wordpress.com).

### What actually happened

There are some inconsistencies that can be found in the mobile promo, including a different font.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by SiobhyB** [comment]
👋 @a8ck3n, @jsnmoon, we're looking to make some changes to [the `<MobilePromoCard />` component](https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/mobile-promo-card/index.tsx), and I see you were involved in its development. I was hoping you might be able to help with the following questions before I go ahead to make changes:

* Are there any blockers to us re-using the `<PromoCardBlock />` component, [similar to other cards in the stats page's carousel](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/promo-cards/index.jsx#L86-L95)? I'm thinking this might be the simplest route to ensuring all the styles in the carousel match up, but please let me know if I'm missing something.

If we want to continue using `<MobilePromoCard />` on the stats page, I have these extra questions:

* Is it necessary for `<MobilePromoCard />` to exist under [the `packages/components` directory](https://github.com/Automattic/wp-calypso/tree/trunk/packages/components) vs. [the `clients/components` directory](https://github.com/Automattic/wp-calypso/tree/trunk/client/components)? I ask because it'd be nice to use [`<AnimatedIcon />`](https://github.com/Automattic/wp-calypso/tree/trunk/client/components/animated-icon), which currently exists under `clients/components`, so there'd be some extra steps to getting this to work. It'd be useful to know if `<MobilePromoCard />` is being used outside of Calypso (and therefore if we should move `<AnimatedIcon />`). 

* The naming of this and the [`<AppPromo />`](https://github.com/Automattic/wp-calypso/tree/trunk/client/blocks/app-promo) component is a little confusing. What do you think of renaming? `<AppPromo />` could be `<SidebarAppPromo />` and `<MobilePromoCard />` could be `<FullWidthAppPromo />`?

Thanks in advance for your help!

**Comment by jsnmoon** [comment]
I took a stab at answering your questions, but @a8ck3n may be able to provide more details.

> Are there any blockers to us re-using the `<PromoCardBlock />` component, [similar to other cards in the stats page's carousel](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/promo-cards/index.jsx#L86-L95)? I'm thinking this might be the simplest route to ensuring all the styles in the carousel match up, but please let me know if I'm missing something. (@SiobhyB)

Not at all. Feel free to send the team pull requests to review!

> Is it necessary for `<MobilePromoCard />` to exist under [the `packages/components` directory](https://github.com/Automattic/wp-calypso/tree/trunk/packages/components) vs. [the `clients/components` directory](https://github.com/Automattic/wp-calypso/tree/trunk/client/components)? I ask because it'd be nice to use [`<AnimatedIcon />`](https://github.com/Automattic/wp-calypso/tree/trunk/client/components/animated-icon), which currently exists under `clients/components`, so there'd be some extra steps to getting this to work. It'd be useful to know if `<MobilePromoCard />` is being used outside of Calypso (and therefore if we should move `<AnimatedIcon />`). (@SiobhyB)

Not particularly, no. We're currently not consuming the MobilePromoCard component outside of Calypso via NPM. (We are, however, distributing this component with the Jetpack plugin via Odyssey Stats; see PejTkB-3B-p2.)

Admittedly, I am curious about what blockers exist around moving the animated icon component into the components package. (That animated icon looks great, by the way!)

> The naming of this and the [`<AppPromo />`](https://github.com/Automattic/wp-calypso/tree/trunk/client/blocks/app-promo) component is a little confusing. What do you think of renaming? `<AppPromo />` could be `<SidebarAppPromo />` and `<MobilePromoCard />` could be `<FullWidthAppPromo />`? (@SiobhyB)

Your approach sounds good! Happy to provide more detailed feedback in a PR.

**Comment by a8ck3n** [comment]
Hello @SiobhyB! 👋 

> Are there any blockers to us re-using the `<PromoCardBlock />` component, [similar to other cards in the stats page's carousel](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/promo-cards/index.jsx#L86-L95)? I'm thinking this might be the simplest route to ensuring all the styles in the carousel match up, but please let me know if I'm missing something.

The main reason we didn't use the `PromoCardBlock` is that the component has some logic built in to allow it to show the correct promo (Jetpack Vs Woo) based on the current device (mobile Vs Desktop). If you opt to use `PromoCardBlock` for everything, you'll need to reimplement that logic somewhere. If you poke around in the component you'll see the messaging, links, and image all change depending on the users environment.

Looking at your proposed changes:

> Update the font so that it matches the other cards in the stats page's carousel.

I'll refer you to [this discussion](p1HpG7-iwG-p2#comment-57871). My reading of the discussion there is they purposefully moved away from the existing design/styling for this promo card. That said, we didn't initially plan to have it as part of a `DotPager` either. I'd defer to @keoshi and @shaunandrews for any design changes.

> Use the `AnimatedIcon` for the Jetpack app's icon […]

This sounds like a nice change but in my testing, the animation fires on page load, which means we'd never see it as the promo cards on the Stats pages are always below the fold. If `AnimatedIcon` was updated to fire once visible, that would be neat.

> Direct users to apps.wordpress.com (instead of jetpack.com/app) in order to download the Jetpack app.

No issues here. Worth noting that if you stick with the `MobilePromoCode` component, the URL in the source is a fallback. The real URL can be updated without updating the code. See [this comment](https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/mobile-promo-card/index.tsx#L14) for details.

> The naming of this and the [`<AppPromo />`](https://github.com/Automattic/wp-calypso/tree/trunk/client/blocks/app-promo) component is a little confusing. What do you think of renaming? `<AppPromo />` could be `<SidebarAppPromo />` and `<MobilePromoCard />` could be `<FullWidthAppPromo />`?

Sounds good to me although I'd favour something that takes advantage of auto-completion to help discovery. ie: `AppPromoSidebar` and `AppPromoFullWidth`.

Hope that helps. Feel free to shoot me a ping if I can help with anything else!

**Comment by keoshi** [comment]
Hey @SiobhyB !

> Update the font so that it matches the other cards in the stats page's carousel.

Could you please go more into detail here and specify what font are you suggesting we change?

I noticed that the screenshot you shared above differs from what I see, namely the typeface in the paragraph that follows the title.

Your screenshot | My view
--|--
<img src="https://user-images.githubusercontent.com/2998162/214670195-2386cd65-76e1-4ce8-8048-81309fe0551a.png"> | <img width="1259" alt="image" src="https://user-images.githubusercontent.com/390760/214827044-d55468ec-2e38-45de-97a9-a662d6886482.png">

This seems to originate on a `font-family` override here:

https://github.com/Automattic/wp-calypso/blob/e9dfc697473e910a69330b6ca680d01e42b0f942/packages/components/src/mobile-promo-card/style.scss#L84

If this is what you're referring to, I totally agree and we should do one of the following:

1. Remove that line entirely.
2. Replace `"SF Pro Text", serif` by `inherit`

Both of which should make that paragraph use the system font as declared here: https://github.com/Automattic/wp-calypso/blob/b74abfa38d482735dfde4270f5312a732c58b783/packages/components/src/styles/_typography.scss#L1

**Comment by SiobhyB** [comment]
Thanks for your replies, all!

> Admittedly, I am curious about what blockers exist around moving the animated icon component into the components package. (That animated icon looks great, by the way!) (@jsnmoon)

I don't foresee any blockers, I suspect it'd be a simple change whichever way we go! As `<MobilePromoCard />` is being used in the Jetpack plugin, and may be used elsewhere in the future, I'll go forward with moving the animated icon component to the packages directory. 

> My reading of the discussion there is they purposefully moved away from the existing design/styling for this promo card. That said, we didn't initially plan to have it as part of a DotPager either. (@a8ck3n )
> Could you please go more into detail here and specify what font are you suggesting we change? (@keoshi)

Sure! For context, the inconsistent font was originally raised in a discussion with Shaun here: p1674146936609819/1674146762.669589-slack-C03KCB9USUW

@keoshi, each of the promo cards in the carousel only show up under certain conditionals. If all the necessary conditionals for showing all the cards are `true` then all three of these cards will show up:

Blaze promo:
 
<img width="1255" alt="Screenshot 2023-01-26 at 13 45 11" src="https://user-images.githubusercontent.com/2998162/214850849-720345bf-7c06-4f9e-9c97-0bde095214be.png">

Yoast promo:

<img width="1245" alt="Screenshot 2023-01-26 at 13 45 45" src="https://user-images.githubusercontent.com/2998162/214850969-4ec2f11a-ec26-400b-afd1-88bed4c3e475.png">

App promo:

<img width="1248" alt="Screenshot 2023-01-26 at 13 46 07" src="https://user-images.githubusercontent.com/2998162/214851039-1f6ba6d1-d2a6-431a-9dae-dee5eed69c81.png">

When all three cards show up, you'll see that the inconsistent font with the app promo is a bit more noticeable.

> This sounds like a nice change but in my testing, the animation fires on page load, which means we'd never see it as the promo cards on the Stats pages are always below the fold. If AnimatedIcon was updated to fire once visible, that would be neat. (@a8ck3n)

The animation will load with the component, not just on page load, so we should be all good! (You can also see an example of this in action by scrolling through the My Home set up tabs.)

**Comment by keoshi** [comment]
> When all three cards show up, you'll see that the inconsistent font with the app promo is a bit more noticeable.

Got it! Please note that there's some work happening in improving the experience of entry points for both Yoast and Boost, which would effectively remove these larger banners from the page and get rid of the `dotPager` component in the Jetpack app banner.

For more context, see this p1HpG7-jIF-p2

cc @jeffgolenski 

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/390760/214854102-43103675-614a-41ba-be45-4a6da8ec27b5.png">

<img width="889" alt="image" src="https://user-images.githubusercontent.com/390760/214854235-b48ecb5d-eb8e-4ade-9e2e-36fd517d7cdd.png">

**Comment by SiobhyB** [comment]
That's good to know, thanks @keoshi!

**Comment by a8ck3n** [comment]
> The animation will load with the component, not just on page load, so we should be all good! (You can also see an example of this in action by scrolling through the My Home set up tabs.)

I actually tested this locally and I was unable to view the animation as it had already played out. This is true if part of the `DotPager` too as all the pages are rendered up front, not just when paging. Just a heads-up though. If I'm missing something and you know how to get it so the animation will be visible, that would look great!

**Comment by SiobhyB** [comment]
Ah, apologies, I'd misunderstood the problem you were describing and was able to replicate after working on the PR. I have something up that addresses all of the areas discussed in this issue at https://github.com/Automattic/wp-calypso/pull/72560 and will go ahead to request your reviews there shortly. :) This isn't high priority, so no urgency to take a look! Thanks in advance.
