### ISSUE TITLE
Purchases: Domain cancellation: confirm button enabled before user confirmed understanding terms

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#726]
When cancelling a domain, if I select "The service isn't what I expected" / "I meant to get a free blog" / "Something not listed here" in the Confirm Cancellation screen, the Cancel Domain button is enabled right away. 

It should only be enabled once the user has checked "I understand that canceling means that I may lose this domain forever".

**Comment by gziolo** [comment]
Note: When you send one request to Cancel Domain Purchase mail is sent. When you go again to Cancel Confirmation page the following message is displayed:
`This upgrade cannot be cancelled.`

**Comment by fabianapsimoes** [comment]
> Note: When you send one request to Cancel Domain Purchase mail is sent. When you go again to Cancel Confirmation page the following message is displayed:
This upgrade cannot be cancelled.

That has been reported in #728 (:

**Comment by gziolo** [comment]
Closed with #784.
