### ISSUE TITLE
Post comment content does not break the long words in the comments

### ISSUE THREAD

**Issue by zdravkov** [Automattic/wp-calypso#7261]
#### Steps to reproduce
1. Starting at URL:https://wordpress.com/posts
2. expand comments of some post
3. type a word that is longer than the line width without adding a break - for example:
   `calypsoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo`

#### What I expected:

the word breaks to the new line
#### What happened instead:

word does not break

#### Browser / OS version

Chrome, FireFox
#### Screenshot

-![_003](https://cloud.githubusercontent.com/assets/9494406/18646577/e70572de-7eba-11e6-8819-0474f0cd5dac.png)

**Comment by lancewillett** [comment]
Thanks for the report — could you include a screenshot next time for visual context, please?

**Comment by zdravkov** [comment]
I will - thank you. I have added one for the issue.

**Comment by lancewillett** [comment]
Left a code note on the pull request.

**Comment by lancewillett** [comment]
Using `break-all` works correctly for me:

<img width="1054" alt="screen shot 2017-01-03 at 14 02 18" src="https://cloud.githubusercontent.com/assets/66797/21622979/69e9783a-d1bd-11e6-9d40-2eebdafc00dd.png">

**Comment by lancewillett** [comment]
Per notes in #10390 decided not to add this change.
