### ISSUE TITLE
Reading Settings: Add Reading —> Settings submenu item in Calypso for Jetpack sites

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#72628]
The Reading settings page link is not displayed in the Settings section in Calypso for Jetpack sites:

![Image](https://user-images.githubusercontent.com/25105483/214796618-82b9281b-6fdb-4ad5-a81e-f43e5e759a5b.png)

Since some of the settings are available in the new Reading settings page only (e.g. Featured image toggle and Full/Excerpt toggle for newsletters), I think we should expose the link for Jetpack sites as well (even though Calypso settings for Jetpack sites is generally limited when compared to Atomic or Simple sites).

**Comment by lakellie** [comment]
JPOP HE here — If this will be the only way for folks to access the featured image setting for subscriptions emails, this change is definitely necessary. The subscriptions feature is very popular with Jetpack users. I am not a developer so I could be wrong, but adding the menu item in Calypso seems to me like it would be a quicker fix than coding the feature into WP Admin for Jetpack.

**Comment by ivan-ottinger** [comment]
Thank you for your feedback, @lakellie! I totally agree. The Reading settings page will be available by accessing the direct URL so we _just_ need to add it to the sidebar menu in Calypso as well.

We will investigate what needs to be done to make that happen.

**Comment by ivan-ottinger** [comment]
It looks like the change can be made in the Jetpack side in `add_options_menu()` inside `projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php`.

It is already working on my local development environment, so I will create a PR.

**Comment by ivan-ottinger** [comment]
https://github.com/Automattic/jetpack/pull/28616 is now ready for review.
