### ISSUE TITLE
Reading Settings: Consider adding a check / handling for "Welcome email" and "Comment follow" text areas when they are empty

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#72630]
At the moment, the "Welcome email" and "Comment follow" text areas can be submitted when empty:

![Image](https://user-images.githubusercontent.com/25105483/214813379-b8dcc737-0d85-41f8-90e8-a189e87b24d5.png)

We can consider:
* preventing user from saving and displaying an error message when the fields are empty
* setting the fields to the default values when they are saved empty - this is currently the behavior of the Reading settings page in WP Admin

**Comment by JuanLucha** [comment]
We got a consensus on what approach to take on this: pdDOJh-2Om-p2

**Comment by JuanLucha** [comment]
Fixed here: D131971-code
