### ISSUE TITLE
Slideshow Block: Feature request to display images in original orientation

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#72641]
### What

A customer asked if it is possible to display images in a Slideshow Block in their original orientation instead of cropping the images to landscape orientation.

### Why

An option to display images in their original orientation would enable site owners to display their images more completely in their Slideshow Blocks where they may have a combination of portrait and landscape orientation images.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request closed

📌 Message to Author
- Hi @pauljacobson ! Thanks for advocating for our customers!  From my tests, the Slideshow block does automatically display images in their original aspect ratio - here's a quick example of a slideshow that contains landscape, square, and portrait style images:


https://user-images.githubusercontent.com/27249804/224512905-7e7c9d10-1692-4129-a2c3-4afd6da8a127.mp4
