### ISSUE TITLE
[Paid Newsletters] Count numbers in the access selector

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#72654]
IN the paid newsletter work, we have introduced the access selector:

![Zrzut ekranu 2023-01-26 o 15 01 20](https://user-images.githubusercontent.com/3775068/214877081-9f49696f-7375-4eac-8a8e-9d82454cff63.png)

We need it to show the # of people this will go out to
So it would say
- Everybody (45+)
- All subscribers (45)
- Paid Subscribers (10)

**Comment by millerf** [comment]
I'll use this one to also fix the follower's count when switching from paid-subscribers to free-subscribers.

https://user-images.githubusercontent.com/790558/221578296-7499f574-d3b6-42e5-a65e-9f86e56b5702.mov

**Comment by artpi** [comment]
> I'll use this one to also fix the follower's count when switching from paid-subscribers to free-subscribers.

YES!! I came in to suggest that

**Comment by millerf** [comment]
First part of the endpoint on WPCOM is in this PR: D103045-code

**Comment by millerf** [comment]
More discussions about possible implementation here: p1677762751666149-slack-C01B6KEJ5GE
