### ISSUE TITLE
Paid Newsletters: Intro  in the newsletter tab

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#72652]
We have an access selector in the paid newsletters:

![Zrzut ekranu 2023-01-26 o 10 59 12](https://user-images.githubusercontent.com/3775068/214874980-d60e5454-ce01-4798-a6e9-28aa0b39b7b1.png)

We need to introduce this for the users that are not familiar:

> You can restrict your post as accessible only to your e-mail subscribers or your paid supporters. The email version of this post will be delivered accordingly.
Read more about Paid Newsletters (doc link).

For the link, create a jetpack redirect (named) PCYsg-pY7-p2

**Comment by millerf** [comment]
Added redirect `paid-newsletter-info`

**Comment by millerf** [comment]
@artpi Is that too much?

<img width="393" alt="Screenshot 2023-02-17 at 17 08 19" src="https://user-images.githubusercontent.com/790558/219705343-395532c9-5343-4087-b403-f1ef55e98659.png">

**Comment by artpi** [comment]
Something to be aware of https://github.com/Automattic/jetpack/pull/29044
