### ISSUE TITLE
[Paid Newsletters] Paid Newsletters Launchpad: Stripe and Plans

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#72651]
We have something called Launchpad: PCYsg-LPB-p2

When triggered for Paid Newsletters we have to add following action items:

1. Connect Stripe Account
2. Set up a newsletter plan (with the proper flag enabled)

**Comment by artpi** [comment]
I reached out to `Cylon` team to confirm if they are the ones to ask more details:

> Check out the FG page - PCYsg-LPB-p2 - for a good rundown of info.
>In general you will need to set up the tasks on the front end and add them to the newsletter checklist.
>You may or may not need backend tracking depending on whether or not those items you linked are already represented in general calypso data. If there are already selectors that supply that info (whether or not a stripe connection was setup, or whether or not they created their first paid plan) then you may not need anything. However, for some tasks we need to set up some backend tracking (tie it to a wp action hook to mark the task as complete) - and if thats the case we need to do that on both wpcom backend as well as wpcomsh currently.
> [13:26](p1677587196531279-slack-D0141BFEYF2)
If you have any other questions or need a hand when implementing and running into blockers, feel free to reach out in [#cylon] as well - I know a handful of the teammates should be super helpful as well :grin:

**Comment by n3f** [comment]
I also asked a couple general development questions directly to @jeyip and he responded in p1677289175138999-slack-CHN6J22MP.

It might be worthwhile putting them in a p2 for gold...
