### ISSUE TITLE
[Earn] Confetti on the thank you screen

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#72658]
Thank you screen in the Earn checkout desperately needs confetti

Prior art: pbuuvu-1kq-p2#comment-2968

**Comment by millerf** [comment]
@artpi  Is there a component for it? Should we create one? Which one should we use?

**Comment by millerf** [comment]
Found-em https://github.com/Automattic/wp-calypso//blob/trunk/packages/components/src/confetti/index.ts#L0-L1

**Comment by millerf** [comment]
Calypso cannot be used. We can go with https://www.cssscript.com/confetti-falling-animation/ or something similar in vanilla-JS

**Comment by artpi** [comment]
There is a thread linked in the description. What do they use?

**Comment by millerf** [comment]
> There is a thread linked in the description. What do they use?
Asking...

**Comment by artpi** [comment]
Ok, I got more information. We should be using this: p9Jlb4-6dJ-p2

In case this is what Fab is referring to https://github.com/Automattic/wp-calypso/issues/72658#issuecomment-1412291283 here, we probably have to build a package out of this confetti to be usable on the frontend (the code lives in the packages
 directory already)

I don't know if this is the lowest hanging fruit right now

**Comment by millerf** [comment]
> Asking...

I also followed up with Tumblr and they used a fully in-house one. The good part is that it is [available here](https://github.tumblr.net/Tumblr/redpop/tree/production/src/components/after-post).

**Comment by romarioraffington** [comment]
Hey @millerf  added some feedback to D101723-code
