### ISSUE TITLE
Signup: "Loading" message in tooltip at /start/domains

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#7265]
There's an indefinite "loading" message that can be found in the tooltip at /start/domains.

#### Steps to reproduce
1. While logged out of WordPress.com, start at: https://wordpress.com/start/
2. Navigate through each of the steps in the signup process until you reach the domain step: https://wordpress.com/start/domains/
3. Hover over "Included in WordPress.com Premium" in order to view more details about the plan.

#### What I expected

After hovering over "Included in WordPress.com Premium," I expected for a tooltip that contained more information about the plan to appear.

#### What happened instead

A tooltip does appear with a list of features included in WordPress.com Premium, however, there's a indefinite "loading" message just beneath the title.

You can find the code for this under **/client/components/plans/premium-popover/index.jsx** here:

https://github.com/Automattic/wp-calypso/blob/master/client/components/plans/premium-popover/index.jsx#L104

#### Browser / OS version

Tested in Chrome 52 and Firefox 48 on OS X El Capitan 10.11.5.

#### Screenshot / Video

<img width="1106" alt="screen shot 2016-08-03 at 23 49 02" src="https://cloud.githubusercontent.com/assets/2998162/17384579/0541800e-59d5-11e6-8866-ff77b84bc737.png">

#### Context / Source

#dogfooding #manual-testing

**Comment by bisko** [comment]
This bug has been fixed by a change we made to the domains screen in Signup in #7233. The example screen has been updated and the problematic popup has been completely removed.
