### ISSUE TITLE
Stats: Restyle the earnings history table in the Ads page

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#72676]
# Development

Please reuse the work done for [Annual highlight table](https://github.com/Automattic/wp-calypso/issues/70608) and #71761.

# Design
|Before|After|
|-|-|
|![Image](https://user-images.githubusercontent.com/4044428/214949132-9487a74e-9e57-48d4-87eb-c10f3de6fdd1.png)|![Image](https://user-images.githubusercontent.com/4044428/214949259-e4bcac5d-29bd-48cb-8d0e-a975d3cb1f2d.png)|

**Comment by jsnmoon** [comment]
@a8ck3n, what's the progress on this task?

**Comment by a8ck3n** [comment]
Thanks for jumping on this one, @jsnmoon! I was planning to revisit this once I finished up the legacy stats notice but got sidetracked with a couple of follow-up PRs.

**Comment by jsnmoon** [comment]
Happy to help! ✋
