### ISSUE TITLE
Editor: Code shortcode content not wrapped, outside of highlight box

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#7268]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Add the following sample in the HTML tab:

```
[code language="html"]
<div ng-repeat="entity in selector">
<label>
<input type="checkbox" ng-model="entity.val" ng-change="updateModel(entity)"></input>
<span ng-bind="entity.value"></span>
</label>
</div>
[/code]
```

3. Edit post from Visual tab, noting code block appearance.

#### What I expected

Code to be wrapped to fit without a scrollbar and within the box, as with WP Admin:

<img width="618" alt="screen shot 2016-08-03 at 9 36 26 pm" src="https://cloud.githubusercontent.com/assets/1900444/17387493/5e90d60e-59c2-11e6-861c-cc07bd8105c4.png">

#### What happened instead

The code is not wrapped to a new line, appearing outside of the highlight box and with a scrollbar

Default view: 
<img width="736" alt="screen shot 2016-08-03 at 9 34 17 pm" src="https://cloud.githubusercontent.com/assets/1900444/17387495/6541de30-59c2-11e6-8b0a-7ebb9d09345d.png">

Scrolled right:
<img width="752" alt="screen shot 2016-08-03 at 9 34 21 pm" src="https://cloud.githubusercontent.com/assets/1900444/17387499/6f1aa072-59c2-11e6-81f7-1aa54db3d386.png">

#### Browser / OS version

Chrome 51/OS X 10.11.6
#### Screenshot / Video

See above.

#### Context / Source

Found in testing #1426

#manual-testing

**Comment by lancewillett** [comment]
@kriskarkoski Would you say this is a personal niggle (you don't like how it works) or a bug that affects the actual content and published code snippet (as in, it visually isn't readable)?

**Comment by kriskarkoski** [comment]
Personally I think it should wrap to have parity with how it's handled in WP Admin, but if there haven't been any further complaints on it I'm happy to close for now and revisit if users bring it up.
