### ISSUE TITLE
Simple Sites: Site Editor will not save any changes to templates or template parts, multiple themes

### ISSUE THREAD

**Issue by TeniCola** [Automattic/wp-calypso#72684]
### Quick summary

I have a user with an FSE site that is refusing to save any changes to their Index template. No matter what I and the user do to confirm this change, it will not save at all -- not in the footer, or even in the main index content. It _looks_ like it confirms saving, but once the browser refreshes, the change is removed from the editor and live site

Trying other blocks will not yield a saved change, either. I can replicate this repeatedly and consistently on their website, and both I and another HE could replicate this on our test sites using the Winkel theme, but not with any others thus far.

### Steps to reproduce

1. Open the Site editor (Appearance > Editor [Beta]), and navigate to any template and Edit (Index, Home, etc)
2. Make any changes to the main content or to a template part (Header, Footer, etc.), such as adding a Paragraph block, etc. The change can be small, or multi-step.
3. Click on the "Save" button, and confirm the changes, then wait until the editor confirms the saved changes were applied.
4. Refresh the browser, and/or view the live site.

### What you expected to happen

For the change to apply to the website with the given template after saving; and for the changes to appear in the editor view for a given template after a refresh.

### What actually happened

The "saved" changes are undone, and cannot be found in either the editor or the live site -- as if nothing was changed at all.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- While this issue is only affecting one user, I and another HE can replicate this consistently so far for Winkel
- I have tried multiple templates, multiple areas of the content, and multiple blocks, and the issue still persists.
- This has only been tested on simple sites so far, both on a paid plan (Premium) and the free plan.
- The issue makes FSE unusable with Winkel for this user, but I can advise them to switch to another theme in the meantime.
- More details + a clear video of what happens on the user's site can be found in the notes for **5900185-zen**, but the results should be replicable by following the above steps.

**Comment by kerrynicl** [comment]
also affecting user in 5900540-zen . Theme - Zoologist

**Comment by tvolpert** [comment]
another report here: 5903568-zen . This site is also using the Winkel theme.

**Comment by rinazrina** [comment]
Another report in #5907528-zen when using Farrow theme.

**Comment by brittanygray902** [comment]
Another report here: 40188788-hc Appleton theme

**Comment by sanjeev00733** [comment]
Another report 5913255-zen Winkel theme

**Comment by zachspears** [comment]
Got another report here: 5916720-zd-woothemes - Astra theme.

**Comment by marutim** [comment]
Another report here: 5921201-zd-woothemes - Antonia theme

I have let the user know that we will follow up with them after the issue is fixed

**Comment by cuemarie** [comment]
Reported cases from https://github.com/Automattic/wp-calypso/issues/72128 (Farrow): 

- [ ] 5884480-zen Theme: Hari
- [ ] 5866181-zen Theme: Russell

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: Could Not Replicate
- Tested on Self-hosted: Could Not Replicate
- Replicable on Core? No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated this issue on **Simple test site** with the following themes: 
     - Farrow
     - Russell
     - Winkel
     - Twenty Twenty-Two (Red)

- **Could Not Replicate** on the same **Simple test site** with these themes:
     - Twenty Twenty Two 
     - Zoologist

Note: Content added through the site editor _inside the post content block_ did save, however content added directly onto templates was erased with a refresh, and nothing changed on the live site

**Examples**

Farrow: 

https://user-images.githubusercontent.com/27249804/216404082-76511e90-6976-40aa-96ae-8c8187001b36.mov

Winkel:

https://user-images.githubusercontent.com/27249804/216408352-e4b2b267-4605-44a2-a78c-ed27102b1c15.mov

TT2 (Red):

https://user-images.githubusercontent.com/27249804/216410363-38e9eae6-6f98-4741-9802-be12cf5ad754.mov

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Escalated here: p1675362082429099-slack-C02FMH4G8

**Comment by cuemarie** [comment]
Reports from https://github.com/Automattic/wp-calypso/issues/72118 : 

[ ] - 5862994-zen - TT2 Red, TT2 Swiss
[ ] - 5896680-zd-woothemes - TT2 Mint

**Comment by cuemarie** [comment]
Reports from https://github.com/Automattic/wp-calypso/issues/72172 : 

[ ] - 39556765-hc / 5867872-zd-woothemes - Byrne, Payton
[ ] - `5861761-zen` - Blank Canvas Blocks
[ ] - 5908143-zen - Appleton
[ ] - 5908955-zd-woothemes - Kerr

**Comment by cuemarie** [comment]
Report from #72389 : 

[ ] - 39602678-hc - Attar

**Comment by cuemarie** [comment]
From https://github.com/Automattic/wp-calypso/issues/72825 : 

[ ] - 5909135-zen - Alonso

**Comment by NoHopeRadio** [comment]
I'm pretty sure that what's happening is a missing relationship to the Blockbase parent theme somehow. Maybe a permissions setting? This user can edit Template parts and certain Templates made by the Zoologist theme, but the ones made by the Blockbase theme will not hold changes:

![image](https://user-images.githubusercontent.com/71042895/216457614-d6b0ffd4-8ae0-4a5f-a22e-f774ae96045a.png)

We were trying to edit these pages, especially the Search page, and when we switched to the Blockbase theme, we finally saw where our edits went:

![image](https://user-images.githubusercontent.com/71042895/216458623-2a9f5115-ed17-42a1-a815-c0f756d7a7ec.png)

40296946-hc

**Comment by jordesign** [comment]
Another example in 40301933-hc

**Comment by mreishus** [comment]
Potential fix in the works: D100261-code

**Comment by supernovia** [comment]
Another case: https://wordpress.com/forums/topic/changes-are-not-saving/

**Comment by helenaartmann** [comment]
Another case - [5916759](5916759-zd-woothemes) - Zen

**Comment by cuemarie** [comment]
D100261-code has been deployed to fix this issue! 🎉

**Comment by mreishus** [comment]
Reported upstream in https://core.trac.wordpress.org/ticket/57630

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
