### ISSUE TITLE
WooExpress Trial: New api endpoint to add site options

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#72716]
Profiler data is going to be passed to `/setup/wooexpress`. Once the site is created and transferred to atomic, we'll need to call a new endpoint which takes this data and sets the appropriate site options.

The endpoint should take a JSON POST request with data like the following:
```
{
  "site_id": 1234,
  "persona": "im_already_selling_online",
  "platforms": [
    "shopify"
  ],
  "store_name": "Beautifully Handmade",
  "industry": "clothing_and_accessories",
  "store_location": "us"
}
```

The endpoint should verify that the site belongs to the current user and that it's already Atomic. We also need to verify the WooCommerce referral header as described in pdibGW-1pT-p2#comment-1088.

Discussion: pdibGW-1jA-p2#comment-1029

**Comment by ilyasfoo** [comment]
Hi @markbiek @daledupreez, the data passed has been updated to directly map to options (discussion: pdibGW-1pT-p2#comment-1084). This [PR](https://github.com/Automattic/woocommerce.com/pull/16136) is the work in-flight on NUX's side.

```json
{
  "blogname": "<store name>",
  "woocommerce_default_country": "<country_code>",
  "woocommerce_onboarding_profile": {
    "is_store_country_set": 1,
    "industry": [
      {
        "slug": "fashion-apparel-accessories",
        "detail": "Clothing And Accessories"
      }
    ],
    "selling_venues": "other",
    "other_platform": "amazon"
  }
}
```

**Comment by ilyasfoo** [comment]
Also, do we have a rough estimate as to when this will be worked on? From our demo call with design team recently, we found out that it's a blocker for skipping the first task `Add store details` by pre-populating store country and marking the task as completed. Not a blocker for launch, but it does have a minimal UX impact.

cc @verofasulo @FlorianBru

**Comment by daledupreez** [comment]
@ilyasfoo, if this is blocking you, we can start on it this week, probably today or tomorrow. Let us know if that works.

**Comment by ilyasfoo** [comment]
Hi @daledupreez, that sounds great, thank you! 🙏

**Comment by daledupreez** [comment]
I am working on the back end for this in D104056-code.

**Comment by daledupreez** [comment]
The internal API has now been deployed; we just need to add handling in the Calypso pages -- that's being tracked in https://github.com/Automattic/wp-calypso/issues/72718.
