### ISSUE TITLE
WooExpress: New step to process profile data

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#72718]
Once #72716 is complete, we'll need to add a new final step which takes the decoded profile data (as described in #72717) and POSTs it to the new api endpoint created in #72716.

The step should come after we're done waiting for the Atomic transfer to complete.

This step should be configured similarly to the `siteCreateStep`. It'll be effectively invisible for most people but should still have some basic styles and a progress indicator for people with slower connections.

Once the request is complete, we redirect the user to the dashboard.

**Comment by daledupreez** [comment]
The eventual implementation from https://github.com/Automattic/wp-calypso/issues/72716 means that we won't need another step, but we will need to add the data to the payload we send when adding the free trial to the site.

**Comment by markbiek** [comment]
> The eventual implementation from #72716 means that we won't need another step, but we will need to add the data to the payload we send when adding the free trial to the site.

Correct! My plan was to store the payload (if any) when we enter the flow, the retrieve it to pass to the trial endpoint.
