### ISSUE TITLE
Form block submission shows "array ()" code in Feedback dashboard

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#72713]
### Quick summary

Form submission that contains multiple choices shows `array ()` code on the Feedback page on WP Admin. 

### Steps to reproduce

1. Create a Form block (Jetpack) on a page or post
2. Add multiple choices
3. Publish the page or post
4. Send a test submission on the form and select a few choices under the multiple choices
5. Once sent, check Feedback section on dashboard, it will show `Array ()` under the multiple choices data. 

### What you expected to happen

The form submission data under Feedback contains plain string and no such odd code. 

### What actually happened

The form submission data shows `Array ()` code which makes the data doesn't look neat. 

**Screenshot of the form submission under Feedback:** 

<img width="1419" alt="Markup 2023-01-27 at 20 00 54" src="https://user-images.githubusercontent.com/33721365/215081630-dd8e752b-9372-4772-8c31-c0faf95da5c2.png">

### Additional details: 

**Screenshot of the Form block:** 
<img width="873" alt="Screenshot on 2023-01-27 at 20-02-22" src="https://user-images.githubusercontent.com/33721365/215082145-8254fb46-5fad-4de7-a80b-2cdb187035d4.png">

**It looks OK on the email though. Screenshot:** 
<img width="541" alt="Markup 2023-01-27 at 20 03 16" src="https://user-images.githubusercontent.com/33721365/215082335-736dd02a-a06f-4fff-abfb-67e609a7ce08.png">

### Impact

Some (< 50%)

### Available workarounds?

Yes. User can view the form submission via email instead of via Feedback dashboard. 

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Reproduced on Blank Canvas, Archeo, and Radiate. 
Tested using Chrome browser. 

User report: 39709102-hc
Follow up: #5902513-zen

**Comment by samiff** [comment]
Hi 👋  The display of the forms data is being handled by Jetpack. I'll close this issue in favor of a similar issue I found here: https://github.com/Automattic/jetpack/issues/28345
