### ISSUE TITLE
WooExpress Trial: Store incoming profile data to the store

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#72717]
When the user enters the WooExpress flow, there will be a new base64-encoded GET parameter containing the profile information.

`https://wordpress.com/setup/wooexpress?profilerdata=ewogICJwZXJzb25hIjogImltX2FscmVhZHlfc2VsbGluZ19vbmxpbmUiLAogICJwbGF0Zm9ybXMiOiBbCiAgICAic2hvcGlmeSIKICBdLAogICJzdG9yZV9uYW1lIjogIkJlYXV0aWZ1bGx5IEhhbmRtYWRlIiwKICAiaW5kdXN0cnkiOiAiY2xvdGhpbmdfYW5kX2FjY2Vzc29yaWVzIiwKICAic3RvcmVfbG9jYXRpb24iOiAidXMiCn0=`

The decoded `profilerdata` will look something like this:
```
stdClass Object
(
    [persona] => im_already_selling_online
    [platforms] => Array
        (
            [0] => shopify
        )

    [store_name] => Beautifully Handmade
    [industry] => clothing_and_accessories
    [store_location] => us
)
```

In the initial `siteCreationStep`, we want to decode and store this information (most likely to the site data store) so it can be used to set the site options in a later step after the Atomic transfer.

**Comment by chihsuan** [comment]
Hey @markbiek, Just wanted to mention it here. To support Unicode inputs, we encode the profile data using `encodeURIComponent` in https://github.com/Automattic/woocommerce.com/pull/16289 as below:

```js
window.btoa(
    unescape( encodeURIComponent( JSON.stringify( profilerData ) ) )
);
``` 

I believe you can decode it using the following code in Calypso:

```js
// from ChatGPT
var profilerData = JSON.parse(decodeURIComponent(escape(window.atob(encodedString))));
```

Let me know if you have any questions. Thank you! 😄

**Comment by markbiek** [comment]
@chihsuan Thanks for the details!
