### ISSUE TITLE
Reading Settings: Adjust bottom margin for all setting titles

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#72721]
Initially @saygunnyc has reported that the bottom margin on the **Related posts** setting title seems to be less than of the other settings on the page.
Once inspected it looks like the bottom margin varies for many of the settings. It would be nice to have it justify for all. 

![Image](https://user-images.githubusercontent.com/2019970/215099632-7871d6ca-ba6c-47f0-b617-b4c994347786.png)

**Comment by saygunnyc** [comment]
> It would be nice to have it justify for all.

❤️ 

I've been using 12 px, we can try to default to that. 

<img width="813" alt="Screenshot 2023-01-27 at 10 23 34 AM" src="https://user-images.githubusercontent.com/78876323/215122807-02b619f2-ffd8-4775-8466-a10d30e1c90a.png">

**Comment by TimBroddin** [comment]
Rebase & merge
