### ISSUE TITLE
Show domain upsell on /plans page if the user has a domain on its cart

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#72722]
Slack thread: p1674750705989769-slack-C03TDMUSUSG

We want to show the new domain upsell on `/plans` page every time the user has a domain on its cart

![Image](https://user-images.githubusercontent.com/1044309/215098756-06b55c01-ccb8-4eea-bf4c-4476643c7a47.png)

**Comment by allilevine** [comment]
@paulopmt1 Do you still see value in working on this as a future project?

**Comment by paulopmt1** [comment]
Since it seems [we don't have that upsell anymore](https://github.com/Automattic/wp-calypso/pull/72532/files), I don't see value in bringing it back. Closing it.
