### ISSUE TITLE
Reading Settings: Place the Related posts setting's info icon beside the setting's title

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#72720]
![Image](https://user-images.githubusercontent.com/2019970/215098428-c09d4949-5c7a-43bc-8295-62a99eb0dfe5.png)

**Comment by ivan-ottinger** [comment]
The Related Posts settings are displayed differently in **two places** in Calypso:

A) `settings/reading`

https://github.com/Automattic/wp-calypso/assets/25105483/750b9412-5450-4bd4-ac37-2e2fe27a0554

B) `marketing/traffic`

https://github.com/Automattic/wp-calypso/assets/25105483/df71b1da-04f2-4d77-8c1a-da822143844c 

Each page is relying on the `<RelatedPostsSetting>` component that has the `<SupportInfo>` component (that represents the ℹ icon) in it.

Here is what I suggest we could do:

1.) Move the `<SupportInfo>` component out of the `<RelatedPostsSetting>` component. This would allow us to properly align the ℹ icon with the "Related Posts" heading:

![Markup on 2024-01-23 at 15:23:46](https://github.com/Automattic/wp-calypso/assets/25105483/27c33cc4-fbfb-4cb9-8371-b40ea9a97e68)

2.) Remove the `<RelatedPostsSetting>` component from `marketing/traffic` settings page completely. This would reduce confusion of why the same setting is in two places in Calypso. It would also align with the settings location referred in the user-facing documentation (https://wordpress.com/support/related-posts/).

To me it feels quite odd to be looking for Related Posts settings in _Tools → Marketing → Traffic_. Having them in _Settings → Reading_ makes much more sense to me.

Also, having the Related Posts settings in _Tools → Marketing → Traffic_ is a leftover from the times when we didn't have the _Settings → Reading_ page available in Calypso.

This approach would also simplify placing `<SupportInfo>` component out of the `<RelatedPostsSetting>` component - as we wouldn't have to duplicate it in two different places (or do some other workarounds).

If agreed, we could even consider displaying a short banner with a button in the _Tools → Marketing → Traffic_ page saying something like: "Looking for the Related Posts settings? We have moved them to the Reading settings".

What do you think, @Automattic/apex?

**Comment by phcp** [comment]
Nice findings @ivan-ottinger, thanks for sharing! I think option 2 makes more sense, as it's a leftover from before Reading Settings. I like the idea of adding a banner on the _Tools → Marketing → Traffic_, so anyone still used to update this setting on this page will know the right place to do it.

**Comment by ivan-ottinger** [comment]
Thank you for your feedback, Paulo! 🙂

**Comment by ivan-ottinger** [comment]
Updated Happiness on the change in p1706539358481569-slack-CB0B2G43X.
