### ISSUE TITLE
Odyssey Stats: Add a customer feedback survey to be used when a customer opts out

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#72738]
![Image](https://user-images.githubusercontent.com/4044428/215221504-92c19755-1b9a-4728-9cc2-03d745408bab.png)

There are multiple open questions on how we might go about implementing this. Note that the questions for the survey have not been finalized. See p1HpG7-khi-p2#comment-60247.

**Comment by jeffgolenski** [comment]
I posted the surveys to the p2 and just absorbing some feedback. The should be complete within a couple of days!

**Comment by jsnmoon** [comment]
I believe this is complete!

**Comment by jeffgolenski** [comment]
@jsnmoon Unless we're get any other feedback, I think we're good to ship. The nice thing about hosting the surveys on CS is that we can update at any time!

**Comment by jsnmoon** [comment]
Sounds good, @jeffgolenski!
