### ISSUE TITLE
Update Blaze logo

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#72732]
We already have a new Blaze logo at `https://wordpress.com/calypso/images/illustration--blaze-ff6cf83b4d50076dea2e.svg`. We expect to use this same logo in all places it's applied.

- [ ] Update Blaze Logo at /marketing/traffic:

![Image](https://user-images.githubusercontent.com/1044309/215149533-d8d26ad6-d887-4719-a0f7-bd0f64df7596.png)

**Comment by allilevine** [comment]
PR: https://github.com/Automattic/wp-calypso/pull/72749

**Comment by paulopmt1** [comment]
[Fixed here](https://github.com/Automattic/wp-calypso/pull/74376).
