### ISSUE TITLE
[Bug]: Site Title Block - Global Link Styles are applied to Site Title

### ISSUE THREAD

**Issue by ha-un** [Automattic/wp-calypso#72743]
### Quick summary

When link styles are applied in the Site Editor → Global Styles → Typography → Links, the changes apply to the Site Title block.

### Steps to reproduce

1. Activate an FSE theme (tested on Masu & Twenty Twenty Three)
2. Apply a style to the Site Title block in the editor (such as font weight, size, etc.)
3. Click on the Global Styles icon and make different changes for Typography → Links

### What you expected to happen

The links on the site should have the styles applied, and the Site Title should keep the styles that were set.

### What actually happened

The Site Title block gets the link styles applied.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

You can reset the "Link" styles to get the Site Title styles to show up again.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Replicated**
- Replicable on Core? **Yes** 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated in all test environments. Tested `Appearance` and `Font Size`

**Self-Hosted Example**

https://user-images.githubusercontent.com/27249804/224519930-346f7d29-c937-4e0d-8048-e5e1e5a7a042.mov

---

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 NOTES
- I've seen a few reports of Global Styles overriding block-specific settings, both here and in `/gutenberg`; wondering if this larger discussion is relevant: https://github.com/WordPress/gutenberg/issues/45086

**Comment by dsas** [comment]
@cuemarie, that's right. This issue might explain a bit more directly: https://github.com/WordPress/gutenberg/issues/44931
 
Basically GB is working as intended, but has a confusing UX. I'm going to close this as not specifically related to Dotcom.

Thank you for testing and reporting @ha-un  🙇‍♂️

**Comment by dsas** [comment]
Thought about this some more on this [duplicate issue](https://github.com/Automattic/wp-calypso/issues/64596#issuecomment-1487607467).
