### ISSUE TITLE
Drafts: The drafts list displays when other users have drafts.

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#7275]
#### Steps to reproduce
URL: wordpress.com/posts

#### What I expected
I'm not sure if the drafts column should display when its empty. It "eats up" valuable space when empty:

![screen shot 2016-08-04 at 12 38 51 pm](https://cloud.githubusercontent.com/assets/191598/17410298/07ce0088-5a41-11e6-8b6a-99aacd8c574a.png)

#### What happened instead
I think we actually hide this when empty, but the screenshot above was taken on a site with multiple users — some of whom had drafts. Even though I don't have any drafts, the column is perhaps being shown based on the fact that others do?

@mtias (I think you were working on this?)

**Comment by shaunandrews** [comment]
Ah, I just found #7222 which seems to be related.

**Comment by lancewillett** [comment]
From my testing this is working as expected. Feel free to re-open if you still see bugs.
