### ISSUE TITLE
Reading Settings: Replace "Reading" submenu item title with Calypso translation

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#72750]
It is a follow up task on https://github.com/Automattic/wp-calypso/issues/72628
It is a temporary fix for no translations in Jetpack. 

Related conversation: https://github.com/Automattic/jetpack/pull/28616#pullrequestreview-1272725427

**Comment by ivan-ottinger** [comment]
All [Mag-16 translations are already in with the newest Jetpack release](https://github.com/Automattic/wp-calypso/pull/73057#issuecomment-1422315713) - hence the fix is not necessary at the end.
