### ISSUE TITLE
Make sure Migration offers a monthly plan option to purchase

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#72758]

**Comment by bogiii** [comment]
Why don't we see the Monthly option anymore?

The answers are here:
- Pricing and packaging: pdgrnI-1Mu-p2
- https://github.com/Automattic/wp-calypso/pull/69643
- https://github.com/Automattic/wp-calypso/issues/69633

I tried to find a workaround, but without success.

cc @ouikhuan @vishnugopal

**Comment by ouikhuan** [comment]
So looks like we did this on purpose, should we reach out to Bumblebee to check?

**Comment by vishnugopal** [comment]
Let's ask in bOQVh-p2, that should be the best place to ask as that is the team of the folks who did those PRs.

**Comment by bogiii** [comment]
Asked here: pbOQVh-323-p2

**Comment by bogiii** [comment]
Based on the comment pbOQVh-323-p2#comment-3652, we will keep the Yearly plan, collect the data, and test the result.

We’ll examine funnels and perhaps convert them to monthly at a future point in time.

**Comment by bogiii** [comment]
The funnel with the name `Migration Plugin: Plugin → Migration flow → Plan upgrade → Import start → Import Success` has been created.

cc @vishnugopal

**Comment by bogiii** [comment]
Follow up ticket: https://github.com/Automattic/dotcom-forge/issues/1698
