### ISSUE TITLE
[WooExpress] Task: Ensure users on the free trial can install proposed payment gateways

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#72768]
### Details

As I found during a walkthrough last week (peapX7-1yF-p2), it is not possible for users on the free trial to pick a proposed payment gateway. We need to fix this so that users can access the page and install any of the proposed payment gateways.

### Checklist

- [ ] Users on the free trial can access the payment gateway selection screen
- [ ] Users on the free trial can install a proposed payment gateway

**Comment by daledupreez** [comment]
For reference, I did some digging into this and I think we can use a very similar approach to the one we use for installing marketplace plugins, which is implemented here: fbhepr%2Skers%2Sjcpbzfu%2Ssrngher%2Qcyhtvaf%2Subbxf.cuc%3Se%3Q68p18r03%2360-og

The basic idea is that we check for the `INSTALL_PURCHASED_PLUGINS` permission when the incoming request is for a specific path. I think we can start by updating the hook to do the same for the suggested payment gateways path, and then (hopefully) add a similar condition for the API used to install the suggested payment gateway. That may or may not be possible, depending on how the code makes the request to the server.

**Comment by sixhours** [comment]
WP.com side patch started at D100771-code
