### ISSUE TITLE
Plans Grid 2023: "my-plan" and "plans" tab switch feels a bit abrupt on desktop

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#72775]
## Description

Switching between the "my-plan" and "plans" tabs in Calypso may feel a bit abrupt with a hard width change in larger viewports. 

### Media

https://user-images.githubusercontent.com/1705499/215507423-56149f8e-ebc2-412d-a6ae-89c77b73fdab.mov

## Reproduce

1. Activate the `onboarding/2023-pricing-grid` feature flag
2. Navigate to `/plans` in Calypso with a site on a paid plan `http://calypso.localhost:3000/plans/[foopaidplan.com]`
3. Switch to full screen and click between "my-plan" and "plans"

cc @lucasmendes-design

**Comment by lucasmendes-design** [comment]
Do you think it's possible to add the new tab navigation? 

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/98343583/215749208-2c370915-cbaa-42a2-8713-8b0208c484bb.png">

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/98343583/215749249-f8f0cefa-319a-4526-ab24-b818a09bb33e.png">

**Comment by claudiucelfilip** [comment]
> Do you think it's possible to add the new tab navigation?

@lucasmendes-design I don't think we'll be able to fit in before launch. My suggestion is to keep the old header for now and follow up with the reskin.

<img width="1024" alt="Screenshot 2023-02-03 at 17 04 06" src="https://user-images.githubusercontent.com/2749938/216636886-bea05a0c-bcdf-4a25-87e5-8083df6bad21.png">

**Comment by ddc22** [comment]
@chriskmnds Please do add tasks to the milestone if you are picking it up in this sprint :) 
https://github.com/Automattic/martech/milestone/20
