### ISSUE TITLE
Requeue unsent emails

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#72778]
The merge of paid newsletters branch has turned off sending emails to users for 3 days (Friday-Monday) until the merge of D99656-code .

See more in 

## Scope of this task

1. Determine exact times
2. Determine if the status of a post sent to a user is stored somewhere
3. If it is and there are protections against double-sending, we can just resend all emails in the window. We need to batch it some way.
4. If it is not stored, we have to somehow find a list and write a script that will resend those particular emails

The emails are probably all purely-email users for posts published within the window of the outage

**Comment by artpi** [comment]
So we need from the the merge until this revert D99642-code

**Comment by artpi** [comment]
I think we can leverage some of the code from `get_for_period`

**Comment by artpi** [comment]
We can just directly pass the subscribers list in batches to `bsub_email_child_send_post_to_subscribers` after it has been repaired

**Comment by artpi** [comment]
I think the first start of this may be a good SQL query to see how many subscribers are affected

**Comment by romarioraffington** [comment]
> I think the first start of this may be a good SQL query to see how many subscribers are affected

Created a query in D99746-code  to determine the number of users affected but it's taking some time to run on the sandbox

**Comment by artpi** [comment]
More discussion in p58i-dTr-p2

**Comment by artpi** [comment]
Lets draft a diff that assumes we have a list of blogs ids to resend.

Discussion is still ongoing, but I feel like we will just resend all email to users that didn't get it.

The list of blogs will be around 100K and we can try to trigger some kind of job for each one

**Comment by pauljacobson** [comment]
@artpi We received a request from a user in 5911702-zen that we not send out email notifications retrospectively. Would it be possible for users to opt-out of this?

**Comment by pauljacobson** [comment]
Our user in 5906190-zen has also asked that we include an explanatory note to the affected subscribers explaining what happened to the notifications.

**Comment by artpi** [comment]
> has also asked that we include an explanatory note to the affected subscribers explaining what happened to the notifications.

No, that is not possible with our resources. I am, unfortunately leaning towards not sending the emails again at all.
After almost a week, this seems pointless.

**Comment by romarioraffington** [comment]
A script has been created to resend all the affected posts to email subscribers for a specified blog.  The script is blog specific and only accepts a single blog ID. [We want to retrigger these emails based on user requests.](p1675441468795609/1675390607.611209-slack-C01B6KEJ5GE)

Patch: D100396-code

**Comment by gaurav1984** [comment]
5908738-zen

User [dupguy](https://wordpress.com/wp-admin/network/users.php?s=dupguy) would like to have the missed emails resent for [https://dupuisg.ca/](https://href.li/?https://dupuisg.ca/) (57605313) – Looks like it’s just 1 post and 43 followers.

They only have one post which was affected by this issue, the published the post on Jan 29th.

**Comment by freelylovinglife** [comment]
Checking in to see if these emails were already resent to followers or when they will be resent?  The following user has contacted us again to confirm. 5906190 ZD.

**Comment by romarioraffington** [comment]
@artpi, how should we approach resending emails since we have deployed the script to resent the emails by blog ID? Should I go ahead and resent these emails?

**Comment by artpi** [comment]
> how should we approach resending emails since we have deployed the script to resent the emails by blog ID? Should I go ahead and resent these emails?

Since we are all travelling, yes - please resend them whenever you get a chance

**Comment by simison** [comment]
Can this be closed already?

**Comment by artpi** [comment]
Definitely yes. even if they weren't resent, its too late
