### ISSUE TITLE
[WooExpress] Task: Ensure users can upgrade to the eCommerce plan

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#72772]
### Details

We need to ensure that our internal plan upgrade and downgrade checks correctly handle upgrades from the free trial to the eCommerce plan. This will likely require upgrade paths being specified in this code: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Sohaqyr%2Qhcfryy.cuc%3Se%3Q3p49n648%2394-og

**Comment by sixhours** [comment]
It looks like this will also involve updating some Calypso selectors to ensure we're getting the correct values; the ecommerce plan is currently treated like a paid plan, so selectors like `isCurrentPlanPaid` or `canUpgradeToPlan` are failing.

**Comment by sixhours** [comment]
Aha, even better, we just need to add the ecommerce trial upgrade paths to the front-end equivalent of the above code, `plans-list.tsx`

**Comment by sixhours** [comment]
D99678-code for the backend.

**Comment by sixhours** [comment]
D99678-code has landed!

**Comment by sixhours** [comment]
I think this has been taken care of with the above changes. @daledupreez Is there anything else we need to check/do for upgrade paths? Downgrade paths don't really come into play since a user can't downgrade to anything but free, AFAIK.

**Comment by daledupreez** [comment]
The final piece here is wiring in the buttons that allow users to trigger the upgrade from the new Plans page specific to the eCommerce trial. I have that in #73216.
