### ISSUE TITLE
Update Queen to King in domain checkout options

### ISSUE THREAD

**Issue by stephhjacq** [Automattic/wp-calypso#72784]
### Quick summary

When purchasing a new domain as a Canadian, the selection for 'Canadian Presence' lists Her Majesty the Queen as an option. This should be updated to His Majesty the King (if it's even necessary, is he likely to purchase a domain? I'm guessing this requirement is coming from the registrar)

### Steps to reproduce

Purchase a domain with TLD .ca
Proceed to checkout
Open dropdown to select your presence in Canada

### What you expected to happen

List includes His Majesty the King

### What actually happened

List includes Her Majesty the Queen
<img width="933" alt="Screenshot 2023-01-29 at 10 00 24 AM" src="https://user-images.githubusercontent.com/29288537/215555311-dd0ab3a1-e2b0-4b5c-84a7-8bb3cc1d24de.png">

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by tyxla** [comment]
This is addressed by #73024 - thanks @jartes!

**Comment by DavidRothstein** [comment]
Moving this out of the Shilling team inbox since it's more an issue for @Automattic/nomado (and has a fix in progress anyway).
