### ISSUE TITLE
[Paid Newsletters] properly fix email sender

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#72780]
We had a problem with the email system. Upon merging Jetpack, following code was triggered:

```
if ( ! empty( $subscriber_id ) && $subscriber_id > 0 && class_exists( WPCOM_Offline_Subscription_Service::class ) && method_exists( WPCOM_Offline_Subscription_Service::class, 'subscriber_can_receive_post_by_mail' ) ) {
	$subscription_service = new WPCOM_Offline_Subscription_Service();
	if ( ! $subscription_service->subscriber_can_receive_post_by_mail( $subscriber_id, $post_id ) ) {
		continue;
	}
}
```

The problem was that `subscriber_can_receive_post_by_mail` started returning false for users that are **email-only** subscribers and sending an email was skipped for them.

In D99656-code I have commented out the piece of code that was causing problems.
Once we requeue unsent emails in https://github.com/Automattic/wp-calypso/issues/72778

 - [x] We have to solve it properly.
 - [x] D99809-code should be reverted or test unskipped
 - [x] a new test should be also added to make sure it does not happen again

IMO it could be a simple fix in the wpcom codebase that says:

```
if ( ! empty( $subscriber_id ) && $subscriber_id > 0 && class_exists( WPCOM_Offline_Subscription_Service::class ) && method_exists( WPCOM_Offline_Subscription_Service::class, 'subscriber_can_receive_post_by_mail' ) ) {
	$subscription_service = new WPCOM_Offline_Subscription_Service();
	if ( ! $subscription_service->subscriber_can_receive_post_by_mail( $subscriber_id, $post_id ) ) {
		continue;
	}
}
```
```

**Comment by artpi** [comment]
MAKE UNIT TESTS SO THIS DOES NOT REPEAT

**Comment by artpi** [comment]
After chatting with @millerf 
`! empty( $subscriber_id ) && $subscriber_id > 0` is probably not the best solution since it would cause the email subscribers to get the paid emails.
The check should actually check only the post meta for if that post is paid. I think @romarioraffington suggested something like that and I did not understand it at first.

Also lets not try to centralize the logic yet.

**Comment by n3f** [comment]
I'm trying to get a proper test working.  Currently the tests work by using a hook to always return empty subscriptions, (to prevent sending emails), but I think we can just override the mail sender instead and test everything...

But yes I think the fix is a lower level than the simple subscriber one here.

**Comment by millerf** [comment]
> I'm trying to get a proper test working. 

Do you have a PR somewhere?

**Comment by n3f** [comment]
> Do you have a PR somewhere?

D99740-code

**Comment by n3f** [comment]
Working tests! Plus I put the fix there (for now), but I'll get a jetpack version out next.

**Comment by artpi** [comment]
I am leaning towards baking all logic in D99740-code so that we are kinda safe on that end, and later discussing how to split logic between wpcom codebase and JP
