### ISSUE TITLE
Purchases: error when trying to cancel an upgrade that is already pending cancellation

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#728]
If I start the cancellation flow for a domain pending cancellation confirmation via email, I'll get this error: `This upgrade cannot be cancelled`. We should improve this error message to let the user know they've already requested a cancellation (or, really, just let the user request the email again).

Steps to reproduce:

- Request cancellation for a domain.
- You will see a notice saying you received an email to confirm the cancellation. Do not confirm from this email.
- Request cancellation again. You'll be told the upgrade can't be cancelled.

**Comment by drewblaisdell** [comment]
We don't have a confirmation email for cancellations anymore, so this is no longer an issue.
