### ISSUE TITLE
Launchpad: First Post Published modal render on top of the Launchpad on save modal

### ISSUE THREAD

**Issue by sharpirate** [Automattic/wp-calypso#72803]
When working on enabling Launchpad for the `build` and `write` intents we encountered an issue where once you go to the Post Editor and publish a post the "First Post Published" modal will render on top of the "Great Progress!" modal:

https://user-images.githubusercontent.com/20927667/215843071-9a0ae5b5-675c-4b5c-bd04-fad69e74a4b7.mov

 This resulted in blocking of the E2E tests due to the issues with focus management between the two modals and and possible different context within the iframes. We've patched the issue for now: https://github.com/Automattic/wp-calypso/pull/72677/files#diff-6d9ee456580855fe44992a59575f18f61200ea5e065504fee3bde53ea5ee083fR131-R140
 
 This issue should serve as a conversation started when it comes to how do we want to deal with the two modals on top of each other since the current behavior is not ideal in terms of user experience. One suggestion would be to not show the "First Post Published" modal at all when we are showing the Launchpad on save modal because the latter is arguably more suited for Launchpad flows providing clear call to action buttons as opposed to the First Post Published which doesn't have Launchpad specific copy

**Comment by jeyip** [comment]
cc @nuriapenya

**Comment by nuriapenya** [comment]
>One suggestion would be to not show the "First Post Published" modal at all when we are showing the Launchpad 

I agree. I prefer to reduce the number of modals too. Especially since it seems in the future, we might have another modal after publishing: pe7F0s-bh-p2

**Comment by lupus2k** [comment]
Reopen because it's happening again. 
Slack discussion: p1694530274144539-slack-C057AH42XQD

**Comment by lupus2k** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/33098
