### ISSUE TITLE
Domains: add site redirects for subdirectorys

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/wp-calypso#7281]
#### Steps to reproduce
1. Starting at URL: wordpress.com/domains/add/site-redirect
2. Add a URL that includes a subdirectory, like exampledomain.com/blog
3. Click "Go"

#### What I expected
The site redirect should be added successfully.  

#### What happened instead
Got this error: Sorry but exampledomain.com/blog does not end with a valid domain extension.

#### Screenshot / Video
<img width="838" alt="screen shot 2016-08-04 at 10 46 21 am" src="https://cloud.githubusercontent.com/assets/15107387/17412268/c338e52e-5a30-11e6-9b1c-d2c0fc84d09d.png">

#### Context / Source
Discovered this while chatting; was able to add with no problem using wp-admin.
#user-report

**Comment by klimeryk** [comment]
Confirmed.
I've checked the code and there's a simple (and embarassing) reason for this - the code expects a `http(s)://` prefix. If it's not there, it won't try to extract the domain part of the redirect. If you add it, you'll be able to successfully add a redirect to a subdirectory (`http://exampledomain.com/blog`).

This should be fixed on both backend and frontend - just adding the `http://` prefix if not present, before sending to the backend should suffice.

**Comment by VagishVela** [comment]
@klimeryk I don't mind having a look at fixing this. I'm interesting in contributing to this repo, about time I gave back for all the wordpress I have used prior.

**Comment by klimeryk** [comment]
Sure thing, @VagishVela! Have a look at our [contributing guidelines](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md#pull-requests) and open a pull request once the patch is ready. Feel free to ping me when it's done or when you have any questions!
