### ISSUE TITLE
[Bug] Persist Home template returns a 500 error (not on production or staging)

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#72811]
### Description
The error is somehow introduced by the feature flag `themes/theme-switch-persist-template`.

This flag was enabled for the development and horizon environments in this [PR](https://github.com/Automattic/wp-calypso/pull/70219/files).

We introduced the flag in [Use a feature flag for the theme switch work](https://github.com/Automattic/wp-calypso/issues/70179), to disable the theme switch work for all, users and a8c accounts because we aren't ready to ship the theme switch work to users and we made the a8c experience equal to the user experience.

### Testing Instructions

- Go to the logged-in theme showcase on horizon or development envs
- Switch to another theme preserving your homepage
- The theme switch will fail and you'll see an error notification

<img width="1092" alt="Screenshot 2566-01-30 at 16 56 53" src="https://user-images.githubusercontent.com/1881481/215453615-ddaef6bb-1cee-47e2-9bd9-9c9c1c42e9e4.png">
<img width="676" alt="Screenshot 2566-01-30 at 16 55 48" src="https://user-images.githubusercontent.com/1881481/215453641-271569a5-42fe-40b6-8f5d-afdb6854d800.png">
<img width="253" alt="Screenshot 2566-01-30 at 16 55 29" src="https://user-images.githubusercontent.com/1881481/215453659-ab88fe56-cf81-4272-be4b-00ed181e397f.png">

### Dev tasks
- [x] Disable the flag `themes/theme-switch-persist-template` for all environments to avoid the error. https://github.com/Automattic/wp-calypso/pull/72813 
- [ ] Investigate the cause of the error before continuing with the theme switch work.

### Related
D92974-code
https://github.com/Automattic/wp-calypso/issues/70179
https://github.com/Automattic/wp-calypso/pull/72747#issuecomment-1408625753

**Comment by okmttdhr** [comment]
Closing as the persisting homepage is disabled currently and it's in inactivity. Let's reopen when we work on it again!
