### ISSUE TITLE
Site logo size change doesn't save, Alonso theme, FSE

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#72825]
### Quick summary

When editing the Site Logo in Header and Footer template, attempted to resize logo. The size changes in the Editor, but after saving, view on live site shows no change. Also attempted to change the header layout with columns. Still no size change. Reproducible on test site.

### Steps to reproduce

1. Appearance -> Editor
2. click into Site Logo block.
3. Resize by click/drag or using the sizer in block settings.
4. Save
5. View site

### What you expected to happen

Expected the logo to resize on the live view.

### What actually happened

Logo stays the same size.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Alonso theme.

**Comment by radtechgh** [comment]
5909135-zen

**Comment by cuemarie** [comment]
Thanks for the report! This looks like part of a larger issue reported here: https://github.com/Automattic/wp-calypso/issues/72684

Closing as duplicate, and sharing the user report over there instead!
