### ISSUE TITLE
LaunchPad -  General onboarding - give "skip to dashboard" from goals page a launchpad

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72870]
we recently added the launchpad to general onboarding for `build` and `write` flows.

This however does not show up if we "skip to dashboard" from the goals page:
![Screen Shot 2023-02-01 at 8 38 12 AM](https://user-images.githubusercontent.com/28742426/216058465-8e0089f5-c8fc-4368-ba16-c6ce52451fbe.png)

Upon inspection this does not set a site intent, however it would make sense to set this to `build` as we do in the "Other" option, and enable the launchpad for this flow.

**Comment by edanzer** [comment]
Closing this as complete based on https://github.com/Automattic/wp-calypso/pull/74082
