### ISSUE TITLE
LaunchPad in General Onboarding - Disable launchpad for later "built by" flows.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#72887]
While we don't enable the launchpad in general onboarding for "built by" flows, there are ways for the user to enable "built by" later on. Such as this upsell in the themes page:

![Screen Shot 2023-02-01 at 2 25 06 PM](https://user-images.githubusercontent.com/28742426/216142835-a46ec067-2420-4691-a215-f73f157a4af7.png)

We need to ensure that a user who enables the launchpad in any onboarding flow, and then selects and checks-out a built-by plan, does not continue to have the launchpad or related functionality.

Currently built-by seems to hide "My Home" so there is no immediate conflict (this could always change). However, if we provide other custom changes to the interface (like a button in the top nav bar) we would not want those to bleed over.

EDIT - some notes in the comment below about how we can achieve this.

**Comment by Addison-Stavlo** [comment]
some added context in this slack thead - p1675435837845359/1675431323.984369-slack-C028NRBP2AU. 

We can essentially check the presence of a blog sticker and use that to override `launchpad_screen` logic - this maybe simple to handle on the backend.

**Comment by mattwiebe** [comment]
D100369-code should have a fix for this

**Comment by mattwiebe** [comment]
D100369-code was shipped, today, finally :)
