### ISSUE TITLE
Plans: add upgrade link to top masterbar

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7288]
This is a very simple idea, to add a link that says "upgrade" in the top bar for existing users who have a single site without a paid plan. @apeatling may have more specific ideas for how to implement this. But I think a text link that sits right next to the "reader" tab, rendered as a link (rather than as a tab) would be a good start. I don't believe this will work for the mobile view, so for now we can just try this in the desktop view. The link should point to the plans page.

We may want to try this with a limited test, say for users who have registered after the test start date.

**Comment by lamosty** [comment]
Great idea, I like it.

Here are some initial designs:

## Rendered as a tab (so behaves the same as Reader tab):

![selection_024](https://cloud.githubusercontent.com/assets/4988512/17435278/0316d928-5b10-11e6-9a7e-c61936017e32.jpg)

## Rendered as a link:

![selection_025](https://cloud.githubusercontent.com/assets/4988512/17435507/ab2a59cc-5b11-11e6-96cf-9f49a95fdee9.jpg)

We could maybe change a hover color a bit but for that I need a designer's eye.

**Comment by folletto** [comment]
I'm very very uncomfortable with this. The masterbar is the main navigation piece, we shouldn't really touch it. :(

**Comment by apeatling** [comment]
Giving this one a rethink, as stated in #7301
