### ISSUE TITLE
Odyssey Stats: Add a dismissable nudge for customer feedback after three views of Odyssey Stats

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#72927]
![Image](https://user-images.githubusercontent.com/4044428/215221977-df8dbd19-f68f-4bd1-9150-459d49a1bfb9.png)

Link to a Jetpack redirect in the banner with an appropriate slug, like `jetpack-stats-2023-usage-survey` (PCYsg-pY7-p2). Surveys are still being created. See p1HpG7-khi-p2#comment-60393 for final designs.

**Comment by jsnmoon** [comment]
@jeffgolenski, what are your thoughts on making this kind of survey available for Calypso Stats as well?

**Comment by jsnmoon** [comment]
@annacmc, be sure to hand off the task to the team before your AFKs on Th/F! ✋

**Comment by annacmc** [comment]
Question for @Automattic/red team - how do we want the `remind me later` link to work? I think it could reset itself and show again in 3 more views. Code-wise, I think that's the most simplistic approach, but perhaps that is too soon?

**Comment by jsnmoon** [comment]
@annacmc: That might be too soon. Here's the ideal behavior I have in mind:

1. If the user clicks the CTA for the survey, we should stop showing the nudge for the customer, starting with the next page view. I don't see a need to automatically dismiss the notice on the current page view, however.
2. If the user clicks remind me later, we could hide the notice for ~30 days.

I'm okay with omitting behavior (1) from our initial PR, but it's nice to have. I think behaviors (1) and (2) can use the same underlying mechanism (e.g., via localStorage).

**Comment by jeffgolenski** [comment]
> @jeffgolenski, what are your thoughts on making this kind of survey available for Calypso Stats as well?

I like the idea, but I recommend we see how this mechanism works in wp-admin first. Perhaps for calypso we can sync with dotcom teams to create more tailored surveys? What do you think @jsnmoon 

> If the user clicks remind me later, we could hide the notice for ~30 days.

Love this.

**Comment by jsnmoon** [comment]
> I like the idea, but I recommend we see how this mechanism works in wp-admin first. Perhaps for calypso we can sync with dotcom teams to create more tailored surveys? What do you think? (@jeffgolenski)

Sounds good to me!
