### ISSUE TITLE
Launchpad: Allow deleting launchpad_screen

### ISSUE THREAD

**Issue by sharpirate** [Automattic/wp-calypso#72976]
#### Summary
This is how the `launchpad_screen` option works currently:
1. The option is created for Launchpad sites so it doesn't exist on non-Launchpad sites
2. It accepts the following values: `off`, `full`, `minimized` - all of these make sense for a Launchpad-enabled site.

However, we've recently run into an edge case were if a site is created to use Launchpad initially but later we want to disable the Launchpad there's not good way to do that. We are setting the `launchpad_screen` to `off` but that's not ideal as it indicates that Launchpad has been completed where that's not the case. 

[Example where we do that](https://github.com/Automattic/wp-calypso/pull/72888/files#diff-614cccce787b17e46e84a16af7865700992dfd374e701239023fd2e1feaa12a1R187)

Setting the option to `false` or `null` can be unpredictable and since non-Launchpad sites don't have the option to begin with it makes sense to find a way to delete that option - either by creating a new endpoint or using something already existing

**Comment by Addison-Stavlo** [comment]
with resolving the above PR, i dont think this issue is necessary currently.
