### ISSUE TITLE
Jetpack Scan item showing in wp-admin sidebar for AT sites

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#72982]
### Quick summary

If a user is not logged into their wpcom account and logs into their local user (wp-admin) they have an option for Scan under Jetpack in the sidebar. If they select this item they are directed to login with their wpcom account and then redirected to a page not found.

Ideally, the Scan option should not show for sites that have an associated wpcom plan since scan is included in the plan and they have no ability to access or modify an scan settings. If this is not possible, either on the wp-admin only side or after signing into their wpcom account the user should probably see a screen informing them that scan is managed

### Steps to reproduce

1. make sure you are not logged into a wpcom account associated with a site
2. log in to wp-admin only
3. look under Jetpack > Scan
4. get redirected to the login for wpcom
5. get redirected to a page not found

### What you expected to happen

they either shouldn't have this link or should be made aware it's included in their plan and manged

### What actually happened

it seems like this is a feature they can use but no clear explanation of how or why not

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

came up here: p9F6qB-bqe-p2

**Comment by villanovachile** [comment]
Thanks again for reporting this one as well! Will dig in tonight and should have a PR to fix this tomorrow or this weekend.

**Comment by villanovachile** [comment]
PR submitted here: https://github.com/Automattic/jetpack/pull/29269
