### ISSUE TITLE
Jetpack credentials screen showing for Atomic sites

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#72983]
### Quick summary

When logged into wpcom and the site (either with SSO or with wp-admin creds) the jetpack credentials screen appears under Settings > Jetpack.

This is not breaking things but is confusing because:
1. when first loaded it displays as though credentials are missing (and takes a few seconds to refresh and show a successful connection)
2. wpcom AT users shouldn't ever need this screen and can't manage any settings here

This screen is not available if the user is signed in with local credentials only (i.e. not logged into wpcom)
It sounds like this screen was previously hidden but has since re-appeared

### Steps to reproduce

1. login to a WoA site
2. got to Settings > Jetpack

### What you expected to happen

don't expect to see this screen at all for sites with a wpcom plan

### What actually happened

see the screen 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

came up here: p9F6qB-bqe-p2

**Comment by villanovachile** [comment]
Thanks again for getting this one reported. Finally have a chance to look into this and should have a PR for the fix either tonight or tomorrow!

**Comment by villanovachile** [comment]
Added PR to remove Jetpack submenu item from Settings in Calypso: https://github.com/Automattic/jetpack/pull/29268

Added PR to display notice for Atomic users who navigate to the slug manually: #74034
