### ISSUE TITLE
Mobile visitors from China seeing 429 errors

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#73004]
### Quick summary

Users from china see 429 error without VPN occurs only on mobile devices and not on computers. As per the site owner who contacted us, the issue started after Feb 2, 2023, UTC 00:00

The issue apparently happens with the following conditions:
* On mobile device
* Without VPN.

The user claims they checked with govt agencies and they say WPcom is not blocked. 

### Steps to reproduce

NA

Similar cases were reported for .org as well in the past: p93R5q-1uI-p2#the-underlying-issue-429-too-many-requests

### What you expected to happen

The site should load for users in mainland china.

### What actually happened

429 errors

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

As a workaround, we can ask them to use VPN, but it is not an ideal solution as it cannot be communicated with potential visitors from the affected region. 

User report: 5927945-zd-woothemes

**Comment by filipanoscampos** [comment]
User added more information on this issue:

> 1. https://ttcath.org/loh/ load slow, when visitors in mainland China use VPN on the mobile device, it loads slow.
> 
> 2. The link https://ttcath.org/2023/02/06/prot-9-23-totus-tuus/ in mainland China, who use the mobile device in WeChat internal browse with VPN, the page cannot be load, 429 error again. Without VPN, can load, but slow.

**Comment by pak-cia** [comment]
played into a linked ticket, and left some notes in one of them here: zen-5927945

**Comment by JoshuaGoode** [comment]
How many users/visitors have reported this so far and have their IPs been documented in the support tickets?

**Comment by liviopv** [comment]
I'm closing this issue as this seems to be an isolated case. There are no recent reports that fit the same pattern, so this doesn't seem to be a widespread issue.

Please reopen as need.

**Comment by ttcath** [comment]
@liviopv i get the feedback from WordPress.com Support Team Feb 14, 2023, 08:06 UTC they said:

Following up on |our investigation, recently there has been a significant increase in the amount of malicious traffic from China, and, as a result, we added some additional limits on our side. 
 
These limits inadvertently returned 429 errors for legitimate traffic for your domain ttcath.org. 
 
We have now excluded your domain from the limiting so this issue should be resolved.

So, it's looks like the WordPress.com do some limits in case to provide necessary security options on this case. 

Please kindly investigate the rest .org domain hosted by WordPress.com, in case to deeper investigate.
