### ISSUE TITLE
WooExpress: Disable the "Launch Anyway" button

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#73015]
It is still possible to Launch the site through the Setup task list. We should disable this button and show a message to inform the user that they can't launch while in the trial. We also need to make sure to handle it on the back end.

<img width="1512" alt="Screen Shot 2023-02-06 at 16 02 28" src="https://user-images.githubusercontent.com/1234758/217061810-cdb3db5e-1831-48bf-8849-c071d5394bf8.png">

More context: peapX7-1yF-p2#comment-1594

**Comment by valterlorran** [comment]
The progress on the back end is here: D100473-code

**Comment by daledupreez** [comment]
Noting that this should be addressed by Automattic/wc-calypso-bridge#937 when we get that into a release and get that release into an updated version of `wpcomsh` shipped to Atomic sites.

**Comment by daledupreez** [comment]
I am going to mark this as resolved, as the fix for this issue will be included in wpcomsh 3.7.8, which will be deployed to Atomic sites during the course of today.
