### ISSUE TITLE
Stats: Change "Followers" to "Subscribers"

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#73026]
It appears as though WordPress.com has changed "Followers" to "Subscribers" everywhere in calypso except for the stats navigation (right side). Let's make this quick change to ensure we're consistent.

**Now:**

![Image](https://user-images.githubusercontent.com/214813/217106160-656ef6ef-b5cf-4243-9e65-c828e8620920.png)

**After:**

![Image](https://user-images.githubusercontent.com/214813/217106096-7ce757f8-ad68-4407-9245-97cbfeb7da73.png)

**Comment by kraftbj** [comment]
The rough edge is a self-hosted site can have users on it with the role of "Subscriber" that has no relation to the dotcom notion of "Subscriber", which is why, historically, Jetpack kept using the "Follower" name.

Not blocking any change, but providing context for the why in Jetpack.

**Comment by jeffgolenski** [comment]
@kraftbj Absolutely. Totally agree. For now, this "followers" / "subscribers" nav section is **not** included in the Odyssey stats since the flows and behavior is completely different from a WordPress.com site! 

The delay of that name change for us was largely due to the complexity you described, so we need to take time to figure that out.
