### ISSUE TITLE
Same menu isn't visible on single page when menu is selected in multiple navigation blocks and the menu was created in FSE

### ISSUE THREAD

**Issue by zyousafi** [Automattic/wp-calypso#73059]
### Quick summary

If you create a menu in FSE and you select that same menu in multiple Navigation Blocks on the same page (i.e., in the "Header" part, the main content area, and the "Footer" part), then only the first instance of that menu will display on the live website; all the while, the duplicate menus will show in the editor just fine.

**Known workaround:**
If the menu was created in the Customizer, then that same menu can be selected in multiple Navigation Blocks on the same page without any issues

### Steps to reproduce

1. Create a new menu in FSE with a few menu items.  Call it whatever you want
2. Select that menu in a Navigation Block in the Header, the main content area, and then again in the Footer

### What you expected to happen

I expected the menu I created in FSE to show up in all three locations

### What actually happened

The menu I created in FSE showed up only in the Header, but not in the main content area or in the footer.  I can see the menu in all three locations in the editor, but not on the live website

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested with both the **Antonia** theme and the **Twenty Twenty-Two** theme

**Comment by zyousafi** [comment]
Initially reported here: 5936603-zd-woothemes

The user would like to know when the issue is resolved

**Comment by NoHopeRadio** [comment]
2 cases of this in chat so far today:

40488989-hc
40513762-hc

**Comment by cuemarie** [comment]
@zyousafi Please report all bugs through Bugomattic so that they are automatically queued up for triaging and not missed. Further reading: PCYsg-x6U-p2

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Created a new menu in FSE called "Header Navigation 4"
- Placed it in the Header and Footer of theme Twenty Twenty three, as well as on the page itself
- All 3 appear in the editor and on the live site

**Simple Example**

![Markup on 2023-03-05 at 12:54:42](https://user-images.githubusercontent.com/27249804/222982659-013a2dfb-6717-4521-8881-a0a13129338c.png)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
