### ISSUE TITLE
Domains: Invalid e-mail error message duplicated

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7306]
#### Steps to reproduce
1. Starting from URL: https://wordpress.com/domains/add/example.wordpress.com
2. Select a domain name, either accept or decline GApps
3. Fill out the e-mail field of the contact information form with an invalid e-mail, or more than 80 characters

#### What I expected
A single error message

#### What happened instead
The phrase `The “Email” field does not appear to be valid.`is repeated twice

#### Browser / OS version
OSX Chrome v51

#### Screenshot / Video
<img width="335" alt="screen shot 2016-08-05 at 12 11 38 pm" src="https://cloud.githubusercontent.com/assets/7233112/17443022/6a7caa34-5b06-11e6-8107-5dc9c39a5982.png">

#### Context / Source
#manual-testing

**Comment by klimeryk** [comment]
I've deployed a fix for this on the backend - the issue should be fixed now :)
