### ISSUE TITLE
[Block] Post Carousel - Featured Images hidden by Customizer settings: Customize > Content Options > Featured Images

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#73069]
### Quick summary

The Post Carousel block is impacted by the Content Settings selections in the Customizer. If a theme has the option to hide featured images on posts or pages, and a Post Carousel block is added to posts or pages, then these settings also hide the Post Carousel block's features images, breaking the function of the block.

### Steps to reproduce

1. Activate a theme that uses Content Settings to hide featured images, such as Apostrophe 2
2. Add a Post Carousel block to a Post or Page and publish that
3. In the Customizer, view the page/post in question, then open **Content Settings** and uncheck the option to show featured images on that post type

### What you expected to happen

The featured image on the post or page should be the only thing that's hidden by this setting.

### What actually happened

The Post Carousel block is also responding and hiding featured images too.

https://user-images.githubusercontent.com/27249804/217405197-b15e6b70-9515-4fef-8e75-23689e54a8b9.mov

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- User report: 5934004-zd-woothemes 
     - (asked for an update when the issue is resolved so they can remove the CSS workaround)
- Troubleshooting notes where the issue was discovered: p1675705661312809-slack-C03TY6J1A

Workaround is to provide CSS to hide the page/post featured images, allowing the Post Carousel block to work normally. This won't work for customers whose plans do not include CSS support

```
.single .entry-thumbnail {
	display: none;
}
```

**Comment by cuemarie** [comment]
Found some similar older reports, where the assumption was this was a theme issue. Keeping this report open for now, as it seems those didn't get very far, and it doesn't seem like this is theme-specific, but rather how these blocks interact with the Customizer's content settings:

- https://github.com/Automattic/themes/issues/3540
- https://github.com/Automattic/wp-calypso/issues/59280

**Comment by mdtanjid0** [comment]
Same issue with the Rowling theme. 

5953266-zd

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Can still replicate on any theme that has the option to hide featured images in the Customizer

**AT Example: Twenty Twenty Theme**

https://user-images.githubusercontent.com/27249804/222983549-0e876723-f70a-442a-b9aa-a3e88ed15434.mp4

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by alliebbush2** [comment]
Same issue-Spearhead Blocks Theme
6032610-zd-User would like to be notified when issue is resolved.
Also this theme does not have the "Content Options" in the Customizer

**Comment by ClassicRKR27** [comment]
Another report here, gave them the workaround: 7158638-zd-a8c

**Comment by cuemarie** [comment]
Reports from https://github.com/Automattic/themes/issues/3540 : 

- 3856314-zen
- 4286161-zen

**Comment by victorespigares** [comment]
Another report here, with theme Exford:

- 7478949-zd-a8c

**Comment by kathrynwp** [comment]
Another report: 7535096-zd-a8c

I provided CSS as a workaround to keep featured images hidden on pages but re-display them in the carousel:

```

/* Pages - hide featured image at top / 7535096-zen kp */
.page .post-thumbnail {
  display: none;
}
/* Pages - show featured image in carousel / 7535096-zen kp */
.page .swiper-slide .post-thumbnail {
  display: inherit;
}
```
