### ISSUE TITLE
Pattern Assembler - BlockGap between patterns is not visible on the assembler's site preview

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#73072]
### Description

The gap between header/sections/footer is visible on the site editor and the site front-end but is missing in the site preview in the assembler.

This is in production. It's an important visual issue that degrades the assembler experience. The previews on the assembler and the editor should match. 

**The assembler's large preview doesn't show the gap** 

![Image](https://user-images.githubusercontent.com/1881481/217430584-d9bd9155-d705-45b3-85dc-66adbb767229.png)

**The editor's preview shows the gap**

![Image](https://user-images.githubusercontent.com/1881481/217430654-04a46725-4047-4b87-926b-85c1422fc825.png)

### Dev notes

The gap is in the CSS `body .is-layout-flow > * + *` but won’t affect the preview of the assembler because we use an iframe for each pattern so they don't share the same body. It works fine in the editor canvas because all the patterns are in one iframe.

We can't remove the setting [blockGap: 1.5rem](https://github.com/Automattic/themes/blob/trunk/blank-canvas-3/theme.json#L277) from the BC3 theme because all blocks use it. See [blockGap docs](https://fullsiteediting.com/lessons/theme-json-layout-and-spacing-options/#h-blockgap)

In the editor, the global setting is in :yin_yang: `Styles > Layout > Block Spacing`, and the block level paddings are in `Settings > Block > Dimensions > Padding`.

A potential solution is hiding the gap everywhere by adding a new parent group that has `{"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"default"}}` but something feels off about that extra group. See p1675745922119049/1675734190.665949-slack-CRWCHQGUB

### Testing
- Add a header, sections, and a footer
- Check that there is no gap between them in the assembler preview
- Check that the gap is in the editor and the site frontend

### Dev tasks
- [x] Add the `blockGap: 1.5rem` hardcoded between iframes in the site preview.
- [x] Create an issue to explore using a single iframe for all patterns in the site preview.

Note that later when working on support colors and fonts we'll get the `blockGap` value in the client and use it instead of the hardcoded value. See the convo p1676291449799039-slack-CRWCHQGUB

**Comment by miksansegundo** [comment]
@okmttdhr, we can work on this issue together and review how the Pattern Assembler previews work.

**Comment by okmttdhr** [comment]
Thank you, @miksansegundo!

>The previews on the assembler and the editor should match.

To make sure, we want to **hide** the gap in the previews on the assembler, correct?

**Comment by miksansegundo** [comment]
We will show the gap between iframes in the site preview in the assembler because it's missing.

**Comment by okmttdhr** [comment]
Thanks for confirming.

>A potential solution is hiding the gap everywhere by adding a new parent group that has {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"default"}} but something feels off about that extra group.

I'm commenting without knowing much, but I thought it would be a good idea to fix the design that the style is applied differently depending on whether there is in an iframe or not.
e.g., We may be able to add (inject) the same CSS into an iframe?

**Comment by arthur791004** [comment]
The issue is the large preview (the preview on the right side) displays each pattern in a different iframe, so the gap is missing

For example,

```html
<!-- The gap works well -->
<iframe>
  <pattern1 />
  <pattern2 />
  <!-- ... -->
</iframe>

<!-- The gap is missing -->
<!-- pattern1 -->
<iframe />
<!-- pattern2 -->
<iframe />
<!-- ... -->
```

The pros of the current implementation are as follows:
* It's easy to add the action bar to each pattern in the large preview so users are able to replace/reorder/delete patterns when they browse the large preview. If we put them in a single iframe, we have to use inline styles to style the action bar in the iframe. But if we don't want to display the action bar on the large preview in the future, we can consider displaying them in a single iframe
* It might be easier to scroll to the specified pattern when users are adding/replacing/deleting a pattern.

There are still some downsides:
* This issue
* If users select many patterns, there will be so many iframes in the large preview and the page might be slower
* The style changes (e.g. select a color variation) might have a slight delay for each pattern.

So, we can hardcode the gap to solve this issue for now. We can consider putting them in a single iframe (or any better solutions) but it depends on the features.

**Comment by miksansegundo** [comment]
Thanks @arthur791004 for the details. At this moment, I see more value in the downsides than in the pros. 

I believe we don't currently have on the roadmap a feature to add an action bar per pattern on the large preview. Am I right? Anyways, I believe we could add that action bar in the future in other ways without using an iframe per pattern. 

For the scrolling feature, we can also find other ways without using an iframe per pattern.

Let's consider putting the patterns in a single iframe in the site preview because that's how the editor does it, and it will solve issues like this related to global styles.

**Comment by arthur791004** [comment]
> I believe we don't currently have on the roadmap a feature to add an action bar per pattern on the large preview. Am I right?

We have some feedback related to the action bars

* https://github.com/Automattic/wp-calypso/issues/73268
* p1676785569153359/1676709408.693199-slack-C048CUFRGFQ
* I remember we also discussed this somewhere

In my opinion, putting the patterns in a single iframe takes the same effort to do it now or do it later. As the downside is not a big issue for now, I'd prefer to wait for the new design or we can discuss the future of the action bar with @davewhitley

What do you think?

**Comment by miksansegundo** [comment]
Okay, let's wait for the new design. I'll create an issue in the backlog to use a single iframe in the large preview.

Meanwhile, here is the [PR](https://github.com/Automattic/wp-calypso/pull/73652) that hardcodes gap.
