### ISSUE TITLE
Upsells: Add second upsell to /themes

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#73110]
See pebzTe-Gg-p2#comment-1195

Acceptance criteria:
- [ ] Show second upsell after 6 rows of themes.
- [ ] The new upsell should be the "premium themes" upsell (see the p2 videos).
- [ ] Track the new upsell vs. the upsell at the top.

**Comment by candy02058912** [comment]
I was confused about which upsell to show. WIll add a PR to see if I got it right.
