### ISSUE TITLE
Theme Showcase: selected category not respected after viewing theme detail page

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#73138]
# Description

The selected category is not persisted after viewing theme detail.

![Image](https://user-images.githubusercontent.com/5665959/217745632-b4f3d95e-4b68-4b53-83c9-c04f77df2df5.png)

### Expected behavior
* Select a category
* View any theme detail page
* Got back to /themes
* My selected category and the filtering should be persisted to the state before I view the detail page
*

**Comment by taipeicoder** [comment]
Closing via #73420.
