### ISSUE TITLE
Add Jetpack Import package check

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#73139]
Context: a Jetpack self-hosted site. Visit `http://calypso.localhost:3000/import/SELF_HOSTED_SITE`

Now that the Jetpack Importer is a package, we should check if it is loaded. It will happen:

1. Atomic sites: Jetpack is automatically updated to the last version in `wpcomsh`: **not needed**
2. Self-hosted Jetpack sites: when Jetpack is **updated to the version that includes the Unified Importer**
3. Simple sites: **not needed**

Ideally, we should check if a user is on a self-hosted site. If the package is not loaded, Jetpack must be updated. This can be done in two ways.

1. Check the Jetpack version, once we know the version that introduces the new feature.
2. Check if the package is there like all other packages. We need to investigate if there is a quick way of doing this with the API. see p1675930288012339-slack-CDLH4C1UZ

Once we detect that the user needs to update Jetpack, we should warn it.

**Comment by vishnugopal** [comment]
Deployed with this change: https://github.com/Automattic/wp-calypso/pull/73802
