### ISSUE TITLE
Domain shortcodes don't render in the help center

### ISSUE THREAD

**Issue by heavyweight** [Automattic/wp-calypso#73145]
### Quick summary

The support articles `Domain Pricing and Available TLDs` and `Premium Domains` use shortcodes in the content and when viewed in the help center those fail to render and instead the text `[wpcom-available-tlds links=true render_restrictions=true]` for the first article and `[wpcom-available-tlds links=true render_restrictions=true render_only=premium]` for the second article is shown.

### Steps to reproduce

1. Open the help center
2. Search for `Domain Pricing and Available TLDs` or `Premium Domains` and open the article
3. Look though the content and you will see the shortcode displayed as text

### What you expected to happen

The shortcodes should render and show the content relevant to the articles

### What actually happened

`[wpcom-available-tlds links=true render_restrictions=true]` and `[wpcom-available-tlds links=true render_restrictions=true render_only=premium]` appear in the article content

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by karenroldan** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO

I no longer see the shortcodes upon checking the support articles: `Domain Pricing and Available TLDs` and `Premium Domains`

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
