### ISSUE TITLE
`rss_use_excerpt` setting: Fix unexpectedly displayed "Changes you made may not be saved." dialog

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#73149]
When the `rss_use_excerpt` setting on the _Settings → Reading_ or _Settings → Writing_  page is saved and we try to navigate away from the page (or reload it), the "Changes you made may not be saved." dialog is displayed unexpectedly.

![Markup on 2023-02-09 at 11:09:36](https://user-images.githubusercontent.com/25105483/217782836-80e73eea-df9d-48ed-bde8-a88cc07d2660.png)

We have addressed similar issue for other settings on the Reading settings page in https://github.com/Automattic/wp-calypso/issues/71071, but the root cause for the `rss_use_excerpt` setting is different and requires further investigation.

**Comment by ivan-ottinger** [comment]
It looks like the cause is related to the following observation:
![Markup on 2023-02-08 at 16:53:47](https://user-images.githubusercontent.com/25105483/217783176-7f366496-4178-44bd-b5e0-b5516af8373c.png)

Needs more investigation why this happens.

**Comment by TimBroddin** [comment]
Tested this and it works now. Closing this.
