### ISSUE TITLE
Update tour events to include intent and editor type

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#73142]
## Description

Referring to https://github.com/Automattic/wp-calypso/pull/72989#issuecomment-1423609534 and https://github.com/Automattic/wp-calypso/pull/72989#issuecomment-1423742277, we want to include `intent` and `editor_type` to the tour events in the editor. 
* intent: [SiteIntent](https://github.com/Automattic/wp-calypso/blob/be19d52186f71e67ab365831dc36a4a1e216469d/packages/data-stores/src/onboard/constants.ts#L12)
* editor_type:  site | post | page

Here are the tour events
* calypso_editor_wpcom_tour_open
* calypso_editor_wpcom_tour_dismiss
* calypso_editor_wpcom_tour_rate
* calypso_editor_wpcom_tour_minimize
* calypso_editor_wpcom_tour_maximize
* calypso_editor_wpcom_tour_slide_view
* calypso_editor_wpcom_tour_site_editor_course_link_click

Note that you can install [Tracks Vigilante Chrome Extension](https://github.com/Automattic/tracks-chrome-extension) to verify events 🙂

## Acceptance Criteria

- [x] The tour events should include the `intent` property
- [x] The tour events should include the `editor_type` property

**Comment by and1can** [comment]
Hi @arthur791004 , 

Is this issue still open? If so, I'd like to work on this.

**Comment by arthur791004** [comment]
@and1can Howdy! Thanks for you're interested in this issue but I'm sorry that we want to reserve it for our new dev. You can pick other issues from [Good first issue](https://github.com/Automattic/wp-calypso/labels/Good%20First%20Issue) 🙂
