### ISSUE TITLE
Events Calendar PRO version not added after purchase

### ISSUE THREAD

**Issue by kylemcph** [Automattic/wp-calypso#73168]
### Quick summary

User purchased The Events Calendar PRO plugin but still sees a the following message on their dashboard.

```
To begin using Events Calendar Pro, please install (or upgrade) and activate Events Calendar Pro (6.0.6+)
```

![Screen Shot on 2023-02-09 at 16_31_37](https://user-images.githubusercontent.com/38780306/217876300-a9366969-4383-4e39-9c39-a75945674387.png)
![Screen Shot on 2023-02-09 at 16_32_09](https://user-images.githubusercontent.com/38780306/217876330-2dd22526-fff7-489f-88ac-c25e165d7508.png)

It is unclear if this is only a version mismatch, and if they actually have Pro features or not. I've checked [Pro features here](https://theeventscalendar.com/products/wordpress-events-calendar/?TB_iframe=true), and when adding a new event, I trying to add a new recurring event, this message is displayed: 

![Screen Shot on 2023-02-09 at 17:31:10](https://user-images.githubusercontent.com/38780306/217876930-712279ac-7222-4723-bc69-a6868d2c60c4.png)

### Steps to reproduce

1. Search WP.com plugin marketplace for "Events Calendar PRO".
2. Purchase and activate plugin.
3. Notice the above notice on site dashboard

### What you expected to happen

The Pro version of the plugin is displayed and able to be used. 

### What actually happened

Pro version does not seem to be installed.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by cpapazoglou** [comment]
Related vendor chat pcXlSl-2P-p2

**Comment by cpapazoglou** [comment]
@epeicher confirmed that this is reproducible.

**Comment by cpapazoglou** [comment]
The vendor said that license is OK but this seems to be an outdated plugin version error.

I uploaded an updated version of the plugin to be deployed in all sites. It should get deployed in some hours in all sites. I will check then if the issue is resolved.

**Comment by cpapazoglou** [comment]
Problem seems resolved, it was indeed a version miss-match. Let's verify with the customer.

We are following up with the vendor to avoid such cases in the future.
