### ISSUE TITLE
Reading Settings: Add missing comma to the default value of the "Confirmation email message" field

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#73213]
The default value of the "Confirmation email message" field is missing comma:

![Image](https://user-images.githubusercontent.com/25105483/218044124-cf1f135c-1644-4bc6-9251-b5ed045218e6.png)

Context: pdtkmj-Vc-p2#comment-1963

**Comment by TimBroddin** [comment]
We removed the confirmation email, so closing this.
