### ISSUE TITLE
Reading Settings: Extend "Confirmation email message" and "Comment follow email message" text areas

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#73211]
This is how the default values appear in the text areas currently:

![Image](https://user-images.githubusercontent.com/25105483/218042849-0afb8572-218e-4f32-bb39-fa0b80755add.png)

It would be better to extend these, so the content fits in:

![Image](https://user-images.githubusercontent.com/25105483/218042922-a11967d6-053c-4ab2-a306-6ddb6dc32e25.png)

Context: pdtkmj-Vc-p2#comment-1963

**Comment by TimBroddin** [comment]
Welcome email will get a site-editor experience in the future. Closing this as it seems a bit redundant to fix this now.
