### ISSUE TITLE
[WooExpress] Task: Ensure our docs and marketing materials for eCommerce trial storage are aligned

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73212]
### Details

As noted in https://github.com/Automattic/dotcom-forge/issues/1500#issuecomment-1400889976, we were expecting a 3GB upload space limit for the free eCommerce trial, but it looks like it is actually coming out at 2GB. We should verify that our documentation and marketing materials reflect the current reality.

### Checklist

- [x] Confirm the current storage limit for a site on the eCommerce trial plan
- [x] Coordinate with marketing and/or the WooCommerce.com team to confirm we're advertising the appropriate space (or not specifying it)
- [x] Confirm we're specifying the right amount of storage in our My Plan and Plans pages
- [x] Coordinate with the docs team to make sure we have the correct amount documented (or don't document the specific limit)

### Related

Automattic/dotcom-forge#1500

**Comment by that-mike-bal** [comment]
FWIW I don't think we communicate the storage limit externally. I'll double check the Woo doc but I don't see it anywhere you mentioned.

**Comment by valterlorran** [comment]
> Confirm we're specifying the right amount of storage in our My Plan and Plans pages

We had a small issue on the My Plans page, which I addressed here: https://github.com/Automattic/wp-calypso/pull/76515. We are now waiting for the translation so we can deploy it.

> Coordinate with the docs team to make sure we have the correct amount documented (or don't document the specific limit)

I asked the docs team here: p1683546492312869-slack-CSP74N77C But I didn't have an answer yet.

**Comment by valterlorran** [comment]
I'm trying to coordinate with marketing on this thread: p1683913432983849-slack-C02PXDRC67P

**Comment by valterlorran** [comment]
Got the last response we needed here: p1686094567924419/1683546492.312869-slack-CSP74N77C
The woo docs are correct.
