### ISSUE TITLE
[WooExpress] Task: Ensure we display USD prices with US prefix outside of the US on eCommerce trial Plans page

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73223]
### Details

This issue was originally identified in https://github.com/Automattic/wp-calypso/pull/72797#discussion_r1101420149, where the eCommerce trial Plans page always shows USD prices with the currency symbol `$`. However, there are a number of countries where `$` is used as the local currency symbol, so we show USD prices with the symbol `US$` whenever we detect that users are outside of the US.

We need to update the new page to show the price appropriately.

### Checklist

- [ ] Show `US$` for prices on the eCommerce trials Plans page for USD prices outside the US

### Related

#72797

**Comment by markbiek** [comment]
@daledupreez I did a quick test where I manually passed a different locale (`es`) to the call to [getCurrencyObject](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plans/ecommerce-trial/index.tsx#L43) on the plans page and it seems to be displaying the prices correctly.

![image](https://user-images.githubusercontent.com/917632/218869423-d48fe3f2-4d81-406c-b70c-c2937c25c9bf.png)

Is there a recommended/reliable way of checking if a user is outside the US other than using the browser locale settings?

**Comment by daledupreez** [comment]
I should have provided way more context here, as there was some important discussions on how this should be done in the last month:
* pbOQVh-2WH-p2 discusses how we've updated Calypso to handle price formatting in a much more robust and locale-aware way
* #71387 is the PR that implemented the core API change for this

**Comment by daledupreez** [comment]
I've put up a PR for this in #73372, but that doesn't always add the `US` prefix -- I've asked on the original PR about the expected behaviour for that.

**Comment by markbiek** [comment]
> I've put up a PR for this in #73372, but that doesn't always add the `US` prefix -- I've asked on the original PR about the expected behaviour for that.

@daledupreez Can you drop a link to your question? If it's on either #73372 or #72797, I'm not seeing it.

**Comment by daledupreez** [comment]
Sorry for not including the context, @markbiek!
My questions on the original issue are in [this comment](https://github.com/Automattic/wp-calypso/pull/71387#issuecomment-1430869326) and [this comment](https://github.com/Automattic/wp-calypso/pull/71387#issuecomment-1431105505).

**Comment by markbiek** [comment]
@daledupreez I'm not sure what the next steps are.

I've done a couple of tests (changing my currency in the SA and changing the locale of my browser) and the trial plans page seems to show the correct currency. I also verified that the behavior is the same with SSR (I hard refreshed the page).

Is it possible this is already functioning correctly or am I missing a piece? :)

**Comment by daledupreez** [comment]
I am going to close this out -- it looks like we are using the right solutions available to us in Calypso, so I don't think we need to keep this open.

**Comment by daledupreez** [comment]
Though I have dropped [another comment](https://github.com/Automattic/wp-calypso/pull/71387#issuecomment-1434628152) on the original `formatCurrency()` PR, as we are generally using just the `en` locale for most English-speaking users, and not more nuanced locales like `en-CA` or `en-AR`.
