### ISSUE TITLE
Marketplace: Yoast SEO Premium doesn't upgrade to Premium after purchase

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#73259]
### Quick summary

Yoast doesn't upgrade to Premium after purchase of Premium version. This happens on both upgrade and new install. It only installs the Free version. 

https://user-images.githubusercontent.com/9984867/218240244-eceb5360-304b-47eb-a80d-20515d7bc684.mp4

**Workaround:** 

1. Download the Premium version .zip file from https://my.yoast.com/downloads (need to login with the same email from WPCOM)
2. Upload the .zip file to /plugins and activate.

https://user-images.githubusercontent.com/9984867/218240382-e88d15d0-f0ca-45c4-b0cd-d3d4699373d1.mp4

### Steps to reproduce

1. Purchase Yoast Premium from Plugin Marketplace. 
2. Manage plugin to check Yoast. 

### What you expected to happen

1. It will install the Premium version. 

### What actually happened

1. It installs the free version. 

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by arinoch** [comment]
Had this issue in 11822606-hc. Symlinking it from CLI resolves it.

**Comment by rw-ye** [comment]
Another report - 5955931-zd-woothemes

Symlinked via CLI to fix the issue.

**Comment by mxhassani** [comment]
Another one: 40330642-hc 
Fixed via Cli.

**Comment by ccwalburn** [comment]
Another instance here:  22165549-hc
Fixed with CLI

**Comment by cuemarie** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/70980 which, happily, was fixed within the last 24 hours by 261988-wpcom 🎉
