### ISSUE TITLE
Conversion: Offer monthly pricing at a premium

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7325]
We currently offer annual pricing for our paid plans. We should keep these prices as the monthly cost if a user pays for a plan for 12 months up front. Let's introduce monthly payments with a premium, which means paying annual would offer a discount over monthly.

Example:
Personal: $5.99/month (paid annually), $7.99/month (paid monthly)
Premium: $8.25/month (paid annually), $11.99/month (paid monthly)
Business: $24.99/month (paid annually), $28.99/month (paid monthly)

We would need to offer and display the options at checkout, so the user would need to select if they want to pay annually or monthly, and be clearly shown the discount for paying annually.

**Comment by apeatling** [comment]
Here's how I think we can offer this selection. It should be show as a modal on the checkout page:

![screen shot 2016-08-15 at 11 08 41](https://cloud.githubusercontent.com/assets/1464705/17674054/b3240bcc-62d8-11e6-8889-e21bd7479ba5.png)

**Comment by lamosty** [comment]
Nice.

Q: the modal would show up after going to the checkout step automatically? Or would the user need to perform some action to open it?

**Comment by apeatling** [comment]
No, it should show automatically and require a selection to proceed to the checkout.

**Comment by apeatling** [comment]
On different plans, the three checkmarks should be three things that differentiate that plan from the lower plans.

**Comment by artpi** [comment]
Do we intend to test this? Because I believe this would be very dangerous

- It raises possibility of missed subscription renewal 12 times ( card cannot be charged, over limit, etc. )
- I strongly believe it will make people cancel on a whim much more often - having to renew 12 times a year we will stumble onto someone's tough month and decision to resign "just for now" and never come back
- It will create more load on our support tickets
- It will create a mismatch between domain renewal cycles and plan renewal cycles
- It will create a perfect venue for scammy short-lived websites. I can pay only for 1 month for ephemeral campaign website WITH a free domain. Do we want to encourage that?

IF we intend to test this, how long do we run it?
Since the repercussions of such test could have impact for a whole year after subscribing ( high possibility of people leaving in the middle of the year ), how do we design a test?

IF we don't test this, how are we addressing the dangers?

I actually see both pros and cons of this approach, but I think the biggest headache will be devising a plan to test it.

**Comment by apeatling** [comment]
> Do we intend to test this?

Yes we should absolutely test this and look at the areas of potential impact that you mention above. It's possible this change may look good up front but be worse over the long term.

> It will create a perfect venue for scammy short-lived websites. I can pay only for 1 month for ephemeral campaign website WITH a free domain. Do we want to encourage that?

If you do not maintain the payments, then you lose the domain, as mentioned in the screengrab. We would gain control of it.

Open to ideas for testing it. As an aside, this is something all of our competitors offer, but strongly encourage year long subscriptions.

**Comment by kriskarkoski** [comment]
@wensco Do you know what the ICANN rules are around monthly domain renewals? I seem to remember there being rules about keeping control of the domain for the remainder of the period or if you're required to cancel it, but I can't find them at the moment? Obviously we want to provide a buffer for people to renew after it expires, but I don't know what the ICANN rules allow us to do for the domain itself.

**Comment by wensco** [comment]
Hey @kriskarkoski  - thanks for the ping on this. :)

Domain renewal pricing is up to each respective registry. No registry that I know of offers anything less than a 1-year registration term. ICANN requires that the registrant be able to use, manage, transfer, renew, etc their domain for the full registration term.

ICANN requires a registrant to pay for a domain registration and **once they pay, it's theirs to do with as they like until their registration term expires**. 

This is similar to the issue that came up a while back when we were considering offering free plan trials including a domain. Tl;dr was that there is not a way offer a free domain for a limited time period and then compel the registrant to pay if they want to keep it. 

If we want to offer monthly plan payments with the option to cancel at any time _and_ we want those plans to include domains, we will have to let the user keep the domain if they cancel their plan.

**Comment by m** [comment]
I'd like to reiterate I'd love a much lower priced Personal plan.

**Comment by p3ob7o** [comment]
I agree with @wensco, taking control of a user domain name once we have registered and before expiration it is impossible.

Wendy mentions: "ICANN requires a registrant to pay for a domain registration"

Actually, it goes a bit further, ICANN requires the Registrant (in this case Automattic) to guarantee they have perceived full payment for the domain name registration at the moment the domain is registered. It's the same reason that makes it impossible to offer free domains with a free trial.

The only option we have here is to limit the domain offer to TLDs that do not have to follow ICANN rules, which limits us to ccTLDs, including some that are used as generic (.me, .co, etc). For these, we might be able to negotiate an agreement with the respective registries, but that's not guaranteed as the fight against domain tasting has set tight limits around such practices.

**Comment by apeatling** [comment]
Let's move this to a P2 to discuss further. @mattm Thanks for the offer, I will follow up there.
