### ISSUE TITLE
Gifting Banner displays all the time instead of near expiration

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#73252]
### Quick summary

A user reported this in chat: 38774445-hc
Seems potentially related to this change: https://github.com/Automattic/wpcomsh/pull/1198/files

The Gift a WordPress.com Subscription banner was displaying on their site still despite their plan renewing 15 days ago. I confirmed this behavior in an incognito browser while logged out. I also tested this on a Simple and Atomic test site that are 10+ months out from renewal, and both displayed the banner at all times. 

According to the [doc](https://wordpress.com/support/gift-a-wordpress-com-subscription/), this should only begin to appear once your subscription is close to expiring. This will be within 54 days for annual plans and within 5 days for monthly plans.

A simple workaround is to disable the setting to hide the banner at all times.

### Steps to reproduce

1. Create a Simple or Atomic test site or test on an existing site that is not within the timeframe for when the banner should display.
2. Under Settings > General, enable Allow site visitors to gift your plan and domain renewal costs.
3. Save.
4. Review site to see banner displayed (Gift the author a WordPress.com plan.)

### What you expected to happen

The banner should only begin to appear once your subscription is close to expiring. This will be within 54 days for annual plans and within 5 days for monthly plans.

### What actually happened

The banner seems to display at all times and not within the timeframe it should. 

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by ccwalburn** [comment]
Another report here: 40772264-hc

**Comment by louinel** [comment]
Another report here: 5987237-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Simple and AT sites, both of whom don't expire until May 2024
- Gifting banner appears at the top of both sites

**AT Example**

![Markup on 2023-03-09 at 09:21:43](https://user-images.githubusercontent.com/27249804/224086817-c2a9e049-5099-40a7-a798-7f3a60006956.png)

![Markup on 2023-03-09 at 09:21:19](https://user-images.githubusercontent.com/27249804/224086798-763ee82d-0d0a-4801-93c1-1c28ed852685.png)

**Simple Example**

![Markup on 2023-03-09 at 09:20:52](https://user-images.githubusercontent.com/27249804/224086870-ece30fe1-e5e8-4785-b0e2-da9495e02827.png)

![Markup on 2023-03-09 at 09:20:18](https://user-images.githubusercontent.com/27249804/224086984-ac79f039-790d-4721-8f48-a3bfd3239f51.png)


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by mgozdis** [comment]
Another report 23688628-hc

**Comment by lupus2k** [comment]
Hey @mgozdis, I did some research about it, and I saw the Gifting toggle automatically turns it on when the user reaches the date to expire (5 for monthly / 54 for yearly) only if the user never changes the status of the toggle.
We discussed it here: p1671220272056839-slack-CKZHG0QCR

We may need to add some details to [the docs](https://wordpress.com/support/gift-a-wordpress-com-subscription/)

To make it more clear, for example, in a site with a monthly plan and auto-renew off that never changed the toggle on settings:
- 6 days before the expiration date, the banner will not show.
- 6 days before the expiration date, the toggle shows disabled.
- 4 days before the expiration date, the banner will show.
- 4 days before the expiration date, the toggle shows enabled.

But if the user changes the toggle at least once, the banner will reflect the toggle and will not change, no matter the date-to-expire logic.

Do you think changing the docs would help to resolve this issue?

**Comment by mgozdis** [comment]
Hi @lupus2k 👋  I think updating the docs would be the easiest, but not sure what is best. It sounds like the logic works  correctly as long as the user never toggles it on their own. Users may not want the banner to show at all if they never toggle it or opt-in to it displaying. 

The few interactions I've had with users on this were expecting it to work as stated in the docs and only display close to expiration when enabled. They all seemed fine with turning it off when they no longer wanted it to display.

**Comment by lupus2k** [comment]
Hey @mgozdis, we made changes to [the doc](https://wordpress.com/support/gift-a-wordpress-com-subscription/), and we sent it to translate to all languages.
We updated this part of the documentation:

> By default, the banner will appear on websites near their expiration date (within 5 days for monthly plans, 54 days for annual plans) and have auto-renew turned off. However, you can change this behavior by visiting https://wordpress.com/settings/general and adjusting the Gifting Banner setting. Once you make changes to this setting, the banner will no longer use the expiration window logic.
