### ISSUE TITLE
Stats: Post details page fails to render an appropriate title for the "Home page / Archives"

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#73251]
![Image](https://user-images.githubusercontent.com/4044428/218194463-71be0488-cf8b-4f12-ace7-bbb2a19542b4.png)

This bug occurs at `/stats/post/0/:siteSlug` for all sites.

**Comment by jsnmoon** [comment]
cc @dognose24

**Comment by kangzj** [comment]
Hey @dognose24 I would appreciate it if you could fix this for Odyssey as well - Odyssey doesn't even have the title `Home page / Archive` shown in the Nav 😄

**Comment by dognose24** [comment]
There were [two issues reported](https://github.com/Automattic/wp-calypso/issues/70671#issuecomment-1363531011):

> <img width="1090" alt="image" src="https://user-images.githubusercontent.com/4044428/209253990-60e8dcca-11f7-4c38-9643-54819d75bf01.png">
- [x] All-time stats card of the Highlights section is broken for "Hompage / Archives".
- [x] The empty "likes" card is missing the "There are no likes on this post yet" copy.

**Comment by dognose24** [comment]
> Odyssey doesn't even have the title Home page / Archive shown in the Nav

It is fixed within the PR as well. 😄

<img width="1273" alt="截圖 2023-02-17 上午5 52 15" src="https://user-images.githubusercontent.com/6869813/219495563-059ea4a1-c92b-4569-8418-5fb01efbceec.png">

**Comment by dognose24** [comment]
> Odyssey doesn't even have the title Home page / Archive shown in the Nav

@kangzj It is fixed within the PR as well. 😄

<img width="1273" alt="截圖 2023-02-17 上午5 52 15" src="https://user-images.githubusercontent.com/6869813/219495563-059ea4a1-c92b-4569-8418-5fb01efbceec.png">

**Comment by dognose24** [comment]
Closed with #73459.
