### ISSUE TITLE
Gallery Block missing settings

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#73262]
### Quick summary

Gallery Block is not showing image cropping and description settings. 
![Screenshot on 2023-02-12 at 18-37-32](https://user-images.githubusercontent.com/10124024/218351937-84ed90f8-9718-4469-8d18-98c0914b6d2e.jpg)

### Steps to reproduce

1. Add Gallery Block
2. Add images
3. Open the settings menu and try to make changes. 

### What you expected to happen

Should see settings for cropping and descriptions. 

### What actually happened

No settings

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Theme: Argent

**Comment by zachspears** [comment]
Forgot to add Ticket: 5950557-zd-woothemes

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple -  Could Not Replicate 
- Tested on AT -  Could Not Replicate 
- Tested on Self-hosted - Could Not Replicate 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to replicate with various images, and with Gutenberg plugin active/inactive


📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
