### ISSUE TITLE
Change one-off first-party theme purchases to be part of premium plan

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#73265]
# Description
See [Removing One-Time Theme Purchases] pekYwv-FL-p2

![image](https://user-images.githubusercontent.com/5665959/218370551-2de23427-95b0-48cf-bcb6-ba12469345ca.png)

I believe the first effort on this is to remove one-off sales of themes in the logged-out showcase (e.g. the `with-theme` flow). Stop selling individual themes at the very least in with-theme flow and instead enforce premium plan purchase with that theme in the flow.  Confirmed with this 14 Feb 2023 this statement from @ianstewart p1676324031389709/1676323802.999559-slack-C048CUFRGFQ

# Tasks
Verify these with Ian or additional research before starting dev work
- [ ] Look for examples of flows that prompt for the premium plan -e.g. certain themes. Or similarly biz/eCommerce themes that prompt for a plan purchase.
- [ ]  In LoTS, replace the one-off purchase of first party themes with a prompt to purchase the premium plan.

@Automattic/lego

**Comment by BogdanUngureanu** [comment]
Handled in https://github.com/Automattic/wp-calypso/pull/76773
