### ISSUE TITLE
Site Assembler: Improve the UX (feedback from CfT PA in logged-out Theme Showcase

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#73268]
#### Description

Referring to pdtkmj-13U-p2#comment-1884, we can do the following things to let users have a better understanding of the pattern assembler

* It’s not intuitive that I can’t (or why I can’t) “edit” the content in this assembler.
* It’s not intuitive when in the “Add Sections” portion that clicking the Done button will result in the patterns being listed in the left sidebar where they can then be moved/replaced/removed
* Once I’ve added all my pieces, rather than “Continue” at the bottom of the left sidebar, could it be more explicit? What exactly is going to happen when I click on that Continue button? I could see someone accidentally clicking Continue thinking it would move them on to the next section.
* We found it a little difficult in the sidebar on the left to distinguish where one section ends and the next begins. Maybe there should be a clearer border/spacer between them?
* On small screens, maybe it would be better to redirect them to My Home, where they have a structured site setup checklist to work through? Not sure it makes sense to redirect directly to the Site Editor. The Pattern Assembler invites the user to put their template together, but then we drop them into an empty Site Editor.
* You’re then taken to the Site Editor… but it’s not clear what to do next.

#### Acceptance Criteria

- [ ] Let users know they cannot edit the content in the large preview, but they're able to edit the content when they're proceeding to the site editor
- [x] Maybe a better way to let users know they can move/replace/remove the section patterns
- [x] An explicit copy to let users know what will happen when they click on the "Continue" button
- [ ] Maybe increase the gap of patterns in the sidebar
- [ ] Maybe hide the CTA on small screens or update the copy to make it clear
- [ ] Maybe show the launchpad modal first to let users know what to do next, e.g.: Launch, Edit the content, etc.

**Comment by taipeicoder** [comment]
cc: @davewhitley

**Comment by miksansegundo** [comment]
@davewhitley, I'll use this issue to add my feedback:

1. **Add a description under the `Add patterns` header** 
Introduce the concept of patterns and clarify that they can click multiple times to add patterns.

<img width="313" alt="Screenshot 2566-02-24 at 14 09 36" src="https://user-images.githubusercontent.com/1881481/221115287-7a8a65d9-d476-48a7-95bb-41b70d5abd0d.png">

2. **Add a notification when patterns are added as the editor does**

<img width="301" alt="Screenshot 2566-02-24 at 14 08 24" src="https://user-images.githubusercontent.com/1881481/221115202-3b494da6-e550-41b8-8f3c-20b1a2b68994.png">

3. **Add more information for new users (good-to-know things)** 
For instance, add ℹ️ tooltips with insights or bits of knowledge in certain areas like "You can edit everything (content and styles) in the WordPress editor later", "You can find your homepage in the Home template in the WordPress editor"...

4. **Add an inner shadow at the end of the list of selected patterns when the scroll is available**

https://user-images.githubusercontent.com/1881481/221111060-3f7b970e-9bf3-4c9f-be5b-ea83d270877c.mov

**Comment by taipeicoder** [comment]
Closing this since it's outdated. See the latest effort in pekYwv-2u4-p2
