### ISSUE TITLE
Conversion: Test a more prominent upgrade link for free users older than X days

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7327]
This will be a controversial one, but we should look at (and communicate the reasons why) adding a prominent upgrade link for free users. The user should be older than brand new, but still inside their first week of WordPress.com usage where they are the most engaged.

The upgrade link should convey more value and understanding of our plans than just clicking on the "Plans" link in the sidebar. Otherwise it is somewhat redundant.

**Comment by rralian** [comment]
@apeatling Did you have an idea for what this should look like and where it should go? We had a PR that would have added an upgrade link to the masterbar (https://github.com/Automattic/wp-calypso/pull/7301), but the feedback there was pretty negative and we closed it.

**Comment by apeatling** [comment]
We really need some designers for this one. I think along with #7331 we should sit down and brainstorm ideas for this at the GM.
