### ISSUE TITLE
Launchpad: Small UI improvement Progress Circle

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#73273]
In order to make the fonts more readable in the circle we could do the following changes:

* Change to system-font
* 15px
* Increase the whole circle to 52px

![Image](https://user-images.githubusercontent.com/7931304/218521835-69c87363-6355-44aa-bc76-26cc571b5407.png)

Figma: 9wpoYJrMlYKAKUYvVBMN74-fi-2198%3A35829

**Comment by edanzer** [comment]
Tests as expected. It can be hard to do pixel-perfect comparisons from screenshots. But based on screenshots in this PR and the linked issue, the new circular progress bar styling looks like it matches expected new designs, adjusts as expected on mobile, and generally looks good!
