### ISSUE TITLE
Contact Form: Form Block loads blurred before clarifying

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#73286]
### Quick summary

One of our customers reported that their Form Block was blurred when the page loaded, like this:

![Capture_2023-02-13 at 16 18 00](https://user-images.githubusercontent.com/2912202/218502759-ba21eedc-0935-4368-92d0-cdae14f1f156.jpeg)

The rest of the page loaded fairly quickly, except for this Form Block. I deactivated the AMP plugin, and this seemed to allow the Form Block to load, although it still started loading blurred, and then clarified as if this were a large image that was still loading into the page.

The customer's site uses the Gateway theme so I tested this on one of my test sites using both the Gateway and Blank Canvas themes. In both cases, the Form Block started loading blurred, and then clarified, like this:

https://user-images.githubusercontent.com/2912202/218503423-1c529956-6697-4b18-afd2-e29187bfde19.mp4

Is this expected behavior or is something slowing the Form Block's load?

This issue persists if I disable Lazy Images.

### Steps to reproduce

1. Visit a page with a Contact Form
2. Reload the page
3. Observe the Form Block loading blurred, and then clarifying

### What you expected to happen

I'd expect the Form Block to load clearly from the initial load.

### What actually happened

Instead, the Form Block is blurred initially, and then clarifies.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

The customer reported the issue in 5954151-zen

I reproduced this issue using - 
- Edge v110.0.1587.41
- Chrome v110.0.5481.77
- Firefox v109.0.1 

I'm running macOS 13.2

I was able to reproduce the issue on these pages:

- My personal site: https://pauljacobson.me/contact-me/ (self-hosted WP.org site on Pressable)
- My test site: https://atomicpljcbsn.blog/gateway-form-test/ (a WordPress.com Business plan site)

**Comment by pauljacobson** [comment]
It looks like the original issue was investigated here: https://github.com/Automattic/jetpack/issues/28883 and a patch is being released within the next 24 to 48 hours.

I'll close this issue in favor of the other one.

**Comment by jcheringer** [comment]
Hey @pauljacobson!
Just to clarify, the blur effect that appears briefly is intended behavior.
The issue we're handling on https://github.com/Automattic/jetpack/issues/28883 is for some sites where the blur effect was never removed.

**Comment by pauljacobson** [comment]
> Hey @pauljacobson! Just to clarify, the blur effect that appears briefly is intended behavior. The issue we're handling on [Automattic/jetpack#28883](https://github.com/Automattic/jetpack/issues/28883) is for some sites where the blur effect was never removed.

Thanks @jcheringer. I can see that. This particular report started out as the same issue as the one being handled over at Jetpack.
