### ISSUE TITLE
Conversion: Adjust Free plan in Signup flow

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7328]
The free plan in the signup flow is very prominent. We should explore ways to encourage users to select a paid plan in the flow, without causing confusion and killing overall signup conversion.

**Comment by artpi** [comment]
One of the avenues:

## Sorting plans in price decreasing order

https://github.com/Automattic/wp-calypso/pull/7463

**Comment by artpi** [comment]
Sorting plans in decreasing order abtest is running in p3fqKv-3rm-p2

**Comment by artpi** [comment]
Test was kind of a failure. ( p3fqKv-3C3-p2 )
Closing this issue.
