### ISSUE TITLE
Users: Subscriber Search doesn't work

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#73295]
### Quick summary

Searching for a user on the Subscriber tab of the Users section of the dashboard shows zero results when I search for any username on the Subscriber tab

### Steps to reproduce

1. Go to the Users section of the dashboard
2. Click on the Subscriber tab
3. Click the Search icon and the search bar will expand with the instructions "Search by email..."
4. Enter the username or email of one of the subscribers in the Search bar

### What you expected to happen

- I expected the instructions to allow me to search by either username or email since the WordPress.com subscribers and external subscribers are all combined on this tab now and the user may not have access to the emails of the WordPress.com subscribers. (And, since the users are listed by username!)
- I expected the search to return the subscriber as a result

### What actually happened

I got a message "No results found"

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes
I tested on two of my own sites and two user sites and get the same results.

5941705-zen

_No response_

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: Not replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated exactly as described above on both Simple and AT sites.

**AT Example**

https://user-images.githubusercontent.com/27249804/221078180-2d1c13c0-156e-4921-a4f2-b219ad67b5b2.mov

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by jp-imagines** [comment]
Fairly sure I ran into this with a user in 6404831-zd-woothemes, though there may have been some other weirdness going on there in this particular case (possibly because the subscriber subscribed to the site by email before creating a WPcom account with the same email).

**Comment by cuemarie** [comment]
The recent updates the Subscribers pages included improvements to search, and I can no longer replicate this issue. 

Internal ref: p7DVsv-hGI-p2

📌 ACTIONS
- Closing as resolved
