### ISSUE TITLE
Launchpad: Add link back to design picker

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#73297]
### Details

For flows (including general onboarding) that have a 'design picker' step, we want to enable a link on the launchpad screen back to that step so users can change their designs.

**Comment by Addison-Stavlo** [comment]
is this now complete with https://github.com/Automattic/wp-calypso/pull/73401 ?

il close assuming, but feel free to reopen this issue or create a new one if there are follow ups to track.
