### ISSUE TITLE
[WooExpress] Calypso home is loaded after completing signup

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73307]
### Quick summary

After completing the `/setup/wooexpress` signup flow, we end up loading the Calypso home page at `/home/:siteSlug`. We should be redirected to the WooCommerce home page, which suggests that WooCommerce may not be fully installed by the time we wrap up the signup flow.

### Steps to reproduce

1. Visit `/setup/wooexpress`
2. Wait it out - you may or may not be redirected to WooCommerce home after the flow completes

### What you expected to happen

I should have been redirected to the WooCommerce task list in the WooCommerce home page.

### What actually happened

The page did not redirect and I stayed on the Calypso home page.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by markbiek** [comment]
> Available workarounds?
> Yes, easy to implement

@daledupreez What was your thinking for a workaround here?
