### ISSUE TITLE
Viewer of a private site can't see images 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#73306]
### Quick summary

A viewer that's invited to the private site cannot see images in pages or posts, unless the blank spot (where the image should be at) is right clicked and opened in a new tab. 

### Steps to reproduce

1. Add images to pages and publish. 
2. Set the site to private. 
3. Invite a Viewer user to the private site. 
4. Log in as the Viewer and open the private site to check the images on the pages. 

### What you expected to happen

Even the site is private, the images should be visible in pages and posts for the Viewer as they're invited to the site. 

### What actually happened

The images in pages and posts are not visible to the Viewer unless it's right clicked and opened in a new tab, then the image will display. 

![Screen Shot on 2023-02-14 at 09:11:19](https://user-images.githubusercontent.com/36863633/218676957-6b4eee0a-09da-4572-aca6-ae7116b1e608.png)

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I logged in as the viewer to the user's site and can't see images. I also invited my test account as a viewer to the user's private site, but can't see their images. I tested this in Chrome, Firefox and Safari. 

User report: 5953919-zd

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on P2 -  Could Not Replicate 
- Tested on Simple - Could Not Replicate 
- Tested on AT - Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
- There's a similar issue with Atomic here https://github.com/Automattic/wp-calypso/issues/52520

📌 ACTIONS
- Await author feedback


📌 Message to Author
- @kspilarski I have not been able to replicate this. If you are able to, please share more details about the plan, site, etc. Thanks

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Tested once more - on my simple test site set to "Private", images are visible to "Viewer" users on the site.
- Closing report due to stale conversation/unable to reproduce. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
