### ISSUE TITLE
Task: Update the font and subtitle for the Plans and My Plan pages when in the eCommerce trial

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73314]
### Details

During a recent walkthrough, the design team flagged that we'd missing some updates to the header section in the Plans and My Plan pages.

**Design:** lD0gTB4IqGsmSmsnjZNaP6-fi-1%3A144&t=8p6bh7aUi3aYaka7-0

### Checklist

- [x] When we're in the eCommerce trial, the page title should use the `proxima-nova` font, or fall back on a sans-serif font (it is the WooCommerce brand font)
     - We may want to try and push this into a variable if we can
- [x] When we're in the eCommerce trial, the subtitle should read `See what's available on your plan.`
- [x] As a bonus, we should ensure that the background for the main content (below the header section) is plain white, and not a very light grey

**Comment by sixhours** [comment]
> When we're in the eCommerce trial, the subtitle should read "See what's available on your plan."

The designs show the current subheading in production, which is "Discover what's available in your Woo Express plan." so I'm going to leave this for now!

**Comment by sixhours** [comment]
This was deployed in #75842
