### ISSUE TITLE
Task: Update spacing on My Plan page for eCommerce trials

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73319]
### Details

During a recent walkthrough, the design team noticed that there are a number of issues with spacing in the My Plans content. It may make sense to tackle this across multiple PRs or a single PR, but I think it's simpler to keep most of the spacing issues together.

The issues can be loosely grouped by part of the page as follows:
 * General mobile layout: the left and right padding should be 20px
 * _What's included_ grid:
   - The horizontal and vertical gutters should stay at 24px in desktop view, and the content should resize
   - The vertical gutters should stay at 16px for mobile displays
   - On overflow, we should left-align grid items rather than having them fill the horizontal space on the last row
   - The spacing between the header in each grid item and the text copy should be 8px
   - The spacing between the text copy in each grid item and the action link should be 20px on desktop and 12px on mobile
   - The icon for each grid item should be reduced to 48px on mobile
 * _Ready to start selling_ section\
   - The header should have 80px of spacing between it and the previous grid
   - There should be a 12px gap between the _Ready to start selling_ header and the subtitle
   - There should be a 60px gap between the end of the grid and the CTA on desktop, and a 32px gap on mobile
   - For each item in the grid, there should be an 8px gap between the header and text copy on desktop, and a 2px gap on mobile
   - There should be 16px horizontal padding between the icon/image and text in each grid item when on mobile
   
Walkthrough: peapX7-1DZ-p2
Design: lD0gTB4IqGsmSmsnjZNaP6-fi-470%3A11560&t=8p6bh7aUi3aYaka7-0

### Checklist

- [ ] The implementation should match the designs more closely

**Comment by that-mike-bal** [comment]
@daledupreez  I copied this over to 73311 and included feedback from Beau. It think it makes sense to just have someone go through and cleanup that page in a single issue/session vs splitting it across people and working sessions. Let me know if I'm wrong. If you agree, we can close this one out

**Comment by daledupreez** [comment]
I've just worked through the details in #73311 and consolidated the issues. I am going to close this issue as a result.
