### ISSUE TITLE
Task: Improve time remaining calculation in eCommerce trial banner

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73312]
### Details

It's possible that our calculations in the `ECommerceTrialBanner` component for computing `trialProgress` results in a value < 0. We noticed this in a walkthrough due to the progress "ring" being dots, one at 12 o'clock and a second at ~11 o'clock.

Walkthrough action items: peapX7-1DZ-p2

### Checklist

- [ ] Ensure trialProgress is between 0 and 1.

**Comment by valterlorran** [comment]
I checked this issue, and the logic behind it seems solid. The only way the `trialProgress` to be less than 0 is if the days left for the trial be greater than the trial duration. In that case, it would show two dots, indeed.

**Test hardcoding 15 days left on trial**
<img width="1148" alt="Screen Shot 2023-02-15 at 15 29 41" src="https://user-images.githubusercontent.com/1234758/219120226-231303c2-77e7-48d6-a08f-37e6a3e3b260.png">

https://github.com/Automattic/wp-calypso/blob/5cc12ce9106e31695b1baa3405e45c072086266e/client/my-sites/plans/ecommerce-trial/ecommerce-trial-banner/index.tsx#L44

**Comment by valterlorran** [comment]
This was closed by #73435
