### ISSUE TITLE
Task: Update Spacing around components on My Plan page

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73311]
### Details

- [x] We should remove the left and right padding from the `DoughnutChart` component we use in the banner on the Plans and My Plan pages. This will result in the content being truly right-aligned in the card. -- #75975
- [ ] We may also need to right-align the text label below the image.
- [x] We need to add padding to the bottom of the "Upgrade Now" button as it currently sites on the bottom of the screen  -- #75726

![Image](https://user-images.githubusercontent.com/89872780/224372126-27a21c1e-464e-4a0f-9814-148789a9d9e0.png)

During a recent walkthrough, the design team noticed that there are a number of issues with spacing in the My Plans content. It may make sense to tackle this across multiple PRs or a single PR, but I think it's simpler to keep most of the spacing issues together.

The issues can be loosely grouped by part of the page as follows:

*General mobile layout:*

- [x] the left and right padding should be 20px -- ETA: I'm seeing 20px left and right on mobile devices already, maybe this was fixed earlier?

*_What's included_ grid:*

All of these should be handled by #75981

- [x] The horizontal and vertical gutters should stay at 24px in desktop view, and the content should resize
- [x] The vertical gutters should stay at 16px for mobile displays
- [x] On overflow, we should left-align grid items rather than having them fill the horizontal space on the last row
- [x] The spacing between the header in each grid item and the text copy should be 8px
- [ ] ~~The spacing between the text copy in each grid item and the action link should be 20px on desktop and 12px on mobile~~ (There is no action link in the current variation)
- [x] The icon for each grid item should be reduced to 48px on mobile

*_Ready to start selling_ section*

All of these should be handled by #75984

- [x] The header should have 80px of spacing between it and the previous grid
- [x] There should be a 12px gap between the _Ready to start selling_ header and the subtitle
- [x] There should be a 60px gap between the end of the grid and the CTA on desktop, and a 32px gap on mobile
- [x] For each item in the grid, there should be an 8px gap between the header and text copy on desktop, and a 2px gap on mobile
- [x] There should be 16px horizontal padding between the icon/image and text in each grid item when on mobile

Walkthrough: peapX7-1DZ-p2
Design: lD0gTB4IqGsmSmsnjZNaP6-fi-470%3A11560&t=8p6bh7aUi3aYaka7-0

**Comment by sixhours** [comment]
All of these fixes have been shipped!
