### ISSUE TITLE
Task: Update font sizes for Plans and My Plan pages

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73321]
### Details

This work is grouped as a single task because we need to interact appropriately with the Calypso font size checks and restrictions, so trying to handle this via a single task may be better to get that worked out correctly first.

Regardless, we want to update font sizes for various components as follows:
* My Plan
  - The action links in the _What's included_ section should be 13px, not 12px
  - The body copy for the grid items in the _What's included_ section should be 13px on mobile
  - The "Upgrade your free trial…" text should be 13px
  - The inner items in the "selling list" should be 13px
* Plans
  - The headlines in the accordions should be 18px
  - The body font in the accordions should be 13px, not 12px

### Checklist

- [ ] The fonts in the My Plan page should be the right sizes
- [x] The fonts in the Plans page should be the right sizes

**Comment by nelsonec87** [comment]
Related PR https://github.com/Automattic/wp-calypso/pull/73819

**Comment by that-mike-bal** [comment]
@daledupreez idk if we still need this one since we have to redo this pages to match the designs anyway. Can you confirm we'd actually be tracking this in another issue? - even if I still need to create said issue.

**Comment by chihsuan** [comment]
https://github.com/Automattic/wp-calypso/pull/75605
