### ISSUE TITLE
Launchpad: Improve Parsing of Query Params

### ISSUE THREAD

**Issue by sharpirate** [Automattic/wp-calypso#73341]
### Summary
Currently, we are reading some of the URL Query params directly from the URL string which is not the best approach:
[Example 1](https://github.com/Automattic/wp-calypso/pull/72880/files#diff-8ed61e0c0ac4b866b1a59c2205eec908e764cc51908450e48c5ee367ac05b466R53)
[Example 2](https://github.com/Automattic/wp-calypso/pull/72930/files/1456fb20c4e20ff4ad66be8af364a10e8ed85cd8#diff-e7abd0fc6c4b37d4d7e47d5be213f381deed85ab92b3ebcc0f7e4bc789962e04R51)

### Goal
We should explore ways to improve this and parse query parameters in a more declarative way. Options might include useQuery hook within stepper, useLocation hook (from react-router-dom, which useQuery uses), something like new URLSearchParams(location.search) etc.

We should refactor the two examples noted above along with any other places we might be using this current approach.

**Comment by edanzer** [comment]
This task is being handled via three separate PRs. Last one should be deployed shortly: 
https://github.com/Automattic/wp-calypso/pull/73465
https://github.com/Automattic/wp-calypso/pull/74020
https://github.com/Automattic/wp-calypso/pull/73975

**Comment by edanzer** [comment]
Marking this as complete now.
