### ISSUE TITLE
Marketplace: Add default icon in case product doesn't have icon image

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#73359]
### Details

In marketplace paid plugins, some products don't have app icons. The plugin listing page shows the default icon when a product doesn't icon. We should do the same when loading the same plugin on the plugin details page. 

#### Plugin List
![Image](https://user-images.githubusercontent.com/86406124/218948139-a1121cf3-6074-4025-9bb6-50082d37cfbb.png)

#### Plugind Details
![Image](https://user-images.githubusercontent.com/86406124/218948046-3e165300-7508-49c7-94d6-882b809e4c9d.png)

**Comment by cpapazoglou** [comment]
After adding the default icon in Plugin Details let's try adding a real icon too 😁

**Comment by gavande1** [comment]
I've tried adding a real icon in WCCOM but it's not syncing back to the shadow side for some reason. I will investigate why it's not syncing correctly soon.

**Comment by cpapazoglou** [comment]
Adding a space in Product Icon Url hitting save and then removing and saving it again seems syncing the value to the shadow DB.



![Image](https://user-images.githubusercontent.com/12430020/220426317-57f24e80-091c-4c8e-a6bb-bd81b3256eec.png)





![Image](https://user-images.githubusercontent.com/12430020/220422779-df7e14f4-8572-494e-873e-80c354c2c135.png)

Will try now fixing also
- AutomateWoo - Refer A Friend add-on
- WooCommerce Gift Cards

**Comment by cpapazoglou** [comment]
Done 


![Image](https://user-images.githubusercontent.com/12430020/220423564-008edbcf-7472-403b-9c2e-1f1635c81950.png)



![Image](https://user-images.githubusercontent.com/12430020/220423594-aeaff002-3962-4f13-86f7-e14c97102f5b.png)

**Comment by gavande1** [comment]
Great work Harris! I did not remove the value prior to updating the products. That might be the issue with values didn't sync back to the shadow site. I think we can close this now!
