### ISSUE TITLE
Bug: Ensure WooCommerce "Add a domain" task supplies a suggestion

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73393]
### Details

For eCommerce trial sites, users haven't selected their domain name - we generate it for them. However, the `/domains/add/:siteSlug` page uses the site slug as the default search term if no other suggestion is supplied.

We should update the "Add a domain" task to use the site title as the search term via the `suggestion` URL parameter. We should likely do this whenever the site slug starts with `woo-` or `wooexpress-`.

### Checklist

- [ ] When clicking on the "Add a domain" task for an eCommerce trial, I get reasonable results

**Comment by that-mike-bal** [comment]
Use site title for a recommendation.
