### ISSUE TITLE
Research e2e test failures caused by launchpad_screen=full on test site

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#73405]
Discussion in p1676498959797489-slack-C1A1EKDGQ

## Description
- e2eflowtesting5.wordpress.com

## What we expect from the fix
* We've figured out how `launchpad_screen` was set to `full` on the e2e test suite.
* Any next steps are identified, with GitHub issues created correspondingly.

**Comment by jeyip** [comment]
No further reports have been made after merging https://github.com/Automattic/wp-calypso/pull/74451
