### ISSUE TITLE
Jetpack Cloud: Plugins page incorrectly says Jetpack is managed

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#73403]
### Quick summary

Jetpack is listed as a managed plugin. How is this determined?

### Steps to reproduce

1. Visit a self-hosted Jetpack site's plugin page via cloud.jetpack.com
2. See Gutenberg, Akismet, Jetpack, etc listed as "auto managed" even though it isn't.

### What you expected to happen

Plugins not be displayed as managed when not an Atomic host.

### What actually happened

Atomic managed plugins listed as such.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

![2023-02-15 at 4 25 PM](https://user-images.githubusercontent.com/88897/219199741-63130ee1-55ae-4773-a8a6-1843d79ef278.png)

**Comment by kraftbj** [comment]
x-post 1203946504299038-as-1203981105935605

**Comment by jkguidaven** [comment]
The bug with the auto-managed tooltip has been fixed for the self-hosted sites. However, plugins managed by a Host other than WPCOM (e.g., Pressable) will not be detected as auto-managed yet in Calypso.

We will still need to figure out how we can solve this properly. I added a task to our board to further investigate this. 

1202619025189113-as-1204755800257985
