### ISSUE TITLE
Task: Investigate slow progress through WooExpress flow

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73419]
### Details

We've had multiple reports of slowness in the new `/setup/wooexpress` flow. We need to investigate what is taking so long, and identify whether we can improve the performance.

### Checklist

- [ ] Identify the cause(s) of slowness in the flow
- [ ] Work out whether there are any actions we can take to reduce the delay(s)

**Comment by that-mike-bal** [comment]
The API call for adding the free trial is really slow - look into which data center the request is routed through.

**Comment by daledupreez** [comment]
I've done some investigation here -- this _definitely_ looks like it's related to routing. I've asked our systems teams for some guidance: pMz3w-gZU-p2

**Comment by daledupreez** [comment]
We investigated this further and the primary issue was due to us running some write-intensive code that triggered notable lag for the endpoint. Our systems team have helped work around the problem in the short term, but we have identified two follow-up issues:
* Automattic/dotcom-forge#1891
* Automattic/dotcom-forge#1892

I am going to close this issue as a result.
