### ISSUE TITLE
Classic Themes: 'Move to Widget Area' button not working

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#73411]
### Quick summary

When using the 'Move to Widget Area' button in the block widgets toolbar it seems to have no effect.

### Steps to reproduce

1. With a classic theme (with widget areas) active - go to Appearance > Widgets (or widgets area of Customizer)
2. Select a widget so the toolbar is active.
3. Click the 'Move to Widget Area' button (squiggly arrow) and then select an widget area

### What you expected to happen

I should be able to move the widget to another area

### What actually happened

Nothing

https://user-images.githubusercontent.com/1842363/219255007-6843993a-597d-4c3a-a59e-51f9cc1666a3.mov

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

This is present in Simple Sites and Atomic sites _when Gutenberg is active_

**Comment by jordesign** [comment]
This appears to be an issue in Gutenberg 15.1 and is reported here:
https://github.com/WordPress/gutenberg/issues/48113

**Comment by kavyagokul** [comment]
Not sure why this is in 'Needs triage'. Moving to Done.

**Comment by cuemarie** [comment]
Looks like this was resolved by https://github.com/WordPress/gutenberg/issues/48113
