### ISSUE TITLE
Create language strings pack to get them translated early.

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#73439]
### Acceptance Criteria:
- Ensure the designs include the final copies
- Strings to be collected from inDLaEQV8jJ21O4WXawIsJ-fi
- Create a file in Landpack defining static constants for all the collected copies
  - Provide all necessary translation metadata (e.g. "translator" comments)
- Merge into `trunk` so that the strings are picked up for translations

### Related Discussions
- pdDOJh-1uZ-p2#comment-1219
- p1676635937549499-slack-C02TCEHP3HA

**Comment by mashikag** [comment]
Hey @saygunnyc 👋  

We would like to submit all (or at least most) of the new Subscriptions Management portal's copies for translation as soon as possible. This would eliminate the potential of translations becoming our shipping blocker. 

Do you believe all the copies in the designs are considered to be in their final state? In case there is still a bit to go over, we can split-up this task and address the copies section-by-section.

cc @yansern

**Comment by yansern** [comment]
Let's get the existing one in Figma already submitted. We can iteratively change them over time.

**Comment by mashikag** [comment]
> Let's get the existing one in Figma already submitted. We can iteratively change them over time.

I believe this was deprioritized after. We decided we will ship to english only first. Right @yansern ?

**Comment by yansern** [comment]
Yes, we will ship to EN users first.

**Comment by saygunnyc** [comment]
Chiming in here late, but I believe, as of now, (correct me if I'm wrong 😄 ) @michaelpick reviewed all the copy on the UI.
