### ISSUE TITLE
Editor: Prompt to confirm publishing if title is blank

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#7344]
Internal request from @rachelsquirrel (p58i-3W1-p2):

> I sometimes forget to add a title to my blog posts. When this happens the post slug autofills with the post ID. This is irritating because as soon as I realise my mistake I have to add a title to my post and then edit the slug which then means anyone who clicks the link to my post from their inbox will get a 404. Since I’m using publicise it also breaks those links unless I go and delete the shares first and share them again. It also sends this number as the post title in email notifications to followers.
> 
> Can we add a “Are you sure you want to publish this without a title?” alert to the editor? I seem to do this more often than I care to admit but I’m sure I’m not the only one.

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Closing because there is now an "Are you sure?" publishing prompt for every post before publishing
