### ISSUE TITLE
WooExpress: RTL language breaks the ring design

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#73441]
The tip of the progress is flat for RTL languages.

**RTL Languages**
<img width="252" alt="Screen Shot 2023-02-16 at 13 37 00" src="https://user-images.githubusercontent.com/1234758/219430716-d2e70f81-1eee-4b01-b2a5-80a9ca6cf25e.png">

**Other Languages**
<img width="295" alt="Screen Shot 2023-02-16 at 11 19 45" src="https://user-images.githubusercontent.com/1234758/219430976-d8e0a08a-6f02-44e2-ae83-8aa1929c1e3f.png">

**Comment by that-mike-bal** [comment]
@daledupreez - double check to see if it's in progress in another issue.
