### ISSUE TITLE
Fix zIndex at the new domain upsell on editor

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#73445]
Slack thread: p1676569166916009-slack-CKZHG0QCR

Even with zIndex = 1 it still stays in front because it’s outside of the iframe. We’ll need to investigate more how to fix it:

![Image](https://user-images.githubusercontent.com/1044309/219447200-d6e2c4cb-6f7e-4399-911a-03a466e692d8.png)

**Comment by paulopmt1** [comment]
Should we move forward with the new approach [implementing the Post editor domain upsell inside the editor](https://github.com/Automattic/wp-calypso/pull/72944)?

**Comment by lupus2k** [comment]
This approach has some work to do, but it could work because it won't show the upsell over the iframe. Besides that, it will be good to take note of [this suggestion](https://github.com/Automattic/dotcom-forge/issues/1604#issuecomment-1422368324) too

**Comment by allilevine** [comment]
Putting this on hold since the upsell may be removed: p9Jlb4-6AL-p2#comment-7122

**Comment by lupus2k** [comment]
I reopened because we need to merge https://github.com/Automattic/wp-calypso/pull/72944 to finish the task

**Comment by lupus2k** [comment]
Reopened because we reverted [this one](https://github.com/Automattic/wp-calypso/pull/76855) because of a bug (p1684250921623969-slack-C02FMH4G8).

We already created a new PR with a fix [here](https://github.com/Automattic/wp-calypso/pull/76987)
