### ISSUE TITLE
Reskinned Portal: Create a landpack section for reskinned portal.

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#73460]
We need to create a landpack block that includes the subscription management functionality. In this stage, we are going to use the same html found in the subscription management page, but being part of the landpack project it will have the correct header and footer. Later on, we will change the look and feel of this screen.

The actual version can be found going to this url: https://subscribe.wordpress.com/ and it has this look and feel:

![Image](https://user-images.githubusercontent.com/3832570/219496343-dbd3a0ce-969f-482c-aa82-2f45ae455323.png)

For context, the new one will be placed in https://wordpress.com/subscriptions and will have this look and feel (even though this new look and feel is out of the scope of this task):

![Image](https://user-images.githubusercontent.com/3832570/219496823-fa390102-0fa1-4c27-a468-d92c5184f91e.png)

**Comment by yansern** [comment]
Just to note that we are on a 1-2 day spike on Week 7 to understand feasibility. The actual implementation will be on later sprints.
