### ISSUE TITLE
Editor: [code] is not unescaped on edit

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#7346]
When using the Editor and including `[code]` blocks, code comes back as escaped when revisiting the post by editing.

**Steps to reproduce**
1. Create a new post `https://wordpress.com/post/<my-domain>.wordpress.com`
2. Include a block of code

<img width="866" alt="screen shot 2016-08-09 at 3 42 00 pm" src="https://cloud.githubusercontent.com/assets/1922453/17504099/cfc8b482-5e49-11e6-830d-b95cc2edad74.png">

3. Publish the post
4. Edit the post

<img width="656" alt="screen shot 2016-08-09 at 3 42 24 pm" src="https://cloud.githubusercontent.com/assets/1922453/17504116/fd19889e-5e49-11e6-8626-14d2e387048d.png">

**What I expected**
I should see the code in its original form

**What I did see**

<img width="814" alt="screen shot 2016-08-09 at 3 42 50 pm" src="https://cloud.githubusercontent.com/assets/1922453/17504124/26b61154-5e4a-11e6-8777-67a189ec3896.png">

**Note**
This bug does not present itself using `[code]` shortcodes when editing posts via `wp-admin`

**Comment by lancewillett** [comment]
This should be fixed now, see #1109 and #1426.
