### ISSUE TITLE
Task: Add logging to GitHub deploy flow

### ISSUE THREAD

**Issue by mpkelly** [Automattic/wp-calypso#73475]
### Details

It would be interesting to have some logging included because it’s not clear at all for us to track what’s going on. Ideally, we should track the most meaningful steps. At the top of my head:

- The webhook event received (and its content)
- WPCOMSH endpoint called (with its arguments)
- Link of zip ball
- Each removed files
- Each inserted/updated files
- Any errors
- Finished operation

### Checklist

- [ ] Add logging to WPCOM project
- [ ] Add logging to WPCOMSH project

**Comment by zaguiini** [comment]
@mpkelly, I've included some logging on the Atomic part where we're logging the process and eventual errors. I remember that yesterday you were adding some Logstash entries -- I liked that, so I think it'd be appropriate if you added some more logs if you don't think the ones we have are enough 👍 

If you think, feel free to close this issue and call it done

**Comment by p-jackson** [comment]
I've been working on this today. Handing this over to @@zaguiini 
- Here's a diff which proxies the deployment logs through `public-api` so it works on private sites D102343-code
- Here's a wpcomsh PR which stores the logs in a CPT https://github.com/Automattic/wpcomsh/pull/1274

**Comment by zaguiini** [comment]
Thanks, @p-jackson!

As the last part of this issue, let's log the complete process:
- GitHub integration: log webhook call details to Logstash (D102450-code)
- https://github.com/Automattic/wpcomsh/pull/1276

With these changes, temporarily we'll not delete the log file, but this is just a quick solution to the problem. Ideally, we'll log from Atomic to Logstash too.
