### ISSUE TITLE
Ability to redirect request key form operation from subscribe.wordpress.com back to wordpress.com/subscriptions.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73479]
When a form request is made `subscribe.wordpress.com/?action=request_key&v2`,
it should redirect back to `wordpress.com/email-subscriptions?update=keysent`.

Use the existence of the `v2` get param to determine whether to redirect to the new Subscriptions Management page.

**Comment by yansern** [comment]
I scoped this down to `request_key` and renamed the issue. We'll create another issue for general form operations in another planning session.

**Comment by ivan-ottinger** [comment]
> I scoped this down to request_key and renamed the issue. We'll create another issue for general form operations in another planning session.

Thank you! Yes, that should be enough for the initial landing page needs.

**Comment by ivan-ottinger** [comment]
D101549-code patch is now ready for review.
