### ISSUE TITLE
Create a landpack block for Email Sent section.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73478]
**When the user hits submit after entering their email on the email form block:**
 - a call will be made to `subscribe.wordpress.com/?action=request_key`
 - and redirects back to `wordpress.com/email-subscriptions?update=keysent`.

**Email Sent Block:**
- Use `update=keysent` param to display this Email Sent block.
- This Email Sent block should support both desktop & mobile view.

Figma: inDLaEQV8jJ21O4WXawIsJ-fi-712%3A14117&t=tDTLHkYjEJctD075-0

Design:
![Image](https://user-images.githubusercontent.com/1287077/219644744-edb67879-a0c7-4244-a7d1-d690e8696b27.png)

**Comment by yansern** [comment]
Even though the issue description says to create a block, it likely can be just an if...else condition on the existing block.
1223-gh-Automattic/landpack

**Comment by JuanLucha** [comment]
> Even though the issue description says to create a block, it likely can be just an if...else condition on the existing block. [1223-gh-Automattic/landpack](https://href.li/?https://github.com/Automattic/landpack/issues/1223)

Indeed. After talking with @ivan-ottinger and @mashikag , that's what I'll do 👍
