### ISSUE TITLE
Switch to new landing page for EN users.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73486]
When a logged-out user accesses `subscribe.wordpress.com`, redirect the user to `wordpress.com/email-subscriptions`, **but only for users on EN locale**.

Challenge: Is it possible to get the locale of the guest user?

If non-EN user accesses `wordpress.com/email-subscriptions` directly, too bad for now. We didn't advertise it but they knew how to get there. (It's possible to redirect from the new landing page to old if needed, but not a priority.)

~Bear in mind that it might be `wordpress.com/subscriptions` depending on the status of https://github.com/Automattic/wp-calypso/issues/73477.~

**Comment by ivan-ottinger** [comment]
> When a logged-out user accesses subscribe.wordpress.com, redirect the user to wordpress.com/email-subscriptions, but only for users on EN locale.

What we will also need to make sure is that the change will only apply when users navigate to `subscribe.wordpress.com` specifically - the address without any URL parameters. This will make sure the existing requests to are intact.

**Comment by ivan-ottinger** [comment]
Here are some initial thought I had while you were reviewing Juan's PR: D102548-code. It doesn't solve the language yet though.

**Comment by yansern** [comment]
Semi-related patch, I didn't want to create another issue for it.

This patch just redirects logged-in users who access the landing page `/email-subscriptions` back to the old portal.
D102579-code

**Comment by yansern** [comment]
> What we will also need to make sure is that the change will only apply when users navigate to subscribe.wordpress.com specifically - the address without any URL parameters. 

It should redirect at the point when it knows to render the logged-out page `access_denied()`, this will save you a lot of work thinking about the logic.

Also, it can't without any URL parameters as the `locale` param can be used to display in the preferred language, e.g.
`https://subscribe.wordpress.com/?locale=nl`

**Comment by mashikag** [comment]
## My Dev Notes Pt. 1
It seems to me that the language of the subscribe.wordpress.com changes only when the `?locale=${locale}` param is applied to the URL.

Some TODO's for myself:
1. How do new (not logged-in) users get to the https://subscribe.wordpress.com?
2. Is the `locale` param applied to the URL that the new users enter?
3. How does the `_()` decide on the language of the output text?

**Comment by yansern** [comment]
Not particularly subscribe.wordpress.com but for LOHPs, there's some clues in the fieldguide here:
PCYsg-mPd-p2

Just need to find out where in the code is doing that, because I doubt its the generic `get_user_locale()`, it must be something else.

**Comment by yansern** [comment]
Looks like the function is `determine_locale()`.

**Comment by yansern** [comment]
From a team huddle, we discovered that:
 - there is a `subscribe_blog_language` locale filter that overrides the locale based on the provided `locale=` param in the GET request.
    - it also does something else which we are unsure of, related to memberships.
 - non-landpack LOHPs can successfully determine visitor's browser locale and switch to the right language.
   - landpack LOHPs is not determining the correct visitor's browser locale and is still showing in EN.
   - @mashikag will raise that issue to landpack/i18n team.
- we will simply use `get_locale()` to determine if the user is EN, even though it might be from a visitor who's browser language is not-EN.
   - this is because the primary entry to [subscribe.wordpress.com](http://subscribe.wordpress.com/) is coming from email footers where the `locale=` param is already set.
   - and the `locale=`  param will be picked up by the `subscribe_blog_language` filter.
  - so we will respect the value that is returned from that filter.

**Comment by mashikag** [comment]
The patch to redirect the traffic to EN version of the old site (not logged-in) to the new page: D102700-code

**Comment by ivan-ottinger** [comment]
D102700-code is now merged and deployed to production.

**Comment by mashikag** [comment]
> - non-landpack LOHPs can successfully determine visitor's browser locale and switch to the right language.
    - landpack LOHPs is not determining the correct visitor's browser locale and is still showing in EN.
    - @mashikag will raise that issue to landpack/i18n team.


Regading above the following issue was created: https://github.com/Automattic/wp-calypso/issues/73770
