### ISSUE TITLE
Find out what metrics can we measure for the landing page.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73480]
On the subscription management landing page, let's find out:
- What are the metric questions that we should ask & what can be asked on the landing page?
- What trackings already exists on the landing page?
- What trackings need to be implemented on the landing page?

Acceptance criteria:
- We can consider this task done when a P2 is published about this or the findings are written as a reply in this issue.

**Comment by yansern** [comment]
@mashikag and I had a Zoom pairing session to explore the above question, and this is the relevant Slack thread:
p1676630047327969-slack-C02TCEHP3HA

A P2 post will be created to explain in further detail.

**Comment by mashikag** [comment]
The issue was resolved with:
- pdDOJh-1w1-p2
- pdDOJh-1wH-p2
