### ISSUE TITLE
Reskinned Portal: Create a V2 class for Subscription Management.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73483]
Here are the difference between V1 and V2 class.

**V1 class**
 - The class is `Subscription_Management`.
 - The file is `subscriptions-admin.php`.
 - It should contain mostly route-related modifications.

**V2 class**
 - The class is `Subscription_Manager`.
   - The class extends from the V1 class `Subscription_Management`.
 - The file is `subscription-manager.php`.
 - It should contain mostly template-related modifications.

**Tasks:**
 - The V2 class should extend from the V1 class.
 - The V2 class should define a global constant, e.g. `SUBSCRIPTION_MANAGEMENT_V2` at the very beginning of the file.
 - The V1 class should be modified not to self-instantiate and pollute the global `$subscriptions` variable when the constant `SUBSCRIPTION_MANAGEMENT_V2` is true.
 - An action called `get_subscription_manager` should be created on the `subscribe-to-blogs.php` mu-plugin which will instantiate (if it hasn't been instantiated) the V2 class and return the instance of the class.
   - This is to be used by the Landpack block.

Variable/constant/action namings are not final. You are free to use a more appropriate naming convention.

**Comment by ivan-ottinger** [comment]
D102203-code is now ready for review.

**Comment by ivan-ottinger** [comment]
D102203-code is now ready for another round of reviews.

**Comment by ivan-ottinger** [comment]
D102203-code is now merged and deployed to production.
