### ISSUE TITLE
WooExpress: New has-upgraded-from-free-trial sticker for trial sites

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#73482]
This adds a sticker to note when a user first completes an eCommerce (or equivalent) plan purchase after being on a free trial.

A possible implementation would be, on upgrade, to check if the site does have the `had-ecommerce-trial`  sticker but doesn't have the `has-upgraded-from-free-trial` sticker, then we'd add the `has-upgraded-from-free-trial` sticker.

We may be able to override the [deactivate](fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Scebqhpgf%2Sohaqyrf.cuc%3Se%3Q74qpn2r0%23551-og) method in the `[Store_Product_Bundle_Ecommerce_Trial](fbhepr%2Sf%3Sersf%3QFgber_Cebqhpg_Ohaqyr_Rpbzzrepr_Gevny%26cebwrpg%3Qjcpbz-og)` class to achieve this.

Slack discussion: p1676559981020399-slack-C03Q87XT1QF

**Comment by daledupreez** [comment]
This task is being worked on in D102210-code.

**Comment by daledupreez** [comment]
We just addressed this in D102210-code, where we are using `has-upgraded-from-ecommerce-trial` as the new sticker.
