### ISSUE TITLE
Marketplace: Support youtube embeds in .org Plugin descriptions

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#73488]
It seems that we are stripping out youtube embeds from descriptions of WordPress.org Plugins

Example 
WordPress.com: https://wordpress.com/plugins/give
WordPress.org: https://wordpress.org/plugins/give/

![Image](https://user-images.githubusercontent.com/12430020/219656249-0001dd54-110a-4e95-afcc-e682010967dc.png)

**Comment by epeicher** [comment]
#### Backlog grooming:
- The response of the API call contains the YouTube embedding so it seems that Calypso is removing it. [Example of API request](https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request%5Bslug%5D=give&request%5Blocale%5D=en_US&request%5Bfields%5D=icons%2Cshort_description%2Ccontributors%2C-added%2C-donate_link%2C-homepage)
- For security reasons, we generally strip out iframes but we can whitelist youtube source

**Comment by cpapazoglou** [comment]
The sanitisation seems happening in https://github.com/Automattic/wp-calypso/blob/d01ec58003b9893c224cc10dc03a01d5932c5a87/client/lib/plugins/sanitize-section-content.js#L103

**Comment by WBerredo** [comment]
`give` iframes are falling on this case https://github.com/Automattic/wp-calypso/blob/0a2e8404a4ea756bf04471b70998abb4262e5cd9/client/lib/plugins/sanitize-section-content.js#L71-L73

Making `isValidYoutubeEmbed` returns `false` and not rendering this node.
