### ISSUE TITLE
Argentina set to en-US misleadingly shows USD with $ currency symbol

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#73496]
### Quick summary

Many countries (eg: Canada, Argentina) use `$` as their currency symbol in addition to the US. If a user is in Argentina, are paying in USD, and have their locale set to `en-US`, they will see prices like `$100.00`. This is misleading because they might assume it's in ARS and not USD. (This is not an issue if the user has `en-GB` or `en-CA` where the currency symbol will appear as `US $`; but we cannot use that inside the US because US users would be confused.)

This problem was resolved in https://github.com/Automattic/wp-calypso/issues/46205 primarily by using the IP address to determine if we should show `$` or `US $`. However, https://github.com/Automattic/wp-calypso/pull/71387 moved all currency formatting to the frontend and https://github.com/Automattic/wp-calypso/pull/71895 made it rely only on the user's locale, so this issue has returned.

Props to @daledupreez who noticed this in https://github.com/Automattic/wp-calypso/pull/71387#issuecomment-1434628152

**Comment by daledupreez** [comment]
I think it may be worth noting that the issue is not that users have Calypso set to `en-US`, but that Calypso only offers `en` and `en-GB` locales via the language settings. This means that English-speakers in most countries that use `$` as their primary currency symbol (which is most common in South America) will not see `US$` as the symbol, because Calypso defaults to the `en` locale, where it's not clear that `US` should be used as a prefix.

**Comment by daledupreez** [comment]
And as a follow-on, it may be worth looking at general pageview data to see if we can identify how many users in countries that use `$` for their local currency have their Calypso language set to `en`.

**Comment by jjchrisdiehl** [comment]
From an earlier discussion, we could use the server's geo ip lookup to seed the likely location of the customer to Calypso, then use this data to check if the customer is in the US or not (similar to how we handle this with our backend formatting) this would then allow us to dynamically set the currency symbol for `$`.

**Comment by daledupreez** [comment]
This might be getting way too deeply into the implementation weeds, but might it be something where the eventual result would be to conditionally inject the `US$` symbol override into the data we check for display purposes (and we'd need to flush any impacted caches when we switch). That way the interface for callers would stay the same, but `getCurrencyOverride()` could check a separate/additional, semi-dynamic data set for the currency symbol.

How we communicate the override to the client is still an open question, as we'd want this data available super-early in the Calypso bootstrapping (ideally close to where we set up the user's preferred language), but we could tightly scope the way we represent the data to focus on "these are the currency overrides we want to apply".

**Comment by DavidRothstein** [comment]
I don't know if this is helpful, but it appears the Happychat code in Calypso has access to geo-location info from the server already: https://github.com/Automattic/wp-calypso/blob/d3e2e0c8e510191c95c519691093a8f65db05073/client/state/happychat/selectors/get-geolocation.js

**Comment by michaeldcain** [comment]
From planning:

Since this is a regression and could affect a decent number of users, let's prioritize the fix for right after we finish our in progress tax work.

**Comment by sirbrillig** [comment]
> I don't know if this is helpful, but it appears the Happychat code in Calypso has access to geo-location info from the server already

Interesting! I did a quick test of loading checkout for myself and a test user and in both cases that geolocation was set to null. 😞 Maybe it has to be fetched explicitly. I'll look around.

<img width="307" alt="Screenshot 2023-03-10 at 1 15 47 PM" src="https://user-images.githubusercontent.com/2036909/224393082-358f8604-e638-41c3-8385-7e98bc8e6adb.png">

If using that state does not suffice, we can probably expose geolocation from the server to one of our other endpoints (ideally something that's already being fetched when calypso loads).

**Comment by sirbrillig** [comment]
I just found [this `useGeoLocationQuery()` hook](https://github.com/Automattic/wp-calypso/blob/136443bd1dfb5792563475a4a4981e0ffded1750/client/data/geo/use-geolocation-query.js#L3), which is interesting. It's currently used only [by the main account page](https://github.com/Automattic/wp-calypso/blob/136443bd1dfb5792563475a4a4981e0ffded1750/client/me/account/main.jsx#L200) but that might do just what we want. The question then becomes: where do we call this?

**Comment by sirbrillig** [comment]
https://github.com/Automattic/wp-calypso/pull/74351 fixes this but I need to consider if this is the right API.

**Comment by sirbrillig** [comment]
There may be a way to inject the geolocation country via boostrap code by putting it into the `/me` endpoint (see this Slack thread: p1678719863981819/1678473246.782839-slack-C02DQP0FP). Looking into this...

**Comment by sirbrillig** [comment]
This should now be fixed.
