### ISSUE TITLE
Sidebar: "👉 Not me" appears under Setting when I have PT-BR as my interface language

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#73494]
Two menu items that say "👉 Not me" are shown under Settings when I have Portuguese-BR as my interface language.

<img width="268" alt="Screen Shot 2023-02-17 at 10 34 12" src="https://user-images.githubusercontent.com/1234758/219666489-ea7bce22-057d-40df-a0cd-7fcca9ad5104.png">
<img width="517" alt="Screen Shot 2023-02-17 at 10 28 47" src="https://user-images.githubusercontent.com/1234758/219666501-afd809a5-1390-4c42-9613-8bcf56e35575.png">

**Comment by markbiek** [comment]
No longer an issue

<img width="614" alt="image" src="https://user-images.githubusercontent.com/917632/225754958-79f1118a-bdec-4f95-9628-3d437355d55c.png">
