### ISSUE TITLE
Task: Add post-purchase screen for users who purchase an eCommerce plan from the trial

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73500]
### Details

We need to implement a post-purchase screen for users who upgrade from the free trial to the eCommerce plan.

From an implementation perspective, detecting when an eCommerce purchase occurred on a site that was previously on the free trial may be really tricky in the Calypso context. It may be easier to specify a redirect URL when we send users to checkout, but that may be complicated if any upsells directly add products to the cart.

While building the page, it will also be worth confirming whether we should add some sort of escape hatch that doesn't require one of the next steps cards to be selected.

Design details:
 - peapX7-1yI-p2
 - jBwlERMS350NqhJNHZzAVF-fi-98%3A33334&t=xbjxJ2I9nnqtCPTA-0

### Checklist

- [ ] After I upgrade to the eCommerce plan from the free trial, I should see the post-checkout screen with next steps
- [ ] Add actions to the next-step cards - flows are catpured here: lD0gTB4IqGsmSmsnjZNaP6-fi-470%3A17348&t=oWgWy5zHSYbWIcS8-0
- [ ] Add dynamic confetti

**Comment by that-mike-bal** [comment]
@daledupreez  why not just take them back to the plan page to show they are off the free trial and on the e-commerce plan or back to my home and their task list?

**Comment by daledupreez** [comment]
That's as much a question for @veronicafasulo as it is for me. Any of the above could work, but we do need something other than the default thank you experience.

**Comment by daledupreez** [comment]
With #74064 and #74093 being merged, we have now addressed all open items relating to the post-purchase UI, so I am going to close this issue.
