### ISSUE TITLE
ReferenceError: Can't find variable: fieldset

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#7350]
This is error from found through Calypso remote Error logging. We have approx. 6605 of these errors per 24h
### Error message

`ReferenceError: Can't find variable: fieldset`
### Paths
- /post/:siteId
- /page/:siteId
### Browsers

Only Safari.
### Stack trace

> [{"url":"https:\/\/wordpress.com\/post\/[SITE_ID]","line":3,"column":376,"func":"?","context":"[\"<!DOCTYPE html><!--<3\",\"             _\",\"    ___ __ _| |_   _ _ __  ___  **_\",\"   \/ __\/ _` | | | | | '_ \\\/ __|\/ _ \\\",\"  | (_| (_| | | |_| | |_) \\** \\ (_) |\",\"   \\___\\**,_|_|\\**, | .**\/|_**\/\\**_\/\",\"               |**_\/|_|\",\"\"]"}]
### Kibana issues

78081ac5d6d6f2ea687ce16266a2aea8-logstash

**Comment by designsimply** [comment]
#bug-scrub

I checked for the `ReferenceError: Can't find variable: fieldset` error in our logs and found there were 540 so far today (as of 19:38 UTC) predominantly in the `/post/:siteId` route. 

Internal ref: 8d29bf084d19f58f0b008b8dc93bb5ef-logstash

Based on a quick search for `fieldset` in the `client/post-editor/` directory,  this might be an issue with sharing options or gallery fields. I tried testing creating a new post and making updates to the sharing settings, adding an image from a URL, adding a gallery, adding captions, and changing all the gallery settings I could see, but I was unable to trigger the error. Tested with Safari 10.0 on Mac OS X 10.11.6.
