### ISSUE TITLE
Change Blaze banner behavior

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#73506]
Currently, [the Blaze banner is hidden after user create their first campaign](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/promote-post/main.tsx#L177).  As we talked in this Slack thread, we'll change that behavior: p1676573522092679-slack-CKZHG0QCR

Current /advertising Banner:

![Image](https://user-images.githubusercontent.com/1044309/219791023-c091b4a8-85e9-44f9-bd67-6a3fa760e3da.png)

### Acceptance criteria

- Show the big banner (current) when a user didn't use Blaze yet (no campaigns created)
- Show a small version of the banner after 2 campaigns created
- Make sure it works great at mobile as well

**Comment by allilevine** [comment]
Putting this on hold status since /advertising is being redesigned: peeHDf-GM-p2

**Comment by allilevine** [comment]
Closing, I don't think this is needed post-redesign. Feel free to re-open @paulopmt1
