### ISSUE TITLE
Yoast SEO Premium Purchased, not Showing Premium on Site

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#73511]
### Quick summary

Marketplace bug report.

Customer has purchased monthly Yoast SEO Premium. The plugin is properly installed, but there are many prompts asking them to upgrade to Yoast SEO Premium. On Yoast SEO > Premium, it says INSTALLED, NOT ACTIVATED.

### Steps to reproduce

In my attempts to reproduce, I purchased Yoast SEO Premium on a test site. After paying for the upgrade, Yoast SEO was installed, but Yoast SEO Premium was not installed.

I symlinked and activated Yoast SEO Premium in CLI (which is not available to customers), and after this, Yoast SEO Premium was INSTALLED and ACTIVATED on my test site.

### What you expected to happen

Yoast SEO Premium should be both INSTALLED and ACTIVATED after purchasing.

### What actually happened

On the customer's site, Yoast SEO Premium was INSTALLED and NOT ACTIVATED.

On my test site, Yoast SEO Premium was NOT installed, but WAS activated.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Customer report: 5963702-zen

**Comment by rw-ye** [comment]
There is an another existing report for this aswell - #73259

**Comment by cuemarie** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/70980 which, happily, was fixed within the last 24 hours by 261988-wpcom 🎉
