### ISSUE TITLE
Minified exception occurred;

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#7352]
This is error from found through Calypso remote Error logging. We have approx. 16626 of these errors per 24h
### Error message

`Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.`
### Paths
- /post/:siteId
- /page/:siteId
- /stats/insights
- /settings/delete-site/:siteId
- /posts/:siteId
- /me
- /pages/:siteId
- ...
### Browsers

All
### Stack trace

>   [{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"invariant","args":[],"line":38,"column":16765,"context":"[\"yy:[\\"godina\\",\\"godine\\",\\"godina\\"]},correctGrammaticalCase:function(number,wordKey){return number===1?wordKey[0]:number>=2&&number<=4?wordKey[1]:wordKey[2]},translate:function(number,withoutSuffix,key){var wordKey=translator.words[key];if(key.length=="},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"Dispatcher.dispatch","args":[],"line":65,"column":23478,"context":"[\"var _actionTypes=__webpack_require__(4);var _schema=__webpack_require__(972);var _utils=__webpack_require__(14);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{\\"default\\":obj}}function items(){var state=arguments.length<=0||argument"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"Dispatcher.handleViewAction","args":[],"line":7,"column":24846,"context":"[\"if(!valid__isValid(tempConfig)){continue}currentScore+=getParsingFlags(tempConfig).charsLeftOver;currentScore+=getParsingFlags(tempConfig).unusedTokens.length*10;getParsingFlags(tempConfig).score=currentScore;if(scoreToBeat==null||currentScore<scoreToBea"},{"url":"https:\/\/wordpress.com\/calypso\/post-editor.7c780cf9b5890899ab78.min.js","func":"Object.fetchPageTemplates","args":[],"line":42,"column":16697,"context":"[\"var _actions2=_interopRequireDefault(_actions);var _store=__webpack_require__(254);var _store2=_interopRequireDefault(_store);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{\\"default\\":obj}}var SERVICE_HOSTNAME=\\"service.afterthedea"},{"url":"https:\/\/wordpress.com\/calypso\/post-editor.7c780cf9b5890899ab78.min.js","func":"Constructor.componentWillReceiveProps","args":[],"line":34,"column":26808,"context":"[\"this.setState({fullImage:!this.state.fullImage})},trashPost:function trashPost(){var updateStatus;this.setState({showPopoverMenu:false,isTrashing:true});updateStatus=function(error){if(!this.isMounted()){return}if(error){return this.setState({isTrashing:"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"ReactCompositeComponentWrapper.updateComponent","args":[],"line":73,"column":31248,"context":"[\"links:[\\"Africa\/Abidjan|Africa\/Bamako\\",\\"Africa\/Abidjan|Africa\/Banjul\\",\\"Africa\/Abidjan|Africa\/Conakry\\",\\"Africa\/Abidjan|Africa\/Dakar\\",\\"Africa\/Abidjan|Africa\/Freetown\\",\\"Africa\/Abidjan|Africa\/Lome\\",\\"Africa\/Abidjan|Africa\/Nouakchott\\",\\"Africa\/Abi"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"ReactCompositeComponentWrapper.receiveComponent","args":[],"line":73,"column":30135,"context":"[\"links:[\\"Africa\/Abidjan|Africa\/Bamako\\",\\"Africa\/Abidjan|Africa\/Banjul\\",\\"Africa\/Abidjan|Africa\/Conakry\\",\\"Africa\/Abidjan|Africa\/Dakar\\",\\"Africa\/Abidjan|Africa\/Freetown\\",\\"Africa\/Abidjan|Africa\/Lome\\",\\"Africa\/Abidjan|Africa\/Nouakchott\\",\\"Africa\/Abi"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"Object.receiveComponent","args":[],"line":13,"column":15325,"context":"[\"var merge=createAssigner(function(object,source,srcIndex){baseMerge(object,source,srcIndex)});module.exports=merge},,,function(module,exports,__webpack_require__){var arrayMap=**webpack_require**(95),baseIteratee=**webpack_require**(42),baseMap=__webpack"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"ReactCompositeComponentWrapper._updateRenderedComponent","args":[],"line":74,"column":2289,"context":"[\"return false}return indexedDB&&typeof indexedDB.open===\\"function\\"&&typeof self.IDBKeyRange!==\\"undefined\\"}catch(e){return false}}();result[DriverType.WEBSQL]=!!function(){try{return self.openDatabase}catch(e){return false}}();result[DriverType.LOCALST"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"ReactCompositeComponentWrapper._performComponentUpdate","args":[],"line":74,"column":1641,"context":"[\"return false}return indexedDB&&typeof indexedDB.open===\\"function\\"&&typeof self.IDBKeyRange!==\\"undefined\\"}catch(e){return false}}();result[DriverType.WEBSQL]=!!function(){try{return self.openDatabase}catch(e){return false}}();result[DriverType.LOCALST"}]
### Kibana issues

657eea746900a995ad7a01f2ac7f95d0-logstash

**Comment by designsimply** [comment]
I searched Kibana for the "Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings." error with timeframe 2016-11-22 19:17:00.671 to 2016-11-24 19:17:00.671 and found 907 originating from `/settings/delete-site/:siteId` out of 962 total with very few from other areas (i.e. 14 from `/`).

I tried visiting https://wordpress.com/settings/export/design5279.wordpress.com using Safari 10.0 with Mac OS X 10.12 and interacting with the page by creating an export (I didn't click the "Delete Site" button), and I didn't find any errors in the console during my testing.

@lamosty, is there anything else I can do to help test this issue?
