### ISSUE TITLE
Task: Investigate behaviour for /plugins/manage when on free trial

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#73538]
### Details

At present, users who visit `/plugins/manage/:siteSlug` while on the free trial are redirected back to `/plugins/:siteSlug`, though this may only occur after the page has mostly rendered. (Note that `/plugins/manage/:siteSlug` is also the redirect target for users who try to visit  `/wp-admin/plugins.php` on the site.)

With the changes to remove permissions to install paid plugins last week, and the subsequent introduction of the new feature to list installed plugins, we need to work out what level of access (if any) we want to grant to this page.

### Checklist

- [ ] Identify whether we should list the set of installed plugins directly - what would this look like if we didn't redirect away?
- [ ] If the above looks OK, identify how much work it would be to refactor the page to support a view-only mode

**Comment by that-mike-bal** [comment]
Decision - Yes - let’s hide them 
Part 1: Modify the menu on the back end hide it in all context
Part 2: Follow up - while it’s not visible, if they end up on that

**Comment by daledupreez** [comment]
I explored this last week, and the underlying code is relatively complex, and modifying it to support a read-only view would be complicated and risky. So we don't plan to show that UI to users on the free trial, which we will be implementing in #73753.
