### ISSUE TITLE
WooExpress: Update wpcomsh feature-plugin hooks to allow install_plugins

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#73541]
There are a few routes in `Automattic\WooCommerce\Admin\API\Plugins` that check for `install_plugins` permissions (for example, `/wp-json/wc-admin/plugins/connect-wcpay`). We need to unblock those routes in order for WooExpress trial sites to function properly

We can do this by  updating the referrer checks in `wpcomsh_is_woocommerce_payment_gateway_requests` (`feature-plugins/hooks.php#L120`) to include the above routes.

Slack discussion: p1676904653541629-slack-C0Q664T29

**Comment by daledupreez** [comment]
Automattic/wpcomsh#1301 was deployed yesterday, so I am marking this as complete.
