### ISSUE TITLE
Cannot read property 'getContent' of undefined

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#7356]
This is error from found through Calypso remote Error logging. We have approx. 3200 of these errors per 24h

### Error message
`Cannot read property 'getContent' of undefined`

### Paths

- /posts/:siteId
- /pages/:siteId
- /post/:siteId
- /page/:siteId
- /stats/day/
- /me
- /
- ...

### Browsers

- Chrome

### Stack trace

> 	[{"url":"https:\/\/wordpress.com\/calypso\/post-editor.7c780cf9b5890899ab78.min.js","func":"Constructor.saveRawContent","args":[],"line":52,"column":14735,"context":"[\"var _formLabel2=_interopRequireDefault(_formLabel);var _compact=__webpack_require__(1764);var _compact2=_interopRequireDefault(_compact);var _section=__webpack_require__(1543);var _section2=_interopRequireDefault(_section);var _selectors=__webpack_requir"},{"url":"https:\/\/wordpress.com\/calypso\/post-editor.7c780cf9b5890899ab78.min.js","func":"Constructor.autosave","args":[],"line":52,"column":14872,"context":"[\"var _formLabel2=_interopRequireDefault(_formLabel);var _compact=__webpack_require__(1764);var _compact2=_interopRequireDefault(_compact);var _section=__webpack_require__(1543);var _section2=_interopRequireDefault(_section);var _selectors=__webpack_requir"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"complete","args":[],"line":22,"column":1136,"context":"[\"getSlug:function getSlug(){return FEATURE_ADVANCED_DESIGN},getTitle:function getTitle(){return _i18nCalypso2.default.translate(\\\"{{strong}}Advanced{{\/strong}} Design Customization\\\",{components:{strong:_react2.default.createElement(\\\"strong\\\",null)}})},g"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"maxDelayed","args":[],"line":22,"column":1524,"context":"[\"getSlug:function getSlug(){return FEATURE_ADVANCED_DESIGN},getTitle:function getTitle(){return _i18nCalypso2.default.translate(\\\"{{strong}}Advanced{{\/strong}} Design Customization\\\",{components:{strong:_react2.default.createElement(\\\"strong\\\",null)}})},g"}]

### Kibana issues

bd4ff795e07548d26a209d3310505a01-logstash

**Comment by aduth** [comment]
__Steps to reproduce:__

1. Navigate to the [post editor](https://wordpress.com/post)
2. Select a site
3. Enter a title
4. Allow autosave to take effect
5. Change the title
6. Navigate to another page in Calypso
7. (Accept the prompt that there are unsaved changes)
8. After 15-20 seconds, note error in console

**Comment by artpi** [comment]
Nice @aduth ! Thank you!
Confirmed that the problem stopped being an issue:
<img width="540" alt="zrzut ekranu 2016-08-29 o 07 11 43" src="https://cloud.githubusercontent.com/assets/3775068/18054252/edc42a20-6db7-11e6-9a1a-8cb4f6222317.png">

As a sidenote - I noticed that we also have a very small subret of users running very outdated code. I have no idea why is that

**Comment by aduth** [comment]
>[...] small subret of users running very outdated code I have no idea why is that

Well, so long as they don't close their tab, they'll continue to run whichever version of the code they'd originally loaded WordPress.com as... one of the downsides of single-page applications (though we could consider forcibly refreshing bundles, which has been raised in the past for more urgent issues).

Or perhaps it could be reports from the desktop application?

**Comment by artpi** [comment]
> Well, so long as they don't close their tab, they'll continue to run whichever version of the code they'd originally loaded WordPress.com

I've seen it run for 2 weeks! But yeah!

> Or perhaps it could be (also) reports from the desktop application?

I thought so initially, but js error logging is disabled for app
