### ISSUE TITLE
Encrypt the access token from GitHub 

### ISSUE THREAD

**Issue by mpkelly** [Automattic/wp-calypso#73566]
### Details

This was requested by Systems [here](pdKhl6-1u2-p2#comment-1737). There is also some Slack discussion [here](p1676924761366179/1676629960.498069-slack-C04H4NY6STW).

### Checklist

- [ ] Can encrypt/decrypt token per blog, not per user since connections are shared across blogs since D101677-code

**Comment by p-jackson** [comment]
D102164-code

**Comment by p-jackson** [comment]
Deployed
