### ISSUE TITLE
Skatepark: Slideshow block keeping background color

### ISSUE THREAD

**Issue by ha-un** [Automattic/wp-calypso#73567]
### Quick summary

When using the Skatepark theme, despite changing the background color, the Slideshow block keeps the original background color. It is however not an issue on the front-end.

### Steps to reproduce

1. Create a new site using Skatepark theme
2. Add slideshow block & add images
3. Change the global background color & save changes
4. Refresh or open the Site Editor again, and the original color (green) should show up.

### What you expected to happen

After changing the background color, the original color shouldn't be affecting the Slideshow block.

### What actually happened

The green overlay color continued to show on the Slideshow block in the Site Editor and its images, but only within the editor.

**View of Site Editor:**

<img width="1623" alt="Screenshot 2023-02-21 at 11 49 27 AM" src="https://user-images.githubusercontent.com/96960321/220235086-c0de4494-dc8b-4b1c-bbfc-b796fd364b31.png">

**View of live site:**

<img width="1515" alt="Screenshot 2023-02-21 at 11 49 39 AM" src="https://user-images.githubusercontent.com/96960321/220235117-635cdfcf-b8df-4163-9e89-cb1cccced822.png">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could Not Replicate
- Tested on AT: Could Not Replicate
- Tested on Self-hosted: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was not able to replicate this issue. When adding the slideshow block to theme Skatepark, the slideshow did not take on the duotone filter automatically.  Consequently, when the background color was updated, the slideshow block behaved as expected.
- This behavior was consistent across all test environments.

**AT Example - Before BG Color Change**
![Markup on 2023-03-11 at 19:30:38](https://user-images.githubusercontent.com/27249804/224520919-2b19960b-57bb-45e4-8ed7-e07a7d1ee6b0.png)

**AT Example - After BG Color Change**
![Markup on 2023-03-11 at 19:33:05](https://user-images.githubusercontent.com/27249804/224520915-de6a9f83-4f50-4028-a9ec-85daa509b652.png)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)
