### ISSUE TITLE
Stats: Labels (x-axis) in Years/Weeks/Months view are rendered with an offset in relation to the bars

### ISSUE THREAD

**Issue by oskosk** [Automattic/wp-calypso#73589]
### Quick summary

![image](https://user-images.githubusercontent.com/746152/220347716-cec57351-5be8-4443-b911-d51e59304a53.png)

I think this happens on wide layouts only
* Resizing the window fixes the issue.

To reproduce:

### Steps to reproduce

* Visit the stats page for a site. 
* Click Years
* Reload the page
* Confirm the labels are not aligned to the bars

### What you expected to happen

To not have the bars offset to their labels

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/746152/220349368-cf1d14af-a2bd-4e33-b30e-fa620c833eb2.png">

### What actually happened

~Labels are rendered properly, but bars aren't~

Edit: apparently bars are rendered properly and not labels.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement. Resizing the Window works

### Platform (Simple and/or Atomic)

Simple, Self-hosted

**Comment by jsnmoon** [comment]
Related PR: https://github.com/Automattic/wp-calypso/pull/70288.
