### ISSUE TITLE
Cannot read property 'postMessage' of null

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#7359]
This is error from found through Calypso remote Error logging. We have approx. 2500 of these errors per 24h
### Error message

`Cannot read property 'postMessage' of null`
### Paths
- /stats/insights/:siteId
- /stats/day/:siteId
- /post/:siteId
- /
- ...
### Browsers
- chrome
- android
### Stack trace

>   [{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"postMessage","args":[],"line":56,"column":16657,"context":"[\"return promise}function getItem(key,callback){var _this2=this;debug(\\"localForage bypass\\",\\"getItem\\",key);if(typeof key!==\\"string\\"){key=String(key)}var promise=new _promise2.default(function(resolve,reject){_this2.ready().then(function(){try{var db=_"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"handleVisibilityChange","args":[],"line":56,"column":14904,"context":"[\"return promise}function getItem(key,callback){var _this2=this;debug(\\"localForage bypass\\",\\"getItem\\",key);if(typeof key!==\\"string\\"){key=String(key)}var promise=new _promise2.default(function(resolve,reject){_this2.ready().then(function(){try{var db=_"}]
### Kibana issues

14d3e0f781d9d19094f841854318086c-logstash

**Comment by designsimply** [comment]
#bug-scrub

I checked for this error in our logs and found there were 209 recorded for 2014-10-28 (Friday last week) and 298 for today so far (as of 19:13 UTC). I tried to check top pathway (i.e. `post/:siteId` → `https://wordpress.com/post/design5279.wordpress.com`) manually to see if I could trigger the `Cannot read property 'postMessage' of null` error, but I didn't see it in the console while testing the `post/:siteId` route with Firefox 49.0.2 on Mac OS X 10.11.6.

@artpi or @rralian, how else can I help check in on `Logstash`-labeled issues like this one?

Internal ref: p4TIVU-455-p2

**Comment by rralian** [comment]
@designsimply It can be difficult to figure out what's happening in these kibana errors. So the most beneficial thing is to help us figure out how to recreate a problem. I spent some time looking at kibana records and unfortunately I can't figure out exactly what's going on here. And the error message seems to happen on several different pages. If we can't reproduce it, then sometimes we just can't fix it. I notice that we see a _similar_ error message pretty commonly when we load the customizer. But  I don't know for sure whether it's related.

![error message](http://cld.wthms.co/zAeo+)
