### ISSUE TITLE
Task: Route Help Center support requests appropriately

### ISSUE THREAD

**Issue by arcangelini** [Automattic/wp-calypso#73590]
## Summary

This is being opened primarily to address the routing of support requests for the e-commerce plan but I also figured it would be a great opportunity to make sure we are routing things properly for all our products that see the Help Center. p1676494179148869/1672745808.112169-slack-C03Q87XT1QF

The main task is to make sure users on the e-commerce plan are routed to Woo HE's for chat. I am also not sure what forums should do now that it is open for all plans. As a sub task it would be nice to know what should happen for Jetpack products. After brainstorming with @joelwills he thought it would be best to connect with @jobthomas and @lizthefair to make sure Help Center is sending requests to the right places. For example, is there a situation where someone on Jetpack only plan should be routed to WordPress.org forums?

Please let us know what everyone thinks and how we can make sure we are connecting the users with the right people.

### Checklist

- [ ] Woo requests
- [ ] JPOP requests

**Comment by jobthomas** [comment]
Are you asking for specific cases on when people should be directly routed from the help center to Woo? 

* For now: if they have signed up for the free trial and need help
* Likely in the near future: if they signed up for the commerce plan

Longterm: I'm not sure if there are qualifying questions for email/chat submission, but it'd be great if there's some form of smart routing there as well where we can cut out some back-and-forth. E.g. if someone asks a question about domains in the commerce plan, it still gets routed to WP.com

**Comment by drwpcom** [comment]
> I am also not sure what forums should do now that it is open for all plans

That's what I'm wondering as well. @jobthomas would we want to have some way for Woo to serve ecommerce customers through forums or are we focusing on chat and email?

**Comment by jobthomas** [comment]
I think we can leave that part as is, maybe at some point we should revisit having forums on Woo.com, but I'm not sure we're there yet.

**Comment by joelwills** [comment]
@jobthomas When you say "leave that part as is" I'm not sure what you mean. Is it that you don't show forums now and want to hide that option on WP.com for Commerce plan users?

**Comment by jobthomas** [comment]
Stepping back: are we currently showing forums to them? I think it'd be great to do that (that's what I thought we'd be keeping.)

**Comment by joelwills** [comment]
We show WP.com forums as the first option now to all Plan holders. The question is for Commerce plan owners do you want that Forums link to go to Woo forums, not be shown at all and just live chat and Email, or keep pointing to the WP.com forums?

**Comment by jobthomas** [comment]
Yup. So I did understand correctly. We currently don't have forums on Woo.com, so the only option would be to send them to WP.org which I don't think is a good scenario here. WP.com forums seem like the best idea. So yes:

* forums should stay
* should continue to point to WP.com

at least for now

**Comment by klimeryk** [comment]
FYI, the eCommerce trial routing change has been made - see pdm0RZ-v5-p2 and D103642-code 🙇

**Comment by kriskarkoski** [comment]
Closing as there are not current plans to route Entrepreneur to Woo HEs.
