### ISSUE TITLE
Cannot read property 'subscriptions' of undefined

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#7360]
This is error from found through Calypso remote Error logging. We have approx. 2500 of these errors per 24h
### Error message

`Cannot read property 'subscriptions' of undefined`
### Paths
- /
- /following/edit
- ...
### Browsers
- chrome
- android
### Stack trace

>   [{"url":"https:\/\/wordpress.com\/calypso\/commons.7ee8dcd0ac416fea9f5f.min.js","func":"Object.receiveFeedSubscriptions","args":[],"line":8,"column":7634,"context":"[\"var activeAbTests=[];var lastRoute=null;function userHasHistory(context){return!!context.lastRoute}function renderFeedError(){_reactDom2.default.render(_react2.default.createElement(_feedError2.default),document.getElementById(\\"primary\\"))}module.export"},{"url":"https:\/\/wordpress.com\/calypso\/commons.7ee8dcd0ac416fea9f5f.min.js","func":"Object.ID_18","args":[],"line":8,"column":10156,"context":"[\"var activeAbTests=[];var lastRoute=null;function userHasHistory(context){return!!context.lastRoute}function renderFeedError(){_reactDom2.default.render(_react2.default.createElement(_feedError2.default),document.getElementById(\\"primary\\"))}module.export"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"Dispatcher._invokeCallback","args":[],"line":65,"column":23863,"context":"[\"var _actionTypes=__webpack_require__(4);var _schema=__webpack_require__(972);var _utils=__webpack_require__(14);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{\\"default\\":obj}}function items(){var state=arguments.length<=0||argument"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"Dispatcher.dispatch","args":[],"line":65,"column":23610,"context":"[\"var _actionTypes=__webpack_require__(4);var _schema=__webpack_require__(972);var _utils=__webpack_require__(14);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{\\"default\\":obj}}function items(){var state=arguments.length<=0||argument"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"Dispatcher.handleServerAction","args":[],"line":7,"column":25015,"context":"[\"if(!valid__isValid(tempConfig)){continue}currentScore+=getParsingFlags(tempConfig).charsLeftOver;currentScore+=getParsingFlags(tempConfig).unusedTokens.length*10;getParsingFlags(tempConfig).score=currentScore;if(scoreToBeat==null||currentScore<scoreToBea"},{"url":"https:\/\/wordpress.com\/calypso\/commons.7ee8dcd0ac416fea9f5f.min.js","func":"Object.receiveFollowingList","args":[],"line":4,"column":24698,"context":"[\"webpackJsonp([0],{1436:function(module,exports,__webpack_require__){\\"use strict\\";var React=**webpack_require**(1),assign=**webpack_require**(22),classnames=**webpack_require**(11);var Card=**webpack_require**(136);module.exports=React.createClass({disp"},{"url":"https:\/\/wordpress.com\/calypso\/commons.7ee8dcd0ac416fea9f5f.min.js","func":"?","args":[],"line":4,"column":23910,"context":"[\"webpackJsonp([0],{1436:function(module,exports,**webpack_require**){\\"use strict\\";var React=**webpack_require**(1),assign=**webpack_require**(22),classnames=**webpack_require**(11);var Card=**webpack_require**(136);module.exports=React.createClass({disp"},{"url":"https:\/\/wordpress.com\/calypso\/commons.7ee8dcd0ac416fea9f5f.min.js","func":"?","args":[],"line":4,"column":22019,"context":"[\"webpackJsonp([0],{1436:function(module,exports,**webpack_require**){\\"use strict\\";var React=**webpack_require**(1),assign=**webpack_require**(22),classnames=**webpack_require**(11);var Card=**webpack_require**(136);module.exports=React.createClass({disp"},{"url":"https:\/\/wordpress.com\/calypso\/vendor.7ee8dcd0ac416fea9f5f.min.js","func":"?","args":[],"line":5,"column":12081,"context":"[\"(function(modules){var parentJsonpFunction=window[\\"webpackJsonp\\"];window[\\"webpackJsonp\\"]=function webpackJsonpCallback(chunkIds,moreModules){var moduleId,chunkId,i=0,callbacks=[];for(;i<chunkIds.length;i++){chunkId=chunkIds[i];if(installedChunks[chun"},{"url":"https:\/\/wordpress.com\/calypso\/build-production.7ee8dcd0ac416fea9f5f.min.js","func":"XMLHttpRequest.onerror","args":[],"line":35,"column":21792,"context":"[\"weekdays:\\"Sonntag_Montag_Dienstag_Mittwoch_Donnerstag_Freitag_Samstag\\".split(\\"_\\"),weekdaysShort:\\"So._Mo._Di._Mi._Do._Fr._Sa.\\".split(\\"_\\"),weekdaysMin:\\"So_Mo_Di_Mi_Do_Fr_Sa\\".split(\\"_\\"),longDateFormat:{LT:\\"HH:mm\\",LTS:\\"HH:mm:ss\\",L:\\"DD.MM.YYY"}]
### Kibana issues

388e3d01fd332dfa05dd5d105456c0d3-logstash

**Comment by designsimply** [comment]
#bug-scrub 

I tried to test this by going to https://wordpress.com/following/edit using Chrome 54.0.2840.98 on Mac OS X 10.12 and interacting with the page as well as with notifications and looking in the console for errors, but I didn't see any errors.

I also checked 388e3d01fd332dfa05dd5d105456c0d3-logstash (an internal tool for tracking error messages) and searched in the timeframe from 2016-11-29 19:17:00.671 to 2016-11-30 19:17:00.671 and from 2016-11-22 19:17:00.671 to 2016-11-24 19:17:00.671and "No results found" was the message returned for the first search and only one error was found in the second search.

I'm closing this issue because it appears the specific error, "Cannot read property 'subscriptions' of undefined," has not appeared recently. Please re-open if needed or create a new issue if this comes up again.
