### ISSUE TITLE
Stats: "View all" link is broken on the subscribers module on the insights page

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#73611]
This applies to WordPress.com and Email subscribers, which link to `/people/followers/:siteSlug` and `/people/email-followers/:siteSlug`. Neither links work; instead, they render this blank page:

![Image](https://user-images.githubusercontent.com/4044428/220445747-820f9837-5a72-47ed-afe9-85b68e35e87d.png)

It looks like both links should be updated to use `/people/subscribers/:siteSlug`. It doesn't seem possible to filter subscribers by type anymore.

**Comment by grzegorz-cp** [comment]
It looks like recent changes to people's controller removed `email-followers` and created some conditions, rendering the `followers` URL to subscribers but not handling it, resulting in a blank page.

The code handling `followers` and `email-followers` is still there - [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/people/index.js#L16).
But the handling is redirected here by an already released feature flag [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/people/controller.js#L96) swapping `<PeopleList />` handled [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/people/main.jsx#L34) to <SubscribersTeam /> handled [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/people/subscribers-team/index.tsx#L84).

As a result, `followers` renders a header with blank content, `email-followers` is not handled and `subscribers` is the only valid URL.

**Comment by grzegorz-cp** [comment]
I created a PR updating all the routes we use to `subscribers`.
