### ISSUE TITLE
Update the Email Login & Email Sent section with the new copy tweaks.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73657]
Copy tweaks have been made on the Figma design inDLaEQV8jJ21O4WXawIsJ-fi-712%3A13475.
Let's bring them over to the Email Login & Sent section.

Further discussion here:
p1677240386855839-slack-C02TCEHP3HA

**Comment by ivan-ottinger** [comment]
While reviewing Juan's PR, I did not notice any changes in the "Sent" section.

**Comment by yansern** [comment]
Thanks for verifying @ivan-ottinger.

**Comment by JuanLucha** [comment]
Thanks for checking while reviewing, @ivan-ottinger !

**Comment by yansern** [comment]
Newsletter Section is OK now.

Changes need to be brought to both Email Login & Email Sent section with the recent updates as discussed on p1677240386855839-slack-C02TCEHP3HA.

**Comment by yansern** [comment]
Email Login Section copy update is completed with this PR.
https://github.com/Automattic/landpack/pull/1238
