### ISSUE TITLE
Components: FormTextarea placeholder missing in IE11

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7368]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design/form-fields
2. At the very bottom of the example page is the FormTextarea component, which should say "Placeholder text..." 
#### What I expected

Placeholder text
#### What happened instead

The text is present in all browsers I checked except IE11.  The placeholder text is present in other components, it's just missing in this one.
#### Browser / OS version

Windows 10, IE 11.494.10586
##### IE11

![screen shot 2016-08-09 at 2 32 52 pm](https://cloud.githubusercontent.com/assets/7233112/17528747/993dd93e-5e3e-11e6-8d64-676424260417.png)
##### Chrome

![screen shot 2016-08-09 at 2 32 43 pm](https://cloud.githubusercontent.com/assets/7233112/17528781/b7d1845e-5e3e-11e6-8a08-da1f3114d0d6.png)
#### Context / Source
# automated-testing

**Comment by lancewillett** [comment]
I think this could be an OK tradeoff for IE11 to not show the placeholder text.

However, a fix could be <a href="http://stackoverflow.com/questions/22199047/placeholder-css-not-being-applied-in-ie-11/26164266#26164266">separating out the CSS rules</a> as that seems to be a common solution.
