### ISSUE TITLE
Can't hide Fiverr card in Calypso

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#73688]
### Quick summary

The Fiverr card in the My Home area of Calypso can't be hidden, it just gets a spinning "loading" icon that never clears

### Steps to reproduce

1. Go to the My Home page in Calypso
2. Click on the `Hide > Forever` option in the Fiverr card

### What you expected to happen

The card would hide like all the other ones

### What actually happened

The Loading icon keeps going in a loop (but _only_ for the Fiverr card!)

![2023-02-22 16 18 23](https://user-images.githubusercontent.com/4000628/220762571-9e2ec5a1-6a4d-4459-a4b8-08bf926fa77b.gif)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Tested on Firefox, Edge, and Chrome
- Originally reported in #38525816-hc, follow-up in #5983915-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*

- Tested on Simple: Replicated
- Tested on AT: Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described! Even when going out of order, hiding the Fiverr logo design card fails to hide. 

**AT Example**

https://user-images.githubusercontent.com/27249804/221082955-8def7666-40e2-4ae7-9e8b-2e513f1fafbc.mov

**Simple Example**

https://user-images.githubusercontent.com/27249804/221082961-4100c909-7888-4211-8d2e-88c6062ddd8b.mov


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by mgozdis** [comment]
I also reproduced this on a test site after a user reported here: 5990448-zd-woothemes

**Comment by aleone89** [comment]
There's another report of this here: https://wordpress.com/forums/topic/cant-remove-fiverr-box-on-home-page/?view=all

**Comment by kingsleyinfo** [comment]
There is another report of this here: 
6022827-zd-woothemes

**Comment by aisajib** [comment]
Another user said they couldn't dismiss the Fiverr box. https://wordpress.com/forums/topic/cant-remove-fiverr-box-on-home-page/?view=all#post-3932295

**Comment by edwinho89** [comment]
6039997-zd-woothemes

**Comment by cuemarie** [comment]
Ticket from https://github.com/Automattic/wp-calypso/issues/74590

- [ ] Report: 41226049-hc
- [ ] Follow Up Ticket for update: 6051457-zen

**Comment by mgozdis** [comment]
Another report 40267661-hc

**Comment by supernovia** [comment]
Another case here:
https://wordpress.com/forums/topic/cant-remove-fiverr-box-on-home-page/?view=all#post-3926560

**Comment by BogdanUngureanu** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/74757
