### ISSUE TITLE
Pexel Images do not load in search when picking images

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#73713]
### Quick summary

The search won't return any results when trying to add a new image by selecting Pexels. This happens on Simple and AT sites.
![Screen Capture on 2023-02-23 at 14-52-35](https://user-images.githubusercontent.com/8070771/220868199-feeb48cc-a552-4bb4-b4d1-f6e18a40ed0d.gif)

### Steps to reproduce

1. Add a new image block
2. Select the image from **Pexels**
3. Search for any term and the search won't return any results.

**Error:** Sorry, but nothing matched your search criteria.

### What you expected to happen

Results of the photos with the searched term.

### What actually happened

No results and an **Error message:** Sorry, but nothing matched your search criteria. 

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes

In the meantime, users can use other options such as uploading the photo from other sources or downloading the photo directly from the Pexel.com site and then uploading it as a Local Media.

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on P2 - Replicated 
- Tested on Simple - Replicated 
- Tested on AT - Replicated 
- Tested on Self-hosted - Could Not Replicate 
- Replicable on Core - No

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by vinnykaur** [comment]
First reported at zen-5984509

**Comment by carolframen** [comment]
Another report 5983878-zen

**Comment by mgozdis** [comment]
Another report 23810802-hc

**Comment by mxhassani** [comment]
5985939-zd-woothemes
Suggested Openverse  or direct uploads from Pexels.com

**Comment by carolframen** [comment]
Another one 5984707-zen

**Comment by wynwin** [comment]
40525482-hc

**Comment by aetta** [comment]
+1 5984723-zen

**Comment by aetta** [comment]
Possibly one more here: 

5985984-zen

**Comment by sophiegyo** [comment]
I have issues on my Simple site when searching within the Media library too:
![image](https://user-images.githubusercontent.com/36608681/221147972-5ccfdfcf-2c3d-41d1-969f-4eb0b78058cd.png)

Same thing when searching in the Image block modal:
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/36608681/221148145-3e101651-5f81-4a18-bf1d-2e04a4d455b5.png">

Report from user:
https://wordpress.com/forums/topic/the-pexel-photos/?view=all

**Comment by allanftd** [comment]
Another case reported by a user today - 40567132-hc

**Comment by devNigel** [comment]
Another report: 35664159-hc

Followup: 5988958-zd-woothemes

**Comment by philnick206** [comment]
Another report here: 25748478-hc

Pointed to Openverse as an alternative

**Comment by deancroyal** [comment]
Reported here: 7385741-hc

**Comment by ebinnion** [comment]
This should now be fixed after shipping D102743-code.

**Comment by supernovia** [comment]
@ebinnion was this shipped? I'm getting errors currently

**Comment by supernovia** [comment]
I have a case here: https://wordpress.com/forums/topic/pexels-2/ and I've confirmed I can't bring up any images in searches.

**Comment by rosepajaroja** [comment]
Another case reported here: 9258331-hc

*Note the same issue happens for Google Photos.

**Comment by filipanoscampos** [comment]
Another one here 40917205-hc

**Comment by shameemreza** [comment]
Another one here 5987556-hc

**Comment by isocialtish** [comment]
Another case reported at 5990969-zen, and still seeing the error on my test sites

**Comment by hacchism** [comment]
Another case at 5992389-zen

**Comment by hacchism** [comment]
Another one at 5993526-zen

**Comment by rw-ye** [comment]
Another report: 5993008-zd-woothemes

**Comment by sophiegyo** [comment]
Another report: https://wordpress.com/forums/topic/the-wordpress-free-library-does-not-load/?view=all

**Comment by syhussaini** [comment]
Another report 5993755-zen

**Comment by syhussaini** [comment]
I just noticed the Pexel site is throwing **500 internal server error**

![image](https://user-images.githubusercontent.com/8070771/221405564-377097a9-8aba-400a-a866-6ace6f783c53.png)

**Comment by syhussaini** [comment]
Another report here: 5994225-zen

**Comment by syhussaini** [comment]
Another one: 5994331-zen
Advised them to use Google Photos or Openverse in the meantime.

**Comment by syhussaini** [comment]
> *Note the same issue happens for Google Photos.

@rosepajaroja I was able to get it working after disconnecting and reconnecting the Google Photos Account.
I updated the user on 5992278-zen

**Comment by bryandev602-gh** [comment]
Another report here: 5997019-zen

**Comment by danielk-am** [comment]
Another report here:

41056019-hc

**Comment by rinazrina** [comment]
Another one: #34051998-hc

**Comment by carolframen** [comment]
#5996464-zen another one

**Comment by syhussaini** [comment]
I noticed the Pexel site is back online, so I tested and found the images are now loading fine on the following:

- AT Site: https://d.pr/i/QD6HPc
- Simple Site: https://d.pr/i/IwSEsQ
- P2: https://d.pr/i/znFLl7

**Comment by synora** [comment]
The user and I in 41115759hc just tried on our Atomic sites and Pexel images aren't loading.

**Comment by ebinnion** [comment]
This was shipped. But, it appears that Pexels has been having issues and we're also working with them to increase our API limits for the key that we created.

**Comment by jorpdesigns** [comment]
Reported in 35289087-hc

- [ ] Follow-up ticket: 6002583-zd-woothemes

**Comment by desnum** [comment]
Another report 38559171-hc

**Comment by mdtanjid0** [comment]
- [ ] 5997328-zd ( needs to follow up ). 

As a workaround, I advised them to use https://www.pexels.com/.

**Comment by ccwalburn** [comment]
Another report here: 40221462-hc

**Comment by ebinnion** [comment]
Pexels reports that the limit has been lifted as of ~5 minutes ago.

**Comment by tvolpert** [comment]
reported in this chat. I suggested they try Openverse instead since that interface is still working

- [ ] 39980140-hc

**Comment by ebinnion** [comment]
I just looked into this again and we are still getting rate limited. I responded back to Pexels to ask them to confirm our rate limit increase.

**Comment by ebinnion** [comment]
I added MC stats for tracking response codes in D103264-code, adding a caching layer for all 200 requests in D103269, and then followed up with Pexels.

I will continue to follow up as I know more.

**Comment by synora** [comment]
Another report: 6005721
I've suggested they try Openverse.

**Comment by shameemreza** [comment]
Another report here: 5996195-hc. As a workaround, I advised using Openverse.

**Comment by dlaurisse** [comment]
another one here: 5991648-hc

**Comment by synora** [comment]
Reported in 6007440-zd-woothemes

**Comment by synora** [comment]
Reported in 6006111-zd-woothemes

**Comment by sguzovskaia** [comment]
Reported in 26058452-hc

**Comment by synora** [comment]
Reported in 6008070-zd-woothemes

**Comment by ebinnion** [comment]
Pexels has responded again this morning that they lifted the limits. I have observed that 429 response codes have stayed steady and 200 response codes are increasing, over the last several hours, so things seem actually fixed at this point.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Could Not Replicate**
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Thanks for the update @ebinnion ! From testing, it does appear this is resolved across Simple and AT sites.

**AT Example**

https://user-images.githubusercontent.com/27249804/222979673-d9803462-c6e3-48f5-8ea6-7703cfe3df39.mp4

**Simple Example**

![Markup on 2023-03-05 at 11:45:31](https://user-images.githubusercontent.com/27249804/222979679-1f815e1d-9867-4e99-9dd1-ad0ea75c231e.png)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
