### ISSUE TITLE
Add missing `is-style-white-gray-mono` class to the Email Login Section block

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#73723]
The Email Login Section block is missing `is-style-white-gray-mono` class that needs to be added in order for the block to work well with other Landpack blocks.

Related discussion: p1677154477391449/1677142611.098769-slack-C02TCEHP3HA.

**Comment by yansern** [comment]
Switched over to a master block. https://github.com/Automattic/landpack/pull/1256
We'll just continue to add the custom class when adding the block.
