### ISSUE TITLE
Post editor domain upsell: Swap globe icon

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#73727]
We need to replace the gridicon in this upsell (and in identical upsells, like site preview and Launchpad). See p1676463651153569/1676362885.292659-slack-C03TDMUSUSG

![Image](https://user-images.githubusercontent.com/1689238/220951720-f2f2e796-56c2-4d09-b5c8-bba054e28faa.png)

Acceptance criteria:
- [x] We're no longer using a gridicon.
- [x] Instead, use [the Gutenberg globe icon](https://github.com/WordPress/gutenberg/blob/trunk/packages/icons/src/library/globe.js). [Preview here.](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library) Import using `'@wordpress/icons'`.

**Comment by DustyReagan** [comment]
Update domain upsell globe icon on "Preview in new tab" here: D103918-code
