### ISSUE TITLE
Atomic Transfer Dialog component should be functional

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#73731]
The Atomic Transfer Dialog component would be better implemented if it was functional.

https://github.com/Automattic/wp-calypso/pull/72665#discussion_r1108184105

**Comment by markbiek** [comment]
Confirming that this still needs to be done.

**Comment by sixhours** [comment]
We're unlikely to get to this in the next year. Closing as wontfix for now.
