### ISSUE TITLE
[Paid Newsletters] When Stripe is disconnected - the Newsletter Access panel remains visible but the access options are unable to be selected

### ISSUE THREAD

**Issue by romarioraffington** [Automattic/wp-calypso#73746]
## Description

When a site has newsletter enabled and stripe is disconnected, the newsletter panel remains visible but its options are unable to be selected

<img width="1167" alt="Screenshot 2023-02-23 at 6 55 21 PM" src="https://user-images.githubusercontent.com/7076981/221058369-1c8cf9f9-0660-4f62-a62c-7039f4c2b83e.png">

## Steps to Reproduce

1. Connect Stripe and create a post with a newsletter access option
2. Disconnect Stripe
3. Return to the post and refresh. Notice the newsletter options are unable to be selected

**Comment by artpi** [comment]
@millerf I remember you had a fix for that in one of your new PRs?

**Comment by millerf** [comment]
> @millerf I remember you had a fix for that in one of your new PRs?

Yes, in https://github.com/Automattic/jetpack/pull/29042
> Fixed a regression where there actual newsletter visibility is not displayed

**Comment by artpi** [comment]
I think i independently fixed it in #29247

**Comment by artpi** [comment]
https://github.com/Automattic/jetpack/pull/29247/files is merged, this is fixed now
