### ISSUE TITLE
Pattern Assembler - Remove the 8px padding from pattern previews

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#73759]
### Description

Let's remove the `8px` padding from the pattern previews (small and large). It's introduced by `.editor-styles-wrapper`.

![Image](https://user-images.githubusercontent.com/1881481/221131710-b6e3c941-4fa1-4072-8bff-f3e3fcfd8eba.png)

|Before|After|
|-|-|
|![Image](https://user-images.githubusercontent.com/1881481/221131620-5bcee952-eac2-4e68-8ac5-c9027fbac9b2.png)|![Image](https://user-images.githubusercontent.com/1881481/221131597-020d7ebd-b895-40db-a2e7-8e4c67807bfb.png)|

#### Why?
The previews look much better without it. Also, that padding is not visible in the editor or the front of the site, and the site preview in the assembler should look "like" the front of the site.

![Image](https://user-images.githubusercontent.com/1881481/221131757-2ef62caa-a3d0-4872-92a4-f3903a1eae3c.png)

**Comment by arthur791004** [comment]
Closed it via https://github.com/Automattic/wp-calypso/pull/74033
