### ISSUE TITLE
Pattern Assembler - Use a single iframe for the large preview

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#73757]
Currently, we use an iframe per pattern while the editor uses only one for all.

See this [comment](https://github.com/Automattic/wp-calypso/issues/73072#issuecomment-1439392389).

**Comment by okmttdhr** [comment]
After combining all into a single iframe,

>https://github.com/Automattic/wp-calypso/issues/73072#issuecomment-1439392389
>It's easy to add the action bar to each pattern in the large preview so users are able to replace/reorder/delete patterns when they browse the large preview. If we put them in a single iframe, we have to use inline styles to style the action bar in the iframe. But if we don't want to display the action bar on the large preview in the future, we can consider displaying them in a single iframe

I think it would be nice in the end to be able to have ⬆️ (the pros of using multiple iframe) as well.
(Though I haven't looked into the implementation in depth yet.)

**Comment by miksansegundo** [comment]
> ...easy to add the action bar to each pattern in the large preview

I think we could add the action bar in the future (or find a solution when that feature is on the roadmap) without using multiple iframes; not sure why @arthur791004 mentioned that. 

We should use a single iframe to apply global styles to the canvas (background of the patterns). See the next screenshot. Single iframes are introducing styling issues:

![image](https://user-images.githubusercontent.com/1881481/222306914-06385d10-428b-4a0f-ab46-84427cb2c1da.png)

**Comment by miksansegundo** [comment]
Moving this issue to the backlog because the action bar is already shipped and we still have to discuss the pros/cons of using a single iframe. cc: @Automattic/lego

**Comment by arthur791004** [comment]
Hold this on as we're not able to fix the issues related to jetpack blocks. We can come back to this again when we have a strong opinion to use the single iframe to resolve the viewport issue, floating action bar, etc

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
