### ISSUE TITLE
Launchpad: Update tests for domain upsell task

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#73777]
### Details

I'm just creating a quick placeholder / follow up issue for this PR: https://github.com/Automattic/wp-calypso/pull/73772

We may want to update our tests for the domain upsell task to confirm that the task is complete / incomplete based on whether plan is free / paid. See this comment for more context: https://github.com/Automattic/wp-calypso/pull/73772#discussion_r1117419000

**Comment by Addison-Stavlo** [comment]
closing this since the above unit test PR was merged.
