### ISSUE TITLE
Payment Button Block has sporadic "subscribe.wordpress.com redirected you too many times" error

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#73788]
### Quick summary

User reported this in chat and I created follow-up ticket: 5990746-zd-woothemes

The [Payment Button Block](https://wordpress.com/support/wordpress-editor/blocks/payments/#payment-button-block) will sporadically have a 301 redirect loop that shows the error: `subscribe.wordpress.com redirected you too many times` in Chrome. This happens when clicking on the button when the popup is supposed to display. No popup displays and only a redirect loop occurs. This is sporadic and does not seem to happen all of the time, however, I was able to reproduce consistently on Simple and Atomic test sites. 

When the redirect loop **does not** occur and the button works fine, I noticed that the following header is returned:
`content-security-policy: frame-ancestors http://sometestsite33.sometestsite.com http://sometestsite33.sometestsite.com;`

There is no content-security-policy header returned when the redirect loop happens and this missing header seems related to the problem.

This recording is in Safari 16.1 where it just displays a spinner after clicking. User was reporting similar behavior on mobile:
![PCx2F6.gif](https://user-images.githubusercontent.com/121042930/221362031-2c557709-1667-4984-b03a-3f0a6197111f.gif)

### Steps to reproduce

1. Create a Simple or Atomic test site
2. Create a new page and add a Payment Buttons Block 
3. Connect Stripe
4. Add a new payment plan such as a yearly subscription and publish the page
5. Visit the page on another computer while not proxied or logged in and test clicking the button to see if it works while monitoring network requests. 
6. If it 301 redirect loops, review the response headers for the URL and see if a content-security-policy header is returned (shouldn't be). You should see multiple 301 redirects for URLs like the following: https://subscribe.wordpress.com/memberships/?blog=212139807&plan=333&lang=en&pid=328&redirect=https%3A%2F%2Fsometestsite33.sometestsite.com%2Febooks&display=alternate
7. If it doesn't 301 redirect loop and button works fine, do the same header check on the URL (content-security-policy should be returned).

### What you expected to happen

The button should always load the popup for users to pay and a content-security-policy should always be returned.

### What actually happened

The content-security-policy is not always returned and causes a 301 redirect loop. The popup does not display and users are unable to pay. 

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

This may not be reproducible when proxied or logged in. I originally reproduced while not proxied or logged in Chrome 110.0.5481.178 on a Windows 10 test box. I also reproduced on Ventura 13.0.1 in Safari 16.1 and Chrome 110.0.5481.100.

**Comment by retnonindya** [comment]
Another report. Followup ticket: 5997296-zd-woothemes

The user wants to be updated once the issue is fixed.

**Comment by formosattic** [comment]
+1 5995996-zd-woothemes

Notify the user once fixed.

**Comment by ariel-maidana** [comment]
5996537-zd-woothemes
Issue happens with Firefox as well.
Please notify the user when fixed.

**Comment by thesacredpath** [comment]
Another report here 41079853-hc
Follow-up: #5999504-zd

**Comment by rw-ye** [comment]
5997296-zd-woothemes replied and let us know that this bug is impacting their sales.

**Comment by mgozdis** [comment]
Another report: 5998410-zd-woothemes

**Comment by yansern** [comment]
It appears that browsers treats urls with `&` and without `&` at the end as the same URL, and apply disk caching to it.
In our case, it cached the 301 redirection, and resulted in an infinite redirection loop.

The removal of the `&` in this case is unnecessary and it is being done by `redirect_canonical` function, so we'll need to find out how to workaround this issue.

Initial call that wasn't cached.
![image](https://user-images.githubusercontent.com/1287077/222362604-9597af19-017e-4eb9-8f9d-32a852d31725.png)

Redirected without `&` but 301 was being cached.
![2023-03-02_09-34-23](https://user-images.githubusercontent.com/1287077/222362510-953e7d97-09ba-42a5-90b0-84e9c197c564.png)

Stack trace that shows that the removal of `&` is happening on the `redirect_canonical` function.


![2023-03-02_09-33-38](https://user-images.githubusercontent.com/1287077/222362952-dcef2f49-285b-4b3e-9ef6-ead1a70f9028.png)

**Comment by yansern** [comment]
The function [tb_show()](https://github.com/Automattic/jetpack/blob/94ddae8284758db97529fad30752b9e11a556bb1/projects/plugins/jetpack/extensions/shared/memberships.js#L24) leaves a trailing `&`. We generate URLs without them, that's where the trailing `&` is eventually added.

I have tried switching the param order around from `&display=alternate&TB_iframe=true` to `&TB_iframe=true&display=alternate` but it still leaves a trailing `&`.

Since Thickbox is a third-party library, we can't fix it there, we can only ensure that redirection doesn't happen on `redirect_canonical`.

It is likely possible to circumvent redirection if a filter was added on `redirect_canonical`. I'm now looking into that.

**Comment by yansern** [comment]
Patch is ready for review D103305-code.

This will prevent trailing ampersand `&` from being redirected.

Once the patch is rolled in, however, for users where browsers have the 301 redirects already cached on disk, the only thing to do is to let time pass and the cache expire, or press Shift+F5 / Shift+Cmd+R for hard refresh, or for the site owners who reported the issue on zendesk to just clear their cache in the meantime.

**Comment by druesome** [comment]
Seems to be happening for this user as well, but on a premium content block: 6008416-zd

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by rickmgithub** [comment]
I'm afraid this user has come back saying the issue isn't fixed - 5997296-zd

**Comment by cuemarie** [comment]
Hi @rickmgithub , 

Can you see if the user who has re-reported the issue can resolve with the cache clearing steps noted [in the comment above](https://github.com/Automattic/wp-calypso/issues/73788#issuecomment-1451600828)?

📌 ACTIONS
- Await feedback

**Comment by ha-un** [comment]
Hi @cuemarie - I played into thish ticket and requested to ask their subscriber to try clearing cache.

**Comment by serabi** [comment]
The user has decided to accept that there will be "occasional glitches" and doesn't want to continue trouble-shooting at this time.

**Comment by cometgrrl** [comment]
> The user has decided to accept that there will be "occasional glitches" and doesn't want to continue trouble-shooting at this time.

Closing based on this.
