### ISSUE TITLE
Onboarding - Re-add the progress bar in /site-setup flows

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#73798]
Related https://github.com/Automattic/wp-calypso/pull/73653

Due to the fragility of the progress bar, it is removed from the `/site-setup` flow until we have a more maintainable version. See pbxlJb-3wV-p2

**How can we make it more maintainable?**

- [ ] Adapt the progress bar dynamically to the changes in the flow steps
- [ ] Consider not adding it back and rethink the UX benefits of this progress bar. Maybe there is a chance to think outside of the box to create a different kind of progress bar or a different logic. 
- [ ] Try with a simple `Step -> Progress` mapping, as in [useFlowProgress](https://github.com/Automattic/wp-calypso/blob/f2c930ff425f2858cea33c93073aca0dbce37667/packages/onboarding/src/flow-progress/use-flow-progress.ts#L66), to reduce the complexity and bugginess in the [useSiteSetupFlowProgress](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/hooks/use-site-setup-flow-progress.ts) hook.
- [ ] Move the steps to a more visible/maintainable place, like the flow declaration. See https://github.com/Automattic/wp-calypso/issues/71401.

**Comment by taipeicoder** [comment]
We can revisit this issue once there's more interesting in reinstating the progress bar in the onboarding flows.
