### ISSUE TITLE
Login Link Email: Slice & dice Login Link Email into actionable tasks.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73804]
Build the Login Link Email. Figma link: [inDLaEQV8jJ21O4WXawIsJ-fi-200%3A3664](inDLaEQV8jJ21O4WXawIsJ-fi-712%3A14749)

This task is considered complete when the [Apex Project Board > Subscription Management](https://href.li/?https://github.com/orgs/Automattic/projects/431/views/3) project board is filled up with actionable tasks for the Login Link Email.

**Comment by JuanLucha** [comment]
4 tasks has been created out of the new design of the Login Link Email:

https://github.com/Automattic/wp-calypso/issues/73812
https://github.com/Automattic/wp-calypso/issues/73809
https://github.com/Automattic/wp-calypso/issues/73810
https://github.com/Automattic/wp-calypso/issues/73811

Closing this preparation task as completed.
