### ISSUE TITLE
Login Link Email: Find a way to speed up the testing of Login Link Email.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73806]
Find a way to help speed up the process of testing the Login Link Email, whether it is:
- manual: creating a test instructions that everyone can follow
- or automated: modifying the send-script to support the login link email
- or via the email preview tool.
- or something else.

**Comment by ivan-ottinger** [comment]
→ I have created a new page manual testing and testing with Email on Acid: PdDOJh-1Bb-p2. 
→ Next, I will look at the options with the send-script

**Comment by ivan-ottinger** [comment]
D102881-code patch that add a new send-script is now ready for review.

**Comment by ivan-ottinger** [comment]
There's one more patch that will allow us to test the new email template with Email on Acid: D103196-code.

**Comment by ivan-ottinger** [comment]
D103196-code is now merged and deployed.

---

I am closing this task with the following results:
- We have testing instructions available at PdDOJh-1Bb-p2.
- It is now possible to test the new email template with the _Email on Acid_ tool: PdDOJh-1Bb-p2.
