### ISSUE TITLE
Portal: Scaffold a /subscriptions page on Calypso.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#73803]
- Create a route entry for `/subscriptions` on Calypso.
- It should render a page with a placeholder SubscriptionManagement component.
- Hide it behind a feature flag.

The purpose of this page is just to help us to spike further.

**Comment by mashikag** [comment]
Actually it is not very clear to me what are we planning to implement in Calypso. 
Is the final goal to have the whole Subscription Portal, for the logged-in users, re-implemented in Calypso?

I am asking because if this is the case then we should probably create a package for it.

**Comment by yansern** [comment]
> Actually it is not very clear to me what are we planning to implement in Calypso.
Is the final goal to have the whole Subscription Portal, for the logged-in users, re-implemented in Calypso?

That is correct.

> I am asking because if this is the case then we should probably create a package for it.

Yes, that is beyond the scope of this issue, which is just scaffolding.
