### ISSUE TITLE
Login Link Email: Scaffold the new email

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#73812]
## The goal of the task
The design for the new Login Link email can be found here: inDLaEQV8jJ21O4WXawIsJ-fi-200%3A3664

This task consists in the implementation of the scaffolding of the email itself, as the one being sent right now is a text output. With just a bare minimum `<div>` with some text is enough, but It should be behind a feature flag, like `subscriptions/login-link` so the old email is still sent in production.

TODO: Add stuff related to EN/non-EN sending of emails.

## What's the Login Link email anyway?
The Login Link email is the email the user receives after, being logged out in the subscription page, enters an email and click the `Send me a link` button.

![Image](https://user-images.githubusercontent.com/3832570/221525759-b2ebe6da-be41-4b52-a5ff-2beff4f6c355.png)

**Comment by ivan-ottinger** [comment]
Just noting that the feature flag has been added through D102897-code.

**Comment by ivan-ottinger** [comment]
Just noting that the D102909-code patch which is adding the email template scaffolding is now merged deployed.
