### ISSUE TITLE
Login Link Email: Create New Account section

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#73810]
## The goal of the task
The design for the new Login Link email can be found here: inDLaEQV8jJ21O4WXawIsJ-fi-200%3A3664

This task consists in the implementation of the second part, the section of the email with the action to create a new WordPress.com account. That section can be found selected here: inDLaEQV8jJ21O4WXawIsJ-fi-200%3A3709

![Image](https://user-images.githubusercontent.com/3832570/221526218-b7af2574-5a5b-4afe-bdf1-d896e927ba3e.png)

## What's the Login Link email anyway?
The Login Link email is the email the user receives after, being logged out in the subscription page, enters an email and click the `Send me a link` button.

![Image](https://user-images.githubusercontent.com/3832570/221525759-b2ebe6da-be41-4b52-a5ff-2beff4f6c355.png)

**Comment by yansern** [comment]
Pasting it here to make it easier to find the link to the patch. D103431-code

**Comment by ivan-ottinger** [comment]
D103431-code has been merged and deployed to production. → Closing this task.
