### ISSUE TITLE
Login Link Email: Footer section

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#73811]
## The goal of the task
The design for the new Login Link email can be found here: inDLaEQV8jJ21O4WXawIsJ-fi-200%3A3664

This task consists in the implementation of the third part, the section of the email with the footer links. That section can be found selected here: inDLaEQV8jJ21O4WXawIsJ-fi-200%3A3774

![Image](https://user-images.githubusercontent.com/3832570/221526880-1950d925-54f9-48cb-bc96-af95b50631d7.png)

## What's the Login Link email anyway?
The Login Link email is the email the user receives after, being logged out in the subscription page, enters an email and click the `Send me a link` button.

![Image](https://user-images.githubusercontent.com/3832570/221525759-b2ebe6da-be41-4b52-a5ff-2beff4f6c355.png)

**Comment by ivan-ottinger** [comment]
Looks like the footer presented in the design haven't been merged to production yet. If I am not mistaken, once the following patch is in: D99533-code, we will be able to reuse the footer for our new email template as well.

**Comment by ivan-ottinger** [comment]
The D99533-code patch that introduces the new footer component has been already merged.

→ I am working on adding this new footer to our new template as well.
→ Asked a couple of things in inDLaEQV8jJ21O4WXawIsJ-fi-712:14749.

**Comment by ivan-ottinger** [comment]
D99533-code patch is now ready for review.

**Comment by ivan-ottinger** [comment]
D99533-code is now merged and deployed.
