### ISSUE TITLE
Spanish domains page, search not working 

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#73827]
### Quick summary

On the domains page in Spanish, the Search button doesn’t work.

### Steps to reproduce

Go to https://wordpress.com/es/dominios/
Add a domain name, e.g. wp101.com
Click on ‘Buscar’ (Search)

### What you expected to happen

I would expect the button to perform some action or view information about the domain.

### What actually happened

Nothing happens the button doesn’t work.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described; the `Buscar` "button" just looks like text, and does not respond.  Keying `ENTER` also does not search for the domain.

https://user-images.githubusercontent.com/27249804/222979889-19ba5577-70a3-44b6-a705-d687c69ea0f4.mp4

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by emilyaudela** [comment]
The domains button should be fixed on the Spanish landing page now. Thanks for reporting!
