### ISSUE TITLE
Pingback missing

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#73821]
### Quick summary

From  2023-2-15 23:28 pingback at ttcath.org missing

### Steps to reproduce

1. https://wordpress.com/comments/all/ttcath.org
2. pingback at ttcath.org missing

### What you expected to happen

pingback at ttcath.org must work 

### What actually happened

From  2023-2-15 23:28 pingback at ttcath.org missing

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

**Comment by ttcath** [comment]
@tyxla  pls help to fix the problems. Because WordPress.com Support Team cannot solve it proper.

**Comment by tyxla** [comment]
Hi @ttcath, could you please describe your issue in detail?

**Comment by ttcath** [comment]
@tyxla 

1. I create a post like : https://ttcath.org/2023/02/24/lc-w1-lent-a-2023-cn-grm/
2. everyday, I add four link into the post.
3. Once I finished add the link, I press renew
4. but at here https://wordpress.com/comments/pending/ttcath.org the pingback missing

This problem was reported to WordPress.com Support Team via Email at 2023.2.26, till now, the pingback still missing.

Pls do the investigation, restore missing pingback.

**Comment by tyxla** [comment]
@ttcath I've glanced through `/wp-admin/edit-comments.php?comment_status=approved` and can see quite a few approved pingbacks. The latest few ones are from today. That confirms that pingback functionality is working fine. 

Perhaps there is a specific scenario that doesn't work as to your expectations? Here's more info on pingbacks in case that helps:

https://wordpress.com/support/comments/pingbacks/

**Comment by ttcath** [comment]
nope. from date 2023.2.10 to 2023.3,1, eveyday, I add 4 pingback on the post, but the entire pingbacks missing. 

Please find the logs at

https://wordpress.com/activity-log/ttcath.org?after=2022-12-31+16%3A00%3A00&before=2023-02-01+15%3A59%3A59&group=pingback

**Comment by tyxla** [comment]
I see, thanks for elaborating, @ttcath! 

This appears to be a known issue - see #68245. 

Feel free to provide any useful information there.

In the meantime, I'll close this one as a duplicate.

**Comment by ttcath** [comment]
@tyxla ok, once I find more information, I will leave them at this tickets.

**Comment by ttcath** [comment]
@tyxla  looks like some missing pingback from 2023.2.25 to 2023.2.28 restore, rest pingback from date 2023.2.10 to 2023.3,1, eveyday, I add 4 pingback on some post on the same site still missing, but the link added work.

**Comment by ttcath** [comment]
Dear @tyxla 

Today, I add two pingback into a post, but pingback is missing

https://ttcath.org/2023/03/10/intenzioni-di-preghiera-del-santo-padre-2024-cim-cn/
https://ttcath.org/2023/03/10/intenzioni-di-preghiera-del-santo-padre-2024-tra-cn/

both two links add as pingback into those two posts 
https://ttcath.org/2023/03/27/prot-13-23-tt-tra-cn/
https://ttcath.org/2023/03/27/prot-13-23-tt-sim-cn/

So, totally, there must be 4 pingpacks, but in fact, none.
