### ISSUE TITLE
Display Thank You page when installing WooCommerce theme

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#73836]
Parent task: 
- https://github.com/Automattic/wp-calypso/issues/72703

**Comment by epeicher** [comment]
This should be reviewed with Product Ambassadors before proceeding, as indicated in p58i-e3f-p2

**Comment by cpapazoglou** [comment]
AFAIK woocommerce themes have a specific flow that kicks in after purchase. Let's verify if that flow always kick in when:
- buying a woocommerce theme
- buying a second woocommerce theme after having completed the flow for the first one

**Comment by epeicher** [comment]
> AFAIK woocommerce themes have a specific flow that kicks in after purchase. Let's verify if that flow always kick in when:
> 
> * buying a woocommerce theme
> * buying a second woocommerce theme after having completed the flow for the first one

I have verified that the above is the current flow: 
- For the first WooCommerce theme, the Woo-specific flow triggers. After completing the flow, the Theme details page is displayed.
- For subsequent WooCommerce themes, the Woo flow does not trigger. An installation screen is displayed first, and after it completes, the Theme details page is displayed with the theme Active.

**Comment by epeicher** [comment]
After an initial investigation, I have identified:
- The redirection to the Woo flow is done [here](https://github.com/Automattic/wp-calypso/blob/bcf6117fca12838a09687598675ca8d1e4a2e435/client/my-sites/themes/thanks-modal.jsx#L96)
- The Woo flow is defined [here](https://github.com/Automattic/wp-calypso/blob/bcf6117fca12838a09687598675ca8d1e4a2e435/client/landing/stepper/declarative-flow/plugin-bundle-flow.ts#L32)
- The other Premium and Free flows are handled in the action as opposed to the UI so the code to redirect to the Woo flow could be moved from [here](https://github.com/Automattic/wp-calypso/blob/bcf6117fca12838a09687598675ca8d1e4a2e435/client/my-sites/themes/thanks-modal.jsx#L96) to [the activate action](https://github.com/Automattic/wp-calypso/blob/bcf6117fca12838a09687598675ca8d1e4a2e435/client/state/themes/actions/activate.js#L107)
- The condition that avoids running the Woo flow more than once is [here](https://github.com/Automattic/wp-calypso/blob/bcf6117fca12838a09687598675ca8d1e4a2e435/client/landing/stepper/declarative-flow/plugin-bundle-flow.ts#L164) that eventually calls the [CheckForWoo step here](https://github.com/Automattic/wp-calypso/blob/bcf6117fca12838a09687598675ca8d1e4a2e435/client/landing/stepper/declarative-flow/internals/steps-repository/check-for-woo/index.tsx#L34). 
- That condition is that the `WooCommerce` plugin is installed. [Code here](https://github.com/Automattic/wp-calypso/blob/bcf6117fca12838a09687598675ca8d1e4a2e435/client/landing/stepper/declarative-flow/internals/steps-repository/check-for-woo/index.tsx#L26)

**Comment by epeicher** [comment]
Draft PR created https://github.com/Automattic/wp-calypso/pull/75887

**Comment by epeicher** [comment]
The PR https://github.com/Automattic/wp-calypso/pull/75887 has been updated with an implementation, but it still requires some additional investigation.

**Comment by epeicher** [comment]
The PR https://github.com/Automattic/wp-calypso/pull/75887 has updated to `Needs Review` and the found issues will be treated as follow-up tasks as described in a Note the description [here](https://github.com/Automattic/wp-calypso/pull/75887#issue-1672936009)
