### ISSUE TITLE
Display Thank You page when purchasing a Marketplace theme

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#73838]
Parent task: 
- https://github.com/Automattic/wp-calypso/issues/72703

**Comment by WBerredo** [comment]
On the cart step we will need two additional information on the `extra` object of marketplace themes: 
* `is_marketplace_product ` set to `true`
* the theme slug to mount the thank you page URL

---

Currently when we receive the plugin information on cart we use two infos from the extra object: `is_marketplace_product`
and `plugin_slug`
We use it to identify if we should redirect to the marketplace thank you page and to mount the url with the proper slug

**Comment by WBerredo** [comment]
On the cart step we will need two additional information on the `extra` object of marketplace themes: 
* `is_marketplace_product ` set to `true`
* the theme slug to mount the thank you page URL

---

Currently when we receive the plugin information on cart we have this info on the extra object: `is_marketplace_product`
and `plugin_slug`
We use it to identify if we should redirect to the marketplace thank you page and to mount the url with the proper slug

---

discussion:  p1678098925961309-slack-C02JPCHEKDY

**Comment by epeicher** [comment]
This task will be closed in favor of the following:
- https://github.com/Automattic/wp-calypso/issues/73995
- https://github.com/Automattic/wp-calypso/issues/74295
- https://github.com/Automattic/wp-calypso/issues/74371
