### ISSUE TITLE
Login Link Email: Prepare language pack.

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#73831]
The goal of this task is to create and merge a WPCOM patch that will introduce the language strings and make them available for translation. This will make sure we will have the translations ready by the time when we will be launching the new email template to public.

Email template design: inDLaEQV8jJ21O4WXawIsJ-fi-200%3A3664.

**Comment by ivan-ottinger** [comment]
D102998-code is now ready for review.

**Comment by yansern** [comment]
Thanks and done.
