### ISSUE TITLE
LaunchPad - Email Verification Task

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#73868]
As discussed in our team meeting yesterday - paYE8P-2zy-p2 we want to add a "verify email" task to all launchpad flows.

- [x] Other checklist items will not be usable until this task is completed
- [x] The task can lead nowhere, and @nuriapenya notes its ok to disappear once completed.
- [x] We can remove the "verify email" banner from newsletters once complete.

cc @nuriapenya if you have other info on what the task should look like, notes/descriptions, or anything else to share related to this item.

**Comment by nuriapenya** [comment]
Requirements sound good 👍🏽 

Copy: `Verify email address`

Let's start with this minimal approach; later on, we can iterate based on observations. Maybe some improvement ideas could be a tooltip with more info, a change copy, etc. But for now, let's do it like this:

📍 Here's [the design](9wpoYJrMlYKAKUYvVBMN74-fi-2553%3A10598)
<img width="1440" alt="Launchpad - Email task" src="https://user-images.githubusercontent.com/7931304/221858631-9c47a997-0695-4f84-9f69-f1314db1788c.png">

**Comment by edanzer** [comment]
Updates: 

There was additional discussion of this issue on slack, and there is uncertainty about whether this task should be added to all flows. See: p1677754610259639/1677618619.287359-slack-CHN6J22MP

In the meantime, we've added this task to the Newsletter flow here: https://github.com/Automattic/wp-calypso/pull/74135

**Comment by edanzer** [comment]
Marking this as complete. The PR to add this to the Newsletter flow is linked above. And [this PR](https://github.com/Automattic/wp-calypso/pull/74489/files) removes the EmailVerificationBanner from launchpad.
