### ISSUE TITLE
Login Link Email: Implement send, open and click email tracking

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#73877]
The new email template should include tracking for the following three events: send, open and click.

Update:

Here are the link_desc values we are going to use for both buttons in the email:

- Manage subscriptions → `subscriptions-manage`
- Create and account → `subscriptions-cta-create-account`

**Comment by ivan-ottinger** [comment]
When it comes to the `send`, `open` and `click` events, would you say these information: 2f4f5-pb is enough? Or are we aiming to get something more out of those events?

Link with screenshots: 2f4fc-pb (if the view of events on the previous link expires)

@yansern @JuanLucha

**Comment by yansern** [comment]
For the click event, also ensure that the Create an Account CTA has a click event attached to it as well.

And if we can document it (what's the email name, what are the click link desc names, etc.) in a table here or on docs somewhere, then all is good.

**Comment by ivan-ottinger** [comment]
Perfect! Thank you for your feedback, Yan. We could add a new section to the email doc for instance: PdDOJh-1Bb-p2.

**Comment by ivan-ottinger** [comment]
> For the click event, also ensure that the Create an Account CTA has a click event attached to it as well.

@JuanLucha has already included `manage-subscriptions` as the `link_desc` in the main CTA button (in D103286-code):
![Markup on 2023-03-03 at 11:07:47](https://user-images.githubusercontent.com/25105483/222692806-47c6a433-ff40-4adb-85cb-2bb3e6c12c70.png)

If there are no objections, I think that for the other button we could use `create-account`:
![Markup on 2023-03-03 at 11:08:12](https://user-images.githubusercontent.com/25105483/222692822-66d65497-f900-41e2-ade7-abc470e76952.png)

**Comment by yansern** [comment]
> If there are no objections, I think that for the other button we could use `create-account`.

Let's follow the `context-action` convention for link descriptors. Here are some suggestions:

- `subscriptions-manage`
- `subscriptions-cta-create-account`

Also cc @JuanLucha 

Adding D103286-code and D103431-code for quick access.

**Comment by ivan-ottinger** [comment]
I have added a new section with tracking details: PdDOJh-1Bb-p2. → Marking this task as `Done`.
