### ISSUE TITLE
Improve WooExpress store setup loading UX

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#73872]
Currently, it takes about 85 seconds to finish store setup. I've timed the sequences, the steps take approximately:

1. Woo! We’re creating your store: 56 seconds
2. Applying the finishing touches: 10 seconds
3. Turning on the lights: 18 seconds

There's also a mismatch with the font used, I assume it's currently the default font used by calypso.

### Acceptance criteria

1. Update the `#FunWooFact` font to the font specified in figma lD0gTB4IqGsmSmsnjZNaP6-fi-1%3A3420.
2. Distribute the texts more evenly. I think we don't have to consider the actual [steps](https://github.com/Automattic/wp-calypso/blob/86094797dd2ec8b40d56da54468efeca8f143e0a/client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/hooks/use-processing-loading-messages.ts#L26) since it's not really relevant to user.
3. Add loading copies as interim solution to the long loading time lD0gTB4IqGsmSmsnjZNaP6-fi-1:9762

**Comment by ilyasfoo** [comment]
@rjchow The new copies have been finalized, and we now have 6 loading items. lD0gTB4IqGsmSmsnjZNaP6-fi-1%3A3420

We should be able to rotate 10 - 15 seconds each, with the last one set for the longest duration in case it's more than 85 seconds.

Also, note the "#FunWooFact: Our favorite color is purple" has an SVG icon instead of an emoji

**Comment by rjchow** [comment]
I might not be able to complete all of the acceptance criteria by today - the current messages loader only takes a string so there are two consequences of that:
1. the #FunWooFacts tag can't be bolded because I can't selectively apply CSS to the first part of the string
2. I can't put a SVG purple heart in :(

**Comment by ilyasfoo** [comment]
@rjchow  Oof that's a bummer. Is it something that's overly complicated, or do you think it only requires some time for us to investigate how to make the change?

cc @verofasulo there are some complications to customising loading screen to Woo-specific styling since it's a shared component.

**Comment by rjchow** [comment]
It's not super complicated I'm just not confident of making it by today 🤣 

The code's over here:

https://github.com/Automattic/wp-calypso/blob/6f89b5e03342bd79b7645185deac8ee7d62006c3/client/landing/stepper/declarative-flow/internals/steps-repository/processing-step/index.tsx#L134

So the changes that need to be done is probably to make either subtitle capable of taking React components or define separately another field that's not related to subtitle and use that.

**Comment by rjchow** [comment]
Took a screencap of the times taken for each defined stepData.currentStep in calypso for posterity:



![Image](https://user-images.githubusercontent.com/27843274/222676567-84596bc6-d926-400d-bbda-8b786b4c96df.png)


siteCreationStep: ~5s
waitForAtomic: ~27s
undefined (??): ~12s

So I'll split the steps into [1 message, 2 messages, ..rest]

**Comment by ilyasfoo** [comment]
Yours are only 44 seconds? That's 2x faster than my setup 😭 

Wonder if the performance issue is intermittent? But I guess having more messages is much better than fewer anyway, we can always skip some of them if they're not required.

> So the changes that need to be done is probably to make either subtitle capable of taking React components or define separately another field that's not related to subtitle and use that.

Sounds good!

**Comment by rjchow** [comment]
It's probably overall server loads etc, it is Friday today after all

**Comment by adrianduffell** [comment]
@rjchow Is this closed by https://github.com/Automattic/wp-calypso/pull/73980, or is there still more to do?

**Comment by rjchow** [comment]
It's done!
