### ISSUE TITLE
WooExpress Small: Add monthly billing product and plans

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#73888]
We need to add the billing product, billing plans, and legacy store product for the monthly Medium-Woo plan.

Billing plan pricing in peapX7-1Q7-p2.

**Comment by nelsonec87** [comment]
`test_store_products` id `1054`
`test_billing_plans` slug `wp-bundle-wooexpress-small-monthly-<currency>-2023-02-28`
`test_billing_products` product_slug `wp-bundle-wooexpress-small`
