### ISSUE TITLE
Login Link Email: Create the template header section

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#73892]
The goal of this task is to add the following header with WordPress.com logo:

![Image](https://user-images.githubusercontent.com/25105483/221907081-da4729ca-2355-4735-9738-f7fd42815b07.png)

- the logo should be PNG24, retina and displayed at 48 px height in the email
- the logo should display correctly on all screen sizes

Design: inDLaEQV8jJ21O4WXawIsJ-fi-200%3A3664

**Comment by ivan-ottinger** [comment]
Opened discussion in inDLaEQV8jJ21O4WXawIsJ-fi-200:3664.

**Comment by yansern** [comment]
Set the logo height to 24px for now as what's in the design. The switch to 32px should be fairly easy if needed.

**Comment by ivan-ottinger** [comment]
> Set the logo height to 24px for now as what's in the design. The switch to 32px should be fairly easy if needed.

I have actually implemented the change yesterday, just haven't asked for the review yet. 🙂

**Comment by ivan-ottinger** [comment]
I have added requirements to the issue description.

**Comment by ivan-ottinger** [comment]
Just noting that the D103154-code patch is now ready for review. @JuanLucha

**Comment by ivan-ottinger** [comment]
D103154-code is now merged and deployed.
