### ISSUE TITLE
Domains: When removing a domain mapping record, the product seems wrong

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#73908]
### Quick summary

When I attempt to remove a secondary domain mapping record for a site, at the top of the screen there's a mention of:

"Remove product eric.blog"

Which doesn't seem technically correct to me and kind of scared me. 😄 

<img width="1395" alt="Screenshot 2023-02-28 at 4 43 28 PM" src="https://user-images.githubusercontent.com/1126811/221999500-8acc1635-f936-4445-9fd2-3be645290fd6.png">

### Steps to reproduce

1. Have more than on domain for a site
2. View settings
3. Click "Delete"
4. Arrive on the page above

### What you expected to happen

For the domain that I'm deleting to be the domain mentioned.

### What actually happened

My primary domain was mentioned.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by villanovachile** [comment]
Resolved with #74027
