### ISSUE TITLE
Payton | Cannot use full width images in single post template

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#73952]
### Quick summary

Cannot use blocks (image/cover/group) to make images with full width though the theme supports full site editing in single post template.

### Steps to reproduce

1. Try a default theme like Twenty-Twenty Two and make a new post with an image set to full width
2. Change the theme to Payton
3. Change the image width to something else
4. Now try to change the width to full width again, and notice that the option is missing
5. Try to create a new post and see that images cannot be made full width there as well (wrapped by Group block, Cover block, “Inner blocks use content width” inactive, changing Layout width in Global Styles doesn't work too)

### What you expected to happen

For images to be made full width on all block editor themes.

### What actually happened

Payton does not let you set full-width to images since post template has set the max-content width

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

CSS workaround: 
.post-template .entry-content {
      max-width: 100%;
}
.post-template .wp-site-blocks {
	padding: 0;
}

If another template is used it also works.

**Comment by christianguerrag** [comment]
I am unable to replicate this issue anymore, and in 5996434-zen they confirmed the bug is gone for them as well.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Thanks @christianguerrag  for that test and update from the user!
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @daria2303 if you can still repro this, feel free to reopen!
