### ISSUE TITLE
Paid Themes Filter Option

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#73986]
### What

I would like to have the option to show the **Paid** themes in the marketplace separately using the dedicated filter.

![image](https://user-images.githubusercontent.com/8070771/222399162-46988d5e-0c6a-4043-8664-5c5b596a4ede.png)

### Why

This will help us list the Premium and Paid themes separately. This way, the users who are not on a Business Plan can see the Templates that are available for them to use.

### How

![image](https://user-images.githubusercontent.com/8070771/222399708-815436ed-c906-44ce-a370-abbe4634cc75.png)

**Comment by zdenys** [comment]
Would have been helpful here 41180896-hc where instead I had to tell them to filter for Free themes or pick the ones that don't have a Paid label to avoid extra charges.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

📌 Message to Author
- Thanks for this report! This definitely would improve user experience when it comes to understanding what themes come with their WordPress.com plan, and which cost extra.

**Comment by druesome** [comment]
6061116-zen

**Comment by syhussaini** [comment]
It looks like this was implemented successfully.

![image](https://user-images.githubusercontent.com/8070771/230058781-80b3b870-425c-4fb5-8e7b-570840de882e.png)

**Comment by Copons** [comment]
Closing as not relevant anymore.
