### ISSUE TITLE
Marketplace: Update the Theme card in thank you page

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#73995]
![Image](https://user-images.githubusercontent.com/12430020/222444353-841900d0-2a5a-404b-b05b-26b8d1fe5eba.png)

Related designs: p9Jlb4-6ic-p2
Iteration 2 with Figma design link included here: p9Jlb4-6qr-p2

**Comment by WBerredo** [comment]
Related task: https://github.com/Automattic/wp-calypso/issues/73838

**Comment by epeicher** [comment]
This task will only cover the main card 
![CleanShot 2023-03-13 at 17 43 14@2x](https://user-images.githubusercontent.com/3519124/224768804-c61dfdcb-9da6-4aa4-9008-fb21ae6d6904.png)
The other changes will be covered in the following task:
- https://github.com/Automattic/wp-calypso/issues/74292
