### ISSUE TITLE
Bug: issue with hebrew character ת when adding a tag to a post

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#740]
User reports in ticket that while trying to add a tag to a post, typing the ת works like pressing Enter.

After checking with @bgbg, this actually due to the fact that the ת is in the same key than comma character:

![img_20151125_160627_402_720](https://cloud.githubusercontent.com/assets/1041600/11399438/2e16e202-9366-11e5-9990-3da6af450249.jpg)

Pinging @yoavf since he manages i18n and knows hebrew :)

Ticket: 2435478-t

**Comment by markpeak** [comment]
I can confirm this problem with Thai keyboard. Typing 'ม' character (which share the same key with comma in Latin keyboard) will create a new tag.

**Comment by nylen** [comment]
Also reported here:  https://en.forums.wordpress.com/topic/problem-with-adding-new-tags
