### ISSUE TITLE
Stats: Create the "Most popular post" card for the Insights page

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#74008]
# Development
Tackle the `all-time` most popular post data via updating or creating specific endpoints. The data query may come across a few DB tables.

- [x] Apply data to the [existing MostPopularPostCard component](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/all-time-highlights-section/most-popular-card.tsx).
( https://github.com/Automattic/wp-calypso/pull/74495 )
- [x] When the latest post is also the most popular, just display the most popular at full width
( https://github.com/Automattic/wp-calypso/pull/76775 )
- [x] Add mobile support using the dotPager component.
( https://github.com/Automattic/wp-calypso/pull/74495 )

--- Updated ---
- [x] [Add a placeholder/loading visual for the Most popular post card](https://github.com/Automattic/wp-calypso/issues/74008#issuecomment-1476639537) during data load instead of having the Latest post card expand to take up the entire width.

# Design
Create the most popular post that is not tied to any specific author.

### PC
<img width="644" alt="截圖 2023-03-03 上午12 50 23" src="https://user-images.githubusercontent.com/6869813/222497338-1029d10e-9ab7-4484-8f86-6badb3789a8b.png">

### Mobile
<img width="606" alt="截圖 2023-03-03 上午1 01 45" src="https://user-images.githubusercontent.com/6869813/222499651-80e7c17b-8196-4474-9bb4-dc6042212841.png">

**Comment by jsnmoon** [comment]
Note that it's currently not possible to obtain an all-time most popular post.

**Comment by dognose24** [comment]
The data period to determine the most popular post was proposed in the discussion: `pejTkB-nM-p2`.

**Comment by dognose24** [comment]
[Feedback from the PR comment](https://github.com/Automattic/wp-calypso/pull/74495#pullrequestreview-1346847427) of @jsnmoon:

> In the future, it'd be nice to see a placeholder/loading visual for the `Most popular post` card during data load instead of having the `Latest post` card expand to take up the entire width:

While Loading|While Loading (desired)|After Loading
-|-|-
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/4044428/226072147-78ed1466-fcd2-4e3e-8377-bf1d2dc4a99e.png">|<img width="1250" alt="image" src="https://user-images.githubusercontent.com/4044428/226072406-44654042-33a8-4b62-9b14-e1dc375b11d8.png">|<img width="1252" alt="image" src="https://user-images.githubusercontent.com/4044428/226072175-ea50c0f3-0e62-4cce-8e1a-fd2e884e802a.png">

**Comment by dognose24** [comment]
@jeffgolenski @keoshi What do you think about the placeholder card for loading status? I feel like there should be animations for the on-loading title or date. Or if there exist specific designs already?

![ezgif-1-e4c40b2547](https://user-images.githubusercontent.com/6869813/226804002-a622681a-29b5-412e-bf52-46eeb30e8afb.gif)

**Comment by jsnmoon** [comment]
> What do you think about the placeholder card for loading status? I feel like there should be animations for the on-loading title or date.

That looks good to me! Rendering a placeholder card is better than not showing anything to indicate the loading state, which is what we're currently doing on the insights page for the two post stats cards.

**Comment by dognose24** [comment]
> That looks good to me! Rendering a placeholder card is better than not showing anything to indicate the loading state, which is what we're currently doing on the insights page for the two post stats cards.

Generally, the advantages outweigh the disadvantages even though the most popular post card will disappear after loading for those _new sites_.

**Comment by keoshi** [comment]
That looks great to me!

**Comment by jsnmoon** [comment]
@dognose24, can we close this task?

**Comment by dognose24** [comment]
>- [ ] When the latest post is also the most popular, just display the most popular at full width

@jsnmoon I'll tackle the remaining feature for this task soon and close it when it's done. 🙂

**Comment by jsnmoon** [comment]
Sounds good!

**Comment by dognose24** [comment]
This task is completely done with the [PR](https://github.com/Automattic/wp-calypso/pull/76775) merged.
