### ISSUE TITLE
Built by upsell: the logo looks cut off on one side, blurry

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#74014]
The logo looks like it's being cut off on the right side:

![Image](https://user-images.githubusercontent.com/1689238/222543835-c1d2eec1-6eb3-4052-86b0-db10f5d24f69.png)

It's also blurry in desktop Safari:
![screenshot-2023-02-27-at-15 05 48](https://user-images.githubusercontent.com/1689238/222768169-b50ad2be-e3e3-42ca-8d90-97f13f2d8467.png)

Raised here: pebzTe-Fg-p2#comment-1362

Acceptance criteria:
- [ ] The whole logo is visible.
- [ ] It's not blurry in Safari.

**Comment by JanaMW27** [comment]
Here is the new logo with the new requirements,
<img width="150" alt="BBW" src="https://user-images.githubusercontent.com/71137829/222778215-f6a901d2-ece7-42e8-83ae-52a6ae0e864b.png">
