### ISSUE TITLE
How to make plugins available to legacy plan holders?

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wp-calypso#74012]
Legacy e-commerce plan holders do not have access to the plugins that are now bundled in the plan. We need to determine the easiest way to make these available to those users. 

Confirmation that the marketplace Ui doesn't automagically update and catch this. 

![Image](https://user-images.githubusercontent.com/89872780/221994103-306a064c-ee59-44dc-922b-5685b9baf140.png)

Eric B. thinks it's best to script something to install the plugins that should be available on these users' sites. I will then send an email with info about why it happened, what they are, how to activate them, etc. 

I do NOT think we need to address the case where a user already purchased it but now it's available for free.

**Comment by daledupreez** [comment]
I am thinking that we may want to improve this behaviour by allowing the plugin UI to install and activate the plugin when it has been bundled with the user's current plan. This should be pretty easy to check for if the user has access to bundled plugins.

That would work well for all plugins that we offer through the marketplace -- I am not sure if there are other bundled plugins that we don't yet offer via the WordPress.com marketplace.

**Comment by that-mike-bal** [comment]
This doesn't need to be a blocker for the performance launch but it needs to be done soon after to avoid dotcom legacy commerce plan holders from finding out about this and getting pissed because they are missing out on $300+ worth of free/useful extensions. 

cc @ebinnion  on this because I don't know if Serenity will have th bandwidth to pick it up before the launch/marketing start.

**Comment by ebinnion** [comment]
> I am thinking that we may want to improve this behaviour by allowing the plugin UI to install and activate the plugin when it has been bundled with the user's current plan. This should be pretty easy to check for if the user has access to bundled plugins.

Possibly. Though, I imagine that there is a matching `host-plans` subscription on the WooCommerce.com side that we need to keep in sync if/when a user cancels their sub. How does this work out if we then provision subs one-off?

**Comment by sixhours** [comment]
We were chatting about this during our sprint planning meeting, and rather than a one-time script, would it make sense to allow users to opt into having the plugin bundle installed by clicking a link in the email/button in the UI? This might help avoid user confusion ("Where did these plugins come from?") and avoid running a script on sites that don't want/need the extras.

**Comment by that-mike-bal** [comment]
@sixhours I think that is OK in theory but what would that experience look like? One click and it would install all of them or is it something where they are going to have to take multiple steps? 

Do we have a sense of what would happen if the user had purchased any of these extensions prior to us doing this?

**Comment by sixhours** [comment]
> I think that is OK in theory but what would that experience look like? One click and it would install all of them or is it something where they are going to have to take multiple steps?

Yep, that's the idea! We'd probably set up an API endpoint that installs the plugin set when the user clicks a button.

> Do we have a sense of what would happen if the user had purchased any of these extensions prior to us doing this?

Any currently installed/activated plugins on the user's site should be fine -- the script will skip them if it sees the plugin is already active. But if a user has installed/activated a plugin from this set at one point then deleted it, it will be re-added to their site, which might be undesirable behavior.

**Comment by that-mike-bal** [comment]
Perfect, let me know where we land on this. I have the copy drafted here and want to make sure it's updated to reflect the actual experience. 
https://docs.google.com/document/d/1DO5WXmizC_rHrR0gavUUSYNzFQkkoiy1Em6hXBMGUZ0/edit?usp=sharing

**Comment by that-mike-bal** [comment]
Sorry @ilyasfoo  I commented on the wrong issue here. Edited to avoid future confusion.

**Comment by ilyasfoo** [comment]
Hey, @that-mike-bal! I'm slightly confused, are you referring to the [plans grid](https://github.com/Automattic/wc-calypso-bridge/issues/1108) design? If so, I think following the design may not be possible since calypso's design would be vastly different.

**Comment by warrendholmes** [comment]
@daledupreez I think we can close this one now?

**Comment by daledupreez** [comment]
Yes, we can mark this issue as closed. We have rolled out plugins to existing users, and have communicated the changes/updates via email.
