### ISSUE TITLE
FSE > Navigation Block: Parent menu items lose typography settings/customization when adding submenus

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#74016]
### Quick summary

When you add a menu item you can change the font size and typography, but if you add a submenu to that item, the typography setting is gone, and the changes made before reset to the default of the Navigation block.

### Steps to reproduce

1. Activate an FSE theme.
2. Open the Site Editor and select the Navigation menu.
3. Select a Menu item and change the typography setting.
4. Add a submenu to that Menu item, and the typography goes back to the default value.
5. Open the settings of the Menu item to change the typography.

### What you expected to happen

Font applied to the parent menu item to not change when adding a submenu. Then, to be able to change the font family of the parent menu item when it has a submenu.

### What actually happened

The typography setting of the parent menu item is gone when adding a submenu. Also, if you change it before adding the submenu, the typography setting resets to the default values.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

**Workaround:** Change the font for the Navigation block. That would change fonts for all menu items, though.

How to reproduce the issue:

https://user-images.githubusercontent.com/50875131/222546138-d7d5e43e-9779-45fe-a3f7-1027b6c8d4e1.mp4

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Replicated**
- Replicable on Core? **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated in core - converting a Menu item to a Submenu loses any individual Typography settings on the link.
- The full Navigation block can still be stylized using Typography, but individual submenu items cannot have their own typography styles the way other menu items can.

**Self-Hosted Example**

https://user-images.githubusercontent.com/27249804/227380693-342c209c-17bf-4379-bb1d-cb11f10977c7.mov

📌 ACTIONS
- Assigned to Cylon
- Added to ‘HE Cross-repo Watchlist’ project board
- Submitted as Feature Request in Core: https://github.com/WordPress/gutenberg/issues/49319

**Comment by annezazu** [comment]
I can replicate this! How rough:


https://github.com/user-attachments/assets/adc39835-003f-48b8-a494-56459fde0d29

**Comment by annezazu** [comment]
Closing this out with the merging of https://github.com/WordPress/gutenberg/pull/65060
