### ISSUE TITLE
Classic Block: Top Toolbar scrolls off screen with long content

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#74031]
### What

When editing content in the Classic Block, if that content is longer than can be displayed in the viewport, it becomes cumbersome to format text because the classic editor tools stay pinned to the top of the block and scroll out of view.

Edit: addendum by @worldomonation - this is reproducible only with classic themes (non-block-based).

### Why

In most cases this is not an issue, but for sites with long-form content that was created in the classic editor originally, it can be very difficult to edit and format text due to the pinned toolbar.  It's not always feasible to convert a classic block to native Gutehberg, so a floating editor toolbar that stays in view will help site owners that are forced to edit content in the Classic block, so they are not forced to use the native classic editor (if such an option exists)

EX: https://wordpress.com/forums/topic/new-bugs-or-stupid-changes-on-the-site/

---

_2023-03-23 - cuemarie Since this has been updated as a bug, I'm adding some additional details:_

### Step-by-step reproduction instructions

1. Activate a Classic Theme such as Twenty Twenty One
2. Insert a Classic Block in a page or post
3. Add enough content that you must scroll down to see the lowest content

### WORKAROUNDS

- Switch to an FSE theme
- Switch to Blocks
- Enable[ top toolbar](https://wordpress.com/support/wordpress-editor/learn-the-interface/#more-options) in editor preferences (hattip @zdenys )

I was able to replicate outside of Dotcom, so this has also been reported here: https://github.com/WordPress/gutenberg/issues/50887

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by philnick206** [comment]
Another request for this here: 6263574-zd-woothemes

**Comment by christianguerrag** [comment]
Another request here 6263653-zen. 
I wanted to mention that in FSE themes there is an option to "Classic Edit" which opens a pop-up window to edit the content of the Classic block which helps with this problem, but on Classic themes that option is not there and the toolbar stays at the top.

**Comment by philnick206** [comment]
Another request 6281066-zd-woothemes

**Comment by philnick206** [comment]
Another 6283055-zd-woothemes

**Comment by christianguerrag** [comment]
Another here 6282017-zen

**Comment by christianguerrag** [comment]
Another user with the same problem and request 6290172-zen

**Comment by worldomonation** [comment]
I tried to reproduce this issue.

Environment:
- os: macOS Ventura
- browser: Firefox Nightly 115

Steps:
1. switch to a non-block-based theme  (Twenty Twenty)
2. create new post.
3. insert Classic block.
4. paste in long-form content.

Expected:
The toolbar will remain visible (like with block-based themes).

Actual:
The toolbar scrolls out of view.

Non-block-based theme
<img width="1100" alt="Screenshot 2023-05-17 at 4 40 19 PM" src="https://github.com/Automattic/wp-calypso/assets/6549265/4cb58241-4114-45e0-a84a-46424da9c87d">

Block-based theme
<img width="1100" alt="Screenshot 2023-05-17 at 4 35 14 PM" src="https://github.com/Automattic/wp-calypso/assets/6549265/edac8fe8-c10f-475b-ba53-109ffaf14e8e">

Video

https://github.com/Automattic/wp-calypso/assets/6549265/a9c29f78-4e1e-4e7c-9aff-aabe262bbd01

**Comment by worldomonation** [comment]
Addendum: @jorpdesigns was not able to reproduce this issue on self-hosted sites, which suggests that it's a bug in Calypso.

Video

https://github.com/Automattic/wp-calypso/assets/40006288/c05185ab-0e78-4229-970d-76e420704309

**Comment by jorpdesigns** [comment]
Reported in 6274321-zd-woothemes

**Comment by kuropixel** [comment]
Reported in 36014130-hc. Retired theme: The Journalist 1.3
6302493-zen Would like to be notified when this is resolved.

**Comment by worldomonation** [comment]
Switched category to Bug and assigned High priority, as the workarounds (switch theme or use Gutenberg blocks) are likely to be untenable suggestions.

**Comment by karenroldan** [comment]
This seems related to #76652

**Comment by zdenys** [comment]
6268459-zd-woothemes Told the customer to enable Top Toolbar as a workaround https://wordpress.com/support/wordpress-editor/learn-the-interface/#more-options

**Comment by zdenys** [comment]
6313269-zd-woothemes Told the customer to enable Top Toolbar as a workaround

**Comment by cuemarie** [comment]
@karenroldan I actually closed https://github.com/Automattic/wp-calypso/issues/76652 as that was about the Block Toolbar, which didn't move to specific sections within the Classic block (as expected). 

I'll see if there's anyone who can take a look at this today

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated in Simple & AT on theme **Twenty Twenty One** and outside of Dotcom using theme **Twenty Nineteen**

#### Screenshots/Recordings

**Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/c21034b2-d424-4a80-bf20-193662f22d1a

**Outside of Dotcom**

https://github.com/Automattic/wp-calypso/assets/27249804/f8885907-d8f6-4060-a098-ad54faa0ee01

📌 ACTIONS
- Scrubbed, awaiting assignment 
- Added to ‘HE Cross-repo Watchlist’ project board
- Reported to /gutenberg repo: https://github.com/WordPress/gutenberg/issues/50887

**Comment by cuemarie** [comment]
📌 ACTIONS
- Assigned to `Other`, awaiting on progress on the Core issue linked just above

**Comment by pauloeaquino** [comment]
6323050-zd

**Comment by mdtanjid0** [comment]
Another one: 

- [ ] 6348765-zen ( needs to be followed up )

**Comment by kavyagokul** [comment]
Also seen in 6363485-zen

**Comment by christianguerrag** [comment]
Reported here 6360613-zen

**Comment by christianguerrag** [comment]
Another here 6345278-zen

**Comment by jorpdesigns** [comment]
Reported in 6359002-zd-woothemes

**Comment by carolframen** [comment]
#6396027-zen

**Comment by DavidSaladu** [comment]
Found as well in [forums](https://wordpress.com/es/forums/topic/editar-en-clasico/?view=all).

**Comment by carolframen** [comment]
6538711-zen on Twenty Sixteen

**Comment by fstath** [comment]
Two reports in a forum thread:
https://wordpress.com/forums/topic/edit-post-toolbar-not-following/

**Comment by Gustavo-Hilario** [comment]
Another report here: 6639382-zen. The user also installed [Advanced Editor Tools](https://wordpress.org/plugins/tinymce-advanced/), but this is also an issue with that plugin. @cuemarie, should I open another bug report for that specific plugin, or once this gets fixed, the plugin should also be fixed? I'm not sure if the plugin offers the same Classic block we have on dotCom.

**Comment by cuemarie** [comment]
Hey @Gustavo-Hilario ! That's super interesting that the same symptom is impacting https://wordpress.org/plugins/tinymce-advanced/ as well!  I think it's a decent guess that the same underlying problem is at fault, but I can't say for sure.  `/wp-calypso` would not be the right place for a report for the plugin, though, so I'd say for now we can just note that here, and would you note on the core issue that the same symptom seems to be impacting that plugin? https://github.com/WordPress/gutenberg/issues/50887

**Comment by renata-franco** [comment]
I got a new one, but an old one. User said that we helped with this issue before and that we fixed it, but now they have the issue again. Ticket here: 6655764-zd.

**Comment by darnelldibbles** [comment]
Another report here: https://wordpress.com/forums/topic/edit-post-toolbar-not-following/?view=all#post-3981982

**Comment by jp-imagines** [comment]
> #6396027-zd-a8c

This customer came back with a repeat report, but I'm actually not able to reproduce this anymore. The toolbar sticks to the top of the editor as I scroll down now. (Simple site, Lodestar theme.)

@cuemarie I'm not sure if this needs re-triaging?

**Comment by cuemarie** [comment]
Thanks for the ping, @jp-imagines ! Likewise, I am no longer able to replicate this!

**Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/0b9d734f-5ebc-4291-a9dd-c7b57e26c5ca

**Simple**

https://github.com/Automattic/wp-calypso/assets/27249804/92d46bf5-890b-461c-93c4-00e4d3b8f393

📌 ACTIONS
- Closing as resolved
