### ISSUE TITLE
Prevent Mapkit from loading twice

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#74040]
Currently, when using the `[useMapkitSetup](https://github.com/Automattic/jetpack/blob/add/map-block-mapkit-editor/projects/plugins/jetpack/extensions/blocks/map/mapkit/hooks/index.js#L24)` hook, there's a check to see if `mapkit` already exists as a property on the [current window](https://github.com/Automattic/jetpack/blob/add/map-block-mapkit-editor/projects/plugins/jetpack/extensions/blocks/map/mapkit/hooks/index.js#L80).

If it does, it just returns the already present object.
If it doesn't, it adds a script tag to the document to load the library.

However, when you (for example) add two map blocks to the page, this will result in the script tag getting added twice, because the second call will get called before the mapkit object is available.

## Proposed solution
- Set a `mapkitScriptIsLoading` property on the current `window`.
- Use the [waitForObject](https://github.com/Automattic/jetpack/blob/add/map-block-mapkit-editor/projects/plugins/jetpack/extensions/blocks/map/mapkit/hooks/index.js#L43) to return the object when this is set.

### Before loading the library
```javascript
const { currentWindow } = getLoadContext( mapRef.current );
currentWindow.mapkitScriptIsLoading = true;
```

### When the library is loaded
```javascript
currentWindow.mapkitScriptIsLoading = false;
```

### When checking if we need to load it
```javascript
if ( currentWindow.mapkit ) {
	setMapkit( currentWindow.mapkit );
	setLoaded( true );
} else if ( currentWindow.mapkitScriptIsLoading) {
	waitForObject( currentWindow, 'mapkit' ).then(mapkitObj => {
		setMapkit( mapkitObj );
		fetchKey( mapkitObj ).then( () => {
			setLoaded( true );
		} );
	});
} else {
	loadLibrary().then( mapkitObj => {
		setMapkit( mapkitObj );

		fetchKey( mapkitObj ).then( () => {
			setLoaded( true );
		} );
	} );
}
```

## Notes
- Poluting the global namespace is not ideal, but added this to a higher data store seems a lot of overhad
- We might implement something similar for the `fetchKey` function, because now it will get called twice

**Comment by JuanLucha** [comment]
Even when polluting the global namespace is not ideal (I agree completely), this solution still feels good.
