### ISSUE TITLE
Domain Upsell: Add sense of urgency copy to the flow

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#74056]
> For the flow: At the checkout or somewhere, it might be good to have an urgency action such as Congrats on choosing this domain, snatch it before somebody else does or something similar.

Reference: pebzTe-OR-p2#comment-1349

This issue probably needs a little exploration. Consider where we might be able to do this effectively and get buy in.

**Comment by allilevine** [comment]
Closing as won't fix.
