### ISSUE TITLE
Domain Upsell: Change border on /me page & possibly /home page

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#74055]
> What if we mark the upsell in a different color with borderline or something? This section is more of a settings page so it might set the tone that the upsell area is different while also giving attention to it.

Reference: pebzTe-OR-p2#comment-1349

This issue probably needs a little exploration. Try something that looks nice and get some buy in.

**Comment by allilevine** [comment]
Closing as won't fix.
