### ISSUE TITLE
Stats: unresponsive script in Firefox

### ISSUE THREAD

**Issue by MicBosi** [Automattic/wp-calypso#7406]
#### Steps to reproduce

View stats for site: aboxofoldletters.com (https://wordpress.com/stats/insights/aboxofoldletters.com)
OS version: unknown
Firefox version: unknown (presumably latest)
#### Screenshot / Video

User gets a "Warning: Unresponsive script" when trying to access the stats page with Firefox on a Mac:

![edited-e605e23e-5fe7-11e6-98cc-155937da8199](https://cloud.githubusercontent.com/assets/66797/18213654/27b19b70-70fe-11e6-9a14-2c6fd9d036f9.png)

2766380-t

**Comment by hambai** [comment]
The user also reported his system os and browser versions:

The OS is 10.11.06
Firefox is 48.0

**Comment by chaitanyamsv** [comment]
I ran into this problem myself some weeks ago. Then it stopped. Now it returned to my Firefox 48.0.1 (latest). When this happens, the Mac Book Pro CPU spins up.

Here is the screencast of the problem: https://cloudup.com/cfHjdqPV_Je
Here is where the error seems to be coming from: [JS Error.txt](https://github.com/Automattic/wp-calypso/files/466290/JS.Error.txt)

I also had a user in chat (#468792-chat) last week reporting similar, but not the same error. 
Their Firefox says: `A website is slowing down your browser.` and Chrome says: `Oh no! Error showing your website.`.
When this happens, both their browsers became unresponsive, and their Mac Book Pro CPU spins up and becomes noisy.

**Comment by hoverduck** [comment]
#bug-scrub

I'm unable to reproduce the problem now, but I think I also saw a similar issue a couple weeks ago.  I resolved it by completely clearing my cache (which also kept me from capturing any useful diagnostics).  Although in my case it was limited to Chrome, and if it was purely a cache problem it wouldn't likely happen in multiple browsers at once like in earlier reports on this thread.
