### ISSUE TITLE
`/subscriptions`: Make the page accessible to external users

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74070]
## Acceptance Criteria:
- the `/subscriptions` should be accessible for non-wpcom (external) users 
- the page is still to remain hidden behind a feature flag

## Dev Notes
Add `enableLoggedOut: true` property to the subscriptions section definition in [sections.js](https://github.com/Automattic/wp-calypso/blob/a89bbd6c83f4317d383d38e62a8ac503dc5f159e/client/sections.js#L566)

**Comment by yansern** [comment]
> Add enableLoggedOut: true property to the subscriptions section definition in [sections.js](https://github.com/Automattic/wp-calypso/blob/a89bbd6c83f4317d383d38e62a8ac503dc5f159e/client/sections.js#L566)

Ah, I just saw that you've mentioned that in the Dev Notes.

Anyhow, I also added it as a late comment on https://github.com/Automattic/wp-calypso/pull/73818/files#r1126281531
