### ISSUE TITLE
`/subscriptions`: Add wpcom header to the  page

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74071]
## Design
inDLaEQV8jJ21O4WXawIsJ-fi-712%3A29015

### Desktop Version
![Screen Shot 2023-03-04 at 09 16 09](https://user-images.githubusercontent.com/2019970/222885155-c1744ed3-0acf-46a6-979f-db8894a4625b.png)

### Mobile Version
![Screen Shot 2023-03-04 at 09 16 16](https://user-images.githubusercontent.com/2019970/222885156-0fab1334-d159-4bc8-aa7a-b7485d97d11f.png)

## Acceptance Criteria
- The header should contain:
  1. WPCOM logo
  2. "Log in" button
  3. "Get Started" button 
- The mobile version of the header should instead display the hamburger icon as per the design 

## Dev Notes
I have not seen an exact implementation of the "master" header bar in Calypso. Similar one but with more menus exists for:
https://wordpress.com/plugins/ and https://wordpress.com/themes/

To add the "masterbar" from the above examples we would need to add `'subscriptions'` to [the array defined within the following condition in logged.out.jsx at line 108](https://github.com/Automattic/wp-calypso/blob/2909f576b4e5836d5eed35232b723a3333b6bd34/client/layout/logged-out.jsx#L108):
```
} else if ( [ 'plugins', 'themes', 'theme' ].includes( sectionName ) ) {
```

**Comment by yansern** [comment]
On Calypso, we can use the `UniversalHeader` component from `wpcom-template-parts`. If customization is needed on that component, we can modify the component that since it's a package we own.

**Comment by yansern** [comment]
Just linking the other issue on header for Reskinned Portal, as this one will need to be modified in either the H4 theme, or CSS hiding in Landpack (look for masterbar stylesheets in Landpack) or in our own block as well if easier.

https://github.com/Automattic/wp-calypso/issues/74108
