### ISSUE TITLE
`/subscriptions`: Create “Sites”, “Comments” & “Settings” tabs

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74075]
## Design
inDLaEQV8jJ21O4WXawIsJ-fi-712%3A29026

### Desktop Design
![Screen Shot 2023-03-04 at 17 43 53](https://user-images.githubusercontent.com/2019970/222918304-1cbb9fbc-9d6d-4928-98e3-fb5e4214a1bd.png)

### Mobile Design
![Screen Shot 2023-03-04 at 17 44 39](https://user-images.githubusercontent.com/2019970/222918299-c60bc8af-03f3-468c-a8fe-ed164d993e2a.png)

## Acceptance Criteria
- display the number of subscribed-to sites beside **Sites** tab title
- display the number of subscribed-to-comments sites beside **Comments** tab title (@phcp can you verify please if that is what the number is meant to represent 🙈)
- the current open tab should be the **Settings** tab
- clicking on **Sites** tab should open (in the same browser tab) `${INTERIM_PORTAL_URL_FOR_THE_EMAIL}?option=sites`
- clicking on **Comments** tab should open (in the same browser tab) `${INTERIM_PORTAL_URL_FOR_THE_EMAIL}?option=comments`

## Related Conversations
https://github.com/Automattic/wp-calypso/issues/74368#issuecomment-1466626570
https://github.com/Automattic/wp-calypso/issues/74368#issuecomment-1466848809

## Dev Notes
- We can use the [`calypso/components/section-nav`](https://wpcalypso.wordpress.com/devdocs/design/section-nav)
  - However it will require us to create some type definitions for the components
    - See [my draft PR](https://github.com/Automattic/wp-calypso/pull/74077) for how this is done
    - Example: see how `packages/help-center` is defining the type for `SearchCard` calypso component and others in its [`src/components/index.d.ts`](https://github.com/Automattic/wp-calypso/blob/b4ba58ae97d6c09dbdb8da58fff1b28e22859565/packages/help-center/src/components/index.d.ts).
- The tabs are already functional in the interim portal. It may be a good idea to use the implementation as a reference when confused.

**Comment by yansern** [comment]
Just wanna add that the Pending tab exists (but only for External Users) and it appears when external users subscribe to a site but haven't confirmed the subscription.
