### ISSUE TITLE
`/subscriptions`: Ensure the user is authorized to access the portal for the given email address

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74076]
Acceptance criteria:
 - Create an API endpoint that returns the details of the `subkey` cookie.
 - Create a simple lib on Calypso that allows retrieval of the details of the external user via this endpoint. (Maybe client-side can already parse the cookie but highly unlikely.)

**Comment by mashikag** [comment]
Hey @yansern 👋 
Can you write a little bit more on the description of this task to help explain how the authorization is meant to happen? 
What do we check for in the cookie? Or what request should we make to the backend and what response should we expect back? 🙇‍♂️

**Comment by yansern** [comment]
Looks like its semi-related to this one. https://github.com/Automattic/wp-calypso/issues/74070
One more step is to get Calypso to recognize users authenticated with `subkey` cookie which is what this issue is about.

**Comment by yansern** [comment]
>Hey @yansern 👋
Can you write a little bit more on the description of this task to help explain how the authorization is meant to happen?
What do we check for in the cookie? Or what request should we make to the backend and what response should we expect back? 🙇‍♂️

Added something simple. Will expand as we go.

**Comment by yansern** [comment]
There is no more separate endpoint for doing authorization.

On backend, we receive via the request header.
On frontend, we retrieve by cookie (at least for the moment). It needs to have a more secure way of doing it in the future.
