### ISSUE TITLE
New AT sites can't access Site Editor - too many redirects

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/wp-calypso#74072]
### Quick summary

When creating a brand new site on the Business plan, you can't access Site Editor. Instead, you will see an error saying you have been redirected too many times or that the page is not redirecting properly. 

Follow steps exactly under **Steps to reproduce** to duplicate issue. 

Issue seems specific to AT sites that are new and have never used Site Editor before. 

### Steps to reproduce

1. Create a brand new WordPress.com site and go through purchase flow (select domain, Business plan, and design Spearhead Blocks in purchase flow). Do not edit site via Site Editor yet. 
2. Once site is created with Business plan and with Site Editing theme (Spearhead Blocks), AT site - head to *My Site → Settings → Hosting Configuration → Activate* 
5. Access Site Editor from *My Site → Appearance → Editor* 

### What you expected to happen

I expected to be able to access Site Editor to edit my site.

### What actually happened

See error instead: The page isn’t redirecting properly 

<img width="1358" alt="Screen Shot 2023-03-04 at 7 39 14 AM" src="https://user-images.githubusercontent.com/77413972/222902275-04a7a7f4-cdf9-467d-a260-6f43b0d66400.png">

**As a workaround for now** you can deactivate Gutenberg and error goes away. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, not ideal. Requires you to deactivate Gutenberg

**Comment by carinapilar** [comment]
Got this while on chat:
- 41243590-hc
- 41246830-hc

**Comment by wpshellbelle** [comment]
40854016-hc

**Comment by ha-un** [comment]
37271931-hc

**Comment by pauljacobson** [comment]
Just encountered this issue in 6015582-zen when I tried to access the Site Editor for the user.

**Comment by pauljacobson** [comment]
I have just reproduced this issue on my test site: https://theatomizertestsite.wpcomstaging.com/

https://user-images.githubusercontent.com/2912202/222951619-fb31c0aa-f2c3-486a-afd6-0b12ab5ad1fe.mp4

I noticed that when I clicked on the link in my Console to see more information, the browser highlighted this:

```
console.warn('crbug/1173575, non-JS module files deprecated.');
```

**Comment by susanjanec** [comment]
Encountered in hc-28936175

Kept getting "This page isn’t working
[domainname] redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS"

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Steps taken to replicate: 

1. Switch Sites -> `Add new site`
2. Chose free domain
3. Business plan - purchased this plan
4. Entered basic site details and chose **Spearhead blocks** as design
5. From the Launchpad screen ("Your website is ready!"), chose **Skip to dashboard**
6. Settings -> Hosting Configuration -> **Activate**
7. Once those activated, I opened **Appearance -> Editor**

**EXAMPLE**

https://user-images.githubusercontent.com/27249804/222980928-f600327b-0800-48ab-ad02-97dee0192229.mp4

---

**RESOLUTION**

I opened up my Installed Plugins page to deactivate Gutenberg, and was prompted to resolve a Jetpack IDC between my .wordpress.com and .wpcomstaging.com addresses. Once I did that, without any other changes, I opened the Site Editor once more, **and it loaded properly** at `https://testsite20230305.wpcomstaging.com/wp-admin/site-editor.php?postId=none&canvas=view`

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 Message to Author
- big kudos to @wpshellbelle for the clear steps to follow on this report! 
- Thanks @hideandgeek404 and @wpshellbelle for helping escalate this as well here: p1677851321234409-slack-C02FMH4G8

**Comment by adelineyaw** [comment]
41027828-hc
41362506-hc

As a workaround, I was able to access the Site Editor via **Appearance > Customize** then click on the 'Use Site Editor' button. Once that's done, I was then able to access the Site Editor via **Appearance > Editor**

<img width="288" alt="Markup 2023-03-08 at 11 38 14" src="https://user-images.githubusercontent.com/7424885/223589202-6dc5aa51-921f-4bf4-b232-b8cb02412978.png">

**Comment by dragstor** [comment]
40772381-hc

**Comment by dragstor** [comment]
41306056-hc

**Comment by IoanaAMuresan** [comment]
41294057-hc

**Comment by dragstor** [comment]
ℹ️ Possible workaround:
1. Open the site's `wp-admin` (example.com/wp-admin)
2. Access the Editor from there (**Appearance → Editor**)

**Comment by liviopv** [comment]
Another:

- [ ] 41287266-hc

Asking them to visit a /wp-admin screen to set login cookies first worked

**Comment by zdenys** [comment]
6012566-zd-woothemes

**Comment by dragstor** [comment]
41313621-hc

**Comment by rickmgithub** [comment]
6021761-zen

**Comment by pauljacobson** [comment]
6020538-zen

I also can't access Site Editor for this customer's site on my side, either.

**Comment by Nic-Sevic** [comment]
two more instances here:

6023745-zd-woothemes
6019595-zd-woothemes

**Comment by mdtanjid0** [comment]
- [ ] 6019595-zen ( needs to follow up ).

**Comment by filipanoscampos** [comment]
Had this issue today: 41373057-hc

**Comment by wpshellbelle** [comment]
38800915-hc

**Comment by mattwiebe** [comment]
This is as a result of https://github.com/WordPress/gutenberg/pull/48283

I'm working on a hotfix for Atomic

**Comment by happychait** [comment]
41389494-hc
