### ISSUE TITLE
 Payments and Premium Content Block: Allow multiple subscriptions option (monthly, yearly, and one-time payment)

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#74088]
### What

To allow visitors multiple subscriptions options they can choose from (monthly, yearly, and one-time payment)

The current workaround involves creating two separate Premium Contents blocks, one for yearly and another for monthly (resulting in duplicate effort and contents)

### Why

Kind of similar to https://wordpress.com/pricing/ , where customers will be able to choose if they want to subscribe monthly or yearly subscriptions

**Comment by edwinho89** [comment]
41297082-hc

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

📌 Message to Author
- This enhancement would definitely reduce duplicate efforts!  Adding multiple premium content blocks also would add additional content that some subscribers couldn't see - making it seem like the "yearly" subscriber was still missing out on content that only "weekly" subscribers can see. Not a great experience.

**Comment by katiebethbrown** [comment]
@cuemarie - I think this is a duplicate of 

- #41606

**Comment by cuemarie** [comment]
Ooh, great find, thanks @katiebethbrown !

📌 ACTIONS
- Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/41606
