### ISSUE TITLE
Plans 2023: [Bug] Old plans grid briefly shown when navigating to /plans from another route

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#74098]
## What

The old plans grid is briefly shown when navigating to `Upgrades -> Plans` from another route e.g. `home`. This looks related to https://github.com/Automattic/wp-calypso/pull/73481 

https://user-images.githubusercontent.com/1705499/223075550-acd0d024-2941-4391-acf6-23ac5fe0123f.mov

**Comment by chriskmnds** [comment]
cc @southp I believe this begs for confirmation and prioritization. the more visual changes that go into the new plans page the more profound the flicker will be (e.g. [notices](https://github.com/Automattic/martech/issues/1528) going from black-green to light-gray will be especially noticeable)

**Comment by southp** [comment]
Great catch 😱 
In my case, it doesn't apper on the first click on the Plans tab, but on all the navigating that follows. Please go for it. It might have some more serious implication, e.g. the old plan grid might be always loaded behind the scene.

**Comment by chriskmnds** [comment]
> In my case, it doesn't apper on the first click on the Plans tab, but on all the navigating that follows. Please go for it. It might have some more serious implication, e.g. the old plan grid might be always loaded behind the scene.

It doesn't appear cause there's no transition between routes. My guess is this is related to how we switch only on specified routes in #73481 (my lizard brain [flagged this](https://github.com/Automattic/wp-calypso/pull/73481#discussion_r1111321510) at some point as a concern, but I couldn't narrow in on it). I can poke around for the cause, but it might be the case we need to rethink the approach instead (deal with the issues that lead to #73481 instead of ambiguous workarounds, assuming that's the cause) 🤔

**Comment by southp** [comment]
> it might be the case we need to rethink the approach instead 

Sure. I'm happy to defer the most prgamatic solution to your best judgement :)
