### ISSUE TITLE
Landing Page: Support locale param in `/email-subscriptions` landing page.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#74118]
The `/email-subscriptions` page needs to support the `locale` URL param.

When the `locale` URL param exists, ensure the email login form's action URL contains the `locale` param.

As for the`lang` URL param, we will not support it, as the introduction of the param was to fix a mistake where the `lang` param was mistakenly used in older versions of JP. See comment on `subscribe_blog_language()`.

~Need to support both prepended and appended locale in the URL, e.g.~
 - ~prepended = `/en/email-subscriptions`. (URL Fragment Locale)~
 - ~appended = `/email-subscriptions/?locale=nl`. (URL Param Locale)~
 - ~The email login form needs to have the locale param appended as well.~

As for `/locale` URL fragment support, this is now described in another issue. https://github.com/Automattic/wp-calypso/issues/74159

This is important for the new emails to be sent out in the right language if we're going to launch emails for all users by end of the week.

**Comment by yansern** [comment]
Take note: `lang` was a mistake (see comment on `subscribe_blog_language()`), the official param is `locale`, so ignore the `lang` param.

**Comment by ivan-ottinger** [comment]
> Take note: lang was a mistake (see comment on subscribe_blog_language()), the official param is locale, so ignore the lang param.

Thank you, Yan! I think we could pass all the query strings to the action URL. At least I don't see any issues with that at the moment. 🤔 

→ I started working on the PR: https://github.com/Automattic/landpack/pull/1255 (not ready for review yet).

---

> The /email-subscriptions page need to be locale/lang GET param aware.
> If it exists, change the locale on the page.
> Need to support both prepended and appended locale in the URL, e.g. (Can be a separate issue / patch / lower priority)
> - prepended = /en/email-subscriptions.
> - appended = /email-subscriptions/?locale=nl.

Here you meant to redirect the user to that specific e.g. `/de/` URL?

**Comment by yansern** [comment]
> Here you meant to redirect the user to that specific e.g. /de/ URL?

If it matches the mag16 languages. The trouble is the url fragment locales covers only mag16, while the existing portal covers all locales, so some compatibility work needs to take place.

We'll create another issue for this to describe the requirements. (UPDATE: Here it is https://github.com/Automattic/wp-calypso/issues/74159)

**Comment by ivan-ottinger** [comment]
https://github.com/Automattic/landpack/pull/1255 is now ready for review. @JuanLucha 🙂
