### ISSUE TITLE
Site Editor: Browse All Templates results in loading spinners

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#74127]
### Quick summary

When clicking "Browse all Templates" from within the Site Editor's template selector, it results in a perpetual loading state that doesn't resolve.

https://user-images.githubusercontent.com/1398304/223197472-2ee5f794-44c8-4988-b9dc-01213e4a1227.mov

### Steps to reproduce

1. Start at wordpress.com to load Calypso
2. Select a site with a block theme.
3. Select Appearance > Editor.
4. Select a template to edit.
5. Click on the template name at the top of the edior.
6. Click Browse All Templates

### What you expected to happen

To have a list of templates to choose from.

### What actually happened

Unending loading indicator

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by ntsekouras** [comment]
Could have this been resolved by this GB PR: https://github.com/WordPress/gutenberg/pull/48301?

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple –Could Not Replicate
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Seems this is indeed resolved

📌 ACTIONS
- Closed as no longer relevant (issue resolved)
