### ISSUE TITLE
Remove Sensei code and references from Launchpad

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#74141]
### Details

When the Sensei flow was first added, there was a sensei Launchpad screen. They've since removed that. I've confirm with the team who worked on this, and we can go ahead and remove all sensei references from launchpad now.

**Comment by Addison-Stavlo** [comment]
I see an issue was mentioned and merged. Is there still more to fllow up on for this issue @edanzer ?

**Comment by edanzer** [comment]
This was completed with https://github.com/Automattic/wp-calypso/pull/74168
