### ISSUE TITLE
Landing Page: Make email landing page landpack locale compatible.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#74159]
**Glossary:**
- url fragment locale = `/de`
- url param locale = `&locale=de_CH`
- mag16 languages = `['es','pt-br','de','fr','he','ja','it','nl','ru','tr','id','zh-cn','ko','ar','en','sv']`
- get lang from locale = `mb_strtolower( preg_replace( '/_.*/i', '', LOCALE_VALUE_HERE ) )` (taken from `landpack_get_locale()`). 

**Requirements:**
1. When the landing page is accessed with **locale url param** matching one of the mag16 languages, e.g. `/email-subscriptions?locale=de_CH`, redirect user to `/de/email-subscriptions?locale=de_CH`.
   - The `/de` url fragment ensures header & footer is displayed in DE language.
   - The `?locale=de_CH` URL param when carried over to the email login form's action URL ensures the email is sent out with the specified locale. (handled by **https://github.com/Automattic/wp-calypso/issues/74118**)

2. When the landing page is accessed with **locale url fragment** without the **locale url param**, e.g. `/nl/email-subscriptions`, ensure the email login form action URL contains the locale param, e.g. `?V2&locale=nl`.
   - You can use `landpack_get_locale()` and filter it through the mag16 languages whitelist (just to be safe because internally it uses `get_locale()` which could still cover non mag16 languages)

3. When the landing page is accessed with **locale url param** not matching any of the mag16 languages, e.g. `/email-subscriptions?locale=ms`, just ensure the locale is carried over to the email login form's action URL. (handled by **https://github.com/Automattic/wp-calypso/issues/74118**)

**Comment by ivan-ottinger** [comment]
Thank you for the detailed description, Yan! It helps a lot!

**Comment by ivan-ottinger** [comment]
> get lang from locale = mb_strtolower( preg_replace( '/_.*/i', '', LOCALE_VALUE_HERE ) ) (taken from landpack_get_locale()).

Turns out that `mb_strtolower( preg_replace( '/_.*/i', '', LOCALE_VALUE_HERE ) )` cuts away the `_CH` portion from `de_CH` which is good in this specific case. But for instance, when we look at `pt_BR` locale, the corresponding URL fragment in Landpack is `pt-br`.

This means that we will need to treat those two specific cases (`pt-br` and 'zh-cn') separately when redirecting.

**Comment by yansern** [comment]
For the locale URL fragment, they specifically require `pt-br` for the url fragment, so the regex `/_.*/i` is still OK for no. 1, but wait, if the locale `pt_br` was passed in from url param, then it needs to be replaced with `pt-br` for the url fragment, so yes, replace `_` with `-` from the url param and see if it matches the mag16 list for the url fragment.

For the locale URL param, I do not know if `pt-br` and `pt_br` can be used interchangeably. If it can be used interchangeably, then nothing more to be done for no. 2, else the dash `-` from the url fragment needs to be replaced with `_` when passing it back to the url param.

**Comment by ivan-ottinger** [comment]
Thanks for your point of view, Yan.

> For the locale URL param, I do not know if pt-br and pt_br can be used interchangeably. If it can be used interchangeably, then nothing more to be done for no. 2,

`?locale=pt-BR` isn't handled by `subscribe.wordpress.com` unfortunately.

I am currently focusing on case 1. and then will focus on 2. 🙂

**Comment by ivan-ottinger** [comment]
> `?locale=pt-BR` isn't handled by `subscribe.wordpress.com` unfortunately.

Luckily, I was wrong here. 😄 Probably had a typo in the URL when I was testing it earlier.

Anyways, the draft PR (not ready for review yet) that handles the case 1 is over here: https://github.com/Automattic/landpack/pull/1262

It is working as expected in all of my test when trying on WordPress.com, but when testing on local Landpack, I get one warning. Will investigate why so tomorrow. 

I will also create another PR that will handle the case 2.

**Comment by ivan-ottinger** [comment]
The PR that handles the **Requirement 2** is ready for review: https://github.com/Automattic/landpack/pull/1265.

**Comment by ivan-ottinger** [comment]
https://github.com/Automattic/landpack/pull/1262, that handles the Requirement 1, is now ready for review.

**Comment by ivan-ottinger** [comment]
All requirements are met now. → Closing this task.
