### ISSUE TITLE
Fullpost: Sidebar: Spacing issues on the comment/like links

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7416]
• Comment icon should scoot 1px down, so that the bottom of the bubble is on the same baseline as the text.

Current:
![screen shot 2016-08-11 at 2 06 06 pm](https://cloud.githubusercontent.com/assets/24388/17609516/c79c8de0-5fea-11e6-90cd-2a2af1b8a895.png)

• Comment and Like links should have about 30px of whitespace in between them

Should be:
![comm-like-space](https://cloud.githubusercontent.com/assets/24388/17609522/d7ae7cac-5fea-11e6-8cfa-c86eb4e665e7.jpg)

**Comment by blowery** [comment]
Fixed in #7202

**Comment by fraying** [comment]
LGTM
