### ISSUE TITLE
Custom font not appearing in Editor

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/wp-calypso#74181]
### Quick summary

When using a custom font (eg. Jost) on the Meraki Theme (when site is Atomic), the font defaults to Times New Roman within the page/post Editor and on the front-end (or when previewed), the custom font can be seen.

### Steps to reproduce

1. Select a custom font within the Styles/Typography panel
2. Edit a post/page
3. The font appears to be Times New Roman
4. Preview the post/page and the custom font you've selected will be visible.

### What you expected to happen

The post/page Editor should show the custom font selected as per the Styles/Typography panel

### What actually happened

The post/page Editor fonts are Times New Roman and not the selected custom font.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I've tested this on my end (on a simple site) and did not come across this issue but once a site has the ability to install plugins/themes, I did experience this issue.

41227350-hc
6024521-zen (Follow up)

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Wasn't able to replicate - the page/post editor is showing the font I've set up in Site Editor > Styles > Typography.

Reviewing the ticket, it looks like this was likely resolved by getting their **WordPress.com Editing Toolkit** plugin updated.

📌 ACTIONS
- Closed as no longer relevant (user issue resolved by updating their plugins)
- No follow up on ticket needed
