### ISSUE TITLE
Fullpost: Text Colors

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7418]
A note on text colors. Could we try these? (I'm limiting myself to the official colors.)

Sidebar (author name, site name, follower count, and comment/like counts):
Normal: Gray Lighten 10 (#a8bece)
Link: Medium Blue (#00aadc)
Hover: Light Blue (#78dcfa)

Date and tags:
Normal: Gray Lighten 10 (#a8bece)
Link: Gray (#87a6bc)
Hover: Light Blue (#78dcfa)

Even though the link colors are different in the two sections (to denote importance), I'd like to try to make the normal text and hover colors consistent. Thoughts?

**Comment by bluefuton** [comment]
Sounds good to me.

How about the hover state for the follow button for a site you're already following? Looks a touch odd at the moment:

<img width="102" alt="screen shot 2016-08-16 at 15 17 50" src="https://cloud.githubusercontent.com/assets/17325/17700105/af49e89a-63c4-11e6-9ee3-d633425bea3e.png">

**Comment by fraying** [comment]
Oh yeah. That should stay green (no hover). Thanks!

**Comment by bluefuton** [comment]
Fixed in #7489.
