### ISSUE TITLE
Site Assembler: Let us choose a header/footer easily with keyboard

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#74188]
### What

We want to improve keyboard accessibility to let us choose a header/footer easily.
In this issue, it needs to focus on the `Done` button if a user presses the tab after selecting a header/footer, 

### Why

If we try to select a header/footer using only the keyboard, we have to press the tab many times to reach the “Done” button, as shown below.

https://user-images.githubusercontent.com/5287479/223653006-d6ab4546-fde5-471e-8bed-d93a006d3a60.mov

### How

We may do this by changing the DOM structure or using `tabindex`.

### Related

- https://github.com/Automattic/wp-calypso/pull/74157#issuecomment-1459578432
- https://github.com/Automattic/wp-calypso/issues/74189

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/75948
