### ISSUE TITLE
Reader: add a way to browse lists

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#742]
Raised by @blowery 

Implement the browse lists screen, which will let you see popular lists and follow them.

![screen shot 2015-01-08 at 3 06 09 pm](https://cloud.githubusercontent.com/assets/14350/5669707/fe7aea7c-9747-11e4-84df-b3d6da3ec5d9.png)

This will require new bits in the REST api to enable list manipulation and the browsing of lists.

**Comment by alisterscott** [comment]
Lists are currently on hold and not available for non-list using customers, so closing this one out.
