### ISSUE TITLE
Woo Express Medium: Update upsell nudges

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#74201]
We need to check various upsell nudges to make their target plan depending on the user’s current plan (and the feature flag for eCommerce vs WooExpress).

This includes nudges from the Plans page, My Plan, and the theme showcase. We'll want to double-check that there aren't other places with nudges as well.

**Comment by markbiek** [comment]
@daledupreez Here's my thinking about what the nudges should look like:

* Ecommerce Trial: Nudge to upgrade to the Medium Monthly plan (or is yearly better)?
* Medium Monthly: Nudge to upgrade to Medium Yearly.
* Medium Yearly: Nudge to upgrade to Ecommerce Yearly.

Please let me know if there are changes I need to make to the above.

**Comment by daledupreez** [comment]
@markbiek, I think there is some nuance to the work here that we shouldn't miss.

* For any existing nudges that point to the plans page, we should make no changes
* For any existing nudges that directly add the eCommerce plan to the cart, we should consider whether we should redirect to the plans page (preferable), or add the medium monthly product instead (as users can pick longer terms within checkout)

I don't know that there are any nudges for the eCommerce plan that we'd need to pull across for the medium plan.

**Comment by markbiek** [comment]
@daledupreez Thank you!

**Comment by markbiek** [comment]
I _think_ the only places that need adjusting are

- `/plans/:siteSlug` 
	- Top of the features list (Monthly & Annual)
	- Upgrade button at the bottom of the page
- `/plans/my-plan/:siteSlug`
 	- Top of the features list
 	- Upgrade button at the bottom of the page

Both of these currently directly add the eCommerce plan to the cart.

_However_, it may already be taken care of in #73898. I need to verify and report back.

**Comment by markbiek** [comment]
I think I was confused about what #73898 was doing. Those upgrade buttons still add the eCommerce plan to the cart.

@daledupreez Unless you have objections, I'm planning to change those to add the Medium monthly plan. That makes the most sense to me since we're already on the plans page :)

**Comment by markbiek** [comment]
I think @nelsonec87 has already covered this as part of his plans page work.
