### ISSUE TITLE
Plugin name is alternating on the thank you page

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#74200]
After purchasing the [ManageWP - Worker](https://wordpress.com/plugins/worker) plugin, on the thank you page, the plugins query is re-sent every couple of seconds, and the plugin name is alternating between two versions:
![Image](https://user-images.githubusercontent.com/11555574/223704503-99248036-08d9-4131-80a6-0aabeea2491b.gif)

Here's a video of the issue with the requests being sent: https://user-images.githubusercontent.com/11555574/223703252-55dc208b-8ef4-42bc-bbb1-e15b17458630.mp4

**Comment by WBerredo** [comment]
I figured this issue is only happening now when not WP.com plugin is being used, as the #74125 only searches on WP.com.
The query keeps being sent because no results for this slug are being retrieved after searching on plugins sources and WP.com themes.

**Comment by WBerredo** [comment]
The PR https://github.com/Automattic/wp-calypso/pull/74125 was updated to also search on WP.org now and this problem shouldn't be happening anymore. 

The multiple retries are being done on https://github.com/Automattic/wp-calypso/blob/a37ea8db9a323bc9627a8149b40314ec5b20a848/client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx#L131-L136

There is room for improvement if we retry the search only of the not available dotOrg plugins and not all of them.

**Comment by WBerredo** [comment]
The investigation and fix for this is done, further improvements will be fixed here: [#74228](https://github.com/Automattic/wp-calypso/issues/74228)

**Comment by gcsecsey** [comment]
Thanks @WBerredo, for quickly identifying and resolving the issue! 🙌
