### ISSUE TITLE
Fullpost: Avatars

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7420]
Banish the RSS icon!

![screen shot 2016-08-11 at 2 50 22 pm](https://cloud.githubusercontent.com/assets/24388/17609641/ccf66a80-5feb-11e6-93a3-171bc84c8867.png)

Banish the default person avatar!

![screen shot 2016-08-11 at 3 36 08 pm](https://cloud.githubusercontent.com/assets/24388/17609644/d29f9a38-5feb-11e6-8b53-65c6db21188a.png)
https://calypso.live/read/feeds/23091427/posts/1117060142

Logic for the main avatar: Use the first one we find. All become circles.

- gravatar
- blavatar
- rss feed site image
- Apple touch icon from main site
- anything else we can think of
- a photo of one of my goats

If none of those are found, omit the avatar image entirely and slide everything up.

(Just kidding about the goats.)

**Comment by bluefuton** [comment]
The first challenge here is finding out when a user doesn't have a gravatar. As far as I can see, Gravatar always hands us back the generic icon if the author doesn't have one, and it looks like every Wordpress.com user gets a Gravatar profile set up, so we can't check `author.profile_url` either.

We could do with a `has_gravatar` property on the author.
