### ISSUE TITLE
Marketplace: Allow complete upgrade plan checkout to SaaS products

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#74212]
When trying to complete the checkout process for a SaaS product upgrade the message "This blog already has some of these upgrades. Did you mean to renew your subscriptions?" is displayed, preventing from completing the checkout.

![Image](https://user-images.githubusercontent.com/351784/228842915-0c55b813-a9e6-40d9-b3fd-7fde113e43d8.png)

**Comment by JulianBustamante** [comment]
This task will require initial research to look for the best approach to allow the creation of the upgraded subscription.

Currently, the prepurchase validations don't allow the creation of a new subscription for a product that already has a subscription created. fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Spynff.jcpbz%2Qfgber.cuc%3Se%3Q9r554r92%233510%2Q3510-og

This task expects the following deliverables

- A number of code changes descriptions to be done
- An example of another similar code

**Comment by cpapazoglou** [comment]
@JulianBustamante What's the status here?

**Comment by cpapazoglou** [comment]
Related diff D107982-code

**Comment by JulianBustamante** [comment]
Deployed r265816-wpcom

**Comment by brezocordero** [comment]
@JulianBustamante 
Which webhooks will be sent?
