### ISSUE TITLE
Fullpost: keyboard shortcuts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7421]
Add support for existing keyboard shortcuts:
- [x] <kdb>esc</kdb> to close post
- [x] <kdb>l</kdb> to like post
- [x] <kdb>j</kdb> for next post
- [x] <kdb>k</kdb> for previous post

**Comment by bluefuton** [comment]
It looks like other keyboard shortcuts are also affected (e.g. j/k to move between posts), as pointed out by @gwwar in Slack.

**Comment by fraying** [comment]
Yup! We should support whatever we had previously. Are they written down anywhere?

**Comment by gwwar** [comment]
see 11162-gh-calypso-pre-oss

**Comment by bluefuton** [comment]
Thanks @gwwar. So we have <kbd>j</kbd> (previous post), <kbd>k</kbd> (next post) and <kbd>esc</kbd> (close post) to implement.

**Comment by designsimply** [comment]
Fixed via #10351, fixes #10097. Props @samouri.
