### ISSUE TITLE
Jetpack.com/stats add user quote

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#74227]
![Image](https://user-images.githubusercontent.com/214813/223829339-bd2369ba-8427-43a2-9330-131120e0046a.png)

The image + quote from Mark-Andrew needs to be added between these two sections within the page. As mentioned on p2, this quote pattern already exists in production, so all we need is the image, quote, and link! I'm attaching here.

> “Jetpack Stats gives you all the information you need to know without Google Analytics. This is all I need to know: who’s coming to my site, where on the web they’re coming from, and where in the world they’re coming from. That’s great for me.”

Mark-Andrew Nordstrom
_Entrepreneur & Open Source Evangelist_

Learn more about how Mark-Andrew uses Jetpack & WordPress within the skateboarding community. 

"Learn more" should link to his site in a new tab: https://nomadskateboarding.blog/

![Image](https://user-images.githubusercontent.com/214813/223828473-2ac913dd-428d-4c45-a974-1daf938e652b.png)

**Comment by jsnmoon** [comment]
Should be fixed by D104064-code 🙂
