### ISSUE TITLE
Fullpost: First Comment, then Like

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7422]
Reverse the order of comment and like in the sidebar.

Currently it's like and then comment. It should be comment and then like.

(This is to match the order in the card view. Current live site is share, comment, like, ellipsis.)

So, should be:

![screen shot 2016-08-11 at 6 03 32 pm](https://cloud.githubusercontent.com/assets/24388/17609904/f5c2d4ce-5fed-11e6-86db-892f8f86c8ce.png)

**Comment by blowery** [comment]
Fixed in #7202
