### ISSUE TITLE
bug: Jetpack.com/stats image shadow cut-off

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#74225]
I noticed on Jetpack.com/stats one of the images that has a shadow has an improper crop—probably due to the container size.

Attaching here. The shadow should extend gracefully like the other images on the page! Thank youuuuu

![Image](https://user-images.githubusercontent.com/214813/223825629-9e56247a-2485-423b-8f82-f02e69cadc77.png)

**Comment by jeffgolenski** [comment]
cc @jsnmoon

**Comment by jsnmoon** [comment]
Should be fixed by D104064-code 🙂
