### ISSUE TITLE
Jetpack.com/stats: Add primary images to the top of the page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#74224]
![Image](https://user-images.githubusercontent.com/214813/223824452-95b49cc3-6b57-484c-96e6-ce8665e7bbc4.jpg)

We just need to add the primary header UI images to the top of the page as seen above. We can keep our existing breakpoints to alter which image is shown. 

* Display large image when viewport is 900px and above
* Display mobile image when viewport is 899px or below

(I think these are the current breakpoints we have. If not, please use whatever we have that's close)

For now, they're static images. In the future we can make them animated. 

Attaching the optimized pngs. Just be aware that the shadows are included in the images.

![Image](https://user-images.githubusercontent.com/214813/223824886-0b189805-bb5c-428a-89fa-21f375ecb73c.png)
![Image](https://user-images.githubusercontent.com/214813/223824885-361d0649-c0ef-4aca-9f3f-11082b59d301.png)

**Comment by jeffgolenski** [comment]
cc @jsnmoon !

**Comment by jsnmoon** [comment]
Should be fixed by D104064-code 🙂
