### ISSUE TITLE
Link for Desktop App Missing Arm64 Option

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#74232]
### Quick summary

On the Get Apps page, it's only showing the option to download the Intel version of the Mac app.

### Steps to reproduce

1. Go to the Get Apps page on your account: https://wordpress.com/me/get-apps

### What you expected to happen

To see both Arm64 and Intel options to download.

### What actually happened

It shows just the Intel version, when you click on it, it downloads the app and loads a page that shows the Arm64 version. This is what Get Apps looks like:

![wp-desktop-mac-app](https://user-images.githubusercontent.com/16104522/223845340-27ef6450-e8be-4134-93fe-557f236a74a2.png)

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by sejas** [comment]
@carinapilar, thanks for reporting :raised_hands:

@katinthehatsite and I will take a look next week.

As a reference, I've found the missing link and design on this page: https://apps.wordpress.com/

![image](https://user-images.githubusercontent.com/779993/224306628-a74acebf-2b88-4012-a2d4-6432c8df53e5.png)

**Comment by katinthehatsite** [comment]
Hi @carinapilar - these should be now fixed!

**Comment by carinapilar** [comment]
That's great, thanks @katinthehatsite, and @sejas! 🙌
