### ISSUE TITLE
Site Assembler: Pattern Category: Scroll to the corresponding UI when hovering the pattern

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#74246]
# Description

We would like to see a preview that scrolls to the corresponding UI when the pattern item is moused over or clicked (Since I felt that if I added several patterns, it would be difficult to grasp what my site looked like).
<img width="1422" alt="Screen Shot 2023-03-08 at 14 42 25" src="https://user-images.githubusercontent.com/5287479/223629467-816d2b29-5e5f-473a-94da-ab412d48a280.png">

https://github.com/Automattic/wp-calypso/pull/74157#issuecomment-1459578432

# Acceptance Criteria
- [ ] Decide when to scroll (click or hover?)
- [ ] It scrolls to the corresponding UI

# Testing 

* Create a new site and click "Start designing" from the bottom of the design picker 
* Choose a header and a footer
* Create your homepage 
* Add patterns 
* Open categories
* Replace, order, and delete patterns
* Continue and verify the patterns are added to a Home template on your site
* Verify it scrolls to the corresponding UI when hovering (clicking?) an item

## Related

- https://github.com/Automattic/wp-calypso/issues/72563
- https://github.com/Automattic/wp-calypso/pull/74157

**Comment by miksansegundo** [comment]
Closing this because the patterns list screen has been removed in #79103
