### ISSUE TITLE
Marketplace: Allow billing intents with 0 price

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#74254]
When billing intents are create through our SaaS flows it seems that billing plans do not accept a 0 price.
We should probably allow 0 priced plans for cases where we need to provision free products like mailpoet.

Related: pdh6GB-2eH-p2#comment-3515

**Comment by gcsecsey** [comment]
I've allowed 0 in the validator, but I'm getting 401 on the API currently, I may have an expired auth token. I'll reach out to the team on how to refresh it to be able to test this further.

Diff created: D104688-code

**Comment by gcsecsey** [comment]
I've tested the purchase and renew flows with a free test product, and found no further issues. It seems that in billingdaddy products are supported with 0 price.

The diff is now ready for review.

**Comment by gcsecsey** [comment]
Changes deployed with r263295-wpcom
