### ISSUE TITLE
Marketplace: add billing intent to upgrade webhook

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#74252]
When an upgrade happens (checkout complete) through our SaaS flow the webhook sent should include:

- that this was an upgrade
- the related billing intent info

Related: pdh6GB-2eH-p2#comment-3509 and 

See https://github.com/Automattic/wp-calypso/issues/74253 for schema

**Comment by epeicher** [comment]
I am waiting for the task https://github.com/Automattic/wp-calypso/issues/74253 to be deployed as I could use that functionality

**Comment by epeicher** [comment]
Diff created D110050-code

**Comment by epeicher** [comment]
Diff deployed r266644-wpcom
