### ISSUE TITLE
Fullpost: Sidebar: Unlinked author name bug

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7425]
Strange bug: occasionally I'm seeing unlinked author names.

For example: https://calypso.live/read/feeds/41437948/posts/1117086279

![screen shot 2016-08-11 at 3 33 47 pm](https://cloud.githubusercontent.com/assets/24388/17609781/f4e55532-5fec-11e6-93ef-c05a9e700c15.png)

The lack of link is also messing up the spacing, I think.

**Comment by blowery** [comment]
Those are authors that have no profile URL associated with their account. We should just use the site URL if the profile URL is missing.

**Comment by fraying** [comment]
Agreed! Please and thank you.
