### ISSUE TITLE
Plans 2023: biannual toggle - implement AB test

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#74264]
Part of addressing pdgrnI-28f-p2 

- Decide if an AB test should run for this
    - See relevant discussion and confirm with @southp pdgrnI-28f-p2#comment-3561
- Once https://github.com/Automattic/wp-calypso/issues/74260, https://github.com/Automattic/wp-calypso/issues/74262, and https://github.com/Automattic/wp-calypso/issues/74261 have shipped

**Comment by southp** [comment]
Assigning myself to it since it's an ongoing negotiation effort :)

**Comment by southp** [comment]
I've updated the issue title from "Implement AB test(?" to "implement AB test" since we have the green light to do so now: pdgrnI-28f-p2#comment-3738 .

* It will be a calypso-side A/B test
* We can likely just use the experiment spec @aaronyan wrote for us: pbxNRc-2qr-p2

**Comment by southp** [comment]
Memo: 

* The PR where hiding the shorter terms comparing to the picked one was first introduced: https://github.com/Automattic/wp-calypso/pull/69643

**Comment by chriskmnds** [comment]
@southp this will probably involve adding the flag to the configs right? 

we've been calling it `plans/biannual-toggle` so far, but it really should be something else - `plans/biennial-toggle` or `plans/2y-toggle`, etc. props to @aneeshd16 who actually checked what "biannual" means :-)

**Comment by southp** [comment]
@chriskmnds Good catch. TIL that `biannual` is a totally different term 🙃
My PR ends up replacing the config flag by the experiment assignment though. If we need the flag again, we should surely update it :)
