### ISSUE TITLE
Fullpost: Daily Post action button

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7426]
Just a note that the new action buttons Daily Post implemented haven't made their way into this branch yet.

![screen shot 2016-08-11 at 3 41 45 pm](https://cloud.githubusercontent.com/assets/24388/17609805/1c3af1b4-5fed-11e6-9093-9759f0f94f99.png)

Live Site: https://wordpress.com/read/feeds/27030/posts/1116987710

Staging: https://calypso.live/read/feeds/27030/posts/1116987710

**Comment by blowery** [comment]
Fixed in #7202
