### ISSUE TITLE
Plans 2023: biannual toggle - improve messaging on checkout page

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#74262]
Part of addressing pdgrnI-28f-p2

From the description:

> Since it also means we will miss the chance of communicating the different offers of a monthly plan, we will also need to enhance communication in the checkout page, when users alter to the monthly term.

Liaise with @southp on what that messaging should be in exact terms

**Comment by southp** [comment]
It looks like what I cited as "proposed design" in that post was already implemented back in 2022: https://github.com/Automattic/wp-calypso/commit/4ef9895f501 . I somehow have had the false impression that we never have that. My apology.

Thus, this will be more about whether we really want to turn on shorter term options in checkout. e.g. we currently don't show the monthly option when an annual one is picked(pdgrnI-28f-p2#comment-3606). Either way, I'm closing his unless there is a new proposed design.
