### ISSUE TITLE
Fullpost: Sidebar: Duplicate Author & Site Names

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7427]
I'd like to make a proposal. In situations where the Author Name and the Site Name are the same, like: https://calypso.live/read/feeds/24393283/posts/1116435392

![screen shot 2016-08-11 at 3 44 35 pm](https://cloud.githubusercontent.com/assets/24388/17609820/46f049cc-5fed-11e6-92c9-ae8269e09eee.png)

I'd like to suggest that we show the text only once, linking to the site view in Reader. This makes the display simpler, and keeps the user in Reader. Use the same bold treatment as the first one.

(In fact, I'd like all the site links to stay in Reader whenever possible.)

**Comment by blowery** [comment]
I think the best way to do this would be to keep the "author" element and just overwrite the linked URL with the site URL, then remove the site element entirely.

**Comment by bluefuton** [comment]
> I think the best way to do this would be to keep the "author" element and just overwrite the linked URL with the site URL, then remove the site element entirely.

Just to clarify - would this be removing the site when the titles are the same, or removing the site in all cases?

**Comment by fraying** [comment]
@bluefuton Just when the titles are the same.
