### ISSUE TITLE
Login: A few oddities on Login link flow

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/wp-calypso#74285]
When using the login link, there are three steps that could use some finesse –maybe they didn't get updated in the general overhaul @simison was doing. Likely they can be separate issues but wanted to connect them at first as they belong to the same flow. @obenland 

**Case 1**
<img width="489" alt="Screen Shot 2023-03-09 at 12 59 41 PM" src="https://user-images.githubusercontent.com/25516611/224091509-f383b738-aded-4b8f-a62c-78cb6fb77df6.png">

The heading has a punctuation other headins in the flows don't. There's white box surrounding the subtext, field, and button. _Request an email_ is confusing as a CTA,

- [x] Remove final punctuation. 
- [x] Correct the bg color to blend with whichever is defined behind. 
- [x] Change CTA to **Get link** or alike.

**Case 2**
<img width="589" alt="Screen Shot 2023-03-09 at 12 58 07 PM" src="https://user-images.githubusercontent.com/25516611/224091511-57511e70-536d-488f-89e1-9dd06731b4bb.png">

- [x] Avoid the widow _in_.
- [x] Correct the bg color to blend with whichever is defined behind. 
- [x] Remove the illustration for now, as we are moving away from those styles. 
- [x] Back should say where the user goes back to. 

**Case 3**
<img width="705" alt="Screen Shot 2023-03-09 at 1 02 28 PM" src="https://user-images.githubusercontent.com/25516611/224091504-2bdff999-2015-4887-add0-f3bd8ddea5a2.png">

- [x] Unsure if this screen is actually needed from a technical standpoint, but I'd perhaps remove it all together, it should log/get me in me automatically without extra click. At the most a loading or transient screen. 
- [x] If we do need to keep it, align styling (fonts and colors) with the other steps. 
- [x] If we do need to keep it, remove the illustration for now, as we are moving away from those styles.

**Comment by obenland** [comment]
@allilevine Do you think Explorers has some capacity next sprint to look at Case 3? I'll pick up Case 1 & 2 myself.

**Comment by allilevine** [comment]
> @allilevine Do you think Explorers has some capacity next sprint to look at Case 3? I'll pick up Case 1 & 2 myself.

@obenland Sounds good! Added to our board.

**Comment by DustyReagan** [comment]
Here is another screen that looks like it needs the same treatment. https://wordpress.com/log-in/link/use The user sees this screen on expired magic links.

![expired-link](https://user-images.githubusercontent.com/140841/226748580-487be34a-d5cf-43fe-bb48-fefaef4c8aa3.png)

- [x] Remove the illustration
- [x] Align styling (fonts and colors) with the other login steps.
- [x] Add some margin between the buttons.

**Comment by DustyReagan** [comment]
All oddities identified here have been addressed. Feel free to reopen this issue (or create a new one) if another inconsistency is found. ☺️
