### ISSUE TITLE
Fullpost: Main Column: Tag icon

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7428]
The tag icon should drop down 2px. (This makes it consistent with how it's used elsewhere.)

Before:
![screen shot 2016-08-11 at 6 08 36 pm](https://cloud.githubusercontent.com/assets/24388/17610037/1cb5ab32-5fef-11e6-9524-064d407d6a10.png)

After:
![screen shot 2016-08-11 at 6 08 36 pm fixed](https://cloud.githubusercontent.com/assets/24388/17610060/511a5526-5fef-11e6-8459-0b57f91ad1a0.png)

**Comment by blowery** [comment]
in #7202 now

**Comment by fraying** [comment]
LGTM!
