### ISSUE TITLE
Marketplace: Update the Thank you page to receive the product type via URL

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#74299]
Currently the Markeptlace Thank you page URL is: `/marketplace/thank-you/:slug1,:slug2,:slug3/:site`
We want to update it to `/marketplace/thank-you/:site?themes=slug1,slug2&plugins=slug1,slug2&plan=slug` in order to know the product type as they get to the Thank you page. 

https://github.com/Automattic/wp-calypso/pull/74125#discussion_r1129187325

**Comment by cpapazoglou** [comment]
@WBerredo do you remember why we avoided using the `orderId`? I assume we can retrieve the order items and the related products from an order.

**Comment by WBerredo** [comment]
As discussed during the planning, we won't always have the `orderId` (ex: free plugins installation) so the plugin slug way has to be supported.
