### ISSUE TITLE
Marketplace: Update Thank You page component to split the logic for different product types

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#74300]
The [Marketplace Thank You](https://github.com/Automattic/wp-calypso/blob/3d1006d1780d61012d7a1f1572abd6660cbb6a7d/client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx) component handles all its logic inside it, as show/hide the progress bar, retrieve .com and .org plugins and themes.

With p9Jlb4-6qr-p2, the Thank You page should support multiple types and it would be increasingly hard to keep up the development on this component the way it is. 

We should change this component's architecture in order to split the logic for different product types in multiple components.

**Comment by WBerredo** [comment]
The [Marketplace Thank You](https://github.com/Automattic/wp-calypso/blob/3d1006d1780d61012d7a1f1572abd6660cbb6a7d/client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx) component handle all its logic inside it, as show/hide the progress bar, retrieve .com and .org plugins and themes.

**Comment by gcsecsey** [comment]
I've looked into this issue briefly and AFAIU the step we need to take are:
- get which product types we have on the current page: either get ithese from the URL params, or iterate over [`productInformationList`](https://github.com/Automattic/wp-calypso/blob/15c6130bafe8b41fda0e8891b4388e32822beb99/client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx#L113), and group by `product_type`
- decide which thank you page version to show based on the groups we have
- as the different versions will have different title, subtitle and footer section, I think it would be best to create a mapping between the thank you page versions and their respective data (texts and footer props)
- render the thank you template and use the data from the map we've created
