### ISSUE TITLE
Stats: Evaluate external chart library

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#74316]
We'll need a line chart for our next feature and we want to analyse our options.
This issue focuses on finding tradeoffs of using an external library.

Things to pay attention to:
- package size
- is it language agnostic (e.g. React.js vs vanilla JS or pure CSS)
- how popular is it (e.g. GitHub stars and followers), and is it still maintained
- if possible, find out if we could extend it (e.g. is it easy to apply custom CSS, write a plugin)
- is it open source 
- does it match features of our existing bar chart (e.g. have tooltips, multiple data sets on one graph)
- extras (e.g. sharp and smooth edges for a data point)
- other

Libraries to check:
- https://chartscss.org/
- https://www.npmjs.com/package/react-chartjs-2
- https://github.com/soorena110/ReactLightChart

The suggested approach would be to analyse one library after another.

**Comment by annacmc** [comment]
I'm going to start with [npmjs.com/package/react-chartjs-2](https://www.npmjs.com/package/react-chartjs-2) first then move onto the other two. Just in case anyone else decides to jump in on this and wants to know what to start with 😄
