### ISSUE TITLE
Post-purchase: Update success copy for plugins

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#74323]
![Image](https://user-images.githubusercontent.com/6586048/224297069-a4584479-30bd-4a77-838e-595789619b9a.png)

Design: 5ddl1WFTEnaIatL2WlZp4k-fi-2459%3A3164

Acceptance criteria:

- [ ] Check that this is the final copy
- [ ] Send in translations early if possible
- [ ] Implement the copy

**Comment by allilevine** [comment]
> Check that this is the final copy

👍 This definitely isn't final copy we can ship (at least in English). We'll need to get final copy from Design or Editorial.

**Comment by DustyReagan** [comment]
I went ahead and created a PR https://github.com/Automattic/wp-calypso/pull/74441 of these copy changes based on the copy in the Figma (it looks to be recently updated). I also tagged the PR with "[Status] Needs Copy Review".
