### ISSUE TITLE
e2e test for purchasing multiple plugins

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#74327]
As part of our testing efforts (p1678135347895659-slack-CKZHG0QCR), we'd like to explicitly break this into an issue to account for the time needed.

Acceptance criteria:

- [ ] Add e2e test for purchasing multiple plugins

**Comment by lupus2k** [comment]
We only tested adding multiple plugins to the cart until we had an atomic user to test it. Follow up [here](https://github.com/Automattic/dotcom-forge/issues/2032)
