### ISSUE TITLE
e2e test for purchasing 1 plugin

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#74326]
As part of our testing efforts (p1678135347895659-slack-CKZHG0QCR), we'd like to explicitly break this into an issue to account for the time needed.

Acceptance criteria:

- [ ] Add e2e test for purchasing 1 plugin

**Comment by lupus2k** [comment]
As we still don't have the test user to purchase plugins, we made the tests for all the post-purchases changes
