### ISSUE TITLE
Add Logo Media Management Layout Break

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wp-calypso#74337]
## Description 

It's hard to tell in Beau's screenshot but it looks like the task to upload a logo. When the select or upload an image window is opened, the layout is broken and the search bar is partially covered by the images. Shared in this post https://hostedwoo.wordpress.com/2023/03/09/a-stroll-through-woo-express/

![Image](https://user-images.githubusercontent.com/89872780/224377360-62a15a48-1dcb-4b5d-bc8e-facc76271467.png)

**Comment by daledupreez** [comment]
I've taken a quick look here -- this looks like it's an issue with the core media library as used in the upload a logo task. I think this should be something Ghidorah takes on as a first pass, as the modal is being loaded from the task list in wp-admin.

cc @adrianduffell, @ilyasfoo

**Comment by ilyasfoo** [comment]
It seems the plugin that caused it is `WordPress.com Editing Toolkit`. I've tried deactivating the plugin and was able to get the styling fixed:

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/3747241/227965532-568191a9-4438-4c13-8d7b-43f4ab17a4cc.png">

**Comment by ilyasfoo** [comment]
Found a duplicate, perhaps we can close this

https://github.com/Automattic/wp-calypso/issues/69568

**Comment by daledupreez** [comment]
I don't think they are from exactly the same source code, at least on Atomic sites. I don't know that the Editor Toolkit plugin pulls in that specific code from Calypso. Regardless, I think this may make more sense for Serenity to investigate further. Are you happy for us to shift this onto our plate, @ilyasfoo?

**Comment by ilyasfoo** [comment]
Yes please @daledupreez, thanks! 🙏

**Comment by andres-blanco** [comment]
I took a look at this. The search input is part of core and it's height is being messed up by a rule that sets `height: 51px` on the class `.search`. It seems to be [this css code](https://github.com/Automattic/wp-calypso/blob/03d9261e5684a01c1ae4ae48a2f2813a83a7e412/client/components/search/style.scss#L18).

At this point it is just intuition, I am struggling to test this since I can't figure out how that `.search` class is leaking to the Atomic site.

**Comment by warrendholmes** [comment]
Closing this since we're going to remove this UX from the Personalise store task.
