### ISSUE TITLE
User Invites: Accept screen doesn't properly wrap long domain

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#74359]
![image](https://user-images.githubusercontent.com/36432/224552568-3ee3d2f8-a278-4d06-84f2-4c3b919b5b85.png)

From p1677684822767929-slack-C0347E545HR

**Done is:**
* We either wrap or clip the domain, depending on what's done elsewhere in the app.

**Comment by katinthehatsite** [comment]
Just wanted to add some observations as I was testing this.

When you invite the user to a site with **a plan** (like Business) but that has not gone Atomic yet. the invites display **Site Title** given to a site:

<img width="1258" alt="Screenshot 2023-03-21 at 1 47 30 PM" src="https://user-images.githubusercontent.com/25575134/226611321-3bd53653-61b4-42af-bcfa-5a9774dc3d96.png">

As soon as the site goes **Atomic**, this is what happens with user invites:

<img width="1265" alt="Screenshot 2023-03-21 at 1 49 59 PM" src="https://user-images.githubusercontent.com/25575134/226611417-a368d243-1d50-4afe-8b8e-6fe58d51e59e.png">
