### ISSUE TITLE
Duotone Filter Not Being Applied to Images 

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#74357]
### Quick summary

When a custom duotone filter color is applied to an image, it shows in the Editor, but not on the live site. However, the preset filter colors work as expected. 

### Steps to reproduce

1. Add an image block to your site.
2. Click on the duotone icon and select a shadow and highlight color.
3. Filter is applied in Editor but not on the live site. 
4. Alternatively, if you choose a preset duotone color, then it works as expected. 

https://user-images.githubusercontent.com/74204272/224519588-2dccc560-ecec-4674-8c32-0cc5ff2763e5.mp4

### What you expected to happen

To see filter applied on site. 

### What actually happened

The image remained the same even with the filter applied. Issue reported in 6035440-zen. The user says it was working as expected until today. A workaround could be taking a screenshot of the image with the filter applied in the Editor and reuploading it 😅

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by carolframen** [comment]
Another one #6034973-zd

**Comment by sophiegyo** [comment]
It seems like this specifically affects Gutenberg 15.3.1 - the user in 6030671-zd states that they switched Gutenberg off and all their duotone settings came back.

This does seem to be specific to atomic, I tried on my self-hosted site with 15.3.1 and the duotone works fine there.

**Comment by nicolynramos** [comment]
Another one here on a simple site using Blank Canvas. 6039032-zd
Preset duotone filters work fine, however, setting up a custom filter does not work.

**Comment by carolframen** [comment]
#6039070-zen

**Comment by aleone89** [comment]
Another report here: https://wordpress.com/forums/topic/quadrat-black-theme-broken-colors-wonky/?view=all this time using the Quadrat theme.

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on P2 - Replicated
- Tested on Simple - Replicated 
- Tested on AT - Replicated 
- Tested on Self-hosted - Replicated 



📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cometgrrl** [comment]
This should be fixed in the next version of Gutenberg.  https://github.com/WordPress/gutenberg/pull/49004

**Comment by rakshitwesley** [comment]
Reported here: 6049720-zd-woothemes

**Comment by rakshitwesley** [comment]
6050267-zd-woothemes

**Comment by kerrynicl** [comment]
another report 6050925-zd-woothemes

**Comment by hacchism** [comment]
Another report: 6052094-zen

**Comment by Agepeuve** [comment]
Another report: https://wordpress.com/es/forums/topic/filtro-duotono/

**Comment by carolframen** [comment]
#6053836-zen

**Comment by daria2303** [comment]
[6050249-zd-woothemes](https://href.li/?6050249-zd-woothemes)

**Comment by Joshgrygiel** [comment]
Another #6060210-zen

**Comment by Gustavo-Hilario** [comment]
Another report here: 40472880-hc

**Comment by jp-imagines** [comment]
Another report in 40859052-hc.

**Comment by tellisbethel** [comment]
Same issue on the Sequential theme here: 27843422-hc (I originally reported this [here](https://github.com/Automattic/themes/issues/7054), but not sure if it's the same.)

I assigned a CSS class to the gallery block that had the duotone applied and provided CSS to turn the images grayscale as a close approximation to their original duotone settings:

/* Set images grayscale to somewhat imitate duotone feature | 27843422-hc (db) */
.homepage-logos {
filter: grayscale(100%);
opacity: 80%;
}

**Comment by zyousafi** [comment]
Another report in 42323227-hc

They'd like to be notified when there's a fix

**Comment by mgozdis** [comment]
Recent Gutenberg plugin update appears to be breaking this again. This user reported the issue was fixed and it now returned after Gutenberg updated to 15.7.0. Deactivating Gutenberg worked as a workaround. 

41237642-hc

**Comment by kspilarski** [comment]
32056521-hc 
Yuga theme

**Comment by csabarakasz** [comment]
43279766-hc The image is inside a cover block and the duotone is still not applied. Suggested using this website https://medialoot.com/duotones/ to add the duotone filter to the image before uploading it.

**Comment by kspilarski** [comment]
43034296-hc Stow theme

**Comment by rickmgithub** [comment]
6248218-zd Skivers theme

**Comment by carolframen** [comment]
Another report 6276618-zen

This user also has issues with the background of the cover block not showing how it should. Not sure if it is related or a coincidence. I asked them some questions to try to figure it out.

**Comment by csabarakasz** [comment]
42723322-hc suggested https://medialoot.com/duotones/
theme: Yuga

**Comment by jorpdesigns** [comment]
Reported in 6286303-zd-woothemes

Suggested using this tool to generate the filtered image: https://medialoot.com/duotones/

**Comment by mgozdis** [comment]
Just noting again that deactivating Gutenberg is a workaround and the filters then work. I first saw it break again in 15.7.0 and it's also still broken in 15.7.1 on my test sites.

**Comment by freelylovinglife** [comment]
ZD-6297165 Another Report - Could not find a preset option for the images for this user.

**Comment by csabarakasz** [comment]
42808196-hc image in the cover. Shared https://medialoot.com/duotones/

**Comment by mriyazuddin** [comment]
- [ ] 6296238

**Comment by tvolpert** [comment]
Another report here. Simple site, Blank Canvas theme.

- [ ] 6304402-zen

**Comment by rickmgithub** [comment]
Simple site - 6293212-zd

Shared the https://medialoot.com/duotones/

......site.

**Comment by brinbliss** [comment]
- [ ] 6289768-zd

Simple site, Stow theme. Shared workaround site with user, or suggested they use the premade duotone filters for now.

**Comment by sudeepbaral** [comment]
- [ ] 6310203-zd

Plan: Pro
Theme: Shawburn

Shared workaround of deactivating Gutenberg as well as using another alternative - https://medialoot.com/duotones/

**Comment by carolframen** [comment]
6336281-zd

**Comment by dolgelukkig** [comment]
6345121-zd 
simple site on a personal plan, theme is Illustratr.

**Comment by dcalhoun** [comment]
From testing this recently, custom Duotone filters now appear to function as expected. For me, it works for a Simple site using Twenty Twenty-Three theme and an Atomic site with a custom theme. 

This issue appears to be resolved by https://github.com/WordPress/gutenberg/pull/50678. Please feel free to reopen this issue if the problem still occurs.

**Comment by sguzovskaia** [comment]
I'm reopening this issue. The applied custom duotone filter is not showing on the live site for images, but visible in the Editor.
Noticed in hc-6427916/zen-6428606.
Reproduced the same on my test Atomic site.

**Comment by cuemarie** [comment]
@sguzovskaia From my tests, it seems the Duotone issue this user is facing is specifically on classic themes, like **Libre 2** which the user has active on their site. 

On an AT site using FSE theme Twenty Twenty Three, the duotone works as expected.

On the same site using **Twenty Twenty** or **Libre 2**, duotone is applied in the editor, but not on the live site.

![Markup on 2023-06-20 at 10:37:04](https://github.com/Automattic/wp-calypso/assets/27249804/49bbc835-e586-44ad-88b0-51b58cf93140)

![Markup on 2023-06-20 at 10:38:26](https://github.com/Automattic/wp-calypso/assets/27249804/aa329b46-7296-49f2-b1ef-4d5e845c166a)

---

This original issue was happening across FSE and Classic themes, so with this in mind, I'm closing this original report, and have opened this new report instead: 

- https://github.com/Automattic/wp-calypso/issues/78442
