### ISSUE TITLE
SSL in some location invaild

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#74354]
### Quick summary

Test www.ttcath.org by using Uptima SSL monitor, the SSL of the site in some location invailed

### Steps to reproduce

1. proxy visit www.ttcath.org
2. SSL invaild

### What you expected to happen

The SSL must vaild in entire world

### What actually happened

proxy visit by using  151.236.25.95 at Mar 11 2023, 19:26:52 visit ttcath.org, the browser says the connection with the website is not scecure. SSL expaired.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by ttcath** [comment]
@tyxla pls fix the problem

**Comment by tyxla** [comment]
This looks like another duplicate of #74358 - feel free to close it @ttcath, having multiple similar issues doesn't help us much. I haven't been able to reproduce issues with the SSL certificate, so I've requested triage in #74358.

**Comment by poeticabdul** [comment]
User reported the issue here 6028987-zen

**Comment by jeherve** [comment]
Closing as duplicate of #74358

**Comment by jeherve** [comment]
Closing as duplicate of #74358
