### ISSUE TITLE
Add Tracks props to differentiate domain upsells

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#74352]
Followup to https://github.com/Automattic/dotcom-forge/issues/1564

Add Tracks props to My Home domain upsells to differentiate between free users, monthly plan users, and yearly plan users, so we can create a Tracks funnel for each group.

**Comment by allilevine** [comment]
@DustyReagan Should we put this on hold since the implementation could change if we're moving it into the card carousel?

**Comment by DustyReagan** [comment]
Yeah, that makes sense to me. 👍
