### ISSUE TITLE
Time zone not reflected in date heading in wp-admin

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/wp-calypso#74369]
### Impacted plugin

Jetpack

### Quick summary

The timezone set in a site's General settings is not reflected in the date shown on the Stats page in wp-admin.

Reported in 6027668-zen

### Steps to reproduce

The current time is 14:10 UTC on March 11th.

My site's timezone is set to UTC+0 in Settings > General.

If I look at my stats in wp-admin and in WordPress.com they both correctly show the date as March 11th.

---

Now if I change my site's timezone to UTC+13, the date should be March 12th (03:10 UTC+13)

If I look at my stats in WordPress.com, the date is March 12th as expected:

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/1990037/224489516-eb70ddb9-f564-45da-87a0-c1e6ee3b6f41.png">

But in wp-admin, the date is still March 11th:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/1990037/224489541-e8b9b427-4985-4b65-a40a-f59ef814d7a8.png">

### A clear and concise description of what you expected to happen.

I expect the date in Stats to show the correct date according to the timezone of my site, and to show the same date in wp-admin and WordPress.com.

### What actually happened

The date is correct in WordPress.com, but not in wp-admin.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by danjjohnson** [comment]
Note: The user in the ticket reported that the date changes for them at 11am Melbourne time (UTC+11), which would be midnight UTC, suggesting that the date in wp-admin is set to UTC.

**Comment by myhro** [comment]
I was able to reproduce this issue in the [Jetpack Docker development environment][1] by using the [`faketime` utility][2] and working around Apache, serving WordPress directly through the `php` command.

# Docker setup

First there's a need to point port `80` (in the host) to another port, like `8000` (in the container), avoiding Apache running on port `80`:

```diff
diff --git a/tools/docker/docker-compose.yml b/tools/docker/docker-compose.yml
index ed3b73fae43..1d84042b6dd 100644
--- a/tools/docker/docker-compose.yml
+++ b/tools/docker/docker-compose.yml
@@ -42,7 +42,7 @@ services:
       - ./logs/${COMPOSE_PROJECT_NAME}/php:/var/log/php
       - ./bin:/var/scripts
     ports:
-      - '${PORT_WORDPRESS:-80}:80'
+      - '80:8000'
     env_file:
       - default.env
       - .env
```

After that, start the Docker services normally and open a shell in the WordPress container:

```
$ jetpack docker up -d
$ docker exec -it jetpack_dev-wordpress-1 bash
```

## Faketime setup

In the container, install the `faketime` package and use it to start the PHP development server, binding it to the port `8000` on all IPs:

```
root@645d1a107c79:/var/www/html# apt update
root@645d1a107c79:/var/www/html# apt install -y faketime
root@645d1a107c79:/var/www/html# faketime '14:10' php -S 0.0.0.0:8000
```

# Positive offsets

When accessing `/wp-admin/admin.php?page=stats`, I'm redirected to `/wp-admin/admin.php?page=stats#!/stats/day/236297789?page=stats` and it still shows `December 14`, whereas it should be `15`.

| Settings | Stats |
| :-: | :-: |
| <img width="562" alt="Image" src="https://github.com/user-attachments/assets/d95b49cf-cb5d-407d-a332-ef3442a62de4" /> | <img width="533" alt="Image" src="https://github.com/user-attachments/assets/c37d5f64-2cf5-4141-b18a-51b46d468342" /> |

I also tried with different hours after 14:00 UTC, like 23:00 UTC which is noon next day in UTC+13, and the day is still the same.

# Negative offsets

At the same time, this is not an issue where we are just showing "the day as it is in UTC", given that it works for negative offsets:

| Settings | Stats |
| :-: | :-: |
| <img width="563" alt="Image" src="https://github.com/user-attachments/assets/e9260a7d-9a55-4181-859d-4e69482d8ef9" /> | <img width="534" alt="Image" src="https://github.com/user-attachments/assets/88bd6554-b8a0-43a2-9f38-f25028c5b1e9" /> |

[1]: https://github.com/Automattic/jetpack/tree/4ff8c9007f33663bc13e20cd7e1be251b08d1c24/tools/docker
[2]: https://packages.debian.org/bookworm/faketime

**Comment by myhro** [comment]
Apparently I was debugging an outdated Odyssey Stats page. The current design doesn't contain the date information (p1734374104197649-slack-C0438NHCLSY), so apparently this issue isn't relevant anymore.
