### ISSUE TITLE
Add Marketplace Theme informations to the cart

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#74371]
Add the necessary information to complete #74295 

Discussion here p1678098925961309-slack-C02JPCHEKDY

**Comment by cpapazoglou** [comment]
We should be able to reuse `Marketplace_Theme_Product_Catalog::is_marketplace_theme_slug();` like in fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sgurzrf%2Srynfgvpfrnepu.cuc%3Se%3Q1n44n034%23419-og

just make sure we are adding the product type in the returned properties.

**Comment by epeicher** [comment]
This task will be used to implement the backend changes required by the task:
- https://github.com/Automattic/wp-calypso/issues/74295

**Comment by epeicher** [comment]
Diff created D104617-code

**Comment by epeicher** [comment]
Deployed r263278-wpcom
