### ISSUE TITLE
Checkout: After a user pays via PayPal.com, redirect them to the thank you page

### ISSUE THREAD

**Issue by mattm** [Automattic/wp-calypso#7438]
#### Steps to reproduce
1. Purchase a plan using the PayPal checkout option
2. Notice that you are redirected to wordpress.com afterwards, not the thank you page like you would be if you paid via a credit card
#### Why this is important

Besides being a better experience for users because they're provided with follow up instructions after completing a purchase, the thank you page is where we fire all of our analytics and ad conversion events.

By not redirecting users there after completing a purchase with PayPal, we're causing not just our internal analytics to be underreported (like `calypso_checkout_payment_success` and `calypso_checkout_product_purchase`), we don't fire any of the conversion events for our third party ad platforms (like AdWords, Criteo, Bing, Facebook, One by AOL, and others).

Fixing this would provide for a better user experience and improve the reliability of our analytics data, helping us make better decisions that impact our business.

**Comment by rads** [comment]
As far as I know this was how it originally worked when we first implemented Calypso store. There was a bit of hacking involved because we had to use `localStorage` to store the checkout state and this didn't work in Safari, but we did end up going back to the Thank You page after a PPE checkout. Maybe this was changed to go straight to WordPress.com because of the Safari issue.

**Comment by meremagee** [comment]
Note (to self), post-checkout, I was taken to Atlas reader in this flow:
![](https://cloudup.com/cWFbcegFo6K+)

**Comment by meremagee** [comment]
Currently in testing: updated Thank-You page with streamlined CTA that takes user to the optimum NUX. The url & data handling should be the same, but wanted to have this noted for posterity https://github.com/Automattic/wp-calypso/pull/8012.

**Comment by meremagee** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/8616

**Comment by mattm** [comment]
@meremagee Hey hey - You mentioned at the marketing meetup that your team might get a chance to look at this. Are there still plans to? (We run into frequent issues in marketing because these tracking pixels aren't fired for users that pay via PayPal.)

**Comment by marekhrabe** [comment]
This was fixed yesterday by altering our server configuration. More info in p58i-5c9-p2

**Comment by lsinger** [comment]
Hooray! 🎉

**Comment by mattm** [comment]
Yay :)
