### ISSUE TITLE
Stats: Add new subscriber chart section

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#74404]
When #74403 is done, use findings from the chart analysis tickets (#74316, #74317, #74318) and create a section on the Traffic page showing the subscriber count changing over time.

**Comment by a8ck3n** [comment]
Will set up a new placeholder section using [the existing](https://wpcalypso.wordpress.com/devdocs/design/line-chart) `LineChart` component and some temporary data.
