### ISSUE TITLE
NUX: Verifying your email immediately after signing up loses NUX plan selection

### ISSUE THREAD

**Issue by mattm** [Automattic/wp-calypso#7440]
#### Steps to reproduce

1) Go through the NUX and select the Personal Plan. 
2) After submitting your account details, you're instructed to check your email while waiting:

![screen shot 2016-08-12 at 3 01 28 pm 1](https://cloud.githubusercontent.com/assets/44436/17633885/b6fcae4e-609d-11e6-831c-b6d16a72e36e.png)

3) Clicking the link in the email takes me to a log in page where the `redirect_to` URL parameter is set to `https://wordpress.com/posts/mhmazur20160812v3.wordpress.com?verified=1`.

![screen shot 2016-08-12 at 3 03 09 pm](https://cloud.githubusercontent.com/assets/44436/17633925/e7158416-609d-11e6-8019-d377fd62a686.png)

4) Logging in takes me to Blog Posts, ignoring the fact that I expressed interest in the Personal Plan during the NUX.

![screen shot 2016-08-12 at 3 04 20 pm](https://cloud.githubusercontent.com/assets/44436/17633957/10c6defe-609e-11e6-8193-41509d8906a6.png)
#### What I expected

An easy fix for this would be to remove the notice while the account is being created:

> We’ve sent a message to mhmazur+20160812v3@automattic.com. Please use this time to confirm your email address.

This would keep users in the NUX which would then take them to checkout after the account is created.
#### What happened instead

I go to check my email, have to sign in to confirm my account, then forget about that Personal Plan I had expressed interest in, losing us revenue.

**Comment by alisterscott** [comment]
The message doesn't show on the loading screen for paid plans any more, so I can close this issue:

<img width="568" alt="screen shot 2017-07-18 at 11 56 07 am" src="https://user-images.githubusercontent.com/128826/28297240-2da489d6-6bb0-11e7-832c-db4261a39db2.png">
