### ISSUE TITLE
Stats: Add mock data for subscriber count

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#74403]
Check in with Squad 1 and come up with a contract between the back-end and front-end regarding the data that will be used for the subscribers' chart.

Document the structure here and propose a place to store the mock data before implementation.
It might be a good idea to keep it in a `connect()` function that will be replaced with proper action and reducer in the future.

Tasks:
- [x] Document data structure
- [x] Provide mock data allowing us to create a chart

**Comment by annacmc** [comment]
Notes so far:

* Squad 1 are still finalising their mock API and finalising the data structure. In the meantime, we expect that it will likely take the format of the other stats endpoint returns. CC @kangzj here for more details about the specific data being used & confirmation of the structure once it's available. 
* I think that we could create a separate mock data store in Redux (`client/state/stats`) to use temporarily until real data is available for us. I have been playing around with some approaches at how to do this today. 
* We can then use the `connect()` function along with a `mapStateToProps()` function to map the mocked data object to the component's props and use as needed in our new section.
* Once the real data is ready, we can replace the `connect()` function and remove the mock data store in redux.

**Comment by annacmc** [comment]
Noting that the [following patch ](D105106-code) contains sample data structure for the API endpoint return

**Comment by grzegorz-cp** [comment]
The team has discussed adding Redux with `react-query` but decided to opt for an easier implementation, using `react-query` only. At this point, this is sufficient. If we need Redux in the future, we can reference commits related to this GH issue and add Redux code.
