### ISSUE TITLE
LaunchPad - create a "choose domain" task flow.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#74416]
We want to update the "choose domain" task flow to not be reliant on calypso and have a better cohesive feel with the onboarding flows it is used with.

For this flow to be considered complete:
- [x] Create a stepper flow to use with the "choose domain" launchpad task.
- [x] The first step of the flow is domains selection, and allows the user for a clear way to select that they are happy with their current domain to return to launchpad with the step completed.
- [x] The second step (if choosing a domain) should be the plans and pricing grid. Note - we can show the "free" plan here IFF the domain they chose was a free domain.
- [x] After this we should leverage the existing checkout step, and completion should return to the launchpad.

Some visual and design representation of this flow can be found in p9Jlb4-6mr-p2 (2nd video) 

When this is completed, lets move the below follow up tasks to a new issue to be actioned:
- <s> update the launchpad congrats/launch modal to lean harder into the domain upsell language (@nuriapenya is looking into this) </s> moved this to a separate issue - https://github.com/Automattic/wp-calypso/issues/74712 
- [ ] after that is complete (per p9Jlb4-6mr-p2) we will also want to remove the "choose domain" task from flows that already have domain selection steps (pretty much all main flows except "free"). - when this is being done we should notify @paulbonahora as he has requested a ping once this goes into effect.

**Comment by jeyip** [comment]
@agrullon95 started on this https://github.com/Automattic/wp-calypso/pull/74313
