### ISSUE TITLE
`/subscriptions/settings`: Create client-side data interface for retrieving subscription settings.

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74422]
Since this is going to a new API endpoint I would encourage using react-query for integration (see related conversation: p1678807696397609-slack-C7YPUHBB2).

The call to the new API should be integrated into [@automattic/data-stores](https://github.com/Automattic/wp-calypso/tree/trunk/packages/data-stores).

**Comment by TimBroddin** [comment]
@mashikag am I making the right assumptions here?

- we should add a new store to [@automattic/data-stores](https://github.com/Automattic/wp-calypso/tree/trunk/packages/data-stores) 
- the hooks to call React-Query's useQuery and populate the store shoud live in our `subscription-manager`, in useQuery's onSuccess method we dispatch to the store (like they do here: p9oQ9f-1qT-p2)

**Comment by mashikag** [comment]
> we should add a new store to [@automattic/data-stores](https://github.com/Automattic/wp-calypso/tree/trunk/packages/data-stores)

It depends on what you mean by adding a new store. For now, we will just add a new subdirectory with our queries. Similarly to [`starter-designs-queries`](https://github.com/Automattic/wp-calypso/tree/trunk/packages/data-stores/src/starter-designs-queries), or to [`support-queries`](https://github.com/Automattic/wp-calypso/tree/trunk/packages/data-stores/src/support-queries).

**Comment by mashikag** [comment]
> in useQuery's onSuccess method we dispatch to the store (like they do here: p9oQ9f-1qT-p2)

For now, I do not see a point of storing this user state in a Redux store, especially when it comes to our external subscription management portal.
