### ISSUE TITLE
Checkout: Improve mounting components

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#7442]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checkout/<testing-site>/personal
2. Open dev tools and uncheck some css properties like below

![image](https://cloud.githubusercontent.com/assets/77539/17635920/8336f6ba-60b0-11e6-8a61-3c1590a0712c.png)

![image](https://cloud.githubusercontent.com/assets/77539/17635924/88d43056-60b0-11e6-95a1-2b17684f62f9.png)

3. You should see all component mounted.

![image](https://cloud.githubusercontent.com/assets/77539/17635905/7d5f8568-60b0-11e6-808a-43b7f245ec28.png)

#### What I expected

See only one component mounted instead of hiding them through of css properties

**Comment by gwwar** [comment]
This was closed by #7507 right? @retrofox feel free to reopen if not
