### ISSUE TITLE
Task: Clean up newsletter flow code from /start

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#74458]
### Details

As we are using domains and plans for stepper on newsletter flows, we need to clean up the /start code done previously.

### Related

#74411

**Comment by escapemanuele** [comment]
Hey @renancarvalho, I think that this can be closed, right?

**Comment by renancarvalho** [comment]
I need approvals on the[ PR here](https://github.com/Automattic/wp-calypso/pull/74466)

**Comment by escapemanuele** [comment]
Approved ✅
