### ISSUE TITLE
Add Goodreads as a Block

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#74494]
### What

We've tried to encourage our users to update to newer themes, but several legacy widgets, including Goodreads, do not work in block themes.

### Why

Currently, to get the old look Goodreads widget look with a newer theme, a user has to copy the GoodReads code, select just the "Static HTML" portion, and paste that into a block. And then they'd have to repeat this every time they update their Goodreads account.

### How

Can we create a Goodreads block so folks who enjoy the legacy widget are free to update their sites to newer themes?

I'd love to make it less complicated than the old version, too, and properly support readers as well as authors. [Here are the old steps.](https://wordpress.com/support/widgets/goodreads-widget/)

**Comment by supernovia** [comment]
Requested here:
https://wordpress.com/forums/topic/goodreads-widget-seemingly-doesnt-exist-anymore/

**Comment by jordesign** [comment]
Collecting some additional interactions where we had to offer a workaround, or it wasn't possible for users to include goodreads.

* 35875562-hc
* 35525465-hc
*38733671-hc
* 37663780-hc
*35875256-hc
* 35210607-hc
* 35880837-hc
* 5987237-zd-woothemes
* 5193398-zd-woothemes
* 5318371-zd-woothemes
* 5885164-zd-woothemes

**Comment by jordesign** [comment]
I'm also classing this as triaged - and moving it to Feature Requests

**Comment by Aurorum** [comment]
@supernovia Hi Velda, I'm working on adding this (hopefully including with proper support for authors) but do you have an example of the code which Goodreads provides for their Author widgets? 

I'm afraid that I don't have an Authors Account so I can't access that section...

**Comment by Aurorum** [comment]
7561160-zen
