### ISSUE TITLE
`/subscriptions/settings`: Update "Sites" and "Comments" tabs to point to re-skinned portal

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74503]
For the short term release of the "Settings" view implemented in Calypso, the "Sites" and the "Comments" tabs should redirect the user to the relevant view in the re-skinned portal.

## Acceptance Criteria
- when "Sites" tab is clicked, the user should be redirected to the re-skinned portal with the "Sites" tab view open
- when "Comments" tab is clicked, the user should be redirected to the re-skinned portal with the "Comments" tab view open

**Comment by ivan-ottinger** [comment]
If I understand correctly:
- the "Sites" and "Comments" tabs should link to the re-skinned portal for the non-logged in user as well, right? 🤔 
- the "Sites" tab should no longer be the default view - since it will be directing users to the re-skinned portal temporarily. We could make the "Settings" tab the default one (until the "Sites" and "Comments" views are finished).

**Comment by mashikag** [comment]
> the "Sites" and "Comments" tabs should link to the re-skinned portal for the non-logged in user as well, right? 🤔

Yes. In fact, our main focus right now is a non-logged in user. At the same time, we should to keep in mind that the components we develop will be later reused in reader for logged-in users too.

>the "Sites" tab should no longer be the default view - since it will be directing users to the re-skinned portal temporarily. We could make the "Settings" tab the default one (until the "Sites" and "Comments" views are finished).

Good point. Let's do that. 👍

**Comment by ivan-ottinger** [comment]
Thanks! 🙂 

> Yes. In fact, our main focus right now is a non-logged in user. At the same time, we should to keep in mind that the components we develop will be later reused in reader for logged-in users too.

As far as I know, there haven't been discussions on setting the correct locale of the Subscription Management portal (In Calypso) for the non-logged in user, right?

**Comment by mashikag** [comment]
> As far as I know, there haven't been discussions on setting the correct locale of the Subscription Management portal (In Calypso) for the non-logged in user, right?

Yes, you are right once again. 🙈 There was non consideration for locale yet other than submitting text for translations.

**Comment by ivan-ottinger** [comment]
https://github.com/Automattic/wp-calypso/pull/74567 is now ready for review.

**Comment by ivan-ottinger** [comment]
https://github.com/Automattic/wp-calypso/pull/74567 is now merged and deployed.
