### ISSUE TITLE
Heading colors on checkout success/thank you page

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wp-calypso#74511]
After you upgrade from a free trial to the paid plan, the confirmation page headings are currently blue. They need to be black for consistency across the UI. 

For reference, we noticed his after upgrading from an expired free trial.

**Comment by andres-blanco** [comment]
I've just updated from free to Essential and this is what I am seeing
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/375980/232135799-5e83387e-2085-42b6-b5d9-9d6617a4131d.png">

You are referring to the cards titles @that-mike-bal ? (Launch your store, Promote your products etc)

**Comment by that-mike-bal** [comment]
This was from design so @FlorianBru might be able to clarify. I believe it is for each of the headings under the images e.g. "Launch your store" 

See design
<img width="713" alt="Screen Shot 2023-04-14 at 3 38 08 PM" src="https://user-images.githubusercontent.com/89872780/232150234-fd5baf14-d713-4d1e-90eb-f76227dabc86.png">
