### ISSUE TITLE
`/subscriptions/settings`: Create “Email address” input

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#74519]
## Design
inDLaEQV8jJ21O4WXawIsJ-fi-712%3A29263

## Description of the task

We need to create a text field for the external user to be able to modify their email address. An external user is a user without a WordPress account.

This text field is not in the design, but we must keep the same style as the other fields in the Figma file. This means a label with the text `Email address` and a text field containing the user's email address.

## Acceptance Criteria
- display the label with the input, with the same styles as the Figma design for the other inputs.
- the label should both be translated
- have the correct value displayed based on the relevant prop passed into the `UserSettings` container
- Note: There is no need to deal with the submission of the changed value as part of this task. The submission will be implemented with the following task once all the settings form inputs are included in the parent component: https://github.com/Automattic/wp-calypso/issues/74433

## Related conversations
- p1679044133451139-slack-C02TCEHP3HA

**Comment by mashikag** [comment]
Blocked because of p1679044133451139-slack-C02TCEHP3HA

@yansern can you suggest whether we should go ahead with this task. Is it in [our current milestone](https://github.com/Automattic/wp-calypso/milestone/420) to fix the email change?

**Comment by yansern** [comment]
This is no longer needed as we are moving all email subcribers to WPCOM users and external portal is removed.
