### ISSUE TITLE
User Management: Empty list for email-subscribers

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#74528]
### Quick summary

The user list is empty when accessing the http://wordpress.com/people/email-followers/ route.
Users get there through the "Manage Subscribers" button in the "Subscriber Import Completed" email after going through the Newsletter onboarding flow.

### Steps to reproduce

1. Start at wordpress.com/start/newsletter and go through the onboarding flow.
2. In the step to add email subscribers, enter your email address.
3. Launch the site.
4. When the "Subscriber Import Completed" email shows up, click "Manage Subscribers"
5. See this:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/1398304/225713283-41f0a309-83c9-4e1f-a024-02bfbf26d5e1.png">

### What you expected to happen

To see a list of email subscribers.

### What actually happened

The list is empty.

It looks like this switch statement doesn't account for the `email-followers` case
https://github.com/Automattic/wp-calypso/blob/391f81bea18051ef155398fe2de4aba51455ebe4/client/my-sites/people/subscribers-team/index.tsx#L87-L118

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by obenland** [comment]
@bogiii It looks like `SubscribersTeam` doesn't handle all the cases that `PeopleList` can. Short term fix might be to limit `SubscribersTeam` to only the `context.params.filter`s that it has results for?

https://github.com/Automattic/wp-calypso/blob/391f81bea18051ef155398fe2de4aba51455ebe4/client/my-sites/people/controller.js#L98-L103

**Comment by obenland** [comment]
Based on https://github.com/Automattic/wp-calypso/pull/74533#issuecomment-1472712358 it looks like this should really be a bug report about the button in the email needing to be updated.

**Comment by bogiii** [comment]
Email template's CTA has been updated: D107853-code
