### ISSUE TITLE
`/settings`: Apply updated design to mobile header

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74526]
## Design
inDLaEQV8jJ21O4WXawIsJ-fi-712-16233
![Image](https://user-images.githubusercontent.com/2019970/225703923-83fad10b-9e0c-40ec-a958-60d32005b372.png)

## Related conversation
p1678388803357779-slack-C02TCEHP3HA

___
Thanks, @saygunnyc, for a quick turnaround on this! 🙇‍♂️

**Comment by mashikag** [comment]
@yansern please include in our current milestone if needed.

**Comment by phcp** [comment]
~~@mashikag as the header is still missing on the subscriptions page I'll include it as part of the task, ok?~~
Ignore it, it seems to be an issue for logged in users, I'll try to understand that better later today and if that is the case I'll open a task for that.

**Comment by saygunnyc** [comment]
Thank you for tackling it!

**Comment by yansern** [comment]
> @yansern please include in our current milestone if needed.

Not the highest priority but since the work is done we'll bring it in. :)
