### ISSUE TITLE
Giphy block: unable to select from 'Related GIFs'

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#74546]
### Quick summary

When using the Gutenberg Giphy block and you've selected a GIF to use, a row of related GIFs appear at the bottom. It is not currently possible to selected one of these related GIFs to use instead.

### Steps to reproduce

1. Create a new post on WordPress.com and add a GIF block (type `/gif` in the editor).
2. Type a search phrase like "charlie chocolate factory".
3. Choose one of the results from the top row of thumbnails.
4. Hover over the selected GIF. Note that the 'Related GIFs' panel appears at the bottom.
5. Try to choose one of the Related GIFs.

<img width="688" alt="Screenshot 2023-03-17 at 9 31 33 AM" src="https://user-images.githubusercontent.com/17325/225756018-6ebc2e95-3995-4580-8087-7e1b56eb6834.png">

### What you expected to happen

Clicking on one of the Related GIFs chooses that GIF and replaces the main one shown.

### What actually happened

Clicking on any of the Related GIFs did not have any effect.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Firefox Mac v110

**Comment by cometgrrl** [comment]
This is a Gutenberg issue, not a Dotcom issue, and needs to be filed in https://github.com/WordPress/[gutenberg](https://github.com/WordPress/gutenberg).

Lowering the priority as this seems to be FF-specific. The related gifs only show up in FF (I checked in Arc and Chrome), and the related gifs only show up on the front end, not in the editor in those browsers. Also, I do not know if it's intended functionality or not.

**Comment by bluefuton** [comment]
Thanks @cometgrrl! I filed it here because Gutenberg doesn't appear to have a Giphy block yet: https://github.com/WordPress/gutenberg/issues/13426

I subsequently found out that it's a Jetpack block: https://github.com/Automattic/jetpack/pull/10989 so will file an issue in the Jetpack repo. Shall we close this one?

> Lowering the priority as this seems to be FF-specific. The related gifs only show up in FF (I checked in Arc and Chrome), and the related gifs only show up on the front end, not in the editor in those browsers.

Thanks for discovering this! I will report the bug as Firefox-only.

**Comment by cometgrrl** [comment]
> I subsequently found out that it's a Jetpack block: https://github.com/Automattic/jetpack/pull/10989 so will file an issue in the Jetpack repo. Shall we close this one?

Ah, yeah, I didn't actually realize that it was a Jetpack block. We can close this one.  In the future, you can use "transfer issue" on the right-side panel to move issues between wp-calypso and Jetpack repos in Github, rather than creating a new issue.
