### ISSUE TITLE
Task: Remove Gutenboarding related specs and POMs from `@automattic/calypso-e2e`

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#74544]
### Details

Gutenboarding is being removed in https://github.com/Automattic/wp-calypso/pull/74475. 

`@automattic/calypso-e2e` has POMs that support the Gutenboarding flow, and there may also be remaining E2Es that still use the endpoint. Deprecate them.

### Related

Depends on https://github.com/Automattic/wp-calypso/pull/74475.

**Comment by tyxla** [comment]
Thank you for considering further cleanup, @worldomonation!

https://github.com/Automattic/wp-calypso/pull/74475 has just landed.

**Comment by worldomonation** [comment]
Looks like no cleanup is needed.
