### ISSUE TITLE
Task: Add Tracks events for eCommerce trial JITM

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#74548]
### Details

We need to add impression and CTA click events for the upgrade nudge/JITM we show in the left sidebar for eCommerce trials.

### Checklist

- [x] When we show the upgrade nudge in the left nav to a user, we should log an impression event
- [x] When a user clicks on the CTA, we should log a click event

### Related

#73003

**Comment by valterlorran** [comment]
This task is being addressed here: D105219-code
