### ISSUE TITLE
Navigation Block on Appleton Theme

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#74554]
### Quick summary

The block does not allow you to add a "page list" successfully to the navigation block on Appleton both publically and in the editor. 

### Steps to reproduce

* When switching to Appleton the "page list" in the nav block empties. None of the public pages appear in the page list in the navigation block
* Tried creating a new menu. The "Page list" item doesn't add
https://user-images.githubusercontent.com/13706336/225775389-0ddb9651-d22c-465c-99dd-6fa561653d3f.mp4
* Set up test site with Appleton theme. It only seems to add the page list if you add it to a menu with existing items
* But if you try to create a new menu and click + to add a page list it offers page templates and nothing related to the menu
https://user-images.githubusercontent.com/13706336/225775627-354f8616-7d69-4037-b68d-cf1b945f07ff.mp4
* The only solution I found was to go into the customizer, create a classic menu then assign it in the navigation block
* However, even setting the theme with a classic menu doesn't show the correct one publically 

https://user-images.githubusercontent.com/13706336/225775705-58cfd82a-798a-4f83-8c76-9dd08e2d74a7.mp4

* Tried changing the theme to blank canvas but the nav block then said it was broken. 
* I added a new navigation block and this time it worked so this seems to be related to Appleton

### What you expected to happen

The navigation block to suggest only navigation related items
The block to show what I entered into it publically on the site

### What actually happened

As per the steps above

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

6049162-zd

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Could Not Replicate**
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to replicate this issue on either Simple or AT sites.  In both environments, I'm able to add the Page List to a navigation block as expected.

**AT Example**

https://user-images.githubusercontent.com/27249804/228405473-12856ab3-feba-4fa6-b277-b5ad2613f22a.mp4


**Simple Example**

https://user-images.githubusercontent.com/27249804/228405468-0d4a0d9f-0f18-4cea-891e-51e8e69eaa18.mov


📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @rickmgithub Always make sure to exclude any user-specific information as well as internal-facing tools from your screenshots or details. (More on internal tools: pbawwo-18-p2 )
- [ ] Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.
