### ISSUE TITLE
"Billed annually" shows biyearly price as charged annually

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#74553]
### Quick summary

There is a small confusion when you're about to upgrade a site that's on a biyearly plan. It's not clear to the customer what is their current plan, how much will they get charged if they want to upgrade, and whether that upgrade is for one or more years.

Appears to be connected with the work in #74261 

Example from customer: 6047621-zen

### Steps to reproduce

1. Start with a site with a biyearly Premium plan ($156)
2. Go to Upgrades > Plans
3. Check 

### What you expected to happen

* To quickly understand what my current plan is (is it annual, biyearly?)
* To see the right print that says _per month, US$156 **billed every two years**_

### What actually happened

* We're showing _per month, US$156 billed **annually**_, which is incorrect
* There is no way for me to tell what is my current plan in case I want to either move to a higher plan (see #74165) or move from biyearly to annual
* To have a clear understanding of how much I should pay if I want to upgrade. If I have the biyearly Premium plan and wants to upgrade to biyearly Biz, the prices we show should follow that rather than saying _per month, CA$396 billed annually_ under the Business column.
* At checkout, things are as expected

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by mxhassani** [comment]
Another case here 41718661-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could Not Replicate
- Tested on AT: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Looks like the copy on the plans page has been updated for sites on multi-year plans.  They now say "every two years".  As such, the user can see `Your Plan` at the top of their plan column, and the correct billing cycle reflected below the price.

**Simple Example**
![Markup on 2023-03-28 at 18:35:14](https://user-images.githubusercontent.com/27249804/228403779-38592407-895b-4ea9-b003-cb77cf5b0bad.png)

📌 ACTIONS
- Closed as no longer relevant
