### ISSUE TITLE
LaunchPad - Update front-end site banner "My Home" button.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#74578]
For unlaunched sites, there is an extra banner on the front-end with a "My Home" button.

When the launchpad is active ('full') - we need to:

- [ ] Update the button copy to read "Next steps"
- [ ] Update it to lead directly to the launchpad and not My Home.

![Screenshot 2023-03-27 at 10 05 29 AM](https://user-images.githubusercontent.com/28742426/227963191-51111d48-01b8-4cbe-85f7-33b30401bda8.png)

**Comment by agrullon95** [comment]
"My home" button has been updated to "Next steps" (redirects to launchpad) : D106321-code
