### ISSUE TITLE
Provide option to hide paid plans on premium plans.

### ISSUE THREAD

**Issue by DavidSaladu** [Automattic/wp-calypso#74570]
### What

Provide an option to hide paid themes on premium plans.

### Why

Some users have requested it and there have been mentions of the confusion it brings. As over the fold only paid plans that require an upgrade are displayed, some customers thought that only free and paid plans exist now as they have to scroll down 4 rows before seeing a premium plan they can actually use.

### How

![image](https://user-images.githubusercontent.com/79575219/225907643-b935cde7-6027-42ec-950e-759ce8344d47.png)

**Comment by DavidSaladu** [comment]
Case 39228947-hc

**Comment by csabarakasz** [comment]
35362863-hc -> same issue here.

The user is confused and a little upset that even when they use the Premium filter option, the Paid themes are still very prominent.

**Comment by dsas** [comment]
This is the same request as https://github.com/Automattic/wp-calypso/issues/73986 so I'll close it, please feel free to update https://github.com/Automattic/wp-calypso/issues/73986
