### ISSUE TITLE
Newsletter onboarding: Update input focus

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#74583]
Focus state is different in _Let's get started_ and subsequent pages with inputs.
The first one seems to be the right one, at least considering the [Figma file](eqlepL7MHifK8Bgr1OWqLr-fi-5807%3A8019).

**Comment by escapemanuele** [comment]
Hello @crisbusquets, I think the Figma link may be broken.
[This](https://www.figma.com/file/eqlepL7MHifK8Bgr1OWqLr/Dotcom-System?node-id=5807%3A8019&t=NqcX9itFVeBnMQbA-11) should be the correct one.
