### ISSUE TITLE
Checkout: Pre-select the subscription's assigned payment method during renewals, rather than the first option

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#74585]
### Quick summary

When a subscription has an assigned payment method attached and you go to renew it, it seems like it would be useful to have that payment method be pre-selected by default on the checkout form?

Instead, it seems like we are selecting the first payment option in the list.  So for example, if you have credit card A and credit card B and credit card A is older, then switching the subscription from credit card B to credit card A and going to checkout will still show you credit card B as the pre-selected payment method, which is confusing.

This even happens when there is no existing credit card -- for example if you pay via PayPal and then go to renew, the pre-selected option in checkout will be to add a new credit card (rather than to use PayPal).

There are a couple possible complications with fixing this:
- Does this cause any issues with how we prefill the tax location during checkout?
- What happens if you're renewing more than one subscription at once and they have different assigned payment methods?  (In that edge case, though, it really seems fine whichever we pick.)

This came up in pbOQVh-3aL-p2, although it may not be the cause of the issue the user experienced there.

### Steps to reproduce

There are many ways to reproduce it, but here's one:
1. Add two credit cards to your account in a row.
2. Buy a subscription and use the first credit card from above when paying.
3. Go to the purchase management page for the subscription and confirm that the card you paid with is the one assigned.
4. Click "Renew now" to go to checkout.

### What you expected to happen

The first credit card (i.e. the one assigned to the subscription) would be selected by default on the checkout form.

### What actually happened

The second credit card (the newer one)  was selected instead.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by john-legg** [comment]
Hi @DavidRothstein 👋 I noticed that you removed the `[Pri] Low` label. We (KitKat/Forge) are trying to ensure that all bugs in the Calypso repo have priority labels so we can properly track and keep things prioritized. Whenever you have a moment, do you mind adding a priority label back? There's also `[Pri] Normal` and `[Pri] High` if you feel those are more appropriate. Thank you 😄

**Comment by DavidRothstein** [comment]
Our team will probably talk about this in a planning meeting tomorrow and decide on priority then.  We don't really tend to use those labels at all, but I'll make up a priority for now anyway, `[Pri] Normal` :smile:

**Comment by john-legg** [comment]
Sounds good. Thank you, David!

**Comment by michaeldcain** [comment]
From planning:

For manual renewals, we'd need the stored detail ref in the shopping-cart response (we might need to add this). Then we'd create a hook in Checkout to see if this is a renewal, if there's an ID, and if that ID exists in the stored details list. There could also be some side effects related to timing, cart makeup (if there is more than one product then grab the stored detail of the first), etc…

This is medium-effort, but a good enhancement. Placing it in the backlog for a future Checkout sprint.

**Comment by DavidRothstein** [comment]
It's possible this idea needs more refinement also; if they add a new payment method but didn't assign it to **all** subscriptions on their account, maybe we still want to have it selected by default when renewing those subscriptions sometimes (since it is after all the newest)?  There are a few different use cases here.

**Comment by JanaMW27** [comment]
>What happens if you're renewing more than one subscription at once and they have different assigned payment methods? (In that edge case, though, it really seems fine whichever we pick.)

I think for this case I would pre select the one they have used the last time they have gone through checkout, rather than randomly select one of the assigned payment methods. WDYT?

**Comment by sirbrillig** [comment]
Working on this in D161081-code and a calypso PR TBD
