### ISSUE TITLE
Editor: enhance Location Selector for more granular selection

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#7459]
Currently the location selector in the editor will allow you to use your current location, or to search for a location - which are both quite nice.  I like to use the location feature myself to document things I do out-of-doors, and I think a nice enhancement would be to embed a map ( shakes fist at Google API rate limiting ), and allow for specifying a location by clicking on said map.

Alternatively, allowing entry of Lat/Long coordinates would be a good in-between.

**Comment by popthestack** [comment]
Hey! I've created a branch that implements this desired feature. I haven't yet opened a pull request as I'm hoping for a bit of feedback first, but here's the link to the diff:

https://github.com/Automattic/wp-calypso/compare/master...popthestack:update/post-editor/7459-enhanced-location-selector

Here's a gif of it in action:

![google-map-enhanced-location](https://user-images.githubusercontent.com/136891/33039835-5e1c52d8-ce07-11e7-90c0-dd19f3c1c5fe.gif)

I'd love to hear what anyone has to think.

One thing I'm not sure about is how to handle the API key. Anyone running it locally would have to use their own, as putting an API key directly in the source is a bad idea. I'm thinking the build process for the official Calypso release would need to include an Automattic API key, but I don't know how that would be handled.

**Comment by alisterscott** [comment]
Keeping this open as it's being looked at in #20026 

#bug-scrub #pre-gutenburg-bug-purge
