### ISSUE TITLE
Reader: replace video embeds with a static image in the stream

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#746]
Raised by @blowery 

`iframe` elements are pretty intensive, both in CPU and memory usage. Investigate how to include a thumbnail for popular embed sources, like YouTube. 

YouTube:
http://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api

Vimeo:
http://stackoverflow.com/questions/1361149/get-img-thumbnails-from-vimeo
https://developer.vimeo.com/apis/simple#video-request

**Comment by designsimply** [comment]
Example of a missing Facebook video embed that looks odd:

![screen shot 2016-03-30 at wed mar 30 3 05 51 pm](https://cloud.githubusercontent.com/assets/1119271/14158814/94fc9854-f68f-11e5-9d39-10411adb129d.png)

Full post view: https://wordpress.com/read/feeds/37149996/posts/979366024
The post: http://singletrackworld.com/2016/03/video-corner-like-fabien/
The video: https://www.facebook.com/canyon/videos/1125874930779191/?pnref=story

**Comment by blowery** [comment]
@designsimply can you give #4421 a shot? Should fix the facebook video (and twitter embeds)

**Comment by blowery** [comment]
fixed with the refresh

**Comment by designsimply** [comment]
Re-tested to confirm the fix, and the video from the test post above is showing up now.

![screen shot 2017-04-10 at 15 10 12](https://cloud.githubusercontent.com/assets/1119271/24882872/e4ab1a9a-1dff-11e7-8510-02a73f6c7c9c.png)
<sup>Seen at https://wordpress.com/read/feeds/37149996/posts/979366024 using Firefox 52.0.2 on Mac OS X 10.12.4.</sup>
