### ISSUE TITLE
Components: Site Dropdown scroll issue overlap

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#7460]
When going to `/me/account` today and testing, I noticed some awkward overlapping in the sites dropdown component when scrolling.

![screen shot 2016-08-14 at 8 44 36 pm](https://cloud.githubusercontent.com/assets/1126811/17653791/2962bb54-6260-11e6-8a39-aae44263036e.png)

On Mac and Chrome Version 52.0.2743.116 (64-bit)

**Comment by lancewillett** [comment]
I couldn't repeat this — feel free to re-open if you see it again.
