### ISSUE TITLE
Plans: formatCurrency should be used in a couple places

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#74605]
### Quick summary

The new 2023 plans grid doesn't use `formatCurrency` in the grid header billing info section, this leads to conflicting currency symbol positioning:

![image](https://user-images.githubusercontent.com/16580129/226078489-f5d808ca-2597-4bb0-8e56-83339ec6a239.png)

This can be resolved by using `formatCurrency` rather than `getCurrencyObject`. The latter is useful when you wish to construct a price from its constituent parts and need a bit more control, but that doesn't really appear to be the case in the [code](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plan-features-2023-grid/billing-timeframe.jsx#L25). Using `formatCurrency` will manage the symbol placement for you.

**Resolved:**
<img width="603" alt="image" src="https://user-images.githubusercontent.com/16580129/226078437-197b5b29-f986-4bd9-bccc-ceb2b16f58a7.png">

An additional issue (though similar) is that it appears we hardcode the `US$25,000` text for Enterprise plans. This falls into the sticky issue of using 'US' for currencies in the "US", which is an issue we tried to steer away from.

We can do this dynamically by using `formatCurrency` here as well, since `formatCurrency` automatically checks if the customer is in the US and adds/removes the `US$` in favor of its alternate `$`. This can be useful since it allows US customers to see a plain dollar sign, but, doesn't confuse other locales that use a $ for their currency, such as Argentinian Pesos.

**formatCurrency in action from the USA:**
![image](https://user-images.githubusercontent.com/16580129/226079382-b73b10c2-5143-4bd2-a02e-295bac556756.png)

**formatCurrency in action from Argentina:**
![image](https://user-images.githubusercontent.com/16580129/226079029-5312b79a-bce6-4ed1-abdf-01a0c2f81945.png)

### Steps to reproduce

1. Go to /me and set your interface language to `fr-CA`
2. Go to the Plans page
3. Observe the incorrect formatting, in `fr-CA` the symbol should be right aligned, yet in the billing heading info section it is still left aligned

### What you expected to happen

I expected to see the symbol align left or right depending on the locale that is set, but at this time those specified prices only show as left aligned regardless of locale.

I also expect to not see the `US$` symbol while in the USA, you may need to use a VPN to test this on your own.

### What actually happened

Symbol positioning was not implemented based on locale.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by sirbrillig** [comment]
The link above to the use of `getCurrencyObject` doesn't seem to work anymore so I went and found a permalink that I think is correct: 

https://github.com/Automattic/wp-calypso/blob/3c68e088d6be1530634eecf390f94eb63897f8a0/client/my-sites/plan-features-2023-grid/billing-timeframe.tsx#L51-L55

A few other places that have this issue:

https://github.com/Automattic/wp-calypso/blob/ce42ebba42b76d7dba42e940ce6741ceadb767e8/client/my-sites/plan-features-comparison/header.jsx#L75-L76

https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/client/my-sites/plan-interval-discount/index.js#L41

**Comment by sirbrillig** [comment]
I keep trying to assign this to @Automattic/martech-autobots but Github won't let me so I'll just ping y'all.

**Comment by jjchrisdiehl** [comment]
Splitting this into two PRs to avoid issues with string translations

- [x] Changes to the billing info heading 

https://github.com/Automattic/wp-calypso/pull/74683

- [x] Changes to the hardcoded Enterprise figure

https://github.com/Automattic/wp-calypso/pull/74747

**Comment by kavyagokul** [comment]
📌 ACTIONS
- Looks already in progress, so moving out of 'Triage needed'
