### ISSUE TITLE
Site Assembler - Restyling menu items in the category list screen for consistency with the main screen

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#74622]
Related #74621 #74157
Figma 7l53h5fxAUNjVRBQ82YFwn-fi-2322-60205

### Description

We want to use the same look in the category list as on the main screen.

![Image](https://user-images.githubusercontent.com/1881481/226250624-97666d95-6539-4fa9-9cd8-016b454c6ccd.png)

Notice how the > icons are the same, the text styles are the same, and the colors are the same. 

The menu items in the category list will use the same hover and active effects as in the main screen.

![Image](https://user-images.githubusercontent.com/1881481/226250673-485e078e-cb46-400f-b991-49d4931a87cb.png)

**Comment by autumnfjeld** [comment]
Just noting that the Figma files need to be updated with latest copy and sidenav order p1679292113721759/1678352637.548059-slack-CRWCHQGUB
