### ISSUE TITLE
Site Assembler - Restyling menu items and active/hover effects in the main screen

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#74621]
Related https://github.com/Automattic/wp-calypso/pull/74157 https://github.com/Automattic/wp-calypso/pull/72144
Figma 7l53h5fxAUNjVRBQ82YFwn-fi-2322%3A60205

### Description

The sidebar revamp introduced a list of menu items on the "main" screen with separators:
|Initial|Hover|Focus|
|---|---|---|
|<img width="341" alt="Screenshot 2566-03-20 at 16 18 17" src="https://user-images.githubusercontent.com/1881481/226296562-a34cbef5-fc6f-4393-bba9-d54539fe0962.png">|<img width="335" alt="Screenshot 2566-03-20 at 16 16 57" src="https://user-images.githubusercontent.com/1881481/226296203-e6c0117b-66a8-4dba-869e-24fb9dae0867.png">|<img width="338" alt="Screenshot 2566-03-20 at 16 17 21" src="https://user-images.githubusercontent.com/1881481/226296318-3fa4b4bc-02fe-4364-9a32-e4c36c216cdc.png">

We want to remove the separators in this new design iteration and add new hover and active effects. 

![Image](https://user-images.githubusercontent.com/1881481/226515795-13ebd416-08f6-4e3e-8264-6494ab649d6a.png)

This look will be reused for consistency in the category list in a follow-up issue.

**Comment by autumnfjeld** [comment]
Note that copy is not correct in these screenshots.    See https://github.com/Automattic/wp-calypso/pull/74245

**Comment by autumnfjeld** [comment]
@miguel I think "Features" is supposed to be "Featured" . Correct?
<img width="340" alt="image" src="https://user-images.githubusercontent.com/5665959/226259995-a140047f-9e4c-47ce-89be-23447e954869.png">

I think it is a mistake from Dave's Figma?   And I guess right now we don't have a Featured category anyway....that will come later.
