### ISSUE TITLE
Site Assembler - Accessibility - Restyle focus state for consistency

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#74633]
Related to https://github.com/Automattic/wp-calypso/issues/74622 
[Accessibility utilities in Calypso](https://wpcalypso.wordpress.com/devdocs/docs/accessibility.md#utilities-in-calypso)
CSS pseudo-class [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)

### Description

The styles for the focus state on buttons are not consistent across the UI, and the outline border is cut off in some cases:

**Cut off cases**

![Image](https://user-images.githubusercontent.com/1881481/226317127-bbdcd2e8-8fb5-4ca1-b2a8-b0520840ed99.png)

![Image](https://user-images.githubusercontent.com/1881481/226317143-024efe65-79ef-4b46-8b44-914ef6fc0196.png)

**Non-consistency cases** 

![Image](https://user-images.githubusercontent.com/1881481/226317462-7a1942ca-d8e4-4c80-873b-82c954e2e35c.png)

![Image](https://user-images.githubusercontent.com/1881481/226317506-b64d29d6-ec14-48ea-86cb-f61c4e4a4d75.png)

### Expected result

All buttons should use this style:

```
    box-shadow: 0 0 0 2px var(--color-primary-light);
    outline: 0;
```

The new category list should also use these styles for the focus state. https://github.com/Automattic/wp-calypso/issues/74622 

**Cases looking good**

![Image](https://user-images.githubusercontent.com/1881481/226317838-07d00de1-c2dd-4f47-8e21-9fba602c5af6.png)

![Image](https://user-images.githubusercontent.com/1881481/226317783-7c76dcdf-2228-4891-b0cf-ec10fc347968.png)

![Image](https://user-images.githubusercontent.com/1881481/226317941-4d6bad99-41ee-4329-aaae-9065e5810304.png)

**Comment by okmttdhr** [comment]
![badge](https://img.shields.io/badge/review-ask-blue.svg)
Do we have a consistent focus style across Calypso? Having the style across Calypso rather than just the Site Assembler would be better.

**Comment by miksansegundo** [comment]
@okmttdhr I see in the [Calypso UI Components](https://wpcalypso.wordpress.com/devdocs/design), that the focus style is inconsistent for all components. 

Have a look at them and let me know what you think. I think the blue border with `box-shadow: 0 0 0 2px var(--color-primary-light);` would look consistent in the assembler.

**Comment by arthur791004** [comment]
> Have a look at them and let me know what you think. I think the blue border with box-shadow: 0 0 0 2px var(--color-primary-light); would look consistent in the assembler.

That makes sense to me 👍

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/74754 and https://github.com/Automattic/wp-calypso/pull/76006
