### ISSUE TITLE
Plans 2023: Enable the 1yr/2yr toggle when on an annual/biennial plan

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#74636]
As of merging the biennial toggle in https://github.com/Automattic/wp-calypso/pull/74206:

> Visiting /plans, the 1y/2y toggle is missing when I'm on an annual plan. Currently it is hide because it's problematic to downgrade from an annual term to a monthly one. Now that we are showing a longer term option, it makes sense to show the toggle . It would also open up the question regarding what we want to show for the monthly plan owner, though. We can discuss that further separately. 

_Originally posted by @southp in https://github.com/Automattic/wp-calypso/issues/74206#issuecomment-1475758211_

**Comment by chriskmnds** [comment]
> It would also open up the question regarding what we want to show for the monthly plan owner, though. We can discuss that further separately.

Hey @southp - let's clarify this. Do we need to show something else for monthly plan owners?

**Comment by chriskmnds** [comment]
This is being addressed in https://github.com/Automattic/wp-calypso/pull/74778

**Comment by southp** [comment]
> Hey @southp - let's clarify this. Do we need to show something else for monthly plan owners?

No, let's not change what they see. We can revisit this decision later if the A/B test tells us that we should go all-in to the 1y/2y toggle :)
