### ISSUE TITLE
Reader: Remove unnecessary comment hiding under "Conversations" section

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#74645]
## Description

A user reported that comments were being needlessly hidden within the Reader "Conversations" section. Here is the screenshot they shared:

![image](https://user-images.githubusercontent.com/5634774/226350417-72f2546b-0556-467a-847d-9afe310c28c0.png)

### Expected

Newer comments and comments without too much of a thread should just be shown by default.

### Actual

Many comment threads are truncated by default, even when the comment thread is shallow, or the comment is new.

### Testing Instructions

- Go to https://wordpress.com/read/conversations
- If you don't see posts with comments truncated, try adding https://philosophyandfiction.com to your reader feed

**Comment by hngdny** [comment]
5990448-zd-woothemes

**Comment by eoigal** [comment]
Should be fixed with https://github.com/Automattic/wp-calypso/pull/75187
