### ISSUE TITLE
LaunchPad in general onboarding - remove "WordPress.com" text by icon

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#74650]
For general onboarding Launchpad flows (`write` and `build`) we want to remove the "WordPress.com" text in the upper left of the launchpad and only have the logo.

![Screenshot 2023-03-20 at 10 15 33 AM](https://user-images.githubusercontent.com/28742426/226367231-7e9e58bb-54ac-419a-9a5a-b7583d03e4c5.png)

p2 context - pdqkMK-TC-p2 / p9Jlb4-6AL-p2#comment-7147

**Comment by agrullon95** [comment]
Changes merged in: #74719
