### ISSUE TITLE
Launchpad: Large displays should expand the height of the previewer

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#74651]
For very large displays, the Launchpad previewer should also expand vertically, taking the viewport height it needs. This example is 2560 x 1920px

![Image](https://user-images.githubusercontent.com/7931304/226368054-763a9b18-3ca6-4c0c-8632-0b927b0ca1da.png)

**Comment by agrullon95** [comment]
Changes to expand the height of the site preview have been merged: #75129
