### ISSUE TITLE
Reader: show "no results found" message if Search returns no results

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#7468]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/read/search?q=thisdoesntexist

#### What I expected

A message showing "No results found" and some calls to action.

![screenshot-2016-07-19-15-42-14](https://cloud.githubusercontent.com/assets/17325/17665183/895ca256-62f9-11e6-9aaf-8fb1e4e0ddd0.png)

#### What happened instead

<img width="789" alt="screen shot 2016-08-15 at 15 04 23" src="https://cloud.githubusercontent.com/assets/17325/17665186/9434b83a-62f9-11e6-9a2a-35832f4a6745.png">

**Comment by fraying** [comment]
Confirmed. Weird, I thought we had this one.

**Comment by bluefuton** [comment]
I think we did have it :) A regression I reckon...

**Comment by bluefuton** [comment]
This was a regression caused by adding search to Cold Start. We don't want to show the `blankContent' intro card there.
