### ISSUE TITLE
Jetpack Cloud: The sidebar sites list shows "Loading sites" even if user don't have any sites

### ISSUE THREAD

**Issue by vitozev** [Automattic/wp-calypso#74693]
### Summary

When you visit cloud.jetpack.com (either as an agency or regular user) and you don't have any sites, the sidebar will still show "Loading sites...", which isn't expected.

### Steps to reproduce
- Create a new WPCOM account
- Access cloud.jetpack.com without any Jetpack sites connected to your account
- Verify that the sidebar says "Loading sites"

### What you expected to happen

If I don't have any sites, I'd expect to see "No sites" instead of loading indicator.

### What actually happened

The "Loading sites..." is shown.

![Image](https://user-images.githubusercontent.com/1749918/226543349-83dd97b7-9bc0-4cd4-902e-af4cce222980.png)

**Comment by jkguidaven** [comment]
@vitozev I followed the test instruction and created a WPCOM account. when accessing cloud.jetpack.com. I get this screen



![Image](https://user-images.githubusercontent.com/56598660/230904950-6c2db632-35b5-410e-85ee-77d2597d33c4.png)

How can actually bypass this screen so I can reproduce the issue? 🤔

**Comment by vitozev** [comment]
@jkguidaven, that's interesting! I'm curious if that would be something related to agency partners in that case. Could you try to signup as an agency using the self-serve form here: https://cloud.jetpack.com/agency/signup and see if you can reproduce it?

**Comment by jkguidaven** [comment]
@vitozev Yes, I can reproduce it now with the agency user. 👍
