### ISSUE TITLE
Reader: embiggen videos in the single-post view

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#747]
Steps to reproduce:
1. Go to https://wordpress.com/
2. Find any post that has embedded videos
3. Click on the post title to open the single-post view in the Reader

<strong>Result:</strong> embedded videos are too small, especially VideoPress.

Compare:
- https://design5279.wordpress.com/2015/07/10/videos/
- https://wordpress.com/read/post/id/5276229/8772

<img src="https://cloud.githubusercontent.com/assets/1119271/8623123/7a3f2534-26fd-11e5-9867-4dcd9a14db0e.png" width="49%" /> <img src="https://cloud.githubusercontent.com/assets/1119271/8623124/7a4182d4-26fd-11e5-9bc8-abf675c156e0.png" width= "49%" />
<sup>Tested using Chrome 43.0.2357.132 on Mac OS X 10.10.4</sup>

**Comment by fraying** [comment]
@designsimply Is this still an issue? (I can't view https://wordpress.com/read/post/id/5276229/8772 anymore.)

**Comment by designsimply** [comment]
The VideoPress embed from that post still looks noticeably smaller to me in Reader, however, I also found that only happens when using the shortcode method to embed a VideoPress, i.e. `[wpvideo 4qvny630]`, so it may be fine as is.

![screen shot 2017-05-04 at thu may 4 9 02 14 am](https://cloud.githubusercontent.com/assets/1119271/25710109/77590356-30a8-11e7-8ca1-93ecf398c2c0.png)
<sup>Seen at https://design5279.wordpress.com/2017/05/05/video-test-3/ and https://wordpress.com/read/feeds/42873943/posts/1445920881 using Firefox 53.0 on Mac OS X 10.12.4 unproxied.</sup>

Here is a full screen side-by-side comparison or the same post on the site and in Reader:

![screen shot 2017-05-04 at thu may 4 9 10 08 am](https://cloud.githubusercontent.com/assets/1119271/25710470/92d26e50-30a9-11e7-8a27-b09d5af5396c.png)
<sup>Seen at https://design5279.wordpress.com/2017/05/05/video-test-3/ and https://wordpress.com/read/feeds/42873943/posts/1445920881 using Firefox 53.0 on Mac OS X 10.12.4 unproxied.</sup>

Aside: noticed a few other things while testing this: old Reader urls lead to a blank page with no left sidebar and [Hulu embeds](https://en.support.wordpress.com/videos/hulu/) don't seem to work either on the site or in Reader. I've filed separate issues for each.

**Comment by fraying** [comment]
Thanks, @designsimply!

Pinging @jancavan on the size discrepancy between different video embed methods.
