### ISSUE TITLE
Fix production not loading the Calypso subscriptions management properly.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#74708]
Also, need to investigate the wordpress.com/subscriptions redirection issue.
- going to wordpress.com/subscriptions?flags=subscription-management is redirecting to My Home
- going to wordpress.com/subscriptions/settings?flags=subscription-management is redirecting to some draft landpack page (but why?)

**Comment by ivan-ottinger** [comment]
I think that as a first step we could try to remove the private Landpack page that lives on the same `/subscriptions` URL: 2f889-pb (I believe this is the one).

I cannot edit this page myself for some reason:

```
data: {status: 403}
message: "User cannot access this restricted blog."
```

~~Looks like if the page is private, it needs to be edited by the author; although that's odd.~~

Ok, it is not about that specific page: I cannot edit any Landpack page at the moment for some reason.

**Comment by ivan-ottinger** [comment]
Alright, I managed to edit the page and updated its URL to `/xsubscriptions`. Now when I navigate to either of the URLs mentioned in the description of this issue, I get to the "Uh oh. Page not found." page.

Btw, the change that allowed me to edit Landpack pages again was to make sure the public-api isn't sandboxed.

**Comment by yansern** [comment]
Turns out the `/subscriptions` redirection rule redirects to [wordpress.com](http://wordpress.com/) which leads logged-in user into Calypso. So there wasn't an entry created in what I think is on the nginx level, that redirects users to Calypso from the URL.

Eitherway I'm made a system requests here:
pMz3w-haX-p2

**Comment by yansern** [comment]
> as a first step we could try to remove the private Landpack page

I have now removed it. I think it's because the page was called "Subscriptions" and it actually uses the `subscriptions` permalink. The redirection rule on Safe Redirect Manager actually doesn't match all the characters that comes after it, so it redirected back to this page. Mystery solved. :)

**Comment by yansern** [comment]
This is now pointing to Calypso. pMz3w-haX-p2
