### ISSUE TITLE
Post title heading size not changing edited from block toolbar

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#74704]
### Quick summary

The Post Title block doesn’t change the heading from the block toolbar.

### Steps to reproduce

1. Enable a theme compatible with the Site Editor Blockbase themes like Zoologist, Geologist, Quadrat, Arbutus but also some others like Stewart, Skivers, Bibimbap
2. Through the Site Editor, edit the Page template;
3. Click on the Post Title block, and through the Block toolbar change the Heading to h2, h3,h4…h6;
4. It doesn’t apply the change and keep’s it on H1;

*It does work on some themes like Adventurer, Twenty twenty-three, Blank canvas

### What you expected to happen

Since it’s available on the Block toolbar, it should be changed accordingly to the user change;

### What actually happened

The H1 size is kept even showing a different Heading size.

![kooha-2023-03-17-20-33-03](https://user-images.githubusercontent.com/11535091/226585670-346548df-a8b2-4fd5-97b7-c644cc291d4d.gif)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

zen-6035420

Workaround
You can decrease its size using the Styles. It’s not clear if this is expected or not, but at least, a bit confusing!

Note: 
It was noticed that when changing the heading by the toolbar, it applies that class in the title: <h2 class="wp-block-post-title" ...> but in themes where the toolbar does not work, the heading element has an inline style that seems to override the change made via the toolbar!

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on P2: 
- Tested on Simple: **Replicated** (Zoologist)
- Tested on AT: **Replicated** (Stewart)
- Tested on Self-hosted: **Replicated** (Blockbase)
- Replicable on Core? **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Not only the Post Title block, but also the Site Title block behaves this way as well - not changing it's size when adjusting the H1 selection; and this happens across templates.

**Stewart Example (on AT site)**

Post Title block

https://user-images.githubusercontent.com/27249804/228636215-81ca08b1-685d-4404-a2f8-fc3f06abec8e.mp4

Site Title block & using the typography settings

https://user-images.githubusercontent.com/27249804/228636233-e5a61db2-b4e0-47e2-bc86-efc0c3bad886.mov

---

**Twenty Twenty-Three for Comparison (On Self-Hosted site)**

https://user-images.githubusercontent.com/27249804/228636203-ec985404-2c38-4c08-968d-f296c8fa9dc2.mov

📌 ACTIONS
- Assigned to Cylon

**Comment by jayseventwo** [comment]
This is also happening in the Blockbase Theme. I'll post there.

**Comment by jamiepalatnik** [comment]
Ran into this issue on a site with Munchies theme. User report: 38731318-hc

**Comment by radtechgh** [comment]
Zoologist theme. 42530560-hc

**Comment by annezazu** [comment]
In exploring this, it appears this is theme specific rather than related to the Site Editor. For example, I can replicate with Zoologist but not with OnyxPulse. 

Closing this out in favor of an issue in the Themes repo: https://github.com/Automattic/themes/issues/8046

Let me know if that's not the right move!
