### ISSUE TITLE
LaunchPad Celebration modal - redesign to harness more prominent upsell opportunity.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#74712]
We want to update the launchpad celebration launch modal to make upsells more prominent. Currently our "Choose a domain" link at the bottom is not very prominent and we would like to increase this since we may be removing upsell opportunities from earlier in the flow.

While the design is not 100% final on the copies, the layout and base idea seems to be solidified to start working on. And we can always update the copies later.

The modal can support 3 different copies based on the state of the site and plan:

- [x] user has no paid plan / custom domain
- [x] user has a paid plan but has not claimed their custom domain
- [x] user has a paid plan and custom domain set -> we upsell something else like Blaze.

Base version (user has no plan):
![Screenshot 2023-03-21 at 8 32 05 AM](https://user-images.githubusercontent.com/28742426/226606827-b7962d4f-1e23-460e-b761-d47e04c4fa99.png)

If users already purchased a plan but didn’t get the domain yet, we could adapt the upsell part:
![Screenshot 2023-03-21 at 8 33 04 AM](https://user-images.githubusercontent.com/28742426/226607058-4c1757b5-67b4-479e-a7e6-0bf87e5e0a34.png)

And if the user already has a paid domain + plan, the upsell part could display a different (but still relevant) feature:
![Screenshot 2023-03-21 at 8 34 14 AM](https://user-images.githubusercontent.com/28742426/226607273-6b095897-9273-466f-a6c1-99e70f7b35de.png)

some slack context - p1678883754247339-slack-CHN6J22MP

**Comment by jeyip** [comment]
I’m out from tomorrow until next week, so if someone could shepherd it, that’d be awesome. If folks are too busy though, no worries, I’ll pick it up next week.

### Next Steps:
- Decide what we want to upsell when the user already has a paid plan and a custom domain. We currently just have placeholder text when that condition is triggered.
- Address any feedback from @nuriapenya  or the design team
- Code review and Test the PR
- Bonus points — figure out if we can find cached data about the blog’s custom domains without making a new network request https://github.com/Automattic/wp-calypso/pull/74744/files#diff-b2a3bdf3b4cec65b339e0803b39186ea50d15861cfa347b97294688a3b89e58eR14-R19
