### ISSUE TITLE
`/subscriptions`: Count should not be displayed when 0

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74714]
## Relevant conversations
- inDLaEQV8jJ21O4WXawIsJ-fi-712:29014
- inDLaEQV8jJ21O4WXawIsJ-fi-1549:18447

**Comment by ivan-ottinger** [comment]
This shouldn't be an issue. When any of the counts is 0 (or before it is fetched), it shouldn't display in the tab already.


![Image](https://user-images.githubusercontent.com/25105483/226872751-5cf2ce62-2b51-4485-8d3d-1a3a2b716fd1.png)


Have you noticed a case when this is not true? 🤔

**Comment by yansern** [comment]
Looks like no work needed here.
