### ISSUE TITLE
Domains: DNS notice displayed for Jetpack site

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#7472]
@aduth Pinged me today after receiving an unusual notice for a Jetpack site.

![pasted_image_at_2016_08_15_08_31_am_720](https://cloud.githubusercontent.com/assets/1126811/17669357/0138b4da-62d3-11e6-8afe-83a7e4bb9382.png)

Notice the "DNS configuration required" notice. Also, notice the URL. When @aduth clicked the notice, he was taken to page that said he couldn't do anything.

When I looked into this, I saw some logic that is aimed at not showing the notice to Jetpack sites: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/components/domain-warnings/index.jsx#L96-L98

When I blamed the file, @umurkontaci seems to have done most of the work for that notice. Can you help us track down why this notice would have displayed @umurkontaci?

**Comment by aidvu** [comment]
https://github.com/Automattic/wp-calypso/pull/7471

**Comment by ebinnion** [comment]
I could not reproduce myself. So, let's close for now.
