### ISSUE TITLE
Plans 2023: Plan grid styling is not wrapping correctly

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#74749]
### Quick summary

The plan comparison table on `/plans/[your-site-url]` under Compare Plans has some styling issues where the text breaks outside of its bounding box for the left hand column headers.

![image](https://user-images.githubusercontent.com/16580129/226727760-55699a71-f2cf-404f-8498-9ce6baa740c3.png)

I'm not entirely sure why this is the case, but it looks like the table is using an svg for the borders which may be why the width of the header is wider than the apparent column.

### Steps to reproduce

* Go to `/plans/[your-site-url]`
* Click on Compare Plans at the bottom of the page
* Modify the header text in the left hand column to be longer, eventually it will overlap the column's right hand border

### What you expected to happen

I expected the text to simply wrap to the next line once the sentence was longer than the column width.

### What actually happened

The text continues beyond the column's border onto the next column.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I found this originally while looking at the interface in Spanish. While the columns look fine in English, once we translate these strings into other languages we may run into this issue since the amount of text needed in another language may exceed that of English.

**Comment by karenroldan** [comment]
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Low` to better reflect its status in the larger context of open bugs in this repo.

**Comment by davemart-in** [comment]
I just checked. It looks like the text now wraps. Closing this out.
