### ISSUE TITLE
Add support for Yubi key on 2FA for WordPress.com accounts

### ISSUE THREAD

**Issue by rakshitwesley** [Automattic/wp-calypso#74753]
### What

The user would like to have the option to add Yubi key as 2FA

### Why

They feel this is more secure way of protecting the account.

https://www.yubico.com/

**Comment by rakshitwesley** [comment]
They would like to be notified if this feature request is accepted.

6061544-zd-woothemes

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by ehti** [comment]
@rakshitwesley Security keys including Yubi keys are supported on WordPress.com for quite a few years now: https://wordpress.com/support/security/two-step-authentication/security-key-authentication/
