### ISSUE TITLE
Woo Express Performance: Unable to install plugins from Calypso

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#74765]
Cft: pdtkmj-1k4-p2#comment-2379

After purchase, user is unable to install plugins from Calypso. The call to `/plugins/install` returns `This user is not authorized to install_plugins on this blog.`.

Plugin settings could be modified and plugins could be deleted from the wp-admin.

Blog id: 216905564

The logstash entries can be found via the comment above.

**Comment by markbiek** [comment]
@daledupreez I wanted to raise a flag that I didn't get anywhere with this today since you'll be the first one online.

I had a ton of trouble trying to track down the code that's checking the user capabilities or what's calling it.

It seemed like it should be the `Jetpack_JSON_API_Endpoint` (thanks Andy!) here: fbhepr%2Skers%2Swrgcnpx%2Scebwrpgf%2Scyhtvaf%2Swrgcnpx%2Swfba%2Qraqcbvagf%2Swrgcnpx%2Spynff.wrgcnpx%2Qwfba%2Qncv%2Qraqcbvag.cuc%3Se%3Q1n7961pq%238-og 

But I added logging to that file for both staging and production jetpack on my sandbox and it didn't seem to get called.

**Comment by daledupreez** [comment]
We had a separate thread about this issue, and this specific endpoint gets called on the site itself, so you would not see it on your WordPress.com sandbox.

**Comment by markbiek** [comment]
For anyone else interested, the main separate thread is in p1679594394723529-slack-C0Q664T29.

**Comment by markbiek** [comment]
Myself and @andres-blanco dug into this and it looks like this was caused by a mismatch between WPCOM and wpcomsh.

The wpcomsh PR 1310 which contains all of the Performance plan features hadn't been deployed yet.

We've deployed that and will verify the issue is resolved once the change is fully launched.

**Comment by markbiek** [comment]
I've confirmed that this is functioning now that wpcomsh 3.10.1 has deployed.
