### ISSUE TITLE
Add external user support on the Reader API endpoint for getting list of subscribed sites.

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#74762]
The goal of this task is to bring support for fetching an external user's subscriptions to the Reader API endpoint.

## Acceptance Criteria

**✅ Changes the task covers**

When sending a POST request to `https://public-api.wordpress.com/rest/v1/read/following/mine` with a X-WP-SUBKEY Authorization header set, the endpoint will return the list of subscriptions with the same data shape as for an authorized user. Irrelevant fields will be `null`.

**❌ Changes this task does not cover**

Searching & filtering.

**Comment by mashikag** [comment]
Resolved by: D106264-code
