### ISSUE TITLE
FSE Themes: Navigation Block displays an error in the Site Editor when navigating to different sections

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#74790]
### Quick summary

The Navigation Block show the `This block has encountered an error and cannot be previewed` message when navigating to different areas of the Site Editor, like the new Navigation or the Template List. The behaviour is erratically (repeating the same steps can lead to different results) and, sometimes, the issue clears itself.

I was able to reproduce it on my site with a brand new menu using both Arbutus and Geologist, and I reproduce it on Geologist's demo site as well:

**Geologist Demo site**
<img width="1502" alt="CleanShot 2023-03-13 at 10 29 16@2x" src="https://user-images.githubusercontent.com/14153300/224676181-c9f63dcd-733c-4ed9-bcdf-1743afcbd6b2.png">

https://user-images.githubusercontent.com/14153300/224677609-68256a4d-1889-4686-8131-ac34ccbfada2.mp4

### Steps to reproduce

As mentioned above, the behaviour is erratic. The steps below are the most reliable I have found so far, but I've ran into the error message when navigating to different screens in the Site Editor.

1. On a site with a header with a Navigation Block, open the Site Editor
2. Navigate to the new dedicated "Navigation" screen

### What you expected to happen

Accessing different areas of the the site editor should not affect the behavior of the Navigation Block

### What actually happened

Navigating in the site editor affects how the Navigation Block is rendered in the editor.

### Browser

Google Chrome/Chromium

### Context

Customer report

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Possibly related https://github.com/Automattic/themes/issues/5337

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment]
- [ ] 6031710-zd-woothemes

**Comment by hngdny** [comment]
Another occurrence on Munchies theme – Simple site

40683631-hc

**Comment by kylemcph** [comment]
Another occurrence on Appleton theme – Simple site. The navigation block displays correctly when the editor first loads, but when we switch to another template is when we see the error message. 

41447147-hc

**Comment by getdave** [comment]
Please can folks reporting include Gutenberg Plugin (active/inactive + version) and the WP version? 🙇 Thank you.

**Comment by getdave** [comment]
I tested this on Dotcom with Geologist. Editor works correctly with a fresh site until you create a Navigation (remember initially you will have no Navigation and the block will generate a fallback for you. Only once you've added a menu item does it "save" the menu to a Custom Post called `wp_navigation`).

With a menu created and saved, when you toggle Browse mode and go to the Navigation section the block in the editor will crash.

Reproduction steps:

- Fresh WP.com site
- Activate Geologist
- Go to Site Editor.
- Click on Nav block and use editor to add a link to the block.
- Save the menu (using "Save" button top right).
- Now open the Browse Mode sidebar and click on `Navigation`.
- The block will crash in the editor.

The error is minified but it resolves to [this](https://reactjs.org/docs/error-decoder.html/?invariant=185):

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

This suggests there may be an underlying bug.

**Comment by getdave** [comment]
On further discussion with other Nav block contributors in Gutenberg Core we suspect [this bug may have been the culprit](https://github.com/WordPress/gutenberg/pull/48219).

It was due for inclusion in **Gutenberg 15.4** which is due for release _today_ (otherwise we would do a patch release now).

Once this lands on Dotcom we can see if this resolves the problem. Highly likely as 

- the bug manifests when adding a top level link
- the error is setState "Maximum update depth exceeded" which matches the fix in the PR

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Replicated**
- Replicable on Core? **Yes** - as @getdave noted, this may be an incoming fix: https://github.com/WordPress/gutenberg/pull/48219

📌 FINDINGS/SCREENSHOTS/VIDEO
- Thank you @getdave for the steps to replicate!  I was able to replicate following your steps exactly.

**Self-Hosted Example**

https://user-images.githubusercontent.com/27249804/226060309-034137c5-bede-486e-a9f9-39060843027c.mov

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Transferred to `wp-calypso` repo as this is reproducible across many themes
- Updated title - between the report and comments, this has been reported on Geologist, Arbutus, Munchies, & Appleton

**Comment by getdave** [comment]
See also https://github.com/WordPress/gutenberg/issues/49231

**Comment by liviopv** [comment]
I tested the steps @getdave [shared](https://github.com/Automattic/wp-calypso/issues/74790#issuecomment-1479925209) on a fresh simple site running 15.5 and I wasn't able to reproduce this. Closing.

cc @Addison-Stavlo since it's on Cylon's board.
