### ISSUE TITLE
Site Assembler - Categories - Tracks metrics

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#74827]
### What

Verify that all Tracks metrics work and consider adding more Track events.

### Why

In [Site Assembler - Add pattern categories](https://github.com/Automattic/wp-calypso/pull/74157/files) we pass new props to track:

- `pattern_category` in the event `calypso_signup_pattern_assembler_pattern_select_click`
- `pattern_categories` in the event `calypso_signup_pattern_assembler_pattern_select_done_click`

### How

- Verify the events and props with Tracks vigilante extension
- Document new events/props and funnels in Metrics - Site Assembler: PekYwv-WG-p2

**Comment by miksansegundo** [comment]
We are already tracking the categories in the following events:

When a pattern is added to the list we trigger the event `calypso_signup_pattern_assembler_pattern_select_click`


![Image](https://user-images.githubusercontent.com/1881481/227823611-b040306f-32cf-4472-babd-87008c85cb81.png)


When users click the `Save` button to close the `Add patterns` screen (the category list) we trigger the event `calypso_signup_pattern_assembler_pattern_select_done_click`


![Image](https://user-images.githubusercontent.com/1881481/227824411-ac35c3ab-6078-4897-95ab-feacd3d85dd9.png)

When users click `Continue` we trigger an event `calypso_signup_pattern_assembler_pattern_final_select` per each pattern in the list:


![Image](https://user-images.githubusercontent.com/1881481/227825178-a7ffaecd-6d5e-47e3-8016-7a5fb8f22848.png)

**Proposed changes**

 - [x] We could create a new event to track when a category is clicked, say `calypso_signup_pattern_assembler_category_click` with the prop `pattern_category`.


 - [x] We could also add the categories on the following event `calypso_signup_pattern_assembler_continue_click`, say in a new prop `pattern_categories` with the category slugs separated by comma.


@autumnfjeld I'll create a [PR](https://github.com/Automattic/wp-calypso/pull/74934) to add these proposed changes. Let me know if you have other ideas to improve the category tracking.

**Comment by autumnfjeld** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/5665959/228787394-724ba383-465c-47ce-b8a9-86c532c6ebce.png">


@miksansegundo Your proposals  are good  Thank. you!  Can you also validate and register the event and add descripition info?
<img width="759" alt="image" src="https://user-images.githubusercontent.com/5665959/228788760-30b9a512-5f74-4e5c-8ef1-3bf752353e01.png">

A couple other requests:


Can you also add prop `category_count` to [calypso_signup_pattern_assembler_continue_click](https://href.li/?https://mc.a8c.com/tracks/events/event.php?eventname=calypso_signup_pattern_assembler_continue_click)

Can you update the table in PekYwv-WG-p2 with new events & props & screenshots?

![image](https://user-images.githubusercontent.com/5665959/228787689-57d1a6f9-626d-4ee1-995a-49c27955fbca.png)
