### ISSUE TITLE
eCommerce Trial: Notify Mailchimp when a user upgrades from the free trial

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#74838]
Full discussion: p1679277261186519-slack-C4E0DVDB2

When a user upgrades from the free trial, we need to notify Mailchimp of the upgrade.

**Comment by markbiek** [comment]
@ilyasfoo FYI

**Comment by daledupreez** [comment]
Work on this is in D105921-code and Automattic/woocommerce.com#16468.

**Comment by daledupreez** [comment]
This was shipped to users in D105921-code and Automattic/woocommerce.com/pull/16468 on Monday.
