### ISSUE TITLE
Site Assembler - Show a larger pattern preview floating over the site preview

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#74833]
### What
Show a larger pattern preview floating over the site preview when hovering over a pattern in the list.

### Why
Because the pattern thumbnails are too small to see the details. 

![Image](https://user-images.githubusercontent.com/1881481/227188713-1c6305fc-109d-4c2a-a130-1eaff0538bca.png)

This feature makes less sense for header/footer pattern because we can easily switch them to preview them on the site preview.

![Image](https://user-images.githubusercontent.com/1881481/227188784-8b29c4c6-65d4-4389-b129-320b63312a31.png)

### How
- Using the `<PatternRenderer>` component. 
- We'll have to calculate the width & height based on the available viewport. 
- Consider updating the dimensions on a resize window event
 
![Image](https://user-images.githubusercontent.com/1881481/227188898-efd4a82e-cbc1-4fce-8eb4-47a5d84d3666.png)

**Comment by autumnfjeld** [comment]
Let us know if you have any design input on this @davewhitley .  :) 

These are @miksansegundo 's thoughts:
> I moved [Site Assembler - Show a larger pattern preview floating over the site preview](https://github.com/Automattic/wp-calypso/issues/74833) to the backlog because I think we have other priorities. The design we have is enough to start working on that feature.
I think it would be better to ask Dave to think about it and add more details to the issue. For instance, about how it should work based on the viewport size.

**Comment by arthur791004** [comment]
My only concern is the site editor doesn't have this feature and users might feel confused when they land on the site editor and want to insert a pattern.

**Comment by miksansegundo** [comment]
@lucasmendes-design I think we won't add this feature because the large preview will be always visible thanks to https://github.com/Automattic/wp-calypso/issues/75327 that is ready for dev.

**Comment by lucasmendes-design** [comment]
Thanks @miksansegundo ✌🏼

**Comment by taipeicoder** [comment]
Closing this as not planned.
