### ISSUE TITLE
Make devdocs layout wide or just for a single item

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7483]
When adding items to devdocs (be it Blocks or any other section), sometimes I need a wide layout (e.g. designing component for /plans). Ideally, I should be able to add a wide layout to just one specific component (`.docs__design-assets-group`). However, that's not possible due to the `padding` on `.design-assets` which is the parent for `.docs__design-assets-group`.

I propose to either make the whole devdocs layout wide or add the ability for a single devdocs item to be wide.

Screenshots of example Blocks component with and without wide layout:

![selection_027](https://cloud.githubusercontent.com/assets/4988512/17692687/629beddc-639b-11e6-8397-9f899e8e06a5.jpg)

![selection_030](https://cloud.githubusercontent.com/assets/4988512/17692711/7f6a4256-639b-11e6-8e3e-390a78f4fa8c.jpg)

cc @mtias @gwwar @aduth

**Comment by gwwar** [comment]
I think this makes sense if the block components are rendered by themselves on separate pages. Doing so would also limit the number of network requests fired from the blocks list page.
