### ISSUE TITLE
Unauthorized users should be redirected from `/subscriptions/settings` to `/email-subscriptions`

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#74849]
Unauthorized users that go to `wordpress.com/subscriptions/settings` are presented with this screen:

![Image](https://user-images.githubusercontent.com/3832570/227273333-770c7136-217c-4e97-8ff6-4e721e0b12db.png)

That screen is located in Calypso, with a `loading` spinning circle in an infinite loop.

The correct behavior is to redirect the unauthorized  to the landing page `wordpress.com/email-subscriptions` so they can ask for the logging URL and continue with the Subscriptions flow:

![Image](https://user-images.githubusercontent.com/3832570/227273700-ac7bd73a-4b41-4d84-8eba-009d8ec73a1a.png)

**Comment by yansern** [comment]
Superceded by https://github.com/Automattic/wp-calypso/issues/74886
