### ISSUE TITLE
Zaino theme live preview doesn't load

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#74855]
### Quick summary

In Calypso (Appearance ---> Themes) the live preview for the Zaino theme doesn't load. Instead, a white screen is shown:
![imagen](https://user-images.githubusercontent.com/4965723/227335135-4836097e-4d26-468c-926e-c455b3c28765.png)

A workaround is to visit the theme's demo site: https://zainodemo.wpcomstaging.com/

### Steps to reproduce

1. Go to Appearance ---> Themes.
2. Search for the Zaino theme and open the details.
3. Click on "Open Live Demo"

### What you expected to happen

The live demo should load inside the modal.

### What actually happened

A white rectangle appears inside the modal.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

Browser console shows a mixed block error:

`Blocked loading mixed active content "http://zainodemo.wpcomstaging.com/?demo=true&iframe=true&theme_preview=true&calypso_token=394d6f76-518d-4ef2-a5ff-ab8fa6346771"`

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
That `blocked loading mixed active content` error has also been seen on these issues:

- https://github.com/Automattic/wp-calypso/issues/57484
- https://github.com/Automattic/wp-calypso/issues/75577

Specifically, above the error noted in the OP is referencing `http://zainodemo...`, and not `https://zainodemo...`, and the iframe may not be redirecting to the correct protocol properly.  I think is a similar underlying problem across these issues. See https://github.com/Automattic/wp-calypso/issues/57484#issuecomment-962177751 and onward for more details.

**Comment by taipeicoder** [comment]
This has been fixed via D110041-code
