### ISSUE TITLE
`/subscriptions` routes should be only available to external users

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#74851]
The reskinned portal and the Subscription Manager settings page should only be available to external users. Logged-in users should be redirected to the reader.

**Comment by TimBroddin** [comment]
Fixed for the new portal in this PR: https://github.com/Automattic/wp-calypso/pull/74861
I'll take a look at the reskinned portal

**Comment by yansern** [comment]
> I'll take a look at the reskinned portal

I have a feeling there isn't anything to do there because the old V1 class handles it, but let me know. :)

**Comment by yansern** [comment]
Superceded by https://github.com/Automattic/wp-calypso/issues/74886.

**Comment by yansern** [comment]
> I have a feeling there isn't anything to do there because the old V1 class handles it, but let me know. :)

Just to confirm that unauthorized users are already redirected to landing page.
