### ISSUE TITLE
Site Assembler - Pattern Rendering Optimizations - Reduce images size in thumbs

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#74870]
### What

Reduce the image size in the thumb previews on the sidebar to `600px`. The sidebar is about `300px`, let's use x2 to support retina displays.

### Why

The image width is `1280px` now, which only makes sense for the large preview. 

![Image](https://user-images.githubusercontent.com/1881481/227424215-e95406ef-d224-4378-9700-8d6dd8937554.png)

See how big the images are: [header-mountains.jpeg](https://dotcompatterns.files.wordpress.com/2022/07/header-mountains.jpeg)

![Image](https://user-images.githubusercontent.com/1881481/227424274-c54c902b-9831-4fe2-beb1-5ee625910c46.png)

The image size impacts the loading and rendering time of the thumb previews. Patterns without images render much faster.

### How

Maybe our best option is adding the URL param `?w=600` to the images in the pattern thumbs. 

Other option is the `srcset` attribute so that the images will load with different dimension based on the viewport. For some reason, this param is not being used but anyways, I think that won't work for our use case because the viewport of the thumbnails is scaled down with CSS.

Also, the image `srcset` might not be a good idea because the size of the rendered HTML in the response of `/block-renderer/patterns` will increase dramatically for all patterns with images.

Here is a HTML example of an image with `srcset`:

```html
<figure class="wp-block-image alignfull size-large">
	<img decoding="async" loading="lazy" width="1200" height="800" data-attachment-id="9521" 
		data-permalink="https://dotcompatterns.wordpress.com/2022/09/22/cover-image-with-left-aligned-call-to-action/mountains_landscape/" 
		data-orig-file="https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg" 
		data-orig-size="1200,800" 
		data-comments-opened="0" 
		data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" 
		data-image-title="mountains_landscape" 
		data-image-description="" 
		data-image-caption="" 
		data-medium-file="https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg?w=300" 
		data-large-file="https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg?w=1024" 		
		src="https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg?w=1024" 
		alt="" 
		class="wp-image-9521" 
		srcset="https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg?w=1024 1024w, https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg?w=150 150w, https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg?w=300 300w, https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg?w=768 768w, https://dotcompatterns.files.wordpress.com/2023/02/mountains_landscape.jpg 1200w" 
		sizes="(max-width: 1024px) 100vw, 1024px">
</figure>
```

**Comment by okmttdhr** [comment]
>Maybe our best option is adding the URL param ?w=600 to the images in the pattern thumbs.

I agree with this opinion. 
Using `srcset` is too much for now, and we can consider it when we work on the mobile version of the Site Assembler.

> the size of the rendered HTML in the response of `/block-renderer/patterns` will increase dramatically for all patterns with images.

I have a question for my understanding! What do you mean by the size of the rendered HTML? 
Background: If you are referring to the `figure` and `img` in the sample code, I thought the browser rendering cost would be about the same as if there was one `img` there. I believe the problem at rendering time is, for example, if we are misusing the Data URL schema or if we include complex svg structure.
@miksansegundo

**Comment by okmttdhr** [comment]
I’m trying to implement to

- Add a parameter to the API ( `/block-renderer/patterns` ) to specify the image size in returned HTML.
- Request with `?image_size=small` and remove `?w=xxx` with JS from the client side when displaying the large preview.

pbxlJb-3GJ-p2
