### ISSUE TITLE
All login status based redirections should happen, in calypso server, before the subscription-manager entry point is loaded

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#74886]
## Related conversations
- https://github.com/Automattic/wp-calypso/pull/74733#discussion_r1147342355

**Comment by mashikag** [comment]
Hold off until the following PR is merged in: https://github.com/Automattic/wp-calypso/pull/74733

**Comment by yansern** [comment]
Just to add a bit more specific detail:
- Redirect unauthorized user (no-cookie, not-logged-in) to landing page `/email-subscriptions`.
- Logged-in users entering `/subscriptions` should be redirected to `/email-subscriptions`.
- Logged-in users entering `/subscriptions/settings` should be redirected to  `/email-subscriptions?option=settings`.
