### ISSUE TITLE
Woo Express Copy Updates: Plans page

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wp-calypso#74899]
Copy changes for mysite.wordpress.com/plans

Subtext under page title plans should read "Discover what's available on Woo Express"

![Image](https://user-images.githubusercontent.com/89872780/227570459-f73136a7-b2a0-4fa2-aa11-0cf813d01c2b.png)

The plan name should reflect "Performance" 

![Image](https://user-images.githubusercontent.com/89872780/227570191-9875bb20-0467-4da8-9dd8-35102c42a252.png)

The "General features" section should read as displayed in the screen shot/design 

![Image](https://user-images.githubusercontent.com/89872780/227570169-dd255b1a-99a6-44ec-ba69-4617fa66ae7f.png)

Note: @FlorianBru  since this page will display all of the available Woo Express plan, I suggest we change the title subtext to "Discover what's available on Woo Express."

**Comment by FlorianBru** [comment]
So regarding the subheading 'Discover what's available on Woo Express', Laura will take care of that on Monday.

@that-mike-bal, Regarding the plan name 'Performance' and also the 'General features', that's already part of the layout, or are you referring to something else here?

**Comment by daledupreez** [comment]
@markbiek and @nelsonec87, if we have cycles later today, this may be something worth picking up after we launch the Performance plan. Please feel free to add it to our board if we can get started on it today, otherwise we can work with the Ghidorah folks tomorrow to work out who can pick this up first.

**Comment by markbiek** [comment]
@Automattic/serenity is going to pick this update today.

**Comment by markbiek** [comment]
@Automattic/serenity is going to pick this update today.

**Comment by markbiek** [comment]
@that-mike-bal A couple of things I could use clarity on:

## Item 1
![image](https://user-images.githubusercontent.com/917632/228056358-2921c7eb-6755-489a-87a0-868c93af46ee.png)

Should the above copy be on just the plans page for sites already on Woo Express Performance or should it be changed on the Trial plans page as well?

## Item 2
![image](https://user-images.githubusercontent.com/917632/228056957-eb9744a5-9081-4fb4-8e32-41544586cf0e.png)

I'm also unsure what needs to change on the "General features" list. That copy appears to be the same as what you provided in that screenshot. The only difference is a slight change in the support copy for trial sites vs. upgraded sites (See #74789 for more details).
