### ISSUE TITLE
Woo Express Copy Updates - Checkout Confirmation

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wp-calypso#74900]
Changes to the screen users see after they complete their plan purchase from the free trial. 

Headline: Woo! Welcome to Woo Express
Subtext: Your purchase is complete and you're now on the **Performance plan**. Now it's time to take your store to the next level. What would you like to do next?

Update the options to include "Launch your store" ensure the layout and copy matches the design 

![Image](https://user-images.githubusercontent.com/89872780/227572261-f1fa1eb7-da54-49af-a08e-0175094b7b14.png)

Figma for reference: https://www.figma.com/file/lD0gTB4IqGsmSmsnjZNaP6/Free-Trial---E2E-Experience?node-id=2645-34362&t=BvDFYTBslrq85bv8-0

**Comment by nelsonec87** [comment]
![image](https://user-images.githubusercontent.com/3801502/230382664-aef15cf7-bb66-44d0-a954-de57554d1d95.png)

Fixed on https://github.com/Automattic/wp-calypso/pull/75034 and https://github.com/Automattic/wp-calypso/pull/75286
