### ISSUE TITLE
Stats: Add loading states for subscribers chart

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#74937]
The subscribers' chart we added as part of #74404 has no loading state and doesn't handle empty data sets properly.

As part of this task, add a loading indicator to the chart.
Because all of the other modules on the `Traffic` page have circular loading indicators use that one for consistency. Avoid copying and pasting the code. If a component doesn't exist (that would allow reusing the loader), create it. For styles, create a sass mixing allowing for easier sharing.

Because the redux store is not ready, simulate the loading state by extending `client/my-sites/stats/subscribers-section/index.jsx` with the following temporary code:
```
import { useEffect, useState } from 'react';

[...the rest of the file...]

export default function SubscribersSection() {
	const [ isLoading, setIsLoading ] = useState( true );
	const data = transformData( isLoading ? [] : getData() );
	useEffect( () => {
		setTimeout( () => setIsLoading( false ), 5000 );
	}, [ isLoading ] );

	// Determines what is shown in the tooltip on hover.
[...the rest of the file...]
```

Development tasks:
- [x] add a circular loading indicator to the subscribers' line chart (use the indicator from other components on the `Traffic` page)
- [x] (optional) create a component for the circular indicator to make the code DRY

**Comment by a8ck3n** [comment]
I think we can consider this done for now. We are currently using `StatsModulePlaceholder` so we don't need our own loading component. We can revisit as needed once we have initial designs.

cc: @grzegorz-cp
