### ISSUE TITLE
Task: Register Tracks events for eCommerce trial JITM nudge

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#74941]
### Details

As part of https://github.com/Automattic/wp-calypso/issues/74548 / D105219-code, we introduced two new Tracks events for the sidebar nudge we show in the left nav, `calypso_wpcom_jitm_ecommerce_trial_impression` and `calypso_wpcom_jitm_ecommerce_trial_cta_click`.

We need to ensure that both events are correctly registered in Tracks per this documentation: PCYsg-mUj-p2

### Checklist

- [x] Register `calypso_wpcom_jitm_ecommerce_trial_impression` event
- [x] Register `calypso_wpcom_jitm_ecommerce_trial_cta_click` event

### Related

#74548

**Comment by that-mike-bal** [comment]
I'm thinking this could be passed to Ghidora? Let me know what you think @daledupreez 

I'm kind of surprised there's no tracks event for that Jitm we could add a prop to already — did we check with he Jetpack team? I'm sure we've tracked this for upsells before, so I can try and hunt that down. 

Can we make this more usable for other teams in the future by making the event not plan specific and pick up the plan as a prop?

**Comment by sixhours** [comment]
@that-mike-bal The events are already in place and working, we implemented them in D105219-code. As a follow-up administrative task we need to follow the registration procedures outlined in the FG to make the events "legit" in the eyes of Automattic devs and data folks going forward. I'm working on that now!

**Comment by sixhours** [comment]
Registration PR for impression event: https://github.com/Automattic/tracks-events-registration/pull/1521

**Comment by sixhours** [comment]
Registration PR for CTA click event: https://github.com/Automattic/tracks-events-registration/pull/1522

**Comment by sixhours** [comment]
Both events have been registered and validated now!

**Comment by that-mike-bal** [comment]
You rock!
