### ISSUE TITLE
Assembler: provide visual space and subheadings to differentiate between Structure and Styles

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#74945]
# Description

See
* pbxlJb-3EX-p2
* pbxlJb-3EX-p2#comment-2454

This is not tied to a specific PT, can be done at any time.

![Frame 4736](https://user-images.githubusercontent.com/618551/229175619-4963d7cb-26f3-4846-812b-9b9895a5b402.png)

## Design Tasks
Figma link:  7l53h5fxAUNjVRBQ82YFwn-fi-2322%3A60205

Since Figma Tampermonkey isn't working, here's a link to the slack message with the figma link : p1680279755023999-slack-CRWCHQGUB

- [x] Provide Lego team with a Figma design
- [x] Please update this description with screenshot and Figma link @davewhitley 

## Dev Tasks
- [ ] Implement design

**Comment by davewhitley** [comment]
Please ping me if the Figma link is needed 👍

**Comment by autumnfjeld** [comment]
> Please ping me if the Figma link is needed 👍 

@davewhitley  Could you default to always including a Figma link (since  time zones mean we can't get a quick response)? thank you 😊

This is a good pattern to follow in the main issue description:
<img width="168" alt="image" src="https://user-images.githubusercontent.com/5665959/229681433-4e589828-bf81-4efe-8285-51aec7b29eac.png">


🤩

**Comment by autumnfjeld** [comment]
@davewhitley  This has out of date ordering and copy

<img width="308" alt="image" src="https://user-images.githubusercontent.com/5665959/229688213-3a3c3c91-dbd0-4d3d-a971-8f40c95ca29f.png">

Could you update it in the Figma file?  thank you.

**Comment by autumnfjeld** [comment]
Testing Figma link and I don't think it is working 7l53h5fxAUNjVRBQ82YFwn-fi-2540-60679

**Comment by miksansegundo** [comment]
After updating to the last version of [tampermonkey-highlighter](https://github.com/Automattic/tampermonkey-highlighter/raw/master/a8c-linker.user.js), this 7l53h5fxAUNjVRBQ82YFwn-fi-2540_60679 Figma link works for me.
