### ISSUE TITLE
Assembler: improving colors & fonts and style gating integration (aka Unlock this style modal)

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#74946]
# Description

![image](https://user-images.githubusercontent.com/5665959/227901140-5303b462-7898-45c6-a235-c51a8216fd4d.png)

We've been discussing how the copy & UX of the style gating "Unlock this style" modal doesn't fit with the Assembler context. 

**Recent discussions:**
*  @dsas says "you can fix it, go for it" 😄  p1679478751843249/1679394673.172269-slack-C048CUFRGFQ
*  Discussion in Lego p1679459482050959-slack-CRWCHQGUB
* @miksansegundo idea pbxlJb-3d0-p2#comment-2444
* p1679459482050959-slack-CRWCHQGU
* Colors & Fonts walkthrough: pbxlJb-3EX-p2

## Proposed solution
I've made a [quick FigJam](cWkuJQiObZafHS02lDmxs6-fi-0%3A1) to outline the solution.  Ideally we'd  like @davewhitley  to mock up the final design, but perhaps we can make due with my fabulous FigJam.  These updates are for the Assembler context only, the modal shouldn't change for other contexts unless stated in the Dev Tasks items below.

## Design Tasks
- [ ] Approve the FigJam ideas.  Ideally it would be great to get an updated Figma design (but might be hard with Dave being sick. 
- [ ] Get approval on copy from Pablo.  However if he doesn't have time to review copy by the time the dev work on this is done then,  we will ship this update.  We can incorporate any Pablo-copy-updates later.

## Dev Tasks & Acceptance Criteria

- [x] https://github.com/Automattic/wp-calypso/pull/75062
  - [x] Update copy in the modal (see the FigJam cWkuJQiObZafHS02lDmxs6-fi-1%3A212)
     - [x]  First sentence: dynamic text: You’ve selected a premium { font and color | font | color}.   OR with static text "You've selected a premium color or font."
     - [x] Last sentence "You can also continue with your selected colors and font and upgrade later."
  - [x] The title on the right side of the modal should be updated to "Included with your Premium plan" .  This change can be made for all instances of the modal.  
  - [x] Update button copy in the modal to [Upgrade later] and have it close the modal - it should not go to the editor.
  - [x] When the modal closes the button in the side nav should change to [Continue]
- [x] https://github.com/Automattic/wp-calypso/pull/75057
  - [x] If the user clicks [Upgrade plan] , the user should go to checkout -> finish/exit checkout -> return to Assembler with all their selections saved

### Other items under discussion (but not needed for this issue or shipping Colors & Fonts)
 - [ ] Add a "Reset" link or  "Reset fonts & colors" button 
 - [ ] If user clicks Continue without having seen the Colors or Fonts first, we could remind them to take a look at the styles before they continue to the editor.  (See the last sentence in Miguel's idea [comment](pbxlJb-3d0-p2#comment-2444))

@Automattic/lego

**Comment by arthur791004** [comment]
I guess we're able to close this issue since we have updated both experience and copy of the Global Styles Upsell Modal via https://github.com/Automattic/wp-calypso/pull/75062. We can continue to iterate the copy when we get the reviews from Pablo.
