### ISSUE TITLE
Woo Express Small: Refactor Atomic site software removal to use new data constant

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#74967]
The Atomic software removal-on-downgrade logic needs to be updated to use the new constant(s) and functions introduced in D105787-code, to ensure we're removing the correct software set from an Atomic site when a user downgrades from a Woo Express plan.

The primary affected files are here:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Qi2.cuc%3Se%3Qn74s560p-og
fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sjbn%2Sjbn%2Qqrnpgvingr%2Qcebqhpg.cuc%3Se%3Q5n52232q-og

We can use D103751-code as a reference for how to accomplish this, and expected behavior for testing instructions.

**Comment by valterlorran** [comment]
This issue is being addressed here: D106404-code

**Comment by valterlorran** [comment]
Closed by D106404-code
