### ISSUE TITLE
Add external user support on the Reader API for updating site subscriptions

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#74964]
The goal of this task is to bring support for updating an external user's site subscriptions to the Reader API endpoints:

- POST /read/sites/%s/post_email_subscriptions/new
- POST /read/sites/%s/post_email_subscriptions/update
- POST /read/sites/%s/post_email_subscriptions/delete

Acceptance Criteria
✅ Changes the task covers

When setting an `X-WPSUBKEY` Authorization header, an external user is able to:

- Update site subscription settings 
- Subscribe to blogs
- Unsubscribe from blogs

This issue may seem like 3 issues, but the changes needed here seem very minimal.

**Comment by mashikag** [comment]
Resolved by: D106368-code
