### ISSUE TITLE
LaunchPad - "choose a domain" step - ensure exiting checkout leads back to launchpad.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#74962]
related slack p1679688496675049-slack-CHN6J22MP

for the "Choose a domain" task flow of launchpad, if the user exits checkout they are redirected into calypso.

we need to:

- [ ] ensure exiting checkout here directs users back to the launchpad.

![image](https://user-images.githubusercontent.com/28742426/227965357-7f58647c-27bd-459d-bdfa-761322c3a1be.png)

**Comment by agrullon95** [comment]
Changes for this task merged in #74994
