### ISSUE TITLE
Woo Express Small: Update helper functions to add check for Essential plan

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#74972]
We need to add conditions to check for the new Essential plan once it has a `WPCOM_Feature` so the correct set of software can be installed, removed on downgrade, and sent to WooCommerce.com.

Functions to modify: 
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sjbn%2Qrpbzzrepr%2Qfbsgjner.cuc%3Se%3Qrqq67ps2%23308-og
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sjbn%2Qrpbzzrepr%2Qfbsgjner.cuc%3Se%3Qrqq67ps2%23290-og

Example of implementation in original diff: D103751-code

**Comment by sixhours** [comment]
Started this in D106433-code but I think we need to wait until we have corresponding updates to WPCOM_Features for the small plan.

This is waiting on #73958 to ship, then it will be ready for testing.

**Comment by sixhours** [comment]
Now being worked on in D106830-code, we ran into some issues in testing that require additional helper functions.

**Comment by daledupreez** [comment]
Marking this issue as resolved, as we deployed D106830-code earlier today.
