### ISSUE TITLE
Subscription Management: Add external user support on API endpoint for confirming site subscription.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#74979]

**Comment by yansern** [comment]
Just like to add that there is no need to prioritize this for the sprint of Week 13 & 14 as there is no feature for Following / Refollow.

**Comment by mashikag** [comment]
Was this task not done as part of implementing the Pending page?
cc @JuanLucha

**Comment by yansern** [comment]
API endpoint for confirming comment subscription - D108147-code
API endpoint for confirming site subscription - D107895-code
