### ISSUE TITLE
`/subscriptions/sites`: Create the unfollow button

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#74987]
## Requirements

- [x] Unfollow button component should be created with a layout that matches the design specifications on Figma.
- [x] Button should be integrated with the Unfollow endpoint, so that when a user clicks on it, the site associated with that row should be unfollowed.
- [x] Unfollow button should be added to the Subscription Settings dropdown, it should appear as the last item when the dropdown is opened.

## Design
![Image](https://user-images.githubusercontent.com/3113712/228053042-cce562b6-02fe-4377-a45b-bb1a5a26d59c.png)
inDLaEQV8jJ21O4WXawIsJ-fi-712-15534

**Comment by yansern** [comment]
(re-opened because I realized the integration isn't done yet)

**Comment by phcp** [comment]
@yansern The integration is together with the mutation task https://github.com/Automattic/wp-calypso/pull/75165

**Comment by phcp** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/75165
