### ISSUE TITLE
Plans Grid: Domains Only: Discount text looks borked on smaller viewports

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#74986]
### Quick summary

On a smaller viewport, the discount text nearly touches the border, which seems off.

<img width="1305" alt="Screenshot 2023-03-27 at 2 34 20 PM" src="https://user-images.githubusercontent.com/1126811/228047832-8008f29c-572e-4229-a28e-3a1f08dc9cc9.png">

### Steps to reproduce

1. Go to leandomainsearch.com
2. Search for a domain
3. Select domain
4. Start new site on WordPress.com
5. Change viewport size to find issue

### What you expected to happen

For there to be padding within the column and the discount text to respect that.

### What actually happened

Discount text touched border.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Noticed in Microsoft Edge Version 111.0.1661.51  on a Mac.

**Comment by ebinnion** [comment]
@dzver - When do we think that we'll get to updating the pricing grid to take over the various flows? If soon, then perhaps we can roll this issue into that work?

**Comment by dzver** [comment]
I'm not sure about the exact time to replace the Pricing Grid and I'd normally suggest just waiting for this grid to be replaced with the new one but this should be such a small fix. CC @southp

**Comment by southp** [comment]
Thanks for the heads up. Rolling the new pricing grid into all the flows is what we will plan for the next milestone, but that will surely take some time. There are also a good amount of high priority bugs that I'm considering to fix beforehand(see p2-pdgrnI-2cl)
For the interim, I'll come up with a fix for this.

**Comment by southp** [comment]
Since we are working on exposing the new pricing grid to all the flow already, I've chosen to just expose it to the domain flow in https://github.com/Automattic/wp-calypso/pull/75868

**Comment by southp** [comment]
We can effectively close this now that the pricing grid is the new default through https://github.com/Automattic/wp-calypso/issues/77651 and https://github.com/Automattic/wp-calypso/issues/77650.
