### ISSUE TITLE
Blockbase themes: primary theme color is used instead of Navigation block color setting

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#74984]
### Quick summary

Tested on Quadrat Black and Quadrat Green. When you set a "Text" (or "Submenu & overlay text") color on a Navigation block, links show up in the selected color in the editor. On the live site, however, only ~~custom links (not page links)~~ _*Submenu parents_ are affected; the rest remain in the theme's primary color.
_*edit from cuemarie, see [comment](https://github.com/Automattic/wp-calypso/issues/74984#issuecomment-1491121656)_

### Steps to reproduce

1. Activate a Quadrat theme.
2. Open the Site Editor.
3. Insert a Navigation block (if one doesn't already exist) and add links.
4. Select the Navigation block and set a "Text" color in the block settings.
5. Save.

### What you expected to happen

As in the editor, all of the Navigation block's links should render in the chosen color.

### What actually happened

The color affects the editor as expected. On the live site, "page" links remain in the default "primary" theme color. Only custom links are affected.

![Markup on 2023-03-27 at 15:27:07](https://user-images.githubusercontent.com/5630717/228046151-51d61984-25e8-4ea0-b748-ec42430d84e9.png)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Not yet tested on Atomic.

The Nav block's selected color applies to the `<nav>` element, and has `!important`, but the theme applies a color to the more specific `.wp-block-navigation-link`, which takes precedence.

CSS can be used (for sites with a Premium plan or higher) to set a desired color. For free/Personal sites, additional CSS classes can be used in the editor (e.g. `has-white-color` for white links), but that needs to be set on each individual link within a Nav block (not on the Nav block itself).

**Comment by jp-imagines** [comment]
First reported here: 6068579-zd-woothemes

**Comment by christianguerrag** [comment]
Another report of this happening with the Zoologist theme here: 6075438-zen
I was able to reproduce the bug.

**Comment by jromales** [comment]
Another report in 6083786-zd-woothemes

Using Zoologist theme

I shared CSS workaround

**Comment by jp-imagines** [comment]
Changed issue title, since this doesn't seem specific to Quadrat.
Wasn't able to replicate on _Vetro_, _Appleton_, or _Russell_, but could replicate on _Zoologist_ (and Quadrat themes). Not sure if others are affected too. 🤔 

ETA: Quadrat and Zoologist are both Blockbase children. Updating title again. 😅

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Replicated
- Tested on AT: Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I created a very similar issue on this as well a couple days ago 😆, here: https://github.com/Automattic/wp-calypso/issues/75088 (I'll close that one in favor of this report)

From my tests there and today, I don't see a custom link displaying the color either - only **SubMenu Parent** items are picking up the selected color in the editor.

Screenshots from my re-tests today:

### Menu Structure
![Markup on 2023-03-30 at 17:07:10](https://user-images.githubusercontent.com/27249804/228991187-3be69b43-57af-49ef-9ca7-96e3362f334d.png)
Note - it seems that only the dropdown menu children are appearing as "custom links" - custom links in the parent menu are displaying as "Page Links".

### Global Styles > Colors
![Markup on 2023-03-30 at 17:04:10](https://user-images.githubusercontent.com/27249804/228991212-0f3fcbd5-e6db-4938-b123-98049a3c8665.png)
I've set Text and Link colors in Global styles, to catch if these are picked up by the Navigation block at all.

**Nav Block Color**
![Markup on 2023-03-30 at 17:07:26](https://user-images.githubusercontent.com/27249804/228991233-fe2040b8-2853-491a-9ad4-8d1d9b7d62b9.png)
The Navigation Block itself has been set to show a blue text color. For the purposes of this test I excluded the submenu text color.

**Live Site Result**
![Markup on 2023-03-30 at 17:07:51](https://user-images.githubusercontent.com/27249804/228991250-3f86a763-544f-4845-a528-99e9e8345367.png)
Only the Submenu Parent displays the correct color. 

📌 ACTIONS
- Assigned to Cylon

**Comment by cuemarie** [comment]
User reports from https://github.com/Automattic/wp-calypso/issues/75088

- 6067313-zd-woothemes (Zoologist)
- 6067364-zd-woothemes (Zoologist)
- 6068609-zd-woothemes (Zoologist)
- 6074726-zd-woothemes (Zoologist)

All these users were provided CSS as a solution for now.

**Comment by NoHopeRadio** [comment]
36402057-hc

I believe this is something similar to what happened in Varia themes last year, where some rules to inherit colors are inheriting from the wrong source because of specificity, but I was also wondering if it might have something to do with the fact that link colors and text colors are separate in some other blocks, like in Query Loops (Site title block, Post title block, etc.) but in many cases, it doesn't make sense to separate these into two colors.

**Comment by cuemarie** [comment]
Reports from https://github.com/Automattic/wp-calypso/issues/75196

- Reported in Forums: https://wordpress.com/forums/topic/navigation-menu-text-color-live-not-what-is-set-in-editor/
- 6067099-zen

**Comment by thekingsprojects** [comment]
Another report here: 6175027-zen

Personal plan user, so we used the CSS class workaround. However, the user would prefer to have the links use a different hover color, which isn't possible with this workaround; they'd like to be notified when this is fixed so the workaround can be removed and the hover color will display again.

**Comment by rinazrina** [comment]
Another one with Zoologist theme: #6206739-zen

**Comment by tellisbethel** [comment]
Another report with Geologist - Slate theme on Atomic site here: 6217612-zd-woothemes
Provided CSS workaround.

**Comment by happychait** [comment]
42669286-hc
 
Videomaker theme

**Comment by mattwiebe** [comment]
Re-opening for now because the changes have not yet been shipped to wpcom

**Comment by mattwiebe** [comment]
Ok *now* these changes are merged and deployed. This should be fixed: `core/navigation-link` items should properly inherit the color from the parent nav block.

Please re-open this issue and/or ping me or the Theme team if something goes awry.
