### ISSUE TITLE
Signup: Checkout step

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#750]
Originally opened by @scruffian.

We need to design and implement a checkout step for signup. Some things to consider according to @breezyskies:

- [ ] Mobile cart (we don't currently have an on-page mobile cart in checkout)
- [ ] Exit path (in usability tests, we saw some users struggle to exit checkout when they realized they need to put down a cc for a free trial)
- [ ] Thank you page (post-signup for purchasers vs. non-purchasers)

An initial design:

Collapsed | Expanded
------------ | -------------
<img width="368" alt="screen shot 2015-07-27 at 5 12 39 pm" src="https://cloud.githubusercontent.com/assets/3011211/8920804/ba569912-3482-11e5-8f8b-8887f417279f.png"> | <img width="367" alt="screen shot 2015-07-27 at 5 13 41 pm" src="https://cloud.githubusercontent.com/assets/3011211/8920812/de9e9978-3482-11e5-87f0-d1975677db1c.png">

We've seen several users struggle in usability tests when they hit the checkout step and decide they don't want to enter a cc -- assuming it doesn't break completely, they end up somewhere outside of the NUX flow, with no guidance in place.

One option is adding a "skip" link:

Desktop | Mobile
------------ | -------------
<img width="674" alt="screen shot 2015-07-29 at 3 37 47 pm" src="https://cloud.githubusercontent.com/assets/3011211/8971758/49e8a620-3608-11e5-9b87-1785aba9c264.png"> | <img width="363" alt="screen shot 2015-07-29 at 3 39 53 pm" src="https://cloud.githubusercontent.com/assets/3011211/8971759/49eae28c-3608-11e5-9198-895cee728191.png">

**Comment by folletto** [comment]
The Cart expanded view could use the `FoldableCard` component. :)

**Comment by fabianapsimoes** [comment]
We gave up on implementing checkout as an independent signup step, so closing this issue.
