### ISSUE TITLE
Newsletter onboarding: Update layout typography sizes

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#75019]
Adjusted overall layout typography sizes to ensure they are the same on all steps of the newsletter onboarding flow.

[Specs for desktop and mobile are here](HSljkKnYECEEegL3DqP2xC-fi-7819-77766).

![Image](https://user-images.githubusercontent.com/25607244/228166098-0974e570-45c3-4157-b85f-93aad63bfe46.jpg)

**Comment by lezama** [comment]
Not sure if it can be solved just with typography sizes but a note that we need to improve how things look on 13 inches screens.

**Comment by crisbusquets** [comment]
> Not sure if it can be solved just with typography sizes but a note that we need to improve how things look on 13 inches screens.

Got it. I'll review smaller screens once this is changed. Maybe it's more about the spacing and less about font sizes 🤔
