### ISSUE TITLE
Launchpad: Remove blue loading screen from build flow

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#75028]
This blue loading screen should only appear on Newsletter-only flows. On general onboarding (write & build) we should stick to the default white background.

![Image](https://user-images.githubusercontent.com/7931304/228243348-700959a8-5d9a-41c2-a0b3-5f719a958fd4.png)

**Steps to reproduce:**

* General Onboarding select `Build` flow (Other, promote myself...)
* Select a design
* Once the click on the task `Select a design`
* Select any other design and continue
* Blue loading screen appears

https://user-images.githubusercontent.com/7931304/228243763-39d1d7ab-e853-4faf-9045-31571c6f08b1.mov

**Comment by edanzer** [comment]
This is done in https://github.com/Automattic/wp-calypso/pull/75141
