### ISSUE TITLE
`/subscriptions`: Make `TabSwitcher` work well with the `react-router`

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#75021]

**Comment by yansern** [comment]
Clarification needed. By completing issue, does it also mean that clicking "Sites" tab on Calypso Portal would go to Sites?
And clicking "Comments" tab on Calypso Portal would go to reskinned portal?

**Comment by yansern** [comment]
Possibly decoupling just the part that is needed for shipping. https://github.com/Automattic/wp-calypso/issues/75226

@JuanLucha You might need to chime in on the issue with page refresh?
