### ISSUE TITLE
Plans Grid: Toggle is full width on mobile screen

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#75033]
### Quick summary

<img width="368" alt="Screenshot 2023-03-27 at 7 15 27 PM" src="https://user-images.githubusercontent.com/1126811/228259614-70649f1f-3d0a-402b-a603-df96377b6deb.png">

I would expect the monthly/yearly toggle to have the same margin/padding that logo, header, and plan cards have.

### Steps to reproduce

1. Load wordpress.com/start on mobile size
2. Start through flow
3. Get to pricing page
4. Notice full width toggle

### What you expected to happen

Yearly/monthly toggle to not be full width.

### What actually happened

Was full width.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Tested with device emulator on Microsoft Edge.

**Comment by cometgrrl** [comment]
@southp Can y'all take a look at this one when you have time?

**Comment by lucasmendes-design** [comment]
On my end, the styling also changed. 

![image](https://user-images.githubusercontent.com/98343583/228318394-075c6c43-169d-4d05-b4ac-90c70411ff7c.png)

**Comment by saygunnyc** [comment]
The same goes for me; styling also changes on Chrome and iOS. Just have shared it on the thread, actually.
