### ISSUE TITLE
Feature Request: Onboarding flows for use with mapped domains

### ISSUE THREAD

**Issue by delputnam** [Automattic/wp-calypso#75048]
### What

We'd like to add a special onboarding flow for users who have domains at DNS providers that support Domain Connect. This would allow partners to provide a link to direct their users to a special flow that would allow them to easily create a new site on WordPress.com and use their existing domain name with it.

I think we'll want at least two versions of this flow:

1. A version that would allow a user to create a regular site with a domain that they already own.
- Register / Login
- Choose a plan
- Checkout with the selected plan and the domain connection in the cart
- Immediately after checkout, the user would be redirected to the domain connection setup flow (https://wordpress.com/domains/mapping/[site name]/setup/[domain name]?firstVisit=true). This would give the user the ability to use domain connect to immediately set up the DNS records at their DNS provider.

2. A version that would allow the user to create a link-in-bio site using the same flow as the existing link-in-bio flow.

- Register / Login
- Choose a design (from the link-in-bio themes)
- Choose the profile image, site name, and description
- Choose the plan (personal or premium)
- Checkout with the selected plan and the domain connection in the cart
- Immediately after checkout, the user would be redirected to the domain connection setup flow as in the flow above.

The link to these flows should include query string variables that provide the domain name and the Domain Connect name of the DNS provider, and perhaps the version of the flow. Something similar to the following: https://wordpress.com/start/domain-connect-site?domain=example.com&provider=dc-provider-name&version=standard

We'll want to log (probably in tracks) which dns provider the user is coming from, and which version of the flow they are using.

Also see: pcYYhz-13z-p2#comment-1103

### Why

The reason for this is to allow partners who are interested in helping their users quickly attach sites to their domains provide a way to do this while keeping the name servers of the DNS provider.

### How

We can create a new declarative flow for these and use the existing pages that have been created for them. I think the biggest change will be providing a way to automatically add the domain connection to the cart using the query string parameter.

Please ping the Nomado team with additional questions, testing requests, and for code reviews.

**Comment by obenland** [comment]
What's the current status of this ticket? Is there more work needed or is this complete?

**Comment by delputnam** [comment]
This seems complete to me.
