### ISSUE TITLE
Stats Widget: add widget entry in Odyssey Stats webpack config

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#75109]
Build a sample widget that could be rendered from Jetpack with minimum dependencies.

Note: the widget doesn't have to look anything like the design, we'll have it behind a feature flag. This is meant to accelerate our verification process.

**Comment by jsnmoon** [comment]
I believe we took care of this in https://github.com/Automattic/wp-calypso/pull/75058.
