### ISSUE TITLE
`/subscriptions/sites`: Localize date in the "Since" column

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#75135]
## Acceptance Criteria

- the `date` string in the Since column on the Sites view should be localized based on the user's locale

![Image](https://user-images.githubusercontent.com/25105483/228871771-80bdf50a-28af-4f54-87bc-e99860abb30b.png)

Related PRs where the need for the localized date was brought up:
- https://github.com/Automattic/wp-calypso/pull/75119#pullrequestreview-1364934201
- https://github.com/Automattic/wp-calypso/pull/75115#pullrequestreview-1365078218

**Comment by ivan-ottinger** [comment]
Might be resolved by https://github.com/Automattic/wp-calypso/pull/75119.

**Comment by JuanLucha** [comment]
Hi @ivan-ottinger! That one fixes it, yes. We are using the `useLocalizedMoment` hook now, so as long as we use the correct localization for the user (something that will be implemented later when we open the feature for non-English users), we should be fine.

**Comment by yansern** [comment]
It is now clearer how we want to approach this:

Taken from the comment by @saygunnyc here: https://github.com/Automattic/wp-calypso/issues/74966#issuecomment-1492681887

>  The format currently introduced on the designs, September 12, 2022 is friendlier than 9/12/2022. To make it even friendlier, we can follow https://wordpress.com/sites, –hours, days, followed by date.
> 
> Since
> 2 hours
> 2 days
> March 15, 2023


We'll also just follow how Sites list does the locale for the dates there.

**Comment by TimBroddin** [comment]
Looking into the even friendlier formatting now
