### ISSUE TITLE
Temporary Store Customization Solution

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wp-calypso#75143]
Site design has proven to be a big part of activation and conversion. Our store customization step in the task list is currently broken and irrelevant to the theme we're using and the current state of WordPress and store editing. 

Woo core isn't likely to update this task until June or later. 

To ensure we're converting as many free trials as possible, we need to provide merchants a light experience to make them feel like the site is theirs — and like they have accomplished something. 

Since this is a temporary solution until Woo core fixes this step, I suggest we go with something that is as simple and easy to implement as possible. 

Options: 

1. Use the theme selection step dotcom is using

Pros: Already built, very simple, seems to be effective. 
Cons: Not all of those themes are receiving the improvements Chris has been working on, drops them into the site editor without a lot of guidance. 

2. Use launchpad to do something like Sensei did and show them a preview of their site with name/logo and colors/styles before they get into the full editor. 

Pros: Have an existing framework and examples to leverage, full control of the steps/experience, dynamic preview of their site. 
Cons: More work to implement, potentially need to update the default theme

**Comment by that-mike-bal** [comment]
@daledupreez - not sure if you guys will have time to tackle this in April or not but do you have any other ideas and/or thoughts on the lift?

**Comment by that-mike-bal** [comment]
Talked about it a bit this week, and we seem to all agree that the new store customization experience is too far out to wait. We'll need to explore a temporary solution that is relatively quick to implement. 

@FlorianBru I think this is now on your radar, but let me know if you need any input/direction/help finding the existing experience. 

You can see the current dotcom experience by going to https://wordpress.com/setup/ecommerce/
If that URL doesn't work replace "setup" with "start"



![Image](https://user-images.githubusercontent.com/89872780/232096104-910dced5-f867-4b38-8aff-784d2fe6df0f.png)

**Comment by warrendholmes** [comment]
Closing this, since we are going to create a new project around this.
