### ISSUE TITLE
Posts links not being embedded in Twenty Seventeen

### ISSUE THREAD

**Issue by christianguerrag** [Automattic/wp-calypso#75149]
### Quick summary

A WordPress.com user has added many links to their posts on the same page. 
All the links are saved as embeds, but some of them show only as links, and others load the embed with the post information. 

They are using the Twenty Seventeen theme.
Reported in 6081313-zen

### Steps to reproduce

I wasn't able to reproduce this problem.
Copied their HTML code into a test site and none of the embeds worked.
Tested embedding my posts using the Twenty Seventeen theme, and everything worked as expected.

### What you expected to happen

I expected all the posts to be embedded correctly.

### What actually happened

Some of the posts were shared only as links.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Theme: Twenty Seventeen
Workaround: Asked them to use a Blog posts block for now.

**Comment by christianguerrag** [comment]
The first report was in 6081313-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- On a Simple Test site using theme **Dara**, I published a page with links to other posts on the site.
- These resulted in a preview card of the posts.
- I then switched the site's theme to Twenty Seventeen, and the result was consistent.

**Screenshots/Recordings**
![Markup on 2023-04-12 at 16:06:17](https://user-images.githubusercontent.com/27249804/231605205-128f129a-1bc0-447b-b768-bd18784cf95e.png)

---

**Dara Result**
![Markup on 2023-04-12 at 16:05:01](https://user-images.githubusercontent.com/27249804/231605224-93411c19-d5fe-4dec-ab32-13ba33a4dbf6.png)

---

**Twenty Seventeen Result**
![Markup on 2023-04-12 at 16:05:37](https://user-images.githubusercontent.com/27249804/231605257-62a0f04c-fe6d-43b9-8455-3521ee1b3be6.png)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- Hey @christianguerrag ! Always make sure to exclude any user-specific information in your screenshots or details.

- [ ] Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

Also, while this wasn't replicable directly, I do recognize this issue - I think it may have more to do with the number of posts on the page, and what the Embed block officially supports. I've come across it here and there. 

If you can find a consistent way to replicate the issue (based on number of posts from the same site embedded into one page, for example), please open a new issue with those details!  If I get a chance to do so on my side, I'll update this issue with a link as well 😊
