### ISSUE TITLE
Assembler Sidenav: adding clarity & guidance (checkmarks and premium badge)

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#75156]
# Description

UPDATE on 8 May.

Per discussion below the current design to implement is this [comment](https://github.com/Automattic/wp-calypso/issues/75156#issuecomment-1515228150).  This design satisfies items 2 and 3 below.

See Dave's figma   7l53h5fxAUNjVRBQ82YFwn-fi-2579%3A61230 and reach out to @lucasmendes-design to give him a heads up with dev work starts on this.

![Image](https://user-images.githubusercontent.com/5665959/236757616-eeb72d8e-75b4-449e-bc45-bc4a6ee3b406.png)

-----

A few ideas for improving the sidenav have come up in the Colors & Fonts walkthrough call and in slack.
* pbxlJb-3EX-p2
*  p1680235303990409-slack-CRWCHQGUB

Current Colors & Fonts sidenav:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/5665959/229028253-c2e721f7-c025-495c-b182-cd8040e035d7.png">

# Proposed Ideas

###  1. Spacing between Layout and Styles ✅ 
- [x]  Add subheading text, something similar to these examples
- [x] ✅ https://github.com/Automattic/wp-calypso/pull/75321
| . | . | . |
| --- | --- | --- |
|  ![Image](https://user-images.githubusercontent.com/5665959/229027373-43b058ad-712f-473e-add7-08125addc1c1.png) |   ![Image](https://user-images.githubusercontent.com/5665959/229027562-a87f3460-7f86-4fa6-9641-2289bed40597.png)  | . |

### - [ ] 2. Add premium label if user selects a premium color or font

![Image](https://user-images.githubusercontent.com/5665959/229027953-52a472e2-00a5-468e-8f37-ddbe73fc65ce.png)

### - [ ] 3. Add checkmark or similar indicator as user progresses through items

![Image](https://user-images.githubusercontent.com/5665959/229028016-b9e232b4-c95d-4e83-aa21-fa7de12489af.png)

# Design Tasks
- [ ] @davewhitley can you provide feedback and any designs as needed?
- [ ] 

# Dev Tasks
- [ ] TBD after Dave feedback

**Comment by davewhitley** [comment]
This is sounding a lot like the launchpad in terms of "checklist" functionality and upgrade labels, so I'd like to borrow from that UI. I think it could work well.

<img width="382" alt="Screen Shot 2023-04-03 at 2 57 46 PM" src="https://user-images.githubusercontent.com/618551/229614015-1fc3833c-34a2-4444-bed7-1b53a331ba5e.png">

There are some details to work out but my thoughts are:

- If you click on any of the sections and return to the main menu, then it should be styled as crossed out with a check mark (existing icon changes to an icon). This happens whether they choose something or not. You don't have to choose a footer, for example, right?
- Alternatively, we could just do the crossed-out style without the checkmark icon.
- I agree that adding the upgrade label could help but I'm not fond of the very black label we have. I wish it was lighter.

I'll take a look and mock this up.

Also, here is another checklist we use in the product:
<img width="361" alt="Screen Shot 2023-04-03 at 3 04 13 PM" src="https://user-images.githubusercontent.com/618551/229615418-86d68a9b-de47-41e6-888f-21d9b6d26bf1.png">

**Comment by davewhitley** [comment]
Wanted to go ahead and share this design. Figma https://www.figma.com/file/7l53h5fxAUNjVRBQ82YFwn/Site-Assembler?node-id=2612-60743&t=zqkLOYnYji4O8SI2-4

I'm not exactly sure about the Premium label's visuals or when it should be visible. But, I think the crossed-out style with a checkmark is consistent with other UI in Calypso. You can still click on the list item (it's not disabled).

![image](https://user-images.githubusercontent.com/618551/231621310-121f5ed0-a254-4881-97cb-710f4e920c1e.png)

**Comment by autumnfjeld** [comment]
It makes sense to follow existing UI / visual cues.  Thanks for surfacing those examples @davewhitley .  :)   In this case, could we not have the words crossed out, to me it looks messy, unattractive.  And there is a "double signal" with both the check and the strikeout text.  Seems to me we only need the the checkmark. (I'm ok with deviating here because well, it looks nicer LOL.)

For some reason your image above seems off in boldness/font when compared to the crispness of the LP, but maybe just because the pic is fuzzy? (Not a huge deal, just make a comment for devs to use the idententical styles that LP uses)
<img width="410" alt="image" src="https://user-images.githubusercontent.com/5665959/232953331-820d5058-bd36-4cf0-b74b-6bc17ed8a795.png">


For the premium badge, is it ok if we follow the pill styles that are elsewhere in WP UI? Meaning an oblong pill with a background color. For example:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/5665959/232953536-d719aac9-6ea9-4794-b414-01413cbebe95.png">
<img width="127" alt="image" src="https://user-images.githubusercontent.com/5665959/232953638-19a192b4-bde2-4655-9cd4-87329db591e6.png">
<img width="163" alt="image" src="https://user-images.githubusercontent.com/5665959/232953821-473540c5-7e9e-47cf-96d8-0dd6a0a6b71d.png">
<img width="131" alt="image" src="https://user-images.githubusercontent.com/5665959/232953884-6183875d-a59a-498e-a4c3-a59e3c32d80f.png">

I'm partial to the happy blue background, but if normal premium pill is always black maybe that is best to keep consistency.

cc: @Automattic/lego

**Comment by autumnfjeld** [comment]
Moving this to ready for dev since Dave has given us a solid design, just need a few minor details finalized.

**Comment by davewhitley** [comment]
Yep, we can use the black Premium pill, and not crossing out the text is ok with me. Let's just use the checkmark and try it out. This image is at 1x so it will look fuzzy on a retina screen. I'm using a `Green 50` checkmark here because the checklist on My Home uses the same style. I'm ok with just a gray check as well.

![image](https://user-images.githubusercontent.com/618551/233174545-94f60b15-8ef9-4458-8726-f3559f2951c4.png)

**Comment by lucasmendes-design** [comment]
Hi there, per @autumnfjeld comment ([#76694](https://github.com/Automattic/wp-calypso/issues/76694)). I wonder what do you think about that?  

https://github.com/Automattic/wp-calypso/assets/98343583/c0c0d708-54f8-4dec-928d-e7c0afd73e54

**Comment by lucasmendes-design** [comment]
Some details: 
- Can we make the checkmark slightly smaller? In the prototype I used the 24x24 px. 
- Animation similar to the video below.
- Checkmark and copy are gray. With hover, change e color to black. 

cc: @autumnfjeld 

[Figma prototype](https://www.figma.com/proto/Tv3pYqA3EcRfiXC31IxrXE/Site-Assembler-part-2?page-id=368%3A11840&type=design&node-id=485-13204&viewport=1145%2C-2845%2C0.53&scaling=min-zoom&starting-point-node-id=368%3A12763&show-proto-sidebar=1)

https://github.com/Automattic/wp-calypso/assets/98343583/da4bd829-3cc0-4a6a-8143-760a6c54192c

**Comment by miksansegundo** [comment]
@lucasmendes-design I'm starting with this. Is there anything you want to update?

**Comment by lucasmendes-design** [comment]
Yes, It is :) 

I don't think we need the dark star badge anymore.
<img width="200" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/ecd2ccac-6850-40c5-a8c7-5f47e074251a">

Instead, we can split free and premium styles. 
<img width="626" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/4e650cc7-0add-477f-8ac4-8a3ea8e39b26">

For the checkmarks ✓, let's make it black. There is no need to be like it is disabled (light gray).  
<img width="540" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/779b003c-8f11-4a5b-a3c0-4e269a10f46b">

**Comment by miksansegundo** [comment]
Thanks @lucasmendes-design, the [PR](https://github.com/Automattic/wp-calypso/pull/78324) with those changes is ready for testing.

**Comment by arthur791004** [comment]
> Instead, we can split free and premium styles.
> <img width="626" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/4e650cc7-0add-477f-8ac4-8a3ea8e39b26">

@lucasmendes-design I assume we have to align the copy, badge, etc with the style variations for consistency. WDYT?

| Free Site | Premium Site |
| - | - |
| ![image](https://github.com/Automattic/wp-calypso/assets/13596067/dacbcaf9-6e76-462d-82c7-646d610af525) | ![image](https://github.com/Automattic/wp-calypso/assets/13596067/ed935304-9eae-4e24-bea0-87026363c950) |

**Comment by lucasmendes-design** [comment]
Thanks, Miguel. I put a comment there. 

@arthur791004, yes, we should align there as well. Here are my suggestions for free and premium (and higher) plans. 

_Note: I used the color style as an example._ 

**Free and Personal:**
When we tell users that one category is free and the other is premium. I think we imply that the other one is paid. So, I don't think we need to explain all that in the copy. 
<img width="323" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/a6cbae04-f255-4a53-96a7-e5fd55d022e3">

**Premium and up:**
This way, I think it's clear that they have access to a premium style because of their plan. They can see the value of it. WDYT?
<img width="290" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/56da869e-86c9-45a6-ad6b-cb62928ebc95">

**Comment by arthur791004** [comment]
Looks good to me 👍 cc @Automattic/t-rex

**Comment by mmtr** [comment]
> When we tell users that one category is free and the other is premium. I think we imply that the other one is paid. So, I don't think we need to explain all that in the copy.

There are two aspects that I think are worth noting somewhere in the UI for users: 

1. The needed plan to use the premium styles. I agree users will understand these premium styles are paid, but they won't know what they need to purchase unless we explicitly say so.
2. Premium styles can be tried out for free. If we don't say anything, users could assume they are required to pay to use them and maybe they will be less likely to interact with them.

**Comment by miksansegundo** [comment]
@mmtr, I agree that users should know exactly what they need to purchase and that they can try the styles out for free.

In the assembler, we say "Premium plan or above/higher" in the description of the colors and fonts screens:

<img width="344" alt="Screenshot 2566-06-20 at 11 38 31" src="https://github.com/Automattic/wp-calypso/assets/1881481/8ec734fe-af56-493d-aaa7-57c6c16ce198">


and then in the modal, we mention that they can decide later and try it out first:

<img width="798" alt="Screenshot 2566-06-20 at 11 52 22" src="https://github.com/Automattic/wp-calypso/assets/1881481/f618991b-64b0-456e-b27f-68c4c4fe9126">


In the theme detail, currently, we mention the premium plan and say "or try them out now for free".

<img width="641" alt="Screenshot 2566-06-20 at 11 47 18" src="https://github.com/Automattic/wp-calypso/assets/1881481/f3ac863f-c9c4-41ad-8f74-93bdcb99cad1">


and then in the modal, we say "you can decide later and try it out first":

<img width="808" alt="Screenshot 2566-06-20 at 11 55 06" src="https://github.com/Automattic/wp-calypso/assets/1881481/52c366dd-5657-440b-9195-47f8eaad1f88">



@taipeicoder @arthur791004, I think the [PR](https://github.com/Automattic/wp-calypso/pull/78324) for the assembler is ready to go but maybe we could improve it by adding the description "Make your site stand out with premium styles." for "Premium styles/fonts" and if styles are included or not in the plan say "It's all included in your plan." or "Try them out now for free."
