### ISSUE TITLE
Bug: Ensure that purchased plugins are not removed on eCommerce downgrades

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#75173]
### Details

We have been working on consolidating the code responsible for removing plugins when an eCommerce or Woo Express plan is removed from a user's site (either via cancellation or after expiration).

The logic currently doesn't check whether the user has an active WordPress.com Marketplace or WooCommerce.com Marketplace subscription for the relevant plugin, which means that we can incorrectly remove a plugin that the user is entitled to use even if they are no longer using the eCommerce plan.

_We may have an existing issue for this, but I am adding this issue to make sure the problem is tracked._

### Checklist

- [ ] When a user has an active WordPress.com Marketplace subscription and downgrades their eCommerce plan to a Business plan, we should not remove the plugin associated with that subscription
- [ ] When a user has an active WooCommerce.com Marketplace subscription and downgrades their eCommerce plan to a Business plan, we should not remove the plugin associated with that subscription

**Comment by valterlorran** [comment]
Closing this issue, for more details: p1681480026359469/1681401086.270859-slack-C0Q664T29
