### ISSUE TITLE
Woo Express: Refactor `class-wpcom-features.php` constants

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#75170]
As a follow-up to D106438-code, as suggested by @daledupreez, we should:

- [x] Make the `WOOEXPRESS_PLANS` constant depend on the `SMALL` and `MEDIUM` constants
- [x] Add unit tests for the Woo Express small and medium plans

**Comment by sixhours** [comment]
Started in D106914-code

**Comment by sixhours** [comment]
Closed in D106914-code
