### ISSUE TITLE
Bug: Update post-upgrade screen to use the correct payments task

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#75172]
### Details

We show a post-upgrade screen for users who have upgraded to a Woo Express plan. This page is shown at `/plans/my-plan/trial-upgraded/:siteSlug`. The screen includes a link to set up payment methods. However, the link is for a generic payments setup task, which may not be active when WooCommerce Payments has been installed.

We need to ensure that the task links to a valid, available task.

### Checklist

- [ ] Ensure that the link loads a valid task when WooCommerce Payments is installed

**Comment by sixhours** [comment]
This has been fixed in #75642!
