### ISSUE TITLE
Plans / Components: Incorrect placement of popover toggled at right edge of screen

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7518]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans
2. Select a site
3. Shrink the browser viewport enough that there's not much blank space around main content
4. Click an info button under the Business
5. Click the info button again to dismiss the tip
6. Click the info button once more

#### What I expected

For the tooltip placement to be consistent with as shown after step 4, adjacent the info button.

#### What happened instead

The tooltip was placed further to the right than I'd expected.

#### Browser / OS version

Verified in OSX Chrome 52.0.2743.116 (64-bit) and Safari 9.1.2 (11601.7.7).

#### Screenshot / Video

![tip](https://cloud.githubusercontent.com/assets/1779930/17737713/4a6d72dc-645c-11e6-8f3d-61286b06d3c0.gif)

#### Context / Source

Possibly related to recent Popover refactoring in #7217 (cc @retrofox @gwwar)

**Comment by gwwar** [comment]
Looks like this should be fixed by #7544
