### ISSUE TITLE
Taxes: Show Location Specific Taxes in calypso receipt and print to pdf

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#75195]
### What

Update Calypso's billing receipts to reflect the accurate taxes paid on charges, instead of combining and abbreviating that to "TVA"

### Why

A user came to chat today concerned they were being charged `TVA` tax, when they should be paying `TPS` (GST) & `TVQ` (QST), because they are in Canada. Chat: 34439246-hc

They are being charged those proper tax types, however their receipt in their dashboard shows a combined total tax and labels it TVA.

When they print their receipt, the same shows there; so for now I advised them to add their TPS/TVQ details in the tax field for their record keeping.  It'd be great to elimintate this step and make their calypso receipt reflect what shows in their email receipt. 

**Email Receipt**
![Markup on 2023-04-01 at 10:24:42](https://user-images.githubusercontent.com/27249804/229306126-9d601075-e357-40af-8b36-7ae26c73155a.png)

**Calypso Receipt**
![Markup on 2023-04-01 at 10:25:32](https://user-images.githubusercontent.com/27249804/229306120-cf18e56f-743d-4d8a-8bfe-0c8f894ba805.png)

**Comment by cuemarie** [comment]
Possibly related: https://github.com/Automattic/payments-shilling/issues/1510 

(Closed at first, but I'm not sure these are the same issues, so reopened again for now)

**Comment by JessBoctor** [comment]
This issue will likely be resolved by a combination of https://github.com/Automattic/payments-shilling/issues/2133 and https://github.com/Automattic/payments-shilling/issues/2061

**Comment by JessBoctor** [comment]
There are a number of pieces of information we provide to customers in email receipts that are not available in Calypso receipts. Since this is one of a few, I created a new issue to track making all compliance information available via the API. 

Closing this issue in favor of https://github.com/Automattic/payments-shilling/issues/2408
