### ISSUE TITLE
Users shuffling between In Progress and Failed Import in the in-product migration page

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#75192]
See p1680291374213229-slack-C01A60HCGUA for more details.

**Summary:** 

While the user is migrating their site in the in-product migration page, they kept seeing status shuffling between In Progress and Failed import screen. This shouldn't happen because we should terminate the migration process once the migration has an error. 

**Easy to reproduce?**

This is difficult to reproduce, still trying to find a way to reproduce this behavior.

**Comment by Nic-Sevic** [comment]
Have another instance of this here: 6219984-zd-woothemes

User is seeing 
![image](https://user-images.githubusercontent.com/47717887/233399237-aaef7060-5d86-4cf2-a0ba-f57a1aedf23a.png)
 but I see active (but slow) progress in the rewind logs

User reported seeing the failure around 2023-04-20T14:20:35.664Z but there is a continued directory walk (rewind period 1681965995)

So far I'm only seeing warnings and no errors. There are also several timeouts which are then scheduled as retries. 
In the JP debugger there's a very large queue (Queue Size: 17655 items) which is causing a sync error and likely related

**Comment by Nic-Sevic** [comment]
another instance here: 6704720-zen

blogid: 220127344
rewind period: 1692699082

**Comment by retnonindya** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
I triaged this issue, but since this issue is difficult to replicate, the result is inconclusive. I noticed this issue has been assigned to the team in charge.

**Comment by bogiii** [comment]
I am closing this ticket because we introduced a new way of the migration process with the Migration Guru plugin, so it is no longer relevant.
