### ISSUE TITLE
Reader: comment feed sometimes get added instead of the post feed during auto-discovery

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#752]
Raised by @blowery 

<blockquote>For some reason, Atomic Spin keeps hopping back and forth between the comment feed and the normal post feed. We might need to teach the feed finder to ignore comment feeds during auto-discovery.</blockquote>

Notes from @designsimply

I tested using the feed link for Atomic Spin https://wordpress.com/read/blog/feed/11976096 and I noticed it shows (and links to) http://spin.atomicobject.com/ in the header card and the post author is listed as "Comments for Atomic Spin":

![screen shot 2015-08-27 at thu aug 27 1 33 46 pm](https://cloud.githubusercontent.com/assets/1119271/9528219/7cc467ee-4cc1-11e5-8019-8f54b0546a89.png)
<sup>Seen at https://wordpress.com/read/blog/feed/11976096 using Firefox 40.0.2 on Mac OS X 10.10.5</sup>

I also noticed that http://spin.atomicobject.com/feed/ redirects to http://feeds.feedblitz.com/atomicspin while http://spin.atomicobject.com/comments/feed/ does not redirect. Could that be a factor in this case?

``` bash
↪ curl -I http://spin.atomicobject.com/feed/                                                                                                              HTTP/1.1 302 Temporary Redirect
X-Pingback: http://spin.atomicobject.com/xmlrpc.php
Last-Modified: Thu, 27 Aug 2015 14:49:11 GMT
ETag: "569c6125cab696c01ff67ba086a06bb3"
Location: http://feeds.feedblitz.com/atomicspin
Content-Type: text/html
Cache-Control: public, max-age=3600
Vary: Accept-Encoding, X-UA-Device
X-UA-Device: pc
Date: Thu, 27 Aug 2015 17:38:27 GMT
Age: 2170
Connection: keep-alive
X-Cache: HIT
```

**Comment by bluefuton** [comment]
The comments feed on Atomic Spin (http://spin.atomicobject.com/comments/feed/) now redirects to http://feeds.feedblitz.com/atomicspin too.

**Comment by bluefuton** [comment]
Another possible example is http://www.comptoirdesobjets.com/. There's an empty comment feed which seems to be picked up in preference to the main feed.

**Comment by blowery** [comment]
This sometimes happens when the main feed gets borked with a bad character in the XML, but the comment feed is fine. 

We need to augment SimplePie's autodiscovery stuff wpcom side and always ignore feeds with "comments" in the end of the url.
