### ISSUE TITLE
[Design Request: Site Design for wpcom.link]

### ISSUE THREAD

**Issue by jrdnhllr** [Automattic/wp-calypso#75206]

**Comment by jrdnhllr** [comment]
Project thread (p9Jlb4-6JT-p2)

**Comment by garretsteider** [comment]
@jrdnhllr @Noemish  Updated social link site I collaborated on with [Mindy can be seen here](https://wpcomsociallinks.wpcomstaging.com/)

**Comment by Noemish** [comment]
@garretsteider-a8c can you update the link, please? Is not longer working :/

**Comment by garretsteider** [comment]
@Noemish Done!

**Comment by garretsteider** [comment]
This landing page has been launched! 

[Website](https://href.li/?https://wpcom.link)
[Project thread ](pe8liG-9g-p2)
