### ISSUE TITLE
Restore plan software API is not restoring eCommerce software correctly

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#75216]
### Quick summary

As a result of a recent refactor in D106404-code, which was deployed late last week, the `/wpcom/v2/hosting/restore-plan-software` API is not correctly identifying the right set of software to (re)add to sites with the eCommerce plan.

We need to update the back end to make sure that we (re)install all the correct plugins.

### Steps to reproduce

1. Start with a site that has the eCommerce plan
2. Manually remove one or more plugins that should be included in the eCommerce plan - this may require admin access via WP CLI to enforce that
3. Navigate to _Settings_ -> _Hosting Configuration_
4. Click on the _Restore plugins and themes for my website's plan_ button in the _Restore plugins and themes_ section
5. You should not see the plugins reinstalled as expected

### What you expected to happen

The full set of eCommerce plugins should be (re)installed.

### What actually happened

The eCommerce plugins were not installed.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

It may be possible for support staff to manually add the relevant plugins, but that hasn't been tested.

**Comment by sixhours** [comment]
Started working on this in D106880-code

**Comment by sixhours** [comment]
Shipped a fix in D106880-code
