### ISSUE TITLE
`/subscriptions/sites`: Follow sites list for UI behaviours.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#75221]
> Let's follow the experience on https://wordpress.com/sites. – Underline text links, mouse pointer | Form elements, beam All (icon, name, URL) should be linked to the site in a new window.

The above is taken from a comment from @saygunnyc here. https://github.com/Automattic/wp-calypso/issues/74966#issuecomment-1492681887

**Here are the acceptance criteria:**
- when hovering over the site title, it should underline.
- when hovering over the URL, it should underline.
- the title link should open in a new window
  - The site page title link does not open in a new window because it is going to an internal calypso page.
  - i'm deriving this decision from the fact that external links seem to have target="_blank" in the sites page (from the URL link of the sites page)
- the URL link should open in a new window
- the site icon should open in a new window

**Comment by yansern** [comment]
~This needs to be more refined as in what are the exact list of things that needs to be done.~

Done.

**Comment by ivan-ottinger** [comment]
> - the title link should open in a new window
>   - The site page title link does not open in a new window because it is going to an internal calypso page.

If I am understanding correctly, all the links should basically open in a new tab, correct?
![Markup on 2023-04-04 at 15:13:44](https://user-images.githubusercontent.com/25105483/229802892-f87ac9af-4440-4bfe-9916-dba4deb7ad87.png)

The second bullet point basically means that if one of the links was pointing to a Calypso page, then it wouldn't open in a new tab, right?

---

Underlining is clear to me.

**Comment by ivan-ottinger** [comment]
One more thing for discussion. Do we want to introduce the "open in a new tab" icon as well? 

![Markup on 2023-04-04 at 15:20:28](https://user-images.githubusercontent.com/25105483/229808115-614577e6-2e8d-4671-8780-7e9a761ce078.png)

I vote yes. 🙂 

Related PR review: https://github.com/Automattic/wp-calypso/pull/75277#pullrequestreview-1370980040

**Comment by JuanLucha** [comment]
It was specified we won't in a slack message.
