### ISSUE TITLE
Problems with updating delivery frequency options for external users.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#75224]
Clicking on any of the options here...
<img width="329" alt="Screenshot 2023-04-03 at 12 59 56" src="https://user-images.githubusercontent.com/3832570/229491060-b578457a-d10f-46e6-9d25-b85694723c84.png">
...makes the code explode in the console:
<img width="779" alt="Screenshot 2023-04-03 at 13 00 00" src="https://user-images.githubusercontent.com/3832570/229491186-13986ea6-7dfe-4ea2-98fc-e0b4d2d33e18.png">
It seems to be because that first entry in my list of sites has `blog_ID: 0`:
<img width="324" alt="Screenshot 2023-04-03 at 13 09 28" src="https://user-images.githubusercontent.com/3832570/229492930-a5539d40-943e-485f-90e8-8e74295d160b.png">

---
Another problem I found is this:
<img width="779" alt="Screenshot 2023-04-03 at 13 03 18" src="https://user-images.githubusercontent.com/3832570/229493041-3491ef75-2894-42c6-83b2-958ff74ab024.png">
<img width="779" alt="Screenshot 2023-04-03 at 13 03 47" src="https://user-images.githubusercontent.com/3832570/229493071-bd44c866-18f2-4ba2-a7c4-11e12983e334.png">
This problem occurs when clicking on any of the buttons but with a different site on my list, one with blog_ID other than 0 (One of the P2 of Automattic).

Maybe @TimBroddin can help, as these problems seem related to the API at first glance.

_Originally posted by @JuanLucha in https://github.com/Automattic/wp-calypso/issues/75180#issuecomment-1494136737_

**Comment by yansern** [comment]
@JuanLucha Try to change the delivery frequency on the reskinned portal and see if it works there. This will determine the severity of this issue.

**Comment by mashikag** [comment]
This issue relates to P2 subscriptions - which are only available for internal users. The portal should not support internal users, hence I am closing this issue.

More context: p1680596365266609-slack-C02TCEHP3HA
