### ISSUE TITLE
/subscriptions/sites: Optimistic update for the delivery window input.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#75236]
It feels a bit sluggish to change the delivery window right now. Could we just update the UI first and then have the requests run in the background.

If the request results in error, just silently revert to the previous state for now.

It would be better if an error notice was shown, this can be related to the other issue https://github.com/Automattic/wp-calypso/issues/75222.

**Comment by TimBroddin** [comment]
I agree! Nice read on Optimistic UI patterns: https://simonhearne.com/2021/optimistic-ui-patterns/

**Comment by yansern** [comment]
Thanks! I renamed the title to "optimistic update" as that as the term I was looking for but in my head only "eventual consistency" came up yesterday when I was creating this issue.
