### ISSUE TITLE
Site Assembler - Use tooltip component for category description and pattern name

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#75253]
## What

The tooltip we show on the category list and pattern list uses a `title` HTML attribute while the editor uses a [Tooltip component](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/tooltip).

|Assembler|Editor|
|----|----|
|![Image](https://user-images.githubusercontent.com/1881481/229664790-162ef5a4-6006-4858-a3f4-eeaa4d107e17.png)|![Image](https://user-images.githubusercontent.com/1881481/229664781-a2bd9417-67da-4204-a920-f9472fc56124.png)|

## Why

For design consistency

## How

Use the same [Tooltip component](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/tooltip) as in the editor.

**Comment by miksansegundo** [comment]
@davewhitley What are your thoughts on showing the category name on a tooltip on hover? 

![Image](https://user-images.githubusercontent.com/1881481/229666119-ac5d27a5-c724-4f1b-b9ce-cc3861b1b2a2.png)

The editor doesn't do it. Maybe we don't need it either. Let me know if you think we better remove it.

**Comment by davewhitley** [comment]
It seems fine to me to leave out the category tooltip
