### ISSUE TITLE
Plan Features component icons hidden at intermediate screen widths

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7525]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks
2. Scroll the the Plan Features section
3. Resize the browser such that there are two columns of blocks
4. Slowly narrow the browser window and observe
#### What I expected

The icons to remain visible
#### What happened instead

The icons on the left column are obscured before the page adjusts to a single-column layout:
<img width="1052" alt="screen shot 2016-08-17 at 3 53 27 pm" src="https://cloud.githubusercontent.com/assets/7233112/17751034/45d178d6-6493-11e6-8684-59e8b217179c.png">

It's also a problem specifically on the Custom Domain card when a long site name is listed:
<img width="816" alt="screen shot 2016-08-17 at 3 58 08 pm" src="https://cloud.githubusercontent.com/assets/7233112/17751072/723a0384-6493-11e6-9fa0-17d0744c55a8.png">
#### Browser / OS version

OSX Chrome and Firefox tested
#### Context / Source
# automated-testing

**Comment by lancewillett** [comment]
Good find — I think it sounds like a bit more responsive CSS is needed for these components. Since it's Plans probably a designer from Spectrum, CC @breezyskies

**Comment by breezyskies** [comment]
Plans is currently under the purview of Triton. cc'ing @adambbecker since I'm not sure which team owns this specific piece.

**Comment by lancewillett** [comment]
Doh! You're right — brain fart on my part. Sorry Brie. :)

**Comment by adambbecker** [comment]
Yeah I see what you mean. This and #8510 looks to be flexbox related and it looks like @lamosty is the one to tackle this one based on his experience from #7538.
