### ISSUE TITLE
Change Web Address after domain purchase

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/wp-calypso#7526]
To clarify: _Web Address_ is a public URL of the user that will be used when they, for example, post a comment somewhere. It can be changed at https://wordpress.com/me/account

I have had a report where the user complained that after domain purchase they can still see ".wordpress.com" in their comments. I traced their steps and found the Web Address field in settings. We make a pretty good job to hide wordpress.com address from the user after they upgrade, so we might change this one as well.
#### Steps to reproduce
1. User owns example.wordpress.com
2. Buys upgrade with domain example.com
#### What I expected

I expected the Web Adress would be replaced by example.com if the original matched example.wordpress.com
#### What happened instead

It is still example.wordpress.com
#### Context / Source
# user-report

**Comment by kelliepeterson** [comment]
After doing work on this and review we've determined that auto updating this may lead to more issues than intended and greater likelihood of deadlinks due to expired domains, etc. We will not be making this change.
