### ISSUE TITLE
Site Assembler - Search bar for patterns and categories

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#75262]
## What 

Add a search bar on top of the categories to filter categories and help find patterns. 

**Screenshot of the search bar in the editor**

![Image](https://user-images.githubusercontent.com/1881481/229726428-fb42eaf7-d2d3-4e95-a7b4-d8fc0e41e5d1.png)

**Screenshot of the search bar in the assembler**

![Image](https://user-images.githubusercontent.com/1881481/229727463-e60abdd7-2884-4622-9833-d49f72a91c13.png)

## Why

Because we'll soon have all Dotcom patterns and categories in the assembler. See https://github.com/Automattic/wp-calypso/pull/74957

## How

**Dev tasks** 
In this first iteration, let's use the text input to filter categories: 

- [ ] Filter category matches using their name. 
E.g. the search "call" will filter the category "Call to action"
- [ ] Filter categories that contain patterns that match the pattern name. 
E.g. the search "CTA" will filter the category "Call to action" because in that category there are patterns with names like "Large CTA".

**Design tasks**

- [ ] Search bar design.
Confirm that the design is in this Figma file 7l53h5fxAUNjVRBQ82YFwn-fi-2075-59619

- [ ] Search bar UX
Confirm how the search bar will work when users type something. 
 
- [ ] Empty results design. 
When there aren't any matches, let's show a friendly "No search results" message.

**Comment by miksansegundo** [comment]
I'll leave this issue in the backlog until we agree on the requirements. Should we filter patterns within a category? cc: @davewhitley @Automattic/lego 

My proposal is to filter the list of categories using the text input, meaning that the search result is a shorter category list but all patterns in that category will be shown in the panel after a user clicks on that category.

**Comment by autumnfjeld** [comment]
My initial thought is that it should work the same way that pattern search works in the editor.

**Comment by autumnfjeld** [comment]
> Empty results design.
When there aren't any matches, let's show a friendly "No search results" message.

Instead of an empty list, which is always a little sad, let's say "We didn't find an exact match, but here are our featured patterns".   Something like that.

This is one particular item that I think could deviate from the Editor search bar.  

I believe in any search (themes, or anywhere) an empty list should never be shown to the user.  It doesn't help move them forward and it also gives a sense of "oh, sadness, what I want isn't here".

**Comment by miksansegundo** [comment]
@lucasmendes-design I'd like to know your thoughts on this. Would it work if we copy the same UX as in the editor?

**Comment by lucasmendes-design** [comment]
We can mimic what happens in the Editor and create an empty state for this list where it adds more light to take action instead of leaving the users with nothing. Put some comments here as well marvelousp2 (2023/04/21/call-for-review-dotcom-pattern-categories/#comment-880)

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
