### ISSUE TITLE
Task: Create a bank of 30 #FunWooFacts for use in Woo loading screens

### ISSUE THREAD

**Issue by adrianduffell** [Automattic/wp-calypso#75273]
### Details

At present, the limited amount of facts causes some to repeat during the loading screen.

![image](https://user-images.githubusercontent.com/9312929/229783131-2ce99fe6-e149-4a2f-860a-e47034257632.png)

### Checklist

Updated by ilyas:

- [ ] During the `siteCreationStep` state, display loading message `Hang tight! Your free trial is currently being set up and may take a few minutes.`
- [ ] During the `waitForAtomic` state, display all facts for a set duration 
- [ ] After the facts duration has ended, display `We're almost there! Your free trial will be ready in just a moment.` 
- [ ] Let Warren & Laura [test the change](https://github.com/Automattic/wp-calypso/issues/75273#issuecomment-1539562822) in calypso.live or a video demo
- [ ] Capture conversion data for 1 month prior deployment and compare it with 1 month after

**Comment by warrendholmes** [comment]
I tried to dig up why we have these fun Woo facts, and couldn't find anything. The only thing I could find was the post where @verofasulo summarised the latest design here https://hostedwoo.wordpress.com/2023/03/02/summary-of-the-most-recent-design-updates-for-the-free-trial-launch/.

@dlcallaway I'm curious for your input here. I think these messages are a little off brand and remind me of the [Jester](https://arielhudnall.com/2015/09/06/archetypes-jester/) archetype that Woo used to embody a long time ago — we've spent more time working away from that. 

While we're looking into [how to speed up site creation](https://hostedwoo.wordpress.com/2023/04/27/free-trial-provisioning-drop-offs/) I think a better use of this space would be to set user expectations that their site is being created and might take a few minutes.

**Comment by warrendholmes** [comment]
@lauroraa Could I ask for your help here, please! I'd like to remove the Fun Woo Facts (while we speed things) to add a message to set expectations of how long the free trial creation may take. Something like :

"Your free trial is being set up, this may take a few minutes."

**Comment by verofasulo** [comment]
Hey @warrendholmes :) Thanks for looking into it!

> I'd like to remove the Fun Woo Facts (while we speed things) to add a message to set expectations of how long the free trial creation may take. Something like :
"Your free trial is being set up, this may take a few minutes."

How're you envisioning this part? Currently, the user waits between 60 and 90 secs before landing on the home screen. It's a good idea to set user expectations, but I'm not sure that a static message displayed for 90 secs it's compelling enough to mitigate the issue. Were you thinking about something more dynamic? 

Looping in also @FlorianBru and @that-mike-bal as they're working on this :)

**Comment by lauroraa** [comment]
Hey @warrendholmes! May I propose an alternative?! I completely agree that we should set user expectations here, but I also agree with @verofasulo's point about how a static message might not be very compelling. The intention of the facts was to provide something light and enjoyable during what might be quite an overwhelming experience, as well as to help position ourselves as being more human and personable. 

So how about on the first screen we say:

**Hang tight! Your free trial is currently being set up and may take a few minutes.**

Then, we have some of the facts in the middle. And on the final (or near final screen) we say:

**We're almost there! Your free trial will be ready in just a moment.**

**Comment by that-mike-bal** [comment]
That was my thought as well, something more like 

"It may take a minute or two to set up your site, but while you're waiting... Did you know...."

**Comment by warrendholmes** [comment]
@lauroraa @verofasulo Ok, that makes sense. @adrianduffell / @ilyasfoo Is it possible to make those changes as described by @lauroraa ?

**Comment by ilyasfoo** [comment]
AFAIK, there are only 2 states for loading at the moment, `siteCreationStep` and `waitForAtomic`.

Unfortunately, the `waitForAtomic` step represents the majority of loading time (probably 80%), so we're unable to properly distinguish a "final step" from the rest. What we could do instead, is to set the facts messages for a fixed duration, and set the `We're almost there! Your free trial will be ready in just a moment.` message after until the loading finishes.

One downside is that if it loads too fast (not trying to sound like that's a bad thing), users will never reach that final message. I don't think that's a blocker though. 

@warrendholmes @lauroraa  Does that sound ok?

**Comment by warrendholmes** [comment]
@ilyasfoo Thanks for digging in there! Yes, that sounds good. Will there be a way to test this before it's merged?

**Comment by ilyasfoo** [comment]
@warrendholmes Awesome! 

> Will there be a way to test this before it's merged?

We could try to use calypso.live ([example](https://github.com/Automattic/wp-calypso/pull/76689#issuecomment-1539152021)) when the PR is up. Otherwise, the next best thing I could think of is by making a video demo of it.

**Comment by simison** [comment]
👋  If you add any generic messages that fit other customer types as well (bloggers, builders...), feel free to ship those to everyone, not just Woo.

Also if you end up changing the animation to something else than banner, bring it up with .com design and we could perhaps ship for everyone and avoid maintaining different visuals for different flows.

Thanks!

**Comment by FlorianBru** [comment]
>We could try to use calypso.live (https://github.com/Automattic/wp-calypso/pull/76689#issuecomment-1539152021) when the PR is up. Otherwise, the next best thing I could think of is by making a video demo of it.

A video would be super helpful, so everyone has a chance to check the new solution

**Comment by ilyasfoo** [comment]
Thanks for your feedback, @simison! This issue addresses the loading messages, I think we're not changing any animations (yet).

I'll note your feedback since I think we may have animation changes in consideration somewhere.

We'll consider sharing the loading message texts for other free trial plans as well, if it's relatively simple to implement. Thanks!

> A video would be super helpful, so everyone has a chance to check the new solution

Gotcha, thanks @FlorianBru !

**Comment by ilyasfoo** [comment]
Hey @warrendholmes @FlorianBru @lauroraa, here's a video of the updates.

Observable changes are:
- Initial message set to `Hang tight! Your free trial is currently being set up and may take a few minutes.`
- Reduced duration of various Woo facts – not all facts are able to be shown (4 out of 6 facts was shown in the video, may vary if loading times are longer/shorter).
- Just before being redirected, the message `We're almost there! Your free trial will be ready in just a moment.` is shown.

https://github.com/Automattic/wp-calypso/assets/3747241/b90cf321-a838-40dc-b961-5be2daed835f

Let me know if this works for you!

**Comment by warrendholmes** [comment]
@ilyasfoo 👏 A few cosmetic suggestions (though it's probably best for @verofasulo to decide):

- Can we have "Hang tight! Your free trial is currently being set up and may take a few minutes." contained to one line?
- Maybe we should bold "Hang tight! Your free trial is currently being set up and **may take a few minutes."** and "**We're almost there!** Your free trial will be ready in just a moment."

**Comment by verofasulo** [comment]
Thanks @ilyasfoo @warrendholmes 

> Maybe we should bold "Hang tight! Your free trial is currently being set up and may take a few minutes." and "We're almost there! Your free trial will be ready in just a moment."

Nice! I would use **Medium** weight instead of bold as designed [here](https://www.figma.com/file/4ixWMlzrxllx93tSFsCW6k/Customer-first--Experience?type=design&node-id=7076-153095&t=4T6ihn7dxCQW4UjS-4) for the fun facts. Could we emphasize the initial part of the line? 

- Hang tight! 
- #FunWooFact
- We're almost there!

Also, @ilyasfoo, are we using some specific letter spacing different from 0px? It seems very compressed compared to the designs. 🤔

> Can we have "Hang tight! Your free trial is currently being set up and may take a few minutes." contained to one line?

It would appear a bit off as it would exceed the loading bar. Maybe we can avoid having a widow and wrap the second part of the line?

**Comment by ilyasfoo** [comment]
> Nice! I would use Medium weight instead of bold as designed here for the fun facts. Could we emphasize the initial part of the line?

Ok!

> Also, @ilyasfoo, are we using some specific letter spacing different from 0px? It seems very compressed compared to the designs. 🤔

Good eye! It was in fact, set to `-0.02em` (perhaps a [design requirement](https://github.com/Automattic/wp-calypso/pull/72287) from another flow). I've overridden it for Woo Express flow.

> It would appear a bit off as it would exceed the loading bar. Maybe we can avoid having a widow and wrap the second part of the line?

Ok, I've changed the container's max-width from 540px to 610px.

@verofasulo Please review the updated video 🙏 :

https://github.com/Automattic/wp-calypso/assets/3747241/557ca5b7-9afe-4fa8-b42b-ae62e99aba7a

**Comment by verofasulo** [comment]
Thanks, @ilyasfoo! 💜  

> I've changed the container's max-width from 540px to 610px.

If we go with this solution, could we also change the loading bar width from 540px to 610px and align it with the text container? Other than that, it looks great! 🙌

**Comment by ilyasfoo** [comment]
Deployed in https://github.com/Automattic/wp-calypso/pull/77051.

I've created a funnel to observe any tangible improvements to the conversion rate.

**Comment by verofasulo** [comment]
> I've created a funnel to observe any tangible improvements to the conversion rate.

Thanks, Ilyas ❤️
