### ISSUE TITLE
Users are not shown the Woo Express purchase page after purchasing a plan

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#75281]
### Quick summary

When a user purchases a Woo Express plan from the pricing grid that we are rolling out, we do not redirect them to the Woo Express post-purchase page. This was the behaviour before we switched to the pricing grid.

### Steps to reproduce

1. For a site with the eCommerce trial, navigate to _Upgrades_ -> _Plans_
2. Once on the page, enable the `plans/wooexpress-small` feature flag by adding `?flags=plans/wooexpress-small` to the URL
3. You should see a pricing grid showing the Essential and Performance plans
4. Click on the CTA to purchase a plan, and complete the purchase from the checkout page

### What you expected to happen

The user should be redirected to the Woo Express upgrade page at `/plans/my-plan/trial-upgraded/:siteSlug`.

### What actually happened

The user was redirected to the legacy eCommerce thank you page.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by that-mike-bal** [comment]
I had logged this here but I can go ahead and close that one https://github.com/Automattic/wp-calypso/issues/75302
