### ISSUE TITLE
`/subscriptions/sites`: Settings Popover on the wrong position after screen resizing

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#75282]
https://user-images.githubusercontent.com/3832570/229819323-81f65681-e21b-4e9c-9cc2-c3ca031c4c2d.mov

_Originally posted by @JuanLucha in https://github.com/Automattic/wp-calypso/issues/75239#issuecomment-1496042603_

**Comment by TimBroddin** [comment]
@JuanLucha I can't seem to reproduce this issue. I've tried in both Chrome & Firefox. I checked the code for the Popover component, and it registers an onresize handler:

```js
	bindReposition() {
		window.addEventListener( 'scroll', this.onWindowChange, true );
		window.addEventListener( 'resize', this.onWindowChange, true );
	}

	unbindReposition() {
		window.removeEventListener( 'scroll', this.onWindowChange, true );
		window.removeEventListener( 'resize', this.onWindowChange, true );
	}
```

I went through it step by step, and I didn't catch any immediate errors in the implementation.

![CleanShot 2023-04-05 at 08 55 36](https://user-images.githubusercontent.com/528287/230004225-22a4e0dc-9957-4664-917b-1a155e4324cc.gif)

**Comment by TimBroddin** [comment]
Wait, I can reproduce it! Not deleting the above comment for documentation purposes.
