### ISSUE TITLE
Woo Express: Update trial software deactivation jobs

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#75296]
Atomic folks ran into issues when a large number of trial site software deactivation jobs ran at once. As a result, these jobs are being randomly distributed over a 12-hour time period so they're less likely to bog things down.

Given that, it's possible some users will have upgraded their plans in the up-to-12 hours between the time the job is queued and the time it's run.

If a user has a paid plan, we wouldn't want to deactivate their software, so we need to add checks to these deactivation jobs to confirm the site does not have the `WOOEXPRESS_PLANS` feature before proceeding with the deactivation; otherwise, we should cancel the job.

We can probably rely on `wpcom_site_has_feature` to implement the checks, and the deactivation jobs are located here:

fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sjbn%2Sjbn%2Qqrnpgvingr%2Qcebqhpg.cuc-og

Ref: p1680628522033829-slack-C03TF581JSZ

**Comment by sixhours** [comment]
Started working on this in D107065-code

**Comment by sixhours** [comment]
I'm not sure how to get a site into a state where it does *not* have `ECOMMERCE_MANAGED_PLUGINS` feature but does have the ecommerce software we'd want to remove. Is there a way to remove/add site features via cli?

**Comment by daledupreez** [comment]
I have started exploring a different approach to solving this problem: why not defer the primary decision-making code to run asynchronously? That way we can have the main logic check the conditions at the time the check is running, and don't need separate checks in the secondary code.

Code is in D107169-code, but I haven't had time to get this tested.

**Comment by sixhours** [comment]
The software permissions check was added in D107065-code, so I'm going to close this out for now. We may revisit with a different method of handling multiple ecommerce trial software deactivations in the future.
