### ISSUE TITLE
WooExpress: Yearly discount information is not displayed below the pricing

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75299]
The discount information(`SAVE x% BY PAYING ANNUALLY`) is not shown below the pricing described in the design.

### Calypso
![Screen Shot 2023-04-04 at 17 13 00](https://user-images.githubusercontent.com/1234758/229909616-fb82d0ed-7003-44f6-814c-08904fbd0df4.png)

lD0gTB4IqGsmSmsnjZNaP6-fi-2740-73590

**Comment by sixhours** [comment]
It looks like it's only visible when viewing the "Pay monthly" tab, and then only for the Performance plan, and then it's not styled the way it is in the mockups:

<img width="1074" alt="Screen Shot 2023-04-05 at 2 08 07 PM" src="https://user-images.githubusercontent.com/2124984/230167404-c3a2d047-c700-493b-b161-ffd836587eea.png">

The mockups suggest we should always display it below both plans regardless of whether we're viewing the monthly or annual tabs.

**Comment by sixhours** [comment]
I've run into some weirdness with the plans' monthly price data while working on this; I don't think we're getting the correct values for the Essential plan. The math works out to it being a "-15%" discount (not true -- should be about 36%):

<img width="1061" alt="Screen Shot 2023-04-05 at 4 01 05 PM" src="https://user-images.githubusercontent.com/2124984/230195391-5c48eec9-14a8-47d0-8413-cdfa324f5f42.png">

I'll keep plugging away at it.

**Comment by sixhours** [comment]
The plans object data for the small plan lists the wrong `annualPricePerMonth`, which is one of the values used to do these calculations. It should be `25`, but it's coming back the same as the medium plan at `45` and messing up the calculation:

<img width="803" alt="Screen Shot 2023-04-05 at 4 48 48 PM" src="https://user-images.githubusercontent.com/2124984/230208288-61dde6fd-28c8-45d8-bff7-28d2bb514441.png">

**Comment by daledupreez** [comment]
I think we should discuss whether this is a change we should be making. By deviating from the design for the standard pricing grid, we're buying a _lot_ of long-term maintenance that I am not sure is worth the effort.

I'll bring this up during our dev+design sync today.

**Comment by daledupreez** [comment]
Broader discussion with design: peapX7-22h-p2

**Comment by warrendholmes** [comment]
@daledupreez Should we close if we're going to use existing components?
