### ISSUE TITLE
WooExpress: Features available only on yearly cycle are stroke through instead of hide on the monthly view 

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75298]
Some features available only on the yearly cycle are being stroked through instead of hiding on the monthly view. 

![Screen Shot 2023-04-04 at 16 32 33](https://user-images.githubusercontent.com/1234758/229902895-faf171e9-bfa7-4f01-9bb5-5b542ee6be91.png)

To follow the design proposal, we need to hide this feature and only display it on when the user selects the Yearly pricing.

lD0gTB4IqGsmSmsnjZNaP6-fi-2740-74642

To achieve it, we can add the possibility to receive options on the `get2023PricingGridSignupWpcomFeatures` method:
https://github.com/Automattic/wp-calypso/blob/a2445beec4cd994dedb2dbc00c22748d781d9556/packages/calypso-products/src/types.ts#L56

On the plan definition, we would be able to identify the billing cycle and add the feature `FEATURE_CUSTOM_DOMAIN` conditionally.
https://github.com/Automattic/wp-calypso/blob/257c1036a90e241de8dfba4270ca2aff91847ccd/packages/calypso-products/src/plans-list.tsx#L943-L959

**Comment by sixhours** [comment]
Would it be simpler to `display: none;` these features with CSS since we can already target them with the `plan-features-2023-grid__item-available` class?
