### ISSUE TITLE
Signup: Add autofill for username when available.

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#753]
Originally reported by @kwight.

The current signup flow has a great feature I just discovered: on the user step, `username` was auto-filled as the same as the site slug (eg. `kwight307` was the site name I chose, and that was autofilled and validated for `username`). Would be great to add this to Calypso signup in the future.

**Comment by drewblaisdell** [comment]
We're testing this as of #812 (props @SawyerHood).

**Comment by fabianapsimoes** [comment]
@drewblaisdell can I close this issue?

**Comment by drewblaisdell** [comment]
Yep.
