### ISSUE TITLE
Themes: Sidebar covers theme info in Safari

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#7530]
#### Steps to reproduce
(In Safari)

1. Starting at URL: https://wordpress.com/design/site.wordpress.com
2. Click on a theme to view more info

#### What I expected
I expected the sidebar to disappear and to be able to see the whole window of theme information.

#### What happened instead
In Safari (9.1.2), the sidebar sticks around and covers up much of the information.

#### Browser / OS version
Safari 9.1.2, OS X El Capitan

#### Screenshot / Video

Safari
<img width="1280" alt="screen shot 2016-08-17 at 3 22 06 pm" src="https://cloud.githubusercontent.com/assets/7240478/17753737/62d3dadc-648e-11e6-947f-03b3aa74c764.png">

Chrome
<img width="1280" alt="screen shot 2016-08-17 at 3 22 28 pm" src="https://cloud.githubusercontent.com/assets/7240478/17753743/6d64ae68-648e-11e6-9340-6e60f4263eaf.png">

**Comment by folletto** [comment]
Can this be reproduced? I can't seem to be able to reproduce on the same Safari / OSX version.

**Comment by jeremeylduvall** [comment]
@folletto — Yes, it's still happening each time on my side:

![screen shot 2016-08-31 at 10 28 24 am](https://cloud.githubusercontent.com/assets/7240478/18137481/b30a847e-6f65-11e6-844f-e19ad0b62ccc.png)

Still using Safari 9.1. I don't have any specific add-ons installed. I'm not sure why the experience would be different.

**Comment by folletto** [comment]
Screen width you're working at? 
Retina?

Not sure either... let's see if we can figure that out :D

**Comment by seear** [comment]
Foolproof steps to reproduce, via @lsinger:

1) Use Safari
2) Go wordpress.com
3) click on My Sites
4) click on Themes in sidepanel
5) click on a theme screenshot

**Comment by seear** [comment]
Problem is that `getElementsByClassname` [here](https://github.com/Automattic/wp-calypso/blob/master/client/boot/index.js#L410) returns a [`NodeList` in Safari](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByClassName) instead of an array, so the `isEmpty()` call is not having the intended effect.

The upshot of this is that the previous layout is not being unmounted before _themes_ is rendered.

**Comment by seear** [comment]
Got it. Thanks for reporting, @jeremeylduvall :)

**Comment by folletto** [comment]
Ace debugging and fixing there. Kudos 💯
