### ISSUE TITLE
Stats: move components to the new Subscribers page

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#75316]
PR #75208 added a new Subscribers page, but it uses a module grid from the Insights page.
Create a new module grid for Subscribers and move missing components to implement i1 design.

Design:
![Image](https://user-images.githubusercontent.com/112354940/229968875-edad4f1e-8831-4622-ad55-2bd5b7d75561.png)

Development tasks:
- [x] use existing SCSS mixin to create another grid (similar to the Traffic and Insights) page
- [x] use a new CSS class to represent the above grid and remove `is-insights-page-enabled` CSS class (Subscribers page only) 
- [x] add the `Emails` section and module but keep the existing one on the Traffic page intact
- [x] increase the size of the top subscribers modules to 50% (from 1/3 width now)

**Comment by a8ck3n** [comment]
PR #75379 should address all the tasks listed above.
