### ISSUE TITLE
Themes: Remember position when returning from theme info to viewing all themes 

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#7531]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/
2. Scroll down several times until you're pretty far from the top
3. Click on a theme to view the info for that particular theme
4. Click on "All Themes" to go back to the main theme list
#### What I expected

I expected the page to remember my position and keep me there so I don't have to scroll down through all of the themes again.
#### What happened instead

I'm automatically dropped back at the top. If I've scrolled through 50+ themes, I have to do that all over again.
#### Browser / OS version

Tested on Chrome (latest version) in OS X El Capitan
#### Screenshot / Video

Cloudup: https://cloudup.com/c56piRW4Ka4

**Comment by lancewillett** [comment]
I think this is a nice-to-have UX and comes up in a lot of interactions with JS-driven web apps. One solution is to save the "x,y" position and return there. I know this is something we've had trouble with on front-end views with Infinite Scroll — paging, clicking into a post — then back, and poof! You've lost your place in the scrolling history.

On the other hand, clicking "All Themes" seems like an indication that you're going back to the main list so it might be logical to start at the top. What about supporting position only for when viewers use the browser back button?

CC @folletto for opinions and thoughts (in case Hyperion has discussed this).

**Comment by folletto** [comment]
It's a great suggestion.

We already tried at least a couple of times to do that, but it's not trivial (yes, I recall one of the problems was infinite scroll). It's definitely something that should happen on any "back" action, we just de-prioritized it due to more pressing issues.

**Comment by lancewillett** [comment]
Closing as low priority — let's revisit in the future.

**Comment by folletto** [comment]
Reopening. The reason is that while it's lower in priority after other issues regarding the showcase (i.e. completing the migration to one single showcase), it's still a major UX issue that keeps being reported to us even if it's a kind of frustration that not always surfaces.

**Comment by folletto** [comment]
> Reopening. The reason is that while it's lower in priority after other issues regarding the showcase (i.e. completing the migration to one single showcase), it's still a major UX issue that keeps being reported to us even if it's a kind of frustration that not always surfaces.

Still applies.
There's currently no team working on this, but it's still a major UX concern.

**Comment by folletto** [comment]
Still a major experience problem, but given the lack of a dedicated team right now, the upcoming FSE with new themes, I think the next time the themes page will have developers on it will be due to a rework/redesign of the system, thus closing.
