### ISSUE TITLE
Stats: Convert the new Subscribers page to a functional component

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#75317]
Convert Subscribers page to a functional component by implementing feedback from this PR https://github.com/Automattic/wp-calypso/pull/75208

**Comment by a8ck3n** [comment]
@grzegorz-cp I think this has been addressed in PR #75467.

If anything is missing there, please let me know and I'll spin up a follow-up PR for it!

**Comment by grzegorz-cp** [comment]
@a8ck3n, thanks for all the work. The only thing left was to convert the component to TypeScript. I'll add another ticket to do it.
