### ISSUE TITLE
Notification for expired eCommerce trial leads to dead end

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#75328]
### Quick summary

The notification we show for expired eCommerce trial plans leads to a dead end, as we don't allow eCommerce trials to be renewed.

### Steps to reproduce

1. Set up an eCommerce trial site, ideally one that expired in the last few days
2. If the site wasn't already expired, update the subscription expiry day to expire at the end of today - this probably need to be in the future so the full expiration process occurs
3. In Calypso, open the Notifications panel in the top right corner (the bell icon), and look for a "Reactivate your expired plan for [Site Title] to restore features" notice
<img width="416" alt="Screenshot 2023-04-05 at 10 57 02" src="https://user-images.githubusercontent.com/3376401/230043186-7cf182e6-19f4-44f6-9f3b-e53bbcaf01f5.png">
4. Click on the item
5. This will show you the following "Reactivate Now" content
<img width="404" alt="Screenshot 2023-04-05 at 10 57 16" src="https://user-images.githubusercontent.com/3376401/230043171-aa16a905-d0b7-4985-b6e2-7951abf45109.png">
6. Clicking on the "Reactivate now" link either drops you into `/me/purchases` _or_ tries to add a renewal of the subscription to your shopping cart, which won't work

### What you expected to happen

The notification should either show me a relevant link, or not be shown to me at all.

### What actually happened

The notification was shown to me and took me to a URL that didn't actually allow me to complete the relevant action.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by daledupreez** [comment]
I started exploring a possible solution in D107156-code, but won't have a chance to wrap that up today.

**Comment by nelsonec87** [comment]
This diff implements @sixhours proposed alternative (redirect users to the upgrade page): D108133-code.

It doesn't fully fix the problem yet since we still get the `/me/purchases` sometimes (still debugging that), but this will be a different diff.

**Comment by nelsonec87** [comment]
The diff (D108133-code) was updated to handle the `/me/purchases` problem that happened when no subscriptions were found.
