### ISSUE TITLE
Fixing the with-theme flows

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#75335]
### Details

We discovered some issues with the with-theme flow a [while ago](https://github.com/Automattic/dotcom-forge/issues/1454#issuecomment-1397197929), which prompted us to do a walkthrough paYJgx-2Vo-p2. 

In a nutshell, the problem is if the user selects a paid theme, even if they pay for it, we never activate it; instead, we activate a very old random theme from a hardcoded list of fallback themes. Bespin is addressing this for atomic flows but this still happens for premium themes when you choose the premium plan.

### Steps

- [x] Replace the hardcoded fallback theme list with the current default Core theme. (fbhepr%2Skers%2Sjcpbz%2S.pbasvt%2Sjcpbz%2Qbcgvbaf.cuc%3Se%3Qp62722n8%23867%2Q887-og)
- [x] In the /with-theme flow, ensure we actually activate the chosen theme as long as the site can support it.
- [ ] Install a fallback theme if the site doesn’t support the chosen theme.

### Related

https://github.com/Automattic/dotcom-forge/issues/2045

**Comment by dsas** [comment]
@BogdanUngureanu the middle 'step' here can be ticked off right? It works, it's just not an ideal UX?

**Comment by BogdanUngureanu** [comment]
@dsas yup, that's right! I've ticked that point :)

**Comment by BogdanUngureanu** [comment]
>  Install a fallback theme if the site doesn’t support the chosen theme.

@dsas I don't think this is necessary anymore, right? After the change from D109689-code lands, the default theme (fallback) would be TT3.

**Comment by dsas** [comment]
Sounds good 🎉

**Comment by BogdanUngureanu** [comment]
Both of the tasks have been completed. Closing this issue. :)
