### ISSUE TITLE
Assembler: Solving the weird empty pattern list problem

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#75334]
# Description

Marvel (um or rather Autumn 🤣) has been discussing the awkward "empty pattern list panel" for many weeks.   

This is the screen the user sees after selecting "Sections" from the main side nave .  See here:

### Proposed solution
Discussed in slack, p1680595118197219-slack-CRWCHQGUB  with @davewhitley  giving his 👍.   I'd just like to get @arthur791004 and another @Automattic/lego person to agree this is a good idea. 

* User clicks “Sections” from main side nav
* If user has 0 patterns selected,  show the Categories list
* User sees Category list
* User selects categories, patterns…….
* User clicks Save
* Then user is taken to the “Sections panel” where they see their list of patterns.

* User clicks “Sections” from main side nav
* If user has ≥ 1 pattern selected, show the user's pattern list 
* User sees their list and can select "Add patterns" (or maybe user does nothing) 
* User sees Category list
* User selects categories, patterns…….
* User clicks Save
* Then user is taken to the “Sections panel” where they see their list of patterns.

I do not think this needs any visual design.  It's just mechanics of going straight to the category list if user has selected 0 patterns.

**Comment by okmttdhr** [comment]
I agree with this proposal 🙋‍♂️

**Comment by taipeicoder** [comment]
Closing since this has been address in #77547
