### ISSUE TITLE
Investigate new theme sort orders

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#75346]
### Problem
Themes in the showcase are currently sorted by newest (but labelled Recommended), those in the design picker are sorted kind of randomly.

This leads to several problems:
 * Evergreen popular themes slowly get pushed down the list which makes them difficult to find
 * Sometimes we'll have a glut of marketplace or first party themes solely due to the accident of release dates

### Ideal state

- The list of themes you see shouldn’t be random with only free themes in one place and sorted by recently launched with a mix of free and premium in another.
- We should present a good mix of free and premium themes and should not overwhelm users with too many premium themes at the top of the lists of themes.
- We should present the most appropriate themes to a user which will naturally include free and premium.
- When we present new themes to users we should present the ones they are most likely to buy or activate. (No sense in presenting duds.) But we should also give new themes (free or premium) a chance somehow.

### Solution
We should add a new 'Trending' view and use that as the default, it could include these factors:

- Block vs Classic theme
- Recent activations
- Newness
- Views of the details page
- Views of the demo site
- Has style variations
- Sales if a marketplace product
- Churn if a marketplace product

Ideally the same implementation will be used on both the design picker and the theme showcase, but the theme showcase is arguably more important and it'll be simpler to get it right on one of them and then bring to the other.

We should keep a separate list that is ordered by new. 

### Context
 * p1677083487878989-slack-C048CUFRGFQ - important read
 * Prior art: theme.wordpress.com and fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sgurzr%2Qivrjre%2Scbchyne%2Qgeraqvat%2Qgurzrf.cuc%3Se%3Qpo4s76s3%23192-og (doesn't prefer block themes over non-block themes, doesn't include marketplace themes)

**Comment by dsas** [comment]
This work needs some investigation and breaking down into reasonable chunks

**Comment by dsas** [comment]
Might be worth a quick check with our friends at @Automattic/bespin just to confirm they haven't made any moves on this. Harris was aware of it but it's definitely not been a priority for them.

**Comment by cpapazoglou** [comment]
Hey @dsas 

This project is on our radar but not something we will get to it in the near future. We have made no discussions around it except the sorting criteria that you already mentioned and seem reasonable.

I would start with a good mix of easy ones like views, active installations, sales, newness. That should fix 90% of this issue.

**Comment by dsas** [comment]
This investigation led to this P2: paYJgx-3ig-p2 and indirectly to this project thread: paYJgx-3ht-p2
