### ISSUE TITLE
Stats: Enable selecting an arbitrary start date and end dates for summary pages (e.g., /stats/day/posts/:siteSlug)

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#75356]
Requested here: p1680725466809779-slack-C0438NHCLSY

- Enable visualizing page views from arbitrary start and end dates (e.g., 03/01/2023 to 03/12/2023).
- This will require adding two date inputs for `startDate` and `endDate` as a selectable period.
- We should be able to derive the appropriate `date` and `num` given the start and end dates.

**Comment by kangzj** [comment]
This falls to our project of new date picker which is shipped now: https://github.com/Automattic/jetpack-roadmap/issues/491
