### ISSUE TITLE
Stats Widget: New Odyssey approach leaks styles to other wp-admin components

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#75360]
> I see the same problems reported by @a8ck3n; we'll want to limit our styles to our widget and avoid affecting the rest of the dashboard.

_Originally posted by @jsnmoon in https://github.com/Automattic/wp-calypso/pull/75190#discussion_r1159025357_

**Comment by jsnmoon** [comment]
Related issue: [#75107](https://github.com/Automattic/wp-calypso/issues/75107).

**Comment by dognose24** [comment]
Closed with #75897.
