### ISSUE TITLE
Anchor.fm: Remove the flow from stepper

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75387]
We should remove all the files and references to Anchor on the Stepper once we fully disable the flow and communicate the removal to the users.

Related to #75366

More details: 
* p7fD6U-9EZ-p2
* https://github.com/Automattic/wp-calypso/pull/75366#issuecomment-1498932360

**Comment by daledupreez** [comment]
The original PR was reverted in https://github.com/Automattic/wp-calypso/pull/78315, so I am re-opening this issue.
