### ISSUE TITLE
Task: Add expandable features for Woo Express plans

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#75383]
### Details

As per the Figma designs in lD0gTB4IqGsmSmsnjZNaP6-fi-2740-66911, we need to show a more detailed feature list for the Woo Express plans. That display is currently hidden, as we need to add the relevant feature content and enable the extended list.

### Checklist

- [x] Add the detailed features for the Woo Express Essential and Performance plans
- [x] Enable display of the extended feature comparison

**Comment by markbiek** [comment]
Expanded view: lD0gTB4IqGsmSmsnjZNaP6-fi-2740_69162

**Comment by markbiek** [comment]
Waiting to merge & deploy #75883 and then this can be closed.

**Comment by sixhours** [comment]
Since https://github.com/Automattic/wp-calypso/pull/75883 has been merged and deployed, closing this as complete!
