### ISSUE TITLE
Checkout: Forms need improvement

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#754]
Originally reported by @dzver.

The way we use React, we need to do complicated operations over and over again and repeat code with slight variations. Proper form validation is particluarly hard. We have a solution called form-state, but it's hard to use and not very intuitive. We built an abstraction that's influenced by the way React works with forms, not by our needs and I struggle to use it.

I think it'd be better, if we have forms that look like this:

```
<Form validate={ formValidationCallback } onSubmit={ }>
   <Input validate={ inputValidationCallback } error={ errorComingFromTheServer } />
   <SubmitButton />
</Form>
```

The `Input` component can have an error placeholder and take care about displaying errors. The `Form` component can take care about handling submitting/validating/loading states, server side validation and server side errors.

There are open source forms we may be able to use or we could build a solution and open source it.

cc @scruffian @gziolo @drewblaisdell @rads

**Comment by fabianapsimoes** [comment]
Here's a solution proposed by @rads.

----

There are two problems with `lib/form-state` right now:

1. There is no documentation.
2. It is a monolithic piece of code that covers many different use cases.

I have been hesitant to write documentation for the library because it has changed quite a bit since I originally wrote it, and I expected it would need another refactoring after some real world testing.

The library is inherently complex because we have a variety of different requirements for each form. Some forms need to change the number of fields dynamically, some need to initialize asynchronously, some need to display errors a special way, and some don't need any of that. [My original proposal](https://github.com/Automattic/calypso-pre-oss/issues/6371) was to fix this at the UI level and make all of our forms behave the same way.

It's clear to me now that it's impractical to expect every form on our website to use the same logic. It limits our ability to experiment and some forms just need to be different than others based on UI constraints. Maybe someday we will have inline errors in the Domain Contact Information form, but we shouldn't be forced to implement that based on the limitations of our form handling library.

The component-based API that @dzver proposed in the original post is indeed an improvement from the boilerplate we currently have to write to hook up `lib/form-state`. The library requires boilerplate right now because it's fully decoupled from React, which makes it possible to write tests for it without any DOM or React-specific code. There's nothing stopping us from writing a thin layer of components that wrap the current library to provide the proposed API. That said, the current proposal would need some more work to cover all our use cases. 

I feel the most significant way to improve the current library is to figure out how to break apart the responsibilities into separate modules. Right now there's just one `index.js` file that does everything. It would be much easier to work with if we had a structure like so:

```
lib/form-state/index.js (entry point)
lib/form-state/core.js (basic field changes and form submission)
lib/form-state/initialization.js (async field loading)
lib/form-state/validation.js
lib/form-state/sanitization.js
```

The idea is that you could start by using only the core features and add each module as needed. If you needed only basic validation, you would only need to enable the `validation.js` module and could ignore the rest.

Here is a list of requirements I came up with off the top of my head based on our existing use cases:

- Form fields
	- Initialize with filled in field values synchronously
	- Initialize from server asynchronously and disable fields
	- Initialize from a previous form state
	- Reset fields to initial state
	- Allow the structure of the fields to be change dynamically (drop down menu, adding additional users, etc...)
- Validation
	- Asynchronous
	- Only happens after the user changes a field
	- Debounced
- Sanitization
	- Happens right before validation
- Error display
	- All errors in a single list
	- Inline errors next to each field
	- Don't show errors for a field that hasn't been changed yet
- Submitting
	- Show errors for all fields after submitting
	- Run validation again if there are errors or unchanged fields
	- Prevent submit if there are errors after validation

**Comment by gziolo** [comment]
I was thinking how we could make this easier to use. Recurring issues I noticed:
- lots of boilerplate code in all React components using ...

... to be continued, I need to go offline now :)

**Comment by mtias** [comment]
Site settings is also in need of attention, adding the label to try and sync work. And cc @rralian.

**Comment by janm6k** [comment]
Going through old issues, closing ones that does not look like important one.

Please feel free to reopen if applicable.
