### ISSUE TITLE
Anchor: Remove Anchor.fm library

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75409]
We need to remove the Anchor.fm library on WPCOM.

It's also important that we make sure that we have a decision about the blocks(https://github.com/Automattic/wp-calypso/issues/75405). We may have some blocks that depend on this library.

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Snapube.cuc%3Se%3Q3917q0r3-og

More details: p7fD6U-9EZ-p2

**Comment by andres-blanco** [comment]
D112382-code
