### ISSUE TITLE
Anchor: Remove Jetpack block

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75405]
We should dig more into this one and think what are the impacts on the users that had these blocks added. 

fbhepr%2Skers%2Swrgcnpx%2Scebwrpgf%2Scyhtvaf%2Swrgcnpx%2Srkgrafvbaf%2Soybpxf%2Snapube%2Qsz%2S-og

**Comment by andres-blanco** [comment]
Relevant comment: https://github.com/Automattic/dotcom-forge/issues/1959#issuecomment-1489087666
