### ISSUE TITLE
Anchor: Remove Anchor.fm mu-plugins 

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75407]
We should remove the Anchor.fm mu-plugins.

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Snapube.cuc%3Se%3Qr925rr2s-og

More details: p7fD6U-9EZ-p2

**Comment by andres-blanco** [comment]
D112226-code
