### ISSUE TITLE
Site Assembler - Handle Server Errors fetching categories and patterns

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#75419]
## What

We don't handle an error 500 or others in case the server fails when fetching categories or patterns.

Find the code in the hooks `usePatternCategories` and `useDotcomPatterns`. See #75326.

## Why

Without a retry or a notification the UI will be broken and the users won't know what to do.

## How

- [ ] Retry using `useQuery` retries. See [docs](https://tanstack.com/query/v3/docs/react/guides/query-retries).

Consider showing a friendly notification saying that we are having technical difficulties if the retry doesn't work.

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
