### ISSUE TITLE
Anchor: Remove Anchor.fm rest API

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75410]
We need to remove the Anchor.fm rest API after removing the flow.

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Snapube.cuc%3Se%3Qsr701o92-og

I believe we should work on this change after the stepper flow is removed:
* https://github.com/Automattic/wp-calypso/issues/75387

More details: p7fD6U-9EZ-p2

**Comment by andres-blanco** [comment]
D112235-code

**Comment by mreishus** [comment]
I think I found another one: `podcast-details.php` `PodcastDetailsTest.php`, originally added in D54402-code, used in caly here:
https://github.com/Automattic/wp-calypso/blob/fd44f7341791070d8547cac73539e4dffb20b2df/client/landing/stepper/hooks/use-podcast-title.ts#L20-L24
