### ISSUE TITLE
Anchor: Remove Anchor.fm unit tests on WPCOM

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75411]
We should remove the Anchor.fm unit tests from WPCOM. We should do this after removing the Anchor library:
* https://github.com/Automattic/wp-calypso/issues/75409

fbhepr%2Skers%2Sjcpbz%2Sova%2Sgrfgf%2Svfbyngrq%2Sfhvgrf%2SNapube%2Spynff%2Qnapube%2Qgrfg.cuc%3Se%3Q2860o62p-og

More details: p7fD6U-9EZ-p2

**Comment by andres-blanco** [comment]
D111648-code
