### ISSUE TITLE
Site Assembler - Show translated patterns

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#75421]
## What

The pattern name and content are not shown translated in the UI.

## Why

When a user has a language different than English set in `Account Settings > Interface language`, we must show the patterns translated. 

# How
The patterns toolkit API gets the `lang` param and returns the list of patterns translated, including their `html` markup.

![Image](https://user-images.githubusercontent.com/1881481/230546221-f3f774bc-844a-4f61-a640-0d78b38303eb.png)

E.g. `html` in `en`:

```html 
"<!-- wp:group {\"align\":\"full\"} -->\n<div class=\"wp-block-group alignfull\"><!-- wp:group {\"align\":\"full\",\"style\":{\"spacing\":{\"padding\":{\"top\":\"4em\",\"bottom\":\"2em\",\"right\":\"var:preset|spacing|60\",\"left\":\"var:preset|spacing|60\"}}},\"layout\":{\"inherit\":false}} -->\n<div class=\"wp-block-group alignfull\" style=\"padding-top:4em;padding-right:var(--wp--preset--spacing--60);padding-bottom:2em;padding-left:var(--wp--preset--spacing--60)\"><!-- wp:paragraph {\"align\":\"center\"} -->\n<p class=\"has-text-align-center\">Proudly Powered by <a href=\"https://wordpress.org\">WordPress</a></p>\n<!-- /wp:paragraph --></div>\n<!-- /wp:group --></div>\n<!-- /wp:group -->"

```

E.g. `html` in `es`:
```html
"<!-- wp:group {\"align\":\"full\"} -->\n<div class=\"wp-block-group alignfull\"><!-- wp:group {\"align\":\"full\",\"style\":{\"spacing\":{\"padding\":{\"top\":\"4em\",\"bottom\":\"2em\",\"right\":\"var:preset|spacing|60\",\"left\":\"var:preset|spacing|60\"}}},\"layout\":{\"inherit\":false}} -->\n<div class=\"wp-block-group alignfull\" style=\"padding-top:4em;padding-right:var(--wp--preset--spacing--60);padding-bottom:2em;padding-left:var(--wp--preset--spacing--60)\"><!-- wp:paragraph {\"align\":\"center\"} -->\n<p class=\"has-text-align-center\">Ofrecido con orgullo por <a href=\"https://wordpress.org\">WordPress.com</a></p>\n<!-- /wp:paragraph --></div>\n<!-- /wp:group --></div>\n<!-- /wp:group -->"

```

- [ ] Make sure the `lang` param is correct.
There seems to be a race condition bug because the request gets the `lang` prop with `en` in the development environment. See https://github.com/Automattic/wp-calypso/issues/74928
- [ ] Try client rendering strategy?
Can we use the pattern markup in the `html` prop to render patterns directly in Calypso? See the component [PatternRenderer](https://github.com/Automattic/wp-calypso/blob/trunk/packages/block-renderer/src/components/pattern-renderer.tsx#L38).
- [ ] Try server rendering strategy?
Can we pass the pattern markup in the `html` prop to render patterns using API `/block-renderer/patterns/render`? See the hook [useRenderedPatterns](https://github.com/Automattic/wp-calypso/blob/079090fded1b19041c71ab3e84be1a4c385da9cf/packages/block-renderer/src/hooks/use-rendered-patterns.ts#L31).

**Comment by arthur791004** [comment]
Closing it as it's completed via https://github.com/Automattic/wp-calypso/pull/75469
