### ISSUE TITLE
Notifications: Import Successful notification appears blank

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7543]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/import/example.wordpress.com
2. Ensure desktop push notifications are enabled
3. Import a WordPress file into your site
4. Observe notification

#### What I expected
A notification alerting me that the import was successful

#### What happened instead
An empty notification (seen below with the e-mail notification for context).
<img width="359" alt="screen shot 2016-08-18 at 4 36 56 pm" src="https://cloud.githubusercontent.com/assets/7233112/17792106/0af97044-656d-11e6-8296-7825aed90447.png">

Originally noticed from this ticket for the Android app: https://github.com/wordpress-mobile/WordPress-Android/issues/4502 (which is now fixed)

cc: @dmsnell 

#### Browser / OS version
OSX Chrome

#### Context / Source
#manual-testing

**Comment by dmsnell** [comment]
@mzorz is this related to the work you have been doing?

**Comment by mzorz** [comment]
I think they are using the old callbacks and need to implement the new
builders following the lines of the new work.

**Comment by dmsnell** [comment]
@hoverduck where are these coming from? Are they from the backend on WordPress.com just like mobile device push notifications?

**Comment by hoverduck** [comment]
I assume so.  They come through whether I have the Import page open or not

**Comment by mzorz** [comment]
This has been fixed now by @mattsherman, closing (and many thanks all)
