### ISSUE TITLE
Plans: Plans screen doesn't set a screen title

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7545]
Originally observed at https://github.com/Automattic/wp-calypso/pull/7224#issuecomment-240914104
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/insights
2. Select a site
3. Note title is "Stats - WordPress.com"
4. Switch to Plan screen in Sidebar
#### What I expected

Title changes to "Plans" prefix
#### What happened instead

Note title is still "Stats - WordPress.com"
#### Browser / OS version

Chrome OSX Version 52.0.2743.116 (64-bit)

**Comment by aduth** [comment]
Note that #7224 will change the implementation behavior of screen title.

**Comment by lancewillett** [comment]
This is still a valid bug, re-tested the same steps during a bug scrub today.

Plans subpages change the title: "Plans" and "Domains" — but "My Plans" as the landing view for /plans doesn't update the title.

**Comment by rachelmcr** [comment]
#bug-scrub

I re-tested the issue using the steps provided, and by navigating to "My Plan" and "Plan" from other subpages, and each time the page title updated to "Plans" as expected.
