### ISSUE TITLE
Plans: "My Plans" needs clear page title and heading

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7546]
#### Steps to reproduce
1. (Prerequisite) Use a mobile device, device emulator, or Chrome viewport emulation for small screen
2. Starting at URL: https://wordpress.com/plans/my-plan
3. Select a site
#### What I expected

A heading like most My Sites sections, with access to sidebar navigation and meaningful page title.

![image](https://cloud.githubusercontent.com/assets/1779930/17797453/0366fe26-6597-11e6-9569-f3b0ef38f038.png)
#### What happened instead

I have no access to sidebar navigation, and am presented with a dropdown labeled "plans my-plan".

![image](https://cloud.githubusercontent.com/assets/1779930/17797463/170db6cc-6597-11e6-8840-abc0020eaa1c.png)
#### Browser / OS version

Chrome OSX Version 52.0.2743.116 (64-bit)

**Comment by lancewillett** [comment]
Saw this today in a note from @beaulebens 

> "My Plan" page doesn't set a page title properly

1. Start at Stats page
2. Click on Plans, My Plan
3. You'll see the page title is still "Stats"

<img width="575" alt="screen shot 2016-10-05 at 15 23 19" src="https://cloud.githubusercontent.com/assets/66797/19133907/b652fa06-8b0f-11e6-99c4-3e7fbd9a6851.png">

**Comment by rachelmcr** [comment]
I tested this using the steps above and can no longer reproduce. The page title is set as "Plans" and I have a heading area with access to the sidebar navigation as expected:

![screen shot 2017-08-07 at 4 32 40 pm](https://user-images.githubusercontent.com/8658164/29033868-5496ee56-7b8e-11e7-9e56-710eb7fd0570.png)

Tested on Chrome 60.0.3112.90, Mac OSX 10.12.6
