### ISSUE TITLE
Woo Express Essential: Monthly/Yearly toggle overflow

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#75487]
CfT: pdtkmj-1mM-p2#comment-2527

The "Pay Monthly"/"Pay Annually" buttons overflow on small mobile screens (eg iPhone SE).

![image](https://user-images.githubusercontent.com/917632/230934732-f3a7f50b-3e84-4463-8e5a-3f5f23d3bb39.png)

**Comment by sixhours** [comment]
There's some discussion about changing the design that I think would solve this issue: peapX7-22h-p2#comment-2484
