### ISSUE TITLE
Woo Express Essential: Add downgrade/upgrade paths in Bundle_Upsell

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#75480]
We need to add downgrade and upgrade paths to the backend for Woo Express Essential. Bundle_Upsell file is here:

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Sohaqyr%2Qhcfryy.cuc-og

This was done in D103820-code for the Performance plan, may be a good reference to follow.

**Comment by sixhours** [comment]
Started working on this in D107438-code

**Comment by markbiek** [comment]
@sixhours I suspect that #75484 is related to this issue but I'm keeping it separate for now.

**Comment by sixhours** [comment]
Fixed in D107438-code
