### ISSUE TITLE
Woo Express Essential: Charged full price when upgrading to performance

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#75484]
CfT: pdtkmj-1mM-p2#comment-2526

When upgrading from Essential to Performance, we're charging the full performance price rather than the difference between plans.

This may be fixed by #75480.

![image](https://user-images.githubusercontent.com/917632/230932471-509c63a3-75f1-44fd-a198-9dd18fca19d9.png)

**Comment by sixhours** [comment]
I think this will be addressed by D107438-code -- if I apply that patch and sandbox the API, I am not charged the full price. The $300 I originally paid for essential is subtracted, leaving a final price of $240.

**Comment by sixhours** [comment]
This was fixed in D107438-code
