### ISSUE TITLE
Woo Express Essential: Downgrade button tooltips

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#75486]
CfT: pdtkmj-1mM-p2#comment-2527

The desktop site Downgrade button has tooltips instructing users to contact support but there is no corresponding copy on mobile whihc could be confusing.

![image](https://user-images.githubusercontent.com/917632/230934195-3636f94e-ed88-401d-9078-4b7a9fd9af2e.png)

**Comment by sixhours** [comment]
Fixed by #75903
