### ISSUE TITLE
Woo Express Essential: Monthly plan note differs from Performance

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#75483]
CfT: pdtkmj-1mM-p2#comment-2505

On the monthy plan toggle, Essential and Performance have different notes under them. The annual plan notes are the same.

Essential: "per month, billed monthy"
Performance: "Save 36% by paying annually".

![image](https://user-images.githubusercontent.com/917632/230931898-7fecc495-3e37-46a2-94fe-f04285bd397e.png)

**Comment by daledupreez** [comment]
There is more discussion about this aspect of the design in peapX7-22h-p2.

**Comment by valterlorran** [comment]
I believe this PR caused it to break: https://github.com/Automattic/wp-calypso/pull/75073

https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plan-features-2023-grid/components/billing-timeframe.tsx#L46-L62

**Comment by warrendholmes** [comment]
I think this can be closed now, looks like we have fixed this:



![Image](https://github.com/Automattic/wp-calypso/assets/995473/0cdbd32e-c7e1-46de-8623-9bbd6f327285)
