### ISSUE TITLE
Woo Express: Fatal error on plans page

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#75497]
### Quick summary

Woo Express plans and trial can't load the `/plans` page on local and wpcalypso environments. Production is fine, but I'm making this a blocker because it interferes with our ability to test and launch the Essential plan

### Steps to reproduce

1. Create a trial site at `/setup/wooexpress`
2. Visit `https://wpcalypso.wordpress.com/plans/yourtrialsiteslug`
3. The screen will go gray

### What you expected to happen

For the plans page to load

### What actually happened

A typescript error we traced back to https://github.com/Automattic/wp-calypso/pull/75424; `visiblePlans` is undefined.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by youbrokesomething** [comment]
@sixhours The bot keeps adding that '[Status] Escalated' tag because that lets us (KitKat) get a ping whenever a high-priority or blocker bug gets opened to track the issue until it's fixed. Sorry if that was confusing!

Also, thanks for getting this one fixed so fast!
