### ISSUE TITLE
Woo Express Essential: Unable to deactivate/activate plugins

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#75491]
CfT: pdtkmj-1mM-p2#comment-2529

User can visit `/plugins/manage` but can't activate/deactivate plugins.

**Comment by sixhours** [comment]
AFAIK users should be able to manage plugins on the Essential plan and I'm able to activate/deactivate plugins there (both locally and on wpcalypso using an Essential plan site). I wonder if this came up before https://github.com/Automattic/wpcomsh/pull/1340 was shipped and deployed to Atomic?

**Comment by markbiek** [comment]
Closing as unreproducible. Please reopen if more information becomes available.
