### ISSUE TITLE
Hide my Gravatar button overlaps with the text

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#75518]
### Quick summary

<img width="701" alt="image" src="https://user-images.githubusercontent.com/18581859/231041801-81169e75-f1ad-46cf-9bb3-e5243df158c4.png">

The button for "Hide by Gravatar" section on this page seems to overlap with the text:

https://wordpress.com/me

### Steps to reproduce

- Visit https://wordpress.com/me
- See that the button overlaps with the text.

### What you expected to happen

Button shouldn't overlap with the text.

### What actually happened

Button overlaps with the text.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
- Replicated.

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to reproduce the issue following the steps provided above.

<img width="695" alt="Screenshot on 2023-04-11 at 10-40-25" src="https://user-images.githubusercontent.com/67279475/231105137-0371831b-6852-4f42-971b-edb639498497.png">


📌 ACTIONS
- Closed as duplicate of issue #74598 

📌 Message to Author

Thanks for the report! The issue will be fixed once https://github.com/Automattic/wp-calypso/pull/75385 is shipped.
