### ISSUE TITLE
Woo Express: Add support for new plans to live chat in the UI

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#75556]
* We need to ensure Woo Express Essential (monthly and yearly) and Woo Express Performance (monthly and yearly) users are eligible for live chat support in the UI.
* Woo Express Trial users may get live support chat access, but it's not a blocker.
* This may include work on chat routing, but we'll need to coordinate with Woo folks (possibly Woo Ops) to ensure they're aware and ready to take incoming chats.
* File where chat support is added is here:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sfhccbeg%2Shfre.cuc%3Se%3Qo352s5o9%23615-og
* It may make sense to classify the Woo Express plans under the same plan tier as ecommerce plans at first, then find out from Woo if they need more fine-grained control.

Ref: peapX7-1Yu-p2#comment-2438

**Comment by sixhours** [comment]
Started working on this in D107558-code

**Comment by sixhours** [comment]
Shipped in D107558-code

**Comment by sixhours** [comment]
Apparently there's one more step; I mistook the ZD routing for live chat routing. 🙃 Started working on live chat routing to Woo in D107654-code

**Comment by andres-blanco** [comment]
@sixhours is this issue finished?

**Comment by sixhours** [comment]
Oh, yep!
