### ISSUE TITLE
Woo Express: Make sure support for new plans is available in ZD

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#75557]
We probably don't have access to do this, but we should check with @kriskarkoski and/or @jesscga to ensure the plans are added to ZenDesk for support reference.

Ref: peapX7-1Yu-p2#comment-2438

**Comment by markbiek** [comment]
Initiated discussion in p1681231258429749-slack-C03Q87XT1QF

**Comment by sixhours** [comment]
New slugs to map are in D107558-code

**Comment by markbiek** [comment]
Plans have been added to ZD: peapX7-1Yu-p2#comment-2480
