### ISSUE TITLE
Woo Express: Feature flag cleanup

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#75560]
Once the Essential plan flag is enabled in all environments, we should go through and remove any lingering references to Woo Express feature flags both in the implementation code and the config files themselves.

1. PR to remove references to the flags in code.
2. PR to remove the flag itself from the config files. 

This could also be a time to review other feature flags we've added that can be removed.

**Comment by sixhours** [comment]
This has been cleaned up!
