### ISSUE TITLE
Jetpack Comments - Pages/Posts with comments on automatically scroll to malformed comments - Logged in Chrome browser only

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#75578]
### Quick summary

I've found that as of right now, on `AT` sites only if comments are enabled on a page/post, it automatically scrolls to that section and the section does not appear correctly as seen below:

![gbm4Kl.png](https://user-images.githubusercontent.com/51870544/231273265-4582fdf3-7c12-40c1-be93-78754593d6d6.png)

### Steps to reproduce

1. Make sure that you are on an Atomic site and have comments enabled on your posts/pages
2. Navigate to one of the post/pages with comments

### What you expected to happen

The post/page should not scroll to the comments section and the comments section should look as expected.

### What actually happened

The posts/pages are scrolling to the comments section and the comments section is distorted.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I've only been able to reproduce on Chrome so far. Firefox and Safari seem okay. Right now the only workaround I'm aware of is to disable comments completely.

**Comment by ClassicRKR27** [comment]
Reported in this interaction: 39918395-hc

**Comment by metabreakr** [comment]
Working on pdEkSe-2I9-p2 and can confirm this occurs on AT using the TT3 theme.

**Comment by thekingsprojects** [comment]
I can also replicate this on an Atomic test site, in Chrome only. Tested with the Twenty Twenty-One theme. I noticed that a lot of `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` errors (and a few others) are appearing in the browser inspector console, for a few different files. Those same errors don't appear in Firefox, and the issue doesn't seem to happen there.

<img width="1359" alt="comments-bug-console1" src="https://user-images.githubusercontent.com/82622339/231283398-dddbe0f7-1791-4693-b43e-46a73b79f2f4.png">

**Comment by kerrynicl** [comment]
Also reported in this chat 42389236-hc

**Comment by dhackneya8c** [comment]
Another report in 37736741-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple - Could not replicate
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – **Yes**, with Jetpack Comments module enabled

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described in Chrome Version 112.0.5615.49

**Screenshots/Recordings**

_Comments behavior on page refresh_

https://user-images.githubusercontent.com/27249804/231293118-5180b7a9-6044-4892-af60-121a2771c00a.mp4

---

_Self-Hosted Site with Jetpack Comments enabled - scrolling that happens is automatic_

https://user-images.githubusercontent.com/27249804/231295236-1aafb35b-b27a-4bed-9631-31aea5f805df.mp4

---

Incognito Browser:

https://user-images.githubusercontent.com/27249804/231295411-00df07d1-ee78-4357-85b5-bd39e16f889e.mp4


📌 ACTIONS
- Assigned to Loop (with a ping: p1681249153661569-slack-C03NLNTPZ2T )
- There's also some findings & discussion happening here: p1681248536938019/1681242949.706089-slack-CB0B2G43X

**Comment by cuemarie** [comment]
Looks like there's some additional findings tracked here: p1681248536938019/1681242949.706089-slack-CB0B2G43X

**Comment by cuemarie** [comment]
D106778-code has been reverted, this should be resolved! 🎉 

Thread: p1681259104619809/1681242949.706089-slack-CB0B2G43X
