### ISSUE TITLE
Simple Sites with Custom Domain - FSE Template homepage fails to load from Pages screen, 'blocked loading mixed active content' error

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#75577]
### Quick summary

On FSE/block themes, if the site's homepage is set to display latest posts (and therefore uses the "Home" or "Index" template), a "virtual" homepage is shown in Calypso at _My Site > Pages_. The option to preview the homepage yields a blank preview.

### Steps to reproduce

1. Make sure you have an FSE-compatible block theme active.
2. Set your site's homepage to the default/latest posts at _Settings > Reading_.
3. At _My Site > Pages_, click the 3-dot kebab menu next to the "virtual" homepage, and click "View page."

### What you expected to happen

Expected to see a preview of the site's homepage.

### What actually happened

The preview is blank.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Homepage can be previewed (including on different device sizes) in the Site Editor or Customizer instead as a workaround.

Browser console log:

`Blocked loading mixed active content “http://{DOMAIN-NAME}/?iframe=true&theme_preview=true&frame-nonce=b65387fce2&cachebust=0&calypso_token=006313bd-a9d8-4f11-aa10-f94c08039bab”`

**Comment by jp-imagines** [comment]
Initial report in 40862082-hc. I was able to replicate on Simple, but not on Atomic.

**Comment by cuemarie** [comment]
~~📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*~~
- ~~Tested on Simple – Could Not Replicate~~
- ~~Tested on Atomic – Could Not Replicate~~

📌 ~~FINDINGS/SCREENSHOTS/VIDEO~~
- ~~Tested with themes `Blank Canvas` and `Skatepark` (what the user in the above report is using) on Simple site, as well as `Twenty Twenty Three` on AT site, and could not replicate in any test.~~
- ~~Tested using Firefox 111.0.1 and Chrome Version 112.0.5615.49~~

~~**Screenshots/Recordings**~~

~~**Simple Site, Skatepark Theme**~~
~~https://user-images.githubusercontent.com/27249804/231266844-91abbe37-bf2f-4298-83ba-a07dc124ee7f.mp4~~

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- Hey @jp-imagines ! I wasn't able to replicate this same result - could you share more details about your browser, and perhaps a screen recording of the issue in your test site(s) where you're able to replicate?

**Comment by jp-imagines** [comment]
@cuemarie Still able to replicate on my end! Using Firefox 112.0 (just updated today; was using 111.0 yesterday when I initially replicated the issue), simple site using the _Zoologist_ theme.

Screen recording:

https://user-images.githubusercontent.com/5630717/231490760-d1f8394e-51b0-41a3-bbd1-cae34b6f1372.mov

Tested with different site privacy settings too (Coming Soon, Private, and Public) just in case, but still replicated the issue in all cases.

**Comment by cuemarie** [comment]
@jp-imagines Thanks so much!  I was finally able to repro this **when a custom domain is primary** on the simple site.  In that scenario, the template fails to preview as you've described.

Seems similar to this issue: 

- https://github.com/Automattic/wp-calypso/issues/57484 

however I have no trouble opening the Site editor - it's just the homepage preview in this case.

---

Just to be extra sure, can you please try switching your primary site address to the default on that site, and then viewing the homepage once more?

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Simple Site with custom domain set as primary. Console shows:

`Blocked loading mixed active content “http://MYDOMAIN.TLD/?iframe=true&theme_preview=true&frame-nonce=9e11062f83&cachebust=0&calypso_token=852bfaa4-2654-4f67-9b7b-7469d61b1326”`

**Screenshots/Recordings**

https://user-images.githubusercontent.com/27249804/231541002-587ee038-9479-450d-a78b-5ce63c7ba526.mp4

📌 ACTIONS
- Assigned to Cylon

📌 Message to Devs
@Automattic/cylon this looks quite similar to issue #57484 - could the solutions proposed in https://github.com/Automattic/wp-calypso/issues/57484#issuecomment-965428569 work here too?

**Comment by jp-imagines** [comment]
> Just to be extra sure, can you please try switching your primary site address to the default on that site, and then viewing the homepage once more?

Confirmed – switching to the default primary address allows the preview to load on my test site too. 🙁

**Comment by annezazu** [comment]
Is this still a problem? Asking as I couldn't replicate a similar issue on my simple site: https://github.com/Automattic/wp-calypso/issues/76105 and I'm not seeing recent reports here. If it still is an issue, I'd like to escalate it!

**Comment by annezazu** [comment]
Since no one has responded in 24 hours, going to close this out but I'm happy to reopen if it remains an issue.
