### ISSUE TITLE
Restaurant blocks: single product template layout

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#75570]
### Quick summary

"Product Single" template shows the Single product block with an "Upgrade to Blockfied" button.

Clicking on that button allows the single product sub-blocks to be customized, but it completely breaks the single product CSS.

### Steps to reproduce

1. Activate Restaurant-blocks theme.
2. Go to the Site Editor.
3. Open the Product Single template.
4. Click on "Upgrade to Blockfield" on the single product block.
5. Save the changes.
6. Visit a product on the live site.

### What you expected to happen

The theme's layout should show.

### What actually happened

The layout is broken.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

Workaround: It's possible to use CSS to do minor changes instead of editing the single block from the Site Editor.
Could not test on a different site since this is a paid theme.

**Comment by ariel-maidana** [comment]
6193075-zd-woothemes

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closed as outside scope

📌 Message to Author
- Hey @ariel-maidana ! As [Restaurant](https://wordpress.com/theme/restaurant-block/) is a Marketplace theme developed by Organic Themes, technical issues are supported by the theme developers, not here in `wp-calypso`. ([Reference in Public WordPress.com Documentation](https://wordpress.com/support/marketplace-themes/#theme-support), if that helps!)
- You should be able to send the ticket directly to the developers. Working on digging up some guidance on that for you here: p1681239775637029-slack-C0160HSMDQV
