### ISSUE TITLE
Advanced SEO: Move Website Meta to Business Plan

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7560]
As part of advanced seo, move the `Website meta` section to only show if the user has a business plan:

<img width="735" alt="screen shot 2016-08-19 at 10 46 53 am" src="https://cloud.githubusercontent.com/assets/789137/17818880/4b39ec0a-65fa-11e6-9954-e5796f24f9e4.png">

**Comment by vindl** [comment]
It seems like this is already added in https://github.com/Automattic/wp-calypso/pull/7563. I'll continue testing it and see if everything is working as expected.

**Comment by vindl** [comment]
Resolved in #7563.
