### ISSUE TITLE
Calypso: Billing History missing pagination, can't load older receipts

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#75619]
### Quick summary

You can only view at most 5 receipts when viewing history billing page - https://wordpress.com/me/purchases/billing

### Steps to reproduce

1. Visit https://wordpress.com/me/purchases/billing
2. Select "Dates", pick months where you have more than 5 receipts (for example: Older)

### What you expected to happen

Older receipts are shown and can view, print receipts.

### What actually happened

Only the latest 5 from any given months are shown, no option to display/load more receipts.

![image](https://user-images.githubusercontent.com/34882260/231427108-d551f536-428a-4370-9e6c-02775f437107.png)

Workaround: To view older receipts, obtain receipt ID from SA or email, and paste to the end of the link: https://wordpress.com/me/purchases/billing/<receipt_ID>

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Some discussions on Slack: p1681288185103199-slack-C03TY6J1A and p1681288992008169-slack-C02BEP610

Mostly likely the code that adds 5 pagination: fbhepr%2Skers%2Spnylcfb%2Spyvrag%2Szr%2Schepunfrf%2Sovyyvat%2Quvfgbel%2Sovyyvat%2Quvfgbel%2Qyvfg.gfk%3Se%3Qon83762q%23273-og

**Comment by martian77** [comment]
I think it's related to #74975, and I think we've lost the pagination bar. I don't think the number per page has changed, just that we can't page through the history anymore.
