### ISSUE TITLE
Settings: cannot change blog address in Calypso

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#7562]
It should be possible to change your blog address from within Calypso, but this currently links back to the My Blogs page in `wp-admin`.

Steps to reproduce:
1. Start at https://wordpress.com/domains/manage and select a site if prompted
2. Click on the blog name
3. Click the "Edit Site Address" link

<strong>Result:</strong> that link leads to `/wp-admin/index.php?page=my-blogs#blog_row_71207386` and should be available in Calypso instead.

<strong>Aside:</strong> when you do change the blog address, you should be able to register any address that is available to register as a new site, see [1m39s](https://cloudup.com/cg2-TDY9Ohv).

#calypso-gaps

**Comment by lancewillett** [comment]
More feedback on this flow, from a recent #dogfooding session by @beaulebens 

1. After clicking "Settings > Change Site Address" the view needs to force scroll to top.
2. The action in "Settings > Change Site Address" links to the Domain Management page (such as `https://wpcalypso.wordpress.com/domains/manage/example.wordpress.com`), but doesn't actually offer a way to change your free WP.com subdomain without clicking through again. Maybe click through to the edit view directly? So clicking from Settings would go directly to `https://wpcalypso.wordpress.com/domains/manage/lucidityweb.wordpress.com/edit/example.wordpress.com` and remove that middle click.

**Comment by folletto** [comment]
This is a fairly big one imho, especially to new users that might want to take more time to find the right name / URL.

**Comment by drw158** [comment]
wp-admin screenshots

needs a lot of design work

![screen shot 2017-01-23 at 11 11 43 am](https://cloud.githubusercontent.com/assets/618551/22214452/3e2dc5ca-e15d-11e6-914a-ccf67cfa31e2.png)
![screen shot 2017-01-23 at 11 11 16 am](https://cloud.githubusercontent.com/assets/618551/22214453/3e3c2228-e15d-11e6-91cc-338d072216f3.png)

**Comment by mikeshelton1503** [comment]
Some designs were created for this in #2473

**Comment by lancewillett** [comment]
Closing #2473 in favor of this one.

**Comment by jblz** [comment]
Feature shipped in #24265
