### ISSUE TITLE
Stats Widget: Respective deep link for relevant summary pages

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#75638]
Use more specific, deeply related links for different actions. Feedback from https://github.com/Automattic/wp-calypso/pull/75323#discussion_r1162139983.

- `/wp-admin/admin.php?page=stats#!/stats/day/posts/:siteSlug` for `View all posts & pages stats`.
- `/wp-admin/admin.php?page=stats#!/stats/day/referrers/:siteSlug` for `View all referrer stats`.

<img width="567" alt="截圖 2023-04-13 上午12 21 20" src="https://user-images.githubusercontent.com/6869813/231520529-fa5cb9ca-1a3e-4dd9-af63-03bfd725b7fe.png">

**Comment by kangzj** [comment]
fixed in https://github.com/Automattic/wp-calypso/pull/75810
