### ISSUE TITLE
Marketplace Themes: The state is not being refreshed on the new celebration screen

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#75631]
The button `Activate this design` should not be displayed in this case, because it was right after I purchased the theme and theme was already active. This happened before on the old theme page because the state was not getting updated after the purchase and activation.

To reproduce it:
* Create a new site with the Business plan
* Subscribe to Makoney
* You should be redirected to the screen shown below.

![Screen Shot 2023-04-12 at 11 00 55](https://user-images.githubusercontent.com/1234758/231482210-5e18a9bf-993a-4099-a7be-92aa51ce96f1.png)

### Expected behavior

We expect to see the buttons "Customize this design" and "Visit site" after subscribing to the theme.

![Screen Shot 2023-04-12 at 11 14 04](https://user-images.githubusercontent.com/1234758/231485516-d0eb5590-9354-4da5-8631-ea3064bbee9f.png)

**Comment by valterlorran** [comment]
This is still happening. However, I wonder if the behavior has changed because the theme was still inactive after refreshing the page.
Further investigation is required.

**Comment by sixhours** [comment]
Closing this since it hasn't been reported as a user-facing issue.
