### ISSUE TITLE
Consider changing default behavior of gift subscription

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#75644]
### What

In https://github.com/Automattic/jetpack/pull/27374 the default value for "Accept gift subscriptions" was changed to the inverse of the plan's autorenew setting, until the user sets a value for "Accept gift subscriptions"

I received customer feedback in 39490613-hc that the customer would prefer for the default value of "Accept gift subscriptions" to be OFF unless opted-in.

Alternatively, include a message indicating that Gift subscriptions will be accepted when auto-renew is turned off.

### Why

Customer says that accepting gift-subscriptions makes their site look less professional. They didn't expect that turning auto-renew off would turn on accepting gift subscriptions.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- CC: @Automattic/explorers 

📌 Message to Author
- Thanks for sharing the context and this customer's experience, @masperber !

**Comment by lupus2k** [comment]
Hey @masperber, we updated our [support article](https://wordpress.com/support/gift-a-wordpress-com-subscription/).

> By default, the banner will appear on websites near their expiration date (within 5 days for monthly plans, 54 days for annual plans) and have auto-renew turned off. However, you can change this behavior by visiting https://wordpress.com/settings/general and adjusting the Gifting Banner setting. Once you make changes to this setting, the banner will no longer use the expiration window logic.

In case the user wants to deactivate the banner forever before it appears (or fulfills the day's logic), he must activate and deactivate it, in this way the banner will never appear since it will not be changed automatically.

**Comment by lupus2k** [comment]
Closed because we already updated the [support article](https://wordpress.com/support/gift-a-wordpress-com-subscription/) and we showed the steps to deactivate the banner.
