### ISSUE TITLE
Replace my homepage content does not work if Default Homepage is not selected

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#75659]
### Quick summary

When activating a theme, choosing "Replace my homepage content with the [theme] homepage" does not show the theme demo's homepage on the site if _Settings → Reading → Your homepage displays_ is not set to default. This headstart feature is important for helping users to succeed in creating their sites.

If a user selects "Replace my homepage content with the [theme] homepage", then _Settings → Reading → Your homepage displays_ should switch back to 'Default'.

![image](https://user-images.githubusercontent.com/30727666/231627222-edbb79ef-0592-4d3d-8c32-fe2c006e9b2c.png)

### Steps to reproduce

1. Go to Settings → Reading
2. Set _your homepage displays_ to a custom page (not 'default')
3. Go to Appearance → Themes 
4. Activate a theme such as Stewart, Adventurer, or CTLG
5. When prompted, choose "Replace my homepage content with the [theme] homepage."
6. View the site with the new theme active

### What you expected to happen

I expected the site's homepage to match the demo.

### What actually happened

My old content continued to display on the homepage.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – No 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated just as described - the theme homepage switch is not switching to the default template as expected.

### Screenshots/Recordings

**ATOMIC TEST** Twenty Seventeen -> Stewart

![Markup on 2023-04-13 at 13:46:08](https://user-images.githubusercontent.com/27249804/231879310-1a22ba4a-58c1-4b51-a028-22a93d769203.png)

https://user-images.githubusercontent.com/27249804/231879279-42093757-0dd9-4f97-ab10-7ee4109d522d.mp4

---

**SIMPLE TEST** Twenty Twenty-Three -> Stewart

https://user-images.githubusercontent.com/27249804/231880049-ae670a66-40bb-4e2d-afb2-fdc0bcead29c.mov


📌 ACTIONS
- Assigned to Lego

**Comment by obenland** [comment]
@donalirl It looks like Stewart does not have a front page template in its Headstart annotation, even though it has the auto-loading-homepage tag. Adventurer and CTLG don't have annotations either, but they also don't have the tag in their `style.css`. For some reason [they're shown in Calypso as having it](https://wordpress.com/theme/ctlg), though.

@pbking Could You take a look at updating Stewart's Headstart annotations?
@autumnfjeld Who'd be the best person/team to look at why Calypso shows themes in the auto-loading-homepage filter that don't have the `style.css` tag?

**Comment by autumnfjeld** [comment]
@obenland & @donalirl & @pbking 

I don't think auto-loading-homepage tag has anything to do with this issue, though correct me if there is something I am missing.

[Stewart annotations](fbhepr%2Skers%2Sjcpbz%2Qcho%2Qgurzrf%2Sfgrjneg%2Svap%2Surnqfgneg%2Sra.wfba%3Se%3Q5s937q35-og) work fine when creating a new site, I do not think the annotations are the problem. 

I would describe the root problem as this: For the examples shown above the site starts out with "Your homepage displays" set as a static page (not Default).   During theme switch what SHOULD HAPPEN is 
* the `"show_on_front": "posts"` in the [stewart annotation](fbhepr%2Skers%2Sjcpbz%2Qcho%2Qgurzrf%2Sfgrjneg%2Svap%2Surnqfgneg%2Sra.wfba%3Se%3Q5s937q35-og) is respected
*  the reading settings are updated
* the result is that the site's homepage uses the [index.html template from the stewart theme.](https://github.com/Automattic/themes/tree/trunk/stewart/templates).

I don't know why the theme switch process/headstart isn't respecting the Stewart annotations.  Can find out.  I do know that this is broken for every theme switch like this:  
Theme with static home -> theme with no pages (instead a index.html displays as the root page)

All new dotcom themes are made like this, where the root page content is in index.html.  

---------

  If we were to really do this right, theme switch would need to change the site's reading settings according to scenario at play (knowing what the current theme/reading settings are, knowing what they need to be for the new theme/site, knowing what the user really wants to do with their content).  Team Lego has spent much reseach working on this large problem.    
Some reading  if you want a deep dive: 
* Auto loading homepage on theme switch issues  pbAok1-1Yh-p2  -  a P2 from Feb 2021 :( 
* https://github.com/Automattic/wp-calypso/pull/73726
* Thought about improving the Live Preview/Theme Switch experience as a whole: pekYwv-1vZ-p2
* What are the common use cases of the Theme Switch?:  pekYwv-1pj-p2
* Search for "theme switch" in bxlJb-p2

Addressing this a Marvel goal for the next two or so months.

---
## FYI  
* auto-loading-homepage can also be set as a "Theme Feature" in https://theme.wordpress.com/wp-admin/edit-tags.php?taxonomy=theme_feature&post_type=showcase_theme 

![image](https://github.com/Automattic/wp-calypso/assets/5665959/b773d39e-85b5-4388-885f-2f3a4268c523)


---
## In Progress & Pending Work

We are about to change the theme switch  modal, in part for the exact reason of this issue, it isn't helpful and is broken for block themes. 
* [Theme Switch modal : update to make it "less wrong"](https://github.com/Automattic/dotcom-forge/issues/2222).
* https://github.com/Automattic/wp-calypso/pull/77471
* https://github.com/Automattic/wp-calypso/pull/77881/

We are removing these options to choose preserve or not:

![image](https://github.com/Automattic/wp-calypso/assets/5665959/822942fb-dab3-4ad0-b32d-525bf62c07a0)


And then we'll be doing this:
[PT: Live Preview in the Theme Showcase]( pbxlJb-3Uv-p2 

Lots of theme preview / theme switch fixes coming up: p58i-evH-p2#comment-58380

We welcome your HE input and advice as we make these improvements @donalirl 

cc: @Automattic/lego  (please chime in if I missed any details)

**Comment by obenland** [comment]
> I don't think auto-loading-homepage tag has anything to do with this issue, though correct me if there is something I am missing.

The code that does the homepage loading relies on the the tag to determine if it should swap it or not (See `A8C\MU\Full_Site_Editing\Template_First_Themes::update_homepage_template()` and `::has_autoloading_homepage()`).

Themes that don't have annotations with a front page should not have the `auto-loading-homepage` tag. There's a separate tag for blog themes, `blog-homepage`, that correctly sets `show_on_front` and preps any existing front page to be restored later, if the customer changes back to their old theme. D61673-code has a pretty good summary of how that functionality works.

> `auto-loading-homepage` can also be set as a "Theme Feature"

Let's please remove the tag from themes that shouldn't have it.

**Comment by autumnfjeld** [comment]
Thank you for the re-direction and the extra information @obenland.  Very helpful!  Now I better understand the role of the `auto-loading-homepage` tag.  I suspect  that implementing the fixes you suggest above will fix a few different problems we've encountered in theme switch.   cc: @okmttdhr

**Comment by arthur791004** [comment]
> Who'd be the best person/team to look at why Calypso shows themes in the auto-loading-homepage filter that don't have the style.css tag?

I guess this is because the Design Picker in the onboarding flow only showed themes with the `auto-loading-homepage` tag before, so people might add the tag manually, especially for the newly created themes. But now we don't rely on this tag to decide whether it should be shown on the Design Picker. Instead, we're using the `full-site-editing` tag, so we might need to review the theme with the `auto-loading-homepage` but their style.css doesn't have it 🤔 CMIIW

**Comment by autumnfjeld** [comment]
After fixing this, it might be worth a quick P2 post, x-post to HE, as the fix may have a lot of impact on known issues with theme switch.

**Comment by donalirl** [comment]
@autumnfjeld You've summarized the issue well 👍 I've since recreated the same issue on the Iotix and Loudness themes.

From a HE perspective, a typical user expects that when they activate a theme, they will have access to the same content they see on the demo site. The natural flow is to activate the theme, begin replacing the demo text and images for their own, and publish their customized content to the live site.

**Comment by arthur791004** [comment]
Proposing D113778-code to configure the “Homepage Displays” setting to “posts” for any block themes as they should use the template as their homepage. Is there any block theme using the static page as the homepage?

**Comment by okmttdhr** [comment]
> Is there any block theme using the static page as the homepage?

I left a comment in the diff, but some themes have a static page as the homepage, e.g., Appleton, Ames, and Dorna (I think there're more). 

> we might need to review the theme with the auto-loading-homepage but their style.css doesn't have it 

I vote for this!
I think it means that the `auto-loading-homepage` tag is attached to themes that should not have it, so it seems to be better to review it to reduce the complexity in the future.

(If we have a large number of such themes, we might have to think about it though.)

**Comment by fushar** [comment]
We have fixed this issue!

* Stewart is no longer considered as "auto-loading-homepage" because it does not have the corresponding front page setting in the Headstart annotation. The "Your homepage displays" setting will be reset to Default after activating Stewart. See: #79167
* We will clean up Stewart's `auto-loading-homepage` tag in a subsequent initiative; see pbxlJb-4hQ-p2
