### ISSUE TITLE
Define list of theme subject categories

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#75662]
## Description

As discussed in p1680276596845429-slack-C029FM1EH, the theme subject category list in the Theme Showcase could benefit from being a predefined list. The benefit of this approach is that we avoid having unintended subject categories showing in the Theme Showcase, while making sure that predefined subject categories are well curated and populated. 

This is also an opportunity for the Theme Showcase and the Onboarding Design Picker to have the same list of theme subject categories.

| Theme Showcase | Onboarding Design Picker |
| --- | --- |
| ![Image](https://user-images.githubusercontent.com/797888/231646381-2a0decb8-dc1d-46e0-8457-fa17f486f636.png) | ![Image](https://user-images.githubusercontent.com/797888/231646534-f4014284-f283-4027-8570-54c0b77f61eb.png) |

## Acceptance Criteria
- [x] Define the list of theme subject categories with stakeholders.
- [x] The Theme Showcase should only show the list of predefined theme subject categories.
- [x] (Optional) The Onboarding Design Picker should also show the same list of predefined theme subject categories.
- [x] (Optional) The Theme Showcase and the Onboarding Design Picker should retrieve the list from the same source. 
- [x] When done, make a P2 announcement with the allow list and cross post to themedev. Include instructions on how allow list can be be updated.

## Dev Tasks
- [x] D108008-code
- [x] D108257-code
- [x] https://github.com/Automattic/wp-calypso/pull/75900

**Comment by autumnfjeld** [comment]
@taipeicoder Another point of this that Ian & I discussed is ensuring that a "single theme category" doesn't accidentally show up.  This has happened before, where a designer inadvertently added a new category and then it showed up in the DP or TS.  However some categories actually (and sadly) have only one theme. Like podcasts I think.

We discussed adding a check "if subject only has one theme, do not show it in the UI",  but I guess there would have to be exceptions of Newsletter or Podcasts.  But that should be solved by making other themes show under podcasts.  Will check with Ian on that: p1681778682178049/1681726242.675349-slack-C048CUFRGFQ

**Comment by autumnfjeld** [comment]
Also adding that the path forward, the list of theme subject categories, should be decided in collaboration with @alaczek

**Comment by taipeicoder** [comment]
Follow-up discussion in p1681726242675349-slack-C048CUFRGFQ

**Comment by taipeicoder** [comment]
P2: pekYwv-1bL-p2
