### ISSUE TITLE
Newsletter onboarding: change input placeholders to Gray/30

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#75683]
Change input placeholders from Gray/50 to Gray/30.

The current one (Gray/50) makes it easy to mistake it for a filled input.

![Image](https://user-images.githubusercontent.com/25607244/231708067-d3dfb619-5d97-4960-96d4-449c490c91a8.jpg)

**Comment by davewhitley** [comment]
I think we've used Gray 50 as the text color with the minimum contrast allowed. Anything below, like Gray 30 doesn't pass contrast (assuming white background, normal weight, and normal size for the text).

**Comment by simison** [comment]
What else we could do to improve?

- change copy
- remove them entirely
- Turn more light or empty when input is focused
- ?
