### ISSUE TITLE
Newsletter onboarding: align background image to center

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#75684]
The content and the background are not aligned with the center:
[Here's the asset](HSljkKnYECEEegL3DqP2xC-fi-8313_78590).

![Image](https://user-images.githubusercontent.com/25607244/231709678-94b9b955-b90a-4f6e-9af2-dad3af98e296.jpg)

**Comment by lezama** [comment]
¡qué ojo!

Seems that the [background image](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/images/onboarding/newsletter-intro-bottom.png) is like that, maybe on purpose? if not maybe @heavyweight can replace it?

**Comment by heavyweight** [comment]
Nice catch.
Seem that the distance from the left to the center is `711` and from the center to the right `728`.
Making this distance the same will fix the issue. But another one will become more obvious the start of the pattern vertically on the left and the start of the pattern vertically on the right won't be at the same starting point (16px difference). But I think this is ok.

<img width="965" alt="Screenshot 2023-04-24 at 12 08 48" src="https://user-images.githubusercontent.com/7000684/233967263-be2885c3-6f1a-47de-9351-55f043da854a.png">

**Comment by heavyweight** [comment]
Spin up a quick PR for this here https://github.com/Automattic/wp-calypso/pull/76126 to see if that's ok.
@crisbusquets can you check it out using the PR link?

**Comment by crisbusquets** [comment]
Hi @heavyweight !

Sorry I missed this comment. I checked it, now it's ok :) Thank you!
