### ISSUE TITLE
Newsletter onboarding: fix textarea line-height

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#75688]
Slightly misaligned placeholder in textarea.
A regular input has a `line-height: normal` and the textarea has `line-height: 20px`, which optically misaligns the content.

The right one should be`line-height: normal`.

**Comment by edanzer** [comment]
@crisbusquets - I wanted to confirm that the relevant text area input here is the one for description on the Setup page? 

That one does have line-height: 20px. I've updated that to line-height: normal. Below is a side by side comparison. Also just wanted to confirm this is what we're going for. Thanks!

<img width="1199" alt="line-height" src="https://github.com/Automattic/wp-calypso/assets/21228350/8ef1deb7-28cc-42f2-8223-8ec2b16ecd9d">

**Comment by crisbusquets** [comment]
Hi @edanzer, thanks for tagging me :)

Oh wow. Now that I see it with more text, I think we should keep it at `20px`. `Normal` makes it difficult to read, it feels too tight.

I originally created this issue because when the `textarea` input only has one text line, it looked a bit misaligned when compared to regular inputs.

![image](https://github.com/Automattic/wp-calypso/assets/25607244/e52b6e4c-d12d-4483-95e6-f0a30eef3f3b)

**Comment by simison** [comment]
Shall we keep as-is? Feel free to re-open if we should change something! :-)
