### ISSUE TITLE
Reskinned Portal: Redirect sites & settings page to Calypso Portal.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#75698]
When user accesses `/email-subscriptions/?option=(blogs|settings)&locale=(ar|nl|pt-br|zh-cn|...)`, they should be redirected to `/subscriptions/(sites|settings)/(ar|nl|pt-br|zh-cn|...)`.

The tab URL for Sites & Settings on reskinned portal should also go to the Calypso Portal's url.

**Comment by yansern** [comment]
Patch is ready D107751-code.

**Comment by mashikag** [comment]
Resolved by: D107751-code
