### ISSUE TITLE
Launchpad: Update font title (desktop & mobile) according to stepper flows

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#75692]
As [mentioned here](https://github.com/Automattic/wp-calypso/issues/75019), we will be adjusting the overall layout typography sizes to ensure they are the same on all steps of the newsletter onboarding flow.

Therefore, it makes sense to update Launchpad accordingly 

[[Figma Design](9wpoYJrMlYKAKUYvVBMN74-fi-3172_39026)](9wpoYJrMlYKAKUYvVBMN74-fi-3172_39026)

![Image](https://user-images.githubusercontent.com/7931304/231726230-ab11cdce-0dba-471a-af48-3dfe16fd723c.png)

**Comment by simison** [comment]
@nuriapenya can these sizes be updated across all the _launchpads_, not just newsletter? (I haven't checked how other flows look like in production)

**Comment by nuriapenya** [comment]
@simison Ideally, yes, all the Launchpads should be updated accordingly, so we don't have inconsistencies. I'm assuming the Zap team will only take care of the Newsletter part, right?

**Comment by simison** [comment]
> I'm assuming the Zap team will only take care of the Newsletter part, right?

No, I will update to all flows at once. I don't think we should have any flow-exceptions on components like these, unless for branding reasons (like VideoPress/Sensei).
