### ISSUE TITLE
Stats: fix "View subscribers" margin

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#75707]
These spacings are too tight compared to `2023 in review` ones.

![Image](https://user-images.githubusercontent.com/25607244/231776179-16657ee5-ae2c-4703-b61f-dbbd3aa87fcb.png)

I'd suggest modifying them so:

* `subscribers-section` should have `padding: 32px` at the top and bottom
* `highlight-cards-heading` should have `margin-bottom: 16px` (currently it doesn't have any margin)

So the final result is:

![Image](https://user-images.githubusercontent.com/25607244/231777392-103af2d0-064e-4ac4-a70b-53f1c1bbe634.png)

**Comment by jsnmoon** [comment]
This was a goof on my part during #75653, where I unintentionally added a bottom border line beneath the heading. I'll have a fix for this shortly.
