### ISSUE TITLE
`/subscriptions/pending`: Create API endpoint to retrieve list of pending site subscriptions.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#75713]
**This API endpoint should:**
- Return a list of pending subscriptions.
- Only for external users as logged-in users don't need to confirm their subscriptions.
- Request header may return the total count but not necessary.
- No pagination needed.
- It should include:
  - site_id
  - site_title
  - site_icon
  - site_url / domain
  - date_subscribed
  - organization_id

**Comment by mashikag** [comment]
Resolved by: D107879-code
