### ISSUE TITLE
Launchpad: URL has misplaced copy icon

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#75720]
### Quick summary

Icon is off when hovering:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/87168/231824846-f90600d9-8119-421c-958c-42aaf06d47a4.png">

Looks fine on shorter URL:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/87168/231874082-6318c788-e5a3-44d7-9759-f2c4949af034.png">

### Steps to reproduce

Create a new site to get the launchpad, and hover the URL area at the launchpad.

### What you expected to happen

Better spacing

### What actually happened

Too close to the "customize" button

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

on Firefox

**Comment by simison** [comment]
cc @nuriapenya  @Addison-Stavlo could Cylon take a look? Thx!

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Only tested on AT site bc I couldn't quite sort out how to trigger the Launchpad on my unlaunched simple sites, but they appear to behave the same way based on the report above and my test.

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/231896488-13162d95-e2ce-4c11-b8a5-75a5af75cc81.mp4

📌 ACTIONS
- Assigned to Cylon
