### ISSUE TITLE
Stats: Deprecate "stats/horizontal-bars-everywhere" feature flag

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#75742]
Deprecate "stats/horizontal-bars-everywhere" feature flag.

**Comment by grzegorz-cp** [comment]
Additionally, remove unused CSS class `stats__module-wrapper--${ path }` from SCSS files in `grid-layout.scss` (noticed [here](https://github.com/Automattic/wp-calypso/pull/75750#pullrequestreview-1385549061))

**Comment by jsnmoon** [comment]
I believe this is done! 🚀
