### ISSUE TITLE
Page Break Block - Learn More link is incorrect

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#75758]
### Quick summary

The Page Break block has a block description with a Learn More Link, but the link is to the wrong page.

Current link: https://wordpress.com/support/site-editing/theme-blocks/post-content-block/
Correct link: https://wordpress.com/support/wordpress-editor/blocks/page-break-block/

<img width="597" alt="image" src="https://user-images.githubusercontent.com/30727666/231980833-b1307aca-a871-4100-b781-169dada17265.png">

### Steps to reproduce

1. Open the editor
2. Insert a page break block
3. Open the sidebar settings
4. Click 'Learn more'

### What you expected to happen

To see this page: https://wordpress.com/support/wordpress-editor/blocks/page-break-block/

### What actually happened

I saw this page: https://wordpress.com/support/site-editing/theme-blocks/post-content-block/

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Yep, looks like that points to the wrong guide! Thanks for reporting.

📌 ACTIONS
- Assigned to Vertex
