### ISSUE TITLE
Newsletter onboarding: change first step copies

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#75761]
Old:

`Unlimited subscribers. Beautiful design. And everything you need to grow your audience. Powered by WordPress.com.`

New:

`Everything you need to reach and grow an audience, with the power and permanence of WordPress.com.`

**Comment by simison** [comment]
Changing here: https://github.com/Automattic/wp-calypso/pull/75762 — I need to send it for translation before deploying.

"permanence" might be extra we can drop to simplify; not such a well-known word?

It could also just be "Everything you need to reach and grow an audience.". It's clearly within and under the WP.com brand already, so we don't necessarily need to highlight WP.com here.
