### ISSUE TITLE
Plans: Picking a monthly plan quickly flashes the annual plans grid

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#75778]
### Quick summary

When selecting a monthly plan, specifically on `/start/hosting`, the screen briefly shows the annual plans before proceeding to the domains step.

https://user-images.githubusercontent.com/26530524/232076941-f300ca1b-230a-4975-83fd-6416790a1861.mov

### Steps to reproduce

1. Browse `/start/hosting`;
2. Switch to monthly plans;
3. Click any monthly plan;
4. Check that the screen rapidly flashes the annual plans before proceeding to the domains step.

### What you expected to happen

The user should not see the annual plans flash.

### What actually happened

The user sees the annual plans for a brief period.

### Impact

All

### Available workarounds?

There is no user impact

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on https://wordpress.com/hosting/ – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm able to replicate the behavior when starting from WordPress.com/hosting/ - see below

Replicated in Firefox 112.0.1 (64-bit)

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/233225477-c2f432ff-48d9-4097-bee5-6773c0cd24e2.mp4

Happens at the 0:10s mark in the recording above

📌 ACTIONS
- Assigned to ~~MarTech~~ Build (based on recent project board updates)
