### ISSUE TITLE
Add a Newsletter access levels to posts on the posts page

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#75788]
In the Calypso posts list page, add a badge to the posts with Newsletter access when a post is marked as newsletter.

Mock-up:

<img width="300" alt="Screenshot 2023-04-18 at 13 27 14" src="https://user-images.githubusercontent.com/790558/232763490-31f1ae77-0a25-4eb8-bbea-6c440fbeff7e.png">

**Comment by millerf** [comment]
@romarioraffington, I added a mockup in the description in case this was not clear enough

<img width="300" alt="Screenshot 2023-04-18 at 13 27 14" src="https://user-images.githubusercontent.com/790558/232763490-31f1ae77-0a25-4eb8-bbea-6c440fbeff7e.png">

**Comment by romarioraffington** [comment]
I think we should also consider the WPCOM redesigned experience here as well

<img width="1274" alt="Screenshot 2023-04-18 at 10 48 51 AM" src="https://user-images.githubusercontent.com/7076981/232832305-f9021902-6517-469a-9c00-16f5d40803af.png">

**Comment by millerf** [comment]
> I think we should also consider the WPCOM redesigned experience here as well
> 
> <img alt="Screenshot 2023-04-18 at 10 48 51 AM" width="1274" src="https://user-images.githubusercontent.com/7076981/232832305-f9021902-6517-469a-9c00-16f5d40803af.png">

@romarioraffington , yes, that is why I meant by Calypso. I know I took the jetpack table for the mockup, it is a mistake of mine. But having both is actually even better.

Please ping me in the answers otherwise I don't get notified...

**Comment by romarioraffington** [comment]
> @romarioraffington , yes, that is why I meant by Calypso. I know I took the jetpack table for the mockup, it is a mistake of mine. But having both is actually even better.
> 
> Please ping me in the answers otherwise I don't get notified...

@millerf any ideas as to where we should include the newsletter access level for the Calypso experience?

**Comment by millerf** [comment]
> @millerf any ideas as to where we should include the newsletter access level for the Calypso experience?

Following the rest of the data should be fine?

<img width="300" alt="Screenshot 2023-04-20 at 12 58 01" src="https://user-images.githubusercontent.com/790558/233347194-1f620dac-686f-49b3-b36a-89fad3d78b4e.png">

**Comment by millerf** [comment]
@romarioraffington Please put this on hold while @crisbusquets is looking into it. See this thread: p1682059082275009-slack-C052XEUUBL4

**Comment by crisbusquets** [comment]
I'm currently working on this. Small screen sizes will be a challenge, so I'm taking the time to ensure that the final design works with any situation.

**Comment by millerf** [comment]
@romarioraffington Could you please implement the new alert design once you are done with your actual task? You will find them in the `How we (quickly) can improve this` part of: peKye1-x-p2. They will replace the "info" and the "warning" we have at the moment.

This alert is used on wpcom: peKye1-x-p2#comment-11, so there must be a component you can reuse for those 🥳



The design for the access level in the posts list should be available some time later this week: peKye1-x-p2#comment-9

**Comment by crisbusquets** [comment]
@millerf is there a reason why we use "Subscribers only" instead of "Subscribers"?

**Comment by millerf** [comment]
> @millerf is there a reason why we use "Subscribers only" instead of "Subscribers"?

@crisbusquets  Not that I know of...

**Comment by millerf** [comment]
@romarioraffington We have the designs:

<img width="800" alt="Screenshot 2023-04-26 at 18 54 38" src="https://user-images.githubusercontent.com/790558/234648242-162e4971-c044-48b8-8ce5-47b735e6c3aa.png">
<img width="800" alt="Screenshot 2023-04-26 at 18 54 32" src="https://user-images.githubusercontent.com/790558/234648224-0f85dcc6-4493-471b-9894-8282e75cff09.png">

The icon is called "mail", if it helps to get it from an icon set (not sure where the "private" icon is sourced)...

Icon:
![mail](https://user-images.githubusercontent.com/790558/234648832-1bd15026-bac1-4cec-8e79-5436a8bbdae5.png)

Would you need anythign else, please let @crisbusquets  know.

**Comment by crisbusquets** [comment]
Hi there @romarioraffington @millerf !
The other "private" icon is called `aside`. But afaik that's already implemented.
Let me know if you need anything else, and feel free to ping me when there's something I can stress-test.

Thank you!

**Comment by romarioraffington** [comment]
The Calypso PR can be found in https://github.com/Automattic/wp-calypso/pull/76382

**Comment by millerf** [comment]
Code looks good. We now need to harmonise behaviour between JP and Calypso and choose between Public and everybody. See this [comment](https://github.com/Automattic/jetpack/pull/30172/files#r1181613125)
