### ISSUE TITLE
Remove the domain upsell while user is in the write flow

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#75794]
The current domain upsell is not a great strategy while the user is at the new write flow:

![Image](https://user-images.githubusercontent.com/1044309/232128834-981cf6a8-d797-45f7-8ec0-190da0ef2a10.png)

### Requirement

- [ ] When having the new write flow flag `showLaunchpad=true` we don't see the domain upsell

**Comment by paulopmt1** [comment]
Since we moved to no iFrame version, I believe we don't need to work on this anymore @candy02058912. Just be aware once we re-add it in the future.

**Comment by candy02058912** [comment]
Closing this issue per the comment [above](https://github.com/Automattic/wp-calypso/issues/75794#issuecomment-1511464281).
