### ISSUE TITLE
Signup: Improving password selection 

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#758]
Originally reported by @breezyskies.

We're not doing the best job right now of helping users pick a good password -- our password rules are obscured until they enter a bad password, and the design doesn't really encourage a better password so much as make it a hurdle to jump over. We've also seen users struggle with this in usability testing.

I've started playing with some ideas for reducing friction in password selection here: https://wpcomnux.herokuapp.com 

Obligatory screenshot (but really, go play with the prototype):
![passwordhelper](https://cloud.githubusercontent.com/assets/3011211/9695895/d69e54b8-531b-11e5-883e-0d1df9f49012.png)

There are several options here, ranging from very simple hints in the placeholder text, to more complex checklist interactions:

1) Simple placeholder text hint
2) Help text, using copy from old signup + generate password link
3) Counter + generate password link
4) Interactive help text (changes green as you meet each requirement) + generate password link
5) Interactive rule list (fades out as you meet each requirement)
6) Strength meter + generate password link

(I'll also be posting ideas for username selection / suggestions soon.)

Another thing I think would be worth testing: removing the password step from the main NUX flow entirely and having the user choose their password during email confirmation.

Feedback? Thoughts on these designs?

**Comment by fabianapsimoes** [comment]
@ranh had some ideas on improving the feedback through messaging, and reviewing the password experience.

----

I love these ideas to improve feedback on signup. I agree with @scruffian's sentiment though: the password experience is inherently broken, and the more we complicate the design, the more we expose the inherent flaws. So IMHO, less is definitely more here:

* Generating a password on the spot is essentially the same as removing passwords from the flow altogether, just without any of the benefits. New users still have to take an extra step on signup, and existing users are still sidetracked to a "forgotten password" flow. 
* Requiring special characters or numbers increases complexity and can hurt engagement, but does not improve security. 
* Same goes for showing the detailed requirements on first view. At best it can save some users from their first failed attempt. Otherwise it increases complexity and can hurt engagement by intimidating every visitor from the get-go.
* Adding UI to the immediate area around the field makes it harder to read and harder to use, and is probably too English-centric and not i18n-friendly.

Also note that the requirements for signing up to WordPress.com now are actually much simpler than what you mentioned in the design. Are you suggesting changing the requirements? Or simply experimenting with different requirements for the mockup?

Seems that the main requirement is eight characters minimum. A password like `aunhikle` is acceptable.  The requirements are a bit more involved and include a blacklist. But that seems to be the main idea.

**Comment by mikeshelton1503** [comment]
In recent user testing for WordPress.com Domains this issue came up again. In addition to there being no guidance about requirements initially, the error state doesn't provide clear instructions: 

![image](https://cloud.githubusercontent.com/assets/12596797/24455979/82fb8be4-145f-11e7-8d13-4610668e8e7a.png)

**Comment by supernovia** [comment]
This came up in a [tweet](https://twitter.com/realpratiknikam/status/1023998893938360320) today. as well. Can we require better passwords? If they're all text, require a longer length, etc?

**Comment by cathymcbride** [comment]
No movement or user confusion since 2018. Closing....
