### ISSUE TITLE
Stats: Subscribers page - add Subscribers highlights

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#75855]
Replace the placeholder `Annual highlights` (aka YYYY in review) from the `Subscribers` page with the new highlights section.

# Designs
* Widescreen
![Image](https://user-images.githubusercontent.com/112354940/232655784-1b26009f-b6ca-45c9-b259-c73a092fc4e8.png)

* Mobile
![Image](https://user-images.githubusercontent.com/112354940/232655834-161427c7-f747-4289-905c-53eb03eaf382.png)

# Development
* Verify if all data points are already available - e.g. free and paid email subscribers
* Create new components to display data and place it in Storybook with the shared component (use Storybook with test data set)
* Add the new component to the Subscribers page
* Verify with the designers if the tooltip content is correct

Before starting the task, consider a further breakdown of the task and which step could result in a partial pull request.

**Comment by jsnmoon** [comment]
I believe this is complete!
