### ISSUE TITLE
Design Picker: mShots viewport issues

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#75858]
## Description

As discussed in p1681751382005269-slack-C048CUFRGFQ, there are some mShots images that have viewport issues. For instance:

Background image being cut off:
![Image](https://user-images.githubusercontent.com/797888/232670600-b87a411b-95a1-4e8b-880b-74c7282d8f50.png)

The block cover not having its `vh` applied:
![Image](https://user-images.githubusercontent.com/797888/232670693-787440d7-72e6-43ec-a916-acd8c3622e2d.png)

## Acceptance Criteria

- [ ] Improve the viewport of the preview page that mShots takes snapshots from.

**Comment by autumnfjeld** [comment]
Thank for creating this! Was on my todo list and its already been done!!   💟

**Comment by taipeicoder** [comment]
Closing via #77052
