### ISSUE TITLE
Site Assembler: Continue button to create site responds to right-click like a left-click.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75863]
### Quick summary

Right-clicking on the "Continue" button in the Site Assembler overview results in a behavior identical to a left-click.

### Steps to reproduce

1. navigate to `https://wordpress.com/setup/site-setup/patternAssembler?siteSlug={testSite}`.
2. right-click on the "Continue" button.

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/6549265/232692604-d0eb5c97-ff08-4bc1-b3f1-f961ed790d7b.png">

### What you expected to happen

Button should not respond to a right-click.

### What actually happened

The button responds to right-click as if it was a left-click.

https://user-images.githubusercontent.com/6549265/232692913-80914f15-c5a6-468e-9679-684ce8f1119a.mov

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes

Browser: Microsoft Edge

**Comment by worldomonation** [comment]
@Automattic/lego This is not a high priority item (as the workaround is easy), but I thought you'd like to know.

**Comment by arthur791004** [comment]
Oh, I can take on this. We want to avoid people misclicking on the Continue button when they come back from another screen, so we use `onMouseDown` event to deal with it and it leads to the right-click also works

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/75865. Thanks for the report!
