### ISSUE TITLE
Agency Dashboard signup: issues with company website field

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#75880]
### Quick summary

When signup up to become an agency partner, one must provide their company website URL. That field doesn't seem to accept full URLs	

### Steps to reproduce

1. While logged in to WordPress.com, go to https://jetpack.com/for/agencies/
2. Click on the CTA, and start the signup flow.
3. As company website, enter a full URL, e.g. `https://jeremy.hu/`
4. When submitting the form, you will get an error that the company website field is required.
5. You can also see the error in the js console:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/426388/232750345-053cef4f-c08b-4a32-b45c-45ce6828efe5.png">

### What you expected to happen

I would have expected the form to be submitted with no issues

### What actually happened

I had to remove `https://` to be able to submit the form with no issues.	

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

- Google Chrome

**Comment by yashwin** [comment]
I tried reproducing this issue. 

`https://jeremy.hu` is still a valid input. But invalid with the trailing `/`. `https://jeremy.hu/` is rejected by the API (invalid) which should ideally be valid

**Comment by jeherve** [comment]
Ah nice catch!

**Comment by yashwin** [comment]
@jeherve - We have fixed this. Could you please review it - D108449-code

**Comment by yashwin** [comment]
This is fixed
