### ISSUE TITLE
Jetpack Agency dashboard: JetBackup info displayed on backup page

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#75884]
### Quick summary

https://cloud.jetpack.com/plugins/backup displays information about the wrong plugin

### Steps to reproduce

1. Start with a WordPress.com account where you've applied to access the agency dashboard.
2. Go to https://cloud.jetpack.com/plugins/manage
3. Click on the link to access backup plugin updates, and load https://cloud.jetpack.com/plugins/backup
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/426388/232760462-d55ea9fd-1e44-4928-af09-df23162f99ee.png">

The page includes information about Jetpack VaultPress Backup, but the name and icon is wrong:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/426388/232760389-3ec8d429-cc8e-4934-90a2-596a289aa1be.png">

### What you expected to happen

I would have expected this to be about Jetpack VaultPress backup, with no other plugins.	

### What actually happened

The plugin name and icon is not the correct one.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by yashwin** [comment]
**Update** - Please ignore this comment as I'm following the conversation about this on slack now 

------

@jeherve - Thanks for reporting this.

However, I'm unable to reproduce this. 

As per the screenshot, the slug of `JetBackup` is `backup`, and all the details loaded here are correct except the title in the breadcrumb and the title next to the icon are wrong. 

This is what I see on the plugin details page when I click on JetBackup from the `Plugins` page, which is correct

<img width="1441" alt="Screenshot 2023-04-26 at 11 45 59 AM" src="https://user-images.githubusercontent.com/10586875/234485756-b787a901-1eb0-4a6b-9031-ef0df2708deb.png">

This is how the details page of  `Jetpack VaultPress Backup` looks like

<img width="1441" alt="Screenshot 2023-04-26 at 11 47 40 AM" src="https://user-images.githubusercontent.com/10586875/234486083-19c1e936-ac19-447e-ae5a-afd30672e988.png">

Could you please try it once more and let us know if you are still able to face this issue?

**Comment by jeherve** [comment]
Related discussion: p1681816553723359-slack-C02RE7J6KEU

This was related to me running Jetpack Backup in the Jetpack monorepo, where it lives under the `backup` slug. Closing.
