### ISSUE TITLE
Subscription Management: Add paid subscriptions property on comments API endpoint.

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#75892]
The comments API endpoint needs to return property (or properties) the indicate that the subscription is a paid subscription.

**Comment by phcp** [comment]
@Automattic/apex I'll keep it as blocked for now. We need clarification on filtering by Paid subscriptions, is this information ready to be retrieved on the API side? There is a draft implementation for the API, it's open to discussions, D108411-code.

**Comment by yansern** [comment]
Resuming work on this. Assigned to [Subscription Management: Paid Subscriptions Integration](https://github.com/Automattic/wp-calypso/milestone/428) milestone.

**Comment by yansern** [comment]
D112430-code

**Comment by JuanLucha** [comment]
Closed by D111748-code
