### ISSUE TITLE
FSE: Submenus with background color inherit CSS on pages where list block is present

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#75908]
_2023-04-18 Update - Findings show that this is not unique to Bitácora, but to any FSE theme where the submenu has a background color.  Relevant Gutenberg report: https://github.com/WordPress/gutenberg/issues/49445 -cuemarie_

### Quick summary

Bitácora Theme shows submenus with additional Padding when the Page has a list of items added using **List Block.** The submenu appears correctly when the page without a **List Block** is viewed.

Please see this image for reference: 

### Steps to reproduce

1. Activate Bitácora theme.
2. Now add submenu items in the menu
3. Add a new page with **List Block**
4. Now view the page with the **List Block** to see the menu appear with additional padding.submenu items

### What you expected to happen

The menu should appear the same as it appears when on a page without a **List Block.**

![image](https://user-images.githubusercontent.com/8070771/232826142-1d08f783-cf0f-4991-bdff-42a28efda711.png)

### What actually happened

The submenu appears with additional padding.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by syhussaini** [comment]
user on this ticket 6211163-zen is impacted with this issue.

**Comment by cuemarie** [comment]
Very similar issue reported here on Munchies theme: 

- https://github.com/Automattic/wp-calypso/issues/75244

I've been having trouble replicating but perhaps between the two I can figure this out :)

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this on a brand new Free site, created today:

https://user-images.githubusercontent.com/27249804/232927228-998e375f-0f5e-474f-8af7-f48f346c4592.mp4

Looks like it's stemming from this inline CSS:

```
ol.has-background, ul.has-background {
  padding: 1.25em 2.375em;
}
```

Which is overriding the default padding setting for the .wp-block-navigation ul:

```
.wp-block-navigation ul, .wp-block-navigation ul li {
  list-style: none;
  padding: 0;
}
```

![0MZj5V.gif](https://user-images.githubusercontent.com/27249804/232927496-1cf055a4-0dc2-461b-a0b2-eb7e4e6290fc.gif)

Same result on AT and Simple, tested with CTGL, Vetro, and 

**AT Site, Vetro**

![UIQMLk.gif](https://user-images.githubusercontent.com/27249804/232929224-fe7ee6e1-6cda-4e5d-9c90-679e47bbe907.gif)

**Simple Site, CTGL**
![vk7dPs.gif](https://user-images.githubusercontent.com/27249804/232928687-f99811f6-1fb3-4d22-9c07-c8fb8f75febc.gif)

**Simple Site, TT3 (Default)
![Ry35sZ.png](https://user-images.githubusercontent.com/27249804/232929407-b5c0c89e-673c-45bd-ab60-0a05e2fd0d58.png)

📌 ACTIONS
- Assigned to Cylon
- Looks like this was reported here as well: https://github.com/WordPress/gutenberg/issues/49445

**Comment by cuemarie** [comment]
User report from #75244, who would like to be notified when this is resolved:

- 6158230-zd-woothemes

**Comment by cuemarie** [comment]
Ran into this here: 42217934-hc

Provided the following CSS as a workaround:

```
/* fix submenu padding bug | xxx-hc [XX] */
.wp-block-navigation ul, .wp-block-navigation ul li {
  list-style: none;
  padding: 0;
}
```

**Comment by cuemarie** [comment]
Also related: 

- https://github.com/WordPress/gutenberg/issues/50342

**Comment by cuemarie** [comment]
Created a more generalized core report here: 

- https://github.com/WordPress/gutenberg/issues/50486

**Comment by ariel-maidana** [comment]
6267568-zd-woothemes
Please notify the user once this issue is fixed.

**Comment by ariel-maidana** [comment]
Another case here: 6279660-zd-woothemes
Please let the user know once this issue is fixed.

**Comment by sourourn** [comment]
Another case here: 6318112-zd-woothemes
Please let the user know once this issue is fixed.

**Comment by jp-imagines** [comment]
Came across another instance in 6569091-zd-woothemes, gave CSS to fix. Follow-up not needed.

**Comment by CodeAllNightNDay** [comment]
Encountered the issue here:
6773296-zen

Gave CSS for the workaround.

**Comment by eduardozulian** [comment]
Another report in 7391190-zen, using the Munchies theme. Shared the following CSS as a workaround:

```
ul.wp-block-navigation-submenu.has-background {
    padding: 0;
}
```

**Comment by annezazu** [comment]
Digging through layers of reports on the Gutenberg GitHub repo and this should have been resolved: 

https://github.com/WordPress/gutenberg/issues/50486#issuecomment-2225715338

I am going to close this out but let's **please** reopen and/or flag for me if folks can still replicate this. Thank you!
