### ISSUE TITLE
Post Carousel Block not available on new Simple Sites

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#75916]
### Quick summary

Some simple WordPress.com sites cannot insert the [Post Carousel Block](https://wordpress.com/support/wordpress-editor/blocks/posts-carousel-block/), as the block will not show up in the Block Inserter.

![hULrB-o_bl.png](https://user-images.githubusercontent.com/14153300/232843358-ce8bff84-9b16-4f7c-83c9-b0b11e173ff3.png)

It's as if the block was retired for simple sites, and it's only now available on Atomic or sites that previously used it.

### Steps to reproduce

1. Create a new simple site on WordPress.com
2. Open a post or page
3. Try to add the Carousel Block by typing /carousel or searching the block inserter

### What you expected to happen

The block should show up as a result in the block inserter

### What actually happened

The block doesn't show up, and there's no way to add it to new sites.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

This is a WP.com issue, and it's not affecting Newspack customers p1681834908556279-slack-C015W6BES8J and is likely caused by WP.com-specific code

**Comment by cuemarie** [comment]
Hey @liviopv ! I just tried replicating this on a brand new free test site, and the `Post Carousel` block appeared there for me:

![Markup on 2023-04-18 at 10:49:07](https://user-images.githubusercontent.com/27249804/232861767-bd667d9b-2a96-4ada-9663-77cb036b6137.png)

On the site where this is happening, can you see if the Post Carousel block appears under **Editor Preferences > Blocks > Visible Blocks**?

![FooZil.png](https://user-images.githubusercontent.com/27249804/232861929-04def5ab-014e-4424-9e0e-582a7f5f11e7.png)

**Comment by dsas** [comment]
That fixed it for me @cuemarie. It's probably the same underlying cause as https://github.com/Automattic/jetpack/issues/28523 - see https://github.com/Automattic/p2/issues/6103

**Comment by liviopv** [comment]
@cuemarie That was it!

What's weird is that it is not showing up by default on the Page Editor. This block was not created as an FSE Block, so it doesn't make sense that it would be contained to the Site Editor.

**Comment by cuemarie** [comment]
Glad that was it!  I'll close this in favor of https://github.com/Automattic/p2/issues/6103 , thanks for sharing your thoughts over there @liviopv , and for that quick find, @dsas!
