### ISSUE TITLE
Stats: Add TS to the Subscribers page component

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#75925]
Following updates for the Subscribers page done in #75317, add TypeScript to the page.
This is also a good opportunity for cleanup in component naming and location.

# Development
- [x] add TS to `wp-calypso/client/my-sites/stats/stats-subscribers-page/index.jsx`
- [x] delete `wp-calypso/client/my-sites/stats/stats-subscribers/index.jsx` (old component used before the page was created)
- [x] rename `wp-calypso/client/my-sites/stats/stats-subscribers-page/` to `wp-calypso/client/my-sites/stats/stats-subscribers/`
- [x] rename `wp-calypso/client/my-sites/stats/subscribers-section` to `wp-calypso/client/my-sites/stats/stats-subscribers-chart-section`
- [x] rename the definition and imports from `SubscribersSection` to `SubscribersChartSection`

**Comment by jsnmoon** [comment]
All items are in progress at #76556.
