### ISSUE TITLE
Showcase: "Unlock this style" does not revert to "Activate"

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#75946]
# Description

Originally reported by @ianstewart p1680545433925719/1680545224.994839-slack-C048CUFRGFQ
![image](https://user-images.githubusercontent.com/5665959/233012807-deb8281c-1bad-4699-b3d6-57de764fafa8.png)

Acceptance Criteria / Dev Tasks
 The button “unlock this style” should revert to "Activate" when you click on to a style variation then you click back on the default variation afterwards.

@Automattic/lego

**Comment by taipeicoder** [comment]
This is fixed via #75367 🙂
