### ISSUE TITLE
Site settings: Start Over page UX issue

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#7594]
Starting at URL: https://wordpress.com/settings/start-over/

Users often contact requesting their site to be emptied. We added a text link to emptying instructions, but it's very understated, with a larger button to contact support instead. It may be better (and faster for users) to push them to the Empty Site support documents instead of contacting support. Perhaps giving the Empty Site instructions equal weight with a button would cut down on those requests, and decrease the time the user needs to spend on getting their site emptied.

Something like this?

![screen shot 2016-08-22 at 10 59 56 am](https://cloud.githubusercontent.com/assets/8002138/17865498/a7defaf4-6857-11e6-8a97-41f0ac778c61.png)

@jeremeylduvall

**Comment by jeremeylduvall** [comment]
Closed in #7786
