### ISSUE TITLE
Cover block contents scroll over sticky/fixed header 

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#75986]
### Quick summary

Initially reported in 42176808-hc. 
This may be related to the recent Gutenberg 15.6.0 release – the customer I spoke with said the issue wasn't present earlier today (April 19).

Cover block contents (the `.wp-block-cover__inner-container` element) have a z-index of `32`, which is much higher than Group blocks assigned the "Sticky" position (which have a z-index of only `10`). The contents of cover blocks can appear on top of sticky elements as a result.

### Steps to reproduce

1. Start with a site with a Site Editing theme active.
2. In the Site Editor, create a Group block with the "Sticky" position. (It may be helpful to set a background color on the Group, or add some larger content to it, so it's easier to see where its contents lie.)
3. Somewhere below the sticky Group, add a Cover block with some form of content.
4. View the site, and scroll.

### What you expected to happen

Cover block content should scroll "beneath" the sticky Group (i.e. the sticky Group should appear on top of all content as you scroll).

### What actually happened

The contents of the Cover block have a higher z-index, so they appear on top of the sticky Group:

https://user-images.githubusercontent.com/5630717/233200853-d68c11f4-13f0-4f84-94eb-a6e99e330ac7.mov

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Only tested on Simple so far, on both Twenty Twenty-Three and Russell. CSS can be used to either set the sticky Group to have a higher z-index (>32) or to have the Cover block contents to have a lower z-index (<10) as a workaround.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described on AT, Simple, and Self-Hosted running Gutenberg 15.6.0.

#### Screenshots/Recordings

**Self-Hosted on Gutenberg 15.5.1**

https://user-images.githubusercontent.com/27249804/233214536-8049466b-3ade-43fe-8cbe-95dd732e987e.mp4

**Self-Hosted on Gutenberg 15.6**

https://user-images.githubusercontent.com/27249804/233214766-e91bc38d-14ba-4b2f-988f-a442de262fff.mp4

📌 ACTIONS
- Assigned to Cylon
- Escalated internally to see if there's anything that can be quickly caught: p1681944210933779-slack-CBTN58FTJ

📌 Message to Author
- Thanks for the quick report, @jp-imagines !

**Comment by cuemarie** [comment]
Reported here: 

- https://github.com/WordPress/gutenberg/issues/49939

**Comment by cuemarie** [comment]
https://github.com/WordPress/gutenberg/pull/49943 resolves this in Gutenberg [15.6.1](https://github.com/WordPress/gutenberg/releases/tag/v15.6.1)
