### ISSUE TITLE
Menus: Menu UI doesn't show all categories when adding menu items

### ISSUE THREAD

**Issue by joanrho** [Automattic/wp-calypso#7598]
A user (2785599-t) brought to my attention that his list of 30+ categories were not all viewable through the wordpress.com/menus UI when he was trying to add new category menu items—several were cut off. I was able to replicate this bug by logging in as user. 

![menucategories](https://cloud.githubusercontent.com/assets/204742/17873842/ee87199e-6895-11e6-9a78-15e915534f16.png)

Suggested that he use the Customizer route of adding menu items, where all category items are visible.

**Comment by lancewillett** [comment]
Good find. We'll most likely replace menus in the near future.
