### ISSUE TITLE
Signup: Improving username selection

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#760]
Originally reported by @breezyskies.

Similar to https://github.com/Automattic/wp-calypso/issues/758 (for passwords), here are some ideas around improving the selection of usernames during signup:

Prototype: http://wpcomnux.herokuapp.com/usernames.php

<img width="462" alt="screen shot 2015-09-07 at 7 53 30 am" src="https://cloud.githubusercontent.com/assets/3011211/9719023/8ceb9a44-5535-11e5-8871-8bf1581680ed.png">

1) Show alternative suggestions in error message
2) Show suggestions in help text, based on email address (or previous site address step, if available)
3) Ask for "display name" and generate username based off this (with optional "change this now")

One other thing I came across during research is this [autofill concept](https://cloudup.com/c8Fe6TcBQS8). I believe they are pulling Twitter profile info using email address (and I'm not sure how many of our users have Twitter accounts), but it's pretty slick.

**Comment by folletto** [comment]
> Ask for "display name" and generate username based off this (with optional "change this now")

Auto-generate + change (considering also one can change it later if they want) seems ideal :100:

**Comment by bisko** [comment]
I laid some groundwork on `username` suggestions in #5234. It could be used in implementing this.
