### ISSUE TITLE
Site Assembler - Restyle button hover style for consistency

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76002]
Related #74633

## What

The button hover styles in the assembler screens are not consistent.

|Fonts screen|Patterns screen|
|---|---|
|![Image](https://user-images.githubusercontent.com/1881481/233265254-96201f3c-edd0-4af8-92a1-4f3e16a6771c.png)|![Image](https://user-images.githubusercontent.com/1881481/233265264-f93bb88e-8f01-4fa6-984d-5a10587e45c1.png)|

## Why

The button states should be consistent across the UI in the assembler flow.

## How

- Use the same blue color for the hover effect
- Any other styles?

**Comment by taipeicoder** [comment]
@miksansegundo IIRC we should be using the blue color on the Patterns screen (right side), correct?

**Comment by miksansegundo** [comment]
We have to use the blue color from the Fonts screen.

**Comment by taipeicoder** [comment]
Taking a closer look, most of the a11y focus state is set to `box-shadow: 0 0 0 2px var(--color-primary-light);` which is indeed the Patterns screen. Let's use `var(--color-primary-light)` for hover/focus state 🙂

**Comment by taipeicoder** [comment]
Closing via #76752
