### ISSUE TITLE
Gutenberg 15.6.0: Blank WooCommerce page on WordPress.com eCommerce websites

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#76000]
_**[Update](https://github.com/Automattic/wp-calypso/issues/76000#issuecomment-1517911621) 2023-04-20**_

_Calypso bridge patch resolves: https://github.com/Automattic/wc-calypso-bridge/pull/1086_

- _Now, it should be possible to run WooCommerce 7.6 with Gutenberg 15.6 on WPCOM websites._
- _The issue may still occur on WooCommerce 7.5 sites. In these cases, the best remedy to try is updating to the 7.6 version._

---

### Quick summary

When the plugin Gutenberg is active, the WooCommerce pages: `https://.../wp-admin/admin.php?page=wc-admin` and `https://.../wp-admin/admin.php?page=wc-admin&path=...` will render a blank page.

Deactivating the plugin Gutenberg resolves the issue.

This only happens on WPCOM websites with WordPress.com eCommerce plan. Business plan is not affected.

### Steps to reproduce

1. Access a WoA site with eCommerce plan.
2. Make sure Gutenberg is active and on ver. 15.6.0
3. Access Woo pages with this type of file path: `https://.../wp-admin/admin.php?page=wc-admin&path=...`
4. See blank page

Note: Woo pages with `post_type` are not affected.an 

### What you expected to happen

All Woo pages to work properly

### What actually happened

Blank page on pages with the following file path:
- https://.../wp-admin/admin.php?page=wc-admin&path=...
- https://.../wp-admin/admin.php?page=wc-admin

The workaround is to deactivate plugin Gutenberg. This is not ideal as Gutenberg takes care Block Editor and our customers might lose some functionalities.

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Console error:

```
act-dom.min.js?ver=18:1 TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at a (registry.js:125:24)
    at Object.__unstableMarkListeningStores (registry.js:204:30)
    at l (index.js:132:31)
    at index.js:166:3
    at $e (index.js:184:34)
    at Xe (index.js:273:5)
    at Gu (index.js?ver=7.6.0:2:142465)
    at index.js?ver=7.6.0:2:142814
    at wt (react-dom.min.js?ver=18:1:47623)
ar @ react-dom.min.js?ver=18:1
t.callback @ react-dom.min.js?ver=18:1
tt @ react-dom.min.js?ver=18:1
Jr @ react-dom.min.js?ver=18:1
Zr @ react-dom.min.js?ver=18:1
Gr @ react-dom.min.js?ver=18:1
(anonymous) @ react-dom.min.js?ver=18:1
xl @ react-dom.min.js?ver=18:1
fl @ react-dom.min.js?ver=18:1
zn @ react-dom.min.js?ver=18:1
pl @ react-dom.min.js?ver=18:1
(anonymous) @ react-dom.min.js?ver=18:1
ta @ react-dom.min.js?ver=18:1
e.render @ react-dom.min.js?ver=18:1
(anonymous) @ index.js?ver=7.6.0:2
(anonymous) @ index.js?ver=7.6.0:2
(anonymous) @ index.js?ver=7.6.0:2
react-dom.min.js?ver=18:1 Uncaught TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at a (registry.js:125:24)
    at Object.__unstableMarkListeningStores (registry.js:204:30)
    at l (index.js:132:31)
    at index.js:166:3
    at $e (index.js:184:34)
    at Xe (index.js:273:5)
    at Gu (index.js?ver=7.6.0:2:142465)
    at index.js?ver=7.6.0:2:142814
    at wt (react-dom.min.js?ver=18:1:47623)
a @ registry.js:125
(anonymous) @ registry.js:204
l @ index.js:132
(anonymous) @ index.js:166
$e @ index.js:184
Xe @ index.js:273
Gu @ index.js?ver=7.6.0:2
(anonymous) @ index.js?ver=7.6.0:2
wt @ react-dom.min.js?ver=18:1
$s @ react-dom.min.js?ver=18:1
wl @ react-dom.min.js?ver=18:1
bl @ react-dom.min.js?ver=18:1
yl @ react-dom.min.js?ver=18:1
fl @ react-dom.min.js?ver=18:1
zn @ react-dom.min.js?ver=18:1
pl @ react-dom.min.js?ver=18:1
(anonymous) @ react-dom.min.js?ver=18:1
ta @ react-dom.min.js?ver=18:1
e.render @ react-dom.min.js?ver=18:1
(anonymous) @ index.js?ver=7.6.0:2
(anonymous) @ index.js?ver=7.6.0:2
(anonymous) @ index.js?ver=7.6.0:2
admin-bar-v2.js?ver=12.1-a.7-202316-lite:2 Missing data from PHP (wpNotesArgs).
(anonymous) @ admin-bar-v2.js?ver=12.1-a.7-202316-lite:2
(anonymous) @ admin-bar-v2.js?ver=12.1-a.7-202316-lite:74
DevTools failed to load source map: Could not load content for chrome-extension://oncaapliomaamlbopdmhmdompfemljhm/scripts/contentScriptsCheck.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for https://ecom.corianderpho.blog/wp-content/plugins/full-site-editing/common/dist/common.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://ecom.corianderpho.blog/wp-content/plugins/full-site-editing/help-center/dist/help-center.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
6The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by retnonindya** [comment]
User report: 
6218673-zd-woothemes

**Comment by rakshitwesley** [comment]
Reported here on site with Pro plan:
6218854-zd-woothemes

**Comment by kuropixel** [comment]
40972960-hc eCommerce plan.

**Comment by worldomonation** [comment]
Reproduced by just accessing `/home` on a site with `WordPress.com eCommerce` plan enabled.

Multiple errors and warnings in the console, but I think this error does not exist when Gutenberg is disabled:
```
TypeError: can't access property Symbol.iterator, items is null
```

https://user-images.githubusercontent.com/6549265/233269934-e3703a8f-eadb-49a4-af7e-bba06d0f14de.mov

<img width="1478" alt="Screenshot 2023-04-20 at 2 49 53 PM" src="https://user-images.githubusercontent.com/6549265/233270049-1df4c5bd-49e1-4c34-a021-c31c7c588574.png">

**Comment by rw-ye** [comment]
Another report here: 6218750-zd-woothemes

**Comment by daledupreez** [comment]
@Automattic/ghidorah, are you available to take a look?

**Comment by adrianduffell** [comment]
Are you able to see what version of WooCommerce is in the SSR? (sorry I don't have access to Zendesk right now)

**Comment by retnonindya** [comment]
@adrianduffell Hello hello! Yes! The Woo version is 7.6.0 (the latest).

This is the SSR from my test site (eCommerce) -- ecom.corianderpho.blog :

```
### WordPress Environment ###

WordPress address (URL): https://ecom.corianderpho.blog
Site address (URL): https://ecom.corianderpho.blog
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Total Database Size: 4.37MB
Database Data Size: 2.75MB
Database Index Size: 1.62MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.17MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.27MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

amp_validated_url: 1
attachment: 33
customize_changeset: 5
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
nav_menu_item: 4
page: 15
post: 2
product: 18
product_variation: 7
revision: 10
sensei_email: 19
wp_global_styles: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: by Automattic – 5.1
AMP: by AMP Project Contributors – 2.4.1
Classic Editor: by WordPress Contributors – 1.6.3
CoBlocks: by GoDaddy – 3.0.2
Facebook for WooCommerce: by Facebook – 3.0.19
WordPress.com Editing Toolkit: by Automattic – 3.62711
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 12.1-a.7
Layout Grid: by Automattic – 1.8.2
Mailchimp for WooCommerce: by Mailchimp – 2.8.3
Page Optimize: by Automattic – 0.5.3
Press This: by WordPress Contributors – 1.1.1
Sensei LMS: by Automattic – 4.13.1
Storefront Powerpack: by WooCommerce – 2.0.0
WooCommerce Product Add-ons: by WooCommerce – 6.2.0
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce: by Automattic – 7.6.0

### Inactive Plugins (16) ###

Gutenberg: by Gutenberg Team – 15.6.0
Klarna Checkout for WooCommerce: by Krokedil – 2.10.1
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 3.0.6

TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.1.5
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.1
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.0
WooCommerce Eway Payment Gateway: by WooCommerce – 3.6.1
WooCommerce Payfast Gateway: by WooCommerce – 1.5.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Royal Mail: by WooCommerce – 2.8.0
WooCommerce Square: by WooCommerce – 3.7.0
WooCommerce Stripe Gateway: by WooCommerce – 7.3.0
WooCommerce UPS Shipping: by WooCommerce – 3.4.2
WooCommerce USPS Shipping: by WooCommerce – 4.6.3
WP Reset: by WebFactory Ltd – 1.97

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #68 - /shop/
Cart: #69 - /cart/
Checkout: #70 - /checkout/
My account: #71 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Homestore
Version: 2.0.34
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.2.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: /wordpress/themes/homestore/2.0.34/woocommerce/single-product/title.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
navigation
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-20 16:44:35 +00:00
Options: ✔
Notes: 127
Onboarding: completed

### Action Scheduler ###

Complete: 320
Oldest: 2023-03-20 09:04:34 +0000
Newest: 2023-04-20 07:28:53 +0000

Pending: 3
Oldest: 2023-04-20 07:28:54 +0000
Newest: 2023-04-20 18:08:09 +0000

Failed: 12
Oldest: 2022-11-02 21:59:07 +0000
Newest: 2023-04-14 18:43:45 +0000


### Status report information ###

Generated at: 2023-04-20 07:29:51 +00:00
```

**Comment by daledupreez** [comment]
As a quick follow-up, I am not able to reproduce this across multiple sites running the WordPress.com eCommerce plan or the Woo Express Performance plan. AFAICT, we should be running WooCommerce 7.6.0 and Gutenberg 15.6.0 across the sites.

Might this be some logic that's conditional on location or site setup?

**Comment by adrianduffell** [comment]
We knew about a similar error on WC 7.5 and below when Gutenberg is installed, and made a fix for it in 7.6. I was hoping these sites were on an older version for some reason.

**Comment by adrianduffell** [comment]
I would love to 100% rule out the deactivated WooCommerce Admin plugin. @retnonindya, would you be able to delete that one and test with Gutenberg enabled? (it's obsolete)

Another thing to try is clearing the browser cache in case there's some artifacts from the 7.5 version still being used

**Comment by retnonindya** [comment]
@adrianduffell Thanks! And no luck, I have deleted the `woocommerce-admin` plugin from my test site, and still no go :( I also have cleared my browser cache and use a different browser.

**Comment by adrianduffell** [comment]
Thanks @retnonindya! Hmm one more thing to try. Could try de-activating all plugins except Gutenberg and WooCommerce? Let's try to see if it's another plugin causing it or WooCommerce core itself.

**Comment by retnonindya** [comment]
@adrianduffell Yep, I have done that (left side, my dashboard. Right side, Blog RC.)

![Screenshot 2023-04-20 at 4 06 14 PM](https://user-images.githubusercontent.com/44726232/233301425-04b7c825-0711-492c-99e1-13fe81c942ce.png)

FWIW, I keep seeing this on Console:

```
The resource https://ecom.corianderpho.blog/wp-content/plugins/woocommerce/assets/client/admin/components/index.js?ver=7.6.0 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

Not sure if that's related 🤔 

**Update**: I noticed the PHP version was 7.4. I set it to 8.2 and still no luck 😞

**Comment by adrianduffell** [comment]
@retnonindya Thanks, hmm so it's seemingly an issue in Core or a customization added for Atomic sites 🤔

**Comment by adrianduffell** [comment]
@retnonindya Is it just the home screen? 

What happens when you navigate to the Analytics or Marketing pages?

**Comment by worldomonation** [comment]
@adrianduffell I happened to have my test site open, here are the results:
- Customers: grey page with proxy header and `Uncaught TypeError: can't access property Symbol.iterator, items is null
    a registry.js:125`.
- Analytics: same
- Marketing: same as above.
- Extensions: loads

**Comment by retnonindya** [comment]
@adrianduffell 

- Home: https://ecom.corianderpho.blog/wp-admin/admin.php?page=wc-admin -- Blank
- Orders: https://ecom.corianderpho.blog/wp-admin/edit.php?post_type=shop_order -- Opens
- Product: https://ecom.corianderpho.blog/wp-admin/edit.php?post_type=product -- Opens
- Customers: https://ecom.corianderpho.blog/wp-admin/admin.php?page=wc-admin&path=%2Fcustomers -- Blank
- Analytics: https://ecom.corianderpho.blog/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview -- Blank
- Marketing: https://ecom.corianderpho.blog/wp-admin/admin.php?page=wc-admin&path=%2Fmarketing -- Blank
- Extensions: https://ecom.corianderpho.blog/wp-admin/admin.php?page=wc-addons -- Opens
- Tools > Woo Status: https://ecom.corianderpho.blog/wp-admin/admin.php?page=wc-status -- Opens
- Settings > WooCommerce: https://ecom.corianderpho.blog/wp-admin/admin.php?page=wc-settings -- Opens

**Comment by jsnajdr** [comment]
It's most likely this issue in Woo: https://github.com/woocommerce/woocommerce/pull/37641. Already fixed in trunk, but I'm not sure if it's been part of any release.

In Gutenberg, the implementation of the `useSelect` hook has changed a little bit, and it uncovered an incorrect usage of it in Woo.

**Comment by i11za** [comment]
User report, eCommerce plan: 6219719-zd-woothemes

**Comment by ariel-maidana** [comment]
6219827-zd-woothemes
Please let the user know once the issue is resolved.

**Comment by zdenys** [comment]
6219948-zd-woothemes

**Comment by adrianduffell** [comment]
@jsnajdr has a fix underway in the WooCommerce plugin here https://github.com/woocommerce/woocommerce/pull/37882

Until that's available we're looking at the feasibility of downgrading the Gutenberg plugin on Atomic sites.

At the moment, disabling the Gutenberg plugin is the best workaround for the issue.

**Comment by fetenlakhal** [comment]
38216513-hc

**Comment by sanjeev00733** [comment]
Another report in 6220262-zen

**Comment by sanjeev00733** [comment]
Another report 6220557-zen. But the site is on the Business plan. 

The customer page is blank and the orders page load partially without the left side panel. Browser console shows error from Gutenberg plugin

<img width="1419" alt="gutenberg-error" src="https://user-images.githubusercontent.com/2501779/233441893-a0c397b8-7601-4c2d-8a87-1ed4dbafa4ca.png">

**Comment by cuemarie** [comment]
Hey @sanjeev00733 ! 

> orders page load partially without the left side panel

This looks a bit different than the specific issue in the report above.  ~~Were you able to replicate those details in a test environment? If so, can you file a new issue for that via Bugomattic?~~

_Edit - @jp-imagines beat you to it! :) See: https://github.com/Automattic/wp-calypso/issues/76054_

**Comment by cuemarie** [comment]
42707275-hc eComm site where all their `/wp-admin/admin.php?page=wc-admin&path=...` pages are blank.

- Follow up ticket: 6221227-zd-woothemes

I've placed that on hold in case we get a fix in place in the next 24h, so we can update the user.

**Comment by jp-imagines** [comment]
> Another report 6220557-zen. But the site is on the Business plan.
> 
> The customer page is blank and the orders page load partially without the left side panel. Browser console shows error from Gutenberg plugin

Reported the missing left-side navigation here: https://github.com/Automattic/wp-calypso/issues/76054 (I've already added this report there too.)

**Comment by mgozdis** [comment]
Another report in 39288091-hc on Business plan.
Deactivating Gutenberg allowed pages and sidebar to load.

**Comment by mgozdis** [comment]
Another report in 6220931-zd-woothemes on eCommerce plan.
Deactivated Gutenberg as work-around.

**Comment by Greatdane** [comment]
Another; 6221013-zd-woothemes

Looks like it affects the customers page as well

**Comment by adrianduffell** [comment]
## Update

([previous update](https://github.com/Automattic/wp-calypso/issues/76000#issuecomment-1516313859))

It's not safe to rollback the Gutenberg plugin safely. Instead, today we're aiming to try [patching WooCommerce using the calypso bridge](https://github.com/Automattic/wc-calypso-bridge/pull/1086). I'll report back with the results.

**Comment by adrianduffell** [comment]
## Update

The calypso bridge patch appears to be successful. Now, it should be possible to run WooCommerce 7.6 with Gutenberg 15.6 on WPCOM websites.

The issue may still occur on WooCommerce 7.5 sites. In these cases, the best remedy to try is updating to the 7.6 version.

**Comment by mgozdis** [comment]
Additional report here but looks like they canceled plan and pointed domain elsewhere: 6219744-zd-woothemes

**Comment by cuemarie** [comment]
@adrianduffell With the Calypso bridge patch in place, what do you think about closing this issue as resolved? Not sure if that's better for communicating about the issue, or if its best to keep it open given the possibility that it can occur on WooCommerce 7.5 sites 🤔

**Comment by adrianduffell** [comment]
@cuemarie, thanks for the reminder - yeah I was keeping it open to get a sense of how many 7.5 users might still be impacted. 

Due to the low activity, I will close it out now!
