### ISSUE TITLE
Stats leaks CSS out to other panels

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#76032]
### Quick summary

Some CSS overrides at Stats page (`.promo-card`?) seems to be unscoped, and leaks into Earn page:

After visiting Stats, Earn page's boxes become all wonky and rounded:

<img width="1754" alt="Screenshot 2023-04-20 at 16 39 05" src="https://user-images.githubusercontent.com/87168/233385903-02f35e55-4c7f-4634-85e3-f774b3f39ae8.png">

https://user-images.githubusercontent.com/87168/233385885-236181b8-440b-409c-bc41-98f9a6450821.mov

### Steps to reproduce

- Open Tools -> Earn
- shift+refresh to ensure you have cache cleared, note square boxes
- Go to Stats
- Come back to earn; note rounded boxes now

### What you expected to happen

Styles not to change.

### What actually happened

Styles leaking.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

@dognose24 @kangzj @jsnmoon hi! I see you've been recently working a lot on Stats with Team Red. Could your team take a look?

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described!

#### Screenshots/Recordings

**Tools > Earn Page before viewing stats page**
![Markup on 2023-04-20 at 10:42:00](https://user-images.githubusercontent.com/27249804/233445843-a5bcc3d5-61f0-46b5-9f89-a8773b96fb43.png)

**Tools > Earn Page AFTER viewing stats page**
![Markup on 2023-04-20 at 10:42:14](https://user-images.githubusercontent.com/27249804/233445889-622a0a0a-a884-4b66-af06-2c43607fb9f0.png)

📌 ACTIONS
- Assigned to Other (OP pinged a few people for next steps)

**Comment by jsnmoon** [comment]
I'll have a PR ready for fixing this today.

**Comment by jsnmoon** [comment]
The [fix for this regression](https://github.com/Automattic/wp-calypso/pull/76053) is ready for review.

**Comment by simison** [comment]
Thanks for fixing this so swiftly! 👏
