### ISSUE TITLE
New WooCommerce Navigation conflicts with Gutenberg, navigation top and sidebars hide

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#76054]
_Update - replicable with Gutenberg 15.5.1 as well_

### Quick summary

This seems to only affect sites on the Business plan with the newer WooCommerce navigation system (from 2020: pbIJXs-qm-p2) – i.e. the navigation system where `Products` is a sub-menu of `WooCommerce` rather than its own top-level menu. 

With Gutenberg 15.5+ active, other Woo-related WP Admin pages (Orders, Products, Marketplace, Settings) load their contents properly, but the left-side navigation is missing.  `/wp-admin/admin.php` and `/wp-admin/edit.php` pages seem impacted

- _Separate issue where WC Admin pages (i.e. `http://.../wp-admin/admin.php?page=wc-admin...`) are fully blank can be found here: https://github.com/Automattic/wp-calypso/issues/76000_

### Steps to reproduce

1. Start with a Business plan site with WooCommerce and Gutenberg 15.6.0 active.
2. Make sure your site has the "new" WooCommerce navigation system in place. If it isn't, you can go to _WooCommerce > Settings > Advanced > Features_ (`/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`), use the browser console to remove the `disabled=""` attribute on the **Navigation** feature's checkbox, check the box, and save settings.
3. Navigate to _WooCommerce > Orders_ (or Products, Marketplace, or Settings).

![1b4mTk.png](https://user-images.githubusercontent.com/5630717/233461501-0b7d0693-fc28-4de1-aaa5-c6247634e945.png)

### What you expected to happen

New Woo navigation experience should load as expected.

### What actually happened

The left-side nav area may load briefly as a blank dark pane before disappearing, but otherwise there is no left-side navigation, making it impossible to return to other pages without using your browser's back button.

https://user-images.githubusercontent.com/5630717/233461077-37335c95-2fd0-48e5-871e-6c26e221ed7a.mov

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Reported in 6220131-zd-woothemes and I believe 6220557-zen (from https://github.com/Automattic/wp-calypso/issues/76000#issuecomment-1516691500).

**Comment by cuemarie** [comment]
Escalated here: p1682017254105729-slack-C02FMH4G8

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Replicated** / Could Not Replicate / Uncertain
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described, however **this also occurs in Gutenberg 15.5.1**
- To undo the change to the navigation style, you can return directly to `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features` and uncheck the **Navigation** setting again

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/233500603-403c653a-8489-411f-935a-199dd8c15f26.mp4

**Gutenberg Inactive vs Gutenberg 15.5.1**

https://user-images.githubusercontent.com/27249804/233501011-0a9405de-d05e-406d-af8d-7ec8f39ee464.mp4

📌 ACTIONS
- Assigned to Other as folks are reviewing in slack

**Comment by cuemarie** [comment]
One other note - it seems like that WooCommerce Navigation experience was paused ( pbIJXs-7A-p2#comment-4016 ), which would explain why it's a little more difficult to repro test this (having to employ a browser workaround). If so, this may impact way fewer users.

@pmcpinto can you shed some light here on that nav experience? Is it paused/onhold/deprecated? Any idea how many sites use it?

**Comment by cuemarie** [comment]
Fixed by https://github.com/Automattic/wc-calypso-bridge/pull/1086 🎉
