### ISSUE TITLE
Popover: improve integration with masterbar

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#7605]
The masterbar is the real top limit of the viewport for some visual components. Specifically the Popover should be positioned considering this limit. Some inconsistent visual bugs:

**stats/insights**
![image](https://cloud.githubusercontent.com/assets/77539/17893088/b343d0c2-691a-11e6-9a9f-dfcaeaa0cca8.png)

**reader/share popover**
![image](https://cloud.githubusercontent.com/assets/77539/17893121/dbf82ff4-691a-11e6-823f-25a942b654b8.png)

**Comment by mtias** [comment]
I don't think this is bad.

**Comment by retrofox** [comment]
Let me add an animation to show what I mean.

<img src="https://cloud.githubusercontent.com/assets/77539/17900379/7cbc621a-6935-11e6-9fe1-1c65f173ae1a.gif" width="400px" />

**Comment by mtias** [comment]
That looks worse :)

**Comment by retrofox** [comment]
cc @folletto

**Comment by mtias** [comment]
Seems popovers should just have a z-index below masterbar. The problem before was with popovers rendered within a dialog — those need a great z-index or they are invisible. It'd be good to detect when a popover is called within a dialog and append a class to bump the z-index.

**Comment by folletto** [comment]
> Seems popovers should just have a z-index below masterbar.

Agreed. :)
