### ISSUE TITLE
Post Author Block: Gravatar profile image links to HTTP profile URL

### ISSUE THREAD

**Issue by wiesenhauss** [Automattic/wp-calypso#76061]
### Quick summary

Adding the Post Author Block to a page or Site Editor template and toggling the "Show avatar" option causes the profile picture to be displayed and linked to the HTTP version of the Gravatar profile page. This will display a 'not secure' browser warning.

<img width="403" alt="Screenshot 2023-04-20 at 16 18 41" src="https://user-images.githubusercontent.com/99455043/233465871-ef40aaca-0751-4936-992d-09e107546bca.png">

### Steps to reproduce

1. Add the 'Post Author' block to a post, page, or template
2. Enable the 'Show avatar' setting in the Settings panel
3. Save and preview content

### What you expected to happen

Gravatar profile links to https profile page URL.

### What actually happened

Gravatar profile links to http profile page URL, and browser shows 'not secure' error on address bar.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Self-hosted installs don't seem to link the profile picture to the Gravatar profile automatically, so I couldn't reproduce the issue there.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – No (Gravatar link is a WPcom feature, I _think_)

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described - Gravatar profile loads with `http://`, leading to an unsecure warning from browsers

#### Screenshots/Recordings

**Firefox 112.0.1**
![Markup on 2023-04-20 at 15:56:42](https://user-images.githubusercontent.com/27249804/233504282-48b97602-a187-4625-aa4f-b2de41e09c9f.png)

**Chrome Version 112.0.5615.121**
![Markup on 2023-04-20 at 16:00:40](https://user-images.githubusercontent.com/27249804/233504368-3d03b5c6-d75b-4cb2-81b4-0dfae852d53c.png)

📌 ACTIONS
- Assigned to Cylon

**Comment by annezazu** [comment]
I can't replicate this on nomad.blog, a simple site on WordPress.com:

https://github.com/user-attachments/assets/95909bd1-8a2f-4b35-8c09-0d7a61973717

I'm going to close this out as a result unless someone can provide more context as to whether the issue still exists.
