### ISSUE TITLE
NUX: Trampoline: button styling glitch

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#7607]
When getting the Trampoline view for a newly created site, I noticed a glitch with the button borders that happens on hover:

![trampoline](https://cloud.githubusercontent.com/assets/23619/17894150/b0627ccc-6948-11e6-950c-185c446d966c.gif)

**Comment by lancewillett** [comment]
Hi Leif, can you add steps to repeat and the browser / OS where you saw this?

**Comment by lsinger** [comment]
Can't reproduce anymore — was on Safari / macOS. Closing. Thanks @lancewillett. :)
