### ISSUE TITLE
Improve theme card hover colors in wp-admin

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#76088]
## Description

As discussed in p9Jlb4-6ZK-p2, the active theme card hover state colors look a bit weird in wp-admin.
![Image](https://user-images.githubusercontent.com/797888/233654614-0b58a144-4989-490c-9720-9acbaf015072.png)

## Acceptance Criteria

- [ ] Improve the hover state for the active theme card in wp-admin.

**Comment by fushar** [comment]
This was already fixed by https://github.com/Automattic/jetpack/pull/37343.
