### ISSUE TITLE
Theme showcase: Make Pick design available for DotORG themes in the logged-out flow

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#76090]
### Quick summary

We should make the `Pick design` button available for dot-org themes for logged-out users too.

Right now, logged-out users don't have a clear CTA button that will allow them to signup with a DotORG theme (e.g. Astra).

Based on stats, we've seen that there is a clear intent to select dot-org themes during signup.

### Steps to reproduce

1. Open incognito and go to WordPress.com/themes
2. Search for "Astra"
3. Click on the theme card and visit the theme details page.
4. Notice that we don't display a `Pick design` CTA button like we do for other themes.

### What you expected to happen

We should add the `Pick design` button

### What actually happened

No button. The user doesn't know how to proceed next with this theme selection. 

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by youbrokesomething** [comment]
Hi @BogdanUngureanu 👋 
The priority, triage, and escalated tags are all for the bug prioritization and triage tasks with team KitKat. Removing them is going to result in the bot just adding them back. You can ignore them; we go through all of them manually every day. Sorry if it's confusing.

**Comment by BogdanUngureanu** [comment]
Oh, I see! Thanks for letting me know! :) I've created the issue mostly for tracking purposes since I'll start working on it myself soon. :)
