### ISSUE TITLE
Wordpress.org vs wordpress.com

### ISSUE THREAD

**Issue by Glis** [Automattic/wp-calypso#761]
I just tested calypso and it's really great! I have this small question regarding it's current use case, sorry if it's silly, I think I'm missing something.

When I tried calypso after ```make run```, it deployed a local server pointing to calypso.localhost:3000. after that, I completed a wordpress install of a new site just for testing. I noticed this site got published in my account of Wordpress.com. I thought that it would be a local instance of wordpress like it was with wordpress.org installations.

So my question is: is this just the current state of calypso?, will you be releasing some sort of local-instance type of download or installation of calypso, like the "Famous 5-minute install"? or is there a way in this build to host the calypso clone i have into a custom VPS hosting with a custom DNS and such.

Thank you for your support :)  I hope this grows fast and soon!

**Comment by lamosty** [comment]
I'm not a Calypso dev but I think it will stay like this for some time. It's basically an admin interface to WordPress.com sites. However, you can still use it on your self-hosted WP blog through Jetpack. Install it on your blog, connect it with your WP.com account and you are good to go.

As Calypso is open source, maybe we (you) could change its API to point it to your self-hosted blog with WP REST API. But that might be a lot of work.

**Comment by lancewillett** [comment]
lamosty is correct. Thanks for the comment and questions. Cheers.

**Comment by Glis** [comment]
Thanks for the responses, Could you point me in the right direction for using calypso in my "self-hosted WP blog through Jetpack" I checked jetpack and could not find a calypso package"

**Comment by lancewillett** [comment]
Glis, to get started you can take a look at https://developer.wordpress.com/calypso/#common-questions and the project README here and find out more about how everything works together.

To get Jetpack connected read the instructions here: http://jetpack.me/support/getting-started-with-jetpack/ — all you need is a WordPress.com user account and the Jetpack plugin installed properly to connect your self-hosted blog to WordPress.com.
