### ISSUE TITLE
Invalid button label when non plan purchasing user visits plan page

### ISSUE THREAD

**Issue by ddc22** [Automattic/wp-calypso#76102]
How to reproduce
1 - Create a site with a paid plan
2 - Add a non Super User account to a WordPress site as an administrator (This is to trigger the `This plan was purchased by a different WordPress.com account` state)
3 - On the non super user account visit the plans page

As shown below the `Downgrade` greyed out text is incorrect to be shown in the Business/eCommerce plan when a Premium plan  is purchased. It should be changed to `Upgrade` but still remain greyed out because we are not in the site owner's context.

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/3422709/236474619-2fb51302-7edb-4cee-9aca-c0c1acbc1256.png">

**Comment by ddc22** [comment]
Hi @southp I assigned this to you so that you can prioritise this as you see fit :)

**Comment by southp** [comment]
@jdc91 Looks like the screenshot is missing :P Could you help me add it when you have a moment?

**Comment by ddc22** [comment]
For some reason the previous screenshot was not showing 😮 . I added it again.

**Comment by southp** [comment]
Thanks. I've moved it to Next Up since it is conveying wrong information.

**Comment by jeyip** [comment]
Hi! Closing this in favor of https://github.com/Automattic/wp-calypso/issues/87479. If, for some reason, we want both issues open at the same, we can always reopen 🙂
