### ISSUE TITLE
Site Creation Flow: Stuck in Editor

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#76119]
### Quick summary

After creating a new site on the Personal plan and going through the creation flow, when I eventually land in the editor after selecting a design I am unable to leave the Editor experience.

### Steps to reproduce

1. Calypso Admin > Add new Site
2. Select a domain and personal plan
3. Usage option: "Writing and publishing"
4. Select a design > I selected "Hey"
5. Land in the Editor after site is created. Now _without_ publishing a post try and leave the Editor via the WP icon in the top left. (`https://wordpress.com/setup/write/launchpad?siteSlug={site-slug}.wordpress.com`)
6. See that you're now stuck.

### What you expected to happen

I am able to leave the Editor and go to the WordPress.com dashboard.

### What actually happened

I am stuck in the Editor.

### Impact

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- In my test, I purchased a Personal Plan and selected the "Write & Publish" option as instructed. After opening a new post, I was able to return to "Next Steps" using the WordPress logo at top left.  
- Tested in Firefox 112.0.1

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/235009439-b66794bc-5605-4790-8dbf-cd4049941086.mp4

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- Hey @tjcafferkey ! Can you take a look at the recording I enclosed above and let me know if there's anything different between our tests?
- If you can still reproduce the issue, can you share a recording of the behavior you're seeing with the Console in view, so we can see any error details there?  Thank you!

**Comment by tjcafferkey** [comment]
@cuemarie I am going to close this issue, weirdly I cannot reproduce this bug anymore 😕 . I guess this is a good thing but feel bad for any time wasted on this.

**Comment by arthur791004** [comment]
It's resolved via https://github.com/Automattic/wp-calypso/pull/76307

**Comment by cuemarie** [comment]
No worries @tjcafferkey , and thanks for the PR link, @arthur791004 !
