### ISSUE TITLE
Odyssey Widget: reuse the Button component of `@automattic/components` 

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#76115]
IMHO, we can reuse the Button component of `@automattic/components` along with the `emerald-button-style` to implement the busy status quickly.

```suggestion
						<Button
							primary
							busy={ disabled }
```

<img width="548" alt="截圖 2023-04-22 上午12 19 27" src="https://user-images.githubusercontent.com/6869813/233686557-a0fd4962-87b9-45db-b763-10396cb16c2b.png">

_Originally posted by @dognose24 in https://github.com/Automattic/wp-calypso/pull/75993#discussion_r1173965909_

**Comment by dognose24** [comment]
This task should be done by https://github.com/Automattic/wp-calypso/pull/76858.
