### ISSUE TITLE
`/subscriptions/comments`: When you unsubscribe from a post/comment, the settings popup stays open for the next row on the list

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#76123]
When you unsubscribe from a post/comment, the settings popup stays open for the next row on the list:

![Markup on 2023-04-24 at 11:47:32](https://user-images.githubusercontent.com/25105483/233962328-087f3640-315a-469b-9f6a-d74bfbb9d0aa.png)

This can confuse the user thinking they haven't unsubscribed yet. As a result, they may accidentally unsubscribe from another site they hadn't planned to unsubscribe from in the first place.

I suspect the issue may be related to the virtualized list.

**Comment by ivan-ottinger** [comment]
This issue hasn't been fixed yet. 🙂 (the https://github.com/Automattic/wp-calypso/pull/76121 was fixing a different issue)

→ Reopening this issue.

**Comment by JuanLucha** [comment]
I just learned that it's not like the menu is open for the next item. The open menu still has the data from the removed item. I'll keep investigating.

Edit: even when the label is from the first one, triggering unfollow from the remaining popup will remove the next one.
