### ISSUE TITLE
Ecommerce Plugins on Legacy sites: Write script that adds the desired plugins to the site

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#76143]
* Function inputs: Blog ID (or possible a CSV file of blog IDs) and an array of desired plugin slugs and their corresponding actions.
* Should check that the site has permissions/plan capabilities to install the plugin(s).
* Should check to see if the plugin is already installed/active before proceeding.
* Should install (but not activate) the desired plugins on the blog ID
* We may be able to activate the plugins via API calls.
* We may need to investigate making this part of an async job if we anticipate running the script for multiple sites at once.

Related to #74012

**Comment by andres-blanco** [comment]
> Function inputs: Blog ID and an array of desired plugin slugs.

I think it should alternatively receive a file with a list of blog ids so it's easier to run in chunks.


> We may need to investigate making this part of an async job if we anticipate running the script for multiple sites at once.

If the site count is small enough we might get away with running chunks from our sandboxes.

**Comment by andres-blanco** [comment]
> Should install (but not activate) the desired plugins on the blog ID

I will be looking into what we can user to accomplish this task

**Comment by sixhours** [comment]
> I will be looking into what we can user to accomplish this task

The API is designed to accept either `ATOMIC_STATE_ACTIVATE` or `ATOMIC_STATE_INSTALL` parameters along with the plugin slug; you can probably see how it comes together with `site_manage_software`: fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sjbn%2Sjbn%2Qgenafsre.cuc%3Se%3Q9870ss3r%23542-og and using methods from `woa-ecommerce-software.php`

**Comment by andres-blanco** [comment]
> > I will be looking into what we can user to accomplish this task
> 
> The API is designed to accept either `ATOMIC_STATE_ACTIVATE` or `ATOMIC_STATE_INSTALL` parameters along with the plugin slug; you can probably see how it comes together with `site_manage_software`: [fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sjbn%2Sjbn%2Qgenafsre.cuc%3Se%3Q9870ss3r%23542-og](uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Sjbn%2Sjbn%2Qgenafsre.cuc%3Se%3Q9870ss3r%23542-og) and using methods from `woa-ecommerce-software.php`

Oh yes, that looks pretty straight forward! I've just run this line from the sandbox:
```php
WPCOM_Sites_on_Atomic::site_manage_software( $site_id, array('plugins/woocommerce-gateway-stripe'=> ATOMIC_STATE_INSTALL ) );
```

And it indeed installs the plugin (without activating it).

**Comment by andres-blanco** [comment]
I will start working on this, will update with the diff

**Comment by andres-blanco** [comment]
the diff D108967-code

**Comment by andres-blanco** [comment]
The script was already run: p1685039539409969-slack-C0Q664T29
