### ISSUE TITLE
Consider applying the hook for all plan upgrades, not only WooExpress

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#76148]
We should consider allowing other types of plans to take advantage of the `woa_ecommerce_handle_bundle_upsell` hook to remove plugins on "upgrade". Currently, the hook only works for WooExpress plans, for example, when the user upgrades from the Trial plan to the Essential plan, we need to remove some software that is not included in the Trial.

Context: D108329-code #inline-370562

**Comment by sixhours** [comment]
Started looking at this in D109719-code

**Comment by sixhours** [comment]
Shipped in D109719-code!
