### ISSUE TITLE
Assembler: move Premium badge closer to heading

### ISSUE THREAD

**Issue by davewhitley** [Automattic/wp-calypso#76160]
Currently, the badge is far from the heading text:

<img width="392" alt="Screen Shot 2023-04-24 at 3 42 52 PM" src="https://user-images.githubusercontent.com/618551/234112342-533fa532-8b04-4340-9f78-9147b96cb988.png">

Let's change it to have a 10px margin:

<img width="382" alt="Screen Shot 2023-04-24 at 3 42 04 PM" src="https://user-images.githubusercontent.com/618551/234112445-6cbfcdb7-eb99-4b07-ab31-468153fe029d.png">

**Comment by taipeicoder** [comment]
Closing via #77150.
