### ISSUE TITLE
Patterns - Remove static links from navigation blocks

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76169]
Related 
Navigation menus in Dotcom pekYwv-Jv-p2

## What

The Dotcom patterns have static navigation links (About - Home - Contact) to make the previews uniform.

![Image](https://user-images.githubusercontent.com/1881481/234163350-aa3fe837-88ef-4b34-9420-34e52cd4472a.png)

## Why

Pattern in core use empty navigation blocks because they are more user-friendly as they use a fallback to load a page list or use the latest menu on the user site.

## How

 - Add the demo pages Home, About, Contact in dotcompatterns and use empty navigation blocks in header and footer patterns so they will show the page list as a fallback.
 - The same must be done in the `creatio2demo` site because the PA uses it to preview patterns.
 - Remove the static navigation links from Dotcom header and footer patterns.
 - To prevent breaking navigations when used on other sites, we must strip out the ref (the menu id on a site) from navigation blocks. See this [PR](https://github.com/WordPress/wordpress-develop/pull/3899/files) that will add a helper function to do that.
   - Option 1: do it on post-save
   - Option 2: do it on the output from the PTK API when patterns are fetched (This is preferred because sounds safer)

**Comment by taipeicoder** [comment]
This is a non-trivial task, @miksansegundo will write a P2 for this.

**Comment by miksansegundo** [comment]
This is done because we removed all static links from all published header and footer patterns.

The following two patterns have been unpublished because they use static links for design reasons and it's preferred to unpublish them to provide users with the best possible experience in the assembler and editor. 


- https://dotcompatterns.wordpress.com/2023/07/28/header-with-navigation-buttons/
 This pattern uses buttons with static links, rather than a navigation block, in order to support the border on links (button style)
- https://dotcompatterns.wordpress.com/2022/08/29/centered-header-with-logo-and-navigation/
 This pattern still uses static links because it has two navigations in order to support the logo between links.
