### ISSUE TITLE
Site Assembler - Make the Pattern toolbar (Remove button) always visible

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76176]
## What
The remove button is hidden in the site preview sometimes.

![Image](https://user-images.githubusercontent.com/1881481/234178880-2c531dbc-ecbc-4e8f-836d-35832af6db42.png)

## Why

The toolbar should be always visible to avoid scroll just to find it

## How

- Option 1: Make it float (CSS fixed position) and move with the scroll. 
- Option 2: Move it to the bottom when the top of the pattern is hidden because of the scroll.

![Image](https://user-images.githubusercontent.com/1881481/234179313-91a2d093-fce2-4b60-afe6-5c4fa9fb1aeb.png)

**Comment by arthur791004** [comment]
This will be part of https://github.com/Automattic/wp-calypso/issues/76020

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/76312

**Comment by arthur791004** [comment]
There is an issue related to https://github.com/Automattic/wp-calypso/pull/76750 and it seems that we cannot have a quick fix for now. So, re-open this issue and we can work on the floating toolbar on the large preview first.
