### ISSUE TITLE
Site Assembler - Pattern Inserter - Show to users that a pattern was already added

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76175]
## What

Show to users that a pattern was already added.

## Why

Having a larger variety of patterns can make it difficult to remember which ones they have already added. 

## How
<img width="539" alt="Screenshot 2566-04-27 at 17 52 16" src="https://user-images.githubusercontent.com/1881481/234841476-32dbc085-1162-4004-b240-376d0bcfe3de.png">

Show a dark border. See figma Tv3pYqA3EcRfiXC31IxrXE-fi-7_1414

**Comment by autumnfjeld** [comment]
What a great idea.   @lucasmendes-design   What do you think? Should we prioritize this idea?  (Meaning move it to Ready for Dev)

**Comment by lucasmendes-design** [comment]
> What do you think? Should we prioritize this idea?

Yes, I think it's a good improvement and I believe it's not a heavy lift in terms of development.

**Comment by miksansegundo** [comment]
@lucasmendes-design, what is the latest on this? Do we want to add the ☑️ icon too?

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/50ea97b2-3012-447c-a94f-d9aa001aef24)

**Comment by lucasmendes-design** [comment]
Hi @miksansegundo, let's **not** add the check mark. 

<img width="156" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/e5e996a9-4031-4087-9c17-e41624911c29">
