### ISSUE TITLE
Site Assembler - Pattern Inserter - Show [+] icon on hover

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76172]
## What

When I add two patterns from the same category it seems that I'm replacing the pattern instead of adding a new one.

## Why

Improve the affordance to be clearer that users are adding new patterns.

## How

Show an `[+]` icon on hover. See figma Tv3pYqA3EcRfiXC31IxrXE-fi-7_1414

![Image](https://user-images.githubusercontent.com/1881481/234174536-67f997d8-09e5-4cc9-a09c-f336f3faa257.png)

**Comment by miksansegundo** [comment]
@lucasmendes-design what's the last about this? I'm moving it to ready for dev to add the `[+]` only.

The `Replace` action won't work because patterns can be added multiple times and we don't know which pattern the user wants to replace from there.
 
<img width="243" alt="Screenshot 2566-05-15 at 18 42 22" src="https://github.com/Automattic/wp-calypso/assets/1881481/7bb2949e-247b-4656-82e6-9fabefead454">

**Comment by lucasmendes-design** [comment]
> I'm moving it to ready for dev to add the [+] only.

Perfect. Thanks @miksansegundo ✌🏼 Are we adding the patterns preview with hover as well? 
<img width="1199" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/55e668a0-7987-45db-a79a-0a8208e4a2a1">


> The Replace action won't work because patterns can be added multiple times and we don't know which pattern the user wants to replace from there.

You're 100% right.

**Comment by miksansegundo** [comment]
It was tested with different components (patterns, fonts, colors, etc) and we think it will not work properly.
