### ISSUE TITLE
Site Assembler - Undo actions from notices

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76177]
## What

We show notices when patterns are added/replaced/removed. We can add a link on the notice to undo the action. 

![Image](https://user-images.githubusercontent.com/1881481/234180864-c6b37f28-b243-4c86-8493-a66f8e517a3b.png)

## Why

It's quite useful to add back a pattern we just removed/replaced so users don't have to go find it again. It's common to see this in other products.

## How

- Undo a removed pattern add the pattern back. In what position? I guess in the same position it was.
- Undo an added pattern removes the pattern.
- Undo a replaced pattern replaces it back

Shall we start from undoing removed patterns. That seems the most useful feature.

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
