### ISSUE TITLE
Site Assembler - Pattern Inserter - Replace and strip images and text in pattern previews

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76198]
## What

Using completely different images and creating a website is confusing. The final result is very chaotic. Maybe we can use the same image for all patterns or one image for each category

## Why

- To standarize images in the previews using only one placeholder image
  - per pattern category
  - per theme  
  - random
  - image filter (add color or all grades of gray/black)
- To apply a theme or style variation to the previews
- Make some text pattern tweaks for the previews in the assembler

## How

Passing params to the render endpoint `block-renderer/render/pattern` to replace or strip content like images and text in pattern previews

**Comment by autumnfjeld** [comment]
I don't think we want to take "custom patterns" and replace the image.  The patterns will look bad because they've been created with a particular look and feel.    We should focus on all new patterns and all wireframe patterns using the same image or a pool of similar images.  cc: @alaczek

**Comment by miksansegundo** [comment]
For context, this issue can be the technical path to try the ideas shared in this comment from Ian: p1682343734538199/1682046205.168139-slack-C048CUFRGFQ

**Comment by miksansegundo** [comment]
This was just an idea
