### ISSUE TITLE
Stax Theme. Button Gradient color cannot be changed or overwritten.

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#76199]
### Quick summary

The Button background colors are not working as expected on the Stax theme. Gradient colors over-write everything and they are cannot be changed, only to a different gradient color.

https://user-images.githubusercontent.com/84539773/234233655-99b407f9-0719-43e4-87a6-f42039f162b1.mp4

### Steps to reproduce

- Activate Stax theme
- Visit Site Editor > Style > Button solid background colors are not respected. You can only change it from one Gradient to another kind of Gradient, but not to a Solid.
- If a solid color is applied to the button in the Page Editor, the button will show that color open hovering.
- Tried Styles > Colors > Buttons or Styles > Blocks > Buttons

### What you expected to happen

The button background color could be changed. I could turn off the Gradient and choose a solid instead. (In other themes, when I click on a selected Gradient color again, it would get deselected. Doesn't work here.)

### What actually happened

Gradient over writes everything

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by youbrokesomething** [comment]
📌 ACTIONS

Closed as outside scope
📌 Message to Author

Hey @csabarakasz  ! As Strax is a Marketplace theme developed by Organic Themes, technical issues are supported by the theme developers, not here in wp-calypso. ([Reference in Public WordPress.com Documentation](https://wordpress.com/support/marketplace-themes/#theme-support), if that helps!)
