### ISSUE TITLE
`/subscriptions/comments`: Create "Notify me of new comments" toggle

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#76203]
The goal of this task is to create a working "Notify me of new comments" toggle to the Comments page (**for logged-in users only**):

![Image](https://user-images.githubusercontent.com/25105483/234249524-f4471aee-55e3-4a82-ba26-93e6d9a522de.png)

Design: inDLaEQV8jJ21O4WXawIsJ-fi-712_26668

**Comment by phcp** [comment]
While digging into this issue, I've found that it's more extensive than I initially thought. So, I've put together a list of all the things that need updating to get this task done.

- [ ] Update `wpcom/v2/post-comment-subscriptions` endpoint to return `send_comments`
- [ ] Create an endpoint to update `comment_email_subscriptions` for a `post_id`
- [ ] Create a `useSiteNotifyMeOfNewCommentsMutation` hook to consume the new endpoint
- [ ] Create a toggle component and integrate with the dropdown menu

**Comment by phcp** [comment]
Draft PRs for this task:
- D131027-code
- https://github.com/Automattic/wp-calypso/pull/84888
