### ISSUE TITLE
`/subscriptions/comments` & `/subscriptions/pending`: Launch both pages to all users

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#76202]
Once all user-facing strings related to the Comments and Pending page are translated, we can launch both pages to all users.

Please note that apart from making adjustments to the Calypso side, we also need to edit the temporary redirects on the WPCOM side.

**Comment by yansern** [comment]
Done.
D110369-code
https://github.com/Automattic/wp-calypso/pull/76758
