### ISSUE TITLE
Clicking "Add Plan" from cart on plans page does nothing

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#7621]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/src.wordpress-develop.goldsounds.wpvm.io
2. Click the cart icon
3. Click "Add a plan"
4. Nothing happens
#### What I expected

Something happens? Or the button or cart shouldn't be there, perhaps.
#### What happened instead

The cart icon and button are there but do nothing.
#### Browser / OS version

OS X, Chrome 52
#### Screenshot / Video

https://cloudup.com/c-uJrRGx2SR

**Comment by hoverduck** [comment]
#bug-scrub

Closing - now it appears that if you open the cart on the Plans page the button reads "Add a Domain".  Conversely, if you open it on the Domains page it reads "Add a Plan", which should prevent you from getting into a 'load the same page' error.
