### ISSUE TITLE
`/subscriptions/comments`: Fix focus outline on comments row

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#76223]
- The row should not be focussable as a whole, but rather by each cell
    ![Image](https://user-images.githubusercontent.com/2019970/234300836-9b85ff99-1cd4-438e-8dd2-239005535875.png)

- Focus outlines on the row's edge cells have hidden overflow
   ![Image](https://user-images.githubusercontent.com/2019970/234300937-4cb9b497-9c6e-47a8-b4c0-ec4b7b11589f.png)
   ![Image](https://user-images.githubusercontent.com/2019970/234300936-c13c19a9-fd19-4b11-b9ad-d3acaecad020.png)

- The row's cells right-margin is not set. This results in the outlines appearing to close to the content of a cell to its right. 
![Image](https://user-images.githubusercontent.com/2019970/234300938-fcd94b53-6793-4b3d-9f3e-ef372eedbb1e.png)

## Related Discussions

**Comment by TimBroddin** [comment]
The focus overlap is still there
