### ISSUE TITLE
Subscription Management: Refine the GET comments subscriptions API response

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#76227]
More questions:
- How do we handle duplicated x-posts?
- How do we filter out what seems like revisions of a post, auto drafts and posts that are of non-post post types?

## Related Discussions
pdDOJh-1Kg-p2

## Related Issues
 https://github.com/Automattic/wp-calypso/issues/76678

**Comment by yansern** [comment]
Two related patches.
- D110588-code
- D110595-code

**Comment by yansern** [comment]
I'm considering this issue done with the merging of D110588-code, D110595-code and #77022.

As for count hiding, we might not restore it back as there is an ongoing design discussion to get rid of counts or move it elsewhere (stats summary under heading).

We'll recreate another issue for cleaning up the comment subscription table.

And any further changes in filtering can be in a separate issues.
