### ISSUE TITLE
Ecommerce Plugins on Legacy sites: Register plugins with WooCommerce.com after adding to site

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#76228]
When a site has new WooCommerce plugins added, we need to register those as a purchase on WooCommerce.com. We can probably follow the example set in this file to do so.

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Spynff%2Qjbbpbzzrepr%2Qznantre.cuc%3Se%3Qr5o180s5%2343-og

Related to #74012

**Comment by sixhours** [comment]
@andres-blanco , @valterlorran , and I met about this specific point today. We found we don't actually store the list of registered plugins in the site's transfer meta (that we could find), so we don't have a way to see exactly which plugins were registered on WC.com-- only the batch's order ID. This means we can't compare the list of plugins to install with the existing registered plugins to make sure there are no duplicate orders.

**Comment by sixhours** [comment]
Work on this is also happening in D108967-code

**Comment by andres-blanco** [comment]
The order on WC.com side is recreated if needed by the script D108967-code
