### ISSUE TITLE
/me throws an unexpected error

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#76250]
### Quick summary

Trying to access the profile page at /me throws a fatal error and doesn't proceed.

### Steps to reproduce

1. Either log into a new account, or use an existing account.
2. Navigate to wordpress.com/me

### What you expected to happen

The profile page should load and be editable.

### What actually happened

"We're sorry, but an unexpected error has occurred"

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Discovered when resolving an issue for a user in 42917386-hc. The user created a new account in an incognito window and could access that account's profile page. Current account in an incognito window fails, tested by the user and myself.

**Comment by bluefuton** [comment]
We discovered that this was a side-effect of https://github.com/Automattic/wp-calypso/pull/76167, and have reverted that PR in #76252.

**Comment by bluefuton** [comment]
Revert has now shipped to production. 🚢
