### ISSUE TITLE
Top Nav Bar: Weird background glow effect that appears when the top-nav bar reaches the section with background image

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#76273]
A weird background glow effect appears when the top-nav bar reaches the section with a background image.

This will be only visible to logged-in users.

**Comment by RT-1904129** [comment]
Hi @bogiii 
Can you please assign me this task?I have relevant experience in this I will contribute and complete this
Thanks & Regards
Rishabh Tripathi

**Comment by bogiii** [comment]
Hi @RT-1904129,

Thanks for your interest in helping us with this issue and improving the Calypso product! This issue has been mistakenly created in the wrong repo, and I will close it.

If you want to collaborate, here is the [Good First Issues](https://github.com/Automattic/wp-calypso/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) list so that you can take a look.

Best,
Bogdan
