### ISSUE TITLE
Site can't be deleted after eCommerce trial expires

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#76284]
### Quick summary

After an eCommerce trial expires, we limit the pages the user can interact with, and redirect them to the expired trial UI if it's not in the allowed list of pages. This prevents users from deleting the site if that's what they want to do.

### Steps to reproduce

1. You need to start with a site that has an expired eCommerce trial.
2. Try to navigate to `/settings/general/:siteSlug` - you should be redirected to the expired trial UI
3. Try to navigate to `/settings/delete-site/:siteSlug` - you should be redirected to the expired trial UI

### What you expected to happen

I should be able to use Calypso to delete my site.

### What actually happened

I am not able to access the UI to delete the site.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by daledupreez** [comment]
@FlorianBru, can you comment on whether you'd prefer us to allow general access to the General Settings page and the Delete Site page, or whether we should add a link to the expired trial page that allows users to access the Delete Site page?

**Comment by daledupreez** [comment]
My first pass at this in https://github.com/Automattic/wp-calypso/pull/76294 addresses most of the gaps here by making it possible to access `/export/` and `/settings/delete-site/` in Calypso, and adding buttons to get to those pages at the bottom of the expired trial page.

However, exports from still-Atomic sites need to happen via `/wp-admin/export.php`, so we need to add that as an allowed page/exception in the redirect logic that's implemented in `wc-calypso-bridge`.

**Comment by daledupreez** [comment]
The final piece of this was addressed in Automattic/wc-calypso-bridge#1104, which we merged last week.

**Comment by FlorianBru** [comment]
Hey @daledupreez Is there a way for me to test the current implementation? Or maybe you can share some screenshots with me?

**Comment by daledupreez** [comment]
I am reopening this issue as we still need a small update to Calypso to redirect to `/wp-admin/export.php` for Atomic sites now that we are no longer redirecting users away from that URL.

@FlorianBru, the expired trial screen now looks like the following (except for the button colours -- I changed my theme earlier today):
<img width="1181" alt="Screenshot 2023-05-05 at 13 58 13" src="https://user-images.githubusercontent.com/3376401/236452400-f24d97bf-c8a6-4bf7-84a3-7bc77633f79a.png">
