### ISSUE TITLE
Focus problem

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#76287]
> I also noticed that when editing a post with an existing map on it, I cannot focus on the map block properly. Clicking on the block doesn't bring its sidebar like with any other block like the old Map block. I think it may prove confusing for some. Only when you click on the marker itself, then on the marker elements, can you access the map block options.

Sometimes I couldn't focus on the block at all, no matter where I clicked. I had to reload the editor to make things work.

**Comment by TimBroddin** [comment]
Hey @jeherve ,

Can you elaborate a bit on this one? I've tried this, but I cannot reproduce this 

https://user-images.githubusercontent.com/528287/236401368-923f8eab-83be-4263-a98f-85e3fffec528.mp4

**Comment by jeherve** [comment]
I can't seem to reproduce anymore! I guess this can be closed now.

**Comment by TimBroddin** [comment]
Thanks for trying it again! I closed this issue.
