### ISSUE TITLE
Reader: pullquotes overlap author compact profile in new full post view

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#7630]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/read/feeds/27030/posts/1117210232

#### Screenshot / Video

<img width="629" alt="screen shot 2016-08-24 at 10 00 59" src="https://cloud.githubusercontent.com/assets/17325/17923071/8fb6742a-69e2-11e6-8585-6686b3dee6a3.png">

I suspect this is a regression caused by #7549.

**Comment by fraying** [comment]
This is a factor, I believe, only with Discover and Daily Post. (It's mentioned as "Change special CSS used by Daily Post and Discover to avoid collisions with sidebar" in Trello.)

Suggestion: Change the special CSS to put the left side marginalia on the right side. Check to make sure there aren't any other special CSS rules that could overlap with the new sidebar. (I swear I saw super-wide images somewhere.)

We also need to communicate this change to Editorial. 

Make sense?

**Comment by bluefuton** [comment]
I had a play with putting them on the right hand side but I'm not sure there's enough room over there unless we shuffle the sidebar leftwards significantly.

In the smaller breakpoints, we currently do this:

<img width="741" alt="screen shot 2016-08-25 at 16 06 49" src="https://cloud.githubusercontent.com/assets/17325/17974559/7b32ebda-6ade-11e6-80ea-f77bc4487337.png">

I suggest we use the same approach for pullquotes across the board.

**Comment by fraying** [comment]
LGTM!
