### ISSUE TITLE
`/subscriptions/sites`: Create "Email me new posts" toggle

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#76314]
// needs more context

![Image](https://user-images.githubusercontent.com/2019970/235080511-61dca804-52eb-4721-b63e-a3dad1c6dd61.png)

Design: inDLaEQV8jJ21O4WXawIsJ-fi-712_26668

**Comment by ivan-ottinger** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/76504.

**Comment by mashikag** [comment]
Duplicated by https://github.com/Automattic/wp-calypso/issues/76489
