### ISSUE TITLE
Site Assembler: update "unlock" modal design

### ISSUE THREAD

**Issue by davewhitley** [Automattic/wp-calypso#76319]
Make small tweaks to the design and copy of the "Unlock" modal shown in the Site Assembler when you select premium styles.

### Before

![image](https://user-images.githubusercontent.com/618551/234691651-f5df5ffe-cf10-4ee6-812a-a594a3d170f4.png)

### After

![image](https://user-images.githubusercontent.com/618551/234691727-1bb37cb0-ca0e-403a-8a9d-39a6cbde73a3.png)

Specs can be found here:

https://www.figma.com/file/7l53h5fxAUNjVRBQ82YFwn/Site-Assembler?node-id=3009-60582&t=vS8fTApZL8Q2PMkF-4

I'm not too concerned about font styles and colors, as long as we are using the standard variables.

**Comment by BogdanUngureanu** [comment]
Added some feedback about the design in pekYwv-1ax-p2#comment-1173 (posting here too for more visibility).

**Comment by autumnfjeld** [comment]
Closing this since
1) We just shipped updates to this modal https://github.com/Automattic/wp-calypso/pull/76528
2) Further adjustments will come in work associated with [Limited Global Styles flow review #1] pekYwv-1ax-p2, perhaps done in a T-rex project
