### ISSUE TITLE
Subscription Management: Add external user support on API endpoint for confirming comment subscription.

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#76313]
This used to be just a draft issue. 
Originally created by @yansern

**Comment by mashikag** [comment]
Was this task not done as part of implementing the Pending page?
cc @JuanLucha

**Comment by yansern** [comment]
API endpoint for confirming comment subscription - D108147-code
API endpoint for confirming site subscription - D107895-code
