### ISSUE TITLE
Editor domain upsell: Gray out the upsell behind the modal

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#76321]
See p1682496634800579-slack-CKZHG0QCR and p9Jlb4-6AL-p2#general-write

The domain upsell at the top of the editor isn't being grayed out like the editor, when the modal overlay is visible. 
Also, the z-index may be too high. See p1682515858354489/1682446289.812659-slack-C9EJ7KSGH and p9Jlb4-6AL-p2

Acceptance criteria:
- [ ] The domain upsell is grayed out like the editor, when the modal overlay is visible.
- [ ] The upsell has the correct z-index.

Screenshots:

![image](https://user-images.githubusercontent.com/87168/234777890-7d6f0258-8137-4e2e-91de-b690b6331489.png)
![image](https://user-images.githubusercontent.com/87168/234777916-1213a284-3eb0-481b-9245-365f89f9f340.png)

**Comment by simison** [comment]
You might be doing this already but make sure to use Z-index manager and correct index between right elements from https://github.com/WordPress/gutenberg/blob/3fc895725ddd53c93233713872fe34fc948c4b78/packages/base-styles/_z-index.scss

**Comment by lupus2k** [comment]
The problem with this is the Upsell is outside the Site Editor Iframe, so we need to capture when an overlay is opened to hide the Upsell.

**Comment by lupus2k** [comment]
As we don't know when a Modal is open or not inside the Iframe, we have to follow another approach for this issue. I'm thinking of continuing with [this approach](https://github.com/Automattic/wp-calypso/pull/72944). What do you think about it?
With this fix, it should also fix [this](https://github.com/Automattic/wp-calypso/issues/73445) and [this](https://github.com/Automattic/dotcom-forge/issues/1604)

**Comment by simison** [comment]
Site editor iframe is gone though, so suppose the upsell is no more as well (p7DVsv-h8i-p2).

The iframe still exists for page/post editor, but that is going away at some point too I'd assume (@mattwiebe can maybe elaborate on plans there). At least is has to go in one year from now when 3rd party cookies are no more.

Why wouldn't you ship the upsell in the editor though?

**Comment by simison** [comment]
Another place where this upsell is really awkward: 

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/87168/236195106-8aff5207-ab24-4fa6-b904-b229fa6c72e5.png">

**Comment by simison** [comment]
Spotted more:

<img width="1418" alt="Screenshot 2023-05-04 at 14 52 01" src="https://user-images.githubusercontent.com/87168/236196169-4f47059a-9ea1-4d05-b50e-67ead835537c.png">

<img width="1416" alt="Screenshot 2023-05-04 at 14 51 52" src="https://user-images.githubusercontent.com/87168/236196184-6567655e-ae11-457c-a768-79c2c8e724dd.png">

Weird help center situation:
<img width="893" alt="Screenshot 2023-05-04 at 14 51 32" src="https://user-images.githubusercontent.com/87168/236196198-ec35a054-3d36-4286-b583-dbff94c33c53.png">

"Distraction free" mode becomes less distraction free:

<img width="1415" alt="Screenshot 2023-05-04 at 14 52 21" src="https://user-images.githubusercontent.com/87168/236196263-100ca95b-9b69-471b-a558-29b35444fee5.png">

**Comment by lupus2k** [comment]
Definitely, the next step is to move the Upsell inside the editor, I will work on this in the next days ;)

**Comment by lupus2k** [comment]
Hey @simison, I created [this one](https://github.com/Automattic/wp-calypso/pull/72944) to move the upsell to `wpcom-block-editor`.
Can you take a look at it?
My only concern is with Atomic sites, it's not loading the CSS file 🤔

**Comment by simison** [comment]
@lupus2k thanks for the PR! Really nice to see this.

Typically for code we want in wp-admin (like editors) and shipped to both WP.com simple and Atomic sites, we use either [ETK](https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit) or [Jetpack](https://github.com/Automattic/jetpack). The former we've feature frozen (p58i-dox-p2), though.

The `wpcom-block-editor` scripts are a bit odd case and there mainly for infrastructure reasons to support the iframed editor, although we also ended up adding some features to it since ETK back then didn't exist yet and there was other friction with Jetpack plugin.

In Jetpack (or ETK) you can also use PHP, which you can use to avoid loading the upsell based on the conditions:

https://github.com/Automattic/wp-calypso/blob/669d6249c09cabe34149a515646fd0d332aa550a/client/components/domains/domain-upsell-callout/index.jsx#L47-L57

I think @obenland can give further guidance here.

**Comment by simison** [comment]
Opened, still an issue until https://github.com/Automattic/wp-calypso/pull/72944 or similar solution.

**Comment by lupus2k** [comment]
> Typically for code we want in wp-admin (like editors) and shipped to both WP.com simple and Atomic sites, we use either [ETK](https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit) or [Jetpack](https://github.com/Automattic/jetpack). The former we've feature frozen (p58i-dox-p2), though.

We created a new approach using ETK [here](https://github.com/Automattic/wp-calypso/pull/76855)

**Comment by lupus2k** [comment]
Reopened because we reverted [this one](https://github.com/Automattic/wp-calypso/pull/76855) because of a bug (p1684250921623969-slack-C02FMH4G8).

We already created a new PR with a fix [here](https://github.com/Automattic/wp-calypso/pull/76987)
