### ISSUE TITLE
Assembler: April 2023 copy updates

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#76333]
# Description

Following , [Colors & Fonts Walkthrough Tasks – Team Lego] pbxlJb-3EX-p2   a thorough copy review of the Assembler was done and is now ready for dev.

# Dev Tasks
Consult the Figma and make the "final" updates.

Figma: 7l53h5fxAUNjVRBQ82YFwn-fi-2424%3A60507

Look in the Final columns
> the “final” columns are now all done. If they are empty that means no change.
![image](https://user-images.githubusercontent.com/5665959/234762445-d75be9aa-bfd4-4939-abb0-566775527639.png)

Check with @autumnfjeld or @davewhitley if you have questions.

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/76528. And we will continue to improve the copy. See https://github.com/Automattic/wp-calypso/issues/76614
