### ISSUE TITLE
Patterns - Extract patterns from demo sites and themes into the Dotcom pattern library

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76338]
## What

Extract patterns from demo sites and themes into the Dotcom pattern library.

## Why

Because we need them all in the Dotcom library.

## How

Let's do it manually for now and learn how the process can be automated.

**Comment by taipeicoder** [comment]
Closing as it's a duplicate of https://github.com/Automattic/wp-calypso/issues/77127
