### ISSUE TITLE
Site Assembler - Patterns - Fix patterns with Jetpack blocks like forms and maps

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76343]
## What

Patterns with Jetpack blocks like forms and maps are not renderer.

|Assembler|Editor|
|---|---|
|![Image](https://user-images.githubusercontent.com/1881481/234809407-e27b5de0-8342-45ac-a4c9-a1fed9f8381c.png)|![Image](https://user-images.githubusercontent.com/1881481/234809132-25f93528-11cd-4d9a-b0e8-dc252a48b84b.png)|

## Why

It seems like Jetpack blocks are not ready for our server-side rendering system. 

## How

> The "Submit a form" link makes it seem like your server-side rendering is failing the jetpack_is_frontend() check [here](https://github.com/Automattic/jetpack/blob/a27cfebbccfec63dda77b550af5466eb22f581b7/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L524) or [here](https://github.com/Automattic/jetpack/blob/a27cfebbccfec63dda77b550af5466eb22f581b7/projects/packages/forms/src/contact-form/class-contact-form-plugin.php#L419), so you're getting the fallback rendering that's used for emails and notifications and such.

Find a way to workaround it and ask Jetpack for help. See p1681882551868759-slack-CBG1CP4EN and p1683021691694579-slack-CDLH4C1UZ

Test them in Horizon and remove the tag `assembler-waitlist` when they are fixed.

**Comment by arthur791004** [comment]
The blocks related to payments are not rendered correctly either, e.g. `jetpack/recurring-payments`

| Actual | Expected |
| - | - |
| <img width="300" src="https://user-images.githubusercontent.com/13596067/236412821-2772591a-bc98-4720-be2f-c122719c2338.png" /> | <img width="300" src="https://user-images.githubusercontent.com/13596067/236413125-515d26ee-b620-4705-b374-88e7b7d2b6e9.png" /> |

**Comment by arthur791004** [comment]
Related changes

* D109916-code
* D109531-code

**Comment by arthur791004** [comment]
This one is ready to close but we have to wait for the next release of the Jetpack since we made https://github.com/Automattic/jetpack/pull/30400

**Comment by arthur791004** [comment]
Closing it as the latest Jetpack is deployed to wpcom 🎉
