### ISSUE TITLE
`/subscriptions/comments`: Add P2 tag to each P2 site on the comments list

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#76356]
Similarly as with the Sites page, we want to include the blue P2 tag for P2 sites on the Comments page as well:

![Image](https://user-images.githubusercontent.com/25105483/234861155-6426d7a5-5412-4165-819a-6d1c9b009071.png)

Related PR (that adds the tag to the Sites page): https://github.com/Automattic/wp-calypso/pull/76239

**Comment by yansern** [comment]
Completed with the PR https://github.com/Automattic/wp-calypso/pull/77103.
