### ISSUE TITLE
Help Center: Remove useLaunchpadChecklist hook from Launchpad component

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#76362]
Once [backend code returning checklist from our main Launchpad endpoint](https://github.com/Automattic/jetpack/pull/30227) is deployed, we can update the help center launchpad component to use the data-stores/useLaunchpad hook rather than the help-center/useLaunchpadChecklist hook.

**Comment by sixhours** [comment]
`useLaunchpadChecklist` was removed from the inline help component in https://github.com/Automattic/wp-calypso/pull/76596 so I'm closing this out!
