### ISSUE TITLE
`/email-subscriptions/?option=blogs`: Redirect a logged-in user to Calypso Sites page when an attempt to access the re-skinned portal sites page is made

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#76396]
This issue should address the two following:
1. Redirect a logged-in user who enters `/email-subscriptions`, or `/email-subscriptions/?option=blogs`, into their browser path.
2. When a logged-in user is on the Comments page in the reskinned portal (`/email-subscriptions/?option=comments`), clicking on the Sites tab should take the user to the Calypso version of the portal.

**Comment by ivan-ottinger** [comment]
D109073-code is now merged and deployed.
