### ISSUE TITLE
Site Assembler - Restyle pattern cards to make them more appealing

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76407]
## What

Restyle pattern cards to make them more appealing.

## Why

So they pop up more.

## How

Add a drop shadow on the pattern cards as in the editor. `box-shadow: 0 15px 25px rgba(0,0,0,.07);`

![Image](https://user-images.githubusercontent.com/1881481/235117287-424eb7d3-52b0-4c40-8e3d-885fd4f28e45.png)

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/76759
