### ISSUE TITLE
New Post Emails: Verse block has white text on white background

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#76422]
### Quick summary

When a post has a verse block added, the new post email has all-white text for the verse block, making it illegible (white text on white background)
<img width="1530" alt="Screenshot on 2023-04-28 at 08:54:55" src="https://user-images.githubusercontent.com/41035049/235195707-77f4268c-6305-42fa-8cd9-ec639d883176.png">

### Steps to reproduce

1. On a simple site you are an email subscriber on, publish a new post that has a verse block and text within the block
2. Check the new post email to see the white text on white background

Happening on multiple themes (tested in Dyad 2 and Twenty Twenty-Three)

### What you expected to happen

The verse block text should be black.

### What actually happened

The text in the verse block is white.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Gutenberg: v15.6.2
Editing Toolkit: 3.63979
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.4

**Comment by khristiansnyder** [comment]
#6244390-zen for follow-up.

**Comment by wpshellbelle** [comment]
6236387-zen

**Comment by wpshellbelle** [comment]
43084635-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated just as described, on theme Twenty Twenty Three
- WordPress 6.2, Gutenberg Version 15.6.2

#### Screenshots/Recordings

![hKOyVR.gif](https://user-images.githubusercontent.com/27249804/235736432-0789cf72-a93c-473a-9ec1-9b4937dc1909.gif)

📌 ACTIONS
- Assigned to Apex

**Comment by christianguerrag** [comment]
Another report here 6259206-zen

**Comment by ktyfuller604** [comment]
[42740325-hc](42740325-hc) for follow-up please

**Comment by csabarakasz** [comment]
6253062-zd-woothemes - note, the issue is present with the Preformatted block as well, not only with the Verse block.

**Comment by carolframen** [comment]
Another one #6269632 (User has Twenty Sixteen theme, I tested it using Blank canvas)
I tested it using a background color to see what happened (black background, white font) and got a slightly different thing on the email. It is not showing the colors I chose, but I though I should mention it 🙂

![image](https://user-images.githubusercontent.com/119800062/236911324-b308c090-2d84-403a-965b-df3b6536ec7d.png)

**Comment by stronenv** [comment]
This bug is also present in the Invitation email when you invite a new user to the site: 
<img width="824" alt="Screenshot 2023-05-10 at 11 49 15" src="https://github.com/Automattic/wp-calypso/assets/70795294/d625ab3f-18ff-47a8-89e6-206bb69295fe">

Tested with both Private and Public sites and with multiple themes.

**Comment by jartes** [comment]
Another case on 6277878-zd-woothemes with the Preformatted block.

**Comment by foleynotrose** [comment]
Report of it affecting Inline Code Block: 6253745-zd-woothemes

**Comment by rakshitwesley** [comment]
Reported here with Preformatted block. : 6291720-zd-woothemes

**Comment by mdtanjid0** [comment]
- [ ] 6285599-zen - Preformatted Block.

**Comment by rw-ye** [comment]
Another report: 6250785-zd-woothemes

**Comment by pauljacobson** [comment]
I may have a related report where a user used a Preformatted Block. A subscriber reported a similar experience. I asked the user to try contact another subscriber to determine if they experienced this too.

Ref 29785551-hc

**Comment by carinapilar** [comment]
User from 42740325-hc was back asking for an update on 6304315-zd-woothemes.

**Comment by carolframen** [comment]
6304567-zen preformatted block

**Comment by cuemarie** [comment]
@Automattic/apex is this something y'all might have time to check out? We're starting to see more reports come in about the issue. Thanks!

**Comment by bobmatyas** [comment]
Multiple reports in the Jetpack forums: 

- https://wordpress.org/support/topic/email-white-text-on-a-white-background
- https://wordpress.org/support/topic/jetpack-emails-photo-caption-text-not-visible/?view=all

**Comment by danjjohnson** [comment]
In the second forum thread of the previous comment, it's happening on the image caption when using the Classic Editor plugin:

<img width="557" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1990037/3414ae9e-69d8-46b4-abfc-5e6424e48130">

**Comment by bobmatyas** [comment]
Report on 6271616-zen

![Annotation-Annotation on 2023-05-26 at 10-07-36 png](https://github.com/Automattic/wp-calypso/assets/45246438/cb24a5e0-45e7-4814-9234-28c88102c8f9)

![Annotation-Annotation on 2023-05-26 at 10-07-28 png](https://github.com/Automattic/wp-calypso/assets/45246438/87f5f473-03e4-4766-bcf7-31373a8c38fd)

Text is rendering as white on white in email templates. Text can be selected (second screenshot).

**Comment by TimBroddin** [comment]
A patch fixing this issue has been deployed: D112193-code
