### ISSUE TITLE
Some Retired Themes Can Be Selected in the Theme Gallery

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#76426]
### Quick summary

Some retired themes can be selected in the Theme Gallery.

For Simple Sites, if the activate button is clicked, confetti will shoot on the screen as though the theme was activated, but simultaneously a message `Theme not yet available for this site` will appear, and the theme is not activated.

For Atomic Sites, the theme is activated.

### Steps to reproduce

1. Create a Simple Site.
2. Search for a retired theme. For example, Nikau
3. Click on the theme, then click "Activate this design"

### What you expected to happen

The theme should not be available on simple sites. I'm not sure of the expected behavior on Atomic sites.

### What actually happened

The theme is available, and an error message is displayed if the user attempts to activate it.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by masperber** [comment]
Customer report: 28249613-hc

**Comment by nicolynramos** [comment]
User report: 42060823-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated** - Themes in showcase (marked "Premium") and error when activating
- Tested on Atomic – **Replicated** - Themes in showcase (marked "Premium"), but no error when activating

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated with Nikau theme on simple site, using a non-staff WordPress.com account.
- AT site activated the theme without any error

#### Screenshots/Recordings

**Simple Site**

https://user-images.githubusercontent.com/27249804/235218350-2b53e605-4798-4029-a4c5-21755fc1161e.mp4

**Atomic Site**

https://user-images.githubusercontent.com/27249804/235218413-6a88b741-81e3-47a4-866e-8bde113483c6.mp4

📌 ACTIONS
- Assigned to @Automattic/lego

**Comment by masperber** [comment]
@cuemarie is it expected behavior for the retired themes to be available on Atomic?

**Comment by cuemarie** [comment]
@masperber It's a little harder to tell there - they probably shouldn't be listed as Premium themes in our showcase though, that's true.  If the themes are still managed by their providers then they are just third-party themes.  Since the error doesn't present in the same way, I was specifically tagging/reporting for that, - I'll update my notes a bit! Lego will I'm sure look into both environments either way 👍

**Comment by ccwalburn** [comment]
Customer report: 41788317-hc

**Comment by isocialtish** [comment]
Another WordPress.com customer report for The Four theme 40408637-hc

**Comment by taipeicoder** [comment]
Proposed a fix in D109441-code

**Comment by taipeicoder** [comment]
Closing as this issue seems to be fixed. Please reopen if other instances of this issue occurs again, thanks!
