### ISSUE TITLE
Subscriber import form yelds an error

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#76421]
### Quick summary

There's a React console error coming from Subscriber import form:

<img width="1627" alt="Screenshot 2023-04-28 at 18 45 30" src="https://user-images.githubusercontent.com/87168/235193760-228ad94c-48dd-4e1d-915e-10f83fa11ee6.png">

See HTML:

<img width="1196" alt="Screenshot 2023-04-28 at 18 45 40" src="https://user-images.githubusercontent.com/87168/235193781-e041cb4c-136a-47e5-8ce0-85ee6b1baaca.png">

Something here?
https://github.com/Automattic/wp-calypso/blob/8d14d55b2f35d5f83e6b6882319135bc1f833285/packages/subscriber/src/components/add-form/index.tsx#L378-L410

### Steps to reproduce

1. At Calypso localhost development, got to /setup/newsletter
2. Go to Subscribe step
3. See console

### What you expected to happen

—

### What actually happened

—

### Impact

All

### Available workarounds?

There is no user impact

### Logs or notes

@Automattic/caribou can you take a look? Nothing urgent but nice to clean these up, should be simple.

Perhaps instead of `<button>`s those links could be `<a>`s?

**Comment by vishnugopal** [comment]
cc @bogiii to self-assign and take a look when you get time. Thanks!
