### ISSUE TITLE
FSE: Unpublished posts and pages default to incorrect template on Simple sites using custom domains

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/wp-calypso#76440]
### Quick summary

New and unpublished posts and pages are defaulting to the 404 template. Posts do appear correctly on the live site but the editor says post/page uses the 404 template instead of the Single (post) or Page (page) template. 

### Steps to reproduce

1. Activate a Site Editing theme, such as Russell
2. Create a new post or new page 
3. See default template is set to 404 

### What you expected to happen

Expected the default template to be set on the new page or post (single or page) 

### What actually happened

New pages and posts default to 404 template 

https://user-images.githubusercontent.com/77413972/235328599-69a9b771-24e7-4543-837a-88734171ac8d.mp4

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by wpshellbelle** [comment]
Some notes: I had to SSP to duplicate issue on users' sites. Noticed issue on user's sites on themes Russell and Twenty Twenty-Three

Found at: 6241898-zen and 6237913-zen

**Comment by rickmgithub** [comment]
6240233-zen  User provided screenshots as well

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic –Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on a test Simple site with theme **Twenty Twenty Three**.
- The live site displays the content on the correct template, but if I try editing the template via the post/page editor, I'm taken to the 404 template - this could lead to some confusion and unneeded changes for users trying to "fix" things.
- **Once published**, the correct default template is displayed in the editor.

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/235485040-d0eccc9b-6453-4d50-aa58-a84bebbd93a5.mp4

📌 ACTIONS
- Assigned to Cylon
- Escalated here: p1682957800198599-slack-C01LXBU1N21

**Comment by wpshellbelle** [comment]
6276197-zen

**Comment by cuemarie** [comment]
Escalated here: p1683666696966989-slack-C02FMH4G8

**Comment by kimerlin81** [comment]
Another case: 6271984-zd
Theme: Masu
Plan: Personal

**Comment by liviopv** [comment]
- [ ] 6281712-zd-woothemes (Geologist)
- [ ] 6271222-zd-woothemes (TT3)

The template not loading in the editor causes the loss of Full Width and Wide Width alignment in blocks that should support it.

![CleanShot 2023-05-11 at 14 59 25@2x](https://github.com/Automattic/wp-calypso/assets/14153300/4dfe0dbc-36dc-422a-a974-5cafc20379ee)

**Comment by edequalsawesome** [comment]
Wrong template and alignment issue was also reported in 43382190-hc, please follow-up when this is resolved in 6283553-zen

Additonal report in 28109481-hc, with a follow-up requested in 6271442-zen

**Comment by wpshellbelle** [comment]
6249117-zen - please follow up with this user once resolved.

**Comment by tanjoymor** [comment]
I ran into this issue with a customer on their pages, but publishing the page resolved it and the published page updated to the correct "Page" template for the customer. 43499928-hc Storia theme (couldn't replicate through SU and didn't realize it was a bug)

There's another customer with the same issue on a draft post 6290142-zen and I was able to see it via SSP (not SU):

![YBOG0P.png](https://github.com/Automattic/wp-calypso/assets/42655541/ea787748-86b8-4c7e-813d-915c1ce35790)

This one is using the Attar theme. I've been unable to replicate the issue on any of my Simple test sites with Russell or Attar in order to confirm if publishing does in fact resolve the incorrect template assignment, but I see above that Marie did confirm this.

**Comment by cuemarie** [comment]
Further testing today suggests this is specific to **Simple Sites with Custom Domains set as Primary**:


https://github.com/Automattic/wp-calypso/assets/27249804/0b6372e5-1f64-4443-ab00-c030dab76154

**Comment by donalirl** [comment]
Reported also by a user in #6313744-zen on the Zoologist theme, simple site, with custom domain as primary.

**Comment by edequalsawesome** [comment]
Also reported in 6316397-zen with the Tù theme on a site with a custom domain, but changing the primary domain back to the `*.wordpress.com` domain didn't resolve the issue, unfortunately.

**Comment by jartes** [comment]
Another report on 6315024-zd-woothemes, using the `Iotix` theme and a custom domain as the primary address.

**Comment by cuemarie** [comment]
Tested today on Simple Site with custom domain, and the problem no longer presents:

- Gutenberg: v16.0.0-rc.5

https://github.com/Automattic/wp-calypso/assets/27249804/588401e3-e379-461a-adae-5cb80219434d

📌 ACTIONS
- Closing as resolved
