### ISSUE TITLE
Newsletter: ensure copy between "setup" and "post-setup" are identical

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#76448]
It's a bit unfortunate these steps are basically duplicate, so it's hard to keep them in sync.

https://github.com/Automattic/wp-calypso/blob/f458b29062af33638887003fe3a2baa35b7cd41e/client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-post-setup/index.tsx#L31-L36

https://github.com/Automattic/wp-calypso/blob/f458b29062af33638887003fe3a2baa35b7cd41e/client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx#L31-L40

**Comment by simison** [comment]
Mostly done in https://github.com/Automattic/wp-calypso/pull/76283

**Comment by simison** [comment]
@crisbusquets we can update the headers & button copy to match, unless there's any reason to keep these separate?

These used to be way different but I synced most of the labels to be same already.

During onboarding:

<img width="1514" alt="Screenshot 2023-05-09 at 15 10 15" src="https://github.com/Automattic/wp-calypso/assets/87168/678c248e-ab02-4a0a-a50e-338da194a23c">


After going through onboarding, and clicking back to setup step from the launchpad:

<img width="1512" alt="Screenshot 2023-05-09 at 15 10 01" src="https://github.com/Automattic/wp-calypso/assets/87168/44b95517-4ff0-430b-9def-c3b07026bbe1">

**Comment by crisbusquets** [comment]
> @crisbusquets we can update the headers & button copy to match, unless there's any reason to keep these separate?
> 
> These used to be way different but I synced most of the labels to be same already.

+1 to match buttons. `Continue` feels more natural.
