### ISSUE TITLE
Site Assembler - Show the category title and description in the patterns panel

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76443]
## What

- Create a description for all categories so we can standardize the UX in the editor and the assembler.
- Show the category description on the top of the pattern list as in the Editor. 

## Why

The category description can help users to understand what each category means.

## How

Create a description for all categories. See pekYwv-1kJ-p2#comment-948

Show the title and description in the assembler as in the editor.

![Image](https://user-images.githubusercontent.com/1881481/235411018-526ea537-0872-4500-b7bb-2c74a6cfcf9b.png)

**Comment by autumnfjeld** [comment]
We have copy updates from Francisco, so we can start dev work on this.   p1683570747538799/1683552689.470639-slack-CRWCHQGUB

**Comment by miksansegundo** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/77087
