### ISSUE TITLE
Site Assembler - Update categories in assembler and editor

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76451]
### Keep most useful/cool/popular at the top and the rest ordered alphabetically

1. **All**
2. **Basic**
3. **Blog**
4. **Call to Action**
5. **Image Gallery**

The rest will be ordered alphabetically.

### Categories that will be hidden/removed

We’ll hide them in simple sites but could still appear in Atomic sites because core patterns and plugins can still use them.

- **Posts**
We’ll use “Blog” instead

- **Sidebar**
We’ll create “Columns” instead

- **Wireframe**
We’ll create “Basic” instead

- **Gallery/Image/Photography**
We’ll create “Image Gallery” instead

- **CV/Portfolio**
We’ll remove it and keep “Portfolio”

- **Editorial**
We’ll remove it and use “Text” and “Image Gallery” instead

### Categories that will be created/renamed

- **View All**
Will contain all patterns in the same list

- **Basic**
Will contain “Wireframe” patterns

- **Image Gallery**
Will contain “Gallery/Image/Photography” patterns

- **Text**
Will contain patterns with mostly text.

### Reassign patterns to most relevant categories 

Reorganize existing patterns to make sure they’re in the best and most relevant categories.

**Comment by alaczek** [comment]
> Reorganize existing patterns to make sure they’re in the best and most relevant categories.
To be clear - this means going to the source site and re-categorizing them? Who is going to do this? :)

**Comment by miksansegundo** [comment]
> Reorganize existing patterns to make sure they’re in the best and most relevant categories.
To be clear - this means going to the source site and re-categorizing them? Who is going to do this? :)

@alaczek I will do it and ask you for reviewing it when ready and help if needed.

**Comment by miksansegundo** [comment]
These tasks are done with some minor adjustments on the category names for simplicity and have more alignment with other labels used in WordPress.

 - `All` rather than `View All`
 - `Blog Posts` rather than `Blog`
 - `Gallery` rather than `Image Gallery`

Here is the result:

<img width="338" alt="Screenshot 2566-05-16 at 19 19 10" src="https://github.com/Automattic/wp-calypso/assets/1881481/13e5f5c4-ab4f-47f0-bb17-6f26269c2693">



I'll follow up with a PR for Gutenberg to give us the ability to customize the categories order.
