### ISSUE TITLE
Launchpad: Delete launchpad.php plugin from wpcom

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#76473]
### Details

Once all the logic from wpcom/laucnchpad.php is moved to Jetpack (see this PR https://github.com/Automattic/jetpack/pull/30365), we can delete the launchpad.php plugin from wpcom.

**Comment by sixhours** [comment]
D111041-code

**Comment by daledupreez** [comment]
For reference, the actual changes in Jetpack were handled via https://github.com/Automattic/jetpack/pull/30397.

**Comment by sixhours** [comment]
The plugin has been removed from wpcom, so closing this out!
