### ISSUE TITLE
Conversion: Add Expanded Google Analytics Nudge

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7647]
Breaking up #7330

We should expand the nudge for Google Analytics to be more informative. It should look something more like the Advanced SEO nudge in #7540 and be self contained. When you hit upgrade it will add the plan directly to your cart.

![screen shot 2016-08-24 at 12 29 20](https://cloud.githubusercontent.com/assets/1464705/17944892/6c6b3ffa-69f6-11e6-92de-6c5138480495.png)

/cc @rralian

**Comment by artpi** [comment]
I'm unassigning myself here, because #7672 is ready for review. Once its merged, this task should be a breeze.
