### ISSUE TITLE
Conversion: Add Expanded Front-End No Ads Nudge

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7649]
Breaking up #7330

This is what our no ads nudge currently looks like on the front end:

![screen shot 2016-08-24 at 12 41 13](https://cloud.githubusercontent.com/assets/1464705/17945292/0dcccc50-69f8-11e6-9ba1-5a05b9147a8f.png)

Let's bring this in line with our expanded nudges, and sell the personal plan here:

![screen shot 2016-08-24 at 13 00 52](https://cloud.githubusercontent.com/assets/1464705/17945920/cce35a6c-69fa-11e6-9fd9-1ded000c000b.png)

We need to make sure the pricing is synced. If they don't have an existing domain, we should send them to the cart when hitting upgrade. I think if they already have purchased a domain, we should present the same nudge as in #7329. This would instead purchase when hitting upgrade since we have their cc details.

**Comment by dmsnell** [comment]
@apeatling do you know where this nudge is shown? I tried searching in the code and couldn't find it

**Comment by apeatling** [comment]
This is shown on the front end of sites, where we should advertising. This will be a task outside of calypso, so you'll need to search the PHP codebase.

**Comment by dmsnell** [comment]
@apeatling I noticed that in the preview the dismiss button is missing. was this intentional?

**Comment by apeatling** [comment]
No there should be a white dismiss button here as well, good catch.

**Comment by dmsnell** [comment]
Tracking in D2697

**Comment by dmsnell** [comment]
> This would instead purchase when hitting upgrade since we have their cc details.

That's kind of sneaky/unscrupulous isn't it, @apeatling?

Besides, it seems like it would lead to a higher number of refunds anyway because of how many people would click on that expecting a checkout page with a confirmation button and be surprised to find out that we already took their money without making sure they understood that we were doing so.

**Comment by apeatling** [comment]
This is the same as the domain to plan upgrade nudge in cases where they already have a domain.

We should update this mockup to match what we have changed there. Add the credit card last four digits, as well as make sure there is a clear link in the next screen where they can reverse the payment instantly.

**Comment by dmsnell** [comment]
@apeatling I think this never went anywhere so I'm closing.
