### ISSUE TITLE
Subscriptions Management: Make use of the color profile set by the user

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#76490]
The Subscriptions Management portal should use colors that come from the color profile the user has set in `https://wordpress.com/me/account`:

![Image](https://user-images.githubusercontent.com/25105483/235641808-a57dee8a-c6b8-45e2-986f-a5c4b2c8c4d1.png)

For instance, the color of toggles should reflect the color profile:

![Image](https://user-images.githubusercontent.com/25105483/235641943-92987cfd-d997-40f2-858f-29a0274d0918.png)

For external users (users that don't have WPCOM account), the default colors can be used.

Related discussion: inDLaEQV8jJ21O4WXawIsJ-fi-712:26668.

**Comment by ivan-ottinger** [comment]
The color overrides for components have been added in https://github.com/Automattic/wp-calypso/pull/48515. Looks like that our app is not utilizing them.

By importing the main styles with `import 'calypso/assets/stylesheets/style.scss';` in `client/landing/subscriptions/index.tsx` we get the primary color CSS variable applied to the Toggle component for instance, but this variable is still holding the default blue color - even when the user has changed their color profile setting.

This means there's something more in play we need to adjust to have our components in the Subscriptions Management use the correct colors.

**Comment by yansern** [comment]
With External Portal gone, the Reader Portal inherits this automatically.

<img width="667" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/4aff38f5-34a7-43e0-aac6-cafbc828cf32">
