### ISSUE TITLE
Conversion: Add Expanded Support Nudge

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7651]
Breaking up #7330

We should introduce a nudge for better live chat and email support. It should look something more like the Advanced SEO nudge in #7540 and be self contained. When you hit upgrade it will add the plan directly to your cart.

![screen shot 2016-08-24 at 13 24 03](https://cloud.githubusercontent.com/assets/1464705/17946645/0aa45ac4-69fe-11e6-8bfb-0a04461c9ff3.png)

**Comment by artpi** [comment]
I'm unassigning myself here, because #7672 is ready for review. Once its merged, this task should be a breeze.

**Comment by dmsnell** [comment]
❓ for you @artpi. If we want to put this on `/help` then we won't have a selected site and that appears to be breaking the nudge. do you think there's a straightforward way to check if the user has any sites with the necessary plan level to display/disqualify seeing this?

support stuff usually goes at the user level and not the site level

**Comment by apeatling** [comment]
Since there isn’t a site selected, probably needs to show the picker first, if it is not a one site account.

**Comment by dmsnell** [comment]
@apeatling how would that work though? suppose we have a user with five free sites who selects `Help`. Do we change the help flow to make them pick a site? Won't they pick a random site? Would it make more sense to have them pick a site when upgrading?

**Comment by apeatling** [comment]
Lets limit this to users that only have free sites. If they have one paid site and other free sites, let's not show the nudge to keep it simple.

So if a user has five free sites, we can show the nudge here. If they click the Upgrade button, then take them to full page site picker you see when you don't have a site selected in Calypso. Once they have picked the site, the plan should be added to the cart and straight to checkout.

**Comment by apeatling** [comment]
If they have only one free site, you can just switch straight to that site and do the same, add it to the cart and take them to checkout.

**Comment by dmsnell** [comment]
> we can show the nudge here

where is here?

**Comment by apeatling** [comment]
In /help as mentioned above.

**Comment by artpi** [comment]
@dmsnell : To resolve it, I would hack `mapStateToProps` in `nudge-expanded` in a way that lets you explicitly pass a site. And in case of your conundrum, I would pass user primary site there.

Also, you will need to provide explicit upgrade action so the link leads to a proper place. (I dont know what is that place if no site is selected)

**Comment by dmsnell** [comment]
> I would pass user primary site there

the problem I see with this @artpi is that someone's primary site may be a free site but they may still have a business plan site, for example

hacking `mapStateToProps` could work, but I guess we'd need to scan through the full list of a user's sites until we find a site with the right plan level else assume it doesn't exist and then pick the primary site…

**Comment by apeatling** [comment]
Don't assume anything here, send them first to the full screen picker you see on other pages when you do not have a site set in the URL.

**Comment by artpi** [comment]
Should this be part of #7853 test?

**Comment by artpi** [comment]
Since the test was a bit of a failure, I wil shelve this task.
Background: p3fqKv-3Ew-code
