### ISSUE TITLE
Choosing a virtual theme in the launchpad doesn't switch themes

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#76530]
### Quick summary

After choosing a theme, switching to a virtual theme via the launchpad doesn't actually work.

https://user-images.githubusercontent.com/93301/235859724-9efb9b5f-110c-495c-832f-76eae4938572.mov

Initially raised here: p1683040216008939-slack-C048CUFRGFQ

### Steps to reproduce

1. Go through onboarding at wordpress.com/start choosing a theme 
2. Once you enter the launchpad select the completed 'Select a design' step
3. Choose a virtual theme (one prefixed with Blank Canvas - )

### What you expected to happen

1. To go back to the launchpad which will display a preview of the newly selected virtual theme
2. To go into the site admin and see that the theme has been switched to the newly selected virtual theme

### What actually happened

1. Went back to the launchpad which continued to display a preview of the originally selected theme
2. Went into the site admin and saw that the theme was still the originally selected theme

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

I can't see any POST requests to change the theme in the browser tools network tab. 

For non-virtual themes there is a POST and the theme switch does happen.

**Comment by mmtr** [comment]
I think this is a symptom of the site assembler not being ready yet to perform theme switches (https://github.com/Automattic/wp-calypso/pull/72286#issuecomment-1409607312, p1675128979469429-slack-C048CUFRGFQ).

Adding theme switches support sounds like a project on its own, so the quick fix would be to either exclude virtual themes (they use the site assembler) from the design picker if the site has been already created, or disable the ability to switch themes if the site selected a virtual theme.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to go back and choose another FSE theme via the launchpad, but could not successfully switch to a virtual theme prefixed with "Blank Canvas", such as **Blank Canvas - Single Page**.

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/235994496-e7770825-faff-40bf-b89b-63afc0e28dd5.mp4

📌 ACTIONS
- Assigned to T-Rex
