### ISSUE TITLE
Conversion: Add a nudge when purchasing an a8c or woo theme

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7653]
Breaking up #7330

We are in the process of adding a8c and woo premium themes (27 of them) to plans only. This is likely around one month away from now before it's ready. We can still work on the nudge in the meantime.

When a user clicks to purchase a theme and is promoted to buy a plan, we should present a nudge that promotes the premium plan in this view.

I think we could also show a more generic nudge in themes, promoting the bundle of 27 themes if you purchase a plan, and linking to a view of all the themes that you'd gain access to.

We need some more design thoughts here as to how this could look. There is an existing mockup from @drw158 in #4229 for all themes in plans.

/cc @folletto @ianstewart

**Comment by folletto** [comment]
> I think we could also show a more generic nudge in themes, promoting the bundle of 27 themes if you purchase a plan, and linking to a view of all the themes that you'd gain access to.

I'd just note that we already have a fairly intrusive nudge there, so I'd rather start out by swapping that with this one, and see how they perform. The design in #4429 has some good comments there too that contextualize them, but I feel given the current structure, we can start with swapping the existing one and see the data we get.

Existing one:

![screen shot 2016-08-26 at 17 42 43](https://cloud.githubusercontent.com/assets/4389/18013087/825bec96-6bb4-11e6-9bec-4afe367a3ddd.png)
