### ISSUE TITLE
Site creation: don't assign a random value for default theme, use most current core theme e.g. TT3

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#76564]
# Description
* Read :
  * [What happens when we “just turn off Headstart”?] pbxlJb-10W-p2 
  * Comment from Phil pbxlJb-10W-p2#comment-2050
  * Comment from @michaeldcain pbxlJb-10W-p2#comment-2051 
    * his diff D91417-code  

> Currently, the mechanism used by core for [setting the default theme for new sites is the WP_DEFAULT_THEME constant](https://href.li/?https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/schema.php#L373).
On wpcom [we set this constant in the .config files](uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2S.pbasvt%2Sjcpbz%2Qbcgvbaf.cuc%3Se%3Q9rpp1o7n%23887-og). Low and behold it gets assigned a random value!

As a result, this site creation code behavior skews the `old_theme` data in tracks event `wpcom_theme_switch`

![Image](https://user-images.githubusercontent.com/5665959/236076983-31b47c2f-61f9-4ea4-a1c4-073e5023a8eb.png)

Note the "default theme" terminology confusion:  We have  [wpcom core default ](fbhepr%2Skers%2Sjcpbz%2S.pbasvt%2Sjcpbz%2Qbcgvbaf.cuc%3Se%3Q9rpp1o7n%23887-og) and also the[ calypso signup default](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/signup/site-type.js#L7)).    Should we figure out a way to only source from the wpcom default?  

**Related**
* https://github.com/Automattic/wp-calypso/issues/70604

# Dev Tasks
- [x] Understand best path forward for fixing
  - [x]  Is it simply removing this [random functionality ](fbhepr%2Skers%2Sjcpbz%2S.pbasvt%2Sjcpbz%2Qbcgvbaf.cuc%3Se%3Q47p2578r%26sv%3Qjcpbz_nyg_qrsnhyg_gurzr%23889-og) and using  TT3?
  - [x] How do we make sure this gets properly maintainted? Updated every year? We could have a clever string generator since we know what the core theme will be named. 😄  e.g. twentytwentyfour comes next

@Automattic/lego

**Comment by autumnfjeld** [comment]
We could detect if twentytwentyfour is in /pub and then that will be picked up as the default?!?! 😄

**Comment by arthur791004** [comment]
> Is it simply removing this [random functionality ](https://github.com/Automattic/wp-calypso/issues/fbhepr%2Skers%2Sjcpbz%2S.pbasvt%2Sjcpbz%2Qbcgvbaf.cuc%3Se%3Q47p2578r%26sv%3Qjcpbz_nyg_qrsnhyg_gurzr%23889-og)and using TT3?

It's completed via D109689-code cc @Automattic/t-rex 

> How do we make sure this gets properly maintainted? Updated every year? We could have a clever string generator since we know what the core theme will be named. 😄 e.g. twentytwentyfour comes next

One way is to use the [get_core_default_theme](https://github.com/WordPress/wordpress-develop/blob/d62f8581899be84fd59b987571b6c7b5d42db12e/src/wp-includes/class-wp-theme.php#L1576) function to get the default theme. Core has a list of the [default themes](https://github.com/WordPress/wordpress-develop/blob/d62f8581899be84fd59b987571b6c7b5d42db12e/src/wp-includes/class-wp-theme.php#L1576) and they will update the list 😆

**Comment by arthur791004** [comment]
Working on https://github.com/Automattic/wp-calypso/pull/76656 to centralize the default theme definition on wpcom instead of Calypso

**Comment by BogdanUngureanu** [comment]
> One way is to use the [get_core_default_theme](https://github.com/WordPress/wordpress-develop/blob/d62f8581899be84fd59b987571b6c7b5d42db12e/src/wp-includes/class-wp-theme.php#L1576) function to get the default theme. Core has a list of the [default themes](https://github.com/WordPress/wordpress-develop/blob/d62f8581899be84fd59b987571b6c7b5d42db12e/src/wp-includes/class-wp-theme.php#L1576) and they will update the list 😆

We've already tried to use that core method but it's not working for WPCOM because the themes have to be prefixed with `pub`. That method also checks if the theme exists (without the `pub` prefix), and because it doesn't, it returns twenty ten 😅 . 

The only solution (and the simplest) is just to rely on the WP_DEFAULT_THEME constant, which is currently hardcoded to TT3, and update it manually when a new default theme is released. 😅

**Comment by BogdanUngureanu** [comment]
Also, we haven't found a way to modify the hardcoded list of themes since there's no filter for it and the class is final.

**Comment by arthur791004** [comment]
Oh yes, I forgot we need the prefix for the theme 😓

**Comment by arthur791004** [comment]
Close it via D109689-code and we can update it manually when a new default theme is released 🙂
