### ISSUE TITLE
Bug: Assembler font selection not working

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#76578]
# Description

Unfortunately for me fonts selection in the Assembler not working is a reoccurring issue for me.  It is also intermitent, earlier today fonts _seemed_ to be working fine.   Perhaps the root problems are different now than a few weeks ago.  Can't be sure.  Since this is a bug in production I'd like to address it ASAP.  Thank you!

This happens for both brand new sites and existing site I used with feature flag e.g. https://wordpress.com/setup/site-setup/patternAssembler?flags=signup&siteSlug=auttestbcpa.wordpress.com

Here is what is happened on 4 May 2023:

https://user-images.githubusercontent.com/5665959/236154328-6905b316-af34-432e-9b74-5b5a9443b8a9.mp4

![Image](https://user-images.githubusercontent.com/5665959/236154079-69f1a470-758b-452e-bd74-dec981a7e673.png)

Another Test starting from site creation

https://user-images.githubusercontent.com/5665959/236160520-4a5a17a3-78c9-42a3-8330-317c33dd1fd0.mp4

**Comment by arthur791004** [comment]
Closing it via D109531-code
