### ISSUE TITLE
Subscription management flows over on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#76576]
### Quick summary

Subscription management page flows over on mobile screens

### Steps to reproduce

On mobile device...
1. Subscribe to a blog
2. Get subscription confirmation email
    
    <img width="320" src="https://user-images.githubusercontent.com/87168/236140831-ea9a2378-edb4-4880-812d-5bb945298a0a.png" alt="" />

3. Clicking confirm, see how the following page overflows

    <img width="320" src="https://user-images.githubusercontent.com/87168/236140969-316e3d26-b177-4c67-92b8-fcea001d727e.png" alt="" />
 
    <img width="320" src="https://user-images.githubusercontent.com/87168/236141011-7faf5e2b-2472-42c3-952f-8ee789d99f77.png" alt="" />

### What you expected to happen

Smoother experience on mobile.

### What actually happened

Broken mobile visuals.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

@Automattic/apex could you take a look at this while you're working on these interfaces? Thanks!

**Comment by simison** [comment]
BTW I also didn't get any confirmation/congrats that I've subscribed. Only the management page, which was a bit of let-down. (cc @saygunnyc )

I also had to press "confirm" from the email twice — on first time I just saw Calypso W loader and it was hanging out there for such a long time that I thought it broke.

**Comment by mashikag** [comment]
> @Automattic/apex could you take a look at this while you're working on these interfaces? Thanks!

I am looking into this now. 👀

**Comment by mashikag** [comment]
> I also had to press "confirm" from the email twice — on first time I just saw Calypso W loader and it was hanging out there for such a long time that I thought it broke.

I am not able to reproduce this specific issue myself. Did this only happen once to you? Did you have a chance to test it more than once? 🤔

**Comment by mashikag** [comment]
> ### What you expected to happen
> Smoother experience on mobile.

Would making only the tabs' container horizontally scrollable be a satisfactory resolution?

**Comment by simison** [comment]
Sure! I can still replicate:

- Android phone
- Firefox installed; the link seems to be opening in "in app browser" but it seems to be Firefox, not Android's webview which I think is Chrome based:
     <img src="https://user-images.githubusercontent.com/87168/236236518-0145ce42-fc5b-4943-9215-26a4d25fd87b.jpg"  width="320" />
- Opening the link from my personal email's using Gmail
- My WP.com account is a8c account, non proxied. Not logged in.
- The URL is `https://wordpress.com/subscriptions/sites/en`
- I can replicate on Firefox browser — note how tabs are flowing over:
    <img width="755" alt="image" src="https://user-images.githubusercontent.com/87168/236237246-5dac6701-09bd-4b8d-baac-ddbcb37a4ec2.png">

    <img width="434" alt="image" src="https://user-images.githubusercontent.com/87168/236237489-e1b7c0f1-8043-474d-815a-81a53541fa10.png">

**Comment by simison** [comment]
> Would making only the tabs' container horizontally scrollable be a satisfactory resolution?

Check with Saygun for what makes sense but I think it should either flow onto multiple lines or collapse into dropdown like we do elsewhere:

https://user-images.githubusercontent.com/87168/236238549-441cbede-8d63-4b35-a950-c55eab2cabea.mov

Horizontal scrolling is cumbersome and hard to notice it's there without strong visual cues.

**Comment by mashikag** [comment]
> I can replicate on Firefox browser — note how tabs are flowing over:

Yes, I can replicate the overflow issue too. 
I was asking specifically about the issue where you press the link in your email, and then you just see the Calypso loader. You talked about the issue in [the comment](https://github.com/Automattic/wp-calypso/issues/76576#issuecomment-1534238256).

**Comment by simison** [comment]
Ah sorry, I couldn't replicate that anymore. :-( I'll be testing subscriptions a lot so I'll keep eyes open if it happens again!

**Comment by saygunnyc** [comment]
Thanks for reporting, @simison. Yes, it does make sense to follow the existing pattern here.
