### ISSUE TITLE
Create <ExpandedNudge> component

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#7659]
Breakout Expanded Nudge component introduced by @rodrigoi in https://github.com/Automattic/wp-calypso/pull/7563

To be used in: 
- https://github.com/Automattic/wp-calypso/issues/7648
- https://github.com/Automattic/wp-calypso/issues/7651
- https://github.com/Automattic/wp-calypso/issues/7647

**Comment by dmsnell** [comment]
@artpi should this issue be resolved by the merge of #7672?

**Comment by artpi** [comment]
@dmsnell : Yes, closing :)
