### ISSUE TITLE
Help Center: Delete unused useLaunchpadChecklist hook

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#76597]
### Details

We'll be refactoring all calypso code to use the new useLaunchpad hook in data-stores to fetch Launchpad-related data. Once we've removed all instances where we're using the packaages / help-center / useLaunchpadChecklist hook, we'll want to delete this hook.

**Comment by RT-1904129** [comment]
Hi Team
Can you please assign me this task?I have relevant experience in this I will contribute and complete this
Thanks & Regards
Rishabh Tripathi

**Comment by sixhours** [comment]
this was removed in #77281
