### ISSUE TITLE
Reader: slideshows don't work in the Reader

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#766]
Steps to reproduce:
1. Start a new post at https://wordpress.com/post
2. Add a slideshow
3. Publish the post
4. View the post in the Reader

<strong>Result:</strong> instead of a slideshow in streams or in the single-post view, I see a fallback message:

> This slideshow requires JavaScript.

Orignial post:

![screen shot 2015-11-25 at wed nov 25 10 25 04 am](https://cloud.githubusercontent.com/assets/1119271/11401178/48b0887c-935f-11e5-83c9-b1e0d255f361.png)

Main stream:

![screen shot 2015-11-25 at wed nov 25 10 25 18 am](https://cloud.githubusercontent.com/assets/1119271/11401185/4fe97018-935f-11e5-8205-59e60e8940ce.png)

Single-post view:

![screen shot 2015-11-25 at wed nov 25 10 25 25 am](https://cloud.githubusercontent.com/assets/1119271/11401194/5768aeee-935f-11e5-9262-4ee734d61f07.png)

Note from @shaunandrews 

> The data is there, we just need to extract it and build a slideshow.

![data](https://cldup.com/C3L8PDwvkH.png)

Note from @blowery 

> One way to tackle this would be to extract all of the images from the data attribute and add them as single images to the post content.Then let all of the normal image processing stuff pick them up downstream like normal.

**Comment by lancewillett** [comment]
This is still not working correctly. Tested today in Firefox stable on OS X 10.11.4.

Add the slideshow to a new post.

<img width="1108" alt="screen shot 2016-05-03 at 11 31 19 am" src="https://cloud.githubusercontent.com/assets/66797/14994070/b57e8440-1122-11e6-8446-dc91e3df61cd.png">

Publish it.

<img width="1105" alt="screen shot 2016-05-03 at 11 31 31 am" src="https://cloud.githubusercontent.com/assets/66797/14994080/c9c9ed72-1122-11e6-86ea-162f250bb575.png">

View post on front-end, looks good.

<img width="1104" alt="screen shot 2016-05-03 at 11 31 37 am" src="https://cloud.githubusercontent.com/assets/66797/14994088/d54712c4-1122-11e6-9140-5fb7915cc893.png">

Load the site in Reader (using handy actionbar link!).

<img width="352" alt="screen shot 2016-05-03 at 11 33 44 am" src="https://cloud.githubusercontent.com/assets/66797/14994100/ea703c66-1122-11e6-9769-90102540917b.png">

<img width="1099" alt="screen shot 2016-05-03 at 11 31 57 am" src="https://cloud.githubusercontent.com/assets/66797/14994093/df9a5128-1122-11e6-8620-e7e314edaac8.png">

**Comment by blowery** [comment]
Hrm. I'm guessing we just need to enqueue the right JS / CSS to make this sing. Looking into it.

**Comment by blowery** [comment]
We'll need to port over shortcodes/]s/slideshow-shortcode and shortcodes/css/slideshow-shortcode from wpcom and hack in support for enhancing posts as they're rendered, like we do for other shortcode embed types.

**Comment by blowery** [comment]
Dug into this more. To use the existing slideshow js, we'd also have to pull in cycle.js and jquery. We _can_ do that, but I'd rather not... Looking at alternatives.

**Comment by psealock** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/5368
