### ISSUE TITLE
Launchpad: long domain urls squish the copy button with the pill

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#76605]
### Quick summary

If you have a long domain URL, the (CTA I guess?) in the Launchpad starts to look a little squished.

This one:
![Screen Shot 2023-05-04 at 2 37 57 PM](https://user-images.githubusercontent.com/26772342/236317880-91b15c40-80d2-457a-a6ac-2fc71085b62f.png)

### Steps to reproduce

1. Do an onboarding flow (`/start`)
2. Use a long domain name and make it a subdomain of wordpress.com
3. Pick a plan with a free domain upgrade
4. Go all the way through to the launchpad

### What you expected to happen

Not as squished looking 😄 

### What actually happened

The copy button is really pressed up against that pill@

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described - copy button nearly underneath the "Customize" button in my test:

#### Screenshots/Recordings

![4piJat.png](https://user-images.githubusercontent.com/27249804/236341652-681dbdd6-b5c4-4e98-98f1-680336d91796.png)

📌 ACTIONS
- Assigned to @Automattic/lego

**Comment by miksansegundo** [comment]
cc: @Automattic/cylon because they have been working on Launchpad recently.

**Comment by taipeicoder** [comment]
Re-assigning to team Serenity who are better positioned for issues related to the Launchpad 🙂

**Comment by sixhours** [comment]
<img width="379" alt="Screenshot 2023-08-15 at 2 33 43 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/ba62c6bd-3899-480f-911f-0f1ef8330795">

I think this was fixed at some point because I'm not able to reproduce it. I'll look through the commit history to confirm.

**Comment by sixhours** [comment]
Looks like this was fixed in #76689
