### ISSUE TITLE
Assembler Copy Updates June or July 2023

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#76614]
# Description
As we have learned, copy updates are an ongoing process!   Let's incorporate [some of these ideas](https://github.com/Automattic/wp-calypso/pull/76528#pullrequestreview-1410761475) from @miksansegundo in our next round of copy updates.   
❗ REVIEW AND UPDATE this issue before dev work starts to reflect any new UI/UX/copy in the Assembler.

### Item 1: Design your own CTA
Prior discussion 7l53h5fxAUNjVRBQ82YFwn-fi-2614%3A59849
|BEFORE|AFTER|
|----|----|
| ![image](https://user-images.githubusercontent.com/5665959/236364596-e49746f2-df68-4444-bb4e-773e69af744f.png)   |   TBD |

In this case, adding a subheader creates visual consistency with the placeholder on the styles screens. YES

I'm sure there are good reasons to use the term "elements". I'd rather use "layout and style options" because these are precise references to the labels users can see on the sidebar and suggests that they are optional.

### Item 2: Assembler page title 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/5665959/236362665-4654e0c0-82fe-4b93-80c5-d63aee8b166b.png">

Change "Design you own" to "Create your design"

### Item 4: Update Homepage subheading
<img width="337" alt="image" src="https://user-images.githubusercontent.com/5665959/236363657-5104938a-a34a-43f0-9488-62828c0205fe.png">
New copy: Add and arrange patterns to make your homepage unique and help people instantly understand what your site’s about.

**Comment by arthur791004** [comment]
https://github.com/Automattic/wp-calypso/issues/76918 is also a part of this

**Comment by taipeicoder** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/80118
