### ISSUE TITLE
Gutenberg and Smart Slider 3 conflict

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#76645]
### Quick summary

When both the Gutenberg plugin and Smart Slider 3 are active, Gutenberg shows a blank screen.

### Steps to reproduce

1. Make sure the Gutenberg plugin is active.
2. Install and activate Smart Slider 3.
3. Try to edit or create  a page or post in Gutenberg.

### What you expected to happen

The editor should load.

### What actually happened

A white screen appears. 

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Workarounds:
Option 1: Deactivate Smart Slider 3.
Option 2: Deactivate the Gutenberg plugin.

**Comment by ariel-maidana** [comment]
6265648-zd-woothemes
Please inform the user once it's solved.

**Comment by ariel-maidana** [comment]
Please let the user know once this issue is solved.
6265656-zd-woothemes

**Comment by ariel-maidana** [comment]
6264279-zd-woothemes

**Comment by essleeung** [comment]
Another case here: 33706818-hc
Please follow up with user here: 6266298-zd-woothemes

**Comment by essleeung** [comment]
38164131-hc

**Comment by kavyagokul** [comment]
43056378-hc

**Comment by ariel-maidana** [comment]
Issue solved by Smart Slider 3 team: https://wordpress.org/support/topic/plugin-is-incompatible-with-gutenberg-plugin/
p7DVsv-hit-p2#comment-45648

**Comment by csabarakasz** [comment]
42745958-hc

- shared this https://wordpress.org/support/topic/plugin-is-incompatible-with-gutenberg-plugin/ but also told them to deactivate Smart Slider so they can edit pages.

**Comment by jromales** [comment]
another report in 6277531-zd-woothemes

I shared https://wordpress.org/support/topic/plugin-is-incompatible-with-gutenberg-plugin/ so they can follow the fix recommended by Smart Slider 3 team

**Comment by csabarakasz** [comment]
38518195-hc

Based on Smart Slider's changelog, they released a fix: https://smartslider.helpscoutdocs.com/article/1746-changelog version 3.5.1.15

**Comment by druesome** [comment]
Noting here that the [update](https://wordpress.org/support/topic/plugin-is-incompatible-with-gutenberg-plugin/#post-16712956) provided by the developers worked. The dropbox link can be used to update the plugin in CLI as we are waiting for the fix to be shipped.

```
plugin install https://www.dropbox.com/s/cc6hqbgnmd1h1q2/smart-slider3-wordpress-free-master.zip?dl=1 --force
```
