### ISSUE TITLE
Google Fonts are not shown in the Editor preview

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#76649]
### Quick summary

When selecting a custom font family from our Google Fonts list in Global Styles or blocks Typography controls, the font is not applied correctly in the editor preview but appears on the front end.

https://user-images.githubusercontent.com/14153300/236613673-86cee010-e246-42a2-ba39-e4c635822b66.mp4

Fonts that are part of the theme style variations can be previewed. This is broken in Simple and Atomic sites on Gutenberg 15.7.

On an Atomic site, when Gutenberg is inactive, the list of fonts is not available at all:

<img width="552" alt="CleanShot 2023-05-06 at 09 56 38@2x" src="https://user-images.githubusercontent.com/14153300/236614160-5d59310e-5750-4498-87a6-f0484f4fd50a.png">

I couldn't reproduce any similar behavior in a local site with and without Gutenberg 15.7.

### Steps to reproduce

1. In a site with an FSE theme and access to Global Styles, open the Site Editor
2. Go to Global Styles > Typography
3. Select a font from our Google Fonts selection, like Space Mono
4. The preview will flash as if it was applying the font, but it won't be applied correctly. Instead, a serif system font will load.

### What you expected to happen

The preview should show the correct font selection

### What actually happened

The Editor will not show any fonts from Google Fonts in the preview.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Gutenberg 15.7
Mac OS Ventura 13.0.1
Chrome 112.0

**Comment by rw-ye** [comment]
Another report: 6267935-zd-woothemes

**Comment by autumnfjeld** [comment]
cc: @arthur791004

**Comment by simison** [comment]
Confirmed this is with Gutenberg 15.7, and doesn't happen when I switch to Gutenberg 15.6.2 on simple sites:

**15.6.2**
<img width="1547" alt="Screenshot 2023-05-08 at 12 42 50" src="https://user-images.githubusercontent.com/87168/236792893-e0781f87-c91c-4b06-b503-ffb3fdc63af3.png">

**15.7**
<img width="1542" alt="Screenshot 2023-05-08 at 12 43 48" src="https://user-images.githubusercontent.com/87168/236792925-7adb6c4a-abc5-4dc5-87e4-11a68649c51b.png">

**Comment by arthur791004** [comment]
It's related to https://github.com/WordPress/gutenberg/pull/49655/files#r1185738007

**Comment by hellofromtonya** [comment]
>It's related to https://github.com/WordPress/gutenberg/pull/49655/files#r1185738007

https://github.com/WordPress/gutenberg/pull/49655 removed the decision-making logic of which fonts to print for the iframed editor for the 6.3 compat script-loader (it's still in the 6.2 compat file). That code is being relocated to the Fonts API (see https://github.com/WordPress/gutenberg/pull/50151).

A 15.7.1 minor will contain this [follow-up PR ](https://github.com/WordPress/gutenberg/pull/50151)which should restore printing of fonts in the Site Editor and other block editors.

**Comment by cat-og** [comment]
Another report here: 6272049-zd

**Comment by RT-1904129** [comment]
Hi @hellofromtonya , @arthur791004 
Can you help me to set up this project in my locally as I follow all step but when I am doing yarn start it still scrolling and I am not able to see the correct UI from the last 2 hours in my local
Thanks & Regards
Rishabh Tripathi

**Comment by simison** [comment]
@RT-1904129 unfortunately this issue needs some internal tooling to debug & solve, and we have folks working on this already.

**Comment by RT-1904129** [comment]
Hi @simison 
Basically, I want little help in setup this project. Can you help me on this?
Thanks & Regards
Rishabh Tripathi

**Comment by simison** [comment]
@RT-1904129 please see:
- https://wpcalypso.wordpress.com/devdocs/README.md
- https://wpcalypso.wordpress.com/devdocs/docs/install.md

**Comment by cuemarie** [comment]
📌 ACTIONS
- Assigned to ~Other~ @Automattic/t-rex  since this is related to Global styles, but see discussion below:
- Troubleshooting and a fix is in discussion here: p1683364993859039-slack-C02FMH4G8

**Comment by dsas** [comment]
GB 15.7.1 was rolled out to WordPress.com at 19:56 UTC yesterday, which looks to have fixed this bug as @hellofromtonya suggested.
