### ISSUE TITLE
Customizer CSS is missing after site goes Atomic

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#76642]
### Quick summary

When a simple site is built using FSE, and CSS is added through the Customizer, that CSS is lost when a site goes Atomic — the Customizer's Additional CSS field is blank, similar to when one theme is switched for another.

As I most commonly use Twenty Twenty Three (TT3), I have observed this issue occur consistently, which leads me to believe that the AT site _thinks_ its version of TT3 is a different theme from its simple counterpart.

### Steps to reproduce

1. Activate the TT3 theme on a Simple site
2. Add Additional CSS in the Customizer. An example can be found in pdEkSe-2YS-p2
3. Install a plugin, such as [Yoast](https://wordpress.com/plugins/wordpress-seo/), to AT the site
4. Visit the Customizer again, and observe that the CSS is no longer present

### What you expected to happen

I expected the CSS to remain in the Customizer after the site goes Atomic.

### What actually happened

Any CSS added in the Customizer is removed, and needs to be added again. No revisions are present.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by RT-1904129** [comment]
Hi Team
Can you please assign me this task?I have relevant experience in this I will contribute and complete this
Thanks & Regards
Rishabh Tripathi

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple > Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described!  The CSS is removed on the AT site.  There's also no CSS Revision history, so the CSS is not recoverable.

#### Screenshots/Recordings

![Markup on 2023-05-09 at 10:31:18](https://github.com/Automattic/wp-calypso/assets/27249804/c0ccafc1-ef43-47d5-a7f9-d1c5fc75caef)

**After AT-ing site**

https://github.com/Automattic/wp-calypso/assets/27249804/fe4f44df-967d-4116-85b0-2cac3b0f8bf9

📌 ACTIONS
- Assigned to Other: @Automattic/reactor

**Comment by cuemarie** [comment]
@RT-1904129 Thanks for your interest in contributing!  This won't be assigned to you specifically, but that's not necessary in order for you to contribute! Please refer to:

- https://wpcalypso.wordpress.com/devdocs/docs/CONTRIBUTING.md

**Comment by mikeicode** [comment]
The BBE team has encountered this issue on multiple sites.

**Comment by danielbachhuber** [comment]
Some conversation in Slack: p1685977163534209-slack-C0160HSMDQV

Notably: on Simple sites, the template option is `pub/twentytwentythree`, but it's `twentytwentythree` on Atomic sites. I'm pretty sure the value is used in the custom CSS storage mechanism, so the custom CSS is "lost" when the site goes Atomic (and inverse too).

**Comment by metabreakr** [comment]
After some quick testing, CSS added within the site editor is not subject to this issue.

**Comment by danielbachhuber** [comment]
It looks like custom CSS is stored as `safecss` on Simple sites, and `custom_css` in core:

<img width="905" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36432/3af0aaff-0ba6-465d-96e7-d79f6bc0037b">

<img width="665" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36432/a2c6de2b-f807-4099-98b2-c42959143fc0">

@a8caustin started on a conversion job in D101866-code but doesn't appear to have completed it.

Here are a couple of related P2 threads:
* pdtR3Z-1yB-p2
* p9F6qB-bxx-p2

I followed up on the first one with a comment.

**Comment by danielbachhuber** [comment]
It looks like WPCOM uses some legacy `WPCom_SafeCSS` class: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sfnsrpff%2Qjcpbz.cuc%3Se%3Q7p0s3rqp%237-og

It calls `Jetpack_Custom_CSS`: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sphfgbz%2Qpff.cuc%3Se%3Qn7892421%26zb%3Q220%26sv%3Q10%2310-og

Jetpack has a `Jetpack_Custom_CSS_Enhancements` class: https://github.com/Automattic/jetpack/blob/b8fec24bdeb551af9598037888ee30916ae56535/projects/plugins/jetpack/modules/custom-css/custom-css.php

**Comment by danielbachhuber** [comment]
More debugging here p1686095416816319-slack-C7YPW6K40

**Comment by danielbachhuber** [comment]
Fixed the issue with D113018-code

Enabled for everyone with D113023-code

🚢

**Comment by ash1eygrace** [comment]
This appears to be back: p1692733434652319-slack-C03TY6J1A

**Comment by danielbachhuber** [comment]
@ash1eygrace @cuemarie When something has been fixed in the past and then regresses, can you open a new issue please? It'd be helpful to confirm it reproduces consistently, etc. Thanks!

**Comment by cuemarie** [comment]
Sure thing! I'll close this and report anew if needed once I retest. 

_Update_

@ash1eygrace I tried to replicate this and actually could not - my site retained it's CSS when transferring from Simple to AT, on both TT1 and TT3 themes (this report was specifically only for FSE themes such as TT3).

### Recording:

https://github.com/Automattic/wp-calypso/assets/27249804/a66c7ac4-f5a7-4df1-8817-592d5d3e856a

**Comment by metabreakr** [comment]
Re-opening. This issue occurred in pdEkSe-4WM-p2 when a simple site was made atomic, and the CSS did not persist. Varia theme (Shawburn). I had to manually re-add the CSS to the AT'd site.

**Comment by danielbachhuber** [comment]
@metabreakr Can you open a new ticket please? Thanks https://github.com/Automattic/wp-calypso/issues/76642#issuecomment-1688943562

**Comment by metabreakr** [comment]
@danielbachhuber Thanks, I opened a new issue: #81593
