### ISSUE TITLE
Enabled WordPress.com Editing Toolkit plugin shows a blank page editor 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#76650]
### Quick summary

With WordPress.com Editing Toolkit plugin (full-site-editing) active on the site, opening a page to edit it shows blank. 

### Steps to reproduce

1. Enable WordPress.com Editing Toolkit plugin. 
2. Go to pages and click a page to edit in the editor. 

### What you expected to happen

The page contents will be visible. 

### What actually happened

The page contents are not visible. 

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I am not able to replicate this on my test site. On the user's site, all plugins active (except WordPress.com Editing Toolkit) and using WordPress.com default theme or third-party theme loads the page editor. But when WordPress.com Editing Toolkit is active, the editor is blank. 

- User report: 6266672-zd 
- Firefox 112
- full-site-editing plugin version is 3.64678, and there are no fatal errors in CLI.

**Comment by cuemarie** [comment]
Hi @kspilarski ! I pulled up the user's site, and currently the **WordPress.com Editing Toolkit** is active, and their page editor loads without issue. 

They do have Smart Slider 3 Pro now inactive, and that recently was causing issues with the editor loading - this may be the underyling issue. See: https://wordpress.org/support/topic/plugin-is-incompatible-with-gutenberg-plugin/

📌 ACTIONS
- Closing as not reproducible
