### ISSUE TITLE
Assembler: Survey Modal

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#76653]
# Description

This work is still under discussion.

### Background & Resources
* Jeff Golinsky post [A guide to automating in-app user research] puPv3-evt-p2
* * Crowdsignal  p1683311408586699/1683256622.105359-slack-CRWCHQGUB

## Design Tasks 
For @lucasmendes-design and with collaboration with Lego
- [x] Determine questions
- [x] Understand how to collect data and how to process it
- [x] Create UI

### Survey Questions
When survey questions are finalized, let's document that here @lucasmendes-design or @taipeicoder .

## Dev Tasks
* Show survey CTA for English locale only after users click on an item from the side nav
* Allow dismissing it only for the session
* Link to the survey and open in a new tab
* Add Tracks events to track engagement

@Automattic/lego

**Comment by lucasmendes-design** [comment]
**Determine questions**
WIP.

This is an excellent opportunity to collect users' emails if they want to participate in further paid research. 

**Understand how to collect data and how to process it.**
We're going to use crowdsignal and the analysis and collection is pretty simple with the tool 

**Create UI**
As I shared in Slack, we can show a notice to provide a CTA that is not so intrusive. Let's keep the show the notice for 1 or 2 weeks depending on the number of feedback we receive. 

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/98343583/236893177-b415ca35-4021-4137-a59d-db423cdc1fb6.png">

WDYT?

**Comment by lucasmendes-design** [comment]
**Determine questions**

**[Crowdsignal link](https://lucasmdo.survey.fm/assembler-survey-modal)** 

**1) What motivated you to choose the "Start designing" option?**
- I didn't find a theme that matched my needs.
- I didn't like any of the available themes.
- I wanted to customize my own theme.
- I'm not sure, I was just browsing.
- Other (please specify): ____

**2) Did you spend a significant amount of time looking for a theme before deciding to create your own?**
- Yes
- No

**3) How confident are you in your ability to customize your own theme?**
Scale 1-5

**4) Is there anything you would like to share about your experience with the theme showcase page or any suggestions for improving your overall experience?**
Open question

**5) Thank you for taking the time to complete this survey! If you would be interested in participating in further interviews to help us improve our product, please provide your email address below.**
(Optional)

@alaczek @autumnfjeld Do you want to include/remove/edit anything here? ✌🏼

**Comment by lucasmendes-design** [comment]
cc: @davewhitley if you have more thoughts for this survey :) I created a short one that will answer our doubts.

**Comment by taipeicoder** [comment]
@lucasmendes-design some questions on my end:

1. Are we targeting this survey to only English-speaking users? Perhaps only show the notice for locale = "en".
2. To confirm, will the survey open in a new tab?

The survey should be short and sweet, so I really like the questions! My two cents - I would change question 3 to something more direct, like "How difficult was this step?" 🙂

**Comment by arthur791004** [comment]
One concern is the user with a small screen might not see the CTA as they have to scroll down to the bottom of the main list

**Comment by autumnfjeld** [comment]
Wow! I'm even more excited about this now.  Nice work @lucasmendes-design .

* I agree with @taipeicoder on question 3.  Perhaps "How difficult was this `Design your own` step?" 🤔  or  "How difficult did you find this page design process?" or "How difficult did you find this page setup process?" or  something similar?
* Question 4: don't use term "theme showcase" as the user most likely came from the onboarding Design Picker.  Instead: "Is there anything you would like to share about your experience with design choices available or any suggestions for improving your overall experience?"  (Could say "theme choices" but we use the word design a lot in onboarding, so it is more consistent. Could say design/theme to include both.)


@arthur791004 It's probably ok if users with a small screen miss out, seems like an edge case.  I don't think it would be a big worry, because this isn't a critical feature.

**Comment by RT-1904129** [comment]
Hi @autumnfjeld , @arthur791004 , @miksansegundo, @taipeicoder 
Can you help me to set up this project in my locally as I follow all step but when I am doing yarn start it still scrolling and I am not able to see the correct UI from the last 2 hours in my local
Thanks & Regards
Rishabh Tripathi

**Comment by lucasmendes-design** [comment]
Thanks for the feedback, @taipeicoder. 

> Are we targeting this survey to only English-speaking users? Perhaps only show the notice for locale = "en".

I think it makes sense to target English speakers only so the result will be more accurate. 

> To confirm, will the survey open in a new tab?

Yes 👍🏼. 

> My two cents - I would change question 3 to something more direct, like "How difficult was this step?"

This is an excellent question, but the problem with asking it here is that we need to know if users have already completed the SA step. We could ask that after they complete the SA. We can also plan a different survey when users complete site assembler :) (cc: @autumnfjeld)

> don't use term "theme showcase" as the user most likely came from the onboarding Design Picker.

Totally forgot this one, I'll change it. 

> One concern is the user with a small screen might not see the CTA as they have to scroll down to the bottom of the main list

It's an issue but I don't think this is a big one. The notice will be there and it's optional.

**Comment by lucasmendes-design** [comment]
The new one is here 😃
[Crowdsignal link](https://lucasmdo.survey.fm/assembler-survey-modal)

**Comment by autumnfjeld** [comment]
See the conversation with Veronica Fasulo here: p1684135665611339/1683800558.854399-slack-C048CUFRGFQ

**Comment by miksansegundo** [comment]
I removed my feedback comment from here to move the discussion to the post pbxlJb-3T9-p2
