### ISSUE TITLE
`/subscriptions/comments`: Some post subscriptions contain `false` URL values

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#76678]
I experienced this issue with my WPCOM account. I have multiple post subscriptions, returned by our API, which have their `post_id: 0`, `post_url: false`, `post_excerpt: ""`, `post_title: ""`, while the site related data refers to actual existing sites.

![Screen Shot 2023-05-08 at 19 33 29](https://user-images.githubusercontent.com/2019970/236891648-34287a22-5172-426c-9b02-7a9ec5f4fa95.png)

**Comment by yansern** [comment]
Closing this in favour of the other issue.
https://github.com/Automattic/wp-calypso/issues/76678
