### ISSUE TITLE
Spearhead Theme: Blog Posts Block Featured Image Sizes Not Being Respected

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#76687]
### Quick summary

Featured images appear larger than they should when using the blog posts block while running the Spearhead theme.

### Steps to reproduce

1. Create a site, or use an existing site, running the Spearhead theme.
2. Create at least one page that uses the blog posts block.
3. Assign a featured image to at least one test post, and configure the block to show that image.

### What you expected to happen

The featured image should be the size it appears to be in the editor.

### What actually happened

In the user's case, the featured image is larger on the site than the editor. Only the blog posts block does this.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested on spearhead. Other themes, such as Quadrat, do not have this issue. Did not test on the base theme. Reported to us by a user in 42381310-hc.

**Comment by liviopv** [comment]
- [ ] 33721939-hc

Reproduced in Hever, but not on TT3.
The issue is only visible to logged out visitors, but it can be reproduce in multiple browsers.

Workaround:

```
.wp-block-newspack-blocks-homepage-articles article .post-thumbnail img {
    width: 100%;
}
```

**Comment by liviopv** [comment]
Bumping in priority considering how widely used the block is.

**Comment by filipanoscampos** [comment]
Another case here: 6271682-zd-woothemes
Mayland theme.

Personal plan, so we don't have the option of using CSS.
Suggested the Query Loop block.

**Comment by DavidSaladu** [comment]
Another one with the Hever theme 573439-hc

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- So far I'm not seeing any issue with the Featured Images of the Blog Posts blocks on my test sites.  Using Hever and Spearhead, the size of the images in the editor match the live site.  
- Tested on AT site using Gutenberg 15.7.1 as well as 15.7 - same result - could not replicate.

#### Screenshots/Recordings

**Simple Site - Hever Theme**

Editor: 

![aVNVaM.png](https://github.com/Automattic/wp-calypso/assets/27249804/954fb357-3d1d-4eed-acc0-21c2be1c0ac9)

Live Site: 

![dgZeD9.png](https://github.com/Automattic/wp-calypso/assets/27249804/5b130594-f7e9-4265-a7c2-c88ad423ae97)

**ATOMIC - Spearhead Theme**

Editor: 

![BjkvWo.png](https://github.com/Automattic/wp-calypso/assets/27249804/85849e1c-2d1a-417e-9fcc-6a8ecdbaaa74)

Live Site: 

![4vh4ZM.png](https://github.com/Automattic/wp-calypso/assets/27249804/0953fece-a5fe-44d2-a102-41c22a4508c6)

📌 ACTIONS
- Requested author/HE feedback

📌 Message to Author
- @liviopv @arinoch @filipanoscampos @DavidSaladu are your customers still experiencing this issue?  I checked out these user sites, and did not see any overlapping or problematic featured images. It's possible this is very recently resolved.
-  
- For folks reporting these cases, can anyone replicate in a test environment, and if so, provide screenshots of the issue?  So far there are no screenshots on this report, making this a little more difficult to understand.
- If there are additional steps than what's included in the report needed to replicate, please share that as well, thank you!

**Comment by arinoch** [comment]
@cuemarie - I agree with your suspicion it may have been resolved already. I've pinged the user in 6276926-zd-woothemes to check.

**Comment by cuemarie** [comment]
Thanks @arinoch ! User hasn't replied I see, but I'm going to take that as a good sign! :) Closing as not reproducible (potentially resolved) for now - feel free to reopen if they report the issue is still present and we can take another look for a possible bug.

**Comment by edwinho89** [comment]
I'm reopening as another user experienced in 6318344-zd-woothemes , and I'm able to reproduce this on simple site with Spearhead theme.

On a post page, it expands exceeding screen width to the right:

https://github.com/Automattic/wp-calypso/assets/34882260/11d90a94-d8d2-4f8c-9e04-eec0fc738f7d

On a blog post block, featured images took up the whole width.

<img width="1680" alt="image" src="https://github.com/Automattic/wp-calypso/assets/34882260/dd5258bf-5207-44ca-aaaa-4ac6d196d25e">

Here's is the expected results on how it looks on the editor:

<img width="1680" alt="image" src="https://github.com/Automattic/wp-calypso/assets/34882260/dca133e7-cc10-4333-bccd-886753f6187e">

When inspecting element, I see https://s0.wp.com/wp-content/themes/pub/seedlet/style.css?m=1684754137h&cssminify=yes has the following CSS `max-width: unset;` which made max-width undefined.

```
footer *, header *, main * {
    max-width: var(--global--spacing-measure);
}
```

Possible workaround:

Apply 100% on `max-width` CSS as below:

```
main * {
    max-width: 100%;
}
```

**Comment by zdenys** [comment]
6310376-zd-woothemes I can reproduce on Simple Site with Mayland theme in Chrome Incognito only but not Chrome where I am logged in:

Chrome Incognito | Chrome 
--- | --- 
![mLY1qb.png](https://github.com/Automattic/wp-calypso/assets/39308239/c9f09427-8296-4bc3-bd78-c2ad3dc55dcd) |  ![W52KyY.png](https://github.com/Automattic/wp-calypso/assets/39308239/f6f5cbe6-b721-4029-a431-5ec92ec122de)

[Livio's CSS trick above](https://github.com/Automattic/wp-calypso/issues/76687#issuecomment-1539930622) fixes the issue.

Would like to be updated when issue resolved.

**Comment by cuemarie** [comment]
There are a couple of very similar reports like this:

- https://github.com/Automattic/themes/issues/7095
- https://github.com/Automattic/themes/issues/7099

I've escalated the reports here: p1685056613665109-slack-C029FM1EH to try to get a sense of what cause may be - this may not be a themes-specific issue.

**Comment by edwinho89** [comment]
6332278-zd-woothemes

Not Spearhead theme, but it had the same CSS which made the header display exceeding full width on mobile.

```
header *{
    max-width: var(--global--spacing-measure);
}
```

<img width="1680" alt="image" src="https://github.com/Automattic/wp-calypso/assets/34882260/b3f2465f-4701-4272-ae75-b7fa29d9d8e4">

**Comment by zdenys** [comment]
6316111-zd-woothemes Hever theme on WordPress.com Personal Plan (Simple Site), thus CSS fix is not applicable.

![AGxxI2.png](https://github.com/Automattic/wp-calypso/assets/39308239/9bc34dda-c24c-460d-a8ea-9fcb09e11b0d)

**Comment by tvolpert** [comment]
Is this perhaps related to [this issue](https://github.com/Automattic/themes/issues/7095) as well? Seems like it might stem from the same underlying issue? 

The more I look at it, I think they might actually _be_ the same issue, just manifesting differently on different sites

edit: I see @cuemarie is on top of it already :)

**Comment by cuemarie** [comment]
I agree, @tvolpert  - they definitely look like the same issue! Haven't heard confirmation from the escalated thread yet, but if no action happens by next week I can try to merge these down to one central report 👍

**Comment by IoanaAMuresan** [comment]
Another instance here: 6321662-zen, it seems. Issue not visible on the site as they have reduced the size of the images to display correctly, so no workaround needed.

**Comment by jorpdesigns** [comment]
Reported in 6340780-zd-woothemes, using the Shawburn theme. Shared custom CSS as workaround.

- [ ] Follow-up: 6340878-zd-woothemes

**Comment by jartes** [comment]
6345676-zd-woothemes

**Comment by jartes** [comment]
Another report on 6345676-zd-woothemes with the [Shawburn](https://wordpress.com/theme/shawburn) theme.

It was only happening when checking the site while being logged-out from WordPress.com.

**Comment by cuemarie** [comment]
Reported what seems to be the underlying issue here: 

- https://github.com/Automattic/wp-calypso/issues/77561

Please collect all future interactions on that report

**Comment by cuemarie** [comment]
A [fix has been deployed](https://github.com/Automattic/wp-calypso/issues/77561#issuecomment-1570917159)

**Comment by cuemarie** [comment]
A batch user reply will be sent out to all interactions noted above this comment. Please refer to main issue https://github.com/Automattic/wp-calypso/issues/77561 for updates on that process.
