### ISSUE TITLE
Themes: Open live demo from screenshot

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#7668]
The Theme Showcase Live Demo link feels sort of hidden currently, appearing as a text link above the much large screen shot. What if we made clicking/tapping the screenshot open the demo as well? 

This is related to #3657, which suggests making tapping the screenshot on mobile open a larger view of the screenshot. I'm not sure if we want varying behaviors on desktop or tablets versus smaller mobile devices, but I wanted to cross link that so we can consider both when we get to looking at this.

<img width="641" alt="screen shot 2016-08-25 at 1 24 23 pm" src="https://cloud.githubusercontent.com/assets/1900444/17979160/425aaca6-6ac7-11e6-923c-e2c9a7f02334.png">

**Comment by folletto** [comment]
The screenshot is meant to be used similarly to #3657 on desktop too: tapping left/right sides of the screenshot will go to more screenshots.

However, we might consider a better placement for the live demo button, or use the full screenshot until we have the multiple screenshots available.

**Comment by folletto** [comment]
Done in #13002.
