### ISSUE TITLE
Fullpost: Tweak to headline/body spacing

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#7669]
Current:
![screen shot 2016-08-25 at 10 23 49 am](https://cloud.githubusercontent.com/assets/24388/17979230/6f43c9a0-6aae-11e6-84a3-1ef7f3925ec1.png)

Should be:
![screen shot 2016-08-25 at 10 25 04 am](https://cloud.githubusercontent.com/assets/24388/17979241/7630fc06-6aae-11e6-9a45-f7e4a493eb60.png)

When the headline is one line, the top of the content area should align with the bottom of the avatar. (About 15px lower.)

Screenshots from this post: https://calypso.live/read/feeds/33638212/posts/1132023514

**Comment by blowery** [comment]
I feel like the text in the sidebar should line up with the body text when scrolled all the way up. "The Snow..." should line up with the "ordinary apartment..." line.

**Comment by fraying** [comment]
Yeah I was gonna deal with that kinda finessing at a later stage. It'll involve lots of tweaks.

**Comment by fraying** [comment]
Is this the same problem?

https://wordpress.com/read/feeds/36317097/posts/1152765413

![screen shot 2016-09-13 at 12 34 17 pm](https://cloud.githubusercontent.com/assets/24388/18488475/67ec4b32-79ae-11e6-87e1-b5d39a4f3e78.png)

cc @blowery @jancavan

**Comment by jancavan** [comment]
@fraying They're related. Fixed it in: https://github.com/Automattic/wp-calypso/pull/8086

**Comment by jancavan** [comment]
This is fixed in: https://github.com/Automattic/wp-calypso/pull/8086

> I feel like the text in the sidebar should line up with the body text when scrolled all the way up. "The Snow..." should line up with the "ordinary apartment..." line.

We can create a separate issue for this.
