### ISSUE TITLE
Odyssey Widget: Look at how we proper deal with the links for Atomic sites

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#76690]
Slack discussion: p1683244631915419-slack-C04UCBZMBAA

**Comment by kangzj** [comment]
My impression is that, we want Atomic users to be able to use the refreshed Widget but we don't want them to use Odyssey Stats because Calypso Stats is available and has better performance as it's hosted on CDN and better has direct access of `public-api`. So I'm thinking changes the Widget links on Atomic to Calypso Stats.

What do you folks think? @jsnmoon @Automattic/red

**Comment by jsnmoon** [comment]
> I'm thinking changes the Widget links on Atomic to Calypso Stats.

@kangzj: Sounds reasonable to me!
