### ISSUE TITLE
Site Assembler: Premium blocks will need a premium badge

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#76694]
# Description

See discussion in pekYwv-1kJ-p2#comment-978.

If we have premium blocks, then we probably want to mark them with the standard black premium badge.

However in the editor this is how they are marked.  I think we should check with a broader audience if there are plans to change / update the red dots in the Editor. I remember some discussion about that, but can't remember the details

![Image](https://user-images.githubusercontent.com/5665959/236968212-cabff900-a899-4cf2-b17a-be1e6aa3723c.png)

# Design Tasks
- [x] Get confirmation from Ola that she is making premium patterns
- [ ] @lucasmendes-design to provide design mockup of how we label premium patterns
- [ ] optional or side work: investigate if we should change the red dots in the editor inserter to stars or something in alignment with current premium iconography

# Dev Tasks
- [ ] Do what the designers say. 😆 

@Automattic/lego

**Comment by NkOffiCiAL07** [comment]
Hi Team,
I believe I can resolve the issue and would like to work on, Please assign me the same.
Thanks

**Comment by taipeicoder** [comment]
> Hi Team, I believe I can resolve the issue and would like to work on, Please assign me the same. Thanks

Hi there! Thanks for your interest in contributing to wp-calypso 🙂
We have a `Good First Issue` label that is better suited for first or new contributors, please find them via https://github.com/Automattic/wp-calypso/labels/Good%20First%20Issue

**Comment by NkOffiCiAL07** [comment]
sure, Thanks

**Comment by lucasmendes-design** [comment]
I agree that the tiny pink dot and our dark badge for premium are completely different. 

Here is the solution to try to unify those pages without changing too much. 

**SA:** 
<img width="1225" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/63ac45ad-f6cd-420b-bcce-ee92ff055779">


https://github.com/Automattic/wp-calypso/assets/98343583/5967a1db-54c2-49df-a7d6-d86bf6817b6b

**EDITOR:** to communicate in the same way, we can add a premium badge to the block preview and have the same behavior as SA for patterns. 

Block:
<img width="594" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/2864e630-627a-46c6-a586-af59719b595d">

Patterns:
<img width="1225" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/b45b5729-2671-41d8-acd6-eb9fb42cf132">

**Comment by autumnfjeld** [comment]
Oh, that is such an elegant solution @lucasmendes-design that the badge expands on hover.   I wonder if we should do that here too: https://github.com/Automattic/wp-calypso/issues/75156

**Comment by lucasmendes-design** [comment]
I think it makes sense to me. @autumnfjeld. I put a comment there.

**Comment by lucasmendes-design** [comment]
I think it makes sense. I put a comment there. @autumnfjeld

**Comment by taipeicoder** [comment]
Moving this to the backlog, it's been a while since the last activity.

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
