### ISSUE TITLE
Design Carousel in eCommerce flow is broken in Safari

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#76705]
### Quick summary

When accessing the design carousel step in the eCommerce signup flow at wordpress.com/setup/ecommerce using Safari, the theme images are barely visible due to how narrow the carousel items are.

In addition, the navigation arrows for the carousel are not centred in the white background element. (This occurs across browsers.)

You can see both issues in this screenshot:

<img width="1458" alt="Screenshot 2023-05-09 at 10 55 11" src="https://user-images.githubusercontent.com/3376401/237047900-85ba452f-3392-4658-a167-488ce66b2d00.png">

This is the same step in Chrome at about the same resolution:
<img width="1458" alt="Screenshot 2023-05-09 at 11 07 06" src="https://user-images.githubusercontent.com/3376401/237049297-0dc05b86-d2d5-439d-b3e3-b80e541a12f3.png">

### Steps to reproduce

1. Use Safari as your browser
1. Navigate to `/setup/ecommerce`
2. If needed, log in to WordPress.com
3. Click on _Continue_ for the store details step
4. When you get to the design carousel step, see that the theme screenshots are tiny
   * Note that you can also navigate to directly to the design carousel step at `/setup/ecommerce/designCarousel`

### What you expected to happen

The images in the carousel should take up far more of the screen and be easily visible.

The navigation chevrons should also be centred in the white areas.

### What actually happened

I could barely see the theme screenshots in the carousel.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

**Browser version:** Safari Version 16.0 (17614.1.25.9.10, 17614)

From my initial exploration, it looks like this may be related to when/how Safari computes the box model for the carousel, as simply triggering a minor refresh of styles (even unrelated ones) may cause the carousel size to update and expand slightly (but not nearly enough to match the expected size).

**Comment by daledupreez** [comment]
I also want to add another note: I played with the chevron CSS, and adding `justify-content: center;` seemed to get them aligned correctly.

**Comment by pablohoneyhoney** [comment]
I just checked in Brave, and the chevron is also broken there. 

<img width="81" alt="Screenshot 2023-05-09 at 9 35 35 AM" src="https://github.com/Automattic/wp-calypso/assets/25516611/ca21c5fd-1ffc-4ff9-bcfc-30616b355f81">

**Comment by daledupreez** [comment]
Thanks to @alshakero and @agrullon95, this was fixed earlier today in #76718.
