### ISSUE TITLE
Stats: Fix header link styling for the "Default" color scheme

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#76701]
The header link color of Stats should be highlighted as other header links for the `Default` color scheme.

<img width="538" alt="截圖 2023-05-09 下午1 25 23" src="https://user-images.githubusercontent.com/6869813/237002201-93b95090-9564-4231-8063-3aca111e117f.png">

Original discussion: p1683553575078039-slack-C0438NHCLSY

**Comment by RT-1904129** [comment]
Hi @dognose24 
I want to work on this issue as I already set up the project in my local. Can I work on this issue? I am entirely confident I can resolve this issue very quickly.
Thanks & Regards
Rishabh Tripathi

**Comment by dognose24** [comment]
Hey @RT-1904129! Unfortunately, I merged [the PR](https://github.com/Automattic/wp-calypso/pull/76703) to fix this issue. There should be other issues you can work on. Thanks for your attention on Calypso. 🙂
