### ISSUE TITLE
Latest Posts Read More Links Not Rendering or Working Correctly

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#76739]
### Quick summary

On sites using a theme that uses the Site Editor (FSE themes), the Latest Posts block looks ok in the editor but doesn't function as expected on the live page. The "Read More" link is replaced with "[...]" on the live site.

Discovered here: 15412889-hc

### Steps to reproduce

1. On a page, add the Latest Posts block and set it to show post excerpts. You should see "Read More" links added in the editor.
2. Visit the live page and notice the "Read More" is replaced with "[...]" and clicking it doesn't link anywhere.

How the editor looks:
![Markup 2023-05-09 at 16 21 03](https://github.com/Automattic/wp-calypso/assets/93800099/ee7ad4be-b4a1-4288-9eaf-68b71226d7cf)

### What you expected to happen

The "Read More" link to show on the live page as it does in the editor and take the visitor to the full post when clicked.

### What actually happened

"Read More" is replaced with "[...]" and clicking it doesn't link anywhere.

![Markup 2023-05-09 at 16 17 14](https://github.com/Automattic/wp-calypso/assets/93800099/dbe61b45-8a33-4e00-a045-b33c3f01bfc7)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Issue occurs on any FSE theme such as Zoologist, Munchies, Twenty Twenty Three, etc.

Work-arounds:
- Use Blog Posts block or Query Loop block instead.
- Classic or hybrid themes don't have this issue but using a different block would be a better choice.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Simple with theme TT3, AT with theme Blank Canvas 3 (Gutenberg v15.7.0), and a Self-Hosted Site with theme TT3 (WP 6.2, Gutenberg v15.7.1)

#### Screenshots/Recordings

Self-Hosted site, Editor:

![Markup on 2023-05-09 at 16:03:42](https://github.com/Automattic/wp-calypso/assets/27249804/e2523f81-c767-4940-9a2e-00aa0bf059fb)

Self-Hosted site, Live Site:
![Markup on 2023-05-09 at 16:04:09](https://github.com/Automattic/wp-calypso/assets/27249804/9869eabb-bcd9-47c3-91ca-641ceb9682f1)

📌 ACTIONS
- Assigned to @Automattic/apex 
- Reported here: https://github.com/WordPress/gutenberg/issues/50492

**Comment by annezazu** [comment]
Closing this out as this was resolved in Gutenberg previously: https://github.com/WordPress/gutenberg/issues/50492
