### ISSUE TITLE
`/subscriptions/pending`: Launch the new "Pending" page to all non-EN external users

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#76756]
This issue will require changes in two code bases (WPCOM and wp-calypso). 

1. Redirect a non-EN external user to `/subscriptions/pending`, when they try to access `/email-subscriptions/?option=pending`
2. Open up the new Calypso "Pending" page, for all locale external users, when the "Pending" tab is clicked

**Comment by yansern** [comment]
D110369-code
