### ISSUE TITLE
Plans 2023: make the 2023 grid the default grid, and clean up previous plans code

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#76766]
Related to Automattic/martech#1533

We should make the 2023 grid the new default and consider cleaning up the codebase from obsolete/previous plans code. This can be done over one or more cleanup milestones:

- [ ] Remove the path whitelist (so 2023 grid becomes the default grid unless explicitly disabled)
- [ ] Remove the feature flag `onboarding/2023-pricing-grid` and anything from previous plans code (as it should be unreachable without the flag) e.g. [PlanFeatures](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-features) and [PlanFeaturesComparison](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-features-comparison) deleted.

**Comment by chriskmnds** [comment]
> Remove the path whitelist (so 2023 grid becomes the default grid unless explicitly disabled)

being addressed in https://github.com/Automattic/wp-calypso/pull/76768

**Comment by chriskmnds** [comment]
> Remove the feature flag onboarding/2023-pricing-grid and anything from previous plans code (as it should be unreachable without the flag) e.g. [PlanFeatures](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-features) and [PlanFeaturesComparison](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-features-comparison) deleted.

this is (partly) being addressed in https://github.com/Automattic/wp-calypso/pull/77493

**Comment by dzver** [comment]
@chriskmnds Are there any signup flows or situations left with the old pricing grid after this task is merged?

**Comment by chriskmnds** [comment]
> @chriskmnds Are there any signup flows or situations left with the old pricing grid after this task is merged?

After this issue is closed, No, there won't be any. The old pricing grids to be removed entirely.

There will be a couple of follow-ups to the PRs mentioned above though. The old grids are imported directly into the paid-media flow (some context in Slack p1685011294958529-slack-CV2TX2PAN) and in admin when visiting `/plans` with a p2 plan. They are kinda separate things, so can be tackled after [all the plumbing](https://github.com/Automattic/wp-calypso/pull/77493) is cleaned up.

**Comment by chriskmnds** [comment]
Closing this in favor of the more granular issues surfaced/created:

- [Plans 2023: Remove the path whitelisting for showing the new grid](https://github.com/Automattic/wp-calypso/issues/77650)
- [Plans 2023: Remove the feature flag onboarding/2023-pricing-grid and all the previous plumbing needed](https://github.com/Automattic/wp-calypso/issues/77651)
- [Plans 2023: Migrate p2 flow/admin pricing grid to use the new grid](https://github.com/Automattic/wp-calypso/issues/77652)
- [Plans 2023: Migrate paid-media flow to use the new grid](https://github.com/Automattic/wp-calypso/issues/77653)
- [Plans 2023: Remove old pricing grid code](https://github.com/Automattic/wp-calypso/issues/77654)
