### ISSUE TITLE
Stats: Empty state for video has inconsistent padding

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#76801]
### Quick summary

On a site with no video views, the detail page at `https://wordpress.com/stats/year/videoplays/$site_slug` looks like this:

<img width="1286" alt="Screenshot 2023-05-10 at 9 49 04 PM" src="https://github.com/Automattic/wp-calypso/assets/1126811/979fcde1-f765-419e-93dd-6617b98c2cd5">

On a site with views, it looks like this:

<img width="1243" alt="Screenshot 2023-05-10 at 9 57 26 PM" src="https://github.com/Automattic/wp-calypso/assets/1126811/a3938f5e-1a87-4054-bf5b-009f9772614a">

The top screenshot seems to have incorrect padding to me.

Tested with simple and atomic sites. I expect the same to happen with Jetpack sites as well.

### Steps to reproduce

1. Visit video plays detail page on a site with no video views
2. Ensure screen looks like first screenshot above

### What you expected to happen

More consistent padding. Perhaps something like the other empty state detail pages:

<img width="1245" alt="Screenshot 2023-05-10 at 9 59 39 PM" src="https://github.com/Automattic/wp-calypso/assets/1126811/45fd4ff8-febc-4cfc-ac1e-7dba3afbf8b0">

### What actually happened

Inconsistent padding.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate the same result on simple and AT sites - the `https://wordpress.com/stats/year/videoplays/site_address` page looks like it has improper padding compared to other empty pages, such as `https://wordpress.com/stats/year/searchterms/site_address`

#### Screenshots/Recordings

**Video Plays details with no recorded data**
![Markup on 2023-05-16 at 12:08:48](https://github.com/Automattic/wp-calypso/assets/27249804/d1e62409-d01d-49bf-8f97-b2c1e1680425)

**Search Terms details with no recorded data**
![Markup on 2023-05-16 at 12:10:38](https://github.com/Automattic/wp-calypso/assets/27249804/534f4a5d-3d19-4603-ae18-7e234de0d1cd)

📌 ACTIONS
- Assigned to Other
- CC @jeherve (Jetpack Stats)

**Comment by jeherve** [comment]
cc @kangzj who recently worked on #76929

**Comment by kangzj** [comment]
The new layout is behind a feature flag which aligns the video plays experience (at least the paddings) with other modules `stats/new-video-summary`.

@grzegorz-cp, is the feature ready to be released? i.e. could we remove the feature flag now?

<img width="1143" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1425433/7840d300-062c-4149-99b3-5907d24c7650">

**Comment by grzegorz-cp** [comment]
Sorry, I missed this notification. I'll check the FF and post an update here soon.

**Comment by grzegorz-cp** [comment]
The new videos page is almost ready, but there is an issue with indicating links for each possible click interaction. 
In the meantime, I'm opening a PR to fix the ordering problem described in this bug.

Once I'm back from AFK I'll also figure out a way to fix the new functionality behind the feature flag.

**Comment by grzegorz-cp** [comment]
Hi @cuemarie, I fixed the order of the header and the message. Could you verify that it's fine?

**Comment by cuemarie** [comment]
@grzegorz-cp Looks great across my Simple and AT sites! I'll leave this to you to close in case there's anything else you need to do. Thanks for the fix!

![Markup on 2023-06-21 at 10:20:48](https://github.com/Automattic/wp-calypso/assets/27249804/988b1074-8003-4f65-a342-d41f1a7b52a2)

**Comment by grzegorz-cp** [comment]
Thank you. I will close this now and address any future work in a separate ticket because nothing is tightly linked to the bug.
