### ISSUE TITLE
Design picking in onboarding has grey boxes

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#76821]
### Quick summary

Weird grey boxes visible in design picker during onboarding

### Steps to reproduce

1. Using Firefox
1. `/setup/free`
1. At design step, don't scroll down or resize before the page has loaded
1. Scroll down a bit, note boxes:

    <img width="1817" alt="Screenshot 2023-05-11 at 15 25 42" src="https://github.com/Automattic/wp-calypso/assets/87168/fd662a9f-aa84-408e-8fe1-1db2df40bb5b">

1. Boxes go away on hover, and entirely go away on window resize

https://github.com/Automattic/wp-calypso/assets/87168/a94d2af8-7fe0-49ea-b6ed-41dd8a1d2634

### What you expected to happen

No visual boxes

### What actually happened

Boxes

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

- Firefox browser

**Comment by taipeicoder** [comment]
Fixed via https://github.com/Automattic/wp-calypso/pull/76862
