### ISSUE TITLE
Design Picker theme preview: The Help button overlaps with the Continue button on mobile

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#76824]
### Quick summary

For mobile users, the continue button is (partially blocked) by the help (chat) button. 

### Steps to reproduce

1. Use a mobile resolution (resizing your browser window works too).
2. Go to the design picker (setup/site-setup/designSetup?siteSlug=your-site)
3. Click on a random theme (let's a free one)
4. Notice that the help icon (chat) is on top of the "Continue" button

### What you expected to happen

The help shouldn't overlap

### What actually happened

The buttons are overlapping.

![Screenshot 2023-05-11 at 15 55 39](https://github.com/Automattic/wp-calypso/assets/995955/5abd7e55-cb0f-4e9b-a72d-3c6e468fd261)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Copons** [comment]
@klimeryk I know you were looking at the chat button overlapping primary CTAs, and I was wondering if you have suggestions on how to address this.
E.g. hide the chat button on small screens, move it above the CTA, etc.

**Comment by klimeryk** [comment]
Yup, there's a related conversation on Slack (p1687895996371809-slack-C029S5LLB7D) with @jancavan and @sirbrillig on a similar issue in checkout. I'll be also going through our support flows this week (pbvpgB-39A-p2#comment-9330) and doing an audit and will be on the lookout for issues like this 🙇‍♂️

**Comment by dsas** [comment]
I can't reproduce this right now, I don't get the chat button at all. I've tried both with sites eligible and ineligible for live chat 🤔

**Comment by mmtr** [comment]
I think as of https://github.com/Automattic/wp-calypso/pull/77499 the presales chat icon is only displayed in the checkout and no longer shows up in the design picker.

**Comment by BogdanUngureanu** [comment]
Let's close it then. :)
