### ISSUE TITLE
Marketing Bar - Breaks layout for embeds

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#76851]
Embedding a post from a site on a free plan has a broken layout and cuts off the bottom of the embed with the site details and action buttons. This appears to be due to the presence of the marketing-bar. We will need to update the marketing bar to not be present within the context of embeds.

An embedded post from a free site with the marketing bar:
<img width="434" alt="Screenshot 2023-05-11 at 3 34 15 PM" src="https://github.com/Automattic/wp-calypso/assets/28742426/66571c11-474b-42ac-ab20-76119e785e6d">

After upgrading to a paid plan to get rid of the marketing bar:
<img width="434" alt="Screenshot 2023-05-11 at 3 34 15 PM" src="https://github.com/Automattic/wp-calypso/assets/28742426/5c9d67ec-c9cd-4cfe-b886-7ceb6c453084">

#### Steps to reproduce

1. Create a site with a free plan.
2. Launch the site and make it public.
3. Write a post.
4. Goto another site, open the editor, and embed that post's URL within the embed (core/embed) block.
5. Notice the layout is broken at the bottom and is cut-off.
6. Go back to the first site with the free plan and upgrade to a paid plan to get rid of the marketing-bar.
7. Try step 4 again, notice the layout is now as expected.

#### What I expected

The embed to display correctly regardless of the marketing bar.

**Comment by obenland** [comment]
Fix in D110647-code

**Comment by obenland** [comment]
Fixed in r266983-wpcom
