### ISSUE TITLE
Cannot bulk-edit posts on Simple sites

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#76852]
### Quick summary

When you go to the WP Admin view of the `Posts > All Posts` area, the check boxes to select posts in order to bulk edit them are not visible. (This currently only happens in for posts, pages are able to be bulk edited.)

### Steps to reproduce

1. Go to `Posts > All Posts`
2. Click on the View tab at the top of the page to switch to the WP Admin view
3. Attempt to bulk-edit a post

### What you expected to happen

That I'd be able to select posts to bulk edit them as per usual:

<img width="1254" alt="image" src="https://github.com/Automattic/wp-calypso/assets/4000628/217b4008-b835-4393-af12-b47ab3388edd">

### What actually happened

There is no checkbox to select posts:

![Markup on 2023-05-11 at 16:16:00](https://github.com/Automattic/wp-calypso/assets/4000628/d2934be1-abf3-47c0-9e34-e1e4822a89e5)

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Escalation thread: p1683836218047739-slack-C02FMH4G8

**Comment by cometgrrl** [comment]
@simison Can y'all take a look at this?

Per Eric, it's this line that's the issue:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Qcyhtva%2Scebqhpgvba%2Srkgrafvbaf%2Soybpxf%2Sfhofpevcgvbaf%2Sfhofpevcgvbaf.cuc%3Se%3Qqrrq9784%23109-og

**Comment by simison** [comment]
👋 Hey! I missed the ping for this on Friday. 🤦  

@Automattic/gold hi! I'm suspecting the bug is from access column here:

https://github.com/Automattic/jetpack/blob/1590b7ef94bcb803b58866d0afff35e652679c4c/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L108-L110

Can you take a closer look?

**Comment by romarioraffington** [comment]
> 👋 Hey! I missed the ping for this on Friday. 🤦
> 
> @Automattic/gold hi! I'm suspecting the bug is from access column here:
> 
> https://github.com/Automattic/jetpack/blob/1590b7ef94bcb803b58866d0afff35e652679c4c/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L108-L110
> 

Interesting! This code should only be run for users with the [newsletter feature enabled](https://github.com/Automattic/jetpack/blob/1590b7ef94bcb803b58866d0afff35e652679c4c/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L68). As I understand it, this feature is only enabled for A12s 🤔 

> Can you take a closer look?

We can! This week we're on support rotations, and so I suspect we won't be able to look into this more deeply until next week

**Comment by millerf** [comment]
> We can! This week we're on support rotations, and so I suspect we won't be able to look into this more deeply until next week

@romarioraffington That is what Support Rotation is about... Fixing issues as much as we can to help users/prevent issues to happen :) I'll have a look into it today. As this feature will be released some time this week, we want those bugs fixed beforehand!

Thanks a lot for reporting this @edequalsawesome!

**Comment by romarioraffington** [comment]
> @romarioraffington That is what Support Rotation is about... Fixing issues as much as we can to help users/prevent issues to happen :)

Okay, my bad! I thought the focus of our support rotations was to help users via chat and email versus making code fixes 😄 

> As this feature will be released some time this week, we want those bugs fixed beforehand!

Good call! I reviewed the code and it LGTM, I added a comment to fix a typo that was made.

**Comment by cuemarie** [comment]
Hey @romarioraffington and @millerf ! I'm still seeing this issue on Simple sites. Can y'all take another look at this fix, or has this fix not rolled out all the way yet?

**Simple Site**

![Markup on 2023-05-18 at 09:49:03](https://github.com/Automattic/wp-calypso/assets/27249804/44de62e7-2a05-47cf-a259-bd615b39d5ad)

**Atomic Site**

![Markup on 2023-05-18 at 09:49:15](https://github.com/Automattic/wp-calypso/assets/27249804/7f735644-7c3d-4151-8e6c-e5fc1a6b9114)

**Comment by cuemarie** [comment]
Reported here yesterday: https://wordpress.com/forums/topic/bulk-editor-broken-its-not-displaying-check-boxes/

**Comment by synora** [comment]
User report 6304079-zen.

**Comment by cuemarie** [comment]
User report from #77109 

- [ ] 6304545-zen

**Comment by mgozdis** [comment]
User report 6305034-zd-woothemes Simple Site

**Comment by cuemarie** [comment]
📌 UPDATE
- A fix for this is in the works, and will likely land next week: https://github.com/Automattic/jetpack/pull/30747
- Source: p1684240158229269/1684221960.515919-slack-CBG1CP4EN

📌 ACTIONS
- Assigned to Other

**Comment by romarioraffington** [comment]
Looks like we've had 3 reports so far. I created a hotfix to get this own sooner.


Thoughts on this @millerf @jeherve. Patch: D111335-code

**Comment by millerf** [comment]
https://github.com/Automattic/wp-calypso/issues/77109 was expected to be deployed this week, however it did not happen.

I am deploying @romarioraffington 's hotfix: D111335-code on WPCOM right now.

**Comment by millerf** [comment]
Closing it for now as hotfix was deployed.

**Comment by alliebbush2** [comment]
User reported that the fix added extra HTML breaks to the plugin they developed.
![Screenshot 2023-05-20 at 9 11 20 AM](https://github.com/Automattic/wp-calypso/assets/97132910/d1c2a935-b9f3-4a7f-8edb-7c1968fda9f0)
I told them that I would let the developers know.
6300383-zd

**Comment by romarioraffington** [comment]
Hey @alliebbush2,

Thanks for reporting this! I took a look at the ticket to get some additional context. I understand that the developer has found a temporary workaround, but we still need to fix the issue on our end. Would it be possible for you to share steps to reproduce or a site where the issue exists so that I can debug?

Thanks!
