### ISSUE TITLE
Add uniform border coloring to plans: PlanCard component

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7687]
@rickybanister had a [nice idea](https://github.com/Automattic/wp-calypso/pull/5212#issuecomment-242508388): what if use the same color for borders for the same plans across different pages? While redesigning `/plans` page, we introduced the colored bottom border of the plans headers:

![image](https://cloud.githubusercontent.com/assets/4988512/17998117/0672cf46-6b73-11e6-9faf-6fd884cc2ad4.png)

An idea how to keep this consistent is to create a new `PlanCard` component which could be used to wrap the plans headers, upgrade nudges, etc. However, I'm not sure if this would work because different components/pages have different needs. As an example: on My Plans page, we need to add border around the plan's header on all the sides while on the plans page or in upgrade nudges we need to add the border only at the bottom.

Thinking more, we could solve this easily by adding props to `PlanCard` component. What is more, we could pass a `className` prop so we don't have to wrap the `PlanCard` component in another `<div>` just for giving it different className.

Other possible concern is that the `PlanCard` might need to render different HTML elements. Example: on `/plans`, we wrap the plan header in `<header>`:

![selection_140](https://cloud.githubusercontent.com/assets/4988512/17998562/60b75bb4-6b75-11e6-9c0a-8f86311bca30.png)

However, in some other places, using `<header>` might not be appropriate (e.g.: the upgrade nudge). Maybe we could solve this by passing different prop whether to render `<header>` or just a `<div>`?

Last but not least, what about `PlanCompareCard`?

![selection_141](https://cloud.githubusercontent.com/assets/4988512/17998654/cd409df4-6b75-11e6-82e5-02cc6f8af09c.png)

Where would we add the colored border?

/cc @rickybanister @gwwar @artpi @mtias

**Comment by rickybanister** [comment]
Is that SEO page not styled yet? 

I think the color just need to be present to help ground the user in which plan their viewing. It's just a secondary affordance. On the SEO page (not sure what the design is supposed to look like) we could just keep the colored border at the bottom of the plan header. If the page is going to be long enough to scroll we don't get any benefit from having a colored border way down at the bottom.

On the My Plan page, the primary card explaining your current plan is small enough that the border helps it stand out from the other cards on the page.

**Comment by lamosty** [comment]
Sorry, the page should look like this:

![selection_142](https://cloud.githubusercontent.com/assets/4988512/18013649/591830a0-6bbf-11e6-90e0-4ae55aa176cf.png)

> On the SEO page (not sure what the design is supposed to look like) we could just keep the colored border at the bottom of the plan header.

Yeah, that'll work. :)
