### ISSUE TITLE
Feature Request: [Launchpad] Add "don't show this again" option in fullscreen modal

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#76876]
### What

For customers who are exposed to Launchpad but are not ready to launch their sites yet or focus on the pending tasks presented by Launchpad, the fullscreen modal that pops up when they switch contexts in Calypso is too frequent and might come across as pushy.

Adding a "do not show this again" option would give users the power to exit that flow if they wish, while future improvements like https://github.com/Automattic/wp-calypso/issues/76076 would give them a way to jump back into Launchpad flows whenever they are ready.

### Why

I can take time for customers to feel confident about their sites, so having a reminder every time they switch editing context that the site is not launched yet can have the opposite effect - it might become a reminder of the things they were not able to do yet, which can be demotivating, instead of empowering.

While creating a site, a user might bounce around the Site Editor and the Page/Post Editor several times, and every one of those context switches will expose them to Launchpad with no way of preventing it from showing up again. 

### How

A "Don't show this again" checkbox could be added next to "Skip to Dashboard", and clicking on "Skip to Dashboard" would save that choice.

![CleanShot 2023-05-12 at 14 04 58@2x](https://github.com/Automattic/wp-calypso/assets/14153300/60f434a8-1c30-4910-9b51-72aceebba2e9)

A similar option already exists in the Launchpad modal shown after publishing a page (even though that doesn't seem to be working).

![CleanShot 2023-05-12 at 14 06 00@2x](https://github.com/Automattic/wp-calypso/assets/14153300/1c18629f-b39e-468a-931d-63cfb9623eef)

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- CC: @Automattic/serenity Looks like y'all are currently working on Launchpad issues

Related: https://github.com/Automattic/wp-calypso/issues/76880

**Comment by sixhours** [comment]
cc @nuriapenya for your thoughts on this!

**Comment by daledupreez** [comment]
I think we should do this, though we should consider whether we also need a site launch task in our customer home task lists to ensure that we guide users with unlaunched sites to launch them.

**Comment by daledupreez** [comment]
Further discussion is visible here: paYKcK-3gy-p2

Our initial thinking is that we should show the same set of tasks in Customer Home after users skip the full-screen launchpad, but we're still discussing this further.

**Comment by liviopv** [comment]
@daledupreez considering we launched the "Skip for now" p7DVsv-izx-p2 option in the fullscreen modal and it seems to be a positive change, I think it's ok to close this issue, right?

**Comment by daledupreez** [comment]
@liviopv, I think that's up to you -- we've kept it open because we're still rolling it out to a handful of remaining flows. As an example, we still need to land the following PRs:
 * https://github.com/Automattic/wp-calypso/pull/82128
 * https://github.com/Automattic/wp-calypso/pull/82066

**Comment by daledupreez** [comment]
I am now going to close this issue as we've rolled out the option to all flows that include the launchpad.
