### ISSUE TITLE
WooExpress Upgrades > Plans track

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#76877]
In peapX7-1PC-p2#comment-2863,

We're taking over `Upgrades > Plans` track from Serenity. We'll need to ensure the track is fired and update Google Sheet with the details.

### Acceptance criteria

1. In WooExpress site, when clicking on `Upgrades > Plans` on the sidebar, it should fire a track
2. Ensure the track is fired from both WooCommerce screen and Calypso screen
3. Update sheets with the details (refer link in peapX7-1PC-p2#comment-2863)

**Comment by chihsuan** [comment]
Hey @ilyasfoo It seems that `Upgrades > Plans` menu item in the WooCommerce screen (*.wpcomstaging.com) and Calypso screen (wordpress.com) are different. One is rendered in PHP, and Calypso renders the other.

I found that we can add a track in Calypso [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/sidebar/item.jsx#L31-L39). However, I can't find the code that renders the menu item in the WooCommerce screen. Any idea where to find it?

Alternatively, we add a track in WooCommerce screen via `wc-calypso-bridge` but I think the track name should be like `calypso_sidebar_item_click`. So, I feel like it might not be very suitable in that case. Any thoughts?

cc @daledupreez Need some guidance here  🙏

**Comment by ilyasfoo** [comment]
Hey, @chihsuan!

> However, I can't find the code that renders the menu item in the WooCommerce screen. Any idea where to find it?

Good question, I think the menu is [rendered by Jetpack](https://github.com/Automattic/jetpack/blob/c9fefe7407640e40c37c20cd0430681b486be809/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L138-L178) via nav unification.

> Alternatively, we add a track in WooCommerce screen via wc-calypso-bridge but I think the track name should be like calypso_sidebar_item_click. So, I feel like it might not be very suitable in that case. Any thoughts?

I'm thinking it's okay to have the track name prepended with calypso since it's a shared menu between Calypso and WC. I agree with this alternative, it might be the simplest we have 👍

**Comment by chihsuan** [comment]
> I'm thinking it's okay to have the track name prepended with calypso since it's a shared menu between Calypso and WC. I agree with this alternative, it might be the simplest we have 👍

Nice, thank you! 😊
