### ISSUE TITLE
Simple Sites with custom domains do not embed on other simple sites properly

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#76892]
When embedding a post from a wpcom site with a mapped domain, it appears as a link in the editor instead of showing the embed preview. The embed block reverts from the "wp-embed" variation to the "link" variation.

This does not seem to happen with simple sites with without a subdomain, nor for atomic sites w/ or w/o a custom domain.

#### Steps to reproduce

1. Create a simple site with a custom domain.
2. Write and publish a post.
3. On another site, create a post.
4. Enter an embed block in the editor, paste the url for the post you created in step 2 into the input field and press enter.
5. Notice the embed is only shown as a link instead of embed preview:

<img width="786" alt="Screenshot 2023-05-12 at 1 19 29 PM" src="https://github.com/Automattic/wp-calypso/assets/28742426/4dd1b952-65a7-4dd4-9345-d327674e707a">

6. Repeat these steps sharing a post from a simple site without a custom domain, verify the embed appears as expected in the editor.

#### What I expected

The embed to render as expected:
<img width="597" alt="Screenshot 2023-05-12 at 1 21 32 PM" src="https://github.com/Automattic/wp-calypso/assets/28742426/542ff97c-f750-4eca-8bf5-d0c4cc18957c">

#### What happened instead

The embed was only shown as a link.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested embedding on Simple – **Replicated**
- Tested embedding on Atomic – Could Not Replicate _(different problem presents there)_

📌 FINDINGS/SCREENSHOTS/VIDEO
- **Tested the Embed block on a Simple site**:
     - Embedded post link from a simple site, custom domain: **converted to link**
     - Embedded post link from a simple site, default domain: _embedded as expected_
     - Embedded post link from an AT site, custom domain:  _embedded as expected_
     - Embedded post link from an AT site, default domain:  _embedded as expected_

![Markup on 2023-05-16 at 11:38:00](https://github.com/Automattic/wp-calypso/assets/27249804/171cdb83-688a-428a-8ba9-1ecc377c923a)

![Markup on 2023-05-16 at 11:38:27](https://github.com/Automattic/wp-calypso/assets/27249804/4135f659-9581-4103-be26-72db523d9139)

- **Tested the Embed block on an AT site**:
     - Embedded post link from a simple site, custom domain: `Sorry, this content could not be embedded.`
     - Embedded post link from a simple site, default domain:  `Sorry, this content could not be embedded.`
     - Embedded post link from an AT site, custom domain:  _embedded as expected_
     - Embedded post link from an AT site, default domain:  _embedded as expected_

![Markup on 2023-05-16 at 11:43:34](https://github.com/Automattic/wp-calypso/assets/27249804/99fe3872-127a-4f24-bda6-aec93d2c6236)

![Markup on 2023-05-16 at 11:44:07](https://github.com/Automattic/wp-calypso/assets/27249804/e8f581f9-91af-42a7-a621-f67a67d24773)


📌 ACTIONS
- Assigned to Non-Urgent

**Comment by Addison-Stavlo** [comment]
D111424-code should fix the original issue noted

**Comment by Addison-Stavlo** [comment]
D111803-code should resolve the issue noted with atomic sites embedding posts from simple sites.

**Comment by Addison-Stavlo** [comment]
Closing this issue now as everything should be resolved.

Note - there is some caching with embeds so if some are still looking broken it may be due to that. I would test a newly created post, and expect the cache to clear after a day or so.
