### ISSUE TITLE
Themes: Add renderToString() tests for theme sheets

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#7690]
Add a test, like this one for the [logged-out layout](https://github.com/Automattic/wp-calypso/blob/master/server/pages/test/index.js#L17), for [theme sheets](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/theme/main.jsx). This should catch any changes that cause the `renderToString()` call on the theme sheets to break before they hit production.

**Comment by ockham** [comment]
BTW I think we should move the test for logged-out layout into `client/layout`.

**Comment by ockham** [comment]
(And the theme sheet test should live in `my-sites/theme`.)
