### ISSUE TITLE
Stats: datetime localization

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#76912]
> Show a small notice showing the timezone.
> Timezone dropdown and adjust the timezone.
>   - Some of the endpoints accept an offset e.g. stats/visits.

### Timezone

Currently in most places, the default timezone of momentjs is used and in some cases the browser timezone is used. We want to unify the usage to make the experience consistent. IMO, we could get timezones in the following order. In case of the data doesn't exist, then roll to the next one.

- Site timezone
- Current user timezone
- Browser timezone

I would prefer to create a hook which returns a `moment` instance with timezone and locale set, and re-render the component when the timezone or locale change.

Side note, we should use `withLocalizedMoment` to apply the locale to moment first, and then apply the timezone offset.

https://github.com/Automattic/wp-calypso/blob/3735e18a91bec9a04689832bd371138609b1b841/client/my-sites/stats/controller.jsx#L185

### Start of week

The backend seems to start on Monday always, and the frontend should start from Monday too always. A better solution would be respecting user settings tho.

Related:

- https://github.com/orgs/Automattic/projects/484/views/1?pane=issue&itemId=26938992
- https://github.com/Automattic/wp-calypso/pull/76520#discussion_r1183151234
- https://github.com/orgs/Automattic/projects/484/views/1?pane=issue&itemId=26938995
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/16186
- [ ] https://github.com/Automattic/wp-calypso/issues/74369
```

**Comment by CGastrell** [comment]
I think a dropdown to freely choose a timezone could help, starting it with site's timezone as default. To my knowledge there is no timezone option on the user profile.

**Comment by kangzj** [comment]
@CGastrell Here's a relevant P2: pejTkB-1Lh-p2. Might need design 😄

**Comment by kangzj** [comment]
Plus: Some of the APIs accept `offset` as a param for the sake of more flexible timezone support but not all of them support it.

**Comment by jeherve** [comment]
Adding some related issues and tickets, for reference:

- https://github.com/Automattic/jetpack/issues/40591
- #47000

- 9153038-zd-a8c
- 3330991-zd-a8c
- 24094006-hc
- 3466616-zd-a8c
- 28266031-hc
- 5892100-zd-a8c
