### ISSUE TITLE
Domain Management: Removing last custom MX record prompts the user about deactivating email forwards

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#7691]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage
2. Select a site with a custom domain (preferably a test domain so you don't break your email on a real domain)
3. Select the custom domain
4. Select DNS Records to open the DNS records for your custom domain
5. If you have an MX record for WordPress.com email forwarding, delete it (to set up custom MX records instead)
6. If you don't have any custom MX records, add at least one (e.g. an MX record for the root domain handled by `mail.yourgroovydomain.com`)
7. Delete your custom MX record(s)
#### What I expected

I expected all records to be removed, possibly with a warning that this will stop any email service set up with my third-party email provider.
#### What happened instead

When I removed the last custom MX record, I saw a confirmation dialog with this message:

> Are you sure?
> Removing this record will delete your current Email Forwards.

This confirmation was added in #6319 but doesn't make sense if you are removing custom MX records (for third-party email service) instead of removing the MX record for WordPress.com email forwarding.

cc @rads 
#### Browser / OS version

Chrome 52.0.2743.116 / Mac OS X 10.11.6
#### Screenshot / Video

Screenshot of the confirmation dialog I saw after removing custom MX records for externally purchased Google Apps email service:

![screen shot 2016-08-26 at 11 54 13 am](https://cloud.githubusercontent.com/assets/8658164/18003456/93379e68-6b85-11e6-8201-ec6841e283f5.png)
#### Context / Source
# dogfooding

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed that this is still an issue as described above.  I did verify that if you also have e-mail forwards set up they're not affected by deleting the MX record for a custom 3rd-party service.
