### ISSUE TITLE
Domain Management: Move email forward confirmation from WP Admin to Calypso

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#7692]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage
2. Select a site with a custom domain (that doesn't have Google Apps or third-party email service already set up)
3. Select the custom domain
4. Select "Email"
5. Select "Add Email Forwarding"
6. On the Email Forwarding screen, select "Add New Email Forward"
7. Enter the details for a new email forward
8. Check your email at the forwarding address for the email to confirm the email forward
9. Click "Confirm Email Forward" in the confirmation email
#### What I expected

I expected to be taken back to the Email Forwarding screen in Calypso, with a message that my new email forward was confirmed.
#### What happened instead

I was taken to my site's My Domains page in WP Admin: `/wp-admin/paid-upgrades.php?page=domains&email_forward=1`

The confirmation message appeared at the top of the screen there:

> Your email forward has been setup.

It would be great to move this confirmation into Calypso, instead of sending the user to WP Admin.
#### Browser / OS version

Chrome 52.0.2743.116 / Mac OS X 10.11.6
#### Screenshot / Video

Confirmation email:

![screen shot 2016-08-26 at 12 21 59 pm](https://cloud.githubusercontent.com/assets/8658164/18003778/ccb07776-6b87-11e6-8f43-9980fe42c014.png)

Confirmation message in WP Admin:

![screen shot 2016-08-26 at 11 56 49 am](https://cloud.githubusercontent.com/assets/8658164/18003780/d9d3db78-6b87-11e6-9601-4d585be0ee38.png)
#### Context / Source
# dogfooding

**Comment by klimeryk** [comment]
Per `p2MSmN-5QF-p2`, when creating this view, we should make it available to logged out users too, so that the admin of the site can set up email forwards for others (possibly non-users) and so that they could confirm it themselves, without the need to forward the confirmation back to the admin...
Props to @thehenrybyrd for the suggestion.

**Comment by klimeryk** [comment]
According to https://github.com/Automattic/wp-calypso/pull/13203#issuecomment-314122059, this should be resolved.
