### ISSUE TITLE
Site Assembler - Patterns with maps don't render sometimes because the domReady is undefined

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76936]
## What

Sometimes patterns with the block `wp:jetpack/map` don't render the map.

|MAP ✅| MAP ❌|
|---|---|
|![Image](https://user-images.githubusercontent.com/1881481/238293221-16c51999-21e6-4b3a-85de-0cc4e9b77b5c.png)|![Image](https://user-images.githubusercontent.com/1881481/238293243-3e5b5b90-f7d0-4368-84bb-8e77fa56a590.png)|
|![Image](https://user-images.githubusercontent.com/1881481/238296003-b8300a42-c770-46be-8bf3-5e773b9f434b.png)|![Image](https://user-images.githubusercontent.com/1881481/238295977-34f500f8-465e-4642-bfe3-cffd6c5f59af.png)|
|![Image](https://user-images.githubusercontent.com/1881481/238297027-8e2880dd-0303-4b09-ae94-5c693d672c42.png)|![Image](https://user-images.githubusercontent.com/1881481/238297056-a3f926a7-42d0-4690-a58f-bf4f921542ef.png)
|![Image](https://user-images.githubusercontent.com/1881481/238297318-87b60d2a-c965-4d0c-8d6f-233ef560019a.png)|![Image](https://user-images.githubusercontent.com/1881481/238297351-7452bdde-3cc6-4ce9-9f9b-fbfb5e5124c5.png)|

## Why

Maybe the cause is that `domReady` is `undefined`.

## How
- Explore the patterns in the category `Contact`, you should see **four patterns with maps**
- Find a fix for the `domReady` issue if that is the cause
- Check if it might be something related to the map style, because when the style is terrain the map uses **Mapbox** otherwise uses  **Apple maps**. It doesn't seem related because both types are not rendered randomly.
![Image](https://user-images.githubusercontent.com/1881481/238289238-391766f3-50e9-40b3-8527-25e76fa3ece4.png)
![Image](https://user-images.githubusercontent.com/1881481/238289283-4dc60ae4-98b6-476e-b46b-b951b4f4d659.png)

**Comment by miksansegundo** [comment]
@arthur791004 where is the code that uses `domReady`?

**Comment by arthur791004** [comment]
[Here](https://github.com/Automattic/jetpack/blob/f8a574361269b24174103f5da856c60ebf12e471/projects/plugins/jetpack/extensions/blocks/map/view.js#L6). On production, it will try to get the value from `window.wp.domReady`

**Comment by miksansegundo** [comment]
I debugged it and found that the issue happens because the script `wp-dom-ready` is sometimes missing in the response of `get_rendered_patterns`.

|WITH|WITHOUT|
|---|---|
|<img width="293" alt="Screenshot 2566-05-22 at 23 53 25" src="https://github.com/Automattic/wp-calypso/assets/1881481/51d1556e-7fd1-4f04-9e56-c8686fa5d2d3">|<img width="309" alt="Screenshot 2566-05-22 at 23 53 09" src="https://github.com/Automattic/wp-calypso/assets/1881481/8b6d1ab6-5173-4834-b789-9ce036b94c32">|

You can debug them using the pattern IDs with maps `10413, 5634, 280, 1397`. I still don't know the root cause. Maybe you have ideas?

**Comment by miksansegundo** [comment]
Maybe there is an issue related to the dependency between `wp-dom-ready` and `wp-polyfill` that is injected via webpack. See [dependency-extraction-webpack-plugin](https://github.com/WordPress/gutenberg/tree/trunk/packages/dependency-extraction-webpack-plugin).

I found issues that explain about the polyfill dependency and how the map assets load in the editor: 
 
- https://github.com/Automattic/jetpack/pull/13624
- https://github.com/Automattic/jetpack/pull/19552

**Comment by miksansegundo** [comment]
@Automattic/lego 🚨 It seems this issue is **randomly** affecting all patterns with Jetpack blocks.

I'm seeing this same issue in other patterns with the Jetpack blocks like `jetpack/subscriptions` and `jetpack/recurring-payments`.

You can reproduce it in the assembler by scrolling the list of patterns in the category `Shop` with the JS console open.

<img width="783" alt="Screenshot 2566-05-23 at 14 11 16" src="https://github.com/Automattic/wp-calypso/assets/1881481/b145870e-3ec1-4c48-8324-dd2f9e2cfb90">

<img width="751" alt="Screenshot 2566-05-23 at 14 11 30" src="https://github.com/Automattic/wp-calypso/assets/1881481/ad5ed85b-2cad-46d8-a4a8-51a083edbac7">

**Comment by miksansegundo** [comment]
I think it is random because the request `/block-renderer/patterns/render` receives multiple patterns and **only the first pattern** that requires `wp-dom-ready` will get it. 

Maybe we have to requeue the assets for each pattern before running `apply_filters( 'the_content', $pattern->html )`. 

See `get_rendered_patterns` fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Soybpx%2Qeraqrere%2Soybpx%2Qeraqrere%2Qcnggreaf.cuc%3Se%3Qo2n4r08s%2386-og

**Comment by miksansegundo** [comment]
🐛 Found it!! See D111593-code

**Comment by arthur791004** [comment]
Closing it as it's completed.
