### ISSUE TITLE
Stats: too wide domain upsell at insights page

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#76952]
### Steps to reproduce

1. Open Stats->insights (`https://wordpress.com/stats/insights/SITE`) using a site without domain
2. Scroll down and see domain upsell
    <img width="1683" alt="Screenshot 2023-05-15 at 22 55 44" src="https://github.com/Automattic/wp-calypso/assets/87168/97b0d77b-e41e-45c6-ad2f-522e1fbc5e1a">

Also affects the new subscriber stats page:

<img width="1817" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/e6d022e8-9d7f-4935-b98b-465a76219f59">

### What you expected to happen

Domain upsell banner fit in nicely.

### What actually happened

Too wide upsell banner.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by simison** [comment]
@jsnmoon hi! Could the team red have a look?

**Comment by jsnmoon** [comment]
> hi! Could the team red have a look? (@simison)

We'll get this on our board 👍
