### ISSUE TITLE
Launchpad: Edit task should always open Site Editor (not browser mode)

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#76966]
At the moment, when users click the `Edit site design` task from the Launchpad, they are directed to the Site Editor but with the browser view activated. Currently, users are not yet familiar with templates or any navigational cues. Ideally, they should be in **_edit mode_** so they can change things right away without having to extra-click.

**Current issue:**

https://github.com/Automattic/wp-calypso/assets/7931304/95a364d1-e432-418b-b5fd-5977363523ac

**Proposed solution:**

Open the editor in **edit mode**, and ideally with the sidebar open so users have a good overview of what to do right away: 

![Image](https://github.com/Automattic/wp-calypso/assets/7931304/ed632a14-2a1d-4f65-a893-74646612329d)

**Comment by sixhours** [comment]
Looks like this was closed with https://github.com/Automattic/wp-calypso/pull/78742
