### ISSUE TITLE
Flaky E2E: Validating Instagram block in published post

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#76971]
### Spec file

blocks__core-jetpack-extended.ts

### TeamCity ID

10020884

### Logs

``` 
locator.waitFor: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe.instagram-media').locator('text=woocommerce').first() to be visible
============================================================
at InstagramBlockFlow.validateAfterPublish (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts:62:33)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:90:23)
```

**Comment by worldomonation** [comment]
I filed a duplicate issue in https://github.com/Automattic/wp-calypso/issues/77190. 

Normally I'd close my issue, but @WunderBart and I have had some iterations on the linked issue, so closing this one as duplicate. Sorry Karen!

**Comment by karenroldan** [comment]
> Normally I'd close my issue, but @WunderBart and I have had some iterations on the linked issue, so closing this one as duplicate. Sorry Karen!

No problem! There are multiple linked issues in #77190 and it makes sense to keep that open. 👍🏻
