### ISSUE TITLE
Jetpack.com/pricing modal format changes

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#76992]
### What

Per James' request on pdrWKz-YO-p2, we need to make a few small formatting changes to the modals on Jetpack.com/pricing

**Changes:**

- [x] Bring "Coming soon" list items to the top, for each product.
- [x] Make "Coming soon" bold.
- [x] For all coming soon list items, change the checkmark to the wrench icon. This can be found in the WordPress Design Library icon set (ping me if we need the svg!)

**Verbiage changes for Social modal only:**

- [x] Add coming soon list item to top: "Auto-sharing to Instagram & Mastodon" to the top of the "includes" list.
- [x] Benefits list change: "Coming soon: Share multiple images at once on social media platforms" to "Coming soon: Share multiple images to social media"
- [x] Benefits list change: "Coming soon: Upload and share videos to your social platforms" to "Coming soon: Upload & automatically share videos to social media"

**Current modal design**
![social current](https://github.com/Automattic/wp-calypso/assets/214813/e96de91f-8d5d-41c9-8164-8145ae187ed7)

**Proposed**
![social quick win](https://github.com/Automattic/wp-calypso/assets/214813/4056a8b3-38fa-4985-bd1a-6e4ab3fbd8cb)

### Why

To make upcoming features more prominent and scannable.

**Comment by IanRamosC** [comment]
Solved in #77049
