### ISSUE TITLE
Reader: enable Likes for all posts

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#770]
Raised by @shaunandrews 

Some posts don't have a Like button, and its really disorienting:

![screen shot 2015-06-09 at 10 42 40 am](https://cloud.githubusercontent.com/assets/191598/8060637/83b27dea-0e94-11e5-997e-284bd76be01d.png)

There's a few reasons why this may happen:
- The author has disabled Likes in their site settings.
- The site may not have Jetpack installed.
- Maybe more???

Like'ing is THE primary action in Reader, and to have it missing from some posts (for reasons that are not at all obvious) is really strange. **We should always show the like button in Reader.**

A few caveats:
- If the site has Like's disabled, then we shouldn't send any notifications when someone likes their post.
- If the site doesn't have likes at all (no Jetpack) then we should store the relevant data ourselves.

Example feed stream with missing likes: https://wordpress.com/read/blog/feed/5731

**Comment by jancavan** [comment]
> The author has disabled Likes in their site settings.

I disabled Likes on one of my posts and the Like button still shows up both on my Reader and on a different account's Reader that's following my test blog. So this one in particular may not be the reason why the Like button is non-existent on some posts. Either that, or my example was just an isolated case.

**Comment by designsimply** [comment]
> I disabled Likes on one of my posts and the Like button still shows up both on my Reader and on a different account's Reader that's following my test blog.

Background: a change was made on Jun 11, 2015 to show the Like button for all posts from wpcom and Jetpack sites (6348-gh-calypso-pre-oss)
