### ISSUE TITLE
Shortcodes not working on FSE themes

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/wp-calypso#77001]
### Quick summary

When third party shortcodes are used within the Editor (FSE Theme), the shortcodes appear as text only.

All relevant plugins were updated and activated at the time.

Work-around: The shortcodes work on a regular Post/Page. For example, if the shortcodes are used on a homepage, you'll want to re-create the homepage within a Page.

### Steps to reproduce

1. Activate a FSE Theme
2. Add shortcode within the Editor
3. Preview page
4. Code can be seen on the page

### What you expected to happen

I expect to see results from the third party shortcode.

### What actually happened

I see text only code.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by adelineyaw** [comment]
User report: 42655115-hc 

Work-around resolved this issue.

Theme: Blank Canvas

**Comment by inaikem** [comment]
Closing this issue for now since it's expected behaviour following the [WP 6.2.1 release](https://wordpress.org/news/2023/05/wordpress-6-2-1-maintenance-security-release/) and associated May 12th WPcom update: p1683882880050879-slack-CB0B2G43X .

Cc: @cuemarie

**Comment by arinoch** [comment]
For posterity, adding report 43360805-hc as also having this issue.

@inaikem, do you know if this is a temporary stopgap or the permanent fix? I suspect mine and @adelineyaw's interactions aren't going to be the only two.

**Comment by inaikem** [comment]
Thanks James. My current understanding is this is a permanent change made in Core (WP 6.2.1). We deployed a related update to WPcom several days ahead of the Core release, which has since made its way to WPcom, too.

Pinging @xknown for clarification and any additional context.

**Comment by cuemarie** [comment]
**Workaround**

Wrapping the Shortcode in a Template Part allows it to load.  Tested with `[portfolio]` on a simple site and some `[smart slider xyz]` shortcode on a user's Atomic site and it worked in both places. Hattip @liviopv for digging that up!

**Comment by ariel-maidana** [comment]
Adding for posterity: 6299446-zd-woothemes

**Comment by arinoch** [comment]
Adding for posterity: 43438059-hc

**Comment by Greatdane** [comment]
Adding another affected user; 43347556-hc

**Comment by poeticabdul** [comment]
Another user 35013727-hc

**Comment by dev-sabbir** [comment]
Another user 6306041-zd-woothemes

**Comment by daria2303** [comment]
6289140-zd-woothemes

**Comment by JoshuaGoode** [comment]
6.2.2 was released to WPCloud/Atomic over the weekend, which fixes this regression (restoring the use of shortcodes in block templates) while also resolving the vulnerability

- p9o2xV-36v-p2
- https://wordpress.org/news/2023/05/wordpress-6-2-2-security-release/
- https://wptavern.com/wordpress-6-2-2-restores-shortcode-support-in-block-templates-fixes-security-issue


Simple sites still have a patch that will continue to prevent shortcodes in block templates but Atomic doesn't. (edited) 

Note that 6.2.2 can break/affect the visuals of certain shortcodes as the HTML output is modified -- adding <p> and <br> tags.
https://core.trac.wordpress.org/ticket/58366

**Comment by pak-cia** [comment]
+1 - 7363867-zen
