### ISSUE TITLE
Jetpack: Do not list "subscriber" sites

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#7701]
Jetpack sites can have users with the "Subscriber" role, not used on WP.com. Those users can see those sites in WP.com

But as a Subscriber, it was a rather pointless experience:

![2016-08-26 at 16 59](https://cloud.githubusercontent.com/assets/88897/18021658/a3e6f8b6-6bae-11e6-9a9c-a57983d530ca.png)

Since they were only a subscriber, they couldn't see anything on Insights, which is the de facto "home page" and they couldn't see any option on the side.

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed that this is still an issue as described above.  A Subscriber gets a completely useless stats dashboard and no other options.  But I'm wondering if that's better than the alternative of not showing it at all...is there another location that a Jetpack user can see all of the sites they have connected via their WPcom logon?

Likely related: #6068

**Comment by KokkieH** [comment]
We had a user contact us in the forums (819568-f) looking for an explanation why WooCommerce.com was showing in their My Sites list. Given the number of subscribers on that site I'm surprised this hasn't come up in support before.

**Comment by beaulebens** [comment]
@ebinnion I seem to remember you working on something along these lines. Am I imagining that, or did you do this once already and we came up against a gotcha of some sort?

**Comment by ebinnion** [comment]
I shipped something in r149656-wpcom which should fix this. Basically, it modifies the `/me/sites` response to only return sites where the user has the `edit_posts` cap.

**Comment by lancewillett** [comment]
Confirmed in testing that a subscriber role doesn't see the Jetpack site in their Calypso sites list any more.

However, a minor UX note just for history — if you are logged in, and view the Jetpack site front-end, you'll see the WP.com top navigation bar (if enabled in Jetpack settings, of course).

In that "masterbar" navigation, top left if you click My Sites — you'll still see the current site's menu items such as Stats, Plan, Blog Posts, and Pages. Which you probably shouldn't have any access to at all, right?
