### ISSUE TITLE
`/subscriptions/*`: Focus outline on navigation tabs shouldn't stick

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#77018]
The focus outline on navigation tabs stays displayed even when we are not "tabbing" through the page:

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/018d23eb-5edb-4cff-bf34-7c10e8ba5070)

How to reproduce: Simply click on any tab and the focus outline will stay there.

Also, the outline could be adjusted a little bit to wrap around the tab labels with a little bit of space.

This was discovered by @mashikag during our pair-programming session.

**Comment by yansern** [comment]
External portal has moved to reader portal.
