### ISSUE TITLE
Editing Toolkit: full-site-editing plugin producing PHP warnings

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#77027]
On my annual support rotation, I found that the full-site-editing plugin is producing PHP warnings:
```
PHP Warning:  Undefined property: A8C\FSE\WP_REST_Help_Center_Support_Availability::$is_wpcom in /wordpress/plugins/full-site-editing/3.65612/help-center/class-wp-rest-help-center-support-availability.php on line 70 
```

Logs: 3053f-pb
related ticket: 6287861-zd-woothemes

**Comment by jp-imagines** [comment]
Also reported in 6681735-zd-a8c (plugin version 3.75083).

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- On my AT Test site with only default plugins active, I don't see the same warning in my site's PHP logs.  I have the following plugins active:

```
| akismet           | active | none                         | 5.2       |
| gutenberg         | active | none                         | 16.4.0    |
| jetpack           | active | version higher than expected | 12.5-a.11 |
| layout-grid       | active | none                         | 1.8.4     |
| page-optimize     | active | none                         | 0.5.3     |
| full-site-editing | active | none                         | 3.75083  
```

📌 ACTIONS
- Assigned to @Automattic/vertex 

📌 Message to Vertex
- Couldn't replicate, but based on the warning itself (`A8C\FSE\WP_REST_Help_Center_Support_Availability`), could this be related to specific circumstances, such as while a user is in chat?
