### ISSUE TITLE
Plans: Remove videos and audio from Personal Plan space feature

### ISSUE THREAD

**Issue by rwaynick** [Automattic/wp-calypso#7703]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/
2. Click on the (i) beside the 3GB Storage Space feature of the Personal Plan
3. Notice that videos and audio are listed, but a WordPress.com Premium or WordPress.com Business plan is required to upload video and audio.

#### Browser / OS version

Chrome 52 / Mac OS X 
Issue present in all browsers 

#### Screenshot

![pfibp4hhee-3000x3000](https://cloud.githubusercontent.com/assets/10882502/18058294/15ecbe2c-6dea-11e6-97df-5e515a22bcea.jpeg)

#### Context / Source

#user-report 
#457664-chat

**Comment by omarjackman** [comment]
I don't have the time to work on this right now but I thought I'd make who ever works on this life a bit easier. That text is at https://github.com/Automattic/wp-calypso/blob/master/client/lib/plans/constants.js#L468
