### ISSUE TITLE
Launchpad: Long domain URLs break the Celebrate Launch Modal input field

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#77032]
### Quick summary

Long URLs break the Celebrate Launch Modal input field and push the "View Site" link outside of the field.

<img width="669" alt="Screenshot 2023-05-17 at 17 27 55" src="https://github.com/Automattic/wp-calypso/assets/4933/e40b28d2-47e5-4110-8578-c85bdc0ab68c">

<img width="683" alt="Screenshot 2023-05-17 at 17 27 50" src="https://github.com/Automattic/wp-calypso/assets/4933/9ab8cf91-bc63-4838-93a3-565f7741a378">

Related to https://github.com/Automattic/wp-calypso/issues/76605

### Steps to reproduce

1. Do an onboarding flow (/start)
2. Use a long domain name and make it a subdomain of wordpress.com
3. Pick a plan with a free domain upgrade
4. Go all the way through to the launchpad and activate the site

### What you expected to happen

The modal should not get affected by a long URL.

### What actually happened

The "View Site" link went outside of the field and the modal got a horizontal scroll.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated just as described

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/98aa9108-3b92-42d5-b858-9c1890daabf7

📌 ACTIONS
- Assigned to @Automattic/lego

**Comment by taipeicoder** [comment]
Re-assigning to team Serenity who are better positioned for issues related to the Launchpad 🙂

**Comment by sixhours** [comment]
Confirmed this is still an issue:

<img width="679" alt="Screenshot 2023-08-15 at 2 37 37 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/0cb16bf7-c0dd-4f1f-8eb3-9e330f60ba47">
