### ISSUE TITLE
Rewrite @automattic/global-styles to align with Calypso's React 18 upgrade

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#77048]
Related issue: #77046

## Description

There is an ongoing effort to upgrade Calypso to React 18. WordPress packages will also be updated to the first version that supports React 18. As a result, the package `@automatic/global-styles` will be heavily affected since it has a lot of hard dependencies with WordPress packages, especially `@wordpress/edit-site`.

Please refer to this discussion for more context: p1684368118561169-slack-CRWCHQGUB

## Acceptance Criteria
- [x] Rewrite `@automattic/global-styles` using the WordPress packages updated in #77046.
- [x] (Optional) Avoid importing from the `build_module` path. Please make a separate issue if it's going to be a follow-up task.

**Comment by arthur791004** [comment]
Here are the functions we need to rewrite ([commit](https://github.com/Automattic/wp-calypso/pull/77046/commits/19f4a493055cb229eec5b3975ee81ed1531912ab)):

* GlobalStylesContext
* mergeBaseAndUserConfigs
* useSettings
* useStyle
* useGlobalStylesOutput

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/77319. Will draft a p2 to describe how it works!
