### ISSUE TITLE
Subscriptions email: table in post content is white-on-white

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#77065]
### Quick summary

The issue: when adding a Table block to a post and publishing the post, the table shows as white text and white border, on the white background of the new post email.

Reported by a user: https://wordpress.com/forums/topic/table-is-invisible-in-email-notification/?view=all
Replicated reliably by me.

### Steps to reproduce

1. Start at any wpcom Simple site (not tested with Atomic or self-hosted Jetpack sites yet but I'm pretty confident it's the same).
2. Ensure you're subscribed to receive posts by email
3. Create a new post and insert a Table block, with or without colour formatting via the block settings
4. Publish the post

### What you expected to happen

The table content that's within the post should be visible.

### What actually happened

Generally, it isn't visible.
Cases:

1. Default table block is white-on-white, fully invisible
2. Table block with inline text colour set on the text in cells will show that text colour. This is because it's inline CSS overriding the white-on-white.
3. Table block with text colour set in block settings is white-on-white and fully invisible
4. Table block with text and background colour set in block settings is white-on-light grey and very hard to see

How it looks in the editor:
<img width="935" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/89e2a8c8-18f0-4499-829f-dbcc12393367">

Here's a screenshot of the result from gmail:
<img width="814" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/900dae08-c55b-4980-a7bb-76603a6d64c7">

Yahoo mail is just the same, although the CSS looks a little different.

This is specifically coming from the styling of the subscriptions email; it looks like it's all done using tables. It seems like the white-on-white is a combination of the CSS for the table with the 'presentation' role for showing the email contents, and the fact that somewhere along the line the Table block CSS, which should be there thanks to the block settings in the editor, is being stripped out.

Here's where one of the cells inherits the white text colour:

<img width="984" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/60ff8476-1ec4-404e-980b-e2f34010b644">

This is the CSS it's inheriting from:

<img width="1354" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/9de2cbb8-dfe0-40a1-b8f4-88a93a599a71">

Meanwhile the block with a background colour that's green in the post is doing this instead:

<img width="1290" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/4c1a26c5-ef93-46b6-82b2-561f94be7e4b">

Just for reference, this is the code view of the markup for case 3 (table block settings used to set text colour):

```
<!-- wp:table {"style":{"border":{"width":"4px"}},"borderColor":"primary","textColor":"custom-color-2"} -->
<figure class="wp-block-table"><table class="has-custom-color-2-color has-text-color has-border-color has-primary-border-color" style="border-width:4px"><tbody><tr><td>col 1</td><td>col 2</td></tr><tr><td>col 3</td><td>col 4</td></tr></tbody></table></figure>
<!-- /wp:table -->
```

We can see the classes in there which define that there is a text (and border) colour. The class `.has-custom-color-2-color` should then define which colour I've selected for the text. None of that has come through in the email:

<img width="1313" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/32f563a5-8a8f-467e-accd-c24817277b91">

I think that about covers it. The Table block has some other weird behaviour going on with the border colour, but that's for a different bug report.
The only real workaround I can see is to apply inline colour or highlight to each individual cell, which is absolutely not practical as it has to be applied to each cell one at a time.

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Firefox 112.0.1
Mac OS 12.6
Also replicated in Apple's default Mail application, v 16.00

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – Yes with Jetpack connected

📌 FINDINGS/SCREENSHOTS/VIDEO
- Normal, unformatted table block appears with white text on white background in Post Notification emails. Same result with Simple, AT, and Jetpack-Connected Self Hosted site

#### Screenshots/Recordings

![Markup on 2023-05-18 at 15:44:08](https://github.com/Automattic/wp-calypso/assets/27249804/5264b9c1-8133-41f2-9070-bbc09f02b635)


📌 ACTIONS
- Assigned to @Automattic/apex

**Comment by synora** [comment]
We have a report of this in the forums at https://wordpress.com/forums/topic/text-not-displayed-correctly-e-mails/?view=all. The user discovered a workaround " by changing the font to a gray color (other than black). Then it is displayed correctly."

**Comment by TimBroddin** [comment]
A patch fixing this issue has been deployed: D112193-code
