### ISSUE TITLE
Hide "build" YouTube link on subscriber focused emails

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#77074]
Subscribers don't need to be advertised about website building, as they're _reading_, not building a website.

See code-D108842 where we removed this for one email, but there are more:
- [x] Confirm new subscription
- [x] New post
- [x] Review if there are other emails in [Figma](https://www.figma.com/file/X8eX0V9UNZ9CEgWcboHfnS/Receiving-Newsletter-emails?type=design&node-id=0-1&t=7TalpTB4uCijIB3b-0)

code-D108842 has testing instructions for emails, and pointers for code.

![Image](https://user-images.githubusercontent.com/87168/239177824-610da5b5-031b-4628-a14e-327d906f942d.png)

**Comment by lezama** [comment]
New post removed in code-D115136

**Comment by lezama** [comment]
I think we covered the most common ones, let's close until we find another one :)
