### ISSUE TITLE
Site Editor - Pattern Inserter - Performance issue rendering thousands of patterns

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#77129]
## What

- Keep an eye on the Gutenberg issue [Chrome crashes after opening a category with hundreds of patterns from the pattern inserter.](https://github.com/WordPress/gutenberg/issues/50695)
- Propose a fix

**Comment by annezazu** [comment]
The related issue that's linked here has been closed in Gutenberg: https://github.com/WordPress/gutenberg/issues/50695

As a result, I'm going to close this out. Feel free to reopen if that was incorrect.
