### ISSUE TITLE
Category Updates - Create a Home category with some professional looking layout for a traditional Homepage

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#77123]
## Description
The `Add a Page` modal is missing the `Home` categroy.

<img width="1366" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/9479517f-a46f-49d1-b216-eb0909040424">

See convo p1684305471176009-slack-C048CUFRGFQ

**Comment by autumnfjeld** [comment]
@migu Is it possible to add back the Home category rather than waiting for new layouts?  Using whatever was in the Home category before?   Oh, or maybe that it what you meant.

**Comment by miksansegundo** [comment]
Sorry, I missed this.

I remember that there were two patterns for mobile and one for web in that category, the mobile ones didn't meet the visual quality expectations and that's why Pablo suggested to remove them.

We can put the category back at any time after we curate a collection of `Home` page layout patterns.

During the last patterns and categories sprint, we didn't have time to work on adding page layout patterns from theme demo sites.

Let's discuss this issue with our designers. cc: @alaczek @taipeicoder

**Comment by autumnfjeld** [comment]
@taipeicoder  & @miksansegundo     NOT URGENT.

Can we use the patterns layouts from "Starter designs" in the Home category?   Pick a few of them?  Maybe Tanya can assist you.
<img width="1194" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/3630c152-aa15-4a40-a415-75a098c8154b">


I might be missing something (e.g. the technical implementation), but I see a lot of layouts there that could be used as home layouts.   Just an idea for a quick fix. ;)

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
