### ISSUE TITLE
Site Editor - Pattern Categories - Add a filter in Gutenberg to extend the order

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#77130]
## What

Add a new [filter](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-hooks/) to customize the order of categories and patterns in the editor.

The order of categories is alphabetical after https://github.com/WordPress/gutenberg/pull/53835 was merged.

### Category list in the pattern inserter
<img width="350" alt="Screenshot 2567-01-02 at 15 59 14" src="https://github.com/Automattic/wp-calypso/assets/1881481/3429f169-657e-42d3-9210-4a9dc4a11dbe">

### Category list in the patterns admin

<img width="351" alt="Screenshot 2567-01-02 at 15 59 30" src="https://github.com/Automattic/wp-calypso/assets/1881481/2bca91b5-18b4-4779-81fc-81ca045c9297">

## Why
Because different projects using the editor have different needs.

The editor doesn't allow extending the sorting in:

-  [usePatternsCategories](https://github.com/WordPress/gutenberg/blob/820b13599bf12f5efa472e36a780cd63e86a67b3/packages/block-editor/src/components/inserter/block-patterns-tab.js#L137) in inserter/block-patterns-tab.js
- [usePatternsCategories](https://github.com/WordPress/gutenberg/blob/2d43054e0343cfdc9c3ad9d055e8ba23d2979b34/packages/edit-site/src/components/sidebar-navigation-screen-patterns/use-pattern-categories.js#L85) in sidebar-navigation-screen-patterns/use-pattern-categories.js

## How

Adding [hooks/filters](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-hooks/) to customize the ordering will be useful for us in Dotcom and [others](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-hooks/) too.

**Comment by miksansegundo** [comment]
@richtabor what do you think about adding this feature in core? I can create issues and maybe a PR too. cc: @Automattic/lego

**Comment by richtabor** [comment]
What order would dotCom use that shouldn't be used outside of dotCom? I'm not particularly convinced reordering is a good  idea, but I may be convinced otherwise.

**Comment by miksansegundo** [comment]
Dotcom had the Featured category on top of the rest.

The alphabetical order works well, and I think that having the same order in Core and Dotcom is more user-friendly.

**Comment by richtabor** [comment]
Following up here a bit late, but what about if we get something like this in core, moving All, My Patterns and Featured into a group above the rest? Then everything below it is alphabetically ordered?

![CleanShot 2024-03-22 at 17 06 12](https://github.com/Automattic/wp-calypso/assets/1813435/143b2b22-e110-4852-9532-1cdd95cb3658)

**Comment by miksansegundo** [comment]
Looks good to me 👍

**Comment by richtabor** [comment]
@miksansegundo mind writing up an issue in Gutenberg to propose the changes?

**Comment by miksansegundo** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/60210
