### ISSUE TITLE
Signup: Proper copy for the Site Title step

### ISSUE THREAD

**Issue by bisko** [Automattic/wp-calypso#7716]
The Site Title step, which we are adding in #7386 needs proper labels and explanation texts. It would be good to go over the currently set ones, as they are probably not the best at explaining what a site title is and why do the user needs to fill it during Signup.

The current view for the step is: 
![27921344-6b7d-11e6-8595-aa9de20755e6](https://cloud.githubusercontent.com/assets/184938/18056712/be2332a8-6e15-11e6-8ded-a72159adaa95.png)

cc @shaunandrews

**Comment by shaunandrews** [comment]
I think "What is your site title?" is good.

For the description, maybe something like:

> Give your site a name. You can always change this later.

**Comment by meremagee** [comment]
@shaunandrews - thoughts?

Heading
> Give your new site a name.

Heading subtext/description
> Enter a Site Title that will be displayed for visitors. You can always change this later.

Image Help text
> Your Site Title is the name of your Blog or Website. It's often displayed at the top of your site.

Input placeholder
> Give your site a title

I tried to veer from "what is your site title?" because that could sound like it's asking for information that's been predetermined, like "what's your username?" or "what's your address?" whereas this is asking for them to create something new.

**Comment by shaunandrews** [comment]
I dig it.

**Comment by bisko** [comment]
Looks very good! 👍 

![screen shot 2016-09-02 at 10 57 49](https://cloud.githubusercontent.com/assets/184938/18196764/2a34c48c-70fc-11e6-9adc-a9ac1429ed4f.png)

**Comment by bisko** [comment]
The copy has been updated in #7386. If any further updates are needed, they should be added there.
