### ISSUE TITLE
Conversion: create/store discount code for "free plan" new user

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7717]
The discount code should be human-readable (i.e., avoid ambiguous characters), and we do not need to guarantee uniqueness-per-user. This code will be sent to the user in an email shortly after registration, and they can use this discount code to upgrade to a paid plan with X% discount off the  regular price.

We need to store this code somewhere with the site record, probably `site_meta`, so it can be used when the email is constructed and so it can be checked when the user checks out.

/cc @artpi @retrofox

**Comment by rralian** [comment]
One important point, this should be done as a 50/50 abtest for new users.

**Comment by apeatling** [comment]
Closed now in favour of working on value add.
