### ISSUE TITLE
Conversion: create new-user-discount email

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7718]
Using the discount code generated in #7717, send an email to the user 3 days after registration that explains the discount code and links to the `wordpress.com/plans/:site` page and asks them to pick a plan, then enter the discount code on the checkout page for a 20% discount.

Content will come from the marketing team.

/cc @retrofox @artpi

**Comment by dmsnell** [comment]
@rralian sounds like a good tie-in for a notification as well, no?

**Comment by rralian** [comment]
I think a notification would work as well, but we're tabling this for now.

**Comment by dmsnell** [comment]
Should we remove this from the milestone list then? Are there other tasks that are tabled?

**Comment by apeatling** [comment]
Tabling this in favour of a value add for new plans.
