### ISSUE TITLE
siteCreationStep sometimes return error with blog_name_exists

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#77197]
Sometimes when we are creating a new site leveraging the current `site-creation-step` it returns an error with `blog_name_exists` and blocked the flow. We need to double check why this is happening and see if there's a way to fix this. 

https://github.com/Automattic/wp-calypso/assets/4074459/d2da2711-8b04-445d-ace4-a56f5963fcef

**Comment by jeroenpf** [comment]
Are there steps I can take to consistently reproduce this error?

**Comment by ouikhuan** [comment]
> Are there steps I can take to consistently reproduce this error?

Unfortunately, I do not have a clue at the moment. Sometimes it works for me but sometimes it does not. The created site happens [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/site-creation-step/index.tsx#L126-L167). I can see the code has changed since last time I saw it. In my case, I do have lots of testing sites, I think this might be the reason. When it tried to create a new site but the blog name already existed in the previously created ones.

**Comment by jeroenpf** [comment]
@javierarce - In this instance, we concluded it would be good to have an error page when something goes wrong when we are trying to create a new (target) site for the user.

As described and shown in the video, when something goes wrong the page just hangs on the progress screen. We can redirect to an error page instead. 

We were thinking of having a message like: Something went wrong while setting up your new site, please try again or reach out to our support. Could you help us design an error page for this scenario?

**Comment by javierarce** [comment]
What do you think about [this idea](Zrk1NoQocqdk3uTphuuey4-fi-493_12299)?

The main button would retry the process, the link would allow contacting support, and the user could go back to the admin using the Back link on top of the screen.

![image](https://github.com/Automattic/wp-calypso/assets/4933/90efb7bc-c923-417c-9be4-2080eacfab3d)

**Comment by jeroenpf** [comment]
Looks great to me, thanks! I will go ahead and implement this.
