### ISSUE TITLE
Conversion: Enable new-user-discount code in checkout

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7719]
We need to enable the discount code from #7717 to give a 20% discount for wpcom plan sales for a given user. Upon submission, we must verify that the code matches the new-user-discount stored for the associated site in #7717. And we must verify that the time is no more than 7 days after site registration.

/cc @retrofox @artpi

**Comment by apeatling** [comment]
Closed now in favour of working on value add.
