### ISSUE TITLE
Flaky E2E: Login via popup to like the post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#77194]
### Spec file

specs/published-content/likes__post.ts

### TeamCity ID

10053907

### Logs

```
frame.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('a.like')
============================================================
at PublishedPostPage.likePost (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/published/published-post-page.ts:71:15)
    at /home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/published-content/likes__post.ts:100:5
    at Object.reloadAndRetry (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/element-helper.ts:126:11)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/published-content/likes__post.ts:98:4)
```

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/35c393d6-7dcb-4b1f-8f23-d112fd0bccd6)

**Comment by worldomonation** [comment]
Personally, I'm not sure of the usefulness of testing this particular flow (open post in logged out state, click on like post, log in, assert it's liked). It sounds like there was a regression in the past?

Do you have strong opinions on removing this test case and replacing it with a standard "log in, open a post, click like" @fullofcaffeine @WunderBart?

**Comment by WunderBart** [comment]
> Personally, I'm not sure of the usefulness of testing this particular flow (open post in logged out state, click on like post, log in, assert it's liked). 

I think this is a typical scenario for an E2E test and one that I'd vote to keep testing. Since we're exposing `Like` buttons to signed-out users, I think that's an important part of the liking flow to ensure is functional.

> It sounds like there was a regression in the past?

Not sure though which regression you mean. Could you provide more details?

**Comment by worldomonation** [comment]
> Not sure though which regression you mean. Could you provide more details?

Sorry, I should have been clearer.

I was referring to the following flow: the user liking a post while being logged out, logging in via the popup then confirming the like is present.

This flow sounded far too specific to be a result of an organic outgrowth. As this test case pre-dates my time at A8C, I can't be sure but my hunch is that there was once a regression where this flow broke, which is why it now exists.

In any case, I'll see if I can get a 100/100 clean iteration on AT sites of the scenario above in my PR.
