### ISSUE TITLE
[Bug] Launchpad: Edit design task should not appear for the Write flow (paid plan)

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#77207]
The Launchpad in the Write flow should only show the task `Write your first post`. But currently, when users select a paid plan, we also display the edit design task. This should be fixed.

**Current launchpad for paid plans:**
<img width="1438" alt="Screenshot 2023-05-22 at 11 49 58" src="https://github.com/Automattic/wp-calypso/assets/7931304/735a7252-1a94-45af-a500-0390dc0655a7">

**Correct launchpad should be:**

<img width="1438" alt="Screenshot 2023-05-22 at 11 50 20" src="https://github.com/Automattic/wp-calypso/assets/7931304/0ba46b96-ca65-4ab7-8bd6-23692d0fbb6d">

**Comment by sixhours** [comment]
<img width="448" alt="Screen Shot 2023-06-20 at 3 55 56 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/eea09c2f-ff86-45cb-9390-c7edaf164128">

It looks like this was fixed at some point. I selected a paid plan and checked out, and this is what I see when I land on the Launchpad in Stepper.
