### ISSUE TITLE
Newsletter onboarding: disable "continue" if site name isn't filled

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#77223]
In the newsletter onboarding we allow clicking "continue" even if title (which is mandatory) hasn't been filled:

<img src="https://github.com/Automattic/wp-calypso/assets/87168/4fbd354d-e3f7-43bd-b4d5-67c08c2300af" width="400"/>

Instead can we keep the continue disabled, and show a tooltip on hover that they need to fill site name? Flip side is that it could be confusing to know what they need to do to continue. @crisbusquets 

I can't find the link now but Pablo noted the feedback somewhere.

<img src="https://github.com/Automattic/wp-calypso/assets/87168/c1f98217-de35-43fb-9177-0cf12ed9a244" width="400"/>

**Comment by crisbusquets** [comment]
> I can't find the link now but Pablo noted the feedback somewhere.

[Here it is](HSljkKnYECEEegL3DqP2xC-fi-8527_85266) (first "Make it yours" screen).

It's probably not necessary, but just in case: I added the [design here](HSljkKnYECEEegL3DqP2xC-fi-8780_86693).

![newsletter-setup-default-desktop-disabled](https://github.com/Automattic/wp-calypso/assets/25607244/d61b5952-3215-494e-b5bb-886639551f68)
