### ISSUE TITLE
Subscription Management: Add paid subscriptions information on the individual site subscription page.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#77233]
Add paid subscriptions information on the individual site subscription page.

<img width="753" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/934d21d1-6484-405f-b728-3331c53d6b40">

**Comment by JuanLucha** [comment]
Payment details will be parked for later as we are unable to retrieve payment information.
Plan and billing period will be in.
