### ISSUE TITLE
Newsletter onboarding: add separate "skip" to subscriber step

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#77247]
Instead of combined skip/continue CTA, add a separate skip below the main CTA.

![Image](https://user-images.githubusercontent.com/87168/240189456-d2455427-2635-476b-9b85-d2afc4c70323.png)

Mindful that the same form is inside product (Users->Subscribers->Add) and we don't want the skip there.

FYI @crisbusquets

**Comment by crisbusquets** [comment]
[Design here](HSljkKnYECEEegL3DqP2xC-fi-8533_98450) :)

* Text: `Skip for now`

![newsletter-setup-subscribers-desktop](https://github.com/Automattic/wp-calypso/assets/25607244/69c8e62f-af96-4fc2-9c75-486b09e69ff5)

**Comment by simison** [comment]
Thanks, I was wondering about link colour so good to see it here. :-)
