### ISSUE TITLE
Launchpad: Create a new helper/API to complete the tasks

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#77278]
Dale expressed some concerns surrounding the `add_listener_callback` listener used to mark the task as completed. More details here: p1683832565574479-slack-C0Q664T29.

Currently, the `add_listener_callback` is used as follows:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Qzh%2Qjcpbz%2Qcyhtva%2Sfgntvat%2Siraqbe%2Snhgbznggvp%2Swrgcnpx%2Qzh%2Qjcpbz%2Sfep%2Ssrngherf%2Synhapucnq%2Synhapucnq.cuc%3Se%3Q8s5012q9%2361-og

We should add a new `wpcom_mark_launchpad_task_complete` helper/API to hook directly to the underlying event that will mark the task as completed. We should also deprecate the existing listener callback.

Depends on:
* https://github.com/Automattic/wp-calypso/issues/77275

**Comment by sixhours** [comment]
This was shipped in #31121
