### ISSUE TITLE
Align styles and designs for the new Launchpad component

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#77285]
Align styles and layout for Launchpad component with the initial design, including mobile.

We may not be using the same [checklist-style design for every context,](p9Jlb4-7vh-p2) but that’s still up in the air. For now, we can implement this checklist-style design, and maybe add other components as the concept solidifies and expands to other areas of Calypso.

Related to https://github.com/Automattic/wp-calypso/issues/77284 https://github.com/Automattic/wp-calypso/issues/77283

**Comment by sixhours** [comment]
This was closed in the above PRs.
