### ISSUE TITLE
Launchpad: Create "Edit home page design" task

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#77292]
The task to edit the design is already created. But we will still need to add the task to the "Keep building" task list once we have it.

The task is defined here:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Qzh%2Qjcpbz%2Qcyhtva%2Sfgntvat%2Siraqbe%2Snhgbznggvp%2Swrgcnpx%2Qzh%2Qjcpbz%2Sfep%2Ssrngherf%2Synhapucnq%2Synhapucnq.cuc%3Se%3Q8s5012q9%23171-og

**Comment by sixhours** [comment]
This task is the same as the one currently included in Stepper, and it was added to the new "Keep Building" task list in https://github.com/Automattic/jetpack/pull/30954/files#diff-7a7ab71e45292d18195f8de5e1f0338aa5232291425fa0bbe9a21afa65bca23fR429 

~~It's unclear to me whether we should still show the task if the user completed it prior to launch. Do we want to show it but marked as completed, or hide it entirely? What do you think @nuriapenya ?~~

Nevermind, found the answer. :) We should hide the task entirely for Build sites if it's already been done prior to launch.

**Comment by nuriapenya** [comment]
@sixhours, @valterlorran 

I guess this task refers to the `Edit site's design` (Task ID: design_edited/site_edited) in the spreadsheet, right? 

If so, the idea is to display it **if users didn't complete it during onboarding**. Currently, users on the Build flow can launch their sites without completing all the tasks. For those cases, it would be good to display this task again.

What do you think? Does it make sense?
