### ISSUE TITLE
Premium Theme Unlock Modal: remove theme features and update  premium feature list

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#77299]
# Description

Here is the current modal:

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/3a212564-97b9-4629-b272-720e2278975f)

Remove the theme feature pill section from the Premium Theme Unlock Modal and  update the list on the right side to be the same as this GS modal:

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/8455a8b3-5116-401e-ad4e-64787de7df68)

From: [🎨 [Needs Design] Premium Theme Unlock Modal features incorrect tags](https://github.com/Automattic/dotcom-forge/issues/2413#top)

@Automattic/lego

**Comment by autumnfjeld** [comment]
@taipeicoder  could this be squeezed into the current sprint?  I believe it is a tiny task.

**Comment by taipeicoder** [comment]
The GS modal only covers Premium themes, while the Premium unlock modal can also cover Business themes (WooCommece themes). Should we show the same list? @autumnfjeld 
![Screenshot 2023-05-26 at 10 08 30 AM](https://github.com/Automattic/wp-calypso/assets/797888/34f0f183-ae5c-42e3-a8c4-2515233e2aca)

**Comment by autumnfjeld** [comment]
This is plan details for the GS modal:
<img width="210" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/dab8ff9d-474e-4abf-9bb2-6f058bc51d9b">

Could we have two sections one for Premium and one for business?

You might be able to determine content by looking at the pricing page https://wordpress.com/pricing/.  @lucasmendes-design will definitely be able to help here,  as he has recently worked on pricing things. 💰

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/78043
