### ISSUE TITLE
Add Support Link to Block Descriptions for Time to Read Block

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#77308]
### What

Similar to #67293, #62284 and #56091 , let's add the documentation link to the Time to Read block.

### Why

This will help WordPress.com users easily discover our comprehensive resources on how to use each block in the editor. With these support docs, users can learn about blocks more quickly, figure out the settings themselves, and reduce their likelihood of contacting support for basic editing tasks.

### How

The majority of blocks have a Learn More link to a support doc, such as this example:

![image](https://user-images.githubusercontent.com/30727666/188034347-d0bcdfbe-f1f6-45e1-8a29-751f2c798a82.png)

Let's add the newly-published support doc for the Time to Read block: https://wordpress.com/support/site-editing/theme-blocks/time-to-read-block

<img width="328" alt="Screenshot 2023-05-24 at 5 20 22 pm" src="https://github.com/Automattic/wp-calypso/assets/30727666/6bc0e115-fd50-4e37-a45e-dd058745e5be">

cc @escapemanuele

**Comment by escapemanuele** [comment]
Hey @donalirl, this task has been completed 👍

**Comment by donalirl** [comment]
Thank you so much @escapemanuele ! Will the translated version appear to non-English users automatically when it's ready? The translations haven't been completed yet.

**Comment by escapemanuele** [comment]
Yes @donalirl, it should work automatically 👍
