### ISSUE TITLE
Reader: Some posts are returned out of order from the REST API

### ISSUE THREAD

**Issue by aerych** [Automattic/wp-calypso#7731]
#### Steps to reproduce
1. Go to the REST API console and search the `/v1.2/read/tags/%@/posts` endpoint.  
2. Specify a date for "before" and specify results should be in descending order.
3. Try this with various tags e.g. Japan, Apple, Coffee, Books.
4. Inspect the search results and not the dates.  Posts are expected to be sorted desc by date, however some posts are being returned out of order, and some posts are outside the specified `date_range` field returned by the results. 
5. You might need to page a few times to see this in action. 

#### What I expected
Results should *always* be returned in descending order when order=DESC.
Results should *always* be within the specified date_range. 

#### What happened instead
Some posts were out of order.  This is causing some issues in the mobile clients where it is expected that posts will be returned in descending order.

Here's an example response demonstrating the issue.  The request to reproduce is:
`/v1.2/read/tags/japan/posts?locale=en&before=2016-08-29T06:36:42Z&number=40&order=DESC`
Notice that the date for the 29th item (28th index) is `"date": "2000-11-22T01:11:37+00:00"`
[read-tags-japan-posts.json.zip](https://github.com/Automattic/wp-calypso/files/443571/read-tags-japan-posts.json.zip)

**Comment by blowery** [comment]
This is likely because the posts are ordered by the date they were tagged, not by the publish or update date. You need to use the `tagged_on` field in each post to order the posts. See https://public-api.wordpress.com/rest/v1.2/read/tags/brownie/posts?fields=ID,title,URL,date,tagged_on

**Comment by nbradbury** [comment]
@blowery Have tag streams always been sorted by tagged date? This is the first I've heard of it.

**Comment by bluefuton** [comment]
Related: @nbradbury noticed that order param has no effect (i.e. `order=ASC` didn't work). Prepping a patch for that now.

**Comment by blowery** [comment]
@nbradbury yup. it's been that way as far back as I have brains.

**Comment by lancewillett** [comment]
Looks to be addressed by https://github.com/wordpress-mobile/WordPress-Android/pull/4527

**Comment by aerych** [comment]
> yup. it's been that way as far back as I have brains.

Added 2015.08.25 in 123147  for the v1.2 endpoints.  I guess we just missed that update in the apps, or we just haven't noticed the difference after switching the apps from the v1.1 endpoints. :(  
Sorry for the noise.
