### ISSUE TITLE
Subscription Management: Individual site subscription page should support subscription id & blog hostname as route.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#77312]
The individual site subscription page should support subscription id and blog hostname as route.

I'd like to propose the following format:
- /subscriptions/site/site_id (int)
- /subscriptions/site/hostname (string)
- /subscriptions/site/?sub=subscription_id

For the 2nd scenario `/subscriptions/site/hostname`, this is user-friendliness, and also the same is also being practiced on the reader's url `/following/manage/?s=your_hostname_here`.

For the 3rd scenario `/subscriptions/site/?sub=subscription_id`, this is for situations where the subscription no longer exists (but we'll make a API request anyway to make sure that it is really not there anymore). And the page should just show that the subscription no longer exists. See context: D111719-code (redirection loop)

See also: Locale considerations. https://github.com/Automattic/wp-calypso/issues/77315

**Comment by ivan-ottinger** [comment]
> For the 3rd scenario /subscriptions/site/?sub=subscription_id, this is for situations where the subscription no longer exists (but we'll make a API request anyway to make sure that it is really not there anymore). And the page should just show that the subscription no longer exists. See context: D111719-code (redirection loop)

If I understand correctly, this is the situation you are referring to:

1. The user unsubscribes by clicking on the "Unsubscribe" link in the email and then "Cancel subscription" button.
2. Later, they click the link in the email again to confirm they were unsubscribed. This time, they are redirected to `/subscriptions/site/?sub=subscription_id` where they will see a message the subscription no longer exists.

Is that right?

In that case, shouldn't the frontend be able to display the same message even when the URL was still `/subscriptions/site/hostname` or `/subscriptions/site/site_id`? 🤔

**Comment by yansern** [comment]
> If I understand correctly, this is the situation you are referring to:
> 
> 1. The user unsubscribes by clicking on the "Unsubscribe" link in the email and then "Cancel subscription" button.
> 2. Later, they click the link in the email again to confirm they were unsubscribed. This time, they are redirected to `/subscriptions/site/?sub=subscription_id` where they will see a message the subscription no longer exists.
> 
> Is that right?

Yes, that is right.

> In that case, shouldn't the frontend be able to display the same message even when the URL was still `/subscriptions/site/hostname` or `/subscriptions/site/site_id`? 🤔

That's because the existing unsubscribe link is a `b=` param contains only the subscription id (see also `get_unsubscribe_url()` for how the encrypted `b=` param is generated). So once the user unsubscribes, there is no way to look up information on blog id or blog hostname anymore.

**Comment by ivan-ottinger** [comment]
> That's because the existing unsubscribe link is a b= param contains only the subscription id (see also get_unsubscribe_url() for how the encrypted b= param is generated). So once the user unsubscribes, there is no way to look up information on blog id or blog hostname anymore.

I see. That makes sense now. Thank you for clarifying.

Depending on when we get to this task, we could also consider replacing that link in the email template completely. This, I believe, should prevent us from running into this issue because we will be able to get the blog ID / hostname at the time when the email is generated.

This way, we should be alright with skipping the `/subscriptions/site/?sub=subscription_id` option. At least that's what I believe with the current perspective.

**Comment by yansern** [comment]
> I see. That makes sense now. Thank you for clarifying.
> 
> Depending on when we get to this task, we could also consider replacing that link in the email template completely. This, I believe, should prevent us from running into this issue because we will be able to get the blog ID / hostname at the time when the email is generated.
> 
> This way, we should be alright with skipping the `/subscriptions/site/?sub=subscription_id` option. At least that's what I believe with the current perspective.

This task can be a little complicated because we need to register the subkey cookie and then decrypt the params. (And I'm not sure if there are any bump_stats along the way other than the one for email click).

To question whether both operations can be migrated to Calypso:
 - Registering the subkey cookie likely can be done on Express for the wordpress.com domain.
 - Decrypting params likely requires an API call.
   - If it does need an API call, it would be easier to have the unsubscribe URL hit the WPCOM server before redirecting to Calypso.
   - If we do not rely on an API call, it means we need to see how we can decrypt this on Calpyso.
     - We need to check whether the encryption scheme be can ported to JS.
     - We need to find out how we can store and retrieve this encryption key to decrypt the params.
       - We need to store the encryption key, encrypted, on this open source repo. (At least we know there's an existing practice, drawing examples on how E2E configs are encrypted on this repo.)
      - However, decrypting on Calypso is only useful if the old unsubscribe link is goes through nginx url rewrite instead of wpcom redirect.
        - If it still need to hit the WPCOM server, might as well do the decryption there and redirect to Calypso.
  - We can decide to deprecate the encrypted params moving forward if we decide to introduce new unsubscribe links, but to support links from older emails, the decryption logic still needs to be in somehow.

What could be worth looking into is still keeping the wpcom redirection but just untangle the logic from the V1 class. And we can simplify it to just redirect to say `/subscriptions/site/invalid` when the subcription is invalid.

If we deprecate the encrypted params, we can update the unsubscribe link on new emails moving forward to go directly to Calypso. Old unsubscribe links can still go through redirection before landing in Calypso.

**Comment by ivan-ottinger** [comment]
Good points. I didn't think about the cookies at all to be honest.

> What could be worth looking into is still keeping the wpcom redirection but just untangle the logic from the V1 class. And we can simplify it to just redirect to say /subscriptions/site/invalid when the subcription is invalid.

Yes, this looks more clean to me than using `/subscriptions/site/?sub=subscription_id`.

**Comment by yansern** [comment]
Dropping this due to complexity.
