### ISSUE TITLE
Subscription Management: Add Manage purchase button on individual site subscription page.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#77335]
When clicking on the "Manage purchase" button, it should go to `/me/purchases/other/<payment_or_plan_or_order_subscription_id>`.

The API for individual subscription detail needs to be updated `payment_or_plan_or_order_subscription_id` (to be confirmed what it is actually called).

<img width="591" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/333a750f-9f6b-40d1-93a8-3b5c6bf95891">

**Comment by RT-1904129** [comment]
Hi @yansern 
Can you please assign me this task?I have relevant experience in this I will contribute and complete this task
Thanks & Regards
Rishabh Tripathi

**Comment by yansern** [comment]
@JuanLucha When working on this issue, could you kindly also just update the Cancel Subscription button to grey? Thanks. https://github.com/Automattic/wp-calypso/issues/77394
