### ISSUE TITLE
Launchpad: Consider storing individual task statuses

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#77331]
We should explore the suggestion of storing individual task statuses instead of having a single site option(launchpad_checklist_tasks_statuses) with all the tasks and their statuses. Maybe we should have something similar to `launchpad_task_status_{$task_name}`.

Here's where we define the option:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Qzh%2Qjcpbz%2Qcyhtva%2Sfgntvat%2Siraqbe%2Snhgbznggvp%2Swrgcnpx%2Qzh%2Qjcpbz%2Sfep%2Ssrngherf%2Synhapucnq%2Spynff%2Qynhapucnq%2Qgnfx%2Qyvfgf.cuc%3Se%3Q8s5012q9%23419-og

**Comment by valterlorran** [comment]
Started a discussion about this topic here: paYKcK-322-p2

**Comment by sixhours** [comment]
I think we decided not to go this direction based on Valter's research and feedback. Marking as closed.
