### ISSUE TITLE
Launchpad: Alternate between the Setup Checklist and the Launchpad

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#77330]
We need to be able to display the Launchpad at the Customer's Home and hide the Setup checklist.

This depends on `is_enabled` flag at the task list level logic for showing cards on a per-card basis -- it's either a callback or a massive switch statement

Depends on:
 * https://github.com/Automattic/wp-calypso/issues/77270

**Comment by sixhours** [comment]
This was closed in https://github.com/Automattic/wp-calypso/pull/77830
