### ISSUE TITLE
Subscription Management: Show X icon on New Posts column when no notification settings are set.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#77336]
Under the New Posts column, when no notification settings are set, it should show an X icon.

<img width="1053" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/39b1df34-6e7e-4a82-bb49-761d739acb65">

**Comment by simison** [comment]
Isn't there _always_ a default state, or how does subscription end up in this way?

**Comment by mashikag** [comment]
> Isn't there always a default state, or how does subscription end up in this way?

Yes, this is quite strange, I agree. But once a WPCOM user is a subscriber to a site, they may "pause" their email, and mobile notifications. This means that they are only a subscriber on paper then, because they will receive no notifications of new content on the site.
