### ISSUE TITLE
Reader: post date not updating along with changed post date in post editor

### ISSUE THREAD

**Issue by gracie** [Automattic/wp-calypso#7734]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts
2. Edit an existing post that's a few days old, and update its published date.
3. Return to https://wordpress.com to view the post in the Reader. It will continue to display the original published date and be buried in the feed.
4. Clear the cache for the reader and the post. It will continue to display in the reader with the original published date.

#### What I expected
The post would display the new published date in the Reader, especially after clearing cache.

#### What happened instead
The reader did not update.

#### Browser / OS version
Mac OSX El Capitan 10.11.6 / Chrome 52.0.2743.

#### Screenshot / Video
Date in post:
https://cloudup.com/cN_e8jmCLvI

Date in Reader: 
https://cloudup.com/c1Fn7Fz4_tC

#### Context / Source

#user-report

**Comment by bluefuton** [comment]
@gracie Thanks for reporting this! We currently honour the original posting date in the Reader, which prevents users from repeatedly updating the post to bump it up in others' streams. No plans to change this at the moment.
