### ISSUE TITLE
Stats: Use regex for prefix replacements on child URLs

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#77358]
I'm actually fine with Jason's approach as replace would only replace the first occurrence and all children are prefixed with that. However theoretically yours is safer, I'll go ahead and merge and let's see if we need to do that later.

_Originally posted by @kangzj in https://github.com/Automattic/wp-calypso/pull/76923#discussion_r1204841774_

**Comment by kangzj** [comment]
Feel free to close if you think it's not necessary.

**Comment by jsnmoon** [comment]
This is a reasonable enhancement. For the record, the enhancement is originally mentioned [here](https://github.com/Automattic/wp-calypso/pull/76923#discussion_r1193410517) and looks like the following:

```diff
-					parsed.label = child.name?.replace( item.name, '' ) || '/';
+					const regex = new RegExp( `^${ item.name }` );
+					parsed.label = child.name?.replace( regex, '' ) || '/';
```
