### ISSUE TITLE
Minor UI issues in WooCommerce.com account steps

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#77361]
Reported in p1684847021274329-slack-C01SFMVEYAK

1. Icon used in NUX account step errors is "info" icon, not exclamation mark

![Image](https://user-images.githubusercontent.com/3747241/240793199-38cb2b26-99c0-4821-a139-e97b72e97357.png)

2. Red button highlight when hovering `Get started` button in signup page

![Image](https://user-images.githubusercontent.com/3747241/240793369-50a624c9-fd60-4931-9570-89f7645cfb63.png)

### To reproduce

1. In an incognito browser tab, go to https://woocommerce.com/start
2. Type in an invalid email in the email address field, such as `sasdqw`
3. Observe the icon on warning is "info" icon
4. Fill in a valid email, username, and password
5. Hover over `Get started` button
6. Observe the red color background on hovering

### Acceptance criteria

1. Change the error icon to exclamation mark
7. Hovering `Get started` button should show the same purple color

**Comment by worldomonation** [comment]
Hi! Do you have steps to reproduce and the locations where this occurs? 

I'm trying to triage this issue but not familiar with the WooCommerce.com account side of things.

Also, for future reference, it is preferable to file one issue per problem. That way each issue is dedicated to one problem and a descriptive title can be given.

**Comment by ilyasfoo** [comment]
@worldomonation Apologies for not being vague on this issue. I've updated the testing instructions, but Ghidorah team will be handling it soon so you won't need to triage it 🙏

**Comment by cuemarie** [comment]
Thanks for the heads up @ilyasfoo ! I've moved this to our 'Other' column since you've got a team that will take on triaging it from here 👍

**Comment by adrianduffell** [comment]
@ilyasfoo do we have an exclamation icon that can be dropped in place?

**Comment by ilyasfoo** [comment]
Good question, @adrianduffell! I think we can use `gridicons-notice-outline` from [GridIcons](https://automattic.github.io/gridicons/). AFAIK, we can pass the component to `FormInputValidation` component. 

(Figma: 4ixWMlzrxllx93tSFsCW6k-fi-3947_59220)

**Comment by adrianduffell** [comment]
This is now addressed with https://github.com/Automattic/wp-calypso/pull/90359
