### ISSUE TITLE
`/subscriptions/site/:blogId`: Fix "Cancel subscription" button styling

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#77394]
The goal of this task is to apply correct styling to the "Cancel subscription" button.

Currently, the button looks as follows:

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/09656c3d-7c0b-493b-8195-0b29bf9913f0)

Instead it should match the design (inDLaEQV8jJ21O4WXawIsJ-fi-712_30652):

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/5d698fa9-1fdc-45d8-ac9b-5bc8447bd82d)

**Comment by yansern** [comment]
This issue will be worked on as part of https://github.com/Automattic/wp-calypso/issues/77335.

**Comment by yansern** [comment]
Completed as part of https://github.com/Automattic/wp-calypso/issues/77335
