### ISSUE TITLE
Contact forms with multiple SEND TO addresses generate emails with duplicate Sender headers, against compliance 

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#77409]
### Quick summary

When a Jetpack Contact Form has multiple email addresses set in the `EMAIL ADDRESS TO SEND TO` field, the email sent to those addresses upon submission contains multiple `Sender:` header fields. 

Email providers like Gmail are thus blocking these emails, with the following response:

```
550-5.7.1 This message is not RFC 5322 compliant. There are multiple Sender 550-5.7.1 headers.
```

- Google's guide on the issue: 550 5.7.1 https://support.google.com/mail/?p=RfcMessageNonCompliant

This leads to a temporary block from our servers to avoid bounces, which will eventually bring the user to WordPress.com Support for help resolving.

### Context

See p1685040020606629/1685037157.834549-slack-C0299DMPG thread for troubleshooting with Jetpack and Reactor folks from earlier today.

### Steps to reproduce

1. On an Atomic test site, create a contact form with 2 email addresses in the EMAIL ADDRESS TO SEND TO field
2. Publish, and view the page
3. Submit through the contact form
4. Locate the email you receive on this, and `View Original` / `View Raw Email`, etc.
5. Search for `Sender:`

### What you expected to happen

One `Sender:` header on the email that's sent out.

### What actually happened

Multiple `Sender:` headers can be found, along with a warning about the Duplicate "Sender" header field:

![241047533-66da9e69-5cc4-4b8b-87bc-2c0295432f73](https://github.com/Automattic/wp-calypso/assets/27249804/a1326d77-e280-436d-b75b-a31e8b14695a)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Workaround

Set the contact form to only send to 1 email address for the time being, and likely ask Atomic to remove the temporary block.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Added to Other
- Attn: @Automattic/reactor

**Comment by cuemarie** [comment]
Interactions:

- 6329933-zd-woothemes with me
- 6330440-zd-woothemes with @masperber 

@jp-imagines also ran into this with a customer using Elementor forms here: 6313398-zd-woothemes , so perhaps there's been an update to how Gmail and other mail servers look for this?

**Comment by jp-imagines** [comment]
> @jp-imagines also ran into this with a customer using Elementor forms here: 6313398-zd-woothemes , so perhaps there's been an update to how Gmail and other mail servers look for this?

From what I recall, this user's form was only set to send to _one_ recipient, which is contrary to the findings from the other cases we investigated. I don't know if their form being built in Elementor changes anything though.

**Comment by renata-franco** [comment]
Hi @cuemarie and @jp-imagines. I was wondering if there is any update or workaround on this? I got a ticket open that has been waiting for a while for a response: #6330493-zen

**Comment by cuemarie** [comment]
Hey @renata-franco ! No updates to share yet.  

@RafaelFunchal Do you remember this one from a few weeks back (p1685035723335969-slack-C03TY6J1A)? This is about where it ended that day: p1685042616468149/1685037157.834549-slack-C0299DMPG 

Anything I can do to help Reactor look into this further?

**Comment by RafaelFunchal** [comment]
@cuemarie , this seems to be something that must be fixed on how the Atomic platform sanitizes the TO field. @jmdodd should we move this issue to another repo?

**Comment by RafaelFunchal** [comment]
After talking to Jennifer, I'm moving this issue to p9F6qB-csB-p2 to let AT Developers check it out.

**Comment by cuemarie** [comment]
Thank you @RafaelFunchal for your help escalating this to the right place!

**Comment by RafaelFunchal** [comment]
You're welcome :)

**Comment by RafaelFunchal** [comment]
Using more than one email address should work now :)

> I’ve looked around and didn’t notice any exact place that would _require_ that header. It helps with getting the bounces to the correct place, but it should work without it. I’ve disabled the Sender header for now and it should work.
>
> If you notice anything broken due to that – let me know.
> -- p9F6qB-csB-p2#comment-53894

**Comment by cuemarie** [comment]
Awesome, thanks @RafaelFunchal !
