### ISSUE TITLE
Feature Request: Upload and replace plugin from Calypso (default view)

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#77417]
### What

I want to request a feature to upload and replace an existing plugin on the Calypso upload plugin screen, similar to the WP-Admin behavior.

### Why

This will make replacing an outdated plugin much easier when manually uploading them from the plugins upload screen in Calypso.

**Comment by john-legg** [comment]
📌 ACTIONS

Feature request kept

**Comment by cpapazoglou** [comment]
Closing this, as it doesn't fall in into the guiding principles of untangling Calypso  fsHM7-p2
