### ISSUE TITLE
Stats: Add weekly highlights period toggle panel

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#77425]
Add support to the period (`7 days` and `30 days`) change for the highlights section of the `Traffic` page.

- [x] Apply highlights API for data.
( https://github.com/Automattic/wp-calypso/pull/77500 )
- [x] Store highlights settings with API.
( https://github.com/Automattic/wp-calypso/pull/77806 )

<img width="962" alt="截圖 2023-05-26 下午4 35 56" src="https://github.com/Automattic/wp-calypso/assets/6869813/1f1a76c3-150b-4e15-9096-e7fce5a2f99f">

Project discussion: p1HpG7-lZo-p2

**Comment by kangzj** [comment]
API implementation: D112152-code

**Comment by kangzj** [comment]
API to support different periods: D112152-code
