### ISSUE TITLE
Hide auto-loading tag everywhere

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#77423]
# Description
We cannot remove the `auto-loading-homepage` tag at the root of theme taonomy, but we do need to make sure users never see this as it is meaningless to a user.

[Review of Feature Filters in the Theme Showcase] pekYwv-1HP-p2 
pekYwv-1HP-p2#comment-1257

![image](https://github.com/Automattic/wp-calypso/assets/5665959/8ff10be1-5196-4ea5-9555-d9fb19017bf0)

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/0d7108ec-1744-4248-be95-4b629f2f7f23)

Related to [Premium Theme Unlock Modal: remove theme features and update premium feature list](https://github.com/Automattic/wp-calypso/issues/77299)

cc: @taipeicoder  Not urgent

**Comment by RT-1904129** [comment]
Hi @autumnfjeld 
Can you please assign me this task? I have relevant experience in this I will contribute and complete this task
Thanks & Regards
Rishabh Tripathi

**Comment by autumnfjeld** [comment]
Hi there @RT-1904129  Thank you for reaching out.  This task is already assigned.   Every task on the Team Lego board is already accounted for.   
<img width="336" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/7cb541ce-c977-467a-ba61-ebc0f866d62e">


I'd suggest contributing in these repos:
*  https://github.com/WordPress/gutenberg
* https://github.com/WordPress/WordPress

**Comment by taipeicoder** [comment]
Closing via D112805-code. Announcement: pekYwv-1HP-p2#comment-1381
