### ISSUE TITLE
Plans: personal plan does not include audio/video

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7744]
We need to edit the info-popover description for storage for the personal plan. It does not include audio/video. This is only in the calypso version of the plans page. The homepage, pricing, and SEM landing pages are correct.

![audio video in personal plan](https://cloudup.com/cb1-WA1yy6D+)

**Comment by rwaynick** [comment]
I also reported the issue in #7703. Feel free to close that other one since this resolves it. Thanks.

**Comment by chaitanyamsv** [comment]
@retrofox 
I am confused as this issue is fixed, but I still see audio and video files mentioned in Calypso Plans page: https://cloudup.com/cSjy8GBt2VP

Can you please double-check? Thank you :)

**Comment by retrofox** [comment]
Hi @chaitanyamsv, I think you;re right. In some way we've reverted the fix. 🤦‍♂️ 
I'll re-open it.

**Comment by retrofox** [comment]
Actually let me research about this item since also we've changed the storage from `3GB` to `6GB` so maybe now we are offering the storage also for audio/vide again.

**Comment by KokkieH** [comment]
Adding Video would probably require having to include VideoPress as well, but it would be nice if we can add Audio at least along with the increased storage in Personal.

**Comment by KokkieH** [comment]
The popover on the plans page no longer mentions video uploads, and the plan does include audio, so I'm going to close this.

![plans_ _kokkiestrialtestsite_ _wordpress_com](https://user-images.githubusercontent.com/11873759/34819894-b54142c4-f6c7-11e7-9e7f-ee7f06880d00.png)
