### ISSUE TITLE
Plans 2023 (NPM essential): Refactor the plan highlighting hooks to integrate and sync their logic better

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#77450]
In https://github.com/Automattic/wp-calypso/pull/77441 we shipped some changes to fix the "suggested" column highlights. However, the conditioning happing in the "useHighlightLabel" and "useHighlightAdjacencyMatrix" hooks has now diverged (e.g. the former checks whether a plan is available for purchase, and the latter doesn't). 

These two hooks should sync, otherwise, it can lead to edge cases with breakage - for example, the rounded borders are not being updated properly in some cases (see some relevant discussion [here](https://github.com/Automattic/wp-calypso/pull/77441#discussion_r1206800405)):

<img width="500" alt="Screenshot 2023-05-26 at 4 47 36 PM" src="https://github.com/Automattic/wp-calypso/assets/1705499/3ef9a9c6-eeef-4e93-bdfe-16ff99057b42">

Not the first time this scenario bites. Having two hooks that repeat some logic and are seldom used separately may not be ideal. So there's room for some interesting refactor to happen.

**Comment by RT-1904129** [comment]
Hi @chriskmnds 
Can you please assign me this task?I have relevant experience in this I will contribute and complete this task
Thanks & Regards
Rishabh Tripathi

**Comment by chriskmnds** [comment]
> Hi @chriskmnds Can you please assign me this task?I have relevant experience in this I will contribute and complete this task Thanks & Regards Rishabh Tripathi

Hey @RT-1904129 . Please feel free to take a stab if you like. We will be returning to the issue in a couple of days to prioritize, so if you have something by then, then happy to review it. 🙌

**Comment by chriskmnds** [comment]
`NPM essential` primarily due to the amount of refactoring needed to pull this through (that feeds into other issues to be worked on top).
