### ISSUE TITLE
Unable to install plugins/themes via the Calypso plugin page

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#77461]
### Quick summary

When trying to install a plugin via the Calypso Add New plugin page(https://wordpress.com/plugins/{YOUR_SITE_URL}), the user is redirected to a white screen, and the plugin never gets installed.

### Workaround

The workaround is to navigate to the WordPress dashboard using the link `https://{YOUR_SITE_URL}/wp-admin/plugin-install.php` and install the plugin from there.

### Steps to reproduce

1. Navigate to the `Plugins > Add New` page. 
2. Search for a plugin and click on the plugin name to visit the plugin details page
3. Click the Install and Activate button.

### What you expected to happen

Plugins should start installing, and we should see some indication(loader, progress bar, etc.) that the plugin is being installed.

### What actually happened

We are redirected to a page, and the page is blank. There is no indication. Besides, even if stay there for a while and get back to your `Plugins > Installed Plugins` page, you will notice that the plugin is not installed.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

Slack: p1685168487441229-slack-C02FMH4G8

**Comment by dev-sabbir** [comment]
Encountered here: 6335308-zd-woothemes

**Comment by kavyagokul** [comment]
Encountered in 
- 6335796-zen
- 6335748-zen

**Comment by kavyagokul** [comment]
Tested and reproduced on a test site as well. This is the error that shows up in the console

```
TypeError: i is undefined
    w https://wordpress.com/calypso/evergreen/marketplace.23f8a5b657c3c0209fc1.min.js:1
    n https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    i https://wordpress.com/calypso/evergreen/84577.01184962beac0a646ce9.min.js:1
    V https://wordpress.com/calypso/evergreen/marketplace.23f8a5b657c3c0209fc1.min.js:1
    u https://wordpress.com/calypso/evergreen/30605.ff958a97a9bb81cd7570.min.js:2
    K https://wordpress.com/calypso/evergreen/30605.ff958a97a9bb81cd7570.min.js:2
    ws https://wordpress.com/calypso/evergreen/marketplace.23f8a5b657c3c0209fc1.min.js:1
    ai https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    Ga https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    Al https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    Ol https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    Cl https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    bl https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    Ko https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    unstable_runWithPriority https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    Vo https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    Ko https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    Qo https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    hl https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    eu https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    iu https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    render https://wordpress.com/calypso/evergreen/42530.b58de459e57aa940f374.min.js:2
    a https://wordpress.com/calypso/evergreen/84577.01184962beac0a646ce9.min.js:1
    exports https://wordpress.com/calypso/evergreen/30605.ff958a97a9bb81cd7570.min.js:2
    s https://wordpress.com/calypso/evergreen/30605.ff958a97a9bb81cd7570.min.js:2
    l https://wordpress.com/calypso/evergreen/84577.01184962beac0a646ce9.min.js:1
    exports https://wordpress.com/calypso/evergreen/30605.ff958a97a9bb81cd7570.min.js:2
    s https://wordpress.com/calypso/evergreen/30605.ff958a97a9bb81cd7570.min.js:2
    Ys https://wordpress.com/calypso/evergreen/marketplace.23f8a5b657c3c0209fc1.min.js:1
    exports https://wordpress.com/calypso/evergreen/30605.ff958a97a9bb81cd7570.min.js:2
    s https://wordpress.com/calypso/evergreen/30605.ff958a97a9bb81cd7570.min.js:2
    ht https://wordpress.com/calypso/evergreen/81451.59e06146828bbd73b1a9.min.js:1
42530.b58de459e57aa940f374.min.js:2:191297

```

**Comment by kavyagokul** [comment]
The same issue happens with themes as well. Encountered in 6335308-zen

**Comment by sophiegyo** [comment]
Encountered in chats:  

<strike>6335844-z
6335824-z</strike>

Let both users know in follow-ups.

**Comment by worldomonation** [comment]
I tried to install Hello Dolly and saw a similar stack trace to https://github.com/Automattic/wp-calypso/issues/77461#issuecomment-1565215752, but with a different undefined value.

```
can't access property "error", H is undefined
```

**Comment by worldomonation** [comment]
Reverted offending PR in https://github.com/Automattic/wp-calypso/pull/76788, will be deploying to production after checking a few things.

**Comment by worldomonation** [comment]
Deployed to production.
