### ISSUE TITLE
Site Assembler - Endpoint - Copy starter content posts only when blog patterns are added

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#77489]
## What

In any Assembler flow, only add starter posts if the user has selected blog patterns. See p1685336248543989/1685113615.945219-slack-C048CUFRGFQ

## Why

Because the default theme annotation adds one `Hello world` post and that's fine for sites that don't use blog posts patterns.

## How

Option 1
- The client knows when a blog pattern is added so we can pass a param to the endpoint `/site-assembler`
- The endpoint will copy the posts only when the param is received

Option 2
- The endpoint receives the home template content with the patterns, it can get the block types in the content with
```
$block_names = array_unique( \WPCOM\Lib\Blocks\get_block_type_list( parse_blocks( $content ) ) );
```
- The blocks that query patterns are `query`, `latest-posts`, and `a8c/blog-posts`

Other options?
- Maybe @arthur791004  has more ideas.

**Comment by arthur791004** [comment]
Closing it since it's completed via https://github.com/Automattic/wp-calypso/pull/79132
