### ISSUE TITLE
Site Assembler - How to identify newly created sites

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#77490]
## What

We are currently identifying newly created sites using the assembler entry points:

- `with-theme-assembler` flow
- `site-setup` flow

Let's consider other options if they are easier to maintain.

## Why

The current option using the entry points can be harder to maintain than other options like using the site creation time but none are perfect because using the time will introduce edge cases. See https://github.com/Automattic/wp-calypso/pull/77152/files#r1206228423

## How

- Consider using [isNewSite](https://github.com/Automattic/wp-calypso/blob/97a7f20365454dbb30c4b5fdd98e360a9ab93cb1/client/state/sites/selectors/is-new-site.js#L13) selector in Calypso 
- Other ideas?

**Comment by taipeicoder** [comment]
Closing this as the current approach of `isNewSite` (if the site is created less than 30 mins ago) suits our needs just fine.
