### ISSUE TITLE
Signup: Theme step: layout is distorted on fluid width

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#775]
Originally reported by @jasmussen.

"Fluid width" is currently a feature flag only used by the WordPress Desktop client. But it will likely find it's way to the web-app as well. 

When you navigate to the themes showcase, the layout is distorted. I think we need a `max-width` there somewhere.

![selection_359](https://cloud.githubusercontent.com/assets/1204802/11029135/06ee3098-86c5-11e5-9985-b7fbc14fc13a.png)

cc @folletto

**Comment by folletto** [comment]
Using the `Theme` component this should be automatically handled. :) 

This is probably going to be fixed once #256 is addressed, but could be addressed separately earlier.

**Comment by oskosk** [comment]
#1079 has been merged. It could support what @folletto commented. 

Tried to run dev instance of wordpress-desktop but couldn't get to see #1079 updates on the app.

**Comment by fabianapsimoes** [comment]
This has been fixed. Closing.
