### ISSUE TITLE
WooCommerce Back In Stock Notifications Causes a Critical Error when an FSE Theme is Active

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#77504]
### Quick summary

If the plugin WooCommerce Back In Stock Notifications is active on a site with an FSE theme, the site will experience a critical error.

### Steps to reproduce

1. Create a new site and activate an FSE theme
2. Install the plugins WooCommerce and WooCommerce Back In Stock Notifications
3. Observe that a critical error is caused.

### What you expected to happen

There should not be a critical error

### What actually happened

There is a critical error

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Downgrading PHP version to 7.4 does not resolve the error.

**Comment by masperber** [comment]
The following console errors were noted on the initial report:

```
Uncaught (in promise) TypeError: $ is not a function
    at Object.<anonymous> (userscript.html?name=Theme%2520Detektorrr.user.js&id=2461bef5-7bd3-4379-9ecd-222f73959e2c:35:1)
    at St (<anonymous>:9:89)
    at userscript.html?name=Theme%2520Detektorrr.user.js&id=2461bef5-7bd3-4379-9ecd-222f73959e2c:1:89
    at window.__f__li93d495.yw (userscript.html?name=Theme%2520Detektorrr.user.js&id=2461bef5-7bd3-4379-9ecd-222f73959e2c:1:319)
    at St (<anonymous>:9:89)
    at n (<anonymous>:71:248)
    at <anonymous>:74:85
    at p (<anonymous>:68:59)
```

```
Failed to load resource: the server responded with a status of 500 ()
```

**Comment by masperber** [comment]
Customer requested followup on bug resolution:

6342170-zen

**Comment by Nic-Sevic** [comment]
Looks like it might be tied to this release: https://github.com/woocommerce/woocommerce-back-in-stock-notifications/pull/226
@xristos3490 since this is likely still fresh in your mind, maybe you can confirm/deny?

In troubleshooting this error is only occurring with FSE themes. It was replicated with all other non-required (ie jetpack, akismet, woocommerce)  plugins disabled.

**Comment by xristos3490** [comment]
Thanks for the ping @Nic-Sevic! This is indeed related! 

Back in Stock Notifications v1.6.1 will fix this and should be live shortly. Related release PR: https://github.com/woocommerce/woocommerce-back-in-stock-notifications/pull/228

**Comment by cuemarie** [comment]
[Back in Stock Notifications](https://woocommerce.com/products/back-in-stock-notifications/) is now up to v1.6.2, and I've successfully activated that on a test site using theme Tazza with no issues. Closing as fixed!

**Comment by cuemarie** [comment]
@masperber I followed up with the user here: 6410320-zd-woothemes
