### ISSUE TITLE
Stats: Iterate on subscriber overview data

### ISSUE THREAD

**Issue by annacmc** [Automattic/wp-calypso#77513]
### Details

After merging #76507 there were some remaining feedback tasks to be addressed in a followup PR. 

### Checklist

- [x] consider moving selectSubscribers() to an interface declaration at the top of the file https://github.com/Automattic/wp-calypso/pull/77632
- [x] data fetching should be moved either to the original hook (that can export both data fetching hooks) or to a new hook file. querySubscribers and selectSubscribers should not be manipulated by components consuming data (this component). https://github.com/Automattic/wp-calypso/pull/77822
- [x]  convert `const indexFirstCard = 0; // 0 for today` etc into an array & use `map`for example in the following: `const dateToday = calculateQueryDate( indexFirstCard );`  to get dates as an array too. https://github.com/Automattic/wp-calypso/pull/77515
- [x] consider renaming `subscribersData` as it is actually a two dimensional array of SubscribersData. perhaps something like subscribersDataArrays or similar https://github.com/Automattic/wp-calypso/pull/77703
- [x] look at handling errors and loading status separately, because we still want to show the working cards even when some of them errored out or are still loading. https://github.com/Automattic/wp-calypso/pull/77918

*noting usage of `today` in reference to #76912, no need to change anything right now but  we will consider this all together later.*

### Related

#76507

**Comment by hritvikgupta** [comment]
Please assign this task to me. I can get it done

**Comment by annacmc** [comment]
> Please assign this task to me. I can get it done

Hey @hritvikgupta thanks for offering! This is already underway and will be wrapped up in the next couple of days so we don't need to assign it anyone else. However, if you're looking for things to work on in Calypso and not having any luck,  I'd suggest checking out the [Good First Issues](https://github.com/Automattic/wp-calypso/issues?q=is%3Aopen+label%3A%22Good+First+Issue%22+sort%3Aupdated-desc) label

**Comment by kangzj** [comment]
Hi @annacmc it seems all the tasks have been finished. Could we close this one now?
