### ISSUE TITLE
Jetpack Connect: do not show plans page for connections originating in Jetpack Onboarding

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#7752]
Folks connecting their Jetpack sites via Jetpack Onboarding should not see the plans page as part of their connection flow. But that is currently the case:
https://cloudup.com/cb4p9W1NcqQ

Instead, folks should be redirected back to wp-admin after the connection is complete.

**Comment by johnHackworth** [comment]
fixed already
