### ISSUE TITLE
Subscribers Page: Create the sidebar menu item linking to the Subscribers page

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#77531]
The new menu item will be placed inside Users → Subscribers.

Related discussion: p1685626251216859/1685619952.615039-slack-C02TCEHP3HA.

The menu  item should be hidden behind the feature flag or the related PR(s) need to be deployed at the launch.

TODOs:

- [x] add link to Calypso → Addressed in https://github.com/Automattic/jetpack/pull/31170
- [x] add link to JP and Atomic sites (similarly to https://github.com/Automattic/jetpack/pull/28616).
- [x] add menu fallback → Addressed in https://github.com/Automattic/wp-calypso/pull/78056

**Comment by ivan-ottinger** [comment]
The task is 🔴 blocked until the discussion is finished: p1685626251216859/1685619952.615039-slack-C02TCEHP3HA.

**Comment by ivan-ottinger** [comment]
🟢 Discussion resolved. The Subscribers page will live inside Users → Subscribers.

**Comment by ivan-ottinger** [comment]
This is how we tried to approach translating of the `Reading` settings menu item previously: https://github.com/Automattic/wp-calypso/pull/73057.

At the end, it was never merged because the translation got in faster.

FYI @yansern 🙂

**Comment by ivan-ottinger** [comment]
`Subscribers` string itself has been already translated in Jetpack plugin long time ago:

![Markup on 2023-06-13 at 08:40:45](https://github.com/Automattic/wp-calypso/assets/25105483/cec35944-243a-4263-a5cc-ada3f005e5c3)

[Direct link](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/es/default/?filters%5Bterm%5D=Subscribers&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc&page=2)

So we don't need to worry about this string specifically. As soon as it gets introduced in our own PR it will be already translated.

**Comment by ivan-ottinger** [comment]
When it comes to making sure the `Subscribers` menu item displays for EN users only (until the page translations are ready), we could use a similar approach as @mashikag  cleverly used in https://github.com/Automattic/wp-calypso/pull/73057 for overriding the string with Calypso translation.

What we could do is to just check for user locale and if it is not EN, then we could filter out the menu item from the array.

How does that sound to you? 🙂

**Comment by yansern** [comment]
> This is how we tried to approach translating of the `Reading` settings menu item previously: #73057.
> 
> At the end, it was never merged because the translation got in faster.
> 
> FYI @yansern 🙂

Thanks and yes we can use the https://github.com/Automattic/wp-calypso/pull/73057 method to filter out the menu item when the locale is not EN, assuming we're gonna launch EN only end of this week.

**Comment by yansern** [comment]
> Thanks and yes we can use the https://github.com/Automattic/wp-calypso/pull/73057 method to filter out the menu item when the locale is not EN, assuming we're gonna launch EN only end of this week.

We won't proceed with this and will just let the menu item come in when it comes.

**Comment by yansern** [comment]
It will be EN only this week, and ALL users next week.
