### ISSUE TITLE
Unable to run "make run" on Windows 10

### ISSUE THREAD

**Issue by richdev135** [Automattic/wp-calypso#7754]
#### Steps to reproduce
1. I followed these instructions: https://github.com/Automattic/wp-calypso/blob/master/docs/windows.md
2. I have node.js, Git, npm installed.
3. I am running Cygwin64. I just did an update to make sure my version is most current
4. I am using a cmd prompt as Admin
5. When I enter make run, here's what I get:
C:\dev\projects\calypso\wp-calypso>make run
             _
    ___ __ _| |_   _ _ __  ___  ___
   / __/ _` | | | | | '_ \/ __|/ _ \
  | (_| (_| | | |_| | |_) \__ \ (_) |
   \___\__,_|_|\__, | .__/|___/\___/
               |___/|_|

module.js:340
    throw err;
    ^

Error: Cannot find module 'C:\cygdrive\c\dev\projects\calypso\wp-calypso\bin\check-node-version'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
 make: *** [Makefile:95: node-version] Error 1

C:\dev\projects\calypso\wp-calypso>

#### What I expected
Not that!  :-)  ^^

#### What happened instead
module.js:340
    throw err;
    ^

Error: Cannot find module 'C:\cygdrive\c\dev\projects\calypso\wp-calypso\bin\check-node-version'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
 make: *** [Makefile:95: node-version] Error 1

#### Browser / OS version
OS = Windows 10. 

Docs & troubleshooting:
https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md
https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md

I've looked at the 2 links above, but they do not help my problem.

I'll be happy to answer/help in any way. I'd like to become a contributor. I was excited to see this project on GitHub.

**Comment by richdev135** [comment]
Update: ok, I missed one "small" thing that might be the cause: my git is in "program files" and I see that my path should not include spaces.  I'll move git and try again.

**Comment by richdev135** [comment]
No - that was not the issue.  Still same indications. Git is in a directory with no spaces.

C:\dev\projects\calypso\wp-calypso>which git
/cygdrive/c/Git/bin/git

**Comment by lamosty** [comment]
Hey richdev135, thanks for trying to run Calypso!

First, to be honest, it's a lot of pain to get it working under Windows 10. I tried it once (just a quick try) and didn't get it working. I really recommend using Linux/Ubuntu or OS X if you'd like to contribute. :)

Anyways, I noticed you mentioned that you have Cygwin64. However, the [guide you linked to](https://github.com/Automattic/wp-calypso/blob/master/docs/windows.md) instructs to use [MSYS2](https://msys2.github.io/), not Cygwin. Could you please try and use MSYS2 instead? :)

**Comment by richdev135** [comment]
Hi, Lamosty,  The good news is that I did get it running on a Lubuntu VM. I'm not sure I like the VM, so I'm going to kill it and start new, but at least we know it works. 

In Windows, I did also try with MSYS2 and Cygwin, but it still no luck.  Now that I've got it working on Linux (and will again), I can start digging in.  

Thanks for your suggestion!

**Comment by lamosty** [comment]
> The good news is that I did get it running on a Lubuntu VM. I'm not sure I like the VM, so I'm going to kill it and start new, but at least we know it works.

I'm glad to hear that!

> In Windows, I did also try with MSYS2 and Cygwin, but it still no luck. Now that I've got it working on Linux (and will again), I can start digging in.

Yeah, it's quite complex to get it working properly. Until [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) doesn't run Calypso (last time I tried it didn't fully work), the best option is to run it either in a Linux VM like you did or under a full Linux or OS X operating system.

I'm closing this issue as you've got it resolved, in a way. :)
