### ISSUE TITLE
Email Contact Links not functioning properly

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#77546]
### Quick summary

The email contact links as outlined in the support documentation (https://wordpress.com/support/email-links/#creating-email-links) are no longer working. Instead of directing to the expected destination, they lead to an "about:blank" page when opened in a new tab.

### Steps to reproduce

*  Create an email link following the steps from this guide: [https://wordpress.com/support/email-links/#creating-email-links](https://wordpress.com/support/email-links/#creating-email-links)
*  Click on the email link. The link doesn't seem to respond or do anything.
*  Try to open the link in a new tab. It leads to an "about:blank" page instead of the expected email client.
*  The HTML workaround also doesn't seem to work.

https://github.com/Automattic/wp-calypso/assets/50875131/713f018d-261a-4818-9c12-f112a6057372

### What you expected to happen

When a user clicks on the email link, it should open the default email client with a new email draft to the designated address.

### What actually happened

The email links are not working as expected. They either do nothing or redirect to an "about:blank" page when opened in a new tab.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

– User report here: 6344852-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Could Not Replicate**
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- `mailto:` style email contact links worked fine for me on both Simple and AT sites. Tested with `mailto:help@wordpress.com`

- The issue in this user's case is very likely stemming from their device. When the user clicks on a mailto link, the default email client should open on the user's computer and suggest sending an email to the address included in the mailto link. 
- For me, working in FireFox, clicking a `mailto:` link opens my default Chrome browser.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/3e76ec87-286d-4a25-a73a-19c5ad91f599

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @Gustavo-Hilario I also opened up the reporting user's CONTACT page and tested their link, and that worked as expected for me as well. If you're still running into issues, can you test across multiple browsers, checking for any issues within default email client settings, browser settings, or security settings on your/the user's device?

**Comment by Gustavo-Hilario** [comment]
Thank you for checking this, @cuemarie 🙏 

I was consistently reproducing this issue and thought it was a bug. I'm glad it isn't, and the user is all set now after some browser and site troubleshooting.
