### ISSUE TITLE
[Bug] Uploading Plugins via Marketplace results in errors, no_plugin_installed

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#77556]
### Quick summary

Error `Upload problem: no_plugin_installed.` when uploading plugins via the Marketplace plugin page https://wordpress.com/marketplace/plugin/install/{site address} 

![image](https://github.com/Automattic/wp-calypso/assets/29527450/dcc7993e-b40f-4df5-9c8a-058c2c8ac399)

### Workaround

Go to wp-admin https://{site address}/wp-admin/plugin-install.php to upload the plugin. 

### Steps to reproduce

1. Download any plugin from the org repo https://wordpress.org/plugins/ 
2. In your WordPress.com dashboard My Site > Plugins > Add New and click Upload. 
3. Drag and drop your plugin file or upload it via Browse. 

### What you expected to happen

I expect the plugin to upload to my Atomic site successfully. 

### What actually happened

I get on-page errors:

> An error occurred while installing the plugin.

and 

`Upload problem: no_plugin_installed.`

Console log shows:

`43823.1a19f4f9581269e94ff5.min.js:1     GET https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request%5Bslug%5D=&request%5Blocale%5D=en_US&request%5Bfields%5D=icons%2Cshort_description%2Ccontributors%2C-added%2C-donate_link%2C-homepage 400 `

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

**Currently being investigated here p1685464188850239-slack-C02FMH4G8**

**Comment by cuemarie** [comment]
_Mistakenly closed this as a dupe - but this issue is still open at the moment!_

Resolution is in the works on the escalated thread here: p1685464188850239-slack-C02FMH4G8

**Comment by samiff** [comment]
Jetpack v12.2-beta.2 is now deployed to Atomic sites which resolves this issue: p9o2xV-38b-p2
