### ISSUE TITLE
Jetpack Pricing Page: skip to main feature is broken

### ISSUE THREAD

**Issue by mattgawarecki** [Automattic/wp-calypso#77562]
## What's the issue
In the Jetpack pricing page, the _Skip to main content_ feature does not work.

## How to reproduce the issue
- Visit https://cloud.jetpack.com/pricing
- Press the `Tab` key until you see the _Skip to main content_ link appear
- Press the link
- Press the `Tab` key multiple times: notice the focus keeps moving across the navigation instead of the main content of the page

## Expected behavior
Clicking _Skip to main content_ should move the focus to the main content of the page. This is broken because several elements have an `id` with the `content` value.

## Captures

<img width="400" src="https://user-images.githubusercontent.com/1620183/227262495-318eb07a-046c-4306-8f48-1e13be082b7a.png" alt=""/>

**Comment by john-legg** [comment]
📌 REPRODUCTION RESULTS

Tested on Simple – Not applicable
Tested on Atomic – Not applicable
Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate this on a self-hosted site when signing up for a plan as well as accessing the pricing page on its own. However, I was only able to replicate it on Chrome. In Safari and Firefox, tabbing didn't allow me to navigate across the site or bring up the _Skip to main content_ popup, which might be related to this issue

<img width="1275" alt="Jetpack Plan Skip To Main Feature" src="https://github.com/Automattic/wp-calypso/assets/96805492/1ab0ad28-1b79-4728-9200-30853ea790de">


📌 ACTIONS

Assigned to `Other` column (@jeherve)
