### ISSUE TITLE
Launchpad: rethink the Badge component

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#77564]
Issue created based on this comment: https://github.com/Automattic/wp-calypso/pull/77465#pullrequestreview-1451339843

To create the launchpad package, we had to add a copy of the `Badge` component from Calypso.

A better solution would probably be to move the `Badge` component to the `@automattic/components` and import it in both calypso and the launchpad code.

**Comment by sixhours** [comment]
This has been shipped in https://github.com/Automattic/wp-calypso/pull/78812
