### ISSUE TITLE
Theme Curation: Investigate Page ordering plugins

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#77611]
After [making the theme CPT hierarchical](https://github.com/Automattic/wp-calypso/issues/77610) we should look at how we can have a more graphical way of ordering themes. 

There are some existing plugins ( e.g. [#1](https://wordpress.org/plugins/post-types-order/), [#2](https://en-gb.wordpress.org/plugins/simple-page-ordering/))  or we could look at implementing a lightweight version ourselves.

**Comment by dsas** [comment]
Looking at plugin [#2](https://en-gb.wordpress.org/plugins/simple-page-ordering/) - Simple Page Ordering.

We may want to hook [`simple_page_ordering_is_sortable`](https://github.com/10up/simple-page-ordering/blob/develop/simple-page-ordering.php#LL88C27-L88C59) to only make our post type drag and drop sortable.

It's still necessary to keep the order integer field in the ui, it's handy to make big changes to theme order quickly and it's required to move a theme between pages of results.

Using this plugin means all themes are ordered. Once you make your first re-ordering it assigns a unique value to each theme.  

Putting numbers in fields remains necessary to move the theme between pages in wp-admin, and that there's no graphical preview of the theme. I think overall it's an increase in convenience for curators, but I'm not sure it really addresses the overall problem. They're probably still going to create something in figma and then use wp-admin to repro that.

**Comment by Copons** [comment]
Closing this issue as we're going with an in-house solution.
