### ISSUE TITLE
Subscription Management: Add payment details info on individual site subscription page.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#77612]
> Payment details will be parked for later as we are unable to retrieve payment information.
Plan and billing period will be in.

_Originally posted by @JuanLucha in https://github.com/Automattic/wp-calypso/issues/77233#issuecomment-1561234225_

<img width="497" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/c8e62670-a45a-4bee-8428-feacda69f4c0">

**Comment by mashikag** [comment]
The project is now complete, with the scope reduced to not include the details for now. We have no further plans of iterating on the current implementation for now, hence I am closing as not planned.
