### ISSUE TITLE
Reader Sharing + Embeds - ATOMIC sites fail initial embed request 429

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#77622]
for non-a11n atomic sites on production: sharing from the reader results in a broken embed block on initial load. Clicking "try again" resolves the issue, but loading in a broken state is not a good user experience.

Upon inspection the request for the embed seems to fail on "429: Too Many Requests"

#### Steps to reproduce

NOTE - This was not reproducible on my sandbox, NOR on production with a site tied to an a11n account. Test in production with a non-a11n account creating an atomic site.

1. On a non-a11n WordPress.com account, create an Atomic site by adding a plugin. 
2. Once the site is transferred to atomic, visit the reader.
3. Find a post, click the share icon, and select the atomic site you created.
<img width="250" alt="Screenshot 2023-05-31 at 10 49 39 AM" src="https://github.com/Automattic/wp-calypso/assets/28742426/50a2c85b-6b63-4273-b583-38a4e2a895f8">

4. When the editor loads, notice the embed block appears broken:

<img width="450" alt="Screenshot 2023-05-31 at 10 49 39 AM" src="https://github.com/Automattic/wp-calypso/assets/28742426/50a2c85b-6b63-4273-b583-38a4e2a895f8">

5. If you had devTools open and inspect the request for the embed preview (search "embed" and find the proxy request with the post you tried to embed as the url param), you will see it failed and sent this response: "429: Too many requests"

<img width="750" alt="Screenshot 2023-05-31 at 10 49 39 AM" src="https://github.com/Automattic/wp-calypso/assets/28742426/dff4c6e9-e7c1-46ef-b22c-feafb3e6190d">

6. Select "Try Again" at the bottom of the embed block and notice this now succeeds and embeds as expected.

#### What I expected

1. The embed to load properly the first time.

#### What happened instead

1. The embed loaded in a broken state.

#### Browser / OS version

Firefox 113.0.2 (64-bit)

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Uncertain**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I had mixed results trying to replicate this.  First I tried in Chrome, sharing a WordPress.com News post to my AT and Simple sites (non a11n account). In both cases, this resulted in a broken Embed:

https://github.com/Automattic/wp-calypso/assets/27249804/beb9497e-70ab-4f0c-9902-cbaf8ba00d87

This seems to connect to this `404` error regarding `X-Frame-Options` being set to `sameorigin`, though not positive.

![xtJAN3.png](https://github.com/Automattic/wp-calypso/assets/27249804/5d6324ab-60d6-450f-8b5f-0786e5775712)

Next I tried in a private FireFox tab - trying to share that same post resulted in a different Firefox security error:

https://github.com/Automattic/wp-calypso/assets/27249804/f9c0030b-6c3d-4cf9-a7bd-596ecd1835a7

Finally, another test using a post from the Atavist Magazine didn't encounter any error at all:

https://github.com/Automattic/wp-calypso/assets/27249804/cfc97ff1-9cf0-4a44-9a62-f8ccbc600a53

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @Addison-Stavlo do you see the same error on your tests no matter what post you share, or do you see varying results like I am running into?

**Comment by Addison-Stavlo** [comment]
Il track this.  After some investigation this seems to be due to an unrelated defective selector in the ETK plugin thats triggering some issues where it possibly shouldn't on atomic.  p1685550995632009-slack-C03N25JPCE4 for more context.

https://github.com/Automattic/wp-calypso/pull/77629 should resolve on one side, p9o2xV-38k-p2 on the other.

**Comment by cuemarie** [comment]
Thanks Addison!

📌 ACTIONS
- Assigned to Other given the work already happening around this, noted in the previous comment. (PR is merged, so just the internal discussion with @Automattic/reactor is left)

**Comment by Addison-Stavlo** [comment]
Note this issue is resolved - we are no longer triggering these 428s on the atomic sites and the behavior from the users end works as expected.

> (PR is merged, so just the internal discussion with https://github.com/orgs/Automattic/teams/reactor is left)

Are we ok closing this now @cuemarie , or did you want to hold for this discussion you noted?

<hr />

Just following up on previous discussion:

> This seems to connect to this 404 error regarding X-Frame-Options being set to sameorigin, though not positive. 

Those 404s were definitely the underlying issue (there were 7+ 404s for that site-intent request you linked! and this sometimes triggered some rate limitation causing the 428s on other requests like this embed).  I think the x-frame/sameorigin is unrelated.

> @Addison-Stavlo do you see the same error on your tests no matter what post you share, or do you see varying results like I am running into?

It was so inconsistent TBH. It ended up being fairly consistent when I tested on a non-a11n account, but even then sometimes it was fine.

**Comment by cuemarie** [comment]
Hey @Addison-Stavlo , thanks for the follow up! I'm good to close this! I wanted to make sure I didn't do so prematurely, but it's great to hear that the behavior is now working as expected.

📌 ACTIONS
- Closing as resolved! 🎉
