### ISSUE TITLE
Stats: Fix ICU error in Safari when invoking Intl

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#77635]
Similar: https://github.com/google/site-kit-wp/issues/3255 and https://github.com/google/site-kit-wp/pull/3620.
Reported: 59135490-zen
Sentry: CALYPSO-ZBW
Prior attempts: https://github.com/Automattic/wp-calypso/pull/72922.

This only occurs in Safari 14.1 on macOS Mojave (10.14). This does not happen for macOS 10.13 or macOS 10.15.

**Comment by john-legg** [comment]
@jeherve, I added this to the [Dotcom Bug Prioritization Board](https://github.com/orgs/Automattic/projects/343#card-89385271) since it's Jetpack Stats-related, but I'm a bit unsure since I can't tell how to replicate the issue. What are your thoughts?

**Comment by jeherve** [comment]
@john-legg Since it's already on the board of the team working on this, I don't think there is anything else you have to do to triage this.
