### ISSUE TITLE
Assembler - make sure only one snackbar of same type displays at once

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#77645]
## What

Stacking multiple notices obscures the interface in the assembler.

![Image](https://user-images.githubusercontent.com/1881481/242487750-3c14dec6-d135-4c01-9cc6-4e6bea85f5b8.png)

## Why

For better visibility of the canvas. Following the same behavior as in the editor. See https://github.com/WordPress/gutenberg/pull/50625

## How

Let's show only one notice of the same type (add/replace/remove) at a time.

**Comment by fushar** [comment]
This is shipped!
