### ISSUE TITLE
Theme card CSS is wrongly overwritten in local environment

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#77640]
## Description

As discussed in p1685522026017909-slack-CRWCHQGUB, theme cards might not look right in local environment due to the CSS being overwritten (specificity).

![Image](https://github.com/Automattic/wp-calypso/assets/797888/f1fb8478-8931-4fe3-ab4a-afcbe00c1cac)

## Acceptance Criteria

- [ ] Theme cards should look the same as the ones in production.

**Comment by Copons** [comment]
Just as a note: https://github.com/Automattic/wp-calypso/issues/77757 too seems to be caused by differing CSS load orders on different environments.

**Comment by taipeicoder** [comment]
Closing via #77820 and #77868.
