### ISSUE TITLE
Assembler - Block renderer - Targeting of theme.json styles to a pattern

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#77648]
## What

A classname in the pattern container is required to apply theme.json styles to a pattern. Not sure how that feature works and if we support it in the assembler. Let's check it and add it if missing.

## Why

The slug is added to the wrapper in the editor and the frontend currently in order to allow the targeting of theme.json styles to a pattern.

## How

- Learn how to use the feature. See my [comment](https://github.com/WordPress/gutenberg/pull/50641#issuecomment-1571416666)

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
