### ISSUE TITLE
Plans 2023: Remove old pricing grid code

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#77654]
Related to https://github.com/Automattic/martech/issues/1533
Depends on https://github.com/Automattic/wp-calypso/issues/77652 and https://github.com/Automattic/wp-calypso/issues/77653

Once p2 plans and pm flow have migrated to the new pricing grid:

- [ ] remove [PlanFeatures](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-features) and [PlanFeaturesComparison](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-features-comparison)
- [ ] remove any code that is linked/imported from these components and not used anywhere else (investigate)

**Comment by southp** [comment]
This has been completed by https://github.com/Automattic/wp-calypso/pull/83443/

**Comment by chriskmnds** [comment]
@southp can you please confirm if [plan-interval-discount](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-interval-discount) has any remaining references? I believe this was used in old pricing code and not cleaned up when removed. 

I'll reopen the issue and you can reclose once confirmed. Thanks! :-)

**Comment by southp** [comment]
Thanks for the impressive sleuthing, @chriskmnds . I didn't spot any remaining references so I've removed the code by https://github.com/Automattic/wp-calypso/pull/84951. I also did another round of sweep to see if there was anything else remaining but couldn't find any, so I'm closing this again.
