### ISSUE TITLE
Plans 2023: Migrate paid-media flow to use the new grid

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#77653]
Related to https://github.com/Automattic/martech/issues/1533

Some more context in Slack p1685011294958529-slack-CV2TX2PAN. The paid-media/pm flow is importing and using the old pricing grid from `PlanFeatures` - we need to either migrate to the new grid or conclude the pm flow to unblock removing old pricing components.

**Comment by southp** [comment]
This will be effectively closed by https://github.com/Automattic/growth-foundations/issues/70, since the current paid-media flow will be replaced. Thus I'm moving this down for now :)
