### ISSUE TITLE
Plans 2023: Migrate p2 flow/admin pricing grid to use the new grid

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#77652]
Related to https://github.com/Automattic/martech/issues/1533

If vising `/plans/[site]` with a site created via the p2 funnel `/start/p2`, the old pricing grid shows. The previous `PlanFeatures` component is imported and used directly in one of the wrappers. We should migrate to the new `PlansFeaturesMain` component (gotta love our naming conventions!).

**Comment by dzver** [comment]
Is this is the final task that's needed to retire the old pricing grid?

**Comment by southp** [comment]
@dzver Yes, it is. I've reassigned this to @jeyip since @chriskmnds is still now focusing on https://github.com/Automattic/wp-calypso/issues/77187 which is more complicated than we expected.

**Comment by jeyip** [comment]
Adding a quick status update...

I'm focusing on google domains work ( pet6gk-wX-p2, https://github.com/Automattic/martech/issues/1873, https://github.com/Automattic/martech/issues/1872 ) and will return to this issue as time permits, but it will be lower priority relative to what I've linked

**Comment by jeyip** [comment]
Unassigning myself and pausing work on this for the time being as high priority work has popped up ( Google Domains + Storage Add-Ons )

cc @southp for visibility

**Comment by southp** [comment]
Thanks @jeyip . I've moved it back to Next Up so it's up for grabbing once again :)

**Comment by dzver** [comment]
Thanks for the update. I confirm that both Storage and Domains have higher priorities.

**Comment by jeyip** [comment]
Drafted a P2 to align with design and team lighthouse p9lV3a-6EY-p2

We're moving forward with my PR and removing any custom styling or layout that diverges from the 2023 plans grid

**Comment by jeyip** [comment]
P2 workspace plans page has been migrated to the 2023 plans grid
