### ISSUE TITLE
Subscribers Page: Make `/subscribers` land in Calypso

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#77662]
Similarly as with the `/subscriptions` page before (pMz3w-haX-p2), we will likely need to request `/subscribers` to be pointed to Calypso as well.

At the moment, `/subscribers` lands in Calypso, but in the development environment only.

**Comment by TimBroddin** [comment]
@ivan-ottinger This would become `https://wordpress.com/subscribers/<siteslug>` right?

**Comment by TimBroddin** [comment]
@ivan-ottinger looking at the current paths I see routes such as `/sites/<siteid>/subscribers/import`. Wouldn't it be better to have our route be `/sites/<siteid>/subscribers`?

**Comment by ivan-ottinger** [comment]
> @ivan-ottinger This would become https://wordpress.com/subscribers/<siteslug> right?

Yes, that is where the currently developed page lives.

> @ivan-ottinger looking at the current paths I see routes such as /sites/<siteid>/subscribers/import. Wouldn't it be better to have our route be /sites/<siteid>/subscribers?

🤔 What does load at `/sites/<siteid>/subscribers/import` for you? I am seeing just a blank screen there.

**Comment by TimBroddin** [comment]
> > @ivan-ottinger This would become https://wordpress.com/subscribers/ right?
> 
> Yes, that is where the currently developed page lives.
> 
> > @ivan-ottinger looking at the current paths I see routes such as /sites//subscribers/import. Wouldn't it be better to have our route be /sites//subscribers?
> 
> 🤔 What does load at `/sites/<siteid>/subscribers/import` for you? I am seeing just a blank screen there.

Nevermind, I was just OpenGrokking and wrongfully assumed something (it was an API call). Sorry for the confusion!

**Comment by TimBroddin** [comment]
Posted in systemrequests: pMz3w-hHc-p2

**Comment by ivan-ottinger** [comment]
No worries at all! Thank you for submitting the request, Tim!

**Comment by ivan-ottinger** [comment]
`/subscribers` is now loading nicely (with the feature flag enabled) in staging. 🙂
