### ISSUE TITLE
Radcliffe 2 Grouped blocks ignore backgrounds

### ISSUE THREAD

**Issue by DavidSaladu** [Automattic/wp-calypso#77669]
### Quick summary

Grouped blocks with a background seem to be ignored on the Radcliffe 2 theme.

### Steps to reproduce

1. Create a page
2. Add some blocks (text or others)
3. Group them
4. Change the background color 
5. Check the published page

### What you expected to happen

The color of the grouped area should match the selected color.

### What actually happened

The background color gets ignored

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

MacBook Pro, MacOS Ventura 13.4
Chrome version Version 113.0.5672.126 (Official Build) (x86_64)

### WORKAROUND

Other themes like Zoologist seem to process the background correctly

**Comment by john-legg** [comment]
📌 REPRODUCTION RESULTS

Tested on Simple – Could Not Replicate 
Tested on Atomic – Could Not Replicate
Replicable outside of Dotcom – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

Unfortunately, I was not able to replicate this using the Radcliffe 2 theme on any browser (Chrome, Firefox, or Safari). The background appears on the live site just like it does in the editor view. I've tried it on Simple and Atomic (WPCOM and self-hosted) sites as well.


https://github.com/Automattic/wp-calypso/assets/96805492/04e0509e-9011-4763-97d7-a8761f4b3045



📌 ACTIONS

Requested author feedback

📌 Message to Author

@DavidSaladu, I was unfortunately not able to replicate this. Is the issue still showing up for you? If so, do you mind providing some additional details:

- Which blocks did you group together?
- Was this found on Simple, Atomic, and/or self-hosted?

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closed as not reproducible
- Feel free to reopen and share any thoughts to the inquiry above. Thanks!

**Comment by DavidSaladu** [comment]
Sorry for the very late reply. Tried as well to reproduce it and the issue no longer appears to me either. Thanks!
