### ISSUE TITLE
HTML Embed for Google Maps does not display Map on Live Site

### ISSUE THREAD

**Issue by NatzJoy** [Automattic/wp-calypso#77666]
### **Issue**

When using the HTML block to embed a Google Map, the map will display correctly in the preview. However, it only displays part of the HTML code on the published version of the site. 

### **Cause**

This is theme specific, as I could not replicate the issue using a different theme. 

### **Theme**

**[Pendant](https://wordpress.com/theme/pendant/)**

### **HTML Block Preview**

![screenshot](https://cln.sh/DtJ1Pz7b+)

### **Live Version of the HTML Block**

![screenshot](https://cln.sh/577Dxrpx+)

### Steps to reproduce

1. Obtain an embed code for the address to embed a Google map.
2. Go to Google Maps and type in an address, I've used Automattic's address. 
3. Once you've entered the address, click share as shown below:

![screenshot](https://cln.sh/BD5F8z1w+)

4. Select the option to _Embed a map_ and click _COPY HTML_ as shown below:

![screenshot](https://cln.sh/kpjg6rBZ+)

5. Once you've copied the HTML, go to a _Simple Site_ and set the _Pendant_ theme by navigating to Appearance →Themes. 
6. Go to your _Pages_ or _Posts_ dashboard and click to _Add a New Page/Post_. 
7. Type /HTML to create a new HTML block or click the + sign in the top-left to add the HTML block. 
8. Paste the embed code you obtained in Step 4. 
For ease of reference, the code is: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3154.9584292915943!2d-122.42416362413702!3d37.744119471993216!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8085807c23cc4ebb%3A0x108059532273706!2sAutomattic%20Inc!5e0!3m2!1sen!2sza!4v1685617886630!5m2!1sen!2sza" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`
9. Click  _Preview_ in a new tab. You should see the map as shown below:

![screenshot](https://cln.sh/ZJTnsqLy+)

10. Once published, you will see only the code where the map embed should appear, as shown below:

![screenshot](https://cln.sh/pg9wRs9q+)

### What you expected to happen

I expected to see the map embedded into the page as it has on a different site, using the **[Varese](https://wordpress.com/theme/varese/)** theme, as shown below: 

![screenshot](https://cln.sh/cmHqPRnP+)

### What actually happened

Viewing the published site which is using the _Pendant_ theme, only the embed code is displayed, as shown below: 

![screenshot](https://cln.sh/pg9wRs9q+)

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

**Workaround**

The user can opt to use the _Map_ block, however, the address information accepted by the block leaves room for error as it does not always locate the address correctly.

**Theme**

[**Pendant**](https://wordpress.com/theme/pendant/)

![screenshot](https://cln.sh/2GXY0MmY+)

**User Ticket #6341372**

**Sites Used**
→ User issue replicated [here](https://footballwithnatzcom.wordpress.com).
→ Required outcome achieved [here](https://natzjoy.com/2023/06/01/550/).

**Comment by john-legg** [comment]
📌 REPRODUCTION RESULTS

Tested on Simple – Could Not Replicate
Tested on Atomic – Could Not Replicate
Replicable outside of Dotcom – No


📌 FINDINGS/SCREENSHOTS/VIDEO

Unfortunately, I was not able to replicate this issue with the Pendant theme using the provided embed code as well as my own. I tried on all Simple plans (Free, Personal, Premium) and even on Atomic sites (WPCOM and self-hosted). I also tried it with all browsers (Chrome, Firefox, and Safari) and the embed worked properly on the live site.

https://github.com/Automattic/wp-calypso/assets/96805492/3fe8e2eb-9080-4a11-9819-3a677663b37b




📌 ACTIONS

Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author

@NatzJoy, I wasn't able to replicate this, unfortunately. Do you mind checking your test sites to see if you're seeing the same? Feel free to reopen if it's still an issue 😄
