### ISSUE TITLE
Gutenberg 15.9: Infinite loading on Site Editor when using Safari

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#77663]
### Quick summary

When the plugin Gutenberg is active, the Site Editor will keep showing a spinning circle/loading indicator on the Safari browser. Deactivating the plugin resolves the issue.

### Steps to reproduce

1. Access WordPress.com using the Safari browser
2. Ensure plugin Gutenberg 15.9 is active
3. Access Site Editor
4. See the infinite loading indicator

### What you expected to happen

Site Editor should open, and the plugin Gutenberg should stay active

### What actually happened

The Site Editor keeps loading. Please see the GIF below. On the right is the CLI, indicating the plugin Gutenberg is active. On the left is the Site Editor still spinning.

![Jun-01-2023 18-03-21](https://github.com/Automattic/wp-calypso/assets/44726232/a4945516-3dfa-4d53-bb8c-f64fc66b297b)

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

**Workaround:** Deactivate plugin Gutenberg

---
Happens on Safari browser. My browser's version is: 
Version 16.5 (18615.2.9.11.4)
MacOS Ventura 13.4

---

No significant error on CLI. Error message from Console log referring to Error 404 and 428.
![Screenshot 2023-06-01 at 6 08 18 PM](https://github.com/Automattic/wp-calypso/assets/44726232/f3d8dda4-73bd-478a-a499-e1fe76ba34fe)

![Screenshot 2023-06-01 at 6 08 47 PM](https://github.com/Automattic/wp-calypso/assets/44726232/aaef67f8-0b46-4075-ad99-6239171d7f79)

**Comment by tyxla** [comment]
The fact that the editor keeps loading indefinitely in the case of an error is unfortunate, but we have suggested a fix for it in Gutenberg already, and it's pending code review:

https://github.com/WordPress/gutenberg/pull/51049

The error here seems to be caused by another issue though, all those 404s are unexpected and I'm unable to reproduce on any of my atomic sites.

**Comment by retnonindya** [comment]
Thanks, @tyxla! It's great knowing a fix is ready 🎉 

As for the Error 404, yeah, I'm not sure what's happening. I'm planning to wait for the fix, test it again, and see how it goes. I really appreciate you looking into this. Thank you!

**Comment by tyxla** [comment]
Sure thing, no worries @retnonindya!

Just something to keep in mind is that those intermittent 404s _usually_ indicate a bigger issue on the particular WordPress installation and not a bug with Gutenberg or WordPress in particular.

**Comment by annezazu** [comment]
Noting for good measure that I can't replicate in a self hosted site with Safari using GB 15.9 and WP 6.2.2 with no additional plugins installed. Thanks for tracking this down and surfacing!

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm unable to replicate this problem. On my test AT site with Gutenberg 15.9.0 active, the site editor loads as expected in Safari 16.5. 

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/4200befa-4dbf-4153-be96-613fda3b0874

That said, I am seeing lots of `404` errors in my console. Many of those go away if I deactivate **WordPress.com Editing Toolkit**.  Deactivating Gutenberg and refreshing does not resolve the remaining 404 errors related to the block editor, but loading times speed up a bit.

![Markup on 2023-06-01 at 15:33:57](https://github.com/Automattic/wp-calypso/assets/27249804/32eea681-ef71-4e35-a3f5-af8717010fe2)

**WordPress.com Editing Toolkit disabled, Gutenberg still active**

https://github.com/Automattic/wp-calypso/assets/27249804/36fb4f30-cf85-4550-9445-8566df58a190

**Both WordPress.com Editing Toolkit and Gutenberg deactivated**

https://github.com/Automattic/wp-calypso/assets/27249804/878b370a-d66a-42ab-8bf2-7ad69de23ec7

📌 ACTIONS
- Awaiting author reply

📌 Message to Author
- @retnonindya is your site editor still failing to load at all with Gutenberg active?

**Comment by cuemarie** [comment]
The 404s connected to the WordPress.com Editing Toolkit are in discussion here: p1685550995632009-slack-C03N25JPCE4

**Comment by retnonindya** [comment]
@cuemarie I just tested it, and the Editor now loads! 🎉 Thanks for checking on this, folks! Also, I don't see any reports other than mine and another HE, so it might be something isolated/cache-related. I'm going to close this. Thanks again!
