### ISSUE TITLE
Dotcom Emails: WordPress logo looks indented on email footer.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#77717]
There is an extra whitespace next WordPress logo on the email footer that should be removed.

<img width="851" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/f5198f45-f506-4bd1-b109-b42a494abc27">

**Comment by TimBroddin** [comment]
This is the image used there:

<img width="1216" alt="CleanShot 2023-06-28 at 15 19 29@2x" src="https://github.com/Automattic/wp-calypso/assets/528287/2214b90f-678f-4e7e-93e5-599c64867a3a">

Notice that it has a white/grayish background, and rounded transparent borders.
Wouldn't it be better to replace this with a fully transparent version?

**Comment by TimBroddin** [comment]
Fix in D114826-code
