### ISSUE TITLE
Dotcom Emails: Prevent copy & paste URL from being linkified on Apple Mail.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#77716]
We can't prevent it from being linkified but we can turn it back to grey (so that it doesn't appear as two different shade of blue) and remove the underline using `[x-apple-data-detectors]`.

See: https://www.litmus.com/blog/how-to-remove-blue-links-in-html-emails/

<img width="705" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/ac3be5c7-56d4-4ccb-a7f9-c6cf440c07c1">

**Comment by TimBroddin** [comment]
Fix in D114820-code
