### ISSUE TITLE
The Google Workspace billing info step does not show required fields for Canada

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#77759]
The contact info/billing info step of checkout automatically shows required fields for the selected country (see https://github.com/Automattic/wp-calypso/pull/73121). There are three versions of the contact step: "tax" (the default), "domain" (for domain products), and "gsuite" (for Google Workspace products).

It appears that the Google Workspace version of the form does not show fields that are required.

To reproduce:

- Add Google Workspace to the shopping cart.
- Visit checkout.
- Select "Canada" as the country in the second step of checkout.

Expected: the "City" and "Province" fields appear.

Actual: No additional fields appear.

<img width="588" alt="Screenshot 2023-06-02 at 3 43 13 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/82b010a7-84c1-47da-82fb-961c239a9634">

This was reported in pNPgK-6ur-p2.

**Comment by sirbrillig** [comment]
It looks like when required per-country fields were implemented, while a great deal of code had to be added to the "tax" form to [include the new fields](https://github.com/Automattic/wp-calypso/blob/f61ebc88ced9c53d3ad30c53e89e9ab8e1684a12/client/my-sites/checkout/composite-checkout/components/tax-fields.tsx#L66), no additional work was added to the domain contact form because it already had its own mechanism to display required fields, and (I think) those just happen to match up with the new requirements (although this makes me wonder if there are cases where they will not). 

I think we believed at the time that Google Workspace would be similar because they both are rendered by the [same component](https://github.com/Automattic/wp-calypso/blob/f61ebc88ced9c53d3ad30c53e89e9ab8e1684a12/client/my-sites/checkout/composite-checkout/components/contact-details-container.tsx#L97). However, the Google Workspace form [has its own rendering path](https://github.com/Automattic/wp-calypso/blob/f61ebc88ced9c53d3ad30c53e89e9ab8e1684a12/client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx#L408-L418) and it doesn't have the ability to show any of the required fields.

**Comment by sirbrillig** [comment]
Note: this will only happen when Google Workspace is the only thing in the cart. If it's being purchased with a domain, the domain form will be shown which does not suffer from this bug.

**Comment by sirbrillig** [comment]
This should be mostly fixed by https://github.com/Automattic/wp-calypso/pull/77769

However, the Google Workspace validation endpoint (`/me/google-apps/validate`) does not currently return an error if required fields are missing. This also needs to be fixed! That's a backend change, however.

**Comment by worldomonation** [comment]
@sirbrillig This issue showed up in the Dotcom Prioritization Board but we do not have a column for Shilling. Mind if I move it over to Others column?

**Comment by sirbrillig** [comment]
That's fine. 👍

**Comment by sirbrillig** [comment]
D113439-code should fix the remaining part of this by updating the Google Workspace validation endpoint.
