### ISSUE TITLE
Enhancement: 24 hour time format on scheduled posts

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/wp-calypso#77753]
### What

This request comes from Twitter: 
https://twitter.com/matejlatin/status/1664616815610273794

User would like the ability to use a 24 hour (or military) style time system rather than the AM/PM system. 

### Why

24 hour or military time is more universal and easier for our users who aren't familiar with the am/pm system.

**Comment by john-legg** [comment]
📌 REPRODUCTION RESULTS

Hey @lizkarkoski 👋 I have some great news! It looks like there is already a way to use 24 hour time when scheduling posts. I tested it out on Simple and Atomic (WPCOM and self-hosted) and it worked just fine. All the user needs to do is change the time format in their settings.

On WPCOM sites, go to `Settings > Writing > Composing`,  click the Date and time format header to expand the settings and select the 24 hour time format.

<img width="758" alt="Screenshot 2023-06-02 at 5 46 29 PM" src="https://github.com/Automattic/wp-calypso/assets/96805492/dd76f419-d733-4fa6-aedf-b2c91a4c1d7c">

Now when scheduling a post, the time picker should be 24 hour-based.

<img width="280" alt="Screenshot 2023-06-02 at 5 45 19 PM" src="https://github.com/Automattic/wp-calypso/assets/96805492/d7505814-0a54-4920-b3d4-5ccad71705bf">

For self-hosted sites, the setting is under `Settings > General > Time Format`

<img width="758" alt="Screenshot 2023-06-02 at 5 47 43 PM" src="https://github.com/Automattic/wp-calypso/assets/96805492/79071c08-4d0c-4d89-a1eb-ef78fd759a08">


📌 ACTIONS

Feature request closed
