### ISSUE TITLE
ABTest: replace nudges with ExpandedNudge

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#7777]
#7672 introduced ExpandedNudge component.

We are basing our assumptions on a premise that expanded nudge is better than regular one. But we didnt really test it. It would be nice to uniformly test nudges in regular / expanded version everywhere.

Nudges to test in BOTH versions:

## Themes

<img width="688" alt="zrzut ekranu 2016-08-31 o 09 51 00" src="https://cloud.githubusercontent.com/assets/3775068/18138280/def10856-6f60-11e6-8bc6-d03c74c20361.png">

## Settings

<img width="704" alt="zrzut ekranu 2016-08-31 o 09 51 24" src="https://cloud.githubusercontent.com/assets/3775068/18138283/e0a5353c-6f60-11e6-8724-dda078937e3d.png">

## Stats

<img width="695" alt="zrzut ekranu 2016-08-31 o 09 52 01" src="https://cloud.githubusercontent.com/assets/3775068/18138286/e36bc83a-6f60-11e6-9b3b-67c638abdbed.png">

## Media

<img width="729" alt="zrzut ekranu 2016-08-31 o 09 52 39" src="https://cloud.githubusercontent.com/assets/3775068/18138290/e51b4700-6f60-11e6-8bb9-cc6e28c5d29a.png">

## Questions:

Should we include nudges introduced in #7648, #7651, #7647 in "small" versions as a part of the same test?

CC @rralian @apeatling  - please advise

**Comment by rralian** [comment]
I definitely think it's a good idea to compare an expanded nudge to one of our existing nudges, but I don't think we need to abtest every single one.
