### ISSUE TITLE
Sharing modal looks off visually in mobile viewport

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#77786]
### Steps to reproduce

1. Have a site, which has already published a post so that you don't get other onboarding modals
2. Publish a post, see "sharing modal"
3. Test mobile screen width:

<img width="737" alt="Screenshot 2023-06-05 at 09 26 34" src="https://github.com/Automattic/wp-calypso/assets/87168/bc9ae375-0d00-40d5-ac8e-ad69c56a17da">

Scroll up/down:

<img width="438" alt="Screenshot 2023-06-05 at 09 26 45" src="https://github.com/Automattic/wp-calypso/assets/87168/877b0458-9c5c-4a43-bcd8-8526e25e2bb5">

Desktop version is fine:

<img width="1150" alt="Screenshot 2023-06-05 at 09 28 36" src="https://github.com/Automattic/wp-calypso/assets/87168/1ba8e813-ac3a-42e3-ac89-c201b9acd1c6">

### What you expected to happen

Visually better mobile version:

- Consider removing the image, or change it to different more mobile optimized version. It's silly to need to scroll on mobile.
- Consider removing most of the core Modal component overrides; the core modal is and will get iterated, so more overrides you do, the harder it is to manage those and things will break.
- Not sure what happened to header toolbar compared to core modals where it's visible behind the scrim
- Core version has fixed header (see screenshot below) but the sharing modal doesn't have that:

    https://github.com/Automattic/wp-calypso/blob/b8062d6f337ba951807da5cbe44e8196e3ecb340/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/sharing-modal/index.tsx#L169

    <img width="457" alt="Screenshot 2023-06-05 at 09 42 54" src="https://github.com/Automattic/wp-calypso/assets/87168/1fabcf87-a1b3-4301-b603-18026450664e">

### What actually happened

Visually things look off.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Firefox browser

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS

    Tested on Simple – Reproduced
    Tested on Atomic – Reproduced
    Replicable outside of Dotcom – n/a

📌 FINDINGS/SCREENSHOTS/VIDEO
**AT** - iPhone 12
<img width="776" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/81b79cb5-e16d-4040-b6cf-890707d6bd89">

**AT** - Samsung Galaxy S20
<img width="814" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/9e3d7dcb-2df9-4c91-ae27-4ff572367d46">

**AT** - iPhone SE 2
<img width="811" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/8db712bb-3e92-4c7a-ab67-dd830f6f84f4">

**Simple** - iPhone SE 2
<img width="805" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/3dccec5e-3340-40fb-b28a-83b8e7426466">


📌 ACTIONS
- set priority as Normal.
- assign to YOLO - please let me know if this is incorrect.

**Comment by simison** [comment]
@worldomonation Should be Loop, as they just relased the modal (p7DVsv-hk1-p2). @lessbloat FYI added to team's board. I shared with @roo2 in Slack somewhere earlier already.

**Comment by roo2** [comment]
👀 I'll take a look at fixing this
