### ISSUE TITLE
Launchpad: Create "Drive traffic to your site" task

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#77809]
The "Drive traffic to your site" task should point to `/marketing/connections` with a tooltip (defined in Figma: 9wpoYJrMlYKAKUYvVBMN74-fi-3879_147786)

This one may need clarification from @nuriapenya as I wasn't able to find the Figma tooltip reference.

**Comment by nuriapenya** [comment]
@sixhours This tooltip is already implemented, and I think it appears only once when you create a new site and click the Dive traffic banner. Once you click it away, it never appears anymore:

https://github.com/Automattic/wp-calypso/assets/7931304/4ef507c3-a3dc-4779-a169-caddc1bf9cd3

Theoretically, we don't need to build anything around this - the logic is already there. But if you need the design, I added it here: 9wpoYJrMlYKAKUYvVBMN74-fi-3993_93689

**Comment by andres-blanco** [comment]
The PR linked ended up being a version bump PR.
