### ISSUE TITLE
Launchpad: Create "Confirm your email address" task

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#77808]
For users who haven't confirmed their email address, we should show a task to do so. We already have this task in the site setup list on Customer Home, so we may be able to infer the completion logic from that.

More info in the Tasks spreadsheet.

**Comment by andres-blanco** [comment]
`wpcom_email_verification_complete` is the action that tracks email verification: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Srznvy%2Qirevsvpngvba.cuc%3Se%3Q557q9p0n%23133-og
