### ISSUE TITLE
Editor: Adding captions breaks image links

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#7781]
If an image is already linked to another page, and then a caption is added, the existing link is transferred to the caption text instead of the actual image.

#### Steps to reproduce
1. Starting at URL: WordPress.com/post
2. Add an image, and use the `Insert/edit link` button to link the image to another page (or, paste an HTML image link into the HTML tab)
3. On the Visual tab, select the image, and click the `Caption` button
4. Replace default caption text with your own
5. Publish and view the post
6. The caption will be linked, but the image will not be

Note: If you leave the default caption text of `Enter a caption`, nothing will be linked at all. The caption only gets linked it you add your own text.

#### What I expected

The image should still be linked, even after adding a caption.

#### What happened instead

The link transitions from the image to the caption instead.

#### Browser / OS version

Chrome 52 on OSX 10.11.6

#### Screenshot / Video

<img src="https://cldup.com/MdR8CbT8Eo.gif" />

#### Context / Source

#user-report in 2809239-t

Not as big of an issue for images hosted in the site's media library - adding the caption first, and then creating the link works fine.

If, however, a user is pasting an image link in from an external source directly into the HTML tab, adding a caption is problematic.

**Comment by lancewillett** [comment]
I feel like this has been reported before... but not seeing it with a quick search.

**Comment by formosattic** [comment]
Adding a caption to an image with a link will now completely strip the link from the image, and caption as well.

Here's how it looks like in terms of HTML code.

HTML for image with link:
`<a href="https://wordpress.org/about/logos/" target="_blank"><img class="alignnone size-full wp-image-1283" src="https://s.w.org/about/images/desktops/wp-orange-640x960.png" /></a>`

HTML after adding caption through Calypso editor:
`[caption id="attachment_1283" align="alignnone" width="640"]<img class="alignnone size-full wp-image-1283" src="https://s.w.org/about/images/desktops/wp-orange-640x960.png" width="640" height="960" /> WordPress Logo[/caption]`

HTML after adding caption through WP-Admin editor (it does retain the link element):
`[caption id="attachment_1283" align="alignnone" width="640"]<a href="https://wordpress.org/about/logos/" target="_blank"><img class="wp-image-1283 size-full" src="https://s.w.org/about/images/desktops/wp-orange-640x960.png" alt="" width="640" height="960" /></a> WordPress Logo[/caption]`

#user-report in 285544-hc

**Comment by mobilene** [comment]
For users who host their images externally (e.g., at Flickr) and want the image linked to its source, this solution still requires them to manually re-insert the link back to the image. This is about the same amount of extra work for the user as the workaround to the original condition.

Ideally, adding a caption to an image would retain the link on the image (only), like the behavior in the WP-Admin editor.

**Comment by rachelmcr** [comment]
Closing as this will be resolved in Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
