### ISSUE TITLE
Launchpad: Create "Share your site" task

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#77810]
We don't know what this task does yet; this content is a placeholder.

**Comment by markbiek** [comment]
@sixhours Have we decided what we want to do with this one yet?

**Comment by valterlorran** [comment]
In our sync with Núria and Nelson, we decided to move forward with this task for the next sprint. I will close this one because Nelson created a new issue with more Details(I think we missed this one).

* https://github.com/Automattic/wp-calypso/issues/78856
