### ISSUE TITLE
Odyssey Stats: Fix unexpected chart date label and insights data

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#77817]
I found two Stats related issues when [testing Jetpack 12.2](p8oabR-1e4-p2):

### Unexpected chart date label on the Traffic page
![Image](https://user-images.githubusercontent.com/6869813/243487567-6ca3315e-a0d5-4b4f-9ee0-72af33b927ff.png)

### Unexpected most popular hour on the Insights page
![Image](https://user-images.githubusercontent.com/6869813/243487580-f3349e3a-ba5b-446e-8ba0-13c6c30ce7cc.png)

**Comment by kangzj** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/89369
