### ISSUE TITLE
Track elapsed time on Woo Express loading screen

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#77819]
P2: peapX7-2wb-p2#comment-3198

> To understand this, perhaps we could send an event while the progress bar loads, every 5 seconds or so? If we plot “people who dropped off over time” it’s possible that it may not look like a straight line. If the drop-off rate increases at a certain point, that’s the point where we need to do something to get the user’s attention.

![Image](https://user-images.githubusercontent.com/3747241/243521953-de8b0c87-e88f-48fb-942e-ff5094580fed.png)

### Acceptance criteria

1. Starting from Woo Express loading screen, every 5 seconds, send a track `calypso_signup_loading_elapsed` with props `elapsed: {seconds_elapsed}, step: {current_step}` where `seconds_elapsed` is the total elapsed duration and `current_step` is the current step, ex: `wait-for-atomic`, `processing`, etc.
2. Stop sending the track after 120 seconds since it provides no further value after that point.
3. Register the track as per PCYsg-dY7-p2

**Comment by warrendholmes** [comment]
How would we know when users dropped? i.e. what query/funnel would we look at? (My only hesitation in doing this work is that I believe we have more impactful things to work on)

**Comment by ilyasfoo** [comment]
> How would we know when users dropped?

@warrendholmes I might not know this best, but I think a user who sends this track but does not send a `calypso_signup_actions_submit_step` may signal that they've dropped before completion.

I think the best information we can extract from this track is the breaking point of users who are waiting for the load to finish. i.e.: When does 90% of users drop off? I imagine that could be useful to determine whether the current loading times are problematic.

**Comment by warrendholmes** [comment]
@tckasa or @jonathan-marsan are either of you able to help us understand how we'd query this data? TIA 😄

**Comment by jonathan-marsan** [comment]
I provided some estimates here: peapX7-2H1

**Comment by ilyasfoo** [comment]
Thanks, @jonathan-marsan! Your estimates are helpful. Closing this issue for now since we don't need it and have other better priorities. peapX7-2H1-p2#comment-3279
