### ISSUE TITLE
Permafailing E2E: Click "Continue" and land on the Site Editor

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#77831]
### Spec file

specs/onboarding/setup__site-assembler.ts

### TeamCity ID

10142607

### Logs

```
page.waitForURL: Timeout 45000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/setup__site-assembler.ts:81:15)
```

![image](https://github.com/Automattic/wp-calypso/assets/6549265/2e5d7f7c-f79c-434f-8a96-3dcf81affe6b)

**Comment by worldomonation** [comment]
<img width="1335" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/022fc5fb-e414-43a0-8496-312dfceb7523">

Step used to run in about ~9 seconds before May 26:
<img width="1343" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/c3c88048-154c-44f2-b5ea-04c0e2884357">

**Comment by worldomonation** [comment]
Conversation: p1685752516343169-slack-C1A1EKDGQ

**Comment by worldomonation** [comment]
Related: https://github.com/Automattic/wp-calypso/pull/77152

**Comment by worldomonation** [comment]
Still didn't fix the issue after being raised to 60s. At this point it's not an issue of the test, but rather the endpoint.

**Comment by arthur791004** [comment]
Now the result looks good. I guess we can close this issue 🙂

![image](https://github.com/Automattic/wp-calypso/assets/13596067/79a2a6b6-a056-40a2-8efe-7fb544176bb7)
