### ISSUE TITLE
VideoPress displays upgrade banner on Commerce plan

### ISSUE THREAD

**Issue by john-legg** [Automattic/wp-calypso#77869]
### Quick summary

When adding a video via the VideoPress block to a site with a Commerce plan, the upgrade banner is still visible even though VideoPress is [available for Premium, Commerce, and Business plans](https://wordpress.com/support/videopress/).

https://github.com/Automattic/wp-calypso/assets/96805492/0aea7ce4-2ad7-42b6-b643-28fdaec6b9f2

Uploading via the VideoPress block seems to display an error as well. However, selecting a video from the media library seems to work fine.

https://github.com/Automattic/wp-calypso/assets/96805492/53ee410b-ab43-4a7e-b032-6c17cad88285

### Steps to reproduce

1. On a site with the Commerce plan, create a new post or page and insert the VideoPress block.
2. Verify that the upgrade banner is still visible with the message: `Upgrade to Premium to use this premium block`
3. Click on the `Upload` button and select a video to upload.
4. Verify that the `Failed to upload your video` error is shown.

### What you expected to happen

For the upgrade banner to not be visible and the video to be uploaded without errors.

### What actually happened

The upgrade banner is still visible and uploading a video via the VideoPress block gives an error

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Using the workaround, the video will show on the live site even though the upgrade banner is visible in the editor.

Sites with Premium and Business plans don't display the banner and uploads seem to work fine. Self-hosted sites don't seem to be impacted either. Simple sites have the banner as expected.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm not able to repro this on a test Commerce site of mine:

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/3de45509-4a24-4af5-b25a-bc5a9a8a018c

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- Hi @john-legg ! I think the WPCOM_PURCHASES info in Atomic Persistent Data on your test site may have been out of date, making your editor miss what plan the site was on (_In your recording, the Video block also shows a pink dot above it, indicating it would need an upgrade_), so I updated that via SA for you, and I'm seeing better results now on your site's CLI.  (P9HQHe-14R-p2)

Can you test this again when you get a moment?

**Comment by john-legg** [comment]
> I think the WPCOM_PURCHASES info in Atomic Persistent Data on your test site may have been out of date

AH, I wouldn't have thought to look at that. Thanks for linking to the relavent doc. I learned something new today! I tried everything again and it works fine now, so I'll go ahead and close this issue 😄

**Comment by john-legg** [comment]
> I think the WPCOM_PURCHASES info in Atomic Persistent Data on your test site may have been out of date


AH, I wouldn't have thought to look at that. Thanks for linking to the relavent doc. I learned something new today! I tried everything again and it works fine now, so I'll go ahead and close this issue 😄
