### ISSUE TITLE
Twenty Sixteen - Dropdown menu toggles on mobile don't work as expected

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#77873]
### Quick summary

Dropdown menu toggles don't work as expected on mobile on Twenty Sixteen theme.

First noticed by the user in 6377027-zd

https://github.com/Automattic/wp-calypso/assets/92185881/9201bca2-6d66-48af-a260-c235739b8453

https://github.com/Automattic/wp-calypso/assets/92185881/b4886ec2-e232-45a8-8d5e-b3371d1aba75

### Steps to reproduce

1. Go to Twenty Sixteen theme and open "Live Demo".
2. Select "Mobile" view.
3. Click on the dropdown menu.

### What you expected to happen

Sub-menu items to display.

### What actually happened

Sub-menu items don't display unless they are on the page.

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by danielk-am** [comment]
Current workaround is to add a JavaScript snippet:

```
<script>
        document.addEventListener('DOMContentLoaded', function() {
            var button = document.querySelector('.dropdown-toggle');
            var submenu = document.querySelector('.sub-menu');
    
            button.addEventListener('click', function() {
                button.classList.toggle('toggled-on');
                submenu.classList.toggle('toggled-on');
    
                var ariaExpandedState = button.getAttribute('aria-expanded') === 'false' ? 'true' : 'false';
                button.setAttribute('aria-expanded', ariaExpandedState);
            });
        });
</script>
```

**Comment by karenroldan** [comment]
📌 ACTIONS

- Closed as duplicate of issue https://github.com/Automattic/themes/issues/7092

📌 Message to Author

Thanks for reporting! We'll keep the issue in the Theme repo. Please keep an eye on the ticket to see any updates.
