### ISSUE TITLE
[Earn] Stripe disconnection from Earn does not update the view

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#77898]
When disconnecting Stripe account, the UI does not update as expected (see video).

Also the snackbars stay in place. Not sure if they can be removed programmatically, though.

https://github.com/Automattic/wp-calypso/assets/790558/e800add9-83aa-44d2-a35b-ba37b7b5837f

**Comment by millerf** [comment]
@simison That could be a good quick one for your team when we revamp the Earn page

**Comment by simison** [comment]
Yep, sounds good!

**Comment by cuemarie** [comment]
_As part of KitKat's standard triaging process (PciE2j-1TF-p2), I've added a priority label to this issue and filed it under our DotCom Bug Prioritization Board's Other column, which just lets us know that this needs no further attention from us. Feel free to update priority as you see fit!_
