### ISSUE TITLE
[Block] Post Excerpt - Increase limit to more than 100 words

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#77894]
### Quick summary

A user says in Jan 2023, they were able to able to see excerpts with more than 100 words, they shared a link from [archive.org](https://web.archive.org/web/20230111225142/https://psypolitics.org/) which shows excerpts with more than 100 words. They want the changes to be reverted as now we're only limiting to showing 100 words in an excerpt.

We've tried to make them understand why we're limiting to 100 words as that's the expected behavior of excerpts, but they're not happy with the changes. See if there's something we can do to revert the changes made to it.

Ticket: 6337175-zd-woothemes

### Steps to reproduce

Check the posts under Query Loop block and it shows the excerpts with 100 words only, not more.

### What you expected to happen

They wish to see the excerpts with more than 100 words.

### What actually happened

The excerpt only shows max 100 words.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

The theme used on the site is Hever.

**Comment by cuemarie** [comment]
I believe this change was introduced in Core by:

- https://github.com/WordPress/gutenberg/pull/44964

📌 ACTIONS
- Changed request to `[Type] Feature request` to request increasing the max limit beyond 100 words. 
- Feature request kept

**Comment by annezazu** [comment]
Closing this out as a "won't fix" due to concerns with backwards compatability:  https://github.com/WordPress/gutenberg/issues/49612#issuecomment-2209220813
