### ISSUE TITLE
Signup: Email verification notice is misaligned

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#779]
When you create a new user account, the "Please verify your email address" notice on the `/me/next` page is misaligned.

<img width="947" alt="screen shot 2015-11-25 at 11 03 20 am" src="https://cloud.githubusercontent.com/assets/2036909/11402299/268ec956-9365-11e5-9d5b-9a906801b64c.png">

**Comment by fabianapsimoes** [comment]
Misaligned notices are being tracked here: https://github.com/Automattic/wp-calypso/issues/214

Closing this one as a duplicate.

**Comment by sirbrillig** [comment]
Thanks, @fabianapsimoes. I figured it was there but for some reason I couldn't find it.
