### ISSUE TITLE
Payment plan price field resets when you type any number followed by a decimal point

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#77926]
### Quick summary

When adding a payment plan or edit an existing payment plan, typing a decimal in the price field trips the error `Please enter a price higher than $1.00` and clears out the field. Even if you type in `100.` - the decimal triggers the error.

### Steps to reproduce

1. Open Tools > Earn > Payment > Manage Payment Plan > Payment Plans
2. Add new payment plan or edit an existing one
3. Type in `1000.`

### What you expected to happen

I should be able to continue entering the rest of the price, such as `1000.00`

### What actually happened

The field clears out and `Please enter a price higher than $1.00` appears

https://github.com/Automattic/wp-calypso/assets/27249804/ace66d8a-3f61-4e45-a100-d69f0a23ddf3

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Workaround

The only fix here is to type the entire number, then go back in and add a decimal point in the middle of the number - likely not something a user would guess they could do.

**Comment by cuemarie** [comment]
@simison I see you've been working on Earn pages recently - anything here you can help with? Thanks for taking a look!

**Comment by simison** [comment]
@millerf FYI I added this to our board but great if you also have a moment to look.

**Comment by simison** [comment]
@cuemarie yep, Zap is looking at this UI — generally always ping Team Gold for payment related features.

**Comment by cuemarie** [comment]
Will do, thank you!

**Comment by cuemarie** [comment]
📌 ACTIONS
- Assigned to Other as Team Zap is reviewing this 👍

**Comment by millerf** [comment]
> @millerf FYI I added this to our board but great if you also have a moment to look.

@simison , depends on the timeframe. I don't think we can really trigger this before mid next week. If you get to it earlier, please take it. I add it to our board with low priority...

**Comment by n3f** [comment]
@cuemarie, I'm only seeing this on safari, but wanted to check if you saw this in a different browser.  (Can you confirm this is a safari only issue?)

**Comment by cuemarie** [comment]
Hey @n3f ! I am experiencing this in **Firefox 114.0.1 (64-bit)**, as well as in Safari 16.5 (18615.2.9.11.4)

**Firefox**

https://github.com/Automattic/wp-calypso/assets/27249804/929342ec-2037-4c2f-869c-5a7758007794

Tested my other browsers with the same site, and they did not encounter the issue:

- Chrome 114.0.5735.133 - Issue did not occur
- Brave 1.50.114 & 1.52.126 - Issue did not occur
- Edge Version 114.0.1823.44  - Issue did not occur

**Comment by n3f** [comment]
@cuemarie 🤣 looks like you responded right when I pushed my change!  I checked with the deployed version in firefox and didn't see it so it looks the error should be fixed there too! Thanks for getting back to me.

**Comment by cuemarie** [comment]
@n3f Nice! Working great for me in Firefox now - thank you!
