### ISSUE TITLE
Launchpad: Improve the task list validation function

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#77939]
Make the task list validation function return `null | WP_Error[]` so all the issues can be identified.

More context: https://github.com/Automattic/jetpack/pull/31055#discussion_r1221168911

**Comment by markbiek** [comment]
@valterlorran @daledupreez I wanted to make sure I understood this change to [class-launchpad-task-lists.php](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/jetpack-mu-wpcom/src/features/launchpad/class-launchpad-task-lists.php#L412).

Am I correct that the idea is to change the places that method does `return false;` to return a `WP_Error` and the `return true;` to `return null;`?

And then we need to update everywhere that calls this method?

**Comment by daledupreez** [comment]
Yes, the thinking is that we have no way to identify all issues with a task definition in a single call. As things stand, you need to work through each problem with your task definition one at a time. We likely want to keep the logging/doing_it_wrong code in place until we work out how to handle that better across different site types.
