### ISSUE TITLE
Subscribers Page: Consider exposing `subscribe_as_site_subscriber` in the `/subscribers` endpoint

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#77966]
Depending on how the following conversations resolves: pdDOJh-1Y1-p2#comment-1588, we can consider exposing the `subscribe_as_site_subscriber` value in the `/subscribers` endpoint (D112832-code).

More context: p1686227208937709/1686225973.202869-slack-C02TCEHP3HA

**Comment by yansern** [comment]
Done in Milestone I as part of D113684-code.
