### ISSUE TITLE
Marketplace: Allow users with yearly plans to purchase paid themes with monthly option

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#77964]
Related convo: p1686111686983629-slack-C029JEQRVRT

**Comment by epeicher** [comment]
Summarising here the additional details:

> Does monthly only appear under specific conditions?

Yes, only if the user has a monthly plan. Line of code here https://github.com/Automattic/wp-calypso/blob/bfc4d24402714b493ac74cff427916270624a92d/client/state/themes/actions/add-external-managed-theme-to-cart.tsx#L48

Additionally to the above, it seems that only variants (periods) greater than the originally selected are displayed. This means that if the initial variant is yearly for a product, the monthly period is not displayed as it has a lower interval. Line of code here  https://github.com/Automattic/wp-calypso/blob/bfc4d24402714b493ac74cff427916270624a92d/client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx#L205

We don't think that restriction should apply to Themes, so we could add some logic to apply it only to plans.

**Comment by sirbrillig** [comment]
> Additionally to the above, it seems that only variants (periods) greater than the originally selected are displayed. This means that if the initial variant is yearly for a product, the monthly period is not displayed as it has a lower interval. ... We don't think that restriction should apply to Themes, so we could add some logic to apply it only to plans.

I agree. Here's the request that initiated that feature: https://github.com/Automattic/wp-calypso/issues/69633 / pdgrnI-1Mu-p2 (also noted in the code comment above the restriction). It was specifically for WPCom plans (at the time, I don't believe non-plan products had monthly terms available) so it should be possible to narrow that logic.
