### ISSUE TITLE
Subscribers Page: Replace the `Card` component in the "Empty list" view with the new component

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#77968]
The "Empty list" view (introduced in https://github.com/Automattic/wp-calypso/pull/77844) is using `Card` component[

At the end, we should be using dedicated component instead. At the moment of writing this task, the component doesn't exist. if it isn't available when we get to this task, let's create the component ourselves.

Context: https://github.com/Automattic/wp-calypso/pull/77844#discussion_r1221393828

**Comment by yansern** [comment]
I think the Card component works just fine. Closing task.
