### ISSUE TITLE
Reader: in Firefox, last line of post text loses some of the text for letter descenders (g, j, p, q, y)

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#7798]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com (reader) in Firefox
2. Scroll until post has three lines displayed with letter with descenders (g, j, p, q, y) in the last line

#### What I expected
To see the letters

#### What happened instead
The letters' descenders are cut off visually.

#### Browser / OS version
Firefox 48.0.1 on OSX 10.11.6

#### Screenshot / Video
Firefox is missing descenders

![firefox](https://cloud.githubusercontent.com/assets/128826/18152569/120fcf68-703a-11e6-9d8b-63d6c4f2c0aa.png)

Chrome is OK

![chrome](https://cloud.githubusercontent.com/assets/128826/18152584/1b63959a-703a-11e6-853a-dcaf7390f5ba.png)

#### Context / Source
#dogfooding

**Comment by lancewillett** [comment]
Bug scrub notes:

1. I'm able to repeat in Firefox latest stable on OS X 10.12.1.

<img width="1392" alt="screen shot 2016-10-31 at 14 27 18" src="https://cloud.githubusercontent.com/assets/66797/19872355/87c27ea2-9f76-11e6-9d06-b0c79c82eb62.png">

2. Reader stream is getting a refresh, see #9005. That design does not show the same cutoff descender issue:

<img width="1392" alt="screen shot 2016-10-31 at 14 27 44" src="https://cloud.githubusercontent.com/assets/66797/19872374/9f43a524-9f76-11e6-8a68-75e99d51cb6a.png">

With this change coming soon, I suggest we close this as "works for me".
