### ISSUE TITLE
All sites view: Jetpack site shouldn't have Domains menu

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#77980]
### Quick summary

On All sites view, Jetpack site has domains menu while it shouldn't

cc @vindl can you help triage for Build?

### Steps to reproduce

1. Connect jetpack site to wp.com
2. In all sites view, check the dropdown for jetpack site
3. Click domains
4. Get nowhere...

<img width="549" alt="Screenshot 2023-06-09 at 00 38 58" src="https://github.com/Automattic/wp-calypso/assets/87168/4446d6d8-3a0e-4bd7-b37a-a709e06cdf20">
<img width="1009" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/e35563cf-19ba-44f5-a5e0-4a806cb8b6e4">

### What you expected to happen

No .com specific menu items.

### What actually happened

—

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
Note also "502 bad gateway" in screenshot. We show red error badge in sidebar, maybe we could show something nicer and more actionable at the all sites view, too? 

<img width="238" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/d218f22d-8500-42f4-8b9a-f989b6571c03">
<img width="290" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/e43d2eda-294e-4299-ad48-9e24bd2d8e68">

**Comment by john-legg** [comment]
Hi Mikael 👋 I saw you removed the `High` priority and I just wanted to let you know that I'm adding a priority back to make sure this issue gets properly prioritized and tracked on the board. Feel free to change it to whichever level seems appropriate!

Also moving to the `Other` column for Jetpack (@jeherve)

**Comment by simison** [comment]
Thanks! This should be on Build team who works on that UI and features in the dropdown, not on Jetpack team. cc @danielbachhuber @zaguiini

**Comment by danielbachhuber** [comment]
@john-legg Can you move this to the `YOLO` column?

**Comment by danielbachhuber** [comment]
> Can you move this to the `YOLO` column?

Nevermind, I figured out how to do so.
