### ISSUE TITLE
Assembler - Tracks - Add a prop to know users' window size

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#77994]
Related to #77960 #77962

## What

Let's track the window size when the PA screen loads.

## Why

We want to know what screen sizes are used because it affects users:

- only users on window sizes with `width >= 960 px` can see the assembler CTA and access the assembler because that is considered as `Desktop`. See #77960

- the large patterns preview needs to be scaled to fit the chosen device viewport on the window size. See #77962

## How

Add the props `calypso_signup_viewportwidth` and `calypso_signup_viewportheight` on the events:

- in a new event only when the assembler loads
- only on `calypso_page_view` which already tracks `device_type: desktop`?
- only on `calypso_signup_step_start` which already tracks `device: desktop`?
- global for all events?

cc: @Automattic/lego

**Comment by autumnfjeld** [comment]
Oh, much better idea to create a prop than a new event!!  Nice!!  🧠

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/80171
