### ISSUE TITLE
Assembler - Exclude headers and footers from All category

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#78038]
## What

Exclude headers and footers from All category

## Why

Avoid confusion because users can add them as sections when they should be in template parts.

## How

Check in [use-category-all.ts](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/hooks/use-category-all.ts#L15) to filter by `pattern.categories` excluding `header` and `footer`.

**Comment by arthur791004** [comment]
Do we have any decision on this one? We can move it to this sprint if we want to exclude them from the `All` category 🙂

**Comment by miksansegundo** [comment]
We want to exclude them, it's ready for dev, so I have assigned it to me for this sprint. Thanks!
