### ISSUE TITLE
Sidebar: "View Site" missing for single-site user account

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#7804]
For multi-site users, the "View Site" option shows up in the sidebar, as shown here:
<img width="431" alt="sidebar-missing-view-site" src="https://cloud.githubusercontent.com/assets/15944096/18166513/334f8a3a-707e-11e6-8961-e4889cad3ae9.png">

For single-site user account, "View Site" is not available, see:
<img width="484" alt="sidebar-missing-view-site2" src="https://cloud.githubusercontent.com/assets/15944096/18166397/8581a6cc-707d-11e6-88ec-db072d3d7620.png">

This is an issue for single-site users who prefer to work in the WP-Admin dashboard, and therefore, don't have an easy way to go to their live site.

Would it be possible to have "View Site" available regardless of whether the user only has one site, or not?

460560-chat

**Comment by beaucollins** [comment]
This has been fixed on wordpress.com (this isn't a calypso feature):

![pasted_image_9_1_16__11_23_am](https://cloud.githubusercontent.com/assets/19795/18179287/9c42f286-7036-11e6-8ed9-eeb71969c9ee.png)

**Comment by formosattic** [comment]
Just for reference, it was fixed in 7780-wpcom.
Thanks for the quick fix @beaucollins! :)
