### ISSUE TITLE
Subscribers Page: Launch the Milestone I. version of the page to all EN users

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#78046]
The goal of this task is to flip the switch and make the new Subscribers Page (in its Milestone I. version) available to all EN users in production.

There's a separate task for adding the Subscribers Page link / item to the menu: https://github.com/Automattic/wp-calypso/issues/77531.

If we find that all translations are ready, let's consider launching to all locales instead of EN users only (please see related task: https://github.com/Automattic/wp-calypso/issues/78050).

⚠️ This PR should be merged once we are ready to launch - likely by the end of the Week 24 (June 12 - June 16) ⚠️ 

Related tasks that should go in around the time the Subscribers Page is launched:

- [x] https://github.com/Automattic/wp-calypso/issues/78051
- [ ] Slack announcement (example: p1685012915340789-slack-CB0B2G43X)

**Comment by yansern** [comment]
Did not do a slack announcement. P2 updated with comment.
