### ISSUE TITLE
Subscribers Page: Ship to users of ALL locales.

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#78050]
The goal of this task is to check whether all translations are in before the Milestone I. launch: https://translate.wordpress.com/developer/?path=client/my-sites/subscribers.

If only a few translations are missing by the end of this week, let's ping polyglots for help.

If we can make all translations 🟢 by the end of the week , let's consider launching Milestone I. to all locales. Otherwise let's launch to EN users only.

**Comment by yansern** [comment]
We are doing an EN only release, so this will go to next milestone.

**Comment by yansern** [comment]
Renamed this issue to ship to users of ALL users. We can ship anytime.

**Comment by yansern** [comment]
Changing priority to high and assigning to @TimBroddin. :)

**Comment by TimBroddin** [comment]
I'll make the changes needed to Jetpack
