### ISSUE TITLE
After using the "View Page" notification after a post/page is updated, the editor URL doesn't change in the address bar while navigating.

### ISSUE THREAD

**Issue by christianguerrag** [Automattic/wp-calypso#78059]
### Quick summary

After a page or post is updated, a notification appears on the bottom left side of the screen saying "Post published. View Post".
If the "View post" link is clicked, the updated post loads in the same tab instead of the editor, but the URL still shows something like http://wordpress.com/post/example.wordpress.com/xxxx, if you navigate to any other page or even log out from that tab, the URL still shows the editor URL.

### Steps to reproduce

1. Create or edit a post, and publish the changes.
2. Click on the "View Post" link that appears on the bottom left.

### What you expected to happen

I believe the updated page should open on a new tab, or if opened in the same tab, the URL would change to the public URL.
After clicking the link you should see the published post and not a preview.

### What actually happened

The updated page loads inside the same tab and the URL does not change, it shows the URL of the editor page in the address bar.
You can navigate to other posts or pages while clicking on the links inside the page, and the URL will remain the same, this sometimes causes an error.

https://github.com/Automattic/wp-calypso/assets/46269032/93f626bf-dc28-40d8-88fc-7e9be651b8ae

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested it on a site with a Personal plan and a site with a Premium plan.
Tested it using updated versions of Chrome and Firefox.

It was reported by a user in 6336525-zen, the workaround is to right-click the link and open it on a new tab or window.
I think I've seen a report about it before but couldn't find it.

**Comment by worldomonation** [comment]
s📌 REPRODUCTION RESULTS
Tested on Simple – reproducible
Tested on Atomic – reproudicible
Replicable outside of Dotcom – not tested

When clicking on the "View Post" link, the URL remains the same as the URL while in the editor.
However, as noted in the initial reproduction steps, opening a new tab from the View Post link will load the correct posted URL.

**WORKAROUND**
Clicking on the "View Post" button in the post-publish sidebar will load the correct URL.

📌 FINDINGS/SCREENSHOTS/VIDEO
**Simple**

https://github.com/Automattic/wp-calypso/assets/6549265/567a1b8f-0c58-4151-90b1-2d2e29575a5c


📌 ACTIONS
- maintain Normal priority.
- assign to Non-urgent column.

**Comment by staproehl** [comment]
Any update here? The original user who reported it is asking in a new ticket 7409406-zen

**Comment by allilevine** [comment]
I started investigating after encountering this issue and seeing it raised in Slack. So far I've found that:
- This bug isn't replicable on self-hosted WordPress.
- "View Post" links to the correct URL.
- There was previously a PR to open "View Post" in a new tab: https://github.com/Automattic/wp-calypso/pull/44695 It was reverted. cc @yansern in case you remember why.
- This snackbar notification is part of the editor, but we're modifying it via the iframe.

It's like the correct page is loading within the iframe, but the page url itself doesn't change.

**Comment by noahtallen** [comment]
I looked into that file, and it looks like this is the current code for opening those links:

https://github.com/Automattic/wp-calypso/blob/680131efa7f09ce76465b32a9f7d46eff394fb83/client/gutenberg/editor/calypsoify-iframe.tsx#L394-L402

That gets triggered via these selectors:

https://github.com/Automattic/wp-calypso/blob/80e4de617da7c9994093ed1fc7ef8aa1341c20ae/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L522-L540

**Comment by noahtallen** [comment]
Found a fix: https://github.com/Automattic/wp-calypso/pull/85179

**Comment by simison** [comment]
Any chance we could just remove the iframe for post editor as well, and not need to fix things like these? 😁

**Comment by noahtallen** [comment]
Well, the conversation has been started many times before, but always stalls out for some reason or another. I believe @mattwiebe pushed it pretty far recently; but I'm unsure what the current blockers are.

**Comment by mattwiebe** [comment]
Here was the latest: p58i-eb7-p2#comment-59891 which means that maybe checking in with @vindl and/or the Build Team could be worthwhile

**Comment by vindl** [comment]
The iframe removal is not currently on our roadmap since we have other more pressing priorities. We might tackle it as part of the larger effort to revamp Global Nav, but even the timeline for that project is unclear.

**Comment by noahtallen** [comment]
This bug is weird. The way that we handle links like this where we don't have access to the element ahead of time is to intercept clicks in the editor. For example, if you click "update", our event handler is called.

However, in the snackbar, if you click the area marked with 1, our custom handler is called. But when you click 2, it's not. This prevents the code from opening the link in the right spot:

<img width="301" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6265975/dc7a7993-73f2-4670-af3c-85862ce8611c">

I believe it could be from this code:

https://github.com/WordPress/gutenberg/blob/6bbf33c1eeb634ed404ef8505318852308f0a627/packages/components/src/snackbar/index.tsx#L143-L145

https://github.com/WordPress/gutenberg/blob/6bbf33c1eeb634ed404ef8505318852308f0a627/packages/components/src/snackbar/index.tsx#L76-L87

This could stop the click on the href from propagating to our global handler, which is why my "fix" didn't work.

**Comment by noahtallen** [comment]
PR #85179 should be working now. I used a mutation observer on the list to make give it `target = '_blank'`, since the event listeners aren't working for this one. I think new tab is better behavior for this, but we can also use `_top`
