### ISSUE TITLE
Subscribers Page: Create and publish the heads-up post (Milestone I)

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#78051]
The goal of this task is to create a heads-up post (example p7DVsv-huC-p2) discussing the launch of the Subscribers page (Milestone I).

The heads-up post should be published by Thursday (June 15) or Friday (June 16) - since the new Subscribers page link is expected to become available on the week that start on June 19 (depending on when the latest Jetpack trunk makes it to WPCOM).

**Comment by yansern** [comment]
Done. p7DVsv-hGI-p2
