### ISSUE TITLE
Plans 2023: Tiny visual bug in plans comparison grid

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#78061]
Feature headlines overlap borders in the comparison grid. Reported by @simison in Slack.

![Image](https://user-images.githubusercontent.com/1705499/245124329-7407a77d-eb1b-4f33-add4-2356360ca81f.png)

**Comment by southp** [comment]
This is closed by https://github.com/Automattic/wp-calypso/pull/78143
