### ISSUE TITLE
Launchpad: Layout in setup free flow needs fix

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#78071]
### Details

Starting from https://wordpress.com/setup/free/ seems like the desktop layout should be wider, and the header and footer spacing are off. Tested in Firefox. It should match the Launchpad in other flows.

![Screen Shot 2023-06-12 at 11 45 15 AM](https://github.com/Automattic/wp-calypso/assets/1689238/2989786a-464c-42ca-9ae0-0ef002481361)
![Screen Shot 2023-06-12 at 11 37 15 AM](https://github.com/Automattic/wp-calypso/assets/1689238/b722c375-97b5-46f9-a6c9-c75cae4da4cb)

**Comment by arthur791004** [comment]
Looks like there is a CSS priority issue there, so the width is limited to 1040px

![image](https://github.com/Automattic/wp-calypso/assets/13596067/9325e407-c555-4165-a253-dab3c9154e17)

And the customized header makes it look weird

![image](https://github.com/Automattic/wp-calypso/assets/13596067/f39dfd03-edfb-4fb3-a04a-5f4ed3adb396)

**Comment by lupus2k** [comment]
I confirm the problem is a CSS priority issue, and it's affecting `setup/free` flow but not other flows like `setup/start-writing`

**Comment by lsl** [comment]
I'm seeing it in the design flow `/setup/design-first/launchpad` but only in calypso (not in prod :shrug: )

Note that "Almost ready to launch" is the page title and I don't think it should be getting rendered in these pages at all.

**Comment by lsl** [comment]
Ah ok, that title is just `display:none` instead. :eyes: 

This [display:block](https://github.com/Automattic/wp-calypso/blob/395e53b41d81516399082bba9e6e31f3713a8b9b/packages/onboarding/src/step-container/style.scss#L76) is overriding the [display:none](https://github.com/Automattic/wp-calypso/blob/395e53b41d81516399082bba9e6e31f3713a8b9b/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/style.scss#L10) in the launchpad step depending on which thing gets built / inserted last.

I could repro on calypso hard refresh but after a hot reload the problem would go away.

**Comment by lsl** [comment]
Fix for the header here https://github.com/Automattic/wp-calypso/pull/78163 ~need similar for the page width.~ Switched to full layout instead of relying on css to override wide layout.
