### ISSUE TITLE
Customize default "Coming Soon" Page

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#78093]
### What

I would like to have the option to customize the default WordPress.com "Coming Soon" page to allow users to add a custom logo, background, subscribe, countdown date and time block, and a contact block.

### Why

This will help the users add their brand logo or custom background and a contact form on the page so visitors can contact them while the site is getting ready.

**Comment by syhussaini** [comment]
A recent ticket with this request 6401203-zen

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/65144

📌 Message to Author
- I've shared the ticket link above on the other issue. Thanks!
