### ISSUE TITLE
Assembler - Remove blockGap between header/sections/footer in new assembler theme

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#78097]
Related https://github.com/WordPress/gutenberg/issues/51242

## What
Remove the block gap only between header/sections/footer in BC3:

- from the editor

|BEFORE|AFTER|
|---|---|
|![Image](https://user-images.githubusercontent.com/1881481/245358840-7fac88c5-9afa-4fdc-b591-fbb4ea088ca5.png)|![Image](https://user-images.githubusercontent.com/1881481/245358860-b3006fe3-dbcc-4d79-ad11-9b56c054f22b.png)|

- from the front

|BEFORE|AFTER|
|---|---|
|![Image](https://user-images.githubusercontent.com/1881481/245358760-d257db33-0cb9-464a-9127-0dc0bab81306.png)|![Image](https://user-images.githubusercontent.com/1881481/245358781-c9398ab3-a489-4727-a128-dbbf992ff570.png)|

Note that I changed the background color of the site to orange to show the gap.

## Why

Because users cannot remove that gap easily.

It can be removed by setting the margin as `0` on each pattern container group. However, this option is not viable because there is a [bug](https://github.com/Automattic/wp-calypso/issues/64438#issuecomment-1573236164) that doesn't allow this to work on template parts and the assembler puts the header and footer in template parts.

### A downside

Without the gap between patterns, users won't see the following button to add patterns from the canvas:

![Image](https://user-images.githubusercontent.com/1881481/245357781-2cf95578-6e63-4720-86a4-6a824851092e.png)

Users will have to add patterns using the List view options to add before/after:

![Image](https://user-images.githubusercontent.com/1881481/245357924-b4db4402-ea01-4901-b86f-330b53c2e1f3.png)

## How

**Check first the status of the Gutenberg issue** [Post Content block adds additional margin one can not remove through the UI ](https://github.com/WordPress/gutenberg/issues/51242) because they may remove the gap.
 

We can add [site-wide custom CSS in theme.json](https://href.li/?https://fullsiteediting.com/lessons/how-to-use-custom-css-in-theme-json/) or [style.css](https://href.li/?https://github.com/Automattic/themes/blob/trunk/blank-canvas-3/style.css) to remove the gap **only between header/sections/footer**: 

- from the editor

```
.editor-styles-wrapper :where(.wp-site-blocks) > * {
    margin-block-start: 0;
    margin-block-end: 0;
}
```

- from the front

```
:where(.wp-site-blocks) > * {
    margin-block-start: 0;
    margin-block-end: 0;
}
```

- from the assembler will also remove this gap, we use the variable `--pattern-large-preview-block-gap`.

**Comment by miksansegundo** [comment]
What do you think about this solution? @alaczek @Automattic/lego

**Comment by alaczek** [comment]
Would your solution leave the gap between patterns (within the homepage section) or did we take care of that already?

**Comment by miksansegundo** [comment]
Yes, this solution removes the gap between the first-level patterns, including between homepage sections.

**Comment by miksansegundo** [comment]
@arthur791004, just a note for checking that we load these styles in the assembler from the new theme when it's done. 

For now, we have the [blockGap](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.tsx#L54) added manually on the large preview.

**Comment by miksansegundo** [comment]
About removing the gap between the first-level elements with CSS from Creatio theme.

Here is the current structure of the homepage created with the assembler:

- `<header>`
- `--- gap ---`
- `<main>section/section/...</main>`
- `--- gap ---`
- `<footer>`

Here are the tasks to make it work in all previews (assembler, editor, and site front):

- Add the CSS mentioned in the [issue](https://github.com/Automattic/wp-calypso/issues/78097) to Creatio [style.css](https://github.com/Automattic/themes/blob/trunk/creatio/style.css) to remove the gap in the editor canvas and the front of the site.
- Detect when the assembler is using Creatio to remove the gap in the large preview


The assembler adds the [gap to the header and footer](https://github.com/Automattic/wp-calypso/blob/9efee3b05207f7b12bfc35c67aa88894e081ba11/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.scss#L35) using a variable so it's easy to update.

It'd be better to make it dynamic instead of detecting Creatio to apply this hack in the large preview but we are limited here because we don't use a single iframe with all patterns in the preview. Therefore, I suggest taking the easy path here and iterating later.

**Comment by alaczek** [comment]
Hey Miguel! I added the code to Creatio here: https://github.com/Automattic/themes/pull/7237

**Comment by miksansegundo** [comment]
Thanks Ola, I'll test it soon and update the assembler hack to make sure it works fine.

**Comment by alaczek** [comment]
It actually doesn't :| The gap is only removed in the site preview, but not in the editor or the assembler.

<img width="1625" alt="image" src="https://github.com/Automattic/wp-calypso/assets/4550351/a8428bc5-927c-4b32-a611-4f5d9f0b1fb5">

<img width="1190" alt="image" src="https://github.com/Automattic/wp-calypso/assets/4550351/aa6b2d07-6313-4afb-ad24-c30ada67f038">

<img width="1188" alt="image" src="https://github.com/Automattic/wp-calypso/assets/4550351/e6b9ffe7-d3da-4003-b5a1-559d6cee6251">

This seems to be because our rule from style.css is being overridden:
<img width="842" alt="image" src="https://github.com/Automattic/wp-calypso/assets/4550351/0435a510-b311-4262-8667-ad3e93a82ed1">
