### ISSUE TITLE
Theme Showcase: Activate option shown for retired themes

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#78091]
## Description

As discussed in p1686629515306039/1686174991.330239-slack-C048CUFRGFQ. From @retnonindya:

> This is a GIF screen recording. I’m searching for a retired theme, and I use maxwell as an example.
When I searched for maxwell, I got the result of the WPORG theme. When I checked the three-dots icon, I don’t see Activate.
However, when I went to the theme’s detail page, I noticed a flash of plan information (?) then the info about the theme is retired.
Then, the three dots icon gives the Activate option.

![Image](https://github.com/Automattic/wp-calypso/assets/797888/8364e0be-5587-46e1-9931-343d6d3a809a)

## Acceptance Criteria
- [ ]  The options Activate and Try & Customize should not be available for retired themes.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described!  Tested on a free site, non-admin account, unproxied.
- Before viewing the Info page where the theme is listed as retired, the theme's sticker is `Community`, but after going back, it's tagged with `Premium`.  This means at first it prompts me to upgrade to Business, but later prompts me to upgrade to Premium.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/76f597d3-9700-4aff-974c-24dd00fb926b

📌 ACTIONS
- Assigned to @Automattic/lego

**Comment by taipeicoder** [comment]
Closing via #78231
