### ISSUE TITLE
Assembler - Tracks - calypso_signup_complete isn't firing

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#78092]
## What

The event `calypso_signup_complete` isn't firing when a user goes thru the Assembler flow.

## Why

It should correlate with calypso_signup_step_start with prop flow=site-setup that fires on the intent screen.

## How

Debug it to find out why the event is not triggered by the step framework when the assembler flows are submitted/completed:

- site-setup
- with-theme-assembler

**Comment by miksansegundo** [comment]
@autumnfjeld [mentioned](https://github.com/Automattic/dotcom-forge/issues/2509#issuecomment-1583969691) you are aware of more issues, this issue will focus on firing the event at the end of the assembler flow only.

I found that the event fires unexpectedly when a new site lands in the goals screen after choosing a plan.

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/7879c704-fd7e-4952-a6e8-69d4278751a6)

BTW. here is the event description:

> Fires for all Calypso signup flow completions: For new users signing up for WP.com for the first time, and also for existing users signing up for another website/blog. See FG page /tracks/important-tracks-events/signup-flow-events/

**Comment by autumnfjeld** [comment]
> I found that the event fires unexpectedly when a new site lands in the goals screen after choosing a plan.

Ah, we should fix that too.

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/80304
