### ISSUE TITLE
Plugins: add redirect for a single plugin page for a wpcom site, when switching from a self-hosted site

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#781]
There is no redirect from https://wordpress.com/plugins/akismet/yoursite.com to https://wordpress.com/plugins/yoursite.com. So, when a user attempts to switch from a .org site to a wpcom site on a single plugin page, they see a 'not supported' message.

Steps to reproduce:

1. Go to a Jetpack site that has Manage turned on, and view one of the plugins (either installed already or not). Here's the URL:
https://wordpress.com/plugins/akismet/yoursite.com

![plugins-yoursite com](https://cloud.githubusercontent.com/assets/11487924/10972143/e20d2aa8-83a5-11e5-91b4-0d6883991665.png)

2. Click on 'Switch site' and select a wp.com site instead. Note that the URL changes to this:
https://wordpress.com/plugins/akismet/wpcomsite.wordpress.com

![plugins-wpcomsite](https://cloud.githubusercontent.com/assets/11487924/10972203/30adbbf0-83a6-11e5-8d24-975c99c81966.png)

This is what it looks like for both business & non-business users.

The issue here is that the user should be redirected from https://wordpress.com/plugins/akismet/yoursite.com to https://wordpress.com/plugins/yoursite.com

**Comment by johnHackworth** [comment]
that was the behaviour we had some months ago ... I think it was quite confusing, since the user was redirected without warning... I wouldn't change it back and I would keep the current error screen... ping for thoughts, @enejb @MichaelArestad @rickybanister @beaulebens

**Comment by rickybanister** [comment]
Yeah, this is a little bit tough—I think the best we can do here is swap this rather generic error message for something more helpful:

* A preview of what plugins you can use for business sites (the content preview thing)

* An advert for upgrading to Business for non-business sites (similarly mentioning that you can unlock ecommerce plugins that way)

**Comment by rickybanister** [comment]
It seems like we should just do some further testing on this (there's a store test going right now to display a message similar to what I suggest above) and then we should be able to close this issue as 'wont fix'

**Comment by enejb** [comment]
I agree with @johnHackworth here since. This I think the current implementation works quite well. 
I think maybe improving the messages such as. If the user is on a business site and they land on a .org plugin. They should see an action button that would take them to their list of sites.

**Comment by enejb** [comment]
I am moving this out of the current milestone for now. Since we have no clear idea how to fix this yet.

**Comment by lancewillett** [comment]
This is working as expected now, after recent launch of WordPress.com plugins page in Calypso.

I used steps above, and after going from Akismet page for Jetpack site to a WP.com site, I end up at a URL like `https://wordpress.com/plugins/lancetest35.com` which is accurate.

<img width="1115" alt="screen shot 2016-04-21 at 15 45 14" src="https://cloud.githubusercontent.com/assets/66797/14726575/15b9d598-07d8-11e6-901d-62d8faeeeb38.png">

<img width="1115" alt="screen shot 2016-04-21 at 15 45 26" src="https://cloud.githubusercontent.com/assets/66797/14726576/1a1f7a84-07d8-11e6-9140-0a80bafab848.png">
