### ISSUE TITLE
Flaky E2E: Select the "Try it out" option in the upgrade modal

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#78107]
### Spec file

test/e2e/specs/fse/fse__limited-global-styles.ts

### TeamCity ID

10192655

### Logs

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('body.block-editor-page').locator('.wpcom-global-styles-modal__actions button:first-child')
============================================================
at FullSiteEditorPage.tryGlobalStyles (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts:551:17)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/fse/fse__limited-global-styles.ts:36:3)
```

**Comment by worldomonation** [comment]
<img width="972" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/0904928c-ee04-43e4-a51d-379509c0d3ff">

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/1a297d4e-aeb0-446e-bdf5-b2d0c5bae9ad)

**Comment by mmtr** [comment]
Turns out the issue is caused by the test site unexpectedly using the Blank Canvas theme which doesn't have style variations. It should be fixed by activating the Twenty Twenty-Two theme again (@worldomonation will look into it later).

**Comment by worldomonation** [comment]
Slack thread: p1686646013965979-slack-C1A1EKDGQ
