### ISSUE TITLE
Odyssey Stats: Email Subscribers missing from Stats > Insights Follower count

### ISSUE THREAD

**Issue by julsyd** [Automattic/wp-calypso#78106]
### Impacted plugin

Jetpack

### Quick summary

When viewing Stats > Insights, the follower count only shows WordPress.com followers, and does not include email subscribers. This is confusing, especially since the correct total follower count is shown above that number.

<img width="1195" alt="Screenshot 2023-06-12 at 10 58 57" src="https://github.com/Automattic/jetpack/assets/29981758/9c3a0ec0-9eaa-4da8-a0e7-34baa40fd2a9">

### Steps to reproduce

1. Add at least one email follower to the site.
2. Go to Stats > Insights and check the follower count.

### A clear and concise description of what you expected to happen.

I expected all subscribers (WordPress.com followers and email subscribers) from the current year to appear in the Insights follower count.

### What actually happened

Only WordPress.com followers from the current year appear in the Insights follower count.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
cc @kangzj It looks like I do not have access to the Jetpack Stats - Features and Maintenance project board, so I cannot add that issue to the board.

**Comment by kangzj** [comment]
Hi @julsyd Thanks for reporting this. It is something we need to address for sure. However, the entire red team are working on a priority project now and I don't see the fix an easy one because it likely would include API changes. I've moved it into our todo log and we will tackle it in our next maintenance sprint.

Hi @jeherve Thanks for the ping. I've added crew to the project now.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Quick triaged - replicated on Simple and Atomic WPcom sites as well

📌 ACTIONS
- Assigned to Other as Jetpack folks have this on their radar

**Comment by cometgrrl** [comment]
+1 on this as I noticed this on my new site. It's a tad confusing.

**Comment by kangzj** [comment]
https://github.com/Automattic/wp-calypso/pull/94830
