### ISSUE TITLE
Theme picker: George Lois premium style identical to free style

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#78104]
### Steps to reproduce

1. Logged out /themes
2. Pick George Lois theme
3. Note style tiles, pick between them. See how only some slight spacing changes but otherwise these are identical.

<img width="1686" alt="Screenshot 2023-06-13 at 11 05 02" src="https://github.com/Automattic/wp-calypso/assets/87168/f452ee70-f275-4fad-849c-7104a60750d6">

<img width="1693" alt="Screenshot 2023-06-13 at 11 05 07" src="https://github.com/Automattic/wp-calypso/assets/87168/4349dc7e-2f70-48d2-8ec8-6444d68c95b5">

### What you expected to happen

Significantly more different premium style.

### What actually happened

Identical styles.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
Pinged Marvel team to take a look. p1686643803768049-slack-C048CUFRGFQ

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on WordPress.com/themes – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO

![yU0jL5.gif](https://github.com/Automattic/wp-calypso/assets/27249804/1dd9a6e3-7054-4f57-b13d-e8b71cb385d8)

#### Screenshots/Recordings

📌 ACTIONS
- Assigned to T-rex (no ping as they're already on this thanks to the slack link above)

**Comment by simison** [comment]
Fix at https://github.com/Automattic/themes/pull/7138
