### ISSUE TITLE
Plans 2023: Escape hatch to show all plans in case of tailored plans grid

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#78113]
Related to https://github.com/Automattic/wp-calypso/pull/77667 , https://github.com/Automattic/wp-calypso/issues/77187

**Blocked by** https://github.com/Automattic/wp-calypso/issues/78266 (just the splits in https://github.com/Automattic/wp-calypso/pull/80915 )

As of https://github.com/Automattic/wp-calypso/pull/77667 we are showing the tailored flow's plans when visiting `/plans` with a site created in respective tailored flow. This may include fewer plans than the default list (all current tailored flows show three or four plans).

- Escape hatch to show the default (all plans) list in the grids
- The features in the plans grid should still be newsletter/link-in-bio focused.

cc @lucasmendes-design for updated features for all the plans across all the existing tailored flows (newsletter, link-in-bio)

**Comment by lucasmendes-design** [comment]
> for updated features for all the plans across all the existing tailored flows (newsletter, link-in-bio)

Sorry @chriskmnds but what do you mean by that?

**Comment by chriskmnds** [comment]
> > for updated features for all the plans across all the existing tailored flows (newsletter, link-in-bio)
> 
> Sorry @chriskmnds but what do you mean by that?

@lucasmendes-design This is probably more clear in https://github.com/Automattic/wp-calypso/issues/78114 , where we want to upsell a Business or Commerce (or any plan not included) to a tailored grid view (newsletter/link-in-bio). We'd want to have tailored features for all the plans in order to inject a Business or Commerce plan into that mix, right? (like we did [here](https://github.com/Automattic/martech/issues/1533) for the ones displayed in a tailored flow, but for all)

I'm guessing the same can hold for showing "all plans" via the escape hatch. Shouldn't these also show "newsletter" or "link-in-bio" specific features when visiting with site from respective flow? especially if we'll have them for https://github.com/Automattic/wp-calypso/issues/78114 anyhow 🤷‍♂️

**Comment by chriskmnds** [comment]
After the splits in https://github.com/Automattic/wp-calypso/pull/80915 are merged, this should be unblocked for development. It's still (potentially) pending on getting the updated set of features for plans not shown by default on each of the tailored flows (discussion pdgrnI-2tX-p2 )

However, we can get the basic functionality in and try with the default WPCOM plan features, so to get this moving along -> create a PR, ping folks from tailored flows (e.g. Newsletter) to test, let them raise concerns, address, etc.

cc @southp

**Comment by southp** [comment]
Thanks for mapping the way forward clearly, @chriskmnds . It makes sense to me to sue the default WPCOM plan features to begin with so the whole structure can be put in place first :)

**Comment by southp** [comment]
@chriskmnds I'm wondering if this can be closed now that #83724 is shipped. Could you help me confirm? :)

**Comment by chriskmnds** [comment]
> @chriskmnds I'm wondering if this can be closed now that #83724 is shipped. Could you help me confirm? :)

I am not sure if we completed the task, but we can also close and revisit if it comes up again? Right now, we just revert the intent/context to the default one, which looks fine to me. If the need arises for more, then we can address in a follow up (and hopefully it won't be needed).

A full solution would be to keep the "newsletter" context and have a form of full/default variations of plan mixes. A less full solution would be to keep "some things", like highlight labels, which will also need a careful refactor to avoid ambiguity in the code. Hopefully what we have right now suffices though and we don't need to engineering more around it.

I hope that makes sense? Up to you @southp  :-)

**Comment by southp** [comment]
Ah, you are right that it's not the full solution that we originally envisioned when documenting down this issue. Thanks for clarification, @chriskmnds . 

> If the need arises for more, then we can address in a follow up (and hopefully it won't be needed).
> ...
> Hopefully what we have right now suffices though and we don't need to engineering more around it.

And yeeees, these are exactly what I'm thinking 😆 I think what we have right now has fulfilled the current need, so I'd prefer us to not tinker on the next level of solution until the new business case comes to us. Before that, let's close this and move our focus onto the other things :)
