### ISSUE TITLE
Conversion: Allow a user to upgrade an existing site from /pricing page

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#7812]
via Steve Kryworuka:

Occasionally we run into users who wanted to upgrade an existing site but end up creating a brand-new site. I had a user walk me through how it happened. He went to WordPress.com/pricing which only gives users an option to create a site with the upgrade:

![screen-shot-2016-09-01-at-7-09-27-am](https://cloud.githubusercontent.com/assets/1464705/18175155/143e31f4-7025-11e6-8fe6-ea4184a33f6c.png)

There should be a way here to detect there is a logged in user, and show an option for selecting and upgrading an existing site.

**Comment by apeatling** [comment]
As a sidenote, this also tells me that the flows for upgrading when logged in are not clear enough. This lends well to ideas for: https://github.com/Automattic/wp-calypso/issues/7327

**Comment by kriskarkoski** [comment]
Short-term could we redirect logged-in visitors from /pricing to /plans (the reverse of our logged-out plans->pricing redirect)?

**Comment by rralian** [comment]
> Short-term could we redirect logged-in visitors from /pricing to /plans (the reverse of our logged-out plans->pricing redirect)?

It's possible, but the difference in UI/navigation is pretty significant. These logged out pages are pretty inconsistent anyway though.

**Comment by rralian** [comment]
@josemarques @mattm I think this is something to handle in the php side. Do you mind looking into this?

**Comment by mattm** [comment]
@josemarques: @rralian and I chatted on Slack and think the easiest way to solve this for now is to simply redirect logged in users from /pricing to /plans like @kriskarkoski suggested.

Can you make that update when you have time?

**Comment by artpi** [comment]
I am sorry, I did not understand that this task is meant for @josemarques ...
I just grabbed something unassigned...

In any case, I created a diff D2728-code for this change.

**Comment by mattm** [comment]
@artpi Nice, thanks!

**Comment by artpi** [comment]
D2728-code  merged and deployed, closing the task

**Comment by rralian** [comment]
Reopening this to track a little tweak... I think we should redirect the user to their primary site, rather than just dropping them into `/plans`.

**Comment by supernovia** [comment]
Our forum volunteers are having some trouble with this switch. They want to check pricing but have to select a site to do so.

Also, users who haven't created a site yet and just want to look at plans first see this:

![image](https://cloud.githubusercontent.com/assets/3476361/18403902/ab16b56c-76a4-11e6-9ff4-f782b45d5c71.png)

**Comment by rralian** [comment]
bumping this to bug level

**Comment by supernovia** [comment]
You can see the volunteer feedback here:
https://en.forums.wordpress.com/topic/changes-to-plans-and-pricing-links

> if while logged in you click on the Plans link here https://wordpress.com/pricing/ you are now redirected to the New Dash to select a site. Before this change, logged in users also saw the full pricing plan that now only logged out users see.

> 

> I will not be instructing any users without blogs to jump through any hoops like opening the link in a Private/Incognito window. Many do not even know how to set up their browsers and I will not be providing that support.

>
