### ISSUE TITLE
Launchpad: Checklist shows up empty on a test site

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#78121]
The Launchpad on this particular test site shows up whenever the user goes to `/home`, indicating it is not complete, but the Launchpad itself shows no tasks:

![image](https://github.com/Automattic/wp-calypso/assets/2124984/276175ce-8a19-4a28-a2a1-40dfe807d3fc)

Site details: p1686632135475179-slack-C057AH42XQD

**Comment by cuemarie** [comment]
📌 ACTIONS
- Assigned to @Automattic/serenity as folks are already looking into this via slack

**Comment by sixhours** [comment]
The site in question had its settings messed up due to installing an old version of Jetpack, so I don't think we can use it to accurately troubleshoot the issue.

I'm going to close as can't reproduce, but if a user runs into this problem we will look into it again.
