### ISSUE TITLE
Bug: Template Editor switches to Content Editor after adding a new block

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#78131]
### Quick summary

When using the new content X template editing experience introduced in https://github.com/WordPress/gutenberg/pull/49980, I ran into a very fraught experience when trying to add a new block into a template. While in Template Editing mode, using the "Add Before"/"Add After" options to add new blocks will add the block, but it will also switch the editing experience to the Content Editing mode.

Since the block was added to the Template, it can't be edited while in Content Editing mode. When switching again to Template Editing, typing anything will revert back to Content Editing.

### Steps to reproduce

1. Start at Appearance > Editor > Pages
2. Open a page to edit
3. Click on the Page tab in the right sidebar
4. Click on "Edit template"
5. Select any block in the template and use the block toolbar to "Insert Before"/"Insert After"
6. The editor switches back to page content editing unexpectedly.

### What you expected to happen

The behavior in core is like this:

https://github.com/Automattic/wp-calypso/assets/14153300/06195ad6-4e46-401b-b412-2e5ddbbeb17d

### What actually happened

Trying to edit a block added to the template switches the editing experience back to content editing.

https://github.com/Automattic/wp-calypso/assets/14153300/2859b1fd-e995-4c64-a2fd-4a5a95fae71d

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Gutenberg 16 RC 4

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described. Editing from Appearance > Editor > Templates > Page works fine, but if I am working within the Content editor, and then move to add something to a template, I can no longer add/edit blocks on the template, it keeps switching me back to the content editor, where I then can't edit what's added to the template. 

Testing on free Edge site:

- Gutenberg: v16.0.0-rc.5
- Editing Toolkit: 3.68337
- WP AMP: 2.0.5
- CoBlocks: 2.18.1-simple-rev.4

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/711b13b9-78cb-47ec-9aa8-e50a583b0265

📌 ACTIONS
- Scrubbed, awaiting assignment
- Returned priority to BLOCKER

📌 Message to Author
- Thanks @liviopv for reporting and escalating this here: p1686682258996299-slack-CBTN58FTJ

**Comment by cuemarie** [comment]
📌 UPDATE
- Active investigation happening here: p1686677477797309-slack-CBTN58FTJ

📌 ACTIONS
- Moving to OTHER
