### ISSUE TITLE
Reader Refresh: emojify full post content

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#7814]
Enable emoji in the new `reader-full-post` block.

**Comment by blowery** [comment]
We might want a new `<Emojify>` component that does this using lifecycle methods. Maybe we already have one?

**Comment by blowery** [comment]
Looks like there is one in `components` but it wraps the content in a span. However, it does use a custom CDN, which we should probably work into whatever method we use to do this.

**Comment by bluefuton** [comment]
Fixed in #7843.
