### ISSUE TITLE
Free plan visible in the `/with-theme` flow after selecting a Premium theme

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#78165]
Originally reported by @lsl in p1686716979414759/1685462561.611169-slack-CKZHG0QCR

#### Steps to reproduce

1. Go to [wordpress.com/themes](http://wordpress.com/themes) while logged out and pick a Premium theme.
2. For simplicity, copy the URL of the "Pick this design" button and paste it in a logged-in browser session (it should be something like `wordpress.com/start/with-theme?theme=yuga&premium=true&theme_type=premium`).
3. Proceed with the onboarding until you get to the "Choose a plan" step.

#### What I expected

Free plan shouldn't be visible because I selected a Premium theme that requires the Premium plan or higher.

<img width="1711" alt="Screenshot 2023-06-14 at 08 56 27" src="https://github.com/Automattic/wp-calypso/assets/1233880/bd02fcd6-95ec-430a-976c-1d952a6586c7">

This is how it used to work as of https://github.com/Automattic/wp-calypso/pull/76040 but, after bisecting the recent changes, looks like a regression was introduced in https://github.com/Automattic/wp-calypso/pull/76768 (cc @chriskmnds).

#### What happened instead

Free plan is visible.

<img width="1498" alt="Screenshot 2023-06-14 at 08 53 39" src="https://github.com/Automattic/wp-calypso/assets/1233880/879859b5-c69d-4872-9b3b-798522612be9">

**Comment by chriskmnds** [comment]
> This is how it used to work as of https://github.com/Automattic/wp-calypso/pull/76040

Is the reference commit correct? You obviously checked, so must be doing something wrong on my end. I checked out https://github.com/Automattic/wp-calypso/commit/1b348b922a913d6fe207dd846e5b7939b24e9256 and visited `/start/with-theme?ref=calypshowcase&theme=varese&premium=true&theme_type=premium`. This is what I see on plans step (personal plan visible):

<img width="1353" alt="Screenshot 2023-06-14 at 12 43 47 PM" src="https://github.com/Automattic/wp-calypso/assets/1705499/1b38de9d-cb14-4b60-8b3d-9b559bc0be9a">

**Comment by chriskmnds** [comment]
> Originally reported by @lsl in p1686716979414759/1685462561.611169-slack-CKZHG0QCR 
> #### What happened instead
> Both Free and Personal plans are visible.
> 
> <img alt="Screenshot 2023-06-14 at 08 53 39" width="1498" src="https://user-images.githubusercontent.com/1233880/245702124-879859b5-c69d-4872-9b3b-798522612be9.png">

> Both Free and Personal plans are visible

It's only the Free plan that's visible in the image. Also same in production when I visit `/start/with-theme?ref=calypshowcase&theme=varese&premium=true&theme_type=premium`. Personal plan isn't shown.

Sounds like the issue boils down to not hiding the free plan. The rest seems to work for me e.g. visiting plans step with free theme, shows personal. Can you please confirm? cc @autumnfjeld

**Comment by mmtr** [comment]
> Is the reference commit correct? 

Sorry, wrong PR! I forgot we excluded the ineligible plans in this follow-up PR: https://github.com/Automattic/wp-calypso/pull/76306

> It's only the Free plan that's visible in the image. 

Nice catch! Totally overseen that – should be corrected now.

**Comment by chriskmnds** [comment]
> > Is the reference commit correct?
> 
> Sorry, wrong PR! I forgot we excluded the ineligible plans in this follow-up PR: #76306
> 
> > It's only the Free plan that's visible in the image.
> 
> Nice catch! Totally overseen that – should be corrected now.

Gotcha, thanks. I thought something was off :-)
Created https://github.com/Automattic/wp-calypso/pull/78172 which hopefully fixes the Free plan showing when it shouldn't 🤞

**Comment by autumnfjeld** [comment]
Thank you for fixing!

**Comment by lsl** [comment]
Is there a limit on which themes you can choose in this flow? I happened to choose "geologist slate" theme and it kicked me to theme (re-)selection in the design picker step instead of variation selection like it does for other themes.

**Comment by mmtr** [comment]
@lsl All themes should be available. The issue you described for Geologist - Slate looks like a bug. I don't know why Geologist - Blue, Geologist - Cream, Geologist - Slate, and Geologist - Yellow are listed as independent themes in the Theme Showcase, because they are actually style variations of the Geologist theme. They are are definitely not listed as separate themes in the Design picker, which is why you need to re-select the theme.

**Comment by fushar** [comment]
@lsl It's a bug; we've logged it here:

- https://github.com/Automattic/wp-calypso/issues/78556

**Comment by autumnfjeld** [comment]
>  I don't know why Geologist - Blue, Geologist - Cream, Geologist - Slate, and Geologist - Yellow are listed as independent themes in the Theme Showcase, because they are actually style variations of the Geologist theme. 

@mmtr  They exist as separate themes here: fbhepr%2Skers%2Sjcpbz%2Qcho%2Qgurzrf%2S-og

![image](https://github.com/Automattic/wp-calypso/assets/5665959/180f6751-a016-4820-8e2d-c83484f448e1)

Also, they are on the chopping block :) 
See this draft post: pekYwv-284-p2
