### ISSUE TITLE
Launchpad: Add "Customize your domain" task to the "Keep Building" task list

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#78198]
Instead of re-using the `domain_upsell` task, we should create a new task in the "Keep Building" task list that effectively behaves like a domain upsell, but has a different title, "Customize your domain".

It's a nuanced change, but the user has already completed "Choose a domain" during onboarding because that includes free domains (like *.wordpress.com). Now we want them to customize their domain if they haven't already.

**Logic:**

* This task should be shown to users who are on a free plan who did not purchase a custom domain during onboarding.
* This task should be shown to users on paid plans who selected a custom domain during onboarding, and it should be shown as completed.

As part of this we should also remove the `domain_upsell` task from the "Keep Building" task list.

Ref: pdtkmj-1v1-p2#comment-2687 and p1686835495744379-slack-C0Q664T29

**Comment by markbiek** [comment]
Jetpack PR: https://github.com/Automattic/jetpack/pull/31493
Calypso PR: https://github.com/Automattic/wp-calypso/pull/78545
