### ISSUE TITLE
Launchpad: Make task list status available on the API endpoint.

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#78194]
We have the older `launchpad_status` prop, but that doesn't reflect the completion status of a single task list. We should add that to the API so we can access it on the front end (for example, adding it as a Tracks prop, or showing/hiding a task list based on completion status).

**Comment by markbiek** [comment]
Talked to @sixhours and it seems like we don't need this. We found a different way to get this information on the front end.
