### ISSUE TITLE
Stats: No today/yesterday toggle on individual meta boxes

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#7820]
Old stats (currently in Jetpack) include a toggle on the various stats meta boxes for today/yesterday. This would be nice to have in Calypso as well.

![screenshot](https://cloud.githubusercontent.com/assets/831377/18179620/520047b2-7051-11e6-9846-8afa17b37157.png)

**Comment by chaselivingston** [comment]
2813764-t

**Comment by timmyc** [comment]
The implemented update for this feature was to introduce the arrow date navigation on stats period pages:

<img width="1070" alt="stats_ _trout_bummin_ _wordpress_com" src="https://user-images.githubusercontent.com/22080/30084753-831aaa26-9248-11e7-8e56-229824df639b.png">

A "Try" branch was done with per-module yesterday links and we opted against that route.

Closing this out.
