### ISSUE TITLE
Odyssey Stats: Add version-dependent support for subscriber stats highlights

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#78211]
>- Let's create a follow-up PR for handling the lack of `sites/:siteId/subscribers/counts` API endpoint for Odyssey.
>    - We can use the same `getJetpackStatsAdminVersion` comparison technique used in #77935.
>    - If there is API support, we'll render the highlights as-is.
>    - If there isn't, we can blank out the "All time stats" card counts and recommend that the user upgrade their Jetpack plugin.

From [#78082](https://github.com/Automattic/wp-calypso/pull/78082#issuecomment-1592037326).

**Comment by kangzj** [comment]
Fixed with https://github.com/Automattic/wp-calypso/pull/78297

We'll create several follow up issues to improve the section.
