### ISSUE TITLE
Reader Refresh: Full Post: show featured image in content where available

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#7822]
@blowery says: 

"if there’s a canonical and it’s an image and it’s either the feature or the post thumb, show it"

We should suppress the image if it already appears in the post content.

**Comment by blowery** [comment]
Yup, same logic as in the current full post, except we're lifting the size requirement.

**Comment by bluefuton** [comment]
Example of a post where the featured image is missing:

http://calypso.localhost:3000/read/feeds/52421555/posts/1140434279
