### ISSUE TITLE
Flaky E2E: Click on Insights tab

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#78255]
### Spec file

test/e2e/specs/stats/stats__insights.ts

### TeamCity ID

10214207

### Logs

```
page.waitForURL: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
at clickNavTab (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/element-helper.ts:91:28)
    at StatsPage.clickTab (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/stats-page.ts:28:3)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/stats/stats__insights.ts:31:4)
```

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/621b10d0-9e81-4819-b1cb-9c1ae3bb36b4)

https://github.com/Automattic/wp-calypso/assets/6549265/818fc040-b4b7-4c8e-b5c6-fa2568acc421

**Comment by worldomonation** [comment]
Caused by https://github.com/Automattic/wp-calypso/pull/77935.

**Comment by worldomonation** [comment]
<img width="1518" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/e8f4b4d0-18d2-4859-9891-fb36dc89361d">

**Comment by jsnmoon** [comment]
Cc @Automattic/red, as this reverts the release of a significant feature release.

**Comment by worldomonation** [comment]
Fixed fully in https://github.com/Automattic/wp-calypso/pull/78304.
