### ISSUE TITLE
Conversion: add tracking event for new user creation

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7826]
From what I can see there is no tracks event that gets fired when a new user is created in the signup flow. There are some tracks events for which we can infer that a new user has been created, but it's not obvious. I believe this is `calypso_signup_step_complete` where `step_name === 'user-survey'`.

There's `calypso_signup_complete`, but that gets fired whether this is a new user or not. I think we need a `calypso_user_registration_complete` event that we can use to better understand our funnels.

**Comment by lamosty** [comment]
> I believe this is calypso_signup_step_complete where step_name === 'user-survey'.

From what I can see it's actually `step_name === 'survey-user'`.
