### ISSUE TITLE
Jetpack connect screen loading screens and minor UI update

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#78267]
### Issue description

Core profiler related fixes in Jetpack connection flow

![Image](https://user-images.githubusercontent.com/3747241/246136872-e01c4f26-ce03-42e5-a9fb-a880a3ef4c8c.png)

![Image](https://user-images.githubusercontent.com/3747241/246136804-bd0c3de9-b3f9-42c2-86e8-b04f4e72ab74.png)

### Acceptance criteria

1. Vertically center profile logo according to some texts Y5pUYSJPsGEud1vknUZhi8-fi-1911_36557
2. Implement loading screens in Jetpack connect Y5pUYSJPsGEud1vknUZhi8-fi-1911_36598

**Comment by chihsuan** [comment]
We should create a reusable loading screen component that can be used across different repositories! 😄 It seems that we'll need similar loading screens for Customize your store project (Mrk6SERPZ4KrFHSjM0a8TK-fi-487_85655).

**Comment by ilyasfoo** [comment]
We should create the component in a reusable package

**Comment by chihsuan** [comment]
I will work on implementing the Jetpack Connect loading screens first.

Created a task for creating the reusable component. https://github.com/woocommerce/woocommerce/issues/38935

**Comment by ilyasfoo** [comment]
This was addressed by the PR linked above
