### ISSUE TITLE
Launchpad: Update the "Claim your free one-year domain" task copy for mapping existing domains

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#78270]
This one is a bit subtle and edge-case-y. If a user maps an existing domain, that also counts as using their free domain credit, so "Claim your free one-year domain" could be confusing.

If a user maps an existing domain, let's mark this task completed and change the task copy to "Connect a domain".

Ref: pdtkmj-1v1-p2#comment-2710

**Comment by sixhours** [comment]
> If a user maps an existing domain, does that count as having used their free domain credit? If so, this task is behaving as expected (although the wording might be a bit confusing for users).

Based on the [support documentation](https://wordpress.com/support/domain-connection-vs-domain-transfer/#connecting-a-domain), it looks like the free domain credit counts for either purchasing a new domain 
OR mapping an existing domain

So this behavior is technically accurate, but the wording may be confusing for folks who intend to map an existing domain. /cc @nuriapenya

**Comment by nuriapenya** [comment]
@sixhours ahh, I see, it makes sense though.

In this case, we could rename the completed task by: `Connect a domain` (and make sure it is checked).

In general, we haven't worked on the Launchpad for the connect/transfer domain onboarding flow. Maybe it's a good time to look into it, especially since is very connected to post-launch. I'll add it to my list! 🙏🏽

**Comment by sixhours** [comment]
> In this case, we could rename the completed task by: Connect a domain (and make sure it is checked).

I've updated this ticket to reflect this, thanks Núria!

**Comment by daledupreez** [comment]
@sixhours and @nuriapenya, I think we need to be careful here, as there are two separate things involved.

1. If a user has a paid plan, their plan entitles them to connect a domain they already own. This is called out in our support docs [here](https://wordpress.com/support/domains/connect-existing-domain/#domain-connection-overview).
2. If a user has a paid plan with a yearly or longer subscription period, they are entitled to claim a free domain registration for one year. That's called out [here](https://wordpress.com/support/domains/register-domain/).

We need to be clear about what we're asking the user to do, and what the outcome is. If they already have a domain, they can still purchase another free domain, and we want to encourage them to take advantage of the offer.

**Comment by sixhours** [comment]
> We need to be clear about what we're asking the user to do, and what the outcome is. If they already have a domain, they can still purchase another free domain, and we want to encourage them to take advantage of the offer.

Ahhh, OK, that adds even more confusion to this logic. 😆 We should probably go over all the domains-related task variations to make sure we're on the same page, and create separate tasks for each scenario so we're not having to do lots of complex logic within one task.

**Comment by sixhours** [comment]
Since this is an edge case and we're unlikely to prioritize it soon, closing.
