### ISSUE TITLE
Reader: ask for confirmation when leaving the single-post view when a comment has been typed but not yet submitted

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#783]
Steps to reproduce:
1. Go to https://wordpress.com/
2. Click on a post
3. Start typing a comment
4. Click the back arrow or try to leave the page without submitting the comment

<strong>Result:</strong> if you accidentally leave the comment page too soon without submitting your comment first, it is destroyed without notice.

Notes from shaunandrews 

<blockquote>An easier solution than saving the content is to ask for a confirmation when closing the modal—but only when there's been a comment typed (but not submitted). So, for example, here's a scenario:

1) You open the full post and decide to leave a comment. You click/tap on the input and start typing.
2) You accidentally click/tap outside the modal or hit esc
3). Rather than just closing the modal (or doing fancy tricks to save the content) some sort of confirmation dialog is displayed asking something like "It looks like you're in the middle of writing a comment. Are you sure you want to close this post and lose your unsaved comment? Yes | No"</blockquote>

**Comment by alisterscott** [comment]
11 May 2017 Bug Scrub - Confirmed still an issue
