### ISSUE TITLE
Blog onboarding: celebration step text alignment

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#78301]
Looks like text alignment / margins and page width similar issue to https://github.com/Automattic/wp-calypso/pull/78219 and https://github.com/Automattic/wp-calypso/pull/78163.

Only effects development loading.

When completing the `/setup/blog` flow we see this css issue on the celebration step after launching the site. (To access this flow you need to start with a new user or a user with all sites deleted)

Expected:

![Image](https://github.com/Automattic/wp-calypso/assets/811776/bfbfa9e1-b04b-4102-8fbb-a049baaf4c71)

Got:

![Image](https://github.com/Automattic/wp-calypso/assets/811776/6e4598da-3a7a-41c7-baec-b5b9db6561a4)

**Comment by lsl** [comment]
Some context p4TIVU-awY-p2#comment-11854 

I'm suspecting these are showing up in some way due to calypso's newish hot reloading and maybe something to do with some of the launchpad code being moved out to a package changing the order things load?

Since this doesn't seem to be causing an issue in prod I'm thinking we should leave this one in place until the next sprint so @mreishus has time to take a look.

**Comment by mreishus** [comment]
I haven't been able to replicate, even when editing `client/landing/stepper/declarative-flow/internals/steps-repository/celebration-step/styles.scss` or `client/landing/stepper/declarative-flow/internals/steps-repository/setup-blog/styles.scss` to force hot reloading:

![2023-06-16_10-09](https://github.com/Automattic/wp-calypso/assets/937354/0a66305b-7ced-4b49-8e58-653ea5013b95)

**Comment by lsl** [comment]
:grimacing:  And now I can't repro either. Lets close for now, unless anyone else in @Automattic/explorers is still seeing this?

I would like to understand this but oh well!
