### ISSUE TITLE
wordpress.com/plans: Make `Downgrade` button more functional

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#78330]
![Image](https://github.com/Automattic/wp-calypso/assets/12505355/695c8808-9122-44d7-a157-995c5817f8b3)

Currently, the `Downgrade` button in the plans page is not clickable and only has a tool-tip to contact support. It would be better to make this a button that directs the user to `wordpress.com/help` or opens a chat window directly.

**Comment by michaeldcain** [comment]
This is a good suggestion. @Automattic/martech is currently working on the /plans page, so let's see if they have the bandwidth to take this on.

**Comment by southp** [comment]
Thanks for the heads up, @JessBoctor @michaeldcain . It's on our radar here: https://github.com/Automattic/martech/issues/1458. What we plan to do is very much like the suggestion here. If there is anything further, please feel free to let us know.

**Comment by JessBoctor** [comment]
Closing in favor of martech's issue.
