### ISSUE TITLE
Assembler - Large pattern preview - Resize observer loop with scrollbars

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#78357]
## What

The scrollbars trigger the content resize observer in a loop. See for the implementation of the observer #77962

https://github.com/Automattic/wp-calypso/assets/98343583/4979bd99-9c61-45dd-bc48-6995b6ba0710

## Why

This is a bug, can't reproduce it. Maybe is related to forcing the scrollbars to show?

![Image](https://user-images.githubusercontent.com/1881481/246751399-2c696513-c2c0-4ef1-a4a8-f60053a50a58.png)

## How
- Find steps to reproduce it
- Add a check to avoid the loop if the width changes because of the scroll

**Comment by lucasmendes-design** [comment]
I think it could be related to the scroll. 

I noticed one strange thing. I have here two screens (Second Monitor and Macbook Pro). The problem happens only on my second monitor. Using the Macbook works fine. The main difference was the vertical size. On my second monitor, there is a scroll and on my Macbook don't have the scroll component. 🤔

**Comment by taipeicoder** [comment]
@Automattic/lego let's look into a way to reproduce this consistently.

**Comment by cuemarie** [comment]
Happy to check if I can repro this during KitKat triaging today, as well!

**Comment by lucasmendes-design** [comment]
I found out how to reproduce this bug, but not all patterns have this behavior. 

- Choose a basic pattern.
- Resize the browser resolution until the scroll almost disappears.

https://github.com/Automattic/wp-calypso/assets/98343583/a11cdb48-4c16-49cb-bc52-364d18a62199

https://github.com/Automattic/wp-calypso/assets/98343583/288182e8-518a-4eb2-bf54-704512988165

**Comment by miksansegundo** [comment]
A view in Gutenberg is having a similar [issue](https://github.com/WordPress/gutenberg/issues/52027)

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/80800
