### ISSUE TITLE
Subscribers Page: Add ability to filter by Free & Paid users.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78360]
User should be able to filter by Free & Paid users. The dropdown menu should have 3 options: All, Paid & Free.

If needed, please create a separate GH issue for modifying API endpoint and add the GH issue to this milestone. https://github.com/Automattic/wp-calypso/milestone/437

<img width="1131" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/5efb5a58-63b6-41e0-8b89-1e275487ddd7">

**Comment by ivan-ottinger** [comment]
Why is this task blocked 🔴 ? 🤔  (just trying to understand if it can be worked on)

**Comment by TimBroddin** [comment]
I guess this task can be closed now?
