### ISSUE TITLE
Domain auto renewal styling overflow

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wp-calypso#78379]
### Quick summary

When a domain is purchased, and a user clicks to disable renewal, the popup has some styling/overflow issues

### Steps to reproduce

1. Purchase a domain
2. Once it's activated, disable renewal

### What you expected to happen

You'll be greeted by this popup , where `need help` is over the CTA buttons

![Monosnap Domains ‹ WC Pay Safe Mode Test — WordPress com 2023-06-15 13-09-49](https://github.com/Automattic/wp-calypso/assets/2484390/f78422e4-790b-4079-a73c-07e1dea294f0)

### What actually happened

...

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by klimeryk** [comment]
Thanks for reporting! Possibly related to my changes in https://github.com/Automattic/wp-calypso/pull/78173. I'll have a look.
