### ISSUE TITLE
Launchpad: "Claim your free one-year domain" task is not translated

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#78393]
This is likely a timing issue while we wait for the translations to come through for a new string, since the other tasks may have had strings in GlotPress already, but we should confirm that the string is in GlotPress waiting to be translated.

![screenshot-2023-06-19-at-3 53 32-pm copy](https://github.com/Automattic/wp-calypso/assets/2124984/9728981c-6469-4a9a-837c-08b9fdaccaf2)

**Comment by markbiek** [comment]
Confirmed that this is in the queue for translation.
