### ISSUE TITLE
Domain upsell: Update copy and styles for My Home > Domain Upsell CTA

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#78429]
Context: p1687248914560209-slack-CKZHG0QCR

Acceptance criteria:

- [x] Fix track event for cancel / continue CTA
- [ ] Follow the context for the new copy
- [ ] Update copy
- [ ] Update styles

**Comment by lupus2k** [comment]
[PR created](https://github.com/Automattic/wp-calypso/pull/78759) for Fix track event for cancel / continue CTA

**Comment by lupus2k** [comment]
An A/B test will be created to follow the copy changes.
Slack discussion: p1688001585410109/1687226388.550139-slack-C029GN3KD
