### ISSUE TITLE
Classic Themes: Duotone filter not applied on live site

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#78442]
_2023-08-31 - reported anew in /gutenberg repo here: https://github.com/WordPress/gutenberg/issues/54099_

### Quick summary

On sites using a classic theme, Duotone filters apply in the post editor, but don't appear on the live site

### Steps to reproduce

1. Activate a classic theme like **Twenty Twenty**
2. Open a new post and add an image block
3. Add a duotone filter
4. Save and view the post

### What you expected to happen

The duotone filter to appear just like in the editor.

### What actually happened

No duotone is applied. 

**Editor**
![Markup on 2023-06-20 at 10:37:04](https://github.com/Automattic/wp-calypso/assets/27249804/15ff16a6-5d4d-41aa-91b8-751a35b30320)

**Live Site**
![Markup on 2023-06-20 at 10:38:26](https://github.com/Automattic/wp-calypso/assets/27249804/d758de45-41d7-472c-a27d-22c7cbec8f51)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Tested on Atomic site, Firefox browser

Duotone worked as expected on same site using theme TT3

**Comment by cuemarie** [comment]
Recent report from #74357 : 

- Chat: 6427916-zd-woothemes (Libre 2 theme)
- Follow Up Ticket: 6428606-zd-woothemes

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on simple, AT, and outside of WordPress.com. Also noticed that if I set up an image with Duotone on an FSE theme, then switch the theme to a Classic theme, the duotone I set up is lost.  I have to set it up again, but this time it doesn't apply to the live site.

#### Screenshots/Recordings

Duotone settings while on FSE theme **TT3**: 

![JCfxZg.png](https://github.com/Automattic/wp-calypso/assets/27249804/b87560f8-dd69-4612-97a2-f3b6d760f9b1)

Returning to my post after switching to theme **Twenty Twenty**:

https://github.com/Automattic/wp-calypso/assets/27249804/18bf0a95-d8aa-473b-95b3-3caa9e395d87

Atomic Site: 
- Gutenberg: v16.0.0
- Editing Toolkit: 3.68851

Simple site:
- Gutenberg: v16.0.0
- Editing Toolkit: 3.68851
- WP AMP: 2.0.5
- CoBlocks: 2.18.1-simple-rev.4

---

Self-Hosted:

![Markup on 2023-06-20 at 10:56:06](https://github.com/Automattic/wp-calypso/assets/27249804/09de94c1-c205-46e4-9bdb-29e2ea9939f4)

![Markup on 2023-06-20 at 10:56:36](https://github.com/Automattic/wp-calypso/assets/27249804/7b4ac06a-5c71-491d-9d6d-b00fa03f41df)

Gutenberg v16.0.0 and no other plugins

📌 ACTIONS
- Assigned to `Non-Urgent`
- Added to ‘HE Cross-repo Watchlist’ project board

📌 Message to Author
- Looks like this may have been intentional, but Duotone can likely come back to Classic Themes, based on the discussion in this `/gutenberg` issue: 
- https://github.com/WordPress/gutenberg/issues/49293

**Comment by Greatdane** [comment]
Another; 6473910-zd-woothemes

**Comment by jamiepalatnik** [comment]
Another report: 6752520-zd-a8c
Morden theme. 

Found these similar issues that it might be good to merge: https://github.com/Automattic/themes/issues/7054
https://github.com/Automattic/wp-calypso/issues/75805

**Comment by cuemarie** [comment]
Nice finds, @jamiepalatnik , thank you!

📌 ACTIONS
- closed Automattic/themes#7054 and carried over customer reports
- Retested and closed closed https://github.com/Automattic/wp-calypso/issues/75805 and carried over customer reports

**Comment by cuemarie** [comment]
Customer reports from https://github.com/Automattic/themes/issues/7054 : 
- 6259701-zen [Dara]
- 27843422-hc [Sequential]

**Comment by cuemarie** [comment]
Customer Reports from #75805 : 

- 6199292-zen - Simple, Theme: Orvis
- 37361778-hc - Atomic, Theme: Seedlet
- 6252844-zen - Atomic, Theme: Seedlet

**Comment by cuemarie** [comment]
Retested and can still replicate this on a self-hosted site with **Gutenberg 16.5.1** active and theme **Twenty Sixteen**.

https://github.com/Automattic/wp-calypso/assets/27249804/0b477e2f-df7d-43e0-aebf-c2fb877414e4

**Comment by cuemarie** [comment]
📌 ACTIONS
Reported this anew in /gutenberg, here: 

- https://github.com/WordPress/gutenberg/issues/54099

**Comment by janmckell** [comment]
Since this is still open, I'm adding this Ticket reference, as I don't see it added before:
6545304-zd-a8c
7123721-zd-a8c

**Comment by ckmccoy2** [comment]
I ran into another example of this issue:
7225527-zd-a8c

**Comment by ClassicRKR27** [comment]
Another example while using the `Alves` theme: 7197512-zd-a8c

**Comment by CodeAllNightNDay** [comment]
Example here with Barnsbury theme: 7293087-zd-a8c

**Comment by cuemarie** [comment]
https://github.com/WordPress/gutenberg/issues/54099 was just fixed last week, so this should resolve soon. Will need a retest to confirm.

**Comment by mahfuzurwp** [comment]
7714741-zen

**Comment by tvolpert** [comment]
7814855-zen

**Comment by gikaragia** [comment]
Core fix seems to be merged: https://github.com/WordPress/gutenberg/pull/54778

Tried with themes 2016-2020 and it works.
