### ISSUE TITLE
Paid Stats: Adjust notice styles for Calypso Stats

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#78452]
We'll need to override the notice styles for Calypso Stats, as the notices were original designed for Jetpack only.

![Image](https://user-images.githubusercontent.com/1425433/247343669-8f8e6c07-b264-4a2f-b479-2c18fbbeea5e.png)

And I think we'll need some help from our designers @keoshi @ederrengifo .

**Comment by dognose24** [comment]
The Stats notification banner is updated with the latest design: p1HpG7-nsA-p2

<img width="959" alt="截圖 2023-07-04 上午11 59 19" src="https://github.com/Automattic/wp-calypso/assets/6869813/247342e5-aca3-48eb-9367-178737d82f43">

**Comment by kangzj** [comment]
@dognose24 As Jetpack and Odyssey would share the same purchase flow, I guess probably it would be fine to only adjust the fonts.

What do you think @ederrengifo ? Thanks

**Comment by dognose24** [comment]
> I guess probably it would be fine to only adjust the fonts.

@kangzj Do you mean the adjustment based on the existing styling of https://github.com/Automattic/wp-calypso/pull/78558?

**Comment by kangzj** [comment]
@dognose24 the fonts in the notices are Jetpack styled, so I imagine we should change to Calypso styles 🤔

**Comment by jsnmoon** [comment]
@dognose24: Do we have any remaining actionables for this ticket?

**Comment by jsnmoon** [comment]
@dognose24: Bump 🙂

**Comment by jsnmoon** [comment]
Please re-open if necessary 🙂
