### ISSUE TITLE
Learn LP thumbnails

### ISSUE THREAD

**Issue by jrdnhllr** [Automattic/wp-calypso#78458]

**Comment by jrdnhllr** [comment]
P2 request – p9Jlb4-7W4-p2

**Comment by garretsteider** [comment]
Final thumbnails for /learn thumbnails are here

[Figma Files ->](https://www.figma.com/file/IceKRdz5qlPYwuqzu6pBgF/WPCOM-Learn-Ecosystem?type=design&node-id=2082-39875&mode=design)
