### ISSUE TITLE
Staging sites: User was able to purchase and connect a custom domain

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#78467]
### Quick summary

A user was able to purchase and connect a custom domain to a staging site which shouldn't be possible. 

In trying to test, if the URL for adding a domain (https://wordpress.com/domains/add/{site}) is known, you can access the add flow but see an error message. This page should be getting redirected to the dashboard though like the manage domains page is. Caveat: once you try to access the manage domains page it will redirect every time you try to go to add domains again until you open the dash in a new window.

### Steps to reproduce

Purchasing the domain:
Steps unknown??

Viewing the add domain screen:
1. on WoA staging site go directly to https://wordpress.com/domains/add/{site}
2. see add screen and error

### What you expected to happen

You can't get to the domain purchase screen much less make the purchase

### What actually happened

A domain was purchased and connected

You can access the add domain screen
![image](https://github.com/Automattic/wp-calypso/assets/47717887/7dc1ba2f-9978-4674-97d2-3d51edfda3cc)

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

user in question: blog_id=220042186
related slack thread: p1687333919337039-slack-C03TY6J1A

Was also found that when a user adds a CC and checks “Use this payment method for all subscriptions on my account.” the details also get added to the staging site lifetime plan

**Comment by Nic-Sevic** [comment]
Not sure if it's related but the user also experienced this weirdness with two of their other domains. Check the url and see how two completely different domains on different sites are mentioned
Edit: removed image and added onebin link due to public repo: 30dfd-pb/

**Comment by youbrokesomething** [comment]
This issue might be related: [Staging site: We need to hide/remove the custom domain prompt on the post/page editor #78603](https://github.com/Automattic/wp-calypso/issues/78603)

**Comment by danielbachhuber** [comment]
Thanks for the report, @Nic-Sevic. We'll take a look.

**Comment by kozer** [comment]
### Investigation

I started an investigation to point out why this is happening. I'll create more posts here as I progress.

1. I switch to the user
2. Visiting the staging site I notice something strange:

![domains_access_staging_1](https://github.com/Automattic/wp-calypso/assets/497103/c2a53993-4a1e-48e3-8518-95125d1cae3a)
![domains_access_staging_2](https://github.com/Automattic/wp-calypso/assets/497103/8a5d59fb-b40e-4911-8668-eaab7bbf3954)

We have a mechanism in place that redirects the user when he visits `/domains` endpoints. This is located [here](https://github.com/Automattic/wp-calypso/blob/1a62a85d7b5656894dfc477e7869371f49544cc4/client/my-sites/controller.js#L716).

I'm not sure if for some reason, the second endpoint sets that blog info at `state.ui.selectedSiteId` variable (which is responsible to fetch the `selectedSiteId`). If this is the case then it explains why the user had access to that page. However, this should not be the case, as this domain is added by the user, after the staging site creation.

3. I created a site, bought a domain, transferred it, and created a staging site. The `/domain` endpoints are not accessible.

**Comment by danielbachhuber** [comment]
@Nic-Sevic Have you come across any more reports of this? If not, I think we'll put it on hold until someone can reproduce it reliably.

**Comment by Nic-Sevic** [comment]
There was an instance of a custom domain previously added to a staging site and then transferred to a new staging site here. The domain was not purchased here but the "purchase" of a domain connection was allowed. I believe it was manually placed by and HE but failed to track down the original support conversation: p1696931666901229/1686727931.851909-slack-C03TY6J1A

domain was originally on https://staging-deb4-howardcm760087299.wordpress.com and then transferred to http://staging-6072-howardcm760087299.wordpress.com/ via DARC
domain: https://sandbox.howardcm.com/

sorry for the delay in reporting here

Since this isn't purchase itself, I think this specific issue can be closed but wanted to note the above in case other similar instances occur

**Comment by danielbachhuber** [comment]
@Nic-Sevic Sounds good. Happy to figure out a fix if you find some way users are able to work around the restrictions.

**Comment by wojtekn** [comment]
I've re-opened this issue as I likely figured out the flow to buy a domain for the staging site:

1. Create a site with a Business plan and enable Hosting Features
2. Add a staging site
3. Open the staging site in the Jetpack mobile app on iOS
4. Buy a domain

The site I used was 216963623.

**Comment by katinthehatsite** [comment]
The site that was used for testing previously: https://mc.a8c.com/tools/reportcard/blog/?blog_id=216963623&more=1

**Comment by katinthehatsite** [comment]
Hey @wojtekn - I am attempting to reproduce this but I am not able to purchase the domain from the iOS app. This is what I am seeing on my end:

https://github.com/user-attachments/assets/b08563d8-99a0-4876-8984-ec714d6975b0

Could you give it a test and let me know if you can still see the issue? Please note that there is currently a bug that does not sync Automatticians' sites to the app so to test this you would need to use non-Automattician account.

**Comment by katinthehatsite** [comment]
Also, I opened this issue because the flow of opening the custom domains on staging sites on mobile seems quite strange: https://github.com/wordpress-mobile/WordPress-iOS/issues/23453

**Comment by wojtekn** [comment]
@katinthehatsite thanks for testing it. On your video it looks different when I tested it last time. In my case, it was opening domain search in the browser, but now it's part of the application.

I assume the original issue is gone, but another is visible. Users shouldn't see a free domain nudge on the staging site. Could we pass this on to the proper team?

**Comment by katinthehatsite** [comment]
Yeah @wojtekn  - I already opened the issue, see https://github.com/Automattic/wp-calypso/issues/78467#issuecomment-2257864077 for more details

**Comment by katinthehatsite** [comment]
Since it is not possible to reproduce the issue and the suggested UI improvement has been passed to the mobile team, I will close this issue. Feel free to re-open if this comes up again.
