### ISSUE TITLE
Patterns - Dotcom patterns require to be registered with "template_types" to feature them when creating/editing a template

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#78481]
Related to https://github.com/Automattic/dotcom-forge/issues/2390

## What

A new feature in WordPress 6.3 allow us to establish a relationship between patterns and templates to suggest them when creating/editing a template. Read more in [Patterns API expanded to include template_types property](https://make.wordpress.org/core/2023/03/07/patterns-api-expanded-to-include-template_types-property/).

This means Dotcompatterns can specify in a pattern meta the template they are meant to be used in. Then, during the registration of the patterns, we can use that meta as `template_type`.

We are already using a similar approach for pattern `block_types`. See https://github.com/Automattic/wp-calypso/issues/78478.

## Why

To show the user some patterns that make sense on a template when the user starts creating a template. Users can start from a pattern instead of “blank” or the fallback template.

@Automattic/lego Do you remember the modal we got rid of? See p1685502977404329/1685474338.416489-slack-CRWCHQGUB

![Image](https://user-images.githubusercontent.com/1881481/247532846-3645e583-0682-4a5f-8c7e-8682075f033e.png)

The template in the screenshot is the "Home" and because we are creating it from blank, it shows patterns that are registered with `template_type: [ 'home' ]`. 

## How

- Identify patterns that are meant to be in [templates](https://developer.wordpress.org/themes/basics/template-hierarchy/) like:
  - home
  - author
  - archive
  - 404
  - etc. 
- Option 1: Develop the same approach that we use for `block_types` with a dynamic pattern meta. See https://github.com/Automattic/wp-calypso/issues/78478.
- Option 2: Maybe there is a better approach?

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
