### ISSUE TITLE
Jetpack Stats: Likes tab panels are loading indefinitely on AT sites

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#78515]
https://github.com/Automattic/wp-calypso/assets/6737345/9ab563fd-324e-46f8-ba5d-539a43b09475

### Quick summary

When accessing the Likes tab, the section below are not loading the data.

### Steps to reproduce

1. Spin up or access an AT website
2. Access the Stats section
3. Click on the Likes tab and scroll down

### What you expected to happen

To see the sections below loading data or a message if there's no data to show

### What actually happened

Video: 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

- I couldn't find any particular error
- I asked here(p1687349850070129-slack-C03TY6J1A) and was recommended to report this here.

**Comment by kangzj** [comment]
This is fixed with https://github.com/Automattic/wp-calypso/pull/78612
