### ISSUE TITLE
Assembler & Theme detail - Fonts in two columns layout

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#78524]
## What

A new two-column layout for fonts in the assembler and the theme detail. We are only changing the CSS from one to two columns.

|BEFORE|AFTER|
|---|---|
|![Image](https://user-images.githubusercontent.com/1881481/247873120-27c1a44a-7680-49a4-91c1-8cb6515defc0.png)|![Image](https://user-images.githubusercontent.com/1881481/247870568-af8bbbf2-cf76-41d1-ad22-be0df79eaf7b.png)|

## Why

For uniformity with Woo assembler

## How

Update the CSS layout for the component [FontPairingVariation](https://github.com/Automattic/wp-calypso/blob/trunk/packages/global-styles/src/components/font-pairing-variations/style.scss)  

See Figma Tv3pYqA3EcRfiXC31IxrXE-fi-751_33823

**Comment by miksansegundo** [comment]
@arthur791004 Would you like to do this issue? or guide me to do it?

I tried to do it and got stuck understanding how to change the implementation of `<FontPairingVariationPreview>`.

**Comment by arthur791004** [comment]
@miksansegundo Maybe we can schedule a call tomorrow to work on it together 🙂

**Comment by miksansegundo** [comment]
Thanks so much @arthur791004. I'll give it another try tomorrow morning and then ping you to schedule the call for later.

**Comment by miksansegundo** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/78734
