### ISSUE TITLE
Assembler - UX - New Header and Footer navigation to open on a side panel

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#78527]
## What

The Header and Footer steps will open on a side panel.

|BEFORE|AFTER|
|--|--|
|![Image](https://user-images.githubusercontent.com/1881481/247877631-d29efb17-aee2-435b-9d59-848022f30b71.png)|![Image](https://user-images.githubusercontent.com/1881481/247877662-d1d4d9a5-c6fb-4454-978a-aafc0f27ec69.png)|

## Why

- Removes the need for the "Save" and "<" back buttons
- Keeps the main screen visible so users can click on another step to continue customizing

## How

- Use the component [PatternListPanel](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-panel.tsx) or a variation.
- Review and update Tracks events

**Comment by fushar** [comment]
This is shipped! 🚢
