### ISSUE TITLE
Disable style variations in some of the Blockbase child themes

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#78559]
As discussed in Slack (p1684890861128899-slack-C029FM1EH), the child themes of Blockbase inherit its style variations, but not all are compatible. This issue is to track the effort to go over all the themes, and decide if the style variations should be disabled in the child theme or not.

**Comment by alaczek** [comment]
List of affected themes:
1. Winkel
 * Charcoal
 * Rainforest
 * Ruby Wine
2. Arbutus
 * ✅ Charcoal
 * ✅ Rainforest
 * ✅ Ruby Wine
3. Byrne
 * Charcoal - could potentially work with some adjustments to the homepage.
 *  ✅ Rainforest
 *  ✅ Ruby Wine
4. Marl
 * ✅ Charcoal
 * ✅ Rainforest
 * 🛑 Ruby Wine
5. Russell
 * 🛑 Charcoal 
 * ? Rainforest
 * ✅ Ruby Wine
6. Kingsley - disable all style variations
 * 🛑 Charcoal
 * 🛑 Rainforest
 * 🛑 Ruby Wine
7. Alonso
 * ✅ Charcoal
 * ✅ Rainforest
 * ✅ Ruby Wine
8. Kerr
 * 🛑 Charcoal
 * ✅ Rainforest
 * ✅ Ruby Wine
9. Payton
 * ✅ Charcoal
 * ✅ Rainforest
 * ✅ Ruby Wine
10. Attar
 * ✅ Charcoal
 * ✅ Rainforest
 * 🛑 Ruby Wine
11. Baxter  - disable all style variations
 * 🛑 Charcoal
 * 🛑 Rainforest
 * 🛑 Ruby Wine

🛑 - style variation needs to be disabled
✅ - style variation works ok (keep as is)

**Comment by rcrdortiz** [comment]
Baxter is working correctly with style variations.

**Comment by rcrdortiz** [comment]
@alaczek I've fixed these style variations here: https://github.com/Automattic/themes/pull/7859

**Comment by rcrdortiz** [comment]
These changes are now live.
