### ISSUE TITLE
Plans 2023: Deprecate/remove isReskinned prop in PlansFeaturesMain

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#78569]
The `isReskinned` prop passed to `PlansFeaturesMain` is only used for a tiny small CSS change, and in all cases seems to be statically set to `true`. It's pointless complexity if that's the case. Investigate and throw it away.

**Comment by ddc22** [comment]
Fixed by: https://github.com/Automattic/wp-calypso/pull/83473
