### ISSUE TITLE
Staging site: We need to hide/remove the custom domain prompt on the post/page editor

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#78603]
### Quick summary

When working on a user's website, I noticed the post editor has a nudge to add custom domain name on the top of the editor. I checked my staging site, and I can confirm I see the same thing too, both on a new post/page or on an existing post/page:

![Screenshot 2023-06-25 at 2 57 36 PM](https://github.com/Automattic/wp-calypso/assets/44726232/f52f38a0-3d04-4267-8759-6bb284a8e2c8)

Staging website _should not_ have any custom domain name attached to it, and it's not possible to add domain connection or any custom domain name to it. That said, can we remove the prompt to purchase/register a new domain name on staging sites?

Also, I tried clicking "Customize your domain" and I got redirected to the My Home. GIF screenshot below:
![Jun-25-2023 14-53-39](https://github.com/Automattic/wp-calypso/assets/44726232/e733677a-6854-4296-a438-1b65a497eeaf)

### Steps to reproduce

1. Create a staging site from AT site > _Hosting Configuration_ > _Staging site_
2. Create a new post or a new page. You can also open existing post or page on the website.
3. See the nudge on the top: "WEBSITE ADDRESS Customize your domain" 

### What you expected to happen

I expect to see no nudge to use custom domain name on staging site

### What actually happened

I see a nudge to use custom domain name on staging site. This can cause confusion and give a different expectation: Clicking "Customize your domain" redirects to My Home. While this is an expected flow as it should be impossible to use custom domain name on a staging site, this can cause confusions on the user's side.

Workaround:
We _can_ click the "X" button on the nudge to close the message, but the nudge shouldn't be there on the first place.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by danielbachhuber** [comment]
Thanks for the report, @retnonindya. We'll take a look.

**Comment by sejas** [comment]
I released a new ETK version (3.71072) to fix the issue. It will take a few hours to spread across atomic servers.
- https://github.com/Automattic/wp-calypso/pull/79014
- D115416-code
- r270499-wpcom
