### ISSUE TITLE
Hosting Configuration clear cache button disabled and unclickable

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#78602]
### Quick summary

The [Clear Cache button on Hosting Configuration](https://wordpress.com/support/clear-your-sites-cache/#clear-your-sites-cache) is persistently disabled on all Atomic sites. 

Workarounds:
-  clear the cache via [WP-CLI, which is accessible to all site Owners via SSH](https://wordpress.com/support/connect-to-ssh-on-wordpress-com/#how-to-use-wp-cli). 
- HE's can also clear cache for users via our CLI interface. 

### Steps to reproduce

1. Create or start with an existing Business or eCommerce site.
2. Navigate to Settings > Hosting Configuration ([Click Activate in the notice if prompted.](https://wordpress.com/support/hosting-configuration/)) 
3. Scroll down to the Clear Cache button and try to click it. 

### What you expected to happen

I expect the button to be clickable and to clear the cache.

### What actually happened

It's disabled and can't be clicked. 

<img width="2301" alt="image" src="https://github.com/Automattic/wp-calypso/assets/29527450/14543e1d-a55c-4280-9ffe-0f4a51fbac59">

### Impact

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Reports: 
- 6460751-zd-woothemes
- 6461657-zd-woothemes

Internal ping where this came up: 
- p1687552343978419-slack-C03TY6J1A 

Other notes from testing: 
- Clear cache is disabled with edge cache enabled and disabled. 
- not plan-specific as it happens on both Business and eCommerce.

**Comment by mgozdis** [comment]
User report here: 6462485-zd-woothemes
Cleared cache for them, but they said they need to be able to clear it on their own as they are developing a mobile version of the site and running into cache issues.

**Comment by kimerlin81** [comment]
another case reported [here](6459659-zd-woothemes)

**Comment by happychait** [comment]
Another report in 6462995-zen

**Comment by happychait** [comment]
Another report in 6463011-zen

**Comment by maciejpilarski** [comment]
Another report in 6463269-zen

**Comment by khristiansnyder** [comment]
6463331-zen

Can replicate this across my test sites.

**Comment by rakshitwesley** [comment]
Reported here: 6465276-zd-woothemes

**Comment by retnonindya** [comment]
Another report:
6464228-zd-woothemes

**Comment by worldomonation** [comment]
Confirmed the button is disabled for my testing site. 

<img width="1496" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/517b912a-a037-4e0a-b4f0-9b1377c4f97a">

Escalating in p1687759593977849-slack-C02FMH4G8

**Comment by syhussaini** [comment]
Another instance 6465257-zen

**Comment by jorpdesigns** [comment]
Reported in 6465577-zd-woothemes
