### ISSUE TITLE
Minor UI issues in calypso core profiler authentication UI

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#78615]
There are a few UI issues in Calypso related to core profiler:

1. Connect screen padding above the form

<img src="https://user-images.githubusercontent.com/3747241/248640487-a955aaf3-1258-482d-996a-4fd1b468c281.png" width="450">

1. Login screen padding isn't 40px

<img src="https://user-images.githubusercontent.com/3747241/248640562-20e05bd6-f125-4cc8-98e0-f755c254785c.png" width="450px">

### Acceptance criteria

1. Fix UI as per design in Figma

**Comment by chihsuan** [comment]
> 1. Connect screen padding above the form
> <img src="https://user-images.githubusercontent.com/3747241/248640487-a955aaf3-1258-482d-996a-4fd1b468c281.png" width="450">

Hey @ilyasfoo, 👋  The site title card is missing from your screen. Do you have steps to reproduce it?

![Image](https://github.com/Automattic/wp-calypso/assets/4344253/f0d806f6-f8f3-49e7-a7c6-60a5eecf6c87)


> 2. Login screen padding isn't 40px

Same issue

**Comment by ilyasfoo** [comment]
@chihsuan I'm running in the latest trunk for both calypso and woocommerce.

I deactivate Jetpack in core, go through the full core profiler flow with Jurassic tube by selecting Jetpack extension, and was able to reproduce this. 

Were you able to get the component to show?

**Comment by chihsuan** [comment]
> I deactivate Jetpack in core, go through the full core profiler flow with Jurassic tube by selecting Jetpack extension, and was able to reproduce this.

> Were you able to get the component to show?

@ilyasfoo Yes, I was able to see the component. 🤔 I just tested again with the latest woocommerce Nightly build on a new JN site. I also deactivated Jetpack in core and went thought the core profiler.

**Comment by chihsuan** [comment]
That component will only be displayed in the case of Jetpack version > 4.0.3. In my test, `jp_version` is `12.2.1`.

https://github.com/Automattic/wp-calypso/blob/1a48e44615d9bffa1db23b465f7d6c179a9b8d4b/client/jetpack-connect/auth-form-header.jsx#L209-L215

**Comment by ilyasfoo** [comment]
Thanks for the explanation! I'll continue the discussion in the PR linked
