### ISSUE TITLE
Subscription Management: Redirect cookie authed user who has a WP account to Reader.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78630]
Cookie-authed users with a WP account should be redirected to the Reader if they land on the Subscriptions page. The login page should show if the user is not logged in. (Reader/Calypso should already handle the log-in page so less work on our end.)

**Comment by TimBroddin** [comment]
Wouldn't it make more sense to change the URL in the mail they receive? I'll make a small patch for this.

**Comment by yansern** [comment]
> Wouldn't it make more sense to change the URL in the mail they receive? I'll make a small patch for this.

Discussion continued here. p1688033851049159-slack-C02TCEHP3HA
And an issue is created here: https://github.com/Automattic/wp-calypso/issues/78796


As for this issue, I'm going to update it slightly to this:
"Cookie-authed users with a WP account should be redirected to the Reader if they land on the Subscriptions page. The login page should show if the user is not logged in." (Reader/Calypso should already handle the log-in page so less work on our end.)

**Comment by yansern** [comment]
Also going to set this to lower priority as I'm trying to understand if this is worth the effort based on usage stats.

**Comment by yansern** [comment]
Closing this in favour of auto user creation. Context: pdDOJh-2qY-p2
