### ISSUE TITLE
Subscription Management: Add ability to search to discover new sites and ability to add subscription by URL.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78631]
When a person enters a keyword in the search box, it will do both:
 - filter the existing subscription list
 - show a list of new sites to discover

The search box should also support pasting of URLs for:
- Wordpress Site URL.
- RSS URL

where the entry of the pasted URL will be shown along with the list of new sites to discover.

Prioritize making this work on Reader portal first.

The design will be similar to the recommended sites' design, actual design will be clarified soon.

Bear in mind the design will also include how it will work with paid sites. For now, let's get the backbone built first.

<img width="889" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1287077/7338ffed-111d-4ca4-92f1-327eaea26631">

**Comment by mashikag** [comment]
Remaining tasks: 
- [x] Wrap search result labels in a call to `translate` ([here](https://github.com/Automattic/wp-calypso/blob/1e2cfe9372b5330eb264340b331fd13c7acf710e/client/reader/site-subscriptions-manager/reader-site-subscriptions.tsx#L27))
- [ ] Display search loading state. 
- [x] Display search result for an external URL/ feed URL.
- [ ] Record Tracks events for user interaction with the search results.
    - Search for `// TODO: track click` within the code
- [x] Point the `/following/manage` path to the new page, i.e. `/read/subscriptions`.

Remaining issues:
- [ ] Fix regression - "New Comments" missing color of checkmark and cross sign values.
- [ ] Fix regression - "New Posts" cell's tip is not displayed on hover over.
