### ISSUE TITLE
Launchpad: Update documentation in the FG

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#78645]
We've made some pretty substantial changes to Launchpad infrastructure and those should be reflected in the Field Guide page.

**Comment by sixhours** [comment]
I've updated the docs to account for Launchpad in Customer Home, and for the changes we've made to the backend; search for "Launchpad" in the FG and you should find it.

Please have a look and let me know if there's anything else we want to add at this time.

**Comment by markbiek** [comment]
Not sure if anyone else needs to weigh in here but I think the FG page covers everything.

**Comment by sixhours** [comment]
It's all good, we can always update as needed. :D
