### ISSUE TITLE
Contact form block missing space between field name and required notice

### ISSUE THREAD

**Issue by emilyaudela** [Automattic/wp-calypso#78644]
### Quick summary

On the front end of a website, there is a space missing between the field name and the "required" notice when using the form block.

![Markup on 2023-06-26 at 11:03:38](https://github.com/Automattic/wp-calypso/assets/36699353/1760197f-e96b-4f48-ad51-b019061f4a15)

### Steps to reproduce

1. Start on a test site
2. Create a new page or post
3. Add a Contact Form block.
4. Publish the page
5. On the front end, there is no space by default between the field name and the (required) notification. In the editor, the space appears.

### What you expected to happen

I would expect a space between Field Name and "(required)"

### What actually happened

In the editor, there is a space between the field name and '(Required), but on the front end of the page, the space isn't visible. This can be fixed by manually adding a space after the field name, but it's not intuitive for users. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by mikeicode** [comment]
Aside from the space issue, this text should have additional styling such as a different color, font-weight, etc. I add this CSS to every site I build:

```
/* Form required fields */
.contact-form label span {
	font-weight: 300;
	padding-left: 2px;
	opacity: .5;
}
```
<img width="401" alt="Screenshot 2023-06-26 at 1 30 27 PM" src="https://github.com/Automattic/wp-calypso/assets/10353785/13f6a296-9ba0-428d-8fc7-9ab42a97ec18">

**Comment by metabreakr** [comment]
I have been using a similar variation of the 👆 above for site builds. 

CSS should not be required here; all the text visually is identical and there is no spacing between the `label` and `(required)` text, and should be addressed. It was not an issue not long ago, so this is a recent change.

**Comment by mikeicode** [comment]
I see this has been resolved, with the following CSS:

```
.contact-form label span.required, .grunion-label-required {
  font-size: 85%;
  margin-left: .25em;
  font-weight: 400;
  opacity: .6;
}
```
![Screen Shot on 2023-12-14 at 13:22:07](https://github.com/Automattic/wp-calypso/assets/10353785/b9f9f414-89bf-4738-877d-f5c79f549a18)
