### ISSUE TITLE
Jetpack connect button is automatically clicked after signing up for a new user

### ISSUE THREAD

**Issue by moon0326** [Automattic/wp-calypso#78648]
Details: pdibGW-26P-p2#comment-1582

This is probably by design, but creating this issue to investigate to confirm.

#### Steps to reproduce

Make sure to sign in to wordpress.com first

1. Create a new JN site with WooCommerce 7.9.0+
2. Go through the new core profiler and make sure to select Jetpack on the plugins page
3. You should be redirected to Jetpack auth page at the end of the flow.
4. Create a new account
5. You're redirected to WooCommerce Home automatically

#### What I expected

User should be able to click the button.

#### What happened instead

The button is automatically clicked

**Comment by chihsuan** [comment]
@moon0326 Yes, it's intended. It's the default behavior on the Jetpack connection screen. 🙂

**Comment by moon0326** [comment]
@chihsuan Thank you for the confirmation 👍 Closing it.
