### ISSUE TITLE
Onboarding CI tests: Themes gallery sometimes fails to load any themes.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#78658]
### Quick summary

Observed during tests in CI prior to deploy.

User going through onboarding across several test suites fail due to the theme gallery failing to load. The user is unable to proceed forward with the onboarding as scripted in the tests.

Let's figure out whether this issue is affecting production and real users, or if it's just due to a quirk of the wpcalypso.wordpress.com environment in CI.

### Steps to reproduce

Uncertain what causes this to occur, but the nature of the failure suggests this is not due to specific steps, but rather an infrastructure issue.

The steps taken by one of the tests which can reproduce this issue is transcribed here, but this is **not** the only steps that can reproduce the issue.

1. sign up as a new user.
2. enter site name and description.
3. click next.

### What you expected to happen

List of available themes is presented to the user.

### What actually happened

Theme gallery does not load, showing a blank page in place of theme thumbnails.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/7fc6d9b3-6b68-4357-a165-e2689b7ccd2c)

https://github.com/Automattic/wp-calypso/assets/6549265/50673a2d-702b-44e7-a31f-59b52662706e

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

In the Playwright Trace file, nothing notable in the Network or Console tabs is recorded.

In fact, the network call to `https://public-api.wordpress.com/wpcom/v2/starter-designs?_envelope=1&seed=e2eflowtesting1687782943463186.wordpress.com&_locale=en` seems to receive a proper response:

Open for Response details
<details>

```{
  "body": {
    "filters": {
      "subject": {
        "blog": {
          "name": "Blog",
          "description": "Choose from a wide variety of styles and layouts for your personal or professional blog."
        },
        "business": {
          "name": "Business",
          "description": "WordPress business themes with professional designs for your company or organization: display contact info, feature your products or services, share testimonials, and engage customers with a blog. "
        },
        "portfolio": {
          "name": "Portfolio",
          "description": "Themes that support WordPress’ Portfolio post type, many with added features like front-page sliders, immersive slideshows, and elegant galleries to help viewers engage with your work."
        },
        "store": {
          "name": "Store",
          "description": ""
        },
        "about": {
          "name": "About",
          "description": ""
        },
        "link-in-bio": {
          "name": "Link in Bio",
          "description": ""
        },
        "newsletter": {
          "name": "Newsletter",
          "description": ""
        }
      }
    },
    "static": {
      "designs": [
        {
          "slug": "quadrat",
          "title": "Quadrat",
          "description": "Quadrat is a simple, versatile WordPress theme, designed for blogs and podcasts.",
          "recipe": {
            "stylesheet": "pub/quadrat"
          },
          "is_virtual": false,
          "preview_data": null,
          "categories": [
            {
              "slug": "blog",
              "name": "Blog"
            }
          ],
          "software_sets": [],
          "style_variations": [
            {
              "slug": "default",
              "title": "Default",
              "settings": {
                "color": {
                  "custom": true,
                  "customGradient": true,
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#FFD1D1",
                        "name": "Primary"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#151853",
                        "name": "Tertiary"
                      },
                      {
                        "slug": "background",
                        "color": "#292C6D",
                        "name": "Background"
                      }
                    ]
                  },
                  "link": true
                }
              }
            },
            {
              "slug": "charcoal",
              "title": "Charcoal",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#9FD3E8",
                        "name": "Primary"
                      },
                      {
                        "slug": "secondary",
                        "color": "#FBE6AA",
                        "name": "Secondary"
                      },
                      {
                        "slug": "foreground",
                        "color": "#FFFFFF",
                        "name": "Foreground"
                      },
                      {
                        "slug": "background",
                        "color": "#1F2527",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#364043",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "rainforest",
              "title": "Rainforest",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#35845D",
                        "name": "Primary"
                      },
                      {
                        "slug": "secondary",
                        "color": "#233252",
                        "name": "Secondary"
                      },
                      {
                        "slug": "foreground",
                        "color": "#242527",
                        "name": "Foreground"
                      },
                      {
                        "slug": "background",
                        "color": "#EEF4F7",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#F9F9F9",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "ruby-wine",
              "title": "Ruby Wine",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#C8133E",
                        "name": "Primary"
                      },
                      {
                        "slug": "secondary",
                        "color": "#4E2F4B",
                        "name": "Secondary"
                      },
                      {
                        "slug": "foreground",
                        "color": "#1D1E1E",
                        "name": "Foreground"
                      },
                      {
                        "slug": "background",
                        "color": "#FFFFFF",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#F9F9F9",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "black",
              "title": "Black",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#ffe1d0",
                        "name": "Primary"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#191919",
                        "name": "Tertiary"
                      },
                      {
                        "slug": "background",
                        "color": "#000000",
                        "name": "Background"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "blue",
              "title": "Blue",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#FDF5E2",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#204A72",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#123B62",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "dark-blue",
              "title": "Dark Blue",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#F9DAAD",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#0E2B3B",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#071F2C",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "green",
              "title": "Green",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#F5D5CA",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#103931",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#0A2C25",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "light-blue",
              "title": "Light Blue",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#460707",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#EDF4F9",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#DEE9F1",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "light-green",
              "title": "Light Green",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#0C1946",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#EBF3EC",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#DBE9DD",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "light-pink",
              "title": "Light Pink",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#151853",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#FFE2E2",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#FCD0D0",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "light-red",
              "title": "Light Red",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#8E3636",
                        "name": "Primary"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#E9E5E9",
                        "name": "Tertiary"
                      },
                      {
                        "slug": "background",
                        "color": "#F1F0F4",
                        "name": "Background"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "light-yellow",
              "title": "Light Yellow",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#0E2B3B",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#FFF4E3",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#FBEAD2",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "red",
              "title": "Red",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#CEEDFF",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#822726",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#721A18",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            },
            {
              "slug": "white",
              "title": "White",
              "settings": {
                "color": {
                  "palette": {
                    "theme": [
                      {
                        "slug": "primary",
                        "color": "#2B2B2B",
                        "name": "Primary"
                      },
                      {
                        "slug": "background",
                        "color": "#F8F8F8",
                        "name": "Background"
                      },
                      {
                        "slug": "tertiary",
                        "color": "#FFFFFF",
                        "name": "Tertiary"
                      }
                    ]
                  }
                }
              }
            }
          ]
        }
      ]
    }
  },
  "status": 200,
  "headers": {
    "Allow": "GET"
  }
}
```

</details>

**Comment by cuemarie** [comment]
Given the detailed notes above and the difficulty reproing so far, not trying to replicate before moving forward. 

📌 ACTIONS
- Assigned to @Automattic/lego

**Comment by taipeicoder** [comment]
@worldomonation after some hours of investigation, I'm still not sure what might be causing this bug. This is what I was able to find:

- The endpoint `/starter-design` returned no themes, just an empty array. So it's not on Calypso side.
- This endpoint fetches themes from ES, but does not send the list of themes as-is. There's some post-processing logic.
- At first, I thought that the ES might return empty data set. However, the design picker also calls the endpoint  `/rest/v1.2/themes` which also fetches themes from the ES, but with a different set of post-processing logic.
- The endpoint `/rest/v1.2/themes` did not return an empty array.
- This leads me to think that the culprit might be the post-processing logic of `/starter-design`. There are some randomization going on, which can explain why this bug only happen sometime.

That's my theory, but I'm no closer to the solution. In the meantime, I've created a diff D116935-code that hopefully provides more insights if the issue should happen again.

**Comment by autumnfjeld** [comment]
> There are some randomization going on, which can explain why this bug only happen sometime.

@taipeicoder Do you mean randomization of the theme order? Not anymore, t-rex shipped https://github.com/Automattic/wp-calypso/issues/79138

>The steps taken by one of the tests which can reproduce this issue is transcribed here, but this is not the only steps that can reproduce the issue.
> sign up as a new user.
> enter site name and description.
> click next.

This indicates it was the Write flow, ya?  Since site name & description are only in write, and also newsletter.

**Comment by taipeicoder** [comment]
>Do you mean randomization of the theme order? Not anymore, t-rex shipped https://github.com/Automattic/wp-calypso/issues/79138

There is still a bit of randomization going on with themes that are not curated:

- The list of themes that are not curated are shuffled together with virtual themes.
- The list of themes that are not curated are prioritized by a logic that promotes style variations.

We have just merged D117087-code which removes the second logic. I would like to remove the first logic as well, so that we completely remove randomization, and further reduce the complexity.

>This indicates it was the Write flow, ya? Since site name & description are only in write, and also newsletter.

For this bug report, yes, but I've seen the same issue in the build and sell flow. All from e2e so far, so we don't know if it affects users in production. I've added logging for it.

**Comment by worldomonation** [comment]
@taipeicoder This happened on two builds a total of at least 4 times at 2023/08/03 around 20:32 and 20:34 UTC+8.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/52d510c4-e1bb-44bf-94d3-a06f065cf7ae)

The Pre-Release builds in TeamCity are 13014 and 13015.

**Comment by worldomonation** [comment]
Addendum: it's happening a lot more frequently between late night 2023/08/03 and early morning of 2023/08/04.

**Comment by taipeicoder** [comment]
More information:

Last week, we [added](https://github.com/Automattic/wp-calypso/issues/78658#issuecomment-1649431139) logging that records whenever the design list is empty. This is the result:

<img width="846" alt="Screenshot 2023-08-04 at 2 17 26 PM" src="https://github.com/Automattic/wp-calypso/assets/797888/21aa0709-d059-4f0c-897a-0225ee074ba7">

There seems to be a pattern where this issue occurs within intervals of 10 minutes, and in fixed hours (00:30, 04:30, 08:30, and 12:30). This leads me to think that a cronjob might be causing the ES query to return empty results.

One thing that is throwing me off is that there are two endpoints in the design picker that query directly from the ES. And from the Playwright artifacts, one of the endpoints returns empty results (`/starter-designs`), while the other endpoint returns the expected data (`/rest/v1.2/themes`). I'll report back once have more information!

**Comment by taipeicoder** [comment]
With D118109-code merged, I was able to confirm that it's ES returning empty results. See the following `_id`s in `log2logstash` to see the full log: 

5zpFwokBJDXxtpRW2TSp
FBdFwokBNPvxEOI8zmnm
V-tFwokBAc8bfZrCtOsc
AkVFwokBxrxHbr-pq0vD
od1FwokBZN6x0rvhl1xJ

Some more takeaways:

- Since the `/starter-designs` ES query is the same every time, they all share the same cache key.
- So the issue is that something is causing the cache to be empty during those 10 minute intervals.

This explains why `/starter-designs` returns empty results while `/rest/v1.2/themes` doesn't (different cache keys). But still doesn't explain why the cache would be empty for one, but not for the other 🤔 FWIW the only difference between both queries is that the former has an additional filter `is_block_theme: true`.

@arthur791004 would you be able to revert D118109-code some time early next week? We don't need that logging anymore. Thanks!

**Comment by arthur791004** [comment]
Reverted 🙂

**Comment by taipeicoder** [comment]
More findings after my week-long AFK. The `/starter-design` endpoint was significantly changed via D118600-code on August 11th. Here are the changes that are relevant to this issue:

- The endpoint now does two separate ES queries, instead of one.
- The original ES query might still return empty results at the time intervals mentioned in the comments above.
- The original ES query was slightly modified, so the cache key is different from before.
- When the original ES query returns empty results, the newly added ES query returns the expected result set.

This means that users will no longer see an empty design picker, but only a limit number of themes coming from the second ES query. E2E tests are likely to still fail, since the required theme is still not present.

**Comment by worldomonation** [comment]
@taipeicoder Thanks for the update!

What would be a "safe" theme to use for E2E tests that would be in the smaller subset of themes returned by the endpoint?

**Comment by taipeicoder** [comment]
@worldomonation I tried something yesterday via D119037-code.
Remember how I mentioned that the `/starter-design` endpoint now does two separate ES queries? I wanted to try if the execution order matters, so I switched around so that virtual themes are queried first, then the standard themes last. 

You asked what would be a "safe" theme to use for E2E tests, from Calypso E2E's it'd be Attar, Stewart, and Upside down. As you know, this is likely to change, as we delist or introduce more themes, so ideally we want the `/starter-design` to at least return all standard themes.

What's interesting about D119037-code is that the logstash started logging different things, mainly `themes (2) | standard_designs (2) | virtual_designs (0)`, which is specific enough to attribute it to unit tests. What's more interesting is that standard themes are no longer returning empty.

I'd like to monitor this for a few more days, but from watching the logs from the past 24 hours the takeaway is that:

1. The execution order of the ES queries matters.
2. Since the virtual themes query is placed first, it sometimes might return empty results.
3. Since the standard theme query is placed last, it no longer is affected by this bug.
4. Currently, we only need standard themes for both the E2E tests and the design picker to function properly. 

As result, I think this makes the issue less severe than it used to. I'll continue watching the logs for the following days to confirm my theory. And we still haven't discovered why the first query execution might return empty sometimes.

**Comment by taipeicoder** [comment]
Bad news: The issue popped up again, but at much lower intermittence than before. I will keep monitoring this, while I continue debugging.
![Screenshot 2023-08-21 at 3 14 35 PM](https://github.com/Automattic/wp-calypso/assets/797888/38efbe3e-79dc-4e7d-a604-41bd60c8b29b)

**Comment by worldomonation** [comment]
This happened again rather unexpectedly at 2023/10/09 at 17:30 UTC+9, and it was the first time it happened since the last comment.

**Comment by autumnfjeld** [comment]
Moving this to In Progess since there is active discussion/testing.

**Comment by taipeicoder** [comment]
Posted a P2 for further insights 🙂 p3QzjZ-1FH-p2

**Comment by taipeicoder** [comment]
Closing via D126923-code. See p3QzjZ-1FH-p2 and p3QzjZ-1FH-p2#comment-5664 for more context.
