### ISSUE TITLE
Paid Stats: Add "I want to support" banner

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#78653]
Add a banner on the stats page that will connect to the paid stats flow and transition to [#31344](https://github.com/Automattic/jetpack/issues/31344)

- The notice should be available for Calypso Stats as well
- Always show unless user explicitly closes it
- When user closes it, we postpone it for 30 days

## Design
![Image](https://github.com/Automattic/jetpack/assets/112354940/d15dcb5f-c619-4078-92dd-aa6742fd2088)

**Comment by kangzj** [comment]
Closed with #78558
