### ISSUE TITLE
Design Picker: Error selecting theme variation

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#78659]
While performing a test on https://github.com/Automattic/jetpack/pull/31493 I experienced an error trying to select a variation for a theme. I noticed that there was no site slug on the design page, only the siteID. Every time I clicked on the variation the error below was thrown.

<img width="576" alt="Screen Shot 2023-06-26 at 15 12 58" src="https://github.com/Automattic/wp-calypso/assets/1234758/def5582a-07c0-4fbd-bf7d-b53affd5da40">

**Comment by fushar** [comment]
FYI: @Automattic/lego / @Automattic/t-rex

**Comment by Copons** [comment]
@valterlorran could you provide repro steps?
I don't see issues when using the Design Picker (grid, details, assembler) both when creating a new site or using an existing one. 🤔

**Comment by valterlorran** [comment]
Hey @Copons, I followed the steps described in this Jetpack PR: https://github.com/Automattic/jetpack/pull/31493. I will test it again later today.

**Comment by Copons** [comment]
Thanks @valterlorran!
The steps there don't really involve the Design Picker, so it's unclear to me at what point you saw the issue.

**Comment by dsas** [comment]
@valterlorran can you still reproduce this?

**Comment by BogdanUngureanu** [comment]
Closing this for now. I've tried to click around in DP and I couldn't find a way to reproduce it.

@valterlorran feel free to open it again if you are still reproducing it. :)
