### ISSUE TITLE
Windows: contented shifted due to vertical scroll bar

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#78661]
### Quick summary

On Windows machines, the content shifts by a few pixels to the left if the page has enough content to generate a vertical scroll

### Steps to reproduce

1. Create two pages. One with more content and one with less
2. Make sure you have the latest GB update
3. Check it on a Windows machine

### What you expected to happen

For the content to be centered, similar to macOS

### What actually happened

The content is slightly shifted to the left due to the vertical scroll

https://github.com/Automattic/wp-calypso/assets/6737345/907e8952-b639-40f3-9e13-22fe2b5168b4

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

6457872-zen
Tested on all environments and it's the same on all Windows machines, regardless of the browsers(Tested with Chrome and Edge)
My workaround was this:

```
/* Workaround for Edge content shift | xxxxx-zen */
html {
    margin-left: calc(100vw - 100%);
    margin-right: 0;
}
```

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on a simple site using Browserstack: **Windows 11 + Microsoft Edge 114 (latest)**
- If you watch the entry title during the page switch, you can see the content move slightly to the left to accommodate the vertical scroll bar.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/f96234cb-5fd4-4642-bfb1-4eedb89c25be

📌 ACTIONS
- Assigned to Non-Urgent

**Comment by Robertght** [comment]
I can still replicate this on a Windows 11 machine using Chrome.

**Comment by madhusudhand** [comment]
It is not a problem with WordPress. It is a general browser/operating system behaviour.
It can be avoided by switching to dynamic scrollbars in operating system settings (sometimes in browser settings).

In windows, update the following settings.

* Settings → Ease of Access → Display
* Toggle Automatically hide scrollbars (On: Dynamic scrollbars, Off: fixed scrollbar)

Closing this as not relevant to WordPress.
