### ISSUE TITLE
Assembler step got reset after completing checkout flow after upgrading to premium

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#78662]
### Quick summary

When a user selects a premium color/font in the assembler step, the user will be asked to upgrade to Premium plan. However, after completing the checkout, the user will be redirected to an empty assembler step. The preselected patterns and color are gone.

@Automattic/lego 

### Steps to reproduce

1. Start with a free site.
2. Go to the Theme Showcase (Appearances => Themes)
3. Scroll and click `Start designing` in `Design your own` section
4. Assemble header/homepage/footer
5. Choose any premium color
6. Confirm the modal
7. Complete the checkout

### What you expected to happen

Got redirected to the assembler step with preselected patterns and color

### What actually happened

Got redirected to the assembler step with empty state.

https://github.com/Automattic/wp-calypso/assets/1525580/294476c2-4e59-4440-b917-22687c591e69

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/78668
