### ISSUE TITLE
Reader: In the Conversations sections, clicking on "Read more" or "Reply" to a comment, opens the post instead.

### ISSUE THREAD

**Issue by christianguerrag** [Automattic/wp-calypso#78677]
### Quick summary

Using the reader, in the conversations section, when clicking the Reply button to reply to a comment, it opens the post instead of showing a reply box as it used to. 
If there is a long comment, only the beginning is shown with the text "Read more" link that should expand the text, but instead the post is opened. If you go back to the post, you can see that the text expanded after the fact.

### Steps to reproduce

1. Open the reader.
2. Follow a conversation with long replies to other comments.
3. Go to the Conversations section.
4. Find the conversation with the shortened comments with the link "Read more"
5. Click on "Read More", or click to "Reply".

### What you expected to happen

When clicking "Read more" the comment should expand so you can read the entire comment.
When clicking "Reply" a comment box should appear allowing you to directly reply to the comment from there.

### What actually happened

In both cases, the whole post opens in the reader. 
You would then have to find the comment again so you can read it or reply to it, which can be hard when there are a lot of comments.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported in 6460487-zen

When you click anywhere in the text of a comment, the post opens which seems related to this behavior.
If you highlight a text from a comment, you can click the Reply or Read More button, and the expected behavior occurs.

https://github.com/Automattic/wp-calypso/assets/46269032/008a1fc0-b5ab-4a46-b869-663a5534cf40

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Interacting with any part of the comments (`Read More`, `Reply`, or clicking in the comment field within the reader) all redirect to the post within the reader - adding an extra step that doesn't feel necessary or helpful.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/79aa3131-7780-452c-8b73-f34688ac6b02

📌 ACTIONS
- Assigned to @Automattic/loop

**Comment by christianguerrag** [comment]
Hi @cuemarie the user in 6460487-zen followed up to note that clicking anywhere on the text of a comment also redirects to the post within the reader. I mentioned this in the report, but I thought this was the expected behavior, so I better mention it just in case it is not.

**Comment by bluefuton** [comment]
This seems to be a regression related to the post card. The click handler for the card is overriding the actions on the comment itself.

**Comment by roo2** [comment]
I was just looking at the post card functionality, I should be able to look at this tomorrow 👀

**Comment by roo2** [comment]
raised https://github.com/Automattic/wp-calypso/pull/80603
