### ISSUE TITLE
Themes: Remove the Upsell Banner

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#78695]
Part of https://github.com/Automattic/dotcom-forge/issues/2227
Follow-up to https://github.com/Automattic/wp-calypso/issues/78694

Once the new upsell modals are applied to all theme types in the Theme Details screen, we'll remove the upsell banners as not needed anymore.

<img width="1139" alt="Screenshot 2023-06-27 at 17 40 40" src="https://github.com/Automattic/wp-calypso/assets/2070010/bcb536d2-513c-4c5c-a0c8-2ba8781c3a9f">

**Comment by dsas** [comment]
Done in https://github.com/Automattic/wp-calypso/issues/93603
