### ISSUE TITLE
DevDocs: Plan Thank You Card fails to load on first attempt

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7874]
#### Steps to reproduce
1. Open https://wpcalypso.wordpress.com/devdocs on a fresh browser
2. Click the Blocks link on the sidebar
3. Watch the JS console

#### What I expected
The blocks page to load

#### What happened instead
The page loads blank on the first attempt, spamming the following errors into the console.  Refreshing the page then works fine.

```js
devdocs.588dcf2….min.js:14 Uncaught TypeError: Cannot read property 'URL' of null
build-wpcalypso.63c078a….min.js:7 Uncaught TypeError: Cannot read property '__reactInternalInstance$m7amfkjwt84fb311hw0dd9529' of null
getClosestInstanceFromNode @ build-wpcalypso.63c078a….min.js:7
findParent @ build-wpcalypso.63c078a….min.js:84
handleTopLevelImpl @ build-wpcalypso.63c078a….min.js:84
perform @ build-wpcalypso.63c078a….min.js:
18batchedUpdates @ build-wpcalypso.63c078a….min.js:49
batchedUpdates @ build-wpcalypso.63c078a….min.js:10
dispatchEvent @ build-wpcalypso.63c078a….min.js:84
```

cc: @marekhrabe, this error first started after the Plan Thank You Card component was first introduced in https://github.com/Automattic/wp-calypso/pull/7606

#### Browser / OS version
OSX / Linux Chrome

#### Screenshot / Video
![wp-calypso-plan-thankyou-crash](https://cloud.githubusercontent.com/assets/7233112/18276825/5eff7bdc-741a-11e6-862c-d11d7ad5e492.gif)

#### Context / Source
#automated-testing

**Comment by marekhrabe** [comment]
Sorry to break things, fix is ready for review in #7907
