### ISSUE TITLE
Launchpad: Odd redirect back to `/setup/intent/launchpad` on a site with `launchpad_screen` `off` when publishing a post

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#78755]
Ref: p1687983958852119-slack-C0Q664T29

The site's `launchpad_screen` is set to `off`, but the user is being redirected to the `/setup/intent/launchpad?siteSlug=siteSlug` screen after publishing a post on their site, then to `/home/siteSlug`.

After the post is published, the browser URL never updates; it remains `wordpress.com/siteSlug/page/id` throughout this cycle.

Once the post has been published, the user can't edit the post; they get sent back to `/setup`, and then again back to `/home`.

There's a video of the behavior that more accurately shows what's happening in the Slack thread linked above.

**Comment by cuemarie** [comment]
Strange one! I was looking into this with @jp-imagines who reported it.  I can reproduce on the user's site as well, when trying to open the published "Home" page. Console log shows the following when it happens:

```
POST
https://{SITE_ADDRESS}.wordpress.com/wp-admin/admin-ajax.php?frame-nonce=2091b81d88
[HTTP/2 400 Bad Request 401ms]

Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://{SITE_ADDRESS}.wordpress.com’) does not match the recipient window’s origin (‘https://wordpress.com’). 4 [rest-proxy](https://public-api.wordpress.com/wp-admin/rest-proxy/#https://{SITE_ADDRESS}.wordpress.com)
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://{SITE_ADDRESS}.wordpress.com’) does not match the recipient window’s origin (‘https://wordpress.com’). 2 [rest-proxy](https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0#https://{SITE_ADDRESS}.wordpress.com)
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://{SITE_ADDRESS}.wordpress.com’) does not match the recipient window’s origin (‘https://wordpress.com’). 7 [rest-proxy](https://public-api.wordpress.com/wp-admin/rest-proxy/#https://{SITE_ADDRESS}.wordpress.com)
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://{SITE_ADDRESS}.wordpress.com’) does not match the recipient window’s origin (‘https://wordpress.com’). [rest-proxy](https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0#https://{SITE_ADDRESS}.wordpress.com)
```

📌 ACTIONS
- Assigned to Serenity who's already reviewing, thanks y'all!
- Gave High priority as this is nearly a blocker for the user, who must unpublish any content to edit it further.

**Comment by cuemarie** [comment]
Also noting that the redirect happens from both Calypso and /wp-admin. When you start from /wp-admin and try to edit the published page, the browser URL does update; first showing the post's wp-admin URL, then the launchpad URL, then /home/site_address.

Within Calypso, the browser URL retains the `wordpress.com/siteSlug/page/id` URL throughout the process.

**Comment by sixhours** [comment]
Apparently the user's site should not have the `design-first` intent after launching; this site retained that site intent which is causing the redirect behavior for all published pages/posts. 

Explanation here: p1688054125326909/1687983958.852119-slack-C0Q664T29

@lupus2k is going to reset the user's site intent manually, that should fix the issue!

**Comment by cuemarie** [comment]
@sixhours Any need to keep this open to investigate why the `design-first` intent remained after launch, or shall we close this out now that the user's issue is addressed?

**Comment by valterlorran** [comment]
This was fixed by https://github.com/Automattic/wp-calypso/pull/78869
