### ISSUE TITLE
Reader: New subscribed site's posts aren't appearing in Latest feed of Reader

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#78757]
### Quick summary

Following a site can sometimes result in the site's posts missing from the Reader posts list 

### Steps to reproduce

1. Log in to a WordPress.com account.
2. Visit Reader > Search ( https://wordpress.com/read/search ) and search for https://automattic.design/ - Follow this site
3. Return to Reader > Latest ( https://wordpress.com/read ) and look for recent posts from the new site you've followed

### What you expected to happen

The newly followed blog's posts would be added to my reader

### What actually happened

The newly followed blog's posts are missing.

https://github.com/Automattic/wp-calypso/assets/27249804/7d59e5fd-9426-43d5-b9ad-70123e5f7b55

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Originally reported here: https://github.com/Automattic/wp-calypso/issues/59421

**Comment by cuemarie** [comment]
📌 ACTIONS
- Assigned to @Automattic/loop

**Comment by davemart-in** [comment]
cc @gibrown is this expected with elastic search? Is a delay expected, or should this be instantaneous?

**Comment by gibrown** [comment]
> is this expected with elastic search? Is a delay expected, or should this be instantaneous?

The main following feed isn't powered by ES.

It may just be caching, or maybe we don't backfill the feed after subscribing. I haven't looked at how the main feed works in a long time.

**Comment by davemart-in** [comment]
Okay, thanks for the additional context @gibrown. Adding this to our bugs queue.

**Comment by cuemarie** [comment]
Just to update after my triaging yesterday, I'm still not seeing Automattic Design's posts in my `latest` feed. Will check back in periodically and update if they appear after a certain time!

**Comment by davemart-in** [comment]
@cuemarie thanks for the update! I just flagged this in our channel to see if someone can take a look: p1688065124553889-slack-C03NLNTPZ2T

**Comment by roo2** [comment]
hmm so far I've found that there's something strange going on with the feed ID for automattic.design.
The feed_id for automattic.design should be https://wordpress.com/read/feeds/109222417. But when the user follows that blog, the posts are looked up based on the ID `78515772` which returns no results. 

In the past we've had issues with blogs that have gone from simple to atomic which included changing the `feed_id`. I wonder if something similar is happening in this case.

**Comment by roo2** [comment]
yep, it looks like there is an old entry for http://automattic.design from 2020 

`http://automatticdesign,wordpress,com/` blog_id `131799462`

And the user is mistakenly getting subscribed to this site instead of the new site

`https://a8cdesignsimple,wordpress,com/` blog_id `182890486`

It looks like the old site was already added to the `feedbag` table with the URL `http://automattic.design`, and that's why it's being followed instead of the new site.

Next I need to figure out how this happened, work out a fix. And hopefully then try to work out if other sites are affected and how they can be updated.

**Comment by roo2** [comment]
I think that the migrate subscribers tool needs to be used to migrate the old subscribers to the new blog, this tool also should fix the `feedbag` table which backs these subscriptions.

I'll run it now 🤞 🙂

**Comment by roo2** [comment]
yes, this has fixed it. And they'll be pleased to know that their followers were migrated as well :)

**Comment by davemart-in** [comment]
Good sleuthing! Thanks for the quick resolution @roo2!
