### ISSUE TITLE
NUX: Trampoline step 1 wording

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#7877]
With https://github.com/Automattic/wp-calypso/pull/7831, paid users will go through default Trampoline NUX, so we'll want to make a small edit to the copy in the first step:
- current: Manage your site from the :wp: My Site menu. Change your theme design, add posts or pages, or upgrade your plan.
- update: Manage your site from the :wp: My Site menu. Change your theme design, add posts or pages, or manage your plan.

(Is there a better verb than "manage," which is already used to start the message? Open to suggestions).
- optional logic: if we want to make it more complex, we could persist "upgrade" for all users except those with the Business plan (for which there is no way to upgrade).

![](https://cloudup.com/ccOLzohdmC9+)

**Comment by lsinger** [comment]
Closing since this now has the `manage` wording.
