### ISSUE TITLE
React 18: Upgrade to client rendering apis warning message.

### ISSUE THREAD

**Issue by kozer** [Automattic/wp-calypso#78773]
### Quick summary
We updated to React 18, and from this version, the rendering method has changed.

More info can be found [here](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis).

Visiting almost every page shows the following warning

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch
```

### Steps to reproduce
1. Visit `/sites` as an example. But this has effect to other pages as well (eg `/home`)
2. Open the developer console.
3. Make sure that you see the warning mentioned above

### What you expected to happen
This warning no longer appearing

### What actually happened
The warning appears

### Impact
All

### Available workarounds?
Yes, not easy to implement

**Comment by danielbachhuber** [comment]
cc @noahtallen @tyxla

**Comment by tyxla** [comment]
This warning is expected. If you take a look at @noahtallen's description in the [PR that upgraded dependencies to React 18](https://github.com/Automattic/wp-calypso/pull/77046), we're intentionally not enabling concurrent mode:

> Note: this does not yet enable the new rendering mode -- that will likely be a follow-up due to the size of this PR!

We're still aiming to try it out, and it is one of the next steps, but it will be a separate effort with its own extended testing round. For the time being, we're going with the old rendering mode, and the notice is expected in dev mode. I've announced that with some additional context in p4TIVU-aFJ-p2 for posterity. 

Going to close that one in the meantime - let me know if you have any other concerns!

**Comment by kozer** [comment]
@tyxla , just FYI, I have already created a pr that has the appropriate changes for that to work. It's [here](https://github.com/Automattic/wp-calypso/pull/78839).

In case we want to enable this, this  pr will be a good start (I guess only tests needs to be updated, as from a quick navigation and testing several features, everything seems to work just fine )

cc: @danielbachhuber , @noahtallen

**Comment by tyxla** [comment]
Thanks for that work @kozer, we appreciate it! 

@noahtallen let's use that PR when exploring if there are any other changes we need to do other than tests.
