### ISSUE TITLE
Cookie banner toggles always on by default

### ISSUE THREAD

**Issue by ahegyes** [Automattic/wp-calypso#78772]
### Quick summary

Hi there,

The `privacy-toolset` package of Calypso includes a cookie banner. Part of the cookie banner is a second view where the visitor has granular control over the type of permissions they want to grant/disallow. There are 3 buckets: `essential`, `analytics`, and `advertising`. 

Those get initialized/rendered [in this file](https://github.com/Automattic/wp-calypso/blob/trunk/packages/privacy-toolset/src/cookie-banner/customized-consent.tsx). The initial value of the buckets gets imported [from this file](https://github.com/Automattic/wp-calypso/blob/trunk/packages/privacy-toolset/src/cookie-banner/consts.ts) where you can see that they always start as `true`, i.e. as `toggled on`. 

That is fine for opt-out regions like the US, for opt-in regions like the EU, at least the `advertising` bucket must be `false` by default (A8C Slack source: p1687885161750719/1685714798.062599-slack-C018UMRUN3V).

### Steps to reproduce

1. Implement the cookie banner on a website
2. Visit the site from within the EU (or use VPN)
3. Click on `Customize`

### What you expected to happen

The `Advertising` toggle should be turned off by default

### What actually happened

The `Advertising` toggle is turned on by default

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by klasharr** [comment]
https://github.com/Automattic/wp-calypso/pull/78805

**Comment by cuemarie** [comment]
Hey @klasharr , just to confirm, can we close this as resolved thanks to https://github.com/Automattic/wp-calypso/pull/78805 ?

**Comment by klasharr** [comment]
yes.
