### ISSUE TITLE
Image Editor: Private Sites

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#7878]
Investigate if the image editor works with private sites.

1. Navigate to https://wordpress.com/settings/general
2. Select a site
3. Update privacy settings to private
4. Navigate to http://calypso.localhost:3000/post
5. Select a the site you just updated
6. Open the media editor. Click "Edit" on an image
7. In detail view, click "Edit Image" in the top right corner

Does the editor load with the correct image, or do we get CORS permission errors? If it's the latter disable the "Edit Image" button when a site is private.

**Comment by retrofox** [comment]
@gwwar I think it should be set to `private` instead of `hidden`, right?

**Comment by gwwar** [comment]
Oh good catch, I'll update the summary

**Comment by retrofox** [comment]
related issues:

* https://github.com/Automattic/wp-calypso/issues/5099

**Comment by gwwar** [comment]
@retrofox if this is not available for private sites, we can go ahead and disable the "Edit Image" button when we detect.

**Comment by retrofox** [comment]
> Does the editor load with the correct image, or do we get CORS permission errors? If it's the latter disable the "Edit Image" button when a site is private.

We get CORS permission errors since photon wont work with no public sites.
