### ISSUE TITLE
Add Settings Button on the top-right corner.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78795]
It can be a cog item first. We'll refine the design later. It should go to `/me/notifications`.

**Comment by aleone89** [comment]
Hello! 

Just noting: 

"A user asked to have the option to hide/turn-off comments from Reader. The user wants to be able to scan through the latest posts rather than see comments in between, since some of the comments are lengthy."

zen-6708781

**Comment by yansern** [comment]
Renamed this to just Settings as Comments is handled here.
https://github.com/Automattic/wp-calypso/issues/81896
