### ISSUE TITLE
Image Editor: Jetpack Sites

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#7880]
Investigate if the image editor works with Jetpack sites.

1. Navigate to http://calypso.localhost:3000/post
2. Select a Jetpack site
3. Open the media editor. Click "Edit" on an image
4. In detail view, click "Edit Image" in the top right corner

Does the editor load with the correct image, or do we get CORS permission errors? If it's the latter disable the "Edit Image" button when a site is a Jetpack site.

**Comment by retrofox** [comment]
It seems work correctly. I did the following steps:

1) Select a jetpack site
2) Start to create a new post
3) Open image modal
4) Add and upload a new image
5) Start to edit this image
6) Cut the image creating a new one
7) Insert the image into the post body
8) Publish the post

http://retrofocs.wpsandbox.me/2016/09/06/image-edited-in-a-jetpack-site/

**Comment by retrofox** [comment]
`[POST]` request is ok.

```
Request URL:https://public-api.wordpress.com/rest/v1.1/sites/115878046/media/new?http_envelope=1
Request Method:POST
Status Code:200 
Remote Address:127.0.0.1:8080
```

**Comment by gwwar** [comment]
Thanks @retrofox could you also test what happens when [photon](https://jetpack.com/support/photon/) is turned off?

**Comment by retrofox** [comment]
**photon disabled**
Disabling photon it seems work rightly as well.

http://retrofocs.wpsandbox.me/2016/09/06/original-and-cropped-images/

**Comment by gwwar** [comment]
Nice! I'm going to close this out then.
