### ISSUE TITLE
Checkout does not show domain features in sidebar for transfers

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#78855]
In checkout, if you are purchasing a Domain Transfer product, you are effectively purchasing a Domain Registration. However, the sidebar that typically shows the list of domain features (SSL, Privacy, Refund policy, etc.) does not display for Domain Transfers. We should make it visible for that product.

![Markup 2023-06-29 at 20 28 19](https://github.com/Automattic/wp-calypso/assets/2036909/c93bbe26-4d36-4963-b860-4aca0ad79d3e)

**Comment by ebinnion** [comment]
PR here: https://github.com/Automattic/wp-calypso/pull/79093
