### ISSUE TITLE
Launchpad: Add preview to the Customer Home

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#78865]
Add the site preview to the Customer Home.

We possibly need to create a new Card and have it registered in the Site Setup view:

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Subzr%2Sivrjf%2Sfvgr%2Qfrghc.cuc%3Se%3Q14n331p9%2330-og

On the front-end we would need to register the Preview component here:

https://github.com/Automattic/wp-calypso/blob/8ec8683e99820b415ca6adb6fcb93ae3ee8334c5/client/my-sites/customer-home/locations/tertiary/manage-site/index.jsx#L26-L32

<img width="577" alt="Screen Shot 2023-06-30 at 17 23 21" src="https://github.com/Automattic/wp-calypso/assets/1234758/2bc1073a-ef42-4247-82ae-57635e63e4af">

Figma: 9wpoYJrMlYKAKUYvVBMN74-fi-3879_91663

**Comment by andres-blanco** [comment]
Closed by 
* https://github.com/Automattic/wp-calypso/pull/79024
* D115839-code
* D115362-code
