### ISSUE TITLE
SendInBlue: Name change and referral link not working.

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#78877]
### Quick summary

SendInBlue has updated its name to Brevo. Additionally, if you click the SendInBlue CRM link in WordPress you receive an error.

<img width="531" alt="Screenshot 2023-07-02 at 6 24 24 PM" src="https://github.com/Automattic/wp-calypso/assets/10124024/abb329d1-4db3-4317-80a1-15e2ad64b5a7">
<img width="928" alt="Screenshot 2023-07-02 at 6 24 50 PM" src="https://github.com/Automattic/wp-calypso/assets/10124024/202e54f6-290d-4f6f-b0a2-c1d075c8b1f5">

### Steps to reproduce

First issue: https://www.brevo.com/

Second issue:
1. Visit **Tools** -> **Marketing**
2. Scroll down to _Turn your visitors into customers_
3. Click **Start with CRM**

### What you expected to happen

You should be redirected to Brevo with our referral link.

### What actually happened

You get an error.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – Replicated 
Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
The issue can be replicated exactly as described above. Clicking on the "Start with CRM" button redirects to the `partners.brevo.com` and the page was not found.

![Screenshot 2023-07-04 at 18 31 26](https://github.com/Automattic/wp-calypso/assets/67279475/cc7c4021-b71e-4638-9cbc-5d09224c78ae)

📌 ACTIONS
Assigned to @Automattic/martech

**Comment by gmovr** [comment]
Ref our convo on Slack (p1688488526192419-slack-CFFF01Q4V), let's get rid of this card. I'll open a PR. We can revisit and add something else in the future. 👍

**Comment by gmovr** [comment]
Did a PR here. This will remove the card https://github.com/Automattic/wp-calypso/pull/79121 @zachspears  @karenroldan
