### ISSUE TITLE
Admin users don't have access to the staging site, only the owner

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#78875]
### Quick summary

A user created a staging site but the 4 admin users didn't have that site appear in the dashboard. The admins were there when I checked CLI. I was also able to see them when logged in to the owner account but I was not able to see the site when logged in as one of the non-owner admins. 

The issue was resolved when I manually added the Jetpack connection for the non-owner admins. 

### Steps to reproduce

- Create a staging site as explained here: https://wordpress.com/support/how-to-create-a-staging-site/
- Log in to the site using the WordPress.com login for all admin users

### What you expected to happen

I would expect all admin users to have access to the staging site using their WordPress.com login as they are users on the site. 

### What actually happened

The site was not showing up for the users and I needed to manually connect the site to their account by opening /wp-admin and confirming their connection. 
Confirming this gave a warning that the user was already connected (which it wasn't) but it did connect the site to the account. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Opening the site /wp-admin and clicking on Confirm in he Jetpack connection screen adds the site to the admins' dashboard. 
If this requires manually confirming the admin users (who are not the owners) this should be added to the documentation. 

6488360-zd

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Before creating a staging site, I added a user as Admin. The staging site was successfully created but it's not available to the admin user. 
- The issue was replicated exactly as described above. 

📌 ACTIONS
Assigned to @Automattic/yolo

**Comment by kozer** [comment]
D115331-code

**Comment by danielbachhuber** [comment]
This fix is now shipped 🔨
