### ISSUE TITLE
Subscribers Page: Add ability to export emails of both external and WPCOM subscribers.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78888]
The export button should:
- Export emails of both external and WPCOM subscribers.
- Renamed to "Download subscribers as CSV".

- [x] Once this feature is out, let's inform folks in the following post: p4H3ND-1wS-p2#comment-3269. → p4H3ND-1wS-p2#comment-3304

**Comment by ivan-ottinger** [comment]
Once this feature is out, let's inform folks in the following post: p4H3ND-1wS-p2#comment-3269.

(I have added this into the description of this task - so we don't forget)

**Comment by ivan-ottinger** [comment]
I have shared the info that the feature will be launched to production soon: p4H3ND-1wS-p2#comment-3304.

**Comment by simison** [comment]
Couple follow-ups:

- Wpcomhappy
- Jpophappy
- Check if docs need some wording updates

**Comment by ivan-ottinger** [comment]
> Couple follow-ups:
> - Wpcomhappy
> - Jpophappy
> - Check if docs need some wording updates

Just to close the loop: Related discussion: p4H3ND-1wS-p2#comment-3306.
