### ISSUE TITLE
Assembler: Copy review July 2023

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#78882]
## Description

This issue proposes another round of copy review, following-up the discussions from pbxlJb-45X-p2. Some of the potential improvement during the walkthrough session:

1. Survey CTA - The copy is vague, specifically the text "our product". 
![Image](https://user-images.githubusercontent.com/797888/250429374-4452866e-9a82-4f3e-be79-ff41122c04a8.png)

2. Consistent navigation heading

| Header | Homepage | Footer |
| --- | --- | --- |
| ![Image](https://user-images.githubusercontent.com/797888/250429682-accb6661-6213-4c0e-97b6-1a4fd3d5ccb5.png) | ![Image](https://user-images.githubusercontent.com/797888/250429711-f5ae4a14-de6a-4ffb-bc20-0805eb5538db.png) | ![Image](https://user-images.githubusercontent.com/797888/250429725-363707ab-30ef-4854-a5fe-31ebc82a614b.png) |

3. Consistent navigation buttons

| Header | Homepage | Footer |
| --- | --- | --- |
| ![Image](https://github.com/Automattic/wp-calypso/assets/797888/0a9d525a-b1a3-4908-9017-10751dad0574) | ![Image](https://github.com/Automattic/wp-calypso/assets/797888/e2d2a941-9f23-4f5c-8e48-ff6469337c24) | ![Image](https://github.com/Automattic/wp-calypso/assets/797888/03ca746c-8ca3-4170-af21-e0186dc57924) |

4. Free/Premium label

| Colors | Fonts |
| --- | --- |
| ![Image](https://github.com/Automattic/wp-calypso/assets/797888/cf4ac653-3743-4a25-b698-34853fe44f7a) | ![Image](https://github.com/Automattic/wp-calypso/assets/797888/51a911d8-7c6c-46c0-998c-8e110764f360)|

**Comment by miksansegundo** [comment]
The consistent navigation heading, `Add header` and `Add footer`, has been addressed in https://github.com/Automattic/wp-calypso/pull/78581. We are still waiting for translations.

Please, refer to the latest version of the navigation buttons in that PR as well. We will use `Save sections` rather than `Save homepage`.

**Comment by lucasmendes-design** [comment]
There is a need to improve the CTA and the main page of SA. It's something that Pablo said a lot, sometimes we say design, homepage, or themes. I'll P2 about this today. So, we can unify all places into just one (Themes). 

<img width="814" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/3ea681a4-2eb5-46a5-8bcf-a085feca6170">

<img width="672" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/7413fa3c-509a-494b-898e-54fdb99d338a">

**Comment by lucasmendes-design** [comment]
Here is the [P2](https://marvelousp2.wordpress.com/2023/07/06/unifying-copy-on-theme-showcase-pages/).

**Comment by autumnfjeld** [comment]
@taipeicoder I think the only item in this list that needs to be done is this Save.  It should be `Save sections` to be consistent with `Save header` and `Save footer`.   Is that correct?





![Image](https://github.com/Automattic/wp-calypso/assets/5665959/e30adc72-def1-465b-9965-18e4c90b16de)

I'll add to this issue: [Assembler: Copy updates Aug 1#80118](https://github.com/Automattic/wp-calypso/issues/80118)

Then we can close this, ya?

**Comment by taipeicoder** [comment]
Yes, closing this.
