### ISSUE TITLE
Subscribers Page: One more heads-up post for Subscribers Page.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78894]
This heads-up post is different from the previous heads-up post, we need to put one out that inform HEs of the following:

1. The old `/people/subscribers` page will be removed and replaced by `/subscribers`. And users entering `/people/subscribers` will be redirected to `/subscribers.
2. The privacy policy will be updated to make it clear that following a subscription also means users consent to provide site owners their email. Context: p4H3ND-1wS-p2
3. Also include a list of new improvements, e.g.
  - Email & WPCOM user filter dropdown
  - Export button now exports both Email & WPCOM subscribers.
  - Other fixes that will be ready this milestone.

**Comment by ivan-ottinger** [comment]
I have created and published the heads-up post: p7DVsv-hYp-p2.
