### ISSUE TITLE
Subscribers Page: Replace `/people/subscribers` with `/subscribers`.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78893]
Here are the to-dos:
- [x] When users arrive at `/people/subscribers`, they should be redirected to `/subscribers`.
- [x] The Subscribers tab on `/people` page should be removed.

Also take note that the Classic View toggle is not needed for Subscribers page, so we don't need to match parity on Subscribers page.

**Comment by ivan-ottinger** [comment]
When removing the Subscribers tab from the Users page, we will also want to update the copy on the page:


![Image](https://github.com/Automattic/wp-calypso/assets/25105483/b40135bf-b294-4792-bf6f-6bf7927f6e69)

I think the new copy can be as follows:

```
Invite team members to your site and manage their access settings. [Learn more](https://wordpress.com/support/invite-people/).
```

Related user-facing documentation will need to be updated as well: https://wordpress.com/support/invite-people/m but we have a separate task for it: https://github.com/Automattic/wp-calypso/issues/78053.

**Comment by ivan-ottinger** [comment]
With only one tab remaining on the Users page, it might be worth reconsidering the design of this page - or - leaving it out to be addressed later when the whole Users page is redesigned.


![Image](https://github.com/Automattic/wp-calypso/assets/25105483/875ac1f2-6792-444f-8e63-af86d0ccb0f7)

**Comment by yansern** [comment]
> With only one tab remaining on the Users page, it might be worth reconsidering the design of this page - or - leaving it out to be addressed later when the whole Users page is redesigned.

There is possibly a plan to create a new tab called Viewer. cc @vishnugopal

**Comment by vishnugopal** [comment]
@yansern Yup that's the current plan! Having a page with just one tab in there doesn't make much sense, and this can possibly fix https://github.com/Automattic/wp-calypso/issues/77814

**Comment by ivan-ottinger** [comment]
Thank you for sharing, @vishnugopal! We are aiming to hide the Subscribers tab next week. Do you have any estimated timeframe for the addition of the Viewers tab? (just to get an idea to see if it is already in works)

**Comment by ivan-ottinger** [comment]
Hey @yansern 👋 I also noticed that we have the following "Add subscribers" page / tab at `/people/add-subscribers`:

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/f1ec8177-06dc-4e76-978e-4802101353c9)

We could hide it and redirect the URL to `/subscribers` as well. When the user is redirected, they will need to click the "Add subscribers" modal (unless we want to find a way to trigger the modal open as well). I think simple redirection should be enough.

**Comment by vishnugopal** [comment]
> Do you have any estimated timeframe for the addition of the Viewers tab? (just to get an idea to see if it is already in works)

@ivan-ottinger Not yet! We haven't prioritized this work yet, sorry!
