### ISSUE TITLE
HEAD /version?1448477550954

### ISSUE THREAD

**Issue by tsoliangwu0130** [Automattic/wp-calypso#789]

**Comment by codebykat** [comment]
@tsoliangwu0130 Not sure what you were trying to do here but looks like something went very wrong.

**Comment by tsoliangwu0130** [comment]
I am running "make run" command by following the install instructions, and it can't stop.
I have terminated my terminal now, sorry for the inconvenience.

**Comment by codebykat** [comment]
@tsoliangwu0130 That means it's working! :)

Basically, `make run` starts up a local server to serve Calypso pages. It will indeed continue running until you terminate it.

If you go to `calypso.localhost:3000` in your browser while `make run` is running, it will load up the site, and you'll see the browser requests reflected in the terminal window, e.g.

    GET / 200 2844.758 ms - 3812
    GET /calypso/style-debug.css?v=a16d1d68b7 304 67.312 ms - -
    HEAD /version?1448485414300 200 3.683 ms - 20
    HEAD /version?1448485428641 200 0.443 ms - 20
    HEAD /version?1448485439611 200 0.466 ms - 20

Here, the `GET` and `HEAD` portion shows the type of request being made of the browser, the `/version?` part is the URL requested, the `200` is the response (in this case, 200 OK), and the remainder of the line is the time the request took and the response header.

This is coming from the Node server. See also: https://stackoverflow.com/questions/29077355/what-does-get-bla-ms-mean-in-nodejs-console

**Comment by tsoliangwu0130** [comment]
Got it, I really appreciate your response!
