### ISSUE TITLE
Coupons starting with a number does not work 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#78903]
### Quick summary

Coupons starting with a number does not work, while those starting with a letter works.  

### Steps to reproduce

1. In MC Tools, create two coupons: one starting with a number, and another starting with a letter.
2. Go to the WordPress.com dashboard and add an item in the cart.
3. On the checkout page, apply the coupon. 

### What you expected to happen

All valid coupons will work. 

### What actually happened

Only coupons starting with a letter works, and not coupons starting with a number. 

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

On my test site, using this custom coupon **3030keltest** does not get applied: 

<img width="1121" alt="Screenshot 2023-07-03 at 13 28 09" src="https://github.com/Automattic/mc-coupons/assets/36863633/dad602bf-a4b6-469c-9b62-dc4cadcd4e5d">

But a coupon starting with a letter like **kel21320test** works: 

<img width="1080" alt="Screenshot 2023-07-03 at 13 35 27" src="https://github.com/Automattic/mc-coupons/assets/36863633/7d9941a0-19ae-4c5f-b30e-b925550e06b7">

**Comment by cuemarie** [comment]
Hey @kspilarski ! It looks like this is working as designed.  Here's what the FG says about creating coupon codes:

>  The length of the code should be less than 16 characters, and the code should begin with a **letter**. Any non-English letters except for underscore, dot, and dash are disallowed. *While your coupon code may contain numbers, it should always **begin with a letter**.
Source: _Field Guide:_ `/creating-coupon-codes/`
