### ISSUE TITLE
Subscription Management: All round site icons should be square.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78923]
All round site icons should be square on all Subscription Management pages.

This is because site icons are supposed to be square, and round icons refer to user avatars.

**Comment by ivan-ottinger** [comment]
To make sure I understand correctly, the change needs to be made on the Subscription Management for both logged-in and external users - everywhere where the site icon is displayed as circle currently, right?

This includes:

- https://wordpress.com/read/subscriptions (logged-in users)
- https://wordpress.com/subscriptions/sites (external users)
- https://wordpress.com/subscriptions/comments (external users)

![Markup on 2023-07-13 at 14:59:55](https://github.com/Automattic/wp-calypso/assets/25105483/751887cd-29de-4127-b840-30d2cd581693)

![Markup on 2023-07-13 at 15:06:08](https://github.com/Automattic/wp-calypso/assets/25105483/fc0203f7-369e-41f7-ae25-acefec407d09)
