### ISSUE TITLE
Launchpad: Add the Blog task list on the view list

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#78953]
Similar to the "Keep Building" filter, we need to create a filter for the blog intent `maybe_enable_launchpad_blog_intent`(we may want a better naming here), which should hook on the `simple_and_atomic_pre_setup_views` filter.

Example:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Subzr%2Sivrjf.cuc%3Se%3Qqp359np7%2399%2Q115-og

**Comment by nelsonec87** [comment]
Related diff: D115457-code

**Comment by sixhours** [comment]
This has shipped! D115457-code
