### ISSUE TITLE
Launchpad: Create the Blog Launchpad component

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#78952]
Similar to the `client/my-sites/customer-home/cards/launchpad/keep-building.tsx` component, we will need a new component for the Blog intent.

We also need to register it:
https://github.com/Automattic/wp-calypso/blob/82344ac4df52924cd2d6d18dc484c717f4298787/client/my-sites/customer-home/locations/primary/index.jsx#L83

**Comment by sixhours** [comment]
This was shipped in https://github.com/Automattic/wp-calypso/pull/79031
