### ISSUE TITLE
Domains managing and improvements

### ISSUE THREAD

**Issue by JanaMW27** [Automattic/wp-calypso#78986]

**Comment by ebinnion** [comment]
Latest design iteration is here: p9Jlb4-8BQ-p2

**Comment by ebinnion** [comment]
Quake is now actively working on this:

pet6gk-Dp-p2

**Comment by zaguiini** [comment]
The project is shipped. Do we want to keep this issue open and reuse it for the next iterations, or are we creating a new one in the future?

**Comment by ebinnion** [comment]
I've closed it for now. 👍
