### ISSUE TITLE
Feature request: Button to search through all articles and pages?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-calypso#7898]
Dear all, 

What do you think of a button to easily search through all existing articles and pages to quickly being able to find and edit an article or page?

Thereby I am not only referring to drafted articles but the entire content of a page.

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18120232/dc67e390-6f5e-11e6-805f-64e2109e7be1.png)

**Comment by timmyc** [comment]
@orschiro thanks for taking the time to submit the question.  We do have an existing feature that allows you to search through post listings.  From your "My Sites" page, click on "Blog Posts" in the sidebar - at the top of the post listing page, note the search icon in the navigation bar:

![blog_posts_ _wordpress_com_news_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/18854046/8ad2d5e0-83fd-11e6-9525-9a572fb85218.png)

Clicking that search icon will allow you to do a full-text search of all your posts.  You can also filter by post status here, like search "Drafts" for a certain term.

Let me know if that is a valid solution for you.

**Comment by orschiro** [comment]
Thank you @timmyc!

Does this also filter and search pages or only posts?

-Robert

**Comment by timmyc** [comment]
Correct @orschiro - you can use the search utility within any post type listing - so you can do the same on the Page listing, or even custom post types like Testimonials and Projects

**Comment by orschiro** [comment]
That answered my question, thank you very much! 

-Robert
