### ISSUE TITLE
Plans 2023: Remove recordTracksEvent dependency from plans-grid

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#79006]
This is for uncoupling plans-grid component from Calypso dependencies. See PT: pau2Xa-3Cu-p2 

We need to abstract away the `recordTracksEvent` imports (plans-grid cannot import from anywhere other than released NPM packages). 

### How

There are a couple of possible directions, although I think it should be fairly ok (and more trivial) to pass `recordTracksEvent` in as an **optional** prop to the respective exported components that need it (`FeaturesGrid`, `ComparisonGrid`, `PlanTypeSelector`). The prop should be optional.

The alternative could be to pass callbacks for the various actions/events that call this method - more complex and uncertain if it will not just create complexities.

### What to test

That the respective events fire off properly after migration.

**Comment by southp** [comment]
For a record, here is a backing case that could be benefited from this: https://github.com/Automattic/wp-calypso/pull/81816#issuecomment-1724329831 .
