### ISSUE TITLE
Related Products Block causing Woo product pages to Error 500

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#79037]
### Quick summary

clicking a product on a WPcom hosted Woo store leads to Error 500 on the site.

### Steps to reproduce

1. On a site where Woo is installed, add the  "Related Products" block to the "Single Product" template in the site editor.
2. On the live site, go to shop page
3. Click a product
4. See Error 500

<img width="819" alt="Screenshot 2023-07-05 at 16 14 57" src="https://github.com/Automattic/wp-calypso/assets/31009008/602e8d22-5e28-4456-ae27-c9f29609eb8e">

### What you expected to happen

To see the product page

### What actually happened

Error/ Critical message

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by RafaelFunchal** [comment]
```
$ wp post list --post_type=product --format=count
18,717
```

I'm not a developer, but I risk saying the Related Products Block has performance issues in handling stores with thousands of products.

I re-added the block to the Single Product Template and immediately got a new fatal error:

```
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /wordpress/core/6.2.2/wp-includes/class-wpdb.php on line 2397
```

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic –  **Could Not Replicate**


📌 FINDINGS/SCREENSHOTS/VIDEO
- I was not able to replicate this critical error on a test site.  A few specifics on my test environment:
     - WooCommerce version 7.8.2
     - WooCommerce Blocks version 10.5.0
     - Theme: Tazza version 1.0.0
     - Published Products: `6`

After setting up the Related Products block, I also see no PHP errors on the site. 

#### Screenshots/Recordings

**Editor**

![Markup on 2023-07-05 at 14:59:36](https://github.com/Automattic/wp-calypso/assets/27249804/69c659e7-59d1-4ed1-b801-515d62e4a68f)

**Live Site**

![Markup on 2023-07-05 at 15:00:06](https://github.com/Automattic/wp-calypso/assets/27249804/bd6d48da-9ffb-45e0-b453-3a3415ea8d6d)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @davipontesblog I'd say @RafaelFunchal is probably onto something with the very high product count!  That seems like a thread worth pulling on next. Perhaps Woo folks can help the user with alternatives?

**Comment by RafaelFunchal** [comment]
I created a post on the site of the Woo team responsible for Woo Blocks.

pdnLyh-3VR-p2

**Comment by cuemarie** [comment]
Thanks @RafaelFunchal ! Maybe folks there will be able to either replicate on a test site with high product volume, or identify an improvement we can make without replicating. 

Feel free to reopen this if it helps for tracking purposes, or if we're able to track down a way to repro!
