### ISSUE TITLE
Paid Stats: Hide upsell section on Odyssey for paid plans

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#79040]

**Comment by jsnmoon** [comment]
@kangzj, do we have any remaining actionables for this task?

**Comment by kangzj** [comment]
Closed with #79047 

> Know issue: the visibility of individual product upsell doesn't test site plan to see whether supported. The fix is out of the scope of the PR. We'll tackle that in follow up PRs.

We do have an improvement to detect support from site plan. I'll file a separate issue.
