### ISSUE TITLE
Subscriptions: multiple lists with categories

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#79060]
Customers would like to allow subscribing to partial newsletters, instead of receiving them all:

<img src="https://github.com/Automattic/wp-calypso/assets/87168/9b7e4370-e8cc-47f6-b278-259d6f004dcd" alt="" width="400"/>

### Tech notes

This work can be based on existing WP categories as they offer a lot "for free" that is useful.

- Categories come for free with dedicated views in the blog and RSS feeds, and all the UI to manage their names and descriptions. 
- We even have templates for categories in site editor, so you can completely change how a single category looks.
- Adds a layer of clarity to the categories vs tags; categories are more like channels of distribution, that people can subscribe to selectively.
- They are generally more deeply integrated with existing things than if we'd build something custom.

[There's also some existing code](https://jetpack.com/blog/hook-month-control-subscriptions/) to manage sending via categories we can probably be re-used.

In the subscriber table, we'd have to store which categories user is subscribed to. Later we need to handle showing those in the subscription management UI and handle what happens if the categories change/get deleted.

One of the hard parts is figuring out UI for other places to subscribe outside subscribe block: Follow/Subscribe buttons in the Reader and apps. How do we indicate if you've subscribed to the whole site or just specific category?

### Behaviour

- Initially all checkboxes can be selected. If this is the case, we don't need to . Additionally, should there be extra "All" category toggle?
- If I subscribe to all categories, I sort of didn't subscribe to "any" specific one, and we don't store the info anywhere. They just get all emails, and if publisher adds new categories, they will start receiving those, too.
- If I unselect any of the categories, I indicate that I want emails from checked lists only, and we store those category IDs somewhere.
- If publisher removes the category people subscribed to, we should handle that gracefully somehow. Just unsubscribe the people, or migrate them to another category? How do we ask customer?

### Admin

How does one manage categories for the newsletter? 

- Under newsletter settings, do they pick a category and all sub-categories are newsletters?
- Under newsletter settings, do they just mark one-by-one all categories as newsletters?
- Do all the categories just show up as categories for subscribers, and no need to limit which are blog categories and which newsletter? This is likely best and simplest approach. There should still be setting to "support multiple newsletters via categories" in Newsletter settings though. By default newsletter doesn't have categories support.

### Scope & Release

For the initial release for the Team 51 customer in September, we can:

- Limit the UI work to be quite minimal; we can focus more on the site's frontend UI and publishing experience, and leave out the dashboard work.
- Release for this single customer only, gather feedback, and continue working on the other UI parts before wider release.
- We can release first on WP.com to gather feedback, and then in Jetpack.

### Questions & follow-up projects

- Importing/exporting can take into account categories, to allow importing only to specific category.
- How should categories be presented in stats, if at all?
- How should categories be presented in subscription management page for the subscriber?

    <img src="https://github.com/Automattic/wp-calypso/assets/87168/517f9ec0-7761-4db9-93df-147e39f2a5a2" width="600"/>

- How should categories be presented in subscriber management? Should publisher be able to modify their categories?

    <img src="https://github.com/Automattic/wp-calypso/assets/87168/f93dbd2d-44f6-4930-8af0-a43c036b9463" width="600"/>

- How the UI outside subscribe block should work? Follow/Subscribe buttons in the Reader and apps for example. How do we indicate if you've subscribed to the whole site or just specific category?

- What kind of layout options and flexibility the block should support? Below some very elaborate screenshots from real newsletters, but v1 can be much simpler:

    ![Image](https://github.com/Automattic/wp-calypso/assets/87168/a362c4d4-dc63-4c16-bc57-244ea80968cc)

    ![Image](https://github.com/Automattic/wp-calypso/assets/87168/e63be0a5-65d9-4dcf-ad80-3f91ab188f67)

**Comment by dhanson-wp** [comment]
Idea also shared by @mikemayhem3030 https://github.com/Automattic/dotcom-forge/issues/2953. @simison we are trying to cross reference some features on your roadmap with our Public project.

**Comment by simison** [comment]
Project thread pdDOJh-2f9-p2

**Comment by allilevine** [comment]
New main thread: pdDOJh-2gB-p2

**Comment by simison** [comment]
> Newsletter Categories has been in the works for a few weeks. apex-team released the last iteration just a few days ago (p7DVsv-iWB-p2). So far, more than 1,000 sites are already using Newsletter Categories.

via p9Jlb4-9ou-p2
