### ISSUE TITLE
Plans 2023: Button Styling and Copy Inconsistencies

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#79085]
### Quick summary

@lucasmendes-design [has spotted several design inconsistencies ](https://github.com/Automattic/wp-calypso/issues/78298#issuecomment-1595010657) with the plans pricing page that we should address:

### Upgrade Button
`Upgrade to yearly` is confusing given the context in the image below: 
<img width="552" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/5dcd7884-22e3-4324-82f5-1a244eb87288">

Let's use `upgrade` for all, so the buttons are aligned. 

### Contact Support Button
Let's not use `contact support` and change all buttons to the same hierarchy and copy. "Contact support" and "Downgrade" have different styles (dark gray vs light gray and Bold vs Regular fonts). These buttons should be with the same copy and style. 
<img width="470" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/7caf96d5-5076-4ff3-aa48-f49c71280cdb">

Example
<img width="820" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/6199a977-28b7-4bea-a2bb-aa6bb6a526b0">

**Comment by jeyip** [comment]
This seems low priority given other work we're focused on, but cc @southp for confirmation

**Comment by lucasmendes-design** [comment]
Let me know if you need some UI or help with this @jeyip. Happy to collaborate.

**Comment by southp** [comment]
To close the loop here, the confusing "contact support" button is tracked and worked on separately here: https://github.com/Automattic/martech/issues/1458

**Comment by southp** [comment]
Close this as it's covered by Automattic/martech#1458.
