### ISSUE TITLE
Bug: Calypso `/plans/{siteSlug}` page crash when it's a Jetpack site and has Stats product

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#79092]
Error Stack:

![Image](https://user-images.githubusercontent.com/1425433/251586510-058e6410-05b7-463c-9863-4c88a39d727a.png)

It seems to me, we have to add icons for Stats product and also probably set a default value if a product doesn't have an icon here:

https://github.com/Automattic/wp-calypso/blob/997598e7c6eae1256a1b7182bbf4ad9b58f7db16/client/my-sites/plans/jetpack-plans/product-store/utils/get-product-icon.ts#L94

I asked for a new icon for Stats: p1688695842023279-slack-C0438NHCLSY
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/79402
```

**Comment by jsnmoon** [comment]
This appears to be fixed 🚀
