### ISSUE TITLE
Domains: Invalid e-mail error message missing domain name

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#7910]
#### Steps to reproduce
1. Starting from URL: https://wordpress.com/domains/add/example.wordpress.com
2. Select a domain name, either accept or decline GApps
3. Fill out the e-mail field of the contact information form with a simple string with no `@` sign

#### What I expected
A descriptive error message

#### What happened instead
The error message `The “Email” field does not appear to be valid. does not appear to be a valid domain.` is missing a word (shown in green below).  If the `@` sign is included, the domain name is parsed out from what's after the sign, but if there's no @ it doesn't know what to do.

cc: @klimeryk - Error appeared after #7306 was fixed

#### Browser / OS version
OSX Chrome v51

#### Screenshot / Video
<img width="354" alt="screen shot 2016-09-07 at 9 36 00 am" src="https://cloud.githubusercontent.com/assets/7233112/18313988/2c5d49dc-74df-11e6-9bf8-884fdbc803f6.png">

#### Context / Source
#manual-testing

**Comment by klimeryk** [comment]
Argh 😣 Sorry about that! I've merged and deployed a fix for this now too - I hope this time without introducing any new regressions... 😄
