### ISSUE TITLE
Incorrect subheading style and copy on the Woo Core Profiler Jetpack screen

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wp-calypso#79113]
#### Steps to reproduce

1. Create a JN site using WooCommerce trunk branch
2. Go to Core Profiler flow
3. Install plugins and confirm you're redirected to Jetpack connection page

Figma: Y5pUYSJPsGEud1vknUZhi8-fi-2283_38006

#### What I expected

Subheading used on the Jetpack screen should have the same style compared to the others on Core Porfiler.

Copy:

> We'll make it quick – promise. In order to take advantage of the benefits offered by Jetpack, you'll need to create a WordPress.com account.  Already have one? Log in

#### What happened instead

It’s kind of lighter.

**Comment by moon0326** [comment]
I've compared it with Figma and they look the same to me, except for the letter spacing 🤔 

![text-comp](https://github.com/Automattic/wp-calypso/assets/4723145/ef791034-99f5-4cc1-a375-b37a3ebf08d3)

Text in white background is from WPCOM, gray from Figma.

**Comment by moon0326** [comment]
@chihsuan in case you missed it 🙏

**Comment by chihsuan** [comment]
> @chihsuan in case you missed it 🙏

Thanks for the ping! @moon0326 yeah, it looks the same to me now. 🤔 

Hey @verofasulo 👋  Could you take a look to see if the current subheading style and copy are correct? Thank you! 🙂 

Figma: Y5pUYSJPsGEud1vknUZhi8-fi-2283_38006

To view the screen:

1. Open a incognito window
2. Go to https://wordpress.com/jetpack/connect/authorize?client_id=219799967&redirect_uri=https%3A%2F%2Fdull-wasp.jurassic.ninja%2Fwp-admin%2Fadmin.php%3Fhandler%3Djetpack-connection-webhooks%26action%3Dauthorize%26_wpnonce%3D3f81798d85%26redirect%3Dhttps%253A%252F%252Fdull-wasp.jurassic.ninja%252Fwp-admin%252Fadmin.php%253Fpage%253Dwc-admin&state=1&scope=administrator%3Ae0a0df66fa6e6d2b7c0969d37fa165d4&user_email=test%40automattic.com&user_login=chihsuanhuang&jp_version=12.1.1&secret=uDAtkilHDeWP4lnJewWTAH5Gv7EQVJxt&blogname=Dull+Wasp&site_url=https%3A%2F%2Fdull-wasp.jurassic.ninja&home_url=https%3A%2F%2Fdull-wasp.jurassic.ninja&site_icon&site_lang=en_US&site_created=2023-06-05+07%3A02%3A54&allow_site_connection=1&locale=en&_ui=42367338&_ut=wpcom%3Auser_id&calypso_env=production&_as=wp-cli&purchase_nonce=i5V9KqSt&_wp_nonce=e48c9f86a6&redirect_after_auth=https%3A%2F%2Fdull-wasp.jurassic.ninja%2Fwp-admin%2Fadmin.php%3Fpage%3Dwc-admin&site=https%3A%2F%2Fdull-wasp.jurassic.ninja&from=woocommerce-core-profiler

**Comment by verofasulo** [comment]
Hey @chihsuan 👋

The subheading implemented looks different to me:

![image](https://github.com/Automattic/wp-calypso/assets/98944206/6cf2da7e-2b0b-49cd-be88-5a230b3f1cbb)

![image](https://github.com/Automattic/wp-calypso/assets/98944206/7902fc91-7bbc-45fd-9265-3a3bebab2c30)

It's very subtle, but you can see that all the subheading has this second style apart from the Jetpack screen -- it seems to be related to font weight?

**Comment by moon0326** [comment]
Thanks @verofasulo 👍 

It seems like this is related to `-webkit-font-smoothing`, which is only available on Mac OS. I'll make a PR to fix it.

I opened a PR [here](https://github.com/woocommerce/woocommerce/pull/39526). Could you compare the subheadings again please?

**Comment by moon0326** [comment]
@chihsuan Opened a new PR in wp-calypso [Use subpixel-antialiased for webkit-font-smoothing on the core-profiler pages](https://github.com/Automattic/wp-calypso/pull/80160#top)
