### ISSUE TITLE
Post author not showing author display name, but instead [1]

### ISSUE THREAD

**Issue by aleone89** [Automattic/wp-calypso#79115]
### Quick summary

The post author on an individual blog post is not displaying the author display name, but instead: "[1]"

### Steps to reproduce

1. Visit site eg: https://aidenbentonmusic.com/2021/05/04/how-to-practice-effectively/ 
2. View post on homepage or click through to set posts page. 
3. Click on a blog post. 
4. Look at the meta data of the post (author, post, tags...etc.)

### What you expected to happen

I expected to see the author name. 

### What actually happened

I didn't see the author name, instead just [1] 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported here: https://wordpress.com/forums/topic/post-author-not-displaying-properly/#post-3969893 

Checked sites: 
- https://aidenbentonmusic.com/
- https://elizabethtai.com/
- https://isthatinthebible.wordpress.com/
- https://roguethoughtsweblog.wordpress.com/

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
- **Tested on Simple** – Replicated 
- **Tested on Atomic** – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- The issue can only be replicated in classic themes. 

**Tested on Simple - Twenty Nineteen** 
![6WAQQA.png](https://github.com/Automattic/wp-calypso/assets/67279475/787fb95b-677b-4453-b13a-8f583498c9ad)

**Tested on Simple - TT3**
![HuJNZ5.png](https://github.com/Automattic/wp-calypso/assets/67279475/f219cd6e-4dea-47f0-8cf0-f16232e3b2aa)

📌 ACTIONS
- Assigned to OTHER
- Added to ‘HE Cross-repo Watchlist’ project board

📌 Message to Author
- Thanks for reporting @aleone89! 
- This was escalated in p1688697747543619-slack-CBTN58FTJ and p1688704504701029-slack-CB0B2G43X
- https://github.com/WordPress/gutenberg/pull/52179
- https://github.com/WordPress/gutenberg/issues/52136

**Comment by kingsleyinfo** [comment]
Reported here: 6510028-zd-woothemes and 6510001-zd-woothemes

**Comment by mgozdis** [comment]
Additional user reports:
6511381-zd-woothemes
6510524-zd-woothemes

**Comment by noahtallen** [comment]
This should be resolved now -- I viewed the sites mentioned in the issue, and Author names show up as expected in blog posts and comments.
