### ISSUE TITLE
Plans: Add new FAQ item

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7912]
Based on feedback from our happiness engineers and written by our very own @KokkieH, let's add the following question and answer to the FAQ on the plans page (`/plans/:site`) at the top of the list.

> **What will happen to my content if I upgrade? Will I have to start over?**
Plans add extra features to your site, but they don’t change the content on your site in any way. Your existing posts and pages will still exist, your followers will still get notifications of your posts and see them in the Reader, and if you add a domain people will still be able to find your site by using the free address as well. And should you ever need to cancel your plan, your site will go back to the free plan and you won’t lose any content.

@KokkieH I made a slight tweak to your wording. You had said "your site will go back to the free plan and address but you won't lose any content." It's not strictly true that the site will go back to the free address, because canceling a plan does not necessarily mean you can cancel or refund your domain, so you might just be getting a partial refund while retaining the domain. That situation might be worth its own question/answer, but I think it's best to keep this answer simple.

**Comment by KokkieH** [comment]
That's a valid edit. That question comes up less often and isn't as much a blocker as "what happens when I upgrade".
