### ISSUE TITLE
Themes: Don't show wporg search results on the My Themes tab

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#79136]
When the `themes/interlaced-dotorg-themes` feature flag is enabled, 'My Themes' on the theme showcase shows community themes when searching, it should only show themes that the site has installed like it does when the feature flag is not enabled.

## Reproduction steps
 1. Go to wordpress.com/themes?flag=themes/interlaced-dotorg-themes while proxied
 2. Switch site to an atomic site
 3. Click 'My Themes'
 4. Notice that you have a small number of themes listed, the ones you have installed on the site
 5. Search for something, e.g. 'test'

### Expected results
I expected that the search results would be just those that I have installed that matches the search term

### Actual results
My Themes now lists lots of community themes, including those not installed

Originally reproduced with trunk at b09d689a01daa6

**Comment by dsas** [comment]
Sorry for not making it clearer @karenroldan but this bug only has an effect on some work-in-progress that is currently behind a feature flag, I'm not sure it needs to be prioritised by kitkat?

**Comment by karenroldan** [comment]
Hey @dsas thanks for the info! We regularly check for new issues labeled as bugs, make sure it has a priority label, and subsequently add them to the board. 

However, if a bug is filed by a developer and they've already assigned it to their team's board, we usually just move it directly to the team's column of the prioritization board. 👍🏻
