### ISSUE TITLE
Earn stats: Add a connection link between /earn page and the new earn stats page

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#79141]
More context: pb5gDS-3bY-p2
Figma: pb5gDS-3bY-p2#design

Since we’re removing Earn Stats within Earn page, we need to tweak that page layout a bit to make sure these two pages stay linked.

Note: This is a temporary solution while we work on the redesign.

| Before  | After |
| :-------------: | :-------------: |
| ![Image](https://user-images.githubusercontent.com/1044309/251823058-12ef384e-863f-4749-b4c0-292809923110.png)  | ![Image](https://user-images.githubusercontent.com/1044309/251823234-0c985487-c8e9-4e50-a539-d78f73498b25.png)|

## Acceptance criteria

- [ ] Change the `Earnings` block by removing the old Earn stats and adding two new links
- [ ] `earning stats` link goes to the new /stats earn page
- [ ] `monetize your site` link goes to https://wordpress.com/support/monetize-your-site
- [ ] Deploy it after moving the code (at 3005-gh-Automattic/dotcom-forge), or with a config flag

**Comment by lsl** [comment]
Do we want to keep the upgrade nudge somehow? Maybe blow it up into a full size card for the page now we have the space.
