### ISSUE TITLE
Reset "Your homepage displays" setting to Default upon activating a non-"auto-loading-homepage" theme

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#79167]
_(edited by @fushar on 20 Jul 2023)_

# Description

As proposed in this post: "Revisiting auto-loading-homepage and blog-homepage Tags for the Theme Switch Logic" pekYwv-2bc-p2, we want to change the theme switch logic as follows:

- Always reset the "Your homepage displays" setting to "Default" (formerly called "latest posts"),
   - unless the new theme has the `auto-loading-homepage` tag (which is rare exception).

However, currently the `auto-loading-homepage` tag has been misused; it is assigned to the wrong themes. Therefore:

- For simple and Atomic sites, we rely on whether or not the theme has the `show_on_front: page` option in its Headstart annotation.
   - If it does, we will set the "Your homepage displays" to the (generated) static page instead. This is existing behavior which we will not change.
- For Jetpack-connected sites, we cannot get the Headstart annotation to begin with.
   - For such sites, activating an "auto-loading-homepage" theme won't actually generate the correct homepage even before this issue.  This is existing behavior which we will not change.

For the purpose of testing the acceptance criteria:

- an example of "auto-loading-homepage" theme is Meraki.
- an example of "standard" theme is Exmoor.

# Acceptance Criteria

## Existing Behaviors

1. Given that we are in any theme where the "Your homepage displays" setting is "Default",
   - when we switch to an auto-loading-homepage theme,
      - [x] then the "Your homepage displays" setting is now set to a newly generated static page.
      - [x] then the newly generated static page's content is from the Headstart annotation.
      - [x] then the "Default posts page" setting is set to a newly generated posts page.
1. Given that we are in any theme where the "Your homepage displays" setting is set to a static page,
    - when we switch to an auto-loading-homepage theme,
      - [x] then the "Your homepage displays" setting is now set to a newly generated static page.
      - [x] then the newly generated static page's content is from the Headstart annotation.
      - [x] then the old static home page should be in draft state.
1. Given that we are in an auto-loading-homepage theme,
    - when we switch to any theme,
       - and we switch back to the old auto-loading-homepage theme,
          - [x] then the "Your homepage displays" setting is set back to the old generated static page from the old theme.
1. Given that we are in any theme where the "Your homepage displays" setting is set to a static page,
   - when we switch to an auto-loading-homepage theme,
      - [x] then the "Default posts page" setting is set to a newly generated posts page.
         - then when we switch to a standard theme,
            - [x] then the old posts page should be in draft state.
1. Given that we are in any theme where the "Your homepage displays" setting is "Default",
    - when we switch to a standard theme,
       - [x] then the "Your homepage displays" setting is still "Default".

## NEW Behaviors

1. Given that we are in any theme where the "Your homepage displays" setting is set to a static page,
    - when we switch to a standard theme,
       - [x] then the "Your homepage displays" setting is now set to "Default".
       - [x] then the old static home page should be in draft state.

# Related

- https://github.com/Automattic/dotcom-forge/issues/2983
- Project Thread: pbxlJb-3Uv-p2

```[tasklist]
# Dev Tasks
- [x] Implementation for Simple sites: ⚙ D116100-code
- [x] Implementation for Atomic sites: https://github.com/Automattic/wpcomsh/pull/1452
```

**Comment by fushar** [comment]
This has been shipped to Simple and Atomic sites.

Finally, we fixed theme switch, once and for all.
