### ISSUE TITLE
State: Migrate lib/countries-list to Redux state

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7920]
Related: #5046

The [`lib/countries-list` emitter object](https://github.com/Automattic/wp-calypso/tree/master/client/lib/countries-list) is a legacy store which uses deprecated data patterns. It should be updated to align with our [current data recommendations](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#current-recommendations). Specifically, this may include implementing all or some of the following Redux state behaviors:
- [x] Reducer
- [x] Action creators
- [x] Selectors
- [x] Query components

The implementation of each of these behaviors should be accompanied by tests.

When submitting a pull request, reference this issue and update the checklist above to reflect progress.

**Comment by umurkontaci** [comment]
I forgot this exists. #10766 solves this.
