### ISSUE TITLE
State: Migrate lib/states-list to Redux state

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7922]
Related: #5046

The [`lib/states-list` emitter object](https://github.com/Automattic/wp-calypso/tree/master/client/lib/states-list) is a legacy store which uses deprecated data patterns. It should be updated to align with our [current data recommendations](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#current-recommendations). Specifically, this may include implementing all or some of the following Redux state behaviors:

- [x] Reducer
- [x] Action creators
- [x] Selectors
- [x] Query components

The implementation of each of these behaviors should be accompanied by tests.

When submitting a pull request, reference this issue and update the checklist above to reflect progress.

**Comment by obenland** [comment]
@aduth Low priority, but when you get a chance, would you mind glancing over my commit and let me know if I'm headed in the right direction? Currently I'm thinking this could be a query component that updates the state for other components to use.

**Comment by aduth** [comment]
@obenland Sure thing, I dropped some comments on 2cedce8. Let's continue the discussion in #8202 as changes are made.

**Comment by gwwar** [comment]
@obenland did we mean to close out this issue?

**Comment by obenland** [comment]
I intentionally left it open to close it with #8414
