### ISSUE TITLE
The plans comparison table is broken in /plans when owning a highlighted plan.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#79220]
Originally reported in https://github.com/Automattic/wp-calypso/pull/79122#issuecomment-1628492795. tl;dr: when visiting /plans using a site on a highlighted plan, e.g. the Premium plan, the comparison table will be broken:

![Image](https://github.com/Automattic/wp-calypso/assets/1842898/d57586f7-9cac-4a2d-8c58-cbe7263f72cd)

@chriskmnds later found the code that potentially caused the breakage in https://github.com/Automattic/wp-calypso/pull/79122#issuecomment-1628606672.

**Comment by southp** [comment]
It's broken differently now:
<img width="966" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1842898/e5c056f5-2305-4e24-80e1-4e4a7d0aa157">

**Comment by chriskmnds** [comment]
@southp Hopefully, this is fixed (at least accidentally) by https://github.com/Automattic/wp-calypso/pull/84349. There is one more change that I tried without the fixes in #84349 that seemed to address the situation https://github.com/Automattic/wp-calypso/issues/79220#issuecomment-1792183205, but I think if https://github.com/Automattic/wp-calypso/pull/84349 suffices then we can leave it at that.
