### ISSUE TITLE
Show the correct homepage when previewing a theme

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#79221]
# Description

As we investigated in the spike https://github.com/Automattic/dotcom-forge/issues/2838#issuecomment-1617086512, we're to implement to show the correct homepage when previewing a theme by overriding the `show_on_front` option to `posts`. This covers the following cases;

- when switching from a theme with “a static page as homepage” to another with “template as homepage”
- when switching from a theme with “a front page as homepage” to another with “template as homepage”.

We don't consider "when switching from a theme with "template as homepage” to another with “a static page as homepage"" since BTP doesn't support such a case (c.f. pekYwv-284-p2). 

Project Thread: pbxlJb-3Uv-p2

# Acceptance Criteria
- [x] We can show the correct homepage in the case described above

# Dev Tasks
- [x]  Implement to override the `show_on_front` option
	- [x] https://github.com/Automattic/jetpack/pull/31929
	- ~~[ ] ⚙ D116384 Show the correct homepage when previewing a theme in the Site Editor D116384-code~~

# Testing 

- Try Live Preview switching from a theme with “a static page as homepage” to another with “template as homepage”
- Try Live Preview switching from a theme with “a front page as homepage” to another with “template as homepage”

# Related

- https://github.com/Automattic/wp-calypso/issues/79222

**Comment by okmttdhr** [comment]
I'll close this issue after testing it when it's released.

>https://fieldguide.automattic.com/developing-jetpack/jetpack-mu-wpcom/
As far as release cadence goes for jetpack-mu-wpcom, when there are changes to the package, the Jetpack release lead will deploy a new version of the package at minimum once a week while they work on the [Jetpack Atomic Weekly](https://fieldguide.automattic.com/releasing-jetpack/weekly-atomic-releases/) release.

**Comment by okmttdhr** [comment]
I’ll create a new issue if I find something wrong after testing it when it’s released on the Jetpack side. It'll be done once a week, along with the work on the Jetpack Atomic Weekly release.

**Comment by autumnfjeld** [comment]
@okmttdhr  Could you give me some examples (theme names) of themes that are “a front page as homepage” .  Thank you. :) 

Did you mean `front-page.html` template as homepage?  

Wording here is always hard, we have a lot of confusing terms in dotcom with respect to homepage and templates. :)
