### ISSUE TITLE
Subscription Management: Add address text fields to the modal

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#79232]
Figma: inDLaEQV8jJ21O4WXawIsJ-fi-3850_47488

Add the three text fields that allow entering urls to the modal. If possible, make sure they're `type="url"` for client-side validation & so that mobile users get the right keyboard.

![Image](https://github.com/Automattic/wp-calypso/assets/528287/c77a7a8a-72cd-4e96-ab74-170528911acb)

**Comment by phcp** [comment]
Dropped as per the updated design on Figma, no additional input is needed inDLaEQV8jJ21O4WXawIsJ-fi-4133%3A49232
