### ISSUE TITLE
Enhancement: Restore 'Open in New Tab' or Advanced Options to Link Editor for pages and posts

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#79239]
### Quick summary

Currently, when adding a link that opens in a new to the content of a page, you need to:
1. Add the link
2. Confirm
3. Click edit
4. Advanced
5. Check "Open New Tab"
6. Save

Adding the link:
![image](https://github.com/Automattic/wp-calypso/assets/81776920/66db60dc-812a-48fa-aec7-d73fc5f1ed1b)

Editing the link:
![image](https://github.com/Automattic/wp-calypso/assets/81776920/907a7032-9ce8-473a-80d9-439bc8bb684a)

### Steps to reproduce

Add a link that opens in a new tab in Guttenberg.

### What you expected to happen

1. To have the option to open link in a new tab right when adding the link and not only on the edit screen.
2. To not have the open in a new tab checkbox hidden behind the Advanced menu

### What actually happened

The process seemed overcomplicated for what it does.

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

📌 Message to Author
- Thanks for reporting this - I was just looking into this as well! I found some context in `/gutenberg` that's relevant for where this my go:
     - Equivalent issue in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/52216
     - Some discussion on the prevalence of this type of feedback: https://github.com/WordPress/gutenberg/issues/49091#issuecomment-1477057235
     - There's a PR that's been suggested that would add "always open in new tab" as an editor preference: https://github.com/WordPress/gutenberg/pull/52321
     - There's also a larger refresh of the LinkControl happening, that I wanted to link as well: https://github.com/WordPress/gutenberg/issues/50891

**Comment by cuemarie** [comment]
A recent example of user feedback on this in the forums: https://wordpress.com/forums/topic/open-link-in-a-new-tab-2/

User 1

>Originally, the process was
>>    Click “Insert Link”
    Paste URL into text box.
    Click the “Open link in new tab” checkbox.
    Press Enter.
>
>Now, if you want a link to open in a new tab, you have to
>
>>    Click “Insert Link”
    Paste URL into text box.
    Press Enter.
    Click on the link you just created.
    Click the Edit button.
    Click on Advanced Settings, which has NOW appeared.
    Click the “Open link in new tab” checkbox.
>
>This seems like change for change’s sake, and is time-wasting, especially as ALL the links I use (and there are many hundred, overall, because I still have nearly 300 posts to write) are ones I want opening in a new tab.

User 2

> My frustration [...] is that the process just. takes. too. many. clicks. The effective use of links has helped to drive my niche blog to the top of Google search results for my particular subject matter. I’m looking for the most expedient way to add those links.

**Comment by cuemarie** [comment]
Some internal discussion on this here: p1689240145573219-slack-C0160HSMDQV

**Comment by rw-ye** [comment]
+1 for this feature request.  The original process was much easier:

```
Click “Insert Link”
Paste URL into text box.
Click the “Open link in new tab” checkbox.
Press Enter.
```

**Comment by wiesenhauss** [comment]
This user requested that we relay the same feedback about the new process to set links to open in a new tab: 6560288-zen

**Comment by zdenys** [comment]
Another case 6589792-zd-woothemes

**Comment by jp-imagines** [comment]
Another frustrated user in 6598467-zd-woothemes (emphasis mine): 

> this is a bad change. Anything that makes it harder for us to blog is bad. This one really sux. **It shouldn't be this hard.**

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/open-in-new-tab/

**Comment by mxhassani** [comment]
6638341-zd-woothemes

**Comment by annezazu** [comment]
Closing this out as the refresh completed https://github.com/WordPress/gutenberg/issues/50891 and some changes were made to ensure that once a user opens the advanced section of link control it will stay open until they close it again: https://github.com/WordPress/gutenberg/pull/52799

**Comment by kelasante** [comment]
Another request in 9178078-zen. While the advanced section of link control stays open and is helpful, users still have to add the link and click to edit it before they can find the "open in new tab" option.
