### ISSUE TITLE
Reduxify: Migrate lib/embeds

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7924]
Related: #5046

The [`lib/embeds` Flux store](https://github.com/Automattic/wp-calypso/tree/master/client/lib/embeds) is a legacy store which uses deprecated data patterns. It should be updated to align with our [current data recommendations](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#current-recommendations). Specifically, this may include implementing all or some of the following Redux state behaviors:
- [ ] Reducer
- [ ] Action creators
- [ ] Selectors
- [ ] Query components

The implementation of each of these behaviors should be accompanied by tests.

When submitting a pull request, reference this issue and update the checklist above to reflect progress.

**Comment by tyxla** [comment]
I've been hacking on this in #38608
