### ISSUE TITLE
State: Migrate lib/happiness-engineers to Redux state

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7926]
Related: #5046

The [`lib/happiness-engineers` Flux store](https://github.com/Automattic/wp-calypso/tree/master/client/lib/happiness-engineers) is a legacy store which uses deprecated data patterns. It should be updated to align with our [current data recommendations](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#current-recommendations). Specifically, this may include implementing all or some of the following Redux state behaviors:
- [x] Reducer
- [x] Action creators
- [x] Selectors
- [x] Query components

The implementation of each of these behaviors should be accompanied by tests.

When submitting a pull request, reference this issue and update the checklist above to reflect progress.

**Comment by aidvu** [comment]
https://github.com/Automattic/wp-calypso/pull/8119

**Comment by aidvu** [comment]
WIP: https://github.com/Automattic/wp-calypso/pull/8119
