### ISSUE TITLE
WP CLI not picking up all instance in the database when using `search-replace`

### ISSUE THREAD

**Issue by kimclow** [Automattic/wp-calypso#79278]
### Quick summary

When launching a site, I went from a development URL to a production URL:

After the site launched, I saw lots of broken images on the front and when I inspected the image I saw the URL was the staging site, so I ran: 
Ran `search-replace a8cteam5136.wpcomstaging.com zuvuya.space` 

As my dev URL was `a8cteam5136.wpcomstaging.com` and my production URL is `zuvuya.space`

This fixed some, but not all of the broken images. Specifically, the one image which: 
`https://a8cteam5136.wpcomstaging.com/wp-content/uploads/2023/06/logo-fit-to-size-edited.jpeg?w=64` and this would not update using `search-replace`

I even ran it for the specific image: 
`search-replace [a8cteam5136.wpcomstaging.com/wp-content/uploads/2023/06/logo-fit-to-size-edited.jpeg?w=64](http://a8cteam5136.wpcomstaging.com/wp-content/uploads/2023/06/logo-fit-to-size-edited.jpeg?w=64) zuvuya.space/wp-content/uploads/2023/06/logo-fit-to-size-edited.jpeg?w=64 --dry-run` and the dry run said there was nothing to change. 

I have also logged an issue with Jetpack. See point 3 below. 

### Steps to reproduce

1. Create a test site on WPCOM and have an active Jetpack connection 
2. Add some placeholder content, including images 
3. Add the Jetpack Subscribe Block (I had difficulty getting the image on this block to work). 
4. Launch the site on a different domain 
5. Run `search-replace` to see how many places the database needs to be updated 
6. Check the front end, and inspect the images to see where they're pulling from. 
7. Try to subscribe using the Jetpack Subscribe Block, and see if the image is still pulling from the dev URL. 

### What you expected to happen

I expected all instances of the development URL to change when I ran `search-replace`

### What actually happened

It changed some instances, but not all. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
Looks like the image in the original report that was not being updated in Search-Replace was the `wpsm-site-logo` in the `jetpack-memberships-modal` that appears after someone subscribes to the newsletter.

The logo is updated now to the new domain now, though. That modal is an iframe - I wonder if it took a little more time for that to update to the right content. 🤔 

📌 Message to Author
- @kimclowa8c did you find a way to update that logo, or has that cleared up on it's own? 
- Along these same lines, did you run `cache flush` after your `search-replace`?  
- Were there any other instances of URLs that did not update, or just this one?

_Also, this is just a general fyi - it's important to include `--skip-columns=guid` in your `search-replace` command, in order to prevent the GUID (Globally Unique Identifier) column from being edited. More on that: - P9HQHe-1zm-p2_

**Comment by cuemarie** [comment]
Just ran a quick test on the image in that subscribe modal, and confirmed that this pulls the image set as the site's logo under Settings: 

**Original Logo**
![Markup on 2023-07-12 at 15:58:08](https://github.com/Automattic/wp-calypso/assets/27249804/933f92a4-57bf-4539-b128-549a84f0e625)

**Logo updated under Settings**
![Markup on 2023-07-12 at 15:58:48](https://github.com/Automattic/wp-calypso/assets/27249804/4934f3c5-f170-452e-bb69-f7764d37caff)

**New image under subscribe modal**
![Markup on 2023-07-12 at 15:59:31](https://github.com/Automattic/wp-calypso/assets/27249804/4c873600-4d0d-451e-a2fe-a85f45542bec)

---

Based on that, I'm thinking what could have happened is that the `search-replace` ran and updated the site logo but then the site's cache needed to be flushed to see that update reach this modal. 

But looking forward to hearing from you if there's more I'm not considering/seeing here!

**Comment by kimclow** [comment]
Hey @cuemarie 
Thank you for all this information. 

> Did you find a way to update that logo, or has that cleared up on it's own?

I uploaded a new image into the media library and selected it which is how I got it to work.

> Along these same lines, did you run cache flush after your search-replace?

No. I actually am very new to WP CLI and `search replace` was my first (and only) command I've learnt. 

> Were there any other instances of URLs that did not update, or just this one?

There were other image URLs which didn't update. But we managed to fix those by fiddling with the Jetpack CDN. Switching back to the staging URL and then back to the production URL. 

> Also, this is just a general fyi - it's important to include --skip-columns=guid in your search-replace command, in order to prevent the GUID (Globally Unique Identifier) column from being edited. More on that: - P9HQHe-1zm-p2

Oh thank you! I'm still learning!

**Comment by cuemarie** [comment]
> There were other image URLs which didn't update. But we managed to fix those by fiddling with the Jetpack CDN. Switching back to the staging URL and then back to the production URL.

Got it, thank you for those details!

📌 ACTIONS
- @Automattic/reactor Can y'all take a look at this report and weigh in?  I'm not sure if the `search-replace` tool encountered a bug here, or if it's sometimes the case that it doesn't catch every URL on the site. Appreciate your insight here!

**Comment by RafaelFunchal** [comment]
Hi there!

I think the issue is related to how images are saved on the database and the addition of `--skip-columns=guid` to the search-replace command.

Although the site_icon option is not serialized, the image address is saved on GUID.

Grabbing some details from my own site to illustrate:

```
rafaelfunchal.com.br [149467906] $ wp option get site_icon
2109
rafaelfunchal.com.br [149467906] $ wp post get 2109
+-----------------------+--------------------------------------------------------------------------------+
| Field                 | Value                                                                          |
+-----------------------+--------------------------------------------------------------------------------+
| ID                    | 2109                                                                           |
| post_author           | 3                                                                              |
| post_date             | 2016-07-09 21:38:20                                                            |
| post_date_gmt         | 2016-07-10 00:38:20                                                            |
| post_content          |                                                                                |
| post_title            | logo-rafaelfunchal                                                             |
| post_excerpt          |                                                                                |
| post_status           | inherit                                                                        |
| comment_status        | open                                                                           |
| ping_status           | closed                                                                         |
| post_password         |                                                                                |
| post_name             | logo-rafaelfunchal                                                             |
| to_ping               |                                                                                |
| pinged                |                                                                                |
| post_modified         | 2016-07-09 21:38:20                                                            |
| post_modified_gmt     | 2016-07-10 00:38:20                                                            |
| post_content_filtered |                                                                                |
| post_parent           | 0                                                                              |
| guid                  | https://rafaelfunchal.com.br/wp-content/uploads/2016/07/logo-rafaelfunchal.png |
| menu_order            | 0                                                                              |
| post_type             | attachment                                                                     |
| post_mime_type        | image/png                                                                      |
| comment_count         | 0                                                                              |
+-----------------------+--------------------------------------------------------------------------------+
```

Also, adding `?w=64` to the end of the string probably made it too specific and search-replace couldn't find that instance.

Maybe adding --verbose to the search-replace command to show exactly what is being changed could help next time.

Documentation for context: [WP-CLI.org > search-replace](https://developer.wordpress.org/cli/commands/search-replace/)

**Comment by cuemarie** [comment]
Thanks so much @RafaelFunchal ! With all that in mind, I think we're safe to close this out. Thank you for reporting @kimclowa8c !

📌 ACTIONS
- Closed as by design

**Comment by kimclow** [comment]
Thanks all!
