### ISSUE TITLE
State: Migrate lib/user-settings to Redux state

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#7927]
Related: #5046

The [`lib/user-settings` emitter object](https://github.com/Automattic/wp-calypso/tree/master/client/lib/user-settings) is a legacy store which uses deprecated data patterns. It should be updated to align with our [current data recommendations](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#current-recommendations). Specifically, this may include implementing all or some of the following Redux state behaviors:
- [ ] Reducer
- [ ] Action creators
- [ ] Selectors
- [ ] Query components

The implementation of each of these behaviors should be accompanied by tests.

When submitting a pull request, reference this issue and update the checklist above to reflect progress.

**Comment by nitrajka** [comment]
Hi,

FYI, I just noticed that some things from the todo list were already done here #12819.

**Comment by kriskarkoski** [comment]
@mattwiebe @michaeldcain Since you're assigned, is this still an issue or can we close?

**Comment by michaeldcain** [comment]
It looks like it was covered in #12819. Thanks for the ping!
