### ISSUE TITLE
Stats: Views stat in "Most popular post in the past year" unexpectedly decreases when user views the detail view

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#79292]
### Impacted plugin

Jetpack

### Quick summary

The user initially sees 274 views on their "Most popular post in the last year" module. After they click into the module, they see 92 views. Then, when they navigate back to the main screen, they see 92 views instead of 274 views.

From 6495713-zd-woothemes

### Steps to reproduce

See video in p1689078582793779-slack-C0438NHCLSY

### A clear and concise description of what you expected to happen.

They expect to see 274 views in both places (or a consistent number of views in each place.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by filipanoscampos** [comment]
Another case 6528114-zd-woothemes

**Comment by kangzj** [comment]
Another case https://github.com/Automattic/jetpack/issues/31821

**Comment by dognose24** [comment]
The issue should be fixed by https://github.com/Automattic/wp-calypso/pull/80188.
