### ISSUE TITLE
Pattern Assembler: Site View > Styles turns on Site Editor distraction-free mode

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#79290]
### Quick summary

After the Assemble Flow is complete and the user is taken to the Site Editor, clicking on the Styles tab in the Site View sidebar will trigger the distraction-free mode in the Site Editor, preventing the user to exit the Styles section without turning off distraction-free mode first.

Video:

https://github.com/Automattic/wp-calypso/assets/14153300/50d9c9dd-ecec-4256-b710-4984c24106f0

cc @retnonindya @Automattic/lego 

Thanks for heads up, @tanya

### Steps to reproduce

1. Use the Pattern Assembler to create a new design. I tested the Assembler in site creation and theme showcase, are there any other entry-points?
2. Go to the Site Editor
3. Click on Styles
4. Distraction-free will be turned on without user input

### What you expected to happen

Distraction-free mode shouldn't be turned on without intentional input.

### What actually happened

Distraction-free mode is turned on without intentional input.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Gutenberg 16.1.2 and Gutenberg 16.2 RC3

I haven't tested on Atomic

**Comment by tanjoymor** [comment]
Just to clarify, it's not just when using the Assembler flow. It does happen with that flow, because that flow uses Blank Canvas by default which doesn't have style variations. But it happens in the main flow when you pick any theme that doesn't have style variations. It's not always consistent though. My first test with Otis was flipping the Distraction Free mode off and on. When I recorded the process with Skatepark it was off, then came on, then tried to turn itself off but didn't.

https://github.com/Automattic/wp-calypso/assets/42655541/1e4f70c1-b418-47a3-ba29-ce22f91bceaf

**Comment by tanjoymor** [comment]
Related comment here: https://github.com/WordPress/gutenberg/pull/51173#issuecomment-1603990750

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- So far, I haven't been able to replicate this. I've created 2 new sites and tried following the steps above using the Pattern Assembler as well as choosing a theme with no style options, including Skatepark and Rainfall. 
- In all tests, at no point does my browser default to distraction-free editing. 🤔 

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @tanjoymor @liviopv What browsers are y'all working in? Any other details that you've found help replicate consistently?

**Comment by liviopv** [comment]
@cuemarie I cannot repro anymore. It could be that 16.2.1 or a different Calypso update fixed it 🙌

**Comment by cuemarie** [comment]
Great to hear! In that case, I'll close this out!

📌 ACTIONS
- Closed as no longer replicable / resolved
