### ISSUE TITLE
Theme showcase: Premium Themes feature isn't being featured on the plan grid

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/wp-calypso#79346]
When we have a free plan, and are in the Theme Showcase, if we click on the upgrade banner we can see that the Plans Grid isn't featuring the `Premium Themes` feature even though the URL seems correct:
* https://wordpress.com/plans/{site}.wordpress.com?feature=premium-themes&plan=value_bundle

## Reproduction steps
 1. Go to wordpress.com/themes
 2. Switch the site to a site on a free plan
 3. Click on the upgrade's banner CTA
 4. You will see that the Plans Grid isn't highlighting the Premium Themes feature.

### Expected results
I expected to see the Premium Themes feature highlighted.

**Comment by dsas** [comment]
**I  can't reproduce this 🤔** Am I missing a CTA or something @rcrdortiz ?

Whether I click on the grid CTA:
<img width="1170" alt="Screenshot 2023-08-03 at 18 22 26" src="https://github.com/Automattic/wp-calypso/assets/93301/fab3f88b-8629-4b0e-847a-df409dedb440">

Or the theme-specific CTA:
![w7grRa.png](https://github.com/Automattic/wp-calypso/assets/93301/a3bcbeda-c65f-4426-9126-783d81250927)

Or the live demo CTA:
<img width="1459" alt="Screenshot 2023-08-03 at 18 26 42" src="https://github.com/Automattic/wp-calypso/assets/93301/44b06586-ee9d-4c5d-bab2-f21789e26114">

All take me to `https://wordpress.com/plans/SITE_SLUG.wordpress.com/?plan=value_bundle&feature=premium-themes-v2` sometimes with a redirect_to param) which means I get:

<img width="1164" alt="Screenshot 2023-08-03 at 18 34 32" src="https://github.com/Automattic/wp-calypso/assets/93301/0d0d4820-a3d2-43fb-94ed-5e5354143b66">

and

<img width="1164" alt="Screenshot 2023-08-03 at 18 35 35" src="https://github.com/Automattic/wp-calypso/assets/93301/762bf9e6-9e19-416d-bdce-1d952bddc61e">

**Comment by BogdanUngureanu** [comment]
I can't reproduce it either. Looks like all of them are pointing to https://wordpress.com/plans/site.wordpress.com?feature=premium-themes-v2&plan=value_bundle

**Comment by dsas** [comment]
Lets just close it then, we can always reopen it if someone notices it again.
