### ISSUE TITLE
Advanced SEO: Tokens can Merge/Split

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7934]
In the title editor, you can place the cursor in a token, then add another token and it will split it up:

![site-name-bug](https://cloud.githubusercontent.com/assets/789137/18319669/8f119e56-74db-11e6-9b87-2b03d67b2696.gif)

cc @dmsnell

**Comment by roundhill** [comment]
Related: If you insert multiple tokens without spaces then save the title, these are combined into a really long token (which is removed with one click/tap)

![combining](https://cloud.githubusercontent.com/assets/789137/18319698/b1140b88-74db-11e6-9a32-1bff20c82a2f.gif)

**Comment by dmsnell** [comment]
The first part of this should be resolved when #7887 gets resolved and the second part is a duplicate of #7886 so I'm going to close this issue, but thanks for reporting it @roundhill!
