### ISSUE TITLE
Theme showcase: Tab switches automatically when using the free, premium and paid filters

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/wp-calypso#79344]
When we're on an Atomic site, if you are in the theme showcase and having a look at your themes. If you decide to filter them by free, paid, or premium. The page automatically navigates from `my themes` to `Recommended` this only happens when we are in the `My Themes` tab.

## Reproduction steps
 1. Go to wordpress.com/themes while proxied
 2. Switch the site to an atomic site
 3. Click 'My Themes'
 4. Click on any of the filters on the righthand side (free, paid, premium)
 5. You are now on the `Recommended` tab instead of being on the `My Themes` tab.

### Expected results
I expected to see which of my themes are paid, free or premium instead of navigating to the `Recommended` tab.

**Comment by mmtr** [comment]
Just realized this is not fixed by https://github.com/Automattic/wp-calypso/pull/80334.

**Comment by BogdanUngureanu** [comment]
Implementing the same behavior as the other categories might be confusing because filtering by "Partner" themes will also apply to themes purchased directly from the vendor.

Since this UI will soon change, let's abandon this issue, at least for now.
