### ISSUE TITLE
Advanced SEO: Inconsistent delete behavior on Mobile

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7935]
On iOS the behavior when tapping a token in the fields is inconsistent, sometimes it removes the token (expected), and sometimes it just highlights in red. I am not sure why and can’t work out which is which.

Video: https://cloudup.com/i3vZ4P479jW

**Comment by dmsnell** [comment]
Sounds like tap vs hover-tap @roundhill - we can look into the events on those buttons. I'm sure this is a problem simply because I'm less familiar with mobile touch events.

**Comment by roundhill** [comment]
Additional info:

* The token will delete only if the text field that it is currently in _does not_ have focus.
* Tapping on a token when the field has focus will turn it red, but not delete it.

**Comment by Copons** [comment]
Not reproducible on Chrome on Android 6 (Chrome Custom Tabs on the other hand, has [a good deal of other issues](https://github.com/Automattic/wp-calypso/issues/9300)).

**Comment by dmsnell** [comment]
Closing - this may not even be an issue after draft-js version updates…
