### ISSUE TITLE
Home: Hiding Daily Prompts impacts site checklist, revealing checklist restores daily prompts

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#79380]
### Quick summary

On my Free test site, when I hide the "Daily prompts" card on the My Home page, the "Blog setup" checklist is replaced with **Site setup complete!** But then if I click on the button to "Show me what's next", the Daily prompts card is restored, and I have to hide it again.  

Hiding it a second time seemed to work, but still changes the order of cards in above it.

### Steps to reproduce

1. Open a newer test site, or create a new test site and launch it without completing the checklist.
2. Open **My Home**, and observe the Blog Setup checklist as well as the Daily Prompts card.
3. Use the `...` button to hide the daily prompts.
     - _observe that the daily prompts hide, but so does the site checklist_
4. In the new **Site setup complete!** card, click on "Show me what's next"
     - _observe that the daily prompts card returns along with the checklist_
5. Repeat step 3 and hide the daily prompts again

### What you expected to happen

Only the "Daily Prompts" card is hidden, and the other content onscreen is not impacted.

### What actually happened

On one test site, I was able to hide the Daily writing prompt on my second attempt:

https://github.com/Automattic/wp-calypso/assets/27249804/69aab7a9-b56d-4714-8f58-dc5c57bc9fdd

On another free test site, the Daily writing prompts hid/ were revealed following the steps above, and then could not be hidden again:

https://github.com/Automattic/wp-calypso/assets/27249804/89371250-7cdb-4e2f-943b-e9899cb23db5

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Gutenberg: v16.2.0
Editing Toolkit: 3.71520
WP AMP: 2.0.5

Firefox 115.0.2 (64-bit)

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
- On my AT sites, I'm seeing that I need to hide the card twice before it disappears, and it hides the site setup checklist steps as well.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/a463d7cc-5bc7-4f1d-a9f4-6c7558e9c1d1

📌 ACTIONS
- Assigned to @Automattic/loop 
- Not sure if this would be best with Loop or Lego, but since the Daily Writing Prompts are Loop's, I figured we'd start there!

**Comment by davemart-in** [comment]
Added to our bugs board. Thanks!

**Comment by Addison-Stavlo** [comment]
>  I was able to hide the Daily writing prompt on my second attempt: .... On another free test site, the Daily writing prompts hid/ were revealed following the steps above, and then could not be hidden again:

I was testing dismissing it on another site earlier and it reappeared, but if i did a hard refresh of the browser it was gone, i wonder if thats the same case with these? If so that might point us in the right direction of some local data not being updated properly.

**Comment by cuemarie** [comment]
Hey @Addison-Stavlo ! Hard refresh did not impact the behavior on either Simple or AT test sites for me.  I retested in both environments and took notes along the way, which ended up being overkill since there was no change in behavior, but here's that again in case it helps!

---

### Simple Site

On my simple site, hard-refreshing after hiding the daily writing prompt had no impact on the behavior. I took the following steps:

1. Daily writing prompt Toggle Menu > Hide daily writing prompts
     - _Site build steps are removed and site checklist changes to "Site Setup complete!"_
2. Hard Refresh
     - _same dashboard cards load_
3. Selected "Show me what's next"
     - _Site checklist returns, as do the daily writing prompts_
4. Hard Refresh
     - _Same dashboard cards load_
5. Daily writing prompt Toggle menu > Hide daily writing prompts
     - _card no longer hides at all_

Steps 1-3

https://github.com/Automattic/wp-calypso/assets/27249804/b7ad78b4-3e4c-4f64-a652-172430b80378

Steps 4-5

https://github.com/Automattic/wp-calypso/assets/27249804/caab2579-ec3a-4119-b4d0-9fdf9e14beaa

### AT Site

Hard refresh did not impact behavior on AT site either. Steps taken:

1. Daily writing prompt Toggle Menu > Hide daily writing prompts
     - _Site checklist is removed in favor of primary My Home slider, but daily writing prompts remain_
2. Hard Refresh
     - _No change, same dashboard cards load_
3. Daily writing prompt Toggle Menu > Hide daily writing prompts
     - _Daily writing prompts hide_

**Comment by roo2** [comment]
Potential fix here https://github.com/Automattic/wp-calypso/pull/79776
