### ISSUE TITLE
Checkout: Phone Number field unusable when set to Dominican Republic

### ISSUE THREAD

**Issue by DustinHartzler** [Automattic/wp-calypso#79459]
### Quick summary

Chatter on 6530505-zen tried to come and purchase an additional domain for their site, but on the checkout page, could not properly enter their Dominican Republic domain name.

### Steps to reproduce

1. Add a plan to the cart
2. Go to the checkout page and edit your contact information
3. Change the phone prefix to Dominican Republic
4. Try typing any one of the three prefixes for DR: 809, 829, 849

### What you expected to happen

I expect the three numbers that I press, to be what appears.

### What actually happened

A whole bunch of numbers appear in the form field. In the image below, I typed `829`

![CleanShot 2023-07-15 at 07 43 28](https://github.com/Automattic/wp-calypso/assets/2293077/050bd91f-5cd1-4dc6-b03f-52414db4166e)

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- When I leave the country selection in the Phone field set to the United States, I'm able to enter in any numbers. But when I switch that to the Dominican Repbublic, each key stroke results in more numbers than what I just typed.
- If I type in the number first, then switch to DR, this also results in too many numbers in the field.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/65a8e45a-4ce8-4358-a2a7-11969acf3459

📌 ACTIONS
- Assigned to Other
- CC: @Automattic/shilling 
- Dropped this from `Blocker` to `High` given the specificity of those impacted, but note that this would prevent a user in the DR from purchasing a domain, as the phone number field is required.

**Comment by jjchrisdiehl** [comment]
Working on this now, this also seems to apply to Puerto Rico, Western Sahara, Reunion, Mayotte as well.

**Comment by jjchrisdiehl** [comment]
@DustinHartzler This should be fixed in https://github.com/Automattic/wp-calypso/pull/79760 - marking this closed for now.

**Comment by cuemarie** [comment]
Works on my test site - thanks!
