### ISSUE TITLE
The checkout thank you page shows the incorrect plan expiration date

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#79462]
### Quick summary

After signing up for a monthly or yearly plan, the checkout thank you page https://wordpress.com/checkout/thank-you shows an incorrect plan expiration date which is the date of purchase. 

### Steps to reproduce

1. Go to Upgrades > Plans and pick a plan.  
2. Go to checkout and complete the purchase. 
3. A thank you message will appear in https://wordpress.com/checkout/thank-you which shows a message containing the plan bought, and the incorrect expiration date. 

### What you expected to happen

The checkout thank you page will show the correct plan expiration date. 

### What actually happened

The checkout thank you page shows an incorrect plan expiration date, which is the date of purchase. 

### Impact

All

### Logs or notes

Firefox 115, macOS 13.4.1 

On July 16, 2023 I got the **Personal plan monthly.** After completing the purchase, the checkout thank you page shows the plan expiration date July 16, 2023 instead of August 16, 2023: 

<img width="1439" alt="monthly" src="https://github.com/Automattic/wp-calypso/assets/36863633/219f0bbf-35d3-403e-9dc0-bcafb588b74b">

---

Also on July 16, 2023 I got the **Personal plan yearly**. After completing the purchase, the checkout thank you page shows the plan expiration date July 16, 2023 instead of July 16, 2024: 

<img width="1440" alt="yearly " src="https://github.com/Automattic/wp-calypso/assets/36863633/7b0be257-e259-4466-b6c2-c4d16aa2b0e5">

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated when purchasing Personal Plan, upgrading to Premium, and upgrading to Business.
- The page showing the incorrect expiration date is `https://wordpress.com/checkout/thank-you/SITE-ADDRESS/XXXXXX`

#### Screenshots/Recordings

![Markup on 2023-07-17 at 12:02:26](https://github.com/Automattic/wp-calypso/assets/27249804/5e67b440-ffc3-4ba8-95b7-9d889e044ba8)

![Markup on 2023-07-17 at 12:03:45](https://github.com/Automattic/wp-calypso/assets/27249804/4cee8e39-37ba-496b-ae3c-bcac72c37b02)

📌 ACTIONS
- Assigned to ~Automattic/martech~ `Other`
- CC: @Automattic/shilling

**Comment by sirbrillig** [comment]
Hm... It looks like this logic comes from here:

https://github.com/Automattic/wp-calypso/blob/a9b9b56995dab7d7a31bcb1cc92efe874b17d1a2/client/my-sites/checkout/checkout-thank-you/redesign-v2/sections/product/ProductPlan.tsx#L33-L35

That uses the `expiryDate` field on the purchase object which comes from here:

https://github.com/Automattic/wp-calypso/blob/a9b9b56995dab7d7a31bcb1cc92efe874b17d1a2/client/lib/purchases/assembler.ts#L29

That data comes from the `expiry` field of the subscription. I checked what I believe was one of the purchases tested above (purchased on 2023-07-16) and its `expiry` field is 2024-07-16, which sounds right. 

That means that whatever is in those screenshots must be being broken by something else. Either the `expiry` is changing and was incorrect at the time of purchase or formatting the expiry is doing the wrong thing. I'll see if I can reproduce this to determine which.

**Comment by sirbrillig** [comment]
I logged the `productPurchase` found on that page, and here's what it looks like. Note that there is no`expiryDate` field. This means that `moment(undefined)` is rendering the current date instead.

<img width="305" alt="Screenshot 2023-07-17 at 5 07 55 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/e184b6b2-3808-41c3-8a84-f7341480193f">

It's hard to trace where the list of `purchases` passed into that component comes from (its parent isn't TypeScript) but it clearly is missing data. 

I believe this was a bug introduced in https://github.com/Automattic/wp-calypso/pull/78931 cc @candy02058912

**Comment by sirbrillig** [comment]
cc also @Automattic/explorers

**Comment by candy02058912** [comment]
I was indeed loading the wrong list of purchases, and provided a fix here: https://github.com/Automattic/wp-calypso/pull/79518

I agree that a better way to do this is: p1689665378362099/1689628493.696659-slack-CKZHG0QCR, any thoughts?
