### ISSUE TITLE
Subscribers Page: Update empty state Launchpad

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#79476]
### Details

After working with @nuriapenya, we realized that we need to update the empty state on Subscribers Page.

The design currently implemented diverges from other Launchpad modules in the product and introduces a new pattern.
We need to update it to avoid confusing our users — with the new design they'll know how to interact with it and what to expect.

[Figma file](h8tMpJlCqNFemEerU9owHI-fi-3538_145646).
h8tMpJlCqNFemEerU9owHI-fi-3538_145646 

Screenshot:

![update-empty-launchpad](https://github.com/Automattic/wp-calypso/assets/25607244/3c17e0c5-edb6-4f62-8329-df5bb5df19c3)

Launchpad tasks:

- Import existing subscribers. Done when the user opens/closes the modal that appears when clicking the `+ Add subscribers` button.
- Share your site. On click opens this modal ([Figma](9wpoYJrMlYKAKUYvVBMN74-fi-4206_104558) and https://github.com/Automattic/wp-calypso/issues/78856). Done is when they `copy link` or click any social network icon.
- Add the Subscribe Block to your theme. Done when they've added that block on their site.

cc @yansern

**Comment by TimBroddin** [comment]
Hey @crisbusquets 👋

I have two questions for this issue:

- I didn't find a way to show UI to skip a step in a Launchpad. Is it ok that the launchpad stays "uncompleted" if a user, for example, chooses not to add the Subscribe block to their site?
- What happens when the Launchpad is completed and the user still has no subscribers? Do we show the completed Launchpad or hide it and show a message?

**Comment by crisbusquets** [comment]
Great questions, @TimBroddin!
Pinging @nuriapenya for her perspective on these:

> I didn't find a way to show UI to skip a step in a Launchpad. Is it ok that the launchpad stays "uncompleted" if a user, for example, chooses not to add the Subscribe block to their site?

It's ok, because these are suggestions we do to help them get subscribers.

> What happens when the Launchpad is completed and the user still has no subscribers? Do we show the completed Launchpad or hide it and show a message?

This Launchpad is particular because there's no guarantee that you'll get subscribers if you follow all the steps. If I'm not wrong, there's a new version of the launchpad that includes a "Skip". I remember discussing this with Nuria, but I'm unsure where it landed.

**Comment by nuriapenya** [comment]
Hey @TimBroddin 👋🏽 

>I didn't find a way to show UI to skip a step in a Launchpad. Is it ok that the launchpad stays "uncompleted" if a user, for example, chooses not to add the Subscribe block to their site?

As @crisbusquets pointed out, these tasks are technically optional, so users can choose to ignore them if they wish. 

But the Launchpad principle is to **always showing the next important step to do**. So, we need to ensure the tasks are highly relevant so users interact with them, and achieve their goals. In this case, having the first subscriber.

That being said, if users complete all tasks but have no subscriber yet, the Launchpad can remain open (the tasks will be marked as completed, but they are still clickable), and users can choose to dismiss it if they want. 

This is an example of what's currently live:

<img width="1438" alt="Screenshot 2023-11-06 at 15 04 29" src="https://github.com/Automattic/wp-calypso/assets/7931304/9ad91947-fad7-4930-95de-ee54236618a1">

I think we set a timeframe in which the Launchpad will be closed automatically, right @daledupreez ?

**Here's the Updated Figma Design:** h8tMpJlCqNFemEerU9owHI-fi-3991_89819
For Subscribers would be:

<img width="1440" alt="Launchpad_Active" src="https://github.com/Automattic/wp-calypso/assets/7931304/67da54aa-f3fb-4496-b4c7-2a2f1eab02e2">
<img width="1440" alt="Launchpad_Completed" src="https://github.com/Automattic/wp-calypso/assets/7931304/25753db3-bd6d-4cc2-b2d4-173abcfd65ce">

**Comment by TimBroddin** [comment]
Thanks for the clarification @nuriapenya !

**Comment by daledupreez** [comment]
As a quick follow-up to @nuriapenya's comments above:
> I think we set a timeframe in which the Launchpad will be closed automatically, right @daledupreez ?

At this time, we don't have time-based closure. We discussed doing that for new sites, but we never implemented it. :-/

We could add this, but I think we'd want to understand the use case(s) before doing so.
