### ISSUE TITLE
Domain header spacing: text is too close to the bottom border 

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#79478]
### Quick summary

The domain header displays the text immediately below a border, without enough spacing. 

### Steps to reproduce

1. Start at `Upgrades` > `Domains`.
2. Click on the three dots menu of any domain. 
3. Click `View Settings`.
4. Observe that the domain header is placed too close to the bottom border of the navigation header. 

### What you expected to happen

There will be a space between the border and the text below it.

### What actually happened

There's no space between the border and the text below it, the design looks crowded and may reduce readability. 

![SN4X7j.png](https://github.com/Automattic/wp-calypso/assets/67279475/d81d34eb-beba-4d6f-91b5-eaf313e8d63f)

![OvpuLh.png](https://github.com/Automattic/wp-calypso/assets/67279475/ad25787f-f8b3-4e07-a64d-9817f854273a)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes

This seems to be introduced by #78921 (cc: @jeyip, is this something that you could look at? Thank you!)

**Comment by jeyip** [comment]
@karenroldan Thanks for the ping! It's on my radar  😄

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Quick triage as it looks like Jeremy is already on top of this!

📌 ACTIONS
- Assigned to Nomado

**Comment by karenroldan** [comment]
This was fixed in #79463
