### ISSUE TITLE
After changing theme, sometimes the Reading Settings shows wrong value for "Your homepage displays"

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#79506]
### Quick summary

Some themes (currently, the ones with the `auto-loading-homepage` tag) will update the "Your homepage displays" setting to a new page upon activation. However, this new value is sometimes not reflected in the Reading Settings page.

@Automattic/lego 

### Steps to reproduce

Note: it is important to follow the steps EXACTLY.

1. Create a new site.
1. Skip the Design Picker theme selection, which will set the theme of your site to TT3.
1. Go to Settings -> Reading.
1. First, verify that the values are correct: 
    
    <img width="234" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/844b0550-979a-4715-983d-285d2ae3cf0e">

1. Activate Meraki theme (or any theme in https://wordpress.com/themes/filter/auto-loading-homepage).
1. Go back to Settings -> Reading.

### What you expected to happen

The values should be:

<img width="235" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/409da2fe-98d1-4d4d-9909-9d87f1e890a6">

### What actually happened

The values are not updated (though actually on the backend side, the values did update)

<img width="234" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/844b0550-979a-4715-983d-285d2ae3cf0e">

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Switching from TT3 (with the theme's default Blog Home template set as the homepage) to Meraki replicated this issue just as described. 

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/fbacf599-e525-4939-94e9-828c8a06da0e

📌 ACTIONS
- Assigned to Lego

**Comment by fushar** [comment]
This was fixed and shipped!
