### ISSUE TITLE
Simple Sites: Social Media Icons Missing from Sharing Buttons

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#79502]
### Quick summary

Sharing buttons show an empty box where an icon should be rendered instead

### Steps to reproduce

1. ~Activate Twenty Twenty on test site~ Open a simple WordPress.com site
2. Set sharing buttons to any setting that has icons (Icons & Text, Icon Only, Official Buttons)
3. Save settings and view any post on the site

### What you expected to happen

Icon to be displayed

### What actually happened

Empty box is shown where the icon should go. Tested with Icons & Text, Icon Only, Official Buttons settings.  In all cases there were missing icons, but note that if you test the Official Buttons setting, some buttons will show icons and some will not, likely due to how we are fetching the official button, which may vary by service

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Only workaround for the moment is to direct the site owner to set the "Text Only" option for buttons.  CSS and custom icons may also be a workaround but I have not tested it

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Simple site using multiple themes, both Classic and FSE
     - Themes Replicated: TT, TT1, TT2, TT3 on simple 

#### Screenshots/Recordings

_Firefox 115.0.2 (64-bit)_

![Markup on 2023-07-17 at 16:56:47](https://github.com/Automattic/wp-calypso/assets/27249804/7e344a24-889a-4731-b89f-d6553cba4a29)

**Simple Site, Twenty Twenty**
![Markup on 2023-07-17 at 16:57:06](https://github.com/Automattic/wp-calypso/assets/27249804/479d7f95-4c78-4784-a371-ee988847f98e)

**Simple Site, TT3**
![Markup on 2023-07-17 at 16:59:25](https://github.com/Automattic/wp-calypso/assets/27249804/9ea4415a-8a51-4486-abea-c0d7aa04cfcb)

**Atomic Site, TT3**
![Markup on 2023-07-17 at 17:01:13](https://github.com/Automattic/wp-calypso/assets/27249804/b11064e7-c271-4116-a662-85a7ff2de237)

📌 ACTIONS
- Assigned to @Automattic/loop

**Comment by cuemarie** [comment]
Escalated here: p1689638734304199-slack-C03NLNTPZ2T

**Comment by roo2** [comment]
fixed for now by reverting jetpack release. I suspect it was introduced with this commit to jetpack, but I'll leave it for them to investigate https://github.com/Automattic/jetpack/pull/31873

**Comment by jeherve** [comment]
In https://github.com/Automattic/jetpack/pull/31932 I'm taking another pass at this.
