### ISSUE TITLE
After changing theme, sometimes the Pages list shows the wrong homepage settings and/or spinning loaders

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#79511]
### Quick summary

Some themes (currently, the ones with the `auto-loading-homepage` tag) will update the "Your homepage displays" setting to a new page upon activation. However, this new value is sometimes not reflected in the Pages page.

@Automattic/lego 

### Steps to reproduce

1. Create a new site.
1. Skip the Design Picker theme selection, which will set the theme of your site to TT3.
1. Then, activate Meraki theme (or any theme in https://wordpress.com/themes/filter/auto-loading-homepage).
1. Go to Pages in the left sidebar.

### What you expected to happen

It should look like this:

<img width="1073" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/9007dc67-4fb6-47cb-895c-89941369061b">

### What actually happened

It looks like this instead:

<img width="1093" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/9adf7273-30f1-4b39-bbf3-fdcd79a8b015">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Refreshing the page again multiple times and/or go to other pages, will sometimes fix the issue.

**Comment by fushar** [comment]
Sometimes it will show like this:

<img width="1081" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/74e9c83b-c408-4b5a-b241-c6105601ae2f">

But it's still wrong because it is not using the Index template 😅

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Switching from TT3 (with the theme's default Blog Home template set as the homepage) to Meraki replicated this issue just as described. 

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/fbacf599-e525-4939-94e9-828c8a06da0e

📌 ACTIONS
- Assigned to Lego

**Comment by fushar** [comment]
This was fixed and shipped!
