### ISSUE TITLE
Add Migration Trial case to Upgrade Nudge

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#79531]
The `UpgradeNudge` and `ConnectedSingleSiteJetpack` components must display an Upsell if the user is in a migration trial.

**Comment by ouikhuan** [comment]
After some investigation, I think this ticket is no needed anymore.
- `UpgradeNudge` only shows in the plugins page but we're not blocking the plugins like Woo Trial does, so no extra upsell here is needed.
- `ConnectedSingleSiteJetpack` is not used in the codebase anymore.
