### ISSUE TITLE
Edge Browser: Causing false Jetpack error

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#79556]
### Quick summary

A customer reported:

> Every time I click on "My Home" the browser window goes blank and I get a message "There is a problem with your site's Jetpack connection" and a link to "wp-admin" that I have to click to get to the dashboard.

![Screenshot 2023-07-08 114500](https://github.com/Automattic/wp-calypso/assets/42655541/e5f17d67-65a0-48eb-a2f6-f715a7dd538e)

Confirmed that they are using Edge: https://www.whatismybrowser.com/w/D24MSTZ

Confirmed that the Jetpack connection was healthy and synced.

The site worked correctly for them using Chrome.

### Steps to reproduce

I don't have a Windows computer or access to Edge, so I'm not entirely certain on the exact steps to reproduce. Presumably just access My Home on an Atomic site using the latest Edge browser.

### What you expected to happen

I'd expect there to not be a Jetpack connection error message when the Jetpack connection is fine.

### What actually happened

Customer got a Jetpack connection error.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Edge: https://www.whatismybrowser.com/w/D24MSTZ

The workaround being "easy" is subjective. They have to install a different browser, which some customers don't like doing.

**Comment by cuemarie** [comment]
@tanjoymor can you check to see if this is actually a duplicate of this issue? 

- https://github.com/Automattic/wp-calypso/issues/79324

**Tip** - Check to see if the `wp-admin` link in that warning directs to a different site address than the site they're trying to load. If so, this is likely not a browser issue, but the bug above.  
If that is what's happening, try setting their primary site under https://wordpress.com/me/account, and/or disconnecting the old/incorrect site

**Comment by cuemarie** [comment]
If that doesn't look like a dupe, please share the interaction here, and I'm happy to test the user's site in Edge for you!

**Comment by tanjoymor** [comment]
Agreed, I don't think this situation is the same as the one noted above. This is the interaction: 6514789-zen. 

For this user, going to the My Home page when using Edge produces a Jetpack error with that wp-admin link. But it doesn't happen in Chrome. And, Jetpack Debugger seemed fine from every angle that I could find.

**Comment by cuemarie** [comment]
Tested the user's dashboard in Edge on my side and the error did not show up for me!  This suggests a browser-level cache issue - having the user give things a good clear/reset should help resolve!

📌 ACTIONS
- Closing as not reproducible
