### ISSUE TITLE
Checkout: domain transfer line item to show renewal price and time

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#79554]
Domain transfer line items in checkout don't say very much compared to other products. Can we update them to include information about how much they will cost when they next renew? A domain transfer is a one-time product but it turns into a domain registration so we can probably copy some text from domain reg line items.

**Comment by spraveenitpro** [comment]
@sirbrillig 

Currently, for Domain transfer, we see:

![YZRgiz.png](https://github.com/Automattic/wp-calypso/assets/552016/d6c73290-40d9-44ff-a340-7280f8d84fbe)

What do you think about this, it would be the same size as the domain name before it:

![aQYm6f.png](https://github.com/Automattic/wp-calypso/assets/552016/ad5c50ea-9eb4-484b-a755-082646111f5b)

**Comment by sirbrillig** [comment]
I was originally thinking something like how the WPCOM plan renewal date is displayed:

<img width="602" alt="Screenshot 2023-07-19 at 5 44 50 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/94f5c3f3-3935-4066-a080-e75b31d95420">

Although I do like the idea of having the next renewal date visible. 🤔  It's a trade-off between showing the next renewal date and mentioning that it will renew annually. Maybe there's some way to show both? Try out something and we'll see how it looks.

**Comment by spraveenitpro** [comment]
PR https://github.com/Automattic/wp-calypso/pull/79718
