### ISSUE TITLE
Launchpad: Clicking "Share your site" task creates extra `_task_view` Tracks events

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#79565]
I found this while working on #79460; if you click on the "Share your site" task in the "Keep Building" task list on Customer Home, you'll see multiple `_task_view` tracks events fire when the modal opens, and again when it closes. This could artificially inflate the number of views on the tasks.

Video demo:

https://github.com/Automattic/wp-calypso/assets/2124984/b5124546-b555-4c76-9886-ce81c906df9f

**Comment by daledupreez** [comment]
@sixhours, I believe that #79573 should fix this issue. Can you confirm?

**Comment by markbiek** [comment]
Confirmed that this is no longer an issue.
