### ISSUE TITLE
Launchpad: Explore ways identify when the subscribers import in the onboarding flow

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#79572]
We need to explore ways to identify when the subscriber's import occurred in the Newsletter onboarding flow. We would use this information to conditionally show the following tasks on the Newsletter launchpad:
  * Manage your subscribers: Should only be shown when the user imports subscribers on the onboarding flow.
  * Get your first 10 subscribers: Should only be shown when the user **does not** import subscribers on the onboarding flow.

Manually import users:
fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qnqq%2Qvaivgr%2Qraqcbvag.cuc%3Se%3Q2q78p9r6%26sv%3QJCPBZ_WFBA_NCV_Nqq_Vaivgr_Raqcbvag%23JCPBZ_WFBA_NCV_Nqq_Vaivgr_Raqcbvag-og

Upload CSV:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfhofpevoref.cuc%3Se%3Qn3n383r7%23590%2Q608-og

We will also need to work on the front-end to provide the onboarding context to the endpoints linked above.

More context: p1689707838483749-slack-C0Q664T29

**Comment by valterlorran** [comment]
I stumbled upon this function, which may help us to identify if the user imported the subscribers on the onboarding flow.

https://github.com/Automattic/jetpack/blob/0f1fbbf9a5c2f6d87c47c0f4e7ce65b7ebd0ddbb/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L634-L641

**Comment by valterlorran** [comment]
@sixhours, we can probably close this when you merge D117188-code, right?

**Comment by sixhours** [comment]
Yep!

**Comment by valterlorran** [comment]
Closing this because we merged D117188-code.
