### ISSUE TITLE
Non super-admins can't see the "Account Closure" article in the Help Center

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#79576]
### Quick summary

_Actually caught by an E2E test, see #78968_

**Note: must test as a non a11n / super-user**

This one, very specific support article is broken in the Help Center. If you try to click on it, it will just show the loading indicator indefinitely!

![Screenshot 2023-07-18 at 4 52 01 PM](https://github.com/Automattic/wp-calypso/assets/26772342/a11749f2-d2fe-4720-a33a-054eb5ef16b9)

Article: "Account Closure"

Here is the specific web request that fails -- looks like an auth issue somehow!

`https://public-api.wordpress.com/wpcom/v2/help/article/9619154/138080?_envelope=1`

```
{
  "body": {
    "code": "unauthorized",
    "message": "User cannot view post",
    "data": 403
  },
  "status": 500,
  "headers": {
    "Allow": "GET"
  }
}
```

Weirdly though, if you click the link to open in a new tab, it opens just fine 🤷:
https://wordpress.com/support/close-account/

Also, somehow, the entry for "Close My Account" that references the _same_ document loads just fine!

### Steps to reproduce

1. Log in as a non super-user or non-a11n account
2. Open help center
3. Search "Account Closure"
4. Click "Account Closure"

### What you expected to happen

Article content loads

### What actually happened

It doesn't! Perma-load (auth failure in request).

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by dpasque** [comment]
(I self triaged and scrubbed this 👍 )

**Comment by worldomonation** [comment]
Slightly concerning that this article isn't showing from the Help Centre. Makes me wonder what other articles have wrong permissions set.

**Comment by dpasque** [comment]
Shoot, I misclosed this, this is still a bug!

**Comment by agrullon95** [comment]
@dpasque - Can we check if this is still an issue?

I tested with a new user and I'm able to load the Account Closure article in the Help Center.

**Comment by heavyweight** [comment]
Also not reproducible for me as well
