### ISSUE TITLE
Checkout submit button no longer showing busy animation

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#79589]
In https://github.com/Automattic/wp-calypso/pull/39816, the checkout submit button was modified to show an animated "busy" animation. Somewhere recently that was lost. We need to get it back.

**Comment by sirbrillig** [comment]
@jjchrisdiehl Maybe this is something you can take a look at?

**Comment by dpasque** [comment]
Adding a priority to keep the triage bots happy 😁 Normal seems appropriate!

**Comment by sirbrillig** [comment]
For reference, [here](https://github.com/Automattic/wp-calypso/blob/2cf3dde2b1bc4e11ebb9500db6cbcb773f540b22/client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.tsx#L108) and [here](https://github.com/Automattic/wp-calypso/blob/2cf3dde2b1bc4e11ebb9500db6cbcb773f540b22/client/my-sites/checkout/composite-checkout/payment-methods/existing-credit-card/index.tsx#L226) is where the busy status is set which should be triggering the animation.

**Comment by sirbrillig** [comment]
I figured out what the problem is: the "busy" animation _is actually running_ but [the regular and accent color](https://github.com/Automattic/wp-calypso/blob/665ebc208a3924b68e2f9fc051551ad643ec5c68/packages/composite-checkout/src/lib/theme.ts#L71C1-L72) for disabled buttons were accidentally made the same in #77353 and therefore it looks like a static gray.

<img width="621" alt="Screenshot 2023-07-20 at 11 52 01 AM" src="https://github.com/Automattic/wp-calypso/assets/2036909/3447cc2a-026b-42d8-adf3-f8f2fd25d680">

Here's what the busy animation looks like if the button is not disabled.

<img width="617" alt="Screenshot 2023-07-20 at 12 10 26 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/1cf7553a-5169-4890-9129-bb633755be1d">

Here's the original busy animation before the redesign.

<img width="618" alt="Screenshot 2023-07-20 at 12 10 47 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/f6e6b5fd-fa75-4735-bc11-ac17bd5ae904">

I can change the accent color to "Gray 0" to match the original color combination (Gray 5 and Gray 0) but then the contrast looks wrong since there's no longer a border, shadow, or dark text.

<img width="715" alt="Screenshot 2023-07-20 at 12 04 50 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/5e7921ce-565c-4876-a025-58f9fb478998">

**Comment by sirbrillig** [comment]
Going to go with "Gray 20" for now to at least make it work. We can improve the colors later.

<img width="614" alt="Screenshot 2023-07-20 at 12 14 27 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/cbea9a6e-7da7-4100-8600-4c6ae4b7cfb3">
