### ISSUE TITLE
Domain: typo in the `root_domain_provider` field when unknown.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#79598]
### Quick summary

When attempting to transfer a domain that shows as unlocked but is not eligible to transfer using the existing/legacy domain transfer flow, the `root_domain_provider` field has the value 'unkwnown'.

```
{
	"body": {
		"domain_name": "<domain.",
		"tld": "com",
		"status": "transferrable",
		"mappable": "mappable",
		"supports_privacy": true,
		"root_domain_provider": "unkwnown",
		"product_id": 1337,
		"product_slug": "domain_transfer",
		"cost": "US$12.00",
		"raw_price": 12,
		"currency_code": "USD",
		"ownership_verification_type": "no_verification_required"
	}
}
```

### Steps to reproduce

Attempt to transfer a domain that's not eligible for transfer.

### What you expected to happen

`root_domain_provider` is correctly set as 'unknown'.

### What actually happened

`root_domain_provider` is erroneously set as 'unkwnown'.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by dpasque** [comment]
Lowering priority to low as this doesn't seem to have a big functional impact.
