### ISSUE TITLE
Launchpad: Create the "Write 3 posts" task

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#79612]
We need to create the "Write 3 posts" task for the Newsletter launchpad. This task requires the user to write three posts to complete it. 

- [ ] Create the new task and the completion logic. The completion logic should take into consideration that the user needs to create 3 posts. For that, I think we can hook into some action fired when the post is created and count how many posts the user has. If it's greater the 3, we should mark it as complete.
- [ ] This task depends on the issue linked below to work properly but we can start creating and then apply the new property and new callback suggested in the issue below.

* https://github.com/Automattic/wp-calypso/issues/79611

**Comment by daledupreez** [comment]
We should also add this task to the write intent task list, as that's a key action we want to encourage for bloggers.
cc @nuriapenya
