### ISSUE TITLE
Iotix - Critical Error on pages when using PHP 8.0

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#79622]
### Quick summary

When `Iotix` is active on a site using PHP 8.0, it causes a critical error when viewing static pages. 

This is the error from CLI:

`[06-Jul-2023 18:00:38 UTC] PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument Automattic/themes#2 ($array) must be of type array, null given in /wordpress/core/6.2.2/wp-includes/block-supports/align.php:48`

Reported in this interaction: 6507135-zd-woothemes

### Steps to reproduce

1. On an Atomic site, activate `Iotix`.
2. Make sure PHP version is 8.0.
3. Visit live site.

### What you expected to happen

The site to load without errors.

### What actually happened

Seeing message about critical error on the site.

### Context

6507135-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Switching to PHP 7.4 resolves the error.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Inconsistent**

📌 FINDINGS/SCREENSHOTS/VIDEO
- On my AT test site (created in May) with all default plugins active, activating **Iotix** while the PHP is set to 8.0 does not result in any critical PHP errors.
- However, on another AT test site where WooCommerce is set up and active (to match the user's site a bit more), I do see the critical error; deactivating all plugins does not help, and the error clears once I switch PHP version back to 7.4. 🤔 

#### Screenshots/Recordings

Test Site where critical error does not appear

https://github.com/Automattic/themes/assets/27249804/a203034e-067b-460a-95a9-a7b5e072e89f

Test Site where critical error does appear:

https://github.com/Automattic/themes/assets/27249804/29acb6be-6620-4ce5-93fa-093a7f3c6872

📌 ACTIONS
- Leaving in `Needs Triage` to see if I can work out the difference that matters later today.

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
- **Tested on Atomic** – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
I tested on my AT site and I couldn't reproduce the critical error. I tried:
- deactivating the plugins, 
- setting up WooCommerce and added products,
- leaving default plugins active


📌 ACTIONS
- Leaving in `Needs Triage` until we have a clearer understanding of how to reproduce the issue.

**Comment by cuemarie** [comment]
Brought this up on an internal thread related to PHP 8.0 errors: p9F6qB-a0S-p2#comment-54218

Moving to `Needs Reply` for now to see if anyone can help there!

**Comment by masperber** [comment]
Another report: 6517130-zen

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - Replicated / Could Not Replicate / Uncertain
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Consistently replicated today when the Homepage is set to use a static page instead of the theme Default.

**Screenshots/Recordings**

https://github.com/Automattic/themes/assets/27249804/6bc83e4b-15c3-4b15-9030-e4080dc9fb2d

📌 ACTIONS
- Also shared findings on internal P2: p9F6qB-a0S-p2#comment-54305
- Assigned to @Automattic/theam

**Comment by dolgelukkig** [comment]
Another report 6542920-zd

Changing to php 7.4 solved the issue for now.

**Comment by retnonindya** [comment]
Another report: 6544085-zd-woothemes

I changed the PHP version to 7.4

**Comment by vcanales** [comment]
Thanks for flagging; I've been investigating and this sounds like a problem upstream rather than with the theme.
The specific line causing the error is in core, here: https://github.com/WordPress/WordPress/blob/54f218ae1881084eea0d73479a9c600bac4fd140/wp-includes/block-supports/align.php#L48

**Comment by edwinho89** [comment]
6548508-zd-woothemes

Changing to php 7.4 solved the issue for now.

**Comment by cuemarie** [comment]
Another report here: p1689785944624399-slack-C03TY6J1A
Site moved to PHP 7.4 to resolve.

Troubleshooting revealed that the critical error appears on any static pages, not just a static page as the homepage. I've updated the report accordingly.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Per @vcanales 's [findings above](https://github.com/Automattic/wp-calypso/issues/79622#issuecomment-1642477666), transferred this back to `wp-calypso`.
- Assigned to Other
- CC: @Automattic/reactor , as there's some troubleshooting happening here: p9F6qB-a0S-p2#comment-54218

**Comment by RafaelFunchal** [comment]
I'm not sure the issue is isolated to Core because it happens only when specific themes are active. I tested Twenty Twenty to Twenty Twenty-Three themes on localhost and only iotix-wpcom gives me that error.

**Comment by cuemarie** [comment]
@vcanales Can you take another look given Raf's [comment](https://github.com/Automattic/wp-calypso/issues/79622#issuecomment-1644796486)? :) Full error list can be found here: p9F6qB-a0S-p2#comment-54489

**Comment by eduardozulian** [comment]
Another case in 6563676-zen - 7.4 worked as well.

**Comment by tanjoymor** [comment]
Another case here: 6567876-zen - 7.4 worked

**Comment by hacchism** [comment]
Another case in 6568219-zen - Site moved to PHP 7.4 to resolve

**Comment by kingsleyinfo** [comment]
Another case here: 6569222-zd-woothemes switching the version solved this.

**Comment by kuropixel** [comment]
Another case. 6579862-zen Site changed to 7.4 to resolve.

**Comment by worldomonation** [comment]
> Thanks for flagging; I've been investigating and this sounds like a problem upstream rather than with the theme. The specific line causing the error is in core, here: https://github.com/WordPress/WordPress/blob/54f218ae1881084eea0d73479a9c600bac4fd140/wp-includes/block-supports/align.php#L48

@vcanales @RafaelFunchal I'm pinging both of you again because it appears there's some disagreement on the root cause of this issue resulting in this ticket being bounced back and forth. With 10+ HE interactions, this ticket is starting to cost a non-trivial amount of money for Automattic, so it's in our best interest to narrow things down.

I'll be upfront, I'm not familiar with this piece of code. That said, I'd like to propose opening an issue upstream if there's a chance that core is the root cause of this issue. How does that sound?

**Comment by inaikem** [comment]
Another case. 6584220-zen Site changed to 7.4 to resolve.

**Comment by vcanales** [comment]
I went back to this; the error message is only tangentially related, but after much trial and error, I found that a navigation block being marked up incorrectly was probably to blame. PR: https://github.com/Automattic/themes/pull/7277

I've attached the fixed theme from that PR so that you may test locally as well.

Attachment: [iotix.zip](https://github.com/Automattic/wp-calypso/files/12180235/iotix.zip)

**Comment by RafaelFunchal** [comment]
Thank you, @vcanales :)

The new theme version works for me on both localhost and WoA.

**Comment by vcanales** [comment]
PR Merged, and Iotix deployed.

**Comment by Gustavo-Hilario** [comment]
I got another instance of this issue: 6597103-zen
Theme: Twenty Twenty-Three
_Switching from PHP 8.0 to 7.4 fixed this issue_

Here is the error message I see on their site:

`PHP Fatal error:  Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, string given in /wordpress/plugins/gutenberg/16.3.0/build/block-library/blocks/latest-posts.php:60`

The original report said `null` was given, but now I see `string`. I'm reopening this so devs can take a look. If this is a different issue, let me know so I can create another bug report.

**Comment by cuemarie** [comment]
@Gustavo-Hilario As your user's site is on TT3, not Iotix, this should be a new report - the fix here was deployed specifically to the Iotix theme.

Reported here instead: https://github.com/Automattic/wp-calypso/issues/80104
