### ISSUE TITLE
Launchpad: Create the Newsletters Launchpad components on the front end

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#79635]
Similar to the [Keep Building](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/customer-home/cards/launchpad/keep-building.tsx) component, we'll need a new component for the Free and Paid Newsletters task lists.

I believe we can have both of the task lists together since they will be very similar.

**Comment by sixhours** [comment]
Closed in #79846
