### ISSUE TITLE
Billing History: Incorrect plan name in past receipts

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#7963]
#### Steps to reproduce
1. Starting at URL, on an account with a Personal plan: https://wordpress.com/me/billing
2. Check the "Upcoming Charges" section for your next Personal plan renewal, and note the name ("WordPress.com Personal")
3. Scroll up to the receipts section, find your Personal plan receipt, and note the name ("Personal Bundle")
4. View the receipt for the Personal plan purchase, and note the name in the Order Summary ("Personal bundle")
#### What I expected

I expected to see consistent naming ("WordPress.com Personal") throughout the billing history page.
#### What happened instead

In past receipts, the Personal plan is called "Personal bundle." This only seems to affect Personal plans; Business and Premium plans are named consistently as expected.
#### Browser / OS version

Mac OSX 10.11.6, Chrome 53.0.2785.89
#### Screenshot / Video

Correct name in upcoming charges section:

![screen shot 2016-09-08 at 2 39 28 pm](https://cloud.githubusercontent.com/assets/8658164/18351555/91275544-75d2-11e6-9401-48abfde9cf50.png)

Incorrect name in receipts section:

![screen shot 2016-09-08 at 2 39 37 pm](https://cloud.githubusercontent.com/assets/8658164/18351572/9f378870-75d2-11e6-941c-0de0f020dbe8.png)

Incorrect name on the receipt:

![screen shot 2016-09-08 at 2 39 45 pm](https://cloud.githubusercontent.com/assets/8658164/18351597/c1dc53ba-75d2-11e6-9973-8e0ef7413662.png)
#### Context / Source
# dogfooding

**Comment by janm6k** [comment]
Going through issues on meetup, closing the ones that we (Absinthe) think we can get away with.

Please feel free to reopen when applicable.
