### ISSUE TITLE
Billing History: Woo products appearing in WordPress.com receipts

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#7964]
#### Steps to reproduce
1. On an account with at least one WordPress.com purchase and one WooCommerce purchase, starting at URL: https://wordpress.com/me/billing
2. Note that the receipts section includes WooCommerce purchases
3. Open the "All Apps" filter for the receipts, and select "WordPress.com"
#### What I expected

I was surprised that WooCommerce products appeared in my Billing History on WordPress.com at all, but I expected that selecting "WordPress.com" would limit the receipts to only WordPress.com products.
#### What happened instead

The WooCommerce products remained in the list after selecting "WordPress.com."

The Woo product names also had unexpected prefixes ("themes" and "plugins")
#### Browser / OS version

Mac OSX 10.11.6, Chrome 53.0.2785.89
#### Screenshot / Video

![screen shot 2016-09-08 at 2 51 22 pm](https://cloud.githubusercontent.com/assets/8658164/18351914/05a5c44a-75d4-11e6-87c6-1f2128bd533a.png)
#### Context / Source
# dogfooding

**Comment by gwwar** [comment]
@rachelmcr do you know what filters should appear under the "ALL APPS" dropdown?

**Comment by rachelmcr** [comment]
I'm not sure what filters are expected here, but personally I'd expect them to match the various services in Payments Admin.

**Comment by kwight** [comment]
> The Woo product names also had unexpected prefixes ("themes" and "plugins")

These product names are assembled in a very fragile way; related to #112 .

**Comment by Copons** [comment]
Ok, I've tracked down what goes wrong where.
The endpoint only considers `connect` products as Woo, and returns them as `Store Services`.

Though, normally, Woo products have the `woo` slug, which is not mapped in the endpoint and is returned as `WordPress.com`.

At this point I can do two things:
- Map `woo` products as `WooCommerce`, and display them in Calypso's billing history (the filtering by "All Apps / WooCommerce" would come for free).
- Filter out `woo` products in the endpoint.

@Automattic/payments what should I do here?

**Comment by jeffstieler** [comment]
> The endpoint only considers `connect` products as Woo, and returns them as `Store Services`.

Yep - those products (currently) represent shipping label purchases from both self-hosted [WooCommerce Services](https://github.com/Automattic/woocommerce-services) and the Store functionality on WordPress.com, hence the genericized "Store Services" name.

Any changes to the behavior of `connect` products needs to involve @Automattic/hydra - thanks!

**Comment by Copons** [comment]
For context: I've updated D11598-code to the [first option](https://github.com/Automattic/wp-calypso/issues/7964#issuecomment-372723205):

> - Map `woo` products as `WooCommerce`, and display them in Calypso's billing history (the filtering by "All Apps / WooCommerce" would come for free).

**Comment by Copons** [comment]
Fixed in D11598-code!
