### ISSUE TITLE
Paid Stats: Improvements to purchase success notices

### ISSUE THREAD

**Issue by annacmc** [Automattic/wp-calypso#79652]
- [x] Remove the query string from the window URL without a refresh in both `FreePlanPurchaseSuccessJetpackStatsNotice` and `PaidPlanPurchaseSuccessJetpackStatsNotice` components. 
https://github.com/Automattic/wp-calypso/pull/79897
- [ ] <strike>Consider combining/refactoring the `PaidPlanPurchaseSuccessJetpackStatsNotice` and `FreePlanPurchaseSuccessJetpackStatsNotice`  components into a single component</strike>

**Comment by kangzj** [comment]
> Consider combining/refactoring the PaidPlanPurchaseSuccessJetpackStatsNotice and FreePlanPurchaseSuccessJetpackStatsNotice components into a single component

IMHO the two components are pretty good as is - if we combine them, there would be some `if..else` s to differentiate the notices, which is not particularly ideal I guess.
