### ISSUE TITLE
Design Picker: Add a "Design your own" button that lands in the Assembler

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#79655]
## Description 

As suggested in p1689804980329489-slack-C048CUFRGFQ, let's add a button "Design your own" on the right side of the theme categories section. Currently, the Assembler CTA is only available at the bottom of the theme list.

![Image](https://github.com/Automattic/wp-calypso/assets/797888/41e50478-f83c-4353-8fef-bbe7faa5d29c)

Note: Mobile design might not be needed since the Assembler does not support mobile view.

## Acceptance Criteria

- [ ] Confirm design with @lucasmendes-design.
- [x] Implement the button.
- [x] Implement Tracks events.

**Comment by autumnfjeld** [comment]
p1689817067724439/1689804980.329489-slack-C048CUFRGFQ
Agree that the button should not exist on screen width < 960px (I believe that is the current breakpoint) since the user would just be sent the Editor.

**Comment by autumnfjeld** [comment]
I do not think we need design for this, @taipeicoder's design is perfectly acceptable.   Simply add at it as a link, in the same format as the categories and make it right justified.  We can circle back to adapt the link/button as needed when @lucasmendes-design has time to comment.    Note Lucas this will need to be considered when we expand the category list.

This is very high priorty and very easy. Matias asked for it one week ago. Let's make sure it ships this week.

**Comment by taipeicoder** [comment]
> Note Lucas this will need to be considered when we expand the category list.

Worth keeping an eye on https://github.com/Automattic/dotcom-forge/issues/3057

**Comment by fushar** [comment]
This is shipped!

|Before|After|
|-|-|
|<img width="1240" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/47b6f245-e7e7-41e4-b602-48aeb90ecaba">|<img width="1239" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/19698ecf-129b-4bc6-9d85-560a1177478f">|

Tracks event: `calypso_signup_design_picker_design_your_own_top_button_click`

<img width="652" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/d7242b31-1130-48ef-9502-3ddbcdbc06aa">

**Comment by lucasmendes-design** [comment]
Let's see the metrics for that change 🚀 I'm excited about it 😊

**Comment by autumnfjeld** [comment]
Excellent everyone!   Thank you for the fast execution!

**Comment by autumnfjeld** [comment]
@fushar  Request from Matias to make the "Design your own" button same height as the black highlight:

The black height is 48-6-6 = 36px

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/2b654c12-d187-48a7-ae05-66c7bae87669)

The button is 40px.   

Can you make the button 36px?  And align with the black category-selected box.

See how these toggles on the right match the height of the `is-pressed` state.



![Image](https://github.com/Automattic/wp-calypso/assets/5665959/59e86c50-f40f-4a4c-9ced-fe8abe56de88)

Thank you. 😄 

Not urgent.

**Comment by fushar** [comment]
> The button is 40px.

> Can you make the button 36px? And align with the black category-selected box.

@autumnfjeld Thanks for the feedback, we have implemented it via #79952.
