### ISSUE TITLE
Advanced SEO: Title editor data doesn't change if you switch sites

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7966]
**To reproduce**
1) Visit https://wordpress.com/settings/seo with a business plan.
2) Change some of the title formats and save your changes.
3) Switch to another site that has the business plan.
4) Observe that the same data from the first site is still displayed in the title format fields.

**Comment by MicBosi** [comment]
**more fun**
1) edit title format
2) save
3) reload page
4) title format is empty!
then
5) click "Analytics" tab
6) click "SEO" tab
7) title format is back!
then
8) reload page
9) title format present as expected
then
10) remove the title format
11) save
12) 50% chance you get it back, if not, don't worry...
13) click "Analytics" tab
14) click "SEO" tab
15) title format is back!
**also**
Sometimes saving after clearing a title structure brings back the format you just deleted.
