### ISSUE TITLE
Advanced SEO: Title format editor crash on Chrome

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7967]
Chrome (Windows and macOS) will become unresponsive if you perform the following actions:

1) Add a token to a field.
2) Add a token to a different field.
3) Crash!

![screen-shot-2016-09-08-at-5-15-12-pm](https://cloud.githubusercontent.com/assets/789137/18358328/6094ab12-75a9-11e6-8a33-b9bcbfea2204.png)

**Comment by rachelmcr** [comment]
To clarify, I haven't tested this in Windows — this crash happened to me on Mac OSX 10.11.6, Chrome 53.0.2785.89.

**Comment by roundhill** [comment]
> To clarify, I haven't tested this in Windows — this crash happened to me on Mac OSX 10.11.6, Chrome 53.0.2785.89.

Oh, thanks I actually reproduced on mac as well. Updating title!
