### ISSUE TITLE
Advanced SEO: Title format fields should be disabled on a private site

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7968]
Like the other settings at `settings/seo`, the title format fields should be disabled when the site is `private`.

![screen-shot-2016-09-08-at-5-07-00-pm](https://cloud.githubusercontent.com/assets/789137/18358438/e6e0a05e-75a9-11e6-9274-67216225faae.png)

**Comment by dmsnell** [comment]
@roundhill as per the discussion in #7980 (@drw158 please feel free ti chime in here) are we sure we want to disable this for private sites?

I still think that private sites with multiple users might still have a reason to edit the title formats, even if it won't apply to SEO.

Is that an invalid concern?

**Comment by roundhill** [comment]
I don't really care at this point :) Should we just leave it as-is?

**Comment by dmsnell** [comment]
maybe @drw158 or @folletto could give a final opinion. I don't care too much; it's just my intuition thinking it would be premature to remove it

**Comment by folletto** [comment]
> I still think that private sites with multiple users might still have a reason to edit the title formats, even if it won't apply to SEO.

I agree. Editing the title has functionality beyond SEO, so I'd keep it enabled.

**Comment by drw158** [comment]
Here is what the disabled token component looks like now:

![screen shot 2016-09-30 at 10 07 14 am](https://cloud.githubusercontent.com/assets/618551/18996432/f09f1a6e-86f5-11e6-87e2-921fff11864a.png)

They probably didn't account for this situation when they made the component. I think just changing the token background to $gray would do the trick:

![screen shot 2016-09-30 at 10 07 53 am](https://cloud.githubusercontent.com/assets/618551/18996473/0d7e4646-86f6-11e6-86f1-73cdf0260ec1.png)

**Comment by lancewillett** [comment]
Moving to normal priority.
