### ISSUE TITLE
Payments Modal: Fix font-sizes

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#79689]
Currently de modal has two different font sizes and it creates a confusing information architecture.

Input labels and descriptions have `font-size: 14px` (red) and toggles, `font-size: 13px` (blue).
Ideally toggles should have `font-size: 14px`.

![Image](https://user-images.githubusercontent.com/25607244/254908837-9a142485-e331-4a98-8aa6-cc99e22b3dc2.png)

**Comment by lezama** [comment]
Thanks Cris!
