### ISSUE TITLE
Advanced SEO: Add indication for long meta descriptions

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#7969]
Currently, when you enter a long meta description for a post (longer than 160 characters), the character count turns red like a warning:

![screen shot 2016-09-08 at 11 29 54 am](https://cloud.githubusercontent.com/assets/7240478/18359533/94e146ec-75b7-11e6-86e5-95d6e87aa8a0.png)

Users that aren't familiar with SEO best practices might not know what that means or why they're being limited. We could add a notice about this either:

A) In the info popover like this:

![screen shot 2016-09-08 at 11 31 30 am](https://cloud.githubusercontent.com/assets/7240478/18359592/cea832be-75b7-11e6-84bb-98496ea0b107.png)

B) As an info popover when the character count is over 160 similar to how we treat long Publicize messages:

![screen shot 2016-09-08 at 11 32 25 am](https://cloud.githubusercontent.com/assets/7240478/18359630/fe3a1966-75b7-11e6-9732-3fec7219f810.png)
# manual-testing

**Comment by jeremeylduvall** [comment]
This is a pretty easy fix, and I think it would be really helpful for users that aren't that familiar with SEO.

**Comment by gracie** [comment]
I'd like to both bump this issue, and revise it.

We emphasize 160 characters here, when a) exceeding the character limit doesn't hurt the page's SEO and b) Google has had the search result excerpt set to 300 characters since December.

My Request: Increase the character limit to 300 characters.

**Comment by jeremeylduvall** [comment]
I chatted with @chrisfromthelc about this a bit in Slack. Google technically can display up to 320 characters, but on average, it still displays about 160 characters (seems like a lot of factors at play - [article](https://searchengineland.com/google-confirms-it-shortened-search-results-snippets-after-expanding-them-last-december-298196)). Still the current red warning experience with no additional info is sub-optimal. We could do the following:

- Normal/gray color from 0-160
- Yellow warning color with info bubble from 161-320
- Red warning color with different info bubble from 321+

**Comment by arunsathiya** [comment]
I am closing this as the Calypso editor does not exist anymore. An equivalent Gutenberg editor request is here - https://github.com/Automattic/wp-calypso/issues/44777
