### ISSUE TITLE
Advanced SEO: Display indicator if Site Name or Tagline fields are empty

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#7970]
This is a bit of an edge case, but we currently don't have a great way of handling sites with empty Site Names and/or Taglines.
#### Steps to reproduce
1. Setup a site with an empty site title and/or tagline
2. Go to https://wpcalypso.wordpress.com/settings/seo/
3. Use `Site Name` and `Tagline` in any of the fields.
#### What I expected

I expected to see a preview under the field. However, since the name and tagline fields are empty on my site, I see nothing. In this case, I know why this is happening, but if I didn't recently remove my site name and tagline, I might wonder why I'm not seeing anything.
#### What happened instead

I don't see any preview or indicator of why the preview is missing.
#### Browser / OS version

Latest Chrome
#### Screenshot / Video

![screen shot 2016-09-08 at 11 44 27](https://cloud.githubusercontent.com/assets/7240478/18360046/b2d0e1ce-75b9-11e6-93da-70c1ca8e529c.png)

This is pretty rare to run into with users. It might be too much of an edge case to consider. One solution though would be to disable the `Site Name` button if the site doesn't have a title. We could show a popover on hover indicating why the button is disabled.
# manual-testing

**Comment by dmsnell** [comment]
@jeremeylduvall how about replacing the preview text with something like, "The title is blank because X or Y is blank" (with better wording)

**Comment by jeremeylduvall** [comment]
I think that could work. We could link to https://wordpress.com/settings/general/ so users could click the link and fix the situation.

**Comment by dmsnell** [comment]
Closing because this failed to gain priority and started collecting dust.
