### ISSUE TITLE
Image Editor: Handle when image fails to load

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#7971]
If an image fails to load in the editor we should display an [error notice](https://wpcalypso.wordpress.com/devdocs/design/notices) that lets the user know what happened.

Common error cases would be:
1. Image never finishes loading
2. Image is supposed to have CORS headers but doesn't. Which [taints the canvas](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image).
3. Drawing the image to canvas fails

We can simulate the errors by throwing them locally in the image editor functions. 

To enable the image editor:

1. Navigate to http://calypso.localhost:3000/post
2. Select a site
3. Add an image
4. Select the image
<img width="914" alt="screen shot 2016-08-09 at 2 12 35 pm" src="https://cloud.githubusercontent.com/assets/1270189/17533873/91f17788-5e3b-11e6-854d-3a23fbcfb366.png">
5. Click "Edit", then click on "Edit Image" in the top right corner of the detail view
<img width="917" alt="screen shot 2016-08-09 at 2 12 43 pm" src="https://cloud.githubusercontent.com/assets/1270189/17533877/961582f0-5e3b-11e6-813e-5cfadb5d47b6.png">
6. The image editor should load.
<img width="912" alt="screen shot 2016-08-09 at 2 12 58 pm" src="https://cloud.githubusercontent.com/assets/1270189/17533939/dc97dbc4-5e3b-11e6-8608-57bb43512ced.png">

**Comment by retrofox** [comment]
In some way we will avoid a bit more this situation once merged https://github.com/Automattic/wp-calypso/pull/7977. Let's implement it anyway.

**Comment by retrofox** [comment]
We have a z-index issue here when we wanna show a global error and the image editor modal at the same time. Pay attention to the red global error:

![image](https://cloud.githubusercontent.com/assets/77539/18367983/06f4102a-75f4-11e6-917e-2ad0ca5b2864.png)

Beyond of the discussion if we should swap the level of both elements and how to do it (model and error global notice) in this case I suggest hide the modal and show the global error because doesn't make sense show the modal there since the user won't can edit the image in any way.

**Comment by gwwar** [comment]
I would suggest navigating back to the media detail view, which you should be able to get to by calling: `this.props.onImageEditorCancel`

**Comment by retrofox** [comment]
I was thinking to add an `onLoadError` to canvas component.

**Comment by gwwar** [comment]
Sorry @retrofox let's use an inline notice over a global one. We already do this in the media modal for other validation errors

**Comment by retrofox** [comment]
Ok, it seems finally we have to solve this visual issue.

The global error is behind of the modal.

![image](https://cloud.githubusercontent.com/assets/77539/18369272/24ffdb2e-75fb-11e6-8a6d-a6d2a59fccb3.png)

I'm not sure what's a good solution for this. @adambbecker do you have some opinion here?

**Comment by gwwar** [comment]
Closed by @retrofox in #8002
