### ISSUE TITLE
Site Assembler: the /start/with-theme-assembler step should not require specifying the base theme in the query string

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#79728]
Currently, the full starting point URL for the Site Assembler flow is something like `https://wordpress.com/start/with-theme-assembler/domains-theme-preselected?theme=creatio`. This is fragile, because when in the future we ever change the base theme, the URL would need to be updated in all places which reference this flow.

We should make it so that we always use a predefined default theme (e.g. creatio).

### Before

`https://wordpress.com/start/with-theme-assembler?theme=creatio`

### After

`https://wordpress.com/start/with-theme-assembler`

@Automattic/lego

**Comment by fushar** [comment]
As discussed, we decided to always use Creatio and ignore the query param.

And this is shipped!

**Comment by autumnfjeld** [comment]
@fushar Can you update the desicription with a clear BEFORE and AFTER,  e.g. stating the before and after URL.

**Comment by fushar** [comment]
> @fushar Can you update the desicription with a clear BEFORE and AFTER, e.g. stating the before and after URL.

@autumnfjeld Thanks, this is done.
