### ISSUE TITLE
Task: cleanup React warnings relating to textarea on /read/conversations

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#79726]
### Details

There are three console errors currently showing for /read/conversations:

<img width="930" alt="Screenshot 2023-07-18 at 5 34 13 PM" src="https://github.com/Automattic/wp-calypso/assets/17325/1bc484d3-0e37-4f80-a02e-8f261324ee2e">
<img width="1138" alt="Screenshot 2023-07-18 at 5 34 20 PM" src="https://github.com/Automattic/wp-calypso/assets/17325/76272c12-5492-42ee-9b54-c348fa2fbf17">
<img width="1146" alt="Screenshot 2023-07-18 at 5 34 26 PM" src="https://github.com/Automattic/wp-calypso/assets/17325/f5ce2dce-639b-4306-8986-0630d30f82e8">

They are related to:
- Passing down too many props using the spread operator
- Trying to use a `ref` with a functional component

cc @tyxla - in case there's room in your schedule for a spot of 🧹 

### Checklist

- [ ] Restrict props sent to `textarea` element from HOCs
- [ ] Ensure refs aren't attached to functional components in textarea-enhancing HOCs

**Comment by tyxla** [comment]
cc @flootr - perhaps would you have some spare time to take a look at those?

**Comment by tyxla** [comment]
@flootr's got a fix already in #79787 - thanks!

**Comment by bluefuton** [comment]
Thanks for the swift PR @flootr 🙌
