### ISSUE TITLE
Design Picker: Use wp_is_block_theme to Determine Whether a Theme Is a Block Theme

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#79732]
To only show block themes in the Desing Picker, we check the `full-site-editing` theme tag.

This is not really needed anymore as we can use the Core [`wp_is_block_theme()`](https://developer.wordpress.org/reference/functions/wp_is_block_theme/) function, simplifying the theme developers' work, who won't need to care about the tag anymore.

**Comment by mmtr** [comment]
Fixed by D116698-code
