### ISSUE TITLE
Task: Consider removing strikethrough for completed launchpad tasks

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#79747]
### Details

As suggested by @lucasmendes-design in this thread - pdtkmj-1E4-p2#comment-3021 - we should consider removing the strikethrough effect for completed tasks to make them easier to read.

### Checklist

- [ ] Make a decision regarding our continued use of strikethrough for completed tasks
- [ ] If needed, create any follow-up tasks

**Comment by sixhours** [comment]
@nuriapenya 👋 Have you had a chance to consider this? What do you think?

**Comment by nuriapenya** [comment]
@sixhours @daledupreez Sorry for the delay on that one, but yes, I prepared a new design for completed tasks without the strikethrough and tweaked some styles around to make it even more intuitive. Here's the P2 with the comparison: p9Jlb4-8Sp-p2

**Summary of changes:**

Completed tasks: Strikethrough → Not strikethrough
Completed tasks: Checkbox --color-neutral-50 → --color-neutral-40
Active tasks: --color-neutral-80 → --color-neutral-100
