### ISSUE TITLE
Editor Top Toolbar display issues From Gutenberg 16.x

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#79769]
### Quick summary

With Top Toolbar selected, the bar “takes over” more horizontal space than expected in GB 16.x

A video (self-hosted) and screenshot (WPcom + Yoast) follow. Both browsers were at 1280px wide:

**Self-hosted video:**

https://github.com/Automattic/wp-calypso/assets/66711744/54abd297-9064-4bc4-85e4-423a92756996

**WPcom + Yoast image:** 
<img width="1319" alt="image" src="https://github.com/Automattic/wp-calypso/assets/66711744/aecf8687-1e8a-41b5-b9db-48709b5677b8">

As you can see, the default expanded state covers the `Save Draft`/`Update` buttons, and preview icon + some of the `Publish` button.

With plugins that add elements to the top bar active (Yoast in this case), the effect is more pronounced and looks like a glitch to the untrained eye.

### Steps to reproduce

1. Open a post.
2. Select "Top Toolbar" from the GB settings panel.
3. Expand/contract the toolbar using the double chevron icon. 

### What you expected to happen

I expected the toolbar to cover other elements on the right of the editor when necessary (lots of options).

### What actually happened

Buttons on the right of the top toolbar were unecessarily covered.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

I raised this in Slack via: p1690077406281749-slack-C0160HSMDQV

There is a companion issue in Core here: https://github.com/WordPress/gutenberg/issues/52688

I've created this report for WPcom HEs who come across this issue and want to record interaction IDs/have some additional context.

**Comment by zdenys** [comment]
6559005-zd-woothemes

**Comment by annezazu** [comment]
Just want to note that this PR will fix the problem: https://github.com/WordPress/gutenberg/pull/52722 Available in Gutenberg 16.4.

**Comment by cuemarie** [comment]
📌 NOTE
- For any HEs with user reports of this, feel free to track here, but you can also let folks know that the fix for this should reach their sites in around 2 weeks (from date of comment).

If users need a workaround in the meantime, they can turn off the Top Toolbar and use the block toolbar instead.

**Comment by edwinho89** [comment]
6540504-zd-woothemes

**Comment by csabarakasz** [comment]
6580703-zd-woothemes

We worked on a different issue with the user, but I noticed the same error.

**Comment by annezazu** [comment]
GB 16.4 went out today but this was backported to 6.3 previously. Thus far, I can't replicate on WPCOM, _unless_ I make the screen size a bit smaller:

https://github.com/Automattic/wp-calypso/assets/26996883/807cbc7d-424e-4bdb-b61e-69d522398982

Overall though, this problem should be resolved in most cases. Can someone confirm?

**Comment by cuemarie** [comment]
Hey @annezazu ! I took a few recordings of the behavior I'm seeing on WPCOM, as well as on my self-hosted site for reference.  I am not _positive_ of what the intended behavior is as the top bar responds to narrowing screen sizes, so I didn't want to assume what was expected and what wasn't!  Here are the highlights:

ON WPCOM

- "Save Draft" is hidden whenever the top bar chevron is open on WPCOM, even if there's room in the bar for it
- The rest of the Publish & other top buttons hide once the top bar reaches a certain width; very little overlap occurs with the "Publish" button before elements hide
- Installing a plugin like Yoast still creates a more noticeable overlap, as that adds content to the top bar that the responsiveness doesn't seem to acknowledge.

OUTSIDE OF DOTCOM

- "Save Draft" remains, but the `S` in "Save" gets hidden whenever the chevron is opened

---

Free Edge site - 16.4.0-rc.1

https://github.com/Automattic/wp-calypso/assets/27249804/a255918e-7f4a-4ce1-abf4-e8e07ede3302

Atomic - WP 6.3 + Gut 16.3

https://github.com/Automattic/wp-calypso/assets/27249804/c222f393-9aa3-49bb-8b5c-65bd7b1959e4

Atomic - WP 6.3 + Gutenberg 16.4

https://github.com/Automattic/wp-calypso/assets/27249804/c0e42fcf-f18d-4d61-abfd-fd44743a2960

Atomic - WP 6.3 + Gutenberg 16.4, with Yoast installed (per OP example)

https://github.com/Automattic/wp-calypso/assets/27249804/e5089d90-9546-4098-9b8d-68b7974fa865

---

For comparison:

Pressable Site - WP 6.3 + Gutenberg 16.4, all other plugins inactive

https://github.com/Automattic/wp-calypso/assets/27249804/2f4b2351-0503-491a-925a-21ae688f34a0

**Comment by annezazu** [comment]
This is very helpful! Thank you. @draganescu can you follow up here?

**Comment by draganescu** [comment]
Yes - thank you for the very helpful and detailed issue. I'm sorry for the hassle.

They're known limitations of the current implementation which can't know how many pinned items are on the right of the header so with all the tweaking some overlap is bound to happen. 

We're working to figure out the overall changes required to allow for a better implementation which places the toolbar in a flow context that does not overlap neighboring UI.

**Comment by draganescu** [comment]
I made  https://github.com/WordPress/gutenberg/pull/53526 for some options around sizing the toolbar when many plugins are enlarging the right side of the header.

**Comment by inaikem** [comment]
Merged into Core here:
https://github.com/WordPress/gutenberg/pull/53526

Closing 👍
