### ISSUE TITLE
"Get started" on tailored use-case landing pages leads to generic flow

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#79779]
### Quick summary

"Get started" button in WP.com header on tailored use-case landing pages leads to generic onboarding flow.

Pinging @Automattic/martech who maintain the landing pages.

<img width="1918" alt="Screenshot 2023-07-25 at 13 56 57" src="https://github.com/Automattic/wp-calypso/assets/87168/eef32eeb-4bb1-438b-bd1b-57886ba4d028">
<img width="1391" alt="Screenshot 2023-07-24 at 10 13 04" src="https://github.com/Automattic/wp-calypso/assets/87168/55a96f24-c398-444e-90c7-c933c8ce3927">
<img width="1394" alt="Screenshot 2023-07-24 at 10 12 39" src="https://github.com/Automattic/wp-calypso/assets/87168/94c720dc-cd1b-4313-86bf-c2397e2b99cb">

### Steps to reproduce

1. Open for example [create blog](https://wordpress.com/create-blog/), [newsletter](https://wordpress.com/newsletter/), or [ecommerce](https://wordpress.com/ecommerce/).
2. Click "get started" from the header
3. End up in different flow than main CTA on each of those pages

### What you expected to happen

Dedicated landing page flow instead.

### What actually happened

Generic flow.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- When starting from any of the 3 pages linked: [create blog](https://wordpress.com/create-blog/), [newsletter](https://wordpress.com/newsletter/), or [ecommerce](https://wordpress.com/ecommerce/), I'm taken into the flow of that particular use-case as expected.

#### Screenshots/Recordings

The landing pages I reached for all 3 flows when starting from the links above:

https://github.com/Automattic/wp-calypso/assets/27249804/7d9ab179-8d74-4dd7-8bf9-b8595f982529

📌 ACTIONS 
- Requested author feedback

📌 Message to Author
- @simison are you still seeing this issue on your side?

**Comment by simison** [comment]
@cuemarie I meant the "get started" in the header, not within the page content:

<img width="1918" alt="Screenshot 2023-07-25 at 13 56 57" src="https://github.com/Automattic/wp-calypso/assets/87168/da2a9bbb-5bc3-4061-9d1d-4a0a44567932">

I'll update the issue for clarity.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO

In each flow, the top right **Get Started** button links to `https://wordpress.com/start/?ref=CTA-slug`, but this just launches the generic flow. 

- **BLOGS** - Starting from https://wordpress.com/create-blog/:
     - **Start a blog** links to `https://wordpress.com/setup/blog/?ref=create-blog-lp`
     - **Get Started** links to `https://wordpress.com/start/?ref=create-blog-lp` 
- **NEWSLETTERS** - Starting from https://wordpress.com/newsletter/:
     - **Start my Newsletter** links to `https://wordpress.com/setup/newsletter/?ref=newsletter-lp`
     - **Get Started** links to `https://wordpress.com/start/?ref=newsletter-lp`
- **COMMERCE** - Starting from https://wordpress.com/ecommerce/:
     - **Get started with eCommerce** links to `https://wordpress.com/setup/ecommerce/?ref=ecommerce-lp`
     - **Get Started** links to `https://wordpress.com/start?ref=ecommerce-lp`

📌 ACTIONS
- Assigned to @martech

**Comment by simison** [comment]
@dzver can Martech own the issue?

**Comment by simison** [comment]
@mtias pointed out that if it's easier, we can at least remove the "Get started" link on tailored pages, if linking it to right place is more work.

**Comment by travisw** [comment]
I think @Automattic/martech-autobots can own this. We're currently working to unify the header and footer navigation across pages/sites (pcNC1U-EP-p2) and handling this once that's wrapped up makes sense to me. cc @niranjan-uma-shankar

**Comment by niranjan-uma-shankar** [comment]
Props @claudiucelfilip, this has been [fixed](https://github.com/Automattic/martech/issues/2055#issuecomment-1801596206) in all Landpack landing pages. The legacy framework pages are still pending. `/ecommerce` (on the legacy framework) is being worked on to be redesigned, so it will soon move to Landpack. Fixing this on the remaining legacy framework pages won't take our immediate priority but if there's any page that should be fixed please let us know.
