### ISSUE TITLE
Subscribers Page: Address user's feedback - checking follower’s primary site 

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#79778]
Some feedback came in from a user in [6534430-zd-woothemes](https://href.li/?6534430-zd-woothemes).

This user regularly checks on their new followers to view their sites and potentially follow them, but that’s difficult on the new Subscribers page:

- You can’t click on a follower’s name/details to see more info, and instead have to use the 3-dot/kebab menu > View.
- The follower’s primary site is identified as the “acquisition source,” which is inaccurate and confusing.
- There’s no quick way to open the follower’s primary site to view it, so you’re forced to copy/paste the URL instead.

**Comment by TimBroddin** [comment]
> There’s no quick way to open the follower’s primary site to view it, so you’re forced to copy/paste the URL instead.

You can click on the name in the list, or the acquisition source

**Comment by phcp** [comment]
@ivan-ottinger Of the topics you listed above, the only part that is missing is related to the unclarity in the acquisition source naming. Do you think renaming it to "Primary site" would be enough?

**Comment by ivan-ottinger** [comment]
Thanks for the ping, Paulo!

> Of the topics you listed above, the only part that is missing is related to the unclarity in the acquisition source naming. Do you think renaming it to "Primary site" would be enough?

"Primary site" sounds good to me. 👍🏼 I would say we could even consider "Site".

Hey @crisbusquets 👋🏼 , do you have a preference here? 🙂 

Adding screenshot for context:

![Markup on 2024-01-24 at 16:23:33](https://github.com/Automattic/wp-calypso/assets/25105483/0faa8789-f0ca-42db-940b-71d7bb968915)

**Comment by crisbusquets** [comment]
Thanks for the ping, @ivan-ottinger 🙌 

Last week I wrote about Subscriber Stats (peKye1-CC-p2), and I updated this copy to `Site`. It's shorter than any other option and easy to understand.

**Comment by phcp** [comment]
Sounds good, I'll change it to `Site` then. Thank you @crisbusquets @ivan-ottinger!
