### ISSUE TITLE
Earn stats: create a no-setup state for /stats/earn interface

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#79781]
When users didn't set up their Stripe account, and head to `/stats/earn`, they should see a CTA for starting the progress:

![Image](https://user-images.githubusercontent.com/1044309/255566364-f4e74b7d-666d-48dc-a9b7-4f77df39a1d5.png)

**Comment by allilevine** [comment]
It doesn't look like this is still needed, but I asked here: p1718651186673689-slack-C0438NHCLSY

Closing for now.
