### ISSUE TITLE
Fix blocked subscribers being counted & shown

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#79783]
Background: pdDOJh-25i-p2

Subscribers page & counts shows subscribers that are currently blocked. This causes an inflated number that doesn't match the amount of sends being shown in newsletter stats.

**Comment by phcp** [comment]
This issue was related to the Number of Subscribers card, which was replaced by the Email Stats Summary card early this year.

Closed by https://github.com/Automattic/wp-calypso/pull/87007
