### ISSUE TITLE
Launchpad: Create the "Add an 'about me' page" task

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#79795]
We should create the "Add an 'about me' page" task for the Newsletters flows. Following Mark's suggestion, we should show the "Update the About page" in case of the themes that come with an "About" page. Otherwise, we should show the new task "Add and 'about me' page".

More context: p1690208547116459/1690208299.259409-slack-C0Q664T29

**Comment by markbiek** [comment]
We're going to need a new endpoint to save some information about the page layout the user selects.

A first pass can be found here: D117895-code

**Comment by markbiek** [comment]
Additional details about my approach/progress so far:

p1691002521466859-slack-C0Q664T29

**Comment by valterlorran** [comment]
Closing this because we merged all the PRs related to it.
