### ISSUE TITLE
Launchpad: Create the "Connect your social media accounts" task

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#79791]
This task should redirect the user to "/marketing/connections/:siteSlug:". I started this thread to ensure what would take to complete this task: p1690209126863629-slack-C057AH42XQD

**Comment by valterlorran** [comment]
Visiting the page should mark the task as complete. Example: https://github.com/Automattic/wp-calypso/pull/79703

**Comment by nelsonec87** [comment]
@valterlorran, It seems this task already exists: https://github.com/Automattic/wp-calypso/blob/trunk/packages/launchpad/src/setup-actions.ts#L47

**Comment by valterlorran** [comment]
Oh! That's great! Thanks for finding it!
