### ISSUE TITLE
Skip to dashboard during /start prevent launchpad redirects

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#79813]
While purchasing a plan during the /start flow I clicked skip to dashboard, I was then taken to the launch pad instead of the dashboard.

- [ ] Disable the redirect when people use the skip to dashboard button.

**Comment by allilevine** [comment]
Currently when I:
1. Go to /start/domains
2. Choose a domain
3. Choose a plan
4. Checkout
5. Click "Skip to dashboard"

I see My Home with `?showLaunchpad=true` in the URL, but not the launchpad. I'll go ahead and close it but feel free to re-open if I missed a step.
