### ISSUE TITLE
Plans: offer personal plan nudge in domain-only checkout page

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#7981]
@meremagee mentioned this the other day and I think it's a good idea. She was purchasing a domain for one of her sites with an existing user, and she said she would have upgraded to the personal plan to get rid of advertisements if she would have thought of it at the time.

We should offer some sort of nudge in the checkout page itself when we see that a user is purchasing a domain for a "free plan" site. Ideally it would be a very simple one-click option to change the cart contents to include the personal plan instead. Maybe we could say something like "For $X more you can upgrade to priority support and remove advertising from your site."

This probably needs a mockup and some love for the wording. /cc @apeatling @adambbecker

**Comment by meremagee** [comment]
Note: this would also be a more relevant place to suggest Google Apps for Biz email for users who are purchasing a custom domain should that offering persist a la carte.
