### ISSUE TITLE
Launchpad: Fix customize badge from onboarding flows

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#79820]
For some reason I am not aware of, the style of the `Customize` badge in the domains field has changed as you can see in these two examples of Newsletter and Link in Bio.

<img width="418" alt="Screenshot 2023-07-25 at 08 37 03" src="https://github.com/Automattic/wp-calypso/assets/7931304/749d5ac8-e3b9-4585-8c97-27e6cba17065">
<img width="408" alt="Screenshot 2023-07-25 at 08 37 08" src="https://github.com/Automattic/wp-calypso/assets/7931304/4b102f98-ecf3-482c-a5be-ac9566a96422">

The correct styles are here in [Figma](9wpoYJrMlYKAKUYvVBMN74-fi-4404_2780):
<img width="1440" alt="Desktop" src="https://github.com/Automattic/wp-calypso/assets/7931304/db265302-b2e7-4a8a-b1a2-034c6fadb40c">

**Comment by cuemarie** [comment]
_As part of KitKat's standard triaging process (PciE2j-1TF-p2), I've added a priority label to this issue and filed it under our DotCom Bug Prioritization Board's appropriate column, which just lets us know that this needs no further attention from us. Feel free to update priority as you see fit!_
