### ISSUE TITLE
Image Editor: Crop box can become misaligned if you resize the browser window

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7983]
#### Steps to reproduce
1. Start editing an image
2. Resize the browser window
3. Observe that the cropping outline doesn't resize properly:

<img width="911" alt="screen shot 2016-09-08 at 3 37 16 pm" src="https://cloud.githubusercontent.com/assets/789137/18369590/918122a0-75db-11e6-99ed-8c819b1fc823.png">

Observed in Chrome on macOS Sierra

**Comment by obenland** [comment]
Gif from #8017:

![wp-calypso-image-editor-2](https://cloud.githubusercontent.com/assets/1270189/18406884/7e877cf2-76b8-11e6-84c0-a8749ed366b7.gif)
