### ISSUE TITLE
Subscriptions: land back to site/post after confirming the subscription

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#79836]
### Details

When I subscribe to a blog as non-logged in user, I go through a flow which ends up at subscription management, thus getting me lost from what I was being subscribed to and reading. This is important particularly if the content I was subscribing to was hidden from non-subscribers.

**Subscribe form**

<img width="500" alt="Screenshot 2023-07-25 at 16 49 50" src="https://github.com/Automattic/wp-calypso/assets/87168/80b8294d-1824-4872-9428-d3fdacb282b1">

**Confirmation email**

<img width="500" alt="Screenshot 2023-07-25 at 16 49 38" src="https://github.com/Automattic/wp-calypso/assets/87168/191fcd26-3f1c-4935-ba13-ff99357a3e86">

Both "Confirm" and "manage" linsk lead to "subscription management" page:

<img width="500" alt="Screenshot 2023-07-25 at 16 49 17" src="https://github.com/Automattic/wp-calypso/assets/87168/67f5ec8c-e2e1-42aa-beca-d9766fe071f0">

**Welcome email**

After confirming, I get another email with links to the same management screen as above:

<img width="500" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/36112c08-b946-445c-bdc4-c454be07841b">

### Checklist

- [x] **Land at original site where I subscribed after confirming the email** (priority). D120392-code
- [x] **Land at original post where I subscribed after confirming the email** (priority). D121120-code
- [ ] Adjust copy to avoid "here" language; `Modify how you receive updates here` → `Modify how you receive updates`, the whole sentence could be the link?
    <img width="484" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/5cdacdea-ca5d-4972-abba-2520ea9e7577">

- [ ] Remove "signup" link for customers who are already signed up.
- [ ] Link to individual site's management screen from "manage" links, instead of "all sites management"

    <img width="400" alt="Screenshot 2023-07-25 at 16 49 28" src="https://github.com/Automattic/wp-calypso/assets/87168/05275f1e-7a62-4b5a-83ab-8faa99f6fcec">

**Comment by yansern** [comment]
> Link to individual site's management screen from "manage" links, instead of "all sites management"

Item no. 4 is being addressed in pdDOJh-2lc-p2.

> Adjust copy to avoid "here" language; Modify how you receive updates here → Modify how you receive updates, the 
> Remove "signup" link for customers who are already signed up.

Item no. 2 & 3 we can pick it up as part of pdDOJh-2lq-p2.

>  Land at original site/post where I subscribed after confirming the email (priority).

We might not want to include this as part of pdDOJh-2lq-p2, but depends if work has already started on this. (Update: Some work started with D120392-code for free-subscriber gated content)

**Comment by simison** [comment]
- Landing at site where they subscribed from done in D120392-code
- In progress to land at the post where user started from in D121120-code

Thanks @lezama and @millerf

**Comment by simison** [comment]
@yansern would be great if Apex can indeed handle the other subscription management related issues. ❤️

**Comment by millerf** [comment]
> In progress to land at the post where user started from in D121120-code

Deployed
