### ISSUE TITLE
Business Monthly site can't buy Paid Themes

### ISSUE THREAD

**Issue by RafaelFunchal** [Automattic/wp-calypso#79847]
### Quick summary

A user contacted us via the[ pt-BR Forums](https://wordpress.com/pt-br/forums/topic/ativar-tema-basti/) about issues buying the Basti theme for their Business Monthly site.

After clicking on the button to buy the theme, this message is displayed on the browser console:

```
https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js
Uncaught (in promise) Error: Cannot add product for this type of cart.
    at Q (52203.96e9540bf2318b1516a4.min.js:1:13011)
    at c (52203.96e9540bf2318b1516a4.min.js:1:14147)
    at 52203.96e9540bf2318b1516a4.min.js:1:12288
```

Although it is not possible to add the theme to the Business Monthly site cart, it worked for one of my eCommerce sites.

### Steps to reproduce

1. SU into the Account ID 207105799.
2. While managing the Site ID 193875890, go to Appearance > Themes > Basti.
3. Click on the button Subscribe to Activate.

### What you expected to happen

I'd expect the page redirects to Checkout with the Basti theme in the cart.

### What actually happened

The page freezes, and this message is displayed on the browser console:

```
https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js
Uncaught (in promise) Error: Cannot add product for this type of cart.
    at Q (52203.96e9540bf2318b1516a4.min.js:1:13011)
    at c (52203.96e9540bf2318b1516a4.min.js:1:14147)
    at 52203.96e9540bf2318b1516a4.min.js:1:12288
```

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on User Site – **Replicated**
- Tested on Atomic Test Site – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- On my AT test sites, I could not replicate this error, after trying the following tests: 
     - BRL as my currency
     - PT-BR as my account language
     - with a monthly Business plan
     - with a monthly eCommerce upgrade in my cart (to match the user's current site set up)
     - On a 2nd AT test site with a custom mapped domain
- When following the steps above to test the User's experience, I encounter the same behavior and console error in Firefox 115.0.2 as reported:

```
Uncaught (in promise) Error: Não é possível adicionar o produto a este tipo de carrinho.
    v https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    f https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    Q https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    c https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    syncPendingCartToServer https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    promise callback*syncPendingCartToServer https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    e https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    e https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    setTimeout handler*../packages/shopping-cart/src/shopping-cart-manager.ts/j/< https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    c https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    d https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    d https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    addProductsToCart https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js:1
    U https://wordpress.com/calypso/evergreen/6399.f6b37d2f4d2f2dd424c8.min.js:1
    o https://wordpress.com/calypso/evergreen/89554.cc86e9add3aaf3cd2c7a.min.js:2
    p https://wordpress.com/calypso/evergreen/89554.cc86e9add3aaf3cd2c7a.min.js:2
    bt https://wordpress.com/calypso/evergreen/theme.f55f3c300084d979d04c.min.js:1
    onClick https://wordpress.com/calypso/evergreen/theme.f55f3c300084d979d04c.min.js:1
    Le https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    Ze https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    Ur https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    Ur https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    Ir https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    Hr https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    cu https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    Te https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    Hr https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    Vt https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
    qt https://wordpress.com/calypso/evergreen/56439.d8a2e3b2000908c5a45e.min.js:2
[52203.96e9540bf2318b1516a4.min.js:1:2564](https://wordpress.com/calypso/evergreen/52203.96e9540bf2318b1516a4.min.js)
```

**Note** - Any `Paid Theme` results in this error on the user's site.

📌 ACTIONS
- Assigned to Other
- Dropping to `[Pri] Normal` as this only impacts 1 customer at this time.
- @Automattic/shilling Can y'all have a look at this user's site to help diagnose?

**Comment by cuemarie** [comment]
Any chance this could be an EBANX thing?

**Comment by RafaelFunchal** [comment]
That is probably a good guess.

Although my account currency is BRL as well, I couldn't replicate the issue on any of my testing sites (Business, Business Monthly, eCommerce, eCommerce Monthly).

It seems to be something isolated to the user account.

**Comment by sirbrillig** [comment]
🤔  That error message comes from the shopping cart validator when the user is attempting to create a new site as part of the purchase, but isn't using siteless checkout, registrationless checkout, Jetpack checkout, nor purchasing a gift or a domain. 

Based on the description above, it sounds like the user was not intending to create a new site as part of this purchase, but rather purchase a theme for an existing site, which should not have triggered this logic. Somehow when this shopping cart was created it had no blog_id.

This is related to https://github.com/Automattic/payments-shilling/issues/1536 where we are attempting to make it more clear when a new site is trying to be created.

**Comment by RafaelFunchal** [comment]
@sirbrillig , is there any workaround to let the user purchase that theme?

**Comment by sirbrillig** [comment]
As long as they have a blog_id in their cart, they won't get this error. I reproduced and you can see that the API request from the themes page is trying to create the cart as "no-site" (a cart without a site). 

![bug-with-themes-page-cart](https://github.com/Automattic/wp-calypso/assets/2036909/7253d261-66d7-4921-b0e6-4af355c75b98)

That should read `193875890` instead of `no-site`.

This is probably a bug with how the themes page accesses the cart. Someone will have to investigate what's going on. I've put this on our team's board (although if you can find what team works on the theme page they might be able to get to it quicker).

> is there any workaround to let the user purchase that theme?

~Could you create a manual payment for the product and add it manually in Store Admin?~ see below

**Comment by sirbrillig** [comment]
Oh, I thought of another workaround: you can construct a checkout URL to add the product to their cart manually. It would be something like https://wordpress.com/checkout/dancacrista.com.br/business,wp_mp_theme_basti_yearly

**Comment by pottedmeat** [comment]
When you click the subscribe button, it's running [`cartManagerClient.getCartKeyForSiteSlug`](https://github.com/Automattic/wp-calypso/blob/cfa1d339cfe565ee5be8ce841128789e09813225/client/state/themes/actions/add-external-managed-theme-to-cart.tsx#L127) which is returning a 404.

<img width="978" alt="image" src="https://github.com/Automattic/wp-calypso/assets/38750/12f21c08-6410-4139-9dce-5dc57e50fa97">

**Comment by pottedmeat** [comment]
[`get_blog_id( 'dancacrista.com.br' )`](fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qzr%2Qfubccvat%2Qpneg%2Qraqcbvagf.cuc%3Se%3Qqqs0r9pr%2333-og) is returning [139724639](https://mc.a8c.com/tools/reportcard/blog/?blog_id=139724639).

<img width="1307" alt="image" src="https://github.com/Automattic/wp-calypso/assets/38750/eda15f15-5d70-47ee-b14e-e2450e2eb466">

They are not listed as a blog owner of the Jetpack site (which has no owner).

**Comment by pottedmeat** [comment]
`get_blog_id('dancacrista.com.br')` is returning Site ID 139724639 which is an ownerless Jetpack site and is what is creating the permissions error.

**Comment by RafaelFunchal** [comment]
> Oh, I thought of another workaround: you can construct a checkout URL to add the product to their cart manually. It would be something like https://wordpress.com/checkout/dancacrista.com.br/business,wp_mp_theme_basti_yearly

I tried that workaround but the browser refreshes and redirects to `https://wordpress.com/plans` without any site selected.

> They are not listed as a blog owner of the Jetpack site (which has no owner).

I checked the Jetpack connection before creating this issue, but it listed `Everything looks great!` and `The connection is healthy` for Site ID 193875890.

I will try to disconnect [Jetpack from 139724639](https://jptools.wordpress.com/debug/?url=139724639) and reconnect it to the right site.

**Comment by RafaelFunchal** [comment]
That was a tough one, but everything works as expected now.

It was necessary to follow these steps to fix the Jetpack Identity Crisis:

1. Disconnect 139724639's Jetpack.
2. Edit 139724639's address to dancacrista-old.com.br.
3. Mark 139724639 as disconnected on its Blog RC.
4. Make dancacrista543826773.wpcomstaging.com the site's primary domain.
5. Edit the local user's password on CLI.
6. Swith to user to reconnect Jetpack.
7. Make dancacrista.com.br the site's primary domain again.

@sirbrillig and @pottedmeat thank you so much for your insights.

@pottedmeat, do you have any idea why [Jetpack Debug](https://jptools.wordpress.com/debug/?url=http://dancacrista543826773.wpcomstaging.com) wasn't showing anything related to 139724639. Normally, Identity Crisis lists the wrong Site ID on Jetpack.

**Comment by pottedmeat** [comment]
> 



> @pottedmeat, do you have any idea why [Jetpack Debug](https://jptools.wordpress.com/debug/?url=http://dancacrista543826773.wpcomstaging.com) wasn't showing anything related to 139724639. Normally, Identity Crisis lists the wrong Site ID on Jetpack.

Sorry, I'm not familiar with that tool.

**Comment by sirbrillig** [comment]
What a weird thing and a strange symptom! I think this issue is complete. @RafaelFunchal you may need to check with the Jetpack folks if you have questions about Jetpack Debug. I'll cc @Automattic/jetpack-voyager in case they know the answer but I'm going to close this issue for now.

**Comment by RafaelFunchal** [comment]
> Sorry, I'm not familiar with that tool.

That is fine. Thanks :)

I think we are at a good point to close this issue. Thank you all <3
