### ISSUE TITLE
Add Welcome email text area to Settings > Reading > Newsletter settings

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#79844]
Discussed on [Slack](p1690293027233459/1690292015.143669-slack-C052XEUUBL4).

Add a `textarea` under **Confirmation email message**, so users can also customize the **Welcome email message** their subscribers receive once they confirm the subscription.

![Image](https://user-images.githubusercontent.com/25607244/255972916-48bfea6d-47f3-4f15-b413-93770bf99ea9.png)

This **Welcome email message** will be the generic one. Then, if some one subscribes to a paid newsletter, we only trigger the one that's created on Earn.

**Comment by crisbusquets** [comment]
For context, this is the default **Welcome email message** a regular subscriber receives:
![image](https://github.com/Automattic/wp-calypso/assets/25607244/45b78feb-6bba-4a41-8bf4-7fe60e8bf6c1)

**Comment by simison** [comment]
Done!
