### ISSUE TITLE
Image Editor: Lots of 'Edit' Buttons

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7985]
It's kind of strange when you click on the `Edit` button to edit an image, and then you click `Edit image` to actually get to the new editor.

Not sure how to improve this UX though, maybe the `Edit image` button could say something like `Crop / Rotate` instead?

**Comment by drw158** [comment]
The next big iteration accounts for this. You won't have to click Edit Image again, and the meta data and image editing would just be one thing.

I don't have a problem with the current design, but a simple text change is reasonable. It could say "Crop", and we already have a crop icon. I think most people would understand that it would also include rotate, but "Crop & Rotate" could work too.

This would also close the problems with users not understanding that you can crop once you hit Edit Image.

**Comment by gwwar** [comment]
@iamtakashi going to punt to v2, feel free to keep 🤔  about this in the meantime
