### ISSUE TITLE
Simple Sites: Footnotes Block breaks when editing published post

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#79864]
### Quick summary

Footnotes disappear when updating a post or page

### Steps to reproduce

1. Start here: https://wordpress.com/post and pick a site
2. Write a paragraph, add a few footnotes
3. Publish the post
4. Edit the post, and just edit the text a little
5. Click update

### What you expected to happen

To be able to edit a post with footnotes

### What actually happened

While the footnote markers appear up top, the footnotes block at the bottom doesn't see them anymore. I can add new footnotes and those will appear, but the original ones are just gone.

https://github.com/Automattic/wp-calypso/assets/3476361/52d9d42d-4a51-4f3e-a31f-06b216ee72ff

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Simple site, classic theme, Chrome on Mac with both current

**Comment by supernovia** [comment]
Also, I tested this on a .org instance. WP 6.2.2 with Gutenberg 16.2.1 does not have this problem.


https://github.com/Automattic/wp-calypso/assets/3476361/5115fb0a-9c78-4f32-a3e5-a7538f4d39a8

**Comment by jerrysarcastic** [comment]
Reported in https://wordpress.com/forums/topic/footnotes-keep-getting-deleted-when-i-update-my-page/?view=all

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described on Simple (Free) site, using Gutenberg 16.2.1.  As soon as the page/post is published, editing the content again breaks the Footnotes block.
- Replicated using Classic and FSE themes (Dalston, then TT3)

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/6f95dcbb-091c-449b-84eb-1940cb867c2f

The same steps on an AT site with Gutenberg 16.2.1 installed do not result in the error:
https://github.com/Automattic/wp-calypso/assets/27249804/d6b167d4-1d67-49c5-b3a7-fb124763bee3

📌 ACTIONS
- Scrubbed, awaiting assignment
- Escalation thread: p1690331529464549-slack-C02FMH4G8

**Comment by p-jackson** [comment]
Potential fix D117086-code

**Comment by p-jackson** [comment]
I've deployed a fix for this issue. Unfortunately if a user has already saved their post after the footnotes disappeared then those footnotes aren't recoverable using revisions and they will need to re-write their footnotes.

Please let me know if there's still a way to reproduce this issue. It might be that there are other sorts of footnotes that I haven't taken into account.

**Comment by supernovia** [comment]
> Reported in https://wordpress.com/forums/topic/footnotes-keep-getting-deleted-when-i-update-my-page/?view=all

Ah! Thank you, I knew I forgot something 🙈
