### ISSUE TITLE
Checkout error about missing postal code for free purchase and new card

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#79875]
To reproduce: add `jetpack_stats_free_yearly` to your cart with no quantity so it's free. Then select the new credit card option (existing cards should be fine) and click to pay. 

![image-12 copy](https://github.com/Automattic/wp-calypso/assets/2036909/a7e7ab6b-aa2d-4e49-9488-3779db8c71da)

This happens because credit cards require tax information (usually just postal code and country) but normally in checkout we get this from the contact step. However the contact step is not shown [if the purchase is free and is not a full credits purchase](https://github.com/Automattic/wp-calypso/blob/d683bc06059349a657052f003f19ce8f13c4001d/client/my-sites/checkout/composite-checkout/lib/get-contact-details-type.ts#L48) and [not a domain product](https://github.com/Automattic/wp-calypso/blob/d683bc06059349a657052f003f19ce8f13c4001d/client/my-sites/checkout/composite-checkout/lib/get-contact-details-type.ts#L21).

Fortunately, the credit card input form actually [has the ability to show its own tax fields](https://github.com/Automattic/wp-calypso/blob/d683bc06059349a657052f003f19ce8f13c4001d/client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-fields.tsx#L45) (which it typically uses for the "Add new payment method" form). We can probably enable that here.

Reported in the p2 post here: pejTkB-Ih-p2#comment-655

**Comment by kangzj** [comment]
Thanks for fixing this 👍
