### ISSUE TITLE
Comments: Not able to log in to comment on iPhone mobile browser

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#79883]
### Quick summary

It seems there is an issue logging in to WordPress.com to comment on a blog on mobile Safari browser on iPhone. We also received a report of problems on iPad as well. 

The only workaround seems to be to use a desktop browser to leave a comment, which is very inconvenient for some users. 

### Steps to reproduce

1. Go to a WordPress.com post with comments enabled.
2. Try to log in to WordPress.com to comment.

### What you expected to happen

I would expect to be logged in and be able to leave my comment. 

### What actually happened

The log in did not work and the Leave a Comment field still shows the prompt to log in: "You must be logged in to post a comment."

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

Tested on iPhone, Safari browser. Tried to test on Google Chrome on iPhone as well, but had problems logging in. 

User report: 6582290-zd-woothemes
The user requested to be contacted if there are any updates on this issue.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Using Safari on my iPhone, I was able to login through the comment form on a test simple site and successfully leave a comment.  Here are some specifics from my test:
     - iPhone XR version iOS 16.5.1 - Mobile Safari
     - Safari Settings (iPhone > Settings > Safari):
          - Prevent Cross-Site Tracking is _enabled_
          - Block All Cookies is _disabled_
          - (Under Advanced) Javascript is _enabled_

My test site is a free simple site with Settings > Discussion set up to match the site the user was trying to log into.

![Markup on 2023-07-26 at 16:38:47](https://github.com/Automattic/wp-calypso/assets/27249804/d0f67ff5-f009-48ee-96eb-81dcf7e03017)

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/2a1ea79e-9c9d-4286-808c-ab36d2afe1b1

📌 ACTIONS
- Requested author feedback

📌 MESSAGE TO AUTHOR
- @jamiepalatnik , can you share your test device's iOS version, and the site you tested that on?

**Comment by Greatdane** [comment]
Just a note, I had this user for a few hours over the last few days and could not replicate after trying for a long time! 
T

**Comment by inaikem** [comment]
I helped them enable third-party cookies (cross-site tracking) on their iPad and closed 139 open sessions. Issue resolved, marking as closed! 🙏
