### ISSUE TITLE
Image Editor: previous edited image flashes before new image shows

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#7988]
When loading the image editor the previous image you edited displays for a few seconds before changing to the actual image you are editing – this can cause user confusion like ‘did I select the wrong image to edit?’

![previous image shown](https://cloud.githubusercontent.com/assets/128826/18371219/f3c66be2-7675-11e6-9341-2e8ecfab6a0f.gif)

**Comment by gwwar** [comment]
We have an in progress PR for a placeholder: https://github.com/Automattic/wp-calypso/pull/7913

This issue is likely a dup of #7376

**Comment by lamosty** [comment]
Yeh, it should be dup, closing.

@alisterscott: if you still get this issue after merging #7913, feel free to reopen. :)
