### ISSUE TITLE
Reader: add a "My Comments" section

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#799]
Raised by @bluefuton 

<blockquote>Visually it's possibly too busy, displaying the full post content for each comment made, and the comments surrounding the current user's comment.

There's no API endpoint to provide this information yet. It looks like it was intended to be part of the `WPCOM_JSON_API_Users_Activities_Endpoint` but is not implemented. We probably would need a new `/me/comments` endpoint.

In order to help us design the new API endpoint, it'd be great to figure out what information we'd like to present if we re-implement it in Calypso.</blockquote>

Notes from @blowery 

<blockquote>I think the API should return the comment itself, with meta links to the post, site, and maybe comment author's user... but that'll be driven by what the stream itself should look like.</blockquote>

Past designs for reference:

![screen shot 2015-06-17 at 11 59 45](https://cloud.githubusercontent.com/assets/17325/8197154/6ab27dae-14e8-11e5-8cca-466fae462686.png)

![screen shot 2015-06-15 at mon jun 15 10 35 52 pm](https://cloud.githubusercontent.com/assets/1119271/8213092/89eecd12-14ed-11e5-8f02-7589b428126b.png)
<sup>Seen at https://wordpress.com/activities/comments/ using Firefox 38.0.5 on Mac OSX 10.10.3</sup>

**Comment by bluefuton** [comment]
The Conversations tool solves this well enough, I think - all comments authored by the current user will be shown there.
