### ISSUE TITLE
Image Editor: Safari OSX doesn't load images to edit correctly

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#7991]
On Safari 9.1.3 on OSX I couldn’t load the image in the image editor at all the first time. Oddly, the second time around the previous image I tried to edit is available for edit?!?

The console error is `"XMLHttpRequest cannot load https://i2.wp.com/testsiteonlyforjuiced.files.wordpress.com/2016/09/img_2394-1.jpg?ssl=1. Origin https://wpcalypso.wordpress.com is not allowed by Access-Control-Allow-Origin."
`

![safari osx](https://cloud.githubusercontent.com/assets/128826/18371288/71590e8e-7676-11e6-9d1d-ab758a916f7b.png)

**Comment by simplysaru** [comment]
I can confirm this behaviour on my mac too with a slight change, the image didn't load for editing at all even after I tried 10-12 times, keep getting the same console error Scott mentioned.

**Comment by retrofox** [comment]
@alisterscott @simplysaru were you testing with a private site?

**Comment by simplysaru** [comment]
I was testing it on a public site. Test site is here. https://saru.me/

**Comment by ryanboren** [comment]
Experienced the same on a site that is hidden from search engines, but not private.

**Comment by artpi** [comment]
If any one of you have time, I'd appreciate feedback if it fixed the issue for you. Worked for me.

**Comment by artpi** [comment]
We have OSS contributor @andrewkolesnikov to thank for that
