### ISSUE TITLE
Unify Calypso links and CTAs styles

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#79934]
Both https://github.com/Automattic/wp-calypso/pull/79851 and https://github.com/Automattic/wp-calypso/pull/79904 tasks has raised concerns about us having a unification on Styles of the Button element.

### The current issues

* We're still overriding an override at [global.scss for the stepper flows](https://github.com/Automattic/wp-calypso/pull/79851/files#diff-1832a76502a45365accb111f5b71221b6eeef3553ec042704dae9134f005d187R172-R186). Ideally, we should need to override WordPress components once [as we already do here](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/stylesheets/_wp-components-overrides.scss#L21-L41). There a lot of overriding across Calypso on these primary buttons.

* [Link text is using Core's new blue](https://github.com/Automattic/wp-calypso/pull/79904#issuecomment-1653414224). A possible solution would be to add `.components-button.is-link` to [the _wp-components-overrides.scss as well](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/stylesheets/_wp-components-overrides.scss)

* In Some places we use Button from Calypso and others from Core WordPress. What are the advantages of using one or another? Should we enforce one of them?

We need to coordinate these changes with designers to make sure we have a consistent UX.
cc @nuriapenya

**Comment by lsl** [comment]
Another PR touching on this https://github.com/Automattic/wp-calypso/issues/79934
