### ISSUE TITLE
Checkout: TypeError: t.addEventListener is not a function.

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#79948]
We see a decent number of this fatal error lately reported to our logs for the `review` step in checkout:

```
TypeError: t.addEventListener is not a function. (In 't.addEventListener(\"change\",e)', 't.addEventListener' is undefined); Stack: subscribe@https:\/\/wordpress.com\/calypso\/evergreen\/80998.92f5bc1f27be58bbb686.min.js:2:191882
```

This looks like a bug in the `useMediaQuery` function (see the mention of `subscribe` and the `change` event which match [the source of that hook](https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/src/hooks/use-media-query/index.js#L41)). Unfortunately, that function is part of the `@wordpress/compose` package and is not in our monorepo. It's in [gutenberg](https://github.com/WordPress/gutenberg/tree/trunk/packages/compose)

[Here is the line where the error probably happens](https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/src/hooks/use-media-query/index.js#L41). There is already a guard for a null `mediaQueryList` above it, so for this to occur, `window.matchMedia()` would have to return an object, just not an object that has an `addEventListener` function. That seems impossible based on the MDN info about `matchMedia` but it clearly happens a lot.

One fix would be to modify `useMediaQuery()` to check for the existence of `mediaQueryList.addEventListener` before calling it. However, this is not easy to do since the gutenberg repo is a dependency.

For a first step, it would be good to stop using `useMediaQuery` in checkout. So... what is triggering this error in the review step? It's a good question since the only places I can find that call that are the [ecommerce trial plan page](https://github.com/Automattic/wp-calypso/blob/d45d153c3e79608a1810e1f787bbf0da80accc31/client/my-sites/plans/current-plan/ecommerce-trial/index.tsx#L42). [the site dashboard](https://github.com/Automattic/wp-calypso/blob/d45d153c3e79608a1810e1f787bbf0da80accc31/client/sites-dashboard/components/sites-sorting-dropdown.tsx#L35), [signup](https://github.com/Automattic/wp-calypso/blob/d45d153c3e79608a1810e1f787bbf0da80accc31/client/landing/stepper/declarative-flow/internals/steps-repository/design-carousel/index.tsx#L94) in the stepper, and the [help center](https://github.com/Automattic/wp-calypso/blob/d45d153c3e79608a1810e1f787bbf0da80accc31/apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.js#L26). Maybe it's that last one?

It's possible that it is the help center code imported by `CheckoutHelpLink` which is in the review step. In that case, these errors might just go away now that that component has been removed by https://github.com/Automattic/wp-calypso/pull/79900 although they haven't gone away yet and it's been several hours since that merge.

**Comment by sirbrillig** [comment]
Tasks:

- Find out what is actually using `useMediaQuery` in the checkout review step.
- Try to replace `useMediaQuery` in the checkout review step with code that is not affected by this bug (that might mean copy/pasting the hook into calypso or replacing it with something else).
- Make an issue in the Gutenberg repo to report this bug.
- (bonus) Make a PR in the Gutenberg repo to fix this bug.

**Comment by sirbrillig** [comment]
@jjchrisdiehl noted in Slack that the `HelpCenter` component used by some of his code and used by `CheckoutHelpLink` might actually not be the same one that I found above (from the editor toolkit) that has `useMediaQuery`... so... where is it coming from?

**Comment by jjchrisdiehl** [comment]
Could it possibly be triggered by the layout helper functions like `isMobile`, `isDesktop`, and `isWithinBreakpoint`? These are used throughout Calypso and maybe used in Checkout somewhere?

There is also [this instance](https://github.com/Automattic/wp-calypso/blob/trunk/packages/wpcom-checkout/src/checkout-line-items.tsx#L966) of `useViewportMatch()` in `<WPLineItem>` which would be in step one in checkout. `useViewportMatch` is [imported from the compose package](https://github.com/Automattic/gutenberg/blob/trunk/packages/compose/src/hooks/use-viewport-match/index.js#L79) and makes use of `useMediaQuery`.

**Comment by sirbrillig** [comment]
Amazing find! I think that must be the issue. I've created https://github.com/Automattic/wp-calypso/pull/79985 to remove that hook since there's an easy alternative: CSS.

**Comment by sirbrillig** [comment]
We should still do this:

> Make an issue in the Gutenberg repo to report this bug.

**Comment by sirbrillig** [comment]
From Sentry records this appears to happen only in Mac OS Safari 13.1

I've created an issue in the Gutenberg repo here: https://github.com/WordPress/gutenberg/issues/53251
