### ISSUE TITLE
ETK: Disabling Jetpack plugin crash wp-admin.

### ISSUE THREAD

**Issue by kozer** [Automattic/wp-calypso#79956]
### Quick summary

I have created a WoA site, and the current ETK version is  3.72793.
Deactivating Jetpack using `wp`, makes wp-admin to crash.

### Steps to reproduce

1. Check ETK is enabled
![etk_enabled](https://github.com/Automattic/wp-calypso/assets/497103/59f77eb9-9ed6-42eb-b052-3ba7373c532f)
2. Disable Jetpack plugin
![disable-jetpack](https://github.com/Automattic/wp-calypso/assets/497103/9dd69aef-3907-4476-88c1-9d74d21c9650)
3, Ensure that `/wp-admin` is crashing
![fatal_error](https://github.com/Automattic/wp-calypso/assets/497103/fe96d10e-f4a6-447a-b491-90048affde6a)

( A note here is that this specific site, due to tests, had Jetpack tokens deleted, and thus, the Jetpack connection was not working. I deleted the tokens using: `wp option delete jetpack_private_options` ) 

### What you expected to happen

The `/wp-admin` shouldn't crash.

### What actually happened

The `/wp-admin` crashed

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

```
[28-Jul-2023 06:34:34 UTC] PHP Notice:  Function WP_Scripts::localize was called <strong>incorrectly</strong>. The <code>$l10n</code> parameter must be an array. To pass arbitrary data to scripts, use the <code>wp_add_inline_script()</code> function instead. Please see <a href="https://wordpress.org/documentation/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.7.0.) in /wordpress/core/6.2.2/wp-includes/functions.php on line 5865
[28-Jul-2023 06:34:34 UTC] PHP Fatal error:  Uncaught Error: Class "Jetpack_Options" not found in /wordpress/plugins/full-site-editing/3.72793/help-center/class-help-center.php:139
Stack trace:
#0 /wordpress/plugins/full-site-editing/3.72793/help-center/class-help-center.php(120): A8C\FSE\Help_Center->get_current_site()
#1 /wordpress/plugins/full-site-editing/3.72793/help-center/class-help-center.php(306): A8C\FSE\Help_Center->enqueue_script()
#2 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): A8C\FSE\Help_Center->enqueue_wp_admin_scripts('plugins.php')
#3 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/core/6.2.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/core/6.2.2/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'plugins.php')
#6 /wordpress/core/6.2.2/wp-admin/plugins.php(605): require_once('/wordpress/core...')
#7 {main}
  thrown in /wordpress/plugins/full-site-editing/3.72793/help-center/class-help-center.php on line 139

```

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – not applicable
Tested on Atomic – confused. See notes below.
Replicable outside of Dotcom – n/a

📌 NOTES
I followed the steps below:

1. set a blog as WoA using the internal tool.
2. confirm that WordPress.com Editing Toolkit/ETK is installed.
3. install a plugin on the WoA site (Hello Dolly) to transfer it to Atomic.
4. launch the CLI.
5. delete the token using `wp option delete jetpack_private_options`.
6. confirm in Jetpack Debug that token is deleted.

At this point, the site itself is still displaying fine.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/caff9dc6-618e-42a3-b26c-a6475f4affdf)

7. deactivate Jetpack using `wp plugin deactivate jetpack`.
8. in Jetpack Debug, confirm the site is not healthy, and both blog token and user token are showing red.

At this point, the site itself **continues** to display just fine.
Refreshing Calypso/WP-Admin however results in the critical error message:
![image](https://github.com/Automattic/wp-calypso/assets/6549265/e8674be8-6bcf-4a20-9f3b-60c9a986f79c)

**Note the only action required to result in this is to deactivate Jetpack plugin**.

I am not 100% certain but believe disabling Jetpack would have always resulted in this behavior. Looking at the Report Card, when Jetpack is disabled the user (in this case, myself) is removed from the blog. Thus when trying to access Calypso, you're trying to access a site that you don't technically own.

📌 FINDINGS/SCREENSHOTS/VIDEO
See above.

📌 ACTIONS
- @kozer please confirm whether "site crashing" means the published site is no longer visible, or if it's referring to navigating in Calypso/WP-Admin?

**Comment by kozer** [comment]
@worldomonation . I'm sorry for the confusion. Yes, this affects only `/wp-admin`. I updated the ticket title and the instructions. Do I need to update the labels as well?

**Comment by kozer** [comment]
@worldomonation . Another note: Adding for example `Jetpack Boost` and disabling Jetpack plugin afterwards, doesn't result in that behavior.
I get for the site to not be accessible through Calypso. But doesn't `/wp-admin` should be fully functional? ( Or semi-functional at least )?
Visiting `/wp-admin`, I would expect to behave like every self-hosted site, despite calypso problems.

For example, even with a broken Jetpack connection, you can still access `/wp-admin`, you just need to add your credentials in order to login.

**Comment by worldomonation** [comment]
> Yes, this affects only /wp-admin

Thanks for clarifying! 

> for example `Jetpack Boost` doesn't result in that behavior. ... Visiting `/wp-admin`, I would expect to behave like every self-hosted site, despite calypso problems.

I'm actually not sure how this should behave. If my memory serves correct (and that's a little suspect at the moment), disabling Jetpack would kill any sites hosted on WordPress.com. I seem to recall running into these kinds of issues in the past when I was messing around with Jetpack.

@jeherve, sorry to ping you in here - is it expected for sites on WordPress.com to display that "critical error" when Jetpack is manually deactivated?

**Comment by jeherve** [comment]
The Jetpack plugin is required on WordPress.com sites, so I think errors are to be expected when you deactivate it.

That said, the ETK plugin is also distributed to self-hosted sites via the plugin directory
https://wordpress.org/plugins/full-site-editing/

As a result, we should aim to make it work even when the Jetpack plugin is not active. That's not the case at the moment, as you figured out. This has been an issue for quite some time, and was reported by site owners 8 months ago:

- https://wordpress.org/support/topic/fatal-error-in-3-49493/

The issue was introduced in #69486. @arcangelini Do you think you could take a look? Could we have a better fallback when `Jetpack_Options` does not exist?

**Comment by kozer** [comment]
@jeherve , do you think it make sense to close that issue then?

**Comment by jeherve** [comment]
No, I think it should be fixed, to help folks running the plugin in a self-hosted environment.
