### ISSUE TITLE
Update copies for paywall and subscribe modal

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#79973]
### Details

As per Matías nudge peKye1-fd-p2, let's make sure copies feel consistent together, especially with the new paywall block, and be familiar with customer's existing experience from outside .com.

<img width="740" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/25556cc9-7569-4e22-853f-42d824f06164">

### Checklist

Situations:

- [ ] The whole post is restricted to subscribers only
- [ ] The whole post is restricted to paid subscribers only
- [ ] Post is partially restricted to subscribers only using a paywall block
- [ ] Post is partially restricted to paid subscribers only using a paywall block
- [ ] Subscribe modal

**Comment by crisbusquets** [comment]
@simison copies and design are on this [Figma file](qQxuiiWjgNV0AiYg6070eo-fi-5_3941), but in short:

**Paywall**
- If they choose "anyone subscribed", the block changes to `Subscriber-only content below`
- If they choose "paid subscribers only", the block changes to `Paid content below this line`

**Subscriber block (frontend)**
Anyone subscribed
- Heading: `Subscribe to continue reading`
- Body: `Subscribe to get access to the rest of this post and other subscriber-only content.`

Paid-subscribers only
- Heading: `Subscribe to continue reading`
- Body: `Become a paid subscriber to get access to the rest of this post and other exclusive content.`


I'm still looking at how it should behave if they select `Everyone`. In the Figma file you'll find some ideas too.
