### ISSUE TITLE
Add-ons: Premium Themes Add-On is available on free site if it used to have a Premium Plan

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#79987]
### Quick summary

Our current add-on logic says the Premium Themes add-on cannot be purchased separately and is only available if the site's plan supports it.

But if the site had a supporting plan before, even if it was years and years ago, the add-on offering is still available for purchase.

You can see at the beginning of this video that I'm using a free plan:

https://github.com/Automattic/wp-calypso/assets/3476361/9c73d6e3-b731-4c99-8cdf-a90184cae5c3

### Steps to reproduce

1. Use an account and site that had Premium before, but no longer does and is now on Free
2. Navigate to https://wordpress.com/plans for that site
3. Note Add-Ons are available, and Premium Themes is one of them. 
4. The yearly option can be added to the cart.

### What you expected to happen

Users should not be able to buy Premium Themes unless their current site plan supports it.

### What actually happened

Users can buy Premium Themes if their site _used to_ have a plan that would support it.  The experience of buying an upgrade, only to be told they have to upgrade again to utilize it fully, is suboptimal. [From this thread](https://wordpress.com/forums/topic/not-happy-with-purchases/):

> I just purchased one year Premium Themes and changed font and backgrounds and now I can’t publish it because I need to upgrade.
> 
> Please explain? If I can’t do the simplest of changes, how do you expect me to be an active advocate of WordPress.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Duplicated in Chrome on Mac current. [Thread here](https://wordpress.com/forums/topic/not-happy-with-purchases/); discussion [here](parYuf-zu-p2#comment-1032).

Noting too, the add-on screen says users can buy themes for $50, but that doesn't appear as an offering on the next screen. I don't know whether that's a bug, but I figured I'd mention it.

**Comment by mmtr** [comment]
> Our current add-on logic says the Premium Themes add-on cannot be purchased separately and is only available if the site's plan supports it.

This is incorrect, as clarified in parYuf-zu-p2#comment-1037. AFAIK the add-on is available and we didn't have any discussion to remove it. What we removed is the ability to buy individual premium themes (see p7DVsv-hCY-p2).

**Comment by mmtr** [comment]
Just realized that the wording is indeed wrong. Users cannot buy premium themes for $50 each. But they can buy the full collection for $2/month.

**Comment by dsas** [comment]
I opened D117551-code to fix the wording.

**Comment by supernovia** [comment]
Looks like there was a misunderstanding on this: premium themes do not require a supporting plan. Closing this.

**Comment by autumnfjeld** [comment]
> Looks like there was a misunderstanding on this: premium themes do not require a supporting plan. Closing this.

Just be clear the _"Premium Themes Add-on"_ does not require a support plan.  
But if a user selects a premium theme in the Theme Showcase or in onboarding it definitely requires a premium plan or 
above.

A screenshot from onboarding:
<img width="1421" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/c3f6bb74-d002-4cd1-b800-f0ee9ad4efc9">

<img width="1177" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/72735a00-e842-41a1-9872-028304f18401">
