### ISSUE TITLE
Suggestion: Improve language of DNS import on “Add your domains” step

### ISSUE THREAD

**Issue by sethmclellana8c** [Automattic/wp-calypso#79980]
On the "Add your domains" step of the import flow, there’s a checkbox at the bottom "Import DNS records from this domain".

1. Is there a reason someone **wouldn’t** want to do this? Will 90% of people want to do this? If so, we should add verbiage at the end “(Typical answer)” or “(Recommended)” and default to checking that box. This is much like Turbo Tax does on their edge-case questions (“Do you have a 4056-16.2 Tax preferred status?” No (Typical answer) )
2. Can we add an (i) button explaining the reason why someone might or might not want this? Maybe a link to learn more and the link going to a specific-section.
3. Can we improve the wording to “Import this domain’s DNS records” OR “Import DNS records for this domain”

**Comment by ebinnion** [comment]
As of today's walkthrough, we've decided to remove this checkbox and import by default.
