### ISSUE TITLE
Site Picker: searching should support arrow keys + enter

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#8]
The flow would be something like:

1. Select switch site
2. it should focus in the search field
3. type "my"
4. list is immediately filtered down to sites containing the string "my", with the top site in the list being auto-selected and visibly highlighted (same as the hover effect we currently have)
5. I actually want the second site in the list, so I can just hit the down arrow on my keyboard, which would move the highlight/active selection down to the second site in the list (my cursor is still in the search field though, so I could keep typing if I want)
6. I can now hit enter to select the second site in the list, since that's where my highlight/selection is.

It would work very similar as github @mentions

**Comment by ryanboren** [comment]
https://test.wordpress.com/2016/01/15/keyboard-nav-in-the-site-selectors/

**Comment by beaulebens** [comment]
This should ideally work the same when you click the "New Post" button in the masterbar/toolbar. Click, type, arrows, hit enter.

**Comment by alisterscott** [comment]
Confirmed that searching immediately works, but the up/down and return keys don't, so leaving this open for now

**Comment by marekhrabe** [comment]
PR is ready to be tested ^^^
