### ISSUE TITLE
Question: Adding Styles to a Site

### ISSUE THREAD

**Issue by richdev135** [Automattic/wp-calypso#8001]
#### Steps to reproduce
1. I've created the sample Hello World site using [these instructions](http://calypso.localhost:3000/devdocs/docs/guide/hello-world.md). 
2. I'm going beyond the example to add styles to the h1 tag in the page. I'm referring to [these instructions](http://calypso.localhost:3000/devdocs/docs/coding-guidelines/css.md).
3. The instructions in step 2 say to create a style.scss file in the same folder as the .jsx file - and I've done this. 
4. I see in the output that when I edit the style.scss file that it's writing to public style and map files:

> Rendering Complete, saving .css file...
> Wrote CSS to /home/rich/dev/projects/wp-calypso/public/editor.css
> Rendering Complete, saving .css file...
> Wrote CSS to /home/rich/dev/projects/wp-calypso/public/style.css
> Rendering Complete, saving .css file...
> Wrote CSS to /home/rich/dev/projects/wp-calypso/public/style-debug.css
> Wrote Source Map to /home/rich/dev/projects/wp-calypso/public/styledebug.css.map

I don't see any reference to my new class (hello-world__title).  

I do get a Webpack bundle is valid message.
1. Code: 
   main.jsx file has:
   `<Main>
           <h1 className={titleclass}>Hello, World!</h1>
       </Main>`

The style.scss file has only 1 class declaration:
`.hello-world__title {
    background-color: blue;
    border: 1px red solid;
}`

When I look in the browser's (Chrome) dev tools, I see correct output:
`<h1 class="hello-world__title">Hello, World!</h1>`
#### What I expected

I expected that the style of my html element changed to reflect the style defined in the style.scss file.
#### What happened instead

Nothing. 

What I suspect is that maybe there is some mapping that I'm missing that describes how to "tie" the local .scss file to the Site. 

Disclaimer: I'm a SASS, React noobie, so maybe the tutorials are assuming some knowledge that I don't have yet.  :-)

Any help would be appreciated.  Thanks!
#### Browser / OS version

OS: Ubuntu Mate Release 16.04.1 LTS (Xenial Xerus) 64-bit
Browser: Version 53.0.2785.92 (64-bit)

**Comment by gwwar** [comment]
Hi @richdev135 if we add a new component scss file, we then import it in
https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/_components.scss

At the moment we don't have any helpers to auto-wire this.

cc @mtias if we should update steps
