### ISSUE TITLE
Newsletter Categories: Plan API endpoints for newsletter categories.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#80026]
Let's create a suite of API endpoints based on the needs of the site owners and the subscribers.

 - [ ] Decide on what are the API endpoints to create.

**Comment by TimBroddin** [comment]
For retrieving the newsletter categories & included/excluded categories, @yansern and I had a discussion, and we settled on this:

| Method | Endpoint | Returns | Public facing | Site owner facing |
|-|-|-|-|-|
| GET | `/wpcom/v2/sites/<siteid>/newsletter-categories` | An array containing the newsletter categories for the given site | ✅ |  ✅ | 
| GET | `/wpcom/v2/sites/<siteid>/newsletter-categories/subscription/mine` | Returns an array containing the the newsletter categories & subscription info (true / false) for the current logged in user | ✅ | ❌ |
| GET | `/wpcom/v2/sites/<siteid>/newsletter-categories/subscription/<subscription_id>` | Returns an array containing the the newsletter categories & subscription info (true / false) for the given subscription | ✅ | ❌ |

Furthermore, these endpoints would need to be changed to also include the category information:

`/wpcom/v2/read/sites/<blog_id>/subscription-details`
`/wpcom/v2/sites/<blog_id>/subscribers/individual?subscription_id=<subscription_id>`
