### ISSUE TITLE
Add "My Themes" and "All themes" to Woo Express paid plans

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#80021]
### Issue description

Slack: p1690790762473379/1690589012.365719-slack-C7U3Y3VMY

Paid users are unable to easily find their uploaded themes since we've hidden `My themes` from filters. We need to add it back along with a new `All themes` filter which will show everything.

<img src="https://user-images.githubusercontent.com/3747241/257157828-da57dd1b-593b-4f5e-ac6e-721ba1919b7f.png" width="400">

### Acceptance criteria

1. Add back `My themes` filter for paid users
2. Add a new `All themes` filter for paid users that displays all themes
3. Re-align filter and category UI to left and right aligned respectively for paid users, similar to the UI with other WPCOM plans
4. Ensure it still work as-is with free trial plan users

**Comment by chihsuan** [comment]
Hey @ilyasfoo,

> Add a new All themes filter for paid users that displays all themes

Are we going to display all themes or **all "Store"** themes (e.g. current recommended themes)?

**Comment by ilyasfoo** [comment]
Hey, @chihsuan!

> Are we going to display all themes or all "Store" themes (e.g. current recommended themes)?

Yes!
