### ISSUE TITLE
Newsletter Categories API: Create PUT endpoint to update a newsletter category.

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#80038]
This task aims to create the PUT endpoint for newsletter categories. This endpoint should be called when the user wants to change data related to the newsletter category, such as order and description.

More details about the data structure can be found here: pdDOJh-26F-p2

- [ ] Create V2 PUT endpoint
- [ ] Create automated tests

**Comment by yansern** [comment]
Based on the current UI design, there's no foreseeable way to change the ordering of the newsletter categories. We can park this for the future.
