### ISSUE TITLE
Paid newsletter: update copy for the confirmation email

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#80051]
### Details

Currently when I login to paywalled posts from the site, I get "magic" code sent.

<img width="775" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/8143faea-9a29-40bb-ac31-bbb72508cc04">

The email looks like this:

<img width="1079" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/1bf71df6-2316-4a14-91dd-aaf5ea5f7aea">

We'll need to update the copy to be more specific about signing in, continuing reading the post they just sent the code from, and update the email to use new templates.

### Checklist

- [ ]
- [ ]

**Comment by crisbusquets** [comment]
https://github.com/Automattic/wp-calypso/issues/82013 is related to this (new login email design).

**Comment by simison** [comment]
Updated with magic login link :-)
