### ISSUE TITLE
Blog Posts block: Post content not initially displayed in page editor

### ISSUE THREAD

**Issue by hanananah** [Automattic/wp-calypso#80069]
### Quick summary

When opening the editor of a page with an existing Blog Posts block, only generic/placeholder info is listed rather than showing the actual post content.

### Steps to reproduce

1. Create a new page
2. Add the Blog Posts block
3. Click `Save Draft` or `Publish`
4. Leave and reopen the page editor, or refresh the page

### What you expected to happen

The Blog Posts block should display post content:

![image](https://github.com/Automattic/wp-calypso/assets/71044033/3f57ac14-53b5-46f9-a45c-b2621d09ffd8)

### What actually happened

The Blog Post block loads generic/placeholder content:

![image](https://github.com/Automattic/wp-calypso/assets/71044033/41570c1e-497a-4f40-afee-07f75a706b8e)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

**Additional Info:**
- Behavior occurs on both Classic and Full Site Editing themes

**Workaround:**
- Making other edits to the page or directly to the Blog Posts block forces post content to load (can take a while, but making multiple edits seems to speed up the process)

![Blog Posts block bug workaround](https://github.com/Automattic/wp-calypso/assets/71044033/66975db2-d9fb-498b-9582-0a63629ccdf3)

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Simple and AT sites. Opening existing pages with the Blog Posts Block and publishing new ones, then refreshing, replicates the problem. 

#### Screenshots/Recordings

**Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/b809a80e-ec33-4e74-ae42-ab4792594bb0

**Simple**

https://github.com/Automattic/wp-calypso/assets/27249804/362b7a89-88ba-4599-a261-79ec40e7b491

📌 ACTIONS
- Assigned to Other
- CC: @Automattic/newspack

**Comment by cuemarie** [comment]
My Simple and AT Sites are running **WordPress.com Editing Toolkit version 3.73522**. Also replicated on my AT site using the 2 previous versions, `3.72793` and `3.72624`.

Jetpack also released an update today, version 12.4-beta

**Comment by cuemarie** [comment]
More user reports shared on #80254 👍 

- `6621948-zen
- 6593773-zen

HE's noted there that deactivating Gutenberg improved the performance of the Blog Posts block, indicating some sort of possible conflict.  I can replicate that deactivating Gutenberg 16.3 then opening the page allows the Blog Posts block to load properly right away.

**Comment by zdenys** [comment]
6614563-zd-a8c

**Comment by leogermani** [comment]
Confirming that this looks like a conflict with the Gutenberg plugin starting from Gutenberg 16.3

I'm looking into it

**Comment by philnick206** [comment]
Reported here: 6671412-zd-a8c

**Comment by AlexanderSky** [comment]
Another report here 7042033-zen

**Comment by devNigel** [comment]
Another report: 7181989-zd-a8c

**Comment by adekbadek** [comment]
Fixed in `newspack-blocks` in https://github.com/Automattic/newspack-blocks/pull/1553. Should be fixed in Calypso once `newspack-blocks` code is synced.

**Comment by tvolpert** [comment]
reported in 7248350-zen

**Comment by vajrasar** [comment]
@adekbadek 

> Should be fixed in Calypso once newspack-blocks code is synced.

Can you share the ETA?

**Comment by adekbadek** [comment]
@vajrasar – should be fixed with https://github.com/Automattic/wp-calypso/pull/83906

**Comment by rinazrina** [comment]
Another report: 7281352-zd-a8c

**Comment by edwinho89** [comment]
7165152-zd-a8c
