### ISSUE TITLE
Blaze app on Jetpack sites: non-working support link

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#80099]
#### Steps to reproduce

1. Start with a self-hosted site running Jetpack 12.4 (released today), and connected to WordPress.com
2. Go to Tools > Advertising; the wp-admin version will load
3. Set up a campaign
4. While your campaign is awaiting approval, access its details
5. Click on the "Contact Support" link
6. It is set to `https://yoursite.com/help/contact` instead of WordPress.com.

<img width="474" alt="Screenshot 2023-08-01 at 17 57 31" src="https://github.com/Automattic/wp-calypso/assets/426388/86f7ee63-3cc1-48f4-bd14-e76873993433">

@sbarbosa Do you think you could take a look?

Thank you!

**Comment by sbarbosa** [comment]
Thanks @jeherve ! I could reproduce it. I am working on this issue.

**Comment by sbarbosa** [comment]
I merged the fix in Calypso: https://github.com/Automattic/wp-calypso/pull/80111
After that, I deployed the new version of the Blaze Dashboard. The changes should be live now or when the cache resets for you.
