### ISSUE TITLE
Twenty Twenty Three - Critical Error on Single Posts when using PHP. 8.1

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#80104]
### Quick summary

This was reported here: https://github.com/Automattic/wp-calypso/issues/79622#issuecomment-1660547588 // 6597103-zen

User has theme **Twenty Twenty-Three** active, and reported "Whenever I click on one of my blogposts, the page shows up blank with a 'critical error on this website'." They recently upgraded and took the site AT.

⚠️ **ERROR**

`PHP Fatal error:  Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, string given in /wordpress/plugins/gutenberg/16.3.0/build/block-library/blocks/latest-posts.php:60`

---

Switching the site to PHP 7.4 resolved the user issue for now.

### Steps to reproduce

@Gustavo-Hilario can you provide steps to replicate?

### What you expected to happen

In the user's case, they expected their posts to open without issue. 

### What actually happened

Posts opened with a `critical error` instead.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
@Gustavo-Hilario - I created a new report here, but with a quick test on an AT site, I'm not seeing Critical Errors on single posts with TT3 active on a site using PHP 8.0, so we need to do a little more digging here to see what caused the PHP error you noted.  Some questions:

- Did you run a plugin conflict test?
- Did you try PHP 8.0 as well, or just move from 8.1 to 7.4?
- The user's report and your notes list their staging site as the issue - were you able to replicate the critical error on their primary site, the staging site, or both?

**Comment by Gustavo-Hilario** [comment]
Thank you for filling out this report, @cuemarie.

_* Did you run a plugin conflict test?_ Yes. Unfortunately, that didn't help. They also don't seem to have any third-party plugins on their site _(recently upgraded to Business)_. I thought the issue was with Gutenberg 16.3.0, as I noticed it was mentioned in the error message, but deactivating it and other plugins didn't help.

_* Did you try PHP 8.0 as well, or just move from 8.1 to 7.4?_ Yes. The Fatal Error arises when PHP 8.0 is activated as well.

_* The user's report and your notes list their staging site as the issue - were you able to replicate the critical error on their primary site, the staging site, or both?_ Apologies for that. The issue was reproduced and fixed (temporarily) for their main live site intjreadsbooks.com. If I recollect correctly, I could also replicate this on the staging site.

---

Here are the steps to reproduce the issue:

* Access BRC for user's site and change the PHP version back to 8.0 or 8.1.
* Access their home page
* Try to access any of their blog posts. You should see the Fatal Error message there.

_this comment was updated to redact user-specific information_

**Comment by cuemarie** [comment]
Thanks @Gustavo-Hilario ! Some notes from further testing:

### User's Site

I can confirm the user's staging site replicates the issue on PHP 8.0. Single Posts on their site result in a critical error, and deactivating all their plugins does not resolve.  PHP logs show:

```
[02-Aug-2023 19:25:58 UTC] PHP Fatal error:  Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, string given in /wordpress/plugins/gutenberg/16.3.0/build/block-library/blocks/latest-posts.php:60
Stack trace:
#0 /wordpress/plugins/gutenberg/16.3.0/build/block-library/blocks/latest-posts.php(60): array_column('', 'id')
#1 /wordpress/core/6.2.2/wp-includes/class-wp-block.php(258): gutenberg_render_block_core_latest_posts(Array, '', Object(WP_Block))
#2 /wordpress/core/6.2.2/wp-includes/blocks.php(1072): WP_Block->render()
#3 /wordpress/core/6.2.2/wp-includes/blocks.php(1110): render_block(Array)
#4 /wordpress/plugins/gutenberg/16.3.0/build/block-library/blocks/template-part.php(150): do_blocks('<!-- wp:latest-...')
#5 /wordpress/core/6.2.2/wp-includes/class-wp-block.php(258): gutenberg_render_block_core_template_part(Array, '', Object(WP_Block))
#6 /wordpress/core/6.2.2/wp-includes/class-wp-block.php(244): WP_Block->render()
#7 /wordpress/core/6.2.2/wp-includes/blocks.php(1072): WP_Block->render()
#8 /wordpress/core/6.2.2/wp-includes/blocks.php(1110): render_block(Array)
#9 /wordpress/core/6.2.2/wp-includes/block-template.php(242): do_blocks('<!-- wp:templat...')
#10 /wordpress/core/6.2.2/wp-includes/template-canvas.php(12): get_the_block_template_html()
#11 /wordpress/core/6.2.2/wp-includes/template-loader.php(106): include('/wordpress/core...')
#12 /wordpress/core/6.2.2/wp-blog-header.php(19): require_once('/wordpress/core...')
#13 /wordpress/core/6.2.2/index.php(17): require('/wordpress/core...')
#14 {main}
  thrown in /wordpress/plugins/gutenberg/16.3.0/build/block-library/blocks/latest-posts.php on line 60
```

### User's Activity Log

I'm curious about this Activity Log item in their staging site's history:
![Markup on 2023-08-02 at 12:30:43](https://github.com/Automattic/wp-calypso/assets/27249804/02f38620-fe9f-495b-9f63-99b7f11f95b4)

Their production site transferred to AT on 2023-07-31, while they were using the TT3 theme. 

![Markup on 2023-08-02 at 12:34:16](https://github.com/Automattic/wp-calypso/assets/27249804/4a51b5b5-a3ec-49c0-97f7-7a4a21ccf69b)

Since this isn't replicating on my existing AT sites with theme TT3, I'm wondering if something went wrong with the theme during the transfer to AT. Next I'll try to create a site on TT3, then take it AT, and see if I can reproduce the error that way.

### Attempt to replicate

I created a brand new site today, switched to the theme the user had tried (shown in their activity log above), switched back, then upgraded to Business to transfer the site AT.  I'm still unable to reproduce this PHP error.  I created a staging site, and my staging site's Activity Log shows the same theme activation record, so I don't believe that's relevant to this issue:

![Markup on 2023-08-02 at 12:46:03](https://github.com/Automattic/wp-calypso/assets/27249804/62d2b792-6c9e-44b3-af1b-306f1cc2c760)

Lastly, I reverted the site, made some customizations to the Blog Home template (as the user has customizations on this template as well, but not the Single Posts template), and AT'd again.  Once again, there was no PHP conflict after transferring to AT.

https://github.com/Automattic/wp-calypso/assets/27249804/a7c06c33-f930-4df1-8b50-565572bfbdba

---

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closing as not reproducible

📌 Message to Author
- @Gustavo-Hilario , I think the next step to take here is to report this internally on 9F6qB-p2 (or on p9F6qB-a0S-p2 ) where the user's specific details can be shared in full, and then AT folks can try to help spot what happened that's leading to this error on their site only.
- Please reopen this issue if troubleshooting internally helps uncover a bug!
