### ISSUE TITLE
Update Learn More Link in Bulk Domain Transfer Tool

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#80127]
### Quick summary

The Learn More link in the bulk transfer tool leads to an incorrect jump link. The doc went through several rounds of edits by several people. I don't expect any further changes to the jump link.
<img width="656" alt="Screenshot 2023-08-02 at 3 01 11 pm" src="https://github.com/Automattic/wp-calypso/assets/30727666/081e02a5-754c-45d2-ad29-487227a0c742">

### Steps to reproduce

1. Navigate to https://wordpress.com/setup/domain-transfer/domains
2. Click the i icon next to Authorization code
3. Click learn more

### What you expected to happen

I expected to arrive at https://wordpress.com/support/domains/incoming-domain-transfer/#step-2-unlock-your-domain-and-obtain-your-auth-code

### What actually happened

I arrived at https://wordpress.com/support/domains/incoming-domain-transfer/#step-2-obtain-your-domain-transfer-authorization-code

As a workaround, I added this to the HTML of the doc:

```
<div id="step-2-obtain-your-domain-transfer-authorization-code">&nbsp;</div>
```

This will ensure the old jump link continues to work, but will be good to update the original link.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – n/a
Tested on Atomic – n/a
Replicable outside of Dotcom – n/a

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/6549265/dd14d330-4370-4c0a-a86a-b201f370ff64



📌 ACTIONS
- maintain Normal priority.
- assign to Prioritize & Assign column as this is for the high-priority and high-visibility Google Domains takeover project.
- add to the Google Domains Takeover project board and set to v2.
