### ISSUE TITLE
Reader: Add tooltips to action buttons

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#80122]
see pe7F0s-15t-p2
We should add tooltips to the reader icon buttons for accessibility

![Image](https://github.com/Automattic/wp-calypso/assets/22446385/8aaa3bef-ee3a-404f-9a02-d348e5f76873)

**Comment by simison** [comment]
Native tooltips are nice step, but I'd also consider using tooltip component, similar to Facebook UIs which rely heavily on symbols:


https://github.com/Automattic/wp-calypso/assets/87168/82cef91a-e919-4048-8bc3-560dffe19a21

It just makes things super clear.
