### ISSUE TITLE
Unexpected redirection to about:srcdoc when visiting developer.wordpress.com/wp-admin/widgets.php

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#80139]
### Quick summary

I'm unable to remove the Twitter widget from https://developer.wordpress.com/wp-admin/widgets.php

### Steps to reproduce

1. Visit https://developer.wordpress.com/wp-admin/widgets.php
2. Wait for the page to load a bit.

### What you expected to happen

I'd be able to edit widgets.

### What actually happened

I'm redirected to `about:srcdoc`.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on https://developer.wordpress.com/wp-admin/widgets.php – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described. `/wp-admin/widgets.php` quickly redirects to the Invalid URL page.
- Customizer > Widgets can load, but the widgets for this site don't load in the customizer. 

📌 ACTIONS
- Assigned to @Automattic/yolo 

📌 Message to Author
- @danielbachhuber it looks like installing the [Classic Widget plugin](https://wordpress.com/plugins/classic-widgets) might help. (I didn't want to add anything to the site myself). That may allow you to access `wp-admin/widgets` and find a widget causing the issue.
Example: p1636112269155000-slack-C03TY6J1A

**Comment by danielbachhuber** [comment]
When we fix this, we should add a Subscribe widget to the sidebar too.

**Comment by danielbachhuber** [comment]
@jeroenpf We can wontfix this one. The widget was manually removed (p1693487920226209/1693467057.457069-slack-C025Q5RK2), and I think this is an old enough edge case that it's not worth investing time into.

**Comment by jeroenpf** [comment]
This issue was caused by some old code in the theme that was used. For more details please check D120682-code

I've made adjustments to the theme to prevent the issue.

**Comment by danielbachhuber** [comment]
@jeroenpf Nice find!

**Comment by jeroenpf** [comment]
As mentioned earlier, we can manually edit widgets via wp cli and we will not spend more time on fixing this.
