### ISSUE TITLE
Custom Fonts do not show in the Site Editor on WP.com

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#80136]
### Quick summary

With a WordPress.com site, using the [Custom Fonts plugin](https://wordpress.com/plugins/custom-fonts), the installed plugins do not appear in the Font family options in the Site Editor.

I tested a self-hosted environment with Jurassic Ninja and the plugin worked as expected.

It is a third-party plugin, but the fonts seems to be not working because of how we call in Google Fonts, I presume. 

### Steps to reproduce

1. Use a WP.com AT site and an FSE theme.
2. Install Custom Fonts https://wordpress.com/plugins/custom-fonts
3. Install any font. In the example, I use Allura.
4. The font does not appear in the Site Editor

AT site, fonts installed:
![T7YC15yfkXk9s58eswFGDA8ard6gWMEK0bAnlBI0.jpg](https://github.com/Automattic/wp-calypso/assets/84539773/c8c58198-ecde-4434-9e32-99e31116eb8c)

Do not show up in Site Editor:
![pWiH3d8x3aRg4TMXhBbnXKsfvQECxPVBwCIKJ8i0.jpg](https://github.com/Automattic/wp-calypso/assets/84539773/ae6c32a1-5805-4f08-8a17-e09345c1a114)

5. Use Jurassic Ninja, created self hosted site.
6. Theme is the same, Course.
7. Install plugin and the same font.
8. Custom Fonts show up in the Site Editor

![DtL41fxUtI8m49uFHCXovtI2LX4RbwoUMtZB7SS9.jpg](https://github.com/Automattic/wp-calypso/assets/84539773/b4b1b3e7-5818-4891-b899-d4a4e4f79f21)

### What you expected to happen

I would expect the Custom Fonts to show up among the options.

### What actually happened

Didn't show up. 

### Impact

All

### Available workarounds?

No but the platform is still usable.

The [Use Any Fonts](https://wordpress.com/plugins/use-any-font) plugin appears to work, but it is using CSS classes, so slightly less user-friendly. 

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

All FSE themes

**Comment by csabarakasz** [comment]
6512695-zd-woothemes 

Suggesting Use Any Font

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Reproduced on an Atomic site as described, tested with TT3. The same steps on a Self-Hosted site result in the font appearing anywhere a font family can be set, including Global Styles. 

📌 ACTIONS
- Assigned to Other

- @csabarakasz , would you file a "Developer Outreach" request on 9F6qB-p2 regarding this issue? That way, @Automattic/reactor can take a look and see if we need to work with the plugin developer on a fix for this.

**Comment by hideandgeek404** [comment]
I did some comprehensive testing on this and I can tell you why the issue exists. It's basically because the plugin cannot write to the `theme.json` file in a symlinked theme, e.g. TT3. However, if you remove the symlink or create a child theme then this will work as expected.

**Comment by csabarakasz** [comment]
Thank you, @hideandgeek404, for looking into this. With your findings, do you mean that I do not need to create a developer outreach, but if the user wants to use a block theme with the Custom Fonts plugin, we will need to help them unlink it from the symlinked theme? 

I did some research in Site Profiles, and 496 sites have the Custom Fonts plugin installed and using a symlinked theme. 

![ETKfAW8UO3RLNpHKv0W1YYzLk9mRuq3XwOQ2COnc.jpg](https://github.com/Automattic/wp-calypso/assets/84539773/b82eb2ab-0321-43ea-bd2a-38e23e1f91d2)

**Comment by hideandgeek404** [comment]
Essentially, that's correct, yes. Or, even better, guide them to use a child theme. This means that the symlinked parent theme can continue to be updated (which would not happen if you removed the symlink) but the theme.json file then becomes writeable.

**Comment by cuemarie** [comment]
Thanks so much for your help, @hideandgeek404 ! I think with your explanation in mind, we can close this as by design, since things on our side are working as expected.

📌 ACTIONS
- Closed as by design
- Users who encounter this issue should use a child theme, so that the Custom Fonts plugin can write to the theme.json file.
