### ISSUE TITLE
ImageEditor: resizing window makes cropper incorrect

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#8017]
Comment on post requesting feedback:
> If you resize the browser window the selection box gets offset, making it look like I’ve selected beyond the bounds of the image. Touching the selection box at all resets it to whatever was selected before the resize, and clicking Done saves the actual selection, not what appears in the window.

**Comment by gwwar** [comment]
Gif of this in action:
![wp-calypso-image-editor-2](https://cloud.githubusercontent.com/assets/1270189/18406884/7e877cf2-76b8-11e6-84c0-a8749ed366b7.gif)

**Comment by obenland** [comment]
Duplicate of #7983.
