### ISSUE TITLE
ImageEditor: disable invalid image types

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#8018]
Comment on post requesting feedback.

> Also, I had a .gif in the media library, so why not trying to see what happens, in this case would be good some visual reference to the user that editing .gif files is not allowed, maybe squaring the animation on red or making the files non-selectable for editing, as users may be confused on why cannot they edit animations. Also, the second time I try, it shows some other image instead of a black screen.

**Comment by rralian** [comment]
Hmm... I'm surprised we don't handle gifs at all. At first I was thinking we probably just don't handle animated gifs, but then I tried a few non-animated gifts and it doesn't work for me either.

**Comment by rralian** [comment]
Now it's consistently working fine for me to edit gifs in wpcalypso. I wonder if this was fixed in some other image-editing commits. In any case, I can no longer break it.

I think the main issue now is to either disable image editing for animated gifs or explain that only the first frame will be copied. I don't believe our current approach to image-editing can easily handle editing animated gifs.

**Comment by nb** [comment]
@rralian can we close this one?

**Comment by rralian** [comment]
sure, we can close this
