### ISSUE TITLE
Reader: Link up WORDPRESS.COM in the full post more block

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#8023]
@fraying would like to link up the WordPress.com text in the more block in the new full post view to wordpress.com. 

Should this load the following stream fresh and drop any scroll position the user had? IE, if I scrolled down to page 11 of the following stream and clicked into a full post, then clicked on "wordpress.com" in the related post header, would going back to the top of the following stream be expected? 

Or should the link take you somewhere else, perhaps Discover?

**Comment by fraying** [comment]
Top of Wordpress. Any place else you see a link to Wordpress.com would do the same.

**Comment by fraying** [comment]
Could we get this link added, so we can use it and see how it feels?

**Comment by bluefuton** [comment]
Think it's a good idea to link this up, but have a couple of questions:
- as @blowery says, a link to `/` will just take a logged in user back to their Following stream. Might be odd? Should they go to a wp.com about page instead, or Discover/Recommendations?
- should we open the link in a new tab to avoid losing user scroll position?

**Comment by fraying** [comment]
Top of WordPress is fine. That's what any other link to wordpress.com would do.

No, should not be a new window. No other link does that.

Can we just try it? It's just a link. If it's weird, we'll remove it.
