### ISSUE TITLE
Image Editor: Move the Cancel Button so we don't accidentally delete media

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8024]
When we cancel out of the image editor, our mouse position will then hover over the delete button in the media details page. Let's move the position of the cancel button so we don't accidentally delete media by double clicking. 

![screen-shot-2016-09-09-at-1-47-02-pm](https://cloud.githubusercontent.com/assets/1270189/18406854/ea084d90-76b7-11e6-8341-a75411692974.png)
![screen-shot-2016-09-09-at-1-47-10-pm](https://cloud.githubusercontent.com/assets/1270189/18406855/eb59223c-76b7-11e6-991b-9330a6cfaec4.png)

**Comment by retrofox** [comment]
where it should be moved?

**Comment by gwwar** [comment]
> where it should be moved?

Let's move the image editor cancel button to the left of the `Reset` button. 

cc @adambbecker

**Comment by gwwar** [comment]
Fixed by @rralian in #8043
