### ISSUE TITLE
Advanced SEO: Clarify copy/text explaining custom title format edit

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#8025]
> the wording for the Title Format Tool could be improved to indicate this also changes what is shown in the browser tab title etc.

this and other things could use a designer/copy pass to update the wording and make sure it's clear to our users

from @alisterscott

**Comment by folletto** [comment]
Could you specify where to check the page (and maybe a screenshot for future reference) so it's possible to review and give advice easily? :)

**Comment by alisterscott** [comment]
Sorry for not including this @folletto. You will need a site with a business plan for this to appear, and use https://wpcalypso.wordpress.com and navigate to Settings->SEO where you should see the new "Page Title Structure" component:

![screen shot 2016-09-13 at 10 21 53 am](https://cloud.githubusercontent.com/assets/128826/18457430/152de354-799c-11e6-8d3f-e6b874d299ff.png)

**Comment by dmsnell** [comment]
> Could you specify where to check the page (and maybe a screenshot for future reference) so it's possible to review and give advice easily? :)

Sorry @folletto - I usually try and be diligent about this but was simply rushed at the time and wanted to make sure primarily that the issue was tracked and not left behind.

Thanks @alisterscott for helping me out here!

**Comment by folletto** [comment]
It's cool. :)

So are we referring about the text just above?

> You can set the structure of page titles for different sections of your site. Doing this will change the way your site title is displayed in search engine results, and when shared on social media sites.

Or the whole SEO page?

**Comment by drw158** [comment]
This is just the page title tool text I believe.

Trying to make it a bit more succinct...

>You can set the structure of page titles for different sections of your site. Doing this will change the way your site title is displayed in search engines, social media, and browser tabs.

**Comment by dmsnell** [comment]
I'm closing this @alisterscott. the content that @drw158 suggested above is already in **master**. if you think there are still rough edges here please reopen and let us know why/what

**Comment by drw158** [comment]
Hm I pulled the latest master, and I'm not seeing the new copy.

**Comment by alisterscott** [comment]
@drw158 I'm seeing the new copy in Staging/Production, but the image is missing:

![screen shot 2016-10-07 at 10 43 10 am](https://cloud.githubusercontent.com/assets/128826/19175548/ee90e862-8c7a-11e6-912c-c17c2bca556b.png)

I'll investigate that now

**Comment by alisterscott** [comment]
^ That was an issue with a docker deploy for _all_ images, not related to this change.
