### ISSUE TITLE
Blog Posts block: the block doesn't properly render when Gutenberg is active

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#80254]
### Steps to reproduce

1. Add the Blog posts several times on an already existing page
2. Publish the changes and refresh the editor.
3. The block might look like this

(Alternatively, you may need to place the block on the homepage)

### What you expected to happen

To see the block content properly in the editor.

### What actually happened

![lNRthJ.png](https://github.com/Automattic/wp-calypso/assets/6737345/39ae0490-2b5d-49ef-89ef-d707b393768f)

This is how it was on the user's site 

![5VIwR2.png](https://github.com/Automattic/wp-calypso/assets/6737345/7e214004-f6ea-460d-bfbb-87a1a8402451)

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Turning off the Gutenberg plugin helped.

Theme used: Varia/Hever
Browser: Chrome
Site: AT

Ticket: 6621948-zen

**Comment by druesome** [comment]
Reported in 6593773-zen as well

Fwiw, the block renders on the live site, but this issue makes it difficult for the user to customize it.

**Comment by cuemarie** [comment]
I'd say this looks like a duplicate report of this: https://github.com/Automattic/wp-calypso/issues/80069

---

I'll report the user interactions and the details about multiple blog posts blocks over in the comments on that one.
