### ISSUE TITLE
Live Preview: Show a smart/better transition modal when users land in the Live Preview Site Editor

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#80264]
# Description

Updated 2023-Dec-13

We want to show a transition modal as users are taken from the Theme Showcase to the Site Editor.    The current modal was a temporary solution and now we need real design thinking for a better modal.  

See Improvements to the Live Preview experience – Dotcom Marvel https://marvelousp2.wordpress.com/2023/12/07/improvements-to-the-live-preview-experience/

-----------

**CURRENT MODAL**

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/5eadd8db-1db0-4214-bae5-e7b3be1c0376)

**NEW MODAL** by @matt-west 

Figma: [RcxiuWYjZGkFRdlWL7L02m-fi-1900_11111](https://href.li/?https://www.figma.com/file/RcxiuWYjZGkFRdlWL7L02m/?node-id=1900-11111)

https://private-user-images.githubusercontent.com/417538/288869978-bad0f5bb-980a-4660-87b7-6219867941a0.mov

Project Thread: pbxlJb-3Uv-p2
Slack convo: p1691099412345219-slack-CRWCHQGUB

###  Concepts/tips/info that the modal should convey
* Somehow highlight Styles
* Explain that user is entering the Site Editor
* Depending on the theme you'll see your content and perhaps also the new theme content
* Lucas had ideas for an explanatory video showing some SE interaction
* What else?

# Acceptance Criteria
- [ ] Users can see the transition modal overlaid on the SE Live Preview before/during the Live Preview flow. 
- [ ] Approved by designer

# Dev Tasks
- [ ]  Implement the modal

# Testing 
Get Lucas and Autumn or Ian to test. 

TBD

# Related
- https://github.com/Automattic/wp-calypso/issues/80261

**Comment by autumnfjeld** [comment]
FYI: @lucasmendes-design  when you have a chance to work on this. :) 

Ideas on the content of the modal:
* Introduce the Site Editor and the Preview mode.
* Highlight style customization.
* How to return to the Theme Showcase (either via the Back button or the WP logo).

Do you think we need to run this idea by Pablo?

**Comment by autumnfjeld** [comment]
For reference:  design coming as discussed here  pbxlJb-3Uv-p2#comment-2869.  The "smart modal" .  

Here is an initial mockup (not final design): https://video.wordpress.com/v/AqIq7TsC

**Comment by autumnfjeld** [comment]
A good first task for @matt-west ? 😄 
p1700716328135919-slack-C048CUFRGFQ

**Comment by matt-west** [comment]
Happy to look at this once I go live in design.

**Comment by matt-west** [comment]
I've created a proposal that iterates on @lucasmendes-design’s previous idea of showing an animation to help guide the user. Instead I decided to focus on showing styles.

https://github.com/Automattic/wp-calypso/assets/417538/bad0f5bb-980a-4660-87b7-6219867941a0

I think we can improve on this in the future with a proper tour, but the modal update feels like a good first step.

I’ve removed the `Do not show this again` checkbox from the previous modal. Given how intrusive the modal is, I think we should only show it the first time a user previews a theme. After that, we should display a banner in the editor sidebar to show that the user is previewing a theme.

![image](https://github.com/Automattic/wp-calypso/assets/417538/c48b5450-9d15-4c8a-a905-e3b30568b17e)

This banner should be combined with the banner that appears when a Premium theme/styles are enabled which will require a plan upgrade.

![image](https://github.com/Automattic/wp-calypso/assets/417538/d012a611-4376-4439-b205-8a3b8ca6b63e)

Let me know your thoughts!

Design: RcxiuWYjZGkFRdlWL7L02m-fi-1900_11111
Feedback: pekYwv-3uK-p2

**Comment by lucasmendes-design** [comment]
> Given how intrusive the modal is, I think we should only show it the first time a user previews a theme.

I believe it's fine to remove the checkbox for now. Since the proposed modal shows simple information, and one time should be enough to understand the general concept you're presenting. 

However, If we add a more complex one in the future, like the mini product tour or something else. I believe we need to introduce this checkbox again. It's difficult to assimilate everything at once.

**Comment by autumnfjeld** [comment]
Fantastic @matt-west !!   We'll put this task in our up next.   We're prioritizing getting the Call for Testing done for pbxlJb-4QS-p2 and after the CfT is published we can start on this work.  Thank you! :)

**Comment by fushar** [comment]
Update: we have implemented the new modal in this PR:

- https://github.com/Automattic/jetpack/pull/34935

<img width="797" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/421ebc68-158d-4291-a699-489348634ca8">

The next thing in the new design is the banner in the Site Editor sidebar as follows:

<img width="256" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/16e0a71e-c32d-43f9-b01b-587debf68a58">

In light of the new dotcom priorities, we've decided to punt this. Another rationale for deprioritization is that the Editor already says that we're `Previewing a theme`:

<img width="352" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/4bed11c3-4df4-4d91-9e08-3bd1f63a480a">

Finally, the remaining thing is the unification with the Global Styles, tracked here:

- https://github.com/Automattic/wp-calypso/issues/85538

With this, I'm closing this issue. Thanks @matt-west for the excellent design.
