### ISSUE TITLE
Domains step: Back button doesn't take me back

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#80260]
When entering the domain flow via general settings, if I click back, I end up on the domains management screen instead of going back to where I came from.

![Image](https://github.com/Automattic/wp-calypso/assets/811776/03c4de74-a4f9-499f-88cf-74c19cae79cd)
![Image](https://github.com/Automattic/wp-calypso/assets/811776/6321f677-954b-4e45-b188-84d11ab40a34)
![Image](https://github.com/Automattic/wp-calypso/assets/811776/41355648-d325-487e-81a2-9f6f2b890a02)

- [ ] Fix the back button

**Comment by lsl** [comment]
Similar issue coming from login/domains landing pages

https://github.com/Automattic/wp-calypso/assets/811776/75e1398f-0a53-4505-8c13-2b0eb0bc6264

p1698265226460189-slack-CKZHG0QCR

**Comment by allilevine** [comment]
@lsl @DustyReagan Does this still need additional fixes?

**Comment by lsl** [comment]
Yes, https://wordpress.com/domains/add/test325235.blog's back button sends you to the domains management page regardless of where you've come from. (e.g. site settings)

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described. Only see that link on the Settings page on Simple, so that's the only environment I tested:

https://github.com/Automattic/wp-calypso/assets/27249804/75d61fad-4e5e-43e1-b1b5-ec2aa8065713

📌 ACTIONS
- Triaged

**Comment by gius80** [comment]
I created I PR that should fix the redirect for all the domain flows started from the site settings page.

The landing page is not on Calypso but it's a Landpack page in WordPress.com (I'll create a separate task).

**Comment by gius80** [comment]
> The landing page is not on Calypso but it's a Landpack page in WordPress.com (I'll create a separate task).
I checked again and the regular flow doesn't have the back button anymore, so I think we are good :)
