### ISSUE TITLE
Advanced SEO: Create disabled state for draft-js editor

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#8026]
The draft-js has no disabled state. Even when it's "disabled" one can still type in the editor. We should provide a grayed-out un-editable state.

cc: @rachelmcr

**Comment by roundhill** [comment]
Note: I added this functionality in https://github.com/Automattic/wp-calypso/pull/7980, but we might not merge that one. We could at least pull out the disabled state work from it for this issue.

**Comment by dmsnell** [comment]
Nice @roundhill - it looks like we should gray out the buttons as well. I'll see what I can pull from #7980

**Comment by drw158** [comment]
Whoops I didn't see this issue. Look at https://github.com/Automattic/wp-calypso/issues/7968#issuecomment-250769887 to see my suggestion for the design.
