### ISSUE TITLE
Plugin Details: Related Plugins component

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#80288]
Create the Related Plugins component according the design below:

- [ ] Display the title 
- [ ] Display the related plugins from #80287
- [ ] Add a `See All` link to redirect to the related plugins page (added at #80289)

<img width="592" alt="Screen Shot 2022-08-04 at 09 30 03" src="https://user-images.githubusercontent.com/5039531/182859430-8927ba60-2ac2-424d-b284-4d6b3e0fc697.png">

Related to #63717

**Comment by cpapazoglou** [comment]
We 've spent 2 days on this initially, we will need 1 more day to finalize the PR and merge it. 
This PR ALSO adds the component to the plugin details page, and will resolve https://github.com/Automattic/wp-calypso/issues/80290

Updated points to 1
