### ISSUE TITLE
Marketplace: Related Plugins page

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#80289]
Create a new page to display the related plugins from a given plugin.

- [x] Create a new route. Ex: `/plugins/:plugin_slug/related/:site`
- [x] Display the related plugins in this new route. The layout can be similar to the bottom part of the Category page.
- [x] Display the related plugins from #80287

![CleanShot 2023-08-07 at 17 19 45@2x](https://github.com/Automattic/wp-calypso/assets/5039531/93a8914c-f4f4-46bd-ae98-21e9fe52ea65)

Related to #63717

**Comment by WBerredo** [comment]
Moving this item back to Backlog to be worked on the needed changes.

**Comment by gcsecsey** [comment]
Backend changes are deployed with r275778-wpcom
