### ISSUE TITLE
Posts: Post status toolbar is not displayed when you only have drafts on your site

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#803]
Steps to reproduce:
1. Create a new site, with only one published post.
2. It will appear under `/posts`
3. Edit that post, and revert it to a draft. Save your changes.
4. Reload `/posts`
5. I can't get back to my draft, the post status toolbar isn't there anymore:

![screen shot 2015-11-25 at 9 18 21 pm](https://cloud.githubusercontent.com/assets/426388/11408537/2063fa10-93ba-11e5-945f-55e1d19c6089.png)

The only way to get back to my draft is to enter the editor, and click on "Drafts" at the top of the sidebar.

I think it'd be nice if the post status toolbar was displayed in `/posts`, even when no posts are published yet.

Suggested in 2434138-t

**Comment by alisterscott** [comment]
This is no longer an issue:

![posts revert draft](https://user-images.githubusercontent.com/128826/34231936-c17b5baa-e629-11e7-94d0-fa0cd082e6e3.gif)
