### ISSUE TITLE
Remove "Renew plan" option showing in the /sites

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#80307]
When a migration trial plan is expired, we shouldn't show the "Renew plan" link to them in `/sites`

![Image](https://github.com/Automattic/wp-calypso/assets/4074459/e605b0c9-5ebd-4936-85cd-6e15b6b5cab6)

**Comment by bogiii** [comment]
What should we place there instead of "Renew plan"?

Could it be "Upgrade to Business"? @javierarce, what do you think?

**Comment by bogiii** [comment]
We decided to follow the Woo trial and removed the "Renew plan" link.

cc @javierarce
