### ISSUE TITLE
i18n: Context for Portuguese Translation of "All"

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-calypso#8031]
For the Brazilian Portuguese translation of "All" we keep getting two translations "Todos" and "Tudo". It looks to me that we have a problem with contexts here where one translation fits in one place and one in the other place.

These are the places we have a translation of "All":
- https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/themes/themes-search-card/index.jsx#L116
- https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/themes/themes-magic-search-card/index.jsx#L73
- https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/filter-bar.jsx#L80

@fabianapsimoes Could you review this and tell us where we need which translation so that I can figure out the right contexts? Thanks!

**Comment by fabianapsimoes** [comment]
I think all of these would be fine as "Todos".

**Comment by akirk** [comment]
Thanks, can you think of a case where Tudo should be used? Or some other clue to for me to understand why people keep suggesting "Tudo"? Thank you!

**Comment by fabianapsimoes** [comment]
"Tudo" would be more like "everything". So, for example, Select All could be translated as "Selecionar tudo". 

In addition to that, "tudo" is a noun, while "todo(s)" is an adjective / adverb. So "todo" always refers to something else, such as "Todos os temas" (All the themes). You can't do the same with "tudo".

**Comment by akirk** [comment]
Thanks that helps a lot!
