### ISSUE TITLE
Pricing Grid: Plans Page selected plan header background

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#80348]
### Quick summary

<img width="1203" alt="Screenshot 2023-08-08 at 5 33 47 PM" src="https://github.com/Automattic/wp-calypso/assets/1126811/30915da7-7f13-47bf-83d9-c6408cc61967">

The top of the selected plan card seems to have a white background and then the rest of the card seems to have a gray background below. This feels off.

Mentioned in Slack as well: p1691534140640839-slack-CFFF01Q4V 

### Steps to reproduce

1. Go to wordpress.com/plans/$site
2. Ensure you have a plan already

### What you expected to happen

No gray background probably

### What actually happened

See above

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – unsure, see notes and screenshots below.
Tested on Atomic – ditto
Replicable outside of Dotcom – not applicable

📌 NOTES
I opened the `/plans` endpoint as a user with the WordPress.com Premium plan.

Visually, I did not notice any difference in the background color, but after poking around in the DOM inspector I noticed that there appear to be very slight difference in the background color.

Current plan header -> rgb(255, 255, 255)
Current plan detail card background -> rgba(0, 0, 0, 0)

See screenshots below.

📌 FINDINGS/SCREENSHOTS/VIDEO

![image](https://github.com/Automattic/wp-calypso/assets/6549265/1fffaab9-ca1d-4684-8f30-ad406221ad81)

![image](https://github.com/Automattic/wp-calypso/assets/6549265/18012145-addd-41bf-9344-21059a211c1f)

📌 LOGS
n/a

📌 ACTIONS
- set to Low priority.
- assign to MarTech column.
