### ISSUE TITLE
YouTube throwing ERR_BLOCKED_BY_RESPONSE when trying to visit site from the YouTube block preview

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#80376]
### Quick summary

Clicking on the YouTube link from the YouTube block video player doesn't load the video on Youtube. Instead, users are getting `ERR_BLOCKED_BY_RESPONSE` from YouTube.

https://github.com/Automattic/wp-calypso/assets/5733224/11a4a1ee-0d9f-488c-aec0-74ab49d8596a

### **Workaround**
- User can use the [embed code from YouTube video](https://support.google.com/youtube/answer/171780?hl=en) and use Custom HTML block to show the iframe. 

### Steps to reproduce

1. Open a page in edit mode.
2. Add a YouTube block.
3. Add a YouTube video URL in the URL field of the block(For example, https://youtu.be/_kQhbkPnlQM)
4. Save the change and open the page in the preview. 
5. Try clicking on the YouTube text at the bottom right corner of the YouTube player. ![D5zjiI.png](https://github.com/Automattic/wp-calypso/assets/5733224/70dfae61-edf2-4fda-9ace-87edd2f31276)
6. You will see the following screen.
![Screenshot 2023-08-09 at 17 37 16](https://github.com/Automattic/wp-calypso/assets/5733224/9c755186-bfd2-4b95-9dea-8a4723b1f6b5)

### What you expected to happen

The user should be redirected to the youtube.com site, and the video should be playing there.

### What actually happened

youtube.com throws an error message, `ERR_BLOCKED_BY_RESPONSE`.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I have tried reproducing this error on a self-hosted site with the latest WordPress version(6.3). I couldn't reproduce it there.

**Comment by dev-sabbir** [comment]
6640133-zd-a8c

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm able to open the Youtube link following the steps above on both Simple and Atomic sites, using both classic and FSE themes. 
- Browser: Firefox 116.0.2 with "Standard" browser privacy/securty option selected

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/ce9fe1d8-9dd0-4723-bdd8-ae10a1c88e9f

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- Hey @dev-sabbir ! I wasn't able to reproduce this same issue. What browser & version are you using when you're able to reproduce this?

**Comment by dev-sabbir** [comment]
@cuemarie, I am unable to reproduce the issue on Firefox as well. 

Previously, I was testing from Google Chrome Version 115.0.5790.114 (Official Build) (x86_64) installed on a Mac.

**Comment by cuemarie** [comment]
Thanks @dev-sabbir ! I'm still seeing fine results when testing Chrome, only about a week ahead of you in releases.  Whether using a logged out standard browser as well as an incognito browser, Youtube opened without issue.

- Google Chrome Version 115.0.5790.170 (Official Build) (x86_64)

https://github.com/Automattic/wp-calypso/assets/27249804/2cad9685-7d62-4b50-a60e-71cc768affc8

---

I can only replicate the block if I open chrome://settings/cookies and opt to **Block all cookies**.  Can you check if your Chrome settings match this?

**Comment by dev-sabbir** [comment]
Hi @cuemarie,

Thanks for testing this. After updating my browser, I am unable to replicate this issue either. It seems to be an issue with that specific version of the browser. 

I think we can close this issue now. Right?

**Comment by cuemarie** [comment]
Ah, looks like this was actually also a duplicate! 

- https://github.com/Automattic/jetpack/issues/33593
