### ISSUE TITLE
Reader: Inline images get block'ed & centered in full page view

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#8039]
#### Steps to reproduce
1. Starting at URL: wordpress.com/post/{siteid}
2. Create a post with a couple small inline images
3. Publish
4. View post in Reader

#### What I expected

That inline images would stay inline

#### What happened instead

Inline images are put on their own line and centered

#### Screenshot / Video

https://cloudup.com/cmTLJ-5ioYG

#### Example post

https://wordpress.com/read/blogs/93107746/posts/83

**Comment by blowery** [comment]
😢  🌹

thanks @meremagee! taking a look.

**Comment by fraying** [comment]
Nice catch, @meremagee. Thank you.
