### ISSUE TITLE
Reader: captions are missing in the "View Gallery" image carousel

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#804]
In the single-post view, captions are displayed on galleries by default:

![screen shot 2015-11-25 at wed nov 25 3 23 14 pm](https://cloud.githubusercontent.com/assets/1119271/11408646/7ed948b6-9388-11e5-83e4-d2edac38f646.png)
<sup>Seen at https://wordpress.com/read/post/feed/40471243/873231388 using Firefox 42.0 on Mac OS X 10.10.5</sup>

The “View Gallery” image carousel doesn’t display captions at all:

![screen shot 2015-11-25 at wed nov 25 3 25 11 pm](https://cloud.githubusercontent.com/assets/1119271/11408685/bded4778-9388-11e5-95e5-ab7179a2dc40.png)
<sup>Seen at https://wordpress.com/ using Firefox 42.0 on Mac OS X 10.10.5</sup>

From @shaunandrews 

<blockquote>This is a super basic implementation of the galleries. I threw together a video to show how I'd like to improve it by adding captions and comments:<br>
<br>
<img atl="gallery flow" src="https://cloud.githubusercontent.com/assets/191598/8256181/28f160ce-1673-11e5-9d6d-3e9f0ef5048d.gif" />
<br>
For mobile, we'll do vertical scrolling. Here's a couple storyboards for how that'll work: https://cloudup.com/cr8NpoFqW55</blockquote>

**Comment by alisterscott** [comment]
The compact Reader view no longer shows galleries on the posts view, so this issue is no longer applicable. Closing.

<img width="848" alt="screen shot 2017-05-11 at 1 39 00 pm" src="https://cloud.githubusercontent.com/assets/128826/25931361/3a04add2-364f-11e7-866c-a335bee4533a.png">
