### ISSUE TITLE
Reader: "search" constraints yield no/irrelevant results

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#8040]
Reader search yields some unexpected results when trying to find particular feeds. cc @blowery for encouraging me to post here!

https://cloudup.com/cjKkWciu2fe
#### Steps to reproduce
1. Starting at URL: wordpress.com/reader/search
2. Search the URL with `http://` of a wordpress.com blog you know exists - no relevant results
3. Search the URL _without_ `http://` of a wordpress.com blog you know exists - no results at all
4. Search the title of a wordpress.com blog you know exists - no relevant results
5. Search the author's name of posts from a blog you know exists - no results at all
6. Search a the owner of a wordpress.com site by username that you know exists - see results for user with only primary site.
#### What I expected
1. expected "search" to allow me to find my friend's blogs or wp.com blogs I know exist
2. Search the URL with `http://` of a wordpress.com blog you know exists: expected the wp.com blog feed to pull up to allow me to read posts and/or follow it.
3. Search the URL _without_ `http://` of a wordpress.com blog you know exists: expected the wp.com blog feed to pull up to allow me to read posts and/or follow it
4. Search the title of a wordpress.com blog you know exists: expected the wp.com to be one of several options for clickthrough, likely ranked at the top.
5. Search the author's name of posts from a blog you know exists: expected posts from users with the searched name to display
6. Search a the owner of a wordpress.com site by username that you know exists: expected a way to navigate to a list of all the user's sites.

**Comment by gibrown** [comment]
Thanks for testing these. A lot of these come down to (1) and not having the correct data in the index yet for that use case. The current UI is entirely centered around posts rather than sites. But this is something we are actively working on and its good to have the list of use cases.

For (5), it doesn't look like your full name is set as your display name which is why we aren't finding you. Do you think it is set somewhere?

**Comment by meremagee** [comment]
> For (5), it doesn't look like your full name is set as your display name which is why we aren't finding you. Do you think it is set somewhere?

You're right. I had it set in the profile, but not in the public display name. 

![](https://cloudup.com/iHzuk7i07Ld+)

That said, updating my display name to full First Last, then searching again still yields nothing (probably not enough time to index, regardless). I don't think this is wildly unacceptable, but I think I've been trained by other social search options to expect something of the "posts by people named `xyz`" nature.

For instance, I might expect to be able to find "posts by people named `Matt Mullenweg`" here:
![](https://cloudup.com/cSv1nyhWR-j+)

**Comment by gibrown** [comment]
An additional case to fix here is searching for a post by the full url. That also doesn't work.

**Comment by gibrown** [comment]
I think all of these cases are now fixed on the backend.
