### ISSUE TITLE
Blog post – Site Editor vs Page Editor

### ISSUE THREAD

**Issue by jrdnhllr** [Automattic/wp-calypso#80418]

**Comment by jrdnhllr** [comment]
P2 | pbvYe0-1hZ-p2

**Comment by garretsteider** [comment]
@jrdnhllr 

Designs for this request are below. Tried to do something a little darker in line with the Nested theme. 

![Image](https://github.com/Automattic/wp-calypso/assets/118472190/766e9672-d9fd-4652-89d1-7c45d484fdb3)
