### ISSUE TITLE
Business name generator LP

### ISSUE THREAD

**Issue by jrdnhllr** [Automattic/wp-calypso#80415]

**Comment by jrdnhllr** [comment]
P2 | pcNC1U-KQ-p2

**Comment by Noemish** [comment]
Latest designs 3pi0l3jolYSioBHLwkxrRI-fi
Latest P2 pdZzpt-UT-p2#comment-1552

**Comment by Noemish** [comment]
Latest designs 3pi0l3jolYSioBHLwkxrRI-fi-587_1945
