### ISSUE TITLE
Blog post – Elevate your website with memberships

### ISSUE THREAD

**Issue by jrdnhllr** [Automattic/wp-calypso#80416]

**Comment by jrdnhllr** [comment]
P2 | pbvYe0-1i4-p2

**Comment by garretsteider** [comment]
@jrdnhllr 

What do you think about these options. I'll share here before i share on the P2 thread

One that generally shows a membership card (Similar to how arc browser gives you one when you sign up)

![Image](https://github.com/Automattic/wp-calypso/assets/118472190/b9afffdf-7bf4-4608-9a7c-72596168d5c9)


and one that shows a post behind a paid subscription 
![Image](https://github.com/Automattic/wp-calypso/assets/118472190/644fccfe-138a-4e45-9c20-8025d2d72501)

**Comment by garretsteider** [comment]
### Final Asset


![Image](https://github.com/Automattic/wp-calypso/assets/118472190/8307639e-5028-4fab-9420-e27e57fab87e)
