### ISSUE TITLE
Add language about discounted rates for special currencies on pricing page

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#80455]
### Quick summary

For some curriences, like IDR and MXN, we apply a 20% discount for the first year of a new purchase, then charge full price for subsequent renewals.

While this is evident in Checkout:

![image](https://github.com/Automattic/wp-calypso/assets/16580129/b60041b2-3d8a-49c5-b0bf-62bd2a0f3e3c)

And on the Plans page:

![image](https://github.com/Automattic/wp-calypso/assets/16580129/ccc0d561-01e0-47ba-a946-29d499ce927d)

It is not noted on the Pricing page:

![image](https://github.com/Automattic/wp-calypso/assets/16580129/3c8d258e-2f3e-46ee-bf12-0c5c1db1535e)

I am not sure if this is a marketing decision, but p1691692273494449/1691654144.850329-slack-C02BEP610 @aisajib to check with them to see if perhaps this was an oversight.

If so, we could spin up a PR to add in the appropriate language.

### Steps to reproduce

- Go to Store and set currency to IDR
- Go to [Pricing page](https://wordpress.com/pricing/?currency=INR)

### What you expected to happen

- I'd expect to see language regarding the 20% discount only applying to the first year

### What actually happened

- Instead the current language could be interpreted as '20% off in perpetuity'.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by sirbrillig** [comment]
> For some curriences, like IDR and MXN, we apply a 20% discount for the first year of a new purchase, then charge full price for subsequent renewals.

Are you sure this is true? In the screenshot it looks like the discount is a prorated discount ("Upgrade Credit") based on the site's current plan, which I think applies to all currencies.

**Comment by aisajib** [comment]
Hi @sirbrillig , yes, that is true. You can check out the p2 below:

p7DVsv-9lB-p2

**Comment by sirbrillig** [comment]
TIL! Thanks for clarifying.

**Comment by jjchrisdiehl** [comment]
> In the screenshot it looks like the discount is a prorated discount ("Upgrade Credit") based on the site's current plan, which I think applies to all currencies.

This screenshot was on a Free site with IDR currency set - so it would be the introductory rate rather than a prorated discount (e.g. if I were upgrading from Personal to Premium)

**Comment by sirbrillig** [comment]
Got it. The line item probably isn't displaying the discount correctly.

**Comment by cuemarie** [comment]
Hey folks!  I've added the label `[Pri] Normal` to this issue as KitKat tries to make sure all issues in `/wp-calypso` have priority labels - but feel free to change that if it needs a different priority level!

**Comment by sirbrillig** [comment]
From planning: I didn't read carefully before but it turns out this is actually two issues. The plans page is managed by Martech while Checkout is managed by Shilling. I'll split up the issue shortly to appropriately divide the work.

**Comment by sirbrillig** [comment]
This issue will continue to be about the pricing page and I made https://github.com/Automattic/wp-calypso/issues/80930 to handle checkout.

Re-assigning this to Martech.

**Comment by niranjan-uma-shankar** [comment]
We're tracking this separately [here](https://github.com/Automattic/wp-calypso/issues/51164#issuecomment-1576357551), so closing this issue.
