### ISSUE TITLE
Stats: Add relevant links to empty state modules on the traffic page

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#80465]
Design: p1HpG7-iTh-p2
Context: p1691693207423389-slack-C82FZ5T4G

Our first iteration will forego the modal approach and instead use direct links to the support pages.

```[tasklist]
### Tasks for the traffic page
- [ ] Update empty state for the chart (including all four tabbed states)
- [x] Update empty state for the posts & pages, referrers, country, authors, search terms, clicks, videos, emails, and file downloads modules (https://github.com/Automattic/wp-calypso/pull/80467)
```

**Comment by jsnmoon** [comment]
Updating the traffic page has the highest impact and would be practical to enhance first. We can create new/follow-up issues for the insights page, the My Home module, the Ads page, and the Store page.

**Comment by jsnmoon** [comment]
Cc @ederrengifo and @madebynoam so that you two are aware. We missed implementing improved empty state messaging during the modernization project, so we're addressing parts of it during Red's current maintenance sprint.

**Comment by kangzj** [comment]
I just noticed the docs linked are all from WPCOM. I guess we probably need the Jetpack ones too, but I don't find any 🤔

**Comment by jsnmoon** [comment]
> I just noticed the docs linked are all from WPCOM. I guess we probably need the Jetpack ones too, but I don't find any 🤔

This issue raises an interesting topic: Where do we want to host support documentation for Odyssey Stats? If the answer is Jetpack.com Support, we may need to duplicate some pages from WordPress.com Support.

EDIT: We do have some [here](https://jetpack.com/support/jetpack-stats/traffic-dashboard/)!

**Comment by kangzj** [comment]
> This issue raises an interesting topic: Where do we want to host support documentation for Odyssey Stats? If the answer is Jetpack.com Support, we may need to duplicate some pages from WordPress.com Support.

I guess it'd be Jetpack support? since they've already got the documentation [in place](https://jetpack.com/support/jetpack-stats/traffic-dashboard/) - thanks for finding that for me. And also Odyssey Stats is part of Jetpack as well, which would naturally be supported by Jetpack support team I think. I'm thinking of adding Jetpack doc links for Odyssey if it's okay.

Related: p4ya8V-6aR-p2#comment-3625
