### ISSUE TITLE
Bug: purchase page SVG missing shadow in Safari

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80470]
Related: https://github.com/Automattic/wp-calypso/pull/80270

P2: pejTkB-LV-p2

![Image](https://user-images.githubusercontent.com/1425433/259893706-ad34cc0e-30de-48a0-9765-c8f1f1241075.png)

**Comment by a8ck3n** [comment]
With the changes in #86129 in place (removing the SVGs), I think we can probably close this issue now.

cc: @kangzj.
