### ISSUE TITLE
Components: The RelatedPostCardv2 component has overlapping text at mobile width

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#8049]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks
2. Scroll down to the "More in Site" and "More in WordPress.com" sections
3. Resize the browser to a mobile screen width
#### What I expected

To be able to read the text
#### What happened instead

The user and header text are overlapping
#### Browser / OS version

Seen in Chrome (OSX and Android) and Safari (OSX)
#### Screenshot / Video

<img width="250" alt="screen shot 2016-09-12 at 9 17 20 am" src="https://cloud.githubusercontent.com/assets/7233112/18450605/b79c10e8-7901-11e6-8846-8bd4fe18171e.png">
#### Context / Source
# automated-testing #visdiff-testing

**Comment by lancewillett** [comment]
CC @jancavan Did you implement Related Posts? Can you take a look at this mobile view breakage?

**Comment by jancavan** [comment]
@lancewillett This might be due to the fact there's some odd padding set on Devdocs as mentioned in: https://github.com/Automattic/wp-calypso/issues/8674#issuecomment-253228142, but I'll look into it.

**Comment by jancavan** [comment]
I think the overlapping has been fixed since I'm no longer able to repro this issue.
