### ISSUE TITLE
Reader: make URLs more hackable

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#805]
Raised by @bluefuton 

I often find myself trying to lop off the post ID from a URL like this:

https://wordpress.com/read/post/feed/32897209/737511655
&rarr; https://wordpress.com/read/post/feed/32897209

...expecting it to give me the feed stream, and it doesn't work.

Ideally we should make these URLs "predictable, guessable, hackable" (hat tip to Tom Coates' vintage presentation http://www.darkcoding.net/future-of-web-apps/tom-coates-native-to-a-web-of-data/).

Perhaps we could include `post` later in the URL, to give a better representation of the feed->post relationship:

https://wordpress.com/read/feed/32897209/post/737511655

**Comment by blowery** [comment]
Fixed with #3546
