### ISSUE TITLE
Create Account Screen: Change the eye icon 

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/wp-calypso#80506]
Change and align the eye icon on pw field. 

<img width="456" alt="Screenshot 2023-08-11 at 4 31 42 PM" src="https://github.com/Automattic/wp-calypso/assets/25516611/3e6bc855-2c4c-4331-a487-6fc0ee00f19a">

The WP/component one we could use:

<img width="302" alt="Screenshot 2023-08-11 at 5 06 02 PM" src="https://github.com/Automattic/wp-calypso/assets/25516611/7415f99c-af25-4822-8aa5-8f761f48ff21">

**Comment by simison** [comment]
From [Gutenberg icon library](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library):

<img width="368" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/219546df-6e76-4318-bcca-1e9360d07611">

[I'll update this quickie.](https://github.com/Automattic/wp-calypso/pull/80736)
