### ISSUE TITLE
Launchpad: Shorten Newsletter task lists

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#80502]
On the CfT we noticed that the task lists are too long and we should find ways to make the experience more friendly. There are several ideas, but we decided to shorten both Newsletter task lists(Free and Paid) for now, so we can launch it by next week.

- [ ] Free Newsletter
  * Share your site
  * Enable subscribers modal
  * Write 3 posts
  * Add an about me page
  * Manage your subscribers

- [ ] Paid Newsletter
  * Share your site
  * Enable subscribers modal
  * Write 3 posts
  * Add an about me page
  * Manage your subscribers
  * Set up payment method(if the user skipped the first Launchpad)
  * Create paid Newsletter(if the user skipped the first Launchpad)

More context: 
* pdtkmj-1G6-p2#comment-3106
* pdtkmj-1G6-p2#comment-3116

**Comment by nuriapenya** [comment]
Isn’t Manage your subscribers a conditional task, as well?

If users added subscribers during onboarding, the task is Manage subscribers, but if they skipped, the task is Add subscribers.
