### ISSUE TITLE
Blogger Flow: Username doesn't wrap which causes layout issues with long usernames

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#80510]
### Quick summary

After creating a new account on the `/setup/blog` flow with a new user that had a long username, I end up seeing this.

<img width="1596" alt="Screenshot 2023-08-11 at 10 36 59 AM" src="https://github.com/Automattic/wp-calypso/assets/1126811/87686c92-65e5-483b-896d-bf69b5e7b4c3">

We should find some way to address this. Not sure if it's wrapping very long text or something else though.

### Steps to reproduce

1. Logged out, go to /setup/blog
2. Create account with long username
3. Ensure next step has some layout issues as shown above

### What you expected to happen

Centered content and no layout issues

### What actually happened

Layout issues

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
Tested on Simple – reproduced
Tested on Atomic – n/a
Replicable outside of Dotcom – n/a

📌 NOTES
When reproducing, no need to actually create a new site - navigate to `/setup/blog`.

After playing with the display name of my test user for a bit, it seems 26 characters is the maximum it will support before the odd formatting (shown in the screenshot above) takes over at the 27th character.

Example usernames:
- newline occurs: e2eflowtestingmanual1638568
- newline does not occur: e2eflowtestingmanual163856

**However**, and there's always an exception, even for names under 27 characters (thus no newline should occur), if the viewport width is less than ~820px the title gets shoved into a newline with the resultant odd formatting shown in the original screenshot.

📌 FINDINGS/SCREENSHOTS/VIDEO
Newline
![image](https://github.com/Automattic/wp-calypso/assets/6549265/31a07bb3-feda-4634-820b-7dab5e73f6b1)

No newline
![image](https://github.com/Automattic/wp-calypso/assets/6549265/e475c595-534e-430b-bf84-d12b3abfcc53)


https://github.com/Automattic/wp-calypso/assets/6549265/71bbf7b9-d779-4c16-bec4-c167abde3e0b


📌 LOGS

📌 ACTIONS
- set to Normal priority.
- assign to Lego column (please re-assign if incorrect).

**Comment by rcrdortiz** [comment]
The fix has been deployed 🥳
