### ISSUE TITLE
Components: search selected state border is cut-off in mobile viewport

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#8051]
<img src="https://cloud.githubusercontent.com/assets/66797/19498807/e1d37916-9547-11e6-910c-4264074494c6.png" width="480" />

#### Steps to reproduce
1. Starting at URL: wordpress.com/start on mobile web
2. Navigate through NUX to domains step
3. Notice that blue highlight on selected state is cut off on each side in portrait mode

#### What I expected
To see full selected-state border around search box

@shaunandrews (this happens on domains now and in site title in dev)

**Comment by lancewillett** [comment]
#bug-scrub

I can repeat this in Safari on iOS (and responsive view on desktop) but not in Chrome on Android. So it seems platform specific — at least, on /start forms.

Visual record:

Safari (iPhone 6s Plus, viewing in Safari's responsive mode)
<img width="778" alt="screen shot 2016-10-18 at 15 34 42" src="https://cloud.githubusercontent.com/assets/66797/19499070/370a4242-9549-11e6-9c36-1e1f8e301f60.png">
<img width="806" alt="screen shot 2016-10-18 at 15 35 37" src="https://cloud.githubusercontent.com/assets/66797/19499071/370f9bfc-9549-11e6-854c-e272ac8c1c14.png">

Chrome on Android (Nexus 6P)
![2016-10-18 22 33 21](https://cloud.githubusercontent.com/assets/66797/19499075/3d9e2826-9549-11e6-9f2f-63d155c40f98.png)
![2016-10-18 22 33 33](https://cloud.githubusercontent.com/assets/66797/19499076/3db08138-9549-11e6-8a72-6d48a65c9c83.png)
![2016-10-18 22 35 58](https://cloud.githubusercontent.com/assets/66797/19499077/3dba5852-9549-11e6-8e24-e26d413af7c0.png)

When looking at DevDocs design under Form Fields components, the blue border acts correctly across both Android and iOS.

Visual record:

Safari (iPhone 6s Plus, viewing in Safari's responsive mode)
<img width="773" alt="screen shot 2016-10-18 at 15 39 08" src="https://cloud.githubusercontent.com/assets/66797/19499091/5db98eac-9549-11e6-8df2-939b2be63a25.png">

Chrome on Android (Nexus 6P)
![2016-10-18 22 38 20](https://cloud.githubusercontent.com/assets/66797/19499092/60cb8a82-9549-11e6-8d02-eb2e2c92964c.png)

**Comment by lancewillett** [comment]
So, looks like two possible bugs — both specific to NUX signup forms and **not** across all Calypso form inputs.

1. Android Chrome doesn't highlight blue in domain input.
2. All mobile viewports have cut off sides.

**Comment by lancewillett** [comment]
@shaunandrews Closing then, thanks for your feedback.
