### ISSUE TITLE
Theme Showcase: The Category List Overflows to the Right

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#80555]
<img width="1193" alt="Screenshot 2023-08-14 at 13 18 14" src="https://github.com/Automattic/wp-calypso/assets/2070010/d509ece5-50c8-4036-b861-afa19908df1b">

In the Theme Showcase, at some screen widths, the category list overflows to the right by a little bit.
It is more visible when an element inside the More menu is selected, highlighting the More item itself.

**Comment by rcrdortiz** [comment]
I think this is fixed by https://github.com/Automattic/wp-calypso/pull/80746
