### ISSUE TITLE
Theme Showcase: "Install New Theme" Button and "View" Toggle Are Too Close

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#80556]
<img width="704" alt="Screenshot 2023-08-14 at 13 19 30" src="https://github.com/Automattic/wp-calypso/assets/2070010/d956e8de-fd0d-44e1-ab7b-7acd210005cc">

In the Theme Showcase, the "Install New Theme" Button and the "View" Toggle are too close and should be slightly spaced.

cc @lucasmendes-design for design input on a quick/lightweight solution!

**Comment by lucasmendes-design** [comment]
I'll bring this to the design team since the View option is presented on many different pages.

**Comment by lucasmendes-design** [comment]
Probably, this week I'll have something. Just waiting what others have to say ✌🏼

**Comment by Copons** [comment]
> I'll bring this to the design team since the View option is presented on many different pages.

@lucasmendes-design The View button is pretty much a Core element from wp-admin, so I'd argue that in this specific case our best bet is to leave it alone and move the Install button instead.

There's also a case for removing the View toggle on the Theme Showcase (aka removing the TS' classic view). We have casually chatted about it several times, but we are not ready to commit on it until at least the second half of September.

**Comment by lucasmendes-design** [comment]
> The View button is pretty much a Core element from wp-admin, so I'd argue that in this specific case our best bet is to leave it alone and move the Install button instead.

The pages that have this View toggle are following core as well. For example, the header and visual components (buttons, layout, etc). I couldn't find any page that has the View toggle and the new visual look. 

The theme showcase page isn't following core. It follows our style guide, like the new header component. This is the reason they are too close, we're using two different guidelines on the same page, which is creating conflict in this case.

<img width="555" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/6c6b2977-a6e8-4b83-a8d1-8d6dbb52d285">

Thus, if we want to keep consistency with the new approach, my suggestion is to hide the View "toggle" inside the three dots menu. Like the image below:

<img width="808" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/4e569bd9-95c5-47e0-974a-090f9673a753">

**Comment by mmtr** [comment]
Just noting here that we're considering to remove the view toggle from the theme showcase since the classic view is now obsolete. We just want to be sure that users won't lose any functionality if the classic view becomes unavailable.

More context: pekYwv-1v0-p2#comment-1123

**Comment by dsas** [comment]
We removed the View toggle so I'm closing this
