### ISSUE TITLE
Overlapping text on domain selection page

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#80580]
Long domain names make the text overlap with the labels on the domain selection page.

More context: pdtkmj-1G6-p2#comment-3113

![Screen Shot 2023-08-14 at 15 31 18](https://github.com/Automattic/wp-calypso/assets/1234758/3d030f13-4bd4-41ad-a2aa-42d7f1df97d2)

**Comment by daledupreez** [comment]
@Automattic/nomado do we have a dedicated/separate issue for this on your board? I think it may be better for team more familiar with the domain search results page to tackle this.

**Comment by daledupreez** [comment]
It looks like the original issue may have been resolved, but the badge text doesn't seem to be handled well. This screenshot is from `/setup/domain-upsell/domains?siteSlug=:siteSlug`.

<img width="1067" alt="Screenshot 2023-09-05 at 13 18 16" src="https://github.com/Automattic/wp-calypso/assets/3376401/d8daa83b-7b22-4450-98bc-c5a11d262271">

**Comment by valterlorran** [comment]
Closing this, as it seems to be resolved.
![Screen Shot 2023-10-02 at 08 44 58](https://github.com/Automattic/wp-calypso/assets/1234758/cdd00772-148c-4768-9585-84ce71df5033)
