### ISSUE TITLE
Subscriber Stats Display a Negative Count for Free Email Subscribers

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#80591]
### Impacted plugin

Jetpack

### Quick summary

The subscriber stats page shows a negative count for `Free email subscribers` in the All time stats section.

![CleanShot 2023-08-14 at 15 20 13@2x](https://github.com/Automattic/jetpack/assets/42279181/22aa44f7-8f8e-456d-90da-0a764785e95b)

### Steps to reproduce

1. Open Stats page.
2. Navigate to Subscribers tab.
3. Observe listed count.

### A clear and concise description of what you expected to happen.

I expected to have either 0 or a positive number of subscribers.

### What actually happened

The page shows a negative count for subscribers.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Atomic site on a Business plan.

**Comment by katiebethbrown** [comment]
I also would have expected that the paid email subscriber listed in the count in the top box would have displayed in the Subscribers (Email) section but that's not the case. 

![CleanShot 2023-08-14 at 15 27 09](https://github.com/Automattic/jetpack/assets/42279181/8c5bbc29-1102-44aa-bb74-328bc5dcdfe2)

**Comment by katiebethbrown** [comment]
Wouldn't a `Paid email subscriber` also be a `WordPress.com subscriber` though, since they (by nature of how the payment is setup) have a WordPress.com account?

**Comment by cuemarie** [comment]
Hey @katiebethbrown ! Is this a site of yours, or a user site? This appears to be site-specific (so opening my test sites, I'm not coming across a negative number there), so we'll need to take a closer look at the subscriber set-up on the site to understand how that negative number came to be

**Comment by katiebethbrown** [comment]
> Hey @katiebethbrown ! Is this a site of yours, or a user site?

@cuemarie - It's my test site. Blog ID 195418416.

Other notes:
- I have a paid newsletter set up.
- There are two subscribers:
   - The site owner
   - One paid subscriber (me, from another account).

Every paid newsletter subscriber has to have a WPcom account (an account is created at checkout if they don't) so I don't know that there's actually any way for there to be a `Paid email subscriber` in the same sense that there can be a `Free email subscriber`? 

Maybe that's more of a copy issue though, and it should be `Paid subscribers` instead of `Paid email subscribers`? Because I see that I have one paid email subscriber but the counts below show no email subscribers.

![CleanShot 2023-08-14 at 16 56 07](https://github.com/Automattic/wp-calypso/assets/42279181/178dc472-2a7c-481c-af2d-a5bac861c6fc)

The info presented here is really confusing. Dropping my thoughts below.

**Total email subscribers**
- This appears to be the count of all people that subscribed to my site via email not associated with a WPcom account (so zero).
- If there can't be a paid email subscriber (since all paid subs have a wpcom account) this is conveying the same thing as the count for Free email subscribers. 
- At a glance I expected this to be the total of _all_ subscribers on the site at a because of the word "total."

**Free email subscribers**
- I think this is supposed to be the count of all subscribers that used an email that is not associated with a WPcom account.
- On this site it should be zero, the same as the total email subscribers above.

**Paid email subscribers**
- Appears to be counting Paid Subscribers.
- The label seems wrong though, because all paid subscribers have WPcom accounts.
- It almost seems like we're using "Email subscriber" here to mean "subscribed to emails" and not "subscribed via email" which is different from how it's used in the other areas of the page.
- Maybe this should read `Paid WordPress.com Subscribers` or just `Paid Subscribers` instead.

**WordPress.com subscribers**
- Count of all subscribers (free and paid) connected to a WPcom account.
- Is this a useful metric?  As a site owner, do I care if a subscriber is email vs wpcom? 

### Other Thoughts
- I feel like we're missing the more valuable stat of "Total Subscribers." 

### Possible Approaches
Could we reduce noise and have just three cards?

- Free subscribers
- Paid subscribers
- Total subscribers

If the subscriber type  _is_ an important distinction for reasons I'm not thinking of, maybe these would make sense:

- Free subscribers with WPcom accounts
- Free subscribers without WPcom accounts
- Paid subscribers
- Total subscribers

**Comment by cuemarie** [comment]
Thanks @katiebethbrown ! 

@kangzj I see you're wrangling this a bit as well.  Can you help address the confusing UX here, or should we rope in the Newsletters/Subscribers teams as well, do you think?

**Comment by kangzj** [comment]
> @kangzj I see you're wrangling this a bit as well. Can you help address the confusing UX here

@cuemarie  Sorry I didn't release you were in the discussion. I'm working on https://github.com/Automattic/wp-calypso/issues/80532 and will address the issue by the way. Thanks for chiming in 👍

**Comment by cuemarie** [comment]
No worries at all! I just triage incoming issues that are reported to `/wp-calypso` with KitKat. Sounds like you've got a handle on this, so I can leave you to it!

**Comment by kangzj** [comment]
Hi @katiebethbrown , the issue is fixed and shipped. Are you able to help take look please? Thank you so much for reporting and the suggested solution 🙇 

![image](https://github.com/Automattic/wp-calypso/assets/1425433/ba370d7d-13ba-4c11-8385-a3f1791f352d)


Our next step is that, for sites without paid newsletter set up, we'd show subscriber types because paid / free wouldn't make sense.

- Total subscribers
- WPCOM subscribers
- Email subscribers

**Comment by kangzj** [comment]
I'll close the issue for now. Feel free to reopen if it still doesn't work. Thanks everyone 👍

**Comment by katiebethbrown** [comment]
Can confirm that things look much better on my end!

![CleanShot 2023-08-21 at 11 06 25](https://github.com/Automattic/wp-calypso/assets/42279181/f294fa0b-704d-4079-9bf8-24a19e49f1c7)

Thanks @kangzj!
