### ISSUE TITLE
Subscribers Stats Page is Not Responsive For Small Viewports

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#80590]
### Impacted plugin

Jetpack

### Quick summary

The Subscribers page in Jetpack stats is not responsive for small viewports.

### Steps to reproduce

1. Open Jetpack stats.
2. Navigate to the Subscribers tab.
3. Use or resize to a narrow viewport.

### A clear and concise description of what you expected to happen.

I expected the content to be responsive and shift to display in full on small viewports.

### What actually happened

The top row of cards truncates and is cut off instead of wrapping.

![CleanShot 2023-08-14 at 15 28 11](https://github.com/Automattic/jetpack/assets/42279181/661f66bb-5bb8-4ab6-a15e-d563d1daf021)

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Site is Atomic on a Business plan.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate this on my free test site created today. The cards along the top scroll horizontally once the viewport is narrow enough, but it's hard to tell that is what happens with the way they're cut off, and without a scrollbar.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/b6d57f3a-d613-419a-ab9f-df7426b6ec35

📌 ACTIONS
- Assigned to Other
- CC @jeherve

**Comment by kangzj** [comment]
Thanks for reporting this. 👍 

> We have horizontal scrolling for the highlight cards, dot selector containment for promotional banners, and a responsive grid layout for the stats module. This might be worth keeping in mind as we iterate on our mobile layout - p1692050043711339/1689971745.188539-slack-C052XEUUBL4


> Agreed, I think we could do better here. A partial fade-to-white on the side with scrollable content would do as well - p1692049666886159/1689971745.188539-slack-C052XEUUBL4

 
I felt this is something we need to address for consistency, but I'm not sure how. Before figuring out the best solution, <strike> I'd say we start with what Jason suggested - "A partial fade-to-white on the side with scrollable content".</strike>

=======================Update=============================

Compact cards might be a better idea:

> If it’s just 3-4 numbers, those would fit pretty easily on the screen simultaneously with different design 
> Google analytics has this; combined numbers on one screen, the graph for each is as a slider p1692129868688389/1689971745.188539-slack-C052XEUUBL4

![image](https://github.com/Automattic/wp-calypso/assets/1425433/01efaf5f-1697-44f1-a890-92234cb11fbc)


cc @ederrengifo @madebynoam

**Comment by a8ck3n** [comment]
Per #87214, the highlight cards on the Subscribers page now have an updated layout that will work better for smaller screen sizes.
