### ISSUE TITLE
Move the Information Icon in Traffic Settings

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#80592]
#### Icon Placement

There is an 'i' (information) icon in the SEO section of Traffic Settings. The text in the icon is about the Page Title Structure settings, so the icon should be next to those settings instead of the current position:
![Annotation on 2023-08-15 at 09-58-04](https://github.com/Automattic/wp-calypso/assets/30727666/3376a003-5745-4c3e-8c79-332c1088e3da)

#### Learn More URL

In addition, there's a "Learn more" link in the information text that leads to https://jetpack.com/support/seo-tools/ but it should lead to https://wordpress.com/support/seo-tools/#page-title-structure for WordPress.com sites.

### Steps to reproduce

On a Business or Commerce plan site:

1. Navigate to Tools → Marketing
2. Select the Traffic tab
3. In the "Search engine optimization" panel, click the i icon.

### What you expected to happen

I expected to see general information about SEO Tools.

I also expected the "Learn more" link to take me to WordPress.com documentation, not Jetpack.

### What actually happened

I saw information about the "Page Title Structure" settings, which is a separate settings panel.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- This tooltip is visible on an AT site only, when no other SEO plugins (like Yoast) are active. 

#### Screenshots/Recordings
![Markup on 2023-08-14 at 18:08:57](https://github.com/Automattic/wp-calypso/assets/27249804/986dba49-94d2-4984-afe4-20fe068bcf00)

Learn More link in the pop-up directs to: https://jetpack.com/support/seo-tools/

📌 ACTIONS
- Assigned to @Automattic/vertex

**Comment by escapemanuele** [comment]
Hey @donalirl, it is like this in my PR now:
![image](https://github.com/Automattic/wp-calypso/assets/52076348/78c4c377-81ec-43cf-ba39-3423261e0aa9)

Do you want to change the location of the "i"?

**Comment by donalirl** [comment]
> Do you want to change the location of the "i"?

Seems like a good spot for it 👍 

I also just noticed that the "optimize your site's SEO" link in the previous section links to the wrong doc.

Current link: https://jetpack.com/support/seo-tools/
Correct link: https://wordpress.com/support/seo-tools/

Dotcom sites should link to the WordPress.com doc. Jetpack sites should continue to link to the JP doc.

Should I open up a new issue for this, or is it ok to report that here?

<img width="619" alt="Screenshot 2023-08-31 at 11 54 45 am" src="https://github.com/Automattic/wp-calypso/assets/30727666/2f102327-6d32-4aeb-ad97-ba17edd3d325">

**Comment by escapemanuele** [comment]
Checking in the code, I see this:

```
const seoHelpLink = siteIsJetpack
		? 'https://jetpack.com/support/seo-tools/'
		: 'https://wpbizseo.wordpress.com/';
```

So, it is currently sending you to Jetpack if it is a Jetpack site ( I imagine just by it being atomic, so having any plugin ). Otherwise it is sending you to wpbizseo, and I can change that 👍 

Also, a free user, so without Jetpack, will not see this section 🤔 

![image](https://github.com/Automattic/wp-calypso/assets/52076348/484c24fc-0fb1-46d8-aa5f-912a15df7f12)

**Comment by donalirl** [comment]
Ah I see. `https://wpbizseo.wordpress.com/` is old and we don't want to use that.

To clarify, atomic dotcom sites would also want to use https://wordpress.com/support/seo-tools, not https://jetpack.com/support/seo-tools.

Self-hosted sites would continue to use https://jetpack.com/support/seo-tools.

**Comment by escapemanuele** [comment]
Hey @donalirl, sorry for the delay. I deployed the i icon change of position, and opened a new issue for the link problem: https://github.com/Automattic/wp-calypso/issues/81503
