### ISSUE TITLE
Copy change in WooCommerce.com account screens

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#80601]
P2: p4ya8V-6dF-p2#comment-3608

![Image](https://user-images.githubusercontent.com/3747241/260611307-be6642e9-8383-4a8e-813c-3cb47aa68ab3.png)

Minor copy change in account steps from NUX.

### Acceptance criteria

1. Update `All woo Stores` to `All Woo Express stores` in all screens (please check signup, signin, forgot password, and reset password screens)

**Comment by cuemarie** [comment]
@adrianduffell @crunnells Hey folks! Because of the new `Bug` and `High` priority labels within the `wp-calyspo` repo, this was flagged for team KitKat's attention - but it looks like it may actually be addressed already, so just checking in to see if this can be closed? Thanks!

**Comment by adrianduffell** [comment]
Thanks @cuemarie, yes I think you are right. I will close the issue out now.
