### ISSUE TITLE
Subscriber Stats: Hide admin from being a subscriber to their own site

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#80610]
pejTkB-Mn-p2#one-subscriber

Subscribers page API endpoint: `/wpcom/v2/sites/{site-id}/subscribers?per_page=10&page=1&sort=date_subscribed&filter=all`

Subscribers Stats page API endpoints:
WordPress.com: `/rest/v1.1/sites/{site-id}/stats/followers?type=wpcom&max=10`
Email: `/rest/v1.1/sites/{site-id}/stats/followers?type=email&max=10`

**Comment by dognose24** [comment]
After digging into the API endpoint of the Subscribers page (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfhofpevoref.cuc%3Se%3Q75r57rn6%23338%2Q344-og), we could also filter subscribers to [hide the current user on Calypso Stats](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/stats/lists/utils.js#L511-L528) or API ends.

However, we have [yet to determine a real current user passed through Jetpack](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/stats-admin/src/class-odyssey-config-data.php#L65C1-L74) to fetch corresponding subscriber data since the Odyssey Stats user's id may not belong to any of the WPCOM user ids.

In that case, we could only hide the current user from subscribers on the Calypso Stats. Or we defer to a more comprehensive way for both Calypso and Odyssey Stats.

cc @kangzj

**Comment by kangzj** [comment]
Thanks for exploring this and the helpful notes @dognose24 ❤️ 

> In that case, we could only hide the current user from subscribers on the Calypso Stats. Or we defer to a more comprehensive way for both Calypso and Odyssey Stats.

Agreed. It would be best if we have unified experience between Odyssey and Calypso Stats. It's not always possible especially when it's about user id tho - local users might not have their correspondence on wpcom.

I'm also thinking, does it make sense to filter the current user? If we are doing that, then different users might see different number of subscribers. Would it be better to filter only the blog owner for everyone? Wonder what @simison thinks 😃

**Comment by simison** [comment]
Unified is better, but if it's just .com, that's better than nothing. 👍  Since every .com site subscribes site creator by default, this would stop future "empty state launchpad" never showing up for subscriber stats. (discussed in p1HpG7-mpJ-p2 and pdDOJh-1WO-p2/#comment-1545).

> Would it be better to filter only the blog owner for everyone?

Blog owner makes most sense. 👍

**Comment by kangzj** [comment]
Report of discrepancy due to the issue: p1HpG7-pbn-p2#comment-66545

**Comment by dognose24** [comment]
The Diff to filter the site owner on the Stats Subscribers page is D127415-code. The next step is to resolve the subscriber numbers discrepancy on the highlight cards of Stats Subscribers.

<img width="1038" alt="截圖 2023-11-02 上午12 47 10" src="https://github.com/Automattic/wp-calypso/assets/6869813/f86531d8-5620-4928-88a6-00f8dd1327de">

**Comment by simison** [comment]
Nice, thanks. This all will be very helpful for being able to show "empty state launchpad" described in pdDOJh-2Ee-p2#comment-1991

**Comment by dognose24** [comment]
The D127415-code and https://github.com/Automattic/wp-calypso/pull/83901 to fix this issue are live now! cc @simison @kangzj

<img width="1282" alt="截圖 2023-11-07 下午1 59 53" src="https://github.com/Automattic/wp-calypso/assets/6869813/fa891f03-af58-413c-a245-b9f3dcfcb464">

**Comment by kangzj** [comment]
Let's try a new approach: pejTkB-14x-p2

**Comment by kangzj** [comment]
> The D127415-code and https://github.com/Automattic/wp-calypso/pull/83901 to fix this issue are live now! cc @simison @kangzj

Maybe we could revert some changes to start with 😄

**Comment by dognose24** [comment]
The changes with reversion for the API end and front end are both live now. https://github.com/Automattic/wp-calypso/pull/86762 D135598-code
