### ISSUE TITLE
Error Logging: provide `console.log` alternative

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#8061]
Sometimes we need to log some information to track when events occur.
It would be nice to add some .log opportunity to error logging to see how calypso behaves.

I remember @gwwar had a use-case for it.

**Comment by artpi** [comment]
Maybe look into Domain Medic for insporation?

**Comment by gwwar** [comment]
The primary use case I'm thinking of is when we have a caught exception but still want to report it. This is a common use case for error aggregators. See also [sentry](https://docs.sentry.io/hosted/clients/javascript/#reporting-errors) and [rollbar](https://rollbar.com/docs/notifier/node_rollbar/) for example usage

```javascript
try {
 doSomethingThatBreaksSometimes();
} catch( e ) {
   logger.handleError( e );
}

// or...

promise.then( function() {
    //do other things
} ).catch( function( e ) {
    logger.handleError( e );
} ).; 
```
