### ISSUE TITLE
Theme Showcase: Unify All the Dropdown Colors

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#80626]
![image](https://github.com/Automattic/wp-calypso/assets/2070010/c39901a0-475c-4567-b9ea-d5754cccf3a8)

The Theme Showcase has 4 different dropdowns, each with their own inconsistent colors.

We should unify them, using as a base the `ResponsiveToolbarGroup`, which is the more modern component on the page, and shared with the Marketplace as well.

* Default
  * Black text `var( --color-neutral-60 )`.
  * White background `transparent`.
* Default hovered
  * Black text `var( --color-neutral-60 )`.
  * Light grey background `var( --studio-gray-0 )`.
* Selected
  * White text `var( --color-text-inverted )`.
  * Black background `var( --color-neutral-80 )`.
* Selected hovered
  * No hover effect (note: this is bugged in the current implementation! see https://github.com/Automattic/wp-calypso/issues/80492).

Note: please confirm that the colors are correct!

**Comment by rcrdortiz** [comment]
The scope of the issue is limited to the LITS, which is the one that has a dark color scheme. I'm also going to include the necessary changes to unify the LOTS too. For the LOTS I'm going to use the same approach, using the color of the `ResponsiveToolbarGroup` which is blue.

**Comment by rcrdortiz** [comment]
Changes have been deployed.
