### ISSUE TITLE
Wording of the error message on the Jetpack Install page

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#8062]
When the site doesn't have xmlrpc.php file and returns a 404 message when checked (example.com/xmlrpc.php), the [Jetpack Install page](https://wordpress.com/jetpack/connect/install) returns the following error message:

<img width="464" alt="screen shot 2016-09-13 at 11 16 03 am" src="https://cloud.githubusercontent.com/assets/10340370/18468609/f68365c4-79a4-11e6-8075-de1735b51925.png">

This is quite misleading and needs to be worded better. My suggestion:

_We couldn't find XML-RPC file on your site at $site/xmlrpc.php. Please get in touch with your host and make sure Jetpack can access XML-RPC file on your site._

**Comment by johnHackworth** [comment]
This is a pretty good point. Our way to detect if a site is a WordPress site or not relies in detecting XMLRPC, which as we all now, can or can not be accessible, so it's a pretty weak way of looking into it.

We need to both improve our detection method (looking for several things maybe? XMLRPC, check if /wp-admin is there, check if there's anything being served from a wp-includes url in the html code of the page, etc), but also improve this error message so it's not so absolute (there's no way to be 100% sure that this is not a WordPress site, and we probably should be explaining what we are looking for and not finding)

ping @rickybanister

**Comment by rickybanister** [comment]
Can we start with your suggestion of a better wp detection method and go from there on the error?
