### ISSUE TITLE
Advanced SEO: scrollbars showing in DraftEditor component

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#8063]
![screen shot 2016-09-13 at 12 42 24](https://cloud.githubusercontent.com/assets/4389/18472512/d343760c-79af-11e6-93cb-f6587b06c020.png)

The `DraftEditor` component input box shows scrollbars, see screenshot above. The cause is using `overflow` with a `scroll` attribute that shows the scrollbars even when not needed.

The correct behaviour would be to not show any scrollbar, ever (`overflow: hidden;`), since that's the behaviour of a text input, which this control mimics, like:

![screen shot 2016-09-13 at 12 50 03](https://cloud.githubusercontent.com/assets/4389/18472661/a431ab62-79b0-11e6-8336-bd192faad495.png)

The left-right padding should be also tweaked accordingly to match the top-bottom one.

_Tested in Chrome 52, Firefox 48, and Safari (appears on both), OSX 10.11.6._

**Comment by folletto** [comment]
_Note: the above is often caused by working without visible scrollbars. If you're on OSX please enable the scrollbars when working on any UI. The setting is inside General:_

![screen shot 2016-09-13 at 12 52 04](https://cloud.githubusercontent.com/assets/4389/18472709/ea479bd4-79b0-11e6-9e19-36c1efcf7246.png)

**Comment by dmsnell** [comment]
@folletto and @drw158 and @roundhill - this ties into an unresolved discussion around maximum title length. should we restrict the length of the generated title? if so, how many characters is too long? the tokens add a layer of confusion because the `Site Name` could also be really long, but we could limit things when we _know_ it would be too long if indeed there is such a "too long"

**Comment by folletto** [comment]
I'm not sure: I think the issue you mentioned is relevant, but the above is really just a visual issue with the scrollbars. Shouldn't your question be a separate conversation?

**Comment by dmsnell** [comment]
> Shouldn't your question be a separate conversation?

maybe, though I was thinking that the two were so related they could probably come together

**Comment by folletto** [comment]
The form shouldn't show scrollbars, regardless of it being limited or not, that's why I'd suggest a split. :)

---

Regarding your question: I'm not aware of any need of restricting title length. Is there anything in the standard that hints that way? I'd probably just add a text note that shows up below the form if the title gets longer than 60 characters because [as far as I know](https://moz.com/blog/title-tag-length-guidelines-2016-edition) that's a general cut-off point for display (even if, I think it still gets indexed fully and properly).
The note could be a line below the "Preview:" text that appears when it hits 60 characters, and could have this copy: "Titles above 60 characters might not display entirely on search engines." maybe even with a link to the post above?

**Comment by roundhill** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/8237

**Comment by drw158** [comment]
- I agree title length shouldn't be limited
- warning message though would be great if it's longer than 60

Can we use this, but with different colors?

https://wpcalypso.wordpress.com/devdocs/design/form-fields
![screen shot 2016-09-29 at 11 29 52 am](https://cloud.githubusercontent.com/assets/618551/18962917/455a14b4-8638-11e6-8661-07194296f5e8.png)

I'm imagining the preview text just going below the warning if it goes > 60 characters. But, it'd be fine if the preview text was above the error too.

**Comment by drw158** [comment]
related #8328

**Comment by folletto** [comment]
I feel should be an almost "irrelevant" suggestion. It doesn't really impact anything, it's more contextual information and a very very specific optimization.
