### ISSUE TITLE
Design Picker: Style variations UI moves around on 950px height

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#80632]
### Quick summary

The Style variations UI moves around when the height is 950px. 

https://github.com/Automattic/wp-calypso/assets/995955/94a028ed-34b0-46d2-b23e-6c983378a87e

See discussion in p1692113674471819-slack-C04DZ8M0GHW

### Steps to reproduce

1. Get a free site
2. Go to setup/site-setup/designSetup?siteSlug=your-site&theme=zaino
3. Resize your browser window to a height = 950px
4. Notice that the UI on the left moves (jiggles)

### What you expected to happen

The UI should stay fixed 

### What actually happened

It moves

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

- Chrome
- 950px height

**Comment by Copons** [comment]
I can repro this consistently on Chrome, between ~955-975px height, and width above the ~960px breakpoint.

Cannot repro if I emulate mobile with the browser's dev tools, possibly because the scrollbar is thinner.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Firefox 116.0.2 (64-bit) – **Replicated**
- Tested on Chrome Version 115.0.5790.170 (Official Build) (x86_64) – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO

**Chrome**

https://github.com/Automattic/wp-calypso/assets/27249804/5808765a-1e95-4f56-9011-d051237b9a01

**Firerox**

https://github.com/Automattic/wp-calypso/assets/27249804/87829964-92e8-4443-8d15-492ce253444a

📌 ACTIONS
- Already assigned to T-Rex 👍

**Comment by dsas** [comment]
The previous `transform:scale(1)` fix still seems to be in place (though by a different method?). I tried to bisect back to find the commit but it gave me d25bfffce which seems like utter nonsense 🤔

**Comment by mmtr** [comment]
I think the issue has been always present, since I can definitely replicate it in https://github.com/Automattic/wp-calypso/commit/f92c93ac1b313db3f946e27b73261a5037a02574 which is where we introduced the `transform:scale(1)` fix.

I couldn't find any solution yet though.

**Comment by arthur791004** [comment]
The possible solution is to avoid the layout change via
* Hide the scrollbar
* Reserve space for The scrollbar by the `scrollbar-gutter`

**Comment by mmtr** [comment]
That's a good idea @arthur791004! It indeeds solves the issue, but I'm afraid `scrollbar-gutter` is not supported by Safari, so we probably need to find a different workaround.

**Comment by mmtr** [comment]
> I'm afraid scrollbar-gutter is not supported by Safari, so we probably need to find a different workaround.

I guess one possible workaround is to fallback to `overflow: scroll` so the scrollbar is always visible. I'll open a PR shortly
