### ISSUE TITLE
How to remove myself from a Blog?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-calypso#8064]
Dear all, 

How can I remove myself from a blog?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18474020/2f2e0490-79c0-11e6-8367-af6d7e2365d6.png)

![image](https://cloud.githubusercontent.com/assets/170947/18474028/3dc17d98-79c0-11e6-93d5-43dcd35a5655.png)

**Comment by lancewillett** [comment]
Hi Robert, we ask that you use our support site to ask these questions. Let's keep GitHub to code and design pull requests and bug reports, please.

https://en.support.wordpress.com/my-blogs/#leave-a-blog
https://en.support.wordpress.com/user-roles/

**Comment by orschiro** [comment]
Hi Lance, 

No problems asking it as a question. I was just thinking that maybe this feature could be added to the interface shown in the screenshots above. 

What do you think?

Warmly,

-Robert

**Comment by lancewillett** [comment]
OK: that sounds similar to this open issue: https://github.com/Automattic/wp-calypso/issues/3321 — feel free to add your comments and ideas there. Thanks!

**Comment by orschiro** [comment]
Thank you Lance!

I will subscribe to #3321. 

-Robert
