### ISSUE TITLE
Image Editor Crop: make handles larger

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#8065]
While working on adding touch support to our Image Editor, I discovered that the Image Editor Crop handles are quite small and I'm having difficulties dragging them. This is what I have in mind:

![selection_154](https://cloud.githubusercontent.com/assets/4988512/18474214/5a2781b6-79c1-11e6-97e9-2848d8709ae1.png)

Instead of dragging a handle, I usually drag the image cropper or just nothing happens when I'm trying to drag the handle.

We should make the handles larger on mobile (ie touch) devices.

**Comment by drw158** [comment]
Currently they are 12px. 17 or 18px feel about right. We should retain the size of the handle and just make the click area bigger if possible. The handle dot does not have to be in the direct center of the click target.

**Comment by gwwar** [comment]
+1 for making the target area bigger but leaving the handle sizes relatively small.
