### ISSUE TITLE
Assembler: Show a congratulation screen after plan upgrade

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#80672]
## Description

As proposed in pekYwv-2Fn-p2, we are interested in introducing a congratulation screen in the Assemble flow when users upgrade their plan.

See Figma file: Tv3pYqA3EcRfiXC31IxrXE-fi-1660_51786, or the following screenshot for reference:
![Image](https://user-images.githubusercontent.com/797888/260927162-7cf76fa6-585b-4796-a5e7-96dbe0c7a938.png)

Since there's already a similar step for theme activation, let's look into have as much shared code as possible.

![Image](https://user-images.githubusercontent.com/797888/260927620-5d516555-9e30-4321-8da7-b5a6e4f57892.png)

## Acceptance Criteria

- [ ] Show a congratulation step after users have upgraded their site plan.
- [ ] Ensure that the new interactive elements have Tracks events.
- [ ] Finalize copy with @autumnfjeld  and @lucasmendes-design.

**Comment by autumnfjeld** [comment]
Thanks for adding the copy item. 💟

**Comment by lucasmendes-design** [comment]
We already have the congratulation screen implemented on the Blog flow from the logged-out homepage. So we can reuse it. :) It's not something 100% new. We can also update the congrats page from the theme activation. 

Not related to this GH issue but I really recommend going through this flow because the domain and plan selection happen inside the launchpad, not right after account creation. 

<img width="1321" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/0d251513-edc2-41e9-8a6c-8bad32e5caa4"> 

<img width="1064" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/fee7d813-7f04-46e2-a857-6686307c5b38">

**Comment by lucasmendes-design** [comment]
After checkout, you will see the congratulation page with the confetti animation 🎉🎊

**Comment by taipeicoder** [comment]
>Not related to this GH issue but I really recommend going through this flow because the domain and plan selection happen inside the launchpad, not right after account creation. 

@lucasmendes-design could you explain more what do you mean by this?

**Comment by lucasmendes-design** [comment]
> could you explain more what do you mean by this?

Sorry @taipeicoder, I didn't explain anything hahaha 😆. The Blog flow doesn't have the plans and domain steps after account creation. We also had an idea to have something different, like the entry points on the Paint the Web LP. So, I think we can get some inspiration from it and if we need it, we can reuse some components and behavior.

**Comment by autumnfjeld** [comment]
I'll chime in: the Blog flow is really unusual in that we don't "force" selection of the plans and domain step at the begining of the flow. It is a big deal in that the actual experience and view of their website comes BEFORE the "business aspects" of plan and domain.   I would have to go looking to see if they've posted metrics, but the idea is that many people feel we should be showing the product, the experience BEFORE making people choose a plan.  ANd if their metrics show it doesn't hurt plan purchases more flows could work like this.

So it would b great if all of @Automattic/lego  would take the Blog Flow for a spin. :) See pdtkmj-1uk-p2 & https://wordpress.com/create-blog/

**Comment by lucasmendes-design** [comment]
> ANd if their metrics show it doesn't hurt plan purchases more flows could work like this.

I'm not sure if they have much traffic to draw conclusions but I can ask Say about this. Let's see. I'll post my finding in the Slack channel.

**Comment by lucasmendes-design** [comment]
Some data about this flow pb5gDS-38f-p2#comment-4075

**Comment by arthur791004** [comment]
We might need to consider how to do this as we redirect users back to the Assembler screen with the selected layout and styles after the upgradation. So nothing is ready after the plan upgrade 😅

**Comment by autumnfjeld** [comment]
>  So nothing is ready after the plan upgrade 😅
Not sure I follow. What does this mean? :)

**Comment by arthur791004** [comment]
Sorry for not being clear. I mean the site is not ready after the plan upgrade. We redirect the user back to the Assembler screen and they have to continue again to finish the Assembler.

**Comment by autumnfjeld** [comment]
If we go forward with using the Laundpad, this work is not needed.

@lucasmendes-design  is that decided?  Yes on Launchpad?

**Comment by lucasmendes-design** [comment]
I shared the iteration with Launchpad but I haven't heard from @ianstewart if we're happy with the task I added in the Launchpad. I'll double-check with him.

**Comment by lucasmendes-design** [comment]
Here 

<img width="499" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/443db1f5-3943-42b7-8774-12e9df09d9b3">

**Comment by autumnfjeld** [comment]
@Automattic/lego  can we close this issue?

**Comment by arthur791004** [comment]
Closing it as it's not planned
