### ISSUE TITLE
Site Assembler: Make Sections category list keyboard-accessible

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#80676]
### Description

After we ship:

- #80673

, now the Sections "button" opens the category list in the same sidebar panel as follows:

Currently it is possible to open the category list via keyboard:

1. Hit Tab key; it will go from Header to Sections
1. When the focus is in Sections, hit Enter

The problem is, the focus cannot be moved inside the category list, so it is not possible to browse the category list via keyboard.

### Acceptance Criteria

We should be able to browse the category list inside the Sections section via keyboard.

@Automattic/lego @arthur791004

**Comment by fushar** [comment]
Update: we reverted the new navigation via:

- https://github.com/Automattic/wp-calypso/pull/81439

However, the category list is still not keyboard-accessible; it is not possible to browse through the categories via keyboard.

**Comment by miksansegundo** [comment]
I'm working on this right now. I'll push a PR very soon.
