### ISSUE TITLE
Assembler: Add a gated custom styles step

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#80682]
## Description

As proposed in pekYwv-2Fn-p2, we want to gate custom styles via an additional step in the Assembler instead of a modal. Note that users will only see this step when they have selected custom styles using a site in which custom styles are gated. Otherwise, users will see the confirmation step described in https://github.com/Automattic/wp-calypso/issues/80679

| Before | After |
| --- | --- |
| ![Image](https://user-images.githubusercontent.com/797888/260958318-cb83cb4f-65fa-4d88-8034-303af01d620b.png)|![Image](https://user-images.githubusercontent.com/797888/260958528-deee371d-278d-458d-9639-d19faa937edb.png)|

See Figma file: Tv3pYqA3EcRfiXC31IxrXE-fi-1660_51634

## Acceptance Criteria

- [ ] Implement the gated custom styles step for users that have selected custom styles using a site in which custom styles are gated.
- [ ] Ensure that the new interactive elements have Tracks events.
- [ ] Finalize copy with @autumnfjeld and @lucasmendes-design

**Comment by lucasmendes-design** [comment]
cc: @michaelpick @fcoveram :)

**Comment by michaelpick** [comment]
Hi @lucasmendes-design. 

I understand that Francisco took a look yesterday and shared the following feedback, which I agree with:

- I don’t know if the “You’ve chosen a custom style…” part is needed
- I think “Your color and font choices are exclusive to the Premium or above plans” works better in this context
- In the CTA, “Premium” should be capitalized

**Comment by lucasmendes-design** [comment]
Thanks @michaelpick . 

Btw, nice avatar haha. 
<img width="212" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/6c93411c-baf8-4f9c-9929-3ab461aa748e">

**Comment by michaelpick** [comment]
Hahaha, all credit to Stable Diffusion for that one 😄

**Comment by taipeicoder** [comment]
@lucasmendes-design the current Assembler has this step when the user comes from the LiTS: 
![Screenshot 2023-08-22 at 12 25 01 PM](https://github.com/Automattic/wp-calypso/assets/797888/a9e5d273-7e5d-478a-8409-b50964a14ba1)

Should we merge it to this step?

**Comment by arthur791004** [comment]
@lucasmendes-design The width of the sidebar might not be enough to display the plan with the price, e.g.: Get Premium for NT$240.00/month. Any idea for this?

![image](https://github.com/Automattic/wp-calypso/assets/13596067/ad56e2e1-6044-4d69-b408-ea2ae022bce5)

**Comment by lucasmendes-design** [comment]
> The width of the sidebar might not be enough to display the plan with the price, e.g.: Get Premium for NT$240.00/month. Any idea for this?

Let's use just Get Premium. We can figure out how we want to display the plan's price later.

**Comment by taipeicoder** [comment]
I was going to point out the A/B testing, but it seems that they've reached to a conclusion in paYJgx-3PM-p2#comment-4032.

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/81019
