### ISSUE TITLE
Change trial banner and trial expired page text

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#80694]
The [TrialBanner](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plans/trials/trial-banner/index.tsx#L63) component shows the exact text either for `ECommerce` and `Business` trial. The Business trial must be changed because the "start selling" is only related to a WooCommerce store.

As well as the top text of the trial expired page https://github.com/Automattic/wp-calypso/pull/80693.

**Comment by bogiii** [comment]
We need to update a copy of the Trial Banner component.

From **e-commerce**,
"Your free trial will end in 2 days. Upgrade to a plan by August 24 to unlock new features and **start selling**.",

to **migration trial** context:
"Your free trial will end in 2 days. Upgrade to a plan by August 24 to unlock new features and **launch your migrated website**."

Current look:
![Image](https://github.com/Automattic/wp-calypso/assets/1241413/04d3eae7-7a51-429b-8e9b-dc463e854a21)
