### ISSUE TITLE
Flaky E2E: Site Assembler header, section, and footer validation fails intermittently

### ISSUE THREAD

**Issue by youbrokesomething** [Automattic/wp-calypso#80699]
### Spec file

specs/onboarding/ftme__site-assembler.ts

### TeamCity ID

10605893

### Logs

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for getByRole('listbox', { name: 'Block patterns' }).getByRole('option').nth(1).frameLocator('iframe').locator('.block-editor-iframe__body')
  locator resolved to <body tabindex="0" contenteditable="false" class="bloc…>…</body>
attempting click action
  waiting for element to be visible, enabled and stable
element is not visible - waiting...
============================================================
    at SiteAssemblerFlow.click [as selectLayoutComponent] (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:50:5)
    at Object.selectLayoutComponent (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__site-assembler.ts:96:24)
```

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/28037267-e61f-4b92-b8cc-898a30095366)


![image](https://github.com/Automattic/wp-calypso/assets/6549265/abfc05b1-00a3-4a60-afa9-56efe1b3f3bc)

**Comment by worldomonation** [comment]
cc @fushar, it looks like whatever change in https://github.com/Automattic/wp-calypso/pull/80673 is causing the rates of intermittence to spike up pretty high when selecting site assembler parts.

Kylee and I are investigating, I just wanted you to be aware for the moment.

**Comment by worldomonation** [comment]
@youbrokesomething I think I have a solution, working on verifying it under repeated stress test as of 2023/08/18 17:30 UTC+9.

**Comment by youbrokesomething** [comment]
@worldomonation How did the stress test go?

**Comment by worldomonation** [comment]
@youbrokesomething I have a PR up for review.
