### ISSUE TITLE
Launchpad Newsletter Paid: "Set up payment method" task is not clickable/actionable in Customer Home

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#80714]
I noticed as I was testing a different PR that the "Set up payment method" task does not work when viewed in the Customer Home (`intent-paid-newsletter`) task list.

**Steps to reproduce:**

* Create a new site from `/setup/newsletter`
* Select a Paid newsletter
* At the Launchpad in Stepper step, click on "Set up payment method" task; you should be redirected to a Stripe connection screen (this may be different if you're not in a country that supports Stripe?) but don't configure anything here.
* Go back to the Launchpad in Stepper and write your first post to "launch" your site
* Go to `/home/siteSlug`
* You should see the "Set up payment method" task in the list:

<img width="1087" alt="Screenshot 2023-08-16 at 3 11 48 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/7971e066-de8d-4edb-8e81-56f11a814dfb">

* Try to click on the task. Nothing happens.

I believe we recently updated the API to serve the task action/redirect URL rather than handling them client side, and I suspect we haven't set a URL for this task on the server side.

**Comment by sixhours** [comment]
> I believe we recently updated the API to serve the task action/redirect URL rather than handling them client side, and I suspect we haven't set a URL for this task on the server side.

I've confirmed we haven't set a `get_calypso_path` callback on the server side:

https://github.com/Automattic/jetpack/blob/trunk/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L143-L148

But we haven't completely switched to serving URLs from the server side yet, either, and there's no corresponding task action set up here:

https://github.com/Automattic/wp-calypso/blob/trunk/packages/launchpad/src/setup-actions.ts

So we should probably do both to fix this.

This may be more complicated by the fact that I don't think Stripe is supported in all countries, so in some cases we may not want to link to Stripe at all. There's some logic around that for the Launchpad in Stepper on the front end here, directing users to the marketing connections page instead:

https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx#L527-L529

**Comment by sixhours** [comment]
I think this is fixed on the server side; I'm unsure if we need to address it on the client side as well? I'm thinking not, since those should be a fallback for the newer method, right?

**Comment by valterlorran** [comment]
@sixhours can we close this issue? Since we deployed https://github.com/Automattic/jetpack/pull/32526

**Comment by sixhours** [comment]
Yep, I think we can close this! Thanks for the reminder! :D
