### ISSUE TITLE
Assembler: Categories should only show 6-8 patterns by default

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#80726]
## Description

As proposed in pbxlJb-4lf-p2:

> We’ll show a curated 6-8 patterns per category and put the remaining patterns behind a More click. This reduces the cognitive load, while still allowing more curious users to explore a larger selection of patterns.

The pattern curation process is already ongoing. See p1691545917041729-slack-CRWCHQGUB), and https://github.com/Automattic/wp-calypso/pull/80688.

This issue focuses the user experience of only showing the curated patterns by default, while also showing a More button. Clicking the More button would reveal the rest of the patterns in the category.

## Acceptance Criteria

- [x] Update the behavior so that pattern categories only show the curated patterns by default.
- [x] Implement the More button. Clicking the More button shows the rest of the patterns in the category.
- [x] Ensure that the new interactive elements have Tracks events.
- [x] Finalize design with Lucas.

**Comment by taipeicoder** [comment]
@lucasmendes-design could you point me to the design of the More button in the Figma file? Thank you!

**Comment by lucasmendes-design** [comment]
Sure. Here is the image and Figma link. It was hidden behind the frame and dark background. Now it's clearer. 
 
- Show more patterns / Show less patterns. 
<img width="617" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/b13bea11-26a8-4b57-9df5-85d29b56756a">

- In context:  
<img width="1356" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/3b716e12-d2ee-47b9-abf4-ce82c6a1335c">

**Comment by alaczek** [comment]
Now that we have the tags in place, I'm ready to start tagging selected patterns with `Assembler_priority` tag. 
How soon could we have a PR set up so that I could test it live?

**Comment by miksansegundo** [comment]
> How soon could we have a PR set up so that I could test it live?

I'm currently working on it. It'll be ready early next week

**Comment by miksansegundo** [comment]
While working on this, I found that the button `Show less patterns` might not be necessary. The implementation without it is much simpler. cc: @lucasmendes-design @alaczek @taipeicoder 

Please let me know if that works. You can test it on https://github.com/Automattic/wp-calypso/pull/81130

**Comment by arthur791004** [comment]
If the category has only a few patterns or 6-8 patterns cannot take the full height of the panel, it might look a bit weird as there are still lots of spaces after the “Show more patterns” 😓

<img width="300" src="https://github.com/Automattic/wp-calypso/assets/13596067/18d138a8-a8b0-4da9-a3b5-841cf37370d4" />

How about sticking the “Show more patterns” to the bottom of the panel with the background color and avoiding the panel scrollable before clicking the button?

**Comment by miksansegundo** [comment]
> It might look a bit weird as there are still lots of spaces after the “Show more patterns”

I think it's looking fine for this first iteration. The space after the button looks okay to me. 

In follow-up PRs, I'd like to improve the pattern placeholder we show while patterns are still loading.

**Comment by miksansegundo** [comment]
After discussing, I understand better now @arthur791004's concern about the space. Some categories, such as header and footer that have mostly short-height patterns, leave so much empty space compared to others.

The good news is that we can easily control the look per category as part of the curating process. For instance, tag more header and footer patterns as `Assembler_priority`.

|Header|Contact|
|--|--|
|<img width="696" alt="Screenshot 2566-08-29 at 11 21 28" src="https://github.com/Automattic/wp-calypso/assets/1881481/1c73cee9-ba16-4f12-887f-63f4ea2a40c5">|<img width="696" alt="Screenshot 2566-08-29 at 11 21 16" src="https://github.com/Automattic/wp-calypso/assets/1881481/ca8b9af5-0e68-4f8b-bf25-c2612fb10a1a">|

**Comment by miksansegundo** [comment]
> How about sticking the “Show more patterns” to the bottom of the panel with the background color and avoiding the panel scrollable before clicking the button?

We can implement this version to test it. If the priority patterns show on top and below them we fill the panel with some non-priority patterns, users won't be able to scroll to see more patterns until they click on `Show more patterns`, which is mostly the same as currently on production but forcing users to click on a button rather than just keep scrolling freely.

**Comment by lucasmendes-design** [comment]
> If the category has only a few patterns or 6-8 patterns cannot take the full height of the panel, it might look a bit weird as there are still lots of spaces after the “Show more patterns”

I agree with that.

> How about sticking the “Show more patterns” to the bottom of the panel with the background color and avoiding the panel scrollable before clicking the button?

In some cases, we'll show very few options like 3 or 4.  I don't think this is ideal. 

For headers and footers we can show all by default (or 12-16 pattenrs e.g.). For the other categories, we show 8 patterns. 

I checked all categories and the only ones that might be affected by height are headers and footers. There could also be issues with very large screen sizes, but I believe it should be manageable.

**Comment by miksansegundo** [comment]
I have tagged all headers (19) as `Assembler_priority` and updated the publish date of the six patterns that were prioritized initially because now the most recently saved patterns go on top of the list. 

I decided to put the headers with social icons and buttons on the very top. Let me know if that works.

|BEFORE - Only six prioritized|AFTER - All prioritized|AFTER - Updated order with publish date|
|--|--|--|
|![image](https://github.com/Automattic/wp-calypso/assets/1881481/0d4b128f-e2ad-4bc3-8c27-09cbe36ab7d5)|<img width="700" alt="Screenshot 2566-08-30 at 11 09 50" src="https://github.com/Automattic/wp-calypso/assets/1881481/bbcf2c3d-858f-4a51-928e-fae31b737842">|<img width="696" alt="Screenshot 2566-08-30 at 11 14 24" src="https://github.com/Automattic/wp-calypso/assets/1881481/d9c1429d-692a-460a-b8f0-71e06a6fac41">|

**Comment by miksansegundo** [comment]
I have done the same to Footers (19).

|BEFORE|AFTER|
|--|--|
|<img width="696" alt="Screenshot 2566-08-30 at 11 36 12" src="https://github.com/Automattic/wp-calypso/assets/1881481/d7b5de4d-fa7c-4c9d-b43a-a631256db138">|<img width="697" alt="Screenshot 2566-08-30 at 11 58 16" src="https://github.com/Automattic/wp-calypso/assets/1881481/96fd0d7c-2ce1-417b-b769-45a7c3d3d266">|

**Comment by arthur791004** [comment]
> I have tagged all headers (19) as Assembler_priority and updated the publish date of the six patterns that were prioritized initially because now the most recently saved patterns go on top of the list.

We have to document the above behaviors somewhere and then we can follow the document to add the new headers/footers 😉

> I decided to put the headers with social icons and buttons on the very top. Let me know if that works.

I assume this is very fragile. When we publish a new pattern, we have to re-publish all of those patterns 😅

**Comment by miksansegundo** [comment]
> I assume this is very fragile. When we publish a new pattern, we have to re-publish all of those patterns 😅

Yes, that's right. Newly published patterns will appear at the top which can be a good thing too 😉

> We have to document the above behaviors somewhere

Sure! I have pending to write a post documenting how the ordering works and the new tags `Assembler` and `Assembler_priority`

**Comment by miksansegundo** [comment]
Shipping https://github.com/Automattic/wp-calypso/pull/81130
