### ISSUE TITLE
Fullpost refresh: More in Site: Fade site name

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8072]
In the refreshed fullpost, in the "More In Site Name" block, if the site name is super long, fade it at the right edge so it does not wrap.

Example post: https://wpcalypso.wordpress.com/read/blogs/77147075/posts/195
(Thanks for the great test post, @blowery.)

![screen shot 2016-09-13 at 12 11 28 pm](https://cloud.githubusercontent.com/assets/24388/18487853/af68c1dc-79ab-11e6-898d-5c966e1e2863.png)

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/8090
