### ISSUE TITLE
Fullpost Refresh: No-avatar sidebar spacing issue

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8073]
When a fullpost has no avatar, the name should be on the same baseline as the headline.

Example: https://wordpress.com/read/blogs/64518624/posts/2919

So this:
![screen shot 2016-09-13 at 12 22 59 pm](https://cloud.githubusercontent.com/assets/24388/18488128/f21d1bf8-79ac-11e6-92b2-ded28956f33f.png)

Should be this:
![screen shot 2016-09-13 at 12 23 42 pm](https://cloud.githubusercontent.com/assets/24388/18488131/f6ee8c16-79ac-11e6-813a-c86ab2edd2e5.png)

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/8094
