### ISSUE TITLE
PressThis bookmarklet is trying to embed link, not paste highlighted text

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#80742]
### Quick summary

We announce that [PressThis ](https://wordpress.com/support/press-this/)works for any website.
Yet, at the moment, it isn't working.
Though @galakhyati reported it worked for WordPress.com websites when they tested.

### Steps to reproduce

1. Add the PressThis bookmark
2. Go to any website
3. Highlight your text and click PressThis
4. Notice how it opens an empty post

### What you expected to happen

The selected text to be in the new post and ready to be shared and edited.

### What actually happened

It loaded an empty draft post.

https://github.com/Automattic/wp-calypso/assets/2540430/6f5647f9-3fb6-4ed2-af7d-ecfdf0d2d2fc

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

6639663-zen-a8c

**Comment by dev-sabbir** [comment]
I have tested this with a site that is not hosted at WordPress.com, and the button is somewhat working. I said somewhat because, even though I selected some text and then pressed Press This, it embedded the page(instead of the selected text) on a new post on my site. 

Besides I had to wait for while for the process to complete, there were multiple redirects.

I am using Google Chrome Version 115.0.5790.170 (Official Build) (x86_64).

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated** - somewhat
- Tested on Atomic – **Replicated** - somewhat

📌 FINDINGS/SCREENSHOTS/VIDEO
- My findings reflect the same as @dev-sabbir - the Press This bookmarklets for both simple and atomic sites are just embedding the link of the site I'm trying to Press This.  The result in the pop up new post is an attempt to embed the link, not copy the content itself.  Sometimes that worked and the page embedded (such as https://wordpress.org/news/2023/08/lionel/ or https://longreads.com/2023/08/17/lorne-michaels-saturday-night-live/ ) while other links failed to embed (including https://en.wikipedia.org/wiki/Cat and https://ma.tt/ )

#### Screenshots/Recordings

**LongReads.com**

https://github.com/Automattic/wp-calypso/assets/27249804/ed8c885d-70f5-49c9-9244-398943259b27

**Wikipedia.com**

https://github.com/Automattic/wp-calypso/assets/27249804/0446e883-74f4-45a0-973f-8372958c7e27

📌 ACTIONS
- Assigned to @Automattic/loop

**Comment by davemart-in** [comment]
Hmm... Yeah, we removed the code to display anything but the embed, though I suspect we should have retained the code that checks to see if there was highlighted text on the page. I will add this to an upcoming bug scrub project thread that I'm pulling together for our team. Thanks for the report!

cc @Addison-Stavlo

**Comment by cuemarie** [comment]
Hey @roo2 ! I see this is working now on my Simple (Premium Plan) site, but not my AT test site.  Should the fix #80840  have addressed both environments? 

Here's the bookmarklet for my AT site, added to my bookmarks today:

`
javascript:( function(e){const t=document,s=window,i=s.getSelection,o=t.getSelection,n=t.selection,a=t.location;let r;r=i?i():o?o():n?n.createRange().text:"";const c=e+"?url="+encodeURIComponent(a.href)+"&title="+encodeURIComponent(t.title)+"&text="+encodeURIComponent(r)+"&v=5",d=function(){s.open(c,"t","toolbar=0,resizable=1,scrollbars=1,status=1,width=660,height=570")||(a.href=c)};/Firefox/.test(navigator.userAgent)?setTimeout(d,0):d()} )( 'https://wordpress.com/post/atbugtesting.work' )
`

## Screenshots

**Simple**
![Markup on 2023-08-22 at 10:08:00](https://github.com/Automattic/wp-calypso/assets/27249804/59ea29b8-1dee-46f1-b158-c31b6f69f9f6)

**AT Site**
![Markup on 2023-08-22 at 10:08:27](https://github.com/Automattic/wp-calypso/assets/27249804/a2372675-5739-4f0c-b753-284d43a451ec)
