### ISSUE TITLE
Image Editor: new image should copy meta info from old image

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#8074]
As [mentioned here](https://github.com/Automattic/wp-calypso/issues/7989#issuecomment-246416361), when someone edits an image, we create a duplicate of the image along with a duplicate record. But the duplicate does not retain the original image's meta information. It should copy over the caption, alt text, and description from the original image.

**Comment by gwwar** [comment]
This should also be fixed after implementing #8081
