### ISSUE TITLE
Image Editor: exiting image-editing via Done should take you to image details

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#8075]
Currently the only way to get to the image-editing modal is through the image details modal. If you open the image-editor modal and cancel out, you go back to the image-details modal as you would expect. But if you open the image-editor modal and click "done" after making changes, you are taken to the media gallery modal and you bypass the image details modal entirely.

**Comment by gwwar** [comment]
This should be fixed when we implement #8081
