### ISSUE TITLE
Limit access to stats for Author and Contributor user roles

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#8078]
In Calypso, it is possible to see the stats pages for a site you have been invited to contribute to, regardless of user role.  For Admins and Editors this makes sense, but for authors and contributors is accessing a site stats page necessary?  

Site owners may feel this information to be sensitive enough to limit access, so maybe we should consider blocking access to it at the lower user roles?

Inspired by user feedback in #2830604-t

**Comment by crunnells** [comment]
Just had another request for this by a user in chat (#466288-hc). This would be a great addition, especially since the option to limit stats to specific user roles is available in Jetpack on WordPress.org.
