### ISSUE TITLE
Preview shows a 404 error on unsaved posts for Simple sites

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#80788]
### Quick summary

Unsaved pages on simple sites get a 404 error when previewing on a new page. 

I assume its because a permalink has not been assigned yet.

This looks like a new development, as you always used to be able to preview regardless. 

Only seems to affect Simple sites. 

Video;

https://github.com/Automattic/wp-calypso/assets/5075840/be09e6ea-b04e-4776-8a19-43e79fd79a08

### Steps to reproduce

1. Open a simple site and create a new post
2. Don't save it as a draft or publish
3. Type a few words and click the 'preview in new tab' button
4. The preview will show as 404

### What you expected to happen

The preview should show

### What actually happened

404 error

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes
Workaround is to save as a draft.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated** 
- Tested on Atomic –Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described. As soon as the post is saved as a draft, the preview opens as expected.
- On AT, it seems that previewing the post in a new tab forces the content to save as draft; when I return to the editor, I can see that it has saved. 

#### Screenshots/Recordings

**Simple Site - Replicated**

https://github.com/Automattic/wp-calypso/assets/27249804/732a346d-9d6f-4b62-b08d-fb6c633ec012

**Atomic Site - Issue does not occur**

https://github.com/Automattic/wp-calypso/assets/27249804/39a83992-35a8-421c-a293-cc9e458812dc

📌 ACTIONS
- This appears to be a duplicate of: https://github.com/Automattic/wp-calypso/issues/68071
- That report has been open for a while, and did not clarify that _unsaved_ posts were where the issue lay, though it look like that was the case in the triage notes: https://github.com/Automattic/wp-calypso/issues/68071#issuecomment-1262719207
- Leavings this open for now as a more accurate description of the issue.

**Comment by cuemarie** [comment]
9 Interactions noted on the closed #68071 spanning from October 2022 to end of July 2023

**Comment by villanovachile** [comment]
Another report: 6806737-zen
Browser: Safari
OS: macOS Ventura

Provided workaround to preview from the Pages/Post list

**Comment by villanovachile** [comment]
Another report: 7132586-zen
Browser: Safari & Firefox (doesn't occur in Chrome)
OS: macOS 13.5.2 (Ventura)

**Comment by supernovia** [comment]
We have a case in the forums:
https://wordpress.com/forums/topic/preview-link-not-working/

Happens regardless of the browser. If they remove the nonce, it's fine.

**Comment by supernovia** [comment]
This user reached out on Twitter and by ticket; they're sharing a movie of the behavior here:
7138353-zd-a8c

**Comment by supernovia** [comment]
Another case here: https://wordpress.com/forums/topic/preview-desktop/

**Comment by caitlindawn** [comment]
Another case: 7112062-zen

**Comment by synora** [comment]
Another one: 7178297-zen

**Comment by supernovia** [comment]
Another: 7138517-zd-a8c

**Comment by zdenys** [comment]
7506542-zd-a8c Happens on Firefox (Desktop, including Private mode) Safari on iOS. Their post URL includes a nonce string (`&calypsoify=1&block-editor=1&frame-nonce=f81769b024&origin=https%3A%2F%2Fwordpress.com&environment-id=production&support_user&_support_token`)

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/preview-error-4/

User confirmed that preview does not work in Safari and Duck Duck Go, but does work in Firefox and Brave.

Preview URL also includes a nonce string, but previewing from the All Posts view does not contain the nonce, so I suggested this as a workaround.

**Comment by zdenys** [comment]
7880910-zd-a8c Reproducing in Firefox Developer, Firefox, Chrome and Safari. The workaround is not working though.

**Comment by dolgelukkig** [comment]
7894436-zd suggested workaround.

**Comment by philnick206** [comment]
Reported in 7880525-zd-a8c and suggested workaround

**Comment by caitlindawn** [comment]
Reported in 8176488-zd, suggested workaround.

**Comment by kelasante** [comment]
Another report in 8212051-zd

**Comment by BogdanUngureanu** [comment]
I'm not able to reproduce it anymore with Gutenberg 16.9.0. Closing this
