### ISSUE TITLE
Stats: change cursor to arrow for step titles when the step is expanded

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80792]
The cursor changes when I hover over 2)What is jetpack Stats worth to you? made me think it is clickable.

Step 1 has the issue too.

pbNhbs-7WU-p2#comment-17525

**Comment by grzegorz-cp** [comment]
Step 1 becomes clickable once you select a type (it's a way to go back), but we can apply a class to change the cursor type until the site type is selected.

**Comment by kangzj** [comment]
closed with #80799
