### ISSUE TITLE
Minor copy changes in Woo Express free trial plans page

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#80809]
Slack: p1692346892285349/1692197659.560069-slack-C03Q87XT1QF

Minor copy changes for Woo Express free trial plans page:

1. Plans > Plans - Essential plan ([1st screenshot](https://user-images.githubusercontent.com/3747241/261580610-53ebaeb2-2ba0-4c00-bdff-383312fc8c7a.png)): replace unlimited premium themes with `beautiful themes`.
2. Plans > Free trial - What's included section ([2nd screenshot](https://user-images.githubusercontent.com/3747241/261580656-de2489f7-de46-4008-8eed-a2f594752b1a.png)): replace premium themes with `beautiful themes`

### Acceptance criteria

1. Copy changes as stated above

**Comment by FlorianBru** [comment]
Hey @ilyasfoo, since this is about copy we need to involve @lauroraa

**Comment by ilyasfoo** [comment]
Actually, since it's a simple copy change, I don't think we'll need feedback on design or copy. Unless @lauroraa thinks otherwise, of course!
