### ISSUE TITLE
Image Editor: certain images in the same library cannot be edited 

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#8080]
#### Steps to reproduce
1. Starting at URL: wpcalypso.wordpress.com
2. Select public site
3. Click New Post
4. Click Add button
5. Upload this image via URL https://davewhitley.files.wordpress.com/2015/06/img_1321.jpg
6. click pencil icon
7. click Edit Image
8. Error message is shown
9. If I choose one of the older images I can edit it.

#### Browser / OS version
Safari 9.1.1
Mac OSX 10.11.5

#### Screenshot / Video
![screen shot 2016-09-13 at 3 50 11 pm](https://cloud.githubusercontent.com/assets/618551/18490924/c54da2f6-79c9-11e6-957b-c2fdb5708f7f.png)

**Comment by gwwar** [comment]
I wasn't able to repro, but we should make sure folks are able to get images back consistently with the expected CORS headers.

**Comment by andrewkolesnikov** [comment]
Unable to repro. CORS shouldn't be an issue here. The submitted image is identical to other images on his blog, e.g. **https://davewhitley.files.wordpress.com/2015/01/img_0741-0.jpg**

**Comment by artpi** [comment]
a77e34f fixed for me also. Please reopen if bug still there. Thanks @andrewkolesnikov !
