### ISSUE TITLE
DNS: Investigate supporting 2048-bit DKIM keys

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#80819]
### What

I would like the ability to allow for TXT records longer than 255 characters, which would enable support for a more secure 2048-bit DKIM key.

### Why

1024-bit security keys, which are the longest security keys that will fit in a 255-character TXT record, have been discouraged [since 2014 for SSL certificates](https://www.namecheap.com/support/knowledgebase/article.aspx/9783/38/1024-bit-certificates/), as well as more generally [by the NIST](https://crypto.stackexchange.com/questions/10700/when-nist-disallows-the-use-of-1024-bit-keys-what-effect-will-that-have-on-sha). Some email providers, such as the one used by our user in 6685037-zd-a8c, are refusing to be backwards compatible for security reasons. Allowing for a longer TXT record, therefore, will by default make our users' DKIM keys more secure.

### How

Google suggests one way [and provides examples](https://support.google.com/a/answer/11613097?hl=en), which is to split a longer key into 255-character chunks (each individually quoted). If extending the length of this record type is not possible, can we support splitting records as described in the Google example?

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by DavidSaladu** [comment]
This customer insisted on it as well 6711206-zd-a8c

**Comment by cuemarie** [comment]
FYI @Automattic/nomado - would y'all know if is this on the horizon for domains?

**Comment by delputnam** [comment]
This is a limitation of our current version of PowerDNS. Systems is working to migrate to the new version. Once that cutover is complete, we can remove the 255 character limit on TXT rdata.

Splitting records into multiple "chunks" won't work on this version of PDNS either.

(This cutover is also related to DNSSEC support.)

**Comment by jamiepalatnik** [comment]
Another request in this chat: 7131931-zd-a8c

**Comment by delputnam** [comment]
Still awaiting the PDNS migration.

**Comment by i11za** [comment]
Another request in this chat: 7227680-zd-a8c

**Comment by filipanoscampos** [comment]
Another one 7235803-zd-a8c

**Comment by nightnei** [comment]
@delputnam I remember we removed 255 limitation on Tumblr. So I wanted to ask - does it mean that we can do the same for wp.com? If so, and if you have bandwidth - add it please to your board or if you don't have bandwidth - I will do it.

**Comment by delputnam** [comment]
@nightnei This restriction has already been removed on WPCOM. Sorry that we never updated this issue.  I'll go ahead and mark it closed.
