### ISSUE TITLE
Image Editor: Change Behavior to Update Media Rather than Upload a New Copy

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8081]
If we have the ability to restore an image to it's original value ( #8082 ), let's change the current behavior from uploading a new copy, to instead updating the current media item.

Major flow changes:
1. After we click done in the image editor we should update the media item with the new image value
2. After done is clicked, we can exit to the media detail page. We no longer need to go back to list view (since we're not uploading an extra media item).

**Comment by gwwar** [comment]
Note that this is blocked by https://github.com/Automattic/wp-calypso/projects/4#card-264881

**Comment by retrofox** [comment]
Close with #8945
