### ISSUE TITLE
Image Editor: Restore Original Image

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8082]
If we do destructive updates in ( #8081 ) we should allow the user to restore the original copy if they didn't like their previous edits. 

cc @adambbecker and @drw158 for where this button might be located.

**Comment by rralian** [comment]
We can detect an edited image based on the "guid" and "URL" values of the media item. See my comment here for details. https://github.com/Automattic/wp-calypso/issues/8079#issuecomment-246832953

**Comment by drw158** [comment]
Maybe something like this

![screen shot 2016-09-26 at 11 25 39 am](https://cloud.githubusercontent.com/assets/618551/18842843/0b192ff0-83dc-11e6-98b1-2d7f52cae8d8.png)

I'm concerned if placed in the editor, then it would be confused with Reset, which only resets the current edits. Perhaps "Undo Edits" would be better wording there instead of Reset.

Google Photos is a bit nicer, but I'm not if we can do it. Whenever a photo is opened in the editor, the edits are retained, so it's just a matter of undoing the edits to restore the original image. In other words, you can't open an image and edit it again on top of your previous edits.

**Comment by gwwar** [comment]
@drw158 Do you mean undoing state in a single editor session or enabling media versions (being able to restore across multiple saves).

The first could be implemented without too much fuss in a v2 iteration, while the latter would require a decent amount of api/ui work

**Comment by drw158** [comment]
The google photos thing would be something in-between. It's not just a single editor session but there are no media versions, at least not shown to the user. It looks like there are only 2 states, the original and the edited version. Meaning, there is no restoring across multiple saves. For example, for us, when a photo is opened back up after cropping, the crop handle placement would need to be retained and the image outside of the crop box still there.

Hard for me to explain but here is a gif.

![screen recording 2016-09-26 at 02 45 pm](https://cloud.githubusercontent.com/assets/618551/18849340/2829e050-83f8-11e6-8ce6-ae7558b2b670.gif)

**Comment by retrofox** [comment]
> We can detect an edited image based on the "guid" and "URL" values of the media item. See my comment here for details. #8079 (comment)

@rralian If I'm not wrong the `guid` never changes. On other hand, I've been working on a new version of update media endpoint which handles this issue stylishly. 🍷

**Comment by hoverduck** [comment]
Just wanted to make a note that the current implementation of this puts the "Restore Original" button on an image forever, even after you've used it to discard your edits.  This leaves you with a button that doesn't do anything.

**Comment by gwwar** [comment]
> Just wanted to make a note that the current implementation of this puts the "Restore Original" button on an image forever

Thanks @hoverduck it's a known limitation. We will correct in the future, but requires an additional endpoint. This seemed too minor atm to block for a v1.

> This leaves you with a button that doesn't do anything.

At the moment restoring is an edit, but it uses the original content. So clicking the button will always generate a new file url.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

I briefly checked and it appears that the current image editor supports restoring the original image. The issue described in subsequent comment that an edited image restored to original will always show `restore original` remains and should be filed as a separate bug.

As the main intention of this issue has been addressed, I would like to close this issue with the label `Closed - Fixed`.
If work is scoped and tabled for a milestone, please feel free to re-open this bug.
