### ISSUE TITLE
Cannot remove redirect once set as primary

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/wp-calypso#80835]
### Quick summary

A customer purchased a plan and registered a new domain on an existing site. After that it appears they setup the redirect from their new domain to their old domain unintentionally.

When we transferred their plan and domain to a new site on their account, I set their custom domain as the primary. In doing so, the redirect remained in place and the option to remove the redirect was disabled.

### Steps to reproduce

1. Set the default `.wordpress.com` address as primary
2. Setup a redirect on the custom domain
3. Set the custom domain back as primary

### What you expected to happen

When a custom domain is set as the primary, the customer should get the option to remove the domain redirect, or it should be automatically removed.

### What actually happened

The redirect remained in place for the domain, and the ability to remove the redirect was disabled. The only way to resolve this was to reverse the steps:

1. Set the default `.wordpress.com` address as primary
2. Remove the redirect on the custom domain
3. Set the custom domain back as primary

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

It seems like this only happens on Simple sites. I tested on an Atomic site and the redirect did not happen when following the steps to reproduce.

**Comment by DustyReagan** [comment]
With the addition of this diff: D119391-code domains set as the primary site address should now ignore any and all redirect rules. Note that any old existing redirect rules are not deleted, but instead, they are ignored.

**Comment by paulopmt1** [comment]
We've [created a frontend task](https://github.com/Automattic/wp-calypso/pull/80868) for disallowing redirects to wordpress.com URLs.

We currently have 36 redirects to .wordpress.com domains (wpsh command: `gpr select blog_id, domain, target_host from domain_redirects where target_host like '%wordpress.com';`):

<img width="1298" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1044309/4f87258b-59d2-4b5c-99eb-fba718186798">

**Comment by DustyReagan** [comment]
I'm closing this issue because D119391-code should resolve it. Please feel free to reopen if not.
