### ISSUE TITLE
Theme SND is rendered right-to-left in the logged-out Theme Detail page

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#80843]
## Description

As mentioned in p1692333989441939-slack-CRWCHQGUB, the theme SND is rendered right-to-left while the user is logged out. Note that this does not happen when the user is logged in. See screenshot for reference:

![Image](https://user-images.githubusercontent.com/797888/261931728-36021dae-cbfb-4620-82e9-76f263ef0192.png)

The issue is caused by the theme slug `snd` being wrongly parsed as a locale (Sindhi). 

## Acceptance Criteria
- [ ] The Theme Detail page should correctly parse the locale from the URL.
- [ ] The theme SND should only render right-to-left on the appropriate locales.

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/80958
