### ISSUE TITLE
Post Link Tracking: store URL info and create redirection URL

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#80863]
At the time of creating the email to be sent, we parse all the links found in the body of the post, and we do two things with them:

a) We store the URLs with a generated UUID in the `email_link_mapping` table.
b) We generate tracking URLs containing those UUIDs and use those in the email instead of the original URLs.

This code will live in the WPCOM code base.

**Comment by yansern** [comment]
Completed with D119442-code
