### ISSUE TITLE
Fullpost Refresh: More on WP: Author avatar and text slightly misaligned

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8087]
File this under "sweating the details."

On the refreshed fullpost, in the More on WP block, the author name/site/follow text are slightly misaligned with the gravatar. The text needs to nudge up 2px or the gravatar needs to nudge down 2px.

So this:
![screen shot 2016-09-13 at 5 27 58 pm](https://cloud.githubusercontent.com/assets/24388/18496102/f32eac3e-79d7-11e6-8a2c-13b4c7a2b2ba.png)

Should be this:
![screen shot 2016-09-13 at 5 28 31 pm](https://cloud.githubusercontent.com/assets/24388/18496106/f8cf9892-79d7-11e6-8536-737985445dfb.png)

I know, this is crazy nitpicky, but the text looks a little "saggy" as it is right now.

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/8166

**Comment by fraying** [comment]
I'm seeing this again. @jancavan ?

**Comment by jancavan** [comment]
Good catch. I think another change caused a regression. Fixed in: https://github.com/Automattic/wp-calypso/pull/8246
