### ISSUE TITLE
Recognise emails in the link editor?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-calypso#8088]
Dear all, 

Would it be possible for the link editor to recognise if the user pastes an email and automatically prepends   `mailto:` in front of the email instead of `http`?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18513073/295d5e18-7a8c-11e6-9ea3-d7b7c7038818.png)

**Comment by timmyc** [comment]
Closing this out now that #8093 has been merged
