### ISSUE TITLE
WPCOM Paid Stats: Unify upsell nudge events for WPCOM analytics

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80886]

**Comment by kangzj** [comment]
I took a look at the wpcom upsells, which are pretty different visually from our banners and I don't see a big reason to unify the analytics. I'll mark the issue as closed for now.

**Comment by dognose24** [comment]
> I took a look at the wpcom upsells

Do you mean the product cards for purchasing Stats on the `Plans` and `Add-Ons` pages?

**Comment by kangzj** [comment]
> Do you mean the product cards for purchasing Stats on the Plans and Add-Ons pages?

Not really. I meant the upsells for domains, blaze and etc, for example:

<img width="600" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1425433/79b8f83b-0716-45ff-82f5-e69b1be07d74">
