### ISSUE TITLE
WPCOM Paid Stats: "Learn More" link in the Commercial purchase page should lead to WPCOM marketing page for stats for WPCOM sites

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80884]
![Image](https://user-images.githubusercontent.com/1425433/262213609-e5560611-5e57-48d6-8228-fe909a1e5c6c.png)

**Comment by dognose24** [comment]
We may need a support page describing the [difference between Stats plans like Jetpack Stats support](https://jetpack.com/support/jetpack-stats/free-or-paid/) or extend the [Stats support page of WPCOM](https://wordpress.com/support/stats/).

**Comment by kangzj** [comment]
p1HpG7-nXd-p2#comment-65780
