### ISSUE TITLE
WPCOM Paid Stats: "Learn More" link in the upgrade notice should lead to WPCOM marketing page for stats for WPCOM sites

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80883]
pejTkB-Ih-p2#comment-641

![Image](https://github.com/Automattic/wp-calypso/assets/1425433/ed1f9889-d818-45a4-88a0-1568b70d8848)

**Comment by dognose24** [comment]
There exists a [Stats support page](https://wordpress.com/support/stats/) for WPCOM. However, we may need a page [describing Stats upgrades as Jetpack does](https://jetpack.com/blog/changes-to-jetpack-stats-for-commercial-sites/) for WPCOM.

**Comment by kangzj** [comment]
p1HpG7-nXd-p2#comment-65780
