### ISSUE TITLE
Newsletter Categories: Make the Subscribe block category pills interactive in the published content

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#80906]
### Details

Make the Subscribe block category pills interactive in the published content

### Checklist

- [ ] When no specific category is selected, then no opt-outs should be included in the ~subscribe API call~ iframe URL on submit
- [ ] When a category, or categories are selected then they should be included in the ~subscribe API call~ iframe URL on submit

**Comment by yansern** [comment]
> ~subscribe API call~ iframe URL

Updated the PR description to reflect the decisions made here. https://github.com/Automattic/wp-calypso/issues/80903

**Comment by yansern** [comment]
This needs to be done on `render_block`. Take note that there are 2 functions, `render_wpcom_subscribe_form` and `render_jetpack_subscribe_form`. https://github.com/Automattic/jetpack/blob/2c06579677f752616a4aca175ad8a471782212dc/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php
