### ISSUE TITLE
Newsletter Categories: Make the border radius option of the Subscribe block affect the category pills

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#80908]
### Details

Make the border radius option of the Subscribe block affect the border radius of pills as well.

![Markup 2023-08-22 at 12 42 56](https://github.com/Automattic/wp-calypso/assets/2019970/4016993f-860a-470a-8b7a-f9197f5d3609)

**Comment by TimBroddin** [comment]
Related PR. https://github.com/Automattic/jetpack/pull/32666
