### ISSUE TITLE
Newsletter Categories: Create a Newsletter Categories Blog RC sticker

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#80910]
### Details

The sticker should be of equal priority to the Newsletter Categories feature flag. Hence, moving the feature flag to production would make the feature available to all users in production, while Blog RC sticker would be used to make the feature available in production only for a specific site, even when the feature flag is not set to production yet.

### Checklist

- [ ] Make it possible to enable Newsletter Categories for a given site, in production, via the Blog RC

**Comment by TimBroddin** [comment]
Adding a sticker is as easy as running a command on your sandbox: 317f9-pb

**Comment by TimBroddin** [comment]
Checking for a blog sticker: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qoybt%2Qfgvpxref.cuc%3Se%3Q83370pnn%23163-og
