### ISSUE TITLE
Footnotes are saved in revisions in wp-admin but not Calypso

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#80933]
### Quick summary

Recently core added the ability to save/recover Footnotes in post revisions, but this is not happening in Calypso; the footnotes can only be recovered when working within wp-admin.

### Steps to reproduce

1. On a site with WP 6.3 and GB 16.4.0, Open Posts > Add New Post (`https://wordpress.com/post/SITE_ADDRESS`)
2. Add content and multiple footnotes, and **publish** the post
3. Make changes to the content and footnotes (i suggest changing the text in your footnotes so you can easily monitor changes) and **Update**
4. Open Revisions and restore an older revision
     - Observe that the footnotes don't restore to the previous version
5. Exit the post editor, and view the Posts page in Classic view, then edit your post (`https://SITE_ADDRESS/wp-admin/post.php?post=POSTID&action=edit`)
6. Open Revisions here and view/restore older revisions
     - Observe that the footnotes are saved below the content, and restore alongside the content with a revision restore

---

### Screenshots

| wp-admin | calypso |
| ------------- | ------------- |
| ![Markup on 2023-08-22 at 10:48:35](https://github.com/Automattic/wp-calypso/assets/27249804/9b4ad7a2-8745-4685-b700-046daa1c8de0) | ![Markup on 2023-08-22 at 10:49:14](https://github.com/Automattic/wp-calypso/assets/27249804/31a0c514-dbcf-44ef-aefe-3365384482e0) |

Recording from AT Site - comparing wp-admin (first) to calypso (second)

https://github.com/Automattic/wp-calypso/assets/27249804/18253ad8-900b-422e-84ea-fd79bd306178

### What you expected to happen

The footnotes to be restored with my revision when editing in Calypso. 

### What actually happened

Content restores but footnotes do not when editing in Calypso.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Gutenberg Update: https://github.com/WordPress/gutenberg/pull/52686
Core Changeset: https://core.trac.wordpress.org/changeset/56305/branches/6.3/src/wp-includes/blocks/footnotes.php

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – No

📌 ACTIONS
- Shared here to see if anyone can pick this up: p1692738985042079-slack-C01LXBU1N21

**Comment by supernovia** [comment]
Noting we've got a number of users who are getting "this block has encountered an error" type errors on the Footnotes block and can't get their footnotes back, so revisions would be very helpful in these cases.

**Comment by cuemarie** [comment]
@supernovia To help with those cases, if those block errors are new, then those users should be able to recover their footnotes via wp-admin already! _(Posts > Classic View > Edit > Revisions)_ But if the block errors pre-date the GB updates that added Footnotes into revisions, that may not be possible

**Comment by aleone89** [comment]
Adding information from this thread: https://wordpress.com/forums/topic/the-new-footnotes/page/2/?view=all#post-3984692

```
When did you notice that the content went missing?

I saved a draft and they seemed to crash, not allowing me to put any more in and the block said it encountered an error trying to load footnotes. They were there to begin with, I edited them and added text and links. Now even after deleting all of them, saving the page as draft and reloading it, when I add a foot note it only comes up as an * and the footnote block doesn’t change

Also do you have any other posts or pages on your site that do have footnotes still? Or is this an issue with any footnotes on your site?

This was the first time I was using this feature.

I would be happy to upload my Javascript console if that would help you track down the error.
```

**Comment by cuemarie** [comment]
Crossposted the escalation thread here as well: p1693424682170319-slack-C02DQP0FP

**Comment by filipanoscampos** [comment]
Another case: 7090491-zd-a8c

**Comment by BogdanUngureanu** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/93677
