### ISSUE TITLE
Plans 2023 UI: Discounts in comparison grid cause content overflow on mobile

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#80941]
### Quick summary

If on a mobile device, when prices are discounted for plans, content may overflow from the comparison grid table. Note that, depending on the resolution and dimensions of the mobile device, the content may not appear to be overflowing at all.

![image](https://github.com/Automattic/wp-calypso/assets/5414230/7a31a1b1-977b-4420-bb9e-a4d8b740fd56)

### Steps to reproduce

1. Switch account to use a discounted currency ( INR, MXP, etc. )
2. Navigate to wordpress.com/start
3. Select a domain
4. In chrome dev tools, emulate an `iphone SE`
5. On the plans page, scroll down to the bottom of the page and click on the "Compare plans" button
6. Verify that content is overflowing

### What you expected to happen

Content would be visually contained within the boundaries of the comparison grid

### What actually happened

Content overflowed outside of the comparison grid

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested in Firefox & Chrome using dev tools with INR set as currency. 
- Tested on mobile Safari with INR and MXN set as currency, both in portrait & landscape orientation as part of the 2023 Pricing optimization work. 

📌 ACTIONS
- Wasn't able to repro, but it looks like this is expected, so leaving open for further investigation.

**Comment by jeyip** [comment]
**Note:**

The overflow is caused by _both_ the `One time discount` label and the inline header price and discounted price.

<img width="435" alt="Screenshot 2023-08-24 at 1 51 34 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/2bd5b484-eebd-4104-8dc3-bf4633bb94cf">
