### ISSUE TITLE
Assembler: Align the Activate this Theme step back button with i4

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#80947]
## Description

As discussed in https://github.com/Automattic/wp-calypso/issues/80679#issuecomment-1688165843, the Activate this Theme confirmation step will be shown when users access the Assembler via the logged-in Theme Showcase. Thus, we need to align the back button of this step with the new steps introduced in the Assembler i4.

| Activate this theme | Great job! | Custom styles
| --- | --- | --- |
| ![Image](https://user-images.githubusercontent.com/797888/262526729-24f40c15-5aee-4f15-be0b-1651ab4cae6a.png) |![Image](https://user-images.githubusercontent.com/797888/262526967-4ecc96ee-930b-41c0-9ff1-24b004fde809.png)| ![Image](https://user-images.githubusercontent.com/797888/262526973-f473d609-53af-452a-b335-ed082e411e60.png)|

@lucasmendes-design 

## Acceptance Criteria
- [ ] The back button for Activate this Theme should be aligned with the new steps.

**Comment by arthur791004** [comment]
Actually, I'd prefer the back button next to the WordPress logo as it looks better 😉

**Comment by taipeicoder** [comment]
I'm happy as long as it's consistent 🙂
cc: @lucasmendes-design

**Comment by lucasmendes-design** [comment]
> Actually, I'd prefer the back button next to the WordPress logo as it looks better 

It's good to me this way. We can use as following:
- Back to the themes gallery
- Back to patterns
- Back to styles

Let's make this copy consistent throughout the flow :)

**Comment by taipeicoder** [comment]
Closing this via https://github.com/Automattic/wp-calypso/pull/81069.
