### ISSUE TITLE
Email: The primary CTA is comment and not Read More

### ISSUE THREAD

**Issue by mikestottuk** [Automattic/wp-calypso#80963]
### Quick summary

When creating a post with a read more section - the email rightly shows only the part above read more. However the main button CTA is on someone to comment - vs go to the post to read it.

I feel the focus should be on the Read post.

<img width="845" alt="Screenshot 2023-08-23 at 10 47 56" src="https://github.com/Automattic/wp-calypso/assets/4077604/7c3a9758-d1ce-4560-a6c3-24edef98c978">

### Steps to reproduce

Have a site with comments turned on:-

1. Create a new post
2. Add a read more divider
3. Send a test email

The Comment CTA is a button, the read more is just a link.

### What you expected to happen

The Comment CTA is a link, the read more is a primary button

### What actually happened

The comment CTA is a button and read more a link

### Impact

All

### Available workarounds?

There is no user impact

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described!  

**Atomic**
![Markup on 2023-08-23 at 11:28:35](https://github.com/Automattic/wp-calypso/assets/27249804/f99dce30-775d-4c14-9806-b3b28c840431)

**Simple**
![Markup on 2023-08-23 at 11:27:59](https://github.com/Automattic/wp-calypso/assets/27249804/86c5a7b9-9a8d-47e0-a60a-2adf14de7113)

📌 ACTIONS
- Set to In Progress

**Comment by crisbusquets** [comment]
Design proposal.
* I removed the `Comment` and `Like` options because it seems unlikely someone will comment or like a text that hasn't been fully read yet.
* Left the tip reminding they can comment by replying to that email

<img width="1097" alt="Screenshot 2024-02-21 at 09 18 40" src="https://github.com/Automattic/wp-calypso/assets/25607244/55a07447-6a16-4d2a-8440-c16dfa5b913d">

**Comment by crisbusquets** [comment]
> Design proposal.
> 
> * I removed the `Comment` and `Like` options because it seems unlikely someone will comment or like a text that hasn't been fully read yet.
> * Left the tip reminding they can comment by replying to that email
> 
> <img alt="Screenshot 2024-02-21 at 09 18 40" width="1097" src="https://private-user-images.githubusercontent.com/25607244/306548049-55a07447-6a16-4d2a-8440-c16dfa5b913d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDM5MDgsIm5iZiI6MTcwODUwMzYwOCwicGF0aCI6Ii8yNTYwNzI0NC8zMDY1NDgwNDktNTVhMDc0NDctNmExNi00ZDJhLTg0NDAtYzE2ZGZhNWI5MTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA4MjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZTQ0NGVlZGU2NzY5OTE1MGNlOGRlNDNkOTE0Njg4Njk0NjJmOGQyNzY2YTVmZWJlNzQwZGY3NWJmN2M1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DoSKHTTdDLs2mGijQTiAlqLaHrxCOMSP-AQRBqaHVB4">

**Comment by simison** [comment]
Something to test;
How does the email now look when you enter custom “more” label to the block
How does email look with “next page” block instead of more block

**Comment by enejb** [comment]
@simison and @crisbusquets 
I have a solution for this please see - D148742-code

**Comment by crisbusquets** [comment]
> @simison and @crisbusquets I have a solution for this please see - [D148742-code](https://href.li/?https://code.a8c.com/D148742)

Thanks @enejb !

In the design, I included a reminder that replying to the email would send a comment. However, with the recent `Reply-to` changes, this may not be valid in all cases.

Should we keep the `Leave a comment` as a link below the CTA, in case the site owner disables the reply to comment?

**Comment by simison** [comment]
> In the design, I included a reminder that replying to the email would send a comment. However, with the recent Reply-to changes, this may not be valid in all cases.

@crisbusquets  We're currently hiding the reminder when "reply to" is set to an email.

Do you mean adding "comment" link next to the "read more" CTA but not as a button but as a link, similar to "Like" button?

**Comment by simison** [comment]
Added some test screenshots in D148742-code

@enejb  Currently the button is "Read more of this post" instead of Cris's design "Continue reading". Continue is better, where's the "Read more..." thing coming from, core?

<img width="208" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/e524174a-dd81-4e5c-9738-4003f72ed572">

<img width="225" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/a383cb8a-c98b-4ed7-893f-2909c8eb682f">

**Comment by crisbusquets** [comment]
> > In the design, I included a reminder that replying to the email would send a comment. However, with the recent Reply-to changes, this may not be valid in all cases.
> 
> @crisbusquets We're currently hiding the reminder when "continue reading" is set to an email.
> 
> Do you mean adding "comment" link next to the "read more" CTA but not as a button but as a link, similar to "Like" button?

Yes :)
Does it make sense?

**Comment by simison** [comment]
I think so! 👍 Should we also keep the like CTA? We'd end up with:

Read more (primary) | Comment | Like

**Comment by lezama** [comment]
> I removed the Comment and Like options because it seems unlikely someone will comment or like a text that hasn't been fully read yet.

I vote for this :)

**Comment by simison** [comment]
Shipped!

<img width="1381" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/8f2a9bcd-7acf-46d2-923a-d5efab94a1af">
