### ISSUE TITLE
My home: android app badge missing

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#80962]
### Quick summary

I get different looking app nudge in Firefox and Chrome. Android badge is missing on Firefox, and Apple badge is very big.

**Firefox**

<img width="1618" alt="Screenshot 2023-08-23 at 12 52 03" src="https://github.com/Automattic/wp-calypso/assets/87168/6f9af1a0-4bb9-440e-8c71-b77e3c6dc8d7">

**Chrome**

<img width="1609" alt="Screenshot 2023-08-23 at 12 51 49" src="https://github.com/Automattic/wp-calypso/assets/87168/5cc2c9a1-2b08-4b3d-9c4d-9cf7ea2b9857">

### Steps to reproduce

1. Have a new site (I created mine via logged out `/themes` so I'm still getting non-launchpad my home)
2. Look at my home in Firefox and Chrome
3. See different app nudges

### What you expected to happen

Both app nudges (apple & android) or the link.

### What actually happened

Different experience on each browser.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
@daledupreez @antonis could one of your teams look into this?

**Comment by daledupreez** [comment]
@Automattic/serenity will most likely be able to dig into this next week, unless someone has some cycles in the next day or two.

**Comment by simison** [comment]
FYI If I remember right, problems at this nudge affect the app download stats _a lot_.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
On my simple and AT test sites, I see the same thing in both browsers - the link, not the App store download button.

![Markup on 2023-08-23 at 17:44:25](https://github.com/Automattic/wp-calypso/assets/27249804/ec104e75-5c30-4965-af25-ffddbb87e2b1)

I also created a new site via the logged out `/themes` page, but I'm still seeing only the link on Firefox & Chrome. 🤔 

📌 ACTIONS
- Leaving open for @Automattic/serenity or others to check out. 

📌 Message to Author
- @simison are you seeing the same result on all your sites, or just this one?
