### ISSUE TITLE
Migration trials: Upgrade your plan step has text that is not centered

### ISSUE THREAD

**Issue by jeroenpf** [Automattic/wp-calypso#80965]
On the 'Upgrade your plan' step in the migration trial onboarding, the text under the heading and subheading is not centered. It looks a bit off and should be centered.

![Image](https://user-images.githubusercontent.com/10244734/262662895-f609b75c-cfd2-43b8-92a1-6bc625d1e62a.png)

**Comment by bogiii** [comment]
Interesting... following Figma design, the paragraph is not centered, but the width is lower than the container below.


![Image](https://github.com/Automattic/wp-calypso/assets/1241413/ac692440-9c39-4164-a69b-248dedc1b784)

**Comment by bogiii** [comment]
Hey @javierarce,

What do you think about the unifying paragraph width of the "Upgrade you plan" and "Try before you buy" screens?
It doesn't need to be centered, but the full width make sense to me.

<img width="1694" alt="Screenshot 2023-08-28 at 12 27 27" src="https://github.com/Automattic/wp-calypso/assets/1241413/6e6ff314-ff3c-4e43-82ac-739c169151bd">

**Comment by javierarce** [comment]
Yes, let's change it to full width. I'll update the design.
