### ISSUE TITLE
Paid Content Block - Subscriber Unable to View Premium Content, Stuck on Guest View, Log In Button Disappears

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#80974]
### Quick summary

Possible bug with the WordPress.com Paid Content Block (formerly Premium Content Block). After logging in, the subscriber is shown the Guest View instead of the Subscriber View. As well, the Log In button disappears, and a parameter 'token' is added to the URL.

### Steps to reproduce

1. Create a Paid Content subscription on a site and add a Paid Content Block to a page
2. Add a subscriber to the subscription
3. In a Private window, access the page with the Paid Content Block, then attempt to log in.

### What you expected to happen

The subscriber content should be shown

### What actually happened

The guest content is shown. As well, the Log In button disappears, and a parameter 'token' is added to the URL.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

I reproduced on my own test site. I have only tested and reproduced on Simple sites so far. I did test across multiple themes.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
I tested this on a brand new site, with a new connection to Stripe, and then a new subscriber. 
After subscribing, I opened a new incognito window in Chrome and logged in to my subscriber's account, and could access the subscriber content as expected.

> and a parameter 'token' is added to the URL.

This does occur for me, but I can see the correct content, so this may not be related.

### Recording

https://github.com/Automattic/wp-calypso/assets/27249804/9a041b19-f908-48c9-88fb-d60515aad440

Tested on:

- Premium Plan Site created today; Stripe account created today
- TT3 Theme
- Chrome Version 116.0.5845.110 (Official Build) (x86_64)
     - Under `chrome://settings/cookies`, **Block third-party cookies in Incognito** is enabled 
     - Under `chrome://settings/security`, **Standard Protection** is enabled

📌 ACTIONS
- Requested author feedback

📌 Message to Author
@masperber can you have a look at my recording & notes above and let me know if anything differs in our tests?  If not, it seems like something more specific than a blocker bug with the Paid Content block itself is going on here, and we'll need to do some additional digging 🤔

**Comment by masperber** [comment]
Hey @cuemarie !

Yes, the process you followed seems identical to the process that I followed, but the results are different.

Here is a link to the interaction: 6711609-zen

I'm going to create a P2 post for further investigation, and the link will be in the interaction notes.

(I really enjoyed the GIFs that you used for your testing pages, by the way! 😂 )

**Comment by cuemarie** [comment]
This has been moved to an internal P2 for further investigation: p2EDhh-23L-p2

📌 ACTIONS
- Closing as not reproducible
- Feel free to reopen if the P2 investigation helps uncover a bug/consistent steps to replicate!

**Comment by the-misha** [comment]
Another, possibly related issue: 6717360-zd-a8c

User in chat is reporting their newest subscriber can't view Paid Content when logged into their WPCOM account. Confirmed this by logging in as subscriber. Checked another subscriber as well, which worked without a problem.

**Comment by cuemarie** [comment]
Hey @Automattic/gold ! 👋 I wasn't able to reproduce this in triage or find a duplicate issue, but it seems like it might not be user-specific, and I feel like y'all may have come across this kind of issue before. Can you take a look?

**Comment by millerf** [comment]
👋 

> and a parameter 'token' is added to the URL.

That is totally fine.

I'll follow up on the P2: p2EDhh-23L-p2

**Comment by ha-un** [comment]
Similiar issue: 6728207-zd-a8c

When viewing as a subscriber, login button appears but after clicking on it, the button disappears and still shows guest view content. Confirmed contents were set up correctly.

**Comment by cuemarie** [comment]
Thanks for looking into this one @millerf ! 

📌 ACTIONS
- Triage completed (for now, but please ping me if I can help with any repro tests following further investigation!)

**Comment by the-misha** [comment]
User in 6717645-zd-a8c let us know their subscriber was able to get in the following day. Possibly it took a day to add the access to their WPCOM account...?

**Comment by millerf** [comment]
> User in 6717645-zd-a8c let us know their subscriber was able to get in the following day. Possibly it took a day to add the access to their WPCOM account...?

It could eventually happen if they had a delay in the Jetpack sync (provided they were on Atomic or self-hosted)... But glad it worked in the end...

**Comment by filipanoscampos** [comment]
6655852-zd-a8c

I was also able to reproduce this on a test site.

**Comment by dsas** [comment]
> User in 6717645-zd-a8c let us know their subscriber was able to get in the following day. Possibly it took a day to add the access to their WPCOM account...?

There's an issue open for "doesn't work for first 24 hours" here: https://github.com/Automattic/wp-calypso/issues/68506 & here https://github.com/Automattic/payments-shilling/issues/458

One thing it's worth doing with premium content blocks is ensuring the user hasn't accidentally removed the special premium content login/subscribe buttons and replaced them with their own random buttons (see https://github.com/Automattic/wp-calypso/issues/69427#issuecomment-1380807552 & https://github.com/Automattic/jetpack/issues/28331)

See https://github.com/Automattic/wp-calypso/issues/69427 for more investigation of this problem.

**Comment by kelasante** [comment]
Another report here: 7174744-zd-a8c. Added details about that report to P2: p2EDhh-23L-p2

**Comment by jp-imagines** [comment]
Another report here as well I believe: 7841284-zd-a8c
Commenting in https://github.com/Automattic/gold/issues/36 too, as it looks like this should have been fixed back in October.

**Comment by millerf** [comment]
This should be fixed now (see my comment: https://github.com/Automattic/gold/issues/36#issuecomment-1991453754).

**Comment by davipontesblog** [comment]
I am reopening this as it's been once again reported by a user in 7995674-zd-a8c. I could reproduce on another page of their site as well.

- Clicking on the "Log in" button from the Membership Access page should bring you to a WordPress.com login page. if you are already logged in, it doesn't, instead, it's supposed to show you the content behind "Subscriber view" on the block, refreshing the page in the process and adding a 'token' to the browser URL. **Sometimes** this does not happen, the button disappears once you click it, and the exact same content from "Guest view" appears otherwise. Refreshing caching seems efficient in clearing the issue.

**Comment by the-misha** [comment]
User report: 8086405-zd-a8c

**Comment by filipanoscampos** [comment]
May be related: p2EDhh-2cv-p2

**Comment by i11za** [comment]
User report: 8305581-zd-a8c - they've had this issue consistently for at least a year now, also reported [here](https://github.com/Automattic/wp-calypso/issues/69427). 

I'm initially able to replicate on their site, with various subscribers:
1. Access page with Paid Content 
2. Log in to access paid content
3. Get redirected back to "Guest view"
4. Reload page - see "Subscriber view"

**Comment by CodeAllNightNDay** [comment]
This user's subscribers seem to be experiencing the same issue:
8473396-zen

**Comment by jerrysarcastic** [comment]
This issue has also been found with another site owner using the Paid Content Block
8609840-zd-a8c

**Comment by millerf** [comment]
discussions here: p1724187327555669-slack-C01B6KEJ5GE

**Comment by millerf** [comment]
Closed with https://github.com/Automattic/gold/issues/36

**Comment by millerf** [comment]
For the record I tested it pretty extensively, and it seems to work fine.

https://github.com/Automattic/gold/issues/539#issuecomment-2539495725
