### ISSUE TITLE
Post Link Tracking: change the endpoint to retrieve the clicks of the emails to return user content links info too

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#80976]
In the Email Clicks stat page (`https://wordpress.com/stats/email/clicks/day/[email-id]/[domain-of-the-site]`) we call this endpoint to retrieve the tracking info of the clicked links: `/rest/v1.1/sites/[site-id]/stats/clicks/emails/[post-id]/link`.

We must modify that endpoint to include the tracking info for user-generated links.

**Comment by TimBroddin** [comment]
This is probably the endpoint we'd want to change: `/rest/v1.1/sites/[site-id]/stats/clicks/emails/[post-id]/link`, since the one you referenced only contains the number of clicks on a timeline.

The shape of data returned right now is:

```
 "links": {
            "data": [
                [
                    "post-url",
                    1
                ]
            ],
            "fields": [
                "link_desc",
                "clicks_count"
            ]
        }
```

This data is then parsed [here](https://github.com/Automattic/wp-calypso/blob/c0640752eb4ccd1182729b0ee6ca3b99d515eb02/client/state/stats/emails/utils.js#L224-L224). link_desc fields it doesn't recognize get ignores for now.

I suggest we change the shape to be:



```
 "links": {
            "data": [
                [
                    "post-url",
                    1,
                   false
                ],
                [
                "https://youtube.com/....."
                15,
                true
                ]
            ],
            "fields": [
                "link_desc",
                "clicks_count",
                "is_user_link"
            ]
        }
```

WDYT @JuanLucha ?

**Comment by JuanLucha** [comment]
> This is probably the endpoint we'd want to change: `/rest/v1.1/sites/[site-id]/stats/clicks/emails/[post-id]/link`, since the one you referenced only contains the number of clicks on a timeline.
> 
> The shape of data returned right now is:
> 
> ```
>  "links": {
>             "data": [
>                 [
>                     "post-url",
>                     1
>                 ]
>             ],
>             "fields": [
>                 "link_desc",
>                 "clicks_count"
>             ]
>         }
> ```
> 
> This data is then parsed [here](https://github.com/Automattic/wp-calypso/blob/c0640752eb4ccd1182729b0ee6ca3b99d515eb02/client/state/stats/emails/utils.js#L224-L224). link_desc fields it doesn't recognize get ignores for now.
> 
> I suggest we change the shape to be:
> 
> ```
>  "links": {
>             "data": [
>                 [
>                     "post-url",
>                     1,
>                    false
>                 ],
>                 [
>                 "https://youtube.com/....."
>                 15,
>                 true
>                 ]
>             ],
>             "fields": [
>                 "link_desc",
>                 "clicks_count",
>                 "is_user_link"
>             ]
>         }
> ```
> 
> WDYT @JuanLucha ?

Nice! Changed the body of the issue 👍

**Comment by TimBroddin** [comment]
The more I think about this, the more hacky it feels. I think creating a `/stats/clicks/emails/[post-id]/user_links` endpoint is probably better. We know where combining two data sources in one endpoint gets us 😄 We'll shoot ourselves in the foot should we ever need to filter or paginate in the future.
