### ISSUE TITLE
Discussion Settings need updated copy - remove Twitter and Google from list of accounts that can comment

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#80972]
### Quick summary

In Calypso's Settings > Discussions, we have the option that says `Let visitors use a WordPress.com, Twitter, Facebook, or Google account to comment` . However, it seems we no longer support the ability to use Twitter and Google accounts to leave comments on atomic sites.

The [Jetpack guide here](https://jetpack.com/support/comments/) doesn't mention Twitter or Google. While Jetpack > Settings > Discussion mentions Twitter but not Google.

Can we update the copy in Calypso and in the Jetpack settings?

### Steps to reproduce

1. Go to Settings > Discussions on an atomic site
2. Enable the option for `Let visitors use a WordPress.com, Twitter, Facebook, or Google account to comment`
3. Check a post on the site and you will notice that there's no Twitter or Google as part of the accounts you can use to comment

### What you expected to happen

The ability to use Twitter or Google to leave comments on a site that has `Let visitors use a WordPress.com, Twitter, Facebook, or Google account to comment` enabled.

### What actually happened

Twitter and Google were missing from the options.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Slack discussion - p1692798229145709-slack-C03TY6J1A

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated** / Could Not Replicate / Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO

On `https://wordpress.com/settings/discussion/` : 

![Markup on 2023-08-23 at 17:27:10](https://github.com/Automattic/wp-calypso/assets/27249804/527f7db2-5842-4b08-bb49-abe4418952f7)

![Markup on 2023-08-23 at 17:28:19](https://github.com/Automattic/wp-calypso/assets/27249804/8c09c302-f85d-4a26-bb70-60f515046f45)

On `/wp-admin/admin.php?page=jetpack#/discussion` :

![Markup on 2023-08-23 at 17:32:09](https://github.com/Automattic/wp-calypso/assets/27249804/06305eca-4e8b-48e6-b32f-2ff7b763e7ba)

📌 ACTIONS
- FYI @jeherve

**Comment by tellisbethel** [comment]
Got a user who encountered this here and it caused some confusion: 6722085-zd-a8c
I let them know we'll be updating the copy.
