### ISSUE TITLE
Reader: If Followed site is a feed/non-wpcom site, Follow button isn't green

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8097]
#### Steps to reproduce:
1. In Manage Following, add a site feed or non-wpcom site
2. Go back to your Following stream
3. Check Follow button and notice this site's Follow button hasn't changed to "Following"

This site, for example, I'm already following but button still says "Follow":
![screenshot 2016-09-23 15 09 50](https://cloud.githubusercontent.com/assets/4924246/18802790/f5a1de12-819f-11e6-875d-352717212692.png)

/cc @blowery

**Comment by bluefuton** [comment]
> Check Follow button and notice this site's Follow button hasn't changed to "Following"

@jancavan where were you seeing the incorrect follow state? Can you repro?

I just tried following a new external blog and following state was correctly reflected in the new full post view:

<img width="266" alt="screen shot 2016-09-27 at 17 57 00" src="https://cloud.githubusercontent.com/assets/17325/18897084/e2775670-84db-11e6-9a25-5e13e1c3519c.png">

**Comment by jancavan** [comment]
@bluefuton A couple examples: 

https://wordpress.com/read/feeds/45336349
https://wordpress.com/read/feeds/8878742/posts/1123381012

I'm following these sites, but the Follow button isn't green in full-post:

![screenshot 2016-09-27 18 18 06](https://cloud.githubusercontent.com/assets/4924246/18897379/c1d80c36-84de-11e6-8bc5-f70f538b7a77.png)

![screenshot 2016-09-27 18 17 43](https://cloud.githubusercontent.com/assets/4924246/18897383/c5551200-84de-11e6-98f1-7681d9129c3e.png)

I think TC is a wpcom site (?) so that's probably why it's green.

**Comment by bluefuton** [comment]
Sorry, bad example! I followed a Tumblr blog and the full post follow button for that worked too. I'll try to repro again.

**Comment by jancavan** [comment]
Hmm, that's odd. I can never get the Follow button to turn green for non-wpcom sites.

**Comment by bluefuton** [comment]
Confirmed - I'm seeing the same on https://wordpress.com/read/feeds/8878742.
