### ISSUE TITLE
Plugins: Listen for changes to plugins and update sites right away

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#81]
Currently we rely on the wp cron to trigger the autoupdate. That's not exactly the most reliable way to do this also it could take a while before the update happens. 

Instead would listen for changes to the wp.org plugins svn repo and then try to update the plugins within minutes of the changes happening to the plugin. This way we could keep sites updates faster. 

In order for this to happen we would need to know what plugins are stored on what site. Currently that data is not available on .com without doing an api request to each site.

**Comment by enejb** [comment]
I am changing this to not be part of this milestone but something to look at in the future.

**Comment by jeherve** [comment]
Still a potential improvement that could be made.

**Comment by jeherve** [comment]
Still a potential improvement that could be made.
