### ISSUE TITLE
Donations Form block: Missing visual cue of which tier is selected.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#81008]
### Quick summary

When interacting with the published version of the block, all buttons are completely missing all visual cues indicating which tier has been selected.

### Steps to reproduce

1. insert Donations Form block.
2. publish the post.
3. view the post.
4. try to interact with the tiers.

### What you expected to happen

Visual cue is present indicating which tier has been selected.

### What actually happened

Completely missing all visual cues.

https://github.com/Automattic/wp-calypso/assets/6549265/8d31b851-de6b-44b6-97ba-321fa718cbd8

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
This appears to differ a little by theme, but it's definitely subtle even when something occurs:

Simple Site on Didone Theme: 

https://github.com/Automattic/wp-calypso/assets/27249804/a67bee76-52dd-42e0-bb64-e0d79fa5d529

Simple Site on TT3 Theme:

https://github.com/Automattic/wp-calypso/assets/27249804/10087d92-af4c-4da0-87b3-54d154681013


📌 ACTIONS
- Triage complete
- Lowering priority to `Normal`
- FYI @Automattic/gold

**Comment by caitlindawn** [comment]
Reported in 7617378-zen
Theme: Alves

**Comment by gikaragia** [comment]
This is now fixed as I have tried to reproduce it with many themes but it wasn't possible. Themes that I tried:
- 2020 - 2024
- Alves
- Illustratr
- Fewer
- Wilson
- Leven
- Hever
- Hevor
