### ISSUE TITLE
Donations Form block: selecting DKK currency crashes the block.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#81006]
### Quick summary

Selecting Danish krone currency for the Donations Form block crashes the block.

### Steps to reproduce

1. insert the Donations Form block.
2. in the toolbar, change the currency to DKK.

### What you expected to happen

Block renders DKK version.

### What actually happened

Block crashes:

```
This block has encountered an error and cannot be previewed.
```

https://github.com/Automattic/wp-calypso/assets/6549265/6bb9fd18-badd-4380-be1a-b3cd1dd6a6bc

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Browser Logs:
```
SyntaxError: \ at end of pattern
```

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described! Other currency selections do not throw any errors. 

https://github.com/Automattic/wp-calypso/assets/27249804/ec9d2042-90a3-4b08-9f24-fc47f2d31828

📌 ACTIONS
- Triage complete
- FYI @Automattic/gold

**Comment by dsas** [comment]
> No but the platform is still usable

Well, the block isn't usable if you are Danish. When you add the block it'll default to DKK and crash instantly. Possible workarounds are to use payment blocks instead, or use code view to change the currency code.

**Comment by dsas** [comment]
Customer ticket: 6734561-zd-a8c

**Comment by cuemarie** [comment]
@millerf is this something that Gold may be able to address?

**Comment by millerf** [comment]
@cuemarie Fix in https://github.com/Automattic/jetpack/pull/33072. Thanks for pinging me.
