### ISSUE TITLE
Subscription - New Comments - typo

### ISSUE THREAD

**Issue by mikestottuk** [Automattic/wp-calypso#81027]
### Quick summary

Additional "s" on the tooltip

### Steps to reproduce

If you go here: https://wordpress.com/subscriptions/sites/en and are subscribed to a site and have email notifications on for comments. 

The tooltip hover says "email**s** notifications" - need to drop the s.

<img width="1427" alt="Screenshot 2023-08-24 at 14 38 43" src="https://github.com/Automattic/wp-calypso/assets/4077604/75653052-15bd-43a1-b269-e08a7cdd6af2">

### What you expected to happen

Should say **email notifications** not emails notifications.

### What actually happened

Says **emails notifications**

### Impact

All

### Available workarounds?

There is no user impact

**Comment by simison** [comment]
Good catch! https://github.com/Automattic/wp-calypso/pull/81036
