### ISSUE TITLE
READER - Linear gradient effect at the end of the excerpt is added

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#81032]
### Quick summary

There is a CSS gradient being applied to the end of post excerpts when viewing it in Reader. Since the page has a greyish background, the white part of the gradient is visibly standing out.

### Steps to reproduce

1. Update the RSS feed settings from Settings > Reading 
2. Select "Excerpt" in the "For each post in a feed, include" 
3. Save settings
4. Go to Reader and view the post (example: https://wordpress.com/read/blogs/148605864/posts/11776)

### What you expected to happen

There's no noticeable gradient at the end of the post excerpt.

### What actually happened

![Screenshot 2023-08-24 at 17 48 01](https://github.com/Automattic/wp-calypso/assets/67279475/efda91b3-7ba1-42dd-a654-57c297ddfa3d)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

**Related CSS:** 

.post-excerpt.is-long:after {
    background: linear-gradient(90deg,#fff0,#fff 50%);
    bottom: 0;
    content: "";
    height: 24px;
    position: absolute;
    right: 0;
    text-align: right;
    width: 50%;
}

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described!  This appears on posts whether or not they have a manual excerpt set up. In the example below, I do not have a manual excerpt written.

![Markup on 2023-08-24 at 16:47:08](https://github.com/Automattic/wp-calypso/assets/27249804/2e2251eb-5eab-4dcc-96fb-285ffaaf68e4)

<img width="1374" alt="Screenshot on 2023-08-24 at 16-47-31" src="https://github.com/Automattic/wp-calypso/assets/27249804/10d53380-b855-4169-bed4-eb903d996b46">

📌 ACTIONS
- Triage complete
- CC: @Automattic/loop

**Comment by Addison-Stavlo** [comment]
This should be a quick fix but Im having problems reproducing.

I updated the settings to show 'exerpt' and saved.
<img width="828" alt="Screenshot 2023-08-25 at 10 46 07 AM" src="https://github.com/Automattic/wp-calypso/assets/28742426/c3e36a53-7353-4622-b9ac-32db66d48bd6">

I published a post on that site and made sure to add an excerpt as well.

I viewed that post in the reader and it showed the full post, not an excerpt to repro this issue. Maybe im missing something?

> Go to Reader and view the post (example: https://wordpress.com/read/blogs/148605864/posts/11776)

I also tried this link and its not showing as an excerpt either.  Do you happen to have a link to a post that shows as an excerpt here?

**Comment by roo2** [comment]
I dug into this some more, it looks like we don't respect the "excerpt only" setting in reader for simple sites, only atomic sites. p5PDj3-1wD-p2 we should probably also disable that setting if the site isn't Atomic.

But I made a PR for a simple fix for the gradient issue https://github.com/Automattic/wp-calypso/pull/81124
