### ISSUE TITLE
Newsletter Categories: Update email sending job to support `wpcom_newsletter_categories_enabled` site option.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#81075]
The newsletter category support for email sending job was created when we haven't decided whether to have a master switch `wpcom_newsletter_categories_enabled` so it is determining whether to support newsletter categories based on whether site owners have marked some categories as newsletter categories.

With the site option `wpcom_newsletter_categories_enabled` now introduced, we need to update the async job to determine using the `wpcom_newsletter_categories_enabled` site option instead. 

To fix in the file `async-jobs/includes/subscription-emails/subscription-emails.php`.

**Comment by mashikag** [comment]
Addressed in: D120573-code
