### ISSUE TITLE
Plans 2023: Convert FeaturesGrid from class to function, and clean up folder structure

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#81078]
As of https://github.com/Automattic/wp-calypso/issues/78266 we export FeaturesGrid and ComparisonGrid from plans-features-2023-grid (which is now mainly an index of the individual components) and assemble the plans page on consuming end.

FeaturesGrid is a class component that also encloses the Spotlight plan. We should be converting this to a function component and moving out individual parts that can be reused between FeaturesGrid and SpotlightPlan (being extracted in https://github.com/Automattic/wp-calypso/issues/81076 ). Make use of `/components/shared` folder for shared components.

**Comment by oswian** [comment]
@chriskmnds I believe we can now mark this issue as resolved. I'll mark as 'Done ✅' for the assigned projects?

---

> FeaturesGrid is a class component that also encloses the Spotlight plan. We should be converting this to a function component

PR merged: https://github.com/Automattic/wp-calypso/pull/86730

> ... and moving out individual parts that can be reused between FeaturesGrid and SpotlightPlan (being extracted in https://github.com/Automattic/wp-calypso/issues/81076 ). Make use of /components/shared folder for shared components.

PR merged: https://github.com/Automattic/wp-calypso/pull/86825

**Comment by oswian** [comment]
@chriskmnds I've created a new [issue](https://github.com/Automattic/wp-calypso/issues/87208) for implementing stories + tests for all of the `FeaturesGrid` components we created for this. Do you think that is something I should focus on next? Alternatively I was going to move on to https://github.com/Automattic/wp-calypso/issues/81076.

**Comment by chriskmnds** [comment]
Hey @oswian . Thanks for the great work done in those PRs. I think we still need to address before closing issue:

> Make use of `/components/shared` folder for shared components.

This includes existing components under `/src/components`. Ideally, nothing should remain there that is not in one of the respective folders (`/src/components/shared`, `/src/components/features-grid`, `/src/components/comparison-grid`). That said, considering the scope of the work, it would probably make sense to create a separate issue for this (to migrate shared components under `/src/components/shared`) and indeed close this one. This issue originally meant to reflect both, which does seem a little too wide :-)

**Comment by chriskmnds** [comment]
> Do you think that is something I should focus on next? Alternatively I was going to move on to https://github.com/Automattic/wp-calypso/issues/81076.

As you like! Also https://github.com/Automattic/wp-calypso/issues/86642 is an interesting issue (probably higher in priority, but more involving). So either of these and we can also leave stories for Milestone 3 if you like/prefer (left a related comment here: https://github.com/Automattic/wp-calypso/issues/87208#issuecomment-1931747960)

**Comment by oswian** [comment]
> it would probably make sense to create a separate issue for this (to migrate shared components under /src/components/shared) and indeed close this one. This issue originally meant to reflect both, which does seem a little too wide :-)

Sounds good, done: https://github.com/Automattic/wp-calypso/issues/87293

**Comment by oswian** [comment]
> As you like! Also https://github.com/Automattic/wp-calypso/issues/86642 is an interesting issue (probably higher in priority, but more involving). So either of these and we can also leave stories for Milestone 3 if you like/prefer

Ok I'll take closer look at #86642 tomorrow.
