### ISSUE TITLE
Theme Details: Send to Checkout without Modals (If Appropriate)

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#81095]
If the site is Atomic and the theme requires an additional subscription, upon clicking on the primary "Subscribe" action, send the user straight to checkout without showing any modals.

---

The Theme Details page and the primary "Subscribe" action:

<img width="1428" alt="Screenshot 2023-08-25 at 16 50 26" src="https://github.com/Automattic/wp-calypso/assets/2070010/527f1807-4351-4cb6-9cc3-ffcdd8b1bcc0">

**Comment by BogdanUngureanu** [comment]
Looks like this no longer happens, the user is now redirected directly to checkout when they click on the button. I'll close the issue :)
