### ISSUE TITLE
Domain Forwarding: Support multiple redirects per domain

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#81100]
Feature PT: pb5gDS-3ig-p2

We want to support multiple redirects per domain:

<img width="1529" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1044309/323793f0-d1c5-40c5-a620-c0e39023070a">

### Acceptance criteria

- [ ] Support multiple redirects per domain
- [ ] They need to support [subdomains as well](https://github.com/Automattic/wp-calypso/pull/81047)
- [ ] Make sure the interface works on mobile
- [ ] Review how deletion will work
- [ ] Make sure validation for wrong source URL domain communicate the problems well. For instance, what happens if the user types a different domain as Source URL?

**Comment by JanaMW27** [comment]
mbuq4o5QxohQpBU9YoexXo-fi-2282%3A62194 for the multiple redirect input fields:

For reference:
![Screenshot 2023-08-28 at 12 51 00](https://github.com/Automattic/wp-calypso/assets/71137829/5eddb8df-6626-46d3-9533-d5bfb41cc64c)

**Comment by paulopmt1** [comment]
We're working on it here: https://github.com/Automattic/wp-calypso/issues/81290
