### ISSUE TITLE
Block: Page List - On site with high page count, editor fails to display all pages

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#81110]
_Update - this report has been redacted and relocated to an internal investigation._

### Quick summary

On a site with over 200 pages, the Page List block is not displaying all the pages in the editor and certain Parent Pages can't be searched, but all of the pages do display on the live page.

### Steps to reproduce

I can experience the issue on the user's site but I can't reproduce the issue on another site, but I also don't have a site with over 200 pages. Full troubleshooting was previously done with the plugins and theme, and it didn't resolve the issue. I didn't personally retest all of this.

### What you expected to happen

I expect the editor to display the same pages that the live version of the page displays. I also expect to be able to search for all available Parent Pages.

### What actually happened

Page List block is not displaying all the pages in the editor and certain Parent Pages can't be searched.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

I can't confirm if this is a site specific issue or not and I haven't been able to deep dive into further troubleshooting. The user has been given a work around of using the Query Loop block instead for now, though styling isn't ideal. The site is atomic. The user has also asked for a link to this issue to track the progress of it getting fixed. I haven't provided it at this time.

**Comment by cuemarie** [comment]
- Interaction: 6719322-zen

**Comment by cuemarie** [comment]
📌 ACTIONS
- Per discussion here: p1693091205248179-slack-C0160HSMDQV , closing this report in favor of an internal investigation.
