### ISSUE TITLE
Embed Block: Add support for x.com links to embed Twitter posts

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#81116]
### What

Users are trying to use the `https://x.com` URLs to embed tweets and it drops them in as a text link only. Swapping the `x.com` for `twitter.com` does work to embed the tweet.

Can this block be updated to work with the `x.com` URLs? Or maybe add a message stating that they have to use the `twitter.com` version of the URL?

### Why

Right now it just looks like the block is broken and not working properly. It either gives an error:
![kDYwGl.png](https://github.com/Automattic/wp-calypso/assets/42655541/b61eb6bd-c870-4434-b884-d0bc5eef81b8)

Or it just posts it as linked text.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- Requested in `/gutenberg`: https://github.com/WordPress/gutenberg/issues/54042

**Comment by sophiegyo** [comment]
Noting another case here: 6694991-zen

**Comment by ariel-maidana** [comment]
Another case here: 6805704-zd-a8c
Please inform the user if this issue is solved: 6806332-zd-a8c

**Comment by ariel-maidana** [comment]
Another case here: 6804730-zd-a8c
Please inform the user when this issue is solved.

**Comment by aetta** [comment]
6981226-zen

**Comment by cuemarie** [comment]
https://github.com/WordPress/gutenberg/pull/54876 was merged in Gutenberg 16.8, which checks if the URL points to `x.com` and replaces it with `twitter.com` as a fallback to retrieve the embed preview using the Twitter provider.

In other words, this workaround is in the future for WordPress.com sites 👍

**Comment by kelasante** [comment]
User experiences issue in Classic Editor in 8526927-zen as https://github.com/WordPress/gutenberg/pull/54876 works for only the Block Editor. 

Asked user to manually switch from X to twitter to embed as they prefer to keep using the Classic Editor.

**Comment by annezazu** [comment]
Closing this out as https://github.com/WordPress/gutenberg/pull/54876 was merged previously and is available on WordPress.com.
