### ISSUE TITLE
Design your own theme error message

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/wp-calypso#81115]
### Quick summary

When you design your own theme via: https://wordpress.com/themes/filter/full-site-editing/ - and follow the steps to add content (eg. header, sections, footer), then accept the theme activation, this error message appears: 

"We've hit a snag. It looks like something went wrong while setting up your store. Please contact support so that we can help you out. Need help? Contact support"

However, if you go to Appearance > Editor, you will see that the theme you designed has been saved and is working as expected.

### Steps to reproduce

1. Start at: https://wordpress.com/themes/filter/full-site-editing/
2. Click on 'Design your own'
3. Follow the prompts to add content ie. Header, Section, Footer
4. Check the select box to activate the theme
5. Error message appears: "We've hit a snag. It looks like something went wrong while setting up your store. Please contact support so that we can help you out. Need help? Contact support"

### What you expected to happen

We should expect a message that indicates that the design we've created has been saved and is activated.

### What actually happened

Error message appears: "We've hit a snag. It looks like something went wrong while setting up your store. Please contact support so that we can help you out. Need help? Contact support" - which causes confusion as the design we've created is in fact saved and can be edited/worked on via Appearance > Editor.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

The issue (error message) doesn't appear on Simple sites but appears for Atomic sites.

Report: 6728823-zen
Follow up: 6729064-zen

**Comment by adelineyaw** [comment]
Another report 6729232-zen
Follow up 6729301-zen

**Comment by donalirl** [comment]
Also reported in #6728946-zen

**Comment by arthur791004** [comment]
Resolved the issue via D119932-code. The reason is the latest Gutenberg made some changes to the global styles endpoint and it made wpcom cannot forward the related endpoints to the AT site.

**Comment by retnonindya** [comment]
Closing as the issue is resolved 🎉  Thanks, @arthur791004!
