### ISSUE TITLE
Update the dotcom default build theme Aug 2023

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#81113]
# Description

Per [Matias' request](url), let's pick one of the new themes suitable for a generic "build flow" website.
Update on Jan 8: TT4 will be new build theme. See p1702565167037019/1702513685.073989-slack-C048CUFRGFQ

## Tasks
- [x] Decide on theme 
- [ ] Update code to select TT4 theme instead of TT3

### Previous changes
* https://github.com/Automattic/wp-calypso/issues/70604
* Call for review: The default theme for the write and build flow  pNEWy-gCz-p2 pNEWy-gCz-p2

**Comment by ianstewart** [comment]
Exmoor seems like a great choice. Has a great default feel. Clean, pleasantly neutral, with nice bold headings, and a projection of authority. Looks easy to edit.

**Comment by autumnfjeld** [comment]
@ianstewart  Exmoor does not exist anymore pbEMJv-2dk-p2

Should we switch the default to TT4?

**Comment by autumnfjeld** [comment]
Check this before starting: p1704686167909059/1704232818.652459-slack-C048CUFRGFQ

**Comment by arthur791004** [comment]
People cannot skip the Design Picker step anymore, so they have to pick a theme. As a result, I think we can close this issue. WDYT?

**Comment by taipeicoder** [comment]
Closing. Let's revisit this when we have a more recent request.
