### ISSUE TITLE
Synced Patterns - No way to "unsync" a pattern

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#81128]
### What

It's possible to create a pattern and there is a "sync" toggle when creating it. However, after creating a synced pattern, there is no visible/clear way to "unsync" the pattern. 

### Why

There are cases where a user may want to make changes to their pattern that is synced by toggling it as no longer syncing. However, they currently need to create a new pattern and not toggle synced as a work around.

### How

![CleanShot 2023-08-28 at 15 38 32@2x](https://github.com/Automattic/wp-calypso/assets/83020905/8b02ad4d-e578-4aca-b797-9cd0a492ba53)

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- Relevant `/gutenberg` discussion here: https://github.com/WordPress/gutenberg/issues/53320

**Comment by annezazu** [comment]
Noting that this has been resolved in https://github.com/WordPress/gutenberg/issues/53320 thanks to a new option to duplicate a pattern and change the sync status. Here's a video:

https://github.com/user-attachments/assets/165d26ef-b41f-4458-865e-ee56b8dc043f
