### ISSUE TITLE
Live Preview: Add "a congratulations moment" after activating a previewing theme

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#81122]
# Description

Currently, there is a very subtle moment when the user knows that the new theme has been successfully activated. So, adding “a congratulations moment”, like showing confetti, after activating a previewing theme might make sense. See pekYwv-1WD-p2#comment-1629.

Project Thread: pbxlJb-3Uv-p2

# Acceptance Criteria
- [ ] Users can clearly know the moment that the previewing theme is applied. 
- [ ] Approved by a designer

# Dev Tasks

TBD

# Testing 

TBD

# Related

- https://github.com/Automattic/dotcom-forge/issues/2806

**Comment by taipeicoder** [comment]
cc: @lucasmendes-design

**Comment by lucasmendes-design** [comment]
Oh God! haha. Is it fine to focus on this issue next week?

**Comment by autumnfjeld** [comment]
I'm going to close this.  We don't need any more congratulations screens. Previewing a theme is not a big event. :)
