### ISSUE TITLE
Email stats - Clicking on "View all" renders a blank calypso page for user with high subscriber count

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#81138]
### Impacted plugin

Jetpack

### Quick summary

- A WordPress.com customer on a Business plan, atomic site, reported that In Jetpack Stats (https://wordpress.com/stats/subscribers/DOMAIN), when clicking on 'view all' it's not loading, cannot see the stats of the previous emails or weeks.
- I can replicate this on their site. Clicking "View all" leads to a blank page in calypso:

<img width="1038" alt="Screenshot 2023-08-24 at 10 38 06" src="https://github.com/Automattic/jetpack/assets/31009008/c759a0a1-60f1-4150-9e7d-bdc69feb7384">

### Steps to reproduce

1. Go to https://wordpress.com/stats/subscribers/DOMAIN
2. Click "view all"
3. See the issue

### A clear and concise description of what you expected to happen.

To see all email stats.

### What actually happened

Nothing loads.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

user report 6655629-zen

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Unable to replicate on Simple or Atomic. Opening Stats > Subscribers > **View Details** under "Emails" (`https://wordpress.com/stats/day/emails/SITE_ADDRESS`) loads stats as expected:

![Markup on 2023-08-24 at 09:45:06](https://github.com/Automattic/jetpack/assets/27249804/e4dbf44f-86db-4012-bdbd-2c9b6494f9b9)

**User's Site**

I checked out the user's site (Blog ID 61647510), and I see they have 3.2k email subscribers, and their Subscriber Stats page says **View all**, not **View details**, like my sites do. I wonder if we're seeing different behavior bc of the high subscriber number?

I throttled my browser to slow down the loading and refreshed the page, and we can see the page starts to load, and then fails. No console logs appear:

https://github.com/Automattic/jetpack/assets/27249804/ebf74bdf-c8dc-4c82-87c5-f3a6973bca7a

📌 ACTIONS
- Set as To Do
- CC @jeherve

**Comment by jeherve** [comment]
Since this interface lives in Calypso, I'll transfer this to the Calypso repo for now. 👍

**Comment by gikaragia** [comment]
I have tried this again and couldn't reproduce it, both on a test site of mine and on the user's site.
