### ISSUE TITLE
Twenty Twenty-Three: Like text besides the comment on the Aubergine style variation is nearly invisible.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#81157]
### Quick summary

The Likes text which appears besides the comment is nearly invisible in the Aubergine variation.

![Screenshot 2023-08-29 at 11 30 06 AM](https://github.com/Automattic/wp-calypso/assets/6549265/70fd5a3f-066b-4a51-ac23-9768ffb79c55)

### Steps to reproduce

1. apply the Twenty Twenty-Three Aubergine variation.
2. make a new post.
3. make a comment on the post.
4. like the comment.
5. see the text.

### What you expected to happen

The text is in white or some other high-contrast colour.

### What actually happened

The text is in black, which is nearly invisible against the dark purple background.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated** / Could Not Replicate / Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described!  The Comment Like text is _very_ hard to read. 

![Markup on 2023-08-29 at 18:29:33](https://github.com/Automattic/wp-calypso/assets/27249804/ac189433-b3f5-4d6d-be70-0c9aaf9735ac)

📌 ACTIONS
- Triage complete
- FYI @Automattic/t-rex , is this something y'all think would fall under Global Styles issues?

**Comment by Copons** [comment]
> FYI @Automattic/t-rex, is this something y'all think would fall under Global Styles issues?

@cuemarie Nay, this is about the (Comment) Like widget itself that hardcodes its text color, rather than inheriting it from the theme:

fbhepr%2Skers%2Sjcpbz%2Sjvqtrgf.jc.pbz%2Syvxrf%2Sfglyr.pff%3Se%3Qq98o2n3q%23141-og

Judging from recent blames (which seem unrelated to this specific issue), I'd ping @Automattic/loop 🙂

**Comment by davemart-in** [comment]
Hmm... I just tested this on https://lessbloat.wordpress.com/2023/08/22/new-post-3/ and I'm unable to replicate it. Here's what I'm seeing:

![CleanShot 2023-08-30 at 11 12 19](https://github.com/Automattic/wp-calypso/assets/5634774/f118291a-fe99-4d4b-8a0c-797b69e4215e)

![CleanShot 2023-08-30 at 11 12 57](https://github.com/Automattic/wp-calypso/assets/5634774/20444e06-d4d2-4393-b69f-54d0e56805f9)

**Comment by Copons** [comment]
@davemart-in AFAICS, this only happens on Atomic.

Check this [random test site](https://copons20230117a.wpcomstaging.com/2023/01/17/behind-the-product-fedora-hat/comment-page-1/#comment-1): 

| Comment | Highlighted | Code |
|--------|--------|--------|
| <img width="352" alt="Screenshot 2023-08-30 at 17 41 08" src="https://github.com/Automattic/wp-calypso/assets/2070010/804bfb84-3556-4d35-b2a8-dc336063f905"> | <img width="336" alt="Screenshot 2023-08-30 at 17 41 13" src="https://github.com/Automattic/wp-calypso/assets/2070010/d47b181c-133f-44bf-85ab-e445dce512fe"> | <img width="185" alt="Screenshot 2023-08-30 at 17 41 26" src="https://github.com/Automattic/wp-calypso/assets/2070010/2a812d89-ccb8-4cc2-9fe7-a2d65d0bb68d"> | 

(note again where this code comes from: fbhepr%2Skers%2Sjcpbz%2Sjvqtrgf.jc.pbz%2Syvxrf%2Sfglyr.pff%3Se%3Qq98o2n3q%23141-og)

**Comment by davemart-in** [comment]
Okay. Thanks. Yeah, that is going to require some investigation. We'd need to pass custom variable into the likes API. Adding this to our board.

**Comment by cuemarie** [comment]
Thanks y'all!

**Comment by davemart-in** [comment]
@cuemarie @Copons I stubbed out a fix for this: D120823-code

**Comment by davemart-in** [comment]
This _should_ be fixed now with D120823-code deployed.
