### ISSUE TITLE
Flaky E2E: Select "Sections"

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#81156]
### Spec file

specs/onboarding/ftme__site-assembler.ts

### TeamCity ID

10672654

### Logs

```
======= Failed test run #1 ==========
  locator.scrollIntoViewIfNeeded: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('listbox', { name: 'Block patterns' }).getByRole('option', { name: 'Heading with two images and descriptions', exact: true })
  ============================================================
  at SiteAssemblerFlow.scrollIntoViewIfNeeded [as selectLayoutComponent] (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:57:16)
      at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__site-assembler.ts:102:4)
======= Failed test run #2 ==========
  locator.scrollIntoViewIfNeeded: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('listbox', { name: 'Block patterns' }).getByRole('option', { name: 'Heading with two images and descriptions', exact: true })
  ============================================================
  at SiteAssemblerFlow.scrollIntoViewIfNeeded [as selectLayoutComponent] (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:57:16)
      at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__site-assembler.ts:102:4)
```

![image](https://github.com/Automattic/wp-calypso/assets/6549265/7f0af71e-b310-4fcf-9ab8-6130e51b2fee)

**Comment by worldomonation** [comment]
[ftme__site-assembler__select--sections-__1-1.webm](https://github.com/Automattic/wp-calypso/assets/6549265/6b8ce4cb-1b65-4c1b-88b8-91345405d0b9)

![image](https://github.com/Automattic/wp-calypso/assets/6549265/eea83d24-e8b7-49eb-8953-80d037976ee9)

**Comment by worldomonation** [comment]
@Automattic/lego Did something change around 1200 UTC+9 on August 28 relating to the Sections, or is this perhaps flakiness in the interaction?

**Comment by arthur791004** [comment]
We're working on curating the categories and pattern list so the `Heading with two images and descriptions` patterns don't seems to belong to the default category now cc @miksansegundo

**Comment by worldomonation** [comment]
Ahhh, gotcha. 

I'll replace the pattern list with something else. What's a (likely) safe one to use for the time being?

**Comment by arthur791004** [comment]
I think it's safer to just select the first one from the list. If it makes sense, I can propose a PR to do that. WDYT?

Also, I guess there is another issue with this e2e test since we have added a new step to the Assembler. I'll propose a PR to update it later 🙂

**Comment by worldomonation** [comment]
It used to be that we'd select the first one, and I changed it last week in https://github.com/Automattic/wp-calypso/pull/81064 to fix a flakiness issue. It turns out selecting by the accessible name is a lot more reliable than selecting the first one.

If possible I'd like to keep it that way, but if there isn't a way to guarantee that a certain component will always be available, there would be no other option I suppose.
