### ISSUE TITLE
Site: Do not show site settings cog for non-admins

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#8115]
For the site component that is shown at the top of the my sites sidebar, I noticed that we show the "Site Settings" cog for non-admins, and then if a user clicks on that cog, we redirect that users to `/stats`. This seems like an awkward flow bug.

Since we probably shouldn't allow editing the site icon or site settings for non-admins, then perhaps we should not show the ellipsis toggle for non-admins?

<img width="280" alt="screen shot 2016-09-16 at 5 00 40 pm" src="https://cloud.githubusercontent.com/assets/1126811/18604249/21d875de-7c2f-11e6-8d43-ab0c2a91a4ad.png">

**Comment by rickybanister** [comment]
That gear is set to be removed for all users once some more work happens on editing site icons so this may resolve itself.

**Comment by lancewillett** [comment]
#bug-scub

Testing this again today, still same behavior. If you are not an administrator user you still see the cog icon. If you click it, you end up at https://wpcalypso.wordpress.com/stats.

**Comment by rickybanister** [comment]
@mtias we should never have even shown the ellipsis for non-admins—they can't edit the site icon either.

**Comment by mtias** [comment]
I think the edit action is hidden if you can't manage, but the toggle was shown because we had the star mechanism that worked for anyone.

**Comment by rachelmcr** [comment]
#bug-scrub

Closing this issue as we no longer show a settings cog or ellipsis in the sites sidebar.
