### ISSUE TITLE
Update Support Doc Links on Two-Step Authentication Screens

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#81159]
### What

Two-step authentication doc: https://wordpress.com/support/security/two-step-authentication/

This doc is linked on the 2SA screens in Calypso. The doc was too long and difficult to follow, so I moved information for these two features into the following sub-docs:

**Security Key Authentication**: https://wordpress.com/support/security/two-step-authentication/security-key-authentication/
**Application-Specific Passwords**: https://wordpress.com/support/security/two-step-authentication/application-specific-passwords/

### Why

It would be helpful to place links to these docs in the UI, since the information can no longer be found in the main 2SA doc.

### How

Implementation is up to you. One method could be to add a "learn more" link or 'i' icon next to the title of the security key and application password sections, like so:
![Annotation on 2023-08-29 at 13-08-39](https://github.com/Automattic/wp-calypso/assets/30727666/42d681be-c5fe-4444-b2fb-b6b201027170)

(but in the style used in WordPress.com - my mockup just uses an emoji.)

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- CC @Automattic/vertex

**Comment by escapemanuele** [comment]
Hey @donalirl, I opened https://github.com/Automattic/wp-calypso/pull/82732 to add two Learn more links in that page, tell me if it is ok for you!
