### ISSUE TITLE
Launchpad: prepare pre-launch tasks for customer-home

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#81186]
After we enable skipping the fullscreen Launchpad, we need to make the pre-launch checklists work on customer-home.

The checklists are defined here: `/jetpack-mu-wpcom/src/features/launchpad/launchpad.php`

We need to check if the checklists and their tasks are compatible with customer-home. 

- Task actions are defined on `Stepper` code ( `client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.tsx` )
- Some actions are closely linked to `Stepper`, like: `goToStep( 'subscribers' );`

**Comment by valterlorran** [comment]
Closing this as we added the skip feature to all flows.
