### ISSUE TITLE
Tracking Issue: Missing styling on WPCloud (Atomic, Pressable, 51)  sites when Gutenberg is inactive

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#81216]
### Quick summary

A change in the way transients are cached for block styles in WordPress 6.3 has caused an issue where sites running on WPCloud (Atomic, Pressable, Team 51 websites) might load without styles, leading to visually broken sites.

Reactivating Gutenberg (if it's inactive) or clearing transients in CLI fixes the issue.

Core issue: https://core.trac.wordpress.org/ticket/59111
There are two PRs suggested so far, and they are currently scoped to ship in WordPress 6.3.2 (timing TBD).

Slack threads:
- p1693339633132379-slack-CB0B2G43X
- p1693336688238999-slack-C02FMH4G8

## Workaround
- Reactivate Gutenberg
or
- Run `wp transient delete wp_core_block_css_files` on CLI

### Steps to reproduce

It seems that simply deactivating Gutenberg might trigger the issue, but it's not consistent in all sites.on

### What you expected to happen

Styles should load normally on all WPCloud sites

### What actually happened

Some styles are missing when loading the site.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
This slack thread (also noted above) is the escalation thread where some additional troubleshooting and discussion is happening: p1693336688238999-slack-C02FMH4G8

**Comment by cuemarie** [comment]
📌 ACTIONS
- Triage complete
- Marked as On Hold awaiting Core Trac or Gutenberg PRs to ship

**Comment by liviopv** [comment]
Closing, considered the issue has been fixed in 6.3 patches and hasn't reocurred since.
