### ISSUE TITLE
On Self-Hosted Sites, update Jetpack Connection "Fix This" links to better guides

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#81233]
### Impacted plugin

Jetpack

### What

When a self-hosted site's jetpack connection is broken, we should link customers to guide documents that apply to their site.

### How

Right now, on an example site where I have had a self-hosted site disconnected for more than a week, I'm directed to 2 different WordPress.com guides:

![Markup on 2023-08-30 at 10:45:09](https://github.com/Automattic/jetpack/assets/27249804/99480c30-2c67-445e-a6cc-fb1a9c6f9c69)

1. https://wordpress.com/support/why-is-my-site-down/
2. https://wordpress.com/support/resolve-jetpack-errors/#jetpack-plugin-is-deactivated

The guidance in both guides is specific to sites hosted at WordPress.com, though, so this isn't super helpful.

---

Is it possible to detect if the site is self-hosted, and, if so, direct the customer to a better guide?

If not, I've also requested we add information to those guides for self-hosted customers, as another possible solution: 

- https://github.com/Automattic/en.support-docs-content/issues/2082

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- Transferred to `wp-calypso`
- CC @jeherve & @Automattic/vertex - is something like this possible?

**Comment by jeherve** [comment]
> direct the customer to a better guide?

Can you think of a better guide for self-hosted sites? Would something like this be better?
https://jetpack.com/support/getting-started-with-jetpack/troubleshooting-tips/

**Comment by cuemarie** [comment]
My go-to is often this one: https://jetpack.com/support/reconnecting-reinstalling-jetpack/ , since usually users at this stage need to reconnect Jetpack before they can do much else in Calypso.

I haven't used that Troubleshooting Tips one much, though!

**Comment by jeherve** [comment]
Would you use that URL for both links? I can certainly update that for you.

**Comment by cuemarie** [comment]
Yes, I think they could both go to that URL 👍
