### ISSUE TITLE
Reader: Remove Staging Sites

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#81240]
### Quick summary

By default, staging sites discourage search engines:

![CleanShot 2023-08-30 at 15 14 07](https://github.com/Automattic/wp-calypso/assets/42279181/f3cc30a3-a3d5-4e0b-95aa-7fbee31c544a)

But this does not exclude them from display in the Reader. They do have an indicator there that they are a staging site:

![CleanShot 2023-08-30 at 15 18 08@2x](https://github.com/Automattic/wp-calypso/assets/42279181/91cf2b0b-147a-4b48-b501-c06594c0f5c9)

Is there particular value in having staging sites displayed?

If not, we're opening up the potential for interested readers to accidentally subscribe/follow a staging site that's likely temporary and not seeing the content updates made to the live site. Followers are likely also lost when the staging site is deleted.

### Steps to reproduce

1. Create a [staging site](https://wordpress.com/support/how-to-create-a-staging-site/).
2. Search the Reader for your site name.

### What you expected to happen

To only see the primary (non-staging) site listed in the Reader.

### What actually happened

I see both sites in the results. The primary site at the top, followed by the staging site at the staging domain.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by katiebethbrown** [comment]
Another thought - Rather than just removing staging sites, would it make sense to hide everything with staging domains - ie. `*.wpcomstaging.com` and `*.mystagingwebsite.com` (from Pressable)?

Or is there another way to ensure staging sites aren't displayed that I might not be aware of?

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described! Be sure to search for the **Site Title** in reader (as noted above), as that's the best way to get both to pop up. (I missed that detail at first when testing 😌)

![Markup on 2023-08-30 at 15:55:42](https://github.com/Automattic/wp-calypso/assets/27249804/e89aa2bb-0673-466c-bdf8-7ef1e6ff453f)

📌 ACTIONS
- Triage complete
- @Automattic/loop

**Comment by davemart-in** [comment]
Thanks for the heads up @katiebethbrown.

> nother thought - Rather than just removing staging sites, would it make sense to hide everything with staging domains - ie. *.wpcomstaging.com and *.mystagingwebsite.com (from Pressable)?

> Or is there another way to ensure staging sites aren't displayed that I might not be aware of?

I'm also going to ping @danielbachhuber to see if he has any suggestions.

**Comment by danielbachhuber** [comment]
@davemart-in There's a bit we can reference to filter out staging sites.

Should we only prevent them from being displayed in the Reader, or should we prevent them from being followed entirely?

**Comment by davemart-in** [comment]
@danielbachhuber I'd probably say both. I can't think of a scenario where you'd want to follow a staging site.

**Comment by katiebethbrown** [comment]
> They do have an indicator there that they are a staging site:

Ha, I just realized this is the tagline on the site, not any sort of indicator. Doh. 😆

**Comment by kozer** [comment]
Backend: code-D120849

**Comment by kozer** [comment]
Fixed with the above diff
