### ISSUE TITLE
Reader: Carousel block doesn't render as on the website

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#81255]
### Quick summary

When using a Carousel block, instead of seeing the component the same as on the website, we'll see the posts listed one after another.

This appears to be somewhat similar to the Slideshow block: https://github.com/Automattic/wp-calypso/issues/45122

### Steps to reproduce

1. Add a Carousel block on a new post
2. Publish it and review the results

### What you expected to happen

To see the Carousel block as on the website

### What actually happened

The posts are rendered one by one like so:

![tDQGf2.png](https://github.com/Automattic/wp-calypso/assets/6737345/cfcf0a70-07fa-4ff4-a673-ad64bffbdd33)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

6701117-zen

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on Simple and AT - the `Post Carousel` block renders as a list of posts in the reader's view of the post. 

Live Site Post:

https://github.com/Automattic/wp-calypso/assets/27249804/04a066a8-9110-4854-9d1c-f74b0c21ffc1

Reader (Search Results):

![Markup on 2023-08-31 at 12:23:10](https://github.com/Automattic/wp-calypso/assets/27249804/fa2f5276-3368-47f1-8542-3f7feca17ecf)

Reader (Post Itself):

https://github.com/Automattic/wp-calypso/assets/27249804/cd3aa09e-464c-4c78-9c0b-24e0d4bfc25f

📌 ACTIONS
- Triage complete
- FYI @Automattic/loop

**Comment by davemart-in** [comment]
Thanks for the detailed report @Robertght! Thanks for the testing report @cuemarie!

We've got a handful of blocks that still don't render well in the reader. The trouble is we have to duplicate styles for each individual block. I'll see if we can round some of these block rendering issues up into a single project.

I added this one to our bugs board.

**Comment by sixhours** [comment]
This has been addressed by https://github.com/Automattic/wp-calypso/pull/84833
