### ISSUE TITLE
Facebook sharing button inconsistently fails to render when set to "Official buttons" style

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#81251]
### Quick summary

Facebook sharing button doesn't render when it's set to "Official buttons" style on some themes. This can be replicated only on Atomic sites.

### Steps to reproduce

1. Activate the theme "Colinear".
2. Go to Tools > Marketing > Sharing Buttons.
3. Make sure the Facebook sharing button is enabled, and the "official buttons" style is selected. 
4. View a post/page where the sharing buttons are visible.

### What you expected to happen

Facebook sharing button appears like this:

![Screen Shot on 2023-08-31 at 11:11:50](https://github.com/Automattic/wp-calypso/assets/32432463/21c7b275-3d80-427b-a7ee-7204c2985176)

### What actually happened

Facebook button doesn't appear on an Atomic site:

![Screen Shot on 2023-08-31 at 11:12:17](https://github.com/Automattic/wp-calypso/assets/32432463/29e61d00-af67-4b5e-afb8-4a7bac623085)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

**Workaround:**
Switching to a different "button style" fixes things, as only the "official button" style seems to be affected.

I tested this only with "Colinear "so far, but it appears other themes are being affected too seeing the comment [here](https://github.com/Automattic/themes/issues/6887#issuecomment-1699934803) by @supernovia. 

Initially reported in 6646376-zen (customer needs a follow-up once this is resolved).

**Comment by hacchism** [comment]
**Update**
I just tested on other themes like Twenty Sixteen, Twenty Twenty-Two, Montagna too and could replicate the issue. So it appears this happens on both classic and FSE themes.

**Comment by jp-imagines** [comment]
Ran into a report with the same behavior on a Simple site with the `Ascetica` theme: 6750852-zd-a8c

Behavior is the same as in the screenshot from the other issue (copied below).

![](https://user-images.githubusercontent.com/3476361/264487483-a8c2c3f7-19d7-4723-b044-cf4a708368f1.png)

**Comment by cuemarie** [comment]
Thanks all for the new report and notes!  On my first swing, I can see the Facebook Official Button rendering properly on an AT site using Colinear - so it seems there's more to this than just the theme! 🤔 Will work on tracking down any patterns behind this today 👍 


https://github.com/Automattic/wp-calypso/assets/27249804/4f2c3681-aebc-40a9-820c-7a49869c4e97

**Comment by cuemarie** [comment]
Hmm, it's possible this is related to browser cookies? 🤔 Here's the same post on the same site, loading in a regular FF window, followed by a private window:


https://github.com/Automattic/wp-calypso/assets/27249804/f76f62cf-b494-4973-9fdf-176ed1ee9db3

---

In the standard window, I can see this notice regarding Facebook's URL on the page: 

![Markup on 2023-08-31 at 11:41:32](https://github.com/Automattic/wp-calypso/assets/27249804/23611edf-c1cc-45f1-b19c-cd1b21ee7609)

And in my Firefox settings, I see that Tracking content is enabled for Private windows, so it seems like that might be an explanation for what I'm seeing:

![Markup on 2023-08-31 at 11:44:24](https://github.com/Automattic/wp-calypso/assets/27249804/6bf019d1-5516-4f2c-a3a7-4dfb1c3c1ebe)

---

That said, I switched the Simple site in 6750852-zen to "Official Buttons" again and reloaded their site in my normal browser window, and the Facebook button did indeed fail to load.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic –Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
So far I've tested on AT with themes Colinear and Twenty Sixteen, and on Simple with themes Ascetica and Colinear.  In all test, the Facebook official sharing button renders as expected in my normal browser window, while private browsing sessions do not render any of the official buttons - I assume this has to do with my logged out state and content tracking in private windows.

| Firefox Browser | Private Firefox Browser |
| ------------- | ------------- |
| ![Markup on 2023-08-31 at 12:04:06](https://github.com/Automattic/wp-calypso/assets/27249804/0ada9825-dc5b-4ff5-bea3-c6e8e330dabd) | ![Markup on 2023-08-31 at 12:04:30](https://github.com/Automattic/wp-calypso/assets/27249804/82f801e7-8d84-4461-ac37-23159cbe08ae) |

However, the user sites mentioned above do not show the Official Button version of Facebook's sharing button even when I check them from a normal browser window.

📌 ACTIONS
- @jeherve can you perhaps take a look and spot anything I'm missing here?

**Comment by jeherve** [comment]
I'm afraid there isn't much we can do to fix this. Official buttons load third-party content on your site; sometimes it's just via an iFrame, sometimes it's additional JavaScript. In any case, it can rely on resources (JavaScript, cookies, trackers, ...) that may be blocked in some browsers or browser configurations.

The best way to have sharing buttons that will work in every browser would be to use non-official buttons. They'll also load faster and not do anything to track visitors (until they decide to click on a button and load a third-party site, of course), so that's a plus! :)

**Comment by cuemarie** [comment]
📌 ACTIONS
- Closed as won't fix (based on previous comment)
