### ISSUE TITLE
Site Monitoring: Improve messaging around Webserver Log exports

### ISSUE THREAD

**Issue by hideandgeek404** [Automattic/wp-calypso#81262]
### Quick summary

The current [support document](https://wordpress.com/support/site-monitoring/#php-logs-and-webserver-logs) suggests keeping exports to 10,000 results for the export to be successful. This is because the export is resource heavy on the system and larger queries can cause Out of Memory (OOM) errors when running. 

This issue should cover two things:
1) The messaging around these limitations does not exist within the Calypso interface at all. The error message that appears when the OOM error occurs does not describe the issue, merely stating `Failed to retrieve logs.`

2) When doing larger queries, the visual output is limited to 10,000 results regardless of how many results there actually are as this is a display limitation but I suspect that if we were to click `Download logs` at this point it may run the query without the display limitation in place and try to export more than 10,000 entries which then causes confusion for customers who are being told to export 10,000 at a time but the display suggests they are. 

### Steps to reproduce

1. Visit ` Tools > Site Monitoring`
2. Click the `Webserver Logs` tab
3. Choose two dates far apart that generate a large number of results (typically that might be an entire month on a quiet site, or a week on a busy site)
4. Visually check the result number at the bottom of the screen and you'll see 10,000 is the largest number shown
5. Click the `Download Logs` button and wait for the export to fail, you'll see the error message in the top right

### What you expected to happen

Firstly, the messaging around this export functionality should be shown on the page, either in a tool tip, in text on the screen, or lining to the support document. The support document should also be updated to reflect any changes we make.

I would expect, based upon the Support document, that any result the visually returns 10,000 results or less should export fine.

### What actually happened

Because of the visual output limitations to 10,000 results, even if my original query in the background returned more than 10,000 results, I would see the `Failed to retrieve logs.` error message which creates confusion.

The workaround is to reduce the number of results by setting dates closer together until the result number at the bottom is **less than** 10,000 rather than 10,000 exactly. The lower the number, the more likely the export will work.

### Impact

All Atomic Customers

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
📌 ACTIONS
- Relabeled as an enhancement to the current design
- Triage complete

**Comment by hideandgeek404** [comment]
This has just occurred while talking to a customer, this seems to confirm the point above about the display showing a maximum of 10,000 log items, but the download running a query that returns many more.

![image](https://github.com/Automattic/wp-calypso/assets/81396999/f4e42387-1d48-408c-82f0-453eb8d73400)

**Comment by jeroenpf** [comment]
These issues have been resolved. Downloading a larger data range no longer causes an error and the number of records shown to be downloaded is capped at 10k.
I was not able to replicate any of the issues described so i will close this one.
