### ISSUE TITLE
Assembler - Block Renderer - Revisit and clean logic for 100vh in pattern previews

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#81269]
## What

Revisit and clean logic for 100vh in pattern previews in [block-renderer](https://github.com/Automattic/wp-calypso/blob/ae2fbbb4466423a98bdabfb5fa42628aec625373/packages/block-renderer/src/components/block-renderer-container.tsx#L26)

## Why

The logic for 100vh patterns works is complex and might be possible to simplify it. 

## How

See https://github.com/Automattic/wp-calypso/pull/81208#discussion_r1311280922

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/81310
