### ISSUE TITLE
Notices: small breakpoint notice-actions can be improved

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#8127]
Notices are a very useful and therefore widely used component. This makes them somewhat fragile as we encounter edge-cases and stretch them to fit many many contexts. 

In #4269 some new flex column code was added to notices that made ugly notices like this:

![aa075ef8-ef9d-11e5-8acd-6f78e564be54](https://cloud.githubusercontent.com/assets/437258/18611453/9f70efd4-7cee-11e6-8811-cd8a7eb81c7a.png)

Look more like this:

![febe4138-f0eb-11e5-98d9-5d4b39408f73](https://cloud.githubusercontent.com/assets/437258/18611460/b3714484-7cee-11e6-8508-ab122f966d5e.png)

A definite improvement when the text is crunched and the `notice-action` is long. 

However, when the `notice-action` would otherwise fit, these new <480px breakpoint notices look bad:

<img width="464" alt="screen shot 2016-09-17 at 3 29 08 pm" src="https://cloud.githubusercontent.com/assets/437258/18611465/d63c18f4-7cee-11e6-9738-e29c0ec9e91c.png">

I have two proposals: 

We give a bit more consideration to the stacked `notice-action` since it is difficult to tell which part is button and which is not. So perhaps something like this:

<img width="543" alt="screen shot 2016-09-17 at 3 46 22 pm" src="https://cloud.githubusercontent.com/assets/437258/18611474/04964e18-7cef-11e6-9fca-fa717fe25b60.png">

And going a bit further, we start with a pure mobile-first approach to notices that make the default font-size and padding a bit smaller, a bit more like the `compact` notice:

<img width="273" alt="screen shot 2016-09-17 at 3 57 20 pm" src="https://cloud.githubusercontent.com/assets/437258/18611495/86db0ff8-7cef-11e6-8409-d0b7c2674e98.png">

cc @mikeshelton1503 @MichaelArestad @mtias @drewblaisdell @folletto

**Comment by folletto** [comment]
I like the proposal. The rounded buttons matching our default buttons in shape I think they fit better our existing design language, on top of that I agree on your assessment on mobile.

I guess on desktop it would align right similarly like a button, and I feel that works too. 👍

**Comment by rickybanister** [comment]
For desktop, I'd propose leaving it as it is currently so there's more parity between the global pill-shape notice and the square version. I feel that works fine as long as there is room for it. At least for now.

**Comment by folletto** [comment]
> I'd propose leaving it as it is currently so there's more parity between the global pill-shape notice and the square version.

I feel the button shape would be clearer, but I see the rationale behind this, I'm ok in keeping it alone too if that's the preference. :)

**Comment by MichaelArestad** [comment]
That last iteration with the pill shape seems awesome for mobile. Nice.

**Comment by mtias** [comment]
This looks great, let's implement it.
