### ISSUE TITLE
Block Inserter - Using the Plus Sign Block Inserter with the Settings Sidebar Closed can cause the Block Insertion Menu to Appear Off Screen

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#81297]
### Quick summary

One of several ways to insert blocks in Gutenberg is the Block Insertion Plus Sign, which appears at the bottom of a selected block. If the plus sign appears at the far right side of the screen and the settings sidebar is closed, sometimes the block insertion menu can appear off screen and cannot be interacted with. This happens more commonly if the browser window is narrow.

Example:
![Markup on 2023-08-31 at 16:12:54](https://github.com/Automattic/wp-calypso/assets/12906034/6fdb42cf-1f33-4aa7-8e42-2e25f8e315f7)

As a workaround, the user can open the Settings Sidebar. This will give enough real estate on the screen for the Block Insertion menu to appear.

### Steps to reproduce

1. Create a site
2. In any editor environment, make a block that has the Block Inserter Plus Sign on the far right corner of the screen. Examples: Group, Columns.
3. Make sure that the browser is sufficiently narrow, and the Settings sidebar is closed.
4. Click on the Block Inserter Plus Sign

### What you expected to happen

The Block Insertion menu should appear in a location where it can be interacted with regardless of location on the screen

### What actually happened

The Block Insertion menu appears off screen in a way that it can't be interacted with.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – **No**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Atomic and Simple sites using FSE themes. 
- Simple site on Twenty Sixteen did not reproduce the same issue.
- A self-hosted site with the same set up (TT3, GB 16.5.1, same window) opens the block search box to the left of the `+` icon, where it remains in view.

**Simple**

![Markup on 2023-08-31 at 16:18:32](https://github.com/Automattic/wp-calypso/assets/27249804/d12f63f4-304e-45ab-8399-143ec4f3abbc)

**Atomic compared to Self-Hosted**

https://github.com/Automattic/wp-calypso/assets/27249804/00d30369-ae24-4897-839a-7cb518a23484

---

On my AT site, the issue replicated in versions:

- 16.5.1
- 16.5.0

But **did not occur** once I reached:

- 16.4.0

![Markup on 2023-08-31 at 16:23:06](https://github.com/Automattic/wp-calypso/assets/27249804/6388f375-d39f-4966-a460-66a7ba815d74)


📌 ACTIONS
- Triage complete
