### ISSUE TITLE
LOTS start/with-theme flow should go to blog flow if theme is blog

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#81299]
# Description

* Requested by @simison .  See pb5gDS-38f-p2#comment-4091
* Discussion: LoTS should go to blog flow if people pick a theme from the blog category  pekYwv-2LO-p2

![Image](https://user-images.githubusercontent.com/5665959/264788177-98f171e0-9680-4c9a-91ac-008659ccda39.png)

Currently when a user chooses a blog theme and then continues to signup & onboarding then go they land on the preview of the theme, like this:

![Image](https://user-images.githubusercontent.com/5665959/264788872-6c4abee1-9dbf-4c5b-bb06-28633a61fa7c.png)

**Comment by arthur791004** [comment]
There is an issue related to the premium themes. See pekYwv-2LO-p2

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/81400. The changes will affect only free themes now and we can consider how to support premium themes later.
