### ISSUE TITLE
Plugins: Make author link on plugin meta more noticeable

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#813]
Right now, you can't tell that the author name on the single plugin page is actually a link. Can we make that somehow more prominent?

Here is a screenshot:
![screen shot 2015-11-25 at 5 24 56 pm](https://cloud.githubusercontent.com/assets/11487924/11410968/c5455a36-9399-11e5-825f-c310a97206ee.png)

A suggestion from rickybanister: I could see this being $blue-wordpress with the standard hover color.

It would also be interesting to browser plugins by the plugin author (when that becomes available in the API) - this is tracked in #821

**Comment by enejb** [comment]
I think this should be fixed now. 
![screen shot 2016-01-25 at 14 17 27](https://cloud.githubusercontent.com/assets/115071/12566475/ae61aa54-c36e-11e5-95f8-e53dd049dc8f.png)
