### ISSUE TITLE
Marketplace Themes on Onboarding: Add eligibility modal

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#81316]
pdh6GB-3as-p2

Add Eligibility modal for non-atomic sites when proceeding to purchase a Marketplace Theme.

**Comment by epeicher** [comment]
The eligibility modal should add the `Business` plan to the modal but the `features` endpoint is returning unexpected features for Free sites. Additional investigation is required about why this function is returning those features for a Free site fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Sfgber%2Qcebqhpg%2Qyvfg.cuc%3Se%3Qqs3n4p8o%232040-og

**Comment by epeicher** [comment]
After some initial investigation and some help from @gcsecsey I have added an estimate to this task of 2 points as it requires to add the modal and some debugging of existing logic to display it.

**Comment by epeicher** [comment]
Uploading a `zip` file theme to a non-atomic Business site displays an _Eligibility_ page that I will use to get the content for the _EligibilityModal_ 
<img width="600" alt="CleanShot 2023-09-07 at 16 53 58@2x" src="https://github.com/Automattic/wp-calypso/assets/3519124/7a5d5278-3d17-4861-9177-1db35281c936">

**Comment by epeicher** [comment]
The priority of this task has been decreased as the follow-up task will be progressed first:
- https://github.com/Automattic/wp-calypso/issues/81597

**Comment by epeicher** [comment]
After the following conversation p1694531856498649/1694526585.127239-slack-C02JPCHEKDY, we decided to progress with this task and upgrade it to Blocker
