### ISSUE TITLE
Reader/StreamBuilder: Pagination on the FollowedStream doesn't work

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#81325]
We've added a new `FollowedStream` in D120539-code but it doesn't have pagination.

The underlying code requires a page number while the rest of the `/read/streams/discover` streams use an offset/limit approach so it's going to require some discussion about how best to implement pagination.

We may not be able to use the existing underlying code. It may be easier to talk about how the `Followed` functionality should work and write it from scratch to be more in line with the stream-builder way of doing things.

**Comment by andres-blanco** [comment]
Working on D120683-code

**Comment by andres-blanco** [comment]
Now it does :)
