### ISSUE TITLE
Plans 2023: Remove dependency on touch-detect lib

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#81349]
https://github.com/Automattic/wp-calypso/pull/80082 introduced a dependency on [touch-detect lib](https://github.com/Automattic/wp-calypso/blob/e04831eeab415f7a7276229ec9036e3ee4380d90/client/lib/touch-detect/index.js) for enabling tooltips on the pricing grid in mobile devices. @southp says https://github.com/Automattic/wp-calypso/pull/80082#discussion_r1299655202 to extract the contents of touch-detect inside the plans grid https://github.com/Automattic/wp-calypso/pull/80082#pullrequestreview-1588980463. This is a tracking issue to address the dependency on the touch-detect lib as part of the NPM extraction project.

**Comment by chriskmnds** [comment]
@niranjan-uma-shankar @southp Is either of you planning to work on this any time soon? 
I will reassign and take over if you don't.

**Comment by niranjan-uma-shankar** [comment]
Hi @chriskmnds , if it's not urgent I can pick this up next week. If it's needed to be landed earlier than that, I'd appreciate if someone can take over.

**Comment by chriskmnds** [comment]
> Hi @chriskmnds , if it's not urgent I can pick this up next week. If it's needed to be landed earlier than that, I'd appreciate if someone can take over.

Thanks, @niranjan-uma-shankar. Happy to take over 👍
