### ISSUE TITLE
Add info/link about Calypso Horizon to README

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#8134]
[horizonfeedback.wordpress.com](https://horizonfeedback.wordpress.com) and [horizon.wordpress.com](https://horizon.wordpress.com) should be used as places where the community and makers of WordPress.com can come together and talk about upcoming changes. However, we don't advertise the info about Horizon anywhere on this repo (as far as I can see).

I suggest we add a short paragraph to [README](https://github.com/Automattic/wp-calypso/blob/master/README.md) about Horizon, how outside contributors can help test new things and links to it.

/cc @folletto @rralian

**Comment by folletto** [comment]
Our README is quite lean, so I'd like to keep it that way. I think a good starting point could be to rephrase the current "Contribute" section.

Here's the current version for reference: 

> ## Contributing
> 
> If Calypso sparks your interest, don’t hesitate to send a pull request, send a suggestion, file a bug, or just ask a question. We promise we’ll be nice. Just don’t forget to check out our CONTRIBUTING doc – it includes a few technical details that will make the process a lot smoother.
> 
> Calypso welcomes – and indeed has been built by – contributors from all walks of life, with different backgrounds, and with a wide range of experience. We're committed to doing our part to make both Calypso and the wider WordPress community welcoming to everyone.
> 
> To clarify these expectations, Calypso has adopted the code of conduct defined by the Contributor Covenant. It can be read in full here.

Here's a proposal:

> ## Contributing
> 
> If Calypso sparks your interest, don’t hesitate to send a pull request, send a suggestion, file a bug, or just ask a question. We promise we’ll be nice. Just don’t forget to check out our CONTRIBUTING doc – it includes a few technical details that will make the process a lot smoother.
> 
> Calypso welcomes – and indeed has been built by – contributors from all walks of life, with different backgrounds, and with a wide range of experience. We're committed to doing our part to make both Calypso and the wider WordPress community welcoming to everyone.
>
> You can contribute in many ways. You can help reporting, testing, and detailing bugs, and also testing any new feature we release in our "beta" program for testing on Horizon.
> 
> To clarify these expectations, Calypso has adopted the code of conduct defined by the Contributor Covenant. It can be read in full here.

"Horizon" would be linked to horizonfeedback.wordpress.com

**Comment by designsimply** [comment]
+1 for @folletto's revision of the Contribute section and for keeping the README lean. A small suggestion for the revised text would be to change this:

> and also testing any new feature we release

to this:

> and also test new features we release

The first one sounds to me like we release every new feature for beta testing, which we do not.
