### ISSUE TITLE
Some WPcom pages inaccessible with VPN enabled

### ISSUE THREAD

**Issue by djlawrie** [Automattic/wp-calypso#81360]
### Quick summary

Wordpress accounts/payment screen not populating when VPN is on (using NordVPN on a Windows 11 computer).

### Steps to reproduce

1. Be sure VPN is on. I am using NordVPN with default settings. I am located in the US and the NordVPN server is also in the US.
2. Open wordpress.com and sign in.
3. Select you gravitar (upper right).
4. Select Purchases.
5. After a while, get "We're sorry, but an unexpected error has occurred."
6. Turn off VPN and refresh page.
7. Page loads immediately with correct information.

### What you expected to happen

Should have seen Purchases page.

### What actually happened

Got error message: We're sorry, but an unexpected error has occurred.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

Workaround isn't obvious and it took 3 exchanges with support before it was suggested that I try to access the purchases screen on another device. The alternate device I used, a Windows 11 loptop, shows the VPN dialogue when booting and noted that the VPN wasn't turned on by default. I then immediately realized what the problem was. However, if I tried to access the Purchases screen on my phone or iPad, it would have been quite a while before I realized what the problem was because the VPN isn't on by default on my phone and the iPad uses Norton's VPN which is always on and provide any feedback when the iPad is started.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Unable to replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Tried replicating on **MacOS 13.5.1** using up-to-date Firefox and Chrome browsers alongside NordVPN.  So far, with the VPN active or inactive, I'm able to log back in to my WordPress.com account and load the `https://wordpress.com/me/purchases` as expected

https://github.com/Automattic/wp-calypso/assets/27249804/f1402306-1aaf-4390-8489-301d8fabded6

📌 ACTIONS
- While I wasn't able to replicate for triage, I wonder if @Automattic/shilling can weigh in here with thoughts/next steps on this behavior that seems to stem from the customer's VPN. Anyone have a Windows 11 device to try that set up as well?

📌 Message to Author
@djlawrie thanks for your thorough report on this issue!

**Comment by sirbrillig** [comment]
> While I wasn't able to replicate for triage, I wonder if https://github.com/orgs/Automattic/teams/shilling can weigh in here with thoughts/next steps on this behavior that seems to stem from the customer's VPN. Anyone have a Windows 11 device to try that set up as well?

There's nothing special that I can think of about the purchases page compared to the rest of calypso. If the user has trouble accessing the purchases page, it's likely that they will have trouble accessing any page in calypso that relies on the REST API.

**Comment by cuemarie** [comment]
@sirbrillig that makes sense - thank you!

📌 ACTIONS
- Relabeled as needed
- Inquiring internally with calypso folks to see if this kind of behavior is expected: p1694118215553089-slack-C02DQP0FP

**Comment by davemart-in** [comment]
This issue seems limited to one user and has not seen any traction in over a year. I'm closing it out.
