### ISSUE TITLE
Paid Stats: Show upgrade notice for commercial sites with personal or free plan

### ISSUE THREAD

**Issue by annacmc** [Automattic/wp-calypso#81361]
Related to #81058

We'd like the Commercial upgrade notice to show if:

It's a commercial site

1. Without any paid plan
2. Or only have Personal or Free plan

Point 1 is implemented in #81254. Now we need to address point 2 in a follow up PR.

**Comment by annacmc** [comment]
Just wanting to clarify on this issue @kangzj - this means that we'd like the Commercial upgrade notice to show if the site is both a commercial site, AND has a WPCOM personal or free plan? 

BUT NOT if it is flagged as Commercial AND has a WPCOM Premium/Business etc plan?

Am I correct here?

**Comment by kangzj** [comment]
> BUT NOT if it is flagged as Commercial AND has a WPCOM Premium/Business etc plan? Am I correct here?

Hi @annacmc, Good question! Yes exactly. Let's leave all WPCOM sites for now. We'll tackle that in Paid Stats for WPCOM project, because the plan for WPCOM sites has not finalized yet really.  😃

**Comment by a8ck3n** [comment]
I'm looking into this one now.

The comments above refer to DotCom plans which we aren't addressing now. Instead, I'll test Jetpack-connected sites with free plans and legacy Personal plans and update this Issue with any needed tasks.

**Comment by a8ck3n** [comment]
So in my testing of Jetpack-connected sites with legacy plans, the notice shows for all plans. I tested this against the Personal, Premium, and Professional plans. But after reviewing the code and re-reading the ticket notes, I'm thinking I'm testing for the wrong thing here.

Are we testing for sites that have a free Stats or paid PWYW Stats plan?

I think we have the necessary info in the `hasFreeStats`, `hasPaidStats`, `isCommercial` values so I'll test these scenarios first.

**Comment by a8ck3n** [comment]
Hey @kangzj. I started work on this but wanted to clarify that I'm moving in the right direction. Can we summarize this ticket as "show the commercial upgrade nudge on commercial sites without a commercial license"? — Excluding DotCom, Team 51, & VIP. As it's currently written and based on the discussion in the related tickets, I'm finding it a bit confusing.

If that is what we're looking to do here, I have it working in the linked Draft PR. I'll pick that up again once we sync up on the goal for this one.

**Comment by a8ck3n** [comment]
Changes have shipped!

**Comment by a8ck3n** [comment]
Second attempt at detecting commercial sites with PWYW plans. This time around it checks for any plan considered to be paid including the Complete bundle.
