### ISSUE TITLE
Paid Stats: Fix link to the commercial plan flow

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#81379]
After introducing the new purchase pages, the link within the notice for the personal plan purchase flow no longer redirects to a commercial flow.

We need to fix it and possibly prepare to remove the old logic if we decide to retire the wizard. 
When working on the task, ensure the original functionality is not broken (the new flow is behind a feature flag, so some customers still use the old wizard).

![Image](https://github.com/Automattic/wp-calypso/assets/112354940/fe508541-223e-41ce-968a-f1d8cdc04539)

**Comment by kangzj** [comment]
Thanks for picking this up @annacmc  👍 

I'd like to add a little bit of information - you could pass `productType` in the URL to switch products, e.g.

https://github.com/Automattic/wp-calypso/blob/b657734d4bae817eaea5d8ceef975a98ac4c2d95/client/my-sites/stats/stats-purchase/stats-purchase-notice.jsx#L15
