### ISSUE TITLE
Zip upload containing Better-Mouse mac application file blocked on Atomic, but allowed on Simple sites

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#81371]
### Quick summary

In triaging https://github.com/Automattic/wp-calypso/issues/80816 we discovered that ZIP files obtained from https://better-mouse.com/ are successfully uploading to Simple sites, but blocked from being uploaded on Atomic.  

### Steps to reproduce

1. Download the zipped file linked here: p1693872044629999/1693853856.624759-slack-CQD1HH4MA
2. Upload to an Atomic site via the default Media library (Calypso)
3. Upload to an Atomic site via the classic Media library (wp-admin)
4. Upload to a Simple site via the default Media library (Calypso)

### What you expected to happen

Either:

- the file upload to be allowed in all environments
- the file upload to be blocked in all environments
- the file upload to be allowed in Atomic environments but not Simple, if it's a more advanced/higher security risk file type

### What actually happened

File is blocked in Atomic Calypso, but allowed in WP-Admin, and allowed on simple sites.

**Atomic Calypso:**

<img width="683" alt="Screenshot 2023-09-04 at 4 43 43 PM" src="https://github.com/Automattic/wp-calypso/assets/27249804/530cdbd0-833e-449b-887b-60251ec50c5d">

Console Log:
```
Uncaught (in promise) PluginMaliciousError: The uploaded file is identified as malicious.
    e https://wordpress.com/calypso/evergreen/72733.89944286416db92d3290.min.js:2
    x https://wordpress.com/calypso/evergreen/91021.9e343af9df2ca07f42d2.min.js:2
```

**Atomic WP-Admin:**

File uploads without issue

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

It appears this could be related to https://github.com/Automattic/wp-calypso/issues/50928 . @dsas can you take a look?

A bit more discussion on this can be found here: p1693438480234909-slack-C036E4KFP2L

**Comment by dsas** [comment]
#50928 brought parity to simple and atomic sites for the types of file allowed to be uploaded. The practical difference was:

 * Atomic sites newly got the ability to upload .zip, keynote files etc using calypso
 * Simple sites newly got the ability to upload tiff, bmp and txt files using calypso

Atomic sites could already upload zip files etc via wp-admin.

Instead it looks like this particular file is being blocked by either fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Spynff.wrgcnpx%2Qpyvrag.cuc%3Se%3Qponr1s10%23743-og or fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Spynff.wrgcnpx%2Qpyvrag.cuc%3Se%3Qponr1s10%23759-og which is only ran on Atomic calypso.

I've asked yamato about this: p1700317696690639-slack-C029WFNV69M

**Comment by davemart-in** [comment]
Seems edge case with no updates in about a year. Closing this issue.
