### ISSUE TITLE
Site Editor: Direct "Manage All Pages" Link to Calypso

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#81390]
In the Site Editor's navigation sidebar, the "Manage all pages" link currently directs to wp-admin.
On Dotcom sites, it should direct to whichever the user preference is: either Default/Calypso or Classic/wp-admin views.

![image](https://github.com/Automattic/wp-calypso/assets/2070010/d3c014b8-9d16-45fc-95c4-d4c544f9c9ed)

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO

On both Simple & AT, I can replicate that "Manage All Pages" directs to the wp-admin Pages dashboard:

https://github.com/Automattic/wp-calypso/assets/27249804/035fe4fe-0e33-476f-90c9-6a371e4370a9

📌 ACTIONS
- Triage complete
