### ISSUE TITLE
Action Bar: Link "Edit Site" to Actual Current Template 

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#81391]
In WP 6.3, [the "Edit Site" button in the admin bar opens the Site Editor to the current template](https://core.trac.wordpress.org/changeset/56209).

For example, if you are viewing a post, it would open the Single Posts template.

This does not happen in the Dotcom's Action Bar.

![image](https://github.com/Automattic/wp-calypso/assets/2070010/6c6c9bb9-6e87-4054-9050-eceb3762ff4e)

...but it should!

**Comment by mmtr** [comment]
D120807-code
