### ISSUE TITLE
Launchpad: Onboarding screen appears for few seconds before returning to My Home

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#81404]
The onboarding launchpad appears for a few seconds when returning from the Editor to My Home.

https://github.com/Automattic/wp-calypso/assets/7931304/35c2c89c-1493-40d2-be53-681f6e457ce0

### Steps to Reproduce

1. - Go through onboarding and select the Build intent (`Promote myself or business`)
2. - Launch the site.
3. - Go to My Home and select the 'Add a new page' task in the checklist.
4. - Will be directed to the editor: Save a draft or publish.
5. - Go to 'Next steps on the left sidebar.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I've seen this behavior before, but I'm not sure how to replicate it intentionally.  @nuriapenya do you recall the steps you took that lead to this behavior?  Here's what I tried that did not result in the same issue:

```
- WordPress.com/start
- free domain and plan
- selected: Write & Publish
- selected: Choose a design (didone) > continue
- published a post
- launched my site (via launchpad)
- opened Appearance > Editor and return to dash
- opened post and returned to dash
```

```
- WordPress.com/start
- free domain and plan
- selected: Write & Publish
- selected: Choose a design (luminance) > continue
- arrive in post editor - return to Next Steps without publishing a post
- Select "Skip for now"
- launched my site (via site settings page)
- skip domain & plan purchases
- arrive on My home
- Posts > Add new post
- save as draft and return to editor
```

📌 ACTIONS
- Requested author feedback

**Comment by nuriapenya** [comment]
Hey @cuemarie, thanks for testing.

The video above is based on a `Build` intent after launching. These are the steps:

* Go through onboarding and select the `Build` intent 
* Launch the site.
* Go to My Home and select the 'Add a new page' task in the checklist.
* Will be directed to the editor: Save a draft or publish. 
* Go to 'Next steps on the left sidebar.

Then, the Onboarding Launchpad is loaded for a few seconds.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described using the steps above!

https://github.com/Automattic/wp-calypso/assets/27249804/7abd7b27-f266-4c0a-951e-6f5377a207c4

**Repeating the My Home > Add new page > exit editor steps, but with browser console open**

https://github.com/Automattic/wp-calypso/assets/27249804/a4e9ed8b-ca12-4a34-98e4-6974c86871df
