### ISSUE TITLE
Feature Conflict: Google Docs embed code is an iframe, which we strip on simple sites.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#81431]
### Quick summary

The current Google Docs embed process breaks on simple sites due to our existing code restrictions.

### Steps to reproduce

1. Create, or log into, any simple site. Do not do this on an atomic or self-hosted site as you will not see the issue.
2. Create a new post or page on this site.
3. Follow [this process](https://wordpress.com/support/google-docs/) to embed a Google doc.

### What you expected to happen

If I follow the process outlined above, the Google doc should display on my site using the embed code I was guided to generate.

### What actually happened

The embed code includes an iframe, which [we strip out](https://wordpress.com/support/code/) on simple sites.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Issue is not theme dependent, and I was able to reproduce this issue on a test site that is only set up explicitly for testing and has no other content on it. Site was a free site, user was Personal.

**Comment by arinoch** [comment]
We can follow up with the user in 6775036-zd-a8c if we intend to resolve this issue one way or the other.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
While we do strip out `iframe` code, following the steps in our guide on a Simple site results in the `iframe` getting updated to `[googleapps domain="docs" dir=...` shortcode, which does embed the Google doc as expected.

Free Test Site:

https://github.com/Automattic/wp-calypso/assets/27249804/316b42d2-3962-44c4-bd2d-5ad9f9aaaa49

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@arinoch I'd recommend having the user double check the sharing permissions on the Google Document itself - if it is not set to public, that could be impacting WordPress.com's ability to connect to that Google doc.
