### ISSUE TITLE
Live Preview: Disable the Custom Styles upsell when clicking Styles

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#81438]
## Description

Currently, the Custom Styles upsell modal shows as soon as users click on the "Style" navigation item. The experience might be jarring, so let's revisit this logic.

https://github.com/Automattic/wp-calypso/assets/797888/31a9a5b7-20d7-4350-b252-d4f0febde7f7

## Acceptance Criteria
- [ ] Finalize with stakeholders what the appropriate response should be.

cc: @autumnfjeld @okmttdhr

**Comment by autumnfjeld** [comment]
> Currently, the Custom Styles upsell modal shows as soon as users click on the "Style" navigation item. The experience might be jarring, so let's revisit this logic.

It only displays once correct?  I mean once per site.  So only for new sites?  In this ok it seems ok.

**Comment by taipeicoder** [comment]
Yes, this seems to be a non-issue at the moment. Closing.
