### ISSUE TITLE
Update name of plan from eCommerce to Commerce in Calypso

### ISSUE THREAD

**Issue by emilyaudela** [Automattic/wp-calypso#81462]
### Quick summary

There are a few instances in Calypso where we still refer to the Commerce plan as the eCommerce plan. This should be changed to `Commerce` to reflect the [current plan name](https://wordpress.com/pricing/).  

### Steps to reproduce

1. Start at https://wordpress.com/earn/
2. Go to `Collect PayPal payments` card. 
3. Text says `Available only with a Premium, Business, or eCommerce plan.` Should say `...Commerce plan`.

1. Start at https://wordpress.com/marketing/tools/
2. Go to the Facebook card.

### What you expected to happen

I would expect not to see `eCommerce plan` in the software since this doesn't exist. These should all be replaced with `Commerce plan`. 

### What actually happened

The text says "eCommerce" plan and not "Commerce" plan.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Free Site – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

Tools > Earn > "Collect Paypal Payments" card:

![Markup on 2023-09-06 at 15:22:41](https://github.com/Automattic/wp-calypso/assets/27249804/1cd5298f-f357-4242-833f-5cf8996a7b52)

Tools > Marketing > "Want to connect with your audience on Facebook and Instagram?" card:

![Markup on 2023-09-06 at 15:23:09](https://github.com/Automattic/wp-calypso/assets/27249804/2dcce239-6a54-42da-9831-cf26e83b1111)

📌 ACTIONS
- Triage complete
