### ISSUE TITLE
Unclear Upgrade Nudge on Partner Themes

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#81493]
### Quick summary

On the pages of Parter themes, it displays this prompt:

> Upgrade to a Business plan and subscribe to this theme!
> Unlock this theme by upgrading to a Business plan and subscribing to this theme.

At first glance, it seems that upgrading to the Business Plan would be enough to use the theme.  However, after upgrading, using the theme requires another subscription that requires payment.

Would it be possible to improve the messaging and make it clearer that the theme requires another subscription?  Perhaps add this disclaimer:

>Using this theme requires a separate subscription in addition to upgrading to a Business plan.

Thank you!

### Steps to reproduce

1. Visit https://wordpress.com/theme/olsen-fse/
2. Select a site that's on the Premium Plan or lower
3. Upgrade to the Business Plan using credits
4. Come back to the theme page

### What you expected to happen

I expected to be able to activate the theme on my site.

### What actually happened

I'm not able to activate the theme unless I purchase another subscription.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I see what you mean, this does feel a bit confusing!

![Markup on 2023-09-07 at 12:37:30](https://github.com/Automattic/wp-calypso/assets/27249804/683e9053-8995-41ff-942c-7531a6b96334)

📌 ACTIONS
- FYI @Automattic/t-rex ~or possibly @ Automattic/martech~ ?

**Comment by dsas** [comment]
Thanks! We're actually working on this area now and will soon be removing the 'Upgrade to a business plan' banner, see paYJgx-3TE-p2#comment-4060

**Comment by cuemarie** [comment]
Awesome, thanks @dsas ! Feel free to close this in favor of that p2, or we can leave open for tracking until that update comes through. 👍

**Comment by Copons** [comment]
Hi folks! I'm going to close this issue as (as mentioned already) this whole area is being actively worked on.

We are tracking the project at https://github.com/Automattic/dotcom-forge/issues/2227.
We'll first update all the modals (https://github.com/Automattic/wp-calypso/issues/78694), and then remove the upsell banners.
It will take time (there are many modals and not much consistency across them 🙂), but we'll get there eventually.
