### ISSUE TITLE
RLT punctuation shows at the start of the paragraph 

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#81502]
### Quick summary

Site is set to Arabic language, and uses RTL. When adding English text, the punctuation moves incorrectly to the beginning of the line. 

### Steps to reproduce

1. Switch site language and account language to Arabic
2. Create new post (should show as RTL)
3. Write a sentence, add punctuation, you'll see the punctuation move to the beginning of the phrase. 

### What you expected to happen

I would expect the punctuation marks to stay in place in the sentence and not jump to the beginning of the line. 

### What actually happened

Punctuation marks jump to the start of the line. 
![Screen Capture on 2023-09-07 at 10-43-32](https://github.com/Automattic/wp-calypso/assets/44442769/c8cd8838-a8dc-40e6-9d1d-d600b8a7759e)

Recommended they add the punctuation at the start so it saves correctly. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
Duplicate of https://github.com/Automattic/wp-calypso/issues/61740
