### ISSUE TITLE
Update Support Doc Link in Upgrade Credit Banner

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#81501]
### Quick summary

The **upgrade credit** banner currently links to: https://wordpress.com/support/manage-purchases/#upgrade-credit

This is the new link to change it to: https://wordpress.com/support/manage-purchases/upgrade-your-plan/#upgrade-credit

### Steps to reproduce

On any site with a paid plan:

1. Go to the plans page: https://wordpress.com/plans/ 
2. View the upgrade credit banner that says:

> We’ve applied the €96.00 [upgrade credit](https://wordpress.com/support/manage-purchases/#upgrade-credit) from your current plan as a deduction to your new plan, below. This remaining credit will be applied at checkout if you upgrade today!

<img width="518" alt="upgrade credit" src="https://github.com/Automattic/wp-calypso/assets/30727666/3e8b45af-d7ed-4730-8357-7474dafd81c4">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

The reason for the change is that the [Manage Purchases doc](https://wordpress.com/support/manage-purchases/) is too long and difficult to follow. We are breaking it up into smaller, more focused docs.

The new docs are live, but I will hold off on removing the information in the original doc until the Calypso links are updated.

Related to #81500

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- FYI @Automattic/shilling is that Pro-Rated Credit banner something y'all can update as well?

**Comment by jjchrisdiehl** [comment]
Should be resolved when https://github.com/Automattic/wp-calypso/pull/81657 is merge.

Also side note, the support site theme seems a bit cramped towards the top?
![image](https://github.com/Automattic/wp-calypso/assets/16580129/52866124-e70a-4f43-975a-c1a323fb4a5b)

**Comment by jjchrisdiehl** [comment]
Above PR is merged, closing for now.
