### ISSUE TITLE
Marketplace: fetch theme dependencies dynamically

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#81512]
### Details

Currently we have hardcoded the theme dependencies in fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Spynff%2Qznexrgcynpr%2Qgurzr%2Qcebqhpg%2Qpngnybt.cuc%2356-og

Since we store the dependencies in WC.com, and they are synced to wpcom shadow site, let's fetch them dynamically.

### Checklist

- [x] Fetch dependencies dynamically
- [x] Make sure that current themes with static dependencies, declare the dependencies in WC.com
- [x] Create a unit test for testing the output

**Comment by cpapazoglou** [comment]
We should have something similar that fetches dependencies for plugins eg `astra-pro` plugin requires `astra` theme.

**Comment by epeicher** [comment]
Draft diff created D122326-code for early review

**Comment by epeicher** [comment]
Diff D122326-code ready for review

**Comment by epeicher** [comment]
Deployed r275785-wpcom

**Comment by epeicher** [comment]
Doing an E2E testing in Production after the deployment works as expected. Installing the `Nokul` theme has installed the dependencies:

### Dependencies of `Nokul`
<img width="669" alt="CleanShot 2023-09-21 at 16 24 42@2x" src="https://github.com/Automattic/wp-calypso/assets/3519124/e255039f-18f9-47a2-b306-82913361db61">


### Installed plugins after installing `Nokul`
![CleanShot 2023-09-21 at 16 23 27@2x](https://github.com/Automattic/wp-calypso/assets/3519124/747151f9-b075-4673-b088-a46cb861c3fb)
