### ISSUE TITLE
Image Block Resolution (thumbnail, medium size) settings apply in editor but not live site

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#81534]
### Quick summary

The Image block has a "resolution" setting that lets the user select a predefined size: Thumbnail, Medium, Large, or Full Size.

If you upload an image and select the thumbnail resolution, the editor will show you a small image, typically 150px wide, depending on the media settings. This works as expected.

When you publish the page, though, even if both sites are using the same theme:
- On (some?) old simple sites, the image is shown as expected, with dynamic resizing to keep the files small
- On new simple sites, the image is shown content width and full resolution

### Steps to reproduce

1. Use a new test site. We had tested with justvelda.wordpress.com and onlyatest.tech.blog before we were able to duplicate on http://veldatestingimages.wordpress.com/ (feel free to test there.)
2. Create a post
3. Type /image to get the image block
4. Upload an image
5. Using the toolbar on the right, select Resolution: Thumbnail (or medium, etc)
6. Publish, and view the post. Note whether the image displays in a thumbnail size or not.

<img width="926" alt="Screen Shot 2023-09-07 at 3 34 42 PM" src="https://github.com/Automattic/wp-calypso/assets/3476361/ef10a8c6-e426-473a-9785-80b3e7349f55">

### What you expected to happen

The image should display at thumbnail size with the appropriate dynamic resizing, for example `focaccia.jpeg?w=300`

### What actually happened

The image displays full resolution and at the full width of the content area, for example just `focaccia.jpeg`

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement IF the site has CSS support:

```
/* Temporarily resize images */
.size-medium {
    width: 300px;
}
.size-thumbnail {
    width: 150px;
}
```

Otherwise users can set widths manually in pixels, but that can take a long time if the site has many posts.

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- This only happens on Simple Sites.
- Multiple themes were tested.
- We couldn't duplicate the user issue til we created a new test site
- Reported [here](https://wordpress.com/forums/topic/image-sizing-15/)
- Browser doesn't seem to matter, since the actual HTML output is different:
-- loading is set to lazy (that isn't happening on the older site)
-- width is incorrectly set to 2000
-- sizes max-width is higher (2000) on the new test site vs the old test site (150)

<img width="971" alt="Screen Shot 2023-09-07 at 3 15 28 PM" src="https://github.com/Automattic/wp-calypso/assets/3476361/192e66bc-7e8c-444e-ab0f-ed59a1ac3275">

**Workaround:**
use the image Size controls instead. You can specify 150 for the width, for example, and the image will be resized to that width on the page. Note this loads full-resolution images, and isn't ideal for performance.

**Comment by supernovia** [comment]
Clive updated us to let us know it's happening in one blog from 2017, so I'm guessing it's a default setting that was in some blogs then and is in new blogs now, but which missed the test blogs I used (circa 2011 and 2020)

**Comment by supernovia** [comment]
We have another case here:
https://wordpress.com/forums/topic/image-size-selection-stopped-wroking/

**Comment by supernovia** [comment]
Another case here
https://wordpress.com/forums/topic/images-are-correct-size-in-visual-editor-but-too-big-when-published/

**Comment by supernovia** [comment]
Another case:
https://wordpress.com/forums/topic/incorrect-image-size-on-blog-posts/

**Comment by supernovia** [comment]
Here's a case with an older blog (same user as the first reporter)
https://justafewrecipes.wordpress.com/2023/07/16/bakewell-pudding/

I tried using Dyad as a test to see if it's a theme issue; it's not. The HTML is still outputting 2000 as a width for the image.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Could Not Replicate** 
- Replicable outside of Dotcom – **No**

📌 FINDINGS/SCREENSHOTS/VIDEO
On a **free test site created 2023-09-06** using theme TT3, when I add an image from Pexels and set the Resolution to `Thumbnail`, the image reduces in size in the editor, but remains full resolution and full size on the live site. 

https://github.com/Automattic/wp-calypso/assets/27249804/ac96af6c-c6a3-4d0a-97f0-cb13925bc989

The image appears to have full resolution, though I can see `src="https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg?w=150"` in the HTML of the image 🤔 

```html
<img data-attachment-id="25" data-permalink="https://mcqdelete20230906.wordpress.com/2023/09/11/s-image-resolution/pexels-photo-1618606/" data-orig-file="https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg" data-orig-size="1733,1300" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="black and white turtle" data-image-description="" data-image-caption="<p>Photo by Richard Segal on <a href=&quot;https://www.pexels.com/photo/black-and-white-turtle-1618606/&quot; rel=&quot;nofollow&quot;>Pexels.com</a></p>
" data-medium-file="https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg?w=300" data-large-file="https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg?w=1024" loading="lazy" width="1733" height="1300" src="https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg?w=150" alt="" class="wp-image-25" srcset="https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg?w=150 150w, https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg 1733w, https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg?w=300 300w, https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg?w=768 768w, https://mcqdelete20230906.files.wordpress.com/2023/09/pexels-photo-1618606.jpeg?w=1024 1024w" sizes="(max-width: 1733px) 100vw, 1733px">
```

On AT site created today with TT3, as well as self-hosted on TT3, I cannot replicate the behavior. 

**Atomic**

Gutenberg 16.6.0

https://github.com/Automattic/wp-calypso/assets/27249804/fdb5c627-807e-4ee5-ad22-6129780fa3fd

```html
<img data-attachment-id="11" data-permalink="https://mcqdelete20230911.wpcomstaging.com/2023/09/11/at-image-resolution/pexels-photo-2189700/" data-orig-file="https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?fit=1040%2C1300&amp;ssl=1" data-orig-size="1040,1300" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;Photo by Emre Can Acer on <a href=\&quot;https:\/\/www.pexels.com\/photo\/forest-photography-2189700\/\&quot; rel=\&quot;nofollow\&quot;>Pexels.com<\/a>&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;forest photography&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="pexels-photo-2189700" data-image-description="" data-image-caption="<p>Photo by Emre Can Acer on <a href=&quot;https://www.pexels.com/photo/forest-photography-2189700/&quot; rel=&quot;nofollow&quot;>Pexels.com</a></p>
" data-medium-file="https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?fit=240%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?fit=819%2C1024&amp;ssl=1" decoding="async" loading="lazy" width="150" height="150" src="https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700-150x150.jpeg?resize=150%2C150&amp;ssl=1" alt="forest photography" class="wp-image-11" srcset="https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?resize=150%2C150&amp;ssl=1 150w, https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?resize=800%2C800&amp;ssl=1 800w, https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?resize=400%2C400&amp;ssl=1 400w, https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?resize=200%2C200&amp;ssl=1 200w, https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?zoom=2&amp;resize=150%2C150&amp;ssl=1 300w, https://i0.wp.com/mcqdelete20230911.wpcomstaging.com/wp-content/uploads/2023/09/pexels-photo-2189700.jpeg?zoom=3&amp;resize=150%2C150&amp;ssl=1 450w" sizes="(max-width: 150px) 100vw, 150px">
```

**Self-Hosted**

Gutenberg: 16.6.0

https://github.com/Automattic/wp-calypso/assets/27249804/86fa9c41-0f1b-419e-901f-220830b0976d

```html
<img decoding="async" loading="lazy" width="150" height="150" src="https://i0.wp.com/mqfour.mystagingwebsite.com/wp-content/uploads/2022/12/pexels-photo-1068554.jpeg?resize=150%2C150&amp;ssl=1" alt="close up photography of grizzly bear" class="wp-image-392" srcset="https://i0.wp.com/mqfour.mystagingwebsite.com/wp-content/uploads/2022/12/pexels-photo-1068554.jpeg?resize=150%2C150&amp;ssl=1 150w, https://i0.wp.com/mqfour.mystagingwebsite.com/wp-content/uploads/2022/12/pexels-photo-1068554.jpeg?resize=50%2C50&amp;ssl=1 50w, https://i0.wp.com/mqfour.mystagingwebsite.com/wp-content/uploads/2022/12/pexels-photo-1068554.jpeg?zoom=2&amp;resize=150%2C150&amp;ssl=1 300w, https://i0.wp.com/mqfour.mystagingwebsite.com/wp-content/uploads/2022/12/pexels-photo-1068554.jpeg?zoom=3&amp;resize=150%2C150&amp;ssl=1 450w" sizes="(max-width: 150px) 100vw, 150px" data-recalc-dims="1">
```

---

When comparing the HTML of the AT site with the simple, the Simple site shows the max-width as `sizes="(max-width: 1733px)`, while the AT and self-hosted sites show ` sizes="(max-width: 150px)`.

**Comment by cuemarie** [comment]
Escalation thread: p1694198987205599-slack-CBTN58FTJ

**Comment by aleone89** [comment]
To note this is also affecting how images are displayed in the reader.

Example 1: https://wordpress.com/read/feeds/70172996/posts/4876978764

Correct visual: The ‘medium’ text-wrapped image from my latest post appears at the right size (and the right resolution), but only after setting the image width individually: 
<img width="597" alt="Screenshot on 2023-09-14 at 09-34-09" src="https://github.com/Automattic/wp-calypso/assets/39101026/0f80334e-22bf-4b27-bf1f-87f4e77b9792">

Example 2: https://wordpress.com/read/feeds/70172996/posts/4806670708

Incorrect visual: Medium text-wrapped image appears at the wrong size (but the right resolution):

<img width="600" alt="Screenshot on 2023-09-14 at 09-39-23" src="https://github.com/Automattic/wp-calypso/assets/39101026/00117980-2402-4e7f-a2ed-d9e525794149">

**Comment by ricklabsdotn8** [comment]
Another user reported this error, provided workaround of resaving post in Classic Editor. Not ideal for hundreds of posts.

6850332-zen

**Comment by supernovia** [comment]
We have another case here, in this case on a 9-year-old site. 
https://wordpress.com/forums/topic/auto-size-images-not-working/

**Comment by supernovia** [comment]
An easy workaround for sites with Premium+ is to add this to CSS.

It's not so easy for sites with lots of posts that don't have access to additional CSS.

`/* Temporarily resize images */
.size-medium {
    width: 300px;
}
.size-thumbnail {
    width: 150px;
}`

**Comment by ccwalburn** [comment]
Another case was reported here: 6728758-zen

**Comment by supernovia** [comment]
User who spent quite a bit of effort helping us troubleshoot this issue asked about an update since it's been about a month. I've applied temporary fixes to his sites that use the Personal Plan, so we'll want to follow up in the [forums](https://wordpress.com/forums/topic/image-sizing-15/page/2/) when this is resolved.

**Comment by cuemarie** [comment]
Retested today - Issue still occurring on Edge Simple site using Gutenberg 16.7.0:


https://github.com/Automattic/wp-calypso/assets/27249804/ba51c5f2-f8c3-4b78-aec6-0a91492fe227

_Note - the test site shown above was created 2y ago (2021-05-20). I don't think the newness of the site exactly explains the pattern, so I'm removing that from the title of this report._

@fullofcaffeine offered to look into this, but I believe there may be some more pressing 16.7 issues that have taken priority.

**Comment by ricklabsdotn8** [comment]
another case - 7130746-zen (Pro Plan)

**Comment by Neha93517** [comment]
Another case here: https://a8c.zendesk.com/agent/tickets/7124018

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/image-sizing-15/page/2/?view=all#post-3994321

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/large-images-issue/

This is an Atomic site using a 3rd party theme.  In the HTML max-width is set at 640px for some reason.

**Comment by carolframen** [comment]
7146638-zen

**Comment by carolframen** [comment]
7148163-Zen

**Comment by Neha93517** [comment]
Another one here : 7147898-Zen
Premium Plan.
Shared CSS workaround

**Comment by supernovia** [comment]
Changed the title because some of these https://github.com/Automattic/wp-calypso/issues/81534#issuecomment-1753463231 are atomic!

**Comment by supernovia** [comment]
Here's another case
https://wordpress.com/forums/topic/medium-image-size-showing-as-large-images/

**Comment by mgozdis** [comment]
Another case here on a Simple site which I also reproduced in Twenty Twenty-Three on a free/Simple site:
7167584-zd-a8c

This user reported their images changed on multiple sites to larger sizes overnight or within the last couple of days. Not sure if related to recent Gutenberg 16.8.1 update. I gave them CSS as a temporary fix.

**Comment by Robertght** [comment]
another case in 7075660-zen. CSS worked.

**Comment by carolframen** [comment]
Another case: 7153553

user says the issue is happening on 2 of their sites:

- Blog ID: 139372071
- Blog ID: 141806499

**Comment by cuemarie** [comment]
Thanks @carolframen . Always make sure to exclude any user-specific information in your screenshots or details.

I have edited your comment above to remove user-specific information, and [deleted the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from the comment history.  You can follow these steps in the future as well if you ever need.

**Comment by carolframen** [comment]
@cuemarie I'm so sorry, that won't happen again. Thank you for taking care of it! :D

**Comment by cuemarie** [comment]
This issue was escalated here: p1697818393967329-slack-C02FMH4G8

And a fix was rolled out, thank you @mreishus , and thanks to @fullofcaffeine  for helping get this under the right eyes! ❤️ I'll close this as I think we're good, but I understand that was a short-term fix, so feel free to reopen if that's more appropriate.

📌 ACTIONS
- Closing as resolved

**Comment by worldomonation** [comment]
Phab diff that fixed the issue: D126318-code

**Comment by mreishus** [comment]
Thank you @sgomes :)

**Comment by sgomes** [comment]
Thank you for the review and the earlier fix, @mreishus 👍
