### ISSUE TITLE
Jetpack Plugins: site indicator needs an 'update all' button

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#8154]
We have recently added a helpful popover in the site list for Jetpack sites needing updates. It's great, but you still have a split between plugin updates (which happen in calypso) and theme/core updates (which happen in wp-admin still). 

Once we can perform all those updates inside calypso we should add an 'update everything' button to the bottom of this popover.

<img width="231" alt="screen shot 2016-09-20 at 10 23 18 am" src="https://cloud.githubusercontent.com/assets/437258/18681355/90d9c024-7f1c-11e6-9630-6f5c19be9ff1.png">

cc @richardmuscat @lezama

**Comment by johnHackworth** [comment]
Should this be on the trash pickup milestone? I mean, since we still don't have theme or core updates, this feels like a new feature more than something we need to fix

**Comment by rickybanister** [comment]
Perhaps not, it helped us keep our thoughts organized last week.
