### ISSUE TITLE
Magic link flow: brand as website when coming from a site as a subscriber

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#81555]
Thanks to https://github.com/Automattic/wp-calypso/pull/81522, we can login email-subscribers with magic-link flow.

We should brand the flow more as if they are logging onto the blog as a reader. If they are a subscriber, they're formed a relation with that site's brand, not ours. They might have no idea they have (or will have) a "WordPress.com account".

That said, we should leave also WP.com (or Jetpack!) branding visible as a platform.

We can also mention apps as a great way to stay signed in, both at the email link confirmation page and the email.

Pages (open in incognito):
- [wordpress.com/log-in/jetpack/link](https://wordpress.com/log-in/jetpack/link)
- [wordpress.com/log-in/link](https://wordpress.com/log-in/link)

Current screens and email:

<img width="895" alt="Screenshot 2023-09-08 at 13 19 20" src="https://github.com/Automattic/wp-calypso/assets/87168/7f06f9c6-ea9f-463d-a39b-b7256585882d">
<img width="923" alt="Screenshot 2023-09-08 at 12 38 34" src="https://github.com/Automattic/wp-calypso/assets/87168/522b526c-5f49-4386-8712-a93a7fe61320">
<img width="1016" alt="Screenshot 2023-09-08 at 13 25 50" src="https://github.com/Automattic/wp-calypso/assets/87168/d3ded984-834f-476d-af17-99814e195b6d">

**Comment by crisbusquets** [comment]
Note: I'm currently working on this

https://github.com/Automattic/wp-calypso/issues/82568, related to https://github.com/Automattic/dotcom-forge/issues/4101
