### ISSUE TITLE
Post Publish Sharing Still Displaying after Checkbox to not display again is checked

### ISSUE THREAD

**Issue by alliebbush2** [Automattic/wp-calypso#81570]
### Quick summary

This is related to the Post-Publish Sharing feature. When a user on a simple site publishes a post for the first time a pop-up appears that says "Post Published. Your post is now live and was delivered to each of your subscribers." There is a checkbox option that states "Don't show again" but the pop-up continues to display even when the checkbox has been checked multiple times. Basically, the checkbox does not seem to be functioning. See the image below:
<img width="628" alt="Screenshot 2023-09-08 at 4 52 32 PM" src="https://github.com/Automattic/wp-calypso/assets/97132910/4cf40a9f-231b-4a1b-a00c-4919a30188b1">

### Steps to reproduce

1. Start with adding a new post on a simple site
2. Once you publish the post, the pop-up appears
3. Check the checkbox for the pop-up to not display again
4.  When you publish a new post again the pop-up will continue to display

There is also the option of going to the ellipsis within the post editor and then choosing Preferences and deselecting "Include pre-publish checklist" which may or may not be the same feature but this does not work either.

### What you expected to happen

The pop-up message should not display again.

### What actually happened

The pop-up message continues to display each time a new post is published.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

ZD: [6789180]

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described; the "Post Published!" modal continues to appear after selecting the "Don't show again" checkbox.

https://github.com/Automattic/wp-calypso/assets/27249804/e5e5c886-b602-4577-9c3c-947278246c96

📌 ACTIONS
- @daledupreez it looks like you addressed something quite similar, but in a different pop-up modal, in this PR: https://github.com/Automattic/jetpack/pull/32567
- Could something similar be done for this one as well? Or do you think we need to take a different approach?

**Comment by bryandev602-gh** [comment]
Another report in 6941056-zen

**Comment by cuemarie** [comment]
Reported here: 6804730-zen (and driving the user a little bananas)

**Comment by cuemarie** [comment]
I also run into this on my test sites all the time, and it is definitely annoying.  While low impact, it's a bug that is pretty visible, since it comes up every time a post is published.

@Automattic/serenity is this something y'all manage?

**Comment by gikaragia** [comment]
Not sure why this happened before but it seems that it works now. When I check the box I can see that there is a request that updates the `sharing_modal_dismissed` option and from this point on every post that I visit has this variable set:

![Image](https://github.com/user-attachments/assets/ac6b7588-0bf4-4859-955c-a9c518685a03)

And the modal isn't displayed anymore. Tried on Firefox and Chrome. I'll close this but please re-open it if you can reproduce it.
