### ISSUE TITLE
Sites page: Nested dropdown clipped by the viewport

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#81590]
When you open a nested dropdown on the Sites page, it's clipped by the viewport:

In the case of a Business plan site, it looks like this:

<img width="533" alt="Screenshot 2023-09-11 at 2 05 08 PM" src="https://github.com/Automattic/wp-calypso/assets/1182160/58eaec14-4861-47e5-bf2d-f1488fc5d607">

In the case of lower-tier plans, we show the upsell nudge, but currently, its styles seem to be off. Not sure if this is a related or separate issue:

<img width="390" alt="Screenshot 2023-09-11 at 2 04 37 PM" src="https://github.com/Automattic/wp-calypso/assets/1182160/a168b1f4-b4ba-47f5-9411-098a468d800d">

**Comment by vindl** [comment]
This could be a regression caused by https://github.com/Automattic/wp-calypso/pull/81291.

**Comment by katinthehatsite** [comment]
I reverted https://github.com/Automattic/wp-calypso/pull/81291 locally and the dropdown seems to be working as expected before that change and breaks after the change so I can confirm that it is a regression from the updates.

**Comment by vindl** [comment]
cc @noahtallen for awareness

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described:

![Markup on 2023-09-11 at 12:55:15](https://github.com/Automattic/wp-calypso/assets/27249804/06454583-8531-4ef9-b67c-86708e92d15c)
