### ISSUE TITLE
Synced block patterns missing from site editor on Dotcom sites

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#81606]
### Quick summary

There's no way to access custom patterns in the page editor. The pattern menu item is missing from the block list and I can't seem to figure out the combination to get it back.

When a site is in troubleshooting mode with healthcheck and all the default plugins are active, things show fine. When troubleshooting is deactivated, no combo of active plugins seems to work. 

I also wasn't able to tie it to a specific theme. 

I'm thinking it was either a FSE or Gutenberg update but also can't find the FSE repo to try different versions. If someone can point me to this I'm happy to try again.

User example: p9F6qB-dg6-p2 
Test site example: BlogID 181938588

**Workaround:**
To use the blocks you can copy and paste them in the new location
to manage them you can go to {site} /wp-admin/edit.php?post_type=wp_block

### Steps to reproduce

1. open a page in site editor
2. click the plus (add new block) in the top tool bar
3. see the missing patterns section
4. turn on Health Check Troubleshooting mode with default plugins on and see the section come back

### What you expected to happen

The section should always be there

![2023-09-11 at 14 38](https://github.com/Automattic/wp-calypso/assets/47717887/e4b3cadb-5806-4d07-a69c-2fa466a240cd)

### What actually happened

it's not

![2023-09-11 at 14 33](https://github.com/Automattic/wp-calypso/assets/47717887/682d4923-c32b-43b5-bf01-5fb4adb60240)

### Impact

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
On both Simple and AT sites using TT3, I see no `Synced Patterns` button in the Site Editor. However, opening a self-hosted site on TT3 with the same GB and WP versions, `Synced Patterns` is available.


All sites use GB 16.6.0 and WP 6.3.1

### Simple

![Markup on 2023-09-12 at 18:22:11](https://github.com/Automattic/wp-calypso/assets/27249804/794b89b9-1daa-4c5c-82b7-5f1faadabbe4)

### Atomic
![Markup on 2023-09-12 at 18:23:47](https://github.com/Automattic/wp-calypso/assets/27249804/4e8410e2-2ab5-4e95-8480-e7da4169a34c)

### Self-Hosted

![Markup on 2023-09-12 at 18:21:35](https://github.com/Automattic/wp-calypso/assets/27249804/ff4a6fcf-227d-4865-a01c-96458bd8c2c9)

📌 ACTIONS
- Flagged here: p1694568344518899-slack-C01LXBU1N21

**Comment by annezazu** [comment]
Hey folks! Following up on this as the experience has changed intentionally: synced patterns has been merged into the overall patterns tab per [this issue](https://github.com/WordPress/gutenberg/issues/51945) and [this PR](https://github.com/WordPress/gutenberg/pull/54007). As a result, here's the current experience below showing both self hosted and a simple WordPress.com site:

https://github.com/user-attachments/assets/95241c4b-6f02-44a3-bf04-33d3da50b47b

I'm going to close this out as a result :)
