### ISSUE TITLE
Assembler: Custom styles selection affect Design Picker theme previews

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#81615]
## Description

The custom styles selected in the Assembler carries over to the Design Picker theme previews. Steps to reproduce:
1. Go to the Assembler via the DP.
2. Select any custom styles (preferably, yellow background so that it's noticeable).
3. Click back to return to the DP.
4. Preview any theme, the custom styles selected in the Assembler are applied to the previews in the DP.

https://github.com/Automattic/wp-calypso/assets/797888/f6850a2d-681b-44c4-beae-b16c63c9ce2d

## Acceptance Criteria
- [ ] Custom styles selected in the Assemble should not affect the Design Picker theme previews, and vice versa.

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/81621
