### ISSUE TITLE
Unexpected or missing limited Global Styles notices

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#81628]
Seems that under some circumstances, we're either displaying the "Your site includes customized styles" notice in the frontend incorrectly, or maybe we're showing it correctly but it's missing in the site editor.

I'm unable to reproduce the issue, but I spotted a couple of tickets where it's definitely happening:

- Blog ID 222367729 (6766682-zd-a8c, [forums](https://wordpress.com/forums/topic/customized-styles-is-reset-issue/?view=all#post-3981887))

Frontend | Site editor (view) | Site editor (edit)
--- | --- | ---
<img width="1728" alt="Screenshot 2023-09-12 at 11 56 13" src="https://github.com/Automattic/wp-calypso/assets/1233880/13d515cc-4db0-4d71-b179-de3c793b407b"> | <img width="1728" alt="Screenshot 2023-09-12 at 11 56 32" src="https://github.com/Automattic/wp-calypso/assets/1233880/67d5ce45-f471-450c-85a4-9bf2adb2c039"> | <img width="1728" alt="Screenshot 2023-09-12 at 11 56 45" src="https://github.com/Automattic/wp-calypso/assets/1233880/5b97b12f-179b-47be-8347-ed22b23ba325">

- Blog ID 222358887 (6722727-zd-a8c)

Frontend | Site editor (view) | Site editor (edit)
--- | --- | ---
<img width="1728" alt="Screenshot 2023-09-12 at 11 54 13" src="https://github.com/Automattic/wp-calypso/assets/1233880/d5420405-2afa-4bb1-9314-a2595be97dc9"> | <img width="1728" alt="Screenshot 2023-09-12 at 11 53 38" src="https://github.com/Automattic/wp-calypso/assets/1233880/7b5f9926-174d-4a42-9567-1b26ccd6a00c"> | <img width="1728" alt="Screenshot 2023-09-12 at 11 58 00" src="https://github.com/Automattic/wp-calypso/assets/1233880/68922959-0176-4dcb-9a77-68ac032cbb08">

- Blog ID 222434302 (6678419-zd-a8c, [forums](https://wordpress.com/forums/topic/upgrade-required-but-no-customization-can-be-found/?view=all))

Frontend | Site editor (view) | Site editor (edit)
--- | --- | ---
<img width="1728" alt="Screenshot 2023-09-12 at 12 26 40" src="https://github.com/Automattic/wp-calypso/assets/1233880/317067a1-5e12-4f7c-a05c-f99bafc50f0a"> | <img width="1728" alt="Screenshot 2023-09-12 at 12 26 59" src="https://github.com/Automattic/wp-calypso/assets/1233880/b3139742-60d6-49d6-b784-09eee7ada5f9"> | <img width="1727" alt="Screenshot 2023-09-12 at 12 27 15" src="https://github.com/Automattic/wp-calypso/assets/1233880/8e2879f1-1d17-45ea-bc62-9fc95d18f931">

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on User Report Sites - **Still reproducible**

📌 FINDINGS/SCREENSHOTS/VIDEO
I'm not able to replicate this on a test site yet, but I **can see the same error warnings the users are reporting** on their sites. 

![Markup on 2023-09-12 at 14:28:25](https://github.com/Automattic/wp-calypso/assets/27249804/20de69e2-4063-4fac-bd6c-3d5f52deddb8)

I SU'd into the owner of the the following sites:

1. Blog ID 216823552 (free) from the first interaction: _https://wordpress.com/forums/topic/customized-styles-is-reset-issue/_
2. Blog ID 222367729 (free) from the first interaction: _https://wordpress.com/forums/topic/customized-styles-is-reset-issue/_
3. Blog ID 222434302 (free) from the second forum post: _https://wordpress.com/forums/topic/upgrade-required-but-no-customization-can-be-found/_

In all sites, the editor does not show any warning about custom styles, but viewing the homepage while logged in shows the warning.  Additionally, their sites contain **Styles Revisions** , but the styles can't be reset (which should mean there are no custom styles saved currently):

<img width="550" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/aab6b16f-8f2d-4894-923e-348a2effc5bd">

<img width="334" alt="Screenshot on 2023-09-12 at 14-34-58" src="https://github.com/Automattic/wp-calypso/assets/27249804/81c57c76-65b7-4eab-b6cb-beb72eba37dd">

- Notice the existing revision, but the inability to reset all styles. Our [support documentation](https://wordpress.com/support/using-styles/#reset-all-styles) says:

> If Styles were never changed, the Reset to defaults option will appear greyed out.



---


📌 ACTIONS
- Noted the GH link on the Forums posts for reference

**Comment by dsas** [comment]
> Additionally, their sites contain Styles Revisions , but the styles can't be reset (which should mean there are no custom styles saved currently):

They should be able to use the revision list to set back to the initial styles, but yes the 'Reset to defaults' menu item is greyed out.

**Comment by dsas** [comment]
Global Styles customisations are stored in a custom post type. For all of the sites mentioned the post corresponding to their active theme includes this:

```
        "post_content": "{\"behaviors\":[],\"version\":2,\"isGlobalStylesUserThemeJSON\":true}",
        "post_content_filtered": ""
```

So they technically have global styles customisations saved, but those customizations are effectively blank. 

I'm not sure how or why they were able to have an effectively blank GS saved but they have and so must many other people. We could track down this behaviour, fix it and remove the affected data....but it's probably easier to make our front-end upgrade notice resilient to "empty" customisations.

**Comment by dsas** [comment]
It's the empty `behaviors` key that does it, we filter out other keys we should ignore here: https://github.com/Automattic/wp-calypso/blob/c315e666979970a047efb20043c84041c684eae6/apps/editing-toolkit/editing-toolkit-plugin/wpcom-global-styles/index.php#L305C96-L305C96 so we probably need to do the same for behaviors. I'll double check that and open a PR.

**Comment by dsas** [comment]
[Behaviours was removed from GB16.7](https://github.com/WordPress/gutenberg/pull/53851), so there's possibly nothing to be done upstream about the revisions really. I'll update our allowlist that I linked above so we're not displaying the notices any longer.

**Comment by supernovia** [comment]
Thanks. We've got a couple of folks to follow up with here.
https://wordpress.com/forums/topic/restore-default-fonts-remove-custom-styles/
https://wordpress.com/forums/topic/upgrade-required-prompt-but-no-customized-style-applied/
https://wordpress.com/forums/topic/your-site-includes-customized-styles/

**Comment by supernovia** [comment]
and one here: https://wordpress.com/forums/topic/your-site-includes-customized-styles/

**Comment by cuemarie** [comment]
> Thanks. We've got a couple of folks to follow up with here.

@supernovia is this a note for the Chiron team, or are you requesting a batch reply for this? I'm not sure this one warrants a batch reply from my side of things (they can be a _slog_, and there aren't a ton of interactions here).  

If I'm understanding @dsas 's last comment, it seems the users should stop seeing the notices, so there's nothing users need to take action on for that fix to reach them, which is another reason I'm thinking that a batch reply wouldn't really be worth the effort here.

**Comment by dsas** [comment]
> If I'm understanding @dsas 's last comment, it seems the users should stop seeing the notices,

Yep, that's right. The bugfix has been deployed and the notices should disappear without any action from the users. I've verified the deployment with the first blog in the initial list.

**Comment by supernovia** [comment]
> If I'm understanding @dsas 's last comment, it seems the users should stop seeing the notices, so there's nothing users need to take action on for that fix to reach them, which is another reason I'm thinking that a batch reply wouldn't really be worth the effort here.

Since these are in the forums with multiple people involved in the threads, it's a nice look for us to update when the issues are solved. We can get that!
