### ISSUE TITLE
Error after deleting WordPress.com site

### ISSUE THREAD

**Issue by jkudish** [Automattic/wp-calypso#8163]
Howdy 👋 

I deleted a WordPress.com site and encountered some errors after deletion was completed:
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Go to site settings
3. Click on Delete Site
4. Follow the prompts
5. Wait until site is deleted (side note: this takes a pretty long time, perhaps Calypso could be enthusiastic here and assume the deletion will succeed)
#### What I expected

To get a prompt as to which site I want to manage next
#### What happened instead

I get redirected to `/stats` but the page still shows the settings screen, and there are errors in the console:

```
Uncaught TypeError: date.format is not a function
Uncaught TypeError: Cannot read property '__reactInternalInstance$rrvm2160sh1woenfqyxk1emi' of null
```

See screenshot below.
#### Browser / OS version

OS X 10.11.6 
Chrome 53.0.2785.116 64 bit
#### Screenshot / Video

![screen shot 2016-09-20 at 5 57 52 pm](https://cloud.githubusercontent.com/assets/260253/18694077/faaa0286-7f5b-11e6-8ebe-63ab769d03f5.png)

#### Context / Source
#user-report

**Comment by lancewillett** [comment]
Thanks for the report, Joey.

**Comment by rachelmcr** [comment]
#bug-scrub

I retested this issue and can no longer reproduce it. After the site was deleted I was redirected to `/stats` with no console errors and the expected all sites stats view.
