### ISSUE TITLE
Update Support Doc Links on Stats Screen

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#81632]
### Quick summary

The [Stats doc](https://wordpress.com/support/stats/) will be broken out into smaller docs:
* Traffic: https://wordpress.com/support/stats/understand-your-sites-traffic/
* Insights: https://wordpress.com/support/stats/learn-insights-about-your-website/
* Subscriber stats: https://wordpress.com/support/subscribers/#subscriber-stats
* Ads stats: https://wordpress.com/support/wordads-and-earn/#ad-stats

Links throughout the Stats UI will need to be updated. 

The main Stats doc will have most of the information removed, except for the video, Access Stats, Download Stats and Data Collected. I am holding off on pushing the changes live until the Calypso links can be updated, thanks!

### Steps to reproduce

1. Visit the Stats page: https://wordpress.com/stats/day/
2. Notice links to specific sections of the [Stats doc](https://wordpress.com/support/stats/), such as Search Terms, Clicks, and Videos:

https://wordpress.com/support/stats/#search-terms
https://wordpress.com/support/stats/#clicks
https://wordpress.com/support/stats/#videos

which need to be updated to:

https://wordpress.com/support/stats/understand-your-sites-traffic/#search-terms
https://wordpress.com/support/stats/understand-your-sites-traffic/#clicks
https://wordpress.com/support/stats/understand-your-sites-traffic/#videos

![Annotation on 2023-09-12 at 12-10-39](https://github.com/Automattic/wp-calypso/assets/30727666/3cfdc507-efb2-43d7-b0c9-2a62d2e0f38c)

**That is not a complete list of URLs to update. Is it possible to search for more?**

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

The reason for the change is that the Stats doc is too long and difficult to follow. We are breaking it up into smaller, more focused docs.

The new docs are live, but I will hold off on removing the information in the original doc until the Calypso links are updated.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Changed to Enhancement type
- Request kept
- CC @jeherve is this something JP Crew could handle on the Calypso Stats pages, or is there a better team to direct this to? Thanks for your insight!

**Comment by jeherve** [comment]
Added this to the Jetpack Stats board. 👍

**Comment by donalirl** [comment]
Thank you @jeherve! I was wondering when we might expect the links updated? We have some [pending doc updates](https://github.com/Automattic/en.support-docs-content/issues/2042#issuecomment-1715528379) we'd like to get finished.

**Comment by kangzj** [comment]
Hi @donalirl, Do we only update these three? because I can see the doc has sections for emails, views and visitors, referrers etc?

**Comment by donalirl** [comment]
@kangzj No, not just those three. Those were the only three that showed to me on the site I checked, but checking a different site (that has no traffic) and I'm seeing more links:
<img width="751" alt="Screenshot 2023-12-14 at 12 43 26 pm" src="https://github.com/Automattic/wp-calypso/assets/30727666/8ffe16c8-dbbb-4ded-8a52-2bebebba4fa2">

We should update any link to https://wordpress.com/support/stats/ as that is the old doc. The new docs are:

- Traffic: https://wordpress.com/support/stats/understand-your-sites-traffic/ (and jump links to specific sections like search terms, referrers, etc.)
- Insights: https://wordpress.com/support/stats/learn-insights-about-your-website/
- Subscriber stats: https://wordpress.com/support/subscribers/#subscriber-stats
- Ads stats: https://wordpress.com/support/wordads-and-earn/#ad-stats

The old Stats doc will have most of the information removed, except for the video, Access Stats, Download Stats and Data Collected sections.

**Comment by donalirl** [comment]
Hey @kangzj thanks for updating the links! I spot-checked several and they all look correct.

I was wondering if you think we should resolve these behaviors:

* Clicking the links takes you off of Calypso to the support doc, instead of opening a new tab.
* The browser's back button doesn't take you back to Calypso.

Here's a video showing these issues:

https://github.com/Automattic/wp-calypso/assets/30727666/cd49789c-b917-4271-abcd-336459218211

I propose updating it to trigger the doc opening in the Help Center, like what happens when you click the Learn More link at the top:

https://github.com/Automattic/wp-calypso/assets/30727666/e475666e-d7c3-44f2-9638-87936527103f

**Comment by kangzj** [comment]
@donalirl thanks for catching those. It makes sense to me. We'll take a look.

**Comment by kangzj** [comment]
> I propose updating it to trigger the doc opening in the Help Center, like what happens when you click the Learn More link at the top:

It is done in the way for Calypso Stats now, and I'm not sure we could do the same for Odyssey. Do you think it's a good idea @jos22 @foleynotrose ? Thanks

**Comment by davemart-in** [comment]
Removing this issue from The One Board, since it's on Jetpack Stats radar.

**Comment by kangzj** [comment]
Closing this one as it's tracked here: https://github.com/Automattic/red-team/issues/194
