### ISSUE TITLE
Paid Stats: delaying "Do you love Jetpack Stats" upsell for new users

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#81655]
Let's deal with this one after Paid Stats launch for WPCOM.

> should we consider delaying the “Do you love Jetpack Stats?” prompt for new users? Prompting them to pay during their initial experience might be premature since:

> They’re still unfamiliar with the product.
They might lack sufficient site data to see the product’s value.
Perhaps the prompt could appear after a user has accessed Stats five times or a month has passed since their Jetpack connection.

p1HpG7-orS-p2#comment-65837

**Comment by dognose24** [comment]
I tried to delay the upsell notices for `30 days` to new users when determining whether to show upsell notices from the API end: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Swrgcnpx%2Qfgngf%2Qqnfuobneq%2Spynff%2Qabgvprf.cuc%3Se%3Q9r6ps2r4%2362-og. The proposed Diff is here: D123027-code.

**Comment by dognose24** [comment]
This task has been addressed and deployed: rWPGITa8ea67ad01e0-code.
