### ISSUE TITLE
Marketplace: add download button and .org page link for plugins

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#81685]
> If we can provide a way for users who land on Dotcom pages to navigate to the Dotorg directory if that’s what they actually wanted to do, I agree that would help ease some of this negative sentiment.

Adding a download link and a backlink to the .org listing seems like a good gesture for wordpress.org.

Related slack convo: p1694615615676399/1694591936.210979-slack-C029GN3KD

**Comment by JulianBustamante** [comment]
Backlog grooming:

We should add more links linking back to .org

1. Adding a download button (as the theme page already does for Astra) on the sidebar.
2. Add a link to the plugin .org page
3. The copy is the same one that already is used on Astra.
4. The copy and the link will be displayed for both logged-in and logged-out users.
5. You could create a simple pattern: https://downloads.wordpress.org/plugin/[PLUGIN_SLUG].zip, this URL downloads the last version.

**Comment by WBerredo** [comment]
Example of what's is displayed on Astra theme currently:
![CleanShot 2023-09-14 at 15 30 05@2x](https://github.com/Automattic/wp-calypso/assets/5039531/3a6e9d36-1c14-4375-89eb-1076899b383f)

**Comment by cpapazoglou** [comment]
Let's also add the `nofollow` attribute in the links.

**Comment by WBerredo** [comment]
During this convo p1695049613546329-slack-C02JPCHEKDY we agreed to add a card below the sidebar.
