### ISSUE TITLE
CoBlocks - Wave Image Style Not Working On Image Block

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#81693]
### Quick summary

On atomic sites with coblock plugin installed, when wave style is selected on the image block, it appears in the Editor and not the published site. 

### Steps to reproduce

1. Add an image block to a page on an atomic site with coblocks installed
2. Add an image block
3. Go to block settings and select top wave or bottom wave styles. 

### What you expected to happen

For styles to apply both in Editor and on live site. 

### What actually happened

Wave styles appear in the Editor but not on the live site.

https://github.com/Automattic/wp-calypso/assets/74204272/589e888f-ba14-42cd-a993-b016f4ed5316

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
This is replicable outside of WordPress.com, so it appears to be something CoBlocks would need to fix.

📌 ACTIONS
- Reported here: https://github.com/godaddy-wordpress/coblocks/issues/2567
- Closed as this requires a third party fix

**Comment by vajrasar** [comment]
@kelasante what is the workaround?

**Comment by kelasante** [comment]
>  what is the workaround?

Taking a screenshot of the Wave style in the Editor and uploading that as the image or editing with a photo software like Photoshop prior to uploading. They are not exactly the best workarounds   @vajrasar
