### ISSUE TITLE
Paid Stats: Adjust free plan purchase summary page

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#81745]
As a follow-up task from the discussion p1HpG7-o4A-p2#comment-66034

Adjust URLs to use the implemented redirect mechanism to show PWYW purchase page after clicking on an upgrade button and only having a free plan. Apply this to `My jetpack` card and success notice on the traffic page.
We already have a mechanism to redirect, so we would only need to update the link with a proper parameter.

Update the summary copy from
`It appears that you have already purchased a license for this product, and it has been successfully activated. You now have access to:`
to:
`You already have a free license for this product, and it has been successfully activated. Currently have access to:`

The outcome:
Redirects should show PWYW straight away after visiting the purchase page - applies for my jetpack widget (upgrade button) and the upgrade banner after purchasing a free plan. 

If someone visits the purchase page manually, it should show the summary screen as it does now.

**Comment by kangzj** [comment]
Hey @grzegorz-cp, this is on the upgrade purchase flow, which I think should be prioritized. Can you please take a look? Thanks 🙇

**Comment by grzegorz-cp** [comment]
It looks like only the wording needed updating but I tested all of the scenarios.

After purchasing a free plan, the `please consider upgrading` link already redirects properly to a PWYW page. It's the same case after visiting the purchase screen summary - `upgrade my stats` redirects directly to PWYW page.
`My Jetpack` card has a `View` button that redirects to the Stats page.
`Upgrade Stats` from the add-ons page properly redirects to PWYW page as well.

**Comment by kangzj** [comment]
Thanks for looking into it. I noticed at least in My Jetpack, when a site only has Free, upgrade will direct users to the Free plan summary page, where I think PWYW page would be better. If the notices already work this way, then all good. Otherwise we’d need to change them too. 🙂️

**Comment by grzegorz-cp** [comment]
Thanks for the tip @kangzj. ~~I just checked on a fresh instance, and the `Upgrade` button only shows up before any plan was purchased, and it redirects to the purchase page. Once a free or PWYW plan was purchased, only a `View` button was visible.~~

Update for the button: https://github.com/Automattic/jetpack/pull/33297
