### ISSUE TITLE
Feature Request: Allow disabling auto renew for paid content subscriptions

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#81741]
### What

Currently, it is not possible for subscribers to paid content to turn off automatic renewal. The subscription may be ended at any time, but the automatic renewal may not be turned off.

I would like to request adding a button to allow turning off automatic renewal for these subscriptions, similar to how we allow our users to turn off automatic renewal for their purchases (plans, domains, email, etc.)

<img width="1042" alt="Screenshot 2023-09-14 at 5 49 14 PM" src="https://github.com/Automattic/wp-calypso/assets/12906034/6bde9c26-f0ec-4fba-8967-8b813b942c33">

### Why

Sometimes subscribers may wish to enjoy the rest of their subscription and allow it to expire.

### How

Add a button to the purchases page similar to what already exists for plans.

<img width="689" alt="Screenshot 2023-09-14 at 5 50 24 PM" src="https://github.com/Automattic/wp-calypso/assets/12906034/b4b1094e-96bc-47d3-a8ce-375fb8c29b7e">

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- fyi @Automattic/gold for this idea

**Comment by millerf** [comment]
That might be related to @Automattic/apex as they are working on the subscriptions page... But happy to help...

**Comment by davemart-in** [comment]
Sending this to the Gold board to add to their feature prioritization list. Seems like a good idea. Removing from The One Board, since this feels like more than a bug fix.
