### ISSUE TITLE
Reader: Tiled gallery cut off on mobile

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8174]
Example URL: https://wpcalypso.wordpress.com/read/feeds/46002335/posts/1005454441

![img_7793](https://cloud.githubusercontent.com/assets/4924246/18769538/d9c2e294-80e2-11e6-89af-6ea955567e50.png)

This seems to be an existing issue even in the old full-post view. Happens around `800px` breakpoint in the new full-post view. In the old full-post view, happens around `500px`.

Reported by @martinremy

**Comment by alisterscott** [comment]
I've noticed this myself on mobile. I am curious why this is set as low considering this affects all mobile browser readers?

**Comment by jancavan** [comment]
@alisterscott We'll revisit issues like these in a couple weeks.

**Comment by fraying** [comment]
I think this is fixed now.

**Comment by alisterscott** [comment]
Thanks, looking great 👍
