### ISSUE TITLE
Add new domain leads to /start intermittently

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#81758]
### Quick summary

Free sites are allowed to own domains, adding a new one should lead to domains/site/add and not to /start

https://github.com/Automattic/wp-calypso/assets/82778/118148aa-48c4-44a3-85e7-6ebb408ccd0a

### Steps to reproduce

1. From /home on a free site, select Upgrades > Domains
2. Register a new domain from the big red button
3. You should go to /domains/add and not to /start

### What you expected to happen

go to /domains/add

### What actually happened

/start

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
On my free test site, selecting a domain to register took me to the add email page, then the checkout page - I wasn't directed to the start flow. 

- `https://wordpress.com/domains/add/` -> `https://wordpress.com/domains/add/domain/email/` -> `https://wordpress.com/checkout/`

https://github.com/Automattic/wp-calypso/assets/27249804/4a59efce-930b-4e2a-a6cc-6b55d55a0738

📌 ACTIONS
- Requested author feedback
- Lowered priority

📌 Message to Author
@dzver can you test this once more, across a couple free sites?  I'm curious if it's still happening/happening everywhere for you. Thanks!

**Comment by dzver** [comment]
I couldn't reproduce this morning but I don't think it's gone. I've seen the issue multiple times. Will check again when I have more time, and try to find possible reasons for it.

**Comment by nightnei** [comment]
@dzver I checked it, and I can't replicate it.
Moreover, it's 1 year since the issue was created and looks like there are a lot of changes, even URL is a bit different now (/domains/add/<DOMAIN_NAME>), so I think it's not relevant anymore. 
WDYT?

**Comment by dzver** [comment]
Okay, let's close it, if I see it again, I'll open a new issue with the current flow that involves an email step.
