### ISSUE TITLE
Plan Features link when cancelling isn't working

### ISSUE THREAD

**Issue by alinclamba** [Automattic/wp-calypso#81769]
### Quick summary

There's an issue with the `Plan Features` link in Calypso Green. Clicking on it doesn't do anything, even though the URL shows up when you hover over it. I think it's important to fix this because it could help users who are thinking of canceling their subscriptions. They could see all the features and change their mind:

<img width="1111" alt="download" src="https://github.com/Automattic/wp-calypso/assets/6790170/c244fef5-8b13-42b3-a88e-4105ddf6d3ef">

### Steps to reproduce

1. Enable Jetpack Complete plan on a Jurassic Ninja site
2. Navigate in Calypso Green to Purchases → My Plan and click the Cancel plan button
3. On the next screen, you'll see a link in green - `Plan Features` which doesn't do anything when click on it. 

### What you expected to happen

I expect to review the features included in my Jetpack Complete plan (and maybe reconsdier my decision to cancel the plan). 

### What actually happened

Nothing happens when clikc the `Plan Features` link. 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Originally reported in Slack: p1694692975743459-slack-C02DQP0FP

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on cloud.jetpack.com - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described - the link does not take me anywhere, in that tab or a new one; with no console logs. The URL is seems to lead to is `https://cloud.jetpack.com/plans/my-plan/SITE_ADDRESS`

https://github.com/Automattic/wp-calypso/assets/27249804/863ba9b8-d7b8-44fe-8616-07edc171361a

📌 ACTIONS
- Lowered priority to Normal
- CC @jeherve

**Comment by agrullon95** [comment]
Created a PR for the Plan Features link: https://github.com/Automattic/wp-calypso/pull/93871
It will now navigate users to `wordpress.com/plans/my-plan` to display the plan features correctly.
