### ISSUE TITLE
Marketplace Themes on Onboarding eligibility modal tracks event

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#81768]
Create a track event for the new Eligibility Modal displayed during Onboarding when the site needs to be transferred to Atomic.

The track event can be triggered here https://github.com/Automattic/wp-calypso/pull/81412/files/ba9ca69b1062c6b7f886bd5c492e6744c238dd70#diff-a539d272b24cf98cb319fb27637a06c9faf52cfea40d0af87cf1b7c2fec0915cR477 just before calling `setShowEligibility( true )`

This is a follow-up of https://github.com/Automattic/wp-calypso/pull/81412/files/ba9ca69b1062c6b7f886bd5c492e6744c238dd70#r1326478989

**Comment by epeicher** [comment]
@WBerredo, after a quick investigation, I have found that the `EligibilityWarnings` component already has the following track events:
- `calypso_automated_transfer_eligibility_show_warnings` when the modal is displayed
- `calypso_automated_transfer_eligibilty_click_proceed` when the `Continue` button is pressed in the modal

Do you think we should add specific track events for this scenario?

For reference, this is a screenshot of the events triggered when opening the eligibility modal:
<img width="1051" alt="CleanShot 2023-09-18 at 12 28 11@2x" src="https://github.com/Automattic/wp-calypso/assets/3519124/444700d7-c0b1-4eea-9426-597ed2fd07f1">

**Comment by WBerredo** [comment]
> Do you think we should add specific track events for this scenario?

That's a good point, I don't see that much value in having a specific event for this case, and the already created events should be enough for funneling.

Thanks for the investigation.

**Comment by epeicher** [comment]
Closing this task as existing track events can be used for possible funneling. Please see the comment above https://github.com/Automattic/wp-calypso/issues/81768#issuecomment-1723140912 to check the track events.
