### ISSUE TITLE
Back button on domain only flow checkout switches to domain + new site flow

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#81787]
### Quick summary

If you click the back button when checking on the domain-only flow `/start/domain/domain-only`, it sends you the domain + site creation flow `/start/domains`.

Video here: p1694800610241119/1694760534.062509-slack-C02FMH4G8

### Steps to reproduce

1. Start at `/start/domain/domain-only`
2. Select a domain to purchase
3. Select to purchase the domain only without creating a site
4. At checkout click the back button
5. You'll be redirected to `/start/domains`

### What you expected to happen

You should be redirected to `/start/domain/domain-only`

### What actually happened

You're redirected to  `/start/domains`

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Firefox – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated using the on-screen `<` Back button, but not the Browser `<-` Back button.  Here's a comparison:

**On Screen Back Buttton**


https://github.com/Automattic/wp-calypso/assets/27249804/57aa0c5c-b72f-40af-8fac-f38b86acb027

**Browser Back Button**

https://github.com/Automattic/wp-calypso/assets/27249804/07db6686-1af9-4b34-aeb9-c0c5e23229cc

📌 ACTIONS
- Triage complete

**Comment by renancarvalho** [comment]
I tried to reproduce this issue doing the same steps as you did, and it did not happen. I noticed that the checkout step has changed a bit, for instance, there's no back button anymore, now there's a close button. Perhaps this was fixed.

**Comment by madhusudhand** [comment]
> I noticed that the checkout step has changed a bit, for instance, there's no back button anymore, now there's a close button. Perhaps this was fixed.

I tried reproducing this issue on latest version. Both close button click and browser back button takes user back to domain-only page.

Closing this issue. Please re-open if it's still happening.
