### ISSUE TITLE
Critical bug where customers can lose content if they happen to go offline

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#81782]
## Description

If you start drafting a post and go offline, it appears that any content you add to the editor after the point that you went offline can be lost (and not recoverable). I recorded a video walking through the steps you can take to reproduce this bug. I suspect most people won't know that this is happening and will lose content when this happens.

https://github.com/Automattic/wp-calypso/assets/5634774/e615a67f-1bac-4983-807f-c721ee9f67f4

## What I expected

- I expected to be notified somehow that I had gone offline, so that I know something is wrong and I can maybe pause and make a quick manual backup of my content
- When I come back online, I expect to be able to save draft, preview my post, and publish again without having to reload the page
- If I do reload the page, I expect to not lose any content.

## What actually happened

1. There was no warning that I had gone offline
2. There was no way to mitigate the issue without reloading the page as the save, preview, and publish buttons all stayed deactivated (even after I came back online)
3. I lost content after refreshing the page

## How to reproduce
- Start a new post on WP.com
- Enter a title and some text
- Save draft
- Open dev tools
- Under the network tab toggle your connection to offline
- Make more changes
- Click save changes
- Come back online
- Reload page
- Changes you made after you went offline are gone

## Setup

- MacBook Air M1
- Chrome Version 116.0.5845.187

**Comment by davemart-in** [comment]
Just noting that I can't reproduce this on JN, so this looks to be limited to Simple sites.

**Comment by jp-imagines** [comment]
User in 6638520-zd-a8c has been reporting this issue – or at least something very similar to it – for a while now. They noticed this happens with auto-saving specifically. They've provided two YouTube videos outlining and demonstrating the issue in real time in the linked ticket.

We've had difficulty replicating the user's report in the past, which may make sense if the issue only comes about if you go offline before/during a save.

They have identified a manual workaround: after identifying the issue has happened (the save/publish buttons are "stuck"), copy all content, open the editor for that post in a new tab, and replace any previously saved content with the updated copy. Definitely not ideal, as it seems to happen quite frequently for this user.

**Comment by flootr** [comment]
This seems very much related or may be the same issue as reported in https://github.com/Automattic/wp-calypso/issues/80822

**Comment by davemart-in** [comment]
Closing this in favor of #80822
