### ISSUE TITLE
Theme Showcase: Translation and CSS issue on Tooltip with theme description

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#81825]
## What

Two issues with the description tooltip:

**1. Theme description is not translated for all themes**

The cause seems to be that the string contains transformed special characters that differ from the translated string.

This issue has been blocked/abandoned for years. See https://github.com/Automattic/i18n-issues/issues/293 and D64821-code

**2. Minor CSS issue in the arrow up**

It should look like the arrow down but opposite direction:

|ARROW UP|ARROW DOWN|
|--|--|
|![Image](https://user-images.githubusercontent.com/1881481/268580355-94b0578f-7519-45e7-9337-2ae256fa992f.png)|![Image](https://user-images.githubusercontent.com/1881481/268580501-5b792de1-f105-4956-be0e-fed745efcd86.png)|

## Why

These issues affect the Dotcom Theme Showcase and Marvel team can help solve them. 

## How

- Let's collaborate with team Global to fix the translation issue and after it's merged themes must be reindexed. 
- The CSS issue seems a quick fix that can be done in a separate PR.

**Comment by autumnfjeld** [comment]
@miksansegundo  Do you have an idea what the effort/difficutly/time is needed to fix this?
What should be the priority?

**Comment by okmttdhr** [comment]
👋 
- I raised a PR https://github.com/Automattic/wp-calypso/pull/83160 to fix the 2nd issue. 
- I sent a ping to @yuliyan in the original issue https://github.com/Automattic/i18n-issues/issues/293 and Slack message.

**Comment by okmttdhr** [comment]
According to @yuliyan's reply https://github.com/Automattic/i18n-issues/issues/293#issuecomment-1767964359, I think we can close this issue for now. Let's reopen or create another ticket if the fix does not come. :)
