### ISSUE TITLE
Stats: Date picker - investigate API changes for a custom date range

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#81832]
The chart and navigation buttons on the Traffic page are linked with the site's URL parameters.
Investigate the current mechanism and check if we need to adjust anything when we pass custom dates from a date picker.
Check how the summary pages and the insights page are affected.

**Comment by a8ck3n** [comment]
Just dropping a few notes here based on investigations so far.

> Check how the summary pages and the insights page are affected.

From what I can tell, the Insights & Subscribers pages are not affected by any changes to the date/chart. None of the metrics on those pages are tied to the current date/range.

> The chart and navigation buttons on the Traffic page are linked with the site's URL parameters. Investigate the current mechanism and check if we need to adjust anything when we pass custom dates from a date picker.

- The chart and chart heading update correctly in response to different startDates.
- My current understanding of the chart is that it does not accept a range, only a start date. So a shortcut like "Last 7 days" will not work with the chart as is.
- The provided date is not assigned the initial point on the x-axis. Setting `startDate=2023-09-01` does not mean the chart will start from Sept 1st.
- The chart seems to work with variable length data arrays. If we get 30 days of data from the API but only pass 7 to the chart, it will properly draw only those 7 increments.
- If the chart needs more space than is visible in the view, it will be clipped. There is no overflow or scroll set so certain dates fall outside the view and can't be visualized or clicked. They can be accessed using the left/right arrows but as the chart doesn't update, this looks like a bug from an end user POV.
- The chart doesn't properly show selection when using `startDate` in combination with `week` or `month` increments. In these cases, it only works if the specified date lies on a week or month boundry.
