### ISSUE TITLE
Upgrading to eCommerce plan wipes out content from users' sites.

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#81850]
### Quick summary

Tested on my test site and can replicate. Dropping a quick report here for now to escalate internally.
Test site where I could replicate:
https://test9575home.wpcomstaging.com/

User on 6932454-zen reported issue of missing pages (content) on their site after having upgraded from Personal plan to eCommerce plan on Sep 14, 2023.

- Activity log shows "server" deleted two pages they had:
<img width="631" alt="Screenshot 2023-09-18 at 13 23 13" src="https://github.com/Automattic/wp-calypso/assets/31009008/f6e172f3-a67b-45f6-b8c9-bf3198d375f9">
- During troubleshooting I reverted site back to Personal, then upgraded to Business, activated hosting features -- site went atomic, all good, pages were there. When I added the eCommerce sub to the site in our systems (SA) the bug immediately happened -- pages were gone (not even in Draft, or Trash).
- I reverted the site again, and again went to Business plan and turned the site atomic. This time though instead I installed the Woo plugin from Marketplace and issue did not occur. The user needed to remain on the Business plan, and cannot use the eCommerce plan until this is resolved.

### Steps to reproduce

1. From a simple site (not atomic), go to My Site > Plans
2. Upgrade to eCommerce plan
3. Check your site pages in My Site > Pages

### What you expected to happen

To see my existing pages/content maintained, while the default Woo pages are added (My account, cart, checkout, Shop).

### What actually happened

Pages are deleted by server activity, and Woo pages are added instead.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple > eCommerce – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
3 pages I created on my free simple site were removed from the site - they're not found in drafts or trashed. 

![Markup on 2023-09-18 at 12:36:36](https://github.com/Automattic/wp-calypso/assets/27249804/7696f88d-18b8-4746-a47c-c9b270dcd76a)

📌 ACTIONS
- Increased priority to `Blocker`

📌 Message to Author
- Thanks for the escalation thread, @davipontesblog ! 

Escalation: p1695058112065739-slack-C02FMH4G8

**Comment by cuemarie** [comment]
_~@/edwinho89~ (sorry Edwin!)_

@worldomonation has replicated as well. Posts were preserved, but pages existing on the site before the upgrade were removed.

**Comment by worldomonation** [comment]
I reproduced:

- set up a Free site.
- made posts and pages, uploaded media.
- upgrade to eCommerce plan.
- upgrade never finished, stuck at Step 3 in the process.
- used a new tab to view the site, pages are gone. Posts remain, media remains.

**Comment by markbiek** [comment]
I was also able to reproduce, though the upgrade process _did_ finish properly for me. I also noticed that only Page content was deleted. Posts/etc were fine.

**Comment by PanosSynetos** [comment]
I'm working on a fix on Calypso Bridge's side - I'll ping when ready!

**Comment by PanosSynetos** [comment]
Closing this, it has been fixed in PR
- https://github.com/Automattic/wc-calypso-bridge/pull/1304

I've released WPCOMSH 3.13.24 and Calypso Bridge 2.12.15 , that include the above PR

It will be deployed on Atomic later in the day; check slack #atomic-alerts
