### ISSUE TITLE
READER - Updates to post do not reflect in the reader

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#81856]
In Slack, @thomashorta relayed:

> Hello :blob-wave: I was checking some of my own test posts on reader and found a possible issue with the reader APIs. Not sure if this is the right place to report it, so feel free to point me in the right direction if I should report somewhere else.
> The issue is that making updates to published posts is not propagated to the Reader version of that post. At first I was testing it in the app and thought it was a bug in the way the app was fetching the post, but then I noticed the behavior also happens on web, so my guess is that it’s something related to the API and how we save posts.
> Here’s an example:
> Post inside the blog (updated content): https://randomthdev.business.blog/2023/09/18/post-with-different-post-image-and-featured-image/
> Same post in Reader (initial published content): https://wordpress.com/read/blogs/217370754/posts/394

We should dig in to see if this was a regression somewhere. I can only assume that this worked correctly at some point.

### Steps to reproduce

1. Publish a post 
2. Open that post's reader version
3. Add new content to the post and Update
4. Refresh reader version of post
     - Observe that the new content does not appear.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on Simple & Atomic. Updates did not appear on Reader version of posts after 5-10 minutes

Simple

https://github.com/Automattic/wp-calypso/assets/27249804/9db67d37-c2de-4f81-ad83-993d96005140

Atomic

https://github.com/Automattic/wp-calypso/assets/27249804/0cf94b45-94f4-4725-81c9-acaaf623d874

📌 ACTIONS
- Added steps to replicate to post

**Comment by roo2** [comment]
this was fixed by D122614-code
