### ISSUE TITLE
Live Preview: Shows the name of the current theme in the prompt text

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#81878]
# Description

We want to show the name of the current theme in the prompt text when users are to activate a previewing theme.
<img width="618" alt="Screenshot 2023-09-19 at 16 39 49" src="https://github.com/Automattic/wp-calypso/assets/5287479/1194e249-ffab-4de8-950f-06bfb9a76b19">

HEs get questions from users about this, like "I want to go back to the previous theme", so resolving this issue might help mitigate that. pdtkmj-1JP-p2#comment-3193

Project Thread: pbxlJb-3Uv-p2

# Related 
I had a try in https://github.com/WordPress/gutenberg/pull/54587, but `getCurrentTheme` does not make sense since [theme-previews.php](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/theme-previews.php) overrides `get_stylesheet()` anyway.

**Comment by arthur791004** [comment]
Completed via https://github.com/WordPress/gutenberg/pull/57588
