### ISSUE TITLE
Add a test to ensure the first step of the onboarding flow would be rendered correctly

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#81879]
Referring to p1694560963053709-slack-C02FMH4G8, the onboarding flow might redirect the user back to the signup flow again. It might be better to have a test case to ensure the first step of the onboarding flow would be rendered correctly.

## Tasks

- [ ] Write a test to ensure the first step of the onboarding flow would be rendered correctly.

**Comment by autumnfjeld** [comment]
@arthur791004  Should we move this into Ready for Dev?

**Comment by lsl** [comment]
Test was added here https://github.com/Automattic/wp-calypso/pull/82633

Post mortem write up here p58i-fmC-p2
