### ISSUE TITLE
FSE themes: Pagination numbers from the Page Break Block doesn't show on live page

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#81898]
_Core report: https://github.com/WordPress/gutenberg/issues/54691_

### Quick summary

When adding a Page Break Block in a post/page, it's showing on the editor, but not on the preview and live page. 

This issue can be reproduced on FSE themes, such as Payton, Munchies, Nokul, Thriving Artists, etc. but not on classic themes., such as Storefront and Twenty Twenty. 

This can be reproduced on Simple sites and Atomic sites with Gutenberg plugin active. 

### Steps to reproduce

1. Open a post or a page
2. Add a [Page Break Block](https://wordpress.com/support/wordpress-editor/blocks/page-break-block/)
3. Add some content below the Page Break Block
4. Check the Preview or update the page and check the live page

### What you expected to happen

The pagination numbers show. The following screenshot is when Twenty Twenty theme is active. 

<img width="896" alt="Markup 2023-09-19 at 20 00 37" src="https://github.com/Automattic/wp-calypso/assets/33721365/1b86c1eb-931b-466b-ba96-684b880cb920">

### What actually happened

The pagination numbers doesn't show on the live page and on the preview. The following screenshot is when Payton theme is active. 

<img width="970" alt="Markup 2023-09-19 at 20 08 26" src="https://github.com/Automattic/wp-calypso/assets/33721365/5f1906f7-271c-4d6e-b4fb-21f60ef97298">

### Impact

Some (< 50%)

### Available workarounds?

- For Atomic sites: Yes, easy to implement. 
- For simple sites: No workaround

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Issue specific to FSE themes
- Reproduced on Chrome
- User report: 6956308-zd-a8c 

**The workaround is to deactivate Gutenberg plugin on Atomic sites.**

**Comment by john-legg** [comment]
📌 REPRODUCTION RESULTS

Tested on Simple – **Replicated**
Tested on Atomic – **Replicated**
Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate the issue as described on Simple and Atomic using Chrome, Firefox, and Safari. Using the steps above, I was not able to see the pagination numbers on the live site.

**Editor**
<img width="699" alt="Screenshot 2023-09-19 at 11 52 11 AM" src="https://github.com/Automattic/wp-calypso/assets/96805492/2426d70e-bea7-4b44-baf9-d234391cc0d1">

**Live**
<img width="699" alt="Screenshot 2023-09-19 at 11 52 21 AM" src="https://github.com/Automattic/wp-calypso/assets/96805492/359bdd21-ff2d-4f56-b8e5-120a61dca835">

On a self-hosted site, I'm able see the pagination numbers, but the content below the Page Break block is not visible.

**Editor**
<img width="699" alt="Screenshot 2023-09-19 at 11 57 09 AM" src="https://github.com/Automattic/wp-calypso/assets/96805492/e287c7cc-85bc-4841-8676-b477edd6d983">

**Live**
<img width="699" alt="Screenshot 2023-09-19 at 11 57 24 AM" src="https://github.com/Automattic/wp-calypso/assets/96805492/4120944b-a589-4313-8006-68d6cc0da257">

**Comment by upwardmomentum84** [comment]
In testing on a local WP install. The issue is present in Gutenberg 16.6.0. I tested earlier versions and the issue is not occurring with Gutenberg 16.5.1.

**Comment by upwardmomentum84** [comment]
I've reported this bug here: https://github.com/WordPress/gutenberg/issues/54691

**Comment by tellisbethel** [comment]
Another case here: 7046686-zd-a8c
Atomic, TT3 theme (FSE)
User would like to be updated when issue is resolved.

**Comment by villanovachile** [comment]
Another case: 7046686-zen
Disabling Gutenberg resolved issue.

User would like to be updated when issue is resolved

**Comment by cuemarie** [comment]
From https://github.com/Automattic/themes/issues/7425
Ticket: 7150318-zen

**Comment by cuemarie** [comment]
From: #83056 :
Ticket: 7119217-zen

**Comment by laragee6** [comment]
issue can also be seen in the Optimismo theme
7175542-zen

**Comment by ai2n** [comment]
Another with Pendant theme
7205029-zen

**Comment by john-legg** [comment]
From https://github.com/Automattic/themes/issues/7441:
Ticket: 7171882-zen

**Comment by pauloeaquino** [comment]
7216912-zen

**Comment by sanjeev00733** [comment]
Another report in 7153229-zen. The user wants to get an update when this gets fixed

**Comment by ntsekouras** [comment]
I closed the GB ticket as it cannot be reproduced. I think we can close this one too..

**Comment by jorgefilipecosta** [comment]
I tested this issue on dotcom sites and everything works as expected going to close this issue.
