### ISSUE TITLE
Rename "Remove WP.com Ads" feature to "Remove Advertising"

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#8192]
In p2MSmN-5qC-p2, @eurello reported that many users think that our footer credit is an ad and by upgrading to the Personal or Premium plan (which include "Remove WordPress.com Ads"), the footer credit will be removed. However, that's possible only for Business plan and the feature "Remove WordPress.com Ads" removes only the third-party ads.

Can we change "Remove WordPress.com Ads" feature title to "Remove Advertising"?

/cc @rralian @gwwar

**Comment by artpi** [comment]
I don't think we should jump the gun here.
We need overall consistent feature taxonomy and we shouldn't rename on the whim whenever user is confused.
I agree this is bad naming, but we need a bit of coordination here.

**Comment by gwwar** [comment]
cc @meremagee any opinions on this one?

**Comment by lancewillett** [comment]
Closed with https://github.com/Automattic/wp-calypso/pull/8523
