### ISSUE TITLE
Stats: Date picker - style the sortcuts section

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#81939]
Following the completion of #81936 and #81938 apply proper CSS to match the design for the shortcut section.

The shortcuts should be versatile to accept different shortcuts if other consumers (another page or a team) need them. Clicking on a shortcut should update date text inputs and shouldn't close the dropdown.

## Design

![Image](https://github.com/Automattic/wp-calypso/assets/112354940/c6659599-3a78-4cb7-8cc6-e3e8a53e08a2)

**Comment by grzegorz-cp** [comment]
@a8ck3n this is done, isn't it?

**Comment by a8ck3n** [comment]
Mostly? I think it needs a review to make sure this and the intervals are styled consistently once the behaviour is fully implemented. Also padding/margin values probably need an update following the final design update.

**Comment by a8ck3n** [comment]
Confirmed this needs some minor touch-up now that the surrounding hierarchy has changed. Padding and/or margin is off now that it's inside a flex layout.
