### ISSUE TITLE
Stats: Date picker - create the remaining shortcuts

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#81938]
After implementing #81936, implement the remaining shortcuts to match the designs.
The component should be ready to transform to a select list for mobile view (implement this as part of this ticket or create a new one if it extends the scope significantly).

Keep in mind that the final CSS changes are handled in #81939

## Design

![Image](https://github.com/Automattic/wp-calypso/assets/112354940/2ad15d3d-f23c-4ab1-874f-dbf145e7614f)

**Comment by grzegorz-cp** [comment]
We clarified in a discussion in the i1 design thread (p1HpG7-oHM-p2#comment-66213) that the shortcuts should only fill in the date input values, not apply them and close the component.

**Comment by a8ck3n** [comment]
Closing this one now. We have separate issues for styling and mobile support.

- #81939
- #82308
