### ISSUE TITLE
Add the option to hide the Post Content Block from the Editor screen

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#81935]
### What

I would like to request an option to hide the Post Content Block in the block settings.

### Why

Reason: A user (6986690-zd) mentioned it messes with their idea of how the page looks and would like a way to hide the content block on the editor.

I believe having the option to display a placeholder text or alternatives, like a border or background color, to signify what this section does, or to display a semi-transparent render of a page (if it's a static frontpage) or to hide it completely, would be great for users who prefer to display it differently on their editor screen.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

📌 Message to Author

> I believe having the option to display a placeholder text or alternatives

@1dr0 currently, if a customer edits the page or single posts template via Appearance > Editor > Templates > Page/Single Posts, the post content block does show placeholder content, like this: 
![Markup on 2023-09-21 at 10:18:18](https://github.com/Automattic/wp-calypso/assets/27249804/fa719c31-133f-4d91-abdb-45aec1d35940)

Were they seeing that and getting thrown off, or were they seeing the page/post content itself and hoping to see something more like the placeholder text above?

**Comment by danielk-am** [comment]
> Were they seeing that and getting thrown off, or were they seeing the page/post content itself and hoping to see something more like the placeholder text above?

Thank you for the ping! If this helps, the user mentioned they "do not want a block on their page telling me it's a content block". Which means not seeing the placeholder text altogether.

**Comment by cuemarie** [comment]
I see, thanks!  I think they probably want something like the previous version of the placeholder content, which was actually updated to the text to improve the confusion around the block in https://github.com/WordPress/gutenberg/pull/40177

Given all the work done to add that text, and how much confusion still stems from the Post Content block, I don't imagine for now the core team would move back to that version, or remove it entirely - but I've submitted a feature request as an idea for a possible solution for customers like this one, who prefer a visual placeholder instead:

- https://github.com/WordPress/gutenberg/issues/54893

📌 ACTIONS
- I'll leave this open for now to see if we run into any other users who request this sort of change.

**Comment by annezazu** [comment]
Closing this out but noting that https://github.com/WordPress/gutenberg/issues/58136 remains a known issue for DotCom.
