### ISSUE TITLE
Settings reset if they are not saved fast enough

### ISSUE THREAD

**Issue by koke** [Automattic/wp-calypso#8194]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Change some settings like privacy and related posts, do not save settings
3. Wait 15-20 seconds
4. Settings go back to their old values
#### Browser / OS version

Safari on macOS Sierra

**Comment by lancewillett** [comment]
I couldn't repeat this one. @koke Could you re-open if you see it again?
