### ISSUE TITLE
Make plan expiration date more explicit

### ISSUE THREAD

**Issue by kingsleyinfo** [Automattic/wp-calypso#81947]
### What

Add an extra column that shows the plan/subscription expiration when auto-renewal is turned on for a user with a valid payment method. 

![Screen Shot 2023-09-20 at 09 55 24](https://github.com/Automattic/wp-calypso/assets/12503321/6139a51d-4cdf-4deb-9993-245f67774d96)

### Why

Generally, we aim to renew subscriptions 30 days before the actual expiry. We are constantly seeing interactions where this becomes a challenge to explain. As much as we expect users to take our word for it, it's even more vital if we can have a place to point this information out to them. 

It fosters transparency and makes what we say more valid as they can see this information themselves. The alternative of having to turn off auto-renew to see that information is counterproductive. 

### How

Option one: We can add an extra column on this page with the subscription expiry date, see screenshot.

![Screen Shot 2023-09-20 at 09 51 32](https://github.com/Automattic/wp-calypso/assets/12503321/0f984e0c-a10a-478c-8594-fc2b5185997f)

Alternatively, we can add extra information that shows the actual expiration date of the plan.

"Your plan expires on 20 October 2024, but you will be billed on 20 September 2024, to avoid service disruption"

Maybe it can be worded differently, but the general idea would be to show the user the exact date the plan expires on the site

**Comment by cuemarie** [comment]
Thanks for this thoughtful request, @kingsleyinfo !

📌 ACTIONS
- Feature request kept
- CC @Automattic/shilling

**Comment by DavidRothstein** [comment]
I'd stay away from wording like "expires" (since it's not expiring), but maybe something like "paid through 20 October 2024" would be good?

Although we'd probably implement something like this as generally as possible, in practice it would only matter for plans and domains (since those are the only products that actually renew early) so not sure if the relevant teams for those would want to weigh in here.

**Comment by DavidRothstein** [comment]
Does anyone else have input on this?  I'm moving it to our "Discussion" column for now.

It does seem like a worthwhile change that could have a nice benefit without a ton of effort.

**Comment by sirbrillig** [comment]
🤔 In my mind the hard part would be trying to figure out what date to show (that is, where to get the correct date on the backend). We have trouble with this in other contexts (like checkout TOS) and I imagine it would be hard here too, but maybe not. 

Do you have any idea how to get this date? If so, including it on the product page would be pretty trivial.

**Comment by DavidRothstein** [comment]
I think it would just be `expiry_date` (from the purchases endpoint) rather than `renew_date`?

![purchases-endpoint](https://github.com/Automattic/wp-calypso/assets/235183/63a2250d-b789-4195-a6da-95ede32b3dc3)

Most likely it's the same date we already use on this page when auto-renew is turned off.

**Comment by sirbrillig** [comment]
Cool. Let's do it.

**Comment by jjchrisdiehl** [comment]
I'm not sure this needs its own column, I'll experiment with adding a column versus adding the text inline to the existing **Subscription Renewal** column.

**Comment by jjchrisdiehl** [comment]
**In the existing column**
![image](https://github.com/Automattic/wp-calypso/assets/16580129/5308ffa2-bcaa-4b2a-be84-b50543671c43)

**In separate column**
![image](https://github.com/Automattic/wp-calypso/assets/16580129/bbf4a79e-c54a-4ef0-98c5-8f15c4dab097)

Now after I've tested it, I agree that a separate column is more clear. I also thought adding an inline link to our renewal notice was a good idea for this section:

![image](https://github.com/Automattic/wp-calypso/assets/16580129/bec7491a-3743-4006-b1b6-58187f6a57d7)

I'll have a PR up shortly.

**Comment by jjchrisdiehl** [comment]
This should be resolved by https://github.com/Automattic/wp-calypso/pull/83383 - closing for now.
