### ISSUE TITLE
Big descriptions shrink the blogroll image in the editor

### ISSUE THREAD

**Issue by heavyweight** [Automattic/wp-calypso#81954]
<img width="697" alt="Screenshot 2023-09-20 at 11 20 58" src="https://github.com/Automattic/wp-calypso/assets/7000684/b978867a-5a71-40cf-9f99-d756e32c9661">

**Comment by alshakero** [comment]
Closing as fixed.

**Comment by alshakero** [comment]
Managed to repro https://sfds793760509.wordpress.com/2023/09/27/test/

**Comment by alshakero** [comment]
Fix is here https://github.com/Automattic/jetpack/pull/33344

**Comment by heavyweight** [comment]
reproduced and confirmed the fix on the PR
