### ISSUE TITLE
Videos not showing in emails

### ISSUE THREAD

**Issue by kirstenmclacey** [Automattic/wp-calypso#81962]
### What

I would like for emails that are auto-sent to subscribers when I write a post to include the video.

### Why

The emails that subscribed users receive from my website (Learnandcreate.org) on WordPress.com doesn’t have the video embedded or even linked. I wasn't aware of this and received a fair bit of feedback about it. Without the video embedded, these emails sometimes don't make sense and offer little value.

Given that other newsletter platforms do this, it feels like a bit of a miss feature. Is this a known bug or by design?

I see on support forums that it's been referenced before:
2014: https://wordpress.com/forums/topic/why-doesnt-video-appear-in-e-mail/
2017: https://wordpress.com/forums/topic/my-embedded-videos-dont-show-when-sending-as-a-newsletter/

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by ivan-ottinger** [comment]
Hello @kirstenmclacey 👋🏼🙂 Thanks for your report.

I have checked the current behavior. VideoPress and YouTube videos are displayed in the emails sent to subscribers with a video thumbnail and a ▶️ button in the middle like this:

<img width="785" alt="Screenshot 2024-09-25 at 16 27 18" src="https://github.com/user-attachments/assets/72c110e4-d484-4f87-9cb0-a67274a63c88">

Clicking on the VideoPress video thumbnail then leads to the post itself, while clicking on the YouTube video goes to the video on YouTube.

Please let us know if that helps or should you have any questions.

---

Email technology generally is quite limited and therefore the video itself cannot play in the email client directly.
