### ISSUE TITLE
Post Carousel Block: Block stops rendering when randomly adjusting block options

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#81999]
### Quick summary

One of our customers reported that when they modified the options for the Post Carousel Block, the block seemed to disappear from the page. I was able to reproduce this on a test page the customer created:

https://github.com/Automattic/wp-calypso/assets/2912202/dcb613ef-c14b-46db-8607-f5a34332707d

The issue seemed to be somewhat intermittent as I wasn't able to reproduce this in a previous test. I then tried to reproduce the test on one of my test sites. I initially tested with a single Post Carousel Block and couldn't reproduce the issue:

https://github.com/Automattic/wp-calypso/assets/2912202/499a8675-5f09-4cb8-a88e-2f03bc6e2fe0

When I experimented with multiple Post Carousel Blocks, I noticed that making a series of changes to one of the blocks' settings didn't result in the block being removed from the page although the content of the block stopped loading. Here is a test on the customer's Test page:

https://github.com/Automattic/wp-calypso/assets/2912202/92a5dd5b-2931-42a8-ac55-ff809b5db530

This is a test on my test site:

https://github.com/Automattic/wp-calypso/assets/2912202/9c048e01-d3ea-4851-910a-f47391cd4bbc

### Steps to reproduce

1. Add one or more Post Carousel Blocks to a page
2. Make a series of changes to the block's options

### What you expected to happen

The block should continue to render correctly and change as the block options are updated.

### What actually happened

- In my initial test on the customer's Test page, the Post Carousel Blocks on the customer's Test page stopped rendering at all.
- When I tried to reproduce the issue as part of this issue report, I noticed that the content of the Post Carousel Blocks stopped loading, even though the blocks didn't "disappear" from the page as I saw in my initial test.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I ran my tests in the following environment:

- macOS 13.5.2
- Microsoft Edge Dev browser v118.0.2088.9

Our customer experienced this issue in the following environment:

- macOS 10.15.7
- Safari v16.6

Original report: 7006887-zen
Follow-up: 7009297-zen

My test page: https://wordpress.com/page/he20171027.com/1353 (will require special access by Automatticians)

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
I could replicate this consistently in Simple and Atomic with the following steps: 

- Add 2 Post Carousel Block to page with various settings
- Save draft and refresh the page

**Example on Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/01351dd3-8489-4725-8c0c-24e794cc2c7c

📌 ACTIONS
- Lowered priority to Normal

📌 Message to Devs

This looks quite similar to a conflict with Gutenberg 16.3+ that's impacting the Blog Posts block, which is also a newspack block:

- https://github.com/Automattic/wp-calypso/issues/80069

@leogermani do you think this could be the same conflict?

**Comment by annezazu** [comment]
https://github.com/user-attachments/assets/ac92ba75-83d4-4bcf-8415-10a49964a69f

I can't replicate this on a simple site both when trying to create in a page and a template. I am going to close this out as I can't see further reports of this and can't replicate.
