### ISSUE TITLE
Jetpack Plugins: add settings link

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#82]
Add a settings link to each plugin card, using the new Button component.

![1bef9d74-65f5-11e5-9fc7-a63cb6cf1aed](https://cloud.githubusercontent.com/assets/426388/11244466/f99e2bfa-8e0d-11e5-8aa0-461725cfe979.png)

Before we can expect that link that work, we need to make sure we catch each plugin. That could be tricky as it really depends on when and how the plugin decides to add the url to the plugins filter. Currently there is no standard way of doing this.

It might be easier to open a ticket in Core first, and suggest a new filter/function that would allow plugin devs to define where the canonical settings URL when the plugin includes one.

**Comment by rickybanister** [comment]
This is related to #447

**Comment by lancewillett** [comment]
Related #2206 but still not implemented. Jetpack plugins in Calypso don't have a settings like to go directly to wp-admin settings for that plugin.

**Comment by roundhill** [comment]
> It might be easier to open a ticket in Core first, and suggest a new filter/function that would allow plugin devs to define where the canonical settings URL when the plugin includes one.

Hey @jeherve we're thinking of adding something like this for at least the most popular plugins. Do you know if any effort was made to get this added to core?

**Comment by jeherve** [comment]
I'm not aware of any work on that, I'm afraid.

**Comment by drw158** [comment]
Here's my suggestion for the design. The proposed method in #6267 will pull more than just a settings link.

wp-admin:

![screen shot 2017-02-06 at 2 17 14 pm](https://cloud.githubusercontent.com/assets/618551/22664677/4bf67664-ec77-11e6-83c7-630625312615.png)

my design:

![screen shot 2017-02-06 at 2 18 25 pm](https://cloud.githubusercontent.com/assets/618551/22664684/5435e0e4-ec77-11e6-8212-4c54f84e2a39.png)

**Comment by MichaelArestad** [comment]
I would put the settings link in a secondary button underneath the plugin icon/name/author. I would put any other links with the other links to the left of the ratings chart.

**Comment by rickybanister** [comment]
@MichaelArestad the design you mention is in the OP of this thread.

**Comment by MichaelArestad** [comment]
@rickybanister I know, but I want the button to be under the icon, too.

**Comment by roundhill** [comment]
The Jetpack PR for the API is close to being merged. When we start working on this, let's make sure to add a stat for when the settings links are clicked. Ref: https://github.com/Automattic/wp-calypso/issues/11063

**Comment by roundhill** [comment]
We have the API now so I started on the implementation of this in Calypso. I added the buttons beneath the icon and made the all Buttons that use the external link icon:

<img width="689" alt="screen shot 2017-02-28 at 3 27 23 pm" src="https://cloud.githubusercontent.com/assets/789137/23439227/9ddbe55e-fdca-11e6-8fc4-f7550659f32c.png">

I added some duplicates to test how it wraps:

<img width="686" alt="screen shot 2017-02-28 at 3 25 44 pm" src="https://cloud.githubusercontent.com/assets/789137/23439263/c1bf6b6c-fdca-11e6-9c22-a350dc65c558.png">

**Comment by rickybanister** [comment]
This is great, but an interesting point came up today during an in-person discussion about AT with @drw158:

Immediately after installing a new plugin, I'd have to imagine the most common thing someone wants to do is configure that plugin (by accessing some sort of settings link). This design is optimized more for accessing that settings link later.

We should do a mockup that overlays some kind of success banner that includes a link to configure settings (if we have access to the appropriate link).

**Comment by MichaelArestad** [comment]
@rickybanister or it could just highlight the settings link somehow, but I see your point.

**Comment by roundhill** [comment]
That's a good idea, although we don't have much data to work with. We get the link url and the link name (localized), so we could see if the url has something like `settings` or `options` in it to try and determine what we should link to in the success banner?
