### ISSUE TITLE
Jetpack Plugins: hidden sites and their plugins should not be displayed anywhere in Calypso

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#820]
A user can hide a site by going to wp-admin > My Blogs (from any of their sites' wp-admin). Right now, we don't display hidden sites in the sidebar. 

However, the plugins for a hidden site do show up on
https://wordpress.com/plugins and its tabs:
https://wordpress.com/plugins/active
https://wordpress.com/plugins/inactive
https://wordpress.com/plugins/updates

Steps to reproduce:
1. Connect a site via Jetpack
2. See that the site shows up on the sidebar on http://wordpress.com
3. Hide the side by first going to the wp-admin area for any of wp.com sites for the same user, and then to Dashboard > My Blogs. You can hide a Jetpack site at the bottom of the page
4. Go to http://wordpress.com/plugins and see that the Jetpack site's plugins are showing up, but the site is not showing up in the sidebar

**Comment by v18** [comment]
Related: errors about plugins from hidden sites should also not be displayed. For example, if a user has a hidden site and Calypso cannot fetch its plugins (due to a bad connection, etc), they'll see this error message:

<img width="979" alt="7af970d0-71c9-11e5-8f8a-d3929d2256c5" src="https://cloud.githubusercontent.com/assets/11487924/11472374/051f2c06-973a-11e5-9473-d8ea22205c57.png">

**Comment by enejb** [comment]
Closed via https://github.com/Automattic/wp-calypso/pull/1489

**Comment by jeherve** [comment]
Reopening, as the problem still exists:
![screen shot 2016-01-08 at 12 12 57 pm](https://cloud.githubusercontent.com/assets/426388/12196708/2fa9e4f8-b601-11e5-88f9-d48be78c1b0f.png)

Most of these sites are hidden from Calypso, but they still generate error messages in Calypso.

Related: #1344
