### ISSUE TITLE
Signup: InvalidStateError after domains substep in Firefox

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#8200]
https://cloudup.com/c5bHP_rWY5i
#### Steps to reproduce
- in firefox, go through signup steps starting at wordpress.com/start
- select custom domain in domains step
- decline google apps for business upsell
- notice plans step shell loads but is empty for ~30sec

**Comment by lsinger** [comment]
Upsell no longer there afaict. Closing.
