### ISSUE TITLE
Onboarding: Insert generic starter posts to blog themes

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#82009]
## Description

"Blog" themes, which are themes that are intended to be used as "blog", don't look good on new sites (after onboarding), because most of the times they don't look like the theme preview. This is mostly visible on Launchpad. Example for Trellick:

|Trellick in Design Picker|Trellick in Launchpad|
|-|-|
|![image](https://github.com/Automattic/wp-calypso/assets/1525580/8ffa2360-373f-4a20-81bb-8ce70c347d9b)|![image](https://github.com/Automattic/wp-calypso/assets/1525580/ec75fe89-32c9-4599-a8f9-128f833e3495)|

After doing some spike in https://github.com/Automattic/dotcom-forge/issues/3735, we agreed that in order for a newly onboarded site to "look like the theme preview", when it uses a "blog" theme:

- it should have some kind of starter (placeholder) posts, so that the post list does not look empty
- the post featured images (if any) should be the same as those of the theme demo site
- the post title / content can be generic; it does not affect the layout

## Acceptance Criteria

After a new site is onboarded,

- If the theme's homepage has a Query Loop block:
   - [x] It should have posts as many as the theme demo site's (but capped at most 6).
   - [x] The posts should have the same featured images from the theme demo site (if any).
      - [x] The images are present in the site's media library.
   - [x] The post titles and excerpts are generic texts.
   - [x] The post content is in such a way that it's clear that it is just a placeholder post.
   - [x] The Launchpad's "Write your first post" task is still open.
   - [x] The Launchpad can still be completed as before.
- otherwise:
   - [x] The new site has the default post (from the default Headstart annotation) (no change in existing behavior).

## Dev Tasks

- [x] https://github.com/Automattic/wp-calypso/pull/81732
- [x] D121838-code

@Automattic/lego

**Comment by miksansegundo** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/81732
