### ISSUE TITLE
Update Learn more link for Export Media Library option

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#82017]
### Quick summary

The "Export media library" option has a "Learn more" link to a support doc. The support doc is being moved to a new location.

Current: https://wordpress.com/support/export/#exporting-the-media-library
New: https://wordpress.com/support/export-your-media-library/

### Steps to reproduce

1. On a simple site, navigate to Tools → Export (Default calypso view)
2. In the Export media library box, click "Learn more"

<img width="587" alt="Screenshot 2023-09-21 at 4 55 56 pm" src="https://github.com/Automattic/wp-calypso/assets/30727666/b4cc0537-a234-4802-81df-ad4f8e990109">

### Impact

Most (>50%)

### Available workarounds?

No but the platform is usable

### Logs or notes

The link can be updated now. I will hold off on removing the information from the old doc until this link is updated.

**Comment by donalirl** [comment]
Sorry, I don't know how to stop this from adding the `Escalated` label. I had marked this as "No but the platform is usable" but it defaulted back to "unusable" after I made a small edit.

**Comment by cometgrrl** [comment]
@donalirl Don't worry about those labels. We get pinged in #dotcom-triage-alerts in Slack, and adjust the priorities as needed. We'd rather have it be prioritized too high to start vs too low, but we are also planning an update to the matrix.

**Comment by cometgrrl** [comment]
@Automattic/caribou does this fall under your area?

**Comment by vishnugopal** [comment]
Yes it should! cc @zaerl as hero!

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 ACTIONS
- Relabeled as Enhancement

📌 Message to Author
@donalirl if you file these as Enhancements/Feature Requests (since they're not really bugs, they're just updates following doc updates), those github actions won't trigger a notification to KitKat - we only escalate High and Blocker issues that are labeled as `[Type] Bug`.

No biggie either way, but just mentioning since I tend to relabel these as Enhancements anyway :)

**Comment by donalirl** [comment]
@bogiii Sorry if I'm missing something, but although the link is updated, clicking on 'Learn more' triggers the help center, which displays the old doc. I checked on my usual account and a non-a8c test account.

![Screenshot 2023-10-24 at 6 52 27 pm](https://github.com/Automattic/wp-calypso/assets/30727666/c346cc74-bfc6-4555-9e07-ba6a2875f006)

**Comment by bogiii** [comment]
Thanks @donalirl, for reporting it.
The link is updated; if you right-click on the link and select the "Open Link in the tab" option, you will see the updated support page.

I didn't realize the content of the help center. I'll fix it as soon as possible!
