### ISSUE TITLE
Newsletter login: update email with the code

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#82013]
Currently, when a subscriber is already subscribed to a site and they want to log in to see the content, we send this email:

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/e02a6f73-f83f-446e-aa0f-df31878f358e)

## Design proposal
Update the design template to this design.
It uses the regular newsletter template.

RJAj9CwrUQnRceVbQ8QVl6-fi-18_1308.

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/110fa5db-09f1-4614-adde-190a67031627)

**Comment by simison** [comment]
Not relevant anymore with magic login.
