### ISSUE TITLE
Gutenberg 16.7 RC: blank templates with only Pattern Placeholder in the block structure

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#82023]
### Quick summary

When running Gutenberg 16.7 RC on a simple edge site, most templates are not loading any content when using a8c block themes. The Site Editor canvas will load a blank page or just text blocks with unstyled text. In most templates, the block structure only lists a Pattern Placeholder block similar to what we've seen before in #79145.

Potentially related to the introduction of Font Management pbxlJb-4wB-p2 I'm reporting in case it's something different.

https://github.com/Automattic/wp-calypso/assets/14153300/de71d0d9-53ca-4b15-bc1b-8332d72590e0

<img width="1502" alt="CleanShot 2023-09-21 at 09 40 16@2x" src="https://github.com/Automattic/wp-calypso/assets/14153300/1d6587bb-fce2-4852-afe2-98f1056e1fe1">

cc @dsas (since you handled the previous "Pattern Placeholder" issue) and @fullofcaffeine (as this is a blocker for merging 16.7)

### Steps to reproduce

1. Activate a a8c block theme (don't use TT3/TT2)
2. Load the Site Editor

### What you expected to happen

The templates should load correctly

### What actually happened

No content or missing content in the templates.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated with Gutenberg: v16.7.0-rc.1 on a Free site created 2023-09-21. It seems like this is visible on TT3 (see 404 page, for example), but more visible on other themes:

**TT3**

https://github.com/Automattic/wp-calypso/assets/27249804/8e9d179e-9a3e-4d63-a848-342508de6c02

**Stewart**

https://github.com/Automattic/wp-calypso/assets/27249804/a5470db2-8594-4264-be66-95b26385b2fb

📌 Message to Author
- @liviopv thanks for the report! I'll wait to escalate this further, since you've pinged a couple relevant folks already 👍

**Comment by dsas** [comment]
Looking at the backtrace the error is triggered from `editor-beta`, which is Jetpack. I'll try reproducing on .org with and without jetpack later.

**Comment by dsas** [comment]
I can't reproduce it on a dotorg JP site, with the GB beta plugin, without ETK (can't try with ETK that is busted) and with the Awburn theme.

I can't reproduce it on an atomic site with the GB beta plugin, with ETK and the Awburn theme.

I can reproduce it on a simple site with the edge sticker and the Awburn theme.

**Comment by dsas** [comment]
@fullofcaffeine this is still happening with rc2. Using the "awburn" theme, when editing the home template the code is:

```
<!-- wp:group {"style":{"border":{"top":{"color":"var:preset|color|secondary","style":"solid","width":"10px"},"right":[],"bottom":[],"left":[]},"position":{"type":"sticky","top":"0px"}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="border-top-color:var(--wp--preset--color--secondary);border-top-style:solid;border-top-width:10px"><!-- wp:template-part {"slug":"header","theme":"pub/awburn"} /--></div>
<!-- /wp:group -->

<!-- wp:pattern {"slug":"awburn/home"} /-->

<!-- wp:template-part {"slug":"footer-home","area":"footer","theme":"pub/awburn"} /-->
```

but the [`awburn/home` pattern](https://github.com/Automattic/themes/blob/trunk/awburn/patterns/home.php) isn't rendering in the editor, just the front-end.

It's definitely a different bug to the similar sounding #79145 I worked on before - that was triggered by patterns using `postTypes` in metadata, which isn't the case here.

**Comment by liviopv** [comment]
Switching priority to Blocker since it doesn't seem to be fixed by disabling the Font Management on WordPress.com as I hoped. Context: p1695732252770119?thread_ts=1695664978.633309-slack-CBTN58FTJ

**Comment by fullofcaffeine** [comment]
Thanks for reaching out, I'll have a look at this today.

**Comment by ramonjd** [comment]
On WordPress.com, I can also reproduce the issue on a simple site with the edge sticker and the Awburn theme.

But on a local WordPress installation, I could not. I ran a check on the following: 

- WordPress 6.3 and Awburn theme
- WordPress 6.3 with Gutenberg 16.7 and Awburn theme
- WordPress 6.3 with Gutenberg trunk and Awburn theme
- WordPress 6.3.1 and Awburn theme
- WordPress 6.3.1 with Gutenberg 16.7 and Awburn theme
- WordPress 6.3.1 with Gutenberg trunk and Awburn theme
- WordPress 6.4-alpha with Gutenberg trunk and Awburn theme

All were working as expected in the Site/Post editors and frontend. 

Is it just happening with themes based on [Block Canvas](https://github.com/Automattic/themes/tree/trunk/block-canvas)?

**Comment by kraftbj** [comment]
Possibly relevant: to load beta blocks of Jetpack, you'll want to set `JETPACK_BETA_BLOCKS` PHP constant to true (e.g. in wp-config.php). WP.com does this but a stock install of Jetpack wouldn't.

**Comment by kraftbj** [comment]
I can duplicate the `toLowerCase` issue on a fresh WordPress site + Gutenberg RC + Jetpack + Jetpack beta blocks.
