### ISSUE TITLE
Include coupon details in calypso customer receipts

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#82025]
### Quick summary

Under https://wordpress.com/me/purchases/billing don't reflect when they have used a coupon on a purchase. 

For example: ![h31TTy.png](https://github.com/Automattic/wp-calypso/assets/42655541/c0074e51-df8f-41b3-9767-04aea67c7574)

### Steps to reproduce

1. Make a wpcom purchase using a coupon
2. Review the receipt under https://wordpress.com/me/purchases/billing

### What you expected to happen

I expected the receipt to provide a detailed breakdown of the pricing including original price, coupon amount, taxes, and total actually paid.

### What actually happened

It just shows the total actually paid without any breakdown or details.

### Impact

All

### Available workarounds?

There is no user impact

**Comment by cuemarie** [comment]
📌 ACTIONS
- Refiled as Feature request
- Feature request kept

📌 Message to Author
  - Just a quick note, we do show the discount applied in the receipt the user receives by email; so if the customer is looking for that in their receipt, this could supplement for now. Here's a quick example _(just pulled up a random user who recently used a coupon code):_

![Markup on 2023-09-26 at 15:34:21](https://github.com/Automattic/wp-calypso/assets/27249804/0deab1fc-cbbb-41ad-bf79-172439bd060d)

**Comment by sirbrillig** [comment]
The data provided to the calypso receipt page appears to come from the `https://public-api.wordpress.com/rest/v1.3/me/billing-history` endpoint, which doesn't mention anything about the fact that a coupon was used. The coupon is saved as a tag on the receipt, so we can add it to the endpoint and then update calypso to support it.

I'm working to add it to the endpoint in D124069-code

**Comment by sirbrillig** [comment]
https://github.com/Automattic/payments-shilling/issues/2076 may cover this by adding all discount reasons to receipt items.

**Comment by sirbrillig** [comment]
After https://github.com/Automattic/payments-shilling/issues/2076 is merged, we should be able to provide that data to the endpoints and then display it in calypso. Just waiting on those changes...

**Comment by susanjanec** [comment]
Another user brought this up in this ticket - 7153384-zd-a8c

**Comment by sirbrillig** [comment]
I've abandoned D124069-code in favor of D127406-code which adds all the purchase discounts to the calypso (not email) receipt view.

I've created https://github.com/Automattic/wp-calypso/pull/83768 to display those discounts, although it needs some UI work.
