### ISSUE TITLE
Plans: Fix Price Placeholder

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8203]
I noticed that the price placeholder could be spaced further from the plan title. To reproduce, navigate to:

![loader](https://cloud.githubusercontent.com/assets/1270189/18847490/503c1cb6-83df-11e6-8548-f346600a0767.gif)

- http://calypso.localhost:3000
- select a site
- loader is too close

I also noticed that jetpack sites appear to be missing the placeholder. 
![loading](https://cloud.githubusercontent.com/assets/1270189/18847676/f7dcbebc-83df-11e6-9c82-21eabe882494.gif)

**Comment by artpi** [comment]
Improvement idea:
Lets hardcode those and pull only discounts from endpoint.

That will solve placeholder issues, be snappier and overall provide better experience.
I am even willing to volunteer to make a test measuring if hardcoding prices increases revenue.

**Comment by gwwar** [comment]
> Lets hardcode those and pull only discounts from endpoint.

I'm of the opinion of hardcoding everything but price. We'd have to do it for all currencies, and it'd be a pain on any price test.

cc @rralian

**Comment by nitrajka** [comment]
Hi, 
would this issue be solved, if we just add some styles to the existing placeholder? 
Look:
![imageedit_5_5847160480](https://cloud.githubusercontent.com/assets/14272775/19042908/39880c3c-898e-11e6-89f5-4d8403d679f1.jpg)
This placeholder is now styled with `height: 12px`. If we change it to 39px and set margin-top to 10px, then the height of the `<PlanFeaturesHeader>` component (which you can see in the following picture)
<img width="1280" alt="screen shot 2016-10-03 at 17 33 58" src="https://cloud.githubusercontent.com/assets/14272775/19043247/aba7df9e-898f-11e6-8662-274c324b2744.png">
 would be the same while and after price loading.  
![imageedit_17_8869698192](https://cloud.githubusercontent.com/assets/14272775/19043364/1bdde72c-8990-11e6-82c1-1a210ed0b080.jpg)
There also wouldn't be such height difference (while and after price loading) as you can see...
I also found out, that the `<PlanFeaturesHeader>` component is used only in the `<PlanFeatures>` component. But its 'grandparents' may be used in several places. So it may also affect several other parts of Calypso. Let me find out where else...

**Comment by gwwar** [comment]
Closed by 8418
