### ISSUE TITLE
Provide more detail when a user tries to log in with a renamed account

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#82068]
### What

When a user tries to log in with the username for a renamed account, they currently just receive a message that their account was closed. Instead, for users whose account was renamed (as opposed to actually closed accounts), could we mention that the account was renamed?

### Why

This is a low impact issue, but we do receive several emails a month from frustrated users who cannot understand why their account shows as closed when they try to log in using their old username.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
