### ISSUE TITLE
Task: Decide on a split method for what tests to include in the Jetpack AT smoke test.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82076]
### Details

We discussed (briefly) at the meetup on how to determine what tests to include in the Jetpack AT smoke test.

Pros and Cons of each:

**Vertical**
Run the entire suite of Jetpack AT E2E specs we have currently, but just for one user.

Pros:
- only one configuration to manage.
- emphasizes feature coverage.

Cons:
- will not detect issues with one particular user configuration.

**Horizontal**
Runs a handful of suites, across the whole (or majority) subset of users.

Pros:
- wide coverage of user configurations.

Cons:
- lacking feature coverage.

**Mapped Matrix**
Coming up with an arbitrary matrix, aimed at running all suites but on at most two users per suite.

Pros:
- covers all features and user configuration.

Cons:
- needs maintenance.
- only as good as the (arbitrary) methodology used to choose the mapping.

### Checklist

- [ ]
- [ ]

**Comment by dpasque** [comment]
Thank you so much for drafting this up -- it's so helpful to see these different strategy approaches! 😄  Maybe when I'm off of support rotation next week, we can also draft up a P2 to get some broader feedback from Jetpack folks on their perferences?

**Comment by worldomonation** [comment]
@dpasque I'm thinking whether there's a need to do a RFC P2 at all. At least in my case, it takes several iterations plus a lot of time for me to come up with a coherent message, and I think that time is better spent debugging and optimizing the suites.

I say this because through trial and error on https://github.com/Automattic/wp-calypso/issues/82074 and https://github.com/Automattic/wp-calypso/issues/82497, it looks like the root of the problem with Editor-related specs is that there are simply too many tests running on the machine at any given time.

I'll kick off the discussion by asking about this in Slack and see where we go from there.

**Comment by worldomonation** [comment]
Thread: p1696837958442599-slack-CDLH4C1UZ

**Comment by dpasque** [comment]
Done in #82893
