### ISSUE TITLE
Task: Update MailPoet banner title

### ISSUE THREAD

**Issue by NeosinneR** [Automattic/wp-calypso#82078]
### Details

There is a MailPoet banner in the Marketplace (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Swrgcnpx%2Qwvgz%2Swvgz%2Qratvar.cuc%3Se%3Q30q5qonp%23792%2Q800-og).

<img width="1111" alt="screenshot-2023-09-21-at-13 01 25" src="https://github.com/Automattic/wp-calypso/assets/470616/33b30552-144d-44a9-ae2b-baac4ac15b05">

I'd like to ask for two changes:
1. Update the title to `MailPoet – Newsletters, Email Marketing, and Automation` as is the title of the SaaS product.
2. Update the link to `https://wordpress.com/plugins/mailpoet-business`.

### Related

- pdh6GB-38D-p2#comment-3888

**Comment by cpapazoglou** [comment]
Diff created D123293-code

**Comment by cpapazoglou** [comment]
Deployed r276267-wpcom
