### ISSUE TITLE
Feature Request: limit font size for inline comments on post cards in Reader

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#82087]
### What

We're now showing inline comments on post cards in the Reader stream, which is really nice!

If the highlighted comment happens to include some big text (like a `h2`), we also show that:

<img width="631" alt="Screenshot 2023-09-25 at 12 26 08 PM" src="https://github.com/Automattic/wp-calypso/assets/17325/f82baecb-2335-4d84-a03c-5694005bc0a5">

It would be good to confine the font size to the same size for all elements, I think.

Example of an affected post (internal users only): p7DVsv-iHO-p2

### Why

The large text looks unexpected. It's not quite a bug, but it doesn't feel right.

### How

When the comment block `is-inline`, set the font size for all child elements using `*` selector in CSS.

cc @davemart-in

**Comment by davemart-in** [comment]
Added to our list. Thanks!
