### ISSUE TITLE
LoTS: Community themes not getting installed after onboarding

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#82102]
### Quick summary

When a user selects a Community theme (e.g. Astra) and purchase a Business subscription, the site is not transferred to Atomic and the theme is not installed on their site.

Instead, they are now redirected to the Design Picker.

Slack discussion(p1695636274671899-slack-C048CUFRGFQ) where we've determined that the regression was introduced in this https://github.com/Automattic/wp-calypso/pull/81340.

### Steps to reproduce

1. Start from http://wordpress.com/start/with-theme/domains-theme-preselected?ref=calypshowcase&theme=zakra&theme_type=dot-org
2. Purchase a Business subscription
3. Notice that after checkout you're now redirected to the Design Picker

### What you expected to happen

The user should automatically be redirected to the marketplace thank you page where the theme installation process should start (since they've signed up with a theme). 

### What actually happened

The user is redirected to the design picker

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by worldomonation** [comment]
Slack thread: p1695636274671899-slack-C048CUFRGFQ

**Comment by BogdanUngureanu** [comment]
Handled in https://github.com/Automattic/wp-calypso/pull/82930
