### ISSUE TITLE
WordAds Ad dashboard doesn't load the settings after changes saved

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#82123]
### Quick summary

When we make any changes on the WordAds Ad Dashboard setting page, we receive a Saved Successfully message, but if I refresh the page, all the settings are lost. However, when I go back via: Tools > Earn > View Ad Dashboard > Settings, all the settings are there and we can see that the change was saved as well.

So far we could not replicate this on other sites, besides the user's reported sites: 6841842-zd-a8c

### Steps to reproduce

1. Go to the View Ad Dashboard page https://wordpress.com/earn/ads-settings/
2. Make a change to the settings; for example toggle "Display ads below posts on" "Posts" and Save Settings
3. Received the successful save, but if I refresh, all the settings are missing. 
4. Click Tools > Earn > View Ad Dashboard > Settings => you can find all the settings again, including the one we changed. So it was indeed saved.

Ps. The settings seem to reset as well if we don't make a change. So visit Tools > Earn > View Ad Dashboard > Settings (Settings are there) => Refresh the same page and the settings disappear. 

### What you expected to happen

The settings would not be reset if I refresh the page. 

### What actually happened

They disappear when the site is refreshed. 

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Could Not Replicate**
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO

The issue has been addressed in #82139. I've verified that after making changes and saving the settings, they stay the same even after refreshing the page.

**Simple - Premium**

https://github.com/Automattic/wp-calypso/assets/67279475/5b84a753-b539-4716-a9e4-a17b8de1d9b9

**Atomic**

https://github.com/Automattic/wp-calypso/assets/67279475/76d4a2f6-0fe3-4159-912c-89bb884f456d

📌 ACTIONS
- Closed as no longer relevant (issue resolved by issue #82139)
