### ISSUE TITLE
Blogroll: Subscription Fails with "Invalid Email" Error for Logged-Out Users

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#82124]
### Quick summary

When attempting to subscribe to a blog listed on the Blogroll while logged out, I get an "invalid email" error and the subscription fails. However, subscribing works as expected when logged in.

### Steps to reproduce

1. Make sure you are logged out. 
2. Visit a page/post with a Blogroll block ([example](https://kcrsimple.wordpress.com/2023/09/25/this-is-a-test/)). 
3. Subscribe to any blog.
4. Observe the error message: "Your subscription did not succeed, please try again with a valid email address".
5. Log in to your account.
6. Try subscribing to the same blog.
7. Note that the subscription succeeds without error.

### What you expected to happen

Since there is an option to subscribe when viewing the page with a Blogroll block and it asks for my email, I should be able to successfully subscribe without receiving an error message regarding an invalid email. For logged-out users, there should be a clear message indicating what's expected or needed when they attempt to subscribe to the blog.

### What actually happened

I get the error message: "Your subscription did not succeed, please try again with a valid email address". I tried using an email with a WordPress.com account but still got the same error.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

**Logged Out**

https://github.com/Automattic/wp-calypso/assets/67279475/7eff89ad-279b-4b29-a2e0-12158a3f2d5e

**Logged In**

https://github.com/Automattic/wp-calypso/assets/67279475/c65971c3-b14f-4b0b-9bf5-3b5db1e5528d

cc: @Automattic/vertex

**Comment by crisbusquets** [comment]
While I'm working on these flows, would it also be possible to change the CTA background and font color when the user is subscribed?

For example:
- Default CTA: White background, black text, `Subscribe`
- Subscribed CTA: Black background, white text, `Subscribed`

**Comment by simison** [comment]
@crisbusquets managing opposite colours for buttons might be challenging, as themes I think define just one colour and the hover styles. (happy to be proved wrong of course!)

Should we use some kind of check mark ✔ instead to make them stand out more?

**Comment by alshakero** [comment]
Maybe we can remove the button entirely and use just a grey-ish text in Italic?

**Comment by crisbusquets** [comment]
> @crisbusquets managing opposite colours for buttons might be challenging, as themes I think define just one colour and the hover styles. (happy to be proved wrong of course!)


@simison With opposite colors I meant that we use as a background the one thats used on the text ant the other way around. But I understand this might be tricky from a dev standpoint.

Something like changing the primary button for the secondary button on the theme (if they have it).

<img width="377" alt="Screenshot 2023-09-26 at 17 31 51" src="https://github.com/Automattic/wp-calypso/assets/25607244/846cded2-65cc-4b05-9b4b-9a7a38ad7438">

Pinging @TimBroddin, I know he worked on Newsletter Category pills that had some issues with the color. I'm unsure if he discovered something related to this.

> Should we use some kind of check mark ✔ instead to make them stand out more?

Tried it, but I'm not a big fan of it (it's difficult to visually differentiate both states):
<img width="339" alt="Screenshot 2023-09-26 at 17 39 04" src="https://github.com/Automattic/wp-calypso/assets/25607244/53aef4e3-2c96-4fd8-9a84-bd1feca77bae">


> Maybe we can remove the button entirely and use just a grey-ish text in Italic?

@alshakero To ensure it works with all themes, I'd use the same font-color they use:
<img width="339" alt="Screenshot 2023-09-26 at 17 37 57" src="https://github.com/Automattic/wp-calypso/assets/25607244/030f121d-c924-4c4e-8f3d-e39b8bb1ee5d">


Related to this: what should we do when someone clicks `Subscribed`? I was thinking about opening Subscription Management and in the future, a modal where they can unsubscribe or upgrade that subscription.

**Comment by simison** [comment]
The button block also has two styles from core — "default" and "outline", in case that helps:

<img width="990" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/6f93acad-5453-4dbf-8d1c-a6708795868e">

**Comment by crisbusquets** [comment]
> The button block also has two styles from core — "default" and "outline", in case that helps:
> 
> <img alt="image" width="990" src="https://user-images.githubusercontent.com/87168/270733997-6f93acad-5453-4dbf-8d1c-a6708795868e.png">

Aaaah yes! This could help! 🙏🏼 Can we try it?
Thank you @simison

**Comment by alshakero** [comment]
Yes absolutely. We use that in the cancel button already.

![image](https://github.com/Automattic/wp-calypso/assets/17054134/93e224f3-ef2c-4f68-8387-e83ebe79570f)

**Comment by TimBroddin** [comment]
> Pinging @TimBroddin, I know he worked on Newsletter Category pills that had some issues with the color. I'm unsure if he discovered something related to this.

Working with colors can be a real headache 😀 While working on the subscription pills, I haven't found a silver bullet that works for both classic & block themes.
