### ISSUE TITLE
Blogroll: Duplicate Recommendations for the Same Blog is Allowed

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#82122]
### Quick summary

Users can recommend a blog more than once, even if it's already added to their blogroll.

### Steps to reproduce

1. Add a Blogroll block. 
2. Add a Blogroll item and select a blog to recommend. 
3. Add another Blogroll item and select the same blog to recommend. 
4. Observe that you can recommend the same blog again.  

https://github.com/Automattic/wp-calypso/assets/67279475/1af8c6d0-edea-4677-832f-74c7a08b644e

### What you expected to happen

Once a blog is recommended and added to the Blogroll list, it should either be grayed out, removed from the list of recommendable blogs, or there should be a notification stating that the blog is already on the list.

### What actually happened

You can add the same blog multiple times.

![FxFxQ3.png](https://github.com/Automattic/wp-calypso/assets/67279475/6ee2ec0b-5aac-4c38-95f3-499e591b7038)

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

cc: @Automattic/vertex

**Comment by crisbusquets** [comment]
> Once a blog is recommended and added to the Blogroll list, it should either be grayed out, removed from the list of recommendable blogs, or there should be a notification stating that the blog is already on the list.

I prefer we don't remove it from the list — a user may think the search box isn't working or that the site doesn't exist. Here's a proposal where the site that's already on the Blogroll has a different background and it's a bit grayed out.

**Specs**
- Background is `gray 0` (we can try with `gray 5`, but I suspect it would be too dark)
- Avatar, site name and description is 50% opacity
- The user can hover it, but the cursor will be the `not-allowed` one

<img width="1595" alt="d_v1_duplicate" src="https://github.com/Automattic/wp-calypso/assets/25607244/85779341-2442-4f76-880d-6941318dfc78">


I also thought about adding a small tooltip, but I'm unsure if it's an overkill. Perhaps in a second iteration, after hearing user's feedback?

**Figma file:**
aOWo8Hpzper3EIXwPbuyzU-fi-374_4054.

**Comment by heavyweight** [comment]
Sounds good to me.
