### ISSUE TITLE
Reduxify: Migrate plugins

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#8213]
This issue is for overall discussions on redux-ifying plugins. We're aiming to get rid of the flux store (migrate to redux). Also, the plugin components were written early-on in Calypso, and could use a refresh, to clean up duplication, naming, and to get it up-to-date with our ESLint standards.
- [x] Reducer, Actions, Selectors – See #8206 
- [x] `QueryPlugins` component - @tyxla - See #8275
- [ ] Audit plugin components — @rickybanister @johnHackworth you both seemed interested :)
- [ ] Replace `lib/plugins/log-store.js` with something, probably the notice middleware, since notices should be triggered on success & failure actions
- [ ] Swap out the flux stores for redux state

I think the order I've added this is how we should tackle it, with some things happening in parallel. The component audit/cleanup should probably be done as separate PRs from the redux-ification, just to make sure we're not doing 2 big changes at once. Do we want to set a time to chat on slack about components? Or just leave feedback on components on this issue (and create separate issues if needed)?

cc @oskosk @tyxla @roccotripaldi 

Related #5046

**Comment by ryelle** [comment]
Some followup from #8206:

- No `createSelector` yet, the selector & tests need to be updated to accept just siteIds
- After fetching plugins, we want to be able to trigger an update for all sites' plugins #8653
- The queue for plugin actions is not in place yet (branch in progress)

I think a good use-case test would be to implement the redux state/actions on plugins autoconfig. Since this is self-contained, it's a much faster conversion than waiting for all the plugins components to be updated, and we can make sure the actions etc make sense.

**Comment by tyxla** [comment]
The `QueryJetpackPlugins` component is ready for review: #8275.

**Comment by tyxla** [comment]
I'm going to close this in favor of #24180, which I'm starting work on.
