### ISSUE TITLE
Image Editor: Disable Jetpack Sites if Version doesn't include new media endpoint

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8214]
In order to support #8081 we need to update the media endpoint to be able to update it's file contents. Until a site updates to whatever Jetpack version this falls into, they won't be able to successfully edit an image. So hide the "Edit Image" button in the media details view.

Alternatively we can keep the current copy flow, but this might add additional confusion to how this feature works.

**Comment by artpi** [comment]
PR disabling for jetpack merged, but Im leaving this issue open so we can follow up with proper endpoind checking once it's operational in Jetpack
