### ISSUE TITLE
Live Preview: Transition modal

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#82187]
# Description

Due to a backlog of design work, we will implement the smart modal #80264 later, and instead immediately create a simple modal with only title and text and normal UI elements (like the X close and a continue button).

## Example modal
This modal can be used as a visual guide.  Use the same:
* title font
* body font
* close X
* one single button [Continue]
![image](https://github.com/Automattic/wp-calypso/assets/5665959/54da325d-ed64-434a-bf43-5492c40fce18)

## Acceptance Criteria
- [x] create simple modal with basic instructional copy
- [x] the modal will overlay the site editor, so it can be seen behind the modal. Same implementation as other modals.
- [x] the modal should have a "Do not see this again" box.    Please look at existing modals for exact copy here, reuse what is on an existing modal. 

## Copy
**Title:** 
Preview & Customize {theme_name}

**Body**
Welcome to the WordPress Editor.  You will be previewing {theme_name} in the Editor with your site's content. If you like what you see you can Activate the theme directly in the Editor.

Most users find the Styles and Pages features particularly helpful in evaluating the look and feel of a new theme.   

To exit the Editor Preview and get back to the theme showcase, click the small arrow next to "Previewing". 

[ ] Do not show this modal again.

[Continue]

**Comment by autumnfjeld** [comment]
EDIT: Let's not do this, but leaving the comment here as a seed for future iteration.

One possibility is that we should show this as an image in the right side of the modal:

@Automattic/lego  and @lucasmendes-design  What do you all think?

<img width="349" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/d5507af1-fd68-432d-a6c2-809aa3fe46ba">

**Comment by fushar** [comment]
This is shipped.
