### ISSUE TITLE
Update Subscriptions API endpoints to return feed ID.

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#82183]
### Details

Update Subscriptions API endpoints to return feed ID. (Warning: Possible challenge around Subscription Matrix ID (DB) to Feed ID (ES) lookup.)

### Checklist

- [ ] Update Subscriptions API endpoints to return feed ID.

**Comment by mashikag** [comment]
Addressed in D123240-code

**Comment by phcp** [comment]
Closed by D123240-code
