### ISSUE TITLE
Cart: Chat button overlaps payment button on mobile view

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#82196]
> the support chat button overlaps the payment button.

> When the chat button appears in blue color they seem the same button.

https://github.com/Automattic/wp-calypso/pull/82008#pullrequestreview-1639177182

![image](https://github.com/Automattic/wp-calypso/assets/5039531/a1a9b350-95ae-46d5-bd85-73e5398623de)

![image](https://github.com/Automattic/wp-calypso/assets/5039531/ccce7a50-fc61-4f2e-addc-041f58aba032)

**Comment by cpapazoglou** [comment]
Pinged in p1695817784632389-slack-C029GN3KD for ideas

**Comment by cpapazoglou** [comment]
Can't reproduce it anymore.
