### ISSUE TITLE
People: Adjust wording in the notice when removing a user from a site

### ISSUE THREAD

**Issue by mattyza** [Automattic/wp-calypso#8220]
#### Steps to reproduce
1. Remove a user from a site, using Calypso's people management.

#### What I expected

I expected a notice which stated that I had _removed_ the user successfully.

#### What happened instead

I received a notice stating that I had deleted the user, successfully. This is ambiguous, and may be scary to some users.

#### Screenshot / Video

![image](https://cloud.githubusercontent.com/assets/880803/18870360/8f8738ac-84b0-11e6-812e-679a5e36e149.png)

**Comment by folletto** [comment]
This is a good advice to have a more precise language. 

I agree with you in using "removed" instead of "deleted":

> ✓ Successfully removed @ name

**Comment by rickybanister** [comment]
cc @ebinnion
