### ISSUE TITLE
Design Picker - Theme preview shows a double padding top on themes with useRootPaddingAwareAlignments as true

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#82228]
## What

Themes like [Bibliophile](https://github.com/Automattic/themes/blob/88570611f1ce54ab9160c0ad5f46ffdd23e014ba/bibliophile/theme.json#L199C3-L199C40) that have `useRootPaddingAwareAlignments: true` and `styles > spacing > padding > top` set in their theme.json show a unexpected double top padding on the theme previews.

https://github.com/Automattic/wp-calypso/assets/1881481/12a119de-2445-4c64-8fe0-5b5e4bfd19e1

## Why

The theme looks different than expected because of the double top padding.

|Expected Preview|Unexpected Theme Preview in DP|
|-|-|
|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/1c7f84ba-e93a-4839-afdc-85ec6315345c)|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/ca887b93-dd3a-43b8-a27d-3fa5f7caaeb9)|

The endpoint `/wpcom/v2/block-previews/site` adds the padding using the selector `.wp-site-blocks`, which is expected.

The [SitePreview](https://github.com/Automattic/wp-calypso/blob/e408abdc5a7ba8023b37947315fd4792ee4b6403/packages/design-preview/src/components/index.tsx#L140C17-L140C26) component in the DP injects the top padding again but this time using the selector `body` via the Gutenberg hook [useGlobalStylesOutput](https://github.com/WordPress/gutenberg/blob/b813d3d28e4651c2e1a5f0c55f9e4b879e5dfdbf/packages/block-editor/src/components/global-styles/use-global-styles-output.js#L793), which is not expected because these styles are for the editor canvas only, not for the front of the site.

## How

- Option 1: Inject CSS in the `SitePreview` to remove the top padding from the `body`. See [INJECTED_CSS](https://github.com/Automattic/wp-calypso/blob/e408abdc5a7ba8023b37947315fd4792ee4b6403/packages/design-preview/src/hooks/use-inline-css.ts#L5).
- Option 2: Reset the body padding before injecting the styles as we do in [GlobalStylesVariationContainer](https://github.com/Automattic/wp-calypso/blob/e408abdc5a7ba8023b37947315fd4792ee4b6403/packages/global-styles/src/components/global-styles-variation-container/index.tsx#L43)
- Option 3: rather than using [useGlobalStylesOutput](https://github.com/WordPress/gutenberg/blob/b813d3d28e4651c2e1a5f0c55f9e4b879e5dfdbf/packages/block-editor/src/components/global-styles/use-global-styles-output.js#L1243) that gets the config from the context, we can remove the setting `useRootPaddingAwareAlignments` and pass a custom config using `useGlobalStylesOutputWithConfig` directly.

**Comment by miksansegundo** [comment]
@arthur791004 which solution would be better? cc: @Automattic/lego

**Comment by fushar** [comment]
I am trying to understand the issue better.

I tested and it looks like in the frontend, the top padding is applied to `.wp-site-blocks`, whereas in the Editor, the top padding is not there (however it is there in the `body`). Do you know why? I mean why the Editor needs to manually inject the padding in the `body`; it looks like if the top padding were to be always present in `.wp-site-blocks`, the problem is solved.

**Comment by miksansegundo** [comment]
There are [comments](https://github.com/WordPress/gutenberg/blob/1fb1343c42a59d5062660a7da20a4bff4d06e369/packages/block-editor/src/components/global-styles/use-global-styles-output.js#L787) in the editor code that inject that CSS in the `body`:
> Root padding styles should only be output for full templates, not patterns or template parts.

>  These rules reproduce the ones from https://github.com/WordPress/gutenberg/blob/79103f124925d1f457f627e154f52a56228ed5ad/lib/class-wp-theme-json-gutenberg.php#L2508 almost exactly, but for the selectors that target block wrappers in the front end. This code only runs in the editor, so it doesn't need those selectors.

**Comment by fushar** [comment]
Yeah, I did see those comments but I didn't get the full picture.

But I think I get it: my current rough conclusion is that we're conflating the CSS used for the frontend (done by the SitePreview) and for the editor (done by the useGlobalStylesOutput()).

I think Option 3 makes the most sense to me, as it's clearer (the intent is clearer and the code will be self-commenting) and we don't have to deal with CSS by hand. 😄

**Comment by arthur791004** [comment]
It might be resolved by D130115-code. We changed to use `gutenberg_get_block_editor_settings` to get the settings and it doesn't seem to return the editor styles that should be applied only to the editor.

**Comment by miksansegundo** [comment]
Not reproducible 👍 

<img width="1665" alt="Screenshot 2566-12-05 at 12 56 17" src="https://github.com/Automattic/wp-calypso/assets/1881481/0c127c1a-d8e5-47dc-bc4f-55b5a0a19384">
