### ISSUE TITLE
Reader/Discover: Format recommended sites data to work with the existing Reader Discover stream

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#82255]
![CleanShot 2023-09-27 at 09 48 11](https://github.com/Automattic/wp-calypso/assets/917632/7f2ba4e6-acdc-447b-9893-d3c217335f7d)

As shown above, we show recommended sites to the right of the recommended posts stream.

We need to update the format of the data we're returning to match the current structure. This includes getting recommended site details.

The existing code can be found in fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sernq%2Qgntf%2Qpneqf.cuc%3Se%3Qrp8352ss%23438-og. 

We need to take that code and make a copy of it (we probably won't need _all_ of it though) in the `RecommendedSitesStream`

**Comment by sixhours** [comment]
Started looking at this in D123574-code

**Comment by sixhours** [comment]
This has been fixed in D123574-code
