### ISSUE TITLE
Add the Legal 500 icon to Social Icons

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#82251]
### What

Our social icons block offers support for multiple social networks and platforms.

A user requested we add the Legal 500 too.

### Why

User requested on 7091668-zd-a8c

### How

As a part of the Social Icons block: https://wordpress.com/support/wordpress-editor/blocks/social-icons-block/

**Comment by cuemarie** [comment]
The Social Icons block is a Core Gutenberg block, and I think this GB issue is probably best suited for something like this:

- https://github.com/WordPress/gutenberg/issues/39868

📌 ACTIONS
- Feature request kept

**Comment by davemart-in** [comment]
No additional requests from customers and this is over a year old, so I'm going to close it.
