### ISSUE TITLE
Reader/Discover: Audit Tracks events to ensure we're still recording views/clicks with the corresponding data

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#82264]
Let's make sure the data we're collecting in the Reader remains the same when we're using the new StreamBuilder-powered API. Two major to-dos for this are:

```[tasklist]
### Tasks
- [x] Audit and document existing Tracks events in the Discover - Recommended stream.
- [x] Ensure we're getting the same results once the new stream is working.
```

**Comment by sixhours** [comment]
@daledupreez has already done a great job of documenting some of the key interaction-related Tracks events in this post: paYKcK-3rS-p2

Additional Tracks event names, gleaned from clicking around the Recommended page, with sample properties:



Event Name | Event Properties
-- | --
calypso_reader_sidebar_discover_clicked | subscription_count: 1065, ui_algo: 'following'
calypso_reader_discover_viewed | ui_algo: 'following'
calypso_reader_infinite_scroll_performed | ui_algo: 'discover_recommended', path: '/discover', page: 3, section: 'discover'
calypso_reader_article_opened | ui_algo: 'discover_recommended', blog_id: 123456789, post_id: 123456789, feed_id: 123456789
calypso_reader_article_closed | ui_algo: 'single_post', blog_id: 123456789, post_id: 123456789, feed_id: 123456789
calypso_reader_feed_link_clicked | ui_algo: 'discover_recommended', blog_id: 123456789, feed_id: 123456789, source: 'reader-discover-popular-sites'
calypso_reader_blog_preview | ui_algo: 'blog_page', feed_id: '6523977'
calypso_reader_share_opened | subscription_count: 1065, blog_id: 123456789, post_id: 123456789, feed_id: 123456789, ui_algo: 'discover_recommended'
calypso_reader_share_action_picked | subscription_count: 1065, blog_id: 123456789, post_id: 123456789, feed_id: 123456789, ui_algo: 'discover_recommended'
calypso_reader_reblog_opened | subscription_count: 1065, blog_id: 123456789, post_id: 123456789, feed_id: 123456789, ui_algo: 'discover_recommended'
calypso_reader_post_comments_button_clicked | ui_algo: 'discover_recommended', blog_id: 123456789, post_id: 123456789, feed_id: 123456789
calypso_reader_site_followed | url: 'http://example.wordpress.com', source: 'reader-discover-popular-sites', follow_source: 'reader-discover-popular-sites'
calypso_reader_article_liked | ui_algo: 'discover_recommended', blog_id: 123456789, post_id: 123456789, feed_id: 123456789, context: 'card'
calypso_reader_post_options_menu_opened | ui_algo: 'discover_recommended', blog_id: 123456789, post_id: 123456789, feed_id: 123456789, environment: 'production'
calypso_reader_conversations_post_followed | subscription_count: 1065, blog_id: 123456789, post_id: 123456789, feed_id: 123456789, ui_algo: 'discover_recommended'
calypso_reader_visit_post_clicked | ui_algo: 'discover_recommended', blog_id: 123456789, post_id: 123456789, feed_id: 123456789, environment: 'production'
calypso_reader_post_options_menu_closed | ui_algo: 'discover_recommended', blog_id: 123456789, post_id: 123456789, feed_id: 123456789, environment: 'production'
calypso_reader_edit_post_clicked | ui_algo: 'discover_recommended', blog_id: 123456789, post_id: 123456789, feed_id: 123456789, environment: 'production'
calypso_reader_block_site | ui_algo: "discover_recommended", blog_id: 123456789, post_id: 123456789, feed_id: 123456789, feed_item_id: undefined, is_jetpack: undefined


This list is not exhaustive; there are more events that fire when you unsubscribe from a blog/discussion, unlike a post, etc. I'm testing these in the new Recommended stream and they appear to be working!

**Comment by sixhours** [comment]
I've yet to find any discrepancies after clicking around with the flag enabled! That makes sense, because the front-end UI hasn't changed, only the API call. Still, good to know the correct data is flowing into the Tracks events after that change. :)

**Comment by sixhours** [comment]
Moving this to needs review if someone would kindly spot-check my work:

Visit `/discover` on a platform without the flag enabled; click around and note the Tracks events/properties you see.

Visit `/discover?flags=reader/discover-stream` and click around. Make sure the same Tracks events/properties are recorded.

**Comment by markbiek** [comment]
cc. @daledupreez If you have some time and want to look at this as well.

**Comment by markbiek** [comment]
@sixhours As far as I can tell, these all look good to me!

**Comment by daledupreez** [comment]
As a quick note regarding Tracks events, @andres-blanco and I just had a relevant discussion about something that we may not be tracking yet. In particular, when we load a Reader page/stream/UI, do we have a way to identify whether there are more posts to fetch or whether we're at the end of the content already? This information will be useful for two things:
1. Working out how often (and why) we're showing limited content for a feed/stream
2. Improving our engagement tracking for infinite scrolling so we exclude pages/streams that don't have more content

**Comment by sixhours** [comment]
@daledupreez Good thinking, I created a new issue to track/implement that! Closing this as complete.
