### ISSUE TITLE
Reader/Discover: Switch to PrependedStream for combining tags and recommended sites

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#82261]
We're currently using a proportional stream combiner which isn't grouping things the way we want.

We need to update the template file to use a PrependedStream to combine the TagsStream and RecommendedSitesStream.

**Comment by sixhours** [comment]
Started work on this in D123433-code

**Comment by sixhours** [comment]
We discovered we didn't need a PrependedStream, just a different ProportionalStreamCombiner without the added injectors. Closing this since we have tickets for those!
