### ISSUE TITLE
Reader/Discover: Performance review of /read/streams/discover

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#82262]
Once the updated Discover stream is fully functional, let's do a final performance review. The new stream needs to be at least as fast or faster than the existing implementation.

We may be able to increase performance by doing more caching in the stream class.

**Comment by sixhours** [comment]
Request Radar suggests that the new Discover stream is slower than the old one:

<img width="1323" alt="Screenshot 2023-10-04 at 9 50 53 AM" src="https://github.com/Automattic/wp-calypso/assets/2124984/e8f7cda9-5b30-4f77-8af8-b37c23b80ea9">

<img width="1408" alt="Screenshot 2023-10-04 at 9 59 00 AM" src="https://github.com/Automattic/wp-calypso/assets/2124984/ff3217e6-afb1-4fa1-8a44-c254fe0599d3">

**Comment by markbiek** [comment]
I didn't see that you'd already started measuring this one so I did some testing too and I see the same thing for the default tag list. Querying a single tag is a bit faster.

| Endpoint                        |  Average (ms) | First Query (ms) |
| ----------------------  |  ------------- | ----------------  |
| discover (default tags) | 1850ms           | 2733ms               |
| discover (1 tag)             | 824ms             | 1709ms                |
| read/tags/cards (1 tag) | 1200ms           | 2454ms              |

Definitely seems like some caching at the stream level is in order.

**Comment by markbiek** [comment]
I wanted to drop a note showing the timing of the Discover endpoint (default tags) with caching on both the `TagStream` and the `RecommendedSitesStream`:

| Endpoint                        |  Average (ms) | First Query (ms)      |
| ----------------------  |  ------------- | -------------------  |
| discover (default tags) | 864ms                 | 3000-4900ms    |
