### ISSUE TITLE
Reader/Discover: Removing RecommendedTagsStream from the discover template

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#82260]
We're going to remove the RecommendedTagsStream from the current discover template as it's not actually necessary. We can leave the stream class in place.

**Comment by sixhours** [comment]
Worked on this  as part of the template change for #82261 in D123433-code

**Comment by markbiek** [comment]
> Worked on this as part of the template change for #82261 in D123433-code

Good deal! I'll change the assignment of this one over to you!

**Comment by sixhours** [comment]
Shipped in D123433-code
