### ISSUE TITLE
Block renaming: Add the original/official block name after the custom name

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#82288]
### What

One idea would be to still include the official block name after the custom name, like "My Custom Name (Group)" or using a visual label.

![Markup on 2023-09-27 at 16:53:15](https://github.com/Automattic/wp-calypso/assets/1136160/b99904f0-50ff-42e1-83c6-928bc832d696)

### Why

The ability to add custom names to blocks is nice, but it may lead to confusion if users name a group by a different block name (like "Columns", for example).

**Comment by cuemarie** [comment]
Hey @eduardozulian , I love this idea! As block naming is part of Gutenberg's functions, this feature request would be best submitted as a Feature Request in the `/gutenberg` GH repo, here: https://github.com/WordPress/gutenberg/issues/new/choose

📌 ACTIONS
- Closed as won't fix
- Recommendation: Submit request to Gutenberg Repo

**Comment by cuemarie** [comment]
Here's the PR for this update on Group blocks, if you'd like to reference this in a Feature Request / Enhancement request in GB! 

- https://github.com/WordPress/gutenberg/pull/53735

**Comment by eduardozulian** [comment]
Thanks, Marie! Moved to a new issue in GB:

- https://github.com/WordPress/gutenberg/issues/55351
