### ISSUE TITLE
Verbum Comments: Update wording / design for sites with "Comment author must fill out name and email" enabled

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#82285]
### Quick summary

In the new Verbum comments, if you are on a site with the "Comment author must fill out name and email" setting enabled, the UI / wording can be confusing.

People seem to be confused because...
1. You're not really logging in if you just provide a name and email.
2. Email is on the same level as WordPress and Facebook logins, so it's easy to miss.

This is discussed in part here: p7DVsv-iqH-p2, and in this comment: pdtkmj-1Gx-p2#comment-3065

### Steps to reproduce

1. Turn on "Comment author must fill out name and email" setting in Settings --> Discussion
2. In incognito mode, look at a published post

### What you expected to happen

Something that differentiates a login (Wordpress/Facebook) from just entering your name/email.

### What actually happened

New UI is confusing some folks

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by dpasque** [comment]
CC @alshakero -- I didn't see this captured anywhere yet, so I made an issue to track it 👍

**Comment by dpasque** [comment]
7018538-zd-a8c

**Comment by alshakero** [comment]
@renancarvalho I think you have fixed this? Can you link the patch and close it please 🙏🏼

**Comment by davemart-in** [comment]
@alshakero mentioned this was resolved. No status update for over a year, so I'm closing it.
