### ISSUE TITLE
Group Block: Offer further customization options

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#82283]
### What

The background image for the Group Block is missing some great elements available in the Cover block

* Focal point picker
* Overlay opacity
* Image filters
* Set as a fixed background
* Set as repeated background (great for small images that will work as a background pattern)

For example, there are no options to set focus and contain options in the background image under the Group Block. 

### Why

It brings feature parity and offer more customization to customers. offers

**Comment by cuemarie** [comment]
Hey @eduardozulian ! As the Group and Cover blocks are both core Gutenberg blocks, this feature request would be best submitted as a Feature Request in the `/gutenberg` GH repo, here: https://github.com/WordPress/gutenberg/issues/new/choose 

I'd bet there's already some discussion on the different ways the Cover and Group blocks will work taking place, so folks that triage there can probably connect your request to those conversations!

📌 ACTIONS
- Closed as won't fix
- Recommendation: Submit request to Gutenberg Repo

**Comment by cuemarie** [comment]
Ah, actually, looks like this would be a great place to share these ideas: 

- https://github.com/WordPress/gutenberg/issues/54336

**Comment by eduardozulian** [comment]
Awesome! I added them to https://github.com/WordPress/gutenberg/issues/54336#issuecomment-1761595481 mostly as a +1 to the main idea. :)
