### ISSUE TITLE
Assembler: add zoom-out preview

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#82296]
# Description
* pbxlJb-4yn-p2#comment-3019
* Part of Assembler Walkthrough Sept 2023 Tasks  pbxlJb-4AT-p2

# Design
Here is a mockup.  Please check with  @lucasmendes-design for additional design details as needed. 

<img width="386" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/fc77ee33-5ad4-416e-a324-d6c780f5e7e6">

![image](https://github.com/Automattic/wp-calypso/assets/5665959/2af6b803-1379-4e00-a231-c1bd3eedc9c5)

# Dev Tasks
ToDo by Lego Devs
- [ ] Implement zoom UI control (probably for 50% and 100%)
- [ ] ....

@Automattic/lego

**Comment by lucasmendes-design** [comment]
The component for this feature: 

![image](https://github.com/Automattic/wp-calypso/assets/98343583/6d47cbfc-e575-4380-8511-d4c7e35dfc3b)


https://github.com/Automattic/wp-calypso/assets/98343583/d314e06b-1d2d-425e-a746-e3229b329369

**Comment by lucasmendes-design** [comment]
I also thought of something more fun as well, like a slider. 

![image](https://github.com/Automattic/wp-calypso/assets/98343583/dd734f62-11d2-4367-9945-9e8d4aeec21b)

![image](https://github.com/Automattic/wp-calypso/assets/98343583/8862cb29-33e5-437f-a99f-6fa3098f3717)

**Comment by lucasmendes-design** [comment]
Double-checking if you need something more here ?

**Comment by autumnfjeld** [comment]
@lucasmendes-design   @Automattic/lego Devs haven't started on this, but there is enough for them to assess your ideas, and ask further questions and give you feedback on which design is best.

**Comment by arthur791004** [comment]
Proposed https://github.com/Automattic/wp-calypso/pull/83034 to add the zoom-out preview, and here is a quick demo:

https://github.com/Automattic/wp-calypso/assets/13596067/8709b2d8-f26e-4a90-a20e-1529182906ae

@lucasmendes-design Does the behavior of the zoom-out look good?

**Comment by lucasmendes-design** [comment]
Amazing @arthur791004, I didn't know you would follow this direction. The behavior looks great. I'll share some suggestions to make this component amazing :) 

Figma link: Tv3pYqA3EcRfiXC31IxrXE-fi-2469:33385#585639702

Guidelines: 

<img width="876" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/b0b204d9-fd9e-45ba-85b0-70656a8eae0f">


### **Hover**
https://github.com/Automattic/wp-calypso/assets/98343583/0f6079fe-2d6e-4b5c-81e8-59e648729557

### **Focus**
https://github.com/Automattic/wp-calypso/assets/98343583/416e5d8d-95ae-4a6f-bd8f-ef4579022de1

**Comment by lucasmendes-design** [comment]
Not sure how difficult would be if the gray border followed the zoom action. For example, when the drawer is visible we reduce the size of the site preview. We would follow the same behaviour for the zoom component. Like the video below: 

https://github.com/Automattic/wp-calypso/assets/98343583/c067db08-575d-406c-8dbb-a9f228d54dbd

**Comment by miksansegundo** [comment]
@lucasmendes-design A use case for the zoom-out view, that was shared on the walkthrough call, is to show all patterns when selecting styles on the assembler.

This zoom-out could be done programmatically as in the editor when browsing styles:

![image](https://github.com/Automattic/wp-calypso/assets/1881481/67b5ad4a-5df7-456d-93ff-f20934b11fb4)

What do you think? I'm not aware if this case has been discussed. Here is a Gutenberg issue for tracking the [Zoomed Out View](https://github.com/WordPress/gutenberg/issues/50739).

Here is an example of the use case in the assembler:
<img width="1624" alt="Screenshot 2566-10-18 at 11 27 22" src="https://github.com/Automattic/wp-calypso/assets/1881481/adbc3380-e91b-484a-8f53-ca17541a7f65">

**Comment by arthur791004** [comment]
I think these two have their own pros and cons. The current one provides more flexibility and people can control when to zoom out and the ratio they want. But they might not be aware of this functionality. Whereas, the programmatical zoom-out makes people easier to preview styles on the whole page.

I'm unsure whether to combine these two. Maybe we can set the zoom-out ratio to 0.45 when people proceed to the styles step for the first time and never touch the slider of the zoom-out 🤔

**Comment by lucasmendes-design** [comment]
> A use case for the zoom-out view, that was shared on the walkthrough call, is to show all patterns when selecting styles on the assembler.

Not sure if this solution will work nicely with all screen sizes and different numbers of patterns. So, the one we're working on here is way more flexible. There is one detail that we need to check. When we zoom out the action bar should not reduce (or just a little). Otherwise, the component will be very small and confusing. See the Wix example below. 

> I'm unsure whether to combine these two.

We may, by default,  set an automatic zoom-out when users reach the style step but I won't bother with this right now. We can develop the component and check if users are interacting with this and then, we can see how to improve the component or add some additional logic to it. 

### **Wix example**
50% zoom out when adding sections. This zoom doesn't work pretty well for small screens and users will not see the whole page. 

https://github.com/Automattic/wp-calypso/assets/98343583/9bf2c402-1d1b-42d2-ba44-288575fdcab2

### **Canva example**
Here it works fine for everyone. 

https://github.com/Automattic/wp-calypso/assets/98343583/59e86ca1-c814-4e13-93dd-4c532bce5d8c

**Comment by arthur791004** [comment]
Closing it as it's completed.
