### ISSUE TITLE
Assembler: The shuffle button breaks when patterns are pre-selected

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#82326]
## Description

See p1695884293511659-slack-CRWCHQGUB, the shuffle button in the Assembler action bar doesn't work when the patterns are pre-selected via URL parameters. For instance: https://wordpress.com/setup/with-theme-assembler/patternAssembler?ref=calypshowcase&siteSlug=${SITE_SLUG}&screen=sections&screen_parameter=intro&pattern_ids=9754.

![Image](https://github.com/Automattic/wp-calypso/assets/797888/f30f410f-9432-4315-a374-d86a4146ed4e)

**Comment by karenroldan** [comment]
📌 ACTIONS
- Closed as no longer relevant (issue resolved by issue #82329)
