### ISSUE TITLE
Reader/Discover/First-Posts: Filter out posts from sites that haven't launched

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#82342]
We should make sure that we are only showing posts from sites that are launched. More info here: p1695909496261009-slack-C0Q664T29

**Comment by markbiek** [comment]
In the ES search, there are `blog.indexable`, `blog.presentable`, and `blog.private` properties. I wonder if any of those can be used to tell if a site is launched.

**Comment by sixhours** [comment]
> In the ES search, there are blog.indexable, blog.presentable, and blog.private properties. I wonder if any of those can be used to tell if a site is launched.

I would have thought the privacy settings would be enough, but a brand-new, unlaunched test site has `is_private: false` and `is_coming_soon: true`:

<img width="232" alt="Screenshot 2023-10-02 at 2 42 10 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/6584f8e0-951c-4aa4-8211-4f1ba0cbabe6">

Will dig into the other options and see if there's an ES equivalent to `is_coming_soon`.

That said, we should probably update the query to specifically exclude private sites, so I'll do that first.

**Comment by sixhours** [comment]
Started working on this in D123939-code

**Comment by sixhours** [comment]
Sites that are unlaunched will be *public* with a *true* `wpcom_public_coming_soon` site option. Asked if there's a way to filter/query for that in Slack: p1696274179982719-slack-C02JQ08G0

**Comment by sixhours** [comment]
D123939-code was deployed, so at least we won't get results from private sites. 

ES folks are going to add the `wpcom_public_coming_soon` option to the ES index after their meetup next week! p1696385013079829/1696274179.982719-slack-C02JQ08G0 Moving this back to the Current Sprint column in the meantime.

**Comment by markbiek** [comment]
Just wanted to note that `wpcom_public_coming_soon` hasn't been added to the index yet but it's on the schedule to be added soon.

p3QzjZ-1F0-p2

**Comment by markbiek** [comment]
That field is now present in ES and the first-posts query has been updated to use it:

D126763-code
