### ISSUE TITLE
Site Profiler: Remove check icons from the main card

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#82356]
I'd like to propose removing the icons from the main card. This is because the red icon with an 'x' has a negative association, and the checkmarks in the table should suffice to identify hosting or domain related to WordPress.com. Additionally, this will give us some extra room in the mobile view.

![image](https://github.com/Automattic/wp-calypso/assets/4933/77ea0ee5-10ba-46e9-9d90-12458a5d22de)

cc: @vishnugopal @bogiii @Automattic/caribou

**Comment by bogiii** [comment]
That's fine; I can do it.
@javierarce, to double-check, are we going to remove the green badge as well?

**Comment by javierarce** [comment]
Thanks, @bogiii!

> @javierarce, to double-check, are we going to remove the green badge as well?

Yes, those should go away too.
