### ISSUE TITLE
Bug: LiTS does not highlight categories selected in the more dropdown

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/wp-calypso#82389]
The Logged-in Theme Showcase does not highlight categories selected inside the `More` dropdown menu.

### Problem
When you select a category inside the more menu it doesn't get highlighted.

### What I was expecting
Selecting a category inside the more menu should highlight the category just like we are highlighting the categories from outside.

### Video reproducing the error

https://github.com/Automattic/wp-calypso/assets/1989914/6b50e1bd-2dc8-4ff3-833d-8aa0f9af2511

**Comment by BogdanUngureanu** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/84566
