### ISSUE TITLE
Newsletter Categories: Update copy in pre-publish panel

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#82383]
Update the copy in the pre-publish panel when using Newsletter Categories:

![Image](https://github.com/Automattic/wp-calypso/assets/528287/7d71ad1b-e3ba-4149-a966-42cc61d3c380)

"This post will be sent to everyone subscribed in the X, Y, Z categories". 

Only show categories that are actually newsletter categories.

**Comment by crisbusquets** [comment]
On it! 🚀

**Comment by crisbusquets** [comment]
Hi @Automattic/apex !

Here's the proposal (bottom row): hTkvvHDX8yafXQpycivyEX-fi-1026_30746

In case the Figma link doesn't work:

## Pre-publish panel

> Newsletter: Selected subscribers
> This post will be sent to everyone subscribed to **{Category 2}** (X subscribers).

Example:
> Newsletter: Selected subscribers
> This post will be sent to everyone subscribed to **Science fiction** (10 subscribers).

<img width="445" alt="Screenshot 2023-10-20 at 16 35 41" src="https://github.com/Automattic/wp-calypso/assets/25607244/cd2b7058-6f00-4171-8d01-cb5a3efeab47">


## Post-public panel

> Newsletter: Selected subscribers
> {post title, linked} was sent to everyone subscribed to **{Category 2}** (X subscribers).

Example:
> Newsletter: Selected subscribers
> Tenth Doctor was sent to everyone subscribed to **Science fiction** (10 subscribers).

<img width="422" alt="Screenshot 2023-10-20 at 16 36 03" src="https://github.com/Automattic/wp-calypso/assets/25607244/d117acea-d200-4bf4-a2d3-712b234c1fba">

**Comment by TimBroddin** [comment]
@crisbusquets Thanks for the details. I have some thoughts:

I think that when there's also a non-newsletter category selected, we need to add "and everyone subscribed to 'All Content' (X subscribers)". When only a non-newsletter category is selected we need to change this to "everyone subscribed to 'All Content' (X subscribers)". 

Should we also return a grand total? For example, if I publish a post in categories `Cars` and `Bikes`, there might be overlap, some `Cars` subscribers might also be `Bikes` subscribers. Telling them that This post will be sent to everyone subscribed to Cards (100 subscribers) and Bikes (50 subscribers), might give them the impression that 150 people will receive the mail, while the total amount might only be 100.

**Comment by crisbusquets** [comment]
> I think that when there's also a non-newsletter category selected, we need to add "and everyone subscribed to 'All Content' (X subscribers)". When only a non-newsletter category is selected we need to change this to "everyone subscribed to 'All Content' (X subscribers)".

💯 

> Should we also return a grand total? For example, if I publish a post in categories Cars and Bikes, there might be overlap, some Cars subscribers might also be Bikes subscribers. Telling them that This post will be sent to everyone subscribed to Cards (100 subscribers) and Bikes (50 subscribers), might give them the impression that 150 people will receive the mail, while the total amount might only be 100.

You're right. In that case, maybe it's better to return the grand total as you suggested. Too many details will confuse site owners.

**Comment by TimBroddin** [comment]
> Too many details will confuse site owners.

I agree. As a site owner you probably just want to know the number of subscribers your post will go out to. 

I'll start dividing this in tasks so we can start working on this.

**Comment by phcp** [comment]
Closed by https://github.com/Automattic/jetpack/pull/34267
