### ISSUE TITLE
Plans grid: tooltip over an unavailable domain is flashing quickly

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#82386]
#### Steps to reproduce

1. Create a new site, and choose to connect an existing domain, registered elsewhere
2. You end up on the `/start/plans` page, seeing the plans grid
3. The infobox for the Free plan tells you that the custom domain is not available there (it's striked out, and only the .wordpress.com subdomain is available. See the screen captures below
4. Hover over the domain feature item
5. The tooltip (domain is not included) will start flashing quickly

#### Screenshot / Video

https://github.com/Automattic/wp-calypso/assets/664258/5804791a-0437-48c7-963a-3eb4ddbdbb46

I think the bug is caused by the fact that the feature item element has a fixed height, and that the striked out part overflows to the top. When I hover on the striked out part, the tooltip will appear because I `mouseenter`-ed into the tooltip container element. But then the tooltip will be aligned over the fixed height box, which means that the tooltip will appear just under the mouse cursor. That means `mouseleave`, and the tooltip disappears again. After it disappears, I will `mouseenter` the tooltip container again, and so on, ad infinitum. The element layout is visible in this screenshot:

<img width="626" alt="Screenshot 2023-09-29 at 10 30 52" src="https://github.com/Automattic/wp-calypso/assets/664258/ec89257a-4c4c-4a90-9940-d13c43254cc0">

Cc @jdc91 and @niranjan-uma-shankar who worked on this in the recent months.

**Comment by ddc22** [comment]
@southp how can we prioritize this bug?

**Comment by katinthehatsite** [comment]
I tested this flow but I am not seeing anymore `Start with Free` when I create a new site and choose to connect a domain: 

<img width="1111" alt="Captura de pantalla 2024-09-03 a las 11 46 31 a  m" src="https://github.com/user-attachments/assets/f2cbbe93-8140-4405-88c0-ea83dba693a5">

It seems that we changed our plans grid so the issue can't be reproduced anymore.
