### ISSUE TITLE
Assembler: Site logo is not shown in header patterns

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#82392]
### Description

When a site already has logo, and the user enters the Assembler flow, then see the header patterns, the site logo is not shown in the patterns where it should be there; a placeholder logo is shown instead.

---

Example: site logo is there:

<img width="271" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/b800575e-2f62-4afe-912e-edeb2acb8bc1">

---

But not in the Assembler:

<img width="1268" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/2c24cae7-9b01-4284-bbc8-7ee001f22f2a">

---

### Steps to reproduce

1. Add a site logo in https://wordpress.com/settings/general/<siteSlug>
2. Go to Appearance -> Themes -> click "Get started" on the Design your Own card
3. Click on the header section
4. Observe that the logo is not shown.

@Automattic/lego

**Comment by autumnfjeld** [comment]
I double checked this and on some sites this works for me.  On others I did not see the logo that I knew existed on the site.  

It works with my makeitsparkly site:
<img width="707" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/9179d76e-0cc9-44bb-9230-d621c29fbde4">

**Comment by arthur791004** [comment]
> Example: site logo is there:
>
> <img width="271" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/b800575e-2f62-4afe-912e-edeb2acb8bc1">

This is not the site logo...it's the site icon. You have to go to the site editor, and upload the site logo via the Site Logo block 🥲

![image](https://github.com/Automattic/wp-calypso/assets/13596067/00ebc34e-e08c-4bf4-9abb-56ceeba5a7b5)

**Comment by autumnfjeld** [comment]
Confusion in terminology.  There isn't a bug, the site logo shows up. :)
