### ISSUE TITLE
[Suggestion] Site Profiler: The Page Feels a Bit Empty for Logged-In Users Because There's No Content in the Footer

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#82399]
#### Steps to reproduce

1. Make sure you are logged in.
2. Starting at URL: https://wpcalypso.wordpress.com/site-profiler.
3. Observe the footer content with a grey background. 

#### What I expected

Since there is a grey background separating the layout, I expected some additional content in that space. This kind of design typically indicates a placeholder for distinct content, guiding users' attention to it. 

#### What happened instead

I initially thought the page was still loading and I scrolled, but that was the entire page already. This can lead to confusion and might give users the impression that some parts of the site are not loading as intended. 

#### Browser / OS version

Chrome Version 116

#### Screenshot / Video

**Logged In**

https://d.pr/i/ElIx59

**Logged Out**

https://d.pr/i/WExATd

#### Context / Source

CfT https://wp.me/pdtkmj-1Rk

**Comment by javierarce** [comment]
I agree, we should show the navigation and the footer to everybody.

**Comment by vishnugopal** [comment]
@javierarce This is not the behaviour of any other logged in page as far as I can see, for example: https://wordpress.com/theme/awburn/

**Comment by vishnugopal** [comment]
Alternate proposal: do something with the grayspace like this: https://github.com/Automattic/wp-calypso/issues/82443

**Comment by javierarce** [comment]
> @javierarce This is not the behaviour of any other logged in page as far as I can see, for example:

Oh, my confusion comes because I thought we were going to treat this page as any other landing page and always show the navigation and footer.

**Comment by vishnugopal** [comment]
> because I thought we were going to treat this page as any other landing page 

I think because of the tech stack used here (we discussed [tradeoffs here](https://wp.me/pcmemI-2nL)) this is harder to achieve. If you feel we should do it, I'll consider this a task for i2 now.

**Comment by vishnugopal** [comment]
Another alternative suggestion here: LhioRMwirFL3WNKErGOzvy-fi-807:13603#567377511

**Comment by javierarce** [comment]
If I follow the link I see this 🤔  <img width="598" alt="Screenshot 2023-10-04 at 11 19 57" src="https://github.com/Automattic/wp-calypso/assets/4933/62b6782e-ff16-4d6f-b7ed-64252cf898e7">

> I think because of the tech stack used here (we discussed pcmemI-2nL-p2) this is harder to achieve. If you feel we should do it, I'll consider this a task for i2 now.

I don't have a strong opinion about that, so I think we could keep this design and reopen the issue if more people raise concerns.

**Comment by vishnugopal** [comment]
> If I follow the link I see this 

Sorry if I wasn't clear. It was to solve the problem of the "page feeling empty." i.e. instead of the footer we have more content on the page as described.

**Comment by bogiii** [comment]
I'll try to add a footer component here for the logged-in users as well.
