### ISSUE TITLE
[Suggestion] Site Profiler: Differentiate WordPress.com hosting between Simple, Atomic, Pressable...

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#82396]
Context: pdtkmj-1Rk-p2#comment-3349

One thing that it would be useful to differentiate is the WordPress.com hosting: Simple, WP.com on Atomic, Pressable or another WP Cloud host.

**Comment by vishnugopal** [comment]
Think this is a good idea.

For Pressable:

```
$is_pressable = (bool) get_option( 'jetpack_constant_IS_PRESSABLE' );
```

should work.

For Simple/Atomic:

```
$is_atomic = is_blog_atomic( get_blog_details( $site_id ) );
```

> or another WP Cloud host.

I don't think there's any other host right now.

**Comment by zaerl** [comment]
Already on review: https://github.com/Automattic/wp-calypso/pull/82508

**Comment by zaerl** [comment]
Unfortunately the `get_option` don't work.
> Think this is a good idea.
> 
> For Pressable:
> 
> ```
> $is_pressable = (bool) get_option( 'jetpack_constant_IS_PRESSABLE' );
> ```
> 
> should work.
> 
> For Simple/Atomic:
> 
> ```
> $is_atomic = is_blog_atomic( get_blog_details( $site_id ) );
> ```
> 
> > or another WP Cloud host.
> 
> I don't think there's any other host right now.

**Comment by ouikhuan** [comment]
Yeah, also not all the Pressable is linked with Jetpack, so checking `jetpack_constant_IS_PRESSABLE`  won't cover all the cases. 

Another approach is to check nameservers and A records, I had a look but some IP addresses are listed under Automattic even it's a Pressable IP, so probably the best way to detect a Pressable hosting is to check the `host_header` from a site like the changes @zaerl proposed here.
