### ISSUE TITLE
Plans 2023: Migrate grid-plans metadata compilation to separate hooks/selectors

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#82409]
### What

The calls in [plans-features-main](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plans-features-main/index.tsx) used to compile the grid plans for use in the grid components can migrate into separate/individual hooks (and ported into the plans-grid package / and later into data-stores from there).

### Why

There is far too much "setup" (lots of chained API/hook calls) happening in [plans-features-main](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plans-features-main/index.tsx) to put together the data for feeding the grid. Not reusable and will inevitably be a bottleneck once things are ported to a package and we attempt to reuse outside of [plans-features-main](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plans-features-main/index.tsx). Most of these calls are now also being optimized with memorization in https://github.com/Automattic/wp-calypso/pull/82403, and they are best be moved to own files to reduce some of the clutter (irrespective of reuse).

### How

These components at minimum should migrate to separate hooks (right next to `use-grid-plans`):

- gridPlanForSpotlight
- gridPlansForFeaturesGrid
- gridPlansForComparisonGrid
- planFeaturesForFeaturesGrid
- planFeaturesForComparisonGrid

It shouldn't be a big deal.

**Comment by chriskmnds** [comment]
Closing this in favour of https://github.com/Automattic/wp-calypso/issues/86642

@southp it looks like you self-assigned this. Are you still interested? I was thinking something for @oswian to deep dive into with me. We'll need this refactor before we experiment with external package use.

**Comment by southp** [comment]
@chriskmnds Sorry for occupying this issue for 2 months without any visible output. Let's follow your plan, integrating this as part of #86642 and let @oswian take lead from here :)
