### ISSUE TITLE
[UI] Site Profiler: add special descriptions for WordPress sites

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#82413]
If a site is not hosted with us but runs on WordPress, we'd like to display a different description on the main card of the profiler and include a kind gesture for the owner of the WordPress site.

The new description is: 

```The owner of this site has great taste—this site runs on WordPress!```

This description appears in two cases: 

| Hosting | Domain | Description | Action | CTA |
|:-------|:-------|:-------|:-------|:-------|
| Other provider | WordPress.com | The owner of this site has great taste—this site runs on WordPress! | If you own this site, consider hosting it with WordPress.com and benefiting from one of the best platforms in the world. | Migrate site |
| Other provider | Other provider | The owner of this site has great taste—this site runs on WordPress! | If you are the owner, bring your site and domain to WordPress.com and benefit from one of the best hosting platforms in the world. | Migrate site |

For reference, here's a table with all the variations: https://www.figma.com/file/LhioRMwirFL3WNKErGOzvy/Site-Profiler?type=design&node-id=1240-13613&mode=design&t=7ZAxh3jYMotvqLzq-4

**Comment by ouikhuan** [comment]
Handling this in #82439

**Comment by ouikhuan** [comment]
Closing this issue as it's done in the PR above.
