### ISSUE TITLE
Jetpack Atomic E2E: Figure out a way to handle database updates

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#82412]
### Details

For two of the atomic staging sites: `wp-beta` and `wp-previous`, because we are decoupled from the standard WordPress version, when there are upgrades, there is a database update required.

Unfortunately, this causes a wave of e2e permafails as the editor loads this message:
![Screenshot 2023-09-29 at 10 16 58 AM](https://github.com/Automattic/wp-calypso/assets/26772342/b99579f4-6b9c-4205-a705-378013662400)

We need to find a way to handle this programmatically without manual intervention and hopefully without any e2e failures

### Checklist

- [ ]
- [ ]

**Comment by dpasque** [comment]
Honestly, this is honestly so fast that we could even just have the tests themselves do this via the UI if they hit it. Like a promise race that handles hitting this screen. 🤷 That's **very** easy and I think will work for us in an automated way.

**Comment by worldomonation** [comment]
I haven't actually clicked on the button. It seems like you have; how long did the process take? 

It seems like there isn't really a good way to handle this other than checking that this screen does not appear at the launch of every test. Frankly, that doesn't sound very pleasant to me but because we're decoupled from the actual codebase I don't see a better way.

**Comment by dpasque** [comment]
> It seems like you have; how long did the process take?

Like 2 seconds, fortunately! 😄 

> It seems like there isn't really a good way to handle this other than checking that this screen does not appear at the launch of every test. Frankly, that doesn't sound very pleasant to me but because we're decoupled from the actual codebase I don't see a better way.

Agreed... But the other option is somehow having an async job kick off a remote process on the specific atomic machines at the right time, which might get a bit rowdy haha 😅 I think we should give this a whirl from the client, and if it sucks or feels gross, we can rig something on the backend. 👍 🙂

**Comment by dpasque** [comment]
Dropping some DOM details for future fix. That button is a `link` with name `Update WordPress Database`. The header shown is also a true `header`.

**Comment by worldomonation** [comment]
My idea: add something in `ElementHelper` or similar a new async function that is guarded by `envVariable.ATOMIC_VARIATOIN` to look for the text you noted above.

and then, call the function as part of `EditorPage.waitUntilLoaded`. That way we don't have to change all the Editor-related specs.
