### ISSUE TITLE
Delete/confirm button for pending reader subscriptions not working 

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/wp-calypso#82429]
### Quick summary

When visiting https://wordpress.com/read/subscriptions/pending, I try to click on the Delete or Confirm button under a pending subscription, but there is no response. 

### Steps to reproduce

1. Start at https://wordpress.com/read/subscriptions/pending
2. Click delete or confirm 

### What you expected to happen

The site should be deleted or confirmed. 

### What actually happened

Nothing. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Reported in this ticket: 6970687-zd-a8c
I was able to reproduce on my own account of `foleynotrose`

**Comment by cuemarie** [comment]
@Automattic/apex I see in pdDOJh-2qy-p2 that y'all were recently working on the Pending page of the Reader, so pinging you to start.

I can't actually figure out how to get a Pending Subscription set up to test this 🤔 I tried adding my account as a subscriber to another site as well as following a new site via the reader.  

📌 ACTIONS
- Lowered priority to Normal

**Comment by phcp** [comment]
I reproduced the same issue here, I'll work on a fix for this. Thank you for reporting @foleynotrose @cuemarie!

**Comment by phcp** [comment]
@foleynotrose @cuemarie It should be fixed with the PR we just merged.
