### ISSUE TITLE
Domains: /domains not loading in Safari 16.x

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#82430]
### Quick summary

Accessing My Sites > Domains on Safari 16.x is leading to an error page:

https://github.com/Automattic/wp-calypso/assets/14153300/d5926c90-376f-458c-bebb-b1bd16599700

![cleanshot_2023-10-01_at_16 12 40_2x](https://github.com/Automattic/wp-calypso/assets/14153300/3eaa97d3-a82a-4c7e-a1eb-8ec517c977f0)

Slack: p1696172580938699-slack-C02FMH4G8

### Steps to reproduce

1. In Safari 16, navigate to My Site > Upgrades > Domains

### What you expected to happen

The page should load a list of domains

### What actually happened

The page loads blank first, and then shows a "We're sorry but an unexpected error has occurred issue"

### Impact

Some (< 50%)

### Available workarounds?

Yes, switching to another browser or updating Safari to 17

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Not reproducible on Chrome 117 and Safari 17 

Reproducible on Safari 16 and 16.1

**Comment by liviopv** [comment]
- [ ] p1696002493690919-slack-C0761SX4K
- [ ] 7107937-zd-a8c

**Comment by delputnam** [comment]
I think this is related to the `<!` assertion in the regex added in https://github.com/Automattic/wp-calypso/pull/81460

In the line: `const CAPTURE_SUBDOMAIN_RGX = /^(?!-)[a-zA-Z0-9-]{0,63}(?<!-)$/i;`

Maybe related to: https://bugs.webkit.org/show_bug.cgi?id=174931

**Comment by delputnam** [comment]
Potential fix here: https://github.com/Automattic/wp-calypso/pull/82432

But I can't test it since I don't have access to Safari 16.1 and I can't reproduce the issue in Safari 17.

**Comment by klimeryk** [comment]
I've tried reproducing it, but cannot in Safari 16.6. So they probably fixed it in a version between 16.1 and 16.6.

**Comment by delputnam** [comment]
It looks like the issue in webkit was fixed between Safari 16.2 and 16.3

**Comment by delputnam** [comment]
I've deployed the PR, but it would be great if someone who has access to Safari 16.1 could confirm that the PR actually fixes the original issue.

**Comment by delputnam** [comment]
@liviopv Confirmed that this fix allows the page to load using Safari 16.1. 🙏
