### ISSUE TITLE
[Suggestion] Redirect Site Profiler URLs to main URL

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#82441]
URLs like `http://calypso.localhost:3000/site-profiler/__string__` do open an empty page with broken controls. They should redirect to `http://calypso.localhost:3000/site-profiler?domain:domain` counterpart.

**Comment by vishnugopal** [comment]
@bogiii Are we planning to make this part of the redirect when we post a request to systems?

**Comment by bogiii** [comment]
@vishnugopal, this is a simple configuration in the Calypso.
We just need to have the same route resolver for the `/site-profiler` and /site-profiler/*` routes.

The system request would be whitelisting the `site-profiler` base route.
