### ISSUE TITLE
Refreshed Fullpost design tweak: add space above more/comment lines.

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8244]
One of the most consistent pieces of feedback we've received from the fullpost call for testing is that the bottom of the post feels too cramped. It was my hope that this was one of those "they'll get used to it" kind of things, but it may not be. So I'd like to suggest a tweak.

For the lines in the More and Comment sections, we had been using 20px of whitespace above and below the line to mark the separation. I'd like to suggest we change this to 40px above the line and 20px below it. (Note this only goes for the more/comment blocks. The space below the main post's footer links is already 40px and should not change.)

So this:
![space-before](https://cloud.githubusercontent.com/assets/24388/18885532/e28a7308-84a0-11e6-94c4-38ce4b0daab4.jpg)

Would change to this:
![space-after](https://cloud.githubusercontent.com/assets/24388/18885535/e81851b4-84a0-11e6-9479-87b309dcc3fb.jpg)

Why not 30px on both sides? Because the line is visually part of the heading, so it makes sense to keep it close to the header text. Putting the space above the line says "that section is over, now we're in a new one."

I think this might give the design a little more breathing room and better define each block as its own thing. It's worth a test, at least. What do you think, @jancavan?

**Comment by jancavan** [comment]
Yes, more space is definitely better visually. Let me try it out to see how it looks.
