### ISSUE TITLE
Stats: Consolidate stateful purchase page without passing force redirect params

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#82444]
We can consolidate state checks in the Stats purchase page to determine showing which purchase screen without passing force redirect params `productType`.

After implementing stateful checks, we can also address the [potential issue](https://github.com/Automattic/wp-calypso/issues/82181#issuecomment-1742563874) of [passing](https://github.com/Automattic/jetpack/pull/33297) `productType=personal` to commercial sites, which would show the inappropriate purchase screen.

cc @kangzj @grzegorz-cp

**Comment by kangzj** [comment]
I'll close this for now because I think it currently works and the gain wouldn't very much match the investment here.
