### ISSUE TITLE
[Navigation Block][iPad]Menu remains open even if another is opened 

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/wp-calypso#82478]
### Quick summary

The submenu remains open even when another submenu is opened on iPad.

https://github.com/Automattic/wp-calypso/assets/78526686/1c560da5-1891-4742-973b-bcaf1de566cc

[Test on Browserstack]

### Steps to reproduce

1. Go to Appearance → Editor → Navigation
2. Modify the Navigation so that each menu item has sub-items
3. Preview page on iPad
4. Click on dropdown arrow
5. Click on another dropdown arrow

### What you expected to happen

The previous dropdown that is open should close

### What actually happened

The dropdown remains open

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

7071962-zen

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicate
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
I'm able to replicate this using my (Firefox) browser's responsive tools across Simple, Atomic and simple Self-Hosted test sites. It appears to get worse the more I scroll/use the menu items on the page - below is a comparison of all 3 environments:

**Simple , Atomic, Self-Hosted**

https://github.com/Automattic/wp-calypso/assets/27249804/e9d6b27d-295a-472f-8840-1ba2104c9d16

**Simple**

Gutenberg: v16.6.0
Editing Toolkit: v3.80059
WP AMP: 2.0.5
Theme: TwentyTwenty-Three

**Atomic**

WP 6.3.1
Gutenberg: v16.6.0
Editing Toolkit: v3.80059
Theme: TwentyTwenty-Three

**Self-Hosted**

WP 6.3.1
Gutenberg: v16.7.0
Theme: TwentyTwenty-Three

📌 ACTIONS
- Lowered Priority to Normal
- Reported in Gutenberg: https://github.com/WordPress/gutenberg/issues/54991

**Comment by cuemarie** [comment]
https://github.com/WordPress/gutenberg/pull/55198 aims to fix this in GB 16.9
