### ISSUE TITLE
Reader/New Blogs: New class to query for new blogs

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#82470]
Let's make a new class similar to `class.first-posts.php` (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Ssvefg%2Qcbfgf%2Spynff.svefg%2Qcbfgf.cuc%3Se%3Qppps4396%2312-og) which gets blog ids for blogs created in the last 5 days that have first posts.

**Comment by andres-blanco** [comment]
D123886-code
