### ISSUE TITLE
"Learn More" link on the Jetpack's Image Accelerator tooltip is broken

### ISSUE THREAD

**Issue by fabiocchetti** [Automattic/wp-calypso#82480]
### Quick summary

When exploring the Jetpack dashboard on one of my test websites I ran into a support link redirecting to a non-existing page.

<img width="537" alt="Screenshot 2023-10-02 at 17 05 26" src="https://github.com/Automattic/wp-calypso/assets/24655386/8c93c75b-fd2c-4bb8-9ad4-2530aca7a2a4">

<img width="568" alt="Screenshot 2023-10-02 at 17 05 42" src="https://github.com/Automattic/wp-calypso/assets/24655386/d374ef36-a3ee-4329-87a6-b5ef99fe85ff">

### Steps to reproduce

1. On a website hosted on WordPress.com, click on "Jetpack" from the sidebar.
2. Scroll down to the "Image Accelerator" paragraph.
3. Click on the "i" (information) box, and then "Learn more" on the tooltip that just appeared.
4. You should be redirected to `https://jetpack.com/support/photon` which returns 404.

### What you expected to happen

The support page should have been loaded.

### What actually happened

Clicking on "Learn more" redirected me to a non-existing page.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described; the `Learn More` link is `https://jetpack.com/redirect/?source=jetpack-support-photon&site=SITE_ADDRESS`, which lands on a Page Not Found page.

📌 ACTIONS
- Triaged
- CC @jeherve

**Comment by jeherve** [comment]
This is also tracked in 8552-gh-jpop-issues. It seems to be an overall issue with redirects on jetpack.com

**Comment by jeherve** [comment]
This should now be fixed.
