### ISSUE TITLE
Authentication: Forgot Password screen is still using the older, blue-centric theme.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82504]
### Quick summary

The Forgot Password screen (https://wordpress.com/wp-login.php?action=lostpassword) is still using the older blue theme.

There is no user impact, but as we have moved away from the blue-centric theme, this reflects poorly on us.

### Steps to reproduce

1. navigate to `/log-in`.
2. click on `Lost your password?` option.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/e12dbf6c-afc8-4107-8acb-03a5f0eb26a4)

### What you expected to happen

Most, if not all of our public pages are updated to the black-on-white theme.

### What actually happened

The older blue-centric theme is still used.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested in Firefox – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO

![Markup on 2023-10-03 at 14:40:38](https://github.com/Automattic/wp-calypso/assets/27249804/401206a6-9375-4bc6-9286-a29d306a5588)

📌 ACTIONS
- Triaged

**Comment by gikaragia** [comment]
This is now done. 
![Screenshot 2024-09-06 at 13 40 14](https://github.com/user-attachments/assets/2abedafc-b26b-4d87-9c72-a1e854562e57)
