### ISSUE TITLE
Launchpad: only allow scroll interaction with site preview pane.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82500]
### Quick summary

https://github.com/Automattic/wp-calypso/issues/66574 specified that Launchpad should only allow scroll interaction with the site preview pane, but as of Calypso `62fa21a88197f66d8a33f22c419e0c4bac9239b8` (2023/10/03) the preview can still be interacted with.

### Steps to reproduce

prerequisite. if required, create a site. Otherwise, a pre-launch site works.

1. trigger launchpad by activating the site.
2. when the preview pane loads, click on any hyperlink in the preview.

https://github.com/Automattic/wp-calypso/assets/6549265/8b578d78-5822-42d7-b824-1330d6a898d2

### What you expected to happen

Only scroll interaction is permitted (ie. click passes through).

### What actually happened

User is able to click and navigate in the preview.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/82502
