### ISSUE TITLE
[Bug] Site Profiler: wrong Pressable header informations

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#82518]
Context: p1696328001372009-slack-C011A0LL8RL
See: https://wpcalypso.wordpress.com/site-profiler?domain=cagrimmett.com

The phrases:
> This site is hosted on WordPress.com but the domain is registered elsewhere.

and:

> If you own this domain, consider transferring it to WordPress.com and benefiting from the best-performing, most reliable registrar in business.

are wrong for Pressable sites. Because:

1. A Pressable site is hosted on Pressable, like specified in the "Hosting information" section.
2. We already host the site and so probably we don't want to encourage a user to switch.

**Comment by vishnugopal** [comment]
> This site is hosted on WordPress.com but the domain is registered elsewhere.

can be changed to:

> This site is hosted on Pressable but the domain is registered elsewhere.

The other one can remain as such.
