### ISSUE TITLE
Stats: Fix encoding issue with URLs on Insights page

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#82510]
Reported via support. — pejTkB-VK-p2

Some of the URLs surfaced on the Stats → Insights page can be wrongly URL-encoded causing the links to not work as expected.

<img width="1160" alt="SCR-20231003-posu" src="https://github.com/Automattic/wp-calypso/assets/40267301/e5e3552a-d454-42dd-92c4-a710ac5a4a00">

Steps to reproduce involve private customer data so see the linked post above for that.

**Comment by a8ck3n** [comment]
Noting that we shipped a client-side fix for this so it should no longer be an issue on the **Stats → Insights** page. We still need to address things on the server side per the comments on the linked P2 post.

**Comment by a8ck3n** [comment]
API side has been updated and client-side fix has been removed. Marking this as done now.

**Comment by jsnmoon** [comment]
Could we mention the differential patch here for future reference? Thank you!

**Comment by a8ck3n** [comment]
> Could we mention the differential patch here for future reference? Thank you!

Sorry about that. I noted it in the last PR but not here. It's D124317-code.
