### ISSUE TITLE
Purchases: Canceling/refunding a Jetpack plan uses vague language

### ISSUE THREAD

**Issue by kraftbj** [Automattic/wp-calypso#8253]
When canceling/refunding a Jetpack plan, the language sounds like the same as a wp.com plan:

![screen shot 2016-09-27 at 15 40 37](https://cloud.githubusercontent.com/assets/88897/18891068/4dcf552a-84c9-11e6-9ce8-16132ed84846.png)

"Custom changes" is vague and unclear since Jetpack doesn't add any custom changes and, even i we did, isn't clear on what they may be.

**Comment by fabianapsimoes** [comment]
@kraftbj I'm not very familiar with the features in Jetpack plans. Could you suggest an alternative to the current copy?

**Comment by kraftbj** [comment]
Something like:

>Are you sure you want to cancel and remove premium from [url]? All plan features—spam filtering, backups, and security screening—will be removed from your site....

I'll ask the Growth folks to chime in too since they're in a better position to keep us on message.

**Comment by rickybanister** [comment]
@kraftbj your suggestion sounds perfect. 

The language you discovered _is_ the wp.com language, we share all the plans code and missed this.
