### ISSUE TITLE
Advanced SEO: site name vs. site title

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#8254]
On the SEO page, we display `Site Name`, but in General settings we use `Site Title`.

![screen shot 2016-09-27 at 3 54 08 pm](https://cloud.githubusercontent.com/assets/618551/18891417/c31a72e6-84ca-11e6-9db6-1424a1cdf87d.png)

![screen shot 2016-09-27 at 3 55 31 pm](https://cloud.githubusercontent.com/assets/618551/18891438/db8ba426-84ca-11e6-8f50-c4d48f07071c.png)

**Comment by dmsnell** [comment]
@drw158 there was a reason we did this and I'm trying to remember why. Maybe it was because the site name is static whereas the title was seen as dynamic and confusing (I thought we were setting the site title _here_)

**Comment by roundhill** [comment]
Revisiting this! `Site Title` seems to make sense to me, since you are adding the title that you set in the `General` tab.
