### ISSUE TITLE
Style variations visible on retired themes

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#82543]
#### Steps to reproduce

1. Go to https://wordpress.com/theme/awburn
2. Note how the theme is retired

#### What I expected

The style variations to be hidden, since it's a retired theme.

#### What happened instead

The style variations are visible.

#### Screenshot / Video

<img width="1840" alt="Screenshot 2023-10-03 at 19 39 33" src="https://github.com/Automattic/wp-calypso/assets/1233880/4e9aa5f1-b845-4b75-b918-a0ae9bf6dee9">

**Comment by BogdanUngureanu** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/84138
