### ISSUE TITLE
Republicize: improve disabled state design

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#8256]
Current:

![screen shot 2016-09-27 at 3 39 08 pm](https://cloud.githubusercontent.com/assets/618551/18892729/486b8750-84d0-11e6-8b35-3a89348b3f7c.png)

The design here can be improved
1. The error should be a notice component.
2. Copy should have a CTA.

Suggestions:

`Publicize is disabled on this site.` `Settings`

`Publicize is disabled on this site.` `Enable`

@artpi

**Comment by artpi** [comment]
Heads up: https://github.com/Automattic/wp-calypso/issues/8299

**Comment by artpi** [comment]
It would be also good to handle when no connection is active:
![screen shot 2016-10-06 at 16 19 13 pm](https://cloud.githubusercontent.com/assets/3775068/19156041/cc9a3622-8be0-11e6-8c9e-e4a9c72d3c4f.png)

**Comment by drw158** [comment]
Is is "disabled" because it is a private site? Perhaps the whole icon should be hidden if it is a private site.

**Comment by drw158** [comment]
Design for no connected accounts. Also can be used for any sort of error.

![screen shot 2016-11-08 at 2 15 45 pm](https://cloud.githubusercontent.com/assets/618551/20115483/0327a084-a5be-11e6-9cd1-a7e8692c0f33.png)
