### ISSUE TITLE
Invite: Social First signup that shows when accepting an invite lacks the pretty formatting present elsewhere.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82560]
### Quick summary

When accepting a site invite from an email, a Social First version of the signup page that's missing a bunch of formatting and icons loads.

Additionally, the Social First version of the `/accept-invite` endpoint does not have feature parity with the previous version of the screen, as it lacks the link to direct users who already have an account to log in.

Current (as of 4995610c0b21a8993e20a30b6518025ab0f29f8b)
![image](https://github.com/Automattic/wp-calypso/assets/6549265/2e2e4a7a-58af-49d8-9e29-3659119f4aef)

Previous (rev. aea8dc9a549651b9831eceb950396fd2dc7b138b)
![image](https://github.com/Automattic/wp-calypso/assets/6549265/3d13a327-6f74-4456-a7d1-03a479f62176)

### Steps to reproduce

1. create a site.
2. invite a user, named `user B`.
3. accept the invite as `user B` by clicking on the link in the email.

### What you expected to happen

The screen that loads `/accept-invite` should have nice formatting of the Social First signup that loads elsewhere.

The screen is lacking the previously present link for users that have an account with WordPress.com (`Already have a WordPress.com account? Log in now.`)

### What actually happened

The screen that loads is not conformant to the Social First signup screens implemented in https://github.com/Automattic/wp-calypso/pull/82481.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by worldomonation** [comment]
@escapemanuele Something I noticed while running through a CfT that I think you might be interested in.

I tried to summarize it best I could, but there are two problems described here. I am happy to split it out if you'd like.

1. `/accept-invite` endpoint doesn't render the visually rich version of the Social First signup screen.
2. The current version of `/accept-invite` is (perhaps intentionally) missing the link at the bottom of the form directing existing WordPress.com users to log in.

**Comment by escapemanuele** [comment]
I don't think we need to split it out 👍 
We'll work on this today:
1. Fix the CSS
2. We could maybe re-add back the link at the bottom for `/accept-invite`

**Comment by escapemanuele** [comment]
@renancarvalho, could you take a look at the CSS of this page?

**Comment by renancarvalho** [comment]
On it, will come up with a PR soon and keep this issue updated 👍

**Comment by davemart-in** [comment]
Looks to be fixed in https://github.com/Automattic/wp-calypso/pull/82602
