### ISSUE TITLE
User Content Link Tracking: track the links generated by the email version of some blocks

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#82583]
Some blocks render differently in the emails than in the blogs. The Vote and the Poll blocks are good examples of this. For example, if you put a Vote block in a post and a subscriber receives an email with the post content, this is how the Vote blog is going to be shown in the email:

![Image](https://github.com/Automattic/wp-calypso/assets/3832570/cccf186f-13d7-41d8-9cd9-ed727e8c5988)

These kinds of links are not tracked at the moment, but there is value for the post's author in knowing whether those links make the subscriber visit the site.

We need to track those links as if they were user content links.

More context here: pdDOJh-2wz-p2

**Comment by yansern** [comment]
Fixed by D124600-code
