### ISSUE TITLE
User Content Link Tracking: fix the geolocation is wrong

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#82586]
The geolocation in the stats for user content links is doing weird things. Example: I clicked from Spain 🇪🇸 , but the country stats showed the UK 🇬🇧 . Then, the clicks are done in the US 🇺🇸 (?).

We need to investigate why and fix it.

**Comment by yansern** [comment]
Addressed here. D124541-code

**Comment by yansern** [comment]
More explanation here: p1696586970605079-slack-C02TCEHP3HA
