### ISSUE TITLE
Subscription Management: Email Subscriptions Landing Page Flow

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#82599]
The plan is to unify Subscription Management portals due to security reasons.

**P2**: pdDOJh-2qY-p2

- [x] Map the flow
- [x] Update design for Email Subscriptions page and the "Your subscription details" email
- [x] Check copies

**Comment by crisbusquets** [comment]
@Automattic/apex  here's the Figma file with the Current flow vs the Proposal, based on what we discussed last week during our design sync.

Can you please check it to make sure it's OK, so I can review copies with Michael/Francisco?

Link: pS3hHF3lIosnX0Mgc8WtYV-fi-82_12218

Thank you!

**Comment by TimBroddin** [comment]
@cristelrossignol can this be marked as done with the new email to wpcom migration in place?
