### ISSUE TITLE
Stats: External links to images in gallery produce redirect error

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#826]
In the Stats we show viewed for image gallery links. For example if you had an image name "example-image" We should show this in the stats:
![screenshot_25-11-2015-15 45 56](https://cloud.githubusercontent.com/assets/150348/11411974/aacd2caa-938b-11e5-8458-19cc4977599a.png)

If you click on "Example Image" external link you are taken to:
https://example.wordpress.com/post/example-image/#main
And see a redirect error:
![screenshot_25-11-2015-17 04 55](https://cloud.githubusercontent.com/assets/150348/11412843/ad41244a-9396-11e5-95d2-4f09cebbbef1.png)

This is because the image file is actually at:
https://example.wordpress.com/post/#jp-carousel-1234

**Comment by lancewillett** [comment]
I think both link **should** work — the `/post_slug/image_slug/#main` and the direct link to the Carousel.

Feel free to re-open if you see this happen again — I couldn't repeat it.
