### ISSUE TITLE
Settings: Pointers overlay media modal

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#82609]
### Quick summary

On a new site (possibly with a new account), the pointers to fill out site title/description and save changes are visible on top of the media modal.

![image](https://github.com/Automattic/wp-calypso/assets/1398304/d9728026-03f6-4021-b72f-a59104fc497a)

<img width="992" alt="Screenshot 2023-10-04 at 11 58 35 AM" src="https://github.com/Automattic/wp-calypso/assets/1398304/00d30d3e-8d08-4d0f-b910-93b1c81d3350">

### Steps to reproduce

1. Register a new account and create a site.
2. Go to Settings General.
3. Try to upload a site icon.

### What you expected to happen

See screenshots.

### What actually happened

For the media modal to be fully visible.

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by DustyReagan** [comment]
I'm having trouble reproducing this. What method/flow did you use to create the new site?

**Comment by obenland** [comment]
I saw it in a MS Clarity video :/
The "Steps to reproduce" don't help? 
Did you try with a brand new account to where it would show these pointers?

**Comment by DustyReagan** [comment]
Gotcha! I tried the steps to reproduce using the onboarding flow. But that didn't cause the pointers to show. 🤔 I'll investigate what flow prompts those pointers next.

**Comment by obenland** [comment]
The query `?tour=checklistSiteTitle` will trigger the pop ups.

This is how I got there in case that's helpful:
* I [searched the wp-calypso repo for the button text](https://github.com/search?q=repo%3AAutomattic%2Fwp-calypso%20%22All%20done%2C%20continue%22&type=code) in the screenshot.
* [Blamed the file](https://github.com/Automattic/wp-calypso/blame/c6ef59973b7ba831d80f5425776ea41cb7ba1fd8/client/layout/guided-tours/tours/checklist-site-title-tour/index.js#L42) it was defined in and selected [the most recent change](https://github.com/Automattic/wp-calypso/commit/b1e02575952e18120657d47f1b419bcf8b730be5).
* Looked at the associated PR and found https://github.com/Automattic/wp-calypso/pull/58087#issuecomment-971298043

(I also followed a few dead ends before that, like searching for the notice body and looking at the PR that first introduced the component, which was not helpful)

<img width="1510" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/0f1c3d48-2fbd-47bf-a8ff-929f57d65f7f">

**Comment by DustyReagan** [comment]
Awesome! Thanks for sharing how you found that, @obenland!

**Comment by paulopmt1** [comment]
Hey @obenland, we just sent @DustyReagan's fix for that. Can you please double-check if it's working as expected to you?

**Comment by obenland** [comment]
I trust that it's fixed when you tell me it's fixed, but since you asked, I checked, and it's fixed. :) 

Thank you!
