### ISSUE TITLE
Woo DNA 2FA button is off-center

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/wp-calypso#82603]
### Quick summary

In the WPCOM auth flow using the Woo DNA design, the 2FA button is not centered and there's no padding when connecting to an account with Jetpack app auth enabled.

### Steps to reproduce

1. Have an existing account on WPCOM with authentication using the Jetpack app enabled.
2. Trigger a WPCOM connection flow by activating and connecting a Woo extension that uses the Woo DNA design for the WPCOM connection flow, example: WooPayments.

<img width="498" alt="Screenshot 2023-10-04 at 13 09 52" src="https://github.com/Automattic/wp-calypso/assets/1759681/b1642885-4952-4d4e-a00e-bd531eded310">

### What you expected to happen

The button is centered and there is padding.

Example design with fix in place:

<img width="490" alt="Screenshot 2023-10-04 at 13 10 40" src="https://github.com/Automattic/wp-calypso/assets/1759681/cfcb0fb9-c571-4d49-b5f6-85b43b78f67a">

### What actually happened

The button is not centered and there's no padding.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Tested on Firefox 118.0.1 (64-bit) on macOS 14.0.

**Comment by jeherve** [comment]
@chihsuan Does this ring a bell? Is that something that you could look at?

Thank you!

**Comment by chihsuan** [comment]
> @chihsuan Does this ring a bell? Is that something that you could look at?
> 
> Thank you!

Hey @jeherve Thanks for the ping! Yes, we will fix it soon. 🙂 cc @adrianduffell
