### ISSUE TITLE
Domains: Search bars are fixed on mobile

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#82605]
### Quick summary

On https://wordpress.com/domains/manage/SITE, scrolling the page on a small screen device will show the search bar and filter dropdown scroll with the page.

https://github.com/Automattic/wp-calypso/assets/1398304/f9d57529-5738-4b6b-976c-a51c9a23b895

### Steps to reproduce

1. On a device with a small screen, go to https://wordpress.com/domains/manage/SITE
2. Scroll down.

### What you expected to happen

For the searchbar and filter to stay where they are.

### What actually happened

The searchbar and filter overlay the underlying information.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by obenland** [comment]
Are we no longer able to assign tickets to teams? I couldn't add @Automattic/explorers in the Assignee field.

**Comment by allilevine** [comment]
> Are we no longer able to assign tickets to teams? I couldn't add @Automattic/explorers in the Assignee field.

I haven't been able to do that for a while either. 😞

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I can replicate this on my site using the browser's responsive tools as well. 

- At `481`px wide and above, the search bar and dropdown filter appear as they do on normal desktop-wide windows.
- At `480`px wide exactly, the Search bar and dropdown filter overlay ontop of the domains on the page, but scroll with the page
- At `479`px wide and below, they fix to the top of the screen while scrolling.

**480px**
![Markup on 2023-10-04 at 11:09:47](https://github.com/Automattic/wp-calypso/assets/27249804/8454eb96-c37a-47d8-8ed9-f7a44c251a2c)

**479px and below**
![Screen Capture on 2023-10-04 at 11-10-25](https://github.com/Automattic/wp-calypso/assets/27249804/a92d3e5f-16de-4104-8843-29982ced6088)

📌 ACTIONS
- Triaged

**Comment by paulopmt1** [comment]
We have a few options here, started a thread about it here: p1696971084215239-slack-CKZHG0QCR
