### ISSUE TITLE
[Editor] Align the styles of the different publishing modals

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#82625]

**Comment by cuemarie** [comment]
Hey @nuriapenya ! This is in my queue for triaging, so I've labeled it as best I can based on the title; it looks like this is mainly a note/task for yourself? Or possibly the content of the issue didn't save.

LMK if there's anything else I can help with here!

**Comment by nuriapenya** [comment]
Hey @cuemarie - yes, I thought it was initially a bug, but while I was writing all the different scenarios, I realized it is more of a bigger UX issue, and I ended up documenting it elsewhere. I will delete this issue and create a new one when I consolidate all the findings.

Sorry for the mess & thanks for following up! 🙏
