### ISSUE TITLE
Authentication: magic link authentication landing screen should put email and Continue button on separate lines.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82627]
### Quick summary

Magic Link landing screen (`/log-in/link`) puts the email address and the Continue to WordPress.com button on a single line resulting in minor formatting issues.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/29543c18-5abc-4be3-9d42-f20d379dfef0)

### Steps to reproduce

1. request a magic link.
2. click on the magic link.

### What you expected to happen

Landing page is nicely formatted.

### What actually happened

See the quick summary above.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described:

https://github.com/Automattic/wp-calypso/assets/27249804/353cbf9e-2914-4913-ad76-17802d373a75

📌 ACTIONS
- Triaged

**Comment by renancarvalho** [comment]
Hello 👋 I Checked it on Chrome, Firefox, Arc and Safari, and I was able to see it nicely.

Although, the page renders a bit fast since it logs in the user and redirects to `https://wordpress.com/sites`

Could you share which browser was used @cuemarie ?

**Comment by cuemarie** [comment]
Hi @renancarvalho ! That test would have been in either Firefox or Chrome, so it's likely this is no longer applicable 👍
