### ISSUE TITLE
Subscriptions: Unable to cancel from /me/purchases

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#82621]
### Quick summary

Users who try to cancel their subscriptions get an error after they click to confirm cancellation.

### Steps to reproduce

1. Navigate to /me/purchases
2. Click an active subscription
3. Click to cancel that subscription
4. Click the cancel button on the confirmation screen

### What you expected to happen

The subscription should be processed, and any pending refund should be applied.

### What actually happened

"An error occurred loading this page."

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Subscriptions need to be cancelled by an HE from the SA. I've so ar had two users (7124235-zd-a8c and 7123831-zd-a8c) with this issue.

**Comment by pauloeaquino** [comment]
Encountered in:

7124303-zen
7124328-zen

**Comment by Greatdane** [comment]
7124395-zd-a8c

**Comment by essleeung** [comment]
7123859-zd-a8c

**Comment by pauloeaquino** [comment]
7124210-zd

**Comment by cuemarie** [comment]
This was escalated here: p1696470382661749-slack-C02FMH4G8 and solved with a PR revert. An incident report is in the works. Thanks for the quick work, everyone!

**Comment by jjchrisdiehl** [comment]
Reverted in https://github.com/Automattic/wp-calypso/pull/82622

Reopening this issue to track future fixes to avoid the above bug in the `ChatButton` component going forward.

**Comment by cuemarie** [comment]
Thanks @jjchrisdiehl ! Do you think this should stay at the `High` priority level (which we monitor and report on more closely), or would `Normal` make more sense now that the issue is open primarily for tracking purposes?

**Comment by jjchrisdiehl** [comment]
Ah my apologies, reopened the wrong issue, closing for now 😄
