### ISSUE TITLE
Launchpad: Next Steps modal appears in the editor despite the site being launched

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#82626]
I found this case in which the Next Steps modal appears in the editor despite the site being launched, and therefore, the onboarding launchpad was deactivated.

Steps to reproduce it:

1. Created a new site, selected Build intent, and followed the steps until Launchpad. 
2. Launched the site from Launchpad
3. From My Home -> Write a new post and publish
4. This modal appears

**Edit**: This case only happens once. After this clip, I did the process again, and the official post-published modal replaced the Next Steps one.

https://github.com/Automattic/wp-calypso/assets/7931304/48fb7ad7-278e-4e4d-84f0-f90ab24c1529

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described.

**Recording** - this is virtually the same as what's shared in the original report :)
https://github.com/Automattic/wp-calypso/assets/27249804/0e0cb9d5-c3ca-4717-a684-fe7ed71e4265

📌 ACTIONS
- Triaged

**Comment by andres-blanco** [comment]
Currently, the modal is redirecting to `/setup/build/launchpad?siteSlug=[A SITE]` and when it renders it hits this code: https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx#L68 which marks the `launchpad_screen` option as `off`. Sadly this is too late.

Our best approach is to update the `maybe_disable_fullscreen_launchpad` on Jetpack so we can actually mark the launchpad as `off` after completing the `Launch site` task. Thant way the modal wont get shown in the first place.
