### ISSUE TITLE
Social First Signup: closing the user account before finishing onboarding results in the user being redirected to `/start/domains` when attempting to sign up for a new account.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82645]
### Quick summary

I know it's a bit of a handful and an edge case, but here goes:

If the user signs up using an email address in the passwordless signup, decides to not finish the onboarding at that time, closes the account, then decides at a later time to sign up for WordPress.com again, the `/start/user` step appears to "remember" the user never finished onboarding, so redirects all navigation to `/start/user` to `/start/domains`.

https://github.com/Automattic/wp-calypso/assets/6549265/0f054411-676f-4a76-b794-27b842608aae

### Steps to reproduce

**prerequisite: do not be logged in to WordPress.com.**
1. navigate to `/log-in`.
2. click on "Create a new account".
3. click on "Continue with Email".
4. enter a valid email address, or some gibberish address, doesn't matter. (Apologies to the owners of `woiuerpouwoeurpweruwer.com`).
5. you should now be in `/start/domains`. Open a new tab and navigate to `wordpress.com`.
6. perform standard Calypso procedure to close the account.
7. once account is closed, navigate back to `/start/user`.
8. click on `Continue with Email`.

### What you expected to happen

Passwordless flow **should not** remember the user had previously not finished onboarding.

### What actually happened

Passwordless flow appears to remember the user had previously not finished onboarding, and redirects the user to `/start/domains` but without a valid user account.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Workaround:
- clearing the cookie is an effective workaround.

Other (similar) scenarios tested:

**Instead of closing the account, user logs out**
Does not reproduce this issue (the state is **not** remembered).

https://github.com/Automattic/wp-calypso/assets/6549265/a9812434-bf85-44c1-9de4-5cf01cb513b2

**If the user finishes onboarding**
Does not reproduce this issue.

https://github.com/Automattic/wp-calypso/assets/6549265/3cb96893-4ac6-48e5-91cb-af692c0e1be8

**If an already-created user account is logged into, and then closed**
Does not reproduce this issue.

https://github.com/Automattic/wp-calypso/assets/6549265/f9e105f1-2a4b-4d61-a52c-33e054ac5d85

**Comment by cuemarie** [comment]
📌 ACTIONS
- Triaged
- FYI @Automattic/vertex just for your awareness
