### ISSUE TITLE
Showcase wp-admin: preview button opens customizer for block themes

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#82667]
### Issue:
The wp-admin view “Preview” button opens the Customizer for Block themes on my free site. 
See p1696486391439839/1696462113.939149-slack-C048CUFRGFQ 

### Expected:
For block themes, clicking on the Preview button should NOT open the customizer.  Expected behavior:
*  Once BTP is realeased (ETA Oct 11 APAC), it should go to BTP for themes that are BTP compatible. 
* For other block themes that are not BTP compatible Preview should open the demo site.

@Automattic/lego

**Comment by autumnfjeld** [comment]
Ian said this is likely a core issue.  p1696522546634599/1696462113.939149-slack-C048CUFRGFQ 

Thusthe task for this issue is
1. Test on a self hosted install
2. See if already reported in core
3. Report in core as needed

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – Could Not Replicate 
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO

> Test on a self hosted install

I was unable to replicate this issue anywhere but my Simple sites.

📌 ACTIONS
- Triaged

📌 Message to Author
According to the slack thread, there's a fix on the way here:  D124706-code

**Comment by autumnfjeld** [comment]
@fushar  I think you started a fix for this? Ya? If so can you move this to In progress?

**Comment by fushar** [comment]
This has been fixed and shipped via D124706-code.
