### ISSUE TITLE
[Suggestion] Site profiler: Add a spinner or any loading indicator when the URL analyzer lasts too long

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#82660]
![Image](https://github.com/Automattic/wp-calypso/assets/1241413/ed51c509-1f2c-45c4-8e27-b012e77abfae)

cc @javierarce @vishnugopal

**Comment by ouikhuan** [comment]
I'd like to propose some temporary solution for this: https://github.com/Automattic/wp-calypso/pull/82668

Before we figure out what to do, maybe we can have a skeleton status info in place so users will expect something that's still loading.  This is something I came up real quick and tempt to make this as a temporary solution only. If this is not helpful at all, feel free to abandon the PR.

**Comment by javierarce** [comment]
Nice, I think that could work, @ouikhuan.

**Comment by javierarce** [comment]
For the bottom part of the card, and to avoid showing a rectangle there, maybe we could just display the link.
