### ISSUE TITLE
Comments: Can't go to the following line and different cursor when hovering the Reply button (Firefox)

### ISSUE THREAD

**Issue by aetta** [Automattic/wp-calypso#82674]
### Quick summary

When leaving a reply/comment using Firefox, pressing **Enter** won't create a new line, and when hovering over the reply button, the pointer is altered.

### Steps to reproduce

1. Access a WordPress.com site using Firefox and locate the Comment box; 
2. Write and hit enter - You will stay in the same line; 
3. Hover over the Reply button and note the cursor pointer change;

### What you expected to happen

- Hitting enter goes to the following line; 
- Cursor pointer could be the same (`default`) on both browsers;

### What actually happened

- Hitting enter in the comment field doesn't go to the following line, it adds a space inline.
- Hovering the mouse over the Reply button changes the cursor pointer
  -  `cursor:unset;` on Firefox and `cursor:default;` on Chrome

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- 7122649-zen;
- Reproducible with Firefox 118.0.1 (64-bit) | Works fine on Google Chrome Version 117.0.5938.149 (Official Build) (64-bit)

Screenshot taken on Firefox 118.0.1:

![image](https://github.com/Automattic/wp-calypso/assets/54185702/d045e0f8-903a-48b8-8bc6-5cb088ebdf70)

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated both issues as described in Firefox 118.0.1 (64-bit):

https://github.com/Automattic/wp-calypso/assets/27249804/9596d9ed-ec57-49b2-9d19-ebd6bd8e648e

📌 ACTIONS
- Triaged
- CC: @Automattic/vertex 

For now I lowered the priority to `Normal`, but if we start seeing lots of Support interactions about this we can re-prioritize as needed!

**Comment by heavyweight** [comment]
Thanks for reporting this.
The fix for this has been merged D124495-code.
