### ISSUE TITLE
Design Picker theme preview: use excerpt from the showcase if available

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#82679]
# Description
p1696455892730859-slack-C048CUFRGFQ

If a theme excerpt exists show it in the Design Picker instead of the first sentance of the theme description.

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/e7494567-af09-4ae5-8a10-641047216ba0)

**Comment by fushar** [comment]
@ianstewart: I've checked via a hand-made script that only the following themes have excerpt (all are Partner themes). And they are all exactly the same with the theme's description (from style.css):

|Theme|Excerpt & Description|
|-|-|
|Kereta|Rev up your online automotive business with Kereta.|
|Vivid|Bring your shop to life with Vivid, a lively block theme that showcases bold colour palettes and draws inspiration from the iconic Bauhaus shapes.|
|Apparel|Experience minimalist and chic design with Apparel - a theme with exceptional dark-mode function.|
|La Beauté|Create a sophisticated WooCommerce health or beauty store with the La Beauté theme—featuring a responsive design and a Dark Mode option.|
|Copenhagen|Create a stylish modern home furniture store or home décor shop with the Copenhagen theme for WooCommerce.|
|Blissful|A complete WooCommerce theme, ideal for stores selling gifts such as flowers, toys, statues, cakes, chocolates, etc.|
|Chrono|Chrono by Organic Themes, the new standard in WordPress block themes for your online store. Designed with both elegance and functionality in mind, Chrono is the perfect choice for businesses seeking to elevate their online presence.|
|Photographer|Professionally showcase and sell your photography. Photographer is a clean and minimal block theme with a focus on the images. It's an excellent solution for professional photographers or hobbyists.|

I think I'll go ahead with this approach instead: when the theme preview screen in the Design Picker would not have any style variations / colors / fonts, show the entire description (not just the first sentence).

cc: @Automattic/lego

**Comment by fushar** [comment]
This is shipped.
