### ISSUE TITLE
Signup: Cannot create an account with `+` symbol in email address when proxied

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#82693]
### Quick summary

When trying to create a new account with a Gmail address containing a `+` symbol (the most common way to quickly create aliases in Gmail), I'm getting an error and am unable to proceed.

### Steps to reproduce

1. In an incognito browser session, go to https://wordpress.com/start/user
2. Type in a Gmail address with a +alias, e.g. `mygmailusername+foo@gmail.com`
3. Click Continue - you should see an error: `Sorry, something went wrong when trying to create your account. Please try again.`

<img width="377" alt="Create_a_site_—_WordPress_com" src="https://github.com/Automattic/wp-calypso/assets/11873759/4b9d2575-f114-4fb5-b62c-08f64e9ed554">

OR

1. In an incognito browser session, go to https://woocommerce.com/start/#/
2. Click Continue on the first two steps, then click the WooExpress CTA
3. In the email field type in a Gmail address with an alias like above
5. On moving focus to the password field it will trigger the API call to validate the email, and an error appears: `Use a different email address. This email provider blocks some of our emails.`

<img width="561" alt="Create_a_site_—_WordPress_com_—_Private_Browsing" src="https://github.com/Automattic/wp-calypso/assets/11873759/33d2bcc4-835a-433a-8a48-ad9cf813ffcb">

### What you expected to happen

To be able to create a new WPcom account using a +alias Gmail address, as I've been able to do many times in the past.

### What actually happened

I see the errors mentioned above, and cannot proceed to create an account

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Firefox - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described - this is definitely new, as this was working for me very recently while triaging other bugs.

https://github.com/Automattic/wp-calypso/assets/27249804/4277d667-63ad-48b8-8f23-7e39d23ba353

**If I disable my Proxy, though, I can create an account with the `+` sign as expected.**

📌 ACTIONS
- Lowered priority from Blocker to High, but we'll still see if we can get attention on this quickly
- Triaged
- CC: @Automattic/vertex as I believe y'all are working on signup stuff right now?

**Comment by cuemarie** [comment]
This is in discussion here: p1696495690262109/1696492384.660109-slack-C02DQP0FP

Unclear at the moment if this is a feature or a bug 🤔

**Comment by mpkelly** [comment]
@KokkieH, could you retest this one. I just tried and found that it worked for my a8c.com email and a regular gmail.com account. 

I will remove the "High" status.

**Comment by escapemanuele** [comment]
Yes, if I recall correctly, it was a temporary code change that has been reverted. It should be fine now.

**Comment by KokkieH** [comment]
Confirmed it's working for me as well again.

**Comment by xavier-lc** [comment]
Closing since the bug can't be reproduced anymore.
