### ISSUE TITLE
Pages: published count is incorrect on some sites.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82697]
### Quick summary

For at least one site, `site_id: 215380534`, the number of Pages being reported by the API `/sites/215380391/post-counts/page` is not the same as the result of `/sites/215380391/posts`.

![273122282-8daef267-7bba-4dd6-9be4-9cb8994fdcd2](https://github.com/Automattic/wp-calypso/assets/6549265/f7e1bde4-4a6e-4375-b6bb-6af90d190a95)

### Steps to reproduce

1. log in to `jetpackAtomicPrivateUser` user.
2. in the sidebar click on Pages.
3. compare the Published, Draft, Scheduled and Trashed counts to the actual count reported in the Network tab for the request to `/posts` endpoint.

### What you expected to happen

Counts of posts in each category should be exactly, or at least closely related to reality.

### What actually happened

Count is way off.

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Notes:
- so far, only observed on the particular `jetpackAtomicPrivateUser` user.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Triaged
- @jeherve in case this involves Jetpack further

**Comment by jeherve** [comment]
I'm afraid that's a known issue with reliability of cache site data. 

At one point we considered changing the way we fetch post count to be more dynamic: #31446 
This was never merged though.

@Automattic/jetpack-vulcan Do you think we should add this to our future roadmap again?

**Comment by Nic-Sevic** [comment]
another instance here: 7547230-zd-a8c

**Comment by davemart-in** [comment]
This issue is fairly old with no recent updates, plus we no plan to deprecate this entire page and use wp-admin page management using forward. See p58i-ioo-p2. Closing this issue.
