### ISSUE TITLE
WoA site with a Business Plan not allowing theme uploads and also displays incorrect error message with outdated design

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#82727]
#### Steps to reproduce

1. Upgrade to Business
2. Search for and activate Hello Dolly from /Plugins
3. Navigate to /Themes, search for and activate Astra
4. See error message below

![image](https://github.com/Automattic/wp-calypso/assets/545779/edee1a8d-c470-4a3c-b3e4-34a32de3a405)

#### What I expected

- [ ] The theme would correctly install and activate
- [ ] If this error displays on lower-tier plans when trying to install a community theme it references themes, not plugins
- [ ] the design has updated branding

**Comment by dsas** [comment]
I can't repro this by using the first two steps, though the theme activation does seem to get stuck until I reload and try it again.

If I go to https://wordpress.com/marketplace/theme/astra/install/:siteSlug on a free site it does get the message in the screenshot above.

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on the platform

📌 FINDINGS/SCREENSHOTS/VIDEO
- The theme installed without issues and I noticed we also got rid of that screen during theme install.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
