### ISSUE TITLE
Add calypso_themeshowcase_theme_click event to when clicking on thumbnails in discovery carousels

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#82720]
### Details

Clicking on a theme in the carousel doesn't trigger a `calypso_themeshowcase_theme_click event`, unlike live lots.

The event isn't firing when clicking on a theme because we're not passing `onScreenshotClick` et al to `ThemeBlock` via `ShowcaseThemeCollection` like we do with [`ThemesList`](https://github.com/Automattic/wp-calypso/blob/becfec6fe211e69792276ccdfd54406646c82993/client/my-sites/themes/themes-selection.jsx#L281)

Initially mentioned on the https://github.com/Automattic/wp-calypso/pull/82254#issuecomment-1750203937

**Comment by rcrdortiz** [comment]
Fixed in:
- https://github.com/Automattic/dotcom-forge/issues/4307
