### ISSUE TITLE
Theme showcase: Atomic sites not limiting to recommended themes

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#82762]
### Quick summary

Searching the logged-in theme showcase via a filter should limit the search results to just the 'recommended' (curated) results unless explicitly set otherwise, e.g. by changing tabs to all. This works on simple sites but not on atomic sites.

The API request being made goes to `https://public-api.wordpress.com/rest/v1.2/themes?http_envelope=1&locale=en-gb&page=1&filter=classic-theme&number=100&include_blankcanvas_theme=` when it should go to https://public-api.wordpress.com/rest/v1.2/themes?http_envelope=1&locale=en-gb&search=&page=1&tier=&filter=classic-theme&number=100&collection=recommended&include_blankcanvas_theme= as simple sites do.

Initial report: p1696610016893549-slack-C029FM1EH

### Steps to reproduce

1. Go to wordpress.com/themes while logged in
2. Select an atomic site
3. in the search bar enter `feature:classic-theme` and search

### What you expected to happen

To get the small number (currently three) of curated themes which match that filter

### What actually happened

All themes matching the filter are being returned, regardless of whether they're curated

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by dsas** [comment]
This issue has been around at least three weeks, it doesn't seem to be related to recent changes.

`tabFilter` is undefined on atomic sites [when creating the query](https://github.com/Automattic/wp-calypso/blob/3d197a200febc110db2afc58e0a3cbc5fb058c4b/client/my-sites/themes/themes-selection.jsx#L367), but is defined on simple sites.

This is because [atomic sites are treated as jetpack sites](https://github.com/Automattic/wp-calypso//blob/trunk/client/my-sites/themes/theme-showcase.jsx#L336) and render their [children](https://github.com/Automattic/wp-calypso//blob/trunk/client/my-sites/themes/single-site-jetpack.jsx#L119) which does not calculate/pass-on the `tabFilter` prop, whereas simple sites don't have any [children](https://github.com/Automattic/wp-calypso//blob/trunk/client/my-sites/themes/single-site-wpcom.jsx#L83) and just render using the logic in \<ThemeShowcase> which does [calculate and pass on a `tabFilter` prop](https://github.com/Automattic/wp-calypso/blob/ec86373da782fd46fa2861ae70a43a951fa18ee5/client/my-sites/themes/theme-showcase.jsx#L477)(which defaults to recommended).

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described - the Recommended tab of filter:classic-themes shows all Classic Themes in results on Atomic, and only the 3 curated selections on Simple.

**Atomic**


https://github.com/Automattic/wp-calypso/assets/27249804/02470840-1eed-42d4-875a-173444fb4b10

**Simple**

![Markup on 2023-10-09 at 16:27:13](https://github.com/Automattic/wp-calypso/assets/27249804/038f27f9-536b-4a23-9255-1296e89bd249)


📌 ACTIONS
- Triaged

**Comment by rcrdortiz** [comment]
Closing this issue, just checked and Simple and Atomic are working consistently. When searching for a classic theme we get 0 Recommended results on the Recommended tab. After switching to "All" you can see the same results on both platforms as expected.
