### ISSUE TITLE
Add New Payment Plan Currency Dropdown Not Working Properly

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#82771]
### Quick summary

When trying to add a new payment plan in Tools > Earn > Payment Settings > Payment plans, the currency dropdown is blank. If you select an item, the dropdown disappears from the screen altogether.

![PaymentPlanCurrencyDropdown-Blank](https://github.com/Automattic/wp-calypso/assets/93800099/a7575bab-1107-4ac4-9139-f1dad27e1f05)

### Steps to reproduce

1. On any site, navigate to Tools > Earn > Payment Settings > Payment plans
2. Click "Add a new payment plan". A modal should pop-up
3. Try changing to a different currency. Notice the dropdown is blank.

### What you expected to happen

The currency dropdown to show a list of currencies and allow the user to choose one.

### What actually happened

The currency dropdown is blank. Upon choosing a "blank" item, the dropdown disappears and you see an error about entering a "price higher than ...."

![PaymentPlanCurrencyDropdown-AfterChoosingCurrency](https://github.com/Automattic/wp-calypso/assets/93800099/2d3f5a66-65b4-416b-9653-5bd2dfe50406)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Slack discussion: p1696860423100459-slack-C03TY6J1A

Customer interaction: 7141720-zd-a8c

**Comment by millerf** [comment]
A fix was deployed that should fix this issue...
