### ISSUE TITLE
☂️  Assembler: Improve education on limits of Assembler and editing in the Editor

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#82782]
# Description

❗ See Task 2 below and this https://github.com/Automattic/wp-calypso/issues/82782#issuecomment-1820045290 for the remaining work on this issue. ❗ 

We have had significant feedback, multiple times,  that users get confused on the "limitations" of the Assembler.  Some users want to edit the content, change copy, resize images, etc.   We need to make it very clear that the Assembler is just a starting point for site layout and styles.  We need to make it clear that editing comes next in the Editor.  I consider this an urgent issue because on reason Pooja (pf2bN8-1x-p2#comment-30 ) rejected the Assembler was because she couldn't resize images in the header---she is an experienced WP user and she could not put the dots together that she would be able to adjust content in the editor.  

### Feedback
* Customer Council interview pf2bN8-1x-p2#comment-30
* Ian's Gurilla testing pekYwv-2ZS-p2
* I know there are additional mentions of this issue, but I do not have links (maybe in CfTs or in the survey).

### Proposal
*  Make better use of the blank starting canvas. and information about "editing later in the Editor." And make sure the font is big and catches the eye so that users will read it. Maybe have engaging icons that draw the eye to the canvas and cause users to read the information.   
* Place small hints at specific moments/actions like @lucas suggested here pekYwv-2ZS-p2#comment-2271
* Address the issue that if someone clicks the Design your own button at the top of the Design Picker, they will not see the information in the CTA

Let's put helpful, instruction information here so the user knows that editing comes later, in the Editor. 
![Image](https://github.com/Automattic/wp-calypso/assets/5665959/0890436b-5596-4db9-93d8-f678c4ac7688)

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/1496e8d7-8f7e-4dbb-8c3c-2d839bacecfd)

##  Task 1: Educational copy in the blank starting canvas
- [x]  Basic copy update:  https://github.com/Automattic/wp-calypso/issues/83379

## Task 2:
- [x] Place small hints at specific moments/actions like @lucas suggested here pekYwv-2ZS-p2#comment-2271

See discussion from mid November in Assembler: visual warning when users try to edit in the site preview – Dotcom Design p9Jlb4-9K2-p2

**Comment by autumnfjeld** [comment]
@ianstewart  & @lucasmendes-design  If we continue using this screen, I'd suggest we add a mention of the Editor.  Be explicit.

**Current:**
Time to add some content and bring your site to life!

**Proposal:**
It's time bring your site to life! Next you'll edit your site and add your own content in the WordPress Site Editor.

**Comment by autumnfjeld** [comment]
OR if we are going with the Launch pad then "Edit site design" takes care of this I think.   
We could have checked off items:

✅ Design homepage layout
✅ Select styles
✅ Add page


![Image](https://github.com/Automattic/wp-calypso/assets/5665959/a2a611ef-7448-4460-a916-24ffd3af07cd)

**Comment by tanjoymor** [comment]
Yay :) I'm glad to see the idea of using this big open space for education is being considered, it was one of my early day suggestions too. Even if the Launchpad is going to be used, I would still recommend using this space on entry to make it clear how it works. Further ideas for copy consideration:

**Welcome to your homepage.**
It's time bring your site to life! 
**Step 1:** Select your Header, Sections, and Footer placeholder patterns to create the base layout.
**Step 2:** Customize the style by choosing custom colors and font pairings.
**Step 3:** Proceed to the Site Editor where you can then edit your chosen patterns and add your own content.
Want more of a walkthrough? [Learn more](https://wordpress.com/learn/courses/quick-launch/design-your-homepage/#Now-let's-design!)

And for this to be included here: ![MnR3XQ.png](https://github.com/Automattic/wp-calypso/assets/42655541/37c7e9ff-2f7d-4146-ae75-67c58a00ec1b)

**Comment by lucasmendes-design** [comment]
> "Edit site design" takes care of this I think.

+1. I think it's a great idea. 

> copy

IMO we can improve the copy, it's something with low effort. 

Food for thought: 
There is a classification for clicks that it's very helpful here. Many softwares out there like HotJar and Fullstory have the feature to identify those clicks:
- [Error clicks](https://www.fullstory.com/blog/error-clicks/#:~:text=Simply%20put%2C%20error%20clicks%20are,which%20can%20cause%20system%20errors.)
- [Rage clicks](https://www.fullstory.com/blog/rage-clicks/#:~:text=Rage%20clicks%20are%20when%20users,Broken%20elements). [HotJar](https://www.hotjar.com/blog/rage-clicks/)
- Dead clicks. 

This could be a way to understand the impact and the size of the problem. We saw some rage clicks on our research, users were clicking multiple times on the image trying to edit or resize it. This was the reason for introducing the tooltip when users click two times on the image for example.

**Comment by ianstewart** [comment]
I like how explicit Tanya's copy is but can see users annoyed when the "steps" disappear after adding content so I reduced it down:

> Start by choosing your site's Header, Section, and Footer patterns on this screen. Then move on to customizing your Fonts and Colours. This is just the setup; once you've got the basics of the design right, you'll edit content at the end in the Site Editor. Need a walkthrough? Learn more.

Nice to have: The learn more could be a video that loads in a modal showing someone go through the whole flow, smoothly.

**Comment by autumnfjeld** [comment]
> This was the reason for introducing the tooltip when users click two times on the image for example.

@lucasmendes-design  Do you mean this pekYwv-2ZS-p2#comment-2271. (it isn't implemented). I'm asking because I don't remember any discussion about "two clicks". :)  But I'm happy to go forward with this in this issue.

**Comment by tanjoymor** [comment]
> Nice to have: The learn more could be a video that loads in a modal showing someone go through the whole flow, smoothly.

This would be a really nice touch. We are launching a webinar in November that will be a live demo of working with the 'pattern assembler' as well. In the meantime, [the link I included above](https://wordpress.com/learn/courses/quick-launch/design-your-homepage/#Now-let's-design!) is the anchor link to the specific section of the lesson in our course that walks through the steps. I've updated some of the wording, I need to swap out the screenshots since there's been updates to the UI.

**Comment by autumnfjeld** [comment]
@miksansegundo  This is Ready for dev if you'd like to take it this week. 

 You can include the following specs in your PR:

![image](https://github.com/Automattic/wp-calypso/assets/5665959/affa9671-de8d-4614-94d4-db11003f3899)

* Show the tooltip with a single click, rather than double, to make it more accessible.
* Hide the tooltip when the pointer moves out of the canvas.
* Tooltip copy: "You can edit your content later in the Site Editor."
* This tooltip should be included on both patterns and pages.

Thank you. ;) 

We'll make a seperate issue for the copy in the sidebar that was also discused in your p9Jlb4-9K2-p2#comment-9765.
