### ISSUE TITLE
Image block: Exiting to the Page/Post from Gallery Blocks requires two clicks when Gallery images have "Expand on Click" enabled.

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#82790]
### Quick summary

When images added to a Gallery block have "Expand on Click" enabled, users need to click twice to exit to the page/post: first click to exit the carousel, and a second click to exit the lightbox.

### Steps to reproduce

1. Add a Gallery block to a page/post
2. Add two images to the Gallery block
3. For both images, enable the "Expand on Click" from Image settings panel
4. Publish the page/post
5. Visit the page/post and click on the gallery image
6. Click on the first image; and enlarged image opens on the carousel
7. Click "x" at the top right of the carousel to exit the carouselthe 

### What you expected to happen

Return to the Gallery on the page/post.

### What actually happened

The screen returns to the lightbox instead and we have to click again to close the light box to finally return to the page/post.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Video of the issue

https://github.com/Automattic/wp-calypso/assets/1519466/dbd577e0-c6b2-449f-a106-e56595dc7804

**Comment by cuemarie** [comment]
This is another component to the conflict between Jetpack's Carousel and Gutenberg's new built-in Lightbox features, which is in discussion here: 

- https://github.com/Automattic/jetpack/issues/32668

📌 ACTIONS
- Closing as duplicate
- Will add the new symptom regarding 'expand on click' to that report
