### ISSUE TITLE
Plans 2023: Sync state/selector use for pricing in grids & notices. Stick to plan-price selectors if possible

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#82795]
In https://github.com/Automattic/wp-calypso/pull/82761, we shipped some changes that affect the pricing for the current plan in the grid. The changes are introducing a new state slice (purchases) and deviate from the plan-price selectors used so far for grid prices and upgrade credits.

Let's explore whether it should have been a simple switch to `planDiscountedRawPrice` for the current plan.

See the relevant discussion below:

> Another thing to confirm is the upgrade credits calculation in the plan notice. I'm not sure how that's computed, but it does call the underlying state selectors separately from the pricing meta hook used for the grids
> 
>> @chriskmnds Good question. The upgrade credits seem to be calculated correctly. The [useCalculateMaxPlanUpgradeCredit](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plans-grid/hooks/use-calculate-max-plan-upgrade-credit.ts#L22) used to calculate the credits relies on the difference between `planDiscountedRawPrice` and `sitePlanRawPrice` for each plan. The price [used](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/sites/plans/selectors/get-site-plan-raw-price.ts#L28) for `planDiscountedRawPrice` is the correct one, the one at which the plans was purchased.

_Originally posted by @claudiucelfilip  in https://github.com/Automattic/wp-calypso/pull/82761#issuecomment-1753185771_

> I need to inspect the changes more closely, but curious - why aren't you using this selector then and instead go through the call to purchases?
> 
>> @chriskmnds I didn't know of at implementation and I used the same [selector](https://github.com/Automattic/wp-calypso/blob/trunk/client/me/purchases/manage-purchase/purchase-meta.tsx#L62) as the on /purchases/subscriptions, which showed the correct price for the active plan.
>>
>>> Cool. If we can refactor here to use the same selector, then I think that would be great (unless there's a strong argument not to). I may be wrong, but shouldn't this be a simple change of selectors used, if we have and use the selector already? Right now, it's also unclear when the previous value is used (is there a case where the "purchased product" doesn't take precedence for the current plan?). If this is too urgent, then I can attempt to refactor in another PR. 
>>>
>>> My other problem is we are introducing another slice of Calypso state (with respective API calls to populate). Everything touched in `usePricingMetaForGridPlans` will have to move to data stores as part of NPM refactor PT. So now we need `purchases` being ported over to keep this logic (so looks like just more work ultimately).

_Originally posted by @chriskmnds in https://github.com/Automattic/wp-calypso/pull/82761#pullrequestreview-1666608836_
```[tasklist]
### Tasks
- [ ] Use planDiscountedRawPrice for current plan's price, removing the logic introduced that derives the price from purchases
- [ ] Test using the same instructions from https://github.com/Automattic/wp-calypso/pull/82761 to confirm the changes (current plan's price reflecting price the plan was purchased with)
```

**Comment by claudiucelfilip** [comment]
After a second look at how the credits are calculated, I realize that things are a bit more complicated and indirect.
The `planDiscountedRawPrice` is actually null for the active plan but the value it gets for the other plans actually hints at the correct price for the active plan.

With this in mind, so far, I don't see a way around the [getByPurchaseId](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/purchases/selectors/get-by-purchase-id.js#L11) selector.
