### ISSUE TITLE
Jetpack Plugins: remote management error should poll for changes

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#828]
Reported by rickybanister. To reproduce:

1. Set up a new Jetpack site
2. Connect to WordPress.com
3. Do not enable remote management
4. Visit a plugin page
5. See this error:
<img width="624" alt="screen shot 2015-09-08 at 12 56 29 pm" src="https://cloud.githubusercontent.com/assets/437258/9744992/215178c2-563d-11e5-8a23-be92524f380c.png">
6. Click the helpful blue button
7. Turn on remote management
8. Close the wp-admin tab
9. Land back on calypso tab, & still see the error above

Since I'd fixed the situation I was annoyed to see the error when I landed back on that page. I'm smart enough (sort of) to know that I could have refreshed the page and see the correct thing, but I wanted that page to poll for updates to the Jetpack connection and be ready for me to manage plugins when I got back.

Can we change it to listen for changes once the blue button is clicked?

**Comment by enejb** [comment]
This part is fixed now since the data if a site has manage enabled is part of the me/sites api endpoint. Which is currently being pulled. 
Feel free to open this if you find this not to be the case.
