### ISSUE TITLE
Themes Discovery: Clicking on interactive elements changes the carousel's position

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/wp-calypso#82803]
When we click on the three dots menu inside an element of the carousel, if the element clicked on is not the first element, the carousel moves until the item is positioned first. The same applies when clicking on style variations.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Quick-triaged 

📌 Message to Author
- If you'd like a deeper repro test on this, feel free to ping me and let me know the steps to replicate, and I'm happy to run that through our fuller triage tests. Otherwise, I won't hold this one up 👍
