### ISSUE TITLE
Free domain feature is sometimes shown in checkout for renewals

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#82813]
As reported here: pNPgK-6HR-p2

[There is a condition](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/checkout/src/lib/get-plan-features.ts#L29) which prevents showing the "Free domain for one year" feature in the checkout sidebar if the cart contains renewals. However, sometimes it appears not to work.

Here's an example of my test user with a renewal:

![free-domain-correct](https://github.com/Automattic/wp-calypso/assets/2036909/bdb43ec3-c899-4025-af22-8c89a6d877f2)

But here's another user with a renewal where you can see the feature incorrectly listed:

![free-domain-incorrect](https://github.com/Automattic/wp-calypso/assets/2036909/daad0e88-2ee1-4cab-b345-6abd7907c57a)

**Comment by DavidRothstein** [comment]
This happens for users in a particular recent test.  I posted details at pbxNRc-33H-p2#comment-4957

The bug was introduced in https://github.com/Automattic/wp-calypso/pull/81313.

Not sure if we should close this issue or leave it open.

**Comment by sirbrillig** [comment]
Hm... yeah, we can probably close this, and then re-open it only if no one does anything about the bug.

**Comment by kristinaquinones** [comment]
@sirbrillig, @DavidRothstein, just a heads up we will fix this; our work will be tracked from this Parent Issue: Automattic/growth-foundations#237

... and we'll note again here and in the original bug report on P2 when completed.

**Comment by kristinaquinones** [comment]
Update:

reported bug has been resolved by Automattic/wp-calypso#83364
