### ISSUE TITLE
Theme Showcase: blank page when loading Appearance > Themes on Atomic sites

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#82816]
### Quick summary

The theme showcase is loading a blank screen on Atomic Sites. 
https://github.com/Automattic/wp-calypso/assets/14153300/3d1aefac-cc50-4637-808e-b53012278cbc

Console log

<img width="1361" alt="CleanShot 2023-10-10 at 16 35 30@2x" src="https://github.com/Automattic/wp-calypso/assets/14153300/091e8457-cd05-45b0-9316-1faa3a9f1a9d">

### Steps to reproduce

1. On an Atomic Site, navigate to Appearance > Themes.
2. 

### What you expected to happen

The theme showcase should load correctly

### What actually happened

Theme showcases loads for a few seconds and then disappears. A blank screen is shown instead

### Impact

Some (< 50%)

### Available workarounds?

Yes and the platform is still usable

Loading `/wp-admin/themes.php` works.

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Chrome 117
GB 16.7.1
ETK and Page Optimize active

**Comment by liviopv** [comment]
Escalated p1696951944278439-slack-C02FMH4G8

**Comment by cuemarie** [comment]
This issue has been fixed in the escalation thread. Summary: p1696954175388419/1696951944.278439-slack-C02FMH4G8
