### ISSUE TITLE
Newsletter Settings - Full Text vs Excerpt setting for new post emails overridden by Settings > Writing > Feed Settings

### ISSUE THREAD

**Issue by janmckell** [Automattic/wp-calypso#82815]
### Quick summary

_Update - this is reproducible when Settings > Writing > Feed Settings is set to "Limit feed to excerpt only". -cuemarie_

When the 'Full Text' option is activated and the changes saved, this does not save. It says that it was saved correctly but when the page is refreshed, the saved change reverts.

Though I could not replicate this on my test sites, it was definitely happening on this users site:
7109261-zd-a8c

Screenshots: [REDACTED]

https://github.com/Automattic/wp-calypso/assets/27249804/ae513e62-bcd4-4bfe-9f1a-2071c50acefb

### Steps to reproduce

_Updated steps to reproduce_

1. Open Settings > Writing https://wordpress.com/settings/writing/
2. Under **Feed Settings**, enable `Limit feed to excerpt only` and Save
3. Open Settings > Newsletter https://wordpress.com/settings/newsletter/
4. Set **For each new post email, include** to `Full text` and Save
5. Refresh the Settings > Newsletter page
        - _observe the selection switch back to Excerpt_
 6. Return to Settings > Writing https://wordpress.com/settings/writing/ and disable `Limit feed to excerpt only`
 7. Return to Settings > Newsletter 
      - _observe that now you can save Full text or Excerpt (you may see that Full text is now selected)_

### A clear and concise description of what you expected to happen.

Expected that the saved change remains as is.

### What actually happened

The saved change reverts, and never saves.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment]
Moving this to the Calypso repo, where those settings live.

**Comment by simison** [comment]
@janmckell  Was this a Jetpack site? (I can't see Zendesk)

**Comment by cuemarie** [comment]
@simison here are some more details:

- Site ID: 224137115
- Simple WordPress.com site on the Personal Plan

But I've actually seen this before!  I thought I'd reported it, but I guess not.  The issue is replicable in this setup:

1. Open Settings > Writing
2. Under Feed Settings, enable `Limit feed to excerpt only` and **Save settings**
3. Open Settings > Newsletter
4. Set **For each new post email, include** to `Full text` and **Save settings**
5. Refresh the Newsletter Settings page
     - _observe the selection switch back to Excerpt_


https://github.com/Automattic/wp-calypso/assets/27249804/ae513e62-bcd4-4bfe-9f1a-2071c50acefb

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated following [the steps here](https://github.com/Automattic/wp-calypso/issues/82815#issuecomment-1758468686) on both Simple and Atomic.

📌 ACTIONS
- Updated Title & Steps to reproduce
- Triaged

**Comment by cuemarie** [comment]
📌 Message to Author
- @janmckell Always make sure to exclude any user-specific information in your screenshots or details.
- For next time, I have edited the report above to use remove the user-specific information, and [deleted the previous revisions](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

**Comment by janmckell** [comment]
> Was this a Jetpack site? (I can't see Zendesk)

@simison It is a site on a Personal plan.

> Always make sure to exclude any user-specific information in your screenshots or details.
> For next time, I have edited the report above to use remove the user-specific information, and [deleted the previous revisions](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

@cuemarie Thank you so much, and noted, I understand, will do.

**Comment by jorpdesigns** [comment]
Reported in 7669629-zen

Suggested disabling "Limit feed to excerpt only" toggle on Writing Settings.

**Comment by Mfarroq1** [comment]
7985093-zen

**Comment by chekle** [comment]
8229923-zd-a8c +1

**Comment by lezama** [comment]
These settings got decoupled after: D163324
