### ISSUE TITLE
Site Profiler: adding an URL with a space create a URL with a "20"

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#82819]
1. On https://wpcalypso.wordpress.com/site-profiler
2. Input `exam ple.com` (notice the space)
3. The site show briefly redirects you to `https://wpcalypso.wordpress.com/site-profiler/exam%20ple.com` and the `%` is removed from the URL-encoded space, and the input shows `exam20ple.com`

**Comment by bogiii** [comment]
Thanks for reporting this; the solution could be a better form validation.
