### ISSUE TITLE
Email Forwarding shows warning that 25 of 25 Forwards used on Business and Commerce Plan 

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#82812]
### Quick summary

When adding email forwards to a domain, once you reach 25 forwards, the Email Forwarding page mentions you hit the limit of 25 of 25 email forwards.

It is possible to continue adding emails using this direct link: `https://wordpress.com/email/{DOMAIN NAME HERE}/forwarding/add/{DOMAIN NAME HERE}`

Here is a screen recording of how to replicate:

https://github.com/Automattic/wp-calypso/assets/93800099/171150bf-5b3b-48af-a6c3-e7ace6445db6

### Steps to reproduce

1. On a Business or Commerce site, navigate to Upgrades > Emails > Start with Email Forwarding.
2. Add email forwards.
3. Keep repeating step 2, when you get to the 26th one, you'll see this limit at the bottom and won't be able to add more forwards from that page:

![EmailForwardLimit](https://github.com/Automattic/wp-calypso/assets/93800099/bdc2113a-0b4e-44e9-aa48-5e275348cd31)

### What you expected to happen

I expected the limit to not show at all until I added 100 email forwards OR for the page to show the current number of email forwards added vs the allotted amount. 

Per our public support doc [Email Forwarding](https://wordpress.com/support/add-email/email-forwarding/), sites on Business and Commerce plans can add up to 100 email forwards for each domain, while sites on lower plans can only add 25.

### What actually happened

A message indicating the limit of 25 of 25 email forwards has been reached.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I did not test on a simple site on the Business or Commerce plan.

Once the forwards are again under 25 total, the limit message disappears.

Related slack thread: p1696945137463299-slack-C03TY6J1A

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO

Replicated as described:

**Business plan on Simple & Atomic sites**

![Markup on 2023-10-11 at 13:47:29](https://github.com/Automattic/wp-calypso/assets/27249804/46e0e910-b017-4101-abec-231a64af88f7)

📌 ACTIONS
- Triaged

**Comment by happychait** [comment]
7250306-zen

**Comment by DavidSaladu** [comment]
Another one here 7253381-zd-a8c

**Comment by Greatdane** [comment]
7353812-zd-a8c

**Comment by jp-imagines** [comment]
Another report in 7478889-zd-a8c

**Workaround:** Visiting the direct "add new email forwarding" URL still works: `https://wordpress.com/email/PRIMARY-DOMAIN/forwarding/add/PRIMARY-DOMAIN` (or `https://wordpress.com/email/PRIMARY-DOMAIN/forwarding/add/SITE-ADDRESS` for Simple sites)

**Comment by Aurorum** [comment]
PR in #86084. :)

**Comment by nightnei** [comment]
The fix is deployed. Now Creator+  plans have a limit of `100` and see `Add new email forwards` button.
Thank you @Aurorum :)
