### ISSUE TITLE
Design Picker: Catch errors triggered by the hexToRgb function

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#82822]
In Design Picker package, we use a `hexToRgb` function that throws an error when an invalid color code is passed as an argument. However, we don't catch this error in the [Style variation badge](https://github.com/Automattic/wp-calypso/blob/175123a739bc436c7acb1d02a3c7c67b43ce37cb/packages/design-picker/src/components/style-variation-badges/utils.ts#L33) component.

The consumers might break since they might not have an error boundary. For example, ThemeShowcase triggers a blank white page.

To make the code more resilient, we should at least catch the error in the design picker package (and possibly add some kind of fallback behavior or reporting).

**Comment by pbking** [comment]
Note that 4 digit color values (i.e. `#aabbccdd`) aren't invalid and will be present in themes. (The 4th value is the transparency level or "alpha".)  I don't know if a "hexToRgba" function should be used/considered instead?

**Comment by dsas** [comment]
Looks like #85764 catches and logs the exception so I'll close this issue
