### ISSUE TITLE
Reader/cache: filter out blocked sites

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#82828]
The code that gets the posts for the discover stream filters out posts from sites a user has blocked. When we added caching to the stream this stopped working. The code still runs, but when results get cached they are related to only one user. This is the code that filters the blocked sites: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Stybony%2Qgnt%2Qcbfgf%2Spynff.jcpbz%2Qtybony%2Qgnt%2Qcbfgf.cuc%3Se%3Q11397p09%23236-og

The solution probably is refactoring the filter outside the get_posts function and creating a separate stream filter that runs it. That way we can still cache the results but later filter them for the specific user.

**Comment by markbiek** [comment]
Implementation work is happening in D126800-code
