### ISSUE TITLE
Support 4/8 digit hex codes in theme palettes

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#82823]
### Details

Our [hexToRgb function](https://github.com/Automattic/wp-calypso/blob/33817ca41a0302641ba4acb2213d5b48a8f09611/packages/onboarding/src/utils/contrastChecker.ts#L43) as part of the `contrastChecker` util does not work with [hex digits which include transparency](https://dev.to/grahamthedev/hold-on-there-are-4-and-8-digit-hex-codes-for-colours-261i).

Upcoming themes will use hex digits that include transparency, and therefore we need to support them.

### Checklist

- [ ] Allow the validation to work with 4/8 length hexcodes
- [ ] Check that the `hasMinContrast` algorithm still makes sense for semi-transparent things
- [ ] Check that `<StyleVariationBadge>` as seen in onboarding & theme showcase, works properly with semi-transparent hexcodes
- [ ] Update the error handling to throw an `Error` rather than a string

**Comment by dsas** [comment]
@taipeicoder can we close this issue now or is there more left to do?

**Comment by taipeicoder** [comment]
Yes, let's close it. I'll add a debug message as you https://github.com/Automattic/wp-calypso/pull/85764#discussion_r1439249833 in a follow-up PR 🙂
