### ISSUE TITLE
Themes: Display the page for the user without any site

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#82839]
Similar to the plugins work.   https://github.com/Automattic/wp-calypso/issues/82549

If a user without a dotcom site searches for a theme on google, then they should be able to get to the theme page on dotcom.

**Comment by autumnfjeld** [comment]
@arthur791004  I moved this to in progress per your geekbot.  Can you link any open PRs or diffs here?

**Comment by arthur791004** [comment]
Sure! Here is the WIP PR, https://github.com/Automattic/wp-calypso/pull/82917

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/82917
