### ISSUE TITLE
Stats: Views for File Download increases when editing the page where it is embedded

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#82848]
### Quick summary

On a simple site, when you open the editor of a page where audio file is embedded, it increases the File Download count for the embedded files.

I was able to reproduce it on Simple sites only.

### Steps to reproduce

1. On a simple site, go to Media and upload an audio file. You can find same files [here](https://href.li/?https://file-examples.com/index.php/sample-audio-files/sample-mp3-download/).
2. Go to Pages > Add New
3. Add Embed block and paste the URL to the uploaded audio file and save the changes.
4. Reload the editor.
5. Check Stats > File downloads.

You will notice that download count increases with each reload of the editor page.

### What you expected to happen

The file download count should not increase when the page editor is opened.

### What actually happened

The file download count should increased when the page editor is opened.

Here's a screen recording: 

https://github-production-user-asset-6210df.s3.amazonaws.com/33957570/274180333-3e861dc8-fb26-4793-82f0-7d183fbdb164.mp4 

You can see the download count increases from 2 to 3.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

User report: 7150549-zd-a8c

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
I can replicate this only if I embed the URL of an audio file using the Embed block.  However, if I use the Audio Block, refreshing the editor does not impact the stats of file downloads.

**Embed Block impacting Stats**

https://github.com/Automattic/wp-calypso/assets/27249804/a066802c-0cf7-4a4c-b411-357218de988c

**Audio Block Alternative**

https://github.com/Automattic/wp-calypso/assets/27249804/3941dd83-01b2-4b2f-b738-004552e7cd82

📌 ACTIONS
- Triaged

**Comment by davemart-in** [comment]
Seems like an older issue that's fairly edge case, with no actual reports from customers. Going to close this issue in my triage process, but happy to open it back up if you feel strongly about it.
