### ISSUE TITLE
Newsletter: Unexpected errors in console & UI when updating the settings

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#82856]
### Impacted plugin

Jetpack

### Quick summary

When navigating to Settings > Newsletter, I see an uncaught error `Uncaught (in promise) NotFoundError: Invalid site specified` in the console. Also, intermittent errors pop up when updating settings, even though the settings appear saved. 

NOTE: This issue was found during the testing of p8oabR-1n7-p2

### Steps to reproduce

1. Navigate to Settings > Newsletter.
2. Observe the console error: `Uncaught (in promise) NotFoundError: Invalid site specified`.
3. Try updating any setting, like enabling the subscriber pop-up. (NOTE: This is intermittent so you may have to refresh the page and update the setting again to replicate the error.)
4. Observe the error message in the UI: `An expected error occurred. Please try again later.`

### A clear and concise description of what you expected to happen.

I expect that I won't see the uncaught error in the console or any error in the UI when accessing and modifying the Newsletter settings. 

### What actually happened

When navigating Settings > Newsletter, there is an uncaught error in the console. 

`Uncaught (in promise) NotFoundError: Invalid site specified`

![no9fCR.png](https://github.com/Automattic/jetpack/assets/67279475/f2d2a1d5-2e6a-40be-83e5-fe5ea962f8ef)

I also get intermittent error messages when making updates, the settings seemed to save successfully. 

![lXH69V.png](https://github.com/Automattic/jetpack/assets/67279475/bb07b162-a3b9-4d68-89dd-6b6170e37b80)

FULL VIDEO:

https://github.com/Automattic/jetpack/assets/67279475/6eb4d4da-395d-419f-b422-a25b8d19ddcd

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by jeherve** [comment]
Moving this to the Calypso repo, since that's where this is being developed.

**Comment by lsl** [comment]
Seeing this on most settings pages in calypso. Seems to be this url:

```
https://public-api.wordpress.com/wpcom/v2/sites/undefined/launchpad?_locale=user&checklist_slug=intent-build&_envelope=1
```

I guess it's not getting selected site id properly :thinking:

**Comment by ezebecke** [comment]
User reported same issue on 7782597-zd and I'm able to replicate it.

**Comment by rickmgithub** [comment]
Also seen in the newsletter signup flow.

https://github.com/Automattic/wp-calypso/assets/13706336/79198130-fb0f-4156-91fc-8d5b7a090c20

**Comment by lsl** [comment]
@simison would you be able to take a look? I couldn't figure this one out.

I can replicate via /setup/newsletter and selecting a wordpress.com subdomain.

It doesn't seem to prevent signup?

**Comment by simison** [comment]
@lsl yep! Thanks for the ping.

**Comment by pkuliga** [comment]
Noticed it for other settings as well. Seems like a global bug, not related to Newsletters.

![2024-03-15 13 14 17](https://github.com/Automattic/wp-calypso/assets/4068554/62da75d1-f912-4237-9703-702801968549)

I'll debug further.
