### ISSUE TITLE
Email Stats: small screen breakpoint issue

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#82861]
### Quick summary

Email stats show up too tight on smaller screen breakpoint:

<img width="1159" alt="Screenshot 2023-10-11 at 14 31 57" src="https://github.com/Automattic/wp-calypso/assets/87168/e1fcf7f7-930d-473c-aeac-349d937cb69a">

### Steps to reproduce

- Check email clicks screen on smaller screen sizes

### What you expected to happen

Better small screen scaffolding.

### What actually happened

Tight side gap.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

- Chrome

**Comment by simison** [comment]
@yansern or @jasperck could one of your teams take a look? Seems quickie.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described on `https://wordpress.com/stats/day/emails/SITE_ADDRESS`

Margins are lost between ~1350 and 782 screen widths

https://github.com/Automattic/wp-calypso/assets/27249804/1633ba30-5e22-4492-be18-477298a5af57

📌 ACTIONS
- Triaged

**Comment by nightnei** [comment]
This was fixed in [this PR](https://github.com/Automattic/wp-calypso/pull/83705).
And checked - now it works correctly 👍 
So, closing the issue.

![Image](https://github.com/user-attachments/assets/f88add9c-bdcd-4a90-aed4-febfd0ba3823)
