### ISSUE TITLE
Social First Signup: Log-in link overlaps step progress indicator

### ISSUE THREAD

**Issue by aneeshd16** [Automattic/wp-calypso#82865]
### Quick summary

<img width="1899" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/7d2fe10d-8020-4967-85b2-c916259eaa88">

For flows which do not have `hideProgressIndicator: true` set in their flow definition (flows-pure.js), the login button on the user step overlaps the flow progress indicator (`Step 1 of X`).

Example flows: `/start/do-it-for-me`, `/start/business`, `/start/with-theme/user?theme=covr&theme_type=free`, etc.

### Steps to reproduce

1. Go to https://wordpress.com/start/do-it-for-me in an incognito window.

### What you expected to happen

The login button should not overlap the progress indicator. 

### What actually happened

The login button overlaps the progress indicator.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

We might need some help from design on this. Possible solutions:
1. Move the login link to a different location. 
2. Hide the progress indicator on the user step. However, the next step after the user step will show `Step 2 of X` which can be confusing.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Firefox – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described:

![0X540p.png](https://github.com/Automattic/wp-calypso/assets/27249804/6e3dc51b-dc64-42ca-87da-a61f2f86abe8)

📌 ACTIONS
- Triaged
- FYI @Automattic/vertex for Social Signup

**Comment by heavyweight** [comment]
This was already fixed and it's not reproducible anymore
