### ISSUE TITLE
Suggestion: WordPress import dialog is missing informations

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#82872]
The modal found on `setup/site-setup/importReadyPreview` should output that you can "import everything" also if you will try a trial.

![Image](https://github.com/Automattic/wp-calypso/assets/167611/7c9e9e31-4134-4180-b135-c621b1cb81d4)

**Comment by bogiii** [comment]
We can consider this ticket outdated since we recently removed the Ready screen from the WordPress importer flow.
