### ISSUE TITLE
Plans: remove google analytics feature page

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8288]
We're not using `http://calypso.localhost:3000/plans/features/google-analytics/:siteId:` so let's delete the page, and remove the related routes.

<img width="785" alt="screen shot 2016-09-28 at 9 50 39 am" src="https://cloud.githubusercontent.com/assets/1270189/18923461/1f163148-8561-11e6-869d-f45cd62962c2.png">

We should also remember to remove the link to this page from `http://calypso.localhost:3000/plugins/:siteId:` in the following nudge:

<img width="791" alt="screen shot 2016-09-28 at 9 52 31 am" src="https://cloud.githubusercontent.com/assets/1270189/18923542/766da066-8561-11e6-8300-2f863871fc99.png">

**Comment by artpi** [comment]
This makes me sad :(
Feature pages, never forget !
