### ISSUE TITLE
Plugins: search should use no-results component and show non-installed matching plugins

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#829]
Reported by @rickybanister: Currently we display this when a search of installed plugins yields no results:

<img width="721" alt="screen shot 2015-09-08 at 12 59 36 pm" src="https://cloud.githubusercontent.com/assets/437258/9745095/da43b17e-563d-11e5-91a2-ab34d2dd5a9a.png">

Here's what it looks like when searching all plugins:

![screen shot 2015-11-25 at 8 40 15 pm](https://cloud.githubusercontent.com/assets/11487924/11413259/020b5946-93b5-11e5-886d-b91f0fbb0cfc.png)

Instead we should refactor to use the `no-results` component which looks like:

<img width="703" alt="screen shot 2015-09-08 at 3 26 25 pm" src="https://cloud.githubusercontent.com/assets/437258/9745117/f72e2580-563d-11e5-880c-5a1cfac1eef0.png">

We will need a plugin-related svg for the image. Perhaps using the plugin gridicon in a circle? cc @MichaelArestad 

I think there's also an opportunity here to add a button to the `no-results` text that submits the query to the plugin browser.

This is related to #830 - show non-installed plugins as suggestions for installed plugin search

**Comment by rickybanister** [comment]
I'm thinking about an image for this, but in the meantime I think you can use it without passing an image.
