### ISSUE TITLE
Localized Landing Pages menu bar appears white on light background

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#82908]
### Quick summary

I noticed that the top nav bar on about half of our localized landing page sites is appearing in white text, instead of black.

### Steps to reproduce

1. Open https://wordpress.com/domains/ and observe the dark text color for the navigation
2. Open https://wordpress.com/ar/domains/ and compare

### What you expected to happen

All pages to have the same CSS as the EN site:

![grK4YZ.png](https://github.com/Automattic/wp-calypso/assets/27249804/6bdd586e-ceb0-40c1-9893-f87a3c9cecad)

### What actually happened

![Q2IX2X.png](https://github.com/Automattic/wp-calypso/assets/27249804/b5ed0c0f-6655-45a0-918b-b9c42ff38700)

The nav bar is white on the following localized sites:

- [AR](https://wordpress.com/ar/domains/)
- [HE](https://wordpress.com/he/domains/)
- [ID](https://wordpress.com/id/domains/)
- [IT](https://wordpress.com/it/domini/)
- [JA](https://wordpress.com/ja/domains/)
- [RU](https://wordpress.com/ru/domains/)
- [SV](https://wordpress.com/sv/domaner/)
- [TR](https://wordpress.com/tr/alan-adlari/)
- [ZH-CN](https://wordpress.com/zh-cn/domains/)
- [ZH-TW](https://wordpress.com/zh-tw/domains/)

The body element is missing the `is-style-blue-0-mono` class on the pages with white text.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by cuemarie** [comment]
FYI: @Automattic/martech

**Comment by dzver** [comment]
Tagging @niranjan-uma-shankar for further assignment

**Comment by claudiucelfilip** [comment]
Found a quick fix for this after a flyby look: D126107-code

**Comment by niranjan-uma-shankar** [comment]
@cuemarie This issue has been fixed (props @claudiucelfilip ). Let us know if we can close it, or if you'd like to test it and then close the issue.

**Comment by cuemarie** [comment]
niranjan-uma-shankar thanks for the heads up!  I'll close it out now 👍 (In the future, no need to wait for me, feel free to close if you've fixed too 🙂 )

📌 ACTIONS
- Fixed by D126107-code
