### ISSUE TITLE
Site Editor shows the static page from "Your homepage displays" setting even though Front Page template is used

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#82910]
### Quick summary

When a Front Page template is used (active) in the site, it will be always used as the site homepage. So, opening the Site Editor by default should always show this template.

However, when we set the Settings -> Reading -> "Your homepage displays" to a static page, opening the Site Editor will open that static page, which is unexpected. Even worse, clicking the "Edit template" link (which appears when we click on any editable area of the editor) will open the `Pages` template, not `Front Page` template.

So, the only way to edit the homepage (i.e. the Front Page template) is to open the template manually in the Templates menu.

This is a regression; this used to be correct before. This does not happen in Core. @tanjoymor has a guesstimate of the timing when it possibly started breaking, in a previous discussion where a related issue happened (https://github.com/Automattic/wp-calypso/issues/81928)

> The only anchor in timing that I have is that it was working as expected on August 4th. So it seems to have been a change that took place some time between August 4th and September 19th, which could possibly be further narrowed down by trimming another week off of those two dates, because it was working for a while after August 4th and I noticed the issue a bit prior to creating this GH issue. So maybe something between August 10th and September 7th - ish. At least as a start point for investigating.

cc: @Automattic/lego 

### Steps to reproduce

1. Activate a theme which has Front Page template active (e.g. Kigen)
2. Now go to Settings -> Reading; set the "Your homepage displays" option to anything other than `--Default--` (for example, the About page). Click "Save settings".
3. Go to Appearance -> Editor.

### What you expected to happen

The Front Page template should be shown.

### What actually happened

The About page is shown instead.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by tanjoymor** [comment]
Yes, I can confirm this behavior with the Enroute theme as well, for both Simple and Atomic sites.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO

This is reproducible in a self-hosted environment, not just in WordPress.com. Tested with theme Kigen.  I think this boils down to confusing relationship(s) between block themes, Reading Settings, and then specific themes that have a Front Page template.  I don't see a specific issue about this in /gutenberg at the moment, but there are many that reference these relationships needing improvement.

**Self-Hosted** - Gutenberg 16.8.1 & 16.7.1 exhibit this behavior

https://github.com/Automattic/wp-calypso/assets/27249804/d803d041-606e-44e1-b4e7-2e7820df64f4

📌 ACTIONS
- Triaged
- reported in Core: https://github.com/WordPress/gutenberg/issues/55431

**Comment by fushar** [comment]
Corresponding Gutenberg issue:

- https://github.com/WordPress/gutenberg/issues/56267

**Comment by jp-imagines** [comment]
Ran into an instance of this in 7363302-zd-a8c.

Seems it's been fixed in https://github.com/WordPress/gutenberg/pull/56418, just waiting on that to be released with Gutenberg 17.2 it looks like.

**Comment by ellatrix** [comment]
The core issue (#56267) has been marked as fixed, but I'm not sure if it's fixed here. I'm also a bit confused about what you're expecting. You select a page as your front page, but then don't expect that to be the front page in the Site Editor?

**Comment by tanjoymor** [comment]
@ellatrix 

> I'm also a bit confused about what you're expecting. You select a page as your front page, but then don't expect that to be the front page in the Site Editor?

Not when the front_page.html template is active. This template should “be” the Homepage regardless of any assigned regular page.

**Comment by annezazu** [comment]
Got it! In this case though, the original issue was resolved: https://github.com/WordPress/gutenberg/pull/56418 I just tested and can confirm it works correctly now.
