### ISSUE TITLE
Remove the import-ready preview screen entirely

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#82919]

**Comment by vishnugopal** [comment]
Maybe it's good to keep this import preview screen for the rest of the importers?

1. The non-WordPress importers have a small amount of steps, so we can keep it.
2. If it's a WordPress platform, let's reduce the number of steps.

Related problems:
- The preview for Wix was 404. Maybe we can remove screenshot preview if it's Wix.
- Lots of flickering in the content importers.

**Comment by bogiii** [comment]
> Maybe we can remove screenshot preview if it's Wix.

We can not remove the preview step for the Wix platform because the step after runs the migration immediately, so we are losing moment when user confirms the action.
