### ISSUE TITLE
Live Preview: Apply preselected style variation in the Site Editor

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#82914]
Currently, the `Preview & Customize` feature will ignore the preselected style variation, both in the theme showcase grid and in the theme details page.

### Acceptance Criteria

- [ ] Previewing a theme from the theme showcase grid, with a style variation preselected, should open the Site Editor with the variation applied (EDIT: see https://github.com/Automattic/wp-calypso/pull/86158)

|<img width="338" alt="Screenshot 2023-10-12 at 13 06 51" src="https://github.com/Automattic/wp-calypso/assets/1525580/7b40c152-668c-4a6a-b749-8ecec1e8ec24">|<img width="353" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/d9018129-2f41-42e8-b49d-7827386dca34">|
|-|-|

- [x] Previewing a theme from the theme details page, with a style variation preselected, should open the Site Editor with the variation applied:

<img width="955" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/6d71dbb2-2b82-4ee7-a539-24da45244611">

@Automattic/lego

**Comment by autumnfjeld** [comment]
Let's do a funnel and see if we can track user behavior in Style variation -> Preview & Customize

**Comment by autumnfjeld** [comment]
Maybe @SaxonF  and @richtabor   can help us expedite a core solution for this. :)

**Comment by fushar** [comment]
Jotting down my notes before I leave for the EOY break.

When previewing a theme, we ALWAYS create a `wp_global_styles` custom post type representing the user's global styles. This is true even though we don't eventually activate the previewed theme. So, we can use this to store the preselected style variation.

My idea is as follows:

1. Create an endpoint to update the current theme's style variation (say `POST /themes/mine/style-variation`). It accept the style variation slug as body param.
2. Right before live-previewing a theme with style variations, call the above endpoint, passing along `wp_theme_preview=<the previewed theme>` query param. This way, the above endpoint will treat [as if the previewed theme is the current theme](https://github.com/WordPress/wordpress-develop/blob/d1faee936de9f08b0e496c86f7cd24dfda6739f6/src/wp-includes/theme-previews.php#L87-L89). It will then update the global styles accordingly.
3. When the user is redirected to the Site Editor, it will pick up the already-updated global styles from the previous step, so the user will see the preselected style variation correctly.

**Comment by fushar** [comment]
Shipped (partially) via https://github.com/Automattic/wp-calypso/pull/85945. Live-preview from theme details page is now working.

There is an open PR that tries to support style variation live preview from the Theme Showcase grid here: https://github.com/Automattic/wp-calypso/pull/86158, which is not a blocker. We can continue the discussion there 😄
