### ISSUE TITLE
Republicize: overall design improvements

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#8291]
Hopefully no one else has already tackled this, but I have some feedback and suggestions for the design of the new Republicize feature.
# Current:

![screen shot 2016-09-28 at 12 11 12 pm](https://cloud.githubusercontent.com/assets/618551/18924134/acaa837a-8574-11e6-92cf-0697543b61b6.png)
- [ ] `.posts__list .posts__post-share-service.is-active` is using `black`. Only use color variables.
- [ ]  No bottom margin on the upgrade nudge.
- [ ]  Headers and paragraphs should use same styles as text found in Settings. Look at `form-label` class.
- [ ] Icon should probably be `Share` not the megaphone.
- [ ]  When no account is selected, then the textarea should also be disabled.
- [ ] Share post button should probably be Primary. Maybe align to the right as well.

The accounts would be better suited as buttons that turn on/off. They can be aligned to the left, and if the user has multiple accounts/services, then they would just wrap. It would also be nice to have an additional button for adding accounts
# Quick mockup:

![artboard](https://cloud.githubusercontent.com/assets/618551/18925105/2bf5d5c8-8578-11e6-9474-2aa18a0e5117.png)

@artpi

**Comment by artpi** [comment]
Nice! I like it!

Keep in mind, this code is very rapidly produced and there are more dragons here :)
Also,  if we are doing this, we need to also handle the issue with publicize connection error, like it is inside "sharing" in post editor.

I ignored this problem because there was not enough time, but there should be a button to re-authenticate any ow the connections.

I envisioned it maybe as notice warnings on top, but the connection itself would be greyed - out ?

**Comment by artpi** [comment]
Heads up: https://github.com/Automattic/wp-calypso/issues/8299

**Comment by enejb** [comment]
@drw158 Thanks for the updated designs. One feature that we would still like to implement is some sort of scheduling for the republicizing. 
The thing that is missing from the current design is 
1. a way to schedule the publicize. I assume it would be something like the current scheduling of posts.
2. Displaying of the schedules publicized items. ( Also a way to edit and remove them) 
I good V1 would be to maybe just allow the user to publicize just one item action that is scheduled. 
Do you have any idea what that might look like?

**Comment by keoshi** [comment]
Love this.

**Comment by drw158** [comment]
Updated the design a bit.

- Added scheduling (works same as posting)
- Added social preview component (same as SEO preview)

![screen shot 2016-11-08 at 4 09 40 pm](https://cloud.githubusercontent.com/assets/618551/20119384/f37eb61c-a5cd-11e6-8270-c20eede371db.png)

After you have picked a date:

![screen shot 2016-11-08 at 3 12 20 pm](https://cloud.githubusercontent.com/assets/618551/20119417/115647c2-a5ce-11e6-8039-65eae328c857.png)

After you hit schedule:

![screen shot 2016-11-08 at 4 13 01 pm](https://cloud.githubusercontent.com/assets/618551/20119467/42f39f1e-a5ce-11e6-9ed4-a5f9ca4ddc5e.png)

Example of a success message:

![screen shot 2016-11-08 at 3 42 46 pm](https://cloud.githubusercontent.com/assets/618551/20119489/5527e712-a5ce-11e6-9f97-8c885cea97b0.png)

Sorry, didn't have time to spend a lot on this, so there are some rough edges. There are a lot of scenarios that will need to be thought out I think.

**Comment by drw158** [comment]
Also, can't you already Publicize after you published a post? I found this in the editor:

![screen shot 2016-11-08 at 4 15 35 pm](https://cloud.githubusercontent.com/assets/618551/20119577/b09a3fa0-a5ce-11e6-830a-77e5f594fde9.png)

In any case, it's strange to have the same functionality in both places. We should pick one or the other.
