### ISSUE TITLE
.heic images cannot be previewed in the WP-Admin/Media page on AT sites

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#82968]
### Steps to reproduce

1. Upload a couple of images to your AT site through the Jetpack app for iOS
2. Check the Media section within the app and browser in Calypso and WP-Admin.

### What you expected to happen

The images should show up on the Media page in WP-admin.

### What actually happened

The wp-admin dashboard didn't show the images

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

7146544-zen

**Comment by cometgrrl** [comment]
There's a fix in the Jetpack app to convert these to JPG. See https://github.com/wordpress-mobile/WordPress-iOS/issues/21617

@Robertght do you know what version of the Jetpack app was used?

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I uploaded 3 HEIC images from my iphone via the Jetpack App (version `23.3.1.0`) in a few different ways. All images were converted to JPEG images and are visible in Calypso and wp-admin on my browsers (Firefox and Chrome). The 3 different methods were:

1. Jetpack App > Media Library > Take a photo
2. Jetpack App > Media Library > Choose from (iphone) library
3. Jetpack App > New Page > Image Block > Choose from (iphone) library

**Jetpack App Media Library**

![IMG_82C9D3E417BC-1](https://github.com/Automattic/wp-calypso/assets/27249804/8bfd00cd-b2d1-4850-8eb4-923fff95f54a)

**WP-Admin Media Library**

![Markup on 2023-10-17 at 16:41:21](https://github.com/Automattic/wp-calypso/assets/27249804/2c00f8c6-76af-4adb-9d01-c7ec6f106852)

**Calypso Media Library**

![Markup on 2023-10-17 at 16:41:38](https://github.com/Automattic/wp-calypso/assets/27249804/d9c43dfa-a72a-453d-8b7e-ae0769197235)

📌 ACTIONS
- Requested author feedback

📌 Message to Author
@Robertght can you check to see when the user's images were uploaded? This may be resolved once they update their Jetpack App, given what @cometgrrl mentioned above. Thanks!

**Comment by cuemarie** [comment]
Sent the customer a follow up email here: 7221323-zen

📌 ACTIONS
- Closing as not reproducible

**Comment by Robertght** [comment]
Thank you for testing this! I can confirm the issues was present on my end on Jetpack for iOS 23.2.2, but it's fixed in 23.4.

I'll follow up with the user.
