### ISSUE TITLE
Publicize: publicize-services refactor

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#8299]
- [ ] handle broken connections properly. Requires design ( #8291  ? ). If the connection does not work, button should appear to re-connect the account
- [ ]  Abstract away `publicize-services` component to be more reusable and move it from PostMeta actions to redux ( `my-sites/posts/post-share.jsx` has some good code ) Pinging @aduth so he knows I'll be messing around with that
- [ ] Use that abstracted component in `my-sites/posts/post-share.jsx`

**Comment by aduth** [comment]
Is the idea that the editor will also use the abstracted `<PublicizeServices />` component. In other words, this listing of connections?

![Connections](https://cloud.githubusercontent.com/assets/1779930/18955851/15049782-8627-11e6-8ecc-906c195756a2.png)

Related: #1743, #3277

**Comment by aduth** [comment]
We'd maybe need a `compact` option if so, but otherwise I'd be on board with that.

(cc @folletto for having raised #1743)

**Comment by artpi** [comment]
> Is the idea that the editor will also use the abstracted <PublicizeServices /> component?

Yes, precisely

> We'd maybe need a compact option

Actually, most of the differences can be covered by CSS, but yes, something like this.

**Comment by artpi** [comment]
I'm closing this down since Stark is working on refactoring this section
