### ISSUE TITLE
Reader full_post stats audit: ensure that refreshed full post fires same analytics events as the existing full post

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#8300]
We're replacing the full post view with a new shinier version.

Before launch, we need to ensure that all the existing analytics events are also fired in the new version.

**Comment by samouri** [comment]
Once I check all the boxes (verify they get fired in new full-post view), then the task is complete.
@blowery @bluefuton  can you verify I haven't missed any full-post relevant stats?

Relevant full-post stats
================
1. [ ] calypso_reader_article_closed
1. [ ] calypso_reader_article_commented_on
1. [ ] calypso_reader_article_liked
1. [ ] calypso_reader_article_opened 
1. [ ] calypso_reader_article_unliked 
1. [ ] calypso_reader_author_link_clicked 
1. [ ] calypso_reader_clicked_featured_post 
1. [ ] calypso_reader_comment_author_click 
1. [ ] calypso_reader_comment_reply_cancel_click 
1. [ ] calypso_reader_comment_reply_click 
1. [ ] calypso_reader_edit_post_clicked 
1. [ ] calypso_reader_feed_link_clicked 
1. [ ] calypso_reader_full_post_comments_button_clicked 
1. [ ] calypso_reader_full_post_like_button_clicked 
1. [ ] calypso_reader_permalink_click 
1. [ ] calypso_reader_post_comments_button_clicked 
1. [ ] calypso_reader_related_post_clicked 
1. [ ] calypso_reader_related_post_site_clicked 

All Reader Stats
==========
1. ~~calypso_reader_article_closed~~
1. ~~calypso_reader_article_commented_on~~
1. ~~calypso_reader_article_liked~~
1. ~~calypso_reader_article_opened~~
1. ~~calypso_reader_article_unliked~~
1. ~~calypso_reader_author_link_clicked~~
1. ~~calypso_reader_clicked_featured_post~~
1. ~~calypso_reader_comment_author_click~~
1. ~~calypso_reader_comment_reply_cancel_click~~
1. ~~calypso_reader_comment_reply_click~~
1. ~~calypso_reader_edit_post_clicked~~
1. ~~calypso_reader_feed_link_clicked~~
1. ~~calypso_reader_full_post_comments_button_clicked~~
1. ~~calypso_reader_full_post_like_button_clicked~~
1. ~~calypso_reader_permalink_click~~
1. ~~calypso_reader_post_comments_button_clicked~~
1. ~~calypso_reader_related_post_clicked~~
1. ~~calypso_reader_related_post_site_clicked~~
1. ~~calypso_reader_share_action_picked~~
1. ~~calypso_reader_share_opened~~
1. ~~calypso_reader_share_to_site~~
1. calypso_reader_add_list_clicked
1. calypso_reader_add_tag_clicked
1. calypso_reader_author_on_discover_card_clicked
1. calypso_reader_block_error_dismissed
1. calypso_reader_block_site
1. calypso_reader_blog_preview
1. calypso_reader_create_list_clicked
1. calypso_reader_daily_post_challenge_opened
1. calypso_reader_daily_post_challenge_site_picked
1. calypso_reader_discover_on_empty_Posts_stream_clicked
1. calypso_reader_discover_on_empty_feed_clicked
1. calypso_reader_discover_on_empty_like_stream_clicked
1. calypso_reader_discover_on_empty_list_stream_clicked
1. calypso_reader_discover_on_empty_manage_following_clicked
1. calypso_reader_discover_on_empty_search_stream_clicked
1. calypso_reader_discover_on_empty_site_stream_clicked
1. calypso_reader_discover_on_empty_stream_clicked
1. calypso_reader_discover_on_empty_tag_stream_clicked
1. calypso_reader_discover_on_feed_error_clicked
1. calypso_reader_discover_on_missing_list_clicked
1. calypso_reader_discover_site_followed
1. calypso_reader_discover_site_unfollowed
1. calypso_reader_discover_viewed
1. calypso_reader_empty_manage_following_loaded
1. calypso_reader_filled_gap
1. calypso_reader_follow_error_dismissed
1. calypso_reader_following_loaded
1. calypso_reader_following_on_empty_Posts_stream_clicked
1. calypso_reader_following_on_empty_like_stream_clicked
1. calypso_reader_following_on_empty_list_stream_clicked
1. calypso_reader_following_on_empty_search_stream_clicked
1. calypso_reader_following_on_empty_tag_stream_clicked
1. calypso_reader_following_on_missing_list_clicked
1. calypso_reader_infinite_scroll_performed
1. calypso_reader_list_loaded
1. calypso_reader_load_new_posts
1. calypso_reader_post_gallery_
1. calypso_reader_post_options_menu_
1. calypso_reader_post_reported
1. calypso_reader_reader_list_followed
1. calypso_reader_reader_list_unfollowed
1. calypso_reader_reader_tag_followed
1. calypso_reader_reader_tag_unfollowed
1. calypso_reader_recommendations_on_empty_feed_clicked
1. calypso_reader_recommendations_on_empty_manage_following_clicked
1. calypso_reader_recommendations_on_empty_site_stream_clicked
1. calypso_reader_recommendations_on_empty_stream_clicked
1. calypso_reader_recommendations_on_feed_error_clicked
1. calypso_reader_recommendations_start_loaded
1. calypso_reader_recommendations_start_search_performed
1. calypso_reader_recommended_site_clicked
1. calypso_reader_search_loaded
1. calypso_reader_search_performed
1. calypso_reader_search_suggestion_click
1. calypso_reader_searchcard_clicked
1. calypso_reader_sidebar_list_toggle
1. calypso_reader_sidebar_tags_toggle
1. calypso_reader_site_followed
1. calypso_reader_site_on_discover_card_clicked
1. calypso_reader_site_unfollowed
1. calypso_reader_start_follow_by_url_link
1. calypso_reader_startcard_clicked
1. calypso_reader_tag_clicked
1. calypso_reader_tag_loaded
1. calypso_reader_unblock_site
