### ISSUE TITLE
Theme Showcase: Remove theme descriptions from loading state

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#83008]
It's possible to see theme descriptions when lists of themes are loading. 

![image](https://github.com/Automattic/wp-calypso/assets/545779/8d00690f-2480-43d3-bcc2-98ea6d33b03a)

These shouldn't appear. It'd be better to not show them at all. See p1697222238957639-slack-C03N25JPCE4

**Comment by Copons** [comment]
This is how Firefox handles loading images. We could address it with something as simple as:
```css
img:-moz-loading {
  visibility: hidden;
}
```
...but it's not [very proper](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-loading).

We can instead take the opportunity to improve how theme thumbnails are loaded.

So far, we show a [placeholder](https://github.com/Automattic/wp-calypso/blob/8949a521153bbc8d52ae4301190a0acb3bee9b8b/client/components/theme/index.jsx#L135-L144) (the pulsating grey box) while we [fetch the theme list](https://github.com/Automattic/wp-calypso/blob/8949a521153bbc8d52ae4301190a0acb3bee9b8b/client/my-sites/themes/themes-selection.jsx#L403-L407). Then, we don't do anything special [while we load the screenshots](https://github.com/Automattic/wp-calypso/blob/8949a521153bbc8d52ae4301190a0acb3bee9b8b/client/components/theme/index.jsx#L145-L189).

In practical terms, this means that the loading of a theme card goes like this:
1. Pulsating placeholder of the whole card while the theme is being fetched.
2. Theme card rendered with an empty white thumbnail while the image is being fetched.
3. Render complete.

What if we turned the theme card's image (`.theme__img`) into an `is-placeholder` while the image is being fetched?

There is a [hook](https://github.com/Automattic/wp-calypso/blob/8949a521153bbc8d52ae4301190a0acb3bee9b8b/packages/social-previews/src/facebook-preview/hooks/use-image-hook.ts) in another package that, among other things, also keeps the image's loading status in state. IMHO, we could reuse that logic and adapt it for the theme card.

The end result would be something like this:
1. Pulsating placeholder of the whole card while the theme is being fetched.
2. Pulsating placeholder **of the thumbnail container** while the image is being fetched.
3. Render complete.
