### ISSUE TITLE
Invisible dismiss X on the domain upsell prompt

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#83023]
### Quick summary

There is an invisible X dismiss option on the domain upsell prompt. Since it is invisible, users can't really get rid of them.

I tried to replicate this, but it is hard to know when that prompt shows up, so I couldn't make it appear on my test sites.

7150514-zd-a8c

Here is the screenshot from the user's site: 
![yJ8LDtKBtub01l5qkT5KZigwr5TCS9jH1qPv487U.jpg](https://github.com/Automattic/wp-calypso/assets/84539773/cbfdbbdc-a230-41d7-8de6-ed657e9327de)

### Steps to reproduce

It is visible on the domain upsell prompt.

### What you expected to happen

The X would be visible so people can dismiss the message.

### What actually happened

The dismiss option is invisible.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by csabarakasz** [comment]
I found this P2 post p99Zz8-K5-p2#comment-5130

**Comment by cuemarie** [comment]
Duplicate of https://github.com/Automattic/wp-calypso/issues/79602
