### ISSUE TITLE
Connections Page: update Like Box Text + Link When Facebook is Connected

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#83032]
### Impacted plugin

Social

### What

After connecting Facebook on a WordPress.com site, there is text that says "You can also add a Like Box". There are two issues: 

1. Facebook no longer calls this a "Like Box". It's called a Page Plugin: https://developers.facebook.com/docs/plugins/like-box-for-pages/ 
3. [The support doc it links to](https://wordpress.com/support/facebook-integration/#facebook-like-box) no longer has details about the Like box. The correct doc link is https://wordpress.com/support/facebook-embeds/#facebook-page-plugin

### How

![Annotation on 2023-10-16 at 12-43-13](https://github.com/Automattic/jetpack/assets/30727666/8e3264ed-3592-48f6-b07b-c5c40ce779ab)

This is how it appears after connecting Facebook on a WordPress.com site. I tried to replicate on a self-hosted site with Jetpack connected, but Facebook started treating me as spam and locked me out... so I'm not sure if Jetpack sites also use this text and which support doc link it uses.

**Comment by jeherve** [comment]
Moving this to the Calypso repo, since that's a Calypso UI.

**Comment by Aurorum** [comment]
Took a stab at updating these tips in #86021. :)
