### ISSUE TITLE
Everything Import attempts in Woo Express trial prompt for Business plan purchase only

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#83043]
### Quick summary

If you attempt to use Jetpack Everything Import on a WE trial site you only see a notice indicating that a Business plan is needed. This should say that Business, Commerce, or Woo Express are needed. Or maybe just Woo Express if that's the only thing we want them to convert to

### Steps to reproduce

1. On WE trial site, go to Settings > Import
2. choose WP and try to import from an external site (via url, site needs to be connected to JP)
3. see prompt for Business purchase

### What you expected to happen

should prompt to upgrade to any eligible plan, or at least not just business

for Woo Express, the upgrade page is this:

![image](https://github.com/Automattic/wp-calypso/assets/15944096/8700470a-a6d7-4f1b-ab75-7ff2466385e0)

### What actually happened

![2023-10-16 at 15 41](https://github.com/Automattic/wp-calypso/assets/47717887/191d98be-d436-4a5c-a6eb-a84a1de94b59)

![2023-10-16 at 15 47](https://github.com/Automattic/wp-calypso/assets/47717887/89ace406-c183-4405-816d-d9f0846157a0)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Woo Express – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described:

https://github.com/Automattic/wp-calypso/assets/27249804/66f096c1-7d89-42ec-a44b-540206114a57

📌 ACTIONS
- Triaged

**Comment by davemart-in** [comment]
Closing this out as we don't offer Woo Express anymore.
