### ISSUE TITLE
Jetpack Stats - Incorrect subscriber counts shown

### ISSUE THREAD

**Issue by cometgrrl** [Automattic/wp-calypso#83058]
### Quick summary

My stats dashboard shows incorrect subscriber counts.

Also, this might belong under Jetpack Stats - data.

### Steps to reproduce

- Go to stats -> subscribers.
- View all-time stats.

### What you expected to happen

I expect under all-time stats to see:
- total subscribers = 6
- WordPress.com subscribers = 4
- email subscribers = 2.

### What actually happened

Under all-time stats

- total subscribers = 4
- WordPress.com subscribers = 2
- email subscribers = 2
<img width="645" alt="SCR-20231016-irlj-2" src="https://github.com/Automattic/wp-calypso/assets/86427589/4384e10f-4e7d-4645-86f2-efa420be81c1">

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

Note: Users -> subscribers shows only 5 subscribers, but it seems not be counting me (as a WordPress.com subscriber).
<img width="863" alt="SCR-20231016-isob-2" src="https://github.com/Automattic/wp-calypso/assets/86427589/a1a271a7-cb0f-4397-b91d-1a601fd28fc9">

**Comment by cuemarie** [comment]
Some troubleshooting and discussion here: p1697658105931269/1697657711.253109-slack-CQD1HH4MA

📌 FINDINGS/SCREENSHOTS/VIDEO

This is tough to replicate, and seems to include a couple different aspects of confusing UX. @cometgrrl to work on P2ing those findings for a better discussion.

While troubleshooting, the subscriber count on the site in question eventually updated to the correct count, which suggests a possible caching delay.

📌 ACTIONS
- Closing as not reproducible
