### ISSUE TITLE
Onboarding > Design Picker: certain themes sometimes do not appear in the list while onboarding.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#83069]
### Quick summary

There is an intermittent failure in CI runs where certain themes used by the E2E tests are reported as not present.

So far, we are aware of the following:

- specs/onboarding/signup__free-tailored.ts: Upsidedown
- specs/onboarding/lifecycle__signup-onboarding-launch-cancel.ts: Attar

![image](https://github.com/Automattic/wp-calypso/assets/6549265/a506836b-b486-427c-bcfa-292115c59326)

![image](https://github.com/Automattic/wp-calypso/assets/6549265/47d3bff6-bf73-40a4-8526-46f3bc68ae35)

![image](https://github.com/Automattic/wp-calypso/assets/6549265/9723944b-f1a3-4e1c-b078-f76ff0af0539)

### Steps to reproduce

1. start at `/start` and go through onboarding.

### What you expected to happen

`Upsidedown` and `Attar` themes are available.

### What actually happened

Intermittently (approx. 3-4 in the last 1.5 weeks) the themes are not available in the list when picking the design as part of onboarding.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

This *may* be related to https://github.com/Automattic/wp-calypso/issues/78658 in the sense that it both affects the Design Picker.

**Comment by davemart-in** [comment]
Closing this out as won't fix. I see no additional reports or updates since it was originally reported.
