### ISSUE TITLE
Login: no_calypso Login page shows duplicate "Lost your password" link

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#83115]
### Quick summary

`https://wordpress.com/wp-login.php?no_calypso` shows two `Lost your password?` links. The links are duplicates.

### Steps to reproduce

1. Open https://wordpress.com/wp-login.php?no_calypso
2. Observe

### What you expected to happen

One lost password link

### What actually happened

<img width="550" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/58bd43a1-4eb6-4280-9c2c-fd187759ed12">

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described. 

📌 ACTIONS
- Triaged

📌 Message to Author
Hat tip to @xpurichan for catching this one! p1697205107353399-slack-C0160HSMDQV

**Comment by zaguiini** [comment]
Fix: D162294-code
