### ISSUE TITLE
Assembler: Font Selection UI

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#83130]
# Description

Update the font selection step in the Assembler.
Part of design proposals in [pekYwv-34D-p2#comment-2461 Site Assembler i5 – Dotcom Marvel]

The following is just a mockup not final design:

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/a54814c7-402a-4e1a-b77b-5f05312a9ca8)

❗ As of 18 Oct design discussion is not close to resolution, Lucas & Pablo still discussing.

**Comment by taipeicoder** [comment]
Closing issue since the UI is pretty outdated.
