### ISSUE TITLE
Earn Checklist overriding earnings

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/wp-calypso#83134]
### Impacted plugin

Jetpack

### Quick summary

When viewing the Earn page, the earnings show for a split second, then those are hidden and a checklist shows even if both items have been completed.

### Steps to reproduce

1. Load Earn page on an Atomic site with existing earnings: https://wordpress.com/earn/

### A clear and concise description of what you expected to happen.

On a site that already has purchases made and a payment processor connected, they should see their earnings listed.

### What actually happened

The earnings loads for a split second, then is replaced with the Earn checklist which you cannot dismiss.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

This only appears to happen on Atomic sites, Simple sites are unaffected (the earnings load properly and no checklist appears)

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described:

https://github.com/Automattic/jetpack/assets/27249804/b16a22c4-b7d3-4b85-b079-40241c2ebc17

**Freeze Frame:**

![Markup on 2023-10-17 at 15:47:12](https://github.com/Automattic/jetpack/assets/27249804/1782e310-753a-439a-a311-7349cba8be96)

📌 ACTIONS
- Transferred to /wp-calypso where the Earn page is
- Triaged

**Comment by davemart-in** [comment]
I retested this just now. I throttled my network to 3G and did not see the earnings show through. I'm assuming this has been fixed in another PR? Closing this one out, but happy to re-open it if you're still seeing it.
