### ISSUE TITLE
Theme showcase: Show theme type in the details page

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#83149]
### Description

There are several theme types: Free, Premium, Partner, Community, WooCommerce. We show the theme types in the showcase grid as follows:

![image](https://github.com/Automattic/wp-calypso/assets/1525580/70bff0d2-22da-4c22-914b-743b68002885)

However, in the theme details page, we don't show it:

<img width="771" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/77621925-fb1a-47a5-90ab-2780bb10791a">

This can cause confusion, as explained by Mo in p1695276179218579-slack-C048CUFRGFQ:

> for some additional context I had a user in chat today sending over theme info page links asking if they were “[WordPress.com](http://wordpress.com/)” themes
> Although at a glance, I could tell by the author they were not, it was harder to differentiate Partner and Community themes.
I think having a small nudge - perhaps after the author or over the theme screenshot would help both HEs and users here.

@Automattic/lego @Automattic/t-rex @lucasmendes-design

**Comment by rcrdortiz** [comment]
Hey @lucasmendes-design where do you think it would make sense to place the `Theme Type`? Is it better for it to be text or re-use the same way we're showing it on the Theme List?

**Comment by matt-west** [comment]
Let's place the badge to the right of the theme title.

![image](https://github.com/Automattic/wp-calypso/assets/417538/057d3b9a-2514-4e1b-a4e5-cbf33a3155c9)

We only need to do this for the Partner, Community, WooCommerce, and Sensei badges. An upgrade badge would be redundant as that's already covered by the primary action button. We also display banners prompting upgrades.

Design: RcxiuWYjZGkFRdlWL7L02m-fi-2092_37729
