### ISSUE TITLE
Theme showcase: inconsistent CTA to activate premium themes

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#83154]
### Description

We have two different copies for premium theme activation for Free users:

|Theme showcase grid|Theme details page|
|-|-|
|`Purchase`<br><br><img width="225" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/9c3a0ad5-4f6b-47f2-8f57-98f2479c11d3">|`Upgrade to activate`<br><br><img width="586" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/342fc8ab-718f-4b98-8f1d-3b12865c2ca8">|

I think both should be `Upgrade to activate`; as it is not possible to purchase a single premium theme.

@Automattic/lego @Automattic/t-rex

**Comment by Copons** [comment]
@fushar I'm closing this issue since we are removing the More menu as part of the (many) simplifications of the Theme Tiers project.

Technically, we have already removed it in https://github.com/Automattic/wp-calypso/pull/85315, but the change is behind feature flag. 🙂
