### ISSUE TITLE
Simplify theme activation confirmation modal flow and copy

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#83152]
### Description

When a user wants to activate a new theme, we show this confirmation modal:

![image](https://github.com/Automattic/wp-calypso/assets/1525580/c01391c3-1cf4-4b96-8c4b-fd81fda7237e)

There is a problem with this modal:

1. It's a bit "scary".
2. User could not figure out the name of the old theme easily after activating the new theme.

See also: p1697480548457719-slack-C048CUFRGFQ

### Proposal

1. Remove the checkbox to reduce the number of clicks.
2. Reword the modal copy:

```
Activate ${newThemeName}

You are about to change your active theme from ${oldThemeName} to ${NewThemeName}.
This will replace your homepage, but your old homepage is preserved and can still be accessed. Learn more.


                                    [ Activate ${newThemeName} ]
```

@Automattic/lego @ianstewart

**Comment by ianstewart** [comment]
:shipit:

**Comment by fushar** [comment]
This is shipped.

![image](https://github.com/Automattic/wp-calypso/assets/1525580/d4d48b27-42f1-42f1-a3cd-238ffe9f1464)
