### ISSUE TITLE
Help Center image captions limited to narrow width

### ISSUE THREAD

**Issue by stephhjacq** [Automattic/wp-calypso#83183]
### Quick summary

When using the help center in the Editor, there is an issue with the width of the image captions causing them to display only 1-2 characters ride so they are very difficult to read. 
<img width="1465" alt="Screenshot 2023-10-17 at 6 20 06 PM" src="https://github.com/Automattic/wp-calypso/assets/29288537/dc2d6163-bc4c-4ba2-af34-53adedd2bee9">

### Steps to reproduce

1. Select a block-based theme
2. Go to Appearance > Editor
3. Open Help Center
4. Search for Image Block, scroll and see captions are not wide enough

### What you expected to happen

Captions are same width as images/paragraph and can be easily read

### What actually happened

Captions are very narrow and display vertically (see screenshot above)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described. You can check any guide in the Help Center, such as the Quick Start Guide (linked from the opening window of the Help Center).

https://github.com/Automattic/wp-calypso/assets/27249804/dc492495-e1b8-4d21-976b-c4fdcc768165

It looks like the CSS:

```
.wp-block-image.aligncenter > figcaption {
     display: table-caption;
}
```

may be the cause of this:

https://github.com/Automattic/wp-calypso/assets/27249804/2bc9af67-4bfe-49c6-9dc3-d21f2d10da35

📌 ACTIONS
- Triaged
- FYI @vertex

**Comment by Mfarroq1** [comment]
same issue with theme Baskerville 2 ,  zen-7646459

**Comment by escapemanuele** [comment]
@cuemarie you may have tagget the wrong Vertex, it should be @Automattic/vertex 😄

**Comment by escapemanuele** [comment]
I'm not able to replicate @cuemarie.

@Mfarroq1, looking at the issue it doesn't seem to be related to Help Center?

**Comment by cuemarie** [comment]
Thanks @escapemanuele , and my apologies on the incorrect ping!

I also am no longer able to replicate: 

![CleanShot 2024-08-04 at 14 39 46@2x](https://github.com/user-attachments/assets/6a0db35f-8c7c-4904-b548-0c64ec6f822c)

I'll go ahead and close as not reproducible!
