### ISSUE TITLE
Stats legend is now missing in the chart

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#83189]
### Quick summary

Previously, the stats chart had a legend:
![Screenshot 2023-10-18 at 1 00 19 PM](https://github.com/Automattic/wp-calypso/assets/26772342/c7b08a01-134d-4fbe-a15d-ae06b63e559d)

With the changes in: https://github.com/Automattic/wp-calypso/pull/82903, it is now gone:

![Screenshot 2023-10-18 at 1 00 43 PM](https://github.com/Automattic/wp-calypso/assets/26772342/bd148b7a-597b-47a3-aab2-165d298b3995)

### Steps to reproduce

1. Go to stats
2. Should see legen in chart

### What you expected to happen

See legend in chart

### What actually happened

Don't now

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by dpasque** [comment]
Left comment on the PR that broke it here:
https://github.com/Automattic/wp-calypso/pull/82903#issuecomment-1769071702

**Comment by kangzj** [comment]
Closed with #83197
