### ISSUE TITLE
Prevent Woo Express sites from purchasing Wordpress.com Business or eCommerce plans

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#83247]
### Quick summary

If a user creates a Woo Express free trial site and then upgrades to the WordPress.com eCommerce plan via the direct checkout link or via support by an HE, they face a confusing UX upon plan expiration since their site is stuck in Woo flows.
Considering this, I think we don't intend for these cross-platform plan changes.  

### Steps to reproduce

1. Create a free Woo Express trial site: https://woocommerce.com/express/ 
2. Upgrade your site to the WordPress.com eCommerce plan via the direct link https://wordpress.com/checkout/{free-woo-trial-addres}/ecommerce 
3. Wait for the plan to expire (A8C: Manually change the expiration date of your test site to today).
4. Go to WordPress.com My Site > Choose your site address 

### What you expected to happen

Since the upgrade flow on WooCommerce.com Woo Express sites only allow users to purchase Essential or Performance plans, **I'm assuming we want to prevent Express sites from purchasing .com plans.** 

- **Prevention:** If we don't expect Woo Express trial sites to purchase a .com plan, show an error on the direct cart link (e.g. https://wordpress.com/checkout/{free-woo-trial-addres}/ecommerce) that says this isn't a valid purchase on Woo Express Trail sites and instead purchase a Woo specific plans: Essential or Performance. Additionally, programmatically prevent HEs from manually adding .com plans in internal tools.
- **Plan specific UX:** If we allow Woo Express free trial site upgrades to a WordPress.com Business or eCommerce plan, they should be able to renew their plan ([using the .com flow to ensure a familiar user experience](https://wordpress.com/support/restore-your-site-after-the-plan-expires/#step-1-renew-your-plan)) and not be redirected to https://wordpress.com/plans/my-plan/trial-expired/{site-address}. 
allows

### What actually happened

In the instance I was pinged about, the user has a very Confusing UX:  All site-specific Calypso pages are redirected to https://wordpress.com/plans/my-plan/trial-expired/{site-address}, which says "Your free trial has ended," even though they upgraded to eCommerce months ago, and they're only presented with Woo plans, not .com plans. 

![](https://user-images.githubusercontent.com/29527450/275984102-69e0f8fc-1438-49a9-87ab-b811a870623b.png)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

- initially raised here: https://github.com/Automattic/wp-calypso/issues/83120 
- 7180601-zd-a8c
- p1697564370005209-slack-C03TY6J1A
- p1697567836888679-slack-C036E4KFP2L

**Comment by davemart-in** [comment]
Closing this out as we don't offer Woo Express anymore.
