### ISSUE TITLE
WordPress.com Theme Showcase - Some Community Themes Install Out of Date Versions

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#83251]
### Quick summary

When installing some community themes from the WordPress.com Theme Showcase, some community themes are installing out of date versions.

Affected themes found so far:
* Astra - Installs version 4.1.6, current version is 4.3.1
* Kadence - Installs version 1.1.40, current version is 1.1.48

Tested and found not to be affected:
* OceanWP - current version is installed (3.5.0)
* Hello Elementor - current version is installed (2.8.1)
* Neve - current version is installed (3.7.2)
* Block WP - current version is installed (1.0.5)

### Steps to reproduce

1. Install one of the affected themes from the WordPress.com theme showcase (https://wordpress.com/themes/{siteURL}), ensuring that the theme is not already installed
2. Compare the theme version number to the current release version number.

### What you expected to happen

The current release version of the theme should be installed.

### What actually happened

On some community themes, an out-of-date version is installed.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Workaround noted - Update the theme after install.

**Comment by Copons** [comment]
Can you add more details of the sites affected (or maybe share one of them internally if you prefer)?

I've tried reproducing on an existing Atomic site (transferred sometimes in the last 2 weeks), installing Astra from Calypso, and Kadence from wp-admin. In both cases, they were installed at their most recent version.

**Comment by masperber** [comment]
I wasn't able to reproduce this on a 2nd test site. On the affected site, I deleted the affected themes and could not reproduce a 2nd time. I'll close this for now.
