### ISSUE TITLE
Logged Out Partner Theme: Use monthly variation

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#83255]
The monthly variation is used when adding a theme to the cart via Design Picker. 
On the logged-out theme flow, the annual variation is being used.

The ideal is both experiences behave the same.

**Comment by WBerredo** [comment]
As there was a discussion to decide the monthly variation would be used, we will try to keep both experiences with the monthly variation.

**Comment by WBerredo** [comment]
For the initial investigation, we must check if:

- There is a way to enable monthly values to be shown
- If we want to display monthly values for every Marketplace Theme on the `with-theme` flow

**Comment by WBerredo** [comment]
The plan selection step has an `intervalType` prop that reads from the URL.  It might be an option to pass this property via URL on the logged-out view for themes.

**Comment by WBerredo** [comment]
As the `intervalType` property has to be on the URL, it seems it have to be passed as `providesDependenciesInQuery` instead of `optionalDependenciesInQuery` on the `with-theme` flow.

**Comment by WBerredo** [comment]
Next-steps discussions happening here: p1698701605951899-slack-C048CUFRGFQ

**Comment by cpapazoglou** [comment]
Next steps:
- create a funnel similar to `?46244/2023-10-02/to/2023-10-31 ` , which needs to be adjusted to logged out users
- merge the PR introducing monthly plans for partner themes
- monitor closely for funnel purchase complete percentage increases

**Comment by gcsecsey** [comment]
I've added a funnel where I tried to update the steps to account for logged-out users: `?48174/2023-10-21/to/2023-11-19`

I tested the logged-out flow and for me the following events weren't fired:
- calypso_signup_design_preview_select
- calypso_signup_design_preview_unlock_theme_click
- calypso_signup_design_upgrade_modal_checkout_button_click

So for the funnel above I chose alternative events where we could still track the theme purchase. @WBerredo let me know if we can still use the above events logged-out, because that way it would be easier to re-use or segment the existing funnel.

**Comment by WBerredo** [comment]
> I tested the logged-out flow and for me the following events weren't fired:

> calypso_signup_design_preview_select
calypso_signup_design_preview_unlock_theme_click
calypso_signup_design_upgrade_modal_checkout_button_click

That's right because the Design Picker is not shown once you already have a selected theme in this flow.

**Comment by WBerredo** [comment]
> I've added a funnel where I tried to update the steps to account for logged-out users: ?48174/2023-10-21/to/2023-11-19

@gcsecsey This new funnel might limit our access to only visits coming from the `Themes` page, and don't consider direct accesses that might be coming from search engines.

**Comment by WBerredo** [comment]
I've created the `48300/2023-10-24/to/2023-11-22` funnel that starts on the `with-theme` flow for Marketplace products, let me know your thoughts on it.

**Comment by gcsecsey** [comment]
> I've created the 48300/2023-10-24/to/2023-11-22 funnel that starts on the with-theme flow for Marketplace products, let me know your thoughts on it.

You're rights, these steps capture all the correct visits we'd like to track IMO

**Comment by WBerredo** [comment]
I've update the dates for this funnel: `48300/2023-11-09/to/2023-11-23`

Using 2 weeks as time to evaluate the results of the merged PR 2 weeks from now.
