### ISSUE TITLE
WP-Admin Stats Links Broken on Simple Sites

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#83268]
### Quick summary

Opening the WP-Admin stats dashboard leads to an error on simple sites:

<img width="860" alt="Screenshot on 2023-10-19 at 14:41:02" src="https://github.com/Automattic/wp-calypso/assets/41035049/4ffa6d54-43ea-4fa5-8892-6f8eac4cd505">

A user (#7190998-zen) reported this was working fine earlier today then stopped, forcing them to use the Calypso stats dashboard.

The issue is they do not have access to stats that were most important to them, which were the media stats available in the old dashboard:

<img width="754" alt="Screenshot on 2023-10-19 at 14:42:07" src="https://github.com/Automattic/wp-calypso/assets/41035049/f555b842-e2d8-464d-aef7-789f8944065c">

WP-Admin stats links are now broken as well, such as: 

<img width="444" alt="Screenshot on 2023-10-19 at 14:43:09" src="https://github.com/Automattic/wp-calypso/assets/41035049/68e22f71-bdfe-41cb-a7ad-2e4ba36514eb">

### Steps to reproduce

1. On a simple site, open the WP-Admin stats dashboard. /wp-admin/index.php?page=stats
2. You should see an error: `The page requested does not exist`

### What you expected to happen

The user should see the WP-Admin stats page: 
<img width="1138" alt="Screenshot on 2023-10-19 at 14:45:57" src="https://github.com/Automattic/wp-calypso/assets/41035049/d48d0433-94f2-4bbb-8db7-c15b147bbb59">

### What actually happened

Error page: `The page requested does not exist`

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

Checked a couple of my simple sites and am not able to replicate the issue on `/wp-admin/index.php?page=stats`

![Markup on 2023-10-19 at 15:49:28](https://github.com/Automattic/wp-calypso/assets/27249804/8bb2f896-9b6c-4c2f-97a1-820dd124cc64)

However, I do see the broken-looking icons under the wp-admin view of Pages and Posts:

![Markup on 2023-10-19 at 15:50:39](https://github.com/Automattic/wp-calypso/assets/27249804/b301622a-c070-435d-a5ec-9eec4344fcdc)

---

That said, if I SU into the user's site, I do encounter the page shown above, that reads: `The page you requested does not exist, or you do not have have the necessary privileges to access it. You may return to the dashboard of deep fried movies by clicking here.`

📌 ACTIONS
- In Triage

**Comment by cuemarie** [comment]
@jeherve FYI

**Comment by cuemarie** [comment]
I can access the wp-admin stats page either with a direct link, or by clicking on any stat icon from the Pages/Posts wp-admin view, in the following ways:

- Super admin account, proxy on and off
- Non-admin account, proxy on and off

However when I SU into the user's site, trying either of those methods results in that **The page requested does not exist** warning.

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/why-has-the-wp-admin-index-phppagestats-page-been-removed/?view=all

Several site owners reporting the same issue.

**Comment by worldomonation** [comment]
@jeherve Seeing this was a Jetpack-introduced issue, a couple of things that occurred to me:

1. it seems like we should check the links work in future deployments (in other words, E2E), and;
2. I did not think the wp-admin interface on WordPress.com has custom, dotcom-only things, but this issue obviously proved otherwise. Perhaps we also need to consider adding wp-admin coverage too.

**Comment by jeherve** [comment]
Yeah, it may be worth looking at for sure. I do not know how many site owners were really impacted, how many folks still use wp-admin stats over Calypso stats, so I cannot judge of the actual priority of this, but I do know that stats are a vital part of the WordPress.com experience for many so it may be worth doing it for sure.
