### ISSUE TITLE
DevDocs: Design page fails to load on IE11

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#8329]
#### Steps to reproduce
1. Using IE11, open URL: https://wpcalypso.wordpress.com/devdocs
2. Click the "UI Components" link
#### What I expected

To see the design components
#### What happened instead

A blank screen is displayed, with the following console error:
`Unable to get property 'replace' of undefined or null reference`

The last time I can verify that it worked was two days ago, September 27th, the last time the cross-browser visual diff tests were run.  My hunch is that there's a single component that's breaking it, but #7866 also went in two days ago with sweeping changes to the devdocs structures.  It's likely a combination - a component or two that's breaking things, but not necessarily because they changed in the last two days, since the system around them changed.

cc: @retrofox 
#### Browser / OS version

Windows 7 IE11
#### Screenshot / Video

<img width="969" alt="screen shot 2016-09-29 at 12 22 18 pm" src="https://cloud.githubusercontent.com/assets/7233112/18962577/6f8fac1a-863f-11e6-97c6-684066eb3af8.png">
#### Context / Source
# automated-testing

**Comment by hoverduck** [comment]
My best guess in limited investigation time is that it's tied to https://github.com/Automattic/wp-calypso/blob/master/client/devdocs/docs-example/util.js#L7

**Comment by retrofox** [comment]
Thanks @hoverduck. Working on this following your research.

**Comment by hoverduck** [comment]
Fixed by #8370

**Comment by hoverduck** [comment]
#8370 fixed the root problem, with the page not loading at all, but there are still a couple components that aren't appearing correctly.  I was planning on writing a new issue to track them, but instead decided to just re-open this one for simplicity.

The two components I see a problem with are Tooltip and Popover, which both appear without titles listed:

<img width="577" alt="screen shot 2016-09-30 at 3 45 22 pm" src="https://cloud.githubusercontent.com/assets/7233112/19005179/2698929a-8727-11e6-9569-78c4ecd81a36.png">
<img width="301" alt="screen shot 2016-09-30 at 3 44 59 pm" src="https://cloud.githubusercontent.com/assets/7233112/19005178/269422c8-8727-11e6-93ce-4570c523c18a.png">

**Comment by lancewillett** [comment]
CC @retrofox ^ see note about two components missing titles still.

**Comment by retrofox** [comment]
I'll take a look asap. Thanks @lancewillett for the ping and I'm sorry @hoverduck for the delay.

**Comment by hoverduck** [comment]
@retrofox any chance you've had time to take a look at this?  It's affecting the new Banner component as well https://wpcalypso.wordpress.com/devdocs/design/banner
