### ISSUE TITLE
Task: Update Launchpad documentation

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#83304]
### Details

We've made some important changes to the Launchpad API over the last month or two, with the most important being the addition of the `DefaultWiredLaunchpad` component in #82612. However, we haven't revisited our documentation for adding the launchpad in a new context, so we should do that.

Note that some of this work may need to wait for decisions about renames to our components in https://github.com/Automattic/wp-calypso/issues/83303.

### Checklist

- [x] Ensure that the `packages/launchpad/README.md` is up to date and accurate
- [x] Ensure that our internal documentation is up to date and accurate. Relevant pages needing a final review are listed below:
  - [x] PCYsg-LPB-p2
  - [x] PCYsg-TZL-p2
  - [x] PCYsg-LPB-p2

### Related

#83303

**Comment by daledupreez** [comment]
I've made an initial round of edits to the following internal documentation:
 * I've made some updates to PCYsg-LPB-p2, which already existed
 * I've added a new page at PCYsg-TZL-p2 that captures the broader process of adding a new Launchpad and links to existing, more specific docs for some steps

These changes don't include any updates that will stem from #83303, but incorporating those changes should be pretty straightforward.

**Comment by daledupreez** [comment]
* The `README` updates were tackled in https://github.com/Automattic/wp-calypso/pull/83460, so I am marking that part of this issue complete.
* I've now reviewed the following pages (and made updates as noted) in response to the changes from https://github.com/Automattic/wp-calypso/pull/83460:
  - PCYsg-LPB-p2 - reviewed and updated
  - PCYsg-TZL-p2 - reviewed and updated
  - PCYsg-LPB-p2 - reviewed

**Comment by markbiek** [comment]
I read through those three remaining FG pages and everything seemed good. I didn't find any mistakes and the instructions seemed to make sense.

**Comment by daledupreez** [comment]
Marking this as complete.
