### ISSUE TITLE
Cannot visit WordPress.com Hosted Site from Mainland China

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#83338]
### Quick summary

Visitors from Shanghai China cannot visit any WordPress-hosted sites by using China Telcom

### Steps to reproduce

 "once I turn on the WLAN, it does not work.and "Once I turn off the WLAN, only use data, it works
The ISP of WLAN is China Telcom, and the ISP of data is China mobile.

### What you expected to happen

 "once I turn on the WLAN, it does not work.and "Once I turn off the WLAN, only use data, it works
The ISP of WLAN is China Telcom, and the ISP of data is China mobile.

### What actually happened

 "once I turn on the WLAN, it does not work.and "Once I turn off the WLAN, only use data, it works

### Impact

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

Following is the tracert log by using China Telcom in Shanghai

tracking through up to 30 hops

Route to ttcath.org [192.0.78.24]:

1 2 ms 2 ms 3 ms 192.168.3.1

2 57 ms 58 ms 58 ms 192.168.1.1 [192.168.1.1]

3 63 ms 58 ms 63 ms 1.208.79.218. broad. xw. sh. dynamic. 163data. com. cn [218.79-208.1]

4 60 ms 63 ms 71 ms 61.152.31.145

5 * * * Request timed out.

6 21 ms 18 ms 22 ms 202.97.24.142

7 8 ms * * 202.97.12.186

8 * * * Request timed out.

9 * * * Request timed out.

10 * 395 ms * ae-0.a00. tokyjp10. jp. bb. bin. net [129250.6.48]

11 * 254 ms * xe-0-0-0-0. bbr01. eq01. tok01. networklayer.com [61.213.145.38]

12 * * 434 ms 192.0.78.24

Following is the tracert log by using China Mobile(data)

C:\Users\admin>tracert www.ttcath.org

tracking through up to 30 hops

Route to ttcath.org  [192.0.78.25] :

  1    73 ms    63 ms    62 ms  192.168.43.1
  2     *        *        *     Request timed out.
  3   103 ms   101 ms    91 ms  172.21.0.98
  4    98 ms    91 ms    77 ms  10.11.251.221
  5     *        *        *    Request timed out.
  6    13 ms    16 ms    28 ms  . [221.181.101.245]
  7     *       74 ms     *     . [117.135.43.233]
  8     *        *        *     Request timed out.
  9    94 ms     *        *     221.183.89.45
 10   102 ms    76 ms    78 ms  221.183.89.70
 11     *        *        *     Request timed out.
 12    74 ms    51 ms    60 ms  223.120.3.145
 13    99 ms    85 ms    56 ms  223.120.2.246
 14    64 ms    54 ms    63 ms  ae-9.edge1.Tokyo4.Level3.net [4.68.38.225]
 15     *        *      106 ms  ae1.3501.ear1.Tokyo4.level3.net [4.69.218.106]
 16   119 ms   105 ms   129 ms  8.244.133.6
 17    79 ms    61 ms    49 ms  192.0.78.25

**Comment by ttcath** [comment]
@trey  could you help to ask someone to have a look on this issue? thx!

**Comment by ttcath** [comment]
@tyxla also, pls help to have a look, thx !

**Comment by cuemarie** [comment]
Hi @ttcath 
Please avoid tagging single individuals when opening new issues. Each new issue gets triaged, so any problem you report will get looked at by the person or team who is best positioned to help you. You do not need to @mention specific people to get a reply.

We'll take a look at this issue and comment again once we have some news.

**Comment by cuemarie** [comment]
Hi again @ttcath ,

ISP blocks on websites is not something that WordPress.com developers can bypass.  You'll need to work with your ISP to address or remove the block. For further clarification, please refer to guidance provided by WordPress.com Support Engineers.

---

📌 ACTIONS
- Closed
- Internal note: pcmoY8-eB-p2

**Comment by ttcath** [comment]
Dear @cuemarie  

Sorry to hear the news from yourside. 

Actually, if the visitors who use China Mobile, China Unicom, and China Boardband, can visit WordPress-hosted website, even the users whom use China Telecom (service not provided by Shanghai Telecom) can visit any WordPress-hosted website. Only  Shanghai Telecom users cannot any WordPress-hosted websites. 

I don't think that ISP block any WordPress-hosted websites from their end.  I enclosed the traceroute logs to one of your "happiness Engineers" via Email at  2023/10/24  23:07. Please kindly ask them have a look at them.

Could you ask your teams in case to do the investigation for this issue.
