### ISSUE TITLE
Cannot embed the songs from AudioMack

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#83337]
### Quick summary

Once I want to embed the songs from AudioMack and embed them into a post here, it says: this content cannot be embed.  The issue also affected with spotify. Please fix it at once.

### Steps to reproduce

1 past the link into the proper place of the post.
2 The error says:this content cannot be embed.

### What you expected to happen

The Songs from AudioMack can be embed from any platform as usual.

### What actually happened

this content cannot be embed

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by ttcath** [comment]
@jeherve  Could you please to have a look at this one?

**Comment by ttcath** [comment]
@tyxla pls

**Comment by jeherve** [comment]
@ttcath Please avoid tagging single individuals when opening new issues. Each new issue gets triaged, so any problem you report will get looked at by the person or team who is best positioned to help you. You do not need to @mention specific people to get a reply.

We'll take a look at this issue and comment again once we have some news.

**Comment by jeherve** [comment]
Fixed in r278584-wpcom
