### ISSUE TITLE
Bingbot cannot index (or scrape) WPcom Simple sites

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#83341]
### Predef
Please see this internal P2 for details on our predef: p7DVsv-j5F-p2#comment-48067.

This issue will be updated with additional context as needed.

### Quick summary

We have determined that Microsoft is using its generic `Bingbot` crawler to scrape sites. They have not yet documented a way to block the scraping behavior, so for the moment, we have blocked `Bingbot` from indexing Simple sites via robots.txt directives.

We've created this issue to track support interactions related to this.

### Steps to reproduce

N/A

### What you expected to happen

N/A

### What actually happened

N/A

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by inaikem** [comment]
Initial interactions:

7163433-zd-a8c
7176519-zd-a8c
7197506-zd-a8c
7187505-zd-a8c
7198087-zd-a8c

Update to the P2 here: peGwbA-Oi-p2#comment-1679

**Edit:** looks like the script didn't catch the link above. Opening the comment to edit changes the link automagically

**Comment by inaikem** [comment]
Adding a quick update: [this link to a Sep 2023 announcement](https://href.li/?https://blogs.bing.com/webmaster/september-2023/Announcing-new-options-for-webmasters-to-control-usage-of-their-content-in-Bing-Chat) covers content usage controls.

**Comment by Greatdane** [comment]
7174793-zd-a8c

**Comment by Greatdane** [comment]
7162106-zd-a8c

**Comment by dragstor** [comment]
7151777-zen

**Comment by carolframen** [comment]
7220012-zen

**Comment by ariel-maidana** [comment]
7191656-zd-a8c

**Comment by carolframen** [comment]
7229871-zen

**Comment by Greatdane** [comment]
7205505-zd-a8c

**Comment by Greatdane** [comment]
I think its quite important we get this fixed ASAP, or at least allow a toggle within WordPress.com for users to opt in or out.

**Comment by rinazrina** [comment]
7211878-zd-a8c

**Comment by jerren1327** [comment]
7232284-zd-a8c

**Comment by happychait** [comment]
7253862-zen

**Comment by carolframen** [comment]
7243871-zen

**Comment by ckmccoy2** [comment]
7274083-zd

**Comment by Robertght** [comment]
#7277358-zen | ticket: 7277446-zd-a8c

**Comment by jorpdesigns** [comment]
7293184-zen

**Comment by Aurorum** [comment]
7329176-zen

**Comment by Aurorum** [comment]
7334644-zen

**Comment by aleone89** [comment]
A report of this here: https://wordpress.com/forums/topic/blocking-bingbot-in-robots-txt-why/?view=all#post-4004393

**Comment by Greatdane** [comment]
Another report; 81441-odie

**Comment by ahmadbaig1** [comment]
Another report- 7344690-zen

**Comment by dataspun** [comment]
Another report, self-reporting

**Comment by Aurorum** [comment]
7360087-zen

**Comment by sudeepbaral** [comment]
- [ ] 7381700-zen 

Another report

**Comment by Aurorum** [comment]
7232492-zen

**Comment by jorpdesigns** [comment]
7411333-zen

**Comment by Robertght** [comment]
7412303-zen

**Comment by Aurorum** [comment]
7414145-zen

**Comment by essleeung** [comment]
7471023-zd-a8c

**Comment by ariel-maidana** [comment]
7472791-zd-a8c
This user requested Bingbot to be unblocked.

**Comment by OmarFPG** [comment]
7453782-zen

**Comment by Gustavo-Hilario** [comment]
Another report: 7497842-zen

**Comment by suyogyashukla** [comment]
7493070-zen

**Comment by AminMehrani** [comment]
070306-Zen

**Comment by edequalsawesome** [comment]
Another report: #7560761-zen

**Comment by Aurorum** [comment]
7581254-zen

**Comment by mahfuzurwp** [comment]
7581664-zen

**Comment by AminMehrani** [comment]
7669127-Zen

**Comment by AlexanderSky** [comment]
7658463-zen

**Comment by happychait** [comment]
Closing this issue as the Bingbot is no longer blocked on WordPress.com sites.
