### ISSUE TITLE
[Spike] Logged out Assembler

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#83343]
# Description

We've been chatting about a way for users (rather potential customers) to start with site building as the first step in their WP journey, before signup and account creation.   This issue is for research and a spike to determine possible ways forward.

## Prior & related work
* WordPress playground 
 *  https://developer.wordpress.org/playground/
 * https://wordpress.github.io/wordpress-playground/
* Arthur's prior spikes on logged-out ...... (ask Arthur to add links)

# Goals of spike
- [ ] Publish a kickoff post with plans for the spike and ideas for technical implementation, cross post to dotcom, codep2, 
- [ ] Provide recommendation of the best technical route forward
- [ ] Advise if this would just be a playground, or if a user could move forward into signup and keep what they have created
- [ ] Advice on ETA for a shippable product ( assuming the path is clear is for a shippable project)
- [ ] If practical a workable prototype

**Comment by okmttdhr** [comment]
FWIW, I'm sharing p1689910086056979/1689742595.181679-slack-CRWCHQGUB when I checked if WordPress Playground fits the use case of Live Preview. 🙂

**Comment by taipeicoder** [comment]
@autumnfjeld we don't seem to have a dev assigned to this yet.

**Comment by autumnfjeld** [comment]
@taipeicoder  & @Automattic/lego   I don't know yet when we will start this work.  First we'll complete  https://github.com/Automattic/wp-calypso/issues/83390  and if I remember correctly from a conversation with @ianstewart  the data/observations from that will help us decided how to prioritize a logged-out Assembler.     

I'm moving this issue to the Backlog given the unknowns in starting the work.

-------

These might be interesting reads related, taken from pb6Nl-hfh-p2

> Adam created a thread for pePf1x-70-p2. Also, see the coordination thread for the https://playgroundp2.wordpress.com/2023/11/21/coordination-thread-wordpress-to-playground-import/-.

**Comment by taipeicoder** [comment]
Not planned.
