### ISSUE TITLE
Task: Add view tracking for cards in the Reader 

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#83358]
### Details

As discussed in this thread, p1697802756500309-slack-C03NLNTPZ2T, we want to add view tracking for cards in the Reader, as we can't tell how many cards users are actually seeing, only how many we return and when they trigger infinite scroll. The viewing aspect here is an important piece of basic data that will allow us to get a better sense for how often we expect users to open the underlying content for that card, as we're not seeing that many of those events.

From an implementation perspective, we should be able to leverage the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) much like I did for the theme showcase in https://github.com/Automattic/wp-calypso/pull/68750.

### Checklist

- [x] Add view-based events for cards in the Reader

**Comment by sixhours** [comment]
This has shipped in #83480

**Comment by sixhours** [comment]
I've validated and registered the Tracks event here: https://github.com/Automattic/tracks-events-registration/pull/1922
