### ISSUE TITLE
Assembler: educational copy in the starting blank canvas

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#83379]
Part of https://github.com/Automattic/wp-calypso/issues/82782

Make better use of the blank starting canvas with information about "editing later in the Editor." And make sure the font is big and catches the eye so that users will read it. Maybe have engaging icons that draw the eye to the canvas and cause users to read the information. Also, users that enter the PA via "Design your own" button at the top of the DP may not see the info in the large "Design your own" CTA

CURRENT:
![image](https://github.com/Automattic/wp-calypso/assets/5665959/49952f38-ae71-4494-b5d3-ef1a4cadcb44)

PROPOSED:
![image](https://github.com/Automattic/wp-calypso/assets/5665959/655f4f49-1b5f-4471-9fd9-9c79c2bd9d13)

Naturally we will not include "Pick additional site pages" until that feature is ready to ship.

# Dev Tasks
- [x] See Tv3pYqA3EcRfiXC31IxrXE-fi-2593:16699#594790356
- [x] Update new copy as a "mockup", put  screenshot in a comment in this issue and tag Autumn, Ian, & Lucas in slack with link to the comment.  Then we will determine if additional design is needed (e.g. font size, or other adjustments).
- [x] When the copy and layout is approved, we can submit translations.
- [ ] Make any follow up issues if we decide to do something additional, more elaborate.

@Automattic/lego

**Comment by autumnfjeld** [comment]
Here is a mockup I tried in the browser. 

![image](https://github.com/Automattic/wp-calypso/assets/5665959/956afbe9-6add-473f-86de-c980c80efa22)


Copy:
Welcome to your home page.
It's time to bring your site to life.

Start by selecting your header, section, and footer patterns. Then you'll pick colors and fonts to add your personal style. Once you've got the basics of the design set up, you'll edit and cusomize the content in the Site Editor. Need a more detailed walkthrough?  [Learn more](https://wordpress.com/learn/courses/quick-launch/design-your-homepage/#Now-let's-design!)

**Comment by autumnfjeld** [comment]
Here is another attempt, also looking not great. :( 

![image](https://github.com/Automattic/wp-calypso/assets/5665959/4326433c-b625-498c-9304-1e0221c04b07)

**Comment by autumnfjeld** [comment]
@lucasmendes-design  I'm going to need your help.    @alaczek shared this image and it has the right "idea".   While I don't think we can put an image in the canvas, we can take a cue from the cute icons and the bullet list.
![image](https://github.com/Automattic/wp-calypso/assets/5665959/63b9be58-6bce-4966-927b-f70504346d02)
 
So something like my terrible mockup 😆  but with cute icons:
![image](https://github.com/Automattic/wp-calypso/assets/5665959/84f0e645-288d-44e4-98d4-27e01b265438)



COPY:

Welcome to your homepage

Bulleted list:
* Select patterns for your homepage
* Choose your colors and fonts
* Continue to the Editor to customize content



Then, after we add pages:
* Select patterns for your homepage
* Choose your colors and fonts
* Add additional site pages
* Continue to the Editor to customize content

**Comment by lucasmendes-design** [comment]
Basically, we want to have similar copy on CTA and the empty state, right? I did a version with this in our Figma file. I think we need to reduce/change the last option. Tv3pYqA3EcRfiXC31IxrXE-fi-2593:16699#594422281

**Comment by arthur791004** [comment]
Proposing https://github.com/Automattic/wp-calypso/pull/83633 to update the copy 🙂

**Comment by taipeicoder** [comment]
Closing via #83633
