### ISSUE TITLE
Expand on click option for Image Block working incorrectly

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#83380]
### Quick summary

When an Image Block above any other has "Expand on click" selected, it causes all images below it to expand on click.
https://wordpress.com/support/wordpress-editor/blocks/image-block/#expand-on-click

### Steps to reproduce

1. Open any post or page.
2. Add two images using Image Blocks.
3. Toggle the "expand on click" option for the image nearest the top of the post or page.
4. Leave the option off on the image below it.

### What you expected to happen

Expected for only the image with the "expand on click" option to expand on click.

### What actually happened

The image and all images below will expand on click. However, the inverse of this does not incur. If an image below the first image has expand on click toggled on, but the top image does not, the top image is not affected.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I've produced this on pages and posts, all block themes I have tried, and for simple and atomic sites.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described above - images following an image block with `Expand on click` enabled also behave that way even with the setting disabled.

**Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/40266f30-69d4-4b1e-808d-d452830ecf77

Simple behaves the same way.  Test site outside of Dotcom does not reproduce the issue.

📌 ACTIONS
- Triaged
