### ISSUE TITLE
Post management bubble width issue

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#834]
On the post management screen (My Sites > Blog Posts) you can sometimes get UI overlapping at small screen sizes:

![bubbles](https://cloud.githubusercontent.com/assets/1277682/11418317/a7307030-9416-11e5-9068-aac18dc3c1dd.jpg)

Note how the dropdown is squashed next to the 'Only me' button, and the post count exceeds the width and drops underneath the line in the dropdown itself.

Note that I've artificially changed the number of posts in this example, but given a different locale for 'published' then the effect could happen easier.

**Comment by lancewillett** [comment]
I wasn't able to repeat this. John, feel free to re-open if you see it again (and include your device, OS, and the steps you took to see this.)
