### ISSUE TITLE
Staging Sites: newly created staging sites empty

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#83412]
### Quick summary

A staging site was created and the restore/sync process failed, leaving an empty site
- HE attempted to delete the site but was not able to until staging site plan removed from site in SA
- before that, the deletion at least partially completed, resulting in a free simple site
- HE then created new staging site which was also empty
- HE attempted to copy content over with new sync feature
- at some point this resulted in an IDC on the staging site (i.e. JP connected to blog ID of live site)

I manually resolved IDC and site appears okay now. Issues may have been related to an issue with `recaptcha-for-woocommerce`

More context here: p9F6qB-dzo-p2
I don't know of any other sites that experienced a similar issue at present

note: no restores present on 2 deleted staging sites according to RWDB

@upwardmomentum84 Can you please check the report here and correct anything that's not correct/clear

### Steps to reproduce

On site in question
1. create staging site and it will end up empty

### What you expected to happen

current state of live site should be copied over

### What actually happened

site was empty

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by upwardmomentum84** [comment]
@Nic-Sevic looks good to me.

**Comment by upwardmomentum84** [comment]
Another instance that looks to be the same issue. I was able to work around it using the same work around steps mentioned above.

Site: https://starjuwelier.nl/
Staging: https://staging-8fbd-starjuwelier.wpcomstaging.com
Atomic Request: p9F6qB-dBI-p2

**Comment by upwardmomentum84** [comment]
Upon further testing, I am able to replicate this issue on all of my sites with the eCommerce plan. I tested with a site I have had for awhile as well as with a brand new one and see these messages after trying to create a staging site. The error `Failed to add staging site: Site can not be transferred. Invalid transfer status`appears after about a minute. After another minute the `Staging site added` message appears. This is the case for the monthly and annual eCommerce plans. I didn't test other eCommerce plan variants.

![CannotAddStagingSite-2](https://github.com/Automattic/wp-calypso/assets/93800099/bfb9fbc5-33b7-4c6a-b68a-dabe9d4badba)

I also tested with two of my sites that have a Business plan and was able to create a staging site as expected.

**Comment by wojtekn** [comment]
@upwardmomentum84 thanks for that find and for sharing the steps. I reproduced the issue with 'Failed to add staging site: Site can not be transferred. Invalid transfer status' displayed for Commerce plan staging sites and prepared the fix (D126545-code).

**Comment by wojtekn** [comment]
@Nic-Sevic @upwardmomentum84 the issue is fixed now.

**Comment by upwardmomentum84** [comment]
Thanks for the quick resolution! I can confirm I'm able to successfully create an eCommence plan staging site now.

**Comment by cuemarie** [comment]
Thank you @wojtekn !

📌 ACTIONS
- Closed as fixed by D126545-code
