### ISSUE TITLE
Change "[Status] Escalated" to "Priority Review Triggered"

### ISSUE THREAD

**Issue by cometgrrl** [Automattic/wp-calypso#83428]
Currently, `[Status] Escalated` is used to track bugs that get alerted in `#dotcom-triage-alerts`. We'd like to reclaim this label to use it for tracking issues that are escalated through `#dotcom-escalations` instead, so that we can do better long-term reporting on true escalations.

To do this, we need to:

- [x] Rename the `[Status] Escalated` label to `Priority Review Triggered`.
- [x] Update the repo gardening scripts to apply and check for the new label, `Priority Review Triggered`.
- [x] Create a new label `[Status] Escalated`.

Additional context: p1697744833053559/1697338479.852949-slack-C03FKS5989J

**Comment by cometgrrl** [comment]
@jeherve Could you help us with this?  It's not urgent, but it'd be nice to have this change in the next few weeks.

**Comment by jeherve** [comment]
Reopening, this got closed automatically during testing in my fork.
