### ISSUE TITLE
Headers: Remove extra margin below header in mobile

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#83439]
> We have some unnecessary space here:
> 
> ![image](https://github.com/Automattic/wp-calypso/assets/1044309/f98794f5-9d39-4467-8267-b188d2559d61)
> 
> ![image](https://github.com/Automattic/wp-calypso/assets/1044309/79d68e5f-942d-4cc3-bcb1-248645caaa62)
> 
> ![image](https://github.com/Automattic/wp-calypso/assets/1044309/c7335f84-56bb-47f8-b485-a4e1ef9081b0)
> 
> ![image](https://github.com/Automattic/wp-calypso/assets/1044309/b5b76afd-6f05-44d2-9272-6d32c73a1d5e)
> 
> ![image](https://github.com/Automattic/wp-calypso/assets/1044309/130b4027-c981-4cfa-853c-72ea77900758)
> 
> 
> ## Fix suggestion
> 
> I'm wondering if we should remove [that default 32px margin-bottom](https://github.com/Automattic/wp-calypso/blob/update/FormattedHeader-to-NavigationHeader/client/components/navigation-header/style.scss#L9):
> 
> ![image](https://github.com/Automattic/wp-calypso/assets/1044309/1ff4303f-04de-4a20-a7ba-2f261e497ae9)

_Originally posted by @paulopmt1 in https://github.com/Automattic/wp-calypso/pull/83328#pullrequestreview-1695682381_

**Comment by lsl** [comment]
Someone fixed this a while ago now
