### ISSUE TITLE
Activating hosting features button text is squashed

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#83446]
![Image](https://user-images.githubusercontent.com/811776/277852229-b9801d62-2550-4bb9-b118-68afcde9d671.png)

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
![Screenshot 2023-12-07 at 5 15 26 PM](https://github.com/Automattic/wp-calypso/assets/44726232/24026c57-83c9-4642-bd5d-732cbbabd678)

📌 ACTIONS
- Triaged

**Comment by davemart-in** [comment]
I'm struggling to find this screen. @lsl mind sharing how you replicate this issue?
