### ISSUE TITLE
Change Doc Link in Newsletter Settings

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#83453]
### Quick summary

In Newsletter Settings there is a link that says "Learn more about sending emails" that would be best to update to a different doc.

### Steps to reproduce

1. Go to Settings → Newsletter
2. Scroll down to the Email section and click "Learn more about sending emails."

![Screenshot 2023-10-25 at 4 32 33 pm](https://github.com/Automattic/wp-calypso/assets/30727666/0c1f2dc1-c0c5-4ded-9574-ce79ef81d85e)

### What you expected to happen

I expected to arrive here: https://wordpress.com/support/subscriptions-and-newsletters/

### What actually happened

I arrived here: https://wordpress.com/support/launch-a-newsletter/

This doc is tailored for the onboarding launch flow for newsletters, not for sending emails from existing sites.

The other doc I shared is more appropriate for an audience of existing users and contains the information about sending emails from a WordPress.com site.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 ACTIONS
- Triaged
- FYI @Automattic/zap
