### ISSUE TITLE
Loading Manage Patterns fails with iframe issues

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#83472]
### Quick summary

Menu items to manage patterns from inside the post-editor are broken, leading you to a browser error page.

#### Editor menu

1. (In firefox, ensuring you use the calypso rather than classic view to manage posts)
2. Go to the **post editor**
3. Click the three-dot/meatball menu at the top right
4. Click Manage patterns

#### Block-specific menu

1. (In firefox, ensuring you use the calypso rather than classic view to manage posts)
2. Go to the **post editor**
3. Insert a block
4. Click on the three-dot/meatball menu for that block
5. Click "Create pattern"
6. Fill out the form ensuring you create a synced pattern
7. The block will now be a pattern block, click on its three-dot/meatball menu
8. Click "Manage patterns"
9. The browser might (repeatedly) warn you about confirming you want to leave, choose leave page

### What you expected to happen

A page to load listing all of my patterns allowing me to manage them.

### What actually happened

The page displays a full screen iframe of `https://deantest772.wordpress.com/wp-admin/post-new.php?calypsoify=1&amp;block-editor=1&amp;frame-nonce=933a230d97&amp;origin=https%3A%2F%2Fwordpress.com&amp;environment-id=stage&amp;support_user=&amp;_support_token=&amp;in-editor-deprecation-group=1` but this is blocked from loading and instead displays:

> Firefox Can’t Open This Page
>
> To protect your security, deantest772.wordpress.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

Console says:
> The loading of “https://deantest772.wordpress.com/wp-admin/site-editor.php?path=%2Fpatterns” in a frame is denied by “X-Frame-Options“ directive set to “sameorigin“.

Clicking "open site in new window" opens https://deantest772.wordpress.com/wp-admin/site-editor.php?path=%2Fpatterns

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple (haven't tested atomic).

It's likely a wpcom specific problem due to the way we iframe the editor.

### Logs or notes

The work around is to ignore the scary text and press the button saying "Open site in new window", it's easily done but the browser warning looks scary and we look broken.

See conversation at p1698185155235349-slack-C0160HSMDQV

Only tested in Firefox, but probably a problem in other browsers too.

**Comment by dsas** [comment]
Looks like it's supposed to be handled here: https://github.com/Automattic/wp-calypso/blob/29a6d24ead8f072acfab7bf3098e0ee70dc610fb/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L563

or here: https://github.com/Automattic/wp-calypso/blob/29a6d24ead8f072acfab7bf3098e0ee70dc610fb/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L666

**Comment by dsas** [comment]
It's the second of the above. A watch is set on the element matching `.interface-interface-skeleton ~ .popover-slot` and when it has nodes added or removed, that code is triggered. Menus use popovers to render, so it worked for both [block-specific menus](https://github.com/WordPress/gutenberg/blob/820b13599bf12f5efa472e36a780cd63e86a67b3/packages/patterns/src/components/index.js#L12) and for the [block-editor menu](https://github.com/WordPress/gutenberg/blob/820b13599bf12f5efa472e36a780cd63e86a67b3/packages/edit-post/src/plugins/index.js#L56) itself.

I **think** that the problem occurs because no element now matches that rule. When the code runs after the editor is loaded `.popover-slot` does not exist. That element is created on demand, if at all. Furthermore, the same is true of the "fallback" element `components-popover__fallback-container`. 

These changes are from https://github.com/WordPress/gutenberg/pull/53889 (GB16.6) though, so it's surprising this has only just been noticed 🤔

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described:

https://github.com/Automattic/wp-calypso/assets/27249804/2f5d1dfa-75b1-403f-9319-74d6e71181c6

📌 ACTIONS
- Triaged

**Comment by cuemarie** [comment]
This has been raised for awareness here: p1698331315179469-slack-CBTN58FTJ

**Comment by dsas** [comment]
I've fixed the post-editor menu problem in #83474. I haven't yet fixed the problem for individual pattern block menus.

**Comment by BogdanUngureanu** [comment]
Looks like the issue is reproducing again. Reported by a user in 7326887-zd-a8c

**Comment by caitlindawn** [comment]
Reported in 7338010-zen

**Comment by AnjanaV93** [comment]
Another report here: 7477388-zen

**Comment by lsl** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/93848
