### ISSUE TITLE
Atomic Sites suddenly missing fonts in Site Editor

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#83484]
### Quick summary

Some themes are missing font choice in the Site Editor. This issues seems to only affect atomic sites. 

I tested using the theme `Fewer` on a simple site and the issue is not happening there but occurs on my test atomic site.

Reported in this Slack thread: p1698262661978439-slack-C03TY6J1A

![MIssingFonts](https://github.com/Automattic/wp-calypso/assets/93800099/de216205-62e6-41b7-8958-432ef4ab82fb)

### Steps to reproduce

1. Activate Tsubaki
2. Navigate to Appearance > Editor
3. Open Styles sidebar > Typography > choose an element.
4. Click the font dropdown and notice there are only a few fonts showing.

### What you expected to happen

More fonts to be listed.

### What actually happened

Only two fonts (Tsubaki) show. I tested with Tazza and see three fonts.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

Tested working around this with adding custom CSS to set the font and it does appear to work.

- Tested with all with all plugins deactivated except for Jetpack and Akismet. 
- Also turned off all performance options in Jetpack.

Even with the above, I'm only seeing limited font options.

**Comment by happychait** [comment]
7216118-zen

**Comment by msilbers** [comment]
reported in 7216062-zen for Tsubaki

**Comment by paxblueribbon** [comment]
7216015-zen

**Comment by mikeicode** [comment]
This is a pretty serious issue for BBE. We have built many sites on AT using TT3 child themes, and within the last few hours, the fonts we chose for the design of the site have stopped working. We spot-checked a few sites from the last couple of months, and they have the issue, as well as others we recently sent (which are still within the BBE refund window).

A couple of examples from yesterday and today, you can compare the screenshots with the current sites:
pdEkSe-60W-p2
pdEkSe-5Zw-p2

**Comment by msilbers** [comment]
reported in 7216105-zen for Masu and Exmoor

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
To replicate, I created a brand new site on a Business plan and chose the theme **Fewer**. Before activating advanced features under Hosting Configuration (going AT), I had a full list of Fonts available in the Styles pane:

![Markup on 2023-10-25 at 15:15:43](https://github.com/Automattic/wp-calypso/assets/27249804/0f73129f-51a4-47b5-9b47-d877cc6aa2d8)

I then AT'd the site and reloaded the editor, and only had ~5 fonts available: 

![Markup on 2023-10-25 at 15:20:07](https://github.com/Automattic/wp-calypso/assets/27249804/b8659be9-08ff-43a8-ae62-326dca8e6c45)

Switching to TT3 on the same theme shows limited fonts there as well:

![Markup on 2023-10-25 at 15:22:43](https://github.com/Automattic/wp-calypso/assets/27249804/e52547bb-d59d-4e9b-b489-f203de287b67)

📌 ACTIONS
- Triaged

**Comment by arinoch** [comment]
Reported in 7215831-zd-a8c using Bitacora. If the user switches browsers, fonts show up in the editor, but do not show up on the live site. IF they're using their usual browser (note: this is a transferred chat so I don't have their current browser info), no custom fonts appear in the editor or on the live site.

**Comment by cuemarie** [comment]
Escalation thread: p1698272685592449-slack-C02FMH4G8

**Comment by happychait** [comment]
7216873-zen

**Comment by mahfuzurwp** [comment]
reported in 7215944-zen

**Comment by helenaartmann** [comment]
7216287-zen

**Comment by mahfuzurwp** [comment]
reported in 7216554-zen
