### ISSUE TITLE
Fluid width notice has oddly placed close button

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#835]
When the page is fluid width (as in the desktop app) and you have a notice it puts the close button at a fixed width position:

![sharing](https://cloud.githubusercontent.com/assets/1277682/11419539/f40a523c-941f-11e5-8b59-20c69f8b1f67.jpg)

Note this was when disconnecting a sharing service.

**Comment by fabianapsimoes** [comment]
This is being addressed in https://github.com/Automattic/wp-calypso/issues/214. Closing as duplicate.
