### ISSUE TITLE
Assembler: Upsell screen with price & copy update

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#83504]
🚧   Waiting for final version

CURRENT IN PROD

<img width="1708" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/1500d804-8f27-4c4b-a768-a8e800652bc0">

PROPOSED

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/a53e39b6-df18-4433-b82f-d75875076a0d)

Tv3pYqA3EcRfiXC31IxrXE-fi-2595%3A43148

**Comment by autumnfjeld** [comment]
@Automattic/lego  work can start on this, just note the Figma inconsistency:

The title of this page should remain "Premium styles",   but the side panel content should be like this:

![image](https://github.com/Automattic/wp-calypso/assets/5665959/25a43532-58f0-48b1-acbb-f825e26ecc15)


Note: Tv3pYqA3EcRfiXC31IxrXE-fi-2595:43148#594419612

**Comment by arthur791004** [comment]
I can start on it this week 🙂

**Comment by arthur791004** [comment]
Proposed https://github.com/Automattic/wp-calypso/pull/84180 for this one

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/84180
