### ISSUE TITLE
Atomic: Video details show a file size of 0,00 B for videos uploaded to media library

### ISSUE THREAD

**Issue by tiniacoleyba** [Automattic/wp-calypso#83512]
### Quick summary

The file size of videos uploaded to the WordPress.com atomic sites media (business and eCommerce plans) is always shown as zero in the video details even though the file size for those videos is greater than zero (WordPress.com dashboard -> media -> videos -> select video -> edit -> scroll and find the video file size).
<img width="1310" alt="wpcom-videopress-videofile-size-not-showing-bug2" src="https://github.com/Automattic/wp-calypso/assets/45241190/1deeeb2a-8d7a-4320-affb-407d87932aa1">

I reproduced this bug on the atomic site www.cursatica.com and attached a screenshot.
The bug happens to every video uploaded the same way to that site. 
You can reach out to @danielbachhuber for more technical details since we went together through a support session, and he could verify the bug in that site.

### Steps to reproduce

1. Go to an Atomic WordPress.com website (You can use the www.cursatica.com atomic site to verify the issue)
2. Go to the WordPress dashboard and select media.
3. Select a video and edit it
4. Check the video file size. It is shown as zero. (See the screenshot in the issue description.)

### What you expected to happen

I expected the file size of the video to be shown in the video details (select the video on the media tab and click edit for the video details to appear) once the video was fully uploaded to the media. Still, I saw the file size to be zero for all videos uploaded when those videos have a considerable file size.

### What actually happened

The video file size was always shown as zero for all the videos uploaded to the site.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
On my AT test site, uploaded videos show the File Size as `0,00 B` as well.  
- (Note for testing: Newly uploaded videos take a bit of time to update before they show the file size field at all)

**Newly Uploaded Video** - File Size on my device: 25.4MB

<img width="550" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/0ccbb4b6-dd11-47e2-9fba-bd3f9ae82286">

---

I'm wondering if this is related to how the [VideoPress storage on AT](https://wordpress.com/support/space-upgrade/#reduce-used-storage) works:
> On Business or Commerce plans with plugins installed, videos added through VideoPress do not count against your storage allotment.

📌 ACTIONS
- Triaged
- @jeherve can you weigh in here - is the 0,00 B file size expected, given the VideoPress feature on AT?

**Comment by jeherve** [comment]
> can you weigh in here - is the 0,00 B file size expected, given the VideoPress feature on AT?

I'd say it's not expected, no; it should be displayed properly.

That said, I cannot even to the screen y'all see on your sites. I don't have any "file size" info on my end:

<img width="1177" alt="Screenshot 2023-10-27 at 13 06 11" src="https://github.com/Automattic/wp-calypso/assets/426388/7ec8231d-b7c9-425e-a7ca-9a19480be717">
 
That may be the expected behavior:

https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/client/post-editor/media-modal/detail/detail-file-info.jsx#L80-L85

Could you try to open your browser's network tools (Cmd+Opt+E in Firefox), and filter for "XHR" and `videos/`:

<img width="1097" alt="Screenshot 2023-10-27 at 13 14 04" src="https://github.com/Automattic/wp-calypso/assets/426388/9769f137-0c51-457f-af04-5ba02132f90c">

Then open the media and inspect the request that is fired:

<img width="1348" alt="Screenshot 2023-10-27 at 13 15 16" src="https://github.com/Automattic/wp-calypso/assets/426388/274f186d-407a-45f6-9c93-f6532da26217">

You'll be looking at info about the file size in there.

**Comment by cuemarie** [comment]
>That said, I cannot even to the screen y'all see on your sites. I don't have any "file size" info on my end:

I saw the same thing for about 10 minutes after uploading a test video, and then the File Size appeared (but remained at 0,00 B). Now that some time has passed, can you check to see if the file size field shows on the vid you uploaded?

**Comment by cuemarie** [comment]
>Could you try to open your browser's network tools (Cmd+Opt+E in Firefox), and filter for "XHR" and videos/
>Then open the media and inspect the request that is fired:
>You'll be looking at info about the file size in there.

Here's what I'm seeing - no file size as far as I can spot:

![Markup on 2023-10-27 at 10:57:14](https://github.com/Automattic/wp-calypso/assets/27249804/b82eb653-d852-4223-a76c-4d226064cf2e)

<details> 
<summary> Raw code </summary>

```
{"guid":"WB9tLljk","title":"Rainy Window","description":"","width":1920,"height":1080,"duration":50560,"display_embed":true,"allow_download":false,"rating":"G","poster":"https:\/\/videos.files.wordpress.com\/WB9tLljk\/production_id-5197762-1080p_mp4_hd_1080p.original.jpg","original":"https:\/\/videos.files.wordpress.com\/WB9tLljk\/production_id-5197762-1080p.mp4","watermark":false,"bg_color":false,"files":{"std":{"mp4":"production_id-5197762-1080p_mp4_std.mp4","original_img":"production_id-5197762-1080p_mp4_std.original.jpg","thumbnail_img":"production_id-5197762-1080p_mp4_std.thumbnail.jpg"},"avc_240p":{"mp4":"production_id-5197762-1080p_mp4_avc_240p.mp4","original_img":"production_id-5197762-1080p_mp4_avc_240p.original.jpg","thumbnail_img":"production_id-5197762-1080p_mp4_avc_240p.thumbnail.jpg","hls":"production_id-5197762-1080p_mp4_avc_240p.master.m3u8","dash":"production_id-5197762-1080p_mp4_avc_240p.dash.mpd"},"dvd":{"mp4":"production_id-5197762-1080p_mp4_dvd.mp4","original_img":"production_id-5197762-1080p_mp4_dvd.original.jpg","thumbnail_img":"production_id-5197762-1080p_mp4_dvd.thumbnail.jpg","hls":"production_id-5197762-1080p_mp4_dvd.master.m3u8","dash":"production_id-5197762-1080p_mp4_dvd.dash.mpd"},"hd":{"mp4":"production_id-5197762-1080p_mp4_hd.mp4","original_img":"production_id-5197762-1080p_mp4_hd.original.jpg","thumbnail_img":"production_id-5197762-1080p_mp4_hd.thumbnail.jpg","hls":"production_id-5197762-1080p_mp4_hd.master.m3u8","dash":"production_id-5197762-1080p_mp4_hd.dash.mpd"},"hd_1080p":{"mp4":"production_id-5197762-1080p_mp4_hd_1080p.mp4","original_img":"production_id-5197762-1080p_mp4_hd_1080p.original.jpg","thumbnail_img":"production_id-5197762-1080p_mp4_hd_1080p.thumbnail.jpg","hls":"production_id-5197762-1080p_mp4_hd_1080p.master.m3u8","dash":"production_id-5197762-1080p_mp4_hd_1080p.dash.mpd"}},"file_url_base":{"http":"http:\/\/videos.videopress.com\/WB9tLljk\/","https":"https:\/\/videos.files.wordpress.com\/WB9tLljk\/"},"blog_id":194192341,"post_id":1304,"is_private":false,"privacy_setting":2,"privacy_details":{"provider":"auth","title":"This video is private","unauthorized_message":"Unauthorized"},"private_enabled_for_site":false,"upload_date":"2023-10-26T18:40:42+0000","finished":true,"files_status":{"std":{"mp4":"DONE","ogg":"DONE"},"avc_240p":{"mp4":"DONE"},"dvd":{"mp4":"DONE"},"hd":{"mp4":"DONE"},"hd_1080p":{"mp4":"DONE"},"hd_1080p_compat":null,"hevc_1440p":null,"vp9_1440p":null,"hevc_2160p":null,"vp9_2160p":null},"subtitles":[],"tracks":[],"adaptive_streaming":"https:\/\/videos.files.wordpress.com\/WB9tLljk\/production_id-5197762-1080p_mp4.adaptive_4.m3u8","adaptive_streaming_r":null,"format_meta":{"std":{"codec":"avc","label":"224p","vertical_lines":224},"avc_240p":{"codec":"avc","label":"240p","vertical_lines":240},"dvd":{"codec":"avc","label":"480p","vertical_lines":480},"hd":{"codec":"avc","label":"720p","vertical_lines":720},"hd_1080p":{"codec":"avc","label":"1080p","vertical_lines":1080},"hevc_1440p":{"codec":"hevc","label":"1440p","vertical_lines":1440},"vp9_1440p":{"codec":"vp9","label":"1440p","vertical_lines":1440},"hevc_2160p":{"codec":"hevc","label":"4K","vertical_lines":2160},"vp9_2160p":{"codec":"vp9","label":"4K","vertical_lines":2160}},"thumbnails_grid":{"grid_interval":1000,"grid_width":10,"grid_height":10,"thumbs_height":288,"files":[{"file":"production_id-5197762-1080p_mp4.thumbgrid_0.jpg","start_time_ms":0,"end_time_ms":51000,"thumbs_count":51}]},"thumbnail_generating":false}
```

</details>

**Comment by jeherve** [comment]
Seems like there is extra discussion about this in #55560 and #41428. Maybe we should close this issue in favor of that one?

**Comment by cuemarie** [comment]
Thanks for that find, @jeherve ! The titles are a bit confusing, it seems like the original issue behind #41428 is resolved, and but then folks have started chatting about the 0,00 B file size there.  🤔  I'll start by asking if that issue is intentionally still open, or if it would work better to track this here.

**Comment by davemart-in** [comment]
This looks to be resolved with https://github.com/Automattic/wp-calypso/pull/55560
