### ISSUE TITLE
Assembler: Disable auto-scrolling for shuffled patterns

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#83528]
## What

Disable auto-scrolling for shuffled patterns. See p1698221512457829-slack-CRWCHQGUB

## Why

Shuffle feels janky to use since the action bar jumps around quite a bit.

## How

Find a way to differentiate the case when a pattern is shuffled to disable the automatic scrolling in the canvas.

**Comment by taipeicoder** [comment]
Closing via #84592
