### ISSUE TITLE
Assembler: Activation screen - Remove checkbox and reword the copy to make it less "scary" 👻

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#83529]
## What

In the Activation screen, remove the checkbox and reword the copy to make it less "scary". See p1698313958107449-slack-CRWCHQGUB

## Why

To be consistent with the theme activation modal in the Theme Showcase.

## How

As we did for the theme activation modal in https://github.com/Automattic/wp-calypso/issues/83152

|Theme Showcase Before|Theme Showcase After|
|--|--|
|![Image](https://user-images.githubusercontent.com/1881481/278326126-17780065-6c99-49f2-bcf8-cca5e2d7d1ac.png)|![Image](https://user-images.githubusercontent.com/1881481/278325965-74ae0da4-5f7c-46a8-a6a1-fc759a087f06.png)|

**Comment by arthur791004** [comment]
@autumnfjeld @lucasmendes-design Now the copy is changed to below. See https://github.com/Automattic/wp-calypso/pull/83744. 
* `This will replace your homepage, but your content will remain accessible. Learn more.`

Does it look good?

![image](https://github.com/Automattic/wp-calypso/assets/13596067/ea3b0ba5-1694-4e88-9109-a637e23c9753)

**Comment by lucasmendes-design** [comment]
All to me :)

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/83744
