### ISSUE TITLE
Notice with transparent background: Add to component docs

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#83533]
We added a new styling for the Calypso notice component, `is-transparent-info`.

<img width="423" alt="image" src="https://github.com/Automattic/wp-calypso/assets/52076348/16cced5b-e82e-428b-a545-5b2f40b9ad6a">

We should add it to the components documentation: https://wpcalypso.wordpress.com/devdocs/design/notice

**Comment by agrullon95** [comment]
Completed with https://github.com/Automattic/wp-calypso/pull/83908
