### ISSUE TITLE
Plugin Details Multi-site: Use the with-plugin flow as CTA when the user has no sites

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#83535]
Parent task: #81713

**Comment by WBerredo** [comment]
When on the Plugin Details page and the user has no sites:

- The user shouldn't see the "Manage Sites" button
- Instead the user should a `Get Started` CTA leading to the `with-plugin` onboarding flow, similar to the logged out view

**Comment by epeicher** [comment]
Currently, for the scenarios of the user having no sites, the CTA reads `Start your free trial` but when clicking it, nothing happens. Investigating the potential bug: 

https://github.com/Automattic/wp-calypso/assets/3519124/cec3099d-0d88-427b-add0-e70089f230fa

**Comment by epeicher** [comment]
After some investigation, it seems that after this task was raised, some changes impacted it.

The following PR fixed the original issue by redirecting the user to `Get started`:
- https://github.com/Automattic/wp-calypso/pull/82559

But it seems this one changes and introduced the bug described in the video above for users with no sites:
- https://github.com/Automattic/wp-calypso/pull/86363

So the potential fix could be to restore the PR #82559 while keeping the behaviour of #86363

**Comment by epeicher** [comment]
After the rollback of https://github.com/Automattic/wp-calypso/pull/86363 as part of https://github.com/Automattic/dotcom-forge/issues/6024, this issue should be solved. I will keep it open to test it

**Comment by epeicher** [comment]
After the completion of https://github.com/Automattic/dotcom-forge/issues/6024, this issue is solved 🎉 

https://github.com/Automattic/wp-calypso/assets/3519124/cd1fa47d-1171-4f7c-a8d2-47c0d938e6af
