### ISSUE TITLE
Reader/First Posts: Filter out test posts

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#83538]
We see a few test posts in the first-posts stream and it'd be nice to filter them out.

It might be tricky to filter out based on key words given different locales so I'm wondering if an option might be to simply remove first posts that are very short (like 3 words or less).

Assuming we do go with a word limit, we'll also want to add a check to ensure we don't filter out posts that only contain an image.

**Comment by sixhours** [comment]
It might be good to apply the same filter to the Discover/Recommended stream as well!

**Comment by markbiek** [comment]
Implementation happening in: D127317-code

**Comment by markbiek** [comment]
Noting here that the first version of this filter will only log possible test posts to logstash rather than removing them from the stream. Once we've collected some data on how the filter is doing, we can adjust the filter as needed.

**Comment by markbiek** [comment]
I checked the logs again and I'm not seeing any new test posts in the log. I'm going to give it a couple more days and check again.

**Comment by markbiek** [comment]
I checked the logs again and I'm not seeing any new test posts in the log. I'm going to give it a couple more days and check again.

**Comment by markbiek** [comment]
I've gone through the logs since yesterday and found a couple additional items that _shouldn't_ be ignored:

* `wp-block-embed`
* `is-reader`

**Comment by markbiek** [comment]
Additional updates in D128568-code

**Comment by markbiek** [comment]
Another tag that we want to allow

* `<audio>`

**Comment by markbiek** [comment]
Things are looking pretty good after checking the logs today. I didn't see any posts that _shouldn't_ have been flagged as test posts.

**Comment by markbiek** [comment]
Opened D130189-code to actually start filtering out the test posts.

**Comment by sixhours** [comment]
@markbiek I think this has been fixed with the deployment of D130189-code?

**Comment by markbiek** [comment]
> @markbiek I think this has been fixed with the deployment of D130189-code?

Yes, thank you! I'll close this.
