### ISSUE TITLE
Plugin Details Multi-site: List all sites and add an Upgrade to Purchase option

### ISSUE THREAD

**Issue by JulianBustamante** [Automattic/wp-calypso#83536]
Parent task: https://github.com/Automattic/wp-calypso/issues/81713

**Comment by WBerredo** [comment]
When on the Plugin Details page with no site selected:

- All sites should be listed (simple/atomic/any plan)
- The button on each item should be similar to the CTA on the Plugin Details page with a selected site. Ex: Upgrade to purchase, Purchase to activate, etc.

**Comment by WBerredo** [comment]
From the parent task:

>  I noticed that one of my sites that is on a Business plan is not listed here. 🤔

Currently the modal only list sites that can already install plugins, which means atomic. So if a site is Business but not atomic, it won't be list.
