### ISSUE TITLE
[Enhancement]: Calypso Media Usage - Improve how we display % storage used for low-media sites

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#83556]
### What

In the WordPress.com Media Library, show either decimal points or an indication that some media storage is used, just less than 1%. 

### Why

Right now, sites show `0% of XX GB used` when they have used less than (I am guessing) 1% of their disk space quota.  With AT sites with larger media quotas, it might stay at 0% for a while, if they're optimizing images properly.

This can lead to confusion, or appear to be a bug.  Example: https://github.com/Automattic/wp-calypso/issues/83516

### How

Option 1 - more decimal places:

- Add decimal places in the WordPress.com Media library to show more detailed media usage, like `0.01% of XX GB used.`

Option 2 - show "<1%" until 1% is met/passed

- Alternatively, we could also just show something like `< 1% of XX GB used`.

**Comment by Aurorum** [comment]
PR in #86124 for this issue. :)

**Comment by bogiii** [comment]
Hey @Aurorum ,

During my groundskeeping rotation, I stumbled upon this ticket and saw [a solved and reviewed PR](https://github.com/Automattic/wp-calypso/pull/86124).

Is there any particular reason why we didn't merge it?

**Comment by Aurorum** [comment]
Hey @bogiii - thanks for revisiting this! No, as far as I’m aware, that PR is still good to ship.
