### ISSUE TITLE
Add a page modal - Disable core modal triggered by page patterns from the active theme

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#83595]
Read more in pekYwv-3a3-p2

**This fix must be done before Kentwood theme is launched because it includes page patterns.** See pNEWy-htG-p2

## What

Disable the core page pattern modal in the editor in Dotcom. 

## Why
Because the pages core modal will open on top of the Dotcom modal

https://github.com/Automattic/wp-calypso/assets/1881481/7e12843e-8706-4a88-a01b-3719401c27f4

## How

Patterns from the active theme are registered on the `init` action. Search for `_register_theme_block_patterns` and `gutenberg_register_theme_block_patterns` in the wpcom codebase.

After they are registered we have to: 

1. Unregister them
2. Remove the `block type: core/post-content` from their properties
3. Register them again

**Comment by taipeicoder** [comment]
Closing via #83750
