### ISSUE TITLE
Themes: SSR Showcase SEO Relevant Fields

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#8359]
While Theme Sheets now have their `title`, `meta`, and `link` tags populated with the relevant data, the showcase (`/design`) currently hasn't. This is probably due to the showcase being marked as non-isomorphic in `client/wordpress-com.js` and some conditionals only populating those tags for isomorphic sections.

**Comment by seear** [comment]
We could perhaps call the new endpoint on the calypso server then bootstrap the data to the client when Calypso loads.

**Comment by mattwondra** [comment]
I think this issue should be resolved after #8870 deploys to production (these features are currently behind a flag). That PR actually renders the ThemeShowcase component on the server, which is how the document head gets those tags populated.

**Comment by ockham** [comment]
Should be fixed now that #8870 is in production 😄
