### ISSUE TITLE
็How  can  install on Win7

### ISSUE THREAD

**Issue by limweb** [Automattic/wp-calypso#836]
How  can  install on Win7

**Comment by Tug** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/592

It does not run on Windows as of now.

**Comment by HammyHavoc** [comment]
Would love to see this arrive on Windows as a universal app; Windows Phone/Windows 10 Mobile app for WordPress is fairly lacking. Would love to contribute to this repository.

**Comment by stephanethomas** [comment]
@limweb, I just wanted to let you know that we have released a [portable development environment](https://github.com/Automattic/wp-calypso-bootstrap) that simplifies the task of running Calypso on Windows.
