### ISSUE TITLE
App download for Linux is 404

### ISSUE THREAD

**Issue by Trez-zerT** [Automattic/wp-calypso#83615]
### Quick summary

Trying to download the .tar.gz app version of Wordpress gives me either a blank page or a 404.

### Steps to reproduce

Start with https://apps.wordpress.com/d/linux/
Wait for redirect
Behold the 404

### What you expected to happen

Download should start

### What actually happened

404 error

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

Using Firefox 119.0 on Endeavour OS.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested from https://apps.wordpress.com/ – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I can replicate this on my side, tested with Firefox 119.0 on macOS 14.0. Redirect 404s at: `https://public-api.wordpress.com/rest/v1.1/desktop/linux/download`

The link noted is found at the bottom of https://apps.wordpress.com/, here: 

![Markup on 2023-10-31 at 10:01:23](https://github.com/Automattic/wp-calypso/assets/27249804/51e3cab8-282b-4045-85e9-46516ada3d7c)


The other links do successfully trigger a file download.

📌 ACTIONS
- Triaged

**Comment by candy02058912** [comment]
Asked in Slack for more context on who we could reach out to: p1720689461875809-slack-C029GN3KD

**Comment by gavande1** [comment]
The diff was created to fix the issue: D154994-code

**Comment by gavande1** [comment]
The fix was deployed in r299529-wpcom

**Comment by candy02058912** [comment]
Closing the issue as I've confirmed that the link is no longer broken.
