### ISSUE TITLE
NC i4: Create an endpoint that takes categories and returns the amount of unique subscribers

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#83635]
Create a new endpoint `/wpcom/v2/sites/<siteid>/newsletter_categories/count?term_ids=xxx,xxx,xxx` that returns the unique total count a post to those categories would go out to.

If the term_ids contain a non-newsletter category, make sure to include users who haven't opted out from any categories.

**Comment by phcp** [comment]
Closed by D128142-code
