### ISSUE TITLE
Turn off Site View achievements and/or stats-tracking for domain-only sites

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#83632]
### Quick summary

A customer reported that their domain-only landing page is tracking stats.  As such they're getting site notifications which is unexpected for them:

> Congratulations! Your site, [domain.com], passed 50 all-time views.

<img src="https://github.com/Automattic/wp-calypso/assets/15944096/0e4634b5-ff52-4a03-95d3-e2a0ab1da5b0" width="400">

Workarounds:
- you'd have to create a free site only for the purpose to make it private 
- the domain DNS would have to be tweaked such that the domain looks broken (nothing loads)

Internal discussion: p1698650452614689/1698483856.837849-slack-C0438NHCLSY
- Is the tracking pixel suppose to be on the domain-only landing page?
- Could there be an option to not have landing page?  I don't see it as an option in [the doc](https://wordpress.com/support/domains/register-a-domain-without-creating-a-site/).

Ticket: 7194032-zd-a8c

### Steps to reproduce

1. Purchase a domain only upgrade
2. Visit the site

### What you expected to happen

No stats should be tracked.

### What actually happened

It appears the stats are tracked.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cometgrrl** [comment]
Related to https://github.com/Automattic/dotcom-forge/issues/3186 which seems to have gotten lost in the shuffle.

**Comment by cuemarie** [comment]
Thanks @cometgrrl , definitely looks like the same thing. 

Slack thread from that time: p1690047600100049-slack-C05CT832K2T

📌 ACTIONS
- Feature request kept
- Closed the internal issue in favor of this one

**Comment by cometgrrl** [comment]
I would say this is a bug.  How can you have site views if you don’t have a site?  Yes, we create a placeholder but from the user’s perspective they don’t site, and shouldn’t see these.

**Comment by sajmes** [comment]
Another report of this here. Certainly a confusing experience: 7592352-zd-a8c

**Comment by hambai** [comment]
Okay I deployed a diff that would prevent those notifications from showing for domain_only sites
