### ISSUE TITLE
Audio block: Allow adding a featured image

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#83645]
### What

Our audio block is quite limited but could be more interesting if users could assign an image to an audio file within the block.

### Why

This would allow users to set a cover for an album or track, for example, and offer a lot more possibilities when it comes to making the audio player more visually attractive.

Also, as colossus like Bandcamp are being sold and musicians abandon these platforms to regain control over their work, it would be nice to offer them good tools to share their work here at WordPress.com in a way that matches the experience they are used to in other audio players.

### How

By adding the option to the audio block.

**Comment by cuemarie** [comment]
📌 ACTIONS
- As this is a core block, I've shared your feature request here instead:
     - https://github.com/WordPress/gutenberg/issues/55715
- Closing in favor of the core request
