### ISSUE TITLE
Assembler: Jetpack blocks are not rendered when shown initially with page load

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#83678]
## Description

Jetpack blocks are not rendered when the pattern is shown with the page load. For instance, this is the screenshot when the Contact category is pre-selected:

![Image](https://github.com/Automattic/wp-calypso/assets/797888/4bd33b66-65e7-4947-9d3b-2263ec66342b)

Another example, when the pattern `Slideshow Gallery` from the Gallery category is pre-selected:
![Image](https://github.com/Automattic/wp-calypso/assets/797888/2bf665dd-5a9e-4fbb-b28d-2478b71ec9cb)

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/83702
