### ISSUE TITLE
Themes: Synchronise client taxonomy list with latest theme taxonomies

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#8367]
In #7151 we added a static list of theme taxonomies to Calypso for validation and auto suggest/complete in the theme search. The list is generated with [this script](https://github.com/seear/theme-taxonomies/blob/master/theme_tax.php).

We need to either automate this process somehow so that theme taxonomy changes are immediately updated at the client, or add a new API endpoint that returns the list.

**Comment by seear** [comment]
We could perhaps call the new endpoint from the Calypso server then bootstrap the data to the browser when Calypso loads.

**Comment by seear** [comment]
cc @ehg this might be an interesting trial project.

**Comment by seear** [comment]
> We could perhaps call the new endpoint from the Calypso server then bootstrap the data to the browser when Calypso loads.

(This is because we don't want to have to wait around for an API return before we can start suggesting search terms).

**Comment by ockham** [comment]
Fixed by #13867.
