### ISSUE TITLE
My Home Launchpad fails to open 'Choose a plan' step after publishing first post

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#83673]
### Quick summary

GH Tracking issue for report here: p1698701024528039-slack-C02FMH4G8

> I’m currently not able to click on “Choose a plan” (nothing happens) when I skip Launchpad and get the “My home launchpad” in the blog flow. Which means my site is stuck in coming soon / private.

### Steps to reproduce

1. Visit the Logged Out Homepage (LOHP)
2. Click “Blog ->” just below the fold on the LOHP
3. Select a design
4. Get to Launchpad
5. Click Skip in the top right
6. Do some other steps like Name your blog and Write you first post
7. Fail to be able to click on Choose a plan

> Note: this issue only happens if I skip the launchpad and get the “my home launchpad”. Everything works as expected in the “default launchpad”.

### What you expected to happen

Open Plans page

### What actually happened

Nothing 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described. In my test and others, after publishing the first post, returning to the dashboard does not update the URL - I still see `https://wordpress.com/post/freetestsitedownload.wordpress.com/30` in my address bar, no matter where I navigate.

Others report seeing the URL work as expected, but the Plan purchase page still doesn't open.

**Workaround**

Opening "Purchase a plan" in a new tab works

📌 ACTIONS
- Triaged

**Comment by worldomonation** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/33872.

**Comment by worldomonation** [comment]
@cuemarie Just to clarify with you - were you able to reproduce this when the escalation occurred?

Am I clicking at the right place? The original steps to reproduce uses acronyms (like LOHP) that I'm not familiar with.

![Screenshot 2023-11-01 at 2 20 08 PM](https://github.com/Automattic/wp-calypso/assets/6549265/7156c372-1458-4073-9b66-0cc5db46d34b)

**Comment by cuemarie** [comment]
Following up to close the loop:

> were you able to reproduce this when the escalation occurred?

I was able to replicate this test when the escalation occurred.

> Am I clicking at the right place? The original steps to reproduce uses acronyms (like LOHP) that I'm not familiar with.

Apologies to anyone who that threw off! For anyone trying to replicate, LOHP stands for Logged Out Home Page, so that is the necessary place to start. I'll update the report above for better record-keeping.
