### ISSUE TITLE
New blog post emails: add "read more" CTA when using "more" block

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#83715]
### Details

When blog post uses "read more" block or chooses to send only excerpts, we cut the content and end up with two competing CTAs (read & comment):

<img src="https://github.com/Automattic/wp-calypso/assets/87168/ad10738f-abec-4a7a-a035-af4e02121b09" width="320" />

Let's update the CTA to read more:

![image](https://github.com/Automattic/wp-calypso/assets/87168/ac53087a-3f09-44b5-8c6f-70479bfab2f1)

Slack p1696497810393719-slack-C052XEUUBL4

The setting to always send emails with excerpts:

![image](https://github.com/Automattic/wp-calypso/assets/87168/6a59a49d-e935-4d46-90a7-31f428a2ed86)

Cris' perspective as a content creator: _I always try to get people to read stuff in the post --> more pageviews = signals Google and search engines that the content is interesting. It also helps with monetization (partnerships usually pay per X number of banner views). That's why I always send an excerpt of the post, and add a CTA to open the post itself._ 

### Checklist

- [ ] Works with "more" and "read more" blocks
- [ ] Works with excerpts setting
- [ ] Works with "page break" block

**Comment by simison** [comment]
@crisbusquets I think the CTA should keep saying "Read more" now that we have "view in browser" in the header. It also makes it clearer the entire post isn't visible in the email.

Any other visual/copy treatment we should add to make it clear the entire post isn't in the email?

**Comment by zdenys** [comment]
I agree that having one clear CTA `Read more` is more appropriate than `Comment` since how would I know I want to comment by just seeing an excerpt of the post?

**Comment by crisbusquets** [comment]
> @crisbusquets I think the CTA should keep saying "Read more" now that we have "view in browser" in the header. It also makes it clearer the entire post isn't visible in the email.

I agree, let's use `Read more`.

 > Any other visual/copy treatment we should add to make it clear the entire post isn't in the email?

Not that I can think of. The `[...]` is self-explanatory.  Combined with a more visible CTA, I think it would be enough (and much better than what we have).

**Comment by crisbusquets** [comment]
An example of what this looks like now, where the primary action is `Comment` (and you won't comment on a post you haven't read yet):

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/42b2d73e-0026-4b60-a975-6a28f0f6ff36)

**Comment by simison** [comment]
<img width="813" alt="Screenshot 2024-02-01 at 10 16 47" src="https://github.com/Automattic/wp-calypso/assets/87168/289065b4-3d18-4135-bb09-bf20980e06f5">

Yeah those custom "more" labels. Noticed the same in Jetpack blog, where the CTA is like since comments are closed.
