### ISSUE TITLE
StreamBuilder: Confirm code is compatible with PHP 8.1

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#83721]
Related Slack thread: p1698768611817879-slack-C02ECE3ML

The Slack thread includes a link to the spreadsheet of files that need to be looked at.

This likely involves coordinating with Tumblr folks to ensure any compatibility updates to the core software on their end are copied over to WP.com.

**Comment by markbiek** [comment]
At this point, we've merged the PHP 8.1 updates (see the above PR). The next step will be a new release of the library and then updating WPCOM.

**Comment by markbiek** [comment]
WPCOM has been updated with the latest version of StreamBuilder: D127557-code

**Comment by markbiek** [comment]
Just noting that we also updated `moon` to v0.9.2 (D127926-code) so both copies are currently in sync on WPCOM.
