### ISSUE TITLE
Image Editor: Move Component Out of Media Modal for better reuse

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8372]
Let's work to make the component reusable, as this could be used in other areas, like for cropping avatars.  If possible, let's move this to the blocks section, and abstract any leftover media modal hooks.

**Comment by retrofox** [comment]
I think `image-editor-canvas.jsx` should be the core of the component so it should be renamed to `blocks/image-editor-canvas/index.jsx` and `image-editor-crop.jsx` should be an internal dependency of `image-editor-canvas` and its name could be something like `blocks/image-editor-canvas/crop.jsx`.

```
- blocks
    | - image-editor-canvas
          | - index.jsx
          | - crop.jsx
```
