### ISSUE TITLE
[Navigation Block] Close button [X] is hidden on overlay view with large fonts

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#83737]
### Quick summary

Under certain conditions, the [X] button disappears on the drop-down/mobile/overlay menu on the navigation block when the font text is large and many links are present. 

Example;

![b8D6AOHuTxhzizLU3zwfbFWMpsVUKetHU6XhglVE.jpg](https://github.com/Automattic/wp-calypso/assets/5075840/c6433801-cd84-4345-9ef2-0d513e94cda6)

Video:

https://github.com/Automattic/wp-calypso/assets/5075840/97af476b-3a2c-4c4d-b32e-42b65f6aba8e

### Steps to reproduce

1. Open the site editor and edit the nav block
2. Add lots of links and sub-menus and make the text large
3. On the live site, the X button may not show. 

### What you expected to happen

The close button should always be visible 

### What actually happened

The button is hidden/

Workaround is to make the font or menu smaller 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Reported here; 7245776-zd-a8c

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic –Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Was unable to replicate following the steps provided.

https://github.com/Automattic/wp-calypso/assets/27249804/aba837f7-c9bd-40c8-8b68-6d4540bf56c7

📌 ACTIONS
- Requested author feedback

📌 Message to Author
Hey @Greatdane ! Are you able to consistently reproduce this on a test site, or only the customer's site?

**Comment by maciejpilarski** [comment]
📌 ACTIONS
– Requested author feedback - no reply
– Closed as could not replicate (please reopen if the issue reoccurs)
