### ISSUE TITLE
Newsletter sites: Unable to upgrade to Business or Commerce

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#83741]
### Quick summary

We found a recent case in the [forums](https://wordpress.com/forums/topic/upgrade-to-the-business-plan-is-not-available/?view=all) where a user with a Newsletter website isn't able to upgrade to the Business or Commerce plan.

### Steps to reproduce

1. Create a new site at https://wordpress.com/newsletter/
2. Complete the wizard
3. Go to Upgrades > Plans under the dashboard.
4. Check the plan options

### What you expected to happen

To see all plans available.

### What actually happened

Only the Free, Personal and Premium showed up.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Workaround: Share the link of the plan they want to purchase. (e.g: https://wordpress.com/sitename.com/business

P2: p2EDhh-26x-p2

**Comment by cuemarie** [comment]
This is fixed by https://github.com/Automattic/wp-calypso/pull/83724

Which added a "View All Plans" link to the bottom of the plans page:

![Markup on 2023-11-06 at 15:31:10](https://github.com/Automattic/wp-calypso/assets/27249804/8d33674b-ae2f-4194-a71b-f498db12506f)
