### ISSUE TITLE
Editor crashes when editing a post in Safari

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#83753]
### Quick summary

Editor crashes and displays an error message while adding Image & Read More blocks to a draft post:

"The editor has encountered an unexpected error"

Error code provided by the Editor:

`lt@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/blocks/index.min.js?m=1698313083i&ver=c5c22b60f30200f18060:7:85
Re@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/blocks/index.min.js?m=1698313083i&ver=c5c22b60f30200f18060:1:101591
map@[native code]
https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/block-editor/index.min.js?m=1698313083i&ver=3470984e2b53337857a7:19:988
useMemo@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:115218
https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/block-editor/index.min.js?m=1698313083i&ver=3470984e2b53337857a7:19:895
St@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:47628
yr@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:56444
Sl@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:88651
kl@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:88579
bl@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:88442
sl@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:85266
dl@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:85653
dl@[native code]
Nn@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:32465
ml@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/vendors/react-dom.min.js?m=1698313083i&ver=18:1:86095
https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/compose/index.min.js?m=1698313083i&ver=da82f6f75e3ba3f58e5f:1:34445
o@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/priority-queue/index.min.js?m=1698313083i&ver=973d01b458326bc1f15d:1:3076
O@https://s0.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/priority-queue/index.min.js?m=1698313083i&ver=973d01b458326bc1f15d:1:991`

- Clearing browser caching did not help.
- Other browsers do not show error (tested Chrome)

### Steps to reproduce

1. Start in the WordPress editor
2. Add text, images and "read more" blocks.
3. Editor crashes

### What you expected to happen

No crashing.

### What actually happened

Editor crashes.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- User report 7247498-zen

**Comment by rickmgithub** [comment]
📌 REPRODUCTION RESULTS
Couldn't replicate on simple or AT test site.

📌 ACTIONS
@davipontesblog I couldn't replicate this. Were there any specific steps we could try, theme, etc?
Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by davipontesblog** [comment]
I asked the user in 7325573-zen to see if they are still experiencing the issue. If they don't reply in 3 days I will leave a comment so we can close the issue 👍

**Comment by davipontesblog** [comment]
> I asked the user in 7325573-zd-a8c to see if they are still experiencing the issue. If they don't reply in 3 days I will leave a comment so we can close the issue 👍

No replies, so keeping this closed.
