### ISSUE TITLE
Task: Adjust Hosting Configuration PHP version labels ahead of PHP 8.0 EOL.

### ISSUE THREAD

**Issue by jmdodd** [Automattic/wp-calypso#83752]
### Details

PHP 8.0 will no longer receive security updates as of 26 November 2023. Ahead of that date, we'd like to recommend 8.1 as the default PHP version for WoA sites and remove the experimental tag from 8.2. Once site upgrades to 8.1 are complete, we will need to deprecate and remove 8.0 as an option in a separate task.

1. Start at `wordpress.com/hosting-config/site-domain.com` for any WoA site.
2. Under "Web server settings", notice that PHP 8.0 is labelled as "Recommended" and PHP 8.1 is labelled as "Experimental".

### Checklist

In `/client/my-sites/hosting/web-server-settings-card/index.js`:
- [x] Remove Recommended label from PHP 8.0.
- [x] Add Recommended label to PHP 8.1 and update `recommendedValue` to 8.1.
- [x] Remove Experimental label from PHP 8.2.
- [x] Test Hosting Configuration changes on a test WoA site and verify PHP version changes on the site as set from Calypso.

**Comment by vindl** [comment]
Updated in https://github.com/Automattic/wp-calypso/pull/83762.

**Comment by obenland** [comment]
> Once site upgrades to 8.1 are complete, we will need to deprecate and remove 8.0 as an option in a separate task.

@jmdodd For PHP 7.4 removal we thought about deprecating the version number in hosting config first, and upgrade sites after, so sites don't switch back. Is there a reason you went with upgrades first, before deprecating the option?

**Comment by jmdodd** [comment]
Usually if a user switches back, they have a good reason for it and we want to provide them and HEs with that flexibility. For the 7.4 to 8.1 upgrade (per our conversation earlier), I would recommend making 7.4 clearly the acknowledged deprecated option without removing it entirely from use.
