### ISSUE TITLE
Framework: Investigate new test warnings

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8376]
After our Node upgrade to 6.7.0 in (#8297) @gziolo noticed that we had new [test warnings](https://github.com/Automattic/wp-calypso/pull/8297#issuecomment-250421605)

Let's try to fix these.

To reproduce, run `make test`. In some of the suites you'll see the following:

```
(node:3495) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Driver not found.
(node:3495) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: No available storage method found.
(node:3495) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Driver not found.
(node:3495) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: No available storage method found.
```
Warning added in node [6.6.0](https://nodejs.org/en/blog/release/v6.6.0/):
> promises: Unhandled rejections now emit a process warning after the first tick. (Benjamin Gruenbaum) #8223

_Maybe Relevant_
- http://www.2ality.com/2016/04/unhandled-rejections.html
- https://github.com/Ecostack/localForage-cordova-sqlite-plugin/issues/2
- http://clarkdave.net/2016/09/node-v6-6-and-asynchronously-handled-promise-rejections/

**Comment by dmsnell** [comment]
I'm suspicious of `use-fake-dom` and `use-mockery`

In `use-fake-dom` we make a `delete` that seems like it could potentially fail (need to investigate if this is possible that it throws an error)

In `use-mockery` we explicitly set a timeout thinking that it could take too long.

I'm hunting down places that could throw errors where we aren't explicitly using them as promises but they are maybe hidden inside of mocha as promises

**Comment by dmsnell** [comment]
This code pasted into the top of `test/runner.js` can be helpful in investigating. It will print a stack trace and abort at the first error

```js
Error.stackTraceLimit=Infinity;
process.on('unhandledRejection', (reason) => {
	console.log('Reason: ' + reason);
	console.trace();
	process.exit(1);
});
```

**Comment by brunoscopelliti** [comment]
Hi there,

I came across this warnings too, while was writing some tests for `sites-dropdown` component.
I've also another strange log before those warnings:

```bash
double callback!
(node:10818) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Driver not found.
(node:10818) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: No available storage method found.
(node:10818) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Driver not found.
(node:10818) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: No available storage method found.
```

I investigated a bit, and can confirm that the `UnhandledPromiseRejectionWarning` warnings are caused by `localforage`.

Currently we're using **localforage@1.4.0**. Latest version is **1.4.3**.
Since version **1.4.1** the warnings aren't present anymore.
I leave you to evaluate the upgrade.

As for the `double callback!` message, it seems caused by [superagent](https://github.com/visionmedia/superagent/issues?utf8=%E2%9C%93&q=is%3Aissue%20double%20callback!%20). However I'm still not sure what is causing it. Does it happen to you too?

**Comment by brunoscopelliti** [comment]
>Does it happen to you too?

**YES**.
I was searching this issue, and found this one #4206 instead :)

**Comment by gwwar** [comment]
> Since version 1.4.1 the warnings aren't present anymore.

Good to know. I'll try to spin up a PR next week.

**Comment by gziolo** [comment]
> I was searching this issue, and found this one #4206 instead :)

Yes, at some point I was able to remove all `double callback!` warnings.

**Comment by gziolo** [comment]
It needs to be revisited since we migrated to Jest. See #16943.
