### ISSUE TITLE
Reader/First Posts: Filter out posts with Headstarted test content

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#83774]
Found this while testing D127317-code

There are multiple dummy content posts showing up in First Posts -- they're getting incorrectly flagged with the `wpcom-is-first-post` post meta:

<img width="623" alt="Screenshot 2023-11-01 at 3 55 03 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/ee059466-286a-4f57-870b-a03fab532f21">

I traced the content back to this file, which was introduced in mid-September this year: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Surnqfgneg%2Spynff%2Qurnqfgneg%2Qtrarengr%2Qnaabgngvba%2Qtrarevp.cuc%3Se%3Q17sq3r2s%26zb%3Q1083%26sv%3Q21%236-og

The first posts meta gets added here:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qsvefg%2Qcbfgf.cuc%3Se%3Q7607318r%2328-og

**Comment by sixhours** [comment]
This appears to happen when you choose to "Design your own" theme in the design picker, instead of picking a theme:

<img width="1254" alt="Screenshot 2023-11-01 at 4 59 07 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/3ad0c5de-a357-4453-b5df-5d47a04fd487">

From there you're put into the Pattern Assembler:

<img width="1284" alt="Screenshot 2023-11-01 at 5 01 45 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/98bcf655-22c3-4594-ac80-46d009edae87">

I've confirmed that the published posts do fire the `publish_post` hook that we're hooking into, but it seems the posts created through that method aren't Headstarted in the traditional way -- `defined( 'HEADSTART' ) && HEADSTART` is not `true`.

**Comment by sixhours** [comment]
We're hitting this endpoint to set up the site from the selections made in the Pattern Assembler, and this endpoint is responsible for creating the test posts via the site's API: 

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfvgr%2Qnffrzoyre%2Sfvgr%2Qnffrzoyre.cuc%3Se%3Qn4377607%23131-og

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfvgr%2Qnffrzoyre%2Sfvgr%2Qnffrzoyre.cuc%3Se%3Qn4377607%23210-og

~~So we may use the same Headstart data to generate the post details, but Headstart is not used to *create* these posts; we're sending the post details as part of the API request and the posts are created there, which explains why we're not in the `HEADSTART` context:~~

The above is not quite correct. The site assembler endpoint does not provide post content; it simply fires off additional requests to the site's API to create new posts if the reset parameter is true, and those new posts are created from the default content and returned as part of the site assembler's response. However, for some reason, when those posts are created, we're still not in the Headstart context. Maybe because we're creating posts via the API?

We may need to add a check in our `publish_post` filter function that checks to see if the post title and content match that of the default data before adding the `wpcom_is_first_post` post meta.

**Comment by sixhours** [comment]
> However, for some reason, when those posts are created, we're still not in the Headstart context. Maybe because we're creating posts via the API?

Aha, it's because we're pulling the posts directly from a theme demo site (in this case, creatio2demo.wordpress.com) rather than using Headstart. The same content is located in the default Headstart annotations file above, but it's never accessed by the site assembler endpoint, so that was a red herring :)

Here's where we grab the theme's starter content in the site assembler endpoint: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfvgr%2Qnffrzoyre%2Sfvgr%2Qnffrzoyre.cuc%3Se%3Qn4377607%23358-og

And here's where we create those posts on the new site using that content:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfvgr%2Qnffrzoyre%2Sfvgr%2Qnffrzoyre.cuc%3Se%3Qn4377607%23391-og

Unfortunately this means we'll have a lot more potential dummy data to check against. 🙃 Conceivably anything from any theme's demo site could be copied into a new site. Trying to maintain a static array of all potential dummy posts is too fragile.

I wonder if we set a specific constant (ie. `DUMMY_CONTENT`, terrible name but just as an example) when we create new posts in these scenarios (basically mimicking what we do to check for Headstart), then we could check to see if that constant is set before applying the first posts meta.

Thoughts on this approach?

**Comment by andres-blanco** [comment]
Really nice digging!

I think the constant approach is a valid one and the behaviour will behave in the same way as with the HEADSTART posts.

Of course if a user goes to the post, makes a really small change (like removing a space) and re-publish the post it will mark it as a first-post, but that is also happening with current HEADSTART posts.

Overall, I think this is a good approach and it will decrease the amount of dummy content in the first posts stream.

**Comment by sixhours** [comment]
More discussion with @Automattic/lego folks in p1698912194233679-slack-CRWCHQGUB

**Comment by fushar** [comment]
I'm assigning myself to this issue. This should be fixed early next week!

**Comment by autumnfjeld** [comment]
Is this the work?  So this can be moved to Review Approved?

[D127856 Assembler: use Headstart for inserting starter posts (production) https://code.a8c.com/D127856](https://github.com/Automattic/wp-calypso/issues/83932)

**Comment by fushar** [comment]
@sixhours @daledupreez We've shipped the fix, could you verify if it fixed the issue? Thanks!

**Comment by sixhours** [comment]
@fushar Thanks! I can confirm we're no longer seeing the starter content in the First Posts feed. 🥳
