### ISSUE TITLE
Framework: Investigate Calypso Performance

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8377]
After working on #8286 @lamosty noticed that the image editor actually had good performance about a month ago, without any tweaks. Let's investigate to see if there's a particular performance bottleneck that was introduced.

We should try to sandbox this to around a day. If you find something substantial, please report back, and we can write up further issues.

**Comment by mtias** [comment]
Not necessarily related, but I've found several performance degradations in the last couple months. Some seemed related to web preview, others to data storage (particularly stats storing in localStorage directly as well as redux store), and some others around routing and constant re-renders.

**Comment by ehg** [comment]
> and some others around routing and constant re-renders.

This is seems to be because `page.js`'s `onclick` fires multiple times per click, causing the same route to be hit multiple times, which means it causes multiple renders. I'm not sure why it's doing this.

Disabling `page.js`'s click handler, and hacking a `page.show` into `SideBarItem` fixes it. But of course for no other links :]
```
diff --git a/client/boot/index.js b/client/boot/index.js
index 67c7b4d..528a14b 100644
--- a/client/boot/index.js
+++ b/client/boot/index.js
@@ -432,7 +432,7 @@ function reduxStoreReady( reduxStore ) {
 	} );
 
 	detectHistoryNavigation.start();
-	page.start();
+	page.start( { click: false } );
 }
 
 window.AppBoot = function() {
diff --git a/client/layout/sidebar/item.jsx b/client/layout/sidebar/item.jsx
index e4b2374..9e75f94 100644
--- a/client/layout/sidebar/item.jsx
+++ b/client/layout/sidebar/item.jsx
@@ -3,6 +3,7 @@
  */
 import React from 'react';
 import classnames from 'classnames';
+import page from 'page';
 
 /**
  * Internal dependencies
@@ -33,6 +34,12 @@ export default React.createClass( {
 		}
 	},
 
+	onNavigate( event ) {
+		event.preventDefault();
+		page.show( this.props.link );
+		this.props.onNavigate();
+	},
+
 	render() {
 		const isExternalLink = isExternal( this.props.link );
 		const classes = classnames( this.props.className, { selected: this.props.selected } );
@@ -40,7 +47,7 @@ export default React.createClass( {
 		return (
 			<li className={ classes } data-tip-target={ this.props.tipTarget } >
 				<a
-					onClick={ this.props.onNavigate }
+					onClick={ this.onNavigate }
 					href={ this.props.link }
 					target={ isExternalLink ? '_blank' : null }
 					onMouseEnter={ this.preload }
```

**Comment by lamosty** [comment]
We fixed the image editor issue in #8408.

However, as you (@mtias and @ehg) have pointed out that we have more performance related issues in Calypso, let's keep this issue open for further improvements.

With regards to the `page.js` `onclick` handler strange behavior, that looks pretty interesting to me. I will try to look into this issue in the following days. :)

**Comment by lamosty** [comment]
@egh: I added a `console.log` into `page.js` as follows:

![selection_022](https://cloud.githubusercontent.com/assets/4988512/19087730/7346b7b2-8a73-11e6-8557-dfda267200cb.jpg)

After clicking on any sidebar item (+ stats/plans `NavTabs` items), only single log item was produced in Chrome dev console.

How can I reproduce the `page.js` `onclick` multiple firing? :)

**Comment by ehg** [comment]
> After clicking on any sidebar item (+ stats/plans NavTabs items), only single log item was produced in Chrome dev console.

> How can I reproduce the page.js onclick multiple firing? :)

Interesting. Thanks for looking at this :) I'm not sure, I see multiple `onclick` handlers firing per Click event in the timeline. Can you reproduce that?

**Comment by lamosty** [comment]
> Interesting. Thanks for looking at this :) I'm not sure, I see multiple onclick handlers firing per Click event in the timeline. Can you reproduce that?

Yeah, pretty interesting. No problem. :)

I can see that too:

![selection_023](https://cloud.githubusercontent.com/assets/4988512/19091297/5784da9a-8a82-11e6-9977-2348caa1438d.jpg)

However, I wonder how that timeline works as the logging statement in both `page.onclick` and `page.show` fire only once per sidebar item click.

**Comment by lamosty** [comment]
If I record JS CPU profile separately in the Profiles tab, there's only one `onclick` call:

![selection_024](https://cloud.githubusercontent.com/assets/4988512/19091546/6c039c1c-8a83-11e6-8f85-f5052bf47c7f.jpg)

**Comment by lamosty** [comment]
> I'm not sure, I see multiple onclick handlers firing per Click event in the timeline. 

I wonder: couldn't the multiple `onclick`s displayed on the timeline be simply a continuation of one `onclick` function call but divided in time as browser worked on it?

When I reveal the Call Tree, there's only one `onclick` activity with some *total time* which is different from the *total time* shown on the `onclick` in the timeline view:

![selection_025](https://cloud.githubusercontent.com/assets/4988512/19091883/b1f8211a-8a84-11e6-918e-36b2362ef731.jpg)

I'm a timeline newbie so just guessing. It's also quite hard to find articles on this and I prefer not to watch the hour long videos about timeline. :D
