### ISSUE TITLE
Media: create new media section

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8381]
Let's stub out a new media section! This requires creating a feature flag and some basic section configuration. See the config under: `wordpress-com.js`

**Comment by artpi** [comment]
Fun fact: I discovered media section already there in calypso. The details view is not hooked up and it's a bit outdated, but its there.

![screen shot 2016-10-07 at 15 47 58 pm](https://cloud.githubusercontent.com/assets/3775068/19192435/88a20186-8ca6-11e6-800c-27b393f6fd51.png)

@aduth was working on it long time ago.
Related:
- 9442-gh-calypso-pre-oss
- 10317-gh-calypso-pre-oss

I'll be refactoring it a bit
