### ISSUE TITLE
WPcom Admin bar overlapping top of page on Simple sites

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#83827]
### Quick summary

The WPcom admin bar is overlapping the top of site content on simple sites and P2s.

![Markup on 2023-11-02 at 12:39:22](https://github.com/Automattic/wp-calypso/assets/27249804/cd709116-5060-40e6-8d27-f945c521dafc)

### Steps to reproduce

1. Log in to WordPress.com
2. Open any simple site or p2, like https://fewerdemo.wordpress.com/ or https://startfitterdemo.wordpress.com/ 
3. Observe the top admin bar

### What you expected to happen

Site content should appear just below the top admin bar

### What actually happened

Site content appears underneath it

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
Escalated thread for P2s, where this is being looked into: p1698950453935769-slack-C02FMH4G8

**Comment by obenland** [comment]
Fixed in r279659-wpcom.
