### ISSUE TITLE
Add dark mode to dashboard

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#83822]
### What

User wants dark mode for Calypso and wp-admin dashboards.

### Why

They find light mode unpleasant, and did not care for the available plugins which purport to add dark mode to the dashboard.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by Aurorum** [comment]
This was something which Calypso used to have, but was reverted a while back (see #31996). I believe that the decision was made that this should not be supported - has that thinking been reversed now?

**Comment by davemart-in** [comment]
Going to close this out as "Won't fix" for now. This just isn't a priority when stacked against all of the other things we could work on.

**Comment by davemart-in** [comment]
It's worth noting though that a dark mode may come with the wp-admin redesign efforts in core.
