### ISSUE TITLE
Google Apps: Change all branding to new brand "G Suite"

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/wp-calypso#8384]
Google announced a branding change to some of their biggest products, including Google Apps. They have asked all of their partners (including Automattic/WordPress.com) to change all references to *Google Apps* and *Google for Work* to the new name, *G Suite*. I've attached all the new logos and the Brand Book for reference. 

Google Apps is in a lot of places within the purchase flow and /domains, but here are the big ones:

![screen_shot_2016-09-30_at_2_58_42_pm](https://cloud.githubusercontent.com/assets/6569475/19005603/11a97c74-8721-11e6-92c0-4a4876822b3a.jpg)

![screen_shot_2016-09-30_at_2_56_12_pm](https://cloud.githubusercontent.com/assets/6569475/19005609/1da743b2-8721-11e6-803d-830f1bd22287.jpg)

![screen_shot_2016-09-30_at_1_44_20_pm](https://cloud.githubusercontent.com/assets/6569475/19005615/24dc78a0-8721-11e6-9453-71882d0002bb.jpg)

![screen_shot_2016-09-30_at_1_43_38_pm](https://cloud.githubusercontent.com/assets/6569475/19005623/2d0a482c-8721-11e6-923d-d6b12c5b3b0f.jpg)

![screen_shot_2016-09-30_at_1_40_56_pm](https://cloud.githubusercontent.com/assets/6569475/19005630/36b3b066-8721-11e6-8374-8331c19abff2.jpg)

![screen_shot_2016-09-30_at_1_39_38_pm](https://cloud.githubusercontent.com/assets/6569475/19005641/3fa521e6-8721-11e6-8e54-b9f7864f85aa.jpg)

![screen_shot_2016-09-30_at_1_38_27_pm](https://cloud.githubusercontent.com/assets/6569475/19005646/46fd4130-8721-11e6-9fd1-fb56a3c97084.jpg)

![screen_shot_2016-09-30_at_1_37_40_pm](https://cloud.githubusercontent.com/assets/6569475/19005651/50f402e6-8721-11e6-9c32-09b177a9e127.jpg)

![screen_shot_2016-09-30_at_1_20_38_pm](https://cloud.githubusercontent.com/assets/6569475/19005657/59174474-8721-11e6-8e66-81590d2de7f5.jpg)

All URLs that have <code>google-apps</code> should also be changed so that it says <code>g-suite</code>. 

There is also the original landing page that @ranh created for the launch, but we rarely use it, and it needs considerable editing because of new information about the product:

https://wordpress.com/google-apps/

We will need a new landing page for the product, but at the very least the URL needs to be changed to:

https://wordpress.com/g-suite

Here is the Google Cloud Brand Book:

[Google Cloud Partner Brand Book - 092816.pdf](https://github.com/Automattic/wp-calypso/files/503750/Google.Cloud.Partner.Brand.Book.-.092816.pdf)

Thank you!

/cc @breezyskies

**Comment by breezyskies** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[XS] Maintenance: Update Google Apps logo](https://trello.com/c/Am39DCe7/649-xs-maintenance-update-google-apps-logo)

**Comment by Lochlaer** [comment]
Forgot to add the download page for all new creative assets:

https://gsuite.google.com/setup/resources/logos/
