### ISSUE TITLE
Login: Quick links to open mail

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#83872]
### Details

pdDR7T-12Q#comment-1288

When requesting a login link by email, we should show quick links to gmail and outlook. Saves an extra couple of steps to open gmail in a new tab.

![image](https://github.com/Automattic/wp-calypso/assets/52076348/25637a2c-641c-408f-8eec-5ebd49aa241b)

**Comment by crisbusquets** [comment]
What options should we add? [This page](https://www.oberlo.com/statistics/most-used-email-clients) suggests that the most popular are:
- Apple (58%)
- Gmail (≈28%)
- Outlook (≈4%)

Is it possible to trigger Apple?

**Comment by simison** [comment]
Remember to add click-tracking for these.

**Comment by agrullon95** [comment]
> What options should we add? [This page](https://www.oberlo.com/statistics/most-used-email-clients) suggests that the most popular are:
> 
> * Apple (58%)
> * Gmail (≈28%)
> * Outlook (≈4%)
> 
> Is it possible to trigger Apple?

Looking at the link you provided and https://www.gmass.co/domains,
we could include links to open these email provider login pages in a new tab:

Apple (iCloud),
Gmail, 
Hotmail/Outlook, 
Yahoo,
Aol

We can start with 4/5 links and track the usage like @simison mentioned above.

@crisbusquets WDYT?

**Comment by crisbusquets** [comment]
> > What options should we add? [This page](https://www.oberlo.com/statistics/most-used-email-clients) suggests that the most popular are:
> > 
> > * Apple (58%)
> > * Gmail (≈28%)
> > * Outlook (≈4%)
> > 
> > Is it possible to trigger Apple?
> 
> Looking at the link you provided and https://www.gmass.co/domains, we could include links to open these email provider login pages in a new tab:
> 
> Apple (iCloud), Gmail, Hotmail/Outlook, Yahoo, Aol
> 
> We can start with 4/5 links and track the usage like @simison mentioned above.
> 
> @crisbusquets WDYT?

I'd start with three to test if it's useful. 5 buttons seem too much:

![check-email-3](https://github.com/Automattic/wp-calypso/assets/25607244/5de3f519-708a-4fdc-8bf8-0e93220214d4)

![check-email-5](https://github.com/Automattic/wp-calypso/assets/25607244/16dcd744-bdc0-4846-9301-5d68f5224962)

**Comment by renancarvalho** [comment]
We could detect the domain of users' email and show the proper button if we have that info, otherwise top 3?

**Comment by crisbusquets** [comment]
> We could detect the domain of users' email and show the proper button if we have that info, otherwise top 3?

Works for me :)
Here's the Figma file with three buttons: 5p3iZ99zPYfl6ronoTYEXO-fi-406_1974
