### ISSUE TITLE
Magic link: Avoid jumps and double confirmation

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#83871]
We should avoid jumping between pages and showing a double confirm to the user.

![Screen Capture on 2023-11-03 at 16-33-48](https://github.com/Automattic/wp-calypso/assets/52076348/314b4743-4e58-412f-9f7c-fd508678f8ca)

**Comment by alshakero** [comment]
This was fixed here: https://github.com/Automattic/wp-calypso/pull/84014
