### ISSUE TITLE
Theme switch from My Home > Next steps > Select a design results in error message on Atomic

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#83881]
### Quick summary

On a new Atomic site, trying to choose a new theme from the crossed-out Select a design 'next step' on the homepage results in an error page:

> We've hit a snag
> 
>It looks like something went wrong while setting up your store. Please contact support so that we can help you out.
>
> Need help? Contact support

![Markup on 2023-11-03 at 12:14:46](https://github.com/Automattic/wp-calypso/assets/27249804/19eb56ce-68eb-44fc-ad37-9d460b0a745e)

### Steps to reproduce

1. WordPress.com/start
2. Free domain
3. Business plan
4. Select an intent – I'm unsure if all intents reproduce, I chose Build intent ('promote myself or my business')
5. Select theme & Colors
6. Launchpad > Skip for now
7. Settings > Hosting Configuration > Activate
8. Return to My Home
9. Select Select a design (crossed out) from the next steps
10. Select a theme and choose Continue

### What you expected to happen

On a free test site, I'm able to change themes from that step.

### What actually happened

On the customer's AT site, they became stuck on that error page, and cannot back out of it.

URL: `https://wordpress.com/setup/update-design/error?siteSlug=SITE_ADDRESS&flowToReturnTo=free`

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment]
7258785-zen

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on AT following these steps:

1. WordPress.com/start
2. Free domain
3. Business plan
4. Build intent ('promote myself or my business')
5. Select theme & Colors
6. Launchpad > Skip for now
7. Settings > Hosting Configuration > Activate
8. Return to My Home
9. Select `Select a design` (crossed out) from the next steps
10. Select a theme and choose **Continue**

https://github.com/Automattic/wp-calypso/assets/27249804/5a0ab0a7-294d-4b4f-b65f-a3a83362b8a1

📌 ACTIONS
- Triaged
- Will update the report with these steps to replicate

**Comment by davemart-in** [comment]
Seems pretty edge case. One customer report. No updates in about a year. Going to close this one out as "Won't fix".
