### ISSUE TITLE
WooCommerce Install: the store address form is jumping when choosing country

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#83904]
#### Steps to reproduce

1. Start the WooCommerce Install flow, and proceed to the `/start/woocommerce-install/store-address` where you enter the store address.
2. Try to choose a country by typing into the country select form control.

#### What happened

As the popup list of countries appears, disappears, or changes size, the entire form content is moving/jumping around. Caused by the fact that the form is vertically centered (`align-items: center` in the `woocommerce-install-two-column-layout` mixin) and that the height of form changes. Screen capture:

https://github.com/Automattic/wp-calypso/assets/664258/92edec53-6c7e-4e0e-a698-0ee215361350

#### What I expected

The UI layout should be "stable", and any layout changes localized to the country form control. Maybe the vertical centering is a bad idea, the form should be aligned to the top.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described:

https://github.com/Automattic/wp-calypso/assets/27249804/76d1aef8-bf29-45d0-b821-e408abac566d

📌 ACTIONS
- Triaged

**Comment by davemart-in** [comment]
The dropdown list should just be set to `position: absolute` instead of `position: relative`.
