### ISSUE TITLE
Staging Site: 'Activate this Design' Button Remains on active FSE themes

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#83913]
### Quick summary

After activating to a new FSE theme in staging sites, the Congrats page shows the new theme with 'Activate this Design' button and can be clicked. When clicked, it shows "Unable to activate theme. Contact support."  

### Steps to reproduce

1. Create a staging site. 
2. Go to Themes and switch to an FSE theme. 
3. Wait for the Congrats page to show up with the new FSE theme. The  'Activate this Design' button remains and can be clicked. 

### What you expected to happen

In staging sites, when the theme has been switched to FSE, the congrats page should not have the  'Activate this Design' button. Instead, display the "Customize this design" and "View site" buttons like in AT (non-staging) and Simple sites. 

### What actually happened

In staging sites, after activating a new FSE theme, the Congrats page shows the new theme with 'Activate this Design' button as if the new theme is not active yet. 

When switching to a Classic theme, "Customize this design" and "View site" buttons appear instead. 

---

### Staging Site - switch to an FSE theme 
'Activate this Design' button appears as if the new FSE theme is not active yet. 

<img width="1290" alt="Screenshot 2023-11-06 at 12 02 22" src="https://github.com/Automattic/wp-calypso/assets/36863633/4f7ab1c1-02af-4aed-8469-e6f2f4db2352">

When clicked,  it shows "Unable to activate theme. Contact support."  
<img width="1310" alt="Screenshot 2023-11-06 at 12 02 31" src="https://github.com/Automattic/wp-calypso/assets/36863633/a654c40d-a9fb-41e1-a00e-b468dcb5d7b5">

---

### Staging Site - switch to a Classic theme 
"Customize this design" and "View site" buttons appear as expected. 

<img width="1305" alt="Screenshot 2023-11-06 at 12 17 01" src="https://github.com/Automattic/wp-calypso/assets/36863633/b4684000-9d0e-40e8-9d5f-de7707f822f6">

---

### AT non-staging sites and Simple sites 
Switching to a Classic or FSE theme works as expected. 
<img width="1310" alt="Screenshot 2023-11-06 at 12 03 26" src="https://github.com/Automattic/wp-calypso/assets/36863633/d075bf31-bd28-49f1-b3d0-1cfc38a68633">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Firefox 119, MacOS 14.1

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I've created a staging version on my test site and was not able to replicate the issue. The "Activate this design" button changes to "Customize this design": 
https://github.com/Automattic/wp-calypso/assets/9025643/0414c19c-72fa-4710-9e7b-126f97d36267



📌 ACTIONS
– Triaged
