### ISSUE TITLE
Reader: There seems to be a performance drop when following specific sites

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#83920]
Following specific sites seems to generate a performance drop when calling the `v1.2/read/following?locale=en&meta=site%2Cfeed` endpoint.

Context: p1699288638234969/1699287735.784949-slack-C0Q664T29

**Comment by mreishus** [comment]
D127969-code + https://github.com/Automattic/jetpack/pull/33980

**Comment by sixhours** [comment]
Can we call this one completed?

**Comment by sixhours** [comment]
Since both of the above related PRs have been merged, I'm calling this done. Feel free to reopen if that's not the case!
