### ISSUE TITLE
Styles Additional CSS: Update Support Link from .org to .com

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#83942]
### Quick summary

In _Styles → Additional CSS_, the 'Learn more' link leads to a .org doc instead of .com. By changing the support link to a dotcom resource, we can provide more tailored help information to our users.

### Steps to reproduce

In a block theme:

1. Go to Appearance → Editor 
2. Click on Styles
3. Click the three dots
4. Select Additional CSS
5. Click 'learn more about CSS':

![Screenshot 2023-11-07 at 4 02 43 pm](https://github.com/Automattic/wp-calypso/assets/30727666/93f7b9c8-405c-4d67-962a-93fede4ef611)

### What you expected to happen

I expected to arrive at https://wordpress.com/support/editing-css/

### What actually happened

I arrived at https://wordpress.org/documentation/article/css/

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by rickmgithub** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Replicated 
– Tested on Atomic – Replicated

📌 ACTIONS
– Feature request kept

**Comment by annezazu** [comment]
Closing this out as it was completed here: https://github.com/Automattic/jetpack/pull/38951
