### ISSUE TITLE
Subscribed button: change width and remove margin

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#83973]
Can we change the width to auto, instead of a fixed/adaptable width?
For it to be centered, we should also remove the small margin-left it has:

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/6bbe5f5b-d2af-40ed-86b8-75aaebd693b1)

The button is really big in some instances:

## Before

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/a36ec17d-1783-4790-9618-3776c2d1332c)

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/1ef2797f-80bc-41a2-9c58-762e15c19479)

## After

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/65578861-e283-4ff1-9d0b-a4d0586fda6b)

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/7a344509-84ca-4405-add1-76f38ae76e5e)

**Comment by lezama** [comment]
> The button is really big in some instances:

this comes from the block settings here:

<img width="1204" alt="Screenshot 2023-11-08 at 21 42 27" src="https://github.com/Automattic/wp-calypso/assets/104869/13b2c499-56e5-468b-9004-66c1a8f5704c">

I think there's room to improve the subscribe block settings and align them closer to the button block ones.
