### ISSUE TITLE
SCSS mixins: long-content-fade seems to not working on Single Site view

### ISSUE THREAD

**Issue by vitozev** [Automattic/wp-calypso#83974]
### Quick summary

The `long-content-fade` (see the [code](https://github.com/Automattic/wp-calypso/blob/7236a5cf2a02fab9eee5b7b8d2612215f038d17e/client/assets/stylesheets/shared/mixins/_long-content-fade.scss#L12)) used in the Site Switcher isn't working on the Single Site views on Jetpack Cloud and WordPress.com. It works fine on the Multi Site view, though.

Here's some of our previous work, which solves the same issue on WordPress.com: https://github.com/Automattic/wp-calypso/pull/65598

Here's a screenshot of how it looks now and the expected result (note the fading effect).

Actual | Expected
--|--
![image](https://github.com/Automattic/wp-calypso/assets/1749918/b55bf008-0ebb-43e2-a0aa-fb3264c97e83)|![image](https://github.com/Automattic/wp-calypso/assets/1749918/be530fb0-5290-4dc3-afa9-f976168f5455)

### Steps to reproduce

1. Visit cloud.jetpack.com
2. From the sidebar, switch to a site with a long title (alternatively, you can change the title using Dev Tools)

### What you expected to happen

The fade-out effect should be applied. The same way it works for the All sites view.

### What actually happened

Observe that the fade-out effect isn't working for the long titles

### Impact

All

### Available workarounds?

There is no user impact

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
 Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on one of my personal self-hosted sites:
![Markup 2023-11-20 at 22 27 39](https://github.com/Automattic/wp-calypso/assets/9025643/246ea5dc-a34f-4588-985d-14c9d67c0b95)
The long title does not have the expected fading effect.

📌 ACTIONS
- Triaged

**Comment by davemart-in** [comment]
Changing status from Normal to Low.
