### ISSUE TITLE
Improve Site Editor sticky notice banner

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#83984]
Let's try  some simple UI / styling improvements for this banner that shows for Global Styles and Live Preview.  I assume it is used in other cases as well? 

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/697ae3b8-f6a2-4116-9008-0109107fc656)

## Related 
- https://github.com/Automattic/wp-calypso/pull/83630
- https://github.com/Automattic/dotcom-forge/issues/4627

cc: @Automattic/lego

**Comment by autumnfjeld** [comment]
@lucasmendes-design  Perhaps this is a good easy task for Matt West next month? What do you think?

**Comment by lucasmendes-design** [comment]
+1. I think this notice needs some love as well. A modern look. Right now, it seems something different from the current UI. We also use this notice in the site preview. 

>  I assume it is used in other cases as well?

I think so. It's good to understand these cases to design something that can scale :)

**Comment by matt-west** [comment]
Here's a proposal that updates the banner to use the `info` styles and pushes the actions inline to the right:

![image](https://github.com/Automattic/wp-calypso/assets/417538/8c485f9b-1b19-4ebf-a8fc-f26a14ea96c8)

I also think we should combine this with the upgrade banner that’s shown when a free/personal user previews a Premium theme or applies premium styles. Here are some variations that address that:

![image](https://github.com/Automattic/wp-calypso/assets/417538/07a7cd9c-b6c8-43f7-a172-cd05f62bee55)

Let me know your thoughts!

Design: RcxiuWYjZGkFRdlWL7L02m-fi-1900_10862
Feedback: pekYwv-3uK-p2

**Comment by matt-west** [comment]
@autumnfjeld Do you need anything else from design to pass this to an engineer?

**Comment by fushar** [comment]
I played around with dotcom-only changes (read: custom CSS overrides), to see what we can achieve without changing anything in Gutenberg. Here is a demo:

<img width="1352" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/fa643ff2-55fc-42c9-9faa-f27c15fb6896">

Some notes:

1. It's impossible to have the theme name in bold, because the corresponding banner library only accepts a single string as the text. There is no way to target just the theme name so that we can apply some CSS to it.
2. The "Activate" button will be replaced by "Upgrade now" button, so we don't need another same button in the banner.

What do you all think? I believe this is clean enough as a second iteration.

@Automattic/lego @matt-west @lucasmendes-design

**Comment by fushar** [comment]
@matt-west Is there an emoji that I can use for the "eye icon"? It needs to be a simple unicode character (e.g. not a React component) for this to work. Currently I'm using "👁".

**Comment by taipeicoder** [comment]
> It's impossible to have the theme name in bold, because the corresponding banner library only accepts a single string as the text. There is no way to target just the theme name so that we can apply some CSS to it.

Agreed! This isn't something that can be easily overridden with CSS nor string manipulation. I propose we ignore this for now.

> The "Activate" button will be replaced by "Upgrade now" button, so we don't need another same button in the banner.

+1.

> What do you all think? I believe this is clean enough as a second iteration.

It looks much better than the current one 🙂

> Is there an emoji that I can use for the "eye icon"? It needs to be a simple unicode character (e.g. not a React component) for this to work. Currently I'm using "👁".

My two cents: Using emoji is weird and AFAIK not really on brand with our UI. Unless it's straightforward to add icons to the banner (which doesn't seem like it), I propose we skip this as well.

**Comment by fushar** [comment]
> My two cents: Using emoji is weird and AFAIK not really on brand with our UI. Unless it's straightforward to add icons to the banner (which doesn't seem like it), I propose we skip this as well.

Haha yes 😄  I just wanted to try to match with the design as close as possible. +1 on skipping this for now.

**Comment by matt-west** [comment]
Thanks @fushar!

> Is there an emoji that I can use for the "eye icon"? It needs to be a simple unicode character (e.g. not a React component) for this to work. Currently I'm using "👁".

Agree that we should skip this if it's not possible to add an icon.

> The "Activate" button will be replaced by "Upgrade now" button, so we don't need another same button in the banner.

Good catch! Agree that it's not needed in the banner.

**Comment by arthur791004** [comment]
I saw `Notice` component supports `rawHTML`, so maybe we can customize the notices as we want

**Comment by fushar** [comment]
@arthur791004: I had noticed that as well, but it will render `children`:

https://github.com/WordPress/gutenberg/blob/a4a7feb31306fa2a1a6e85d4568da432968fe6b9/packages/components/src/notice/index.tsx#L105-L107

whereas the `createXxxNotice()` action that we use, does not support passing `children` 🥲 : 

https://github.com/WordPress/gutenberg/blob/a4a7feb31306fa2a1a6e85d4568da432968fe6b9/packages/notices/src/store/actions.js#L91-L103

**Comment by fushar** [comment]
I'm closing this issue as this is shipped. The issue with stacked banners is tracked here:

- https://github.com/Automattic/wp-calypso/issues/85538
