### ISSUE TITLE
Settings: getting a mixed content warning on general settings

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#84]
Looks like the preview images are served via http.

Reproduced at https://wordpress.com/settings/general/k2testblog.wordpress.com once Show Related Content was selected and "Use a large and visually striking layout" was checked:

![image](https://cloud.githubusercontent.com/assets/7233112/11245273/d5329e8c-8ddf-11e5-9c76-dfbbcb148c96.png)

Here's the URL of one of the linked photos:

http://en.blog.files.wordpress.com/2012/08/1-wpios-ipad-3-1-viewsite.png?w=350&h=200&crop=1

**Comment by rralian** [comment]
I believe this was fixed as part of the code scrub to move to oss. Can you give it another test @hoverduck?

**Comment by hoverduck** [comment]
Verified, I can't reproduce.  Closing.
