### ISSUE TITLE
Update Related Posts Doc URLs to .com

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#84029]
### Quick summary

Related Posts settings for dotcom sites link to Jetpack docs instead of WordPress.com docs. We should link to dotcom docs to give users information tailored to their experience.

### Steps to reproduce

1. Navigate to _Settings → Reading
2. Scroll down to Related Posts.
3. Click the 'i' information icon and 'Learn more'.
4. Click the "related posts added using the block editor." link.

The same settings can also be accessed from _Tools → Marketing → Traffic_ #81903

### What you expected to happen

I expected to arrive at https://wordpress.com/support/related-posts/ for both links

### What actually happened

I arrived at https://jetpack.com/support/related-posts/ for both links

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

This change applies only to WordPress.com sites (simple and atomic.) Jetpack-connected self-hosted sites remain the same.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
![CleanShot 2023-11-18 at 15 54 04@2x](https://github.com/Automattic/wp-calypso/assets/14153300/2452be39-d4dd-42d0-a5a2-0dad26ecad09)

📌 ACTIONS
- Triaged
- Switched Priority to Low

**Comment by donalirl** [comment]
This has been updated, although I'm not sure where (@ivan-ottinger maybe you know?)

**Comment by ivan-ottinger** [comment]
Thanks for the ping, @donalirl! 

I have addressed this as a part of https://github.com/Automattic/wp-calypso/pull/86851.
