### ISSUE TITLE
Passwordless flow: fix line-height and margin

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#84041]
The heading and first paragraph on the passwordless flow (magic link) doesn't look right.

### Current

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/a43e6157-e7de-471b-bccc-1007d5975a9d)

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/f0dd97ae-28a6-440f-894e-bafad270ea13)

### Proposal
* Change h1's line-height from a fixed `57px` to `120%`
* Change margin to `margin: 4px 0 24px 0` on the p below the heading (`.magic-login__form .logged-out-form p`)

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/65b0c522-4511-424f-9f60-9c67d6cffbe2)

**Comment by simison** [comment]
@Automattic/vertex is this still relevant or can be closed?

**Comment by escapemanuele** [comment]
I think this can be closed, PR has already been merged 👍
