### ISSUE TITLE
Refactor the fix for skipping WC.com software registration on staging sites.

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#84059]
While https://github.com/Automattic/wc-calypso-bridge/issues/1335 was fixed by D128279-code, we'd like to do some refactoring.

(The following notes are taken from @a8caustin 's great comments on D128279-code)

We have worked on removing supplementary functionality from the core transfer process. The Transfer Manager Initialize Transfer will be moved into a flat function and refactored at some point soon. 

Let's use this change as an opportunity to move this woo registration code into the woa_transfer_pre_provision action (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sgenafsref%2Spynff%2Qgenafsre%2Qznantre.cuc%3Se%3Qq10p5p4r%23172-og) which was created to allow for teams to tap into the transfer process without altering core transfer code.

There is no preferred place it should be put (other than outside Transfer Manager/Atomic/WoA code).

`get_site_url` cannot be trusted here, before or after the domain transfer. It can't be trusted until post-transfer. But this code is using the transferring domain. Which is available in the `$params` arg of the hook. They are the same params passed to initialize.

Unless it needs to be done before the Atomic Site is created, it would probably be better in post-transfer, which runs after the site transfer is finalized and is meant for configurations like this.

P9HQHe-1Ah-p2

**Comment by sixhours** [comment]
Started working on this in D130222-code

**Comment by sixhours** [comment]
This fix has shipped to production in D130515-code
