### ISSUE TITLE
Like and Comment Buttons are Missing in the Reader for Atomic Sites

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#84055]
### Quick summary

The Like and Comment buttons have gone missing in Reader and this seems to affect only Atomic sites.

<img width="419" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98869/c3189ac0-2eb6-4a35-a37d-243237a5c048">

### Steps to reproduce

1. Open the Reader and follow any site that's Atomic
2. Open the site's feed in the Reader
3. You can also click on any post in the feed

### What you expected to happen

I expected to see the Like and Comment buttons displayed below the posts in the Reader, allowing me to like the post or comment on it without having to visit the live site.

### What actually happened

There are no Like and Comment buttons.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by druesome** [comment]
7292405-zen

**Comment by retnonindya** [comment]
I can't replicate this 🤔  I checked their feed, and I can see all buttons appear as usual:
https://wordpress.com/read/feeds/143022158

![Screenshot 2023-11-10 at 9 30 49 AM](https://github.com/Automattic/wp-calypso/assets/44726232/6cc1d391-0a15-45ac-827b-723060f2f637)

I also SU-ed as the user, and see the buttons are all there. It might be browser/cookies issue? 🤔

**Comment by druesome** [comment]
@retnonindya Thanks for checking.  So weird, I see them now too!  Perhaps something got fixed that we aren't aware of?  I'll close this issue up for now.
