### ISSUE TITLE
Set up your site task (setup_general) is always marked as complete

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#84058]
### Quick summary

The "Set up your site" task (`setup_general` on the back end) is always marked as complete in the fullscreen launchpad, which can be incorrect. Furthermore, this task is disabled, which makes it impossible to fix the issue from the launchpad. We need to allow users set up their site title and tagline.

### Steps to reproduce

* Create a new site from (https://wordpress.com/start)
* Pick a domain and a plan (which can both be free)
* When you get to the step that asks what you want to do with your site, pick "Other"
* Pick a design for your site
* When you get to the fullscreen launchpad, you'll notice that the "Set up your site" task is marked as complete, and is not clickable

### What you expected to happen

The task should not be completed, and I should be able to click on it to set up my site title and tagline.

### What actually happened

The task was marked as complete and I couldn't interact with it.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I've looked at the back end code and I see that this is also an issue on the back end, as we have this task marked as complete in all cases. What we should be doing is marking the task as complete when the user specifies a site title and site description, which would be best-handled on the back end, most likely by hooking into the option-specific `'update_option_[option_name]'` actions. (It looks like we already have similar logic for the more specific `site_title` task.)

We also need to work out whether we can show the relevant screen to update the site settings for the user, as the screen's availability will depend on the Stepper flow that we happen to be in.

**Comment by daledupreez** [comment]
@andres-blanco, was this issue fixed by your work in #84776? Or is there more to do for this issue?

**Comment by andres-blanco** [comment]
> @andres-blanco, was this issue fixed by your work in #84776? Or is there more to do for this issue?

No, we still need to do the backend changes so the task is not marked as complete by default. I will do that today :)
