### ISSUE TITLE
Newsletter Tiers: visual adjustments

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#84067]
There are a few visual adjustments we should improve. They will improve the modal's hierarchy and visual consistency.

See below for visual references:
- [x] h2 title: Margin bottom should be 16px instead of 20px
- [x] Monthly/Yearly selector: Margin bottom should be 16px instead of 20px
- [x] Monthly/Yearly selector: The font color for the selected option should be the same color as the check icon. If there are accessibility concerns due to the variety of themes we have, change the icon color to match the font.
- [x] Tier name: shouldn't have a margin-bottom
- [x] `wpsm-plan-item selected`: the background should match the monthly/yearly selector background for the active option instead of gray
- [x] submit button: should have a 16px distance from the last item

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/ce937007-4622-45f9-86e3-0a5fd73f3f42)

**Comment by chrisfromthelc** [comment]
@crisbusquets One question related to these changes that came up while I was working on this. What should the space I've marked with the red arrows be? It feels a big too big to me...right now it's 56px.

<img width="440" alt="Screenshot 2023-12-04 at 10 31 58 PM" src="https://github.com/Automattic/wp-calypso/assets/8002138/75e7cefd-2af8-461f-8e4b-8b57e23ebd48">

**Comment by crisbusquets** [comment]
> @crisbusquets One question related to these changes that came up while I was working on this. What should the space I've marked with the red arrows be? It feels a big too big to me...right now it's 56px.
> 
> <img alt="Screenshot 2023-12-04 at 10 31 58 PM" width="440" src="https://private-user-images.githubusercontent.com/8002138/287919791-75e7cefd-2af8-461f-8e4b-8b57e23ebd48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Njk1MjgsIm5iZiI6MTcwMTc2OTIyOCwicGF0aCI6Ii84MDAyMTM4LzI4NzkxOTc5MS03NWU3Y2VmZC0yYWY4LTQ2MWYtOGU0Yi04YjU3ZTIzZWJkNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMDk0MDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzMzNGI2NDllOWJjMTk3N2MyMDljNWEzNjZmYjIxZGJlODI2MTVjYTJiNzQ4MTk2NTBhNWFmOGY3MTdhNGU5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f7sF_UdgLcNtF34CmmMi4HQizGlqbpOH7TF8i4h9Wnw">

I agree, it's too big. Spacings in Figma are a bit different (20px less or so):
- The padding for the "header" is 20px (top and bottom)
- The distance between the header and the modal title (`Choose a tier...`) is 16px

![modal-spacing](https://github.com/Automattic/wp-calypso/assets/25607244/447052f2-9cc0-43e3-ba61-f20fae65571e)

**Comment by chrisfromthelc** [comment]
Thanks for looking! I'll get this taken care of.

**Comment by chrisfromthelc** [comment]
@crisbusquets I've got these changes in my latest diff (and a couple of additional things I spotted).

When you get time (absolutely no rush; I'll push my current changes and circle back), can you either make a "for real final" Figma with all of the the dimensions, or point me to which ones those would be the absolute final ones for the whole modal? I looked through the existing Figma but wasn't 100% sure which design/iteration I should take as the final set-in-stone design.

A couple of the small things I caught today I'm pretty sure I had updated in a previous iteration of design corrections. It's quite possible that they were just missed, or perhaps inadvertently changed with the myriad of updates we're doing to the modal lately, but I do want to go over this with a fine-toothed comb and ensure that I've gotten everything to your specifications. 

It would be excellent if you could just make a new issue in https://github.com/Automattic/gold and assign it directly to me when you get around to doing this. I'll do the nitpicking and get anything I find cleaned up. Thanks again!!!

**Comment by crisbusquets** [comment]
Hi @chrisfromthelc, thanks for the ping!

Here you'll find the last updates regarding spacings (4YBqH8l0WWmJ9bF3EmuMOb-fi-398_3965) and typography (4YBqH8l0WWmJ9bF3EmuMOb-fi-463_1374).

They're the same specs I shared in the initial issue, I only added what we discussed about the modal header.

**Comment by chrisfromthelc** [comment]
I spent some time double-checking things, and fixed another couple of nitpicky issues (@chrismccluskey saw a line-height issue and I also fixed the letter-spacing on the label). This is now merged, and should be all set.
