### ISSUE TITLE
Newsletter Tiers: Free option more prominent

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#84065]
As mentioned here https://github.com/Automattic/gold/issues/163 

### Current vs Proposal

Figma link: 4YBqH8l0WWmJ9bF3EmuMOb-fi-384_4064

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/51dfea79-1ac2-4576-903d-5283c553e7ca)

https://github.com/Automattic/wp-calypso/assets/25607244/028750c3-a0a3-4843-a87a-332c1a4ff3a3

### Specs

Figma link to this frame: 4YBqH8l0WWmJ9bF3EmuMOb-fi-398_3965

**Comment by simison** [comment]
@millerf how does the above design proposal look to you?

Meanwhile a quick fix would be just adding the underline and more spacing in the modal as per original design.

**Comment by millerf** [comment]
Follow-up of https://github.com/Automattic/gold/issues/163

@chrisfromthelc can you take this whenever you can?

**Comment by chrisfromthelc** [comment]
D129505-code

**Comment by millerf** [comment]
@chrisfromthelc Answered in the PR.

**Comment by chrisfromthelc** [comment]
This is merged.
