### ISSUE TITLE
Support Site Footer content overlapping itself when screen size narrows

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#84078]
### Quick summary

Footer content CTAs are overlapping one another when the browser window is at certain widths, between around 100px and 780px

![Markup on 2023-11-09 at 15:35:20](https://github.com/Automattic/wp-calypso/assets/27249804/6d6741f4-7f0c-4e96-8b73-f6ca61a00b20)

### Steps to reproduce

1. Open a Support site doc, such as https://wordpress.com/support/domains/incoming-domain-transfer/
2. Use browser responsiveness tools or adjust the width of your browser
3. Observe between ~1000px and ~780px that the CTAs in the footer overlap one another

### What you expected to happen

Content to respond to size changes without fixed columns/overlapping text.

### What actually happened

https://github.com/Automattic/wp-calypso/assets/27249804/3ff9dd05-4df9-499f-9d1f-6d1536d5cd31

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Logs or notes

Observed in Firefox 119.0.1 (64-bit)

**Comment by cuemarie** [comment]
FYI @Automattic/vertex in case this might be a quick fix? 🤞

**Comment by escapemanuele** [comment]
Hey @cuemarie, thanks for the feedback!

I see it like this though:
![Screenshot 2023-11-10 at 12 31 07](https://github.com/Automattic/wp-calypso/assets/52076348/5134b222-b452-4343-ac1d-07571bba53d3)

What browser did you use? I tested with chrome

**Comment by alshakero** [comment]
Can confirm this is fixed now.
