### ISSUE TITLE
The "My sites" button of "Classic style" sites does not point to the list of sites if you are on a Calypso page

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#84093]
### Quick summary

In a site with the Admin interface "classic style" selected, the top-left "My sites" button brings you to the dashboard of the current site and not to a list of sites. This only happens if you are visiting a page that has not classic counterpart.

### Steps to reproduce

1. In `/hosting-config/__BLOG__` select "Classic style"
2. Ensure that the left menu links work (example: `/wp-admin/edit.php?post_type=page`) or others
3. Then goes to a page that is working only on Calypso such as `/hosting-config/__BLOG__`, `/me` or others
4. Click "My Sites"

### What you expected to happen

You should be redirected to `https://wordpress.com/sites`

### What actually happened

You are redirected to `https://wordpress.com/home/__BLOG__`

### Impact

All

### Available workarounds?

There is no user impact

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS 
Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue. The "My Sites" button does not point anywhere:
![Markup 2023-11-21 at 15 36 52](https://github.com/Automattic/wp-calypso/assets/9025643/7ba2b785-f33b-4e8d-8e12-5f62a4be6dd7)

📌 ACTIONS
Triaged

**Comment by wojtekn** [comment]
I'm closing it as it's not an issue anymore. Currently, WP Admin shows 'Browse sites', which points to https://wordpress.com/sites.
