### ISSUE TITLE
Launchpad: Remove language checks that were introduced at the feature launch

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#84095]
PR where the language checks were introduced: https://github.com/Automattic/wp-calypso/pull/84051.

🔴  Blocked until the Mag16 languages translations are in.

Translation status: https://translate.wordpress.com/deliverables/overview/9655858/

**Comment by yansern** [comment]
Done.

**Comment by yansern** [comment]
https://github.com/Automattic/wp-calypso/pull/84705
