### ISSUE TITLE
Color Settings in Customizer Do Not Apply When Comments Enabled

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#84132]
### Quick summary

Customizer settings for colors are defaulting to the theme's default colors despite custom colors set. This only happens when comments are enabled on a page. If comments are disabled on the page, custom colors work as expected. 

7280454-zd-a8c

### Steps to reproduce

1. Install a classic theme such as Dara, Radcliffe 2, or Baskerville 2 on a Simple site.
2. Create a page and enable comments in Discussion Settings: ![6o4zIV.png](https://github.com/Automattic/wp-calypso/assets/121042930/71171dbe-03fe-4628-81e1-83ea870e6da0)
3. Set custom Colors under Appearance > Customize > Colors & Backgrounds and Save (notice they don't apply in preview and theme's defaults show instead): ![IIHKp3.png](https://github.com/Automattic/wp-calypso/assets/121042930/a536645c-6781-4503-b200-660e712dc4d8)  
4. View page and see the theme's default colors are applied instead of custom colors: ![915lrE.png](https://github.com/Automattic/wp-calypso/assets/121042930/4a85cb78-aeae-4ae4-983a-15d62bd77410)
5. Disable comments in Discussion settings for the page, view the page, see correct colors applied: ![yMAYMx.png](https://github.com/Automattic/wp-calypso/assets/121042930/20213acd-28db-4d17-bbe4-e7e0ac750ffb)

### What you expected to happen

The correct customizer color settings should apply regardless if comments are enabled or disabled. 

### What actually happened

Colors only display correctly if comments are disabled. When comments are enabled, CSS is loaded in a different order, causing the theme's default color settings to override the custom colors set in the Customizer. When hard refreshing, you will see the custom colors display briefly before being overridden by theme's default colors. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

This was tested and reproducible on Simple sites with various Classic Themes including Dara, Radcliffe 2, and Baskerville 2. Unknown if AT sites are affected.

**Comment by inaikem** [comment]
I encountered the error here, too: 7280459-zd-a8c

I've advised the user they can fix this temporarily by deactivating comments on affected pages. 

@alshakero, I'm not 100% certain but it feels like this might be related to #83982 (at least in spirit).

**Comment by alshakero** [comment]
Hi! It is related, can you confirm this happens when you're not proxied? We pulled this version, and now it only affects proxied users.

**Comment by mgozdis** [comment]
@alshakero Yes, this was happening when not proxied as users were reporting it. Currently, I am only seeing the issue when proxied now so it seems fixed for users. Can you confirm?

**Comment by alshakero** [comment]
Yes, it was fixed here: p1699612343673279/1699464090.252049-slack-C02FMH4G8
