### ISSUE TITLE
Remove registration notice for Subscriber role

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#84145]
### Quick summary

In order for people to enrol in courses, the _Anyone can register_ setting must be enabled. After going through the Sensei onboarding flow, this setting is enabled by default, which displays a confusing notice:

![Screenshot 2023-11-13 at 8 23 54 AM](https://github.com/Automattic/wp-calypso/assets/1190420/7dbfc90d-4fed-4bd5-89da-a79222596a76)

Although the notice is dismissible, it should be hidden for all users with the Subscriber role.

### Steps to reproduce

1. On an Atomic site with Sensei LMS activated, navigate to _Settings_ > _General_.
2. Enable the _Membership_ setting. 
3. See the notice.

### What you expected to happen

No notice to appear.

### What actually happened

A notice is displayed.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

This notice should still be visible for other roles besides Subscriber.

**Comment by renatho** [comment]
PR on `wpcomsh` repository: https://github.com/Automattic/wpcomsh/pull/1574

**Comment by renatho** [comment]
https://github.com/Automattic/wpcomsh/releases/tag/v3.13.66
