### ISSUE TITLE
Components: add missing toggle control to UI devdocs page

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8415]
I noticed the UI Component for toggling a setting off or on isn't on our Design DevDocs page: `devdocs/design`

<img width="399" alt="a11y-fix-like-app-1s-0s" src="https://cloud.githubusercontent.com/assets/66797/19047762/09bdac72-8958-11e6-9a66-52be992f5b7d.png">

Can we add that UI component into the page?

I'd like to also suggest using a better accessible version, similar to <a href="http://www.imore.com/how-to-enable-on-off-button-labels-better-accessibility-iphone-ipad">iOS on/off visibility</a> for easier and more detectable state for anyone with low-sight or colorblindness. See #8416

**Comment by rickybanister** [comment]
Toggles are represented in the devdocs within the other form components section. It could be improved, but they are there.

**Comment by lancewillett** [comment]
Darn! I'd missed it at the bottom of the form fields group https://wpcalypso.wordpress.com/devdocs/design/form-fields

My bad — sorry for the noise.

See #8416 for the suggestion for a11y.

**Comment by mtias** [comment]
@lancewillett no noise! I think we should break all the form components into separate permalinks (like Button is). That will give us search and better discoverability. Would you mind creating an issue for that?

**Comment by lancewillett** [comment]
New issue created: #8429
