### ISSUE TITLE
Components: consider accessible toggle control like iOS

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8416]
Split from #8415

I'd like to suggest using a better, ore accessible version of on/off labels similar to <a href="http://www.imore.com/how-to-enable-on-off-button-labels-better-accessibility-iphone-ipad">iOS on/off visibility</a> for easier and more detectable state for anyone with low-sight or colorblindness. Thoughts on defaulting to showing the 1 and 0 in the toggle?

![ios-example](https://cloud.githubusercontent.com/assets/66797/19047877/9bc4dc94-8958-11e6-8e18-36d85ab1d538.png)

**Comment by drw158** [comment]
Does Android have on option like this?
