### ISSUE TITLE
Audiomack link embed 

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#84169]
### Quick summary

The Audiomack link created before 2023.11.14 can embed into the post, like :

https://audiomack.com/ttcath/song/monday-32-ot-a-2023-mass-homily 

but this one, cannot be embed into the post.

https://audiomack.com/ttcath/song/tuesday-32-ot-a-2023  

I try to use another source, like:

https://open.firstory.me/embed/story/cloyi3qm2000001tociwxbym2 

It work.

### Steps to reproduce

1.create a post
2. choose embed block, paste any link from Audiomack website
3. the block return 404 error, the page not found

### What you expected to happen

The Audiomack link mut work as usual.

### What actually happened

The Audiomack link not work

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
This is a continuation of this original report:

https://github.com/Automattic/wp-calypso/issues/83337

I can confirm the embeds are not working nor with the "creators" subdomain on it as noticed [here](r278584-wpcom). Can we get more eyes on this @jeherve, please?

PS: I also found this Slack thread which may point to a CORS issue: p1697825963316189/1697823423.625519-slack-C03TY6J1A

7311333-zen

**Comment by ttcath** [comment]
Dear @Robertght thx so much for your help.  @jeherve could you help to fix the problem which I report twice? thx!

**Comment by jeherve** [comment]
> this one, cannot be embed into the post.
> [audiomack.com/ttcath/song/tuesday-32-ot-a-2023](https://audiomack.com/ttcath/song/tuesday-32-ot-a-2023)

It would appear that there are some issues with Audiomack embeds at the moment.

Audiomack's oEmbed setup uses /embed links like this one:

- Song's page: https://audiomack.com/asakemusic/song/lonely-at-the-top-remix
- oEmbed's page: https://creators.audiomack.com/oembed?url=https%3A%2F%2Faudiomack.com%2Fasakemusic%2Fsong%2Flonely-at-the-top-remix
- The iFrame tries to fetch content from https://audiomack.com/embed/song/asakemusic/lonely-at-the-top-remix
- That page above returns a 404 error, so embeds cannot work.

I've contacted Audiomack about this to let them know about the problem. Since you're an artist on the platform, could you contact them as well to let them know about the problem? Hopefully they'll be able to fix the problem on their end.

**Comment by ttcath** [comment]
Dear @jeherve 

I found that the entier embed link which we do embed before(like:https://ttcath.org/2022/11/14/tuesday-c-ot-33-2022-mass-text-grm) it work, and can display the songs at the page, the link from Audiomack is:https://audiomack.com/ttcath/song/tuesday-c-ot-33-2022-chinese-homily, after i wrote a report here, it returns 404.

I submit a ticket to Audiomack ,but till now ,no reply from them. Could you check the entire posts which under these filter:

CATEGORIES [每日弥撒](https://ttcath.org/category/%e6%af%8f%e6%97%a5%e7%a4%bc%e4%bb%aa/%e6%af%8f%e6%97%a5%e5%bc%a5%e6%92%92/)•TAGS [每日礼仪](https://ttcath.org/tag/%e6%af%8f%e6%97%a5%e7%a4%bc%e4%bb%aa/)

Thx

**Comment by ttcath** [comment]
@jeherve  please help to fix. thx

**Comment by ttcath** [comment]
Also, I report the same problem at https://github.com/audiomack/audiomack-api-examples/issues/3, please help to have a look at them. @Robertght @jeherve thx

**Comment by ttcath** [comment]
@Robertght  Please reopen this tickets, thx

**Comment by jeherve** [comment]
I see the problem has now been fixed on Audiomack's end. Embeds now work again.

If you still spot some failed embeds after clearing your browser's cache, I would recommend that you contact the Audiomack team directly about it, and give them some examples so they can investigate.

*********

You'll also note that I deleted some of your past comments. As I mentioned in the past, please do not @mention specific people or post multiple comments to "bump" an issue. Once you've opened an issue, it will be triaged and addressed.

**Comment by ttcath** [comment]
Okay then. So this is not a bug from WordPress, just  Audiomack's problem?

**Comment by jeherve** [comment]
Correct.

**Comment by ttcath** [comment]
okay then
