### ISSUE TITLE
Blog Theme Starter Content: Support setting post as sticky

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#84173]
## Problem

Currently, when we create a new site with Tronar theme, we insert some starter posts using the demo site's featured images. However, in the demo site, one of the post is sticky, but we don't set any sticky post among the starter posts. This makes the resulting site to look different from the preview:

|Design Picker|Resulting Site|
|-|-|
|![image](https://github.com/Automattic/wp-calypso/assets/1525580/585a60e2-14fc-4695-8058-9f491c067734)|![image](https://github.com/Automattic/wp-calypso/assets/1525580/ea9ad2db-9bf8-4e9a-a059-aa9e651acb34)|

See also: paYJgx-4jI-p2

## Possible Approach

When fetching the featured images from the demo site, also check whether the post is sticky or not. If it is, then set the corresponding starter post as sticky in the resulting site as well.

@Automattic/lego @iamtakashi

**Comment by arthur791004** [comment]
Proposing D128861-code to resolve this issue 🙂

**Comment by arthur791004** [comment]
Closing it via D128861-code

**Comment by iamtakashi** [comment]
Perfect⭐  Thank you for sorting this out!
