### ISSUE TITLE
Non-applicable features in Woo Express displayed in free trial plans page

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#84178]
Internal discussion: p1696962790637679/1696891061.457509-slack-C03Q87XT1QF

It seems non-available features are displayed in free trial plans page.

Excerpt:

```
Remove from In-product plan features list:
- Mentions to Referral Program (Due to the AutomateWoo refer a friend add-on Not being included)
- Mention of Customer Birthday Emails (Due to the AutomateWoo Birthdays add-on Not being included)
- Mention of Loyalty Points Program (Due to the  Points and rewards Extension Not being included)

Remove or rephrase on landing page and in-product list
- Mentions of "Customizable Product Kits" or "Assembled Products and kits" (Due to Composite Products not being included)
```

#### Steps to reproduce

1. Go to https://woo.com/start and go through NUX until creating a free trial site
2. In the new site's dashboard, go to Upgrades > Plans page
3. Observe the features mentioned above is displayed

**Comment by manospsyx** [comment]
@ilyasfoo is this good to close?

**Comment by ilyasfoo** [comment]
Thanks for the ping! Yes this is good to close 👍
