### ISSUE TITLE
Could not Add Comments unless Privacy & Cookies banner is accepted

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#84193]
### Quick summary

Comment sections could not insert comments, text until the "Privacy & Cookies" banner is accepted.

### Steps to reproduce

1. Visit a page or post with comments enabled
2. Attempt to insert a comment

### What you expected to happen

Comments can be entered as normal

### What actually happened

The comments section could not be commented until the "Privacy and Cookie" banner has been accepted

<img width="1680" alt="image" src="https://github.com/Automattic/wp-calypso/assets/34882260/5070db66-1742-4f38-b98c-3fc061778c61">

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by edwinho89** [comment]
7308860-zd-a8c

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Replicated
– Tested on Atomic: Could Not Replicate

📌 VIDEO

Video recording:

https://github.com/Automattic/wp-calypso/assets/2540430/23084dd6-4bd3-4ce0-b335-ca35059044d5

**Comment by ouikhuan** [comment]
Doesn't seem able to reproduce it anymore. I'm closing the issue for now, but feel free to reopen it again if you spot anything that's going wrong.
