### ISSUE TITLE
Reply on Comments not visible until refreshing the page

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#84194]
### Quick summary

Reply on comments are not visible until the page is refreshed

### Steps to reproduce

1. Visit a page or post with comments enabled
2. Comment on the page or post (parent comment)
3. Reply to the main comment above (child comment)

### What you expected to happen

Both comments (parent and child) are shown on the comments section.

### What actually happened

- Only parent comment is shown.
- You will need to refresh the page for the child comment to show up.

Before refreshing the page:
<img width="1148" alt="image" src="https://github.com/Automattic/wp-calypso/assets/34882260/20a22be4-17ae-4480-84bd-8b1f6738edc0">

After refreshing the page:
<img width="1181" alt="image" src="https://github.com/Automattic/wp-calypso/assets/34882260/5716047f-a41c-4c06-b1ec-ec6f994057d5">

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by edwinho89** [comment]
7308860-zd-a8c

**Comment by edwinho89** [comment]
7304973-zd-a8c

**Comment by dev-sabbir** [comment]
7279514-zd-a8c

**Comment by edwinho89** [comment]
7293977-zd-a8c

Below is what was commented:

> On a technical note, it took me several iterations before I was able to post this comment. I was not able to add my email and name as I always do – That area was not present. I then copied my message (it is important of course), and returned to your column several times attempting to make the post. Finally I pasted my text, placed the cursor at the end of the last character and then hit the “Enter”/ return key on my keyboard, and the login email and name area suddenly appeared.

> Also, a couple of subscribed readers are now reporting that they are no longer being notified via email of new posts on the blog. One uses Earthlink for email, another a small local provider. Neither has reported finding notifications in trash or spam, so it's possible that their new-post notifications are being blocked at the provider level. I've asked them to check.

> Meanwhile, I've played with a few of the recommended Kubrick replacements on some unused blogs I keep tucked away and can't say I like any of them very much. And I still dislike the Block Editor. I'm no engineer, but I self-hosted a WP blog for years and helped manage a custom build for a magazine when I was still in the journalism game, and the Block Editor feels — to me, at least — as though it was designed for efficiency on your end, not ease of use on mine.

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Could Not Replicate 
– Tested on Atomic: Could Not Replicate 

📌 VIDEO

https://github.com/Automattic/wp-calypso/assets/2540430/12633f44-9f10-4745-afce-e2edfb0e6a22



📌 ACTIONS
– Requested author feedback


📌 Message to Author

@edwinho89 Thanks for the report.
I wasn't able to replicate this on a test site, I wonder if I am missing something?

**Comment by edwinho89** [comment]
@filipanoscampos Thanks for getting back! After revisiting the issue, I am still able to reproduce on Firefox and Safari browsers, maybe because they're unproxied?

Surprisingly, it also happens to me when adding a parent comment, so it isn't only affecting child comments.

https://github.com/Automattic/wp-calypso/assets/34882260/e4d8826b-d221-4605-b5bd-ae621d948bc3

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Replicated
– Tested on Atomic: Replicated

📌 FINDINGS

Replicated while unproxied on the Safari browser.

Thanks @edwinho89!

**Comment by gavande1** [comment]
I tried replicating the problem on my test site during my groundskeeping rotation, but I could not reproduce the issue. While testing, the replied comments were shown correctly. I tested for this behaviour in Chrome, Safari, Firefox, and Arc. 

https://github.com/user-attachments/assets/8318bd62-b385-4107-8714-95645dec3fc3

**Comment by gavande1** [comment]
@filipanoscampos Are you still able to replicate the issue? If not, Can we mark this as closed?

**Comment by gavande1** [comment]
I will go ahead and mark this closed. Feel free to reopen the issue if needed.
