### ISSUE TITLE
Site Editor: Cookie banner reappears

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#84206]
### Quick summary

Even though I don't see the cookie banner on the dashboard (presumably I have accepted cookies), I still see it when the Site Editor loads.

### Steps to reproduce

1. Create a new user account
2. Go to Dashboard and there is no cookie banner (not sure if I accepted or not)
3. Go to Site Editor

### What you expected to happen

No cookie banner to show

### What actually happened

The cookie banner showed.

<img width="1048" alt="Screenshot 2023-11-15 at 17 41 20" src="https://github.com/Automattic/wp-calypso/assets/275961/94ae168f-c43a-4d93-a6c5-4f83dd48da14">

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to replicate the issue. Cookie banner was not displayed on a new account/site:
![Markup on 2023-12-04 at 22:08:50](https://github.com/Automattic/wp-calypso/assets/9025643/6a7ffa43-2c98-44e4-8be7-3975f8117f8b)

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)
