### ISSUE TITLE
Jetpack Subscription forms cause page to refresh instead of sending confirmation email

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#84204]
### Quick summary

Reported in 7311112-zd-a8c. Able to replicate on the user's site, but not yet able to reproduce elsewhere.

This site has three different types of Jetpack subscription forms, only one of which actually works:

1. Legacy Jetpack subscription footer widget (not working);
2. Newsletter pop-up subscription form from _Settings > Newsletter_ (not working);
3. `blog_subscription_form` shortcode at the bottom of posts (working).

Also tested a Subscribe block in their footer, which _did_ work.

For the two that do not work, after entering an email and clicking the button to subscribe, the current page just refreshes (with `/#` appended to the URL). No confirmation message or pop-up is shown, and no confirmation email is sent.

### Steps to reproduce

On the user's site:

1. Scroll down to the footer. Fill out an email address and click the button to subscribe. 
2. Click on any of their posts and begin scrolling until the pop-up subscription form appears. Fill out an email address and click the button to subscribe.
3. Scroll to the bottom of a post to find a subscription form. Fill out an email address and click the button to subscribe.

On a test site:

1. Unsure if the legacy subscription widget can still be added. If a test site already has one, test it as above.
2. Activate the pop-up subscription form from _Settings > Newsletter_. Test it as above.
3. Insert the [subscription shortcode](https://wordpress.com/support/blog-subscription-shortcode/) on a post/page. Test it as above.

### What you expected to happen

All subscription forms should work regardless of how they were created.

### What actually happened

Only the Subscribe block and `blog_subscription_form` shortcode seem to work on this site. Unable to reproduce on a test site (including with the same retired theme on a WoA test site) yet.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Theme: `Perle` (retired premium theme)
Reproduced issues on Chrome and Firefox; doesn't seem browser dependent. No browser or network console errors seen.

Currently asking the user to replace their footer widget with a Subscribe block, but also asking if they mind creating a staging site to test for plugin conflicts. Unsure if this is a broader issue beyond this one user yet.

**Comment by ckcelite** [comment]
I am having the exact same problem on 4 different websites running 4 different standard themes. One in particular is using Hello theme. Page refreshes, does not give any text or info to user and does not collect their email address in the subscribers page.
I have tried using [blog_subscription_form] and [jetpack_subscription_form] and neither work.

**Comment by devNigel** [comment]
Another similar report: 7114788-zd-a8c

In this particular instance, the user was complaining page refreshing and loading to the top after subscribing.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate 

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

@devNigel If is just about the page jumping to the top and not about an error with the confirmation itself, that is the subscribe button working as expected! If you'd like to suggest a change so that the page will not refresh and jump to the top, please submit a feature request!
