### ISSUE TITLE
Launchpad: ?siteSlug= shows the wrong site address

### ISSUE THREAD

**Issue by RafaelFunchal** [Automattic/wp-calypso#84218]
### Quick summary

While creating a brand-new website, the flow shows the URL `https://wordpress.com/start/plans?siteSlug=rafaelfunchalexport.wordpress.com`.

`siteSlug=` is probably reading the Primary Site option saved on Account Settings. As a HE, I understand that it might be used to track where the user started. Still, as a user, seeing the address for a different site in the browser is weird when you're trying to set up a new website with a completely different address (rfcft202311.wordpress.com in this scenario).

### Steps to reproduce

1. Start a site on My Sites > Add new site.
2. On Choose your domains, click on a free address.
3. Click on Continue.
4. On Choose your flavor of WordPress, the URL in the browser address shows ?siteSlug=rafaelfunchalexport.wordpress.com (The Primary Site set on my account).

### What you expected to happen

As I'm creating a brand new site, I expected to see the address of that site on the browser or no address at all.

### What actually happened

The address of a different website was displayed, which is kinda confusing.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

https://whatismybrowser.com/w/XBWJJHS

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS 
– Tested on Simple – Replicated 
– Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate the issue on my new site, the URL of the primary site for the account is visible when creating a new site.
![Markup 2023-11-20 at 21 38 54](https://github.com/Automattic/wp-calypso/assets/9025643/03957917-73fe-4f2a-9d76-ecc1523261df)

📌 ACTIONS
– Triaged

**Comment by andres-blanco** [comment]
Hi @RafaelFunchal I cannot reproduce this issue. Let me know if you are still seeing this, otherwise we can close this.

**Comment by andres-blanco** [comment]
Cannot reproduce. Closing

**Comment by RafaelFunchal** [comment]
Sorry, @andres-blanco . I didn't see the previous ping.

It is safe to close the issue. I couldn't reproduce it anymore.
