### ISSUE TITLE
Ona: Site Title font not applied

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#84221]
### Quick summary

When you set a custom font for the Site Title block in the Site Editor, it's not applied.

### Steps to reproduce

1. Activate Ona theme.
2. Go to Appearance ---> Editor ---> Styles ---> Edit ---> Blocks ---> Site Title.
3. Set a custom font for the Site Title block.
4. Save changes.
5. Visit the site.

### What you expected to happen

The site title should be shown with the custom font applied.

### What actually happened

The custom font is not used for the Site Title.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Possible workaround would be using custom CSS code, but I didn't test it.

Reported here: 7310552-zd-a8c

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
The font is applied correctly to the Site Title block

![CleanShot 2023-11-18 at 14 29 22@2x](https://github.com/Automattic/wp-calypso/assets/14153300/a23dbf9c-cfc5-4b61-a0c8-40aa1d27b7d1)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@ariel-maidana This is a Community Theme, not built by Automattic, so if you can reproduce it and wants to report it somewhere, the best place is https://wordpress.org/support/theme/ona/
