### ISSUE TITLE
Welcome email message does not support HTML text

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#84232]
### Quick summary

Welcome email message under "[Settings > Newsletter](https://wordpress.com/settings/newsletter/)" does not support HTML text. Instead, it displays the HTML text in plain text.

Adding HTML text used to be possible, and older GH report like https://github.com/Automattic/wp-calypso/issues/79844 has screenshots where

### Steps to reproduce

As an admin:

1. Visit "Settings > Newsletter"
2. insert custom HTML text under "Welcome email message"

As a new subscriber:

1. Subscribe to the site above
2. Accept confirm subscription email
3. Wait for "Welcome email message"

### What you expected to happen

The "Welcome email message" displays HTML texts like `<a href="url">link text</a>`

### What actually happened

The "Welcome email message" displays HTML in plain text.

<img width="786" alt="image" src="https://github.com/Automattic/wp-calypso/assets/34882260/c574a39d-03f4-44f5-badf-6139a1b9f7cb">

### Impact

Most (> 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple

**Comment by edwinho89** [comment]
7305063-zd-a8c

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Replicated 

📌 SCREENSHOTS
![Screenshot 2023-11-21 at 14 28 19](https://github.com/Automattic/wp-calypso/assets/2540430/5f9881c8-54a3-4207-90d1-fbfec2bdc9d4)

Set Priritybto low as this would be an advanced customization, though I agree it is very useful.
As a WordPress.com user, I miss this feature.

**Comment by simison** [comment]
@TimBroddin can Apex look into this bug? Potentially pretty simple.

**Comment by TimBroddin** [comment]
> @TimBroddin can Apex look into this bug? Potentially pretty simple.

We disallow HTML here in order to combat spammers. Should we re-enable it here, since this gets sent after confirmation? @simison

**Comment by TimBroddin** [comment]
I have this patch ready: D133470-code

**Comment by simison** [comment]
Welcome message gets sent after confirmation, so it's the same as if publisher would just write normal posts. So there's no point filtering at that point anymore.

**Comment by TimBroddin** [comment]
I'll get the patch approved & deployed. 🎉
