### ISSUE TITLE
Design-first flow has visually broken domains step

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#84235]
### Quick summary

When using design-first flow, on the domains step, the layout looks broken on table and mobile viewport, missing spacing and paddings.

### Steps to reproduce

Navigate to https://wordpress.com/setup/design-first/domains

### What you expected to happen

It should not look broken, I have checked other [flows](https://wordpress.com/setup/newsletter/domains) and they look better

### What actually happened

Looks broken:
<img width="621" alt="image" src="https://github.com/Automattic/wp-calypso/assets/2653810/ba90e170-dfd0-46de-94cf-1bbf86cc87b5">

<img width="416" alt="image" src="https://github.com/Automattic/wp-calypso/assets/2653810/a9f50664-0b45-4847-aaca-9801330a0bb5">

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Replicable on Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my mobile devices:

![IMG_8D28F96897CE-1](https://github.com/Automattic/wp-calypso/assets/9025643/df639cd0-e00c-4361-9cd0-bcc6529301a6)

📌 ACTIONS
– Triaged

**Comment by renancarvalho** [comment]
Fixed https://github.com/Automattic/wp-calypso/pull/84513
