### ISSUE TITLE
The W icon on mobile WP-Admin is unresponsive after accessing /wp-admin screens

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#84236]
### Quick summary

On the mobile browser, open WP-Admin and access any WooCommerce sub-pages like WooCommerce or Products. Once you are on the sub-page like Products → All Products, tap on the W icon in the header and it becomes unresponsive

### Steps to reproduce

1. Open the WP-Admin on the mobile browser.
2. Click on any WooCommerce related sub-pages like WooCommerce → Orders or Products → All Products on the left sidebar
3. Click on the W icon again.

### What you expected to happen

Tapping on the W icon should load the left sidebar in the WP-Admin.

### What actually happened

W icon is unresponsive.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

You can workaround by tapping the Reader icon and then tapping the W icon and the WP-Admin sidebar works normally until you access any other WooCommerce sub page.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Several folks replicated this on mobile browsers, specifically when opening wp-admin pages of any AT site with WooCommerce installed. From there, tapping the W in the top left corner was unresponsive.

https://github.com/Automattic/wp-calypso/assets/27249804/e35f7829-ce7f-476c-97f0-791f5df9360c

📌 ACTIONS
- Triaged

**Comment by liviopv** [comment]
It was also reported in https://github.com/Automattic/wp-calypso/issues/85389 and new testing made it clear that is not WooCommerce-specific - it happens on any Atomic site when accessing wp-admin screens:

Steps to reproduce:

1. Open WordPress.com on a mobile browser (I used Chrome for Android)
2. Select an Atomic site
3. Navigate to any item on the interface that would load with a wp-admin URL, like Plugins > Installed Plugins
4. The page will load but the (W) icon will become unresponsive, and it will continue to be unresponsive while visiting any wp-admin screen on

I'm bumping priority to High and updating the title for clarity

**Comment by candy02058912** [comment]
I can no longer reproduce this issue. It has been a long-standing issue since 2023, and there have been no new reports.
As part of pb5gDS-3YO-p2, we're aiming to fix/close high-priority issues in [The One Board](https://github.com/orgs/Automattic/projects/391/views/12), so I'm marking this issue as closed.




https://github.com/Automattic/wp-calypso/assets/6586048/83fdecd5-96aa-4f8c-bad7-ccf39a4cd681
