### ISSUE TITLE
Multiple Themes: Featured Image placeholder not displaying in Cover Block

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#84247]
### Quick summary

When on the Enroute theme, cover blocks with a featured image have a broken placeholder:

<img width="733" alt="Screenshot 2023-11-16 at 14 46 39" src="https://github.com/Automattic/wp-calypso/assets/275961/f1c09fc8-5df1-4853-9f0e-80c9a5201bd0">

### Steps to reproduce

1. Switch to Enroute theme
2. Add a cover block
3. Select the "featured image" option

### What you expected to happen

The cover block with featured image placeholder should look like this:
<img width="690" alt="Screenshot 2023-11-16 at 14 54 53" src="https://github.com/Automattic/wp-calypso/assets/275961/379e7393-8e7c-4a75-9f65-da19d6e7aaa3">

### What actually happened

The placeholder seems to be white
<img width="854" alt="Screenshot 2023-11-16 at 14 55 30" src="https://github.com/Automattic/wp-calypso/assets/275961/0ad9a726-901d-47e6-b6ca-034f048df929">

This also impacts the overlay for the cover block:
<img width="1783" alt="Screenshot 2023-11-16 at 14 56 34" src="https://github.com/Automattic/wp-calypso/assets/275961/6a229d8a-83d0-4c76-bba1-629bafeaa11a">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated on Enroute
- Tested on Atomic – Replicated on Enroute / Eventual
- Tested on Atomic - not replicated on TT3

📌 FINDINGS/SCREENSHOTS/VIDEO
Simple / Gutenberg 17.0.2
![CleanShot 2023-11-18 at 09 46 36@2x](https://github.com/Automattic/wp-calypso/assets/14153300/f4d8b703-8cfa-4888-8997-0e385f73404e)

Atomic / Gutenberg 17.0.2
![CleanShot 2023-11-18 at 09 48 41@2x](https://github.com/Automattic/wp-calypso/assets/14153300/34da1e8a-b093-44a0-b82b-c667732aeb21)

Atomic / Gutenberg 17.02 / Eventual / Page Template
![CleanShot 2023-11-18 at 09 51 42@2x](https://github.com/Automattic/wp-calypso/assets/14153300/858d8add-13ce-447f-954b-d59b7d388578)

Atomic / Gutenberg 17.0.2 / TT3
![CleanShot 2023-11-18 at 09 53 23@2x](https://github.com/Automattic/wp-calypso/assets/14153300/428c84e3-2234-4c66-89e1-a7abf7781161)

📌 ACTIONS
- Triaged. The platform is still usable, but it makes the block harder to use and it is affecting multiple a8c themes both on Simple and Atomic. Keeping High Priority

**Comment by liviopv** [comment]
## Themes tested so far

### Reproducible
* Enroute
* Eventual

### Not reproducible
* TT3
* Iotix
* Lativ

**Comment by liviopv** [comment]
I think the root cause might be in the Create A Block Theme plugin. Pinged here p1700302864981199-slack-C057THCBY2X to confirm.

**Comment by dsas** [comment]
Still reproducible with enroute on a simple site, it looks like @liviopv's previous ping was sidetracked somewhat into fixing a fonts issue.

**Comment by arthur791004** [comment]
Both Enroute and Eventual set the color of the `core/cover` block to the `base` color, and it's the same as the background color they use, so it looks broken. I assume Gutenberg should not apply the color to the placeholder SVG to avoid the color of text and placeholder being the same. Or maybe a theme should not make the color of the `core/cover` block be the same as the background color.

```
// Enroute
"palette": [
	{
		"color": "#ffffff",
		"name": "Base",
		"slug": "base"
	},
	{
		"color": "#020e01",
		"name": "Contrast",
		"slug": "contrast"
	},
	{
		"color": "#0f6466",
		"name": "Primary",
		"slug": "primary"
	},
	{
		"color": "#fafbf3",
		"name": "Secondary",
		"slug": "secondary"
	},
	{
		"color": "#999999",
		"name": "Tertiary",
		"slug": "tertiary"
	}
],
...
"blocks": {
  "core/cover": {
	  "color": {
		  "text": "var(--wp--preset--color--base)"
	  },
  },
},
"color": {
	"background": "var(--wp--preset--color--base)",
	"text": "var(--wp--preset--color--contrast)"
},

// Eventual
"palette": [
	{
		"color": "#ffeecb",
		"name": "Base",
		"slug": "base"
	},
	{
		"color": "#3858e9",
		"name": "Contrast",
		"slug": "contrast"
	},
	{
		"color": "#33f078",
		"name": "Secondary",
		"slug": "secondary"
	}
],
...
"blocks": {
  "core/cover": {
  	  "color": {
		  "text": "var(--wp--preset--color--base)"
  	  }
  },
},
"color": {
	"background": "var(--wp--preset--color--base)",
	"text": "var(--wp--preset--color--contrast)"
},
```

**Comment by alshakero** [comment]
Sent fixes for Enroute and Eventual

D157598-code
https://github.com/Automattic/themes/pull/7996
