### ISSUE TITLE
Create a blog: Creates sites "automatically"

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#84244]
### Quick summary

With a new user without any site, navigate to `https://wordpress.com/create-blog/` then find the “Pick a design first” button.
When clicking on that, you get redirected to the design-first flow, where you can choose a design. 
At that moment, a simple site is created, even if the user decides not to proceed.
The issue is if you click back on the browser back button and then click on Pick a design first button again, another simple site will be created. 

### Steps to reproduce

With a new user ( without any site ) navigate to https://wordpress.com/create-blog/
Click on Pick a design first button
Land on design-first flow
Navigate back using the back browser button
Click on the same button again
Repeat.

Navigate to your dashboard. `www.wordpress.com` and you will notice that many sites have been created even without finalizing the flow.

The same happens when you use the “start writing” button.

### What you expected to happen

It should not create the site until I complete the flow?

### What actually happened

It is creating sites even if the user decides to navigate back.

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested: Could not replicate

📌 FINDINGS

When I click the back button, no new website was created.
When I returned from the dashboard to the https://wordpress.com/create-blog/ flow, I was asked if I wanted to work on an existing website or create a new one.

This can indeed be confusing to me users, but I didn't end up with multiple websites.

📌 ACTIONS
– Requested author feedback


📌 Message to Author

@renancarvalho Would it be too much to ask if you could try and replicate this again while recording your screen?
Thank you!
