### ISSUE TITLE
Refreshed Fullpost: End of post weirdness

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8425]
On this post ... https://wordpress.com/read/feeds/2928910/posts/1174664134 ... the last image somehow ends up below the footer action links.

![screen shot 2016-10-03 at 4 23 18 pm](https://cloud.githubusercontent.com/assets/24388/19057581/b7a1b8a6-8985-11e6-8690-a7b3914a4e28.png)

Anything we can do to prevent this?

**Comment by blowery** [comment]
likely need to clear a float.
