### ISSUE TITLE
Refreshed Fullpost: Blank Post

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8426]
This post ... https://wordpress.com/read/feeds/19091453/posts/1175465271 ... seems to be blank except for a circle.

![screen shot 2016-10-03 at 4 14 13 pm](https://cloud.githubusercontent.com/assets/24388/19057661/5f76538e-8986-11e6-984f-948229eee740.png)

**Comment by ivantedja** [comment]
seems to be happened when the post contains "video"

**Comment by fraying** [comment]
@blowery Could you look into this when you get a sec? Unsure if it's limited to 538 or not.

**Comment by blowery** [comment]
Looks like it's a problem with their RSS feed. Reported to the appropriate folks, who are looking into it.
