### ISSUE TITLE
Purchases: Add loading page skeleton for Edit Payment Method page

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#843]
Similar to #275.

As part of this task we should also add redirect for this page when there is no purchase selected.

Edit Payment Method:
![screen shot 2015-10-21 at 1 44 45 pm](https://cloud.githubusercontent.com/assets/12596797/10645213/95d0e6c2-77fa-11e5-925f-b40ff0fe08f2.png)

**Comment by fabianapsimoes** [comment]
I'll close this for now, since we're not actively working on this. Payment Method Management will liekly be a project for Gold in the future.
