### ISSUE TITLE
Manages Patterns from Page Editor On Classic Theme Shows Refused to Connect Error

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#84309]
### Quick summary

On simple sites, using a classic theme when you try to open "Manage Patterns" from the page editor, you see a "refused to connect" error message.

### Steps to reproduce

1. On a simple site, activate a classic theme such as "Apostrophe 2"
2. Open a page for editing.
3. Click three dots (upper-right) > Manage Patterns.

<img width="380" alt="Markup 2023-11-18 at 09 29 41" src="https://github.com/Automattic/wp-calypso/assets/93800099/a52833c8-a51c-4047-8c2b-9fe8f9578146">

4. See the error message "Refused to connect", screenshot below:

<img width="1442" alt="Markup 2023-11-18 at 09 30 05" src="https://github.com/Automattic/wp-calypso/assets/93800099/ebaa3370-26ca-4eed-b79e-a5295a0a7789">

### What you expected to happen

To be taken to /wp-admin/edit.php?post_type=wp_block

### What actually happened

Error message shows instead.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Could not replicate on Atomic
- The expected page is accessible from `/wp-admin/edit.php?post_type=wp_block`

7326887-zd-a8c

**Comment by upwardmomentum84** [comment]
Looks like this may be the same issue as https://github.com/Automattic/wp-calypso/issues/83472 but I'm not sure.

**Comment by caitlindawn** [comment]
Same issue in 7338010-zen

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on simple site – Could Not Replicate 

## 📌 ACTIONS ##
##Message to author##
Thanks so much for the report. I couldn't replicate this on a separate simple site. Were you able to see this beyond the user's site? Feel free to reopen if you can still replicate.
