### ISSUE TITLE
Jetpack "Share this Post" option cannot be disabled, and cannot type a message

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/wp-calypso#84314]
### Quick summary

This issue occurs when publishing or scheduling a post.

The Share this post option cannot be disabled, and you cannot type a message - https://share.zight.com/X6unGNyX.

### Steps to reproduce

1. Connect a social media account to blog.
2. Create a post and click on publish
3. On the Pre-publish preferences, go to the "Share this post" section
4. Try disabling/enabling the option
5. Try adding a message

### What you expected to happen

1. The option can be enabled/disabled
2. The message area should accept input

### What actually happened

1. The option cannot be enabled/disabled → shows the same status
2. The message area is not accepting any input, and only accepts the first letter

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

7328996-zen

**Comment by ricklabsdotn8** [comment]
7337909-zen

**Comment by jp-imagines** [comment]
Also reported in 7333088-zd-a8c (simple site). User noted they're also not able to cut/copy and paste into or out of the "message" field either. They've shared some browser console output as well in their ticket.

@villanovachile was able to replicate on a self-hosted site as well: 


https://github.com/Automattic/wp-calypso/assets/5630717/e9505c2e-31cc-4e5b-a85b-ef1b5cd54f8f

**Comment by afzalpansuvi** [comment]
Adding another ticket: HC 7350841.

**Comment by afzalpansuvi** [comment]
Adding another ticket: HC 7337263.

**Comment by manzoorwanijk** [comment]
@afzalpansuvi The issue has already been fixed. Users should now be able to use it as before.
