### ISSUE TITLE
Onboarding > Pick a Design: "Design your own" button looks like a search bar

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#84321]
### Quick summary

The current style of the "Design your own" button looks like a search bar, which is an element that seems to be missing in this page. I was triaging https://github.com/Automattic/wp-calypso/issues/84172 and, at glance, it looked so much like a search bar that I started typing "Tronar" after clicking until I realized I was on the Assembler.

![CleanShot 2023-11-18 at 15 03 14@2x](https://github.com/Automattic/wp-calypso/assets/14153300/17dd6198-e377-4d14-a319-3b877b5f603d)

### Steps to reproduce

1. https://wordpress.com/start
2. Proceed with the onboarding flow until seeing the option to "Choose a design"
3. You will eventually land in the Design Picker https://wordpress.com/setup/site-setup/designSetup?
4. Look at the top right of the page and try to distinguish visually what the "Design your own" button will do without paying attention to the text

### What you expected to happen

The button should look more like a button, with a better indication that it's clickable and it will redirect to somewhere else. With the current design, with a fine border with light gray text inside, it looks just like a search bar, which is an element I would expect in the Design Picker

### What actually happened

It took me to the Assembler, which is expected, but at a glance, I was expecting that it would turn into a search bar so I could search for a specific theme.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Chrome 119, Mac Sonoma

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue. The button does look like a prepopulated search field, not like the usual button we use in our design:
![Markup 2023-12-18 at 21 40 33](https://github.com/Automattic/wp-calypso/assets/9025643/507191d0-d549-40d6-ae60-0d681a1e644e)

📌 ACTIONS
– Triaged

**Comment by taipeicoder** [comment]
Closing this issue as we have removed the Design Your Own button for all users.
