### ISSUE TITLE
Theme showcase: WooCommerce theme variations are displaying an upgrade notice to the Premium plan

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#84323]
### Quick summary

When selecting a style variation in the Theme showcase for a WooCommerce theme, the upgrade notice in the tooltip mentions that the user needs a Premium plan. However, WooCommerce themes require a Business plan.

### Steps to reproduce

1. Go to the Theme Showcase (Appearance > Themes)
2. Search for the Zaino theme
3. Click on the style variation circle
4. Notice that the black label on the card changed to "upgrade"
5. Move the mouse over it and a tooltip will be display

### What you expected to happen

The tooltip should mention a Business plan

### What actually happened

The tooltip informs the user that they need a Premium plan

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by rcrdortiz** [comment]
These changes are now live.
