### ISSUE TITLE
menu module no response

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#84320]
### Quick summary

By using Toujours template, once click any link at menu pattern, it shows no response, but the rest links in the website work usual

### Steps to reproduce

1. visit www.ttcath.org
2. click any links on the menu 
3. on mobile device, it runs very slow, even using VPN in mainland China.

### What you expected to happen

every link and funcitons on the site must work proper.

### What actually happened

any links in menu based on  Toujours template not work at mobile device, even using VPN in mainland China.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple https://toujoursdemo.wordpress.com/ – Could Not Replicate, the menu links open as expected
- Tested on Atomic – Could Not Replicate, the menu links open as expected
- Tested on https://ttcath.org/ – Could Not Replicate, the menu links open as expected (see video below)

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/14153300/eedeb0b2-ef95-480f-ab93-638ca3228965


📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@ttcath I could not replicate, so this is not a problem with the theme or the menu feature. It's likely happening only on your site, and your internet network, so I'm reaching out the email on file for the site to continue the conversation through the regular support channels.
