### ISSUE TITLE
Home: Allow Disabling Home Reader Experiment 

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#84324]
### What

We've had some Support requests about users who are pretty unhappy with this change. I think this is possibly a case where a user's flow has been disrupted. It would be helpful if there was an option to easily disable this.

<img width="812" alt="Screenshot 2023-11-18 at 17 34 35" src="https://github.com/Automattic/wp-calypso/assets/43215253/947265e9-ff72-4b0e-bcf2-f0fa75e2c952">

From 7329282-zen:

> You literally just turned my business into a trashy social media site.

@lupus2k @DustyReagan is there anything I can say to this customer about how to disable it? Thanks! (by the way, I really like the new feature!)

**Comment by DustyReagan** [comment]
Thanks, @Aurorum! I think we can make exceptions. Let us look into this.

**Comment by Aurorum** [comment]
Much appreciated @DustyReagan! I'll keep a note here of any interactions where this pops up in case it helps inform your decisions about the experiment.

7330032-zen - another user who is keen to disable it

**Comment by DustyReagan** [comment]
Yes, please do! Thank you, @Aurorum! For the time being, we'll hard-code individual exceptions. The first one you mentioned is done.

**Comment by Aurorum** [comment]
Thanks @DustyReagan! Will let them know.

**Comment by mahfuzurwp** [comment]
Hi there,

7331311-zen

The user wants to disable it too.

**Comment by Aurorum** [comment]
7320328-zen - still seeking confirmation as to whether they'd actually like to disable it, but some useful feedback I thought:

> It seems that the Home page has changed. A friend of mine has reported the same matter to me on his computer. It seems the writing prompt no longer appears there. I wonder why this is a new policy. I have found another way to access it, after a long winded investigation, but it doesn't seem quite right to me. Should be on The Home page displayed as it used to be. I cleared my computer but the problem is still there and seems universal.

They're not keen that the Daily Blogging Prompts aren't displayed on the new layout.

**Comment by Aurorum** [comment]
7326352-zen - please also disable for this user! They assumed that the blogs are adverts and paying to be promoted - not sure if that might be a concern. 

> But now My Home shows these blogs that I don't want to see. 

> For the unwanted blogs, where did they come from, we used to never have them. I followed the instruction on clicking the three dots on the top right corner of each blog, and there are TONS of them, I don't want any of the blogs, do I have to click each to "block site". We have paid for "ads free", unless in changing the password for the domain, the ads free payment went with the old email address and not this one, did changing the password "changed" the ownership? Please look into this. We just paid the renewal of "ads free " service.

**Comment by Aurorum** [comment]
Sorry, a lot of them coming in right now 🙃  7331083-zen:

> When I log in to my site 'My Home' now displays an unwanted feed of other people's posts. How do I delete that? I don't want to see those posts.

**Comment by rw-ye** [comment]
Another report here: 7330311-zd-a8c

> That section did not exist a few days ago. Please have an option for user to disable that section or have it located somewhere else. It is not helpful and does not provide anything relevant to my website home tab.

**Comment by OmarFPG** [comment]
Got one! Can we opt-out this user too, please? 7336765-zen

**Comment by AlexanderSky** [comment]
Another request: 7339189-zen

**Comment by maciejpilarski** [comment]
7339593-zen

> When I logged on to my account, on my home page there was all this stuff from other people's sites. This is not good. Sorry, but when I log in to MY account, I ONLY want to see MY stuff. How do I remove from my home page all of this stuff from other people? 

>please, Wordpress, I dO NOT WANT To engage with others and GROW MY Site.  If people want to visit my site, they will; if not, they won't.  And both are fine with me.  So, the question: how do I remove this from my Home log in?

**Comment by Aurorum** [comment]
7360224-zen 

> Now: obfuscating 'insights' panel hides the details above (shoves them to the bottom of the page) and pollutes rhe formerly-useful dashboard with multiple posts that have nothing to do with my site.

**Comment by artpi** [comment]
7370653-zd-a8c

User wants blogging prompts back

> I used to read Daily Prompts where there was an option to post beneath the question. This is no longer available. I don't understand. Can you help?

**Comment by ariel-maidana** [comment]
User doesn't want the reader section in the dashboard home: 7375303-zd-a8c
User's feedback: 

> It is VERY annoying and inefficient.
> I would suggest that people on the Business Plan have the option of disabling this annoying "feature." We're using WordPress to WORK not comment on what some retired dude is doing on the beach.

**Comment by davemart-in** [comment]
This A/B test was turned off completely for everyone. Closing this out.
