### ISSUE TITLE
CPT: can't list pages for a site that uses Portfolio CPT and the Portfolio theme

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8433]
First reported by @eduardozulian (ref: p2EDhh-dd-p2)

#### Steps to reproduce
1. Starting at URL for a WordPress.com site: https://wordpress.com/pages/example.wordpress.com
2. Activate <a href="https://wordpress.com/theme/portfolio">Portfolio</a> theme on the site
3. Note that instead of displaying pages, the pages view shows posts (and in one case spammy feedbacks — see 2851041-t for more on that.)

#### What I expected
To see Pages listed here.

#### What happened instead
Viewing posts and revisions instead.

If you click one of the posts, you get a message like this:

> This post type is not supported. To use this post type, please check that your theme and site support it.

View page list in wp-admin works as expected.

@rachelmcr adds

This looks like a theme-specific issue, with the Portfolio theme. I’m not sure if it’s an issue with the theme itself, or if it’s a conflict with the theme name (Portfolio) and how Calypso handles supported post types (including custom post types like portfolio projects).

I can reproduce the issue by switching to the Portfolio theme on my test site. Interestingly, but perhaps not surprisingly, I get the same results (showing all my posts instead of the expected content) in the Portfolio section at https://wordpress.com/types/jetpack-portfolio and the Testimonials section at https://wordpress.com/types/jetpack-testimonial.

#user-report

**Comment by timmyc** [comment]
Thanks for logging the issue - I can reproduce the issue only with the Portfolio theme.  It appears the API is returning the data incorrectly.

**Comment by timmyc** [comment]
Fixed with an api patch.
