### ISSUE TITLE
Automate Jetpack SSO step

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#84350]
### What

When accessing WP admin for a new Atomic site, you have to authorize your WordPress.com user account. Can this be automated?

More specifically, after moving through the Sensei onboarding flow, the user is presented with a Jetpack SSO screen after clicking on the _Finish Sensei setup_ button on the _My Home_ page (or when clicking on the Dashboard). We should investigate to see if we can automatically log them in.

### Why

The Jetpack SSO screen is extra friction, and the user likely won't understand why they were taken there, so we should try to avoid surfacing this step to them if possible.

### Context
From p6rkRX-6Us-p2:

> Jetpack SSO screen looks pretty bad with a lot going on and essentially blocked with email verification. Can this be automated? (06:11)

And another reference from p6rkRX-71z-p2#comment-6833:

> Clicking Dashboard requires him to log into the WoA site (can we do that automatically for the user? I know I said that in other walkthroughs before)

From pdxWSz-1eq-p2#comment-307:

> For Jetpack SSO, you can trigger it like this.

> - From an unverified free account, visit /plugins, search for Hello Dolly (or any plugin), click card, upgrade to Creator to activate, after activation click on Appearance > Installed Plugins.
> - From an unverified free account, visit /themes, search for Astra (or any community theme), click card, upgrade to Creator to activate, after activation click on “Astra” in the sidebar.

> You can also trigger a very outdated email verification screen by doing this:

> - Signup in the new user flow, choose the Entrepreneur plan, checkout.
> - If you click a link in the toolbar like Reader from that screen you’ll see the Jetpack SSO screen.

> These screens are confusing, outdated, and contribute to a bad UX.

> If both these screens were replaced with an updated on-brand “Verify your email screen” that would be a major improvement. The Woo flow on Dotcom has a more on-brand “verify your email screen” blocking interaction that would lead to these screens

> ... is investigating if we need verification at all for Atomic in p1HpG7-qll-p2.

**Comment by donnapep** [comment]
Given the last comment here (pdxWSz-1eq-p2#comment-307), I'm deprioritizing this issue as it will likely require some design. The best case scenario though would be that the email verification step is deemed as not being needed at all.

**Comment by obenland** [comment]
Being worked on in p1HpG7-qll-p2

**Comment by donnapep** [comment]
Closing as this was fixed in D133828-code.
