### ISSUE TITLE
Google Apps: update error shown to users in India

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/wp-calypso#8435]
Currently, when a user geo-located in India (or whose domain has a ccTLD of .in) tries to purchase G Suite (formerly Google Apps, they get an error in their shopping cart like so:

<code>Google Apps is not available in your current region.</code>

Here's a screenshot of what it looks like:

![screen_shot_2016-10-03_at_9_14_13_pm](https://cloud.githubusercontent.com/assets/6569475/19060662/9356f234-89af-11e6-8311-7872d1d29344.jpg)

This is expected behavior because we do not currently offer G Suite to India-based users or to domains with .in TLDs. However, we've had users submit tickets/open a chat because the error doesn't provide any context or further information, so they think it's a "real" error message. 

Could we please add more language that lets users know that they can purchase G Suite directly from Google in these instances? Something like:

<code>G Suite is not available in your current region. You may, however, be able to purchase it directly from Google [here](https://gsuite.google.com/).</code>

(Note: Link goes to https://gsuite.google.com/)

/cc @klimeryk 

Thank you!
# user-report #manual-testing

**Comment by klimeryk** [comment]
@matthusby, as part of your task of bringing G Suite/Gapps to mapped domains, do you plan to refactor at which point of the checkout these errors will show? (like way before checkout, when they are inputting the domain contact info) Just making sure that if I fixed this issue I wouldn't be conflicting with your changes.

**Comment by Lochlaer** [comment]
@matthusby @klimeryk It would be awesome if the error were to show up much earlier in the checkout than it currently does. I know that when I was testing the above error, I was a little confused as to why it would allow me to go all the way through to payment and checkout and *then* tell me I can't actually buy it.

**Comment by klimeryk** [comment]
Yup, totally what I was going for :) Just wondering if @matthusby did something like that already (or will) as part of his task or is this something that can be done separately.

**Comment by matthusby** [comment]
@klimeryk I didn't do any work on that part of this.

**Comment by Lochlaer** [comment]
#### UPDATE ####

As of 2018, we now allow G Suite purchases from users in India, so this is no longer relevant/needed. Closing as resolved.
