### ISSUE TITLE
Verbum: change Reply to Comment

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#84354]
To improve consistency, we should change `Reply` in favor of `Comments`. In the site settings we call it Comments, and we use this taxonomy in [Support docs](https://wordpress.com/support/comments/).

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/d7b6c169-6878-4291-8a4b-cef559ece6a0)

**Comment by lupus2k** [comment]
Hey @crisbusquets, are we good to continue with this? @Automattic/vertex, any concern? or you prefer to work on this after migrating Verbum to Jetpack?

**Comment by crisbusquets** [comment]
> Hey @crisbusquets, are we good to continue with this?

Yes, please :)
We should also use sentence case (for example, `Write a comment` instead of `Write a Comment`).

And we should keep `Reply` when its a reply, like in the case below: I'm replying to Chris O'Sullivan, and it says `Write a comment`. It should say `Write a reply` or similar.


<img width="679" alt="Screenshot 2024-01-09 at 11 26 43" src="https://github.com/Automattic/wp-calypso/assets/25607244/78d01dfb-5eb9-41ce-a046-c8c3748f539b">

**Comment by alshakero** [comment]
@lupus2k this should be a quick issue, let's not block it with that behemoth :D

**Comment by escapemanuele** [comment]
Thanks @crisbusquets, I feel this is a good change :D
