### ISSUE TITLE
Assembler - Pages - Show added pages in navigation preview

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#84360]
## What

When users add pages in the assembler, the header preview is not updated to show them.

|Added pages|Preview|
|-|-|
|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/dd8c8864-f7a6-46aa-bd47-ed1946207e85)|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/b7115d0b-1e20-4381-8f9a-940533b5aecb)|

## Why

The user expectation after adding pages is to see them previewed in the assembler as they will be on their site after completing the flow.

## How

When rendering the header pattern in the preview, modify the HTML of the navigation links in the header to match the pages selected. See [pattern-large-preview.tsx#L263](https://github.com/Automattic/wp-calypso/blob/c2555cb084c1a7a5546e4d6cfd62e28c77680fbe/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-large-preview.tsx#L263)

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/3e5524ce-2ff6-4c07-b975-2cf9a5a841c4)

**Comment by fushar** [comment]
Fixed via:

- https://github.com/Automattic/wp-calypso/pull/84437
- D129610-code
