### ISSUE TITLE
Editor: action bar in editor cuts off the layout for rest of calypso on iOS Safari

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#8437]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post in iOS Safari
2. Write some text in the editor - note the action bar at the top is slightly cut off
3. Now visit a standard Calypso page - note the top part is very cut off
#### Browser / OS version

Safari on iOS 10.0.2
#### Screenshot / Video

Video: https://cloudup.com/cms7IResjH4

Screenshots:

![cut off - 2](https://cloud.githubusercontent.com/assets/128826/19064525/350316f2-8a51-11e6-9f9a-6294d1cf2f8b.jpg)

![cut off - 1](https://cloud.githubusercontent.com/assets/128826/19064531/3b913d14-8a51-11e6-9e61-3e4257e6e6bc.jpg)
#### Context / Source

Found testing #5987 which makes this appear much worse

**Comment by rachelmcr** [comment]
I retested this issue, and with the newer editor layout I'm no longer seeing the action bar cut off at the top in the editor or after navigating away from the editor:

![2017-08-07 16 47 28](https://user-images.githubusercontent.com/8658164/29034536-70843a4a-7b90-11e7-9fd7-0dfb3922f7c4.png)
![2017-08-07 16 48 39](https://user-images.githubusercontent.com/8658164/29034542-79e88668-7b90-11e7-9b17-88f07a1ae187.png)

Tested in Safari on iOS 10.3.3.
