### ISSUE TITLE
Feature Request: Allow moving the minimized Help Center

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#84384]
### What

The Help Center can be moved when open, but cannot be moved when minimized.  It'd be great if we could move the minimized Help Center as well.

https://github.com/Automattic/wp-calypso/assets/27249804/2168b1d8-5d9f-4963-9e46-8cf1f076ec81

### Why

The minimized help center may cover up a feature a customer needs, or may feel inconveniently placed for a particular user's preferences.

**Comment by cuemarie** [comment]
Found while testing: pdtkmj-20q-p2

**Comment by Aurorum** [comment]
Looked into this and seems like it was an intentional change made in #68772 

cc @escapemanuele @heavyweight for if that decision can be reviewed and any rationale behind it

**Comment by andregardi** [comment]
I am closing it since it is intentional:

> The Help Center shouldn't be draggable when minimized. It should stick to the bottom-right side of the page. Maybe 100px from right.

 [Task: Help Center - should always be on the bottom right when minimized](https://github.com/Automattic/wp-calypso/issues/68589)

**Comment by escapemanuele** [comment]
Thanks @andregardi
