### ISSUE TITLE
Framework: iOS Safari mobile widths lose correct width

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#8438]
When using Calypso in Safari on iOS the page widths start getting messed up and you end up not seeing the full width.
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post on mobile Safari iOS
2. Enter some text for a post
3. Navigate through Calypso menus from here
#### What I expected

Correct page width for device
#### What happened instead

Page width starts not being set correctly meaning you can't see the whole page

**Note**: zooming out using two fingers zooms out to correct width
#### Browser / OS version

iOS 10.0.2 on iPhone 7 +
#### Screenshot / Video

This video from another bug (#8437)  shows the width issue in play: https://cloudup.com/cms7IResjH4

These screenshots show how menus are displayed:

![screen width - 1](https://cloud.githubusercontent.com/assets/128826/19064704/4c3195be-8a52-11e6-8641-7b2c5fc5c063.jpg)

![screen width - 2](https://cloud.githubusercontent.com/assets/128826/19064711/59bb0378-8a52-11e6-90a4-5335cf2ae895.jpg)
#### Context / Source

Found during testing of #5987

**Comment by rachelmcr** [comment]
I can't reproduce this issue anymore, perhaps due to the updated editor layout. I followed the steps as described and shown in the video, and the page width was set correctly throughout.

Tested in Safari on iPhone 6, iOS 10.3.3.
