### ISSUE TITLE
Feature: Migrate existing site setup logic to the Launchpad

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#84409]
### What

Many users are still being shown the outdated Site Setup UI in My Home, shown below. We need to migrate this logic across to a Launchpad that we show to users rather than this older UI, especially for new sites. We may want to follow up and migrate older sites across as well, but that may require some more subtle checks for tasks that were completed before the underlying Launchpad task completion logic existed.

<img width="1088" alt="site_setup_in_my_home" src="https://github.com/Automattic/wp-calypso/assets/3376401/27bd849e-40f3-4b99-ad3f-f8e7bbdc732c">

### Why

Our development moving forward is going to involve iterations and improvements to the Launchpad and tasks within that UI component, so we should show this UI in more cases, even if we're sticking to a relatively generic set of tasks to start with.

**Comment by valterlorran** [comment]
I wrote the remaining steps we need to do so we can launch the Site Setup Launchpad to new sites: paYKcK-3Hy-p2#comment-2696

**Comment by valterlorran** [comment]
Update: We deployed it for new sites, and now we are working on how to migrate sites created before the deployment. 

More context: 
* p7DVsv-jQE-p2
* paYKcK-3Hy-p2#comment-2878

**Comment by valterlorran** [comment]
We decided to move along with the runtime migration. More information can be found here: pMz3w-jl4-p2#comment-116617

**Comment by valterlorran** [comment]
Closing this as we are already migrating all three flows we identified: General site setup, blogging, and hosting.
paYKcK-47M-p2
