### ISSUE TITLE
Live Preview: Refine the loading state UI

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#84401]
# Description

Refine the UI of the Live Preview's loading state. 

<img width="664" alt="Screenshot 2023-11-22 at 15 09 08" src="https://github.com/Automattic/wp-calypso/assets/5287479/d56466cf-a63d-4a0a-9e03-992d1b4c79b0">

Slack convo: p1700633552886889-slack-CRWCHQGUB
Project Thread: pbxlJb-4QS-p2

## 1. On the Theme Detail page

- Remove the current loading state.
- Make the button in a loading state and change the label to "Preparing theme preview". 

Example:

https://github.com/Automattic/wp-calypso/assets/5287479/e696b089-c73d-4cc3-9c49-ec484f0001d8

## 2. On the Theme Showcase page

- Remove the current loading state.
- We might want to show the "subtle spinner". See p1700636626214709/1700633552.886889-slack-CRWCHQGUB.

# Dev Tasks
- https://github.com/Automattic/wp-calypso/pull/84698

# Related

The current loading screen comes from https://github.com/Automattic/wp-calypso/blob/58daab75135d6e7068051d52efb57c343749036e/client/my-sites/themes/thanks-modal.jsx#L244-L252. Currently, this loading screen is shown only if the user is NOT redirected to either "the Marketplace thank you page" or "the Marketplace theme installation page" (e.g., Partner themes). See https://github.com/Automattic/wp-calypso/blob/58daab75135d6e7068051d52efb57c343749036e/client/state/themes/actions/activate.js#L88-L108.

https://github.com/Automattic/wp-calypso/assets/5287479/4a85a0aa-6f63-48e9-b7c8-7794d7c37d5c

**Comment by autumnfjeld** [comment]
Ohhhh, so that loading screen is shown in other places? Yikes.   Then fixing it is is an even more important improvement.  Even just removing the modalbox and having a greyed out overlay as the "loading" state seems better.    But if we can replace the modal-box with a spinner, that would be ideal. :)

**Comment by taipeicoder** [comment]
@okmttdhr is this task completed?

**Comment by fushar** [comment]
Yes, sorry, closing this!
