### ISSUE TITLE
User was able to delete a site while the professional email sub is active on the site

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#84405]
### Quick summary

To delete a site, all active subscriptions must first be deleted. It seems it's possible to delete a site while the professional email subscription is still active on the site.

SA of the affected user: https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=242811732

### Steps to reproduce

1. Purchase a domain on a site
2. Purchase the professional email subscription
3. Cancel the domain
4. Delete the site
5. Notice the site is deleted while the professional email remains active on the site.

### What you expected to happen

All active subscriptions should be canceled before a site can be deleted.

### What actually happened

The site was deleted while the professional email subscription is active on the site.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I followed the steps and could not replicate the issue anymore. After canceling all the subscriptions (domain, plan), when I try to delete the site, I am being notified about remaining paid subscriptions, which in that case would be the Professional Email:

![Markup 2023-11-27 at 16 40 44](https://github.com/Automattic/wp-calypso/assets/9025643/2439dcb2-fa73-48f4-b767-6e25d4a26f5a)


📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by poeticabdul** [comment]
Another SA where this has happened https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=climateactionschools
