### ISSUE TITLE
Improving likes: add Tracks to current implementation

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84417]
Add Tracks logging for these events: loads, likes, expands (show more gravatars)

**Comment by ivan-ottinger** [comment]
Turns out we have been already tracking `wpcom_post_like` and `wpcom_post_like_receive` events. More info: 3299a-pb.

There doesn't seem to be any event related to the _load_ nor _expand_ yet. → Something I will look further into it.

**Comment by TimBroddin** [comment]
Nice find! 

I don't think we actually need the load event. There aren't going to be any more loads with the new layout.

Expand might be nice, but it's okay to drop this if the effort required is too big.

**Comment by ivan-ottinger** [comment]
> I don't think we actually need the load event. There aren't going to be any more loads with the new layout.

I agree. And if there are any issues with the load, we would learn that through dropped likes.

> Expand might be nice, but it's okay to drop this if the effort required is too big.

I will look at this.

**Comment by ivan-ottinger** [comment]
What do you think about using `wpcom_post_like_expand` for the expand event?

**Comment by ivan-ottinger** [comment]
New event registered and validated: https://github.com/Automattic/tracks-events-registration/pull/1968.

**Comment by ivan-ottinger** [comment]
Patch for Simple sites is ready for review: D129834-code.

**Comment by TimBroddin** [comment]
Waiting for input from team Jetpack on how to do it there

**Comment by ivan-ottinger** [comment]
At the end we have decided not to track the `wpcom_post_like_expand` event. More context: p1700815594572769/1700750568.107759-slack-C02TCEHP3HA.

Related patch D129895-code.
