### ISSUE TITLE
Improving likes: implement new dialog design

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84424]
Implement the new design for the popover dialog, which gets shown when there are too many avatars.

**Comment by TimBroddin** [comment]
Only show new design when the filter from #84419 returns true.

**Comment by ivan-ottinger** [comment]
Just noting that once D129905-code is in, we will still need a separate PR for WoA and JP sites.

**Comment by ivan-ottinger** [comment]
Just noting that https://github.com/Automattic/jetpack/pull/34308 that updates the design for JP and WoA sites is ready for review.
