### ISSUE TITLE
Design Picker: TT4 mShots are missing the animated gif/video

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#84426]
## Description

See p1700597658776619-slack-C048CUFRGFQ. The animated gif / video of the TT4 theme is not properly shown in the design picker and the theme showcase (style variations).

![Image](https://github.com/Automattic/wp-calypso/assets/797888/52f9a3a3-0c97-446f-b82e-6e32220e9fad)

**Comment by arthur791004** [comment]
The video is from the `core/video` block, and the asset is from WP.org. The video file is supported by the Premium plan and above but the demo site only has a free plan, so I resolved this issue by adding the generated video poster to the homepage of the demo site.

However, I found TT4 has a customized homepage for promotion (?) that is different from the actual homepage after switching to that theme. Should we fix this issue?

| Actual Homepage | Customized Homepage |
| - | - |
| ![image](https://github.com/Automattic/wp-calypso/assets/13596067/d698565c-c448-4f11-99e4-9158a72ec1fc) | ![image](https://github.com/Automattic/wp-calypso/assets/13596067/c1babe9a-8743-4684-84f7-d8c3063a105f) |

**Comment by taipeicoder** [comment]
@arthur791004 I think we can close this one, since the thumbnail now correspond with the theme preview and demo site. WDYT? cc: @autumnfjeld 
 
![Image](https://github.com/Automattic/wp-calypso/assets/797888/275eefff-1b7c-4a83-9721-21554ab752d9)

![Image](https://github.com/Automattic/wp-calypso/assets/797888/a3c3d6da-5b85-4816-8c8e-d5af6805e548)

**Comment by arthur791004** [comment]
Sure!
