### ISSUE TITLE
Improving likes: implement new iframe design

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84420]
When the query parameter from #84419 is set:

- Render only 5 avatars
- Render them as circles
- Sort those 5 by timestamp descending

Design: fJZ60vrt8ZNJwL2TPPM106-fi-153%3A1950

**Comment by Aurorum** [comment]
Hey @TimBroddin - we've had a couple of users in support (eg. 7465477-zen) ask for the rationale behind displaying only five avatars. 

I've generally been providing a generic answer, but this has popped up a few times, so it'd be great if there's any information that you have which we could pass on.
