### ISSUE TITLE
Advanced SEO: Front Page Meta Description doesn't show in Previews

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#8443]
When entered under My Sites > Settings >SEO, the Front Page Meta Description text shows up on the frontend of the site (as a` meta` tag, in the page source), but it does not show up in the Previews of the site that you can get to from the Settings > SEO screen.

#### Steps to reproduce
1. Load the My Sites > Settings > SEO page of any Business plan site - https://wordpress.com/settings/seo/
2. Scroll down to 'Website Meta'
3. Enter some text in the 'Front Page Meta Description'
4. Click 'Save Settings' in the 'Website Meta' box
5. Click the 'Show Previews' button

#### What I expected
The Front Page Meta Description text should show up in the Google / Facebook / Twitter Previews.

#### What happened instead
The Front Page Meta description I entered did not show up in any of the Previews.

#### Browser / OS version
Macnchrome  53.0.2785.116
Mac/Firefox 49.0.1

#### Screenshot / Video
http://d.pr/i/KVLR

Please let me know if you need any additional info!

**Comment by vindl** [comment]
Thanks for reporting this and for the detailed instructions @mahangu!

We resolved this issue in https://github.com/Automattic/wp-calypso/pull/8455.

**Comment by mahangu** [comment]
Awesome, thank you! 👍
