### ISSUE TITLE
Improving likes: investigate behavior on P2

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84456]
The design thread (pdDOJh-2Ht-p2) and this comment (pdDOJh-2Ht-p2#comment-2058) mentions different behavior on P2. The goal of this task is to take a look whether there's anything different on the frontend or backend and document it here.

**Comment by TimBroddin** [comment]
@poligilad-auto 👋

I took a look at the current code, and I can't really find any evidence that rendering is done differently on P2's for the widget itself.

| P2 | WPCOM |
|-|-|
|  ![Image](https://github.com/Automattic/wp-calypso/assets/528287/a85c85c8-dc71-4792-acc4-afce9c747a44) |![Image](https://github.com/Automattic/wp-calypso/assets/528287/9d350b9e-ba8e-4387-96a1-20ce6ceeced1) |

The only difference I see here is that on WPCOM a reblog button is added, and the iframe is slightly higher & thus revealing the "You like this" line. But I can't find any evidence that we order the avatars any other way on P2s.

**Comment by poligilad-auto** [comment]
@TimBroddin 

> But I can't find any evidence that we order the avatars any other way on P2s.

Gotcha. Interesting. Well, we could just leave the order of avatars as is. What do you think?
Do you have anyway of figuring out what the current order of avatars is based on?

> and the iframe is slightly higher & thus revealing the "You like this" line.

Ha. Now I understand why it's different.

**Comment by TimBroddin** [comment]
> [@TimBroddin](https://github.com/TimBroddin)
> 
> > But I can't find any evidence that we order the avatars any other way on P2s.
> 
> Gotcha. Interesting. Well, we could just leave the order of avatars as is. What do you think? Do you have anyway of figuring out what the current order of avatars is based on?
> 

Currently, there is no order at all. They're returned as the database engine seems fit, the only "ordering" that takes place is moving yourself to the front of the line.

I've added displaying them in reverse chronological order to the relevant ticket here: https://github.com/Automattic/wp-calypso/issues/84420

> > and the iframe is slightly higher & thus revealing the "You like this" line.
> 
> Ha. Now I understand why it's different.

We'll try to make it the same height.

**Comment by poligilad-auto** [comment]
So currently just random. That's bizarre :)

> I've added displaying them in reverse chronological order to the relevant ticket here: https://github.com/Automattic/wp-calypso/issues/84420

Thanks!
