### ISSUE TITLE
Assembler: Add a page copy change

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#84454]
Add a sentence to the end of this existing copy.  Per this comment from the CfT pdtkmj-20J-p2#comment-3801 that it isn't clear how to edit content.

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/77e926f5-7f78-4e4a-bb9f-aad04f092e7c)

New sentence: " Page content can be edited later, in the WordPress editor."

@Automattic/lego

**Comment by autumnfjeld** [comment]
cc: @lucasmendes-design  on this copy update.  In the spirit of better communicating that editing content cannot be done in the Assembler.

**Comment by taipeicoder** [comment]
@autumnfjeld shall we use the term Site Editor instead of WordPress Editor? We will make a reference to the Site Editor via https://github.com/Automattic/wp-calypso/issues/82782#issuecomment-1820045290 already, FWIW!

**Comment by lucasmendes-design** [comment]
> use the term Site Editor

+1. 

> on this copy update. In the spirit of better communicating that editing content cannot be done in the Assembler.

Agree.

**Comment by fushar** [comment]
Maybe @autumnfjeld means that there are at least two ways to edit the page content: in the Page Editor, and in the Site Editor? I remember long time ago that @autumnfjeld prefers the blanket term "Editor".

I'm not even sure if the choice of the wording here really could confuse people 😄

**Comment by taipeicoder** [comment]
Closed via #84628.
