### ISSUE TITLE
Improving likes: deploy

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84504]
## Simple: 

like we did for Mapkit: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sznc%2Qoybpx%2Qznc%2Qcebivqre.cuc%3Se%3Qo427396n-og

## Atomic:

Inside jetpack-mu-wpcom: fbhepr%2Skers%2Swrgcnpx%2Scebwrpgf%2Scnpxntrf%2Swrgcnpx%2Qzh%2Qjcpbz%2Sfep%2Spynff%2Qwrgcnpx%2Qzh%2Qjcpbz.cuc-og

## Jetpack:
Just make the filter return true, or remove feature flag check altogether since this will be last.

**Comment by TimBroddin** [comment]
Simple: D130003-code

**Comment by yansern** [comment]
Atomic: https://github.com/Automattic/wpcomsh/pull/1582
