### ISSUE TITLE
Can't go back from domain page for start-writing flow

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#84510]
### Quick summary

As reported in p58i-fXA-p2, we created a site and were working through  the `start-writing` flow, but when we reached the domain purchase page from the Launchpad, we couldn't navigate back to the Launchpad. This should not be a dead end for users. While this was reproduced for the `start-writing` flow, it's possible the issue exists in other flows as well.

### Steps to reproduce

1. Navigate to https://wordpress.com/setup/start-writing/
2. Choose to create a new site when that option becomes available
3. Wait for the site to be created and for the post editor to be loaded
4. Add some content and publish the post
5. After publishing the post, you should be taken to the fullscreen launchpad
6. Click on the "Choose a domain" task, which loads the domain upsell screen

### What you expected to happen

From the domains screen, I expect to be able to get back to the Launchpad easily without making a purchase or even performing a search.

### What actually happened

On the domains screen, I can't navigate back to the Launchpad. I'm stuck.

<img width="1727" alt="Screenshot 2023-11-24 at 15 41 39" src="https://github.com/Automattic/wp-calypso/assets/3376401/ce309dab-7ea8-4393-b079-4a985fc3294a">

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by sixhours** [comment]
>  While this was reproduced for the start-writing flow, it's possible the issue exists in other flows as well.

It looks like this domains screen is used for the blog/writing flow and the VideoPress flow, but I wasn't able to get to it from going through the onboarding process at `/setup/videopress`, so I don't think this is currently an issue in other flows.

**Comment by sixhours** [comment]
This was fixed by https://github.com/Automattic/wp-calypso/pull/84616
