### ISSUE TITLE
Image Editor: disable image editing of image being currently uploaded

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#8452]
After clicking "Done" on image editor, the edited image is being uploaded to our servers. However, users can still go to the currently uploaded image detail view and/or edit the image while it is being uploaded. This causes the following error:

![selection_020](https://cloud.githubusercontent.com/assets/4988512/19077591/8b120408-8a4d-11e6-9b07-6001c22641a3.jpg)

A solution to this is to disable image editing of the image which is currently being uploaded:

![selection_021](https://cloud.githubusercontent.com/assets/4988512/19077604/9d3e2440-8a4d-11e6-9fed-86c93e4e90ac.jpg)

Or disable the whole image detail view:

![selection_019](https://cloud.githubusercontent.com/assets/4988512/19077613/a36e4570-8a4d-11e6-9f8c-ce23e8540107.jpg)

/cc @gwwar @retrofox @artpi

**Comment by gwwar** [comment]
Maybe add a `disabled` attr to the "Edit Image" button while it's still being uploaded?
