### ISSUE TITLE
Theme Demo: Fix Upsell Banner Flows

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#84563]
## ⚠️ DISCLAIMER ⚠️ 

This issue is about fixing bugs, not redesigning banners or refactoring all the flows.

Let's limit the scope to:
- Choose the correct phrasings.
- Fix the `with-theme` flows.
- Fix the activation flows.

cc @ianstewart + @lucasmendes-design & @matt-west for copy suggestions.

## The Banner

<img width="700" alt="Screenshot 2023-11-27 at 15 37 47" src="https://github.com/Automattic/wp-calypso/assets/2070010/0f6338e2-23b7-499a-9755-4635de17d8d5">

On theme demo sites (e.g. https://hevordemo.wordpress.com/), we display an upsell banner with a primary CTA that, when logged-in, typically (not always) opens a sub-banner with two choices: "Activate" and "New Blog".

The primary CTA is (usually) only "Sign Up and Purchase" for logged-out users, without sub-banners.

This banner has a few issues that we need to address.

## The Primary CTA

<img height="40" alt="Screenshot 2023-11-27 at 16 01 23" src="https://github.com/Automattic/wp-calypso/assets/2070010/48a33f57-9089-478a-b5c2-ff98ae52ed65">
<img height="40" alt="Screenshot 2023-11-27 at 15 49 22" src="https://github.com/Automattic/wp-calypso/assets/2070010/bda25115-ed6c-48a2-8226-a11319d5d51e">
<img height="40" alt="Screenshot 2023-11-27 at 15 49 44" src="https://github.com/Automattic/wp-calypso/assets/2070010/5fa20d72-4acb-43aa-8898-ef5e8dc944e3">
<img height="40" alt="Screenshot 2023-11-27 at 16 07 37" src="https://github.com/Automattic/wp-calypso/assets/2070010/87ff032d-f30d-4640-9a5f-79535bf52649">

We currently have lots of different options for the Primary CTA, with inconsistent copy and actions depending on the user status, site type, and theme type. Sometimes it's entirely wrong (are we trying to sell Woo themes individually?).

We should make things clear, consistent, and correct.

Free themes are simple: we can use the same verb in all cases without giving it much thought.
Other themes, instead, depend on the site type; we don't really know the user's (selected) site type at this stage, and IMHO it's overkill to find out.

Easier to use a neutral word that we can use in all cases, like **"Obtain"**.
_(Although, it does sound a bit Dalek-y?)_

| Scenario | Now | Next (Proposals) |
| - | - | - |
| Logged-out, Free Theme | "Sign Up Now" | "Sign Up and Activate" |
| Logged-in, Free Theme | "Use This Theme" | "Activate" |
| Logged-out, Premium Theme | "Purchase Now" | "Sign Up and Obtain" |
| Logged-in, Premium Theme | "Purchase Now" | "Obtain" |
| Logged-out, Woo Theme | "Purchase $XX" | "Sign up and Obtain" |
| Logged-in, Woo Theme | "Purchase $XX" | "Obtain" |
| Partner Theme | N/D | N/D |

_Note: we don't need anything for Partner themes since we don't host their demo sites._

## The Secondary CTA

This only exists for logged-in users, it's always "Activate" and, if the user owns multiple sites, it also involves a site selection.

<img width="433" alt="Screenshot 2023-11-27 at 15 49 31" src="https://github.com/Automattic/wp-calypso/assets/2070010/7259f515-137c-4f24-bfb6-79b8abac5708">

Should this be **aligned to the primary CTA**?
"Activate" and "Obtain and Activate"?

How do we avoid repeating the same verb as in the Primary CTA?

## The Tertiary CTA

<img width="239" alt="Screenshot 2023-11-27 at 15 49 36" src="https://github.com/Automattic/wp-calypso/assets/2070010/7561099e-bd26-4079-aee3-c50e70fc655e">

Is "New Blog" the most appropriate label? What about **"New Site"**?

## The Flows

All the CTAs trigger a `with-theme` flow, although they don't seem to work appropriately.
Some checks to perform:

- [ ] Primary CTA (both logged-in and -out)
  - Current, Free theme: `https://wordpress.com/start/with-theme?theme=sunderland&ref=demo-blog&intervalType=yearly`
  - Current, Premium theme: `https://wordpress.com/start/with-theme?theme=hevor&premium=true&ref=demo-blog&intervalType=yearly&theme_type=premium`
  - Current, Woo theme: `https://wordpress.com/start/with-theme?theme=premium%2Ftsubaki&premium=true&ref=demo-blog`
  - All three `with-theme` flows should: create a new site with the theme pre-selected, routing towards the necessary upgrade flow (e.g. Premium plan for Premium themes, Business for Woo themes).
- [ ] Secondary CTA (only logged-in)
  - Not sure what happens here, but it never seems to really activate the chosen theme.
  - If the theme is included with the selected site: activate the theme.
  - Otherwise: route to upgrade + activate theme flow (with the appropriate plan).
- [ ] Tertiary CTA (only logged-in)
  - It should do exactly the same as the Primary CTA.
  - The action is duplicated just because on logged-in, the Primary CTA is generally used to open the sub-banner (and only has the `with-theme` flow as fallback action).

## Alternative Approach

What if we replaced this whole banner with a simple link back to the Theme Showcase?

> See this theme on the WordPress.com Theme Showcase

(Linked to `/themes/{THEME}`)

This way we'd have a single UI and centralized logic for all our activation/upgrade/subscription/upsell needs — plus, multisite logged-in users would have direct access to the proper site selection.

<img width="500" alt="Screenshot 2023-11-27 at 17 07 27" src="https://github.com/Automattic/wp-calypso/assets/2070010/29f9183e-5180-4d64-8003-ff72ab5dd079">

For this approach, we'd only need a good phrase (do we have a user-facing term for the Theme Showcase?), and we'd be good to go.

**Comment by ianstewart** [comment]
> What if we replaced this whole banner with a simple link back to the Theme Showcase?

This seems like a great idea.

**Comment by matt-west** [comment]
> What if we replaced this whole banner with a simple link back to the Theme Showcase?

I agree, this feels like a much simpler approach.

Perhaps the copy could be:

> Get this theme from [WordPress.com Themes]()

**Comment by Copons** [comment]
Worked in D131004-code.

@matt-west I presume you don't have access to it yet, but these are the changes:

| Before | After |
|--------|--------|
| <img width="835" alt="Screenshot 2023-12-05 at 18 48 41" src="https://github.com/Automattic/wp-calypso/assets/2070010/9f6e17a4-26f1-4786-b1a5-44b51aff1ecd"> | <img width="835" alt="Screenshot 2023-12-05 at 18 47 55" src="https://github.com/Automattic/wp-calypso/assets/2070010/c1e94f7e-0571-4377-a04b-dd90df7cd7f3"> | 

I've changed slightly the phrasing you suggested because it sounds a little more natural to me, but I'm totally open to updating it!

The reasonings are:
- I don't think we use the extended "WordPress.com Themes" name anywhere. I might be biased on this, but I think "themes" is redundant.
- "get this theme on" instead of "from" because you (typically) wouldn't get the theme and take it away, but use it _on_ WordPress.com. This said, I've never fully understood English prepositions, and I usually just randomly guess. 😄

**Comment by matt-west** [comment]
Thanks @Copons!

I think we can drop the period from the end. It feels redundant given the short sentence length, and it conflicts a bit with the WordPress.com link at the end.

**Comment by Copons** [comment]
Removed the period and shipped D131004-code.

Thank you all for the good work! 🙇‍♂️

**Comment by dsas** [comment]
@Copons some feedback on this here: p1702984559032929-slack-C048GFLMBGD
