### ISSUE TITLE
Query Block: No posts displayed in editor

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#84575]
### Quick summary

In the Site Editor, the Query Block doesn't display any posts even if they show on the frontend.

### Steps to reproduce

1. Go to an Atomic site (e.g https://scruffianatomicdec2021.wpcomstaging.com/)
2. Open the Site Editor

### What you expected to happen

You should see posts, like on the front end:

<img width="1512" alt="Screenshot 2023-11-27 at 17 01 59" src="https://github.com/Automattic/wp-calypso/assets/275961/2235900f-d663-4a92-8291-d3d36bc1290e">

### What actually happened

Instead I see no posts:

<img width="1165" alt="Screenshot 2023-11-27 at 17 01 31" src="https://github.com/Automattic/wp-calypso/assets/275961/588d4aed-0462-4eff-8129-c70138919923">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Reported by @henriqueiamarino on Pressable also:
https://mural.mystagingwebsite.com/
https://dosneue.mystagingwebsite.com/

**Comment by alaczek** [comment]
This is happening for me locally as well - in any template (home/index/archive) running WP 6.4.1, Gutenberg 17.1.2.
I was not able to replicate on Atomic site.

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS


– Tested on Simple: Replicated (17.1.2)
– Tested on Atomic – Could Not Replicate (17.0.2)
– Replicable outside of Dotcom (Pressable): Yes (17.1.3)


📌 FINDINGS and SCREENSHOTS

My Pressable site was running an outdated version of Gutenberg.

Replicated issue as soon as Gutenberg was updated to 17.1.3
![Editor](https://github.com/Automattic/wp-calypso/assets/2540430/7ff02290-31f9-4b10-8dfe-633b65bf3ce0)

![Live site](https://github.com/Automattic/wp-calypso/assets/2540430/818f57e8-7efc-40db-b7ff-b4584305712b)


📌 ACTIONS

– Reported in the Gutenberg repo too:https://github.com/WordPress/gutenberg/issues/56592

Keeping this one open to keep track of reports.

**Comment by filipanoscampos** [comment]
Looks like this will be fixed with version 17.2.

Keeping this open for now.

**Comment by Gustavo-Hilario** [comment]
Another report here: 7385217-zen

**Comment by draganescu** [comment]
Juts chiming in to say that this is happening to me too:


https://github.com/Automattic/wp-calypso/assets/107534/6d62d13c-7109-4b72-86dc-19940be534a3


Edit:

it is fixed by the latest gutenberg:

![image](https://github.com/Automattic/wp-calypso/assets/107534/4d2d6cc8-a835-4ea9-9edd-dcf6b51f1fb3)

**Comment by vcanales** [comment]
This has been fixed in the latest version of Gutenberg, which is currently in RC and due to be released next week. The RC is [available here](https://github.com/WordPress/gutenberg/releases/tag/v17.2.0-rc.1).

**Comment by draganescu** [comment]
We can close this.

**Comment by marissaexplores** [comment]
Just wanted to add that we are experiencing this as well.
Because of this issue, none of the blocks under the post template are editable.

Site editor:

![Screenshot on 2023-12-01 at 16_04_57](https://github.com/Automattic/wp-calypso/assets/102770686/6c130b44-fc00-49a6-aea1-81929a57f8aa)

Frontend:

![Screenshot on 2023-12-01 at 16_04_19](https://github.com/Automattic/wp-calypso/assets/102770686/10865164-d502-4383-8562-c53f7249710c)

**Comment by draganescu** [comment]
Hi @marissaexplores 👋🏻 If you upgate the Gutenberg plugin to the latest release (17.2.1) do you still experience the problem?
