### ISSUE TITLE
Theme: import demo content

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#84579]
# Description

In the theme/site setup process, a frequent pain point for both customers and HEs is the inability to easily make a site look like the demo site, populated with the same content as the demo site.  A new starter site may not look anything like the theme's demo site and we should offer a simple solution to import demo site content into a user's site.  We might do this through an import content, like many community themes have.  See

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
