### ISSUE TITLE
Launchpad i2: add funnels

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84596]

**Comment by yansern** [comment]
https://github.com/Automattic/wp-calypso/pull/84642

**Comment by yansern** [comment]
Funnels are in this P2 comment 
pdDOJh-2JD-p2#comment-2083

**Comment by yansern** [comment]
More funnels targeting specifically the subscribers stat page:
pdDOJh-2JD-p2#comment-2098

**Comment by yansern** [comment]
Done.
