### ISSUE TITLE
LoTS & LiTS Design your Own button

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#84624]
# Description
Add a [Design your Own] button to the LotTs and LiTS, similar to the Design Picker.

# Design
### Here is the production DP
<img width="1091" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/9921e897-2d72-485c-805c-3151d8ddcf02">

### Autumn's beautiful LiTS mockup
![image](https://github.com/Automattic/wp-calypso/assets/5665959/02bc810d-79dc-4bb2-8520-ee5e51e60d90)

### And LoTS mockup
![image](https://github.com/Automattic/wp-calypso/assets/5665959/34dd8f41-7380-4ce9-a19a-2c4cfa815bcb)

# Acceptance Criteria
- [ ] In LiTS button dimensions should align wi the "View All" button and be directly beneath it  (Autumn's design opinion)
- [ ] In LoTS, the button can be the same as the Design Picker (Autumn's design opinion)
- [ ] Button is on the right of the categories menu
- [ ] Button does not show on vw<960px (this needs more design I think and isn't really necessary)
- [ ] Tracks events, including prop `is_logged_in` or similar to differentiate LiTs & LoTS
- [ ] Get @lucasmendes-design  design approval

@Automattic/lego

**Comment by autumnfjeld** [comment]
@lucasmendes-design  Will do a quick mockup for us this week. 😄

**Comment by lucasmendes-design** [comment]
Hi there, I think we can use the same rationale as this one below. 
<img width="1044" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/5b1d080a-2da9-4017-aee8-295a78849887">

So, basically, we will have something like this. [Figma link](https://www.figma.com/file/Tv3pYqA3EcRfiXC31IxrXE?node-id=3262:38177&mode=design#633432253)

<img width="1105" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/1bbac049-56b8-40d0-afc2-419fdacb7d0f">

**Comment by autumnfjeld** [comment]
@lucasmendes-design  I don't understand the first picture in the comment above https://github.com/Automattic/wp-calypso/issues/84624#issuecomment-1836172736, and not sure what you mean by "the same rationale" ,  but the second picture is clear. :)

Will follow the design of the second picture. :)

**Comment by lucasmendes-design** [comment]
Sorry, reviewing my comment here doesn't make sense haha. Probably it was the covid yesterday.

**Comment by lucasmendes-design** [comment]
Btw, I believe we'll see more users using the dropdown. It's more visible: 

<img width="1544" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/197a0cbb-9fb7-41a0-b885-6f483adbfea3">

**Comment by taipeicoder** [comment]
Closing via #85138
