### ISSUE TITLE
Hide Post and Page Meta settings for sites on Free, Personal and Premium plans

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#84639]
# Important

This issue is closed. If you're looking to report a case of `Updating failed. Could not update the meta value of jetpack_seo_noindex in database`, **please report it on #86412**

### Quick summary

The SEO tools are a feature available to sites on the Business plan. More about this here https://wordpress.com/support/seo-tools/

However, in the page/post editor for sites on the Free, Personal and Premium plans, it's possible to add post/page meta information (SEO Title, SEO Description) though whatever is added will not reflect on the site when the page source is viewed.

The Page/Post Meta settings, as shown below, needs to be greyed out for sites on the Free, Personal and Premium plans since making changes doesn't produce any results.

![Screenshot at Nov 29 10-22-42](https://github.com/Automattic/wp-calypso/assets/4719037/c808608d-c3c1-418a-a15a-d7f3013aae83)

### Steps to reproduce

1. On a site with the Free, Personal or Premium plan open a page or post
2. In the post or page editor, click on the Jetpack icon in the top right corner of the editor screen
3. Under the SEO section, type an SEO Title and SEO Description.
4. Click Publish or Update to save the change.
5. View the source of the page or post and notice the meta information hasn't updated.
6. Repeat the steps above for a site on a Business plan or higher and you will notice the meta information is updated when you view the source.

![Screenshot at Nov 29 10-26-41](https://github.com/Automattic/wp-calypso/assets/4719037/eff42524-0b03-4666-9551-bd6ac89497b1)

### What you expected to happen

The SEO settings shouldn't be possible to edit on sites with Free, Personal or Premium plan.

### What actually happened

It's possible to edit the SEO settings on sites with Free, Personal or Premium plan though it doesn't make any changes to the site.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Premium Plan site, unproxied, non-a8c account

![CleanShot 2023-12-08 at 09 36 35@2x](https://github.com/Automattic/wp-calypso/assets/14153300/9c772090-9f57-4cfc-81dd-29190395b7f9)

Premium Plan site, frontend. It not only doesn't save SEO Title and Description, but the noindex toggle triggers an error message

https://github.com/Automattic/wp-calypso/assets/14153300/88a2c3c5-c808-4967-bd22-1c7d48f32653

📌 ACTIONS
- Triaged

**Comment by liviopv** [comment]
Escalation thread: p1702028916130899-slack-C02FMH4G8

**Comment by andrii-lysenko** [comment]
The change was successfully merged and should be deployed for all Simple sites. If there would be any further issues please let me know.

**Comment by supernovia** [comment]
Hehe, noting this too:
https://github.com/Automattic/wp-calypso/issues/41444

**Comment by Joshgrygiel** [comment]
Another report of this in: 7473253-zd-a8c 

Copying the post content using the code view, and pasting into a new post entirely allowed the content to save/publish as intended

Using the "Duplicate Post" feature, it copies the meta information as well and those copied posts will not save properly.

**Comment by csonnek** [comment]
more reports here: https://wordpress.com/forums/topic/seo-tab-on-jetpack-panel-disappeared/?view=all

**Comment by philnick206** [comment]
Report here: 7497553-zd-a8c

**Comment by philnick206** [comment]
Another report: 7497918-zd-a8c

**Comment by rickmgithub** [comment]
This case sounds like it's related to the same issue - 74139570-zd

**Comment by darnelldibbles** [comment]
Another report here: https://wordpress.com/forums/topic/grandfathered-account-i-pay-for-custom-domain-suddenly-cant-save-posts/

**Comment by ricklabsdotn8** [comment]
7530603-zen

**Comment by rickmgithub** [comment]
User from 74139570-zd has come back with more details.

They can still publish, but can't update (correct a typo, etc.) until the process fails, which sometimes takes a long time.
Most of the time, the process fails with an unknown error. 
There are more details on the ticket.

**Comment by kuropixel** [comment]
Another report. 7549704-zd-a8c

**Comment by renata-franco** [comment]
Any updates on this?

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/grandfathered-account-i-pay-for-custom-domain-suddenly-cant-save-posts/?view=all#post-4015768

**Comment by csonnek** [comment]
Reported in https://wordpress.com/forums/topic/jetpack-213/?view=all

**Comment by liviopv** [comment]
Closing this, as the original issue was fixed with https://github.com/Automattic/jetpack/issues/34582.

Reports for `Updating failed. Could not update the meta value of jetpack_seo_noindex in database` should go on https://github.com/Automattic/wp-calypso/issues/86412

**Comment by csonnek** [comment]
For anyone coming across this issue - we're now tracking this in #86412
