### ISSUE TITLE
Signup: remove "sign up" link from signup flows

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#8468]
![](https://cloudup.com/cxbIsqc6bcR+)
#### Steps to reproduce
1. Starting at URL: wordpress.com/start as new user
2. Notice that while you're going through the signup process, you have the option of clicking "sign up" in the top right
#### What I expected

We should only be showing the "log in" link for prospective new users in the nux flow. We should not be showing an option to "sign up," which is at best inactive, at worse distracting or broken.

**Comment by alisterscott** [comment]
This has been fixed:

<img width="1156" alt="screen shot 2017-07-18 at 12 09 54 pm" src="https://user-images.githubusercontent.com/128826/28297569-0f123854-6bb2-11e7-88f4-7aa90607b273.png">
