### ISSUE TITLE
Task: Remove PHP 8.0 as an option from Hosting Configuration.

### ISSUE THREAD

**Issue by jmdodd** [Automattic/wp-calypso#84716]
### Details

PHP 8.0 will no longer receive security updates as of 26 November 2023. Site upgrades to 8.1 are complete, and we now need to remove 8.0 as an option.

1. Start at wordpress.com/hosting-config/site-domain.com for any WoA site.
2. Under "Web server settings", notice that 8.0 is available as an option in the PHP version dropdown.

### Checklist

In `/client/my-sites/hosting/web-server-settings-card/index.js`:
- [ ] Remove PHP 8.0.
- [ ] Test Hosting Configuration changes on a test WoA site and verify PHP version changes on the site as set from Calypso.

### Related

https://github.com/Automattic/wp-calypso/issues/83752

**Comment by vindl** [comment]
@jmdodd I noticed that we still have `7.4` as an option in the dropdown. Should we remove it too or is there a special reason for keeping it around?

**Comment by jmdodd** [comment]
We'll start working on 7.4 removal next, but it is currently supported.
