### ISSUE TITLE
Importers url analyzer doesn't fire Tracks events

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#84710]
1. Go through hosting import flow at https://wordpress.com/setup/import-hosted-site/import
2. Expect event fire in the backend 
3. See from Tracks that there's not data

There's an backend event in the code but it doesn't seem to fire, slack convo p1701360382394249-slack-C01A60HCGUA

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
1. Visited https://wordpress.com/setup/import-hosted-site/import
2. Typed in https://fitabruta.com.br (site hosted on Pressable)
3. Proceeded with the onboarding flow and selected the option to create a new site
4. No events tracked on the corresponding Tracks page 

📌 ACTIONS
- Triaged

**Comment by simison** [comment]
@zaerl this came after our convo in November, but it's a bit dated at this point and not on team's board. Should I close this?

**Comment by zaerl** [comment]
Yes. It's outdated. Please proceed.
