### ISSUE TITLE
Setting to Make Internal Links Open in New Tab by Default 

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#84725]
### What

A user came to chat requesting a setting that allows internal links to open in a new tab by default without having to check the "open in new tab" box when adding an internal link to a paragraph. 

This was requested in 7381942-zen. However, there are other instances in Slack of users asking for this feature. 

### Why

The user wants a setting that allows them to change the default behavior for internal links to automatically open in a new tab. This is currently possible by clicking on the link in the Editor and checking the 'Open in new tab" box. However, they have to do that every time they add a link to their site and say it can be tiring since they add many internal links to their site but want users to remain on posts they are reading. 

### How

In Settings > Writing, there could be a setting like "All Internal links automatically open in new tab" and you can check to enable it.

**Comment by liviopv** [comment]
📌 ACTIONS
- Feature request kept but moved upstream https://github.com/WordPress/gutenberg/issues/57417
- Closing in favor of upstream request

📌 Message to Author
@kelasante I moved it to a core feature request above, please review it to see if it describes your request correctly. If not, please comment on the core issue paying attention to the commenting etiquette in core repos pbg9X-eVk-p2
