### ISSUE TITLE
Assembler: Investigate broken padding in header patterns

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#84738]
### Description

The Stacked Header with Social Icons and Search header shows broken (zero?) left and right paddings on Assembler, whereas in the live site, it's fine:

|Assembler|Live site|
|-|-|
|<img width="937" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/72f6ab42-c631-485f-9ec7-f74c81d8caa5">|<img width="1090" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/0e1efea1-293a-4d52-9889-b089b2fbac9d">|

Pattern source site: https://dotcompatterns.wordpress.com/2023/07/28/stacked-header-with-social-icons-and-search/

@Automattic/lego

**Comment by autumnfjeld** [comment]
Maybe related to https://github.com/Automattic/wp-calypso/issues/82228 cc: @miksansegundo

**Comment by arthur791004** [comment]
It's related to the viewport width on the large preview. For example, if the window size is 1060, the padding on your site also looks weird.

![image](https://github.com/Automattic/wp-calypso/assets/13596067/36441138-b873-46bd-a212-597eba511fe3)

If we set the viewport width to 1280 on the large preview, then it looks good.

![image](https://github.com/Automattic/wp-calypso/assets/13596067/ec624a94-c1d5-49ec-a546-46fa79809b5c)

**Comment by miksansegundo** [comment]
Solved! Thanks for the clue @arthur791004 🙂

<img width="1755" alt="Screenshot 2566-12-05 at 12 00 44" src="https://github.com/Automattic/wp-calypso/assets/1881481/57bb9e92-3e4a-4f14-b613-e5f348f0bf9c">

**Comment by fushar** [comment]
@miksansegundo Sorry what exactly did we do to resolve this? 😂 For posterity 😄

**Comment by miksansegundo** [comment]
@fushar I updated the pattern to add horizontal padding on the left and right columns.
