### ISSUE TITLE
Year-in-review: List of data points to gather

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#84758]
This is to build the master list of all data points that we're going to include in the recap.

Current data points are:

* Count of published posts
* Summarize views
* Most popular post on best day
* Count comments
* Most liked posts
* Top posts
* Top search terms
* Top referrers
* Upload summary
* Top images
* Geographic views
* Top commenters
* Most commented posts

Some additional Jetpack-related data points are being discussed in p1HpG7-pA9-p2#comment-68141.

**Comment by andres-blanco** [comment]
this is a relevant thread on Jetpack data points p1HpG7-pA9-p2#comment-68141

**Comment by markbiek** [comment]
Closing for now. At this time, we're sticking with the current set of data points and most likely won't include anything Jetpack specific this year.
