### ISSUE TITLE
Year-in-review: create necessary tables to run the process

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#84770]
We should use roughly the same structure that was being used in previous years so we keep code changes at a minimum.

The table creation is being tracked here: pMz3w-iRW-p2

**Comment by andres-blanco** [comment]
parent issue: https://github.com/Automattic/wp-calypso/issues/84757

**Comment by markbiek** [comment]
The table has been created as `recap_2023`
