### ISSUE TITLE
Subscriber flow: Update confirm email messages

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#84773]
During our walkthrough we uncovered some inconsistencies with how we asked our users to confirm their email. Also, the success message wasn't generic enough to cover all the possible use cases (free subscriber, paid subscriber with newsletter categories...).

## Current vs proposal

Figma link: IUfgRRiMWOSMjjIqveTISt-fi-210_379.

### Subscribe block
![Image](https://github.com/Automattic/wp-calypso/assets/25607244/740f62c6-ef9b-4858-968a-e7bdea711ae5)

### Modal
![Image](https://github.com/Automattic/wp-calypso/assets/25607244/f58cfc18-b221-45e1-b5c3-47e3c7ae35c2)

**Comment by simison** [comment]
@crisbusquets thanks, this aligns the copy to "confirm email" (and not "verify"). The heading in the modal is specifically helpful I think. 👍  

That said, should we instead talk about "confirming subscription" (instead of "confirm email") in the paywall nudge as well, as we do in the modal? I think the modal is clearer in this way.

Not a blocker for shipping this already.

**Comment by crisbusquets** [comment]
> That said, should we instead talk about "confirming subscription" (instead of "confirm email") in the paywall nudge as well, as we do in the modal? I think the modal is clearer in this way.

Ahhh yes! You're right.

I updated the Figma above and I'm attaching the screenshot again to confirm:

<img width="921" alt="Screenshot 2023-12-07 at 10 51 31" src="https://github.com/Automattic/wp-calypso/assets/25607244/9c554b82-9b0e-4cef-afe7-f06903174317">

**Comment by simison** [comment]
First part of the copy updated in https://github.com/Automattic/jetpack/pull/34716 for the lock/wall.

**Comment by chrisfromthelc** [comment]
@simison @crisbusquets 

For the confirm modal ("Almost there!...), the description part has separate text for non-WPCOM sites.

`An email has been sent with a link to confirm your subscription.`

Do we want to make this the same across WPCOM and non-WPCOM sites, or do you have separate copy for those non-WPCOM sites?

Also, should I widen the text area on this? 

![Screenshot 2023-12-19 at 12 36 40 PM](https://github.com/Automattic/wp-calypso/assets/8002138/c6e5a544-308e-4269-8515-584aa64a5e1d)

`chrisfromthelc+2119628336@gmail.com` isn't a particularly long email address. Also, perhaps we could rework it so the email address always fails on a separate line to lessen the chance of the email causing issues. Something kind of like:

```
We're sent an email to your account:

chrisfromthelc+2119628336@gmail.com

Confirm your address to start receiving content from this site directly to your inbox.
```

**Comment by chrisfromthelc** [comment]
Something like this. The left and right padding+margin totals would be 48px on each side.

![Screenshot 2023-12-19 at 1 00 59 PM](https://github.com/Automattic/wp-calypso/assets/8002138/1e35c4ee-beda-4650-ac18-63b0fa364a70)

**Comment by chrisfromthelc** [comment]
Here is where I ended up on both modals. If we don't want to do the wider confirm message, I can switch it back. Also, I wasn't quite sure on spacing for the content (below the site title, above the button), so I just based it off what looked right compared to what we did on the plan selector.

![Screenshot 2023-12-19 at 1 26 53 PM](https://github.com/Automattic/wp-calypso/assets/8002138/605a3ac0-be69-4f9f-ba3c-e70589838d63)
![Screenshot 2023-12-19 at 1 27 02 PM](https://github.com/Automattic/wp-calypso/assets/8002138/01de9f7b-3232-4b27-9b13-60886bdcf3b0)

**Comment by crisbusquets** [comment]
Hi @chrisfromthelc ,

Thanks for working on this, sorry for the delay!
Works for me if it improves readability and the width and spacing are similar to other modals during the flow (which is what I understand from the screenshots you shared).

**Comment by chrisfromthelc** [comment]
I've merged the changes.
