### ISSUE TITLE
Cannot add Professional Email to domain in cart if the email upsell is skipped at domain step

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#84780]
### Quick summary

When a user adds a domain to a site, they are offered a Professional Email upsell on the screen following domain selection. If they skip this and go to their cart but then change their mind, they cannot add go back and Professional Email until completing checkout for the domain. 

I've chatted with a few users who found this confusing. 

### Steps to reproduce

1. Add a domain to a site
2. Skip the Professional Email upsell and go to checkout
3. Leave the checkout without purchasing (keep items in cart)
4. Attempt to add Professional Email from My Site > Upgrades > Email 

### What you expected to happen

I would expect that the option to purchase an email was available while I had a domain in the cart. 

### What actually happened

My Site > Upgrades > Emails shows a domain selection screen rather than the option to add email to the domain that was selected and in cart. 

![Markup on 2023-12-01 at 12:04:50](https://github.com/Automattic/wp-calypso/assets/76757079/a00bbf62-a027-4a63-bc2a-6da544f3b502)

### Impact

All

### Available workarounds?

There is no user impact

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I have followed the steps and was not able to replicate the issue. After leaving the checkout, I was able to get back to the Upgrades section and add the Professional Email subscription to any of the registered domains. It's displayed in the Checkout alongside the domain to be registered:
![Markup on 2023-12-13 at 00:16:16](https://github.com/Automattic/wp-calypso/assets/9025643/bcdabf68-2c30-429c-bad9-d51b2c04cfe5)

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by sajmes** [comment]
I was unable to get this to work on AT or simple sites.

Simple site:

1. Add plan and domain to cart but do not choose email upsell
2. Navigate to cart
3. Leave cart, keeping domain and plan in cart
4. Navigate to Upgrades > Emails
5. The only option shown is to add a plan or domain. Choosing to add a plan does not then show an email upsell. There is already a plan and domain in cart.
![Plan and domain in cart](https://github.com/Automattic/wp-calypso/assets/76757079/2a61d79e-4068-4827-89b1-79f2506bd0b4)
![No email option](https://github.com/Automattic/wp-calypso/assets/76757079/bc8c7861-f31d-4b7c-963d-b257ef36aeda)

I also tested on AT on a site which has a plan already added.

1. Add domain to cart and do not choose email upsell
2. Navigate to cart
3. Leave cart, keeping domain in cart
4. Go to Upgrades > Email
5. Only option shown is to add a domain

![Markup on 2023-12-13 at 08:35:16](https://github.com/Automattic/wp-calypso/assets/76757079/b3e8ac82-c3ec-4166-b850-78ee756fb293)

**Comment by fredrikekelund** [comment]
@sajmes, I'm personally not convinced that this is something we want to fix. I can think of a few reasons:

- When navigating back from the checkout page, either by clicking the `X` link in the top left corner or navigating back in your browser history, users land on the email upsell page. So, if they change their mind about email, the two major paths away from the checkout page will immediately present them with the same offer again.
- Changing the email management page to account for domains in the cart adds considerable complexity to the code. I may be biased from considering the code first, but I don't see this leading to enough new conversions to warrant that technical complexity.

I know this is an old issue, but I would still be interested in looking at cases where users have reported confusion around this. @sajmes, if you, by any chance, have links to tickets where this topic has come up, it'd be great if you could share them 🙏
