### ISSUE TITLE
Assembler - Manage navigation in a screen after users add pages

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#84797]
## What

Allow users to manage the navigation menu items in the assembler after adding pages. 

Possible actions are:

- **Remove menu items**
 This is useful when they have duplicated pages
- **Rename menu items**
 This could be useful if the assembler uses distinctive titles for duplicated pages
- **Add menu items for new pages**
 This is useful for existing sites using a navigation menu without a page list block.

When an existing site has a navigation menu, chances are that that menu doesn't contain a page list block because users can delete the page list block or just create a custom menu with only static links at any time. If there isn't a page list block, then the assembler and the editor won't show the newly added pages, users will have to add them manually to their menu from the editor. 

### What navigation menu is shown in the assembler previews?
The assembler renders navigation blocks using the core fallback method, which is the latest created menu on the user site or a page list.

We can see the latest created menu at the top of the list at `{ YOUR SITE }/wp-admin/edit.php?post_type=wp_navigation&orderby=date&order=desc`.

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/5f03d9ba-0fc5-4942-9717-c9ecc39a3e18)

## Why

Assuming that one purpose of the Assembler is to take some “hard” concepts and simplify them, so that the user is better prepared when they get to the editor.

## How
- if the site doesn't have a menu, or has a menu that contains a page list block, the only way to hide pages in a page list block is by making them as drafts. 
- if the site has a menu without a page list block, the assembler can edit that menu to hide/rename/add static links or create a new menu. Note that if that site has a menu associated with a navigation block, the assembler must update that navigation block reference `ref` to associate it with the new menu. 

cc: @Automattic/lego

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
