### ISSUE TITLE
Newsletter stats: open rate

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84814]
Currently the open rate is calculated like this:

`open rate = total opens / total sends`

This means it can go over 100%, and is not accurate at all. We should be able to get unique opens through the individual subscriber stats table.

**Comment by TimBroddin** [comment]
Additional task:

In the view show an extra box for unique opens

**Comment by JuanLucha** [comment]
> Additional task:
> 
> In the view show an extra box for unique opens

Here is the link to the new task: https://github.com/Automattic/wp-calypso/issues/85097

**Comment by JuanLucha** [comment]
This task is fixed in D131460-code

**Comment by JuanLucha** [comment]
I'll add a filter to show the new changes when the email was sent after the release of the new field in the backend so we don't show weird data to users. This is the task: https://github.com/Automattic/wp-calypso/issues/85430
