### ISSUE TITLE
Uploading images in the Site Editor results in "Invalid parameters: post" on Simple and Atomic sites

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#84818]
### Quick summary

When trying to upload images in the Site Editor, an "invalid parameter(s)" error message appears, and the image fails to upload. This issue appears to be specific to the Site Editor; uploading images still works fine in the post/page editor and the Media Library. I've tested this with various Full Site Editing (FSE) themes, and the error persists regardless of the theme used.

### Steps to reproduce

1. Load the Site Editor (Appearance > Editor) 
2. Add an Image or Media & Text block (or any other block that allows for image uploads)
3. Try to upload an image file

The issue can also be replicated if you add a Block pattern and try to replace the images included by uploading your own.

### What you expected to happen

The image is correctly uploaded and displayed.

### What actually happened

This failed and we see the message "Invalid parameters: post".
<img width="1323" alt="Markup 2023-12-22 at 15 32 31" src="https://github.com/Automattic/wp-calypso/assets/99455043/8dd283b9-768b-4400-9d77-a92e7d250edd">

https://github.com/Automattic/wp-calypso/assets/2540430/915538f7-3d74-40f6-b436-f0621c22664e

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Reported in 7401215-zd-a8c

**Comment by ha-un** [comment]
Another report: 7403941-zd-a8c

**Comment by upwardmomentum84** [comment]
Another report: 7407751-zd-a8c

Uploading the image to the Media library first and then using the "Select Image" option to select it from the Media library worked for this site.

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Replicated

📌 ACTIONS

– Report kept.

**Comment by mikeicode** [comment]
I constantly run into this issue when building sites for customers (BBE). Although it's not a complete blocker, it's pretty annoying and does waste time.

**Comment by Joshgrygiel** [comment]
Another: 7424479-zd-a8c

I shared the workaround of uploading to the media library first

**Comment by coder-mahfuz** [comment]
Another report: 7407751-zd-a8c

**Comment by mahfuzurwp** [comment]
Another report: 7425757-zd-a8c

**Comment by hacchism** [comment]
Another report: 7427117-zd-a8c
Theme: Twenty Twenty-Three
Site type: Atomic

**Comment by jerren1327** [comment]
Another report: 7395952-zd-a8c
Theme: Twenty Twenty-Three

**Comment by dev-sabbir** [comment]
Another: 7427173-zd-a8c
Site type: Atomic
Theme: Creation 2

**Comment by aleone89** [comment]
Reported here in the forums: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009759

**Comment by Joshgrygiel** [comment]
Another here: 440497-zd-a8c
Atomic, Creatio 2 theme

**Comment by jerren1327** [comment]
Another report: 7395952-zd-a8c
Atomic, Annalee  theme

**Comment by jerren1327** [comment]
Another report: 7404960-zd-a8c
Iotix theme

**Comment by jp-imagines** [comment]
Another report in 7446079-zd-a8c. (Simple, Annalee theme.)

**Comment by jp-imagines** [comment]
And another here: 7447303-zd-a8c (Atomic, Tsubaki theme)

**Comment by supernovia** [comment]
Another report in this thread:
https://wordpress.com/forums/topic/invalid-parameterpost/page/2/?view=all#post-4010465

**Comment by supernovia** [comment]
Adding each separate user from this thread, so we can see the scope:
https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4008488

**Comment by supernovia** [comment]
Another: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009087

**Comment by supernovia** [comment]
Another: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009263

**Comment by supernovia** [comment]
Another case: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009702

**Comment by supernovia** [comment]
Another case: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009738

**Comment by supernovia** [comment]
Another case: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009750

**Comment by supernovia** [comment]
Another case here: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009752

**Comment by supernovia** [comment]
Another case: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009793

**Comment by supernovia** [comment]
Another report here: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009799

**Comment by supernovia** [comment]
Another user: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009835

**Comment by supernovia** [comment]
Another user: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009926

**Comment by supernovia** [comment]
Another user: https://wordpress.com/forums/topic/invalid-parameterpost/?view=all#post-4009931

**Comment by ianstewart** [comment]
Reproduced with the Ritratto theme. (The Hemingway one.) 

- Activate the theme
- Click on the big image of Hemingway
- Click replace
- Click upload
- Select an image
- Get the invalid results notification
- Then see a missing image like the screenshot below

![image](https://github.com/Automattic/wp-calypso/assets/545779/f9719698-08e7-4fbb-8b84-40755a6eb187)

**Comment by taipeicoder** [comment]
Reproduced this issue with TT4 on an Atomic site. Downgrading Gutenberg to 17.0.3 no longer reproduces the issue, while 17.1.0 still has this problem.

**Comment by glendaviesnz** [comment]
https://github.com/WordPress/gutenberg/issues/57037

**Comment by glendaviesnz** [comment]
Temporary workaround is to open media library and upload image from there

**Comment by glendaviesnz** [comment]
Possible fix https://github.com/WordPress/gutenberg/pull/57040

**Comment by jp-imagines** [comment]
Another report in 7450454-zd-a8c (Atomic, Creatio 2 theme). 

Of note: only the `Home` (`Blog Home`) template appears to be affected. Trying to upload an image from your device results in the `Invalid paramter(s): post` error, while trying to upload an image from Pexels or Openverse results in a similar `Invalid paramter(s): post_id` error. Replicated this on a test site using TT3 as well.

**Comment by cuemarie** [comment]
More customer reports here: 

- 7447195-zen (ticket)
- 7458865-zen (chat)

**Comment by hacchism** [comment]
Another report: 7463309-zen
Atomic, Hevor theme

**Comment by krutidugade** [comment]
Another report: 7386020-zen

**Comment by edequalsawesome** [comment]
Another report: 7474909-zen

Premium plan, Iotix theme

Follow-up: 7474946-zen

**Comment by wiesenhauss** [comment]
7488993-zen

**Comment by wiesenhauss** [comment]
Updated issue title and description to expand the scope of the report as both Simple and Atomic sites are affected for all image uploads (not just replacing images).

**Comment by Aurorum** [comment]
7489105-zen

**Comment by jromales** [comment]
7492074-zen - shared the suggested workaround (add image in Media library and open from there)

**Comment by OmarFPG** [comment]
7498551-zen |  Creator plan, Atomic site, Tsubaki theme. Provided the upload to media workaround.

**Comment by TPilgs** [comment]
7510944-zen Creator plan, Atomic, provided the upload to media workaround as well, but they also wanted to use Pexels images and can't.

**Comment by liviopv** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/34795 closing

Context: p1706193620037239/1703590834.062169-slack-C02FMH4G8
