### ISSUE TITLE
Assembler: new CTA graphic 🤩

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#84845]
# Description
Update the Assembler CTA graphic.
* PT: Assembler Choice Step in Onboarding – Team Lego https://teamlegop2.wordpress.com/2023/11/29/pt-assembler-choice-step-in-onboarding/
* Onboarding: design choice page – Dotcom Design https://dotcomdesignp2.wordpress.com/2023/11/27/onboarding-design-choice-page/

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/78c50a9d-ef8a-44b7-9db2-91da0f407263)

Figma: https://href.li/?https://www.figma.com/file/Tv3pYqA3EcRfiXC31IxrXE?node-id=3251:12444&mode=design#632229544

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/84849
