### ISSUE TITLE
Assembler: Add support for kebab-case in steps and params

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#84846]
## What

We have been asked a few times why we are using camelCase in step names and params like in `/setup/with-theme-assembler/patternAssembler?siteSlug={ SITE }`. See the most recent time in p1700321967885689/1700040293.699609-slack-C048CUFRGFQ

## Why

Because kebab-case is a common convention for URLs and AFAIK there is no need for using cameCase.

See https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/#whatiskebabcaseanamekebabcasea

## How

We could start by adding support for kebab-case on the steps and params we use in the assembler without removing support for camelCase to avoid breaking links.

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
