### ISSUE TITLE
The uploaded Profile Photo in /me gets removed

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#84857]
### Quick summary

In https://wordpress.com/me a new profile photo gets uploaded, but gets removed after refreshing the page or when switching to a new page. 

### Steps to reproduce

1. Go to https://wordpress.com/me
2. Upload a profile photo. 
3. It will show the banner "You successfully uploaded a new profile photo --- looking sharp!" 
4. Refresh the page or switch to a new page. 

### What you expected to happen

Refreshing the page or switching to another page will not remove the profile photo. 

### What actually happened

If there's no profile image - after uploading a new profile image, refreshing the page or switching to another page removes the profile photo. 

If there is an old profile image - after uploading a new profile image, refreshing the page or switching to another page removes the new image and displays the old image. 

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Chrome 119, macOS 14.1.2
- User report 7406646-zen 

---

### If there's an old image, before uploading: 

<img width="1135" alt="Screenshot 2023-12-05 at 12 00 58" src="https://github.com/Automattic/wp-calypso/assets/36863633/0b8a9eab-7c56-42fd-9b1b-67a8c4fdd0c3">

After uploading, "You successfully uploaded a new profile photo --- looking sharp!"  banner appears: 

<img width="1129" alt="Screenshot 2023-12-05 at 12 00 47" src="https://github.com/Automattic/wp-calypso/assets/36863633/539d133c-2376-453f-a85a-b0a1024f2daf">

After refreshing the page or going to another page and back to /me, the old image remains:
 
<img width="1125" alt="Screenshot 2023-12-05 at 12 00 18" src="https://github.com/Automattic/wp-calypso/assets/36863633/39f37670-e314-4ba2-b3e5-6a893618e990">

---

### If there's no image, before uploading: 

<img width="1382" alt="Screenshot 2023-12-05 at 12 06 54" src="https://github.com/Automattic/wp-calypso/assets/36863633/779a0ca8-1921-45ac-9651-56304cef5111">

After uploading, "You successfully uploaded a new profile photo --- looking sharp!"  banner appears: 

<img width="1395" alt="Screenshot 2023-12-05 at 12 07 11" src="https://github.com/Automattic/wp-calypso/assets/36863633/be65631d-d4b2-4d80-8a8a-3b63a499b281">

After refreshing the page or going to another page and back to /me, the old image remains:

<img width="1334" alt="Screenshot 2023-12-05 at 12 07 25" src="https://github.com/Automattic/wp-calypso/assets/36863633/07802fe4-f2d3-4e15-9284-973c0833c432">

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Replicated exactly as described


📌 ACTIONS

Escalated:
p1701792841005299-slack-C02FMH4G8

**Comment by Aurorum** [comment]
7381374-zen

**Comment by Aurorum** [comment]
7406309-zen

**Comment by jp-imagines** [comment]
Another report in 7380906-zd-a8c. Able to replicate on my test account still too.

**Comment by lamosty** [comment]
Have there been any new reports of this particular issue since 5 days ago, please? On Dec 7th we came up with a batch fix for all of the Gravatar users with malformed identities so it should be addressed. There could be still some caching issues though as that's unrelated to the main bug.

**Comment by helenaartmann** [comment]
I am answering a recent ticket with this issue: 7439160-zd-a8c

**Comment by mariammcWP** [comment]
7521118-zen

**Comment by krutidugade** [comment]
@lamosty We still have user reports regarding this issue indicating it isn't completely fixed for everyone. I was able to replicate it on my test WP.com account.

**Comment by krutidugade** [comment]
As per the latest discussion with @lamosty in Slack DM, the issue no longer exists. I can update profile pic for my test account.

**Comment by krutidugade** [comment]
Closing this issue for now. We can reopen it if the issue resurfaces.
