### ISSUE TITLE
Like block: make sure there are no conflicts with current implementation

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#84852]
The like widgets inserts two iframes:
- a master iframe
- one iframe per like widget

To make sure there are no conflicts, there probably can be only one master iframe

We also need to make sure it is possible to load more than one Like buttons on one post / page.

**Comment by ivan-ottinger** [comment]
Multiple Like buttons: p1702309587445189/1702309146.928149-slack-C02TCEHP3HA

**Comment by TimBroddin** [comment]
I have a draft PR ready that should allow for this: D131588-code. Should anyone want to pick this up while I'm gone, I think this PR should not break anything.

A bit deeper explanation of what's going on there:

Currently, for every API request, a key of a hashmap object is created containing (among other things) the obj_id of the iframe where the like widget should be rendered:


```js
						request = {
							type: 'post',
							blog_id: info.blog_id,
							post_id: info.post_id,
							obj_id: info.obj_id,
							width: event.width,
							slim: info.slim,
						};

						wpLikes.requests[ path ] = request;
						wpLikes.getPostLikes( info.blog_id, info.post_id, wpLikes.displayWidget );
``` 

Once the API request is finished, a callback (`wpLikes.displayWidget`) is called, and in this callback the `request` object (containing the obj_id) is fetched again. 

I changed the signature of the callback, to also pass along the `request` object, thus eliminating the need of looking of the request:

```
	wpLikes.getPostLikes( info.blog_id, info.post_id, ( response, path ) => wpLikes.displayWidget( response, path, request ) );
```
