### ISSUE TITLE
Like block: display placeholder Like and Reblog buttons with avatars in the block editor

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#84868]
Goals:
- display placeholder Like and Reblog buttons with avatars in the block editor; let's use styles 
- the Reblog toggle setting should be reflected

**Comment by ivan-ottinger** [comment]
I have started looking into adding the server-side render to the block in https://github.com/Automattic/jetpack/pull/34563.

The Like widget doesn't load the necessary `master.html`, `queuehandler.js` nor CSS styles in the block editor automatically (as the widget was built to be used in front-end only). This means we would need to manually load them there and make sure they work as expected.

I think instead we could consider creating a placeholder Like and Reblog buttons for the block editor.

**Comment by TimBroddin** [comment]
> I think instead we could consider creating a placeholder Like and Reblog buttons for the block editor.

I agree, just fake it. It doesn't have to be functional or show real data.
Just render the buttons & avatars & style them 😀

Inserting all those scripts & altering the actual widget to display mock data seems a bit much.

**Comment by ivan-ottinger** [comment]
I have updated the task title and description.
