### ISSUE TITLE
Replace 'Import an Existing Site' icon for better clarity

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#84870]
The icon currently used for the 'Import an Existing Site' feature (`arrow-down`) seems more fitting for indicating a download or export action, rather than import.

<img width="391" alt="Screenshot 2023-12-05 at 15 25 21" src="https://github.com/Automattic/wp-calypso/assets/4933/ca9bad6e-5d0d-4aa5-b2a4-fc1dbe0cd683">

We should consider replacing it with the `upload` icon from the Gutenberg library to better represent the action of importing a site.

![image](https://github.com/Automattic/wp-calypso/assets/4933/890a537e-c746-4701-ae8c-91506a73f775)

**Comment by sejas** [comment]
@katinthehatsite , can you replace our icon for `Import site to WordPress.com` to use the `upload` direction?

<img width="548" alt="Screenshot 2023-12-05 at 14 42 34" src="https://github.com/Automattic/wp-calypso/assets/779993/d2f07fe5-40b6-406d-929b-45043f993d20">

**Comment by katinthehatsite** [comment]
@sejas - on it!

**Comment by javierarce** [comment]
I've added an explanation [here](https://github.com/Automattic/wp-calypso/pull/84873#issuecomment-1845739196) on the icon we agreed to use for Import. Sorry for the back and forth!

> After discussing with other designers, we’ve decided to use the download icon for the 'Import' function, as @wojtekn suggested. The direction is not as important as the fact that the arrow in that icon points towards the enclosure.

**Comment by danielbachhuber** [comment]
🚢
