### ISSUE TITLE
Stats: Adjust purchase page layout

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#84885]
<img width="262" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1425433/0b608d8a-4d57-4bf5-9ab7-b8b1953c4ae5">
<img width="309" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1425433/bf2fe60a-da47-478c-98f1-f22b9cb3a5ce">

**Comment by grzegorz-cp** [comment]
We can extend this task to optimise the look and feel of the page for narrow viewports.
It was reported in our call for testing p1HpG7-qbN-p2#comment-68628.

**Comment by dognose24** [comment]
The purchase page is not responsible for the mobile: p1HpG7-qbN-p2#comment-68628

<img width="740" alt="截圖 2023-12-18 下午3 16 56" src="https://github.com/Automattic/wp-calypso/assets/6869813/a0acfb6f-2b5d-43b3-a9cf-18a7394c51b6">

**Comment by kangzj** [comment]
New design: p1HpG7-rv4-p2
