### ISSUE TITLE
Assembler Level-Up: Use new patterns under feature flag

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#84893]
## Description

We want to show next-generation / "leveled-up" patterns in the Assembler flow.

## Design Tasks

- [x] Create `post` patterns without references to `wp_block` patterns. In other words, the `post` patterns should not contain `wp_block` patterns, but they can still exist on the source site https://assemblerv2patterns.wordpress.com.  
- [x] Move patterns v1 to the new source site in case we want them in Assembler v2
- [x] Move page patterns to the new source site and tag them as `assembler_page`.  

## Dev Tasks

- [X] Introduce new `pattern-assembler/v2` flag. Set to `true` in horizon.
- [X] When the flag is true, fetch the patterns from the source site https://assemblerv2patterns.wordpress.com.

**Comment by miksansegundo** [comment]
The dev tasks are completed and the Assembler v2 can now be tested on Horizon.

I have updated the design tasks in this issue. Read more at https://github.com/Automattic/wp-calypso/pull/84977#issuecomment-1851365716

**Comment by fushar** [comment]
We have enabled the new patterns on Horizon (https://github.com/Automattic/wp-calypso/pull/86510). We can consider this issue complete, and we can keep refining the patterns.
