### ISSUE TITLE
Refreshed Fullpost: Make embeds full width?

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8489]
I think it's weird that video embeds are sometimes wider on the stream than they are on the fullpost. For example:

![screen shot 2016-10-05 at 10 31 41 am](https://cloud.githubusercontent.com/assets/24388/19124202/0f8a5dfe-8ae7-11e6-8a4c-efc199c87980.png)
![screen shot 2016-10-05 at 10 31 36 am](https://cloud.githubusercontent.com/assets/24388/19124203/0f8a66dc-8ae7-11e6-920a-913160de7673.png)

Could we set video embeds to full width on fullpost? cc @jancavan

**Comment by blowery** [comment]
We can reuse the sizing strategy stuff we currently use in the streams to handle this.
