### ISSUE TITLE
Posts: "Latest Drafts" in sidebar squished in small screen sizes

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8490]
#### Steps to reproduce
1. /posts for a Jetpack site
2. Make a few drafts
3. Resize your browser (I saw this with Chrome on OS X)

#### What I expected

Latest Drafts to drop or adapt better

#### What happened instead

The column is squished in the midpoint before the smaller layout takes effect (moving it to the section navigation)

#### Screenshot / Video

![screen shot 2016-10-04 at 15 47 55](https://cloud.githubusercontent.com/assets/66797/19124873/ca5c5b26-8ae9-11e6-8cd3-20b6aed4625e.png)

![image08](https://cloud.githubusercontent.com/assets/66797/19124890/d79c020a-8ae9-11e6-9dff-0b3261e552b5.png)
#### Context / Source

#7920 manual-testing raised by @beaulebens

**Comment by drw158** [comment]
Seems like this is less of a problem now

![screen shot 2017-03-17 at 4 01 36 pm](https://cloud.githubusercontent.com/assets/618551/24062883/4b10bc78-0b2b-11e7-97cb-e5c3cb2e1bce.png)

**Comment by lancewillett** [comment]
Cool, good find. Let's close it.
