### ISSUE TITLE
Live Preview: Theme name not showing properly in Atomic sites

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#84906]
### Steps to reproduce

1. Prepare an Atomic site.
2. Go to `/themes`.
3. Preview & Customize any theme.

### What I expected

The theme name should be correct (with Title Case).

### What happened instead

The theme has lowercase letters (e.g. `artly` in the below example):

<img width="844" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/e91f5950-552a-49d9-afff-ee4ecc1516c2">

@Automattic/lego

**Comment by autumnfjeld** [comment]
Deprioritizing this a bit, since it isn't impacting any functionality or user understanding.

**Comment by fushar** [comment]
This is shipped.
