### ISSUE TITLE
Import from WordPress: source site info gets lost after page reload

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#84918]
Steps to reproduce:
1. Start import from WordPress in Tools > Import, you end up on this page where you enter the source site URL:

   <img width="1073" alt="Screenshot 2023-12-06 at 12 26 16" src="https://github.com/Automattic/wp-calypso/assets/664258/af0e6f15-2f5a-4ae7-b2e7-bedcb600baf5">

2. After you enter the source site URL, the site info is loaded and you see the next step:

   <img width="1053" alt="Screenshot 2023-12-06 at 12 30 08" src="https://github.com/Automattic/wp-calypso/assets/664258/58209f61-559c-4410-bd33-22460e6144a4">

3. Now, reload the page! The site info is lost and you see the URL input again:

   <img width="1052" alt="Screenshot 2023-12-06 at 12 31 43" src="https://github.com/Automattic/wp-calypso/assets/664258/bca233e5-47b9-4f9b-a063-bd86ba7cb63e">

But this time the URL input doesn't work, because the `<SitesBlock>` component that's rendering the input is not getting the `url` and `onChangeUrl` props that manage the input. You see a console warning about uncontrolled `input` component.

At this point you're stuck, because entering the source site URL doesn't work.

The problem is caused by how the navigation between `/migrate/:site` and `/migrate/choose/:site` hands over the source site URL. It's stored in local state of one of the components, which accidentally, almost by miracle, is rendered on both routes at the same place in the React tree, and therefore preserves the local state. It's very fragile and after page reload the local state is lost.

**Comment by simison** [comment]
Ping @Automattic/caribou to look.

**Comment by bogiii** [comment]
Thanks for reporting it; I placed it into our Migration Maintenance project and will try to fix it soon.
