### ISSUE TITLE
Posts: for Jetpack sites, filtered plugin content can show up in post content

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8491]
#### Steps to reproduce
1. Starting at URL: /posts for a Jetpack site
2. Enable a plugin that adds Sharing Buttons, or something like o2 that adds a Reply button on the front-end of the site
3. View the Calypso posts list
4. Notice how the extra content shows in the posts list — unstyled, such us `(Reply)`
#### What I expected

Posts content in Calypso posts list to not show filtered JavaScript output from the front-end view.
#### What happened instead

The extra content is added in the post content.

Note: This doesn't happen with WP.com sites running o2/P2.
#### Screenshot / Video

Example from @beaulebens Jetpack site:
![image12](https://cloud.githubusercontent.com/assets/66797/19125101/a5448704-8aea-11e6-86a1-85d01cd4c37a.png)

Example from o2/P2 Jetpack site:
<img width="877" alt="screen shot 2016-10-05 at 10 59 12" src="https://cloud.githubusercontent.com/assets/66797/19125137/c76e1e62-8aea-11e6-9b06-188cae8d3667.png">
#### Context / Source
# dogfooding

**Comment by lancewillett** [comment]
Maybe related: #1292

**Comment by lancewillett** [comment]
Saw this again today with what appears to be Jetpack sharing plugin output (I don't have any other plugins running besides Akismet, Jetpack, Debug Bar).

<img width="840" alt="screen shot 2016-11-19 at 12 31 18" src="https://cloud.githubusercontent.com/assets/66797/20508355/4db41cf8-b01e-11e6-9307-ddecc28d93f9.png">

"Share this" text shouldn't show up in the post list view at all, it's not part of the post content.

**Comment by jeherve** [comment]
Also reported here:
https://github.com/Automattic/jetpack/issues/4601

@lezama Where would you prefer us to keep track of this problem?

**Comment by lancewillett** [comment]
I feel like this should be a simple solution by changing how the post content is filtered in in the API endpoint. Should the post content always run all filters from plugins in this editing context? Should post list preview / view be considered editing?

**Comment by jeherve** [comment]
From the original issue:

> I wasn't able to replicate this bug.
> We did a few fixes such disabling the sharing filters when we sync data so this shouldn't show up in the api any more.
>
> Feel free to reopen this issue if you can still replicate this bug.

**Comment by lancewillett** [comment]
See also https://github.com/Automattic/wp-calypso/issues/1292

**Comment by lancewillett** [comment]
I can still repeat with a Jetpack site connected to Calypso.

<img width="988" alt="screen shot 2017-01-16 at 06 51 39" src="https://cloud.githubusercontent.com/assets/66797/21985495/44a9b2f6-dbb8-11e6-9475-a6234712a8f6.png">

One easy way to duplicate is to enable o2 plugin and P2 Breathe theme on a Jetpack-connected site; you'll immediately see `Reply` text from o2/P2 added into the Calypso post list preview. (This same bug doesn't happen with a WP.com site.)

**Comment by lezama** [comment]
Could we maybe apply the same processing that we do for emails? cc
@gravityrail

**Comment by beaulebens** [comment]
@lezama / @gravityrail yeah, something along those lines might make sense as an abstracted out "fix this post for display" type library, because I imagine the Reader would like to use it as well.

**Comment by lancewillett** [comment]
Re-testing this today, it looks fixed. w00t!

<img width="851" alt="screen shot 2017-01-24 at 09 33 50" src="https://cloud.githubusercontent.com/assets/66797/22256513/3e81a4ea-e218-11e6-9f99-7f217c446665.png">
