### ISSUE TITLE
Posts: improve section navigation filters for Drafts, Scheduled, Trash for Jetpack sites

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8492]
For Jetpack sites in Calypso there are several niggles with how section navigation filters for Drafts, Scheduled, Trash appear and behave.
1. Since "Dynamic" filters are not supported, so we should show Scheduled / Draft / Trash, and let you click there. We have "blank slate" states for them, but they do some weird things. We should figure out how to remove those filters if there's nothing to show, and just drop people back to the Published list if they hit those URLs with nothing there.

You can reproduce this by going to a URL like /drafts/ manually for a Jetpack site. WP.com sites redirect gracefully to the Published view.
1. If you don't have any drafts, but some other author on a site does, then the positioning/widths of the columns on Blog Posts/Drafts is weird and changes when you switch the filter. The positioning of the "haven't published yet" message also looks weird, because it's centered under a portion of the UI

![image15](https://cloud.githubusercontent.com/assets/66797/19125327/84d965ec-8aeb-11e6-8b11-6467f7ab56b5.png)

<img width="776" alt="image251" src="https://cloud.githubusercontent.com/assets/66797/19125329/87961cee-8aeb-11e6-897c-8d03cff3826e.png">

Video showing how the layout jumps around:
![jetpack-posts-list](https://cloud.githubusercontent.com/assets/66797/19125243/2b5762da-8aeb-11e6-8aa1-60447c32a847.gif)

Example of an empty post list for a blog with posts but none authored by current, logged-in user:
![empty-when-zero-posts-for-this-author](https://cloud.githubusercontent.com/assets/66797/19125252/32a6eca4-8aeb-11e6-85b1-4acff3092283.png)

#### Context / Source
#8514 dogfooding by @beaulebens

**Comment by lancewillett** [comment]
I think one needs an update just to re-test the same flows again, and maybe related to #2132 also.

Maybe the best improvement would be to bring "Dynamic" filters to Jetpack sites, and that would solve most of the niggles.

**Comment by lancewillett** [comment]
A team on Delta is going to tackle this one for Q4 2017.

**Comment by bsessions85** [comment]
This appears to be resolved. I no longer see the jumping.
