### ISSUE TITLE
Google My Business is now called Google Business Profile

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#84970]
### Quick summary

We have a Google My Business integration, but Google has changed the name to Google Business Profile.

### Steps to reproduce

On a Business or Commerce plan site:

1. Navigate to Tools → Marketing
2. Click the Connections tab
3. Scroll down to the Google My Business section

### What you expected to happen

I expected our feature to reflect the current name: Google Business Profile

### What actually happened

It says "Google My Business"

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by donalirl** [comment]
<img width="912" alt="Screenshot 2023-12-07 at 1 43 12 pm" src="https://github.com/Automattic/wp-calypso/assets/30727666/323903ab-e034-4444-ba8f-0f83d15d264e">

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
![CleanShot 2023-12-08 at 10 11 30@2x](https://github.com/Automattic/wp-calypso/assets/14153300/cedea581-51e9-440b-893b-e160871f76da)

📌 ACTIONS
- Triaged

**Comment by Aurorum** [comment]
PR in #86301. :)
