### ISSUE TITLE
Assembler: remove "Active this theme" screen

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#84996]
# Description
Remove this screen from the LiTS-Assembler flow

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/0ebf9365-d6d7-4567-8f70-2acb412fb79f)

p1701981686652669/1701970821.592539-slack-C048CUFRGFQ
"Yeah, for this, I feel like when the flow is so focused on creating a homepage … that we don’t have to give anyone any warnings about their homepage disappearing / changing." - Ian

@Automattic/lego

**Comment by autumnfjeld** [comment]
We could replace the "Activate this theme" with this screen,
And we could have copy that introduces the theme.
![image](https://github.com/Automattic/wp-calypso/assets/5665959/1a7d3217-3794-4336-be0d-f7fa654adc5f)

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/85410
