### ISSUE TITLE
Domains: Limit width of domain change modal

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#84995]
### Details

The modal can be triggered by navigating to Domains, clicking the three dot menu, selecting Change Site Address.

The default width is a bit too wide here to show a connection to the wordpress.com TLD.
Let's give it [the same width as the Social Connection modal](https://github.com/Automattic/wp-calypso/blob/205ba0cd450757cdd321ddafe61752bbf3f5dc7f/client/my-sites/marketing/connections/account-dialog.scss#L4), 800px. That'll likely avoid line breaks in the confirmation modal in other languages.
 Before | After
--- | ---
![image](https://github.com/Automattic/wp-calypso/assets/1398304/3c4e4f7b-f808-44cd-a6c3-5f6296927041) | <img width="896" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1398304/cf0ebfab-b3a0-4c88-8ad8-8460721c2010">

### Checklist

- [ ] Limit modal(s) to 800px.
- [ ] Add a Cancel Button in the first modal.
- [ ] Change "Change site address" to "Next" in the first modal.
- [ ] Add a check for email confirmed and show an error message + disable Next button if unconfirmed.

### Related

p58i-fXA-p2

**Comment by JuanLucha** [comment]
Hi!

I have been working on this task, and I only have a doubt about the final result. When the user writes the new domain name, there is an availability check. When that finishes, I check for the user's email to be verified if the domain is available. If it's not, then I show this message and disable the `Next` button:
<img width="863" alt="Screenshot 2023-12-11 at 21 05 54" src="https://github.com/Automattic/wp-calypso/assets/3832570/e96feae9-55ca-48f5-a1c0-b24b59141315">

Are the copy and the way the message is shown good?

**Comment by obenland** [comment]
Can we show the notice above the input field and disable the input and the Next button?
Ideally we'd also show a link/button to send a confirmation email from that notice.

**Comment by JuanLucha** [comment]
Sure, we can do that 👍
