### ISSUE TITLE
Button: Trigger blur on click

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#850]
As noticed in #195 and discussed in #514, when you click on buttons, Firefox keeps the `:focus` state active until the user clicks somewhere else. The `:focus` state on buttons have a blue outline for accessibility and keyboard navigation, but once the click is through, the blue outline becomes confusing as usually show progress information on the button as well.

My solution to that problem is to trigger a `blur()` call on click event so that we can get rid of the problem. However, in #514, this is solved only locally; we should call `blur()` on every click on buttons to solve it throughout the app.

Once done, please also remove the call to `blur()` at around `/client/me/purchases/cancel-private-registration/index.jsx#L39`

**Comment by fabianapsimoes** [comment]
cc @MichaelArestad @mikeshelton1503

**Comment by lancewillett** [comment]
Cleaning up older tickets: this one looks like it still needs work.

Code ref: https://github.com/Automattic/wp-calypso/blob/9c57de43cd01c890fea3f2100cae886fb7b28633/client/me/purchases/cancel-private-registration/index.jsx#L48

**Comment by blowery** [comment]
I don't think we should do this. Calling blur removes focus from the button and hands it ... elsewhere. This would make it more difficult for folks who use the keyboard to use the app.

**Comment by umurkontaci** [comment]
@blowery My initial concern was about the visuals but I didn't think about accessibility. You are right, this doesn't feel like a good approach. How about we remove the blue outline when the button is disabled by CSS?

**Comment by blowery** [comment]
Removing Good First until we decide where we want to move with this.

**Comment by hoverduck** [comment]
#bug-scrub

There hasn't been any activity here in ~3 months, so I'm going to go ahead and close it.  If anyone has any thoughts on a solution to this problem, feel free to re-open it for discussion.
