### ISSUE TITLE
Inconsistent synchronisation of purchases to Atomic sites

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#85015]
### Quick summary

Over the last few weeks, we've seen a non-trivial number of issues on Atomic sites where recent purchases haven't been correctly synchronised across to the site data, where that results in various unexpected downstream gotchas or errors. It's not always obvious that this is the cause of the problematic behaviour, so it takes a non-trivial amount of support time to determine the issue and then resolve the underlying cause by manually triggering a re-synchronisation of the user's purchases to their site using our internal tools.

You can see internal discussions around this here:
 * p1701691282676739-slack-C03Q87XT1QF

### Steps to reproduce

We don't have a specific set of steps to reproduce, but it seems to occur more frequently for sites that start as Woo Express trial sites, and then upgrade to a paid Woo Express plan.

### What you expected to happen

We should not end up in a situation where purchases are not visible to Atomic sites.

### What actually happened

The purchases visible to the Atomic site are out of date, and we're thus blocking access to features that the user has paid for.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by daledupreez** [comment]
Noting that we can see the number of manual synchronisation requests via our internal tools by looking at the `store-admin-action/sync-atomic-purchases` MC stat.

**Comment by valterlorran** [comment]
I couldn't figure it out yet what may cause this problem. Following Dale's advice, I added some logs to better understand what's happening: D132095-code

**Comment by valterlorran** [comment]
We have some updates about this problem, and you can read more in detail here:
* p1705323523256779/1701771016.423169-slack-C03Q87XT1QF
* paYKcK-3TA-p2

**Comment by daledupreez** [comment]
For those following along without access to the internal references, the underlying problem is effectively a race condition: when users purchase multiple products (most commonly a domain registration and a plan), when the first product purchase occurs, we queue up a background process to update the purchase data to run 5 seconds later. However, some purchases can take longer than 5 seconds to complete, in which case the background process won't include all the products, only those that are already purchased.

**Comment by daledupreez** [comment]
Earlier today, we deployed D135288-code to production, which should reduce the prevalence of these issues. That specific change handles all purchases that flow through checkout, which includes new purchases and manual renewals. We don't yet have a solution for auto-renewals, but that should be less of an issue for new users.

**Comment by sixhours** [comment]
Since we've made progress toward fixing this and it's less likely to be an issue for new users, I'm closing this as "good enough for now" :)
