### ISSUE TITLE
Problem with More links and VIP sites

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8501]
There's a problem with the More links and VIP sites. I noticed it on these posts: https://wordpress.com/read/feeds/30997

Problem: View a post, scroll down, click a "More in Site" link. Sometimes the resulting page shows just the excerpt. Reload, and you get the whole post.

After discussing in Slack with @aaronyan and @blowery, a solution was proposed: "this is probably the easiest solution: reload the post (and don’t use the ones given by related posts) when a More link is clicked"

So, let's do that.

**Comment by aaronyan** [comment]
^+1. Another way of wording the suggested fix: "set a new property indicating that the post should be reloaded before being shown"

**Comment by fraying** [comment]
Chatted through this with @blowery. My opinion is that this is something that should be fixed before the refreshed fullpost goes out to all users, since the new design brings this problem to the forefront with the new More in Site links.

**Comment by blowery** [comment]
I think this got fixed?

**Comment by fraying** [comment]
Yup!
