### ISSUE TITLE
Fullpost: Inconsistent Naming, VIP site

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8502]
This post ... https://wordpress.com/read/feeds/39292676/posts/1177815786 ... shows only one name in the sidebar: "adammillerglobal"

![screen shot 2016-10-05 at 2 40 47 pm](https://cloud.githubusercontent.com/assets/24388/19132705/b8874fa8-8b09-11e6-8b84-7f145d2a423f.png)

But if you click it to go to the site page ... https://wordpress.com/read/feeds/39292676 ... the site title there is "Global News"

![screen shot 2016-10-05 at 2 41 40 pm](https://cloud.githubusercontent.com/assets/24388/19132732/d8a88d9c-8b09-11e6-82af-f2065c67f802.png)

So, shouldn't the fullpost sidebar be:

adammillerglobal
Global News

?

**Comment by fraying** [comment]
Seems to be a problem with all Global News posts - they're all missing "Global News" as the site title in the sidebar.

**Comment by blowery** [comment]
Need to fix how we do name fallback. Right now I think we prefer the feed title.
