### ISSUE TITLE
Launchpad: Add the possibility of dismissing the Launchpad without completing all the tasks

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#85037]
Discussing with @daledupreez, we talked about the idea of making it possible to dismiss the Launchpad on the Customer's Home without completing all the tasks. But it can also be used in other contexts too.

- [x] Add a flag to the task list definition to allow the user to dismiss the Launchpad without completing all the tasks
- [x] Make the necessary changes on the front end to accept the new flag

We should also explore how we are going to display the "Dismiss" button alongside the progress ring. We may need @nuriapenya to chime on this.

**Comment by valterlorran** [comment]
I think we should consider allowing the dismissal of an incomplete task to users who have already completed the tasks for other sites.

**Comment by daledupreez** [comment]
In terms of additional context, a key driver for this is for migrating the site setup checklist, where we used to have the ability to skip/hide the list of actions, which is especially important when a user has gotten to My Home and their site is mostly ready.

We already implemented the ability to hide a launchpad after all tasks have been completed, so this should mostly be about making it possible to have that behaviour enabled in additional situations/contexts.

**Comment by nuriapenya** [comment]
It would be great to reuse the same functionality we have in other cards in My Home (Dismiss for a day/week/forever) so we allow users to go at their pace:

<img width="361" alt="CleanShot 2023-12-11 at 11 33 24@2x" src="https://github.com/Automattic/wp-calypso/assets/7931304/cc360d0f-51cc-4bdb-8c3c-5bf354aaf08c">

The UI is the challenging part. We need to find a visible way without adding too much complexity and keeping everything else. Maybe we can add a subtitle (already in use in Monetize Launchpad) and have the option there:

<img width="1394" alt="CleanShot 2023-12-11 at 11 50 17@2x" src="https://github.com/Automattic/wp-calypso/assets/7931304/f2fd3f4a-4b9f-427e-bae4-09c14b9f1ceb">

Alternatively, we can reuse the ellipses we have in other cards (e.g. Prompts) and display the same options:

![CleanShot 2023-12-11 at 12 16 01@2x](https://github.com/Automattic/wp-calypso/assets/7931304/f2276e4c-38a7-4fc0-bce5-efaa343a720e)
![CleanShot 2023-12-11 at 12 16 16@2x](https://github.com/Automattic/wp-calypso/assets/7931304/da20e3be-95d2-4947-85d8-343d93db06c2)

Probably the second option is more feasible (no need to add subtitle) although it breaks a bit the layout on top, with the circle.
