### ISSUE TITLE
WP.com Plugins: change "Purchase" to "Upgrade" in call to action

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8506]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plugins/example.wordpress.com
2. Look at buttons that say "Purchase"
#### What I expected

Call to action to be "Upgrade."
#### What happened instead

The upgrade links on the plugin page say “PURCHASE” whereas everywhere else we say “UPGRADE.”
#### Screenshot / Video

![screen shot 2016-10-05 at 15 04 38](https://cloud.githubusercontent.com/assets/66797/19133441/0e872092-8b0d-11e6-8492-062e545c8ce9.png)
#### Context / Source

Reported by @beaulebens in a recent #dogfooding session.

**Comment by drw158** [comment]
reasoning for "Purchase" 

https://github.com/Automattic/wp-calypso/issues/3840#issuecomment-200427107

> I agree. An activate button that leads to buying a plan doesn't seem right. In that case, the button should say "buy" or "purchase" or "plan" so it's reasonably clear what the button will actually lead to.

@designsimply do you think "Upgrade" is misleading, or would you still prefer "Purchase"?

**Comment by drw158** [comment]
solved via #9493
