### ISSUE TITLE
Self-service site reset: update the copy

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#85080]
We've got several suggestions for the copy of this feature. I've updated [the design](https://www.figma.com/file/2d9bv3p940KDHshek8CuEf/Self-service-site-reset?type=design&node-id=1949-10323&mode=design&t=ssQbgiZnEkt8uxgo-11) to reflect the changes but here's a list of the modified strings:

### Card in the General settings page:

Title: Reset your site
Remove all posts, pages, and media to start fresh while keeping your site's address.

### Description of the page

Remove all posts, pages, and media to start fresh while keeping your site's address. Learn more.

### Content of the card

Resetting [URL of the site] will remove all of its content but keep the site and its URL up and running. Keep in mind you'll also lose any modifications you've made to your current theme.

### Input field

Type [URL of the site] below to confirm you're ready to reset the site:

### CTA

Default state: Reset site
Loading state (for simple site): Resetting site

### Help message 

Atomic: Having second thoughts? Don't fret, we'll automatically back up your site content before the reset and you can restore it any time from the [Activity Log](#).
Simple: To keep a copy of your current site, head to the [Export page](#) before starting the reset.

**Comment by mpkelly** [comment]
>Title: Reset your site

@javierarce Did I get this right? I don't think the Figma file was updated for this one. 

<img width="862" alt="Screenshot 2566-12-12 at 14 21 18" src="https://github.com/Automattic/wp-calypso/assets/6851384/4703ff14-5e71-4c94-a740-e2f1c62cd0d8">

**Comment by javierarce** [comment]
Oh, that title was for here: 

![image](https://github.com/Automattic/wp-calypso/assets/4933/a310ecb5-d64b-4627-ab42-9aaa13c81b84)
