### ISSUE TITLE
Self-service site reset: implement notification email

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#85082]
Here's [the design](https://www.figma.com/file/2d9bv3p940KDHshek8CuEf/Self-service-site-reset?type=design&node-id=2081-31346&mode=design&t=ssQbgiZnEkt8uxgo-11) for the notification email we send the owner of the site and the person that initiated the reset:

![image](https://github.com/Automattic/wp-calypso/assets/4933/0d6f1c44-5df8-4790-9640-7a36ef8a080f)

- Subject line: We’ve finished resetting your site
- Preheader: Ready to start fresh?
- Title: All set! Your site has been successfully reset
- Content: Hi username, [Name of the Site] has been successfully reset and its content removed. Head to your usual address to take a look and start building your new site.
- CTA: Visit your site
- Help: Got questions? Contact our [support team](#) and they’ll be happy to help.

**Comment by vykes-mac** [comment]
D131763-code
