### ISSUE TITLE
MailPoet: Login mobile navigation links overlapping

### ISSUE THREAD

**Issue by agrullon95** [Automattic/wp-calypso#85089]
#### Steps to reproduce

1. Starting at URL: wordpress.com/log-in?client_id=79002&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Faccount.mailpoet.com%252Flogin%252Fwpcom%252Fcallback%26scope%3Dauth%26client_id%3D79002
2. Change browser size to mobile viewport
3. Visually examine header navigation bar

#### What I expected

The links should have sufficient space in between them or a dropdown menu should be available for selecting links.

#### What happened instead

Header navigation links are overlapping.

#### Browser / OS version

Chrome, Safari, Firefox

#### Screenshot / Video

<img width="479" alt="CleanShot 2023-12-11 at 09 39 15@2x" src="https://github.com/Automattic/wp-calypso/assets/10482592/3a372a93-153f-4b92-81bf-5494e3f8948c">

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
Replicated

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
* Go to an incognito browser OR mobile device (tested on Asus Android phone)
* Starting at URL: wordpress.com/log-in?client_id=79002&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Faccount.mailpoet.com%252Flogin%252Fwpcom%252Fcallback%26scope%3Dauth%26client_id%3D79002
* Change browser size to mobile viewport
* Visually examine header navigation bar

Asus Android Phone

![Image](https://github.com/Automattic/wp-calypso/assets/13706336/7fcddd8d-be78-4b9b-9299-8d878564a120)


## 📌 ACTIONS ##
Triaged

**Comment by lsl** [comment]
Introduced in https://github.com/Automattic/wp-calypso/pull/79443

Done means:
- [ ] Logged out masterbar only shows reader links on /read routes
- [ ] Logged out masterbar no longer shows empty title block next to wp.com on the left

Logged out https://wordpress.com/read:

![Screenshot 2024-08-05 at 14-28-30 Browse popular blogs   read articles ‹ Reader — WordPress com](https://github.com/user-attachments/assets/2570c8a0-5d18-46c9-8753-af66eea87760)
