### ISSUE TITLE
Plans: The 'Upgrade' button does not work and Checkout does not offer higher level plans 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#85096]
### What

**One year plans:** 
In Upgrades > Plans page https://wordpress.com/plans/  there's an 'Upgrade' button next to the current plan. Clicking 'Upgrade' does not go anywhere. 
Also in Purchases page https://wordpress.com/purchases/ > select the plan to upgrade > then click 'Upgrade' or 'Upgrade Plan' button. Any of those two will direct to the Plans page https://wordpress.com/plans/  with the 'Upgrade' button that does not work. 

Renewing the yearly plan, then going to Checkout will not offer two or three years plan upgrade. 

**Monthly plans:**
In Purchases page https://wordpress.com/purchases/ > select the plan to upgrade > then click 'Upgrade' or 'Upgrade Plan' button. Any of those two will direct to the Plans page https://wordpress.com/plans/  with the 'Manage plan' button that does not work. 

Renewing the monthly plan, then going to Checkout will not offer one, two or three years plan upgrade. 

### Why

A working "Upgrade" button and offers in the Checkout page to upgrade to higher level plans will make it easier for customers to upgrade and will help increase our sales. 

### One year plans:  

Upgrades > Plans page https://wordpress.com/plans/ 

The Upgrade, Upgrade plan button does not work. 

<img width="1517" alt="Screenshot 2023-12-11 at 16 04 00" src="https://github.com/Automattic/wp-calypso/assets/36863633/c2758a47-87b2-4bb0-9d1f-94ebf54c2682">

Purchases page https://wordpress.com/purchases/ 

<img width="1153" alt="Screenshot 2023-12-11 at 16 17 05" src="https://github.com/Automattic/wp-calypso/assets/36863633/795a4df0-d125-4ec0-880d-d10097e1df82">

The Checkout page has no option to upgrade to two or three years plan: 

<img width="1184" alt="Screenshot 2023-12-11 at 16 45 05" src="https://github.com/Automattic/wp-calypso/assets/36863633/db3ae8f6-5ead-4c16-ad56-c91012e8c9c3">

---

### Monthly plans: 

The Manage plan does not work. 

<img width="1243" alt="Screenshot 2023-12-11 at 16 38 37" src="https://github.com/Automattic/wp-calypso/assets/36863633/0fffe2f0-1f6a-4c5d-9dde-f81f8b7eda8e">

The Checkout page has no option to upgrade to one, two or three years plan: 

<img width="1126" alt="Screenshot 2023-12-11 at 16 39 33" src="https://github.com/Automattic/wp-calypso/assets/36863633/fd60f253-ac25-4ba2-961b-8bb353458c4b">

---

Similar report in: [Checkout: Why isn't the sidebar upsell CTA shown for two-year and three-year (and above) plan variants? #84484](https://github.com/Automattic/wp-calypso/issues/84484)

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
Replicated as per OP description. 

## NOTE:## 
This is bug report (the upgrade button does nothing) and there is also a feature requesting here asking for other plans to be offered when someone wants to upgrade. 

## 📌 ACTIONS ##
Triaged

**Comment by nightnei** [comment]
It works ATM:
In Upgrades > Plans page https://wordpress.com/plans/ there's an 'Upgrade' button next to the current plan. Clicking 'Upgrade' does not go anywhere.
![Image](https://github.com/user-attachments/assets/c7fe2a06-0362-419f-8bac-420c36fff6d3)

Both buttons also work and lead to the /plans/ page where Upgrade buttons works correctly too:
Also in Purchases page https://wordpress.com/purchases/ > select the plan to upgrade > then click 'Upgrade' or 'Upgrade Plan' button. Any of those two will direct to the Plans page https://wordpress.com/plans/ with the 'Upgrade' button that does not work.


"Manage plan" also works correctly:
![Image](https://github.com/user-attachments/assets/c2214e50-7108-4a74-adbc-01ffe2c5de8f)

`The Checkout page has no option to upgrade to one, two or three years plan:`
Hm, I didn't get this one - is it expected to have there plan upgrades by years?
I see that we have such options on /plans/ page and IMO it's the right place, and regarding Checkout page - I. think it can just make the page more complicated and distract from payment.
WDYT?

![Image](https://github.com/user-attachments/assets/48b6953a-31a8-4414-a9ba-2f4f48dd220d)

**Comment by kspilarski** [comment]
Hi @nightnei thanks for testing. Upgrade works as expected now. 

I tested it again today and in Upgrades > Plans page https://wordpress.com/plans/ clicking the Upgrade button now works, unlike before.

As for the current plan "Manage plan" button, clicking "Upgrade" or "Upgrade plan" takes you to the plan page to select a higher level plan. 

> `The Checkout page has no option to upgrade to one, two or three years plan:`
Hm, I didn't get this one - is it expected to have there plan upgrades by years?

This is a feature request. Previously, the lower right section in the checkout displays the option to renew the domain together with the plan. Currently in the checkout, if one year plan is selected, the lower right section has now the option to upgrade to a higher level plan which wasn't the case back in December 2023. 

This is sorted out as well. Thank you!

**Comment by davemart-in** [comment]
Closing out this issue as it appears to be sorted now.
