### ISSUE TITLE
Plans: Manage Payment" button styles looks broken

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8509]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/plans/my-plan/example.wordpress.com with a site that has a paid plan.
2. View the My Plan page.
#### What I expected

Set to Auto Renew on (date) "MANAGE PAYMENT" — button to be blue and laid out correctly, matching other buttons on the same page.
#### What happened instead

"MANAGE PAYMENT" isn't text wrapped correctly, and background color is white
#### Browser / OS version

Chrome on Mac OS X
#### Screenshot / Video

<img width="497" alt="screen shot 2016-10-05 at 15 26 35" src="https://cloud.githubusercontent.com/assets/66797/19133997/1e8cdaec-8b10-11e6-8358-5dbcbb8fa8bf.png">

#### Context / Source

Via a recent #dogfooding session from @beaulebens

**Comment by beaulebens** [comment]
This appears to have been fixed somewhere along the line.
