### ISSUE TITLE
Purchases: Replace `PurchasesMixin` with a set of functions

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#851]
Originally reported by @drewblaisdell 

A couple reasons:

- `PurchasesMixin` doesn't need to access any component lifecycle methods.
- Though they are still supported, there has been talk about deprecating mixins in future versions of React.

@rads recommended (11959-gh-calypso-pre-oss) creating a new module with set of functions that receive `this.props` as an argument.

**Comment by gziolo** [comment]
@drewblaisdell this is done, isn't it?

**Comment by stephanethomas** [comment]
This was fixed in https://github.com/Automattic/wp-calypso/pull/586.
