### ISSUE TITLE
Update "Customize your site menu" task for block themes

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#85107]
### Quick summary

Clicking the _Add to menu_ button from the _Customize your site menu_ task takes you to the Customizer, but there's nothing menu-related there for block themes.

### Steps to reproduce

1. On a new site, ensure a block theme is enabled (or just go through the [Sensei onboarding flow](https://wordpress.com/setup/sensei/senseiSetup)).
2. Click the _Customize your site menu_ task from the launchpad.
3. Notice that it goes to the Customizer, where there are no menu options.

### What you expected to happen

To be taken to `wp-admin/site-editor.php?path=%2Fnavigation`, not the Customizer.

### What actually happened

I'm taken to the Customizer where there's nothing for me to do. This may make sense for classic themes, which have a _Menus_ option, but not for block themes.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Tested on Atomic sites only.

**Comment by rickmgithub** [comment]
##Message to author##
Thanks so much for the report @donnapep  Can you tell us more about the flow you are going through to reach that point? 
I tried creating new sites but couldn't find the flow to get to it for triaging? 
Can you describe the process to replicate this in some more steps?

**Comment by donnapep** [comment]
@rickmgithub Thanks for checking. I've already triaged this one so I'm not sure it needs to be done again. I guess I should have moved it to a different column of the board? (I'm new to Dotcom division. 🙂 )

For more context though, this is part of the [Sensei onboarding flow](https://wordpress.com/setup/sensei/senseiSetup). This will install Course, which is a block theme. Hope that helps!
