### ISSUE TITLE
Newsletter: old confirm template instead of new one

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#85103]
### Steps to reproduce

1. Jetpack locally running
2. Subscribe to site, confirm subscription.
3. Close tab to forget the user.
4. In a post with subscription wall, choose "already subscribed" to login

<img width="736" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/eff1abac-1685-4b8d-a8ed-07e5179823ae">

6. Get magic login link form — it's without site's name and logo

   <img width="1212" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/3228d363-10ad-4ebf-91c9-c0ecaa8e9577">

8. Get the old login email, also without site's name:

    ![image](https://github.com/Automattic/wp-calypso/assets/87168/eca727bb-3191-4be9-95a3-f225181d3df1)

### What you expected to happen

New email template.

### What actually happened

Old email template

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by rickmgithub** [comment]
Hello @simison 
Can I check is this for the Paid Content Block?
Also, are you talking about a locally hosted WordPress rather than a .org site?

**Comment by simison** [comment]
@rickmgithub 

> Can I check is this for the Paid Content Block?

For post paywalls, either by turning post "paid" or "subscribers only", or using "paywall" block.

> Also, are you talking about a locally hosted WordPress rather than a .org site?

I tested with Jetpack running locally, but that's basically ".org site". ;-) Might replicate on .com simple site too but didn't test.

**Comment by maciejpilarski** [comment]
Hey @simison 👋 

I have tested the workflow on a .com simple site and was not able replicate the issue. The email template I've received was already the new one:

![Markup on 2023-12-18 at 21:31:03](https://github.com/Automattic/wp-calypso/assets/9025643/b4d9b889-99e0-42ba-97c5-4ce435a4eed9)

**Comment by maciejpilarski** [comment]
At the same time, I've just noticed that the "Congratulations on your first post!" email is using the old template:
![Markup on 2023-12-18 at 21:35:04](https://github.com/Automattic/wp-calypso/assets/9025643/55b91d81-4a71-4ffe-930e-9a2b7459a287)

**Comment by simison** [comment]
Thanks, noted in https://github.com/Automattic/wp-calypso/issues/85460

**Comment by simison** [comment]
This is sorted out already.
