### ISSUE TITLE
Adjust margins and fonts on Jetpack SSO screen

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#85111]
Steps to reproduce:

1. Go to `wordpress.com/start` in an incognito session.
2. Use a fresh email to create a new account.
3. Complete the Commerce plan purchase flow.
4. At the end of the flow navigate to `/home`.
5. You'll see the following screen.

![image](https://github.com/Automattic/wp-calypso/assets/1182160/0c1d6606-1a5e-4c88-920c-2f8c855e6e73)

Done is:

- The styling of the "Resend Email` notice should match the surrounding elements.

Quoting from the walkthrough post:

> The Jetpack SSO screen needs some tweaking of margins and fonts. Can we coordinate this with Jetpack or address it ourselves? Starting at about 54 after.

The recording is available here p58i-g5m-p2 at 54 minutes.

**Comment by mpkelly** [comment]
I started this. To me, it's not clear exactly what needs to be changed, and it seems like the best thing would be to not see this screen right after sign-up. I have proposed some changes p58i-g5m-p2#comment-60744 and asked for clarification.

**Comment by vindl** [comment]
> To me, it's not clear exactly what needs to be changed, and it seems like the best thing would be to not see this screen right after sign-up.

I agree with this. If we circumvent this screen showing right after signup, are there ways they could run into it in the future? E.g. if they don't verify their email in time and need to SSO again.
