### ISSUE TITLE
Error on Jetpack SSO screen for unverified email in Commerce flow

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#85110]
Steps to reproduce:

1. Go to `wordpress.com/start` in an incognito session.
2. Use a fresh email to create a new account.
3. Complete the Commerce plan purchase flow.
4. At the end of the flow, navigate to `/home`.
5. You'll see the following screen.

![image](https://github.com/Automattic/wp-calypso/assets/1182160/fc9df7b3-1754-4b8e-be09-4471ac850e90)

Done is:

- Investigate potential ways to circumvent this problem. Ideally, we shouldn't show people this screen just after they've finished onboarding. We could try to allow SSO for this user for some period of time after creating a site.

Quoting from the post:

> Going to “Home” for the commerce flow shows an error on the Jetpack SSO screen about the user not having their email verified. Can we just allow SSO for this user for some period after creating their site? Starting at about 54 after.

You can check out the walkthrough recording here: p58i-g5m-p2 at 54 minutes.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
1. Accessed wordpress.com/start
2. Used a brand new email
3. Created a site and selected Entrepreneur
4. Paid for the plan in credits
5. After the payment, I was shown this screen:
![v-IIeSNzLU.png](https://github.com/Automattic/wp-calypso/assets/14153300/192cb063-0206-4b14-85a3-ccbedb4948cd)
6. Clicked on "Resend email"
7. Clicked on "My Site" to exit the flow
8. After another loading screen, I was shown:

![CleanShot 2023-12-29 at 17 44 32@2x](https://github.com/Automattic/wp-calypso/assets/14153300/b78bd01e-4465-4f08-a85e-4cb807c0ebe6)


📌 ACTIONS
- Triaged

**Comment by p-jackson** [comment]
There's discussion about a possible solution here p1HpG7-qll-p2

**Comment by p-jackson** [comment]
The proposed solution was deployed in D133828-code
