### ISSUE TITLE
Stats: Send emails requiring upgrades

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#85115]
p1HpG7-pE5-p2#comment-67435

![image](https://github.com/Automattic/wp-calypso/assets/1425433/2f0d3926-f18f-409b-a573-941423fa542e)

```[tasklist]
### Tasks
- [x] Add email notification templates and the observer to receive events from asybc jobs: D134150-code
- [x] cron job to send out emails D134322-code
```

**Comment by dognose24** [comment]
A similar mechanism was tackled for the Jetpack Search email notification: D89091-code.

**Comment by dognose24** [comment]
The Diff to tackle sending the email notification is here: D134150-code.

**Comment by kangzj** [comment]
The emailing job is scheduled to run daily and running.
