### ISSUE TITLE
Assembler: update zoom control

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85123]
# Description
This work is for further iteration on the Assembler zoom control.

See P2 Assembler: Allow to zoom out the preview  p9Jlb4-9vy-p2

**CURRENT**

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/df2f937e-a18b-4e6f-9f15-c43d0f67021d)

**PROPOSED NEW DESIGN**
Latest slack instructions from Matias and Lucas:  p1703163840417879/1702589666.260559-slack-CRWCHQGUB
Figma  Tv3pYqA3EcRfiXC31IxrXE-fi-2469:33385#653418774
Lucas says he needs to decide on icon, but dev work can start and icon could be suggested by dev.  p1703164324378109/1702589666.260559-slack-CRWCHQGUB

<img width="1217" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/cefa4ac4-a1c4-4f7c-9541-31ae8006aaca">

https://github.com/Automattic/wp-calypso/assets/5665959/1186ca97-344c-4ded-9886-f1744c3a81e4

## Prior work 
https://github.com/Automattic/wp-calypso/pull/83034

@Automattic/lego

**Comment by richtabor** [comment]
I'm curious if we even need this to be honest. 

Why not set it to "50%" effectively (with no control available), so you can see the page as you're dropping in patterns and designing? I suspect this would help with the notion that folks expect to edit content as well. If the view is not 100%, the content does not seem as editable. 

Forcing the scale would remove the need to fix https://github.com/Automattic/wp-calypso/issues/85317

Like this: 

![CleanShot 2023-12-14 at 14 49 32](https://github.com/Automattic/wp-calypso/assets/1813435/a4d1f36e-09a2-4882-9149-ce8fd5a7f302)

**Comment by autumnfjeld** [comment]
FYI: https://github.com/Automattic/wp-calypso/issues/85317

**Comment by autumnfjeld** [comment]
cc: @lucasmendes-design  see Rich's comments

**Comment by lucasmendes-design** [comment]
Now I understood what he meant. However, I still believe that users will not see a good portion of their sites on small screens. I may be wrong, but I need to see how this will be implemented and test it. 

Wix has this feature, and if you check on small screens, if you add two/three patterns, the site will be hidden.

**Comment by richtabor** [comment]
You'd still be able to scroll fine, and with https://github.com/Automattic/wp-calypso/issues/85319 implemented, you'd always see the latest patterns viewed.

**Comment by taipeicoder** [comment]
Seems that this is not quite dev-ready. @autumnfjeld should we move this to the Backlog or Up. Next?

**Comment by lucasmendes-design** [comment]
> you'd still be able to scroll fine

Sure, but you will lose some details from the patterns, and we also have patterns with short heights, for example. Showing 100% is useful for many cases.

**Comment by arthur791004** [comment]
FYI: Here is the metric, `calypso_signup_pattern_assembler_large_preview_zoom_out_scale_change`, for how people scale the large preview

![image](https://github.com/Automattic/wp-calypso/assets/13596067/defea6d2-145b-459e-a2c7-18d2ef11cf28)

**Comment by autumnfjeld** [comment]
@Automattic/lego  I'm confirming that we are going with the design as stated in the issue description.  We can continue discussions in early 2024 as needed, but the design here p9Jlb4-9vy-p2 is approved by Pablo & Lucas. We are going with version 2.

EDIT on 22 Dec: change of plans. See latest comments.

**Comment by autumnfjeld** [comment]
@Automattic/lego  I've updated the issue description due to this slack conversation, p1703165039233399/1702589666.260559-slack-CRWCHQGUB  with Matias & Lucas.   We are going with Version 1 from p9Jlb4-9vy-p2

**Comment by taipeicoder** [comment]
Closing via #85787. Recording for reference:

https://github.com/Automattic/wp-calypso/assets/797888/8812e7c6-cb75-4c49-88a0-f5284954d61e
