### ISSUE TITLE
Assembler: remove survey2 banner

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85125]
# Description

We can take the survey banner down. Next @lucasmendes-design  will help with synthesizing the results. 

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/300ac6cc-ca42-43b9-b2e9-ca6c96c2d532)

**Comment by lucasmendes-design** [comment]
:) 

![image](https://github.com/Automattic/wp-calypso/assets/98343583/4ad9bd5e-d24d-4486-8741-bdb3b3569a5b)
