### ISSUE TITLE
Stats: Support upgrade notices from notices API

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#85122]
- [x] I think we could postpone the upgrade notice for a week before it show up again.
https://github.com/Automattic/wp-calypso/pull/85494
- [x] If site exceed the limit for 3 continuous months, we postpone it for 3(?) days.

We could adjust the numbers if needed.

**Comment by dognose24** [comment]
> I think we could postpone the upgrade notice for a week before it show up again.

Do you mean if users close the tier upgrade notice banner, we won't show it again in a week even though they have reached the limit?

> If site exceed the limit for 3 continuous months, we postpone it for 3(?) days.

The number sounds great to me.

**Comment by kangzj** [comment]
>Do you mean if users close the tier upgrade notice banner, we won't show it again in a week even though they have reached the limit?

Yes otherwise the notice come back right away will definitely annoy users I imagine. We'll need:

**Comment by dognose24** [comment]
> If site exceed the limit for 3 continuous months, we postpone it for 3(?) days.

After publishing Tiered Billing, let's see users' feedback to determine the numbers for postponed days.
