### ISSUE TITLE
Editor: when setting Featured Image, allow double clicking to select, apply with no confirmation needed

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8512]
To speed up the steps to set a featured image for a post or page — don't make authors click the image in the Media library and then also click "Set Featured Image" button. Just allow double-clicking it to set the image (and close the Media selection).
#### Context

Feedback from a recent #dogfooding session by @beaulebens 

> Should be able to double-click to set a Featured Image when browsing for one. I'm selecting a single media item, so if I double-click, it should select, then confirm, and immediately close media/apply.

**Comment by lancewillett** [comment]
As a note, w've improved Featured Image behavior a lot recently, including enabling drag-and-drop. See "Add images in a snap" examples at https://en.blog.wordpress.com/2017/06/29/five-tricks/

**Comment by alisterscott** [comment]
This is still the case of requiring the extra click - although as pointed out drag and drop can now be used

![featured image](https://user-images.githubusercontent.com/128826/36134072-30f8a9a0-10ce-11e8-871f-1dad23b6b9aa.gif)

#bug-scrub #pre-gutenburg-bug-purge
