### ISSUE TITLE
Stats: Some parts of the background are light grey and some are white

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#85121]
p1698319241541159-slack-C9EJ7KSGH

![Image](https://github.com/Automattic/wp-calypso/assets/1425433/a611789f-4eee-4158-9778-74a998a6ea60)

cc @keoshi

**Comment by dognose24** [comment]
After catching up on the original issue for a while, the background of the [page header](https://github.com/Automattic/wp-calypso/pull/83537) has been fixed to color `white`, which would be shared with existing Stats pages. So, we don't have any mismatched background color issues to fix.

However, I found the `Plan Usage` section needs a solid background, which [this PR](https://github.com/Automattic/wp-calypso/pull/87275) will fix.
