### ISSUE TITLE
Assembler CTA - Remove periods on the copy in the numbered list

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#85143]
## What
Remove periods on copy in the list items.

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/ca335470-3731-477c-9e2e-f145e69d685d)

@matt-west what are your thoughts on removing these periods? 

## Why

Because they are unnecessary in bulleted lists as they are single and short sentences and the design looks cleaner without them.

References: 
- https://m3.material.io/foundations/content-design/style-guide/grammar-and-punctuation
- https://www.linkedin.com/pulse/should-bullet-lists-end-period-manali-anaje/

## How
Removing them from https://github.com/Automattic/wp-calypso/blob/204f80428ce71f8198883a926a0f042b3279dff7/packages/design-picker/src/components/pattern-assembler-cta/index.tsx#L31

**Comment by matt-west** [comment]
We should include the periods in this case as the items are complete sentences.

> Use periods at the end of list items that consist of complete sentences.

PCYsg-5n-p2

**Comment by autumnfjeld** [comment]
PCYsg-5n-p2
![image](https://github.com/Automattic/wp-calypso/assets/5665959/d51d4eab-21ad-466e-ba6a-3155d09e6e3c)

https://www.grammarly.com/blog/bullet-points/

Standard english grammar rules:
<img width="728" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/27f57232-a70d-4323-8f62-d727cb279024">
