### ISSUE TITLE
Subscriber Stats: subscriber count is inconsistent

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#85140]
As you'll see below, there are 89 free subscribers. Or 88, depending on the section you check.

Seems related to https://github.com/Automattic/wp-calypso/issues/80610, although in that case it was paid subscribers.

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/5ef0e14b-8b2b-4073-b508-0a2f1202cef7)

**Comment by kriskarkoski** [comment]
I am unsure if it's the same root cause, but in 7567999-zd-a8c their paid subscriber count is inaccurate. If this should be a separate issue let me know!

**Comment by dognose24** [comment]
@crisbusquets @kriskarkoski Since #86762 and D135598-code have been deployed, the discrepancies should be addressed. Please help check the reported blog and let me know if something is weird. 🙏🏼
