### ISSUE TITLE
Reader: The same posts show up for "Recent" and "Popular"

### ISSUE THREAD

**Issue by caitlindawn** [Automattic/wp-calypso#85142]
### Quick summary

When sorting by tags in the Reader, only popular posts are viewable, even when clicking "Recent".
Example: https://wordpress.com/tag/lens-artist?sort=date

### Steps to reproduce

1. From the dashboard, go to Reader.
2. Select any tag.
3. Switch from "Recent" posts to "Popular" posts (or vice versa).

### What you expected to happen

Recent posts should appear when clicking the "Recent" button.

### What actually happened

The same posts are showing for both filters.

<img width="1438" alt="image" src="https://github.com/Automattic/wp-calypso/assets/15062795/c1f04f71-08e0-45a0-b93f-fff0847b7907">
<img width="1438" alt="image" src="https://github.com/Automattic/wp-calypso/assets/15062795/0cb25589-bcf6-4bbb-b6f8-cd70a5865014">

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by caitlindawn** [comment]
Encountered in 7429763-zen

**Comment by caitlindawn** [comment]
Encountered in 7434809-zen

**Comment by sophiegyo** [comment]
Report in the forums: https://wordpress.com/forums/topic/reader-tags-3/?view=all

**Comment by sophiegyo** [comment]
Another report in the forums: https://wordpress.com/forums/topic/reader-tags-not-sorting/?view=all

**Comment by andreabadgley** [comment]
- [x] Encountered in 7431638-zen

**Comment by supernovia** [comment]
This was solved! p1702423782305779/1702420951.390399-slack-C03NLNTPZ2T
https://github.com/Automattic/wp-calypso/pull/85176/

I'll follow up on the forums reports & ping a PA for the others.
