### ISSUE TITLE
Reader Stream Refresh: add card with excerpt only

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#8517]
For cards without usable images or video, present a text-only card that displays the title and excerpt only:

![card-example-text](https://cloud.githubusercontent.com/assets/17325/19135547/cf7836f6-8bc1-11e6-9ea3-da1801b774cc.jpg)

For the cards at all sizes, see https://cloudup.com/c-DVwphUzIi.

- [x] Build HTML/CSS (@jancavan)
- [x] Integrate with real post data

**Comment by blowery** [comment]
Isn't this the same as #8515? I don't think we'll have two separate cards for these two cases.

**Comment by bluefuton** [comment]
> Isn't this the same as #8515? I don't think we'll have two separate cards for these two cases.

@blowery yep, agreed, it should probably be the same component. Just wanted to capture what it'd look like without an image (the PR that implements it can just close out both issues).

**Comment by jancavan** [comment]
Also addressed in: https://github.com/Automattic/wp-calypso/pull/8463
