### ISSUE TITLE
Like widget: "Cannot read properties of null" error when liking a post

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#85173]
Context: p1702412477740719-slack-C02TCEHP3HA

**Comment by ivan-ottinger** [comment]
Merged and deployed to production: D131787-code.

**Comment by daria2303** [comment]
Hi @phcp, @ivan-ottinger :) 

We have a user who has an issue on their site that sounds like this one. 

1) Head to this post https://href.li/?https://poeziipentrusufletulmeu.com/2024/02/14/povesti-neincheiate-alexandrina-iurcu-balan/). Or any post that has one or zero likes.
2) Try to “like” the post and you can’t.
3) Then head to a post with lots of likes https://href.li/?https://poeziipentrusufletulmeu.com/2024/02/13/mircea-rustiuc-pictura-32/
Try to “like” it and you can.

* Site is Creator but not AT
* This site does have 11000+ posts
* Theme is not out of date and it’s ours – Independent Publisher 2
* Tried a similar setup with the same theme on my account (but with only 3 posts) I can like on everything
* When you try to click like you get the following browser console error

```
Uncaught TypeError: Cannot read properties of null (reading ‘textContent’)
at Object.doLike (_static/??/wp-content/js/postmessage.js,/wp-content/js/tannin/compat.min.js,/wp-content/js/wpcom-proxy-request.js,/wp-content/js/likes-rest-nojquery.js?m=202402081217:1926:35)
at _static/??/wp-content/js/postmessage.js,/wp-content/js/tannin/compat.min.js,/wp-content/js/wpcom-proxy-request.js,/wp-content/js/likes-rest-nojquery.js?m=202402081217:1783:13
at Array.forEach ()
at Object.doLikeMultiple (_static/??/wp-content/js/postmessage.js,/wp-content/js/tannin/compat.min.js,/wp-content/js/wpcom-proxy-request.js,/wp-content/js/likes-rest-nojquery.js?m=202402081217:1781:11)
at _static/??/wp-content/js/postmessage.js,/wp-content/js/tannin/compat.min.js,/wp-content/js/wpcom-proxy-request.js,/wp-content/js/likes-rest-nojquery.js?m=202402081217:2630:13
```
* 7738261-zd-a8c

Do you think it can be related?

**Comment by phcp** [comment]
@daria2303 Thanks for the ping! I did some investigation, and it seems more related to the Romanian translation (or at least it's easier to reproduce in this language) and the approach we use to retrieve the previous count. I created an issue https://github.com/Automattic/wp-calypso/issues/88210, and I'll be working on it on the next days.
