### ISSUE TITLE
Skip Plans step in Sensei onboarding flow if user is coming from SenseiLMS.com

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#85170]
### What

Hide the `senseiPlan` step when a user enters the Sensei onboarding flow from the [SenseiLMS.com pricing page](https://senseilms.com/pricing/). When checking out, a one year Sensei Pro subscription should be part of their order.

### Why

When selecting the Sensei Bundle option from https://senseilms.com/pricing/, the user has already chosen an annual subscription plan, so there's no need to select a plan a second time.

**Comment by obenland** [comment]
Looked into this yesterday and I think it'll be a bit more complicated than I envisioned.

The senseiPlan step combines plan selection and site creation, so we can't just skip the step in the flow definition, which would have been nice.

I do wonder if it would make sense to create the site earlier in the process—maybe after the domain step—and in the background, so it doesn't block other steps and we can reduce wait time and a loading screen. None of the things [createAndConfigureSite](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/sensei-plan/create-sensei-site.ts#L66C8-L66C30) does is dependent on user input.

**Comment by renatho** [comment]
When we implement it, we need to update this tooltip from senseilms.com in parallel to not mention about monthly option.

<img width="274" alt="Screenshot 2023-12-20 at 18 06 18" src="https://github.com/Automattic/wp-calypso/assets/876340/ddcf9df9-dad9-4411-9c57-e081448320c4">

And I wonder if it would be worth having another link somewhere for the monthly option. 🤔
