### ISSUE TITLE
Improve wording in paid plan required modal

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#85194]
> Can we find a way to word body text in a way that we don’t need to begin a sentence with “And”?

![Image](https://github.com/Automattic/wp-calypso/assets/528287/1dcb063a-e68d-46de-9527-d38879c41634)

**Comment by TimBroddin** [comment]
@obenland @michaelpick how about just dropping the And? 

> "Customs domains are only available with a paid plan. They are free for the first year with an annual paid plan."

**Comment by obenland** [comment]
Maybe 
> Custom domains are only available with a paid plan. They are free for the first year with annual billing.

@Automattic/editorial What would be your take on it?

**Comment by michaelpick** [comment]
Hey, sorry for the slow reply, I'm on support rotation at the moment.

> "Customs domains are only available with a paid plan. They are free for the first year with an annual paid plan."

This could work!

A few alternatives that might help tease out the specifics of 'they are free' a little more, while more clearly signposting the required action:

> Custom domains are only available with a paid plan. Sign up for any annual plan and get a free year of domain registration.

> Custom domains are only available with paid plans. Sign up to any annual plan, and your domain will be free for the first year.

> You'll need a paid plan to add a custom domain. Sign up for any paid plan and get your first year of domain fees, free.

**Comment by provenself** [comment]
Ha, got pulled away when I was writing this and Pick beat me to it! I had a very similar recommendation:

> Custom domains are only available with a paid plan. Choose annual billing and receive the domain's first year free.

I agree that "annual plan" (rather than "annual billing") is the way to go.

**Comment by michaelpick** [comment]
Choose is _so_ nice <3
