### ISSUE TITLE
VIP: USA Today posts show cruft, omit favorite and More blocks

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8519]
Just testing out various VIP sites in Reader and noticed that all USA Today posts have footer cruft, are missing the favorite action link, and are missing More blocks.

For example: https://wordpress.com/read/feeds/16661605/posts/1177937949

![screen shot 2016-10-05 at 4 56 50 pm](https://cloud.githubusercontent.com/assets/24388/19135870/db9952b2-8b1c-11e6-9f81-b5c7e8f76b18.png)

**Comment by blowery** [comment]
This is a special case shadow site we need to treat like a feed.

**Comment by fraying** [comment]
Rechecking old issues. This one's still an issue (social buttons still appearing in footer).

https://wordpress.com/read/feeds/16661605/posts/1435714211

**Comment by bluefuton** [comment]
Main usatoday.com site doesn't appear to be a VIP site.

Social media icons are added to the feed by Feed Blitz, but aren't in a helpfully-named container to easily strip out.

Closing for now.
