### ISSUE TITLE
Connect "A site refresh box" to site age

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#85195]
> Maybe we can only show this for sites that we don’t consider a new site anymore? ^ months old? For new sites, can we see if there’s a widget like that that covers setting up a site or getting the most out of a new plan on wp.com/learn?

![Image](https://github.com/Automattic/wp-calypso/assets/528287/55953ee1-a139-4f6d-a571-13a62de94056)

**Comment by JuanLucha** [comment]
What about six months old? Is that a reasonable amount of time to suggest a site refresh on the plan bought?
