### ISSUE TITLE
Reader Stream Refresh: add card with a photo gallery

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#8520]
For posts with several usable photos, add a new photo gallery card type:

![card-example-gallery](https://cloud.githubusercontent.com/assets/17325/19135879/8d5adfd2-8bc4-11e6-89c9-e4d0276cfe85.jpg)

For the cards at all sizes, see https://cloudup.com/c-DVwphUzIi.
- [ ] Build HTML/CSS (@jancavan)
- [ ] Integrate with real post data

**Comment by bluefuton** [comment]
Notes from @fraying:

> A note on this card: We currently add a special “gallery strip” to the bottoms of cards like this now. Instead of showing that, I’m suggesting this, where the first X photos all appear in a line (“X” being however many fit horizontally).

> Why this is better: The photos are bigger, so you can see what they’re of. We’re avoiding using the word “gallery” in the UI because it was confusing (a “gallery” in Reader is not a “Gallery” in the post). We’re also avoiding the gallery interface altogether (where you’d enter a special view that showed just images), because it’s confusing, it’s yet another state we have to explain, and it shows the photos outside of the context the author intended.

**Comment by fraying** [comment]
Another note: Not sure how we're making these photo areas (flexbox?) but I was figuring we'd require at least 4 images to trigger this state. So we'd show the first 4 in the post (or, if there's a featured image, use that first and then the next three from the post), at these widths: 40% 30% 20% 10%. (That doesn't exactly match the image above - I had a different thing in mind when I did that.)

**Comment by bluefuton** [comment]
@fraying just to confirm, clicking on the photos in the gallery won't do anything special - it'll just open full post view?

**Comment by fraying** [comment]
Yup!
