### ISSUE TITLE
Theme Showcase: My themes tab displays only the active theme

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#85207]
### Quick summary

The Theme Showcase > My themes tab displays only the current active theme, even though the site has other themes present on the Atomic site.

### Steps to reproduce

1. Go to an Atomic site
2. Go to https://wordpress.com/themes/my-themes/your-site
3. Do a hard refresh on the page
4. Notice that the page displays only the active theme
5. Click on the Recommended and click again on my themes tab
6. Notice that this time we display all the themes present on the site

### What you expected to happen

The My themes should display all the themes present on the site on hard refresh.

### What actually happened

Only only the active theme is displayed

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by rcrdortiz** [comment]
Changes are now live.
