### ISSUE TITLE
Self-service site reset: display a message after the reset is finished

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#85212]
When the user finishes resetting their site, we display a notice but the content of the card doesn't change. This could lead the user to believe nothing has been done. I suggest we display a message in addition to the notice.

Here's what this flow would look like:

![image](https://github.com/Automattic/wp-calypso/assets/4933/d5fd9a18-212e-4d69-937b-5c8e5f9084d7)

The message we could display on the card would be:

`**[url of the site]** has been successfully reset and its content removed. Head to My Home to start building your new site.`

2d9bv3p940KDHshek8CuEf-fi-800_14498

**Comment by mpkelly** [comment]
@javierarce I added a notice after realising it felt a bit weird to end with no feedback. I used the same text that we use for Simple sites when they reset:

![Image](https://github.com/Automattic/wp-calypso/assets/6851384/fc90301d-7f67-46fb-81e5-e4519ea2b15a)

**Comment by javierarce** [comment]
Great, I think the notice is important. If it's not too late to make this change, I'd say "Your site has been successfully reset."

**Comment by mpkelly** [comment]
@javierarce that's been done. https://github.com/Automattic/wp-calypso/pull/85406
