### ISSUE TITLE
Assembler Performance: Use cache when requesting rendered patterns to Block Renderer API

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#85214]
## What
Use cache when requesting rendered patterns to Block Renderer API.

## Why
To improve the rendering performance.

## How
- Option 1: Using `\A8C\Lib\Patterns\get_cached_patterns( $query, $site_id, $locale )` rather than `\A8C\Lib\Patterns\get_patterns( $pattern_ids )` in `get_rendered_patterns`.
  - Will require to get the source site ID from the first pattern for the cache key
- Option 2: Create a new cache with a different key using `$pattern_ids` as a key
- Option 3 (my favorite): An alternative to adding a cache to the Pattern renderer endpoint is to receive the pattern HTML directly as a param because the UI already has fetched all the pattern attributes from the PTK API. We will just have to check what other pattern attributes are required for the pattern transformer. 
  - See fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Soybpx%2Qeraqrere%2Soybpx%2Qeraqrere%2Qcnggreaf.cuc%3Se%3Q039r8427%2368-og
  - See fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Scnggreaf%2Scnggrea%2Qgenafsbezre.cuc-og 
 
In any case, let's skip this cache for automaticcians

cc: @Automattic/lego

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
