### ISSUE TITLE
Reader Stream Refresh: add video card

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#8521]
For posts with an embedded video, add a new video card type:

![video-card](https://cloud.githubusercontent.com/assets/17325/19136044/bceba9ce-8bc5-11e6-84a1-806fe9ae41f7.png)
- [ ] Build HTML/CSS (@jancavan)
- [ ] Build playback logic
- [ ] Integrate with real post data

**Comment by bluefuton** [comment]
We will only show an image by default, with the video becoming active when it is interacted with.

Notes from @fraying:

>Clicking the image (video thumbnail) would load in the video embed, give it the full column width, and begin playback. So one click would drop out the thumbnail image, load in the embed at full width, set to autoplay=true. Clicking anywhere else would result in the usual behavior.

**Comment by samouri** [comment]
WorkInProgress on this branch: https://github.com/Automattic/wp-calypso/tree/add/reader/refresh-video-card

**Comment by samouri** [comment]
@fraying: What do you think the behavior should be if there is a video embed but it isn't from a source which we know how to get thumbnails from?  Start in the expanded state?

**Comment by fraying** [comment]
Can this issue be closed now?

**Comment by samouri** [comment]
I'd say so!
closing
