### ISSUE TITLE
YIR Landing Page: Hide sections without data

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#85224]
Not all sections have underlying data, so may never be shown, especially those that are specific to Jetpack.

We need to do a check before each section and hide it if there's no data.

**Comment by daledupreez** [comment]
I think we're already doing this for the most part. I am wondering whether we should instead _remove_ UI code where we don't have a way to get the data!

**Comment by markbiek** [comment]
> I think we're already doing this for the most part. I am wondering whether we should instead _remove_ UI code where we don't have a way to get the data!

Ah, I see what you're getting at.

We should definitely remove those blocks that we can't/won't get data for.

**Comment by valterlorran** [comment]
For the investigation that I did, we don't have the following data:
* likes
* shares
* subscribers
* akismet
* malware
* browsing_hours
* words

Can you help me confirm if that's accurate?

**Comment by daledupreez** [comment]
Thanks for digging in, @valterlorran!

There are some updates here that are relevant:
* I believe Akismet data was being folded in yesterday, as @robertsreberski landed D132417-code to collect Akismet data in the crawler
* I am not 100% sure how well the additions in D132417-code for blocked logins and threats align with the malware section, but I think there may be some overlap
* likes and shares are still being worked on in D131947-code

I think we can remove `subscribers`, `browsing_hours`, and `words`.

**Comment by valterlorran** [comment]
I'm tackling this issue on D132754-code

**Comment by valterlorran** [comment]
Can we close this, since I merged D132754-code?

**Comment by daledupreez** [comment]
> Can we close this, since I merged D132754-code?

I think that makes sense.
