### ISSUE TITLE
Reader Stream Refresh: add stream card header component

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#8522]
Common to all of the new post cards in the stream refresh is a post header, containing:
- gravatar
- author name
- site title
- relative post date and time (e.g. "1 hour ago")
- primary tag

Add a new component to render this post header on all types of card.

![post-example](https://cloud.githubusercontent.com/assets/17325/19136252/a18348b6-8bc7-11e6-97cc-6b585d1458c4.jpg)

For the cards at all sizes, see https://cloudup.com/c-DVwphUzIi.

**Comment by fraying** [comment]
Not sure it this is part of the component, but just in case:

There's also the Follow link at the top, right. That should appear wherever post cards appear _except_ on the main following view (because they'd all be "Following").

**Comment by bluefuton** [comment]
Good spot @fraying. It's not part of the component so I've added a separate issue and some notes on when it should be visible: https://github.com/Automattic/wp-calypso/issues/8526

**Comment by bluefuton** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/8701.
