### ISSUE TITLE
YIR Landing Page: Header and footer shows WPCOM branding for Jetpack sites

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#85222]
The current YIR landing page is showing WPCOM branding in the header/footer for all sites. We need to update it to show Jetpack branding for Jetpack sites.

**Comment by valterlorran** [comment]
I'm tackling this issue here: D132470-code

**Comment by valterlorran** [comment]
Closing this, as we deployed D132470-code.
