### ISSUE TITLE
YIR Landing Page: Toggle privacy for report in 2023

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#85227]
As it stands now, all reports are public to everyone. We should have a way for owners to toggle report privacy on or off.

One possible method could be to display a toggle to owners which sets a value in `extra_data` in the `recap_2023` table.

On page load, we could check that privacy value in `extra_data` and return a 404 if it's set and the current viewer isn't an owner.

**Comment by daledupreez** [comment]
For reference, there is an existing mechanism in the code, we mostly need to expose a form in the UI to interact with the existing handling.

WIP is in D132818-code.

**Comment by daledupreez** [comment]
I shipped D132818-code yesterday, so this issue has been addressed.
