### ISSUE TITLE
YIR Landing Page: Display real uptime stats

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#85225]
We're currently displaying placeholder uptime stats. These need to be updated with real data.

An open request for the real stats can be found in p55Cj4-2Nr-p2.

**Comment by daledupreez** [comment]
We should also hide these stats for Jetpack sites.

**Comment by valterlorran** [comment]
I'm hiding the stats with this diff: D132437-code

**Comment by valterlorran** [comment]
Closing this as we merged D132437-code.
