### ISSUE TITLE
Improve newsletter emails: better header & footer

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#85230]
### Current
When someone sends a post via email, we use a standard template with this header:

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/2c9f4bb6-d2bb-468b-9dea-81179a1a1ac7)

### Proposal
We could improve the header by:
* Bringing the site avatar closer to the name
* Adding a direct link to read the post on the web and promoting the app

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/380884da-1adb-4081-ab34-de4177452aae)

### Current
<img width="812" alt="Screenshot 2023-12-19 at 12 28 02" src="https://github.com/Automattic/wp-calypso/assets/25607244/a8de4b31-aadd-478c-b8ed-89b671e5fe71">

### Proposal

The reasoning is to have an email footer that is more oriented toward the subscribers, nudging them to download the Jetpack app and providing easier access to manage their subscriptions. We'll also mention the site name, which currently is only present in the header. 

<img width="813" alt="Screenshot 2023-12-19 at 12 28 16" src="https://github.com/Automattic/wp-calypso/assets/25607244/c46c4835-17d2-4bcc-92ce-91343303a71d">

## Instances
We should change this for:
- [ ] New post
- [ ] New like on a comment

Which are the emails that subscribers receive. The other ones are notifications for site owners.

## Figma
* Here's the Figma file (uwEavMdyNLecNt6Ru3M2Za-fi-3902_12082) with all the instances where we need to change this header (in blue)
* Dev specs (uwEavMdyNLecNt6Ru3M2Za-fi-3955_3478).

**Comment by simison** [comment]
Nice.

@enejb hi! I wonder what magic we could do with that app link? :-)

Would be great if the post would open directly after installing the app.

Same format could work for "new comment" emails, too.

**Comment by simison** [comment]
@crisbusquets thoughts on using term "blog" instead of "online"? More WordPress terminology, and highlights how a blog comes with newsletter, and newsletter comes with blog. (and well, emails are "online" as well)

**Comment by crisbusquets** [comment]
> (and well, emails are "online" as well)

Good point @simison 😆 
My goal was to find a shorter version of the classic `View this email in your browser`. But maybe they're already using the browser, so maybe we can say:
* Open the blog or use the app
* Open in app or blog
* Open in blog or app

None of them sound good to me. What do you think?

**Comment by crisbusquets** [comment]
Btw @simison this design update could allow us to remove this:

<img width="840" alt="Screenshot 2023-12-18 at 17 41 47" src="https://github.com/Automattic/wp-calypso/assets/25607244/c6a6f01f-f702-418d-959e-ed5a65881a24">

**Comment by simison** [comment]
Let's update the footer at the same time, in progress design:

![image](https://github.com/Automattic/wp-calypso/assets/87168/b8125491-44d2-4e6a-8ac6-4425c91d4417)

Thread p1702918521299499-slack-C052XEUUBL4

**Comment by simison** [comment]
@crisbusquets the updated description doesn't have the "unsubscribe" link like [the above design](https://github.com/Automattic/wp-calypso/issues/85230#issuecomment-1862498109).

**Comment by crisbusquets** [comment]
> @crisbusquets the updated description doesn't have the "unsubscribe" link like https://github.com/Automattic/wp-calypso/issues/85230#issuecomment-1862498109.

I didn't include it because we don't have it yet. I wanted to write it as a single sentence, so they understand that if they click "Manage" they can also unsubscribe from there.

Do you think it should be more clear?

**Comment by crisbusquets** [comment]
Updated the footer design to add again the "Trouble clicking?..." section.
Customer feedback: p1704879806749979/1704874789.131699-slack-C0160HSMDQV.

## Initial proposal
 
![image](https://github.com/Automattic/wp-calypso/assets/25607244/69d124e0-0434-4021-83d0-8d42d595047c)


## New proposal

<img width="669" alt="Screenshot 2024-01-10 at 12 32 35" src="https://github.com/Automattic/wp-calypso/assets/25607244/6819a1cc-bb9f-4a7d-bf31-c4a52241d3b0">


Figma: uwEavMdyNLecNt6Ru3M2Za-fi-3902_14380

**Comment by edanzer** [comment]
Header and footer for new post emails have been updated here: 
Header: D133961-code
Footer: D134755-code

I'm going to close this issue, though I will still address the extra issue linked at the bottom
(https://github.com/Automattic/wp-calypso/issues/86338)
