### ISSUE TITLE
Enhancement: Explain what Partner Themes are in the Themes Showcase

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#85247]
### What

Explain what "Partner" themes mean in the showcase so that theme shoppers know the difference between Partner & Premium.

### Why

In the Themes Showcase, it's currently a little hard to tell what "Partner" themes really mean. The tooltip explains their price, and the `Learn more` link at the top opens the help center to the Themes doc, but neither explains the difference between Partner & Premium.

### How

Add a link to the `Partner` sticker tooltip that opens the Partner Themes guide:

![CleanShot 2023-12-13 at 13 51 14@2x](https://github.com/Automattic/wp-calypso/assets/27249804/79785f9d-5ad6-4387-a8b2-49b77cf67090)

Or add a short explanation somewhere to the showcase/partner theme info pages to briefly explain what `Partner` really means.

Also, we could add a section on Partner Themes in the Themes guide, which is what pops up when you click `learn more` at the top of the showcase. Requested that here: https://github.com/Automattic/en.support-docs-content/issues/2228

![CleanShot 2023-12-13 at 13 52 06@2x](https://github.com/Automattic/wp-calypso/assets/27249804/ee6ced15-c5c8-437c-abb5-13615d3a5449)

**Comment by andregardi** [comment]
The screenshot experience is outdated. Now we have two badges. `Subscribe` and `Partner`.
The first badge has a tooltip explaining the prices, while the second doesn't. This opens space for us to explain what a parter theme is on `Partner` badge, with a link to help center for more details.

> [Partner themes](https://wordpress.com/support/themes/partner-themes/) are developed by third-party creators who have made their themes available to purchase and install directly through your WordPress.com dashboard.

![Image](https://github.com/user-attachments/assets/f2eea2db-3fff-4d69-966b-4ac3f27af111)
