### ISSUE TITLE
PDF Embeds Not Working on Classic Themes 

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#85244]
### Quick summary

PDF embeds do not show inline embeds on live sites. It shows in the Editor but not in the preview or published page.

### Steps to reproduce

1. Add a PDF to a simple site using File block.
2. Enable "show inline embed" in block settings 

### What you expected to happen

PDF shows in Editor and Live Site 

### What actually happened

PDF shows only in the Editor and not on the live site. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by kelasante** [comment]
Issue was reported in 7448330-zen

**Comment by ai2n** [comment]
Might impact atomic too. 7467104-zen

**Comment by OmarFPG** [comment]
7469540-zen, since this is a business user, I've suggested a plugin as a temporary workaround.
7463738-zen, Premium plan, no plugin workaround at hand. But the PDF embed shows a link to the file, which is viewable, at least.

**Comment by OmarFPG** [comment]
7473833-zen, another premium user, no plugin workaround.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Chrome for Mac
![CleanShot 2023-12-20 at 11 55 35@2x](https://github.com/Automattic/wp-calypso/assets/14153300/cfba9baa-6cdd-491e-9649-94c6497b9874)

Firefox for Mac

![CleanShot 2023-12-20 at 11 57 16@2x](https://github.com/Automattic/wp-calypso/assets/14153300/8e94a249-6e21-4758-a28a-57639ceb83c0)

Safari for Mac

![CleanShot 2023-12-20 at 11 58 57@2x](https://github.com/Automattic/wp-calypso/assets/14153300/b886d1b4-ee19-4678-9d3d-f4593fa9f856)



📌 ACTIONS
- Triaged
- Requested author feedback
- Closed as could not replicate (please reopen if the issue reoccurs)


📌 Message to Author
@kelasante @OmarFPG I was not able to reproduce, as seen in the screenshots above.

Please collect the browser info from the users you interacted with and reopen the issue as needed.

**Comment by OmarFPG** [comment]
Thanks, @liviopv. I tried adding new PDF embeds, and they're working now; however, I'm not seeing them yet on the customers' sites. I'll ask them to try removing them and adding them again.

**Comment by kelasante** [comment]
Thanks! @liviopv it is still not working on my test site, https://nogymhero.wordpress.com/pdf-test/ (Chrome 120, OS Sonoma)

This is how it looks like in the Editor:
<img width="2748" alt="Markup 2023-12-20 at 17 08 12" src="https://github.com/Automattic/wp-calypso/assets/74204272/0336dc9e-1d73-4617-b6c8-55758a3ae066">

And this is how it looks on live site:

<img width="2114" alt="Markup 2023-12-20 at 17 10 58" src="https://github.com/Automattic/wp-calypso/assets/74204272/4789711d-2e10-41a7-aba7-4aed01e99dcf">

**Comment by jp-imagines** [comment]
Just came across this in 7467231-zd-a8c (related to 7467104-zd-a8c – comment above updated for proper ID), and I'm still able to replicate the issue on this user's site. However, I _don't_ see the issue on @kelasante 's test page above.

On the user's site, the `object` element for the embedded PDF file exists, but it has a `hidden` property which forcefully hides it. 

![JXoZIv.png](https://github.com/Automattic/wp-calypso/assets/5630717/2c421f7d-2b76-4394-8792-c3cc7ad4a9ac)

That looks to be coming directly from their theme (_Maywood_). If I preview that theme on @kelasante 's site, I see the same `hidden` property and behavior. This might be a theme-specific issue?

**Comment by Mfarroq1** [comment]
7486167-zen  The issue only appears in the classic themes, In block themes pdf working fine

**Comment by kelasante** [comment]
> Just came across this in 7467231-zd-a8c (related to 7467104-zd-a8c – comment above updated for proper ID), and I'm still able to replicate the issue on this user's site. However, I _don't_ see the issue on @kelasante 's test page above.
> 
> On the user's site, the `object` element for the embedded PDF file exists, but it has a `hidden` property which forcefully hides it.
> 
> ![JXoZIv.png](https://private-user-images.githubusercontent.com/5630717/292514399-2c421f7d-2b76-4394-8792-c3cc7ad4a9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTg0NTUsIm5iZiI6MTcwMzI1ODE1NSwicGF0aCI6Ii81NjMwNzE3LzI5MjUxNDM5OS0yYzQyMWY3ZC0yYjc2LTQzOTQtODc5Mi1jM2NjN2FkNGE5YWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTUxNTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE5NjUyYTE1MWExZDEyMTE2OGFjNjM4OGIwZmM1N2Y0MWQ4MDM2OTQzZTUxNmFmZTgyNjgwMjNhMDVmMjYzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sPZjElWWpMZYNwCydhFagtnL9ho28UQh3KeU1_f0qJ4)
> 
> That looks to be coming directly from their theme (_Maywood_). If I preview that theme on @kelasante 's site, I see the same `hidden` property and behavior. This might be a theme-specific issue?

When I created the test page, I had the Hever theme but switched it to Twenty Twenty-Two yesterday. That seems to be why it was not working yesterday and works today per @Mfarroq1 comment. I'll follow up with the user 7448330/zen who initially reported this and share workaround of switching to a block theme.

**Comment by jp-imagines** [comment]
@kelasante Some CSS should do the trick as a temporary workaround if they're uninterested in changing themes:

```
/* Workaround: Display embedded PDFs | xxx-zd JP */
.wp-block-file > object.wp-block-file__embed[hidden] {
    display: unset;
}
```

**Comment by kelasante** [comment]
> @kelasante Some CSS should do the trick as a temporary workaround if they're uninterested in changing themes:
> 
> ```
> /* Workaround: Display embedded PDFs | xxx-zd JP */
> .wp-block-file > object.wp-block-file__embed[hidden] {
>     display: unset;
> }
> ```

Thank you @jp-imagines That CSS did the trick! 😄

**Comment by mgozdis** [comment]
Another user report here but they are AT: 7489159-zd-a8c 

I thought it was [this bug](https://wordpress.com/support/embed-a-pdf-file/), which was closed, but it's affecting all browsers now and not just Safari.

Deactivating Gutenberg is another workaround if site is AT.

**Comment by Aurorum** [comment]
7482639-zen (provided workaround)

**Comment by sophiegyo** [comment]
Encountered in 7505106-zen (and related 7504998-zen). Provided workaround, including an adjustment to try to stop the preview working on iOS devices because of this issue:
https://developer.apple.com/forums/thread/649982

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated / Could Not Replicate / Uncertain
- Tested on P2 (optional) – Replicated / Could Not Replicate / Uncertain
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Simple Site, Twenty Sixteen Theme
![CleanShot 2023-12-28 at 11 09 44@2x](https://github.com/Automattic/wp-calypso/assets/14153300/a3ae879d-d9f4-42ea-8f85-78be198fd9cc)

Also reproduced in a local site and reported in core: https://github.com/WordPress/gutenberg/issues/57419


📌 ACTIONS
- Triaged

📌 Message to Author
Thanks for reopening @kelasante

**Comment by liviopv** [comment]
Moving interactions from duplicate issue

- [ ] 7458612-zd-a8c
- [ ] 7464568-zd-a8c
- [ ] 7471698-zd-a8c
- [ ] 7486167-zd-a8c
- [ ] 7449298-zd-a8c

**Comment by darnelldibbles** [comment]
Another instance found in the forums: https://wordpress.com/forums/topic/pdf-embed-is-no-longer-working-since-2022/?view=all

**Comment by saginpj** [comment]
- [ ] 7496224-zen (provided workaround)

**Comment by sophiegyo** [comment]
User report 7522039-zen 

Theme: Exford (Varia)
Plan: Personal - can't use CSS workaround

**Comment by saginpj** [comment]
- [ ] 7542307 - zen
- [ ] 7573280 - zen (provided CSS workaround)

**Comment by liviopv** [comment]
I can no longer reproduce, I think it was fixed with https://github.com/WordPress/gutenberg/pull/57396 closing
