### ISSUE TITLE
Simple Sites: Cover Block with Video Background not playing on mobile devices

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#85257]
### Quick summary

On simple sites, cover blocks with video backgrounds show a still image background when viewed from mobile devices.

### Steps to reproduce

1. On a simple site, add a cover block to a page or post
2. Upload a video to the background of the block. (you can download free video clips here: https://www.pexels.com/videos/ )
3. Publish the content
4. View from desktop browser
5. View on mobile device

### What you expected to happen

The background video to auto-play in the cover block, as it does on desktop:

![CleanShot 2023-12-13 at 17 20 49](https://github.com/Automattic/wp-calypso/assets/27249804/fd7ecc4c-a85d-4e72-9b53-5811d83fedde)

### What actually happened

The background video is a still image, appearing frozen.

_Self Hosted, Atomic, then Simple Site behavior:_

https://github.com/Automattic/wp-calypso/assets/27249804/86087083-2f5d-43c4-a5bf-4531f4c9dca3

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Customer report: 7440108-zen

---

Tested on Simple, AT, and outside of dotcom, and can only reproduce on simple sites. 

Simple site: 
- Gutenberg: v17.2.1
- Editing Toolkit: 4.6622
- CoBlocks: 2.18.1-simple-rev.4
- Theme: TT3

Atomic Site: 
- Gutenberg: 17.1.4 
- WordPress.com Editing Toolkit: 4.6407
- CoBlocks: 3.1.5
- Theme: TT4

Self-Hosted Site:
- Gutenberg 17.2.1
- WordPress 6.4.2
- Theme: TT3

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Testing on Chrome for Android on a Pixel 8 running Android 14

Video here: https://videos.files.wordpress.com/XvpRNXFU/wp-1703074411851.mp4 (too big for GH)

📌 ACTIONS
- Triaged
- Requested author feedback
- Closed as could not replicate (please reopen if the issue reoccurs)


📌 Message to Author
@cuemarie I was not able to repro this on my phone (Pixel 8, Android 14) on Chrome . Which browser/device did you use?

**Comment by cuemarie** [comment]
Hey @liviopv ! Thanks for testing, and my bad for not including this! I used an iPhone XR, testing on Safari and Google Chrome.

Feel free to send me the links to your sites (here or in slack) and I can those sites on my device!
