### ISSUE TITLE
Reader Stream Refresh: convert existing streams to use new post cards

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#8525]
For the Reader Stream Refresh, convert each of the following streams to use new Reader post cards and ensure that everything appears as it should:
- [x] Following (/)
- [x] Team stream
- [x] Site stream (e.g. /read/sites/123)
- [x] Feed stream (e.g. /read/feeds/123)
- [x] Discover (/discover)
- [ ] Search (/read/search) ( #9077 )
- [x] My Likes (/activities/likes)
- [x] List stream (e.g. /read/list/blowery/comics)
- [x] Tag stream (e.g. /tag/hongkong)
- [x] Recommended posts - alpha streams (/recommendations/posts)

**Comment by bluefuton** [comment]
As part of this, we need to fix the container page styling, including stream headers.

**Comment by blowery** [comment]
last one will be fixed as part of #9077
