### ISSUE TITLE
Add a visible and noticeable link to the Launch checklist in the admin menu

### ISSUE THREAD

**Issue by merkushin** [Automattic/wp-calypso#85267]
### What

Add a visible and noticeable link to the Launch checklist at the top of the admin menu.

### Why

We can find it in the site switching screen.
However, especially, for a new user it might be hard to remember where they've seen this link.
If we have incomplete tasks, we can add it at the top of the admin menu, for example, or in the top bar, as an alternative.

![Image](https://github.com/Automattic/wp-calypso/assets/329356/36ae632f-1b4f-4db4-8646-10b238f58f3a)

**Comment by donnapep** [comment]
I couldn't find where "Launch checklist" is available from. Regardless, I don't think it matters as we're now going to take the user directly to WP admin after completing the onboarding flow.
