### ISSUE TITLE
Like block: make the Reblog setting toggle enable / disable the Reblog button on per-block basis

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#85273]
Currently the Reblog setting toggle is affecting the site-wide setting. The goal of this task is to change this behavior and make the toggle affect the specific block only.

This task has a lower priority. In case we would like to launch earlier than this task is finished, we can temporarily disable the toggle from displaying: https://github.com/Automattic/jetpack/pull/34646.

**Comment by TimBroddin** [comment]
This can probably be achieved by adding a query parameter to the iframe URL.

**Comment by ivan-ottinger** [comment]
> This can probably be achieved by adding a query parameter to the iframe URL.

That sounds great to me!

One note (so we won't forget): Once the new implementation that will handle the toggle change is in place, we will also want to remove `fetchReblog` and `setReblog` callbacks which will be unnecessary.

**Comment by ivan-ottinger** [comment]
D133509-code is ready for review.
