### ISSUE TITLE
Change migration trials round to floor()

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#85272]
Context:
1. pdKhl6-2Vg-p2
2. https://github.com/Automattic/wp-calypso/pull/81013
3. https://github.com/Automattic/wp-calypso/pull/81016

Change integer approximation to `Math.ceil()`.

**Comment by daledupreez** [comment]
Thanks for creating this issue, @zaerl! I have two comments:
* We should change the rounding to `Math.floor()` - these locations are already using `Math.ceil()`
* We also need to update the client-side nudge to use `Math.floor()`
https://github.com/Automattic/wp-calypso/blob/310a632b8de8bcaa47219a4df2112a6f3584a90d/client/my-sites/current-site/notice.jsx#L157-L159

**Comment by daledupreez** [comment]
Also, we should double-check whether the admin bar nudge/upsell I linked to above should be using `moment.utc( endsAt )`  to make sure we're doing an accurate calculation, and not defaulting to the user's current time zone.

**Comment by p-jackson** [comment]
I've created this PR #85454 and this diff D132466-code.

With the new logic is much more likely there'll be 0-days remaining and so I've edited the copy in the `<TrialBanner>` banner to say "trial ends today" whenever the number of days remaining drops below 1.
