### ISSUE TITLE
Year in Review: Wire in or remove CTAs at bottom of page

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#85283]
### Details

As things stand the CTAs at the bottom of the page don't do anything, but we're not sure what they should do.

We should either wire them in, or remove them.

The UX here may be linked to that for toggling the privacy settings for the report - https://github.com/Automattic/wp-calypso/issues/85227

### Checklist

- [ ] The CTAs go somewhere useful, or are not present

### Related

https://github.com/Automattic/wp-calypso/issues/85227

**Comment by daledupreez** [comment]
I stumbled on some important related code earlier today, and I want to note what I found.

In the 2015 recap code, creating a new blog post is handled via this form: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Snaahny%2Qercbegf%2S2015%2Qcntr.cuc%3Se%3Qq2n4snp9%231079%2Q1083-og
When that form is submitted to `/wp-admin/post-new.php` for WPCOM Simple sites, the code in the `Year_In_Blogging` class hooks in and pulls the landing page content into a post draft - fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Slrne%2Qva%2Qoybttvat.cuc-og

Not sure if we're going to be able to do anything similar, but wanted to note that we may be able to leverage some of this logic.

**Comment by andres-blanco** [comment]
We didn't arrive to something concrete so we removed the CTAs, D133139-code.
