### ISSUE TITLE
Like block: create component that will guide users to enable Likes module (and related site options)

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#85291]
The goal of this task is to implement solution suggested by Mikael in https://github.com/Automattic/jetpack/pull/34639#issuecomment-1855736136.

We will need to handle all the cases that were already addressed in https://github.com/Automattic/jetpack/pull/34639 while providing the user next steps (not just activating the `likes` module, but also suggesting them to enable / disable related site options depending on the site type).

**Comment by TimBroddin** [comment]
Dropped this, because we are now decoupling it.
