### ISSUE TITLE
Stats: bar tooltip blinks when unfortunately positioned

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#85293]
Steps to reproduce:

1. Go to `/stats/day/:site`
2. Scroll or resize the browser window so that the chart with the bars is at the bottom edge of the viewport: that forces the tooltips to appear _above_ the bars
3. Start hovering with the mouse over the bars, and watch the tooltips as they appear and disappear.

After a short time, you'll get one of them blinking really fast:

https://github.com/Automattic/wp-calypso/assets/664258/83e364ef-6191-4179-9535-464286203e12

That happens because the tooltip appears right under the mouse cursor, which triggers a `mouseleave` event on the bar element, and that hides the tooltip, and so on.

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate 

## 📌 ACTIONS ##
- Author feedback
- Closed as could not replicate (please reopen if the issue reoccurs) 

##Message to author##
Thanks so much for the report. I couldn't replicate the issue. Are you still able to produce this on a number of sites? I wonder if this is connected to a site with a lot of daily traffic perhaps? Feel free to reopen if you can still replicate.
