### ISSUE TITLE
PTK API: Update the page to clear the pattern cache

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#85290]
## What
In the MC tool `/patterns-toolkit/cache-management/`
- Remove `fse_block_patterns` source site as it's no longer used
- Review the logic on that page to learn and see if we can make it dynamic 
- Study if it's needed to add new source sites there (assemblerv2patterns)

## Why
It's outdated

## How
Find the code in MC repo

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
