### ISSUE TITLE
Assembler: Site preview zooms over 100%

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#85317]
### Description 

Having the site preview scale past 100% makes the fonts and other elements seem quite distorted and very large. I would expect that the preview cannot scale past 100%, and instead would be centered in the available space. 

### Visuals
![CleanShot 2023-12-14 at 14 50 20](https://github.com/Automattic/wp-calypso/assets/1813435/9570888c-641e-4a3c-99b1-899fc4e33259)

**Comment by autumnfjeld** [comment]
This will be taken care of in https://github.com/Automattic/wp-calypso/issues/85123

**Comment by richtabor** [comment]
> This will be taken care of in https://github.com/Automattic/wp-calypso/issues/85123

The whole site preview is pulled over 100% its original size; not the zooming mechanism itself. We'd need to adapt a full stop on the scaling of the site frame, so that the contents are not scaled.

**Comment by lucasmendes-design** [comment]
> The whole site preview is pulled over 100% its original size

Interesting, I didn't know that. Do you have an example? Like before and after?

**Comment by taipeicoder** [comment]
When the viewport is wide enough, the preview can zoom beyond 100%:
![Image](https://github.com/Automattic/wp-calypso/assets/797888/9ee11370-4106-4b71-ae9e-3a68adcee232)

What @richtabor is proposing is to cap it at 100% and center it:
![Image](https://github.com/Automattic/wp-calypso/assets/797888/79161240-524b-4206-9e95-761310473b87)

**Comment by taipeicoder** [comment]
Proposing this PR https://github.com/Automattic/wp-calypso/pull/85820 cc: @autumnfjeld @lucasmendes-design @Automattic/lego

**Comment by liviopv** [comment]
📌 ACTIONS
- Marking this as Triaged since Marvel/Lego is already working on it and there's a PR to fix.

**Comment by autumnfjeld** [comment]
Closing this https://github.com/Automattic/wp-calypso/pull/85820
