### ISSUE TITLE
Expired plans show up as Free on the plans page

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#85310]
### Quick summary

If you have a plan that is expired but has not been removed yet, the Plans page shows your plan as being "Free" (even though other parts of the page correctly identify that you still own a paid plan).

In the screenshot below, the blue arrows are basically correct, and the red arrow shows the problem:

![expired-plan](https://github.com/Automattic/wp-calypso/assets/235183/f6fd812d-10ba-4641-bb12-dc9cf70aefd0)

I feel like we've seen similar bugs elsewhere (but I can't remember), and there might be some particular API in Calypso that is (deliberately) ignoring the existence of expired plans, and that API shouldn't be used here.

### Steps to reproduce

1. Get a site with an expired plan (i.e. a few days past its expiration date).  Automatticians can set this up themselves, but otherwise I guess you have to wait :smile: 
2. Visit https://wordpress.com/plans for your site, while logged in as the site owner

### What you expected to happen

Some indication that the plan was still on my site, probably also indicating that it is expired (as done elsewhere in Calypso).

### What actually happened

It said I had a free plan, even though I don't (and even though that contradicts information elsewhere on the page).

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Replicated 
![Image](https://github.com/Automattic/wp-calypso/assets/13706336/a1319388-2005-4bb1-be66-5160806f4fe0)
-  Tested on Simple – Replicated 
![Image](https://github.com/Automattic/wp-calypso/assets/13706336/50a00991-5bcd-4d9e-aa76-e01242c37e8f)

**Comment by Aurorum** [comment]
@rickmgithub assuming that nobody is working on this and I can take a stab at it, would you mind inviting me to a site with an expired plan? Thanks!

**Comment by michaeldcain** [comment]
@Automattic/martech-decepticons can y'all track/shepherd this? 

> If you have a plan that is expired but has not been removed yet

This is from the "grace period" of time where a Store Subscription has expired, but not moved to the inactive table.

**Comment by southp** [comment]
Thanks for the ping. I've added it to our Next Up column.

**Comment by aneeshd16** [comment]
I have proposed a fix in #89411
![image](https://github.com/Automattic/wp-calypso/assets/5436027/8143e4b2-79c0-47bd-9a57-dfb622a560ce)

This is a WIP PR, since we also need a way to show that the plan has expired on the spotlight plan card. @southp, do you know who could help us with the design for this?

**Comment by southp** [comment]
Thanks for coming up with a fix so quickly, @aneeshd16 . 

> This is a WIP PR, since we also need a way to show that the plan has expired on the spotlight plan card. @southp, do you know who could help us with the design for this?

@vinimotaa Would you have some bandwidth to help on this? I'd be grateful 🙇🏼

**Comment by aneeshd16** [comment]
A few ideas:

Expired Plan:
<img width="1219" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/0b994ac3-7345-4d53-9f00-52dcf3205614">

Active Plan with auto-renew enabled:
<img width="1260" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/dcefb01b-f2f2-4ba6-bf63-b3f7efa47d80">

Active Plan with auto-renew disabled:
<img width="1238" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/a3750269-afab-414c-8370-2e068c37895d">

This logic is already present in the `<ProductExpiration/>` component: https://github.com/Automattic/wp-calypso/blob/trunk/client/components/product-expiration/index.tsx

**Comment by vinimotaa** [comment]
Hi folks - I give it a crack on this, and here is what I suggest;

![My Plan](https://github.com/Automattic/wp-calypso/assets/97929097/0d8e6562-ac42-43a4-9a3d-74022a2c9fb3)

I reorganized the information within the component, ditching not-relevant information at that touchpoint, and creating a balance within the white space. I hope this helps - all scenarios and specs can be found on FIgma link below.

[Figma](https://www.figma.com/file/Uzd0AYiDAV4eFq1V35T9Ef/WPCOM-Plans-%E2%80%A8Ecosystem?type=design&node-id=775%3A12270&mode=design&t=z1OAXQtXKsvM0OyU-1)

**Comment by aneeshd16** [comment]
Thanks @vinimotaa, looks good! I had some feedback:

* The price shown is the price per month, even for 1/2/3 year plans. Omitting the `per month, US$XYZ billed annually, excl. taxes` text might cause confusion since the price shown is not the amount they paid for the subscription.
* For expired plans, renewing is important, and there is a sense of urgency attached to the action. What do you think about making the "Expired on..." and "Renew Plan" CTAs more prominent?
* On mobile, this card is not shown. Instead, the current plan is shown as the first card in the list. For this card, we can add the "Expired on.." text and change the CTA from "Manage Plan" to "Renew Plan". What do you think?
<img width="362" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/eb34d61b-11d4-4945-a07d-3d2669140da8">

**Comment by vinimotaa** [comment]
@aneeshd16 thanks for your feedback!

> The price shown is the price per month, even for 1/2/3 year plans. Omitting the per month, US$XYZ billed annually, excl. taxes text might cause confusion since the price shown is not the amount they paid for the subscription.

I might be wrong, but I think this should be fine as the whole information will be shown at the checkout page?

> For expired plans, renewing is important, and there is a sense of urgency attached to the action. What do you think about making the "Expired on..." and "Renew Plan" CTAs more prominent?

I think this should be enough - "about to expire" and "expired" could be shown in red (which is already a good affordance), and we don't need a button to allow them to trigger the renew action.

> On mobile, this card is not shown. Instead, the current plan is shown as the first card in the list. For this card, we can add the "Expired on.." text and change the CTA from "Manage Plan" to "Renew Plan". What do you think?

Sound good!

**Comment by aneeshd16** [comment]
> I might be wrong, but I think this should be fine as the whole information will be shown at the checkout page?

That's true! But this card implies that the renewal price is 8$ since that's the only price next to the "Renew Plan" CTA. Once the user goes to checkout, they'll see that the actual renewal costs $96 + tax, which could be misleading for some users. There is a prior discussion on the "excl. tax" language here: pdgrnI-27y-p2, https://github.com/Automattic/martech/issues/1580, p7DVsv-gc4-p2#comment-46307
I also think that the `per month, $X billed anually` language was a deliberate choice, but I can't quite find any references to that. @southp or @niranjan-uma-shankar, would you happen to know where this was discussed?

**Comment by niranjan-uma-shankar** [comment]
I would strongly recommend not to remove the "per month, billed annually" copy. It could lead to user's inferring that the plan costs just $4. We shouldn't rely on users discovering the full price at checkout - that leads to sticker shock and affects purchase conversions. Moreover, we are displaying the full plans grid below the spotlighted plan, and that will have the per month, billed annually copy, it'll be confusing. 

For a long time we had only "per month, billed annually" and even that led to multiple support requests, and we changed to showing the full price ~which I recommend we continue to do so~ but maybe the full price is not needed to be shown in a renewal context for a just-expired plan.

<img width="205" alt="Screenshot 2024-04-17 at 5 00 02 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/a96bf1a1-1cf4-49ab-9eb2-12109610d968">

I understand the intent and sentiment behind the design - the div below the plan price looks busy and text-heavy, and we should reduce the clutter below the plan price (check `pdgrnI-2IT-p2#4-improving-how-we-present-annual-price-and-renewal-price`). We could maybe explore tooltips and footnotes to improve the presentation (we still can't hide the fact that we bill annually behind a tooltip), but that would be best served as a separate discussion with a holistic view across all touchpoints where we display plans, and considering all scenarios (discounts, pro-rated credits etc).

**Comment by DavidRothstein** [comment]
>I would strongly recommend not to remove the "per month, billed annually" copy.

Agreed, and that change seems out of scope for this issue anyway.

Some kind of simple "Expired" indicator (for example like @aneeshd16 mentioned in https://github.com/Automattic/wp-calypso/issues/85310#issuecomment-2048983888) seems like it's all that's required to fix this?  For comparison, that's what's already done elsewhere, e.g. on the My Plan page, so it would make sense to be consistent with that:

![my-plan-expired](https://github.com/Automattic/wp-calypso/assets/235183/ee21a49a-16de-4aaf-97c1-963dd7d8221b)

**Comment by DavidRothstein** [comment]
By the way, I can no longer reproduce the bug as it was originally written (not sure if anyone else can).  For me, if I have an expired plan, it's now showing up correctly on the Plans page (the Free plan is not shown) **but** the action button is changed to "Active plan" and is grayed out so I can't actually click to manage it:

![expired-plan](https://github.com/Automattic/wp-calypso/assets/235183/bd6ff947-ce23-4efa-bb5c-f83b3dc8b3f6)

Still not ideal behavior, though, and probably worth fixing.

**Comment by aneeshd16** [comment]
Hi @vinimotaa, I was wondering if you had a chance to refine the design based on this feedback?

**Comment by vinimotaa** [comment]
Hi folks, based on your feedback, I came up with another 2 alternatives for us to consider.

![My Plan](https://github.com/Automattic/wp-calypso/assets/97929097/4c2031cc-399e-4244-9ea6-024f244788c3)

Please let me know your thoughts so I can refine it further and prepare the handoff.

cc @aneeshd16 @DavidRothstein @niranjan-uma-shankar

**Comment by aneeshd16** [comment]
Thanks @vinimotaa! If the two alternatives are functionally the same, I would prefer the second one since it's closer to the current card and implementing the change would be easier.

**Comment by vinimotaa** [comment]
Folks, hold on, I'm gathering some feedback from other design folks before moving forward with this. :)

**Comment by vinimotaa** [comment]
Latest WIP here: p9Jlb4-bSl-p2

Let's just validate it first with the broader team and we can plan the implementation.

**Comment by aneeshd16** [comment]
Hi all! I have shipped https://github.com/Automattic/wp-calypso/pull/89411 so that it fixes this particular bug where the free plan is shown if the plan is expired. It also changes the button CTA text to "Renew Plan".

There are additional changes planned to the spotlight card (mentioned by Vini above). We'll be taking those up a separate follow-up.
