### ISSUE TITLE
Assembler: Smooth scroll to selected pattern

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#85319]
The site preview should always smooth-scroll to the recently applied pattern on selection. 

You do see the latest applied pattern, if you're already at the bottom of the page, but otherwise there is no real affordance provided to indicate how the pattern you just selected looks among the others. 

And the current implementation also does not smoothly scroll you to the view, which would be helpful in understanding the location of the pattern relative to the page (even if it's always at the bottom). 

Related: https://github.com/Automattic/wp-calypso/issues/68070

### Visual 

https://github.com/Automattic/wp-calypso/assets/1813435/3343660c-8f73-43cf-b061-6f186ab7cc24

**Comment by autumnfjeld** [comment]
cc: @lucasmendes-design

**Comment by lucasmendes-design** [comment]
+1 on this ✌🏽

This is the kind of animation that I'm working on for the BlueSky + Assembler :)

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
