### ISSUE TITLE
Assembler: Remove snackbar notices on pattern selection/removal

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#85320]
They can be distracting, and not quite helpful. 

The notices are not necessary for shuffling, as you've interacted the pattern you're changing anyhow; the same for deleting a pattern. I suspect the notice is in place as you may not visually see the latest pattern added to page. If this is the case, it's not the correct affordance for that. 

Instead, we should first consider scaling down the site (https://github.com/Automattic/wp-calypso/issues/85123#issuecomment-1856485029), so you can see more of what you're doing. And second, the site preview should always smooth-scroll to the recently applied pattern on selection (https://github.com/Automattic/wp-calypso/issues/85319). 

Combined, those would add much more awareness to what's happening than a notice. 

### Visual 

https://github.com/Automattic/wp-calypso/assets/1813435/1e7fb2b7-770b-4877-8d95-d996f188e360

**Comment by richtabor** [comment]
The snackbar also indicates insertion when you move a pattern using the movers. 😅

**Comment by autumnfjeld** [comment]
On shuffle it definitely is not needed.

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
