### ISSUE TITLE
Assembler: Add motion to pattern reordering

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#85321]
The ability to move patterns around throughout the Assembler is a crucial part of the "assembling" experience. However, the interaction itself can be quite disorienting, as two patterns have instantly moved around. The WordPress editor has already added motion to block moving; the Assembler should do the same, giving a better sense of flow and clarity. 

### Visuals

This first visual is how pattern reordering looks today in the Assembler.

https://github.com/Automattic/wp-calypso/assets/1813435/814b936e-f43a-4acd-8b3d-94698c3a90ea

This second visual shows the same interactions, moving patterns within the WordPress editor. There's a much better sense of what is moving where, and the pattern moved stays in focus. 

https://github.com/Automattic/wp-calypso/assets/1813435/e41dfb11-0cb0-4647-99d4-1ec88e560e88

**Comment by autumnfjeld** [comment]
cc: @lucasmendes-design

**Comment by lucasmendes-design** [comment]
+1 as well. This kind of motion will help users and make the experience even better. The motion in the editors is better than the Assembler, but it's not great yet. Let's iterate on this :) it's time to refine the experience to another level 🚀

Thanks Rich

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
