### ISSUE TITLE
Different Renewal Dates on My Plan vs. Purchases

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#8533]
As reported in p2MSmN-5sO-p2 by @kriskarkoski, there are different renewal dates on `plans/my-plan` page and `purchases/` for the same plan.

More details in the p2 post.

**Comment by lamosty** [comment]
I found out the problem: we are using `userFacingExpiry` prop on site specific plan to display the renew date. However, `user_facing_expiry` is deprecated and should not be used for anything these days as it seems like it was used for showing trial expiration date.

We should instead use the same thing as is used on `purchases/`:

1. Get user purchases for specific site;
2. Select the plan purchase;
3. Use `purchase.renewMoment` for displaying the renew date.

We need to write new selector for getting site plan purchase. It could be named `getSitePlanPurchase` and would return the plan purchase object of some site. 

One issue: users can buy multiple Jetpack plans so this function would return multiple plan purchases per site.

Solution to the above might be to either:

1. Pass down plan slug to the `getSitePlanPurchase` which would return only the purchased plan based by the plan slug param. Downside: in addition to querying site purchases, we also need to query site plans to get current plan slug.

2. Return all plan purchases from `getSitePlanPurchase` and then optionally filter the purchases by plan slug. In case we know it's not a Jetpack site, there'll be just one plan so we don't need querying the site plans. In case it's a Jetpack site, we need to do that.

I would run with the second approach because we need to fix the Jetpack plans stuff anyway.

/cc @gwwar 

/cc @mtias as you've introduced the `isCurrentPlanExpiring` selector in `state/sites/plans/selectors`. Can I remove it?

**Comment by gwwar** [comment]
I would try to update this in the API first. I believe we're passing some expiry ( wrong values I suppose ) off of the site specific endpoint, and I think we need to check the values for `site.plan`

**Comment by artpi** [comment]
> Get user purchases for specific site;

Last time I did this, I almost brought down wpcom with me because this is stored in billingdaddy which IS NOT part of wpcom, so wpcom has to request it through API every time we hit that endpoint.
Context: s1471615631004982-slack-plans-focus

That was on /me/sites endpoint, so it was particularly bad. Maybe on /site/plans it wont be so bad...

**Comment by artpi** [comment]
Ok, I have a safe, non-wpcom-destroying fix  D3030-code :)

**Comment by artpi** [comment]
Both parts of the fix deployed.
