### ISSUE TITLE
Stats: Fix average payment in PWYW flow

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#85343]
Currently the value is hard-coded, per this screenshot:

![Image](https://github.com/Automattic/wp-calypso/assets/40267301/b5cec79c-6ff4-4601-8aa7-8327c256b89d)

Should display an appropriate value depending on the current currency and selection.

**Comment by dognose24** [comment]
I found an issue **_when I already had a free plan_** and went to the PWYW purchase page. I saw a weird minimum and maximum price when testing https://github.com/Automattic/wp-calypso/pull/85344. The maximum price even exceeded the base tier of the Stats monthly plan.

|Minimum|Maximum|
|-|-|
|<img width="611" alt="截圖 2023-12-15 下午11 48 11" src="https://github.com/Automattic/wp-calypso/assets/6869813/99e8e1a1-a71c-4837-99a5-b1b8f5e1a81d">|<img width="608" alt="截圖 2023-12-15 下午11 48 17" src="https://github.com/Automattic/wp-calypso/assets/6869813/3762b7a2-d868-4538-9f4a-2054e6cca69a">|

The original minimum and maximum were $0.5 and $10. The problem could be the [calculation of slider steps](https://github.com/Automattic/wp-calypso/blob/b12f719311d7cbc24464c91be1efad8236f47219/client/my-sites/stats/stats-purchase/stats-pwyw-uprade-slider/index.tsx#L77C1-L87).

**Comment by a8ck3n** [comment]
> I found an issue when I already had a plan and went to the PWYW purchase page.

Thanks for the feedback, @dognose24. As far as I'm aware, the PWYW flow doesn't support this scenario yet. We have a separate issue for prorated upgrades here:

https://github.com/Automattic/wp-calypso/issues/85124

I haven't looked at the issue yet but I'm sure it will impact how the tiers are calculated when presenting the slider.

**Comment by dognose24** [comment]
@a8ck3n I think the issue I mentioned is not entirely about https://github.com/Automattic/wp-calypso/issues/85124. It is more about the existing flow caused by introducing the _shared_ tier upgrade slider, e.g., I had the **free plan**, and I want to purchase the **PWYW plan**, but I would get the wrong price periods.

**Comment by a8ck3n** [comment]
> It is more about the existing flow caused by introducing the shared tier upgrade slider, e.g., I had the free plan, and I want to purchase the PWYW plan, but I would get the wrong price periods.

So you mean this is a result of updating to the new slider? In that case, we'd expect the flow to work correctly with the previous slider in place.

I'm not sure I fully understand the root issue here so I'll start by trying to reproduce this first. This PR is specific to the "average payment" line which does appear correct in your screenshots though. I'll open a new issue for the unexpected tier values you flagged in your screenshots.

Edit: See #85398 for this issue.

**Comment by dognose24** [comment]
@a8ck3n Yes, thanks for the follow-up task. 👍🏼
