### ISSUE TITLE
Assembler: Omit V2 patterns categorized as pages

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#85376]
Instead of using tags, we use the existing pattern registration categories for V2 page patterns, assigning page layout patterns to a "Pages" category, indicating they are designed as full page layouts. These patterns also have a category to indicate the type of page (which aligns to the existing pattern categories). I.e. "About", "Services", "Contact", "Store", etc. 

In Assembler, patterns with a "Page" category should be omitted from the "Select patterns" view, as they are complete pages—not individual sections of a website.

### Visuals

A services page pattern, assigned as to the "Services" and "Page" category, which should be omitted from the "Services" category. 

![Image](https://github.com/Automattic/wp-calypso/assets/1813435/bbfc6e6f-bf6c-43fa-9ab8-cc7c8e9ab15b)

**Comment by miksansegundo** [comment]
Closed via https://github.com/Automattic/wp-calypso/pull/85477
