### ISSUE TITLE
Can't select primary site & cannot edit posts for WPCOM simple site

### ISSUE THREAD

**Issue by haszari** [Automattic/wp-calypso#85382]
### Quick summary

I'm supporting someone with their WPCOM blog (on a Premium plan). 

- The initial problem: user can't write new posts, editor doesn't load, `Please set a Primary site` error shown. 

![Editor doesn't load due to no primary site error](https://github.com/Automattic/wp-calypso/assets/4167300/154a0a20-7eb1-407e-be7b-3be1337b171a)

This seems to be caused by an issue with the primary site setting for the user account. The error message prompts user to edit `Account settings`, linking through to https://wordpress.com/me/account

- This page also has an issue. The list of sites doesn't load, so it's impossible to select a primary site. The error message displayed is `Failed to retrieve all domains`.

![Can't select primary site in account settings due to error loading site list](https://github.com/Automattic/wp-calypso/assets/4167300/6e813640-d900-444a-96c6-be1f16edeee1)

#### Things to note
- This site does not use a custom domain, is on a .wordpress.com subdomain.
- This site is the user's only site and has always been (have only ever had one WPCOM blog). 

### Steps to reproduce

As this user, or another user affected…

- Go to https://wordpress.com/me/account and try to select primary site.
- OR
- Go to https://wordpress.com/post and try to author a post.

### What you expected to happen

- Can post anytime, and the "primary site" snafu shouldn't block access to editor or site admin /dashboard screens.
- The snafu with primary site can be easily and quickly resolved.

### What actually happened

Can't figure out what the "primary site" issue is and this seems to be the blocker.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

This issue seems potentially related: 

- #79324

However these reports seem to be mostly related to Jetpack sites, so maybe not related. 

Happy to share user/site info privately, ping @haszari

**Comment by haszari** [comment]
Looking at the screenshot, the account settings page doesn't have the user id/info (blank username field). So that is probably related / the cause of the domain/site list not loading.

**Comment by rickmgithub** [comment]
Hi @haszari 

Did you have a link to share for this user report?

Also, did you happen to report this to AT-help/Reactor? Do you have a link?

**Comment by Aurorum** [comment]
7780354-zen - Simple site

**Comment by sixhours** [comment]
This issue was marked as resolved in the corresponding ZD ticket so I'm closing this.
