### ISSUE TITLE
Calypso Navigation bar does not work on Mobile browsers

### ISSUE THREAD

**Issue by Brianmitchtay** [Automattic/wp-calypso#85389]
### Quick summary

This appears to effect all Dotcom sites. Was initially reported by a Woo Express user.

On the mobile browser view of Dotcom site's dashboard, the “W” menu icon is frozen and doesn’t do anything. It appears to happen on all WPCom sites and could possibly be related to the “New menu bar” I got a JITM message about when I opened the wordpres.com/me view?
![IMG_2918](https://github.com/Automattic/wp-calypso/assets/45057772/05d0e0f0-22ce-4347-b233-18602d94569a)

https://github.com/Automattic/wp-calypso/assets/45057772/c5730360-8ba1-49a9-aaa9-92c7b2ec23b5

This only appears to occur when visiting the site on a mobile browser as opposed to the mobile app prevents, but for those site owners who manage their sites from their browsers, they are prevented from accessing any admin menus to manage their site.

See peapX7-3LE-p2 for initial report.

### Steps to reproduce

- Create a WordPress.com site
- Open the site to its wp-admin page on your phone's web browser
- Log in and visit any wp-admin area.
- Attempt to open the admin menu by tapping the WordPress W icon.
- Note that nothing happens
- Attempt to find any navigation
- Note no other options exist to find other admin pages, etc.

### What you expected to happen

Navigation of the admin area should work on all devices

### What actually happened

You can't navigate the admin area of any WordPress.com site on a mobile browser right now.

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Steps to reproduce:

1. Open WordPress.com on a mobile browser (I used Chrome for Android)
2. Select an Atomic site
3. Navigate to any item on the interface that would load with a `wp-admin` URL, like Plugins > Installed Plugins
4. The page will load but the (W) icon will become unresponsive, and it will continue to be unresponsive while visiting any `wp-admin` screen on

📌 ACTIONS
- Closed as duplicate

📌 Message to Author
@Brianmitchtay It's the same issue as https://github.com/Automattic/wp-calypso/issues/84236 but thank you for the testing, as it is not only related to WooCommerce as initially reported.

**Comment by Brianmitchtay** [comment]
Ahh I missed that open issue, sorry! 🙇
