### ISSUE TITLE
Update dotcom default Blog theme to Hey theme Jan 2024

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85397]
# Description
Update to Hey theme  per @ianstewart 
p1704722094023369/1702513685.073989-slack-C048CUFRGFQ

p1702565206773819/1702513685.073989-slack-C048CUFRGFQ

#84390 
- [ ] update to Hey
- [ ] post announcement on wpcom happy, x-post to dotcom p2 & themedev

Related https://github.com/Automattic/wp-calypso/issues/81113

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/86574 and pekYwv-3LV-p2
