### ISSUE TITLE
In the design-first flow from LoTS fix the flashing "Blog" in top left

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85396]
See the video in the slack conversation p1701447822196539-slack-C048CUFRGFQ

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/60868256-c229-4b98-b337-27ffe7e8088b)

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/5a799369-20b4-4974-9a4a-9e950f6e1c10)

**Comment by taipeicoder** [comment]
Fixed via #85599.
