### ISSUE TITLE
Add verify_site_integrity to import job step names

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#85402]
Context: https://github.com/Automattic/wpcomsh/pull/1619

Add new `verify_site_integrity` name between `postprocess_database ` and `clean_up` to:

1. `client/blocks/importer/types.ts` `ImportJob.customData.current_step`
2. `client/blocks/importer/components/progress-screen/index.tsx` `getPlaygroundImportTitle`
3. `get_steps()`

The new `case` should output `return __( 'Migrating your data' );` like the other two where it is inserted.

**Comment by ouikhuan** [comment]
Also see: D132323-code
