### ISSUE TITLE
Publicize: Megaphone -> Share  

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#8543]
We need to change the megaphone action and move it to bottom action row

As @folletto puts it:

> The icon should be the standard share icon, given that’s the action that is happening we should reinforce it. I understand that we chose the megaphone because feels an extra action on top, but in practice that’s exactly a share action.
## Now

![screen shot 2016-10-06 at 16 40 12 pm](https://cloud.githubusercontent.com/assets/3775068/19156862/963a4344-8be3-11e6-9f9e-1ccaf40e81ad.png)
## Should be

![screen-shot-2016-09-23-at-11-33-32](https://cloud.githubusercontent.com/assets/3775068/19156871/9e3b8d6e-8be3-11e6-99e8-570b4a1b9d21.png)

Thanks @folletto for this design!

**Comment by gziolo** [comment]
Closed with #9701.
