### ISSUE TITLE
Frontend: Add profile picture to the reviews list type

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#85431]
Add the profile picture of the user in each review, in order to display it in the reviews list as below:

![CleanShot 2023-12-18 at 13 42 01@2x](https://github.com/Automattic/wp-calypso/assets/5039531/8e04e5e1-48b5-4203-9b4e-41ad0362bb46)

**Comment by gcsecsey** [comment]
I checked the Postman collection we have, the core API response already contains the author profile URLs:
![image](https://github.com/Automattic/wp-calypso/assets/11555574/f3beefe4-8d85-4af4-8307-095a89079b8e)

We’ll just need to add it to the response type: https://github.com/Automattic/wp-calypso/blob/803f41a92f256b0ddeef20f871a12ad48efff7a1/client/data/marketplace/use-marketplace-reviews.ts#L42

Based on these, I updated the ticket title to be `Frontend`.

**Comment by WBerredo** [comment]
That's great, thanks for the research @gcsecsey, I'll handle this ticket.
