### ISSUE TITLE
Navigation Block Overlay menu non-functional in Classic themes in Gutenberg 17.2+

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#85441]
### Quick summary

Navigation Block > Overlays are not working on Classic Themes. Clicking on the overlay icon has no response, making the navigation items inaccessible.

### Steps to reproduce

1. On a site with a classic theme active, create a page containing a Navigation block set to Overlay > ALWAYS
2. Publish and view the page
3. Click the Overlay menu icon.

### What you expected to happen

The menu overlay to open

### What actually happened

The menu overlay does not open

Self-Hosted Site on theme TT1:

https://github.com/Automattic/wp-calypso/assets/27249804/8bfe6e9b-58bf-41b9-b304-002034169f7c

Simple Site on theme Twenty Twenty:

![CleanShot 2023-12-18 at 16 00 30](https://github.com/Automattic/wp-calypso/assets/27249804/143a05c5-abb7-46a8-8e5c-f0eb76f2e56b)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable with non-hamburger menus. Hamburger menus not working at all.

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Customer Report: 7440108-zen

Reported in Core: https://github.com/WordPress/gutenberg/issues/57189

**Comment by cuemarie** [comment]
Raised awareness here: p1702941432812569-slack-C03EUR81G3V

**Comment by khristiansnyder** [comment]
7431676-zen

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested Self-hosted with Blank Canvas - Replicated 
- Tested on Simple with Stratford - Replicated 
- Tested on Atomic with Alves – Replicated 

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
As per the original OP

## 📌 ACTIONS ##
Triaged

**Comment by pauljacobson** [comment]
We have another report here: 7470634-zen

**Comment by pauljacobson** [comment]
Another report here: 7460472-zen

**Comment by cuemarie** [comment]
Encountered here: 7525097-zen

AT site; unsymlinked Gutenberg and rolled back to 17.1.4 to resolve.

**Comment by Aurorum** [comment]
7525038-zen - Simple site

**Comment by cuemarie** [comment]
Looks like this is hopefully fixed in Gutenberg 17.4: https://github.com/WordPress/gutenberg/pull/57396

**Comment by jp-imagines** [comment]
Encountered in 7515076-zd-a8c (Simple, 2017 theme).

**Comment by saginpj** [comment]
- [ ] 7536284 -zen

**Comment by jerren1327** [comment]
7548597-zen

**Comment by jerren1327** [comment]
7542286-zen

**Comment by liviopv** [comment]
Marking this as fixed, I can no longer reproduce.
