### ISSUE TITLE
Task: Reblog - Add reblog functionality for logged out users

### ISSUE THREAD

**Issue by agrullon95** [Automattic/wp-calypso#85458]
### Details

Logged out users should be able to click the reblog button, log in and be navigated to the site editor with the blog post embed.

Possible solutions:
1. Create new stepper flow to handle site creation and redirect to post editor.
2. Trigger `sites/new` endpoint to create a new site and redirect to post editor.

### Checklist

- [ ] Add functionality to log in when clicking the Reblog button as a logged-out user.
- [ ] Logged-out users should be navigated to the site editor with blog post reblog embed after they log in.

**Comment by escapemanuele** [comment]
We created a flow for this: https://github.com/Automattic/wp-calypso/pull/85807
