### ISSUE TITLE
Pattern Assembler: handle `page_slugs` in the main assembler view

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#85473]
https://github.com/Automattic/wp-calypso/pull/84437 has introduced the ability to override the page titles based on the selected pages in the `pages` step in the pattern assembler. For example, for the URL:

https://wpcalypso.wordpress.com/setup/ai-assembler/patternAssembler?siteSlug=patternassemblertest23.wordpress.com&siteId=227020025&header_pattern_id=11283&footer_pattern_id=5316&pattern_ids=12076%2C12774%2C12946%2C12149%2C11987&site_title=La+Fiesta+Tacqueria&site_tagline=Authentic+Flavors+in+Every+Bite&page_slugs=home%2Cabout%2Cstore%2Ccontact&screen=pages&color_variation_title=Bronze+Serenity&font_variation_title=Playfair+Display+%2B+Fira+Sans

We get:

<img width="951" alt="Zrzut ekranu 2023-12-19 o 12 44 16" src="https://github.com/Automattic/wp-calypso/assets/3775068/22f0b2d1-383e-4728-956b-a9d64627cbf3">

In particular, the selected pages (from the `page_slugs=home%2Cabout%2Cstore%2Ccontact` ) get shown in the header:

<img width="498" alt="Zrzut ekranu 2023-12-19 o 12 45 02" src="https://github.com/Automattic/wp-calypso/assets/3775068/b1d4106f-6211-4deb-8a37-75ced541015a">

It would be fantastic if the same `page_slugs=home%2Cabout%2Cstore%2Ccontact` also showed the same pages in the header on this screen:

https://wpcalypso.wordpress.com/setup/ai-assembler/patternAssembler?siteSlug=patternassemblertest23.wordpress.com&siteId=227020025&header_pattern_id=11283&footer_pattern_id=5316&pattern_ids=12076%2C12774%2C12946%2C12149%2C11987&site_title=La+Fiesta+Tacqueria&site_tagline=Authentic+Flavors+in+Every+Bite&page_slugs=home%2Cabout%2Cstore%2Ccontact&screen=main&color_variation_title=Bronze+Serenity&font_variation_title=Playfair+Display+%2B+Fira+Sans&screen_parameter=header

<img width="1416" alt="Zrzut ekranu 2023-12-19 o 12 46 05" src="https://github.com/Automattic/wp-calypso/assets/3775068/614ee0ee-aab1-483e-a48b-84229f8f2a77">

**Comment by autumnfjeld** [comment]
> It would be fantastic if the same page_slugs=home%2Cabout%2Cstore%2Ccontact also showed the same pages in the header on this screen:

To rephrase that into familiar terminology :) :   The header patterns shown in the Assembler pattern list and homepage large preview result should reflect the page names that the AI has produced.

Is that correct @artpi?

**Comment by artpi** [comment]
> The header patterns shown in the Assembler pattern list and homepage large preview result should reflect the page names that the AI has produced.

@autumnfjeld no, AI is currently only "preselecting" secondary pages already built into the Assembler. i did not end up generating anything.

I made no changes to this mechanism - the "add pages" view already injects the proper titles, but only in the "pages" view

This is IMO a bug in the pages view itself - even in the non-AI flow if you:

1. Go through assembler
2. Pick pages
3. See preview with the chose page titles
4. GO back to chose patterns view

You will see different pages in the menu that you have seen in the pages view.

**Comment by autumnfjeld** [comment]
Ah yes, I see what you mean.  I would not call it a bug.  Rather a product choice and some technical choices.  We've had numerous iterations of how the header patterns should display the menu.    Currently I believe the patterns use the page list from the demo site https://creatio2demo.wordpress.com/  @miksansegundo correct me if I am wrong. 

Let's discuss what is possible with @miksansegundo .


This is related technical write up from Miguel: 
 Dotcom Patterns – Show Page List In Navigation  pekYwv-3jK-p2

**Comment by taipeicoder** [comment]
Closing via #85747.

We've added the logic for the Assembler AI to show the selected pages for all header patterns across the flow. We can discuss whether to implement this in other Assembler flows as well, later on. cc: @artpi
