### ISSUE TITLE
Domain Management: Email: Select site redirects to manage domains

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#855]
Originally reported by @breezyskies

If you go to wordpress.com/domains/manage/email without a site selected, it redirects to wordpress.com/domains/manage -- so when you select a site, you end up in domain management instead of email (Google Apps). 

Note: We are looking to send out promotional emails for Google Apps this week, which will link to this page, so we need the redirect to work properly for that.

cc: @rads who I talked to about this in AMS.

**Comment by klimeryk** [comment]
@fabianapsimoes: is this still an issue for you? I'm guessing the emails already went out :grin:

**Comment by fabianapsimoes** [comment]
@klimeryk I believe that's a question for @breezyskies, as I just copied her initial post into this issue.

**Comment by klimeryk** [comment]
Ooops, my bad :confounded:
> cc: @rads who I talked to about this in AMS.

I was wondering about that - I've been to Amsterdam with Brie and Rads and I'm _pretty_ sure you weren't there, but since it's such a popular meeting place, I figured maybe it was a different meetup. Now it makes sense :laughing:

**Comment by Tsarpf** [comment]
... And I seem to have completely forgotten about this, sorry. I haven't looked at calypso in ... I guess I could say, months?

**Comment by klimeryk** [comment]
Months? :scream: So you missed the migration to `ASP.NET` and SQL Server? :smirk:

**Comment by breezyskies** [comment]
> is this still an issue for you? I'm guessing the emails already went out

The emails did already go out, but I think this is still worth fixing because: 1) there will future email campaigns, 2) it's not consistent for it to redirect this way (no other section does and it's confusing that you can't link directly to the email tab).

**Comment by klimeryk** [comment]
Roger that :+1: Will keep this one on our radar.

**Comment by umurkontaci** [comment]
@mtias I've done some digging and this looks like this falls under your scope. (client/my-sites/controller.js:251) I've tried a couple of methods that makes it work for our case but many of the consumers of that function assumes `prevPath` is irrelevant and breaks.

**Comment by mtias** [comment]
@umurkontaci the my sites controller should be irrelevant here, the redirect should be handled by the upgrades bulk of route definitions. It seems quite intricate to read through, but the site selection screen is something you define for your path if you want to. I don't see it defined for `domains/manage/email` anywhere.

What I see is a `paths.domainManagementEmail( ':site', ':domain' )` function that accounts for having a site fragment, and then there's a specfic `upgradesController.redirectIfNoSite( paths.domainManagementRoot() )`.

Other sections that want to enable the site selection screen for the no-sites case simply do:

```js
page( '/menus/:site_id', controller.siteSelection, controller.navigation, menusController.menus );
page( '/menus', controller.siteSelection, controller.sites );
```

**Comment by mtias** [comment]
By the way, I think the upgrades/store routes should be cleaned up a bit and separated into smaller chunks that are easier to read and placed at the root of "my sites". I'd imagine groups for "plans", "domains", "checkout", etc, better reflecting the url structures (if you have a root url you should have a root folder section in "my sites").

This will also allow us to break the store into chunks for speedier loading, it's currently one of our biggest bundles. I'd also do more explicit route definitions following other sections in calypso.
