### ISSUE TITLE
Plans rename: update all strings in the Assembler upsell nudges

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85511]
* https://docs.google.com/document/d/1uroYdhgjcQ0DxFFHHdsLF7T7KaQnYyyLWrGJxAsqpWI/edit
* p1703000311938939-slack-C048CUFRGFQ
* PSA: Plan name changes now rolling out to all EN users – Dotcom P2 p58i-gcM-p2

* If possible address these comments too: p1703000913378449-slack-C048CUFRGFQ
  * Unbold the item about the premium themes (which will become Explorer themes)
  * Bold free domain (don't make it green!)

I know it might not be 100% clear how to change wording. Please just make your best guess, any string can be changed later.   Let's prioritize getting a first iteration done over getting it perfect.

**Comment by taipeicoder** [comment]
> - Unbold the item about the premium themes (which will become Explorer themes)
> - Bold free domain (don't make it green!)

Addressed in https://github.com/Automattic/wp-calypso/pull/85527.

**Comment by taipeicoder** [comment]
Currently, the Upsell screen already displays the correct plan name. The term "premium styles" and "premium themes" as left as-is until further discussion.

![Screenshot 2023-12-20 at 3 08 21 PM](https://github.com/Automattic/wp-calypso/assets/797888/55e6d5e7-c997-46df-a4ab-ff858ea10159)

**Comment by taipeicoder** [comment]
@autumnfjeld we can reopen a new task if there's further decision on changing more strings. There isn't any urgency to rename the terms "premium themes", "premium styles", "premium colors", or "premium fonts". As per the doc:



![Image](https://github.com/Automattic/wp-calypso/assets/797888/9a060aa7-4169-48c4-8588-cd0fdb81996f)
