### ISSUE TITLE
The tooltip for "unlocking global styles" doesn't link to the plan needed to buy it

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#85537]
### Quick summary

Noticed while working on #85508 that the Global Styles upgrade "badge" (both regular and theme tier badges) doesn't link to the plan, whereas other badges do. 

GS badge | Premium badge
-------|------
![image](https://github.com/Automattic/wp-calypso/assets/93301/da19cfe2-2518-4cf7-95fd-c9fdb64a0801) | ![image](https://github.com/Automattic/wp-calypso/assets/93301/982405a2-3459-4f41-806f-37c4fcc0c99b)

### Steps to reproduce

1. Be on a free plan
2. Go to /themes
3. Find a free theme
4. Click on one of the GS discs underneath the theme image

This needs to work with the `themes/tiers` feature flag on and off.

### What you expected to happen

The plan name to be linked to the checkout page

### What actually happened

The plan name wasn't linked

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue, the tooltip does not link to the plan:
![Markup on 2023-12-25 at 21:00:42](https://github.com/Automattic/wp-calypso/assets/9025643/c8ca745b-76bd-4579-82f0-e4d0c86515f6)


📌 ACTIONS
– Triaged
