### ISSUE TITLE
Site editor: default site editor view not loading/get frozen

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#85530]
### Quick summary

When checking Appearance > Editor, on some sites, the editor doesn't load and remains frozen.

### Steps to reproduce

I cannot replicate this on my end

### What you expected to happen

To see the editor load the assigned homepage template.

### What actually happened

The editor looked like this:

![image](https://github.com/Automattic/wp-calypso/assets/6737345/ba5fe20f-aa56-436e-8b75-b12617ee1c42)

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I cannot find a pattern for this, but so far, I've seen two cases:

7474554-zd-a8c
7446236-zd-a8c

For the second one, I've tried to replicate this locally by moving the content from there to my test site but that didn't help, which means, there's something not right with the contents of the homepage/index/frontpage template.

Browser console:

![2yWDby.png](https://github.com/Automattic/wp-calypso/assets/6737345/bed1f40a-6bf8-443f-9b93-e7d754422f54)

![uIc6NT.png](https://github.com/Automattic/wp-calypso/assets/6737345/259eec9a-2516-4e76-9147-78c307171c25)

The themes used by the customers are Creatio 2 and Yuga.

Checking their website setup doesn't reveal any weird combination of settings.

As a workaround, they can try accessing the templates directly through Appearance > Editor > Templates > Homepage/Index/Frontpage.

**Comment by jp-imagines** [comment]
Came across this in 7480115-zd-a8c as well (Simple site, Twenty Twenty-Two, default/`Blog Home` homepage)

I see the same `uncaught (in promise)` error, as well as a `GET https://public-api.wordpress.com/wp/v2/users/me?context=edit&_locale=user 404` error. Accessing the homepage template directly from the Templates list does work.

User reported this may have started sometime last Friday (December 15).

**Comment by yuliyan** [comment]
I came across a similar problem in 7479191-zd-a8c. As a temporary workaround, I suggested to the user to select a template from the sidebar after opening the Site editor, which seems to load the components correctly.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm able to replicate this on each of the example sites provided, but not on my own site using any of the affected themes. 
- There is no consistency between theme, Atomic status, template used by the Home page, or any other pattern that I could find. 

📌 ACTIONS
- Triaged

**Comment by jp-imagines** [comment]
Another report in 7488887-zd-a8c (WoA, Outland theme, Blog Home homepage template).

**Comment by renata-franco** [comment]
Got another one: **7598056-zen**. Theme is Twenty Twenty-Three.

**Comment by vinnykaur** [comment]
One more: 7643967-zen 
Theme: Creatio 2

**Comment by jp-imagines** [comment]
Another report in 7614084-zd-a8c. Creatio 2 theme.

**Comment by renata-franco** [comment]
Another: 7662798-zen. Theme Varese.

**Comment by kspilarski** [comment]
Similar case with Nokul theme. 7664033-zen

Workaround: From the editor, click Templates > click the template name, click the pencil icon to edit.

**Comment by druesome** [comment]
7624793-zen

Site is using the Creatio theme

**Comment by saginpj** [comment]
- [ ] 7655938-zen
Theme: Pendant (Premium)

**Comment by kspilarski** [comment]
The same issue with 7726645-zen using the Skatepark theme.

**Comment by syhussaini** [comment]
7737876-zen 
Site uses **Creatio 2** theme

**Comment by Robertght** [comment]
7778296-zen

**Comment by Robertght** [comment]
7762263-zen

**Comment by mgozdis** [comment]
7827298-zd-a8c Creatio2 theme. They say it did not happen until upgrading plan and site went Atomic. They were using a custom Home template. Going to Appearance > Editor Templates > Home works. 

Setting a static Home page instead also allows the Site Editor to load. Deleting the static homepage and reverting back to the Home template, and the Site Editor is also still loading correctly. 

It seems a workaround may be to set a static homepage, delete it, and then the Home template loads fine from Pages > All Pages or Appearance > Editor.

**Comment by cat-og** [comment]
7827706-zd-a8c Pendant theme

**Comment by nazilya06** [comment]
7783000-zd-a8c

Theme: **Tsubaki**

**Comment by jp-imagines** [comment]
Another report in 7833498-zd-a8c (Atomic, Creatio 2). This user also reported that the issue first started after upgrading to Creator (and going Atomic only minutes later).

**Comment by csonnek** [comment]
User in https://wordpress.com/forums/topic/homepage-cycling-to-wordpress-backend/?view=all having a similar issue. They can't open the site editor - it redirects them to their dashboard. Using the Tronar theme

**Comment by Robertght** [comment]
787825448-zen shared the workaround

Theme: George Lois

**Comment by janmckell** [comment]
Another case here: 7907379-zd-a8c 
Theme is Twenty Twenty Three. Default homepage set in Settings → Reading.

**Comment by rinazrina** [comment]
[8058932-zd-a8c](http://a8c.zendesk.com/agent/tickets/8058932)

Atomic, Pendant theme. Deactivating Gutenberg doesn't solve the issue. Provided the workaround.

**Comment by mpkelly** [comment]
I couldn't reproduce this specific issue but after trying a bunch of temples via Appearance > Editor > Templates and then going to Editor > Pages I got a blank screen. Theme is Creatio. There is a React error

![Image](https://github.com/Automattic/wp-calypso/assets/6851384/c967a412-6a8b-49a2-a9a7-3f9467cdab08)

I think this is separate to this issue but logging it here for now. I will continue checking then open a new ticket if necessary. 

Edit. Update:

This is happening because `view` [here](https://github.com/WordPress/gutenberg/blob/8deb8f92a30973c47a3336114893b477f008ffa3/packages/edit-site/src/components/page-pages/index.js#L223) in undefined. But this was a Creator site I created on April 10th that I hadn't taken Atomic. I tried to reproduce it with a new site and I can't.

Update 2:

And sometimes on the same site it works. Seems there are a series of events that breaks the newish editor UI but it's not clear what. Sometimes I see the UI below but other times after clicking around I see the blank screen above. 

![Image](https://github.com/Automattic/wp-calypso/assets/6851384/57413b21-82cb-41de-aeb6-fa160a21464c)

**Comment by rinazrina** [comment]
Another report: 8074958-zd-a8c

Theme: Twenty Twenty-Four

**Comment by mdtanjid0** [comment]
Same issue:

- [ ]  8083199-zen ( needs to be followed up )

Theme name: Twenty Twenty-Three

**Comment by upwardmomentum84** [comment]
Another report: 8092573-zd-a8c

Theme: Boxed Bio

**Comment by jp-imagines** [comment]
Another report in 8079294-zd-a8c on the Assembler theme. Very new site, currently Atomic.

**Comment by philnick206** [comment]
Another report: 8120584-zd-a8c

Theme: Remote

**Comment by mdtanjid0** [comment]
Another report: 8122480-zen

Theme: Hevor

**Comment by i11za** [comment]
Two more user reports: 
- 8060676-zd-a8c / Theme: Twenty Twenty-Four
- 8030392-zd-a8c / Theme: Assembler

Both were simple, unlaunched sites. Publishing the site and setting it to `Coming Soon` resolved the issue.

**Comment by i11za** [comment]
I'm wondering if we've explored Privacy settings being the culprit here. I haven't gone through all the interactions in detail, but noticed a few mentions that the sites experiencing the issue are relatively new. 

I assumed it was a new/unpublished site issue, but it would be curious to check if changing the site's privacy settings would resolve the issue/could be used as a workaround.

**Comment by the-misha** [comment]
Another report: 8130973-zd-a8c
Theme: Varese

**Comment by donalirl** [comment]
Encountered in #8146967-zen on Assembler theme. Continued to occur with all plugins deactivated and cache flushed.

**Comment by vinnykaur** [comment]
#8150495-zen

Theme: Twenty-twenty four

**Comment by lsl** [comment]
@david-binda would you be able to take a look at this and tell me if you think it might be related to fbhepr%2Skers%2Sjcpbz%2Sjc%2Qnqzva%2Srqvg%2Qsbez%2Qoybpxf.cuc%3Se%3Qn77rpo7s%26n%3Qgehr%2366-og ?

**Comment by dsas** [comment]
I'd bet that 'default site editor view not loading' could actually be multiple issues hiding inside a trench coat.

This was reported multiple times per month until May and then just stopped. I've tried half a dozen sites from the linked tickets and can't reproduce it. I wonder if it is still actually a problem?

**Comment by alshakero** [comment]
Looking at the 404, I have a strong feeling that this* middleware is not running in some cases.

Good URL: https://public-api.wordpress.com/wp/v2/sites/181652058/users/me
Bad URL: https://public-api.wordpress.com/wp/v2/users/me

* fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Scyhtvaf%2Sthgraoret-jcpbz%2Sthgraoret-jcpbz-ncvsrgpu.wf%3Se%3Q54o24442%23257-og

**Comment by lsl** [comment]
Closing for now as we can't reproduce.

I reviewed diffs and PR's around that May 1 to May 8 period and didn't see anything that jumped out.

Going to suggest the iframe removal as a project that needs shaping / taking through to completion as I believe that would sidestep dealing with the proxy stuff.
