### ISSUE TITLE
Reader: Remove Edit link for sites I don't have access to

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8554]
Example: https://wordpress.com/read/feeds/53669030/posts/1176370841

I see an Edit link in full-post giving the impression that I can actually edit the page:

![screenshot 2016-10-06 10 14 46](https://cloud.githubusercontent.com/assets/4924246/19162691/c68d931a-8bad-11e6-962e-a8a08b993c6b.png)

Clicking on it only takes me to the Site Picker:

![screenshot 2016-10-06 10 15 26](https://cloud.githubusercontent.com/assets/4924246/19162731/eb1932c0-8bad-11e6-8d60-855fcacb31eb.png)

**Comment by jancavan** [comment]
Apparently a non-issue. Closing this.

**Comment by bluefuton** [comment]
Just to clarify why this appeared for @jancavan: if you've got superadmin permissions, you see the Edit link on all wordpress.com posts.
