### ISSUE TITLE
Improve the Global Styles upsell modal

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#85541]
We could improve the modal that includes the price of the plan, similar to the proposal for premium themes. Similar but not exact, the main part of the modal should keep the two buttons, and the specific text in the left part of the existing modal.

Current | Premium themes
-------|------
![Image](https://github.com/Automattic/wp-calypso/assets/93301/6dfd90d5-8d1b-4acc-8c22-060d4a781538) | ![Image](https://github.com/Automattic/wp-calypso/assets/93301/a34e59bd-b1a0-4db9-94b6-90911730c1db)

Here's a figma link for the premium themes modal : fyDEPzt5jnfwaOr5EHCV4Y-fi-74:21756#651424463 

Here's where we do something similar in the Assembler flow wrt getting and displaying the https://github.com/Automattic/wp-calypso//blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-upsell.tsx#L20

See suggestion from @lucasmendes-design : p1702301656648619-slack-C048CUFRGFQ Assembler flow

## Repro steps
1. Go to wordpress.com/start
2. Go through the process using a free domain and the free plan
3. When you get to the theme selection page, click a theme with style variations (has circles underneath it)
4. Once the page loads, choose one of the style variation "microwaves", not the default one.
5. Press "Continue". The dialog should appear.

It's worth checking if the dialog is used in other places too.

**Comment by dsas** [comment]
This _might_ make a good first issue, or it might turn out to be a total pig.

**Comment by niharikamahajan02** [comment]
I am getting following after yarn start command. Could you please suggest (http://calypso.localhost:3000/) is showing following 
![image](https://github.com/Automattic/wp-calypso/assets/72392580/93e6391e-cc02-4a35-90a2-49b07f6cf03d)

**Comment by dsas** [comment]
@niharikamahajan02 hi 👋 , did you wait for webpack to finish compiling before refreshing? Did it show any errors in the terminal?

**Comment by dsas** [comment]
Hey @niharikamahajan02 sorry you didn't get your problem sorted out, as it's been about a week, we'll pick this up and run with ourselves. Thanks for the offer of help though, there are other good first issues around.

**Comment by niharikamahajan02** [comment]
> Hey @niharikamahajan02 sorry you didn't get your problem sorted out, as it's been about a week, we'll pick this up and run with ourselves. Thanks for the offer of help though, there are other good first issues around.

ya sure but just for some other issues to solve I wanted to know following is coming after running yarn start command do I need to wait for a long time for it to get ready as this msg is just being shown again and again.
![image](https://github.com/Automattic/wp-calypso/assets/72392580/28f25fd9-e198-45f2-bf46-2e1ebfc93737)

**Comment by dsas** [comment]
It depends on your computer how long it takes. It looks from your screenshot that it takes fifteen minutes, it takes about a minute or two on my M2 macbook and I don't think took more than five minutes on my 2021 macbook. 

Have you [double checked the pre-reqs](https://github.com/Automattic/wp-calypso/blob/trunk/docs/install.md#prerequisites)?

It might be worth trying a [limited build](https://github.com/Automattic/wp-calypso/blob/trunk/docs/install.md#limited-builds) so that it's doing less at one, just to see if it ever finishes.

**Comment by niharikamahajan02** [comment]
> It depends on your computer how long it takes. It looks from your screenshot that it takes fifteen minutes, it takes about a minute or two on my M2 macbook and I don't think took more than five minutes on my 2021 macbook.

> Have you [double checked the pre-reqs](https://github.com/Automattic/wp-calypso/blob/trunk/docs/install.md#prerequisites)?

 yes I did double check the pre-reqs.

> It might be worth trying a [limited build](https://github.com/Automattic/wp-calypso/blob/trunk/docs/install.md#limited-builds) so that it's doing less at one, just to see if it ever finishes.

Ok sure I will try through this and I think I should wait for some more time
