### ISSUE TITLE
Refreshed Cards: Prefer first usable media

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8555]
Currently, when a post has no featured image, and the post contains both an image and a video, the video is preferred when it comes to display something on the stream card.

In other words, a post with no featured image, that contains both an image and a video, will display the video in the followed stream.

I suggest we change this to prefer the **first usable media** in the post. ("Usable" because if the first image is less than 350px wide/tall, we'd skip it as now.)

WHY: It reinforces the user's click/tap. IE: I see a photo of a duck, I click/tap the card, and now I see the fullpost with that same duck in the page. That connection is reassuring. It can be confusing if I click on something with one image and then see another at the top of the post.

Easy-ish to change?

**Comment by samouri** [comment]
Easy-ish!

**Comment by samouri** [comment]
ToDo:
- [ ] surface `content_media`: an ordered list of images/videos
- [ ] refactor safe-images / safe-embeds
- [ ] add/update unit tests 
- [ ] make refresh-post-card pick first eligible item from `content_media`

**Comment by samouri** [comment]
Going to close this now.
- Issue to create more unit tests: #9315
- the get-video-id checkbox can be figured out when we add more video source support
