### ISSUE TITLE
Assembler CTA: update graphic 

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85591]
# Description

We'll likely be changing this graphic frequently.  See p1703074997937099/1703074429.249509-slack-C048CUFRGFQ

CURRENT:

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/e99046ab-0673-4f6e-85a6-09192f069da0)

PROPOSED:

![image](https://github.com/Automattic/wp-calypso/assets/5665959/5da411ab-3947-4940-9567-9104bddd3242)

See comment below with info from Matt West. 🤩

**Comment by lucasmendes-design** [comment]
Since I'll not have the time to finish this. Let's ping @matt-west  :)

**Comment by matt-west** [comment]
Here’s an updated design for the Assembler CTA using the bolder colors.

Design: Tv3pYqA3EcRfiXC31IxrXE-fi-3511_2925

![image](https://github.com/Automattic/wp-calypso/assets/417538/028c308c-bdbb-4da2-b7c5-eeed52d8a7f2)

**Comment by arthur791004** [comment]
Proposing https://github.com/Automattic/wp-calypso/pull/85966 to update the design of the Pattern Assembler CTA 🙂

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/85966
