### ISSUE TITLE
Image resizing not working on accordeons

### ISSUE THREAD

**Issue by macavalen** [Automattic/wp-calypso#85634]
### Quick summary

Images are not being resized on the published version

![image](https://github.com/Automattic/wp-calypso/assets/154519722/a947d425-8c7e-4920-a678-74b25e197c5b)

### Steps to reproduce

1. Go into https://academy.avvoka.com/advanced-automation-lesson-two/ 
2. See how the image on the first accordeon is very big. 
4. Turn on builder, image will display in the desired size.
5. Click on edit the accordeon
6. Try resizing by dragging the image, or resize it on the Text option. Image will seem like it is on the desired size
7. Save, all looks good
8. Then make sure you update the draft and preview or view the published version, IMAGE WILL NOT BE RESIZED AND WILL BE TOO BIG

VIDEO: https://vimeo.com/manage/videos/896852866/624756f3fe?extension_recording=true 

### What you expected to happen

Changes to image resizing should stick

### What actually happened

changes are not sticking after publishing and images looks very big and not resized. We cant publish this content with images not mantiainng the size and we are stuck

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 ACTIONS
- Closed as not related to WordPress.com/Calypso

📌 Message to Author
@macavalen you've reached out to the Github repository for WordPress.com's hosting interface, Calypso, which is not related to the issue you're having, as your site https://academy.avvoka.com/ is not hosted on WordPress.com and it is not using any WordPress.com-developed products.

From what I could check in the code of the page you sent as an example, the tool you're using to build that page is from Themefy, so I recommend reaching out to them at https://themify.me/contact for support. For other WordPress-related issues, you can also ask for help from the community in the WordPress.org forums https://wordpress.org/support/forums/.

If you're looking for a new host for your site, you'll find all the info you need about moving to WordPress.com here: https://wordpress.com/move
