### ISSUE TITLE
Featured Images Not Showing On Live Page With Query Loop or Blog Posts Block

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#85672]
### Quick summary

Featured images not showing for posts on the live version of pages that use the Query Loop or Blog Posts block.

How the page looks in the editor:

![Editor-FeaturedImages](https://github.com/Automattic/wp-calypso/assets/93800099/7aecdccb-0a9f-4b6d-88fa-ad99e1da00e5)

How the page looks on the live URL:

![LivePage-FeaturedImagesNotShowing](https://github.com/Automattic/wp-calypso/assets/93800099/1fd62d81-31fb-4de1-ae76-78faf73683ea)

### Steps to reproduce

1. Add a Blog Posts block or Query Loop block to a page.
2. Set the block to show featured images of posts.
3. Observe the editor shows the featured post.
4. Observe the live page doesn't show the featured image.

### What you expected to happen

The featured image to show on the live version just like it does in the editor.

### What actually happened

The featured image doesn't show.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Replicated on Alves theme as well as Varia.

Could not replicate on atomic sites.

Reported here: 7484939-zd-a8c

**Comment by caitlindawn** [comment]
Encountered in 7488908-zen (Hever theme)

**Comment by Greatdane** [comment]
Accounted here in Maywood;

7490062-zd-a8c

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Replicated
– Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my test site:
![Markup on 2023-12-26 at 21:03:46](https://github.com/Automattic/wp-calypso/assets/9025643/351470fc-1e08-4131-8ee4-cc3b3f9be0c0)


📌 ACTIONS
– Triaged

**Comment by OmarFPG** [comment]
7498895-zen

**Comment by Mfarroq1** [comment]
7499612-zen 
7497457-zen

**Comment by Aurorum** [comment]
This isn't an issue within the Varia theme - it affects other themes too (eg. Canard). 


| Enabled | Disabled |
|--------|--------|
| <img width="1567" alt="Screenshot 2023-12-16 at 12 04 38" src="https://github.com/Automattic/wp-calypso/assets/43215253/fa343c3d-c37b-4ac3-a423-47c9cda03081"> | <img width="1527" alt="Screenshot 2023-12-16 at 12 04 24" src="https://github.com/Automattic/wp-calypso/assets/43215253/d3009312-d229-4b9c-995d-da16225e7e71"> |

The problem is how Jetpack's Content Options interacts with the blocks, whereby it overrides the settings configured manually within the block. 

Duplicate of Automattic/jetpack#29286

**Comment by OgeAmadi** [comment]
7503239-zen 👉 This is with the Redhill theme (_it's retired_)

**Comment by jerren1327** [comment]
7502636-zen
Shawburn Theme

**Comment by rw-ye** [comment]
7516017-zd-a8c 

Theme: Hever

**Comment by upwardmomentum84** [comment]
Reported here with Shawburn:

7523335-zd-a8c

**Comment by zdenys** [comment]
7527347-zd-a8c Fixed by enabling  Display on pages in Customizer.

**Comment by deancroyal** [comment]
7516017-zd-a8c fixed by enabling "Display on pages" in Featured Images setting in Customizer > Content Options

**Comment by CacheMeOwside** [comment]
Another report here - 7530489-zd-a8c (Barnsbury theme)

**Comment by ckmccoy2** [comment]
Another on Maywood theme (7540409-zd-z8c), also fixed per deancroyal's suggestion or enabling "Display on pages" in Featured Images setting in Customizer > Content Options

**Comment by adelineyaw** [comment]
Another report (Hever Theme) - 7549647-zd-a8c

**Comment by CacheMeOwside** [comment]
Another report (Redhill theme) - 7555462-zd-a8c. Suggested zdenys fix.

**Comment by jerren1327** [comment]
7562207-zen Dara theme
