### ISSUE TITLE
NUX: navigation links aren't center-aligned

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#8567]
![](https://cloudup.com/cqzNiszAHnb+)

From @lancewillett:

> When on [signup] steps with both Back and Next links — Firefox shows them as misaligned, not on the same horizontal baseline (Safari and Chrome seem fine)
#### Steps to reproduce
1. Starting at URL: wordpress.com/start on Firefox
2. Go through signup steps, keeping an eye on the back & skip links on the bottom of some steps
3. Notice misalignment

**Comment by iamtakashi** [comment]
![screen shot 2017-01-05 at 11 28 59](https://cloud.githubusercontent.com/assets/908665/21679139/361133da-d33a-11e6-9965-d38f00176a48.png)

I can confirm this has been fixed. Closing.
