### ISSUE TITLE
Live Preview: The "Activate & Save modal" is opened unexpectedly

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#85682]
### Quick summary

The "Activate & Save modal" is opened unexpectedly by using the shortcut in the Live Preview in premium/Woo themes flow. See pekYwv-3xz-p2#comment-2800.

### Steps to reproduce

- Go to the canvas edit mode, and make any changes.
- Switch to the canvas view mode, and press cmd + S which is the shortcut for the Save/Upgrade Now button.
- See the Activate & Save modal being opened together with the Upsell modal.

### What you expected to happen

The "Activate & Save modal" is never opened.

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/85687
