### ISSUE TITLE
Live Preview: The Upgrade Flow in A New Tab

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#85683]
# What

Currently, when a user clicks on the 'Upgrade' button, they are redirected to the checkout page, and If they complete the purchase and then return to the Site Editor, any changes made before clicking the 'Upgrade' button are lost and not recoverable. It would be beneficial to preserve these changes throughout the flow. 

pekYwv-3xz-p2#comment-2741

# How 

We'd like to update the flow by opening a new tab, rather than a whole page transition. The overall flow is as shown below;

- The user clicks on the Upgrade button on the modal. 
- Open the checkout page in a new tab. 
- Periodically check to see if the user plan has changed.
- The user completes the purchase.
- Automatically close the checkout page tab once the user completes their purchase.
- The user returns to the Site Editor and sees a message like: “Your plan has been upgraded. You can now activate it” upon detecting the upgrade from a separate tab.

## Why not just save the changes?

If we aim to “save” the user’s changes, we need to consider:

- Preventing users from modifying site content (e.g., the site title), as it impacts the users’ live site.
	- If restricting content changes is not feasible, the function of a “Save” button becomes ambiguous. What should happen upon clicking it? Should we save only theme customizations, or include site content as well? How do we clearly communicate this to users?
- Should we preserve the user’s changes if they exit the flow post-upgrade but without activating the theme?
	- If we decide to persist the user’s change, we should revisit https://github.com/Automattic/wp-calypso/issues/81119#issuecomment-1831307892. For instance, do we need a “Reset your customizations” feature to enable starting edits from scratch?
	- Conversely, if we choose not to preserve changes when the user exits the flow, we will have to reset their changes upon leaving.
	- Or should we activate the theme simultaneously when upgrading it? pekYwv-3xz-p2#comment-2752

# Related

**Comment by taipeicoder** [comment]
Closing this via https://github.com/Automattic/wp-calypso/pull/85771.
