### ISSUE TITLE
Year in Review: Update "Your Web" logo to "Your site"

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#85693]
### Details

At present, the LP for WordPress.com pages uses an SVG image with the wording "Your Web". We want to change this to "Your Site" at the very least. We would also like to have the wording translated, which may be much more effectively done using HTML and CSS for the background pill, and only using SVG for the Jetpack and WordPress.com.

### Checklist

- [ ] Year in Review LP has the correct wording for "Your Site", and the strings can be translated

**Comment by valterlorran** [comment]
I'm tackling this issue here: D133046-code

**Comment by valterlorran** [comment]
We are closing this because we deployed D133046-code.
