### ISSUE TITLE
Error message: Trying to initialize anonId outside of a browser context.

### ISSUE THREAD

**Issue by 17Ayaan28** [Automattic/wp-calypso#85745]
### Quick summary

Hi
I am new to the repo and want to contribute. I was trying to set up development on my mac and ran into the above error. I followed instructions in readME to setup. I can't find any solutions in troubleshooting.md

![Screenshot 2023-12-25 at 2 09 16 pm](https://github.com/Automattic/wp-calypso/assets/61399823/ba36a093-95fc-4fdf-9fe5-d323a65fcd7e)
![Screenshot 2023-12-25 at 2 10 04 pm](https://github.com/Automattic/wp-calypso/assets/61399823/01985328-2bb2-40e6-ad90-7643a83300ca)

thanks

### Steps to reproduce

 Node version 20.8.1, yarn v 4.0.2
1. Clone the repo
2. Added 127.0.0.1 calypso.localhost to hosts file
3. ran yarn
3. ran yarn start
4. After encountering the error below I tried with sudo and searched for a solution but couldn't find anything.

### What you expected to happen

I expected that I will be able to see calypso front end

### What actually happened

After running yarn start this error message appears : 

![Screenshot 2023-12-25 at 2 15 58 pm](https://github.com/Automattic/wp-calypso/assets/61399823/5ebad8b3-03f9-4b04-81ab-95879d951831)

then the following message appears

`03:13:28.936Z  INFO calypso: wp-calypso booted in 4473ms - http://calypso.localhost:3000`

The following screen appears in the browser when I go to the address

![Screenshot 2023-12-25 at 2 18 06 pm](https://github.com/Automattic/wp-calypso/assets/61399823/0fb30339-418a-4e6a-b961-8a895198dc93)

Then, I start seeing a bunch of logs - 

![Screenshot 2023-12-25 at 2 15 10 pm](https://github.com/Automattic/wp-calypso/assets/61399823/735e6ea3-dccc-4318-bc54-1b3eb11d9894)
4948846723)

after some time, I get the following js stack trace

![Screenshot 2023-12-25 at 2 19 08 pm](https://github.com/Automattic/wp-calypso/assets/61399823/ff313b26-4087-4432-be01-9891a1383898)

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by noahtallen** [comment]
Hi! The first `anonId` warning is currently expected locally, and shouldn't impact anything. The second issue means that you need to give NodeJS more memory. You can do that with this environment variable:

```sh
export NODE_OPTIONS="--max-old-space-size=8192"
```

I'd add that to your .zshrc (or bashrc). I have it set to a much higher value, because I'm ok allowing NodeJS to consume a lot of memory for development purposes locally.
