### ISSUE TITLE
Media library pop-up shows a smaller search field when using classic view 

### ISSUE THREAD

**Issue by Neha93517** [Automattic/wp-calypso#85746]
### Quick summary

A user reached out with a screenshot of Media library upload window with a smaller search field. Identified the issue to be with classic view. Here's the screenshot from the user
![utf-8''Screenshot-2023-12-22-at-2 50 13 PM](https://github.com/Automattic/wp-calypso/assets/54591499/fd366fa0-d4c9-4bf1-b5e8-38d1a436102d)

### Steps to reproduce

1. Log in to dashboard
2. Go to Pages
3. From the top right, change the view to classic
4. Open any page to edit
5. Click the plus icon and add image block 
6. Choose 'Select option'

### What you expected to happen

Normal media upload window 

### What actually happened

The media upload window shows the search bar smaller than usual

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

User's plan is Creator, however, I have tested his with other plans and different themes. So, the issue is not theme or plan specific

**Comment by OmarFPG** [comment]
7489266-zen wrote back to report the bug is also present when using the classic view (Calypso) and Blocks Editor. Tested on both pages and posts on my HC site and I can confirm.

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I have followed the steps and was not able to replicate the issue both on in the block and classic editor:
![Markup on 2023-12-26 at 21:08:32](https://github.com/Automattic/wp-calypso/assets/9025643/a09e8341-6e0a-4ce6-b815-9f4170ca0847)
![Markup on 2023-12-26 at 21:09:49](https://github.com/Automattic/wp-calypso/assets/9025643/d6a8efe1-152e-48a1-b461-55bd60c64461)

📌 ACTIONS
– Requested author feedback


📌 Message to Author:
Hi @Neha93517 & @OmarFPG 👋 
Does the error still occur on your side? Are you able to share more details about your setup and some examples of the issues that are live to check?

**Comment by OmarFPG** [comment]
Hi @maciejpilarski here's a quick test both on Simple and Atomic sites:
https://share.zight.com/KouKzqpY

Windows 11 Home edition and Google Chrome Versión 120.0.6099.130 (Build oficial) (64 bits)
![image](https://github.com/Automattic/wp-calypso/assets/122303439/8905cfe7-15ae-48d1-bc1d-2df5dab5b183)
![image](https://github.com/Automattic/wp-calypso/assets/122303439/32bf0e34-1c90-44d3-b63f-86c8438eabe5)

Edit: just updated Chrome to the latest version, still same issue.

**Comment by jeremyfelt** [comment]
I'm seeing this issue when I visit the media library directly and when I choose to replace media in an existing post and the media library opens.

At first glance, it seems that the hard-coded width and height in the FSE plugin's `help-center.css` are causing the issue.

I'm on the latest Firefox and Mac OS.

<img width="857" alt="Screenshot 2024-04-10 at 7 53 57 AM" src="https://github.com/Automattic/wp-calypso/assets/286171/63e17c4b-d351-4269-8ac1-4eb4ff3861d1">
<img width="1044" alt="Screenshot 2024-04-10 at 7 52 56 AM" src="https://github.com/Automattic/wp-calypso/assets/286171/4e5c2ca5-3bac-4bff-a13c-f4282fb7b9ee">
<img width="367" alt="Screenshot 2024-04-10 at 7 55 06 AM" src="https://github.com/Automattic/wp-calypso/assets/286171/f8d8c72e-f4b9-4652-a458-cac6df7a171f">

**Comment by taipeicoder** [comment]
Closing as the issue cannot be replicated. Please reopen otherwise.
