### ISSUE TITLE
New post notification emails use large images that are blurry when a gallery is added in the classic block

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/wp-calypso#85753]
### Quick summary

Notification emails for new posts contain large images that are blurry even if the gallery size settings is set to medium.

### Steps to reproduce

1. Create a new post with the Classic block
2. Add a gallery in the classic block and set the size to medium
3. Publish the post and notice the size of the images used in the post notification email.

### What you expected to happen

The images in the new post notification email should not be large and blurry

### What actually happened

The images in the post notification email were large and blurrynew 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported here 7462949-zd-a8c

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO

### Simple
This doesn't seem to be related to the image size chosen for the images - just to how the newsletter service is handling Galleries inside the Classic Block.

The emails are rendered in content container that is 576px wide, but the images being pulled are 560px wide, causing them to stretch to fit the 100% width of the container:

![CleanShot 2023-12-26 at 10 51 31@2x](https://github.com/Automattic/wp-calypso/assets/14153300/9182d66a-1ad8-4b2e-a380-624a079aeaf0)

### Atomic

The first image in the library loads at 750px inside the same 576px container, so it doesn't look blurry, but the rest of the images don't load at all:

![CleanShot 2023-12-26 at 11 16 36@2x](https://github.com/Automattic/wp-calypso/assets/14153300/e7c05a4b-4b3c-4a1f-b8ea-d983bfbf0b26)


📌 ACTIONS
- Triaged
- Switching Pri to Low considering the combo Classic Block + Gallery is not common

📌 Message to Author
@poeticabdul ask your customer to switch to the Gallery Block and set Reading Settings to "Full text" as a workaround

**Comment by Jaccuse** [comment]
7462949-zen

**Comment by mmtr** [comment]
Looks like the issue has been resolved at some point, I cannot longer reproduce it:

![Image](https://github.com/user-attachments/assets/66c1f34d-6be4-4e7b-a231-19bd691244cf)
