### ISSUE TITLE
Help Center: Site picker's list stuck in absolute position

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#85796]
### Quick summary

The site picker in Help Center (visible in Forums form) is stuck in absolute position when scrolling.
Best to see it in video:

https://github.com/Automattic/wp-calypso/assets/3392497/02b94389-e105-4d4b-b650-ad02de137e33

It's not impacting the direct ability to select items from the list. But it can be very confusing when the list appears in a different part of UI.

### Steps to reproduce

1. Open Help Center on a Free site and select Forums support channel.
2. The contact form should now have the Site picker.
3. Click on the list to expand it.
4. If you scroll now (or scroll a bit before expanding it), the expanded list will stay in its absolute position.

### What you expected to happen

The list would scroll/stay connected to the site picker.

### What actually happened

The list stays in place while the rest of the form is scrolled.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Found while testing #85639.

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated  
- Tested on Atomic – I can't replicate it because the site selector itself is missing. Test on 2 different sites

https://github.com/Automattic/wp-calypso/assets/13706336/68f1ae20-fe64-4f13-bd4a-c46471975e61
 
## 📌 ACTIONS ##
Triaged

**Comment by taipeicoder** [comment]
@mrfoxtalbot do you know if this UI is still accessible now that we have Wapuu when users click on the "Still need help" button?
