### ISSUE TITLE
why i can't use markdown to write my blog

### ISSUE THREAD

**Issue by HIKALU-Z** [Automattic/wp-calypso#858]
i have seen [this page](https://en.support.wordpress.com/can-i-use-markdown-on-wordpress-com/)
it is said:
> go to Settings → Writing in your dashboard, and check the box labeled Your posts will be run through the Markdown text processor

but why I can't find this option,at my wordpress it only can choose `uncategorized`.
 hoew can i slove this problem?

**Comment by umurkontaci** [comment]
Hi there, this is the development platform for WordPress.com, please head over to https://en.support.wordpress.com/contact/ for support requests.
