### ISSUE TITLE
Features list on checkout when buying Sensei Bundle should match at least features from the Sensei plan

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#85803]
### What

Features list on checkout when buying Sensei Bundle should contain at least features from the Sensei plan.
Notice that it's a very low priority issue, since we are planning to not display the plans step when users are coming from senseilms.com (https://github.com/Automattic/wp-calypso/issues/85170).

Sensei Plans page:

![screenshot-2023-12-19-at-15 53 39](https://github.com/Automattic/wp-calypso/assets/876340/dbb4c25b-7faa-4082-aa50-3fa737b0f34b)

Features on checkout:

![screenshot-2023-12-19-at-15 53 21](https://github.com/Automattic/wp-calypso/assets/876340/a9fefa7e-5a76-431c-b972-e4f96650fcfd)

### Why

Initially, we display what we are selling to the user, but when they are about to complete their purchase, we display a different list of features, which might be confusing.

UPDATE: Let's update the features under _Included with your purchase_ to match the features that are listed on the Plans page.

### Context

p6rkRX-74d-p2

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated
- 
📌 FINDINGS/SCREENSHOTS/VIDEO
Steps:

1. Go to https://senseilms.com/pricing/ and select "Create a site"
2. After the design and domain picker screens, the flow will show:

![CleanShot 2023-12-28 at 10 15 07@2x](https://github.com/Automattic/wp-calypso/assets/14153300/d20c90c0-6599-445c-ae04-1c9858ab7b60)

3. The Checkout screen will list only features included in the Creator/Business Plan and none from Sensei Pro
![CleanShot 2023-12-28 at 10 16 06@2x](https://github.com/Automattic/wp-calypso/assets/14153300/3cb62da4-592e-4cec-88a6-afadb85afe92)


📌 ACTIONS
- Triaged

**Comment by donnapep** [comment]
Bumping to normal priority as the user can enter this flow from other places besides SenseiLMS.com.

**Comment by donnapep** [comment]
I think it would be best to have the Features list on the checkout page match the features on the Plans page. Note that the features are a bit different depending on whether Monthly or Annually is selected.

**Comment by m1r0** [comment]
This is done. The checkout features list was updated to be the same as the one on the Plans page. (https://github.com/Automattic/wp-calypso/pull/86707)

I also had to do some refactoring to allow for the code to be re-used.
