### ISSUE TITLE
Redirect the user to Sensei Home after the Sensei onboarding

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#85805]
## What

- After completing the onboarding flow, redirect the user to the Sensei Home instead of My Home.
- https://github.com/Automattic/wp-calypso/issues/85270 is also important for this issue.

## Why

In Sensei flow, the Sensei actions are more important to the user.

## Context

p6rkRX-74d-p2

**Comment by donnapep** [comment]
I agree that this is something we should consider doing. I went through the ecommerce onboarding flow and they take the user directly to `wp-admin` afterwards. Going directly to `wp-admin` could also help with the problem of the user being bounced around between Calypso and WP admin during onboarding. Will try to find out more about any potential downsides of this approach.

**Comment by donnapep** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/86546.
