### ISSUE TITLE
Design Picker: missing right padding on mobile

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#85817]
## What

On the Design Picker on mobile, the right padding seems missing.

![Image](https://github.com/Automattic/wp-calypso/assets/1881481/f6e164a5-688d-4a5d-a8a2-79837041e466)

## Why

For a more balanced design.

## How

Add the same padding as on the left side.

**Comment by taipeicoder** [comment]
Closing via #86091.
