### ISSUE TITLE
Tools > Import does not allow eligible plans to import

### ISSUE THREAD

**Issue by vishnugopal** [Automattic/wp-calypso#85824]
See discussion here: p1703753973556079-slack-C7YPW6K40 

![Image](https://github.com/Automattic/wp-calypso/assets/533/bd42f663-6223-449d-b724-439e5ef5a753)

![Image](https://github.com/Automattic/wp-calypso/assets/533/7e9a2ce8-fbbe-4e69-a753-607634ebeb9d)

**Comment by vishnugopal** [comment]
Just a note that we need to upsell the right plan also, for Woo trials, we need to upsell Essential or Performance Woo, see: p1703754666252269-slack-C03Q87XT1QF

**Comment by bogiii** [comment]
Just one question: should we work on this if we plan to replace the Tools/import with an import onboarding experience done in https://github.com/Automattic/wp-calypso/pull/85830 ?

**Comment by ouikhuan** [comment]
> Just one question: should we work on this if we plan to replace the Tools/import with an import onboarding experience done in https://github.com/Automattic/wp-calypso/pull/85830 ?

I think the answer here is probably yes, see @vishnugopal's original request here: p1704878454419509-slack-C01A60HCGUA. It still takes some time for us to finalize the new proposed solution and the request for addressing related plans (especially Entrepreneur ) has been increased lately. 

It shouldn't be too difficult to implement this, so even if this will disappear soon, it's still worth doing it. ll start to get on this tomorrow.
