### ISSUE TITLE
Navigation Block: Overlay Menu toggle not opening on Classic Themes

### ISSUE THREAD

**Issue by Neha93517** [Automattic/wp-calypso#85826]
### Quick summary

The issue first reported here: 7467270-zen.
 The mobile menu for the site studiotec.info is not working. 
 
Identified the issue to be theme related, and only seems to affect sites using certain themes. For example, Organizer, Rivington or Balasana are broken, as per tests by HE Adrian Gomez 
 
The menu is collapsed, but the element cannot be clicked.

![image](https://github.com/Automattic/wp-calypso/assets/54591499/e0bd17c8-fb97-4573-8d68-dcd42af3bfa3)

### Steps to reproduce

1. Go to the site in Zen - 7467270
2. Inspect the element and toggle device icon
3. Click on the hamburger menu

### What you expected to happen

The menu should open

### What actually happened

The menu is collapsed and the links are inaccessible

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

User reached out for update here: 7505440-zen.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Local site

https://github.com/Automattic/wp-calypso/assets/14153300/cc9e1546-ad14-4f91-8ec5-3fef4a41770a

📌 ACTIONS
- Triaged
- Updated the title to be more descriptive
- Reported upstream: https://github.com/WordPress/gutenberg/issues/57428

**Comment by OmarFPG** [comment]
I saw a case like this last week (7431676-zen) where the issue is with the Gutenberg plugin, but this is a simple site, so I can't instruct the user to disable the plugin.

**Comment by fresatomica** [comment]
There's another instance here: https://wordpress.com/forums/topic/mobile-browser/
Also a simple site.

**Comment by mgozdis** [comment]
AT site where deactivating Gutenberg worked: 7503436-zd-a8c

**Comment by pauljacobson** [comment]
There is a duplicate issue here: https://github.com/Automattic/wp-calypso/issues/85441

**Comment by cuemarie** [comment]
Looks like this is hopefully fixed in Gutenberg 17.4: https://github.com/WordPress/gutenberg/pull/57396

**Comment by suyogyashukla** [comment]
Friends - can someone confirm this is fixed now? I have a user who is still facing this issue in 7505440-zd-a8c

Edit: Nvm, ignore this ^ - the user responded back saying it's working now.

**Comment by liviopv** [comment]
Marking this as fixed, I can no longer reproduce.
