### ISSUE TITLE
Calypso is not allowing custom file mime types allowed by wp-admin

### ISSUE THREAD

**Issue by matiasbenedetto** [Automattic/wp-calypso#85833]
### Quick summary

If you add a custom mime type to the allowed mime types in WordPress using the [`upload_mimes`](https://developer.wordpress.org/reference/hooks/upload_mimes/) filter (as [done by the `wp-extra-file-types`](https://plugins.trac.wordpress.org/browser/wp-extra-file-types/trunk/wp-extra-file-types.php#L490) plugin), it will work in wp-admin, but not in the Calypso interface.

### Steps to reproduce

1. Go the media library of a Wordpress atomic website.
2. Try to upload a file with a mime type not allowed by default.
3. Check that it fails.
4. Install a plugin that uses the [`upload_mimes`](https://developer.wordpress.org/reference/hooks/upload_mimes/) filter [like wp-extra-file-types does](https://plugins.trac.wordpress.org/browser/wp-extra-file-types/trunk/wp-extra-file-types.php#L490) to add the mime type of the file you want to upload.
5. Try to upload the file using the calypso interface living in `https://wordpress.com/media/<YOUR SITE URL>` and check that it fails.
6. Try to upload the file using the wp-admin interface living in: `<YOUR SITE URL>/wp-admin/upload.php` and check that it works.

### What you expected to happen

It you added a custom mime type to the allowed mime types it should work in both wp-admin and calypso interface.

### What actually happened

The added mime type is only allowed on wp-admin but not in calypso.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

The workaround for this problem is to use wp-admin instead of the wordpress.com default interface for the media library, but there's no way for the users to know that. You need to navigate the wp-admin manually by writing the URL in the browser navbar.

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated 


📌 FINDINGS/SCREENSHOTS/VIDEO
1. I have installed the https://wordpress.org/plugins/wp-add-mime-types/ plugin.
2. Added the MIME type to the plugin settings svg	= mage/svg+xml
3. Tried to upload an SVG file via Calypso - did not work
4. Tried to upload the file via WP-Admin Media section - was able to upload the file.
![Markup on 2024-01-01 at 17:20:47](https://github.com/Automattic/wp-calypso/assets/9025643/8b7dabd8-6114-4cad-8474-59d43a1ac463)
![Markup on 2024-01-01 at 17:20:13](https://github.com/Automattic/wp-calypso/assets/9025643/5d9a6442-5ebb-424b-8436-50defe03b809)


📌 ACTIONS
- Triaged

**Comment by bogiii** [comment]
I tried to reproduce the issue, and I can confirm that it has been fixed in the meantime.
If the user accesses its Atomic site from the Calypso interface and clicks on Media library, it redirects to the wp-admin media library.

![jqA42Y.gif](https://github.com/user-attachments/assets/869247f1-67a4-4a01-934f-11e95f0fccba)
