### ISSUE TITLE
Live Preview: persist theme showcase filters on return from Live Preview

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85848]
If I select premium blogs in the Showcase filters and then go to "Preview & Customize", when I return to the Showcase  the same filters should be applied.

@Automattic/lego

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/jetpack/pull/34836 & https://github.com/Automattic/wp-calypso/pull/85927 🙂
