### ISSUE TITLE
Like widget: clicking on the like number doesn't open the popover

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#85853]
"85 likes"

Only clicking on "likes" opens it, clicking the number does nothing.

**Comment by ivan-ottinger** [comment]
I am looking into this task now.

**Comment by ivan-ottinger** [comment]
D133387-code is now ready for review.

**Comment by ivan-ottinger** [comment]
The issue is now fixed with D133387-code and D133401-code.
