### ISSUE TITLE
YIR: On some devices the layout breaks

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#85865]
On some android devices, like the Samsung Galaxy s10 the layout breaks:
<img width="560" alt="image" src="https://github.com/Automattic/wp-calypso/assets/375980/ac0e6477-3ce7-45b3-8274-8839e3d7a027">

I've tested on a Galaxy s23 and it looks correct.

**Comment by foleynotrose** [comment]
I have the same broken layout issue on my Samsung Z Flip4
![Screenshot_20231231_084535_Chrome](https://github.com/Automattic/wp-calypso/assets/26651984/7c6ce0c8-6723-4f4e-9b6c-cb2e14857fe3)

**Comment by sixhours** [comment]
This is unlikely to be fixed within the next year, closing.
