### ISSUE TITLE
YIR: Referrer string going out of viewport in on mobile.

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#85864]
CSS is cropping the string for the Traffic source part. This can be reproduced in Safari when making the viewport narrower.

<img width="577" alt="image" src="https://github.com/Automattic/wp-calypso/assets/375980/b6d7af2a-9298-4d20-b158-ba625c9aa82b">

**Comment by sixhours** [comment]
This is unlikely to be fixed within the next year, closing.
