### ISSUE TITLE
Tracks: navigating between pages does not reliably send event

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#85874]
### Quick summary

When one navigates between pages with something like `page.redirect()`, the app state remains and the tracks event is fired as expected. However, in some cases when switching pages, the event will fire but the request does not complete.

### Steps to reproduce

This has been observed in two ways (more info in pf36In-xI-p2#comment-809):

* Create a component that uses triggers an event and immediately calls `window.location.href` to switch to another page.
* Create a bare anchor tag that triggers an event prior to navigating to another page.

The first instance was consistently reproduced when ef0226e688875ff7102c8100096398ac1d9e5136 was checked out, and #85731 was merged to address the specific case observed. Below you can see the cancelled browser call to the tracking pixel (and to a prefs call):

![image](https://github.com/Automattic/wp-calypso/assets/32492176/0ad586d2-bc96-450b-adec-42c5d75c537a)

The second instance is more difficult to reproduce, but the gist is that if the browser goes to another page (e.g. from `cloud.jetpack.com` to `wordpress.com` to connect a new site), and the tracks event does not complete prior to that point due to a slow network or something of the sort, the request will be cancelled and therefore won't be logged server-side.

### What you expected to happen

Ideally we'd catch more tracks events than we do right now. While the current solution works great for most events, developers should have an alternate function for scenarios where there's a higher chance of failure using the normal function.

This fallback function could perhaps use one of the following:

* A synchronous call to tracks. This is less ideal because it's blocking.
* A stack in browser storage (e.g. `localStorage` or `IndexedDB`) that is checked for, sent, and cleared the next time a standard tracks call is triggered, maybe with a suffix or param indicating it was a deferred event.

---

Two further thoughts:

* If we went the latter route, we could even pass all tracks through said stack, though that might be overengineering things, and would require a unique ID to prevent duplicates server-side in scenarios where the request is successful but the browser receives no success confirmation.
* Creating a stack would mean we could batch these requests into one pixel load, resulting in less calls, which is a better client-side experience.

### What actually happened

Tracks events are sometimes lost if the tracks event is triggered at shortly before a URL change.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by lsl** [comment]
If I'm understanding [the page.js doc's](https://visionmedia.github.io/page.js/) correctly, I don't think `page.redirect` should be used for navigation between pages: it replaces the current history entry with the next one, probably want to use `page('/path')`.

> A stack in browser storage (e.g. localStorage or IndexedDB) that is checked for, sent, and cleared the next time a standard tracks call is triggered, maybe with a suffix or param indicating it was a deferred event.

This sounds like an interesting solution but I'm wondering if it's needed or not? `calypso_page_view` events are usually what I use for tracking navigation, button clicks generally only need tracking if they're doing something without a corresponding navigation event.

**Comment by mmtr** [comment]
> the tracks event does not complete prior to that point due to a slow network or something of the sort, the request will be cancelled and therefore won't be logged server-side.

I wonder if we even have a guard for this. According to the Tracks Technical Overview (PCYsg-5hs-p2):

> Receive the pixel call and log it — Our Nginx http servers receive the request for the pixel and log the IP address, the country code, a timestamp, the full URL including all those parameters, the http referrer, and the user agent
>
> Extract and aggregate the raw logs — We monitor the http logs to pull out any Tracks calls.

In theory, I think we can log these requests as soon as they start (i.e. they don't need to be completed) so maybe even if these are cancelled, our logs stills contain them and therefore the Tracks events are recorded.

I'll try to take a deeper look to confirm this theory.

**Comment by tbradsha** [comment]
Awesome, thanks for digging into this!
