### ISSUE TITLE
Woo Express free trial users can't activate WooCommerce themes

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#85889]
#### Issue description

Woo Express free trial plan users should be able to activate WooCommerce themes without subscribing to a paid plan.

#### Steps to reproduce

1. Create a Woo Express free trial site by going to https://woo.com/start and follow through the NUX process
2. Go to Appearance > Themes
3. Search for `tazza`
4. Select Tazza theme
5. Observe you can't activate it now, despite it being free

**Comment by adrianduffell** [comment]
This was fixed by https://github.com/Automattic/wp-calypso/pull/85890
