### ISSUE TITLE
Reader FP: Search scrolls to top when you hit back from new FP

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#8591]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/read/search?q=pretzel%20croissant
2. Scroll down past all the delicious looking pastry. 
3. Click on a particularly good looking one
4. Hit back
5. Notice we scroll back up to the top of the search
#### What I expected

Not to scroll up, but to be in the same place I started
#### What happened instead

We scrolled
#### Browser / OS version

mac 'n chrome

**Comment by fraying** [comment]
I've noticed this, too, but only intermittently. Trying to look for a reason but haven't found one yet.

**Comment by blowery** [comment]
Re-eval.

**Comment by blowery** [comment]
fixed!
