### ISSUE TITLE
Cleanup: Remove translation fallback from the plans page

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#85929]
Since the translations introduced in https://github.com/Automattic/wp-calypso/pull/85413/ are now finished (https://github.com/Automattic/wp-calypso/pull/85413#issuecomment-1867692634), we can now remove the related language fallback (that had been added in that PR as well).

**Comment by ivan-ottinger** [comment]
Hey @phcp & @andregardi 👋 In case you are looking for a tiny low priority Calypso PR opportunity (as a part of the onboarding) that also touches translations, here is one. 🙂

**Comment by phcp** [comment]
Thank you @ivan-ottinger! It seems a nice first Calypso PR. Right now, we are focusing on the wpcom codebase to accomplish the first 3 PRs, but after that, we can take this one.
