### ISSUE TITLE
Assembler: super simple interview survey

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85922]
# Description
We've had two prior Assembler surveys that have a in-product banner prompt like shown below.    We'd like to try something new: instead of asking users to fill out a survey we'll do a simple question and collect name and email that we can use to follow up with an interview.

![image](https://github.com/Automattic/wp-calypso/assets/5665959/eff16961-78ab-4201-b039-2cf8ef5b8a28)

### Simple crowdsignal survey

* How is your WordPress onboarding experience so far (rate on a 1 to 5)
* Name
* Email 

See it in the [Marvel Team folder](https://app.crowdsignal.com/dashboard?folder=32831990) https://app.crowdsignal.com/surveys/2958670/question

# Dev Tasks
- [ ] Proof read survey created by autumn https://automattic.survey.fm/assembler-simple-survey 
- [ ] Make it live in the Assembler, same location and UI banner as the last survey

**Comment by autumnfjeld** [comment]
Can we mention they would get some WP credits?

Update on Jan 10 : we offer blaze credits for doing the interview, and also can give paid credits or coupons.

**Comment by taipeicoder** [comment]
Closing via #86268
