### ISSUE TITLE
Like Block: show the reblog button in the Like Block ignoring the global setting for reblogs.

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#85951]
### Details

This task is part of https://github.com/Automattic/wp-calypso/issues/85273

The Like Block uses an iframe to communicate with the server. That iframe URL now includes a "reblog" variable if the reblog button setting is toggled ON on the sidebar in the editor (only for simple sites).

This task relates to the server side. When the server detects that "reblog" in the iframe URL, it should render the reblog button regardless of the global settings for reblogs on the site.

### Related

https://github.com/Automattic/wp-calypso/issues/85273

**Comment by mashikag** [comment]
@JuanLucha , is this task still in use? Or can it be closed? I would appreciate if you could link the associated diff too. 🙂

**Comment by JuanLucha** [comment]
@mashikag Hi!
Here is the link: D133509-code
I can close this one.
Thanks fo the heads up!
