### ISSUE TITLE
Reskinned white login: the "not you" option is hidden under the fold

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#85967]
#### Steps to reproduce

1. As a logged in user, go to wordpress.com/log-in
2. You'll see the `ContinueAsUser` UI that offers you to continue as the already logged-in user:

   <img width="1221" alt="Screenshot 2024-01-04 at 8 56 59" src="https://github.com/Automattic/wp-calypso/assets/664258/dc163eae-4a8d-400e-af0f-bab0246aa87a">

#### What I expected
There is also the "Not you? Log in with another account" option, but I don't see it.

#### What happened instead
That option is under the fold. Even on a big desktop browser viewport, the screenshot above is 1200x780. I need to scroll down to see it.

The styles probably need fixing. I'm noticing that also the top margin above the large "Log in to WordPress.com" heading is fairly big, it pushes the main UI to the bottom half of the page.

Cc @escapemanuele

**Comment by escapemanuele** [comment]
Thank you @jsnajdr, fixing this now.
