### ISSUE TITLE
Duotones and gradients omitted from V2 Assembler color sets

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#85960]
The [color sets](https://github.com/Automattic/assembler-libraries/tree/trunk/colors/build) within the `/colors/build/` dir in assembler-libraries provide gradients and duotone values (generated via bash script using the source color JSON files in `/colors/`). 

Currently those are not included on the site when going through the v2 Assembler flow. 

I would expect those gradients and duotones available on an assembled site. 

### Visuals

![CleanShot 2024-01-03 at 14 50 10](https://github.com/Automattic/wp-calypso/assets/1813435/74eddb21-5024-470f-822b-4afe17964cfa)

### Expected
Local testing of the assembler libraries color sets:

![CleanShot 2024-01-03 at 14 47 26](https://github.com/Automattic/wp-calypso/assets/1813435/827a9a17-74e2-4bb8-bf06-422e8b5b9a68)

**Comment by fushar** [comment]
Fixed via D133683-code:

<img width="539" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/bebd0c1b-6773-4f1e-85e5-c03783c382e0">
