### ISSUE TITLE
'My Reader' not displaying properly in Samsung Galaxy tablet

### ISSUE THREAD

**Issue by cristelrossignol** [Automattic/wp-calypso#8599]
#### Steps to reproduce
Starting at URL: https://wordpress.com/ (Logged In)

#### What I expected
Access 'My Reader'

#### What happened instead
Clicking 'My Reader' does not trigger any action.
User also reported that the content was 'greyed out'.

#### Browser / OS version
(Samsun Galaxy Tablet)

#### Context / Source
#newtothis #bearwithme #thankyou :)
#user-report ID 2862450

**Comment by lancewillett** [comment]
Hi @cristelrossignol — thanks for the report. Could you please ask for a screenshot if possible? Also, could you clarify if this is using WordPress.com in a browser on the tablet, such as Chrome — or if they are using the Android native WordPress app?

**Comment by cristelrossignol** [comment]
Waiting for those details from the customer, thank you!

**Comment by lancewillett** [comment]
Closing since no reply in a week — feel free to re-open if we hear back with needed details.
