### ISSUE TITLE
Site Settings: Clicking on elements in a checkbox list toggles the checkbox (Safari)

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#86]
![d176b8a4-cbc6-11e4-9899-d19b1c557455](https://cloud.githubusercontent.com/assets/7233112/11245421/aca7a65a-8de0-11e5-846f-72cc5cfe21d3.gif)

My Sites > Settings > Discussion

Click on a select element, and it toggles the checkbox.  Looks like it only affects Safari, not Chrome or Firefox.  IE untested.

**Comment by gwwar** [comment]
This is a Safari only bug. IE11 and Edge are unaffected by this.
