### ISSUE TITLE
Reader: Disable Right Click Copy

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#86025]
### What

Add option to disable right+click on reader content, or allow customers to hide their content from Reader if it is important to them to be able to control this type of interaction with content.

### Why

Customer submitted the following feature request in #7521744-zen :

> I wish to request that your development team consider an updated feature for the Jetpack App. There should be a toggle switch whereby you select whether people using the Reader are allowed to copy and paste your content.
>
>I am not against the use of the Reader but allowing people to copy and paste, save or forward your content in native form is not conducive to growing your site. To the contrary, it promotes the ability to allow third parties to steal your website content. 
>
>Alternatively there should be a toggle switch whether you wish users within Jetpack or within browsers to be able to use the Reader or not.

### How

Not sure this is viable or realistic, but passing along for the customer.

**Comment by cuemarie** [comment]
> Alternatively there should be a toggle switch whether you wish users within Jetpack or within browsers to be able to use the Reader or not.

Filed this separately, here: https://github.com/Automattic/wp-calypso/issues/86119

**Comment by inaikem** [comment]
@davemart-in 👋 We moved this issue to a Loop board for review during today's Group Triage effort 👍
