### ISSUE TITLE
Like widget: "X likes" text is not being translated

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#86040]
The "X likes" text in the Like widget popover isn't being translated:

![Markup on 2024-01-04 at 12:51:15](https://github.com/Automattic/wp-calypso/assets/25105483/7455200b-788c-4335-87d7-8d86be5dea0d)

How to reproduce:

1. Add the Like block / widget to your site.
2. Set the site to language other than English.
3. Review the post with the Like block / widget in the front-end.

**Comment by phcp** [comment]
Dropped a question on the translations channel, seems the `likes-rest-nojquery.js` wasn't sent to translation. 
p1704843376890539-slack-C02AED43D

**Comment by phcp** [comment]
Should be fixed with D134108-code

**Comment by ivan-ottinger** [comment]
Thank you very much, Paulo! That's great!

I am leaving this issue open so we can check back in once the above patch is in and translations are finished in one / two weeks.

**Comment by ivan-ottinger** [comment]
Translations are in place. 👍🏼 → Closing this issue as done. ✅ 🙂
