### ISSUE TITLE
[Woo Express $1 offer] Checkout screen

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#86054]
### Issue description

Update copies in checkout screen to support $1 offer.

### Acceptance criteria

Figma : jFG3dxNDOdMkw8AC1aGWBL-fi-458:1884#624583779

1. Below the "Totals", section, update the copy 
```
You'll be charged $1 for the first 3 months of your Woo Express: Performance plan.

Once the offer period has expired, you'll be charged $540 on an annual basis. You can cancel your plan at any point in the first 3 months.
```
2. Remove the "Free domain" copy

**Comment by psealock** [comment]
@ilyasfoo Can you confirm conditions under which this text should be displayed?

So far I can think of `isWooExpressPlan( productSlug ) === true`. 

Is there a check on whether or not this is the $1 offer? I imagine we may someday remove the $1 offer.

We could also check `product_slug === 'wooexpress-medium-bundle-yearly'` to confirm the purchase is for an entire year. Does that make sense?

Anything I'm missing?

**Comment by ilyasfoo** [comment]
@psealock  Sorry I missed your ping!

> Is there a check on whether or not this is the $1 offer? I imagine we may someday remove the $1 offer.

Yes, there is a check for introductory offer. There is this [prior art](https://github.com/Automattic/wp-calypso/blob/101685cce610c075fbd19c14bbc5566f3b899803/client/my-sites/plans/trials/trial-banner/use-banner-subtitle.ts#L33-L72) that I believe can help.

> We could also check product_slug === 'wooexpress-medium-bundle-yearly' to confirm the purchase is for an entire year. Does that make sense?

In the introductory offer data, we have the information of the intro billing `intervalCount` and `intervalUnit`:

<img width="390" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/fa304d0a-4e6d-4c09-bafc-199b381dcd91">

**Comment by ilyasfoo** [comment]
> Anything I'm missing?

@psealock I should be clearer, the copy needs to be dynamic with the cost and interval:

```
You'll be charged * for the first * * of your *.

Once the offer period has expired, you'll be charged * on * basis. You can cancel your plan at any point in the first * *.
```

**Comment by psealock** [comment]
Closing this issue due to legal copy already displayed.

![image](https://github.com/Automattic/wp-calypso/assets/1922453/4ce931d8-12e4-4bfd-8158-dfead49a7420)
