### ISSUE TITLE
Atomic: Image blocks showing "This block has encountered an error and cannot be previewed" in the editor when AMP and GB 17.3 are active

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#86062]
### Quick summary

When AMP is active on a site with Gutenberg 17.3 or above, image-related blocks (Image, Media & Text, Cover, Gallery, Titled Gallery) are showing `"This block has encountered an error and cannot be previewed"` in the editor.

Deactivating either plugin fixes the issue.

This is also affecting self-hosted sites, as I was able to reproduce on a local site with Gutenberg (17.3 and 17.4) and AMP.

https://github.com/Automattic/wp-calypso/assets/14153300/496d5b70-c141-4b3c-94dd-d6ed80672f59

### Steps to reproduce

1. Activate AMP and Gutenberg
2. Open a new post or page
3. Add an Image Block

### What you expected to happen

The Image Block should render correctly

### What actually happened

"This block has encountered an error and cannot be previewed"

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

**Comment by liviopv** [comment]
AMP forum thread: https://wordpress.org/support/topic/amp-conflict-with-image-blocks-after-recent-gutenberg-versions-17-3-and-higher/#new-topic-0

**Comment by liviopv** [comment]
Issue in AMP repo: https://github.com/ampproject/amp-wp/issues/7710

**Comment by liviopv** [comment]
- [ ] 7540423-zd-a8c

**Comment by OmarFPG** [comment]
I was about to open an issue for this! Glad to see it's reported already!  😃 
I had 4 tickets today with this issue:

- 7542061-zen
- 7541655-zen
- 7541624-zen (this one is interesting as they mention in this case it's with the Paragraph Block. I've asked them if it happens with other blocks too, waiting for a reply).
- 7540380-zen (this one followed my troubleshooting steps to disable the Gutenberg plugin and was able to use the blocks).

**Comment by essleeung** [comment]
7542423-zd-a8c (disabled AMP)

**Comment by cat-og** [comment]
Another issue found here 7541057-zen

**Comment by marutim** [comment]
Another issue here: 7542763-zen

Deactivated AMP plugin to fix the issue.

**Comment by marutim** [comment]
Another issue : 7543196-zen. 

Deactivated AMP plugin to fix the issue.

**Comment by davipontesblog** [comment]
same here 7543879-zen.

**Comment by ktyfuller604** [comment]
Another issue here: 7544872-zd-a8c

Deactivated AMP plugin to fix the issue.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Video of the error on my test site:
https://github.com/Automattic/wp-calypso/assets/86028337/e687bf5b-6e0b-465c-970c-0a84460c3844

I was able to replicate this on one of my Atomic test sites but not both. Changes to the theme or any other plugins (aside from AMP and Gutenberg) made no difference for either site. 

📌 ACTIONS
- Triaged

**Comment by rw-ye** [comment]
7546110-zd-a8c - Deactivated AMP

**Comment by rw-ye** [comment]
Another report here: 7545871-zd-a8c

**Comment by mdtanjid0** [comment]
Another one: 7547607-zen
Advised them to deactivate the AMP plugin to fix the issue.

**Comment by hngdny** [comment]
Another report: 7547880-zd-a8c
Besides affecting Image Blocks, it also affected the File Block, resulting in the same error.
Disabling AMP plugin resolved the issue for both block types

**Comment by dolgelukkig** [comment]
Another report: 
7547854-zd
7548024-zd

Deactivating AMP solved the issue. 


I have another report but deactivating AMP did not resolve the issue on that site. Deactivating Gutenberg plugin did
7547852-zd

**Comment by OmarFPG** [comment]
7514114-zen, suggested deactivating Gutenberg workaround.
7542106-zen it seems for all blocks here. AMP and Gutenberg workaround suggested.

**Comment by jp-imagines** [comment]
Another report in 7548150-zd-a8c; disabled AMP.

**Comment by cuemarie** [comment]
Reported here: 549125-zen

Deactivated AMP.

This customer would love a follow up when this issue is resolved so they can reactivate AMP. @liviopv do you think this will get a batch reply? If not, I'll try to keep an eye on it and when the issue is resolved and I can follow up with the customer.

**Comment by jp-imagines** [comment]
Another report in 7549223-zd-a8c; disabled AMP to resolve.

**Comment by jerren1327** [comment]
Another report here: 7549115-zen
7549026-zen

**Comment by mdtanjid0** [comment]
Another report here: 

- [ ] 7550991-zen ( needs to be followed up )

**Comment by dolgelukkig** [comment]
Another report: 7551295-zd
Deactivating AMP solved the issue.

**Comment by mdtanjid0** [comment]
Another report: 7547797-zen ( needs to be followed up ).

**Comment by i11za** [comment]
More reports:

7552150-zd-a8c
7551964-zd-a8c

Deactivating AMP solved the issue. No need to followup on these.

**Comment by dolgelukkig** [comment]
7552245-zd
Deactivated AMP and Gutenberg plugin to get it solved

**Comment by dolgelukkig** [comment]
And two more 7552463-zd and 7552743
Deactivating AMP solved the issue

**Comment by cagrimmett** [comment]
There is a working patch available at https://github.com/ampproject/amp-wp/pull/7711 to be released in the next AMP release, which does not have a date.

**Comment by connorhipps** [comment]
Another report here: 7553039-zd-a8c

Deactivating AMP worked like in previous cases.

**Comment by radtechgh** [comment]
another: 7552957-zen
7552964-zen

**Comment by upwardmomentum84** [comment]
7553047-zd-a8c

Deactivated AMP and Gutenberg plugin to get it solved.

**Comment by silvio-meter** [comment]
7551606-zen

**Comment by silvio-meter** [comment]
7551606-zen

Deactivated AMP

**Comment by jp-imagines** [comment]
Another report in 7553378-zd-a8c. Deactivated AMP to resolve.

**Comment by radtechgh** [comment]
another, deactivated AMP to solve: 7554411-zd-a8c

**Comment by hngdny** [comment]
Another report 7554703-zd-a8c
Disabling AMP plugin resolved

**Comment by mdtanjid0** [comment]
Another one: 7555392-zen, deactivated AMP plugin to resolve the issue.

**Comment by rw-ye** [comment]
7541861-zd-a8c 

Deactivated AMP

**Comment by mdtanjid0** [comment]
7555448-zen helped them to deactivate the plugin.

**Comment by rinazrina** [comment]
7555691-zd-a8c

Though AMP has been deactivated, there is still an error. Deactivating Gutenberg v17.3.2 resolved it.

**Comment by marutim** [comment]
Another issue reported here: 7555802-zen

Deactivated the AMP plugin to fix the issue.

**Comment by rinazrina** [comment]
7556094-zd-a8c

I have another one where deactivating AMP does not fix the error, but deactivating Gutenberg does. 
The user would like to get an update when this is resolved.

**Comment by rw-ye** [comment]
7542107-zd-a8c

**Comment by jromales** [comment]
7556383-zd-a8c deactivated AMP for now

**Comment by tellisbethel** [comment]
Another case here: 7557261-zd-a8c
Deactivated AMP. User would like to be notified of fix release.

**Comment by WunderBart** [comment]
`7544179-zd-a8c`

**Comment by suyogyashukla** [comment]
7557625-zd-a8c
Deactivated AMP for now which fixed the issue

**Comment by suyogyashukla** [comment]
7558690-zd-a8c
Deactivated AMP which fixed the issue

**Comment by i11za** [comment]
7558664-zd-a8c
Deactivated AMP which fixed the issue

**Comment by nellofn** [comment]
Another case here: 7545320-zen. 
Sent them steps on how to disable the AMP plugin in the meantime.

**Comment by nellofn** [comment]
Another case here: 7544808-zen.
Deactivated AMP to temporarily fix the issue.

**Comment by jp-imagines** [comment]
Another report in 7560392-zd-a8c, this time with an **Audio** block. Disabling AMP still fixed the error.

**Comment by rinazrina** [comment]
7561507-zd-a8c Deactivated AMP which fixed the issue.

**Comment by rw-ye** [comment]
7544945-zd-a8c

**Comment by rw-ye** [comment]
7545273-zd-a8c - Asked to deactivate AMP

**Comment by jerren1327** [comment]
7562384-zen - asked to deactivate AMP

**Comment by dolgelukkig** [comment]
7563057-zen 
deactivated AMP

**Comment by Aurorum** [comment]
7561209-zen - also AMP plugin

**Comment by nellofn** [comment]
7547447-zen
Deactivated AMP

**Comment by nellofn** [comment]
7548583-zen
Deactivated AMP

**Comment by WunderBart** [comment]
`7546406-zd-a8c`

**Comment by liviopv** [comment]
Closing as fixed by AMP 2.5.2, which is rolling out today https://wordpress.org/plugins/amp/
