### ISSUE TITLE
Domain Management: Instruction to set Name Servers

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#861]
Originally reported by @p3ob7o.

As @gziolo pointed out, the DNS section of mapped and registered domains can't be identical as while both should allow editing the custom zone when our DNS servers are used, the former can't allow users to actually set Name Servers.

One solution would be for the domain manager to offer the same choices for both registered and mapped domains, excepted that mapped domains in the Name Servers section would show instructions on how to change them.

A message like: “This domain name is not registered with us, to update its DNS servers you need to log into your account at ​_Registrar_Name_​” and link to https://en.support.wordpress.com/map-existing-domain/#instructions-for-popular-domain-providers

**Comment by umurkontaci** [comment]
Bug scrubbing: We have different views for mapped and registered domains in DNS editor and in navigation for some time.
