### ISSUE TITLE
Woo Express: Trial sites return to the Dashboard before plugins are activated.

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#86108]
We moved Woo Express trial software registration to an async job in D130515-code. This speed up the trial site creation process enough that, sometimes, the plugins haven't finished installing before we return to the dashboard.

Here's the location where we're currently waiting and checking if plugins are installed.

https://github.com/Automattic/wp-calypso/blob/717bdcdbb235a18fec1ef25b01a7fba3d0c38dd6/client/landing/stepper/declarative-flow/internals/steps-repository/wait-for-plugin-install/index.tsx#L80

The most likely fix is that we need to wait for the plugins to be installed _and_ activated. We're currently only checking if they're installed.

More details in peapX7-3Na-p2.

**Comment by sixhours** [comment]
This should be fixed by https://github.com/Automattic/wp-calypso/pull/86243
