### ISSUE TITLE
Upgrade banner: update copies

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#86110]
As discussed here (P2: p9Jlb4-amX-p2#comment-10424) this banner is confusing and it's not working (0.1% CR to purchase).

Example site: https://thedoctorwhonewsletter.wordpress.com/

## Current

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/819b8513-c174-4c88-9918-a083c35c8fdc)

## Proposal

Make the copy clearer to site owners, highlighting the benefits of upgrading (which aren't just removing the banner).

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/513af122-c64a-45e0-9659-3c5bb6925ab0)

**Comment by javierarce** [comment]
I think your proposal makes sense, @crisbusquets. 

Looking at the mobile version of the banner, maybe we could use this opportunity to replace the arrow with the Gutenberg equivalent (or perhaps we could consider a different solution)

![image](https://github.com/Automattic/wp-calypso/assets/4933/4537985c-f001-4ad2-b842-be87389417f5)

**Comment by crisbusquets** [comment]
> I think your proposal makes sense, @crisbusquets.
> 
> Looking at the mobile version of the banner, maybe we could use this opportunity to replace the arrow with the Gutenberg equivalent (or perhaps we could consider a different solution) 
> 

I'd replace it with its equivalent. We could also add a CTA, but since the copy will be longer, I think the arrow icon will work better.

What do you think, @javierarce?

**Comment by javierarce** [comment]
That works for me 👍

**Comment by crisbusquets** [comment]
Closing in favour of D134147-code and https://github.com/Automattic/martech/issues/2573
