### ISSUE TITLE
Like block / widget: Fix misaligned avatars

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#86112]
Currently, the avatars in the Like block / widget are not aligned correctly (vertically):

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/852428d3-46c3-45c5-ba42-fc3f7a818336)

It looks like they should be about one to two pixels lower. Of course the cause might be somewhere else - e.g. in the circular border of those avatars.

Context: p1704383163418159/1704382324.738109-slack-C02TCEHP3HA

**Comment by JuanLucha** [comment]
Fixed in: D133899-code
