### ISSUE TITLE
Global Styles import intermittently fails on simple sites

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#86122]
### Quick summary

Imports of Global Styles posts sometimes fail to take effect, despite the data being imported.

### Steps to reproduce

1. Go to wordpress.com/start
2. Do whatever with a domain
3. Select a plan (free is fine)
4. Press 'skip to dashboard' in the top right
5. Activate Twenty Twenty-three
6. Go to Tools → Import
7. Select a WP import
8. Use the XML file found here: p1690993825016369/1690989410.854689-slack-C0160HSMDQV
9. Wait until it says the import was successful
10. Look at the front-end of the site

### What you expected to happen

I expected the styles in that file to be evident, to whit:
 * Buttons are rounded with a 2px blue-ish border
 * Links have a greenish colour ([2a9d8f](https://www.color-hex.com/color/2a9d8f))
 * Text uses the Jost font
 * Headings use the Literata font

It should look like this: https://expressdemo3.wordpress.com/

<img width="1454" alt="Screenshot 2024-01-08 at 21 46 17" src="https://github.com/Automattic/wp-calypso/assets/93301/6580cf20-a47c-442b-813f-2774c1ff9325">

### What actually happened

 * Buttons radius are squarer than a very square thing
 * Links are black
 * All fonts are the system fonts

In short, it looks suspiciously like TT3 without modifications.

You can see the results here: https://deansas58.wordpress.com/

<img width="1454" alt="Screenshot 2024-01-08 at 21 45 26" src="https://github.com/Automattic/wp-calypso/assets/93301/dec571d6-ec26-4f5f-9b9d-c3fc8eefe1b0">

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Database exploration
You can see that the global styles post has actually been imported by running:
`select id, post_title, post_name, post_content from wp_SITEID_posts where post_type = 'wp_global_styles'`, you'll see two posts, one is basically empty as would be [created by GBs `get_user_data_from_wp_global_styles` if there were no posts](https://github.com/WordPress/gutenberg/blob/ad88b6b9daaae5ac8a737102c0b586163989da56/lib/class-wp-theme-json-resolver-gutenberg.php#L488C1-L488C2), whereas the other will contain the TT3 global style from the aforementioned XML file.

I then learned that both posts were part of the same two taxonomies (2,3) by running `select * from wp_227809155_term_relationships where object_id IN (9,4)` (where 9&4 are the post_ids I got from the first query)

I checked what these taxonomies were, 2 belongs to the link_category taxonomy (which we don't care about) and 3 belongs to the wp_theme taxonomy, which we do care about. The particular taxonomy term for the wp_theme taxonomy was 1357 `select * from wp_227809155_term_taxonomy where term_taxonomy_id IN (2,3);`

Taxonomy term 1357 is named `pub/twentytwentythree` and slugged `pub-twentytwentythree` which you can check by running `select * from wp_227809155_terms where term_id IN (1357)

I _suspect_ the "intermittent" part is because when first queried sometimes the "empty" GB is found first and sometimes the imported GB is found first, though I was reproducing the problem consistently when testing.

### Background and useful links

This slack thread initially introduced support for importing global styles: p1678187168952379-slack-C01A60HCGUA and has links to relevant PRs etc. The only thing I did wonder was whether there was scope for a race condition or something.

This issue has been escalated here: p1704748797978659/1704733118.042909-slack-C02FMH4G8, though it's likely that the slack thread and linked issues https://github.com/Automattic/wp-calypso/issues/81849 and https://github.com/Automattic/wp-calypso/issues/82363 are actually multiple issues which are somewhat tangled together. By creating this separate issue I'm hoping to avoid conflating too many linked bugs and keep things simple.

The problem may or may not also happen on atomic sites - it's difficult to tell whether it's this problem, or whether it is a separate problem. Again for now, I'd rather focus on simple sites as far as possible, in order to keep things separate and simple.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
I tried once again and could not replicate it consistently, just like I could not on the original thread - the resulting site looks the same as the demo https://bbeimporttest4.wordpress.com/


📌 ACTIONS
- Triaged, couldn't repro but keeping as High considering how disruptive it has been for BBE builders.


📌 Message to Author
@dsas I'm editing your report to add a step to active TT3. If you import the WXR over any other theme, it does not bring the styles as expected.

**Comment by dsas** [comment]
> @dsas I'm editing your report to add a step to active TT3. If you import the WXR over any other theme, it does not bring the styles as expected.

Thanks @liviopv, when I wrote this TT3 was the default theme so the steps worked, it's now TT4, so yeah will need TT3 activated.

**Comment by mattwiebe** [comment]
Hypothesis: we need to finish cleaning up `wp_theme` terms on import to get rid of the unprefixed version.

Search for this line in `async-jobs`: `// TODO: Consider deleting unprefixed terms from database.` or look at D62467-code for some background.

On transfer to Atomic, the old, unprefixed terms come back into play and sometimes collide with the `pub/` versions, because it's basically a full db dump. What we need to do therefore on Import on dotcom is to make sure no traces of unprefixed `twentytwentythree` are left behind, so there's a clean conversion on AT transfer. Or something along these lines, this might not be quite it, but the important thing is to ensure that there's no unprefixed leftovers on the dotcom side, first.

For example, after I AT'd a site with the above imported content, I first had the unstyled version, but then it resolved somehow afterwards. One possibly relevant piece of info is that I now have two separate `twentytwentythree` `wp_theme` terms:

```
wp term list wp_theme
+---------+------------------+-------------------+-------------------+-------------+--------+-------+
| term_id | term_taxonomy_id | name              | slug              | description | parent | count |
+---------+------------------+-------------------+-------------------+-------------+--------+-------+
| 1357    | 3                | hey               | hey               |             | 0      | 1     |
| 1358    | 4                | twentytwentythree | twentytwentythree |             | 0      | 16    |
| 1360    | 6                | twentytwentythree | twentytwentythree |             | 0      | 0     |
| 1361    | 7                | yuga              | yuga              |             | 0      | 0     |
| 1365    | 11               | yuga              | yuga              |             | 0      | 7     |
+---------+------------------+-------------------+-------------------+-------------+--------+-------+
```

In short, I imagine that if we clean up the duplicate terms and entries properly on import, we will fix a good chunk of these issues. Both templates and global styles rely on this taxonomy so this is a giant blinking red light to me.

---

UNRELATED BUT ALSO BAD

This does not directly impact this particular issue, but since the WXR file in question was output from wpcom, I also see that we have an incomplete version of stripping `pub/` from our export, eg, the `content` field from the `Single` template looks like:

```
<!-- wp:template-part {"slug":"header-interior","theme":"twentytwentythree","tagName":"header"} /-->

<!-- wp:group {"tagName":"main","style":{"spacing":{"margin":{"top":"0"}}}} -->
<main class="wp-block-group" style="margin-top:0"><!-- wp:cover {"useFeaturedImage":true,"dimRatio":50,"overlayColor":"secondary","contentPosition":"bottom left","align":"full","style":{"color":[]},"layout":{"type":"constrained"}} -->
<div class="wp-block-cover alignfull has-custom-content-position is-position-bottom-left"><span aria-hidden="true" class="wp-block-cover__background has-secondary-background-color has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:post-title {"level":1,"style":{"spacing":{"margin":{"bottom":"var:preset|spacing|40"}}}} /--></div></div>
<!-- /wp:cover -->

<!-- wp:spacer {"height":"20px"} -->
<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:post-content {"layout":{"type":"constrained"}} /-->

<!-- wp:template-part {"slug":"post-meta","theme":"pub/twentytwentythree"} /-->

<!-- wp:template-part {"slug":"comments","theme":"pub/twentytwentythree","tagName":"section"} /--></main>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","theme":"twentytwentythree","tagName":"footer"} /-->
```

Notice how there is a mix of `pub/twentytwentythree` and `twentytwentythree` in those `wp-template-part` `slug`s. On export, all traces of `pub/` should be removed. It probably works ok when re-importing to dotcom, but might be wonky when importing directly into a dotorg/Atomic site (not AT transfer, running the import there directly).

**Comment by ouikhuan** [comment]
This has been fixed in D133982-code for simple sites.

**Comment by mikeicode** [comment]
@dsas 

I tested this current issue (XML import into simple) and it worked correctly. I still ran into the AT content transfer issue, but that is separate.

There is also an issue with this:

> The problem may or may not also happen on atomic sites - it's difficult to tell whether it's this problem, or whether it is a separate problem. 

In my experience, this has never worked. I just tested now and it failed again. Using the new XML import file here:

p1706201331381159/1704733118.042909-slack-C02FMH4G8

I imported into a new AT site, then activated TT3. It was default TT3:

https://mikeicode4.wpcomstaging.com

![Screen Shot on 2024-01-25 at 12-05-48](https://github.com/Automattic/wp-calypso/assets/10353785/0c30f444-acb6-46b9-99fa-9d9722f5fbbe)

Should we mark this simple site issue as resolved for now, and open a separate issue for the AT XML imports?

**Comment by dsas** [comment]
One down, two to go 😄 😢 

> Should we mark this simple site issue as resolved for now, and open a separate issue for the AT XML imports?

Sounds good to me @mikeicode  👍

**Comment by mikeicode** [comment]
@dsas I opened a new issue here for AT:

https://github.com/Automattic/wp-calypso/issues/86908

I titled the issue the same as your issue here for consitency, although it's possible there are 2 separate issues:

* Global style import
* Block changes / site editor customizations import
