### ISSUE TITLE
Stats: Detect new users

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#86130]
Find a way to distinguish existing users from the new users to present the new flow only to the new users.
If we don't have a mechanism to do it, consider extending the Stats endpoint. The existing notification banner mechanism might be a good inspiration.

Find a way to accomplish the task and implement it in #86132

**Comment by kangzj** [comment]
This could be useful:

https://github.com/Automattic/wp-calypso/blob/680131efa7f09ce76465b32a9f7d46eff394fb83/client/my-sites/checkout/checkout-thank-you/hundred-year-plan-thank-you/index.tsx#L137

**Comment by grzegorz-cp** [comment]
I decided to use the selector proposed by Jasper because instead of adding a new property, we can use an existing one.
A new property will be needed to check if users completed the new flow.
