### ISSUE TITLE
API: use .withLocale() by default

### ISSUE THREAD

**Issue by yoavf** [Automattic/wp-calypso#8613]
Occasionally (#8598, #5664), we'll find ourselves with untranslated strings being returned from the API. Usually, this will happen because `withLocale()` hasn't been activated for the query. I can't think of a reason why `withLocale()` shouldn't be the default, so let's do that.

**Comment by akirk** [comment]
I agree. Except of a lot of changed URLs (but they are unique to the users so it should not matter wrt to caching) I don't see a problem either. Let's do it!
