### ISSUE TITLE
Checkout: Privacy Protection is not checked by default when registering a domain to a new WordPress.com site

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#8614]
Privacy Protection is not checked by default when registering a domain to a new WordPress.com site.

#### Steps to reproduce
1. Start at: https://wordpress.com/start
2. Follow the screen prompts to create a new WordPress.com site. 
3. As part of this process, choose a custom domain to register and then follow the prompts until you reach the **Domain Contact Information** form.

#### What I expected

I expected the option next to **Please keep my information private.** above the form to be checked by default.

Since #5677, this option has been checked by default when registering a new domain to an **existing** WordPress.com site. 

As Privacy Protection is included within the cost of a plan (and a plan is required to register a domain) I would assume that most people would default to choosing it.

#### What happened instead

The option next to **Please keep my information private.** was **not** checked by default.

#### Browser / OS version

Chrome 53.0.2785.143 / OS X El Capitan 10.11.6

#### Screenshot / Video

The option for Privacy Protection is unchecked by default:

<img width="1426" alt="screen shot 2016-10-09 at 12 03 51" src="https://cloud.githubusercontent.com/assets/2998162/19219924/f670e18c-8e18-11e6-8734-e36d2c98411f.png">

This is in contrast to the default when registering a domain to an existing WordPress.com site (starting at https://wordpress.com/domains/add):

<img width="881" alt="screen shot 2016-10-09 at 12 24 22" src="https://cloud.githubusercontent.com/assets/2998162/19220026/7d7aabd4-8e1b-11e6-9cbd-6e370daa37b6.png">

#### Context / Source

#dogfooding #manual-testing #perspective

**Comment by klimeryk** [comment]
Thanks, very nice catch! We'll definitely look into this! 🙇

**Comment by klimeryk** [comment]
@aidvu, might having a look at this? (since you were the one that introduced the intended/correct behaviour in https://github.com/Automattic/wp-calypso/pull/6130)

**Comment by aidvu** [comment]
Wow, a whole chunk of code dealing with privacy was removed. Looking. :eyes:

**Comment by aidvu** [comment]
https://github.com/Automattic/wp-calypso/pull/8784

**Comment by aidvu** [comment]
Fixed in #8833
