### ISSUE TITLE
Storage add-on: the same add-on cannot be repurchased from `/add-ons` after cancelling.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#86147]
### Quick summary

_This issue is broken out from the auditing in https://github.com/Automattic/wp-calypso/issues/85773_.

Demonstration:

https://github.com/Automattic/wp-calypso/assets/1842898/0751018a-5f87-4dd2-bd20-906e341ee2f0

From a quick glance, using transaction history to determine whether one has owned an active storage add-on is wrong. This issue will also cause other anomalies in /plans, but I didn't include them here since the root cause is the same. This might potentially relate to Automattic/martech#2418.

### Steps to reproduce

1. Purchase a storage add-on from /add-ons
2. Cancel it from the purchase management page
3. Go to /add-ons again.

### What you expected to happen

The button should be "Buy add-on"

### What actually happened

 The button stays as "Manage add-on".

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable.

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my test site. It is not possible to repurchase the add-on once canceled.

📌 ACTIONS
- Triaged
