### ISSUE TITLE
Storage add-on: The drop-down state is shared between sites. 

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#86152]
_This issue is broken out from the original audit: https://github.com/Automattic/wp-calypso/issues/85773_

### Quick summary

https://github.com/Automattic/wp-calypso/assets/1842898/29078107-dd09-486e-8cca-d9a5bb8537b5

As demonstrated above, the drop-down state stays after changing sites. This _might_ be fine, but I'm still documenting it here in case it actually causes other issues.

### Steps to reproduce

1. Pick a storage add-on from the site A.
2. Switch to the site B, and visit /plans again.

### What you expected to happen

The storage add-on dropdown is set as the default one.

### What actually happened

The storage add-on dropdown is toggled to the one picked from the site A.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Replicated  

## 📌 ACTIONS ##
Triaged

**Comment by jeyip** [comment]
Should be fixed with https://github.com/Automattic/wp-calypso/pull/87342
