### ISSUE TITLE
Classic View: improve responsive view in /posts

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#86161]
The /pages _Classic View_ isn't very responsive.
This screenshot is 1440x900, and some columns are very difficult to read.

The _Title_ and the _Newsletter_ columns should expand more, and leave less room for _Categories_ and _Tags_.

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/21ab83c6-49a4-45e7-9304-dbacf2a86e5f)

**Comment by rickmgithub** [comment]
## TO REPLICATE: ##

1. Ensure you have a post published with tags and categories
2. Then go to /pages
3. Select Classic view
4. Select screen options
5. Select tags and categories
6. Resize and size page to see effect

## 📌 REPRODUCTION RESULTS ##
- Only affects classic wp-admin view
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
It does indeed become unreadable

https://github.com/Automattic/wp-calypso/assets/13706336/9d498002-4805-4d6f-9ec7-e763f81b3074


## 📌 ACTIONS ##
Triaged

**Comment by pkuliga** [comment]
The bug with the title column is a core thing and it's already reported:
https://core.trac.wordpress.org/ticket/52151

If it comes to the Newsletter column, it should be possible to mitigate it. I'll take a look.
