### ISSUE TITLE
Checkout: No confirmation of payment after purchasing a plan via PayPal

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#8616]
After testing the signup flow and making payment for a plan via PayPal, I received no confirmation that payment had gone through successfully. Instead, I was taken directly to the WordPress.com Reader with little clue as to what to do next.
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Follow the screen prompts to set up a new WordPress.com account. As part of this process, choose a plan.
3. When prompted to make payment for the plan, choose the PayPal option.
4. Sign into PayPal and follow the prompts to make payment for the plan.
#### What I expected

After making payment via PayPal, I expected to be taken to a Thank You page or to receive some form of confirmation that payment had gone through correctly.
#### What happened instead

After making payment via PayPal, I was taken directly to the WordPress.com Reader. 

There was no confirmation that payment had gone through correctly and I was left genuinely confused about what steps to take next.
#### Browser / OS version

Chrome 53.0.2785.143 / OS X El Capitan 10.11.6
#### Screenshot / Video

First screencast starts immediately after I have made payment via PayPal and am taken back to WordPress.com. You'll see that I start on the WordPress.com Reader and try to figure out a way around:

https://cloudup.com/ckBS-T5oP1A

I tested the flow for a second time and was, again, taken directly to the WordPress.com Reader after making payment via PayPal. The only confirmation I received that payment had gone through was the email receipt from WordPress.com:

https://cloudup.com/cv3EEjcOaQQ

(Uploaded via Cloudup as the files were too large to upload directly to GitHub.)
#### Context / Source
# reallife #dogfooding #painpoint

**Comment by bisko** [comment]
cc @scruffian

**Comment by scruffian** [comment]
This should now be handled by Gold.

**Comment by melanieharari** [comment]
This is/was in testing, as noted [here](https://github.com/Automattic/wp-calypso/issues/7438). I'm going to close this issue in favor of that one.
