### ISSUE TITLE
Components: Add VerticalNavItem to devdocs

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#862]
Originally reported by @scruffian.

We should add this new component to  https://wpcalypso.wordpress.com/devdocs/design

![vnav](https://cloud.githubusercontent.com/assets/1248436/10281678/8691d788-6b76-11e5-818e-24c8ec2d2b3e.png)

@folletto noticed this is quite similar to `FoldableCard`. He also pointed that, to be generic enough, this requires support to more than just a title (i.e. My Site →  Settings).

**Comment by mtias** [comment]
This has been absorbed by the work @scruffian did with `Cards` when you set a href prop. I believe VerticalNavItem is to be considered deprecated now?

**Comment by scruffian** [comment]
We should replace VerticalNavItem with linkable Cards: https://github.com/Automattic/wp-calypso/issues/878
