### ISSUE TITLE
Device icons: should be same order in DP & PA

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#86214]
![Image](https://github.com/Automattic/wp-calypso/assets/5665959/9b90815e-d809-42c2-b30b-468d9ce4da8b)

We should go with the ordering from the Designer picker. Laptop, Tablet, Phone, Zoom.

**Comment by matt-west** [comment]
Let’s use the ordering from the design picker.

1. Laptop
2. Tablet
3. Phone
4. Zoom

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/86386.
