### ISSUE TITLE
Retire all non-LIB Virtual themes

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#86264]
See discussion: pekYwv-3EK-p2#comment-2869.

The 19 LIB patterns used in onboarding can be viewed here https://wordpress.com/setup/link-in-bio-tld/patterns.

The four LIB patterns that are in teh Add a page modal, but not in onbarding are:

* [Link in Bio left-aligned with yellow background](https://href.li/?https://dotcompatterns.wordpress.com/2022/08/25/link-in-bio-left-aligned-with-yellow-background/)
* [Link in bio with two columns and dark background](https://href.li/?https://dotcompatterns.wordpress.com/2022/08/25/link-in-bio-with-two-columns-and-dark-background/)
* [About Me](https://href.li/?https://dotcompatterns.wordpress.com/2021/04/27/about-me-2/)
* [About Me Card](https://href.li/?https://dotcompatterns.wordpress.com/2021/02/08/about-me-card/)

I think we only need to keep the 19 VT that are in the LIB onboarding.   Let's retire these VT:
* all non-LIB VT
* any VT that aren't in the onboarding flows (confirm with @alaczek )

**Comment by alaczek** [comment]
> The four LIB patterns that are in teh Add a page modal, but not in onbarding are

I think it's fine ti retire/remove these four. 
[This one](https://dotcompatterns.wordpress.com/2021/04/27/about-me-2/) is even a [stand alone theme](https://wordpress.com/theme/baker/).

**Comment by autumnfjeld** [comment]
Worth capturing this "most chosen" VT for bringing back later or just awareness in terms of pattern development (no action needed, just information)

/tracks/funnel/view.php?40973/2023-11-17/to/2023-12-17&selected-segmentation%5B0%5D%5Btype%5D=custom_prop&selected-segmentation%5B0%5D%5Bstep%5D=1&selected-segmentation%5B0%5D%5Bprop%5D=slug&




![Image](https://github.com/Automattic/wp-calypso/assets/5665959/279acaff-1b72-4ba0-a8f3-b87a48f78102)

**Comment by miksansegundo** [comment]
✅ Trashed the patterns:

- all non-LIB VT
- the four not in onboarding
