### ISSUE TITLE
Plans 2023: Plan Type Selector dropdown doesn't handle overflow text well

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#86270]
### Quick summary

Overflow text isn't handled well in the plan type selector dropdown

<img width="1419" alt="Screenshot 2024-01-16 at 11 21 09 AM" src="https://github.com/Automattic/wp-calypso/assets/5414230/54109920-54dd-4d25-9c9c-23ac40f7f11d">

![Screenshot 2024-01-10 at 12 22 06 PM](https://github.com/Automattic/wp-calypso/assets/5414230/069d1339-3074-4de2-8152-9b558a66e862)

### Steps to reproduce

- Switch to a non-english language with longer text
- Visit `/start/plans` 
- Verify that the discount text in the plan type selector dropdown is obscured by the chevron symbol

### What you expected to happen

Text isn't obscured by symbols

### What actually happened

Text _is_ obscured by symbols

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated


📌 FINDINGS/SCREENSHOTS/VIDEO
Testing in a few different languages:
Spanish:
![Image](https://github.com/Automattic/wp-calypso/assets/86028337/3cd72043-21f9-43de-a58a-f43bbc103209)

Portuguese (Brazil): 
![Image](https://github.com/Automattic/wp-calypso/assets/86028337/b47cf321-ff61-46e0-924e-5b6c0dcea0ff)

Italian:
![Image](https://github.com/Automattic/wp-calypso/assets/86028337/3e307bf5-b295-4d06-8ab0-a1f07080df31)
- In Italian, the final word is cut off

Worth noting that in all languages, the dropdown menu, when expanded, did wrap correctly. 

![Image](https://github.com/Automattic/wp-calypso/assets/86028337/3ca39bf6-530c-443c-9cb7-d06795f19666)


📌 ACTIONS
- Triaged

**Comment by jeyip** [comment]
@saygunnyc Wondering if we have thoughts on how to approach this. My first thought was to mimic what we do with overflow text in the storage add-on dropdown on the same page. I think it would be fine, but I wanted to check in with you as well 🤔 
<img width="168" alt="Screenshot 2024-01-16 at 11 18 42 AM" src="https://github.com/Automattic/wp-calypso/assets/5414230/b3d587f2-0e29-4666-889c-9a2704164ff4">

Another option might be to extend the existing width of the dropdown, or expand it based off of dropdown content rather than rely on an explicitly defined width

**Comment by saygunnyc** [comment]
What's the most extended copy we need to work with? cc @vinimotaa

**Comment by jeyip** [comment]
> What's the most extended copy we need to work with?

Unsure, currently digging up that info 🕵️ . Will update here when I'm able to get a sense of the translations 

_Edit:_

I did an approximation evaluating only the "Pay every 3 years" + "up to x% off" string. In this case it looks to be French Ex. `Payer tous les 3 ans jusqu'à 53% de réduction` at 45 characters with Portuguese close behind cc @saygunnyc 

| [Pay Ever 3 years]( https://translate.wordpress.com/projects/wpcom/es/default?filters%5Bterm%5D=Pay+every+3+years )    |[ up to x% off String]( https://translate.wordpress.com/projects/wpcom/es/default?filters%5Bterm%5D=up+to+%25%28discount%29d%25%25+off ) |
| ----- | ----- |
| <img width="226" alt="Screenshot 2024-01-16 at 11 42 55 AM" src="https://github.com/Automattic/wp-calypso/assets/5414230/a4eebfa0-8c32-4e2f-8d34-227d6c4c6353">      | <img width="296" alt="Screenshot 2024-01-16 at 11 42 51 AM" src="https://github.com/Automattic/wp-calypso/assets/5414230/6fc838ab-ee5f-41d1-bd1b-992a4ceb14ab">       |

**Comment by vinimotaa** [comment]
@jeyip can't we automatically re-scale the dropdown's width based on the content?

**Comment by jeyip** [comment]
@vinimotaa 

Yes! I believe so 🙂 I mentioned that as [an option above ]( https://github.com/Automattic/wp-calypso/issues/86270#issuecomment-1894372336 ). I'll start moving in this direction

> Another option might be to extend the existing width of the dropdown, or expand it based off of dropdown content rather than rely on an explicitly defined width

**Comment by jeyip** [comment]
@vinimotaa So I just checked and there _is_ a width limitation. The stickied plan type selector in the comparison grid needs an explicit width or else it extends past its boundaries 🤔 

<img width="1316" alt="Screenshot 2024-01-16 at 12 32 41 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/7c1dd616-8206-47f2-8b54-2551334df910">

The GIF below provides more context about what happens when we adapt width to the dropdown's content

![2024-01-16 12 38 49](https://github.com/Automattic/wp-calypso/assets/5414230/95670928-f3f3-4115-b902-3377d352458d)

**Comment by vinimotaa** [comment]
I see - what if we take this similar approach?

![image](https://github.com/Automattic/wp-calypso/assets/97929097/21bba765-3b30-44ad-a601-d41c7ba3c5b0)

**Comment by jeyip** [comment]
To clarify, the screenshot above doesn't show the case where an option is selected. They only describe what happens when a dropdown is clicked _prior_ to a selection being made.

In our case, the overflow is occurring when a selection is made.

![Screenshot 2024-01-10 at 12 22 06 PM](https://github.com/Automattic/wp-calypso/assets/5414230/069d1339-3074-4de2-8152-9b558a66e862)

Here's the behaviour of the storage add-on dropdown when an item is selected that would overflow the container. 

<img width="168" alt="Screenshot 2024-01-16 at 11 18 42 AM" src="https://github.com/Automattic/wp-calypso/assets/5414230/b3d587f2-0e29-4666-889c-9a2704164ff4">

I believe this should work for us like I mentioned [here]( https://github.com/Automattic/wp-calypso/issues/86270#issuecomment-1894372336 ), but just want to confirm that this is what you're suggesting @vinimotaa ?

**Comment by vinimotaa** [comment]
> @vinimotaa So I just checked and there is a width limitation. The stickied plan type selector in the comparison grid needs an explicit width or else it extends past its boundaries 🤔

I think this could work - what if we don't display the "up to %" when the user scrolls down for the comparison?

**Comment by jeyip** [comment]
> what if we don't display the "up to %" when the user scrolls down for the comparison?

This sounds reasonable to me, and is better than what we have now 👍 After looking at the code, it's also worth noting that we _do_ hide the discount hover popup message for the plan type toggle in the stickied comparison grid header

I still, however, see value in us displaying the calculated discounts to entice the user, and I've been working on a PR that would [allow us to more easily detect visual element overlap]( https://github.com/Automattic/wp-calypso/pull/86508 ). I'll pause it for now to implement your suggestion, but the aforementioned PR should set us up for success if / when we revisit this interaction.

**Comment by jeyip** [comment]
> I think this could work - what if we don't display the "up to %" when the user scrolls down for the comparison?

The primary issue of text overflow is addressed so I'm closing this issue, completed in https://github.com/Automattic/wp-calypso/pull/86560.

I think I'll make a follow-up issue to track the idea of figuring out a way to display discounts to the user, even when they're scrolling through the comparison grid. We can continue discussions there and explore it when some bandwidth frees up.

**Comment by vinimotaa** [comment]
@jeyip sounds good J., could you assign this and any other issue with Design Needs to me, please? So I don't lose track of them over time. Thank you!

**Comment by jeyip** [comment]
Created a new issue here https://github.com/Automattic/wp-calypso/issues/86717
