### ISSUE TITLE
Marketplace: iterate on failed webhooks strategy

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#86280]
Right now, we attempt to deliver the webhook only two times. If it doesn’t respond with a 200 status code, we don’t take any action and consider it a failure. I think we should focus on improving this by retrying the delivery of webhooks until we receive acknowledgement.

IDEA:
We can slightly increase the number of retries and when it eventually fails we could send an email to the vendor so they can take action? Doing so will
- Provide them with all webhooks missed
- Alert them to fix their infrastructure

Related: p1704931037285919-slack-C02JPCHEKDY

**Comment by gavande1** [comment]
Backlog Grooming: Closing the issue for now. Reopen if needed.
