### ISSUE TITLE
Subscription Modal bug: it shouldn't scroll up

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#86294]
I was testing the Subscription Modal on one of my testing sites, and noticed that when I click "Continue Reading", it automatically scrolls up.

UX-wise it doesn't make sense, because it's triggered while the user is reading, so we make them scroll down again to continue reading.

Also, the `Continue Reading` should be a sentence case, not a title case.

https://github.com/Automattic/wp-calypso/assets/25607244/0397dc1b-4882-492b-92cf-0baa1a52e69d

In this second example, I scrolled while the modal was visible to make it more obvious:

https://github.com/Automattic/wp-calypso/assets/25607244/9cded8b7-43dc-4ff6-b77c-d2279f72ef34

**Comment by pkuliga** [comment]
Seems like a bug. I will take care of it. Thanks for reporting!
