### ISSUE TITLE
Checkout: validation errors on mobile

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#863]
Originally reported by @scruffian.

If I have an error when checking out on mobile, it becomes difficult to complete the checkout form, because the errors hide the fields, so I can't edit them. When I scroll the error doesn't move away, so I have to dismiss it. The obvious solution to this is show the errors inline, but that's not a quick fix.

![img_2759](https://cloud.githubusercontent.com/assets/275961/10190572/82d07678-6765-11e5-88f3-c1cad4ddcba7.jpg)

**Comment by gziolo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [M | Checkout: validation errors on mobile](https://trello.com/c/CUb7tum9/251-m-checkout-validation-errors-on-mobile)

**Comment by gziolo** [comment]
It looks like CSS handling has changed a bit.

360x640:

![screen shot 2016-10-05 at 14 12 16](https://cloud.githubusercontent.com/assets/699132/19112564/ce52f78c-8b05-11e6-9f9b-555a524bb97c.png)

412x732:

![screen shot 2016-10-05 at 14 13 16](https://cloud.githubusercontent.com/assets/699132/19112577/e431a422-8b05-11e6-8bcb-7c659a04acd0.png)

320x568:

![screen shot 2016-10-05 at 14 13 48](https://cloud.githubusercontent.com/assets/699132/19112608/007cf76c-8b06-11e6-9fc4-f834ed97929d.png)

@mtias @folletto @breezyskies @MichaelArestad Do you feel like we really should be able to inline error messages or should we rather make sure we don't create such long error notices? :D

I think that we might also show only the first error for a given field in this case or even figure out if we could group errors by type.

**Comment by folletto** [comment]
> should we rather make sure we don't create such long error notices

Definitely this. We haven't discussed this thoroughly so might be just my opinion, but any notice that is longer than a few words, one line, should be reconsidered.

That said, this one probably requires some kind of quick fix to start with. :P

**Comment by gziolo** [comment]
@fabianapsimoes It looks like this issue happens only when you click `Save Card` or `Checkout` button (depending on the flow) on the empty form. We might also display all messages only when user tries to submit form, but display only the last message when user goes to the next field? Then we would make it much more user friendly as a bonus :)

**Comment by fabianapsimoes** [comment]
Yep, that seems to be the case indeed. I'm going to page @ranh and @breezyskies here, with regards to simplifying the copy and input on when to display the messages. I like the suggestion to show validation on blur, but I wonder if it can get annoying easily.

**Comment by ranh** [comment]
I agree that this notice could use a rethink. Both the copy and the presentation are not ideal. For example terms like "issue", "field", and "invalid" don't have to be used. There is unnecessary repetition for every field that is missing, when a simple "please fill all missing details" might have been enough.

I can help out with copy based on how we decide to proceed.

**Comment by gziolo** [comment]
I double checked what is the current status of HTML5 form validation. It looks like it has improved a lot and it works almost in 100% for the browsers we support. See http://caniuse.com/#feat=form-validation.

I think it would make perfect sense to use built-in HTML form validation when user types in form fields, and only show notice when user tries to submit the form. What do you think?

I also did an experiment and added `required` property to all form fields. This is how it changed validation flow:

![form-validation-required](https://cloud.githubusercontent.com/assets/699132/19151714/7d744180-8bce-11e6-8754-af13c27c2249.gif)

It was super simple change and without too much thinking reduced list of errors to the absolute minimum. We are able to inline also invalid field errors messages in a similar fashion.

**Comment by fabianapsimoes** [comment]
@gziolo Oh, interesting! How much can we style the native validation messages, so it's closer to Calypso's feel?

**Comment by gziolo** [comment]
I'm bet we can customize it fully :) I'm sure we can customize error messages. I have seen also articles where they suggest hiding default messages and provide own experience instead. I'll explore it further tomorrow.

**Comment by gziolo** [comment]
@fabianapsimoes it turns out we don't have any control over UI of the error messages. Every browser provides their own styles. We can only change the message displayed to the user.

Taking that into account, we probably should skip all HTML5 implementations and move error handling inline like this if we want to keep one style of handling forms in Calypso:

![screen shot 2016-10-07 at 12 36 10](https://cloud.githubusercontent.com/assets/699132/19187363/57f0bbba-8c8b-11e6-9b4d-f121cff8d599.png)

Though with the current design of the form it can be hard to provide flexible solution for the longer error messages.

**Comment by breezyskies** [comment]
> Though with the current design of the form it can be hard to provide flexible solution for the longer error messages.

This is a known issue, and one of the reasons we haven't moved to inline validation yet, as it would require a rethink of the form design (and likely a/b testing to make sure there isn't any major impact on revenue). The checkout form was one of the earliest pieces that we designed for Calypso store, so it's quite out of sync with the current patterns.

The simplest option here would probably be moving country and postal code to their own line, giving both a bit more room for inline validation, all fields going to full width at the <480px breakpoint. A quick inspector mockup:

<img width="608" alt="screen shot 2016-10-07 at 7 12 16 am" src="https://cloud.githubusercontent.com/assets/3011211/19193070/7194dd68-8c5d-11e6-8f86-18717ff251aa.png">

Another thing noted in checkout is that the label originally used the ["float label" pattern](http://bradfrost.com/blog/post/float-label-pattern/), but that appears to be broken, causing a usability problem (once you start typing in a field, there's no longer any indication of what that field is). We should probably update to use the Calypso standard labels at this point (this could be handled in a separate PR but just wanted to note it here). @mikeshelton1503 previously mocked up a version of this for Purchases:

<img width="679" alt="screen shot 2016-10-07 at 7 20 34 am" src="https://cloud.githubusercontent.com/assets/3011211/19193401/c166c120-8c5e-11e6-820d-ceea09e4be80.png">

**Comment by gziolo** [comment]
With #8666 I want to address form fields changes:

> The simplest option here would probably be moving country and postal code to their own line, giving both a bit more room for inline validation, all fields going to full width at the <480px breakpoint.

Then I would like to create a follow-up PR where we could add logic to AB test changes related to error handling and maybe experiment with the "float label" pattern.

**Comment by Copons** [comment]
Closing because this was effectively tackled in #8666, and it now appears like this:

<img width="447" alt="screen shot 2018-03-08 at 15 50 00" src="https://user-images.githubusercontent.com/2070010/37160577-74f6181e-22e8-11e8-9b71-937000a29cd2.png">
