### ISSUE TITLE
Reader: "subscribe" visible to RSS feed posts

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#86304]
### Quick summary

The subscribe button returns an error when attempting to subscribe to rss feeds. Subscribing to RSS feeds is possible on individual post pages. It should be possible to subscribe on the feed page.

Done means:
- [ ] The subscribe button on the feed page works example feed: https://wordpress.com/read/feeds/1218003

### Steps to reproduce

1. Add RSS feed to Reader
2. Find post
3. It'll try offer subscribe
    <img width="675" alt="Screenshot 2024-01-11 at 17 55 50" src="https://github.com/Automattic/wp-calypso/assets/87168/e75b792f-3390-4bce-ab7b-f05e1f021b9e">
5. Cannot
    <img width="696" alt="Screenshot 2024-01-11 at 17 55 58" src="https://github.com/Automattic/wp-calypso/assets/87168/7be81a8a-593f-40f6-8c13-47b39fe60fcc">

### What you expected to happen

— no "Subscribe" for RSS feeds (but maybe some indications it's from RSS?

### What actually happened

Error

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by roo2** [comment]
hmmm interesting, I think you should be able to subscribe to RSS feeds the same as other feeds. Maybe I'm not understanding this correctly(?)

e.g. if I go to the feed for hacker news feed here https://wordpress.com/read/feeds/1218003 I should be able to subscribe as normal.

**Comment by simison** [comment]
@roo2 Good point!

In this case it was from my own feed, so I'm already subscribed to the feed. So I should see "Unsubscribe RSS" or something like that?

**Comment by simison** [comment]
It might make sense to treat subscribing to RSS slightly separately, and perhaps use separate terminology to set expectations right? It works different from regular subscribing.

- Subscribe to RSS
- Follow RSS

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Reader
– Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my side:
![Markup on 2024-01-15 at 20:20:07](https://github.com/Automattic/wp-calypso/assets/9025643/e8458a67-ad2e-43dd-8788-1ed3d2f5ad76)

📌 ACTIONS
-Triaged

**Comment by lsl** [comment]
This looks like a bug,

You can subscribe to the feed here: https://wordpress.com/read/feeds/1218003/posts/5321298255

But not here: https://wordpress.com/read/feeds/1218003/

![Screenshot(226)](https://github.com/user-attachments/assets/0b677e7c-c83e-4cf1-a11a-ff0352d4de6d)

![Screenshot 2024-07-25 at 15-54-56 Manage subscriptions — WordPress com](https://github.com/user-attachments/assets/27d921af-2e51-4a2f-8175-d345d3ebd9ac)

**Comment by lsl** [comment]
Doesn't look high priority, but should be an easy fix. Cherry picking to the dev board for now.
