### ISSUE TITLE
Action bar: Icon misalignment

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#86305]
![Screenshot 2024-01-11 at 8 01 17 AM](https://github.com/Automattic/wp-calypso/assets/5835847/60f5c623-6496-401a-83ca-9ce41287b2ac)

`Customize` and `Subscribed` icons are stacked instead of inline with the label.

cc @davemart-in

**Comment by davemart-in** [comment]
Thanks for the heads up. We'll get this fixed.

**Comment by davemart-in** [comment]
Patch is up for testing here: D134598-code

**Comment by davemart-in** [comment]
Should be fixed with D134598-code
