### ISSUE TITLE
Like block: “likes” copy inconsistency in Portuguese

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#86311]
"likes" copy in Portuguese (pt-br) is inconsistent between the link and the popover.

- 1 like: `1 curtida` (link and popover)
![Image](https://github.com/Automattic/wp-calypso/assets/3113712/4194ee40-764f-4fe5-be6a-f7079cd7eb71)
![Image](https://github.com/Automattic/wp-calypso/assets/3113712/5ab86693-c632-4b18-a469-eefb7b270e24)

- n likes: `n curtidas` (link) and `n curtiram` (popover)
![Image](https://github.com/Automattic/wp-calypso/assets/3113712/a95996f5-d87e-4fcb-a3e4-bf1ce1201fbf)
![Image](https://github.com/Automattic/wp-calypso/assets/3113712/6f91c9c2-a9bb-4ae1-8afe-b0abcc259538)

**Comment by yansern** [comment]
The respective language strings are:
`<a href="%1$s" id="%2$s">%3$s likes</a>`
https://translate.wordpress.com/projects/wpcom/pt-br/default?filters%5Bterm%5D=%3Ca+href%3D%22%251%24s%22+id%3D%22%252%24s%22%3E%253%24s+likes%3C%2Fa%3E&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

`%d likes`
https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=33421&filters%5Btranslation_id%5D=3489109

Which is part of the json-strings.php file.
https://translate.wordpress.com/developer/?path=wp-content/js/jed/json-strings.php

Well, not sure if `curtidas` or `curtiram` is correct to you, but you can update the language strings in those respective links.

**Comment by phcp** [comment]
Thanks for finding that @yansern. `curtiram` fits more on a full sentence. I think the most used is `n curtidas`, and it's also the word the translators choose on the singular version. I'll update that.

**Comment by phcp** [comment]
Translators just started working on it, and the old translation `curtiram` is now invalidated, so it should be correct after the deploy.

**Comment by ivan-ottinger** [comment]
The correct translation (`n curtidas`) is in place already. 👍🏼 

![Markup on 2024-01-22 at 11:39:26](https://github.com/Automattic/wp-calypso/assets/25105483/9935022d-8189-43d9-b7eb-1a37b5302e8d)


→ Closing this issue as done. ✅ 🙂
