### ISSUE TITLE
Jetpack NUX: add signup flow for user-account only, for Post Likes

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8631]
We don't have a smooth flow for liking a Jetpack post as a non-WordPress.com user.
#### What I expected

There doesn’t appear to be an easy way for a non-WordPress.com user to quickly create an account to simply ‘like’ Jetpack content. Say I am not a WordPress.com user and I come across a site running Jetpack with Likes enabled.
#### What happened instead

When I click ‘Like’ a popup appears for WordPress.com – this doesn’t have any explanation of why a WordPress.com account is needed to ‘like’ something on a non WordPress.com site.

I click ‘Register’ to create an account, and I see the first step to create a site?!?

I click “Sign Up” in the top right but I am redirected to the same page

I didn’t want to create a blog or a site, I simply wanted to like an article. I give up and close the popup.
#### Ideas for improvement
1. We should add explanatory text to this popup to say that liking content on a WordPress site requires you to use a WordPress.com account.
2. We should have a signup flow from the Like button specifically for an account — not a site.
#### Context / Source

From a recent #dogfooding session by @alisterscott

**Comment by alisterscott** [comment]
Confirmed this is still an issue:

1. Visit http://angryweasel.com/blog/ in incognito window not logged into WordPress.com
2.Click Like
3. Redirected to wordpress.com login which then links to creating a site

Possibly being addressed in `p6qnuF-4gP-p2`

**Comment by alisterscott** [comment]
Re-tested this flow, whilst there's no explanatory text on the pop-up, using the social sign-in worked and closed the pop-up and liked the article. So it's much better than previously.

**Comment by alisterscott** [comment]
This is also mentioned in https://github.com/Automattic/wp-calypso/issues/2019
