### ISSUE TITLE
Don't assume that a free A8C theme can be downloaded from wp.org

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#86316]
### Quick summary

The wpcom rest APIs use the WP.org download link for free Automattic themes. The Calypso download **card** uses this URL. We publish themes to WordPress.com, first and WordPress.org second, this means that until the theme is published on WordPress.org, the download URL will 404. Some free themes might not ever get published on WP.org.

The lag between being published on WordPress.com and WordPress.org can be quite long - wporg has its own review process and we publish a lot of themes.

### Steps to reproduce

1. Go to wordpress.com/themes
2. Find a free theme that isn't published on WordPress.org yet. Epi currently is one of these.
3. Press the Download button on the card

![image](https://github.com/Automattic/wp-calypso/assets/93301/fdb1ad1b-2c3b-435b-a3ae-8a9270224d17)

### What you expected to happen

My browser would start downloading a zip

### What actually happened

My browser displayed a 404 message

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

The workaround is that many free themes actually have two download links, the other one works! This is still confusing to users, and gives us less control over when and how to display the download button.

The code in question is `WPCom_Theme_Query::get_download_uri` (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sgurzrf%2Srynfgvpfrnepu.cuc%3Se%3Q47q19q6o%23604-og). Themes can be downloaded from https://public-api.wordpress.com/rest/v1/themes/download/SLUG.zip

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated / Could Not Replicate / Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue:
![Markup on 2024-01-15 at 20:26:27](https://github.com/Automattic/wp-calypso/assets/9025643/f827e738-2daa-4d88-bf76-d7e62e12cfdd)


File not available:
https://downloads.wordpress.org/theme/epi.zip

📌 ACTIONS
- Triaged

**Comment by dsas** [comment]
I don't think this is actually needed. I misread the code before, it will only try a dotorg link if the theme isn't premium AND if it can't get a wpcom download link.

That some of our free themes aren't downloadable on dotcom or dotorg is a separate problem - a step missed in the theme launch process for some themes, that I think I've already tackled for those themes
