### ISSUE TITLE
Update Doc Link in Domain Transfer Status Icon

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#86314]
### Quick summary

The link in the information icon when a domain transfer is pending or failed links to https://wordpress.com/support/domains/incoming-domain-transfer/#pending - which is an invalid link at this time. 

It should be updated to https://wordpress.com/support/domains/incoming-domain-transfer/#step-4-check-the-transfer-status

### Steps to reproduce

1. Initiate a Domain Transfer
2. Click the ? next to the status (pending/failed or other appear to all link to the same URL)

### What you expected to happen

The icon should link to the section in the Domain Transfer doc that explains the transfer statuses, found https://wordpress.com/support/domains/incoming-domain-transfer/#step-4-check-the-transfer-status

### What actually happened

The link goes to an invalid jump link here: https://wordpress.com/support/domains/incoming-domain-transfer/#pending

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my side

📌 ACTIONS
- Triaged
