### ISSUE TITLE
Like block: Likers popover overflows on mobile screens when the reblog button is present

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#86312]
![Image](https://github.com/Automattic/wp-calypso/assets/3113712/62cd3ad3-928f-4cdd-b46e-040c67c9da78)

**Comment by yansern** [comment]
Patch here: D134509-code

Needs one more for Jetpack coming up in next. Context: p1705055504756729-slack-C02TCEHP3HA

**Comment by yansern** [comment]
Jetpack patch here. https://github.com/Automattic/jetpack/pull/35065
