### ISSUE TITLE
Like block: Reblog button overflows with the 3-column or 2-column layouts

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#86315]
Tested with Portuguese (pt-br) as site language:
![Image](https://github.com/Automattic/wp-calypso/assets/3113712/b98c7b1e-778b-45c7-acad-f73c7ddb89c8)

Tested with Hebrew as site language (overflows with 3 columns and break line with 2 columns):
![Image](https://github.com/Automattic/wp-calypso/assets/3113712/ed5bc7c0-06a0-4178-8756-0a947296570d)

**Comment by TimBroddin** [comment]
It also happens on the frontend, so it's more of a like widget issue tbh

**Comment by TimBroddin** [comment]
Fixed in D135469-code

**Comment by ivan-ottinger** [comment]
Marking as closed.
