### ISSUE TITLE
New Post Notification Email: `Read more of this post` link is not clickable if it falls into or somewhere around a quote block

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#86338]
### Quick summary

When the post notification email is set to only display an excerpt, and the truncation happens where a Quote block is placed within the post, the automatically generated link `Read more of this post` is not clickable.

### Steps to reproduce

1. Add a paragraph block with text `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ` or somwhat similar length.
3. Add a quote block with text `Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`
4. Click publish and then `Send test email` in the pre-publish check window
5. Check the post notification email in your inbox

### What you expected to happen

The `Read more of this post` text to always be clickable.

### What actually happened

`Read more of this post` is not clickable if it falls into or somewhere around a quote block

Examples:
![Screenshot on 2024-01-12 at 08:40:38](https://github.com/Automattic/wp-calypso/assets/39308239/8d930fb9-41be-4fd8-b394-19276e15453f)

<img width="2581" alt="Screenshot 2024-01-11 at 20 35 12" src="https://github.com/Automattic/wp-calypso/assets/39308239/840c022a-ff86-4139-8499-1024cf03fe64">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

There is design work happening around email templates here https://github.com/Automattic/wp-calypso/issues/85230 so I think the above can be taken by the team.

**Comment by OmarFPG** [comment]
7539224-zen

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS


– Tested on Simple - FSE and Classic theme: Could Not Replicate
- Tested on Atomic: Could Not Replicate



📌 FINDINGS AND SCREENSHOTS

Despite my best efforts, could not replicate on Simple with an FSE theme, or a Classic theme.

![Screenshot 2024-01-16 at 14 39 04](https://github.com/Automattic/wp-calypso/assets/2540430/9f709494-68b8-4797-aed9-56b2ed979ee8)



📌 ACTIONS
– Requested author feedback


📌 Message to Author

@zdenys, thank you for the report.
I wonder if I am missing any detail here, as I could not replicate.
Despite being inside the quote block, the link worked for me.

Would you mind giving this another try?
Thank you!

**Comment by OmarFPG** [comment]
7539224-zen is reporting this bug in 13 of their past 39 emails. They've included a screenshot where it shows another post with a block quote near the beginning of the post.

**Comment by filipanoscampos** [comment]
Thanks @OmarFPG .

📌 REPRODUCTION RESULTS

– Tested on Simple - FSE and Classic theme: Could Not Replicate
- Tested on Atomic: Could replicate when the content is inside a Classic Block or the site is using the Classic Editor.



📌 FINDINGS AND SCREENSHOTS

Was able to replicate this when the content is inside the Classic Block or the site has the Classic Editor plugin active.
![Screenshot 2024-01-16 at 15 56 40](https://github.com/Automattic/wp-calypso/assets/2540430/be7f9d9d-4daf-476b-b819-492b95d95c4f)


Yet, not in the Block editor.

As soon as I convert the content to blocks, the link works again:
![Screenshot 2024-01-16 at 15 58 55](https://github.com/Automattic/wp-calypso/assets/2540430/5e05f702-5928-4aed-9a90-caaadb4a35d8)

Waiting on author feedback.

**Comment by simison** [comment]
Related:

- Bug https://github.com/Automattic/wp-calypso/issues/86037
- Visual improvements https://github.com/Automattic/wp-calypso/issues/83715

**Comment by OmarFPG** [comment]
@filipanoscampos the user replied:

> Classic Editor. I had the same issue on this morning's post but I noticed WP added a ‘read on blog’ link found at the top right corner of the email which should help over time. 

> Readers are still looking for the 'read more' link at the bottom though.

**Comment by renata-franco** [comment]
The user from 7539224-zen has now reported that their last email did not share the Featured Image on the email message. It can be seen in the Reader, but not via email. Keep in mind this user only has Classic Editor, and nothing with Block Editor. They shared the following screenshot attached. All the settings on this site are correct, and the post contains a Featured Image as always, so it should display. 

Post: https://homeiswheretheboatis.net/2024/01/29/baked-fresh-in-your-dutch-oven-the-easiest-no-knead-artisan-bread/

![image](https://github.com/Automattic/wp-calypso/assets/81378719/85928fbc-ceb1-4cf3-9753-6cb5fc372946)

Is this related? Or different?

**Comment by mmtr** [comment]
FWIW, I cannot replicate this issue, I can see a "Continue reading" button that is clickable:

![Image](https://github.com/user-attachments/assets/16fcb2cd-0aa5-45bd-a815-7e9b2e13866c)
