### ISSUE TITLE
"Your free trial has ended" page has no bottom margin / padding

### ISSUE THREAD

**Issue by ecgan** [Automattic/wp-calypso#86417]
### Quick summary

I have a Woo Express site with an expired trial. When I view the "Your free trial has ended" page (`https://wordpress.com/plans/my-plan/trial-expired/<domain>`), there are no padding / margin at the bottom of the page, i.e. the "Export your content" and "Delete your site permanently" buttons are touching the browser window border. See screenshot below: 

![image](https://github.com/Automattic/wp-calypso/assets/417342/8011d750-e97f-4279-8b45-eddaa06c1089)

It seems like the issue happens in certain screen widths.

### Steps to reproduce

1. Have a Woo Express site with an expired trial plan.
2. Visit the "Your free trial has ended" page.

### What you expected to happen

There should be some margin / padding at the bottom of the page, between the buttons and the browser window border.

### What actually happened

There are no margin / padding between the buttons and browser window border.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by Aurorum** [comment]
PR in https://github.com/Automattic/wp-calypso/pull/86883. :)
