### ISSUE TITLE
Checkout sidebar has an error for wpcom-enterprise plan

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#86420]
Visit https://wordpress.com/checkout/wpcom-enterprise

Notice the error in the sidebar:

<img width="566" alt="Screenshot 2024-01-15 at 12 27 19 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/002deffe-6547-497a-9a9a-b0acb7dc5356">

<img width="518" alt="Screenshot 2024-01-15 at 12 28 12 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/acaef9b7-0ee2-441c-bf89-4da5f3f96ab1">

**Comment by sirbrillig** [comment]
This comes from here: https://github.com/Automattic/wp-calypso/blob/a57559c9736e9a26f66405f12f6ad7f28b8b2e03/packages/calypso-products/src/main.ts#L572 in `calculateMonthlyPriceForPlan()` when `PLANS_LIST` (https://github.com/Automattic/wp-calypso/blob/a57559c9736e9a26f66405f12f6ad7f28b8b2e03/packages/calypso-products/src/plans-list.tsx#L2533) has no entry. Maybe because this product is rarely purchased, no entry was ever added to that list?

**Comment by jjchrisdiehl** [comment]
> ) has no entry. Maybe because this product is rarely purchased, no entry was ever added to that list?

I guess I never thought "should this be purchasable?" Could we just redirect this url to https://wpvip.com/wordpress-vip-agile-content-platform/?

**Comment by sirbrillig** [comment]
Hm... maybe, although it might be hard to figure out where to put that logic. If we want to prevent it from being purchased, we should block it in the shopping-cart endpoint (the cart validator).

Two other possible fixes are:

Add it to `PLANS_LIST`.

or

Change `calculateMonthlyPriceForPlan()` (and probably other functions, depending on what exactly triggers this) so that it fails more elegantly if the plan isn't found.

**Comment by michaeldcain** [comment]
> Maybe because this product is rarely purchased, no entry was ever added to that list?

I don't think this plan should be available. It predates monthly plans and the only purchase in the last 3 years was an accidental assignment from SA. We should probably mark it as unsellable in the Store Products table.

p1705350068656149/1705344435.322189-slack-C096PD42U

**Comment by michaeldcain** [comment]
From planning:

> We should probably mark it as unsellable in the Store Products table.

This was a bad idea. It would prevent people from renewing.

Since we don't generally add product-specific guards against new purchases in the Shopping Cart, let's go ahead and add a guard in the sidebar to prevent the features list from fataling when no product is found. Marking this as a quick fix for next week's quick fix sprint.

**Comment by sirbrillig** [comment]
For reference, I reproduced this in a localhost environment to get a real stack trace and it's happening in the `CheckoutSummaryPlanFeatures` component. 

```
Uncaught Error: Unknown plan: wpcom-enterprise
    at applyTestFiltersToPlansList (main.ts:684:11)
    at getPlanFeatures (get-plan-features.ts:26:113)
    at CheckoutSummaryPlanFeatures (wp-checkout-order-summary.tsx:574:91)
```

We should be able to add a `try/catch` to where that component is calling `getPlanFeatures` and show something as a default instead.

**Comment by inaikem** [comment]
@sirbrillig 👋 Checking to confirm with you if this issue should be closed. I see you marked it as done last Monday. Thanks!

**Comment by sirbrillig** [comment]
@inaikem 🤔 No, I don't think so. I believe that _you_ marked it as closed (possibly accidentally) on October 13, then re-opened it on that same day. However, when it was closed it was removed from our team's board so I restored it to the board.

**Comment by inaikem** [comment]
Thanks @sirbrillig 🙇‍♂️ The marking-as-done was the result of an over-eager workflow on the Group Triage Board. I've corrected the errors now.

I'd like to understand more about the issue and decide if it needs moving off The One Board. Based on what I've been able to gather, this is a VIP plan and not related specifically to WPcom or the Dotcom BU. Is that a valid assessment? If so, would you be ok with me moving it off The One Board?

**Comment by sirbrillig** [comment]
Yeah, that sounds fine. IIRC this is a minor bug for a product we no longer sell and is just being tracked on our team board for a hack week or other bug fix sprint.

**Comment by inaikem** [comment]
Perfect, thanks!

Secondary question: I'd like to find a way to tag/track issues in this repo that are not and don't need to be on The One Board. I was thinking of:

1. Adding a label to denote the issue as "Non-Dotcom", or
2. Moving the issue to a private repo like `gh-Automattic/dotcom-forge`

However, I'd like a confidence check in case there is a better, less clunky option. Any thoughts?

**Comment by sirbrillig** [comment]
Hm... it's tricky. I don't think there's a way to move issues between repos apart from recreating them which is not ideal (although our team does have its own repo). Labels are a cheap option that could work well. Let me loop in @michaeldcain to see if he has any other ideas.

**Comment by inaikem** [comment]
I can confirm we can 100% transfer from public to private repos in our GitHub org, (which is what this would be). 

Going in the other direction, or cross-org like Calypso to Core, would require the issue to be recreated from scratch.

What's driving this question is that ultimately, I'd like to ensure that:

- Anything that should be public remains so (and is prioritised accordingly). 
- Internal tooling/non-public data is moved to an appropriate repo.

I appreciate not everything can be clear-cut, so I appreciate this discussion!

**Comment by sirbrillig** [comment]
Oh! Great. If I remember this issue correctly, the problem is user-facing in calypso (there's an error when visiting a particular checkout route that is displayed to the user). It's only for a specific product but the main problem is that this error can happen at all and is a result of the architecture of some components in checkout. In my mind, that makes it an issue for the public calypso repo, but I'm open to other opinions.

The fix seems to be:

> Since we don't generally add product-specific guards against new purchases in the Shopping Cart, let's go ahead and add a guard in the sidebar to prevent the features list from fataling when no product is found.

Specifically, we need to add a guard in the `CheckoutSummaryPlanFeatures` component to prevent this error.

To update my above research, the error is specifically here:

https://github.com/Automattic/wp-calypso/blob/efe93c9c860d3cfd4bbc7b083fbb30a581acc176/client/my-sites/checkout/src/components/wp-checkout-order-summary.tsx#L726-L733

That function call should not throw a fatal if the product doesn't exist.

Since I've done the research again, I decided to just go ahead and fix this bug: 

- https://github.com/Automattic/wp-calypso/pull/95827
