### ISSUE TITLE
[Bug] Site Profiler: loading button has wrong stripe colors

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#86423]
If you check a URL while being logged in, the stripes of the loading state of the CTA have an incorrect color combination. This becomes more noticeable when you use the Default theme, where the loading state becomes pink with blue stripes.

https://github.com/Automattic/wp-calypso/assets/4933/8125c933-7875-4d3d-985a-479a59fcca89

Users not logged in don't seem to have this problem.

Reported here: p1705342639803899-slack-C9EJ7KSGH (thanks, @crisbusquets!)

**Comment by Aurorum** [comment]
Is this meant to be a conventional primary button (ie. pink in the Default scheme) or is it meant to be blue for all users, including signed in ones?

**Comment by javierarce** [comment]
It should respect the active theme and its defined accent, as you can see [here](https://wpcalypso.wordpress.com/devdocs/design/button).

**Comment by cat-og** [comment]
📌 FINDINGS
Issue is being worked on here; https://github.com/Automattic/wp-calypso/pull/86464

📌 ACTIONS
- Triaged
