### ISSUE TITLE
Bug: Subscribe block disabled email isn't accessible

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#86451]
Related to https://github.com/Automattic/jetpack/pull/34982

When the theme is dark, if the input is disabled it becomes unreadable:

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/c34c7483-0b90-4dfe-af80-f241be485551)

Site: https://gameuidesign.wordpress.com/2024/01/09/embarking-on-a-ui-ux-journey-from-unreal-engine-menus-to-figma-designs/

**Comment by simison** [comment]
Theme is Spiel — might need updating the theme styles.

**Comment by simison** [comment]
Yep, just any disabled input doesn't look good on footer on Spiel, but looks good on content:

<img width="248" alt="Screenshot 2024-01-16 at 12 07 59" src="https://github.com/Automattic/wp-calypso/assets/87168/4ad06f22-716b-41be-87bf-185b6912322a">
<img width="219" alt="Screenshot 2024-01-16 at 12 07 34" src="https://github.com/Automattic/wp-calypso/assets/87168/49b8ba4d-4483-4807-a41f-962f4fc3d6ea">

cc @iamtakashi I think you worked on the theme?

**Comment by iamtakashi** [comment]
@simison, what do you mean by updating the theme style? Adding a custom CSS for the disabled state? I think this is something the block should handle, not themes.

**Comment by simison** [comment]
@iamtakashi in [above screenshots](https://github.com/Automattic/wp-calypso/issues/86451#issuecomment-1893432062) I didn't use the block, simply had inputs in the HTML and it still didn't quite work:

```html
<input type="text" disabled value="text" />
```

So any block outputting disabled state would have the same problem. Happy to add some styles to the block as well if you recon that's truly better.

**Comment by iamtakashi** [comment]
Yes, until themes can style the imput element in the Global Styles, the plugin should style it better to work on both dark and light backgrounds.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
It looks as though a solution here is already in progress! 

📌 ACTIONS
- Triaged

**Comment by simison** [comment]
Spotted also for Nook theme (https://nookdemo.wordpress.com/)

<img width="453" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/8d95bccb-9a4d-4c05-8787-901a2d39237a">

**Comment by crisbusquets** [comment]
Spotted here: https://igrowit23.wordpress.com/

Theme: Creatio 2
<img width="366" alt="Screenshot 2024-01-26 at 11 39 37" src="https://github.com/Automattic/wp-calypso/assets/25607244/099e0ce2-9755-48ae-9e62-971ea2ef8a56">

**Comment by crisbusquets** [comment]
Also here: https://onehiddenthing.com/

Theme: Twenty Twenty-Four (highly customized)
<img width="594" alt="Screenshot 2024-01-26 at 11 42 49" src="https://github.com/Automattic/wp-calypso/assets/25607244/a25cc325-ca40-4840-a549-7f20bb78e17b">

**Comment by crisbusquets** [comment]
Found [another](https://freeskillify.blog/) one. Bedrock theme:

<img width="471" alt="Screenshot 2024-02-22 at 10 47 26" src="https://github.com/Automattic/wp-calypso/assets/25607244/85d02c2a-1307-4935-b088-b12be8fb9f36">
