### ISSUE TITLE
Like block: Multiple Like blocks on one page confuse the "other likers" popover

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#86456]
When we have multiple Like blocks on one page and click on more than one of them, the "other likers" popover gets confused and and displays the same liker multiple times:

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/4c107e53-e467-4000-beb2-3d914e05fbf9)

Once the page is reloaded, all is back to normal.

**Comment by yansern** [comment]
Patch: D135012-code

**Comment by ivan-ottinger** [comment]
D135012-code is now in production. 🚀 
→ Closing this issue and marking it as ✅ done.
