### ISSUE TITLE
Theme Showcase: Right column cut off when longer than left column on larger screens

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#8646]
While starting to add longer featured images to themes, we discovered that if a long screenshot in the right column is **longer** than the content in the left column, the right column gets cut off.

To replicate:

1. Add a long screen as featured image for a theme
2. Make browser window large on desktop screen 
3. View theme page on front end and croll to bottom of page

## Result

Bottom of featured image is cut off.

## Expected

You should be able to scroll to see the entire height of the image in the right column.

## Example - Overview Tab

![bosco theme wordpress com-1](https://cloud.githubusercontent.com/assets/7662449/19270238/fcb04ef0-8f8c-11e6-94a0-b412c8401f8b.png)

Taken at https://wordpress.com/theme/bosco **before** we uploaded a shorter screenshot, which mitigates the issue. 

## Example - Support Tab

Visit:

https://wordpress.com/theme/bosco/support

https://wordpress.com/theme/babylog/support

Since the Support panel content is always short, any longer screenshot will always be cut off when viewing it, for every theme that has a longer featured image.

## Screencast - Babylog

I made a screencast to show how you cannot get to the footer part of the screenshot in Babylog, at the URL above:

https://cloudup.com/cOn2R93pIjl

Tested in Firefox 49.0.1

**Comment by aladwig06** [comment]
I found the issue.  I'm going to submit a pull request to fix it.
