### ISSUE TITLE
Like block / widget: If the site's default Gravatar is set to "Mystery person", the "other likers" popover won't load likers that don't have any Gravatar set

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#86471]
If the site's default Gravatar is set to "Mystery person" (in the Discussion settings):

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/f45778d2-ca4e-4648-867e-5346530e6683)

 the "other likers" popover won't load likers that don't have any Gravatar set:

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/5830f7df-b95a-42eb-8c7f-ff2dd2d06137)
![Image](https://github.com/Automattic/wp-calypso/assets/25105483/c7a91f37-7648-478e-9c74-f60bcca3ed07)

**Comment by JuanLucha** [comment]
Or worse, it loads for me with this ugly setup:
<img width="329" alt="Screenshot 2024-01-16 at 16 51 26" src="https://github.com/Automattic/wp-calypso/assets/3832570/b4a2dcad-5f0f-4857-b2d2-a27f0850eac0">

**Comment by ivan-ottinger** [comment]
> Or worse, it loads for me with this ugly setup:

Does it load the same even after the latest PR (https://github.com/Automattic/jetpack/pull/35072) merged?

I bet it should fix it - in a way that the users with the missing avatars won't load.

**Comment by JuanLucha** [comment]
@ivan-ottinger Indeed, that fixed it 👍

**Comment by ivan-ottinger** [comment]
Nice. So we will then only need to fix the core issue that is causing that the avatars are not loading.

I have started looking into this and it looks like there's an issue in the way the URL for the default "Mystery person" avatar is being used. We are "URLencoding" it twice (first time in `wpcom_get_avatar_url()` and then where the image is outputted) and hence the image doesn't load in the browser.

**Comment by ivan-ottinger** [comment]
Related D135617-code has landed to WPCOM. → Closing this issue and marking it as ✅ done.
