### ISSUE TITLE
Tools > Import: Starting an import from a trial plan or a Woo plan fails

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#86500]
Context: p6q7sZ-fhL-p2#comment-33855

**Comment by ouikhuan** [comment]
I think this is fixed by: https://github.com/Automattic/wp-calypso/pull/86519, I've just did another round of test to do a migration for Entrepreneur plan, and woo trial that upgrades to Essential and both works. So I'm closing this down.

cc @bogiii

**Comment by bogiii** [comment]
> I think this is fixed by: https://github.com/Automattic/wp-calypso/pull/86519,

🤝
