### ISSUE TITLE
Sidebar: Resolve Plan sync issues in sidebar after migration

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#86501]
Context: pdtkmj-1XX-p2#comment-3748

**Comment by bogiii** [comment]
@ouikhuan , do you know if this is still a relevant issue?
We switched to a different migration mechanism and removed the Migration Trial plan, so we can probably close it.

What do you think?

**Comment by ouikhuan** [comment]
I think plan sync was a longstanding issue overall, but I don't see it related to migration only anymore.
