### ISSUE TITLE
Subscriber Stats: acquisition, origin and more stats

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#86529]
Share ideas to improve Subscriber stats to provide more value to users.

Figma link: S4xGQTEkLhYdUvcIdn2Cfr-fi-1_32846

P2: peKye1-CC-p2

```[tasklist]
### Projects
- [ ] https://github.com/Automattic/red-team/issues/25
```

**Comment by simison** [comment]
PT: Jetpack Stats: Paid Subscribers Growth: pejTkB-1mw-p2

**Comment by simison** [comment]
I'll close this one and created a new issue for follow ups:
- https://github.com/Automattic/red-team/issues/153
- https://github.com/Automattic/red-team/issues/153
