### ISSUE TITLE
Like block: Multiple Like blocks on one page don't sync

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#86527]
When there are multiple Like blocks on one post / page and the user clicks on one of them, the action doesn't carry on to the other Like blocks on the page:

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/f07351b5-78b5-425b-b2b3-d4904a991002)

**Comment by yansern** [comment]
Patch here: D135151-code

**Comment by ivan-ottinger** [comment]
D135151-code is now in production. 🚀
→ Closing this issue and marking it as ✅ done.
