### ISSUE TITLE
Help Center: Feedback for articles

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#86531]
### Details

Source: pdDR7T-1dN-p2
Proposed by: @donalirl 

## Goal

Let’s add a feedback form to articles viewed in the Help Center (similar to what’s on the /support pages themselves) with the goal of measuring and improving the effectiveness of our content in supporting users.

<img width="737" alt="image" src="https://github.com/Automattic/wp-calypso/assets/52076348/d601603e-0777-420a-837a-20f5d3b8b5fc">

## Why

By capturing feedback at the end of docs in the Help Center, we can measure:

- Rate of users finding success via self-serve content in Help Center. i.e., Doc resolved instead of AI resolved or HE resolved. 
- Our most rated and highest rated docs (to prioritize the maintenance of these pages.)
-Our lowest-rated docs with qualitative user feedback (to improve the content.)
- How to improve the Help Center flow (are we presenting the right docs to start? what about pdm0RZ-L3-p2 based on the user’s current screen and recent actions?)

## How

The flow:

Did you find the answer to your question?
YES → Open-ended text box → SUBMIT → BACK TO HELP CENTER or CONTACT SUPPORT.
NO → Open-ended text box → SUBMIT → BACK TO HELP CENTER or CONTACT SUPPORT.

The /support pages themselves use this [Crowdsignal survey](https://href.li/?https://app.crowdsignal.com/surveys/2850849/report/overview). The Help Center could use the same one or different (whatever is easiest.) If using the same survey, let’s just add a tag so we can filter the feedback by source (i.e., if it came from the /support site or Help Center.)

**Comment by renancarvalho** [comment]
@donalirl you can check the feedback https://github.com/Automattic/wp-calypso/pull/89175 in this pull request.
You can find the survey result [here](https://app.crowdsignal.com/surveys/2980646/report/overview)

**Comment by escapemanuele** [comment]
@renancarvalho remember to delete your testings before going live :)

<img width="235" alt="image" src="https://github.com/Automattic/wp-calypso/assets/52076348/e52d6528-c5bb-4fd5-abda-0971a4255b3e">

**Comment by renancarvalho** [comment]
This is live 👍

**Comment by donalirl** [comment]
Hi folks 👋 Re-opening this based on the pbvpgB-53O-p2#comment-12650 discussion.

After submitting the survey, there's no path forward for the user:
![Screenshot 2024-07-02 at 8 11 09 PM](https://github.com/Automattic/wp-calypso/assets/30727666/42882c9f-c0b5-4839-b646-d1d3364981e8)

The flow should lead the user either back to the beginning of the Help Center or to Contact Support (still within the Help Center):

YES → Open-ended text box → SUBMIT → BACK TO HELP CENTER or CONTACT SUPPORT.
NO → Open-ended text box → SUBMIT → BACK TO HELP CENTER or CONTACT SUPPORT.

Will that be relatively quick and easy to implement? If so, let's do it. If not, let's remove the rating until we can do something more built-in to improve the UX.

**Comment by escapemanuele** [comment]
Ok @donalirl!

Let us know if we'll need to remove the feedback or maybe just put a button to send users to Support!

**Comment by donalirl** [comment]
Please see further feedback in pbvpgB-53O-p2#comment-12642 (video timestamp 8:30 - 10:20). 

Another issue raised in pbvpgB-53O-p2#comment-12717 is that the 👍️ 👎️ feedback form has the same design as the 👍️ 👎️ below a Wapuu interaction, so it's confusing that the same buttons lead to different outcomes depending on where the user is in the help center.

The best (and likely quickest) thing to do to clear up the confusion is for the 👍️ 👎️ below the doc to lead to a support contact instead of a feedback form. We'll miss out on that qualitative feedback here we might re-introduce it later on in a way that's better for the customer experience.

**Comment by escapemanuele** [comment]
Ok, got it!

But wouldn't it be best to only have the 👎 lead to the Support button?

**Comment by wongasy** [comment]
@escapemanuele A heads up that this is related to https://github.com/Automattic/dotcom-forge/issues/8124
