### ISSUE TITLE
Refreshed Fullpost: More on WP: Show blav if no grav

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8656]
On the Refreshed Fullpost, in the More on WP block, if the links do not have gravatars, but they do have blavatars, show the blavatar instead of the mystery man.

This post (https://wordpress.com/read/feeds/43971191/posts/1159412038#comments) for example, shows:

![screen shot 2016-10-11 at 10 36 02 am](https://cloud.githubusercontent.com/assets/24388/19281384/e4f773b2-8f9e-11e6-91fc-63d0d5d6a0c1.png)

The first post does have a blavatar: https://wordpress.com/read/blogs/84046989/posts/34510

If we show a blavatar instead of a gravatar, it should be square.

On a scale of "easy peasy" to "OMFG," how hard would this be to do?

**Comment by jancavan** [comment]
As discussed with @fraying, it should be gravatar > blavatar > feed icon, then if we can't find any of those, that's when we don't display anything.

**Comment by fraying** [comment]
Also: Rec Posts should work the same way. (Should that be a separate issue?)

**Comment by fraying** [comment]
This is still an issue. In the "More" blocks on Fullpost, if we don't have a gravatar, show the blavatar. If we don't have either, show nothing.
