### ISSUE TITLE
Subscription confirmation email: when viewed in text mode, the confirmation link doesn't work

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#86573]
The confirmation link in the confirmation email is broken if the email is viewed in text-only mode.
More context here: p1705569044738109-slack-C02TCEHP3HA

**Comment by TimBroddin** [comment]
I just inspected a confirmation email; we only seem to be sending the HTML part.

**Comment by JuanLucha** [comment]
> I just inspected a confirmation email; we only seem to be sending the HTML part.

Indeed, I think it's more like the client truncating the links or something like that. Look, using Thunderbird I can select the plain text version:
<img width="803" alt="Screenshot 2024-01-19 at 10 57 18" src="https://github.com/Automattic/wp-calypso/assets/3832570/4ad42664-953a-486f-821e-cc95e32d315c">

At least in Thunderbird the links are perfectly valid. I'm asking the customer to send a screenshot of their email, and a copy/pasted link.

Set as blocked meanwhile we get an answer.

**Comment by jidanni** [comment]
I am the customer.
Well I mean the person who was having the trouble.

Okay, let's see the bad link,
`https://public-api.wordpress.com/bar/?stat=groovemails-events&amp;bin=wpcom_email_click&amp;redirect_to=https%3A%2F%2Fsubscribe.wordpress.com%2F%3Fkey%3Dfa611f156394c807b0aebbcaec3e18b0%26email%3Djidanni%2540jidanni.org%26activate_comment%3D276703856%26n%3D5a332844a4efc1efcb025f515c4cc95d&amp;sr=1&amp;signature=4596dde656bfa1e4bceb38ddf375edc9&amp;user=a72c67bfefed83b72757697b9b9f11e8&amp;_e=eyJlcnJvciI6bnVsbCwiYmxvZ19pZCI6MTkyMjQyOTU0LCJibG9nX2xhbmciOiJlbiIsInNpdGVfaWRfbGFiZWwiOiJqZXRwYWNrIiwiX3VpIjoiYTcyYzY3YmZlZmVkODNiNzI3NTc2OTdiOWI5ZjExZTgiLCJfdXQiOiJhbm9uIiwiZW1haWxfZG9tYWluIjoiamlkYW5uaS5vcmciLCJwb3N0X2lkIjoxNjk5MiwidXNlcl9lbWFpbCI6ImppZGFubmlAamlkYW5uaS5vcmciLCJkYXRlX3NlbnQiOiIyMDI0LTAxLTE2IiwiZW1haWxfaWQiOiIwMDg2YmFlYzAzM2RmNGI2MDJjNWRkOWJhMzYzYTJlNiIsImVtYWlsX25hbWUiOiJzaXRlLXN1YnNjcmliZSIsInRlbXBsYXRlIjoic2l0ZS1zdWJzY3JpYmUiLCJsaW5rX2Rlc2MiOiJjb25maXJtLXN1YnNjcmlwdGlvbiIsImFuY2hvcl90ZXh0IjoiQ29uZmlybSBlbWFpbCIsIl9kciI6bnVsbCwiX2RsIjoiXC94bWxycGMucGhwP2hvbWU9aHR0cHMlM0ElMkYlMkZ3ZWVrbHlvc20uZXUmc2l0ZXVybD1odHRwcyUzQSUyRiUyRndlZWtseW9zbS5ldSZpZGM9MSZmb3I9amV0cGFjayZ3cGNvbV9ibG9nX2lkPTE5MjI0Mjk1NCIsIl9lbiI6IndwY29tX2VtYWlsX2NsaWNrIiwiX3RzIjoxNzA1MzkyNjkwODA4LCJicm93c2VyX3R5cGUiOiJwaHAtYWdlbnQiLCJfYXVhIjoid3Bjb20tdHJhY2tzLWNsaWVudC12MC4zIiwiX3VsIjpudWxsLCJibG9nX3R6IjoiMSIsInVzZXJfbGFuZyI6bnVsbH0&amp;_z=z`

Okay, now let's see the good link.
`https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https%3A%2F%2Fsubscribe.wordpress.com%2F%3Fkey%3Dfa611f156394c807b0aebbcaec3e18b0%26email%3Djidanni%2540jidanni.org%26activate_comment%3D276703856%26n%3D5a332844a4efc1efcb025f515c4cc95d&sr=1&signature=4596dde656bfa1e4bceb38ddf375edc9&user=a72c67bfefed83b72757697b9b9f11e8&_e=eyJlcnJvciI6bnVsbCwiYmxvZ19pZCI6MTkyMjQyOTU0LCJibG9nX2xhbmciOiJlbiIsInNpdGVfaWRfbGFiZWwiOiJqZXRwYWNrIiwiX3VpIjoiYTcyYzY3YmZlZmVkODNiNzI3NTc2OTdiOWI5ZjExZTgiLCJfdXQiOiJhbm9uIiwiZW1haWxfZG9tYWluIjoiamlkYW5uaS5vcmciLCJwb3N0X2lkIjoxNjk5MiwidXNlcl9lbWFpbCI6ImppZGFubmlAamlkYW5uaS5vcmciLCJkYXRlX3NlbnQiOiIyMDI0LTAxLTE2IiwiZW1haWxfaWQiOiIwMDg2YmFlYzAzM2RmNGI2MDJjNWRkOWJhMzYzYTJlNiIsImVtYWlsX25hbWUiOiJzaXRlLXN1YnNjcmliZSIsInRlbXBsYXRlIjoic2l0ZS1zdWJzY3JpYmUiLCJsaW5rX2Rlc2MiOiJjb25maXJtLXN1YnNjcmlwdGlvbiIsImFuY2hvcl90ZXh0IjoiQ29uZmlybSBlbWFpbCIsIl9kciI6bnVsbCwiX2RsIjoiXC94bWxycGMucGhwP2hvbWU9aHR0cHMlM0ElMkYlMkZ3ZWVrbHlvc20uZXUmc2l0ZXVybD1odHRwcyUzQSUyRiUyRndlZWtseW9zbS5ldSZpZGM9MSZmb3I9amV0cGFjayZ3cGNvbV9ibG9nX2lkPTE5MjI0Mjk1NCIsIl9lbiI6IndwY29tX2VtYWlsX2NsaWNrIiwiX3RzIjoxNzA1MzkyNjkwODA4LCJicm93c2VyX3R5cGUiOiJwaHAtYWdlbnQiLCJfYXVhIjoid3Bjb20tdHJhY2tzLWNsaWVudC12MC4zIiwiX3VsIjpudWxsLCJibG9nX3R6IjoiMSIsInVzZXJfbGFuZyI6bnVsbH0&_z=z`

**Comment by jidanni** [comment]
A quick look shows it's the good old-fashioned `&amp;` entity problem!

**Comment by jidanni** [comment]
So you got to resolve the entities in the plain text version. You can't just copy the same URL from the HTML version into the plain text version without resolving those entities first!

**Comment by jidanni** [comment]
What I did to make the above urls in the above comment, was I placed the cursor on each one and I used 'copy link address' there in chrome.

**Comment by jidanni** [comment]
It turns out the problem is https://github.com/roundcube/roundcubemail/issues/9312

In fact, due to miles long URLs, I don't recommend you folks make a real text/plain portion. OK, you can close the bug. Thanks.

**Comment by JuanLucha** [comment]
Thanks @jidanni ! I'll close the bug now 👍
