### ISSUE TITLE
Wrong border around CTA

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#86583]
In the upgrade step of the import hosted site flow, the main CTA has a border of a different color (`--studio-blue: #0675c4;`) than the button background (#7f54b3):

 
<img width="638" alt="Screenshot 2024-01-18 at 13 20 25" src="https://github.com/Automattic/wp-calypso/assets/4933/3fe04fb0-3fec-4580-a833-351a2f160872">

**Comment by JanaganSaravanan** [comment]
Hi! @javierarce  I would like to work on this issue. I have already set up wp-calypso locally. But I need help logging in in web. Any suggestion where i can find demo log in details. Thanks,

**Comment by javierarce** [comment]
Thanks, @JanaganSaravanan! I don't think there is a demo user, you'll need to create an account on WordPress.com

**Comment by JanaganSaravanan** [comment]
Hi!, @javierarce,  Thank you for the clarification.

**Comment by Aurorum** [comment]
I can no longer reproduce this - might be fixed?

<img width="737" alt="Screenshot 2024-02-24 at 22 07 14" src="https://github.com/Automattic/wp-calypso/assets/43215253/f85929df-3121-418b-8555-b29c2ab41ddd">

**Comment by javierarce** [comment]
Thanks for checking, @Aurorum! I wasn't able to reproduce the error either. I'll close this issue now, but feel free to reopen it if the error occurs again.

https://github.com/Automattic/wp-calypso/assets/4933/82059d4f-b3cf-4670-9aa8-825bf8e93489
