### ISSUE TITLE
Refreshed Fullpost: double avatar madness

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8659]
So. After a lot of debate, we decided to show both the gravatar and blavatar, overlapping, on the refreshed fullpost pgae. And it works! Mostly. Unfortunately, this happens.

![screen shot 2016-10-11 at 11 13 36 am](https://cloud.githubusercontent.com/assets/24388/19282645/0ca6ff22-8fa4-11e6-8887-6fbd9a972639.png)

Screenshot from: https://wordpress.com/read/feeds/33638212/posts/1184130471

So, questions:
1. How frequently do you see this doubling? I see it more than I'd like.
2. Is there anything we can do to detect when this happens so we could prevent it (or at least learn how frequent it really is)?
3. Short of simply displaying one or the other, can anyone come up with a clever solution to this problem?

**Comment by blowery** [comment]
> Is there anything we can do to detect when this happens so we could prevent it (or at least learn how frequent it really is)?

We're currently checking if the two images are the same URL. That's obviously not quiiiiiite enough. :)

**Comment by fraying** [comment]
Right. And I'm aware that this is a difficult problem, and one that's pretty much all my fault. Just groping around for solutions a bit.

**Comment by samouri** [comment]
@blowery: isn't that a useless check? My impression so far is that both blavatars and gravatars are hosted by the Gravatar service and they have unique urls no matter what. e.g.:
- Blavatar: `https://secure.gravatar.com/blavatar/5066fbb24b8dc8eb8af7aadfc55a9d40?s=120`
- Gravatar: `https://0.gravatar.com/avatar/92dcc5b39e7b8c7d962455860fd3e0c7?s=96&d=mm&r=G`

Could we potentially use a library like: [Resemble.js](https://github.com/Huddle/Resemble.js) to see if they are probably the same image?

**Comment by fraying** [comment]
@samouri I would LOVE it if you could look into Resemble.js to see if if could solve this problem.

**Comment by blowery** [comment]
I think the thing we ran into last time was trying to load the images into canvas x-origin.

**Comment by samouri** [comment]
@blowery yep! Just ran into the same issue.

The library seemed to work very pretty well (enabled sameSize + ignoreAntialias) but there were three main issues that mean its of no use:

1. cannot load images x-origin (`Access to Image at 'url' from origin 'https://i1.wp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'…`)
2. it was absurdly resource intensive to the point where the full-post page is unresponsive for a couple of seconds
3. the fact that it takes a couple of seconds means that both will exist for a bit and then we can detect it should/shouldn't be there. Not a great UX.

So I believe `resemble.js` is a dead end for solving the double avatar madness.

**Comment by fraying** [comment]
Ah, well. Good to know. Thanks for checking it out.

**Comment by blowery** [comment]
going to punt in this for now

**Comment by fraying** [comment]
Good call. 👍

**Comment by samouri** [comment]
https://github.com/mapbox/pixelmatch may be worth checking out
