### ISSUE TITLE
Yoast SEO section not displaying properly with the Gutenberg Plugin enabled

### ISSUE THREAD

**Issue by OmarFPG** [Automattic/wp-calypso#86601]
### Quick summary

When adding or editing posts, you should see the Yoast SEO section properly, right now it's only loading the title tabs:
![image](https://github.com/Automattic/wp-calypso/assets/122303439/8e2bbaa9-685a-4a0e-b27c-10fb290cec0b)

I tested this on a Creator and Pro site, same results. I tested on my self-hosted site and it's working fine, so not reporting to Yoast but here.

EDIT: further testing shows this is a bug with the Gutenberg plugin. Installing and activating it on my self-hosted also breaks it. However we have an easy fix for our users by telling them to disable this plugin temporarily.

### Steps to reproduce

1. Install Yoast SEO
2. Add or Edit any post
3. Check the Yoast SEO section

### What you expected to happen

The tabs should show the Yoast content to manage SEO settings and writing tips, social sharing, etc. ie:
![image](https://github.com/Automattic/wp-calypso/assets/122303439/40e1669e-2b28-474b-b891-2de28bdff6ce)

### What actually happened

The tabs only show the titles.

![image](https://github.com/Automattic/wp-calypso/assets/122303439/65062dcd-d36a-49fc-9144-86951ce8e6a5)

### Impact

Most (> 50%)

### Available workarounds?

After further testing, disabling Gutenberg seems to fix this.

**Comment by OmarFPG** [comment]
Reported here: 7605075-zen

**Comment by OmarFPG** [comment]
More reports here:
7605080-zen
7605066-zen
7605050-zen
7604911-zen

**Comment by Gustavo-Hilario** [comment]
Another report here: 7605275-zen

**Comment by connorhipps** [comment]
Another report here: 7605405-zen

**Comment by kerrynicl** [comment]
another report - 7605471-zen

**Comment by kelasante** [comment]
Another report in 7605498-zen

**Comment by fullofcaffeine** [comment]
I'm investigating the issue, see p1705603839071639/1705536263.290639-slack-CB0B2G43X.

**Comment by tellisbethel** [comment]
Another report here: 7605609-zd-a8c
Let user know it's being investigated and had them turn off Gutenberg for now.

**Comment by masperber** [comment]
Another report here: 7605998-zen

Worked around by deactivating Gutenberg

**Comment by edequalsawesome** [comment]
Also reported in 7606235-zen and 7606242-zen, let them know we'd follow-up once the issue was resolved

**Comment by cuemarie** [comment]
New reports: 

- 7606925-zen
- 7606929-zen

Both are waiting to see if it is resolved swiftly before deactivating Gutenberg.

**Comment by hacchism** [comment]
Another report: 7607048-zen

Worked around by deactivating Gutenberg.

**Comment by essleeung** [comment]
Another report here: 7607121-zd-a8c
Deactivated Gutenberg.

**Comment by Greatdane** [comment]
7607082-zd-a8c

**Comment by Greatdane** [comment]
7607355-zd-a8c

**Comment by Greatdane** [comment]
7607360-zd-a8c

**Comment by pauloeaquino** [comment]
7607584-zen

**Comment by marutim** [comment]
Another report here: 7607964-zen

**Comment by essleeung** [comment]
7607960-zd-a8c

**Comment by vajrasar** [comment]
Another one: 7607948-zen

**Comment by marutim** [comment]
Another one: 7608069-zen. Deactivated Gutenberg to fix the issue

**Comment by Greatdane** [comment]
7608266-zd-a8c

**Comment by nazilya06** [comment]
Another one: 7608190-zd-a8c.

**Comment by Neha93517** [comment]
Another one : 7608148- zen

**Comment by Greatdane** [comment]
7608362-zd-a8c

**Comment by Greatdane** [comment]
7608362-zd-a8c

**Comment by cecilearkay** [comment]
Two more reports in 7608517-zd and 7608278-zd

**Comment by nazilya06** [comment]
7608282-zd-a8c

**Comment by jerren1327** [comment]
7607081-zen
7605429-zen

**Comment by marutim** [comment]
Another one: 7608778-zen. Deactivated Gutenberg to fix the issue

**Comment by zdenys** [comment]
7608863-zd-a8c

**Comment by tacoverdo** [comment]
Can you please test this again against the latest version of [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/): 21.8.1?

**Comment by zdenys** [comment]
7609300-zd-a8c

**Comment by Robertght** [comment]
7609386-zd-a8c they asked that we follow up

**Comment by davipontesblog** [comment]
Another one 7609570-zd-a8c

**Comment by ccwalburn** [comment]
7609672-zd-a8c would like a follow up when this is resolved

**Comment by dev-sabbir** [comment]
7609648-zd-a8c

**Comment by Gustavo-Hilario** [comment]
Another report: 7610230-zen

**Comment by jorpdesigns** [comment]
7611352-zen

**Comment by jerren1327** [comment]
7607124-zen
7607681-zen

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple/Atomic - Could Not Replicate with Gutenberg on or off
- Tested on two of the users sites mentioned above - Could not replicate with Gutenberg on or off.
- Tested on my own .org site - Could not replicate with Gutenberg on or off.

## 📌 ACTIONS ##
Can't replicate anymore
Either issue in GB has been fixed with the latest update or Yoast has made some update.


## CLOSING  ##
If you see anymore problems please do re-open the thread and add any screenshots or screen capture.

**Comment by Robertght** [comment]
~I believe it was fixed in Yoast: https://wordpress.org/plugins/wordpress-seo/#developers~

Fixed in https://github.com/WordPress/gutenberg/releases/tag/v17.5.1

**Comment by masperber** [comment]
This issue seems to have returned, per a customer report in 8590497-zen. I was not able to reproduce this issue on my end, but the customer provided a screenshot of the issue, and confirmed that when Gutenberg was deactivated, the issue was resolved.

There have been at least 2 other issues caused by Gutenberg 18.9.0 that we have not been able to reproduce on our end ([93395](https://github.com/Automattic/wp-calypso/issues/93395) and [93392](https://github.com/Automattic/wp-calypso/issues/93392)), so I think this is enough cause to reopen this issue.

**Comment by masperber** [comment]
Hi @rafaelgallani !

I only received one report after 18.9.0 was released, and it looks like there haven't been any additional reports. Like several other 18.9.0 issues, it occurred for the customer but I could not reproduce it.

I think it would be OK to close this issue now that 19.0.0 is released, and it can be reopened if more reports come in.

**Comment by rafaelgallani** [comment]
I'm closing this one as we're unable to reproduce it following its instructions. It is currently not reproducible for either `v19.0.0` or `v19.1.0` with the latest Yoast SEO version for both Simple and Atomic sites.
