### ISSUE TITLE
Plans 2023: Storage add-on displays above stickied comparison grid header

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#86611]
### Quick summary

![Screenshot 2024-01-18 at 10 39 50 AM](https://github.com/Automattic/wp-calypso/assets/5414230/ccdc5643-c319-439b-8696-d54cb7769696)

### Steps to reproduce

1. Visit /plans
2. TBD

### What you expected to happen

Storage add-on dropdown should display below stickied header

**Comment by JanaganSaravanan** [comment]
Hi! I would love to work on this issue as my first contribution to wp-calypso. I have already set up wp-calypso locally. But I need help logging in in web. Any tips where i can find demo log in details. Thanks,

**Comment by rickmgithub** [comment]
## 📌 ACTIONS ##
- Author feedback

##Message to author##
Thanks so much for the report. I couldn't replicate the issue? Could you provide some more steps on your set up so we can replicate this and perhaps share a screencast?
