### ISSUE TITLE
Live Preview: Reduce file size

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#86626]
## Description

See p1705629726572469-slack-CRWCHQGUB. Currently, the file size for `wpcom-live-preview-notice.js` exceeds 3mb pre-processed. While lazy loaded, it would be good to look into how could we reduce the file size by removing some of the package imports.

- @fushar also proposes to move these files to `jetpack-mu-wpcom`.
- You can use Bundle Analyzer https://github.com/Automattic/wp-calypso/pull/86629 to identify the bottlenecks.

**Comment by jsnajdr** [comment]
This is strange, the plugin imports a few string constants from `calypso-products`, and yet it bundles the entire package, plus `@tanstack/query`. It's like there wasn't `sideEffects: false` in `calypso-products/package.json`, but it's there.

**Comment by jsnajdr** [comment]
It's caused by #85013 (by @okmttdhr) which includes the `ThemeUpgradeModal` component from Calypso, dragging a sizable piece of Calypso into the block editor: the React Query client, products library, UI components, ...

**Comment by taipeicoder** [comment]
Hey @jsnajdr thanks for looking this!
For more context, we currently [lazy load](https://github.com/Automattic/wp-calypso/blob/48826876f61fddc57a5e2d492805ab776cf9e49e/apps/wpcom-block-editor/src/wpcom/features/live-preview/index.tsx#L7) this file, which after processing should be [around 290kb](p1705645949944149/1705629726.572469-slack-CRWCHQGUB).

Lazy loading introduced another issue on its own, which was that the file did not contain any cache buster. We addressed it in this PR https://github.com/Automattic/wp-calypso/pull/86691.

If there are still any concerns about lazy loading this file, we can look into making the `ThemeUpgradeModal` leaner. cc: @Automattic/lego

**Comment by jsnajdr** [comment]
Thanks for the update! Downsizing `ThemeUpgradeModal` looks like an uneasy task. Now when we know where the bundle size is coming from, and when we manage it by lazy loading, there is probably nothing straightforward we can do to improve this.
