### ISSUE TITLE
Edit with Elementor button not displaying in Gutenberg pages with Elementor and Gutenberg activated

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#86663]
### Quick summary

When editing a Gutenberg page or post when Elementor is activated, there should be a button that appears near the top of the editor which allows the user to convert the page/post into an Elementor page/post.

<img width="539" alt="Screenshot 2024-01-19 at 12 45 05 PM" src="https://github.com/Automattic/wp-calypso/assets/12906034/99a3b7d6-654e-4c1c-8174-8a918d782dbc">

This may be related to #86601

### Steps to reproduce

1. Make sure the Gutenberg plugin is active.
2. Install the Elementor plugin.
3. Create a new page or post.

### What you expected to happen

1. Edit with Elementor should be present in the top left corner of the screen.

### What actually happened

1. Edit with Elementor is not present.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by masperber** [comment]
Customer report: 7611032-zen

**Comment by ash1eygrace** [comment]
Raised here yesterday: p1705536263290639-slack-CB0B2G43X 

For posterity two reports: 
- 7577961-zd-a8c
- 7605649-zd-a8c

**Comment by sajmes** [comment]
7611048-zd-a8c

**Comment by masperber** [comment]
7611476-zen

**Comment by masperber** [comment]
7611944-zen

**Comment by hanananah** [comment]
7615050-zen

**Comment by edequalsawesome** [comment]
7615375-zen

**Comment by edequalsawesome** [comment]
7615490-zen

**Comment by pauljacobson** [comment]
Another instance of this here: 7617317-zen

I suggested deactivating Gutenberg and clearing the site cache.

**Comment by mdtanjid0** [comment]
Another instance of this bug is here: 7619016-zen
Deactivated the Gutenberg plugin for them.

**Comment by rinazrina** [comment]
7619031-zd-a8c

**Comment by jorpdesigns** [comment]
7621007-zen

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Replicated as described

## 📌 ACTIONS ##
Triaged

**Comment by rickmgithub** [comment]
7625566-zd

**Comment by filipanoscampos** [comment]
7625986-zd-a8c

**Comment by filipanoscampos** [comment]
7627297-zd-a8c

**Comment by kerrynicl** [comment]
7627674-zen

**Comment by cuemarie** [comment]
7627871-zen

Workaround: Unsymlinked Gutenberg and rolled customer back to v17.4.1
(Tested Gutenberg 17.5.1, but that version does not contain a fix for the missing 'Edit with Elementor' button, so we rolled back instead).

@Automattic/dotcom-product-ambassadors is there work happening to address this one on our side, or this primarily waiting on Elementor for a fix? I can't quite tell from the report so far, but it'd be handy to know this when chatting with customers impacted by it.  Thanks!

**Comment by liviopv** [comment]
@cuemarie checking here p1706031537843939/1705536263.290639-slack-CB0B2G43X

**Comment by kathrynwp** [comment]
also reported in 7628951-zd-a8c

**Comment by kathrynwp** [comment]
As an alternative workaround, having user switch to the Classic view for pages/posts seems to allow them to click on the "Edit with Elementor" link below each post in WP Admin, and avoids having to deactivate Gutenberg.

<img width="639" alt="Pages_‹_Belmont_Studios_—_WordPress_—_Private_Browsing" src="https://github.com/Automattic/wp-calypso/assets/7662449/c2194a5c-5028-4c18-94d6-d7316b5d56ee">

**Comment by fullofcaffeine** [comment]
> @Automattic/dotcom-product-ambassadors is there work happening to address this one on our side, or this primarily waiting on Elementor for a fix? I can't quite tell from the report so far, but it'd be handy to know this when chatting with customers impacted by it. Thanks!

We're working on it here: p1706055234520509/1705536263.290639-slack-CB0B2G43X.

**Comment by hacchism** [comment]
Another report in 7631078-zen.

**Comment by zyousafi** [comment]
Another report in 7631201-zen

**Comment by liviopv** [comment]
Fixed with GB 17.5.2 p1706135713936989-slack-CB0B2G43X Closing

**Comment by mdtanjid0** [comment]
@liviopv, I came across another report today and managed to replicate the issue on the user's site with Gutenberg Version 17.6.3. It appears the user has some pages created with the Elementor plugin, and they were encountering the same issue. This time, however, the issue was a bit different, occurring on pages where Elementor had already been used.

The button appears normally when I deactivate Gutenberg, as shown here:
<img width="1247" alt="Screen Shot 2024-02-08 at 14 53 06" src="https://github.com/Automattic/wp-calypso/assets/54123436/6c6abc5c-e01b-40d1-906c-2be2649db936">

But it disappears upon reactivating Gutenberg.

Ref: 7709471-zen

**Comment by rinazrina** [comment]
Another one: 7827585-zd-a8c

**Comment by hacchism** [comment]
Another one: 7843387-zen

Reopening the issue as it seems to be recurring now.

**Comment by jp-imagines** [comment]
Another instance in 7901917-zd-a8c. Deactivated Gutenberg on this site to get the button back again, though the "edit with Elementor" option is always available in the WP Admin page list.

**Comment by liviopv** [comment]
This is present on WordPress RC3 as well. Re-escalated p1711044079253599-slack-C45SNKV4Z

**Comment by liviopv** [comment]
Fixed with Elementor 3.20.3:

> Fix: Edit with Elementor button is missing for pages that had been previously edited with Elementor when using WordPress 6.5 ([#25495](https://github.com/elementor/elementor/issues/25495), [#25496](https://github.com/elementor/elementor/issues/25496))
