### ISSUE TITLE
Rank Math Table of Contents items don't display in Editor when Gutenberg plugin is Active

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#86672]
### Quick summary

- The Rank Math Table of Contents block doesn't display the individual TOC items in the Editor when the Gutenberg plugin is Active
- The Table of Contents displays correctly on the front end regardless of whether the Gutenberg plugin is activated or not
- The Rank Math developers said this to the user: "It looks like the Table of Contents is working properly on the front end of your pages but not on the backend. However, after troubleshooting on your website, we can see the issue is occurring because of the Gutenberg plugin you’re using on your website. Please check the screencast in the sensitive data section for your reference."

### Steps to reproduce

I have not tried to reproduce this but the user reports that when Gutenberg is activated the Table of Contents block does not display the individual TOC items in the page editor. The TOC block can be seen in the List view of blocks, though. When Gutenberg is deactivated it displays the individual TOC items in the page editor.

### What you expected to happen

We expected the TOC items to display in the editor 

### What actually happened

The TOC items did not display in the editor

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

7609997-zd-a8c

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Replicated 

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
1. Install RankMath
2. Go through the Wizard to set it up
3. Go to a page and insert the Table of Contents by RankMath block (not our native one)
4. Add in a couple of headings
5. The TOC block doesn't show anything. 
6. Turn off Gutenberg and it shows them

https://github.com/Automattic/wp-calypso/assets/13706336/b13d35c9-7daf-42de-a5b6-98a03733562c

## 📌 ACTIONS ##
Triaged

**Comment by mmtr** [comment]
I cannot replicate this anymore with the latest version of Gutenberg active:

![Image](https://github.com/user-attachments/assets/f8f5152d-d770-4dfb-98f3-b23e5232e936)
