### ISSUE TITLE
Assembler: insert a default header and footer

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#86689]
# Description
Proposal to do something like Woo pdnLyh-5ee-p2#comment-3732.  When user lands on the Assembler, they will see a header and footer already inserted with the instructional text in the middle.

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/c9cbf655-792c-442e-ab05-291803853cf0)

# Design
- [ ] Do we want an image?
- [ ] Do we leave the same four bullet points?

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/ca7c58b9-469d-4516-9956-3e58d724c6b5)

**Comment by autumnfjeld** [comment]
cc: @richtabor  😄

**Comment by lucasmendes-design** [comment]
>  Do we want an image?
 Do we leave the same four bullet points?

The image is needed only if we change the bullet points. For now, I vote to have the bullet points as it is. Let's see how it goes. Unlike Squarespace, we don't have any indication about the next steps. WDYT?

**Comment by fushar** [comment]
We decided to keep the bullet points.

This is deployed. :)
