### ISSUE TITLE
Bug: Access panel text wrapping

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#86700]
The `Access` panel in Gutenberg looks like this:

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/03eb4788-c89a-43c1-a614-0efb14a40aaf)

And it should look like this:

![Image](https://github.com/Automattic/wp-calypso/assets/25607244/d3e7c8ff-a774-4c4d-b2e4-6f4e8e8b39a2)

It looks like there's a `max-width: 75%` that is breaking the layout.

**Comment by simison** [comment]
Hum, wasn't able to replicate in Firefox or Chrome:

<img width="299" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/62ba8709-8a13-4dab-b040-a5c118455b6a">

Also post-publish panel:

<img width="301" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/2bef1daf-35a5-4ad8-adfe-24eeb256c244">

There's a `text-wrap: balance`  applied to these labels just to avoid only `(0)` bit going to second line in some languages as translations can be longer.

I'll dig more 👍

**Comment by simison** [comment]
I found there's something specific on .com simple sites that causes the issue 👍

**Comment by crisbusquets** [comment]
This is being checked here:
https://github.com/Automattic/jetpack/pull/35690#discussion_r1495045824
