### ISSUE TITLE
User Invitation: Send email to users when invited 

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#86736]
### What

Users should get an email with an invite to join WordPress.com.

## How to test

To get a valid URL for testing, invite a user from your site `https://wordpress.com/people/new/{siteSlug}`
Username and password fields should be invisible since it is a passwordless account.

### Why

This is part of [this project](https://docs.google.com/document/d/1eoFwAOHyW7Ij-OGGPOSzTHAiuO5_OMMmf5I2oe6tWWg/edit#heading=h.nybf2j7pvkl0)

**Comment by escapemanuele** [comment]
What needs to be done here is to make accept-invite passwordless. Issue: https://github.com/Automattic/wp-calypso/issues/86757
