### ISSUE TITLE
User Invitation via flow: Add a step on site-setup flow to handle user invitation

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#86735]
Add a user import step on site-setup flow, for instance `https://wordpress.com/setup/site-setup/import?siteSlug=renancarvalhojs71.wordpress.com&siteId=228425413` (replace your site slug) to allow site owners to send an invitation to the users.

It should be opt-out: all users are checked by default.

We should then call the Invite endpoint: fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf.cuc%3Se%3Q7nr44p3q%23786-og

It accepts only one role, we will need to extend it.

Needed for the endpoint to work:
- Port it to v2: https://github.com/Automattic/wp-calypso/issues/86754
- Make it accept multiple roles: https://github.com/Automattic/wp-calypso/issues/86755

## Mockup:

**We need to focus this copy to show the value proposition: briefly pitch why having wp.com users is good in this step; access to 2fa, access to support, access to Apple and Google log-in, and better account recovery.** 

<img width="542" alt="image" src="https://github.com/Automattic/wp-calypso/assets/2653810/55bd0c17-efef-49d0-ad96-77fac8a19b12">

### Why

This is part of [this project](https://docs.google.com/document/d/1eoFwAOHyW7Ij-OGGPOSzTHAiuO5_OMMmf5I2oe6tWWg/edit#heading=h.nybf2j7pvkl0)

**Comment by crisbusquets** [comment]
FYI I'm checking this today, @renancarvalho

**Comment by crisbusquets** [comment]
Hi!

Here's the first iteration:
- Clear title
- Value proposition
- Checkboxes
- Short disclaimer at the end
- There's a `Skip for now` option at the top right. Users will have a way out, but it isn't too explicit.

Will all the users have an avatar? If so, I can iterate the design and add them. I didn't do it at first because I didn't want to add the _mystery man_ avatar —it doesn't look right.

## Flow
This new step should appear right _before_ the confirmation screen (https://github.com/Automattic/wp-calypso/issues/87008). This is when we'll trigger the emails for the selected users and the confirmation email for the site owner.

![invite-users](https://github.com/Automattic/wp-calypso/assets/25607244/3a95aba9-a646-4305-9bf4-655be2521b76)


Figma link: DASWajWXHUUjF4pu1yo4fI-fi-98_9589

**Comment by alshakero** [comment]
I imagine there will be a minority who will want to invite their users after they set up the site, not right when they sign up. I would add a note that they will be able to do this later.

**Comment by crisbusquets** [comment]
> I imagine there will be a minority who will want to invite their users after they set up the site, not right when they sign up. I would add a note that they will be able to do this later.

Good catch. I added the `Skip for now` for this reason but perhaps it isn't clear enough, we can:
* Make it more visible (place it next to the CTA, or below)
* Update the copy to `Do it later`
* Do both 😅

**Comment by escapemanuele** [comment]
Let's not forget to track how many users skip this step. If that number is high, we may need to better deliver our message

**Comment by escapemanuele** [comment]
I see that it is possible that a user has more than one badge

![image](https://github.com/Automattic/wp-calypso/assets/52076348/2bec9734-32a2-4cf3-a66f-aa3daec75868)

Might be worth to expand that table a little? 🤔  @crisbusquets

**Comment by crisbusquets** [comment]
Good catch @escapemanuele. I'll work on this 🚀

**Comment by crisbusquets** [comment]
Here's an updated version. Notice that I've modified the "disclaimer" text a little bit, so it works for both desktop and mobile.

![invite-users-v2](https://github.com/Automattic/wp-calypso/assets/25607244/f3c96338-500b-4e65-a90a-7b250787b47a)

The total width is 450px. Here are the specs: DASWajWXHUUjF4pu1yo4fI-fi-209_12252

And here's the mobile version. The centered text is not ideal, but that's the structure we currently have in all our onboardings, and I don't want to break consistency:

![m_invite-users](https://github.com/Automattic/wp-calypso/assets/25607244/cf666367-4cbd-44e6-aa06-340d6ce2f619)


Mobile specs: DASWajWXHUUjF4pu1yo4fI-fi-209_12892

**Comment by escapemanuele** [comment]
That's great @crisbusquets, thank you

**Comment by crisbusquets** [comment]
This small iteration is based on @escapemanuele's feedback on Slack.
The only thing that changes is the `Skip for now` button:

![d_invite-users-2](https://github.com/Automattic/wp-calypso/assets/25607244/f157703e-d3b3-4482-a4e9-e07ce8bc1444)

![m_invite-users-2](https://github.com/Automattic/wp-calypso/assets/25607244/f0418b14-7501-4c59-b070-719c267162c6)

Figma link: DASWajWXHUUjF4pu1yo4fI-fi-305_1556

**Comment by agrullon95** [comment]
@crisbusquets -

Do we have any thoughts about possible error messages in case the invite API fails (Like displaying a generic error message, allowing users to invite again or skip) or if an invite fails for one or more users ?
