### ISSUE TITLE
Reader Cards: Refresh Card display issues at intermediate widths

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#8674]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/refresh-card
2. Resize your browser's width up and down between desktop and tablet sizes
#### What I expected

All actions to remain encapsulated inside the card
#### What happened instead

The action icons bleed out to the right of the card at most intermediate widths, snapping into place at the boundaries between desktop/tablet.  Also at around 950px wide the image is displayed overtop of the text.

cc: @bluefuton @jancavan I know you're still working on these cards in a couple open PRs, but I wanted to make sure these issues were recorded so we don't forget about them.
#### Browser / OS version

Seen in OSX Chrome and Firefox
#### Screenshot / Video

1100px wide:
![screen shot 2016-10-12 at 9 53 41 am](https://cloud.githubusercontent.com/assets/7233112/19312744/ca36eaf8-9061-11e6-8661-6f3084eaea56.png)

950px wide (image overlaps text):
![screen shot 2016-10-12 at 9 54 20 am](https://cloud.githubusercontent.com/assets/7233112/19312773/e3e4b4ee-9061-11e6-9ea5-3dc4707d6476.png)
#### Context / Source
# automated-testing

**Comment by blowery** [comment]
Hrm...

I'm not sure our breakpoints that control sizing are ever going to make sense on devdocs.

Perhaps we need to move them up a conceptual layer, to the stream?

**Comment by hoverduck** [comment]
If it's just a matter of the devdocs environment not being a real-world use case for these components, I'm fine ignoring these kinds of problems in the context of the visual diff tests.  I've accepted them as-is for the baseline image, so it will flag out again if they change (for better or worse).

**Comment by jancavan** [comment]
> 1100px wide:

`<main>` on Devdocs has a padding set to `1.777em 8.184em` which is what's causing this. I'm unsure why it's there, but it causes the other elements (not just the Refresh card component) to display incorrectly:
![screenshot 2016-10-12 07 23 58](https://cloud.githubusercontent.com/assets/4924246/19313867/de41bb8c-904c-11e6-917c-8ba3df400fe0.png)

> 950px wide (image overlaps text):

This is probably from a previous change I did. Let me fix that.

**Comment by jancavan** [comment]
This is fixed in: http://calypso.localhost:3000/devdocs/blocks/refresh-cards
