### ISSUE TITLE
Edge cases: Handle accounts created directly into the DB

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#86742]
### What

Admins can create users directly to the DB, there's nothing we can do to prevent that.

What we can do is:

- Find a way to identify these users when loading this page `{silte-slug}/wp-admin/users.php`
- Display these users to the admins (see mockup below)
- Allow admins to “connect” these users by sending an email to them, here https://github.com/Automattic/wp-calypso/issues/86738

Mockup example
<img width="636" alt="image" src="https://github.com/Automattic/wp-calypso/assets/2653810/f4841241-a384-4019-8e1d-2c2345e6a06b">

### Why

This is part of [this project](https://docs.google.com/document/d/1eoFwAOHyW7Ij-OGGPOSzTHAiuO5_OMMmf5I2oe6tWWg/edit#heading=h.nybf2j7pvkl0)

**Comment by crisbusquets** [comment]
@escapemanuele does this still need design? Isn't this handled with the different background colors and the new "Status" column on the right?

**Comment by escapemanuele** [comment]
Yes, you're right 👍  I removed the design flag

**Comment by escapemanuele** [comment]
We deployed this change in Jetpack SSO ✌️
