### ISSUE TITLE
Accept-Invite: Improve the form

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#86758]
### What

With this https://github.com/Automattic/wp-calypso/issues/86757 we're making accept-invite passwordless.

It would also be nice to improve it.

<img width="1718" alt="image" src="https://github.com/Automattic/wp-calypso/assets/52076348/84fbd618-8f71-48f1-94ec-9da81f80d6b6">

**Comment by crisbusquets** [comment]
Hi @escapemanuele !

Can you update the description? The image isn't attached (it's stuck on `Uploading image.png...`).

**Comment by escapemanuele** [comment]
Ops!
Updated the image @crisbusquets!

(you can get there by inviting yourself and clicking on the invite while not logged in)

**Comment by renancarvalho** [comment]
Hello @crisbusquets and @escapemanuele, after a more profound investigation, I found out that this form has already a passwordless version, see below.

<img width="963" alt="image" src="https://github.com/Automattic/wp-calypso/assets/2653810/828ac421-687c-4e44-88f7-c434739143bb">

I noticed other flows are using it, soon I will update here with which flows are these.

**Comment by crisbusquets** [comment]
@escapemanuele here's a proposal that leverages what we already have for the passwordless flow.

The main difference is that I've updated the copy to match what we currently display. Additionally, I removed the top bar, which contained too many distracting links from the primary task (signing up).

Let me know if you would update/change anything :)

![passwordless](https://github.com/Automattic/wp-calypso/assets/25607244/3a625cc3-af4b-4bd3-9ad8-9f10f1f735bd)

Figma file: DASWajWXHUUjF4pu1yo4fI-fi-152_10190

**Comment by escapemanuele** [comment]
So much better @crisbusquets 👏

**Comment by escapemanuele** [comment]
Also current mobile status is broken

![image](https://github.com/Automattic/wp-calypso/assets/52076348/05c1740e-1fd6-4c8d-8a64-204149a25cf5)

**Comment by renancarvalho** [comment]
> @escapemanuele here's a proposal that leverages what we already have for the passwordless flow.
> 
> The main difference is that I've updated the copy to match what we currently display. Additionally, I removed the top bar, which contained too many distracting links from the primary task (signing up).
> 
> Let me know if you would update/change anything :)
> 
> ![passwordless](https://private-user-images.githubusercontent.com/25607244/301142486-3a625cc3-af4b-4bd3-9ad8-9f10f1f735bd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjY1MTMsIm5iZiI6MTcwNzIyNjIxMywicGF0aCI6Ii8yNTYwNzI0NC8zMDExNDI0ODYtM2E2MjVjYzMtYWY0Yi00YmQzLTlhZDgtOWYxMGYxZjczNWJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMzAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNDcwMjIxOTZmMmQxZDA3NTk1MGZjNTBjNjRhZjYwOThhNmY2NTE5MmFhM2FhMzZiM2JiMGNmNTBkNDViODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ByerKZ1YmGioG2c5cla-yG4KfnA-VAmlzlgX-Ql-5o0)
> 
> Figma file: [DASWajWXHUUjF4pu1yo4fI-fi-152_10190](https://href.li/?https://www.figma.com/file/DASWajWXHUUjF4pu1yo4fI/?node-id=152-10190)

Hi @crisbusquets I believe the button copy should be something like `create account` than `send link`, right? This is already the link and after clicking on the button the user will land on wordpress.com already logged in.

**Comment by crisbusquets** [comment]
> Hi @crisbusquets I believe the button copy should be something like `create account` than `send link`, right? This is already the link and after clicking on the button the user will land on wordpress.com already logged in.

Hi @renancarvalho, sorry for the delay in my reply. Yes, let's use `Create an account` instead of `Send link`.

**Comment by escapemanuele** [comment]
The form has been improved quite a lot 👍
