### ISSUE TITLE
Accept-invite: Make it passwordless

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#86757]
### Details

Whan a user receives an invite and click on it, he lands in accept-invite

![image](https://github.com/Automattic/wp-calypso/assets/52076348/8ad2c0d3-d6ee-4913-84e8-397fb6cf298c)

We should make this passwordless.

**Comment by crisbusquets** [comment]
Hi @renancarvalho !

Let me know if you need my input here. I'll be working on the form redesign (https://github.com/Automattic/wp-calypso/issues/86758), considering it will be passwordless.

**Comment by escapemanuele** [comment]
I think there is no need for design here, as this is mostly a technical change to be made :) In the other PR yeah, as you already did 👏
