### ISSUE TITLE
User invite step: Add message to be sent

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#86760]
### What

In Google Workspace, when I add a new user and I invite them via email, Google generates en amail that I can just send to the new user. They also give me a text input where I can add some of my own text that would then be included in that email.

When the invite for a WP.com registration goes out to an imported user, it might be nice for the site admin to add something like this to the email that goes out:

"Hi XYZ - We're migrating our site to WP.com. I have recreated your WP Admin account, but you'll need to authenticate it with WP.com (by following the instructions below) to have access."

**Comment by crisbusquets** [comment]
@escapemanuele if I understand this correctly, this means we'll add a textarea here:

![image](https://github.com/Automattic/wp-calypso/assets/25607244/517f1896-78e2-4ba0-bdbd-b3f1335d92de)

(also in Calypso?)

![image](https://github.com/Automattic/wp-calypso/assets/25607244/2a111ad5-210b-4ce4-8076-00f796650482)

And then display this content in this email (https://github.com/Automattic/wp-calypso/issues/86736), right?

![image](https://github.com/Automattic/wp-calypso/assets/25607244/19843e0f-ac3e-4f53-b755-5f1071544e9e)

**Comment by escapemanuele** [comment]
In Calypso we already have this possibility

![image](https://github.com/Automattic/wp-calypso/assets/52076348/20c97eb5-5a9f-485d-af3e-ea9db0e2ca5d)

And furthermore I'd pause stuff there for now, just to be sure we don't do work that is going away in 2 weeks 😄 

**BUT**, we can extrapolate how things are done in Calypso and try to incorporate them in `wp-admin`, in the page you shown yes.

**Comment by crisbusquets** [comment]
> BUT, we can extrapolate how things are done in Calypso and try to incorporate them in wp-admin, in the page you shown yes.

Here's the proposal for WP-Admin: It's better to have a visible `textarea` rather than force users an extra click. 
I also added the email template as an example of how we style these personal messages (it's the same we use for Calypso, I think).

<img width="1105" alt="Screenshot 2024-02-01 at 11 03 11" src="https://github.com/Automattic/wp-calypso/assets/25607244/3d7fdcaa-2ca2-422d-8078-35985fa15a19">


Figma: DASWajWXHUUjF4pu1yo4fI-fi-181_10483

**Comment by agrullon95** [comment]
Changes merged in: https://github.com/Automattic/jetpack/pull/35395
