### ISSUE TITLE
Gutenberg: Missing core paddings on group with background on Dotcom sites

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#86788]
Related https://github.com/WordPress/gutenberg/pull/37356

A bug in how the editor on Dotcom sites renders a group with background affects the assembler because we render the styles correctly as on core sites.

|Dotcom|Assembler|Core|
|--|--|--|
|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/0f0a1416-d2a7-4928-bca5-fb07df886064)|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/40b663cb-49f7-4843-bf96-907f0bf11933)|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/4c44db92-05a5-4d8f-be92-82d65bee5516)|

The padding applied by the selector `:where(.wp-block-group.has-background)` is missing, not overwritten, it's gone on the editor on Dotcom sites. See the [styles](https://github.com/WordPress/gutenberg/blob/b395e43ff6de78dcb058ff5ff5c6fd757077752f/packages/block-library/src/group/theme.scss#L2) and the [padding](https://github.com/WordPress/gutenberg/blob/b395e43ff6de78dcb058ff5ff5c6fd757077752f/packages/base-styles/_variables.scss#L107) in Gutenberg repo.

https://github.com/Automattic/wp-calypso/assets/1881481/f17c4e3d-a935-4bcc-be79-d1e824658530

@Automattic/lego, any ideas of where to debug or why the editor is missing these styles? Maybe @arthur791004.
What about removing/overwriting those styles on the Assembler as a workaround until we find the root cause?

@autumnfjeld, which was the team with experience working on editor styles on Dotcom that helped us in the past?

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
