### ISSUE TITLE
Posts & Pages: All Sites Mode No Longer Works

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#86818]
### Quick summary

Posts and Pages is broken in All Sites Mode.

### Steps to reproduce

1. Publish a post or page
2. Go to https://wordpress.com/posts or https://wordpress.com/pages

<img width="1825" alt="Screenshot 2024-01-24 at 21 40 56" src="https://github.com/Automattic/wp-calypso/assets/43215253/13b6bbae-1352-40bd-8c14-0a3450445fcf">

### What you expected to happen

I used to be able to see all my posts/pages across multiple sites here. That was pretty handy.

If we absolutely cannot do that anymore, we should force users to select a site with SiteSelector and remove references to All Sites mode.

### What actually happened

I'm shown an EmptyComponent instead. A request is made to the endpoint, but it doesn't return any posts, so it looks like it's the API which is broken. 

Relevant endpoint: `https://public-api.wordpress.com/rest/v1.1/me/posts?http_envelope=1&author=&number=20&order=DESC&search=&site_visibility=visible&status=publish%2Cprivate&type=post&page=1`

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

Noticed when testing #86633

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
Could Not Replicate

## 📌 ACTIONS ##
- Author feedback

##Message to author##
Thanks so much for the report @Aurorum  I couldn't replicate the issue based on the information. Can you tell us how we can replicate it on a few accounts or a particular set up?
