### ISSUE TITLE
Jetpack: Investigate why we display Post/Page filters when there are no items available

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8684]
(Published/draft/scheduled) all show for a Jetpack site, even when it has none of each type of post. On WP.com sites, we only show those filters if there are sites to show under that view. We should do the same for Jetpack sites. This is related to lack of functional post_counts endpoint for Jetpack sites.

On a WP.com site we only see filters when there > 0 items:
<img width="758" alt="screen shot 2016-10-12 at 10 57 56 am" src="https://cloud.githubusercontent.com/assets/1270189/19321757/1ce59656-906b-11e6-8f0f-1acb949be1a0.png">

For a Jetpack site this is untrue:
<img width="1062" alt="screen shot 2016-10-12 at 10 58 06 am" src="https://cloud.githubusercontent.com/assets/1270189/19321789/3f688328-906b-11e6-95a3-e6b98e7fc29e.png">

Let's do an investigation spike to see why this is happening. If the steps involved to fix this are very large, please report back and we can create more issues.

**Comment by beaulebens** [comment]
This may (hopefully) be fixable now that we are more thorough with the data that we sync (we didn't previously sync drafts etc, which meant this was impossible).

**Comment by mtias** [comment]
@beaulebens the `post_counts` endpoint is a separate one, we need to make sure that is properly synced and updated.

**Comment by beaulebens** [comment]
Right, what I mean is that even if we don't have the endpoint in Jetpack (yet), we might be able to handle it locally, from synced data.
