### ISSUE TITLE
Zoom control should not be relative to device preview 

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#86856]
I find it disorienting that the zoom control's effect was relative to the active device preview. The zoom control should perform exactly like the other device preview controls do—set the zoom/height/width/scale of the site. 

It should not be a "combo" control that zooms each of the other previews, but it's own state of view.  Otherwise it's quite confusing not understanding what view you're in, and how to get "back". 

We wouldn't need to minus state of the button either. Just apply the same treatment as the other icons get when active. If I click on any other icon, the zoomed state should be omitted and the device preview state is active. 

https://github.com/Automattic/wp-calypso/assets/1813435/8083036d-46c1-465c-8672-f22661ced158

**Comment by arthur791004** [comment]
See p1706194641864719-slack-CRWCHQGUB

**Comment by richtabor** [comment]
Related in part to https://github.com/WordPress/gutenberg/pull/58202, which is directionally how the editor will support zooming. You will not be able to stack zooming and device preview; they're agnostic. Each serves a distinct purpose: zooming alters the view scale, while device preview simulates how content would appear on different devices.

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
