### ISSUE TITLE
Like block: icon misalignment on small containers

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#86869]
When the like block is placed on a small container (for example, using a 3-column layout), the icon is displayed misaligned with the button borders.

![Image](https://github.com/Automattic/wp-calypso/assets/3113712/423b4b86-0767-44bb-bd00-f788f2375921)

**Comment by ivan-ottinger** [comment]
Another report: p8oabR-1qU-p2#comment-7836.

**Comment by yansern** [comment]
D137396-code

List of fixes:
- Fixed icon not centered when in narrow viewport (where button label is not shown).
- Fixed additional gap after liking and unliking when there's only 1 like.
- Fixed RTL paddings/margins not flipped correctly.
- Minor balancing/kerning adjustments between button and textual elements.

<img width="833" alt="2024-02-07_23-07-26" src="https://github.com/Automattic/wp-calypso/assets/1287077/741d72a4-cea0-40ba-b950-8803e3c03872">

<img width="2464" alt="2024-02-07_23-10-35" src="https://github.com/Automattic/wp-calypso/assets/1287077/3668c358-f8a7-4620-abad-a27dd76b992e">

<img width="1708" alt="2024-02-07_23-33-43" src="https://github.com/Automattic/wp-calypso/assets/1287077/d786d46a-4aff-43af-af93-e5090e3e8a5e">

<img width="1812" alt="2024-02-07_23-37-26" src="https://github.com/Automattic/wp-calypso/assets/1287077/09018529-3cf2-40ba-a711-9306c508b36b">

<img width="842" alt="2024-02-07_23-39-22" src="https://github.com/Automattic/wp-calypso/assets/1287077/74593729-b4f3-4cc6-9cd6-297c918773de">

**Comment by yansern** [comment]
This is done awhile back. Closing issue.
