### ISSUE TITLE
Like blog: 4 avatars are displayed after unliking a post with 56+ likes

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#86871]
Possibly related to https://github.com/Automattic/wp-calypso/issues/86870

**Steps to reproduce**
- Open a post you liked recently (with your avatar still displayed as one of the 5 recent likers)
- This post should have 6 or more likes
- Unlike the post
- You will see 4 avatars

<img width="770" alt="Screenshot 2024-01-25 at 17 32 33" src="https://github.com/Automattic/wp-calypso/assets/3113712/f2afde88-31f5-4e31-8905-8ff18d7eb1ed">

**Expected**
- Display 5 avatars, excluding your avatar and including a new one at the end of the list (the 5th most recent liker)

<img width="734" alt="Screenshot 2024-01-25 at 17 35 56" src="https://github.com/Automattic/wp-calypso/assets/3113712/74e486df-2728-449d-b01d-035c99e38dfe">

**Comment by ivan-ottinger** [comment]
Fixed with D137778-code. → Marking this issue as closed.
