### ISSUE TITLE
Like blog: 6 avatars are displayed after liking a post with 5+ likes

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#86870]
Possibly related to https://github.com/Automattic/wp-calypso/issues/86871

**Steps to reproduce**
- Open a post you didn't like yet
- This post should have 5 or more likes
- Like the post
- You will see 6 avatars

![Image](https://github.com/Automattic/wp-calypso/assets/3113712/99afe5c7-ee11-421b-a854-e3fee7bc3c50)

**Expected**
- Display 5 avatars, including your avatar as the first one in the list

![Image](https://github.com/Automattic/wp-calypso/assets/3113712/875cc958-17c6-4f7c-bfb8-f7799d7cba7a)

**Comment by JuanLucha** [comment]
Fixed in D137248-code
