### ISSUE TITLE
Incorrect Redirection to WP Login for existing Users with Google and Apple Signups

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wp-calypso#86884]
### Quick summary

When a user tries to sign up using Google or Apple, and their email matches an existing account that hasn't been connected yet, the user will be redirected to the WP login screen

### Steps to reproduce

1. Create a WP account with a Google email or make sure Google login is not connected. https://wordpress.com/me/security/social-login
2. Log out
3. Go to https://woo.com/start/
4. Continue to the account creation step
5. Sign up via Google
6. Observe that you're directed to the WP login screen without any error message.

### What you expected to happen

Should redirect user to Woo's login screen and display an error message 

4ixWMlzrxllx93tSFsCW6k-fi-5037_90936

### What actually happened

 user is redirected to the WP login screen without any message.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by ilyasfoo** [comment]
> the user should be redirected to the WooCommerce login screen with an User Exists error message

Is this an existing message? Does this behave the same with non-Woo Express users?

If this is a new message, I imagine we could be more descriptive that the email associated with the social account has already been used to register, and they need to login with the existing account and connect the account first before signing-in with the social account.

Perhaps cc @verofasulo if you have any opinion on the UX

**Comment by chihsuan** [comment]
> Is this an existing message? Does this behave the same with non-Woo Express users?

Nope, it's not. For WPCOM users, they're seeing a screen like below and they're not redirected to log in screen.

<img width="804" alt="Screenshot 2024-01-26 at 16 56 01" src="https://github.com/Automattic/wp-calypso/assets/4344253/5e1cdf7c-69b2-4e9a-b6b2-d409a00582df">



```

**Comment by ilyasfoo** [comment]
@chihsuan  Gotcha, thanks! I think we can reuse the same messaging for Woo Express as a default.

From the screenshot, I think the error message look a bit awkward for the social first screen (copy too long, container too small). cc @escapemanuele for awareness since I think you've worked on it prior.

**Comment by escapemanuele** [comment]
It may be a little too long indeed! @crisbusquets I know you're full, when you can we could shorten this a little :)

**Comment by crisbusquets** [comment]
> It may be a little too long indeed! @crisbusquets I know you're full, when you can we could shorten this a little :)

Thanks for the ping, @escapemanuele !

What I can think of now is:
`We found a WordPress.com account with the email 'test123@gmail.com'. [Log in to connect it], or use a different email to sign up.`

(173 vs 126 characters)

I'm unsure if we should specify `...connect it to your profile`.

**Comment by escapemanuele** [comment]
Thank you @crisbusquets!

I opened https://github.com/Automattic/wp-calypso/pull/86945 and I'll merge it when translations are done ✌️
