### ISSUE TITLE
Reader: The Add link next to Add a tag textbox is barely visible with most dashboard color schemes

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#86895]
### Quick summary

The Add link next to Add a tag textbox under Tags section is barely visible with most dashboard color schemes.

https://github.com/Automattic/wp-calypso/assets/39308239/176ce771-d583-42d2-abeb-e78aab74341f

### Steps to reproduce

1. Pick any dashboard color scheme at https://wordpress.com/me/account
2. Check https://wordpress.com/read to see how visible the Add link is next to Add a tag textbox under Tags section

### What you expected to happen

The Add link to be easily visible with any dashboard color scheme

### What actually happened

The Add link next to Add a tag textbox under Tags section is barely visible with most dashboard color schemes.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by zdenys** [comment]
Related: the "See all tags" link is invisible with Dashboard color scheme set to "Light":

https://github.com/Automattic/wp-calypso/assets/39308239/4c264949-b69b-4d3e-8b02-928e2d086776

**Comment by Aurorum** [comment]
PR for this in #87157. :)
