### ISSUE TITLE
Reader: Audio embeds full-width and stacked

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8690]
Currently, we display audio embeds side by side. There also isn't a gap between them that they look connected.

![screenshot-2016-10-12-13 08 12](https://cloud.githubusercontent.com/assets/4924246/19326523/b70d019c-907f-11e6-9065-56be3d78ad07.jpg)

Example:
http://calypso.dev:3000/read/feeds/23059853/posts/1172596157

The player should take up full-width and stacked if there are multiple.

/cc @fraying  h/t @aerych

**Comment by fraying** [comment]
Nice. 👍
