### ISSUE TITLE
Move to WPCOM landing page: update copy

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#86939]
For more info, see:
- RM0R6AwIQRiSVCLdK12pyr-fi-800_14498
- https://docs.google.com/document/d/1uKkcq-9NiVhwO3DL7Fmv0fJJsG8duB2_7xUqmZbyc60/edit

**Comment by vishnugopal** [comment]
I think I've updated everything in `/move` except adding a sub-heading to the feature grids, which I think may require a code change. I'll pick this up in the morning tomorrow.

cc @bogiii can you take a look when you get time? My CSS is a bit rusty, and I'm not sure I got everything right.

**Comment by bogiii** [comment]
Yeah, you are right. It's kinda strange that we can not simply add a paragraph block below the heading.
It looks like the "Landpack Feature Grid" block has predefined fields.

Other changes look good to me, except for the Build By block, which occupies space from edge to edge.

| Now | Figma proposal |
|--------|--------|
| <img width="1098" alt="Screenshot 2024-02-01 at 16 18 47" src="https://github.com/Automattic/wp-calypso/assets/1241413/9a95f1a2-6a03-4b4a-953b-27f9f1f104a6"> | <img width="980" alt="Screenshot 2024-02-01 at 16 19 13" src="https://github.com/Automattic/wp-calypso/assets/1241413/d85936a4-60ef-4334-9c7c-cc8c852e05e9"> |

**Comment by vishnugopal** [comment]
@bogiii I have fixed the margin alignment issue. 

I'll also try to work on adding a sub heading to the Landpack feature grid over the weekend. I set up Landpack but it took me a while to come to grips with how it works.

**Comment by bogiii** [comment]
I'm closing this ticket since the changes are mostly done except for the sub-heading on the feature grid.

I've created a separate ticket for that part for easier tracking: https://github.com/Automattic/wp-calypso/issues/87232
