### ISSUE TITLE
Unable to review Installed Themes to activate an already existing theme

### ISSUE THREAD

**Issue by AmeliaBriscoe** [Automattic/wp-calypso#86935]
### Describe the bug

After uploading a non-WP.com premium theme, if you want to activate it at a later time, there is no visible way to get back to the 'Installed Themes' area. You need to manually navigate to `themes.php` in the URL.

Screencast of the issue below. I'm installing the Altitude Pro theme from the StudioPress team (WP Engine)

https://github.com/Automattic/wc-calypso-bridge/assets/2174223/283ac60f-1195-4b4c-96b4-3d653a4ec76f

### Expected behavior

There should be a link to view the already installed themes so they can be activated

### Steps to reproduce

1. Go to **Appearance > Themes > Install Themes** and upload a non-WP.com theme
2. Navigate away from the themes area and then go back to **Appearance > Themes**
3.  Searching for the theme does not help
4. Clicking 'Install Theme' and searching does not help
5. Using the Class settings in the **Settings > Hosting Configuration"" does not help
6. Need to navigate by adding `themes.php' to the main admin URL. eg - `https://domain.com/wp-admin/themes.php`

### WordPress Environment
<details><summary>Details</summary>
### WordPress Environment ###

WordPress address (URL): https://impossiblyglittery.com
Site address (URL): https://impossiblyglittery.com
WC Version: 8.5.0.41
REST API Version: ✔ 8.5.0.41
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.0.41
WC Database Prefix: wp_
Total Database Size: 38.93MB
Database Data Size: 23.46MB
Database Index Size: 15.47MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 6.02MB + Index: 5.45MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.03MB + Index: 5.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.03MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.03MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.06MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 1.42MB + Index: 0.47MB + Engine InnoDB
wp_posts: Data: 1.38MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpf_logging: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 70
customize_changeset: 7
feedback: 5
jetpack_migration: 2
jp_img_sitemap: 8
jp_sitemap: 8
jp_sitemap_master: 8
mailpoet_page: 1
page: 22
post: 4
prl_engine: 2
product: 31
product_variation: 9
revision: 106
shop_coupon: 2
shop_order: 1
wc_membership_plan: 1
wpcode: 10
wp_global_styles: 5
wp_navigation: 2
wp_template: 9
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Block Visibility: by Nick Diego – 3.2.0
WordPress.com Editing Toolkit: by Automattic – 4.10070
Gutenberg: by Gutenberg Team – 17.4.1
WPCode Lite: by WPCode – 2.1.7
Jetpack: by Automattic – 13.0
Layout Grid: by Automattic – 1.8.4
Loco Translate: by Tim Whitlock – 2.6.6
MailPoet: by MailPoet – 4.41.2
Page Optimize: by Automattic – 0.5.4
RightMessage: by RightMessage – 0.9.4
Woo AI: by WooCommerce – 0.5.0
WooCommerce Back In Stock Notifications: by WooCommerce – 1.6.6
WooCommerce Bookings: by WooCommerce – 2.0.8
WooCommerce Composite Products: by WooCommerce – 8.10.4
Woo Gift Cards: by Woo – 1.16.8
WooCommerce Measurement Price Calculator: by SkyVerge – 3.22.1
WooCommerce Memberships: by SkyVerge – 1.25.2
WooCommerce Min/Max Quantities: by WooCommerce – 4.1.3
WooPayments: by Automattic – 7.0.0
WooCommerce PayPal Payments: by WooCommerce – 2.4.3
Woo Product Add-ons: by Woo – 6.5.2
WooCommerce Product Bundles: by WooCommerce – 6.22.5
WooCommerce Product Recommendations: by WooCommerce – 3.0.4
WooCommerce Product Vendors: by WooCommerce – 2.2.5
Request a Quote for WooCommerce: by Addify – 2.5.1
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WooCommerce Shipment Tracking: by WooCommerce – 2.4.3
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.7
Woo Subscriptions: by WooCommerce – 5.9.0
WooCommerce: by Automattic – 8.5.0.41
WP Fusion Lite: by Very Good Plugins – 3.41.24

### Inactive Plugins (22) ###

AutomateWoo: by WooCommerce – 6.0.13
Avalara AvaTax: by Avalara – 2.7.0
Classic Editor: by WordPress Contributors – 1.6.3
ConvertKit for WooCommerce: by ConvertKit – 1.7.1
Crowdsignal Forms: by Automattic – 1.7.0
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.1

Extra Fees for WooCommerce: by Flintop – 5.4.0
Facebook for WooCommerce: by Facebook – 3.1.9
Google Listings and Ads: by WooCommerce – 2.5.15
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.2.1
TikTok: by TikTok – 1.2.3
WooCommerce Blocks: by Automattic – 11.7.0
WooCommerce Brands: by WooCommerce – 1.6.63
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.4
WooCommerce Checkout Add-Ons: by SkyVerge – 2.7.1
WooCommerce EU VAT Number: by WooCommerce – 2.8.9
WooCommerce FedEx Shipping: by WooCommerce – 3.8.7
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.13
WooCommerce Payment Gateway Based Fees: by InoPlugs – 4.1
WooCommerce Royal Mail: by WooCommerce – 3.1.0
WooCommerce UPS Shipping: by WooCommerce – 3.5.7
WooCommerce USPS Shipping: by WooCommerce – 4.7.6

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: Automattic/wc-calypso-bridge#492 - /shop-placecard/
Cart: Automattic/wc-calypso-bridge#46 - /cart/
Checkout: Automattic/wc-calypso-bridge#47 - /checkout/
My account: Automattic/wc-calypso-bridge#48 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Frost
Version: 1.0.7
Author URL: https://wpengine.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /wordpress/plugins/woocommerce-accelerated-frequency/8.5.0.41/templates/notices/error.php
/wordpress/plugins/woocommerce-accelerated-frequency/8.5.0.41/templates/notices/notice.php
/wordpress/plugins/woocommerce-accelerated-frequency/8.5.0.41/templates/notices/success.php

### WooPayments ###

Version: 7.0.0
Connected to WPCOM: Yes
WPCOM Blog ID: 220652986
Account ID: acct_1NNkMxFmCHc9kdH5
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,checkout,cart)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 1
Free Membership:: Members: 0Access method: Product(s) purchaseAccess length: Unlimited Subscription: No No access-granting products are purchasable❌ The plan has purchasing discounts
but none are active

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://impossiblyglittery.com
Subscriptions-core Library Version: 6.7.0
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Australia — Victoria

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Cash on delivery: products
PayPal: refunds
products
tokenization
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Back In Stock ###

Database Version: 1.6.6
Loopback Test: ✔

### Composite Products ###

Database Version: 8.10.4
Loopback Test: ✔
Template Overrides: –

### Gift Cards ###

Database Version: 1.16.8
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 6.22.5
Loopback Test: ✔
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AU
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: ✔
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: PayPal Vaulting

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
navigation
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-16 22:20:48 +11:00
Options: ✔
Notes: 83
Onboarding: skipped

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Current sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://impossiblyglittery.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Canceled: 1
Oldest: 2023-12-29 10:34:49 +1100
Newest: 2023-12-29 10:34:49 +1100

Complete: 3,045
Oldest: 2023-12-16 13:22:32 +1100
Newest: 2024-01-16 13:22:30 +1100

Failed: 494
Oldest: 2023-06-29 06:07:32 +1000
Newest: 2024-01-03 07:33:52 +1100

Pending: 4
Oldest: 2024-01-16 13:24:30 +1100
Newest: 2024-07-17 12:30:12 +1000

### Product Recommendations ###

Database Version: 3.0.4
Loopback Test: ✔
Task Queueing Test: ✔
Page Cache Test: No cache detected

### Status report information ###

Generated at: 2024-01-16 13:24:44 +11:00
</details> 

### What plan is active?

Performance

**Comment by PanosSynetos** [comment]
@AmeliaBriscoe thanks for raising this. It seems like there was a hiccup. 

Two things I noticed

On your screencast, I don't see the filter bar. I visited your site and I can now see it.

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/e86d01b2-6446-4b37-8257-b6d31e2a1f7a)

I uploaded another theme (Listable) which you can see it when going to `wp-admin/themes.php`

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/58e4e6f4-828b-401a-bdd4-d6e35ab6d7e5)


 but indeed I cannot see it under `My Themes` https://wordpress.com/themes/my-themes/impossiblyglittery.com - I can only see the active one

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/7a698131-3b3d-47bc-8fe0-c46d27e16747)


@ilyasfoo @verofasulo Ghidorah has implemented functionality, to Default to `Store` categories filter

- See Slack p1688448940021139/1687889632.741609-slack-C03Q87XT1QF
- See PR https://github.com/Automattic/wp-calypso/pull/78911/files#diff-8b997c677097d74cfcc610dfa15bc194293656a8bf8f59eeca6ac85241614f10R14

Could this be related?

**Comment by ilyasfoo** [comment]
I think we may need to remove the hidden `Store` filter for `My Themes` query, as mentioned by @PanosSynetos 

cc @chihsuan since you've worked on https://github.com/Automattic/wp-calypso/pull/86516 prior, if you could also help 🙏

**Comment by chihsuan** [comment]
> I think we may need to remove the hidden `Store` filter for `My Themes` query, as mentioned by @PanosSynetos
> 
> cc @chihsuan since you've worked on #86516 prior, if you could also help 🙏

I've opened a PR to show the installed themes in `My Themes` tab.

> Searching for the theme does not help

However, I'm still not able to see my installed (non-WP.com / non-WP.org) theme through the search. I confirmed that this issue exists even on a site with the Creator plan. @Automattic/t-rex team Do you know if this is expected?

https://github.com/Automattic/wp-calypso/assets/4344253/940bc3ee-7faf-4a95-9ec0-142fabbe80ee

**Comment by dsas** [comment]
It's surely unexpected from a user pov. It is expected from our "knowing how the code works" pov. 

The search uses our wpcom API (/rest/v1.2/themes) backed by elastic search, which isn't a site-specific endpoint. It also uses the wporg API (https://api.wordpress.org/themes/info/1.1/?action=query_themes&request%5Bfields%5D%5Bextended_author%5D=true&request%5Bfields%5D%5Btags%5D=true&request%5Bsearch%5D=YOURSEARCHTERM&request%5Bpage%5D=1&request%5Bper_page%5D%3A=100&request%5Bbrowse%5D=popular) and the results are then combined within Calypso. It won't include themes that aren't offered as part of wpcom or wporg.

**Comment by ilyasfoo** [comment]
Thanks for the details, @dsas!

There was indeed a bug in Woo Express that prevented some themes from being displayed, but it's not related to this particular issue.

@chihsuan Has made a fix in https://github.com/Automattic/wp-calypso/pull/86944 to display installed themes for Woo Express & free trial, however it's still limited to themes available on either WP.com or WP.org. Custom themes will not be listed in this screen, users will have to rely on the wp-admin's themes screen instead.

In regards to the original issue, I don't think it can be fixed from our end since it's a problem that exceeds Woo Express' context. @dsas do you think this issue can be addressed by Trex?

**Comment by dsas** [comment]
> it's a problem that exceeds Woo Express' context

If you've got access to a sandbox then I'd encourage you to not be limited by a context, but to address things that get in your way, consulting and asking for reviews for people more familiar with the codebase.

Since the reorg I'm not sure when/if T-Rex will get to this. I'll defer to @Copons on that.

**Comment by Copons** [comment]
We are not actively working on the Theme Showcase right now and for the foreseeable future.

We can definitely help with maintenance, although this specific case seems more related to Woo Express than WordPress.com. 🤔 

The "My Themes" tab should be visible on all site types — it has always been visible on Atomic, and we have recently (https://github.com/Automattic/wp-calypso/pull/86660) extended it to Simple.
Is there a reason for not showing the categories ribbon (which includes the My Themes tab) on Woo Express?

As an aside, could anyone point me to how to test the Woo Express flow? 😄 
If the process includes sensitive info, please send me a DM or use the T-Rex channel on Slack.

**Comment by ilyasfoo** [comment]
> We can definitely help with maintenance, although this specific case seems more related to Woo Express than WordPress.com. 🤔

Thanks, @Copons! Based on my testing, this also reproducible with the Entrepreneur plan (I think it may affect all plans with Nav Unification)

> Is there a reason for not showing the categories ribbon (which includes the My Themes tab) on Woo Express?

"My Themes" tab is actually shown in Woo Express:

<img width="700" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/bd1408d1-2d12-48d7-a874-4a9ff9c20b5e">


> As an aside, could anyone point me to how to test the Woo Express flow? 😄

Sure thing!

1. Go to https://woo.com/start
2. Go through NUX by filling up required fields
3. In the final step, click on `Try Woo Express for free`
4. After the loading screen, you should have free trial site set up
5. Go to `Upgrades > Plans`
6. Purchase either Essentials or Performance plan to gain permission to upload custom themes
7. Install a custom theme that's not in wp.com nor wp.org **but don't activate it**
8. Go to `Appearance > Themes` and observe the theme will not be on the list

**Comment by ilyasfoo** [comment]
Hey, folks! @Copons helped out and he wasn't able to reproduce installed theme not being listed in Calypso's `My Themes` section, which could mean that it only may affect some themes (I was only able to reproduce it with an older theme, BeTheme, but not on a newly generated one).

Additionally, he identified that the `Appearance > Themes` no longer links to Calypso's theme section, but instead goes to wp-admin's theme page. This recent change is a part of navigation redesign project. This means that all installed themes will be listed there, making the bug, if it even exists, inconsequential. 

Closing this issue, but feel free to reopen! Thanks for all the help and feedback! 🙏
