### ISSUE TITLE
Video Stats: Views Column is Not Visible

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#86958]
### Quick summary

In Jetpack Video Stats, the Views column is overflowing the container and isn't visible under ~1180px.

<img width="300px" src="https://github.com/Automattic/wp-calypso/assets/42279181/6e920711-b935-4258-97dd-3e6a5ab8d2fc">

### Steps to reproduce

1. Open the Calypso Jetpack Stats page.
2. Scroll to the Videos section.
3. Observe the overflow.

### What you expected to happen

For the Video views column to display responsively like the columns in the Email Stats to the right of it, and for the Views column to be visible at all viewport widths.

### What actually happened

The Views column in the Video section starts to overflow the container to a hidden state around 1185px, and is fully hidden under around 1170px.

<img width="400px" src="https://github.com/Automattic/wp-calypso/assets/42279181/9d53b63b-16e0-4a35-a0f6-681f0c3f366f">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I'm in Arc/Chrome on an Atomic site.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated 

📌 ACTIONS
- Triaged

**Comment by kangzj** [comment]
tracked by https://github.com/Automattic/red-team/issues/16
