### ISSUE TITLE
Email Stats Page: Breadcrumbs Touch Edge of Viewport

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#86955]
### Quick summary

On the "Stats for Emails` page, the breadcrumbs touch the edge of the viewport. This doesn't appear to happen on other stats pages.

![CleanShot 2024-01-29 at 11 06 29@2x](https://github.com/Automattic/wp-calypso/assets/42279181/d29de65d-a17e-49fe-a4a5-6ff425c7fd9c)

### Steps to reproduce

1. Open Jetpack Stats in Calypso at `https://wordpress.com/stats/day/SUBDOMAIN.wpcomstaging.com`
2. Scroll to the Emails section at the bottom.
3. Click on `View details` to open the `Stats for Emails` page.
4. Observe the issue.

<img width="250px" src="https://github.com/Automattic/wp-calypso/assets/42279181/bcb17086-52bb-47a5-bd8d-352a90cf559d">

### What you expected to happen

For the breadcrumbs to match the styling from the other stats pages, and not touch the edge of the viewport

### What actually happened

The breadcrumbs are not styled consistantly with the other stats pages.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple

📌 FINDINGS/SCREENSHOTS/VIDEO
Reproduced on Chrome, Firefox and Safari viewports smaller than 1360px:

https://github.com/Automattic/wp-calypso/assets/14153300/df3c7741-281c-47ec-93fb-9b1393055353

📌 ACTIONS
- Triaged

**Comment by dognose24** [comment]
I believe this issue has been addressed by https://github.com/Automattic/wp-calypso/pull/89021.
