### ISSUE TITLE
Lativ theme - sticky header 

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/wp-calypso#86965]
### Quick summary

When in the Position of the header, the option "Default" is selected, the header should not stick to the top of the browser.

The header section on the user site is always sticky, no matter the option selected.

### Steps to reproduce

1. Open theme Header Editor.
2. Navigate to the block options and select the "Default" Position:
![Markup on 2024-01-29 at 21:12:52](https://github.com/Automattic/wp-calypso/assets/9025643/5b242210-b981-43f0-ac21-9fd26611e603)
3. Save the changes.
4. Open any page. The header section is sticking to the top of the browser when scrolled:
![Markup on 2024-01-29 at 21:17:24](https://github.com/Automattic/wp-calypso/assets/9025643/68bbae69-f19d-41a7-8a5e-a704bd4fa881)

### What you expected to happen

The header section should not be visible when the "Default" Position is selected.

### What actually happened

The header section is sticking to the top of the browser when scrolled:
![Markup on 2024-01-29 at 21:17:24](https://github.com/Automattic/wp-calypso/assets/9025643/68bbae69-f19d-41a7-8a5e-a704bd4fa881)

I was able to reproduce the issue on my test site.

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by maciejpilarski** [comment]
ZD-7656791

**Comment by devNigel** [comment]
Another report: 8293392-zd-a8c

**Comment by devNigel** [comment]
I have identified that this happens only when a page is set as the home page of the site. 

To get rid of the sticky effect of the header on the home page, you will need to go to Appearance> Editor > Templates > Pages. You should notice a Group block at the top which is set as sticky. Changing that to Default should resolve this issue.

**Comment by annezazu** [comment]
@devNigel this seems to be related to how a theme is built and is working by design with how the overall Group block is set to sticky. Even still, it sounds like this might be worth opening an issue in the theme's repo as feedback from users for what they find confusing about the theme: https://github.com/Automattic/themes/issues/new/choose
