### ISSUE TITLE
Stats: Mismatched title when selecting a custom range

### ISSUE THREAD

**Issue by itsmeichigo** [Automattic/wp-calypso#86986]
### Quick summary

The title for the selected date range on Jetpack Stats always reflects the most recent range based on the selected period. E.g: When "Week" is selected, the title is the last week, not the actual selected date range. 

<img width="996" alt="Screenshot 2024-01-30 at 12 55 16" src="https://github.com/Automattic/wp-calypso/assets/5533851/eb1fb592-cc4b-40d1-953d-0aaff01a261c">

### Steps to reproduce

1. Access wp-admin with Calypso
2. Select Stats
3. Select an arbitrary date range in the past.
4. Notice the big title on the graph doesn't get updated. 

### What you expected to happen

When a custom date range is selected, the range should be displayed on the big title.

### What actually happened

The title only gets updated when picking a different period (day/week/month/year). It would then display the latest range of that period, which doesn't match the specified custom range.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by kangzj** [comment]
Thanks for filing this for us! This definitely is a bug by the looks of it. We'll look into it in the next couple of weeks. Thanks again @itsmeichigo 👍

**Comment by ntsekouras** [comment]
Is this issue still valid? I think not, and we should probably close?

**Comment by kangzj** [comment]
I'm pretty sure this has been fixed 😄 Thanks!
