### ISSUE TITLE
Adding plans to onboarding flow

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#86997]
If we want to leverage the onboarding flow as our single migration flow in the future, we'll need to offer more plans on the page based on the site's current plan.
- **Users with simple sites**: Currently we offer Creator plan here. We'll need to consider if we want to add Entrepreneur plan to the page.
- **Users with Migration/hosting trial plan**: We only allow Creator plan at the moment.
- **Users with Woo Express plan (Woo trial)**: Currently we do not support this flow in the onboarding flow. We'll need to offer Essential and Performance plan for woo trial sites.

![Image](https://github.com/Automattic/wp-calypso/assets/4074459/10454a6e-b18f-44cd-8825-c6e89e74209a)

Reference: https://github.com/Automattic/wp-calypso/issues/86500

**Comment by bogiii** [comment]
Hey @ouikhuan,

Do you know if this is still a relevant issue?
We switched to a different migration mechanism, so we can probably close it. What do you think?

**Comment by ouikhuan** [comment]
The flow has changed so I don't consider this relevant anymore, let's close it.
