### ISSUE TITLE
Advanced SEO: Archives field has focus when switching to this view

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#8699]
In Chrome, when I switch to the SEO tab of the Settings section, the Archives field is focussed for some reason, which is just weird, but also causes the page to scroll down to get that field in view. I can't think of any reason why a specific field should be auto-focused here.

**Comment by beaulebens** [comment]
If I unfocus/blur (click outside) the field, and switch to another panel (e.g. General), then click back to SEO, it's auto-focussed every time.

**Comment by vindl** [comment]
This issue is no longer reproducible.

**Comment by tyxla** [comment]
Ah, I didn't know an issue exists about this one. It was fixed in #11671.

**Comment by vindl** [comment]
Oh nice, I wasn't aware of that PR. Thanks for fixing it @tyxla!
