### ISSUE TITLE
Design picker fails to activate themes

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#86995]
### Quick summary

Trying to activate a theme on an existing site from the Design Picker fails with the following error:

```
We've hit a snag

It looks like something went wrong while setting up your store. Please contact support so that we can help you out.

Need help? Contact support```

Activating themes from https://wordpress.com/themes works as usual.



### Steps to reproduce

1. Go to https://wordpress.com/setup/update-design/designSetup?siteSlug=[site slug]
2. Click on a theme.
3. Click on Continue.

### What you expected to happen

The theme should be activated.

### What actually happened

The following error message was displayed:

```
We've hit a snag

It looks like something went wrong while setting up your store. Please contact support so that we can help you out.

Need help? Contact support```

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Context: 7658363-zen
Please notify the user once the issue is solved.

I was able to reproduce the same issue on a test site, both with and without WooCommerce installed and active.

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Couldn't see anything 

## 📌 ACTIONS ##
- Closed as could not replicate (please reopen if the issue reoccurs) 

##Message to author##
Thanks so much for the report @ariel-maidana  I couldn't replicate the issue. Can you provide some more detailed steps if you are still able to replicate this?
