### ISSUE TITLE
Improve "Congratulations" page after migrating

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#87008]
### Details

After we finish the migration process, we show this to our users:

![current-hooray](https://github.com/Automattic/wp-calypso/assets/25607244/e008503a-3cd7-4f1d-9001-59adf225c7ff)

There's a great opportunity here to provide our users with relevant links. Instead of just one button that opens the Preview, we can provide them with different options:
* `View site` should open the site (with no preview)
* `Go to WP Admin` should open /wp-admin
* `Get the app` we can cross-promote the Jetpack app (https://apps.wordpress.com/mobile/)
* `Migration support resources` to offer some guidance (https://wordpress.com/support/import/import-a-sites-content/#after-importing)

Here's the proposal. For consistency it uses a design/structure we already developed for the checkout and other thank you pages (Letero / Explorers team?).

![say-hello](https://github.com/Automattic/wp-calypso/assets/25607244/9c337fc0-bbb5-49d2-b3d8-12d285785034)

Figma file: DASWajWXHUUjF4pu1yo4fI-fi-92_9467

Figma with the whole flow: DASWajWXHUUjF4pu1yo4fI-fi-22_9

**Comment by renancarvalho** [comment]
@crisbusquets 👋 I assume this is a typo and should be **inquiries**, right?
"Explore our comprehensive support guides and find solutions to all your email **tinquiries.**"

**Comment by escapemanuele** [comment]
This has been done [here](https://github.com/Automattic/wp-calypso/pull/87990)✌️

**Comment by crisbusquets** [comment]
> "Explore our comprehensive support guides and find solutions to all your email **tinquiries.**"

Yes, this was a (funny) typo. Thanks for noticing, @renancarvalho !
