### ISSUE TITLE
Unable to select part of hyperlinked text in the site editor

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#87031]
### Quick summary

Unable to select part of a hyperlinked peice of text in the editor.piece

### Steps to reproduce

1. Create text in a page or post.
2. Add a hyperlink to that text
3. Try to select part of the words in the text
4. The selected area pops back to a small selected area.

### What you expected to happen

To be able to select any part of the text.

### What actually happened

* Tested on 2015 and Mysa themes.
* This is the issue that occurs

https://github.com/Automattic/wp-calypso/assets/13706336/80d57bd7-9c93-4dcb-a090-f7bc832b75f3

* If you remove the hyperlink from the words you get - https://d.pr/v/UJ40az

https://github.com/Automattic/wp-calypso/assets/13706336/27a90824-33c1-4754-b6a3-f87dbec503ba

* Checked to see if the issue was with non-latin characters but issue still occurs. 

https://github.com/Automattic/wp-calypso/assets/13706336/e7ffc3f8-8a56-405f-83d7-e5ed27f26110

* It happens consistently on both 2015 and Mysa

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

7631691

**Comment by jartes** [comment]
Closinga as I'm not able to replicate.
