### ISSUE TITLE
Launchpad: Investigate login endpoints used on the Android app

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#87052]
We need to understand which endpoints are used for logging in the users on the Android app so we can add a hook on these endpoints to update the `jp_mobile_app_last_seen` in real time. 

Important: We should check all login flows, including the "Magic login", which sends a link to the user's email.

This is part of the effort of migrating the "Install the mobile app" task to the launchpad. 

More context: p1706712940362689-slack-C0Q664T29

**Comment by markbiek** [comment]
Android Jetpack app:

I still haven't been able to test logging into the app but here are the API calls made when you're logged out and first launch the app:

- `/wpcom/v2/mobile/feature-announcements`
- `/wpcom/v2/mobile/remote-config`
- `/wpcom/v2/mobile/feature-flags`

On the login form, I do see this call after entering an email address:

- `/rest/v1.1/users/:userEmail/auth-options`

**Comment by markbiek** [comment]
While logging in/Successful login:

* `/rest/v1.1/notifications`
* `/oauth2/token`
* `/rest/v1.1/me`

After logging in:

* `/wpcom/v2/mobile/remote-config`
* `/wpcom/v2/mobile/feature-flags`
* `/rest/v1.1/me/settings`
* `/rest/v1.1/me/sites1
* `/wpcom/v2/sites/:siteID/rewind/capabilities`
* `/wpcom/v2/sites/:siteID/wordads/dsp/api/v1/search/campaigns/site/:sideID`
* `/rest/v1.3/read/menu`
* `/wpcom/v2/mobile/feature-announcements`
