### ISSUE TITLE
Site migration: Update migration-ready (dev side) screen

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#87076]
If someone has han "I am a developer" flag they see this interface first, instead of https://github.com/Automattic/wp-calypso/pull/87028.

Review and adjust the UI:
![Image](https://github.com/Automattic/wp-calypso/assets/25607244/8dc93dd8-f5a7-4ad5-bec1-076f5f06474b)

**Comment by crisbusquets** [comment]
The only thing I'd do here is to make sure that everything is aligned properly and that it uses the default styles for the onboarding flows (font-sizes, spacing, paddings, etc.).

![compare](https://github.com/Automattic/wp-calypso/assets/25607244/49f729b7-49cb-45b8-b911-a0dcd6fbc29f)


Figma file: DASWajWXHUUjF4pu1yo4fI-fi-188_11602

**Comment by agrullon95** [comment]
> The only thing I'd do here is to make sure that everything is aligned properly and that it uses the default styles for the onboarding flows (font-sizes, spacing, paddings, etc.).
> 
> ![compare](https://private-user-images.githubusercontent.com/25607244/301848192-49f729b7-49cb-45b8-b911-a0dcd6fbc29f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDQxMjMsIm5iZiI6MTcwNzUwMzgyMywicGF0aCI6Ii8yNTYwNzI0NC8zMDE4NDgxOTItNDlmNzI5YjctNDljYi00NWI4LWI5MTEtYTBkY2Q2ZmJjMjlmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE4MzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOWViOGQ3MjE0YzIxMTkxMWFjNGU3NjAyNmQ3NDBhYTljNWE2MTcxOGE2NTRlMDllM2YwOWVlMGM0OTFkMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FaD1nXGIU0MbronYawi7Y9xPG1Zhz2XFouKiGLcJzTw)
> 
> Figma file: [DASWajWXHUUjF4pu1yo4fI-fi-188_11602](https://href.li/?https://www.figma.com/file/DASWajWXHUUjF4pu1yo4fI/?node-id=188-11602)


@crisbusquets 
~Where are we getting the values for the `Credential Type` form field in the new design?~ - I found the toggle for field.

Is there anything we want to change in the mobile design? For example, displaying the content on the right side `Do you need help locating your credentials?`. It disappears if I shrink to a smaller viewport.

---

**Current:**

<img width="744" alt="CleanShot 2024-02-09 at 10 12 52@2x" src="https://github.com/Automattic/wp-calypso/assets/10482592/dd607a1f-5dd1-4405-9f55-ece87e0fc985">

**Comment by crisbusquets** [comment]
> Is there anything we want to change in the mobile design? For example, displaying the content on the right side `Do you need help locating your credentials?`. It disappears if I shrink to a smaller viewport.

By "disappear" do you mean that users have to scroll down or that we don't show this content?
Pinging @javierarce, because he did the initial design.

**Comment by agrullon95** [comment]
> > Is there anything we want to change in the mobile design? For example, displaying the content on the right side `Do you need help locating your credentials?`. It disappears if I shrink to a smaller viewport.
> 
> By "disappear" do you mean that users have to scroll down or that we don't show this content? Pinging @javierarce, because he did the initial design.

@crisbusquets  - By "disappear" I mean I don't see that content at all when I shrink the viewport.


https://github.com/Automattic/wp-calypso/assets/10482592/19e940ab-e1f9-4328-a292-4a4effdb2dc8

**Comment by javierarce** [comment]
Thinking about the different possibilities, maybe we could move the contents of the sidebar into a modal and just display a link after the SSH credentials description. That would make the mobile view easier to implement and simplify the layout.

Another, option could be something like this (this is just a quick mockup to illustrate the idea):

![image](https://github.com/Automattic/wp-calypso/assets/4933/d22a4d30-afa7-4d40-baa8-97fad098938b)

In this case, it would probably be necessary to have separate elements for the sidebar and the foldable element and toggle their display based on the viewport size.
