### ISSUE TITLE
Themes: Try draft-js for search input and styling

### ISSUE THREAD

**Issue by seear** [Automattic/wp-calypso#8707]
Try an approach where we can optionally supply a [draft-js](https://facebook.github.io/draft-js/) content-editable div to the `<Search>` component for input.

Potential benefits:
- Full styling capability compared to the overlay div we currently use
- no browser compatibility problems
- no [performance issues](https://github.com/Automattic/wp-calypso/pull/8580)

Related issues: #8304

**Comment by folletto** [comment]
Closing due to some concern on Draft.js size.
