### ISSUE TITLE
Plans: Use 'expiry' instead of 'userFacingExpiry'

### ISSUE THREAD

**Issue by artpi** [Automattic/wp-calypso#8710]
In /sites/:site/plans endpoint we have `userFacingExpiry` prop.
We use it in `plans/my-plan/`. It is pulled in here:
https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/plans/assembler.js#L32

@lamosty has found out, that actually this is just adjusting the expiry date to ending trial.
I am not sure what date should we show... Right now it shows expiry - 3 days.
So we need to:
- Decide what prop should we use and make sure if we need to change this
- See where else we need to change this
- Clean this up / change either on backend OR frontend.

**Comment by gwwar** [comment]
Could we perhaps just use the expiry date and subtract a warning period, (eg 2 weeks)?

This would allow us to remove this date from the endpoint and clean up the client prop.

**Comment by lamosty** [comment]
> Could we perhaps just use the expiry date and subtract a warning period, (eg 2 weeks)?

I would stick to what we are using on the `/purchases` page — `purchases.expiry` (which should be the same as site specific plan `expiry` prop). Why show some 2 weeks warning period if we are not doing it on purchases page as well?

I just want to get rid of `userFacingExpiry` (at least from the assembler), so we don't mistake it for something which it is not again in the future. :)
