### ISSUE TITLE
Pattern Assembler: Mobile preview shows the desktop version of the site

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#87115]
### Quick summary

The mobile view on the Pattern Selection page shows the blocks as they are in the desktop version, not stacked.
Quick video: 
https://github.com/Automattic/wp-calypso/assets/4550351/7ca14511-e162-42c7-9235-d1d9b40918a4

Reported in: pdtkmj-2l9-p2#comment-4181

### Steps to reproduce

1. Open the Pattern Assembler and add a few patterns in the pattern selection step.
2. Pick patterns that use columns.
3. Switch to mobile view via the icon above the site preview. Notice the patterns are not stacked the way they should be on mobile.

### What you expected to happen

I expected the mobile view to show the mobile version, with blocks properly stacked.

### What actually happened

The mobile preview showed the desktop version.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/14153300/1cb81066-076f-41b2-b136-d6ace1e750b1

📌 ACTIONS
- Triaged

**Comment by taipeicoder** [comment]
No longer reproducible. Seems to have been fixed with https://github.com/Automattic/wp-calypso/pull/89588. Please reopen if the issue still persists, thanks!
