### ISSUE TITLE
Stats: The Stats page loads only for Administrators

### ISSUE THREAD

**Issue by RafaelFunchal** [Automattic/wp-calypso#87135]
### Quick summary

[A user reported today in the pt-BR forums](https://wordpress.com/pt-br/forums/topic/estatisticas-completas/) that the Stats page stopped working for them.

Accessing Stats with an Editor account doesn't load the page and the Browser Console shows this error:

```
Uncaught (in promise) ForbiddenError: You do not have the capability to manage settings for this site.
    at k (https://wordpress.com/calypso/evergreen/91021.d11d6fa102b600ad8935.min.js:9750)
```

> These user roles can see the stats: Administrators, Editors, Authors, and Contributors.
> - https://wordpress.com/support/invite-people/user-roles/

Although our public-facing doc says Administrators, Editors, Authors, and Contributors can view stats, it works only for Administrators.

It happens on both Simple and WoA Sites (roles are enabled on Jetpack Stats). **I tested a couple of sites, but it might affect all sites.**

### Steps to reproduce

1. Visit the Stats page with any account with role Editors, Authors, or Contributors.
2. The Stats page fails to load.
3. Visit the Stats page again with an Administrator account.
4. The Stats page loads as expected.

### What you expected to happen

Administrators, Editors, Authors, and Contributors should be able to see Stats.

### What actually happened

Currently, the Stats page loads only for Administrators.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple : Replicated 
– Tested on Atomic: Replicated 


📌 FINDINGS

Stats for an editor on a Simple site:
![Screenshot 2024-02-06 at 16 33 09](https://github.com/Automattic/wp-calypso/assets/2540430/21001dc9-71ca-46f2-8142-3a4f3d6ea852)



And on an Atomic website:
![Screenshot 2024-02-06 at 16 35 22](https://github.com/Automattic/wp-calypso/assets/2540430/88033054-50f6-4755-a2a0-b48d7fd09470)



📌 ACTIONS
– Report kept and triaged.
- Leaving the priority set as blocker given how important stats are on WordPress.com.
- Escalated  p1707237713411699-slack-C02FMH4G8

**Comment by mreishus** [comment]
Deployed a temporary workaround here: https://github.com/Automattic/wp-calypso/pull/87242

**Comment by RafaelFunchal** [comment]
Thanks, @mreishus . I SUed to the user who reported the issue and confirmed Stats loads for their account.

**Comment by grzegorz-cp** [comment]
I opened another PR https://github.com/Automattic/wp-calypso/pull/87246 iterating on the hotfix. if the users don't have the proper rights, it avoids fetching the data causing the loop that was resulting in a blank page.

**Comment by ebinnion** [comment]
It appears this was fixed by the last comment. Closing for now.
