### ISSUE TITLE
Forums: Bring anonymous staff to all forums

### ISSUE THREAD

**Issue by RafaelFunchal** [Automattic/wp-calypso#87145]
### What

Currently, only the English Forum shows staff-something. Localized forums show the HE WP.com username and Gravatar to everyone.

### Why

With more people working on forums, I think we need to expand the anonymous staff username feature to all forums, not only the English one.

At least on [pt-BR](https://wordpress.com/pt-br/forums/) and [PT](https://wordpress.com/pt/forums/), our real username and Gravatar are publicly displayed. It is not normally an issue, but I got a few users (sometimes rude users) messaging me on social media over the years.

**Comment by cat-og** [comment]
📌 ACTIONS
- Feature request kept

**Comment by RafaelFunchal** [comment]
Closing the issue because I wasn't aware of PCYsg-Sg0-p2 when I created it.
