### ISSUE TITLE
Framework: tune upgrades bundle

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8714]
The upgrade bundle, defined as the following in `client/wordpress-com.js` is now past more than 1MB.

```
    {
        name: 'upgrades',
        paths: [ '/domains', '/checkout' ],
        module: 'my-sites/upgrades',
        secondary: true,
        group: 'sites'
    },
```

![pasted_image_at_2016_10_13_16_24_480](https://cloud.githubusercontent.com/assets/1270189/19354357/3df7ea96-911b-11e6-8cd3-eba08b942725.png)

See if we can pull domains and checkout into it's own bundle, otherwise try to get the bundle size down to a more reasonable size.

**Comment by klimeryk** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/15931 🎉
