### ISSUE TITLE
Plan details are overflowing in the comparison grid on a narrow viewport

### ISSUE THREAD

**Issue by oswian** [Automattic/wp-calypso#87164]
On `/plans/:site` with a narrow mobile viewport (2 plans side-by side) there is some text overflow in the right-hand plan:

<img src="https://github.com/Automattic/wp-calypso/assets/69198925/3e08cd9b-0859-4011-bb6a-9ce55a534c20" width=400 />

**Comment by ddc22** [comment]
@oswian can you also include the exact pixel resolution at which this breaks? AFAICR this does not break for something like the Iphone SE which is one of the most smallest resolutions out there. If it's breaking at even smaller screens we can probably make a call On what th the minimum resolution we support and prioritise accordingly :)

**Comment by oswian** [comment]
@jdc91 🤔 Hmm, yes this does occur for me with iPhone SE. Just retested in Chrome:

![CleanShot 2024-02-06 at 15 00 21@2x](https://github.com/Automattic/wp-calypso/assets/69198925/1e66ce82-4665-46b9-bb62-641cdfe74930)

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue on my side, plans are displayed one under the other:
![IMG_BD5E74180213-1](https://github.com/Automattic/wp-calypso/assets/9025643/b828ee6e-10d2-43d0-93b7-1ed2b51bde32)
![IMG_AABA3E48AF8E-1](https://github.com/Automattic/wp-calypso/assets/9025643/4dbf6c25-d7b9-441a-9046-1527e27dc6d3)

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)
