### ISSUE TITLE
Email stats: lock the info for first X minutes

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#87174]
When publisher sends out a blog post/email, we start showing the "recipients" stat right away, which is a significantly lower number than the number of their subscribers. As emails roll out, the number gets updated gradually.

That gets publishers confused for first ~5-10 minutes depending on list size, and they are suspecting that the email didn't get sent as intended. We sometimes get asked "why my email didn't go to all subscribers", when all they would need to do is wait a bit longer for emails to send and stat to update.

Looks like this now:

<img width="1274" alt="Screenshot 2024-05-07 at 11 13 58" src="https://github.com/Automattic/wp-calypso/assets/87168/b802265b-b787-47f4-af05-447ec54576e0">

We could lock the numbers for the first X minutes while the post is still being emailed out, as it can take some time before full rollout:

<img width="985" alt="Screenshot 2024-05-01 at 18 16 46" src="https://github.com/Automattic/wp-calypso/assets/87168/cb8759e4-8f4f-4b76-b425-9cc497af0507">

Let's lock this for 5mins after post's published date, and adjust minutes if needed. While nice, we don't need a more complicated check create a loopback to check with server if emails are still sending if a simple "show stats if x minutes since post was published" covers it.

We can either use server-time and have the backend send us a flag to hide/show stats, or alternatively simply rely browser time, which can be little less reliable but again should mostly work fine.

Slack p1707128954863279-slack-C02NQ4HMJKV

**Comment by edanzer** [comment]
Resolved in https://github.com/Automattic/wp-calypso/pull/97726
