### ISSUE TITLE
Jetpack Stats Traffic Chart: Tooltip popover appear and disappear on mouse hover

### ISSUE THREAD

**Issue by ecgan** [Automattic/wp-calypso#87173]
### Quick summary

When we are in the Jetpack Stats > Traffic tab, and we do mouse hover over the chart at the bottom of the browser window, the tooltip popover appears and disappears, and we are not able to read what is inside the tooltip.

See demo video below:

https://github.com/Automattic/wp-calypso/assets/417342/230f4b4e-8951-4711-8975-ff10764996b8

To workaround this issue, we can scroll the page so that the chart is no longer at the bottom of the page, and the tooltip popover has enough space to be rendered below the chart. This workaround is shown in the demo video above.

### Steps to reproduce

1. Go to `https://wordpress.com/stats/day/<domain>`
2. You should see the Traffic tab.
3. Resize the browser window and/or scroll the page so that the chart is shown near the bottom of the browser window.
4. Move the mouse across the chart.

### What you expected to happen

Tooltip popover should appear, and you should be able to read what is inside the tooltip.

### What actually happened

Tooltip popover appears and disappears, and we are not able to read what is inside the tooltip.

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by kangzj** [comment]
We are replacing the bar char with line chart soon: https://github.com/Automattic/jetpack-roadmap/issues/492
