### ISSUE TITLE
[Continue with GitHub] Coordination with Jetpack Mobile team

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#87180]
Get the conversation going with the Jetpack Mobile team, since they'll need to add the GitHub button as well to provide a coherent experience.

We should start the conversation once we have the specifics such as `redirect_uri` in place.

**Comment by ivan-ottinger** [comment]
I will bring this up to the Jetpack mobile team once we have the CfT post published.

**Comment by ivan-ottinger** [comment]
Message to Jetpack Mobile: p1708619808494429-slack-C0180B5PRJ4
