### ISSUE TITLE
Launchpad: Add an option to allow old sites to display the Site Setup Launchpad instead of the checklist

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#87195]
As part of the site migration, we need a new option to define whether or not the new Site Setup Launchpad should be displayed on the Customer Home. This option will be set when the site is considered migrated. For now, there are two ways that this can happen:
* When the user of old sites clicks on the "Show site setup" on the main banner
* When we run the migration for old sites

The condition should be placed in the function linked below:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Subzr%2Sivrjf.cuc%3Se%3Q1opo234r%23153%2Q175-og

More context: paYKcK-3Z5-p2

**Comment by markbiek** [comment]
Implementation: D137452-code

**Comment by valterlorran** [comment]
Closing this, as D137452-code was merged.
