### ISSUE TITLE
Certain Buttons Unresponsive in Site Editor on Mobile Browsers and Apps 

### ISSUE THREAD

**Issue by kelasante** [Automattic/wp-calypso#87247]
### Quick summary

Buttons that appear in the top toolbar when editing a Template in the Site Editor are not tappable. Nothing happens when you click on a specific feature like the save or style icon.

<img width="660" alt="Markup 2024-02-06 at 17 39 22" src="https://github.com/Automattic/wp-calypso/assets/74204272/94a69c80-931c-4ed5-b1da-ebc842325900">

Additionally, when you scroll to Patterns, and click to open a pattern, nothing happens.

<img width="820" alt="Markup 2024-02-06 at 17 42 44" src="https://github.com/Automattic/wp-calypso/assets/74204272/e8847e70-63a2-40ef-8c7a-f479a6b2ccda">

### Steps to reproduce

1. On a mobile app or mobile browser on a site with an FSE theme active, open the Site Editor by clicking the option to update your site's design. 
2. Go to templates 
3. Click on any of the buttons at the top of the page, like save or the block inserter 
4. Similarly, go to Patterns, and click or double-click on a pattern to open it.

### What you expected to happen

To be able to access specific functionality by clicking on the button 

### What actually happened

Nothing happens 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Able to replicate on Safari on iOS, Jetpack app and WordPress app

**Comment by kelasante** [comment]
Issue first reported in 7677675-zen

**Comment by SiobhyB** [comment]
The regression appears to come from Gutenberg, the buttons become responsive again after changing the `z-index` for the following selector locally:

https://github.com/WordPress/gutenberg/blob/21f0fc0a813d8b4ad85a3a255e973567c9e68ce7/packages/edit-site/src/components/layout/style.scss#L38-L48

I wonder if it was introduced following the changes in https://github.com/WordPress/gutenberg/pull/58077 or similar changes to fix other site editor regressions.

**Comment by SiobhyB** [comment]
I was able to confirm the issue's reproducible on a self-hosted site with version 17.6.3 of the Gutenberg plugin installed. I've copied over this issue to the Gutenberg repo at https://github.com/WordPress/gutenberg/issues/58781.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Reproduce on a Simple Site and Atomic Site running GB 17.6.3. Deactivating GB fixes the issue.

📌 ACTIONS
- Triaged

**Comment by Copons** [comment]
I've deployed the hotfix for the top bar: https://github.com/Automattic/wp-calypso/pull/87274

Although, the patterns menu is not hotfixable as it pertains to the architecture of the Site Editor sidebar, and therefore should be fixed in Core.

Core is aware of that (of both issues, actually), so I'll leave it to you to decide whether to keep this issue open or close it. 🙂

**Comment by Copons** [comment]
This was fixed on Core as well: https://github.com/WordPress/gutenberg/issues/58781
