### ISSUE TITLE
Blogroll: Some blavatars are broken

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#87241]
### Quick summary

As I looked through the blogroll block today, I noticed that there are cases of the blavatars being broken. 

<img width="334" alt="Screenshot 2024-02-06 at 12 11 45 PM" src="https://github.com/Automattic/wp-calypso/assets/1126811/494d8ece-b6b9-4ce3-a345-0850bec24bf6">

In the case of @richtabor's site, it looks like the blavatar that we have points to richtabor.com (https://richtabor.com/wp-content/uploads/2023/12/cropped-avatar.jpg) while his domain is now rich.blog and the avatar does load at https://rich.blog/wp-content/uploads/2023/12/cropped-avatar.jpg.

My guess is that there are a few solutions here:

- We should consider support a redirect from `richtabor.com/wp-content*` to `rich.blog/wp-content*`
- For blavatars, we could force the media to load from the primary domain.
- Have a fallback in the blogroll block (and elsewhere) such that the globe is loaded as a fallback when an image fails to load.

### Steps to reproduce

1. Follow rich.blog in the reader
2. Add blogroll block

### What you expected to happen

No broken images in the blogroll blocks

### What actually happened

Broken images.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is usable.

### Platform (Simple and/or Atomic)

Atomic

**Comment by ebinnion** [comment]
I accidentally reported as the platform is unusable. Apologies. Corrected priority to normal.

**Comment by richtabor** [comment]
Yea, I've noticed this as well. 

I've also recently updated my site icon and logo (to https://rich.blog/wp-content/uploads/2024/02/cropped-rich-avatar.jpg) , but I'm not sure where to update it—or that I had to. 

Noticed the old one still loading here: 

![CleanShot 2024-02-08 at 13 14 00](https://github.com/Automattic/wp-calypso/assets/1813435/857f55f0-50e2-431f-a9d0-ed43577a6593)

Related?
