### ISSUE TITLE
Cannot Upload plugin .zip file on Simple Sites with Plugin-enabled Plans

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#87245]
### Quick summary

On a simple site with plugin-enabled plans (like Creator, Entrepreneur or Pro), it's not possible to upload a plugin zip file, but possible with a theme zip file. 
Before being able to upload a plugin zip file, the site needs to be AT first by installing a plugin from Plugins, or activating hosting features.  

### Steps to reproduce

1. Download a plugin and save the zip file.
2. Add a Creator or Entrepreneur plan to a simple site.
3. Go to Plugins > select Upload. 
4. Click 'Continue' to agree that the site name will end in .wpcomstaging.com 
5. There will be a greyed out "Drop files of click here to install" box. 
<img width="920" alt="Screenshot 2024-02-06 at 20 32 24" src="https://github.com/Automattic/wp-calypso/assets/36863633/69924b99-c96e-42d0-b1db-20cf49dcfe42">

6. Even if you drag the zip file in the greyed out box, it won't install. 

<img width="973" alt="Screenshot 2024-02-06 at 20 33 00" src="https://github.com/Automattic/wp-calypso/assets/36863633/8edd53c6-6a24-489f-9453-88e56f7fbc5e">

### What you expected to happen

It's possible to upload the plugin zip file on simple sites with  plugin-enabled plans (like Creator, Entrepreneur or Pro) and not just theme zip file. 

### What actually happened

On simple sites with plugin-enabled plans (like Creator, Entrepreneur or Pro), it's not possible to upload a plugin zip file. But possible with theme zip file. 

In Themes > Install themes, "Drop files of click here to install" is not greyed out and the theme zip file can be uploaded: 
<img width="1100" alt="Screenshot 2024-02-06 at 20 23 37" src="https://github.com/Automattic/wp-calypso/assets/36863633/d059f17f-f4bd-4c6a-abb8-b30ed54955f7">

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Bug discovered during self-testing. 
- Chrome 121 
- macOS 14.3

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
I was unable to replicate the same as the OP but got another problem with exactly the same steps so they may be related.
Every time I clicked Upload it looked like it was installing WooCommerce. There was no warning about changing the name of the site. The site didn't convert to AT either.
Here is a video

https://github.com/Automattic/wp-calypso/assets/13706336/d7a2962f-5ac3-4030-afe7-db8fe2cb8199



## 📌 ACTIONS ##
Triaged

**Comment by cpapazoglou** [comment]
It should have been resolved by https://github.com/Automattic/wp-calypso/pull/88257
