### ISSUE TITLE
Site Editor: Move Top Bar Hotfix to wpcom-block-editor/default

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#87277]
### Details

In https://github.com/Automattic/wp-calypso/pull/87274 we released a hotfix for the Site Editor top bar in the `wpcom` folder of the `wpcom-block-editor` package.

It was a decision taken to ship the change quickly, but in fact, the change should live in the `default` folder, which is used by all site types, whereas `wpcom` is only loaded on Simple and Atomic sites.

To do so, though, we need to also update the package on Jetpack, [to enqueue the new `default/editor.min.css` styles](https://github.com/Automattic/jetpack/blob/9b0d6d052853ea7e1d5457bcf50d31d27dad5c9e/projects/plugins/jetpack/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L309).

We should also keep an eye out to Gutenberg, and see if the issue was eventually fixed upstream!

### Related

https://github.com/Automattic/wp-calypso/pull/87274

**Comment by dsas** [comment]
It was fixed in GB v17.7 via https://github.com/WordPress/gutenberg/pull/58852 which has already been rolled out to all dotcom sites.

**Comment by Copons** [comment]
Thanks for checking @dsas!
I've moved the issue to the next sprint for convenience and raised the priority.
