### ISSUE TITLE
[Continue with GitHub] Whitelist localhost calypso redirect URLs

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#87278]
For the development purposes, we will need to whitelist the following URLs (at least):

- `http://calypso.localhost:3000/start/user`
- `http://calypso.localhost:3000/log-in/github/callback`

Related patch: D137372-code.

**Comment by ivan-ottinger** [comment]
Patch: D137507-code.

**Comment by ivan-ottinger** [comment]
I have added two more URLs (`http://wordpress.com/me/security/social-login` & `http://calypso.localhost:3000/me/security/social-login`) to the whitelist in D137543#2657171-code.

**Comment by mashikag** [comment]
Resolved by: 
D137507-code
D137543-code
