### ISSUE TITLE
Checkout fails when using the DP to buy a partner theme while on an annual starter or explorer plan

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#87281]
### Quick summary

All sites can use the onboarding design picker at any time. Sites with a annual or longer starter or explorer plan can choose a Partner theme in the design picker. A partner theme adds a mandatory upgrade to the monthly Creator plan, but this won't work - we don't allow "upgrades" to a lower length plan.

### Steps to reproduce

1. Get a site on an annual or greater starter or explorer plan
2. Go to https://wordpress.com/setup/site-setup/designSetup?siteSlug=YOURDOMAINHEREDOTCOM
3. Choose a partner theme
4. Press Unlock theme
5. See the dialog that says you're going to be on the creator plan with a monthly price
6. Press Continue
7. If you get a warning about the domain changing press Continue

### What you expected to happen

See a checkout screen with two items: a monthly creator plan and a monthly paid partner theme and be able to checkout

### What actually happened

Empty cart with error messages including "Sorry, that plan is not a valid ugprade from your current plan"
<img width="1423" alt="Screenshot 2024-02-07 at 17 43 57" src="https://github.com/Automattic/wp-calypso/assets/93301/7d06febd-a546-4cc4-8ae3-4d49dedc786a">

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

The POST to https://public-api.wordpress.com/rest/v1.1/me/shopping-cart/somedigits includes adding a `business-bundle-monthly` product. The response includes an empty product list and two errors with codes `invalid-product-upgrade` and `remove-marketplace-theme`.

Invalid product upgrade probably comes from here: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Sqrsnhyg%2Qfubccvat%2Qpneg%2Qinyvqngbe.cuc%3Se%3Q09or4p97%231673-og which says "This allows a plan upgrade with same or longer term OR a same plan term change (up or down)."

**Comment by dsas** [comment]
@Automattic/bespin maybe one for your backlog? I think if the site already has a plan then we should upgrade the plan but keep the same billing period.

**Comment by cpapazoglou** [comment]
> Get a site on an annual or greater starter or explorer plan
Go to https://wordpress.com/setup/site-setup/designSetup?siteSlug=YOURDOMAINHEREDOTCOM

@dsas is https://wordpress.com/setup/site-setup/designSetup surfaced in any flow for existing sites on a plan?

**Comment by dsas** [comment]
> Is https://wordpress.com/setup/site-setup/designSetup surfaced in any flow for existing sites on a plan?

Yes @cpapazoglou . The dashboard does this in at least two ways (sorry I'm not sure on the exact logic here). 

Sometimes the "Next steps for your site" includes a "Select a design" step 
<img width="904" alt="Screenshot 2024-02-08 at 10 41 09" src="https://github.com/Automattic/wp-calypso/assets/93301/93d5394d-355b-463d-87d5-45989069f321">

Sometimes, just going to the my home for a given site will redirect you back into the launchpad, which includes a "Select a design" step.

<img width="717" alt="Screenshot 2024-02-08 at 10 42 27" src="https://github.com/Automattic/wp-calypso/assets/93301/af41f2b8-dd9e-4d69-9111-aca16db9d1e8">

Then there's the other cases of people bookmarking things and using the browser history.

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my test site:
![Markup on 2024-02-16 at 16:34:05](https://github.com/Automattic/wp-calypso/assets/9025643/3e8b9f3d-6493-4f66-ab5d-56ae160f5686)


📌 ACTIONS
– Triaged
