### ISSUE TITLE
Launchpad: Get the list of sites to be migrated to the Site Setup Launchpad

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#87308]
We need to get the list of old sites that should be migrated from the Site Setup checklist to the new Launchpad, keeping the progress that they made with the existing tasks.

We need the list of sites so we can iterate our migration script over this list, applying the infrastructure that will be introduced on the following diff: D137402-code

We can use Dale's comment as a starting point, as he already made a query available: paYKcK-3Z5-p2#comment-2885

**Comment by andres-blanco** [comment]
This is done. See p1707768590699809-slack-C0Q664T29
