### ISSUE TITLE
Launchpad: Disable the old Site Setup task hooks for new sites or migrated sites

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#87311]
We shouldn't be populating the options after the migration or for sites that were already migrated. We should prevent the code responsible for "completing" the old tasks from being executed. This will also ensure a smooth cleanup in the future.

For that, we should skip the hooks related to the Site Setup checklist when the site is displaying the Launchpad on the Customer Home. Currently, we are hooking the completion logic here:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sbaobneqvat%2Qpurpxyvfg%2Snpgvba%2Qunaqyref.cuc%3Se%3Q1qp108r8-og

Note that some of the tasks on the Site Setup checklist won't be hooked in the file above, because some of tasks performs the completion check in run time.

**Comment by daledupreez** [comment]
Note that we should probably run the checks inside the hooks themselves, as the site context may change between the functions being hooked in and the related hook being run.

**Comment by andres-blanco** [comment]
diff: D137775-code

**Comment by valterlorran** [comment]
Closing this as D137775-code was merged.
