### ISSUE TITLE
Refreshed Stream Idea: Extra wide cards for 1280 and up

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8732]
This is mostly just a suggestion for @jancavan. The other day, @blowery was talking about how the refreshed stream view looks a little lost at wider widths, and we all agreed. So I went back to my original designs to see if we could widen the main column at the largest (1280) breakpoint. Here's what I came up with.

![followed-1280](https://cloud.githubusercontent.com/assets/24388/19366681/fa0907b6-914c-11e6-9933-43eb83710b89.png)

In this revision, the main column increases to 850px, and the photos in the default cards widen to 300px. Otherwise, everything else is the same. For browsers wider than 1280, the main column would stay the same width and center, as before.

I think it looks good! I wouldn't want to go any wider than this, as the text gets too wide in the Text and Gallery cards. But I think this would be a good idea for the big monitor crowd. 

Thoughts?

**Comment by jancavan** [comment]
It looks good for default cards (with thumbnail/excerpt), but the excerpt-only ones become a bit wide. Instead of ~70 characters per line, it'd be around ~90. I don't know if that's optimal, but probably not too bad?

**Comment by fraying** [comment]
Yeah, it’s the upper limit of readability, but I think it’d be an improvement. Easy to try? (It's icing.)

**Comment by fraying** [comment]
We could also try something in-between: like an 800px wide column. We could play with it and see how it feels, at least.

**Comment by jancavan** [comment]
Going to create a `/try` branch for this.

**Comment by fraying** [comment]
Thanks! Let me know what you think.

**Comment by jancavan** [comment]
Settled with an `830px` stream width and a `250px` featured image.

Addressed in: https://github.com/Automattic/wp-calypso/pull/8792
