### ISSUE TITLE
Command Palette: Check bundle size

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#87326]
Check the bundle size of the new app and analyze if it’s too big. We might need to find ways to decrease it.

Could be done now, but it will need doing again once we have ported a sizeable number of commands, as that might increase the size.

**Comment by mmtr** [comment]
This is the current size:

<img width="477" alt="Screenshot 2024-02-29 at 11 45 09" src="https://github.com/Automattic/wp-calypso/assets/1233880/cb916e41-ca65-4797-a82f-850ad542f0cd">

It's not great, but it's lighter than other apps such as `wpcom-block-editor`, `blaze-dashboard`, or `odyssey-stats`. The difference is that we're loading this on every WP Admin page.

If React and/or the `@wordpress/*` packages would be globally available in WP Admin like they are in the editor, we could decrease the bundle size, but I don't see Core switching to that any time soon.

**Comment by dsas** [comment]
That's about half the size of the help center which is similarly loaded on every page and roughly the same size of the notifications area. I think that's ok individually, but it definitely adds up in aggregate.

**Comment by mmtr** [comment]
Yeah, I think the size is fine for now. But one quick improvement we can make is to [load the script asynchronously](https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/), so at least we won't be blocking the loading of WP Admin

**Comment by mmtr** [comment]
> If React and/or the @wordpress/* packages would be globally available in WP Admin

Turns out the packages are already available: https://core.trac.wordpress.org/browser/tags/6.4/src/wp-includes/default-filters.php#L565

So I think we can remove them from the bundle with webpack and add them as dependencies when calling to `wp_enqueue_scripts`, so we should be able to decrease the size. I'll take a further look tomorrow.
