### ISSUE TITLE
Update pingback email template

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#87336]
These old templates make us look very outdated, let's just swap to new one and adjust copy so that it feels modern/smooth/clear what pingpacks even are.

![image](https://github.com/Automattic/wp-calypso/assets/87168/177f6b6f-155c-40ed-b1af-f15af8349b50)

This one is for "waiting for approval". I'm testing if approved pingback has another template.

**Comment by crisbusquets** [comment]
@simison what about this?

The version on the left uses the same structure as the email we send now. The other is a slightly different version, where it highlights the content of the site linking to you, instead of an excerpt of your own post.

I added a tip at the bottom to briefly explain what's a pingback. And I also removed the WHOIS and website links at the bottom.

<img width="1130" alt="Screenshot 2024-02-09 at 16 28 42" src="https://github.com/Automattic/wp-calypso/assets/25607244/50e63fc7-7d37-44a7-b0d8-a5a27283512b">

**Comment by simison** [comment]
Looks good! I'll see how easy the excerpt update is, and focus on template first.

Thoughts on subject line? Currently:

<img width="500" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/2b7e34df-7284-4f5c-b6d4-9a21d77e8edb">

I'll at least update "From" name to be "WordPress.com" instead of "WordPress".

Thoughts on using "Pingback" in the title, as it's kind of special WP vocabulary? 🤔

**Comment by simison** [comment]
Oh and what about "...waiting approval" bit to make that clearer? Current comment approval email:

<img width="1132" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/367cd574-f0ca-44b5-a8b5-9e265baab34a">

**Comment by crisbusquets** [comment]
> Thoughts on using "Pingback" in the title, as it's kind of special WP vocabulary? 🤔

For comments we use this structure:
{[Site name]} {username} liked your post {post title}

We could use:
{[Site name]} {username} added a pingback to your post {post title}

`pingback` is not a verb, so we can't say `pingbacked`(?) 😆

**Comment by crisbusquets** [comment]
> Oh and what about "...waiting approval" bit to make that clearer? Current comment approval email:
> 

What about this?

I removed the "Great post worth seeing...", it distracts from the primary action (Approve/Trash).

The subject should also be updated to:

{[Site name]} {username} added a pingback to your post {post title}

<img width="887" alt="Screenshot 2024-02-09 at 17 42 02" src="https://github.com/Automattic/wp-calypso/assets/25607244/9527ecd3-834a-4204-a7d0-cd2ff7ee925c">

The Figma file for both designs is this one (right side): uwEavMdyNLecNt6Ru3M2Za-fi-4159_1420

**Comment by simison** [comment]
Done in D137809-code
