### ISSUE TITLE
Command Palette: Implement more complex command

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#87330]
Implement a more complex command that involves a site selection step and/or a capabilities check (e.g. Add new post):

* It will use the wpcom-proxy-request to make the API call to fetch the sites. Does this work in WP admin?

**Comment by mmtr** [comment]
As I feared, the wpcom-proxy-request library doesn't work out of the box in WP Admin. This is the error I get when making an API call:

```
{
    "code": 400,
    "headers": [
        {
            "name": "Content-Type",
            "value": "application\/json"
        }
    ],
    "body": {
        "error": "authorization_required",
        "message": "Access token does not have the required scope"
    }
}
```

**Comment by mmtr** [comment]
After further investigating the issue, I found out that the `/me/sites` endpoint (used to fetch all the user sites) cannot be accessed from WP Admin due to some security measures in place.

I asked Systems if they can expand on that and what would be the best way forward: pMz3w-jiR-p2

**Comment by rcrdortiz** [comment]
The investigation is finished, we won't be implementing complex commands as agreed.
