### ISSUE TITLE
[Continue with GitHub] Show link to support document when no public email is set

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#87338]
Currently when the GitHub account doesn't have a public email record set we throw this error: 

```
return new WP_Error( 'github_no_email', __( "Your GitHub account doesn't have any public email address set." ) );
````

It might improve usability if we link to a support document here as well.

**Comment by ivan-ottinger** [comment]
Since we are now able to get the non-public email with the user's permission, this task is no longer needed.
