### ISSUE TITLE
Move Newsletter Categories to Jetpack: Investigate effort to implement UI

### ISSUE THREAD

**Issue by andregardi** [Automattic/wp-calypso#87345]
On the Newsletter setting page, there is the **Newsletter categories** section.

![Image](https://github.com/Automattic/wp-calypso/assets/33497086/99b4f301-3689-4533-99c9-5f2a6bea06bc)

As part of the effort to untangle calypso from wp-admin, we should recreate this section on Jetpack Newsletter setting page:
https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/_inc/client/newsletter/index.jsx

We have dedicated tickets to explore API for read/write those settings.
We also have the first interaction on designs: p1HpG7-r4W-p2

This task aims to investigate the level of effort to build this UI.
- Do we need to build components from scratch?
- Can we use some jetpack components that exist?

**Comment by yansern** [comment]
This is completed.
