### ISSUE TITLE
Move Newsletter Categories to Jetpack: Investigate the API for categories

### ISSUE THREAD

**Issue by andregardi** [Automattic/wp-calypso#87344]
At the Newsletter setting page, there is the **Newsletter categories** section.

![Image](https://github.com/Automattic/wp-calypso/assets/33497086/99b4f301-3689-4533-99c9-5f2a6bea06bc)

As part of the effort to untangle Calypso from wp-admin, we are recreating this section on Jetpack Newsletter setting page:
https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/_inc/client/newsletter/index.jsx

If we activate the toggle, the section becomes a category management tree.
![Image](https://github.com/Automattic/wp-calypso/assets/33497086/131bcd6e-cb14-4ff3-af11-b9c9dfa4ba8e)

At https://github.com/Automattic/jetpack/pull/35585, we already made the discovering for API implementation of the toggle.
The next steps are making the API discovery to edit categories and save which ones are checked for Newsletter.

We will have other issues to match the UI with the proposed designs. So it is ok to work focused on the API with minimal effort on front-end, just to ensure the API communication works.

**Comment by yansern** [comment]
This is completed.
