### ISSUE TITLE
Tenku theme: Category page displays categories from the theme and not what the user created

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#87364]
### Quick summary

In Tenku theme, a category page displays other categories below that comes from the theme and are not replaced by what the user created. 

### Steps to reproduce

1. Activate the Tenku theme. 
2. Go to Posts > Categories and create a couple of categories like Animals and Plants (and additional categories for testing)
3. Go to Posts and assign posts to Animals category and Plants category. 
4. Visit the category pages `category/animals` and `category/plants`. At the bottom of those category pages will be **Archives** and will display the categories from the theme which are: 
_Health. Fashion. Food. Shopping. Events. Fiction. Travel. Japan. Education._
and will not display the categories you created. 

### What you expected to happen

In a category page under Archives, the categories listed will be the categories you created and not display the categories from the theme: _Health. Fashion. Food. Shopping. Events. Fiction. Travel. Japan. Education._

### What actually happened

In a category page under Archives, the categories listed are the categories from the theme: _Health. Fashion. Food. Shopping. Events. Fiction. Travel. Japan. Education._ and does not display the actual categories you created. 

### Tenku theme demo https://tenkudemo.wordpress.com/category/fashion/
<img width="1220" alt="Screenshot 2024-02-11 at 09 50 53" src="https://github.com/Automattic/wp-calypso/assets/36863633/56c01e51-66b7-4851-a24f-76e928a9f251">

<hr />

### User's site with Tenku theme, category page: 

<img width="2256" alt="Screenshot 2024-02-11 at 09 50 11" src="https://github.com/Automattic/wp-calypso/assets/36863633/cd074274-fd94-4a19-9a1d-9be35a8b2676">

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Tenku theme
- I was able to replicate this issue on my site using Tenku theme. 
- User report: 7720452-zen

**Comment by kspilarski** [comment]
This is a similar case with the **Spiel theme**. On a category page, it will show other categories at the bottom, but none of the categories I created. It shows the categories from the theme instead like Reviews. News. Guides. Deals. Videos. Reader Poll. Features. etc. 

<img width="1458" alt="Screenshot 2024-02-11 at 10 19 26" src="https://github.com/Automattic/wp-calypso/assets/36863633/64179830-6214-46c9-8d54-adc15665ee43">

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Replicated
– Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my test site.

📌 ACTIONS
– Triaged

**Comment by annezazu** [comment]
Hey folks! This isn't a bug so much as by design of the theme. To explain, this theme isn't dynamically showing categories on the site. Instead, this theme comes with some categories and then links to them by having them listed out as linked paragraph blocks. You can see this when you edit the template:

https://github.com/user-attachments/assets/dd5888d2-af6e-44ba-97ee-e74abe38c6c2

This is likely due to design limits with the categories block. I agree though that this creates a confusing experience and have opened an issue in the theme repo to ensure the feedback is logged: https://github.com/Automattic/themes/issues/8054
