### ISSUE TITLE
Checkout: `Read more` is still visible when the container is empty

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/wp-calypso#87368]
![Image](https://github.com/Automattic/wp-calypso/assets/12505355/ef7ae831-7cb6-4e98-b93f-f82ceec2fb0e)

As I was testing TOS updates, I noticed that the `Read more` button is still visible even if the container is empty. I would expect that if there were no additional TOS statements in the container, the button would be hidden.

I was forcing the promotional period TOS by hard-coding a discount in the backend. So this probably needs to be tested with a 100% coupon and other products to confirm if the behavior is consistent.

**Comment by sirbrillig** [comment]
This should be fixable by creating a new component to wrap this code:

https://github.com/Automattic/wp-calypso/blob/667602f05b9e11ef47d67eb9d96378205bc70b38/client/my-sites/checkout/src/components/checkout-terms.tsx#L106-L121

That component would just need to look for `children` something like this:

```js
function CheckoutTermsReadMore( { children }: { children: ReactNode } ) {
	const translate = useTranslate();
	if ( ! children ) {
		return null;
	}
	return (
		<TermsCollapsedContent>
			<FoldableCard
				clickableHeader={ true }
				compact
				className="checkout__terms-foldable-card"
				header={ translate( 'Read more' ) }
				screenReaderText={ translate( 'Read more' ) }
			>
				{ children }
			</FoldableCard>
		</TermsCollapsedContent>
	);
}
```

called something like this:

```js
<CheckoutTermsReadMore>
	{ shouldShowRefundPolicy && <RefundPolicies cart={ cart } /> }
	{ shouldShowBundledDomainNotice && <BundledDomainNotice cart={ cart } /> }
	{ shouldShowInternationalFeeNotice && <InternationalFeeNotice /> }
	{ shouldShowJetpackSocialAdvancedPricingDisclaimer && (
	<JetpackSocialAdvancedPricingDisclaimer />
	) }
</CheckoutTermsReadMore>

```
