### ISSUE TITLE
Make Copy Site available to site Admins

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#87361]
### What

Only site owners have the option to "Copy Site", but not site admins. Even the site is eligible to be copied, this option is limited to site owners only. 

### Why

Site admins have access to almost everything, but not "Copy Site". I'm not sure if this is a bug, or whether we intend to have this option for site owners only and not admins. 

### How

`7719530-zen `

**Comment by maciejpilarski** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
The request has been answered in:
https://github.com/Automattic/en.support-docs-content/issues/2323

📌 ACTIONS
– Triaged
