### ISSUE TITLE
Firefox spacing issue on "Use a domain I own"

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#87387]
#### Steps to reproduce

1. Using Firefox, visit https://wordpress.com/start
2. On the Domain step, click "Use a domain I own"
3. Notice that the placeholder text overruns the `https://`

![image](https://github.com/Automattic/wp-calypso/assets/917632/6ecef027-6ebf-45c8-8637-3ac87df25290)

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Mac and Firefox – Could Not Replicate 
- Tested on PC and Firefox –Could Not Replicate 


📌 FINDINGS/SCREENSHOTS/VIDEO
![Image](https://github.com/Automattic/wp-calypso/assets/86028337/43377fe5-deac-49e8-bdf0-3794f142c359)



📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by markbiek** [comment]
I'm still seeing this.

<img width="1182" alt="CleanShot 2024-02-23 at 07 13 39@2x" src="https://github.com/Automattic/wp-calypso/assets/917632/d9511860-b550-40dd-b24b-e5af880efc5e">


Firefox 122.0.1
OSX 12.6.7

**Comment by sixhours** [comment]
I'm not able to reproduce this on Sonoma 14.2.1/FF 123.0.1:

![Image](https://github.com/Automattic/wp-calypso/assets/2124984/850d6d3d-53dd-4854-b2db-b96c14e1a8fc)

@markbiek do you have any extensions running that might be interfering with the layout? Or maybe it's the Mac OS version.

**Comment by markbiek** [comment]
> @markbiek do you have any extensions running that might be interfering with the layout? Or maybe it's the Mac OS version.

The issue may be that my default font-size is fairly large (18px). I tried it in Firefox Developer Edition with the default font size and it's not an issue.

So I think this can safely be closed.
