### ISSUE TITLE
Stats: Hide upsells for Atomic sites

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#87397]
### What

Only show upsells for Jetpack sites

![image](https://github.com/Automattic/wp-calypso/assets/1425433/6b17a421-7e92-4f0d-9a37-bb983c6ec1a3)

This is the only one that I know of, but it might be worth a review and see whether we have any other ones.

### Why

Atomic site is WPCOM, which have their own plans/products, and some products are not available for them either.

### How

Hide upsells for Atomic sites

**Comment by a8ck3n** [comment]
I'll look into this one.
