### ISSUE TITLE
Site Migration: Plugin installation loading screen

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#87392]
**Note: This should be behind the `onboarding/new-migration-flow` flag.**

More context: paYKcK-41n-p2

Similar to Woo Express, we want to have a loading screen which is presented to the user while the site is being moved to Atomic and the migration plugin is installed.

Once complete, we'll redirect the user https://github.com/Automattic/wp-calypso/issues/87393 so they can continue with the migration.

**Comment by sixhours** [comment]
I hesitated to close this out because we don't have a working flow yet to confirm #87499 works as intended. Leaving open for now.

**Comment by markbiek** [comment]
I'm hoping that we'll be able to use the processing step to cover all of this!

**Comment by sixhours** [comment]
I think we've covered this with the BundleTransfer step, no?

**Comment by markbiek** [comment]
> I think we've covered this with the BundleTransfer step, no?

Yes! This is safe to close.
