### ISSUE TITLE
Site Migration: Post-migration cleanup

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#87394]
We're not sure exactly what will be needed but there will be some cleanup that needs to happen after a site is migrated. This may be reconciling user accounts and/or ensuring Jetpack is properly connected.

We'll want to reach out to some of the folks in Happiness to see what kinds of things we may need to automate.

**Note: This should be behind the `onboarding/new-migration-flow` flag.**

More context: paYKcK-41n-p2

**Comment by markbiek** [comment]
Noting that @andres-blanco is going to write up an initial P2 to start the conversation with Happiness about this.

**Comment by andres-blanco** [comment]
I have some notes on this. I am going to gather them all and put a P2 together so we have a starting point.

**Comment by andres-blanco** [comment]
notes here: paYKcK-4b7-p2

**Comment by andres-blanco** [comment]
API to track status added here: D140803-code

**Comment by daledupreez** [comment]
Summary of actions we want is in paYKcK-4b7-p2#comment-3199

* Activate the Jetpack plugin if it is not active
* Reconnect Jetpack
* We should enable the classic interface for these sites so they are wp-admin-first. We can do that by setting the `wpcom_admin_interface` option to `'wp-admin'`
* We should ensure that the site is public and/or launched, which requires us to make an API call to WPCOM, which in turn will depend on Jetpack being connected. (It’s possible that some of this will also be resolved when Jetpack Sync kicks in.)
* Ensure that the site owner has a user on the site with the same email address (this was not specified in the post)

**Comment by daledupreez** [comment]
Note that we should also review the existing post-migration cleanup for additional possible actions, as well as implementation for tasks we want: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Serfgncv%2Qfvgr%2Qzvtengvba%2Qznantre.cuc%3Se%3Qp96q8189-og

**Comment by valterlorran** [comment]
Closing this as we deployed D143586-code
