### ISSUE TITLE
Signup: Theme step has horizontal scrollbar in Firefox

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#8745]
The theme step in signup has an unnecessary horizontal scrollbar in Firefox:
<img width="1438" alt="screen shot 2016-10-14 at 14 48 02" src="https://cloud.githubusercontent.com/assets/275961/19389877/9b5dd256-921d-11e6-9e69-8fed51aec3fa.png">
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/start
2. Go to the theme step
3. Scroll right
#### Browser / OS version

Firefox 49, OSX 10.12

**Comment by michaeldcain** [comment]
Confirmed in Chrome (56, OSX 10.12) too.

![screen shot 2017-02-09 at 11 03 08 am](https://cloud.githubusercontent.com/assets/942359/22791449/6634ddbc-eeb7-11e6-8be9-770584d1a6e5.png)

**Comment by bisko** [comment]
Fixed in #11299
