### ISSUE TITLE
Signup: Survey v2 "other" field doesn't submit with enter key.

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#8747]
#### Steps to reproduce
1. Starting at URL: wpcalypso.wordpress.com/start/
2. Set the `signupSurveyStep` AB test to the `surveyStepV2` variant. (can also be done with `localStorage.setItem('ABTests','{"signupSurveyStep":"surveyStepV2"}')` in the console and a refresh)
3. Select the "other" option from the Signup survey
4. Fill in a value and try to submit using the "enter" key.
#### What I expected

The field should submit and the step should advance.
#### What happened instead

Nothing.
#### Browser / OS version

Chrome/Mac OS X 10.11
#### Screenshot / Video

![screen shot 2016-10-14 at 10 34 00 am](https://cloud.githubusercontent.com/assets/942359/19391333/1fc5bd52-91fa-11e6-8b6e-a9b31640900c.png)
![screen shot 2016-10-14 at 10 34 07 am](https://cloud.githubusercontent.com/assets/942359/19391337/26b6ef5a-91fa-11e6-8d09-c53c1353a878.png)

**Comment by coreh** [comment]
#8651 addresses this. Once it lands, we'll replace the ad-hoc setup in this step with the component, since it has the enter key behavior.

**Comment by bisko** [comment]
Proposed fix in #10404

**Comment by michaeldcain** [comment]
Fixed in #10404.
