### ISSUE TITLE
Like block: Likes formatting broken on RTL sites when the block is displayed in small containers

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#87486]
![Image](https://github.com/Automattic/wp-calypso/assets/25105483/47750270-524f-478f-99e9-eebccc952fed)

**Comment by ivan-ottinger** [comment]
The cause of the issue is that the RTL styling hasn't been updated to get the latest LTR styling:

![Image](https://github.com/Automattic/wp-calypso/assets/25105483/b40a9225-e772-49cd-8c06-411a18df5ac6)

**Comment by ivan-ottinger** [comment]
Fix (D151357-code) is now in review.

**Comment by JuanLucha** [comment]
Reviewed and landed 👍
