### ISSUE TITLE
Developer Website: Add developer tab to support search

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#87482]
### Details

Context: https://github.com/Automattic/wp-calypso/issues/87462#issue-2134639935

Add developer website to the searches in Jetpack search in Support sites (it will also appear in /learn and /forums`)

![image](https://github.com/Automattic/wp-calypso/assets/52076348/3fde58a8-d6b6-44a8-bef0-f487bc5f742f)

To accomplish this, we should work on fbhepr%2Skers%2Sjcpbz%2Qn8p%2Qgurzrf%2Sjcfhccbeg3%2Sshapgvbaf.cuc%3Se%3Q5p1o51s5%23513-og, that handles the tabs of the search, and add the developer website.

**Comment by agrullon95** [comment]
Diff to add `developer.wordpress.com` to JP search: D138577-code
