### ISSUE TITLE
Site Migration: Install plugin

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#87498]
Once the site is transferred to Atomic, we want to run commands to install the plugin on the Atomic site.

Originally, we had planned to add the plugin to the list of symlinked plugins but this doesn't appear to be necessary.

Context: p1707998964494139-slack-C0Q664T29

**Comment by daledupreez** [comment]
I am not sure if we need the plugin to be symlinked -- I think we should get a sense for whether a non-symlinked install is that slow. I think we will also need to wait for a full release of the plugin before we can request this in any case.

**Comment by markbiek** [comment]
> I am not sure if we need the plugin to be symlinked -- I think we should get a sense for whether a non-symlinked install is that slow. I think we will also need to wait for a full release of the plugin before we can request this in any case.

@andres-blanco and I were worried about generating too much traffic by full installing the plugin on each site. But we can go either way with this.

And the issue has a note that we're waiting to have the final version of the plugin we're using before making any requests.

**Comment by markbiek** [comment]
Noting where site software sets are defined: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Qi2.cuc%3Se%3Q287467q2%231184-og

**Comment by markbiek** [comment]
Software set implementation: D138564-code

Next step is to make a call to install the software from the Stepper flow.

**Comment by daledupreez** [comment]
@markbiek, from a technical perspective, might it not be simpler to just request a plugin install on the site via the Jetpack API? This should be doable by making an API call to `POST /sites/%s/plugins/%s/install`.

**Comment by markbiek** [comment]
> @markbiek, from a technical perspective, might it not be simpler to just request a plugin install on the site via the Jetpack API? This should be doable by making an API call to `POST /sites/%s/plugins/%s/install`.

I wasn't aware of that endpoint but it definitely seems simpler. I'll investigate switching what I have over to using that endpoint instead. Thanks!

**Comment by markbiek** [comment]
Just confirming that `/sites/%s/plugins/%s/install` worked great! I'll close that diff with the software set.

@andres-blanco FYI ☝️

**Comment by markbiek** [comment]
Noting that I've got plugin installation working but am having trouble activating it.

Discussion here: p1708362256286349-slack-C0Q664T29

**Comment by markbiek** [comment]
I'm reopening this because I think we need to tweak it a little bit once we have the Atomic transfer step. We either need to switch the plugin-install step to use `setPendingAction` _or_ switch back to using a software set.

I'm leaning towards the software set at the moment so that we can use the `BundleTransfer` step for both the AT transfer and plugin install.

**Comment by markbiek** [comment]
Software set diff: D138564-code

**Comment by markbiek** [comment]
This is done.

**Comment by markbiek** [comment]
Due to issues with Trial plans, we've decided it'll be simpler after all to do the plugin install in its own step.

Reopening to tackle that.
