### ISSUE TITLE
Activating Jetpack VaultPress Backup results in Jetpack connection error

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#87493]
### Quick summary

When a user activates Jetpack VaultPress Backup on their non-Atomic ( Creator plan ) site, the Backup page reports that Jetpack connection has failed. It appears to happen every single time when a site goas AT from the backup page. 

In reality, the Jetpack connection is good as per JP debugger and the other pages are also accessible without issues. It appears the "Jetpack connection has failed" error is actually incorrect.  

This leaves a very poor impression on a user who is excited to start build their website. I hear that this is a temporary connection issue and should resolve itself.  While there may be technical reasons for this, an error message is definitely not the best way to welcome a brand-new user looking to build on WordPress.com

The user is also unable to get rid of the error without intervention from HE. Clicking on "Reconnect Jetpack" just takes to Site's Settings page.

Screen recording: 

https://github.com/Automattic/wp-calypso/assets/33957570/3a49bc3d-d2e5-44e8-a015-538286cbca96

### Steps to reproduce

1. Create a site
2. Purchase Creator plan 
3. Before installing any plugins or theme, while the site is still non-AT, go to Jetpack  Backups.
4. Activate Jetpack VaultPress Backup
5. Observe the Jetpack connection failing.. successfully

In reality, the Jetpack connection is good as per JP debugger and access to other Jetpack pages as seen in the screen recording. 

<img width="949" alt="image" src="https://github.com/Automattic/wp-calypso/assets/33957570/a04d320f-3570-4298-b448-71b7780c81dc">
 

### What you expected to happen

Jetpack connection to not fail

### What actually happened

Jetpack connection failed. 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Chat: 7732457-zd-a8c

**Comment by Nic-Sevic** [comment]
existing report here: https://github.com/Automattic/wp-calypso/issues/50687

**Comment by liviopv** [comment]
7766945-zd-a8c

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated / Could Not Replicate / Uncertain
- Tested on Atomic – Replicated / Could Not Replicate / Uncertain
- Tested on P2 (optional) – Replicated / Could Not Replicate / Uncertain
- Replicable outside of Dotcom – Yes/No

📌 FINDINGS/SCREENSHOTS/VIDEO
Include any additional details or steps to reproduce.
Attach screenshots or videos.

📌 ACTIONS
- Closed as duplicate https://github.com/Automattic/wp-calypso/issues/50687
