### ISSUE TITLE
Use my own server with Wordpress

### ISSUE THREAD

**Issue by elav** [Automattic/wp-calypso#875]
Hey, you can modify Calypso to connect to my VPS and use my Wordpress blog? 
If it is possible what should I change?

Thanks

**Comment by jeherve** [comment]
You don't need to make any changes to Calypso to use it to manage your own self-hosted WordPress site.

To connect the 2, install the Jetpack plugin on your site by going to Plugins > Add New in your dashboard, then connect the plugin to WordPress.com by clicking on the green connect button that will appear in your dashboard and enable the Manage Module in Jetpack > Settings.

You can read more about this plugin here:
http://jetpack.me/

If you run into issues or have questions, you can contact the Jetpack support team here:
http://jetpack.me/contact-support/
