### ISSUE TITLE
Block themes: Product archive/catalog not shown on homepage when it's set as the Woo shop page

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#87502]
### Quick summary

Originally reported in https://github.com/Automattic/theme-thriving-artist/issues/3 for the Thriving Artist (and Twenty Twenty-Two) themes. Initial user report: 7292190-zd-a8c

Also reported in 7710429-zd-a8c on the Creatio 2 theme, and I can replicate on a test site of my own with the Hevor and Attar themes.

With non-block themes, you can set the site's homepage (at Settings > Reading or in the Customizer) to the same page as the Woo "Shop page" (from Woo > Settings > Products). Doing so means that your product catalog/archive is displayed on the site's homepage below any content added directly to the homepage in the editor.

On at least these block themes (and likely others), doing the same does not work. Instead, the homepage uses its default/previously assigned page template (e.g. _Pages_) and displays only content added directly to the editor for that page/template. The product archive/catalog remains visible at a separate URL (e.g. `/shop`) using the _Product Catalog_ template. 

There was some suspicion that this was because of an existing _Front Page_ template, but I have replicated this behavior on sites _without_ that template present.

### Steps to reproduce

1. Start with a site with WooCommerce installed, active, and set up.
2. Activate a non-block theme (e.g. Twenty Twenty-One).
3. Add some content to the "Shop" page (page slug: `/shop`, created by Woo).
4. Ensure this "Shop" page is set as your site's homepage (Settings > Reading, or Customizer > Homepage Settings) _and_ the Woo "shop page" (Woo > Settings > Products).
5. View the site's homepage. Content added in the editor appears at the top, followed by the default product archive underneath.
6. Visit the `/shop` URL. The content (and even the `<body>` tag's classes) should be exactly the same.
7. Change the site's theme to a block theme.
8. Re-publish the "Shop" page, and ensure it's set as the site's homepage again (Settings > Reading). Woo's "shop page" setting should not have changed, so it should still be set there as well.
9. View the site's homepage. See that only the content added to the "Shop" page is present (likely using the _Pages_ template).
10. Visit the `/shop` URL. See that only the default product archive (i.e. the _Product Catalog_ template content) is present.

### What you expected to happen

With the homepage and Woo shop page set to the same page, the site's homepage and the `/shop` URL should display the same. On non-block themes, homepage content is shown first, followed by the default product archive. On block themes, I suspect the expected behavior is to only show the contents of the _Product Catalog_ template (and ignore any content added directly to the homepage unless a Content block is present there).

### What actually happened

Despite being set to the same page, the homepage and Woo shop page show different contents. For a store where the intent is to just display the default product catalog on the homepage, the result is a blank homepage despite having set the homepage to be the Woo "shop page."

Videos and screenshots below are from my test site.

Homepage appearance on Twenty Twenty-One: 

https://github.com/Automattic/wp-calypso/assets/5630717/25dc40b7-2042-4813-96cd-b0608dfaccf8

Below is the homepage and then the `/shop` page on Attar, after re-publishing the "Shop" page and setting it as the homepage again at Settings > Reading. (I've added `This is the Pages template` and `This is the Product Catalog template` directly to the respective templates for quick identification of which template is being used.) Note that the homepage uses the _Pages_ template and shows only the page's content, despite being set as the Woo "shop page."

https://github.com/Automattic/wp-calypso/assets/5630717/dd7ce961-284c-4191-a063-81e73ca834a3

Homepage setting: 
![3H5gVi.png](https://github.com/Automattic/wp-calypso/assets/5630717/c50d5546-01ae-4720-a027-2b9b23b4914c)

"Shop page" setting:
![rwz7Qj.png](https://github.com/Automattic/wp-calypso/assets/5630717/4cb322f5-88ec-4df7-abeb-3f7f3a756814)

No _Front Page_ template present (templates sorted alphabetically):
![XMyt3E.png](https://github.com/Automattic/wp-calypso/assets/5630717/d82f3a62-ba2b-4a0c-9265-5ea5d3b8cd2e)

It's also not possible to change the template for the "Shop" page in the page editor since it's set as the Woo "shop page" (and I assume it should be default to using the _Product Catalog_ template). 

![xTTorO.png](https://github.com/Automattic/wp-calypso/assets/5630717/bdd463eb-515b-43f5-aaea-d686e2c3f086)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Two main workarounds:

1. Add the contents of the _Product Catalog_ template (i.e. the desired homepage shop content) to the homepage itself. **Note:** Some Woo blocks (such as breadcrumbs or sorting filters) do not work outside of templates, so they cannot be used with this workaround.
2. Create a custom page template specifically for the homepage or a _Front Page_ template to override the homepage's default/previously set template.

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Atomic: Replicated 
– Replicable outside of Dotcom: Yes


📌 FINDINGS

Replicated exactly as described but I suspect this is expected given how Block Themes assign the template to the Homepage. The Shop template just won't apply to the Homepage.


📌 ACTIONS

Keeping the report and pinging @annezazu.

Sorry for the ping Anne, but I wonder if you can help me understand if my understanding is correct.

I'm wondering if we should treat this as a feature request in Core. 🤔

**Comment by annezazu** [comment]
I think this is less about Core and more about the intent behind what Woo wants to do. I'd flag this for folks working there as a next step (I'll drop it in their channel).

**Comment by gigitux** [comment]
@albarin (thanks for your great investigation) discovered that `the current_theme_supports( 'woocommerce' )` in [this line](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-query.php#L379) returns false only for the TT4 theme.
Other TTx themes have a dedicated file in the WooCommerce Core codebase to mark them as compatibility: https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/includes/theme-support.

Also, TT4 is not included in the wc_is_wp_default_theme_active here: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php#L2379.


The issue happens because the `current_theme_supports('woocommerce')` returns false in the case of TT4:

- https://github.com/woocommerce/woocommerce/blob/7fe00de7278cbc0d7806e1733b8df7320feef933/plugins/woocommerce/includes/class-wc-query.php/#L359-L360
- https://github.com/woocommerce/woocommerce/blob/7fe00de7278cbc0d7806e1733b8df7320feef933/plugins/woocommerce/includes/class-wc-query.php/#L379-L380



The issue is caused by WooCommerce. For this reason, I'm moving this issue to the WooCommerce repo!

**Comment by gigitux** [comment]
> For this reason, I'm moving this issue to the WooCommerce repo!

It looks like that is not possible; I will create a dedicated issue manually!
