### ISSUE TITLE
Move Newsletter Categories to Jetpack: new category creation endpoint

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#87561]
On the Newsletter setting page, there is the **Newsletter categories** section. There you can find a "

![Image](https://github.com/Automattic/wp-calypso/assets/3832570/359738e7-368c-4c68-820c-5d01f7c2137d)

As part of the effort to untangle calypso from wp-admin, we should recreate this section on Jetpack Newsletter setting page:
https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/_inc/client/newsletter/index.jsx

This task aims to just add an endpoint to create a new category to the Jetpack API.

**Comment by mashikag** [comment]
Not needed anymore as per p1HpG7-rd9-p2#comment-70059
