### ISSUE TITLE
Stats: Extend the post summary page with a UTM component

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#87574]
If there is anything left from the initial #87565 task related to the post summary page display, it should be addressed here; otherwise, the issue could be used to verify the summary page works and looks good.

**Comment by a8ck3n** [comment]
The module was added to the page as part of this PR:

https://github.com/Automattic/wp-calypso/pull/87705

Just needs to be updated with real data via the API now.
