### ISSUE TITLE
CPT: don't show hidden post type taxonomies in editor sidebar

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#8757]
#### What happened

I noticed on a self-hosted Jetpack site running o2 plugin + P2 theme that it shows the taxonomy for P2 x-posts post type in the Calypso editor. That should be hidden away from authors.
#### Steps to reproduce
1. Enable o2 plugin and P2 theme.
2. Create a new post, or edit a post. URL example: https://wpcalypso.wordpress.com/post/example.com (self-hosted WordPress)
3. Look in editor sidebar underneath "Categories & Tags" and you'll see a new section called "Xposts".
#### What I expected

Not to see "Xposts" taxonomy in the sidebar.
#### Screenshot / Video

<img width="383" alt="screen shot 2016-10-14 at 10 24 13" src="https://cloud.githubusercontent.com/assets/66797/19396584/a88db48e-91f8-11e6-8f56-a6305ed4324c.png">
#### Context / Source
# dogfooding

**Comment by aduth** [comment]
At a glance, this is partly a Calypso problem that we don't properly account for the public flags of a taxonomy (though I seem to recall addressing this specific case, so I might have to do some further digging). To be clear, the [`xposts` taxonomy is public](https://github.com/Automattic/o2/blob/830d61e967b7f1789f492ae8552d73f547a2a42d/inc/xposts.php#L240-L245) ([true by default](https://codex.wordpress.org/Function_Reference/register_taxonomy)), though it specifies flags when registering to not have its UI rendered. Our REST API does not currently expose these specific flags, rather only the `public` property of a taxonomy. Enhancements may be necessary to the REST API to reflect the intended UI.

Related: r134334-wpcom

**Comment by lancewillett** [comment]
Closed #10428 as a duplicate

See also #700 and #701

**Comment by lancewillett** [comment]
This is fixed now. See https://github.com/Automattic/wp-calypso/pull/10620 and https://github.com/Automattic/jetpack/pull/5487

<img width="391" alt="screen shot 2017-01-20 at 08 27 14" src="https://cloud.githubusercontent.com/assets/66797/22154856/698332a2-deea-11e6-8aad-7dae3efcfe17.png">

**Comment by aduth** [comment]
#10620 is specific to custom post types, not taxonomies. I need to verify, but I think there's still work to be done to consider `show_ui` flags for custom taxonomies.

**Comment by aduth** [comment]
This is still an issue, if a post type is public but has non-public taxonomies associated with it. Changes similar to those in https://github.com/Automattic/jetpack/pull/5487 (specifically the keys to include) will need to be applied to the taxonomies endpoint and accounted for in the Calypso UI.

**Comment by lancewillett** [comment]
Closing as I haven't seen this again during regular use on Jetpack sites or WP.com sites. If it reappears or is unfinished, feel free to reopen.
