### ISSUE TITLE
Stats: Add an empty state for UTM metric

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#87581]
<img width="763" alt="截圖 2024-03-04 上午12 34 07" src="https://github.com/Automattic/wp-calypso/assets/6869813/13106862-ab37-4589-af60-fd89b99b7d71">

**Comment by dognose24** [comment]
This task has been tackled in the PR of introducing the UTM module. https://github.com/Automattic/wp-calypso/pull/87593
