### ISSUE TITLE
VideoPress: embed flashes a wider size in iOS Safari before resizing to correct width

### ISSUE THREAD

**Issue by isocialtish** [Automattic/wp-calypso#87586]
### Quick summary

On Mobile a VideoPress embed that is vertical will flash a larger size and then resize to fit the screen

### Steps to reproduce

1. In mobile, log in to your WordPress.com site using Safari and/or Chrome
2. Open a page or post (new, or draft, or already published)
3. Insert a VideoPress block and vertical video
4. Click Save, or Preview or Publish
5. View Page on Mobile.

### What you expected to happen

The video will display correct width from the start

### What actually happened

The video flashed a larger width in the beginning, before resizing to correct width

Screenshot:

https://github.com/Automattic/wp-calypso/assets/6664819/d7dd8fac-01fb-41a7-958a-25a0e51ea31a

#user-report
Ticket: 7730845-ZD

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by phcp** [comment]
Closing this issue as the error isn't reproducible anymore. Tested on iOS (real device and simulator) using Safari. See the video below:
https://github.com/user-attachments/assets/63b6ad26-72ac-4595-9787-4c726503bb6f
