### ISSUE TITLE
Site Migration: Plan upgrade step

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#87605]
The existing Import flow steps are tied too closely to current migration process. It's going to be simpler to create lightweight steps to use in the migration flow.

In this case, we need a step for the user to upgrade their plan in the event that they didn't pick a plugin-enabled plan initially.

If the user does have a valid plan, this step will simply submit itself and move on to the next step.

![image](https://github.com/Automattic/wp-calypso/assets/917632/530a6157-beaf-4a60-b85d-c1211b75dfee)

**Comment by markbiek** [comment]
@andres-blanco I'm not sure if we want to transfer the site to Atomic with this step or if that should happen separately.

**Comment by andres-blanco** [comment]
I should happen after that for sure, so once this step is submitted successfully we can start moving the site
