### ISSUE TITLE
Implement WooCommerce NUX passwordless login screen

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wp-calypso#87630]
### Issue description

- Project thread: pdibGW-2FU-p2
- Figma: 4ixWMlzrxllx93tSFsCW6k-fi-9483_7912

Related 
- https://github.com/Automattic/wp-calypso/issues/87636

Implementing a passwordless login flow for Woo Express. Existing users can log in to their accounts using the magic link.

Passwordless users

<img width="750px" alt="03  Social login" src="https://github.com/Automattic/wp-calypso/assets/4344253/e445762c-0858-404c-954d-9698f655a8aa">

For users who sign up before the passwordless signup was implemented

<img width="750px" alt="03  Social login - Password" src="https://github.com/Automattic/wp-calypso/assets/4344253/550c2a36-d0f7-4c9a-aa22-73972384b2ab">

### Acceptance criteria

- [ ] When the feature flag is enabled (https://github.com/Automattic/wp-calypso/issues/87635), a new passwordless login UI should be displayed
- [ ] Implement the passwordless feature

```
Given the user has a passwordless account
	and is logged out
	and is on the Woo Express site creation flow, 
When user enter their email address
	and clicks on "Continue with email"
Then a magic link will be sent to their email address
When user clicks on the magic link
Then 
    if 2FA is not enabled, they will be logged in automatically
	if 2FA is enabled, they will be prompted to complete 2FA
	and they will be redirected back to the Woo Express site creation flow


Given the user has a non-passwordless account
	and is logged out
	and is on the Woo Express site creation flow, 
When user continues with email
Then a password field will be shown
When user enters the correct password
	and completes 2FA (if enabled)
Then they will be logged in
	and they will be redirected back to the Woo Express site creation flow
```

Note: a8c accounts are not allowed to use magic link login

**Comment by rjchow** [comment]
There's a little bit more work here compared to https://github.com/Automattic/wp-calypso/issues/87627 , there's some oddity with `accountType` that modifies what the button does and whether a magic link email is sent. I didn't fully explore this but noted the above complications.

**Comment by chihsuan** [comment]
@rjchow FYI, I've opened a PR for sign-up screen changes here: https://github.com/Automattic/wp-calypso/pull/87976. You might update on login screen based on the changes in the PR to avoid conflicts. 😬
