### ISSUE TITLE
Authorize account screen circle background doesn't follow color scheme

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#87638]
### Issue description

The circle icon container in Core profiler's Jetpack authorization screen does not respect user preference color scheme.

![Image](https://github.com/Automattic/wp-calypso/assets/3747241/cbeda8e8-b430-4519-94ae-ae3ea33dbd0c)

Seemingly, the [`--wp-admin-theme-color--rgb`](https://github.com/Automattic/wp-calypso/blob/a987c59543dde89f4f4b0d453ac8b9815e902c16/client/jetpack-connect/style.scss#L1304) variable does not respect user's color preference.

#### To reproduce

1. Go To https://wordpress.com/me/account
2. In `Dashboard color scheme`, select a non-default color scheme such as `Sunrise`
3. In a fresh JN site with WooCommerce installed, go to Setup Wizard
4. Go through all steps and observe in the connection screen, the color of circle background does not follow color scheme preference.

### Acceptance criteria

1. Ideally, `--wp-admin-theme-color--rgb` should follow user preferred color scheme. Otherwise, find an alternative to ensure the circle background color inherits user preference color scheme.

**Comment by adrianduffell** [comment]
@ilyasfoo, it looks like wordpress.com no longer provides an account-level color scheme choice. Is it still possible to reproduce this?

![Image](https://github.com/user-attachments/assets/58e2c597-a227-44ff-bb0e-23dfc61e9f84)

**Comment by ilyasfoo** [comment]
Good catch, @adrianduffell! I can't reproduce this anymore
