### ISSUE TITLE
Site Migration: Add 'disable-migration-emails' toggle under stickers in BlogRC

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#87659]
### Context
For cases where HEs are assisting users with migration (examples — pc4ICr-1QN-p2 , pc4ICr-1Z6-p2) we want to prevent the automated emails about migration success/failure from being sent to the users. Such emails would only confuse users as HEs may need to make various migration attempts using both Everything import tool and Move to WordPress.com plugin.

### Solution
Add a new toggle 'disable-migration-emails' toggle under stickers in BlogRC. When toggled on, it would prevent any migration-related emails from being sent to the user for a given site. HEs would toggle it on for the duration of the migration assistance and toggle back off (which would be the default state.

### How
@Automattic/caribou shared how this can be implemented here p1708439319591939/1708438168.083239-slack-C01A60HCGUA

**Comment by vishnugopal** [comment]
Done with 2 diffs: D139089-code and D139091-code

![CleanShot 2024-02-21 at 17 18 32](https://github.com/Automattic/wp-calypso/assets/533/d1a6d19d-6c5d-49b5-a07c-2520d37a7f7b)

We used destination address as that's unlikely to change even with the new migration flow coming up: paYKcK-3UF-p2

**Comment by zdenys** [comment]
@daledupreez Can you please confirm if this toggle has any effect if Migrate Guru is used? AFAIK it only stops emails generated by Everything import tool and Move to WordPress.com plugin.

**Comment by daledupreez** [comment]
@zdenys, apologies for the delay: yes, I can confirm that this toggle does not have any effect on Migrate Guru migrations at present. We're not sending any specific emails from our mail system when these migrations finish.
