### ISSUE TITLE
Newsletter Settings in JP: animation when enabling newsletter categories

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#87662]
When clicking on the "enable newsletter categories" checkbox, the rest of the options should appear with an animation, as per the Figma design: p1HpG7-rd9-p2

**Comment by phcp** [comment]
This issue could also include the show/hide of the dropdown component, as it wasn't implemented as part of the component creation.

**Comment by phcp** [comment]
@JuanLucha are you planning to work on this one? We still need to handle this show/hide in order to finish the UI. Please let me know in case you don't have bandwidth so we can take this over if needed.
