### ISSUE TITLE
Global Sidebar - update elements for a11y focus styles

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#87673]
We introduced a11y focus outline in https://github.com/Automattic/wp-calypso/pull/87669 

There are a number of elements that will need their borders and positioning adjusted for the a11y focus to fit design and styles from the prototype.

- [ ] WordPress.com logo - make rounded
![Screenshot 2024-02-20 at 1 51 28 PM](https://github.com/Automattic/wp-calypso/assets/28742426/d5f64fd7-7afe-4f84-9c3e-aee293f2f521)

- [ ] Search button - make rounded
- [ ] notifications button - make rounded
![Screenshot 2024-02-20 at 1 51 37 PM](https://github.com/Automattic/wp-calypso/assets/28742426/80422bc5-452c-4113-86ce-6215f1e893ca)

- [ ] first navigation item - remove cutoff
![Screenshot 2024-02-20 at 1 51 45 PM](https://github.com/Automattic/wp-calypso/assets/28742426/be4d95dc-5f13-4407-88ed-54e5278c8fbb)
![Screenshot 2024-02-20 at 1 52 01 PM](https://github.com/Automattic/wp-calypso/assets/28742426/995e536a-9ed4-4530-9369-2fface1cbc9e)

- [ ] footer items - make rounded
![Screenshot 2024-02-20 at 1 52 24 PM](https://github.com/Automattic/wp-calypso/assets/28742426/41273203-c0d5-4204-9088-a33e8de4bb3c)

**Comment by Addison-Stavlo** [comment]
@nuriapenya - @davemart-in and I were wondering your take on the above a11y focus styles. We added in the base styles where they are square by default, and I was creating this issue to update the corresponding elements styles to be more rounded so they will fit the a11y styles of the prototype. Some thoughts from Dave:

>  Can you ask Núria Peña what she suggests?
Maybe square is fine?
I'm probably getting too fancy.
I just realized that I don't think any other focus styles are rounded on Dotcom.

If the pics above arent enough, you could compare whats currently in production with the `flags=layout/dotcom-nav-redesign`  (basic squared outlines) to the v4 prototype https://wpcomnav4.web.app/ (rounded).  Im fine either way: I think the rounded styles look better but the square are a bit more consistent with what is currently across dotcom and wp-admin.

**Comment by nuriapenya** [comment]
Heya! As a general rule, I'd say to mimic as much as possible the FSE, which is our baseline for design. In this case, they go for rounded outlines everywhere:

<img width="390" alt="screen 2024-02-21 at 12 03 50" src="https://github.com/Automattic/wp-calypso/assets/7931304/a1f19ed7-6751-44a6-863a-95c0860729dc">
<img width="359" alt="screen 2024-02-21 at 12 04 28" src="https://github.com/Automattic/wp-calypso/assets/7931304/4802d4d2-f972-4551-aa61-1056900af3e7">

So, if possible, could we do the same? 🙏🏽

**Comment by Addison-Stavlo** [comment]
Ok, thanks! So slightly rounded edges but not completely circular as in the prototype. 👍

**Comment by nuriapenya** [comment]
Yeah, to be specific, FSE uses a 2px radius - let's do the same.

I will update the Figma files accordingly and @davemart-in, maybe if you have the chance also the prototype? 🙏🏽 so we make sure everything is aligned.

**Comment by davemart-in** [comment]
No prob. @nuriapenya https://wpcomnav4.web.app/ is now updated. 👍

**Comment by Addison-Stavlo** [comment]
@davemart-in @nuriapenya - note that since we also removed the gap between menu items, some of the a11y outline gets cut off. This is what im seeing in the prototype:

![Screenshot 2024-02-21 at 8 47 20 AM](https://github.com/Automattic/wp-calypso/assets/28742426/8ad738af-06a9-4bb0-8b8b-90f13eb6e4f4)

design could go a few ways here, some thoughts:
* we could make the outline more inset on the elements (decrease outline-offset), but we would have to change the outline color **when on the selected item** since both item and outline are the same blue.
* leave the offset, but change the outline color on everything to something that contrasts both selected/unselected menu item states (white?)

I assume we may want to decrease the offset given the FSE comparison, but would still need to make some color choices. 🤔

**Comment by davemart-in** [comment]
Just noting that FSE appears to have the same issue:

<img width="353" alt="CleanShot 2024-02-21 at 09 06 07@2x" src="https://github.com/Automattic/wp-calypso/assets/5634774/23ef9868-22f3-4272-b7f5-689380b933ef">

**Comment by Addison-Stavlo** [comment]
> Just noting that FSE appears to have the same issue:

fair enough! I think our outline in production might have a little more offset and width do it currently (both 2px value), if thats something we want to reduce to match FSE better.

**Comment by Addison-Stavlo** [comment]
handled in https://github.com/Automattic/wp-calypso/pull/87721
