### ISSUE TITLE
Stats: UTM summary page

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#87687]
Verify if we need a UTM summary page (this is a different page from the post summary page), and if we do, make sure it contains all the necessary elements.

**Comment by a8ck3n** [comment]
This was added as part of #87593. Still needs live API data and testing that the period controls work correctly. Alternatively, we could remove the period controls.

**Comment by grzegorz-cp** [comment]
We need to fix the period navigation in the header and check if CSV download works and if we should include it.

**Comment by a8ck3n** [comment]
This is currently blocked pending updates to the API queries. Once they are updated to accept the query parameters, we can wire things up on this page. — https://github.com/Automattic/wp-calypso/pull/88475#pullrequestreview-1936527423

In the meantime, I'll look into how the CSV download works.

**Comment by a8ck3n** [comment]
Download button for CSV export is ready to merge. Two follow-up tasks of note here:

1. Better default file name for CSV file.
2. Guard against double quotes in labels before quoting them.

Both the above are from feedback in #88619.

**Comment by a8ck3n** [comment]
Summary page should be fully functional now. Closing this issue.
