### ISSUE TITLE
[Continue with GitHub] Handle case where user does not accept permissions

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#87701]
Currently it redirects to https://public-api.wordpress.com/wpcom/v2/hosting/github/account-verification?error_description=The%2Buser%2Bhas%2Bdenied%2Byour%2Bapplication%2Baccess.&error_uri=https%253A%252F%252Fdocs.github.com%252Fapps%252Fmanaging-oauth-apps%252Ftroubleshooting-authorization-request-errors%252F%2523access-denied

**Comment by mashikag** [comment]
Is this issue addressing a user who tries to signup with GitHub for a new account, or a user who already has a WPCOM account but is trying to connect his GitHub account, or both?

**Comment by TimBroddin** [comment]
It could be both. Whenever the user's current scope doesn't match the requested scope, or if GitHub detects a lot of logins, the authorization dialog is shown. It could happen in the three scenarios: login, sign up & connect an account.

**Comment by mashikag** [comment]
Ok, so it breaks down to two main flows:
1. User is logged in when that happens.
2. User is logged out when that happens. 

### Logged In User
They were trying to connect their account but received the error.
We could redirect them back to the `/me/secuirty/social-logins` page and display them with the error.

### Logged Out User
They were either trying to login, or signin using GitHub, but the process failed. Perhaps we could point them to some default login/signup page, or create a specific logged out page for GH users who failed to use their GH account for login/signin? 

We could even combine this solution with what you propose in: p1708588469059389-slack-C02TCEHP3HA. 

Does it makes sense what I wrote above? Or am I missing something?

**Comment by ivan-ottinger** [comment]
Addressed in https://github.com/Automattic/wp-calypso/pull/88346. → Closing the task.
