### ISSUE TITLE
Suggestion: Use Immutables .withMutations for better performance.

### ISSUE THREAD

**Issue by spentay** [Automattic/wp-calypso#8773]
Hi All! 😃

While I've been browsing around the code-base I've spotted a few areas where Immutable's change methods (.set, .update, etc) are chained to make changes to various state properties.
The issue with chaining them is that each method computes and returns a new data representation - each change in a chain adds computation overhead that can usually be avoided.

I suggest we address these and either try to avoid setting values for the same key multiple times ([I've seen a couple of examples of this](https://github.com/Automattic/wp-calypso/blob/fc8f1537f6df3905b37bb1e706ef5d132fcee1b4/client/state/themes/themes/reducer.js#L39
)) or use Immutable's .withMutations method to apply multiple changes in one fell swoop.

[Here's another example](https://github.com/Automattic/wp-calypso/blob/fc8f1537f6df3905b37bb1e706ef5d132fcee1b4/client/state/themes/themes-last-query/reducer.js#L29) that would be quite simple to fix yet would avoid the creation of 2 extra Maps.

My only hesitation with making these updates would be that the addition of .withMutations is slightly less straight forward that just chaining .set(...).set(...) etc. in terms of readability.

If you guys think this is a good move, I'd be more than happy to have a hack at the areas that I've come across already :)

**Comment by ockham** [comment]
Hi @spentay, and good spot! Although I'm the one who migrated our previous Flux-based themes stores to Redux (and Immutable.js), I'm clearly not that well-versed with Immutable and wasn't aware of `.withMutations`.

The thing is, the themes redux subtree suffers from a number of architectural shortcomings which I'm in the process of fixing (#8785), so I wouldn't want you to waste your time cleaning up our Immutable usage when most of this is going away soon.

Anyway, thanks a lot for your contribution -- I hope you're not too disappointed!

**Comment by ockham** [comment]
(Closing, since I've merged #8777, and because of my previous comment.)

**Comment by spentay** [comment]
Many thanks @ockham :D
I'll hold off on making other .withMutations updates for now - It makes sense not to optimise something that's fleeting!
