### ISSUE TITLE
View filter doesn't show all the options on the Theme Showcase page

### ISSUE THREAD

**Issue by Agepeuve** [Automattic/wp-calypso#87745]
### Quick summary

If you go directly to https://wordpress.com/themes/yoursiteURL, you'll notice that you can't filter the themes by plan using the drop-down menu next to the theme search bar.

You can refresh it and make it work the way it should by selecting any subject or searching for anything.

### Steps to reproduce

1. Go to https://wordpress.com/themes/yoursiteURL
2. Click on the drop-down menu at the top of the page, next to the search bar.

### What you expected to happen

You should see the plan filters:

![All filters](https://pruebasdedominioag.blog/wp-content/uploads/2024/02/Markup-2024-02-22-at-02.39.28.png)

### What actually happened

You will only be able to select "All".

![Broken filter](https://pruebasdedominioag.blog/wp-content/uploads/2024/02/Markup-on-2024-02-22-at-023319.png)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Tested with different accounts/devices and using different browsers (Chrome 121.0.6167.184, Firefox 122.0.1).

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate 

## 📌 ACTIONS ##
- Closed as could not replicate (please reopen if the issue reoccurs) 

##Message to author##
Thanks so much for the report. I couldn't replicate the issue with the same steps. Are you still able to produce this on a number of sites? Feel free to reopen if you can still replicate.
