### ISSUE TITLE
Storage Add-Ons: Storage add-on selector remains interactive despite plan not purchasable

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#87767]
## What happens

Go to `/plans/[ site not owned ]` and you will likely see: 

1. The storage add-on selector is interactive despite the respective plan not being purchasable. 
2. Selecting different storage add-ons will not reflect the price of the plan either

![Image](https://github.com/Automattic/wp-calypso/assets/1705499/5d73f295-db15-4b26-852a-648acdadd244)

## What I expected to happen

1. Storage add-on selectors not being interactive at all. It's completely redundant if nothing happens. 
2. The plan's storage value displayed in a badge instead, as done for the rest.

**Comment by briowill** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/88756
