### ISSUE TITLE
Custom HTML block with googlemaps embed does not display map when added to a template

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#87784]
### Quick summary

Following guide for [Embed From Google Maps](https://wordpress.com/support/google-maps/), when added to a Page Template in an FSE theme such as `Assembler`, the map does not display and only the shortcode text displays. 

User report: 7779609-zd-a8c

### Steps to reproduce

1. Create new Simple site with Assembler theme
2. Edit the Pages template and Embed a Google Map and save the template
3. Check a Page on the front end using the default Pages template and see the map is not displayed, but only the shortcode text: ![uLt8uj.png](https://github.com/Automattic/wp-calypso/assets/121042930/9a91d2fb-6e5f-4888-9eca-1afa2911574a)

### What you expected to happen

The Google map should display

### What actually happened

Only shortcode text is displayed

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

This was tested on a Simple site only with Assembler theme. Adding the shortcode directly to a Page instead of a Template works.

**Comment by rickmgithub** [comment]
Could be related to https://github.com/Automattic/wp-calypso/issues/87911

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Replicated as per OP instructions

**Comment by isocialtish** [comment]
A customer report here: #7944005-hc

**Comment by syhussaini** [comment]
Another report here 8085725-zen

**Comment by devNigel** [comment]
Another case: 8212437-zd-a8c

**Comment by mdtanjid0** [comment]
8212437-zen ( needs to be followed up)

**Comment by janmckell** [comment]
Another case: 8340778-zd-a8c
Shared workaround, seen [here](https://github.com/Automattic/wp-calypso/issues/87911), which works when I tested it on one of my test sites.

**Comment by caitlindawn** [comment]
Another case: 8347647-zen
Provided workaround

**Comment by CodeAllNightNDay** [comment]
This seems like it's a wider spread issue for other short codes in FSE templates.
This user is unable to get the privacy short code for WordAds to display in a Single Post template using the Zoologist theme. I don't have any WordAds enabled sites to test, but the workaround is the same here, expect the short code needs to be added to each post rather than the Single Post template.
8570902-zen

**Comment by arthur791004** [comment]
Confirmed that it doesn't work in the template but do work in the post/page.

**Comment by arthur791004** [comment]
Follow the instruction here, p7DVsv-hsr-p2, the workaround is to convert the googlemaps embed into a template part so it can display correctly on the content of the template.

**Comment by arthur791004** [comment]
Asked p1725969458829019-slack-C4EUDHL80

**Comment by rinazrina** [comment]
Encountered in 9321025-zd-a8c and 9327030-zd-a8c. 
I shared the workaround -- converting the Googlemaps embed into a template part.

**Comment by le-sgs** [comment]
9496090-zd-a8c adding here.

**Comment by susanjanec** [comment]
Encountered in 9534892-zd-a8c and will share the workaround to convert the embed into a template part.
