### ISSUE TITLE
Stats: Replace support doc links for Odyssey Stats

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#87802]
When there's no stats for stats cards, in most cases, we show a link to support docs. We are only linking to dotcom support at the moment, including Odyssey Stats.

Our awesome Jetpack HEs helped created Jetpack versions of the documentation, and now we'll be able to replace them for Odyssey Stats.

![image](https://github.com/Automattic/wp-calypso/assets/1425433/fd6579e4-6839-4051-8a47-531379ea12e7)

**Jetpack docs:**
- https://jetpack.com/support/jetpack-stats/traffic-dashboard/
- https://jetpack.com/support/jetpack-videopress/add-video-block-editor/video-stats/
- https://jetpack.com/support/jetpack-stats/insights-dashboard/

cc @jos22 @foleynotrose

**Comment by grzegorz-cp** [comment]
@jos22 I noticed that two headings are missing an `id` and I can't link directly to a specific section. The first one is also missing from the sidebar links on the documentation page. 
Would you be able to add the following?

- "countries" id for `Views by country`
- "tags-categories" id for `Tags & categories` on the insights page docs
