### ISSUE TITLE
Reader: Paid Subscribers See Incorrect Content and A Message That They Need to Upgrade

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#87811]
## Issue
Posts gated to paying newsletter subscribers are displaying incorrectly in the Reader.

Paying subscribers still get the preview/gated version, and a message asking them to upgrade.

## Details
Subscription management confirms I have a paid subscription to the site:
<img width="300px" src="https://github.com/Automattic/wp-calypso/assets/42279181/2ac1e665-7a85-4531-9e01-c2432443adb9">

But I see this on every post in the Reader:
<img width="600px" src="https://github.com/Automattic/wp-calypso/assets/42279181/6c139ffc-8133-4f91-8376-57cdf6ab2054">

**Comment by katiebethbrown** [comment]
cc: @Automattic/zap @Automattic/gold

**Comment by katiebethbrown** [comment]
I'm wondering if there could be some kind of caching at play here, because the issue below has numerous reports of the opposite behavior, where the paid content shows in the Reader to non-paying customers:

- https://github.com/Automattic/wp-calypso/issues/44554

**Comment by katiebethbrown** [comment]
cc @Automattic/loop

**Comment by davemart-in** [comment]
With our team transferring into Build, we're not currently focused on the reader at all. @simison curious if this is something your team might be able to look into since it's related to paid subscribers?

**Comment by simison** [comment]
I am pretty sure this was a bug that got sorted several months ago already so seems like something re-triggered it.

@Automattic/gold know what's going on here?

**Comment by millerf** [comment]
I am not sure about the Reader issue.

For the rest, I don't think my team touched much on this. However I wonder if @Automattic/zap tinkering with the cookies in those PRs could be the issue:
https://github.com/Automattic/jetpack/pull/35849
https://github.com/Automattic/jetpack/pull/35852

**Comment by pkuliga** [comment]
> However I wonder if @Automattic/zap tinkering with the cookies in those PRs could be the issue, as the dates seem to match:
https://github.com/Automattic/jetpack/pull/35849
https://github.com/Automattic/jetpack/pull/35852

Hi @millerf, not sure what you mean by that. The first PR you mentioned is not even merged and the second one is just preventing the HTTP 301 redirection which has nothing to do with cookies...

**Comment by katiebethbrown** [comment]
> Can you try again? I wonder if this is due to some desync in JP/Atomic vs WPCOM codebase...

@millerf - I tested again this morning and I'm still getting the free/gated content in the Reader as a paying subscriber.

Clicking on the `upgrade` button in the Reader takes me to the post on the site, where I can see the content in full without issue.

**Comment by millerf** [comment]
> Hi @millerf, not sure what you mean by that. The first PR you mentioned is not even merged and the second one is just preventing the HTTP 301 redirection which has nothing to do with cookies...


@pkuliga  Yes, sorry. I noticed it afterwards. I thought the first PR was merged. I removed my comment too late.


> @millerf - I tested again this morning and I'm still getting the free/gated content in the Reader as a paying subscriber.

@katiebethbrown Thanks for testing. I'll investigate now.

**Comment by chrismccluskey** [comment]
I have a fix for this at D139775-code

**Comment by millerf** [comment]
> I have a fix for this at D139775-code

@chrismccluskey Looking at the fix, how has this ever worked before?

**Comment by millerf** [comment]
@katiebethbrown @simison @davemart-in 

It looks like Reader has never supported paywalled content coming from Jetpack sites.

For the record, @Automattic/gold has never been involved with the Reader, and we were never made aware of this.

**Comment by millerf** [comment]
> I have a fix for this at D139775-code

I'll let @Automattic/loop review it. I don't know enough about Reader.

**Comment by millerf** [comment]
@davemart-in Would you mind to have you or your team review D139775-code ? You have the best knowledge about it.

**Comment by davemart-in** [comment]
@millerf our team is no longer working on Reader. To my knowledge, there is no team currently working on Reader.

**Comment by davemart-in** [comment]
Sorry, I just saw this message come through after my other reply:

> @davemart-in Would you mind to have you or your team review D139775-code? You have the best knowledge about it.

@millerf sure! @Addison-Stavlo, @eoigal, @roo2 would one of you mind reviewing this when you have time?

**Comment by liviopv** [comment]
📌 ACTIONS
- Marking this as Triaged considering there's already a PR in place and two different teams involved. Switching Priority to High considering it's not actively blocking paying customers from seeing gated content *outside* of the Reader.

**Comment by chrismccluskey** [comment]
The fix I have created isn't going to work. See p3btAN-2D0-p2#comment-20298 for more details.

**Comment by millerf** [comment]
@chrismccluskey You should be able to rely on constants introduced in https://github.com/Automattic/jetpack/pull/36254 to prevent that issue.

**Comment by chrismccluskey** [comment]
Deployed D139775-code

**Comment by chrismccluskey** [comment]
Reverted D139775-code and will be making a follow-up patch soon. Context: p1710527966085279-slack-C02ECE3ML

**Comment by chrismccluskey** [comment]
New fix: D142166-code

**Comment by chrismccluskey** [comment]
Deployed D142166-code

**Comment by millerf** [comment]
@chrismccluskey I had to revert it (see slack comment: p1710836162494899/1710527966.085279-slack-C02ECE3ML)
It's a tricky one...

It looks like $feed_item is sometimes not a WP_Post. Maybe checking for that would be enough...metimes

**Comment by chrismccluskey** [comment]
> I had to revert it.

Thanks for catching that! This PR should resolve the issue: D142489-code

**Comment by chrismccluskey** [comment]
Auto-closed when I merged the Jetpack PR, but there is still one PR to merge.

**Comment by chrismccluskey** [comment]
Will deploy WPCOM PR when latest Jetpack change is deployed to WPCOM.

**Comment by chrismccluskey** [comment]
Deployed. I've got alerts setup for errors and I'm not seeing any.
