### ISSUE TITLE
Newsletters: "Manage your email settings or unsubscribe" link redirects to invalid URL

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#87825]
### Quick summary

The hyperlink to "Manage your email settings or unsubscribe" in New Post email notifications has a broken redirect. 

In the email, the linked URL is `https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https%3A%2F%2Fsubscribe.wordpress.com%2F%3Fkey%3Df03148e51803e6c8c577bfecc562b91d%26email%3Dliviopv%2540gmail.com%26b%3DPIvBEAi-dYCmr6F3jXY4npZSbx1a3C_ryuJmHYGFWPqzGRQtdGrE3KZdzfs9wjlaUUA39nvCPiy7nnrUO7paxXSCURRpe8GR20YLdcSj0uXBrTzaUATOzIRGHdI8qLQjZegc3ONmB7B0cMWxBwb4nrigbvpGLNnmgA%253D%253D%26oneclickunsubscribe%3Dtrue&sr=1&signature=8e6cab4c8f99c3b28939cc2b9cd552aa&user=113469066&_e=eyJlcnJvciI6bnVsbCwiYmxvZ19pZCI6MTMwNDE2NDk0LCJibG9nX2xhbmciOiJlbiIsInNpdGVfaWRfbGFiZWwiOiJqZXRwYWNrIiwiaGFzX2ZlYXR1cmVkX2ltYWdlIjoiMCIsInN1YnNjcmliZXJfaWQiOiIyNDYyMjc0MCIsIl91aSI6MTEzNDY5MDY2LCJsb2NhbGUiOiJlbiIsImN1cnJlbmN5IjoiQlJMIiwiY291bnRyeV9jb2RlX3NpZ251cCI6IkJSIiwic2lnbnVwX2Zsb3dfbmFtZSI6IiIsImVtYWlsX2RvbWFpbiI6ImdtYWlsLmNvbSIsInBvc3RfaWQiOjEwOTgsInVzZXJfZW1haWwiOiJsaXZpb3B2QGdtYWlsLmNvbSIsImRhdGVfc2VudCI6IjIwMjQtMDItMjMiLCJlbWFpbF9pZCI6ImM4ZDU1YWNiNjA5OTcyODBlZGE4YTFhZmE4YTMzN2Q3IiwiZW1haWxfbmFtZSI6Im5ldy1wb3N0IiwidGVtcGxhdGUiOiJuZXctcG9zdCIsImxpbmtfZGVzYyI6Im1hbmFnZS1zdWJzY3JpcHRpb24iLCJhbmNob3JfdGV4dCI6Ik1hbmFnZSIsIl9kciI6bnVsbCwiX2RsIjoiXC94bWxycGMucGhwP3N5bmM9MSZjb2RlYz1kZWZsYXRlLWpzb24tYXJyYXkmdGltZXN0YW1wPTE3MDg2ODU5MjQuNTg0JnF1ZXVlPXN5bmMmY2Q9MC4wMDEyJnBkPTAuMDAyMSZxdWV1ZV9zaXplPTUmYnVmZmVyX2lkPTY1ZDg3YTY0OGRkMzA5LjYyNDUzNTUzJnN5bmNfZmxvd190eXBlPWRlZGljYXRlZCZzdG9yYWdlX3R5cGU9Y3VzdG9tJnRpbWVvdXQ9MjAmaG9tZT1odHRwcyUzQSUyRiUyRmF0bGl2aW8ud3Bjb21zdGFnaW5nLmNvbSZzaXRldXJsPWh0dHBzJTNBJTJGJTJGYXRsaXZpby53cGNvbXN0YWdpbmcuY29tJmlkYz0xJmZvcj1qZXRwYWNrJndwY29tX2Jsb2dfaWQ9MTMwNDE2NDk0IiwiX3V0Ijoid3Bjb206dXNlcl9pZCIsIl91bCI6ImFrYWxpdmlvcHYiLCJfZW4iOiJ3cGNvbV9lbWFpbF9jbGljayIsIl90cyI6MTcwODY4NTkyOTA0NCwiYnJvd3Nlcl90eXBlIjoicGhwLWFnZW50IiwiX2F1YSI6IndwY29tLXRyYWNrcy1jbGllbnQtdjAuMyIsImJsb2dfdHoiOiIwIiwidXNlcl9sYW5nIjoiZW4ifQ=&_z=z` which ends up redirecting to https://wordpress.com/read/site/subscription/invalid.

https://github.com/Automattic/wp-calypso/assets/14153300/eea1d787-6578-4dd9-808a-5e789562c137

### Steps to reproduce

1. Subscribe new post notifications on a WordPress.com site
2. Create a new post on the site
3. Open the email for the new post
4. Click on "Manage your email settings or unsubscribe"

### What you expected to happen

The link should go to https://wordpress.com/read/subscriptions with the options to manage settings for that specific site open

### What actually happened

The link redirects to https://wordpress.com/read/site/subscription/invalid

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by liviopv** [comment]
7783447-zd-a8c

**Comment by liviopv** [comment]
📌 ACTIONS
- Triaged
Escalation thread: p1708686711882169-slack-C02FMH4G8

**Comment by jp-imagines** [comment]
I believe there's another report of this in 7858946-zd-a8c, though specific details haven't been shared yet.

**Comment by jp-imagines** [comment]
Another potential report in 7852589-zd-a8c.

**Comment by BrookeDot** [comment]
Related is https://github.com/Automattic/jetpack/issues/36504 in the Jetpack repo.

**Comment by ckoerner** [comment]
We're experiencing the same issue on a site I help manage (diff.wikimedia.org) that uses this feature to manage email subscriptions. 

One thing to note from my testing. When I click the "manage" link in the email, it does appear to unsubscribe me! It's confusing as I see the "Subscription not found" message as shown in this ticket. 

When I go to https://wordpress.com/read/subscriptions I can see I'm now set to _not_ receive emails. Nor do I receive the next post that's published. I have to change my settings to then again receive emails.

**Comment by pkuliga** [comment]
Hi folks, a couple of hours ago we deployed a fix for it D142897-code. Could you check if it fixed the issue for you?

The fix will work only with emails sent after the fix was applied. This link still won’t work for older emails, unfortunately.

**Comment by ckoerner** [comment]
I quickly tested this with an email sent after the fix was applied. I can confirm that in my limited testing I am now directed to the appropriate page on Wordpress.com to manage my subscription!

<img width="1343" alt="Screenshot 2024-03-25 at 4 11 37 PM" src="https://github.com/Automattic/wp-calypso/assets/232862/35769b9a-1c57-414f-8bb2-785bbf00917c">

**Comment by liviopv** [comment]
I can no longer reproduce, closing as fixed.

**Comment by cat-og** [comment]
User reported having this same issue again here: 8326211-zd-a8c, and I was able to replicate this with my own subscriptions. Re-opening this issue.

**Comment by liviopv** [comment]
@cat-og I tested this again today and I wasn't able to reproduce - the "Manage your email settings or unsubscribe" links in all emails I tested worked fine and correctly redirected me to the Subscription Management screen:

https://github.com/Automattic/wp-calypso/assets/14153300/6bca60d4-f9f1-4b0f-a7f7-b1fc1a488571

@pkuliga can take a look at Cat's report above to see if this is a cause that the fix you deployed in March didn't catch?

**Comment by simison** [comment]
We've improved resilience of these links recently, and just last week @lezama and @enejb worked out some quirks. @lezama safe to close now?

**Comment by candy02058912** [comment]
I can't reproduce the issue on my end, sharing the same experience as mentioned by @liviopv in https://github.com/Automattic/wp-calypso/issues/87825#issuecomment-2178356545.
We're addressing clear next steps for all blocker/high-priority issues on The One Board (pb5gDS-3YO-p2).
For this issue, I'll be closing it unless it can be reproduced again.
cc: @Automattic/zap @cat-og
