### ISSUE TITLE
DevDocs: Several components missing titles in IE11

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#8782]
#### Steps to reproduce
1. Using IE11: https://wpcalypso.wordpress.com/devdocs/design
2. Scroll down to look for Tooltip, Popover, and Refresh Cards (on /devdocs/blocks)
#### What I expected

To see the components listed like the others
#### What happened instead

The components themselves appear fine, but they're missing their titles.  This was originally mentioned [here](https://github.com/Automattic/wp-calypso/issues/8329#issuecomment-250838691), but since it's now happening on the RefreshCards component too I wanted to make a standalone issue to track it.

The generated header element looks like this:

``` html
<h2 class="docs-example__wrapper-header">
    <a class="docs-example__wrapper-header-title" href="./design/undefined"></a>
</h2>
```

That anchor element above is what the visual diff tests key off of to load each element individually, so all of these problem components are loading as "Undefined" with an empty page

cc: @retrofox @bluefuton 
#### Browser / OS version

Windows 7 IE11
#### Screenshot / Video

<img width="577" alt="screen shot 2016-09-30 at 3 45 22 pm" src="https://cloud.githubusercontent.com/assets/7233112/19005179/2698929a-8727-11e6-9569-78c4ecd81a36.png">
<img width="301" alt="screen shot 2016-09-30 at 3 44 59 pm" src="https://cloud.githubusercontent.com/assets/7233112/19005178/269422c8-8727-11e6-93ce-4570c523c18a.png">
<img width="673" alt="screen shot 2016-10-17 at 9 24 45 am" src="https://cloud.githubusercontent.com/assets/7233112/19439865/b5803a70-944d-11e6-9b5f-f61f5c97172c.png">
#### Context / Source
# automated-testing #visdiff

**Comment by hoverduck** [comment]
The new Reader Subscription List Item block also fails to show up on IE11

https://wpcalypso.wordpress.com/devdocs/blocks/reader-subscription-list-item?debug=true

**Comment by bluefuton** [comment]
This is still an issue.
