### ISSUE TITLE
Help Center: Add dev sticker to articles in search

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#87824]
Context: pdt2If-17D-p2#comment-806

Add a dev label to the dev docs ( fetched from developer.wordpress.com ) in the Help Center to distinguish them from the general docs, communicating that they’re aimed at an advanced audience.

( to get an article from developer, try searching for `OAuth`

<img width="492" alt="image" src="https://github.com/Automattic/wp-calypso/assets/52076348/ef673d56-ed6f-4743-8dec-d676f908d12c">

**Comment by renancarvalho** [comment]
Addressed here https://github.com/Automattic/wp-calypso/pull/87838
