### ISSUE TITLE
Question: Post Listing Not Showing Various Statuses

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#8783]
Whilst doing a bit of dog fooding this weekend, I noticed that the post listing in Calypso doesn't show counts for all `status` in the nav bar like we do in wp-admin, screen grabs are from the same site:

**Calypso**
<img width="736" alt="blog_posts_ _conepatrol_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/22080/19443262/0e558c5c-9441-11e6-8721-581cb58e643a.png">

**WP-ADMIN**
<img width="313" alt="posts_ _conepatrol_ _wordpress" src="https://cloud.githubusercontent.com/assets/22080/19443246/fee5359c-9440-11e6-9a64-bbf3158f2def.png">

In CPT listings, we expose a bit more, but still do not show the "Private" count like wp-admin does, instead we add them to "Published"

**Calypso CPT**
<img width="735" alt="projects_ _testingtimmy2_wordpress_com_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/22080/19443409/7910bee0-9441-11e6-9df2-c0b5a0be3e31.png">

**WP-ADMIN CPT**
<img width="478" alt="projects_ _ _wordpress" src="https://cloud.githubusercontent.com/assets/22080/19443425/8fc8aa76-9441-11e6-825c-a2964c411832.png">

I can't seem to remember why we grouped Private into Published on CPT's ( /cc @aduth ) but the difference on the post listing page is quite large compared to wp-admin.  At the very least it seems the count groupings shown should match on all post listings within calypso.

/cc @mtias for any info on the background of post listing.

**Comment by aduth** [comment]
It's intentional to group `draft,pending` as "drafts" and `private,publish` as "published":

https://github.com/Automattic/wp-calypso/blob/121b381/client/lib/route/path.js#L111-L130

**Comment by timmyc** [comment]
Ah that is correct - I seemed to vaguely remember seeing that in a review - was there a reason why we chose that vs breaking private out on its own?

**Comment by aduth** [comment]
If I were to guess, for simplicity's sake, since both are technically published, and similarly a pending post could be perceived as a draft.

**Comment by mtias** [comment]
Yes, we condensed statuses that represent similar flows — same reason why we simplified the status selector into chunks of functionality in the editor (revert to draft, visibility, etc).

The overall idea for future iterations was to do more engaging things with each filter view — sticky posts could be shown at the top, scheduled posts in a calendar, etc.
