### ISSUE TITLE
Jetpack Cloud: wp-admin opens in a new tab

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#87884]
On cloud.jetpack.com, it opens wp-admin in a new tab. Do we want this?

Context: pfsHM7-fU-p2

We're concerned that linking wp-admin to cloud.jetpack.com, and then back to wp-admin, could repeatedly open new tabs.

**Comment by jeherve** [comment]
Moving this to the Calypso repo, where the Jetpack Cloud interface is being developed.
