### ISSUE TITLE
Feature Request: Site Analyser tool for HEs (similar to Site Profiler)

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/wp-calypso#87899]
### What

Happiness Engineers are currently using a variety of 3rd party sites to help them analyze a user’s site. HEs use these 3rd party sites to be able to determine what CMS the user is using, info about the theme as well as plugins.

### Why

At the moment we are using third party tools for this and driving traffic there. If we have in-house solution it will help us just like in case of Site Profiler that we have.

### How

I don't have the answer to this :) but happy to discuss options. Slack discussion: > p1708716192675369 - slack-C01A60HCGUA

**Comment by inaikem** [comment]
Closing in favour of 6542-gh-Automattic/dotcom-forge. This is being worked on as we speak as an update to the current Site Profiler.

For the moment, Any A12 can use stored details for the tool mentioned in `6542-gh-Automattic/dotcom-forge#issuecomment-2056538056`.
