### ISSUE TITLE
Site Migration: Update Import vs Migration step

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#87905]
We want to update the step we implemented in #87731. The functionality of the step will remain the same but we want to add copy showing the benefits of migrating over importing.

It may be easiest to have lists of features side-by-side kind of like we do on the plans page.

![CleanShot 2024-02-26 at 11 55 36](https://github.com/Automattic/wp-calypso/assets/917632/fc285fa2-d887-4fb8-bc11-3d94589ccd39)

This step will still to the existing Import flow if they choose not to migrate. 

If they choose to migrate, they will either go to upgrade their plan and then the Atomic transfer step (#87906) or straight to the AT transfer step (if their plan doesn't need upgrading).

**Comment by gabrielcaires** [comment]
it is duplicated with the issue #88189

**Comment by gabrielcaires** [comment]
Closed with https://github.com/Automattic/wp-calypso/issues/88189
