### ISSUE TITLE
Refreshed Fullpost Design Idea: New "visit site" link

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8791]
Currently, on the Refreshed Fullpost, the post title and date stamp link to the original post.

I'd like to suggest adding a new link to the original post at the top, right.

![visit-site](https://cloud.githubusercontent.com/assets/24388/19450742/77ff0dcc-945f-11e6-80fa-497e87be2351.png)

Design details: the link matches the same type treatment as the "BACK" link, and is on the same baseline. The color of the icon matches the color of the back arrow. The idea is to mirror that functionality, so the left side is back to the stream, and the right side is forward to the post.

Why do this? The links on the title and datestamp are not obvious. This change would make it obvious how to get to the parent blog if the user wants to see the post in context. Now that we're showing the full text on fullpost, some are complaining. Giving users a clear way to get to the parent blog might assuage a bit of that concern. After all, we want to give people an obvious way to get to the parent blog if that's what they want to do.

Thoughts @jancavan?

**Comment by jancavan** [comment]
@fraying 

This would link to the home page of their site instead of the post itself, correct? I think that'd help, although its location may be easy to miss on wider screens, but we can give it a shot. We should also add an event to this to see how often people click it.

How do you envision it on mobile? This may feel cramped, but maybe just the external link icon next to the Like icon? Another idea is an external link icon right after the post title.

**Comment by fraying** [comment]
@jancavan No - this would link to the permalink page. The same URL linked from the title and datestamp now. (I know "VISIT SITE" makes it sound like the homepage, but I needed a word to make it clear that what you'd be visiting is the parent site.)

And: I love the idea of tracking clicks on this.

As for mobile, you think there's space to put it on the right side in the top bar, to keep it on the same line as "BACK"? Maybe shorten it to "VISIT"?

**Comment by fraying** [comment]
Rough sketch of mobile version, just to communicate the idea:

![visit-site-mobile](https://cloud.githubusercontent.com/assets/24388/19458518/70a19bea-9481-11e6-8e73-77b91e8cce1f.png)

**Comment by jancavan** [comment]
It's going to be really tight at `<480px` especially if the Comments/Likes are 3-digits. Not very common...
![screenshot 2016-10-17 16 18 04](https://cloud.githubusercontent.com/assets/4924246/19459097/93d17a6e-9485-11e6-99ec-c8c9c883d369.png)

...but even with 2-digits.
![screenshot 2016-10-17 16 20 50](https://cloud.githubusercontent.com/assets/4924246/19459117/b041237a-9485-11e6-8ac1-036e834bc7ad.png)

> Another idea is an external link icon right after the post title.

What did you think of this? Although it's making it look quite busy, but just an idea.
![screenshot-2016-10-17-16 20 50](https://cloud.githubusercontent.com/assets/4924246/19459207/2dc53872-9486-11e6-981b-2407795164aa.png)

**Comment by fraying** [comment]
I appreciate the suggestion, but I think it looks weird beside the headline. Like something in the page broke.

Alternate suggestion: We could drop the "BACK" and "VISIT" labels at the smallest view. Which would be consistent with how we've dropped "Comment" and "Like" here.

![alternatively](https://cloud.githubusercontent.com/assets/24388/19459774/8d554062-948a-11e6-908b-26fbf4e0f16f.png)

**Comment by jancavan** [comment]
That's better! Following may overlap with Comments if we consider i18n. Although I forget if full-post test is English only? But what about dropping Follow/Following labels on mobile?

**Comment by fraying** [comment]
We could to that, too!

**Comment by fraying** [comment]
Fullpost test is all users, not just English, FWIW.

**Comment by jancavan** [comment]
- [ ] Add "Visit Site" link
- [ ] Add Tracks event to this link

**Comment by blowery** [comment]
> Fullpost test is all users, not just English, FWIW.

Just checked, it's actually English only.
