### ISSUE TITLE
Add 'view.genially.com' to Embed Block

### ISSUE THREAD

**Issue by chekle** [Automattic/wp-calypso#87916]
### What

User is asking if 'view.genially.com' can be added to the Embed block, 'view.genial.ly' works well already but not 'view.genially.com'.

e.g. using the Embed Block: This URL works: [​https://view.genial.ly/57cea0e1c10e0c5c80245f3a](https://view.genial.ly/57cea0e1c10e0c5c80245f3a) 

![image](https://github.com/Automattic/wp-calypso/assets/8153800/193ba54b-f34a-4605-a020-e8992695dc75)

This URL doesn't work: [​https://view.genially.com/57cea0e1c10e0c5c80245f3a](https://view.genially.com/57cea0e1c10e0c5c80245f3a)

![image](https://github.com/Automattic/wp-calypso/assets/8153800/aa5010bc-7f30-4310-93ce-ec0baa83e067)

### Why

User from https://genial.ly/ is asking if an update can be made to the Embed Block that allows for embeds from 'view.genially.com' to be allowed.

**Comment by kraftbj** [comment]
Apologies for the delay on the earlier request. Working on it in D139952-code and am planning on deploying it tomorrow US hours.

**Comment by chekle** [comment]
Thank you very much! I'll update the user :)

**Comment by kraftbj** [comment]
Deployed via r288670-wpcom and responded to the ticket regarding difficulty in accessing the site to confirm it is working as expected. Since it's a pretty harmless change, went ahead with the deploy as I wait to hear back.

**Comment by rickmgithub** [comment]
Looking at the ticket, the user hasn't replied for 2 days so marking as closed pending any changes to remove it from the queue.
