### ISSUE TITLE
wp-admin Command Palette: "Open WooCommerce settings" on Atomic sites without Woo

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#87937]
Follow-up of https://github.com/Automattic/wp-calypso/pull/87901.

For Atomic sites without a Woo Store, the "Open WooCommerce settings" command in WP Admin should link to the Woo installation entry point, just [like we do in Calypso](https://github.com/Automattic/wp-calypso/blob/48bbe440e5bb7a6411c78ced61e82032e45a96a7/client/sites-dashboard/components/wpcom-smp-commands.tsx#L1196-L1200).

**Comment by dsas** [comment]
The untanglers have said that this command should only appear if Woo is installed when using the classic interface. https://github.com/Automattic/dotcom-forge/issues/5733#issuecomment-1967911391

I think this is consistent with how the new navigation will behave.

**Comment by rcrdortiz** [comment]
The issue is now completed.
