### ISSUE TITLE
wp-admin Command Palette: "Get help" should open the Help Center

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#87933]
Follow-up of https://github.com/Automattic/wp-calypso/pull/87901.

Just like in Calypso, the "Get help" command should open the Help Center in WP Admin.

<img width="446" alt="Screenshot 2024-02-27 at 13 35 13" src="https://github.com/Automattic/wp-calypso/assets/1233880/1c531d9f-efb7-4419-ae34-63e9f2bdad06">

**Comment by rcrdortiz** [comment]
These changes are now live.
