### ISSUE TITLE
Command Palette in WP Admin: Open site dashboard does not open My Home

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#87934]
Follow-up of https://github.com/Automattic/wp-calypso/pull/87901.

Just like in Calypso, the "Open site dashboard" command should open the My Home page.

**Comment by rcrdortiz** [comment]
We've already had a conversation about this not being the case p1708947026164119-slack-C06DN6QQVAQ. I'm closing this issue.
