### ISSUE TITLE
wp-admin Command Palette: Check admin interface style

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#87943]
Follow-up of https://github.com/Automattic/wp-calypso/pull/87901.

To avoid a mistake we recently made by always forcing the WP Admin interface (see p7DVsv-jXA-p2), the command palette in WP Admin should check and redirect to the preferred admin interface (https://wordpress.com/support/dashboard/#set-the-admin-interface-style) for the following commands instead of always redirecting to WP Admin:
- Manage posts
- View media uploads
- Upload media
- Manage pages
- Manage comments
- Manage themes
- Install theme
- Manage plugins
- Install plugin
- Manage users
- Add new user
- Manage general settings
- Manage writing settings
- Manage reading settings
- Manage discussion settings

For reference, this is how we check the preferred interface in Calypso:

https://github.com/Automattic/wp-calypso/blob/fbbd52ec657736dfb967e6d29b6f493bcc4d0e36/client/sites-dashboard/utils.ts#L90-L102

**Comment by mmtr** [comment]
For the Add new post/page commands, I think it's fine if we always link to WP Admin, since the Calypso editor is just an iframe of the WP Admin editor, so users shouldn't feel confused about it. We can keep linking to Calypso instead if want though for consistency.

**Comment by rcrdortiz** [comment]
I don't think this should be an issue tbh. What you've linked is just a user report about not being able to switch to the default view. That's pretty much unrelated to the command palette. I think it would make more sense to not implement this and wait for user reports to come in.

**Comment by mmtr** [comment]
Re-opening after getting some clarification in p1709046751963829/1709044877.519909-slack-C04DZ8M0GHW

> we should always follow the users preferences unless it completely doesn’t make sense, e.g. if the command is “Do Foo” and the wp-admin version of that page doesn’t support doing Foo.
