### ISSUE TITLE
Site Migration: add live chat to migration flow

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#87944]
There should be a live chat button on the migration flow. Right now it will be default inactive since we still don't know the exact location. But we are pretty sure we are going to need one.

**UPDATE** details in this comment: p9Jlb4-bYZ-p2#comment-11574; we want to offer live chat/support on the migration instructions screen.

Context: pc4ICr-1ZC-p2

**Comment by valterlorran** [comment]
Hey @andres-blanco, are we going to use the `ChatButton` button component for this?

**Comment by valterlorran** [comment]
Update: We added the chat to the `/move` page: paYKcK-4dh-p2#comment-3207

**Comment by valterlorran** [comment]
It was also request to add the chat for logged-in users on the `/move` page. You can find more details about how we can implement this change here: paYKcK-4dh-p2#comment-3215

**Comment by sixhours** [comment]
Live chat has been added in https://github.com/Automattic/wp-calypso/issues/91639
