### ISSUE TITLE
Site Title block font size setting doesn't work when changing font family on Links under Global Styles

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#87986]
### Quick summary

When changing the font family on the Links setting under Global Styles to Lora font, the font size setting on the Site Title block does not work.

### Steps to reproduce

1. Activate Twenty Twenty-Four or TwentyTwenty-Three theme
2. Go to Appearance > Editor 
3. Click **Site Title** block and try to change the font size. It should be working normally.
4. Then go to **Global Styles** > **Typography** > **Links**
5. Change the font family to **Lora** 
6. Go back to Site Title block settings, and try changing the font size, see it works
7. If you save the changes, then there's no way to undo the font changes, and the issue persists even after we switch the font back to Default. 
8. When switching to a different theme, the issue is gone. But when switching back to the original theme (2024 or 2023), the issue persists. 

### What you expected to happen

The font size setting for the Site Title block should be working even if the Font Style is changed.

### What actually happened

The font size setting for the Site Title block is not working after changing the font style via Links setting. 

I demonstrated the steps to reproduce in the following video: 

https://github.com/Automattic/wp-calypso/assets/33721365/edacfd2b-450e-43c4-a77e-8ee2dbe8754e

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

While using Chrome, the issue was encountered when using Twenty Twenty-Four and Twenty Twenty-Three. However, this issue was not found while using the Creatio 2 theme, which has a drop-down font size setting. Not sure if that's related. 

User report: 7805723-zd-a8c

The workaround is switching to another theme or using CSS: 

.wp-block-site-title a {
    font-size: 30px;
}

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate 

##Message to author##
Thanks so much for the detailed report. I couldn't replicate the issue with the same set up. Are you still able to produce this on a number of sites? Feel free to reopen if you can still replicate.
