### ISSUE TITLE
The users are not able to complete the "Launch your site" task

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#88007]
The truth is that the site is launched by the time we get the design selection step on the **sell** flow. I suspect that the `launch-status` is being set directly for the flow instead of using `set_status_launched` function.

### Steps to reproduce it
* Create a site through the `/start` flow.
* On the Goals step, select sell.
* Go through the flow until you reach the Customer Home page.
* Click on the `Launch your site` task.
* It won't get marked as complete.

**Comment by nelsonec87** [comment]
https://github.com/Automattic/wp-calypso/assets/3801502/ebca0d44-59d7-4b35-a44c-28678ea31a10

@valterlorran , can you confirm you can still reproduce the issue?

**Comment by valterlorran** [comment]
@nelsonec87, thanks for testing it! I'm unsure if the behavior changed or if I wrote the testing instructions were missing some steps. But if you click on "Show site setup", you'll see the the "Launch your site" task incomplete, and won't be able to complete it.
![Captura de Tela 2024-04-10 às 09 28 47](https://github.com/Automattic/wp-calypso/assets/1234758/8eff4115-4710-4728-91f7-1c7c7760744e)

**Comment by nelsonec87** [comment]
There is a fix in this PR: https://github.com/Automattic/jetpack/pull/36839

The `launch_status` option is set to "launched" when the task is clicked, but the task is never marked as completed. The PR above adds logic to check the `launch_status` option to guide the task.
