### ISSUE TITLE
Theme Showcase - Extra Blank Column

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#8804]
On themes where content description is short and/or the full-site screenshot is long, some extra blank space is showing:

<img width="712" alt="screen shot 2016-10-18 at 17 23 12" src="https://cloud.githubusercontent.com/assets/15944096/19474138/e165c9d4-9560-11e6-904e-e696fe93ab2b.png">

Examples:
- https://wordpress.com/theme/penscratch
- https://wordpress.com/theme/intergalactic

Discussed on p1476782881003186-slack-hyperion

**Comment by aladwig06** [comment]
The minimum size for that div is set to 900px.  Reducing the minimum size fixes the problem.  I'll do some digging to see if there is a reason that it is set to 900px and to make sure it doesn't affect anything else.

**Comment by folletto** [comment]
Fixed in #8829 by @aladwig06.

Thanks!
