### ISSUE TITLE
Checkout: Move the site fragment to the last portion of the URL

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#8805]
We currently have checkout URLs like this:
`https://wordpress.com/checkout/:site/:product/`

The convention in Calypso is that the siteSlug goes at the end of the URL path, so we should move the `product` parameter before it.

In addition we also use this convention `theme:theme-name` to add a specific theme to the cart. This is a wrong convention. We should add `productMeta` to the URL.

**Comment by janm6k** [comment]
Going through old issues, closing ones that did not have any activity in long time.

Please feel free to reopen if applicable.
