### ISSUE TITLE
Help Center: Better ul margin

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#88074]
### Details

Context: pdDR7T-1nN-p2#comment-1622

ul elements have quite a big margin applied to them (3 em).

Maybe we could make it smaller (1.5 em looked good), since the horizontal space is already quite limited 

<img width="405" alt="image" src="https://github.com/Automattic/wp-calypso/assets/52076348/c7780f44-a7a8-4690-9c37-98c008a53be1">

**Comment by renancarvalho** [comment]
Fixed https://github.com/Automattic/wp-calypso/pull/88077
