### ISSUE TITLE
Site Migration: Remove software set

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#88079]
We need to remove the migration software set from wpcom. We'll be going back to a separate plugin install Stepper step (#87498).

The software set was added in D138564-code.

~Sometimes the software set required by the new Migration flow is not installed from the bundleTransfer step.~

~Some discussion here: p1709239239049149-slack-C7YPW6K40~
~And more context here: p1709236314212559/1709236131.505619-slack-C0Q664T29~

**Comment by markbiek** [comment]
I'm updating this issue to be about removing the software set since we're not going that route anymore.

Context: https://github.com/Automattic/wp-calypso/issues/87498#issuecomment-1973812331

**Comment by markbiek** [comment]
Removed in D140825-code

**Comment by retnonindya** [comment]
This GH issue is reported by a developer. 

📌 ACTIONS
Triaged

📌 Message to Author
@markbiek -- Just to check here, is this issue resolved now? Feel free to close this issue if needed. Thank you!

**Comment by markbiek** [comment]
> This GH issue is reported by a developer.
> 
> 📌 ACTIONS Triaged
> 
> 📌 Message to Author @markbiek -- Just to check here, is this issue resolved now? Feel free to close this issue if needed. Thank you!

@retnonindya I'll be landing the diff for this shortly and will close this issue once the change is deployed.
