### ISSUE TITLE
Gutenberg plugin - Hover color cannot be set to Site Title block

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#88107]
### Quick summary

The latest upgrade to Gutenberg caused an issue with the user site where the hover color set for the Site Title block in the template part Header does not "stick" to what it's set to. **Disabling the Gutenberg plugin resolves the issue.**

- Tested on atomic site (staging and public sites) with only "default WordPress.com" plugins active.
- Gutenberg plugin Version 17.8.0
- tested with Theme "Twenty Twenty Three"

Workaround: **Disabling the Gutenberg plugin resolves the issue.**

### Steps to reproduce

1. Start at site editor
2. Edit the Header template part
3. Site title - apply Hover color style
4. Test front end

### What you expected to happen

For the color set to apply on front end.

### What actually happened

The color is different.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

User report on 7825514-zen

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Could Not Replicate
– Tested on Atomic: Replicated
– Replicable outside of Dotcom: No


📌 FINDINGS

Repçocated as described on Atomic sites with Gutenberg active.

https://github.com/Automattic/wp-calypso/assets/2540430/33f5123e-a238-471a-8885-f125db163bba

With the Gutenberg plugin deactivated all works as expected:

https://github.com/Automattic/wp-calypso/assets/2540430/554c5801-bbed-48f5-9d64-bb2197ad462f



📌 ACTIONS
– Report kept. Marking as triaged.

**Comment by annezazu** [comment]
Hey hey! I can't replicate this:

https://github.com/user-attachments/assets/aa2d4538-0460-465d-aff4-222811e68be2

Nor could I find current Gutenberg repo reports of the problem. Closing this out as a result. Happy to reopen if folks can replicate.
