### ISSUE TITLE
Stats: UTM section on the support page

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#88117]
https://github.com/Automattic/wp-calypso/issues/87581 ensured that there an empty state for the module but it leads to #utm part of the support documentation but the documentation doesn't have such section. Either update the link or ensure that the documentation is being updated.

**Comment by kangzj** [comment]
Hi @jos22 👋 Are you able to help on this one please? Thanks! 👍

**Comment by jos22** [comment]
Sure @kangzj. Will take a look at this over the weekend 👍.

**Comment by jos22** [comment]
@kangzj @grzegorz-cp, we can update the current link to the Jetpack.com resource here: [jetpack.com/support/jetpack-stats/traffic-dashboard/#utm-stats](https://jetpack.com/support/jetpack-stats/traffic-dashboard/#utm-stats). It's currently set to a WordPress.com support stub.

**Comment by dognose24** [comment]
The support document link on Calypso and Odyssey Stats has been updated. D143079-code
