### ISSUE TITLE
Help Center: Upgrade dev docs icon

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#88126]
Context: pdDR7T-1nN-p2#comment-1629

### Details

Current state of dev docs in the Help Center:

![image](https://github.com/Automattic/wp-calypso/assets/52076348/ff161205-bc9f-4176-9e89-e63cb87cf7e2)

What we want: 

![image](https://github.com/Automattic/wp-calypso/assets/52076348/b54bfd23-44ca-4073-8445-50b4dbe3e51f)

**Comment by renancarvalho** [comment]
Done here https://github.com/Automattic/wp-calypso/pull/88131
