### ISSUE TITLE
Link color not used after toggling "inner blocks use content width"

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#88158]
### Quick summary

Initial report: 7836286-zd-a8c (issue replicated on a test site afterward).

Tested with a couple themes (Attar & Twenty Twenty-Three) and with different blocks (Cover, Group, Products (Beta) > Product template, Query Loop > Post Template). It's sometimes bit tricky to reproduce naturally (depending on the block used), but in my tests, the block code for container blocks contains either `"layout":{"type":"constrained"}` or `"layout":{"type":"default"}` property which corresponds to the **Inner blocks use content width** setting. Whenever that property exists, custom link colors applied to contained blocks show up in the editor but *not* on the live site. 

### Steps to reproduce

1. Start with a site with Twenty Twenty-Three active.
2. Create a new page.
3. Insert a Query Loop block. Select the "Start blank" option, then "Title & date."
4. Click on a post's title to select the Title block. In the settings sidebar, enable "Make title a link." In the block's style settings, set a custom text color (which should automatically apply as the link color as well).
5. Preview the page, and see the link colors match what was chosen in the editor.
6. In the editor, select the **Post Template** block. On the right, enable the "Inner blocks use content width" toggle. 
7. Preview changes, and see the link color has now changed.
8. In the editor again, disable the "Inner blocks use content width" toggle.
9. Preview changes, and see the link color has not changed back.

Note: This _can_ be replicated with other containers (e.g. Groups and Cover blocks), but you may need to use the Code Editor to remove the `"layout":{"type":"constrained"}` or `"layout":{"type":"default"}` property. I'm unsure if that property is always added to these blocks regardless of theme, and whether that has changed at any point in the past.

### What you expected to happen

Custom link colors applied should appear on the live site.

### What actually happened

The custom link color CSS is entirely missing from the affected links.

Compare the CSS styles applied to the example Query Loop links before toggling:

![correct link color styles](https://github.com/Automattic/wp-calypso/assets/5630717/c3fbe40f-fd5b-4632-850f-c7a559bb98ee)

vs. after, where `.wp-elements-{ID} a:where(:not(.wp-element-button))` is missing from the page's inline styles entirely:

![missing styles](https://github.com/Automattic/wp-calypso/assets/5630717/2499fdfe-c619-4f54-a0c3-0ba395e07817)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Only tested on Atomic so far.

Possible workarounds:

* Place affected blocks into a Group, and set a custom link color on the Group block. (Applies to all links within the Group.)
* (Possibly theme dependent) From Appearance > Editor > Styles > Blocks > Content block, set a preferred default link color. (Applies to all links within any post or page's content.)

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate 

## 📌 ACTIONS ##
- Author feedback
- Closed as could not replicate (please reopen if the issue reoccurs) 

##Message to author##
Thanks so much for the report. I couldn't replicate the issue with the same set up on Simple or Atomic. Are you still able to produce this on a number of sites? Feel free to reopen if you can still replicate.

**Comment by jp-imagines** [comment]
@rickmgithub I can't replicate anymore! I wonder if the latest Gutenberg release may have fixed this. 🤔 Thanks for taking a look regardless!
