### ISSUE TITLE
Fix failing Calypso E2E tests

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#88160]
Flipping the `layout/dotcom-nav-redesign` flag in production caused two e2e tests to fail in Calypso due to the new "All together now" modal interrupting the e2e test flow. I've muted those tests while we update them.

More info on those tests here: p1709590571214239-slack-C06DN6QQVAQ

**Comment by arthur791004** [comment]
I'll check this today 🙂

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/88169
