### ISSUE TITLE
Plans Next: Migrate assets/svgs imported in features-list to packages

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#88182]
### What

Part of addressing https://github.com/Automattic/wp-calypso/issues/79004

Migrate the following icons or images into a publicly accessible package:

- `SupportIcon`: from [client/assets/images/onboarding/support.svg](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/images/onboarding/support.svg).
- `Theme2Image`: from [client/assets/images/onboarding/theme-2.jpg](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/images/onboarding/theme-2.jpg). 
- `MaterialIcon`: from [client/components/material-icon](https://github.com/Automattic/wp-calypso/tree/trunk/client/components/material-icon). 

### Why

These are being imported into `lib/plans/features-list` which is being migrated to `@automattic/calypso-products` for importing and using outside of the Calypso environment.

### How

One idea would be to create a `@automattic/calypso-assets` package (or something of this nature) and initiate the package with migrating `SupportIcon` and `Theme2Image` there. Moving along, we could be migrating more things until the entirety of `/client/assets` migrates.

Other options:

- [SupportIcon](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/images/onboarding/support.svg): This could fit into `@automattic/components/icons`
- [Theme2Image](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/images/onboarding/theme-2.jpg): This is a jpg that's only used in `features-list`. It could fit into `@automattic/calypso-products/assets` (new folder)
- [MaterialIcon](https://github.com/Automattic/wp-calypso/tree/trunk/client/components/material-icon): This could fit straight into `@automattic/components` (similar to the WP logo there)

**Comment by tyxla** [comment]
If you really insist, you can create a new assets package, but for a couple of assets, it feels like overkill. What you suggested in "other options" seems OK to me and that's what I'd likely prefer to do.

**Comment by chriskmnds** [comment]
> If you really insist, you can create a new assets package, but for a couple of assets, it feels like overkill. What you suggested in "other options" seems OK to me and that's what I'd likely prefer to do.

Thanks @tyxla. It makes sense. "other options" were also my first/immediate take on this, so will go with that and avoid a new package
