### ISSUE TITLE
Activity Log can fail to load when recent activity includes 1000+ events

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#88204]
### Quick summary

Occasionally, when a customer has made a huge number of edits in a very short amount of time, Activity Log fails to load, instead just displaying greyed out bars. 

### Steps to reproduce

Likely hard to repro – as you'd need to make 1000 changes to blog posts or something.  But theoretically:

Customer in 7841368-zen has 21 pages and 20 posts published, but had just finished manually editing every single one in the last day, when this issue began. 

### What you expected to happen

The Activity Log to load properly, no matter how recently a lot of activity took place. 

### What actually happened

<img width="900" alt="CleanShot 2024-03-05 at 10 29 34@2x" src="https://github.com/Automattic/wp-calypso/assets/27249804/e3e9cb87-7651-476b-b30c-d35d3384464a">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Workaround

The workaround is to manually append the end of the URL for the Activity Log to add a filter. It's easy to do, but not at all intuitive for customers, so it generally requires contacting support and support going through a lot of troubleshooting steps before finding.  Example: p1709659923343749-slack-C03TY6J1A

📜 **HISTORY**

Similar Issue reported but closed here: https://github.com/Automattic/wp-calypso/issues/39772

But in the comments, this specific issue was reported a few times: 

- https://github.com/Automattic/wp-calypso/issues/39772#issuecomment-1150229508 from 35748568-hc
- https://github.com/Automattic/wp-calypso/issues/39772#issuecomment-1154216119 from 5294095-zen
- https://github.com/Automattic/wp-calypso/issues/39772#issuecomment-1154500302 from 5294718-zd-woothemes
- https://github.com/Automattic/wp-calypso/issues/39772#issuecomment-1155921605 from 5298341-zd-woothemes
-

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
As it's so difficult to reproduce marking as triaged but as it's such an edge case, leaving as normal priority rather then high.

## 📌 ACTIONS ##
Triaged

**Comment by Joshgrygiel** [comment]
Seemingly another case here: 7858954-zen

**Comment by Initsogar** [comment]
This seems related to #88749. We just deployed a fix for this and tried rendering the Activity Log for the customer in 7841368-zen, and it is loading now.

Additional context in p9F6qB-eAH-p2#comment-59076.

**Comment by Initsogar** [comment]
> This seems related to #88749. We just deployed a fix for this and tried rendering the Activity Log for the customer in 7841368-zd-a8c, and it is loading now.
> 
> Additional context in p9F6qB-eAH-p2#comment-59076.

@Joshgrygiel this also applies for 7858954-zen. Thanks for adding that ticket as well!
