### ISSUE TITLE
Jetpack Backup Retention Settings Confirmation Modal not disappearing

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/wp-calypso#88201]
### Quick summary

The confirmation modal to change Jetpack settings persists unless you click the `cancel` button or refresh the page. 

### Steps to reproduce

1. Go to https://cloud.jetpack.com/settings/
2. Reduce backup retention period to 7 days. 
3. Click `confirm change` on the warning model which pops up: "You are about to reduce the number of days your backups are being saved. Backups older than 7 days will be lost."

### What you expected to happen

After confirming the change, the modal should disappear. 

### What actually happened

It persists until clicking the `cancel` button or refreshing the page. 

https://github.com/Automattic/wp-calypso/assets/26651984/1728bd09-6a1c-42a3-a84b-588a37e9f1ec

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by Initsogar** [comment]
Thanks for the report!

I'm able to reproduce the issue with the instructions provided. I just added this to our backlog so we can take a look into the fix.

**Comment by Initsogar** [comment]
This is now fixed. Thanks @foleynotrose for the report!
