### ISSUE TITLE
Jetpack Plugins: allow updating from a GitHub repo

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#8820]
Right now, you can update plugins if they're available in the WordPress.org plugin directory, and if an update is available.

It would be nice if site owners could specify a GitHub repository URL as well, and have Calypso pull updates from there when a new tagged release is available.

**Comment by slaFFik** [comment]
Possible UI:
When switching on the Autoupdate toggle: if no such plugin on WordPress.org - ask for a Github repo URL. If it is provided - check (validate) and use Github API, if not or check is failed - display appropriate error message.

**Comment by jeherve** [comment]
Still a potential improvement.
