### ISSUE TITLE
DevDocs: ReaderAuthorLink not rendering

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#8821]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/reader-author-link

#### What I expected
To see a link to the Author Site

#### What happened instead
A blank box is rendered

#8701 made some changes to this component, and I think it's probably working fine in a normal context, but DevDocs is failing to render it. cc: @bluefuton 

Before:
<img width="855" alt="screen shot 2016-10-18 at 3 55 42 pm" src="https://cloud.githubusercontent.com/assets/7233112/19494055/598602e6-954b-11e6-94f0-449efc20c453.png">

After:
<img width="818" alt="screen shot 2016-10-18 at 3 51 26 pm" src="https://cloud.githubusercontent.com/assets/7233112/19494131/a4f3a6fc-954b-11e6-9bad-a6d2ab8f24c2.png">

#### Browser / OS version
Seen in OSX Firefox and Chrome, 

#### Context / Source
#automated-testing #visdiff

**Comment by bluefuton** [comment]
Thanks @hoverduck! I'll take a look.

#automated-testing-is-awesome

**Comment by bluefuton** [comment]
Fixed in #8840.
