### ISSUE TITLE
Site Editor: certain themes fail to load static homepage content

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#88219]
### Quick summary

When the homepage is set to show a static page, Site Editor will show blank page instead of the static page content. Only happens to certain themes. I tested Bedrock.

This issue is not reproduced on self-hosted site, or on Atomic sites which have Gutenberg plugin disabled.

The workaround is to edit the home page in Page Editor, but it might be not intuitive.

### Steps to reproduce

1. Activate Bedrock theme
2. Go to Settings -> Reading
3. Set a static page as homepage
4. Open Site Editor

### What you expected to happen

The page content 

![image](https://github.com/Automattic/wp-calypso/assets/1525580/5a48f968-df03-4d16-b688-ef08ae9b26ad)

### What actually happened

I see blank page 

![image](https://github.com/Automattic/wp-calypso/assets/1525580/8d97b0f7-d4b8-469d-91f0-53f661cec9c8)

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by arthur791004** [comment]
Here are my findings:

* The static homepage of the bedrock theme contains `bedrock/page` pattern with a template part
* When the “homepage displays” is configured to a static page, the post type is weird.
  * It may become the “Page” post so the post type is page. See [here](https://github.com/WordPress/gutenberg/blob/5531a689679576f1b26e6d27e1a95dc1609911c2/packages/edit-site/src/components/editor/index.js#L196).
* We have a hook, [useHideBLocksFromInserter](https://github.com/WordPress/gutenberg/blob/5531a689679576f1b26e6d27e1a95dc1609911c2/packages/editor/src/components/provider/use-hide-blocks-from-inserter.js#L27), that adds a filter to filter out the template part if the post type is not one of wp_block, wp_template, and wp_template_part
* As a result, some blocks of this pattern cannot be inserted into the canvas, resulting in an empty content

So the issue becomes what's the “CORRECT” post type when you open the side editor to edit a static homepage?

**Comment by fushar** [comment]
Corresponding GB issue: https://github.com/WordPress/gutenberg/issues/59634

Should we close this one? cc: @liviopv I am not sure

**Comment by fushar** [comment]
@iamtakashi, based on the GB issue linked above, it looks like it's caused by the theme.

Bedrock theme's Pages template consists of a single `bedrock/page` pattern, which in turn contains template parts (header/footer). Looks like this is not supported? Should we "flatten" the contents of `bedrock/page` pattern into the Pages template instead?

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 

Problem seen as per OP instructions.

## 📌 ACTIONS ##
Triaged

**Comment by iamtakashi** [comment]
> it looks like it's caused by the theme. [...] Looks like this is not supported? Should we "flatten" the contents of bedrock/page pattern into the Pages template instead?

@fushar As far as I've tested, this approach is fine on self-hosted or Atomic sites. Something strange must be going on simple sites, and that should be fixed at the root rather than blaming or taking a different approach in the theme. Otherwise, WP.com will have more themes like this, and there is no way to stop themes from doing the same thing if they work elsewhere. In fact, this issue blocks Low Fi.

**Comment by iamtakashi** [comment]
Isn't this issue the same as https://github.com/Automattic/wp-calypso/issues/87770 ?

**Comment by iamtakashi** [comment]
> This issue is not reproduced on self-hosted site, or on Atomic sites which have Gutenberg plugin disabled.

Were you able to reproduce the issue on Atomic if the Gutengerg plugin is activated? Your screenshot seems that way.

**Comment by fushar** [comment]
> @fushar As far as I've tested, this approach is fine on self-hosted or Atomic sites. Something strange must be going on simple sites, and that should be fixed at the root rather than blaming or taking a different approach in the theme.

> Were you able to reproduce the issue on Atomic if the Gutengerg plugin is activated? Your screenshot seems that way.

@iamtakashi I checked again and I can replicate in simple, Atomic, and self-hosted sites using the latest Gutenberg version (17.8.2 as of this report). See also  @rickmgithub's comment above where he can replicate it on Atomic (which activates latest Gutenberg by default).

So, this is not a dotcom-only bug. I'm not sure if Gutenberg breaks something or it's actually a "bugfix". One solution is to try older GB versions until we find the first version which introduced this behavior. cc: @annezazu 

> Isn't this issue the same as https://github.com/Automattic/wp-calypso/issues/87770

No, this is a different thing altogether.

**Comment by iamtakashi** [comment]
@fushar, My apologies, I spoke too soon. I thought it was the same issue as #87770. I can also replicate this issue in my local install with the Gutenberg trunk activated.

I can't turn the `page` pattern into an HTML page template because it uses a cover block and needs PHP to print the image's URL.

We can open the page template by clicking it from the list in the editor, but we can't open it during the initial load. If I temporarily remove the header template part from the `page` pattern, we can open it without an issue. But it breaks if I add the template part back in. Weirdly, if I wrapped the header template part with a group in the pattern, I was able to open it. This seems to be a Gutenberg issue.

**Comment by dsas** [comment]
> I can't turn the page pattern into an HTML page template because it uses a cover block and needs PHP to print the image's URL.

~~You can [register patterns with PHP](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/) though, shouldn't that work?~~

Edit: Sorry I misunderstood.

**Comment by iamtakashi** [comment]
I'll move the template parts out from the patterns and add them to the templates.

**Comment by iamtakashi** [comment]
I'm not sure when but it wasn't an issue until recently. Anyway, the linked PR above should fix the issue.
