### ISSUE TITLE
User management: Update new user notice copy

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#88222]
## Problem

![image](https://github.com/Automattic/wp-calypso/assets/52076348/2bd99654-31aa-4a9e-b624-53cec5d377c8)

Invitation is now not mandatory, but if a user toggle the `Invite user to WordPress.com` checkbox, we still show

![image](https://github.com/Automattic/wp-calypso/assets/52076348/9c7634d9-efc4-4bb5-8c1e-344a7cf829db)

And in this case, we are contradicting ourselves.

## Solution

Let's update the notice:

```
We highly recommend inviting users to join WordPress.com and log in securely using [Secure Sign On] to ensure maximum security and efficiency.
```

**Comment by JanaMW27** [comment]
I fear the current proposal makes it sound like they may have trouble logging in.

What about:
While users can log in to the site using their credentials, we highly recommend creating a WordPress.com account and using those credentials for logging in to ensure maximum security and efficiency.

What do you think?

**Comment by escapemanuele** [comment]
You may be right, I also sounded a bit too imperative :D

Can we change it slightly to reintroduce "invite" and "join"? "We highly recommend inviting users to join WordPress.com and using that account ...." ?


Also, in some cases, if they have SSO on, they will not be able to log in with their local credentials, as we'll only show the WordPress.com login

**Comment by JanaMW27** [comment]
> Can we change it slightly to reintroduce "invite" and "join"? "We highly recommend inviting users to join WordPress.com and using that account ...." ?

Sounds good

> Also, in some cases, if they have SSO on, they will not be able to log in with their local credentials, as we'll only show the WordPress.com login

This is a bit confusing. If we do not let them log in with their credentials, then we should do as much as possible to make them create an account and not have a checkbox to not send the invite. We are only making it harder for the users and us in case they want to log in, no?

**Comment by escapemanuele** [comment]
For now unfortunately, the checkbox has been requested, as it was blocking some sites that do not work well with invitations.
Maybe we should state that if they rely on WordPress.com login and do not invite the users, they will not be able to use it.
