### ISSUE TITLE
Featured Image: Clicking on Featured Image section in Post or Page shows blank modal.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#8822]
#### Steps to reproduce
1. Starting at URL:  https://wordpress.com/page/ (a new or existing post/page)
2. Click on Featured Image section (with existing image or no image set)
3. Modal comes up completely blank, except for Cancel/Set Featured Image buttons at bottom.

Additionally, clicking on Add Media before going to the Featured Image section results in the modal loading normally for Featured Image afterward.

#### Browser / OS version

Chrome/Firefox/Safari on OSX

#### Screenshot / Video

https://cloudup.com/cOFDr_sLP6o

#### Context / Source
User-reported, verified by other HEs.

**Comment by aduth** [comment]
Regression introduced in #8691 / #8691

Attempted fix in #8827 which was never deployed after discovering unrelated issue with views not being reset when navigating from detail view of editor modal to featured image selector

Straight revert in #8830 now live in production
