### ISSUE TITLE
FE: Last update column data presentation

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#88235]
We are waiting for the BE endpoint to be done to show this data.

The HTML structure and styles are done and the only thing is missing is the real data.
```
<td><Badge type="success" />Feb 21 7:00 PM UTC</td>

<td><Badge type="failed" />Feb 21 7:00 PM UTC</td>
```

**Comment by zaerl** [comment]
1. D141242-code
2. https://github.com/Automattic/jetpack/pull/36277
3. https://github.com/Automattic/wp-calypso/pull/88332
