### ISSUE TITLE
FE: Schedule name; decide the future of this field

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#88232]
Currently, the schedule name field is ignored and the server return hardcoded "jetpack_scheduled_update".

Let's decide the future of this field. Are we going to support the custom name or to build one based on filled params such as "frequency", "time", and the number of selected "plugins".

Proposal:
The form design could stay the same. We can disable the Name field with value: "Everyday updates at 6pm (3 plugins)" or "Weekly updates at 9am (1 plugin)", or whatever in this similar form.

**Comment by obenland** [comment]
I think we should [re-use the strings we currently have to show update frequency for plugins in wp-admin](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/scheduled-updates/src/class-scheduled-updates.php#L130-L153). 
We don't allow time duplicates, so they should cover all cases and be unique enough.

With that switch also comes the opportunity to simplify our create/edit form and only show the things we (currently) need information on. I'd prefer to remove the name field and the concept of schedules having names entirely.

**Comment by zaerl** [comment]
I vote for removing the name field as well. It's an acceptable kind of customization suitable for i2.

**Comment by TimBroddin** [comment]
When testing the project yesterday, I had to use brainpower to come up with a name. +1 to remove this.
