### ISSUE TITLE
FE: Redirect user to home page if user doesn't have update plugins cap

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#88249]
See https://github.com/Automattic/wp-calypso/pull/88177#pullrequestreview-1917711230

This will need to wait until we expose the `update_plugins` cap from the backend. Needs to hold until this is done:
https://github.com/Automattic/dotcom-forge/issues/5943

**Comment by zaerl** [comment]
Renamed the title. Context: p1714469044720709/1714467228.371239-slack-C01A60HCGUA
