### ISSUE TITLE
Users unable to edit wp-admin user profile

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#88258]
### Quick summary

In /wp-admin/profile.php users should be able to edit their user profile information. The editable fields are First Name, Last Name, Nickname (required), and Display name publicly as. Currently, these fields cannot be edited, and the message `WordPress.com users can change their profile's basic details (i.e., First Name, Last Name, Display Name, About) in WordPress.com Profile settings.` However, the WordPress.com Profile settings do not appear to actually have an influence on these settings in wp-admin.

### Steps to reproduce

1. Visit /wp-admin/profile.php
2. Note that there are fields missing under "Name"

### What you expected to happen

All fields should be editable under "Name"

### What actually happened

Some fields are missing

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
Not applicable to simple sites. 
 - Tested on Atomic – Could Not Replicate

## 📌 ACTIONS ##
- Author feedback

##Message to author##
Thanks so much for the report. I couldn't replicate the issue with the same set up. 
When I go into /wp-admin/profile.php for both another user and myself I don't see the First Name, Last Name, Display Name, About sections. Or more correctly they appear for a moment then disappear. Can you share some more details on this one? Is there any example account perhaps or screenshots? Please do reopen if you have more info.

**Comment by masperber** [comment]
Hi Rick, could you refer to this P2 post for a bit more context? p7DVsv-jRh-p2#comment-49418

**Comment by masperber** [comment]
This bug seems to no longer be relevant now that the Untangling Calypso project has moved along. Current functionality allows the wp-admin profile to be edited independently from the WordPress.com profile.
