### ISSUE TITLE
504 Bad Gateway error with MailPoet Automations

### ISSUE THREAD

**Issue by lynnjat7** [Automattic/wp-calypso#88266]
### Quick summary

I have a customer on the Entrepreneur plan which includes both AutomateWoo and MailPoet. 

Originally, the Automations area of MailPoet was disabled, to encourage use of AutomateWoo instead.

Recently, however, we decided to reactivate the MailPoet > Automations menu item for hosted accounts as it was required to set up Welcome emails.

This customer is now seeing that if he goes under MailPoet > Automations, nothing happens for several minutes and then there is a 504 Bad Gateway error. Wondering if something has gone wrong with the return of the Automations menu item for Entrepreneur accounts.

Ticket --> 7815783-zd-a8c

### Steps to reproduce

SU into the account on the ticket (Entrepreneur account)
On the dashboard menu, select MailPoet > Automations
Wait several minutes...eventually see a 504 Bad Gateway error.

### What you expected to happen

Should load the MailPoet automations interface. Other MailPoet features work fine, it's just automations.

### What actually happened

Bad gateway error and nothing loads, the main screen area is just blank except for the gateway error.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Entrepreneur WP plan.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate 

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)


📌 Message to Author
Thank you for this report! I wasn't able to replicate this on any other site with MailPoet I checked which all opened the Automations page as expected. I would recommend a plugin check next.
