### ISSUE TITLE
Stats: dropdown on the single post stats only shows an arrow

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#88268]
https://github.com/Automattic/wp-calypso/assets/1425433/2b510e84-8949-41c3-8fca-5b6d37083dc9

- I would expect it's showing the current selection
- ~The black is huge below the bread crumbs~ (https://github.com/Automattic/wp-calypso/issues/88269)

**Comment by dognose24** [comment]
In my testing, this situation only occurs for a post with Email Stats.

**Comment by dognose24** [comment]
> I would expect it's showing the current selection

I would focus on this issue since the second one would be duplicated with https://github.com/Automattic/wp-calypso/issues/88269.
