### ISSUE TITLE
Stats: Massive blank space after header

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#88269]
<img width="439" alt="Screenshot 2024-03-07 at 9 59 47 AM" src="https://github.com/Automattic/wp-calypso/assets/1425433/c71d2919-44cd-4133-bbad-4ffa4c185d09">

The blank space should reasonable.

**Comment by kangzj** [comment]
Btw the header isn’t aligned well at some break points. I’m not sure whether it’s still the case

**Comment by dognose24** [comment]
> Btw the header isn’t aligned well at some break points.

@kangzj Thanks for the heads up. I will investigate it along with https://github.com/Automattic/wp-calypso/issues/86955
