### ISSUE TITLE
Payments: Unable to create a plan using JPY 

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#88280]
### Quick summary

When trying to create a payment plan in Tools > Monetize > Payment Settings, an error stating `Please enter a price higher than ¥50` shows up, and it never goes away no matter what amount is set. As a result, a payment plan can't be created.

Done means:
- [ ] Payment plan creation validation no longer shows incorrect errors when user fulfills the requirements

### Steps to reproduce

1. Go to Tools > Monetize > Payment Settings.
2. Hit `Add a new payment plan`.
3. Set the currency to JPY.
4. Enter a price higher than ¥50 as suggested.

### What you expected to happen

A new plan is created without any issues.

### What actually happened

The save button remains greyed-out no matter what amount is added.

![Screen Shot on 2024-03-07 at 11:10:07](https://github.com/Automattic/wp-calypso/assets/32432463/f07bfb90-6b97-4d8b-8b7c-22b123d9fd38)

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

User report: 7844652-zen

I tried to switch the dashboard interface language to Japanese to see if it makes any difference, but it didn't solve the issue.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described. Also occurs with HKD and MXN

📌 ACTIONS
- Triaged

**Comment by lsl** [comment]
Looks like something to do with the yearly price values on paid newsletter teir. Guessing state is leaking between these two toggles where it shouldn't be.

![Screenshot(230)](https://github.com/user-attachments/assets/71ea6b9c-3da2-413a-b0d6-98002c2637fe)

**Comment by lsl** [comment]
cc @Automattic/gold In case you're able to pick this up faster than we can.

**Comment by millerf** [comment]
We'll take it. Thanks for the ping!

**Comment by chrismccluskey** [comment]
Fix deployed!
