### ISSUE TITLE
Newsletter Settings in JP: Introduce Tracks stats to the Newsletter Categories settings

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#88304]
**Context:** p1HpG7-rkO-p2

**Comment by yansern** [comment]
Research: p1HpG7-rkO-p2#comment-70485
Action items: p1HpG7-rkO-p2#comment-70486

**Comment by yansern** [comment]
Links to the 2 funnels here (p1HpG7-rkO-p2#comment-70492):
- How many users enable newsletter categories on Jetpack?
- How many users toggle the newsletter categories settings on and off on Jetpack within 7 days?

**Comment by yansern** [comment]
PR for tracking creation of newsletter category with the event name `jetpack_newsletter_add_category`. https://github.com/Automattic/jetpack/pull/36326.
