### ISSUE TITLE
Newsletter Settings in JP: Remove the Follower Settings section from the reading settings on Classic View

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#88305]
Remove the Follower Settings section from the reading settings on Classic View `/wp-admin/options-reading.php`.

**Context:** pdDOJh-3a8-p2

**Comment by yansern** [comment]
Jetpack PR: https://github.com/Automattic/jetpack/pull/36314 
Cleanup PR: D141432-code
