### ISSUE TITLE
Center the "All together now" modal

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#88324]
The "All together now" modal should be centered on the screen.

For context see: p1709762884683639-slack-C06DN6QQVAQ

![Image](https://github.com/Automattic/wp-calypso/assets/140841/5c40740a-dd61-416b-af3e-591cc9a65532)

**Comment by allilevine** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/88364
