### ISSUE TITLE
Do not show "All together now" modal to new users

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#88325]
Do not show the "All together now" modal to new users, as they have nothing to compare the new navigation to.

For context, see: p1709762884683639-slack-C06DN6QQVAQ

![Image](https://github.com/Automattic/wp-calypso/assets/140841/74f3a077-ba3c-4883-aa8c-0e3f0ba609dc)

**Comment by roo2** [comment]
fixed by https://github.com/Automattic/wp-calypso/pull/88446
