### ISSUE TITLE
Command Palette: GitHub deployment isn't available in wp-admin

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#88345]
### Quick summary

A new "Open GitHub deployments" command was introduced in #88092 and later feature flagged in #88101 in Calypso, it is not added in wp-admin

### Steps to reproduce

1. Go to a site which ought to have GitHub deployments available in Calypso 
2. Open the command palette with ⌘+k
3. Type GitHub 
4. Notice a Open Github deployments command
5. Go to `/wp-admin` on the same site
6. Open the command palette with ⌘+k
3. Type GitHub 

https://github.com/Automattic/wp-calypso/assets/93301/f58549e7-a4f8-465a-9242-2811dce80262

### What you expected to happen

To be given a GitHub deployments command which goes to `/github-deployments/:siteSlug`

### What actually happened

No commands found

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by filipanoscampos** [comment]
📌 ACTIONS
Report kept.
Updated triage labels.

**Comment by rcrdortiz** [comment]
These changes will be available once Jetpack gets released on Simple and Atomic sites.
