### ISSUE TITLE
Safari: Unable to add a featured image on mobile

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#88358]
### Quick summary

While navigating a post on mobile using Safari on mobile, we can't assign/add a featured image.

### Steps to reproduce

1. Create a new post or open an existing one
2. Try selecting/changing the featured image section.

### What you expected to happen

For the field to work

### What actually happened

When tapping on the section, nothing happens.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Reported from here: p1709906991691769-slack-C03TY6J1A

Ticket: 7857985-zd-a8c

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Could Not Replicate
– Tested on Atomic: Could Not Replicate



📌 FINDINGS

Either on a simple site or atomic, I was able to set a post featured image without issues.


📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)
