### ISSUE TITLE
Plans: AT Business Users should see a WPCOM Business plan on my-plan page

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8836]
Folks that have been used been automatically transferred should still see the wpcom plans page when visiting: http://calypso.localhost:3000/plans/my-plan/:site:/  instead of the Jetpack my-plans page.

We're not quite sure on how transferred sites will be represented in data yet, but let's investigate to see what steps we'd need to make to have an existing Jetpack site display the wpcom my-plans page. 

We should double check that all modules make sense, and that links work.

**Comment by artpi** [comment]
## Sections

I have checked sections that I have no doubt,that they make sense:

- [ ] Enjoy priority support from our Happiness Engineers
- [ ] Custom Domain ( how to use domain credit? )
- [ ] Advertising Removed
- [ ] Google AdWords credit
- [ ] Customize your theme
- [ ] Attend live courses
- [ ] Video and audio posts
- [ ] Stats from Google Analytics ( in progress )
- [ ] Find a new theme ( is the theme catalogue going to work? Its only installed themes now )
- [ ] Easily monetize your site ( @dereksmart ? )

**Comment by artpi** [comment]
Per @rralian comment https://github.com/Automattic/wp-calypso/pull/8847#issuecomment-254821090 I am ticking off "advertising removed" and "google analytics" as "no doubt".

**Comment by artpi** [comment]
This seems to be done now
