### ISSUE TITLE
Bug: Plugin Marketplace - Don't Display Related Plugins that Don't Exist

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#88368]
### What

In the Plugin Marketplace, there are Related Plugins displayed but not all of them exist. 

### Why

Clicking on a Related Plugin that do not exist shows "Oops! We can't find this plugin!". If a plugin does not exist, remove it from the related plugin list. 

### How

For example, in Woo Subscriptions plugin https://wordpress.com/plugins/woocommerce-subscriptions/ the Related Plugins are: All Products for Woo, Recurring, Subscriptions & Recurring Payments and Subscriptions for WooCommerce. 

<img width="1137" alt="Screenshot 2024-03-11 at 12 05 05" src="https://github.com/Automattic/wp-calypso/assets/36863633/8ef247e5-dfa0-413a-b304-ead8f1d1487b">

The "Recurring" plugin does not exist, but is still displayed on the Related Plugins section. Clicking "Recurring" plugin shows "Oops! We can't find this plugin! The plugin you are looking for doesn't exist."

<img width="672" alt="Screenshot 2024-03-11 at 12 11 16" src="https://github.com/Automattic/wp-calypso/assets/36863633/bcfc3935-0ae5-44e1-b845-31305a2613b4">

The full list of Woo Subscriptions plugin Related Plugins are in: https://wordpress.com/plugins/subscriptions-recurring-payments-for-woocommerce/related and there are several plugins here that don't exist. 

<img width="1414" alt="Screenshot 2024-03-11 at 12 12 47" src="https://github.com/Automattic/wp-calypso/assets/36863633/60403894-a062-45eb-a69d-c895ad64da36">

**Comment by filipanoscampos** [comment]
It is strange that plugins that no longer exist are still showing up here.
I'm not sure if this shouldn't be treated as a bug.

Let me ping the relevant team.

📌 ACTIONS
– Feature request kept for now.
Ping here: p1710261540649279-slack-C029JEQRVRT

**Comment by gcsecsey** [comment]
Diff created with the fix: D141768-code

**Comment by gcsecsey** [comment]
Changes deployed in r289818-wpcom
