### ISSUE TITLE
Plans: AT Footer Credit Management

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8837]
When a site is transferred automatically, the footer credit feature should work as expected.

If you have a Business plan you can manage the footer text by navigating to https://wordpress.com/settings/general/:site:

<img width="749" alt="screen shot 2016-10-18 at 2 53 21 pm" src="https://cloud.githubusercontent.com/assets/1270189/19497824/fe5d3de2-9542-11e6-93d8-75325f0be19e.png">

Clicking on the button, which takes you to the customizer:

<img width="290" alt="screen shot 2016-10-18 at 2 55 48 pm" src="https://cloud.githubusercontent.com/assets/1270189/19497832/06de85ac-9543-11e6-8872-ace5c567d512.png">

And this gives us a few options:

<img width="286" alt="screen shot 2016-10-18 at 2 55 53 pm" src="https://cloud.githubusercontent.com/assets/1270189/19497830/0327c798-9543-11e6-821c-a09629e4135c.png">

**Comment by artpi** [comment]
Please review https://github.com/Automattic/pressable-footer-credit/pull/1
