### ISSUE TITLE
Launchpad: Site cannot access `/home` because of redirect loop

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#88386]
Site in question along with a description of the behavior is here: p1710175764454889-slack-C0Q664T29

Unlaunched Atomic site cannot access `/home` because of a chain of redirects that ends in a loop:

1. User goes to `/sites`
2. User clicks on their site to go to `/home`
3. `/home` redirects to `/site-setup/goals?siteSlug=...`
4. Clicking "Skip to dashboard" on `/site-setup/goals?siteSlug=...` redirects to `/home`
5. ...which then redirects back to `/site-setup/goals?siteSlug=...`

This site is also on an Entrepreneur plan, so `/home` _should_ redirect to WC admin.

Seemed like it might be related to https://github.com/Automattic/wp-calypso/issues/88384 but clearing the `site_intent` did not fix it.

ZD: 7787925-zd-a8c

**Comment by sixhours** [comment]
The redirect happens here: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/customer-home/controller.jsx#L73

Oddly, if I look at the site settings in network admin, the `launchpad_screen` option is `skipped`, but if I log it on the front end or check the site's API, it's `full`. So that's why the redirect is happening, but I don't know where the mismatch comes from yet.

**Comment by sixhours** [comment]
Well, I've fixed this manually by updating the site option via CLI on the user's site:

`wp option update launchpad_screen 'skipped'`

The bug to fix here is figuring out what steps were taken to get the site into this state so it doesn't happen again. :)

**Comment by arthur791004** [comment]
The mismatch happens as we don't sync the `launchpad_screen` to the atomic site correctly. See D141422-code.

**Comment by sixhours** [comment]
I tried to get a new site into this situation in a couple ways:

* Straightforward -- signed up and purchased an Entrepreneur plan. No Launchpad was shown, so no need to worry about the option.
* Roundabout -- signed up on a Free plan, skipped the Launchpad step, then upgraded to Entrepreneur. Everything worked as expected.

So I don't think this is a common bug or one that can easily be reproduced. From the diff intended to solve this issue:

> Everything seems to work well without this change. So, let's close it for now. We can make changes again when there is any issue related to this one 🙂

I'll close this as a result.
