### ISSUE TITLE
Feature Request: Add an “erase everything” button on themes to remove all demo content and start from scratch.

### ISSUE THREAD

**Issue by xavier-lc** [Automattic/wp-calypso#88389]
From this user interview (pekYwv-3Hg-p2):

> She would like an “erase everything” button to remove all demo content and start from scratch.

As an example, this is how a fresh site looks after creating it with the [Hey theme](https://wordpress.com/theme/hey):

![Image](https://github.com/Automattic/wp-calypso/assets/8511199/3dcee21e-0472-48fc-95d8-81ef5c390763)

**Comment by Aurorum** [comment]
Does that not already exist? https://wordpress.com/settings/start-over/

I believe that works for Headstart.

**Comment by xavier-lc** [comment]
@Aurorum you're right, that cleans up the predefined posts. But it's at the bottom of the settings page, and the interviewed user didn't find. Maybe it should be more accessible, in the same line as the user can see an `Edit Site` button while logged in.

**Comment by liviopv** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
Include any additional details or steps to reproduce.
Attach screenshots or videos.

📌 ACTIONS
- Requested author feedback

📌 Message to Author
> Maybe it should be more accessible, in the same line as the user can see an Edit Site button while logged in.

@xavier-lc I think that would be a very bad idea considering we don't have an easy way to restore simple sites without intervention. My perspective from supporting Dotcom customers for 8 years is that we should avoid giving them the chance to perform destructive actions if there is no easy way to revert them.

I'm inclined to close this in favor of https://github.com/Automattic/wp-calypso/issues/76883 where there was already previous discussions about surfacing options to start over in different ways - what do you think?

**Comment by Aurorum** [comment]
> I think that would be a very bad idea considering we don't have an easy way to restore simple sites without intervention

strong +1

**Comment by xavier-lc** [comment]
@liviopv sounds good, closing this.
