### ISSUE TITLE
FE: provide empty state for plugin picker

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#88404]
In the create/edit schedule, let's provide an empty state for the plugin list view.

cc @JanaMW27 

Context: https://github.com/Automattic/wp-calypso/pull/88376#issuecomment-1988970849

**Comment by JanaMW27** [comment]
hummm... is this in case the user doesn't have any plugin?
if that is the case they should not be able to access the feature no?

**Comment by TimBroddin** [comment]
It's the case where the user doesn't have any plugin that's not managed by us. We currently show a banner in the add/edit view when this happens:

![Image](https://github.com/Automattic/wp-calypso/assets/528287/ff2d3321-12db-4394-a4fa-dde531bf3a36)

It would be nice if we also show something inside the empty list view there.

**Comment by JanaMW27** [comment]
My take on this:
- If no plugins can be included in an update schedule, the user shouldn't be able to access the feature.
- If for some reason they still are able to access it, I would have an announcement on the empty schedules page saying: To set up schedules to manage your plugins, first you need to install plugins that are not managed by the plugin provider.
- I would not have the Create a new schedule CTA and I would replace it with one that would take the user to the plugins page (Explore plugins)
- I would not allow the user to access the New Schedule page
![Empty state](https://github.com/Automattic/wp-calypso/assets/71137829/d4d18d39-9f79-4673-85d1-69fa3a4eb36c)

Is there a specific case scenario where they may still have access to a Schedule page even though no plugins are available?
