### ISSUE TITLE
Checkout: Postal code validation error is incorrect for Germany

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#88436]
### Quick summary

A German postal code consists of five numbers, where any code with fewer or more than (5) will result in a validation error. In the case for Germany, the validation error says `Expects 8 numbers, no letters or special characters. Please use the 12345678 format.` which leads to further confusion.

![image](https://github.com/Automattic/wp-calypso/assets/16580129/37b4ba18-dfc7-41a2-8269-a65970acad6b)

### Steps to reproduce

Go to checkout, click on Edit next to Contact Information, set country to Germany, and enter a postal code that is fewer or more than (5) characters.

### What you expected to happen

I expect the error validation to show the correct suggestion and format.

### What actually happened

Instead we are advised to enter an 8 digit code.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by jjchrisdiehl** [comment]
Diff is here D141721-code

**Comment by sirbrillig** [comment]
Approved!

**Comment by jjchrisdiehl** [comment]
Deployed
