### ISSUE TITLE
Checkout: Fields use a mixture of rounded and square corners

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#88437]
### Quick summary

Checkout fields appear to use a mixture of rounded and square corners - we should make them all rounded and uniform.

### Steps to reproduce

Go to checkout and inspect the different checkout fields.

### What you expected to happen

Should show as rounded corners on all fields.

### What actually happened

There is a mixture of rounded and square fields - see original report pbOQVh-45k-p2#comment-5580

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by retnonindya** [comment]
📌 ACTIONS
- Triaged

**Comment by JessBoctor** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/93775
