### ISSUE TITLE
Classic Editor | Bug | "Set Featured Image" button in browser in mobile breakpoints disabled

### ISSUE THREAD

**Issue by pak-cia** [Automattic/wp-calypso#88445]
### Quick summary

The "Set Featured Image" button found in _Classic Editor_'s **Featured Image** selection screen remains disabled and cannot be used to add or update a post's featured image: https://prnt.sc/AQ9qsLCrfULA

Can be replicated on both actual mobile devices and on desktop mobile view emulators. Button works without issue on Desktop view/breakpoint.

Have tested across different _Classic Themes_ with similar results: https://prnt.sc/QSZKjnpBGfJS
Tested with _FSE Themes_ as well, with similar results, where the "Set featured image" button is grayed out and unclickable.

Calypso button is "Insert" which works without issue in both desktop and mobile.

### Steps to reproduce

1 - Set browser to view as mobile, or use a mobile device
2 - Open/Create any post in _Classic Editor_
3 - Select/Edit the post's _Featured Image_ to bring up the _Media Library_

### What you expected to happen

We should be able to select an image, then click on the "Set featured image" button to confirm the selection and save changes.

### What actually happened

"Set featured image" button is disabled/grayed out and cannot be clicked.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

some console errors that don't seem to be part of the norm - https://prnt.sc/vrRVTfP5KDHD

7865125-zen

**Comment by pak-cia** [comment]
Additional findings:
Same issue occurs for "Add media" interface on mobile breakpoints, the "Insert into post" button is disabled/grayed out
https://prnt.sc/-QJcNR-e6fOs

**Comment by pak-cia** [comment]
other tickets with similar issue:
7859375-zen
7859638-zen

**Comment by Aurorum** [comment]
7897742-zen

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple: Mixed results
– Tested on Atomic: Could Not Replicate


📌 FINDINGS
Thanks to @mrfoxtalbot we were able to reproduce this partially on a few simple sites on smaller viewports.
On larger viewports, this cannot be reproduced.

On my Apple device, I was not able to reproduce the issue, only on an Android device. 

When using the Classic Editor and uploading media either as a Featured Image or content, the "Insert into post" button or the "Set featured image" buttons are greyed out and do not work.

Setting a Featured Image:
https://github.com/Automattic/wp-calypso/assets/2540430/846db175-abf7-4d06-b035-ca582c2ac667


Inserting an image:
https://github.com/Automattic/wp-calypso/assets/2540430/c5c2f3fa-cdc0-44b1-b292-815dc1d857cb



📌 ACTIONS
– Report kept and updated.

**Comment by lsl** [comment]
Seems to be fixed at this time. If you encounter this again please drop a ping in #dotcom-escalations so a dev can take a look while the issue is reproducible.
