### ISSUE TITLE
It seems to be possible to create a WooPayments account before confirming an email address of a WordPress.com account

### ISSUE THREAD

**Issue by grig-23** [Automattic/wp-calypso#88478]
### Quick summary

It seems to be possible to create a WooPayments account before confirming/verifying an email address of a WordPress.com account as per 7881836-zen. Check the audit trail of the account mentioned in the note of this ticket on March 13th, the note that starts with "According to audit trail of..".

### Steps to reproduce

I have not tested this but all evidence points to it being possible to:

* Create a WordPress.com account with an email address that isn't yours.
* Create a Woo.com and a WooPayments account with that email address.
* Only then change the email address of the WordPress.com account to your own, and verify the ownership.
* There is a WooPayments account under someone else's email address.

### What you expected to happen

We could put restrictions in place on the WPCOM server to only facilitate the connection if an account is verified

### What actually happened

The owner of the email address is threatening with legal action since there is a WooPayments account they did not create.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

**Comment by csmcneill** [comment]
While the original issue is related to WooPayments, this is potentially an issue with any product that uses Jetpack for connecting to the WPCOM servers (e.g., [WooCommerce Shipping & Tax](https://woo.com/products/shipping/?aff=10486&cid=1131038))

A couple of things to note/clarify:
- Creating a WooPayments account requires a WPCOM account — not a Woo.com account. A Woo.com account is used for purchasing, managing purchases, and getting support for said purchases on Woo.com.
- If creating a WooPayments account with a fresh WPCOM account, the WPCOM email must be verified via a magic link before the WooPayments account can be created:

![CleanShot 2024-03-13 at 12 37 25](https://github.com/Automattic/wp-calypso/assets/82999806/325fb37d-2b0c-45cc-a090-55fa07fcd3b7)

**Comment by grig-23** [comment]
Sounds like we were unable to replicate this and there's evidence that the email address verification actually happened before a WooPayments account was created. Closing.
