### ISSUE TITLE
Site Editor never finishes loading for certain themes when Gutenberg 17.8.2+ is active

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#88516]
### Quick summary

https://github.com/Automattic/wp-calypso/assets/14153300/6f58122e-e9ec-4047-b563-db8f62638ce8

### Themes where it can be reproduced
- Hevor
- Pomme
- Cakely
- Bedrock
- Feeling Good
- Spiel

### Themes where it is working fine
- TT4
- TT3
- Creatio 2
- Assembler

### Workaround
- Deactivate Gutenberg
or
- Navigate to the Template directly at Editor > Templates > [Template] 

### Steps to reproduce

1. Activate an block theme like Hevor or Cakely on an Atomic site
2. Go to the Site Editor
3. The Site Editor will not finish loading

Repro'd on GB 17.9.0 and 17.8.2. Cannot repro without the GB plugin on WP6.4.3

### What you expected to happen

The Site Editor should finish loading and display the template content

### What actually happened

The template loads with no content. Container Blocks are visible in the List View, but Pattern Placeholder shows for everything else.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by dsas** [comment]
Note that this sounds almost identical to #88219 but apparently that should only happen when the “homepage displays” is configured to a static page.

#87770 is a different issue that presents similar symptoms. The template is loaded but some blocks aren't displayed and "pattern placeholder" is in the block list.

**Comment by liviopv** [comment]
Marking this as closed
