### ISSUE TITLE
Bug: Add default value if utm values are empty

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#88537]
![Image](https://github.com/Automattic/wp-calypso/assets/1425433/dd3bce71-7caf-459f-90db-29bcfea35ab0)

**Comment by a8ck3n** [comment]
Hey @kangzj. Did you happen to check the API results for this? I'm looking at something similar and I think this might actually be an issue with our parsing logic. cc @dognose24 as we were discussing something similar earlier today.

**Comment by dognose24** [comment]
https://github.com/Automattic/wp-calypso/pull/88636 should already address this issue on the front end. We may need to investigate the reason for the unrecognized label on the API end.

**Comment by dognose24** [comment]
> We may need to investigate the reason for the unrecognized label on the API end.

As the `utm_values` from data tables are already written with unrecognized numbers, we may need to trace back to the UTM parameter recording part.

**Comment by kangzj** [comment]
> we may need to trace back to the UTM parameter recording part.

Sounds good; however we probably also want to front end to be able to correctly handle these, for example, `(Empty)` or `(Unknown)` etc, to be more robust.

**Comment by kangzj** [comment]
I didn't find any more of these cases, so it was probably only related to https://github.com/Automattic/wp-calypso/pull/88636. I'll close the issue now.
