### ISSUE TITLE
Faulty error when signing up account using android browser and specific email structure

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#88545]
### Quick summary

When signing up using OAuth, android mobile browser and use a specific email address, an error `Use a different email address. This email provider blocks some of our emails.` will be produced.

#### Reproduce using android mobile browser
1. In an android device, open up Firefox browser
4. Go to https://jetpack.com/login
5. Click on `Create an Account`
6. Enter email with suffix of `+` and a number, such as `avalidemail+12345@gmail.com`
7. Observe you'll be shown the following error:

<img width="200" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/8ef7834a-b36c-44c0-b30b-2f8096eb3b8d">

#### Reproduce using desktop browser
1. In a browser, install user-agent modifier extension, such as https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/
3. Use the browser agent string `Mozilla/5.0 Chrome/1 Safari`
4. Run steps 2-4 in above instructions
7. Observe you'll be shown the following error:

<img width="465" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/4a1739ce-8294-4337-ade4-af8829b81f52">

### What you expected to happen

Should not produce error differently than other user agents

### What actually happened

Error that's specific to android mobile browsers

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by taipeicoder** [comment]
@ilyasfoo could you check if this issue is still reproducible? Thank you!

**Comment by ilyasfoo** [comment]
Hey, @taipeicoder. Yes, I'm still able to reproduce the issue with the steps in the issue description:

<img width="818" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/d5ba0ef7-3b7d-46a8-a716-6874a6b867a0">

**Comment by lsl** [comment]
Expected behavior.

**Comment by 8227846265** [comment]
I also experience the same issue.
