### ISSUE TITLE
Add-Ons: Refactor use of feature slugs for determining storage add-on uniqueness

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#88553]
### What

This is a follow-up issue to a recent discussion we've had in https://github.com/Automattic/wp-calypso/pull/87938/files#r1507406936 

The issue seems twofold:

1. It is unclear whether feature slugs are the right term/concept to associate with the storage add-ons. Their intended use was to map the add-ons to site/plan features. 
2. The features slugs were introduced to serve a single purpose - to uniquely identify storage add-ons that are using the same product slug. Initially, add-ons were meant to be uniquely identified by the product slugs. I think the use of feature slugs was at least partly the consequence of leaving add-on definitions in an unindexed array (back when we wrapped up the work), otherwise we'd probably never even considered using features slugs for this purpose.

### Why

1. It's important to have non-ambiguous concepts and definitions in the codebase. Otherwise this risks becoming a vicious cycle where "feature" slugs lose their meaning. 
2. Technically speaking, uniquely identifying an object based on an element that could live inside an array (e.g. `Foo: { featureSlugs: [ 'use this for id of foo' ] }` is an anti-pattern that needs to be fixed. This is the current scenario right now with storage add-ons (`featureSlugs` being of type `string | string[]`).

**Comment by chriskmnds** [comment]
cc @jeyip @southp (I think I summarised things well?) 😆

**Comment by jeyip** [comment]
Hi @chriskmnds! This sums things up wonderfully. Thanks for making this issue 🙏

**Comment by southp** [comment]
Agreed. Thanks for the great summary :) 
It clearly depicts the fact that the current data representation is not enough to express our products, i.e. plans & add-ons. (maybe domain is also a "product" ... not sure). It'd take another foundational refactor to fully resolve this 🌝

**Comment by chriskmnds** [comment]
This should be resolved through the last few refactors. We now use add-on identifiers/slugs and no longer feature slugs for storage
