### ISSUE TITLE
Reader: Refresh cards wrap when happy chat is open

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#8856]
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/ with `reader/refresh/stream` feature enabled
2. Open chat by clicking the `SUPPORT CHAT` link at the bottom of the sidebar. 
3. Resize window larger so that chat docks to the right side
4. Resize window down until action links wrap badly

<img width="1167" alt="following_ _reader_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/14350/19521990/a3a51464-95e3-11e6-9e1b-9f98feb45f36.png">

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/8865

I also noticed a similar issue in full-post. I'll fix that in a separate PR.

**Comment by jancavan** [comment]
Also happens in current stream. I'll fix.

![screenshot 2016-10-19 20 31 46](https://cloud.githubusercontent.com/assets/4924246/19545436/1dc56f76-963b-11e6-876c-357aa3a5e22b.png)
