### ISSUE TITLE
List block not showing bullet points

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#88589]
### Quick summary

List block not showing bullet points

### Steps to reproduce

1) Create a site with a Starter plan
2) Add a post
3) Add a list block with the bullets and not numbers
4) Notice that no bullets appear

### What you expected to happen

Bullet points to appear

### What actually happened

Bullet points didn't appear

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Video of issue occuring

https://github.com/Automattic/wp-calypso/assets/13706336/864696bf-ab16-4b95-9766-ffa23023da68

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Could Not Replicate

Uploading Kapture 2024-03-19 at 13.47.24.mp4…



📌 FINDINGS

Could not replicate on a Simple site.



📌 ACTIONS
– Requested author feedback


📌 Message to Author
Hey @rickmgithub!
I wonder if this is specific to a theme.
Could you give me more details about the theme you reproduced it with?

Thank you!

**Comment by ntsekouras** [comment]
Thank you for your issue @rickmgithub ! This seems like a theme issue indeed and I think we can close it. Feel free to reopen if needed.
