### ISSUE TITLE
WPCOM API: Edit method doesn't work for some random case

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#88596]
As we had a problem with deleting a schedule item before, I stumbled upon a case where edit acted the same way as delete. I got a status 200 OK, but after the schedules fetch, everything returned to the previous state, so the edit was not applied.

Related to: https://github.com/Automattic/dotcom-forge/issues/5948

**Comment by obenland** [comment]
I think this might actually be a duplicate of https://github.com/Automattic/dotcom-forge/issues/5948. When a schedule gets edited, under the hood the endpoint deletes it and creates a new one.

**Comment by ouikhuan** [comment]
Yes, it is. I think create/update/delete is probably all the same issue under the hood.

**Comment by zaerl** [comment]
Close. See https://github.com/Automattic/dotcom-forge/issues/5948.
