### ISSUE TITLE
/pricing landing page: Add links/access to Support guide on the /pricing page

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#88591]
### What

There are potentials on the page https://wordpress.com/pricing/ for users to learn more about WordPress.com by adding link to our Support guide or /learn site.

### Why

Dotcom Happiness has worked on the new scope of support (p7DVsv-kbu-p2) and will be helpful if we can teach users to "fish" by exploring our public-facing Support guide and /learn. It will also allocate more time for HEs to focus on developers and agencies.

### How

For example, in this section on FAQ: "Can I import..."

<img width="1316" alt="Screenshot 2024-03-17 at 8 04 47 PM" src="https://github.com/Automattic/wp-calypso/assets/44726232/cc64b0dc-7346-47ae-898b-566eb7a3eb54">

It will be helpful if we also put the Support guide of website import https://wordpress.com/support/import/ that users can explore and browse.

Also, on this section: "Get free, expert help in our community forums..."

<img width="1323" alt="Screenshot 2024-03-17 at 8 07 49 PM" src="https://github.com/Automattic/wp-calypso/assets/44726232/490d068f-2d8d-4d0e-b942-863390ff04df">

We can also add links/pointers to wordpress.com/learn ("Get free, expert help in our community forums, join our free courses and webinars on wordpress.com/learn, or upgrade to any plan for pro support by email and live chat.")

**Comment by Aurorum** [comment]
> We can also add links/pointers to wordpress.com/learn

This might be problematic in the sense that it would no longer mean the pricing page is harmonised across all locales (`/learn` doesn't support i18n).

**Comment by fredrikekelund** [comment]
@dzver @claudiucelfilip, was it a conscious decision not to include links in the FAQ section on the current `wordpress.com/pricing` iteration?

I think this is a reasonable request, but I also know there are plenty of parameters governing the look of that page.

**Comment by fredrikekelund** [comment]
I've updated wordpress.com/pricing/ to include several new links. Here's a rundown:
- Added a link to [wordpress.com/forums/](https://wordpress.com/forums/)
- Added a link to [wordpress.com/themes](https://wordpress.com/themes)
- Added a link to [wordpress.com/patterns](https://wordpress.com/patterns)
- Added several links in the FAQ section with inspiration taken from [wordpress.com/hosting/](https://wordpress.com/hosting/). The question that most sorely needed a link was perhaps "Can I create a site in another language?" that previously said "…please visit our support page all about setting up multilingual sites" but didn't include a link.
