### ISSUE TITLE
Customizer: Header image cannot be cropped on mobile

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#88603]
### Quick summary

Previous reports:

https://github.com/Automattic/customization/issues/135

https://core.trac.wordpress.org/ticket/30634

https://core.trac.wordpress.org/ticket/40152

### Steps to reproduce

1. Activate a classic theme like Toujours
2. Open the dashboard on your smartphone
3. Go in Appearance > Customizer > Header image

### What you expected to happen

To be able to crop the image after selecting it.

### What actually happened

I select the image and nothings happens except for the "Select and crop" button that's changing color but cannot be pressed.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

As a workaround you can crop an image on desktop/laptop screens or through the Media section, but the main issue si that you can't assign an image on mobile via Appearance > Customize > Header image.

7856789-zen

More context:

> Ok I will try the larger screen on a tablet, but this is really VERY odd because I have used cropping with no issue at all from my iPhone for years without any issues, so why would it suddenly not work?🤔
> 
> Please let me know what your tech gurus at your end may still dig up. 
> 
> This all started with the latest Wordpress “update” that added a new copy feature that shows up with scheduled posts.  
> 
> Since that update, I no longer get an image icon with the scheduled posts — just a blank icon. This glitch happened at the exact same time as the loss of the photo cropping feature.

**Comment by lsl** [comment]
Couldn't repro. Reopen if it pops up again, looks fixed.
