### ISSUE TITLE
Site Migration: Plans page, fix border and update copy

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#88625]
On the Plans upgrade step, the Continue button should not have a blue border:

![Image](https://github.com/Automattic/wp-calypso/assets/2124984/d9845aee-b8da-4a1b-ba39-b1ac4c569487)

Also, the text says, “Continue.” We used to say, “Upgrade and migrate.” I’m just curious: Is there a reason for this change?

Finally, if you click “Show all features” the list is expanded but there’s no separation between the card and the edge of the page.

Ref: pdtkmj-2uc-p2#comment-4645

**Comment by andres-blanco** [comment]
The blue border seems to be fixed now:


![Image](https://github.com/Automattic/wp-calypso/assets/375980/7b2ca204-9db4-484d-ba35-077570dc4de9)

> Finally, if you click “Show all features” the list is expanded but there’s no separation between the card and the edge of the page.

Can you add a screenshot? I don't fully understand the issue here.

**Comment by sixhours** [comment]
I think when the "Show all features" was expanded there was no bottom margin between the content and the bottom of the screen, but that's not the case with the updated layout. Closing this!
