### ISSUE TITLE
Site Migration: Add admin user/email as a user on the migrated site

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#88621]
After a site has been migrated, we need to add the site owner's email address/account as a user to the new site. `wpcom_get_blog_owner( $blog_id )` can check a site ID and return the owner.

Ref: pfxNPL-5s-p2#comment-108

**Comment by valterlorran** [comment]
We are tackling this issue on D143118-code

**Comment by valterlorran** [comment]
Closing this as we deployed D143118-code
