### ISSUE TITLE
Site Migration: Consider adding direct link to migration plugin

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#88624]
> I don’t know if this idea was abandoned for a good reason, but if not, I think it would be nice to offer this as the installation link: {source-site-url}/wp-admin/plugin-install.php?s=%2522migrate%2520guru%2522&tab=search&type=term instead of just directing the user to the plugin’s page. This URL will open the ‘Add plugin’ page inside the source site with ‘Migrate Guru’ as the only result, making it faster to install the plugin and complete the instructions.

@javierarce made this suggestion for the site migration instructions page.

Ref: pdtkmj-2uc-p2#comment-4645

**Comment by gabrielcaires** [comment]
Already implemented as part of https://github.com/Automattic/wp-calypso/pull/88813

**Comment by gabrielcaires** [comment]
closed as part of  https://github.com/Automattic/wp-calypso/pull/88813
