### ISSUE TITLE
Editor: keyboard shortcut to toggle visual/html

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#8864]
Hey! Long time listener, first time caller... love your work on the Editor.

I really dig the visual mode, and that's where I do most of my writing. But one thing I run into sometimes is that certain things are easier to do in html. And when I'm writing a long post, it's a pain to have to scroll up to toggle the mode, and then scroll back down to find where I was to make a change. Would be awesome if there was some keyboard shortcut to do this instead. :-)

**Comment by designsimply** [comment]
#bug-scrub #pre-gutenburg-bug-purge

Re-checked and confirmed there is still not a keyboard shortcut for switching between visual and HTML mode in the editor.

<img width="469" alt="screen shot 2018-01-05 at fri jan 5 5 24 17 pm" src="https://user-images.githubusercontent.com/1119271/34634028-8d2109b6-f23d-11e7-9105-0719996b24ac.png">
