### ISSUE TITLE
Table of Contents Block: Add more options for bullet points and numbering

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#88649]
### What

Currently, the ToC block only shows content with numbering, there are no settings to change this numbering (such as a b c, or I II III) or to remove the numbering all together

### Why

User noted that the current format is not standard; 

<img width="674" alt="table-of-contents-block-with-nested-headings" src="https://github.com/Automattic/wp-calypso/assets/5075840/1b358394-9325-475b-ba00-00142e7e11fc">

Examples we can use instead;

![CleanShot 2024-03-19 at 11 12 56@2x](https://github.com/Automattic/wp-calypso/assets/5075840/e7244e1a-338d-401a-811c-5bb6bf2a1adc)

![CleanShot 2024-03-19 at 11 13 06@2x](https://github.com/Automattic/wp-calypso/assets/5075840/3c373840-3bdc-4a6f-a27e-d257988efda2)

![CleanShot 2024-03-19 at 11 13 42@2x](https://github.com/Automattic/wp-calypso/assets/5075840/65d4f952-de1b-4359-9ada-ad828e53f12f)

### How

Add more options in the block settings to show how the ToC is displayed

**Comment by liviopv** [comment]
📌 ACTIONS
- Closed as duplicate

📌 Message to Author
@Greatdane TOC is a core Gutenberg block and there's already a bug/feature request for this https://github.com/WordPress/gutenberg/issues/41769 in core, so I'm closing this report.
