### ISSUE TITLE
Reader Stream Refresh: Standard card flashes while photo card is loading

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8866]
As mentioned in this thread https://github.com/Automattic/wp-calypso/pull/8843#issuecomment-254695791, standard card flashes while the photo-only card is loading:

https://cloudup.com/cldHLUdue13
https://cloudup.com/cTNFfmXaXTc

Example: http://calypso.dev:3000/read/feeds/23059853 (first post in stream)

**Comment by bluefuton** [comment]
Notes on a possible fix from @blowery:

> We need to teach the fast rule set in the post normalizer to build post.images
> Maybe post.content_images. Need to peek at the classifier to see which it uses
> The trick is that we need to try to figure out image dimensions before they load
> And maybe assume images without a size are big enough. Then we would flash from photo or gallery to default or text only
> Which may be less jarring
> And hopefully infrequent

**Comment by blowery** [comment]
Hopefully will get fixed with #8555

**Comment by blowery** [comment]
Should be mostly fixed now
