### ISSUE TITLE
Stats: Browser back button doesn't work after clicking upgrade nudge

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#88714]
Clicking the upgrade button in the UTM module directs you to the purchase flow. If you decide to back out of this, you'll end up on the last page that manually updated the browser history instead of going back to the root Stats page.

### Example steps

1. Visit Stats → Traffic.
2. Scroll down and click on the Authors → "View all" link.
3. Navigate back to Stats → Traffic.
4. Click the "Upgrade plan" button.
5. Once on the purchase flow, click the browser's back button.
6. Note that you end up on the Authors summary page instead of the Stats → Traffic page.

I think the quick fix here would be for us to update the browser history before routing to the purchase flow.

**Comment by dognose24** [comment]
I think simply using `page()` rather than `page.redirect()` would address the issue. https://github.com/Automattic/wp-calypso/blob/46a9dd5274bd6a3bae937cb62771d53e62dbeca3/client/my-sites/stats/stats-card-upsell/stats-card-upsell-jetpack.tsx#L52

**Comment by dognose24** [comment]
As I mentioned in [the comment above](https://github.com/Automattic/wp-calypso/issues/88714#issuecomment-2009721149), the issue has been addressed in https://github.com/Automattic/wp-calypso/pull/89380/files#diff-5b052d8ff7bc2315ea4eef4790990d30e709f7465441b69b1ae193c1aa354649R60.
