### ISSUE TITLE
FE:Add track events when create/edit/delete schedules fail and notify user to try again

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#88741]
We observe that sometimes create, edit, delete schedules doesn't work even if the status comes back with 200, or the response is `true`.  In this case, the schedule remains untouched and it will confuse users. Until we figure out the root cause:

- We need to add a track event so we can have a better understanding of how often this happens.
- We need to notify users that something went wrong and they have to try it again.

Related to:
- https://github.com/Automattic/wp-calypso/issues/88596
- https://github.com/Automattic/dotcom-forge/issues/5948

**Comment by ouikhuan** [comment]
It looks like the root cause might be the cache from the backend. Please hold until we decide what's the best to do next. More context: p1711022309360939-slack-C01A60HCGUA

**Comment by zaerl** [comment]
See https://github.com/Automattic/dotcom-forge/issues/5948.
