### ISSUE TITLE
Activity log: not loading on specific dates and activities

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#88749]
### Quick summary

I've seen two cases now where the activity log is refusing to load people data for specific days. It doesn't seem like the number of changes is so large and the requests are getting responses back but nothing is loading. 

looks similar to https://github.com/Automattic/wp-calypso/issues/88204

p2: p9F6qB-eAH-p2

In the latest instance I see numerous recquests for this which all return 200s and data:
https://public-api.wordpress.com/wpcom/v2/sites/220727301/activity?_envelope=1&aggregate=true&after=2023-07-19%2021%3A00%3A00&before=2023-07-20%2020%3A59%3A59&group%5B%5D=user&number=1000

If anything other than People on July 19-20, 2023 is selected, things load fine
If no filter is used, it fails to load anything, presumably because the full log includes the data above

### Steps to reproduce

This is not a generic bug, it seems to only be on a few sites and the prerequisite conditions are not clear

1. Go to unfiltered activity log and see failure to load
2. filter by date and exclude problem date (July 20, 2023) > see load
3. Filter to July 19-20 and select everything but People > see load
4. Filter to July 19-20 and select only People > see fail

### What you expected to happen

activity log should load and truncate if there's too much data

### What actually happened

fails to load
![2024-03-21 at 11 19](https://github.com/Automattic/wp-calypso/assets/47717887/affdb342-3840-48dc-ab4c-2f5003423126)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by vparkhere** [comment]
@Automattic/yamato-backup Could we get some help on this Activity Log issue please?

**Comment by jwebbdev** [comment]
@Initsogar started looking into this and will follow-up when we get some more information.

**Comment by Initsogar** [comment]
Thanks for the report. We had some issues when returning specific user role updated events, that's more likely what it was failing especially when filtering by `People`. The Activity Log were expecting a `summary` field that wasn't returned in those scenarios.

The issue is now being fixed and discussed in p9F6qB-eAH-p2#comment-59076.
