### ISSUE TITLE
Hook: Identify website host

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#88773]
We want to be able to identify the current host of the user that is going through the migration flow.

We have a method already for identifying it: https://github.com/Automattic/dotcom-forge/issues/6428

We need to build a hook inside Calypso. This hook will call the site-profiler endpoint and return the information about the current host.

**Comment by renancarvalho** [comment]
Found out that there's already an implementation of it [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/data/site-profiler/use-hosting-provider-query.ts).

@escapemanuele closing it 👍
