### ISSUE TITLE
Site Migration: Fix loading style

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#88818]
# Goal
Fix the loading style when we are creating the wp.com site.

![Image](https://github.com/Automattic/wp-calypso/assets/38718/1a2a1c0a-9455-4e59-a6ea-d00623320431)

More context pdtkmj-2uc-p2#comment-4612

**Comment by andres-blanco** [comment]
Not sure what the action item is for this issue. I've asked for more context from Bogdan here: pdtkmj-2uc-p2#comment-4680

**Comment by andres-blanco** [comment]
Closing this, since the style used in the new migration flow is the same as in the rest of stepper. So I think keeping it that way is better for consistency.
