### ISSUE TITLE
Domain registration flow - pre-fill email address

### ISSUE THREAD

**Issue by dhackneya8c** [Automattic/wp-calypso#88860]
### "What": What is your idea?

When a user purchases a domain, they're prompted to enter their contact details for the domain registration. We propose pre-filling the email address field with the email address that's registered to their WordPress.com account automatically.

### "Why?": Why would this be impactful?

In Account Recovery, when someone uses a different email address to register their domain than the one that's listed on their WordPress.com account, a series of extra tasks are formed that take two weeks to resolve (this is outlined in the Field Guide under Domain Ownership & Disputes). Pre-filling the email address in the domain registration contact details would help reduce the number of incidences of this that take up more time for HEs to resolve.

### "How?" How should this feature work?

On the checkout form, contact details are requested before payment:

<img width="1161" alt="Screenshot 2024-03-25 at 8 36 24 AM" src="https://github.com/Automattic/bugomattic/assets/24231249/70977287-1ef9-4a67-b991-2db1c742e665">

Pre-filling the email address field there for the user automatically will reduce domain disputes down the line, allowing HEs more time to work on other issues.

**Comment by maciejpilarski** [comment]
📌 ACTIONS
– triaged

**Comment by mmtr** [comment]
Looks like this idea has been already implemented in production. Tried with an existing and a new account, and in both cases the contact information during checkout had the email pre-filled.
