### ISSUE TITLE
Editor: "Undo" errantly converts some code in code tags

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#8886]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Using the visual editor, add some code, wrapping it in code tags.
3. Add some more text
4. Use ctrl+z or command+z to undo
#### What I expected

I expected my last changes to be undone
#### What happened instead

The code in the tags gets converted to HTML character entities or otherwise modified.  If you try undoing again, more HTML character entities are inserted.
#### Browser / OS version

Chrome on Windows & Mac; also on Firefox on mac.
#### Screenshot / Video

https://cloudup.com/cB2jkGRQQtj

**Comment by lancewillett** [comment]
CC @aduth in case related to recent `code` handling changes in editor.

**Comment by aduth** [comment]
Unlikely to have been _caused_ by #8325, but rather the changes there had not accounted for undo history. If I were to guess, the issue may be that TinyMCE internally stores the original content even though we proceed to change it, so when undoing, the encoded version is used instead.

We may need to either:

- Replace content entities in the entire undo history ([similar to as we do for media](https://github.com/Automattic/wp-calypso/blob/30b185e71cb3a64ead9e9b07a60087212e9757f6/client/components/tinymce/plugins/media/plugin.jsx#L247-L254))
- Capture the undo event and ensure content entities are replaced

**Comment by supernovia** [comment]
Just noting another case of this:
https://pbs.twimg.com/media/Cx-ilyJXAAA_tHM.jpg:large

I'll find out if it's happening on Undo.
