### ISSUE TITLE
Using assembler doesn't mark select a design as complete in the blog flow

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#88893]
### Quick summary

Using the /create-blog flow, and opting to use 'Creating your own design' (the assembler) results in the launchpad not marking the 'Select a design' step as complete. It does mark it as complete in other flows.

### Steps to reproduce

1. Start at wordpress.com/create-blog
2. Click 'Start a blog' (or scroll and use "pick a design first")
3. Click to "Pick a design first"
4. Click to "Start a new site"
5. Click 'Design your own'
6. Click through the assembler just choosing the defaults at each step
7. Eventually you end up in the site editor
8. Press the WordPress logo in the top left to go to the dashboard
9. Reach the launchpad

### What you expected to happen

The "Select a design" launchpad task to be checked

### What actually happened

The "Select a design" launchpad task was not checked

<img width="1456" alt="Screenshot 2024-03-26 at 09 33 48" src="https://github.com/Automattic/wp-calypso/assets/93301/ece534f7-2f7d-4993-9d91-bd089d3e09b0">

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

Originally reported at p1711441584480669-slack-C048CUFRGFQ by @JanaMW27 

This does not happen in the standard onboarding flow (/start) - the task is checked there no matter how you enter the assembler.

**Comment by hacchism** [comment]
Another report: 8012803-zen

This seems to be creating another issue that makes Site Editor unusable. If you visit Appearance → Editor, you get redirected to My Home like this:

https://github.com/Automattic/wp-calypso/assets/32432463/827203cc-6e9b-4d25-9d0e-6c78816b0cbf




The only solution for this is just switching to a different theme.

**Comment by filipanoscampos** [comment]
For future reference: It looks like this is solved by launching the site and setting it to Coming Soon.

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
