### ISSUE TITLE
Stats: UTM module interactivity on the post details page

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#88911]
https://github.com/Automattic/wp-calypso/pull/88535#pullrequestreview-1938216875:
> The UTM module doesn't respect the chart selection. To be consistent with other pages, we probably need to move the UTM module above the "All-time insights" module and make sure it respects the current selection values.

More discussion: p1710513646032379/1710470649.962169-slack-C82FZ5T4G

For now, the data is all-time for the UTM module, which does not correspond to the selected date period above.

<img width="1290" alt="截圖 2024-03-26 下午11 45 27" src="https://github.com/Automattic/wp-calypso/assets/6869813/67af136d-3c97-4750-ad3b-9866919d07cb">

cc @ederrengifo @kangzj

**Comment by ederrengifo** [comment]
Just to clarify, this means we want for the UTM stats to be affected by the time range selection, right? If that's the case it makes sense for the all-time insights and UTMs to switch places:

![Image](https://github.com/user-attachments/assets/00d48d17-db59-4ede-a63f-92e6558633b8)

cc @dhasilva
