### ISSUE TITLE
Cannot add more than 19 Payment Plans on AT sites

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#88924]
### Quick summary

When a site is AT'd, it cannot have more than 19 plans set up for the Payments block in the `Tools > Monetization > Payment Settings` area -- when adding new plans, old plans are removed from the site

### Steps to reproduce

1. Set up a new AT site and connect it to Stripe from `Tools > Monetization > Payment Settings`: `https://wordpress.com/earn/payments/`
2. Add up to 19 new payment options on the site
3. Attempt to add a new 20th payment option

### What you expected to happen

The new level would be added without any loss of other subscription levels, which is how it works on simple sites:

![2024-03-26 18 14 01](https://github.com/Automattic/wp-calypso/assets/4000628/058c3024-2557-4669-ba5d-26848f5f856f)

And self-hosted sites:

![image](https://github.com/Automattic/wp-calypso/assets/4000628/92bd82bb-40f8-4528-80e3-955102bc4159)

### What actually happened

The last plan is dropped from the list, which could result in lost revenue -- note in this GIF that the plan list starts at Test Plan 8, and after refreshing the page after adding a new plan, the list now starts at Test Plan 9

![2024-03-26 16 29 56](https://github.com/Automattic/wp-calypso/assets/4000628/2b087581-a41d-4ba7-9605-9e6898c420bd)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Tested on Chrome and Firefox, on an Explorer plan, Creator plan, and Jurassic Ninja site

**Comment by edequalsawesome** [comment]
7942269-zen

**Comment by millerf** [comment]
@edequalsawesome Thanks for reporting!

After looking into it, I found the issue. 

First of all, the plans are not deleted. There is an issue with an internal pagination that defaults to 20 items and prevents the plans to be displayed. I'll update the pagination number to 100 and we will look into a proper fix later.

**Comment by millerf** [comment]
Fix in D143494-code

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Could not replicate after @millerf fix

![CleanShot 2024-04-02 at 15 26 26@2x](https://github.com/Automattic/wp-calypso/assets/14153300/45a27393-4e6c-41fd-a669-36281a263cbd)


📌 ACTIONS
- Closed as fixed / resolved
