### ISSUE TITLE
Default option in Design Your Own page

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#88940]
### Quick summary

When I enter the Design Your Own Feature the Intro section is selected rather than the Header section making for a less logical flow in designing the site.
Should the Header section be pre-selected instead.

### Steps to reproduce

1. Go to the themes area - https://wordpress.com/themes/
2. Scroll down to select the design your own option
3. When the designer loads the intro option is selected by default rather than the header.

<img width="3228" alt="Markup 2024-03-27 at 17 12 50" src="https://github.com/Automattic/wp-calypso/assets/13706336/8943fd41-924e-4ad9-bd2b-1cfe6159b38f">

### What you expected to happen

The first item in the list to be selected.

### What actually happened

The second item in the list is pre-selected.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
Replicated

📌 ACTIONS
- Triaged

📌 Notes
I'm not sure if this is a bug report or Feature Request. Might be best to set as Feature Request. 

Checking with team Marvel here: p1711531331102119-slack-C048CUFRGFQ

**Comment by retnonindya** [comment]
Closing the Feature Request. This flow is expected. See: pekYwv-3MZ-p2
