### ISSUE TITLE
Refreshed Stream: Photo Cards showing when they shouldn't

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8894]
Just testing the current state of calypso.live and noticed that photo cards are showing for pretty much everything from gizmodo.com, even though their posts have over 130 character excerpts. Maybe because it's RSS?

For example: https://calypso.live/read/feeds/10080096/posts/1194713322

![screen shot 2016-10-20 at 4 57 29 pm](https://cloud.githubusercontent.com/assets/24388/19582040/549ae5d4-96e6-11e6-9083-5f2e596cc7d6.png)

**Comment by fraying** [comment]
Another (not-RSS) example: https://calypso.live/read/feeds/41325786/posts/1194852576

![screen shot 2016-10-20 at 5 22 11 pm](https://cloud.githubusercontent.com/assets/24388/19582498/c09d0912-96e9-11e6-8b81-1614bb03ead0.png)

The excerpt is 203 words.

**Comment by bluefuton** [comment]
I make the excerpt 37 words on that Discover post @fraying (has it been edited?)

<img width="751" alt="screen shot 2016-10-21 at 15 48 43" src="https://cloud.githubusercontent.com/assets/17325/19585073/f1cc4716-97a5-11e6-97dc-ff1f8a8997b1.png">

**Comment by bluefuton** [comment]
Ah, the _character_ count is 203. Got it.

We currently look for posts under 100 words to classify it as a photo card. I'll change that to 130 chars.

**Comment by fraying** [comment]
It’s 130 characters we’re looking for, not words. ;-)
