### ISSUE TITLE
Mobile preview in Design Your Own feature is different on final site

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#88941]
### Quick summary

If you preview the site in the Design Your Own on a mobile view, the preview just shows a narrower desktop preview. 

### Steps to reproduce

1. Set up a site and select to design the sign with the "Design Your Own" option - https://wordpress.com/setup/site-setup/design-choices
2. Add a few element to the page
3. Preview the mobile view and desktop view.
4. Notice the mobile preview is not the "mobile" version but a shrunk down "desktop" view.
https://github.com/Automattic/wp-calypso/assets/13706336/1c4d99fc-d167-4a9c-be55-bd750e859b47

5. Now complete the "Design your own" process and look at the mobile preview in the editor with the completed site.

https://github.com/Automattic/wp-calypso/assets/13706336/2a63e179-a158-4778-9670-a095f9ebf6cd

4. This time it correctly shows the mobile preview.

### What you expected to happen

The mobile preview to work correctly in both instances

### What actually happened

The mobile preview in the Design Your Own view didn't work

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by arthur791004** [comment]
Closing it as the design-your-own flow has been removed.
