### ISSUE TITLE
Refreshed Stream: Death to the RSS icon

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8896]
The RSS icon is showing in the new cards. For example:

![screen shot 2016-10-20 at 5 02 08 pm](https://cloud.githubusercontent.com/assets/24388/19582143/0e5f2174-96e7-11e6-89d6-f3d2d7757feb.png)

This icon should be the circle gravatar if the author has one. If not, the square blavatar. If not, the square feed icon or favicon. If none of those, then no icon at all, and just scoot the text to the left edge.

**Comment by bluefuton** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/8904.
