### ISSUE TITLE
Plan step: Implement dynamic stats based on hosting

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#88971]
There is a new endpoint that we can leverage to get dynamic data:
`site-profiler/metrics/basic?url=...` 

- [ ] Let's build a hook in calypso that queries that endpoint and returns the data
- [ ] Context here: p55Cj4-2Wq-p2#comment-3450. Download the cwvtech.report file and use it in Calypso (@escapemanuele: I can do this). Let's focus on LCP for now (speed).
- [ ] TBD: Compare user's site performances with WordPress.com averages and show in the upgrade plan page.

**Comment by renatho** [comment]
Closed with https://github.com/Automattic/wp-calypso/pull/90457 and https://github.com/Automattic/wp-calypso/pull/90717 (It included the LCP and the FID).

**Comment by renatho** [comment]
Closed with https://github.com/Automattic/wp-calypso/pull/90457 and https://github.com/Automattic/wp-calypso/pull/90717 (It included the LCP and the FID).
