### ISSUE TITLE
Refreshed Stream: Default Card: Images too tall

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8897]
The images in the Default card need to end on the same baseline as the action links (the bottom edge of the Visit icon is a good indicator).

So this:
![screen shot 2016-10-20 at 4 41 19 pm](https://cloud.githubusercontent.com/assets/24388/19582168/587bdb94-96e7-11e6-9b89-9a8ff238c698.png)

Should be this:
![screen-shot-2016-10-20-at-4 41 19-pm2](https://cloud.githubusercontent.com/assets/24388/19582198/828c3866-96e7-11e6-8628-1b28a5b31e0a.png)

**Comment by blowery** [comment]
I added a min height to the images because so many ended up with worthless crops. Also, why isn't this one a photo card?

**Comment by blowery** [comment]
Or did I? I think that pr was punted actually.

**Comment by blowery** [comment]
Oh, what site is that? @dllh's secret blog?

**Comment by blowery** [comment]
https://calypso.live/read/feeds/29809688

looks like it's because the action row is weirdly tall.. @jancavan any ideas on why that might be? Seems to be twice as tall as necessary...

**Comment by fraying** [comment]
The screenshot in above is from this post: https://calypso.live/read/feeds/29809688/posts/1194977999

(So, no, should not be a photo card.)

**Comment by dllh** [comment]
I think you're looking for @aheckler re the secret blog.

**Comment by jancavan** [comment]
> Also, why isn't this one a photo card?

@blowery I think that might https://github.com/Automattic/wp-calypso/pull/8899?

> @jancavan any ideas on why that might be? Seems to be twice as tall as necessary...

I'll take a look.
