### ISSUE TITLE
Reader: update placeholder image to better match new default card format

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8898]
The current placeholder image ...

![placeholder](https://cloud.githubusercontent.com/assets/24388/19582617/f68b96b4-96ea-11e6-9213-23c4b34951f9.png)

... should be updated to better match the new default card format. (Wanna take this @jancavan?)

**Comment by blowery** [comment]
While we're at it, we might want to look at using something easier for the browser to draw. The current pulse is pretty choppy, even on my recent edition Mac. On a phone, its almost nonexistent.

**Comment by fraying** [comment]
What would be easier to draw? Is filesize the issue?

**Comment by blowery** [comment]
http://cloudcannon.com/deconstructions/2014/11/15/facebook-content-placeholder-deconstruction.html

**Comment by fraying** [comment]
Oh, nifty!

**Comment by blowery** [comment]
Right now we animate by altering the opacity of various bits inside the placeholder. opacity is actually supposed to be a "cheap" thing to animate: http://blog.teamtreehouse.com/create-smoother-animations-transitions-browser

Maybe we just have too much of it? 

Either way, something to poke at. Not the focus of the issue.

**Comment by mtias** [comment]
If we have ideas to improve placeholders it should be done globally in Calypso.

**Comment by blowery** [comment]
@mtias Yeah, of course. After sleeping on it, I have a hunch the problem isn't with the animation itself, but with work being done on the main UI thread in the browser, leading to jank appearing in the animation. Need to do some profiling to sort it out.

**Comment by fraying** [comment]
So, back to the original problem: the placeholder just needs to lose the border and maybe tweak the shapes so they better match the new format.

**Comment by blowery** [comment]
@jancavan can you take this?

**Comment by jancavan** [comment]
@blowery yes, on my to-dos.
