### ISSUE TITLE
An article about Calypso

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#890]
Hello,

I just published an article about Calypso. It contains some technical details so I thought it might be useful for new developers. If you like it, please share it.

https://lamosty.com/2015/11/wp-calypso-first-impression/

Thanks.

**Comment by reginaldojunior** [comment]
:+1:

**Comment by jeherve** [comment]
Thanks for the post, it's a good intro to Calypso!

I'll close this issue, since you don't seem to be reporting any bugs in your post. :)

Feel free to open a new issue if you run into issues or have questions about Calypso!

**Comment by lamosty** [comment]
@jeherve Thanks!
