### ISSUE TITLE
Site Migration: Add tracks to banners

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#89052]
# Goal 
We want to track the users coming from the new  migration banner

More details p1711627374986019/1711622736.933629-slack-C0Q664T29 

![Image](https://github.com/Automattic/wp-calypso/assets/38718/222369f3-e20a-40ac-8861-c646f6fb4423)

The banner was applied on the following pages:
* https://wordpress.com/support/import/import-an-entire-wordpress-site/
* https://wordpress.com/support/import/import-using-move-to-wordpress-com/
* https://wordpress.com/support/import/#self-hosted-word-press-org-site
*  https://wordpress.com/support/import/import-using-migrate-guru/

NOTE: Move these tasks to the appropriate repository.

**Comment by markbiek** [comment]
Initial implementation here: D144025-code

This is a fairly simplified approach which adds some JS to the theme to catch the "Request" button click and fire a tracks event. We may want to explore a more general solution down the road. One suggestion from @daledupreez for a future implementation was a button wrapper which helps automate Tracks handling.
