### ISSUE TITLE
Nav Redesign: Jarring with Different Colour Schemes

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#89065]
I'm not sure if this an intentional design decision, but I'd like to start some discussion about it just to confirm. I've been using the new sidebar for a bit now, and I generally really like it, but there's only one thing which slightly bugs me. 

The new sidebar is always blue and white, which can be very jarring when you're using a different colour scheme. I feel like most people generally navigate immediately to editing a site, so the jump between colour schemes is very noticeable. 

![ScreenRecording2024-03-30at21 26 45-ezgif com-video-to-gif-converter](https://github.com/Automattic/wp-calypso/assets/43215253/de5b931d-63ba-4e35-919c-1a60b7af46bb)

Any idea on if this was intentional?! 

cc @davemart-in

**Comment by davemart-in** [comment]
Hey @Aurorum! Great to hear from you.

Prior to finalizing our navigation updates, we conducted numerous usability tests. A significant insight emerged from these tests: novice users found it challenging to distinguish between the global state and the wp-admin state. The recent changes were deliberately implemented to visually differentiate these two states more clearly.

That said, we'd like to implement a dark mode option. I'd be curious to hear your thoughts on that.

**Comment by Aurorum** [comment]
Thanks for your reply @davemart-in! :) 

> A significant insight emerged from these tests: novice users found it challenging to distinguish between the global state and the wp-admin state. 

Ahhh, I see! For what it's worth, although that reasoning makes perfect sense, I didn't quite catch the distinction between the two until you mentioned it (but I recognise you might have tested that with new users already!). I think that's partly because some of the colours are inherited from the colour scheme, but others aren't. 

> That said, we'd like to implement a dark mode option. 

That'd definitely make it a lot easier on the eyes when opening Calypso in the dark! :) Might also be very nice if an option was added to match the colour scheme for the site dashboard, if that's something you'd be willing to consider. 

Might just be my personal preference, but I did prefer the consistent colour scheme. I guess my only comment would be that I've seen users getting confused between their user profile for sites and their Account Settings, so I do understand confusion between global state and wp-admin state is a problem, but I'd argue that it's not a problem so widespread (at least from my experience in Support!) to not have that option available.

**Comment by davemart-in** [comment]
I'm not sure if this is 100% decided yet, but I think the plan is to 100% do away with Dashboard color schemes at the global level. This option under Me -> Account Settings:

![CleanShot 2024-04-02 at 17 33 15@2x](https://github.com/Automattic/wp-calypso/assets/5634774/de68215c-ff5d-4753-828a-0a66bb8c560c)

At the same time we'll re-activate WP Core's admin color schemes for each site under /wp-admin/profile.php

The primary benefit of doing this will be that customers with multiple sites will have the option of using a different admin color scheme for each site they manage (making it easier to tell at a glance which site they're editing).

The global nav would then just have a light and dark mode.

I'd be very curious to hear your thoughts on this proposed plan @Aurorum.

**Comment by Aurorum** [comment]
Ah, that's very interesting - thanks for sharing @davemart-in! I presume that the Core admin colour selection would also take effect in Calypso, but not for the global state? I think that's a very reasonable plan and would definitely make things feel a lot cleaner between the global state and dashboards for individual sites. 

I'll close this particular issue for now since it's intentional for the Nav Redesign not to inherit colours, but I'd definitely be keen to see a dark mode for the nav scheme (as ever, do let me know if there's anything I can do to help with that).
