### ISSUE TITLE
Notifications: Following your own new site is a weird experience

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#8908]
I was creating a new site and got a notification on doing so that I'd followed it. This felt a little odd. I think I've experience it before and maybe just accepted it, or I never got this before - as it felt really weird.

![2016-10-22 at 11 46](https://cloud.githubusercontent.com/assets/253067/19618833/5c49b284-984d-11e6-8d62-55d72324a1d6.png)

I'm not sure in the process following your own site and at least getting a notification make sense.

**Comment by drw158** [comment]
We've gotten this issue enough to the point where we can label this as a bug/enhancement.

I suppose following your own blog is a technical requirement. If that is true, we should create an exception for this notification and not let the user see it.

**Comment by drw158** [comment]
Moved https://github.com/Automattic/notifications-panel/issues/217
