### ISSUE TITLE
Add featured image section to theme templates 

### ISSUE THREAD

**Issue by Joshgrygiel** [Automattic/wp-calypso#89088]
### What

In cases where the homepage theme template is used, it is not directly possible to add a featured image to it - This causes confusion on what image would be shared to social media or in feeds for the homepage.

### Why

This would add a level of clarity to the featured image assignment for site-editor based themes, especially when the customer is not accessible to set a custom homepage 

Ref: https://github.com/WordPress/gutenberg/issues/55978

### How

Would it be possible to add the same featured image options that appear for pages and posts within the index or home theme templates as well?

**Comment by liviopv** [comment]
📌 ACTIONS
- Closed as duplicate

📌 Message to Author
@Joshgrygiel closing in favor of https://github.com/Automattic/wp-calypso/issues/87844
