### ISSUE TITLE
Monetize: Improve the "Download CSV" button.

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#89108]
When a user has a lot of supporters the "Download CSV" button is difficult to find:

> They have so many supporters that the button keeps dropping lower down as I scroll. 
—Slack thread: p1712053711106029/1712052696.364479-slack-C03TY6J1A

Here's a screenshot, very zoomed out (thanks @millerf):

![monetize-supporters](https://github.com/Automattic/wp-calypso/assets/87168/9bc586a4-2a32-4777-a88a-50d245bf6349)

**Comment by crisbusquets** [comment]
cc @Automattic/zap

**Comment by simison** [comment]
@crisbusquets thoughts on having the download button moved to one of these placements?

<img width="861" alt="Screenshot 2024-04-02 at 13 54 22" src="https://github.com/Automattic/wp-calypso/assets/87168/1ffceda7-2583-44af-8f43-41f9df4b1d82">

Subscription management as a comparison:

<img width="1223" alt="Screenshot 2024-04-02 at 13 53 32" src="https://github.com/Automattic/wp-calypso/assets/87168/48769f97-9334-4156-bcea-a15eecc5213f">

It could be put behind a three-dots menu, but feels a bit hidden just for one action. Multiple actions behind three dots would make sense.

**Comment by simison** [comment]
Moved the button to the table heading in https://github.com/Automattic/wp-calypso/pull/89111 since that was the simplest approach with the current code structure.

It's also semantically at the right level since heading is shared between other pages.

**Comment by liviopv** [comment]
📌 ACTIONS
- Marking as Triaged since it's on Gold's board and there's a PR in progress. @simison or @crisbusquets  please close this once the PR is merged.

**Comment by millerf** [comment]
Fixed by https://github.com/Automattic/gold/issues/369
