### ISSUE TITLE
Update the Pricing page: Explorer plan Support 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#89100]
### What

Update the Pricing page https://wordpress.com/pricing/ plan features to avoid user confusion. 

### Why

The Pricing page Explorer plan yearly includes "24/7 expert support". This is confusing and misleading to users and think that the Explorer plan comes with 24/7 live chat support.

### How

User case: 7975759-zen 

<img width="1243" alt="Screenshot 2024-04-02 at 10 17 54" src="https://github.com/Automattic/wp-calypso/assets/36863633/79fe19f6-8f3f-4595-9aae-be57856dc727">

**Comment by rickmgithub** [comment]
I've reached out to marketing for suggestions on this here - p1712212018901839-slack-C042CJ2NH to see if this is something they'd action.

**Comment by taipeicoder** [comment]
It now says "Fast support from our expert team". I'll close this but free to re-open if needed!

![Image](https://github.com/user-attachments/assets/22ed85a2-4a4e-492e-a6a1-d3a711f6a0e1)
