### ISSUE TITLE
Site Migration: Roll out to all locales after translations are available

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#89107]
The underlying changes were initially shipped in https://github.com/Automattic/wp-calypso/pull/88952 before being reverted and then shipped in https://github.com/Automattic/wp-calypso/pull/89006. I am not sure which PR will get the translations, but we should keep an eye on those two PRs to know when the translations are available.

Note that we limited the rollout to the `en` locale in https://github.com/Automattic/wp-calypso/pull/89016, and then to English locales in https://github.com/Automattic/wp-calypso/pull/89035.

**Comment by sixhours** [comment]
I'm not sure we'll get an update on translations for those PRs if we didn't trigger it with the String Freeze label 🤔 But we can look at the translations recently committed by developer username and I think we're in good shape except for `pt-br`:

<img width="1489" alt="Screenshot 2024-04-04 at 12 49 52 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/009b448d-6b1e-4ae0-91d0-3580b7248fc1">

**Comment by daledupreez** [comment]
It looks like all the strings from this PR are now translated based on https://translate.wordpress.com/deliverables/overview/11803816/, so I think we can roll this out to all locales now.

**Comment by daledupreez** [comment]
I am going to mark this as complete, as both https://github.com/Automattic/wp-calypso/pull/89257 and https://github.com/Automattic/wp-calypso/pull/89277 have been shipped to users.
