### ISSUE TITLE
Unable to Update Newsletter Settings 

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#89109]
### Impacted plugin

Jetpack

### Quick summary

On Atomic sites, the Newsletter settings are not saving properly. It shows the error "An unexpected error occurred. Please try again later" when saving. Refreshing the page, shows the settings are changed however, the live site remains unaffected. 

### Steps to reproduce

1. On an Atomic site, navigate to Settings > Newsletter
2. Adjust the settings under Subscriptions.
3. Click "Save Settings". See the error.

![error](https://github.com/Automattic/jetpack/assets/93800099/40bfc9ea-3512-4f52-a948-d019112da548)

### A clear and concise description of what you expected to happen.

That the settings would save successfully and the changes be reflected on the live site.

### What actually happened

An error shows and the live site doesn't reflect the changes.

This is what a sample post page looks like with all Newsletter Subscriptions settings turned off.

![Subscribe block showing](https://github.com/Automattic/jetpack/assets/93800099/c9c528c6-8b41-453a-bf2d-7d503da3d105)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Reported here: 7966380-zd-a8c

Was not able to replicate on a Simple site.

**Comment by jeherve** [comment]
Moving this to Calypso since this is about the toggle in the Calypso UI.

**Comment by jeherve** [comment]
I can't quite reproduce on my end, the settings appear to save properly on my end. @upwardmomentum84 Could you tell us more about the site setup? Is the site public or private? 

Could you also open the browser's dev tools, go to the "Network" tab, filter for "XHR", try reproducing the error, and then click on the call that generated the error and navigate to "Response"? What do you see there?

Thank you!

cc @pkuliga who recently worked on #88702.

**Comment by pkuliga** [comment]
I was able to repro this on Atomic.

The `GET 
https://public-api.wordpress.com/rest/v1.4/sites/229656926/settings?http_envelope=1` request does not contain the `jetpack_subscriptions_subscribe_post_end_enabled ` setting which is causing this error.

It was added here https://github.com/Automattic/jetpack/pull/36381 to the endpoint. Is it not on Atomic yet?

**Comment by pkuliga** [comment]
Ok, now it's there and it works ok. A cache maybe?

**Comment by upwardmomentum84** [comment]
The site in the screenshots is an Atomic test site on the Creator plan. It only has minimal plugins active (Akismet, Jetpack, Gutenberg and WPCOM Editing Toolkit). The newsletter settings seem to be saving now and being applied on the live site (they weren't when I filed the bug report). I'm still seeing the error in Calypso when saving the changes though. The toggles also don't update until you refresh the page.

Here is a screen recording showing the error and some information from the browser dev tools:
https://github.com/Automattic/wp-calypso/assets/93800099/0d75361b-365f-4b81-bd5e-1eac2f9cead4

Here is the XHR Response for `https://public-api.wordpress.com/rest/v1.2/sites/199097935?http_envelope=1`
[XHR-Response.txt](https://github.com/Automattic/wp-calypso/files/14836095/XHR-Response.txt)

**Comment by pkuliga** [comment]
Thanks for it @upwardmomentum84!

Is it the case you have the `public-api.wordpress.com` sandboxed? If yes, I think that could be your sandbox cache not flushed, if not I need to talk to opers since others could also be affected.

**Comment by upwardmomentum84** [comment]
No, it's not sandboxed. I don't even know how to set one of those up :)

**Comment by Aurorum** [comment]
I had a report of this in 8036390-zen in case it helps debug (not sure if it's the same cause though, and I can't submit an API request to Atomic sites!).

**Comment by enejb** [comment]
I am closing this issue since I am not able to replicate it any more. Feel free to open it again if this is not this issue still exist.
