### ISSUE TITLE
Posts: Trashing a post - Slightly weird behaviour - Icons are inconsistent - Button Text misaligned

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#8911]
While trashing a test post I noticed that the icon a couple of things that seemed 'off' with the design...

To see the below points in the app, go to [/posts](http://calypso.localhost:3000/posts)
#### Text + Icon buttons:

<img width="838" alt="screen shot 2016-10-23 at 23 28 01" src="https://cloud.githubusercontent.com/assets/4335450/19626223/6ba8759a-9978-11e6-960a-ef77bae7e32a.png">
- The bottom pink boxes show space from the button edge to the icon (visual).
- The bottom blue boxes show space from the button edge to the copy (visual).
- The top boxes are of equal height to their bottom counter-parts, anchored at the top of the button - these help visualise the off-centre skew.
  I see that vertical-centre alignment has been an issue in other buttons around the site and is why CAPS are used for many buttons... uppercasing here doesn't fix the alignment issue.
#### Inconsistent Trash Icons:

<img width="351" alt="circled-trash-icons" src="https://cloud.githubusercontent.com/assets/4335450/19626336/f815c8b4-997a-11e6-8743-953542a07bef.png">
- The icons circled in green here are Gridicons, with the prop `icon: 'trash'` as defined in [/my-sites/posts/post-controls.jsx](https://github.com/Automattic/wp-calypso/blob/36e5105e2dcc2b747d5808a409636c930c450607/client/my-sites/posts/post-controls.jsx#L158)
- The icon circled blue doesn't seem to be a Gridicon, instead it seems to just be defined pure by class name in [lib/mixins/update-post-status/index.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/lib/mixins/update-post-status/index.jsx#L46)

Also note that the margining between the title and the icon is not in keeping with icons in other areas of the UI:
<img width="106" alt="screen shot 2016-10-23 at 23 44 47" src="https://cloud.githubusercontent.com/assets/4335450/19626501/42ede958-997f-11e6-9a0c-985372a3fdff.png">
### Behaviour

On hitting the 'Trash' post button, a small dialog pops up to show that the trash is being processed... This last for around 1s.  
Then the dialog changes, stating 'Moved to Trash' with an option to 'undo'. Not that at this point the post controls behind the dialog go back to their original state (showing the first options & the '... more' button).
<img width="554" alt="screen shot 2016-10-24 at 00 28 38" src="https://cloud.githubusercontent.com/assets/4335450/19626574/d6bd8da4-9980-11e6-9896-7b924f7c81ef.png">
After a short-while (sometimes up to ~20s actaully) an XHR (looks like 'sites') will land and the post view will update in the background, as so:
<img width="554" alt="screen shot 2016-10-24 at 00 32 43" src="https://cloud.githubusercontent.com/assets/4335450/19626606/6a39a37e-9981-11e6-80ab-6fc60abe4e18.png">
There'll now also be 1 post in 'Trashed':
<img width="554" alt="screen shot 2016-10-24 at 00 34 49" src="https://cloud.githubusercontent.com/assets/4335450/19626629/bf723130-9981-11e6-9e34-e8ff9277337b.png">
When hitting 'undo' to restore the post, a similar process happens, only in reverse.
First the dialog shows 'Updating Post' before hiding.
The post view now looks like this:
<img width="552" alt="screen shot 2016-10-24 at 00 39 32" src="https://cloud.githubusercontent.com/assets/4335450/19626669/5bdb6ad2-9982-11e6-98bd-4bbffa0c4221.png">
Note that since we pressed 'undo' the language here should be different, we shouldn't have the option to 'Delete Permanently' or 'Restore' & that the 'Private' is now missing from the post title.

Also note that there are now 0 'Trashed' posts... It seems that this tab & indicator should just hide now that there are 0 to list...
<img width="553" alt="screen shot 2016-10-24 at 00 40 59" src="https://cloud.githubusercontent.com/assets/4335450/19626675/8f447a26-9982-11e6-835b-63c70c503474.png">

After a few seconds (again this has been up to 20s in some cases, sometimes less) we get another XHR that seems to correct all of the discrepancies:
<img width="552" alt="screen shot 2016-10-24 at 00 43 06" src="https://cloud.githubusercontent.com/assets/4335450/19626692/da5d76d4-9982-11e6-96b6-4601432cbb7f.png">

So far in this journey, waiting for the XHR to update the state does fix the problems. It's far from ideal to have to wait, but at least the user can get right back to using the features as expected.

I have however found one case that blocks the user until they refresh or re-route:
<img width="637" alt="screen shot 2016-10-24 at 00 43 51" src="https://cloud.githubusercontent.com/assets/4335450/19626742/805820d4-9983-11e6-8b1f-df621ebea7ab.png">

Here I clicked 'undo' from the dialog but then also clicked 'Restore' straight after the dialog hid away.
Even after waiting this 'Restored' dialog persists.

I'm happy to split this issue up or create a progress list if either of those would be preferred - This issue ended up larger than expect!
Also happy to start investigating and getting stuck in to some of the fixes. It looks like some of these files along the way could use a lick of es6 too!

**Comment by folletto** [comment]
That whole piece is really really reaaaally old, and has to be redesigned entirely. Everything you pointed out is fairly accurate.

We have an entirely different design planned, similar to custom post types, but I'm not sure on the ETA for that:

<img width="761" alt="screen shot 2016-10-26 at 10 54 55" src="https://cloud.githubusercontent.com/assets/4389/19719535/a5f31450-9b6a-11e6-9de3-f98436530ccd.png">

However, some issues are quite transversal and we could address them with benefits even once that design lands, namely:

> Also note that there are now 0 'Trashed' posts... It seems that this tab & indicator should just hide now that there are 0 to list...

This should be addressed, yes.

As for the others, would be cool to fix these, as I don't know when we get to the new design.

**Comment by nylen** [comment]
This entire section of Calypso has been rewritten and the code/UI referenced in the original report has been removed.  The new code (originally the posts list for custom post types) lives under `client/my-sites/post-type-list` and `client/blocks/post-item`.  The behavior for trashing and restoring may be subject to revision in the future, but for now, trashing and restoring are immediately reflected in the posts list.

It would be good to re-test this behavior in the new posts list and create smaller issues for anything that is still problematic here (for example: alignment; mismatched icons; counts not updating correctly).  For now I am closing this as outdated.
