### ISSUE TITLE
Notification dot is misaligned on smaller screens

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#89113]
## Description

I'm waiting to get an unread notification to test this out, but @niranjan-uma-shankar reported (p1712041586382319-slack-C025Q5RK2):

> The unread notification circle is not aligned in <783px screen width.

![Image](https://github.com/Automattic/wp-calypso/assets/5634774/2226deb1-4b23-42d3-9d4c-d08a0e52d4ca)

**Comment by davemart-in** [comment]
@niranjan-uma-shankar I'm not able to replicate this on Chrome. What browser are you using? Here's what i'm seeing:

https://github.com/Automattic/wp-calypso/assets/5634774/bfeed630-351b-44ca-a5b0-3bc2f2b87816

**Comment by niranjan-uma-shankar** [comment]
Interesting, I am using Chrome. Looks like this misalignment happens only when I'm on a site, not when I'm in Calypso.


https://github.com/Automattic/wp-calypso/assets/1269602/82dfa53f-8038-4994-bc7f-fd70e38d7b4c

**Comment by Addison-Stavlo** [comment]
cc @eoigal - I think your recent changes around D141499-code and D142671-code are bleeding into unexpected areas.

It sems the `top: 2px; left: 23%;` are the culprits in this case. removing them fixes the issue here, but then the placement is off on the atomic sites admin bars we were updating.

**Comment by Addison-Stavlo** [comment]
I think D144064-code should resolve the issue.

**Comment by niranjan-uma-shankar** [comment]
Thanks @Addison-Stavlo!
