### ISSUE TITLE
Themes: searching then selecting "Premium" themes partially hides the select list

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#8912]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/
2. Search for a theme eg 'magazine'
3. Select "Premium" in the theme type list

#### What I expected

Select list to remain fully displayed

#### What happened instead

The right hand side of the select list is lost: 

<img width="236" alt="screen shot 2016-10-24 at 9 52 52 am" src="https://cloud.githubusercontent.com/assets/128826/19630528/b319a816-99cf-11e6-8d7d-07a8e42fe458.png">

#### Browser / OS version

Chrome Version 53.0.2785.143 (64-bit) OSX 10.12

#### Screenshot / Video

![theme premium select](https://cloud.githubusercontent.com/assets/128826/19630524/9fe9fd86-99cf-11e6-98f7-c23919be8141.gif)

#### Context / Source
#manual-testing

**Comment by budzanowski** [comment]
@alisterscott We will shortly switch to our new design that does not have this problem. You can check it out already at wpcalypso.

**Comment by lancewillett** [comment]
Closing as will be replaced soon.
