### ISSUE TITLE
Themes: selecting "All" again after another selection loses word "All"

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#8913]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/
2. Select a theme category (eg. Free)
3. Select "All"

#### What I expected

Select list displays "All"

#### What happened instead

Select list is empty. Selecting "All" again shows "All"

#### Browser / OS version

Chrome Version 53.0.2785.143 (64-bit) on OSX 10.12

#### Screenshot / Video

![theme all](https://cloud.githubusercontent.com/assets/128826/19630569/587905b8-99d0-11e6-9160-def0bff044da.gif)

#### Context / Source
 #manual-testing

**Comment by brunoscopelliti** [comment]
Hi there,

I'm new to the codebase... and this seemed a pretty good bug to get started, so I investigated a little the issue.

The behaviour is implemented in the `select-dropdown` component... I think it should be used diffusely.

Apparently, when you change the selection the info about the selection is stored by the router (am i right?). So when you change it back it is lost.

I've a pull request that fixes the issue, and passes the tests... @alisterscott Do you mind to review it?

**Comment by budzanowski** [comment]
@alisterscott Same like with #8912 this will be shortly replaced with new design already visible at wpcalypso.

**Comment by designsimply** [comment]
@brunoscopelliti, thanks for submitting a PR! Looks like an update was already in the works, but you should check out the [[Type] Good First Change](https://github.com/Automattic/wp-calypso/labels/%5BType%5D%20Good%20First%20Change) if you haven't already seen it. :)

**Comment by brunoscopelliti** [comment]
@designsimply Thank you for the suggestion.

When I started investigate this issue, I had no idea that I would end up to submit a pr... I just wanted to debug a bit through the codebase, and this issue seemed a good starting point 😄 
Sorry if I caused someone to do extra work... I'll check the issues "[Type] Good First Change" more often.
