### ISSUE TITLE
Themes: activating 'Currents' theme crashes Calypso

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#8914]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design
2. Choose 'Currents' theme and activate it

#### What I expected

Theme to be activated

#### What happened instead

Calypso crashes with 'There was a problem fetching the themes' error

Note: this theme isn't currently displayed in theme showcases, but it is in wp-admin themes (THX) and it activates there okay

#### Browser / OS version

Chrome OSX latest

#### Screenshot / Video

<img width="1405" alt="activating currents calypso" src="https://cloud.githubusercontent.com/assets/128826/19633416/c72851a2-99f4-11e6-86d7-724742a6cf4c.png">

#### Context / Source
#manual-testing

**Comment by folletto** [comment]
Were you on a plan? Because it's a Premium Theme, so you shouldn't be able to just activate it. Can you add more details about the configuration you started from, and if there was any error in the console?

**Comment by folletto** [comment]
Ok so it's likely connected to the Premium Squared partial test. :)

**Comment by budzanowski** [comment]
This looks like #8851 
Currents theme was retired on 2015-09-01.

**Comment by alisterscott** [comment]
Closing as this is being tracked in #8851 where I left a comment about this theme
