### ISSUE TITLE
Login: Offer typo correction

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#89172]
### Details

In signup, we offer typo correction on the domain:

![image](https://github.com/Automattic/wp-calypso/assets/52076348/93f03b5f-48bf-4b16-aa53-495a0bea5557)

Let's do the same thing in login!

![image](https://github.com/Automattic/wp-calypso/assets/52076348/a5468472-891b-4a0a-b542-a0651619e7a8)

**Comment by agrullon95** [comment]
Typo correction suggestion logic has been added to the login page in: https://github.com/Automattic/wp-calypso/pull/89189
