### ISSUE TITLE
Blog Posts block not respecting the "Shape" options on Simple Sites

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#89180]
### Quick summary

7987001-zd-a8c User reported in this chat that they noticed that their featured images were not all the same size/shape all of a sudden. I checked and found that this appears to be affecting all Simple sites regardless of the theme (could not reproduce on an AT site).

### Steps to reproduce

1. Add the Blog Posts block to a page
2. Try to change the shape of the Featured Images

### What you expected to happen

The size/shape of the images should change.

### What actually happened

The settings don't change the size/shape at all:

(Direct link to Droplr GIF here since it's too large to embed) - [d.pr/i/205MIX](d.pr/i/205MIX)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Having them switch to the Query Loop block is the best option for now until this gets resolved.

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 

📌 ACTIONS
- Triaged

**Comment by jartes** [comment]
Closing as it's no longer replicable: 

https://github.com/user-attachments/assets/49c4720a-027e-4a97-a232-6eade32a5322
