### ISSUE TITLE
Typo on subscribe.wordpress.com

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#8921]
#### Steps to reproduce
1. Starting at URL: subscribe.wordpress.com
2. Go to the site while logged out
3. Look in the Activate Your Subscription area
4. Note that there is an extra "p" in the word "opposite."

We'd also love to know how you found the bug: #user-report

[WordPress-typo.pdf](https://github.com/Automattic/wp-calypso/files/548082/WordPress-typo.pdf)

**Comment by beaulebens** [comment]
Fixed in r144328-wpcom
