### ISSUE TITLE
Site Migration: Automatically add hosting plan after user verifying email account

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#89254]
Email verification as a requirement for Free trials has been implemented in https://github.com/Automattic/wp-calypso/pull/89178. This issue is to track an improvement to be made, since right now the flow goes like this:
1. User with unverified account selects `Free trial`
2. Gets redirected to a waiting screen until the user clicks on the verify button in the email
3. The screen automatically redirects to the upgrade plan screen after verifying
4. The user needs to click on the `Free trial` again

A possible improvement would be to automatically [add the free hosting plan](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/importer/wordpress/upgrade-plan/index.tsx#L70) after the user verified the account.

**Comment by markbiek** [comment]
Based on this recent feedback: p1712759574962479-slack-C0Q664T29

It might be worth seeing if it's possible to have the verification link in the email redirect the user back into the migration flow.

**Comment by sixhours** [comment]
Added this step in https://github.com/Automattic/wp-calypso/pull/89417 and tests in https://github.com/Automattic/wp-calypso/pull/89540, closing.
