### ISSUE TITLE
Stats: Devices - Explore using Calypso pie chart and an external library

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#89302]
While we wait for the API endpoint, we can explore adding a pie chart to the new widget.
Explore using a pie chart from the existing Calypso component library and adding a new chart package. Consider the impact on the bundle size. The previous exploration might be useful PejTkB-sk-p2

<img width="505" alt="截圖 2024-04-11 上午1 48 27" src="https://github.com/Automattic/wp-calypso/assets/6869813/b78b53b1-7747-4bb3-a5b0-81185fcb57a0">

<img width="829" alt="截圖 2024-04-11 上午1 48 18" src="https://github.com/Automattic/wp-calypso/assets/6869813/e602658b-7e45-4ac6-be84-3d5afdf24bb8">

**Comment by dognose24** [comment]
The existing [PieChart](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/pie-chart/index.js) and [PieChartLegend](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/pie-chart/legend.js) components work well in line with the design.

<img width="648" alt="截圖 2024-04-11 上午1 40 52" src="https://github.com/Automattic/wp-calypso/assets/6869813/0608b790-ddc6-4032-bc2f-0889890676eb">

However, we don't have the tooltip to interact with the donut chart. I am still looking for a design-like library. Or implementing the tooltip interaction as the [LineChart](https://github.com/Automattic/wp-calypso/blob/ffc1d656ed906dc48efa3227d99294d5d6b2b5f8/client/components/line-chart/index.js#L205) component would also be a viable idea.
