### ISSUE TITLE
Import Content from Another Platform Screen Doesn't Include Wix as an Option

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#89323]
### Quick summary

The Import Content from Another Platform Screen Doesn't Include Wix as an Option

![image](https://github.com/Automattic/wp-calypso/assets/98869/801d2fdf-122b-497a-8b95-eef72be5fe35)

### Steps to reproduce

1. Start at https://wordpress.com/setup/import-focused/import?siteSlug=
2. Click "choose a content platform"
3. The list of platforms to import from doesn't include Wix

### What you expected to happen

I expected to see Wix as an option, because it is option in Tools > Import: 

https://wordpress.com/import/

### What actually happened

There isn't an option to import from Wix.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

@inaikem

**Comment by inaikem** [comment]
Hi @Automattic/caribou 👋 Are you still the most appropriate team to ping on these importer issues?

**Comment by zaerl** [comment]
> Hi @Automattic/caribou 👋 Are you still the most appropriate team to ping on these importer issues?

Yes, it has already been discussed here: p1712587233773969-slack-C01A60HCGUA

**Comment by inaikem** [comment]
Perfect, thanks! Want me to close this in favour of another open issue on your board?

**Comment by zaerl** [comment]
> Perfect, thanks! Want me to close this in favour of another open issue on your board?

Yes, please, put a backlink here in the close comment.

**Comment by inaikem** [comment]
Sure. Do you have a URL for the issue you want referenced?

**Comment by bogiii** [comment]
I don't remember 100%, but we hid the Wix importer from the list for a reason.

The entry point for the Wix importer is a Capture screen. You enter the valid Wix URL, which will lead you to the Wix importer (the valid Wix URL is required). If we add a Wix to the list of importers, the CTA will be redirected to the Capture screen, which will be a loop.

@javierarce, do you remember any details about the decisions here?

**The capture screen:**
<img width="625" alt="Screenshot 2024-04-10 at 11 15 23" src="https://github.com/Automattic/wp-calypso/assets/1241413/110f0c2d-2338-4ce2-a7db-d66b7c17d874">

**Comment by druesome** [comment]
> You enter the valid Wix URL, which will lead you to the Wix importer (the valid Wix URL is required). If we add a Wix to the list of importers, the CTA will be redirected to the Capture screen, which will be a loop.

@bogiii fwiw, entering URLs from Blogspot, Medium and Squarespace in the capture screen also leads us to their respective importers.

**Comment by Robertght** [comment]
While reviewing the recent Wix Importer related reports, I found this.

@bogiii is this still relevant or it is ok to close it?

**Comment by bogiii** [comment]
I think that it is ok to close it. Thanks!
