### ISSUE TITLE
Bug: Email stats should be sorted descending

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#89338]
the Emails section may be sorted ascending instead of descending (5144 opens at top, 5977 at bottom; should be reversed)

![Image](https://github.com/Automattic/wp-calypso/assets/1425433/92628dea-88e5-4314-86fe-8a569ed45cc0)

Reported: p1711997198566049-slack-C0438NHCLSY

cc @Automattic/apex

**Comment by ivan-ottinger** [comment]
Hey @kangzj 👋🏼 Thanks for the ping.

Looking at the stats at https://wordpress.com/stats/day/, they are displaying based on the `post_id`. The `sort_order` is set to `desc`. In most cases, this should make the newest email (latest post) displayed on the top.

In other words, the emails are not being sorted by number of opens or clicks at the moment.

To me, this matches with the stat heading of "Latest Emails". But maybe I misunderstood your point. 🤔

**Comment by kangzj** [comment]
@jsnmoon it seems to be intended 😀

**Comment by dognose24** [comment]
This issue should be addressed by https://github.com/Automattic/wp-calypso/pull/90324.
