### ISSUE TITLE
Email: show "No plugins to update" when there are no plugins to update

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#89348]
Context: p1712646760413159/1712646516.193049-slack-C01A60HCGUA

**Comment by TimBroddin** [comment]
Not needed, as no update is performed when there are no plugins to update.

https://github.com/Automattic/jetpack/blob/trunk/projects/packages/scheduled-updates/src/class-scheduled-updates.php#L76-L85

**Comment by TimBroddin** [comment]
If needed in the future, here's a diff that does it: D144760-code

**Comment by obenland** [comment]
I don't think sending an email after nothing happened provides much value. That's what the Last Updated column in the UI is for.

**Comment by TimBroddin** [comment]
We aren't sending an email when nothing has happened, [if there's nothing to update we return early](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/scheduled-updates/src/class-scheduled-updates.php#L76-L85). 

We're seeing these mails in our testing because we bypass this check when using @zaerl's CLI command.
