### ISSUE TITLE
Unexpected redirect to https://wordpress.com/nullsite-editor.php when clicking "Edit" for the active theme

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#89399]
### Quick summary

On a Simple site as a super admin, clicking "Edit" on the active block theme redirects you to `https://wordpress.com/nullsite-editor.php`.

![CleanShot 2024-04-10 at 03 45 10@2x](https://github.com/Automattic/wp-calypso/assets/36432/3e31bd9a-59ca-4a9c-bfdc-58337caf6dd2)

### Steps to reproduce

1. Visit https://daniela8cgmailtest.wordpress.com/wp-admin/themes.php as a super admin
2. Click on "Edit"

### What you expected to happen

I expected to end up on `https://daniela8cgmailtest.wordpress.com/wp-admin/site-editor.php`

### What actually happened

I ended up on `https://wordpress.com/nullsite-editor.php`

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by danielbachhuber** [comment]
A side effect of D88732-code

Asked in Slack p1712746536408039-slack-C06DN6QQVAQ

**Comment by Addison-Stavlo** [comment]
potential fix at D144925-code

**Comment by danielbachhuber** [comment]
🔨
