### ISSUE TITLE
WooCommerce Theme: Kiosko

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#89441]
### Details

The Kiosko WooCommerce theme documented in pNEWy-ggT-p2 needs the following:

### Checklist

- [x] Set up the demo site (https://kioskodemo.wpcomstaging.com/)
- [x] Theme showcase draft
- [x] Soft-launch the theme
- [x] Build a ZIP for the theme
- [x] Headstart annotations (don't forget to submit for translation) (Strand ID: 240060)
- [x] GlotPress Project creation
- [x] Launch the theme to users

**Comment by markbiek** [comment]
Soft launch diff: D146916-code

**Comment by markbiek** [comment]
Headstart diff: D146925-code

**Comment by markbiek** [comment]
@alaczek I think everything is done at this point. To be safe, I went ahead and soft-launched the theme.

Please let me know if you'd like me to remove it from the soft-launch list so it's fully available to everyone.

**Comment by alaczek** [comment]
Yep, I think so. I can't think of anything else.

**Comment by markbiek** [comment]
We're fully launched!
