### ISSUE TITLE
Editor: cursor positioning on Chrome for iOS is tricky

### ISSUE THREAD

**Issue by rosswintle** [Automattic/wp-calypso#895]
This may well be a Chrome for iOS bug rather than a Calypso bug, but thought it was worth reporting. I do NOT see the same behaviour in Safari.

URL: https://wordpress.com/post/<blog_url>/<post_id>

What I expected: To be able to use touch to successfully position the cursor within the editing box

Steps to reproduce: Open a post for editing in Chrome for iOS. Tap in the edit box to try to position the cursor.

What happened instead: Cursor doesn't seem to want to position itself anywhere on the right hand side of the screen. If I tap in the right-hand 50% of the screen the cursor seems to position itself at around half way across the screen. If I tap on the left-hand side of the screen then it works fine. This happens in both portrait and landscape on an iPad Air 2 running up-to-date Chrome browser on iOS 9.1

I'll try to add an annotated screen grab for you.

**Comment by rosswintle** [comment]
Annotated screen grab:

![wordpressdotcom-ipad-cursor](https://cloud.githubusercontent.com/assets/1532368/11444812/de2cc3f0-951e-11e5-88a8-4b5a2e15b946.jpg)

**Comment by lancewillett** [comment]
Thanks for the report. We haven't been able to replicate it, so closing for now.
