### ISSUE TITLE
User Totals Not Displayed Correctly - Updated as Page Loads

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#89506]
### Quick summary

On Simple Sites, in Users > All Users the site administrators can view the number of users registered to the site. This is displayed as "Team X" at the top of the page, where X is the total number of registered users. Below this is a complete listing of all registered users, in an infinitely scrolling list. Above this list, it says "You have Y team members," where Y is the total number of users that have been loaded into the infinitely scrolling list. The number Y should be the same as the number X, whether or not the entire list of users has been loaded by scrolling to the very bottom.

![Annotation on 2024-04-12 at 17-16-56](https://github.com/Automattic/wp-calypso/assets/12906034/91270575-d33b-48c6-a5d3-8ef47e35fc05)

### Steps to reproduce

1. Upload more than 100 users to a Simple site. (Probably 120 should be sufficient)
2. Go to Users > All Users
3. Observe that the number of team members does not match the total number of users until scrolling to the bottom of the list of users.

### What you expected to happen

The total number of users should be consistent.

### What actually happened

The total number of users is inconsistent.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Not tested on Atomic sites.

Workaround is to scroll to the bottom of the page when viewing all users, or to only use the number at the very top of the page.

**Comment by masperber** [comment]
7978970-zen Initial customer report.

I've reproduced the issue on another site with over 100 users.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I didn't have a safe user list to import to test it on my site, but I was able to reproduce the behaviour on the user site and a large P2 like dotcomhappy

![CleanShot 2024-04-25 at 10 40 55@2x](https://github.com/Automattic/wp-calypso/assets/14153300/2fa31e6b-bd88-45a5-921c-5982dedb746d)

📌 ACTIONS
- Triaged

@Automattic/apex is this something you can look into based on your work in the Subscribers page last year?

**Comment by ivan-ottinger** [comment]
Thanks for the ping, @liviopv.

Looks like the issue was unintentionally introduced by this PR: https://github.com/Automattic/wp-calypso/pull/88369.

The following change should fix it, but I think it would be better if @renancarvalho (👋🏼🙂 Hi!) could take a closer look - since the proposed fix may potentially cause some other regression to the changes introduced in the PR (that I may be unaware of). 

```diff
diff --git a/client/my-sites/people/team-members/index.tsx b/client/my-sites/people/team-members/index.tsx
index fe5614fc31..f7384b0c68 100644
--- a/client/my-sites/people/team-members/index.tsx
+++ b/client/my-sites/people/team-members/index.tsx
@@ -55,7 +55,7 @@ function TeamMembers( props: Props ) {
 		( obj ) => obj.linked_user_ID === false
 	);
 
-	const membersTotal = nonPendingMembersSorted.length;
+	const membersTotal = data?.total;
 	const addTeamMemberLink = `/people/new/${ site?.slug }`;
 
 	function getPersonRef( user: Member ) {
```

**Comment by rinazrina** [comment]
Another user was confused with this: 8318410-zd-a8c

The Users page shows, "You have 100 team members" even though they have 600+ users.

**Comment by renancarvalho** [comment]
This issue is being handled [here](https://github.com/Automattic/wp-calypso/pull/95085)

🙇
