### ISSUE TITLE
Plans Next [Storybook]: improve the data mocking mechanism.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#89526]
This issue is extracted from the discussion in https://github.com/Automattic/wp-calypso/pull/89430#pullrequestreview-2000357128.

Currently, we are using static mocking data which presents several potential issues:

1. It's fragile to any structural change, since the change will need to be maintained manually onto the static mocking data.
2. The `useGridPlans` hook in particular is not really used in Storybook, presenting a huge gap between production.

We should explore ways to close these gaps as much as possible, e.g. mocking the API requests or other more full-scale implementation like @chriskmnds raised in the above linked thread.

**Comment by chriskmnds** [comment]
I too agree on this. It should be easy to test things directly in Storybook. Right now, I'm not sure I see it being more than "something to fix in the end", at least for bigger changes. It might be worth to seek out some recommended practises, what's available in terms of practice for mocking, etc.

**Comment by oswian** [comment]
👍  We could use something like [msw-storybook-addon](https://storybook.js.org/addons/msw-storybook-addon) to mock API requests in stories. I have used this previously and it seemed to work well. Approach is basically:

```ts
import { http, HttpResponse } from 'msw';
import sitePlans from 'fixtures/site-plans.json';

const meta: Meta< typeof FeaturesGrid > = {
   ...
   msw: {
      handlers: [
        http.get('https://public-api.wordpress.com/rest/v1.3/sites/[:id]/plans', () => {
          return HttpResponse.json(sitePlans);
        }),
      ],
    }

```
