### ISSUE TITLE
Email Verification: Changing email address if not already verified is not possible

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#8952]
The current email verification gate suggests that the user either:

1) Verify their email address
2) Change their email address

If you click the "change the email address on your account" link, you are taking to `/me/account`, which does not allow you to change your email address if you're not verified. This is a broken flow.

![screen shot 2016-10-25 at 3 32 28 pm](https://cloud.githubusercontent.com/assets/1126811/19703202/9367ad3e-9ac8-11e6-8808-dc9ed6d11b3e.png)

![screen shot 2016-10-25 at 3 32 32 pm](https://cloud.githubusercontent.com/assets/1126811/19703210/960807f0-9ac8-11e6-863d-123210222d1b.png)

**Comment by lsinger** [comment]
> you are taken to `/me/account`, which does not allow you to change your email address if you're not verified

@ebinnion I just tried to reproduce and was able to change my email address without problems. Can you give me further instructions to reproduce?

**Comment by ebinnion** [comment]
Hrm, perhaps it was fixed or I misunderstood the issue when I reported. I'll close for now.
