### ISSUE TITLE
Feedback: Calrify "site migration instructions step 1"

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#89521]
### Quick summary

Step 1 currently reads:

> Install and activate the [Migrate Guru plugin](https://wordpress.com/wp-admin/plugin-install.php?s=%2522migrate%2520guru%2522&tab=search&type=term) on your existing site. 

<br>

This could be clearer. The "existing site" text can easily be confused with the source site being imported from, which makes step 2 more confusing.

<br>

**Suggestion:** 

> Install and activate the [Migrate Guru plugin](https://wordpress.com/wp-admin/plugin-install.php?s=%2522migrate%2520guru%2522&tab=search&type=term) on the WordPress.com site you want to migrate content to.

### Steps to reproduce

Enter the migration flow and land at: https://wordpress.com/setup/site-migration/site-migration-instructions

### What you expected to happen

N/A

### What actually happened

N/A

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by sixhours** [comment]
> Install and activate the [Migrate Guru plugin](https://wordpress.com/wp-admin/plugin-install.php?s=%2522migrate%2520guru%2522&tab=search&type=term) on the WordPress.com site you want to migrate content to.

👋 Thanks for giving this flow a run-through!

We automatically install and activate Migrate Guru on the WordPress.com site they will be migrating to, so the above change would be incorrect. We need the user to install Migrate Guru on their old site (or "existing site" in the current copy, the site we don't have access to).

I know it's confusing as to which site is which. :-/ Let me know if I'm misunderstanding the issue here or if you have other suggestions for clarity!

**Comment by inaikem** [comment]
AHA, thanks! Ok, this is what tripped me up. I'll lay out the steps on the migration instructions page:

1. Install and activate the [Migrate Guru plugin](#) on your existing site.
2. Go to the [Migrate Guru page on your source site](#), enter your email address, and click Migrate.
3. When asked to select a destination host, pick WordPress.com.
4. Copy and paste the migration key below in the Migrate Guru Migration key field and click Migrate.

I'd like to propose the following update to step 1:

1. Install and activate the [Migrate Guru plugin](#) on your source site.

How does that sound?

**Comment by sixhours** [comment]
Just noting this is similar in concept to https://github.com/Automattic/wp-calypso/issues/89765 so linking to it here.
