### ISSUE TITLE
Reader: Newsletter Paywall Copy Displays HTML Markup

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#89555]
### Quick summary

When viewing paid Newsletter posts in the Reader as a free subscriber, the paywall copy is showing HTML markup.

![CleanShot 2024-04-15 at 17 27 24@2x](https://github.com/Automattic/wp-calypso/assets/42279181/ec426221-9571-4ee1-a72b-46643eabb14d)

```
font-family: ‘SF Pro Text’, sans-serif; line-height: 28.8px;”> You're currently a free subscriber. Upgrade your subscription to get access to the rest of this post and other paid-subscriber only content.
```

### Steps to reproduce

1. Subscribe to a site with paid content as a free subscriber.
2. View a post with the paywall block in the Reader.

### What you expected to happen

To see the copy and button for upgrading.

### What actually happened

The copy displays, but includes HTML markup.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Observed on an Atomic site.

**Comment by katiebethbrown** [comment]
Addtl notes:
p1713224293747489/1711651527.736909-slack-C053A0D3WGK

**Comment by katiebethbrown** [comment]
The same copy is also showing in the post notification emails for free subscribers.

![CleanShot 2024-04-16 at 17 48 47@2x](https://github.com/Automattic/wp-calypso/assets/42279181/97c441c8-7877-4ea1-8ef8-48fb10663e63)

**Comment by Aurorum** [comment]
Automattic/jetpack#36912 should take care of both scenarios. :)
