### ISSUE TITLE
BE: implement function/class to decide on who to notify

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#89570]
Takes succes/failure status and returns a list of emails/users to notify. Needs to take into account to only return users that have the `update_plugins` cap.

**Comment by TimBroddin** [comment]
This will also need to add a `user_can( $user_id, $capability)` function to the shadowstore. See p1713338355411189/1713336861.530469-slack-C01A60HCGUA

**Comment by ouikhuan** [comment]
Done in D145696-code
