### ISSUE TITLE
Bug: Site migration instructions page is not using the site root

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#89586]
## Steps to Reproduce
- Create a JN site for testing purposes
- Create and publish a new page   (or use the JN sample page like https://interim-starfish-starlight.jurassic.ninja/sample-page/)
- Follow the migration flow until reach the `Where will you import from?` 
- Set the published page on the field `Enter the URL of the site:`
- Continue the flow until reach the instructions page
- Check the links in steps 1 and step 2 to see if the links are using the page URL instead of the site URL.

## What is expected?
- We should see the correct links

## What is happening?
- The links are using the same path the user set on the `Enter the URL of the site:`, instead of the WordPress root installation

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on JN/Atomic – Replicated

Replicated. The URL links go to the page, rather than the main domain name.
I couldn't login once I got to step 1/2.

## 📌 ACTIONS ##
Triaged

**Comment by nelsonec87** [comment]
Related diff D148565-code
