### ISSUE TITLE
Import-hosted-site: User can't  back to goals step when they see the importReadyNot step.

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#89619]
### Quick summary

https://github.com/Automattic/wp-calypso/assets/38718/651c37f7-6935-4967-85a4-602a20d92c1d

### Steps to reproduce

1. Start the `setup/import-hosted-site/` flow
2. Set a non-WordPress site on the field 'Enter the URL of the site:'
3. Click `Continue`
4. On the screen `Your existing content can't be imported` click on `Back to goals`

### What you expected to happen

The user should be redirected to the goals screen

### What actually happened

The user is stuck on the `importReadyNot`

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

More context p1713358201887019-slack-C0Q664T29

**Comment by andres-blanco** [comment]
Moving this to the Site Migration i2 tab where we are creating a flow to replac the one referenced in this issue.
We should make sure that the bug is not present in the new flow.
Refs:
* Project thread: paYKcK-4BA-p2

**Comment by sixhours** [comment]
In the new flow(s), putting in a non-WP.com URL brings you to the import from another platform screen:

<img width="1505" alt="Screenshot 2024-05-22 at 12 23 23 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/a488795a-3da6-4b51-a580-c2782ab8b639">

From there you can go back to the step where you put in your URL. You can also go back to the goals step from the step where you put in the URL.

I'll go through both `/setup/site-migration` and `/setup/hosted-site-migration` flows and check back links throughout but I think we can consider this fixed.
