### ISSUE TITLE
Audio Blocks not working correctly on Simple Sites

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#89632]
### Quick summary

A user reported that their audio blocks weren't working all of a sudden - I was able to replicate the issue across browsers and on a test site, but AT sites appear to be unaffected.

### Steps to reproduce

1. Add an audio block to a page on a Simple Site (this also includes using the audio shortcodes while using the `Classic Editor` block)
2. Open the page and check to see if the audio will play

### What you expected to happen

The audio should play

### What actually happened

The block is unresponsive and doesn't play audio at all.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by ClassicRKR27** [comment]
Initial user report here: 8057759-zd-a8c

**Comment by tellisbethel** [comment]
Another report here: 8057900-zd-a8c (Edit: Not sure why this shorthand link isn't resolving properly.)
This user noted that the original file URL has the site.files.wordpress.com format, but now when they attempt to access that link directly, it redirects to a /wp-content/uploads/ link that 404s.

**Comment by ezebecke** [comment]
8057994-zd

**Comment by jp-imagines** [comment]
Escalating here: p1713377394024169-slack-C02FMH4G8

> This user noted that the original file URL has the site.files.wordpress.com format, but now when they attempt to access that link directly, it redirects to a /wp-content/uploads/ link that 404s.

That is expected – see p58i-gPS-p2.

**Comment by upwardmomentum84** [comment]
Another report: 8057999-zd-a8c

**Comment by devicenull** [comment]
This has been fixed - was limited to just audio

**Comment by taipeicoder** [comment]
From the comment above, this seems to be fixed already.
