### ISSUE TITLE
Task: Store the source domain for incoming Migrate Guru migrations

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#89649]
### Details

The current back end code for tracking migrations doesn't have a way to store the domain for the source site for a transfer. This makes it harder for us to show relevant, contextual information about the transfer to users, because we don't have the source site details available to us. 

### Checklist

- [x] Build a way to store the source domain for incoming Migrate Guru migrations 
- [x] Ensure that the source domain is stored when we detect an incoming migration
- [ ] Ensure that we show the source domain in the migration-in-progress page

**Comment by daledupreez** [comment]
From a technical perspective, we may want to modify the underlying table to add a new column, or we may want to add a new meta table for this kind of data. We may also want to add a way to store which tool is being used for the migration.

**Comment by nelsonec87** [comment]
These are related PRs:

https://github.com/Automattic/jetpack/pull/37060
https://github.com/Automattic/wp-calypso/pull/89866

**Comment by markbiek** [comment]
@nelsonec87 @daledupreez Can we close this?

**Comment by markbiek** [comment]
> Ensure that we show the source domain in the migration-in-progress page

@daledupreez @nelsonec87 Is this something we still want to do? If so, can someone give me any more context?

**Comment by markbiek** [comment]
I don't think there's any thing to at the moment so I'm closing this. Feel free to reopen if I'm mistaken.
