### ISSUE TITLE
Support: Switching selected sites doesn't update Contact Us site selector

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#8964]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Click My Sites
3. Note selected site
4. Click Help in sidebar footer
5. Click Contact Us
6. Click My Sites
7. Switch site
8. Repeat steps 3-5
#### What I expected

The site selector is set to the site noted in step 8.
#### What happened instead

The site selector is set to the site noted in step 3.
#### Browser / OS version

Chrome Version 54.0.2840.71 (64-bit)
macOS 10.12.1 (16B2555)
#### Context

Originally observed at https://github.com/Automattic/wp-calypso/pull/8281#issuecomment-256450414

cc @tyxla

**Comment by rachelmcr** [comment]
#bug-scrub

I tested using the steps provided and can no longer reproduce the issue; the site selector is set to the site notes in step 8. Closing as resolved.
