### ISSUE TITLE
Stats: Devices - Empty state for Size

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#89669]
Let's updat e the empty state for the Size tab.

Current state:
![Image](https://github.com/Automattic/wp-calypso/assets/112354940/141e836d-785f-4da9-aff1-2b9950ea2c3f)

**Comment by dognose24** [comment]
This issue has been addressed in https://github.com/Automattic/wp-calypso/pull/89660.

**Comment by grzegorz-cp** [comment]
Thanks for solving it. I had this issues when testing the ticket but I can't reproduce it now.
