### ISSUE TITLE
Page break block breaks styling on all pages except the first

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#89719]
### Quick summary

When using the page break block the user found that the width limit of the column blocks they added to all the blocks was only applied on the blocks that were displayed on the first page. Blocks displayed after the page break do not use full width and are not stacked correctly even though the same styling was added to those blocks in the editor. 

### Steps to reproduce

Create a page
Add content inside the columns block, in this case: 2 columns, image on the left, Title + text + link in the right column. 
Add page break between the different columns
The width and the stacking of the columns was only displayed correctly on the blocks that displayed before the page break. 

### What you expected to happen

I'd expect the content after the page break to use the same width and stacking as the blocks before the page break. 

Blocks before the page break:
![Markup on 2024-04-21 at 10:55:40](https://github.com/Automattic/wp-calypso/assets/5507879/e1c491bb-8150-4493-967c-d99bfe84c346)

Blocks after the page break: 
![Markup on 2024-04-21 at 10:56:04](https://github.com/Automattic/wp-calypso/assets/5507879/352e203d-ad7c-454a-896d-06b1c9bac4cd)

### What actually happened

The columns width and stacking is not applied on blocks after the page break. 

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested it on my test site with Twenty Twenty-Four and I can replicate the exact issue. 

Suggested the user to use the Query loop block with page breaks instead of custom blocks and page breaks.

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple as per the original instructions  

## 📌 ACTIONS ##
- Closed as could not replicate (please reopen if the issue reoccurs) 

Thanks so much for the report. I couldn't replicate the issue with the same set up. Are you still able to produce this on a number of sites? Feel free to reopen if you can still replicate.
