### ISSUE TITLE
Give users the option to toggle off default patterns OR make My Patterns more bold. 

### ISSUE THREAD

**Issue by kimclow** [Automattic/wp-calypso#89720]
### What

Give user the option to toggle off and on the default WordPress.com patterns in the Editor, or make the "My Patterns" option more prominent.

### Why

When users create their own patterns, they get a bit lost in the full list of other patterns that exist. It would be nice for them to only be able to see their specific ones (especially if their site has been built by an agency, and an entire library of patterns for their site may exist). I fully recognise there is the "My Patterns" option in the dashboard, but I think we can push this further. 

### How

I think it should be a toggle that's easily accessible to change in the page settings.

**Comment by liviopv** [comment]
@kimclowa8c I think what you're looking for is the same as this feature request https://github.com/Automattic/wp-calypso/issues/88027 - can you check and confirm?

@miksansegundo shared a snippet in that issue that will hide theme/Dotcom patterns from the list as well, which might come in handy for some of 51's clients while a dashboard control is not implemented.

**Comment by kimclow** [comment]
Hey @liviopv  - thanks for sharing #88027. I was actually thinking this should be for the site owner to do in Calypso or WP Admin (not just for developers). I'm aware that there are existing ways for developers to hide the patterns using code snippets however my thought was more for the site owner :-)

**Comment by liviopv** [comment]
>  I was actually thinking this should be for the site owner to do in Calypso or WP Admin

@kimclowa8c that's exactly the request I made on https://github.com/Automattic/wp-calypso/issues/88027 so I'm closing this as duplicate.
