### ISSUE TITLE
Checkout: Plan upsell for domains sometimes incorrectly says that the plan can be purchased at "no extra cost"

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#89768]
### Quick summary

Sometimes, if you have a domain in your cart, the plan upsell in the checkout sidebar says you can upgrade at "no extra cost", even when that's not true (the plan costs $48 so the upgrade cost shown below should actually be $43.16):

![plan-upsell](https://github.com/Automattic/wp-calypso/assets/235183/783a0f45-5bb7-4248-82ae-f0bfe1b60f93)

The root cause is that this `getPlanPrice()` call returns `null`: https://github.com/Automattic/wp-calypso/blob/c428208ca12a454155fac66c4b4a6df1c0bde0ec/client/my-sites/checkout/cart/cart-free-user-plan-upsell.tsx#L188

Which in turn requires two fixes:
- A fix for the underlying bug. @sirbrillig thinks it may be a side effect of https://github.com/Automattic/wp-calypso/pull/87540 and that this upsell component needs to be updated to actually fetch the plan data it needs, rather than assuming Calypso already has it.
- The component should be more robust.  Currently it uses the "no extra cost" wording as a fallback when it can't figure out what's going on: https://github.com/Automattic/wp-calypso/blob/c428208ca12a454155fac66c4b4a6df1c0bde0ec/client/my-sites/checkout/cart/cart-free-user-plan-upsell.tsx#L106-L115 Instead it should only use that wording when it's confident that there's actually no extra cost.  If it doesn't have the data it needs, it should probably just not show the upsell at all instead.

### Steps to reproduce

Originally reported here: p1713798200733949-slack-C0117V2PCAE

It is currently reproducible with the specific customer account mentioned there.  I was also able to reproduce it with my own account, although not always.  (The basic reproduction steps are to put a domain in your cart on an existing site that doesn't yet have a plan.)

### What you expected to happen

The correct price to be shown.

### What actually happened

It was identified as a free upgrade even though it isn't.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by sirbrillig** [comment]
Just to add some details: the logic says to show this particular upsell [when the item in the cart is a renewal or when the cart contains a domain and no plans (and the site has no plan)](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/checkout/src/components/checkout-main-content.tsx#L291), and more specifically [when the item in the cart is not a renewal](https://github.com/Automattic/wp-calypso/blob/f7b17c38628d2f0f782d5d66f845348d01e92b85/client/my-sites/checkout/src/components/secondary-cart-promotions.tsx#L80-L81) and [the cart contains a domain registration, the site has no plan, and there is no plan in the cart](https://github.com/Automattic/wp-calypso/blob/f7b17c38628d2f0f782d5d66f845348d01e92b85/client/my-sites/checkout/cart/cart-free-user-plan-upsell.tsx#L132-L136). To summarize: show this upsell when the cart contains a domain registration and no plan on a site with no plan.

Therefore, to reproduce: for a site with no plan, add just a domain to your cart and visit checkout using calypso.localhost, then reload the page until you get the notification that the Redux store has been cleared and you'll see the bug.

**Comment by sirbrillig** [comment]
https://github.com/Automattic/wp-calypso/pull/89874 should fix this.
