### ISSUE TITLE
Remove processing step: add loading behaviour to new instruction step

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#89762]
This is the most open-ended issue and will probably need to be implemented in more than one PR. This is the behaviour that we are aiming for in the new instructions step:
1. Wait for AT transfer to be completed and Migrate Guru to be installed
1. Create a new visual indicator of the status of this two actions
1. Enable the 5th instruction step (Copy/paste the key) once the two previous actions are done

**Comment by gabrielcaires** [comment]
@andres-blanco I think we can close this issue, implemented here https://github.com/Automattic/wp-calypso/pull/90143
