### ISSUE TITLE
Site Migration: Improve site migration instructions step copy

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#89765]
### Details
During our empathy flow testing, we received some feedback to improve the page copy.

## Points we need to improve
- [ ] Make clear which email the user should use (wpcom account email, admin email, random email, etc...)
- [ ] Explain the user should skip all other migrate guru fields when the migration key is set, (Image 1)
- [ ] Add instructions to agree to BlogVault’s terms
- [ ] It might help to display the existing site URL on the migration screen, especially when migrating multiple sites (so we know which is being migrated at the time).

## Original feedback:
pdtkmj-2z6-p2#comment-4838

_No response_

**Comment by sixhours** [comment]
Some additional feedback/suggestions for copy changes here: https://github.com/Automattic/wp-calypso/issues/89521

**Comment by gabrielcaires** [comment]
Closing with the correct status to not affect the sprint count
