### ISSUE TITLE
Trail Map: The comparison grid can render both the new design and the current design on mobile

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#89787]
## Summary

While there is no design-wise change for the comparison grid on desktop, there are proposed changes for it on mobile.
This task is specifically about implementing the UI changes. Once #89785 is done, we should be able to just wire in the updated feature map.

The mobile design: Uzd0AYiDAV4eFq1V35T9Ef-fi-673_7146. 

For a quick reference, below is a rough comparison between the two variations:

|Current | Trail-map version|
|-----|--------|
| <img width="413" alt="CleanShot 2024-04-23 at 16 58 25@2x" src="https://github.com/Automattic/wp-calypso/assets/1842898/185c8d06-3f5c-4827-ba82-815515f0ca55">| <img width="414" alt="CleanShot 2024-04-23 at 16 57 46@2x" src="https://github.com/Automattic/wp-calypso/assets/1842898/0762a3b4-7b17-4d41-94dd-1dddb518a134">|

### Checklist

- [ ] The comparison grid can switch different rendering mode, e.g. by a prop.
- [ ] In the Trail Map version, the absent features are no longer rendered as strike-outs, but simply leaving out as empty space.

**Comment by oswian** [comment]
@southp A question related to our testing/experiment setup. I read a discussion (pau2Xa-5Nw-p2#comment-15362) about separating the testing for desktop & mobile. As this task is specific to the mobile layout, I'm wondering what needs to be considered in terms of the implementation. Do we still use the same feature flag? Do events (button clicks etc) need to be triggered with mobile-specific parameters?

**Comment by oswian** [comment]
I'd like to build this change in Storybook and leverage some recent improvements (https://github.com/Automattic/wp-calypso/pull/89834), so if you have a moment @southp I'd greatly appreciate the review 🙏

**Comment by southp** [comment]
> A question related to our testing/experiment setup. I read a discussion (pau2Xa-5Nw-p2#comment-15362) about separating the testing for desktop & mobile. As this task is specific to the mobile layout, I'm wondering what needs to be considered in terms of the implementation. Do we still use the same feature flag? Do events (button clicks etc) need to be triggered with mobile-specific parameters?

Good question. Separating the testing for desktop & mobile is actually mainly for better segmenting the data for device types since ExPlat doesn't support that at the moment. We are simply running the same UI experience through them, so we need to make sure there is a proper mobile experience implemented for the proposed design.

Thus, we will be using the same feature flag to alter the design of the comparison grid we present to users. We also don't need to add new button click event since we will rely on ExPlat to do the math for us. 

Does that make sense? I feel my explanation is a bit mouthful 😂, so please feel free to let me know if I can clarify anything for you further.

**Comment by oswian** [comment]
@southp Thanks for the information regarding ExPlat, it's very useful context.
