### ISSUE TITLE
Site: 'Issues with Site' generic message displaying in Calypso when disk quota is exceeded

### ISSUE THREAD

**Issue by brezocordero** [Automattic/wp-calypso#8979]
**Steps to reproduce**
1. Starting at URL: https://wordpress.com (user logged in)
2. If more than one site: 
            Go to My Sites, Switch Site and select a site with Premium plan and disk quota exceeded
3. if only one site with Premium plan and disk quota exceeded: 
            Go to My Site

**What I expected**
To see 'Exceeded disk quota' message, same message that is displayed in WP Admin
**What happened instead**
A generic message is displayed 'Issues with' Site
**Screenshots**

Dashboard view:
![calypsoviewnodata](https://cloud.githubusercontent.com/assets/8002881/19770089/36b4e63c-9c5e-11e6-8be0-865422ca6de8.png)
WP Admin view:
![wpadminviewnodata](https://cloud.githubusercontent.com/assets/8002881/19770088/36b1a544-9c5e-11e6-9d13-0159b8fd06b0.png)
#### Context / Source

Issue found on ticket 2893468-t when user with exceeded disk quota reported not understanding the message
# user-report

**Comment by folletto** [comment]
This is probably a great spot to show a link to plans too.  :) 

/cc @breezyskies
