### ISSUE TITLE
Sites: Websites are duplicated on the Sites page

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#89825]
### Quick summary

The `Sites` page at `https://wordpress.com/sites` shows duplicate sites.
<img width="1293" alt="Screenshot 2024-04-23 at 4 12 31 PM" src="https://github.com/Automattic/wp-calypso/assets/11635760/40b1fa36-bd47-4aef-bd5e-5eb2c62726c8">

### Steps to reproduce

1. Go to WordPress.com
2. Click on "All Sites" at the top left corner.
3. View the Sites page with the duplicates.

### What you expected to happen

Only show each site once.

### What actually happened

Each site is listed twice.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

**Workaround**: Reloading the page seems to fix the issue.

This seems to occur on random sites, it's difficult to pin down an exact reason, and seems unrelated to the number of sites an account might own.  It happens on some accounts and not others.

It can be reproduced with account `mrsenff`.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Uncertain
- Tested on Atomic – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
I couldn't reproduce it on my own site, but I saw this yesterday on a user's account:

![CleanShot 2024-04-25 at 10 54 54@2x](https://github.com/Automattic/wp-calypso/assets/14153300/a31966d0-db2f-40c1-90eb-f0de43fcedf2)

- [ ] 8090794-zd-a8c

📌 ACTIONS
- Triaged
- Requested author feedback


📌 Message to Author
@vparkhere are you able to reproduce reliably on your own account? Have you run into user reports about this?

**Comment by liviopv** [comment]
@Automattic/quake is this something you can look into?

**Comment by vykes-mac** [comment]
I also saw this issue, It seems it only appears on support sessions.

**Comment by senff** [comment]
> I also saw this issue, It seems it only appears on support sessions.

I also see it (intermittently) when I do it in a regular session.

**Comment by liviopv** [comment]
@vykes-mac The user on 8090794-zd-a8c indicated they saw it as well, so it might be happening outside of SU as well.

**Comment by vykes-mac** [comment]
Thank you @liviopv I'll take a look into it.

**Comment by vykes-mac** [comment]
I've created a fix here https://github.com/Automattic/wp-calypso/pull/89997
