### ISSUE TITLE
Upgrade: Allow a monthly billing plan for Creator Trial

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#89832]
### What

Currently, there is no way for a Creator Trial user to upgrade to a monthly billing plan.

https://github.com/Automattic/wp-calypso/assets/32432463/fd93fa90-39de-4be9-988e-d0a539651f4f

### Why

This would prevent some users who want a monthly billing plan from leaving.

**Comment by andregardi** [comment]
I am closing this, since we don't offer Creator Trial anymore.
