### ISSUE TITLE
Fullpost: Gizmodo posts missing More blocks

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8986]
For example: https://wordpress.com/read/feeds/10080096/posts/1202865056

![screen shot 2016-10-27 at 2 15 25 pm](https://cloud.githubusercontent.com/assets/24388/19785820/d23f2662-9c4f-11e6-9aa1-2834468ccb74.png)

Missing both More blocks.

Is it because it's an RSS feed?

**Comment by blowery** [comment]
Yup, no more blocks because it's RSS. Notice there's also no Like button.

**Comment by fraying** [comment]
I thought RSS subs had the More blocks? Did they before? Could they?

**Comment by blowery** [comment]
Moving to #8988
