### ISSUE TITLE
Refreshed Video Cards broken in Safari

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8987]
The refreshed video cards don't work correctly in Safari.

![screen shot 2016-10-27 at 2 27 45 pm](https://cloud.githubusercontent.com/assets/24388/19786308/34da72fc-9c52-11e6-9913-746efa865299.png)

![screen shot 2016-10-27 at 2 28 04 pm](https://cloud.githubusercontent.com/assets/24388/19786309/34dbedbc-9c52-11e6-83cc-bcfdd31be817.png)

**Comment by blowery** [comment]
cc @samouri

**Comment by samouri** [comment]
Two things to fix:
- [ x ] alignment of the play icon
- [ ] the way it resizes in safari when play is clicked

**Comment by samouri** [comment]
#9406 In Progress

**Comment by samouri** [comment]
Issue fixed. Closing
