### ISSUE TITLE
Fullpost: Add "More on WP" block to RSS posts.

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8988]
Currently, if the user follows a site via RSS, the fullposts do not have either More block. This is due to tech limitations. But we could do the following:

Add the "More on WP" block to the end of the post. Instead of using the Related algo, use the Recommended Post algo. 

This would be great to keep people clicking through posts, especially for excerpt-length posts, where the More links will be visible.

Possible? Easy?

**Comment by gibrown** [comment]
We could also use the related posts algo and take the data from feedbag. Not implemented yet, but should be pretty easy to do.

**Comment by fraying** [comment]
@gibrown Easier or harder than just using the "More on WP" block? The goal is just to give people something else to read at the bottom of a post.

**Comment by gibrown** [comment]
More backend work, so slightly harder, but my assumption is that showing content that is related to what the user was just reading will perform better than just general recommendations. Especially for new users where we don't have much data to use for customizing recs.

**Comment by fraying** [comment]
The most immediate goal is just to get some cross-navigation links added to the bottoms of posts from RSS feeds so we're no longer missing that opportunity. Once it's in place we can test what works best.
