### ISSUE TITLE
Reader full post: handle 403 and 404 errors better

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#8989]
When viewing a full post from a private blog to which the user has no access, the page currently looks like this:

<img width="920" alt="screen shot 2016-10-28 at 10 48 16" src="https://cloud.githubusercontent.com/assets/17325/19786786/2f9f0d70-9cfc-11e6-8596-03c876261a9a.png">

We should display a helpful error message if it has not been possible to retrieve the post due to a 403 or 404.

**Comment by fraying** [comment]
Just show 404?

**Comment by bluefuton** [comment]
> Just show 404?

That could work. Unfortunately, 404 also does the same at the moment :/

https://wpcalypso.wordpress.com/read/blogs/82798297/posts/999

I'll update the issue title to reflect that.
