### ISSUE TITLE
Site Migration: Send success emails when migration cleanup is complete

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#89897]
The old, Jetpack-based migration process sends out two emails (`migration/migration-success-new` and `migration/migration-trial-success-new`) when it's complete.

We want to send these same emails when a MigrateGuru migration is complete. The emails will be triggered when the migration-cleanup async job is done.

**Comment by markbiek** [comment]
A couple of Jetpack and Calypso changes have been made to support this. The rest will happen in the WPCOM backend and is currently in-progress.

**Comment by daledupreez** [comment]
Note that I documented further details in https://github.com/Automattic/dotcom-forge/issues/6661.

**Comment by markbiek** [comment]
Noting that I have most of an implementation for this in D146636-code
