### ISSUE TITLE
Problems on install

### ISSUE THREAD

**Issue by ramjc** [Automattic/wp-calypso#899]
Hi,
I'm trying to run the project on Ubuntu Trusty and other distros on Vagrant(with nodejs v. 0.12.8 and 4.2.2) but after excecuting `make run` or `sudo make run` I always end up with this error: 
```
/bin/sh: 1: /home/vagrant/proj/wp-calypso/node_modules/.bin/webpack: not found
make: *** [build-server] Error 127
```
I didn't have any problem installing on Mac, those folders have installed correctly. Please I just only know what can I do for running this project on my pc described.
Thanks

**Comment by ramjc** [comment]
Looks like it was only an npm problem, I only update `npm install -g npm` and `npm cache clean` :smiley_cat:

**Comment by Viper007Bond** [comment]
Glad you got it fixed. :+1:
