### ISSUE TITLE
Refreshed Cards: Header Spacing Nits

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8990]
Getting into the pixel-level tweaking here.

Currently the card headers look like this. (Screenshots from Safari but the spacing is the same in Chrome.)

![screen shot 2016-10-27 at 2 51 45 pm](https://cloud.githubusercontent.com/assets/24388/19787402/5cfd2c5c-9c57-11e6-811e-60d0edf36df3.png)

But they should look like this:

![screen shot 2016-10-27 at 3 07 55 pm](https://cloud.githubusercontent.com/assets/24388/19787410/68868db6-9c57-11e6-8b62-07d595379136.png)

Changes:
- Text should be 10px from avatar (6px right from present)
- Name should be 2px down from top line (2px down from present)
- Meta info should be 2px up from bottom line (1px up from present)

**Comment by fraying** [comment]
Also, just curious: Why isn't the avatar circle mask symmetrical? Notice the hard edge on the left. Any ideas, @jancavan?

**Comment by jancavan** [comment]
We use `border-radius` so probably just differences in browser rendering. Although I'm not sure why there's that hard edge on the left on your screenshot. Looks okay on mine.

Safari:

![screenshot 2016-10-28 14 54 44](https://cloud.githubusercontent.com/assets/4924246/19823632/8615eaf8-9d1e-11e6-84cd-f43943219acd.png)

Chrome:
![screenshot 2016-10-28 14 56 06](https://cloud.githubusercontent.com/assets/4924246/19823659/ab97541a-9d1e-11e6-8fa4-9a5f40e2291a.png)

**Comment by fraying** [comment]
Okay, let's not worry about that one for now.
