### ISSUE TITLE
Refreshed Cards: Text Tweaking

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#8992]
In all refreshed cards:

* The post title font size needs to decrease by 2px. It also seems to be bolder than bold. I notice that font-weight is set to "600" in the new version and "bold" in the old one. Is that why?

* The post title needs to have ~5px more bottom margin to separate it from the excerpt a bit.

* I also notice that the excerpts are ending with an ellipsis before the end of the block (in other words, the ellipsis appears in the middle of the block, not on the right edge). Why is this?

So this:
![example-before](https://cloud.githubusercontent.com/assets/24388/19789117/e2e405ac-9c61-11e6-8568-5f36f4ea5583.png)

Should be more like this:
![example-after](https://cloud.githubusercontent.com/assets/24388/19789122/e7014398-9c61-11e6-9870-cbe47ad996f9.png)

Note that there's ~20px of whitespace in between the title (excluding descenders) and the excerpt, and in between the excerpt (excluding descenders) and the action links.

**Comment by blowery** [comment]
> The post title font size needs to decrease by 2px. It also seems to be bolder than bold. I notice that font-weight is set to "600" in the new version and "bold" in the old one. Is that why?

600 and "bold" are typically the same thing I think? With the font dropped to 25px, they appear identical.

> I also notice that the excerpts are ending with an ellipsis before the end of the block (in other words, the ellipsis appears in the middle of the block, not on the right edge). Why is this?

We're currently using the short excerpt, which is limited to 160 characters

**Comment by fraying** [comment]
> 600 and "bold" are typically the same thing I think? With the font dropped to 25px, they appear identical.

Should, yes. Identical, no. At least, not in Safari.

> We're currently using the short excerpt, which is limited to 160 characters

But we can change that to do what we were doing before, yes? Using CSS to limit the excerpt to three lines and ending with an ellipsis?

**Comment by jancavan** [comment]
> But we can change that to do what we were doing before, yes? Using CSS to limit the excerpt to three lines and ending with an ellipsis?

There's still a limit being set outside of CSS.

@blowery Do we use long excerpts for the current streams? Might still be tricky though that's why in the current stream, some end with an ellipsis and some don't.

**Comment by fraying** [comment]
Should we take this (the excerpt thing) to a separate issue?

**Comment by jancavan** [comment]
> Should we take this (the excerpt thing) to a separate issue?

Probably should.

**Comment by fraying** [comment]
@jancavan Done: https://github.com/Automattic/wp-calypso/issues/9013
