### ISSUE TITLE
Provide more details in logs when pre-flight health checks fail

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#89935]
Follow up from the comment here: https://github.com/Automattic/wp-calypso/pull/89904#discussion_r1580111029 

We don't reveal much information when it's `pre_update_health_check_failed`, and users won't be able to debug or knowing what do do next without reaching out to us.

**Comment by obenland** [comment]
Did https://github.com/Automattic/wp-calypso/pull/89904 fix this ticket?

**Comment by ouikhuan** [comment]
No it didn't. It's for the site health check after the plugin updated but not the pre-flight checks.
