### ISSUE TITLE
Site Migration: Modify in_site_migration_flow setting to store the actual flow instead of a bool

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#89958]
A couple of changes need to be done for this setting now that there is more than 1 site migration flow:
 * We should update the `in_site_migration_flow` setting to store the actual flow instead of a boolean.
 * Probably we would need to wrap up the function that updates this setting into a hook of some sort so it can be used from different flows as needed.

**Comment by nelsonec87** [comment]
https://github.com/Automattic/jetpack/pull/37099
