### ISSUE TITLE
FE list: search filter component

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#89966]
❗Needs this merged first: https://github.com/Automattic/wp-calypso/pull/89902

Do we need the status filter & sort? What would status be?

The search prop is already implemented inside `<ScheduleList />`

![Image](https://github.com/Automattic/wp-calypso/assets/528287/6161827b-b83e-40ae-992c-eff76dd7c785)

**Comment by ouikhuan** [comment]
Should status be a list of plugins with a checkbox to select? cc @JanaMW27 for thoughts here.

**Comment by JanaMW27** [comment]
If this is for the schedules list, maybe the filter should be;
Status: Active / Inactive
Status: Successful / Errors

I think this are the 2 top cases for a user with a lot of schedules, but I would not show it unless the list has more than 10 schedules.
WDYT?

**Comment by ouikhuan** [comment]
> Status: Active / Inactive
Status: Successful / Errors

Thanks @JanaMW27  this sounds good! 

Does this mean it's better for us to have two status dropdown? One for active schedules and one for the update results of schedules? 

>  I would not show it unless the list has more than 10 schedules.

👍 

> Do we need the sort?

I'm also wondering how much will sorting plays in this scenario, the name of a schedule is all defined by us, but perhaps sorting for site name is still helpful.

**Comment by JanaMW27** [comment]
I have reviewed what is currently in production for WP 6.5 and come up with the following proposal for filtering and sorting:
![Filtering : sorting](https://github.com/Automattic/wp-calypso/assets/71137829/6514cad2-8965-44c9-b938-c718da7bd574)

Figma file: https://www.figma.com/file/rrEvrq63njWdmuXkJSTcY2/Plugin-scheduler---multisite?type=design&node-id=3172%3A53969&mode=design&t=ImEIYFRAbTigYrkI-1

**Comment by TimBroddin** [comment]
Nice design @JanaMW27 !

Since we're running out of available appetite for this project (we want to wrap up the list this week) I suggest we start with search and add on filtering/sorting next week or when bandwidth allows.
