### ISSUE TITLE
Subdomains: specific mapping message

### ISSUE THREAD

**Issue by cecilerainon** [Automattic/wp-calypso#8997]
While testing #8923, I noticed that when I tried to create a subdomain I got the same message I would get if I tried mapping a regular domain:

> subdomain.domain.com is taken.
> If you purchased rainon.fr elsewhere, you can map it for $13.00.

I think that could be misleading to non-savvy people and I think it would be a nice enhancement to reword this message when it comes to creating a subdomain.

I'm not sure how this could work, but is it possible to dig CNAMEs on subdomains and see if they exist? And if they don't, a specific message such as the following could be displayed:

> subdomain.domain.com is available!
> If you own domain.com you can map subdomain.domain.com for $13.00.

I'd keep the message in yellow still to give a sense that they (the user) have some actions to complete (adding a CNAME to the domain).

![capture d ecran 2016-10-28 a 14 42 52](https://cloud.githubusercontent.com/assets/16645645/19806699/daa65bea-9d1c-11e6-942b-8231bc640a7d.png)

**Comment by lancewillett** [comment]
See also #10947

**Comment by lancewillett** [comment]
Fixed with https://github.com/Automattic/wp-calypso/commit/c45fcb98710b4f3ab516470e19789c1530d51695
