### ISSUE TITLE
FE list: mobile view

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#89970]
❗Needs this merged first: https://github.com/Automattic/wp-calypso/pull/89902

Currently only the desktop table is implemented. 

👋 @JanaMW27 how do you envision the mobile view of the multi-site scheduled updates? A card view like we currently do in single-site scheduled updates?

**Comment by JanaMW27** [comment]
Yes, I think so. I need to look at it cause there is the dropdown for the site specific update. I will look into it during next week.

**Comment by JanaMW27** [comment]
Sorry for the delay on this:

Here is the mobile format
![multi-site mobile](https://github.com/Automattic/wp-calypso/assets/71137829/0143f206-6f9e-4617-a479-524352ecaebf)

[Figma file](https://www.figma.com/file/rrEvrq63njWdmuXkJSTcY2/Plugin-scheduler---multisite?type=design&node-id=3231%3A61866&mode=design&t=sdvkgubmptii0bYs-1)

I had to change and update some things, dont know if we can propagate this changes to the site specific mobile list.
