### ISSUE TITLE
.ie domains shown as taken no matter state

### ISSUE THREAD

**Issue by cecilerainon** [Automattic/wp-calypso#8998]
While doing some tests, I tested .ie domains and noticed that no matter the .ie domain that I tried, the yellow "domain is taken-map it" message would be displayed, even for domains that don't exist at all.
#### Steps to reproduce
1. Go to wordpress.com/domains/add
2. Lookup the .ie domain of your choice
3. See the message saying it's taken
#### What I expected

When the domain doesn't exist, I'm expecting to see that it can be registered elsewhere (because it's not a ccTLD we have) then mapped. This is the message I was expecting:

![capture d ecran 2016-10-28 a 15 01 43](https://cloud.githubusercontent.com/assets/16645645/19807227/7f0b8564-9d1f-11e6-878d-e47b035a957b.png)
#### What happened instead

It shows the yellow already taken message for any .ie domain that you'll try:

![capture d ecran 2016-10-28 a 15 01 22](https://cloud.githubusercontent.com/assets/16645645/19807244/91a0727a-9d1f-11e6-892a-e260c129e845.png)

**Comment by klimeryk** [comment]
Fixed by @aidvu in `D3294-code` 🙇
