### ISSUE TITLE
Menus: "Category" shows incomplete list of categories

### ISSUE THREAD

**Issue by deancroyal** [Automattic/wp-calypso#9003]
**Steps to reproduce**
1. SU (or SSP) as the user and start from their insights page for chrissiemason.com
2. Click on Menus
3. Click edit (the pencil icon) on any existing menu item.
4. Choose Category then scroll to the bottom of the category list.

**What I expected:** to see all categories in the list.

**What happened instead:** it does not show the entire list of categories (they have so far 38).

**Browser / OS version:** Chrome / Mac OS Sierra v. 10.12.1

**Screenshot & Video**
![screen shot 2016-10-28 at 9 48 40 am](https://cloud.githubusercontent.com/assets/13387217/19815229/bb40c662-9cf6-11e6-8c1e-5fa1a0a106d6.png)

Video: https://cloudup.com/ccVIwsLbGZy

**Context / Source**
Had the user in a 506152-chat. We were working on the menu environment together and this was something I noticed while I was SU'd to help her.

**Comment by lancewillett** [comment]
Thanks for the bug report — we're closing Menu bugs in Calypso because our plan is to point everyone to Menus in Customizer in the near future (so not fixing all the nitpicks with Menus).
