### ISSUE TITLE
Theme Test Data site: Host or upload images to Github

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#90054]
### What

See https://github.com/WordPress/wordpress-playground/issues/718#issuecomment-1850730227 and https://github.com/WordPress/theme-test-data/issues/82#issuecomment-2055567664 for more details.

Media files on `wpthemetestdata.wordpress.com` are hosted on WordPress.com, i.e. `wpthemetestdata.files.wordpress.com`. CORS errors prevent these images from being imported into WordPress Playground sites. 

It has been proposed that the media files be hosted on or uploaded to Github to bypass CORS errors.

### Why

To allow this site's setup – including media files – to be used as a default option for testing themes in Playground.

### How

Possible options:
1. Upload all images from `wpthemetestdata.wordpress.com` to Github and update the site to use these externally-hosted images and regenerate a new XML export file.
2. Provide a ZIP of all images on the site which can then be uploaded to Github by anyone. Media file references can then be updated in the existing XML file in the https://github.com/WordPress/theme-test-data/ repo.
3. Update references in the existing XML file to use `i*.wp.com` CDN URLs instead of `*.files.wordpress.com` URLs.

**Comment by flexseth** [comment]
@jp-imagines thanks for taking a look at this!

**Comment by jp-imagines** [comment]
@flexseth I spoke to a few colleagues about this, all of whom agreed with the recommendations from here: https://github.com/WordPress/theme-test-data/issues/82#issuecomment-2055567664

Looks like a fix is already in the works in https://github.com/WordPress/theme-test-data/pull/89 (using `i*.wp.com` CDN URLs), and the other solution would be to just download some or all of the media files from the test site and upload them to Github instead.

I'll close out this issue in light of that open PR and the discussions in the WP repos.
