### ISSUE TITLE
Components: InfoPopover position is wrong on mobile

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/wp-calypso#9007]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/post
2. Select a site to create a post (if available)
3. Click on _Actions_ to show the post actions panel.
4. Open the _Categories and Tags_ panel.
5. Open and close either the _Categories_ or _Tags_ information popover
#### What I expected

When opened and closed, the popover should show the correct width when opened a second time.
#### What happened instead

When opened a second time, the information popover is shown collapsed. `left` inline style is wrong the second time.
#### Browser / OS version
- Chrome v54 (Device Toolbar enabled as iPhone 6)
- Safari 10 (Responsive Design Mode - iPhone 6)
- Safari on iOS 10.1
#### Screenshot / Video

![img_0775](https://cloud.githubusercontent.com/assets/233601/19817742/4884f166-9d23-11e6-8abe-7538ba5ef543.jpg)

**Comment by AnnaMag** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/19992.

**Comment by rodrigoi** [comment]
@AnnaMag thanks for taking care of this!
