### ISSUE TITLE
Photo Cards: Reduce character count to 100

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9010]
Using the new thing, I still see a bunch of cards that really shouldn't be photo cards. So I suggest we lower the character limit to 100 to use the photo card. Easy to tweak and see?

**Comment by bluefuton** [comment]
> Easy to tweak and see?

Yes! I'll work up a quick PR.

**Comment by fraying** [comment]
Thanks, @bluefuton!
