### ISSUE TITLE
Site Migration: Need to activate Videopress as part of the post-migration cleanup

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#90101]
We need to make sure that the Videopress Jetpack module is activated.

We should check to see if multiple Jetpack modules can be activated with a single command (since we're already doing a command to activate the SSO module).

If we _can't_ activate multiple modules, we probably want to move Videopress activation into a separate job.

**Comment by valterlorran** [comment]
I tested it, and I think we can't enable more than one module. I see we have two options:

1. Concatenate a new command to enable VideoPress alongside the SSO. But if the VideoPress fails to enable it, it will give a negative response.
2. Have a separate call for enabling the VideoPress module, which we can evaluate if we should stop the execution and retry the job again.

**Comment by sixhours** [comment]
> Have a separate call for enabling the VideoPress module, which we can evaluate if we should stop the execution and retry the job again.

I think it makes sense to create a separate job for this so we can handle any errors separately and keep the jobs simpler. Improperly activated SSO could break the site, but not having VideoPress won't.

**Comment by sixhours** [comment]
Started working on this here: D148186-code

**Comment by sixhours** [comment]
This has been shipped in D148186-code

However, in the future we probably need to refactor how these Jetpack module activations are handled into a single new job.
