### ISSUE TITLE
Refreshed Cards: Excerpt treatment

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9013]
In the old stream, excerpts were usually three lines ending with an ellipsis at the right edge. Like so:

![screen shot 2016-10-28 at 2 52 47 pm](https://cloud.githubusercontent.com/assets/24388/19823599/568eafe0-9d1e-11e6-9716-f5ee2db243c0.png)

But in the refreshed streams, excerpts are limited to 160 characters and end with an ellipsis wherever.

![screen shot 2016-10-28 at 2 52 54 pm](https://cloud.githubusercontent.com/assets/24388/19823615/6af734b6-9d1e-11e6-9fd3-80131f63f603.png)

This is one case where I think we should stick to what we were doing before. What are the pros/cons?

cc @blowery @jancavan @bluefuton

**Comment by blowery** [comment]
We can go back to the old treatment, sure. Likely want to use `post.better_excerpt_no_html` and then either use the long-content-fade or use the line-clamp magic that chrome / webkit supports. IE / Edge / Firefox don't have a way to clamp lines, so we'd have to use the long-fade there.

**Comment by fraying** [comment]
Excellent! Let's do it.

**Comment by blowery** [comment]
Should be fixed with #9314

**Comment by fraying** [comment]
Fixed!
