### ISSUE TITLE
Approving comments doesn't update the sidebar

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#90138]
### Quick summary

Approving pending comments doesn't seem to update the sidebar notification about the number of pending comments. Check the screenshot - I've approved the comment and navigated outside of the list of pending comments.

<img width="1380" alt="Screenshot 2024-05-01 at 8 12 48" src="https://github.com/Automattic/wp-calypso/assets/82778/3aa1c5f8-f27d-4448-906d-af25f8b71b19">

It was originally reported in the comment section of https://weirdo82.wordpress.com/ although I couldn't find exactly where.

### Steps to reproduce

1. A blog has to receive a comment that's pending
2. Go to https://wordpress.com/comments/pending/SITE
3. Approve the comment
4. The sidebar still shows (1)

### What you expected to happen

The sidebar should not show (1)

### What actually happened

Label not updated

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by lsl** [comment]
Seems to be already fixed

https://github.com/user-attachments/assets/a01dedd6-9ed9-4fa5-ab4c-2a375e1d37d5

**Comment by dzver** [comment]
@lsl are you sure this issue is completed?

<img width="100%" alt="Image" src="https://github.com/user-attachments/assets/20979350-2629-41f7-8d2f-6bbb64b82295" />

**Comment by lsl** [comment]
Not at all, I just wasn't able to repro at the time, is this something you're still seeing? I wonder if it's related to the larger count.

Do you see the same issue with `/wp-admin/edit-comments.php`? Most users see this now.

**Comment by dzver** [comment]
I'm in the control group. Let's drop this given that UI is going to change.
