### ISSUE TITLE
Remove processing step: Redirect user from checkout page directly to the instructions page

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#90146]
### Details

As part the initiative to reduce the number of loading screens we have on the site migration, we need to update the flow to redirect the user directly from the checkout page to the site migration instructions page.

Nowadays it is redirecting first to the deprecated bundler page and then redirecting again to the instructions page.

**Comment by sixhours** [comment]
I think we can close this, right?

**Comment by sixhours** [comment]
This was handled by https://github.com/Automattic/wp-calypso/pull/90712
