### ISSUE TITLE
Refreshed Stream: More Text Tweaking

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9015]
I'd like to try changing the text sizes a little more. Could we try changing:

* Title down to 21px
* Excerpt down to 15px
* Excerpt line-height up to 24px

(Or whatever the proper units are.)

These changes, plus the added space in between title and excerpt from the other issue, results in something like: 

![screen shot 2016-10-28 at 3 17 21 pm](https://cloud.githubusercontent.com/assets/24388/19824120/b71bb530-9d21-11e6-94be-326f3dc28bcd.png)

The smaller titles take some getting used to, but they're such a blessing for long ling 3-line titles. Give it a try and see how it feels?

Also, @jancavan, it may make sense to keep the old values for the largest breakpoint? Please advise.

**Comment by blowery** [comment]
When I was playing with it, I took titles down to 18px, excerpt down to 14. But I come from 8pt in editors, so... :)

**Comment by fraying** [comment]
Heh. Yeah. I always figured we'd do some tweaking once we got to play with it a bit.
