### ISSUE TITLE
Design Picker: add support for woo product filters in block-previews endpoint

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#90156]
### What

The woo product filter blocks keep loading in the design picker preview of Kiosko them

### Why

These blocks should look as in the demo site

|DEMO SITE|DESIGN PICKER PREVIEW|
|-|-|
|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/c7b8105f-ab81-4466-afc1-ebfcc26afb68)|![Image](https://github.com/Automattic/wp-calypso/assets/1881481/051fcbbf-4e4a-479f-b41b-bf5814ba915b)|

### How

- Probably missing JS assets or other data required.
- See the blocks: https://github.com/Automattic/themes/blob/trunk/kiosko/patterns/product-filters.php
- See Kiosko preview: https://public-api.wordpress.com/wpcom/v2/block-previews/site?stylesheet=pub%2Fkiosko&language=en&viewport_height=1040&viewport_unit_to_px=true&calypso_token=kiosko&remove_assets=true

**Comment by arthur791004** [comment]
Proposing https://github.com/Automattic/wp-calypso/pull/90487 to resolve the issue.

**Comment by taipeicoder** [comment]
Closing as it's fixed.
