### ISSUE TITLE
[Bug] "Add subscribers" icon is black in Jetpack Cloud

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#90168]
### Impacted plugin

Jetpack

### Quick summary

Some users see the `+` with a black fill instead of white:

The right one:
<img width="922" alt="Screenshot 2024-05-01 at 17 37 54" src="https://github.com/Automattic/jetpack/assets/25607244/2aab3220-9d9b-47c2-bd0c-df5d9bd097b2">

The wrong one:
![image](https://github.com/Automattic/jetpack/assets/25607244/d0822ae1-ab98-4efd-a920-781b0556d72e)
![image](https://github.com/Automattic/jetpack/assets/25607244/9471859f-ead6-4b50-9d49-c914000a01be)

### Steps to reproduce

1. Go to `https://cloud.jetpack.com/subscribers/{site}`
2. Check the color of the `+` inside the `Add subscribers` button (top right)

### A clear and concise description of what you expected to happen.

The icon should be white instead of black.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by jeherve** [comment]
Moving this to the Calypso repo where the Calypso green interface, aka Jetpack Cloud, is being built.

**Comment by DustyReagan** [comment]
I was able to reproduce this by:

- Go to https://jetpack.com/manage/
- Click on "Manage sites" in the upper right
- Select any site
- Click on "Subscribers" in the left hand menu
- Observe the black + button
- If you refresh the page, the button style is corrected.

**Comment by Aurorum** [comment]
The styles are seeping from here, introduced in #71423:

https://github.com/Automattic/wp-calypso/blob/879b0a2f6cb670b957fe3c7a39ca885b10daf8bc/client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-content/style.scss#L120-L124

The steps outlined by @DustyReagan cause the problem because the button links to `/dashboard`, which then redirects, but not before those styles are loaded.

But I don't have enough knowledge of the section to know what the Agency Dashboard is and therefore how specific they should be.

**Comment by simison** [comment]
@simonktnga8c 👋 above agency/manage section lacks scoping class (like `.jetpack_sites-overview`) and thus the generic component overrides end up in global scope with rest of Jetpack Cloud.

As Calypso loads sections in different order depending on what pages users visit, quite a lot of stuff can appear broken with unscoped CSS.

Would someone from your team be able to fix and probably review other CSS files for the section?

**Comment by andrii-lysenko** [comment]
Thank you for reporting this. I've created a PR to address this issue.
In the same time, it's hard to identify all CSS errors like this just from code perspective, as we need to verify is it actually breaking something or fixing it. 
I will run some code scanner to try to identify possible mistakes and will log these into separate tasks.
