### ISSUE TITLE
Signup: inconsistent error in Survey step

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#9018]
In the `survey` step, sometimes I'll get the following console error when selecting a vertical:

`build-stage.be41313….min.js:21 Uncaught TypeError: Cannot read property 'value' of undefined(…)`

When that is triggered, it's impossible to move forward in the flow. Unfortunately, I can't consistently reproduce the error, though it happens often enough I've seen it a couple of times already.

Noticed in the `/get-dot-blog` flow, as well as `/`.

**Comment by ranh** [comment]
I was able to reproduce the same issue (or a very similar one anyway):

![wbp13 - screen shot 2016-10-29 at 11 33 41 am](https://cloud.githubusercontent.com/assets/426518/19828331/bc0ad3fa-9dcb-11e6-91d4-eee862277e06.png)

When choosing a vertical, I did not move to the next screen, and all the console errors in the screenshot showed up.

**Comment by bisko** [comment]
Fixed in #9240
