### ISSUE TITLE
PostSelector: Create Empty/Null Prop

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#902]
From discussion in #896 - the task is to create a new prop for the `PostSelector` that will inject a null/empty option at the top of the selector.  The immediate use case would be to insert a "Top Level Page" option in the Page Editor sidebar as seen in this design mock from @folletto:

![screen shot 2015-11-27 at 16 00 52](https://cloud.githubusercontent.com/assets/4389/11444943/1104a012-9520-11e5-9cac-5b67fb9676d1.png)

**Comment by alisterscott** [comment]
The UI looks different now so I'm closing this out. 

<img width="258" alt="screen shot 2017-05-12 at 3 38 04 pm" src="https://cloud.githubusercontent.com/assets/128826/25983576/07f88d24-3729-11e7-948a-4123cb1f347c.png">
