### ISSUE TITLE
Purchases: Changing links from /my-upgrades to /purchases

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#903]
There are some links returned from the API that point to /my-upgrades. We should update these to /purchases.

Logged by @stephanethomas in https://github.com/Automattic/wp-calypso/issues/543.

**Comment by drewblaisdell** [comment]
- I think we should clarify which links we need to change here. @stephanethomas mentioned that these are in error messages, but I'm not sure which. I'll list them here as I encounter them.
- For messages that need to link to a `/purchases` route, ideally, we shouldn't rely on a link from the API at all, as links to these routes already live in `/me/purchases/paths`. Instead, I think we should include a string `error_code` with these messages and determine the message on the client (like we do in [`RegisterDomainStep`](https://github.com/Automattic/wp-calypso/blob/master/client/components/domains/register-domain-step/index.jsx#L402)).

**Comment by fabianapsimoes** [comment]
Moved to T350 since this is a back-end issue.
