### ISSUE TITLE
Top Post & Pages Displays Deleted Post

### ISSUE THREAD

**Issue by sbathompson-he** [Automattic/wp-calypso#90308]
### Quick summary

The Top Post & Pages block is showing a deleted post. When clicked, it results in a 404, which is expected. However, the post should be shown in that block. 
Informed the customer that we would flag it as a bug and work on possible workarounds or solutions.
7875379-zd-a8c

### Steps to reproduce

1. Click on the post `Get the upgraded eBook Alexius' Duality Hacks for free` on the [homepage](https://alexiusdualityhacks.com) under Most visited posts of all time
2. 404's, which is correct
3. Post is trashed and should not be showing there at all

### What you expected to happen

Should not be showing deleted posts 

### What actually happened

Shows deleted post

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by Aurorum** [comment]
PR in Automattic/jetpack#37251 - thanks for the report!
