### ISSUE TITLE
Add the "best for eCommerce" label for the Entrepreneur plan

### ISSUE THREAD

**Issue by ddc22** [Automattic/wp-calypso#90301]
## Summary

This is a follow-up issue extracted from https://github.com/Automattic/wp-calypso/issues/89682#issuecomment-2076889005. For all the Trail Map variants, we should show "best for eCommerce" badge for the Entrepreneur plan:

![image](https://github.com/Automattic/wp-calypso/assets/1842898/2e94ea2b-eb37-4dff-b226-9e33e8095a5f)

**Comment by southp** [comment]
Closing this per deployment of #90302
