### ISSUE TITLE
FE: link site title to single site schedule

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#90358]
> When unfolding a row in list view, would it make sense to link the site name to the single-site schedule updates UI?
>
> -- @obenland

**Comment by TimBroddin** [comment]
I don't know, this might feel odd and users might miss that they're editing the single site schedule.

**Comment by obenland** [comment]
> users might miss that they're editing the single site schedule

That's a good point.

I find it odd that there's currently no way to get to individual sites' schedules from multisite. Not sure what the best solution would look like

**Comment by TimBroddin** [comment]
I think something like this would confuse the hell out of me:

![Image](https://github.com/Automattic/wp-calypso/assets/528287/d9e221bf-72ea-4947-993a-d25af9855665)

Maybe (just thinking out loud) we can open a modal when you click Edit that asks if you want to edit it only for the selected site or for all sites?

**Comment by obenland** [comment]
It's not about editing for me per se, more about having a way to get to the single site from multisite.
Which is why I thought of the using the site title for it

**Comment by ouikhuan** [comment]
How about having an action as "View schedules on site" and link to the schedule list on site instead, will this be more clearer? Otherwise, if we link the site title to the site level schedule list and not the edit schedule screen, it shouldn't confuse user too much. What do you think?
