### ISSUE TITLE
FE: hide sites that don't have scheduleable plugins

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#90356]
> Do we want to show sites that don’t have schedule-able plugins in the site selector? It feels kind of odd to show a site that's ineligible, but users could miss them if we didn't show them?
>
> -- @obenland

**Comment by TimBroddin** [comment]
It makes sense to me to hide them.
We could add a label beneath the site selector like we already do on the plugin selector.

![Image](https://github.com/Automattic/wp-calypso/assets/528287/8479b1c2-0b9a-4a4d-8582-107d20294247)

**Comment by TimBroddin** [comment]
Filtering these would either mean:

- Calling `/sites/<slug>/plugins` for every one of your Atomic sites
- Creating a new endpoint that only returns sites with eligible plugins

Is either of those options worth it @obenland ?

**Comment by obenland** [comment]
> For now we only fetch plugins after a user selects a site and decide what plugins to show on the screen. If we want to do this beforehand this means we need to prefetch all the /plugins endpoint on page load, I'm not sure if it's worth doing so :thinking_face: This also means we'll need to check if a plugin is managed on the target site on WPCOM too.
> —p1715074147342269/1715027396.631299-slack-C01A60HCGUA

Maybe it's enough to display a fallback string for that case, something along the lines of https://github.com/Automattic/wp-calypso/pull/90237
