### ISSUE TITLE
FE: Multisite schedule list doesn’t update for me when deleting a schedule

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#90361]

**Comment by TimBroddin** [comment]
@obenland is this when you try to delete a multisite schedule, or when you try to delete a single site schedule?

**Comment by ouikhuan** [comment]
I can reproduce this when I have two sites with the same schedule on the multisite screen. One got removed, and another didn't get removed correctly. (However, the logs are still removed from the schedule). In my other tests, I got all the sites removed correctly but immediately refetching the list after the deletion seems to happen before the sync finished so it still returns old data until I refresh the page a few seconds later. It's about 3~5 seconds delay for sync.

**Comment by obenland** [comment]
> @obenland is this when you try to delete a multisite schedule, or when you try to delete a single site schedule?

A multisite schedule. But even if it only contains one site. 

Again, it could be something wonky with my test site as it also doesn't update the sync option when I make changes

**Comment by bogiii** [comment]
Closing, it's fixed here: https://github.com/Automattic/wp-calypso/pull/92429
