### ISSUE TITLE
Command palette: Open site dashboard should respect the admin interface style

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#90394]
The 'Open site dashboard' command opens up the Calypso dashboard, instead it should use the users preferred admin interface to open up either the calypso dashboard (`/home/:site`) or the core dashboard (`:site/wp-admin`)

https://github.com/Automattic/wp-calypso/blob/deb836f33523439f42d9d6d4c652822fc5789d4e/packages/command-palette/src/commands.tsx#L215

**Comment by rcrdortiz** [comment]
Changes are now live
