### ISSUE TITLE
Editor: preview returns 404 when trying to preview a self-hosted WP.org site while not logged in to the site

### ISSUE THREAD

**Issue by m** [Automattic/wp-calypso#904]
I wasn't able to preview a post for a Jetpack site when not locally logged into the site itself, the video shows the problem and has a little commentary:

https://cloudup.com/c1yAXE8Ad9d

**Comment by rralian** [comment]
I just tested this and it's working fine for me. I navigated to my wp-admin for a jetpack site, I logged out from that domain. Then I went to wordpress.com, created a draft, and clicked preview and it successfully opened a new tab with the preview. I think we can close this (yay!). @lancewillett do you wanna re-confirm?

**Comment by lancewillett** [comment]
Confirmed fixed.

#5607 is a slight variation in that it happens **after** you've published a post, and try to edit and preview, **before** saving the updates.
