### ISSUE TITLE
FE: Expand chevron misaligned

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#90400]
The center of the chevron doesn't seem to align with the schedule title. Not sure if that's on purpose.

<img width="1510" alt="Screenshot 2024-05-07 at 11 51 28 AM" src="https://github.com/Automattic/wp-calypso/assets/1398304/6978e9a6-637f-41e3-835b-1fd92d272e3d">

@JanaMW27

**Comment by JanaMW27** [comment]
Good catch! not on purpose, it should be aligned

<img width="945" alt="Screenshot 2024-05-08 at 11 11 22" src="https://github.com/Automattic/wp-calypso/assets/71137829/30759e31-8cdd-46cd-b2de-5aa62277cfd7">

Also, do we use right side chevron for a closed drawer? normally is down chevron for a close drawer, up chevron for an open one right?
