### ISSUE TITLE
FE: List view differences between multisite and single site

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#90401]
There are a handful of differences between multisite list view and single site list view.
Which ones of these do we want to change?

|| Multisite | Single Site |
| -- | -- | -- |
Button | bigger radius corners | smaller radius corners |
Button text | New schedule | + Add new schedule |
Title | Update schedules | Plugin Update Manager |
Subtitle | Doesn't exist | Exists
Table heading | Doesn't exist | Exists
Table borders | Doesn't exist | Exists

https://github.com/Automattic/wp-calypso/assets/1398304/9525247e-3a0c-48f8-a16f-3e78ac71a9a1

@JanaMW27 Can we re-use the style of the multisite list view on single site and break it out of that box?

**Comment by JanaMW27** [comment]
Yes, let's use the styles from multi-site since it is the one designed latest and accounts for all the different scenarios.

**Comment by TimBroddin** [comment]
I'm starting on bringing the style of the multisite view to single site.

**Comment by TimBroddin** [comment]
@obenland @JanaMW27 Here's a preview without the box: https://github.com/Automattic/wp-calypso/pull/90443

You're free to leave feedback in the PR.
