### ISSUE TITLE
Trail Map: Change the storage section label to title-case.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#90478]
### Details

Originally reported by @chriskmnds from pau2Xa-5Sh-p2#comment-15398

In design:
![image](https://github.com/Automattic/wp-calypso/assets/1842898/e61974ad-7d8d-4adf-9eea-b63e5963a749)

In implementation:
![image](https://github.com/Automattic/wp-calypso/assets/1842898/57ded186-f27f-4628-901a-6487e1fb8a21)

Although the design is from the Project Trail Map, I think the original all-caps label violates the Chicago Writing Style that we are following. Thus, we can either fix it for the trail map variants, or we can also just fix it across the board.

**Comment by chriskmnds** [comment]
> Although the design is from the Project Trail Map, I think the original all-caps label violates the Chicago Writing Style that we are following. Thus, we can either fix it for the trail map variants, or we can also just fix it across the board.

@southp yes, good point. Let's fix it for all and go from there
