### ISSUE TITLE
Jetpack Cloud: Missing tracking in /monetize

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#90496]
### Impacted plugin

Jetpack

### Quick summary

While building a funnel to track how many people click the Paid Newsletter CTA inside Newsletter settings I realized that we aren't tracking this button:

<img width="1063" alt="Screenshot 2024-05-09 at 13 07 54" src="https://github.com/Automattic/jetpack/assets/25607244/2e8166e2-931c-443a-a69a-168a174cac4f">

### Steps to reproduce

1. Navigate to https://cloud.jetpack.com/monetize/payments/:site
2. Check if you can trigger an event when clicking `Add a new payment plan`
3. Creating a plan doesn't have any track either

### A clear and concise description of what you expected to happen.

It should have a tracks event like the Stripe button (`calypso_memberships_stripe_connect_click`).
Perhaps `calypso_membership_add_plan_click`?

And something similar for the user interactions happening inside the modal, especially when a user creates a new plan. This way, we'll be able to measure how many people open the modal and how many end up creating a new plan:
<img width="805" alt="Screenshot 2024-05-09 at 13 11 36" src="https://github.com/Automattic/jetpack/assets/25607244/8faa93e5-8efd-4508-8775-b8f6e6546a13">

### Impact

All

### Available workarounds?

There is no user impact

**Comment by pkuliga** [comment]
The event for the button click is "calypso_memberships_add_payment_plan_click".
