### ISSUE TITLE
Editor: Localized Domains Cause Editor Links To Fail

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#905]
Some accounts on WordPress.com can have their primary domain set to be localized domains such as WordPress.de under their domain management page at https://wordpress.com/my-domains/

For those accounts links to the editor that include that domain will fail to work. For example if someone has the site.

siteaddress.wordpress.de and that is set to their primary domain links to https://wordpress.com/post/siteaddress.wordpress.de/postid to edit a post will instead redirect to https://wordpress.com/post/siteaddress.wordpress.com/ and try to start a new post instead of edit the desired one.

Ideally we should redirect to https://wordpress.com/post/siteaddress.wordpress.com/postid so that the post can still be edited. 

One place this link comes to play is when visiting your own site, looking at a post, and clicking the generated Edit link.

**Comment by jkudish** [comment]
After a little bit of internal research, I found that *.wordpress.de domains are not really supported anymore. If other users are still using that, they should switch to *.wordpress.com as their primary domain. 

Closing as wontfix.
