### ISSUE TITLE
Update the Site Profiler's "Migrate" button text and link

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#90506]
### What

Update the Site Profiler's heading information "Migrate site" button text and link.

&nbsp;
Currently: 

<img width="1194" alt="image" src="https://github.com/Automattic/wp-calypso/assets/66711744/11e1f7a1-2049-4450-bab9-cd2c93f8caba">

### Why

- To help attract more users to our Happiness-assisted migration service.
- To reduce usage of Move to WP.com (see pdqkMK-1db-p2)

### How

**Update the button text:**
"Get a free assisted website migration"

&nbsp;
**Update the link:**
https://wordpress.com/support/request-a-free-migration/?ref=site-profiler&section=heading-information

(Edited to remove the incorrect link)

Note: I have updated the referrer link to reflect the same information being shown on `https://wordpress.com/hosting`

&nbsp;
**Visual example:**
<img width="1194" alt="image" src="https://github.com/Automattic/wp-calypso/assets/66711744/e994197e-2dcd-4568-8104-e40b9362d5de">

Cc: @bohdankit07

**Comment by cpapazoglou** [comment]
When using `/setup/new-hosted-site/plans?ref=site-profiler&section=heading-information` I am just presented with the creator, entrepreneur plans 

![CleanShot 2024-05-10 at 15 28 01@2x](https://github.com/Automattic/wp-calypso/assets/12430020/bda4b5bf-a66e-44a7-8307-007c12c999e0)

After purchasing one, I don't get into the migration flow. @inaikem this seems like a regression. For comparison, `/setup/import-hosted-site?from=` is loading the following screen 

![CleanShot 2024-05-10 at 15 29 49@2x](https://github.com/Automattic/wp-calypso/assets/12430020/a977f25d-f6d2-4d79-868f-95340f5538e2)

**Comment by cpapazoglou** [comment]
Also, I would expect some copy / instructions related to the "assist" we are offering.

**Comment by inaikem** [comment]
> When using /setup/new-hosted-site/plans?ref=site-profiler&section=heading-information I am just presented with the creator, entrepreneur plans

This is expected for _this_ flow since we need the site to go Atomic and install the Migrate Guru plugin.

&nbsp;

> After purchasing one, I don't get into the migration flow. @inaikem this seems like a regression. For comparison, /setup/import-hosted-site?from= is loading the following screen

> Also, I would expect some copy / instructions related to the "assist" we are offering.

My apologies, I provided you with the incorrect link. It should go straight to a form, not a flow: 

[https://wordpress.com/support/request-a-free-migration/?ref=site-profiler&section=heading-information
](https://wordpress.com/support/request-a-free-migration/?ref=site-profiler&section=heading-information)

The linked page provides all the relevant copy and emails will be dropped into a specific ZD queue. Example ticket: 8179838-ZD.

Apologies for the confusion 🙏

**Comment by andres-blanco** [comment]
It was brought up by Jana on Figma that currently, after entering your site's url while logged out you get asked for the input URL after creating the account. I am making this note so we check that is not the case in the new flow.

**Comment by inaikem** [comment]
Solid feedback, well made. Thank you 🙇‍♂️

I reviewed the flow again today with this feedback in mind and think that if we were to keep the existing link to the new migration flow, then we should default that to Migrate Guru after the site selection and plan selection/purchase screens. It currently defaults to testing a JP connection.

@daledupreez, do you foresee any issues with defaulting to Migrate Guru vs the Jetpack steps after a site/plan has been selected/purchased?

**Comment by andres-blanco** [comment]
@inaikem Once this project is ready: paYKcK-4BA-p2, this link will default to Migrate Guru, and the Jetpack steps will be removed.

I will update/close this issue once that's done

**Comment by andres-blanco** [comment]
@inaikem, this is now deployed; clicking on the Migrate site will bring you to the Migrate Guru-based flow.

I am closing this; feel free to re-open it if there something I missed :).
