### ISSUE TITLE
Forums Customer Pseudonym does not replace username in old mentions

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#90525]
### Quick summary

Setting a staff customer pseudonym should replace your username in the forums with `staff-{pseudonym}` everywhere; however it does not appear to replace `@mentions` within comments, leaving the staff username exposed.

> The change will be immediate and total, and the real username and gravatar should not appear anywhere, including in past replies.
From: PCYsg-Sg0-p2

### Steps to reproduce

Noticed this on a very old thread I worked on once: https://wordpress.com/forums/topic/support-126/

### What you expected to happen

The `@mention` should also read `@staff-{pseudonym}`

### What actually happened

The `@mention` does not update. 

![CleanShot 2024-05-09 at 16 10 03@2x](https://github.com/Automattic/wp-calypso/assets/27249804/1e604011-e010-4560-b106-647506468060)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
related: p5gXjh-3EO-p2#comment-10568

**Comment by AtrumGeost** [comment]
Currently working on this 💪 Will update back with any news.

**Comment by AtrumGeost** [comment]
Deployed D148724-code and this is now fixed 👍
![CleanShot 2024-05-23 at 20 12 38@2x](https://github.com/Automattic/wp-calypso/assets/3696121/14ac7fd7-741d-4e4f-b5c1-379845691e10)
