### ISSUE TITLE
Site Migration: Refactor module activation during cleanup

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#90526]
From D148186-code via @daledupreez 

At some point, we should refactor how we approach module activation during post-migration cleanup to avoid modules potentially being missed or not activated properly on the site due to plugin conflicts.

> Have a dedicated `wpcom_site_migration_activate_jetpack_modules()` job that specifies a clear set of modules that ought to be activated AND works out what all the plugins are on the site (via something like `wp plugin list --status=active --format=csv --field=name`), and then runs `wp jetpack module activate <modules> --skip-themes --skip-plugins=<all_plugins_except_jetpack>`.

**Comment by nelsonec87** [comment]
Related diff D149308-code

**Comment by sixhours** [comment]
This was deployed in D149308-code 🥳
