### ISSUE TITLE
VIP - Testing VIP specific functionality #question

### ISSUE THREAD

**Issue by spentay** [Automattic/wp-calypso#9052]
I'm [currently refactoring](https://github.com/Automattic/wp-calypso/pull/9032) some files relating the sidebar and would like to test that the vip specific rendering is still a-ok. I'm pretty sure it is since I've only changed very trivial logic - but I'm curious as to how this should actually be tested.

I can see that the VIP config on dev is set to false, so I know to change that - I'm more thinking of site status (is this site 'vip' or not)

Are there test accounts that can be used? 
If so are they reserved for Automattic members only?
Finally, if both of the above are true, shall I just leave the testing of the VIP menu in the hands of a member?

Thanks :)

**Comment by lancewillett** [comment]
Good question: don't worry about VIP sites for now. They are indeed reserved for very... important... (ahem)... WordPress.com sites.

> Finally, if both of the above are true, shall I just leave the testing of the VIP menu in the hands of a member?

Yes! That's fine — we'll double check it after those changes are in staging.

Thanks for your contributions. 👍

**Comment by lancewillett** [comment]
@spentay Another _ahem_: https://automattic.com/work-with-us/javascript-engineer/ 😈 👀

**Comment by spentay** [comment]
Thanks Lance! I'll just be sure to make a note if I make any changes close to any `isVip` type logic!
...oh and 😉
