### ISSUE TITLE
FE: Convert html if it's showing up from the error message

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#90547]
See: p1715325569109759-slack-C01A60HCGUA

**Comment by obenland** [comment]
```
<p>There has been a critical error on this website.<\/p><p><a href=\"https:\/\/wordpress.org\/documentation\/article\/faq-troubleshooting\/\">Learn more about troubleshooting WordPress.<\/a><\/p>
```

I don't know how helpful it is to pass on this error message. Maybe we could check for a 500 error and show a more helpful message?

**Comment by ouikhuan** [comment]
Hmmm, I agree. Probably point them to our support directly? Something like "Your website is experiencing technical issues. Please contact our support for assistance."?

**Comment by obenland** [comment]
Let's link them to a support doc instead?
https://wordpress.com/support/resolve-jetpack-errors/#critical-error-on-the-site

**Comment by ouikhuan** [comment]
Sure, something like: 
`Your website is experiencing technical issues.  Please refer to our [link]support documentation[/link] for assistance in resolving this error.` 
We can even keep it shorter like: 
`Your website is experiencing technical issues.  [link]Learn how to fix[/link].`

**Comment by obenland** [comment]
Let's go with the first one!
