### ISSUE TITLE
The infinite scroll in the reader appears to be broken

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#90545]
### Quick summary

Scrolling new posts mostly doesn't work at the moment but sometimes does.it 

### Steps to reproduce

1. Go to wordpress.com/read and browse by tag, for example https://wordpress.com/tag/blog or https://wordpress.com/tag/books
2. Scroll down
3. Witness no infinite scrolling

https://github.com/Automattic/wp-calypso/assets/82778/541d4871-7ae0-4aad-840f-a24b16ba11c6

### What you expected to happen

Scrolling to work

### What actually happened

it didn't

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

**Comment by DustinHartzler** [comment]
Curious @lupus2k if the fix has anything to do with the scrolling location is no longer remembered when opening a post.

Steps to reproduce:
- Go to https://wordpress.com/read/a8c
- Scroll down to the 10th post and click on the title to open the P2
- Use the Reader <-Back button in the upper left corner
- See that your position has been lost and you are at the top of the page again

It seems to work properly for tags.
