### ISSUE TITLE
Enhancement: Week name overlaps with the Jetpack stats in WP Admin area

### ISSUE THREAD

**Issue by bizanimesh** [Automattic/wp-calypso#90557]
### Impacted plugin

Jetpack

### What

We can make changes to avoid overlapping of stats data with the week name.

### How

If we go to Jetpack » Stats » and select Weeks for stats from the filter and hover on any green stats bar, we will notice that the week name is overlapping with stats data.

![Screenshot 2024-05-10 at 9 23 37 AM](https://github.com/Automattic/jetpack/assets/52444539/fab0bb90-1657-476a-b260-df8e100afd1b)

Screen Recording:

https://github.com/Automattic/jetpack/assets/52444539/00bfd5c7-2b6c-47fd-bc54-10f226ccf453

Reported in 8153300-zd-a8c

**Comment by kangzj** [comment]
Thanks for reporting! Dup with https://github.com/Automattic/jetpack/issues/37444 and is fixed.
