### ISSUE TITLE
Site Migration: Offer clearer progress and next steps from migration instructions screen

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#90573]
### Details

As flagged in pfuQfP-fb-p2#comment-430 and pdxWSz-1oA-p2, the migration instructions page feels like a dead end while you're waiting for a migration to finish, as well as when the migration has finished.

It would be much better if we can detect that a migration has started, and communicate that the migration is in progress.
It would also be excellent if we can detect that a migration has completed, in which case we should celebrate that! And we should also provide the user with clear next steps, likely using links to Customer Home and/or /wp-admin/.

**Comment by sixhours** [comment]
This feedback all applies to the old migration screen that was just a text list of instructions. The new one attempts to solve these problems with a more dynamic progress indicator and a launchpad-style step-by-step. I think we can close this.

<img width="1373" alt="Screenshot 2024-07-23 at 1 01 01 PM" src="https://github.com/user-attachments/assets/4b4ff77a-1611-4b70-88b5-8b47274030ef">
