### ISSUE TITLE
Scheduled Updates: Add Plugins menu item with drilldown

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#90577]
This will add a "Plugins" menu item to the new multisite UI with a drilldown function to expose submenu items.
We don't want to expose the multisite plugins page at this point, so the only submenu item should be "Scheduled Updates".

Let's make sure we stay closely aligned with @davemart-in, @lucasmendes-design, and @JanaMW27 on this one.

See video mockup in p9Jlb4-bDg-p2#comment-11238

**Comment by lucasmendes-design** [comment]
Nice to hear that 🚀

I have a question. Are we using the same data table (A4A - JetPack) as the one on the site list? Let's make sure that we won't add one more data table UI. 

Please ping me whenever you need me, I'm happy to help :)

**Comment by davemart-in** [comment]
> This will add a "Plugins" menu item to the new multisite UI with a drilldown function to expose submenu items.
We don't want to expose the multisite plugins page at this point, so the only submenu item should be "Scheduled Updates".

Just wanted to double check that the submenu item doesn't live on the global nav itself, but shows only after you click into "Plugins".

**Comment by bogiii** [comment]
> Just wanted to double check that the submenu item doesn't live on the global nav itself, but shows only after you click into "Plugins".

Exactly, that's the idea.

> Are we using the same data table (A4A - JetPack) as the one on the site list? Let's make sure that we won't add one more data table UI.

Are you talking about the sites table, which lives on the `/sites` route? If so, it's not implemented in a way that can be easily reused.
The scheduled updates list is already implemented, and it can be found here: `wordpress.com/plugins/scheduled-updates`.

In other efforts, we could create a reusable data table component in a unified, maintainable place and apply it to the existing features (sites, scheduled updates, etc.).

**Comment by lucasmendes-design** [comment]
> In other efforts, we could create a reusable data table component in a unified, maintainable place and apply it to the existing features (sites, scheduled updates, etc.).

How far are we from this? In my mind, I thought we had the data table component that could be reused =/

**Comment by davemart-in** [comment]
@cleacos just tagging you on this convo. Figured you might be able to share some context on the current state of things with regards to reusing the data table for things outside of sites.

**Comment by cleacos** [comment]
If I understood correctly, you want to create a new Plugins section and reuse the data table component with the Preview Pane option for any expanded option. It's possible with the current implementation; just use the `ItemsDataViews` component; it's agnostic about the context. I'd be the same process, it will need a wrapper component, `PluginsDataViews` and if you want the Preview Pane, another wrapper component, `PluginPreviewPane` and these components grouped by a new one called `PluginsDashboard`:

- `PluginsDashboard`
   - `PluginsDataViews` > `ItemsDataViews`
      - List of plugins with info columns.
   - `PluginPreviewPane` > `ItemPreviewPane`
      - A overview tab to show the info about the selected plugin
      - A tab to schedule updates
      - Maybe a tab with the sites where it's installed, and an option to install the plugin in an specified site.
