### ISSUE TITLE
Plans 2023: Incorrect free plan highlight label in `/start`

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#90608]
### Quick summary

There should be no "Your plan" highlight label

<img width="1418" alt="Screenshot 2024-05-10 at 5 08 52 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/cfecd96f-a8dc-4818-9a63-029dc2475c4e">

### Steps to reproduce

- Navigate to `/start/plans`
- Verify that the free plan has a highlight label

### What you expected to happen

There should be no label

### What actually happened

There was a label

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
1. Started on `/start`
2. Selected a free .wordpress.com subdomain
3. Landed on `/start/plans` 

![CleanShot 2024-05-14 at 12 17 13@2x](https://github.com/Automattic/wp-calypso/assets/14153300/b5bdfee3-d687-4002-94e7-4816178e34e6)


📌 ACTIONS
- Requested author feedback


📌 Message to Author
@jeyip I wasn't able to reproduce this one when creating a new site, but I'm wondering if you're coming from a different flow. Can you share more info about your test?

**Comment by jeyip** [comment]
Hi @liviopv it looks like it was fixed :D Not sure when it was patched, but I can't reproduce it either. I'm going to close this issue for now.
