### ISSUE TITLE
Image Editor: hasChanges should return false if default aspect ratio was changed

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#9060]
In #8922, we introduced a bug in which the image editor "Reset" button is enabled even when there are no "changes" as `hasChanges` reducer returns `true` when we set the initial/default aspect ratio.

See [#8922](https://github.com/Automattic/wp-calypso/pull/8922#issuecomment-257590152) for more details.

**Comment by gwwar** [comment]
Fixed by #10393
