### ISSUE TITLE
Task: Create signup intent capture step in Stepper

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#90628]
### Details

Build a tentative step to collect user intent in Stepper. It should look something like this:

![image](https://github.com/Automattic/wp-calypso/assets/17054134/03aded6c-ac5c-4388-b86b-0f3ffd5e8b64)

![image](https://github.com/Automattic/wp-calypso/assets/17054134/162234d4-ab56-4eeb-a4f8-914e2de20c35)

We already have `IntentStep`. We should probably extend that.

When the user clicks, the steps should submit the intention to the flow. 

_Note: this design is not final._ 

Design is here: https://www.figma.com/design/3u71fUJraClkRQiLrAORPf/Trail-Map-Project?node-id=3906-5213&t=C4ETPSlpGWgigLG6-0

**Comment by wongasy** [comment]
A heads up that there's a copy request for reviewing the segmentation module copy: pfGA22-1B-p2#comment-81
Here's the copy doc: 1-HU9hHrvQMUESPEy76aBA_21y1TfB9kw61DgNGbzCmU-gdoc

**Comment by escapemanuele** [comment]
We created the step in /start 👍
