### ISSUE TITLE
Importers: Consolidate list of supported/available importers

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#90635]
### Details

We have multiple places in Calypso that track permitted/enabled importers, including the following:
* `getConfig()` and `getImporters()` in `client/lib/importer/importer-config.tsx`
* The logic in `getFinalImporterUrl()` in `client/landing/stepper/declarative-flow/internals/steps-repository/import/helper.ts` includes a local `productImporters` constant
* The `ListStep` component in `client/blocks/import/list/index.tsx` includes a hard-coded list of primary and secondary import platforms

### Checklist

- [ ] Confirm which platforms should be enabled during import flows
- [ ] Confirm which location we're going to use as our source of truth
- [ ] Update callers to use the primary location

**Comment by markbiek** [comment]
To help wrap my head around this a bit, I've created a spreadsheet of the different engines and locations in Calypso:

34b20-pb/#bash

It makes the most sense to me to consolidate everything into `getConfig` in `lib/importer/importer-config.tsx`. The other functions are using a subset of the data defined in `getConfig` so it seems reasonable that they can pull their data from `getConfig` instead.

We can also add a `primary`/`secondary` designation that the `ListStep` could use.

**Comment by markbiek** [comment]
> Confirm which platforms should be enabled during import flows

@daledupreez The one thing I'm not sure about is how to confirm the above.

**Comment by markbiek** [comment]
Also noting that we may want to move the  `ImporterPlatform` and relates types out of `client/blocks/import/types.ts` and into `importer-config.tsx`.

**Comment by markbiek** [comment]
Leaving this open as I'm going to move some of the importer-related types around in a separate PR.
