### ISSUE TITLE
Site Migration: Handle `/import/siteSlug.wordpress.com/?flow=onboarding` path

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#90657]
The URL at `/import/[siteSlug]/?flow=onboarding` points to the `import-focused` flow. We don't know where the entry points to this URL are.

We may want to redirect this URL to the new site migration flow variant to be safe.

**Comment by sixhours** [comment]
I'm trying to figure out if we have any references to this path that need to be updated. The only reference I've found so far is in the importer controller here:

fbhepr%2Skers%2Spnylcfb%2Spyvrag%2Szl%2Qfvgrf%2Svzcbegre%2Spbagebyyre.wf%3Se%3Q326s4s7p%26zb%3Q2742%26sv%3Q89%2385-og

But that doesn't show where users are coming *from*.

**Comment by andres-blanco** [comment]
We couldn't find a way to navigate to this screen. This wasn't handled because it seemed unnecessary.

paYKcK-4BA-p2#comment-3465
