### ISSUE TITLE
WooCommerce new product editor (beta): Add block button causes editor to crash

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#90667]
### Quick summary

The "new product editor (beta)" allows for creating WooCommerce products using the block editor. With Gutenberg v18.3.0 installed and active, clicking the new block (**+**) button in the "full editor" experience causes the editor to crash to a blank screen.

### Steps to reproduce

1. Start with a site with WooCommece installed.
2. Enable the new product editor (beta) experience from _WooCommerce > Settings_ (or _Settings > WooCommerce_ on an  Entrepreneur plan site) _> Advanced > Features_. 
3. Go to _WooCommerce > Products_ (or _Products_ on Entrepreneur).
4. Add a new product or edit an existing product.
5. Click on the **Description** field, then click the **Full editor** button to bring up the block editor.
6. Click the **+** button at the top left.

### What you expected to happen

New block/pattern dialog should open.

### What actually happened

Editor crashes without visible error messages, showing just a blank screen.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Console errors:

![LKV9qx.png](https://github.com/Automattic/wp-calypso/assets/5630717/793fb609-c16e-40ff-baca-e5c1e58e5e21)

```
TypeError: e.focusSearch is not a function
Uncaught TypeError: e.focusSearch is not a function
Plugin "wc-admin-more-menu" is not registered.
Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
```

---

Workarounds: 

* use `/` to search for and add blocks instead of the **+** button
* deactivate Gutenberg 
* disable the new product editor

**Comment by jp-imagines** [comment]
Initial report here: 8184637-zd-a8c

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Replicated

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
Replicated as per the OP description
I tested on two different sites with WooC 
In my case I went to create a new product on both sites and the editor just hung. With the feature off, it worked as expected

## 📌 ACTIONS ##
Triaged

**Comment by lsl** [comment]
Couldn't replicate e.focusSearch error, looks resolved.

> I tested it today on an Atomic site, and while the editor didn't hung at any point, when I clicked on Patterns, there were none, which does feel like a bug

This looks like intentional filtering for the description field. Please re-open if I'm mistaken.
