### ISSUE TITLE
Fullpost: "Visit Site" should scroll

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9066]
On the new fullpost page, in some widths, after scrolling, the new "VISIT SITE" link appears over the text.

For example: 

![screen shot 2016-11-01 at 12 14 53 pm](https://cloud.githubusercontent.com/assets/24388/19903756/ff20630e-a02c-11e6-8b35-22992b2ac872.png)

I suggest that the "VISIT SITE" link scroll with the rest of the page to avoid this happening. 

Thoughts, @jancavan?

**Comment by jancavan** [comment]
@fraying Good catch. Fixed this in: https://github.com/Automattic/wp-calypso/pull/9071
