### ISSUE TITLE
Create the AdvancedMetrics component

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#90704]
Investigate and implement the suggestion here https://github.com/Automattic/wp-calypso/pull/90662#discussion_r1600315690

**Comment by WBerredo** [comment]
PR: https://github.com/Automattic/wp-calypso/pull/90765

**Comment by cpapazoglou** [comment]
Should we close this issue?

**Comment by WBerredo** [comment]
Yep, closing due to the merge of https://github.com/Automattic/wp-calypso/pull/90765
