### ISSUE TITLE
Migrations: Platform check flow idempotency issue

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#90713]
### Quick summary

When I start a migration by clicking the migrate a site button on wordpress.com/hosting and then enter in a site that isn't on the correct platform, I'm not then able to correct the issue and choose a site that is on the WordPress platform.

### Steps to reproduce

1. Start at wordpress.com/hosting
2. Click migrate a site button
3. Enter in a site that is on a non-WordPress platform (ex. twitter.com/ebinnion)
4. Verify that you get a message that your content can't be imported
5. Click "back to start"
6. Enter in a URL that is known to be on WordPress
7. Verify that you see an infinite spinner

### What you expected to happen

To be directed to a UI that allows to choose whether I want to migrate my site or have a trial.

### What actually happened

A broken UX.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by andres-blanco** [comment]
While this is reported for the flow we are trying to replace, I am adding this issue to the board so we can verify that this behaviour doesn't happen on the new flow.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/14153300/2fac27c9-8d4f-410a-9d1d-678c7cc299ab

📌 ACTIONS
- Triaged

**Comment by andres-blanco** [comment]
We've migrated to the new flow and this is the new behaviour. After entering an unrecognized site you get redirected to the import list, just in case our analysis tool fails. If you click back and enter a site hosted on WordPress it works as expected.

https://github.com/Automattic/wp-calypso/assets/375980/ad4c1012-973a-446a-bc12-8118dad3bef5
