### ISSUE TITLE
Stream Narrow Width: Right margin breakage

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9073]
I was just testing wpcalypso.wordpress.com and noticed that, when the browser is narrow enough to trigger the image-on-top cards, the excerpt and action links are about 20px too far to the right.

![screen shot 2016-11-01 at 3 10 06 pm](https://cloud.githubusercontent.com/assets/24388/19909573/93331b78-a045-11e6-92a9-4834e8237cdd.png)

**Comment by jancavan** [comment]
This is the same issue mentioned in: https://github.com/Automattic/wp-calypso/issues/9144 and is fixed in: https://github.com/Automattic/wp-calypso/pull/9163
