### ISSUE TITLE
Reader Refresh: update search cards to be the same as refreshed cards

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#9077]
Currently, Reader Search uses custom cards with a lower width than pre-refresh cards:

<img width="882" alt="screen shot 2016-11-04 at 09 24 57" src="https://cloud.githubusercontent.com/assets/17325/19983915/d543d890-a270-11e6-82a8-f4c8a54f3bb7.png">

As part of the Stream Refresh, we want to convert it to use the same cards as the other streams, which are wider and fancier:

<img width="922" alt="screen shot 2016-11-04 at 09 24 33" src="https://cloud.githubusercontent.com/assets/17325/19983970/146129ce-a271-11e6-9995-baca8764759f.png">

We should also make sure we capture and carry forward any custom stats we're tracking on the fancy search cards compared to normal cards.

**Comment by lancewillett** [comment]
Could you add some screenshots or other visuals to illustrate? It's nice for history, and for others to understand. Thanks. :)

**Comment by fraying** [comment]
@lancewillett It's all on the Readersquad P2.

**Comment by lancewillett** [comment]
We're an open project — it's a good practice to document openly.

**Comment by bluefuton** [comment]
Thanks @lancewillett, that's good feedback. I've added some screenshots to the description above.
