### ISSUE TITLE
Clicking on the back link from /me doesn't always go back

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#90792]
Clicking the back arrow on the /me page sometimes doesn't actually go back, there are two ways of triggering this so far.

### When changing language

 1. Go to https://wordpress.com/me/account
 2. Click on Interface Language, select a new language and then press Apply Changes
 3. It redirects you to https://wordpress.com/me/account?updated=success
 4. Which then redirects you to https://wordpress.com/me/account
 5. Pressing back goes to https://wordpress.com/me/account?updated=success which then redirects you to https://wordpress.com/me/account

https://github.com/Automattic/wp-calypso/assets/93301/02359e4d-37c8-408d-9326-9eaf7696af8f

### Via P2

 1. Click your avatar in the p2 masterbar (regular blog masterbar is fine)
 2. This takes you to https://wordpress.com/me/
 3. Which then redirects you to https://wordpress.com/me
 4. Pressing back then goes to https://wordpress.com/me/ which redirects you back to https://wordpress.com/me

----

Possibly introduced by: https://github.com/Automattic/wp-calypso/pull/89075

Originally reported here: p1715850956458639-slack-C9EJ7KSGH by @jarekmorawski

**Comment by taipeicoder** [comment]
Closing via merging https://github.com/Automattic/wp-calypso/pull/90833.
