### ISSUE TITLE
Site Migration: Show a progress state when the user starts a migration

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#90808]
### Details

Related to #90573 and #89765

Nowadays, when the user starts a migration via the `/site-migration` flow,  we are showing the instructions step as flow dead end. 

We need to show an "in-progress" state when the user starts the migration using Migrate Guru and redirect the user to a celebration step or state (Implemented on #90807) when the migration is completed. 

<img width="1005" alt="image" src="https://github.com/Automattic/wp-calypso/assets/38718/4132b91c-c503-4498-86a6-6599f3f5e9f5">

https://github.com/Automattic/wp-calypso/assets/38718/b8807844-61dc-443c-8c3d-4c5f9f03be63

**Comment by gabrielcaires** [comment]
@JanaMW27 Can you help us with design suggestions regarding this task and  #90807?

**Comment by JanaMW27** [comment]
I've created a task and will be looking into first explorations on the upcoming days.

**Comment by gabrielcaires** [comment]
@JanaMW27 Do you have progress about it? Maybe we can just implement something simple for now.

**Comment by JanaMW27** [comment]
I have been looking into migrations holistically and will be posting in the upcoming days. But my intention is to propose a restructure of the page: 
![Screenshot 2024-05-28 at 15 12 56](https://github.com/Automattic/wp-calypso/assets/71137829/4788a981-c0e2-4933-9c61-4aa3fed90929)
