### ISSUE TITLE
Reader Stream Refresh: add attribution line for Discover

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#9081]
In the current Reader post card, we have an attribution line for Discover posts:

Post attribution:
<img width="440" alt="screen shot 2016-11-02 at 18 36 28" src="https://cloud.githubusercontent.com/assets/17325/19917817/66e7a322-a12b-11e6-8fe0-b78a81516f31.png">

Site attribution:
<img width="218" alt="screen shot 2016-11-02 at 18 36 34" src="https://cloud.githubusercontent.com/assets/17325/19917818/66e9b658-a12b-11e6-832e-7479bada9667.png">

We need to add the same functionality to the new Reader post card.

**Comment by fraying** [comment]
@bluefuton Were those screengrabs from the main stream or the Discover tab?

**Comment by fraying** [comment]
Please hold off on this. There are other changes we need to do for Discover first, which may make this unnecessary. I'll work up a separate issue.

**Comment by fraying** [comment]
Please see: https://github.com/Automattic/wp-calypso/issues/9096

The changes for Discover cards there should also be applied to the Main Following Stream, which makes this issue unnecessary.

**Comment by bluefuton** [comment]
Just caught up on the background, thanks @fraying!

The attribution lines are shown in the Discover stream and main streams in the current cards (you can still see them on https://wordpress.com/discover).

<img width="322" alt="screen shot 2016-11-03 at 09 27 52" src="https://cloud.githubusercontent.com/assets/17325/19946097/da80e02e-a1a7-11e6-9efd-bf884d52b713.png">

Showing the original author details in the post card byline works in most cases - I've laid the groundwork for that in https://github.com/Automattic/wp-calypso/pull/9080.

The 'site pick' is a tricky one though (like this post: https://wordpress.com/read/blogs/53424024/posts/18838) - do we want to display the Discover post there? We don't actually have an original post to open in the full post view, and we won't have all of the author details to populate a byline (what we do have: site name, URL and avatar).

**Comment by fraying** [comment]
@bluefuton Was that question not answered in #9096?

**Comment by bluefuton** [comment]
@fraying Mostly :)

On site picks, we don't have an original post to work with, so there are a couple of things missing.

> link date to the original external URL as usual

We won't have an external post URL to link the date to. Linking the date to the site URL feels a bit odd. Perhaps we shouldn't link date for site picks?

> Include main tag (links to tag page as usual)

We won't have any tags, because there's no associated post. Perhaps we could grab a tag off the Discover post instead for site picks?

> For site picks, it goes to the site view of the site.

This is a great idea. 👍

**Comment by fraying** [comment]
Great questions!

I'd say: link the date to the site. Better to keep it consistently linked.

And: no tags is fine, skip it.

Cool?

Rock!

**Comment by bluefuton** [comment]
Sounds good!
