### ISSUE TITLE
Site Monitoring: 429 not available as a filter

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#90868]
### Quick summary

429 isn't available from the drop down filter
![2024-05-19 at 12 33](https://github.com/Automattic/wp-calypso/assets/47717887/49df750a-ecba-4062-9a2e-696f04ee17ba)

### Steps to reproduce

1. on a WoA site go to Tools > Site monitoring > server logs
2. open the status filter dropdown
3. look for 429

### What you expected to happen

Since this is one of the statuses that users are likely to be most interested in, I expected it to be an option

### What actually happened

can't filter by 429s

they can download the entire log and manually filter but it makes more sense to have the filter on our end

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

would be nice if the filter was a multi-select rather than a single select

**Comment by Aurorum** [comment]
> they can download the entire log and manually filter but it makes more sense to have the filter on our end

You can also use the link directly at the moment: `https://wordpress.com/site-monitoring/site.com/web?request_status=429`

But I've proposed adding it to the filter in #90869. :)
