### ISSUE TITLE
File block hangs in Safari Browser

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#90865]
### Quick summary

A PDF file when added via file block in editor greys out in Safari (works on other browsers) and the screen hands when we try to toggle: Show inline embed

I am uploading the video a customer sent us. I experienced the same when I tested on my end. 

https://github.com/Automattic/wp-calypso/assets/25743084/325b9a2a-cab1-4e7d-964f-4ced12bde823

### Steps to reproduce

1. Open Safari browser, login to WordPress.com
2. Add a new page and a File Block in it
3. Insert a PDF file, see if it loads or is greyed out
4. Try to make changes to the file and screen is stuck (you cannot click even) 

### What you expected to happen

1. File preview to work properly, can use toggles like Show inline embed and screen should not get stuck

### What actually happened

File preview greyed out so not working properly, cannot use toggles like Show inline embed and screen got stuck

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by rambogenius** [comment]
zd-8198790 Customer reported here

**Comment by chekle** [comment]
8226134-zd-a8c Potentially related - The user reported 'website freezing issues' when attempting to delete the File Block using Safari. I was able to delete it without issue using Chrome.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated / Could Not Replicate / Uncertain
- Tested on P2 (optional) – Replicated / Could Not Replicate / Uncertain
- Replicable outside of Dotcom – Yes/No

📌 FINDINGS/SCREENSHOTS/VIDEO

Simple
https://github.com/Automattic/wp-calypso/assets/14153300/bdec6cc6-f30c-4f9a-8b79-d57f936a6aaa

Atomic
https://github.com/Automattic/wp-calypso/assets/14153300/ac6a412b-135a-4959-891e-8b237fbcd231



📌 ACTIONS

- Requested author feedback

📌 Message to Author
@rambogenius @chekle have you been able to reproduce this yourselves?

I don't see any issues when using the File Block on Safari 17, but older versions of Safari tend to have issues with the Block Editor and Calypso in general. Can you try to reproduce yourselves and collect browser information from the customers?

**Comment by liviopv** [comment]
@rambogenius @chekle I'm going to close this as I couldn't replicate. Please reopen if you get consistent repro in the latest versions of Safari.
