### ISSUE TITLE
Site Settings: Prevent non-owner admin from deleting a site. 

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#9087]
Previously when a site was deleted on WordPress.com from `wp-admin` we sent a verification email to the site's owner This was true if it was the original owner or another admin user on the site trying to delete it.  This verification required the site owner to click a link before the site was deleted. 

This helped prevent situations where a disgruntled admin removed a site without the owner's knowledge. Currently we do not notify or verify with the owner when a site is deleted by a non-owner admin. This can lead to some confusing when a non-owner admin deletes a site. 

In Calypso, if upgrades are involved we do notify user that upgrades will need to be removed before the site can be deleted. This provides some protection if the site owner also owns the upgrades. 

I would like us to always at least notify the site owner of deletion even if it's after the process has occurred. (Maybe we add a 24 hour grace period).  Alternatively we can prevent non-owner deletions from the interface.

#### Steps to reproduce
1. Create two accounts
2. Create a site with one account
3. Invite/add second account as admin to the site created in step 2. 
4. Log in as the invite/added user
5. Delete the site from Settings > Delete site.
6. After the site URL has been verified the site will be deleted with no notification sent to the owner. 

#### What I expected
To be sent a verification to the site owner's account or at least be notified post delete. 

#### What happened instead
No notification was sent and the site was removed. 

#### Browser / OS version
Firefox 49.02 Linux Mint 18

#### Context / Source

Came in as a report from a forum mod see:  https://en.forums.wordpress.com/topic/deleted-my-blog-but-can-still-see-it-access-itwhy-so?replies=14#post-2774269

I also think on a personal note that while user's should be aware of who they are adding as an admin mistakes happen. By notifying the site owner we can allow them to right a wrong.

**Comment by KokkieH** [comment]
Another example of a non-owner admin deleting a site, and in this case it appears that the admin in question had had their account compromised: http://en.forums.wordpress.com/topic/my-blog-has-been-deleted-7

I agree with @BandonRandon that it's ultimately a site owner's responsibility who they add as an admin, just as it's the responsibility of each user to be aware of their account security, but adding an email notification as a kind of two-step authentication for site deletions will at least make it harder for this to happen and hopefully decrease claims of "accidental" deletions as well.
