### ISSUE TITLE
Email templates: no proper space between quote block and paragraph block

### ISSUE THREAD

**Issue by JuanLucha** [Automattic/wp-calypso#90876]
In the email templates, when a quote block is followed by a paragraph, how it looks is not consistent between frontend and email. There should be some spacing between them. Take a look at this example:

![Image](https://github.com/Automattic/wp-calypso/assets/3832570/322fb7dd-5877-495d-b76d-90a3d1cfda01)

**Comment by Robertght** [comment]
8213231-zen

**Comment by ivan-ottinger** [comment]
The new D151044-code patch will fix the issue. We are adding `24px` margin-bottom below the Quote block.

**Comment by ivan-ottinger** [comment]
The fix is now in production. All new emails will have more space below the Quote block. 🙁
