### ISSUE TITLE
Plans Grid: Storage Add-on Dropdown not displaying for spotlight plan

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#90905]
### Quick summary

There used to be a dropdown that allowed users to purchase storage add-ons for creator / entrepreneur spotlight plans in the plans grid. Something changed and the dropdown is no longer rendered.

Was this intentional? If not, the dropdown should be rendered again.

<img width="1223" alt="Screenshot 2024-05-13 at 2 30 44 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/f8be5724-6e8a-4390-b2e6-75eee4877b6b">

### Steps to reproduce

1. Ensure no storage add-ons have been applied to the site.
2. If the site doesn't have a creator or entrepreneur plan, purchase one.
3. Navigate to `/plans`
4. Verify that the spotlight creator / entrepreneur plan doesn't render a storage add-on dropdown, and only shows a storage capacity label of "50GB"

### What you expected to happen

There should be a dropdown in the spotlight plan which allow the user to purchase storage add-ons for their current plan.

### What actually happened

No dropdown is rendered

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by chriskmnds** [comment]
I've assigned this to myself and looking into it.

I think I'm convinced the functionality was deliberately disabled/removed, as we actually don't have the logic anywhere for doing it right. It was probably disabled due to being broken and misleading. It needs a bit of tweaking to account for the available storage upgrade.

**Comment by chriskmnds** [comment]
Hmmm I've done quite a bit of digging here, and boy is this turning into a challenge! As far as controlling how/what is shown for the current plan, which may involve already purchased upgrades, the way we've defined "add-on" storage slugs resulting to things like `FEATURE_50GB_STORAGE_ADD_ON` mapping to `100GB` strings. Part of me insists on reaping it all out and redoing, which isn't really going to happen.

Things apparently work perfectly well for add-ons page without any form of ambiguity on what is shown/available there. I'm starting from there and working my way out to figure out why/how things needed to diverge for plans-grid.

I'll dive a bit deeper still.

**Comment by chriskmnds** [comment]
Another issue likely related https://github.com/Automattic/wp-calypso/issues/90947

Storage just keeps giving. Things look pretty complicated/tangled to me throughout. 😞

**Comment by chriskmnds** [comment]
This is also related https://github.com/Automattic/wp-calypso/issues/90949
I guess things get rather convoluted when in site/admin context
