### ISSUE TITLE
Site Profiler: Search results display a placeholder

### ISSUE THREAD

**Issue by Agepeuve** [Automattic/wp-calypso#90919]
### Quick summary

When you search for a domain using Site Profiler, you receive a placeholder message instead of the search results.

### Steps to reproduce

1. Start at https://wpcalypso.wordpress.com/site-profiler
2. Search for any domain from the search bar

### What you expected to happen

You should see the domain information in the results page.

### What actually happened

You will see an empty page with the text "Results Placeholder".

![Markup on 2024-05-21 at 08-24-10](https://github.com/Automattic/wp-calypso/assets/35295198/d1b2278d-e45c-4b56-bc0f-f5c71ef2e5b0)

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by inaikem** [comment]
Escalated: p1716273005938319-slack-C02FMH4G8

**Comment by inaikem** [comment]
I can confirm the subdomain linked above isn’t working - https://wpcalypso.wordpress.com/site-profiler - but the live site does: https://wordpress.com/site-profiler/wordpress.com

Will continue the thread in Slack.

**Comment by inaikem** [comment]
Resolved - An incorrect link was shared in the HE heads-up and was bookmarked. False alarm!
