### ISSUE TITLE
Plans: Plan price not updated when storage option selected if a storage add-on previously purchased

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#90947]
### Quick summary

When having purchased a storage add-on (e.g. 50GB) and going to `/plans/[site]`, then selecting any storage option for one of the higher tier plans will not update the price of the respective plan.

<img width="600" alt="Screenshot 2024-05-21 at 5 47 12 PM" src="https://github.com/Automattic/wp-calypso/assets/1705499/8646fedf-ed20-4a2d-af9c-867ce42b8475">

### Steps to reproduce

1. Create a site on the `Creator` plan
2. Go to `/add-ons` and purchase a 50GB storage upgrade
3. Go to `/plans/[site]` and select any of the options in the dropdown for the Entrepreneur plan
4. Confirm that the price of the Entrepreneur plan no longer reflects the change

### What you expected to happen

Either the storage option NOT being available for selection (if any issues with it) or the price of the Entrepreneur (higher tier) plan to reflect the storage option's price.

### What actually happened

The price did not get updated

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by chriskmnds** [comment]
@southp @jeyip can you please confirm here and/or point to any existing issue if spotted previously?

**Comment by jeyip** [comment]
If any storage add-ons are purchased, user's shouldn't be able to purchase any more storage add-ons. I thought I added logic to ensure it wasn't available for selection on the plans page, but it's been quite a while and I can'tdistinctly remember. 

The behavior we're seeing now might have been an oversight 🤔

**Comment by chriskmnds** [comment]
> If any storage add-ons are purchased, user's shouldn't be able to purchase any more storage add-ons ( I'll try and dig up a link for context soon ). I thought I added logic to ensure it wasn't available for selection on the plans page, but it's been quite a while and I can'tdistinctly remember.

I think that concept and direction (that only a single purchase is permissible) is the root of a lot of issues I'm seeing with the implementation. The design and abstractions would have been a lot more natural if that was never baked into the logic so deeply.

I am also not sure if that is even a restriction on the backend. The error that I get is that I need to purchase storage greater than the previous purchase. I'm investigating that, but I am pretty sure the frontend should have been flexible to reason beyond the confines of either 50 or 100 GB (irrespective of what's made available for selection).
