### ISSUE TITLE
Force Action Links full width

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9094]
Posts with floated images at the end can cause the action links to bunch up. Can we force the action links to be full width below all post content?

For example: https://wordpress.com/read/blogs/67216947/posts/1159

![screen shot 2016-11-02 at 10 17 16 am](https://cloud.githubusercontent.com/assets/24388/19939295/8c6521a6-a0e5-11e6-9021-df41095a8725.png)

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/9226
