### ISSUE TITLE
Refreshed Discover Tab

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9096]
Implement Refreshed Discover Tab and special Discover card rules. (See Readersquad p2 post "Refreshed Discover" for the discussion around all this.)

![new-reader-3-discover-21](https://cloud.githubusercontent.com/assets/24388/19939624/087bdb76-a0e7-11e6-99d0-763990500469.jpg)

Notes:

Container: This uses the refreshed site view template, beginning with grav/blav (grav if single author, blav if multi author), site description, site owner name, follow count, and follow button.

Cards: For all Discover cards...

1. [x] Show all excerpt text. Don't truncate. 

6. [x] Show Follow button on Discover cards. Should follow featured site, not Discover.
3. [x] Links in the card (image, title, text) go to the fullpost view of the original post (not the Discover post) for quotes, picks, and photos. The "View" link goes to the original external URL (post or site), as usual.
2. [ ] For card header, show the original poster info, not Discover poster. Use date stamp of discover post date, so they appear in order, and link date to the original external URL as usual. Include main tag (links to tag page as usual).

7. [ ] For site picks, links on the card go to the site view of the site.
4. [ ] All “Quote” posts get the Text card layout and omit the image and title.  (Requested by Discover staff.)

5. [ ] All “Photo” posts get the Photo card layout and omit the title. (Requested by Discover staff.)

8. [ ] Post byline on cards: add Discover category with folder icon (links to "https://discover.wordpress.com/category/whatever" in a new tab).

**Comment by bluefuton** [comment]
> 1. Show all excerpt text. Don't truncate.

I think we may need to limit this one to Discover picks. Features and Collections posts like this one would have the entire post as the excerpt:

http://calypso.localhost:3000/read/blogs/53424024/posts/19516

**Comment by fraying** [comment]
The Ed folks said that all of the posts have properly sized excerpts.

**Comment by bluefuton** [comment]
> The Ed folks said that all of the posts have properly sized excerpts.

Ah I see now - we need to construct Discover excerpts differently. Rather than making our own excerpt from the `post.content` as we do for all other posts, we need to strip the HTML from `post.excerpt` and use that. I'm on it in #9410.

**Comment by fraying** [comment]
Thanks! I think we don't even have to strip the html, since we can trust the Ed folks to do the right thing.

**Comment by bluefuton** [comment]
For quote and photo posts - we'll have to figure out how to identify those. I'm assuming each one is a custom post type. We don't currently have that information passed us in the API.

**Comment by fraying** [comment]
@benhuberman How do you set the post types for Discover? Categories?

**Comment by benhuberman** [comment]
@fraying We use these [custom Discover post formats](https://discover.wordpress.com/wp-admin/edit-tags.php?taxonomy=discover_fp_post_format). Categories are reserved for post topics.

**Comment by kjellr** [comment]
Expanding on @benhuberman's comment, the post formats are stored under the `discover_fp_post_formats` custom taxonomy. Taking a quick look at console output though, I'm not sure we're sending that through to the API. If not, we should. @hakanb, can you confirm one way or another?

**Comment by bluefuton** [comment]
I've broken out the remaining tasks into https://github.com/Automattic/wp-calypso/issues/10060, #10062, #10063, #10064 and #10065.
