### ISSUE TITLE
Refreshed Tag Pages

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9098]
Update existing Tag pages to match the Refresh. See Readersquad p2 post "Reader Design Refresh 3: Container Pages" for full discussion.

![new-reader-3-tag-pretty](https://cloud.githubusercontent.com/assets/24388/19942023/8a81dcf8-a0ef-11e6-8044-2c8590ef26ca.jpg)

Header:
* Normal Back link.
* Follow tag on right. Text is "Follow Tag" to make it clear what you're doing. Clicking it adds that tag to the user's followed tags.

New header image:
* Use background image from ES query (paging @gibrown). 
* Darken whole image and place Tag name in the middle (SF UI Bold ~28px).
* Image credit bottom right, "Photo by First Last, Site Name" with name and site linking to the post it's from in a new tab. Text at 75% opacity.
* Set a dark grey background color for the div just in case the image doesn't load.

Post cards as normal with Follow links visible.

**Comment by gibrown** [comment]
> Use background image from ES query

Hmmm, ya we probably need a new endpoint for selecting a good image. @aaronyan seems tightly related to the image stuff you were recently working on. Let's chat about it when you get a chance.
