### ISSUE TITLE
Refreshed "My Likes" Page

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9099]
Update existing "My Likes" page to match the Refresh. See Readersquad p2 post "Reader Design Refresh 3: Container Pages" for full discussion.

![new-reader-3-likes1](https://cloud.githubusercontent.com/assets/24388/19942579/7b76584a-a0f1-11e6-90d5-5d82a5e54133.jpg)

Header: Nothing special. Hooray!

Post cards: Normal with Follow links visible and the Like icon lit up as now.

**Comment by blowery** [comment]
Looks done.
