### ISSUE TITLE
Ads Dashboard missing additional ad placement

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#90997]
### What

The additional placement option "Inline within post content" is missing from the Ads dashboard from https://wordpress.com/earn/ads-settings/SITE. This option shows up if the user goes to Jetpack  > Dashboard > Monetize

![CleanShot 2024-05-22 at 08 58 48](https://github.com/Automattic/wp-calypso/assets/24919469/5100ce0e-e37e-479d-ad3d-5c87a1657609)

![CleanShot 2024-05-22 at 08 59 31](https://github.com/Automattic/wp-calypso/assets/24919469/70f4588a-8d84-419a-943b-6c687e363dea)

### Why

Helps with consistency and users not finding the right option to disable/enable inline post ads.

**Comment by Aurorum** [comment]
PR for this issue in https://github.com/Automattic/wp-calypso/pull/91006. :)
