### ISSUE TITLE
Jetpack Plugins: All Sites Single Plugin View needs an 'Update All' notice

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#910]
This was first reported by @lezama:

Steps to reproduce (bug is in step 7):

1. Connect at least two sites using Jetpack
2. Make sure that at least one site has Jetpack Manage turned on and one site has Jetpack Manage turned off
3. Upload an out-of-date plugin to all sites above (it should be the same plugin for all sites - for example Akismet)
4. Go to WordPress.com > My Sites > View all sites, see that there is an update available for all Jetpack sites:<br>
![screen shot 2015-11-27 at 2 40 20 pm](https://cloud.githubusercontent.com/assets/11487924/11447501/d47ab8da-9514-11e5-9c4a-5116255b40ac.png)
5. Click on one of the sites and go to Plugins. See this:<br>
![screen shot 2015-11-27 at 2 41 36 pm](https://cloud.githubusercontent.com/assets/11487924/11447512/faf2d7d6-9514-11e5-954c-d35c31e55435.png)
6. Click on the plugin that should be updated, see this:<br>
![screen shot 2015-11-27 at 2 42 19 pm](https://cloud.githubusercontent.com/assets/11487924/11447517/179c43d6-9515-11e5-84fe-fbb2efa33d14.png)<br>
So far so good!<br>
7. Click on 'Switch site' and select All Sites instead, and see this:<br>
![screen shot 2015-11-27 at 2 43 14 pm](https://cloud.githubusercontent.com/assets/11487924/11447528/3784b62e-9515-11e5-9d37-bca06ffd01f6.png)<br>
This is incorrect - Akismet is available to be updated on at least some sites, and does need an update on all other sites. The version installed on all the sites is not 3.1.5 (it's 3.0.0 in this example)
8. Go back to the main Plugins page for All Sites, and see this:<br>
![screen shot 2015-11-27 at 2 44 38 pm](https://cloud.githubusercontent.com/assets/11487924/11447536/6a950d52-9515-11e5-9c69-4f8b8b33df9c.png)<br>
Here it is shown that Akismet should be updated, that's good.

The error happens only in step 7. Instead we should display that the plugin needs updating, even though Jetpack Manage is off for some sites, and the plugin cannot be updated for all sites. We should also let the user know that the plugin will be updated only on the sites we can update it on, and not for any of the sites that cannot be updated.

**Comment by lezama** [comment]
@rickybanister, @MichaelArestad, do you have any suggestions on how to handle this case?

**Comment by rickybanister** [comment]
One thought:

A lot of the info in this issue will be outdated once the `Update All` button lands, also this issue doesn't contain any of the SectionHeader work @johnHackworth has been doing. It is likely worth holding off on this until #1044 is merged.

Four ideas:

Once the new notices hit:

<img width="394" alt="screen shot 2015-12-10 at 2 58 45 pm" src="https://cloud.githubusercontent.com/assets/437258/11726829/8a2d59ec-9f4e-11e5-9115-dc1280c0da29.png">

<img width="468" alt="screen shot 2015-12-10 at 2 58 04 pm" src="https://cloud.githubusercontent.com/assets/437258/11726809/76e702b6-9f4e-11e5-8d52-cc7723d333f3.png">

Or with the inline notices:

<img width="701" alt="screen shot 2015-12-10 at 2 59 53 pm" src="https://cloud.githubusercontent.com/assets/437258/11726855/b11f29fe-9f4e-11e5-9338-3d874ab9522a.png">

<img width="745" alt="screen shot 2015-12-10 at 2 56 57 pm" src="https://cloud.githubusercontent.com/assets/437258/11726780/4d28eed0-9f4e-11e5-9d37-138ac7a6fff8.png">

**Comment by rickybanister** [comment]
Also relevant to this issue is this design (I can't find the related issue at the moment):

![slice 1](https://cloud.githubusercontent.com/assets/437258/11727160/5962271e-9f50-11e5-96a1-a265d7f13102.png)

**Comment by MichaelArestad** [comment]
@rickybanister I agree with you 100% on this one.

**Comment by rickybanister** [comment]
Just a note: let's go with `Version X.X.X is available for N sites      [Update All]`

**Comment by johnHackworth** [comment]
@lezama I'm totally stealing this issue from you :D

**Comment by johnHackworth** [comment]
(I started working on it without realizing it was assigned to you, sorry!)

**Comment by lezama** [comment]
works for me :P
