### ISSUE TITLE
Site Migration: Track cases where a `from` param is missing in the URL

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#91019]
p1716406428459539-slack-C0Q664T29

A user can complete the site migration flow without having provided a source site, which leads to a lack of a `from` parameter in the URL. To go through the flow this way:

* Go to `/start`
* Select Import at the goals step
* Do **not** put a URL in at the "Let’s import your content" step; choose "Pick your platform from a list" instead
* Choose WordPress
* Choose Everything
* Check out
* Land on the site migration instructions screen

This is intentional (thanks @gabrielcaires for the context)

Per @daledupreez: 

> We should work out how often this is happening, likely by adding/enriching an existing Tracks event.

**Comment by gabrielcaires** [comment]
Yes, it is intentional, part of it was implemented here https://github.com/Automattic/wp-calypso/pull/88047 and this issue p1709123884789089-slack-C0Q664T29

**Comment by sixhours** [comment]
This was done in #91071
