### ISSUE TITLE
Remove Recommendations from Sidebar

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9102]
UPDATE: We've decided to remove the Recommendations page from the sidebar for Refresh v1. Easy! So the only To Do here is:

- [ ] Remove "Recommendations" link from sidebar
#
- - - - -

The original Refresh designs contained a refreshed version of the Recommendations page.

![new-reader-3-recommendations](https://cloud.githubusercontent.com/assets/24388/19943847/7aff32a6-a0f6-11e6-8d9a-5e3f74a573a9.jpg)

But! Two things:

1. We've decided to focus on the Recommended Posts API instead of the Recommended Sites one,  so we haven't built the API for recommended sites yet, which would be needed for this page (at least, as it's designed here). We could show Rec Posts here instead, but ...

2. If we're successful in getting in-stream Recommended Posts at launch, which we seem on track to accomplish, I think this page becomes unnecessary. In stream recs will be much more powerful anyway.

So! The question: Should we build this page with Recommended Posts? Or should we just discontinue it and remove it from the sidebar, saving us a little pre-launch work?

Any passionate feelings on either side? We could always launch without it and bring it back in later if there's need.

cc @blowery, @bluefuton, @jancavan, @gibrown, @aaronyan, @samouri

**Comment by jancavan** [comment]
@fraying I vaguely remember this, but didn't we use this same design as an empty state for Following? Or did we completely scrap this in favor of the dismissible illustration banners (Welcome to the Reader)?

**Comment by gibrown** [comment]
I'd say get rid of the tab, but use this design for the empty state of Following. Though maybe there is also a search bar on there? I'm not clear where we ended up on adding search relative to timing of other things.

(if we don't have recommended sites then use recommended posts instead)

**Comment by fraying** [comment]
@jancavan I'm not sure what you mean. This is talking about the fate of this page: https://wordpress.com/recommendations

@gibrown Empty Following is all set (it's the big 4 plus in-stream recs). This is just about what happens to https://wordpress.com/recommendations

**Comment by gibrown** [comment]
Ah ok. ya. I think kill that page. Add recommendations in elsewhere

**Comment by jancavan** [comment]
Right, I was just thinking that if we ever built this page, we can probably reuse the code as an empty state for Following. I'd say remove it from the sidebar.

**Comment by aaronyan** [comment]
I think building the Recommendations page will add value. It may not need its own dedicated page though (and sidebar slot).

How about putting this design in the empty Search page (and removing Recommendations from the sidebar)?

Example of Empty Search:
[message]
[search bar]
[recommendations]

Empty Following could have the same content as empty Search but with a different message at the top: "You're currently not following anything. Let's find you some amazing content.".

**Comment by fraying** [comment]
I appreciate that we all have ideas for what to do with all this stuff, but again, this issue is only to decide what to do with the existing recommendations page.

So! We have a decision: We're removing it from the sidebar for Refresh v1. Cool?

**Comment by fraying** [comment]
@aaronyan As you can see in https://github.com/Automattic/wp-calypso/issues/9106, Search is already what you were suggesting here. Great minds think alike!

**Comment by fraying** [comment]
Note: We currently send this email to new members.

So if/when we remove the Recommendations tag, we need to disable this email as well.

![screen shot 2016-11-11 at 11 35 39 am](https://cloud.githubusercontent.com/assets/24388/20227869/55790408-a803-11e6-9e19-ef07384462bb.png)

cc @blowery

**Comment by fraying** [comment]
UPDATE: I spoke with @meremagee and the emails above are slated to be discontinued before Refresh launch, so it should be a nonissue.
