### ISSUE TITLE
Segmentation Survey: Fix wrong Group By on the GET /answers endpoint

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#91075]
<img width="815" alt="333347511-8df37bad-3176-48de-b501-25a8a6b4b88d" src="https://github.com/Automattic/wp-calypso/assets/3113712/73abe5cd-d755-4b16-bb59-8f155e12573c">

**Comment by ivan-ottinger** [comment]
Resolved in D149981-code.
