### ISSUE TITLE
Shortcode block converting to embed/paragraph block after trying to add a link

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#91084]
### Quick summary

This is a test I've done only using Google Maps.

### Steps to reproduce

1. Create a new page
2. Add a shortcode block
3. Type in [googlemaps 
4. Try to paste the Google Maps link
5. Check if the block converted itself into an embed block or paragraph

### What you expected to happen

To just paste the link in there and close the shortcode

### What actually happened

It converted either to Embed or Paragraph.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

Video: 
https://github.com/Automattic/wp-calypso/assets/6737345/886d9bfa-6337-4ac3-bef2-6abf607f6f6f

Found in 8231469-zen

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/14153300/058e0110-d909-496b-a776-3e5112e26a56




📌 ACTIONS
- Triaged
- Core issue: https://github.com/WordPress/gutenberg/issues/61377
- Also related: https://github.com/Automattic/wp-calypso/issues/91097#top

**Comment by liviopv** [comment]
Fixed in 18.4. Closing.
