### ISSUE TITLE
Command palette: Consistent focus styles in footer

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#91105]
#### Steps to reproduce

1. Go to /home/:site
2. Invoke command palette with `⌘k`
3. Use tab to focus the links in the footer
4. Notice that the focus borders are a grey dotted style
5. Go to /wp-admin on the same site
6. Invoke command palette with `⌘k`
7. Use tab to focus the links in the footer
8. Notice that the focus borders are a blue solid style

#### What I expected

The focus styles to match, they should use the Calypso (grey dotted) ones.

#### What happened instead

The focus styles in wp-admin use a blue solid style

#### Screenshot / Video

wp-admin | Calypso
-------|------
 ![image](https://github.com/Automattic/wp-calypso/assets/93301/bb6eb607-c517-433d-9862-ea948daf2e41)| ![image](https://github.com/Automattic/wp-calypso/assets/93301/b360e9ef-dced-4841-b534-31bdc5dcf445)

#### Context / Source

@javierarce reported while testing

**Comment by rcrdortiz** [comment]
These changes are now live
