### ISSUE TITLE
Simple Site Hosting Config redirects to Dev Tools and prompts to purchase a plan instead of activate hosting features

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#91134]
### Quick summary

https://wordpress.com/hosting-config/ is now redirecting to https://wordpress.com/dev-tools/exampletestsite.wordpress.com and that Notice that says,  "Please activate the hosting access to begin using these features." with the button labeled "Activate" on the right side is no longer showing, instead you're told to upgrade your plan when you already have a paid plan. 

### Steps to reproduce

1. Create a new Simple Site 
2. Purchase a Creator plan 
3. Go to My Site >  Hosting Configuration 

### What you expected to happen

I expect to see: 

> Please activate the hosting access to begin using these features 

![image](https://github.com/Automattic/wp-calypso/assets/29527450/badacbcc-058f-49a4-b3dd-0ee300c74f42)

And not be asked to upgrade my plan since I already have a Creator plan. 

### What actually happened

Instead, you're redirected to and prompted to upgrade my plan even though my site already purchased a Creator plan: 

<img width="1643" alt="image" src="https://github.com/Automattic/wp-calypso/assets/29527450/6bcf82b5-a265-4233-974a-0bcf8eb8272c">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The easy workaround is to install any plugin or custom theme to initiate the AT transfer.

**Comment by taipeicoder** [comment]
This redirect should only affect proxied users accessing the staging environment. In case users in production are experiencing this issue, please let me know.

See p1716600861719809/1716577991.331869-slack-CB0B2G43X for more context, thanks!

**Comment by rickmgithub** [comment]
## 📌 ACTIONS ##

- Based on the response to the thread it looks like this only effects HEs viewing a site through proxy.
- I looked at the tickets and couldn't see any indication that the users had also seen the issue. I asked p1716967829696939/1716561546.618179-slack-C03TY6J1A just in case.
- Right now there are only 2 reports, so closing this pending reopening if it's a blocker for HEs, or a problem for users.
