### ISSUE TITLE
Unable to detach synced patterns on a few sites using Creatio 2 and Assembler

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#91203]
### Quick summary

Although we've had inconsistent results, I was able to reproduce this one. new Atomic site with Creatio 2.
There are reports with the Assmbler theme too.

### Steps to reproduce

Here is a list of all the steps I took:

1. Made site Atomic;
2. Duplicated a default pattern to create a new synched pattern;
3. Proceeeded to add it to a page
4. Attempted to detach it and nothing happened

### What you expected to happen

The synched pattern should detach from the original pattern, allowing users to edit it without changing the original pattern.

### What actually happened

The detach causes no change.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Changing the theme (in my case, to Assembler) solved the issue on my test site. When I reactivated the previous theme, everything worked as expected.

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
I also couldn't replicate it at first but then was able to but on a simple site.

Steps I took
1) Create an entirely new site, not an existing one.
2) Set it up on the Explorer plan and make sure the Creatio 2 theme is installed
3) Now go to a page in the site editor
4) Add a "pattern", any will do but I picked ???
5) Duplicate that pattern
6) Set up the new pattern as a synced pattern
7) Duplicate this
8) Now try to "detach" the new synced pattern. 
9) However many times you click on the Detach link, nothing happens. 


## 📌 FINDINGS/SCREENSHOTS/VIDEO ##



https://github.com/Automattic/wp-calypso/assets/13706336/28677948-5a43-494f-a87b-a1e4f3d86f95

## 📌 ACTIONS ##
Triaged

**Comment by annezazu** [comment]
I couldn't replicate this on a previously built simple site (https://testttting179142315.wordpress.com/) and a new simple site (https://satetkalsjgse.wordpress.com/). I replicated a pattern, made it synced, added it to both a post or page, and had no problem detaching. I ddi all of this using the Creatio 2 theme:

https://github.com/user-attachments/assets/e6188cf9-e9ed-43a8-8156-bf04bf56aced

Can anyone still replicate?

**Comment by annezazu** [comment]
Closing this out as I can't replicate. Let's please reopen if anyone can!
