### ISSUE TITLE
/me: Part of the navigation is impossible to see (Untangling Calypso)

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#91225]
### Quick summary

While comparing a screenshot @davemart-in shared in Slack, I realized that I can't see part of `/me` navigation. Here's the comparision:

Dave's view | My view |
--- | --- |
![image 32](https://github.com/Automattic/wp-calypso/assets/25607244/6aca7c4b-483e-492b-be93-6c81f6385c69) | <img width="305" alt="Screenshot 2024-05-29 at 09 31 35" src="https://github.com/Automattic/wp-calypso/assets/25607244/276575f2-75c9-45dd-8211-6df961c89e70"> | 

I can see it if I zoom out. I'm using a 4k monitor (1920x1080, with device-pixel-ratio of 2).
The initial view is Chrome at 100%. Only when I decrease it to 80% I can see all the items. I can't scroll that part of the screen.

https://github.com/Automattic/wp-calypso/assets/25607244/64381107-434c-4dda-b11c-905dcf8bd452

### Steps to reproduce

1. Log in with your WPcom account
2. Navigate to `/me` and check if you can see the `Apps` menu item

### What you expected to happen

The entire navigation should be visible at 100% zoom (the default).

### What actually happened

I can't see part of the navigation.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

**Comment by davemart-in** [comment]
Thanks for sharing the screenshot. It looks like we're seeing the same thing—I had just scrolled up the left navigation a bit before taking my screenshot.

![CleanShot 2024-05-29 at 04 32 06](https://github.com/Automattic/wp-calypso/assets/5634774/a066a06c-e5fc-401e-a178-663adff83b1d)

We might be able to show more of the links by reducing the size of the avatar image at the top. However, I'm not entirely sure if we'll be able to fit all the links in view without any scrolling on a standard laptop resolution.

**Comment by crisbusquets** [comment]
> Thanks for sharing the screenshot. It looks like we're seeing the same thing—I had just scrolled up the left navigation a bit before taking my screenshot.

The main issue is that I can't scroll there unless I'm using the trackpad. The browser scrolls the content part, not the navigation.

Also, I didn't know there was content below the last option I saw, and I'm guessing this happens to some of our customers too.

**Comment by Aurorum** [comment]
This is particularly problematic on tablets; for instance, I can’t access my purchases on iPad without using the direct link.

![B941FA2E-57B0-43E4-8915-E0DAF85D7458](https://github.com/Automattic/wp-calypso/assets/43215253/88e98092-a9ff-4adf-94f6-c8e2f75e498f)

**Comment by lucasmendes-design** [comment]
Can we mimic dotorg here? 

Example: 
- Once users hover over the sidebar, a scroll bar will appear. 
- I believe this way, it's easy to implement and doesn't require any additional UI or new affordance. 

https://github.com/Automattic/wp-calypso/assets/98343583/e60b14c8-2b33-4351-8051-5b82079cf4ad

**Comment by lucasmendes-design** [comment]
Example: 
<img width="592" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/14784d3f-58e8-449f-af61-fbe0f29d1c60">

**Comment by davemart-in** [comment]
Let's give it a try! I'll pull together a quick PR.

**Comment by Addison-Stavlo** [comment]
>  Once users hover over the sidebar, a scroll bar will appear.
> I believe this way, it's easy to implement and doesn't require any additional UI or new affordance.

Should we just show a scrollbar all the time when the container enables scrolling?

The hover approach doesn't resolve the issue for touch devices, such as what @Aurorum [noted above](https://github.com/Automattic/wp-calypso/issues/91225#issuecomment-2198494707) with tablets.

**Comment by Addison-Stavlo** [comment]
Ok, I was looking into this and it was a bit confusing as there are a couple things at play.

This [PR](https://github.com/Automattic/wp-calypso/pull/92342) removes a (now) unnecessary rule that ended up hiding the scroll bar altogether.

With that, you still may not notice the scrollbar when hovering into that area, and only see it appear when you start scrolling. This seemed similar but subtly different between different browsers. I found that I have to turn on a system setting on my mac corresponding to scroll behavior to resolve this (Show scroll bars: Always):

<img width="708" alt="Screenshot 2024-07-03 at 3 23 11 PM" src="https://github.com/Automattic/wp-calypso/assets/28742426/d5b5a47b-10ac-40a1-ab16-4263444355eb">

The combination of that PR and that system setting should give the desired behavior.

**Comment by lucasmendes-design** [comment]
> Ok, I was looking into this and it was a bit confusing as there are a couple things at play.

Thanks for digging into this. We can add a gradient at the bottom when the scroll is needed. 

<img width="1622" alt="jndo238423" src="https://github.com/Automattic/wp-calypso/assets/98343583/a128598b-05f4-4a23-beff-3105b424cc29">

**Comment by lucasmendes-design** [comment]
This way we don't need to rely on OS specific settings

**Comment by davemart-in** [comment]
I suspect this issue will largely go away with the latest nav updates (which will remove the global left nav footer).

**Comment by lucasmendes-design** [comment]
+1.

**Comment by Addison-Stavlo** [comment]
I think this has been resolved since https://github.com/Automattic/wp-calypso/issues/91225#issuecomment-2207032430
