### ISSUE TITLE
Reader Stream Refresh: Some images missing in gallery card

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9123]
As pointed out by @blowery [here](https://github.com/Automattic/wp-calypso/pull/8872#issuecomment-257952952):

Seeing something odd on http://calypso.localhost:3000/read/feeds/23920982

<img width="1516" alt="d9ea3d3c-a106-11e6-950c-53d8480c400a" src="https://cloud.githubusercontent.com/assets/4924246/19978781/4f85c51c-a1b5-11e6-88f1-677aa732407a.png">

You're also unable to Follow this particular feed.

**Comment by jancavan** [comment]
Same thing happens on this site: https://wpcalypso.wordpress.com/read/feeds/55576197

![screenshot 2016-11-08 09 21 39](https://cloud.githubusercontent.com/assets/4924246/20109419/d0b3460e-a594-11e6-8031-b59d963c9bc1.png)

**Comment by bluefuton** [comment]
Seems to be caused by malformed image URLs that are then dropped from the style declaration.
