### ISSUE TITLE
Sites management page: Renamed site addresses should not be listed as deleted sites

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#91259]
### Quick summary

We now allow users to self-serve restore deleted sites within 30 days, and all eligible deleted sites are listed on the site management page (`wordpress.com/sites`). When changing a Simple site's free `.wordpress.com` address, the old address is considered a "deleted site," and shows up on the `/sites` page to restore when it cannot be restored (as per https://wordpress.com/support/changing-site-address/#reuse-other-word-press-com-site-addresses).

### Steps to reproduce

1. Create a new site with no plan or a Simple site plan.
2. Navigate to Upgrades > Domains.
3. Click the kebab/3-dot menu next to the free site address and choose the option to change your free site address. Follow the prompts as outlined in https://wordpress.com/support/changing-site-address/#change-your-word-press-com-site-address
4. After confirming, navigate to https://wordpress.com/sites/
5. See that the original/old site address is listed as a "deleted" site with a restore option. Click restore, and see `Only an administrator can restore a deleted site.` error.

### What you expected to happen

The old site address should not be listed on the `/sites` page as a deleted site as it cannot be recovered. 

### What actually happened

The old site address is listed as a deleted site, and attempting to restore it yields a confusing error message.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported in https://wordpress.com/forums/topic/deleted-correct-free-domain-dot-wordpress-com/
Also reported in https://github.com/Automattic/wp-calypso/issues/89826#issuecomment-2095830945 (8145699-zd-a8c).

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
1. Changed site address from fseone.wordpress.com to gutenbergtestone.wordpress.com
2. Filtered my sites by "Deleted"

![CleanShot 2024-05-31 at 11 20 48@2x](https://github.com/Automattic/wp-calypso/assets/14153300/3838458c-866a-4ef0-ab33-61cab2cd4cdd)


📌 ACTIONS
- Triaged

@Automattic/quake is this intentional? It feels confusing as those URLs can't be recovered, unlike regular deleted sites.

**Comment by vykes-mac** [comment]
Thanks @liviopv for reporting this, no it's not intentional. It's a bug

**Comment by vykes-mac** [comment]
Fix was deployed here D150762-code
