### ISSUE TITLE
Customizer Menu: Adding Project Types items as a Category

### ISSUE THREAD

**Issue by isocialtish** [Automattic/wp-calypso#9127]
When adding a Project Type to the menu within the Customizer and the Project Type has the same name as a Category, the Project Type is added as a "Category".

#### Steps to reproduce
Step 1: Add “test” as a Project Type
Step 2: Add “test” as a Category 
Step 3: Navigate to Customizer> Menu> Add New Item
Step 4: Click “Project Type” and add “Test” to the menu
Step 5: Note that “test” was added as a “Category”

#### What I expected
To be able to add a Project Type to my menu

#### What happened instead
A Project Type was added as a Category Page

#### Browser / OS version
Reproduced in Mac OS Sierra 10.12.1
Using Chrome 54.0.2840.71

#### Screenshot / Video
![project type bug](https://cloud.githubusercontent.com/assets/6664819/19982012/88290a4e-a1c1-11e6-9d95-13ddc7cde221.gif)

#### Context / Source

#user-report #livechat

**Comment by lancewillett** [comment]
Thanks for the report.

**Comment by lancewillett** [comment]
Closed as this isn't a bug in Calypso (Customizer still loads from wp-admin).

**Comment by SiobhyB** [comment]
Re-opening as the Customizer now loads in Calypso and I can still replicate this issue. The recent comment in the repo this was moved to advised us to now report this to the Calypso repo.
