### ISSUE TITLE
HTML Block - Preview button: Unconsistent Javascript Code Handling Depending On Browser

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#91287]
### Quick summary

In the editor, when one tries to preview some HTML content that has JS code in it, In some browsers it renters almost fully, in another browser the JS code is just ignored.

Typically with the follow-button code mentioned here: 
[developer.wordpress.com/docs/follow-button-creation](p2gHKz-pR4-p2)

### Steps to reproduce

1. Generate/Grab the HTML code from here: [developer.wordpress.com/docs/follow-button-creation](p2gHKz-pR4-p2)
2. Add an HTML block to a page
3. Add the JS code to it
4. Press preview in the HTML code
5. Try that on Firefox, Safari, and Chrome to see different results - Some show the actual follow button, and some show a link. 

### What you expected to happen

It's unclear what the original behavior should be, but the expectation is to get the same result on all browsers.

### What actually happened

Different results on different browsers. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by mxhassani** [comment]
8255456-zen

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
The preview for the code in the instructions work on all browsers for me

![CleanShot 2024-05-31 at 11 58 12@2x](https://github.com/Automattic/wp-calypso/assets/14153300/b3c2c80e-3591-4c15-910d-d531ef46a0ec)

📌 ACTIONS

- Closed as could not replicate (please reopen if the issue reoccurs)


📌 Message to Author
@mxhassani I couldn't repro with the code you shared, but I'm unsure if the block is even designed to preview *any* JS code correctly, tbh.
