### ISSUE TITLE
Reader: Removing a tag in the reader sidebar doesn't stick

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#913]
When I click the X to remove a tag in the Reader sidebar, it does not delete. It does initially disappear, but the then reappears a second or two later. This was tested in the Mac desktop app v1.0.1 and in Chrome.

![image-drop](https://cloud.githubusercontent.com/assets/1464705/11448855/1a0da5cc-9517-11e5-8004-c83b99481156.gif)

**Comment by bluefuton** [comment]
Hmm - not able to reproduce this one @apeatling (on Mac desktop app v1.0.1 or Chrome). The API call to `read/tags/:tag/mine/delete` seems to succeed and the tag doesn't reappear for me.

If you run this on a local development copy of Calypso, can you see anything peculiar in the console when attempting the tag delete? If you check the Network tab, what's the response from that API call?

**Comment by apeatling** [comment]
Doesn't seem to be happening for me any more. Not sure what changed.

**Comment by bluefuton** [comment]
Thanks @apeatling - it looked like an unexpected API response may have caused it, and if so we could handle that scenario more gracefully. Let us know if it happens again.
