### ISSUE TITLE
Reader Full Post: Happy Chat overlaps with article

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9130]
If Happy Chat is open, it sits on top of the article. 

I poked at this for a bit this morning, but not quite sure how to fix it yet.

![screenshot 2016-11-03 13 06 27](https://cloud.githubusercontent.com/assets/4924246/19983246/7653d074-a1c6-11e6-869c-4e96acd7a73d.png)

**Comment by fraying** [comment]
I'd suggest not worrying about this for now. Smells like it could take a lot of time and it's not SO bad of an experience. We'll fix it! Just not a as high a priority as the rest of the stuff in this milestone.

**Comment by bluefuton** [comment]
User can minimise the chat window now, so not too concerned about this :)
