### ISSUE TITLE
Feature request to mute specific blogs in the "recent" section, without blocking them. 

### ISSUE THREAD

**Issue by tavilla61** [Automattic/wp-calypso#91317]
### What

User requested the ability to mute some blogs in the Recent section, without actually blocking the blogs. 

Reference: ticket https://a8c.zendesk.com/agent/tickets/8242976

### Why

They don't want to unfollow or block some blogs, but don't always want to see the content and want the ability to temporarily mute them.

**Comment by davemart-in** [comment]
We are probably not going to do this. :-) Lists would be a workaround. You can add whatever sites you want to a list and it acts just like the recent feed.
