### ISSUE TITLE
Reader: Refreshed Streams Stats Audit

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#9131]
Make sure we're capturing all the same stats, in equivalent ways, for the refreshed streams.

**Comment by samouri** [comment]
Pulling from our previous [stats audit](https://github.com/Automattic/wp-calypso/issues/8300#issuecomment-250311524)

this is a WIP

Relevant stream stats
================
1. [ ] **calypso_reader_article_closed** -- nothing firing
1. [ ] **calypso_reader_full_post_like_button_clicked** -- nothing firing
1. [ ] **calypso_reader_related_post_clicked** -- nothing firing
1. [ ] **calypso_reader_related_post_site_clicked** -- nothing firing
1. [ ] **calypso_reader_author_link_clicked**  only tracks event not firing
1. [x] calypso_reader_article_commented_on
1. [x] calypso_reader_article_liked
1. [x] calypso_reader_article_opened 
1. [x] calypso_reader_article_unliked 
1. [x] calypso_reader_comment_author_click 
1. [x] calypso_reader_comment_reply_cancel_click 
1. [x] calypso_reader_comment_reply_click 
1. [x] calypso_reader_edit_post_clicked 
1. [x] calypso_reader_full_post_comments_button_clicked 
1. [x] calypso_reader_permalink_click 
1. [x] calypso_reader_post_comments_button_clicked 
1. [x] calypso_reader_liked_comment

All Reader Stats
==========
1. ~~calypso_reader_article_closed~~
1. ~~calypso_reader_article_commented_on~~
1. ~~calypso_reader_article_liked~~
1. ~~calypso_reader_article_opened~~
1. ~~calypso_reader_article_unliked~~
1. ~~calypso_reader_author_link_clicked~~
1. ~~calypso_reader_comment_author_click~~
1. ~~calypso_reader_comment_reply_cancel_click~~
1. ~~calypso_reader_comment_reply_click~~
1. ~~calypso_reader_edit_post_clicked~~
1. ~~calypso_reader_full_post_comments_button_clicked~~
1. ~~calypso_reader_full_post_like_button_clicked~~
1. ~~calypso_reader_permalink_click~~
1. ~~calypso_reader_post_comments_button_clicked~~
1. ~~calypso_reader_related_post_clicked~~
1. ~~calypso_reader_related_post_site_clicked~~
1. ~~calypso_reader_share_action_picked~~
1. ~~calypso_reader_share_opened~~
1. ~~calypso_reader_share_to_site~~
1. ~~calypso_reader_liked_comment~~
1. calypso_reader_feed_link_clicked
1. calypso_reader_clicked_featured_post
1. calypso_reader_add_list_clicked
1. calypso_reader_add_tag_clicked
1. calypso_reader_author_on_discover_card_clicked
1. calypso_reader_block_error_dismissed
1. calypso_reader_block_site
1. calypso_reader_blog_preview
1. calypso_reader_create_list_clicked
1. calypso_reader_daily_post_challenge_opened
1. calypso_reader_daily_post_challenge_site_picked
1. calypso_reader_discover_on_empty_Posts_stream_clicked
1. calypso_reader_discover_on_empty_feed_clicked
1. calypso_reader_discover_on_empty_like_stream_clicked
1. calypso_reader_discover_on_empty_list_stream_clicked
1. calypso_reader_discover_on_empty_manage_following_clicked
1. calypso_reader_discover_on_empty_search_stream_clicked
1. calypso_reader_discover_on_empty_site_stream_clicked
1. calypso_reader_discover_on_empty_stream_clicked
1. calypso_reader_discover_on_empty_tag_stream_clicked
1. calypso_reader_discover_on_feed_error_clicked
1. calypso_reader_discover_on_missing_list_clicked
1. calypso_reader_discover_site_followed
1. calypso_reader_discover_site_unfollowed
1. calypso_reader_discover_viewed
1. calypso_reader_empty_manage_following_loaded
1. calypso_reader_filled_gap
1. calypso_reader_follow_error_dismissed
1. calypso_reader_following_loaded
1. calypso_reader_following_on_empty_Posts_stream_clicked
1. calypso_reader_following_on_empty_like_stream_clicked
1. calypso_reader_following_on_empty_list_stream_clicked
1. calypso_reader_following_on_empty_search_stream_clicked
1. calypso_reader_following_on_empty_tag_stream_clicked
1. calypso_reader_following_on_missing_list_clicked
1. calypso_reader_infinite_scroll_performed
1. calypso_reader_list_loaded
1. calypso_reader_load_new_posts
1. calypso_reader_post_gallery_
1. calypso_reader_post_options_menu_
1. calypso_reader_post_reported
1. calypso_reader_reader_list_followed
1. calypso_reader_reader_list_unfollowed
1. calypso_reader_reader_tag_followed
1. calypso_reader_reader_tag_unfollowed
1. calypso_reader_recommendations_on_empty_feed_clicked
1. calypso_reader_recommendations_on_empty_manage_following_clicked
1. calypso_reader_recommendations_on_empty_site_stream_clicked
1. calypso_reader_recommendations_on_empty_stream_clicked
1. calypso_reader_recommendations_on_feed_error_clicked
1. calypso_reader_recommendations_start_loaded
1. calypso_reader_recommendations_start_search_performed
1. calypso_reader_recommended_site_clicked
1. calypso_reader_search_loaded
1. calypso_reader_search_performed
1. calypso_reader_search_suggestion_click
1. calypso_reader_searchcard_clicked
1. calypso_reader_sidebar_list_toggle
1. calypso_reader_sidebar_tags_toggle
1. calypso_reader_site_followed
1. calypso_reader_site_on_discover_card_clicked
1. calypso_reader_site_unfollowed
1. calypso_reader_start_follow_by_url_link
1. calypso_reader_startcard_clicked
1. calypso_reader_tag_clicked
1. calypso_reader_tag_loaded
1. calypso_reader_unblock_site

**Comment by blowery** [comment]
TODO
- [ ] calypso_reader_reader_list_followed
- [ ] calypso_reader_reader_list_unfollowed
- [ ] calypso_reader_empty_manage_following_loaded
- [ ] calypso_reader_author_on_discover_card_clicked
- [ ] calypso_reader_block_error_dismissed
- [ ] calypso_reader_daily_post_challenge_opened  ?
- [ ] calypso_reader_daily_post_challenge_site_picked  ?
- [ ] calypso_reader_discover_site_followed
- [ ] calypso_reader_discover_site_unfollowed
- [ ] calypso_reader_filled_gap
- [ ] calypso_reader_follow_error_dismissed
- [ ] calypso_reader_following_on_empty_Posts_stream_clicked
- [ ] calypso_reader_following_on_empty_like_stream_clicked
- [ ] calypso_reader_following_on_empty_list_stream_clicked
- [ ] calypso_reader_following_on_empty_search_stream_clicked
- [ ] calypso_reader_following_on_empty_tag_stream_clicked
- [ ] calypso_reader_following_on_missing_list_clicked
- [ ] calypso_reader_recommendations_on_empty_feed_clicked
- [ ] calypso_reader_recommendations_on_empty_manage_following_clicked
- [ ] calypso_reader_recommendations_on_empty_site_stream_clicked
- [ ] calypso_reader_recommendations_on_empty_stream_clicked
- [ ] calypso_reader_recommendations_on_feed_error_clicked
- [ ] calypso_reader_recommendations_start_loaded
- [ ] calypso_reader_recommendations_start_search_performed
- [ ] calypso_reader_recommended_site_clicked
- [ ] calypso_reader_site_on_discover_card_clicked
- [ ] calypso_reader_start_follow_by_url_link
- [ ] calypso_reader_startcard_clicked
- [ ] calypso_reader_discover_on_empty_Posts_stream_clicked
- [ ] calypso_reader_discover_on_empty_feed_clicked
- [ ] calypso_reader_discover_on_empty_like_stream_clicked
- [ ] calypso_reader_discover_on_empty_list_stream_clicked
- [ ] calypso_reader_discover_on_empty_manage_following_clicked
- [ ] calypso_reader_discover_on_empty_search_stream_clicked
- [ ] calypso_reader_discover_on_empty_site_stream_clicked
- [ ] calypso_reader_discover_on_empty_stream_clicked
- [ ] calypso_reader_discover_on_empty_tag_stream_clicked
- [ ] calypso_reader_discover_on_feed_error_clicked
- [ ] calypso_reader_discover_on_missing_list_clicked

**Comment by blowery** [comment]
calypso_reader_discover_site_followed
 calypso_reader_discover_site_unfollowed

these two are missing. Need to tack them into the follow from the discover stream.

**Comment by blowery** [comment]
calypso_reader_author_on_discover_card_clicked

we no longer have the author on the discover cards.

**Comment by blowery** [comment]
calypso_reader_block_error_dismissed

we're not showing block errors properly

**Comment by blowery** [comment]
`calypso_reader_follow_error_dismissed`

We're not showing any error when follow errors occur.

**Comment by blowery** [comment]
calypso_reader_recommendations_on_empty_feed_clicked
 calypso_reader_recommendations_on_empty_manage_following_clicked
 calypso_reader_recommendations_on_empty_site_stream_clicked
 calypso_reader_recommendations_on_empty_stream_clicked
 calypso_reader_recommendations_on_feed_error_clicked
 calypso_reader_recommendations_start_loaded
 calypso_reader_recommendations_start_search_performed
 calypso_reader_recommended_site_clicked

we no longer have a recommended page. need to fix all of these links to point to search.

**Comment by blowery** [comment]
Closing this, as all parts are covered elsewhere.
