### ISSUE TITLE
Reader: Clicking back to a List from a post goes to the top of the page

### ISSUE THREAD

**Issue by staproehl** [Automattic/wp-calypso#91314]
### Quick summary

When clicking back to a List in the Reader after viewing a post, the user is taken to the top of the page, rather than the post they had clicked on. This only happens with Lists, not with Recent, Discover, Likes, Conversations, or Tags.

### Steps to reproduce

1. Start at WordPress.com/read
2. Go to a List feed
3. Scroll down the page until you don't see the top of the Reader
4. Click on a Post
5. Click on the "back" link or the back button in the browser

### What you expected to happen

The user is taken to the position in the feed where the post that was viewed is.

### What actually happened

The user is taken to the top of the page

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Screen recording: https://github.com/Automattic/wp-calypso/assets/145057843/0a74bddd-1775-4179-a429-a37e10fbc0fa

zen-8250259

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
1. Opened one of my Reader lists
2. Scrolled down
3. Clicked on a post
4. Clicked on "Back"
5. I was back to the top of the List's feed

📌 ACTIONS
- Triaged

**Comment by davemart-in** [comment]
I wonder if this is similar to https://github.com/Automattic/dotcom-forge/issues/7272?

**Comment by Addison-Stavlo** [comment]
This seems related to both Automattic/dotcom-forge#7272 and https://github.com/Automattic/loop/issues/181

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/91731 should resolve
