### ISSUE TITLE
Connected Email Not Working

### ISSUE THREAD

**Issue by sophiem2** [Automattic/wp-calypso#91318]
### Quick summary

The email which i have connected to my wordpress.com site is not working and I can't log in to it. Additionally images on my site aren't loading and everything is too slow to use. 

### Steps to reproduce

Started at CP Panel where my email is, and it is hosted by wordpress now. Attempted to log in

### What you expected to happen

I expected to log in to my email

### What actually happened

It said my login details were invalid despite there definitely being correct

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by liviopv** [comment]
Hi @sophiem2! This is a public repository used by WordPress.com developers to build the custom interface available on https://wordpress.com. It's not the place where we answer support requests :)

If your site is hosted at WordPress.com, you can contact us from help@wordpress.com or through the forums https://wordpress.com/forums/.

If your site is a self-hosted WordPress.org site, please contact your hosting provider or post to the WordPress.org forums https://wordpress.org/support/forums/
