### ISSUE TITLE
Reader: Need action button for daily post prompts on refresh cards

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#9133]
It's currently missing. Should probably just put it in the excerpt like we did before?

Current:
<img width="745" alt="the_daily_post_ _reader_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/14350/19984347/5670fd36-a1e4-11e6-8786-c15dd67e6cca.png">

**Comment by fraying** [comment]
Yes please.

**Comment by fraying** [comment]
🎉
