### ISSUE TITLE
Editor: can't copy page URL 

### ISSUE THREAD

**Issue by msdesign21** [Automattic/wp-calypso#9134]
#### Steps to reproduce
1. When editing a page it is not possible to copy the text for the URL of the page:
![](http://cld.wthms.co/TkHJ/5HuyturH+)
Image Link: http://cld.wthms.co/TkHJ/5HuyturH 
2. I can't highlight the full URL to copy
3. Selecting the link icon only copies `how-to-be-a-woo-buddy`

#### What I expected
To be able to copy the full URL. 

#### What happened instead
Selecting the link icon only copies `how-to-be-a-woo-buddy` and trying to drag my cursor to highlight the full URL is disabled for some reason. 

#### Browser / OS version
Chrome Version 54.0.2840.71  
OS 10 - 10.11.6

#### Screenshot / Video
![](http://cld.wthms.co/wvG1/m9ciGFjF+)
Image Link: http://cld.wthms.co/wvG1/m9ciGFjF 

#### Context / Source
#stresscase #painpoint #frustrating 

@artpi suggested I log this issue here.

**Comment by artpi** [comment]
The page link: PCYsg-8VG-p2
Blame me in case of oxygen in the open issues for the gif.

**Comment by mtias** [comment]
@timmyc perhaps we can show the "copy" button on hover.

**Comment by nitrajka** [comment]
Hi, 
couldn't be a [clipboard](https://davidwalsh.name/clipboard) implemented? It's not big. However, I don't think you want to add a new dependency to Calypso. 
The [clipboard.js](https://clipboardjs.com/) library.

**Comment by lancewillett** [comment]
This is working for Posts really well now. Needs to be ported to Pages.

<img width="911" alt="screen shot 2018-04-05 at 13 41 21" src="https://user-images.githubusercontent.com/66797/38390750-1325125c-38d7-11e8-8b58-b7b5c3a0d07c.png">

**Comment by mattsherman** [comment]
As part of this fix, do we want to make the display of page permalinks consistent with how post permalinks are displayed?

Currently, page permalinks are always displayed under the page title. Post permalinks are displayed in a popover upon clicking the link icon.

I imagine that page permalinks might be edited more frequently than post permalinks and thus worthy of being always visible. So, perhaps the inconsistency is actually desired?

Any thoughts @mtias or @shaunandrews?

Page permalink:

<img width="514" alt="screencapture at wed jun 6 10 17 45 edt 2018" src="https://user-images.githubusercontent.com/2098816/41043997-3339c610-6973-11e8-94c0-7d291ff067c5.png">

Post permalink:

<img width="611" alt="screencapture at wed jun 6 10 18 50 edt 2018" src="https://user-images.githubusercontent.com/2098816/41044012-391007d4-6973-11e8-89cb-3ce6cd527200.png">

**Comment by shaunandrews** [comment]
> page permalinks consistent with how post permalinks are displayed

Yes, I think that makes sense.

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on issue count.

Is this still a relevant issue today? I used the block editor to play around with links, but I was not able to observe the copy link button when working with links in paragraphas.

![Screen Shot 2021-01-29 at 13 42 11](https://user-images.githubusercontent.com/6549265/106330299-cef7c600-6237-11eb-9b2c-c2d1d9474096.png)

Would it be acceptable to close this issue and apply the label `Closed - Won't Fix`?

**Comment by mattsherman** [comment]
> Would it be acceptable to close this issue and apply the label Closed - Won't Fix?

Yes, as this issue refers to the older editor, not the block editor.
