### ISSUE TITLE
Media Section: Section item doesn't have add button

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#9135]
The media section is the only item in publish that doesn't have an add button. 

<img width="273" alt="4c4ccd46-a052-11e6-9386-65dcd5fc7fd5" src="https://cloud.githubusercontent.com/assets/1270189/19986394/bec379a6-a1d3-11e6-8d8c-fbcfbfb6db05.png">

( Updated by @gwwar )
As a first pass, let's do as @iamtakashi suggested and
- [ ] Add the add button to the sidebar
- [ ] Clicking on Add opens the media section with the file picker open
![18a66264-f92f-11e6-817e-63e706785e87](https://cloud.githubusercontent.com/assets/1270189/23384744/e510fca4-fd00-11e6-82d3-fc8bc61fe6f5.jpg)
 (Let us know if there are browser limitations)

**Comment by lamosty** [comment]
To clarify: media section is not enabled on prod. After https://github.com/Automattic/wp-calypso/pull/9141 is merged, it'll be enabled everywhere except stage/prod/desktop.

**Comment by lancewillett** [comment]
Ran into this myself today with trying to upload something to my photo blog — but in this case didn't want to start a post first. Would be great to match the other "add" buttons for consistency, it felt odd.

<img width="404" alt="add-media-button" src="https://cloud.githubusercontent.com/assets/66797/23036395/e96a1016-f43f-11e6-8a30-efc1323a30f5.png">

#reallife #flowsharing

**Comment by rralian** [comment]
I agree that it would be ideal to match the "add" button for media. A couple of options;
1. Open a file-selection dialog (just like the "add new" button from the media page), and then navigate to the media section upon file selection.
2. Open a page with a drag-drop interface, like we do in wp-admin
![wp-admin example](https://cloudup.com/clPTDiQUCRF+)

I'm not sure which would be simpler to implement, I'm thinking the second one, and it would also be a little more clear.

**Comment by gwwar** [comment]
> Open a page with a drag-drop interface,

The entire media section is already a drag and drop interface. We could maybe have the prompt visible in the add case perhaps? cc @iamtakashi

**Comment by rralian** [comment]
Main thing is we should be explicit about what we expect to happen when someone clicks the "add" button. I'm a little concerned that just opening the file selector from that button will feel like it lacks context (especially if you're coming from a different section). Whereas just having the button navigate to the media section without any differentiation begs the question of why there's a separate "add" button versus the "media" link. It might be nice for the "add" button to navigate to the media section with some additional instructions about the ability to drag/drop, which otherwise isn't very discoverable. And it's not obvious you can drag a big set of files, or which files we support.

**Comment by iamtakashi** [comment]
Thanks for bringing this up, @rralian. Until now I was thinking to just open a file-selecting dialog, but your concerns are absolutely valid. I can see the lack of context is an issue — it’s not clear where our users are adding the media to, unless the “add” button displays the media section. Currently, only 5% of uploads is via drop method, and that shows the discovery issue. I’ll work on a design something similar to what you’ve suggested.

**Comment by iamtakashi** [comment]
I wonder if this makes sense — the "add" button takes you to media section and opens file-select dialog. Basically it works like a shortcut that does "go to media section" and "click add new" button. Is it possible?

![media-add](https://cloud.githubusercontent.com/assets/908665/23226884/18a66264-f92f-11e6-817e-63e706785e87.jpg)

We still need to address the discovery issue of drag/drop but I think using a guided tour or a small instruction text might be more appropriate way to address.
