### ISSUE TITLE
Notifications - educate about shortkeys

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#91358]
spinning this issue off of Automattic/dotcom-forge#7551

The notifications app and panel support a variety of shortkeys for controlling the panel with keyboard navigation. n toggles the panel, a, f, u, c, l set the filters, and up/down/left/right control navigating the list and opening closing items, etc.

We should find a way to surface, highlight, and educate users about this feature. It is not clear to a new user that these shortkeys exist or why/what each key does. Finding a good way to highlight these shorkeys could be handy for new users (or even existing users!), especially ones restricted to keyboard navigation.

**Comment by Addison-Stavlo** [comment]
This could definitely use some design thought.

One idea could be to add a new icon/button next to the settings cog:



![Image](https://github.com/Automattic/wp-calypso/assets/28742426/cc96840e-3199-4dc8-93ff-b0f57b35b683)



This could open an extra section with a 'legend' that explains the shortkeys (we could use the existing fly-out level that opens when we select an individual comment). We could potentially have this section auto-open in certain circumstances (first time opening the panel since adding it?), make it the default keyboard focus item when opening the panel, etc.

**Comment by davemart-in** [comment]
I'm going to take a pass at this.

**Comment by davemart-in** [comment]
After looking at this one, I'm going to unassign myself. Here's a rough idea of what I had planned to implement:

![CleanShot 2024-06-19 at 10 18 54@2x](https://github.com/Automattic/wp-calypso/assets/5634774/f220523c-0b5c-4e35-beb7-3628d371b92d)
