### ISSUE TITLE
Notifications - add a11y focus styles.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#91357]
Spinning this issue off of Automattic/dotcom-forge#7551

Currently in the notifications panel if we navigate with the keyboard tab navigation it is not clear what item the focus is on. We should update this to have a11y focus styles in the app so they can be present both inside and outside of calypso.

**Comment by davemart-in** [comment]
Closed with https://github.com/Automattic/wp-calypso/pull/95198
