### ISSUE TITLE
Classic Themes: Jetpack Likes and Sharing conflict with Dotcom Sharing Buttons settings

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#91371]
### Quick summary

When `Marketing > Sharing Buttons > Front Page, Archive Pages, and Search Results` is ON, and the Homepage has `Likes and Sharing > Show likes` OFF, a perpetual `Loading..` element becomes visible on the homepage.

Classic Themes on Simple sites only.

### Steps to reproduce

1. Create a simple site
2. Enable a classic theme on it (i.e Canape)
3. Make sure `Marketing > Sharing Buttons > Front Page, Archive Pages, and Search Results` is checked.
4. Set a static page as the homepage, under `Appearance → Customize → Homepage Settings → A static page → Homepage`
5. Go to your pages list and edit the page you've set as the homepage in 4. 
6. On the top right part of Gutenberg, click the Jetpack icon.
7. Make sure `Likes and Sharing > Show likes` is OFF.
8. Visit the front end of the site (homepage).
9. Notice the `loading..` text just before the footer

### What you expected to happen

To not see the "Loading" mention 

### What actually happened

I see the following "Loading" mention:
![image](https://github.com/Automattic/wp-calypso/assets/81776920/349c613c-0c8d-45c8-aea9-06a9fd0fea14)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Issue nonexistent on AT sites.

### Workaround

Make sure `Marketing > Sharing Buttons > Front Page, Archive Pages, and Search Results` is unchecked.

Or, use CSS:

```
.home #jp-post-flair{
  display: none;
}
```

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple as per the report

## 📌 ACTIONS ##
Triaged 
- Closed as could not replicate (please reopen if the issue reoccurs) 

##Message to author##
Thanks so much for the report. I couldn't replicate the issue with the same set up? Are you still able to produce this on a number of sites? Feel free to reopen if you can still replicate.
