### ISSUE TITLE
Posts List: Previously Published Posts Don't display by last modified date on Calypso Draft Post list

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#91374]
### Quick summary

Users expect Draft posts to be displayed sorted by the date/time the post was last modified, with the most recently modified post at the top. In the WP Admin view, they are displayed correctly, even if a previously published post appears in the draft post list. But in Calypso view, previously published posts display ordered by their Published date instead of the last modified date of the draft.

I noticed that the Last Modified date column on the Posts List in WP Admin shows the Published date for posts that were previously published, instead of the last date the draft was modified so it seems like Calypso is using that date for sorting, even though it appears to know that the post was modified since then since Calypso shows the correct last modified date under the post title.

### Steps to reproduce

1. View Draft Posts in the Draft folder on Calypso and make note of the last modified date of the first post
2. Open a Published Post that is older than the date noted in Step 1 and save it as a Draft
3. Modify the previously published post and save it again as a draft 
4. Open the Posts list in WP Admin and select the Drafts post list. Note that the previously published post now displays at the top.
5. Open the Posts list in Calypso and select the Drafts posts list

### What you expected to happen

I expected the previously published post i just modified to display at the top as it did in WP Admin.

![WP Admin Posts](https://github.com/Automattic/wp-calypso/assets/32983813/955dddb0-7297-431d-a199-5e39c1f5caab)

### What actually happened

The previously published post I just modified displayed lower down in order of the published date.

![Calypso New Post List](https://github.com/Automattic/wp-calypso/assets/32983813/7de7be8f-435d-4456-a65f-4e8bed4f7c1c)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

8263857-zd-a8c

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
![CleanShot 2024-06-03 at 14 13 25@2x](https://github.com/Automattic/wp-calypso/assets/14153300/1af2e397-1a07-4327-9e6c-7d3ee029232c)


📌 ACTIONS
- Triaged

**Comment by matt-west** [comment]
@dsas Is this issue still relevant given that we’re switching to using Core’s Posts page?

**Comment by dsas** [comment]
We're not going to bring that behaviour over to wp-admin, no.

Once we've done the work, it's relevant for the users we haven't yet switched over, and it'll become re-relevant if we decide to rollback.

It's unlikely we'll ever work on this :)
