### ISSUE TITLE
Checkout page shows incomplete/incorrect calculation for domain renewal with free domain credit

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#91382]
### Quick summary

The checkout page for domain renewal with free domain credit on the site shows incomplete/incorrect calculations. 

It shows the domain price(in my case, it was $15) and the price to be reduced because of the free domain credit(it was shown as -$2). The calculated value should be $13. But it was showing $0.

![Screenshot 2024-06-03 at 12 32 01 PM](https://github.com/Automattic/wp-calypso/assets/5733224/52ebdfe5-0612-43d0-a2c4-8e0a22d41c5a)

### Steps to reproduce

1. Create a site with an annual hosting plan.
2. Transfer an existing domain(from another WordPress.com site) to the newly created site and try to renew that domain.
3. On the checkout page, you will see something like the following screenshot - calculation on the right side of the screenshot.

![Screenshot 2024-06-03 at 12 32 01 PM](https://github.com/Automattic/wp-calypso/assets/5733224/f7f14a06-85e1-408a-8eb3-c52a85946c4f)

### What you expected to happen

The breakdown of cost should be clear.

### What actually happened

It was not clear, and the calculation seems incorrect.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by rickmgithub** [comment]
As this required a domain to be imported before renewing, I've reached out to Payments to see if there is a way of checking this easily - p1717655548195329-slack-C02BEP610

**Comment by michaeldcain** [comment]
This is a result of some changes to how we bundle domain mappings and registrations. Added some more context for what's happening here: p1720712291846379/1717655548.195329-slack-C02BEP610

**Comment by lupus2k** [comment]
As part of pb5gDS-3YO-p2, we're aiming to fix/close high-priority issues in [The One Board](https://github.com/orgs/Automattic/projects/391/views/12)
Hey @michaeldcain, I saw you working on this. Can you pick up this issue and fix it? If prioritization isn't possible, just let us know here or in the P2.

Thanks :pray:

**Comment by DavidRothstein** [comment]
Worth fixing, but this doesn't seem "high priority" to me at all.

**Comment by michaeldcain** [comment]
> but this doesn't seem "high priority" to me at all

Agree. I don't know where that tag was added. The end total in Checkout is correct. It's definitely worth fixing, but we likely won't get to it in short order on Shilling.

> Hey @michaeldcain, I saw you working on this. Can you pick up this issue and fix it? If prioritization isn't possible, just let us know here or in the P2.

Sorry for the confusing status. I was just checking the One Board for Payments-related issues to see if I could offer any context. Since Shilling won't likely be able to get to this in the near future, feel free to take a look if you think it's deserving of the prioritization. If it helps with prioritization, as mentioned in the Slack thread, this will only be an issue for users manually renewing older domains, and the final total shown to the user is accurate.

**Comment by DavidRothstein** [comment]
Yesterday was our "quick fix" sprint day, and we were debating whether this might be a quick fix.  I looked at it towards the end of the day and determined it (mostly) is, but couldn't finish writing an automated test for it.  I finished that now so here is the fix: D156465-code

In the end, I think this bug could potentially affect other types of discounts for the same domains too (not just the "Free domain for first year"), so it's a bit more of a fundamental issue and worth fixing, although still not high priority.

**Comment by JessBoctor** [comment]
[D156465-code](https://code.a8c.com/D156465) is approved.

**Comment by DavidRothstein** [comment]
Fix deployed.
