### ISSUE TITLE
Cannot log into WordPress.com with password, stuck in circles

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#91399]
### Quick summary

When trying to log into WordPress.com, I am requested to use a login link. If I choose to Ènter password instead, I am taken back to the previous screen, and there is no place to enter the password anywhere.

### Steps to reproduce

1. Start from https://wordpress.com/log-in
2. Enter WordPress.com (non-Automatic) email
3. Proceed to the next screen and click on `Enter a password instead`
4. Notice how you are taken back to https://wordpress.com/log-in and there is no option to enter a password.

https://github.com/Automattic/wp-calypso/assets/2540430/f3e4e37a-c2e2-40c9-971e-79c55e184476

### What you expected to happen

I expected to be taken to a page to log in with my account password.

### What actually happened

I was stuck in circles, continuously going back to https://wordpress.com/log-in instead.

### Impact

All

### Available workarounds?

Yes, difficult to implement

**Comment by liviopv** [comment]
📌 ACTIONS
- Marking as Triaged
- Escalation: p1717415836832119-slack-C02FMH4G8
