### ISSUE TITLE
Blog RC: Update link in Themes section for Atomic sites

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#91417]
### What

This link in the Blog RC for Atomic sites leads to an old page that no longer exists and needs to be updated with the new page.

`theme symlink command in CLI`:

![image (13)](https://github.com/Automattic/wp-calypso/assets/11635760/ea18194e-fbb0-432a-bf59-4ae4ee2e6374)

New page: P9HQHe-Ge-p2

### Why

This will fix a broken link.

**Comment by zdenys** [comment]
Reported more recently here https://github.a8c.com/Automattic/missioncontrol/issues/158191. Once a dev fixes it, we can close this one too.
