### ISSUE TITLE
Task: Migrate/Import page improvement in migration flow

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#91415]
### Details

**Goal**

Here we will try to make this page better fit in the flow, plus be more clear and align with our common practices. We will:

- Surface the type of site and where it is hosted to validate with the user that we have made the correct assumption.
- Revisit the headline to make the page more integrated in the flow and accurate with what is happening on the page.
- Replace the radio button and CTA format for the big buttons where the user can progress to their desired option.
- Make the Plan requirement more prominent so we better manage the user expectations.

**Existing Look**

<img width="1718" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6820724/77c33bce-5c36-46c5-807d-4048efb0801e">

**Goal Design:**

![image](https://github.com/Automattic/wp-calypso/assets/6820724/17fd2284-7db8-4b8d-8766-0fe8a5b121ff)

### Checklist

- [ ] The title has been updated
- [ ] Subtitle has been added showing the host and the type of site
- [ ] CTA radio buttons are big buttons as per design
- [ ] The plan requirement matches design

**Comment by Imran92** [comment]
@donnapep in case we can just detect the platform type but not the hosting, should we show something different the sub-heading's place?

**Comment by donnapep** [comment]
Yup, I'll figure something out when I get there. 🙂
