### ISSUE TITLE
Editor: Switching between Visual and HTML strips characters

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#9142]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Click on Visual
3. Paste the following text, or something similar:
`SONATA A DUO N.4 (fl, guit) (1975) <Publisher: BÈRBEN [E. 2594 B.]>`
4. Click on HTML, or click Save

#### What I expected
I would expect characters not in a "code" bracket to be converted to their HTML entities.

#### What happened instead
The characters are stripped

#### Browser / OS version
Mac & Chrome, Windows & Firefox

#### Screenshot / Video
https://cloudup.com/ct-YAdEO12T

#### Context / Source
Forum thread. It took me a bit to duplicate this, but I see it whenever I switch back and forth between HTML and Visual.
http://en.forums.wordpress.com/topic/some-of-my-content-disappear-after-edit-the-page

**Comment by lancewillett** [comment]
Thank you. I thought this was already reported, but can't find the other report now.

**Comment by lancewillett** [comment]
Could be similar to #1109

**Comment by supernovia** [comment]
Maybe also related: #8886

**Comment by dcoleonline** [comment]
Here is a recent comparison between how Calypso and wp-admin handle switching between the HTML tab, to the Visual tab, and back to the HTML tab:

**wp-admin keeps the HTML**: https://cloudup.com/ix93flSLSJ6

**Calypso strips most of the text**: https://cloudup.com/iPDJsa4zB5Q

429334-hc & 3339681-t (AT)

**Comment by jblz** [comment]
Related #18203

**Comment by nebososo** [comment]
Reported in HC-3845369

**Comment by rachelmcr** [comment]
I tested this issue in Gutenberg and it's resolved there. After switching to the HTML editor and back to visual, or saving the post, the full content is retained. I'm closing this issue since it will be resolved with the Gutenberg launch.
