### ISSUE TITLE
Refreshed Manage v1

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9143]
Update Manage to fit into the Refresh. See Readersquad p2 post "What’s Needed to Launch Refreshed Manage with Search" for details.

Because it's unlikely that we'll get to the full Refresh of Manage before launch, this issue is MVP version.

![manage-1](https://cloud.githubusercontent.com/assets/24388/19989944/238e960a-a1e7-11e6-97da-b81ce6d61236.png)

So, just:
• Change background to white.
• Remove button borders from "Following" and "Follow" links.

That's it! 

If we have more time, we'll move on to v2, which I'll post as a separate issue.

**Comment by samouri** [comment]
To do:

- [x] white background
- [x] borderless follow
- [ ] 2px border around search to make it stand out more
