### ISSUE TITLE
Task: Show more informative error messages for commonly made URL mistakes

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#91479]
Analyzing the latest incidnts of the wrong URLs, we have detected some common patterns of mistakes that users make. We can show some error-specific messages that are easily detectable by regex. The top few are-

1. Missing TLD (Top-Level Domain) Error: A very large number of users write “mysite” instead of “mysite.com”.
2. Email Address Detected Error: Another large portion writes their email address instead of a URL.
3. Invalid Characters in URL Error: Many add invalid characters in the URL. (Maybe it can be worth exploring later if we should allow these characters in the input field at all?)
4. Incomplete URL Error: Some users just write URLs like “http://”, “file:///C:/DEVELOPER/xyz.html” etc.

The error messages we can show for them can be -

- “Please include a top-level domain (e.g., .com, .net etc) in the URL.”
- “It looks like you’ve entered an email address. Please enter a valid URL instead.”
- URL contains invalid characters. Please remove any special characters.”
- “Invalid URL. Ensure it includes a top-level domain (e.g., .com, .org etc) and starts with ‘http://’ or ‘https://’.”

If the URL does not match any of the above, we’ll fall back to the current error message.

**Comment by donnapep** [comment]
@Imran92 Can you connect the PR with the issue so reviewers don't have to look for it?
