### ISSUE TITLE
Unable to switch between default and classic views

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#91493]
### Quick summary

Users who are on the Explorer plan or lower (Creator and higher not tested) are unable to switch between default and classic views, as described [here](https://wordpress.com/support/navigate-wordpress-com/).

### Steps to reproduce

1. On a site with Explorer or lower, navigate to a page with the "view" option. In calypso, that will be /people.
2. Click the "view" option, and choose either "classic view" or "default view". If you're already using default view, choose "classic".

### What you expected to happen

The page should update and I should be using the view I picked, whether default or classic.

### What actually happened

When testing for a user in 8238608-zd-a8c, both I and the user stayed on classic view. The user wants to be using the default view and is unable.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I reproduced this issue on a test site by switching away from the default view. The switch didn't take, and I'm still in default view.

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Could Not Replicate


## 📌 ACTIONS ##
- Author feedback

##Message to author##
Thanks so much for the report. I couldn't replicate the issue with the same set up. Are you still able to produce this on a number of sites? Feel free to reopen if you can still replicate.
