### ISSUE TITLE
Jetpack Plans: create a jetpack-specific cancelation survey

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#9155]
Currently the WordPress.com plan cancellation survey is shown to all users cancelling a plan (WordPress.com users AND Jetpack).

<img width="599" alt="screen shot 2016-11-04 at 10 08 58 am" src="https://cloud.githubusercontent.com/assets/437258/20008493/2fbb5734-a277-11e6-8d3f-2b12092fa934.png">

We need to add a condition so that we can modify the survey to present Jetpack-specific options to Jetpack users.

cc @johnHackworth @richardmuscat @beaulebens @sararosso

**Comment by bubel** [comment]
Thanks for raising, @rickybanister . I'd like to start making some progress here. I'll work on formatting a survey for Jetpack folks and will follow up with whatever's needed beyond that.

cc @richardmuscat

**Comment by richardmuscat** [comment]
Good point. It will be useful to make this change because right now the data we get from the cancellation survey for JP customers is not very useful.

**Comment by rickybanister** [comment]
How do you think the user's feel?

They must be very confused and just click whatever to try to get through this weird confusing and irrelevant survey.

**Comment by sararosso** [comment]
Thanks @rickybanister - would love a heads-up as this gets close to launch / launching so I can check in and make sure the other data keeps rolling in as expected!

**Comment by bubel** [comment]
Fixed in #10506.
