### ISSUE TITLE
Gallery Cards: Ignore small images

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9159]
This post: https://wpcalypso.wordpress.com/read/feeds/34222/posts/1211847530

Creates this card in Reader:
![screen shot 2016-11-04 at 11 40 27 am](https://cloud.githubusercontent.com/assets/24388/20018083/90f2c31e-a283-11e6-954b-661776ed2ead.png)

The gallery card is omitting this big image: https://youarenotsosmart.files.wordpress.com/2016/11/chems.png

But it includes these images:
https://youarenotsosmart.files.wordpress.com/2014/01/screenshot_13.jpg
https://youarenotsosmart.files.wordpress.com/2016/07/screen-shot-2016-07-18-at-11-34-02-am.png
https://youarenotsosmart.files.wordpress.com/2016/08/screen-shot-2016-08-24-at-6-15-48-pm.png
https://youarenotsosmart.files.wordpress.com/2016/07/6a00d83451b36c69e201b8d0ed5719970c-300wi.png

Most of those images are pretty small. 

So, questions:

• Will the gallery card currently pick any image?
• Can we set a minimum size requirement for images to be considered for Gallery cards?
• Will #9149 change the behavior here? 

Ideally we'd ignore any image that's under 350px wide as usual here to avoid little bugs and logos for the gallery card. Possible?

cc @blowery, @bluefuton, @samouri

**Comment by samouri** [comment]
1. currently the gallery only takes images from the content and ignores the featured image.
1. we can but it will be subject to the same _flashing_ found [here](https://github.com/Automattic/wp-calypso/issues/8866).  Flashing means that we will make an initial best-effort guess without knowing actual sizes, and then right after its loaded make some adjustments based on gathered sizes.
1. Shoudn't have an effect on this.  9149 only affect cards where it was already decided it cannot be a gallery (not enough images)

**Comment by blowery** [comment]
https://github.com/Automattic/wp-calypso/pull/9238 should help with the flashing, though it won't eliminate it

**Comment by blowery** [comment]
for 1) we can just walk post.images instead of post.content_images I think. It has the feature prepended, though maybe not deduped... have to check into that.

**Comment by fraying** [comment]
@blowery I'm wondering if we should ignore ignore the featured image for gallery cards. I'm seeing a few where the featured image is both in the post and the featured image, so it's appearing in cards twice.

![screen shot 2016-11-14 at 11 04 22 am](https://cloud.githubusercontent.com/assets/24388/20278614/3f4e0ce2-aa5a-11e6-8bc4-d87d9c538357.png)

**Comment by blowery** [comment]
We can dedupe that. Looking into it.

**Comment by samouri** [comment]
We already do the same exact thing for full-post (if image is both featured & in content then do X) [source](https://github.com/Automattic/wp-calypso/blob/7b9cfe699b5ba012ba0985442d33d3d4fa963e43/client/blocks/reader-full-post/index.jsx#L308)

**Comment by blowery** [comment]
@fraying try it again? think I fixed it with 491f2d2

**Comment by fraying** [comment]
@blowery Much better! 👍
