### ISSUE TITLE
Migration Flow Improvements: Feature the 14-day refund window and rework the headline and subcopy

### ISSUE THREAD

**Issue by merkushin** [Automattic/wp-calypso#91591]
### Details

In the Upgrade plan screen (client/blocks/importer/wordpress/upgrade-plan):

- Feature the 14-day refund window more prominently.
- Rework the headline and subcopy to not hide the fact that the user requires a Creator plan to access migrations. Confirm copy with @JanaMW27 

Design:
![Image](https://github.com/Automattic/wp-calypso/assets/329356/4c58bdec-250e-4c4a-910b-7add149900e9)
![Image](https://github.com/Automattic/wp-calypso/assets/329356/dd153b9b-c5e8-4172-9dc5-0f8d626a63b6)

**Comment by Imran92** [comment]
> Rework the headline and subcopy to not hide the fact that the user requires a Creator plan to access migrations

@merkushin  Looks like the existing sub-copy doesn't hide the requirement for the creator plan as it explicitly mentions it. Do we still need to change it?

![Image](https://github.com/Automattic/wp-calypso/assets/6820724/be022540-bc31-4c57-b87f-50ca7f15667c)
