### ISSUE TITLE
Unable to restore deleted sites when an account is restored

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#91627]
### Quick summary

Users who contact us for an account restore may not be able to self-restore their own sites.

### Steps to reproduce

1. Create, or log into, an account with at least one free site.
2. Delete that account from /me/account/close.
3. Restore that account, either by using your HE powers or by pinging an HE internally to restore it.

### What you expected to happen

I expected that a user who's account was restored should be able to restore their own sites.

### What actually happened

There is no option to restore the site when visiting /sites, and if the site is clicked on, the user is informed they have no sites. Tested by me for 8302629-zd-a8c.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

HE can still restore the site manually, and should do so if we're restoring an account until a fix is deployed.

**Comment by hacchism** [comment]
Another case: 8312844-zd-a8c

**Comment by jartes** [comment]
Another: 8413814-zd-a8c

**Comment by retnonindya** [comment]
📌 ACTIONS
- Triaged

📌 Note
I'm not sure if this is a bug report (more like a feature request), since this is a known limitation according to Accounts University here:
PaIqia-6p-p2

> As of April 3rd, 2024, users can [self-service restore their sites](https://wordpress.com/support/delete-site/#restore-a-deleted-site) from [WordPress.com/sites](https://wordpress.com/sites) within the standard thirty day recovery window. This process should work without HE intervention in the vast majority of cases. Some known limitations require manual effort as per the original process below:
>
> – The user changed their username which also changes their user ID.
> – The user deleted their account.

This seems like an expected flow. I'm closing this as of now.
