### ISSUE TITLE
Site Migration: Show chat window/option on migration instructions screen

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#91639]
### Details

As proposed in p9Jlb4-bYZ-p2#comment-11574, we want to offer live chat/support on the migration instructions screen. Let's make that happen.

### Checklist

- [ ] Users who view the migration instructions screen in any migration flow should be able to get in touch with an HE easily

**Comment by andres-blanco** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/87944
