### ISSUE TITLE
Help Center: Change Wapuu new chat text

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#91642]
### Details

Context: pau2Xa-5Yj-p2#comment-15656

![image](https://github.com/Automattic/wp-calypso/assets/52076348/c72ae548-89a3-4cab-88b8-fe0dcbc0c2b1)

We need to change from `Start a New Chat` to `Clear Conversation`

**Comment by agrullon95** [comment]
PR created : https://github.com/Automattic/wp-calypso/pull/91646

Waiting for translation
