### ISSUE TITLE
Visual bug: Subscriber Stats chart

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#91688]
### Quick summary

Related to https://github.com/Automattic/wp-calypso/pull/91585 and https://github.com/Automattic/wp-calypso/issues/91632

### Steps to reproduce

1. Visit a WordPress.com site > Stats > Subscribers
2. Mouse over the chart to choose a date.
3. The `subscribers-section` is ignoring its parent (at least on a 1440x900 screen), and the y-axis isn't visible.

<img width="1149" alt="Screenshot 2024-06-11 at 17 14 13" src="https://github.com/Automattic/wp-calypso/assets/25607244/a2a96e4b-33c3-4420-a33a-ee6ad28189d9">

### What you expected to happen

It should look like this:
<img width="1236" alt="Screenshot 2024-06-11 at 17 15 30" src="https://github.com/Automattic/wp-calypso/assets/25607244/d02f634f-8a4c-48db-965a-405f04af2d0e">

### What actually happened

The `subscriber-section` isn't loading properly on some screen resolutions.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
👋 @kangzj can your team take a look?

**Comment by kangzj** [comment]
@simison sure thing. onto it.

**Comment by grzegorz-cp** [comment]
I'm having problems reproducing this issue but I'll keep debugging.

**Comment by crisbusquets** [comment]
> I'm having problems reproducing this issue but I'll keep debugging.

For context:
- I use Chrome
- This happens when the subscriber stats for this site: https://wordpress.com/stats/subscribers/songokunewsletter.wordpress.com
- I resize the browser to something like 1440x900 or similar
- **It works well, except if I reload the page again**.

A demo:

https://github.com/Automattic/wp-calypso/assets/25607244/42931f01-c886-44a7-81b4-bc612963a079

It also happens if my screen resolution is 1440x900 (or similar). When I navigate to another page inside WP Admin and then return to Stats > Subscriber Stats, it loads like that.

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
On the first load, I get consistent repro, but as I adjust the screen width, it gets very inconsistent:


https://github.com/Automattic/wp-calypso/assets/14153300/a782b3f9-770c-4af6-a2ef-f4038831cb79


As you see in the video, on the first load, the element is hidden. Once I start adjusting the viewport width, it gets hidden but then it adjusts itself, but I couldn't hide it completely after adjusting the screen width.

📌 ACTIONS
- Triaged
