### ISSUE TITLE
Navigation Block Unavailable in Simple/Free Sites

### ISSUE THREAD

**Issue by ha-un** [Automattic/wp-calypso#91693]
### Quick summary

Navigation block does not show up as an option for some/most Simple or Free sites compared to Atomic sites.

### Steps to reproduce

1. Create a new free site
2. Go to header template part
3. Remove navigation block
4. Search for navigation block

### What you expected to happen

Navigation block should appear as one of the block options

### What actually happened

Only "Page List" block shows up, or sometimes none at all.

![cleanshot_2024-06-11_at_11 39 53_2x](https://github.com/Automattic/wp-calypso/assets/96960321/684c0cbb-c963-42b4-9cd0-6a802528fbcd)

![download](https://github.com/Automattic/wp-calypso/assets/96960321/eb36d2ab-f97f-4ec1-89ad-f5dcf0d46267)

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

After testing on the free site, changing the site to be atomic resolved the issue - the Navigation block was available in header and anywhere else in the site.

![CleanShot 2024-06-11 at 11 54 42@2x](https://github.com/Automattic/wp-calypso/assets/96960321/93cde46a-7ab4-40b7-b4f9-29a9b592865c)

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I wasn't able to reproduce

https://github.com/Automattic/wp-calypso/assets/14153300/fbd933ad-5395-49bb-8406-4355a4d3bc1b

If it was widespread, it would have impacted support by now.

📌 ACTIONS

- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@ha-un I'm pretty confident that what you're experiencing is this pbxlJb-5Kl-p2 which affects only a12s
