### ISSUE TITLE
Editor: hide page template options on Posts page to match wp-admin UX

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#9169]
#### Steps to reproduce
1. Set theme to Shoreditch (edit by Lance: or any theme with page templates, such as Twenty Twelve)
2. Set posts page to a page titled, Blog.
2. Visit Blog page in /wp-admin/ — no page template options visible.
3. Visit Blog page in Calypso — can view and select Page Template options. These options have no effect on the blog's appearance.

#### What I expected
I expected the page template options in both /wp-admin/ and Calypso to be consistent.

#### What happened instead
On the blog page in /wp-admin/ there are no page template options.

On the blog page in Calypso a user can view and select one of the following page templates: Default Template, Full Width Page Template, Panel Page Template. There are no changes to the page layout.

#### Browser / OS version
Chrome Version 54.0.2840.87
OS 10.10.5

#### Screenshot / Video

<img width="1247" alt="screen shot 2016-11-06 at 15 01 25" src="https://cloud.githubusercontent.com/assets/11627765/20038855/7259bf9c-a432-11e6-8c1c-a7a4c0b34632.png">

<img width="1244" alt="screen shot 2016-11-06 at 14 53 48" src="https://cloud.githubusercontent.com/assets/11627765/20038856/7474e8ec-a432-11e6-93d2-744617e5196b.png">

#manual-testing, #user-report

**Comment by lancewillett** [comment]
Thanks for the report — this is interesting. Needs more investigation to see if it's a theme issue or Calypso or ... something. :)

**Comment by lancewillett** [comment]
I looked into this a bit more. A few findings:

1. It's normal WordPress behavior to be able to set a static page as the "Posts page" — but when you do so, that page no longer is really a page; it behaves like a blog archives index view instead, so you can't set any page template options on it.
2. Calypso should work more like wp-admin in that case, and hide anything that would normally be applicable to a static page — but that isn't useful for a "posts page", including the template choice and even the editor text itself. If you notice in wp-admin the editor is disabled for that case.

**Comment by lancewillett** [comment]
I updated the title to reflect the requested change (bug fix) and moved into the wp-admin parity milestone.

**Comment by gemmagarner** [comment]
Thanks for your work on this Lance!
