### ISSUE TITLE
Purchases > Remove Plan: switch "Cancel" copy to something clearer

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#91760]
### What

In cancelations where we don't show the exit survey, users will see this pop-up:

![CleanShot 2024-06-13 at 15 39 15@2x](https://github.com/Automattic/wp-calypso/assets/14153300/01a77160-f9cb-4da1-b6e6-1fe795b8d02c)

"Cancel" and "Remove plan" seem to be same action from a user perspective, but they lead to different results. 

### Why

It's confusing and might come across as dark pattern.

### How

Change "Cancel" copy to "Keep the plan"

**Comment by supernovia** [comment]
I have seen a few cases, including one here today
9126117-zd-a8c

**Comment by matt-west** [comment]
I agree this is confusing. Let’s update the cancel button to `Keep plan`.

@Automattic/lego Do you have any availability to handle this?
