### ISSUE TITLE
Migration Instructions: Provision site and plugin installation

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#91779]
### Details

The component and integrations to provision the site and plugin installation, which is already implemented in the current instructions and we just need to migrate to the new screen.

We also need to create the component that displays the progress.

![Screenshot 2024-06-13 at 18 04 15](https://github.com/Automattic/wp-calypso/assets/876340/7b42c21d-97af-4c43-921d-e62a2ef4b009)

### Checklist

- [x] Steps to provision site and install plugin are integrated.
- [x] Component to display the progress.
- [x] Tests created.
- [x] Record events as the status progress, like the current instructions step.
- [x] Handle errors.

### Related

https://github.com/Automattic/dotcom-forge/issues/7703

**Comment by m1r0** [comment]
I'm on support rotation this week, so feel free to pick this up. 🙂
