### ISSUE TITLE
Migration Instructions: Migration key integration

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#91780]
### Details

Add the migration key integration. It already exists in the current instructions, and we need to migrate to the new screen.

![Screenshot 2024-06-17 at 14 30 06](https://github.com/Automattic/wp-calypso/assets/876340/2fe24a41-db6c-4c40-9678-7a598801ed20)

### Checklist

- [x] The step of the migration key is created.
- [x] The migration key is integrated and works dynamically.
- [x] We have checked and implemented what is needed regarding the fallback from the current step instructions. See `client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-instructions-i2/index.tsx`.
- [x] Tests created.

### Related

https://github.com/Automattic/dotcom-forge/issues/7703

**Comment by donnapep** [comment]
@renatho I think this issue could use a screenshot of the UI. Actually, it would probably be best to add a screenshot to all UI-related cards so that it's really clear which part of the UI the cards is responsible for updating.

**Comment by renatho** [comment]
> I think this issue could use a screenshot of the UI. Actually, it would probably be best to add a screenshot to all UI-related cards so that it's really clear which part of the UI each card is responsible for updating.

@donnapep, good point! Added screenshots to all the UI-related cards to clarify more. 😉
