### ISSUE TITLE
Cannot remove long tags for posts

### ISSUE THREAD

**Issue by nabsul** [Automattic/wp-calypso#918]
Hi,

For long post tags, it's not possible to delete tags from the post.

![image](https://cloud.githubusercontent.com/assets/11143071/11449939/9dc90948-953e-11e5-930a-5ba9184b64c5.png)

**Comment by lancewillett** [comment]
Thanks for the report. This is a weird one — I hadn't thought of tags ever being this long.

Can you think of a real-life scenario where it would happen?

**Comment by nabsul** [comment]
This issue was reported by a WordPress.com customer in Romania. They have long words :-D

**Comment by lancewillett** [comment]
`0123456789` doesn't look like Romanian! haha.

**Comment by nabsul** [comment]
Oh, that was my personal test do demonstrate the issue my own English blog. The customer's blog is Hungarian, not Romanian actually. I can get a link to it if you like, but I figured demonstrating the issue was sufficient :-)

**Comment by pzs11** [comment]
Hi, I was the one with the "too long tag" problem. If could suggest, the easiest way to solve this - I suppose - is to put the "x" (for deleting) on the beginning of the tag, not on the end.

**Comment by lancewillett** [comment]
Thank you for all the info — it's nice to know real-life scenarios where possible, to put it into perspective.

**Comment by pzs11** [comment]
Yes, my blog works already as a database. Until now I have more than 26.000 tags (names of persons, names of institutions, corelations, logical connections etc.). For my readers it's more easy to find the related articles, if they use the tags. And many times those names are longer than 23-25 letters. So this cause the problem. Thank you, if you could help me.

**Comment by nylen** [comment]
> For long post tags, it's not possible to delete tags from the post.

This is not true:  you can still use Backspace/Delete to remove tags, and use the arrow keys to move the cursor in between tags if needed.

**Comment by kriskarkoski** [comment]
For a real world example, I helped a user who had "Federal Bureau of Investigation" as a tag that triggered this issue and I advised what @nylen suggested above of using the cursor to delete until this is resolved.

**Comment by pzs11** [comment]
Hi,
Thanks a lot, I do it that way.
Best regards,
Zsolt


Az üzenetet Samsung táblagépről küldték.

-------- Eredeti üzenet --------
Feladó: kriskarkoski <notifications@github.com> 
Dátum: 2015. 12. 16.  16:17  (GMT+01:00) 
Címzett: Automattic/wp-calypso <wp-calypso@noreply.github.com> 
Másolatot kap: pzs11 <paszkanzs@gmail.com> 
Tárgy: Re: [wp-calypso] Cannot remove long tags for posts (#918) 

For a real world example, I helped a user who had "Federal Bureau of Investigation" as a tag that triggered this issue and I advised what @nylen suggested above of using the cursor to delete until this is resolved.

**Comment by timmyc** [comment]
Fixed in #1669
