### ISSUE TITLE
Editor: changing size of image which has caption with - and + removes text written next to it

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#9180]
## Steps to repro

1. Upload image and add caption;
2. Click in front of the image (ie to the left of it) and add some text;
3. The text should jump above the image;
4. Increase or decrease size of the image with the - or + buttons;
5. The text disappears

## Video

https://drive.google.com/file/d/0B8e-IpRwSdjtc3Fqd2lLMlQ1ZFk/view

## What I expected

I expected the text to stay after increasing or decreasing captioned image size.

**Comment by rachelmcr** [comment]
Closing as this behavior will be superseded by Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
