### ISSUE TITLE
Reader Stream Refresh: Any card with < 100 characters in the excerpt should be a photo card

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9185]
Example post: 
https://wpcalypso.wordpress.com/read/feeds/41934482
https://wpcalypso.wordpress.com/read/feeds/41934482/posts/1195536226

![screenshot 2016-11-07 08 52 28](https://cloud.githubusercontent.com/assets/4924246/20066743/86eb8126-a4c7-11e6-8125-286f343290b6.png)

This isn't treated as a photo card probably because it has two images.

> @fraying: Any card with less than 100 characters in the excerpt should be a photo card, even if it has more than one image. (Just use the first for the photo.)

**Comment by fraying** [comment]
Great catch, Jan! Thank you.

**Comment by blowery** [comment]
I was wrong here, it's because the caption is 164 characters, and captions are included in the character count.

**Comment by fraying** [comment]
@blowery Aha! So! Can we ignore captions for the excerpt word count?

**Comment by blowery** [comment]
@fraying sometimes? if they're from wordpress-y things, there's a pattern we can look for. for general run of the mill things, .... less so. I'll see what we can do.

**Comment by samouri** [comment]
I think right now we are doing a word count inside of `client/lib/post-normalizer/rule-content-word-count.js`.  Is there any reason we aren't using `post.excerpt` (or `post.better_excerpt`) for a word count?

**Comment by blowery** [comment]
@samouri fraying said "word count" but we're really using the character count. We can just switch the normalizer to look at `post.better_excerpt_no_html` i think.

**Comment by fraying** [comment]
Yes, character count, not word count. Sorry.

**Comment by samouri** [comment]
I'll test this out then

**Comment by jancavan** [comment]
Fixed in: https://github.com/Automattic/wp-calypso/pull/9256
