### ISSUE TITLE
Media Section: non-business/non-premium site warning/nudge on video/audio pages

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#9186]
When inserting images into a post the media modal will show a message explaining that video/audio requires the business plan. But we don't show this same nudge to people viewing the standalone media section.

![media nudge](http://cld.wthms.co/NKIW+)

Similarly, we should show the "remaining space" nudge persistently in the media section for non-business sites. This exists in the post->media-modal, but not the standalone media section.

![space left nudge](http://cld.wthms.co/H97S+)

- [ ] Make sure there are upgrade nudges for Audio/Video on a Free/Premium Plan
- [ ] Sites with Premium & Business can use these tabs normally
- [ ] Remove Drake from Empty Views (This pushes down call to actions )
![screen shot 2017-02-27 at 9 13 38 am](https://cloud.githubusercontent.com/assets/1270189/23371453/0bdf7222-fccd-11e6-849b-3b38c787b348.png)
- [ ] Use the new banner component with button call to action. We should target Premium plan (make sure the plan icon matches). Copy for the two bullet points: "Enable audio and video". "Upgrade to 13GB storage"
![screen shot 2017-02-27 at 9 17 46 am](https://cloud.githubusercontent.com/assets/1270189/23371648/acdb3792-fccd-11e6-878f-da4728ee82b2.png)

Remember to use the new banner component https://wpcalypso.wordpress.com/devdocs/design/banner

**Comment by iamtakashi** [comment]
I saw some inconsistency in error message when I tried to upload a video between free and personal plan sites.

Free plan:
![screen shot 2017-01-23 at 16 00 44](https://cloud.githubusercontent.com/assets/908665/22211838/5c54b3c8-e186-11e6-86cc-f77fdb82fbba.png)

Personal plan:
![screen shot 2017-01-23 at 16 01 01](https://cloud.githubusercontent.com/assets/908665/22211852/68f86354-e186-11e6-8807-64fb35a0b67c.png)

The one I see with personal plan isn't very helpful.

**Comment by iamtakashi** [comment]
> But we don't show this same nudge to people viewing the standalone media section.

Let's display the same nudge in the section also.

> Similarly, we should show the "remaining space" nudge persistently in the media section for non-business sites. This exists in the post->media-modal, but not the standalone media section.

This will be addressed in #10805

**Comment by iamtakashi** [comment]
I've made a separate issue for the unhelpful error in personal plan: #11623

**Comment by iamtakashi** [comment]
> Remove Drake from Empty Views (This pushes down call to actions )

Since we don't show Drake in video and audio tab in the modal either, we can remove this criteria from this specific issue. The nudge is more important here. So, it should look like this although the price could be wrong and I don't know if the discount should be applied.

![image](https://cloud.githubusercontent.com/assets/908665/23435822/586dfcb0-fe00-11e6-80fe-750c43a76743.png)

Removing Drake (or make it smaller) from other empty tabs should be discussed in a separate issue.

**Comment by kriskarkoski** [comment]
These nudges are active now for free sites. Closing.
