### ISSUE TITLE
The comparison grid is broken when rendering a longer feature

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#91870]
Originally reported by @niranjan-uma-shankar from pdvytD-EC-p2:

e.g. in `de`:

![Image](https://github.com/Automattic/wp-calypso/assets/1842898/7261a6ec-80ca-40fe-ae7d-b413ce341c25)

We will need to check other languages having longer copies as well.

**Comment by southp** [comment]
The title overflow is due to the non-breaking space before `WordPress`:
![Image](https://github.com/user-attachments/assets/4bc0444a-46dc-40d0-9f92-213bd1466b7f)

@Automattic/i18n Could you help me confirm if that `&nbsp;` can be removed?

**Comment by yuliyan** [comment]
@southp, I think that `&nbsp;` comes from [preventWidows](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/formatting/prevent-widows.js#L9) used in the FormattedHeader component so I'm not sure if it can be easily removed.

**Comment by southp** [comment]
The comparison grid overflow issue looks like just another symptom of the originally reported bug. This time, it's caused by "Mindest-/Höchstbestellmengen" and "Individuelle Marketingautomatisierung". e.g. In the following screencast, I attempted to replace them by shorter copies, and the issue then disappeared:

https://github.com/user-attachments/assets/d200e3c1-4923-4bf0-bfb3-46c9ec6bf0ac

It looks like there are still some rooms we can attempt to fit the text, so I'll see if it's something we can solve by fine-tuning.

**Comment by southp** [comment]
@yuliyan Thanks for investigation. In that case, other than updating the copy, I'm wondering if let the title wrap with a hyphen automatically added would work:

![Image](https://github.com/user-attachments/assets/8bd5e549-bd6a-4bb6-a84b-85f7c3fcc5b2)

Does that work for German and any other longer languages?

**Comment by yuliyan** [comment]
I don't know if breaking WordPress into a new line would be a good solution in this case. 

Personally, I'm not a big fan of the `preventWidows` as it has also caused issues before, and would love to see it removed from the formatted header title in favor of something like `text-wrap: pretty;` or `text-wrap: balance;`.

**Comment by southp** [comment]
Good point, @yuliyan . I've created a PR following your comment in a conservative way: https://github.com/Automattic/wp-calypso/pull/95426. I'd be grateful if you can help me take a look :)

**Comment by southp** [comment]
This has now been fixed by https://github.com/Automattic/wp-calypso/pull/95426 and https://github.com/Automattic/wp-calypso/pull/95427.
