### ISSUE TITLE
Try adding borders to images

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9187]
I'd like to try adding a 1px border to all images in cards in the stream. Same color as the divider lines. 

Why: images with white backgrounds appear "floaty" and make the page hard to scan. The idea is, the light borders will not be noticed when they appear around full color images, but they'll come in handy when the background is white.

A good example with borders added: 

![image-borders](https://cloud.githubusercontent.com/assets/24388/20069577/00f21390-a4d2-11e6-855a-0b590b44f865.png)

Note that, in the gallery card, there's no longer any space between images - just the 1px border.

Easy to try, @jancavan?

**Comment by jancavan** [comment]
> Easy to try

Yup
