### ISSUE TITLE
Image Editor: after editing image quickly navigating to html tab won't update content

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#9189]
To reproduce:
1. Navigate to http://calypso.localhost:3000/post
2. Select a public wpcom site
3. Upload a media item
4. Insert it into the page
5. Edit the image using the image editor
6. Quickly close the media modal (or throttle your internet connection)
7. Click on the html tab
8. Wait for content to update

**Comment by lamosty** [comment]
Note: this bug is present after #9093 gets merged.

**Comment by obenland** [comment]
I couldn't really reproduce the issue, part of it may have been that I wasn't entirely sure what to look for. After inserting editing, and updating an image, the HMTL markup did update for me after switching tabs. Are there any more details for this bug?

**Comment by gwwar** [comment]
@obenland could you verify by throttling your connection to something very slow after step 5 (in chrome dev tools), close the modal, click on the html tab, then restore your internet connection speeds

If you can't repro with a throttled connection we can close this out.

**Comment by obenland** [comment]
Throttled to 2G, the content does update for me.

Maybe I'm not doing it in the right sequence? Can you still reproduce it?

**Comment by gwwar** [comment]
Thanks @obenland Let's close this out for now and reopen if it's still an issue later
