### ISSUE TITLE
Cards without post titles

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9191]
When a card has no post title, the text should scoot up to where the title usually is.

For example, this post: https://wpcalypso.wordpress.com/read/feeds/14781946/posts/1215093079

Currently creates this card:
![screen shot 2016-11-07 at 12 45 59 pm](https://cloud.githubusercontent.com/assets/24388/20075269/6a18b4c6-a4e8-11e6-9b82-745b265b60d5.png)

But it should be this:
![screen-shot-2016-11-07-at-12 45 59-pm](https://cloud.githubusercontent.com/assets/24388/20075304/8dff8bf8-a4e8-11e6-9f80-16e32b131051.png)

**Comment by blowery** [comment]
Hrm. Currently we set the title to a non-breaking space, explicitly to avoid that collapse, but really only for photo cards. 

We can special case the override to just photo cards, which should fix the issue.

**Comment by blowery** [comment]
addressing this in #9163
