### ISSUE TITLE
Tweaks to Lists in Sidebar

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9195]
For the Lists element in the Sidebar:

If the user has 0 lists, remove the Lists element.

![tbt11](https://cloud.githubusercontent.com/assets/24388/20078394/315b70d0-a4f5-11e6-9dae-68f678b85e82.png)

If the user has 1 or more lists, retain the Lists element, but remove the ADD and MANAGE links.

![tbt2](https://cloud.githubusercontent.com/assets/24388/20078554/def9c28c-a4f5-11e6-9250-a66264054c11.png)

This can happen anytime before the refresh launch.

**Comment by jchimienti89** [comment]
@fraying I attempted to update the sidebar component and made a pull request. https://github.com/Automattic/wp-calypso/pull/9269

**Comment by fraying** [comment]
@jchimienti89 Hey thanks!

**Comment by jchimienti89** [comment]
@fraying if all's well I can also help clean up the component. 

I can wrap the reader-sidebar-tags  in a localize function like I did with https://github.com/Automattic/wp-calypso/pull/9017

**Comment by fraying** [comment]
@blowery please advise.

**Comment by blowery** [comment]
Sure, any help modernizing the reader codebase would be appreciated.

**Comment by fraying** [comment]
Thanks, @blowery. Green light, @jchimienti89! Thanks so much for your help.

**Comment by jchimienti89** [comment]
Coolies, will do.
