### ISSUE TITLE
Some images showing "The image has an empty alt attribute" in editor after downgrade/lossless import in Private

### ISSUE THREAD

**Issue by TPilgs** [Automattic/wp-calypso#91952]
### Quick summary

After performing a Lossless Import and the site being set as Private, some images weren't displaying in the page/post editor properly. They showed the error message "The image has an empty alt attribute." This was after running the “Import media from domain” and “Backfill attachments” tools on the blog RC.

Setting the site to Coming Soon fixed the issue, but it continues to not work on Private.

### Steps to reproduce

Unfortunately I can't reproduce on a test site. In this particular case, the HE downgraded the site from Atomic to Simple, performed a Lossless Import, but then the Creator plan was added back and the site was never made Atomic again.

The site is https://christeien.com/ and the issue still occurs when the site is set to Private.

### What you expected to happen

All the images should show, not just most of them, while on Private. That error message should also not show.

### What actually happened

When in Private, the editor shows some images and many others don't display at all, other than with the error message.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Slack thread: p1718807035100869-slack-C03TY6J1A

**Comment by nazilya06** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/87642

**Comment by retnonindya** [comment]
📌 ACTIONS
- Triaged
- Requested author feedback

📌 Message to Author
I'm not sure if this is a bug report, since this happens on one website and it looks like more as an isolated issue. @TPilgs, can you report this on AT Requests P2 instead? FWIW, I checked the site and it seems like all images are working well. For the time being, I'm closing this report.
