### ISSUE TITLE
Themes: themes.php on Simple should not submit the search

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#91978]
In the `themes.php` page on untangled Simple sites, there's a search field that filters the list of themes displayed.

The filtering happens on type; submitting the field is not needed.

However, we don't block it. Hitting <kbd>enter</kbd> and submitting the form causes the page to reload without search param, returning to the original unfiltered theme list.

On the Core version, the field is prevented from submitting, guarding against this behaviour.

We should do the same on the untangled Simple sites version.

**Comment by rcrdortiz** [comment]
A fix has been deployed.
