### ISSUE TITLE
Reader: If 0 follows, show Search instead of Followed

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9198]
Idea: In the refresh, when a user goes to Followed (aka the top of Reader), if their follow count is zero, instead of showing the Followed page content, show the Search page content.

Why: If a user follows no sites, the Followed page will contain a single card (with two recommended posts in it) and that's it. But the Search page contains a search bar as well as many recommended posts, which would be much better. (Basically the Search page is what Cold Start used to be.)

This is necessary even if we're autofollowing, because a user could unfollow everything. (Granted, it's an edge case.)

Thoughts? Good idea? If so, how much time would it take to implement? (Hours/days/weeks?)

cc @blowery

**Comment by blowery** [comment]
Doable. Could piggy-back on the current stuff we use to detect cold start users. Probably hours.

**Comment by fraying** [comment]
Excellent. Let's do it if there's time.

**Comment by fraying** [comment]
Redirect from Drake page?

**Comment by fraying** [comment]
@blowery I still think this is a good idea. Still doable?
