### ISSUE TITLE
Jetpack Connect: Authorize screen should have a better connected state

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#9201]
As reported by @beaulebens , there is some weirdness on the authorize screen when you have a site that is already connected.

To reproduce:
- in your wp-admin, connect an un-connected, un-upgraded Jetpack site
- purchase a plan
- press back until you are back in wp-admin with a connect button
- click "connect" again

What I expected
- A message that says "You are already Connected" with some links into various parts of Calypso

What I got
- A message that says "Your are already Connected" with a confusing "Approve" button, and no clear way to move forward

![download](https://cloud.githubusercontent.com/assets/2694219/20081563/5c2bc1a6-a51e-11e6-92ee-ad906d26b78b.png)

**Comment by beaulebens** [comment]
I haven't confirmed, but I don't believe the plan purchase is specifically necessary here, you could just do:

- click Connect from within wp-admin
- go through the connection process far enough to be connected
- click back in your browser
- see connection prompt
- click Connect again
- get "already connected" message

I actually wouldn't expect a message at all in this case. I would expect it to continue on the connection process automatically, given that I'm connected. If I would have been sent back to wp-admin after this connection, then send me back there. If I would have ended up in Calypso, then send me there. Basically, just detect that I'm connected, and continue as if things were normal and I'd just connected for the first time.
