### ISSUE TITLE
Reader Refresh: remove vestigial pieces of cold start

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#9202]
in #9199 we removed coldstart from the reader without removing all of its traces in wp-calypso.  This is to track the janitorial effort of cleaning it up.

**Comment by blowery** [comment]
we'll want to keep the cards and the container ui around for #9106 I think. Though it would be really nice to get rid of masonry, I don't think that's in the _cards_ this iteration.

**Comment by jancavan** [comment]
> we'll want to keep the cards and the container ui around for #9106 I think

The rec cards have to be equal in height so we can probably get rid of masonry.
