### ISSUE TITLE
Passwordless Core Profiler Auth - Enable passwordless signup

### ISSUE THREAD

**Issue by moon0326** [Automattic/wp-calypso#92104]
We need to update the existing sign-up page to support a passwordless signup flow. This feature aims to improve user experience by allowing users to sign up using a secure link sent to their email 

FIgma: Y5pUYSJPsGEud1vknUZhi8-fi-3183_8554

## Acceptance criteria

**Feature**: Enable passwordless sign-up

**Scenario**: Signed-out customer signs up a new passwordless account.

```
Given a signed-out user is on the "One last step!" page
When the user clicks on the "Continue with email" button
Then a new user account should be created
And the user should be logged-in
Then user should see logged-in screen
```

The user should also receive "Confirm your email address" email.

**Updated designs**

![image-2](https://github.com/Automattic/woocommerce.com/assets/4723145/70991b74-a606-431e-8d11-8ff967b02026)

After logged-in:
![image](https://github.com/user-attachments/assets/a4149436-e1ae-42c5-b270-17645826f672)

Email confirmation:

![image](https://github.com/user-attachments/assets/0edb55e1-17f0-4d71-822f-d687e5539013)

**Comment by chihsuan** [comment]
https://github.com/Automattic/wp-calypso/pull/93230
