### ISSUE TITLE
"Preview & Customize" button does not show up for Twenty Twenty-Four

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#92198]
### Quick summary

Under specific conditions, the "Preview & Customize" button does not appear for the "Twenty Twenty-Four" theme. 

This issue seems to be related to the client side (e.g., redux store) rather than the backend because of the following;

- Reloading the page fixes the problem 
- The API response appears to be correct: https://public-api.wordpress.com/rest/v1.2/themes/twentytwentyfour?http_envelope=1&locale=en-gb
- This bug only occurs when clicking the theme card from the search view, not when scrolling directly to the "Twenty Twenty-Four" theme on the `/themes` page.

Previous Conversations:
p1700742791214349-slack-C029FM1EH
p1700710027291949-slack-CRWCHQGUB

### Steps to reproduce

- Go to /themes.
- Search for "Twenty Twenty Four".
- Click the "Twenty Twenty Four" theme card.
- Observe the "Demo site" button.
- Reload the page.
- Observe the "Preview & Customize" button now appears.
<img width="720" alt="Screenshot 2024-06-28 at 14 59 23" src="https://github.com/Automattic/wp-calypso/assets/5287479/a11527aa-c837-49d0-91ba-824884d32258">

### What you expected to happen

The "Preview & Customize" button should consistently appear without needing to reload the page.

### What actually happened

The "Preview & Customize" button initially does not appear and only shows up after reloading the page.

### Impact

Most (> 50%)

### Available workarounds?

Yes

### Platform (Simple and/or Atomic)

Both

**Comment by taipeicoder** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/60623

**Comment by okmttdhr** [comment]
> Closing in favor of #60623

This is a separate issue from "Try & Customize", so I [created](https://github.com/Automattic/wp-calypso/issues/60623#issuecomment-2196199653) a new issue. It seems to be more of a bug, and we should treat 'Try & Customize' and 'Preview & Customize' as mutually exclusive.
Could you please clarify if you still intend to close this issue? 🙂

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/95540
