### ISSUE TITLE
Migration Flow Improvements: Replace Redux state with hooks for getting site-aware pricing and introductory offer on the Upgrade plan step

### ISSUE THREAD

**Issue by merkushin** [Automattic/wp-calypso#92221]
### Details

As per [this discussion](https://github.com/Automattic/wp-calypso/pull/92088#discussion_r1658517640), we should avoid using Redux state whenever we have an option to use a hook.

For the Upgrade step (`client/blocks/importer/wordpress/upgrade-plan/upgrade-plan-details.tsx`), we have the following hooks:
- `usePricingMetaForGridPlans` to get information on the pricing;
- `useIntroOffers` to get information about the introductory offer.

It might make sense to look at other options that suit better.

**Comment by chriskmnds** [comment]
Thanks. I left a comment/response here: https://github.com/Automattic/wp-calypso/pull/92088#discussion_r1659181698

Please reply on my two inquiries there so we can align. I'd be greatful. 🙇

**Comment by daledupreez** [comment]
@merkushin, Serenity can also step in to tackle this aspect of the refactor so you can focus on exposing the introductory offers.

**Comment by chriskmnds** [comment]
Thank you. I'm stripping out other selectors (like `getPlanRawPrice` https://github.com/Automattic/wp-calypso/pull/92235), so eventually our efforts will converge :-)

**Comment by merkushin** [comment]
Done in https://github.com/Automattic/wp-calypso/issues/91166
