### ISSUE TITLE
Feature Request: Option to disable the 'pre-publish checklist' when creating a post/page from a mobile browser

### ISSUE THREAD

**Issue by mahfuzurwp** [Automattic/wp-calypso#92226]
### What

Add an option to disable the 'pre-publish checklist' when creating or editing posts/pages from a mobile browser on WordPress.com Calypso.

### Why

The 'pre-publish checklist' is a useful tool for ensuring content quality before publishing. However, when working from a mobile browser, this feature can sometimes be cumbersome and slow down the workflow. Users should have the option to disable this checklist when creating or editing posts/pages from their mobile browsers to improve efficiency and streamline the publishing process.

**Comment by inaikem** [comment]
HC-created issue. 
ZD: p1719713703255519-slack-C03TY6J1A

**Comment by jartes** [comment]
Thanks for this suggestion, @coder-mahfuz! 

While I was trying this, I discovered that the option to show or not the pre-publish checks doesn't work on mobile #92388

**Comment by mmtr** [comment]
I think we can close this one out in favor of https://github.com/Automattic/wp-calypso/issues/92226 then.
