### ISSUE TITLE
Login Assistance: Re-run the "migrate CTA after failed login" experiment

### ISSUE THREAD

**Issue by m1r0** [Automattic/wp-calypso#92247]
### Details

We want to re-run the "[show migrate CTA after failed login](https://github.com/Automattic/wp-calypso/issues/90950)" experiment. 

More context can be found here: pdxWSz-1yz-p2#comment-488

### Checklist

- [x] [Don't show the migrate CTA to existing users](https://github.com/Automattic/wp-calypso/issues/92246)
- [x] Create the experiment in ExPlat - 21864-explat-experiment
- [x] Write the experiment P2 post - pbxNRc-3PH-p2
- [x] Launch the experiment after review

**Comment by donnapep** [comment]
@m1r0 This issue is in Done. Wondering if it should be closed?

**Comment by m1r0** [comment]
Thanks for the reminder, Donna. Closing...
