### ISSUE TITLE
X.com links doesn't embed automatically on Simple sites

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#92266]
### Quick summary

X ( Twitter ) has officially changed its domain from twitter.com to x.com. Hence, the URL that we get from X when pasted to the editor ( post, page or comment box ) as a link or in the shortcode no longer works as expected. 

The issue is reproducible on Simple sites.

### Steps to reproduce

1. Grab an X link, such as this: https://x.com/MKBHD/status/1806486060978831763
2. Go to Post / Page editor or a comment box editor
3. Paste the link.

### What you expected to happen

Expected to see X tweet to get embedded on the editor.

### What actually happened

X tweet did not get embedded on the editor.

Screenshot: ![zmoMKk.png](https://github.com/Automattic/wp-calypso/assets/33957570/b4675172-36d7-4f51-8e3a-0a27dc5ca6ab)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Workaround:

Replace x.com with twitter.com

User report: 8377888-zd-a8c

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Replicable outside of Dotcom – No

📌 ACTIONS
- Triaged

**Comment by jeroenpf** [comment]
This has been fixed already. I was able to paste the example X link and it correctly creates the embed:

![Image](https://github.com/user-attachments/assets/60e7993a-b5fa-4e92-9f9e-de959de1c661)

I will close this issue
