### ISSUE TITLE
Plugin schedule list refreshing on add/remove

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#92263]
### Quick summary

Adding and removing plugin update schedules doesn't clear stale state while refreshing the list of schedules in the background:

https://github.com/Automattic/wp-calypso/assets/811776/c6a28dae-262e-4fec-b1c0-8d7700739bca

### Steps to reproduce

Add / remove schedules from https://wordpress.com/plugins/scheduled-updates

### What you expected to happen

The page to show some kind of loading spinner while the schedule list is being updated

### What actually happened

A stale list of active schedules is shown after adding or removing schedules while the schedule list is updated.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Testing on user account with many sites. Could not replicate the same issue on a single site view. Guessing having many sites to check causes a network delay that wouldn't otherwise be there. I suspect slow network connections would also have this problem.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
I was able to reproduce this on production (no proxy) as well. 

📌 ACTIONS
- Triaged
