### ISSUE TITLE
Reader Stream Refresh: Some posts not appearing as photo cards

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9227]
Example: https://wpcalypso.wordpress.com/read/feeds/52296202

These posts don't have text and should be photo-cards.

![screenshot 2016-11-08 10 09 23](https://cloud.githubusercontent.com/assets/4924246/20111039/a36e817a-a59b-11e6-9a42-de0e9a14978d.png)

![screenshot 2016-11-08 10 09 28](https://cloud.githubusercontent.com/assets/4924246/20111044/a5129200-a59b-11e6-865f-78635b555941.png)

**Comment by blowery** [comment]
We're going to try dropping the min width down to 480 and see how it feels.
