### ISSUE TITLE
Themes showcase page white screen

### ISSUE THREAD

**Issue by marissaexplores** [Automattic/wp-calypso#92285]
### Quick summary

When you go to https://wordpress.com/themes/ , we get a white screen.
Sometimes the themes show for a few seconds before the screen goes white.
Appears to only be an issue on simple sites. 

https://github.com/Automattic/wp-calypso/assets/102770686/7ef46332-9cf2-4f4c-8fab-e7c27afc0647

### Steps to reproduce

Login to a simple site
Go to Appearance > Themes

### What you expected to happen

It's expected that the list of available themes show on this page.

### What actually happened

We see a white screen. Sometimes the theme list shows for a few seconds before the screen goes white.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested this on Chrome and Firefox.

**Comment by dev-sabbir** [comment]
8424156-zd-a8c

**Comment by rcrdortiz** [comment]
The issue should be fixed now in production
