### ISSUE TITLE
Post OOPSing

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9229]
I follow this blog: https://eightsevenzerozerofour.wordpress.com/

I can see this post on the blog: https://eightsevenzerozerofour.wordpress.com/?p=7134

But when that post appears in my Following Stream, it shows this error:

![screen shot 2016-11-08 at 10 43 48 am](https://cloud.githubusercontent.com/assets/24388/20112258/782846fe-a5a0-11e6-9dc5-383676ad0199.png)

Same error in Chrome and Safari, on wp.com and wpcalypso.wordpress.com.

Same error on site page: https://wpcalypso.wordpress.com/read/feeds/15197253

Going to https://public-api.wordpress.com/rest/v1.3/read/feed/15197253/posts/1216243636?http_envelope=1 shows: 
```
{
 "code":403,
 "headers":[
  {"name":"Content-Type","value":"application\/json"}
 ],
 "body":{
    "error":"unauthorized",
    "message":"User cannot view post"
  }
}
```

I can see all the other posts on that site:
![screen shot 2016-11-08 at 10 47 00 am](https://cloud.githubusercontent.com/assets/24388/20112339/e0221eba-a5a0-11e6-8449-afac65230e41.png)

Is it just me?

**Comment by bluefuton** [comment]
> Is it just me?

Looks like it :) Are you still seeing the same result from the API endpoint @fraying?

https://public-api.wordpress.com/rest/v1.3/read/feed/15197253/posts/1216243636?http_envelope=1

**Comment by fraying** [comment]
@bluefuton The API endpoint is no monger OOPSing. No idea why, but I'll close this now.
