### ISSUE TITLE
Question on Gizmodo and site icons

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9232]
How come Gizmodo has a site icon in Reader on iOS ...

![image1](https://cloud.githubusercontent.com/assets/24388/20115495/4b671d2c-a5ad-11e6-95fa-933f16d0878c.PNG)

... but not on the website?

![screen shot 2016-11-08 at 12 17 40 pm](https://cloud.githubusercontent.com/assets/24388/20115512/5ee4d290-a5ad-11e6-924e-a5365f85c3be.png)

**Comment by blowery** [comment]
cc @aerych

**Comment by aerych** [comment]
In cases where a site icon is not specified by the REST API, the iOS reader checks if it can load a site's blavatar from a hash of its host name.  In the case of gizmodo.com it queries https://secure.gravatar.com/blavatar/066856f95ebba2e63854a0b324c0e8a9/ where `066856f95ebba2e63854a0b324c0e8a9` is an md5 hash of `gizmodo.com`
See: https://github.com/wordpress-mobile/WordPress-iOS/blob/6.5/WordPress/Classes/Models/ReaderPost.m#L160

**Comment by fraying** [comment]
Thanks, @aerych! 

@blowery, is this something we can do, too? (Icing!)

**Comment by bluefuton** [comment]
Thanks for the tip @aerych!

In the `ReaderAvatar` component, we need to know upfront if we have a blavatar to display. I reckon we'd need to fire off an HTTP request to check each blavatar exists when we use the hash method mentioned above, which may carry a performance hit.

**Comment by bluefuton** [comment]
@blowery adds: "I'd want to collect some evidence that it actually gets us good icons too"

**Comment by bluefuton** [comment]
Useful things:
- adding `d=404` to a Gravatar URL will return a 404 response if the avatar doesn't exist, rather than a generic avatar
- Calypso already includes `jshashes`, which supports MD5 https://www.npmjs.com/package/jshashes

**Comment by fraying** [comment]
Closing this out since favicons would look shitty in stream anyway.
