### ISSUE TITLE
Media Section: Updating the image name doesn't reflect in the UI immediately

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#9233]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/media
2. Choose an image and click the edit pencil icon
3. Update the image name and move out of the field (or hit enter)

#### What I expected

The new image name to show

#### What happened instead

The old image name still displays. Navigating away and coming back shows the new value

#### Browser / OS version

Chrome OSX Latest

#### Screenshot / Video

![edit image name](https://cloud.githubusercontent.com/assets/128826/20115930/2c6aa7a2-a5c8-11e6-9bc7-9d1bb5356eff.gif)

#### Context / Source

#manual-testing

**Comment by gwwar** [comment]
fixed in #12033
