### ISSUE TITLE
Reader Stream Refresh: add a minimum height for featured assets on cards

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#9234]
If a thumbnail-with-text card doesn't have much text content, the image or video preview appears like a letterbox.

<img width="863" alt="screen shot 2016-11-09 at 10 28 53" src="https://cloud.githubusercontent.com/assets/17325/20117896/5d8eeae2-a667-11e6-8d4a-dfeca7e61ee2.png">

We should probably add a minimum height for the image or video preview.

**Comment by fraying** [comment]
This is not a bug. This is as designed.

**Comment by fraying** [comment]
We might want to look into a card design for video posts with no excerpts, but let’s put that off for now. It’s an edge case.
