### ISSUE TITLE
Plan upsell during cancellation shows wrong refund values

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#92374]
### Quick summary

When attempting to cancel a Premium/Creator plan purchase and filling out the survey with choosing "too expensive", a plan upsell shows to downgrade to a cheaper (Personal) plan. The refund value shown there is 0, which is incorrect.

<img width="500" alt="Screenshot 2024-07-04 at 1 54 20 PM" src="https://github.com/Automattic/wp-calypso/assets/1705499/46141b5b-d878-4f6b-85ac-568b621a368b">

### Steps to reproduce

1. Get a 1-year Premium/Explorer plan
2. Go to the cancellation form and select that the plan was too expensive
3. You should see the offer to switch to Personal/Starter

### What you expected to happen

Show a correct refund amount or no mention if the refund is 0 or the plan is non-refundable. Mentioning "you will get a $0 refund" is probably incorrect.

### What actually happened

See img above. The wording is:

> Personal still gives you access to fast support, removal of ads, and more — and for 50% of the cost of your current plan. You can downgrade and **get a partial refund of €0.00** or continue to the next step and cancel the plan.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by chriskmnds** [comment]
@dzver @southp it looks like you both put together the `getRefund` function in https://github.com/Automattic/wp-calypso/pull/34994 

It's been a few years, but do you mind looking back at this and determining what may be causing the regression(s)? It's all borged right now - the refund is always generated as `0`.

**Comment by dzver** [comment]
<img width="1066" alt="Screenshot 2024-07-04 at 14 57 18" src="https://github.com/Automattic/wp-calypso/assets/82778/9c17cd99-7975-4e1f-83cf-e3710368d709">

I see this on trunk for a brand new Explorer plan paid with a test credit card.

Once I proceed and switch to Starter, and I repeat the cancellation process I see this:

<img width="1066" alt="Screenshot 2024-07-04 at 14 58 50" src="https://github.com/Automattic/wp-calypso/assets/82778/55b41b0b-636e-4488-8d59-b224f8a52e71">

Both upsells appear and work correctly for me. However! In case the test subscription is added from the admin UI or is received with credits, these downgrade paths might behave like they do.

**Comment by chriskmnds** [comment]
@dzver Thanks! and oh my, I should have pinged you earlier, cause I feel like I've spent a lifetime on this. I'm definitely purchasing with credits on my end. 

This is the purchase object that comes back from the endpoint (clearly no refund options as expected from `getRefund` function):

```
        {
            "ID": "24112170",
            "user_id": "52053875",
            "blog_id": "234788367",
            "product_id": "1009",
            "subscribed_date": "2024-07-03T10:24:47+00:00",
            "renew": "1",
            "auto_renew": "1",
            "renew_date": "",
            "inactive_date": null,
            "active": "1",
            "meta": "",
            "ownership_id": "54962290",
            "most_recent_renew_date": "2024-07-03T10:46:20+00:00",
            "amount": 48,
            "expiry_date": "2027-07-03T00:00:00+00:00",
            "expiry_message": "Expires on July 3, 2027",
            "expiry_sub_message": "",
            "expiry_status": "manual-renew",
            "partner_name": null,
            "partner_slug": null,
            "partner_type": null,
            "partner_key_id": null,
            "subscription_status": "active",
            "payment_type": "credits",
            "product_name": "WordPress.com Personal",
            "product_slug": "personal-bundle",
            "product_type": "bundle",
            "blog_created_date": "2024-07-03T10:24:15+00:00",
            "blogname": "Site Title",
            "domain": "chriskmnds57.wordpress.com",
            "description": "Use your own domain and establish your online presence without ads.",
            "attached_to_purchase_id": null,
            "included_domain": "",
            "included_domain_purchase_amount": 0,
            "currency_code": "EUR",
            "currency_symbol": "\u20ac",
            "renewal_price_tier_slug": null,
            "renewal_price_tier_usage_quantity": null,
            "current_price_tier_slug": null,
            "current_price_tier_usage_quantity": null,
            "price_tier_list": [],
            "auto_renew_coupon_code": null,
            "auto_renew_coupon_discount_percentage": null,
            "price_text": "\u20ac48",
            "bill_period_label": "per year",
            "bill_period_days": 365,
            "regular_price_text": "\u20ac48",
            "regular_price_integer": 4800,
            "product_display_price": "<abbr title=\"Euro\">\u20ac<\/abbr>48",
            "price_integer": 4800,
            "is_cancelable": false,
            "can_explicit_renew": true,
            "can_disable_auto_renew": false,
            "can_reenable_auto_renewal": false,
            "iap_purchase_management_link": null,
            "is_iap_purchase": false,
            "is_locked": false,
            "is_refundable": false,
            "refund_period_in_days": 14,
            "is_renewable": true,
            "is_renewal": false,
            "has_private_registration": false,
            "is_woo_express_trial": false,
            "refund_amount": 0,
            "refund_integer": 0,
            "refund_currency_symbol": "\u20ac",
            "refund_text": "\u20ac0",
            "refund_options": null,
            "total_refund_amount": 0,
            "total_refund_integer": 0,
            "total_refund_currency": "EUR",
            "total_refund_text": "\u20ac0",
            "check_dns": false
        },
```

**Comment by dzver** [comment]
@chriskmnds did it work for you with the store sandbox?

Credits and other $0 purchases are not refundable.

**Comment by chriskmnds** [comment]
@dzver yes - everything worked when purchasing with the credit card.
You are my savior. Thanks. I really should have pinged you earlier 😅 

<img width="500" alt="Screenshot 2024-07-04 at 3 27 16 PM" src="https://github.com/Automattic/wp-calypso/assets/1705499/236fcffe-d98a-45a6-841b-7298b14eaf02">

I will go ahead and close this issue along with https://github.com/Automattic/wp-calypso/issues/92375
