### ISSUE TITLE
Account creation & login forms do not trigger 1Password to save credentials

### ISSUE THREAD

**Issue by astralbodies** [Automattic/wp-calypso#9237]
The account creation and login screens don't appear to be crafted in such a way that trigger saving of credentials by apps like 1Password.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Create a new account.
3. Step through the screens and enter a username and password in.
4. Click create/save.

alternatively
1. Starting at URL: https://wordpress.com
2. Log in with a username & password not already stored in 1Password.

#### What I expected
1Password's browser extension should prompt to save or update credentials depending on the state of your data.

#### What happened instead
1Password's browser extension does not trigger either upon account creation or login.

#### Browser / OS version
Safari & Chrome on macOS Sierra. Latest 1Password extension & app.

#### Context / Source
1Password gives the following tips on best practices for making sites work with their browser extension. Their best practices are also useful with accessibility and other features of modern HTML browsers.

https://support.1password.com/compatible-website-design/

While supporting a single app is probably hard to justify I think the ramifications of fixing it are quite important beyond just 1Password support.

#dogfooding, #empathy

**Comment by stephanethomas** [comment]
Is it still happening @astralbodies? The `Login` page went through several iterations recently, and password managers that interact with input fields via HTML should work just fine now.

**Comment by astralbodies** [comment]
I haven't seen this happen again lately so I think we're good!

**Comment by stephanethomas** [comment]
Thanks, closing!
