### ISSUE TITLE
Migration Instructions: Handle site preview case without a "from"

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#92389]
### Details

We need to have another way to display the step when the user doesn't inform the site they are migrating from.

### Checklist

- [ ] Design is created.
- [ ] Design is implemented and it's displayed when the user doesn't inform the "from".

### Related

https://github.com/Automattic/dotcom-forge/issues/7703

**Comment by donnapep** [comment]
@renatho I think this issue may have been addressed already. Can you confirm?

**Comment by renatho** [comment]
Correct, @donnapep! Closing this!
