### ISSUE TITLE
Photo only format being applied to videos

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#9239]
In the reader refresh, photo only cards are defined to be cards with under 100 characters that contain a single wide-enough photo.

I am seeing the photo-only card formatting being applied to video cards which I don't think was intentional: ![image](https://cldup.com/SNcT_ll53j.png)

**Comment by samouri** [comment]
@fraying, is this intended?

**Comment by fraying** [comment]
Nope

**Comment by fraying** [comment]
@samouri What's the URL of that post?

**Comment by samouri** [comment]
It's happening when the photo-only conditions apply (content_images.length is 1 etc.) and doesn't look at content_embeds.  That url is https://calypso.live/read/feeds/55800870

**Comment by fraying** [comment]
@blowery Check this URL: https://wpcalypso.wordpress.com/read/feeds/55800870

How do we make sure videos get the Video Card and not the Photo card?

**Comment by samouri** [comment]
#9288 should fix this.

**Comment by blowery** [comment]
fixed!
