### ISSUE TITLE
Reader: optimistic comment save does not preserve line breaks

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#924]
Raised by @bluefuton

When saving a comment, we optimistically insert it into the page before receiving the API response.

Steps to reproduce:
1. Open a single post in the Reader
2. Add a multiline comment including a URL that needs to be parsed (e.g. a Cloudup URL) to  should slow up the response a bit.
3. Submit the comment and watch to see if the lines are collapsed at first

<strong>Result:</strong> when a multi-line comment is inserted, we lose line breaks when the comment is optimistically shown.

After save, before API response:

<img width="404" alt="screen shot 2015-07-09 at 08 59 38" src="https://cloud.githubusercontent.com/assets/17325/8590480/f5cd2c90-2618-11e5-8422-cd7fad6cddae.png">

After API response:

<img width="420" alt="screen shot 2015-07-09 at 08 59 59" src="https://cloud.githubusercontent.com/assets/17325/8590483/02d8df10-2619-11e5-884e-55d0e215acf8.png">

Video: https://cloudup.com/cNURizmobmH

**Comment by bluefuton** [comment]
Fixed by @tellyworth in #13328.
