### ISSUE TITLE
Site Overview: WordPress.com hosting options listed for a self-hosted site.

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#92435]
### Quick summary

The new `/overview` page in Calypso supports sites that run the Jetpack plugin, but does not appear to support sites that run standalone Jetpack plugins like Jetpack Boost.

### Steps to reproduce

1. Start in a browser where you're not logged in to WordPress.com.
2. Log in to a self-hosted site (e.g. created with JN).
    * At this point no plugin should be installed on the site.
3. Go to Plugins > Add New and install the Jetpack Boost plugin.
4. Configure the plugin and purchase a Boost plugin.
    * As part of the process, you'll create a WordPress.com account.
5. Once the process is complete, check the email with your receipt.
6. Click on the link to manage your purchase in the email.
7. View your purchase, and click on the WordPress.com logo
8. You'll be directed to `https://wordpress.com/overview/yoursite.com`

### What you expected to happen

At that point, the site should not offer me any WordPress.com-related options since it is not hosted on WordPress.com. It should not link me to Jetpack Cloud either, since Boost sites are not displayed in Jetpack Cloud.

### What actually happened

Instead I see info about WordPress.com features and hosting.

<img width="1348" alt="image" src="https://github.com/Automattic/wp-calypso/assets/426388/1a6f44f9-01ae-4884-86c7-70d2b7e1e44d">
<img width="898" alt="image" src="https://github.com/Automattic/wp-calypso/assets/426388/26171a2d-d1cc-4ca2-af50-14031e2736be">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
Related internal conversation:
p1HpG7-tme-p2

**Comment by wongasy** [comment]
Related to https://github.com/Automattic/dotcom-forge/issues/9388 

Fixed by https://github.com/Automattic/wp-calypso/pull/95487
