### ISSUE TITLE
Reader: allow navigation between posts by swiping

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#9244]
Steps to reproduce:

1. Open https://wordpress.com/ in a mobile web browser
1. Try to swipe left / right or up / down to navigate

<strong>Result:</strong> it's not possible to navigate between full posts by swiping (note: it's possible on WP Android but not WP iOS).

<strong>Video:</strong> [10s](https://cloudup.com/cp1x0i_-xXA)
<sup>Seen at https://wordpress.com/ using Safari iOS 10.1.1 on iPhone 6S</sup>

**Comment by blowery** [comment]
The trick here is that that same swipe gesture is used by the browser natively to do back and forward. Need to determine how / if we should override native browser behavior.

**Comment by hoverduck** [comment]
For reference: https://github.com/wordpress-mobile/WordPress-iOS/issues/6183

**Comment by fraying** [comment]
It's also unclear what the "next" post should be. Next in stream? Next from that site? Next in that tag? Next recommendation? That's why we're showing those things as links and not as a gesture.

**Comment by blowery** [comment]
It would be next in whatever the underlying stream is. I think it would default to the feed / site stream if the user somehow comes into the post directly.

**Comment by fraying** [comment]
That's an assumption that I'm not sure we can make.
