### ISSUE TITLE
Reader: break out the StreamHeader action button to its own component

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#925]
Raised by @blowery

> We should break out the action button into it's own thing. We're starting to stack up the showXXXX props, and that's usually a good sign we need to break out the thing being passed.

Screenshot for reference:

![screen shot 2015-07-09 at thu jul 9 7 16 06 am](https://cloud.githubusercontent.com/assets/1119271/8594041/55b9e232-260b-11e5-810e-95375327e398.png)
<sup>Seen at https://wordpress.com/read/blog/feed/18 using Chrome 43.0.2357.130 on Mac OS X 10.10.4</sup>

**Comment by blowery** [comment]
Closing as I don't think we still need this
