### ISSUE TITLE
Media: filenames and titles with non-latin characters appear html entities in the Media Library

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#9252]
Steps to reproduce:

1. Save an image with non-latin characters to your computer (i.e. `σχολείο.jpg`)
1. Go to https://wordpress.com/media and select a site if prompted
1. Add the image to the Media Library
1. Click the pencil icon on the images to view the filename and title

<strong>Result:</strong> filenames and titles with non-latin characters appear html entities in the Media Library (i.e. `σχολείο.jpg` becomes `%cf%83%cf%87%ce%bf%ce%bb%ce%b5%ce%b9%ce%bf`).

<img width="1280" alt="screen shot 2016-11-09 at wed nov 9 12 24 30 pm" src="https://cloud.githubusercontent.com/assets/1119271/20148104/11617722-a679-11e6-9716-839eca8a6a0d.png">
<sup>Seen at https://wpcalypso.wordpress.com/media/design5279.wordpress.com using Firefox 49.0.2 on Mac OS X 10.11.6</sup>

Reported at https://en.forums.wordpress.com/topic/error-in-media-names-titles-in-non-latin-languages

**Comment by designsimply** [comment]
Also see https://core.trac.wordpress.org/ticket/37989

**Comment by iamtakashi** [comment]
I can confirm (with Japanese file name) this issue has been fixed.
