### ISSUE TITLE
Site Title Block on Block Themes: if Link settings are defined via Global Styles, they override settings for the Site Title Block

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#92525]
### Quick summary

When Link settings are defined via Global Styles, they override settings for the Site Title Block.

### Steps to reproduce

1. On an Atomic website with the Texty theme active
2. Please navigate to the Link Global Styles settings and define size, for example
3. Save your changes
4. Now, navigate to the SIte Title block, either via the Block Editor or Global Styles, and notice how the Link settings override the ones on the block.4. Now, navigate to the Site Title block, either via the Block Editor or Global Styles and notice how the Link settings override the ones on the block.

### What you expected to happen

The Block settings should prevail.

### What actually happened

The Global Syle  Link settings are overriding the block-specific settings.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Theme: Texty
Reported on 8442638-zd-a8c
Once the Global Style Link settings are reset, this works as expected.

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated / Could Not Replicate / Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
This happens on other themes, too. I tested on theme Cottage and Goodskin, and I can replicate it.

Theme: Goodskin.

On Global Styles, I set the Links (Editor > Global Styles > Typography > Links) to DM Mono.

<img width="1714" alt="Screenshot 2024-08-08 at 5 35 10 PM" src="https://github.com/user-attachments/assets/71e0001d-bb9f-4f21-997c-f40da9bc921c">\

I then clicked the Site Title Block and changed the font to Alegreya on the block settings.

<img width="1718" alt="Screenshot 2024-08-08 at 5 36 07 PM" src="https://github.com/user-attachments/assets/3055b2fe-f167-43ec-9428-ea6e6ffde241">

The font DM Mono persists. 

📌 ACTIONS
- Triaged

**Comment by dsas** [comment]
I think this is the same underlying issue as https://github.com/WordPress/gutenberg/issues/42404 🤔 That's about text decoration rather than typography but I'd guess the same applies.

**Comment by jorgefilipecosta** [comment]
Issue being discussed at https://github.com/WordPress/gutenberg/issues/46180.

**Comment by annezazu** [comment]
Closing this out as a fix has landed: https://github.com/WordPress/gutenberg/pull/64911
