### ISSUE TITLE
Site Migration: Skip select site step when user has no sites

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#92558]
It was noted that the site picker step shows 3 CTAs AND a search box for creating a site when the user has no sites. I think two actions are needed. 

 * When the user has no sites, we should skip the site picker step all the way and directly create an empty site.
 * When the user has sites, we should show only one CTA for creating a site.

**Comment by fditrapani** [comment]
> When the user has sites, we should show only one CTA for creating a site.

I'd even vote to just create the site in this case. We're not asking people to pick sites in some of our other flows. I also think it gets confusing as to what happens if you have content on the site already (to which we need to communicate that all the content will be replaced — and we all know how much people love to read things :) ).

**Comment by sixhours** [comment]
The original feedback that generated this issue: pcmemI-3dx-p2 

We removed the duplicate CTA to create a new site on the site picker screen here: https://github.com/Automattic/wp-calypso/pull/92561

Took me a bit to get the reproduction instructions for getting to this screen so I'm going to add them here for posterity:

<img width="1286" alt="Screenshot 2024-07-23 at 2 15 51 PM" src="https://github.com/user-attachments/assets/8022e1fe-d89a-4479-ba4f-506436ee198a">

1. Go to `wordpress.com/move` from an incognito window or while logged out
2. Put in your URL to migrate
3. Create an account via email (not sure if this works the same with connected signup methods)
4. You'll be brought to the empty site picker

I agree with Filippo, it doesn't make sense to show this screen under these circumstances.

**Comment by sixhours** [comment]
This was fixed in #92912
