### ISSUE TITLE
Editor: Stuck displaying "Saving..." and preview fails to display

### ISSUE THREAD

**Issue by ellwal** [Automattic/wp-calypso#9255]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/mynintendonews.com
2. User writes any post (not content-specific)
3. User clicks Preview or attempts to save post

-Unable to reproduce issue on any computer except user's (user has also been referred to Mac support for additional assistance)
-Clearing caches temporarily resolves issue
-Issue does not occur in Private Browsing

#### What I expected
Post auto-saves, then displays preview pane

#### What happened instead
"Saving..." appears, but gets stuck - does not revert to "Saved"
When user clicks "Preview" again, preview pane is blank

#### Browser / OS version
macOS Sierra 10.12.1 / Safari 10.0.1

#### Screenshot / Video

<img width="1280" alt="screen shot 2016-11-08 at 20 11 51" src="https://cloud.githubusercontent.com/assets/23367434/20155895/f5c165c2-a69b-11e6-94cc-215ec44d44ea.png">
<img width="1280" alt="screen shot 2016-11-08 at 20 12 56" src="https://cloud.githubusercontent.com/assets/23367434/20155896/f5c1b87e-a69b-11e6-8bda-ffc461122652.png">
<img width="1280" alt="screen shot 2016-11-08 at 20 11 43" src="https://cloud.githubusercontent.com/assets/23367434/20155897/f5c1d70a-a69b-11e6-9232-856e9ac72b6a.png">

#### Context / Source
#user-report

**Comment by lucasjoyce** [comment]
Same issue occurring in 3152781-t

**Comment by lancewillett** [comment]
This has most likely been resolved since Nov 2016. Please re-open a new issue if you see it again. Thank you!
