### ISSUE TITLE
Global view for Themes - add content frame.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#92563]
Noted in slack: p1720635774053039-slack-C06DN6QQVAQ

There is no content frame around the themes showcase in the global dashboard view. We should add the frame consistent with the other items here (sites, domains, plugins, etc.)

![image](https://github.com/Automattic/wp-calypso/assets/28742426/7404d8e7-43cb-4e8c-82cb-02b058b88c16)

example of frame:
<img width="1389" alt="Screenshot 2024-07-10 at 3 15 53 PM" src="https://github.com/Automattic/wp-calypso/assets/28742426/023bf317-a859-40f6-bea2-6d2bba6836d5">

**Comment by lucasmendes-design** [comment]
Just adding more thoughts:
- We must use the same header style (font size, buttons, etc).
- Frame layout.
- We could do something very similar to plugins. So it's consistent everywhere. 
- Sticky header. 

Figma file: kyCC1EHKtv4qsElmlAzp5T-fi-964_31887 

Layout:
<img width="1630" alt="TS 3" src="https://github.com/Automattic/wp-calypso/assets/98343583/7bbd4316-33d6-497a-a298-557cef6a3f6a">

Sticky header: 
<img width="1630" alt="817489174801924" src="https://github.com/Automattic/wp-calypso/assets/98343583/5a6c49bd-6e43-4f87-aaa5-556cbaaee64f">

**Comment by rcrdortiz** [comment]
> Just adding more thoughts:
> 
> * We must use the same header style (font size, buttons, etc).
> * Frame layout.
> * We could do something very similar to plugins. So it's consistent everywhere.
> * Sticky header.
> 
> Figma file: [kyCC1EHKtv4qsElmlAzp5T-fi-964_31887](https://href.li/?https://www.figma.com/file/kyCC1EHKtv4qsElmlAzp5T/?node-id=964-31887)
> 
> Layout: <img alt="TS 3" width="1630" src="https://private-user-images.githubusercontent.com/98343583/347573935-7bbd4316-33d6-497a-a298-557cef6a3f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODA2ODgsIm5iZiI6MTcyMDY4MDM4OCwicGF0aCI6Ii85ODM0MzU4My8zNDc1NzM5MzUtN2JiZDQzMTYtMzNkNi00OTdhLWEyOTgtNTU3Y2VmNmEzZjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA2NDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMTU3NGEwYTMwZWVkNzg2MzcwOGMyMTMxNWIwZmZiNzJhOGMwMGYzODA1ZjNlMTFkYWIzMjEwZGMyYjE1OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hLUvGgP8nIKjVglmGAwBhUikAfk7Wivhb2QrDU3xLhw">
> 
> Sticky header: <img alt="817489174801924" width="1630" src="https://private-user-images.githubusercontent.com/98343583/347575455-5a6c49bd-6e43-4f87-aaa5-556cbaaee64f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODA2ODgsIm5iZiI6MTcyMDY4MDM4OCwicGF0aCI6Ii85ODM0MzU4My8zNDc1NzU0NTUtNWE2YzQ5YmQtNmU0My00Zjg3LWFhYTUtNTU2Y2JhYWVlNjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA2NDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNjU5Mjc1MmM1Mzk5OGFjYmEzNzUxYmY1MDUzYjE4MjQ3N2JkOTdhOWY0ZTllMzBmOWNlZTRkMTRiNmM3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q31jCb8jLC3Xow3fa-qEifIOFZ3ebvdaD5ocJS96opg">

Should the style be applied only when we're in global nav view? The Theme Showcase can be accessed from normal Calypso too, both share the same code.

**Comment by mmtr** [comment]
@rcrdortiz it should be applied to site-selected contexts too except the frame layout. We need to replicate what we do for the plugins marketplace page

**Comment by lucasmendes-design** [comment]
Hi there, I noticed that we're using different button positions on Themes and Domains/Site pages. The button is jumping. See the video below:
https://github.com/user-attachments/assets/8aa4badd-1f6e-4b56-83a3-645a58eb18ea

**Comment by lucasmendes-design** [comment]
Maybe it's because the Heading + Subheading, I'm not sure.
