### ISSUE TITLE
Add translation context to "Total" in checkout

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#92565]
### What

As noted at https://github.com/Automattic/wp-calypso/pull/88493#discussion_r1651052126, we should give translators some context for the translation of "Total" in checkout.

However, we need to do that consistently (not just that one place in the code) so that the translation of the word "Total" is the same throughout checkout.  At a minimum, looking at the checkout screen in German should show either "Gesamt" and "Gesamtbetrag" throughout the page.  We should probably make sure other places like the mini-cart are consistently changed too.

### Why

Adding a translation context will make it possible to translate the word "Total" a bit differently than it is translated elsewhere, given the limited space in checkout.

**Comment by DavidRothstein** [comment]
Here's the inverse of one of the changes we'd need to make here: https://github.com/Automattic/wp-calypso/pull/88493/commits/595658c7dc23460c09a4f261d1d90b180723dad8

**Comment by michaeldcain** [comment]
From planning:

We'd want to make this update to any of the instances of "Total" in Checkout, the mini-cart, and the one-click Checkout modal.

**Comment by jjchrisdiehl** [comment]
Fix is now deployed
