### ISSUE TITLE
Dashboard: Preview of site from Home button does not include FB sharing data

### ISSUE THREAD

**Issue by corypina** [Automattic/wp-calypso#9260]
Issue noted by a WordPress.com user. Sharing data doesn't appear in the FB buttons on a site's Preview from the Dashboard. It *does* show on the actual site.

#### Steps to reproduce
1. Starting at URL: WordPress.com Dashboard
2. Click the Home button for a preview of the site
3. Find a post with sharing buttons

#### What I expected

User indicated the preview used to include FB share numbers

#### What happened instead

The FB button does not include a "shared" number.

#### Context / Source
Discovered via #user-report

![screen shot 2016-11-09 at 4 43 50 pm](https://cloud.githubusercontent.com/assets/1993354/20160906/88708e22-a69f-11e6-940d-18a4d060cd2d.png)

Share number displays correctly on the site (front page):

![front-page](https://cloud.githubusercontent.com/assets/1993354/20294358/6eff7216-aab2-11e6-80c4-da37488a1f42.png)

And on the single post:

![single-post](https://cloud.githubusercontent.com/assets/1993354/20294415/ec060144-aab2-11e6-99a2-35fbec4d59a7.png)

I checked another site, using a different theme, and experienced the same issue.

**Comment by kriskarkoski** [comment]
I had a user report this as well recently and sharing from the preview shared the post with a slightly different URL that still works for non-site users but I think that's why the Share count is different.
