### ISSUE TITLE
Global view for Themes - add sticky header and update styles

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#92601]
### Details

This is a follow up to https://github.com/Automattic/wp-calypso/issues/92563

We want to update the styles on the Global themes page to copy the search UX.

This will mean the search area will be a sticky header and have similar styles.

For more - https://github.com/Automattic/wp-calypso/issues/92563#issuecomment-2221274288

Figma - [kyCC1EHKtv4qsElmlAzp5T-fi-964_31887](https://href.li/?https://www.figma.com/file/kyCC1EHKtv4qsElmlAzp5T/?node-id=964-31887)

### Checklist

- [x] Add sticky search area
- [ ] Update styles to be the same as other global search areas

**Comment by arthur791004** [comment]
> Figma - kyCC1EHKtv4qsElmlAzp5T-fi-964_31887

@lucasmendes-design Do we want to apply the new design and sticky feature to the logged-out theme showcase?

**Comment by arthur791004** [comment]
Proposing https://github.com/Automattic/wp-calypso/pull/94097 to make the search bar and categories sticky to the top when they are out of the view.

**Comment by lucasmendes-design** [comment]
I added a comment there, Arthur. Thanks.

**Comment by arthur791004** [comment]
> Add sticky search area

Completed by https://github.com/Automattic/wp-calypso/pull/94097. Someone can continue to improve the layout in the follow-up PR 🙂

**Comment by Copons** [comment]
@arthur791004 I think this can be closed. If this is not the case, would you mind reopening it and adding it to The One Board? 🙇‍♂
