### ISSUE TITLE
Plans: Stats Plan Doesn't Show Tier in Plan Overview

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/wp-calypso#92629]
### Impacted plugin

Jetpack

### Quick summary

When a customer has a Jetpack Stats plan, we don't show the tier in the plan overview. It would be nice if customers could see what plan they actually have at a glance

### Steps to reproduce

1. Add a tiered stats plan
2. View plans on WordPress.com, see that it doesn't show the tier in the plan overview

### A clear and concise description of what you expected to happen.

I would expect to see the tier for plan

### What actually happened

Plan Overview:

![Annotation on 2024-07-11 at 13-45-48](https://github.com/Automattic/jetpack/assets/45246438/0221035c-54a1-4a86-a10d-25b9758cc70b)

Actual Plan:

![Annotation on 2024-07-11 at 13-45-23](https://github.com/Automattic/jetpack/assets/45246438/5e801c40-2ad2-44ec-9006-1e3c422a64e9)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by ianstewart** [comment]
Might be true with the Sensei plan as well. (But haven't tested.)
