### ISSUE TITLE
Reader Full Post: possible to view trashed post

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#9262]
If a post has been trashed on a WordPress.com site, it is still possible to view it in Reader Full Post if you know the blog ID and post ID.

For example:

https://wpcalypso.wordpress.com/read/blogs/82798297/posts/97

<img width="1017" alt="screen shot 2016-11-10 at 16 42 19" src="https://cloud.githubusercontent.com/assets/17325/20163847/b536af7a-a764-11e6-919f-b41874e3a239.png">

**Comment by blowery** [comment]
I'm 99% sure this only happens if you have access to the post. So we're not leaking anything, it's just suboptimal.

**Comment by bluefuton** [comment]
> I'm 99% sure this only happens if you have access to the post.

Just checked this, and you're 100% right.

We should improve the 403 for this situation though! (#8989)

**Comment by samouri** [comment]
@bluefuton, good work fixing the 404 situation 👍 ! https://github.com/Automattic/wp-calypso/pull/9810

Given that you are only capable of seeing your own trashed posts, I'm not sure this is actually a bug.
I'd be in favor of closing this issue!

**Comment by bluefuton** [comment]
@samouri I opened this issue when I made a mistake and published something I shouldn't have done:

1. Oh no! I hit publish!
2. Trash post
3. Phew. It's trashed.
4. Checked in Reader - it's still viewable! It must still be public! Argh!

There's no security issue here, but it was confusing. I think there's still a case for the post endpoint to fire a 404 for trashed posts (should be pretty easy to add).

**Comment by bluefuton** [comment]
@samouri I've fixed this in wpcom patch D3918 (pending review).

**Comment by fraying** [comment]
@bluefuton Is this still in progress?

**Comment by bluefuton** [comment]
@fraying yep - I'm still waiting on a review for the API patch D3918.

**Comment by bluefuton** [comment]
API patch landed (thanks for :eyes: @blowery).
