### ISSUE TITLE
Themes global view - fix return scroll position after previewing a theme.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#92646]
Currently in global view themes showcase, when we preview a theme and come back, we are no longer at the same scroll position in the showcase. I would expect to be at the position I was previously at and to see the theme i had just previewed in the visible section. Instead I am a bit confused to where I left off browsing.

![themes-goo](https://github.com/user-attachments/assets/f6862c5a-fef8-4094-a7d3-a0995af80750)

The theme showcase in the older site view seems to handle this perfectly.

Note - that the Showcase exists as logged-in (single site, all sites) and logged-out. So any change should be tested in all cases

### Repro steps
1. Go to /sites
2. Click Themes in the global nav
3. Click a theme category like Business (unsure if strictly related, but seems to make repro more reliable)
4. Scroll down through the theme list a bit
5. Click on a theme
6. Click Back to themes

Expected to be scrolled with that theme's row centered in the viewport.

Actually, a different theme's row is centered in the viewport.

**Comment by dsas** [comment]
I'm strugging to repro this, after trying across three browsers.

There is [code that scrolls back to the visible theme](https://github.com/Automattic/wp-calypso//blob/d2f640d00a8f4b4782dca1b9153454ed3fc30c43/client/my-sites/themes/theme-showcase.jsx#L145) (written by @Addison-Stavlo years ago). The bug only makes sense to me if something is added to the page immediately after the scrolling ends which means it scrolls to the wrong location. Possibly the partner carousel?

There is something somewhat similar - but definitely different to the video here in that if you click on a theme in the Partner carousel you get returned to the themes place in the grid, not to the carousel.

**Comment by Addison-Stavlo** [comment]
> (written by @Addison-Stavlo years ago)

Blast from the past! 

> if you click on a theme in the Partner carousel you get returned to the themes place in the grid, not to the carousel.

We recently [resolved a similar bug](https://github.com/Automattic/wp-calypso/pull/93564) in the plugins showcase doing something similar (scrolling to all instances of the same plugin one by one, as opposed to the one clicked). So instead of tracking by slug only, we start tracking it by slug and list grouping.

**Comment by Addison-Stavlo** [comment]
> I'm strugging to repro this

It seems like [this may help](p1723822461379169/1723821700.764009-slack-C07GQ1Q0L6B) with repro'ing:

>  if I do a fresh reload on /themes iteself I cannot repro the issue. But If i start on /sites first I do? (or goto sites and come back, it ends up being reproable again)

**Comment by allilevine** [comment]
@Addison-Stavlo I'm having trouble repro'ing this again. 🙂 I also noticed that there's a sticky header now, which I don't see in your recordings. Could a change in the past three weeks have fixed this?

I see that changing categories in the sticky header doesn't scroll correctly, I can take a look at that:


https://github.com/user-attachments/assets/39c868d7-a090-4df0-befb-2fe0742e24b9

**Comment by Addison-Stavlo** [comment]
>  I'm having trouble repro'ing this again.  Could a change in the past three weeks have fixed this?

I can't seem to reproduce anymore either.

> I see that changing categories in the sticky header doesn't scroll correctly, I can take a look at that:

Thanks! I do see that as well. I wonder if the change that caused this fixed the former 😅

**Comment by allilevine** [comment]
Looks like it was this PR from last week: https://github.com/Automattic/wp-calypso/pull/94097

I'm looking at https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/themes/theme-showcase.jsx#L248 but not seeing a quick fix so far. I removed the larger screen condition and tried `window.scrollTo( 0, 0 )` but `scrollToSearchInput` isn't working in any scenario. Maybe it needs a re-render, or a different ref. 🤔

**Comment by arthur791004** [comment]
> I see that changing categories in the sticky header doesn't scroll correctly, I can take a look at that:

I think it scrolls correctly. It might look weird because “the scroll height changes with the categories”, especially for loading placeholder. However, the scroll top is always the same.

https://github.com/user-attachments/assets/be59c834-5de6-43b5-8d76-0e9245b2a6a4

**Comment by arthur791004** [comment]
> Thanks! I do see that as well. I wonder if the change that caused this fixed the former 😅

No. I checked this issue but it worked as expected. Something weird is it scrolls to the lastTheme instead of the previous position so it might not look great.

https://github.com/user-attachments/assets/dfd5ad66-bc28-4378-89e0-fb9cf31a2d45

**Comment by allilevine** [comment]
> I think it scrolls correctly. It might look weird because “the scroll height changes with the categories”, especially for loading placeholder. However, the scroll top is always the same.

You're right, it's scrolling correctly and the scroll top is the same. But it looks weird and lands the user in the middle (or on the bottom) instead of the top of the category they clicked on. I want to fix that UX. PR in progress here: https://github.com/Automattic/wp-calypso/pull/94375

**Comment by Copons** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/94097 and https://github.com/Automattic/wp-calypso/pull/94375 ✨
