### ISSUE TITLE
Themes global view - adapt theme preview for content frame.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#92645]
Currently when viewing the theme showcase at global view, clicking in to preview a theme shifts the interface away from global view.

We should find a way to keep the interface more consistent, such as showing the preview inside the global views content frame. 

![themes-goo](https://github.com/user-attachments/assets/08a85967-1027-4304-851f-dd9bd5dfea74)

Note - that the Showcase exists as logged-in (single site, all sites) and logged-out. So any change should be tested in all cases

**Comment by javierarce** [comment]
Perhaps we could use the collapsed sidebar and do something like this:

![image](https://github.com/user-attachments/assets/18ebb8c6-5fce-4f79-9123-ca79df264357)

For the navigation we could use the Plugin breadcrumb.

**Comment by Addison-Stavlo** [comment]
> perhaps we could use the collapsed sidebar and do something like this:

Its not a bad idea but I think we want to be consistent with when we do and don't collapse the sidebar. The plugins browser in global for example shows individual plugins within the content frame with the sidebar open:

<img width="1545" alt="Screenshot 2024-08-20 at 4 34 11 PM" src="https://github.com/user-attachments/assets/ae114c3c-52b6-4757-8e41-58d05a58204c">


Originally writing this issue, I didn't expect needing a new design and we would literally just put the individual theme preview inside the exact same content frame that the theme browser is in here:

<img width="1546" alt="Screenshot 2024-08-20 at 4 33 59 PM" src="https://github.com/user-attachments/assets/d2a60d39-110d-4031-a657-7288cade5a79">

I would think if we wanted to use the collapsed sidebar, we should be consistent and do that with the plugins pages as well.

Or for now, just use the existing content frame and sidebar? It feels more like a bug that it breaks out of that to view the individual items.

**Comment by javierarce** [comment]
> Or for now, just use the existing content frame and sidebar? It feels more like a bug that it breaks out of that to view the individual items.

Yes, sorry, let's do that. I originally thought we weren't displaying the regular left sidebar because we didn't want to shrink the columns, but I ran a quick test (which I should have done before publishing my first comment, sorry), and it's not too bad.

**Comment by davemart-in** [comment]
> Originally writing this issue, I didn't expect needing a new design and we would literally just put the individual theme page inside the exact same content frame that the theme browser is in

Let's do this @Addison-Stavlo. 👍
