### ISSUE TITLE
Calypso: Failing page edit screen for specific page/user

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#9265]
#### Steps to reproduce
This is a localised bug to a specific site and page: 2908969-t

I can confirm the issue on the original site. I tried using the same content on a test site and didn’t experience the issue.

#### What I expected
Clicking edit on the page in Calypso would load the page content for editing.

#### What happened instead
Page content does not load, nothing is clickable and the browser tab eventually crashes.

#### Browser / OS version
Chrome Version 54.0.2840.87
OS X 10.10.5

#### Screenshot / Video
![edit](https://cloud.githubusercontent.com/assets/11627765/20172022/46ce26aa-a72b-11e6-93fe-ce42fc384786.jpg)

#### Context / Source

#manual-testing, #user-report

**Comment by timmyc** [comment]
Interesting issue indeed.  I can re-create the error on both chrome and firefox.  It _feels_ like an endless loop is happening, and was able to trace the script crashing to [this logice](https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/wpcom/plugin.js#L243-L248) that "Remove spaces from empty paragraphs".

This TinyMCE plugin is logic taken from core's TinyMCE implementation, so I was able to trac down https://core.trac.wordpress.org/ticket/35890 - which is a similar crash of tinymce.  The update in https://core.trac.wordpress.org/changeset/36597 would explain why the page is editable in wp-admin and note calypso.

PR incoming to update the logic in calypso and make this page editable again for the user.
