### ISSUE TITLE
Unable to "Add a new site" or purchase plan for domain-only site

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#92666]
### Quick summary

When selecting `Add a new site` on a domain-only site/unattached domain and then trying to add any plan it brings up the `Help Center`. When selecting the "Free" plan, I'm redirected to the current active purchases I have.

<img width="807" alt="Screenshot 2024-07-14 at 2 21 05 PM" src="https://github.com/user-attachments/assets/a6fee836-8408-416e-a505-414ea92b31ad">

Unable to select a plan, instead the `Help Center` modal keeps popping up. 

<img width="1729" alt="Screenshot 2024-07-14 at 2 10 38 PM" src="https://github.com/user-attachments/assets/4083863a-da3b-4dbd-8a08-3de09accfb5a">

### Steps to reproduce

1. Go to your domains.
2. Select a domain-only site (a domain that is not currently attached to a site).
3. Select "Add a new site"
4. Try selecting any plan, the Help Center modal will open up instead.

### What you expected to happen

To be able to purchase the selected plan.

### What actually happened

The `Help Center` modal shows instead and I'm not able to choose a plan. 

### Impact

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

Workaround is to create a new site manually and then attach the domain to the new site.

**Comment by rw-ye** [comment]
User report: 8479047-zd-a8c

**Comment by klimeryk** [comment]
It looks like the plan comparison logic thinks we're trying to downgrade the plan. @aneeshd16, looks like this was introduced 2 days ago in https://github.com/Automattic/wp-calypso/pull/92624 🙏

**Comment by fushar** [comment]
Thanks @klimeryk. I've reverted the above PR (via https://github.com/Automattic/wp-calypso/pull/92674) and the issue should be resolved now.
