### ISSUE TITLE
Reader: content is difficult to read while media is loading

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#927]
Steps to reproduce:

1. Go to https://wordpress.com/read/post/id/4/7202<br><sup>(use a slow or throttled connection to see the problem more clearly)</sup>
1. Try to read the comments on the post when it first starts loading

<strong>Result:</strong> the way the content resizes as images are loaded makes it difficult to read anything until the post has completely loaded, which could take a while when using a mobile network.

<strong>Video:</strong> [1m38s](https://cloudup.com/caqa5SMunst)

![screen shot 2015-07-10 at fri jul 10 9 01 23 pm](https://cloud.githubusercontent.com/assets/1119271/8631543/daeac160-2746-11e5-8250-17bd542a6142.png)
<sup>Seen at https://wordpress.com/read/blog/id/4 and https://wordpress.com/read/post/id/4/7202 using Chrome 43.0.2357.132 with DevTools settings "Laptop with MDPI screen" and "Regular 3G" connection throttle on Mac OS X 10.10.4</sup>

/hat tip m for the original report

<blockquote>Because we’re not setting the height-width of images in the HTML, trying the read the comments is almost impossible because it keeps bouncing down as new images load.</blockquote>

Notes from @blowery

> Not much we can do about this short-term, as the content provided does not contain size attributes.
> 
> Longer term, we can fetch the images when we pick up the post from the feed and store them for later. We could then send down the size of the images along with the post content and add the width and height dynamically, if we have them.

**Comment by blowery** [comment]
Closing this until we have a way to do something about it
