### ISSUE TITLE
Site Migration: Repetitive import screen when coming from Tools > Migrate

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#92725]
In [this PR](https://github.com/Automattic/wp-calypso/pull/92726) we reinstated the escape hatch link to importers from the identify step because there was no easy way to start a migration from an export file.

We should do better than that, because the new behaviour (after the PR is merged) feels repetitive. This is what a user needs to do to import from an export file:
1. Go to `Tools > Import`.
2. Select `WordPress` from the list.
3. Click on the link in the Identify step.
4. Select (_again_) WordPress from the list.
5. Actually import from the file.

## Proposal
In the identify step, we can support pre-selecting the WordPress importer via query param, and when the user clicks on the link directly go to the file upload screen.
### Example of proposed flow
1. Go to `Tools > Import`
2. Select `WordPress` from the list.
3. Click on the link in the Identify step. This time, the link text should change to something like `Import from a WordPress export file`.
4. User lands in the WordPress importer ready to upload the file

## What's missing to move forward on this
1. This is just one idea, there might be better ones. So please share it if you have it :)
2. What's the correct copy for the link?

**Comment by gabrielcaires** [comment]
@andres-blanco  I am suggesting updating the link directly to the import or migrate screen because it solves both scenarios.
https://github.com/Automattic/wp-calypso/pull/92941
