### ISSUE TITLE
Site Migration: Add step to capture site URL for users requesting assisted migrations

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#92731]
As flagged in this internal thread - p1721123488820649/1721122890.137469-slack-C06PZC1RR5F - we realised earlier today that our migration flows allow users to request assisted migrations without specifying the URL of their source site. This drives additional work for our migration teams, as they need to contact the user to get that information before they can even review the user's site.

@fditrapani proposed the following design for the step, which should be shown to the user after checkout if they are requesting an assisted migration and they haven't specified their source site URL: https://www.figma.com/design/F8foKv974Gc5dTHSh0i0Wo/Assisting-assisted-migrations?node-id=74-223&t=b2UwZa7M2BCcVKQa-1

![site_url_capture](https://github.com/user-attachments/assets/b932f0a2-2eda-49bb-9562-087325eb6812)

Note that we should validate the supplied URL (possibly after adding `https://` as a prefix) before we accept it. We probably don't want to fully validate that the site is running WordPress using the URL analyser at this time, as that introduces unnecessary complexity at this stage in the flow.

**Comment by sixhours** [comment]
This was closed in #92944
