### ISSUE TITLE
Calypso Navigation bar does not scroll on Mobile browsers

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#92764]
### Quick summary

The sidebar Admin menu from the Dashboard doesn't scroll in any Calypso pages on iPhone using Chrome or Safari for Atomic or Simple sites. It does work on WP Admin pages. I don't have an Android phone to test.

### Steps to reproduce

1. On iPhone, open a **browser** (I've tested Chrome and Safari)
2. Go to wordpress.com/wp-admin and log in
3. Tap the hamburger menu icon to open the admin sidebar menu
4. If the site is using the WP Admin Classic view, go to Hosting > My Home and tap the hamburger menu icon again
5. Try to scroll

### What you expected to happen

I expected the sidebar admin menu to scroll.

### What actually happened

It did not scroll.

Video of my full testing:

https://github.com/user-attachments/assets/22bb09a9-cb14-4b54-938f-14e8fe92c622

You can see in this recording that when I'm on a WP Admin page the sidebar is added to the left and scrolls as expected. If I navigate to a Calypso page, the menu covers the full screen and doesn't scroll.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

For someone who only has access to a phone, they can't get to the Admin Interface setting under Settings > General to switch the default UI to WP Admin Classic. So while this might be a work around to an extent, it's not possible for some people. It also only helps with pages that have a WP Admin version. Even with this setting, if they go to My Home, it's a Calypso page and they'll be stuck with a menu that doesn't scroll again.

**Comment by jartes** [comment]
This is already escalated internally here p1721244854714069-slack-C06DN6QQVAQ

**Comment by Addison-Stavlo** [comment]
We found the cause and are in the process of reverting https://github.com/Automattic/wp-calypso/pull/92768

The fix should be live in the next 10-15min.

**Comment by Addison-Stavlo** [comment]
this should now be resolved.
