### ISSUE TITLE
Notifications gear icon's tooltip says "Cog" 

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#92770]
### Quick summary

In the Notifications Sidebar in the WordPress.com dashboard, the gear icon's tooltip says `Cog`. 

### Steps to reproduce

1. From your WordPress.com dashboard, open the BELL notifications sidebar
2. Hover over the Gear icon

### What you expected to happen

A word like `Settings` or `Preferences` to appear to tell me what that does

### What actually happened

The word `Cog` appears as the tooltip

![CleanShot 2024-07-17 at 13 42 40@2x](https://github.com/user-attachments/assets/7dd92e2d-e81e-47f9-9761-b857bda6c8f5)

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 ACTIONS
- Triaged
- Added priority and `Accessibility` label.

**Comment by davemart-in** [comment]
Let's change it from "Cog" to "Notification settings".

**Comment by allilevine** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/97782 and https://github.com/Automattic/wp-calypso/pull/97784
