### ISSUE TITLE
Domains: Long domain forces "Issues" message link off screen

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#9277]
Using Chrome 54 on 10.11.6, a long domain forces the "More" link on the "Issues with example.com" message mostly off screen. Here's what it should look like:

![screen shot 2016-11-10 at 3 16 53 pm](https://cloud.githubusercontent.com/assets/1900444/20192730/25c3151e-a759-11e6-9fcd-87a6708c8abd.png)

And with a long domain: 

![screen shot 2016-11-10 at 3 17 11 pm](https://cloud.githubusercontent.com/assets/1900444/20192738/2c862ca6-a759-11e6-8a23-5a51001895b1.png)

**Comment by umurkontaci** [comment]
This was reported in #6098.
