### ISSUE TITLE
Reader: posts from domains purchased on WordPress.com and moved to WordPress.org do not appear in the Reader

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#928]
Steps to reproduce:
1. Setup a blog with a custom domain on WordPress.com
2. Setup a WordPress.org blog and point the name servers to the new web host
3. Wait for the DNS changes to propagate
4. Try to follow the WordPress.org blog in the Reader
5. Publish new posts on the test blog that was moved to WordPress.org
6. Wait 1.5 days
7. Check the Reader to see if the new posts appear there

<strong>Result:</strong> new posts published on a blog with a domain moved from WordPress.com to WordPress.org do not appear in the main Reader page or in the feed stream.

After publishing a post http://design5279.com/2015/07/testing-all-the-time/ on a blog that was moved from WordPress.com to WordPress.org in the past and waiting at least 1.5 days, I still could not see it in the feed stream:

<img width="1280" alt="screen shot 2015-07-14 at tue jul 14 9 05 01 pm" src="https://cloud.githubusercontent.com/assets/1119271/8688740/ac250d34-2a6d-11e5-94f6-535e093b829e.png">
<sup>Seen at https://wordpress.com/read/blog/feed/36182934 using Safari 8.0.7 on Mac OS X 10.10.4</sup>

Note: feeds for design5279.com were moved manually by @blowery on Jul 25, so that domain is no longer a good test.

**Comment by blowery** [comment]
still need to investigate

**Comment by davemart-in** [comment]
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.
