### ISSUE TITLE
Slideshare embeds don't work when pasting the URL in the block editor

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#92854]
### Quick summary

Slideshare is listed as a supported service on this page: https://wordpress.com/support/wordpress-editor/blocks/embed-block/#other

However, pasting a Slideshare URL in the block editor results in an error message: 

![Screenshot on 2024-07-20 at 08-06-37](https://github.com/user-attachments/assets/14649b93-7927-41c0-9ae9-bef1501759e1)

## Workaround

Use a shortcode instead. For example:

` [slideshare id=270352617&doc=test-lorem-ipsum-file-this-is-a-test&w=500]`

### Steps to reproduce

1. Open the Block Editor.
2. Paste a Slideshare embed in a new block.
3. See issue.

### What you expected to happen

The content should be embedded.

### What actually happened

This error message appeared instead:

`Sorry, this content could not be embedded.`

![Screenshot on 2024-07-20 at 08-06-37](https://github.com/user-attachments/assets/14649b93-7927-41c0-9ae9-bef1501759e1)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

In simple sites, the error message doesn't appear, but the content also fails to embed. The Slideshare URL is simply added as text in a paragraph, with no error messages.
The shortcode workaround works for both Atomic and simple sites.

**Comment by ariel-maidana** [comment]
8506538-zd-a8c

**Comment by jartes** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
Slideshare has recently deprecated their oEmbed API, and it's also reported in Core: https://core.trac.wordpress.org/ticket/61349

📌 ACTIONS
- Triaged
- Closing.
- Opened an issue to update our docs.
