### ISSUE TITLE
ETK Migration: wpcom-block-editor-nux

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#92861]
Part of PT: ETK Feature Migration CANI Vol. 2 pbxlJb-60m-p2  

Motivation:
- We want to retire the ETK build process and consolidate ETK features within the new jetpack-mu-wpcom plugin.

Done means:
- [ ] wpcom-block-editor-nux has been moved to jetpack-mu-wpcom
- [ ] wpcom-block-editor-nux has been removed from wp-calypso

**Comment by taipeicoder** [comment]
@arthur791004 @lsl is this completed?

**Comment by lsl** [comment]
Stopped following closely but I believe so
