### ISSUE TITLE
Replace the VideoPress upsell by the Explorer plan

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#92887]
## Description
This issue is originally reported in pau2Xa-6bY-p2#comment-15895.

Currently, there is a upsell of VideoPress under /stats for wp.com users:

https://github.com/user-attachments/assets/a1ea60f7-ec8b-4237-b4c6-3594e3d0edeb

It doesn’t make sense for a wp.com site to purchase VideoPress instead of upgrading to the Explorer plan or higher. We should update it to a direct plan upsell, like "Get Explorer".

#### Bonus
Note that the CTA is quite misaligned between the "Search terms" card and the Videos card. A good follow-up is to align those CTAs.

**Comment by oswian** [comment]
I've opened a PR for this change: https://github.com/Automattic/wp-calypso/pull/93174

**Comment by oswian** [comment]
Updated copy has been merged with a [fallback](https://github.com/Automattic/wp-calypso/pull/93237) for non-EN locales. Once the translations are complete, I'll remove the fallback.

Note for future self: using a fallback like this isn't ideal, unless the change is urgent. As [mentioned](https://github.com/Automattic/wp-calypso/pull/93237#discussion_r1703615772) by @chriskmnds:

>  it's best to add the teanslation label, wait for translations to complete, and then merge

**Comment by oswian** [comment]
> Once the translations are complete, I'll remove the fallback.

Done: https://github.com/Automattic/wp-calypso/pull/93442
