### ISSUE TITLE
Reader Stream Refresh: HTML entities not decoded in stream card excerpt

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#9290]
In my Following stream, I spotted an &amp; that wasn't decoded in the excerpt:

<img width="408" alt="screen shot 2016-11-11 at 18 15 15" src="https://cloud.githubusercontent.com/assets/17325/20205110/f10a2992-a83a-11e6-8f58-0237fbc9f3fc.png">

**Comment by fraying** [comment]
@blowery Will this one also be fixed by going back to old style excerpts?

**Comment by blowery** [comment]
@fraying unsure. we should already be decoding entities.

**Comment by blowery** [comment]
Try #9314 for a fix

**Comment by fraying** [comment]
I don't see any unescaped chars in my stream, but I can't locate the post above. @bluefuton?

**Comment by fraying** [comment]
I take it back! I found some in this post: https://wpcalypso.wordpress.com/read/feeds/36358700/posts/1220393328

![screen shot 2016-11-11 at 2 38 14 pm](https://cloud.githubusercontent.com/assets/24388/20232358/9f26727a-a81c-11e6-9162-6a2748c62a30.png)

**Comment by blowery** [comment]
That one's busted in the actual feed. http://feeds.feedburner.com/birthmoviesdeath

Not much we can do in that case, because if we try to double decode the entities, we'll break cases where folks really want entity text in content.

**Comment by bluefuton** [comment]
False alarm folks - just noticed the original example is wrapped in a `<pre>`:

<img width="676" alt="screen shot 2016-11-14 at 10 50 04" src="https://cloud.githubusercontent.com/assets/17325/20249149/34be56b2-aa58-11e6-97f7-65d3bf589712.png">

**Comment by bluefuton** [comment]
Actually - still seeing this on "WordCamp San José, Costa Rica" in Events P2, and that's not wrapped in a `<p>`. I'll try and repro in a test post.

**Comment by bluefuton** [comment]
Here's a repro with the same content:

https://wpcalypso.wordpress.com/read/feeds/40474296

<img width="870" alt="screen shot 2016-11-14 at 17 58 41" src="https://cloud.githubusercontent.com/assets/17325/20253865/086ce61e-aa94-11e6-8b0f-4198887bc482.png">
