### ISSUE TITLE
Newsletter: Settings page prevents you from navigating away.

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#92908]
### Quick summary

We need to investigate why sometimes when you save the newsletter options it prevents you from navigating from the settings page displaying the "unsaved changes browser popup". 

### Steps to reproduce

Still needs more investigation.

### What you expected to happen

That once you save the settings successfully that you don't encounter the "You have unsaved changes" popup. 

### What actually happened

You save settings and sometimes you see the "You have unsaved changes" popup. 

See p1721733930201509-slack-C052XEUUBL4

### Impact

One

### Available workarounds?

Yes, difficult to implement

**Comment by pkuliga** [comment]
It seems it's a global bug. I was able to replicate it also by editing the "For each post in a feed, include" option in the Reading options.

<img width="744" alt="Screenshot 2024-07-24 at 10 39 49" src="https://github.com/user-attachments/assets/643464a5-fd02-42b5-be8d-e3959dae8118">

**Comment by pkuliga** [comment]
The same happens with “Related Posts” in the “Reading” section and with “Newsletter categories” when you modify the list of categories to subscribe to.

**Comment by pkuliga** [comment]
Closing this one since all spotted issues have been fixed.
