### ISSUE TITLE
Site Migration: Activate modules during cleanup

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#92933]
There's a handful of Jetpack modules that HEs activate for all sites post-migration; it would be ideal if these could be activated automatically to save time.

PfxNDN-2g-p2

p4ya8V-9X6-p2#comment-4783

**Comment by sixhours** [comment]
Started looking at this in D157574-code

**Comment by zdenys** [comment]
Once this is launched, could you please drop an FYI in [#dotcom-developer-and-migration-support](https://a8c.slack.com/archives/C06PZC1RR5F)? That way folks can update the internal guide PfxNDN-2g-p2 too. Thank you so much!

**Comment by valterlorran** [comment]
Closing this as it was deployed!
