### ISSUE TITLE
Deleted site not appearing in Sites list for self-service restore

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#92949]
### Quick summary

Users should be able to restore deleted sites from the dashboard: pdtkmj-2wE-p2

This does not seem to be working.

### Steps to reproduce

1. Delete a site.
2. Check Sites list. 

### What you expected to happen

The deleted site should appear so the user can restore it if they choose within 30 days.

### What actually happened

The deleted site does not appear.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Workaround is for the user to contact support to restore the site.
User report: 8518001-zd-a8c
I was able to recreate this issue with a test site.

**Comment by jamiepalatnik** [comment]
Discussed here, looks like this may be a known issue: p1721853425598409-slack-CDJ9Z349W

**Comment by mpkelly** [comment]
Hi @jamiepalatnik. This issue is [fixed](https://github.com/Automattic/dotcom-forge/issues/8149#issuecomment-2259961656) now. I will close this down. Please reopen if you still see a problem.
