### ISSUE TITLE
Media: Unintentional bulk-editing of image description field

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#9295]
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/post
2. Create a new post and click the Add Media button
3. Select the Upload option and upload multiple image files at once
4. With all the images still selected, click the Edit button at the bottom or the edit icon on any of the images
5. Edit the description of the first image
6. Click the arrow to go to the next image

#### What I expected
For the image description field to be blank on the next image

#### What happened instead
The description field for all the following images that were uploaded together are identical to the first. If image number 2 is edited, it also changes 3 and 4. If 3 is edited, it also changes 4, etc.

#### Browser / OS version
Confirmed on FF on Mac OS X Sierra

#### Screenshot / Video
![media](https://cloud.githubusercontent.com/assets/11873759/20213068/4c13afba-a80f-11e6-8312-bf53c1fe44b1.gif)

#### Context / Source

Reported via [Twitter](https://twitter.com/user/status/796099568651956224)

**Comment by iamtakashi** [comment]
It would be great to fix this soon because more users possibly start bulk editing in Media section  that's soon to be launching.

**Comment by gwwar** [comment]
Related #11188

**Comment by gwwar** [comment]
To clarify, when selecting multiple images and going into edit mode. Modifying fields on the right side along with the editable title should only update the current item.

**Comment by iamtakashi** [comment]
This is no longer valid. Closing.
