### ISSUE TITLE
Site Migration: Start Jetpack Sync during automated cleanup

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#92968]
After migrations with Migrate Guru users may keep seeing "My WordPress Site" instead of the real site titles in Calypso site list. The manual fix on our end is to start a JP Sync from JP Debugger.

I think the JP sync kicks in automatically at some point and we can ask @Automattic/jetpack folks when exactly. But in the context of migrations, it would be a better user experience to start the sync as part of the post-migration cleanup.

p1721899404908869-slack-C0Q664T29

**Comment by zinigor** [comment]
I would say that it's best to ask @Automattic/jetpack-vulcan about this.

**Comment by zinigor** [comment]
It looks like this case only covers the client creation, while the migration process doesn't seem to create a new client. @darssen  do you know if we can trigger the same job using a hook of some sort?

**Comment by zdenys** [comment]
To add some context by @mgozdis pfxNDN-OF-p2#comment-1248:
> I’m not sure when a sync automatically runs, but when triaging older migrations, I’ve seen the sync never ran even after a week or longer with a generic/default site title still displaying in /sites and elsewhere.

**Comment by m1r0** [comment]
I've managed to fix this in D166081-code. Your feedback is welcome.

**Comment by m1r0** [comment]
This was fixed by the above. 🙂
