### ISSUE TITLE
Stepper: Create a replica of `/start/onboarding` flow to use for auditing/experimenting

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#92961]
We can create a "dev flow" for experimenting and auditing with the various improvements. 

This can be a close replica of `/start/onboarding`, something to eventually act as a replacement (to be compared and audited in full down the line). It doesn't have to be an "exact" replica. A skeleton should suffice. I recall several quirks needed in a previous attempt (for paid-media project - `/start/onboarding-pm`), and we probably don't need to deal with them straight away.

**Comment by escapemanuele** [comment]
The flow has been created and can be found in `/setup/onboarding`
