### ISSUE TITLE
Error - "The parent theme is missing" showing even though the parent theme is installed

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#92986]
### Quick summary

Some child themes cause an error to show that prompts to install the parent theme. However the parent theme is installed.

### Steps to reproduce

1. Create a child theme and activate it.
2. Notice the error message `The parent theme is missing. Please install the "hevor" parent theme.`

![CleanShot 2024-07-25 at 15 32 43](https://github.com/user-attachments/assets/b306b02f-ad19-4822-af71-a1f2ab029192)

### What you expected to happen

The error not to show if the parent theme is installed.

### What actually happened

The error message shows.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Replicated on Hevor, Twenty Twenty-Three, Twenty Twenty-Four and Cakely. There are likely more themes this happens on.

Could not replicate with Varia theme.

- Replicated with all plugins deactivated including Akismet and Jetpack.
- Replicated on WP 6.5.5
- Replicated with both symlinked and non-symlinked versions of the themes.
- Also tested with older versions of some themes and issue persists.

**Comment by cagrimmett** [comment]
Looks like this was likely caused by something in wpcomsh and it was reverted back to 4.0.0. After the revert, I needed to flush cache before the child theme looked correct again.
