### ISSUE TITLE
Assembler: Insertion should scroll to and highlight patterns as they're inserted

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#92996]
TBD, follow up from https://github.com/Automattic/wp-calypso/issues/87114#issuecomment-2251932891

Pattern insertion currently places new patterns below the fold in the preview making it unclear what, if anything, my button clicks are doing.

Done means:
- [ ] The preview page scrolls to and highlights the patterns as they're inserted.
- [ ] The insertion toast is removed or copy is replaced with something less wordy like "Pattern inserted".

**Comment by richtabor** [comment]
We can remove the snack bar entirely, if the pattern is within view (you see it added).

**Comment by mmtr** [comment]
Moving this one to the "Future / Deferred" status since we don't want to change anything in the Assembler until the "Disable Assembler A/B test" finishes.

**Comment by Copons** [comment]
I'll close this out since we are moving away from the Assembler.
