### ISSUE TITLE
Missing back button in the "use a domain I own" flow

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#92999]
Originally reported by @sethmclellana8c in p5uIfZ-fsX-p2.

When users pick "use a domain I own" in the main onboarding flow and reach the domain mapping step, there is no back button comparing to the plans step:

![Image](https://github.com/user-attachments/assets/e545d40e-1b10-4b27-9c6e-ebdc681bce2b)

![Image](https://github.com/user-attachments/assets/dc327a62-1dcb-4837-a2dc-161a48942147)

For consistency, there should be a back button allowing users to go back to the domain step.

**Comment by jeyip** [comment]
I believe this has been fixed. Feel free to reopen this issue if I'm mistaken.

![2024-08-22 12 51 32](https://github.com/user-attachments/assets/a861cc72-2c55-403f-9fc6-3860085117e2)

**Comment by sethmclellana8c** [comment]
@jeyip  I tried signing up for a test account and triggering this and didn't see the back button.

Replicate. I tried two different ways.

1. When I reached domain step just clicking on the "Use a domain I own" link
2. Typing something into the domain prompt, domains populating (with sidebar including option to skip this step), and then clicking "Use a domain I own" 

In both cases neither flow produced the back button.

Screenshots
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/d55d51a5-c042-4d9b-bdde-c7bb6ade8cd0">

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/ae4f5880-8243-4e97-bfd6-5b7906e1c1c7">

**Comment by jeyip** [comment]
Thanks for the details @sethmclellana8c!

Two key differences you noted from how I tested:

1. Seth tried signing up for a test account while going through this process. I _only_ tried signed in with my normal WordPress account.
2. Seth was also using FireFox. I tested with Chrome.

For whoever takes a closer look at this issue ( or for me if I find extra bandwidth ), I'd start by accounting for those differences when replicating the problem.

**Comment by sethmclellana8c** [comment]
@southp  Can you please reassign this ticket to be completed?

**Comment by jeyip** [comment]
> Can you please reassign this ticket to be completed?

I've relocated this issue into the Decepticons backlog for folks to pick up if / when they have bandwidth 🙂

cc @southp

**Comment by jeyip** [comment]
@sethmclellana8c I merged a patch for this.

![2024-09-03 09 55 34](https://github.com/user-attachments/assets/d3321b19-b0ef-495f-be5c-0aa2104a2bf4)

I'll leave this open for you to confirm the fix. Please close the issue when you verify that things look good. If not, feel free to add more comments to our discussion here 🙂

**Comment by sethmclellana8c** [comment]
_(Sorry @jeyip , I'm not getting alerts of pings in Github and didn't see your comment above. I'll check on that setting this week.)_

Tested new user signup on Chrome and Firefox and looks good. I'm seeing the back button.

Closing this as solved. Thanks for your work on this.

**Comment by jeyip** [comment]
No worries at all @sethmclellana8c. Thanks for confirming the functionality 🙂
