### ISSUE TITLE
Reader: custom post types CPTs are missing in the Reader

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#930]
Steps to reproduce:
1. Find a blog that is using custom post types
2. View the feed stream for the blog in the reader
3. Check to see if CPTs show up or not

<strong>Result:</strong> CPTs don't show up in the Reader

<strong>Example:</strong> [photo challenges ](https://dailypost.wordpress.com/photo-challenges/) from The Daily Post  blog are not included in the Reader at https://wordpress.com/read/blog/feed/27030

/hat tip benhuberman for the original report

**Comment by blowery** [comment]
I think we'll need to treat The Daily Post like a non-wpcom feed to pick up the CPTs, or so some special wrangling for themes that use CPTs. The later is probably the best idea.

**Comment by blowery** [comment]
What other themes does wpcom offer that have CPTs?

**Comment by designsimply** [comment]
<blockquote>What other themes does wpcom offer that have CPTs?</blockquote>

* Confit (Food Menus)
* Stay (Rooms)
* Panel (Comics)

**Comment by blowery** [comment]
@designsimply do posts with those types appear in the feed when using those themes?

**Comment by bluefuton** [comment]
This appears to still be an issue. See also p5PDj3-kU-p2.

> I had a user that said the Prompts from Daily Post weren’t showing in the Reader for him.

**Comment by rantoncuadrado** [comment]
Maybe related https://github.com/Automattic/wp-calypso/issues/14442

**Comment by bluefuton** [comment]
Currently, Reader only supports the 'post' and 'page' post types.

If there are specific post types that we think should be included, let's create individual issues for them.
