### ISSUE TITLE
/website-builder LP image 

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#93013]
### Quick summary

Edit:  this issue was raised in the dotcom walkthrough p58i-hK7-p2 and documented in p58i-hK7#comment-63722.

The text in the following image looks squished

<img width="1168" alt="Screenshot 2024-07-26 at 4 28 31 PM" src="https://github.com/user-attachments/assets/0e8a7fed-bcfc-416f-81b0-45f9c1834717">

**Comment by jrdnhllr** [comment]
It's a condensed font :) 

![image](https://github.com/user-attachments/assets/49fa9aec-c985-4beb-864a-33e036b6c2bc)

**Comment by niranjan-uma-shankar** [comment]
Please feel free to close the issue if it's not applicable (for anyone who might follow through from the bug list on the P2 post).

**Comment by niranjan-uma-shankar** [comment]
>  bug list on the P2 post).

Since the GH description didn't provide context, this issue was raised in the dotcom walkthrough  p58i-hK7-p2 and documented in p58i-hK7#comment-63722.
