### ISSUE TITLE
Notifications: Closing the notification pane pushes a blank history event

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#9301]
To repro:

1. Open https://wordpress.com while logged in, you should see the Reader
2. Click on any post in the Reader following stream to go to the Full Post View in the Reader
3. Click on the notifications bell in the masterbar to open the notifications pane
4. Wait for notifications to load
5. Click on the bell again to close the notifications pane
6. Click on the browser back button (or hit the back link in the full post view, or hit the `esc` key). Notice you don't go anywhere

I expected the back button to take me back to the stream, but instead I'm left on full post.

If you open the console and look at `history.length`, it will increment by 1 every time the notification pane is **closed**. 

Noticed this on Mac 'n Chrome. Also happens in Firefox / Safari.

**Comment by blowery** [comment]
cc @dmsnell

**Comment by dmsnell** [comment]
This is no longer in the iframe…I'm guessing the issue isn't real anymore.
