### ISSUE TITLE
Logo / back to dashboard link overlapping after activating a theme on mobile

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#93028]
### Quick summary

Logo / Back to dashboard link overlapping after activating a theme on mobile

### Steps to reproduce

1. Open your Chrome browser on your mobile device
2. Go to /themes/ and change your theme.
3. Check the confirmation page

### What you expected to happen

To see the two elements one next to each other or have the logo removed.

### What actually happened

This

![IMG_06E8CE91E9A8-1](https://github.com/user-attachments/assets/f90c4cfa-1419-4137-9a3a-b544ef36c1ea)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Saw this while testing another bug.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicated on Safari for iOS too.

📌 ACTIONS
- Triaged

**Comment by inaikem** [comment]
@Automattic/t-rex 👋 Does this fall under your purview? Thanks!

**Comment by arcangelini** [comment]
I got a fix for this, I assume this is what we are going for?

<img width="425" alt="Screen Shot 2024-08-12 at 09 46 17" src="https://github.com/user-attachments/assets/659c9f1f-408b-42da-a93a-880104e3f09e">

**Comment by jartes** [comment]
Yes, @arcangelini! That would be perfect :)
