### ISSUE TITLE
Nav Redesign i4 - Add selected state to reader tab

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#93037]
## Before

![Image](https://github.com/user-attachments/assets/ca3290c6-2ab6-421b-b17f-5ab042bd6a70)

## After

![Image](https://github.com/user-attachments/assets/eb1ef36e-9394-4709-bf7d-43a943b45a10)

Note: those bottom rounded corners will need to be applied as `::before` and `::after` pseudo elements. We may have to use an SVG there, as I'm not sure you can do an inverse curve with CSS.

**Comment by Addison-Stavlo** [comment]
@lucasmendes-design - Do you happen to know the border radii you used in the mockups for this?  It looks like the top borders have 1 radius value and the bottom borders a bit larger. I was curious if you had specific values in mind?

<img width="214" alt="Screenshot 2024-07-30 at 1 04 39 PM" src="https://github.com/user-attachments/assets/a0d17a01-c4fb-476e-be0e-2ad2378dbb3a">

**Comment by lucasmendes-design** [comment]
I my prototype, I used 4px at the top and 6px at the bottom (same as the panel) but **let's use 6px for both**. 

<img width="574" alt="image" src="https://github.com/user-attachments/assets/c85df8d6-eeab-41f8-b770-43490f11d23c">

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/93110 should resolve
