### ISSUE TITLE
Nav Redesign i4 - Add selected state to WP icon

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#93038]
## Before

![Image](https://github.com/user-attachments/assets/b1f32948-d6bf-4af7-a473-9b3156a76b9e)

## After

![Image](https://github.com/user-attachments/assets/7d667831-7926-4110-9fcf-dc8201b2d9cf)

Note: That bottom right rounded corner will need to be applied as an ::after pseudo element. We may have to use an SVG there, as I'm not sure you can do an inverse curve with CSS.

**Comment by lucasmendes-design** [comment]
Thanks for pointing out this. I agree that the tablet is not an issue. 

Can we have the same panel styling on mobile as well? I believe this could fix the problem. 


https://github.com/user-attachments/assets/7e38002f-2ec9-48cb-bb65-3d7b8214dd65

<img width="676" alt="image" src="https://github.com/user-attachments/assets/f7a631a3-b9b0-4d9c-8e0a-0576f65aef2f">

**Comment by Addison-Stavlo** [comment]
> Can we have the same panel styling on mobile as well? I believe this could fix the problem.

I think we can definitely do that, thanks @lucasmendes-design !

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/93110 should resolve
