### ISSUE TITLE
Nav Redesign i4 - Add selected state to profile tab

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#93039]
Similar to these two tasks https://github.com/Automattic/wp-calypso/issues/93037 & https://github.com/Automattic/wp-calypso/issues/93038 we need to add a white selected tab look to the profile section when you're in it:

## Before

![Image](https://github.com/user-attachments/assets/90e4a617-adcb-4d6c-85bb-38eeca5d16c5)

## After

![Image](https://github.com/user-attachments/assets/714e37f6-bb22-4145-8862-762d9ab48241)

Note: That bottom left rounded corner will need to be applied as an ::after pseudo element. We may have to use an SVG there, as I'm not sure you can do an inverse curve with CSS.

**Comment by lucasmendes-design** [comment]
Thanks. LGTM.

**Comment by Addison-Stavlo** [comment]
@lucasmendes-design would you help elaborate on what this should look like when we are on the profile page (so the tab has the color/styles shown above), and we hover (or a11y nav) to open the dropdown submenus?

Current for reference:
<img width="303" alt="Screenshot 2024-07-30 at 8 42 07 AM" src="https://github.com/user-attachments/assets/e907e9bc-a547-4253-828b-4879d865e762">

Should the top level button in the masterbar go back to black in this situation (like shown above), and back to the gray/rounded style once the dropdown menu is closed?

Should the contents inside the dropdown menu go to the white/blue color scheme instead in this case?

Other thoughts?

**Comment by lucasmendes-design** [comment]
At the WP-Admin level, I would follow what the color scheme has defined. So if you hover over the profile item or any other item in WP-Admin the hover and selected state are defined. 

Examples: 
<img width="1842" alt="kjsdfjnsd234234" src="https://github.com/user-attachments/assets/cc254f98-61e1-4d93-8398-01ca779e4699">

------- 

At the global level, Daniel asked to use the WP style for now. I'm sharing with you the hover state for New and Profile page. 

<img width="646" alt="image" src="https://github.com/user-attachments/assets/1340a4d6-6f6d-49f6-a5e5-fb8652348aef">

<img width="494" alt="image" src="https://github.com/user-attachments/assets/740a8571-493b-4201-8670-f77f3b20e574">


Specs: 

<img width="449" alt="Frame 1000007528" src="https://github.com/user-attachments/assets/720d5058-17e1-496f-aafe-ec3a5baa32ed">

**Comment by lucasmendes-design** [comment]
The initial idea was to reuse the dropdown and global components so it's everything more consistent but let's not use that for now. 
https://d.pr/i/vKNjfB

**Comment by Addison-Stavlo** [comment]
Thanks!

> At the WP-Admin level...

Makes sense, I should have clarified I am talking about the calypso global level specifically here.

> At the global level, Daniel asked to use the WP style for now. I'm sharing with you the hover state for New and Profile page.

This hover state for the profile page makes sense WRT my last question (opening dropdown while profile is selected). 

> for New

Im a bit more confused here now. Should all the dropdowns in global view have the white backgrounds regardless of if their main item is selected? or just new? or new and profile both? 😕

**Comment by lucasmendes-design** [comment]
> Im a bit more confused here now by this image. Should all the submenu dropdowns in global view have the white backgrounds regardless of if their main item is selected? (<- Im assuming that) or just new? or new and profile both? 😕

Sorry about that. Let me share a video. I hope this clarifies your doubts. The specs I shared, it is related to the hover states in the global view. 

https://github.com/user-attachments/assets/b398dd55-e67e-41dc-9144-136e8c15a487

![image](https://github.com/user-attachments/assets/04af7277-f762-4452-a7be-51a1821dd157)

**Comment by Addison-Stavlo** [comment]
Ok thanks, We will handle that with a separate issue...

**Comment by lucasmendes-design** [comment]
Updated the color for better accessibility :) 

Background: Gray 90
Text color: gray 10
Text color: white

<img width="449" alt="Frame 1000007528lnadl" src="https://github.com/user-attachments/assets/1860b65f-3682-4b16-9457-616593b3311c">


<img width="1228" alt="image" src="https://github.com/user-attachments/assets/33a4a063-b7f8-4585-a09f-a409c7aa56ff">

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/93110 should resolve
