### ISSUE TITLE
Site Health Uploads directory size does not show size but Loading instead.

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#93052]
### Quick summary

I noticed that the Uploads directory size does not show the size but stays in Loading...

I found this when I was trying to revert a customer's site who wanted to preserve content. I can see my Atomic and Pressable test sites also show Loading... but Pressable has more options that say that then Atomic site. Sharing screenshots:

Customer's atomic site:
<img width="686" alt="Screen Shot 2024-07-29 at 08 09 13" src="https://github.com/user-attachments/assets/344e3b31-5ca2-4bf2-8bd7-a882a8a1b7db">

My Atomic test site:
<img width="561" alt="Screen Shot 2024-07-29 at 09 32 51" src="https://github.com/user-attachments/assets/1827849c-2819-4fd0-bd2b-f0c9b338fcf8">

My Pressable test site:
<img width="599" alt="Screen Shot 2024-07-29 at 08 23 15" src="https://github.com/user-attachments/assets/020c320a-7028-4353-9841-4bec0d0de3e8">

### Steps to reproduce

Check storage on any Atomic/Pressable Site via wp-admin under Tools > Site Health > Info > Directories and Sizes > Uploads directory size.

### What you expected to happen

To see the Uploads directory size number.

### What actually happened

It just showed Loading... even after refreshing. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – Yes

📌 ACTIONS
- Triaged
- Adding `Core Fix Needed` tag.

📌 Message to Author
Thanks for reporting this one @rambogenius! This is coming from Core and has already been reported on https://core.trac.wordpress.org/ticket/61638

**Comment by lsl** [comment]
There was a fix merged https://core.trac.wordpress.org/ticket/61638#comment:21 - leaving the ticket open until this rolls through.

**Comment by daledupreez** [comment]
I just tested and things are looking good on Atomic sites, which are now running WordPress 6.6.2. Per [the Trac query](https://core.trac.wordpress.org/query?status=closed&id=!61982&milestone=6.6.2&group=status&col=id&col=summary&col=owner&col=type&col=priority&col=component&col=version&col=keywords&order=id) linked from the [6.6.2 release notes](https://wordpress.org/news/2024/09/wordpress-6-6-2-maintenance-release/), this is the first release that includes the fix [backported to the 6.6 branch](https://core.trac.wordpress.org/ticket/61638#comment:23).

Closing as this is now fixed.

<img width="807" alt="Screenshot 2024-10-02 at 13 53 56" src="https://github.com/user-attachments/assets/8cec32e9-968c-4676-96c4-89b2bad0972e">
