### ISSUE TITLE
Excerpt different from fullpost page (Laughing Squid)

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9306]
This post: https://wpcalypso.wordpress.com/read/feeds/12098/posts/1220141604

Creates this card:
![screen shot 2016-11-11 at 9 15 07 am](https://cloud.githubusercontent.com/assets/24388/20223636/5ce34e9c-a7ef-11e6-942d-68ab038a018b.png)

Note that the card includes "Related Laughing Squid Posts" but the post does not.

Can we make sure that the stuff we're omitting from the fullpost page is also omitted from the excerpts?

**Comment by blowery** [comment]
This should get automatically fixed when we switch back to the old excerpt style.

**Comment by fraying** [comment]
Cool!

**Comment by blowery** [comment]
Try #9314 for a fix?

**Comment by fraying** [comment]
@blowery Alas, I still see "Related Laughing Squid Posts" on https://calypso.live/?branch=update/reader/old-style-excerpts-in-refresh

![screen shot 2016-11-11 at 1 03 28 pm](https://cloud.githubusercontent.com/assets/24388/20230143/432bdf58-a80f-11e6-9bf3-58005a545fd4.png)
