### ISSUE TITLE
Reusable Synced Pattern: Donation Block in Pattern causes Post Editor to Freeze

### ISSUE THREAD

**Issue by lizswafford** [Automattic/wp-calypso#93072]
### Quick summary

Inserting a Reusable Pattern which include a Donation Block can cause the post and page editor to freeze. 
Error message: "The "jetpack-sidebar" plugin has encountered an error and cannot be rendered."

### Steps to reproduce

Create a two new patterns using the Site Editor or a post or page editor. One pattern should include an image, text, and any other non-payment related blocks such as a button block. Name the pattern Test One (or similar).  
The other pattern should have similar blocks as pattern one and include a Donation Block. Set the Donation Block to accept payments. Name the pattern Test Donation (or similar).

- Go to Posts > Add New Post. 
- Click +  > Patterns > My Patterns. 
- Select the pattern called Test One. Notice it is inserted into the editor. 
- Select the pattern called Test Donation. Notice the editor freezes. 
- Depending on your browser you may get an error message similar to:  "This page is slowing down Firefox. To speed up your browser, stop this page." 
- Notice that items on the editor are not clickable, it's not possible to close the block inserter or click on list view.
- A red banner with the error message "The "jetpack-sidebar" plugin has encountered an error and cannot be rendered."
- Reload the post editor. Content added to the page is not saved. 
- Depending on the browser you may get an error message related to restoring blocks.

### What you expected to happen

Adding a Donation Block to a pattern, then inserting the pattern to a page or post should not cause any errors. 
Or if it is not possible to use a payment related block in a reusable pattern we should see a warning message stating that it's not doable. 

### What actually happened

Editing the patterns in the Site Editor is possible. 
However, inserting the pattern in a post or page editor is not. 

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

8473749-zd
Theme: Apostrophe 2

**Comment by lizswafford** [comment]
Similar issue with PayPal Block inside a Pattern (8368017-zen)

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated - With and without the GB plugin.
- Replicable outside of Dotcom – No (it's a Dotcom feature)

📌 FINDINGS
This only happens when we create a Synced pattern. When creating this pattern as unsynced, it works: 
 
https://github.com/user-attachments/assets/8547644f-fa3b-40a8-865d-88b7faa4d0f8


📌 ACTIONS
- Triaged

CC @Automattic/gold

**Comment by arthur791004** [comment]
It's related to https://github.com/WordPress/gutenberg/issues/63909. If a block that calls `setAttributes` when the component is mounting and create a custom pattern with this kind of the block, then the editor will get stucks when you insert that pattern.

**Comment by arthur791004** [comment]
For similar issues, I think it would be better to wait for the fix on Gutenberg!
