### ISSUE TITLE
Help Center: All URLs of support docs should open in Help Center

### ISSUE THREAD

**Issue by correliebre** [Automattic/wp-calypso#93086]
### Steps to reproduce

1. Open Help Center and click on a support doc. It'll open right there in the Help Center area. 
2. Click on one of the in-line URLs. It'll open in another tab.

https://github.com/user-attachments/assets/e448c8fc-d13c-4285-b3d6-7fbbdb0aef47

### What you expected to happen

The expectation was to keep seeing all documentation in Help Center.

### What actually happened

Instead, URLs opened in another tab.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by escapemanuele** [comment]
Working on that here: https://github.com/Automattic/dotcom-forge/issues/8291
Fix is here: https://github.com/Automattic/wp-calypso/pull/92745
