### ISSUE TITLE
Reader: mixing RTL and LTR text in the same paragraph is broken

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#931]
Steps to reproduce:
1. Go to https://wordpress.com/settings/general and change the language to Hebrew
2. Start a new post at https://wordpress.com/post
3. Add some content that contains both RTL and LTR text in the same paragraph (see sample content)
4. Publish the post
5. Compare the post on the blog itself and the single post view for it in the Reader

<strong>Result:</strong> I expected the text to appear RTL in both the original post and the Reader

Sample content:

```
"סוכר", אם כך, היא "מילה נודדת" או ונדרוורט (Wanderwort), כלומר מילה שהתפשטה בין שפות רבות, לרוב לאורך נתיבי סחר – כמו "קפה". היא מופיעה בצורה דומה בשפות שמיות והודו-אירופיות (ובהן עברית, ערבית, אנגלית, צרפתית, גרמנית, ספרדית, דנית, פולנית, רומנית ואפריקנס), וקיימת בצורה דומה תקופה ארוכה מאוד. למעשה, ארוכה להפתיע: מתי החלו להפיק סוכר? מתברר שבחצי האי ההודי הפיקו סירופ סוכר מקני סוכר במאה ה-5 לפני הספירה, וגבישי סוכר מוצק בסביבות המאה ה-5 לספירה. לא מפליא, אפוא, ששרשרת המילים שמתאר מריאם-ובסטר מתחילה דווקא בסנסקריט.
```

/hat tip @bgbg for the original report

**Comment by designsimply** [comment]
Upon further review, I found that RTL display in the Reader depends on the Interface Language setting at https://wordpress.com/me/account — if that is set to English, the Hebrew text is displayed LTR instead of RTL. 

@blowery, should the Reader be able to detect RTL languages per-post for each card displayed in the Reader even if the user's interface language is set to an LTR language?

**Comment by bgbg** [comment]
> @blowery, should the Reader be able to detect RTL languages per-post for each card displayed in the Reader even if the user's interface language is set to an LTR language?

 @designsimply : Sorry for interferring, but the answer is "definitely yes". Many RTL people read and/or write LTR . It might be a rare thing to find a blog that mixes RTL and LTR posts (there are definitely some of them), but there are tons of  people who follow RTL and LTR blogs. I think that most of them have English as their interface language, but I might be mistaken here

**Comment by blowery** [comment]
We might be able to figure this out now that we have the ES cluster inspecting each post to determine a language. Putting it into the feature backlog for now.

**Comment by tellyworth** [comment]
Looks like this was fixed at some point - wfm with those steps.
