### ISSUE TITLE
Wapuu: Double Contact Support button when giving thumbs down

### ISSUE THREAD

**Issue by correliebre** [Automattic/wp-calypso#93109]
### Quick summary

When asking Wapuu to talk to a human, and, giving thumbs down on a message the "Contact Support" button duplicates. 

### Steps to reproduce

1. Start a chat with Wapuu
2. Ask it to talk to a human
3. You will see a Contact Support button
4. Click thumbs down on the most recent of Wapuu's message
5. Click Back or Close the window
6. Reopen the Help Center and click again on the "Still need help" button
7. You will now see two Contact Support buttons

https://github.com/user-attachments/assets/2cd3c55e-c117-4e6d-9244-d69511a5523c

### What you expected to happen

I expected to only see the "Contact Support" button once.

### What actually happened

The button appeared twice, making it look like a glitch.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by AllTerrainDeveloper** [comment]
Can this be closed already?

**Comment by correliebre** [comment]
@AllTerrainDeveloper  Yes! This is no longer an issue.
