### ISSUE TITLE
Wapuu: "Jump to recent" button isn't working

### ISSUE THREAD

**Issue by correliebre** [Automattic/wp-calypso#93108]
### Quick summary

Wapuu "Jump to recent" button isn't working. When clicking it, nothing happens.

### Steps to reproduce

1. Start a new chat with Wapuu
2. Read one of the support docs and give it a thumbs down
3. An odd jump will happen within the text
4. Right after the jump, you will see a "Jump to recent" button
5. Clicking the "Jump to recent" button won't have any effect. 

https://github.com/user-attachments/assets/b5877cff-5e97-45ea-98a7-3ad267606d8b

### What you expected to happen

I would've expected the "Jump to recent" button to take me to the most recent message.

### What actually happened

The "Jump to recent" button didn't work, I tried clicking on it several times. At the end, I scrolled but that scrolled both Calypso and the Wapuu chat window. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by neehhaa06** [comment]
Hello @correliebre :)

> I think this would be helpful 
> To fix Wapuu's "Jump to recent" button:

>>    **Debugger**: _Verify that the button's event listener is operational._

>>    **Check Function**: _Make sure the scroll function works properly._

>>    **Control Focus**: _Avoid focus divergence from one interface to another._

**Comment by jartes** [comment]
👋🏻 @AllTerrainDeveloper Was this issue fixed on #93145? I'm just asking if we can close this one. Thanks!

**Comment by correliebre** [comment]
I tested the flows of the scroll rework, and the issue with the Jump to recent button was no longer happening, by the way!
