### ISSUE TITLE
Site Migration: Follow-up email shows "Array" instead of plugin name

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#93118]
The email received after a user completes a site migration is supposed to list up to three incompatible plugin names for incompatible plugins installed on a migrated site; instead, it just says "Array":

![Image](https://github.com/user-attachments/assets/37ad610c-e45b-4be7-9b99-bfcb67eb348a)

**Comment by markbiek** [comment]
This appears to be happening because the SSH call to get the plugin list from the site is failing with a `WP_Error`.

It'd be simple enough to check for the `WP_Error` but this seems to be happening a lot so we really need to figure out why there's an error first.

**Comment by markbiek** [comment]
Fixed by D157099-code
