### ISSUE TITLE
Entrypoint: Update Add Subscribers Entrypoint

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#93165]
Current when you visit subscribers list we show users a way to add new subscribers. but we don't ask them to add paid subscribers. 

This is what they currently see 

![Image](https://github.com/user-attachments/assets/e6a5566c-dea0-43b2-8659-ac9c073cff6b)

### Task 
- [ ] Decide what we should show them instead. 
Once the new flow is ready we could show them a button to invite them to import paid subscribers here instead.

**Comment by simison** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/96143

Internal announcement p7DVsv-lJy-p2
