### ISSUE TITLE
Entrypoint: Update Tools/Import/substack to use the new flow

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#93161]
Update the current tools/importer/substack to highlight the paid subscriber importer. 

Currently after you import content using the substack importer we send the user to the check the importer content or send them a link to import subscribers we should invite them to continue with the paid importer flow. 

This is what they currently see
![Image](https://github.com/user-attachments/assets/c3c6eb9f-0c2c-46a6-8143-6a504674afe1)

And after they finish the import this is what they currently see. 

![Image](https://github.com/user-attachments/assets/857d9235-c330-4951-ad55-86e97681ae78)

### Tasks
- [ ] Decide what should happen happen after the new flow is available on the importer page. 
Send the user to the new flow once click on substack or invite them to choose between the current content only flow and the new content + subscriber flow.

**Comment by simison** [comment]
Internal announcement p7DVsv-lJy-p2
