### ISSUE TITLE
Passwordless Core Profiler Auth - User uses passwordless sign-in link

### ISSUE THREAD

**Issue by moon0326** [Automattic/wp-calypso#93171]
This issue is 2nd part of https://github.com/Automattic/wp-calypso/issues/93160.

Figma: [Y5pUYSJPsGEud1vknUZhi8-fi-3182_14593](https://href.li/?https://www.figma.com/file/Y5pUYSJPsGEud1vknUZhi8/?node-id=3182-14593)

When a user signs in with a passwordless link, we should implement the following scenarios.

**Scenario**: User uses the passwordless login link

Given a user with passwordless account
When the user clicks on the sign-in link from the mail
Then the user should be signed-in and continued to the next step

**Scenario**: User account has two-factor auth enabled

Given a user with two-factor auth enabled with/without security key
When the user uses passwordless sign-in link
Then present newly designed "Authenticate your login" design

![image](https://github.com/user-attachments/assets/d0d61645-3301-49a4-b800-3238403213c8)

**Comment by chihsuan** [comment]
Hey @moon0326 Is it correct that #93977 also addresses this issue?

**Comment by moon0326** [comment]
> Hey @moon0326 Is it correct that #93977 also addresses this issue?

Yup!
