### ISSUE TITLE
Reader: mixed content errors

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#932]
Raised by @bazza 

> I noticed the #reader generates #mixed-content errors for some sites (in this case I subscribed to ma.tt)

![matt-insecure](https://cloud.githubusercontent.com/assets/17325/8938292/9e7f42e4-3512-11e5-940c-3d79cdfa0d52.png)

In the past, it was possible to consistently reproduce on Firefox, using this post: https://wordpress.com/read/post/feed/18/760199620

Note from @blowery

> I think its a timing thing.

Note from @designsimply

> I just checked this again and I can see a mixed content error for the latest post on ma.tt

<img width="1280" alt="screen shot 2015-11-29 at sun nov 29 12 48 57 am" src="https://cloud.githubusercontent.com/assets/1119271/11455539/31df02b4-9633-11e5-9d33-3d3d32a97b36.png">
<sup>Seen at https://wordpress.com/read/post/feed/18785507/871775346 using Firefox 42.0 on Mac OS X 10.10.5</sup>

```
Loading mixed (insecure) display content "http://feeds.wordpress.com/1.0/comments/matt.wordpress.com/7661/" on a secure page[Learn More] reader.59b886136ecc04a1fd0a.min.js:3:0
```

**Comment by lancewillett** [comment]
I saw this on Dan Ariely's site yesterday: 

<img width="1179" alt="screen shot 2016-05-25 at 13 16 30" src="https://cloud.githubusercontent.com/assets/66797/15585523/94d64434-2334-11e6-8a78-3d2f5a066ed0.png">

**Comment by coderkevin** [comment]
I just saw this while testing on `master`.
![developer_tools_-_http___calypso_localhost_3000_store_coderkevin_mystagingwebsite_com_products_add_and_reader__mixed_content_errors_ _issue__932_ _automattic_wp-calypso](https://cloud.githubusercontent.com/assets/945228/25629069/eb424272-2f2d-11e7-8409-b2139abdaeb6.png)

**Comment by blowery** [comment]
@coderkevin looks like that came from the notifications client. @dmsnell ?

**Comment by dmsnell** [comment]
@coderkevin and @blowery probably an image inside a post or comment that's trying to load based on the URLs I see. Not sure how we could fix this but maybe on the server try and force HTTPS on all URLs with a string replace?

**Comment by coderkevin** [comment]
IIRC, this was on localhost:3000 for testing on `master`. Would that make a difference?

**Comment by dmsnell** [comment]
maybe @coderkevin but I don't know `¯\_(ツ)_/¯`

**Comment by bluefuton** [comment]
No longer able to access the original post and haven't seen this happen for a while. Please reopen if you see any examples of this 👍
