### ISSUE TITLE
Request access to private site email link not working

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#93226]
### Quick summary

When someone requests access to a private site, an email is sent to the site owner with a link for them to click. But when you click the link, it's not giving access to the site and is instead redirecting to the WP Admin user list, but nothing more.

https://github.com/user-attachments/assets/a09b4cc4-da61-4840-9d3e-e1a9ad5c7d5c

### Steps to reproduce

1. Visit a "Private" site
2. Click the Request Access link
3. Login to the email account for the owner of the Private Site
4. Click the link to allow access to the site

### What you expected to happen

I expected it to add the user as a subscriber.

### What actually happened

It redirected to the WP Admin user list and didn't add the user.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I've only tested this on Simple sites. One Free site and one Explorer plan site.

**Comment by tanjoymor** [comment]
In addition to the issue detailed above, the confirmation email includes a line that says:

`To see a list of users who have access to [SITE], visit [URL]/wp-admin/options-reading.php`

Yet that page doesn't provide any kind of list of viewers or subscribers. I have a user claiming that it used to. Do we know more about this too?

**Comment by allilevine** [comment]
There's two tasks here:
1. Revert the diff: D156494-code to fix the broken link.
2. Show viewers in the users list in wp-admin. Currently they're only visible in /people/team.

**Comment by allilevine** [comment]
> 1. Revert the diff: [D156494-code](https://href.li/?https://code.a8c.com/D156494) to fix the broken link.

Deployed: D157464-code

**Comment by jartes** [comment]
@tanjoymor 
> Yet that page doesn't provide any kind of list of viewers or subscribers. I have a user claiming that it used to. Do we know more about this too?

This was reported previously, and a fix was deployed. But it seems it was not. Asked here: p1723029651402689/1721761574.515359-slack-C0160HSMDQV

**Comment by allilevine** [comment]
> 2. Show viewers in the users list in wp-admin. Currently they're only visible in /people/team.

Proposed short-term and long-term solutions here: pe7F0s-20L-p2

**Comment by allilevine** [comment]
Diff for the short-term solution: D157917-code

**Comment by allilevine** [comment]
> Diff for the short-term solution: D157917-code

Deployed.

**Comment by jartes** [comment]
Thanks @allilevine! Closing this issue :)
