### ISSUE TITLE
TypeIt4Me text expander deletes existing content in the Classic block

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#93232]
### Quick summary

When using the text expander software TypeIt4Me on the Classic block, it replaces all the text in the Classic block and converts the expanded text to the block editor's Paragraph block. TypeIt4Me is a third-party tool.

We've set an expectation for the support since it is a third-party application. We did mention some workarounds, but they expect the text expanders to work on Classic block since it works for block editors without an issue. They mentioned the following:

> Given the great utility and common use of text expanders — and the fact that the text expander works fine in (say) the Paragraph block and the List block and the Quote block, among others, I really think it should work in the Classic block as well. 

Ticket: 8560521-zd-a8c

### Steps to reproduce

1. Have some text in the Classic Block
2. Use TypeIt4Me to expand some text
3. When it expands, it removes all the text from the Classic block and converts the expanded text to Paragraph block.

### What you expected to happen

To expand the text in the Classic Block and not replace the existing block

### What actually happened

The expanded text from the text expander application replaces all the text from the Classic block and converts it to block editor's Paragraph block.

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated / Could Not Replicate / Uncertain
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate it with TextExpander and Alfred: 

https://github.com/user-attachments/assets/779d5ef0-38b1-4e47-aaf6-ae34852de7f5

However, this is a duplicate from #91148

📌 ACTIONS
- Closed as duplicate
