### ISSUE TITLE
Zendesk: mini spike on how to handle email sending and adding notes to HEs

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#93249]
We should find out 
* how to configure a ZendDesk ticket to trigger an email to the user. It will probably need to be parametrized to customize it for the user, including the site they are migrating and their name.
* how to add internal notes to an existing ticket

**Comment by merkushin** [comment]
There are two endpoints in Zendesk API:
- Create ticket: https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#create-ticket ([JSON format for a ticket](https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#json-format))
- Create a comment: https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_comments/#creating-ticket-comments (set `public` to `false` to make it an internal note)

On the WP.com side, we have [Zendesk_API](fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Scyhtvaf%2Smraqrfx%2Qncv.cuc%3Se%3Qr98rq4r4-og) class that implements calls for [creating a ticket](fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Scyhtvaf%2Smraqrfx%2Qncv.cuc%3Se%3Qr98rq4r4%23624-og) and [comments](fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Scyhtvaf%2Smraqrfx%2Qncv.cuc%3Se%3Qr98rq4r4%231106-og).

Also, we have [an endpoint](fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Suryc%2Qzvtengvba%2Qgvpxrg.cuc%3Se%3Q354s1nqn%26zb%3Q41%26sv%3Q5%235-og) for creating a ticket for the migration help.
We probably need to reuse it for the purposes of the project.

We have a staging environment for Zendesk, but it is not suitable for development and testing.

Here is the suggested solution for development and testing:
> If it’s creating tickets for HEs the best solution might be creating them like they will once development is finished, but tag them in a way to exclude them from their views and/or deleting them when done so they’re not counted in any stats.

As for required data in a ticket to trigger email sending: 
> The ticket will need the requester email set. If they are emailed will be based on the triggers we have setup, not something you control when the ticket is created. In short we can email the user (or not) in our Zendesk settings.

**Comment by klimeryk** [comment]
Hi, @andres-blanco , @merkushin! @Automattic/happops-devs are always happy to help navigating the murky waters of Zendesk 🙇 Please feel free to ping us in #happops-dev on Slack or P2 at +happopsdev.

> We have a staging environment for Zendesk, but it is not suitable for development and testing.
It depends on your use case. It's great as a starting point, to avoid sending many test tickets to production. Once you honed in on the logic/shape of the ticket, you can verify on production that it's working as expected there. Staging env is not a copy of production. Most notably, it does not have the plethora of triggers and automations that could introduce unexpected side-effects or outcomes.

> If they are emailed will be based on the triggers we have setup, not something you control when the ticket is created. In short we can email the user (or not) in our Zendesk settings.

Could you share where you've learned this from? If it's documentation, it does not seem fully accurate. Triggers indeed control when we do _not_ send an email notification to the user - but that is based on the metadata from the ticket. For example, there's a marker tag that will always prevent the email notification sent. Happy to discuss details on what best suits your use case!

**Comment by andres-blanco** [comment]
I think between the comments and the P2: p8wKgj-6xJ-p2 post we have enough to start. Nice work @merkushin
