### ISSUE TITLE
QuickForget: create function to create a new secret

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#93248]
Create a function on the backend that given
* A number of reads
* A number of hours for expiration
* A payload

executes a POST to `https://quickforget.com/secret/submit/` with the following form data:

![Image](https://github.com/user-attachments/assets/64635870-116d-4ffb-bfc6-483d0ddffd92)

If the secret is saved successfully the POST will return a redirect (303) and a response header called `Location` with the URL for the secret.

![Image](https://github.com/user-attachments/assets/dcde6491-492d-44e0-a13e-bde9db38207c)

If everything goes right the function should return the URL for the secret. If there's an error a WP_Error object.

We started a file that can be found here: `wp-content/lib/migration/automated-migration-tools.php` to store the utility functions. Probably, that's the best place for this function to live in.

**Comment by valterlorran** [comment]
Closing this as we merged D157612-code.
