### ISSUE TITLE
Zendesk: create ticket to track the migration

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#93250]
Create a Zendesk ticket once credentials are submitted. This ticket should go the the Migration queues and should contain a note with the QuickForget link.

This is related to https://github.com/Automattic/wp-calypso/issues/93249

**Comment by valterlorran** [comment]
It is worth mentioning that we already have the code to create the ticket on the assisted migration flow. We should consider that so we don't create the ticket twice:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Suryc%2Qzvtengvba%2Qgvpxrg.cuc%3Se%3Q354s1nqn%23148-og

**Comment by merkushin** [comment]
> fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Suryc%2Qzvtengvba%2Qgvpxrg.cuc%3Se%3Q354s1nqn%23148-og

I think we can reuse that endpoint, but also add an internal note with a link to credentials.

Or I miss something?

**Comment by andres-blanco** [comment]
@valterlorran @merkushin For this specific issue I had in mind a function rather than an API endpoint. We will need to [create a new endpoint for the UI](https://github.com/Automattic/wp-calypso/issues/93253) and in that endpoint code we should create the ZD ticket. Otherwise we would be orchestrating backend calls from the UI and that normally is complex and error-prone.

So an alternative to reusing this endpoint would be to refactor it and put the ZD code into a separate function that is called from both sides, this endpoint and the new one for the credentials UI.

Please let me know what you think.

**Comment by andres-blanco** [comment]
Closed by this diff D157992-code
