### ISSUE TITLE
API: create endpoint for the UI to use

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#93253]
This is the endpoint that will be used by the UI to store the credentials or backup link. The final description of the work to be done here might change, but at least, this endpoint should:
* Verify that the url provided is valid
* Verify user name (we could use [this function](https://developer.wordpress.org/reference/functions/validate_username/) )
* Verify none of the fields are empty
* If some of the checks above fail return an error
* If everything looks correct it should:
  * Create a ZD ticket to track the migration using D157992-code
  * Run a job that creates the new credentials that will be used throughout the migration (this job D158186-code), if successful, enqueue the job to store the credentials on QuickForget ([this job](https://github.com/Automattic/wp-calypso/issues/93294)).

**Comment by merkushin** [comment]
Make the endpoint site-specific.

**Comment by andres-blanco** [comment]
I just merged it D158344-code closing this issue.
