### ISSUE TITLE
Suggested Tags Not Added After Clicking Add Tags Button

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#93268]
### Quick summary

The automatic tag suggestions lead to a "No Tags Added" result. The reason for the problem is that the suggested tags may partially overlap with the ones I already added.

### Steps to reproduce

1. Write a post
2. Add some relevant tags using the editor
3. Publish the post
4. Select to also add the auto-suggested tags
5. No tags added

### What you expected to happen

Tags to be added

### What actually happened

Tags weren't added

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

https://github.com/user-attachments/assets/a7b54c23-e1ef-43ac-911f-78660100a242

I also found a similar issue that was closed #92461

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate
- Tested on P2 (optional) – Replicated / Could Not Replicate / Uncertain
- Replicable outside of Dotcom – Yes/No

📌 ACTIONS
- Triaged
- Lowered priority from High to Normal.

**Comment by ntsekouras** [comment]
This seems like a Jetpack issue and not a calypso one. @dzver could you 'port' this issue to [Jetpack repo](https://github.com/Automattic/jetpack) (create a new one there and close this one)? Thank you!

**Comment by dzver** [comment]
Per request, I created an issue there and closing this one.
https://github.com/Automattic/jetpack/issues/39110
