### ISSUE TITLE
Create job to store credentials on QuickForget

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#93294]
Recently a function to store secrets on QuickForget was added: D157612-code. We need a job to call this function after the user submits them in the UI.
Since this is sensitive information before calling the job we should
1. Create a JSON string with one object and 3 keys, one for each value. Example:
```json
{
   "site_url": "THE URL",
   "username": "USERNAME",
   "password": "PASSWORD"
}
```
2. Encrypt the JSON string with the `wpcom_encrypt` function

Given 
* The encrypted string 
* The ZD ticket ID tracking the migration

The job will:
1. Decrypt the encrypted param with the credentials
1. Call the function created in D157612-code with the obtained JSON as parameter
2. If there's an error log to logstash and add a note in the ZD ticket describing that there was a failure storing credentials
3. If the call is successful add a note with the QuickForget URL in the ZD ticket

**Comment by valterlorran** [comment]
Closing this as we deployed D157848-code.
