### ISSUE TITLE
Step: Upgrade prompt

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#93297]
### Details

Add a new step to the new migration flow to upgrade the plan. This step should also contain a link to the import flow at the right top. Make sure that this link is only displayed in the new flow and the step doesn't get affected in other flows.

<img width="1700" alt="Screenshot 2024-08-06 at 17 04 18" src="https://github.com/user-attachments/assets/06fb076e-e778-445a-b8c3-c47f324c3df9">

### Checklist

- [ ] The step has a link to the import step at the top right only when it's in the new flow. #93461
- ~~The import step also has a link to return to the migration option.~~ This will be handled as part of https://github.com/Automattic/wp-calypso/issues/93463.

### Related

https://github.com/Automattic/wp-calypso/issues/93258

**Comment by gabrielcaires** [comment]
@renatho According to the thread https://a8c.slack.com/archives/C07FPA0R0KB/p1723483479643709, we will not update the copy inside the boxes.

**Comment by gabrielcaires** [comment]
Completed as part of #93327
