### ISSUE TITLE
Reader: add @mentions to comments

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#933]
Raised by @bluefuton 

> It should be possible to see a list of local users to @mention when writing a comment.

Note from @beaulebens 

> For reference, there's a React-based implementation already in the Notifications client.

Related: #320

**Comment by blowery** [comment]
Related to #320

**Comment by blowery** [comment]
This would use `/users/suggest` for things with site IDs. Likely only wpcom to start.

**Comment by bluefuton** [comment]
@gibrown notes a limitation of the `/users/suggest` endpoint: "you can’t mention anyone who isn’t already on the site". There are plans for an Elasticsearch-powered version.

**Comment by blowery** [comment]
There's also already an implementation in the editor today.

**Comment by bluefuton** [comment]
> There's also already an implementation in the editor today.

There certainly is: https://github.com/Automattic/wp-calypso/pull/8028

I hoped we could reuse this easily but it seems tightly coupled to the Editor (it's implemented as a TinyMCE extension).

**Comment by blowery** [comment]
> I hoped we could reuse this easily but it seems tightly coupled to the Editor (it's implemented as a TinyMCE extension).

Yeah. :/ 

At least we can use the backing redux / data bits.

**Comment by bluefuton** [comment]
🚢 to internal users in https://github.com/Automattic/wp-calypso/pull/24746 🎉
