### ISSUE TITLE
Rename new migration flow

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#93328]
### Details

The new migration flow was created in [this PR](https://github.com/Automattic/wp-calypso/pull/93277). We need to tweak the name to a final one. I'm suggesting `"migration"`, but it's open to other ideas.

For this, it would be good to rename a constant in used called `MIGRATION_FLOW` and its references. See https://github.com/Automattic/wp-calypso/pull/93277#discussion_r1706835675. So we can use this constant.

### Checklist

- [x] The references to the current `MIGRATION_FLOW` were renamed.
- [x] `MIGRATION_FLOW` now has the value `"migration"`.
- [x] The migration flow is loaded under `"/setup/migration"`.

### Related

https://github.com/Automattic/wp-calypso/pull/93277

**Comment by gabrielcaires** [comment]
We also need to  update this class name when we rename here https://github.com/Automattic/wp-calypso/pull/93382/files#diff-fbcb3c2ed35577fdd0b8a488e1602148c7707df9afdb84d39b52be49c22fc5cdR5
