### ISSUE TITLE
Activate new flow if the experiment is a success

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#93348]
### Details

Only when (and if) the project is validated, we should activate the new flow, remove the experiment integration, and the code that will become obsolete.

If we decide that the project doesn't go ahead, we can remove the experiment and the created flow.

### Checklist

- [ ] Expriment is removed.
- [ ] New flow is activated if the experiment is a success.
- [ ] Obsolete code is removed.

**Comment by donnapep** [comment]
Experiment was not a success. Closing.
