### ISSUE TITLE
Design Picker: Text layout in upgrade tooltip

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#93356]
### Quick summary

The Upgrade tooltip in the design picker onboarding step has a single lonely word that looks off.

<img width="650" alt="image" src="https://github.com/user-attachments/assets/cdd74a5d-60ad-4564-867a-092a7081a3d2">

This only seems to be happening in onboarding, in the theme showcase it works as expected:
<img width="737" alt="image" src="https://github.com/user-attachments/assets/a63ae41e-085e-496b-a845-9bf1247257ea">

### Steps to reproduce

1. Start at /start and go through onboarding.
2. Pick free plan, and "Other" as site goal.
3. In the design picker step hover over Cottage or Vows themes Upgrade text.
4. Note the tooltip content is split into two lines, with the word "plan" on its own new line.
5. Hover over a theme that requires premium plan, for example Podcasty, and note the text layout is better.
<img width="701" alt="image" src="https://github.com/user-attachments/assets/ba9f1214-14c0-4c42-90ae-b48f29627070">

### What you expected to happen

I expected words "Personal plan" to be together on a new line in the Upgrade tooltip.

### What actually happened

The word "plan" was alone on a new line in the tooltip.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Replicated during onboarding.

📌 ACTIONS
- Triaged
- Lowered priority.
