### ISSUE TITLE
Feature Request: Add Support Link to Blog Stats block

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#93387]
### What

Add a "Learn More" link to the Blog Stats block description that links to https://wordpress.com/support/widgets/blog-stats-widget/

[Similar Examples](https://github.com/Automattic/wp-calypso/issues/67293)

### Why

This will help WordPress.com users easily discover our comprehensive resources on how to use each block in the editor. With these support docs, users can learn about blocks more quickly, figure out the settings themselves, and reduce their likelihood of contacting support for basic editing tasks.

### How

[Similar Examples](https://github.com/Automattic/wp-calypso/issues/67293)

**Comment by Aurorum** [comment]
Hi @ktyfuller604! That support doc is for the Legacy Widget, which has a different set of instructions to the block, but perhaps more crucially, it doesn’t contain information or instructions on the functionality that the block now provides. I can’t seem to find a support document for the block - would you know whether it exists? Thanks!

**Comment by ktyfuller604** [comment]
Sorry @Aurorum! I just wrote the doc and copied the wrong link. 😄 

Correct doc: https://wordpress.com/support/wordpress-editor/blocks/goodreads-block/

**Comment by Aurorum** [comment]
Thank you! :)
