### ISSUE TITLE
Site Verification Tools: "full instructions" link should open in a new tab

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#9339]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/seo/
2. Pick your site.
3. Click on " full instructions"
4. The support page opens in the same window, although all the other links open in a different window.

Reported in p2JiWH-1tm-p2

**Comment by drw158** [comment]
Not a bug, it was intentional. External links are denoted with the external icon.

**Comment by drw158** [comment]
I'm not opposed to making it external, since the user could lose their place. Just make sure to include the external icon!

**Comment by jeherve** [comment]
This has not changed.
