### ISSUE TITLE
Image Block 'Rotate' Feature Not Working on Simple Sites

### ISSUE THREAD

**Issue by mahfuzurwp** [Automattic/wp-calypso#93403]
### Quick summary

The 'Rotate' feature of the image block is not functioning as expected on simple sites. When attempting to rotate an image within the block, the image remains unchanged, and no rotation occurs.

However, it is working on atomic sites as expected.

### Steps to reproduce

1. Go to a simple site.
2. Insert an image block in a page.
3. Upload or select an image.
4. Attempt to rotate the image using the 'Rotate' feature in the block settings.

### What you expected to happen

The image should rotate by 90°, 180°, 270°, or 360°.

### What actually happened

The image does not rotate, and the feature appears to be non-functional.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Edit the Image in Media: https://wordpress.com/support/media/editing-an-image/#rotate-crop-or-flip-an-image

### Logs or notes

A screen recording of the issue can be viewed here: [Loom Video](https://www.loom.com/share/efd9133696a04d2eb8f50b35d1cad499?sid=53350a69-59c9-4100-999c-3b802c6d2af1).

**Comment by coder-mahfuz** [comment]
zen-8544970

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic –  Could Not Replicate

📌 ACTIONS
- Triaged
- Requested author feedback
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
👋🏻 @coder-mahfuz Thanks for reporting this, but I'm not able to replicate it either on Simple and Atomic sites. Can you please check it from your end? Thanks 🙏🏻
