### ISSUE TITLE
Posting multiple photos make the Reader ignore my text

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#93414]
### Quick summary

Posting a blog post with text and multiple photos makes the reader treat is as a gallery. The text is ignored and it gets no clicks.

### Steps to reproduce

1. Using a desktop browser
2. Post a post with more than one photo and text
3. Go to the reader
4. It displays a gallery with no text

### What you expected to happen

1. Post a post with more than one photo and text
2. Go to the reader
3. See the text and one photo

### What actually happened

3. I saw a gallery of my photos, all text stripped

<img width="638" alt="Screenshot 2024-08-09 at 17 24 51" src="https://github.com/user-attachments/assets/64657091-f0e9-4bdb-a7cc-11ad66cfca1d">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Chrome browser, 13"

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
Replicated.

📌 FINDINGS/SCREENSHOTS/VIDEO

<img width="629" alt="Screenshot 2024-08-11 at 3 59 45 PM" src="https://github.com/user-attachments/assets/b035b25f-2d0e-4c60-afe0-75b788b2bd17">

I honestly thought this was expected, as mentioned here:
https://wp.me/p5PDj3-1ym  

That said, I agree that no text is displayed, only images. This might not be a good experience for users.

📌 ACTIONS
- Triaged

**Comment by lsl** [comment]
> The Gallery card is used when the post contains text and 4 or more images (excluding the featured image – the featured image is ignored for the Gallery card to avoid duplications if the author used the image in the post as well). The card gets a row of four images above the headline. These images should be the first four usable (over 350px) images in the post. Each image gets 25% of the width. 1px of whitespace in between each image.

Looks like expected behavior, we also do show text along with the images but you need a certain word count or maybe placement for it to show up.

![Screenshot 2024-08-15 at 16-08-05 Following ‹ Reader — WordPress com](https://github.com/user-attachments/assets/38d84948-4e2c-4d5d-9cdf-77076421fddc)

**Comment by inaikem** [comment]
Pulling out a thread from DM: 

This is expected behaviour for the Reader preview but not a great experience. 

Considering the original presentation was outlined nearly 8 years ago, I believe there's a case to improve that. Reopening as an Enhancement and pinging @davemart-in in case this is a potentially quick fix, or there's capacity in the team to prioritise it 🙏

**Comment by davemart-in** [comment]
> This is expected behaviour for the Reader preview but not a great experience.

We can add this to our queue if it's clear what the expectation is. I'm hearing a couple of different perspectives.

If we can get consensus on what _would_ be a great experience, I'm happy to add it to our board.

**Comment by dzver** [comment]
As a minimum, the text must be visible.

**Comment by davemart-in** [comment]
Thanks. I think we can do that. Okay, so here's my summary:

## Expected

If I publish a post with multiple images and text, some portion of the text should be shown.

## Actual

If I publish a post with multiple (4+) images and text, only the images are shown.
