### ISSUE TITLE
Plugins marketplace - site level - sidebar submenu collapses when visiting an individual plugin.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#93424]
Notice that the submenu group under "appearance" collapses and expands when going between the plugins marketplace and individual plugin pages.

https://github.com/user-attachments/assets/7f5e1374-d8b0-48ea-91bc-5e529956ea6a

I would expect the sidebar submenu group to stay expanded while in this flow.

**Comment by mmtr** [comment]
The same underlying issue (but with a slightly different effect) is also present on Simple sites:


https://github.com/user-attachments/assets/b3ebf9d2-a5a9-407c-94e4-c8347f04ca2b
