### ISSUE TITLE
Help Center: Unable to contact support through Wapuu in some cases

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#93427]
### Quick summary

In some cases users are unable to contact support through Wapuu. This was experienced by @andrewspittle through the new Feeling Stuck? direct contact option we added, but it's unclear if it's directly related to that.

### Steps to reproduce

1. Open Help Center
2. Click Still Need Help
3. Ask Wapuu a question
4. Click Contact our support team link next to Feeling stuck?
5. Contact option is greyed out

### What you expected to happen

To be able to contact support. I'm also unclear why it moves outside Wapuu versus showing the contact option in-line like it does if you ask for a human or thumbs down. But if we don't want to tackle that now we can do this as part of our work to bring Messaging into the Wapuu UI when we'll just open the conversation below the AI messages.

### What actually happened

The contact option was greyed out and unable to be used. 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

Browser: Safari

**Comment by AllTerrainDeveloper** [comment]
The feeling stuck is using the same logic as the old button "Still need help"? that showed all the available contact options, which is to navigate to "/contact-options" within the Help Center.

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
Unable to replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

The option to contact Support is active and clickable -- and on the screen recording below (GIF), I managed to open two interactions.
![Aug-11-2024 15-34-49](https://github.com/user-attachments/assets/8df8e376-c27c-420a-b0eb-22d05572d19f)

Also, an HE was able to support me immediately: 8595638-zd

📌 ACTIONS
- Triaged

**Comment by escapemanuele** [comment]
Hey @kriskarkoski, I believe we can say that the bad UX is opening a new page to just show the button to contact support.

But as the others were saying, I was able to open Zendesk when clicking that button.

Is the button still gray for you?

**Comment by AllTerrainDeveloper** [comment]
I would be happy to modify the UX :) I just don't have any other option or design. That was thee quick thing in order to move faster.

**Comment by escapemanuele** [comment]
I feel like that if the only option we offer is a button, then we could make the users avoid clicking that button and directly send them to Zendesk!
Asking @kriskarkoski for a confidence check on this.

**Comment by lsl** [comment]
Safari could be causing this, and it may not be easily reproducible as they use heuristics to determine where and when things get blocked that isn't the same for all users.

Can anyone, using safari, get a screenshot of the "greyed out state"?

I'm seeing this in firefox, the zendesk urls are getting blocked as trackers:

![Screenshot(245)](https://github.com/user-attachments/assets/5339cc46-5ff1-4906-a349-cd90a6eb924f)

![Screenshot(246)](https://github.com/user-attachments/assets/2fa1ee98-ca0e-4417-998d-d0428f98016e)

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/blob/7e0d8e19ad5e0aa975510a7dd7c1082753d521c3/packages/help-center/src/components/help-center-contact-support-option.tsx#L41

This button is only disabled (greyed out) when `isOpeningZendeskWidget` is set to true.

That is only set to true in two scenarios: https://github.com/Automattic/wp-calypso/blob/7e0d8e19ad5e0aa975510a7dd7c1082753d521c3/packages/zendesk-client/src/use-open-zendesk-messaging.ts#L51
1. After you click, while some data is being submitted, before we open the chat window with zendesk.
2. If the zendesk messaging script isn't loading for some reason.

Without being able to reproduce the issue there's not really much we can do here in terms of bug fixing.

Please feel free to re-open if you think it's worth specing out something to improve the error handling.
