### ISSUE TITLE
Issue with .env file not loading during yarn start

### ISSUE THREAD

**Issue by MrCyberlord** [Automattic/wp-calypso#93438]
### Quick summary

Hello, I’m trying to run the Calypso project locally by following the setup instructions, but I’m encountering an issue where the .env file fails to load during yarn start. The following message is displayed:

Failed to load ./.env.

The server then gets stuck in the "Compiling assets" phase and never fully loads.

### Steps to reproduce

Clone the repository and follow the guidelines in the readme file.
Run yarn start in the terminal from the project root.
Observe the terminal output and logs.
Wait for the project to compile and the development server to start.
Start at http://calypso.localhost:3000.

### What you expected to happen

The development server should start successfully, and the Calypso application should be accessible at http://calypso.localhost:3000.

### What actually happened

The terminal displays a message: Failed to load ./.env.
The server then gets stuck in the "Compiling assets... Wait until you see Ready!" phase and never fully loads.
The application does not become accessible at http://calypso.localhost:3000.
![calypso](https://github.com/user-attachments/assets/1cd2bba5-07f6-4c80-8e45-c27520db57ba)

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

OS - Windows 11
yarn - 4.0.2
node - v20.8.1

**Comment by lsl** [comment]
> `Failed to load ./.env.`

Just a warning about missing env file, you can ignore the error or create an empty .env file in the root.

> The server then gets stuck in the "Compiling assets" phase and never fully loads.

This looks like an out of memory error.

You could try bumping node's `--max_old_space_size` option, e.g.

```
wp-calypso trunk env | grep NODE
NODE_ARGS=--max_old_space_size=24087
NODE_OPTIONS=--max-old-space-size=24087 --no-deprecation
```
