### ISSUE TITLE
Help Center: Thumbs Up Message Duration

### ISSUE THREAD

**Issue by connorhipps** [Automattic/wp-calypso#93433]
### What

When the thumbs-up message is selected in the Help Center, it appears very briefly. The expected behavior is that the thumbs-up button's duration matches that of the thumbs-down button. 

**Message Location:**

![CleanShot 2024-08-09 at 17 27 25](https://github.com/user-attachments/assets/a16a36c0-6a9d-4e7d-829a-ffa828979413)

**Example:**

https://github.com/user-attachments/assets/08e465e5-059e-4ada-aedf-e26deeebfe74

![CleanShot 2024-08-09 at 17 32 08](https://github.com/user-attachments/assets/be4d8ead-8667-410b-bc10-e4cba1c3825b)

### Why

The briefness of the "Thank you!" message is distracting. 

### How

Perhaps we can match the thumbs-up action to the thumbs-down?

**Comment by renancarvalho** [comment]
Probably, we can increase the animation duration. Haven't tested but seems to be [here](https://github.com/Automattic/wp-calypso/blob/trunk/packages/odie-client/src/components/message/style.scss#L426)

**Comment by escapemanuele** [comment]
@connorhipps tested this and the animation duration seems fixed now

**Comment by renancarvalho** [comment]
This has been fixed, probably with all the changes done in the Help Center redesign pdDR7T-1Qg-p2
Closing :)
