### ISSUE TITLE
Marketplace: WP.org plugin zip links to trunk rather than stable

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/wp-calypso#93439]
### Quick summary

Follow up to #81685

The WP.org link on plugin pages currently link to `https://downloads.wordpress.org/plugin/plugin-slug.zip`, for example the WooCommerce download link is https://downloads.wordpress.org/plugin/woocommerce.zip

The `plugin-slug.zip` files are generated from trunk rather than from the version listed as stable, stable releases use `plugin-slug.latest-stable.zip`, for example the WooCommerce stable download link is https://downloads.wordpress.org/plugin/woocommerce.latest-stable.zip

Usually this is fine but for plugin that tag beta an release candidate versions on WP.org the download link on the market place can link to non-productions versions of plugins. This affects both WooCommerce and Jetpack.

### Steps to reproduce

1. Wait until WooCommerce or Jetpack tag a beta/RC release
2. Visit the plugin's marketplace page on WP.com
3. Click the download link for WP.org
4. Unzip the plugin
5. Observe the version number is listed as RC while the stable version links to the stable version.

### What you expected to happen

Download links should link to the most recent, production ready, stable version.

### What actually happened

Download links are to unstable versions not recommended for production.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Calypso – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
This can be directly reproduced with the Jetpack plugin: https://wordpress.com/plugins/jetpack. When clicking on the `Download` button, we get the JP beta version.

📌 ACTIONS
- Triaged

📌 Message to Author
Good catch! Thanks for reporting this one @peterwilsoncc! 

Adding to @Automattic/bespin backlog.
