### ISSUE TITLE
Help Center: "Get Help" Beside ?

### ISSUE THREAD

**Issue by connorhipps** [Automattic/wp-calypso#93435]
### What

We list "Get Help" throughout the dashboard to access support. The help center option in the top navigation (`?`) doesn't include this text. 

We should add "Get Help" beside `?` for consistency. 

### Why

The `?` doesn't clearly convey an option to access customer support. Adding "Get Help" will align our support access with the top navigation. 

![CleanShot 2024-08-09 at 17 34 21](https://github.com/user-attachments/assets/6729c5cb-7b83-4655-8c2a-bf3f0db949bc)

**Comment by matt-west** [comment]
I agree with Javi’s suggestion here. A tooltip feels more appropriate as we’re trying to keep this menu minimal.

This icon does currently have a simple tip on hover:

![Image](https://github.com/user-attachments/assets/f491ca30-8667-41c5-b186-b43bbc8feb99)

This is default browser behaviour based on the `title` attribute on the button.

If we implement a custom tooltip here, we should remove the default behaviour and add tooltips to the Reader and Notifications icons for consistency.
