### ISSUE TITLE
DevDocs: Canonical image not displayed on RefreshCards

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#9346]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/refresh-cards

#### What I expected
To see images on each example card.

#### What happened instead
The only images shown are on the gallery example.  PR #9149 indicates that the first choice for an image to be displayed should be the canonical image, which this component has defined [here](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/reader-post-card/docs/example.jsx#L30), but nothing is being loaded.

cc: @samouri

#### Browser / OS version
Seen in OSX Chrome and Firefox

#### Screenshot / Video
![screen shot 2016-11-14 at 9 43 25 am](https://cloud.githubusercontent.com/assets/7233112/20268837/cf3b468c-aa4e-11e6-80e8-72f5b6e4275e.png)

#### Context / Source
#automated-testing #visdiff

**Comment by hoverduck** [comment]
Update: As of now the Gallery cards are also not showing any images in DevDocs

**Comment by samouri** [comment]
Thanks for the find @hoverduck! Hopefully 9400 will fix it

**Comment by hoverduck** [comment]
Looks good to me!  I see the note in #9400 saying it's a band-aid rather than a long-term fix...do you want to leave this issue open to track that, or close it and open a new one if another fix becomes necessary?

**Comment by samouri** [comment]
I think we should close this and only work towards the stronger fix if it becomes obvious that it is necessary (it is more heavyweight + complex)

**Comment by hoverduck** [comment]
Sounds good.  Closing.
