### ISSUE TITLE
QR login page not responsive 

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#93482]
### Impacted plugin

Jetpack

### Quick summary

Try logging in using the QR code

### Steps to reproduce

1. Start at https://wordpress.com/log-in
2. Click on "Login via app"
3. Check the full page

### A clear and concise description of what you expected to happen.

The QR code should be fully visible and not go outside the container

### What actually happened

The code is cut on the side, so I can't scan it even if I zoom out.

![asan7I.png](https://github.com/user-attachments/assets/0ec4c220-7361-4d1b-a17b-374b3f72dec9)

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Found it while reviewing some of the log-in/out flows.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Calypso – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tried to replicate it on Safari and Chrome with an iPhone 13, but I got the QR code without getting cut: 

![46950CEA-2A37-4DB6-9812-3E87A1AC2C89_4_5005_c](https://github.com/user-attachments/assets/d134cfed-b707-4532-bd00-4e9663a3e594)


📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
👋🏻 @Robertght Are you still being able to reproduce this? Which device are you using?

**Comment by Robertght** [comment]
@jartes I'm using Chrome on an iPhone 13 Pro. 

It appears the issue is also present on Safari.

![FrzWVf.png](https://github.com/user-attachments/assets/fcaa9e22-486b-4c90-a6bd-f3c4120864c6)

**Comment by lsl** [comment]
Repro anything below 375 width
