### ISSUE TITLE
Billing history: Get.blog receipts showing on WordPress.com billing history

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#9348]
Receipts for items purchased in get.blog are showing in the receipts in WordPress.com:

<img width="788" alt="screen shot 2016-11-14 at 10 03 25 am" src="https://cloud.githubusercontent.com/assets/275961/20270465/0c91f906-aa7f-11e6-934e-0a175ce4c99b.png">

This looks very similar to: https://github.com/Automattic/wp-calypso/issues/7964

We need to update the endpoint so it only returns WordPress.com receipts.

Originally reported by @kriskarkoski.

**Comment by fabianapsimoes** [comment]
@melanieharari I'm moving this to Amber's backlog, since we'll need to address it as part of future work we're doing for get.blog billing.

**Comment by fabianapsimoes** [comment]
Fixed with D3771-code.
