### ISSUE TITLE
`redirect_to` param in `/log-in` page is reset in some cases

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#93522]
### Quick summary

The `/log-in` page sometimes sets a `redirect_to` param when arriving on the login page from another WP.com page. There's a bug that causes the param to reset in some instances. 

### Steps to reproduce

There are a few ways to reproduce this issue:

**Method 1**

1. Go to the logged-out landing page https://wordpress.com/newsletter/
2. Click "Start my newsletter" CTA
3. In the `/start` page, click on "Continue with email". Notice the page URL has the `redirect_to` prop with the value `redirect_to=%2Fsetup%2Fnewsletter%2FnewsletterSetup%3Fref%3Dnewsletter-lp`. 
4. Enter an email address that has an existing WP.com account.
5. You will now be taken to the `/log-in` page. Notice in the URL that the `redirect_to` query param has already changed value to `redirect_to=https%3A%2F%2Fwordpress.com%2Fsetup%2Faccount`.
6. Complete signing in to the account.

**Method 2**

1. Repeat steps 1-5 above.
2. Click on "Email me a login link" in the `/log-in` page.
3. In the `/log-in/link/...` page, click on "Enter a password instead".
4. You'll be back on the `/log-in` page. Now complete signing into the account.

### What you expected to happen

I expected to be taken to the newsletter signup flow after successfully signing in.

**NOTE: Please also verify with other sign in methods such as Google / Apple / GitHub / "Login via app" methods on whether the `redirect_to` param value is retained.**

### What actually happened

I was taken to My Home page because the `redirect_to` prop was reset to a path that does not exist.

### Impact

This impacts existing users because we're not taking them to the intended destination. This bug also affects our metrics as some of our funnels track signup step -> onboarding step completion rate. If the user is directed to the Customer Home page, then it artificially decreases the step completion rate.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Able to replicate by using a password and the login link that is being sent via email.

📌 ACTIONS
- Triaged
- Added high priority as this is affecting Dotcom users who are logged out.
