### ISSUE TITLE
Reader - move admin bar link to the right side of the masterbar

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#93534]
related thread - p1723032282006269-slack-C06DN6QQVAQ

We want to test having the reader on the right side of the adminbar instead of the left.

Current position:
<img width="1390" alt="Screenshot 2024-08-14 at 11 51 19 AM" src="https://github.com/user-attachments/assets/e91fe96f-19dd-41f7-869a-78a29bd0dd1b">

Proposed position:
![image](https://github.com/user-attachments/assets/38e55083-a32a-4bb2-807b-240c9ec453a7)

We will want to ensure this is moved for:

- [ ] calypso admin bar
- [ ] site admin bar (classic)
- [ ] site admin bar (default)

We will want to also measure the impact of this on the readers usage. Notes on click events and feed loading events that may be useful in the slack thread p1723488532296959/1723032282.006269-slack-C06DN6QQVAQ

**Comment by davemart-in** [comment]
Update: I pinged Matt just to vet this idea prior to us picking it up. I'll follow up once I hear back from him.

**Comment by danielbachhuber** [comment]
@davemart-in @Addison-Stavlo Can we queue up the PRs for this, please?

**Comment by davemart-in** [comment]
Can do. I moved it to ready for dev, high priority.

**Comment by danielbachhuber** [comment]
Also, to clarify my intent: I'm fine and even supportive of us iterating on the Reader and driving more Reader usage.

I think the current nav item location is incorrect, though, and receiving a lot of accidental clicks as folks try to work on their website.

**Comment by allilevine** [comment]
PRs here:
- https://github.com/Automattic/jetpack/pull/38976
- https://github.com/Automattic/wp-calypso/pull/93749
