### ISSUE TITLE
Subscriptions: Don't email deleted accounts

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#93548]
Background: https://github.com/Automattic/wp-calypso/issues/56919, 

This issue is to split off and track a fix for the sending email part, leaving the count recalculation issue as a separate problem.

Done means:
- [x] When sending new post / follower notification emails to subscribers we need to check the receiving account hasn't been deleted. 
- [x] If the account has been deleted, don't send the email.

**Comment by miksansegundo** [comment]
I haven't been able to test this because I don't receive any emails on my subscriber inbox after posting content. Maybe it's my user, or my site.

I'm going to leave it and work on another issue.

**Comment by TimBroddin** [comment]
I'm taking over this ticket and I'm working on a diff that will prevent new post / comment emails from going out to deleted user accounts.

@lsl  Do we have a report on follower notification emails going out to deleted user accounts? I can't seem to replicate this.

**Comment by TimBroddin** [comment]
Diff: D158732-code

**Comment by miksansegundo** [comment]
Approved 👍

**Comment by miksansegundo** [comment]
@TimBroddin would you be interested in giving a try to fix this [other issue](https://github.com/Automattic/wp-calypso/issues/68506) that is also related to subscribers? I am struggling to reproduce it because it seems to happen only when the subscriber's membership for paid content is renewed.

**Comment by TimBroddin** [comment]
Will do, thanks for the review!

**Comment by miksansegundo** [comment]
We can close this now that D158732-code is deployed to avoid emailing deleted accounts. 

The pending part for the count recalculation issue is tracked in https://github.com/Automattic/wp-calypso/issues/56919#issuecomment-2290366844
