### ISSUE TITLE
The Reader link from a subscription profile points to null

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#93550]
### Quick summary

Some sites have their Reader feeds pointing to null

### Steps to reproduce

1. Go to https://wordpress.com/read/subscriptions/774515505
2. Click Reader
3. See an error

https://github.com/user-attachments/assets/9da3cada-be57-419e-9423-829320559ffd

### What you expected to happen

3. See a feed with posts

### What actually happened

3. The link points to /null and is broken

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
Replicated.

To note: To access the link https://wordpress.com/read/subscriptions/774515505, we must subscribe to the website first. If we haven't subscribed to the site, we will see "Subscription not found" message. 

For this triage, I'm using my personal WPCOM account and subscribe to martiandaze.net from Reader, and this is the subscription link that I have: https://wordpress.com/read/subscriptions/780042867 (TIL, it's different for every user, I guess?)

📌 FINDINGS/SCREENSHOTS/VIDEO

GIF screen recording:
![Aug-15-2024 15-12-53](https://github.com/user-attachments/assets/0a129d08-a3e3-4105-9eb3-4a1333db541c)


📌 ACTIONS
Triaged

**Comment by dzver** [comment]
Another example:

https://myinspiredlife.org/2024/08/14/top-it-off/ - This is a poem and then some text

<img width="836" alt="Screenshot 2024-08-15 at 10 34 00" src="https://github.com/user-attachments/assets/637b6d98-46fc-405f-bf01-d48a2c49a1e1">

Here's the Reader representation:

<img width="630" alt="Screenshot 2024-08-15 at 10 33 23" src="https://github.com/user-attachments/assets/840af691-9712-41fe-b882-72eae1bedd4c">

**Comment by retnonindya** [comment]
@dzver it seems like the comment you just shared before should be on this issue: https://github.com/Automattic/wp-calypso/issues/93414

**Comment by retnonindya** [comment]
Closing as we have a [fix](https://a8c.slack.com/archives/C02FMH4G8/p1723709998210369?thread_ts=1723706740.777859&cid=C02FMH4G8)
