### ISSUE TITLE
Help Center (module) CSS is loaded on site frontend on WordPress.com

### ISSUE THREAD

**Issue by sergiu-radu** [Automattic/wp-calypso#93561]
### Quick summary

Hello guys,

We recently noticed that the `https://widgets.wp.com/help-center/help-center-wp-admin.css?ver=db43fb906617f7ff786e` file is loaded on the front end of the site causing conflicts with the theme variables in the Blocksy theme.

I suspect this CSS is needed for this module:
![CleanShot 2024-08-15 at 19 05 18](https://github.com/user-attachments/assets/32f9a4b1-f4af-4074-8942-9fe9b95c98cb)

The file rewrites some variables that are defined by the theme, specifically as you can see in the screenshot:
- `--theme-text-color`
- `--theme-icon-color`

I understand that this is the naming convention you use in Calypso but at the same time it is not correct to apply them on the front end of the site.

Maybe you need to scope somehow those variables more specifically?

### Steps to reproduce

1. Start with a site that has a Business plan
2. Install & activate Blocksy theme
3. Install and activate the Blocksy Companion plugin
4. Open "Customizer", make a small change and hit the "Publish" button
5. Close the "Customizer" and open the frontend
6. You will see that some parts with text are white

### What you expected to happen

I expect the `help-center-wp-admin.css` won't override the theme colors.

### What actually happened

All the text is white because `help-center-wp-admin.css` is overriding it.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by sergiu-radu** [comment]
Hello guys, do you have any updates on this?

**Comment by arcangelini** [comment]
Hey @sergiu-radu we have a few PR's that will address this issue that will get deployed ASAP. We are testing them now and should hopefully have them deployed in the next day or so.

**Comment by sergiu-radu** [comment]
Hi @arcangelini, that's awesome, thanks you very much for the heads up.

Have a wonderful day!

**Comment by mxhassani** [comment]
While waiting for the PR deploy, this is another report 8634538-zen

**Comment by arcangelini** [comment]
Just an update. We deployed a fix yesterday to Jetpack. This should get released today.

https://github.com/Automattic/jetpack/pull/38941

**Comment by sergiu-radu** [comment]
Hello @arcangelini, thanks for the heads up!
I can confirm, this issue seems to be fixed on WPCOM, thank you!

**Comment by arcangelini** [comment]
The fix has landed ✅
