### ISSUE TITLE
Install Theme: On free sites, the disabled dropzone still highlights when dropping files

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93579]
## Description

The theme install dropzone is disabled for free sites, but it's still highlighted when dropping a file.

![Image](https://github.com/user-attachments/assets/2a376704-6dc5-437c-85e1-8202f1331bfc)

## Acceptance Criteria
- [ ] The dropzone should remain disabled and not react to dropped files.

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/93958 should resolve
