### ISSUE TITLE
Users -> {My Profile, Account Settings} on unproxied (non-superadmin) Simple Default sites

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#93578]
`Users -> {My Profile, Account Settings}` are missing when the following conditions are all met:

1. Simple site,
2. using Default admin interface,
3. when on Calypso screen (e.g. My Home),
4. unproxied (non-superadmins)

They are correctly shown if we're on wp-admin pages, though:

|Calypso|wp-admin|
|-|-|
|![Image](https://github.com/user-attachments/assets/a37fec76-f6dc-402a-bad3-39c913aeae8f)|![Image](https://github.com/user-attachments/assets/305e20d4-4258-4a09-998d-11b2dc4553d5)|

**Comment by fushar** [comment]
@okmttdhr you can check my investigation of the other issue here: D158515-code. I believe it could be related.

**Comment by okmttdhr** [comment]
I just submitted this one for review: D158687-code

**Comment by okmttdhr** [comment]
I deprioritize this issue since the Site Level Profile will address this issue and the solution may look like tricky: D158687#2973469-code

**Comment by davemart-in** [comment]
Removing from logical flows board.

**Comment by okmttdhr** [comment]
Closing as we launched the Site-Level User Profile
https://dotcomhappy.wordpress.com/2024/09/03/heads-up-site-level-users-profile-page-is-launching/
