### ISSUE TITLE
Plugins Marketplace: Plugin card titles are truncated

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93583]
## Description

When comparing to the dotorg plugins directory, long plugin names are truncated in the Plugins Marketplace. In dotorg's plugin directory, they wrap to new lines.

| Dotcom Plugins Marketplace | Dotorg Plugins Directory |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/3a396f35-de6a-4300-bf7d-91569a49b5b7) | ![Image](https://github.com/user-attachments/assets/c9c338f6-4f8d-4c62-a301-d324a82f8169) |

**Comment by eoigal** [comment]
The issue I'm seeing here is that the plugin description is not aligned if one plugin has a title with 2 lines and another with 1.

If I clamp to 2 lines it looks like this;
![Image](https://github.com/user-attachments/assets/3b7c458d-6b55-4f37-8ffe-7ca8e5a86c6d)

If I set a min-height to allow descriptions to be aligned, there is now empty space under the plugin title;
![Image](https://github.com/user-attachments/assets/c74eb414-bd36-4152-9ad9-7fd182d95eae)

@davemart-in - Do you have any suggestions on how best to proceed with this? Thanks

**Comment by davemart-in** [comment]
@eoigal let me play around with this a little bit.

**Comment by davemart-in** [comment]
@eoigal I just pushed a proposed solution. Let me know what you think.
