### ISSUE TITLE
Reader: improve highlighting of current post in stream when using J and K keyboard shortcuts

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9358]
We came up with an interim solution for cards that are `is-selected` and as mentioned in https://github.com/Automattic/wp-calypso/pull/9330, we'd like to revisit this and implement a border around the card as it's a more obvious solution to selected cards.

> keeping the 830px in place, but adding a little more whitespace in the cards, so reducing the column width visually by a little bit

**Comment by fraying** [comment]
Note that, when we do this, it's okay if the cards get a little narrower. I think the addition of a little more whitespace would help.
