### ISSUE TITLE
Plugins Marketplace: No back navigation when clicking on "Browse All"

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93588]
## Description

The Plugins Marketplace defaults to showing many sections where users can click on "Browse All" to see the full list.

![Image](https://github.com/user-attachments/assets/b458cc58-cd22-4c68-a226-03c4b8ce2a43)

However, once they enter the subsection, there is no back button to go back to the previous state.

![Image](https://github.com/user-attachments/assets/7bff847b-02d9-42d6-a00d-aaa4e2044f9c)

**Comment by davemart-in** [comment]
Let's just add one, pulling the same style from other pages with a back button.

**Comment by dsas** [comment]
> pulling the same style from other pages with a back button.

Can anyone quickly name one? We don't have one on /themes, /read, /sites. Outside of Onboarding the only one I can think of is purchases:

<img width="1459" alt="Screenshot 2024-08-19 at 11 40 16" src="https://github.com/user-attachments/assets/3005ac69-0dff-4c29-8d5f-0b415213e773">

I'm not even sure where to put a back button, I had assumed next to the header, but the header is always "Plugins marketplace" so "Back" there makes it feel like you're leaving the marketplace.

My quick and dirty attempt is this, I'm not certain it looks right

<img width="1459" alt="Screenshot 2024-08-19 at 11 57 15" src="https://github.com/user-attachments/assets/a5a77947-2ef2-4b59-b699-90cadd486878">


CC @lucasmendes-design / @javierarce

**Comment by dsas** [comment]
Maybe we just need to make "Plugins marketplace" be a link back to "Discover"

**Comment by javierarce** [comment]
Why don't we make the "Discover" option sticky like the search field on the left? It's not really a category and it could act as the back button.

**Comment by dsas** [comment]
I wondered about that too, in the theme showcase we have "All" which serves that purpose. I'm not sure if "Discover" is discoverable enough, but maybe it'd work if it had the right ui affordances.

**Comment by javierarce** [comment]
> I'm not sure if "Discover" is discoverable enough, but maybe it'd work if it had the right ui affordances.

True. Maybe with a light shade of gray? 

![image](https://github.com/user-attachments/assets/8f6b77f9-3ba9-4361-a25d-86e7c4355dbd)


And here's also alternative idea for a back link (the copy is just an idea, perhaps "See all" is not the best solution)

![image](https://github.com/user-attachments/assets/fb99ad43-dfb8-49ba-92df-e2f49d260ad6)

**Comment by javierarce** [comment]
And thinking a bit more broadly, what if, instead of working on this issue, we unified the Theme and Plugin navigations?

**Comment by Addison-Stavlo** [comment]
> Can anyone quickly name one?

The individual plugins page show one on tablet view:

<img width="950" alt="Screenshot 2024-08-22 at 9 24 46 AM" src="https://github.com/user-attachments/assets/947ded6b-8d0f-4ccf-867b-6d587c6debe5">

While on desktop it is replaced by "Pugins -> {current plugin name}" and clicking "plugins" serves as going back:

<img width="780" alt="Screenshot 2024-08-22 at 9 25 41 AM" src="https://github.com/user-attachments/assets/5c864275-d0f2-455c-8353-8fc1ec444535">

Individual post pages in the reader have one as well:

<img width="796" alt="Screenshot 2024-08-22 at 9 26 12 AM" src="https://github.com/user-attachments/assets/53429095-f6bb-44a6-a0ed-450954b8e7db">

**Comment by mmtr** [comment]
> Here's what I propose:
>
> ![Image](https://github.com/user-attachments/assets/ed42e686-f496-466f-98b8-e8cd49e0d405)

Would it be possible to reconsider this? When experiencing it in real time, it looks a bit janky with the search and the categories list suddenly jumping to the bottom:


https://github.com/user-attachments/assets/7ce6f614-f3d7-4fbd-8a6e-e8ad52d8ee35

**Comment by nuriapenya** [comment]
Heya 👋🏽 

I think the `< Back` button is not the correct answer here. These sections work as filter, so the users do not "go back" to another level or page. It's a very confusing interaction.

If you don't want to change the mechanism of this page, then we need to make sure that the "Discover" tab is always visible and sticky, as Javier suggested above.

**Comment by lucasmendes-design** [comment]
+1

**Comment by davemart-in** [comment]
> I think the < Back button is not the correct answer here. These sections work as filter, so the users do not "go back" to another level or page. It's a very confusing interaction.

That's my bad. I was obviously in too much of a rush and didn't notice this. I'm sorry @javierarce! Thanks of moving this back to "Needs design".

@javierarce mind clarifying what your proposal would be?

**Comment by Addison-Stavlo** [comment]
> what your proposal would be?

If this is an issue to resolve, I say we would add a link in the same place as "browse all" (where it becomes "60 plugins").

Note when I click "browse all" the entire interface remains the same except that link and what is shown below it. If we wanted a link to go back to the last state, it could make sense right here as this feels to work like an expand/collapse toggle in a way:

![browse-all](https://github.com/user-attachments/assets/5666c72b-fc6b-4ecb-b63d-ac7bec57dddf)

My other thought: maybe this isn't an issue and we could just close this. The user can go back to the initial state by hitting "marketplace" in the sidebar again.
