### ISSUE TITLE
Plugins Marketplace: No filter between community and commercial plugins

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93584]
## Description

When comparing to the dotorg plugins directory, the Plugins Marketplace doesn't have a clear filter to display community and commercial plugins. See the dotorg plugins directory for reference:

![Image](https://github.com/user-attachments/assets/3882878a-7b22-4c56-970e-e4581de4aa7f)

**Comment by davemart-in** [comment]
I believe everything in the plugin marketplace is a commercial plugin. Closing this out.
