### ISSUE TITLE
Plugins Marketplace: The guides in the "Get started with plugins" section are outdated

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93587]
## Description

Currently, the guides in the "Get started with plugins" link to the defunct and outdated /go blog. The guides should link to updated or timeless material.

![Image](https://github.com/user-attachments/assets/f054b312-836f-4054-bc13-ee2986778122)

**Comment by mmtr** [comment]
Where is this "Get started with plugins" section?

**Comment by taipeicoder** [comment]
Sorry for not being clearer, here it is:

![Image](https://github.com/user-attachments/assets/aad755ac-704c-47e2-9f18-16488f6443ca)

**Comment by mmtr** [comment]
Thanks @taipeicoder!

I was wondering if we should remove this section, but 14.7% of the users who see one of these guides end up clicking on the activate plugin button ([funnel](https://mc.a8c.com/tracks/funnel/view.php?55014/2024-01-01/to/2024-08-16)), which seems like a decent conversion rate.

Maybe we can link to some of our support pages?

- What are WordPress plugins? > https://wordpress.com/support/plugins/
- How to install a WordPress plugin > https://wordpress.com/support/plugins/install-a-plugin/
- Find and choose the best plugins > https://wordpress.com/support/plugins/find-and-choose-plugins/

**Comment by davemart-in** [comment]
I like that suggestion @mmtr. Let's do that. Moving this to Ready for dev.
