### ISSUE TITLE
Plugins Marketplace: Consider removing the confetti animation after installing a plugin

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93593]
## Description

Currently, we display a Thank You page with a confetti animation. It feel a bit "too much", especially when installing multiple plugins.

**Comment by davemart-in** [comment]
I'd say let's just remove it.

**Comment by ntsekouras** [comment]
I noticed this too when testing and it felt too much..

I'm wondering why in calypso we don't have the `install` button at the plugins list (like core) and an extra click is required in order to install.
