### ISSUE TITLE
Preview & Customize: Improve the UX

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93595]
## Description

The Preview & Customize (Live Preview) experience feels overwhelming in the following ways:

1. Upon entering the Editor, the user sees the preview modal. Then when switching to the edit mode they see the preview notice and possibly the Welcome tour as well.

![Image](https://github.com/user-attachments/assets/9e4f068e-95de-4d94-9d4a-043c27817bc9)

![Image](https://github.com/user-attachments/assets/9ac4a123-52d8-4394-b245-d9b9a81b7b37)

2. After saving and activating the theme, it's unclear what's next and how to get back to the Theme Showcase. The preview notice is no longer available.

![Image](https://github.com/user-attachments/assets/dfcae197-5ecd-4ac5-a585-597b70125efe)

**Comment by davemart-in** [comment]
@taipeicoder can you please clarify what you'd hope to see as next steps? I'm wondering if this issue could be broken out as two separate issues? Thoughts?

**Comment by taipeicoder** [comment]
I've opened two issues and will be closing this one.

* https://github.com/Automattic/wp-calypso/issues/94095
* https://github.com/Automattic/wp-calypso/issues/94096
