### ISSUE TITLE
Partner Themes: On free sites, an annual theme subscription is added to the cart but the plan subscription is monthly

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93597]
## Description

Currently, when clicking the "Subscribe to activate" button, a theme subscription and a plan subscription are added to the checkout cart. The theme subscription is annual, but the plan subscription is monthly.

![Image](https://github.com/user-attachments/assets/6278049c-2ed4-4da0-9409-a6a669412d8b)

![Image](https://github.com/user-attachments/assets/19944865-6aa1-4fb8-bc5f-a8e044b5f618)

**Comment by mmtr** [comment]
We should fix this by adding a yearly plan, rather than decreasing the term of theme subscription to a monthly bill.
