### ISSUE TITLE
Install Plugin: Progress screen looks off-centre when transitioning from the upload screen

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93609]
## Description

The progress screen will look off-center when seen immediately after the plugin upload screen. It’s an optical illusion but still worth correcting. See recording for reference:

https://github.com/user-attachments/assets/b7e7beb5-6524-4ef9-88b5-2f233f9b934d

**Comment by javierarce** [comment]
I'm not sure if I understood you correctly. Do you mean we should consider the missing left sidebar when centering the progress information on the new screen?

**Comment by davemart-in** [comment]
@taipeicoder mind clarifying your intention here?

**Comment by taipeicoder** [comment]
@javierarce @davemart-in this issue was created from p9Jlb4-dr7-p2#comment-12797:

> The Stepper onboarding progress screen will look off-centre when seen immediately after the plugin upload screen. It’s an optical illusion but still worth correcting.

@ianstewart could you clarify further? From what I see the progress UI seems slightly off-center to the right, but would be good to confirm what the optional illusion consists of.

**Comment by ianstewart** [comment]
It might just be me but the transition to the stepper screen creates this effect where it feels like the progress bar is off-centre because of the "weight" of the black sidebar that disappeared. Priority is low. The only fix I could imagine would be "don't transition to stepper, stay on screen with a loading state."

**Comment by davemart-in** [comment]
I'm going to close this out for now. Happy to re-open if someone feels strongly about it and has a good solution in mind.
