### ISSUE TITLE
Install Plugin: No post-purchase confirmation

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93607]
## Description

After checkout completion, the user is redirected back to the Install Plugin page with no confirmation that their purchase was successful. This is the UI they see post-purchase:
![Image](https://github.com/user-attachments/assets/fdbe9eb0-ea76-406f-8c39-c38093fa6dca)

Which looks very similar to pre-purchase:
![Image](https://github.com/user-attachments/assets/e46139a3-d6d7-4230-8f5e-49b5e8174924)

**Comment by davemart-in** [comment]
Seems related to https://github.com/Automattic/dotcom-forge/issues/7727

**Comment by davemart-in** [comment]
To make progress on this, I propose that as a next step, we just add a success [notice](https://wpcalypso.wordpress.com/devdocs/design/notice), indicating that the purchase was successful. Perhaps something as simple as "Payment successful."

**Comment by eoigal** [comment]
@taipeicoder - what plugin did you see this with? I tried purchasing the Sensei plugin and I was redirected to a thank you page;
<img width="895" alt="Screenshot 2024-09-02 at 16 18 32" src="https://github.com/user-attachments/assets/befaac9a-b10f-429d-afb5-7a9e682dbb26">

**Comment by mmtr** [comment]
@eoigal you need to start the "upload plugin" flow on a simple free site. See p9Jlb4-dr7-p2#comment-12797

**Comment by Addison-Stavlo** [comment]
> what plugin did you see this with? I tried purchasing the Sensei plugin and I was redirected to a thank you page;
> you need to start the "upload plugin" flow on a simple free site.

So this isn't about purchasing a plugin, but purchasing a plan to allow uploading when on the upload page / and getting sent back to it?

> I propose that as a next step, we just add a success [notice](https://wpcalypso.wordpress.com/devdocs/design/notice),

makes sense to me!

**Comment by mmtr** [comment]
> So this isn't about purchasing a plugin, but purchasing a plan to allow uploading when on the upload page / and getting sent back to it?

Correct!

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/94195 should resolve.
