### ISSUE TITLE
Plugin Update Manager: Improve UI

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93611]
## Description

Plugin update manager text should be aligned to the left. Otherwise, it's difficult to read, off-brand.

![Image](https://github.com/user-attachments/assets/16992618-19fd-4826-b3a9-20c61b8d9649)

![Image](https://github.com/user-attachments/assets/f6c521c4-35a2-4cda-b2a3-283b0e319460)

**Comment by davemart-in** [comment]
Let's just make these changes.

**Comment by mmtr** [comment]
I think we just to replicate the alignment of the global view to the selected site view.

- Global view (`/plugins/scheduled-updates/`):

<img width="1195" alt="Screenshot 2024-08-19 at 14 43 57" src="https://github.com/user-attachments/assets/94822506-0e8e-45ac-abe7-7d55b21d9309">

- Selected site view (`/plugins/scheduled-updates/:site`):

<img width="1022" alt="Screenshot 2024-08-19 at 14 47 00" src="https://github.com/user-attachments/assets/dda48eae-85f2-4bf4-9599-9aa1c7dc50dc">
