### ISSUE TITLE
Posts List: Consider removing ads banner

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93614]
## Description

Ads inserted into the post list feels cheap. May create impression we’ll surface ads everywhere. Impression of bad iOS game. Do we have data about the performance of this banner?

![Image](https://github.com/user-attachments/assets/45a1d440-68ee-44fb-9eb7-b4d0ef8e1bfa)

**Comment by mmtr** [comment]
Since 2024-01-01, the banner has been displayed 560K times, clicked 11K times (2.0%), and drove 256 purchases (2.3%).

Funnel: 35633-pb

I think we can remove it.

**Comment by davemart-in** [comment]
@danielbachhuber Since this affects revenue, wanted to make sure it hits your radar.

**Comment by danielbachhuber** [comment]
@taipeicoder Thanks for flagging! I'd prefer to 1) document all of our upsells first, 2) understand their financial impact, 3) decide upon some heuristics for what's appropriate vs. what's not, and then make changes.

cc @ianstewart to make sure this one is on your list.

**Comment by ianstewart** [comment]
Noted. 👍

**Comment by davemart-in** [comment]
Moving this to deferred.

**Comment by taipeicoder** [comment]
Actually this is already done via https://github.com/Automattic/wp-calypso/pull/95737. Thanks for closing!

**Comment by Copons** [comment]
Oh nice reminder! I'll re-close it as completed instead as not planned. 👍
