### ISSUE TITLE
Typo in Connections Tab (Fediverse)

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#93656]
### Quick summary

There's a minor punctuation error on this public-facing settings page. Instead of "eg Mastodon" it should read "e.g., Mastodon".

### Steps to reproduce

On a Free, Personal, or Premium plan site:

1. Navigate to Tools → Marketing → Connections (or Hosting → Marketing → Connections in WP-Admin).
2. Under Fediverse, toggle on "enter the fediverse".
3. View this text:

> Anyone in the fediverse (eg Mastodon) can follow your site with this identifier:

### What you expected to happen

> Anyone in the fediverse (e.g., Mastodon) can follow your site with this identifier:

### What actually happened

> Anyone in the fediverse (eg Mastodon) can follow your site with this identifier:

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
This is what I see from my end: 

![Markup on 2024-08-19 at 08:01:28](https://github.com/user-attachments/assets/03c9387c-18b2-4d93-b2d9-fa50f522777a)

📌 ACTIONS
- Triaged
- Lowered priority
