### ISSUE TITLE
Reader Stream Refresh: Some posts with little to no text are not displaying as photo cards

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9366]
These should be displayed as photo cards:

https://wpcalypso.wordpress.com/read/feeds/55575582
![screenshot 2016-11-14 14 51 26](https://cloud.githubusercontent.com/assets/4924246/20286449/ab877b98-aa7b-11e6-84c7-b43dda6ce9cf.png)

https://wpcalypso.wordpress.com/read/feeds/12974569
![screenshot 2016-11-14 15 05 12](https://cloud.githubusercontent.com/assets/4924246/20286475/c0bb3554-aa7b-11e6-844d-e9b9930fcaf8.png)

**Comment by bluefuton** [comment]
In the first case (Dog vs Handbag), the canonical media width is 466px, which is just below the photo-only required width of 480px.

**Comment by bluefuton** [comment]
Same story in the second post, too - main image is 468px wide.

**Comment by jancavan** [comment]
If that's the case, then that's also why the second image isn't a photo card since it's only`468px`.

@fraying Should we consider making the required width less than 480px?

**Comment by fraying** [comment]
@jancavan Let's test it!

**Comment by bluefuton** [comment]
@jancavan you can experiment by changing the first value here:

https://github.com/Automattic/wp-calypso/blob/master/client/state/reader/posts/normalization-rules.js#L47

**Comment by raoulwegat** [comment]
@bluefuton is there a reason that photo only cards to have a minimum photo width?

**Comment by bluefuton** [comment]
@raoulwegat purely because smaller images don't look particularly fantastic when stretched out across the whole card (most desktop users are seeing the image at 800px wide).

Happy to tinker with the minimum, though!

**Comment by raoulwegat** [comment]
Seeing that desktop users are currently the most prevalent, and that using a cut off of 480px already sees a minimum image zoomed 66%, I don't see a problem with decreasing to 440px which will see a minimum sized image zoomed 82%.

If you factor in the future as desktop use slowly decreases, on narrower devices like portrait tablets with a 768px viewport there is no zooming as the image width is 368px, or a horizontal tablet where the image width is 688px would only zoom 51%.

Do we have a consensus on 440px minimum?

cc @bluefuton @fraying

**Comment by bluefuton** [comment]
@raoulwegat makes sense to me. I'll work up a quick PR to try it out!

**Comment by raoulwegat** [comment]
Closed in #10601
