### ISSUE TITLE
Reader doesn't preview portrait photos well

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#93672]
### Quick summary

The Reader has the tendency to cut people's heads when cropping images

### Steps to reproduce

1. Post a new post with a photo of a standing person, head and legs included
2. Check how it looks in the reader

### What you expected to happen

See the person's head

### What actually happened

Head and legs are cropped

<img width="616" alt="Screenshot 2024-08-19 at 15 48 35" src="https://github.com/user-attachments/assets/e3ea5b72-0295-49cc-8d6f-709a36ec99e1">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

The workaround is to never post portrait photos

### Platform (Simple and/or Atomic)

Simple

**Comment by dzver** [comment]
<img width="619" alt="Screenshot 2024-08-19 at 16 57 32" src="https://github.com/user-attachments/assets/8a3d00a4-c6dd-44cf-8649-01eabe5b3100">

I know this photo shows another instance of the same problem, but just highlighting that it is a problem with photos where the legs are already not part of the photo. This way of cropping highlights the chest area and removes the head, which is a bit unpleasant.

**Comment by xavier-lc** [comment]
Addressed on https://github.com/Automattic/wp-calypso/pull/93693
