### ISSUE TITLE
Subscribe button on websites has unexpected styling

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#93676]
### Quick summary

Some of the Subscribe buttons come with an unstyled menu, while others work fine

### Steps to reproduce

1. Visit https://pjtemple.com/ or https://knijnikrile.wordpress.com/ with a desktop browser
2. Scroll down, then a bit up to see the subscribe button at the left bottom corner of the browser
3. Click Subscribe

Observe:
<img width="1423" alt="Screenshot 2024-08-19 at 17 36 09" src="https://github.com/user-attachments/assets/4afd54c8-94a3-4d0d-b787-7f2f0cd5f6fa">

Expected:
<img width="327" alt="Screenshot 2024-08-19 at 17 36 48" src="https://github.com/user-attachments/assets/bb88c3fb-190b-4cb0-bd08-542103c3b21d">

### Browser

Google Chrome/Chromium

**Comment by agrullon95** [comment]
Resolved in D158929-code
