### ISSUE TITLE
Automated migrations: create function to activate Migrate Guru

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#93688]
This will be used from [this job](https://github.com/Automattic/wp-calypso/issues/93684), we can use as implementation base the `auto_migrate_guru_activate` function from this pastebin: 354b7-pb/#php

**Comment by valterlorran** [comment]
I started a diff to tackle this here: D162069-code

**Comment by valterlorran** [comment]
Closing this as we deployed D162069-code
