### ISSUE TITLE
Global /themes and /me - empty scrollbar on first load

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#93681]
If I load `*/plugins` or `*/me` directly (not visiting other calypso pages first) <s>on a mobile viewport</s>, I end up seeing an second scrollbar that is empty on the right edge of them:

<img width="450px" src="https://github.com/user-attachments/assets/42eb2ee0-c4f4-4234-be27-9169abd6bb43" />

<img width="310px" src="https://github.com/user-attachments/assets/9928e8d9-9f3e-4b5f-b541-bb7a58b3683c" /><img width="310px" src="https://github.com/user-attachments/assets/a71cec4a-ad11-456f-b2a1-efc0bb8de9f7" />

If I visit other calypso pages and come back (or visit them first), the problem is gone.

TO REPRO. go to either of these pages and reload the browser.

**Comment by davemart-in** [comment]
Yeah, for me it's like a split second reveal of a second scrollbar and then it goes away.  I suspect this is a thing where it's taking a split second  for the code that hides the parent overflow to load.

@Addison-Stavlo I just tested this on my iPhone (Safari) and it wasn't an issue. In which case, should we still try and fix this, or should we just make a note of it and close it?

**Comment by Addison-Stavlo** [comment]
> Yeah, for me it's like a split second reveal of a second scrollbar and then it goes away.

It sticks around for me, until i navigate to another page.

> I just tested this on my iPhone (Safari)

I cant get it to show up on android / chrome either.

> should we still try and fix this, or should we just make a note of it and close it?

Im actually noticing this happens at desktop viewports for me as well:

<img width="1092" alt="Screenshot 2024-08-19 at 3 29 59 PM" src="https://github.com/user-attachments/assets/beff010c-2087-4381-b00a-0e81e5c8d65a">

Although maybe not a high priority as it is not breaking and only observable if reloading on these pages directly.

**Comment by davemart-in** [comment]
Moving this to Ready for Dev to investigate.

**Comment by Copons** [comment]
I can't repro anymore, which is not surprising with all the changes that happened on the Global view. 🙂
