### ISSUE TITLE
Subscriptions management link incorrect in Jetpack Cloud

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#93694]
### Quick summary

As part of untangling, we moved the subscription management from WordPress.com to Jetpack Cloud. As part of that, we missed a link.

![IMG_0067](https://github.com/user-attachments/assets/fd025ab3-520b-4f4f-87b6-d3c5e61885c0)

### Steps to reproduce

1. Go to https://cloud.jetpack.com/subscribers/{BLOG_ID}
2. Click … for a paid subscriber
3. Click to remove
4. In modal, click “Manage paid subscribers”
5. See page not found route
6. Change “cloud.jetpack.com” in URL to “Wordpress.com”
7. Note that the management page shows up correctly now

### What you expected to happen

No errors

### What actually happened

Error

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by vykes-mac** [comment]
@ebinnion I was able to repro following your instructions. I looked at it and it seem like a simple enough fix. Should we change to a lower priority or I can go ahead with the fix?

**Comment by jartes** [comment]
📌 ACTIONS
- Triaged
- Lowered priority from `High` to `Normal`.

@vykes-mac If you have the fix, go ahead :)
