### ISSUE TITLE
Double images

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9371]
Some fullpost pages have double images. For example: https://wpcalypso.wordpress.com/read/feeds/114813/posts/1223737989

Any way to avoid this?

**Comment by blowery** [comment]
We already suppress featured images that also appear in the content. In this case, those are two different image URLs, so we don't have a way to suppress the double..

**Comment by blowery** [comment]
This might be a place where having AMP support could be useful. Maybe.

**Comment by fraying** [comment]
This is an RSS subscription, and the original post (http://gizmodo.com/report-apple-explores-the-idea-of-making-its-own-googl-1788975226) doesn't have double images, so where is the second one coming from?

**Comment by blowery** [comment]
Hrm, site name is odd on https://wpcalypso.wordpress.com/read/feeds/114813

**Comment by blowery** [comment]
the actual feed has the image doubled up

<img width="792" alt="gizmodo_-_powered_by_feedburner" src="https://cloud.githubusercontent.com/assets/14350/20289944/db020120-aaaa-11e6-86f6-2be8c8441359.png">

**Comment by blowery** [comment]
Feed was a dupe, merged it into https://wpcalypso.wordpress.com/read/feeds/19797

**Comment by blowery** [comment]
For this specific case, we need a specific fix. You'll find that in #9388
