### ISSUE TITLE
Theme's live demo buttons need better spacing

### ISSUE THREAD

**Issue by annezazuu** [Automattic/wp-calypso#9373]
1) Head to My Sites > Appearance
2) Select a theme > Open Live Demo
3) Look at the buttons :) 

Here's a video:

https://cloudup.com/cMzsVkyLeRG

The spacing seems off and the hovering results in odd pixels (dark blue?). 

Notes: using latest version of chrome, retina display

**Comment by folletto** [comment]
Screenshot (from the video) for quick reference:

![screen shot 2016-11-15 at 16 21 55](https://cloud.githubusercontent.com/assets/4389/20313702/ab1e13a4-ab4f-11e6-8942-39787ff78dc4.png)

**Comment by folletto** [comment]
I can't seem to be able to reproduce it on Chrome latest.

Question/guess to try to pinpoint it: are you maybe browsing at a smaller than 100% zoom level in Chrome?

**Comment by folletto** [comment]
I just noticed Chrome has a "zoom out" icon in the address bar and it's present in the video, so I'd bet it's the zoom. Closing, but for reference here are some different screenshot at different zoom levels:

![screen shot 2017-02-21 at 12 58 20](https://cloud.githubusercontent.com/assets/4389/23165802/ccd9831a-f835-11e6-9436-a2172ecb1e29.png)

![screen shot 2017-02-21 at 12 58 26](https://cloud.githubusercontent.com/assets/4389/23165803/cef0d874-f835-11e6-839a-c1c535689b60.png)

![screen shot 2017-02-21 at 12 58 31](https://cloud.githubusercontent.com/assets/4389/23165807/d1f4c97c-f835-11e6-8b3a-ec8740b22ddd.png)

![screen shot 2017-02-21 at 12 58 36](https://cloud.githubusercontent.com/assets/4389/23165813/d5b9003c-f835-11e6-8301-6fa9769c86dc.png)

![screen shot 2017-02-21 at 12 58 44](https://cloud.githubusercontent.com/assets/4389/23165819/d90c1332-f835-11e6-9490-2f153adfaea7.png)

![screen shot 2017-02-21 at 12 58 50](https://cloud.githubusercontent.com/assets/4389/23165820/dcdb0b94-f835-11e6-80fe-216f2be350cb.png)
