### ISSUE TITLE
"Status is All sites" is a confusing filter default

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#93751]
The following screenshots show the default sorting filter in the All Sites view.

![Image](https://github.com/user-attachments/assets/8115b918-ca1b-4845-89cb-3d4ae0cbb94a)

![Image](https://github.com/user-attachments/assets/e94f9091-5508-41e3-807c-46766f43565e)

### Issue

"Status is All sites" reads oddly. 

- Looks sort of like a sentence but "All sites" isn't a status.
- It has strange case. Is it sentence case? Title case? It looks like neither.

### Suggestion

A quick fix might be to drop "Status is" as a prefix. All sites with a highlight colour may be clear enough on it's own.

There might be other alternatives.

**Comment by davemart-in** [comment]
Thanks for the report! But this will be completely updated once [this PR](https://github.com/Automattic/wp-calypso/pull/93503) lands (which should be list week or next). As such, I'm closing this issue.
