### ISSUE TITLE
Mystery Man refuses to die

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9375]
Some users/sites are still showing the mystery man.

https://wpcalypso.wordpress.com/read/blogs/37571143
https://wpcalypso.wordpress.com/read/blogs/16563158

Can we do anything more to banish him more substantially? Magic ice wall perhaps?

**Comment by jancavan** [comment]
Probably related to this: https://github.com/Automattic/wp-calypso/issues/8076

https://wpcalypso.wordpress.com/read/feeds/1792967

**Comment by bluefuton** [comment]
No plans to fix this one.
