### ISSUE TITLE
Omit username when it's mostly the same as site name

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9376]
Currently we omit the username when it's exactly the same as the site name.

Could we also omit the username when it's 80% the same as the site name?

This is to avoid instances like these:

<img width="313" alt="screenshot 2016-11-14 16 55 46" src="https://cloud.githubusercontent.com/assets/24388/20291465/5fc3f464-aa9b-11e6-85e4-6dd44980b03e.png">
<img width="394" alt="screenshot 2016-11-14 16 54 46" src="https://cloud.githubusercontent.com/assets/24388/20291468/5fe71142-aa9b-11e6-8d02-feb437cdd57c.png">
<img width="481" alt="screenshot 2016-11-14 16 54 36" src="https://cloud.githubusercontent.com/assets/24388/20291466/5fdf4c00-aa9b-11e6-80eb-081d9696af11.png">

(Reported by @benhuberman )

**Comment by blowery** [comment]
We can easily strip all the spaces and punctuation and compare case-insensitively... That should catch most of these. 

Past that though, I'm not sure what 80% means really...

**Comment by fraying** [comment]
@blowery Stripping spaces and punctuation and comparing case-insensitively would be a great start.

**Comment by bluefuton** [comment]
We could do the string difference with something like Levenshtein distance (e.g. https://github.com/hiddentao/fast-levenshtein) but seems a bit heavy.

I'm all for the 'strip spaces+punctuation and lowercase' approach 👍

**Comment by blowery** [comment]
> We could do the string difference with something like Levenshtein distance (e.g. https://github.com/hiddentao/fast-levenshtein) but seems a bit heavy.

Explaining that in support just sounds ... fun. 😄 

"Why isn't my site name showing?"

"Well ma'am, ..."
