### ISSUE TITLE
Onboarding: add logged-in version with navigation

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#93761]
### What

When launching the new site flow from the Calypso sidebar or from `/sites`, aside from the browser back button, there is no way to navigate back to the original admin view.

https://github.com/user-attachments/assets/6bcd38fa-d76d-4bb6-b6f9-cd97ecd7ad47

Furthermore, there is no indication that a user is logged-in.

I think the onboarding should be, to some extent, integrated with the user's logged-in admin state.

### Why

Logged-in users arriving to the onboarding flow from an admin screen are disconnected from admin functionality.

They may have clicked on "Add new site" by mistake, or need to check which themes or domains they already have.

### How

At the very least it would be worth showing some type of admin bar for logged-in users.

I understand there might be reluctance to distract users once on the onboarding flow - a navigation bar with which they can access their account and admin home could be a minimum offering.

Example only:

![logged-in-signup](https://github.com/user-attachments/assets/670ec74c-945a-4aea-9a5f-4f9b15f1f419)

**Comment by richtabor** [comment]
> Okay, now I'm seeing this on the /sites page. Strange I couldn't before.

It's not consistent. I too did not see this recently, on the "Transfer Your Domains" view: https://connectingthedotsp2.wordpress.com/2024/09/06/product-review-transferring-a-domain/

**Comment by richtabor** [comment]
I think it's fine as-is, relying on the browser back button. As we re-think domains we'll revisit the navigation.
