### ISSUE TITLE
Design Picker: allow sorting by free status

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#93762]
### What

It would be helpful to folks who aren't ready to commit with their cash to have an option to filter all the free designs for display.

### Why

Themes that require upgrades are introducing the topic of payment very early on in the onboarding process.

I speculate that users who are more invested in picking a good design without a financial commitment do not need the cognitive overload of sifting through designs that require upgrade, especially where that upgrade's monetary value is not disclosed. 

Instead of "what a nice design", the thought of "how much" is planted.

I could be wrong. Perhaps it warrants an experiment.

### How

Adding a "Free" or some better copy to the categories list somewhere.

<img width="1298" alt="Screenshot 2024-08-21 at 3 12 18 PM" src="https://github.com/user-attachments/assets/fdda92c2-ae13-437e-abe5-0de6f04926dd">

<img width="1406" alt="Screenshot 2024-08-21 at 3 13 44 PM" src="https://github.com/user-attachments/assets/29d007f9-4174-45b5-81cd-d01fc28183df">

**Comment by annezazu** [comment]
Noting that this overlaps with https://github.com/Automattic/dotcom-feedback/issues/278 and it's already on the Connecting the Dots board. Can we consolidate?

**Comment by dsas** [comment]
> It would be helpful to folks who aren't ready to commit with their cash to have an option to filter all the free designs for display.

Even for people who have committed with their cash, we have options for them to commit more. The personal plan includes some themes, the premium plan includes some more and then partner themes require an additional subscription. Ideally "free" would be more like "no extra cash required"

**Comment by ramonjd** [comment]
> Noting that this overlaps with https://github.com/Automattic/dotcom-feedback/issues/278 and it's already on the Connecting the Dots board. Can we consolidate?

Thanks for linking that. I'll close this issue in favour of that one as it's more general. I'll also drop a note on it.

Cheers folks! 🍺
