### ISSUE TITLE
Post details view is missing the author and the subscribe button

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#93781]
### Quick summary

The post details view in the reader lacks important information that the readers may need, and the authors would like to be there.

### Steps to reproduce

1. Go to /read and click any post
2. No author and subscribe button, the site title is visible but at the bottom

### What you expected to happen

Here's how it looks in the Mobile Reader

![IMG_8980](https://github.com/user-attachments/assets/e17ea4ee-8367-48ef-9c4e-75c914b975ca)

Site, Author, and Subscribe are at the top, clearly visible (okay, a bit hidden but clearly there)

### What actually happened

<img width="1423" alt="Screenshot 2024-08-21 at 17 32 47" src="https://github.com/user-attachments/assets/bbec843f-ab58-45ce-9c44-a5d6f81959a5">

Who wrote that? How do I subscribe? There's a follow conversation button instead of subscribe, which is probably also worth removing to not confuse the audience from what's important.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Chrome, Desktop

**Comment by DustyReagan** [comment]
Closing this issue with this PR: https://github.com/Automattic/wp-calypso/pull/93816
