### ISSUE TITLE
Assembler: Should the icon for “Upgrade” be clickable or have some sort of interaction?

### ISSUE THREAD

**Issue by mikachan** [Automattic/wp-calypso#93792]
### What

I noticed there's a little Upgrade animated button/icon on the Select Styles page, but it's not clickable and doesn't seem to have a tooltip.

https://github.com/user-attachments/assets/9d38cf24-192c-43b8-ad90-8d600a5116a2

### Why

With the icon being animated it feels like it should be interactive or give the user more information.

**Comment by richtabor** [comment]
I say we just remove the star.

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
