### ISSUE TITLE
Assembler: Small bug with the screen resolution selection animation

### ISSUE THREAD

**Issue by mikachan** [Automattic/wp-calypso#93790]
### Quick summary

There is a small bug with the screen resolution selection animation, where it briefly goes wider than the third column on selection:

https://github.com/user-attachments/assets/ffea7cf1-fa9d-480f-9b03-b886b82b6d4a

### Steps to reproduce

1. Start at wordpress.com/start
2. Choose your domain later
3. Select a free plan
4. Select "Promote myself or business"
5. Select "Design your own"
6. Click through the screen resolution icons and notice how the preview window expands wider than the third column briefly

### What you expected to happen

The preview window should not overlap its container.

### What actually happened

The preview window overlaps its container.

### Impact

Most (> 50%)

### Available workarounds?

There is no user impact

**Comment by richtabor** [comment]
I'd hold off on this while the Assembler is sorted as a viable part of the flow or not.

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
