### ISSUE TITLE
Assembler: The first 12 or so style variations don't visually change the patterns much

### ISSUE THREAD

**Issue by mikachan** [Automattic/wp-calypso#93796]
### Quick summary

Selecting the first 12 or so styles didn’t change the colours much on the patterns I’d selected:

https://github.com/user-attachments/assets/540bb3b5-981d-479a-a8f2-c49c78e9681b

### Steps to reproduce

1. Start at wordpress.com/start
2. Choose your domain later
3. Select a free plan
4. Select "Promote myself or business"
5. Select "Design your own"
6. Select a couple of patterns
7. Click through to "Select styles" and try selecting the first few style variations

### What you expected to happen

I'd expect more to change visually as I select the different colour variations, or I'd expect the colour variation to be demoed in a slightly different way, maybe by zooming out the page.

### What actually happened

Not many colours changed in the visible elements in the preview.

### Impact

Most (> 50%)

### Available workarounds?

There is no user impact

**Comment by taipeicoder** [comment]
Closing this as we are sunsetting the Site Assembler.
