### ISSUE TITLE
Reader: occasionally clicking on the "New Posts" pill doesn't scroll you all the way to the top

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#938]
Raised by @blowery 

It's kind of a pain to repro, but I see it occasionally on Chrome / OSX.

Might be better to switch to a smooth scrolling scroll-into-view that does the scroll over a series of animation frames rather than one call to window.scrollTo(0,0).

**Comment by blowery** [comment]
Yay, this was fixed a while back, when we redid how scroll to top works.
