### ISSUE TITLE
Plugins Marketplace: inconsistent states in the 'Manage Sites' modal

### ISSUE THREAD

**Issue by javierarce** [Automattic/wp-calypso#93807]
### Quick summary

Clicking on the "Manage Sites" button in the plugin overview page displays a modal with different options depending on the state of the requests.

In this video, the modal presents 3 different states, even after the requests have finished:

https://github.com/user-attachments/assets/0e45b736-cd86-4672-81fe-b8dd18203b34

A possible solution would be to display a loading state in the plugin sidebar or inside the modal.

### Steps to reproduce

1. Go to /plugins
2. Click on a plugin that has been installed in multiple sites (eg: https://wordpress.com/plugins/woocommerce)
3. Wait until the banner on the right side displays the number of sites

Compare that modal with the one you get if you reload the page and immediately click the "Manage Sites" button.

### What you expected to happen

I'd expect the modal contained the same information, regardless of when I clicked the button.

### What actually happened

If I wait until all the data is loaded, the modal gives me more options to manage the plugin.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

The only workaround for the user is to wait until the requests in the plugin page have finished.

**Comment by davemart-in** [comment]
@javierarce Is there an existing pattern for showing an inline loader if we wanted to show one in the sidebar? Would we disable the button?

**Comment by javierarce** [comment]
I think the most common pattern we are using across the platform is skeleton loaders. We are using something like this in the admin to display the sidebar, but in that location the loading is much faster because it doesn't need to retrieve information about other sites.

https://github.com/user-attachments/assets/94b4e085-4593-46fc-85c4-73e0a5dc39bc

I've also seen the loading state of the button used as the loading state (I don't remember where, though). I think this solution could make more sense in our case because there's some information we have available when the user enters this page and the rest of the data takes a while to load:

https://github.com/user-attachments/assets/d0d1de02-9842-4590-acec-d280580d1ade

**Comment by davemart-in** [comment]
Let's proceed with the second one then (the button loader). Thanks @javierarce!

**Comment by epeicher** [comment]
Hi @javierarce, are you working on this? If not, I can try to tackle it
