### ISSUE TITLE
Hosting screen: respect the reset state for filters

### ISSUE THREAD

**Issue by oandregal** [Automattic/wp-calypso#93815]
### Quick summary

After the user has reset the filter states, changing the view sets "All sites" again.

### Steps to reproduce

I provide a video to reproduce:

https://github.com/user-attachments/assets/fcba84a7-7c1c-42ed-9ea8-9719c7b10b69

### What you expected to happen

The filters should be reset.

### What actually happened

The filters were set again.

### Impact

All

### Available workarounds?

There is no user impact

**Comment by davemart-in** [comment]
Thanks for reporting this @oandregal! This seems straightforward. I moved it to "Ready for Dev"

**Comment by Addison-Stavlo** [comment]
I think having "All sites" listed as the filter by default as by design here. cc @lucasmendes-design 

There is currently no indication on the status column header that it can be filtered (I think the original had a dropdown for choosing the filter setting, that design wanted to remove?), unlike other columns we show indications for sorting.

<img width="318" alt="Screenshot 2024-08-27 at 11 51 20 AM" src="https://github.com/user-attachments/assets/61fe9367-63fe-4f55-ba35-343e176a00fb">

Having the default filter of "all sites" set makes the filters easily discoverable. As this icon by itself is not something our users would easily identify as where to filter by status:

<img width="49" alt="Screenshot 2024-08-27 at 11 52 46 AM" src="https://github.com/user-attachments/assets/6e48849a-ac86-4d54-9ff8-15436cff7a3f">

I think if we want to remove the default filter for "All sites" that shows up, we should apply some other design (such as to the column header) to better indicate the availability of filtering.

**Comment by mmtr** [comment]
> I think having "All sites" listed as the filter by default is by design here

Can we then make these changes?

- If filters are in their default state, "Reset filters" and "Reset status" should be disabled/greyed out

<img width="452" alt="Screenshot 2024-09-04 at 13 13 08" src="https://github.com/user-attachments/assets/3b2c0221-82d5-4d78-b107-934a1e704ae6">

- If filters are in their default state, and a site is selected, the filters icon in the left sidebar shouldn't have any number: 

Expected | Wrong
--- | ---
<img width="379" alt="Screenshot 2024-09-04 at 13 17 21" src="https://github.com/user-attachments/assets/8a02e7d8-5eb6-4c42-97dc-84a8414277e4"> | <img width="390" alt="Screenshot 2024-09-04 at 13 17 12" src="https://github.com/user-attachments/assets/9e683e5b-03b3-4718-b182-6d1598834742">




- If filters are NOT in their default state, when clicking on "Reset filters", the label next to the filters icon should say "Status is All sites":


Expected | Wrong
--- | ---
<img width="451" alt="Screenshot 2024-09-04 at 13 15 02" src="https://github.com/user-attachments/assets/1dd2caf5-7ca6-4e83-81cb-f59a8579a915"> | <img width="487" alt="Screenshot 2024-09-04 at 13 15 09" src="https://github.com/user-attachments/assets/cdf6d4e6-42c9-4582-a93e-4026a19e9a20">

**Comment by oandregal** [comment]
Just noting that there's this PR to update the DataViews version in use https://github.com/Automattic/wp-calypso/pull/93503 It looks like it may be merged this afternoon or tomorrow morning. 🤞 

This is a bit unusual for me, but I'd perhaps suggest fixing this issue _after_ 93503 is merged if this is a big change. 93503 is a difficult PR that has been 3 weeks in the works, and it'd be good to avoid conflicts, complex rebases, etc.

**Comment by Addison-Stavlo** [comment]
> Can we then make these changes?

These are logical and seem like an option we could move forward with. 

I think the alternative approach would be:

* Make the filters reset as they should (default state = no filters, not 'all sites')
* We go back to having the dropdown/popover that appears from the "status" header. Whether it is the core one, or slightly different design we inject by core means.

Noting for context on that second note. In core DataViews, when a column allows filtering, there is/was a dropdown on the column header to select the filter you want for that column. Our designers didn't like the design for this and we sort of overrode it by hacking. The [visible "status" columns is not set up for filtering](https://github.com/Automattic/wp-calypso/blob/6fda2a9e57dba54f705487132944f4af0f57ee2b/client/hosting/sites/components/sites-dataviews/index.tsx#L150), and in place we added an [invisible status column that enables the filters](https://github.com/Automattic/wp-calypso/blob/6fda2a9e57dba54f705487132944f4af0f57ee2b/client/hosting/sites/components/sites-dataviews/index.tsx#L219) to show up in the other filtering UI. IIRC this was all done to avoid having the dropdown from the column header, and I think why we make filters more discoverable by the "all sites" default state. 

So the other option is to re-think that design conflict, and show the dropdown from the header as core does or in a similar way. In which case we could just make the default state no filters at all?


> I'd perhaps suggest fixing this issue after 93503 is merged 

👍  Thanks for mentioning that.

**Comment by Addison-Stavlo** [comment]
Given the dataViews refactor has re-added the popovers anyways:

<img width="318" alt="Screenshot 2024-09-05 at 10 54 44 AM" src="https://github.com/user-attachments/assets/590012a4-73d9-4272-b668-0ff0ec6d5d4c">

We may as well fix the hack hiding the filtering from here, and just default the filter to none.

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/94253 should resolve this.
