### ISSUE TITLE
Domain Registration: First special character (like accents) is removed instead of replaced in URL suggestions

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#93819]
### Quick summary

The domain search and registration process removes unsupported accents, but this only happens for the first occurrence.

When testing the Business Name Generator with a Portuguese sentence ([_eu vendo comida orgânica_ / I sell organic food](https://wordpress.com/business-name-generator/?query=eu+vendo+comida+org%C3%A2nica)), I get a lot of nice options but when I try to register, the examples with accents are not replaced with the actual letter. 

In this case, I went with _Alimentação Saudável_:

![Markup on 2024-08-22 at 11:44:10](https://github.com/user-attachments/assets/0eb34ef8-a616-4ea5-bad6-3b4bfce1f11a)

But this also happens on other domain registration areas such as:

* https://wordpress.com/start/domain/
* http://wordpress.com/domains

### Steps to reproduce

1. Start at https://wordpress.com/business-name-generator/, http://wordpress.com/domains, or https://wordpress.com/start/domain/
2. For the first option, find one that suits (a word with accents) and choose next. For the other two, type words with accents in the field. Example: _alimentação saudável_ (healthy food)
3. Check the options

### What you expected to happen

To have all characters replaced with their "regular" versions.

In our example, the domain alternatives for _alimentação saudável_ will be `alimentacaosaudavel`

### What actually happened

The first special character is removed from the domain suggestions and not replaced with anything. Other special characters are properly replaced.

* _alimentação saudável_ becomes `alimentaaosaudavel` (note the lack of `c` but how we replaced `á` with `a`)
* _orgânico delícia_ becomes `orgnicodelicia` (the `â` is removed instead of replaced with `a`)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by paulopmt1** [comment]
Fixed at https://github.com/Automattic/wp-calypso/pull/93834
