### ISSUE TITLE
Hosting dashboard: remove the initial select hack and replace with a DataViews solution

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#93827]
We load the /sites dashboard with a currently selected site. We previously used a hack to achieve this, but now we can use the updated DataViews package.

Discussion: p1724253058727239/1724191497.496709-slack-C06ELHR6L9J
Hack: https://github.com/Automattic/wp-calypso/blob/trunk/client/hosting/sites/hooks/use-initialize-dataviews-selected-item.ts

Proposed solution:

> This is actually already possible the DataViews component allows a "controlled" mode for the selection so you can pass a selection prop and onChangeSelection to receive selection changes.

**Comment by davemart-in** [comment]
@allilevine is this ready to pick up, or do we need to wait for the dataViews changes to ship?

**Comment by allilevine** [comment]
> [@allilevine](https://github.com/allilevine) is this ready to pick up, or do we need to wait for the dataViews changes to ship?

@davemart-in We need to wait for https://github.com/Automattic/wp-calypso/pull/93503 to ship.

**Comment by davemart-in** [comment]
Moving this to "Ready for dev"
