### ISSUE TITLE
Theme Showcase: Style variation incorrectly set

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#93826]
### Quick summary

It's possible to choose the default (free) style variation, make no global styles changes and still have global styles upgrade nudges everywhere.

h/t @JanaMW27 for the original report (p1724264534878539-slack-C048CUFRGFQ)

### Steps to reproduce

1. Be on a free site
2. Go to /themes
3. Click a style variation disc on the theme showcase grid
4. Click the default variation disc
5. Click into the theme
6. Activate it
7. Look at the front-end of the site, or the site editor

https://github.com/user-attachments/assets/15291397-6dfc-4257-918b-9b35ef5cfd7e

### What you expected to happen

I should see my site using the default style variation and no global styles upgrade nudges.

### What actually happened

I see global styles upgrades nudges in all the usual places.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

There are two workarounds:

 1. Ignore the misleading upgrade nudges
 2. Use the site editor, open the gs panel and reset global styles

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Presumably selecting a style variation disc, even if it's the default means that the style variation is copied into the global styles CPT and so the upgrade nudge thinks there's a need to ugprade. Probably somewhere we need to check whether the selected style variation slug is `default` and not do this.

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
The live site displays upgrade nudge despite the style being used is the default style

![Screenshot 2024-08-28 at 4 07 37 PM](https://github.com/user-attachments/assets/4c546d15-6102-44ca-ba1f-1cc37cd92bcc)

📌 ACTIONS
- Triaged

**Comment by arthur791004** [comment]
Closing it by https://github.com/Automattic/wp-calypso/pull/95542
