### ISSUE TITLE
"My Plan" Jetpack page links to wrong dashboard URL

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#9383]
#### Steps to reproduce
0. Your Jetpack site should have [WordPress in a subdirectory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory).
1. Starting at URL: https://wordpress.com/plans/my-plan/xxxx
2. Scroll down to the bottom of the page.
3. The link back to the dashboard doesn't include the WP directory (e.g. `mysite.com/wp-admin` instead of `mysite.com/wordpress/wp-admin`)

![screen shot 2016-11-15 at 15 15 08](https://cloud.githubusercontent.com/assets/426388/20308963/6c5a4916-ab46-11e6-9bd4-94d6e0d80175.png)

**Comment by tyxla** [comment]
I'm unable to reproduce this. @jeherve this might be an issue with the API returning a wrong URL for your Jetpack site?

**Comment by jeherve** [comment]
@tyxla What are your test site's `home` and `siteurl` values?

**Comment by tyxla** [comment]
Ah, I get it. I was testing with an installation in a subdirectory, but with equal `home` and `siteurl`. I'm able to reproduce with different ones. Thanks 👍

**Comment by jeherve** [comment]
Same problem with links from Settings > Analytics or Settings > SEO when trying to enable the Analytics or the SEO Tools module:

![screen shot 2017-01-31 at 22 17 14](https://cloud.githubusercontent.com/assets/426388/22484732/0ba5f15c-e803-11e6-9c13-8ace4bb45f23.png)

![screen shot 2017-01-31 at 22 17 36](https://cloud.githubusercontent.com/assets/426388/22484742/171142ee-e803-11e6-8d2c-c648b485d509.png)
