### ISSUE TITLE
Feature Request: make clicking the W a consistent experience, not connected to the onboarding stepper

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#93831]
### What

During onboarding, the usage of the browser back button and/or clicking the WordPress logo leads to inconsistent and frustrating experiences. At first before you complete the launchpad items, you are brought to a list of actions to take sometimes causing you to lose a post you just wrote, including an item to "write a post" even as you've written one. After completing the stepper, it then brings you to the site editor view (or the dashboard if you are in Posts). 

### Why

To ensure the W is seen as a consistent tool to help you navigate parts of your site.

### How

Make the W behave consistently, most likely by removing the attachment to the "stepper" process guiding folks through onboarding as the rest of the time someone uses the W it won't behave that way.

**Comment by richtabor** [comment]
> At first before you complete the stepper, you are brought to a list of actions to take sometimes causing you to lose a post you just wrote. 

Is this the launch pad?

**Comment by annezazu** [comment]
Nearly positive. For clarity, this is where I pulled that from:

![Screenshot 2024-08-26 at 2 54 39 PM](https://github.com/user-attachments/assets/aded3ca0-82eb-4686-8a8d-eb5362d5a808)

**Comment by richtabor** [comment]
I say we close this while the state of launchpad and onboarding stepper is in flux; revisit if necessary afterwards.
