### ISSUE TITLE
Jetpack Plan purchase: no instructions to set up AK /VP / PD

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#9384]
### Steps to reproduce.

1. Install Jetpack on a brand new site.
2. Install and activate [the Jetpack Beta plugin](http://jetpack.com/beta).
3. Update to the most recent version of Jetpack (4.4. Beta 4 in my test)
4. Go through the connection flow; no option to purchase a plan at any time during the flow.
5. Go to Jetpack > Dashboard > Plans, and click to get to the plans page in Calypso.
6. Purchase a monthly Professional plan.
7. Get to this generic post purchase page:

![screen shot 2016-11-15 at 15 17 07](https://cloud.githubusercontent.com/assets/426388/20309176/3c9eb3be-ab47-11e6-924b-83b002b46ef5.png)

8. Click on "Back to my site", then navigate again to the Plans page, then to "My Plan". There is a lot of info there, and links to dashboards that won't work for me since I didn't set up VP / PD yet. There is no link to start the autoconfig process anywhere, though.

Related: #9354

**Comment by ryelle** [comment]
@johnHackworth was this fixed on the API side? Just wondering if we can close this… Unless we want to add something to `getCheckoutCompleteRedirectPath` to handle null `receiptId`s?

**Comment by gravityrail** [comment]
This was "fixed" by increasing the BD API timeout inside WPCOM (as far as I know). This doesn't necessarily eliminate the problem - sounds like there's something really inefficient going on inside BD if we need more than 30 seconds to process a single purchase.

**Comment by lezama** [comment]
![image](https://user-images.githubusercontent.com/104869/27746908-758f6a32-5d9f-11e7-94b1-5fe6467d5878.png)
