### ISSUE TITLE
Migrate flow: Checkout close button does not work

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#93851]
### Quick summary

This issue was previously reported in pcmemI-3dx-p2#comment-2406.

### Steps to reproduce

1. Go to wordpress.com/move
2. Enter a website you want to migrate, say https://lexfridman.com/.
3. Create a new account, go through the flow, select the Business plan, and land on checkout.
4. Click on the `X` close button

Related:
Empty cart and click on "Go back":
<img width="1113" alt="Screenshot 2024-08-23 at 11 51 10 AM" src="https://github.com/user-attachments/assets/2305f09c-9d89-4ace-93fd-3327c0d28ef3">

### What you expected to happen

* The checkout page should close when clicking the button.
* The checkout page should navigate away when clicking "Go back"

### What actually happened

Nothing happened on clicking the button. Check pcmemI-3dx-p2#comment-2406 for a video recording.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by TimBroddin** [comment]
📌 REPRODUCTION RESULTS

Able to replicate, also while already logged in.

📌 FINDINGS/SCREENSHOTS/VIDEO
The close button does nothing:

![CleanShot 2024-08-23 at 08 25 58@2x](https://github.com/user-attachments/assets/84d6a7b4-e60a-4124-bba4-fab61d805b81)

The close button should act like a back button here, and go back to:

![CleanShot 2024-08-23 at 08 28 09@2x](https://github.com/user-attachments/assets/9f57e5ba-b609-41ef-907e-ca74094edde0)


📌 ACTIONS

Triaged

**Comment by TimBroddin** [comment]
(Noting my findings here):

- You visit wordpress.com/move & enter a URL
- A new tab opens with the flow
- When clicking close, [leaveCheckout](https://github.com/Automattic/wp-calypso/blob/ddd65060d9fd4c52b7f9eb9e951ff169aee59c5e/client/my-sites/checkout/src/lib/leave-checkout.ts#L15-L16) is called 
- The close button tries to send a message to opener (the landing page): https://github.com/Automattic/wp-calypso/blob/ddd65060d9fd4c52b7f9eb9e951ff169aee59c5e/client/my-sites/checkout/src/lib/leave-checkout.ts#L41-L43

**Comment by miksansegundo** [comment]
I tested https://github.com/Automattic/wp-calypso/pull/93853 and approved it because works fine. I vote for merging it.

**Comment by paulopmt1** [comment]
I also tested it, and it looks good. I'll merge as soon as Calypso tests are green.
