### ISSUE TITLE
Modify the job that checks credentials to read from QuickForget

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#93867]
We should modify the job introduced by this diff D158186-code to receive a QuickForget URL and stop receiving username and password.

That URL will hold a JSON with the following structure:
```json
{
   "username": [USERNAME]
   "password": [PASSWORD]
}
```

The job should use the function created in [this issue](https://github.com/Automattic/wp-calypso/issues/93866) to obtain the secret.

**Once we make this change, the jobs enqueued by the API will fail. It's not so bad since this isn't live yet, but we should deploy this once the work for [this other issue](https://github.com/Automattic/wp-calypso/issues/93869) is also ready for deploy.**

**Comment by andres-blanco** [comment]
Here's the diff for the storage update: D159636-code

**Comment by markbiek** [comment]
D159661-code
