### ISSUE TITLE
Jetpack Plugins: installing a network-only plugin doesn't work

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#939]
There are several issues with installing network-enabled-only plugins on network sites.

Currently we don't activate plugins when installing them on multi site, but it's a strange experience:

Issue 1: The install button for network-enabled-only plugins installs the plugin, but does not activate and does not provide that information
Issue 2: The install button appears on the main network site for plugins that have already been installed on the network
Steps to reproduce issue 1 & issue 2:
1. Start with a network that doesn't have W3 Total Cache installed
2. Go to to the plugin browser for a main site of a network
https://wordpress.com/plugins/browse/example.com
3. Find 'W3 Total Cache'
4. See and click the Install button:
![screen shot 2015-11-29 at 6 27 07 am](https://cloud.githubusercontent.com/assets/11487924/11456786/59aa326c-9662-11e5-9dbc-4771a4b2a298.png)
5. See that the installation went through successfully:
![screen shot 2015-11-29 at 6 27 14 am](https://cloud.githubusercontent.com/assets/11487924/11456790/9ce9191c-9662-11e5-9be8-a326a0f01ff9.png)
6. Go to the Plugins page for the main network site, but do not see W3 Total Cache in the list (as expected in general, but strange in this case)
7. Go to wp-admin > Plugins from network admin, and see that W3 Total Cache was correctly installed, but not activated:
![screen shot 2015-11-29 at 6 31 56 am](https://cloud.githubusercontent.com/assets/11487924/11456797/e7ea9850-9662-11e5-8991-2a3d96bc91c6.png)
7. Go back to the W3 Total Cache single site view for the main network site -
https://wordpress.com/plugins/w3-total-cache/example.com - you still see the install button (this is a bug):
![screen shot 2015-11-29 at 6 27 07 am](https://cloud.githubusercontent.com/assets/11487924/11456799/f2e43e5a-9662-11e5-99ee-0e703370c3d2.png)
8. But this time, the install fails (as expected):
![screen shot 2015-11-29 at 6 28 22 am](https://cloud.githubusercontent.com/assets/11487924/11456801/0173864c-9663-11e5-84cb-858a14e397e1.png)

The steps above indicate that it's unclear what's really happening on a main site for a network. When on WordPress.com - is the main site acting as the main site or the network admin? It would be great to make that clearer the way it is clear in wp-admin by the URL and interface:
ie. example.com/wp-admin/network/plugins.php vs example.com/wp-admin/plugins.php

Right now the .org API does not provide the data to see whether a plugin is network-enabled only. The API endpoints that would need to be updated are:
https://api.wordpress.org/plugins/info/1.1/?action=query_plugins and https://api.wordpress.org/plugins/info/1.0/w3-total-cache

**Comment by designsimply** [comment]
Tested and confirmed that a plugin installed on a Jetpack multisite parent site via https://wordpress.com/plugins/ does not show up in the plugin list on WordPress.com after it is installed and that if you click the Install button again it results in an error.

My testing steps:

1. Go to https://wordpress.com/plugins/browse/ click "Switch Site" and select a Jetpack network site that doesn't have W3 Total Cache installed
1. Search for "W3 Total Cache" and click on it
1. Click the Install button
1. Click Plugins in the left menu and look for "W3 Total Cache"
1. Go to https://wordpress.com/plugins/w3-total-cache/ click "Switch Site" and select the same site
1. Check to see if the Install button is active or not
1. Click the Install button

<strong>Result:</strong> after installing the plugin, I see a success notice that says the plugin was activated even though it was not:

> Successfully installed and activated W3 Total Cache on [sitename].

<img width="1280" alt="screen shot 2016-05-05 at thu may 5 9 13 35 am" src="https://cloud.githubusercontent.com/assets/1119271/15048461/e4085f68-12a6-11e6-8490-6fe284861368.png">
<sup>Seen at https://wordpress.com/plugins/w3-total-cache/disambiguously.com using Firefox 46.0.1 on Mac OS X 10.11.4</sup>

<strong>Result:</strong> the plugin does not appear in the list of plugins at https://wordpress.com/plugins/ for the site and the following error appears if you try to click the Install button again: 

> An error occurred while installing W3 Total Cache on [sitename].

<img width="1280" alt="screen shot 2016-05-05 at thu may 5 9 19 52 am" src="https://cloud.githubusercontent.com/assets/1119271/15048467/ecf61a8e-12a6-11e6-800c-36727399f02d.png">
<sup>Seen at https://wordpress.com/plugins/w3-total-cache/disambiguously.com using Firefox 46.0.1 on Mac OS X 10.11.4</sup>

I also noticed that the `wp-admin` > Plugins page lists the plugin as "Network Only":

<img width="1280" alt="screen shot 2016-05-05 at thu may 5 9 33 42 am" src="https://cloud.githubusercontent.com/assets/1119271/15048471/f43a4e0a-12a6-11e6-989e-9a8f86cb476f.png">
<sup>Seen at http://disambiguously.com/wp-admin/plugins.php using Firefox 46.0.1 on Mac OS X 10.11.4</sup>

And the `wp-admin` > My Sites > Network Admin > Plugins page has a link to "Network Activate":

<img width="1280" alt="screen shot 2016-05-05 at thu may 5 9 52 10 am" src="https://cloud.githubusercontent.com/assets/1119271/15048540/4c24d6b2-12a7-11e6-906a-55a32feb2bc0.png">
<sup>Seen at http://disambiguously.com/wp-admin/network/plugins.php using Firefox 46.0.1 on Mac OS X 10.11.4</sup>
