### ISSUE TITLE
Plans: The font size of the pricing is smaller

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93908]
## Description
See [context](https://wp.me/p58i-hYA/).

![Image](https://github.com/user-attachments/assets/ac183017-a721-4061-99b5-d8e3338cdad9)

![Image](https://github.com/user-attachments/assets/2117abbb-d765-4195-a6be-8cd3bfd40864)

**Comment by mmtr** [comment]
Seems this one is reproducible only if the currency is set to USD (this can be done in Store Admin):

EUR | USD
--- | ---
<img width="1486" alt="Screenshot 2024-08-26 at 15 41 25" src="https://github.com/user-attachments/assets/860fd741-c3f4-4e79-b852-3884cfd6c029"> | <img width="1548" alt="Screenshot 2024-08-26 at 15 43 23" src="https://github.com/user-attachments/assets/b6a61e39-fcda-4e17-ae18-564e88472876">

**Comment by taipeicoder** [comment]
The font size reduction is [intended](https://github.com/Automattic/wp-calypso/blob/trunk/packages/plans-grid-next/src/hooks/use-is-large-currency.ts#L67) to handle large display prices. We currently determine display prices to be large whenever the text string exceeds six characters.

The issue is that display prices uses `Intl.NumberFormat()` which account for the locale.

For `en-US`, running the following code:
```
const formatter = new Intl.NumberFormat( 'en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0, minimumFractionDigits: 0 } );
console.log(formatter.formatToParts(300));

// Output
▼ (2) [{...}, {...}]
  ▶ 0: (2) {type: "currency", value: "$"}
  ▶ 1: (2) {type: "integer", value: "300"}
  ▶ [[Prototype]]: []
``` 

However, running the same code for `es` results in:
```
const formatter = new Intl.NumberFormat( 'en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0, minimumFractionDigits: 0 } );
console.log(formatter.formatToParts(300));

// Output
▼ (3) [{...}, {...}, {...}]
  ▶ 0: (2) {type: "integer", value: "300"}
  ▶ 1: (2) {type: "literal", value: " "}
  ▶ 2: (2) {type: "currency", value: "US$"}
  ▶ [[Prototype]]:[]
``` 

This additional whitespace makes the display price exceed the threshold, making it "large".
