### ISSUE TITLE
Blog Courses: The i18n banner is vertically misaligned

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93906]
## Description

See [context](https://wp.me/p58i-hYA/).

![Image](https://github.com/user-attachments/assets/57301473-e6c8-451b-aaca-1f1cb3f9925c)

**Comment by mmtr** [comment]
Actually, it's not misaligned, but the nav header has a black background that overlaps the notice:

<img width="1257" alt="Screenshot 2024-08-26 at 15 49 16" src="https://github.com/user-attachments/assets/fa3be051-3bca-41be-ace5-8b5cbe9b1164">
