### ISSUE TITLE
Blog Courses: Improve post-onboarding discoverability

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93905]
## Description
See [context](https://wp.me/p58i-hYA/).

Currently, the Blog Courses screen is available via the Blog intent screen.

![Image](https://github.com/user-attachments/assets/5c28ec51-839e-4fe6-945a-dcee37bd30f1)

However, once the user completes the onboarding they cannot find their way back to the Blog Courses screen again. Consider linking users to these guides from the Help Center.

**Comment by mmtr** [comment]
FWIW, I can find a link to this tutorial in My Home:

<img width="1262" alt="Screenshot 2024-08-26 at 15 51 57" src="https://github.com/user-attachments/assets/82150c87-b8da-4a94-a342-770813528542">

**Comment by davemart-in** [comment]
Closing this out since it looks like there is a link already post signup. Happy to reopen it though.
