### ISSUE TITLE
Welcome Tour: When displayed, the left/right arrows key don't work in the Editor

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93904]
## Description
See [context](https://wp.me/p58i-hYA/). Jump to 20:00 to see the issue.

When the Welcome Tour is displayed, it hijacks the left/right arrows key so it doesn't work on the Editor.

https://github.com/user-attachments/assets/e2751398-fe37-461a-9837-03d3f3c2bf63

**Comment by eoigal** [comment]
Having trouble with workflow, going to pass this over to someone with more experience with jetpack mu plugin changes.
