### ISSUE TITLE
Post Editor: Improve Welcome Tour discoverability after it's been dismissed

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93902]
## Description

See [context](https://wp.me/p58i-hYA/). Jump to 22:00 to see the issue.

When users accidentally dismiss the Welcome Tour either via Skip or the Close button, it's hard to access it again.

**Comment by mmtr** [comment]
> it's hard to access it again.

This is possible via Options (aka three dots or ellipsis) > Welcome Guide:

<img width="297" alt="Screenshot 2024-08-26 at 16 21 01" src="https://github.com/user-attachments/assets/afff18d9-0a89-43b9-8556-4ca6a10e5604">

Not sure if we can do improve the discoverability here. If we only want to prevent accidental dismisses, maybe we can add a notice after the tour is being dismissed, and show an "Undo" action.

**Comment by davemart-in** [comment]
Going to close this out. It's possible, but not obvious, which I think is fine.
