### ISSUE TITLE
Design Picker: The theme preview displays content from the demo site but Launchpad displays content from user site

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93900]
## Description

See [context](https://wp.me/p58i-hYA/).

https://github.com/user-attachments/assets/bd3c21fa-db4b-4b0c-8b4f-97c6d9fd9192

**Comment by davemart-in** [comment]
@ianstewart I was not on the call, but I sort of feel like this is expected. Thoughts?

**Comment by ianstewart** [comment]
iirc it was unexpected in context. We had got into a flow, I think Write flow, where we wrote a post and published it, and _then_ saw the design picker where the post we published was nowhere to be seen. I don't think steps to reproduce are captured in the clip above.

**Comment by davemart-in** [comment]
This feels low priority to me. I'm going to close this out, but I'm happy for anyone to open it back up if they feel strongly about it.
