### ISSUE TITLE
i18n: Spanish translation issues in the onboarding

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93914]
## Description

See [context](https://wp.me/p58i-hYA/).

Plans screen: "Desbloquea un completo pack de functiones" is odd.
![Image](https://github.com/user-attachments/assets/6a4c8e01-ac21-4200-9d75-22db830303fe)

Goals screen: "Dejanos crear tu sitio en 4 dias" is odd.

![Image](https://github.com/user-attachments/assets/0c2fa679-e831-4901-a27e-9e93aa02127e)

Blogger intent screen: "Escribe tu primera entrada", and "Echa un vistado a video sobre blogs" are odd.

![Image](https://github.com/user-attachments/assets/43936889-8872-4682-811a-155e114bbdb4)

**Comment by mmtr** [comment]
@Automattic/i18n do we have any process to improve existing translations?

**Comment by yuliyan** [comment]
> @Automattic/i18n do we have any process to improve existing translations?

@mmtr, We'd usually reach out to our i18n reviewers, or for Spanish specifically we could also ask the folks from the Dotcom Spain Growth team.

If you feel comfortable, you could also fix [the translations directly in GlotPress](https://translate.wordpress.com/projects/wpcom/es/default).

Please, let me know if any of these options sound good to you and which one you'd like to proceed with, so I can assist you further.

**Comment by sdnunca** [comment]
@mmtr The translations are all available in [GlotPress](https://translate.wordpress.com/projects/wpcom/es/default?filters%5Bterm%5D=Desbloquea+un+completo+pack+de+funciones.) and can be edited by any a11n. 

Once the translations have been updated, please ping us in #i18n so we can handle translation deployment.

If you keep running into similar translation quality issues, please ping us so we can raise the problem with the vendor.

**Comment by mmtr** [comment]
Thanks @yuliyan. Went ahead and updated the translations myself:

- "Desbloquea un completo pack de funciones" > "Accede a un potente paquete de funcionalidades"
- "Echa un vistazo a vídeos sobre blogs" > "Ve nuestros vídeos sobre blogs"

There are a few that don't look bad to me, so @JanaMW27 I wonder if you can provide more context about why you found them weird?

- "Déjanos crear tu sitio en 4 días" is the right translation for ["Let us build your site in 4 days"](https://github.com/Automattic/wp-calypso/blob/99333d0be4f6a89ff78127d821ede65dde4096e5/client/landing/stepper/declarative-flow/internals/steps-repository/goals/goals.tsx#L36).
- "Escribe tu primera entrada" also looks great as a translation of ["Draft your first post"](https://github.com/Automattic/wp-calypso/blob/99333d0be4f6a89ff78127d821ede65dde4096e5/client/landing/stepper/declarative-flow/internals/steps-repository/blogger-starting-point/starting-points.tsx#L10). [Entrada is the right term in Spanish for Post](https://wordpress.com/es/support/entradas/).

**Comment by taipeicoder** [comment]
Any ideas for improvements @JanaMW27? Thanks!

**Comment by JanaMW27** [comment]
I agree with @mmtr recommendations. BUT I would add.

Déjanos crear tu sitio en 4 días" is the right translation for -> Creamos tu página web en 4 días

The entrada one has to stay. IMO, "entrada" is a weird term, and Post is widely accepted but is not yet officially accepted.

**Comment by mmtr** [comment]
Thanks @JanaMW27!

> Creamos tu página web en 4 días

Ended up using a slightly different translation: "Creamos tu sitio web en 4 días". The reasoning is that "página" (page) can be confused with [WordPress pages](https://wordpress.com/support/pages/).

Feel free to re-open this issue if you feel there is another translation that needs amending.
