### ISSUE TITLE
LOHP: Missing translations

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93913]
## Description
See p58i-hYA-p2.

The "Please fill out this field" text is not translated:

![Image](https://github.com/user-attachments/assets/8f6036c3-5ec3-48ce-a8ba-54dd729e9efd)

**Comment by mmtr** [comment]
> Text in images.

I guess one idea is to build different images for different languages and add a suffix to the filename so we can load them dynamically (e.g. `image_es.png`, `image_fr.png`, etc). If an image for a given language has not been built, we can default to the English one (e.g. `image.png`).

@Automattic/dotcom-design Can you provide alternative versions of the hero image used in the WP.com LOHP (https://wpcom.files.wordpress.com/2024/06/lohp-i3-hero-2x.png) for other languages? Ideally for all mag16 languages.

**Comment by javierarce** [comment]
> Text in images

What if we used SVG images there instead of PNG files? Perhaps we could even translate the strings automatically.

> Domain suggestions

The domains we use in many landing pages come from this list https://fieldguide.automattic.com/example-domains-to-use and belong to us. I don't think it would be practical (both economically and in terms of management) to register domains for every locale, but perhaps we could register some in the most widely used languages.

**Comment by mmtr** [comment]
> What if we used SVG images there instead of PNG files? 

That would be great!

**Comment by davemart-in** [comment]
Let's just be mindful of file sizes. I could be wrong, but my guess is that PNG, if converted to an SVG would be MASSIVE compared to the PNG. 

I don't mean this to come across as arrogant, but I think it's fine to have some images with text in one language or urls that are not localized. This feels like a potentially massive rabbit hole (meaning we could spend a great deal of time here) with quickly diminishing returns.

My vote would be to add translations for "Please fill out this field" and close the rest of these out as won't fix.

**Comment by dsas** [comment]
> The "Please fill out this field" text is not translated

That's the browser UI not ours, it will use the computers system language not the language of the webpage. It'll display in Spanish if you change your computer settings to Spanish. I think this happens throughout Calypso (and indeed basically every site), I don't think we want to reimplement browser field validation. 

I'll close this ticket but please reopen if I got any of that wrong.

**Comment by mmtr** [comment]
> That's the browser UI not ours, it will use the computers system language not the language of the webpage.

Looks like a browser issue then! I'd expect it to use the browser language as defined here:

<img width="711" alt="Screenshot 2024-09-12 at 16 27 07" src="https://github.com/user-attachments/assets/1c232f50-a3e5-4313-b652-35f467fab998">

But apparently it ignores that and uses my computer language.
