### ISSUE TITLE
Broken badge and text in migration flow in mobile

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#93927]
### Quick summary

When going through the migration flow in the mobile view, the text and the badge in the "Migrate Site" button looks broken
<img width="654" alt="Screenshot 2024-08-27 at 1 40 12 AM" src="https://github.com/user-attachments/assets/4429832e-f264-4c2e-bb06-99f94fa3727b">

### Steps to reproduce

1. Make sure your display size is set to a mobile size (tested with iPhone ** Pro Max devices)
2. Start at `wordpress.com/start`
3. Keep going through the steps in the flow. When asked for goals, select "Import existing content or website"
4. Wait till you reach the step in the screenshot attached above

### What you expected to happen

Everything to look unbroken

### What actually happened

The button looks a bit broken

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by fditrapani** [comment]
Looks great! thanks for taking care of this @Imran92!
