### ISSUE TITLE
Notifications UI breaks with a post having a preformatted block

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#93937]
### Steps to reproduce

I received a notification for post that has a preformatted block. The UI looks broken. Check the recording at 35763-pb.

### What you expected to happen

The notification should not overflow.

### What actually happened

Overflow error in the UI.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by miksansegundo** [comment]
I have reproduced it and going to prepare a fix.

<img width="435" alt="Screenshot 2567-08-27 at 16 30 07" src="https://github.com/user-attachments/assets/df734de6-19f8-4728-ace4-fc5008bf3c83">

**Comment by miksansegundo** [comment]
While the fix is deployed, we can expect a 24 hours delay to see the issue resolved due to the cache.
