### ISSUE TITLE
Make all themes either free or requiring at least a personal plan

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#93930]
It's confusing that some themes require a premium plan, while others require a personal plan. I'm not confident in the logic associated with what themes are set to what tier. 

Instead of connecting themes to different tiers of plans, what if instead you had access to all our themes if you're a paying customer? It's confusing having a theme determine a plan, rather than functionality I want on my site determining a plan (i.e. eCommerce equals the Commerce plan).

**Comment by Copons** [comment]
cc @ianstewart
