### ISSUE TITLE
Remove style variation badges from the theme card

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#93931]
As an alternate to https://github.com/Automattic/wp-calypso/issues/93799 and a resolution to many noticeable quirks with style variations displaying on the showcase grid views, I propose we simply remove these style variation badges.

### Requirements 

- [ ] Remove the style variation badges from theme cards.
- [ ] Position the `theme-tier-badge` to the right of the title, where the style variation badges were.

### Visual 

![Image](https://github.com/user-attachments/assets/bbba863d-b7b4-4d85-807b-d8dbb1e0514e)

**Comment by fditrapani** [comment]
Related to this, I shared an update to the theme cards here: https://github.com/Automattic/wp-calypso/issues/95471

**Comment by arthur791004** [comment]
Looks like we should remove the style variation badges on the Theme Showcase as well, right?
