### ISSUE TITLE
Notification: "Getting started video" does not link to videos

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#93955]
### Steps to reproduce

1. Create a new free plan account from wordpress.com/start
2. Check your first notification.
3. Click on the link for "getting started video"

### What you expected to happen

I expected it to take me to video tutorials.

### What actually happened

It links to https://wordpress.com/support/video-tutorials/ which in turn redirects to https://wordpress.com/support/. The link is misleading if it doesn't take to video tutorials. However, it would be better if we can completely remove any mention of video tutorials. From the discussions in p58i-hK7-p2#comment-63750, our video tutorials are outdated and are probably more confusing than helpful. So I recommend changing the second point to "2. Join our free live [webinars](https://wordpress.com/webinars/)."

<img width="1036" alt="Screenshot 2024-08-27 at 7 09 05 PM" src="https://github.com/user-attachments/assets/0d009a5b-a5e6-41da-bb9c-932fec40dbc6">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by paulopmt1** [comment]
We updated it here: D159670-code
**Note**: Non-EN languages will take up to 2 weeks to see the changes.

How it looks now:

<img width="884" alt="image" src="https://github.com/user-attachments/assets/8f00d2a9-6bac-44c3-8b6e-2a12d905d74c">


Can you please double-test it so we can close this issue @niranjan-uma-shankar?

**Comment by niranjan-uma-shankar** [comment]
Thanks for quickly fixing it @paulopmt1 ! I tested and it works well.
