### ISSUE TITLE
Add Skincues theme

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#93968]
Add Skincues theme from https://woocommerce.com/products/skincues/

**Comment by epeicher** [comment]
Soft launched as part of https://wpcom.trac.automattic.com/changeset/305994

**Comment by epeicher** [comment]
Soft launched as part of r305994-wpcom

**Comment by epeicher** [comment]
Launched as part of D163241-code by removing it from the soft launch list

**Comment by epeicher** [comment]
Diff deployed. Theme launched as part of r306001-wpcom

**Comment by epeicher** [comment]
Announcement here p1728319671333409-slack-CB0B2G43X
