### ISSUE TITLE
UI: Implement i3 design

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#94003]
We should implement the changes detailed in this post to the UI: p9Jlb4-dPf-p2. This changes include:
* Small wording fixes: `WordPress.com Admin credentials` > `WordPress.com Admin login`
* Replace the Notes section by a collapsable `Special instructions` section which allows us to add extra help
<img width="459" alt="image" src="https://github.com/user-attachments/assets/a516e0ac-aae7-42f1-9f27-1c2cedf8260b">

This issue probably will be tackled by more than one PR.

Figma reference: F8foKv974Gc5dTHSh0i0Wo-fi-329_5339

**Comment by daledupreez** [comment]
Two specific thoughts:
* Where possible, we should make the wording changes progressive/conditional on translations being available. That way we can keep the existing translated terms until we have translations available.
* We should probably add a Tracks event to the _Special instructions_ toggle so we know how often users are (not) expanding the section.
* We may want to add some sort of Tracks event for the form submission that identifies what fields were (not) included. It may be enough to have a `type` field for `backup|credentials` and a `has_special_instructions` field that's set to `true` when those are included.
