### ISSUE TITLE
"Design your own" theme option not showing

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#94004]
### Quick summary

Under Appearance > Themes, the option is not showing for the user. this should show as documented in https://wordpress.com/support/themes/design-your-own-theme/. Direct links don't work either.

<img width="970" alt="Screenshot 2024-08-28 at 15 55 18" src="https://github.com/user-attachments/assets/11ed8851-f5f2-440b-a109-1f8033016199">
<img width="957" alt="Screenshot 2024-08-28 at 15 55 31" src="https://github.com/user-attachments/assets/a6a2e8f9-798c-4e3c-b53d-3e91cd87da7f">

### Steps taken to troubleshoot
- Searched for open bug reports, but nothing shows.
- No Blog RC stickers that could be controlling this.
- This is happening on both sites (both simple sites) on the user's account.
- Both links below don't work:
 - https://wordpress.com/setup/with-theme-assembler/pattern-assembler?ref=calypshowcase&siteSlug=DOMAIN&screen=main&header_pattern_id=15892&footer_pattern_id=15364&screen_parameter=intro
 - https://wordpress.com/setup/site-setup/goals?siteSlug=DOMAIN
- Cannot replicate on test sites.
- Changing their language in calypso to English to see if it changes anything (in French now), but nothing happened.

### Steps to reproduce

1. Start at My Site > Appearance > Themes
2. Look for "Design your own" button on top right corner alongside "Install new theme"

### What you expected to happen

Option to be available

### What actually happened

Option not shown:
<img width="961" alt="Screenshot 2024-08-28 at 16 26 33" src="https://github.com/user-attachments/assets/bab68ac7-ac59-4ec7-99b6-508f6877eaad">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

User reports:
8647929-zd-a8c
8660733-zd-a8c

**Comment by davipontesblog** [comment]
More reports coming in:
8649897-zd-a8c

**Comment by DustyReagan** [comment]
The missing button appears to be due to an experiment: p1724877122570549-slack-C029GN3KD

**Comment by retnonindya** [comment]
I'm closing this issue since the option for Assembler flow not showing is expected due to an A/B experiment:
pbxlJb-68Y-p2

**Comment by davipontesblog** [comment]
I replied to these customers recommending the following:

> Hi there, https://wordpress.com/patterns will allow you to use the "Design my own" option to create your website. You can pick and choose the sections you want to use, like a Header, or a "Call to action" banner, or use the full site creator as well to design your own theme. I hope this helps!
