### ISSUE TITLE
The theme activation modal has the wrong colors

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94015]
## Description

See pbxlJb-6dR-p2, 17:18.

Currently, the theme activation modal has a hard-coded blue color.
![Image](https://github.com/user-attachments/assets/305dad74-f948-41c1-9171-3ba9a601188a)

It should use the color scheme accent color.
![Image](https://github.com/user-attachments/assets/dd4c7c23-870a-4b56-952b-58b0621f7955)

**Comment by Aurorum** [comment]
PR for this in #94556. :)
