### ISSUE TITLE
Help center links are not working on migration flows

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#94027]
### Quick summary

Help center links are not working on the checkout page. 

### Steps to reproduce

1. Start any migration flow  (/setup/migration,  /setup/site-migration, /setup/hosted-site-migration)
2. Follow all steps until you reach the checkout step 
3. Try to click on the links marked in red. 

![screenshot-2024-08-28-at-11 04 39e280afam](https://github.com/user-attachments/assets/4e2d26ca-0d60-4395-bc37-1d858050c169)

### What you expected to happen

The Help Center should be available. 

<img width="1301" alt="image" src="https://github.com/user-attachments/assets/e84c1c79-75df-4223-8776-8535d4b2c726">

### What actually happened

Nothing is happening

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by DustyReagan** [comment]
I can replicate the issue in production, and high priority seems appropriate. I'm marking this as "triaged."

**Comment by renancarvalho** [comment]
Fixed [here](https://github.com/Automattic/wp-calypso/pull/94141)
