### ISSUE TITLE
Main Followed Page: Scoot cards up 20px

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9403]
On the main followed page, there's ~20px too much whitespace at the top.

So this:

![before](https://cloud.githubusercontent.com/assets/24388/20328526/1f637716-ab48-11e6-9a6d-22fa9b821918.png)

Should be more like this:

![after](https://cloud.githubusercontent.com/assets/24388/20328530/22635012-ab48-11e6-8f1e-61a8ff782709.png)

cc @jancavan

**Comment by fraying** [comment]
Note also that at the smallest breakpoint, the content also needs to move up. Hopefully this is a two birds one stone thing.

Before:
![before](https://cloud.githubusercontent.com/assets/24388/20361091/2589c700-abeb-11e6-82e4-d6d61a68bc06.png)

After:
![after](https://cloud.githubusercontent.com/assets/24388/20361098/292f0406-abeb-11e6-8e2f-72518c9e3250.png)

**Comment by bluefuton** [comment]
@fraying just to confirm - is this required just on the Following stream, or on all streams without a stream header (e.g. My Likes)?

**Comment by jancavan** [comment]
@bluefuton I applied it to My Likes too and others, but there are streams that have the header cake which doesn't need to be moved up.

**Comment by fraying** [comment]
👍
