### ISSUE TITLE
Blue OAuth screen in calypso

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wp-calypso#94047]
### Issue description

Source: p1722972160655609-slack-C01SFMVEYAK

When logged-out from WooCommerce.com, certain OAuth login link will show non-designed screen OAuth screen, while it's supposed to show [this screen](https://github.com/user-attachments/assets/f90ca9c5-0f9e-44b5-bdef-8bc3eeb57bc2).

![Image](https://github.com/user-attachments/assets/7a8fdcca-51ad-49f6-bfe9-4345c4086732)

#### To reproduce

1. Go to https://woocommerce.com and log out
2. Ensure you're logged into https://wordpress.com
1. Open [this link](https://wordpress.com/start/wpcc/oauth2-user?oauth2_client_id=50916&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3D56b5c2e903dbcb79be48bc6394f24b05b7b245cd8cd222ac8ea5f4b5e5c033fa%26redirect_uri%3Dhttps%253A%252F%252Fwoocommerce.com%252Fwc-api%252Fwpcom-signin%253Fnext%253D%25252Fhosting-solutions%25252F%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26from-calypso%3D1&woo-passwordless=yes)
2. Observe blue screen

### Acceptance criteria

1. OAuth login from WooCommerce.com should either show [this screen](https://github.com/user-attachments/assets/f90ca9c5-0f9e-44b5-bdef-8bc3eeb57bc2)

**Comment by chihsuan** [comment]
Closing by https://github.com/Automattic/wp-calypso/pull/95353
