### ISSUE TITLE
People: usernames with dots can't be edited

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#9405]
On Jetpack sites user can have a dot in their username can't be edited.

#### What I expected
To be able to edit a user with a dot in the name. 
by visiting http://calypso.localhost:3000/people/edit/bo.b/example.com

#### What happened instead
Instead I got redirected to 
http://calypso.localhost:3000/people/team

#### Browser / OS version
Every browser. 

#### Context / Source
#manual-testing

I think this is related to how getSiteFragment method works.

**Comment by tyxla** [comment]
I'm no longer able to reproduce this one. It appears it has been fixed in #9445, but can you please confirm that before we close this one @enejb?

**Comment by tyxla** [comment]
❤️ 

Tested again, this has already been fixed. Closing.
