### ISSUE TITLE
Gallery Card: Add space between images

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9406]
After a suggestion from @benhuberman, I'd like to recommend this change: add 1px of space between images in the gallery card.

So this:

![before](https://cloud.githubusercontent.com/assets/24388/20329409/d44ba640-ab4c-11e6-8870-b8b50e00bd56.png)

Would be this:

![after](https://cloud.githubusercontent.com/assets/24388/20329417/d931ccf2-ab4c-11e6-96dd-6788fc2e10c0.png)

The idea is to separate out the images a bit more so they don't all run together when they look very similar. Thoughts, @jancavan?

**Comment by jancavan** [comment]
I think this looks better after trying it out quickly in inspect. I'll make the change.
