### ISSUE TITLE
Preserve Privacy Settings on Production when Syncing Staging to Production

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#94077]
### What

Privacy Settings should be preserved on Production when syncing the Staging database to Production. 

### Why

When syncing the Staging database to Production, Privacy Settings are overwritten due to not offering any selective database sync and how this option is stored. The following change purposefully sets `blog_public` to `0` in `wp_options` on Staging sites: https://github.com/Automattic/dotcom-forge/issues/2105

When a Staging database is synced back to Production, Production is then set to `noindex` and `nofollow`, potentially damaging SEO if a user does not realize. There is currently no way to change the setting on Staging and SEO could be equally damaged if users allowed indexing their Staging site. 

A user requested this feature here: 8670964-zd-a8c

### How

I do not know an easy fix for this unless we allowed selective syncs to exclude the `wp_options` table, preserved the option during syncing, or changed the Privacy Settings to not store data in the database and rely on a constant instead.

**Comment by ash1eygrace** [comment]
Hey @wojtekn! Pinging you so this is on your radar, as it's about Synchronizations.

**Comment by wongasy** [comment]
>When a Staging database is synced back to Production, Production is then set to noindex and nofollow, potentially damaging SEO if a user does not realize. 

I would consider this a bug, rather than a feature request. @wojtekn What is the level of effort for addressing this issue? If it requires a task, I'll add this issue to Build's opportunity inbox. Otherwise, let's tackle it as part of regular maintenance.

**Comment by wojtekn** [comment]
@wongasy it's good as a regular maintenance issue.

**Comment by jartes** [comment]
📌 ACTIONS
- Marked as Triaged on TOB.
- Added `[Pri] Normal` label, and updated [Type] label.

**Comment by katinthehatsite** [comment]
Diff: D166504-code

**Comment by katinthehatsite** [comment]
@mgozdis We just deployed the changes to fix this. Would you be able to give it a test and let us know if there are any issues?

Feel free to re-open the issue if you are still experiencing problems with these settings!

**Comment by mgozdis** [comment]
@katinthehatsite Getting back from AFK. Tested and the issue is fixed. Thanks for fixing and finding the root cause 🙂

**Comment by katinthehatsite** [comment]
Nice, glad it works now!!
