### ISSUE TITLE
Missing translations for Limited Global Styles and Page Patterns selector

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#94070]
Context: paYJgx-5jH-p2

After changing the language to Spanish, some texts still appear in English:

- Limited Global Styles warning notice in the editor: ![image](https://github.com/user-attachments/assets/491a53e9-3b80-4749-8658-9dfec1bc4308)

- Limited Global Styles welcome modal: ![image](https://github.com/user-attachments/assets/52857d73-a4fc-4195-8bd2-ce7d0cc3c358)

- Limited Global Styles warning notice in editor sidebar: ![image](https://github.com/user-attachments/assets/934b91cc-4973-4914-9753-26bd7a1eb043)

- Page patterns selector: ![image](https://github.com/user-attachments/assets/5b639782-5741-45e8-8935-309ae26a8936)

**Comment by gikaragia** [comment]
Hey @mmtr do you intend to work on this? I looked and tried to find out what the problem was but couldn't find it. Seems like the translations don't exist, I could find only [a similar translation with a link](https://translate.wordpress.com/projects/wpcom/es/default?filters%5Bterm%5D=that+are+only+visible+to+visitors+after+upgrading). 

In any case, I downgraded the priority to normal.

**Comment by mmtr** [comment]
@gikaragia I wasn't intending to work on this, but I'm happy to take a look if I have some time later today,

> I downgraded the priority to normal.

Can you expand on this? The reason why I gave this a high priority is because for non-English speakers this issue can be a blocker if they don't understand what they see.

Also, considering that the issue seems to be affecting different areas of ETK features that have been moved to the jetpack-mu-wpcom plugin (pbxlJb-5WO-p2), I wonder if we have a more widespread issue that could be causing missing translations to other ported ETK features.

**Comment by gikaragia** [comment]
Hey @mmtr, I wasn't aware that this might be part of a wider issue, I'll raise the priority to High again. 

I tried to debug this too, but it was too complex to do as part of the Groundskeeping week without any context.

> ETK features that have been moved to the jetpack-mu-wpcom plugin

We should probably notify someone from the team then cc @taipeicoder

**Comment by mmtr** [comment]
This seems related: https://github.com/Automattic/jetpack/pull/39178

**Comment by mmtr** [comment]
> I wonder if we have a more widespread issue that could be causing missing translations to other ported ETK features.

Seems this is the case, so I'm closing this issue in favor of https://github.com/Automattic/i18n-issues/issues/858
