### ISSUE TITLE
wp-admin masterbar icons don't have tooltips

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#94105]
### Quick summary

We've added some icons to the WordPress toolbar:

<img width="339" alt="Screenshot 2024-09-02 at 11 57 24" src="https://github.com/user-attachments/assets/5e3f4af2-36d6-4a7e-ab40-4a05dd4e56a4">

The help icon and the notification bell are probably recognisable due to their widespread use on other websites and apps. The Reader icon isn't recognisable from outside or inside contexts and requires learning to figure out.

It would be easier to learn if it had a tooltip (and for consistency so should the others). They have tooltips in Calypso but not in wp-admin

<img width="339" alt="Screenshot 2024-09-02 at 12 01 05" src="https://github.com/user-attachments/assets/a113977e-a086-4fac-a1ad-0424ca334716">

### Steps to reproduce

1. Go to /wp-admin on one of your sites
2. Hover over the eyeglass icon at the top right

### What you expected to happen

A tooltip to be displayed

### What actually happened

No tooltip is displayed.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Click the icon and see what happens.

### Logs or notes

Confirmed in Safari and Firefox

I noticed this in some [blogged feedback](https://lifesfinewhine.ca/2024/08/29/what-really-grinds-my-gears-wordpress-latest-changes/).

**Comment by retnonindya** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
Just adding it here. There is a tooltip for Reader on Calypso, but it can be dismissed.

![Screenshot 2024-09-05 at 3 22 05 PM](https://github.com/user-attachments/assets/70aeba56-efcc-4d6e-a832-3e20ad4d7f7b)

And I'm not sure if new users are aware what Reader is 🤔 
![Screenshot 2024-09-05 at 3 22 57 PM](https://github.com/user-attachments/assets/a319fdc6-7f9c-41c3-accb-65d60575728b)

And yes, no information about Reader on WP Admin

I also would like to mention this issue: https://github.com/Automattic/dotcom-forge/issues/8940 -- When I clicked the Reader icon on WP Admin dashboard, the "jump/switch" from WP Admin to Calypso feels jarring: Different color and different masterbar height.

📌 ACTIONS
- Triaged
- Feature request kept

**Comment by davemart-in** [comment]
Whatever we do, it should probably be proposed in core, vs. hacking this just for WP.com.

**Comment by m1r0** [comment]
It was a very quick change, so I've decided to add the tooltip to the reader icon in https://github.com/Automattic/jetpack/pull/39803. Do you think this is an ok solution for now?

**Comment by m1r0** [comment]
Here's the last diff waiting for review: D164233-code

**Comment by m1r0** [comment]
The last diff got merged. Closing...
