### ISSUE TITLE
Google Pay / Apple Pay icon alignment has been lost in checkout

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#94123]
The Google Pay and Apple Pay icons in checkout's payment method list have lost their right alignment recently somehow.

<img width="595" alt="Screenshot 2024-09-02 at 6 53 26 PM" src="https://github.com/user-attachments/assets/a3419f18-38b6-4d34-b4a4-73669817bb4f">

<img width="653" alt="Screenshot 2024-09-02 at 6 58 28 PM" src="https://github.com/user-attachments/assets/e836cc81-130d-4871-b35a-07c8f3cc9dd6">

Possibly related to https://github.com/Automattic/wp-calypso/pull/94007 or https://github.com/Automattic/wp-calypso/pull/93932

To reproduce:

- Visit wordpress.com and add a product to your cart (eg: a plan upgrade).
- Visit checkout (you should end up there automatically).
- Make sure your browser is configured to allow either Apple Pay or Google Pay (for Apple Pay you must have Safari and Apple Pay enabled with a card in your wallet, for Google Pay you must have Chrome with Google Pay enabled and a card in your wallet).
- Click through to the end of checkout and view the payment method options (if a payment method is already selected, you may need to click "edit" on the payment method step).
- Examine the alignment of the Google Pay or Apple Pay icon relative to the other icons in the list and notice that it is smooshed against the text on the left side rather than right-aligned.

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by michaeldcain** [comment]
Closed by #94159
