### ISSUE TITLE
[Bug] User did not get migration email after completing the assisted migration flow

### ISSUE THREAD

**Issue by mpkelly** [Automattic/wp-calypso#94126]
### Quick summary

Initial report p1725073959936799-slack-C06PZC1RR5F

A user contacted support after waiting to receive an email about their assisted migration. On inspecting tracking, we found they had submitted two requests but did not produce a ZenDesk ticket on the backend. It is suspected an early exit check in `submit_new_ticket ` failed and returned `site_not_found`, and this wasn't caught on the front end, which doesn't handle the response. This happened in the old migration API, but as `init_automated_migration` has a similar check, we created this ticket to avoid the same issue in the new API. 

See Slack for further analysis and Tracks event log.

### Steps to reproduce

It's not known how to reproduce this issue yet. It could be related to the user having a Jetpack-connected site. 

### What you expected to happen

A ticket should be created in ZenDesk for every issue. 

### What actually happened

No ZenDesk ticket was created for this migration. 

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by mpkelly** [comment]
It seems there was another case but the issue appears to be only on the client. This conditinal check fails:

```
// config.isEnabled( 'automated-migration/collect-credentials' )  = true
// isCredentialsSkipped = false

if ( ! config.isEnabled( 'automated-migration/collect-credentials' ) || isCredentialsSkipped ) {
	sendTicket( {
		locale,
		from_url: fromUrl,
		blog_url: siteSlug,
	} );
}

```

More details and a video here p1725334011341529/1725073959.936799-slack-C06PZC1RR5F

**Comment by mpkelly** [comment]
Another report here 8684398-zd-a8c.

**Comment by m1r0** [comment]
@andres-blanco, to double check, did your PR fix the issue or it's just related?

**Comment by obenland** [comment]
@markbiek @andres-blanco Did https://github.com/Automattic/wp-calypso/pull/94151 fix this bug?

**Comment by andres-blanco** [comment]
> @markbiek @andres-blanco Did #94151 fix this bug?

Since the PR addresses a fix for users who went through the flow while already having a plan, I would consider it a related PR rather than a direct fix. This is because the issue doesn't specify whether the affected users had a plan or not.

cc @m1r0

**Comment by valterlorran** [comment]
@daledupreez, thanks for pinging. Yes! By the time Mike tested it, it seemed he didn't see the credentials step, which would explain the broken ticket creation flow.

**Comment by daledupreez** [comment]
OK, I think we can mark this as closed based on the two PRs that we shipped.
