### ISSUE TITLE
Reader Stream Refresh: Excerpts and action buttons are not displayed in gallery cards (IE11)

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9412]
In IE11, excerpts and action buttons are not displayed in gallery cards:

![screenshot 2016-11-15 21 24 44](https://cloud.githubusercontent.com/assets/4924246/20335741/f3061ea8-ab79-11e6-8c05-10296fbbc85b.png)

Reported by: @alisterscott

**Comment by samouri** [comment]
I believe the issue we are running into is that nested flexboxes don't respect children's min-heights in IE11. [bug report](https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview).

**Comment by samouri** [comment]
Fixed in #9994
