### ISSUE TITLE
Clicking manage patterns on the editor opens a patterns view which is not ideal for pattern management

### ISSUE THREAD

**Issue by jorgefilipecosta** [Automattic/wp-calypso#94137]
### Quick summary

With the normal post editor opened when clicking on "Manage Patterns" we go to a normal post view applied to patterns as the following image shows:
<img width="1097" alt="Screenshot 2024-09-03 at 11 40 04" src="https://github.com/user-attachments/assets/ccffc2bb-2078-437f-97b1-ba010a0eb746">

This view is not ideal as patterns don't have status like published, scheduled, etc. That view also does not include a pattern preview which makes managing patterns hard.

### Steps to reproduce

1. Open a post in the editor.
2. Go to the options menu (three points at top right corner).
3. Click manage patterns and verify the UI shown above loads.

### What you expected to happen

I expected the core pattern view to be loaded as it happens in a normal core install.
<img width="2546" alt="Screenshot 2024-09-03 at 11 45 37" src="https://github.com/user-attachments/assets/0f8c9ee3-76b8-4110-a29c-d2f17c327e6a">

### What actually happened

A normal post view was used in patterns.
This view is not a good fit for patterns because of the following reasons:
- Shows status the patterns don't have (published, scheduled, etc)..
- Does not allow to explore patterns by category or their sync/unsync status, making it harder to manage patterns properly.
- Does not show a preview of the pattern.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by nightnei** [comment]
> Shows status the patterns don't have (published, scheduled, etc)..
Looking at the page, such info is not relevant, since we don't have opportunity to render patterns with different statuses at once. We have tabs for rendering templates with specific status
<img width="500" alt="Screenshot 2024-09-03 at 13 25 08" src="https://github.com/user-attachments/assets/87d247c5-c7fe-4006-9334-99d7c075a268">

> Does not allow to explore patterns by category or their sync/unsync status, making it harder to manage patterns properly.
Is it possible to set specific category fo own patterns?
Also, I don't know - what does it mean "sync" / "unsync" statuses? Is it really relevant to own patterns?

> Does not show a preview of the pattern.
It's true, maybe it would be a bit more comfortable to have previews. But if previous two points are indeed not relevant (I can be wrong), then it looks like only point about previews is relevant, and personally for me it looks like just enchansement, so I would decrease the priority to "Normal", since it's not a bug and it's just about rendering preview or not, anyway we still have preview name as an identification.

@jorgefilipecosta WDYT?

**Comment by jorgefilipecosta** [comment]
Hi @nightnei,

> Looking at the page, such info is not relevant, since we don't have opportunity to render patterns with different statuses at once. We have tabs for rendering templates with specific status

Patterns don't have status, we don't schedule or publish patterns. We just have saved patterns. So referring status is unexpected and is a bug.

>  Is it possible to set specific category fo own patterns?

Yes, the user can attribute categories to patterns. E.g.: about page patterns or contact page patterns. And can change categories etc. I guess when managing patterns it should be possible to see patterns of a specific category.


> Also, I don't know - what does it mean "sync" / "unsync" statuses? Is it really relevant to own patterns?

Sync means when the pattern is changed all the posts using that pattern, are changed to reflect the pattern change. Unsync means when the pattern is changed it will only affect new posts using that pattern. When creating a pattern the user can decide if the pattern is synced or unsync:
<img width="496" alt="Screenshot 2024-09-03 at 13 58 32" src="https://github.com/user-attachments/assets/b1f2e3af-f8f7-4d59-820c-11f869335d5b">

So when managing them it should be possible to see what type of pattern the user is managing.


What this issue is proposing is not to implement something new in WordPress.com. It is just to use the core pattern management UI that any other WordPress hosts offers and I think is better that what WordPress.com is currently offering its users.

| WordPress.com UI | WordPress.org UI |
|------------------|---------|
| <img width="1097" alt="Screenshot 2024-09-03 at 11 40 04" src="https://github.com/user-attachments/assets/ccffc2bb-2078-437f-97b1-ba010a0eb746">               | <img width="2546" alt="Screenshot 2024-09-03 at 11 45 37" src="https://github.com/user-attachments/assets/0f8c9ee3-76b8-4110-a29c-d2f17c327e6a">       |

**Comment by nightnei** [comment]
I see, sounds reasonable.
I am looking at the list of possible lanels for tasks and WDYT about marking this task as `[Feature Group] User Interaction & Engagement` & `[Pri] Normal`? Since the UI is usable now w/o bugs, it's mostly about improvements of UI/UX. What is your opinion?
