### ISSUE TITLE
You can't select Twenty Twenty-Four theme in mobile onboarding

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#94145]
In mobile onboarding, the default active theme is Twenty Twenty-Four. When you reach the design selection screen, it is impossible to continue with the default theme; the user must select a different theme to continue in the onboarding flow to continue.

https://github.com/user-attachments/assets/bfed2e82-31c6-475d-aa95-9899f574fbec

**Comment by mmtr** [comment]
Seems this is a regression introduced by https://github.com/Automattic/wp-calypso/pull/94115 (cc @rcrdortiz)

**Before**

https://github.com/user-attachments/assets/f137e01e-850a-4f54-904e-c855e36e2b87

**After**
https://github.com/user-attachments/assets/d6938444-9179-4670-9e9b-5865476caf82

**Comment by rcrdortiz** [comment]
This should be fixed here: https://github.com/Automattic/wp-calypso/pull/94176

**Comment by miksansegundo** [comment]
Closing as completed by https://github.com/Automattic/wp-calypso/pull/94176
