### ISSUE TITLE
Broken scrolling on /me profile pages

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#94167]
Reporting a regression caused by #90437. Two bugs:

1. go to any `/me` subsection, like `/me/privacy`, and scroll all the way down. Notice that the bottom part of the page is cut off, the page hasn't really scrolled to the very bottom. In this screenshot, I should see a horizontal bottom border of the `Card` box under the "Request DPA" button, but it's not there:
  
  <img width="1036" alt="Screenshot 2024-09-04 at 8 44 51" src="https://github.com/user-attachments/assets/7ff2c3b6-060a-439e-8324-a5c3b7e5398b">

2. after scrolling the page down, use the sidebar links to navigate to another `/me` subsection. The expected behavior is that the page scrolls up and I see the section header. But the actual behavior is that I see the bottom of the new section.

Both bugs are probably caused by the `main` element having a fixed `height`. It's no longer the element that scrolls, some inner element scrolls instead.

FYI @candy02058912

**Comment by candy02058912** [comment]
Asked for help from the teams currently working on Logical Flows.
Thanks for the report. 🙏

**Comment by taipeicoder** [comment]
Moving this to Ready for Dev.

**Comment by jartes** [comment]
📌 ACTIONS
- Triaged: added relevant product labels
