### ISSUE TITLE
Coupon button in checkout is not indented correctly at small widths

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#94187]
If you view checkout at small widths, the "Have a coupon" button seems to be outside the normal margin region of the rest of checkout's elements. This is a regression from when the button was moved to deemphasize it. (I'll try to find those PRs and add a link)

![Image](https://github.com/user-attachments/assets/f883b26b-affb-4b3f-9bd9-2d1e48788503)

**Comment by sirbrillig** [comment]
This is where the field was moved: https://github.com/Automattic/wp-calypso/pull/88450 and https://github.com/Automattic/wp-calypso/pull/88718

It's likely that those were the origin of this issue.

**Comment by sirbrillig** [comment]
@jjchrisdiehl this might be a quick fix if you find the time for it. You've done wonders with checkout's CSS before.

**Comment by jjchrisdiehl** [comment]
PR is ready for review here https://github.com/Automattic/wp-calypso/pull/94514
