### ISSUE TITLE
Ability to organize Media

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#94182]
### What

Simple site users do not have an easy way to manage media on their site.

### Why

This will make it easier for users to manage and find media files on their website.  

They have no other option but to upgrade to a much expensive Business plan to install third-party plugins to manage media. 

User report: 8690271-zd-a8c

**Comment by fditrapani** [comment]
Thanks for reporting this @devNigel. This is something that's not possible in Core. It would be a nice addition but is a very big lift. I'm going to close this issue for now since we don't have plans to make improvements to the media gallery at the moment.
