### ISSUE TITLE
Hosting Dashboard: Convert the existing “Actions” fields into core DataViews “Actions”

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#94198]
Convert the existing “Actions” fields into proper core DataViews “Actions”. This means we have bulk selection for free and there’s no table header tools for that column (move left/right controls).

Follow-up to https://github.com/Automattic/wp-calypso/pull/93503

**Comment by youknowriad** [comment]
I started looking at this a little bit. There are a two things that are not possible currently in the Actions API and that exist in the Actions dropdown used in the sites dataviews

1- Descriptions or help text for actions

<img width="196" alt="Screenshot 2024-09-05 at 12 56 45 PM" src="https://github.com/user-attachments/assets/6152c237-75af-4764-9435-30dfe3ae88d4">

This is probably something we can easily support upstream if needed.

2- Nested drop-down for actions (or "grouping" actions)

<img width="459" alt="Screenshot 2024-09-05 at 12 57 10 PM" src="https://github.com/user-attachments/assets/1f8f08c0-8bad-4a9c-8527-d74101e614a5">

While I think it's possible to support potentially by introducing some notion of "group" for actions or something like that. I'm not entirely sure we should support it to be honest. My suggestion would be to remove the nesting and maybe have a single link to Hosting where the user can see all these sections.

WDYT. @jameskoster @davemart-in

**Comment by davemart-in** [comment]
I think it would be fine to drop both the nested dropdown and the help text.

**Comment by youknowriad** [comment]
For clarity, myr PR is at the moment blocked by the fact that the `/sites` endpoint doesn't include `features` which means that for each "site", we need to perform an extra REST API request to fetch the features before rendering the DataViews. 

I know @jsnajdr was looking into iterations on the sites endpoint to address that but it seems a bit complex, so I'm not entirely sure what's the next step here.

**Comment by jsnajdr** [comment]
The REST endpoint is fixed, it now returns the active `features`. I have a draft PR for Calypso that removes all the explicit `QuerySiteFeatures` queries, but it's a big change and will some more work to finish: #94840.

**Comment by youknowriad** [comment]
Oh I didn't know. Thanks @jsnajdr. Do you think I should wait for your PR to land first or should I update my actions PR (smaller scope) to use the featured directly? Thinking the latter unless you have any reservations

**Comment by jsnajdr** [comment]
> should I update my actions PR (smaller scope) to use the featured directly?

I won't get to work on it again at least until Oct 2, so you might want to use the `features` directly for now.

Instead of using the `siteHasFeature` selector, look directly at the `site` object:
```js
hasFeature = ( state, siteId, feature ) => getSite( state, siteId ).plan.features.active.includes( feature )
```
If the `/me/sites` info is loaded at all, then the `plan.features.active` info will reliably be there.

**Comment by youknowriad** [comment]
Great Thanks, I'll give it a try.

**Comment by Copons** [comment]
I think this can be closed now. ✨
