### ISSUE TITLE
Reader: share link is difficult to tap when the site title and share link overlap

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#942]
Steps to reproduce:

1. Open a single-post various WordPress.com blogs using the Reader in Safari on iOS
1. Try to tap the "Share" link at the top

<strong>Result:</strong> on posts that have comment and like count showing, the site title and the "Share" link in the top bar overlap a bit making it a little hard to tap.

<img src="https://cloud.githubusercontent.com/assets/1119271/9736988/64d2d1f2-5612-11e5-8de1-476e8ed3ee43.PNG" width="400" />
<img src="https://cloud.githubusercontent.com/assets/1119271/9736990/64dd22ba-5612-11e5-8542-b58dd0345132.PNG" width="400" />
<img src="https://cloud.githubusercontent.com/assets/1119271/9736989/64d6d856-5612-11e5-91d4-abc380cd6823.PNG" width="400" />

Note from @shaunandrews 

> We could save some room if we drop the comment/like counts, and shrink things down a bit:

<img src="https://cloud.githubusercontent.com/assets/191598/9925412/39788786-5cd9-11e5-8b93-a033f9e085d4.png" alt="screen shot 2015-09-17 at 1 12 14 am" width="400" />

Note from @karmatosed 

> +1 to shrinking things down a bit like above. Perhaps the Share could become an icon though? Just a thought as at that size we have icons for comments, likes and pretty much everything else.

Note from @shaunandrews 

> So after some tinkering, it occurred to me that the most obvious thing to do here is to pull the site title out of that action bar.
> 
> ![screen shot 2015-10-29 at 2 01 59 pm](https://cloud.githubusercontent.com/assets/191598/10827508/cce8dae2-7e45-11e5-8964-cb85db08fcda.png)
> 
> ![screen shot 2015-10-29 at 2 02 35 pm](https://cloud.githubusercontent.com/assets/191598/10827511/cfa6db6c-7e45-11e5-9510-42519c2d4167.png)

**Comment by shaunandrews** [comment]
Fixed  in #630
