### ISSUE TITLE
Hosting Dashboard: Persist selected options

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#94203]
**Consider fixing this upstream:** https://github.com/WordPress/gutenberg/issues/57669

None of this seems to persist - If for instance, I click "10" items per page, the current page updates, but if I navigate away from the sites page and then come back, I expect to still see 10 items per page. Instead these settings always seem to reset:

![CleanShot 2024-09-03 at 14 33 09@2x](https://github.com/user-attachments/assets/86d07d88-91ee-4c79-8e45-ed385be3d90e)

From https://github.com/Automattic/wp-calypso/pull/93503#issuecomment-2327194413

**Comment by davemart-in** [comment]
Sounds like this is already on the radar for core.
