### ISSUE TITLE
Streak notifications not reset

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#94224]
### Quick summary

There are multiple users recently reporting reporting that their streaks don't get reset after missing a day
 * [Streak not resetting after skipping days](https://irenefes9.wordpress.com/2024/08/29/help-me-understand-wordpress-streak/)
 * [Missed three days and my WP streak continues](https://lifesfinewhine.ca/2024/09/03/are-wordpress-stats-bogus/)
 * Streak notifications too long (p1724266514186399-slack-C03N25JPCE4)

### Steps to reproduce

?????

### What you expected to happen

Streak notifications to be reset if missing a day

### What actually happened

Streak not resetting after skipping days

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by allilevine** [comment]
It looks like @kraftbj shipped a fix here: D162046-code

I'll keep this open to check my streak count, to confirm.

**Comment by allilevine** [comment]
I posted two days in a row and saw a 2 post streak using the MC tool mentioned in the diff. Then I skipped a day, and posted again today. My streak correctly changed to 1 post. I'm closing as fixed, but feel free to re-open if there's another report.
