### ISSUE TITLE
Cleanup: remove language checks on site-migrations-credential step

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#94237]
In [this PR](https://github.com/Automattic/wp-calypso/pull/94204) language checks were added to prevent showing a mixed language UI.

Once translations are in we should remove those checks to keep the code clean.

**Comment by valterlorran** [comment]
Oh! Thanks for creating this issue @andres-blanco!

**Comment by valterlorran** [comment]
We are tackling this issue here: https://github.com/Automattic/wp-calypso/pull/94337

**Comment by andres-blanco** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/94337
