### ISSUE TITLE
AT: Plugins search for .com sites

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#9425]
It should just search the existing plugins object that already exists in Calypso.

**Comment by drw158** [comment]
<img width="746" alt="screen shot 2016-11-16 at 10 44 50 am" src="https://cloud.githubusercontent.com/assets/618551/20349563/c0173930-abe9-11e6-973f-305bb2f0b806.png">

**Comment by drw158** [comment]
New tab names that are on Jetpack 4.4 that we need to use:

<img width="421" alt="screen shot 2016-11-16 at 10 43 32 am" src="https://cloud.githubusercontent.com/assets/618551/20353774/a4708c34-abfa-11e6-9162-e16e0db412a2.png">

**Comment by drw158** [comment]
Also, just to make sure, all "features" will be on the page at once (not divided by tab). The tabs will just filter the view.

**Comment by drw158** [comment]
We'll need to follow Jetpack's lead with how they grouped the settings. Go to the Jetpack settings in wp-admin to see how they grouped each feature.

<img width="749" alt="screen shot 2016-11-16 at 1 00 20 pm" src="https://cloud.githubusercontent.com/assets/618551/20354432/df4f1166-abfc-11e6-8694-5412ef40c188.png">

**Comment by drw158** [comment]
We need to make an empty state. 

<img width="759" alt="screen shot 2016-11-17 at 1 15 07 pm" src="https://cloud.githubusercontent.com/assets/618551/20397325/13cf4ae8-acc8-11e6-9b84-028f0726f3ad.png">

This seems to be the standard 

<img width="708" alt="screen shot 2016-11-17 at 1 16 22 pm" src="https://cloud.githubusercontent.com/assets/618551/20397338/1d6a0df4-acc8-11e6-8a82-314dee4086a0.png">

Not sure I like the illustration though, maybe just use a Gridicon instead?
