### ISSUE TITLE
Command Palette: add tracking to understand discoverability

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#94267]
Currently, there's no tracking around how the command palette is initiated. Opening this issue to better understand what entry points folks are using and to track how that might change when/if new entry points are added. There are three items to add tracking to right now:

Editor header:

https://github.com/user-attachments/assets/f2465293-9863-47fc-adda-d482c2bb9d3f

Site editor sidebar:

https://github.com/user-attachments/assets/f9c83521-32cd-435c-94d6-efd410889f06

Command K (shortcut that makes it open)

**Comment by arthur791004** [comment]
Proposing https://github.com/Automattic/wp-calypso/pull/94271 to track the command palette behavior 🙂

**Comment by miksansegundo** [comment]
https://github.com/Automattic/wp-calypso/pull/94271 has been merged. We can find in the PR description the events and props being tracked.
