### ISSUE TITLE
AT: Customize plugin detail view on .com

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#9426]
Most of the info shown on the plugin detail view is irrelevant to .com users and could cause confusion.

Plugin detail view for self-hosted sites:

<img width="782" alt="screen shot 2016-11-16 at 11 01 17 am" src="https://cloud.githubusercontent.com/assets/618551/20350076/0771eef4-abec-11e6-81c7-4f6b15c38306.png">

New design that should be doable this week:

Basically I just hid all of the irrelevant stuff with CSS.

<img width="736" alt="screen shot 2016-11-16 at 11 17 26 am" src="https://cloud.githubusercontent.com/assets/618551/20350626/5fcfaa4e-abee-11e6-9814-fc6d8e676dfe.png">

**Comment by drw158** [comment]
On second thought, that should be a Nudge, not a notice.

**Comment by vindl** [comment]
Resolved in https://github.com/Automattic/wp-calypso/pull/9468.
