### ISSUE TITLE
My Sites: Actions button showing up below compressed sites list

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#94278]
### Quick summary

The actions button is pushed to the bottom when expanding a site's details.

![Screenshot 2024-09-06 at 1 37 05 PM](https://github.com/user-attachments/assets/b19d5c23-5c92-4e9d-81bc-85437f0eb524)

## Example

https://github.com/user-attachments/assets/80c546a6-edfa-4007-b79c-53a09096b2e6

Slack - p1725601374661019-slack-C03NLNTPZ2T

### Steps to reproduce

1. Go to `/home/${BLOG_SITE}`
2. Click the **Managed your sites** button (The WordPress logo at the leftmost).
3. Click on any site to show the site overview panel and compressed site list
4. You should see the actions button below each site in the list
5. Refresh the page and it should render next to each site list (as it should be)

### What you expected to happen

The actions button should show to the right of the site list;

<img width="498" alt="Screenshot 2024-09-06 at 09 54 41" src="https://github.com/user-attachments/assets/b1f22fc8-c430-4c69-976a-0daa30ca2958">

### What actually happened

The actions button renders below each site in compressed site list

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Not sure bug is present on all browsers but the issue was reproduced in Chrome
Refresh the page

**Comment by Addison-Stavlo** [comment]
resolved in https://github.com/Automattic/wp-calypso/pull/94289
