### ISSUE TITLE
AT: add "Browse all Plugins" button to plugins page

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#9427]
This can be separately from the CSS style update to the plugins page. The button goes to the plugin directory.

Depends on #9424 

Should be done after #9423 ?

<img width="762" alt="screen shot 2016-11-16 at 11 03 55 am" src="https://cloud.githubusercontent.com/assets/618551/20350141/646f973c-abec-11e6-95e4-39f4380808f2.png">

Also 

<img width="290" alt="screen shot 2016-11-16 at 11 00 48 am" src="https://cloud.githubusercontent.com/assets/618551/20350131/57fce108-abec-11e6-8483-e8e4af905709.png">

**Comment by vindl** [comment]
Partly resolved by https://github.com/Automattic/wp-calypso/pull/9468. I've inserted the `Add` button there.

**Comment by vindl** [comment]
Resolved by https://github.com/Automattic/wp-calypso/pull/9448.
