### ISSUE TITLE
Reader: Export feeds via OPML

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#943]
We should allow OPML exports for feed subscriptions.

Raised by @blowery

**Comment by TooTallNate** [comment]
@blowery Do you envision this being server-side API logic, or client-side JS logic?

**Comment by blowery** [comment]
@TooTallNate server side, it's already part of the API. see `public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-read-export-endpoint.php` in wpcom
