### ISSUE TITLE
Cache Flush Resets Admin Color Scheme to Classic Dark

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#94308]
### Quick summary

Selecting any Admin Color Scheme in Users > Profile (https://mysite.com/wp-admin/profile.php) updates the colors as expected. However, flushing the cache via CLI resets the scheme to Classic Dark.

### Steps to reproduce

1. On an Atomic site, click Users > Profile (https://mysite.com/wp-admin/profile.php)
2. Change the Admin Color Scheme to anything other than Classic Dark (preferably something more colorful like Sunrise or Sakura)
3. Press Update Profile
4. Notice the change in colors
5. In a new tab, visit the site's CLI interface at https://mysite.com/_cli
6. Flush the cache with `cache flush`
7. Go back to the tab containing Users > Profile and refresh the page

### What you expected to happen

For the currently selected Admin Color Scheme to stay as is.

### What actually happened

The Admin Color Scheme switches to Classic Dark and the colors have changed.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by druesome** [comment]
Tickets:

8696762-zen
8689265-zen

**Comment by m1r0** [comment]
I can confirm that this happens when `wp_cache_flush()` is called.

It might be related to https://github.com/Automattic/wpcomsh/pull/1669. @Automattic/lego does this sound like something in your domain?

**Comment by arthur791004** [comment]
The issue seems to be gone with the latest WordPress.com Features. Could you help to provide the version of `jetpack-mu-wpcom-plugin` on client sites? Thank you!

**Comment by m1r0** [comment]
> Could you help to provide the version of jetpack-mu-wpcom-plugin on client sites?

I'm not that familiar with Atomic. Could you give me a hint of where to look?

If that helps, the `wpcomsh` plugin (`/home/150760296/wordpress/plugins/wpcomsh`) version is 5.8.1-alpha. The atomic site that I'm testing is https://m1r0slav82.wpcomstaging.com.

Here's a step-by-step of how I'm testing this bug:

* Visit `https://m1r0slav82.wpcomstaging.com/wp-admin/profile.php`
* Change the Admin Color Scheme to something else.
* Go to the CLI and run `wp cache flush`.
* Go back to `https://m1r0slav82.wpcomstaging.com/wp-admin/profile.php` and refresh.
* The scheme is reset.

https://github.com/user-attachments/assets/b3b97932-3e8d-4f1e-ba8b-8d344c5ef7f3

To remove the CLI from the picture, I've also tried executing a file `https://m1r0slav82.wpcomstaging.com/flush.php` which only calls `wp_cache_flush()`. The result is the same - the scheme is reset.

**Comment by arthur791004** [comment]
I confirmed that the reason is the Admin Interface Style is configured to the `Default styles`. It means the admin color is based on their WordPress.com account.

<img width="635" alt="image" src="https://github.com/user-attachments/assets/e6b8c53a-c091-4808-9d58-08ec1152bd33">

I'll continue to check why updating the color scheme from the profile.php doesn't work correctly

**Comment by arthur791004** [comment]
Proposing https://github.com/Automattic/jetpack/pull/39368 to resolve this issue.

**Comment by druesome** [comment]
Thank you @arthur791004 !  I have notified the users.
