### ISSUE TITLE
Tabs content of Site details page is not displayed after navigating to hosting features tab

### ISSUE THREAD

**Issue by fluiddot** [Automattic/wp-calypso#94325]
### Quick summary

On the Sites page, after navigating to a site that doesn't have hosting features enabled but can opt-in, navigating to other tabs like "Deployments" on other sites results in not displaying the content. It remains with the content of the Hosting Features tab.

### Steps to reproduce

1. Navigate to the [Sites page](https://wordpress.com/sites).
2. Select a Simple site that has a plan to enable hosting features.
3. Select the tab Hosting Features.
4. Select another site that has hosting features enabled.
5. Try to navigate any of the tabs (e.g. Deployments or Staging Site).
6. Observe the content of the tab is not displayed and remains in the Hosting Feature tab.

### What you expected to happen

Content of tabs of site details should be displayed.

### What actually happened

The content of the Hosting Feature remains after clicking on other tabs.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

- Select a Simple site.
- Select the Overview tab.
- After navigating to the Overview tab, other tabs are displayed again.

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

After navigating to the Hosting Features tab, I noticed that navigating to other tabs is actually trying to load its content but the browser quickly redirects to `https://wordpress.com/hosting-features/<SITE_DOMAIN>`.

**Comment by Addison-Stavlo** [comment]
I can repro this:
![hosting-features-bug](https://github.com/user-attachments/assets/2bf0c97a-65ed-47d6-b89a-d2c47f9f20a8)

Note - this does not seem to happen if the first site for the "Hosting Features" tab is lower than business and prompts to "upgrade". It only seems to happen if the site has a business plan or higher and the hosting features tab prompts activation.

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/94380 aims to resolve.
