### ISSUE TITLE
Add link to reach Purchases page in Hosting Overview

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#94341]
### What

Add a "Purchases" quick link to reach the Purchases page to manage subscriptions on a site's Hosting Overview page.  

### Why

Sites that use wp-admin as their default use the Hosting Overview page for a lot of settings access; but to reach purchases, they have to enter the dashboard through some other method, _then_ hover over Hosting and choose Purchases.  This seems unnecessarily buried.

![CleanShot 2024-09-09 at 11 22 21@2x](https://github.com/user-attachments/assets/0ddc9398-336e-483a-91d1-b3e32d90f50b)

### How

When a site admin is the owner of the site's plan, there is a "Manage Plan" link in the Plan's modal – but that feels limited, as it is easy to miss, only visible to the plan owner, and does not refer to any other subscriptions owned on the site (email, domains, storage add-ons, themes, etc). 

The list under "Command Palette" could easily be updated to include a **Manage Purchases** link.

**Comment by fditrapani** [comment]
Thanks for reporting @cuemarie. It looks like a link has been added:

![Image](https://github.com/user-attachments/assets/423de6a7-31f5-4c02-bd34-89c81d66551a)

I'm going to close this issue for now. Feel free to open it up if there's still a problem.
