### ISSUE TITLE
GuidedTours: remove target duplication in Step/Continue elements

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#9435]
In a tour definition, both a `Step` and a `Continue` element can point to a `target`. So far, we have duplicated every `Continue` element's `target` in the parent `Step` element. 

We do need to know the `target` in the `Step` element so blanket exit / `Step.quitIfInvalidRoute` works correctly. Possibly also for other things? 

We should remove this duplication, e.g. by automatically finding a child `Continue` element and its `target` when running `Step.quitIfInvalidRoute`. Alternatively we could also require the `target` to only be in the `Step` element and deduce a `Continue` element's `target` from its parent `Step`. 

Any opinions on the approach to take here? 

/cc @mcsf

**Comment by mcsf** [comment]
> Any opinions on the approach to take here?

At this moment, I should think about it a little and also figure out whether there were deeper implications in #9432 and the early GT decisions to have `target` and blanket exit checks in `Continue`.

Furthermore, as far as nascent frameworks go, it's acceptable to require some duplication to tour authors. As authors start working on tours, we can come across limitations and/or interesting use cases and make a more informed decision on this. It's also late for my brain.

**Comment by lsinger** [comment]
This is OK to close for now IMHO.
