### ISSUE TITLE
Stepper: Investigate `calypso_signup_complete` Tracks event and ensure it gets recorded properly

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#94415]
See the audit by @travisw: https://github.com/Automattic/wp-calypso/issues/94394

Ensure that we meet the criteria for this:

- [ ] `calypso_signup_complete` not recorded as expected

**Comment by chriskmnds** [comment]
@travisw I'm also seeing this getting called correctly once I select a plan and get past the processing step. Can you please confirm once more?

**Comment by travisw** [comment]
While testing [here](https://github.com/Automattic/wp-calypso/issues/94423#issuecomment-2356650180) I did also see this event fire 🎉. I think not seeing it was related to me getting redirected to /sites in my original audit. As long as the flow proceeds normally then it _seems_ ok.

**Comment by escapemanuele** [comment]
Closing this as not an issue :)
