### ISSUE TITLE
Stepper: User step - ensure `calypso_signup_start` fires before `calypso_signup_step_start`

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#94416]
See the audit by @travisw: https://github.com/Automattic/wp-calypso/issues/94394

Ensure that we meet the criteria on User step:

- [ ] `calypso_signup_start` should get recorded before `calypso_signup_step_start`

**Comment by chriskmnds** [comment]
@daledupreez @gabrielcaires it looks like you've done a bit of work/investigation with the `calypso_signup_start` event - across https://github.com/Automattic/wp-calypso/issues/91280 and https://github.com/Automattic/wp-calypso/issues/91243 seem to be relevant.

Is this issue something you're looking into already? I think this is what you describe in https://github.com/Automattic/wp-calypso/issues/91280 , but not sure. Was it something you expected to go away with bringing User step into Stepper? 

I can keep investigating, but pls do shed some light. I get the feeling this may reflect back to the way the User step was implemented in Stepper, which is not treated like a regular step (right?).

**Comment by travisw** [comment]
I'm getting mixed results so maybe it's intermittent. But with _most_ of the times I just tested now I'm seeing them in the correct order. I tried multiple browsers and locales.

**Comment by chriskmnds** [comment]
> I'm getting mixed results so maybe it's intermittent. But with _most_ of the times I just tested now I'm seeing them in the correct order. I tried multiple browsers and locales.

Thanks @travisw . I see these getting logged properly on my end, with one exception: If I refresh `/setup/onboarding` while logged in, then `calypso_signup_start` won't get logged at all. Is this expected? I think it was a workaround to having to send user to `/start` and back previously (for logging in), but this sounds broken now that we don't send them back/forth?

**Comment by travisw** [comment]
> Thanks @travisw . I see these getting logged properly on my end, with one exception: If I refresh /setup/onboarding while logged in, then calypso_signup_start won't get logged at all. Is this expected? I think it was a workaround to having to send user to /start and back previously (for logging in), but this sounds broken now that we don't send them back/forth?

Interesting. That doesn't seem expected to me. cc @MicBosi for awareness on some of these ongoing investigations.

**Comment by escapemanuele** [comment]
> then calypso_signup_start won't get logged at all. 

Yes, just came here to say the same, as I kinda expected it to fire anyways. Well, Start is firing the event, so we should do that

**Comment by skim1220** [comment]
Hi Team, just wanted to share that `calypso_signup_start` and `calypso_signup_step_start` were firing in the correct order at the account creation step in [my latest test](https://github.com/Automattic/wp-calypso/issues/95106).

**Comment by chriskmnds** [comment]
@escapemanuele Should we close this?
