### ISSUE TITLE
Wrong upgrade credit calculation for sites with multiple subscription of the same plan

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#94413]
### Quick summary

The upgrade credit calculation seems to be wrong on sites where the user has renewed their plan multiple times before expiry. 

### Steps to reproduce

1. Create a new site.
2. Add a yearly Personal plan via free credit/actual card 2/3 times on the same site.
3. Now, visit the Upgrades > Plans page from the site's admin dashboard.

### What you expected to happen

You should see everything you've paid as upgrade credit there. For example, if you're using the yearly Personal plan for $48(per year) and renew it two times(meaning you've already paid $96), you should see $96 in the upgrade credit section.

### What actually happened

You will see $48 as the upgraded credit. Although you have purchased the subscription for multiple years, it will show you the cost of one year as the upgrade credit. 

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by DavidRothstein** [comment]
This may be a duplicate of https://github.com/Automattic/payments-shilling/issues/2069?

**Comment by Addison-Stavlo** [comment]
> This may be a duplicate of https://github.com/Automattic/payments-shilling/issues/2069?

It reads like a duplicate, but I will leave it to your discussion to close or keep tracking separately since the details are slightly different. I see this has been added to the shilling board.

**Comment by michaeldcain** [comment]
This should be solved by https://github.com/Automattic/payments-shilling/issues/2069, which is near the top of our Up Next column. I'm going to close this issue and track the work over there.
