### ISSUE TITLE
Stepper: Plans page - ensure `calypso_signup_actions_submit_step` fires once only

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#94421]
See the audit by @travisw: https://github.com/Automattic/wp-calypso/issues/94394

Ensure that we meet the criteria for this:

- [ ] `calypso_signup_actions_submit_step` should get recorded only once when selecting a plan (e.g. Personal)

**Comment by renancarvalho** [comment]
I investigated this issue, but I'm unsure if it's a bug.

The event is triggered during the [step submit](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/index.ts#L63) process. After selecting a plan, subsequent steps like “processing,” “site creation,” and “create-site” also trigger the submit step. This is why we see the event being logged multiple times.

Compared to the behavior in /start, there's a slight difference. In /start, this event is triggered when selecting a plan, not during the submit step. There, the event passed is an action that triggers the log.

Even though the event is triggered more than once, the step property in the logs seems accurate. It logs each step being submitted according to the respective step, which makes me question whether this is actually an issue.

If we do consider this a problem, I suggest moving the log from the submit step to the PlanSelect event.

c/c @escapemanuele

**Comment by chriskmnds** [comment]
Thanks for the detailed analysis. The behavior you describe is how it ought to work in my mind too - every step starts and submits when navigated away, not sure if plans should be any different

**Comment by renancarvalho** [comment]
Hi @chriskmnds, just to make sure I got your comment, you think we should then log it when the user selects a plan?

🙇

**Comment by chriskmnds** [comment]
> Hi @chriskmnds, just to make sure I got your comment, you think we should then log it when the user selects a plan?
> 
> 🙇

Hey @renancarvalho, I think the way it is right now makes sense. I would consider this a non-issue as well.

let's cc @travisw to confirm maybe?

**Comment by renancarvalho** [comment]
Maybe @MicBosi can also help us here?

**Comment by MicBosi** [comment]
> The event is triggered during the [step submit](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/hooks/use-step-navigation-with-tracking/index.ts#L63) process. After selecting a plan, subsequent steps like “processing,” “site creation,” and “create-site” also trigger the submit step. This is why we see the event being logged multiple times.

> Although the event is triggered multiple times, the step property in the logs appears accurate, with each instance having distinct properties. It correctly logs each step being submitted based on the respective step

@renancarvalho I tested the plans step with /setup and /start and pretty much I found what you described above - so I don't see an issue in this specific case with `calypso_signup_actions_submit_step`.

Also, both fire `calypso_signup_actions_submit_step` with `step: plans`, so `/setup` is compatible with old funnels etc. that rely on it. So overall everything looks good to me.

**Comment by renancarvalho** [comment]
Thank you for checking it @MicBosi, closing it 👍
