### ISSUE TITLE
Submit Tracks event for `Status` filter on wordpress.com/sites

### ISSUE THREAD

**Issue by fredrikekelund** [Automattic/wp-calypso#94433]
### Details

We currently don't submit any Tracks event for the `Status` filter on wordpress.com/sites. We should do that, and we should track which value users select by passing a prop.

### Checklist

- [ ] Ensure we record a Tracks event when the `Status` filter is used and that the filter value is passed in a prop.

**Comment by supernovia** [comment]
📌 Message to Author
Hi @fredrikekelund! This was marked as Needs Triage, where the Product Ambassadors work to replicate and validate an issue then pass it along to the correct team. It seems like you've got that pretty well handled already, but if not, please set the Status back to the Needs Triage in The One Board and give me a ping. Cheers!

**Comment by fredrikekelund** [comment]
Ah, thanks for the clarification regarding triage statuses, @supernovia 🙏
