### ISSUE TITLE
Theme Showcase: Install button links to Calypso for AT sites

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#94435]
### Quick summary

When the page loads, the install theme button links for a second to the Calypso Theme install page for Atomic sites. After the page finishes loading, it points to WP-Admin (as it should).

### Steps to reproduce

- Go to an Atomic site
- Go to Theme Showcase (/themes)
- Refresh the page and immediately click on the "install theme" button in the upper-right corner of the page
- Notice that you are redirected to calypso for a second and then redirected again to WP-Admin
- Go back to the theme showcase and refresh the page
- Wait until the page finishes loading
- Notice that the button is now linking to WP-Admin

### What you expected to happen

The link should be to WP-Admin

### What actually happened

It links for a second to Calypso

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Atomic

**Comment by Robertght** [comment]
Triaged.


I couldn't replicate this on my end, but I can see this [PR](https://github.com/Automattic/wp-calypso/pull/94942) so I'm assuming things are being worked on/implemented?

**Comment by BogdanUngureanu** [comment]
@Robertght yes. The bug only happens if you refresh the page and immediately click on the button (in 1 or 2 seconds). If you wait for more than that, it points to WP-Admin Core (as it should).
