### ISSUE TITLE
Stepper: Not reaching checkout

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#94432]
### Details

Follow the video to reproduce the issue:

It should happen when selecting a custom domain and then premium plan

https://github.com/user-attachments/assets/1baf713f-3231-49cd-92fe-bdb4826ffd67

**Comment by m1r0** [comment]
I was able to reproduce it as well using the following steps:

* When logged out, go to https://wordpress.com/setup/onboarding/.
* Create an account.
* Pick a non-free domain and select the Premium plan.

I've noticed that the params are missing when you get redirected to `/setup/site-setup/goals?`. Usually, that link looks like this: `/setup/site-setup/goals?siteSlug=mydomain.com&siteId=123`. 🤔 

@alshakero could this be somehow related to https://github.com/Automattic/wp-calypso/pull/93865 / https://github.com/Automattic/wp-calypso/pull/93035?

**Comment by skim1220** [comment]
@renancarvalho , thanks for quick action on this! 🙌 

@travisw , I checked EN version (I still need to ask you how I can check non-EN version, because I kept being directed to EN version...) and I was able to reach the check out page. Could you check if this issue is resolved in non-EN version? 🙏

**Comment by renancarvalho** [comment]
> @renancarvalho , thanks for quick action on this! 🙌
> 
> @travisw , I checked EN version (I still need to ask you how I can check non-EN version, because I kept being directed to EN version...) and I was able to reach the check out page. Could you check if this issue is resolved in non-EN version? 🙏

Hi @skim1220,
To change your locale, you go to [wordpress.com/me](https://wordpress.com/me/account), there you can change your language.

This issue happens for newly created users, so to be able to reproduce you need to start with a newly created user, but you won't be able anymore since it is fixed, I truly hope 😄
