### ISSUE TITLE
Free setup flow — Back button not working 

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#94434]
### Quick summary

When creating a user from [wordpress.com](https://wordpress.com/setup/free/?ref=pricing-lp) on the home page, users are redirected to `freesetup` after adding a site name and description, users are redirected to `designSetup` `https://wordpress.com/setup/free/designSetup?siteSlug={siteSlug}`. 
In that step, the back button does not work. 

### Steps to reproduce

1 . Navigate incognito to wordpress.com 
2 . Go to plans and pricing
3 . Start free plan
4 . Land on freesetup step and add site name and description
5 . Land on designSetup
6 . Click on back button

### What you expected to happen

The back button should take me back to the previous step

### What actually happened

Nothing happened

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by m1r0** [comment]
I'm not able to reproduce this. It looks like the flow got updated. Can you confirm?
