### ISSUE TITLE
Your Stuff shows incorrect stuff for domain-only sites

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#94443]
### Quick summary

`/wp-admin` shows a "Your Stuff" dashboard widget which includes posts / comments from all sites that you are part of.

If you have a WordPress.com site as well as a domain registered at WordPress.com but pointed elsewhere, you can see the contents of the wordpress.com version of the domain pointed elsewhere. These contents are unlikely to be up to date, might just contain dummy content and will confuse users.

This was initially discussed on slack (p1725885621121479-slack-C029GN3KD) in response to `8679615-zd-a8c`

### Steps to reproduce

(Reconstructed, not confirmed)

 1. Create a wordpress.com website (we'll call this Site A)
 2. Register/transfer a domain to us but keep the name server elsewhere (we'll call this Site B)
 3. Create a WP website for that domain if one wasn't created during onboarding
    * One way of doing this is to use WordPress.com/professional-email, use the trial flow, search for the domain created earlier and opt to move it.
 4. Go to Site A's /wp-admin

As an A12 "Your Stuff" will be very noisy, you probably need to do it on a separate account.

### What you expected to happen

I didn't expect to see any posts for Site B, or if it points to a site hosted elsewhere, I expected to see posts from that site.

### What actually happened

I saw dummy content from Site B, e.g. "Hello World" or our default blog posts 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

The Your Stuff widget data comes from:
 1. `pressing_matters_widget` fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Scerffvat%2Qznggref.cuc%3Se%3Q6qq9pr43-og
 2. The ajax url to populate the widget is set to `/wp-admin/index-yourstuff.php` by this plugin: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qsvkrf.cuc%3Se%3Qnq0534o9%23130-og
 3. The code for that ajax url is here: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qnqzva%2Svaqrk%2Qlbhefghss.cuc%3Se%3Q085n132r-og

**Comment by arthur791004** [comment]
Since it's the feature only on wpcom, how about just removing this widget 🤔

**Comment by dsas** [comment]
Could do, I don't have a strong opinion on that. Maybe worth P2ing or adding to "extraneous UI"?

**Comment by candy02058912** [comment]
Related conversation: p1726653370319779/1726649423.271039-slack-CRWCHQGUB

**Comment by jartes** [comment]
I reviewed this report and lowered the priority from High to Normal, as this seems to be affecting only a particular group of users. 

Related conversation: p1727295080280389-slack-C01UW7SB411

**Comment by jartes** [comment]
Linking the opportunity post to remove this widget pbxlJb-6nI-p2

**Comment by davemart-in** [comment]
Closing this issue since we plan to remove this widget.
