### ISSUE TITLE
Reader: "Edit post" should NOT show on sites the user does not own

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#94452]
On the /discover page, in the ellipses menu, "Edit post" should not be an option on sites the user does not own.

![Image](https://github.com/user-attachments/assets/fedec605-adcd-40d2-a398-825651c10603)

**Comment by javierarce** [comment]
I haven't been able to reproduce this 🤔  

This is what I see instead:

![CleanShot 2024-09-12 at 15 29 08@2x](https://github.com/user-attachments/assets/e972b6ea-022f-4eb4-8037-8cf1a82c086f)
