### ISSUE TITLE
profile.php: The texts for the links are too long

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94466]
### Quick summary

The following texts are too long, and too specific.

"Your admin interface language is managed on WordPress.com Account settings"
"You can manage your profile on WordPress.com Profile settings (First / Last / Display Names, Website, and Biographical Info"
"Your WordPress.com email is managed on WordPress.com Account settings"
"You can change your profile picture on Gravatar"
"Your WordPress.com password is managed on WordPress.com Security settings"

![SCR-20240912-mbam](https://github.com/user-attachments/assets/a382cead-5dda-43a9-a8e8-47f1e2a1ed12)

### Steps to reproduce

1. Head to /wp-admin/profile.php

### What you expected to happen

Links with texts that are easily readable and concise.

### What actually happened

Links with texts that are too long.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by fushar** [comment]
Just a note that most of the above texts were inspired from `You can change your profile picture on Gravatar.` text which comes from Core 😅
